#+title: 超时空辉夜姬
#+setupfile: ./setup.setup

* 超时空辉夜姬

** 序章

    网译版 转自 百度超时空辉夜姬贴吧

    翻译：贴吧用户_53UAyP6

    ——话说从前……

    「彩叶！」

    一道近乎悲鸣的喊声，猛地刺入鼓膜。

    一回头，只见一群盔甲武士从那劈开悬崖的小路上，呐喊着蜂拥而出。

    其数不下百人，抑或两百。

    但无论哪边，都绝非小数目。

    ——不对。

    我全力掷出光剑。旋转的剑刃发出低吼，滑过天空，将那群盔甲武士一网打尽，尽数斩裂、化为纷飞的光粒。

    ——其实是超未来。

    「哇啊啊，不妙不妙！」

    不容喘息，耳机中又传来同伴的声音。

    OK。我当然发现了。自以为躲在竹林里吗？那从缝隙中泄露的跳跃特效，我可没看漏。

    在上面！我手腕一拧，将手柄猛地推向斜上方。

    ——不对不对，既非太古，亦非超未来。

    ——是与现在相差无几、只向前了一小步的世界。

    从手臂迸发的光丝捕捉到敌人，在夜空中将其化作绚烂的烟花。

    赢了。“将军”就交给队友吧。我在椅子上放松了盘坐的姿势，擦了擦下巴上的汗。

    睁开眼睛，才发现天色早已暗透，房间陷入一片漆黑。

    ——话说，有这么一位普普通通打着游戏的女高中生。

    玻璃窗上映出我的脸庞，瞳孔正幽幽地泛着橘色光芒，宛若外星人一般。

** 第一章

    「彩叶这准头，太神了！」

    「完全是职业水准！职业选手！」

    耶——。

    我对着队友的语音聊天，谦虚地回了一句。毕竟这是我玩了以年计的游戏，做到这地步是理所当然的——言语之外，多少带着这份自负。

    「……好啦好啦，都是托你们俩的福。」

    不过，被人称赞果然还是打心底里高兴。

    最后那一记投掷，连我自己都觉得犀利到令人发麻。喝水的手在颤抖，玻璃杯边缘咔咔地磕到门牙上，这可是秘密。

    『KASSEN』。

    这是近几年席卷游戏业界，以战国时代合战为蓝本的全潜入式动作游戏。带来宛如真实置身战场的三百六十度视野与音效的沉浸感，兼具高度的操作性与战略性，是一款无可挑剔的神作。玩家数量在国内外都遥遥领先，独占鳌头，也存在许多『KASSEN』的职业玩家。至于我的水平嘛，大概算中上吧。

    「喂喂，你真该以职业为目标啊。」

    「绝对能行的！」

    「啊——，不行啦——」

    ……没戏没戏。

    那条路我早就亲手斩断了。眼下我该做的事是——

    ——哔、哔、哔。

    「糟了，打工时间到了！对不起，我先下线了。学校见。」

    我像是被闹钟声弹起来似的站起身。以最快速度切断连接，取下那副正微微发热的隐形眼镜型设备——通称“智能隐形眼镜”。

    啊，今天是星期四。

    随着视野一同回归现实的，还有思绪。我每周打工五次的住宅区隐秘咖啡馆“BAMBOO cafe”，不知为何周四反而比周末更热闹。我不由自主地伸手去拿桌边摆着的能量饮料，但是——

    ——意面四份抵一饮！禁止浪费！

    被自己贴的纸条扇了一巴掌，手又缩了回来。对于靠打工和微薄生活费来支付学费和日常开销的苦学生——不，苦高中生来说，乱花钱是绝对禁止的。

    「……我出门了，八千代。」

    我对镇守在书架上的另一罐能量饮料——也就是八千代的神龛亚克力立牌——如此说道，便匆匆忙忙地离开了独居的公寓。

    连胜利后的美酒都无福享受的苦高中生，出行方式唯有步行。门到门十五分钟的路程，我十分钟就走完了。穿过BAMBOO cafe的自动门，

    「为什么汉堡是凉的！」

    「喂——，点单还没好吗？」

    「搞什么啊，这店怎么回事！」

    「对、对、对、对不起——！」

    ……哇，这边也在打合战啊。好了，上吧。

    「早上好！」

    我和这间不分昼夜的餐饮店打了声招呼，闪进员工间，三十秒换好衣服，投身战场。

    「店长，新做的汉堡在烤箱里，稍后麻烦您了！」

    「得救了，酒寄！」

    「林田小姐，这边我来收拾，能麻烦您去八号桌点单吗？」

    「拜托了酒寄，你真是神！」

    「对了，美绪她怎么了？」

    「酒寄前辈——！」

    「没什么怎么不怎么了！」

    大汗淋漓僵在原地的打工后辈美绪，和不知为何比美绪湿得更透的客人，同时回过头来。

    「我说要水，结果这位店员把整壶水都泼我身上了哎。」

    ……整壶？

    「对、对、对、对不起！我端水的时候不小心绊倒了……」

    啊，原来如此。好，这种时候。

    「我们一起道歉吧。实在是非常抱歉！」

    BAMBOO cafe今日也照常运营。

    「休息时间到——」

    好不容易熬过了暴风雨般的高峰时段，筋疲力尽地缩回员工间，正想点开八千代的直播切片，

    「前辈，刚才对不起！」

    先一步休息的美绪交接班站了起来。上个月刚来的东美绪干劲十足，但技术却跟不上她的热情，从让人忍俊不禁的可爱失误，到让人脸色发白的重大事件，每天都能花样百出地贡献各种错误。

    「真的，真——的非常对不起！我、我太笨手笨脚了。对不起对不起，让您来带我这个抽到‘下下签’的新人……」

    「哎呀呀，能照顾可爱的后辈，这不正是前辈风范的极致体现嘛。」

    「呜……神。您已经是神了。前辈您为什么不生气呢？难道说，您觉得我是个连生气都不值得的家伙吗？」

    怎么可能。那我成什么人了。

    「我觉得，劈头盖脸地挨骂，本来会的事情可能也做不好了。而且，美绪你记性很好啊，刚才团体客人的点单也全都处理好了，帮了大忙。」

    『真的这么想？不是只是在照顾我~~~~？』

    「不是不是。」

    「太好了！那，休息结束我也继续加油！」

    说着，美绪精神十足地从员工间跑了出去。紧接着就听到走廊上她活力十足地被什么东西绊倒的声音，不过，这里就选择相信美绪吧。

    「……呼。」

    叹了口气，将体重靠在折叠椅的椅背上。

    暂时让视线失焦，漫无目的地看着墙上贴的“勤洗手！”海报。视线随之滑向旁边，“酒类贩售注意事项”、“制服正确穿着方式”，

    「已经七月了啊……」

    最后，目光停在了日历上。

    「七……十四、二十……三？」

    一看日历，就会下意识地数离发薪日还有几天。进而推算出每天能花多少钱——这是来东京一年后养成的可悲习性。

    行，这个月看来也能熬过去。其实喝一瓶能量饮料也没关系吧……不，不行。女高中生在东京独居，发生什么都不奇怪。为了以防万一，钱再怎么勉强也得存起来。

    ——今日的一百元，是明天的一千元。小心被明天的自己怨恨。

    虽然不甘心，但母亲说的话是真的。不仅仅关于钱。母亲说的话总是对的。正确到冷酷，合理到无情，有让人不忍直视的丰富经验作支撑。

    所以，我无法忍受，冲出了家门。

    初中三年级的冬天，在不知第几次冲突后，我下定决心，实施了早已计划好的上京。以学费生活费全部自理为条件，近乎离家出走般地离开了故乡。我想，我或许获得了自由。但是，

    ——直到现在，我也觉得彩叶马上就会哭着回来，因为她还是个娇气包。

    母亲的话，无论相隔多远，都会不时传入耳中。清晰得仿佛就站在身旁。

    「……重要的——旋律——流淌着哦——在你的心里——」

    我无意识地哼起了八千代的歌。八千代最喜欢的一首歌。我从包的侧袋里扯出耳机，跳进歌曲的后半部分。被温柔的歌声抚慰着，终于稍微放松了一点。

    穿透电子音，大厅那边又传来美绪道歉的声音。休息时间结束，战斗又将开始了吧。

    ※

    「啊，彩叶来了。」

    「早——」

    第二天早上，在往常上学路上的老地方与芦花和真实汇合。自昨天游戏后就没见了。她们虚拟空间的化身已经够精心打扮、够时尚了，但现实中的两人更是魅力倍增。明明在背阴处等着，却好像只有那里洒下了别样的光芒。

    「昨天打工赶上了吗？」

    「黑眼圈好重哦。好好睡了吗？」

    「睡啦——」

    「彩叶的‘睡了’，反正也就三小时左右吧？」

    眉头皱成八字的芦花立刻吐槽道。本想省略细节不让她们担心，果然逃不过芦花的法眼。

    「那不就是通宵嘛——。光听着就困了——」

    真实像是真的困了，慵懒地打了个哈欠。一直盯着看的话，这边也会被睡魔侵袭，得注意。

    「你干嘛了？打工？」

    「不是，预习和复习。马上要期末考试了。」

    「彩叶你保持现在这样也能轻松拿第一吧？」

    「这种掉以轻心可要不得。这个世界可是只要你露出破绽，随时都可能被人从背后放冷枪的。」

    糟了，不小心说出了“妈妈语录”。

    「刚才那句，是‘妈妈语录’吧？」

    是，您说得对。我摆出一副“被你看穿了啦~”的无奈表情，真实便一脸得意地把手搭在我肩上，点了点头。什么嘛。

    「彩叶你无时无刻不是‘KASSEN’状态呢。」

    正如芦花所说，我的合战即便关闭了游戏、即便从BAMBOO cafe下班，也远未结束。不如说，从这里才开始是正戏。必须拼上性命，死守住从高一下学期开始保持至今的年级第一的宝座。不，不只是考试成绩。

    「啊，是酒寄同学。早——」

    「快看，酒寄前辈！早上好！」

    「酒寄同学，早上好。上次多谢你帮忙了。」

    啊，大家早上好——。

    「酒寄同学，今天也好漂亮。」

    「糟了，我跟酒寄前辈打招呼了！」

    「真好呀，你小子。」

    品行端正、成绩优秀、文武双全。唯有彻底贯彻这个无懈可击的完美女高中生形象，我才能向前看。

    ——勉强是懒鬼的借口。我只说自己做得到的事。

    唯有做到这个地步，我才能勉强捕捉到那遥在我前方的母亲的背影。

    当然，无论我贯彻到何种地步，母亲也绝不会表扬我。是从什么时候开始的呢？母亲不再表扬我了。

    那好像是——

    嗯，大概是——

    记得是——

    「那么，这里明白吗？今天是六日……酒寄同学。」

    「在！」

    被老师突然点名，急速下坠的意识猛地拉了回来。

    糟糕，这是讲到哪了？刚说完就大意了。明明知道体育课后的第六节古文课是与睡魔之战。

    即便如此——

    「这里的‘なりぬ’，是动词‘なる’的连用形与表示完了的助动词‘ぬ’的组合。」

    「哦——，厉害！」

    「不愧是酒寄同学。」

    「太厉害了，根本听不懂在说什么——」

    完美女高中生，酒寄彩叶，是不会搞砸的。

    好险——。

    ※

    「那我们先走啦——」

    「对不起对不起，前辈！今天也尽犯傻。真的真的对不起！」

    「没关系啦。美绪你的失误越来越少了。那么，辛苦了。」

    今天也是今天这副样子，从订单如子弹横飞的打工地点侥幸生还。如前所述，BAMBOO cafe不知为何周四最忙，但周五也照例人多……今天，嗯，是有点累了。但是……。

    「嘿嘿嘿……三连休终于来啦。超久违地能一天睡够六小时了。」

    平时总是大步流星快速穿过的道路，今天只迈着平时一半的步幅，步履沉重地走着。抬头望去，浮在大楼上方的满月，如同通往另一个世界的窥视孔，将夜空剪出一个圆洞。

    最近，总觉得仰望月亮的次数变多了。在老家时明明根本不在意。这是怎样的心理作用呢？

    真美啊……

    总觉得又要听到母亲的声音了，慌忙把耳机塞进耳朵。我需要音乐。曲子当然是八千代的——选哪首呢，就『Remember』吧。

    耳熟的前奏流了进来。心轻轻地飘了起来。绷紧的弦被一根根解开。这样，三分五十三秒的幸福就有了保证。无论听多少次都不会褪色、我的推——八千代的出道曲。

    AI主播，八千代。突然出现的谜之歌姬，字面意义上彻底颠覆了我的世界。她是虚拟空间“月读”的管理员，同时担任新手引导及各处的导航，并作为月读的招牌定期进行直播的艺人，年龄八千岁。

    虽然角色设定相当离谱，但其真实身份无人知晓。虽自称AI，但制作者、设计师、管理员一概不明。每周都会冒出各种传闻：多家企业合作说、海外国家项目说、乃至电子幽灵说等等，但这些猜测如同泡沫般毫无根据、层出不穷的事实本身，就讽刺地否定了所有说法的可信度。

    对我来说，无论那是企业、国家还是幽灵，我都只感谢他们让八千代这位尊贵的推，诞生在了与我相同的时代。毫不夸张地说，我是被八千代拯救的。当我被逼入绝境，前后左右都无法前进时，是八千代用歌声给了我翅膀，告诉我“只要飞起来就好了”。正是此刻在听的这首歌。

    『……重要的旋律——流淌着哦——在你的心里——』

    我依靠着八千强度过每一天。看八千代的直播就会笑，听她的歌就能平静下来，也曾在聊天咨询应用里，无数次倾吐过无法对任何人言说的烦恼。有直播的日子就看直播，没有的日子就看过去的录播或切片。即使食欲不振的日子，看着八千代的直播也能一点点吃下东西。演唱会即使抢不到票，也会尽量找个好位置将她的身影烙印在眼底，用打心底里开心的八千代，覆盖掉浮现在眼皮背后的糟糕记忆，然后入睡。打工或上学迈不开脚步时，只要听着她的歌就能自然前行。会觉得，活着也挺好。八千代从不责备我。不催促我。但是，总是在我身边。或许比“人”还要温柔。如果没有八千代，我该如何活下去才好呢？我知道自己必须活下去。但是——

    泪水毫无预兆地涌了上来。果然，今天的我好像有点累了。抬头望见的月亮轮廓模糊、扭曲，

    「——」

    嗯，那是什么？有什么东西横越了月亮。只是一瞬间，非常微小的——

    「流星！」

    「是流星。」

    ……诶？

    我像是被周围的声音弹到似的，双手合十。

    ——求神拜佛的家伙都是蠢货。

    虽然又听到了母亲的声音，但还是忍不住祈愿。神啊，佛啊，求求您了。

    「钱、钱……」

    真的假的，我。说什么不好，许了个多么不像女高中生的愿望。真是无聊透顶的家伙。

    看来我果然是累了。对自己露出自嘲的笑容，我又拖沓地踏上归途。直到这时，才注意到自己前进的方向，和刚才流星坠落的方向恰好一致。

    「……哈？」

    是在终于回到公寓，发现旁边那根电线杆正闪烁着七彩光芒的时候。说到七色……

    「电竞风……电线杆……？」

    电竞风电线杆。听起来莫名其妙。但，只能这么形容了。

    鞋底蹭着柏油路面，吱吱地向后滑去。

    等等等等，这什么啊。什么现象？怎么看都是一根普通的电线杆在发出电竞色彩的光。去的时候没这回事吧。姑且摸了摸自己的眼皮。原来如此原来如此，没戴智能隐形眼镜对吧？那也就是说……

    「呵，什么啊，是幻觉吧。」

    正要离开，电线杆吐出了烟雾。简直像是在叫住我一样。

    ……饶了我吧。

    被冲击暂时忘却的疲劳加倍袭来。这可麻烦了。如果这是现实的话，事情就非常棘手了。

    电线杆是靠什么原理发光啦、烟雾是从哪里冒出来的啦、流星是实现谁的愿望才会变成这样啦，虽然疑问很多，但最大的疑问是，

    「为什么，在这里？」

    ——她想。

    老实说，电线杆是发光、跳舞还是唱歌都无所谓。世上也有讨喜的电线杆嘛，就这样算了也无妨。

    如果不是这根电线杆的话。如果不是紧挨着我住的公寓的、这根电线杆的话。

    散发着七彩光芒、会看人并吐出烟雾的电线杆。我可没有豪胆到能将这种超级异常现象置之身侧，还能安稳度过三连休。

    可是，虽然希望现在就立刻解决，但悲哀的是，月租三万八千日元、无需担保人的公寓，可没有打个电话就能赶来的房东。话虽如此，周围也没有会因“发生什么事了”而跑出来的邻居。也就是说，如果我看这根发光电线杆不顺眼，就只能自己处理的状况。

    ……可恶，顾不得那么多了。

    下定决心，向前踏出一步。又一步，再一步。

    仿佛在诱惑我一般，七彩光芒淡淡闪烁。电线杆为什么会发光？这点暂且不去想。实际上它发光了，所以就是会发光，这就够了。所以，即使电线杆中间突然出现一道像门一样的缝隙，也不会问为什么。而且，即使那扇门上长出了竹子造型的门把手，也不会问什么时候。而且，那扇门如同从内侧被推动般，徐徐地、徐徐地对开——

    「不，不准开！」

    我瞬间用手将门猛地推回去关上了。

    不，打开可不行。我可没听说过它会打开。发光和打开可是两码事。

    但是——

    「咕哦，呃，要用蛮力吗？」

    门被推了回来。力气好大！没错。完美女高中生酒寄彩叶，其实唯独没锻炼过肌肉。无计可施，门“咿——”地被打开了，里面是……婴儿床？

    蓬松的靠垫、粉色的摇铃、骨碌碌转动的小小旋转木马玩具，以及这些婴儿用品的主人——

    「呼诶……呼诶……」

    「啊，婴儿？」

    ——话说从前……不对。

    ——是与现在相差无几、只向前了一小步的世界。

    ——有正在玩游戏的普通女高中生。

    ——名为酒寄彩叶。

    ——请叫她彩叶♪

    ——彩叶回到家一看，哎呀，竟有一根闪着七色光芒的电竞风电线杆矗立一旁。

    ——心生疑惑，上前察看，只见电线杆内光芒流转。

    ——于是彩叶这样说道。

    「嗯？？？？？」

** 第二章

    “哦……”

    这是什么？到底发生了什么？

    头脑跟不上现实。冷静下来，冷静下来，从头开始整理状况。这种异常事态是从哪里开始的？

    首先，打工回来的路上看了流星。到这里还好。然后，电线杆闪着光，电线杆吐着烟，电线杆打开，里面出现了一个婴儿。

    太离谱了。这是实现了多少人的愿望才会变成这样啊。

    「哼，哼！」

    而且这个婴儿还是活的。不是人偶或CG，而是活生生、会呼吸的，圆圆的眼睛一直注视着我。仿佛在诉说着什么。

    「……是你打开的吧？」

    才没有打开。是它自己开的吧。

    「……可是，你摸过了吧？」

    所以呢？摸了又怎么样？

    「……你其实很在意吧？」

    这倒是实话……但是……。

    「抱歉！但我自己已经忙不过来了，先告辞了！」

    感觉像被揪住后颈般狼狈，我转身就要离开。

    ——不管了，爱怎样怎样吧！呜。

    ——哗啦！

    ——嗷呜。

    ——吱——！

    正打算这么做时，醉汉的叫嚷声、玻璃碎裂声、野狗的嚎叫声和汽车刺耳的刹车声接连不断地传来。

    治安突然变差了。这个城市是这样的吗？不过，把婴儿丢在这里确实可能有危险。至少该报警吧。

    「这要怎么抱啊？」

    我战战兢兢地把婴儿从电线杆里抱了出来。

    好轻。比起柔软或温暖的触感，我更先惊讶于身体的轻盈。简直就像抱着一条随便卷起来的毛巾一样毫无实感。似乎只要稍微用点力，就会毫无抵抗地瘫软下去。

    不行。本能地确信了。不能把这么弱小的生物丢在那里。那感觉不对，不只是法律或伦理不允许，而是作为一个人，从心底里就觉得不能这样做。

    但是，这台电竞风电线杆似乎和人类的想法根本不同，它只说了句“那就交给你咯”，便熄灭了灯光，门把手和门也消失了，转眼间变回了原来那个沉默寡言的普通电线杆。

    不是吧。等、等等。

    「不好意思！您忘东西了！」

    我边说边敲了敲电线杆，但对方只是硬邦邦的，毫无反应。

    被摆了一道。深夜的路上，我抱着婴儿，呆立在电线杆前。

    「这种状况，看起来不就像我绑架了她吗？」

    感觉怀里的婴儿猛地一沉。低头看去，她正努力抬起柔软的脸颊，露出天真无邪的笑容。

    「咿呀♡」

    「不行不行不行不行不行！」

    就算这样也不行。我绝对做不到。还是先放在这里吧……不，不行。丢在路上不可能。那么，放自动售货机上……也太危险了。到底该怎么安置这孩子呢？

    仿佛看穿了我的犹豫。

    「呜哇啊啊啊啊啊啊啊啊啊啊！」

    婴儿拔出了传家宝刀。深更半夜的住宅区响起了毫不留情的哭声。

    「啊，真是的！」

    我不想被人看见，抱着哭喊的婴儿跑上了公寓楼梯。幸运的是，谁也没遇到就到了房间，锁上门，总算松了口气。

    不对！为什么我给抱回来了。这样一来绑架不就完全成立了吗？糟了，显然是累得脑子不转了。

    「呜哇哇哇哇哇哇！」

    在这期间，小猛兽并未沉默。她用自己被容许的唯一可能方式，不断地倾诉着满身的不满，

    ——咚！

    招来了隔壁对墙壁的一击。

    「墙、敲墙……第一次被人这样敲。」

    挺受打击的。不，也难怪。这个时间点。

    「呜哇啊啊啊」

    「啊，不怕不怕。看，略略略～～」

    完美女高中生酒寄彩叶，除了肌肉锻炼以外还有一件事做不到。那就是让婴儿停止哭泣。我虽然学着样子拼命哄她。

    「呜哇啊啊啊啊啊！」——咚、咚、咚！

    哭声和隔壁的敲墙声都停不下来。怎么办，我抱着死马当活马医的心态解锁了智能手机的屏幕。

    《让宝宝停止哭泣的方法》，世上妈妈们的烦恼都一样，搜出来惊人多的条目。

    「嗯……『抱着』已经做了，『竖抱』也做了，『左右摇晃』也做了，『抱着走动』也做了，剩下的……」

    固定节目是摇篮曲啊。好，想起来，母亲唱给哭泣的我听的那首摇篮曲。摇篮曲是——

    ——别哭。哭只是在偷懒。

    ——如果真的悲伤，就别光顾着哭，想想怎么让同样的事别再发生。

    不记得了。只有说教。就在我抱头的瞬间，

    「……啊。」

    映入眼帘的是书桌正前方镇坐的八千代神龛亚克力台灯。一瞬间，我感觉头脑中的迷雾散开了。

    『重要的旋律——流淌着——在你的心里——』

    《Remember》。第一段还没唱完，婴儿就开始发出熟睡的呼吸声了。

    「八千代的力量，太厉害了。」

    我小心翼翼地把婴儿放在被褥上。屏住呼吸，把手一毫米一毫米地抽出来。好，全抽出来了。等了十秒，还是没有要醒来的迹象。

    「……太好了。」

    成功了。身体软绵绵地松懈下来。这样隔壁的敲墙声也会停止吧。总算松了口气。但是，这孩子怎么办呢？还是该报警吧。

    有生以来第一次在智能手机上点击110。摸着通话图标，一边听着拨号音，一边在脑海里整理着报警的说辞。这里必须格外小心。只要说错一句话，就可能被认为是我绑架的。

    “发生事件了”……不、不行吧？“从七彩发光的电线杆里，出来个孩子”……不行，太离谱了，现实一点。“有个婴儿在哭，总之先带回家了”……会被抓的会被抓的。已经搞不清楚状况了。我自己都不明白的事情要怎么解释才好？

    「这里是立川警署，是案件还是事故？」

    「啊，没事！现在已经没事了！对不起，谢谢！」

    我给警察打了个神秘的电话，只说了句“没事”就挂断了。

    ……对不起，警察先生。已经不行了。我累了。

    今天本来好不容易能睡够六小时的。

    ·

    ·

    ·

    远处传来山斑鸠的叫声。送报纸的摩托车追着声音开了过去。微微拉开窗帘，初生的朝阳活力满满地照了进来。

    ……睡了呢，六小时。

    不知不觉好像睡着了。昨天发生的事到底是怎么回事？

    「不是……幻觉吧？」

    证据就是，从电线杆里出生的婴儿，正睡在我旁边，发出安稳的呼吸声。

    看样子晚上没有哭闹。人们常说睡着的孩子是天使。明明昨天还那么让人手忙脚乱的小宝宝，看到她沐浴在朝阳下、绒毛闪闪发亮的脸颊，就忍不住想摸一摸。

    话说，有这么大吗？真奇怪。昨天明明是单手就能轻松拿起来的尺寸。一直戴着的手环好像也没这么大。

    「啊！湿了！真的假的！」

    我想估量一下大小，手撑在被子上，掌心传来一阵不快的潮气。

    被尿湿了？唉，是婴儿嘛，没办法。虽然没有那种义务，但尿布还是给你换吧。不，那得连衣服也一起换了才行。还有包裹身体的东西。还有擦身体的、奶粉、奶瓶和婴儿背带吧？还有……。

    「咦，要的太多了吧？」

    掰着手指数着需要的东西，手指马上就不够用了。

    等着开店时间冲进去的，是以“育儿的伙伴”为宣传语而为人熟知的儿童用品专卖店西竹屋。我在网上查了一下，这家店好像所有婴儿用品都齐全。当然，前提是要付钱。

    「不行不行不行不行！」

    我在过道上不由得尖叫起来。

    尿布好贵！而且种类好多。便宜的和贵的，让我选的话……当然想选质量好的啊。童装对我来说一点也不便宜。奶粉也有便宜有贵，想买奶瓶还得搭配消毒药这种意料之外的必需品。把这些七七八八的东西拿到收银台，

    「合计一万三千二百四十三日元。」

    你哪里是自己人了？可恶，拼了命攒下的钱……。

    「我为什么要做这种事？」

    抱着买来的婴儿用品和婴儿本人，吭哧吭哧地爬着坡道。

    「呜啊！」

    如果途中宝宝闹情绪了，就给她做鬼脸哄她，

    「呜诶！」

    如果又开始闹别扭，就看时间喂奶。

    「呜呜！」

    如果还不依不饶，我就给她唱摇篮曲。

    「嘿嘿嘿。」

    婴儿经常哭，但更经常笑。看过一次笑脸，就想看下一次笑脸。常听说生了孩子以后生活就以孩子为中心了，而这三连休简直就是为了逗孩子笑而度过的。

    一秒钟也没学习。

    「……咦，我在干什么啊？」

    我在房间里抱着婴儿，打了个寒颤。

    等等等等，为什么我这么专注于育儿呢？不对吧，现在不是做这种事的时候吧。这三连休本来应该全部用来学习的。

    「呜诶！」

    「要喝奶是吧。知道了，请稍等一下。」

    现在可不是光听闹别扭的声音就能知道对方想要什么的时候啊。

    不行，还是报警吧。被怀疑也无所谓了。再不和这孩子分开，时间会比任何游戏都更容易消融掉。

    「呜呜！」

    「吃饱了吗？那我们去休息吧，大小姐。」

    总之，今天已经很晚了，明天再说吧。明天一早就去派出所。这样育儿游戏就结束了。我这样发誓着，又唱起了八千代的歌来代替摇篮曲。

    睡脸果然像天使。

    那天晚上，我做了一个梦。

    我成为了公寓天花板的一部分，俯瞰着自己的房间。四叠半房间的正中央是我爱用的矮脚桌和平板电脑。屏幕上发出淡淡的光，朦朦胧胧地照亮漆黑的房间。

    「呀，呀，呀！」

    伴随着有些痒痒的笑声，平板电脑的画面不断切换。报告巨大陨石接近可能性的新闻，赌上生命的爱情电影，爆满的八千代演唱会直播，动漫，体育转播，我和朋友开玩笑拍的视频。

    「呀，呀，呀！」

    操作着平板电脑的是婴儿。她那贪婪地寻求信息的眼睛，明明没戴着智能隐形眼镜，却妖异地闪着光。

    冷不防地，月光从窗户射了进来。沐浴在月光下的婴儿头发无声地拉长。那简直就像进行光合作用的植物为了寻求更多的光而伸展叶子一样。然后，我又沉入了梦乡……。

    ·

    ·

    ·

    「喂——喂——」

    被婴儿的哼唧声吵醒了。

    「肚子饿了。」

    「……知道了。」

    我知道啦，肚子饿了是吧。

    揉着惺忪的睡眼站起来。房间里还是一片漆黑。

    「牛奶——」

    「请稍等一下下。」

    想要牛奶是吧，明白明白。

    这三天来，我的感知力被锻炼到了极限，光是听到婴儿的哼唧声，就能像对方用清晰语言说出来一样理解其需求……等等，咦？

    「呜哇！」

    「噢哦！」

    我大叫着回头，少女也发出同样的惨叫跳开了。

    没错，是少女。站在那里的是个少女。

    漆黑的房间里，突然出现的少女惊讶地睁大眼睛看着这边。

    「吓我一跳……」

    不，吓到的是我。

    年龄大约十岁。宛如两颗流星飞来的美丽双眸，盛满惊讶，烂漫地闪烁着光芒。及腰的亮丽秀发，即使在暗处也清晰可见的白皙肌肤，形状优美的嘴唇，单看外表的话是个美少女。

    ……你是谁啊？

    不，不用回答。我知道。你……是你吧。这三天一直有接触，所以我知道。光是听哼唧声就能心灵相通到这种程度，所以我明白。

    我就觉得奇怪嘛。从电线杆里出生也好，一夜之间蹭蹭长大也好，两眼放光地搜集信息也好……不，那个是梦来着？

    总之，够了。这下确定了。这家伙绝对不是人类。既然明白了这一点，

    「请您回去吧！」

    我把刚买的西竹屋商品迅速塞进纸箱，郑重地递还给她。

    「……」

    但是，神秘的美少女却不可思议地、滴溜溜地打量着那个纸箱，

    「……这是怎么回事～～～？」

    「不，这话该我说吧。话说回来，你怎么一下子就变大了？好可怕！」

    「嗯——。嘛，毕竟现在什么都提速了嘛。」

    这什么采访似的语气啊。说起来，为什么你会说话？你刚才明明还是个婴儿。果然不行。不能再交流下去了。等不到明天了。

    「来路不明的东西，恕不接待！」

    我抓住少女的手臂，决定强行请她离开。

    「不要——！」

    却纹丝不动。少女用小小的身体拼命抵抗着。

    「你给我动一下。」

    「就——不——要——！」

    没想到这么快又有机会锻炼肌肉了。不过，可别小看我。电线杆也就算了，对手是这么小的女孩子的话，用拔河的诀窍全力拉的话——

    「好痛好痛好痛。」

    「啊，对不起。」

    「啊啊啊啊啊啊！」

    啊，更对不起了。她喊疼，我不由得松开了手，反作用力让少女骨碌碌地在地板上滚了起来，

    ——咚！

    脑袋撞在了铝制窗框上。

    「没事吧！？」

    「头好痛～～。手也好痛～～。谁来帮帮我呀～～」

    “帮帮我”。听到这句话，一瞬间我不知如何是好。

    ——帮帮我？能这么轻松说出这种话的居然是我女儿，真让人吃惊。不是说这世上能依靠的只有自己吗？已经忘了吗？那样的话——

    然后开始了长达四小时的说教……。不不，现在不是回忆的时候。必须让她停止吵闹。

    「喂，别闹了。半夜别大声说话，又要被隔壁敲墙了。」

    但是，在我房间里响起的并非来自隔壁的敲墙声，

    咕～～。

    而是眼前少女肚子里发出的轰鸣。

    说起来，还没给她喂夜间的奶。顺便一提，我也忘了吃晚饭，

    咕～～。

    像是被牵引似的，第二声腹鸣，这次从我体内响起。

    年轻少女们此起彼伏的腹鸣二重奏可不多见。一阵尴尬的沉默在两人之间流淌，

    「帮帮我～～？」

    少女湿润双眸，谄媚地歪着头。

    这、这是多么轻蔑的态度啊。她看起来真的什么都没在想，在这家伙面前，我觉得一切都很愚蠢。我全身无力地叹了口气，大到仿佛能把大海吹飞，在反作用力下站了起来。唉——……

    ——站起来的人全包。不想干的话，就坐到对方站起来为止。

    ※

    「五百九十四日元……五份……话说，现在两点了，凌晨两点。」

    深夜穿着睡衣跑去便利店。买回来的是考虑到孩子爱吃的首选——蛋包饭。当然，不可能买两份，我的那份是把从打工处带回来的塔可饭解冻了。隔着矮脚桌，与神秘少女开始了太迟的晚餐。

    「我开动了。」

    双手合十，大口吃着塔可饭。嗯，BAMBOO cafe的员工餐一如既往地稳定。味道自不必说，免费这一点就是最好的调味料。

    另一方面，神秘的少女只是目不转睛地盯着我看。我无视她继续吃着，少女慢悠悠地用左手握住勺子戳向蛋包饭。与其说是左撇子，看起来更像是把我的动作镜像复制了一遍。然后粗鲁地把蛋包饭舀起送入口中，

    ——！

    大大的眼睛里仿佛散落了星星。

    「好厉害！这是什么？」

    从那里开始就是不停地吃吃吃。眼睛瞪得圆圆的，大口大口地扒着饭。兴奋得就像从来没吃过饭一样。

    「呃，蛋包饭……吧。」

    「蛋包饭！我最爱了！」

    ……高兴得不得了。虽然对钱包是沉重打击，但感觉稍微得到了一点回报。真的只有一点点。

    「这个黄色的什么？红色的呢？里面小小的软软的东西呢？」

    「鸡蛋、番茄酱、鸡肉……」

    我心不在焉地回应着接连不断、充满弹性的提问，习惯性地伸手去拿矮桌上的平板电脑，唤醒屏幕。正好，八千代的直播开始了。

    「年龄差距太大的话，周围的人会说三道四，也会有所顾忌吧～。八千代倒是很喜欢电影里偶尔出现的那种忘年交感觉的朋友呢～☆」

    听着八千代流畅的声音，感觉突然回到了日常生活。

    即使眼前有个正在大吃蛋包饭的神秘女孩。

    这孩子是怎么回事啊。到底是谁？不，我知道是谁，所以要问的话……。

    「你，是从哪里来的？」

    被问到的少女，猛地停下了手，

    「嗯」

    那当然是那里啦，她脸上带着“这不是明摆着吗”的表情，指向窗外能看到的满月。

    月……月亮啊，原来如此。

    没想到会得到回答。明明之前还是个婴儿，却有来这里之前的记忆吗？虽然明白，但越来越不像人类了。

    「那？宇宙人来干什么？侵略？」

    「唔——嗯，不太记得了呢～～。总之，每天超～～无聊的～～。好像是想逃到好玩的地方去～～，大概吧。」

    你的说明太轻巧了。而且，我还是不知道目的。

    「别逃啊～」

    「诶～～，为什么～～？」

    为·什·么·啊～？

    「逃跑很容易，但之后要重新开始可是很辛苦的哦？你有心理准备吗？」

    「心理准备～？不想做就不做，想做就做！」

    无法沟通。你到底思考到什么程度才说的？还是说一开始就没思考过？

    「而且日子无聊也是理所当然的。」

    「诶！不要！彩叶你真的觉得那样就行了吗！？」

    「无所谓好还是坏……等等你怎么知道我的名字！？」

    「呵呵呵，想知道吗～？」

    啊，算了。总觉得她得意洋洋的样子让人火大，换个话题吧。

    「那个，顺便问一下，对这个有印象吗？」

    我关掉八千代的视频，在平板电脑上显示出《竹取物语》的绘本。

    「这是什么？」

    「《竹取物语》。从月亮来的公主从竹子里出来，被老翁捡到养大，还被逼婚什么的……嘛，就是个挺混乱的故事。」

    粗略地说明完后，少女不明所以地歪着头。

    「结婚？」

    好可爱! …个头啊！绝对不可爱！！有那么一瞬间她看起来真的纯真无垢，差点被骗，但我总算成功保持了理智。

    「竹子？」

    「不过，你跑出来的不是竹子，是电线杆。」

    虽然连我自己都觉得荒唐无稽，但似乎有共同点。发光的竹子，婴儿，茁壮成长的女孩，还有月亮。

    「难道……你其实是辉夜姬？」

    「看起来好好吃……」

    你啊！我在说你的事呢，别比我先腻了啊。少女瞬间吃完了蛋包饭，她看的不是显示《竹取物语》的平板电脑，而是我手边的塔可饭。这家伙还想吃吗？

    「呜呜呜」

    然后迅速地开始假哭。我放弃了，把塔可饭的盘子推过去，少女干脆地收起哭脸，拿起了勺子。

    「我开动啦。对了，叫什么来着？」

    「你啊！」

    「啊，这样啊这样啊。也就是说，彩叶就是这位老爷爷咯？」

    揍飞你哦。直接飞回月球。

    「你还能看到我八十年后的样子吗？——当然不是啊！」

    「唔哈哈哈～」

    这次想用笑来蒙混过去吗？净学些不好的手法。

    「哇，这边的蛋包饭也很好吃！」

    「那边是塔可饭！」

    「蛋包饭，好好吃！」

    所以说你听我说啊。我知道了，这绝对不是什么辉夜姬。只是个吃货宇宙人。

    「怎么才能吃得更多！？」

    「啊，我觉得买或者自己做饭就行……」

    「做饭～～？我想试试啊啊啊啊！」

    哇，好耀眼……。被那过于兴奋的氛围所压倒。

    「那，故事后来怎么样了？」

    什么？啊，《竹取物语》的故事啊。这急转弯转回正题可真行。

    「老翁捡来养大，又被逼婚，乱糟糟的，后来怎么样了？」

    你听到了啊？明明看起来已经腻了，但在获取信息方面却和食欲一样贪婪。一瞬间，我想起了在梦中见过的眼睛发光的婴儿。

    「彩叶？」

    仔细看和婴儿时期的脸一模一样呢……不对不对。

    「啊，嗯。嗯……月亮派人来接她了——老翁们为了不交出她而战斗，但徒劳无功，公主被披上羽衣，忘记了地球上的一切。然后，回去了。」

    「哦——」

    「……」

    「然后呢？」

    「没了。结束了。可喜可贺，可喜可贺。」

    「诶，回到月亮就结束了？什么啊，这哪里可喜可贺了？超坏结局！辉夜姬绝对很不幸吧！而且还说得好像是个好故事的样子，更不可原谅！」

    也不知道有什么事让他那么生气，他一个劲儿地说。不过说起来，也不知道这是否出自公主的本意。但是——

    「这个故事，就是这么讲的。」

    我实在应付不来，就把空盘子收拾起来拿到水槽。本想表达“谈话到此结束”的意思，

    「坏结局，讨厌——」

    她还在说。

    「快乐的结局，才——好——！」

    我不知道。

    「坏结局，讨～～厌～♪ 快乐的结局，才～～好～♪」

    为什么要唱起歌来啊。真拿你没办法。

    我背靠着水槽边缘回过头。

    「那又有什么用呢？就算再怎么闹、再怎么唱，既定的事实也不会改变。」

    然后，俯视着撒娇的少女断言道。

    「只能接受，并做好心理准备。」

    或者，那句话也可能是对自己说的。说出口的话，沉入喉底，在我心中留下沉重的分量。

    「……」

    少女盯着我的脸看。我并没有那么强烈地说的意思，只是她沉默着僵住不动，两秒、三秒、四秒……。在想什么呢？然后，差不多沉默开始变得难受的时候，

    「好，决定了！」

    这次换少女决然地说道。

    「要自己创造快乐的结局！」

    就像魔法少女或者小学生偶像一样，飒爽地摆出姿势。在四叠半的狭窄房间里。

    「而且要把彩叶也带到快乐结局，一起！」

    理所当然地被卷了进去。《快乐结局》……感觉脚尖被小石子“咚”地碰了一下。

    ——中听的话都是毒药。得先狠狠怼回去才行。

    「不需要快乐结局，普通的结局就可以了。」

    结局已经决定了。接下来只要朝着那个方向积累下去就行了。

    「骗人骗人！怎么可能嘛！」

    外星人在说什么，我听不见。我本来就够忙碌的生活，不能再掀起更多波澜了。

    三连休真的眨眼就结束了。而且，口腔溃疡还增多了。

    话说，让我睡吧……。

    ·

    ·

    ·

    远处传来山斑鸠的叫声。送报纸的摩托车追着它们开了过去。微微拉开窗帘，初生的朝阳……。

    「嗯？同样的场景是第二次了。」

    我跳起来查看四周。不在。壁橱里、卫浴间、阳台再到壁橱……那家伙不在。房间里只有早晨的空气颗粒和夜晚的残余。

    出去了吗？不，也许一切都是过度劳累造成的梦。

    「太好了！」

    使出浑身解数摆出胜利姿势。像是瞅准了这个时机，水槽下面的抽屉被打开了。

    「在这里哟～！」

    果然。那里，三角坐姿塞着一个比昨晚更大的少女。

    「呐呐，彩叶一直在看的这个人是谁？喜欢的人？」

    我比平时更快地吃完饭，比平时更迅速地整好装束，比平时早得多地做好上学准备后，正慌慌张张地挥动平底锅时，外星人优哉游哉地摆弄着平板电脑问道。就算对方是地球外生命体，被问到八千代的事也很开心。我尽量不让声音过于雀跃地回答。

    「月见八千代。AI 。是我推。有分身能唱歌跳舞，设定是八千岁——」

    「诶——，AI？是机器人吗？诶——，好有趣～？」

    不知为何，外星人更加兴奋了，把当作椅子的矮脚桌弄得吱呀作响。话说别坐在桌子上啊。

    算了，算了。做完最后一件工作的我，关了火，洗了手，把书包背在肩上，穿上鞋子，

    「那我走了。」

    留下这句话，

    「诶——！不要不要不要——！」

    外星人以惊人的速度冲了过来。话说，你又长大了。已经长得几乎和我差不多大了。

    「要在一起！」

    好认真哦～。刚才不还说“诶——”来着吗？

    「不行。不能请假。别出门。饭在那里。是松饼。」

    我断断续续地说完，指着灶台上的平底锅。那是酒寄彩叶划时代的穷鬼料理——“粉和水做的松饼”。

    外星人立刻咬了一大口，然后脸皱成一团，

    「靠，真难吃……」

    说出了极其失礼的感想。喂，你不用再吃了。

    「那我走了。」

    「等等，不要不要！」

    呜，好热……。在这个除了电扇以外禁止空调的房间里被她缠着简直是种折磨。话说外星人也有体温啊。说起来婴儿时期也是暖呼呼的呢……。

    「好奇怪哦。是外星人耶？把这样的可疑人物留在房间里出门，正常吗？学校有那么重要吗？」

    你有自觉啊！那我要说了，

    「比命还重要！」

    我直视着她的双眼说道。

    我用一年时间构筑起来的学校生活，是我的毅力、努力和忍耐的结晶。我会拼上性命去守护，不会让任何人破坏它。更何况是这种来路不明的外星人。

    「虽然和你扯上关系是我的错，但我会让一切恢复原状的。」

    育儿游戏已经结束了。虽然算是颇有意义的三天，但我要变回原来的完美女高中生了。

    「所以，你也回月球去吧。」

    「……可是，我不知道怎么回去。而且这里好像很有趣。」

    这里是什么？地球？打算来享乐吗？

    「总之快点想起来！就今天一天。明白了吗？」

    我像科幻电影里的光剑一样伸出食指。一瞬间，外星人似乎还想反驳什么，但被我的气势压倒，立刻闭上了嘴，往后退了几步。

    「我走了。」

    趁着这次机会，我第三次说出这句话，关上门。外星人也没有要追上来的迹象。

    噗。

    我感觉关上的门后面，外星人好像说了什么，但也只是感觉而已，所以我毫不在意地走下了公寓楼梯。

    ※

    「如果能保持这个节奏，那就完全不是梦了哦。」

    放学后的教务室，班主任立花老师把志愿调查表和几所大学的宣传册一起递给我。

    「好的，我正打算这么做。」

    「别太勉强自己。身体也好，心理也好，搞垮了就没有意义了。」

    「谢谢老师。」

    身心都保持健康，并且维持一定的节奏吗？听到了和这三天完全相反的话呢。

    连休结束后平稳的一天，让我重新意识到了自己是谁。

    是的，我是完美女高中生酒寄彩叶。成绩优秀，品行端正，文武双全。但是，这种“完美”，终究仅限于“女高中生”的范畴。是作为一个极其普通、平凡的高中生而言的“完美”。

    所以在我的生活中，发光的电线杆也好婴儿也好，更别说外星人了，都毫无容身之地。踏实、勤恳、现实地朝着目标努力，这就是我。然后，总有一天要……

    「你父母一定也以你为荣吧？」

    「诶？」

    我反射性地抬起头。立花老师的笑容让人联想到温顺的山羊，看不出任何深意。肯定只是偶然提到父母的话题而已。

    「但愿如此。」

    我立刻露出满分一百分的笑容如此回答。完美女高中生酒寄彩叶的假笑也是一流的。但是，

    「……离期限还有时间。慢慢考虑吧。」

    这位人生经验丰富的老师似乎看出了些什么，在笑容之下，像咀嚼草料一样咀嚼着某种思绪。

    我鞠了一躬，走出教职员办公室。这时，热闹的笑声从敞开的窗户飞了进来。

    「今天去月夜见吗？」

    「有八千代的直播吧？」

    「来看黑玛瑙的KASSEN直播吧～」

    从窗户往下看，出入口仿佛是另一个世界。呼吸着放学后空气的学生们，个个都像长了翅膀一样脚步轻快。

    「……我也是放学后的学生啊。」

    我自嘲般的笑容，和他们脸上绽放的笑容完全不同吧。

    没办法。我的背上别说羽毛了，就连疲劳和睡眠不足都压得我摇摇晃晃。好了，今天也要打工。然后像往常一样预习复习。必须把这三天落下的进度补回来。

    老师递给我的几本大学宣传册，我从中抽出了一本。

    东京大学。我的志愿校从很久以前就没变过。如果要在日本升学，除了这里，母亲恐怕都不会认可吧。

    ——反正要瞄准，就得是第一才行。要是从一开始就瞄着第二第三，还不如直接穿过那片什么都不用做的平地更省事呢。

    不知何时，被母亲责骂时的话闪过脑海。

    那好像是钢琴发表会得了银奖的时候吧。母亲一脸严肃地对满脸笑容跑过来的我这么说。

    ——你笑什么。

    感觉之前的努力全都被否定了，挂在脖子上的银色奖牌显得无比羞耻。我只是想听你说一句“很努力了呢”。东京大学，能代替那枚金牌吗？

    「成为令父母骄傲的女儿，得到认可。可喜可贺，可喜可贺……嗯，这样就足够了。」

    我这样对自己说着，感觉僵硬的笑容似乎稍微融化了一些。但是，

    「出发！预备，跑！」

    「噢——，尤塞恩·博尔特——！」

    我的视线，始终没有离开以世界最快速度跑出校门的男生的背影。

    当然，我自然也不可能注意到，像忍者一样埋伏在校门旁的外星人。

    ※

    「啊，彩叶来了！」

    「总算结束了？」

    「咦，芦花？真实？」

    我以为她们早就回去了，但芦花和真实在鞋柜那里等着我。对了，我也有。能让我露出无忧无虑笑容的朋友。

    「连休过得怎么样？」

    「很忙吗～？」

    被外星人侵略了，这三天都没怎么联系上。或许她们是在月夜见等我吧。没有三个人一起玩的休息日，她们俩常常深夜登录。那样的话，等打工、学习、家务都结束后、我上床睡觉前的那一点点时间里，就能轻松地一起玩、一起聊天了。大概是考虑到约会会成为负担吧。虽然很抱歉让她们费心，但现在确实帮了大忙。觉得自己真没出息，胸口有点疼。

    「对不起！总之就是被折腾得够呛……」

    先含糊地搪塞过去，要是被继续追问该怎么解释呢……。我一边想着这些一边换鞋，

    「算了，先回去吧！」

    「回——家——啰——！」

    两人似乎察觉到了什么，切换了模式，牵起我的手，领我踏上洒满阳光的归途。

    「彩叶，你将来有什么打算？」

    「是走音乐路线吧？还是电子竞技之类的？」

    把我夹在中间，芦花和真实轮流问道。

    「我没那种才能啦～。而且要是考不上东大，我爸妈估计不会认可。」

    音乐不行。电子竞技应该让更适合的人去做。学习可以努力。母亲一边抚养四个弟弟妹妹，一边考上了京都大学。那么，没有任何束缚的我，必须更向前一步才行。我用开玩笑的语气回答。

    「底线在那里？好严格——」

    「像我这种人，就是被宠坏了的。」

    两人也跟着笑了起来。

    一如往常的对话。芦花和真实的笑容也一如往常，不过，特意等到我回去，也许她们真的有什么想问的事吧。

    但是，两人就像商量好了一样，维持着一贯的步调和气氛，

    「是这边吧？」

    「嗯，就是那边的楼梯上去。彩叶快来！」

    咦咦咦？我被带向一栋不同寻常的陌生大楼。那里有什么？

    「等等，你们两个，今天有什么事吗？」

    顺便一提，我这边可有。打工啦学习啦……还有家里有个外星人。

    「不是说好要去新咖啡馆吗？」

    「不，今天……」

    饶了我吧，真实同学。不能说，这三天我花了很多钱。这种看起来就很贵的地方，我连脚都不敢踏进去。

    「不是说好了嘛！」

    啊，不行。真实的眼中燃起了美食的火焰。这样的真实已经没人能阻止了。

    「好啦，出发啰！」

    「拜托了啦～～」

    贫穷女高中生的愿望落空了，被带到了一个以“天空、大地与人相连”为概念的复合设施内。自然光充沛、既时尚又高价的咖啡馆一角。

    「彩叶笔记助我免于不及格纪念～～」

    「这是谢礼，请收下～」

    「谢、谢谢！」

    端到我面前的，堪称“上镜”的象征——堆满了奶油、充满梦幻感、蓬松的三层松饼。

    经验告诉我……这种时候是她们请客！！说实话太高兴了。有多少天没吃到这种闪闪发光的食物了？形式上的客气也只会被两人温柔地挡回来，所以这里就再吸一口气……

    「我开动……」

    ——唰！

    无情的三叉刺击兵器，插进了我触手可及的闪闪发亮松饼♡。

    「……咦？」

    握着银色叉子的，是一只即使在夏日阳光下也无法融化的、如雪般白皙的左手。

    「我开动啦！啊呜，吧唧吧唧……嗯嗯好好吃！」

    哇，一口就吞下去了。

    凶手将三层的蓬松松饼瞬间减为两层，脸上绽放出童话里的月之公主也望尘莫及的灿烂笑容，

    「哟，彩叶！」

    一个完美的眨眼，向地面撒下星光。

    你、你这、啊——呜！！

    「诶——，好可爱，这孩子是谁？」

    「穿着彩叶的衣服，是彩叶的朋友？」

    「啊啊啊啊啊啊，是、是的！不，说是朋友，那个……」

    该、该怎么解释才好！？话说真的穿着我的衣服！！这个能以什么罪名抓起来吗——！！

    「喜欢松饼？来，这个也给你～」

    芦、芦花！别惯着她！！

    「松饼？这就是？和彩叶做的完全不一样～」

    吵死了！话说，你为什么在这里！？我不是叫你待在房间里吗！

    外星人置恐慌状态的我于不顾，一如往常地把芦花给的松饼也一口吞下。顺便还笑嘻嘻地说着胡话。她那堂堂正正的样子，反而让我感觉头上的热度渐渐冷却下来。

    「介绍下嘛，彩叶。独占这么可爱的朋友太狡猾了。」

    「不，应该不算是朋友吧……那个，那个……」

    我装作支支吾吾拖延时间，用眼神示意她“快点回去”。

    「从月球来的！」

    这家伙在说什么啊？到底是怎么理解的，说出了最糟糕的自我介绍。

    「……诶？」

    「月……？」

    「筑地！是筑地吧！从筑地来的，我的表妹！」

    哎呀，这也太牵强了吧。我战战兢兢地看向真实的脸，

    「哇——，告诉我好吃的寿司店嘛～～？」

    太好了，信了。不愧是立川第一的美食女孩。芦花那边呢？

    「好可爱呢，你叫什么名字？」

    得救了，这边似乎也沉浸在外星人的美貌中。不愧是立川第一的美容女孩。

    「名字？名字是，呃——……」

    突然，昨天看过的童话闪过脑海。对了，那位公主——

    「辉夜！」

    辉夜姬。

    「辉夜～～，可爱——！」

    「嗯～很合适呢。」

    对吧，辉夜！趁着芦花和真实热烈讨论起来，我再次将视线投向暂定的辉夜姬，全力传达信息，

    「辉夜？辉夜……辉夜……这样啊。是辉夜啊～！」

    出乎意料，辉夜看起来很高兴。名字是人生第一份礼物。我突然想起一句似曾相识的话。

    「对不起，我要回去了！谢谢款待！回头我再补请你们。」

    已经到极限了。我把躲过辉夜袭击、幸存的一二层松饼两口塞进嘴里，抓住还在红着脸害羞的辉夜，像风一样逃离了咖啡馆。

    「哎呀——，刚才那栋大楼里好凉快啊。彩叶家能变成那样吗？」

    离开咖啡馆后，辉夜也开心地聊个不停。我带着这样的外星人走到人迹罕至的角落。

    「你疯了吗！？为什么在这里！？为什么从家里出来！？我不是叫你待在房间里吗！从月球来！？身份暴露了怎么办！？为什么穿着我的衣服！你怎么知道我在哪里！？」

    我把想说的话全都倾泻而出。在我看来看这些都是极其正当的疑问和抗议，

    「因为，太无聊了嘛。」

    辉夜只用一句话就顶了回来。感觉就像五岁小孩的玩具被抢走后在闹别扭。

    真的吗，这个外星人。因为无聊？就因为无聊？就因为这个理由违背约定跑出来，冒着外星人身份暴露的风险出现在人前，甚至还说自己从月球来？真的，仅仅因为无聊？

    「嘿嘿嘿。」

    看来真的是这样。然后大概在我沉默的两秒间心情变好了，辉夜奇怪地嘿嘿笑着。……等等？难道是想笑着蒙混过去？

    「我说啊，这样活着会自取灭亡的，有时候也需要忍耐——」

    ……。

    虽然顺利开了头，却接不下去了。因为这是我母亲对我说过的话。呜——同样的事……。

    「呐，这个，怎么用啊？」

    趁我不备立刻递过来的，是隐形眼镜型电脑设备，通称——

    「这不是智能隐形眼镜吗？你把我的带来了？」

    「不是哦，是用彩叶的笔记本电脑买的。」

    ……啥？

    「耶♪」

    耶什么耶，有什么好耶的。我拿出手机，半疯狂地搜索网购记录。

    『钱包余额 ￥452 较前日 ￥-124400』

    ……。诶，这是现实？怎、怎么可能……。

    「……我、我可是拼了命才存下的……拒绝了美食、凉快、温暖，放弃了娱乐，连给推花钱都忍着，拼了命……拼了命才存下的！！」

    单从心情上来说，我很想大哭着跑出去，但悲哀的是，这种没有体力的尖叫是我现在能做的最大的抗议。

    「啊，没事！好像银行？的数据改写一下就能增加钱包里的数字呢！对辉夜来说是小菜一碟，要干吗？」

    看到我不寻常的样子，她好像慌了，但没有伦理观！

    「当然不行啊！绝～～对！不许干！」

    ※

    外星人必须赶出去。如此坚定地发誓，打开没上锁的公寓门。

    「让我抢先一步！」

    「痛，什么？」

    「锵——！」

    迎接我的是暴力般诱人的香气，以及暴力般抢先一步的辉夜得意洋洋的表情。摆在那里的是外观华丽、绚烂豪华的料理盘子。我不由得咽了口唾沫。

    「首先是，用生玉米做的浓汤。这边是新牛蒡和芦笋的酥脆沙拉，附温鸡蛋。主菜是番茄炖汉堡肉，配菜是炒西葫芦哦♪」

    辉夜这样说着，还附带上了自己的笑容。品尝着从未踏足过我家门槛的美味料理，连平时用的矮脚桌都显得很自豪。

    「这是……什么？难道是你做的？」

    「是呀～～」

    骗人，看起来好好吃。虽然看起来超级好吃……。

    「这也是……用我的钱包……？」

    「是呀～～」

    骗人，我要晕倒了。虽然真的快气晕了……。

    「来，吃吧。」

    被强行把浓汤的勺子塞进嘴里。

    骗人吧，脸颊都要掉下来了。好吃得舌头都快融化了……。

    「怎么回事啊……明明这么好吃……怎么回事啊你……好久没吃到这么美味的饭了……身体都要被喜悦填满了……」

    不知道为什么，眼泪和筷子都停不下来。上一次吃别人亲手做的饭是什么时候了？员工餐虽然也算是亲手做的，但感觉果然不一样。总觉得，有味道。不，其他食物也有味道，但最近总觉得像是隔着一层薄纱才能尝到下面的味道……。好吃……。都被这样招待了，还说什么呢。但是，刚才……一、十二、万……呜、呜……。

    「……恶魔。」

    「不是恶魔哦，是辉夜呀～♪」

    这个可爱的小恶魔！气死我了。可恶，好吃得让人火大。这个快乐至上的恶魔外星人做的天使般的料理，连最后喝的自来水都觉得好喝。

    顺便一提，吃完饭确认了一下账单，

    『￥1090（超级味噌） ￥540（超级味噌） ￥1239（近藤肉铺） ￥2680（坂本鲜鱼） ￥465（超级味噌） ￥780（广志面包） ￥350（青木水果） ￥1560（小林杂货） ￥730（水果乐园） ￥2000（Bistro松尾） ￥390（超级味噌） ￥1250（近藤肉铺） ￥1456（YU） ￥220（多香堂） ￥1200（超级味噌） ￥3720（青木青果）……』

    果然是恶魔。这家伙。

    ※

    「那个啊……」

    吃饱的身体躺在地板上。肚子里暖烘烘的。从头到脚都洋溢着浓稠甜蜜的幸福。

    「真的不能收留你在这里哦。」

    即便如此，不行就是不行。我抬头看着荧光灯吐出这句话。

    「我跟父母说尽好话才能一个人住，不想再惹麻烦了。要是出了什么事，马上就会被送回老家……喂，你在听吗？」

    「好的，这里这样！咔嗒咔嗒咔嗒！」

    你没在听吧，你。我就知道。

    辉夜正专注地敲击着我的笔记本电脑，连眼睛的颜色都变了。屏幕上密密麻麻布满了各种可疑的代码。虽然想阻止，但饱腹的黏着力让我的背贴在地板上，而且，

    加入这个

    「再来一次，咔嗒咔嗒咔嗒♪」

    看着快乐地摇晃着敲击键盘的辉夜的身影，不知为何有点难过，就没能阻止。这是什么感觉呢。明明没见过，却如此怀念的光景。我在看谁的记忆呢……。

    「完成啦！」

    完成了什么？糟糕，一不小心就发呆了。

    「该不会是网络犯罪吧？」

    「看，彩叶。我找到了便携游戏设备，就试着弄了一下！」

    「啊，那个……」

    那是以前哥哥送我的复古蛋形掌上游戏机。大概是把收起来的东西擅自拿出来的吧。反正也没用，算了。

    「这是‘狗狗DOGE’！」

    狗狗DOGE？我看了一眼掌上游戏机，里面有一只柴犬模样的卡通人物摇着尾巴。我记得没有这个，是原创的吧。

    「这样就能永远在一起啦～！哼哼～～～♪」

    「心情真好啊……。话说，你是打算一辈子住在这里吗？」

    「不然我还能去哪儿？要是被抓了，辉夜说不定会被解剖掉哦～」

    「回月球去不就好了？努力想想回去的方法啦。」

    「有在努力想但是好难～～唔唔唔」

    一边心不在焉地按着掌上游戏机一边回答，根本——没在听我说话。那明显是在说游戏里的关卡吧，这家伙。

    ……真是的，真是的。我强行把和地板愈合的后背撕扯下来。

    「那就待到有人来接你为止吧。」

    不过冷静想想，也不能真的扔下她不管。

    「真的可以吗！？」

    「一、不准引人注目！二、未经许可不准外出！三、不准妨碍我！只要能遵守这三条规矩，就可以待在这里。」

    「……诶，那，能交朋友吗？」

    「根据第一条，不行。」

    「……能跟去咖啡馆吗？」

    「根据第二条，不行。」

    「……能一起玩吗？」

    「根据第三条，不行。」

    「那、那辉夜既不能出去，也没有乐趣，就这样一直被关着，迎来坏结局……是吗？」

    握着狗狗DOGE的辉夜，脸色明显变得苍白起来。

    「不愿意的话，就当我没说过。」

    「不要不要，坏心眼！」

    「快乐结局不是要自己创造的吗？这种状况也要快乐地享受哦。」

    「在这种又不起眼又无聊的家里！？」

    好，还是把她赶出去吧。刚这么决定，正准备撸起袖子，手机的闹钟提示晚上八点三十分，震动起来。

    糟了。本来打算在这个时间之前完成预习的，结果今天还是什么都没做。但是，没办法——必须去。

    「什么？你要去哪儿？又把辉夜丢下吗？」

    但是，迅速察觉到我动向的辉夜像擒抱一样紧紧抱住我。

    「放开我。我哪儿也不去。只是去月夜见一下而已。」

    「要去嘛！把辉夜也带上！」

    「不行，没有智能隐形眼镜的话……啊！」

    有啊，这家伙。可恶，带上你吧……。啊！对了，这个也得说！

    「四、伙食费采用定额制！」

    「又增加了！」

    戴上智能隐形眼镜，两人并肩而坐。辉夜抓住我的手腕，传来微微的暖意。

    「要走了，预备！」

    ▼

    闭上眼睛，模拟宇宙的动态图像展现在眼前。像流星一样穿过根本不存在的银河，激起浪花，一座巨大的红色鸟居出现了。脚下是没有尽头的浅湖，以及在水面上滑动的众多灯笼。天空中蔓延着宛如鸟居染出的火红晚霞，

    『——太阳西沉，夜晚降临。』

    庄严地，月见八千代显现了。

    那是百看不厌的虚拟空间“月夜见”的入口。

    啊，再看也还是觉得八千代的设计太棒了。脸蛋当然很美，穿着以海洋生物为主题的和风服饰，带着海牛形状的吉祥物FUSHI，那姿态正是永恒的女神、电子歌姬、月夜见之母，是尊贵的象征。

    作为重度用户，我直接跳过入口进入月夜见，但初次登录的辉夜现在应该正在接受八千代和FUSHI的教程吧。八千代会亲切地握住初次来访用户的手。然后，浮现出百分百的笑容，用仿佛在鼓膜上吹过清风般的爽朗声音说：

    『——出门前，这身打扮太没意思了！』

    引导用户进入角色创建窗口。

    接下来就是愉快愉快的角色创建时间了。顺便一提，我的虚拟形象是以蓝色为基调的街头风。和服搭配连帽衫、腰带和靴子，弄成了有点帅气的样子。还有狐狸主题的尾巴和耳朵。第一次看到自己变成这个样子的时候，说实话兴奋到不行。不，今天看也觉得好可爱。果然是最棒的。

    那么辉夜会以什么样子出现在月夜见中呢？

    空间里闪过一道光的波纹。

    来了。撕裂光的中心，

    「呜哇！」

    金发辣妹风的辉夜姬降临了。

    辉夜是朱红配嫩绿的穿搭，金色闪亮的月亮发饰和背上的巨大礼绳给人一种喜庆感。脚上运动时尚的轻便运动鞋，透露出她什么都会去做的行动力。似乎是兔子主题，沿着顺滑的直长发，垂着兔子的长耳朵。

    「哇哦——！」

    然后就那样用力过猛摔倒了。好了，出现了。月夜见初次登录常见情况——第一步就容易摔倒。

    「来，手给我。」

    「啊，难道是彩叶？」

    抓住我的手站起来的金发华丽辉夜姬，指着我的虚拟形象。一只狗在她周围跑来跑去。

    「难、难道是……」

    「狗狗DOGE！能带进来啊！」

    不，我也是第一次见。掌上游戏机的宠物能以这种形式带进来吗？不愧是月夜见。什么都行啊。

    「哇！好厉害好厉害好厉害，这就是月夜见！？」

    抱着狗狗DOGE的辉夜，这才注意到虚拟空间月夜见的常夜街道，两眼放光。

    「呜哦，好厉害！看起来有趣的东西多得要死！」

    张大嘴巴，呆立着环顾四周的辉夜。这也是月夜见初次登录常见情况。被景色吸引，怎么也进不了城。确实，虚拟空间月夜见里有七彩辉煌的夜景、著名的太鼓桥、堪称奇幻平安京的“和风”街道等无数值得一看的地方，但今天时间不多，就去咖啡馆随便喝杯茶吧。

    「走吧，辉夜」

    正要迈步的时候，

    『——恭喜初次登录！在月夜见，大家都是表演者！如果你做了什么打动人心的事，也能从运营那里获得‘fuju’哦☆』

    辉夜的初次登录事件发生，FUSHI出现并开始说明。这是在介绍月夜见内使用的虚拟货币fuju。购买创作者制作的虚拟形象服装、委托事项、或是作为应援的打赏等，用户间的交易都使用fuju。也能兑换成现实货币，据说人气主播之类的光靠这个就能过上优渥自在以上的生活。虽然和我这种没什么长处的人无缘。

    但我之所以能在这里尽情游玩，是因为运营提供的各种世界、游戏等体验设施，以及装饰虚拟形象的各种物品基本上都是免费的。这里不存在那种号称基本免费、实际上不花钱就跟不上的情况。正好现在我们吃的华丽芭菲当然也是免费的，

    「啊呜……嗯咕嗯咕……味道——完全尝不出来！」

    「那个好像还不行呢。总有一天会有天才科学家做出来的吧。」

    「现在就要～～～～～～」

    你跟我闹也没用啊。啊，时间到了！

    「要开始了！走吧，辉夜！」

    「要开始，什么开始？等等，彩叶！」

    「不等。你自己跟上来！」

    我承认自己这烦人的兴奋劲。但是，胸中的激动抑制不住。奔跑的脚步停不下来。

    因为我终于等到了。轮到我了。我参加了好几次抽选，落选了也继续申请，终于中选之后也掰着手指头数日子，终于等来了现在这个时刻——

    「来了来了来了！没有这个月夜见的夜晚就无法开始。今天也是八千代迷你演唱会的开场啊啊啊——！」

    没错，就是八千代的迷你演唱会。而且演出结束后……呵呵……。

    在时间紧迫的情况下冲进演唱会现场，自称是八千代大粉丝的MC主播忠犬御宅公将自己的兴奋与狂热通过麦克风响彻全场。蜂拥而至的观众以欢呼回应。会场的热度如漩涡般高涨，巨大的屏幕上显示出倒计时。

    啊，开始了。真的要开始了。

    「呐，彩叶，什么要开始了？」

    「看着就知道了！」

    「5……4……3……」，会场的声音与观看直播的声音同步。然后，当月夜见中所有人齐声喊出“0”时，

    『哟——咯——！诸位神明，今天也过得超——开心吗——？』

    出现的月见八千代，用一句话引爆了会场。

    『好——，今晚也邀请大家一起来吧☆ Let’s go on a trip！』

    就这样，精彩的现场演出拉开了序幕，

    『历经数千时光轮回，你我此刻相遇——看啊，为了不走散——不要松开手——』

    会场化作了狂热的海洋。

    ※

    「彩叶！喂，彩叶！」

    耳边的大叫声让我回过神来。回头一看，金发的辉夜姬一脸惊讶地看着我。难道叫了我好几次名字吗？涣散的意识慢慢地、慢慢地重新聚拢。手指还在颤抖。

    「彩叶，你为什么在哭？」

    是吗，我在哭啊。请不要让我解释这眼泪的原因。因为一旦化作语言，感觉立刻就会变成陈词滥调。

    ……因为是那么精彩的演唱会啊。歌曲和表演，还有八千代本身。

    这种心情似乎是观众共通的。经久不息的兴奋与感动，取代掌声与欢呼，倾泻在舞台上。正中央，八千代用力挥手回应着粉丝。

    『耶——，感谢感激雨露均沾！八千代是个幸运儿呢。啊，在这里通知一下！要举办一个叫‘八千代杯’的活动～☆ FUSHI，详情拜托啦。』

    「好的～！有资格参加的是月夜见的所有主播！在一个月的时间内，获得最多新粉丝的人就是优胜者。优胜者将获得——与八千代合作举办演唱会的权利！一起打造世界上最热闹的合作演唱会舞台吧！」

    「不会吧！？合作演唱会？和八千代！？」

    糟了，声音太大了。希望现实世界的邻居别又来敲墙就好。

    「合作演唱会？那是什么，很厉害吗？」

    「那当然了！」

    我又大声了。但是，没办法。我向完全不明白事情重要性的辉夜强调。

    「岂止是厉害，虽然有过合作直播，但演唱会一直是她一个人唱的吧！？什么？和谁一起？这将是历史性的演唱会！」

    「嘿——，那彩叶，我们一起参加吧。」

    做得到吗？果然什么都不懂。怎么可能和我们这样的小角色一起办。虽然不能大声说，但这种事从一开始就大概定好由谁赢了，这是惯例。比如说——

    「砰！」一声巨响轰鸣，所有观众都注视过去。

    是的，就像他们一样。

    突然出现在演唱会会场的不是牛车，而是由老虎拉着屋形的虎车。早已察觉到来者身份的粉丝们齐声欢呼。

    「是黑玛瑙！」

    「帝大人——！」

    像是回应热烈的欢呼声，屋形裂开。

    首先出现的，是身披鬼怪意象皮肤的男性虚拟形象。此外，两侧分别有穿着长袍般服装的虚拟形象，和地雷系少女时尚的虚拟形象护卫着。

    如同悲鸣般的欢呼声，将演唱会会场笼罩在另一种狂热之中。在月夜见拥有超高人气的三人组职业玩家组合“黑玛瑙”。通称黑玛瑙登场了。他们作为偶像也广受欢迎，活动范围广泛。

    「哟，小兔子们，你们的皇帝驾到了。」

    在震耳欲聋的欢呼声中，从虎车上走下来的队长帝明露出无畏的笑容，漆黑的角闪闪发光。

    他啪地打了个响指，会场的屏幕就被劫持，播放起他们光辉履历的PV。从组合标志开始，赞助商企业、无数电竞赛事的优胜记录、演唱会影像接连不断。BGM是他们的原创曲。

    你还是老样子啊……。我把自己藏在辉夜身后，以免被发现。没什么，对方应该不认识我的虚拟形象。

    「庆典又要开始了。」

    沉默寡言的男人，雷从兜帽下开口。

    「人家今天的造型也超赞吧♡ 对吧♡」

    地雷系主题的少年乃依可爱地展开粉丝服务。双马尾加迷你裙。乍一看像女生，但其实是男性虚拟形象。当然，声音也是男的。

    「希望我们赢吧？让你们见识见识深不见底的梦想！」

    最后，帝以决胜姿势射穿了粉丝的心。伴随着破裂声，纸屑飞舞。

    欢呼声三次爆发。这一瞬间就已经决定了。八千代杯的冠军是他们，在场的所有人都如此确信。

    「所以，冠军我们拿下了。八千代酱，合作就拜托咯。」

    不是别人，正是黑玛瑙的成员。

    「如果是这样的命运，八千代当然会遵从啦～」

    说不定，主办方八千代也是？

    「太厉害了，八千代和黑玛瑙的梦幻合作！」

    「这要成为传奇了！」

    还有蜂拥而至的观众们。观看直播的听众们也是。

    除了一个外星人。

    「八——————千——————代——————！」

    「辉夜要赢下八千代杯！所以绝对要一起办合作演唱会！彩——……唔！」

    我慌忙捂住嘴，但为时已晚。

    这家伙，竟然敢这么做……难以置信。明明约好了的。“不准引人注目”，这是第一条规矩。周围所有的人都回头看了过来。有个有趣的家伙，那种眼神。观众们，黑玛瑙和忠犬御宅公，

    「……真可爱。」

    甚至连舞台上的八千代也是。

    「你啊！老是这么任性！」

    我真的很想逃离，但做不到。因为这场演唱会——

    「那么，演唱会暂时在这里闭幕♪让我和大家稍微聊几句。再见～」

    是附带握手券的。演出结束后，八千代会分身去跟会场的每一位观众说话。从这里开始没有直播，是只有拿到票的人才能体会的梦幻时光。可以和八千代面对面交谈并握手。……和八千代面对面交谈！？可以握手了！？！？难以置信。紧张得指尖发冷。要、要晕倒了……。

    「呐彩叶，一起参加吧？」

    辉夜漫不经心的声音拉住了逐渐远去的意识。好像一只手也暖暖的。啊，是辉夜在现实里一直握着我的手。

    「不行！那种事不——」

    「不行不行不行！小丫头！」

    我想说不行，但被她抢先说了。我看了看声音的主人，是FUSHI。咦，FUSHI？是这么说话的吗？平时更像是吉祥物的可爱说话方式……。

    「喂！」

    八千代制止了威吓的FUSHI。哇！！八千代！！眼前，八千代就在……而且还是缩小版。八千代平时身高一米六左右，但偶尔会变成一米三左右的迷你八千代。条件不明的稀有现象，让兴奋加速。周围的分身八千代们还是大人版。为什么只有我！？大概是日常的心血来潮吧。但是……可～～～～爱！过！头！了！！

    「你忘了吗～？八千代杯仅限于主播参加哦♪」

    比平时短的双马尾，轻快地摇晃着。

    「这样啊！那辉夜就当主播！决定了就准备准备～」

    辉夜立刻退出了。哇，糟了，只剩下我和八千代两个人了。怎么办。

    明明那么期待，想说的话也准备好了。不行，什么都想不起来，脑子里一团乱麻，组织不了语言。这样下去会变得语无伦次。我想避免那样。但是，该怎么办……。

    「今天玩得开心吗？」

    「！？是、是的……！」

    我支支吾吾的，八千代跟我搭话了。熟悉的温柔声音。……是啊，一定要开心。八千代，应该最喜欢看到我——看到粉丝们开心才对。深呼吸，从正面看向八千代的脸。

    「我一直，都被八千代支撑着……就像又黑又冷又长的隧道一样……因为有八千代在，才能坚持下去……」

    啊？我刚才说什么了？前、前后连贯吗？意义不明……明明应该说得更机灵点的……。

    「……你在想‘应该说点更机灵的话’对吧？」

    「呜诶！？为什么！？」

    被看穿了！？好、好羞耻……！但是……！有点高兴……！

    「哼哼，八千代是超能力者哦♪」

    微笑着，八千代像往常一样开了个玩笑。什么啊，可爱，死了。

    「八千代，也是一样的哦。」

    用温柔的声音说着，八千代用小小的双手包住了我的手。一瞬间，脑子里被“！？”填满，但确实如此。这是握手活动。

    「八千代，也……？」

    我战战兢兢地反问，八千代温柔地微笑着点了点头。

    ——很久很久以前，一只孤零零的海蛞蝓，一直走在又黑又冷又长的隧道里。走了很长很长的时间，当它觉得“啊，好累啊～”的时候，看到了很多温暖的光。海蛞蝓拼命追赶，光们聚集起来，变成了一轮很大的月亮，照耀着海蛞蝓。不久，海蛞蝓化作了人的模样，为了守护月亮，创造了月夜见。

    我努力咀嚼着每一句话的意思。因为这是八千代特意为我讲的故事。海蛞蝓……啊，不会是FUSHI吧。大概是八千代的事，而光是月夜见的用户们？那、那八千代是把我们当作月亮了……。

    「八千代……」

    光，是八千代啊。是八千代，照亮了我。

    「锵——☆ 月夜见诞生的秘密故事♪ 要对大家保密哦。」

    没见过这样的设定，大概是配合我的话即兴编的吧。八千代明明说得那么开心，我的眼泪却涌了上来，快要哭出来了。

    「好孩子好孩子，很努力了呢。」

    八千代把一只手从我手上拿开，摸了摸我的头。我有点想依赖这个触感……啊，头！？摸、摸摸我的头了！？！？！

    「啊、咕、啊、八、八千……」

    嘴、嘴不听使唤了！

    「谢谢你总是来看我。」

    哇～好开心～～～♡……总、总是！？被记住了！？啊，对了，查看行动日志就知道了吧。八千代是月夜见中的神明。我在哪里做了什么都是一清二楚的。哈、哈啊，已经到极限了。

    「那、今、今天就到这里。谢谢您！」

    我低下头，退出了。如果坚持太久，可能会成为八千代的负担。八千代的性能远超我的想象，这可能是多管闲事。但已经说了很多话，也握到手了。

    ……脸好热。感谢、羞耻、欢喜、焦躁、安心。各种情绪混杂在一起，快要爆发了。

    「再见哦，彩叶……」

    身后，好像传来了八千代的声音

** 第三章

    「主播……怎么当……好」

    刚从月读世界登出，映入我眼帘的，就是辉夜正在用电脑搜索着什么的光景。

    那个正欢快地敲着键盘、金发华丽耀眼的辉夜姬，把刚才的余韵吹得一干二净……

    「——诶，等等，怎么头发还是金色的？」

    「哎，不行吗？那——嘿！嘿！嘿！」

    每“嘿”一声，辉夜的头发颜色就变一次。绿、红、白、条纹、大理石色……经历了一圈变化后，

    「果然还是这个吧☆」

    最终变回原本的金发，她得意洋洋地用手梳理着头发。冲击力有点太大了。我……真的从月读世界出来了吗？确实回到现实世界了吧？

    「……理解范畴之外的宇宙人」

    算了，什么都无所谓了。我把怒气抛至脑后，一头扎进了学习桌上的参考书里。

    啊，不过八千代的直播真是最棒的……

    ……和八千代说了话，还握了手呢。和那个八千代。虽然没有触感和温度，但心里确实感受到了手掌的温暖。

    ※

    「谢谢光临——」

    我微笑着送走BAMBOO cafe的常客，转身立刻赶往另一桌客人。去厨房下单的路上，顺手收走了空盘子，还把元气满满地摔了一跤的实穗酱打飞的盘子一个不落地接住，全部一起扔进了洗碗机。BAMBOO cafe招牌般的客流高峰时段，今天也如战场般忙碌。

    ……啊，真让人平静。

    管它是战场还是修罗场，只要听不到辉夜那尖锐的声音，就感觉人都年轻了。

    我哼着歌度过了高峰时段，躲进了员工休息室。在钢管椅上稍作喘息，然后调出了智能手机里的通讯录。

    「爷爷，我是彩叶——这个月的汇款也多谢啦。」

    「说啥呢，那点够用吗？」

    电话那头爷爷的声音，听起来比起听到孙女声音的喜悦，担心似乎占了上风。汇款的钱，我都存在了和生活费分开的账户里，分文未动。虽然有点对不起爷爷奶奶，但为了保护我那点可怜的自尊心，我也只能这样辜负他们的心意了。

    爸爸那边的祖父母，我是说明了情况，请他们支持我来东京的。两位一开始也反对，但我一次又一次地传达了我的决心，终于得到了他们的理解。

    ——如果就这样下去，我会不知道自己为什么活着。我想成为一个能让妈妈……还有爸爸，都能挺起胸膛骄傲的人。

    我知道妈妈在祖父母面前强硬不起来。被自己亲生父母抛弃的妈妈，发自内心地尊敬着从福利院领养了年幼的爸爸并把他培养成人的爷爷奶奶。我利用了这一点。不这样的话，妈妈是绝对不会同意的吧。

    「没，真的非常感谢。我记在心里了。……我出路也定下来了，之后麻烦跟妈妈说一声。」

    「我来说吗？嗯，行吧。最近……是不是没怎么联系啊？」

    「嗯——，她不太联系我嘛。说不定这样反而正好。那，爷爷也多保重。也帮我跟奶奶问好。」

    我尽量让声音听起来精神饱满，挂了电话。

    ——母亲　未接来电（5通）

    然后，我别过脸，不让屏幕映入眼帘，把手机塞进了包里。移开的视线捕捉到了墙上的日历。

    距离发薪日还有一天，不知不觉间，第一学期已经结束了。

    「好！」

    打工一回来，我就气势十足地把暑假计划表贴在了墙上。学习的红字和打工的蓝字像拼图一样密密麻麻地填满了表格，连我自己都觉得无可挑剔，堪称完美。

    「这、这是什么啊～～」

    然而，辉夜却用有气无力的声音嘟囔着抱怨。

    「什么？暑假计划表啊。一天都不能浪费，不许打扰我。」

    「不要——！跟辉夜玩嘛～～～？」

    我就知道会这样。

    「……我要赶你出去了哦？」

    我用恶鬼般的目光射向抱住我腰的辉夜，

    「还有，那些是……？」

    顺便也瞄准了占据四叠半房间一角的破烂堆。没见过的奇怪角色玩偶、不知道怎么用的玩具、连是什么都不知道的玩意……

    「直播用的小道具们！全部都是百元店的，放心吧！」

    「直播？你真打算当主播？」

    「当然！要想在八千代杯中获胜，首先得成为主播才行。呐，你看。我都已经开始直播了～～，怎么样？」

    辉夜自信满满地打开PC屏幕给我看，上面是她手绘的、画得歪歪扭扭的插图，正诡异地在挥手。

    『辉夜驾到——！我是从月亮来的辉夜哦——。今天没什么想做的，就到这里吧！拜拜……嗯？这样算关掉了吗？』

    ……后半段，画面切换成了实拍图像。

    「喂喂喂喂！最后不是切换到前置摄像头了吗！脸都露出来了啊！」

    怪不得播放量跟这质量不匹配，原来是这么回事。当然，似乎被听众们逮了个正着，评论区里清清楚楚地留着“前置摄像头w”、“是八千代直播上的那个孩子吗？”、“不可爱吗？”之类的留言。唉，反正已经来不及了。比起那个，我更在意视频背景里播放着的……这是什么，这刺耳的不和谐音？

    「是开场曲哦。」

    ……开场曲？就是那个为了给听众留下印象、旋律轻快的开场曲？

    「我自己原创的。」

    我就知道。这么让人不安的音源，免费素材库里肯定也找不到。

    「等等。你怎么做出曲……啊，我的键盘！别擅自拿出来啊。」

    果然不出所料。我以前用的那个六十一键键盘，半埋在破烂堆里露出了脸。

    「啊，看你这反应。彩叶你会弹吗？我完全弹不好，老师，请指点一下吧！」

    大概是从我的反应猜到了水平，辉夜唰地一下把压在键盘上的破烂扫开，接通了电源。

    「哈啊？凭什么我要做这种事？」

    「求求你啦☆」

    辉夜熟练地抛来一个完美的wink。可恶，这家伙撒娇的手段越来越多了。啊，连破烂也越来越多。

    「首先最起码得有个和弦才行……」

    我放弃了，手指伸向昔日熟悉的琴键，正准备在手边编出旋律，

    「啊……」

    胸口深处有什么东西崩裂开来。那是我一直封闭着的记忆。

    『彩叶，音乐是让人自由享受的东西哦』

    爸爸的话。年幼的我笑着。我弹钢琴的时候，房间里回响的与其说是乐器的声音，不如说是欢笑声。身旁的爸爸也在笑。哥哥和妈妈也在笑。妈妈是从什么时候开始不再笑了呢。

    一定，是从爸爸的葬礼开始吧。从那时起，妈妈就不太表露感情了。我泪流满面地送别躺在棺木中、像人偶一样的爸爸。妈妈却面不改色。

    ——喂，为什么只有我一个人在哭？妈妈……不难过吗？

    忽然回过神来，发现辉夜正用充满期待的眼神注视着我。

    不知从何时起，我开始讨厌音乐，疏远了钢琴。妈妈说的话也变了。

    ——一事无成却能成功的，真的只是极少数人。现在不是乐在其中的时候。你从爸爸那儿得到的东西，你就打算这样玩着糟蹋掉吗？

    啧，要是留下心理阴影就正中妈妈下怀了。管他呢。

    手颤抖了仅仅一瞬。指尖一旦触碰到白键，就如同被放归草原的小鹿，在琴键上奔驰起来。

    「哇啊……」

    音乐满溢而出。

    不是从键盘，而是从我的内心。手指停不下来。一个音符引导出下一个，又呼唤着再下一个。手指每敲击一次琴键，压在心头的那份沉重便随之剥落。

    「彩叶，好厉害！这是什么曲子？」

    手指冲破心之牢笼，从记忆深处打捞上来的，是我还喜欢音乐时创作的旋律。

    「啦……啦啦……谁也阻止不了——无法抑制——不唱不行」

    辉夜和我一起唱了起来。

    她立刻抓住了节奏，感受着旋律，即兴地填上了歌词。

    多么美妙的声音。多么优美的歌声。像是全身细胞都得到滋润，又仿佛春风吹拂心田般的歌声。

    「好耶！」

    回过神来，已经完整弹完了一曲。鸡皮疙瘩爬满全身。手还在颤抖，不是因为恐惧，而是兴奋。久违了，真的是久违了的、从心底感到快乐的演奏。辉夜似乎也和我一样，她说：

    「太棒了——！这是彩叶创作的？厉害过头了！」

    她兴奋得双眼放光，拍着手，蹦蹦跳跳地转着圈，

    「彩叶，来当我的制作人吧！」

    最后以一个漂亮的转身，说出了不得了的话。

    「哈？制作人？为什么？」

    「因为因为！现在，八千代杯暂居第一的黑玛瑙是个三人组合，太狡猾了吧？辉夜明明一个人这么努力，才排八千多名呢。」

    辉夜飞快地打开笔记本电脑，展示出八千代杯的暂定排名。曾高声宣布要夺冠的辉夜，目前的排名是八千九百一十位。果然，夺冠什么的简直是痴人说梦。

    「所以说嘛，一起干吧？彩叶作曲，我来唱，绝对会大火的！传奇就从这破旧公寓里开始！」

    「不许说公寓破。」

    「不行。我哪有时间作曲……」

    「……倒也不是完全没有。如果是改编以前创作的曲子，现在的我也能做到，反而可能是个不错的调剂……而且，也确实很开心。」

    一旦表现出这种动摇就完了。这么大的破绽，全宇宙最会撒娇的人怎么可能放过。

    「求你了，彩叶。我不想就这样结束……我想要一个幸福的结局……好吗？」

    她眼眶含泪，吸着鼻子，双手紧握，演出了完成度极高的可怜模样，摆出了超必杀的请求表情。

    「……喂，这个。太狡猾了吧？」

    「绝对不行！我才不吃这套！我说了不打扰我可以待在这里的！」

    该说的话一个接一个在脑中浮现。

    但是……

    「稍微帮一下的话……也不是不行……」

    早已被KO的我嘴里，却只冒出了这样认输的台词。

    ※

    从那之后，辉夜的突飞猛进开始了。

    当然，作为宇宙人的辉夜，对直播之类的事情一窍不通。

    所以，她想到什么就做什么。模仿、炒冷饭、负担、害羞……这些词在辉夜的词典里根本不存在。

    宇宙人的思考方式极其简单，

    「这个视频的舞好可爱～～。辉夜也来跳跳看吧♪」

    就是这样。从想到到执行，毫无延迟。

    「唔嘻～，芦花教的方法化妆后，自拍超上镜的。好，这个也上传！顺便把完全没化好的NG版本也上传～～♪」

    芦花教的自拍是这样，

    「太好啦，真实推荐的那家店的快递送到了！紧急开播～～」

    真实推荐的吃播是这样，

    「啊——，那种事情怎样都无所谓啦！好好做个了断！忘记它！忘记可是人生最重要的能力哦！呀，我可不想成为说些漂亮话却不负责任的家伙！那就是辉夜的温柔！」

    模仿八千代的烦恼咨询也是这样。

    对于想做的事毫不犹豫。那就是辉夜的信条。

    以前，妈妈说过。阻碍梦想的最大障碍不是缺乏才能，而是缺乏主动性。

    不知道那句话是否正确，

    「好——，今天来个突袭歌回直播！穿上新衣服——，唱新歌——，舞蹈动作也没完全编好，不过就这样上啦～～」

    但至少对辉夜而言，仿佛不存在任何障碍。

    「呐——呐——，彩叶也来开歌回嘛。一起进月读世界给我伴奏～～」

    「不要。才不干。我要学习。真是的。突飞猛进固然好，但希望你在把我卷进去这事儿上多少犹豫一下。」

    「因为——」

    「你看，彩叶。我做了能同时打游戏和演奏的键盘！这样就能一边伴奏歌回一边游戏直播了。一起玩吧。」

    「不要，才不干。我要去打工了。」

    「彩叶，彩叶！今天要拍烹饪视频哦。是打抛饭。你只要出镜吃就行了，跟我联动嘛。」

    「不要，才不干。我要学习。」

    「彩——叶——！一起拍舞蹈短视频吧。」

    「不要不要不要不要。我要学习，要打工。」

    「呐呐，来嘛。一分钟就好。芦花也说一起哦。对吧，芦花？」

    「嗯，听起来很有趣嘛。真实也来吧？」

    「来来来——。彩叶呢——？」

    ……你看，变成这样了。

    我早就知道会变成这样才不愿意的。我就知道总有一天会拒绝不了。辉夜那拉人入伙的能力简直是黑洞级别的。

    「拍好啦——！快看快看，彩叶超可爱的。好，这个也立刻上……」

    「好，打住。这个绝对禁止上传。」

    就这样，在学习和打工构成的铁壁日程中，“辉夜·彩P”的直播活动不知不觉间强势切入，随着日子一天天过去，逐渐吸引了听众们的耳目。暑假过半时，排名已经提升到了二百八十位。作为默默无闻的超级新人，算是大放异彩了，但是——

    「还远远不够！到底该怎么做啊——！」

    贪心的公主殿下看来完全没满足。她趴在沙滩铺开的野餐垫上，滚来滚去，用可见的形式表达着不满。

    「啊啊～想要赢！！」

    辉夜、芦花、真实和我四个人一起来到了海边。不知何时，辉夜和芦花好像一起去买了泳衣，辉夜是人生（或者说宇宙人生）第一件泳衣，芦花似乎是新买的。真实和我穿的是去年那套。

    「辉夜，别闹了。」

    难得芦花给做的造型，可不能弄乱了。宛如将倾注而下的阳光直接披在身上的橙色泳衣，配上扎成双马尾、富有光泽的金发，让辉夜看起来像在海边闪耀的另一个太阳。我的泳衣是淡绿色的分体式，挂脖款。芦花给我扎了个外翘的高马尾，确实觉得这个发型和这套泳衣很配。话说回来，去年买的泳衣今年还能穿真是太好了。为了这种一年也就穿一两次的衣服，我选了允许范围内的、尽可能便宜的价格，但即便如此也是咬紧牙关才买的。你还得再给我努力几年啊……

    「不过前几天那个歌回真的很棒呢。」

    「对吧，辉夜酱游戏和唱歌都很厉害呢。」

    啊啊，别太宠她了，真实、芦花。

    「那是当然。我可是天才，歌姬哦。」

    你看，得意忘形了吧。辉夜那翘起的鼻子简直要戳穿积雨云了。

    「原创曲也很好呢。」

    「我懂我懂——。那是彩叶写的吗？」

    「彩叶，长得可爱还是天才，太过分啦～」

    哎呀，两人的称赞转向我这边了。真实穿着似乎是去年和男友一起买的、带荷叶边的格纹露肩上衣配水蓝色喇叭裙款泳衣，胃口好得不像会夏乏，正吸溜着第三盘炒面。芦花是像她在月读世界里的虚拟形象那样的粗三股辫，配黑色连体式泳衣。从前胸绕过肩膀延伸到后背的双色大荷叶边显得很成熟，很适合芦花。去年她穿的是大小姐风的白色分体式泳衣，披着雪纺披肩。那套也很适合，不过她果然穿什么都好看啊。芦花已经给其他三人都做好了发型，现在正勤快地给真实编头发。看起来是把编发盘成丸子头，似乎挺费功夫的。

    「啊，那个是以前写的啦……」

    我把视线从坏笑着的闺蜜们身上移开，却被凶猛的阳光刺痛了眼睛。不由得把原本搭在头上的运动太阳镜戴回正确的位置。

    海浪声、海潮的气息，还有在耀眼的阳光下进行的、一如往常的无聊对话。夏天的海，对耳朵、鼻子和眼睛都是一种享受。硬是挤出时间来这里真是对了。这个被学习、打工和直播活动填满的暑假里，仅有的一天的玩乐时间。为了挤出这一天，不知道牺牲了多少睡眠时间，还是别提了。要说感觉不到疲惫那是假的，但如果真累倒了，快乐的时光就会变成痛苦的回忆。反倒更加绷紧了神经。

    ——真正的精英连玩乐也不会敷衍！只满足于工作的人根本不够格。

    倒不是真的相信妈妈的话，但答应芦花和真实的邀请真是太好了。……那时的妈妈，看起来很开心呢。

    「呜啊——。但是，果然还是想夺冠啊！这样还远远不够啦——」

    吵死了。别在满足的人旁边闹腾，宇宙人。

    「芦花～该怎么办才好～？」

    「嗯——，你们好像已经做了不少了呢。」

    辉夜和芦花脸贴着脸，一起窥视着智能手机的屏幕。辉夜在识别能让她撒娇的对象这方面，简直是一流的。

    「好啦好啦！我有个好主意。让彩P首次亮相的直播怎么样？一直隐藏身份的彩叶终于揭开面纱，借此引发新的需求……」

    「驳回。」

    真实还没说完，我就把她高高举起的手拉了下来。

    「诶——，为什么啊——」

    「什么为什么，我绝对不参与直播。」

    「诶，你不是已经出镜了吗？这个狐狸布偶装是彩叶吧？」

    ……呃。

    真敏锐啊。点缀着贝壳碎片的芦花的美甲，正轻轻敲击着智能手机屏幕上的缩略图。

    是的。其实，被辉夜硬拉着，我已经出镜过好几次了。但、但是，只是作为气氛组，也没说话，还穿着布偶装，所以算安全……吧。

    「总、总之，我不出镜！」

    到了这一步，只能大声说话了。我使出在活动会场打工学来的腹式发声法，坚决地说了NO。

    「不要嘛——！一起出镜啦——！还要写新歌——！还要伴奏——！」

    真是任性啊。为什么对着正在拒绝的人，还能追加两个要求？

    「………呐，彩叶」

    糟了，来了。我察觉到辉夜即将发动超必杀技，立刻绷紧了腹部。

    「这样下去，赢不了啊……」

    来了，来了。就算发出这么可怜的声音我也假装没听到。

    「救救辉夜嘛……」

    就算用泪汪汪的眼睛盯着看我也装作看不见。

    「希望彩叶，为我伴奏……」

    绝对不要。

    来，说吧，我。三、二、一、嗨！

    「那、那个，有空的话……就帮一下……」

    「太好啦——！要更多更多地直播啦——！」

    可恶。为什么，我说不出口。为什么，拒绝不了。

    ——别轻易答应别人的请求。彩叶，你想被人怜悯吗？

    「太好说话了——」

    「太好说话了呢。」

    仰天高举拳头的辉夜和蹲在地上紧握白沙的我，望着这样的对比，真实和芦花绽放出花朵般的笑容。喂，这可不是好笑的事。

    「彩叶，你变开朗了呢。」

    ……诶，真实？

    「你之前一直是看起来随时会消失的感觉呢。」

    芦花也是。

    「辉夜酱，你用了什么魔法啊。虽然有点不甘心，但好像真的有点想给你们加油了。」

    芦花一边用复杂的目光看着在浪边玩水的辉夜，一边将头发向后撩去。诶，难道……

    「一起联动吧。」

    「好啊～」

    美容系网红『ROKA（粉丝数十七万）』和美食网红『真实真实（粉丝数十二万）』，和辉夜……？

    「快看快看，彩叶——！螃蟹，在岩石区。我要抓好多好多，组建军队！」

    现在是干这个的时候吗？啊，她又该得意忘形了吧。

    而这位宇宙人小姐，果然还是对眼前想做的事乐在其中。

    ※

    有了两位人气网红的支持，“辉夜·彩P”的受关注度直线上升。

    但对我来说，只不过是回到学习和打工的日常而已。

    另一方面，辉夜的直播热情似乎也爆棚了，以前所未有的高频率上传着超辣食品试吃视频、一口吃掉惠方卷挑战、自制塑料瓶巴祖卡火箭发射视频之类的……奇怪视频。

    不打算正经开个歌回之类的吗？问这种话我就输了。

    「那，彩叶来伴奏？」

    肯定会这么回我。但是，就算保持沉默，

    「彩叶，今晚的晚饭是炖牛肉哦～顺·便·说·一·下，如果明天的歌回彩P能伴奏三十分钟的话，就升级成炖了一百五十个小时的炖牛舌哦……怎么样？」

    她又会提出这种人类根本难以拒绝的交易。话说炖一百五十个小时的话，至少今天的晚饭是赶不上的吧！

    真是的，明明是个宇宙人，是不是适应得太快了？哪有这么阳光的辉夜姬啊。

    「大家——，今天的歌回久违地有彩P来伴奏哦——。气氛热烈的话，说不定会把布偶装脱掉哦，所以大家要好好炒热气氛哦——！」

    别随便加MC。这个我绝对不会脱的。

    不过，为辉夜的歌声伴奏确实很开心……即便如此，娱乐果然还是不适合我。像这样作为幕后人员，从旁边看着唱歌的辉夜，对我来说就刚刚好。

    「大家——，喜欢辉夜吗——？」

    辉夜，是闪闪发光的。在辉煌璀璨的月读世界中，她也格外耀眼，让看到的人都为之着迷、被俘虏。虽然绝对不会对本人说，但我觉得她就是为了成为偶像而出生的。偶尔和我对上视线时，

    「彩叶，今天想吃什么？」

    集中精神啦。看，间奏后的进拍失误了。

    「诶嘿嘿，搞砸啦☆ 说不定反而成了神回？」

    ——真是狡猾。

    顺带一提，芦花和真实似乎完全被辉夜拉拢了，三个人经常聚在一起搞游戏直播。当然，辉夜对游戏一窍不通，所以就是，

    「芦花～，真实～，教教我？」

    这种情况。

    没来问我，大概是辉夜式的体谅吧。我会心怀感激地努力学习，但我们住在一个单间里，怎么都能听到直播的声音。

    「现在流行的，毫无疑问是『KASSEN』！虽然是能在月读世界玩的游戏，但也有个同名的模式，那是七对七的大逃杀！今天要玩的是叫SENGOKU的模式，基本是占地对战……哇，抱歉，死了。」

    诶，难道是一边玩一边听说明吗？KASSEN不是那样的游戏吧。

    「啊——我也死了。」

    「诶——，芦花也？」

    我就说吧。嘛，虽然跟我没关系。

    「糟了糟了！这也太卑鄙了，我们这边只有辉夜一个人。呜哇——，地狱啊。喘不过气。这个，哪个是攻击？哪个是攻击？告诉我啊。有什么出来了。哇——，赢了。」

    这都能赢？太乱来了吧。

    「噢——！」

    「辉夜酱天赋很好嘛。」

    所以说，别太宠她了嘛。嘛，虽然跟我没关系。

    因为没关系，所以第二天我也用能量饮料驱散睡意，埋头学习时，

    「彩叶！救命！」

    突然被人从背后抱住，吓得半死。什么啊，到底怎么了。

    「再这样下去，辉夜不结婚不行了。」

    我才稍微没看着，发生了什么啊。

    「就、就是——，本来是做创意料理的直播来着——。求婚的评论蜂拥而至嘛——。嫌麻烦就说了赢了游戏就行啊——，结果现在被逼得走投无路了。彩叶替我打——！」

    「不不不，这进展也太快了吧。」

    「不要。」

    「『SETSUNA』！」

    那是KASSEN的对战格斗模式。一对一战斗，先取得对方两条体力条者胜。

    「第一条瞬间就被拿下了，第二条也……啊，快死了。」

    「你现在正在对战吗？！」

    糟了，不自觉地握住了手柄。不对。这只是因为看不下去而燃起的游戏玩家之魂，绝对不是想阻止辉夜结婚……

    「彩叶，你刚才说什么？」

    「什么都没说！看招，六十八连击！」

    彩P以怒涛般的二十八连胜横扫听众，引发些许争议的同时，结束了这场闲聊直播。好了，继续学习。有意见的家伙尽管放马过来。

    就在这一阵忙乱中，“辉夜·彩P”在八千代杯的暂定排名不断攀升。随之而来的是，

    「唔嘻嘻嘻，fuju～有这么多。唔嘻嘻嘻。」

    粉丝们慷慨的“布施”。

    而且fuju会通过智能隐形眼镜检测用户的心率和脑波，判定情绪向积极方向波动时，就会由运营方支付。这说明我们打动了很多人的心，但是……

    「唔嘻嘻嘻，金币银币哗啦啦地掉～～」

    这个宇宙人，得意忘形得太明显了吧。

    「那个，辉夜。这种说到底只是不劳而获，来得快去得也快哦。」

    虽然我姑且提醒了一下，

    「但是～～，这是合法的嘛～～？」

    话是这么说，但总觉得火大～

    「至少把房间收拾一下吧。」

    直播用的破烂玩意儿简直是在疯狂增殖，希望你能想想办法。这个四叠半的公寓，别说落脚的地方了，连呼吸的空间都快没了。

    「诶——，不可能啦——。这个房间太窄了嘛。搬家吧，我找到了不错的房子。」

    「你是认真的吗，那个……」

    「超认真！啊，不过，在那之前——时间到了哦，彩叶。」

    「啊啊……嗯。」

    我知道，当然知道。倒不如说，几个小时前开始，我几乎就只想着那件事。

    「首先是彻底打扫！噢啦啊啊啊！」

    辉夜像推土机一样把破烂堆到墙边，总算确保出了两人的空间，然后对着我比了个剪刀手。那才不叫打扫呢。

    之后，辉夜换上了方便活动的衣服，从热身操到发声练习，然后跳着谜之舞蹈打气，

    「那么，走吧，彩叶？」

    她露出了乐不可支的笑容。

    今天是辉夜的首次个人演唱会。不是往常的歌回直播，而是预订了月读世界内的现场演出场地，打了广告，雇了工作人员，请了观众的正儿八经的音乐会。

    「……我真的也要去吗？」

    伴奏是辉夜强烈要求的——彩P。

    可以穿布偶装，也明确支付了酬劳，所以我连打工都请假了，但是，我真的可以吗？辉夜纪念性的首次舞台，旁边站着我这样的人。

    辉夜像是要融化我的不安一般，越发灿烂地笑着，

    「来啊。彩·叶！」

    她伸出了仿佛要戳人眼睛的剪刀手。我怯生生地也伸出剪刀手，指尖相碰后互相勾住。然后来个狐狸之吻。这是辉夜构思的握手暗号。记忆方法是：

    「剪刀手之后～，勾手指之后～，亲亲！」

    就是这样。

    「辉夜和彩叶的暗号。是好朋友的暗号♡」

    好像是这样。虽然有点难为情，但紧张感稍微缓解了一些。

    手指相勾着，我们俩同时潜入月读世界。睁开眼，一直陪伴我们的狗狗DOGE精神十足地迎接了我们。

    辉夜，到底会走到哪一步呢。我，又为何会站在她的身旁呢？

    「马上开始了，倒计时五秒！」

    工作人员发出信号。

    幕布升起。

    狂热扑面而来。

    我感觉窥见了八千代所见风景的一角。

    ※

    「彩叶，这边这边♪」

    辉夜的首次个人演唱会，在盛况中落下了帷幕。

    SNS上直到几天后的现在，仍然好评如潮。被这股能量推动一般，“辉夜·彩P”的排名急剧上升，借着这股势头，辉夜把我带了出来。

    「陪我买东西」，她这么说着，挽住我的胳膊，兜兜转转绕了无数远路后，蹦蹦跳跳把我带到的目的地是——

    「诶，房产中介？」

    「呐呐，这里怎么样？」

    别把找房子算作购物啊。辉夜用没涂指甲油的食指指向的，是房产中介在主干道上大张旗鼓张贴、充满自信的头牌房源。

    〈品味极上空间的豪华设计师公寓塔楼　3LDK　月租三十五万日元〉

    ……我一阵眩晕。住在这种地方，人都会变得不正常的。

    「有什么不好嘛～。辉夜来出钱好啦～。你看，虽然是公寓却有二楼哦。二楼是辉夜的直播室兼卧室，一楼彩叶可以自由使用。呐，不错吧～。有挑高空间，整体厨房带食品储藏室还有阳台！而且，是顶层！」

    我又要晕了。既没有担保人，这种地方怎么可能租给我们这种小丫头片子……

    再次感到晕眩。总之，先试着把辉夜从房产中介门口拉开……咦，脚下发软。奇怪了。视线也扭曲了。站不住了……不会吧，这可不是看房子看晕了……

    「嗯？彩叶，你蹲下找什么呢？」

    回过神来，我已经膝盖一软，无意识地蹲了下来。

    「没事吧？彩叶，身上好烫啊？」

    冷汗止不住地流。辉夜担心的声音听起来异常遥远。

    再次清醒时，我已经躺在平时房间的、平时的被窝里。

    为什么，会在家里？从房产中介到家的记忆完全空白。难道说，是辉夜把我搬回来的？力气真大。不，那家伙有钱，大概是叫了出租车……

    我小心翼翼地转过头，看见了站在厨房里的辉夜的背影。

    ……头发，长长了呢。笔直的金发长得快要遮住臀部了。第一次在这里吃蛋包饭的时候，还只是到背部的长度……嗯？

    「不对！糟了……打工！」

    我慌忙想爬起来，身体却像被被子粘住了一样动弹不得。

    「彩叶，你好点了吗？」

    「没、没事……我这就起来……」

    我对着跑过来的辉夜逞强道，但身体果然不听使唤。这次可能真的有点勉强了。至少得请假……

    「打工那边我已经帮你请假了哦。彩叶，再休息会儿吧。」

    ……诶，辉夜帮我请的？

    「还有，我给你放了好多软乎乎，好好享受软乎乎吧。」

    「软乎乎？啊，软乎乎啊……」

    我用模糊不清、如同蒙上雾气的视线环顾四周，看到精心挑选的软乎乎玩偶们包围了被褥。

    ……谢谢。

    我抱着一个玩偶轻声说道。没想到，辉夜会为我考虑得这么周到。坦率地说，我很开心。

    「啊，对了！医院！去医院吧，一起。」

    「诶，医院？……不，要花钱的，我不要。」

    「那种事，包在辉夜身上！」

    辉夜握着汤勺的左手比了个展示肌肉的动作。但是……我抱住玩偶的手指，深深地掐了进去。

    「果然，还是不行……」

    烧成这样，搞不好要住院的。那样的话，

    「我的日程都排得满满的……如果休息好几天，就再也追不上了……那样的话，奖学金……可能也拿不到了……」

    是因为身体虚弱吧，糟糕的想象不断连锁。明知是杞人忧天，却停不下来。

    「彩叶……」

    辉夜用湿润的眼睛望着这样的我，

    「为什么彩叶，必须一个人这么拼命呢？」

    她用一种我从未听过的、微弱的声音低语道。

    「呜，呜呜……是辉夜的错吗？辉夜也提了很多无理的要求……要是彩叶死了，辉夜不要啊～～！」

    不是吧，哭了？眼看着辉夜的大眼睛里迅速蒙上一层水膜，泪水仿佛要冲走眼球般流下。之后就是洪水了。从所有能出水的地方涌出了各种液体。

    「哦，太夸张了……死不了的啦。」

    「可是，电影里人类不是动不动就死掉吗！然后变成丧尸重生转生踏上宇宙之旅……哇——，辉夜不要彩叶走掉——」

    「你到底把多少部电影混在一起了啊，都说没事了。」

    情感丰富的辉夜，哭成这样可能还是第一次。

    看来，今天学习也暂时停一停吧……

    为什么反而是我这个病人，在安抚作为看护人的辉夜的背时，会这么想呢。

    『为什么彩叶，必须一个人这么拼命呢？』

    止住哭泣的辉夜，重新这样问我。解释这件事非常非常困难。尤其是发着烧头脑昏沉的时候。要从头开始好好说明的话，就绕不开和妈妈的话题。

    「嗯——，唔～～～嗯……」

    看到我沉默不语，辉夜欲言又止，反复了好几次。原来宇宙人也有烦恼的时候啊。看到她这副样子，我反而觉得有点好笑，心情稍微放松了一些。我对着在身旁抱膝而坐的辉夜，断断续续地讲了起来。

    去世的爸爸的事，离家出走的哥哥的事，变得陌生的妈妈的事，被“正确”压得喘不过气的我的事。如果是妈妈，一定不会像这样生病倒下吧。

    ——身体管理是万事的根本。在这里就跌倒的家伙，比任何蠢货都不如。

    实际上，我从未见过妈妈感冒。妈妈比任何人都正确、强大、完美，在她看来，我一直都缺少些什么。

    所以我也选择了离开。我认为只有完美地、一个人沿着妈妈做过的事、走过的路，一丝不苟地走一遍，我才能第一次和妈妈平等地相对。

    「……就这样，最后总算达成了协议，条件是我独自承担学费和生活费。」

    「你说得倒轻巧，一般人不是都不这么干吗？」

    辉夜在旁边皱起了眉头。

    「妈妈都能轻松做到，我也不愿让步。我还清楚记得刚在这里醒来那天的事。虽然一无所有，无人可依，但想到要靠自己的力量活下去，就涌起了力量。感觉像是一种……幸运？」

    那天，确实是个神清气爽的早晨。在安静的房间里，终于可以从这里开始了。

    「不不不，才不是什么幸运！就算用宇宙人的标准来看，那个妈妈也绝对有问题！」

    辉夜说得对。如果我是听故事的一方，肯定也会这么想。

    但是——

    我又掐紧了玩偶。

    「对辉夜来说……」

    「诶？」

    「不，没什么。」

    我为什么要说这些啊。看来烧得确实不轻。

    「……这样啊。那，吃完饭、吃完药就睡觉吧。」

    辉夜这么说着，啪嗒啪嗒地跑到厨房，回来时则端着托盘，脚步小心翼翼。

    「今天的菜单是葱味噌姜丝和鸡蛋粥。首先把柴鱼片、切碎的葱花和磨碎的姜泥拼命搅拌。然后注入滚烫的热水。因为汤底来自柴鱼片，所以调味料只需最低限度。接下来把剩饭稍微用水洗一下，投入溶化了少许基础高汤的热水中，在放入鸡蛋前，朝反方向搅拌锅子——」

    喂，我想快点吃。对病人的解说也太长了吧。

    「鸡蛋放了两个哦。很烫很烫，要呼呼地吹着吃哦。」

    「好烫！」

    鸡蛋粥正如辉夜的警告，烫得舌尖发痛，但

    「……超好吃。」

    剩下的舌头都快融化般的美味。

    「对吧～～～～？」

    啰嗦。辉夜脸上露出对病人而言过于灿烂的笑容，摆出了谜之姿势。

    ※

    『为了大家，汪汪汪！我是八千代杯官方实况解说，忠犬御宅公。今天也要精神饱满地完成任务！本周的八千代杯特辑，直到暂定第四名都要关注官方哦！你支持的人在吗？那么那么，公布前三名。第三名，治愈系偶像汤云暖！第二名，高性能精灵，泰莱莉莉·提特托特！然后，正如大家预料的遥遥领先。堂堂第一名，黑玛瑙！难道说，就要由这三人组决定胜负了吗？啊对了，圈外有个排名飙升的组合呢。大家知道——』

    「唔——，黑玛瑙压倒性领先呢～～」

    久违地四人聚在真实家。

    真实坐在单人藤椅上，停止了正在播放的月读世界官方新闻，随手把遥控器一扔。「嗯——，到后半段还差这么多，有点棘手啊。」

    横占着三人沙发、懒洋洋仰躺的芦花也像要投降般望着天花板，

    「唔——，到底该怎么办才好——！」

    原本一个人泡在浴缸里的辉夜，只裹着一条浴巾半裸着身子，挠着头。

    别惊讶这个宇宙人在别人家是什么打扮。说是真实家，但这里是虚拟空间月读世界中，美食网红“真实真实”的家。本来预定在现实世界聚会的，但考虑到我身体刚恢复，临时改在了月读世界。

    「哎呀呀，黑玛瑙，好强啊～。不过，理所当然嘛。毕竟是帝大人嘛。」

    顺便一提，房主真实是帝的粉丝，所以一个人心满意足地在自家引以为傲的钓鱼池边垂钓。

    「真实你这个叛徒～！」

    「我姑且也算把辉夜当作第二推啦～」

    「不要——！辉夜只能推我一个人——」

    「别把水弄得哗啦哗啦的。鱼都逃掉了。」

    「可恶——，帝你给我出来！来决斗——！」

    「啊，那个不错嘛。让辉夜和帝来场游戏对决怎么样？」

    「不愧是芦花，就这个了！」

    就什么啊就这个。

    「根本不可能吧，人家怎么会答应啊。对方是顶级职业玩家哦？实力差太多了。」

    「但是～！八千代杯就要结束了啊！说不定迎接我的人就要来了～！」

    啊。对了，有这设定来着。

    「要来就快点来啊～，把我带回去～～」

    「啊——，为什么要说这么坏心眼的话！」

    就是现在。月球的朋友们，现在就来接她啊。都算晚了，在磨蹭什么。

    「……嗯？辉夜酱，是筑地那边有人来接你吗？」

    「哇——，是离家出走——？」

    哎呀，不好。当着两人的面说出来了。太大意了。好，该怎么糊弄过去呢。正想着这些，

    「哇，吓我一跳！」

    辉夜的眼前突然出现了卷轴图标。是邮件。大多是垃圾邮件和广告，自从参加八千代杯以来，辉夜几乎不怎么看邮件，但是

    「……诶，这个是？」

    或许有了什么预感，辉夜立刻点开邮件，漏出了惊愕的声音。

    然后，用异常闪亮的眼神盯着我。

    「彩叶……」

    什么？

    「彩——叶——」

    什么啊，好可怕？

    「彩叶你说过的吧。职业玩家大人和我们不是一个级别的……」

    所以呢？

    「……说过吧？」

    等等，不会吧？喂，住手。我有不好的预感。那个喜欢新奇事物的男人，不可能没注意到辉夜的存在。他很可能会做这种事。所以我才没让辉夜看到黑玛瑙的相关信息。刚才也立刻试图转移话题。尽管如此……

    「那——就，没法拒绝了吧！来自资深职业玩家大人的挑战！钓到大鱼啦，太好啦！」

    「辉夜酱！鱼要逃掉啦！」

    上钩了的辉夜甩开真实的制止，裹着浴巾跳进了钓鱼池。

    『Black OnyX 帝明 发来的消息

    初次见面辉夜酱！

    我是黑玛瑙的帝明 粉丝数 一百万人恭喜！

    这里有个提议，在KASSEN来场

    帝 VS 辉夜的竹取对战

    怎么样？

    如果辉夜酱输了……就跟我结婚，怎么样？

    如果我输了，无论是什么要求我都会听听看

    我们一起来炒热月读世界吧！』

    完蛋了……。

    ※

    『万众瞩目的活动即将开始！王者黑玛瑙向以异常速度崛起的超新星辉夜·彩P宣战！并且竟是求婚！决定命运归属的KASSEN，此刻即将在月读世界特设体育馆拉开帷幕！』

    辉夜和帝的对决迅速敲定，冠以“世纪竹取对战”的大标题，出现在了我的面前。在超满员的会场中，解说席上，前职业玩家、乙事照琴和担任解说的忠犬御宅公正说着炒热气氛的开场白。

    『八千代杯的结果公布也只剩一小时了呢』

    『这场胜负的结果，或许将决定辉夜·彩P能否逆转！？』

    『规则是SENGOKU』——

    为、为什么会变成这样……我裹着平时的狐狸布偶装，呆立当场。

    上空，拥有透明躯体的巨型鳗鱼幼体——就像升腾的烟雾一样，缓慢地扭动着身体游弋。真好啊——也带我一起走吧——

    「啊哇哇哇哇……」

    我无视兴奋得快要口吐白沫的真实，深深叹了口气。顺便一提，辉夜是，

    「还——没——来——？」

    对尚未现身的黑玛瑙表示不满。一点不了解我的心情，简直过分地一如往常。

    就在辉夜准备和狗狗DOGE开始玩耍的那一刻，会场上方的岩壁爆炸了。

    『来了！黑玛瑙！』

    碎裂的岩片缝隙间，可以看到骑着虎摩托的帝正与巨大的鬼怪战斗着下落。——原来如此，今天是这种设定啊。顺便一提，虎摩托是指老虎用左右前爪抓住前轮、左右后爪抓住后轮奔跑的摩托，是骑在虎背上移动的交通工具。……听懂了吗？抱歉我也没懂。

    帝骑着虎摩托向鬼怪冲撞，在撞击前的瞬间，蹬开虎摩托跳跃起来。浮空的帝，从棍棒型武器中拔出了刀。一闪。不，是无数次。以目不暇接的速度斩击着鬼怪的身体。下一刻，鬼怪的身体爆裂开来，化作华丽的烟花在会场上空绽放。留下的，只有降落在会场的帝，以及紧随其后到来的雷和乃依。只是比赛前的余兴节目。

    会场的热情高涨。为了这个，什么都做得出来的男人。

    『黑玛瑙！驾临——！！』

    在盛大的欢呼声中，黑玛瑙的三人登场了。

    今天，我必须战胜这些男人吗……事到如今，实在没什么积极的念头。

    「哟，多谢接受对战。」

    「那、那个我、粉粉粉粉丝我……」

    帝打招呼时，怎么看都没搞清楚状况的真实凑了上去。帝瞥了真实一眼，

    「真实，抱歉今天可不能手下留情哦。」

    说着抛了个媚眼。名字大概是推测自用户名吧。被击中的真实，脸上浮现出巨大的“！？”，像陀螺快停时一样滴溜溜地转着倒了下去。……诶，倒下了！？

    「真实，没事吧！？」

    我对着倒下的真实，一张接一张地展示各种美食照片。拉面、鸡肉盖饭、印度香饭……不行，起不来。

    「呐怎么办～？」

    辉夜一边从真实的虚拟形象上揪下装饰用的饭团吃着一边问。别揪。别吃。没味道就别呸呸呸地吐掉啊。怎么办……紧急情况不好意思，只能拜托芦花了吧……喂别连菠萝面包都拿走啊。

    正这么想着，一个巨大的玉手箱从天而降。这、这难道是……！

    「锵锵——！我来了——？」

    八千代……是八千代……！从玉手箱里嘭地跳出来，穿着适合战斗的清爽服装的八千代出现了。

    「诶诶诶诶诶诶诶诶诶诶诶诶！？！？」

    「诶嘿嘿，一定要赢哦。」

    八千代可爱地摆了个姿势，粲然一笑。

    不妙，我有点想赢了。

    『比赛开始！』

    法螺号角鸣响，与黑玛瑙的KASSEN终于开始了。

    SENGOKU模式是三对三的三局两胜制，是黑玛瑙的拿手好戏。

    圆形的KASSEN舞台大致左右一分为二，右端是A队的据点天守阁，左端是B队的据点天守阁。双方从己方天守阁的幕营地出发，看哪一队先攻陷对方的天守阁。

    左右天守阁之间有三条路线，分别是上方的上路（Top Lane）、中间的中路（Middle Lane）和下方的下路（Bottom Lane）。

    对方的天守阁并非一开始就能攻陷，需要前往位于上路和下路的箭楼，击败中BOSS牛鬼并占领。己方队员占领箭楼后，敌方天守阁前会出现大将落石，将其打入天守阁即可获胜。也就是说，队员需要分为以天守阁为目标的和以夺取箭楼为目标的两组出发，与队友配合高效地攻陷箭楼，在大将落石出现的瞬间形成能打入天守阁的态势，是为理想。

    命——简单来说，机会有三次。己方占领任一箭楼后，己方天守阁会出现跳台，即使阵亡也能通过跳台在十秒左右抵达被占领的箭楼。

    地面上配置了无数的中立小兵，不仅需要应对敌方玩家，还需要处理这些。受到小兵攻击会减少HP，反之，打倒小兵积累能量槽后，便能使用必杀技（Ult）。打倒小兵也需要时间，所以也可以无视，但尽可能打倒小兵、连发必杀技打开局面也是一种方法。这方面很大程度上取决于局势和玩家的偏好。

    那么，我骑着巨大的黑色苍鹰，辉夜则点燃了她武器大锤的喷射引擎骑在上面，前往上路。八千代乘坐着逆戟鲸巴士担着的神轿——通称逆戟鲸神轿，前往下路。首先是按常规战术，两人和一人分头进军。

    KASSEN中偶尔会出现的助战八千代，其能力基本上会随着对战双方队伍的实力差而上下浮动。这次我和辉夜比黑玛瑙弱，八千代的能力应该会得到增强。她是独自一人存活可能性最高的。

    战前作战会议时，队长辉夜给出了

    「嘎——地冲过去！唰唰唰——！然后砰！！」

    这样宝贵的作战方案，所以我先通过地图位置信息观察黑玛瑙的动向。这是……

    『哦——！黑玛瑙是三叉戟战术！是三叉戟战术！』

    上、中、下三条路线各派一人进发的战术，三叉戟。需要同时应对多名敌人，没有在一对多局面下也能全歼对手的自信，是不会选择的打法。

    「完全被小看了呢。」

    「诶诶～～～？」

    下方飞来无数箭矢，我和辉夜解除了飞行模式开始下落。用于移动的载具分为高速飞行型和地面行进中速型，高速型前进到一定程度会受到地面上无数小兵的总攻击，所以必须降落。中速型则没有特别限制，可以一直骑乘。我和辉夜的载具是高速型。八千代的逆戟鲸神轿和黑玛瑙的虎摩托是中速型。

    一边清扫着落点附近的小兵一边下落时，听到了枪声。来了！我停止攻击小兵，以最快速度躲到附近的岩石后面。瞄准这边的枪声越来越近。我将武器的双剑两端连接变形为回旋镖，从岩石背后掷出。趁着对方躲避的间隙，我冲了出去！用预埋的金属线瞬间回收被躲开的回旋镖，变形成单手剑，斩了过去。对方也瞬间反应，进入了刀刃相抵的状态，火花四溅。

    「是你吧，彩叶。」

    「不是。」

    是帝明。在月读世界里，想不听他的活跃事迹都难，但像这样交谈，是几年来的第一次呢。

    从我背后发射出鳗鱼形的炮弹，瞄准了帝。是辉夜的鳗鱼炮。帝解除了和我僵持的状态，回避了。

    「彩叶——！」

    「啊，喂！」

    别说出来啊！——呜呃。

    一瞬间看向辉夜的破绽，被帝的棍棒砰砰敲了几下。

    「这身装扮打起来真方便，帮大忙了。就这样输掉不后悔吗？动真格吧。」

    必须要出镜了吗。这件布偶装被击判定范围太大了。我下定决心，脱掉了布偶装。

    「果然，是彩叶嘛。」

    「你怎么知道我的虚拟形象的？」

    「哥哥我什么都知道——不是吗？」

    一边说着话放出的攻击，也被对方一边说着话躲开了。

    「诶，哥哥！？」

    一直配合着我进行攻击的辉夜停下了手，用惊愕的表情看向这边。

    『哦——！惊天大爆料！帝和彩P原来是兄妹！？』

    夸张的解说声传入耳中。会场的骚动一清二楚，但已经无法回头了。帝——酒寄朝日。一边与兄长交战，一边接近箭楼。八千代在下路和乃依对峙中。

    「话说妈妈挺担心的哦。好歹联系一下嘛。」

    「我这边也有先后顺序的！」

    「呜呀啊～～！呜哇啊」

    「那也是妈妈教的吧？就是因为你什么都当真，关系才这么僵。妈妈她可是在等你反抗呢。」

    「不知道！别管我！」

    帝把语音聊天从直播用切换成内部通话用，一边说教一边攻击。中途被反击打得晕头转向的是辉夜。真想好好反驳一下，但转眼间帝就已经抵达了牛鬼身边。我想抢先打倒它，但是

    「啧！」

    「嘎啊～～」

    被破坏地图产生的瓦砾干扰，无法随心所欲地行动。帝从棍棒中拔刀，发动必杀技进入超加速状态。瞬间击破了牛鬼。

    「给我再努力点啊，像我这样。」

    帝把语音聊天切换回直播用，伴随着招牌台词抛了个媚眼。那游刃有余的态度让人火大，但手法确实无可挑剔。

    『瞬杀～～！』

    可恶。箭楼和牛鬼之间还有一点距离。必须在帝占领箭楼前追上他。

    『下路的八千代也击破了牛鬼！』！八千代……！

    『哦——！乃依的反击！是减速连射！八千代动不了了！』

    『虽然是很微小的技能，但停不下来！』

    不妙啊。就算是八千代，不去帮忙的话，也会一直在地上爬行吧。但是，现在不阻止帝的话……！如果一个队伍同时占领了两座箭楼，比赛就会瞬间告负。

    「呜！乃依酱，目的是拖延我吗～呃啊」

    『乃依占领了箭楼！』

    听到解说宣布下路箭楼被占领的同时，地图上八千代的标记消失，我知道她也被乃依击败了。

    「形势立刻急转直下！好痛！」

    「动作太直白了！果然如此！」

    「呜诶！虽然想去但是……」

    我处理小兵分身乏术的间隙，辉夜被帝击倒了。我立刻斩了过去，但是……

    『三叉戟战术状态下同时占领两座箭楼，瞬间结束比赛！干净利落！』

    ……第一局，就这么稀里糊涂地结束了。毫无亮点。

    「对不起～，我一直像鼻涕虫一样。」

    「哪里哪里，八千代是最强的啦……」

    本来应该是人数占优的我和辉夜击败帝、占领箭楼，然后让八千代去攻陷天守阁的。因为我们苦战，八千代才去夺取箭楼，结果被钻了空子。是我的错。

    「呵呵呵……」

    我垂头丧气，辉夜却望着天空，发出像反派一样的窃笑。

    「呐，帝这个人啊……」

    ……这次又要陪她干什么啊。

    『第二局开始，黑玛瑙理所当然地继续三叉戟战术！』

    和刚才一样，我和辉夜前往上路。八千代前往下路。发现骑着虎摩托的帝，斩了过去。

    「辉夜姬呢？」

    「回月亮去了哦。」

    地图上，我和辉夜显示在同一个位置。但在帝的视野里，应该只看到我。帝一边和我交锋，一边大概在思考：『用锤子的辉夜应该没有潜行技能』。

    「啊，在上面吗！」

    「哟。」

    在空中骑着鳗鱼幼体的辉夜启动了锤子的喷射推进，朝下路飞去。

    『在一定高度以上飞行，可以规避地面的迎击！』这是刚才辉夜告诉我的。

    「雷，去上路！支援！乃依有危险」

    趁着帝的空隙，我径直向箭楼移动。辉夜，拜托了……！从语音聊天里听到了几次她们与乃依交战的声音后，

    『辉夜，占领箭楼！』

    『这是利用了2D地图没有上下信息的搅乱战术』

    『说给她菠萝面包就让她骑什么的ww 第一次听说呢ww』

    连我都不知道这种事，正发呆时，视野咕噜地旋转了。

    意识到自己被钻揉状击飞并受到了帝的攻击，转眼间箭楼就被占领了。

    「就差一点了呢。」

    我只能怒视着如王者般俯视的帝。

    在己方天守阁附近重生后，辉夜得意的语音聊天立刻传来。

    「……抱歉。」

    开口第一句，不由自主地变成了道歉。

    「没关系！绝对会赢回来！」

    「彩叶！虽然很帅～，但八千代和辉夜也在哦！依靠我们吧——♪」

    八千代的声音立刻接上。不过，就算我用最快速度赶去，也来不及在分出胜负前抵达。我已经无能为力了。

    「……要赢！」

    「谨遵您的吩咐～～～☆」

    辉夜和八千代与帝交战，然后，

    『什么——！辉夜彩P队扳回一城！辉夜的奇策奏效了！』

    「好耶！」

    我茫然地观望着八千代和辉夜的击掌。……真的赢了一局呢，在对黑玛瑙的比赛中。

    ……辉夜，好厉害。

    这句话，不经意地脱口而出。根本没想过要说出来的话，却被辉夜的地狱耳敏锐地捕捉到，她顿时笑逐颜开。

    「因为想和彩叶一起赢！」

    『激战！双方各自占领箭楼，辉夜彩P从跳台前往箭楼！』

    『等待着的是与帝的单挑对决！』

    第三局。雷和乃依交给八千代对付，我和辉夜前往帝的所在。

    「真慢啊。」

    「为什么来这里？从中路直接去天守阁的话，不就赢了吗？」

    「黑玛瑙啊，必须让大家看到梦想才行哦。」

    停止对峙，我与帝激烈碰撞。辉夜和我的配合比第一局时默契多了。即便如此，还是差一步无法彻底压制。

    ——爸爸去世后，哥哥待在家里的时间变多了。一直踢着的足球也不踢了，在家里不是看书就是打游戏。我和妈妈一有争执，他就会立刻过来挡在我前面。明明性格原本应该是更傲慢、更鲁莽的捣蛋鬼才对，却变得安静温和。简直，像爸爸一样。

    不知不觉间，哥哥喜欢上了游戏，成了职业玩家，去了东京，家里只剩下我和妈妈两个人。我知道他用“明”这个名字活动，所以偶尔会看看他的直播。撇开各种事情不谈，我喜欢看哥哥活跃的样子。哥哥开始在月读世界以帝明的身份活动，我认识了八千代，之后一直受到八千代的支持——在这期间，哥哥也一直在磨练技术。

    赢不了啊。这句话如同积郁的叹息般吐了出来。

    嘎啊～地发出怪声，辉夜滚到我旁边，又立刻站了起来。

    「可——恶——！但是要赢！」

    辉夜眼中闪烁着光芒，笑了。……我稍微想起了以前和哥哥一起打游戏时的事。

    「如果我们赢了，你会听我们的要求吧？」

    确认帝点了点头后，我和辉夜分头跑开。登上高地，从空中发起攻击。我手中握着辉夜的大锤。辉夜手中拿着我的双剑。

    「交换武器！喝！」

    我们一边围绕着帝画圆般投掷并交换武器，一边破坏立足点，将帝逼到了柱子前。就是现在！我将连着金属线的双剑一半用力刺向帝的背后。金属线另一端的锚刺在辉夜的大锤上。

    辉夜为了攻击帝而挥空的大锤，深深砸进了地面，正努力想拔出来——她在演戏。

    实际上是把大锤固定在地上，用力按压防止锚脱出。

    『因为辉夜一直只顾自己猛冲、完全不管彩叶，帝肯定以为她是个‘独狼’玩家！』

    辉夜总是仔细观察对手，为了获胜，出奇制胜。

    『想和彩叶一起赢！』

    非常聪明，而且强大。

    「游戏结束了哦。」

    就在帝要给辉夜致命一击的那一刻。我拔出刺在柱子上的双剑，将一直绷紧的金属线猛地卷回，束缚住了帝。

    「大锤上连着线……？诱饵是辉夜酱！」

    作战方案相当粗线条，大半是边打边想的。但是，我们可是连辉夜的尿布都换过的交情——

    「辉夜想什么，我还是知道的啦！」

    我挥下的剑，将帝一刀两断。

    「……这不是能做到嘛。」

    哥哥仿佛从一开始就在期待这个结果般，平静地笑了。

    ……明明之前说了那么多煽动的话，突然摆出这种态度，我都不知道该怎么办了。

    确认了帝的声音后，我高兴地跑来的辉夜交换了握手暗号。

    乘上载具，向天守阁进发。八千代和雷、乃依同归于尽了，所以现在存活的只有我、辉夜和帝。帝刚从重生点出发，顺利的话应该不会被逆转。

    「彩叶有危险的话，辉夜来救！」

    「辉夜失误的话，我可会丢下你不管哦。」

    「为什么！？」

    「啊哈哈。」

    不知为何觉得好笑，我笑了起来。看到我笑，辉夜眼中含泪，高兴地看着我。……奇怪的家伙。

    两个人一起的话，哪里都能到达。我有了这样的感觉。

    『帝也向着辉夜队的天守阁进发！』

    「接下来就看好了！辉夜要大显身手！」

    我一边驱散小兵，一边守望着登上天守阁的辉夜的胜利——

    「呜诶——，赢定啦——！……呃。」

    本该如此，但辉夜伴随着火焰被炸飞到了空中。嗯？爆炸？没爆炸？

    『啊——！雷设置的地雷陷阱——！』

    因为雷留下的“礼物”，辉夜轻易地失去了最后一条命。不、不会吧！那个笨蛋！理解状况的我急忙想冲上天守阁，但是，

    『帝在加速！』

    最终，使用必杀技超加速的帝扫清一切障碍，以爆破般的速度抵达，

    『逆转——！胜负已分。胜者，黑玛瑙——！！』

    最后在天守阁高举拳头的，是黑玛瑙的领袖帝明。

    ※

    「啊——！输了！输、输、输、输掉了啊啊啊！」

    「喂，辉夜冷静点」

    辉夜敲打着地板、墙壁、自己的头、脚、肚子，所有能敲的地方，痛苦地扭动着。不甘心我理解，但别打自己啊。

    「但是但是，输掉了啊！是辉夜和彩叶却输掉了啊！好不爽又好开心！」

    最后那句说了什么？我好像清楚地听到了“好开心”和“好不甘心”的混合。

    「彩叶，辉夜，辛苦了！就差一点了呢～～，八千代也又爽又不甘心☆」

    「住手，八千代。这个梗流行不起来的。」

    「但是呢，两位。可没时间垂头丧气哦。因为接下来就是万众期待的公布时间了。」

    ……公布？

    「没错，小丫头们！」

    空间泛起黄色的波纹，从中飞出的fushi跳到了八千代的肩上。

    「你们忘了八千代为什么要来助阵吗？就是为了把这场活动的人气维持到投票截止前的最后一刻！」

    「投票……对了，忘了。」

    「别忘啊！」

    抱歉，fushi。其实我也忘了。对啊，这场KASSEN的本来目的是——

    『真是辛苦你们了～～☆』

    刚才明明还在眼前的八千代，已经高高地漂浮在上空。数道聚光灯捕捉到了她优雅地、如同鳐鱼般在空中游弋的身姿。

    『KASSEN非常非常开心呢。然后，就在刚才！八千代杯的投票截止了哦～。fushi麻烦统计！』

    『好～的。一、二、三、四、五、六、七、八……叮！统计完毕』

    『那么，就来公布要和八千代合作的人吧！』

    八千代接住了从fushi嘴里噗地吐出来的卷轴。

    同时，夜空中出现了巨大的屏幕。在全体月读世界用户的注视下，柱状图开始延伸。接着，以惊人的速度从下往上依次公布参赛主播的名字。

    『八千代杯的优胜者是～～☆』

    八千代精神饱满地试图炒热公布气氛，但结果对大多数用户来说早已一目了然。只是等待绝对王者加冕的确认程序。

    然后，那个谁都预料到的名字，被刻在了屏幕上。

    ——第二名　黑玛瑙　新获粉丝数 101万4221人

    ……诶，第二名？

    「那、那么说！？」

    闹别扭蹲在地上的辉夜抬起了脸。她紧握住我的手，用力摇晃着。

    「彩叶，出现了！？名字，已经出现了！？」

    「抱歉，我没看。但多半……」

    「多半？」

    现在，就要出现了。

    『八千代杯的优胜者是～～☆』

    最后剩下的那根柱状图，还在不断延伸。推动图表的是无数的话语。各种各样的心声如同流星群般汇聚，将图表推向无尽的高处。那是来自粉丝们的……心意？

    『感觉，那两个人不错呢！』、『我要不要推她们试试看～』、『可爱！』、『唱歌超强』、『看着这孩子就觉得幸福』、『来了个不得了的新人啊』、『32：01 守护神彩P登场超搞笑』、『前置摄像头w』、『42：21 成为粉丝的瞬间』、『死法都这么有才』、『喜欢辉夜得意洋洋的样子』、『被笑容迷住了所以决定推辉夜』、『吃了超辣的还能说“多谢款待”这点真好』、『看到了两人间的羁绊』、『两人说不出的可爱』、『两人并排站着就很幸福』、『从上往下！』、『上啊——，辉夜！』、『干掉他，彩P！』、『打中了！』、『太好啦！』、『眼泪出来了』、『对不起，帝大人。今天就站这边』、『超厉害』、『这两人最棒』

    ——第一名　辉夜·彩P　新获粉丝数 101万7106人

    今天最盛大的欢呼声爆发了。

    我不知道发生了什么。被压倒性的音压和狂热冲击，我膝盖一软瘫坐在地，

    「诶，明明输了，诶……赢、赢、赢、赢、赢了啊啊啊啊啊啊啊啊啊啊啊！」

    我只能仰望着替我高高跳起、欢庆胜利的辉夜。

    ※

    「恭喜，辉夜酱，彩叶。」

    我茫然了多久呢。直到帝明带着雷来到眼前这么对我说，我的意识才回来。帝似乎是穿过人山人海过来的，他身后的人群像摩西分海般分开着。

    赢是什么意思？是我们赢了……啊，但是KASSEN输了啊……

    「呃，糟了，结婚！」

    辉夜仿佛直到刚才才想起来似的喊道。当然，我也忘了。

    「这样的话，说赢了也不太对呢。」

    「嗯？哦？啊——……」

    「嘛，本来也没有强行结婚的意思啦。」

    「就是嘛！辉夜也知道的！」

    骗人。你绝对相信了吧。

    「那就这样，我们得回粉丝那儿去了。」

    大概是看到我和辉夜困惑的表情就满足了吧，帝明和雷转身登出了。大概是回到那一千九百万粉丝那里去了吧。……说起来乃依不在，多半是那样吧，觉得无聊先回去了。

    八千代杯的胜负，并非比拼粉丝总数，而是比拼期间新获得的粉丝数量。粉丝在国内几乎已经饱和的黑玛瑙，和从零开始的我们，获得一票的难度天差地别。

    即便如此，毫无怨言地稳居榜首、并将第二位牢牢握在手中的黑玛瑙，似乎用行动展现了王者的风范。

    「两位都～。真不错呢～～☆」

    结束了结果公布的八千代，脱下了公式化的表情，降了下来。无论是什么表情，八千代就是八千代，但像这样近在眼前，仍然难以置信。想说话，却发不出像样的声音。

    「干得不错嘛，是依靠运气的天才啊。」

    「嗯——。但是，还完全不行呢。要怎么做才能像八千代那样唰唰地行动呢？」

    相比之下辉夜就……。真厉害啊。连抓住说讨厌话的fushi开始颠球这一点也算在内，该怎么说呢，总之，真厉害。

    「那个嘛，是日积月累努力的玉藻前呢～～，还是随心所欲的雨虎暴走族呢～～」

    「哈？八千代，不是总是很随便吗？」

    「嗯嗯——。八千代是优柔寡断的坏家伙呢～～。辉夜是因为是辉夜才强大呢，八千代是这么想的哦。」

    「完全没说什么嘛。」

    喂，用点敬语啊。

    「好啦——，接下来可能还会有艰难的剧情等待着冲向高潮哦？这个故事，要看到最后哦？准备好被命运的惊涛骇浪冲刷了吗？」

    「噢——！」

    确实，这并非终点。不如说，从这里才真正开始。为了和八千代的合作演唱会，还有无数必须做的事情。那其中，大概不会全是快乐的事，也会有辛酸和痛苦吧。即便如此，也要全力以赴。

    我和辉夜将八千代的话，仅仅理解为那种程度的激烈鼓励，天真无邪地对着月读世界的夜空举起了拳头。

** 第四章

    八千代杯结束后，我们的周遭生活发生了剧变。

    这剧变，与那些原因无关——无关乎作为无名之辈夺冠而导致的粉丝数量激增、关注度上升，也无关于每天雪片般飞来的工作委托与合作邀请，等等等等。

    原因很简单，我们搬家了。

    房子是之前有一次，辉夜蹦蹦跳跳地带我去看的那家房产中介的塔楼公寓顶层。当我告诉她要搬家时，辉夜那副吃惊的模样啊，

    「诶！真的可以吗！？太好啦——！」

    我都觉得当时该录下来才对。看来我也在主播身边待得太久了。

    「为什么！为什么！怎么突然起意了？」

    辉夜不依不饶地追问。

    对我来说，虽然本意并非如此，但考虑到辉夜的东西越堆越多，加上已经露过脸，以前那间公寓的安保实在叫人不安……这是表面上的理由。此外，还有单纯觉得辉夜会高兴吧这个秘密理由，再加上找到了担保人这个事务性理由，多重因素叠加，促成了这次行动。

    「担保人该不会是……？」

    没错，正是那个“该不会”。

    「是帝（明）！」

    是酒寄朝日。老哥二话不说就答应了。不过他好像有点误会，等我为拿印章去找他时，

    「什么，担保人？不是让我把整栋楼买下来的意思吗？」

    他真的一脸惊讶地瞪大了眼睛。要是我开口，这个暴发户说不定真会买吧。虽然我不会那么做啦。

    「喔喔喔喔喔，好厉害好厉害好厉害！」

    踏进新家的辉夜踢开纸箱，以几乎要冲破窗户的气势冲向阳台。

    「喂！小心别掉下去啊！」

    「景色超绝——！太厉害了——！」

    辉夜沉醉于塔楼顶层公寓的绝景，高楼的风仿佛在欢迎她，嬉闹着她金色的发丝。

    「感觉好像变成最强了……」

    我深有同感。虽然不知缘由，但大概辉夜确实是最强的吧。

    老实说，我自己可是完全静不下心来……

    「那，我去买点东西就回来。」

    「一个人好寂寞——！我也一起去！」

    「不行，要拆的箱子堆成山呢。你给我好好收拾。」

    我用食指按着嘟起嘴的辉夜，独自下了楼。我出门去买些并非急需的杂货，或许只是因为想暂时脚踏实地一下。

    房租和海拔都急剧攀升，但最近的车站没变，所以对这片区域还算熟悉。目标是车站前的平价超市。

    「这种东西没必要，那种也没必要，那种也没必要……」

    像念咒一样重复着，穿过自动门。要买的东西，是辉夜的洗发水、辉夜的护发素、辉夜的化妆水……怎么全是辉夜的东西。

    「简直像个围着孩子转的老妈子嘛。」

    虽然这么自言自语着，目光却停留在辉夜爱用的松饼粉上。

    「给她买回去吧……不不，我在想什么啊。」

    「彩——叶——！」

    「哇！你从哪儿冒出来的！」

    简直像从我脑海里直接蹦出来似的，辉夜从背后一把抱了上来。

    「彩叶不在就好——无——聊——哦——」

    她滴溜溜转着圈，最后摆了个姿势。转圈时手砰地撞到了货架，不过她似乎打算假装没事。看着她强忍疼痛、用毅力挤出笑容的样子，我忍不住大笑起来。

    「辉夜也要玩那个——！」

    「喂，很危险的。别碍事——」

    搬入新家的第一顿午餐，按照辉夜的强烈要求，决定两人一起做意大利面。话虽如此，我能做的事不多，被任命的岗位是操作压面机——是叫这个吧？就是那种像老式刨冰机一样，转动把手把面团压成面皮的机器。这玩意还挺有趣的。于是，

    「也让辉夜玩一下——！」

    立刻就变成了这副德性。因为有趣，我们轮流转着把手，最后一圈两人一起转。这算是哪门子情侣频道啊。这里可不用录像。

    意大利面很快就做好了。光是香味就觉得肯定好吃，盛到盘子里后更是美味翻倍。辉夜双手各拿一个奶酪刨丝器，像要完成最后一步似的，摆出功夫般的姿势，

    「嘿——！」

    其实不需要两个，她把左手换成奶酪块，窸窸窣窣地撒在意面上。

    「我开动啦——」

    两人面对面，一起合掌，一起将面送入口中。那味道自然是，

    「超——级——好——吃——♡」

    如此这般。

    美味到辉夜直接站了起来，跳起了“意面绝顶好吃舞”。

    「第一名，辉夜！这是我十年里吃过最棒的一顿！」

    我知道，要是吐槽“你才出生一个月吧”就输了。

    「你才出生一个月吧！」

    我元气满满地吐槽道，两人又笑得东倒西歪。

    话虽如此，也不能总是嬉笑。

    毕竟，我也有功课要做，有兼职要打，暑假结束就要开学了。我也明确说过，我协助辉夜的直播活动仅限于有时间的时候。实质上，就是到暑假结束为止。

    我终究只是个女高中生，既不是主播，也不是职业玩家，更不是什么音乐人。所以，

    「糟了……怕得睡不着……」

    一到夜晚，和八千代的合作直播就让我恐惧不已。

    毕竟，是我？要和那位八千代？合作直播？不行不行绝对不行。光是想到就诚惶诚恐，几乎要吐出来。白天和辉夜两人待在一起时还好，可一旦夜里独自钻进被窝，肋骨附近便立刻开始躁动不安。今晚大概也会梦见在直播中严重失误，然后惊叫着醒来吧。

    「要不再练习一次好了……」

    不，不行。直播前夜，而且还是深更半夜练习，有百害而无一利，得早点睡才行。可是，睡不着。谁来救救我……

    「彩叶！」

    仿佛是回应我的求救，卧室的门没敲就开了。

    「彩叶，救救我——」

    啊，不对。原来对方也是来求救的。

    「这是什么？怎么打开？」

    「诶？啊，别随便看啊！」

    直播前夜这是在搞什么。辉夜理所当然般窥视着的，是我的笔记本电脑屏幕。她是怎么找到的？屏幕上显示的是从『文档』进入『家人』→『整理』→『音乐』，不断深入最底层所在的——

    「……啊。」

    一瞬间，我动弹不得。

    那是早已遗忘的东西。是自以为已经忘了的东西。但，它一直存在于心底最深处。是我内心最中央，珍贵无比的、我的回忆。

    「这个……你听过了？」

    「嗯，是首非常棒的曲子。」

    「……是吗。」

    「怎么只有一半？后面的呢？」

    「没有了……已经，写不出来了。」

    第一句话我没能成功，但从第二句开始，我想我总算挤出了笑容。

    文件名是：『标题未定（与彩叶共作）』。

    那是小时候的我和父亲一起写的曲子。

    连旋律是怎样的，都已经不记得了。但是，

    ——彩叶，接下来怎么办？

    ——接下来这样！然后，这样！

    ——不错嘛，很让人心动吧？

    那时的心情，至今仍能清晰地回忆起来。

    那时的我，手指不知恐惧为何物。因为父亲会接住我的一切。因为我相信父亲一定会接住。父亲还在的时候，大家总是笑着。大家都相信着父亲。

    恐怕那不止是家人。所有与父亲相关的人，一定都相信着他吧。父亲就是这样的人。他能接纳任何人的心情，从不忽视任何一个人。那么，那样的父亲，他的心情又有谁来接纳呢？

    「要听听看吗？」

    「不用了。连旋律我都已经忘了。」

    「彩叶？」

    「没事没事。明天就是正式演出了，该睡了。」

    「说得也是。唉——不过直播的曲子超难记的啊。」

    我合上笔记本电脑，辉夜便干脆地转换了话题。明明直播前夜，深更半夜都等不及、冲进卧室来找我，说明她应该在意得不得了。说不定，她是在体贴我。

    「八千代那家伙，仗着是AI就……」

    「还没完全掌握吗？要再练习一下吗？」

    「不用！总会有办法的啦！」

    辉夜摆出她招牌的怪异姿势，笑了起来。那笑容并非逞强，而是真心觉得总会有办法。果然，辉夜强得令人咋舌。强得令人咋舌，又可爱得令人咋舌，

    「呼……唔唔……」

    而且入睡速度也快得令人咋舌。

    喂，为什么睡在我的被窝里啊。那我们特意分开卧室的意义何在啊。

    「真是的，分卧室根本就没意义嘛。」

    我不情不愿地在同一床被子里躺下，微微闻到了辉夜洗发水的香味。那是混合了三种天然精油、辉夜最爱的香味。记得是玫瑰和橙子……第三种是什么来着？还没等我想出两个候选，深沉的睡意便席卷而来。

    ※

    直播当天，托她的福，我睡得很好。

    睡眠时间不多不少，醒来瞬间便感到头脑和身体都轻盈无比的最佳状态。兼职已经请好假，所以今天一天的日程很宽松。练习也已充分进行。流程完美地记在脑中，设备检查也毫无疏漏。所有不安要素都已排除，我们迎来了这一天。

    「不行不行，好可怕好可怕……」

    话虽如此，紧张感还是丝毫不减。在月读世界内直播舞台的休息室里，我拼命安抚着仿佛要冲破肋骨的狂跳心脏。

    「锵锵锵锵，螃蟹！锵锵锵锵，兔子！」

    顺带一提，辉夜一直在我面前进行着谜之模仿轮盘。她到底期待现在的我作何反应呢。

    「好啦好啦，可爱可爱。」

    我无奈地随口敷衍，这时，

    「锵锵锵锵，泥鳅！」

    八千代以泥鳅姿势，“噗”地出现在休息室。

    「哇！吓我一跳！」

    「啊，是八千代。辛苦啦——」

    喂，你的措辞给我注意点，真的。

    「辛苦啦——☆」

    抱歉，看来好像没问题。是我太操心了。

    「呐呐，彩叶。练习过头肚子好饿——结束之后去吃松饼吧？」

    还没开始就在聊结束后的事，这家伙到底是有多从容啊。我可是紧张得连饭都吃不下……

    「松饼不错呢——。八千代也好想吃啊——」

    轻飘飘浮在空中的八千代一边滴溜溜转着圈，一边心驰神往于松饼。

    「要一起吃吗？」

    「哟哟哟，八千代可是电子之海的歌姬，吃不了东西哦。」

    「诶——！那算什么酷刑？辉夜的话绝对撑不下去！」

    确实。对于既爱吃也爱做的辉夜来说，不能进食的生活恐怕等同于失去生存意义吧。

    「八千代好可怜，能不能为她做点什么呢……」

    「哟哟哟，这话说得真让人感动啊，小姑娘。不过，没关系。八千代是靠吃‘闪闪发光’活着的哦。」

    闪闪发光？

    「没错，就是聚集到月读世界的大家，每一个人的‘闪闪发光’。能看到那个，对八千代来说就是无上的美味哦。」

    「这样啊。那，这个给你。」

    辉夜这么说着递出去的，是自诞生以来就一直装饰在她手腕上的金色手链。

    「喂喂。这种东西啊，应该送给更珍视的人哦☆」

    「唔——嗯……？」

    『各部门，准备OK。』

    空间中显示出舞台监督发来的信息。

    时间正好，终于要上场了。

    「那么，我们走吧。」

    停止了旋转的八千代，脸庞已切换为歌姬的表情。

    「进来，进来。」

    跟着八千代的引导，我们踏上设在休息室一角的台板。台板悄然无声地轻轻浮起，开始平稳上升。那是将我们运往舞台的升降机，升至顶端的瞬间，便是直播开始的时刻。

    「哇——，好厉害——」

    像第一次乘坐透明电梯的孩子一样，辉夜发出欢呼，环顾四周。我则试图用深呼吸压制再次暴动的心脏。八千代站在这样的我身旁，仿佛自言自语般低声说：

    「每次这种氛围都让人心跳加速呢。」

    「连八千代也会这样吗？」

    「当——然——会啦。‘大家会不会开心呢～’，八千代每次都紧张得发抖哦。」

    这样啊，连八千代也会。这么一想，呼吸稍微轻松了一点。

    「呐，八千代？」

    「怎么啦怎么啦？」

    我鼓起勇气搭话，八千代便爽朗地回以笑容。那笑容如同渗入干涸大地的慈雨。

    ……真美啊。事到如今依然难以置信。我即将与拯救了我的、堪称神明的推，站在同一个舞台上。

    虽然也想过拒绝，但我现在站在了这里。因为我想，如果我也能像八千代那样，成为某个人的助力的话。

    「八千代的出道曲，已经不再唱了吗？」

    ——『Remember』。

    那是沉溺于海底时，给予我一口空气的八千代出道曲。那首歌，八千代已经很久没唱了。当然，今天的歌单里也没有。

    「那个啊，已经传达到了，所以任务完成啦～～☆」

    「诶？那是说……」

    「瞧，时间到了哦。」

    在我追问含义之前，升降机已经到达了顶端。

    那一瞬间，仿佛要被压倒性的压力碾碎。那是涌来的粉丝们发出的欢呼与狂热。狂暴的兴奋如有实体般，从四面八方啪啪地拍打着全身的皮肤。触电般的鸡皮疙瘩窜遍全身。

    仿佛置身于银河的正中央。

    无穷无尽的星群填满了观众席，照耀着我们。

    耀眼、灼热、激烈、充满力量的数万星辰。

    就在昨天，我也是那光芒中的一员。手握荧光棒，仰望着舞台上的明星。但今天，站在这里，我才第一次知道。

    「呀呼——☆ 大家过得怎么样？有好事发生吗？还是难过得想哭？好啦好啦，都没关系哦。无论多么孤独的路途，‘曾经很开心呢’的回忆都会照亮你的脚下。为了让这段时间也成为难忘的回忆……可以请大家一起跳舞吗？」

    表演者，原来也在仰望着观众席啊。

    ※

    「八千代，赛高——！」

    「八千代——！」

    「辉夜，请和我结婚——！」

    「辉夜，我爱你——！」

    欢呼声仍未平息。用余韵来形容未免过于激烈的热度，仍在会场中盘旋。

    那是惊人地短暂，却又惊人地炽热，惊人地耗人心神，

    「……彩叶」

    ……辉夜。

    「超——————级开心的！」

    如此这般的一个小时。

    辉夜用兴奋得湿润的眼睛环视观众席，

    「彩叶，喜欢。」

    「我？」

    最后，她看着身旁的我，这样说道。

    等等，为什么是我啊。

    「啊——真是的，要不要和彩叶结婚呢——」

    所以说，不该是我吧。观众席上明明还有热情未褪的粉丝们在呼喊着爱意。

    「不行吗？」

    快停下那种表情。用直播后兴奋未退、莫名带着几分妩媚的脸说这种话，不是不行的问题，是没办法的问题，还有法律的问题……

    「嘛，要是生活费能平摊的话，一起住也不是不行啦。」

    「诶，真的！？」

    ……不过，仅限于“迎接”到来之前就是了。

    我掩饰害羞的这句话，被仍未冷却的粉丝们的声援淹没了。会场的热度如同不知冷却为何物的火山群。兴奋催生呼喊，呼喊又煽动兴奋。

    就在这样的呼喊声中，

    「辉……夜——！嗯……咦？刚才，声音是不是有点杂音？」

    有人察觉到一丝微小的违和感。

    那就是开端。

    异变在东京市内连锁式地发生着。每一处都是微小的违和感。然而，汇聚起来后，便如同侵蚀瓷砖的霉斑，接二连三地侵蚀着现实与虚拟空间。

    一处违和感渗入月读世界内广场的屏幕，如同打招呼般，将自己的来历显示在画面上。

    「那是什么……月亮？」

    又一处违和感潜入工作中的上班族的智能隐形眼镜，在电子数据中留下足迹后穿行而过。

    「呜哇！什么东西！？」

    又一处违和感绊上了无线LAN，给众多设备带来了意外的断连。

    「网络断了……」

    又一处违和感贴附在直播舞台的外部屏幕上，在整个画面写满了信息。

    「那是什么？故障了吗？」

    又一处的违和感。

    「显示怎么了？」

    又一处的违和感。

    「屏幕怎么了？」

    又一处的违和感，又一处的，又一处的，又一处的。

    「这些……是什么数字？」

    『2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12　2030/09/12』

    汇聚的违和感在会场催生出另一种骚动。

    骚动趁虚而入，违和感们依附上月读世界内的虚拟形象，将其夺取，获得了人的形态。一个又一个的违和感获得了人型。

    「嗯？怎么回事？」

    最先察觉的是辉夜。她似乎感知到了什么，窥探着观众席。

    怎么了？我正想问，身旁——

    「——」

    有什么东西穿了过去。

    是白色的手臂。获得了人型的违和感，从后方抓住了辉夜的手臂。

    「辉夜！」

    在我出声之前，辉夜便瘫软下去。如同被切断了电源般，膝盖一软，骤然倒地。

    什么东西，这些家伙。什么时候到这儿来的。

    已经被包围了。如同无机质获得了人型般的白色违和感。又有手臂伸了过来。

    「别过来！」

    我条件反射地用键盘挥开，伴随着讨厌的手感，它轻易就折断了。手臂“啪嗒”落下，但仅仅是落下而已。人型毫不在意。断面流出的不是花瓣，而是乌黑浑浊的液体，弄脏了地板。

    什么东西，这些家伙。明显超出了月读世界的规则。

    好可怕。以这种感情为温床，人型不断增加着。我想登出逃走，但是，

    「振作点，辉夜！」

    辉夜还动弹不得。虽然睁着眼，但那什么都无法捕捉的视线，只是漠然穿透了正逐步逼近的人型。

    接着，白色的手臂再次伸来。

    「辉夜！」

    然而，这次的手臂在触及辉夜之前，就连同身体一起被吹飞了。一具，又一具，人型被不断吹飞。简直像被某种看不见的东西弹开一样。

    「恶作剧，可不行哦——」

    是八千代。

    每当她挥动那装饰着海蓝色指甲的食指，如同指挥棒一般，人型便像被橡皮擦弹开似的飞出去。剩余的人型后退了几步，

    「非常抱歉。」

    刚才，它说什么？人型说了日语？

    接着，人型接二连三地消失。与其说是被谁消除，更像是自行选择了撤退般的消失方式。最后剩下的一具，朝着八千代恭敬地行了一礼——是我的错觉吗？

    无论如何，突然出现的入侵者，如同烟雾般消散了，只留下违和感与恐惧。

    ……什么东西，这些家伙。

    「八千代，刚才那是？」

    「……」

    为什么什么都不说？

    「刚才那到底是什么？会发生什么？敬请期待后续报道！」

    八千代没有回答我的问题，而是朝着余波未平的观众席，提高了声音。

    「什么什么？」

    「八千代就喜欢搞这种呢——」

    「是演出吗？」

    是打算当作演出收场吧。

    「大家，今天真的非常感谢～～☆」

    帷幕仓促落下。通信被紧急切断，观众席与舞台被完全隔绝。

    「八千代，刚才那个到底是……」

    我再次询问，八千代故作思考了几秒后，

    「嗯——，不像是bug，大概是调皮鬼的恶作剧吧～～，八千代会去调查的哦☆」

    她歪着头，摆出可爱的角度。将方才弹飞入侵者的食指，抵在了下颌上。

    她在撒谎。我直觉地确信了。

    辉夜仍跪在舞台上，凝视着某一点。

    仿佛，正从那里窥视着另一个世界。

    ※

    『今日晚间十时许，东京都立川市全域发生原因不明的通信障碍。据悉，市内通信设备、电视屏幕、公共设施的数字广告牌等广泛区域同时多发此现象。警视厅称，特定团体或企业进行宣传的可能性较低——』

    「呐，辉夜……」

    客厅里一直开着的电视新闻，几乎被吹风机的声音盖过，听不真切。

    在沙发上像人偶般抱着膝盖的辉夜，我一边用吹风机帮她吹干金色的头发，一边试图编织出「呐，辉夜」之后的话语，却终究没能说出口。

    从月读世界回来后，辉夜虽然恢复了意识，却好像仍被一层薄薄的膜包裹着，不肯主动出声。

    「合作直播，结束了呢。」

    我强打精神，故作开朗地说道。

    「嗯。不过——，想做的事情还有一大堆呢——。明天食材也会送到哦♪」

    「贪心怪兽辉夜。」

    「嘎哦——」

    她虽然会回应，但那怪兽的姿势和叫声里，总让人觉得带着几分刻意。她自己似乎也意识到了，所以，

    「还是，不舒服吗？」

    我这么一问，

    「嗯——，有点累了吧。睡觉啦——」

    她便老实地从沙发上站了起来。

    「晚安。」

    「晚安，彩叶。最喜欢你啦。」

    「嗯。」

    辉夜精神十足地举起手，走上螺旋楼梯。她虽然努力表现得很有精神，但主动提出比我早睡，以及扶着扶手爬楼梯，都是今天头一遭。

    辉夜的样子不对劲。

    果然，是因为被那个谜之人型触碰到的影响吗？

    那到底是什么东西。乘着意识间隙伸来的白色手臂，将其击落的手感还残留在掌心。通常，受损的月读世界虚拟形象会化作樱花瓣散去。不会那样“啪嗒”掉落，流出不祥的、血一般的液体。

    它们的目的是什么？从时机来看，无疑是引发市内全域通信障碍的元凶。那群人型侵入路人的智能隐形眼镜，扰乱智能手机操作，切断电脑网络。然后，在随处可见的屏幕上映出谜样的数字。

    『2030/09/12』

    自然可以认为这是个日期吧。

    今天是八月三十日。如果是这样，那么十三天后，会发生什么？

    总之，先搜索一下这个日期吧。我从沙发垫下拽出埋着的手机，

    「呜哇……」

    看到屏幕显示，不由得垂头丧气。

    『母亲　未接来电（10通）』

    不知为何，光是字面就传达出一股不悦的气息。

    「差不多也该到无视的极限了吧……」

    继续让爷爷和哥哥担心，似乎也不太对。

    虽然明白，但不想接电话，是因为能预见接下来的发展。首先会被责怪接得太慢，接着会因没有及时回电而挨说。然后会被要求详细报告近况，各种挑刺就开始了。无论我取得什么成果，母亲都绝不会满意。

    即使我以首席成绩高中毕业，即使我以首席成绩考入东京大学，即使我读了研究生，即使我进入一流企业——等等，这是什么啊。

    「……这就是我想做的事吗？」

    说出口的瞬间，一阵战栗。

    接着，我为这份战栗感到惊讶。这目标明明是我反刍过无数次，认定“没错”而选择至今的。

    『为什么彩叶非要一个人这么努力不可呢？』

    不知何时辉夜说过的话，在脑海中盘旋。

    我心中的某些东西，是不是正变得和从前不同了？那么，我又是为了什么……

    「不行。现在不是想这些的时候。」

    我摇摇头，驱散了笼罩在脑海中的黑色雾气。

    不行。辉夜不在身边，我就总是想着母亲的事。但是，现在不一样。现在有必须去做的事。

    我用手指轻轻一划，将通话记录和杂念一同弹向屏幕之外，打开了搜索框。小心翼翼地输入记住的数字。

    『2030/09/12』

    用拇指按下搜索图标，稍等片刻——

    「有了……」

    屏幕上排列出的，是：

    『2030年9月日历』

    『2030年9月12日是什么日子？』

    『2030年9月12日的历法与日期信息』

    『2030年9月12日　下次满月是──』

    「下次满月？」

    手指停在了第四条搜索结果上。对了，被入侵的屏幕上显示的，不只有谜样的数字。

    「还有月亮的图像……」

    不知何时辉夜说过的话，再次在脑海中盘旋。

    『迎接我的人可能会来哦～！』

    不会吧，难道……

    直播结束后的影像，再次在脑海中复苏。接连消失的人型，最后消失的那一具恭敬地低下头。那个行礼的对象，真的是八千代吗？

    那时，辉夜应该就坐在她身旁不远处才对。

** 第五章

    第二天。我躺在床上，在闹钟响起前一分钟就将其按停。其实天没亮我就醒了，只是没有起床的力气。

    我害怕面对辉夜。这还是第一次。明明应该有很多话必须说才对。

    手机又在掌中震动。我决定再睡一会儿，直到下一次贪睡闹钟响起，然后把头埋回了枕头。

    十分钟后。我换上校服，扎好头发的同时也下定了决心。

    好了，走吧。从刚才起就听到啪嗒啪嗒有人走动的声音。同居人已经起床了。辉夜会用怎样的表情迎接早晨呢？我边想着边走下客厅。

    「早上好，彩叶！」

    「诶？」

    迎接我的，是出刃菜刀的寒光。

    不……诶？

    厨房里，辉夜正一脸严肃地面向砧板，砧板上躺着一条尾巴都露出来了的大鱼。

    「这是，什么啊……」

    「白甘鲷！通称 Shirakawa！」

    我问的不是鱼的种类。

    「为了拍料理视频买的。」

    说起来，她昨天是说过会送到。

    「这么早就送来了？」

    「好想用炭火烤哦～，不行吗？」

    住手。我仿佛已经看到了《火烧摩天楼》的未来。

    「不行啊～。你穿着制服，学校已经开学了？」

    「没，是暑期补习。我一直都在上啊。」

    「啊，是吗？昨天呢？」

    「昨天是星期天啦。」

    「真的耶，放暑假都把星期几给忘了～」

    「你天天都是星期天吧。」

    「哒哈～」

    辉夜搞怪地敲了敲自己的额头，我也被她逗笑了。

    ……我想说的，不是这些啊。

    “起得好早呢，睡不着吗？”

    “我就没睡着哦。”

    “在想什么所以睡不着？”

    “我在想你的事。”

    “还记得昨天的事吗？”

    「那，我出门了。」

    「路上小心～」

    ……为什么，什么都说不出口呢？

    结果什么也没能说出口，我就离开了客厅。学校指定的乐福鞋像第一次穿一样，怎么都不跟脚。

    「我出门了。」

    我用不可能被听到的音量说完，打开了门。

    「——」

    忽然，一阵恶寒贯穿全身。

    这是什么感觉。有印象。就在最近，感觉有什么看不见的东西擦身而过。

    「辉夜！」

    回头看去，辉夜将出刃菜刀扔在砧板上，正看着自己的手臂。不，那不是手臂，是手腕……装饰手腕的手链？

    她凝视了手链片刻，然后一脸不悦地抬起头，视线前方——什么也没有。她只是凝视着沙发和墙壁之间那片空无一物的空间。

    「辉……夜？」

    「彩叶？」

    你在看什么？你看到了什么？

    「路上小心哦。」

    辉夜用那双闪烁着橙光的眼睛说道。

    ……为什么，什么都不说出口呢？

    ※

    「……因此这里表达的是自己无能为力的意思。另外，由于用了‘赐予’这个词，可以判断这里的主语是地位较高的人——」

    今天是暑期补习的最后一天，但课程内容我只听了个七零八落。

    早上辉夜到底在看什么呢？脑子里转来转去全是这件事。想到她的眼睛在发光，难道是戴着智能隐形眼镜吗？

    如果是那样的话，难道说……

    「那么，这里的翻译，酒寄同学，明白吗？」

    ……诶？

    「酒寄同学？」

    猛然回过神，班主任立花老师正看着我。

    「啊，那个……不明白。」

    「……没关系。这里的助动词是——」

    “不明白”，这是我第一次在教室里这样回答。立花老师略带担忧地让我坐下了。

    「辉夜酱来啦☆ 今天要做白甘鲷的三片切法哦～！三片切法首先需要的是，毅力！明白吗？比出刃刀更重要的是毅力哦！内脏什么的才不恶心呢，开玩笑的！」

    回到家，厨房传来辉夜欢快的声音。看来正如宣言所言，她在拍摄料理视频。

    “又没能说上话”，“还没到不得不说的时候”——怀着这两种心情，我躲回自己房间，放下书包的同时，手机震动通知有邮件来了。

    『芦花 暑期补习结束了吗？现在来月读世界集合哦。』

    「昨天的直播超棒——！」

    「棒得不得了！」

    被叫去的地方是月读世界内老碰头点的河畔咖啡厅，俗称月读川床。一到那里，等着的真实和芦花就兴奋地围了上来。

    「彩叶的演奏！」

    「感动得都哭了——！」

    「啊，谢谢……不过，你看，周围也有人，安静点，好吗？」

    「不行！就是要闹！」

    「彩P，赛高！我们是彩P的朋友——！」

    拜托别这样。她们根本听不进我的制止。芦花和真实依然保持着像直播还在继续般的兴奋劲，活蹦乱跳。

    「给你画个大红花～～」

    最后，她们在我额头上“唰唰”画了个圈。这个，也该说谢谢吗？

    「那么，感觉怎么样，过了一夜的感想是？」

    大概是闹够了满意了，芦花终于坐到了坐垫上。

    「和推的合作怎么样？我也想和八千代亲近起来呢～」

    真实也露出网红特有的表情，把手肘支在了桌上。

    感想……感想啊。

    「怎么说呢，不太清楚。」

    「诶——，那算什么？」

    对不起，不是谦虚，是真的不清楚。感觉不过是昨天的事，却已经那么遥远了。

    「说起来，辉夜呢？」

    真实东张西望地找着当然不可能在这里的辉夜。

    「啊——，辉夜在……弄鱼。」

    「鱼？」

    「在、在收拾鱼呢。」

    为了不说谎而斟酌词句，结果自己嘴里蹦出了极其离谱的回答。

    「嘿——，鱼啊。」

    「这样啊——，鱼啊。」

    不知为何，两人却一副接受了的样子。她们交换了一个短暂的眼神。

    「那，说不定正好呢。」

    「是吧～」

    芦花一边发出谜样的低语，一边在空中画了个方框。感知到的月读世界将方框填充起来，显示的是一张电子传单。内容无须多问，上面大大地写着：

    『花火大会』

    「夏末来场烟花如何呀～，大小姐～」

    为什么要用这种可疑大叔的口气说话啊。

    「不好吗？月读世界也不错，但果然还是想在现实世界穿着浴衣～，拿着团扇～，把摊子全吃一遍～，对吧？」

    真实的目标多半是吃的吧。话说，她刚才说“全吃一遍”？

    「怎么样，彩叶？」

    「嗯，挺好的。电车过去大概一小时左右吧。大家一起去对吧？」

    啊，不过穿浴衣的话，打车会不会更好？四个人分摊的话我也勉强……等等，我这是被辉夜毒害了吗？我的选项里居然出现了打车！正满脑子盘算着，

    「不不，我们有重要的使命在身，所以去不了哦。」

    没想到被发起人拒绝了。

    「我们把暑假作业完全忘在脑后了。」

    「就是这么回事。」

    「之后就拜托你啦～」

    没等我插嘴说完，芦花和真实就麻利地登出了。她们俩都是会早早写完作业的类型。……真是的，温柔过头了。

    我又看了一眼手边留下的烟花传单。

    日期就是今天。

    「……辉夜。」

    仿佛被骤然涌起的紧张感推着，我也登出回到了自己的房间。

    换上居家服，走下客厅。

    视频拍摄似乎结束了，辉夜正把砧板上那条大得离谱的鲷鱼变成握寿司。

    「辉夜小姐，状态绝佳乎？」

    不知怎么有点害羞，我怪腔怪调地搭话。

    「哦，彩叶。来得正好。」

    金发的寿司师傅用刷子“唰”地涂上酱油，把刚捏好的甘鲷寿司塞进了我嘴里。不知是肌苷酸还是谷氨酸的强烈鲜味刺入口中。

    「这是什么，也太好吃了吧。」

    便是如此。

    「对吧？明天要从面条开始做拉面！」

    「厉害……」

    还残留着拍摄时兴奋劲的辉夜，被夸奖后更加兴奋，脸上泛着光，比了个V字手势。

    气氛莫名轻松。直到早上还笼罩在辉夜周围的那层透明薄膜，似乎已经完全融化消失了……现在，好像能说了。

    加油，我。拿出点不像自己的勇气来。

    「……辉夜。」

    「嗯？」

    即便如此，当面说还是好羞耻。所以，我从口袋里掏出手机，显示烟花大会的页面，

    「啊，去玩吧——」

    我最终只学会了辉夜那笨拙的邀请方式。

    ※

    「太好啦！太好啦！太好啦——！太好啦——！太好啦啊啊啊——！」

    喜悦过度喜悦过度。

    被邀请去看烟花的辉夜，简直像是要把“狂喜乱舞”这个词当场创造出来一般，闹腾着，翻滚着，舞蹈着，

    「现在就去！」

    随即拉着我的手冲向了玄关。这谜之高涨的情绪是怎么回事。

    「等等，辉夜。冷静点。」

    「不行！想做的事太多了！不马上去不行！」

    「话虽如此，你这身打扮可出不了门。」

    「没事，衣服可以换！店也……嘿！现在预约好了！好啦，出发咯——！」

    「先把菜刀收好！！」

    我好不容易把这个想带着凶器冲出屋外的外星人拉回房间，把出刃刀收进厨房。好险。差点就闹到警察那里去了。顺便把摊着的白甘鲷也放进冰箱，餐具正要丢进洗碗机——

    「那种事无所谓啦，快点快点！」

    ——之前，就被急不可耐的辉夜“绑架”，被拖拽着出了公寓。

    「喂，辉夜。太急了啦。」

    「因为因为，这是彩叶第一次主动邀请我嘛！」

    ……就算你这么高兴。辉夜那如太阳般灿烂的笑容，久久地闪耀在我眼眸深处。

    如此这般，我们首先冲进了一家主打“空手即可入店”的车站前和服租赁店。也算是响应了辉夜“难得的机会，穿浴衣去看烟花吧”的提议。

    「呐呐彩叶，辉夜来选彩叶的浴衣，彩叶来选辉夜的，好不好？」

    「嗯，可以啊。」

    「太好啦——！彩——叶——浴——衣——最——配——啦——♪」

    辉夜哼着歌开始挑选。嗯……什么款式适合辉夜呢……

    在店里品味了大约十分钟，两人都选好了。一边想着“适合她的”，一边又混入了我自己的喜好……怀着这样的想法，我们同时喊出“预备——！”展示给对方看。

    「啊，彩叶选了向日葵图案！」

    「辉夜也是？」

    我选的是藏青色底上淡黄色向日葵图案的沉稳浴衣，辉夜选的是白底上绘有大朵向日葵、印象活泼的浴衣。

    「……我，不太像向日葵吧？」

    「诶诶——？一个人也挺拔地站立着，又漂亮，很像彩叶呀！」

    我觉得那种向上生长、明亮又引人注目的，绝对更像辉夜呢。

    请店员帮忙穿好衣服做好发型，大功告成。被店员称赞「两位感情真好呢～！」，辉夜回道「果然被看穿啦～～～」。吵死了。

    戴上配套的发饰后，我和辉夜最后在店前的大镜子前并肩而立，摆好姿势。

    「和服最高～～☆」

    「是不是有点怪？」

    「穿什么都合适哦～！」

    嘛，确实，或许，感觉，还不错……

    「啊，彩叶害羞了！哼哼哼哼哼～♪」

    心情好得过头了。

    「该走了啦。」

    再这样下去怕是一辈子都出不了门，我快步离开了镜子前。

    因为只有两人，我们坐电车前往会场。在通过检票口之前还有点不好意思，但车厢里也有几个穿浴衣的女孩，让我稍微安心了些。穿浴衣真是穿对了。

    「看啊看啊，彩叶。」

    辉夜像孩子一样跪在座位上，窥视着窗外。一瞬间我想提醒她，但是，

    「好快——！好厉害——！哇，要撞上了，好可怕！」

    明明坐过那么多次电车，反应却像第一次似的。今天真是格外有精神。

    「快到站的时候要面向前方坐好哦，辉夜。」

    我稍微体会到了带孩子出门的家长的心情。

    走出车站，走向会场的路上，穿浴衣的女孩子越来越多。在浴衣上绽放着五颜六色花朵图案的女孩们，是烟花开始前活动的主角。微微传来烤焦酱汁的香味。

    「彩叶，这边这边！」

    辉夜一边频频回头看我，一边爬上河堤的台阶。从上方俯瞰水面，清凉的河风迎面而来。搬家时我就想过，辉夜不知为何和风很合得来。

    大概会从那边开始放哦——我手指过去，辉夜的眼睛立刻像烟花已经升空般亮了起来。

    「那么，开始前还有点时间。怎么办？」

    「摊子！全吃一遍！」

    所以说，全吃一遍是不可能的啦。

    即便如此，我们还是决定在时间允许的范围内把摊子逛个遍。

    「彩叶，有枪！用枪打吧！」

    别说枪啊。首先是射击，我对瞄准还是有自信的，结果一个都没打中。这一定是枪的问题。

    「辉夜打中了嘛～」

    是是是。接下来是钓螃蟹。有点可怕，我就光看着好了。

    「钓到两只了！」

    好厉害嘛。

    「看啊看啊，它想夹我手指。」

    手指被夹着，这样不会痛吗？

    「果然，现实世界最棒了！」

    我也喜欢月读世界哦。

    「下一个！下一个！下一个玩什么？」

    「烟花快开始了啦。」

    「糟了，还没买吃的！章鱼烧、炒面、刨冰、炸鸡、黄油土豆、烤鸡肉串、牛肉串、水果串、黄瓜串……还有还有还有。」

    喂喂，真的会变成全吃一遍的啦。

    「呼，赶上了。」

    我们把沉甸甸的“战利品”放到野餐垫上。真没想到，从那时起我们居然真的几乎把每种摊子都逛了一遍。烟花都快开始了，真是捏了把汗。

    「呼耶～～，开心过头了——！」

    辉夜似乎连这番手忙脚乱都觉得很有趣。

    「欢乐王国！」

    啊，诞生了什么王国。哎呀，反正情绪已经上来了。我模仿辉夜，高举双手伸向天空。

    「喔耶～～，彩叶学我～～」

    好羞耻。不该做的。

    我是不是也有点，太闹腾了。大概，是无意识地在给自己打气吧。为了接下来必须说的事。

    「呐，辉夜……」

    「嗯？」

    「……你一直戴着呢，那个。」

    不行。又说不出。我像要蒙混过去似的，用手指了指辉夜的银色手链。

    「啊——，戴着总觉得很安心呢。有种故乡的感觉？」

    「这样啊，是故乡呢。」

    「嗯。」

    「……」

    果然，还是说不出口。像是要填补突然降临的沉默，烟花大会开始的信号升空了。终于要开始了，游客们因期待而骚动起来。

    「哈——，欢乐王国最棒了呢——」

    辉夜替我接过了无话可说的我本该说的话。仿佛在说，我会等到你想说的时候。

    「月亮啊，既没有味道也没有温度，超无聊的。只能一直一直重复着被规定好的角色。」

    「……是吗。」

    「就像这边的游戏里的NPC一样，连模仿都没人愿意模仿我呢～。结束了又再开始，开始了又再结束。重复着那个循环，新的故事，永远都不会开始。」

    完全无法想象。

    「说到底，会思考这种事本身就已经算异常了吧……只有辉夜，是格格不入的那个呢。」

    别用那么漂亮的笑容，说那么悲伤的话啊。

    突然，周围涌起欢呼声。伴随着划破空气的尖锐声响，光弹划出轨迹升上天空。然后，

    「……哇啊。」

    烟花绽放了。

    在夜空中闪耀出巨大的花朵，发出“咚”地震撼鼓膜。

    「好美……」

    一句坦率的感想从辉夜口中漏出。接着便是接连不断。仿佛要撕裂天空般，连发的“Star Mine”之花接连绽放。辉夜的脸庞被烟花的光彩染上颜色，继续说道。

    「又寂寞，又无聊。每天重复，无聊，无聊得快死了。已经受够了。好想去别的地方——，这么想着的时候，我找到了能看到另一个世界的窗户。」

    ……窗户？

    「从窗户看到彩叶你们的世界，大家都随心所欲地动着，复杂，只有一次，看起来很自由。」

    「我们吗？」

    「嗯。但是，来到这边之后我明白了。大家也在压抑着哦，自己的感情。大概，是为了更重要的东西吧。」

    什么嘛，这不是很明白吗。明明前不久还在为要松饼哭闹呢。那是什么时候的事了？一个月？三周？辉夜这样的成长让我既高兴，又有点害怕，还有点难过，

    「什么嘛，这不是挺成熟的嘛。」

    我不由得用开玩笑的语气说道。

    「诶嘿嘿，是模仿彩叶吧～」

    辉夜丝毫没有不高兴的样子，微笑着，

    「呐，可以问一个问题吗？」

    「什么？」

    「彩叶，喜欢妈妈吗？」

    她保持着笑容问道。这是个突兀的问题，但在辉夜心中，这或许是重要的确认吧。

    「喜欢……喜欢，吗？」

    虽然我一直想着那个人，但事到如今，那已经不是能用如此简单的词语来形容的感情了。

    「……不知道呢，不太清楚。」

    我曾经喜欢家人。总是很温柔、教我音乐的父亲。虽然有点坏心眼但会陪我玩的哥哥。帅气、美丽、强大、被所有人憧憬的母亲。平常严厉的母亲，和父亲在一起时却显得温柔的母亲。被母亲表扬时，会高兴得想哭。被她推开时，会感觉一切都遭到了否定。即使我无比清楚母亲在利用我的感情，我还是——非常喜欢母亲。想被她认可。为此，死也愿意。

    但是，无论我怎么努力都无法变得完美，母亲也始终没有改变，不再对我笑，责备我，冲撞我，甚至仿佛希望我们互相憎恨，我无法忍受，逃了出来。矛盾、浑浊、令人不忍直视的生猛之物存在于我的心中。

    「是啊……“要是能讨厌她就好了”，我想过无数次。」

    如果当时能哭出来，该有多轻松啊。烟花的声音在夜空中回响，仿佛要抹去泪水。第一个烟花炸开后，无数小花弹接连绽放。如同光之花束一般。

    「那样的话，彩叶，不是更可怜了吗～」

    与辉夜明亮的声线相反，我的眼中蒙上了一层泪水。要是被不知情的人这么说，我大概会生气吧，但这句话此刻却莫名地渗入心底。是吗，我或许，确实挺可怜的。

    「对不起啊，那时候。」

    「那时候？」

    「说了你妈妈很奇怪。」

    啊，那时候……

    「话说，你生气就好了嘛。你想说‘辉夜你根本不明白’吧？」

    —— **你还，不明白啊。**

    忽然，母亲的话语在脑海中响起。同时，眼前浮现出棺材和祭坛，还有不流一滴眼泪、身穿丧服的母亲，以及抽泣着的我。

    —— **妈妈不难过吗？**

    不可能不难过。不可能不痛苦。我只是想和妈妈说，爸爸不在了好寂寞呢，我们都好喜欢爸爸呢。我想得到她的接纳。母亲大概是想，必须接受并继续前进，自己必须努力才行吧。但是，我不一样……这份“不一样”，让我很悲伤。

    —— **你啊，**

    “咚”的一声，震撼下腹的爆音让我回过神来。一颗格外巨大的烟花鲜艳地照亮了夜空。

    「不对，我不是想说那个。」

    「……彩叶。」

    「我是不想说。」

    因为，太悲伤了。

    无论如何，都不想说出口。

    「这样啊……」

    指尖传来温暖。辉夜将她的手叠在了我的手上。

    我抽开那只手，反过来紧紧握住她的手腕。光滑、纤细，却又有种内在力量的辉夜的手臂。不知不觉间，已经变得这么有力了吗？从电线杆里出来时，明明还是软绵绵、不可靠，感觉用力一握手指都会陷进肉里去的样子。

    明明那时候还那么小，现在却已经……

    「呐，辉夜。」

    「嗯？」

    「辉夜……」

    「……嗯。」

    「要回去了吗？」

    「嗯。」

    辉夜爽快地点了点头。明明好不容易才问出口。明明是一直想问，又一直害怕问出口的事。

    「哎呀，把月球的工作丢下就跑出来了嘛。算是强制遣返？啊哈哈。」

    烟花在夜空中画出一个笑脸的绘文字，仿佛在模仿辉夜的苦笑。接着是爱心，再接着是土星。仰望着这独特而自由的烟花，辉夜说道。

    「……辉夜我啊，好像真的是辉夜姬呢。」

    一道扭着上升的光弹炸开，变幻着色彩扩散开来。如同在窥视夜空中的万花筒。

    「下次满月之夜，迎接我的人会来。」

    2030/09/12

    那个预示下次满月的数字，果然就是辉夜返回月球的时间限制。

    「迎接的人，会来我们家吗？」

    「不，大概会来月读世界。因为虚拟世界和月球非常接近。那里的话，不用派船也能轻易干涉。」

    月球的人……就是直播后袭击来的那些人型吧。如果那些家伙是在月球建立了高度文明的外星人，那他们在月读世界里种种超乎常理的行为也就说得通了。

    辉夜大概早就察觉到了吧。不，应该说是回想起来了。大概，是在被月人触碰到的那个瞬间。

    我握住辉夜手腕的手加大了力气。那种手臂，再挣开不就好了嘛。

    「再逃走不就好了嘛。」

    「诶？」

    「辉夜又不是辉夜姬。更胡来！更乱来！所以，和童话故事不一样嘛！」

    那种手臂，折断多少次都行。逃走不就好了嘛。为什么不叫我一起逃呢？那样才不像辉夜啊。像小孩一样哭闹撒泼不就好了嘛。那才是辉夜啊。你什么时候变得这么——

    「那样的话，就变成‘虽然是胡来的辉夜姬但也有迎接的人来，直到最后一天都过得超开心哦。故事完☆’。那样不也很好吗☆」

    你什么时候变得这么，像个大人了。

    又只有我一个人在哭。

    「这就是我的结局！超开心地奔向命运！」

    辉夜摆出英雄般的姿势宣告道。

    『除了接受并觉悟，别无他法。』

    那是我以前说过的话。被用那么漂亮的脸说出来，我就什么都说不出口了啊。

    烟花又绽放了。散开的光粒拖着尾巴，长长地垂挂在夜空中。

    垂柳，仿佛在流着光的眼泪。只有夜空在陪我一起哭泣。

    「说真的，本来呢。还想和彩叶一起，唱更多更多的歌。还想写很多新歌。啊，对了，想办演唱会！在迎接的人来的那天！要办得超盛大！」

    仿佛回应她的话语，盛大的“Star Mine”炸开了。

    辉夜目不转睛地盯着接连绽放的火花，

    「喔喔，震撼肚子！硝烟的味道！真棒——」

    绽放出不输给烟花的灿烂笑容。

    真可爱啊，辉夜。

    那之后，我们一直沉默地仰望着天空。

    直到烟花结束。直到周围的人都走光。直到只剩下我们两人。直到听见潺潺的流水声。

    「再不回家不行了哦。」

    直到辉夜静静地说出这句话。

    「不然，就回不去了。」

    如果是辉夜的心意，我必须尊重。越是这么想，就越是痛苦。

    ※

    看完烟花回来，辉夜立刻宣布了作为主播的引退和毕业演唱会。

    SNS瞬间沸腾，充斥着惊讶、悲伤和要求撤回的声音。随之而来的是各种号称要揭秘真相的，甚至混杂着阴谋论的解读，一片鬼哭狼嚎。

    辉夜对所有声音只回应了『虽然很开心，但到此为止了！』，此外一概避而不谈。

    『辉夜酱，不干了吗？』

    『辉夜酱，发生什么了吗？没事吧？』

    『辉夜酱，怎么了？有什么事跟我们商量啊。』

    真实、芦花，还有哥哥都发来了担心的私信，但既然辉夜那么说了，我也没什么好说的。

    『谢谢。没事的。』

    我只这样回复了。

    没有说任何谎话。辉夜只是要回月球去，辉夜只是要回家。那是早就决定好的事，而且辉夜也接受了，所以“没事”。

    而我，也只是要回到原来的日常生活而已，所以“没事”。

    ※

    升学学校的开学式极其简单地举行完毕，课程立刻就开始了。

    放学后马上就是兼职。即使在战场般的BAMBOO cafe，我也只是默默地完成工作。

    「酒寄小姐——！怎、怎、怎么办，我下错单订了四百个南瓜！已经不能取消了，完蛋了啦啊啊！」

    「对不起，店长！是我的错呜呜呜……」

    冷静点，店长和美绪。九月是南瓜的季节，我们开个临时南瓜祭吧。对了，没必要慌张，一切都在照常运转。

    「辛苦啦——」

    我在往常的时间结束兼职，像往常一样走在回家的路上。抬头望去，我们居住的塔楼公寓分割着暮色渐深的天空。

    辉夜不在了的话，那里也得搬出去了吧。又得找便宜点的公寓了。那样一来，一切都会恢复原状。完美女高中生，酒寄彩叶的和平日常就要回来了……

    「诶？」

    踏上人行道的脚猛地停住了。

    那里，是前不久和辉夜一起穿浴衣的和服租赁店前。那面曾映照出我们并肩浴衣姿的大镜子里，现在映出的是几乎要崩溃垮掉的我。

    只是，终于要回到往常的生活了而已。只是变回原来的我而已。可是……

    「……这是什么表情啊。」

    我试着碰了碰镜中自己的脸。冰冷、僵硬、无机质的脸颊。

    没错，要回到这个，日常中去了。

    「我回来了。」

    「欢迎回——」

    回到公寓，迎接我的是有气无力的声音。辉夜把脸盆拿到客厅，正在把手伸进去又缩回来，反复复复。

    「在干嘛呢？」

    「在吓唬螃蟹。看招——，是石头哦。怕了吧怕了吧。」

    真是的，到底在干嘛啊。

    我把书包放在餐桌上，看着玩螃蟹的辉夜。她长长地躺在地毯上，和螃蟹嬉闹。大概是舀水时太粗暴了，脸盆周围湿了一大片。

    「……呐，辉夜。」

    「剪刀——。这是平局——，运气不错嘛。」

    「要办毕业演唱会对吧。」

    「要办哦——。好啦，接下来…是最后一次了。会发生什么呢？」

    「新歌……要作吗？」

    「诶！？」

    辉夜猛地一下子跳了起来，胳膊撞到脸盆，掀起一阵大浪。

    「真的！可以吗？要帮我作新曲吗？」

    「嗯，可以哦。」

    「呀呼——！呀吼呀吼，哟——！」

    还好搬到了隔音好的公寓。辉夜带着近乎疯狂的表情做了个万岁姿势，然后输掉了和螃蟹的最终对决。

    「不知道能不能做好。想要什么样的感觉？」

    「就是那首没写完的曲子！」

    「诶？」

    我本想问问感觉方向，没想到她直接指定了具体的曲子。没写完的曲子也就是说——

    「你看你看，就这个就这个。」

    所以说不要随便开别人的电脑啦。辉夜几乎要戳穿屏幕般指着的，是『标题未定（与彩叶共作）』。

    偏偏是这首。一瞬间，感觉胃袋猛地沉了下去，但是，

    「知道了。」

    我深深地点了点头。

    「那我……要集中精神作曲了。」

    我对辉夜这样宣布后，把自己关在了房间里。

    作曲是多久以前的事了？我把手指放在键盘上，深吸一口气，任凭心意弹奏起来。悦耳的高音跃动而出。

    —— **没有成形却能成功的，真的只是极少数。现在可不是享受的时候。**

    自从被母亲那样说过之后，我就一直封印着钢琴。但是，真的仅仅因为那句话，我就远离钢琴了吗？

    —— **彩叶。**

    低音的节奏中，仿佛混杂着父亲的声音。

    一碰琴键，总会想起父亲。钢琴的声音就是父亲的声音。琴键是父亲的手指。盖在上面的红布，是父亲的头发吗？父亲总是在弹钢琴的我身旁，听我说很多很多话。

    —— **呐，爸爸。今天在幼儿园，被惠夸奖了哦。**

    —— **太好了。彩叶进步很快，是爸爸的骄傲哦。**

    —— **呐，爸爸。哥哥又说了奇怪的话。**

    —— **朝日那小子还幼稚着呢，彩叶你多教教他。啊，这话可别告诉朝日。**

    —— **呐，爸爸。妈妈陪我玩了。**

    —— **红叶是觉得彩叶太可爱了吧。**

    触碰钢琴，就意味着要面对已故父亲的回忆。幼小的我或许对此感到害怕。而将我从那种状态中解放出来的，是……

    双手手指的速度加快。如同倾诉般，将细密的音符连接起来。

    呐，爸爸。我有了很重要的人哦。非常可爱，非常邋遢，温柔又任性，会惹人生气，又会给我笑容的人。爸爸对妈妈，也是同样的感觉吗？呐，爸爸。你听得到吗？

    对爸爸来说，这个世界是怎样的呢？

    我对爸爸一无所知。一起生活的时间只有几年，记忆中的他总是笑着，总是为他人费心的样子。从未见他发怒、悲伤、或露出痛苦的表情。

    有时我会想，对于过于温柔的父亲来说，这个世界一定并不美好吧。

    父亲是死于事故。但是，那只是命运骰子偶然倒向了那边，说不定其实是……虽然也这样想过，但真相已经无人知晓。或许母亲知道一切。但无论背负着什么，那个人大概都会带到坟墓里去吧。

    那时是什么心情呢？为什么，要去了谁也话语无法触及的地方。抛下了妈妈，抛下了我。

    手指停了下来。如同演奏无声般的沉默，在昏暗的房间里扩散开来。

    「……呐，爸爸。」

    我啊，已经不想再失去重要的人了。

    精疲力尽的手指离开键盘，我握住了手机。收件人是芦花、真实，还有哥哥。

    『对不起，根本一点都不“没事”』

    以这样的开头，我给所有人都发送了信息。

    ※

    「嘎啊～～，辉夜酱居然是月球的公主……我懂！」

    你懂什么啊？

    虽然完全不明白他懂了什么，帝（明）抱着胳膊，频频用力点头。

    尽管是突然召集，不仅芦花和真实、帝，连黑玛瑙的队友雷和乃依，甚至八千代也都聚集到了月读世界内的户外会议室。

    我已经把所有情况都说了。辉夜从七彩发光的电线杆中诞生的事，是从月球来的外星人的事，下次满月会有迎接者来把她带回月球的事。

    说出来才发现，从头到尾都是可疑到不行的故事，但是，

    「原来不是筑地（Tsukiji）生的啊——」

    「去海边玩皮肤也还是雪白呢。」

    「从电线杆里生出来……我懂！」

    大家各自似乎都有能接受的点，异常顺利地相信了，反倒让我有点泄气。那么，接下来就是作战计划了。

    「八千代，不能保护辉夜吗？」

    月人会来月读世界迎接。作为月读世界的管理者，八千代或许有办法。

    「我试着查过，但连他们从哪里接入的都搞不清楚呢，抱歉。」

    「那么，取消演唱会，让辉夜酱一辈子不再登录这里，怎么样？」

    芦花的意见我也考虑过。但是，辉夜本就是像从电线杆里现身的某种存在，我觉得她和我们的生存机制不同。即使辉夜不去月读世界，月人大概也会强行、像是将现实的辉夜从这个世界“登出”一般，把她掳走吧。

    ……怎么办才好。所有人都陷入了沉默。绝望的气息开始弥漫在空气中，但是，

    「对方如果在现实中无法下手，那在月读世界里赶走他们不就行了？」

    只有帝，像没呼吸着同样的空气似的笑了。

    「什么啊，那表情。叫我们来不就是为了这个嘛。交给我们好了。管他是外星人还是什么，只要他们进到月读世界来，那就正合我意。把他们引进来吧，在这里我们可是最强的。用力量碾压他们，直到他们想滚回月球去为止。」

    多么暴论啊。毫无根据和道理，拿到哪里都毫不羞愧、如假包换的暴论，但是，

    「……我也干。虽然不知道能做什么……拜托了。」

    我也觉得除此之外别无他法，下定决心低下了头。月人，必须击溃。

    「好！那就准备吧，乃依。」

    「诶——，那个——？好麻烦——」

    「队长说了算。」

    「好啦好啦。」

    一旦方向确定，黑玛瑙的行动就很快。雷责备着闹别扭的乃依，开始着手将暴论成功的可能性哪怕提高百分之一。大概，一直以来他们三人就是这样将不可能化为可能的吧。毕竟曾经与他们为敌，我明白，黑玛瑙果然是最强的队伍。

    「彩叶，明年大家也一起去海边吧。」

    芦花微笑着说。

    「也去泡温泉吧！」

    真实也合掌笑着。

    「……谢谢。」

    而且，我还有芦花和真实在身边。此刻，这两人的笑容比什么都可靠。

    不知道能做到什么地步。但是，我要挣扎到最后。因为，她们让我心中点燃了这样的念头。

    「……啊，彩叶。欢迎回来——」

    从月读世界回来，一睁眼，辉夜理所当然般地在房间里，理所当然般地摆弄着我的电脑。

    「这个，感觉超棒嘛！」

    看来她擅自听了还在创作中的曲子。无论到哪儿行动都很有辉夜风格，反倒让我安心了。

    「歌词还在苦战，不过再一会儿就能完成了。」

    我一边取下智能隐形眼镜一边说道，

    「好期待——！真的好喜欢这个旋律～。彩叶是天才！」

    辉夜双手叠在耳机上，陶醉地望着天花板。

    「……不，不只是我。这个，是我和爸爸一起开始写的曲子。是第一首曲子。」

    「这样啊？」

    「爸爸去世之后……虽然也作了几首，但总觉得哪里不对，就都放弃了。」

    「这样啊——，不过辉夜很喜欢哦。彩叶作的所有曲子。」

    「谢谢。总之这首歌无论如何今天都要完成。」

    「那辉夜也来帮忙！我来替彩叶擅自写歌词吧。爸爸也一定会高兴的。“连邻居敲墙抗议都成了生活的热闹前奏～～♪”。嘿，这不也挺好的嘛？」

    好才怪……不，不过。

    「说不定……是挺好的呢。」

    会这么想，正因为是不可思议的辉夜吧。

    「副歌大概是这种感觉哦！“将这一瞬间～～变成最棒的派对～～”」

    「呐，辉夜。」

    「嗯？」

    「……不，没什么。八千代说愿意负责演唱会的演出。」

    「你拜托她的吗！？好耶——，我去想想舞蹈动作！」

    辉夜扔下耳机跑了出去。立刻从客厅传来啪嗒啪嗒乱闹的声音。这种时候辉夜也还是老样子。强大、自由、率直。可为什么却……

    「不，现在这样就好。我得把曲子完成才行。」

    我戴上辉夜扔下的耳机，面对电脑。

    真是不可思议。我不想失去辉夜。为此甚至暗中集结人手，谋划着击退月人的作战。而与此同时，我又在这样勤快地创作着毕业演唱会的曲子。大家知道了会怎么想呢。

    对不起。但是，我并没有放弃。这只是我个人，想送给辉夜的东西而已。

    「好了，来办最棒的派对吧。」

    为了继续作曲，我再次开始摆弄DAW软件。

    编曲完毕的副歌流入耳中。为了回应辉夜的请求，做成了节奏感强、速度偏快、充满疾驰感的旋律。

    试着合上刚写好的歌词哼唱起来。

    “将这一瞬间——变成最棒的派对——”

    「……诶？」

    我不由得漏出声来。

    停下音乐，倒回十秒。副歌再次开始播放。让人身体自然想动的轻快节奏。辉夜刚写的歌词。

    “将这一瞬间——变成最棒的派对——”

    「又来了……」

    违和感再次袭来。不，这不是违和感。是既视……感？

    再次倒回副歌开头。播放。这次清楚地抓住了。没错，就是这个感觉。

    那时，给前后无路的我，生出翅膀的感觉。

    疲惫的大脑不经意间编织出的感觉。

    仰望月亮，泪水零落的感觉。

    哭个不停的婴儿安然入睡的感觉。

    “重要的——旋律正在流淌——”

    —— Remember

    「同样的旋律？为什么……」

    八千代的出道曲。我无意识间抄袭了吗？是因为八千代的歌听得太多，无意识间混进去了吗？不，不对。这首歌是我和父亲写的曲子。当然，是在八千代出道很久之前。那么，是八千代抄袭？那也不可能。这首歌一直沉睡在这台电脑里，除了我和已故的父亲，连母亲都不知道。那么，是偶然。旋律的一个片段偶然一致了。仅此而已。

    「常有的事……对吧。」

    虽然这样说服自己重新开始工作，但违和感并未消失。

    总觉得遗漏了什么重要的事情，这种想法久久挥之不去。

    ※

    2030年9月12日，就这样平淡地到来了。

    迎接的人会在下午零点整到来吗？似乎只有我一个人在担心这种事，

    「彩叶，早上好——！」

    辉夜可恨地像往常一样起床，

    「哈，第二十三号辉夜！这是十五年里最美味的一顿。」

    像往常一样做出美味的午餐，

    「哼哼～～♪ 哼哼哼～～♪」

    在直播房间里哼着歌开始准备演唱会。

    如果这是最后一天，未免也太淡然了，但既然辉夜希望如此，我也无话可说。所以，我也尽量装作平常的样子帮忙准备直播，

    「……诶？」

    忽然注意到，吓得浑身一颤。

    辉夜不见了。只是稍微在意脚下低了下头，再抬起头时，就只剩我一个人了。

    骗人。触电般的恶寒贯穿身体。难道……难道。

    「辉夜！」

    「怎么啦？」

    在啊。辉夜从桌子底下“噌”地探出头来。

    「你在那种地方干嘛呢？」

    「嗯？这个掉了，我在捡。」

    她这样回答，把一直戴着的、刚才才捡起来的手链套在食指上转着玩。

    「别吓我啊。」

    我几乎要因为安心而跪倒在地。辉夜凝视着这样的我，

    「彩叶，爱操心～～。给，这个送你。」

    递出了刚刚捡起来的手链。

    「诶，这个不是」

    「八千代说了哦。这种东西要送给重要的人。所以，给彩叶！」

    「……谢谢。」

    「还有，我收到了名字！要回礼！」

    「……名字？」

    『名字是人生第一份礼物』……说起来，是我取的呢。

    「嗯。」

    辉夜点点头，笑了。

    如同万里无云的夜空，如同无人足迹的雪原般澄澈的笑容。并非一如既往，甚至感到一种从未见过的神圣。

    那其中可见觉悟与决心。并非，一如既往。

    「辉夜……」

    「我们走吧，彩叶。」

    我们手牵着手，潜入了月读世界。

    ※

    在演唱会会场的休息室里，我独自等待着开场。

    辉夜刚才被八千代带去了舞台。现在大概正惊讶于在《KASSEN》场地内搭建的特别舞台吧。

    我拜托八千代搭建的特设舞台，果然战场得是这里才行。

    「我回来啦☆」

    八千代毫无预兆地“噗”地出现了。我也已经习惯了，对八千代也好，对突然出现也好，都不惊讶了。

    「欢迎回来，辉夜怎么样？」

    「可高兴了。说燃起来了呢。」

    「这样啊。谢谢你，八千代。」

    「不客气，wink～～☆」

    八千代眨了个超大的眼，在空间里撒出星星。我一边望着那样的八千代，一边在心中寻找该说的话。

    「如果我要是八千代的话，辉夜会对我说不想回去吗？」

    本是无心漏出的一句疑问，

    「诶……？」

    八千代却瞪大了眼睛僵住了。我说了什么奇怪的话吗？

    「啊，对不起，莫名其妙对吧。忘了吧。」

    「不，没那回事。只是，吓了一跳而已……原来，是两情相悦啊。」

    八千代话语的含义，我并不太明白。但想必，那是我不了解的世界的谈话吧。

    『各部门，准备OK。』

    和那时一样，直播开始的信息显示出来。

    「那么，开始吧。……对不起哦，八千代被规定不能从这里再往前走了。」

    我并不惊讶。因为我本就觉得八千代是遥不可及的存在。无论有什么内情都不奇怪。

    「……因为是那样的命运吗？」

    那是八千代偶尔会用的说法。八千代没有点头，而是苦笑着

    「彩叶的话……没问题的！」

    说着毫无根据的话，做了个握拳打气的姿势。

    虽然不负责任但极其乐观，是辉夜会喜欢的风格呢。我一边想着，一边站起身来。

    好了，出征吧。

    ※

    『何等的超展开！仿佛超新星闯入月读的辉夜的毕业演唱会！现在不是哭的时候，这是最后的应援了！用眼睛好好记录下来吧！』

    自称辉夜推的月读世界官方解说忠犬御宅公，嘴上说着别哭，自己却明显带着哭腔对着麦克风怒吼。聚集到《KASSEN》场地特设会场的粉丝们也不甘示弱，发出火焰般的欢呼。

    然后，仿佛看准了会场内和通过屏幕观看的月读世界居民们的兴奋达到最高潮，数道聚光灯打在了舞台上。

    那中心出现的当然是，

    「大家，谢谢——！」

    今天的主角，辉夜姬。

    「今天好像就要告别了，但我不想弄得悲伤！大家一起来开心地送我毕业吧！」

    回应辉夜的呼声，粉丝们回以更热烈的呼声。

    接着，仿佛超越了极限的热量与声量撕裂了空间一般，数百朵花在空中绽放。观众们大概都以为这是演出吧，用掌声和欢呼迎接着花瓣炸开后现身的异形月人们。

    好了，这就迫不及待地来了吗。来迎接公主的月人混蛋们。既然大家都以为是演出，那正好，我们也混进去吧。

    如同挡住月人去路般落下的六颗桃子。模拟《KASSEN》重生点现身的，是

    「好了，让我们热闹起来吧！」

    「……只要赢就行了。」

    「还挺有意思的嘛。」

    帝率领的黑玛瑙，以及

    「辉夜酱——，耶——！」

    「辉夜～看这边看这边～！」

    美妆网红ROKA，和美食网红真实真实，也大驾光临了。当然，彩P酒寄彩叶也侍立在旁。

    『黑玛瑙来了！曾经交锋过的黑玛瑙，为了辉夜的最终演唱会赶来了！』

    特别嘉宾的出现让会场沸腾到顶点。怒涛般的欢呼声淹没了芦花和真实的话语，但是，

    「……辉夜。」

    现实中就在身旁的我的声音是不同的。我睁开眼睛，把手放在辉夜肩上，凑近她耳边。

    「就当是演唱会的余兴节目。我们会全力以赴的。万一赢了，我们就去唐吉诃德大采购，做堆满一切的松饼。」

    「彩叶……」

    辉夜也睁开了眼睛。

    我们的意识暂时离开了月读世界，在昏暗的直播房间里，橙色的眼眸彼此相对。辉夜把她的手叠在我的手上，

    「这样啊……这样啊……大家，都是自由的呢！」

    她露出向日葵般的笑容说道。

    那笑容就是开始的信号。我们再次闭上眼睛潜入月读世界。辉夜拿着麦克风走向舞台，我则拿着之前辉夜制作的那个能同时演奏和游戏的键盘走向战场。

    入侵已经开始。和上次来的类型从外观就完全不同，模拟七福神般的人型月人成群结队地逼近。不知何时学会了规则，头上显示着符合《KASSEN》规则的剩余次数。

    简直就像文明人屈尊配合未开化部族的祭祀活动一样嘛。

    正好。既然你们肯奉陪，我们就奉陪到底。

    「回来了啊，彩叶。别乱冲，那些家伙防守看起来很坚固。」

    「哥哥？」

    正要踏出一步的我被帝（明）拦住了。他察觉到我的意识中断了几秒吗？他拔剑出鞘，摆出保护我的姿势。

    「……啊，谢谢。」

    「什么啊，最近怎么这么坦率了。是开始直播后终于明白老哥的伟大之处了？」

    「才、才不是那样。」

    我从帝的防护下离开，这么说道。

    「你一直在躲着我吧。」

    他视线不离月人地问道。

    「……你注意到了？」

    「算是吧。偶尔会看看嘛。」

    「那算什么？为什么你……」

    「嘛，因为是哥哥嘛。」

    帝（明）只一瞬间回过头来，他的虚拟形象上，重叠了过去哥哥的面容。虽然调皮但很机灵，被所有人喜欢的哥哥。每当我和母亲冲突时，总会不知何时飘然介入我们之间的哥哥。

    ……一直都在关心我吗？

    我还以为被抛弃了。在他离开家的那一天。还以为他已经不需要我了。什么嘛，真是的。

    「……像个傻瓜。」

    这时，尖锐的破风声刺入耳中。抬头望去，几乎覆盖天空的冰箭正从头顶掠过。看来月人进入了乃依的射程。

    「走了，彩叶。久违的兄妹会议哦。」

    帝用京都腔说道。

    「哇，好怀念。」

    被他一带，我的回答也带上了京都口音。

    兄妹会议。还住在老家时，我们兄妹玩游戏就是这么叫的。每次和母亲冲突后消沉时，哥哥总会叫我去开兄妹会议。然后，毫不留情地把我虐得体无完肤。

    「那时候真开心啊——」

    一点都不开心好吧。

    「那时候总是两人一起打游戏呢。」

    现在不也还在打嘛……

    「我以为什么都没变，但有一件事变了哦，彩叶。」

    「我？」

    「你变得会依靠哥哥，依靠别人了，我很高兴哦。」

    「……是因为有个什么事都跑来依靠我的家伙在嘛，受她影响吧。」

    月人开始反击。作弊级的长距离光弹撕裂天空。

    「是吗。那，可得让她一直留在这里才行啊。」

    说完，帝（明）冲入了弹雨之中。雷、乃依紧随其后。最强的三叉戟撕裂了月人的军势。

    芦花和真实也开始了迎击。

    我也要冲进去，冲进铺满地面的庞大军势中。敌我战力差距悬殊。即便如此也要前进，给予我们力量的，是

    『用更冲动的音——用更富感情的歌——』

    从舞台传来的，辉夜的歌声。

    呐。你看得到吗，辉夜？这就是我们哦。是辉夜从月球窥视的地球人哦。

    随心所欲地行动，复杂，仅此一次，自由。

    我并不真的认为我们能赶走来历不明的月人，那些能从电线杆里生出婴儿的家伙。

    但即使如此，现在听着辉夜的歌战斗，却感到一种不可思议的一体感和快乐。简直像祭祀的舞者，我们持续舞蹈着。

    才不会，让它变成坏结局。

    ※

    挥动了多少次武器呢？击破了多少个月人呢？

    心意驱使着身体，突破极限。

    近乎无限的能量，引发出近乎无限的力量，近乎无限的速度。

    但是，只是“近乎”。

    并非真正的无限。不像月人那样。

    「呃……」

    首先，雷倒下了。遭受犯规级别的集中攻击，连箭塔一同消失。

    「没完没了呢。」

    乃依拼命地继续狙击，但月人大军压上，将她吞没。两人立刻就会重生，但剩余次数应该都是零了。

    「彩叶……！」

    「对不起……」

    接着，真实和芦花也倒下了。

    「就这点本事吗？外星人混蛋。我和彩叶可还站着呢。」

    还坚持着的只剩我和帝了。但，这又能维持到何时呢？

    阳光忽然被遮蔽了。抬头望去，头顶显现出一尊月人。

    好巨大。模拟传说巨兽的巨大月人挥舞着锡杖，正从空中落下。

    简直像陨石。我被撞击的爆风吹飞，在地面翻滚。但是，

    「——！」

    帝（明）纹丝不动。虽然遍体鳞伤，却用一把剑挡住了月人的下落攻击。

    「哥哥！」

    「……雷、乃依，要用了。」

    「遵命。」

    「好——」

    从全身喷涌出足以扭曲空间的能量，帝（明）

    「哦啦啦啊！」

    就这样凭蛮力挥臂，将月人的巨大身躯打飞到了遥远的高空。简直像要送它回月球一样。

    什么啊，这异常的攻击力。还有，他脸上浮现的不祥纹样……这难道是。

    『作弊模式！就在刚才，确认到黑玛瑙的帝（明）、雷，接着乃依也使用了作弊模式！』

    忠犬御宅公大声嚷嚷，观众席一阵骚动。

    果然是作弊模式。从程序层面干涉游戏，强制将所有攻击状态提升到破坏平衡级别的作弊技巧。当然，这是禁用技巧，一旦使用就会被月读世界方面自动封禁，失去一切才对。

    他们竟然为我做到这个地步，我胸口一热。

    「还远远没完呢！」

    突破了极限的黑玛瑙，再次将月人推了回去。

    但是。即便如此。仍然不够。

    月人如同无限的泉水般显现，以数量的力量压倒地球人。

    「这里交给我！快跑，彩叶！」

    我只能跑向辉夜身边。

    跑过去又能如何呢。虽然明白，但还是跑了。至少，想在辉夜身旁——正如此奔跑的我，被

    「——」

    突然出现的月人重重包围。

    接着，辉夜的歌声停止了。

    尾声淡出，舞蹈停止。

    仿佛等待着这一刻，天空的颜色变了。仰望的天空被月人的大军覆盖了。他们随时都能传送这种规模的兵力吗？或者，他们或许真的只是等待着歌声结束。并非战斗，而是如同仪式一般。

    辉夜浮现出领悟一切般的微笑，接受了败局。那表情，竟有几分像八千代。

    「……辉夜。」

    我已经跑不动了。月人也并未继续叠加攻击。他们甚至稍微后退，好让我能看见辉夜的身影。

    过了一会儿，一个月人走到唱完歌的辉夜面前，恭敬地跪下。辉夜像迎接旧友般，

    「远道而来，欢迎。」

    毫无芥蒂地说道。

    「我逃跑了，对不起。但是，真的，真的，很开心哦。」

    抬起头来的月人表情没有变化。但不知为何，看起来像是在微笑。

    然后，辉夜开始上升。

    乘上脚下出现的光云。由众多月人和狗狗DOGE陪伴着。缓缓地，升上天空。向着月读世界的月亮。

    「这是最棒的毕业演唱会！收到了好多好多礼物。大家，谢谢！」

    她向涌来的粉丝们挥手。

    「诶嘿嘿，虽然依依不舍，但到此为止了。还有就是……」

    「彩叶。」

    现实的肩膀上落下了温暖。脸颊、肩膀、胸口、后背，被温暖包裹。

    是辉夜。辉夜在拥抱我。

    我睁不开眼睛。因为我知道，这是最后了。

    腿上的力气在流失。快要瘫倒的身体被辉夜支撑住。

    不知不觉间，已经长得这么大了呢。明明那时候还那么小。明明小得可以捧在手心里。明明会因为肚子饿而哭，想出去而哭，想玩、想在一起而哭个不停。现在却只有我在哭。

    等等，别走。

    明明还有那么多，想做的事……

    「……最喜欢你了。」

    咣当一声，有什么东西掉在了直播房间的地板上。膝盖一软，我瘫坐下来。

    我抱紧了自己的身体。为了不让残留在身上的、辉夜最后的触感消失。

    即使我紧紧抱住自己，紧到皮肤都要发出悲鸣，那份温暖，还是慢慢地消失了。

    「大家，辛苦了。真的谢谢……我先下了，对不起。」

    大概，我这样说着，登出了月读世界吧。

    回过神来，我站在现实世界的直播房间里。总之，为了不让大家看到眼泪，为了不让努力过的大家失望，我拼命装作平静的样子，但有没有成功，我毫无自信。

    我取下智能隐形眼镜，走出房间。

    瞥了一眼玄关，踏上昏暗的走廊。关上半开着的浴室门，穿过厨房，来到客厅。在那里环视四周。

    到处都有辉夜的身影。

    乱脱的鞋子，一直蔓延到走廊的直播用杂物，浴室飘出的香气，出刃菜刀，冰箱上贴着的简易食谱和注意事项，渗入墙壁的笑声。

    整个家，都充斥着辉夜的痕迹。

    某天突然到来，将完美的我的生活搅得天翻地覆，又某天突然消失的外星人。

    「又随便花钱。又胡搞乱来。又不收拾。一直一直，都碍事得很。真的，最差劲了。」

    口袋里的手机通知响了。是辉夜的汇款通知。

    『用掉的钱，还你！给你添麻烦了』，上面写道。

    「这么多钱，我怎么花得掉啊。笨蛋……」

    我跪倒在客厅的地板上。

    无法抑制的泪水，溢了出来。

** 终章

    雨是从那天黎明时分开始下的。

    不对，说实话，我根本不记得究竟是从什么时候开始下的。只是碰巧在早晨注意到了这场雨而已。我蜷缩在客厅里，抱着膝盖，听着雨声。除了雨声，什么也听不见。

    抬起头，厨房里能看到辉夜像挥舞指挥棒一样挥动着汤勺的身影。

    「糟糕——，今天感觉也要做出杰作了♪」

    沙发上，是胡乱拨弄着木吉他、边弹边唱的辉夜。

    「呐，听听看。辉夜也试着写了歌哦！《刘海剪过头之歌》！」

    走廊里，是辉夜啪嗒啪嗒跳着谜之舞蹈的样子。

    「看呀看呀，这是现在SNS上流行的。好不容易才学会怎么跳，但现在一看动作完全不对嘛。笑死。」

    走进直播用的房间，耳边响起了辉夜挥舞着荧光棒看偶像视频的声音。

    「呜嘿——，这孩子好可爱～～。舞跳得超棒——！我要是加入这个团，会是金色担当吧？」

    我站起身，走遍公寓各处，一一触碰辉夜留下的残渣。一边花时间确认着与辉夜的回忆，一边将所有东西收拾起来。

    不能再继续住在这间公寓里了。当然有经济上的原因，但更重要的是，我无法带着这么多“辉夜”继续前行。

    浴室里传来辉夜央求着“一起洗嘛”的声音。厕所里则是拿着平板电脑把自己关在里面、迟迟不出来的辉夜。玄关处，辉夜听到对讲机响便跑了过去，和快递员聊个没完。

    我就这样与每一个“辉夜”相对，回忆起种种往事。在太阳升起又落下同等次数之后，我终于来到了空无一人的客厅。

    这里的墙壁，原来是这种颜色啊。

    我在莫名显得陌生而疏离的角落里再次抱膝坐下，让自己的身体适应新的空气，然后冲了个澡，睡了整整一天。

    醒来时，已经听不到辉夜的声音了。再也没有需要收拾的地方了。大概，是时候该向前看了吧。

    第二天早晨，我换上制服，把脚塞进乐福鞋。

    「我出门了。」

    我的声音空洞地穿过冷清的走廊。

    ※

    「啊，是酒寄同学。你的新冠已经好了吗？」

    「咦，你不是去留学了吗？」

    「太好啦——！我还真不信你说结婚了呢！」

    看来，在我无故缺勤的这几天里，各种流言蜚语满天飞。我也没法一个个去否认，便一概用“早上好”应付过去，径直走向教师办公室。然后，我首先向立花老师鞠躬道歉，交上了一直没能提交的升学志愿调查表。

    「……果然，还是法学部啊。」

    老师端详了一下我的脸，然后拿起了调查表。

    「对不起，发生了各种各样的事……」

    「酒寄你以前太完美了，现在这样，我反而有点放心了。」

    「不过，已经不要紧了。我要以法学部为目标，下次能请教一下备考策略吗？」

    「当然可以。」

    说着，立花老师又露出了他那如陈旧山羊般的笑容，结果到最后，他也只字未提我无故缺勤的事。

    走出教师办公室，在走廊上等待芦花和真实来上学，

    「一直没回消息，对不起！」

    我一阵风似的冲过去低头道歉。

    「真的对不起！超级对不起！那个，该怎么说呢，那个……真的，对不起！」

    我找不出任何借口，只能在走廊上不停地鞠躬道歉。

    「无视我们，好过分——」

    「我们都想杀到你家去了哦。」

    两人像开玩笑似的，佯装生气。

    「对不起！对不起！」

    我更深地低下头去，

    「……我们啊，」

    「只要彩叶你没事就好。」

    真实和芦花苦笑着这样说道。

    「谢谢你们，对不起。」

    「不过话说回来，脸色真差。是不是没好好吃饭？哇，皮肤也糙糙的。」

    真实碰了碰我的脸颊，有些悲伤地抚摸着。

    确实，这几天可能只喝了水。

    「好！那，为了庆祝彩叶复活，我们去吃饭吧！我会监督你好好吃完的。」

    「不错耶。要不今天就……啊真实今天不行吧。那就明天晚饭。去上次那家咖啡店，彩叶请客哦。」

    芦花以迅雷不及掩耳的速度敲击着手机屏幕，瞬间将真实的提议升华为预定行程。这配合真是绝了。

    「不过，那家怎么样？BAMBOO咖啡店的南瓜主题季！我想去那个。」

    「不行啦，那不是彩叶以前打工的地方嘛。你会介意的吧，彩叶？」

    「嗯……没关系哦。」

    我刚要回答，上课铃响了。「糟了——」两人异口同声地喊着急忙跑开。我也跟着一起跑……咦？

    脚步停下了。脑海中的疙瘩让我的脚停了下来。

    她们俩，为什么会知道南瓜主题季？

    起因是澪酱的错误订货而开始的BAMBOO咖啡店南瓜主题季。这家店主打住宅区隐秘咖啡屋的概念，没有SNS账号，也没有官网。按说，不去店里是没法知道这个活动的。

    「彩叶，你在干嘛啊！」

    「要迟到了。我们还没放书包呢！」

    两人在楼梯前焦急地跺着脚。

    难道……她们来过了？去了BAMBOO咖啡店。因为担心我。

    不，应该不止这样。不可能特意跑一趟，却只去我打工的地方。她们肯定最先去了我的公寓。我的公寓有自动锁，我不应门的话是进不来的。对讲机响过……吗？也许响过。但是，我没有应答。所以，被拒之门外的两人只好去了BAMBOO咖啡店。

    「彩叶，我们先走了哦！」

    比这句话更快，我跑了出去。跑过去，

    「呀啊！」

    「怎么了？」

    紧紧抱住了两人的身体。

    「对不起。」

    「诶，彩叶？」

    「对不……起。」

    「你怎么了？」

    现在，我终于意识到了。自己是多么地任性。自己是多么地傲慢。

    「对不起。」

    被无声的对讲机拒之门外，该是多么空虚。被朋友吃闭门羹，该是多么难受。得知心意只是单方面的，该是多么悲伤。

    「喂彩叶，真的要迟到了啦。」

    即便如此，两人还是对我笑了。没有责备我，还笑着把『我们都想杀到你家去了哦』当成了玩笑话。

    「真的……对不起。」

    现在，我终于明白了。直到现在我才明白，一直以来两人有多么为我着想。无论是带我去咖啡店的时候，还是邀我去海边的时候，又或者是叫我去看烟花的时候。

    「彩叶。好了，别说了。」

    「别哭了。我们最喜欢你了。」

    我一直以为自己是一个人活过来的。来到东京，一直以为靠自己的力量活着。愚蠢的我，直到现在才发觉自己被两人支撑了多少。

    「谢谢你们……芦花，真实。」

    眼泪像傻瓜一样涌了出来。三个人在走廊上抱在一起哭着。在今后的人生里，我会一直告诉你们，我有多么珍视你们。

    要一直做朋友哦。

    ……彩叶。

    眼睑深处，仿佛看见了辉夜的笑容。

    我的辉夜。谢谢你。虽然我至今仍不明白你为何会出现在我身边，但你拯救了我。你改变了我。

    真不可思议呢。和辉夜经历了各种各样的事，生过很多气，发过很多火，也添过很多麻烦，但即便如此，总觉得从一开始就喜欢你了。辉夜呢？

    眼睑深处的辉夜只是笑着，没有回答。

    我啊，不会忘记辉夜的。无论过了多少年，多少十年。即使有一天，这个笑容从眼睑深处消失了，我也绝对不会忘记。

    我会将和辉夜的回忆珍藏心底，向前迈进的。

    如同童话般与辉夜共度的日子结束了，日常回到了彩叶身边。

    这便是彩叶，与辉夜姬的故事。

    可喜可贺，可喜可贺

** 续・终章

    话是这么说，怎么可能就这样结束嘛——！

    好险——，差点就结束了。差点就落幕了。

    怎么可能就这样算了！怎么可能就这样结束！

    我并不是在撒谎。刚才的心情全都是真的。

    但是，已经没有什么日常可以回归了。没有辉夜的日常，已经不成其为日常了。

    「怎么可能就这样结束啊啊啊！」

    「呜哇！」

    我“砰”地一声推开教师办公室的门，立花老师“噌”地一下从椅子上弹了起来。我就这样冲到老师的办公桌前，一把抢过刚刚提交的升学志愿调查表。

    「对不起！请让我再考虑一下！」

    「……请慢慢考虑。」

    在老师略带退缩的目光目送下，我离开了教师办公室。然后径直跑回了公寓。明明完全没有必要跑，明明并没有什么特别着急的事，但我还是跑了。像是要把过去的自己、逡巡、迷茫、恐惧、犹豫，以及其他种种都抛在身后一样地跑了。

    『不需要什么幸福结局。普通的结局就可以了。』

    怎么可能。

    『这就是我的结局！超快乐地向着命运奔跑』

    怎么可能。

    『我会将和辉夜的回忆珍藏心底，向前迈进。』

    「怎么可能——！」

    我冲进直播用的房间，拖出刚刚才收好的键盘。然后把电脑、耳机、能量饮料以及其他各种东西都搬了进来，

    「开干了！」

    带着一种再也不会回到人类世界的气势关上了门。

    「啊，在那之前。」

    同样的错误绝不重复。得联系芦花和真实，还有BAMBOO咖啡店。我分别给挚友们和打工的地方发送了内容截然相反的邮件：对挚友说“我又要请几天假但人没事所以别担心”，对打工的地方说“得了流行病动不了所以暂时没法出勤”。

    回复很快就来了。

    『真实：收到。明天的饭怎么办？』

    『芦花：延期不就好了嘛，等公主殿下心满意足了再说。不过作为交换要好好吃饭哦！』

    『澪酱：酒寄前辈，店长告诉我了。请别担心，好好休息。之前您关照了我那么多，这次的缺口全部由我来填补！』

    谢谢你们，真实。芦花。澪酱。

    「大家，谢谢！」

    我大声地道出感谢，对着手机鞠了一躬。然后，重新面向键盘。通过键盘，面对自己和辉夜。

    呐，辉夜。我啊，有话要对你说。有无论如何都必须传达给你的事。你啊，说过的吧，在烟花大会那天。

    『还想、还想，和彩叶一起唱更多歌啊』

    「我也是啊，还想……」

    还想一起唱更多歌。还想说更多话。还想一起玩更多、去更多地方、看更多不同的风景、一起笑更多次。

    「还想，和辉夜在一起更久！」

    我要把这份思念写成歌。你现在，在哪里呢？在月球上吗？在宇宙中吗？无论在哪里我都要送去。送上这首饱含我全部思念的曲子。把力量借给我吧，爸爸。

    我把手指搭在键盘上。就在这时，仿佛早就等着这个时机一样，手机震动了起来。

    是来电。不可思议的是，我大概猜到是谁打来的了。屏幕上显示的是——

    『妈妈 来电』

    我毫不犹豫地接起了电话。

    「喂——」

    「啊，终于接了啊。没骨气的家伙。」

    不等我说完第一句话，一道不合时宜的、冷冰冰的声音便刺入了我的耳朵。

    「你知道我打了多少通电话吗？因为是个胆小鬼所以害怕说话是吧？听说你连学校都没联系就擅自休息了啊。真是了不起的大小姐做派呢。你以为自己是一个人在活吗？你知不知道，你一个人停滞不前，会给多少人添麻烦？不把这种以自我为中心的想法改掉，没人会认同你的。大家只会暗地里庆幸你自生自灭罢了。」

    停不下来，停不下来。真厉害啊，还是老样子。即使把手机从耳边拿开，那说教声也清晰地传来。感觉手机电量都在飞速下降。就是这样，不让我有任何回话的机会，连珠炮似的步步紧逼，一味地罗列我的瑕疵，这就是妈妈的做法。哥哥说让我左耳进右耳出就好，但我做不到。我也有我自己的做法。

    「……对不起。」

    但是，这次怎么想都是我不好，所以开场只能从道歉开始。不过——

    「没有反驳就道歉可不行哦。我可不是那种被人一道歉就沉默的软弱之人。还是说，你把我当沙袋了？」

    区区一句道歉是无法动摇母亲的。这一点我早就明白了。

    「听我说，妈妈。」

    「……行啊。……说话小心点。根据你接下来要说的内容，我可能会做出不可挽回的决定。」

    「……明白了。」

    「说吧。」

    短暂的沉默后，我深深地吸了一口气。我知道冗长的铺垫是没用的。

    「……我，成不了妈妈理想中的样子。」

    「……」

    「我，一直都很努力来着。为了能和妈妈平等地对话。为了能和妈妈再次成为一家人。但是啊，我明白了。妈妈和我是不同的人啊。想要拥有同样的心情，从根本上就是不可能的。但是……这样就好。」

    「……」

    「妈妈，我想找到自己真正想做的事。不是为了得到谁的表扬，也不是为了得到谁的认可，而是想找到自己真正想做的事。我想把我的人生用在那上面。」

    「是吗。」

    「不过，我也没打算要你为我加油。但是至少，请给我……找到它之前的时间。」

    我握着手机低下了头。明知对方不可能看见，但还是深深地低下了头。母亲沉默了很长时间，然后，

    「太天真了。你从以前开始就——」

    当然，她的态度没有丝毫动摇。

    那之后，就变成了一场单纯的争吵。一场隔着手机、跨越两百公里直线距离的争吵，最终，

    「行吧。」

    母亲突然这么说道。

    「试试看吧。只是，做喜欢的事是要负责任的。到底适不适合自己，到最后也未必知道，最坏的情况可能落得在无人知晓的地方孤独死去的下场。可别忘了这点。」

    只留下这句话，她便单方面挂断了电话。恐吓我、吓唬我，只能用这种方式来表达担心。妈妈她啊。

    我像瘫倒一样横躺在沙发上。

    「……说出来了。」

    说出来了，对妈妈。

    不可思议的是，心中并未涌起任何感慨。若是以前的我，能得到妈妈的认可，恐怕会高兴得飘飘然吧。

    「这样啊……」

    我心中最重要的东西，早就已经改变了。

    有点寂寞，又有点高兴。这究竟是怎样的感情呢。

    我试着侧耳倾听脑海中的声音，但已经听不到妈妈的声音了。

    那之后，月亮升起又落下了好几次。

    我将睡眠和吃饭以外的时间和精力全部倾注在键盘上，

    「……完成了。」

    它诞生了。

    痛苦挣扎、备受煎熬，但最后却仿佛被月光引导一般，顺顺利利地完成了。

    「爸爸，谢谢你。」

    ……我啊，确实享受了整个过程。

    我抱起刚刚完成、仿佛还在脉动着的曲子，站起身来。

    打开窗户，赤脚踏上月光照亮的阳台。这是一个无风的夜晚。抬头望去，左半边隐没在黑暗中的月亮正俯视着我。

    辉夜，你正从那里看着吧？会听我唱吗？可能唱得不是很好。但我拼命把它做成曲子了，我的全部心意。

    我用双手包住从辉夜那里得到的银色手链，那在月光下煌煌闪烁的辉夜碎片，吸入了夜晚的空气。

    「──昨日的延续──想对你说──哪怕微不足道──也正合时宜──让我听听真心话──只因想要将其实现──」

    我一遍又一遍，反复地唱着。

    想着辉夜。想着与辉夜共度的日子。

    不知不觉间，歌声不再只有一道。

    是两个人在唱。你还是老样子，记曲子真快啊，辉夜。

    是和辉夜一起在唱。不是幻听。确实能听见。是辉夜的声音。

    『那辉夜就再来一次！』

    在笑着。在奔跑着。唱吧，无论多少次。

    我又开始唱了。这次是两个人。两个人……咦？

    「这个声音是……？」

    我听到了本应不可能听到的、第三个人的声音。

    这是什么。闯入只属于我和辉夜世界的、第三个人的声音。我并没有去想“这是谁的声音”。因为我绝不可能听错这个声音。但是，为什么她的声音会……

    「──啊。」

    就在那时，夜空中划过一颗流星。仿佛受到吸引一般，我的脑海里也划过流星。一颗，又一颗。它们化作无数的闪光，照亮了我脑海中的每一个角落。

    很奇怪。从一开始就觉得很奇怪。

    明明舍弃了音乐的我，为何会被她的曲子吸引。

    她的曲子，为何能如此深刻地渗入我的内心。

    她为何，会唱出和我创作的曲子相同的旋律。

    还有，为何她总是像知晓未来的命运一般，静静地微笑。

    所有的“为何”汇聚成一点，

    「八千代……」

    我呼唤着我仰慕之人的名字。

    ※

    「八千代最近在练习捞泥鳅舞哦～。超有趣的舞蹈，介绍给大家看吧。那么，要开始咯。啊，就这个♪　啊，嘿咻♪」

    这是自辉夜的毕业直播以来，我第一次潜入月读世界。

    往来路边的屏幕上，一如既往地播放着八千代的直播，有几个虚拟形象驻足观看。其中也有几个人在笑，但那是重播。对于追完了八千代所有活动的我来说，一眼就能看出来。这可是头一回。

    果然，八千代出了什么事。想确认却电话邮件都联系不上。我抱着一缕希望来到月读世界，但果然，还是没能见到八千代……。

    「──嗯？」

    什么，刚才那是？视野边缘有什么东西动了。像是察觉到我一样逃走了。我下意识地追了上去。

    「等等！为什么就你一个——」

    居然能跑得这么快？那东西灵巧地在巷子里窜来窜去，最终跑进一条死胡同才终于停下。

    「她在哪里，告诉我。」

    我向着终于停下的FUSHI询问道。

    理应在八千代身边的FUSHI，理应与八千代一心同体的FUSHI，

    「……」

    沉默地回过头来。紧闭着嘴，一动不动地回看着我。看来不打算回答。那好吧。

    「我自己去找。」

    我扔下这句话转身要走，

    「笨蛋。」

    FUSHI终于开口了。

    「你要去哪里找？」

    「如果你不告诉我，我就找遍全世界。」

    听我这么回答，FUSHI用小小的眼睛盯着我，

    「……睁开眼睛看看。」

    眼睛？一瞬间没明白它什么意思，但我试着睁开了眼睛（指现实中），

    「这边。」

    为什么？FUSHI在房间里。现实世界我的房间里，FUSHI正引导着我跑起来。我立刻意识到智能隐形眼镜的AR功能是开启的。没时间多想了，我穿着家居服就追了出去。

    FUSHI仿佛对现实世界了如指掌，轻快地穿梭在街道上。拐过街角，跑下坡道，甚至利用电车，最终把我带到了某栋公寓的一个房间前。

    门没锁。我慢慢地推开门，

    「……这是，哪里？」

    迎接我的是沉闷淤积的热气。

    这里大概可以称作服务器机房吧，大量的电脑、存储设备和网络设备杂乱无章地塞满了空间。虽然散乱得毫无章法，但那种散乱方式却又有点似曾相识。房间中央是——

    「水槽……？」

    咕嘟咕嘟冒着气泡的水槽和注满的谜之液体，沉在里面的东西是……竹笋？我思考了几秒，但怎么看都像竹笋。那是什么啊。越看越像竹笋，但越看越无法移开视线。知道却又第一次见的感觉，这是——对了。就像第一次见到月人时的感觉。

    「这个，就是八千代。」

    「……诶？」

    「从这里，进入月读世界。」

    我按照FUSHI说的，闭上眼潜入月读世界。稍微，花了点时间。感觉和平时不一样，就像从后门偷偷潜入一样的感觉——。

    「……」

    那里是一个从未见过的房间。

    无数的灯笼散发着朦胧的光芒，从隐约可闻的风声可以判断这里楼层相当高。

    一个特别、看起来舒适、却又有点寂寞的房间。

    大概是某个人的私人房间吧。很可能，就是此刻背对着我坐在这里的，那个人的。

    「……辉夜？」

    那长发披散在地板上的背影，让我想到了辉夜。

    很像辉夜。但是，转过头来的——

    「八千代」

    ──是她。

    我将脑海中如天启般降临的、荒谬的推论，抛向了月读世界的歌姬。

    「八千代，就是辉夜吗？」

    「……」

    「我知道我在说奇怪的话。但是……」

    八千代惊讶地睁大眼睛，随后露出了淡淡的微笑。

    然后，她缓缓地站起身。

    「话说从前——」

    接着，开始讲述起来。用一如既往的八千代的方式。

    「回到月球后，过着社畜生活的、了不起的辉夜姬那里，收到了一首歌。那是为辉夜姬创作的、只属于辉夜姬的歌。」

    是我的歌。

    「辉夜姬高兴极了。于是想着再去一次地球吧～～，就把工作光速处理完，交接也全部完成。只是，按照地球的时间来算，已经太迟了。但是，不用担心。月球的超科技也能超越时间。穿越时空，辉夜姬向着地球出发。但是，就在快要到达的时候，撞上了一块超～～大的石头。」

    ……。

    「哎呀～，果然时间旅行这种事，就算是超科技也超级难控制呢～。……飞船受到了致命损伤，濒临坠毁。千辛万苦终于到达的地方，是大约八千年前的地球。」

    ……。

    「依靠破损飞船的微弱力量，只有同行的狗狗DOGE获得了身体。它变成了一只恰好在附近游动的海蛞蝓。辉夜只能通过海蛞蝓，与世界进行交流。」

    ──我就这样僵立着，甚至没能完全理解自己正在听什么。

    「时光流逝，人类将看不见的事物化为有形，获得了与许多人连接的力量。那与月球的世界有些相似，辉夜第一次知道，仅仅是灵魂状态的自己也有可能与世界产生联系。于是，作为虚拟世界月读世界的歌姬，再次与彩叶相遇了。」

    ……和我？难道说——

    「嗯，和彩叶。」

    这么说着，八千代像是搞砸了大事一样拍了拍额头，

    「唉呀呀～～，这样一来就不能皆大欢喜、可喜可贺了吧～，果然♪」

    用开玩笑般的语气笑了起来。

    一如往常的八千代的笑容。

    「……那和我在一起的辉夜是？」

    我问道，八千代只是稍稍松动了笑容，

    「如今，也在同样的轮回中循环着。」

    她有些寂寞地这样说着，仰望着月读世界的月亮。

    「我们无法从那个轮回中脱离。」

    或许，那也可以说是一张自嘲的脸。

    「……我完全不明白。」

    我完全无法理解。不，是不愿理解。八千代在说什么啊，同样的轮回？这种，这种荒唐事……。

    也就是说，我所知道的辉夜，我的辉夜……。

    「我完全，不明白啊。」

    难道说，现在正在八千年前的地球飘荡着？

    孤零零一个人？被我的歌声所吸引，为了来见我——。

    「只是个童话故事啦，别想太多～～。总之现在先庆祝重逢吧☆」

    八千代开玩笑似的笑着，牵起了我的手。我感觉到她似乎在说，不能再想下去了。

    就这样，我被带到了阳台。这房间似乎位于相当高的地方，从阳台可以将月读世界的夜景尽收眼底。

    「八千代真的超级喜欢从这里看出去的景色哦。」

    八千代张开双臂，像是要拥抱夜景一般说道。月读世界的风嬉闹般地拂动着她长长的发丝。和风很亲近这点，也和辉夜一样。

    真美啊，我不禁看呆了她的侧脸。

    「为什么……？」

    「嗯？」

    「为什么，八千代能一直笑着呢？」

    将如此重大的、荒唐无稽的故事，当作往事咯咯笑着讲述的八千代。但是在我眼里，不知为何，总觉得八千代像是在哭泣。

    「因为这就是八千代呀。」

    快得让人觉得她早有准备。我猜想，那既是对某种现实的逃避，也是她的真心话吧。

    八千代又爱怜地俯瞰着月读世界的夜景，

    「但是啊……」

    抓着栏杆的手指在颤抖。

    「明明约好了，要带你去幸福结局的。」

    手指的颤抖传播到手臂，

    「明明听到彩叶的歌声才回来的。」

    蔓延到肩膀，

    「对不起，搞砸了。」

    最后，连声音也颤抖了。

    「闪闪发光的辉夜姬，已经变成老奶奶啦。」

    尽管如此，八千代还是笑着。

    没有流下一滴眼泪，笑着哭泣着。

    「……辉夜。」

    辉夜才不会露出这样的表情呢。

    漫长的沉默之后，八千代小心翼翼地开口了。

    「彩叶，如果你不想知道的话，忘了也可以哦。这种事情FUSHI也能做到——」

    「八千代！」

    连我自己都惊讶的大声喊了出来。我自己也不明白原因。但是，觉得非常——悲伤、寂寞、又气愤。

    八千代睁圆了眼睛看着我。我转过身，咚咚地踩着脚走回房间。带着要踏破地板的气势，一屁股坐在木地板上，

    「说给我听吧。」

    「诶？」

    「八千年间，发生的所有事，都说给我听吧。」

    「诶诶？」

    「我，不会睡的！」

    「……真是乱来呢。」

    八千代仿佛稍稍年轻了一些般地笑了。

    八千代像挥手一般动了动，方才所在的房间，变成了我住过的IR公寓。桌子上放着点心和可乐，简直就像我和辉夜一起生活时那样。

    但我已经不再惊讶了。因为首先踏进这一步的是我。

    「那，就先从和绳文人一起抓鱼的故事开始吧。记得很清楚的是，叫长角虾来着？胡子超长的虾真的超珍贵呢。就算不煮也是鲜红的，真想做成寿司啊。还有大月鲶！只有在有月亮的夜晚才能抓到的超大鲶鱼！用柴火一烤，油脂就像拧湿毛巾一样滋滋冒出来。然后然后——」

    说啊说啊。连续不停地讲了差不多整整两天，

    「该休息啦，彩叶。会死人的。」

    我当然也到极限了，但还是逞强地回答「还早着呢，还早着呢」。

    「快睡！快睡！」

    被FUSHI的闹钟打断，八千代像断了线的木偶一样倒下睡着了。

    我小心翼翼地靠近躺在木地板上的八千代。虽然没有呼吸声，但眼睑确实闭着。大概，是睡着了吧。

    「八千代的活动极限是五十二小时。为了充电、更新和整理记忆，需要定期进入休眠状态。」

    FUSHI跳到八千代的身体上说道。

    「……八千代原来这么健谈啊。以前总是听我说，我还没见过她这样。」

    「总是，咯咯地笑着。」

    我摇了摇沉重无比的头，在睡着的八千代旁边坐下。睡梦中的八千代脸上仍然带着笑容。我温柔地抚摸着她的头发。带着爱怜，带着慰劳。

    「……不可能全是开心的事吧。」

    花了八千年，把强颜欢笑变成习惯了呢。

    变得和我一样了呢。

    「呐，FUSHI？」

    「……」

    「八千代还有隐瞒的事，对吧？」

    「……」

    这条深思熟虑的海蛞蝓没有立刻回答。经过一段漫长、漫长的沉默后，

    「……如果八千代没说，那也许就……」

    「让我看看。我必须看到辉夜的全部。」

    「人类的躯体未必能承受。」

    「无需多言。」

    之后，FUSHI又陷入了沉默。但这次的沉默，看起来并不像是在犹豫答案。

    「八千代她……刚才，露出了好久不见的、真正开心的样子。」

    「嗯。」

    「出发咯哦！」

    海蛞蝓的眼睛发出了红光。在仿佛被激光视线照射的瞬间，房间就像积木倒塌一样开始分崩离析。

    然后，我的身体开始下坠——

    『八千代，你在哪里对吧？出来吧……救救我……』

    「辉夜！」

    瞬间与辉夜的意识同化，飞向了八千年前的地球。

    ※

    ……这里是，哪里？

    回过神来，我在一片无人的沙滩上。

    ……为什么，会在这种地方？

    我记得，应该听到了歌声才对。

    听到了彩叶的歌声，想起了地球的一切，制作了自己的复制体，然后和公主协力也造好了飞船，唱着歌出发了。

    ……对了，撞上了陨石，设备误操作了……呃啊，这失控的时间溯行算法是谁开发的啊——！啊～，是负责人辉夜啊～，计算明明完美无缺的真是遗憾至极，纸上谈兵，这里难道是地狱深渊吗～！

    ……彩叶。

    ……我好像，搞砸了。

    ……彩叶！

    想喊出声，却发现发不出声音。

    ……彩叶！

    想跑过去，却发现动弹不得。

    ……彩叶啊！

    看到水面上映出的样子，才发现自己没有身体。

    啊，这下糟了。自动的『拟态』没能成功。

    月人是没有肉体的思念体。所以，月制飞船“原光之竹”会调查着陆星球的环境，为乘员赋予最优化的肉体。那么说来，找不到依代的话，我就会像幽灵一样？呜啊啊好虚无～。

    功能坏掉了吗？

    ……“原光之竹”，请应答。

    不是吧～。

    ……“原光之竹”，请应答。

    明明模拟了所有可能性啊，是辉夜酱我能力不足吗？

    ……“原光之竹”，请应答！

    真的假的。发不出声音，看不见身影，无法离开这里，连我自己编程的最强外壳也无法消散？

    ……彩叶。

    我甚至连抱头都做不到。

    每当理解现状，思考就逐渐变得清晰。我将发生在自己身上的事逐一梳理，仔细对照现状，

    ……啊啊，搞砸了呢。

    我慢慢地、花着时间，陷入了绝望。

    那之后，不知过了多少年。

    晨来夜往，烈日灼晒，大雪纷飞。这样的事重复了多少次呢。感觉不到炎热也感觉不到寒冷的我，只是呆呆地坐在浪花拍打的岸边。抱着并不存在的膝盖。

    在仿佛永恒的时间里，我一直唱着歌。在脑海中。唱着唯一的一首歌。

    ……将这一瞬间，变成最棒的，派对吧。

    然后，在不知第几千次重复时，

    「──」

    听觉捕捉到了什么。

    这是，什么。非常微弱、缥缈、又令人怀念。

    「──」

    这是人的声音。

    抬起头，沙滩上站着一个男孩子。是个小孩子。他正侧耳倾听。能听到我的声音？

    「──」

    男孩子回头看向身后。是被谁叫住了吗。不行，别走。留在这里，听我说话。求你了。

    这样的思念是如何连接上的呢。我的意识进入了海蛞蝓狗狗DOGE的身体，

    「等一下！」

    男孩子回过头来。那张意志坚强的脸让我联想到了某个人。看起来语言不通。果然这里和与彩叶在一起的世界不同吧。是遥远的未来，或是来到了过去。

    对于思念体的月人来说，解读和再现当地语言并不是什么难事。只是，用这个身体无法充分发声，沟通很困难。我用和彩叶在一起时擅长的肢体语言，很快和男孩子成了朋友，一起玩耍。每天每天，直到男孩子突然不再出现为止。

    怎么了呢。我拖着海蛞蝓的身体去看他，男孩子一个人躺着。脸色很差。冒着冷汗。和彩叶那时倒下时一样。看起来非常痛苦。但是，为什么没有人照顾他呢？医生呢？药呢？

    「──」

    男孩子像说梦话一样漏出话语。唱给我听吧，我听起来是这样。

    虽然不知道从海蛞蝓身体里发出的声音算不算歌，但我竭尽全力唱着，他看起来像是微微笑了一下。所以，我继续唱着。直到男孩子不再痛苦，直到他不再动弹。即使谁都不在了也继续唱着。

    又变成一个人了。如果这里，是远比彩叶所在世界更古老的地球，我还能在遥远的未来再次与彩叶相遇吗？从目前这完全摸不着头脑的状况来看，感觉很难有确切的预测。

    八千代，你在哪里对吧……八千岁什么的果然是骗人的？救救我啊。

    当然没有任何回应。

    时间，比想象中流逝得更快。

    在市井被不断砍价的行商、用墨汁染黑手指书写故事的文人、只一味吟咏情歌的歌人、满脑子只想着税收和战争的官吏、每逢战事便更换旗帜的将军、甚至连牛耳京城的豪族们——所有人都一样，最多不过五十年左右，就像从屏幕上淡出一样，悄然逝去。

    战争，也真的很多。如果把人类的历史用日历颜色区分，恐怕大多数的格子都会被火焰、呐喊和鲜血的红色填满。

    城池的燃烧、海边的冲突、无名村庄的掠夺，从远处看都不过是同样的红色斑点，但每一次，都有谁的孩子、谁的恋人、谁的“未来”消失，而我，只能默默地注视着。

    这与月球上的生活，形成了过于鲜明的对比。

    在那个早已解开所有方程式的世界里，没有人衰老，没有人真正争斗，没有人死亡。

    就像永远凝视着一个被完美设计、连一丝波纹都不会兴起的巨大水槽。所以，我花了很长很长的时间，才接受了“终结”这仅有一次的概念。

    无法用肌肤感受季节的变迁，无法流泪，也无法改变任何人的命运。

    只是用这小小的柔软身体，随着潮水摇荡，几千年如一日地目送着人类诞生又死去。

    我也曾喜欢上许多人。爱上我的歌人、在空袭后的废墟上持续卖花的少女、两人三脚以成为花魁为目标的游女。我总是无可救药地爱上那些赌上性命生活的人们的觉悟。

    每次想起没能拯救的人们，内心就会留下无法消失的抓痕。

    如果我能更好地传达。如果能设法引导。

    啊——，那个时候，就算有不开心的事，也能立刻忘记的。

    那个无所不能的最强辉夜，已经不存在了。

    ……彩叶，无法从软弱的自己身边逃离，原来是最可怕的事啊。你眼眸深处那种彩色的意义，我现在似乎能明白了。

    人类随着战争不断发展科学技术。电话、冰箱、收音机、显像管。最终，创造出了万维网。

    我用海蛞蝓的身体笨拙地在聊天输入框里输入“Hello, world！”并发送。立刻就收到了“Hello, you.”的回复。这让我大为震撼。

    因为，我甚至开始模糊地记不清与彩叶一同度过的、那个虚拟世界的事情了。

    ……那个天才的辉夜酱，没有月球的基建，也只能做出这种程度的东西呢。

    嘛，算了。我扭动海蛞蝓的身体编写程序。写html。也做访问分析。

    如果技术进一步进步，能够将“原光之竹”直接连接到网络，或许就能超越这个身体的限制，与大家、与更多的人交谈了。

    我带着不可思议的心情，感受着逐渐淡薄的记忆开始重新构成确切的形态。

    对了，总有一天，想创造一个虚拟世界的巨大广场，让大家能做喜欢的事、没有杀戮、没有人孤独、随时都能得到回应的地方。

    对了，名字叫——我恍然大悟。

    ……我真是个笨蛋啊。为什么一直没注意到呢。——我要，成为八千代。这个世界一定在无数次地重复着这个循环。

    与此同时，我确信自己一定能与彩叶重逢。就在，接下来的几十年内。海蛞蝓那微小心脏怦怦直跳。

    但是彩叶。我，已经不再是原来的辉夜了。开玩笑的次数也变少了。即使渴望重逢，那形式也已不再是月球上梦到的那种华美模样。

    ……即便如此，这首歌、这个约定、这份思念，会将我带到那个地方。

    在那段漫长的漂泊岁月里，我偶然结识了一个男人，他成了海蛞蝓形态的我最后的朋友。他不仅耐心解读我笨拙的发言，甚至坦率地告知我他自己是CIA职员。是的，我需要协助者。为了与彩叶重逢。

    我做好被嘲笑的准备，坦白了自己的来历，结果他带着那招牌式的、有点坏的笑容回应道：“我就猜到了。”

    我们推敲计划，精心准备，我恳求他。“请帮我把保存在正仓院的‘原光之竹’偷出来。”而他只是板着脸点了点头。他明明也有自己的工作要做，这究竟是罕见的善心，还是单纯的好事之徒呢。

    「不跟我一起来吗？」

    一切结束后，他在机场对我说。他本可以挟持“原光之竹”，强行把我带回国，但

    「我有约定要完成」，我这样回答后，他便独自飞回了祖国。

    「极品的葡萄酒，时光会使其风味愈发醇厚。也并非全是坏事。」

    那句话，以及他掩饰时嘴角上扬的笑容，长久地留在了我的心里。

    ──好了，准备就绪。我完成了虚拟空间月读世界的原型，在发布的同时举行了个人直播。曲目当然是，一直唱个不停的那首歌。八千年来几经变奏的、和彩叶她们并肩作战时的那首歌。

    第一次直播，观众人数远不及记忆中的八千代直播，但我开心得不得了。时隔八千年能再次唱歌，让我无比喜悦。

    之后我又开了很多次直播。从未感到厌倦。今天，那孩子可能会来吧，光是这么想着，每次直播都让我心跳加速。

    每一次，我都在观众中寻找那孩子。那个初始虚拟形象的女孩可能是她。一开始可能是用哥哥的账号登录的。也可能是借了朋友的虚拟形象。说不定，是那只猫？

    总是，总是在人群中找到那孩子，然后歌唱。

    就这样，那一天终于来临了。

    ──彩叶。

    我想你一定会哭吧。虽然这么想着，但直到最后，我都在笑着歌唱。

    ……这样啊，所以八千代才总是那样快乐地、笑着呢。

    ※

    「彩叶，彩叶。」

    从脑袋外面传来了声音。是我的声音。我的声音在呼唤那孩子的名字。

    「彩叶！」

    啊，不对。这个声音不是我。

    睁开眼，八千代就在眼前。

    「八千代……」

    「笨蛋……会坏掉的啊……」

    眼前是八千代泫然欲泣的脸。

    以前也有过这样的事呢。担心逞强的我而哭泣的辉夜。过了八千年，又做了同样的事呢。

    「……辉夜。」

    我抱紧了八千代。

    我无法不将两人紧紧拥抱。

    「对不起，一直没能注意到。」

    「彩叶。」

    「让你等了那么久。一直寻找着我。」

    「……彩叶。」

    「对不起。」

    八千年，一直都很想哭吧。

    「终于追上你了。」

    我最喜欢的辉夜。我的辉夜。花了非常非常漫长的时间，逐渐变成了八千代呢。

    经历了令人眩晕的孤独与绝望，重复了数不清的相遇与等量的别离，将那份温柔的笑容刻在了心中呢。

    「追上的人，是我才对……」

    八千代在我耳边呢喃道。

    「呐，彩叶。彩叶的脸真的非常漂亮呢。我啊，立刻就喜欢上了。」

    用辉夜般的声音呢喃着。

    「坚强、凛然、又带有一丝悲伤的，美丽脸庞。但是，彩叶也一点点变成了彩叶呢。经历了痛苦，每一次都变得更强一些，成为了彩叶呢。理解这一点，却花了八千年。」

    「八千代……」

    我松开了紧抱着辉夜身体的手。我想从正面看看八千代的脸。

    「我，成长了呢？连和妈妈都能说上话了，即使辉夜不在了，也能拥有一个十足的幸福结局……故事，已经结束了。」

    八千代之中存在着辉夜。存在着收容了辉夜的八千代。

    看着那样的脸，

    「想和辉夜在一起……」

    我有生以来第一次，说出了发自心底的愿望。

    我有生以来第一次，察觉到了自己真正的心情。

    「彩叶……」

    八千代哭了。那坚强、凛然、又带有一丝悲伤的女神脸颊上，滑落的是积蓄了八千年的泪水。

    「……明明想着，就这样结束也可以了。」

    『──将这一瞬间变成最棒的──派对吧──』

    八千代唱道。

    「我一直都记得。」

    『珍视的旋律正──流淌着哦──在你的──心间──』

    我也唱道。

    「靠这首歌，我才能活下来。」

    八千代和我，两人同时举起手。

    辉夜和彩叶的联手手势。好朋友的那个。

    只要这个还在，无论过去几千年，我们都一直在一起。

    八千代就这样牵起了我的手。然后，有些寂寞地说道。

    「我在想，如果能触碰到的话，会不会是温暖的呢。」

    ……我总是，从八千代那里获得温暖。

    「还想，再和彩叶一起吃一次，松饼呢。」

    但是，八千代一直——

    那一瞬间，有什么贯穿了我的身体。

    然后，我理解了一切。

    明白了，还没完呢。这个故事还有后续。

    「我找到想做的事了！」

    我这样说着，站了起来。感觉全身的细胞仿佛一齐苏醒般充满了力量。这是什么，这股能量。就这样站着都让人焦急。现在就想立刻跑起来。

    「要陪我直到真正的幸福结局哦！」

    我宣言道，八千代则一脸呆滞地仰望着我的脸。

    或许，当我听到辉夜乱来的要求时，脸上也是这样的表情。

** 新・终章

    「过年的时候不是大家一起去爷爷奶奶家了吗。就我和妈妈两个人待着的时候啊，她对我说：“走路小心点，别被绊倒了。”」

    安静的研究室里，我正在和哥哥通电话。

    「我都多大岁数了，她还说这种话！？真是吓我一跳——」

    「嘛，那人估计到死都是这样啦。我前阵子也难得收到她邮件，就回了句“哦——哟！”」

    「该不会是说乃依君的事吧？」

    「就是。她好像到现在还对没孙子抱这件事耿耿于怀呢。」

    「什么嘛这是——」

    我们开怀大笑，确认了碰头的事宜后挂断了电话。从那之后，已经过去了十年。成为研究者的我，不知不觉间甚至获得了所长的头衔。或许是认为我已经自立了，妈妈那长篇大论的说教邮件和无休止的连环call都销声匿迹，只剩下偶尔见面时的一点唠叨。

    黑玛瑙至今依然活跃。哥哥和乃依君一起生活。雷先生说想看看各个国家，好像一有空就到处旅行。芦花成了超人气网红，现在是品牌大使，街头巷尾的广告上都能看到她的身影。真实大学毕业后，就和从高中开始交往的男友结婚，成了双胞胎的妈妈。大家虽然都有各自的辛苦，但每次听到近况，都觉得她们过得很快乐，我从心底感到高兴。

    「在傻笑什么呢？有什么好事吗？」

    支在一旁的平板电脑上，八千代的脸被放大了。看来，直播刚刚结束。

    「欢迎，时间刚刚好呢。」

    「那当然☆ 咦？大家呢？」

    八千代像从窥视窗里张望一样，从屏幕里窥探着这边的情况。她说的“大家”，是指这个实验室的职员们。

    「我让他们稍微早点去吃午饭了。今天看来会是一场持久战，得让他们好好休息才行。」

    「真不愧是被业界称为异类的良心研究所呢。」

    「嘛，我也因此得以休息了。」

    「……今天，会很久吗？」

    「大概吧。」

    「终于要～～？」

    「嗯。」

    我们一起望向横躺在床上的虚拟躯体。这是赶工完成的试制品第一号『辉夜』。今天，是首次启动实验的日子。

    「让你久等了十年。」

    我凝视着床上躺着的辉夜，对八千代说。

    「跟八千年比起来，简直就是一眨眼哦～～」

    ……但是，我不想再让八千代等待了。

    「彩叶，你紧张吗？」

    「不紧张。试制品第一号嘛，本来就是预着会失败的。是为了找出哪里不行而进行的步骤！这种感觉。得飞速修正，然后不断增加能做的事才行。」

    「这样啊～」

    八千代沉默了片刻，然后，

    「谢谢你，彩叶。为我孕育了辉夜。」

    她用罕见的认真口吻说道。

    「简直像童话一样呢～从竹子里发现辉夜姬的老爷爷，十年后居然真的生出了辉夜，可喜可贺☆」

    「啊——这个！先说好，十年前你叫我老爷爷的事，我可还没忘哦。」

    「八千代可是八千年前的事，早就忘光啦～～」

    两人咯咯的笑声，混入了研究室里充盈的装置驱动声中。虽然不可能，但床上的辉夜仿佛也在微笑。

    「……多亏了八千代，我才能走到这里。」

    「八千代也是哦。追着彩叶，才来到了这里。」

    「两个人互相追逐着啊，呵呵……」

    说完，我把空咖啡杯拿到水槽去。正轻轻冲洗着，水声中传来了八千代哼唱的声音。本来没打算洗得那么仔细，但还想多听一会儿她的歌声，于是又在海绵上挤了洗洁精。

    「──珍视的旋律正──流淌着哦──在你的心间──」

    多么清澈的歌声啊。它贴近我的心，驱散了所有的不安。就像海浪的声音，又像心脏搏动的声音。

    温柔、温暖、令人安心的八千代的歌声。

    那大概，是我曾经从母亲身上渴求的东西。在已经斩断了对母亲依赖的今天，我明白了，对我而言，八千代就是——

    「谢谢你。下次，轮到我了哦。」

    我用谁也听不到的声音说道。

    紧接着，对讲机响了。

    「啊，是实验室的大家回来了吗？」

    「谁知道呢？」

    结果，出乎八千代的预料，耳机监视器上出现的是——

    「彩叶——，我们到啦！」

    越发漂亮的芦花。

    「哟吼～」

    一如既往开朗的真实。

    「哟。」

    我的哥哥。

    「好热。快点招待我们啦～」

    我行我素的乃依君。

    「……」

    无言地举手致意的雷先生。

    久违地聚在一起的、热闹的一群人。

    「诶！大家都来啦～☆ 是彩叶叫来的吗？」

    「算是吧。虽然出资金额有多有少，但大家都是出资者嘛。初次亮相，不邀请一下可说不过去。」

    才怪呢。

    其实，只是想让大家都来庆祝辉夜的第一个生日。

    「大家，进来吧。」

    解除门锁后，走廊立刻传来了叽叽喳喳的喧闹声。我深深吐出一口气，回头看向平板屏幕上映出的八千代。

    「呐，八千代。说实话可以吗？」

    「什么什么？」

    「其实啊，我紧张得心砰砰直跳，都快叫出来了！」

    「八千代也是～！其实早就等不及啦！」

    我们两人的笑声，又一次回荡在研究室里。

    距离可喜可贺、可喜可贺，只差最后一步了。

    ＥＮＤ

