#+title: 刀剑神域 第四卷 妖精之舞
#+setupfile: ./setup.setup
* 第四卷 妖精之舞

** 序章

台版 转自 anglegamer@SOSG论坛

昂首仰望，可以看见微暗的远方有几道闪烁的光芒。

但那不是星星，而是由宽广岩洞顶端垂下来的无数冰柱所发出的微弱磷光。也就是说目前所在位置是在地底洞窟中。问题在于这个地底洞窟的规模实在太过于惊人了。

由所在地到屹立在远方的壁面，换算成实际距离单位大约超过三十公里。而到达顶端的高度最少也有五百公尺。平面上则散布无数的断崖、峡谷，以及冻结成一片雪白的湖泊与雪山，此外甚至还可以见到一些零星散布的山寨与城堡。

这种规模早已经不能称为洞窟，而应该称之为地下广场，不对，应该是「地底世界」才对。

实际上也是如此。因为这里是处于精灵国度阿尔普海姆地底的另一个区域，同时也是被恐怖邪神级怪物所支配的黑暗与冰之世界。它的名字便是——

「幽兹海姆」。

** 第五章

「哈啾～！」

发出一声不该出自女孩子口中的粗鲁喷嚏声后，风精灵族的少女剑士莉法急忙用双手掩住嘴巴。

她迅速看了一下出口的方向。心里担心刚才的喷嚏声会不会让落单的邪神给听见，接着它那恐怖的大脸将会出现在入口。幸好只有轻飘飘的雪片从入口吹入。当雪片在靠近小庙地板上的营火时，马上就在空气中融解了。

莉法将厚重的外套衣领拉紧之后，退回到庙里墙壁边蹲了下来。接着「呼～」一声叹了口气。她用力眨了几下眼睛，才把温暖营火带来的睡意从脑袋里赶出去。

这间石造小庙是个长宽大概只有四公尺左右的狭小空间。墙壁和天花板上吓人的怪物浮雕在晃动的火焰照耀之下也跟着扭动，那种模样让人看了实在心慌。但是莉法往旁边一看之后，就发现那个将背靠在墙上席地而坐的同行者，正以非常安稳或者应该说是一脸蠢样地打着瞌睡。

「喂，快起来——」

莉法一边小声说着一边拉了一下对方尖锐的耳朵，却只有得到同行者的几句梦话响应。至于另一名伙伴小妖精，则是已经在他膝盖上缩成一团睡着了。

「喂，睡着就会直接登出啰——」

莉法又拉了一下对方的耳朵。结果同行者的头直接就往莉法大腿上一躺，然后开始蠕动找寻最舒服的位置。

莉法吓得挺直了背部，双手在空中不断开合，心想着到底要怎样打醒他才好。

不过话说回来，在这种状况之下也难怪他会打瞌睡。

因为出现在视线下方的现实世界时间早已经超过凌晨两点。通常莉法自己在这种时候也早已登出，然后在床上熟睡了。

是的，这座幽兹海姆——以及位在其上的一整片阿尔普海姆并不是真正的异世界。它们是构筑在服务器内部的假想世界，而服务器目前应该放置在真实世界里日本国首都东京的某处。

莉法和同行者都是使用一种名为「AmuSphere」的游戏机来完全潜入这个世界。

要脱离这个假想世界其实相当简单。只要左手的食指和中指一起往下一挥，然后在出现的主选单窗口上按下「Log Out」按键就可以了。或者是只要在这个地方熟睡，当机器探测出脑波变化时便会自动中断联机。而早上便会在现实世界的床铺里醒来。

但现在因为某些原因，使得他们必须抵抗强烈睡意来让自己保持在清醒状态。

因此莉法只好狠下心来用左手握着拳头，然后朝同行者那尖尖的头发正中央敲了下去。

「哐当」的轻快效果音伴随着肉体攻击的特殊黄色效果闪光响起，同行者也发出奇怪的叫声跳了起来。莉法微笑着对用两手按住头部到处乱看的他说道：

「早安啊，桐人。」

「早、早安…………」

同行者是个有着浅黑色肌肤与一头黑发的守卫精灵族剑士，名叫桐人。原本有着少年漫画主角那般豪放面容的他，这时却以一脸沮丧的表情问道：

「……我睡着了吗？」

「还靠在我的大腿上哩。只捶你一拳算是便宜你了呢。」

「……那真是不好意思。为了道歉，莉法也可以在我大腿上睡……」

「不用了！」

她用力别过头去，不断斜眼瞪着桐人。

「别再说蠢话了，赶快用你在梦里想到的好主意来脱离这鬼地方吧？」

「梦……你这么一说我倒想起来了……我差点就能吃到巨大的水果奶油布丁了呢……」

「我真是傻了才会问你这个问题」莉法一边这么说一边无力地垂下肩膀。接着她又看了一下小庙的入口，结果还是除了在黑暗中随风飞舞的雪片之外，就没有别的动静了。

至于为什么会无法登出，那是因为莉法、桐人以及在他膝盖上呼呼大睡的小妖精结衣，现在都被困在幽兹海姆这个地底世界，没办法回到地面上去。

当然他们可以随意离开这个游戏。但是这座小庙既不是旅馆也不是安全地带，所以就算意识回到现实世界，没有灵魂的游戏角色也还会残留在现场一段时间。

而被留下来的游戏角色可以说非常容易吸引怪物。在这种情况下一旦遭受袭击，角色便只能毫无抵抗地减少HP，没两下就会「死亡」然后被送回存盘地点「司伊鲁班」去。这么一来，他们远道由风精灵领地到这里来就变得毫无意义。

莉法和桐人的目的是到阿尔普海姆的中央都市「阿鲁恩」去。

他们是今天正确来说应该是昨天晚上才由司伊鲁班出发。两人飞过广大的森林地带，穿越漫长的矿山隧道，还击退了敌对势力火精灵的袭击。最后在风精灵领主朔夜的感谢中与他们告别时，已经是超过凌晨一点了。

途中虽然去上了几次厕所而休息了一下，但这时也已经连续潜行达八个小时。

这时央都阿鲁恩看起来还在遥远的彼方，不可能马上就到达。于是莉法他们便决定让旅途先在这里告一段落，到附近村落的旅馆里登出游戏。因此他们便降落到刚好映入眼帘的森林村落里。

当时就算麻烦，也该叫出地图来确认一下村庄的名称与里面究竟有没有旅馆才对。想不到——

「没想到——竟然整座村庄都是怪物的拟态……」

似乎刚好回想起同一段记忆的桐人叹了口气之后这么说道。莉法也跟着叹了口气后点了点头。

「就是说啊……到底是谁说阿鲁恩高原没有怪物出没的！」

「好像是莉法你说的吧……」

「我不记得有说过这种话。」

他们俩持续着这种无力的斗嘴，然后又一起叹了口气。

莉法和桐人降落到神秘村落里时，刚开始只是怀疑怎么没有任何居民——也就是NPC的影子。但是当他们觉得至少会有旅馆的店主而准备进入最大建筑物的瞬间……

构成村子的三栋建筑物全部同时崩毁。他们还没时间为忽然变成光滑肉瘤的旅馆感到惊讶，脚下的地面就忽然裂开，底下则是不停蠕动的暗红色洞窟。没错，在他们眼中看起来像村庄的物体，其实是埋在地面下的恐怖巨大蚯蚓怪物，利用嘴巴周边突起物变化而成的诱饵。

莉法和桐人，以及在桐人胸前口袋里的结衣全被这股强烈的吸力给吞噬。当他们被巨大蚯蚓的光滑消化管不断向前搬运时，莉法心想如果就这样被胃酸溶化的话，可以确定这绝对是她玩ALfheim Online一年来最糟糕的死法！

所幸莉法他们并不合蚯蚓的口——正确来说应该是不合它的胃才对，在历经三分钟左右的消化器官之旅后，终于被它给排放了出来。莉法一边因为全身沾满黏液的感觉而起鸡皮疙瘩，一边准备用背后翅膀来减低掉落速度时，却又发生让她更为惊恐的情形。

她竟然无法飞行。就算肩胛骨再怎么用力，再怎么让翅膀震动也无法产生浮力。她和接着被排出来的桐人便在不知名的微暗中直线落下，最后「磅！」地一声埋在深深的雪地里面。

莉法拼命挣扎后，终于将脸由雪地里拉出来。此时首先映入眼帘的，是一整片广阔的岩壁，取代了原来有着月亮与星光的夜空。当她心里想着「呜哇，原来是洞窟，所以才飞不起来」，然后绷着脸环顾四周时，立刻发现眼前的雪原上有抬头才能看清楚的异形正缓慢移动当中。那无疑是在照片里才见过的「邪神级怪物」。

待在她身边的桐人原本正张开嘴巴准备大叫，但莉法在急忙全力按住他嘴巴的同时，也了解自己究竟来到了什么地方。自从潜入ALO后，她首次来到这个一望无际的地底世界，同时也是难度最高的练功场「幽兹海姆」。也就是说，那只巨大蚯蚓不是要捕食玩家，而是为了把玩家强制移动到这个冰之国度的陷阱。

好不容易躲过足有五层楼高的多脚型邪神后，莉法他们才狼狈地找到这间小庙并躲进来避难，接着还在里面讨论起该如何应对目前的状况。但是在这个无法飞行的地方，可以说根本没有简单的脱出方法，所以这一个小时以来他们只能蹲在墙边盯着营火发呆——这就是他们目前的状况。

「那个……别说离开的方法了，我根本连这个幽兹海姆是什么样的练功场都不知道啊……」

好不容易才将瞌睡虫赶跑的桐人，用恢复锐利视线的黑色瞳孔，边看着外面的黑夜边这么说道。

「在到这里来之前，风精灵领主她们确实提过这个地方对吧。当我把手里的金钱交给她们时，她们确实说过『要在幽兹海姆进行野营狩猎来打倒邪神等级的怪物，才有可能赚到这种金额』这种话吧。」

「啊——嗯，确实说过。」

莉法一边点头一边回想。

在被大蚯蚓吞进去的不久前，正当风精灵族与友好的猫妖族正在举行领主会谈之际，敌对种族火精灵趁他们不注意时前来偷袭这次的聚会，莉法和桐人由敌人的大部队手中解救了两位领主。当时桐人还把巨额的金钱交给领主她们，表示要让她们拿去当成军队资金。收到大量货币的风精灵领主朔夜当时确实曾说过这样的感想。

「……话说回来，桐人你是在哪里赚到那么多资金的？」

面对莉法这突如其来的问题，桐人支支吾吾了一阵子后才这么回答：

「那是一个以前对这个游戏非常着迷，现在已经砍账号的朋友送给我的……」

「这样啊……」

确实常常听说砍账号的玩家会很大方地将装备与金钱送给朋友。莉法似乎可以接受这样的说法，于是又回归本题说道：

「刚才说到哪了？对了，就算朔夜曾这么说又怎么样？」

「没有啦，既然领主都那么说了，那就表示也有玩家在这个练功场进行狩猎对吧？」

「好像是有没错……」

「那就表示除了刚才那只巨大蚯蚓的单向通路之外，也有能双向通行的道路存在才对啰。」

莉法这时才理解桐人究竟想说些什么，于是她点了点头后回答说：

「应该是有没错……虽然说我也是第一次到这个场所来，所以并没有实际走过，不过央都阿鲁恩的东西南北确实都各有一座大型迷宫，而迷宫最深处就有通往幽兹海姆的阶梯。地点是在……」

莉法挥了一下左手叫出选单，然后把地图显示出来。几乎是圆形的幽兹海姆平面图虽然被显示出来，但由于莉法几乎没有到过里面的任何区域，所以除了现在所在地的周边之外全部都是一片灰色的状态。她说完之后便用右手食指依序在平板地图的上下左右各指了一下。

「应该是在这里、这里、这里和这里。我们现在的小庙是在中央与西南壁的中间左右，所以最近的应该是西边或南边的阶梯。只不过……」

她耸了耸肩后继续说道：

「有阶梯的迷宫里面当然都有邪神守护着。」

「那邪神大概有多强呢？」

面对桐人这种不知死活的问题，莉法先是横眼瞪了他一下后才继续说道：

「就算你再怎么强，这次也是派不上用场的。据说这个练功场开放之后马上就冲进来的火精灵大队，在遇上第一只邪神时立刻就被全灭了。连你刚才经过一番苦战才获胜的尤金将军，听说独自一个人遇上邪神也绝对撑不过十秒钟。」

「……那可真是棘手……」

「据说现在要在这里进行狩猎，至少要有负责防御的重武装玩家、高歼灭火力的玩家、担任支持•回复的玩家各八个人才能够存活。像我们这两个轻装剑士，只够出去让邪神一脚踩扁而已。」

「我可不想被踩扁。」

桐人虽然点头同意，但暗地里似乎燃起了挑战心般地不断动着鼻子。莉法又瞪了他一眼之后才开口继续说：

「总之我们九成九连迷宫都到不了。在这种距离之下，走在路上时遇见落单邪神，只要被它盯上我们就是只有死路一条了。」

「这样啊……在这个区域里面又不能飞行……」

「没错。要有日光或月光的地方才能恢复翅膀飞行能力。但正如你所见，这里没有这两种光线……唯一只有黑暗精灵在地底也能够稍微飞行一段时间……」

说完之后，他们便互相看了一下对方的翅膀。无论是风精灵莉法背后的浅绿色翅膀，或者是守卫精灵桐人的灰色翅膀，这时都失去磷光而萎缩了起来。失去飞行能力的精灵根本就只是尖耳的小丑罢了。

「这样的话，最后希望就是能加入刚才莉法所说的狩猎邪神大队，然后跟他们一起回到地面上去……」

「是没错啦……」

莉法点了点头之后，便将视线往小庙外面看去。

微暗的蓝色当中所能见到的，就只有一望无际的雪原、森林以及屹立在遥远彼方的异形城堡。当然，那座城堡里一定有魔王级的邪神与它的一大堆部下，当莉法他们接近的瞬间八成就会有让人很不愉快的事情发生。当然也看不到其他玩家的踪影。

「……这个幽兹海姆是为了取代地上的高级迷宫，最近才刚追加进来的最困难区域。所以会来这里的队伍大概都在十组以下。这些队伍在偶然之间来到这座小庙附近的可能性，可能比只靠我们自己赢过邪神的机率还要低……」

「看来真的得靠我们的运气了。」

桐人只能无力笑了笑。接着他看向在他膝盖上熟睡，身高只有十公分左右的少女，然后伸出右手食指来戳了一下她的头。

「喂——结衣，快醒醒啊——」

听见他的呼叫之后，少女长长的睫毛动了两、三下，接着包裹在粉红色洋装的娇小身体才撑了起来。结衣用右手掩住嘴巴，左手高高举起，打了一个大大的呵欠。她这样的动作实在很惹人怜爱，让莉法一个不小心就看呆了。

「呼啊……早安啊——爸爸、莉法小姐。」

小妖精以银铃般声音打着招呼，而桐人则是温柔地对她说道：

「早啊，结衣。可惜现在还是晚上，而且我们也还在地底。可不可以麻烦你搜寻一下附近有没有其他玩家在？」

「我知道了。请稍等一下……」

结衣点点头之后闭上了眼睛。

跟在桐人身边的小妖精结衣，其正式名称是「导航妖精」，任何人只要付出额外的费用就可以由选单里面呼叫他们出来。但是就莉法所知，导航精灵通常只会用毫无感情的合成音念出辅助系统里的记载事项，从没见过像结衣这样有丰富感情表现的个体。应该说根本就没听过还有自己专属姓名与个性的导航妖精。

莉法一边想着重复招唤同一只精灵的话是不是就能够和他变得这么熟稔，一边等着结衣开口说话。

过没多久，睁开眼睛的小妖精，很抱歉似地垂下了长耳朵，甩动黑色的长发说道：

「对不起，在我可以读取的档案范围内没有其他玩家的反应。应该说如果当初我有注意到那个村庄没有登录在地图上的话，现在就不会……」

坐在桐人右膝上的结衣沮丧地低下头，而莉法则反射性用指尖摸着她的头说：

「别这么说，那不是结衣的错。毕竟那时候是我拜托你专心警戒周围有没有其他玩家的。所以你千万不要在意。」

「谢谢你……莉法小姐。」

看着结衣以湿润的眼眸望着自己，让莉法实在无法相信眼前的这个妖精居然是由程序代码所驱动的。莉法露出一个发自内心的微笑，轻轻摸了一下结衣的脸颊之后看向桐人。

「嗯，这样的话就只有奋力一搏了。」

「什么奋力一搏……？」

莉法对着桐人豪气地一笑，接着开口说：

「当然是试试看我们能不能靠自己回到地面上啰。反正继续坐在这里也只是浪费时间而已。」

「但、但是你刚才说绝对不可能成功的不是吗……」

「我是说九成九不可能成功，所以要赌在那百分之一的可能性上。其实只要看出落单邪神的移动模式，然后慎重行动的话就有可能成功。」

「莉法小姐好帅！」

莉法对努力拍着小手的结衣眨了一下眼睛，接着便准备站起身来。

但这时桐人却拉住她的袖子，用力把她拖了回来。

「做、做什么？」

莉法一个踉跄后坐回地面，原本打算要开口抗议，但看见桐人在至近距离之下的眼神后又闭上了嘴巴。桐人就这样一直凝视着莉法，然后以非常正经的口气坚定地说道：

「不……你还是在这里登出吧。我会守护你的角色直到消失为止。」

「咦？为、为什么？」

「现在已经超过凌晨两点半了。你说过自己在真实世界里是学生吧？今天你已经为了我连续潜行超过八个小时以上，我不能再让你陪我耗下去了。」

「…………」

这突如其来的说词让莉法没办法做出反应，而桐人则是凝视着她继续平静地说道：

「光是直线前进都不知道要花多少时间了。现在还要一边躲开那种超大型怪物的搜敌范围一边移动，实际移动距离可能要加倍也说不定。就算能够安全到得了阶梯应该也已经天亮了。虽然我自己有非到阿鲁恩去不可的理由，但今天不是假日，所以你还是登出去休息比较好。」

「我……我……我不要紧，就算熬个一整晚也……」

莉法勉强挤出笑容，正准备摇头的时候——

桐人却在此时放开她的袖子，以中止这段谈话的气势向她低头说道：

「莉法，一直以来真的很谢谢你。如果没有你，光是收集这个世界的情报就不知道要花掉我多久的时间。因为有你才让我只用了半天时间就能到这个地方来。我真的不知道该如何向你道谢才好。」

「…………」

莉法无法忍受胸口突如其来的刺痛，只能用力紧握双拳。

她不知道胸口为何会如此地疼痛。但是她的嘴唇几乎是自动张开，然后勉强挤出僵硬的声音。

「我、我也不是为了你才这么做的…………」

「咦……」

把视线由抬起头的桐人身上移开后，莉法用僵硬的声音继续说道：

「是……是因为我自己也想要来才能一路陪伴你到这里。我还以为你能了解呢。什么叫不能让我再耗下去了。难道你认为一直以来我都是在勉强自己跟你同行吗？」

AmuSphere读取到莉法内心涌起的感情，直接忠实地让她两眼的泪水即将夺眶而出，她只好用力眨了几次眼睛将眼泪挡回去。坐在桐人膝盖上的结衣一脸担心地交互看着两个人，而莉法则像是要逃开她的眼神般朝着小庙出口站起身来。

「今天的冒险……是我玩ALO以来最愉快的经验。有好多事情都让我兴奋不已、心跳加速。让我好不容易开始相信，这里也是另一个真实的世界，但现在却……！」

她用右臂迅速擦干双眼的泪水，接着就往黑暗的外头冲去。

就在这一瞬间——

忽然有股不像雷鸣也不像地鸣的巨大怪异声响在极近的距离内响起。

这道「吼噜噜噜噜」的声响，无疑是从超大型怪物喉咙里所发出来的咆哮声。接着足以让地面产生摇晃的脚步声也跟着响起。

莉法内心一边想着「糟糕，刚才的叫声把落单邪神给引过来了，我这个大笨蛋！」并因此而自责，一边决定自己当诱饵来把邪神引开。于是她再度准备往外冲去。

但是不知何时已经站在她身后的桐人却用力抓住她的左臂要她留下来。

「放开我！我来把敌人拖走，你就赶紧趁隙离开……」

虽然她压低声音如此嚅嗫道，但旁边的桐人却以敏锐目光看着外面然后迅速说道：

「不，等一下。情形有点奇怪。」

「有什么好奇怪的……」

「敌人不只有一只而已。」

听见这句话后莉法急忙竖起耳朵，结果由邪神发出来的咆哮，除了一道类似大型引擎的重低音之外，还混杂着一道类似寒风的咻咻声。莉法先是屏住呼吸，然后才准备将抓住自己的手臂甩开。

「如果是两只的话那我就更应该出去！等你被其中一只给盯上就来不及了！死亡的话就得从司伊鲁班重新出发唷？」

「不是那样的，莉法小姐！」

乘在桐人肩膀上的结衣轻声叫道。

「接近中的两只邪神级怪物……似乎正在互相攻击！」

「咦？」

莉法眨了几下眼睛之后，再度把注意力集中在耳朵上面。接连不断的震天脚步，听起来确实不像是直线前进，而像是在滚动般的不规则震动。

「但、但是……怪物之间互相攻击，这究竟是……」

莉法瞬间忘了几乎压垮心脏的悲伤，茫然地低声说道。结果桐人像是下定决心般这么嚅嗫着：

「我们去看看到底怎么回事吧。这种小庙也不是防空洞，一直待在里面也不是办法。」

「说、说得也是……」

两人互相点了点头之后，莉法将手放在长刀之上，然后跟着桐人往雪花纷飞的微暗空气中走去。

才走了几步，声音来源的两只邪神马上就映入他们眼帘。由小庙东边不断接近的它们，简直就像两座晃动的小山一样。高度应该有将近二十公尺吧。两只的色泽都是邪神级怪物特有的蓝灰色。

定眼一看之下，可以发现两只的大小有些微差异。发出「吼噜噜噜噜」那像发电机般吼叫声的个体比「咻咻咻」啼叫的个体还要大一点。

而大型邪神还可以说稍微有一点人类的形状，它有着三张直向连在一起的巨大脸孔，脸孔旁边还长出四根手臂宛若巨人。那类似邪教神像的四方形脸孔各自发出「吼噜、吼噜」的叫声，听起来简直就像引擎连续发动的声音。此外四只手上还轻松挥舞着像工地现场钢筋般的四角形巨剑。

另一方面，较小型的邪神则已经不知道该怎么形容它的外形了。巨大耳朵与长长鼻子让它的脸就跟大象一样，但后面身体却是像馒头般的扁平圆形，而支撑这种身体的则是将近二十只左右带有钩爪的长脚。整体来说，大概就像是——有着象头的水母吧。它虽然伸出尖锐的爪子来逼退巨人的攻击，但爪子却被像暴风般的四角铁剑挡住而根本没办法抓到巨人的脸。小型邪神因此不断被逼退，每当剑前端砍过馒头型身体时，就会有全黑液体像雾一般飞散。

「这…这到底是怎么回事……」

莉法已经忘了要隐藏自己的身体，只是茫然地如此呢喃着。

ALO里面通常只有在三种情形之下怪物才会互相攻击。第一就是某一边的怪物是擅长于驯兽技能的猫妖族玩家所操纵的「宠物」。第二种情形就是某一边受到音乐精灵所演奏的乐曲所煽动。再来第三种就是被幻属性的魔法给迷惑了。

但是这三种情形很明显都不适用于现在眼前进行的死斗。如果是宠物的话目标箭头应该会变成黄绿色，但两只邪神的箭头都还是一般怪物的黄色。空气中能听到的也只有两只邪神的吼叫声与震动声，根本没有音乐，甚至也见不到任何幻惑魔法发动时的光线效果。

莉法他们只能呆站在那里看着这场大战，而两只邪神也丝毫不在意他们的目光，只是不断进行着激烈的死斗。目前依然是三头巨人占优势，象水母屈居劣势的情况。最后象水母的一只脚被巨人用剑从根部完全打断，飞出来的脚就掉在莉法他们附近，让他们的身体随着震动而摇晃着。

「喂、喂，继续待在这里好像不太妙吧……？」

身边的桐人虽然如此呢喃着，但莉法点了点头之后却还是没有任何行动。因为她的目光没办法从象水母身上移开，从伤口迸发出来的血液将白色雪原染成一片黑色。

受伤的象水母发出一声尖锐的「咻咻」声后，再度试着逃离现场。但是巨人似乎不打算让对方逃走，它除了往象水母如馒头般的身体扑过去之外，手中的铁剑还更用力往象水母身上招呼。无法承受压力而倒在地上的象水母，发出的声音也愈来愈虚弱了。它灰色外皮上被划下好几道残忍的伤口，而巨人的剑更是无情地对伤口不断发动攻击。

「救救它吧，桐人……」

当这句话由自己的口中说出来的时候，莉法也感到十分惊讶。桐人脸上先是出现比她惊讶三倍左右的表情，接着又交互看着莉法和两只邪神，最后才简短地问道：

「救、救哪一边？」

确实，跟勉强还算是人类形状的巨人相比，象水母的外型确实是相当惊悚。但这种情况之下其实根本就不用多加考虑了。

「当然是被欺负的那边啰。」

桐人面对马上这么回答的莉法，提出了一个非常简单的疑问。

「怎、怎么帮？」

「这个嘛……」

这次莉法实在没办法马上回答。因为她自己也没有任何点子。但就在她犹豫该怎么办的时时候，象水母的青灰色背上已经又多了好几道伤痕。

「…………桐人，你快想点办法！」

莉法在胸前握紧双手如此大叫着，但守卫精灵的少年也只能看着天空然后用两手搔着满头黑发。

「要我想办法我也～」

但这时候桐人的手忽然停了下来，接着再度凝视着两只邪神。他瞇起双眼，黑色瞳孔深处闪烁着脑内正进行高速思考的光芒。

「……如果那种外型有其意义的话……」

桐人低声说完之后，忽然看起四周环境，接着又小声地对肩上的结衣说道：

「结衣，附近有什么有水的地方吗？无论是河川或湖泊都可以！」

结果小妖精不问理由马上就闭起眼睛，然后迅速点头回答：

「有的，爸爸！北方约两百公尺左右的地方，有一座结冰的湖泊！」

「好……听好啰，莉法，我们要拼命跑到那里去。」

「咦……咦？」

外型——是指那个三头四臂的巨人吗？那跟有水的地方又有什么关系呢？

桐人不理会充满疑惑的莉法，轻推了一下她的背部之后，便直接从腰带里拔出类似钉子的物体。那应该是投掷用的锥子才对，但莉法至今为止从没见过有人使用这种武器。那是因为在ALO中有魔法这种超强力的远距离攻击方法，所以修炼这种单调的武器投掷技能可说是一点意义都没有。

但是桐人却相当熟练地一边将全长十二公分左右的锥子在手指上转动着，一边做出投掷的动作。

「……要去啰！」

他的右臂随着准备投掷的声音以迅雷不及掩耳的速度挥出，铁锥带着蓝色光芒在空中以直线飞去——

飞锥直接命中三头巨人最上方的脸那发出暗红光线的两眼之间。

令莉法惊讶的是，巨人的HP值竟然微微减少了大概一个画数左右。那种像玩具一样的武器竟然可以贯穿邪神级怪物的坚强装甲，可见他的飞剑技能一定经过相当程度的锻炼。

当然这点伤害对邪神那庞大的HP值来说根本就不值得一提，但这种时候最重要是要让对方产生损伤。因为——

「吼吼吼噜噜噜噜噜噜噜！」

发出这样的吼声后，巨人那三张脸与六只眼睛都转了过来，这就是它已经把目标从象水母转到莉法与桐人身上的最佳证明。

「……要逃啰！」

桐人大叫完之后，马上转向北边然后踢起雪片全力往前冲。

「等等……」

莉法只能不断开合着嘴巴，然后急忙从后面追上逐渐远去的守卫精灵。紧接着后面马上有震天的咆哮与震动传了过来。巨人立刻开始追起他们两个人。

「等等不不要啊啊啊啊啊啊！」

莉法一边发出悲鸣，一边将脚底下的速度提升到极限。但前面的桐人却以不输奥运短跑选手的漂亮姿势，持续拉开与莉法之间的距离。虽然在贯穿地面山脉的「鲁古鲁回廊」中她就已经体验过桐人逃走的速度，但被丢下来的话可就一点都不好玩了。

「太～～过～～份～～了！」

在莉法发出尖叫声当中，背后的巨大震动声也持续不断接近。邪神身高大概有莉法的十三倍，所以两者之间步伐的差距应该也是这样的倍数吧。莉法一边担心那像钢筋的大剑会不会马上挥下来，一边用尽全身力气正确来说应该是脑部所发出来的运动命令来追上桐人。

结果前面的黑衣少年忽然啪沙一声将雪踢散然后停了下来。接着他又转过身子，张开双臂来挡住莉法。即使是在这种情况之下，被对方这样抱在怀里，莉法还是羞红了脸颊。她一停下来后马上转头往后看去。

三头巨人已经接近到抬头就能看见的吓人距离。再过几秒钟马上就能追上他们了。要是被它的铁剑打中一下，身为轻装战士的桐人和莉法，HP值一定马上就会归零。

——你到底打算做什么！

正当莉法以不成声音的音量对紧抱着自己的桐人如此问道时……

由地底传出了「啪叽啪叽」这样奇异的声音。

那是巨人宛如大树般的脚踩破埋藏在雪面下冰层时发出的声音。桐人之所以会停下来，是因为这里是被积雪覆盖的广大结冰湖正中央。

大概十五公尺前方的雪原整片下陷，阴暗清澈的水面整个露了出来。三头巨人掉下自己所创造出来的湖泊里，接着马上激起一条高高的水柱。

「就、就这样沉下去吧……」

莉法拼了命地祈祷，但事情果然没有那么容易解决。巨人马上就有一个半的脸孔露出水面，接着啪嚓啪嚓拨着水往他们这里前进。看来它是用我两条手臂当成桨在湖面下划水。全身像岩石一样的邪神竟然如此会游泳。如果让它沉到湖底就是桐人的作战，那他的赌注可以说完全失败了。

莉法站起身来决定至少要再跑一段路，但抱住她的桐人却是一动也不动。他用几乎快触犯性骚扰防范规范的力道压住莉法，然后一直凝视着迫近的巨人。

「……啊，难、难道说，你……」

——「想直接就这样死亡吗」的直觉闪过莉法脑海里。

就像他刚才曾经说过的，为了让莉法能够登出而准备和邪神同归于尽，然后再度从存盘地点风精灵首都司伊鲁班出发。

莉法绝不允许他这么做。莉法光是今天和他一起同行，就能感受到桐人想到央都阿鲁恩中心点「世界树」去的强烈决心了。这名守卫精灵少年是为了要去世界树上见一名等待他的人，才会进入ALO，然后历经千辛万苦而来到这个地方。

「不行，你快点逃……」

莉法虽然挣扎着想从他怀中逃离，但她嘴里的细微叫声这时又被另一道水声给掩盖过去了。

吓了一跳的莉法往声音来源看去，随即看到迫近的三头巨人身后又出现了一道新水柱。

「咻噜噜噜！」的吼叫声无疑是来自刚才不断被巨人欺负的象水母。亏他们已经把巨人拖走了，它却自己又从后面追了上来。

莉法瞬间忘了自己的状况，只是惊讶地瞪大了眼睛——

先是水面被分割开来，然后象水母将近二十只脚全部缠上了巨人的脸与手臂。

巨人立刻发出「吼噜吼噜！」的愤怒叫声并且挥舞手里的铁剑。但是在水里挥剑的动作相当迟缓，根本无法摆脱对方脚的纠缠。

「……原、原来……」

莉法用沙哑的声音轻声说道。

那头象水母原本就是生长在水里的邪神。在陆地上的时候，有大半的脚为了支撑它那巨大的碗型身体而派不上用场，但现在进入湖里面之后整个身体便浮在水面上，全部的脚都可以拿来攻击。相对地巨人需要用两条手臂来游泳，攻击力已经被削弱了一半。

也就是说，桐人刚才嘴里的「外型」指的原来是象水母邪神。现在一想起来水母确实是水里的动物，莉法对于自己连这么简单的事情都没注意到而感到丧气，进而更握紧了双手。

象头邪神以如鱼得水，不对，应该说是以水母得水的气势压制着三头巨人，让巨人的头整个沉到水底。两头超大型怪物的缠斗溅起了滔天巨浪，浪花在碰到了冰岸之后喷出大量水沫。

这时象水母发出更为尖锐的叫声，然后身体开始发出蓝白色光芒。光线接着变成细微的火花，透过二十只脚流入水中。

「啊……」

「太棒了！」

莉法与桐人同时大叫了起来。三头巨人的HP开始急剧减少。利用观测技能一看之下，发现每当火花闪烁时三头巨人高达数十万的HP值便不断下降。

也许是巨人的最后悲鸣吧，水面下闪烁了数次红色闪光，然后浮起了好几道蒸气柱，但这些对水母邪神的HP值没有任何影响。不久之后，吼噜噜的吼叫声开始慢慢减少，最后完全停止——紧接着便产生超大规模的多边形爆发效果，让莉法的视线完全看不见东西。

瞬间莉法将自己的脸转向旁边。当她把头转回来时，留在现场的箭头便只剩下一个而已。

咻噜噜噜噜噜噜噜噜……一阵类似胜利的吼叫声之后，象水母将自己所有的脚高举起来。

接着又马上将它们放了回去，开始在湖面上游起泳来。

当它巨大的身体爬上岸边时，身上流下来的水简直就跟瀑布一样。莉法一边吞着口水，一边看它踩着冰雪向他们走过来。

邪神愈来愈接近的沉重脚步让莉法他们的脚底随之震动，而当它停在他们眼前时，可以再度感受到它确实十分巨大。光是一只与巨人作战时看起来像细小触手般的脚就足足有两手合抱起来那么粗。那些脚就像高耸入云的大树一样，让他们只能看见馒头型身体的轮廓。

它身体前面的头部实在与大象非常相似。脸颊两旁圆滚滚像耳朵的部分或许应该称为鳃还比较合适，脸孔下方有着与脚差不多长的鼻子垂下来。两边各有三个像黑色镜头般的眼睛正发出光芒，虽然这看起来有些吓人，但由于排列形状就跟饭团一样，所以整体的表情倒还算是逗趣。

「那我们接下来该怎么办…………」

桐人轻声说道。

莉法确实说过要帮助这只有点像大象的邪神，但接下来的行动她就完全没有想过了。现在停在他们眼前的是一只恐怖的邪神级怪物，而且箭头也依然是代表敌人的黄色，只要它那带有锐利钩爪的脚往下一踏，莉法他们一定马上就会魂归西天了。

但是反过来说，现在这一刻它没有发动攻击就已经是很不寻常的现象。像幽兹海姆这种高级的练功场，所有怪物一旦在视线里发现玩家的踪影，应该马上就会像抓狂般发动攻击才对，既然它没有这么做的话，是不是静静待着象水母就会自动离去了呢……

但莉法这样的想法在一秒钟之后便被打破了。邪神发出一声「咻咻」的啼叫后，长长的鼻子就往他们两人伸了过来。

「咿……」

原本桐人已经准备向后逃走，但至今为止一直没有发言的小妖精结衣，忽然用可爱的手把他的耳朵拉了过去。

「不要紧的，爸爸。这孩子没有在生气。」

……孩子？莉法听见这种称呼之后差点没让下巴整个脱臼——

前端分裂开来的鼻子一下就把他们两个给卷了起来。接着便像拔萝卜般迅速将两人抬离地面。

「咿呀～～」

发出这种狼狈叫声的桐人与连声音都发不出来的莉法，就这样被象邪神轻松地抬到数十公尺的高度然后慢慢放进嘴里——幸好没发生这种事情，象邪神只是把他们两人丢到自己的背上。

他们一屁股掉在象邪神身体上，一度弹起来之后才又坐了上去。远看似乎相当光滑的象水母身体其实长满了灰色短毛，当桐人和莉法在它身体中央坐定之后，象水母才满足地叫了一声，然后像是什么事都没发生过一般开始移动。

「…………」

莉法和桐人互相看了一眼之后，也就不再努力想弄清楚目前的状况，只是茫然看着四周围的风景。

虽说幽兹海姆被称为是永夜的国度，但也不是完全的黑暗。覆盖在头顶的冰柱群全都发出些微磷光，让整片雪原都染上了一层薄薄的蓝色。即使这里是超危险区域，这样的景色依然非常迷人。莉法他们由距离地面数十公尺的高度见到了漆黑的森林、险峻的断崖以及建立在上面的高塔与遥远的古城。

象水母的二十只脚持续踩着沉重脚步，而桐人在它背上摇摇晃晃过了一分钟左右后，终于开口如此呢喃道：

「也就是说……这应该是某种任务的开端吧……？」

「嗯……」

莉法歪着头，小声地回答：

「如果是任务，在开始的时候应该会有Start标志出现才对……」

她用左手在视线左上角画了一画。

「如果没有出现的话，就不是有明确开始与结束的委托型任务，而是偶发性的事件……不过如果是这样的话，就有点麻烦了……」

「为什么？」

「如果是任务的话，在结束时一定会得到某种报酬。但事件就有点像是玩家参加型的戏剧，不一定都会有好结果啊！」

「……也就是说，有可能最后会有很悲惨的结局？」

「当然有可能了。我之前曾在类似恐怖电影的事件里因为选错了行动选项，最后被魔女放在锅子里煮死了。」

「这、这游戏也太恐怖了吧……」

桐人脸上露出僵硬的笑容，接着开始摸起腰部下方丰盛的邪神毛发。

「……嗯，反正已经误上贼船，错了，应该说误上水母才对。而且从这个高度跳下去一样会受到很大的伤害，我们也只能撑到最后了……不过——那个……虽然有点迟了……」

「怎、怎么了？」

一脸严肃的守卫精灵先是凝视着莉法，然后忽然低下头说道：

「莉法……刚才很对不起。说出那种忽视你心情的话来。嗯……或许我心里真的有某个地方太小看这个游戏了。觉得再怎么说也不过是游戏而已。但……不论是真实或是虚拟，所感觉到的事物与想法其实都是最真实的，我明明应该是最了解这一点的人……」

桐人低下头来，脸上闪过一抹悲哀的表情。

莉法总觉得曾在哪见过这种表情，但她为了将这种感觉从脑袋里赶走而用力摇了好几次头。

「不……其实我也有不对的地方。那个……如此拼命地解救了我和风精灵族的你，怎么可能会认为ALO只不过是个游戏呢，这一点我很清楚……」

——包含ALfheim Online在内，这个称为「VRMM」的新类型游戏，总是会在某些地方考验着玩家。莉法最近对这一点有很深刻的感受。

夸张一点来说，游戏所考验的便是玩家的尊严。既然这是个游戏，就不可能永远获胜。不论是掉入敌方玩家所设的陷阱而进退两难，或者是被敌人从正面打得一败涂地，这些都是随时有可能会发生的情形。

当那种时候发生时，玩家能够努力挣扎到什么样的地步、落败时又是否能保有尊严。这些都是游戏考验玩家的地方。如果是往常那些映在平面屏幕上的游戏，只要玩家不打出图示，角色脸上的表情就不会有任何变化，当然也可以在实时通讯上利用表情文字来舒缓失败所带来的悔恨感。但是在完全潜行环境下的角色将会忠实呈现玩家当时的感情。有时候玩家甚至会流下悔恨的眼泪。

而有些人就是不想被人看见这种表情，于是在情况对自己不利时马上就笑着放弃比赛，甚至有许多人在输掉的瞬间便登出了。当然莉法也不希望自己哭泣的脸让别人给看见。

但是眼前这名不可思议的守卫精灵，似乎完全不会做这些表面功夫。在鲁古鲁回廊里遭受火精灵突袭而陷入九死一生绝境时、被尤金将军的魔剑打得毫无还手之力畤，桐人都毫不隐瞒自己的愤怒与悔恨，只是拼了命地挣扎并且在最后成功扭转劣势。认为这个世界「只不过是游戏」的人，是不可能做到这种事的。

「……那个……我说你啊……」

——在到ALO来之前，都是玩什么游戏？真实世界里又是什么样的人呢？

原本准备这么问的莉法急忙又闭上了嘴巴。就算是彼此交情很好，在VRMMO里面也不应该询问其他玩家现实世界里的事情。

莉法对感到疑惑的桐人摇了摇头表示没事，然后微笑着说道：

「那……我们这样就算合好啰。我到几点都没关系，因为我已经可以自由选择去不去学校了。」

说完后她便伸出右手，而桐人也笑着说「这样啊」，然后与她握手。莉法为了掩饰害羞的心情而用力摇着手，当她发现到桐人肩膀上的结衣也很高兴地微笑着时，害羞的心情又更加地强烈了。放开手后，她便马上把红透耳朵的脸庞转往另一边。

载着两个人的象水母完全不在乎背上乘客的对谈，只是不断踩着沉重的步伐往前走。随意往前进方向一看之后，莉法瞬间忘了自己发烫的脸颊，开始紧紧皱起眉头来。

「怎么了？」

听见桐人的声音后，莉法一边伸出右手一边这么回答道：

「我们刚才不是说过应该要往西方或是南方角落前进吗？但这孩子好像完全走往相反方向……你看。」

手指前方有一道巨大剪影逐渐从黑暗当中浮现出来。幽兹海姆呈现平缓弧形的顶端上，有许多呈倒圆锥形的构造物垂了下来。此外还有许多由复杂分枝所构成的网状物体包围了非常巨大的冰柱。

由远近效果的模糊程度来判断，冰柱距离莉法他们应该还有十公里左右吧，但由于它实在太过巨大了，让距离感产生了混乱。冰柱里还埋有几道光点，那缓慢且有周期性的明灭模样看起来甚为庄严。

「……那些包围冰柱的网状物不知道是什么东西……」

「我也只在屏幕照片上见过而已……那是世界树的根部。」

「咦……」

桐人迅速瞇起了眼睛，莉法瞄了一下他的侧脸后便继续说明：

「贯穿阿尔普海姆的根部会直接垂到幽兹海姆的顶端。也就是说这头邪神不是走向幽兹海姆的外围，而是前往它的中心部份。」

「这样啊……世界树就是我们的最后目的地了……难道没有通路能从这里爬上那些树根到外面去吗？」

「我没听过有那种通路。话说回来，你看，最长的树根也只有到天花板和地面的中间而已。但就算是那个位置也已经超过两百公尺了，在这个无法飞行的练功场更是绝对不可能到达的地方。」

「这样啊……」

桐人轻轻叹息了一声之后，又重新打起精神来笑着说道：

「嗯，现在只有把一切交给这只不知道是象鼻虫还是巨型等足虫的家伙了。不知道会被送去龙宫城接受盛大欢迎还是被它当成明天的早餐就是了。」

「等、等等。什么是巨型等足虫啊。要说的话应该也是大象或是水母吧？」

莉法噘起嘴巴反驳之后，桐人一脸惊讶地扬起眉毛说：

「咦——你不知道吗？别名又叫做深海大虱，那是在深海海底，像这么大的鼠妇虫……」

他边说边用两手比出相当宽的幅度，莉法上半身抖了一下之后急忙将桐人的嘴遮住。

「我知道了，那我们来给它取名字吧！取个可爱点的名字！」

看着身体下方长满毛的躯体以及前端若隐若现的圆头，桐人心里拼命想着适合大象的名字……猛象……不好……象人类……也不是……

「那就叫当叽好了！」

听见桐人忽然这么说，莉法吓得直眨眼睛。这确实是个可爱的名字，不过他到底是从哪想出来的呢。等等大象当叽，怎么好像听过这个名字。

花了两秒左右探查着记忆深处后，答案终于浮现出来。那是小时候家里一本绘本当中曾出现过的大象名字。内容是从前战争末期，政府对动物园发出处死猛兽的命令，饲育员只好一边哭泣一边拿了有毒的饵想要杀害聪明的大象当叽，但它却不吃毒饵而一直重复着万岁的动作直到饿死为止。当莉法的母亲念这本绘本给她听时，她马上就大哭了起来。

「这名字有点触霉头耶……」

她低声说完后，桐人也一脸抱歉的点了点头。

「好、好像是耶。我脑海里也开始有印象了。」

「咦——你也看过那本绘本吗。那……没关系。就叫这个名字好了！」

莉法拍了一下手之后，便摸了摸脚下的短毛。

「喂——邪神，从今天起你就叫当叽了……」

当然怪物没有任何反应，而莉法他们也就当它已经接受了。如果能用驯兽技能把这只邪神变成宠物的话，系统便会允许玩家帮它取名字，但就算是猫妖族的大师级驯兽师也没有人曾成功驯服过邪神级怪物。

坐在桐人肩上的结衣也接在莉法后面挥着自己的小手，对比自己大上数百倍的巨大身躯说：

「当叽先生，初次见面——今后也请你多多指教！」

或许是偶然也说不定吧，这次邪神头部两旁不知是耳朵还是鳃的东西竟然动了几下。

被取名叫做当叽的象水母沿着冰冻的河川一路北上。

这段时间里面他们曾近距离遭遇过好几次在练功场里徘徊的落单邪神。但不知道为什么，所有邪神都只是由树丛或是山丘的另一边看了一下他们然后便离开了。

或许是把莉法他们当成是当叽的附属品了吧，但这样就又会有个疑问产生，那就是为什么三头巨人型邪神会袭击当叽呢？莉法能想出来的理由就只有移动中与他们擦身而过的邪神全部都跟当叽一样，外型完全不像人类而已。

当她转头想要寻求桐人的意见时，想不到这个守卫精灵竟然在这种状况之下也开始打起瞌睡来了。莉法原本又握紧了拳头，但灵机一动之下，伸手便抓起一大把累积在当叽背上的雪块。

在雪球对象快要消失前，莉法赶紧将它们从桐人黑衣的衣领里丢了进去。

「呜哇！」

被冰冷效果直接击中之后，桐人发出奇怪叫声跳了起来。而莉法则是向他道了声早安之后提出刚才的疑问。守卫精灵脸上虽然暂时出现了懊恼的表情，但随及边想边这么说道：

「……也就是说，比较像人类的邪神与像野兽的邪神之间也发生了斗争吗……」

「或许吧……说不定人型邪神就只攻击当叽和它的伙伴呢……」

幽兹海姆大概是在一个月前的大型更新里才刚导入的新练功场，由于难度相当高，所以几乎都是没经过探索的地带。如果这种状况真是某种事件的话，那么莉法他们很有可能就是最先发现到这一点的玩家。如果是一般狩猎邪神的队伍发现当叽与巨人的战斗，那他们应该都会在一旁隔山观虎斗，等到当叽被杀掉之后便直接和巨人发生战斗——

「嗯，知道所有内幕的只有当叽和这场事件的程序设计师了。我们就顺其自然吧。」

桐人说完之后便将身体往后一躺，然后把两条手臂当成枕头还翘高了脚。从肩膀上轻飘飘飞起来的结衣在停到桐人胸口上之后也做出跟他一样的动作。对于这两个人过于放松的态度叹了口气后，莉法心里一边盘算着这次要是再睡着就要对他施放结冻系魔法，一边看了一下视线角落的时刻表。曾几何时蓝白色的数字已经超过凌晨三点。

对至今为止最晚到凌晨两点就一定会下线的莉法来说，接下来就是未知的领域了。她心里一边抱着「我竟然也会因为网络游戏而熬夜」的感慨，一边摸着脚边的短毛。

这只怪异邪神一点都不理会背上的人，只是按照一定速度持续走着——

当它爬上被雪与冰掩埋的山丘之后，终于停下了脚步。

「呜哇…………」

莉法移动到当叽的头部附近，然后往前一看，接着便不由得发出巨大的惊呼声。

她眼前出现一个洞穴。

而且是规模超乎想象的洞穴。它的直径宽广到让对面看起来只是一片蓝色迷蒙，巨大的垂直洞穴就在眼前张开血盆大口。险峻直立的峭壁被深厚冰层所掩埋，冰层由上部的透明白色往下依序形成浅蓝、蓝、深蓝最后是漆黑的层次。就算再怎么集中精神往洞穴下面看，也只能见到一片深沉的黑暗而已。

「掉下去的话不知道会怎么样……」

连桐人也用紧张的声音这么说道，停在他肩膀上的结衣则用相当认真的口气说：

「我能进入的地图档案里，洞穴的底部构造没有获得定义。」

「呜哇～也就是无底洞的意思吗？」

莉法和桐人一起往后退，准备回到当叽背部中央。但是邪神的身体却率先动了一下。

——难道是要把我们丢进这个洞里吗？

莉法内心虽然如此大叫着，但幸好这个邪神似乎不是那么忘恩负义的怪物。它将二十只脚全部往内侧折起，一边保持着背部平衡一边让巨大身躯往下降去。

数秒钟之后身躯的最下端便碰到了雪地。邪神「咻噜噜」的小小叫了一声后，又开始把长鼻子给吸进身体内侧——然后就完全不动了。

「…………」

莉法他们先是互相看了一眼，然后才畏畏缩缩地从背上下来。

离开几步之后回头一看，发现在那里的已经不是头象水母。它把头和身体都收进身体底下，现在静静待在那里的，就只是一颗很普通的大馒头罢了。

「……这家伙到底打算做什么……」

桐人茫然地说道，莉法从他身边往前走了几步后便开始拍起邪神身上的毛皮。

「喂——当叽。我们接下来该怎么办啊？」

但邪神却完全没有反应，莉法再用力拍打了一次之后，她感觉右手上的触感有了变化。两人坐在上面移动时，当叽的身体感觉像是树脂坐垫那样有弹性，但现在却全部都变硬了。

莉法担心它是不是因为完成任务就死去了，于是便赶紧把一边耳朵靠在毛皮上。结果从内部深处传出「轰轰」这样周期性的重低音，莉法这才安心地把脸从邪神身上移开。

看来应该是还活着吧。被巨人所攻击的损伤也没有大碍，黄色箭头上表示的HP条现在已经完全复原。

「这么说来……会不会只是睡着了？我们都还没办法睡耶？」

当莉法噘起嘴唇，生气地轻拉一下邪神的毛时，背后的桐人忽然开口说到：

「喂，莉法。你快看上面，很壮观哦！」

从远处看起来像倒圆锥形的世界树根部，现在几乎就在他们头顶正上方。巨大冰柱被到处盘据的黑色根部所包围。其直径应该与下方的垂直深洞差不多宽吧。凝神一看之下，可以发现冰柱内部似乎存有某种构造。透过清澈的冰柱可以见到里面有通路与大厅，而当中的火把还透过冰柱发出蓝色光芒。

「真的很壮观……如果那全部都是一座迷宫的话，无疑将会是ALO里最大规模的迷宫……」

莉法一边感叹，一边无意识地伸出手去。但是到大冰柱下端至少也有两百公尺以上的距离，所以就连可以在地下飞行的黑暗精灵也无法到达。

「怎么样才能到那里去呢……」

听见这个问题之后，桐人似乎准备说些什么。

但是坐在他肩上的小妖精却抢先用尖锐的声音说：

「爸爸，有其他玩家正从东边接近——一个人……不对，之后还有……二十三个人！」

「……！」

莉法倒吸了一口气。

二十四个人。很明显是为了狩猎邪神所联合起来的队伍。

这本来是他们梦寐以求想要遇上的对象。只要跟对方说明事情经过然后加入他们，应该就可以从有楼梯的迷宫那里回到地面上了。

但是在这种状况接近之下的玩家，他们的目标显然就是——

莉法咬紧嘴唇往东边看去，几秒钟之后，马上就有踏着雪地的细微声响传了过来。如果莉法不是长于听觉的风精灵，一定听不见这种声音。但现在虽然听得见声音却看不见对方的人影。对方应该是施行了隐形魔法吧。

莉法马上抬起手，准备咏唱识破魔法。但在她开始咏唱之前，离她十公尺左右的空间忽然有像水般的薄膜产生扭曲，接着一名玩家便随着「啪嚓」的声音出现在他们眼前。

那是一名男性玩家。他有着略带蓝色的皎白肌肤以及同样淡蓝色的头发，毫无疑问一定是水精灵族的人。男性身穿刻有类似鱼鳞模样的灰色皮革铠甲，肩膀上还挂着小型弓箭。

由他一身斥侯的打扮来看，应该是负责侦查•搜敌的工作吧，看他身上装备的等级与敏捷的身手，这名男性应该是等级相当高的玩家。

相貌机警加上眼光敏锐的斥侯，又在雪地上踏出一声脚步声后，开口说出莉法最害怕的一句话。

「你们两个要不要打那只邪神啊？」

当然男性指的是在莉法两人身边缩成一团的当叽。

看见莉法没办法马上回答，男性脸上的表情瞬时变得险峻起来，接着又这么说道：

「如果要打的话就快点攻击。不打的话可不可以请你们离开。不然会被卷入我们的攻击范围当中。」

当男人话还没说完时，他背后的棱线处就又有好几道脚步声响起。看来是本队的队员已经追上来了。

如果他们是以中立区域为据点的种族混合队伍的话，那就还有希望……

但莉法的希望却完全落空。越过雪线边缘出现的二十几名玩家，全部都有着白色肌肤与蓝色长发。也就是说这只狩猎邪神的队伍，是由遥远东方的「弦月湾」来到这里的水精灵族精锐部队。

如果是由「领地叛徒」所组成的混合部队，或许就会放过同样由风精灵与守卫精灵组成搭档的莉法和桐人。但是代表水精灵族展开行动的这群人可就没那么好说话了。应该说他们如果杀了别种族的莉法与桐人，反而还能获得荣誉点数。人单势薄的莉法他们根本是绝佳的猎物，但对方还像这样给予他们警告，已经可以说是仁至义尽。

——但是现在也只有让他们接受自己的不情之请了。因为总不能让把我们当成伙伴的当叽被这群人杀掉。

莉法在心里如此想着，然后她便像要保护当叽一样挡在那名斥侯的面前，开口低声说：

「……我也知道这是违反游戏礼仪。但能不能请你们把这只邪神让给我。」

听见这句话后，眼前的男人与他身后的大部队都流露出轻微的苦笑。

「如果是低等级的练功场就算了，想不到来到幽兹海姆还能听见这样的台词。像你这种能到这里来的老玩家，应该也知道『这练功场是我包的』、『这只怪是我的』这种话是行不通的吧。」

男人所说的话可说是再正确也不过了。这种强调练功场或怪物是自己所有的话，连莉法自己听了都觉得受不了。当然如果正和那只怪物战斗当中的话就能拥有优先权，但现在当叽只是缩成一团而已，所以莉法他们完全没有妨碍水精灵们攻击的权利。

莉法只能咬紧嘴唇然后低下头去，这时忽然有个人影站到她面前，而那当然就是桐人了。

莉法一惊之下停止了呼吸。心里想着他该不会又要像在跟尤金将军对峙时那样大吹牛皮，或者是——准备要跟他们作战了吧。即使对方人多势众，他还是不惜拔剑相向吗？

这实在太鲁莽了。从能够到幽兹海姆进行狩猎这点来看，就能知道眼前这二十四个人都是元老级的玩家。光看重战士铠甲与魔法师法杖上闪烁的光芒，马上就能理解在鲁古鲁回廊和莉法他们战斗的火精灵部队，战力根本跟这群人没得比。

但是桐人所采取的行动完全出乎莉法的意料之外。

黑衣守卫精灵完全没碰到背上的大剑，只见他当场深深一鞠躬，然后说：

「拜托你们。」

传出来的声音让人可以感受到他的真诚。

「……箭头虽然是黄色的。但这只邪神是我们的伙伴……不对，应该说是朋友。这家伙原本已经快要死亡，但好不容易才撑到这个地方来。我们想让它做自己想做的事情。」

桐人说完之后将头垂得更低，但他所对面的蓝发斥侯瞪大眼睛愣了一秒钟之后……

脸上便浮现出——极为夸张的爆笑。而他背后的集团也毫不顾忌地放声大笑起来。

「喂……喂喂，你这家伙真是玩家吗？不会是NPC吧？」

大大张开双手的斥侯，收起笑容后摇了摇头，然后拿下肩膀上施有美丽装饰的弓，接着又从箭筒里抽出一只银箭然后将它架到弓上。

「……抱歉，我们也不是到这座练功场来玩的。刚才差点就被一只较大的邪神给全灭了。我们费尽九牛二虎之力才回收所有残存之火，刚刚才好不容易重整整个队伍。现在能杀的怪物我们当然不愿意放过。所以……我给你们十秒钟时间从那家伙身边离开。时间一到，我就要当你们不存在了。魔法师队——开始施放支持魔法。」

男人迅速一挥手之后，排在部队最后面的魔法使们便不断开始咏唱起咒文来。每当各种颜色的光线效果出现，战士们身上就被各种增强能力的魔法所包围。

「十……九……八……」

弓箭使斥侯倒数的声音穿透好几种效果音响了起来。

莉法紧握住双手的力道让骨头几乎快要发出声响，全身还因为愤怒而剧烈震动着，但最后还是用沙哑的声音对眼前的桐人说：

「……我们走吧，桐人。」

「嗯嗯…………」

低声回答之后，桐人也低着头转过身子，然后沿着无底洞边缘往西方前进。这时莉法也跟在他身边。而他们身后的倒数则持续着。

「三……二……一……开始攻击！」

听见这丝毫不自夸的冷静指示之后……

重装战士们一起往前冲去的金属摩擦声与攻击魔法的凶猛发射声同时响起。

不断从他们背后响起的强烈爆炸声，让脚下的地面也产生震动。朝这边推过来的热风让莉法的绿色马尾激烈摇晃了起来。

离开三十步以上的距离之后，莉法和桐人同时转过头去。

这时正是战士们的剑、斧头与枪不断朝当叽巨大身体上招呼的时候。马上就产生一阵强烈的效果光线与剧烈的爆炸声。战士们的高级装备顺利穿透邪神级怪物当叽的防御力，让它的HP值不断减少。

持续了几秒钟的物理攻击之后，八名战士拉开了与当叽之间的距离。但咏唱完攻击魔法的魔法师们马上就取代战士发射第二波攻击，此外还有数名弓箭使也加入射击。

当叽那缩成一团，高达四公尺以上的躯体上不断有猛烈的爆发产生。爆炸接着形成一条条火柱，将当叽的毛皮完全烧焦。它的HP继续减少，一下子便少了十分之一左右。

这时在爆炸声之间，可以听见「咻噜噜、咻噜噜」这种类似笛子的声音。

那无疑是当叽的啼叫声。象头邪神这时的叫声比被三头巨人欺负时还要细微而且断断续续。

莉法已经不忍心再看下去，于是她把头转向左边。

结果却看到让她更加感到冲击的景象。

桐人双手握拳站立在那里，而小妖精结衣一边从桐人胸前口袋探出头来，一边以她娇小的双手用力抓住口袋边缘。

她那惹人怜爱的脸庞已经因为悲伤而扭曲，大颗的泪水由她黑色眼珠里不断流出。看见导航妖精那拼命忍住哭声，肩膀因为痛哭而不断震动的模样，莉法双眼里也流下了热泪。

——如果这只水精灵部队是无情残忍的PK集团就好了！

这样莉法就可以憎恨他们。可以跟即将死去的当叽约定将来一定会帮它报仇。

但他们现在只是在行使MMO玩家的正当权利而已。远从上个世纪的初期桌上型RPG开始，打倒怪物来赚取金钱与经验值便已经是这种游戏的第一目的，即使经过数十年进化而成为现在的完全潜行型RPG，目的也丝毫没有改变。支配这整个阿尔普海姆的游戏规则以及礼仪，让莉法无法指责这群水精灵。

就算对方是怪物，但再怎么说它也曾和莉法他们心灵相通并且一起旅行过一阵子。现在游戏里这种让人无法保护自己伙伴的礼仪是怎么回事？让人没办法说「那孩子是我们的同伴，请不要杀害它」的规则又有什么意义呢？

莉法一直相信这个世界有所谓「灵魂的自由」。相信在真实世界里无法表现的感情，也可以在这个地方流露出来。但是玩家们似乎也随着能力强化、装备晋级、等级提升而加重了绑在自己翅膀上的束缚。那些水精灵在懵懂无知的新手时期，看见不主动攻击人的怪物也会觉得它们很可爱而舍不得杀害它们吧。

莉法这时只能抱持着无法发泄的郁闷站在当场，耳朵里听着不断传过来的剧烈攻击声以及当叽那愈来愈虚弱的啼叫声。它的HP应该已经低于五成了吧。最多只能再撑两分钟——不，大概六十秒吧。

「桐人……」

「莉法……」

他们两个人同时开口说道。

莉法猛然扬起视线看着守卫精灵的黑色眼珠，然后开口说：

「我决定要去救它……」

「我也要去。」

莉法把原本要说出口的「你就先离开这里朝阿鲁恩前进吧」这句话吞了回去后，点了点头。这时候两个人杀过去的话，撑不到十秒钟便会死亡已经是可预见的结局。这场行动对他们来说完全没有任何利益。

但只是站在旁边冷眼旁观，实在是有违莉法——还有桐人的信念。莉法他们从三头巨人手底救出当叽，之后当叽它也回过头来救了莉法他们。就算那只邪神只是根据写在服务器角落的单纯指令来行动，但眼睁睁看着自己认定并且命名的伙伴被杀害而不伸出援手，那玩VRMMO就根本没有意义了。

「那个……我今天会再和你一起从司伊鲁班出发到阿鲁恩去的。」

她迅速说完之后，桐人也边点头边把手放在剑上。

「那就拜托你了。结衣……你要躲好唷。」

「好……好的，爸爸、莉法小姐。你们要加油唷。」

当小妖精那泪流满面的脸躲进口袋里去时，桐人和莉法便一起将剑拔了出来。站在水精灵部队边缘的一名魔法师，在听见「喀锵——」这种尖锐的声音之后，转过头来以惊讶的视线看着他们。

他们首先瞄准了防御力较低的魔法师部队。仅用眼神确认过彼此的想法后，他们便同时全力冲刺。脚边的积雪高高地溅起，空气也为之震动。

一口气将距离拉近的莉法，从较远处就将两手高举过头的绿色长刀挥下。

「嘿呀～～！」

「啪咻！」的清澈斩击声随着猛烈的气势响起。变成绿色闪电的刀刃在后排左端的魔法师肩口上炸裂。

虽然感觉已经确实命中要害，但水精灵身上那件淡蓝色长袍似乎真的是非常高级的装备。他的HP只不过减少了三成左右。魔法师原本打算举起法杖，但是接下来又有一道漆黑闪光横向划过他的身体。紧接着发出了「咚磅！」的沉重冲击声。桐人手上大剑的神速一击让魔法师的HP条又减少了将近四成左右。

水精灵还来不及发出声音身体已经浮在半空中，莉法的连击则是毫不容情地又往他身上招呼。手腕、手腕、脸部的攻击各让他丧失了一成的HP，好不容易才让他的生命值归零。

一道蓝色水柱「啪嚓」一声喷起，然后魔法师便被消灭了。莉法抛开漂浮的残存之火，马上面向下一名敌人。

这时候将全部注意力放在施放远距离魔法攻击当叽的其他魔法师们，终于也注意到事情有点不对劲了。其中一个人一脸惊讶地叫道：

「你……你们疯了吗！」

「嗯，这我们自己也不清楚耶……！」

如此大叫响应后，莉法往雪地上一踢便冲了过去。

但水精灵族精锐部队的反应也相当迅速。他们立刻中断咏唱当中的大型咒文，开始念起简短的快速咒语。但是莉法和桐人冲刺的速度稍微比他们快了一点。他们抢得能以第二名魔法师当作盾牌的位置，再度互相使出剑技。眼前的魔法师们虽然强行施法，但却几乎都是直线轨道型的攻击魔法，这些魔法在擦过莉法他们的衣服之后便向后逸去。

虽然有一、两发追踪型攻击混在里面，但莉法即使被击中也还是绷着脸利用身体重量使出突刺来终结第二名敌人的生命。这时桐人的目标已经换到下名敌人身上。他将与身高差不多的巨剑扛在肩上，经过一瞬间的蓄力后，发出了像要割裂大地般的一击——

这时忽然有一道声音响起，结果原来是由射穿桐人左肩的银箭所发出的声响。

仔细一看，站在中间位置的斥侯领队已经用险恶的表情架上第二只箭。接着他开口用强而有力的声音命令道：

「剑士队，快回来！魔法师队遭受袭击了！」

随后发射出来的第二只箭对准莉法胸口中央飞了过来。宛若流星般拖着长长尾巴的银箭实在太过快速，莉法只好用左腕来抵挡。「咚！」一声沉重的冲击音过后，她的HP条立刻减少了一成以上。莉法的脚一个踩空，像雷射般的高压水流魔法攻击便飞过来射穿她的右脚。虽然不会有痛楚，但令人不舒服的麻痹感还是让她的脸扭曲了起来。

而桐人在让第三名敌人的HP减少一半时，整个人被无法闪避的冰龙卷风给击倒在地上。当莉法赶到桐人身边准备使用回复魔法时，看见敌人魔法部队已经开始咏唱较大型的攻击魔法。此外原本围在当叽身边的重装战士们也一脸凶狠地往这里杀了过来。

——到此为止了吗？

他们冲杀进来已经过了将近五十秒的时间。面对如此庞大的队伍，这样的战果应该已经算是相当不错了。这样的话，当叽应该也可以原谅我们才对。

蹲在地上的莉法直接闭上眼睛，然后将脸伏在桐人胸口，等待着魔法或者弓箭将他们HP归零的瞬间。

但是在攻击声还未响起之前，莉法就先听见宛如把直笛声音加强数万倍的啼叫声。这道让冰冷空气产生强烈震动，也让远方雪山发出回声的啼叫声毫无疑问是来自于当叽。但很明显可以听出与刚才软弱的悲鸣完全不同。

难道说它真的要死去了吗？莉法一想到这里，马上用扭曲的表情往山丘上看去。

她随即见到当叽椭圆形身体上有了几道很深的裂痕。接着裂痕愈变愈长，最后互相连结起来。

「啊…………」

莉法一边发出细微的叫声，一边预想着会有大量邪神的黑色血液由裂痕里喷出来。

但是——

迸发出来的却是非常刺眼的纯白光芒。

由当叽身体放射出来的环状白光伴随着「咕哇哇哇」这种尖锐声音包围住水精灵剑士、射手、魔法师们的身体。瞬间，缠绕在他们身体上的支持魔法光芒以及咏唱当中的攻击魔法效果全都变成白烟蒸发了。

……广域解咒能力！

这是只有一部分高等级的魔王级怪物才拥有的能力。最下级的落单邪神应该无法操纵如此强大的力量才对。由于没办法理解究竟发生了什么事，莉法、桐人以及其他二十二名水精灵瞬间都僵住了。

在所有视线的注视之下，当叽那由裂痕里发出白色光芒的身体整个碎裂了。不对，应该说喷飞出来的只是又厚又硬的壳而已。现在由依然耀眼的光芒里面，开始有像螺旋状尖塔般的物体伸了出来。

得仰头才能看见的巨大光之螺旋，在轻轻回转一圈之后便分解开来。

呈放射状展开的，是带着纯白光辉的四对总共八张翅膀。

「……当叽………………」

彷佛听见莉法的呢喃一样，翅膀根部那唯一跟以前一样的象脸抬了起来。接着它又高高举起长鼻，将大耳朵整个打开来——

再度发出「咻噜噜噜噜噜！」的高声啼叫后，已经不再是水母的邪神张开八片翅膀垂直飞了起来。

原本圆滚滚的身体变成了细长流线型状。腹部虽然同样垂着二十只脚，但现在不像以前那样是长着钩爪的触手，而是类似植物的蔓藤。莉法注意到它原本剩下一成左右的HP条已经一口气全部恢复了。

当叽停留在十公尺左右高度的翅膀，在没有任何前兆下便开始发出与刚才不同的蓝色光芒。

「啊……糟糕……」

桐人发出惨叫声。他马上抱住莉法的身体，两个人一起趴到雪地上。

接着便开始有恐怖又强烈的电击从当叽所有脚上往地面发射。

还来不及发出悲鸣，被闪电击中的水精灵们便随着爆发被轰飞了出去。剑士们虽然都挺过了这波攻击，但弓箭使与魔法师当中有人受到一击，角色便整个烟消云散了。

「退到山丘底下！以密集阵型来回复HP并且重整支持态势！」

斥侯队长马上从震惊当中回过神来叫道，活下来的二十名左右水精灵马上一起冲下斜坡。

接着重装剑士们开始围起人墙，而他们背后的魔法师则开始展开咏唱。

但是当叽滑过天空、追逐敌人的翅膀这次又充满纯白光线。

接着「咕啊啊！」的声音响起，让一切魔法无效化的光环往下降。几乎快要完成的几道咒文马上变成白烟消散。

「可恶！」

斥侯这时终于以愤怒的声音叫道。他迅速动手，朝正上方射了好几只箭。而这些箭的尾巴都拖着黑烟，随即烟雾就隐藏了部队的所在地。

「撤退、撤退！」

从莉法的位置上，可以见到水精灵小队随着这个声音以直线离开的模样。他们一旦决定要撤退，移动的速度可真是快如疾风，蓝色精灵们的身影一下便消失在远方的雪棱线后面。

当然孵化成飞行型态的当叽应该能轻而易举就捕捉到那些在地上跑的玩家。但邪神只是发出一声胜利的啼叫然后便停了下来，单边四片翅膀一阵起伏后就变换了方向。

它就这么轻盈地飞了过来，然后直接在莉法他们头上停住。色调稍微变得比较白皙的象头上，六颗眼珠全部看向在地面的两人。

「…………那我们接下来要怎么办？」

桐人嘴里又吐出这种似曾相识的话。

但当叽马上就将长鼻子伸过去来回答他的问题。鼻子将莉法与桐人卷起来之后，不管三七二十一便将他们从地面上拉了起来。当他们心里想着「果然又是这样吗！」的时候，就被往背后一丢，两个人又同时一屁股坐到当叽的背部。

他们互相看了一眼，然后同时将剑收了起来。接着莉法便开始摸起当叽的白色毛皮。感觉上毛好像比以前更长也更柔软了。

「不论如何，能活下来真是太好了，对吧当叽！」

她低声说完之后，由桐人胸前口袋露出脸来的结衣很高兴地边拍手边说：

「真的是太好了！只要活着就会有好事发生！」

「如果是这样就好了……」

桐人一边摇头一边这么说着，然后按照顺序看着上方与下方。

当叽接下来一定是要移动到某个地方去。如果它的目的地是幽兹海姆中心那个深不见底的无底洞——那事情就会愈来愈混乱了。但幸好当叽在叫了一声之后便朝着头上遥远且壮观的世界树根部飞去。

每当那长满毛发的翅膀依序在空气中拍动时，邪神巨大的身躯便轻飘飘地在微暗的世界中上升。随着当叽以螺旋状不断向上高飞，幽兹海姆广大的全貌便呈现在莉法眼前。

「哇啊…………」

莉法不由得边发出赞叹声，边眺望这座美丽又残酷的冰雪世界。

由于这里是无法飞行的区域，所以莉法他们应该是第一组由高空俯瞰这里的玩家吧。她反射性地想要从窗口里拿出拍照道具，但念头一转便又握紧了双手。就算把眼底下的风景用道具撷取下来，也还是无法纪录现在内心的这种感觉。这种悲伤、喜悦、无法发泄的郁闷与解放感参杂在一起的复杂感情是绝对无法重现的。

不知道当叽究竟能否理解莉法这时的想法，只见它慢慢降低速度并开始回旋，接着又用力拍了一下翅膀。

头顶上忽然有物体进入视线莉法视线当中，但她一瞬间无法掌握与该物体之间的距离感。

那是一根清澈的蓝色倒圆锥形冰块，以及像网子般包围住它的黑色管线。这些管线当然就是世界树的根部了。

按照远近效果来判断，巨大冰柱全长至少超过两百公尺以上。正如由地上看见时所猜测的一样，内部被划分为好几层，形成一座非常巨大的冰迷宫。

莉法一言不发，只是瞪大眼睛看着迷宫，这时她突然注意到冰柱最下方也就是最尖端的部分，有一道强烈金色光芒在闪烁着。

虽然拼命睁大眼睛但还是看不清楚。她在无意识中抬起右手，咏唱起简短的咒文。

手掌前端立刻有一团摇晃着的水出现，接着又马上结冻变成扁平的结晶体。桐人马上把脸凑过来问道：

「那是什么？」

「望远冰晶魔法。那根冰柱的顶端似乎有什么东西在发光对吧……」

莉法一边说一边把脸颊和桐人靠在一起，然后看着巨大的望远冰晶。瞬间被放大的视线中央可以见到一股金色光线摇晃，不久后便形成清晰的姿态。

「哇呀！」

一看见光芒的来源，莉法马上发出小女孩般的尖叫声。

被封在冰柱前端的，是一口有着金黄色透明剑身而且异常庄严的长剑。无论是包围刀刃的磷光或者是上面细微的装饰，都显示出那把剑被归类为传说武器。不对，应该说莉法早就知道那把黄金剑的名称了。

「那……那是『断钢圣剑』啊。我以前曾在ALO的官方网站上看到过照片……能超越尤金将军『魔剑瓦兰姆』的唯一一把武器……至今为止都不知道它藏在何处的最强之剑……」

「最、最强……」

莉法用沙哑的声音解说完之后，桐人便吞了一大口口水。

封印之剑上方，可以见到有狭窄的螺旋阶梯。阶梯似乎就是连接着巨大冰柱内部的迷宫。

也就是说，只要能突破那座迷宫，就能够拿到全服务器里只有一把的究极武器了。

邪神当叽载着两名全身僵硬的精灵，以螺旋轨道沿着蓝色冰柱不断提升飞行的高度。莉法好不容易将眼睛从圣剑上离开，抬头往前进方向看去，这时她同时见到两样东西。

首先是冰柱当中有一个平板状的降落台突了出来。而当叽飞行的轨道似乎会擦过降落台的边缘。届时他们要跳下去并不是一件难事。

而更上方的天空则是有一根上面刻有楼梯的树根，由被冰雪覆盖的幽兹海姆顶端垂了下来。楼梯就这么贯穿顶端，一路延伸到上面去。毫无疑问那一定是通往陆地——阿尔普海姆的出入口了。

由冰柱上延伸出来的降落台与通往地上的阶梯之间没有互相连结。如果跳下降落台的话或许就有机会能得到断钢圣剑，但是之后就没有到达阶梯的方法了。

看来桐人也同时做出了相同的结论。他的视线在降落台与楼梯之间往返了好几次。当他在这么做的时候，当叽已经愈来愈接近降落台了。还有二十……不对，大概十秒钟就得做出决定……

当叽载着沉默不语的两个人慢慢到达宽广的降落台，并且沿着它的边缘平行飞行。莉法和桐人的身体因为VRMMO玩家的本能而震动了一下。

但是当然他们两个都没有跳下去。

他们彼此看了一眼后露出有些不好意思的笑容，接着莉法便开口说道：

「下次我们带一堆同伴再来吧……」

「说得也是。我想这一定是幽兹海姆里难度最高的迷宫。光靠我们两个人一定没办法突破的……」

「啊——你还那么依依不舍！」

当莉法大笑时，当叽已经直接通过降落台往更上方前进。低头一看之下，可以发现冰之迷宫的四角形入口处里面，出现了非常恐怖的邪神身影。虽然长得很像在地面上袭击当叽的三头巨人，不过是更为恐怖的人型邪神。

住在这迷宫最深处的幽兹海姆最强邪神应该也是这种类型吧。而当叽它们这一族的异型邪神与人型邪神敌对，并且担任这种将玩家载送到这里来的工作。所以那名巨人才会在当叽羽化之前就想杀了它。

如果是参加一般狩猎邪神的队伍，应该不可能会有打倒巨人来解救象水母的想法。就因为是和桐人一起掉到这里来所以才会有这场事件，不，应该说才会有这种友情产生。

当莉法心里想着这些推测时，当叽也愈来愈接近顶端。那根从角落垂下来的阶梯树根也已经愈来愈清晰了。

当叽发出「咻噜噜……」的声音，然后便将翅膀打开降低速度，接着像根羽毛般在空中漂浮滑行，最后伸出鼻子像缆绳般缠住阶梯附近的树根前端。

莉法先是盯着在眼前轻轻摇晃的木头阶梯，接着才站起身来。

她很自然地握住桐人的手，开始踩上最下方的阶梯。

当叽像是要确认背上的重量是否已经消失般摇了摇身体，接着便放开鼻子，稍微降低一点高度并回转巨大身躯。

莉法用另一只手紧握住由庞大象头伸出来的鼻子前端。

「……我们会再来的，当叽。你要乖乖的哦。不要再被其他邪神欺负了。」

她轻声说完之后便放开了手。接着换成桐人握住鼻子，最后连他胸前口袋里的结衣也用小小双手紧握一撮鼻子上长出来的毛。

「下次再跟你好好说话唷，当叽先生。」

听见小妖精令人微笑的话语之后，邪神便以咻噜噜噜的喉咙声回答，接着便依序收起了翅膀。

它就这样以极快的速度下降。整个身体愈来愈小。

让羽毛发出最后一次光芒后，这只不可思议的邪神便消失在幽兹海姆的微暗当中。接下来当叽应该可以轻松地生活在没有人会欺负它的天空中才是。而有一天莉法一定会再次站在那大洞穴边缘呼喊它的名字，而它也一定还会让莉法坐到它背上吧。

莉法迅速地将眼角的泪水拭去，然后看着桐人的脸露出了笑容。

「来，我们走吧！我想这上面应该就是阿鲁恩了！」

她用充满元气的声音说完之后，桐人也大大打了个呵欠然后回答：

「好，最后再努力一下吧。那个……莉法啊，断钢圣剑的事情别跟别人说啊。」

「啊——真是的，讲这种话把整个气氛都破坏光了啦……」

轻轻戳了一下黑衣守卫精灵的肩膀后，莉法就这么牵着他的手开始迅速爬起粗壮树根上的螺旋阶梯。

从巨大蚯蚓体内掉到这里只花不到三分钟的时间，但要用自己的脚走回去时道路可就非常遥远了。莉法老早就放弃去数这条被发光香菇隐约照亮的楼梯到底有几阶，她只是不断向上爬着，大概经过十分钟以上的时间后前方终于出现一道细微的光线。

默默和桐人交换了一下眼神，两人开始了最后的冲刺。他们一次爬过两阶楼梯，用头往开在木头上的树洞撞去。

「吱磅！」一声过后，两人掉在一片长满青苔的露台上。由于速度太快而直接在地上转了一圈，接着才在石板上坐了下来。

他们一瞬间先闭起了双眼，接着才迅速抬起头来，而这时出现在眼前的就是——

异常美丽且庄严的高层都市夜景。

类似古代遗迹的石造建筑物四通八达地连结在一起。成排的黄色火把、蓝色魔法光与粉红矿物灯闪烁的模样就像星光一模一样。而在这些亮光下行走的玩家们，身型可以说是高矮胖瘦全部都有。这是因为九种精灵族的人全部混杂在里面了。

稍微眺望了一下光辉耀眼的夜景之后，莉法忽然抬头往正上方看去。

深蓝色的夜空当中，确实可以见到枝叶清晰的影像。

「…………世界树…………」

低声说完之后，莉法便把视线移到旁边的桐人身上，接着又开口说：

「………不会错了。这里就是『阿鲁恩』。也是阿尔普海姆的中心。世界最大的都市……」

「嗯嗯。我们终于到了……」

结衣由正在点头的桐人胸前口袋露出脸来，然后露出耀眼的笑容。

「哇啊……！我还是第一次到有这么多人的地方来！」

其实莉法也跟她一样。至今为止她从没想过会有那么多离开自己的领地，尽情享受自由冒险的玩家存在。

两人与一只妖精就这样暂时坐在高地的露台边缘，体验这座大城市所带来的喧嚣。

但是不久之后便有像管风琴的巨大厚重声音响起。接着就是柔软的女性声音从空中降下。那是表示从凌晨四点开始要进行每周一次的定期系统维护，所以服务器将会暂时关闭的营运广播。由于从来没有持续登入到这么晚的时间过，所以莉法也是第一次听见这种广播。

莉法心里一边想着由昨天开始就一直有许多全新的体验，一边用力把两脚往前一甩然后站起身来。

「今天就先到这里了。我们到旅馆去登出吧。」

「系统维护都到几点？」

「到今天中午十二点。」

「这样啊……」

桐人先是将视线往下移，接着又忽然抬头凝视着上空。

遥远的前方有着世界树往四面八方扩散的枝叶。

当看见桐人将黑色眼珠眯了起来，稍微牵动嘴角的模样后，莉法才想起这名少年到阿尔普海姆来的目的。

他是为了要跟世界树上方的「某个人」见面。

那到底是谁呢。如果不是任务上的NPC，难道是营运公司的工作人员，又或者是……

但在她继续想下去之前，桐人便恢复以往的表情然后开口说道：

「我们来找旅馆吧。我现在已经是一贫如洗了，所以没办法住太贵的地方。」

「……打肿脸充胖子把所有财产交给朔夜才会有这种下场。至少也要留下住宿费吧！」

莉法将脑袋里一瞬间的想法抛开之后便开始笑了起来，接着又对桐人胸前的结衣问道：

「你爸爸他都这么说了，那附近有什么便宜的旅馆吗？」

不可思议的是这时导航精灵正皱起眉头凝视着世界树，但她听见莉法的问题后马上就笑着回答：

「嗯嗯，从那边下去之后好像就有超便宜的旅馆了！」

「咿，超便宜的那种吗……」

不管脸上露出抽搐表情的莉法，桐人马上迈开脚步。莉法在没办法的情况下也只好跟了上去。

明明已经因为过度熬夜而非常想睡了，但莉法还是因为胸口小小的骚动，最后又抬头看了一眼世界树。

当然她没办法从融入遥远夜空当中的枝叶上发现任何东西。

** 第六章

二〇二五年一月的现在，亚丝娜/结城明日奈可以说是遭到双重囚禁。

第一层禁锢是围住四周的黄金栅栏。关住她的虽然只是个把尺寸加大的美丽鸟笼，但无论用什么方法也没办法破坏它纤细的栏杆。

因为每根栏杆之间足有一公尺宽的鸟笼并不是由金属而是由数位代码所构成，只是假想世界的3D物件。只要系统上写入「无法破坏」的程序，那么就算是用大铁锤来敲打也无法伤它分毫。

而第二层禁锢便是亚丝娜所潜行的这座假想世界。

世界的名称是「ALfheim Online」。简称ALO。是由名为「RECT•PROGRESS」的企业所营运的假想大规模网络RPG也就是所谓的VRMMO游戏。

ALO本身其实是很普通的网络游戏，目前也在正常营运当中，里头有数万人的一般玩家付出连接费用来享受这个游戏。但是有一个男人却因为自己的私欲，暗地里利用这款游戏进行着非常巨大的不合法•非人道计划。

驱动ALO的基础系统，是二〇二二年至二四年里震撼整个日本的「Sword Art Online」这款游戏的复制品。

SAO将不分男女老少的一万名玩家囚禁在假想世界里，并且造成四成左右的人死亡。而其开发•营运企业「ARGUS」也遭受这起恐怖事件的波及而迅速倒闭。SAO服务器于是被委托给知名电子机械制造商「RECT」的完全潜行技术研究部门来维持与管理。而担任这个要职的邪恶男子，不只利用拷贝的基础系统来建立ALO并将其交给子公司来营运，还把完全攻略死亡游戏时就应该马上被解放出来的一部分SAO玩家，大概三百人的意识给直接「绑架」到ALO服务器里面来。

男人的目的是要利用这三百人的脑做实验，研究靠完全潜行系统来操纵记忆以及感情的技术。

这个男人也将亚丝娜的意识监禁在ALO世界里面。他将亚丝娜的分身关在黄金鸟笼里，然后将鸟笼高挂在耸立于阿尔普海姆中央，其他玩家绝对不可能到达的「世界树」枝头上。而男人的目的就是要趁亚丝娜在现实世界里昏睡时成为她的丈夫，进而得到亚丝娜父亲，也就是RECT董事长•结城彰三后继者的位子。SAO事件解决至今已经过了两个月，他的两个目的也几乎都快要达成了。

这名野心男子的名字叫做须乡伸之。

而他的另一个名字则是阿尔普海姆的支配者「精灵王奥伯龙」。

亚丝娜用费尽千辛万苦才获得的开锁密码将门打开后，终于成功来到鸟笼外面。她一边看着快要沉到平缓地平线下的鲜红太阳，一边向前走着。

粗大「世界树」的树枝上嵌有一条道路，而道路低处的壁面与路面上还都雕刻有精致的图案，再配合左右两旁新芽所形成的天然扶手，整体给人一种奇幻世界的感觉。由时常会出来露脸的小动物与小鸟这些活动物体的配置来看，也可以确定她是在「游戏内部」。

虽然心里想着这里应该不会有怪物出现才对，但亚丝娜还是提高警觉地走了几分钟路程，最后终于在树叶帘子对面见到应该是世界树本体的巨大墙壁。树枝与树干接合的部分有个类似树洞的黑色孔道，小路便一直延伸到里面去。亚丝娜在无意识之间一边垫起脚尖，一边慎重地往洞穴口靠近。

来到树洞前面时，可以发现入口本身是模仿天然树洞而做成扭曲的椭圆形，但里头则有一道很明显是出自于人工的长方形大门。门上虽然没有门把，但却有一面触控式面板。她心里一边祈求门没有上锁一边碰了一下面板。

结果门无声地往右边滑去。屏住呼吸确认里面没有其他人的气息之后，亚丝娜便迅速闪身入内。

内部是一条灰白色直线往前延伸的通道。通道里头有些阴暗，只是每隔一段距离便会有橘色照明灯照耀着无机质的壁面。与外部通路那漂亮的树木造型不同，这里似乎是任何物体都懒得配置，可以说是没有任何装饰品的单调通道。

简直就像是游戏世界忽然变成办公室的书库或者是某些严肃的地方一样。赤脚的亚丝娜感觉全白的地板上不断有冰凉的冷气传到自己脚上。这种感觉无情地宣告着她即将进入敌人根据地，亚丝娜不由得咬紧自己的嘴唇。

须乡伸之是被与茅场晶彦不同的疯狂思想所支配的男人。

身为企业的一份子，却利用自己身份绑架了三百个人脑部来进行危险的人体实验，他的精神状态已经不正常了。他一切的行动都是来自自己永无止尽的欲望。一直以来他都是被永远想要更多的无穷贪念所驱使着。从小就认识他的亚丝娜非常了解他的这种性格。

须乡现在已经获得亚丝娜的一部分，更因为确定自己不久后将会得到她的全部而有了某种程度的满足。当他知道亚丝娜自己尝试由鸟笼脱身而出这件事时铁定会暴跳如雷。到时候他将尽可能给予亚丝娜最大的屈辱，甚至还有可能直接把亚丝娜拿去当成他邪恶研究的试验品。一想到这里，亚丝娜的双脚就几乎快要失去力量。

但如果在这里转身回到鸟笼去的话，亚丝娜就可以说在精神上完全输给了须乡。如果是桐人的话，就绝对不会站在这里犹豫不决。就算手里没有剑他也会大步向前迈进。

亚丝娜挺直腰杆，凝视通道前方。好不容易才让重如铅块的脚往前踏出一步。一旦跨出第一步之后，后面的脚步很自然便不断跟上来。

这似乎是条永无止尽的道路。上下左右的面板别说是接合线了，甚至见不到任何瑕疵，让人开始怀疑起自己到底有没有在移动。亚丝娜只能靠着偶而出现在天花板上的橘色灯光不断向前走，最后看见正面出现第二扇门之后才终于松了一口气。

这扇门与第一扇门可以说完全一模一样。亚丝娜再度慎重地用手指碰了一下面板。果然门又无声地向旁边滑去。

这次门里面也是与刚才完全相同的通道，只不过左右两边皆可通行。虽然已经感到有些厌烦，但亚丝娜还是穿过那扇门。惊人的是，几秒钟后自动关闭的门瞬间便融入墙里不留任何痕迹。亚丝娜急忙在墙壁上到处摸着，但似乎已经没办法再将门打开了。

亚丝娜耸了耸肩之后，决定把门的事情抛在脑后。反正她也没打算再回到那里去了。她抬起脸来往左右两边看了一下。

通路这次已经不是直线而是呈平缓的圆弧形。经过短暂考虑之后，亚丝娜开始往右边的通道走去。

随着她不断前进，脚底也发出细微「啪哒啪哒」的脚步声。当她又开始觉得有些奇怪，想说自己是不是沿着圆形通道重复走了好几圈时——终于有墙壁以外的东西进入亚丝娜的视线当中。

弯道内侧，浅灰色的墙壁上贴着某张类似海报的东西。亚丝娜忍不住跑过去一看之下，发现那是这个地方的导览图。她立刻聚精会神地看了起来。

长方形物体上部以极为普通的字体写着「研究室全图 C层」这样的内容。下方则是简单的平面图。看来她目前的位置是在三层正圆形通道的最上面一层。

亚丝娜目前所在的C层除了通道之外便没有任何东西。刚才通过那条连接鸟笼的直线道路并没有被标示出来。但是下方的B层与更下方的A层里，圆环通道的内侧则有各式各样的设施——像是「档案阅览室」、「主屏幕室」、「休息室」等等。

楼层之间的移动似乎是靠地图上标示在圆环顶端的电梯来实行。由俯瞰视点所画出来的圆形三楼层之间有一条垂直线将其连结起来，代表电梯的直线甚至还延伸至楼层下方。

视线沿着表示电梯的直线一路往下看后，发现最下方是一间长方形的宽广房间。见到标示在上面的文字时，亚丝娜马上感觉到背后一阵恶寒。那上面的文字是「实验体收藏室」。

「实验体……」

轻声说出来的名词在亚丝娜嘴里留下苦涩的味道之后才消失不见。

这里无疑就是须乡的非法研究设施。确实，只要把所有研究都搬到假想世界里进行，那就可以轻易瞒过公司了。就算秘密快要被发现，也只要一根手指就能把所有证据消灭，甚至连一张纸都不会留下来。

至于这个设施的主要目的，其实从「实验体」这名词就可以知道。被须乡绑架的旧SAO玩家。他们的精神就是被以某种形式监禁在导览图标示的收藏室里面。

亚丝娜静静考虑了一阵子之后，转过身子继续开始在通道里前进。快步走了几分钟后，通道左手边的外侧墙壁上便又出现了平淡无奇的电动门。旁边墙壁上依然设有面板，上面还有个朝下的小三角形。

亚丝娜深呼吸一下之后用手指碰了那个三角形。结果门马上就往旁边滑开，接着出现一间长方体房间。踏进房间里并将身体半转过来后，马上就见到与现实世界电梯同样的操纵面板。

亚丝娜迅速看了面板，接着按下并排的四个按钮里最下面那个按钮。门立刻关上，接着是相当轻微的下坠感包围住身体。搭载亚丝娜的小箱子无声地朝假想大树根部下降，几秒钟之后便伴随着假想的减速感逐渐停了下来。光滑的纯白色电梯门上忽然出现前一刻还没有的直线裂缝，接着便往左右打开。

亚丝娜尽可能不让自己发出任何声响，悄悄往门外跨出一步。

眼前是与上层同样没有任何装饰的通道，直线向前延伸。亚丝娜确认过没有人之后开始向前走去。

奥伯龙只给了亚丝娜一件简单又单薄的洋装，实在让人觉得有些心慌。但是她倒是很庆幸自己现在是打赤脚。如果脚上有穿鞋子的话，就一定会有脚步的效果声音会出现。亚丝娜从前在SAO里面，尝试不让怪物注意到自己存在由背后攻击或是伏击时，也曾舍弃防御力而光着脚。

除了实战之外，亚丝娜也曾与桐人、克莱因、莉兹贝特等人在阿尔格特的废墟地区玩过好几次「偷袭游戏」，原本就是轻装备的她由于几乎没有发出声音的因素，所以在游戏里总是能拿到好成绩。但是不知为何对桐人的背后攻击总是无法成功，有一次终于忍不住试着打赤脚来接近他，但就在木剑快要击中桐人时便被察觉。桐人不但轻松躲过攻击还把亚丝娜的脚抓来搔痒，让她差点就要笑死了。

跟不晓得是否还存在的真实世界比起来，现在还比较想回到那个时候——亚丝娜随着忽然浮现的眼泪而有了这种想法，但她随即摇了摇头将自己的感伤抛到脑后。

桐人他在现实世界里等我。自己唯一应该去的地方就是他的臂弯。因此亚丝娜现在只能不断前进。

通路其实没有多长。走着走着前方便出现一扇平板门。

亚丝娜心里打算如果门锁着的话，就到上层实验室里去寻找系统控制面板。结果她一站到门前，门便出乎意料之外的静静往左右两边打开了。亚丝娜还因为门内所射出来的强烈光芒而眯起了眼睛。

「…………？」

一看见内部，亚丝娜便倒吸了一口气。

里面是一片非常广大的空间。

可以说像是一座超巨大的活动会场。除了遥远的左右两边以及正面深处的垂直壁面之外没有其他细部物体，所以远近感似乎暂时失去功能。天花板上全部发出白光，而同样是白色的楼层里——紧密且整然有序地排列着许多类似短柱般的物体。

确定视线当中没有任何会动的东西后，亚丝娜便畏畏缩缩地往里面走去。

根据亚丝娜的观察，柱型对象大概是以十八根为一列而摆设着。如果这里是正方形空间的话，那依照十八的平方来算，已经快要接近三百根短柱了。她一边压抑自己的恐惧心，一边接近其中一条短柱。

白色圆柱由地板上一直延伸到亚丝娜胸部左右的高度。尺寸大概有两手合抱那么粗。由平滑表面的狭小细缝里可以见到里面似乎飘浮着某种物体。而浮着的物体，怎么看都像是人类的脑髓。

尺寸虽然与真实的脑髓差不多，但色泽就没有真实感了。它是由青紫色的半透明素材所构成。以假想物体来说实在非常细致，与其说是利用全息光学所呈现的立体影像，倒不如说是把蓝宝石直接加工后的雕像。

仔细观察之后，可以发现透明脑部的各个地方都会有电流周期性出现，而当电流消失时便会产生彩色火花。简直就像把好几根极细的仙女棒集中起来一样。

在亚丝娜皱着眉头凝视之下，呈放射状的一部分电流网络竟然加强了脉动。最末端的火花也由之前的黄色变成红色并且开始不断闪烁。脑髓下方所表示的半透明表格持续纪录这些激烈的反应。格旁边不断流出来的细微记录上有许多数字与符号混在一起，偶而还可以见到Pain、Terror这样的单字。

……他正感到痛苦。

亚丝娜直接产生这样的感觉。

眼前的脑髓现在正因为巨大的痛苦、悲伤或者是恐惧而不断挣扎着。不断出现的火花便是脑部的悲鸣。亚丝娜眼前忽然浮现了脑髓主人的幻影。他的脸孔已经整个扭曲，嘴巴虽然张开到已经快要脱臼的地步，但还是不断重复着无声的吼叫。

由于受不了这样的想象，亚丝娜不由得后退了几步。脑袋当中闪过在上层见到的导览表上写着「实验体收藏室」——以及奥伯龙所说过的话——「操纵感情的技术」。将那些情报与眼前的景象结合之后，亚丝娜得到了一个结论。

也就是说，这个脑髓以及周围其他数百具脑部，全都不是由计算机所生成的假想物体，而是真正的人类——也就是过去SAO玩家们的实时屏幕影像。原本游戏被完全攻略时他们就应该被解放出来了，但须乡却将他们关到这个地方，然后利用NERvGear「在他们身上进行操控思考、感情、记忆这样的恶魔实验。

「竟然……做出如此残忍的事情……」

亚丝娜用两手捂住嘴巴，然后在喉咙里如此嚅嗫着。

这里所进行的研究跟复制人技术一样，是人类绝对不可以进入的禁忌领域。这除了是犯罪行为之外，也代表人类的思考，亦即灵魂这个最大且最后的尊严正在遭受践踏与破坏。

亚丝娜转动僵硬的脖子将视线往右边看去。距离她两公尺左右的地方也有同样的圆柱，里头也有蓝色透明的脑髓浮在上面。虽然造型与眼前这个完全一样，但对面那个「某个人」的脑髓上面的电流较为缓慢。迸出来的火花也是黄色中略带一点红色，看起来简直就像浓稠的液体一样。

而它的后面……以及更后面，那些整齐排列在一起，看起来似乎有无限数量的俘虏们，透明脑髓都被染上各式各样的色彩，而他们本人则都在发出绝望的悲鸣。

亚丝娜拼命压抑住自己恐慌的心情，然后将停留在眼角的眼泪擦掉。

这是绝对不可原谅的事情。不，应该说亚丝娜绝对不允许有这种事发生。自己和桐人绝对不是为了让须乡做这种事而赌上性命战斗的。她一定要将须乡所干的坏事揭发出来，让那个男人受到应有的惩罚。

「等我一下……我马上会救你们出来……」

低声说完之后，亚丝娜便由侧面轻轻摸了一下正感到痛苦的脑。接着她坚定地抬起头来，快步朝房间深处走去。

当一边前进一边数的圆柱数目超过十根时，亚丝娜耳朵里忽然听见像是人类讲话的声音。

她马上反射性地低下身体，然后整个人贴在附近的圆柱上。

亚丝娜慎重地看着四周围并寻找声音的来源。类似讲话的声音是由右手边深处所流出来。

亚丝娜保持着几乎可以说是爬行的姿势，慢慢往那个方向前进。

当她经过了几根圆柱的阴影之后，在前方见到了相当奇怪的东西。

「…………？」

她急忙把身体缩了回去。眨了好几次眼睛之后，才又畏畏缩缩地把头探出去。

——现在已经消失的艾恩葛朗特，其第六十一层被称为是「虫虫乐园」。整个楼层就如它的名字一样充满了虫系怪物，对包含亚丝娜在内的大多数女性玩家来说，那里就像是地狱一样。而怪物之中最讨人厌的，是一种叫做「公牛蛞蝓」的巨大蛞蝓型怪物。它那有黑色斑纹的灰色表皮被一层浓稠的黏液所包围着。那种以大小共三对的眼柄瞪人然后由嘴里伸出触手攻击过来的模样实在可以说是亚丝娜的恶梦——

但目前在离亚丝娜数公尺远的地方，背对着她讲话的两只生物就与公牛蛞蝓非常相像。

巨大蛞蝓们盯着一根圆柱里的脑髓看然后热烈地交换着意见。右边的蛞蝓一边晃动长眼睛一边用尖锐的声音说：

「喂，这家伙又在做关于史皮卡的梦了。B13和14区域也已经突破界限。16也出现了很高的数值……太棒了！」

左边的蛞蝓一边用触手碰着浮在实验体周围的全息图窗口一边回答：

「这只是偶然吧？才第三次而已不是吗？」

「不，这是感情诱导线路形成的结果。虽说是我把史皮卡的影像插进他的记忆领域当中，但这种出现频率已经超出界限值了。」

「嗯——总之还是继续把他列为观察对象好了……」

亚丝娜心里一边对这两只用尖锐声音谈话的蛞蝓感到厌恶，一边再度躲进柱子的阴影底下。

虽然不清楚为什么会是那种模样，但他们应该是帮助须乡从事非人道试验的部下。从他们谈话里听不见一丝良心不安的感觉。

亚丝娜紧握起右手，心里想着如果这只手里有剑的话……就能给这两个丑陋家伙应有的报应了。

她好不容易才让燃烧起来的怒火沉静下来，接着慢慢向后退去。与蛞蝓们隔了一段距离之后，亚丝娜再度朝着房间深处前进。

她谨慎地以最快速度经过一根根圆柱，最后终于来到房间最深处。果然可以见到有一块黑色立方体飘浮在远方的白色墙壁前面。

那块黑色立方体让她想起曾在艾恩葛朗特底层的地下迷宫里见到过的系统控制台。如果能使用那个控制台来进入管理者权限的话，或许就能由这个疯狂的世界里登出也说不定。

但接下去的路程就没有任何可以作为掩护的物体了。亚丝娜深深吸了一口气，下定决心后便从圆柱阴影里跑了出去。

她尽量不发出任何声音并全力朝着系统控制台冲过去。虽然只有十公尺左右的距离，但感觉上像是永远到不了一样。

每跑一步就会担心是不是有人从背后叫住她。但亚丝娜还是死命动着僵硬的双脚，好不容易才来到控制台前面。她立刻转身看了一下。在并排着许多圆柱的远方，可以看见有触手稍微在摇晃着。看来蛞蝓们还在热烈交谈当中。

亚丝娜再度面向漆黑的控制台。黑色斜切的台子虽然没有任何动静，但是它的右端有一道细缝，细缝上端可以见到一张应该是卡片钥匙的银色物体插在里面。她一边祈祷一边伸出手，抓住卡片之后便一口气将它向下滑去。

「碰——」的效果音响起，让亚丝娜吓得把脖子缩了起来。细缝左边浮现了淡蓝色窗口与立体键盘。

可以见到窗口上排满了各种选单。亚丝娜按耐住焦急的心情，由最旁边开始确认起细小的英文字体。

她在左下方发现了「Transport〈转送〉」的按钮，接着用发抖的手指碰了按钮一下。结果一道新窗口随着「噗」的声音浮现。上面标示着整间研究设施的平面图。看来可以利用系统随意跳跃至各个地方。

但是亚丝娜已经不愿意继续待在这里了。她拼命动着眼睛，见到右边角落上有个「Eit virtual labo〈脱离假想实验室〉」的按钮正发出细微光芒。

「就是这个了……！」

她嘴里轻轻叫了一声，然后又碰了一下该按钮。上面接着又出现了一个新窗口。小长方形上面有着「Eecute log-off sequense?〈确定要登出吗？〉」的短文与OK、CEL的按钮。

神啊——

她一边在心里拼命默念着，一边伸出右手准备触碰OK按钮时——

突然有条灰色触手从背后紧紧缠住亚丝娜的右手。

「…………！」

亚丝娜奋力压抑快要冲出嘴的悲鸣，拼命想把手指接近按钮，但纤细的触手简直就像是钢丝一样根本不允许她的手再往前移动一分。接着又有新的触手缠上她准备伸出去的左手。亚丝娜的双手就这样被往上绑了起来，整个人被吊在半空中。

捕获者把亚丝娜被高高吊起的身子半转过来。结果果然就是刚才那两只巨大蛞蝓抓住了她。

有着橘色虹彩，大概有网球那么大的四颗眼珠在纤细眼柄上晃动着。没有任何感情的眼睛像是在检查亚丝娜的脸孔与身体一样直盯着她看，但不久后左边蛞蝓的圆形嘴巴便蠕动起来，发出犹如杀鸡般的声音。

「——你是谁？在这里做什么？」

亚丝娜隐藏内心的恐惧，极力装出平静的声音说：

「快把我放下来！我是须乡先生的朋友。是他让我来这里参观的，但我现在想要回去了。」

「咦？我怎么没听说有这回事？」

右边蛞蝓的两根眼柄像是表示怀疑般弯了起来。

「你有听说吗？」

「没有。不过让外人见到这些设施应该不太妙吧！」

「啊……等等……」

圆圆的眼珠往前伸过来，直盯着亚丝娜的脸看。

「……你应该就是须乡老大关在世界树上面的那个女孩对吧……」

「啊——啊——这我倒是有听说。老大真是狡猾，竟然把这么可爱的女孩……」

「呜……」

亚丝娜回头往控制台看去，并且伸出左脚准备用脚尖去触碰按钮。但是蛞蝓嘴巴附近又伸出新的触手将她的脚也给绑住了。她虽然试着扭动身体来抵抗，但在她成功之前，全息图窗口便因为时间过久而恢复成最原始的画面。

「喂喂，别乱动啊！」

蛞蝓不断伸出触手，开始把亚丝娜全身绑得紧紧的。无情的触手整个深深陷入她腹部和大腿上的娇柔肌肤里面。

「好痛……！住手……快放开我，你们这两只怪物！」

「啊——真是过分。我们这可是在做深部感觉的测试实验耶。」

「对啊对啊。要像这样操纵这副身体可是要经过相当的训练唷！」

假想世界特有，宛如被蚕丝绵包围起来的钝重疼痛感，让亚丝娜绷起了脸。但她还是努力对着蛞蝓们骂道：

「你们也算是科学家吧……？帮忙须乡做这种非人道的研究……难道一点都不会觉得可耻吗？」

「嗯——比把实验动物的脑露出来然后插上电流要人道多了吧。这些家伙都只是在作梦而已啊。」

「对啊对啊。我们偶尔会让他们做非常舒服的美梦唷。我看他们还应该感谢我们哩。」

「……你们疯了……」

亚丝娜边感觉到一股冻人的寒气边这么嚅嗫道。这种没感情的蛞蝓才是这群家伙的真正外表。

蛞蝓们完全不在意亚丝娜所说的话，开始看着对方然后交谈起来。

「老大他应该出差去了吧？你到现实世界去请示一下该怎么做吧。」

「啧，真是麻烦。亚那，你可别趁我不在时一个人享受啊。」

「知道了知道了。你快点去吧。」

一只蛞蝓把触手从亚丝娜身上移开之后，就靠着那根触手敏捷地操纵起控制台。按了好几次按钮，他巨大的身躯就这么无声的消失了。

「…………！」

看见眼前的情况之后，亚丝娜不由得心急如焚起来，开始拼命摇晃着被绑紧的身体。通往现实世界的出口——自己梦寐以求的通道就在眼前。那扇门像故意要让人心焦般打开了一道小缝，然后从里面洋溢出刺眼的光芒。

「放开我！放开我！让我出去！」

亚丝娜虽然疯狂的大叫，但是蛞蝓的触手却丝毫没有放松。

「不行啊——我会被老大给杀了。倒是你一直待在这种什么都没有的地方一定觉得很无聊吧？要不要一起来试一下电子毒品？那些人偶我已经玩腻了。」

在他说话的同时，又湿又冷的触手便开始摸起亚丝娜的脸颊。

「住……住手！你想做什么……？」

她虽然拼了命的抵抗，但蛞蝓却不断伸出新的触手。所有触手开始摸起亚丝娜手臂和脚的肌肤，甚至开始侵入她的洋装里面。

亚丝娜一边忍受着全身被抚摸的不舒服感，一边将全身放松装出一副没有力气再抵抗的模样。一根得意忘形的触手开始靠近她的嘴巴。当它碰到亚丝娜嘴唇的瞬间——

她马上抬起脸来，用力往触手咬下去——

「哇呀！痛痛痛痛痛痛！」

她完全不理会蛞蝓的悲鸣，毫不留情地把牙齿咬进触手里面。

「停、快停！好痛！我知道了、我知道了啦！」

确认潜入衣服里的触手已经撤退后，亚丝娜才松开嘴巴。被咬到痛得受不了的触手马上缩了回去。

「好痛啊，忘记疼痛缓和装置已经关起来了……」

当蛞蝓将眼柄缩了回来并发出呻吟时，他身边忽然出现了一道光柱。另一只蛞蝓随着效果音出现了。

「……？你在干什么？」

「没事没事。倒是老大他怎么说？」

「气到整个人抓狂了。要我们马上把她关回鸟笼，然后变换门的密码并二十四小时监视她。」

「啧，还以为能够享受一下呢……」

亚丝娜由于太过于失望而感到眼前一片黑暗，千载难逢的机会就这么从指尖溜过了。

「至少不要用传送，让我用走的送她回去吧。我还想体验这种触感。」

「你也真是爱玩耶。」

绑着亚丝娜的蛞蝓开始蠕动没有脚的身体并转向收藏室入口。当两只蛞蝓将视线移开的瞬间，亚丝娜迅速伸出了右脚。她的脚尖夹住插在控制台细缝里的卡片钥匙然后将它拔了出来。

同一时间窗口也因此而消失，但蛞蝓们似乎没注意到这件事。亚丝娜接着便像虾子般弓起身子，然后将脚尖上的卡片移动到被绑在身体后面的手里。

「喂喂，不要乱动啊。」

蛞蝓再度将亚丝娜的身体抬起来后慢慢朝出口移动。

「喀嚓」一声后鸟笼的门被关上。蛞蝓的触手在操纵了一下密码锁后对着亚丝娜挥了一挥。

「再见了——有机会的话再来找你玩——」

「我不想再见到你们了！」

亚丝娜冷冷说完之后便走到对面的栏杆去。两只蛞蝓虽然依依不舍地看着亚丝娜，但不久之后还是改变身体的方向，慢慢从树枝上离开了。

不知不觉间黑夜已经包围了整个世界。亚丝娜一边低头看着遥远下方闪烁的小小街灯，一边嚅嗫道：

「我不会认输的——桐人。绝对不会放弃。一定会从这里逃出去。」

她说完后把视线移到手里的卡片钥匙上。虽然没有控制台卡片便派不上用场，但现在这已经是她唯一的希望了。

亚丝娜走近床铺，假装要躺在床上然后将卡片塞到大枕头下方。

闭上眼睛后，沉睡的薄纱慢慢包围住她那已经疲累的脑袋。

** 第七章

当我来到还留有一点残雪的庭院时，早晨冻人的冷空气迅速将我包围。但即使是这样，停留在脑袋里的睡意却还是挥之不去。

摇了好几次头之后，我才下定决心往庭院角落的洗脸处走去。转开已经有点历史的银色水龙头，然后用手接住流下来的自来水。

将冰冷到让人怀疑怎么没连水龙头都结冻的冷水泼到脸上后，被强迫清醒过来的神经马上发出疼痛感来表达抗议。我不理会疼痛又往脸上泼了两、三次水之后，直接从水龙头上喝起水来。

当我用挂在脖子上的毛巾擦脸时，走廊边缘的玻璃门被拉了开来，穿着运动服的直叶也来到了庭院里。早晨总是相当有精神的她，今天很难得也跟我一样睡眼惺忪地摇着头。

「早啊，小直。」

对她打了声招呼后，她摇摇晃晃来到我面前，一边眨着眼睛一边说：

「早啊——哥哥。」

「怎么看起来还那么想睡。你昨天晚上几点上床睡觉啊？」

「嗯——大概凌晨4点左右吧……」

我感叹地摇了摇头。

「不行唷，小孩子那么晚睡。你在干什么啊？」

「那个——……就上网啊……」

这个答案让我有点惊讶。从前的直叶绝不可能因为上网而熬夜。我不禁有一种「自己不在的这两年里面，这家伙也有所改变了吗」的感慨。

「不要那么晚睡啊。虽然我也没资格说你就是了……」

把后半句话含糊在嘴里带过后，我从昨晚的记忆里想起一件事，于是便对直叶说道：

「喂小直，你向后转一下。」

「……？」

直叶歪着还未清醒的脸半转过身子。我把右手放在水龙头下淋了许多水后，轻轻拉开直叶运动服衣领，然后在她毫无防备的背后滴了一些冰水。

「哇呀——————！」

直叶整个人跳起来发出了震天的悲鸣声。

接着直叶在伸展运动与挥剑练习时也露出一脸生气的模样，但约好请她吃附近复合式餐厅的宇治金时覆盆子冰淇淋圣代后，她总算是原谅我了。

由于今天两个人都睡过头，所以运动结束依序淋浴完毕时，时钟上的指针已经超过九点。

母亲按照惯例还在寝室里昏睡当中，所以便由直叶和我两个人负责准备早餐。

将洗好的西红柿切成六等分后，旁边正在将莴苣切丝的直叶看着我的脸说：

「哥哥，你今天打算做什么？」

「嗯——中午过后我跟人有约了……中午之前想到医院去一趟。」

「这样啊……」

得知亚丝娜目前状况之后，两天到医院去看她一次变成我最重要的习惯。

我在现实世界里只是个无力的十六岁少年，能帮亚丝娜做的事可以说相当有限。不应该说完全没办法帮她做些什么。我能够做到的就只有握着她的手祈祷而已。

我的脑海里浮现艾基尔送过来的照片。

靠着那个线索而踏入了阿尔普海姆的假想世界，花了两天时间终于到达照片里那名少女的所在地附近，但却还没有确实的证据能够证明她就是亚丝娜。有可能自己完全找错方向了也说不定。

但可以确定那个世界确实有些古怪——

希望亚丝娜永远沉睡的男人•须乡。靠他经营的企业来营运的ALfheim Online。残留在那个世界的「桐人」档案，与SAO精神状况管理系统AI「结衣」的存在……目前还不知道这些碎片能拼出什么样的图案来。

今天下午ALO的服务器定期维护结束之后，我将会在那个精灵国度里尝试挑战突破「世界树」。每当一想到这里，兴奋的心情就会让我感到自己背部正在震动。我实在没办法继续待在房间里，想着自己前进的方向是否正确一直到维护结束为止。

所以我决定在那之前先去跟现实世界里的亚丝娜见面，再度确认由她身体散发出来的体温。虽然须乡曾以亚丝娜的现状要挟我别再去医院了，但那个男人应该也没有什么具体的办法可以阻止我才是。

当分工合作处理完西红柿与莴苣后，我将它们和水芹一起放进钵里，然后淋上色拉酱加以搅拌。当我进行作业时，身边的直叶原本完全没有说话，但不久后她便抬起头来说：

「哥哥……我可以跟你一起去医院吗……？」

「咦……」

我不禁感到有些疑惑。至人早为止直叶从没有主动向我询问过关于SAO的事情。除了之前曾向她提过亚丝娜的事情之外，我在游戏里的角色名称以及其他事情全部没对她说过。

想起前天晚上因为遭受亚丝娜婚约事件的打击而在直叶面前哭泣那件事，内心虽然感到有些狼狈，但我还是尽可能用平静的表情点了点头。

「嗯嗯……好啊。亚丝娜一定会很高兴的。」

结果直叶也笑着对我点头，但她的笑容里面似乎带着一丝阴霾，于是我继续盯着她的眼睛。但直叶马上就转过身子，抱着放色拉的钵往餐桌走去。

由于她之后没有什么异状，所以我也马上就忘记直叶那看起来有点僵硬的笑容。

「哥哥，你学校的事该怎么办呢？」

直叶坐在我对面的椅子上，一边发出声音嚼着生菜一边这么问道。

这是个相当重要的问题。我在十四岁，也就是国中二年级的秋天被囚禁到SAO里面，花了两年时间才从里面逃脱出来，现在我已经十六岁了。本来今年四月开始应该就是高中二年级的学生，但我当然没参加过学测，而且脑里的记忆空间大部分都被SAO相关的庞大信息给填满，就算想参加也没办法。应该要花上好一段时间才能忘记道具价格或怪物的攻击模式来改记住历史年号或英文单字吧。

那个戴眼镜的总务省职员应该告诉过我关于学校的事情才对。虽然当时脑袋里尽是亚丝娜的我只是漫不经心地听着，但我还是拼命回忆起来然后回答：

「这个嘛……总务省好像说过要利用在都立高中合并过程中空下来的校舍，成立一所专门的临时学校来给从SAO回来的国高中生就读。当然不用考试就能入学，毕业之后也能获得参加大学学测的资格。」

「原来如此。那真是……太好了……」

直叶虽然一瞬间露出笑容，但马上又皱起眉头含糊的说：

「…………但又好像有种要把所有人集中起来的感觉……」

「哦，你倒是很敏锐嘛。」

我听见妹妹的话之后对她笑了一下。

「我想这就是政府的主要目的了。再怎么说我们这两年来都是生活在充满杀戮的死亡游戏里面，政府应该也很担心我们心理层面会不会受到什么影响吧。把我们集中到一个地方来统一管理，这样他们才有办法安心。」

「怎、怎么会……」

看见直叶脸上的表情整个垮了下来，我便急忙接着说道：

「但是先别理集中管理这些事，政府肯用这种社会援助的方式来对待我们已经是很好了。比如说如果我现在想考普通高中的话，今年就一定得在补习班里拼个一年才行吧。当然这所临时学校也不是强制一定要去就读，也可以选择靠自己的实力去参加学测就是了……」

「哥哥的成绩这么好，就算靠自己也一定没问题的！」

「那已经是过去的事了。我都两年没看书了。」

「那我来当你的家教吧！」

「哦。那就拜托你教我数学和信息处理吧。」

「呜……」

对说不出话来的直叶笑了笑之后，我便把涂上奶油的吐司塞进嘴里。

老实说我现在根本没心情去想学校的事情。我只在意亚丝娜的事情，对于自己是学生这件事情根本还没有什么真实感。

虽然回到这个世界来已经过了两个月，但两把爱剑不在背上的感觉还是让我相当心慌。就算知道这里是现实世界，不会有要夺走我生命的怪物出现，还是会觉得非常不安。今后就算进到学校里就读或是年纪增长，我的本质也都还是「剑士桐人」。「桐谷和人」才是假想存在这样的意识应该还会存在心里好一阵子吧。

或许这是因为在我心里，「Sword Art Online」这款游戏还没完全结束的缘故吧。必须等亚丝娜回到这个世界来，我才能放下手里的剑。等到将她夺回来之后，我的世界才会再度开始转动——

利用手机付完两人份车资之后，我便带着直叶从公交车的下车门来到道路上。虽然平常都是骑车到医院来，但今天停止体能训练而选择了坐公交车。

直叶抬头看了一下眼前的医院后瞪大了眼睛说道：

「呜哇——好大的医院。」

「里面的设备也跟饭店差不多唷。」

我对守卫抬起手打了声招呼后穿过了大门。经过徒步得走上好几分钟的漫长林木道路之后，我们才终于踏进暗棕色的建筑物里面。一向身体健康的直叶很难得来到医院，于是她不断四处张望着。我拉着她的衣领拖着她一起到柜台，请他们发行通行证之后便和直叶一起进到电梯里面。我们在最顶楼步出电梯，然后在无人的走廊上一路走到尽头。

「这里……！」

「嗯嗯。」

我点了点头。然后将通行证放进门旁的细缝里。直叶看着旁边的金属门牌然后开口低声说道：

「结城……明日奈……她的角色名称就跟本名相同（注：日文里亚丝娜发音与明日奈相同）吗。很少有这种人对吧？」

「你倒是很清楚嘛。就我所知直接用本名的人也只有亚丝娜而已……」

我一边说一边将卡片往旁边滑去，接着LED灯便伴随着细微的电子声变成绿色，门也跟着打了开来。

房间里随即流出一股浓郁的花香。我很自然地降低呼吸声，接着往公主安眠的寝室内走去。同时我也从紧跟在我后面的直叶身上感觉到紧张的气息。

把手放在纯白布帘上后，我像往常一样简短地祈祷着。

下一刻我静静将布帘拉开。

★　　★　　★

直叶这时甚至忘了呼吸，只是凝视着躺在大床上的沉睡少女。

一瞬间她差点以为眼前的少女根本不是人类而是精灵一定是住在世界树上，传说中真正的光之精灵。眼前的少女就是给人这种清新脱俗的感觉。

身边的和人也暂时无言地伫立在当场，但不久后便轻叹了口气以细微的声音说：

「我来跟你介绍。她就是亚丝娜……『血盟骑士团』副团长、人称『闪光』的亚丝娜。出剑速度与准确度是我到最后都望尘莫及的……」

稍微停顿一下后，和人便把视线放回少女身上接着继续说：

「亚丝娜，她是我妹妹直叶。」

直叶微微往前走了一步，畏畏缩缩的说：

「你好啊……亚丝娜小姐。」

当然，沉睡中的少女没有答话。

直叶接着把视线移到囚禁少女头部的那顶深蓝色头盔上。那是直叶以前每天见到，有时会对它感到非常厌恶的「NERvGear」。它前端发出深蓝色光芒的三颗LED指示灯正显示——少女亚丝娜的意识依然存在。

哥哥现在应该也跟从前的我一样，体验着心爱的人被关在那个游戏里的深沉悲痛吧。直叶一想到这里，心里便激起了一阵涟漪。

这个像精灵般美丽的人，灵魂竟然被残留在某个异世界当中，这实在是太残酷了。直叶希望她能赶快回到现实世界的和人身边，让他能早日取回发自内心的笑容。

但直叶同时也不想看见和人无言凝视着亚丝娜的表情，于是她垂下了视线。她稍微有点后悔来到这个地方了。

向和人提出同行的要求时，直叶心里想着今天一定要确认自己的心情。

自从母亲翠对她说出真相之后，直叶在这充满后悔与期盼的两年里，内心开始产生一股疼痛感。那种感觉究竟是对哥哥的敬爱，或者是对表哥的爱慕呢。自己究竟希望在和人身上得到什么呢？

就这样一直待在和人身边……然后作一对感情良好的兄妹。但自己真的这样就满足了吗？

除了一起运动、一起吃饭之外，自己难道就真的别无所求了吗？

这是和人回来后的两个多月以来，直叶不断询问自己的问题。

于是她心想：如果能直接与占据和人内心的那个「女孩」见面，是不是就能够得到答案了呢。

但直叶如今站在这间充满金色静谧阳光的病房里时，内心却感到一阵恐惧。她害怕得知真正的答案。

当她一边让自己不去看和人，一边准备开口说「不打扰你们，我先出去了」时——

和人忽然往前走去而让直叶错失开口的机会。他绕过床铺底端然后在对面的椅子上坐了下来。直叶视线里自然映出和人的身影。

和人用双手包围住亚丝娜由纯白床单里露出来的小手，静静地看着少女沉睡的脸庞。当直叶见到和人脸上的表情时——

「呜…………」

有一股尖锐痛楚直接深深贯穿直叶的心脏。

她心想，这到底是什么样的眼神啊。那种眼神简直就像花了好几年……不对，应该说从前世到今生、甚至到来世都不断在寻找命运伴侣的旅人一样。温柔、平稳的光芒深处，可以感受到和人疯狂的爱意，他甚至连眼珠的颜色都跟平时不同。

就在这个瞬间，直叶知道自己心里追求的究竟是什么，但她同时也了解到自己将永远无法达成目的。

她甚至连回家路上与和人说过什么话都记不得了。

回过神来之后，直叶已经躺在自己床上，凝视着天花板上海报的一片蓝天。

这时床头板上的手机发出轻快声音。那不是来电铃声，而是昨天晚上睡前设定好的闹钟。

下午三点，正是ALO的服务器定期维护结束，那个世界的大门再度打开的时刻。

她不想在现实世界里流泪。因为一旦哭出来反而会让自己无法死心。

因此她决定在精灵国度里稍微流些眼泪。如果是那个总是充满元气的莉法，一定能够马上就恢复笑容。

直叶将闹钟停止，接着拿起放在旁边的AmuSphere。静静戴上之后，再度躺到床上。最后闭起眼睛，开始让灵魂飞翔。

她以风精灵族少女的身份在阿尔普海姆央都「阿鲁恩」外围一间旅馆里醒了过来。

昨晚正确来说应该是今天早上，莉法好不容易才从地下世界幽兹海姆里脱身而出。爬完树根上漫长的阶梯之后，结果让人失望的是出口在阿鲁恩街道外围。背后树根上打开来的巨大树洞几秒钟后便合了起来，似乎也不会再次打开的样子。

接着他们一边揉着快闭上的眼睛一边到最近的旅馆登记住房，甚至连订两间房的时间都没有便躺在床上直接睡眠登出了。

莉法撑起身体后坐在床沿。街上的喧嚣、空气的味道以及自己肌肤的颜色都改变了，但刺进心底深处的悲痛感却没有消失。她低下头去，任由痛楚变成液体囤积在自己的眼角。

数十秒之后，她身边随着轻快的效果音出现了另一道人影。莉法慢慢将头抬了起来。

黑衣少年看见莉法的模样后稍微瞪大了眼睛，但马上就用温柔的声音对她说道：

「你怎么了……莉法？」

他那平稳又宛若夜里微风的笑容跟和人有些相似。一见到他，莉法的眼泪便从双眼滑落，变成光点飞散在空中。她勉强在脸上挤出微笑然后开口说：

「桐人……我……我、失恋了……」

桐人深黑的眼眸直盯着莉法看。这个外表看起来相当成熟又带着神秘感的少年一瞬间让莉法有想对他说出一切的冲动，但最后还是咬紧牙根忍耐了下来。

「抱……抱歉，竟然对刚认识的人说出这种奇怪的话来。把真实世界里的问题带到里面来算是违反礼仪吧……」

莉法保持着笑容然后迅速这么说道。但脸颊上的泪水却完全没有停止的迹象。

桐人伸出左臂，将戴着薄薄手套的手放在莉法头上。接着像要安慰她般轻轻地摸了两、三下。

「不论是在外面还是在这里，难过的时候就尽情地哭吧。谁说游戏里面就不能表达自己的感情。」

在假想世界里行动或是说话时一定会有些不自然的地方。但是桐人不论是带有韵律感的柔软声音，或是摸莉法头时的手部动作却都是那么顺畅。这些情报直接温柔地包围并且流入莉法的感觉神经。

「桐人…………」

低声说完后，莉法便将头静静靠在身边的少年胸前。每当悄悄流下的泪水滴落在桐人衣服上时，就会散发出淡淡光芒并且开始蒸发。

——我喜欢哥哥。

莉法像是要确认自己的心意般在胸口深处呢喃着。但她马上又接着说道。

——但是我却不能把这种心情说出来。我得把它埋藏在心底深处。直到有一天完全淡忘为止。

就算实际上是表兄妹，但一直以来和人与直叶之间都是以兄妹相称。如果把自己这种心情表露出来，那么和人及爸妈一定会感到相当困扰与烦恼吧。最重要的是，和人的心已经完全被那个美丽女孩给占据了……

所以我得把这份感情全部忘记才行。

变成莉法的模样，把头靠在不可思议少年桐人的胸前，直叶觉得，有一天自己应该能够忘怀这份情感才对。

虽然维持了这种姿势很长一段时间，但桐人却是一直默默摸着莉法的头。

终于，莉法随着窗外遥远的钟声响起而撑起身体看着桐人的脸。这次她脸上已经有了与往常一样的笑容。泪水在不知不觉间已经停了下来。

「……已经不要紧了。谢谢你，桐人。你人真好。」

听见莉法这么说后，桐人很不好意思的搔着头回答：

「但我常被人说不贴心耶。你今天要不要先下线？我一个人应该也没问题才对……」

「不用，都来到这里了，我就陪你到最后吧。」

莉法迅速从床上跳了起来。她转了一圈半后面向桐人，接着伸出右手。

「来——我们走吧！」

桐人嘴角也浮现平常的笑容，点了点头后便握起莉法的手。当他站起身时，像是想起什么事情般忽然往天空看去。

「结衣，你在吗？」

话还没说完，两个人之间的空间有一道光芒凝结，接着那个熟悉的小精灵便出现了。她边用右手揉着眼睛边打了个大呵欠。

「呼哇～～……早啊……爸爸，莉法小姐。」

小妖精说完后降落在桐人肩上。莉法看着她的脸对她打招呼时顺便问道：

「早啊，结衣。那个——我昨天就有点想问了……你们导航妖精晚上也需要睡眠吗？」

「怎么可能。不过爸爸不在的时候我便会把输入路径中断然后进行既存档案的整理与检验，这可能就跟人类的睡眠行为相当类似吧。」

「但你刚才还打呵欠……」

「人类在展开起动程序时不是都会那么做吗？爸爸的话平均需要约莫八秒……」

「不要说些奇怪的话！」

桐人用食指戳了一下结衣的头，然后打开窗口叫出背后的大剑。

「我们出发吧！」

「嗯！」

莉法点了点头，然后也将爱刀挂在腰间。

两人一起走出旅馆时，刚好是早晨太阳完全升起的时刻。并排在一起的NPC商店大部分都已经开店，反而是夜间营业的酒吧与诡异的道具店都紧闭门户并挂起「Closed」的牌子。

现实时间是平日的下午三点过后，但每周一次的定期维护结束时怪物和宝物的出现机率也会重新设定，所以往来的玩家出乎意料的还不少。

今天凌晨时由于太过想睡而没有仔细观察周围环境，但现在这样看着走在大马路上的人群可以说是充满了新鲜与惊奇感。

这里面有矮小粗壮的身体上穿着金属铠甲，肩上还扛着巨大战斧的大地精灵、娇小的身体只到大地精灵腰部左右，身上带着银色竖琴的音乐精灵、拥有不可思议的浅紫色皮肤，带着黑色珐琅质皮革装备的黑暗精灵等各种种族的玩家们边走边高声谈笑着。另外在随处可见的石头板凳上，红发的火精灵少女与蓝发的水精灵青年含情脉脉地凝视着对方，旁边还有带着一头大狼的猫妖经过。

这里的景色跟街道与居民全部统一成绿色基调的司伊鲁班完全不同，这个地方可以说充满了让人心情雀跃不已的活力。莉法也迅速忘了心底深处的疼痛而露出了笑容。

她心里不禁有了「在这里的话，风精灵与守卫精灵看起来也会跟一般情侣一样吧」的想法，但她还是急忙将这种想法抛到脑后。然后将视线往道路前方看去

「呜哇……」

有些让人难以置信的景色出现在她哏前。

阿尔普海姆的央都阿鲁恩是由圆锥形的超巨大高楼构造所组成。现在莉法所站的地方是离中心相当远的外环部，但还是没办法将重重连结起来的阿鲁恩街景尽收眼底。

阿鲁恩高耸入云的街道表面上蜿蜒着好几根灰绿色的弯曲粗大圆筒。它们与由浅灰色岩石所构成的建材质感完全不同。而每根圆筒的直径都大概有一栋两层楼建筑那么宽。

宛若要包围阿鲁恩中央街道到处蜿蜒的圆筒状物体，其实就是树木的根部。由深层地底幽兹海姆贯穿厚重地壳往上生长的树根，以扭曲的形状逐渐往上聚合并且愈来愈粗壮，最后在阿鲁恩街道的顶点集合为一。也就是说，阿鲁恩街道与从幽兹海姆顶端伸出来的巨大冰柱是互相对称的构造。

当莉法将视线往更上方移去的同时，背上也感到一股足以令人发抖的兴奋感。

由底层开始便有一棵笔墨难以形容其巨大程度的树干笔直朝天空生长。被青苔以及其他植物所覆盖的金绿色树干愈往高处就愈像是和天空融合在一起，颜色也慢慢转变为浅蓝色。最后树干四周全被一片白色物体所包围。当然白色物体不是雾气而是白云。云层是为了标示出飞行限制区域而存在，而树干则是贯穿了云层继续往上方伸展。

在树干快要完全与蓝色天空混在一起而看不清楚的地方，隐约可以见到树干上有粗大树枝呈放射状往外扩展开来。树枝虽然不多但涵盖的范围却相当宽广，甚至连莉法他们所在的外环部上空也被树枝给盖住了。由这种超乎想象的尺寸来看，如果这里有宇宙存在的话树木顶端应该已经突破阿尔普海姆的大气层一直延伸到外层空间去了吧。

「那就是……世界树……」

身边的桐人以敬畏的声音如此嚅嗫道。

「嗯……很壮观吧……」

「对了——你说过那树上面有城市，然后……」

「据说精灵王奥伯龙与光之精灵就住在里面，而最先谒见精灵王的种族就能转生为光之精灵……」

「…………」

桐人无言地抬头看着巨树，但不久后便以认真的表情回过头来说道：

「可以从外侧爬上那棵树吗？」

「树干周围都是禁止入侵的区域，所以不可能爬树。就算用飞的过去，在还没到达上层时翅膀就已经超过限制的飞行秒数了。」

「我听说有群人靠叠罗汉的方式突破了高度限制……」

「啊啊，你说那件事啊。」

莉法持续嘻嘻笑着。

「当时他们还差一点点就要到达树枝了。结果GM似乎也慌了手脚，他们马上就修正了程式。现在云层上面一点的地方已经被设下障壁了。」

「……原来如此……总之我们先到根部去吧。」

「嗯，了解了。」

两人互相轻轻点了点头，然后便往大马路上走去。

在人来人往的混合队伍里面穿梭了几分钟之后，可以看见前方有一道巨大石头阶梯以及上方敞开的大门。穿过那道大门之后终于就要到达世界的中心，阿鲁恩中央城市了。他们抬头仰望天空，发现这时世界树看起来已经像是一面巨大的墙壁了。

他们一边感受庄严的气氛一边爬上楼梯，正准备穿越大门时——

结衣突然从桐人胸前口袋里探出脸来。她用非常认真的表情抬头凝视着上空。

「喂喂……你怎么了？」

桐人像是害怕别人发现般用细微的声音问道。莉法也歪着头看向小妖精的脸。但是结衣只是无言的睁大眼睛看着世界树上方。经过几秒钟之后，从她小小嘴唇里终于发出了沙哑的声音。

「妈妈……妈妈在上面。」

「什…………」

这次换成桐人绷紧了脸。

「真的吗？」

「不会错的！这个玩家ID是属于妈妈的……坐标就在这里的正上方！」

桐人听见之后，立刻用火热的视线抬头看着天空。他的脸色变得苍白，紧咬的牙关用力到几乎快发出声音

忽然间他背上的翅膀张了开来。灰色透明的翅膀瞬间发出白热般光芒，当「磅！」的爆破声在空气中响起时，他人已经从地上消失不见了。

「等……等等啊，桐人——」

莉法急忙大叫，但黑衣少年只是以惊人速度不断往上飞去。虽然不知道究竟是怎么回事，莉法也只得张开翅膀跟着追了上去。

虽说垂直上升与紧急下降都是莉法的得意技巧，但这时却根本追不上像火箭般加速的桐人。黑色身影一下子就变成小小的黑点。

穿越构成阿鲁恩这座城市的无数尖塔群，来到街道上空只花了不到几秒钟的时间。在塔上露台休息的玩家们虽然觉得奇怪而将视线移了过来，但桐人擦过他们眼前之后还是继续上升。

不久之后视线里便看不到任何建筑物，取而代之的是宛如金绿色绝壁般的世界树树干。桐人顺着树干平行飞行，整个人像颗黑色子弹般冲向天际。他愈来愈接近树干周围的一大片白云。莉法这时则是在后面拼命追赶，一边忍受打在脸上的风压一边大叫：

「小心啊，桐人！马上就要碰到障壁了！」

但是桐人似乎听不见她的声音。化身为飞箭准备要贯穿天际的他，像是要把假想世界钻破一个洞般往前突进。

是什么原因让他这么着急呢？在世界树上的某个人对他来说真有这么重要吗？

结衣叫那个人「妈妈」。那么应该是女性啰？能让桐人如此急着寻找的那个人究竟是什么身份？

一想到这里，莉法的胸口深处便又感到一阵刺痛。那跟由和人身上感觉到的痛楚完全相同。

注意力一个不集中，往前冲的速度马上便慢了下来。莉法摇了摇头抛开杂念，将全部精神集中在背后的翅膀上。

晚桐人几秒钟之后莉法也冲进了层层云海当中，放眼所及尽是一片浓密的白色。如果以前听见的传闻属实，这片云海上方已经被设定为不可入侵的区域。她开始减缓速度，接着穿透云层。

忽然一片深蓝色的世界在她眼前展开。与在地面上见到的不同，这里是一整片没有任何瑕疵的蔚蓝天空。头顶上则是如同撑天支柱般往四方扩展枝叶的世界树树干。桐人加快速度对准了当中的一根树枝冲了过去。

几秒钟之后，彷佛落雷般的撞击声让大气为之晃动。撞上透明墙壁的桐人就像只被枪击中的黑鸟般反弹，接着无力地飘在空中。

「桐人——」

莉法发出悲鸣并急忙往桐人身边飞去。由这种高度直接坠落到地面，除了HP会马上归零之外，登出后在现实世界里也会残留不良影响。

但是在莉法追上去之前，桐人似乎就已经恢复意识。他摇了两、三次头之后再度开始上升。但随即就又被障壁挡住，只能在空中撞击出光线效果。

好不容易来到相同高度的莉法，抓住桐人的手臂拼命地大叫：

「桐人，快别这样！没用的，没办法再上去了！」

但是桐人双眼发出有如被附身般的光芒，依然不断尝试往上突进。

「我得过去……我得到那边去才行啊！」

世界树的粗大树枝在他眼前横跨过天空。虽然这时候的树枝已经比在地上时清楚多了，但按照细部绘图的缺少程度来看应该还是有一段距离。

这时候结衣从桐人胸口飞了出去。她边洒着闪亮的光粒边朝着树枝上升。

对了，如果是属于系统的导航精灵……虽然莉法一瞬间有这种想法，但是透明障壁同样冷酷地拒绝了结衣娇小的身体。壁面上一道七彩光芒如同水面上的波纹般扩散并将结衣推了回来。

但结衣却用让人难以相信她是程序的严肃表情，拼命用两手推着障壁开口说道：

「警告模式的声音或许能传到那里去……！妈妈！是我啊！妈妈！」

★　　★　　★

「……！」

亚丝娜忽然感觉到耳边有细微的呼叫声，于是她将原本趴在桌子上的脸抬了起来。

她急忙看着四周围，但金色鸟笼里当然没有其他人的身影。连时常会到这里来的小鸟现在也不在里面。目前只能见到阳光与落在地板上的栅栏影子而已。

当她觉得可能是自已听错了而将两手放回桌上时……

「……妈妈……！」

这次她很清楚地听见了声音。亚丝娜迅速由椅子上站起身来。

那是一道小女孩的声音。这道宛若银弦所发出的声音与亚丝娜遥远的记忆产生了强烈的共鸣。

「是……是结衣吗……？」

亚丝娜发出细微的声音之后冲到栅栏旁边。她用两手抓住金属棒，拼命地看着四周。

「妈妈……我在这里啊……！」

由于那道声音像是直接在亚丝娜脑海里响起，所以她无法马上分辨出来源。但她随后还是感觉到声音是来自于下方。不过就算她再怎么定眼凝神，也无法看透包围巨树的白色云海。但声音确实是由下方传了上来。

「我……我在这里啊……！」

亚丝娜大声嘶吼着。

「我在这里啊……！结衣……！」

如果——结衣这名在SAO里遇见的「女儿」出现在这里的话，那么「他」一定也在这里了——

「……桐人！」

不知道从这边发出的声音能不能让他们听见。亚丝娜立刻看了一下鸟笼内部。除了声音之外还有什么让他们得知自己存在的手段——

这个鸟笼里所有物体都被定位系统给锁住，亚丝娜早已确认过没有办法将任何东西丢到笼子外面。她在很早之前曾尝试过将茶杯以及坐垫丢下去以吸引下界玩家的注意，但最后还是以失败告终。满心焦躁的亚丝娜只能握紧金色栏杆。

不对——

还有唯一的希望。那件物品以前不属于这里。算是规格外物体。

亚丝娜跑到床边，然后从枕头底下将它抓了出来。那是一张小小的银色卡片钥匙。她再度回到栏杆前面。接着战战兢兢地将握住卡片的右手伸出栅栏。如果是以前的话，这时候手便会被透明墙壁挡住了。

「……！」

右手没受到任何阻碍便伸出栅栏。银白色的卡片在太阳光的照耀下发出闪亮的光芒。

——桐人……拜托你一定要注意到……！

亚丝娜一边祈祷一边毫不犹豫地放开手。卡片无声地在天空中飞舞，最后一边发出闪亮光辉，一边一直线朝着云海落下。

★　　★　　★

几乎要将我全身撕裂的激烈焦躁感折磨着我，驱使我挥出右拳大力敲打着透明障壁。拳头就像被强力磁铁的相斥磁力给弹了回来，然后在透明墙壁上形成一道七彩波纹。

「这到底算什么嘛……！」

我从紧咬的牙根里挤出这么一句话。

好不容易历尽千辛万苦才来到这里。关闭亚丝娜灵魂的牢狱就近在眼前。但我却被「游戏系统」这种无机质的程序代码给挡在外面。

强烈的破坏欲望充满我全身，在我心中激起一阵白热的火花。

登入这个ALfheim Online两天，遵循游戏规则而一路来到这里，这段期间持续累积在我内心深处的焦躁感一起爆发了出来。我露出虎牙，右手用力握住剑柄准备将剑拔出。

就在这个时候——

充满愤怒之火的视线前方忽然有一道白光闪烁。

「……那是……？」

我瞬间忘了激愤，凝视着光芒。某件发光物体正缓缓往我们这里掉落。光芒有如飘扬在盛夏青空中的雪片，或是长途跋涉的蒲公英棉毛一般，朝着我的方向落下。

我就这样停在空中将手放开剑柄，朝着光芒伸出双手。在感觉相当漫长的几秒钟后，白色光芒缓缓降落在我手里。我立刻有了某种温暖的感觉，接着把手收到胸前打开。

这时结衣与莉法则由左右两边探头过来看着我的手。而我则是默默凝视着手里的物体。

「……卡片……？」

莉法呢喃了一声。那确实是小小的长方形卡状物体。清澈的银色表面上没有任何文字与装饰。我稍微瞄了一下莉法的脸。

「莉法，你知道这是什么吗……？」

「嗯……我没见过这种道具耶。你何不点一下试试看？」

我听从她的话用指尖在卡片表面上点了一下。但如果是游戏道具的话绝对会弹出来的窗口并没有出现。

这时候结衣探出身子，一边摸着卡片边缘一边说道：

「这是……这是系统管理用的登入码！」

「…………？」

我停止呼吸，凝视着手中的卡片。

「……那只要有这个的话就能行使GM权限了吗？」

「不……要从游戏里进入系统的话，必须要有相对应的控制台。我也没办法直接叫出系统选单……」

「这样啊……但是这种东西不会没来由的掉下来吧。这应该是……」

「是的。是妈妈注意到我们而故意丢下来的。」

「…………」

我静静握紧卡片。刚才亚丝娜还碰过这张卡片。我感觉到似乎可以从这上面读取到一点她的意识。

亚丝娜也在奋战当中。她也拼命想办法要逃离这个世界。我应该还有能做的事情才对。

我看着莉法然后开口说道：

「莉法，请告诉我。通往世界树里面的大门是在哪里？」

「咦……那道门的话在根部的巨蛋里面……」

莉法很担心似地皱起眉头。

「但、但你一个人是办不到的。那里有守护骑士防卫着，至今为止无论什么样的大军团都没办法突破。」

「就算是这样我也非去不可。」

将卡片收进胸前口袋之后，我静静握着莉法的手。

回想起来，这名风精灵少女真的帮了我很大的忙。在这个完全不熟悉的世界里，如此焦急的自己之所以能顺利来到这个地方，绝大部分都是依靠她的知识与开朗笑容的鼓励。总有一天我一定要在现实世界里向她说明一切，然后好好向她道谢才行……我心里一边这么想一边开口说：

「这几天真的很谢谢你，莉法。接下来就让我一个人去吧。」

「……桐人……」

这时莉法已经快要哭出来，甚至连话也说不清楚了。我握紧她的手然后又放开。接着便让结衣坐在肩膀上并后退拉开与她的距离。

我最后又看了一眼这名飘浮在空中的长马尾少女，在深深对她鞠了个躬后便转身离开。

我叠起翅膀，利用重力来加快自己的速度，接着一直线朝着世界树最下端前进。

经过数十秒让眼睛几乎睁不开的急速下降后，错综复杂的阿鲁恩街道终于出现在世界树底部。我在上方巨树的树根之间发现了一座大露台，接着变换姿势并开始减速。

我利用完全敞开的翅膀一边减速一边确定降落地点。在伸出去的双脚碰到石板时已经用尽全力来煞车了，但还是发出响彻四周的巨大撞击声。在露台上眺望风景的几组玩家全都用惊讶的表情看着我。

我等他们将视线移开之后才对肩膀上的结衣小声说道：

「结衣，你知道怎么到巨蛋去吗？」

「嗯，爬上前面的楼梯之后马上就到了。但是——爸爸，这样真的不要紧吗？由至今为止的情报来判断，要突破大门应该是相当困难。」

「也只有尽量试试看了。而且就算失败也不会真的死亡。」

「是这么说没错……」

我伸出手来轻轻摸了一下结衣的头。

「何况再继续浪费时间下去我就要发狂了。结衣你也想早点见到妈妈吧。」

「嗯……」

我在结衣点着头的脸颊上戳了一下，接着便朝着眼前的巨大阶梯走去。爬上幅度相当宽广的阶梯后，我发现这里已经是阿鲁恩的最高处。蜿蜒在阿鲁恩这座巨大圆锥状城市表面的世界树树根在我眼前集中起来形成一根树干。虽说是集合成一根，但由于直径实在太过于粗大，所以从这里看起来就只是一面弯曲的墙壁而已。

这座墙壁上的一个地方，摆放了两尊大概有玩家身高十倍左右的精灵骑士雕像。而雕像之间则耸立了一座上面有华丽装饰的石造大门。这个最终任务的起始点见不到任何其他玩家的身影。应该是「不可能突破」的观念已经在所有玩家之间形成共识的关系吧。

但是我无论如何都要穿越这扇门，然后突破那些叫做守护骑士的家伙，最后到达通往世界树的大门。

——等等我，亚丝娜。我马上就过去了……

我在胸口深处如此嚅嗫着并将这句话深深刻在心里。

又走了数十公尺，当我站在大门前面时，右侧的石像发出重低音并开始动了起来。我有些意外地抬头一看，结果发现石像庄严头盔下的双眼发出蓝白色光芒低头看着我，最后还张开嘴 巴。随即有一道如同大岩石滚落般的声音响起。

「不知天高地厚的精灵啊，汝是否欲前往王城？」

同—时间，我眼前出现询问是否要挑战最终任务的YES、NO按钮。我毫不犹豫地用手按下YES按钮。

结果这次换成左边的石像发出巨大声音。

「如此一来，汝应展示背后双翼足以在天际翱翔。」

当骑士像远雷般的回声仍未消失时，大门中央便裂了开来。接着门更一边发出地鸣一边缓缓往左右两边分开。

这巨大的声音让我不由得想起艾恩葛朗特里的楼层魔王攻略战。当时那种让人为之屏息的紧张感再度出现，我的背后也产生一阵冷颤。

我对自己说完「就算在这里被打倒也不会真的死亡」后，就把这种想法抛到脑后。赌上解放亚丝娜的这场战斗，在某种意义上可以说比过去任何艰辛的战斗都还要来得沉重。

「要冲啰，结衣。你可要躲好。」

「爸爸……加油哦！」

我摸了一下结衣躲进口袋里的头之后便拔出背后的大剑。

厚重的石头大门随着完全敞开而静了下来。门里面则是一片黑暗。我往里头踏出一步，正当开始考虑是不是要使用夜视咒文而准备举起右手时，突然有一道炫目的光芒由头顶上降下。

我不由得眯起了双眼。

门里面是个相当宽广的圆形巨蛋状空间。虽然让我想起与希兹克利夫对战时那个艾恩葛朗特第七十五层的魔王房间，但这里的直径应该超过那房间好几倍。

巨蛋内部就像在树里面一样，地板是由许多如同粗壮藤蔓的物体紧密交缠而成。藤蔓在外围部份垂直上升，除了形成墙壁之外也缓缓延续到屋顶上面。

纠结的藤蔓到了呈半球形巨蛋模样的屋顶上时便较为稀疏，形成了类似彩色玻璃的图样。而白光就是由屋顶后面照射下来。

最后——在屋顶的顶端部分可以见到一扇圆形的门。这扇带着精致装饰的圆形大门，被分割为十字状的四片石板给封闭了。通往树上方的道路应该就在这扇门的后面才对。

我双手握着大剑，深吸了一口气。接着将力量灌注在两脚上并张开翅膀。

「——冲吧！」

发出激励自己的叫声之后，我用力往地上一踢。

往上飞不到一秒钟的时间，屋顶的发光部分就开始有异状产生。一扇发出白色光芒的窗户忽然像沸腾般产生泡沫，看来似乎马上有东西要从里面出现。下一瞬间光芒便幻化成人的形状，接着像水滴滴落般掉进巨蛋里面。一进到巨蛋里，它马上就伸出手脚、展开背后的四片翅 膀并发出咆哮。

那是一名全身穿戴白银铠甲的巨大骑士。脸部由于被类似镜子的面具遮住而看不见。右手上拿着比我手上武器还要长的大剑。这无疑就是莉法所说的守护骑士了。

守护骑士将镜子脸对准了急速上升的我，接着再度发出不像人类的怒吼并由正面开始俯冲。

「给我让开～～！」

我一边大叫一边挥下手里的大剑。随着两者之间的距离归零，脑中忽然有一股像冰冷火花爆开的感觉向我袭来，在那个世界超越极限的战斗当中曾有过好几次的加速感又回到我身上。手里的剑对着守护骑士面具上映照出来的自己用力挥下。

我和那家伙的剑在空中互击，接着像闪电般的效果光线撕裂整个空间。骑士再度准备将整个被弹开的剑由头上挥落，但我却随着剑的去势钻进他怀里。身高大约有我两倍的巨人，领子被我用左手抓住，然后我整个人贴在他身上。

在面对CPU驱动的怪物时，基本上要确认敌人武器所能及的攻击范围，然后尽量处身于攻击范围之外。但在面对这种巨大敌人时，在最近距离之下也常会有死角出现。当然一直停留在这里相当危险，但只是争取一点时间让失去平衡的身体恢复过来的话则没有关系。

我将右手握住的剑往回一扯，接着将剑尖贴在守护骑士的脖子上。

「嘿呀！」

用力一拍翅膀，将全身体重量放在剑上然后向下一压。剑马上随着「喀！」这种硬物碎裂的声音深深刺入骑士脖子里。

「咕啊啊啊啊啊啊！」

守护骑士发出与神圣外表不符的野兽叫声后便全身僵住了。接下来他巨大的身躯便被纯白色的残存之火所包围然后四处飞散。

——行得通！

我内心欣喜地叫道。这种守护骑士在能力上远远不及SAO各楼层的魔王。一对一的话应该是我占优势。

甩开身体周围的白色火焰后，我抬头看向上方的圆形大门。接下来当我看见那种景象时，脸上表情不由得紧绷了起来。

我距离巨大屋顶还有很遥远的一段距离，但那些形成屋顶的彩色玻璃以及所有窗户上都开始出现白色骑士。数量大概有数十——不对，应该有数百名吧。

「————呜哦哦哦！」

为了要鞭策一瞬间感到胆怯的自己，我开始吼叫了起来。不论来多少人马，只要把他们全部干掉就可以了。我震动翅膀，开始全力冲刺。

刚从屋顶上掉下来的几名骑士为了阻止我前进而来到我眼前。我瞄准最前面一名的身体再度挥出长剑。

这次为了避免两剑碰撞造成的身体僵硬，我将注意力集中在敌人斜砍下来的剑尖上，接着回转身体来躲过攻击。虽然因为没办法完全看穿攻击，稍微被剑尖划过肩膀而受到伤害，但我还是无视这点小伤继续把所有注意力都集中在自己的攻击上。

我的大剑直线砍进守护骑士的面具里面，接着将他一刀两断。白色火焰马上喷起，从消失的巨大身躯后面又出现下一名骑士。

发现敌人的剑已经进入攻击轨道后，我判断出已经完全没有躲避的空间。只能咬紧自己的牙根，用左拳拳背来挡开攻击。

随着刺骨的冲击，视线左端的HP条减少了一成左右。但是敌人剑的轨道也因此偏离我的身体，骑士的身躯更因此失去了平衡。我马上用右手上的剑对着他脖子砍了下去。

这次由于攻击速度遭到削落，所以没办法一击便将他击杀。此时右方又有新的守护骑士逼近。我在将身体转向的同时，也利用去势将左脚靴子在受伤骑士的面具上用力一踹。

幸好我从过去的剑士桐人能力档案里，继承了在这个世界被人认为没有用处的体术技能，光靠这一记踢腿似乎就成功削减了敌人的HP值。往后仰的巨体被火焰包围，接着响起悲鸣的音效并爆散开来。

在千钧一发之际我又用剑挡开第三名骑士的巨剑。

「嘿啊啊啊啊！」

我随着吼叫声将握紧的左拳朝镜子面具轰下。「哔叽！」一声过后，镜子表面呈放射状碎裂，骑士同时发出痛苦的吼叫声。

「下去！给我下去啊！」

我奋力大喊着。今天凌晨在幽兹海姆里与水精灵战士作战时未曾感受到的一股燃烧般的破坏冲动，如今正在驱使着我向前。现在我将右手上的剑放在骑士脖子上，开始用左拳不断捶着对方的面具。

是的——我以前曾生活在这样的世界里。曾经一个人在迷宫最深处里彷徨、曾因为不断面临死亡而消磨灵魂，但依然像要用怪物的尸骸来建造自己的墓碑般，不停挥舞着手里的剑。

最后拳头终于贯穿敌人面具，里面立刻有黏液状发光体四处飞散。我随着内心追求杀戮的欲望，左手直接往光芒深处插了进去。当手臂贯穿敌人头部的同时骑士全身也开始溶解，我的身体也被白色火焰所包围。

那时候的我，内心就像石头般干枯坚硬。心里觉得什么完全攻略游戏、解放所有玩家都无关紧要了。我只是不断地拒绝他人，一味追求着下一个战场。

这时又有四、五名守护骑士高举手中光芒四射的大剑，发出像怪鸟般的叫声降了下来。我嘴角露出狰狞的笑容，背上翅膀划破天空直接就往那群骑士冲了过去。剧烈的加速感让我全身神经产生震动，连结脑部与假想肉体的电子脉冲波变成蓝白色火花横跨我的视线。

「呜哦哦哦啊啊啊啊啊啊啊！」

我随着吼叫声将两手握住的剑横向一扫。敌人的剑马上被弹开。我接着像风车般转动身体，将速度提升至极限然后把剑砍向所有骑士的脖子。

「喀！喀！」的钝重声音连续响起，两颗被镜面包围的头颅高高飞向天际。如白色玫瑰般盛开的死亡火焰让我的神经发热，整个人也因此更加亢奋。

将自己置身于死地当中，我才能感受到自己的生命。投身于生死一线的战斗，将生命燃烧到最后才倒地死亡，我曾经认为这样才对得起那些在眼前死去的玩家。

我完全不停止旋转的速度而直接改变身体方向，伸出去的右脚脚尖如同锥子般剌入新出现的守护骑士胸前。尖锐又带有钝重感的刺耳声响起，我的身体整个穿透骑士巨大的身躯。在残存之火当中停下动作后，马上左右两边就各有两把剑朝我逼近。以手上的剑挡下右边来剑，另外以左腕接下左边来剑，完全不去注意HP条的我直接把他们给推了回去。

下一刻我马上抓住右边骑士的手腕……

「咕呜呜呜哦哦哦哦！」

我一边咆哮一边将敌人高高举起，最后把他往左边骑士身上砸去。当两名骑士重叠在一起时再用剑将他们贯穿，给予他们最后一击。

我感觉不论要花多少时间、面对多少敌人，我都可以一直持续战斗下去。就像那个时候一样，让杀戮的怒火燃烧自己，狠下心肠来残杀敌人——

不——不是这样的……

——克莱因、艾基尔、西莉卡、莉兹贝特以及亚丝娜这群人拼命为我早已干枯的心灵灌注了水分。

我……我是为了救出亚丝娜，然后让那个世界真正终结才到这里来的——

我抬起脸，将视线朝屋顶看去。想不到石门这时已经在离我不远的地方。

当我准备朝着石门上升时，某样发出声音的物体贯穿了我的右脚。

那是只散发着冰冷光芒的箭。箭雨像是早已看准我停下动作的瞬间般不断朝我降下。身上连续中了两、三根箭，HP条也开始迅速减少。

环视了一下周围之后，发现不知不觉间在远距离下包围我的守护骑士们都将左手对准我，接着用扭曲的刺耳声音咏唱着咒文。第二波光箭立刻随着尖锐的声音朝我杀到。

「呜哦哦哦哦哦！」

虽然我已经挥舞大剑将不少箭弹开，但还是有好几只箭命中了我的身体。这时HP条直接进入黄色警戒地带。我抬起头，凝视着上方的大门。

要独力击败进行远距离攻击的敌人可以说是相当困难。于是我决定采取强行突破的策略朝大门冲去。降下来的光箭虽然贯穿我全身上下，但终点就在眼前了。我咬紧牙关承受着冲击，伸出左手准备触碰石门——

但是——

再过几秒便要碰到石门时，忽然有一道猛烈冲击撞上我的背部。一名不知道什么时候接近的守护骑士，在镜面面具上露出扭曲笑容的气息并将剑插在我背上。我的身体失去平衡，加速也停了下来。

这时十数名守护骑士像是发现猎物的白色食尸鸟般由四面八方向我涌来。我的身体随着「咚咚」的钝重声音不断被剑刺穿，甚至连确认HP条的时间都没有。

视线里卷起一道带有绿色磷光的黑色火焰。我花了一点时间才领悟到那是我自己的残存之火。这时在火焰前面浮现了一道小小的紫色文字。「You are dead」。

下一瞬间，我的身体就这样四处飞散。

紧接着就像电源被关闭一样，身体慢慢失去了知觉。

在艾恩葛朗特七十五层里与圣骑士希兹克利夫同归于尽而倒下时的记忆鲜明地闪过脑海，我瞬间感到一阵强烈的恐惧。

但我的意识当然没有就此消失。在思考能力有一半停止的状态下，我有了自从SAO封测以来首次的「游戏内死亡」体验。

那是一种不可思议的感觉。视线里的物体失去色彩，一切都被一片紫色所包围。视线中央以与系统颜色相同的细小文字写着「复活剩余时间」，然后右边还有不断减少的数字。视线远方可以见到杀掉我的白银守护骑士们，一边发出满足的声音一边回到屋顶上的彩色玻璃里去。

我的四肢完全没有感觉。现在的我和在这个世界里被砍倒的所有玩家一样，只是一道小小的残存之火，就算想动也动不了。我的心中充满了恐惧、悲伤与卑微的感觉。

是的——我就是这么悲惨。感觉这就是自己在心底某处一直认为这只是个游戏的报应。我所谓的实力其实只不过是名为能力值的数字而已。但我却还天真地认为无论哪个游戏，我都能够超越极限并办到任何事情。

我想与亚丝娜见面，想被她那能包容一切、治愈心灵的温暖臂膀环绕，想在她怀抱里解放所有思考与感情。但她却已经在遥不可及的地方了。

显示在视线里的秒数逐渐减少。我没办法立刻想出当它归零时，我将会变成什么模样。

但无论如何，在这之后我所能做的也只有一件事。那就是再度回到这个地方挑战守护骑士。不论被打倒几次、就算绝对无法获胜——我还是愿意削减、耗损自己的存在，一直努力到自己在这个世界里完全灰飞湮灭为止……

就在这个时候。我朝正下方看去的视线里，忽然横向冲出一道人影。

有人从打开的入口侵入到巨蛋里面，然后以猛烈的速度急速上升。

虽然很想放声大叫「别过来」，但我却发不出任何声音。瞄了一下上空后，发现排在屋顶的白色窗户上又不断产生许多守护骑士。

白色巨人们一边发出刺激神经的叫声，一边通过我身边朝侵入者杀了过去。我已经亲身体验过他们不是单枪匹马就能抵挡的对手。心里虽然拼命祈求入侵者现在赶快逃走，但人影还是一直线朝我飞了过来。

最前列的几名守护骑士依序将右手上的大剑挥落。虽然侵入者以敏捷的行动力躲开这些攻击，但以时间差袭击过来的剑还是划过了入侵者身体。光是这样，便足以将入侵者那娇小的身躯弹开。

但对方却反而利用这个弹力来增加速度，只见那道人影绕过前排骑士们持续上升。随着入侵者愈来愈接近我，屋顶上为了阻止这人而产生的骑士数量也愈来愈增加，并发出奇怪的合唱回旋飞翔。

人影的右手上虽然握着长刀，但都只有拿来防御。在将敌人全部吸引到一个地方后，入侵者反而利用他们当成障壁，然后以优越的机动力确实缩小与我之间的距离。看得出来入侵者已经用尽吃奶的力气来飞行了。

终于来到我眼前时，那玩家流着眼泪大声喊道：

「——桐人！」

来的人正是莉法。风精灵族少女伸出双手，用力将我抱住。

由于已经相当接近石头大门，所以骑士们绝对不允许入侵者继续上升，他们在上空集结起一道厚厚的人墙。但是莉法在抱住我之后便马上回转，接着朝出口直线冲了过去。

背后立刻传来如同诅咒般的咒文咏唱声。下一瞬间白色光箭破空飞来。虽然莉法左摇右晃的让敌人无法准确瞄准，但降下来的飞箭就如同骤雨一般。当她被无法躲过的一箭射中时，震动也同时传到我身上。

「呜……！」

莉法虽然因为这个攻击而屏息，但往前冲的速度却丝毫没有降低。光箭随着「咚咚」的声音不断贯穿莉法身体。她显示在我视线上端的HP条马上减少了一半。

当然对她的追击不仅只有光箭而已。我看见以猛烈速度逼近的两名骑士由左右两方挥下十字长剑。

莉法往右方螺旋飞行躲过一边的攻击，但另一方的金属物体则扎实地砍中她的背部。

「啊……」

莉法发出悲鸣似的声音，接着像皮球般弹了出去，整个人撞上了近在眼前的地板。数度弹跳之后，像要把地面翻起来般滑行了一阵子才停下来。这时数名骑士为了要给她最后一击而降了下来。

莉法以发抖的单手撑起身体并让背上的翅膀拍动了一下。她就靠这样的推进顺势往地面上一滚——接着我的眼前便被一片光亮所包围。我们来到巨蛋外面了。

★　　★　　★

由前所未有的绝望当中逃出生天后，莉法将因为恐惧而发冷的身体整个瘫在石板上大口喘息着。当她往背后看去时，发现应该是任务的设定时间已经结束了吧，巨大的石门开始缓缓关闭，里头的白色巨人们也全都向上飞起。

手臂当中还有一道小小的黑色残存之火正在晃动。莉法她虽然在心底深处呼唤了一句「桐人——」但目前根本没时间让她继续沉浸在感伤当中了。莉法撑起身体，将背靠在旁边巨石像的脚上，接着挥动右手叫出道具窗口。

由于莉法没有完全习得水属性以及神圣属性的魔法，所以没办法使用高等复活魔法。因此她将「世界树的树汁」这个道具实体化，然后用手拿起出现的蓝色小瓶子。

关上窗口拔开小瓶子的瓶盖，将闪亮液体倒在桐人的残存之火上。当场就有像复活魔法般的立体魔法阵产生，几秒后黑衣少年的身影再度出现。

「……桐人……」

莉法坐在地上，用笑中带泪的神情呼唤着少年的名字。桐人也露出了哀戚的笑容，然后单脚跪在石头地板并将右手静静放在莉法手上。

「谢谢你，莉法。但是……不要再做这种危险的事情了。我不要紧的……我不能再给你添麻烦了。」

「什么麻烦……我……」

当她准备说我一点都不觉得麻烦时，桐人已经先站了起来。他转过身子再度朝那扇连结着世界树内部的大门走去。

「桐、桐人！」

惊讶的莉法将力量注入还在发抖的脚上，勉强让自己站了起来。

「等、等等……一个人是办不到的！」

「或许吧……但我还是得去……」

莉法看着背对自己这么说道的桐人，感觉他就跟一尊背负着无法承受之重的玻璃雕像一样。莉法拼命地想要找话来安慰他，但喉咙却像烧焦般发不出任何声音。她最后只能死命伸出双手来抱紧桐人的身体。

她感觉自己已经深深被这名少年所吸引。虽然心底有个声音告诉她：这或许只是为了忘记和人而勉强自己喜欢上这个人罢了，但心底同时也觉就算是这样也无所谓。她认为这是自己最真实的心情。

「不要……再这样了……拜托请你恢复成往常的桐人吧……我……我，觉得自己已经喜……」

莉法的右手轻轻被桐人握了起来。接着耳朵里便听见他平静但充满张力的声音。

「莉法……抱歉……我不过去的话，一切就不会结束，然后什么事情都没办法重新开始。我一定得再见到她才行……」

「得再见到……亚丝娜……」

莉法一瞬间无法理解自己听见的话。蒙上一整片空白的意识当中，桐人所说的话不断发出回音并慢慢消逝。

「……你刚才……刚才……说什么……？」

桐人微微歪着头，然后开口回答：

「啊啊……亚丝娜，就是我要找的人的名字。」

「但是……那个人是……」

「。」

莉法用两手捂住嘴巴，接着往后退了半步。

记忆残像慢慢由整个冻结的脑海里渗了出来。

几天前在道场和她比赛的和人。

初次相遇时，在古森林里击退火精灵的桐人。

记忆中两个人在战斗结束之后，都是迅速左右甩着右手上的剑然后收回背上。动作可以说完全一模一样。

这时两个人的剪影完全重叠在一起，然后放射出光芒并慢慢溶化。莉法瞪大了眼睛，从颤抖的嘴唇里挤出一道微弱的声音。

「……是哥哥……吗？」

「咦？」

听见莉法叫声后桐人惊讶地扬起眉毛。他漆黑的瞳孔直盯着莉法眼睛看。瞳孔里浮现的光芒就像水面上月亮那样缓缓摇晃，接着——

「——小直……直叶……？」

黑衣的守卫精灵利用几乎不成声音的呢喃叫出了这个名字。

周围的石头地板、阿鲁恩的街道与巨大的世界树，感觉包围这一切事物的世界正在开始崩坏，莉法/直叶摇晃着身子退了好几步。

与眼前这名少年一起旅行的几天里面，莉法感觉到这个假想世界的色彩愈来愈鲜艳。光是与他一同飞行，便让莉法的心头感到十分雀跃。

当她身为直叶时喜欢着和人，所以变成莉法时深深被桐人所吸引这件事让她多少有些罪恶感。但是一直以来，阿尔普海姆世界对莉法来说只是假想飞行仿真器的附属品而已，是桐人教会她这里也是另一个真实世界。因此莉法才能了解自己在这个世界的感情并不是数字档案，而是货真价值的感觉。

直叶勉强把爱慕和人的心冻结，感觉上只要能够待在桐人身边，总有一天她就能忘记深埋在心底的痛楚。结果——成为这个世界基盘的「现实」、给予精灵角色生命的其实还是真正的人类这种「真相」，却以想象不到的形式暴露在莉法面前。

「……太过分了……这实在太过分了……」

莉法口中一边梦呓般的低语，一边左右摇着头。她已经没办法继续待在这个世界了。她将视线桐人身上移开，接着挥了一下左手。

触碰一下弹出来的窗口左下角，甚至看也不看浮现出来的确认讯息便直接敲了下去。紧闭的眼睑底下一道彩虹光轮扩散、变淡，接着则是黑暗来访。

在自己床上醒过来后，最先见到的就是映照在阿尔普海姆天空里的一片蔚蓝。平常总是给人一阵憧憬与乡愁的颜色，现在却只能带给直叶痛苦。

直叶缓缓地将AmuSphere从头上拿下，放在眼前。

「呜……呜……」

喉咙深处流出再也无法压抑的呜咽。两手握住由两道细细圆环重叠在一起的单薄机体，放任自己的冲动在手上灌注力量。圆环开始弯曲并发出些微悲鸣。

原本想直接破坏AmuSphere，让回到那个世界的道路永远封闭。但最后她还是办不到。这对在圆环背后那名叫做莉法的少女来说，实在太过于残忍了。

把机械放回床上后，直叶撑起了身体。双脚踏上地板，闭上眼睛并将头垂了下去。此时的她已经不愿意去想任何事情。

但这时一道略带顾忌的敲门声打破了寂静。接下去从门的另一边传来音频与桐人不同，但口气却完全一样的声音。

「——小直，我能进去吗？」

「住手！不要开门！」

直叶反射性地大叫。

「让我一个人……静一静……」

「——你怎么了，小直。虽然说我也很惊讶……」

感觉疑惑的和人继续说道：

「……如果是因为我又使用了NERvGear的话，那我道歉。不过我一定得用才行。」

「不是，我不是为了这件事而生气。」

感情的洪流忽然贯穿直叶全身。她迅速从床上站起来，对着门说道：

「我……我……」

自己的心情擅自变成眼泪与话语溢了出来。

「我——背叛了自己的心。背叛了喜欢哥哥的感情。」

终于对他说出了「喜欢」这个字眼，但这个字眼却像一把利刃般直接切裂直叶的胸口、喉咙与嘴唇。她一边感觉火烧般的痛楚，一边用沙哑的声音继续说道：

「我本来已经决定放弃，忘了一切，准备要喜欢上桐人。不对，我已经喜欢上他了。但是——但是……」

「咦……」

和人霎时说不出话来。最后他只能低声说：

「你说喜欢……但我们是……」

「我已经知道了！」

「……咦……？」

「我早就知道了！」

虽然心里明知道不应该继续。但就是无法让自己停下来。直叶将灌注澎湃感情的视线转往和人，接着用发抖的嘴唇继续说道：

「我和哥哥并不是真正的兄妹。这件事情我两年前就知道了！」

不行。母亲当初不是为了让自己像这样宣泄内心的感情，才拜托自己不要把已经知道这件事的实情告诉桐人。她是希望自己多花一点时间来仔细思考这件事情所代表的意义。

「哥哥之所以会放弃剑道然后开始避着我，是因为很早之前就知道这件事了对吧？因为我不是真正的妹妹才疏远我的对吧？那为什么现在才要对我那么好呢！」

虽然心里很清楚自己不可以说这种话，但嘴里的话就是停不住。每当直叶的声音在走廊冰冷的空气中响起，和人黑色瞳孔里的表情就跟着慢慢流失。

「当哥哥从SAO里回来时……我真的很高兴。而且就像小时候那样对我那么好，真的让我很开心。觉得哥哥终于肯正视我的存在了。」

直叶脸颊上落下两滴再也忍耐不住的泪水。她粗暴地将它们擦掉后，便将紧绷到极点的声音由胸口推了出来。

「……但是……早知道是这种结局的话，那不如一直保持冷淡还好一点。这么一来我便不会注意到自己喜欢哥哥……不会因为知道亚丝娜的事情而难过……也不会为了取代哥哥而喜欢上桐人了！」

听见这些话之后和人稍微睁大眼睛，脸上表情整个僵住。经过所有事物都完全静止般的几秒钟后，他眼神动摇低下头去，只开口说了这么一句话。

「……抱歉……」

醒过来之后的两个月里，和人看着直叶的眼神常带着关爱的光芒。但现在那道光芒已经消失，取而代之的是深沉的黑暗。这情形看在直叶的眼里，心中悔恨的感觉就像一把利刃般，随着激痛狠狠刺进她心底。

「不要管我了……」

她没办法继续看着和人的脸，只觉得罪恶感与自我厌恶已经快将她压垮，于是直叶像逃走般关上门并往后退了几步。当脚跟碰到床时，她直接横躺在床上。

直叶在床上卷缩起身体，肩膀开始因为呜咽而震动。泪水不断由她眼眶中溢出，接着在白色床单上留下些许痕迹后消失无踪。

★　　★　　★

我在关上的房门前伫立了好一阵子。

接着转过身子，将背靠在门上然后缓缓地坐到走廊上。

因为不是真正的妹妹所以才疏远她，其实直叶这样的指责基本上并没有错。但是在我注意到电子户口档案里有被消除的纪录，因而对现在的双亲提出质问时才十岁而已。所以具体来说，我并没有刻意想和直叶保持距离。

从那时候起我便没办法理解人与人之间的距离感究竟是怎么回事。

除了对于亲生父母完全没有印象之外，桐谷峰嵩·翠夫妇在告诉我事实之后对我的态度也完全没有改变，所以可以说没受到什么外在性的冲击。但还是有一种奇怪的感觉在我内心萌芽并且根深蒂固。

那就是在面对某个人时，内心一定会产生「这个人究竟是谁呢？」的疑问。就算是认识相当久、了解非常深的对象应该说即使是在面对家人的时候，我也时常会浮现这种想法。想着「这究竟是什么人？而我真的了解这个人吗？」

或许这种奇怪的感觉，就是让我往网络游戏发展的原因之一也说不定。因为透过网络接触的游戏角色，一定会有另一张脸孔存在。没有人真正知道对方的事情。大家就是在这样的前提下做交流，说起来算是虚伪的世界，但对我来说却是相当舒服的地方。我从小学五、六年级时便开始沉溺于网络游戏，甚至根本可以说是一头就栽进那个不久之后会造成我被幽禁两年的世界里。

名为「Sword Art Online」的那个世界，只要没有死亡游戏的规则，对我来说就是最棒的理想国度。那是个永远不会醒的虚伪梦境，也是个永远不会结束的假想世界。

我在那个世界里，扮演着名字叫桐人的某个人。

但是无法登出的完全潜行型网络游戏这种异常状况，不久之后便不顾我的意愿让我直接了解到一个真理。

那就是不论现实世界还是假想世界，本质其实都是一样的。

因为人类的脑部就是靠处理五感所接收的情报来认识这个世界。而网络游戏之所以能成为虚伪的世界，就只是建立在将游戏机电源关上之后就可以随时脱离这点上面而已。

脑部接受电子脉冲波后所认识的无法登出的世界。

基本上就跟真实世界没有两样了。

当注意到这点时，我好不容易才理解到，从十岁开始就一直困扰着我的疑问实在相当无聊。为了对方究竟是什么人而烦恼根本没有任何意义。我们只要去相信并且接受别人就可以了。我们所认识的那个人，其实就是他最真实的模样。

直叶细微的呜咽声透过房门传了过来。

回到这个世界，刚见到她脸的瞬间，我率直地认为能再见到她真是太好了。我为了取回因为毫无意义的疑问而与她保持距离的数年时间，决定从今以后要去除一切隔阂，以自己最直接的方式来对待她。

但恐怕在这两年里面，直叶她也重新定位了对我的认识。知道我不是真正的哥哥而是表哥之后，因为突然产生的距离感而困惑，然后持续在探索该如何与我相处吧。一直认为她还不知道真相的我，完全没有注意到她的心情。

我在直叶面前好几次表露出对亚丝娜的思念，甚至还因为想着亚丝娜而在她面前哭泣。不难想象这会对直叶造成多么深的伤害。

不，还不只是这样而已。

明明是个计算机白痴又讨厌游戏的直叶，之所以会开始玩VRMMO的理由应该也是为了我才对。直叶是为了理解我的世界而潜行到假想世界里面，花了很长一段时间来培育出另一个自己。那名在阿尔普海姆世界里救过我好几次的少女莉法——她就等于是我眼前的直叶。

至于登入之后首次遇见的玩家为什么会是她，结衣曾推测过可能是与从附近联机至ALO的玩家搞混了也说不定。但其实不是附近，我们根本就是从同一栋房屋里进行潜行，所以IP位置也完全一样。我和莉法之间是注定会相遇的，但我变成桐人的时候脑袋里还是只想着亚丝娜的事情，这点同样也让直叶变成的莉法受到伤害。

我用力闭上眼睛，然后又啪一声迅速睁开，接着两脚用力站了起来。

我要为直叶做我所能办到的事情。当言语没办法完全表达心情时就伸出自己的双手，这是SAO世界里许多人以身作则教给我的道理。

★　　★　　★

力道强劲的敲门声晃动着直叶已经虚脱的意识。她的身体不由得僵硬了起来。

虽然她准备张开口叫对方「不要开门」，但喉咙里却只能发出沙哑的声音而已。不过和人没有转开门把，他只是在门外简短地这么说道：

「小直……我在阿鲁恩北边的露台上等你。」

那是相当冷静平稳的声音。直叶感觉到他说完后便离开了。走廊对面响起开关门的声音，接着又是一片寂静。

直叶紧闭眼着眼睛，再度缩起身子。涌出的泪水啪哒啪哒地直往下滴落。

和人声音里面没有任何动摇的感觉。才刚经过妹妹严厉的指责而已，他马上就已经释怀了吗？

——哥哥真是坚强。但我没办法像你一样啊……

在心中嚅嗫完之后，直叶忽然想起前几天夜里的事情。

那天晚上直人就像现在的直叶一样整个人缩在床上。跟她一样想着遥不可及的那个人而哭泣。那个样子就跟迷路的幼童一样。

而自己就是在隔天与桐人相遇。也就是说和人不知从什么管道——得知沉睡的那个人意识被困在阿尔普海姆的世界树上，所以他挥别泪水，再度握剑投身于假想世界。

——那个时候我对他说了加油。也要他千万不能放弃。但我自己却像这样一直哭泣……

直叶慢慢睁开眼睛。视线前方放着一顶闪烁着光芒的圆冠。

她伸出手将它拿起，接着套到自己头上。

从云层稍多的天空降下来的淡淡阳光，温柔地照着阿鲁恩这座古色古香的街道。

在登入地点见不到桐人的身影。由地图上确认之后，得知目前所在的巨蛋前广场是位于世界树南侧，而北侧有一座办活动用的广大露台。他应该就是在那里等着莉法吧。

虽然已经来到这里了，但老实说莉法还是不敢跟他见面。除了不知道该说些什么之外，也无法预测他会对自己说些什么。莉法默默走了几步之后，在广场角落的板凳上坐了下来。

低着头过了好几分钟之后。忽然发现有人在她面前着地。莉法反射性地绷紧身体，接着闭起眼睛。

但是呼唤莉法名字的却是个意想不到的人物。

「真是的～～我找你好久了，莉法！」

那让人觉得靠不住却又充满精神的熟悉声音响彻整个空间。莉法惊讶地抬起头来之后，眼前出现有着一头黄绿色头发的风精灵族少年。

「……雷、雷根？」

莉法见到那张出乎意料之外的脸孔后暂时忘了心痛，直接问他为什么会出现在这里。结果雷根双手叉腰，很骄傲地挺起胸膛说：

「哎呀——我趁西格鲁特离开下水道时解除麻痹然后毒杀了那两名火精灵逃了出来，本来决定也让西格鲁特吃下毒药但他却不在风精灵领地了，在没办法的情况之下我也朝着阿鲁恩前进，被主动攻击型怪物盯上时我就把它们拖给别人，一直重复同样的动作后才好不容易越过山脉，到达这里时已经是今天中午左右了。整整花了我—个晚上的时间呢！」

「……你那是MPK（注：Monster Player Kill的略称。即利用怪物来杀害别的玩家）的行为吧……」

「这时候就别管那种小事了！」

雷根完全不在乎莉法的指摘，一脸高兴地直接靠紧她坐了下来。这时候他才对莉法只有自己一个人这件事产生疑问，开始四处张望并开口问道：

「那个守卫精灵到哪去了？你们解散了吗？」

「那个……」

莉法先是含糊其词，然后一边拉开两人间的距离一边想着该怎么解释。但她的心底还是被悲伤与痛楚填满，一时想不出什么好的借口来。等回过神来时她已经将自己的心事说出口了。

「……我对那个人说了很过分的话……明明喜欢他，但却说了绝不该说出口的话来伤害他……我实在是个大笨蛋……」

虽然眼泪差点再度夺眶而出，但莉法拼命地不让它们掉下来。雷根/长田只是她的同班同学，而且这里是假想的游戏世界，她实在不想直接让会引起长田困扰的感情暴露出来。于是莉法别过脸去，继续快速地说道：

「抱歉，我怎么胡说八道起来了。当我没说过吧。我不会再跟那个人见面了……我们回司伊鲁班去吧……」

就算在这里逃走，现实世界里两个人的寝室也不过距离几公尺远而已。但莉法实在不敢面对桐人。她心里想着不去桐人等待的地点而直接回司伊鲁班，跟少数几个要好的朋友道别之后便让「莉法」进入沉睡状态。等到某天自己内心的痛楚减轻后，她才有可能再到这个世界来。

下定决心之后莉法便抬起头来看着雷根的脸。接着她便不由得向后一仰。

「怎……怎么了？」

只见雷根的脸像只煮熟的虾子般完全通红，他瞪大了眼睛，嘴巴不断一开一闭。莉法一瞬间忘了这里是街道，还以为他是被人施放了窒息魔法。但下一刻雷根便突然以猛烈的速度抓起莉法双手，然后在自己胸前紧紧握着。

「你、你、你做什么？」

「莉法！」

莉法才刚提出疑问，他便用连远方的玩家都回过头来观看的大音量叫着。莉法虽然已经退到了极限，但他还是将脸挤了过来，在极近距离之下凝视着莉法的脸然后继续说：

「莉、莉法你不能哭啦！脸上没有笑容就不是莉法了！我、我会一直待在你身边……不论是在真实世界还是这里，我都不会让你孤零零一个人……我、我喜欢莉法……也就是直叶你啊！」

雷根的嘴就像坏掉的水龙头般吐出一大串话来，而且不等莉法回答就直接把脸更加往前挤了过去。平常看起来总是相当怯懦的眼睛这时发出异样光芒，鼻子下面的嘴唇高高噘起并往莉法逼近。

「那、那个、等……」

虽然出乎意料之外的突袭算是雷根的得意技巧，但这种乱七八糟的突袭可以说让莉法整个人吓呆了。雷根因此误以为莉法已经答应，于是他马上就将身体靠近，只差没飞扑到莉法身上而已。

「等……等、等……」

当雷根靠近到已经可以让莉法感受到他的呼吸时，莉法才好不容易从僵硬中恢复过来，她立刻握紧拳头。

「我不是要你等一下了吗……！」

她在大叫的同时转过身体，用尽全身力气对准雷根的胸口下方挥出一记下勾拳。

「咕哇！」

虽然在街道里不会产生任何伤害，但还是产生击退效果，雷根往后飞退了一公尺左右才掉落在板凳上。他就这么用双手按住腹部然后以痛苦的声音说：

「呜咕咕咕呜呜呜呜……太、太过分啦，莉法……」

「你、你才过分哩！忽、忽然胡说八道些什么啊，大笨蛋！」

这时终于开始脸红的莉法气呼呼地说道。一想到刚才差点就被夺走初吻，莉法就因为愤怒与害羞的相乘效果而像只快要喷火的龙一样。她不管三七二十一便抓起雷根的衣领，又赏了他几记右拳。

「呜哇！呜啊！抱、抱歉，是我不对！」

雷根从板凳上跌了下去，倒在石板地面上抬起手拼命摇着头求饶。看见莉法终于解除攻击态势后，他才盘腿垂头丧气的坐着。

「咦咦～～……奇怪了……应该只剩下她有没有勇气向我告白这个问题才对啊……」

「……你这人啊……」

莉法实在觉得很无奈，于是她用感触良多的口气说了句：

「真是个笨蛋耶……」

「呜咕……」

见到雷根宛若挨骂小狗般的受伤表情后，笑意开始超越无奈感从心底涌了出来。莉法用力地将带着笑意的叹息由胸口呼了出来，同时也感觉心情似乎变得轻松多了。

莉法忽然有了「一直以来我是不是都太压抑自己了呢」的想法。因为害怕受伤，所以老是咬紧牙根忍耐着。最后因为没办法再阻挡感情洪流的溃堤，才会伤害了对自己来说相当重要的人。

事到如今或许已经太迟了——但至少希望能在最后这一刻展现最真实的自我。一想到这里，莉法便放松肩膀，抬头看着天空。接着开口说了这么一句话：

「——但是我不讨厌这样的你唷。」

「咦？真、真的吗？」

雷根再度跳上板凳，学不乖的他再度准备握起莉法的手。

「别高兴的太早了——」

将手抽出来之后，莉法便轻轻浮上天空。

「——我偶尔也得向你学习才行。在这里等我一下。敢跟上来的话就不只是吃拳头而已啰！」

莉法对愣住的雷根伸出右拳然后又张开来摇了摇手，接着便转过身子。下一刻她便用力拍了拍翅膀，朝着世界树树干高高地飞了起来。

绕着异常粗壮的世界树飞了几分钟后，视线下方出现了一个广大的露台。时常举办跳蚤市场或公会活动的这个场所今天倒是相当冷清。阿鲁恩北侧由于没有什么太壮观的建筑物，所以也就看不到什么观光客。

在空无一人的石板地面中央，有一道瘦小的黑色人影站在那里。他有着锐利造型的灰色翅膀，翅膀上面还斜背着一把巨剑。

莉法用力深呼吸一下后，下定决心降到黑色人影面前。

「嗨……」

桐人见到莉法时虽然有些僵硬，但脸上还是出现了跟平时一样的悠闲微笑，接着他简短地打了声招呼。

「让你久等了。」

莉法也同样笑着对他打招呼。两个人随后陷入一阵沉默。只有一阵风吹拂过两人之间。

「小直……」

不久后桐人首先开口。这时他眼里还带着相当认真的光辉。但莉法却轻轻抬起手阻止他再继续说下去。莉法拍了一下翅膀，稍微往后退了一步。

「哥哥，我们那天还没比完。现在继续来比赛吧。」

说完之后便把手放在腰间的长刀上，桐人这时则稍微瞪大了眼睛。他动了一下嘴唇，似乎准备说些什么，但又马上闭上嘴巴。

这个世界里的桐人只有那深邃的眼神与现实世界里的和人相同，而他现在便用那黑色的眼珠凝视着莉法。几秒钟后，他用力点了点头，随后也拍动翅膀，拉开与莉法间的距离。

「——好吧。但这次我可不会让你啰。」

他带着微笑说完后，手便往背后的剑伸去。

两个人几乎是同时拔剑。两声清脆的金属声重叠在一起。莉法不慌不忙地将爱刀摆在中段，随即笔直地凝视着桐人。桐人降低腰部，与那天一样将大剑垂到几乎快碰上地面的位置。

「不用点到为止也没关系。要上啰——！」

说完后莉法便冲了出去。

在彼此拉近距离的一瞬之间，莉法心里有了「原来如此」的想法那天和人那种乱七八糟却很能发挥效用的姿势，原来是在这个世界里磨练出来的吗？在那两年的漫长岁月里，和人就是赌上性命用剑来进行生死搏斗。

莉法首次有了热切想了解那个世界的想法。她想知道在那个原本只是憎恨对象的死亡游戏里，和人见到了什么、想了些什么，又是怎么样活下去的呢。

莉法将高举的剑一直线向下挥落。虽然这是莉法在司伊鲁班里号称无人可以闪避的斩击，但桐人却以行云流水的动作稍微移动一下身体便躲过了。接着桐人手里的大剑随着风声往上弹了起来。莉法虽然拉回长刀来抵挡，但双臂却因为强烈的冲击而麻痹了。

两人同时利用武器弹开的后座力往后一跳，接着在空中拍动翅膀。他们一边划出两道螺旋轨迹一边急速上升，然后在交叉时用剑攻击对方。如同爆炸般的声光效果在空中产生，整个世界都为之震动。

在剑与剑互击当中，除了是精灵剑士之外同时也是剑道选手的莉法不由得对桐人的动作感到赞叹不已。他利用没有任何多余且类似舞蹈的优美动作，不断使出攻防一体的剑技。

配合他的节奏不断挥剑之后，曾几何时莉法也感觉到自己的技术正在提升至前所未至的领域。现在想起来，过去在这个世界里进行的多次单挑，没有一次是让莉法打从心里感到满足的。虽然被打败过好几次，但那不是因为对方的武器有附加攻击就是敌人使用咒文，并没有任何人可以光靠剑来击败莉法。

但现在她却遇见了这个超越自己的剑士，而且他还是自己最心爱的人，这让莉法产生了一种类似欢喜的情感。就算今后不会再有机会和他谈心，但只要有这样的一瞬间，莉法就觉得已经足够了。这时她注意到自己的眼眶在不知不觉间已经盈满了泪水。

当身体因为剑与剑之间数度的冲击而向后弹时，莉法直接在空中拍动翅膀向后飞以拉开两人间的距离。她张大翅膀静止在空中，然后将剑高举过头部。

看来莉法「这是最后一击」的意思已经传达给桐人知道了。他也转过身体，在身体后方高举起自己的剑。

一瞬间，像寂静湖面般的静谧降临到两人之间。

莉法脸颊上静静流下的泪水最后滴落到石板上，在寂静的湖面激起了一片涟漪。两人这时同时展开动作。

莉法以几乎快让空气起火燃烧的速度向前冲。长刀跟随着她划出一道炫目弧线。她从正面可以见到桐人也以同样的速度冲了过来。而他手里的剑也发出纯白光芒，直接撕裂空气往莉法身上攻去。

当自己的爱刀稍微越过头顶时——莉法松开了双手。

失去主人的剑像光箭般往天空高飞而去。但莉法已经不再注意它的去向，只是张开双臂迎向桐人的剑。

她当然不认为桐人/和人会因为她这么做而原谅她。但是莉法/直叶实在找不出任何言语来为自己的愚蠢而深深伤害到他这件事谢罪。

莉法心里有了至少让自己的分身死在他剑下来赎罪的想法。

她张开双臂，半闭着眼睛，等待着那一瞬间到来。

但是——逐渐沉浸在白光当中的视线里，发现飞过来的桐人手里也没有剑。

「……？」

莉法惊讶地睁大眼睛。视线角落里，可以见到桐人的大剑也与自己的剑同样一边旋转一边往外飞去。莉法将剑放开的同时，他也丢弃了自己的武器。

莉法还来不及想为什么——两人便在空中交错。同样张开双臂的桐人与莉法正面冲撞，一阵让人几乎无法呼吸的冲击后，莉法拼命地抓住对方。

由于撞击的能量无法抹消，所以两人的身体便黏在一起一边回转一边往外飞去。蓝色的天空与巨大的世界树在他们视线里不停地旋转。

「为什么——」

莉法好不容易由嘴里挤出这么一句话。而在极近距离之下凝视着莉法的桐人也同时说出：

「为何——」

两人再度沉默下来，就这么凝视着对方，然后暂时让惯性带着他们在阿尔普海姆的天空当中流动着。不久后桐人张开翅膀，控制姿势让回转停下来并开口说道：

「我——想向小直道歉——但……又不知道该说什么……所以决定要受你一剑……」

莉法感到桐人环绕在自己背后的双臂忽然用力了起来。

「抱歉——小直。我好不容易才从那个世界回来……却没好好去注意你，只顾想着自己的事情……我根本没有好好去听你想要说些什么。真的很抱歉……」

听见这道声音在耳朵旁响起时，莉法双眼里的眼泪便溃堤而出。

「应……应该是我要跟你道歉才对……」

但说到这里时她便再也无法继续下去了。莉法一边放声大哭，一边将脸深深埋进桐人的胸口。

希望能永远持续下去的时间终究会结束，两人轻轻地在草地上降落。当莉法还在哽咽的这段时间里，桐人一直温柔地摸着她的头。但过了几分钟后他便以沉稳的声音开始说道：

「我……其实根本还没有从那个世界里回来。对我来说那个世界仍未结束。只要她还没醒过来，那我在现实世界里的生活就不会开始……所以我现在还不知道该如何去考虑小直的事情……」

「嗯……」

莉法微微点了点头，如呢喃般低声说道：

「我会等你的。等哥哥能真正回到家里来的时候……所以……也让我帮忙吧。告诉我关于那个人的事情，还有你为什么会来到这个世界好吗……」

** 第八章

好不容易将两把飞出去的剑找回来后，莉法和桐人一起降落在有守护神像的大门广场前，这时想不到真的乖乖在这里等的雷根也跑了过来。他看见站在莉法旁边的黑衣少年之后表情马上为之一变，接着歪着头说道：

「那个……现在到底是怎么回事？」

莉法边笑边回答：

「他、我和你三个人要去攻略世界树啰！」

「这、这样啊……什……什么？」

雷根整个人脸色苍白并向后退了好几步，莉法拍了一下他的肩膀，对他说了句「加油啰」之后抬头看着眼前巨大的石门。夹在两尊守护神像之间的巨门像是要拒绝入侵者般带着冰冷空气耸立在那里。

莉法嘴里虽然说着要攻略世界树，但在看过连桐人这种等级的剑士也遭受那么悲惨的下场后，老实说她觉得就算多了两个人也没多大帮助。莉法稍微瞄了一下身边的桐人，发现他也是紧闭着嘴唇露出一脸沉重的表情。

这时桐人像是想起什么事情般抬起头来。

「结衣，你在吗？」

他话还没说完，空中随即有光粒凝结，接着熟悉的小妖精现出了她的身影。她两手用力叉腰，一脸愤慨地噘起嘴巴说道：

「爸爸你太慢了！你不叫我的话我就不能出来了！」

「抱歉抱歉。稍微有点事耽搁了。」

桐人一边苦笑一边伸出左手，而小妖精则是一屁股坐到上面去。结果旁边的雷根忽然快速地探出头来紧盯着小妖精看，接着又爆出一大串话来。

「呜哇，这、这就是宠物妖精吗？我还是第一次见到！呜哦哦，太厉害了，真的好可爱哦！」

结衣见到他的样子马上瞪大眼睛向后退去。

「这、这人是怎么回事啊？」

「喂，你看你都吓到人家了！」

莉法用力拉着雷根耳朵，把他拖离结衣身边。

「你不用理这个家伙没关系。」

「嗯……我知道了。」

桐人以无奈的表情眨了两三次眼睛后，再度看向结衣问道：

「那么——你从上一场战斗里面有得到什么情报吗？」

「有的。」

结衣可爱脸上出现严肃的表情然后点了点头。

「那些守护骑士能力值上并不高，但涌出的模式可以说相当异常。距离圆形石门越近涌出的比例就越高，最靠近时可以达到一秒钟涌出十二只的速度。照这种速度来看……只能说这款游戏的难易度是被设定在无法攻略的等级了……」

「嗯。」

桐人一边点头一边同意结衣的看法。

「守护骑士的个体大概击中一、两次就可以解决，所以才不容易注意到，但他们集合起来根本就跟绝对无敌的大魔王一样。我想应该是将最终任务的难易度设定在似乎可以突破的程度，好藉此来吸引玩家兴趣并且不断煽动玩家的挑战心吧。不过如果是这样的话，那可就麻烦了……」

「但是爸爸的技能熟练度也同样是属于异常状态。所以只看瞬间性突破能力的话，爸爸或许能办到也说不定。」

「…………」

桐人暂时默默考虑了起来，但不久后便抬起头凝视着莉法说：

「……抱歉。可以陪我再冒一次险吗？我也知道聚集更多人马或是寻找别的路径都比现在勉强冲进去要好多了。但是……我心里总有种不祥的预感。似乎剩余的时间已经不多了……」

莉法听见这句话后，一瞬间想要传送讯息到风精灵领地司伊鲁班的领主馆去。她心想不知道能不能请领主朔夜派风精灵族的高等级玩家们前来救援。

但她马上又轻咬嘴唇放弃了这个想法。今天凌晨时在幽兹海姆里遭遇到的水精灵族身影在她脑海里浮现。他们凡事讲求效率与安全，完全不理会莉法他们的请求而准备击毙毫无抵抗能力的邪神。

当然她不认为好朋友朔夜也跟那群水精灵族一样。但再怎么说朔夜她也是背负着重大责任的领袖。在这个位置上的人绝对不能感情用事，必须以全族的利益为前提来进行各种决策。就算他们总有一天会攻略世界树，也应该得等到做好完善准备之后才会付诸实行。她不可能为了莉法一个人的要求便将部队投入这场很可能会遭到全灭的战斗里。

经过短暂沉默之后才抬起头的莉法，用坚定的口气对桐人说：

「我知道了。那我们就再试一次看看吧。我一定会竭尽自己所能来帮忙……当然雷根也是。」

「咦、咦咦～……」

被莉法用手肘一戳之后，雷根虽然跟往常一样把眉毛垂成相当困扰般的八字型，然后发出丢脸的声音，但在碎碎念了我和莉法永远是一体同心等话后便用力点了点头。

石门一边发出宛如来自地底的低沉声音一边缓缓打了开来，感觉上里面似乎有浓厚的妖气流出，让莉法不由得轻轻拍动了一下翅膀。刚才为了解救桐人而冲进去时根本没有多余精神去注意别的事情，但现在再度站到门前便有了相当强烈的心理压迫感。

不过很不可思议的是这时内心却相当平静。

自己目前正处身于风暴当中。无论是在现实或是假想世界里，所有事物都在暴风吹动下而不断发生变化。虽然不知道这场风暴最后会造成什么样的结果，但她现在也只能朝着远方的灯火奋力飞去。

莉法与雷根也随着桐人拔出武器。包含结衣在内的四个人互相看了一眼之后打开翅膀。

「……要冲啰！」

以桐人的叫声作为讯号，所有的人一起往巨蛋里冲去。

按照事前商量好的战略，桐人一开始便猛烈加速往屋顶中央的大门冲刺。莉法和雷根两个人则停留在地面附近开始咏唱起回复魔法。

可以见到屋顶发光部分开始有类似黏液状物体滴落并且不断变成白色巨人。他们边发出恐怖的咆哮边往桐人进攻。当第一波的守护骑士与和他们相比显得十分渺小的桐人交错那一瞬间，响雷般的爆炸声与光芒让巨蛋内部整个摇晃了起来。

看见好几名巨人受到桐人一击而分尸之后，莉法身边的雷根低声呻吟道：

「太厉害了……」

那把剑的威力确实大得吓人。虽然桐人已经如战神般奋力作战，但莉法在见到他前方所出现的景象时，还是不由得全身一阵发冷。

敌人的数量实在太多了。由网状屋顶所产生的守护骑士，其规模已经可以说完全超过游戏的平衡度。现在玩家们都认为地下世界幽兹海姆是难度最高的练功场，但里面迷宫的怪物涌出速度跟这里比起来根本只是小巫见大巫。

守护骑士们聚集成好几个部队，然后成群结队朝桐人展开攻击。每当他们冲过去时空间里便会连续产生炫目的闪光，接着被轰飞的骑士身躯便会像雪片一样落下，但只要有一名被消灭几乎就会有三名新的骑士出现。

当桐人来到距离圆形石门还有一半距离的地方时，HP值终于减少了大约一成左右。但莉法和雷根呈现待机状态的回复魔法马上就发挥作用。桐人身体被绿色光芒所包围，HP条也开始回复。

但是——

当咒文传达到桐人身上时，发生了一件恐怖的事情。

在最低处飞行的一群骑士马上发出简短的怪叫声并将视线朝着莉法他们看去。

「呜哇……」

雷根发出类似痉挛的声音。

莉法感觉到守护骑士们由镜子面具深处投射出来的视线完全集中在自己身上。这让她不禁咬紧了牙根。

为了避免成为骑士们的攻击目标，莉法与雷根决定除了对桐人施展回复咒文之外便不咏唱其他任何咒语。那是因为怪物通常是在玩家入侵反应范围或是以弓箭、咒文由远距离攻击它们时才会展开反击。

但看来这群守护骑士与外面的怪物不同，他们身上背负着充满恶意的系统规则。如果对巨蛋内部的玩家施放回复咒文也会引起他们注意的话，那前卫、攻击手、后卫以及补血者这样正统的队伍分配就根本没意义了。

由五、六名骑士所构成的小队无视莉法心中「别过来！」的祈祷，开始拍动四片翅膀俯冲过来。他们右手上超越莉法身高的大剑正放射出嗜血的光芒。

莉法马上对着雷根大叫道：

「我来引开他们，你继续施放回复咒文！」

她不等雷根回答便开始准备上升。但一直以来在战斗当中都相当遵从莉法指示的雷根，这次却抓住她的右手要她稍等一下。莉法惊讶地回过头后，雷根便用以往不曾见过的认真表情以及因为紧张而发抖的声音说：

「莉法……我虽然还不是很清楚，但这次攻略很重要对吧？」

「——是啊。现在这个时候其实已经不能算是游戏了。」

「……虽然比不上那名守卫精灵……但我会想办法阻止那些守护骑士……」

话才刚说完，雷根便握着遥控器往地面一踢飞了上去。莉法被他突如其来的动作吓到，只能站在当场看着他不断远去，最后由正面冲进守护骑士群里。

「笨、笨蛋……」

——当莉法心里想着那群家伙不是你能应付的对象时，已经再也追不上雷根了。她只好将视线往更远的方向看去，这时又发现桐人原本已经完全恢复的HP再度开始减少。莉法只好再次开始咏唱回复咒文。当她快速念着咒语时，也因为在意雷根而一直看着他的背影。

雷根发射了他在飞行当中准备好的风属性广范围攻击魔法。绿色风刀呈扇状向外放射，缠上骑士后割裂他们的身体。虽然骑士们的HP条只减少了九牛一毛的数值，但他们同时也因此将目标转移到雷根身上。

白色巨人群边发出扭曲的怒吼声，边往与他们对峙的那个瘦小绿色少年攻去。雷根就像一艘在暴风雨中的小船般摇摇晃晃地飞行，他在千钧一发之际穿越那些巨剑并绕到巨人群身后去。骑士们一个急回转后又朝着他追过去。

这时莉法的咏唱结束，在遥远上空战斗的桐人又被一片回复光芒所包围。但同时再度有几名守护骑士产生反应而开始下降。这一团骑士马上和追着雷根那群人会合，因此由巨人集合而成的白色带状物体厚度马上就增长了一倍。

原本空中战斗就不是雷根的得意项目，但他却以惊人的集中力不断躲过往他身上招呼的巨剑。虽然有时会因为被剑擦过身体而减少一些HP，但到目前为止还没受到什么致命性的攻击。

「……雷根……」

他那种拼尽全力的飞行模样让莉法不由得非常感动，但很明显的，他已经撑不了多久了。每当莉法的回复咒文传达到桐人身上，降下来的骑士数量也随着增加。

最后追逐雷根的守护骑士群终于一分为二并开始展开左右夹击的动作。宛如下雨般的无数剑尖里，终于有一根击中雷根背部，将他的身体整个轰飞出去。

「雷根，够了！快逃到外面去！」

再也看不下去的莉法对着雷根如此大叫。一旦退出巨蛋之后，在内部战斗仍持续的时间里面就无法再度穿越那扇大门。莉法做出接下来只有靠自己硬撑到极限为止的决心，一边咏唱回复咒文一边准备起飞。

但就在这时候，雷根稍微回头看了她一眼。看见他脸上出现充满某种决心的笑容之后，莉法又将原本已经打开的翅膀收了起来。

雷根身上虽然不断遭到剑吻，但还是开始咏唱新的咒文。马上有一道紫色效果光包围他的身体。

「……？」

注意到这是黑暗属性魔法的光辉时，莉法不禁屏住呼吸。随着咒文立刻就有复杂的立体魔法方阵展开。由它的大小判断，这应该是相当高级的咒文。由于是风精灵领地里不常见到的黑暗魔法，所以莉法无法立刻得知它拥有什么样的效果。

魔法方阵创造出几道中心轴并随着旋转而不断巨大化，最后魔法全方位包围起所有冲过来的骑士群。复杂的光纹一瞬间凝聚变小——接着又散发出恐怖的闪光。

「啊……！」

莉法因为过于刺眼的光亮而别过头去。接着是一阵天崩地裂般的爆炸声响起，整个巨蛋内部也因此而产生震动。

呈现一片白色的视线经过一秒之后才回复过来。莉法用手挡在眼睛上方然后拼命凝视着爆炸的中心点部分，但她马上就因为过于震惊而说不出任何话来。刚才如此密集的骑士群已经被清除地一干二净。现场只有紫色残光还在空中摇晃着。

这魔法的威力实在太惊人了。风魔法甚至是火魔法中应该都没有拥有如此威力的广范围攻击魔法才对。莉法除了心里惊叹雷根那家伙到底是什么时候学会这种密技之外，嘴里还发出痛快的叫声。只要连续施放几记这种魔法，应该就有可能打开通往石门的突破口了。当她决定先帮雷根回复而伸出手来时她的身体再度僵住了。

残存爆炸余光的场所已经见不到雷根的瘦小身躯。取而代之的是一道微弱的残存之火飘浮在那里。

「——自爆魔法……？」

莉法呆呆地嚅嗫着。话说回来——印象当中确实曾听过黑暗魔法里面有这样的法术存在。但在死亡的同时还会比平常多掉数倍的经验值，所以也就是所谓的禁咒。

莉法静默了好一阵子之后才紧紧闭上自己的眼睛。或许有人会认为这只不过是游戏、只不过是一些经验值，但雷根为了达成目的的努力与热情可以说是货真价值的牺牲。莉法心里想着这下可绝对不能轻易撤退了，她下定决心后张开眼睛凝视着上空。下一刻——

莉法见到那个景象之后，感觉自己双脚上的力量正在流失。

不知不觉间巨蛋的屋顶已经被一大群蠕勫的白色物体给挤得水泄不通。

变成一道小黑点的桐人还差一点点，真的只差一点点就能到达屋顶了。每当他手里的剑光一闪，就会有许多断裂的骑士肢体掉落下来。但这其实只是像精卫填海般的举动而已。由守护骑士身体所组成的白色肉墙只有稍微凹陷，接着马上又填补起来阻挡住桐人的去向。

「呜哦哦哦哦哦哦哦！」

如战神般作战的桐人那呕心泣血的吼叫声也微微传到莉法耳里。虽然她反射性举起双手准备施放回复咒文，但双手随即又无力地垂了下来。她嘴里嚅嗫着：

「……没用的，哥哥……这、这根本不可能……」

桐人表示那个人被囚禁在这个世界里面，但老实说莉法到现在还是无法完全相信这件事。这里再怎么说也只是个娱乐用的假想世界，莉法实在很难相信对她来说就等于是恶梦一样的「SAO世界」也开始侵蚀这里了。

但是现在莉法感受到至今为止从未有过的「系统的恶意」。感觉上原本应该以公正平衡角度来运转整个世界的无形存在——一到这个空间里就变得只对玩家充满杀意，只是不断挥舞着手里沾血镰刀的死神。这就是神的杀意。没有任何人能够抵挡。

忽然一阵如同诅咒般的扭曲低音在巨蛋内响起。

一部分守护骑士停止移动，伸出左手来咏唱咒文。那是桐人首次挑战时封住他行动的光箭咒文。被那种武器射中之后会有短暂的麻痹，接着便会尝到全部骑士的巨剑攻击。

莉法因为脑海里浮现桐人再度被无数刀刃刺穿的景象而整个人冻结。

就在这个时候……

背后突然传来一阵海啸般的吼声，刺激了莉法萎缩的翅膀。

「咦……？」

莉法急忙转过头去，而这时映入她眼帘的是——一大群身穿鲜绿色闪亮铠甲的风精灵战士以密集队形由打开的大门外冲了进来。

这群玩家身上所有的装备都发出让人一看就知道是传说武器等级的光芒。他们如春风般吹拂过莉法身边然后朝屋顶直线上升。总人数大概有五十人左右。

说不出半句话来的莉法将视线集中在那群玩家身上，让表示着他们姓名的箭头不断出现。虽然因为深邃的帽沿而看不清楚他们的脸，但箭头上面每一个名字都是风精灵领地里知名的实力派玩家。守护骑士群在听见他们的怒吼之后停下瞄准桐人的咒文咏唱，再度开始移动。

一道战栗夹杂着感动的感觉让莉法背部开始震动了起来。但参加巨蛋攻略战的还不只有他们而已。

风精灵族的精锐部队通过大门几秒钟之后，门口再度有怒吼声响起。而且声音里面还混杂着类似远雷般的野兽吼叫。

新冲进来的这一团人人数比风精灵部队少了很多。全部大概只有十名左右吧。但他们的体积都相当巨大。

「飞龙……！」

莉法由于太过惊讶而大叫了起来。那是一群有着铁灰色鳞片的飞龙集团，而每头龙从头部到尾巴的长度大概都有玩家的好几倍吧。龙的额头、胸口以及又长又粗的两翼前端闪烁的装甲，代表着它们并不是野生怪物。

坐在龙背上的玩家们，手里都紧握着从龙额头装甲两边延伸出来的银链降生。龙骑士们身上虽然也都穿着全新的铠甲，但跟铠甲比起来，由他们头部两边冒出来的三角形耳朵与腰部下方的细长尾巴更是引人注意。

他们无疑正是猫妖族最终战力的龙骑士队。身为猫妖族最后王牌的他们一直都隐藏在猫妖族领地内，甚至连屏幕影像都完全没有外流。但现在这群传说中的战士就在莉法眼前飞翔着。

莉法被一股全身血液都要为之沸腾的兴奋感所包围，打直了翅膀一直站在原地。这时忽然有人从背后对她说话。

「抱歉，我们来迟了。」

转头一看，站在那里的人正是穿着高木屐与和服便装的风精灵族领主·朔夜。而靠在她身边的猫妖族领主亚莉萨·露则是边动耳朵边开口说道：

「抱歉唷——虽然已经动员所有小矮妖打铁工匠来打造这些人的装备以及龙铠，但还是一直到刚刚才完成唷～现在除了从守卫精灵那里拿到的金钱，连我们和风精灵族的金库也都空无一物了！」

「也就是说在这里全灭的话我们两种族就破产了。」

朔夜将双手环抱在胸前笑着说道。

——她们来帮助我们了。两个人都不顾丧失领主地位的危险，竟然这么快就赶过来了。这只超越掠夺资源这种VRMMO的本质，完全视风险计算为无物的两种族混合部队，一定会发挥出GM所想象不到的力量。

「……谢谢……谢谢你们两位……」

莉法好不容易才以发抖的声音挤出这么一句话。她心里想着「果然这个世界里，还是有比规则与礼仪等常识还要重要的东西」，然后就再也说不出话来了。

但是两位领主则是异口同声的说等一切结束后再道谢也还不迟，接着便以严肃的表情凝视着屋顶。这时朔夜将握在右手里的扇子啪一声打开。

「那么我们也行动吧！」

互相用力点了点头后，三人便往地上一踢飞了起来。而她们眼前的白色守护骑士墙也早就垂下好几道长长的人龙来迎击风精灵部队。桐人虽然还是在中央进行着激战，但他似乎也注意到援军的存在了。只见他停下无头苍蝇般的冲刺动作，开始与墙壁隔开一段距离。

迅速上升至巨蛋中央部份后，亚莉萨·露高举起右手，用她那可爱又清澈的声音叫道：

「飞龙队！喷火攻击准备——！」

十名龙骑士组成包围莉法她们三人的圆阵后便滞空不动。只见翅膀整个张开的飞龙将脖子缩成S型，接着从牙齿深处露出些微橘色光芒。

紧接着朔夜也举起涂着红漆的扇子。

「风精灵队，附加攻击准备！」

围成紧密方阵的风精灵部队也一边突进，一边将右手上的长剑举到头上。他们的刀身上都布满了翡翠色的电网。

由于他们聚集了相当多人，所以如白蚁群的守护骑士一边发出怪声一边往这里杀了过来。

亚莉萨·露以长长的虎牙咬紧嘴唇，一直等到守护骑士来到最近距离时才用力挥下右手，提高声音说：

「飞龙咆哮，发射————！」

十头飞龙听见号令后便将含在嘴里的红莲业火一起喷了出去。暗红色火线拖着长长尾巴飞过整个天空。十道火柱像是要包围风精灵队与在前方的桐人般横跨众人眼前往守护骑士群里冲去。

炫目光芒随着「磅！」一声巨响照亮了整个巨蛋。几秒钟后，膨胀起来的火球不断爆炸并形成一片巨大的火焰障壁。剧烈爆炸声让整个世界产生摇晃。变成碎片的白色骑士残骸呈放射状扩散并拖着白色火焰逐渐燃烧成灰烬。

但几近于无限的守护骑士马上又从肉壁里生出新的一群，他们立刻开始强行突破熊熊燃烧的烈火。他们像液体般扩散成一张大口，似乎是准备以此掩盖在最前线的桐人。

在这些白色肉块杀到之前，朔夜迅速挥下手里的扇子并大叫着：

「狂狼风暴、发射！」

风精灵部队以一丝不乱的动作将长剑刺了出去。由五十把剑各自迸发出来的绿色闪电扭曲着划过天际并深深贯穿守护骑士群。

接着又是一道白色闪光将整座巨蛋染成白色。这次虽然没有爆炸，但四面八方都有巨大的闪电激射，而被闪电击中的守护骑士全都变成了碎片。

大集团被这两次攻击粉碎，守护骑士所构成的墙壁中央部份终于产生了一块大凹陷。但屋顶四周围的液体表面马上像是要填补这块凹陷般又开始慢慢隆起。

莉法确信这是他们唯一的机会。于是她立刻丢开长刀的刀鞘，从空中开始突进。而领主们也做出跟她相同的判断。朔夜尖锐的声音像鞭子般延伸至每个角落。

「全员，突击！」

那无疑是这个世界里所举行过的最大规模战斗。后方断断续续有火焰放射出来，守护骑士也因此而不断着火并往下掉落。采取弹头型密集阵型的风精灵部队为了在肉壁上穿出更深的洞而不断用手上具有强大威力的长剑砍倒直直进逼的巨人们。

站在弹丸尖端的是黑衣守卫精灵的瘦小身影。他身上装备的等级明显劣于风精灵战士们，但手中那以神速挥动的剑无论碰到什么都能令其灰飞湮灭。

莉法冲进风精灵队在中央所打开的缝隙，一路到达桐人身后。她用长刀弹开守护骑士想从后面偷袭桐人的剑，接着刀身深深插到镜子面具底下的白色发光体里。用尽全身力气将刀横向一扫之后，骑士的头颅飞上天空，身体也随着发出白色火焰。

桐人稍微往后一看，然后只用嘴唇这么说道：

「小直——我的背后就拜托你了！」

「交给我吧！」

用视线如此回答完之后，莉法将背紧靠在桐人背上。两个人接下来便开始旋转起来，不断砍倒出现在眼前的守护骑士。

如果是一对一的话，巨人骑士也不是那么容易打倒的对手。但是与桐人紧贴在一起，把速度提升到与他相同的境界时，莉法感觉到骑士们的动作越来越慢了。不对或许应该说是自己神经的反应速度变快了吧？这时一种脑袋中心部份可以直接掌握所有信息的感觉包围住莉法，过去她在几次剑道比赛里面也曾有过几次这种稀有的经验。

感觉上自己已经跟桐人合为一体。青白色电子脉冲波直接流过两人连结起来的神经，让她不用回头看也能知道背后桐人的动作。一名守护骑士正与桐人用剑互击，但她一个转身便将敌人的头砍了下来。莉法才刚在一名骑士身上造成伤口，桐人的剑便往该伤口深深刺了进去。

桐人、莉法、风精灵部队、飞龙部队整合为一个发出光热的能源体，他们开始溶化、挖掘并深深侵入不断出现的守护骑士人墙里。就算骑士的数量是无限的，但巨蛋内的空间却是固定的。只要不断前进，到达终点的瞬间终究会降临。

「嘿呀～～～～！」

被莉法随着吼叫声直接切成左右两半的守护骑士，躯体就这么崩坏并且消散不见。

骑士身后一瞬间可以见到巨蛋的屋顶。

「哦哦哦！」

发出怒吼的桐人从莉法背后离开，变身为黑色闪电往肉壁的缝隙里冲去。最后的守护骑士群为了阻止他而一边发出怨恨吼叫一边由上下左右逼近。它们的总数大约有三十名左右。

「桐人！」

莉法本能性地将自己的手用力往后拉，然后将自己的剑朝桐人左手丢了过去。

边回转一边飞行的淡绿色长刀刀柄就像被吸过去般落入桐人手里。

「呜……哦哦哦哦哦哦————！」

桐人右手上的大剑与左手上的长刀，随着让整座巨蛋产生震动的怒吼以惊人速度交互发动攻击。

剑先从右上方砍下来。接着又从左下方向上撩起。发出光芒的两把剑慢慢改变角度画出一个正圆形。那简直就像日全蚀时在太阳旁边出现的日冕一样。被卷进这数十记超高速连续斩击的骑士们，身体都像纸片般向周围四处飞散。

随后马上扬起一阵剧烈的白色残存之火风暴，但桐人这次已经可以很清楚看见后面的景象。巨蛋那布满网状树枝的屋顶中央，有一扇分割为十字型的圆形大门。那扇贯穿世界树树干，一直通往阿尔普海姆的最后之门。

黑衣少年身后拖着光影直接朝着石门飞去。他终于突破了骑士们的守卫线。

莉法眼前又有好几名骑士重叠起来，立刻就将瞬间打开的隙缝填满了。看见桐人突破防卫线之后，朔夜马上在后方大叫：

「全员转身，撤退！」

随着风精灵部队一起转身，在飞龙咆哮援护之下急速下降的莉法瞬间回头看了一眼屋顶。虽然被守护骑士墙壁挡住而看不见桐人，但莉法心里面还是浮现出桐人的身影。她见到桐人正朝着那过去未曾有人到达过的场所高高地飞去。

飞啊——快过去吧——冲进那道门里！穿越巨树、翱翔天际，一直到世界的核心为止。

★　　★　　★

我以脑神经几乎都要为之灼伤的速度冲过最后一段距离。

眼前就是那座巨大的圆形大门。被分割为四等分的石板组合成十字型状挡住了门口。那女孩——亚丝娜就在这道门后面。她正和我被残留在那个世界的一半灵魂在一起。

背后传来守护骑士们宛若悲鸣的巨大怨叹声。感觉他们已经转过身子来追我。此外从石门周围的屋顶发光部分也立刻有新骑士掉下，他们也全部对准了我冲过来。

但我还是比他们快了一步。现在石门已经在我伸手可及的距离。

但是——但是……

「……打不开……？」

这料想不到的事态让我不由得大叫了起来。

石门竟然打不开。原本以为来到它面前时那可恨的沉重石板便会自动打开，但现在那紧闭的十字沟道却连丝毫摇晃都没有，它依然在那里挡住我的去路。

现在已经没有减速的时间了。我将右手上的剑摆在腰间蓄力，然后随着准备将石门击碎的大剑一起向前冲。

下一瞬间我便随着猛烈的冲击撞上了石门。这时剑尖插在石板上并且爆出大量火花。但是——它的表面却没有任何损伤。

「结衣——这是怎么回事？」

陷入混乱的我如此大喊着。难道这样还不够吗？不只要击退那群守护骑士，还需要某件道具或是触发某个事件才能打开门吗？

当我因为难掩冲动而准备再度挥下手里的剑时，结衣带着银铃般的声音由我口袋里飞了出来。她用娇小双手轻轻摸着紧闭的石板。

「爸爸……」

她马上转过头来开口快速说道：

「这扇门不是因为任务参数才打不开的！它单纯就是要使用系统管理者权限才能打开。」

「你——你的意思是？」

「也就是说……玩家是绝对打不开这扇门的！」

「什……」

我不禁说不出半句话来。

那么这个最终任务——到达世界树上的空中都市就能转生为真正的精灵，根本只是摆在玩家眼前却永远得不到的诱饵吗？除了将难易度提升到极限之外，门上还加了一道永远无法解开，名为系统权限的锁吗……？

我忽然感到全身脱力。这时背后又传来守护骑士朝我杀过来的吼叫声。但我已经连握剑的力气都没有了。

——亚丝娜，我好不容易、好不容易才来到这里……还差一点就能遇见你了……难道说由你手上掉落下来的那一点余温，就是我们两人间的最后一次接触吗……？

不对。等一等，那、那确实是……

我迅速睁开眼睛。马上用左手摸索着腰间的口袋。最后终于让我找到那张小卡片。结衣曾说过这是系统登入码……

「结衣——快用这个！」

我将掏出来的银色卡片拿到结衣眼前。结衣见到卡片后瞬间瞪大眼睛，但随即用力点了点头。

她用娇小的手摸着卡片表面。此时可以看见有几道光线由卡片传到结衣手上。

「我把登入码转移到上面去！」

简短叫了一声后，结衣便用双手手掌敲了一下门的表面。

我因为刺眼的光线而眯起眼睛。结衣手所碰到的部分产生了放射状蓝色闪电线条，接着石门开始发出光芒。

「——要开始传送了！爸爸，抓住我！」

我用左手指尖紧紧抓住结衣伸过来的娇小右手。光线先传到结衣身上，接着也流入我体内。

头部后方的守护骑士们突然发出怪声。我还来不及防御，好几把大剑便朝我插了下来。但是——这些剑简直都像失去实体一般，完全没有带来任何痛楚便穿透我的身体。不，应该说是我的身体开始透明化了才对。只见身体影像逐渐变薄，接着开始溶化在光线当中。

「——！」

我整个人忽然被向前拉去。这时石门已经变成发出白色光芒的屏幕，我和结衣则变成一道奔流往里面冲去。

我的意识陷入短暂的空白状态。

恢复过来后我摇了好几次头、眨了数次眼睛来驱除残留在身上的传送感。虽然跟在艾恩葛朗特里使用转移水晶后的感觉有些类似，但它不像转移水晶一样必定会让人在大门广场的喧嚣当中出现，目前我们周围可以说是没有任何声音。

我由单膝跪地的姿势下缓缓站起身来。眼前马上就见到恢复原本十岁少女姿态的结衣那十分担心的表情。

「你不要紧吧，爸爸？」

「——嗯嗯。这里是……？」

我一边点头一边看着四周围环境。

这真是个奇怪的地方——与司伊鲁班还有阿鲁恩那种施加过多精致装饰好符合最新游戏形象的街道完全不同，映入眼帘的是一整片没有任何细部与纹路的平凡白色面板。

这里看起来像是在某条通道的途中。而整条通道不是直线，而是缓缓向右弯曲。往后一看发现后面的通道也是一样呈弯曲状。看来这不是漫长的弯道，就是圆形的通路。　　「我也不清楚……导航用的地图情报里面没有这个地方……」

结衣也以困惑的表情这么说道。

「知道亚丝娜在什么地方吗？」

一问之下，结衣刻闭上眼睛，接着用力点了点头。

「嗯，非常——非常接近了。妈妈在上面……就在这边。」

由白色洋装下伸出来的赤脚往地板一踢后，马上静静地跑了起来。我将右手的剑放回背上，急忙从后面追了上去。原本在左手上的长刀已经消失不见，应该是被传送到这里时就回到系统上所有者的莉法身边了吧。如果她没有将长刀丢过来的话，我一定无法突破最后的障壁。

我一瞬间闭上眼睛，对残留在左手上的感触表达自己的谢意。

追着结衣跑了数十秒钟后，可以见到左侧，也就是外圈部份有一扇没有任何装饰的门。

「可以由这里转移到上层去。」

听见停下来的结衣这么说后我点了点头，接着将视线移到门旁边但我的身体就此瞬间僵硬住了。

出现在那里的是上下并排的两个三角形按钮。虽然在这个世界里还是首次见到，但是在现实世界里却常可以看见这种形状的物体。这应该是电梯的按键不会错了。

身穿战斗服、背着大剑的我忽然有一种自己不应该站在这里的感觉，这让我不由得绷紧了脸。我错了——是这个地方不对劲才对。如果这真是电梯按键的话，那这里就不是游戏内部了。那……究竟是什么地方呢？

但这问题也只有短暂停留在我脑袋里几秒钟的时间而已。只要亚丝娜在这里，那这里是什么地方根本一点都不重要。

我毫不犹豫地伸手按下朝上的三角形。门马上就随着「碰」的效果音滑开，接着后面出现了一个箱型小空间。我和结衣一起进到里面，转过身来便看见门旁边果然设置了并排着好几个按钮的面板。如果发光的按钮是现在位置的话，这上面应该还有两层楼才对。稍微犹豫了一下之后，我便按下最上面的按钮。

效果音再度响起。门关上之后立刻就有股上升感包围住我。

电梯马上就停了下来。门打开之后出现在眼前的，是一条与刚才相同的弯曲道路。我看着紧握我右手的结衣然后开口说道：

「应该是这层楼没错吧？」

「嗯。已经——很靠近了，就在那里而已。」

话还没说完，结衣就拖着我走出电梯。

我拼命压抑着加速的心跳，继续在通道里跑了数十秒左右。虽然途中内圈出现好几道并排在一起的门，但结衣完全不予理会直接跑了过去。

不久后，结衣在一处没有任何东西的地方停了下来。

「这后面……有一条通道……」

结衣一边嚅嗫着，一边用手在外圈光滑的墙壁上抚摸。一会儿后她的手忽然停止，结果墙壁上出现与打开石门时相同的蓝色光线，光线在墙上划出直角后便继续在墙上跑动着。

粗大线条最后在墙上画出四角形，而四角形更在发出「噗」一声后便从墙壁上消失。里面果然出现一条光滑又平淡无奇的笔直道路。

结衣默默踏入通道后便加快速度往前跑去。看她稚嫩脸上无法压抑的渴望神情越来越浓厚，我就知道亚丝娜已经在我们附近了。

我一边在内心专心念着「快点、再快一点」一边不断向前跑去。不久后，前方道路到了尽头，眼前出现一扇四方形的门挡住我们的去路。但结衣完全没有停下脚步，她直接伸出左手，顺势便将门给打开。

「————！」

逐渐西下的巨大太阳出现在我们正面。

整片世界都是一望无际的夕阳景色。由于视点位置让人感到有些不对劲，我才发现这个地方的设定高度实在是超乎想象。眼前除了可以见到缓缓画出弧形的地平线外，还能听见强风吹过的声音。

我立刻想起了那个瞬间。

和亚丝娜并肩坐着，一起看浮游城末路的那个永恒的夕阳世界。这时耳朵旁又响起她的声音。

「我们要永远在一起……」

「嗯嗯——你说的没错。所以我回来了。」

低声说完之后，我便将视线朝脚边看去。

现在踩在脚下的不是水晶地板，而是相当粗壮的树枝。

因为一直注视深红太阳而变得模糊的视线这时也开始恢复过来。我发现头顶上有着像要撑起天空的树枝，往四面八方伸展，而枝桠上也有相当茂盛的树叶。视线下方还可以见到好几根树枝扩展，而更下方则是一片薄薄的云海。至于遥远地面上则稍微可以见到几条蜿蜒在绿色草原上的河流。

这里正是世界树的顶端。也是莉法……直叶她渴望来到的世界之巅。

但是——

我缓缓回过头去。眼前只有如同墙壁般屹立在那里的世界树树干笔直往上伸展开枝散叶。

「根本没有什么空中都市嘛……」

我呆呆地说道。这里有的只有那条平淡无奇的白色通道而已。那种东西不可能是传说中的都市。说起来如果真如最终任务的宣传台词所写的那样，在突破巨蛋里的石门时应该就要有事件发生了才对。但我的耳朵却没有听见任何奏乐声。

也就是说，这款游戏根本就像是个里面空无一物的礼盒。只是利用好看的包装纸与缎带来包装外表，但里面其实装满了空洞的谎言。我该怎么对如此渴望转生为高等精灵的莉法解释才好呢。

「……不可饶恕……」

我忍不住对运转这个世界的某个人这么呢喃着。

这时右手忽然被轻轻拉了一下。结衣一脸担心地抬头看着我的脸。

「啊，对了。我们快走吧。」

这些事情等救出亚丝娜之后再来想吧。毕竟这才是我来到这里的主要目的。

眼前这根粗壮的树枝朝着夕阳伸展而去。而树枝中央还崁有一条人工小径。小径前方虽然被茂盛的枝叶给遮住了——但树梢后面似乎有物体反射夕阳而发出金色光芒。我和结衣朝着那道光芒跑了过去。

我拼命压抑住马上就要爆发的焦躁与渴望，只是不断在树枝上前进着。只要想到再过几分钟——或是几十秒那个瞬间就要来到，我开始加速的知觉就开始觉得每一刻都变得像是一个世纪那般漫长。

又钻又爬地经过一片深色浓密的奇异树叶之后，我发现道路还是继续往前延伸。每当因为树枝扭曲而出现忽上忽下的短阶梯时，我便振翅直接将它们跳过。

不久后目标的金色发光物体终于出现清楚轮廓。那是一道由金属所制成的栅栏不，应该说是一只鸟笼才对。

我们行走的树枝上方还另有一根与它平行的树枝，而传统式下宽上窄的筒状鸟笼就是被挂在那根树枝上。只不过那是只非常巨大的鸟笼。不要说是小鸟了，甚至连猛禽都能关得进去。是的——那应该是被拿来当成别种用途的鸟笼——

我从感觉上似乎已经是相当久远的记忆里，挖出艾基尔在自己店里时所讲过的话。曾有五名玩家利用叠罗汉方式逼近世界树，然后在极限高度下拍摄了影像。那张照片拍到树上有一名少女被关在不可思议的鸟笼里。对了，不会错的。亚丝娜她就在那只鸟笼里面。

结衣那拉着我右手的小手也因为确信亚丝娜在那里而加强了力道。我们以几乎可以算是在空中滑行的速度跑着，接着跳过最后一段阶梯。

崁有小径的树枝忽然急遽变细并连结到鸟笼底端，道路就这样到了尽头。

金色鸟笼的内部这时也已经清楚地呈现在我们眼前。里面有一株巨大的盆栽以及各式各样的花盆点缀着白色瓷砖地板。中央则是一张附有顶蓬的豪华公主床。旁边还有一张纯白圆桌与一张椅背相当高的椅子。一名少女坐在椅子上，两手合在一起置于桌面，似乎在进行祈祷般垂着头。

少女有着一头柔顺的直长发。身上穿着与结衣类似的白色薄洋装。此外少女背后也长有优美的纤细翅膀。鸟笼里的一切事物这时都被快下山的夕阳照成一片红色。

少女的脸庞因为被阴影遮住而看不清楚。但我早已经知道她是谁。应该说我怎么可能会不知道。吸引我们两人灵魂的磁力变成一道透明闪光，直接串联起我和少女的心灵。

下一个瞬间，少女——亚丝娜迅速抬起头来。

或许是太过于思念她了吧，她那令人怀念的身影在我脑海里早已升华为充满光芒的女神形象。那种时而像是把锋利刀刃的伶俐美、时而让人感到亲切又调皮的温暖再度在脑海里浮现。

而在那段短暂又令人怀念的日子里，总是在我身边的那张脸庞这时先是出现惊讶的表情，接着又用原本合起来的双手捂住嘴巴。她黄褐色的大眼睛盈满了快要溢出来的光辉，接着马上变成眼泪停留在睫毛上。

我一边飞过最后一段路程，一边用几乎快听不见的声音呢喃道：

「亚丝娜——」

结衣也同时大叫了起来。

「妈妈……妈妈！」

小径与鸟笼连接的终点部分有着一道比壁面还要密集的栏杆所组成的四方门，门旁有一片应该是门锁的小金属板。门虽然紧闭着，但拉着我手的结衣却依然不减速度，在门前直接将右手在身体左侧扬起。这时她手上开始出现蓝色光芒。

她把手往右边一挥，门和金属板随即一起飞了出去。接着两样物体便化为光粒并消失无踪。

结衣放开我的手，用力伸直自己的双臂并再度大喊着：

「妈妈——！」

她一口气由打开的入口冲进鸟笼里。

亚丝娜这时也踢倒椅子迅速站起身。她原本捂住嘴巴的双手也完全打开，接着由她嘴唇里发出颤抖但相当清楚的声音。

「——结衣！」

结衣往前冲的娇小身躯马上扑进亚丝娜的胸口。两人栗色与漆黑的长发在空中摇曳并且发出夕阳的橘红色光芒。

紧紧相拥的结衣与亚丝娜把脸颊靠在一起，像要确认彼此的存在般又叫了一次对方。

「妈妈……」

「结衣……」

不断由两人脸上落下的泪水，在夕阳照射之下发出如火焰般的光辉后消失不见。

我放慢奔跑的速度，静静地往亚丝娜走去，但在离她还有几步的距离时便停了下来。抬起头来的亚丝娜眨了眨眼让眼泪滑落，接着由正面看着我。

我就跟那个时候一样无法动弹。我害怕继续靠近并用手去触碰她的话，她马上就会消失无踪——而且我现在的样子与过去完全不同。守卫精灵无论是浅黑色皮肤或是刺猬般发型都与过去的桐人完全没有共通点。我只能忍住眼泪，站在当地一直凝视着亚丝娜。

但亚丝娜果然跟那个时候一样张开嘴唇，然后叫出我的名字。

「桐人——」

一瞬间的寂静之后，我也开口叫着她的名字。

「亚丝娜……」

我跨出最后两步然后张开双臂，用力抱紧娇小的亚丝娜以及在她胸口的结衣。怀念的香气飘散在空气当中，怀念的温暖整个渗透到身体里面。

「抱歉……我来迟了……」

我用颤抖的声音低声说完后，亚丝娜她从至近距离之下笔直地看着我的眼睛回答道：

「不会，我一直相信……你一定会来救我的……」

这时已经不需要任何言语。我和亚丝娜两人一起闭起眼睛，互相将脸靠在对方的肩膀上。亚丝娜也将手臂绕到我背后并用力抱紧我。结衣在我们两个人之间呼出感到非常幸福的一口气。

——我心里想着这样就够了。

如果这个瞬间就是我生命的最后一刻，那么即使就此死去我也毫不后悔。原本在那个世界就应该结束的两条生命变成在这里完结，我们两人就是为此而活到现在……

——不对，不应该有这种想法。我们现在才终于要开始属于我们的未来。这么一来，那个剑与战斗的世界总算结束，我们也可以一起展开名为现实世界的全新旅程了。

我抬起头这么说道：

「我们回现实世界去吧。」

解开彼此的拥抱之后，我和亚丝娜紧握着对方的手，而结衣则是被亚丝娜用另一只手抱着。我看了一下小女孩的脸，对她问道：

「结衣，可以从这里让亚丝娜登出吗？」

结果结衣瞬间皱起眉头，接着又立刻摇了摇头。

「妈妈的角色被复杂的程序代码给限制住了。要解除的话必须要有系统控制台才行。」

「控制台……」

正当我感到疑惑时，亚丝娜以紧张的声音这么说道：

「我在研究室的最下层发现到应该是控制台的东西。啊……研究室就是……」

「你是说那条白色空无一物的通道吗？」

「嗯。你们是经过那边来到这里的吗……？」

「嗯嗯。」

看见我点头之后，亚丝娜似乎有些不安地绷起了脸。

「没有什么奇怪的东西在吗……？」

「没有，我们没遇上任何人……」

「……须乡的手下有可能在那边徘徊。到时候你就用手里的剑把他们给砍了！」

「咦……须乡？」

听见亚丝娜说出来的名字后，我在惊讶的同时也马上了解到是怎么回事。

「就是那个男人把亚丝娜关在这里的吗……？」

「嗯嗯。还不只是这样而已——须乡他还在这里进行恐怖的……」

亚丝娜愤怒的想要说些什么，但马上又摇了摇头。

「剩下的等回到现实世界里再说吧。须乡他现在不在公司里的样子。得趁现在夺取服务器然后解放大家……我们快走吧！」

虽然还有许多事想问，但目前最重要的就是让亚丝娜回到现实世界。我点了点头后便转过身子。

我抓住亚丝娜抱着结衣的手，马上朝着门已经消失的入口跑去。前进了两、三步，当我缩起身子准备钻过栏杆时……

——我感觉有人正看着我们。

我脖子后方忽然产生一阵让人不舒服的感觉。在SAO世界里，被怪物之外的橘色箭头杀人玩家躲在暗处盯着时就是这种感觉。

我马上放开亚丝娜的手，改握住背上的剑柄。当我准备拔剑而稍微动了一下手腕的瞬间……

鸟笼里忽然进水了。某种高黏性的深色液体「咚噗」一声将我包围住。

不对，看来不是鸟笼进水。因为我目前还可以呼吸，但空气却感觉异常沉重。只要我想移动身体，就会像处身于极为浓稠的黏液里一样感觉到强烈的抵抗感。这时我的身体变得相当沉重，甚至连站立都感到相当痛苦。

同时外界的亮光也逐渐离我远去。原本充满整个鸟笼里的夕阳光芒现在已经慢慢被深沉的黑暗所掩盖。

「——怎、怎么了？」

亚丝娜大叫了起来。她的声音也像从深海里发出来般扭曲不清。

我一边有种非常厌恶的战栗感，一边想要转过头来抱住亚丝娜和结衣。但是——身体却完全无法行动。黏稠的空气像是有意志般缠着我的身体。

不久之后整个世界终于陷入一片黑暗当中。不对，这种形容有点不太妥当。我还可以很清楚地看见穿着白色洋装的亚丝娜与结衣。但除了她们之外，视线里其他背景都被一片浓密的黑色给掩盖住了。

我咬紧牙根拼命动了一下右手。鸟笼的栏杆应该就在我附近才对。我心里想着要抓住栏杆，然后把身体拖离开这个空间——但伸出去的手却什么都没碰到。

原来不只是外表而已。我们是真的被丢进一个未知的黑暗世界里了。

「结衣——」

当我准备问她清不清楚这是什么状况时……亚丝娜手臂里的结衣忽然仰起身体并发出悲鸣。

「哇呀！爸爸……妈妈……小心啊！有某种……不好的东西……」

话还没说完，结衣娇小的身体表面便有紫色闪电爬过，然后瞬间爆出炫目的闪光——等我们回过神来时，亚丝娜臂弯中已经见不到她的身影了。

「结衣？」

「结衣——？」

我和亚丝娜同时叫道，但没有得到任何回答。

在浓稠的深沉的黑暗当中，只有我和亚丝娜被留了下来。我拼命伸出手想把亚丝娜的身体拉过来。这是以不安的表情瞪大眼睛的亚丝娜也朝我伸出手来。

但是我们两个人手指碰到对方之前，一股剧烈的重力忽然压在我们身上。

我简直就像被丢进一座深沉的黏液沼泽底部一样。由于承受不住压在全身的重量，我一只脚不禁跪了下去。同一时间亚丝娜也整个人倒了下来，两手撑在看不见的地板上。

亚丝娜看着我的眼睛，张开嘴巴说着：

「桐……人……」

不要紧的，无论发生什么事我都会保护你——当我准备这么回答时……一道夹杂黏稠笑声的尖锐声音在黑暗中响了起来。

「嗨，这个魔法滋味如何啊？我预定在下一次更新时导入它唷，效果是不是太强了一点？」

我记得这道带有浓烈嘲弄感的声音。这道声音正是来自于在沉睡的亚丝娜面前，揶揄我是英雄的那个男人。

「——须乡！」

我一边挣扎着想要站起来一边愤怒地大叫。

「啧啧，在这个世界里可不可以别用那个名字叫我啊。直呼你们国王的名讳未免也太没礼貌了吧。应该要叫我——奥伯龙陛下才对！」

那道声音的语尾往上升后整个变成了尖叫，同时也有某样东西用力敲打着我的头部。

转动头部之后我才发现，那男人不知道什么时候已经站在那里了。他脚上穿着满是刺绣的靴子，而穿着白色紧身裤的另一只脚则放在我头上左右来回移动。

将视线往上移之后，可以见到他那身刺眼的绿色长袍，以及上方那像是塑造出来的端正脸孔。不对——那原本就是塑造出来的结果。但完全由多边形构造出来的美貌上没有丝毫生气，看起来反而让人觉得相当丑恶。他鲜红的嘴唇整个扭曲，脸上浮现出过去曾见过的那种笑容。

就算外表不同，我也可以很清楚地知道这个男人就是须乡。他就是强行夺走亚丝娜灵魂并把她关在这种地方，让我恨之入骨的那个男人。

「奥伯龙——不，须乡！」

亚丝娜虽然倒在地板上，却还是坚强地抬起头尖声叫着。

「我亲眼见到你所做的坏事了！竟然做出那种残忍的事情……我绝对饶不了你！」

「什么？谁饶不了我啊？你吗？还是他呢？该不会跟我说是神吧？很可惜，这个世界里除了我之外就没有别的神了，呵呵——」

须乡用夹杂刺耳笑声的声音说完后，又更加用力地踩着我的头。我因为无法承受重量而整个人趴到地上。

「快住手，你这卑鄙小人！」

须乡完全不理会亚丝娜的骂声，直接蹲了下来从我背上的剑鞘里拔出大剑。巨剑垂直立在他伸长的食指上，接着开始旋转了起来。

「话说回来——桐谷小弟，不对……应该叫你桐人比较好吧。没想到你真的会来到这个地方。不知道该说你是勇敢呢还是愚蠢。不过看你现在这样狼狈地倒在地上，我想应该是后者吧，呵呵。我听说我可爱的鸟儿从笼子里逃出去，所以赶回来要给她严厉的处罚，结果可真令人惊讶啊！鸟笼里竟然有蟑螂混进来了！倒是——刚才好像还有还有一个奇怪的程序在运作……」

须乡说完之后便迅速挥动左手叫出窗口。他歪着嘴注视发出蓝光的窗口一阵子之后，才又用鼻子哼了一声然后将窗口关闭。

「……逃走了吗？那到底是什么？说起来你们到底是怎么爬到这里的？」

知道结衣应该不是被他给删除了之后，稍微感到安心的我开口回答：

「用这双翅膀飞过来的。」

「——哼，随便了。反正之后直接问你的脑袋就能知道。」

「……什么？」

「你不会以为我是因为兴趣而制作出这整个世界的吧？」

须乡让剑在他指尖上不断反弹着，然后露出阴险恶毒的笑容。

「靠着前SAO玩家们的牺牲奉献，思考·记忆操纵技术的基础研究已经完成了八成左右。再过一阵子我就可以完成直接操纵人类灵魂这种过去从未有人成功过的神技了！而且我今天又得到这么棒的新实验体。哎呀，实在太让人高兴了！光是想到能窥看你的记忆、改写你的感情我就感到兴奋不已哪！」

「怎么可能……办到那种事情……」

对方那超乎想象的发言让我一边感到惊愕一边这么说道。须乡这时则再度把右脚放在我头上，然后用脚尖戳着我。

「你又不怕死地戴上NERvGear了对吧？那你现在的状况就跟其他实验体完全相同。小孩子果然就是这么笨。连狗被踢过一次之后都知道要学乖了。」

「须……须乡，你敢这么做的话我绝饶不了你！」

亚丝娜脸色苍白的大叫着。

「你要是敢对桐人出手，我一定饶不了你！」

「小鸟儿啊，只要一个按钮就能让你现在的憎恨变成绝对服从的日子马上就要来临啦！」

须乡用陶醉的表情说完之后重新握好剑，然后用左手指尖慢慢抚摸刀身。

「接下来！在窜改你们的灵魂之前，我们就来办个有趣的派对吧！啊啊……终于到了这个期待已久的时刻。现在最棒的客人也来到了现场，我拼命的忍耐也算值得了！」

他将身体转了个圈，接着大大张开双臂。

「现在这个空间的所有档案情报都会被纪录下来！你们就尽量作些生动的表情吧！」

「…………」

亚丝娜紧咬住嘴唇，接着又凝视我的眼睛迅速说道：

「桐人……你现在马上登出。然后到现实世界里揭发须乡的阴谋。我不要紧的！」

「亚丝娜……！」

听见她这么说之后，我心里的挣扎几乎快将身体撕裂。但我还是马上点头并挥动左手。有这么多情报的话，就算没有物证也能让解救小组有所行动也说不定。只要能夺回在「RECT·PROGRESS」的ALO服务器，就可以让须乡招认所有罪行了。

——但是窗口却没有出现。

「啊哈哈哈哈哈！」

须乡弯下身体，捧着肚子放声大笑。

「我不是说过了，这里是我的世界！没有任何人可以从这里逃出去！」

他让身体不断向上弹起并且跳舞般走动着，但突然又扬起左手。弹了一下指头之后，被无尽黑暗所掩盖的天空上便有两条锁链垂了下来。

随着刺耳金属声降下来的锁链前端，有两只发出暗沉色泽的宽大金属环挂在上面。须乡拿起其中一只金属环后抓起倒在我眼前的亚丝娜，然后将她的右手随着「喀叽」这种金属声锁进圆环里面。接着他又轻轻拉了一下垂在黑暗当中的锁链。

「哇呀！」

锁链忽然往上卷，亚丝娜的右手也被抬了起来。锁链一直上升到她的脚尖已经快碰不到地面时才停了下来。

「你这家伙想干什么……！」

我虽然这么叫道，但须乡却完全不理我，只是哼着歌然后拿起另一边的圆环。

「我准备了许多小道具唷。那我们就先从这里开始吧。」

须乡边说边将亚丝娜的左手也锁上，然后又拉了一下锁链。另一条锁链也开始上升，最后亚丝娜便以两手被强行往上拉的姿势吊在半空中。强烈的重力似乎仍然对她产生影响，让她优美的眉毛皱了起来。

须乡两手抱胸站在亚丝娜眼前，接着吹起低级的口哨。

「真漂亮。NPC的女性果然做不出这种表情。」

「哼……！」

亚丝娜先是恶狠狠地瞪着须乡，然后便低下头紧紧闭住眼睛。须乡在喉咙深处发出咕咕的笑声，接着绕到亚丝娜身后。他用手抓起亚丝娜的一缕长发，放在鼻子上用力吸了一口气。

「嗯——真是香啊。要忠实呈现亚丝娜在现实世界里的香味可花了我好一番功夫哪。真希望你能体会我特别把解析机搬到病房里的苦心。」

「快住手……须乡！」

我全身燃烧着无法压抑的怒火。红色火焰流过我的神经，让压在身体上的重力瞬间消失无踪。

「呜……哦……」

我伸出右手，将身体由地板上撑了起来。立起一边膝盖之后，把全身力量灌注在上面来慢慢抬起自己的身体。

须乡用演戏般的夸张动作把左手插在腰上并左右摇着头。他走到我眼前来时歪着嘴说：

「哎呀，观众只要乖乖……趴在地上看就行了！」

两脚忽然被他横扫过去，失去支撑点的我再度跌在地上。

「咕啊——」

几乎让肺部破裂的冲击使我不由得发出悲鸣。我再度把手撑在地上然后抬头往上看去，只见须乡露出只有嘴角上扬的狠毒笑容然后右手拿着我的剑直接往我背上用力刺了下来。

「呜……！」

被厚重金属贯穿的感觉将我神经当中的火焰完全熄灭。剑似乎穿透我胸口中央而深深插入地面。虽然没有疼痛感，但却有一股强烈的不舒服感觉袭上心头。

「桐……桐人！」

我朝发出悲鸣的亚丝娜看去，准备开口告诉她我不要紧。

但是在我开口之前，须乡便忽然抬头看着黑暗天空然后说：

「系统指令！将疼痛缓和装置变更为第8级。」

他话刚说完，一股被利刃刺入的疼痛感马上由背上传了过来。

「呜……咕……」

听见我发出呻吟声后，须乡便发出相当愉快的笑声。

「呵呵呵，这只是开胃菜而已唷。我会一个阶段一个阶段的把它增强，你好好期待吧。降到第3级以下时，似乎登出之后也会有休克症状出现唷。」

他说完后便拍了一下手，然后又回到亚丝娜背后。

「须……须乡！现在马上就放我下来！」

当然他还是丝毫不理会亚丝娜的吼叫。

「我呢，最讨厌像他这种小鬼了。这种没有任何能力与背景，只会出一张嘴的小虫子。呵呵，所以得像在标本箱里的虫子一样把他钉住才行。而且你现在都自身难保了，还有时间替他担心吗，小鸟儿？」

须乡从后面伸出手来，用食指在亚丝娜脸颊上轻轻摸着。亚丝娜虽然转动脖子想躲开他，却因为强烈的重力而无法如愿。

指尖在亚丝娜脸上到处游移了一阵子，最后来到了她的脖子上。这时亚丝娜脸上露出厌恶的表情。

「快住手……须乡！」

我一边死命想撑起身体一边大叫着。结果亚丝娜露出坚强的笑容，以颤抖的声音对我说：

「不要紧的，桐人。我不会因为这点小事就受到伤害。」

须乡一听见她这么说，马上就发出了杀鸡般的笑声。

「就是得这样才行。我看你还能嘴硬多久三十分？一小时？还是一整天？拜托你要尽量延长我的乐趣啊——」

须乡这么大叫的同时，右手也抓住亚丝娜领口的红色缎带。他接着将缎带连布料一起扯了下来。血一般的缎带无声地飞舞在空中，最后落在我眼前无力地躺在地面上。

洋装的胸口部分因为被撕裂而大大敞开，可以从该处见到亚丝娜白皙的肌肤。亚丝娜的脸因为羞耻而扭曲，紧紧闭起来的眼睑边缘不断微微震动着。

须乡一面伸出右手准备触碰亚丝娜的肌肤，一面歪着头嘻嘻笑着。他的嘴唇像上弦月般上扬，接着更吐出长长的红色舌头。他的舌头上发出黏液滴落般的声音，然后由亚丝娜脸颊下方舔了上去。

「呵、呵，告诉你我现在脑袋里在想些什么吧。」

须乡依然吐着舌头，接着以疯狂的声音在亚丝娜耳边嚅嗫道：

「在这个地方好好享乐之后。我就到你的病房去，只要锁上房门、关上摄影机，那里就是密室了。就我和你两个人独处而已。然后我要在那里设置大型屏幕，一边播放今天的录像一边再度好好享受你真正的身体。首先要夺取你心灵的纯洁——接下来再玷污你身体的贞节！太有趣了，你不觉得这是很独特的经验吗！」

须乡完全发狂的尖锐哄笑充满整个黑暗空间然后慢慢消失不见。

亚丝娜虽然一瞬间睁大了双眼，但还是很坚强地紧闭着嘴巴。

只是难以压抑的恐惧还是变成两粒透明的泪水停留在她睫毛上。须乡这时竟用舌头舔了舔她的眼泪。

「啊啊……好甜、好甜啊！来，为了我再多流一点眼泪吧！」

似乎要烧尽所有一切的熊熊怒火一直线贯穿我的头部，在我眼里激起一串猛烈的火花。

「须乡……须乡……你这家伙！」

我一边狂吼一边狂乱地动着四肢并准备站起身来。但插在我胸口的剑却丝毫没有任何动摇。

我感到眼泪正从双眼里流出。这时像只虫子在地上蠕动、挣扎的我发出了咆哮。

「你这家伙……我要杀了你！杀了你！绝对要杀了你！」

须乡那疯狂的笑声在与我的怒吼重叠之后显得更加清晰。

如果现在有谁能帮助我的话——

我的两手指尖用力抓着地面，

一边尽量想让身体往前移动，一边在心里这么祈求着。

我愿意付出任何代价来换取让我现在能站起来的力量。即使是付出生命、灵魂也在所不惜。只要能让我砍倒那个男人，让亚丝娜回到应该回去的地方，无论是厉鬼还是恶魔我都愿意跟他签订契约。

这时须乡用两手摸着亚丝娜的手臂与纤足。每当他的手移动就会有邪恶的电子脉冲波强制性刺激亚丝娜的感官，但她只能死命咬着嘴唇来忍耐这种侮辱。

看见她这种模样之后，我感觉整个脑袋被完全烧焦。愤怒与绝望的火焰吞噬着我的身体，思考回路也整个变成灰烬。当它变成像骨头色干枯的块状物时，我就无法思考。也不用再思考了。

我原本认为只要有一把剑就可以做到任何事情。因为我是站在一万名剑士顶点的英雄。因为我是打倒魔王，拯救世界的勇者。

由企业根据营销理论所建构起来的假想世界，说到底也不过只是一款游戏，但我却错把它当成另一个现实世界，错认在那里面锻炼出来的能力就是真正的实力。从SAO世界里被解放——或者说是被放逐而回到现实世界之后，我不是对自己贫弱的肉体感到失望了吗？心里某个地方还想回到那个自己才是最强勇者的世界去不是吗？

所以我这笨蛋才会在知道亚丝娜灵魂被关在新的游戏世界里时，自认为可以靠自己的力量救她出来。结果放弃了求助于真正有力量的大人这个正确选项，自己不知死活地跑到游戏里面。但其实这一切只是为了再度取回幻想中的能力，超越其他玩家来满足自己那丑恶的自尊心而已吧？

所以这种结果——根本是我应该尝到的报应。是啊，我只是个因为得到某人给予的力量便欢欣鼓舞的孩子。但事实上根本连名为系统管理权的ID都无法打倒。在这里面能够轻易获得的，就只有悔恨这种感觉而已。如果不想再悔恨，那就连思考都放弃吧。

「你要逃避吗？」

——不是的，我只是认清现实而已。

「你要屈服于过去曾否定过的系统力量吗？」

——那有什么办法。我只是玩家而他是系统管理者啊。

「你这发言已经辱没了那场战斗。那埸让我得知人类的意志力能凌驾系统，让我领悟未来可能性的战斗。」

——战斗？那根本没有意义。单纯只是数字的增减而已吧？

「你应该知道不只是那样而已。来，站起来吧。站起来拿着你的剑。」

「——站起来啊，桐人！」

那道声音像雷鸣般响起，接着又像闪电般贯穿我的意志。

原本已经逐渐远去的感觉瞬间像重新联机般全回来了。我立刻用力睁开双眼。

「呜……哦……」

由喉咙深处发出沙哑的声音。

「哦……哦哦哦……」

咬紧牙根，发出像濒死野兽般的吼声后，我将右手撑在地面上并且立起手肘。

当我准备撑起身体时，贯穿背部中央的剑却还是重重压在我身上。

——怎么能这么狼狈地趴在这种东西下面呢。我绝不允许自己屈服在这种没有灵魂的攻击之下。在那个世界里承受过的所有刀刃都比它还沉重且疼痛。

「呜……咕……哦哦！」

我配合简短的咆哮，用尽身体里所有的力量让身体撑了起来。剑在发出「喀叽」的钝重声后离开了地板，并且由我背后脱落掉到地面上。

须乡先是呆呆看着摇摇晃晃站起身的我。但他马上就皱着眉头并将手从亚丝娜身上移开，用像演戏般的动作耸了耸肩膀。

「哎呀哎呀，我明明都已经固定物体的坐标了，难道是有什么Bug存在吗？营运小组那群没用的家伙……」

他一边碎碎念一边走到我眼前，举起右拳准备将我揍飞。

但我却伸出左手在空中抓住他的拳头。

「唷……？」

我一边瞧着须乡再度出现的惊讶表情，一边张开嘴巴。直接重复了一遍在脑海里响起的一连串话语。

「系统登入。ID『希兹克利夫』。密码……」

当我说完整串复杂的英文与数字之后，包围我的重力便消失了。

「什……什么？那ID是怎么回事？」

须乡露出牙齿惊讶地大喊后，甩开我的手往后飞退，并且将左手往正下方掸去。蓝色系统窗口马上就出现在他眼前。

但是在他手指有所动作之前，我已经先发出声音指令。

「系统指令，管理者权限变更。将ID『奥伯龙』变成等级1。」

须乡手底下的窗口瞬间消失了。他瞪大了眼睛，视线在空无一物的空间与我之间来回了好几次后，很不高兴地又挥了一下左手。

但什么事情都没发生。给予须乡精灵王能力的魔法滚动条已经不会再出现了。

「比……比我还高阶的ID……？怎么可能……怎么可能……我是支配者……创造者……是这个世界的帝王……神……」

这时须乡发出类似将测试音效快转好几倍的尖锐声响。我一边看着他那整个垮下来的美貌一边开口说：

「不是吧？这个世界和居民都是你偷来的。你只是在偷来的宝座上唱独角戏的盗贼国王。」

「你……你这小鬼……敢对我说这种话……你一定会后悔……看我把你的头砍下来当装饰品……」

须乡对我伸出像钩子般弯曲的食指并用尖锐的声音说：

「系统指令！生成物体ID『断钢神剑』！」

但是系统已经不再对须乡的声音有反应了。

「系统指令！这烂东西听不懂我说的话吗！这……这是神的命令啊！」

我将视线从狂吼的须乡身上移开，往被吊起来的亚丝娜看去。

这时她被须乡粗暴撕破的洋装已经变成像是盖在身上的破布一样。她除了发丝凌乱之外，脸颊上也还留着些许泪痕。但亚丝娜的眼神仍然充满光辉。她的灵魂没有因此而受挫。

——我马上就会结束这一切。再忍耐一下。

我凝视着亚丝娜深褐色的眼睛，在心里如此呢喃道。亚丝娜以细微但很确实的动作点了点头。

看见亚丝娜遭受凌虐的模样后，让我内心再次喷起一道新的怒火。我稍微抬起视线并开口说道：

「系统指令，生成物体ID『断钢神剑』。」

我眼前空间立刻产生扭曲，微小数字列以猛烈的速度流入并形成一把剑的模样。剑慢慢从尖端开始出现色泽与质感。那是一把剑身闪着金色光芒，上面还有美丽装饰的长剑。这无疑与那把被封印在幽兹海姆中心部迷宫尖端的武器完全相同。但众多玩家梦寐以求的最强之剑，却只要一个指令就能够出现，这让我有种无法言喻的不快感。

我抓起剑柄，将它丢给瞪大眼睛的须乡。看见他以笨拙的动作接住剑之后，我便轻轻抬起左脚。

往地板上爱剑的剑柄用力一踩之后，剑立刻随着声响一边旋转一边垂直飞了上来。我接着便用右手对准带着暗沉钢铁光芒的剑柄横扫过去。一阵沉重的声音过后，剑已经握在我的手里了。

将朴质的黑铁色大剑对准须乡之后，我开口说道：

「该是盗贼之王与镀金勇者一决胜负的时刻了……系统指令，将疼痛缓和装置降到0级。」

「什……什么……？」

听见将假想痛楚界限完全解除的指令后，拿着黄金之剑的精灵王脸上出现了动摇的表情。他开始往后退了一两步。

「别想逃。那个男人——茅场晶彦在面对任何场面时可都是绝不退缩的啊！」

「茅……茅场……」

一听见这个名字，须乡的脸马上就整个扭由了起来。

「茅场……希兹克利夫……是你吗？又是你在妨碍我吗！」

须乡将右手的剑高举起来，用异常尖锐的声音大喊着：

「你已经死了吧！尸骨无存了吧！那为什么连死了都要阻碍我！你总是这样……老是喜欢与我做对！脸上一直都挂着那种一切都了然于心的表情……然后从旁夺走所有我想要的事物！」

他忽然用剑对我刺来，然后嘴里又叫道：

「像你这种小鬼……又知道些什么！你能了解……在那家伙底下工作、跟那家伙竞争有多痛苦吗？」

「我知道。因为我也输给那个男人并且变成他的手下。但我和你不同我从没想过要取代他。」

「小鬼……你这小鬼……死小鬼啊啊啊啊！」

须乡随着沙哑的悲鸣向前冲过来并对我挥下手里的剑。当他来到剑的攻击范围里面时，我用右手上的剑轻轻横向一扫，剑尖便稍微划过精灵王光滑的脸颊。

「好烫！」

须乡高声叫着并且用左手按住脸颊，最后整个人向后飞退。

「咿……啊啊啊……！」

他瞪大眼睛发出悲鸣的身影让我更加怒火中烧。一想到亚丝娜被这种男人关住，还让他虐待了两个月，我就再也压抑不住自己的愤怒。

我用力踏出一步，将剑由正面砍下。须乡反射性抬起来的右手被我一击砍断，黄金剑连着手腕一起高高飞向深黑色的远方并就此消失不见。不久后远处传来清澈的物体落地声。

「啊啊啊啊啊啊啊啊！手……我的手啊啊啊啊啊啊！」

虽然只是仿真的电子讯号，但现在彷若真实的痛楚感应该正袭击着须乡吧。不过我当然不可能这样就饶过他。这只是一点小惩罚而已。

须乡这时抱着右手发出了呻吟，但我又用力往他那穿着绿色长袍的身体横砍了下去。

「咕哇啊啊啊啊！」

他浓纤合度的身体被我从腹部切成两段后，掉在地面上发出沉重的声音。他的下半身马上就被白色火焰包围并且变成灰烬。

我用左手抓起须乡满头的金发然后把他拉了起来。他那瞪到不能再大的眼睛里流着眼泪，嘴巴一边开合一边持续发出须乡那种金属般的尖锐悲鸣。

但他这种模样只会让我感到异常厌恶。我一挥左手便将须乡的上半身垂直丢了上去。我两手握住大剑，一个转身摆出准备突刺的姿势。接着便朝着边发出刺耳悲鸣边落下来的物体——

「……呜哦！」

全力将剑刺了出去。「喀嗞」一声后，剑身直接由须乡右眼处深深刺入并且贯穿他整个脑袋。

「叽啊啊啊啊啊啊啊！」

像是好几千颗生锈齿轮同时转动的刺耳悲鸣声响彻了整个黑暗世界。须乡被剑分割成左右两边的右眼里喷出浓稠白色火焰，而火焰一下子便由头部扩散到整个上半身。在完全溶解、烧尽前的几秒钟里，须乡一直持续吼叫着。最后那道声音逐渐远去，然后彻底消失。当世界完全回归平静时，我左右挥动手里的剑将白色残存之火吹散。

用剑轻轻扫过之后，禁锢亚丝娜的两条锁链便完全断裂并消失无踪。我把任务结束的剑往地板上一扔后马上就抱起全身无力的亚丝娜。

这时支撑着我的能源也同时用尽，我当场跪了下来，凝视着怀里的亚丝娜。

「……呜……」

无可宣泄的感情洪流变成泪水由我眼里溢出。我抱紧亚丝娜娇小的身体，将脸埋在她的发丝里后开始哭泣。我说不出任何话来，只是任由自己不断流着眼泪。

「我相信你会来的——」

亚丝娜透明的声音在我耳边响起。

「……嗯嗯，一直以来我都相信你……今后也是一样。你是我的英雄……无论什么时候都会来救我……」

她说完后用手静静抚摸我的头发。

——不是的。我……我真的没有任何能力……

但我在用力吸了口气之后，还是用颤抖的声音这么说道：

「……我会努力达成你的期望。来……我们回去吧……」

我一挥动左手，马上就出现跟平常不同的复杂系统窗口。直觉性地掠过数个阶层并移动视窗，直到显示转送相关的选单才停下指头。

我凝视着亚丝娜的眼睛，开口对她说：

「现实世界里应该是晚上了。但我马上就会到你的病房去。」

「嗯，我等你。我想醒过来见到的第一个人就是桐人。」

亚丝娜轻轻微笑着。她用清澈如泉水般的视线看着远处，接着开口说道：

「啊啊……终于要结束了。我要回到那个世界去了……」

「是啊。外面世界变化很大，一定会让你吓一大跳的。」

「呵呵。我们要一起到各地去玩，然后还要一起经历各种事情唷！」

「嗯嗯。那是当然——」

我用力点了点头并用力抱了一下亚丝娜，然后才移动自己的右手碰了一下登出按钮。最后用目标待机状态下发出蓝光的之间轻拭去亚丝娜脸颊上的泪水。

这时亚丝娜洁白的身体被一片鲜艳蓝光给包围住。接着一点一点像水晶般变得透明。最后光之粒子在空中飞舞，她也从脚尖、指尖开始消失。

我用力抱着亚丝娜，直到她完全从这个世界里消失为止。当手臂当中的重量感终于完全消失时，我便一个人被留在黑暗当中。

我就保持着这样的姿势在黑暗里蹲了好一阵子。

虽然所有的事情似乎都已经结束，但又有种某件重大事件仍未完结的不确定感。由茅场的梦想与须乡的欲望所引起的事件——真的就此结束了吗？还是说这还只是巨大变革的一部分而已？

我鞭策着自己耗尽能源的身体，好不容易才站起身来。看着头上被一片黑暗包围住的世界深处，开口说了句：

「你在这里对吧——希兹克利夫……」

经过一阵子寂静之后，那道刚才在我意识中响起的厚重声音再度出现。

「久违了，桐人。虽然对我来说那个日子似乎是昨天才发生过一般。」

这道声音与刚才不同，感觉上似乎是由某个遥远的地方传过来。

「——你还活着吗？」

简短问完后，对方沉默了一阵子才回答道：

「可以这么说，但也不能这么说。我只是茅场晶彦这个意识的回音与残影。」

「你这人还是喜欢说些难懂的事。总之我要先向你道谢不过反正都要救了，你怎么就不早一点行动呢？」

「…………」

感觉得出对方正在苦笑。

「那真是抱歉了。这个分散保存在系统里的程序是在刚刚也就是听见你的声音时才完成结合·觉醒的。而且你根本不用向我道谢。」

「……为什么？」

「我们两人的交情还没好到让我完全不求回报吧。当然我一定会向你收取代价的。」

这次则换成我露出苦笑。

「那你要我做什么？」

结果从遥远的黑暗当中——落下某样银色的物体。我伸出自己的手，接着该物体便在发出轻微声响后落进我的手里。那是颗小小的蛋型结晶体。内部还有微弱光芒闪烁着。

「这是？」

「那是世界的种子。」

「——什么？」

「等它发芽之后，你便会知道它是什么东西。接着该怎么做就交给你来判断了。要把它删除并加以遗忘也无所谓……但是如果你对那个世界还存有憎恨以外的感情——」

这时声音中断了。经过短暂沉默后，只有一道冷淡的告别降了下来。

「——那么我要走了。有机会再见吧，桐人……」

接着他的气息便忽然消失了。

我虽然觉得奇怪，但还是先把发光的蛋型结晶收进胸前口袋。思考了一阵子后，忽然抬起脸来叫着：

「——结衣，你在吗？你不要紧吧？」

我才刚开口，黑暗世界便开了一道裂缝。

由裂缝外射进来的橘色光线撕裂整个黑暗空间，同一时间还有风吹起，在不知不觉间黑暗消失了。过于刺眼的光线让我瞬间闭上眼睛，慢慢张开后才发现自己依然还是在鸟笼里。

正前方马上就要下沉的巨大夕阳散发出最后的光芒。但我只听见风声而没看见任何人影。

「——结衣？」

又叫了一声之后，眼前的空间出现浓缩的光芒，接着砰一声黑发少女现身了。

「爸爸！」

她叫了一声之后扑了过来紧紧抱住我的脖子。

「你没事吗。那真是太好了……」

「嗯……由于所在位置突然被锁定，所以我便躲到NERvGear的私人用记忆体里面去了。但我再度联机回来时，爸爸和妈妈都已经不在了……我真的好担心。妈妈她呢……？」

「嗯嗯，她回现实世界去了……」

「这样啊……那真是太好了……」

结衣闭上眼睛，把脸颊放在我胸前来回摩擦着。她的脸上露出些微寂寞的表情，我默默地摸着她的长发。

「我们马上就会再见面的。不过……这个世界之后不知道会怎么样……」

我低声说完后，结衣便笑着对我说：

「我的主程序不在这里，而是在爸爸的NERvGear里面。我会一直和爸爸在一起。咦——但有点奇怪耶……」

「怎么了吗？」

「好像有一个很大的档案被传送到NERvGear的储存器里面了。看来不是会主动发挥效用的程序就是了……」

「这样啊……」

我虽然觉得奇怪，但还是先把这个疑问抛到脑后。因为现在还有更重要的事情等着我去做。

「——那我也要登出去接妈妈了。」

「好的。爸爸——我最喜欢你了。」

结衣眼里含着泪水，说完之后用力抱紧我。我一边摸着她的头，一边挥动右手。

我停下准备要按下登出键的手指，再度眺望着这整片染上夕阳颜色的世界。这个被冒牌国王所治理的世界今后究竟会变成什么样子呢。一想到深爱着这个世界的莉法以及其他玩家，我的胸口便感到一阵刺痛。

轻吻了一下结衣的脸颊之后，我用力按下登出键。呈放射状的光芒在眼前扩散并包围我的意识，接着将我带往高处的天际。

边感觉脑袋深处浮现的那股疲劳感边睁开眼睛后，我随即看见直叶的脸出现在眼前。她一脸担心地凝视着我，但眼神与我相对之后便急忙撑起身体来。

「抱、抱歉，随便跑进你的房间。因为你这么久都没醒过来，我是担心才……」

直叶坐在床沿，脸颊微红地这么说道。从时差所造成的迟钝当中恢复过来后，我在四肢上灌注力道，接着用力撑起上半身。

「抱歉，回来得太晚了。」

「……全部结束了吗？」

「——嗯嗯。一切都结束了……」

我一边看着空中一边如此回答。至于差点再度成为假想世界的俘虏，而且这次将被关进没有完全攻略事件的牢狱当中这件事，我实在没办法对直叶开口。虽然总有一天会全部告诉她，但目前我不想再让她担心了。我这唯一的妹妹已经帮了我太多的忙，实在不知道该怎么感谢她才好。

自从在深夜的森林里遇见那名绿色头发的女孩，我的新冒险便开始了——漫长的旅途当中都是她陪在我的身边。她不但替我带路、告诉我游戏里的种种情报，还以她的剑守护着我。而且全是靠她的介绍我才能认识两位领主，如果最后不是那群知己帮忙，我一定不可能突破那些守护骑士的防御。

回想起来，我真是受到了许多人的帮助。而最先帮助我的，当然就是眼前这名少女了。身为桐人时有莉法，变回和人时又有直叶帮助、支持着我，但在这段期间内她小小的肩膀上却背负着深刻的烦恼——

我再度凝视着直叶那同时有着男孩子般耀眼活力与刚发芽嫩叶般脆弱的脸庞。直叶这时有些不好意思的笑了起来，我则伸出手一边静静抚摸着她的头一边说：

「真的——真的很感谢你，小直。如果没有你，我就什么都办不到了。」

直叶满脸通红地低下头去，扭扭捏捏了一阵子之后才像下定决心般往前走了几步，将她的脸颊靠在我胸前。

「别这么说……我真的很高兴能够在哥哥的世界里帮上哥哥的忙。」

直叶闭着眼睛如此低声说道。这时我将右手绕到她身后，接着轻轻抱了她一下。

松开手之后直叶便抬头看着我说：

「那……你已经救回亚丝娜小姐了吧……」

「嗯嗯。她终于——终于回到这个世界来了。小直……我……」

「嗯，你快过去吧，她一定也在等着哥哥。」

「抱歉。详细情形等我回来再跟你说。」

我将手砰一声放在直叶头上接着站起身来。

我以破纪录的速度做好准备，抓起羽毛外套站在走廊上后，发现外面已经完全暗下来了。客厅那颇有历史的壁钟显示还差一点就要九点。虽然医院的会客时间早已经结束，但现在是紧急状况。我想只要向护士站里值班的护士说明清楚，她们应该会让我进去才对。

这时候直叶急忙跑了过来，说了句「这是我做的」后便塞了一份厚厚的三明治在我手里。怀着感谢的心情接下来后将它咬在嘴里后，我拉开玻璃门便来到庭院。

「好、好冷……」

直叶因为透过外套的冷空气而缩起脖子，接着抬头看着天空说：

「啊……下雪了……」

「咦……」

确实正有两、三片巨大雪片带着白色光辉飘了下来。虽然一瞬间考虑要叫出租车，但一想到除了要叫车之外还得走到干线道路去等车子过来，就觉得直接骑脚踏车冲过去应该会比较快些。

「骑车小心哦。帮我向亚丝娜小姐打声招呼……」

「嗯嗯。下次一定介绍你和她认识。」

我对直叶挥了挥手后跨上登山脚踏车，直接踩起踏板。

自行车以几乎让脑袋变成一片空白的速度向前奔驰，开始横越整个埼玉县南部。虽然雪越下越大，但路面还不至于有积雪，而且交通流量因此减少反而让我觉得相当幸运。

虽然想尽快到达亚丝娜的病房——但另一方面自己也害怕再度去到那个地方。这两个月以来，当我每隔一天到那个房间去时，就会有一种非常、非常失望的感觉。在病房当中沉睡的亚丝娜，让人十分担心她会不会就此变成冰冷的雕像。但即使如此我也还是握着她的手，就算知道她听不见也仍然不断呼唤着她。

当我再度奔驰在这条已经连何处有凹陷都一清二楚的路面上时，忽然感觉在精灵国度发现亚丝娜、打倒冒牌国王并将她解救出来等等全都只是自己的幻觉。

如果我在几分钟后到达病房，而亚丝娜并没有醒过来的话……

她的灵魂已经不在阿尔普海姆里，但也没回到现实世界来——再度消失在不知名场所的话……

这时一股强烈的冷冽穿透我的背部，但我知道这不是因为暗夜中打在脸上的雪片所造成。不，不会这样的。控制着这个现实世界的系统应该不至于会如此残酷才对。

我就这么抱持着复杂的思绪不断踩着踏板。在宽敞的干线道路右转后，开始进入丘陵地带。胎面上有高隆起颗粒的登山车轮胎跑与蒙上一层冰沙状薄雪的柏油路面互相咬合，接着向后转去，让车体的速度更为加快。

不久后前方终于出现巨大建筑物的黑影。该建筑物里几乎见不到灯光，只有屋顶上直升机停机场前的蓝色诱导灯像点缀暗黑之城的鬼火般闪烁着。

爬上最后的坡道后，眼前可以见到高高的铁栅栏。沿着栅栏又骑了数十秒钟，两旁由高大门柱所守卫的正面大门便出现在我眼前。

由于这里是不接收急诊的高级医疗专门机构，所以这个时间早已是大门紧闭，连警卫室里也没有任何人了。我经过大门直接来到休息区之后，利用开放给职员使用的小门进到医院腹地里。

在停车场角落停下自行车，懒得上锁的我便直接跑了起来。在水晶盐灯朦胧的橘色灯光照耀下，停车场里见不到任何人影。这里只有大片雪花无声地由天空落下，将整片世界染成白色。我一边跑一边随着急促的呼吸吐出一大片水蒸气。

当我跑过这个宽广的停车场一半，准备穿过一台高大的箱型车与白色房车之间时……从箱型车后面迅速冲出来的人影差点就跟我撞在一起。

「啊……」

一边道歉一边准备闪躲的我，眼里忽然看见——

一道刺眼的金属光辉闪过我面前。

「————！」

接着我的右腕，手肘稍微下面一点的地方马上产生一股刺痛的热辣感，同时也有大量白色物体飞散。但那些白色物体不是雪花，而是细微的羽毛。是我羽毛外套里面的保暖材料。

一个踉跄之后，原本已经快撞上白色房车后车箱的我好不容易才又站稳脚步。

直到目前为止我都还无法了解究竟发生什么事，只能哑然凝视着站在离我两公尺远左右的黑色人影。那是一名穿着近似黑色西装的男性。他右手里还拿着某样细长的白色物体。而白色物体在受到橘色光线照射之后发出了厚重的光芒。

那是一把刀。一把大型的蓝波刀。但为什么这种东西会出现在这里呢。

我感觉到在箱型车阴影之下的男人正凝视着我冻僵的脸。男人开始牵动嘴角，接着马上有一道类似呢喃的沙哑声音响起。

「太慢了吧，桐人小弟。我要是感冒了怎么办。」

这声音是……这种尖锐又浓稠的声音是……

「须……须乡……」

男人在我呆呆叫出这个名字的同时也向前走了一步。水晶盐灯放射出来的光线照出他的脸庞。

他几天前见面时还整理得相当整齐的头发现在是一片零乱。尖锐的下巴上长着胡渣，几乎完全解开的领带只是单纯地挂在脖子上而已。

另外——金属框眼镜下方的异样视线正紧盯着我看。但我马上就知道他的视线之所以会那么奇怪的理由了。他原本细小的眼睛这时撑大到极限，在暗夜当中扩散的左边瞳孔虽然稍微在震动，但右侧瞳孔却完全处于缩小状态。而那正是我在世界树上贯穿他头部的地方。

「你还真是残忍啊，桐人小弟。」

须乡以沙哑的声音说道。

「疼痛感到现在还没消失呢。不过这有很多特效药，所以没关系……」

他将右手伸进西装口袋，抓出几颗胶囊之后丢进嘴里。须乡一边发出咀嚼的声音一边又往前走了一步。我好不容易才从冲击当中恢复过来，拼命动着干枯的嘴唇说：

「——须乡，你已经完了。你以为你能湮灭那么庞大的证据吗？你就乖乖接受法律的制裁吧。」

「完了？什么完了？我可还没玩完啊。不过RECT已经不能再待下去了。我会到美国去的，那里可是有一大票企业想雇用我呢。我手里还有至今为止累积起来的庞大实验档案。只要使用那些档案让研究完成，我就能成为真正的王、真正的神我将在现实世界里成为神。」

——这人已经疯了。不对，应该说这男人从很早以前就坏掉了。

「不过在那之前还有几件事情得先完成。我就先从把你杀掉这件事开始吧，桐人小弟。」

须乡表情毫无变化地碎碎念完之后，马上又快步向我靠近。他右手上的蓝波刀直接对准我腹部刺了过来。

「……！」

我为了躲开他的攻击而用右脚在柏油路上一踢。但可能是鞋底上雪花的缘故吧，我因此而滑了一大跤并失去平衡，整个人跌倒在停车场的地面上。当身体左侧猛烈撞击地面的同时，我整个人也无法呼吸。

须乡将失去焦点的瞳孔朝下看着我。

「喂，站起来啊！」

须乡接着便用力朝我踹了下去。他那看来很昂贵的皮鞋尖端直接深陷入我的大腿。被踢了两、三下之后，一股灼热疼痛感闪过我的脊髓直达头部。接着冲击也传达到右手腕，一股强烈的刺痛感油然生起。这时候我才注意到被切开的不只是夹克，我的手腕也受伤了。

倒在地上的我根本无法动弹。而且也发不出任何声音。须乡手里的蓝波刀——刀刃应该超越二十公分长吧，那把为了杀害人而存在的道具散发出沉重压力，让我整个人都僵住了。

他要用——那把刀——杀了我——？

片段性的思考闪过脑部接着消失。厚厚的刀刃无声地侵入我的身体，然后给予我致命性——也就是夺走生命力的伤害。我除了不断想象着那个瞬间之外就没办法做任何事情了。

右腕上的疼痛变成麻痹般的热辣感。此时由外套的袖口以及冬用手套的隙缝里流出几滴黑色液体。感觉血液似乎正永无止尽地由我体内流出。这一刻死亡不再是由HP条上的数值来表示，而是以最真实的模样呈现在我面前。

「来，站起来。快站起来啊。」

须乡以机械式动作重复又踢又踹了我的脚好几次。

「你这家伙在那个世界里面是怎么对我说的。别想逃？别像个胆小鬼？要决一胜负？你就是那么不可一世地对我说的对吧？」

这时须乡的说话声与在那个黑暗空间里一样都带有疯狂的色彩。

「你到底懂不懂啊？像你这种只会玩游戏的小鬼其实一点用都没有。根本可以说是劣等垃圾。竟然还敢跑来扯我的后腿……所以你应当以死来对我谢罪。除了死亡之外就没有别的下场了。」

以毫无抑扬顿挫的声音碎碎念完之后，须乡便把左脚放在我腹部上，接着把重心往下移。这种物理上的重压与他所散发出来的疯狂压力让我感到窒息。

我不断重复着短浅又急促的呼吸，然后看着须乡不断靠近的脸孔。弯下身体的须乡高举起右手里的凶器。

他毫不犹豫地就把刀刺了下来。

「呜————」

当我由喉咙里露出类似痉挛的声音时——

蓝波刀尖端也同时随着钝重的金属声擦过我脸颊并深深刺入柏油路面里。

「咦……右眼还有点模糊所以瞄不太准啊！」

须乡嘴里这么念着，接着再度高举起右手。

水晶盐灯的照明滑过刀子尖端，在黑暗当中画出一道橘色轨迹。

可能是刚才插进坚硬的路面里吧，刀子切面前端出现了一点点缺口。但这样的瑕疵更让人强烈感觉到这把刀子无论是在现实或物理上都是货真价实的凶器。它不是由多边形所组成，而是由紧密的金属分子浓缩而成。它沉重、冰冷，且带有真正的杀伤力。

黑色天空中飞舞的雪片、由须乡扭曲的嘴里吐出来的白色气息、对我降下来的刀子、在刀背锯齿状凹陷上一边闪烁一边移动的橘色反射光，这一切事物似乎都放慢了动作。

话说回来，我好像看过这种锯齿状的武器啊……

几乎已经停止的思考表层这时流过无意义的记忆片段。

那是什么呢。对了，是在艾恩葛朗特中层街上贩卖的短刀系道具。它的名字应该是叫做「长剑破坏者」吧。只要利用它刀背上锯齿状部分来防御敌人的剑，就会有很低的机率能破坏敌人的武器。由于我觉得很有趣，所以就把短剑技能放进技能格子里用了一阵子，但因为基本攻击力实在太低而没办法获得理想的战果。

现在须乡手里握着的武器比它还要更小。甚至连短刀都称不上。不——这种东西甚至进不了武器的范畴。它只是日常生活中使用的道具而已。根本不是剑士拿来战斗用的武器。

耳朵深处又响起须乡数秒前说过的话。

你根本一点用都没有——

他说的完全正确……不用他讲我也很清楚。但这么一来准备杀掉我的你又算什么呢，须乡。你是刀术达人吗？还是精通于武术呢？

我凝视须乡眼镜深处那对充血的小眼睛，里面除了兴奋与疯狂之外就没有任何感情。那是双胆小鬼的眼睛。在迷宫里被大量怪物围住，陷入九死一生的危机时，为了逃避现实而狂暴挥着剑的人就有这种眼神。

这家伙也跟我一样。一直想要得到力量，但因为无法如愿以偿而不断狼狈的挣扎着。

「……去死吧，小鬼！」

须乡的吼叫声将我的意识由减速世界里拉了回来。

我的左手像是被吸过去般往上抬，直接抓住了须乡挥下来的右手手腕。我同时伸出右手，用大拇指戳进须乡松开的领带与喉咙凹陷处之间。

「咕呜！」

一道东西被压扁的声音响起，接着须乡便整个人向后仰去。我转过身体，用两手抓住须乡的右腕，然后全力将他的手朝结冻的柏油路面擦了下去。他的手随着悲鸣而松开，刀子跟着也掉到路面上。

须乡一边发出宛若笛子般尖锐且沙哑的怒吼，一边准备朝刀子飞扑过去。我弯曲右脚，用鞋底直接往他下颚踢去。接着更一把抓起刀子，利用反作用力站了起来。

「须乡……」

由喉咙里流泄出连我自己也意想不到的破碎声音。

我透过右手的手套，感觉蓝波刀又硬又冷的存在感。它作为武器来说实在太过于单薄了。除了重量不足之外，攻击范围也相当短。

「但是用来杀你已经是绰绰有余了。」

低声说完后，我便猛然朝坐在地上呆呆看着我的须乡扑了过去。

左手一把抓起他的头发，将他的头推倒在箱型车车门上。铝制车身随着沉重声响出现了凹陷，须乡的眼镜也整个飞了出去。这时他张大了嘴巴说不出话来。而我则朝着他的喉咙奋力举起右手上的刀子——

「咕呜……呜呜……」

但我就此停止手腕的动作，用力咬紧牙关忍耐着。

「咿咿咿！咿～～！咿～～！」

须乡再度发出数十分钟前曾在那个世界里叫喊过的尖锐悲鸣。

这男人根本死不足惜。他本来就应该接受制裁。只要我现在挥下右手，就能够确实结束一切。决定真正的胜利者与失败者。

但是——

我已经不是剑士了。靠剑技来决定一切的那个世界早已随风远去。

「咿咿咿咿咿咿咿……」

须乡忽然翻起白眼。他的悲鸣就此中断，全身像失去电力的机械般摊成一团。

而我的手也在这时候失去了力量。蓝波刀从我手上滑落到须乡肚子上。

放开左手后我撑起了身体。

再继续看着这个男人的话，我内心的杀意将会再度沸腾，而我这次将再也无法抑制自己。

我拉起须乡的领带，把他的身体滚到路面，将其双手绕到身后然后绑住。至于蓝波刀则是一把抛到箱型车车顶。完成这些事后我才努力将摇晃的身体向后转去，拖着脚一步一步在停车场里走了起来。

光是爬上宽广的阶梯来到正面入口就花了我五分钟的时间。我停下来深深吸了一口气，低头看着总算比较听话的身体。

只见我身上沾满了雪与泥土，看起来真可以说是相当狼狈。被刀子割伤的右腕与脸颊虽然疼痛，但是血似乎已经止住了。

我虽然已经站在自动门前，但门却没有要打开的样子。透过玻璃往里面看去，发现主大厅的灯光已经关上，但更里面的柜台还有灯亮着。看了一下周围环境后，我发现左手边深处有一扇旋转门，幸好一推之下门就打开了。

建筑物里是一片寂静。宽敞的大厅里相当整齐的横排着许多板凳。

柜台里面虽然没有人，但从深处的护士站里有谈笑声传了出来。我一边祈祷自己能好好发出声音一边开口说：

「那个……有人在吗！」

我说完话的数秒钟后，护士站的门打了开来，并有两名穿着淡绿色制服的女性护士出现。两人脸上原本带着怀疑的表情，但在见到我的模样后马上就变成一脸惊讶。

「——发生什么事了吗？」

身材较高，把头发整个盘起来的年轻护士高声问道。看来我脸颊的出血比想象中还来的严重。我用手指着入口方向然后说：

「我在停车场被一名拿着刀子的男性袭击了。他目前昏倒在白色箱型车后面。」

两人脸上出现紧张的神情。年纪较大的护士操纵柜台内侧的机械，接着将小麦克风拉近脸部。

「警卫先生请马上到一楼护士站来。」

正在巡逻的警卫似乎就在附近，马上就有一名穿着深蓝色制服的男性随着脚步声跑了过来。听完护士小姐的说明之后，警卫脸上也出现严肃的表情。他对着小型对讲机交代了一些事情，然后便朝着入口走去。年轻的护士则是跟在他后面一起离开。

留下来的护士仔细检查过我脸颊的伤口后才对我说：

「你是十二楼结城小姐的家人吧？只有这里受伤而已吗？」

虽然与事实有些不符，但我已经没有订正的力气，于是便点了点头。

「这样啊。我马上请医生过来，你在这里等一下。」

说才刚说完她便跑走了。

我大大呼了一口气，开始看起周围环境。确认过附近没有任何人之后，我探身到柜台里面，从里头抓起一张访客用通行证。我拼命用颤抖的双脚朝着护士离开的相反方向，也就是我已经来过许多次的住院病房通道走去。

电梯刚好就停在一楼。按下按钮后，电梯门随着低沉铃声打了开来。我将身体靠在电梯内部的墙上，按下最上层的按钮。虽然医院电梯上升速度已经算是缓慢，但仅是这样的负荷就足以让我膝盖快要跪下去。我只有死命撑着自己的身体。

在我几乎要失去意识的几秒钟后，电梯终于停止并打开门，我连滚带爬地来到通道上。

距离亚丝娜病房的短短几十公尺距离，对我来说就有如无限般地遥远。我将手放在墙上的扶手好支撑住快要倒下的身体，然后就这样慢慢往前进。在L字型通道往左转后——那一扇白色的门终于出现在我眼前。

我一步一步慢慢向前走。

那个时候也像现在一样——

被包围在夕阳里的假想世界结束之后我回到了现实世界，在另外一间医院里醒过来的那一天，我也是这样拖着萎缩的双脚，奋力走着。为了寻找亚丝娜而不断向前走着。当时那条通道一定就是连接到这里。

我终于能见到她了。这一刻终于来临了。

随着距离越来越短，充塞在我心里的各种感情也剧烈地高扬了起来。除了呼吸急促之外，视线也开始逐渐模糊。但我不能在这里倒下。我为了继续前进而不断迈出脚步。

没注意到自己已经来到门前，在几乎快要撞上门时才赶紧停下脚步。

心里只有一个想法。那就是——亚丝娜就在这道门后面。

当我抬起颤抖的右手时，因为汗水而让手上的通行证滑落到地面上。将证件捡起来后，这次终于确实把它插进金属门牌上的隙缝里。我暂停呼吸，一口气将卡片往旁边滑去。

显示灯的颜色改变，门随着马达声打了开来。

里面马上流出一股花香。

病房里没有点灯。雪地反射出来的光线由窗外照了进来，让房里稍微有了一些白光。

我无法动弹。已经没办法再前进，也没办法发出任何声音了。

此时耳边忽然出现了一道呢喃声。

「来——她在等你啊……」

接着感觉有手轻轻推了一下我的肩膀。

结衣？直叶？总之是在这三个世界里，某个帮助过我的人所发出来的声音。我将右脚往前移动。又往前走了一步再一步。

我在帘子前停下来。伸手抓住布帘边缘。

接着用力拉开。

白色布幕随着吹过草原的微风声音摇晃并滑向旁边。

「啊啊……」

从我喉咙里流出简短的声音。

一名背对着我，身穿纯白色洋装般单薄病服的少女正坐在床上看着黑暗的窗口。飞散的白雪在她那光滑的秀发上反射出些微亮光。少女纤细的双手放在身体前面，手里还拿着一个深蓝色的蛋型物体。

那是NERvGear。持续禁锢着少女的荆棘王冠。但它现在已经结束任务，静静躺在少女的怀里。

「亚丝娜……」

我以极细微的声音叫着她的名字。少女的身体猛烈震动了一下让充满花香的空气产生晃动后转过身过来。

刚从漫长缍眠里醒过来，还带着梦境般光辉的褐色瞳孔笔直地凝视着我。

我不知已经梦想过多少次、祈祷过多少次遭个瞬间的到来。

她那粉红色光滑的嘴唇淡淡地微笑了一下。

「桐人……」

这是我第一次听见她的声音。与在那个世界里每天听见的声音完全不同。但是在空气中震动，在我听觉器官里产生共鸣而传达到意识里的声音，可以说比在游戏里悦耳了好几倍。

亚丝娜左手离开NERvGear对我伸了过来。光是这个动作就花了她不少力气吧，我看见她的手正在颤抖着。

我像触摸冰雕般静静地握住她的手。她的手是如此的虚弱纤细，但却相当温暖。彷佛可以愈合任何伤口般的暖流，由她的手中缓缓传递过来。此时我的双脚忽然失去力量，我只好将身体靠在床的边缘。

亚丝娜伸出右手，缓缓摸着我受伤的右颊，像是要发问般歪着头。

「啊……真正的最后决斗，刚才已经结束了。结束了……」

这么说的同时，眼泪终于从我双眼夺眶而出。顺着脸颊来到亚丝娜手指上的泪水，在窗外光线的照射下闪烁着光芒。

「……抱歉，我还听不太清楚。但是……我知道桐人你在说什么。」

亚丝娜像是要慰劳我的辛苦般一边摸着我的脸颊一边呢喃着。光是听见她的声音，我的灵魂就不断颤抖着。

「一切都结束了……我终于……终于……见到你了。」

此时亚丝娜的脸颊上也滑下了银色的泪珠。她湿润的双眼像是要传达内心所有想法般直盯着我，接着她又开口说道：

「初次见面，我是结城明日奈。我回来了——桐人。」

我也忍住呜咽回答：

「我是桐谷和人。欢迎回来……亚丝娜……」

两人的脸同时靠近，嘴唇先是轻轻相交，接着才又深深地吻在一起。

我将双臂绕过她娇小的身体，接着静静地紧抱住了她。

两人的灵魂开始一趟旅程。由现实世界到假想世界。再由今世前往来生。

接着两人的灵魂更接受了彼此。坚定地呼唤着对方的姓名。

从前在一座浮在天空中的大城堡里，一位梦想成为剑士的少年遇见了一名很会做菜的少女，两个人坠入了情海。他们虽然已经不存在了，但他们的心在经过漫长旅途之后终于再度相遇。

这时我一边轻抚着亚丝娜因为哭泣而震动的背部，一边将因眼泪而模糊的视线看向窗外。我似乎看见了两个紧靠在一起的人影站在越下越大的雪中。

一个是身穿黑色大衣，背上背着两把剑的少年。

另一个则是腰间吊着银制细剑，身穿红白骑士服的少女。

两个人脸上带着微笑牵着手，转过身子之后慢慢远去。

** 第九章

「那我们今天就上到这里。我会传送回家作业档25和26给你们，记得下周末前要上传过来。」

模拟大钟的铃声宣告上午课程已经结束，当老师将大型面板荧幕的电源关上之后，教室中开始飘荡着一股慵懒气氛。

我操纵着插在电脑上的旧式鼠标，打开下载结束的回家作业档案后瞄了一眼内容。我对着看来相当令人伤脑筋的一长串问题叹了口气，然后拔下鼠标、关上平板电脑并将它们一起放进背包里。

话说回来，这里的铃声与艾恩葛朗特第一层·「起始之城镇」里的教堂钟声实在很相似。如果这栋校舍的设计者是故意这么设定的话，那他黑色幽默的品味可以说相当令人佩服。

不过穿着同样制服的学生们似乎没有注意到这件事就是了。他们和谐地一边谈笑，一边三三两两的离开教室往食堂走去。

拉上背包的拉链，将它背到肩上准备站起身来时，旁边位子上跟我感情不错的男学生抬头看着我说道：

「啊，小和，要去食堂的话记得帮我抢个位子。」

在我回答他之前，坐在更旁边位子上的学生便笑着对他说：

「别问小和啦，今天是他和『公主』见面的日子吧。」

「啊，对哦。可恶，真令人羡慕。」

「嗯，就是这么一回事。所以抱歉啦……」

我决定在这群家伙开始调侃我之前赶紧离开，于是举起手打了声招呼后便迅速走出教室。

快步走过贴着暗绿色面板的走廊，接着由逃生门来到中庭之后，好不容易从吵闹午休时间当中解脱的我才松了一口气。眼前这条铺着崭新炼瓦的小径在刚发芽的树木之间一路往前延伸。虽然在树梢上方可以见到校舍水泥整个外露的粗糙外表，但整体来说这座美丽的校园实在让人看不出这里原本是已经废校的旧校区。

持续在穿越绿色隧道的小径上走了几分钟后，我来到一座圆形的小庭园。庭园里的花圃外围均衡设置了几张白木板凳，而一名女学生正坐在其中一张板凳上抬头看着天空。

少女那一头栗色长发笔直地垂在以深绿色为基调的制服外套后面。她的肌肤白净剔透，但最近脸颊上终于逐渐出现有如玫瑰般的血色。

女孩专心看着蓝色天空并且将穿着黑色长袜的纤足往前伸直，接着以平底船形鞋的脚尖部份不停敲着炼瓦。由于少女这副模样实在十分惹人怜爱，于是我便把手放在树干上，站在庭园入口一直默默地凝视着少女。

结果她突然转过身来，一见到我之后脸上随即露出笑容。但立刻又装出不在乎的表情闭起眼睛，然后哼一声把头别到一边去。

我一边苦笑一边接近板凳，开口对她说：

「让你久等了，明日奈。」

明日奈瞄了我一眼之后便噘着嘴说道：

「真是，为什么桐人你老喜欢躲在暗处偷看人家啊？」

「抱歉抱歉。嗯——说不定我有成为偷窥狂的资质呢……」

「恶——……」

在露出厌恶表情并往后缩的明日奈身边坐下来后，我大大地伸了个懒腰。

「啊啊……又饿又累……」

「桐人你怎么像个老头一样啊……」

「老实说这一个月里感觉就像老了五岁一样……还有——」

我将手放在脑袋后面，侧眼看着身边的明日奈。

「应该叫我和人而不是桐人才对吧。在这里叫人角色名称算是违反校规唷。」

「啊，对哦。不小心就……但那我要怎么办啊！根本每个人都知道了嘛——」

「谁叫你要用同样发音的名字来做角色名称。不过……我好像也已经被发现了……」

在这所特殊「学校」里就读的学生，全都是国中、高中时期被卷入那个事件里的旧SAO玩家。这里除了因为积极杀人而必须接受心理咨询并被赋予一年以上治疗与观察义务的橘色玩家之外，也有不少像我这种为了自卫而攻击过其他玩家的人。此外在游戏里犯下的窃盗与恐吓等罪行由于不会留下纪录，所以也没办法清查。

因此学校为了避免纠纷，基本上禁止提起在艾恩葛朗特里的名字，但这么做其实没什么意义，因为每个人的长相都跟在SAO里一模一样。像明日奈她的身份在刚入学时马上就被人发觉了，而我在游戏里的名字以及其他事情也早被—部分旧SAO高级玩家们所知晓。

其实要大家把那段过去当成没发生过，本来就是不可能的事。在那个世界里的经验全都不是作梦而是事实，这些记忆也只能靠我们每个人自己去接受与释怀。

明日奈的双手原本抱着膝盖上的小竹篮，但我这时静静拉起她的左手并用双手将它包住。她的手虽然还相当瘦弱，但和刚醒过来时相比已经是好多了。

她为了赶上入学，经过了一段相当严酷的复健过程。而且她一直到最近才能够不靠拐杖走路，目前医生仍严禁她进行包含跑步在内的各种运动。

自从她醒过来后我便时常到医院去看她，但每当我看见明日奈一边流泪一边进行步行练习的模样，心中就会有一股锥心刺骨的疼痛感。想起那段日子的我，不知不觉间便不断摸着明日奈修长的手指。

「桐人……」

听见她的声音后我抬起头来，结果脸颊微红的明日奈用难以置信的声音说道：

「你不知道吗？从食堂里面可以看见这里耶！」

「唔……」

抬起头往上一看后，我发现由这里确实可以见到树木上方那最高层校舍的大片采光玻璃。于是我急忙把手放开。

「真是的……」

明日奈露出一副真受不了你的表情然后叹了口气，接着又再度别过脸说：

「粗心鬼没便当吃！」

「呜哇，饶了我吧。」

拼命道歉几秒钟后，明日奈终于露出笑容并打开膝盖上的竹篮。她拿出一份裹着餐巾纸的小包然后交给我。

我接过来后急忙打开餐巾纸，结果里面是塞了满满莴苣的大汉堡。令人食指大动的香味直击胃部，我立刻张开大口咬了下去。

「这……这个味道是……」

我拼命地嚼着嘴里的汉堡，大口吞下喉咙之后瞪大了眼睛看着明日奈的脸。

「呵呵。你还记得啊？」

「怎么可能忘记。这是在第七十四层安全地带里吃到的汉堡……」

「哎呀——我可是费了一翻苦心才重现这种酱料的呢。你不觉得很没道理吗。在那里面时拼命想要做出现实世界里的味道，但现在却又为了要重现里面的口味而大费周章。」

「明日奈……」

一回想起过去那段幸福的日子，内心涌起一阵强烈感伤的我不由得又凝视着明日奈。

这时明日奈也马上回看我，然后带着微笑小声说道：

「你嘴巴上沾到美奶滋了。」

当我吃完两个大汉堡而明日奈吃完一个小汉堡时，午休时间也差不多要结束了。准备帮我从小保温瓶里倒杯花茶的明日奈一边用两手拿着纸杯一边开口说：

「桐人，你今天下午还有课吗？」

「我下午还有两堂……真是的，现在教室里都不是黑板而是EL面板，而且不用笔记本而是用平板电脑，回家作业也都是以无线网络传送过来，这样的话在自己家里上课还不是一样吗？」

明日奈看着抱怨的我然后「呵呵」笑了一声。

「说不定面板和PC不久后也要被淘汰了呢。之后或许都会变成全息投影也说不定……而且我们就是因为来学校才能像这样见面啊。」

「这倒是没错啦……」

虽然我和明日奈已经把所有自由选修科目都排成一样，但我们原本学年就不同，所以课程内容也不一样，现在一个礼拜里只能见面三天而已。

「况且听爸爸说这里将会成为次世代学校的模范呢。」

「这样啊……那彰三伯父他还好吗？」

「嗯。有段时期相当消沉，一直责怪自己没有看人的眼光。他从CE0的位子上退下来之后已经算是半退休了，可能是不知道怎么打发空下来的时间吧。我想等他找到新的兴趣之后，马上就会恢复精神了。」

「这样啊……」

我啜了一口茶，然后学起明日奈抬头看着天空。

至于被明日奈的父亲结城彰三先生认为是未来女婿的那个男人——须乡。

下雪当天在医院停车场里被逮捕的须乡，之后也很难看地不断想逃避罪名。他只是一味保持沉默，并完全否认自己的犯行，最后还想把所有罪过都推到茅场晶彦身上。

但是他的一名部下在被列为重要证人并被检方带走之后，便将所有事情全盘托出。借着在RECT PROGRESS横滨分公司里设置服务器，利用SAO未归还者三百人来进行非人道试验的犯行被揭发之后，须乡便再也无法狡辩了。但听说开始公开审判的现在，他已经在申请精神鉴定了。虽说他主要的罪状是伤害罪，但目前社会大众最注意的是他掳人监禁的罪名是否能够成立。

而他所着手，利用完全潜行技术来进行洗脑的邪恶研究，也被发现除了初代NERvGear之外便没有机械可以实现。现在NERvGear几乎已经全部报废，而且似乎还能够开发出对抗须乡实验结果的措施。

所幸沦为实验体的三百名未归还者都没有残留遭到实验时的记忆。此外也没有脑部出现实质障碍或是发生精神异常的玩家，他们所有人在接受完善的治疗之后都可以正常回归到社会当中。

但是RECT PROGRESS公司与ALfheim Online，不，应该说VRMMO这种类型的游戏则全都受到了无法回复的打击。

原本光是SAO事件就已经造成相当大的社会不安了。而声称这全都是一名狂人所引起的偶发性犯罪，这次保证绝对安全的ALO以及其他VRMMO，却又再度因为须乡这次所引起的事件而让社会大众认为所有VR世界都可能会被利用来犯罪。

RECT PROGRESS最后因此而解散，而RECT总公司也受到很大的伤害，但在更换社长以下的营运阵容之后总算是慢慢渡过了危机。

当然ALO也被迫停止营运，虽然其他持续营运中的五、六款VRMMO游戏玩家并没有减少许多，但由于社会上的批评声浪实在太过猛烈，据说这些游戏今后恐怕也难逃停止经营的命运。

但以强大力量将这种状况整个反转过来的——

就是茅场晶彦托付给我的「世界的种子」。

在这里我必须提一下关于茅场的事情。

当二〇二四年十一月SAO世界崩坏的时候，茅场晶彦果然也随之死亡——这件事是在两个月前的二〇二五年三月时被证实的。

茅场在长野县人烟罕至的森林里有一栋山庄，而他以希兹克利夫这个身份存在于艾恩葛朗特的两年当中就是潜伏在这栋建筑物里面。

当然茅场的NERvGear没有被加上「死亡枷锁」，所以他可以随时登出，但身为公会血盟骑士团团长的他曾经连续登入游戏里长达一个礼拜的时间。

而在这段时间内帮忙照顾他的，是茅场同时任职于ARGUS开发部与都内工科大学时，与他进行同一项研究的研究所女学生。

在该研究室里的这名女性，从学生时代便与须乡熟识，表面上除了景仰须乡这个前辈之外，也对他存有相当强烈的对抗心。但实际上这名女性私下曾多次对须乡表达爱慕之意——这件事是上个月被保释出来的那名女性亲口告诉我的。

我勉强从解救对策室工作员那里问出那名女性的电子邮件信箱，在犹豫了许久之后才传了一封「我对你没有怨恨，只是想跟你谈谈而已」的电子邮件给她。结果在一个礼拜之后我就收到了回信。这名叫做神代凛子的女性还特别由现在居住的宫城县来到东京，然后在东京车站附近的咖啡厅里结结巴巴地对我述说事情经过。

茅场似乎从以前便决定要随着SAO世界的崩坏来结束自己的生命。但他选择的死亡方式可以说相当异常。他利用改造完全潜行系统后所制成的机器来对自己大脑进行超高密度扫描，结果脑部整个烧焦而死。

扫描成功的机率根本不到千分之一——这名让人感到有些可怜但又相当坚强的女性这么说道。

如果真能如茅场所愿，他就能把自己的记忆和思考，也就是大脑内部的电流反应全部转换成数字码，然后将自己的脑变成真正的电脑而存在于网络当中。

我犹豫了很久之后，对她说出在旧SAO服务器内部和茅场对话过这件事。另外也将茅场救了我和亚丝娜，以及他托付给我一样东西的事情告诉她。

女性低着头过了几分钟，从眼里落下一滴泪水之后对我说道。

——我原本到他潜伏的山庄去准备要结束他的生命。但最后却无法下手。害得许多年轻人因此而失去生命。

他和我所做的是无法被饶恕的事情。

如果你还恨他的话，就请你把他托付的档案给消除吧。

但是，如果……如果你心里还存有憎恨以外的感情…………

「桐人——桐人啊……关于今天的网聚……」

手肘被戳了一下后，我才终于回过神来。

「啊啊——抱歉。刚才在发呆……」

「真是的。不管在这里还是在那边，你只要一放松，就会变成一个成天只会发呆的大笨瓜耶！」

明日奈无法忍受似地摇了摇头，接着又露出宛若和煦阳光的笑容，接着把头靠在我的肩上。

★　　★　　★

食堂西侧窗户边，我坐在从南方数来第三个圆桌前，用力吸着铝箔包里剩下来的草莓优格。由于发出了不符合少女形象的巨大噪音，坐在我对面的绫野珪子脸色变得相当难看。

「真是的，莉兹……里香小姐，可不可以请你喝东西时小声一点。」

「但是……啊——桐人那家伙又靠那么近……」

我的视线前方是只有从这张桌子才能透过树梢看见的中庭板凳，而板凳上有一名男学生正和一名女学生并肩坐在一起。

「真是不害臊，竟然在学校里做出……」

「这、这样偷看人家不太好吧！」

我瞄了珪子一眼，然后故意用调侃她的口气说：

「你还敢说我哩，西莉卡自己刚才还不是一直盯着看。」

珪子也就是短刀使的西莉卡——或许应该反过来说——她马上满脸通红的低下头去，接着大口大口地吃起虾肉炒饭。

我将喝完的铝箔包捏扁丢进几公尺外的垃圾桶后，把脸撑在桌子上后大大叹了一口气。

「啊——啊……早知道会变成这样，当初不要签订什么『一个月休战协议』就好了。」

「那都是莉兹小姐你提出来的不是吗！说这个月就让他们两个人去卿卿我我……实在是太天真了啦！」

「你脸上黏着饭粒唷。」

我再度叹了一口气，然后抬头朝着采光玻璃后面流动的白云看去。

我不知道桐人是怎么查到我的信箱，不过他在二月中左右寄了封电子邮件给我。

我当时感到相当惊讶，脑袋里一边响着恋爱大赛第二回合就要开始的钟声，一边赶紧跑去和他见面。而桐人在咖啡厅里所说的话更是让我大吃一惊。

桐人他直接卷入了那起让社会为之骚动的「ALO事件」，而社会大众并不知道亚丝娜其实也是这事件里特殊型态的受害者。

当桐人告诉我亚丝娜她很想见我之后，我当然马上就去探病了。当我见到亚丝娜那副随时都可能消失不见，宛若雪精灵的模样之后，以往在艾恩葛朗特里那种想要保护她的心情也再度受到强烈刺激。

幸好亚丝娜她日复一日逐渐恢复了元气，也同时能够进入这所学校就读。但是我只要一见到她，就会觉得她不是情敌而是应该保护的妹妹，结果在一个不注意之下便把眼前这个同样喜欢上桐人的朋友卷进来，组成了「到五月底为止我们就在旁边守护着他们吧」的同盟，但是将最后一块BLT三明治（注：培根、生菜、蕃茄所做成的三明治）随着第三次叹息一起送进嘴里之后，我朝着西莉卡看去。

「今天的网聚你会去吗？」

「当然——听说莉法……直叶也会来。这是我第一次在网聚里见到她，很期待呢！」

「西莉卡和莉法感情真的很好呢。」

我再度露出不怀好意的笑容。

「可能你和她同样是『妹妹』，所以有亲近感吧？」

「哼……」

西莉卡鼓起脸颊，将最后一口虾肉炒饭塞进嘴里然后同时笑了起来。

「莉兹小姐还敢说我呢，你自己现在还不是完全一副『姐姐』的模样。」

我们两个人之间爆发了好几秒钟的火花，然后才同时抬头看着白云，又同时叹了一口气。

★　　★　　★

艾基尔的店「Dicey Cafe」那扇不友善的黑门上挂了一块同样不友善的木牌，上面还有不友善的字迹写着「今日已出租」。

我看着身边的直叶说道：

「直叶你有见过艾基尔了吗？」

「嗯，在另一个世界里一起狩猎两次了。他真的很魁梧耶～」

「先告诉你，他本人也是那种模样。你要先做好心理准备喔。」

亚丝娜在瞪大了眼睛的直叶身后嘻嘻笑着。

「我第一次来这里时也吓了一大跳呢！」

「老实说，我也吓到了。」

直叶脸上这时露出了怯意，我砰一声拍了一下她的头之后便一口气把门推开。

大量欢呼声、拍手声、口哨声随着门被打开时的「喀啷」铃声一起响起。

不是很宽敞的店里此时已经挤满了人。扩音器里发出超大音量的BGM惊人的是那竟然是艾恩葛朗特的NPC乐团所演奏的阿尔格特街道主题曲——而店里所有人手里的杯子都发出液体亮光，看来气氛已经是相当热络了。

「喂喂——我们可没迟到啊！」

吓了一大跳的我这么说完之后，穿着制服的莉兹贝特走出来说：

「嘿嘿，主角当然是要最后登场啦。所以我告诉你们的集合时间比较晚。来，快进来快进来！」

我们三个人马上被拉进店里，然后又被推到店深处的一座小舞台上面。这时店门磅一声被关上，接着BGM暂停，灯光也全都拉了过来。

忽然聚光灯整个照在我身上，接着莉兹贝特的声音再度响起。

「桐人，恭喜你完全攻略了SAO——！」

所有的人一起齐声说道。接下来便是一连串礼炮声与拍手声。

我脸上因为惊讶而呆滞的表情就这么被数台相机给拍了下来。

今天的网聚——「艾恩葛朗特攻略纪念派对」原本是由我和莉兹、艾基尔所共同策划，但在不知不觉之间他们便瞒着我进行了这样的安排。店里参加者的人数大概超过我预期的一倍以上。

干杯之后所有人都开始做了简单的自我介绍，接着在我的演讲——当然这也是原本没有的项目结束之后，就轮到艾基尔特制的好几盘巨大披萨登场，这时宴会完全陷入一片狂欢状态。

我在受到所有男性参加者有些粗暴以及女性参加者有点过于亲密的祝福后，疲累不堪地来到了柜台前并整个人摊在圆凳上。

「老板，来杯加冰块的纯波旁酒……」

当我随便点完饮料之后，穿着白色衬衫、打着黑色蝴蝶结领带的巨汉便低头狠狠瞪了我一眼。惊人的是，几秒钟之后果然有一只装着冰块注满琥珀色液体的平底杯滑了过来。

畏畏缩缩舔了一口之后，发现原来其实只是普通的乌龙茶而已。当我抬头看着露出「骗到你了吧」笑容的店主并垂下嘴唇时，有一名身穿西装的瘦高男子坐到我旁边来。男人除了西装上搭配了一条很没品味的领带之外，额头上竟然还绑着一条印有低俗图案的头巾。

「艾基尔，给我来杯正牌的波旁酒。」

男人——刀使克莱因接住平底杯之后便转动圆凳，然后用色眯眯的表情看着店内角落那张女孩子们正发出娇笑声的桌子。

「喂喂，不要紧吗。你等一下不是还要回公司？」

「哼，不喝酒哪能加班啊。不过话说回来……这可真是秀色可餐哪……」

我对快流下口水的克莱因叹了口气，然后喝了一大口乌龙茶。

不过这确实是一副很养眼的美景。莉兹贝特、西莉卡、纱夏、由莉耶尔、直叶等女性玩家全部聚集在一起的这幅景象，实在让人很想把它拍下来当装饰品呢。虽然为了给结衣看我还真的有在录像就是了——

我身旁另一边的圆凳上也坐着一个男人。虽然他也是穿着西装，但看起来就是与克莱因不同，一副就是很正经的上班族模样。而他就是元「军队」最高负责人辛卡。

我举起杯子对他说道：

「对了，听说你和由莉耶尔小姐结婚了对吧。虽然有些迟了——但还是要恭喜你。」

我们两个人的杯子互相碰了一下。辛卡似乎有点不好意思地笑着说：

「哎呀，到现在还是在拼命习惯这个现实世界。而且工作也好不容易才上轨道而已……」

克莱因也举起杯子，探出身体说：

「嗯，真的很值得庆祝！可恶，早知道也在里面找个对象。话说回来，我是你们新生『MMOTODAY』的读者唷。」

辛卡再度露出羞涩的笑容。

「哎呀，不好意思。我们的内容还不是很充足……而且对于现在的MMO来说，攻略档案或是最新消息都已经慢慢失去意义了……」

「简直就像是宇宙诞生的浑沌一样。」

我点了点头后便抬头看向摇着雪克杯的店主。

「艾基尔，之后『种子』的状况如何？」

秃头巨汉露出会吓哭小孩的笑容后愉快地说道：

「那可真是不得了。现在大概有五十个镜像服务器……下载总数达到十万，实际运作的超大型服务器大概有三百台吧……」

茅场晶彦的思考仿真程序托付给我的「世界的种子」——

我和茅场的女性助手谈过之后又过了几天，在结衣的帮忙之下把由NERvGear局域网络传送到内存芯片的巨大档案拿到艾基尔店里。因为我认为只有这个身为我知己的男人可以帮忙种子发芽。

我当然对茅场以及他所创造的浮游城艾恩葛朗特怀有憎恨的感情。那个死亡游戏的世界让好几名与我心灵相通的友人失去了生命。一想到在恐惧当中死去的他们——还有那个女孩，我就无法饶恕茅场。

但很遗憾的是，我也无法否认在强烈的憎恨当中还对他存有一丝的认同感。

就因为有生与死的存在，那座城堡才会变成真正的异世界。我心里虽然渴望脱离那个世界，但同时也深爱着它。在我心底深处确实有着希望它永远存在的感情。

因此我想，至少要确认那颗「种子」会发出什么样的芽来。

世界的种子。

那是由茅场所开发出来的，借着完全潜行系统来运作全感官VR环境，名为「The Seed」的相关程序套件。

茅场在整理过自动管制SAO服务器的「Cardinal」系统后，除了将系统规模缩小为可以在小型服务器里运作之外，该系统里面还包含着游戏组件的开发环境支持。

也就是说如果你想要创造一个VR世界，只要准备一台带宽还可以的服务器并下载这个套件，然后设计3D对象或者是配置套件里既存的对象接着让程序运作，你就可以诞生出一个属于自己的3D世界了。

要开发控制五感输入·输出的系统程序可以说相当困难。实际上全世界营运当中的VR游戏，都是根据茅场在ARGUS所开发出来的Cardinal系统所制造，而要使用这套系统必须付出非常高额的权利金。

随着ARGUS消灭，程序的权利也转移到RECT手里，但现在又因为RECT PROGRESS解散而正在寻求愿意买下该程序使用权的企业。不过由于金额过于庞大以及社会大众对于VR游戏的批判，使得没有企业愿意出手收购，而这也让此类型的游戏开始陷入衰退状态。

这时候登场的就是标榜完全不需要权利金而且小巧又机能充实的VR控制系统「The Seed」了。艾基尔先运用他的关系彻底检验了我所得到的程序，确定里面不存在任何的危险因素。

我们不清楚茅场真正的意图究竟为何——而且就算是程序本身没有危险，但这个程序流出到市面上之后，应该也只有茅场本人才知道会造成什么样的状况吧。只是我想茅场创造出这程式的动机应该相当单纯。

那就是不断追求「真正异世界」的梦想。

我拜托艾基尔把「The Seed」上传到全世界各地的服务器里，让不论是个人或者是企业都可以自由下载这个程序。

ALfheim Online原本应该已经死亡，但同时也是ALO玩家的几家新兴企业经营者又让它重新复活了起来。

他们先共同出资来建立一所新公司，然后由RECT手里以几近免费的低价接收了ALO所有档案。

崭新的阿尔普海姆大地便在新的摇篮里再生，玩家原本的档案也完全被继承过来。因为那个事件而离开游戏的玩家几乎不到全体的一成。

当然新诞生的世界不只有阿尔普海姆而已。

原本没有能力支付庞大权利金的企业乃至于个人，多达数百名人员表达愿意成为营运者的意图，因此不断有VR游戏的服务器开始运作。当然这些游戏里面有的需要收费也有的完全免费，但这些游戏相当自然地就互相连结起来并且订定了几条最高原则。目前已经慢慢建立起「在某个VR游戏里创造出来的角色也可以转换到另一个游戏里使用」这样的结构了。

而且The Seed还不是只能利用在游戏上而已。像是教育、交流、观光等等，每天都有新领域的服务器诞生，所以每天也都会有新世界出现——相信不久之后，VR世界的「现实世界换算面积」大于日本这个国家的日子就会来临了。

辛卡一边苦笑，一边用怀有梦想的眼神继续说道：

「我们现在正目睹一个新世界的诞生。只靠MM这个名词已经不足以概括形容这个世界了。虽然我也很想更新网页的名称……但是却又找不出个足以形容它的名词。」

「嗯～～……姆……」

克莱因把手臂交叉在胸前，皱着眉头拼命思考着。我戳了一下他的手肘，边笑边说：

「喂，把公会取名为『风林火山』的家伙没人会期待你的品味啦！」

「你说什么！我告诉你，新生·风林火山可是有一堆人想加入呢！」

「这样啊——如果有可爱的女孩子就好啰～」

「呜……」

我看着克莱因无话可说的脸笑了一阵子后，再度看着艾基尔说：

「喂，续摊的预定没有改变吧？」

「嗯嗯，今天晚上十一点在世界树城市集合。」

「那么……」

我放低了声音说：

「那个可以动了吗？」

「没问题。不愧是『传说中的城堡』，听说用了一整个新的服务器群呢。但不论是使用者或是资金都大幅增加了！」

「如果可以顺利成功就好了。」

——旧SAO服务器已经完全被初期化并且报废了。但是在交给新ALO营运者的ARGUS开发档案里，竟然有着令人意想不到的物品存在。

我一口气将杯子里的乌龙茶喝光，然后就这样握着杯子抬头看向店里的天花板。黑色天花板看起来就像深夜的天空一样。这时忽然有淡灰色的云流过，月亮出现将整片世界染成蓝色。接着在遥远处出现了巨大的——

「喂——桐人，到这边来！」

完全处于亢奋状态的莉兹贝特一边用力挥手一边大声叫唤着我。

「……那家伙不会是喝醉了吧……」

我的眼光停留在她手里那杯装有粉红色液体的巨大杯子上，结果视法律为无物的店主听见我的呢喃后，一脸无所谓的说：

「酒精浓度百分之一以下不要紧的啦。而且明天又放假。」

「喂喂……」

我摇了摇头之后便起身离开。看来这会是个相当漫长的夜晚哪。

★　　★　　★

莉法飞翔着穿透了漆黑的夜空。

四张翅膀在大气中挥动撕裂空气，让莉法不断加快速度。

如果是在以前的话，为了用有限的飞翔力量来尽可能延长飞行距离，就必须考虑以最有效率的巡航速度或者是不断重复加速与滑行的滑翔飞行法来飞行。

但现在这些都已经是过去式了。因为束缚她的系统枷锁已经不存在。

结果世界树上根本没有空中都市。根本就没有所谓的光之精灵，宣言要让第一个谒见他的种族转生的精灵王根本就是个冒牌货。

但是这个世界在历经一次崩坏再度重生之后，新的支配者——不对，应该说是调整者们便给予所有精灵能够永远飞翔的翅膀。虽然种族依然是风之精灵而不是光精灵，但对莉法来说这样就已经足够了。

莉法比集合时间早了一个小时登入，由最近时常待在这里的猫妖领地首都「弗莉莉亚」里起飞后，已经持续飞行了快要二十分钟。这段时间里面她没有停下来休息过，只是依照本能全力震动着翅膀。但发出草绿色光芒的魔法动力到现在依然没有失去力量，它还是一直遵照着莉法的意思持续运作着。

根据桐人表示，这个新世界里的加速理论就跟汽车非常类似。

飞上天空之后马上将翅膀往左右张开并加大振幅，利用所谓「扭力重视」——这名词也是桐人所说，但莉法不太清楚是什么意思——的飞行方法来用力排开空气。

速度慢慢增加之后，就配合将翅膀叠成锐角，然后也逐渐缩小振幅。当达到最高速度时，翅膀除了几乎叠成一直线之外还会以看不见的速度震动着，因此从地面上看起来根本就像带着颜色的彗星掠过天际一般。到达这个阶段时速度便难以再增加，至于能加快到什么样的程度就要看玩家个人的勇气了。一般玩家不久后都会因为恐惧与精神上的疲劳而开始减速。

上周举行的「阿尔普海姆横贯大赛」里，莉法在与桐人经过了剧烈竞争之后以些微差距赢得比赛。由于两个人实在领先其他参赛者太多，所以第二届大赛能不能顺利举行还是个问题。

……那个时候真的很快乐……

莉法一边飞一边因为回想起那时候的事情而笑了出来。在终点前追上来的桐人为了让莉法发笑而使用了讲冷笑话这种卑鄙手段，而莉法也真的整个人大笑了起来。最后她为了报复而将解毒药水实体化并朝桐人丢了过去，如果不是药水有击中桐人的话莉法早就输掉这场比赛了。

像那样在比赛当中的飞行虽然也很过瘾——但还是把脑袋放空之后，纯粹只为了突破界限而不断加速的时刻最让莉法感到开心。

经过数十分钟的飞翔之后，莉法的速度已经快提升到极限。这时被一片黑暗所包围的地面看起来就像不断像后流去的线条，而前方刚出现的小街灯也马上就消失在身后了。

当身体感觉已经到达学会飞行以来的最高速度时——莉法瞬间张开翅膀并反转身体开始急速上升。

从头顶上厚厚的云层缝隙里可以见到巨大满月正发出光芒。而莉法就像火箭般朝着这蓝白色的玉盘直线上升。

几秒钟之后，莉法随着产生细微变化的风声一起冲进云海。她就像颗子弹般贯穿这层黑色面纱。突然在距离莉法非常近的地方发生闪电，云层也整个被染成白色，但她还是毫不在意的往前突进。

不久之后她终于穿透云海。眼前的宝蓝色月光包围整个世界，眼下则是一片云的平原。这里唯一能见到的物体便只有远方那贯穿云海的世界树尖端而已。此时速度终于开始有点下降，但莉法还是紧闭着嘴唇努力伸长指尖，只是一心朝着满月前进。可能是心理作用吧，感觉上像银盘般的月亮直径好像一点一点变大了。莉法这时甚至可以清楚见到月亮上有几道陨石坑。

其中一个巨大坑洞的中央似乎可以见到一群闪烁的光芒。难道这只是莉法眼睛的错觉吗？还是说那是某一座无人知晓的月球人街道所发出的光芒呢？如果可以——可以再靠近一点的话——

但是世界的尽头，也就是名为限制高度的墙壁终于挡住了莉法。到此就没办法再继续往上升了。但是……

莉法用力伸长了右手，像是要抓住月亮般张开手指。

我想到更高、更远的地方去。越过平流层，脱离重力束缚，一直到那个月世界为止。不对，之后还要跨过行星轨道、超越彗星直达一大片星海——

终于，她的上升速度完全归零，接着变成负数。莉法就这么张开双臂，在夜空当中变成自由落体。月亮开始慢慢离她远去。

但是莉法却闭上眼睛，脸上浮现微笑。

虽然现在还无法达成——

但根据桐人表示，这款ALfheim Online也有加入更大VRMMO集合体的计划。而且—开始就是要和以月球表面为舞台的游戏互相连结的样子。这么一来，莉法就可以直接飞到月球上去了。不久之后其他游戏世界将被设定为不同行星，到时候有渡船横跨星海到各个行星的日子就会来临。

届时莉法将可以随意飞行到任何地方。但是……却还是有一个她永远到达不了的场所。

莉法心头忽然涌起一丝寂寞。

她一边朝软绵绵的云海落下，一边用双手抱紧自己的身体。

她知道自己觉得寂寞的理由。那是因为今天晚上在现实世界里，桐人——和人带自己去参加的那个派对所造成的。

当然她感到非常开心。因为一直以来她只能在这个世界里与新朋友们见面，而今天是她首次能和他们在现实世界里相见并且聊天。举行派对的三个小时可以说一转眼间便过去了。

但是她同时也在里面感觉到他们之间那种看不见但却十分牢固的羁绊。他们在目前已经消失的「那个世界」浮游城艾恩葛朗特里共同作战、哭泣、欢笑、相恋的记忆——即使现在已经回到现实世界，也仍然在他们心中放出强烈光芒。

直叶喜欢桐人的心情到现在依然没有改变。

晚上在门前道晚安时、白天一起跑步到车站时，她总是有一股类似和煦阳光的心情。她也曾一边流着痛苦的泪水，一边想着如果他们是真正的兄妹，甚至是生活在不同城市的陌生人就好了。但是现在每天在同一个屋檐下的生活已经让她感到非常幸福。就算不是全部也没关系，自己只要能在和人心里占据一个小小的位子就够了。

——自己好不容易才能这么想了。

但在那场派对里头，直叶心里就是有一种和人不久后将会离她远去的预感。自己绝对无法进入那群人的羁绊当中。那里面根本没有直叶的容身之处。因为直叶她没有关于「那座城堡」的记忆。

莉法缩起身体，像流星一样不停往下坠落。

马上就要到达云海了。集合场所是新设在世界树上的世界树城市，所以该是要展开翅膀准备滑翔的时候了。但是因为内心充塞着寂寞心情，让她无法运动自己的翅膀。

寒风吹拂过她脸颊同时也将她胸口的温暖给带走。她就这么一直往黑暗的云海里深深沉去——

突然身体像被什么东西接住而停止落下。

「——？」

莉法惊讶的张开眼睛。

桐人的脸随即就出现在她眼前。他用两手抱着莉法，在快到云海前的空中盘旋着。在莉法说出「为什么——」前，浅黑色肌肤的守卫精灵便开口说道：

「我还担心你究竟要上升到什么地方去呢。时间快到了所以我过来接你。」

「……这样啊……谢谢……」

莉法微微一笑之后张开翅膀从桐人怀里飞了出来。

运作这座新ALfheim Online的营运体从RECT PROGRESS公司接收过来的全部游戏档案里面，也包含了旧Sword Art Online的角色档案。因此营运体在旧SAO玩家联机至新ALO开设帐号时，特别让他们可以选择是否继承原本角色包含外表在内的所有档案。

因此经常和莉法玩在一起的西莉卡、莉兹贝特等人除了附加上精灵的种族特征之外，长相基本上都与现实世界里的她们非常相近。但是桐人在面临这个选项时却没有让以前的外表复活，选择了继续使用这个守卫精灵的外表。此外他还将那些惊人的能力值全部初期化，开始重头锻炼起自己的各项能力。

莉法现在忽然很想知道他这么做的原因，于是她同样停在半空中并对着桐人问：

「哥哥……桐人，为什么你不像其他人那样恢复原来的面貌呢？」

「嗯——……」

结果桐人把双臂交叉在胸前，眼神望向远处某个地方。他微微笑了一下才回答：

「那个世界里的桐人，任务已经结束了。」

「这样啊……」

莉法也轻轻笑了笑。

最先遇见守卫精灵战士的桐人，然后和他一起旅行到世界树的人就是自己。一想到这里莉法就觉得有些开心。

他们以站姿在空中移动着，结果莉法忽然握起桐人的右手说：

「桐人，我们来跳舞吧……」

「咦？」

莉法拉着瞪大眼睛的桐人，开始在云海上像滑行般横移了起来。

「这是最近才开发出来的高级技巧。就像这样一边停在半空中一边慢慢地横向移动。」

「原、原来如此……」

桐人像是被激发了挑战心一样，以非常认真的表情配合着莉法的动作滑行。但他马上就向前倒去并且失去了平衡。

「呜哇！」

「呵呵，你往前面加速才会这样。你弄错了，只要产生一点上升力，然后同时往横向滑行……」

「唔唔……」

被莉法拉着手臂，东摇西晃地奋斗了几分钟之后，桐人便以他那惊人的适应力学习到了跳舞的诀窍。

「哦……原来如此，是这样吗……」

「对对。好厉害哦！」

微微笑了一下之后，莉法便从腰间的口袋里拿出一个小瓶子。拔开栓子让它飘浮在半空中之后，随即从瓶口溢出带着银色光芒的粒子，同时也开始能听到有清澈的弦乐重奏传了出来。

这是音乐精灵的高等级吟游诗人将自己演奏装进瓶子后拿来贩卖的道具。

莉法配合着音乐慢慢地踏起舞步。

他们两人的身影便这样在空中忽远忽近、忽大忽小地跳着舞。在这当中桐人一直牵着莉法的手，而莉法则是一直凝视着他的眼睛，随着移动方向即兴踩着舞步。

两人就在湛蓝月光照耀下的无尽云海里不停旋转着。原本缓慢的动作开始越来越加快，光是一个踏步就能飞出老远的距离。

莉法翅膀上飞散的绿色光芒与桐人翅膀上洒下的白光互相重叠、碰撞并且消失。这时风声忽然整个消逝。莉法也静静闭上眼睛。

她用心灵感受桐人由指尖传递过来的全部心意与感情。

莉法心想这或许是最后一次了。

至今为止两个人曾有过好几次心灵相通的魔法时刻。但这可能是最后一次了。

桐人——和人有属于他自己的世界。属于他自己的同学、伙伴，还有最心爱的人。他的翅膀太过于强壮、步伐太过于辽阔，让莉法根本追不上他。

从两年前他到那个世界旅行而不再回来的那天起，他们两个人便开始渐行渐远了。虽然为了想接近他而获得精灵的翅膀，但和人和其他人的心到现在还有一半留在那空中的梦幻城堡里。

科学技术的进步已经让假想世界越来越真实。它已经超越了游戏的领域，把假想变换成现实。但人类还没有灵巧到能在好几个现实世界里生活。和人之所以对那个世界有那么深的依恋，一定是因为他在那个直叶永远无法到达的梦幻世界里累积了太多欢乐、悲伤以及爱情的经验。

莉法感到自己眼睛里流下了泪水。

「——莉法……？」

耳边响起了桐人的声音。

莉法睁开眼睛，边微笑边看着他的脸。这时由瓶子里传出来的音乐声先是越来越淡，然后随着瓶子破裂的细微声音同时消失。

「我今天就先回去了……」

莉法放开桐人的手后这么说道。

「咦……？为什么……」

「因为……」

她的眼中再度流下泪水。

「哥哥和大家……都离我太遥远了。我没有办法跟你们到那边去……」

「小直……」

桐人以认真的眼神看着莉法，接着轻轻摇了摇头。

「没那回事。只要你愿意就可以到任何地方去。」

不等莉法回答，桐人便再度紧握起她的手并转过身子。

「啊……」

他用力拍动翅膀开始加速。只见他直线朝着耸立在云海远方的世界树飞去。

桐人不理会莉法的意愿，只是以猛烈速度向前飞行。他紧握住莉法的手丝毫没有放松，而莉法也只能在后面拼命跟着他前进。

世界树的体积也随着他们越来越接近而大到足以遮蔽整个天空。这时可以见到树干分叉出好几根树枝的中央部位上出现了一大群光点。而那便是世界树城市的灯光。

桐人对着中央最为高大而且发出耀眼光芒的塔飞去。

随着距离越来越近，原本看起来是一大团的发光群，现在也分为建筑物窗里的光芒与照亮道路的街灯了就在这个时候……

忽然连续响起好几道钟声。这是宣告阿尔普海姆已经到了午夜十二点的钟。世界树内部目前设有连结阿鲁恩与世界树城市的电梯，而这口钟便摆在这个大空洞的上方，它的钟声可以传遍整个世界。

桐人张开翅膀进行紧急煞车。

「哇啊？」

莉法一时停不下来而差点撞上他。但停在半空中的桐人张开双臂轻轻抱住了莉法。

「看来是来不及了。它要下来啰——」

「咦？」

由于不了解这句话的意思，莉法只能呆望着桐人的脸孔。桐人笑了一下并眨了眨眼睛，最后用手指向天空的一角。莉法在他臂弯里改变身体方向，抬头看着夜空。

莉法只见到——巨大的满月正发出清澈的蓝色光芒。

「月亮怎么样了吗……？」

「看仔细一点。」

桐人将手往更高处指去。莉法定睛凝神看着天空。

光辉的正圆形右上方边缘——稍微出现一点缺角。

「咦……？」

莉法瞪大了眼睛。她一瞬间有了「是月蚀吗……？」的想法，但随即想起阿尔普海姆里从没有发生过这种现象。

侵蚀月亮的黑影面积不断增加。但它的形状并不是圆形。黑影就像三角形楔子般持续钉入月亮当中——

这时莉法耳朵忽然又听见一道重低音。由远方传来一种让整片天空为之震动的「轰隆轰隆」声响。

影子终于整个盖住月亮。但是由远方照射下来的月光却还是让三角形影子的轮廓朦胧地浮现出来。只见它越来越大、越来越靠近。

看来那似乎是个圆锥形的物体。但目前为止还无法掌握与它之间的距离感。莉法皱着眉头仔细观察起那个物体。结果——

那个浮游物突然发出了光芒。

一道眩目的黄色亮光往四方散去。

看来它是由许多薄薄层状物所堆积起来的物体。光线就是由层状物里发射出来的。它的底端垂下三根柱子，柱子前端还发出刺眼的光芒。

是船吗……？还是房子……？莉法歪着头这么想着。在她思考的期间，该物体的外表也因为逐渐接近而不断变大。现在它已经遮蔽住一部分的天空了。大气里的重低音让莉法的身体震动了起来。

这时她发现最下层与上层之间似乎有什么东西存在。那看起来像是几根小突起物由下方往上延伸。不——那应该是——

建筑物！数栋排着好几层楼窗户的巨大建筑物聚集在一起。但是——如果以建筑物的大小来换算的话，那这有着几十层的物体光是一层就有风之塔那样的高度了。这么一来，那个浮空圆锥的整体高度……不就有几百公尺，不对，应该有几公里才对……？

「啊……难道……难道那是……」

想到这里时，莉法脑里忽然灵光一闪。

「那是……！」

她转过头来看向桐人。

桐人用力点了点头，接着用兴奋的声音说道：

「没错——那就是浮游城艾恩葛朗特！」

「——！但是……为什么？为什么会出现在这里……」

浮在空中的巨城好不容易减缓来势，在快碰到世界树顶端树枝的地方停了下来。

「因为我想要跟它做个了断。」

桐人沉稳地说道。

「这次一定要从第一层到通到第一百层来完全征服那座城堡。之前才通过四分之三的楼层就结束了。莉法——」

他砰一声把手放在莉法头上，接着才又继续说：

「我现在已经变弱了……你会帮我的忙吧？」

「……啊……」

这时莉法根本发出不声音，只是凝视着桐人的脸。

——只要你愿意就可以到任何地方去。

泪水再度由她脸上流下，滴落到桐人胸口。

「——嗯。无论……你要去什么地方……我都会跟着你……」

当她靠在桐人身边抬头看着巨大浮游城时，脚下忽然有声音传上来。

「喂——你太慢啰，桐人！」

莉法将视线朝下方看去，马上就见到满头红发上绑着黄黑色头巾，腰间还挂着一把惊人长刀的克莱因飞了上来。

他身边则跟着带有大地精灵的茶色肌肤，背上扛着一把巨大战斧的艾基尔。

此外还有垂着小矮妖专用的银造榔头，身上纯白与蓝色围裙礼服发出亮光的莉兹贝特。

当然也少不了长着带有光泽的黑色耳朵与尾巴，肩膀上还停着一匹水蓝色小龙的西莉卡。

这时由莉耶尔与辛卡也牵着手飞了过来。

而纱夏似乎还没习惯飞行的样子，她手里握着遥控器摇摇晃晃地飞着。

不知道是什么时候与他们会合的，连朔夜与亚莉萨·露还有数名风精灵与猫妖玩家也都赶了过来。

另外下方还有一边挥手一边上升的里根。

结果竟然连火精灵将军尤金与他的部下们也出现了。

「喂，再不快点要丢下你们啰！」

克莱因留下叫声后便与一大群人争先恐后地在夜空中往上飞，朝向天空中的城堡直线前进。

最后面则是穿着白色束腰外衣与迷你裙，腰间挂着白银细剑，肩膀上停着一只小妖精的亚丝娜甩着一头长长秀发在两人面前停了下来。

「来，我们走吧，莉法！」

莉法畏畏缩缩地握起对方伸出来的手。亚丝娜笑了一下之后拍动背上水蓝色翅膀并转过身子。

她肩膀上的结衣也飞了起来，最后在桐人肩膀上着地。

「爸爸，快一点嘛！」

桐人清澈的视线往艾恩葛朗特看了一下，接着又低下头去沉默了一阵子。这时他的嘴唇微动似乎在叫着某个人的名字，但由于声音实在太小了而听不清楚。

当桐人再次迅速抬起头来时，往常那种自傲的笑容已经再次回到他的脸上。他将翅膀完全张开，用手笔直指着天空开口说道：

「好——我们走吧。」

<全文完>

** 后记

大家好，我是川原砾。谢谢各位购买我的第八本作品《Sword Art Online刀剑神域4妖精之舞》。

本篇虽然是由上下两集所构成的故事，但它除了是第1集的续篇之外，也是篇非常非常漫长的终章。当初开始写这篇故事时，我只是想写主角·桐人寻找并发现女主角·亚丝娜的故事而已，但在加入许多要素之后就造成了这么一大长篇的内容了。

而要素之一，便是「很普通地玩着RPG而已真的能够成为一本小说吗」的错误试验。

我在创作《SAO》第1集时，认为RPG小说如果不附加上什么条件就无法成立。因为游戏内的主角就算遇见九死一生的危机，现实世界里的他依然完全不会受到任何伤害。为了要消弭「只不过是游戏」所以「只要重来就好了」的双重不利要素，我只好在第1集里加上了死亡游戏，也就是游戏里的死亡就等于真正死亡的条件。

但是在我心中一直残留着「难道真的是这样吗」的疑问。感觉如果RPG小说一定要有附加条件才能成立的话，那我身为MMO玩家所得到的兴奋与感动也不过只是假像而已。于是是否能够借着故事表达出「与朋友们组队后，战战兢兢地突破首次进入的迷宫时那种乐趣」，便是这分成上下两集的「妖精之舞」最重要的题目。

至于我的企图是否已经成功……从看完本书最后一页的你会不会有「我也想玩玩看MMO」这样的心情就能知道了（笑）。

以正统「虚拟世界网络游戏」为故事内容的SAO系列将从下一集起完全转移方向，开始进入横冲直撞的暴走状态。喜欢我作品初期气氛的读者或许会感到非常不适应，但唯一不变的就是，故事内容还是全由桐人氏所干出来的好事所构成（笑），如果大家也能支持他今后的冒险我会感到相当高兴。

与上一集相同为大量出现的角色们与怪物群画下美丽插图的abec老师、因为我补写作业延迟给而您添了不少麻烦的担当编辑三木先生，这次也非常感谢你们！当然也要对一直支持着我的读者们献上足以塞爆你们硬盘容量的感谢！

二〇—〇年一月二十八日 川原砾