#+title: 刀剑神域 第五卷 幽灵子弹
#+setupfile: ./setup.setup
* 第五卷 幽灵子弹

** 序章

台版 转自 watashi101、葉月零、折原あずさ、哦☆卖糕的、葉月和、奇跡のかけら@SOSG论坛

『AGI（注：敏捷度）万能论根本只能说是幻想而已！』

尖锐的男性声音响彻整个宽广的酒店。

『AGI确实是相当重要的能力值。到目前为止，只要速射与回避这两个能力够突出就能够称为强者了。』

微暗店内的中央飘浮着四面全息图面板，而映照在面板上的玩家正以充满自信的声音这么说道。

这是网络电视节目「MMO动向」的人气单元「本周的优胜者」。虽然由现实世界里的电视或者是透过网络也能收看这个节目，但无数VRMMO世界内的旅馆与酒店也经常播放本节目，而玩家们也特别喜欢在「内部」收看。

尤其当特别来宾是来自于「那个世界」时就更吸引人注意了。

『但那已经是过去的事情了。花了八个月拼命提升AGI的废人玩家们，我必须对你们说——请节哀顺变。』

他那种充满调侃的语调让店内各处都响起了大量嘘声，甚至有些酒瓶与杯子被丢在地面上而散发出多边形碎片。

但是「他」没有加入这场骚动，只是缩着身体静静坐在沙发上。

由深深拉下来的吉利服头套与盖住下半边脸部的厚布之间，射出一道冷冷的视线环顾着店里。

画面中趾高气昂的男人固然可憎，但这些呆呆看着电视的玩家同样也令人不愉快。每个人虽然都不断发出嘘声，但一方面也像是参加祭典般不断起哄着。

「他」实在没办法理解，这些人为什么能够那么天真呢。电视里的那个男人只是偶然拿下世界最强的宝座而已，接着马上就转变成游戏里最大的榨取者，开始掠夺全体玩家的部分连接费用，还自认为是职业玩家。

其他玩家心里应该也跟「他」一样嫉妒并憎恨那个男人才对。如果说这是丑恶不堪的情绪，那么这些人用皮笑肉不笑的笑容来隐藏自己这种情绪就不丑陋又滑稽吗？

「他」服装底下的肌肉全部紧绷起来，由轻轻紧咬的齿缝中呼出一口气。现在还不是时候。再过一会儿才是扣下板机的时间。

将视线移回全息图屏幕上之后，发现镜头正整个拉远，映照出坐在男人右边的主持人以及坐在左边的另一名特别来宾。

身穿流行电音类型服装的少女主持人用甜甜的声音说：

『人家说全VRMMO里难度最高的游戏便是「Gun Gale Online」，而您不愧是该游戏里的首席玩家，一开口便是如此劲爆的发言。』

『没有啦，一辈子可能只有一次机会来上这个「MMO动向」。当然要把想说的话全说出来啊。』

『太客气了。您应该也会参加这次的「The Bullet of Bullets」吧？』

『那是当然，而且既然要参赛就一定会以夺取优胜为目标。」

男人撩起那夸张的蓝银色长发并傲慢地看着镜头这么说道。这时店里再度响起一片嘘声。

MMO动向虽然不是Gun Gale Online——通称GGO的内部频道，但无论是主持人还是现场来宾都不是真人而是游戏角色。「本周的优胜者」是每个星期都会邀请各个VRMMO游戏的高等级玩家前来接受访问的节目，而这周的来宾则是在GGO上个月所举行的最强者淘汰赛「The Bullet of Bullets（简称BoB）」里获得冠军与季军的两位玩家。

『但是ZED先生……』

听了银发男一连串傲慢的言词后，获得季军的男性终于忍不住开口说道：

『BoB应该都是单人的遭遇战吧。再度对战时不能保证你一定能获胜，我想你刚才那种自己的类型占绝对优势的发言应该是言过其实了吧。』

『不不不，这次的结果就代表全GGO目前的倾向。暗风你是AGI类型，所以我能理解你不想同意我说法的心情……』

名为ZED的优胜者马上如此反驳道。

『……一直到前阵子为止，敏捷度超高且能迅速射击强力实弹枪械的角色确实是最强类型。因为同时回避率也会提升，所以也能弥补耐久力不足的缺点。但是MMO这种游戏与单机版游戏不同，它的平衡度是无时无刻不在改变的。尤其等级型原则上是没办法更换能力值，所以得先预测将来的趋势来分配能力点数才行。在这个等级范围里最强的类型不代表接下来也会是最强。你只要想一下就知道了嘛。今后出现的枪械，装备时需要的STR（筋力）以及命中准确度都会不断上升。不断回避就可以不受伤害通过弹幕的天真想法已经不适用了。我和暗风你的战斗便象征着这种情况。你的子弹被我的耐弹装甲减低了许多杀伤力，反而是我射击的命中率将近七成左右。说明白一点好了，今后已经是STR-VIT（体力）型玩家的时代。』

面对这一连串的批评，那名叫做暗风的男人脸上终于因为悔恨而扭曲了起来。

『……但那是ZED你在大会举行前得到了刚好符合你STR的稀有枪械才能有这种结果吧。你付了多少钱买那把枪？』

『真讨厌，那当然是我自己打怪得到的啊。这么说起来，最重要的能力值或许是运气也说不定呢，哈哈哈……』

「他」一边用充满怨恨的眼神看着全息图屏幕里那个大笑的银发男，一边动起包在服装下的右臂。从腰间的手枪皮套里找到突出来的握把，接着紧紧握住这冰冷又坚硬的金属。时间马上就要到了——确认一下视线角落的时间后，发现还有一分二十秒。

坐在他邻桌的二人组一边喝着啤酒一边这么低声说道：

「哼，竟然敢这样大放厥词。以前到处宣称AGI型最强的不就是ZED本人吗？」

「现在想起来，那可能是他故意引导错误流行的陷阱也说不定……被他给摆了一道……」

「这么说……现在的STR-VIT最强论也是骗人的啰？」

「那到底什么才是真正的最强呢。拼命狂升LUK吗？」

「那你试试看啊。」

「才不要哩。」

两人组说完便嘻嘻笑了起来。这种声音更燃起了「他」的怒火。既然发现被骗了，怎么还能笑得那么开心呢。真让人无法理解。

——但是，你们那愚昧的笑容也马上就要冻结起来了。因为你们即将见到真正的力量与真正的最强者。

是时候了。

「他」无声地站了起来。然后在桌子之间一步步往前进。没有任何人注意到「他」的存在。

愚蠢的群众啊……准备品尝恐惧吧。

「他」嚅嗫完之后便在酒店的中央，也就是全息图面板的正下方停了下来。接着由配备在吉利服腰间的皮套里拔出一把粗糙的手枪。

枪身上闪烁着有如把所有黑暗凝缩在上面的冰冷金属光辉。这把手枪连握把都是金属制，有着直排锯齿状突起的中央部份还有一个星型刻印。外表看起来就是一把很普通并且没什么威力的手枪。

但是这把手枪拥有「真正的力量」。

「他」拉下滑套发出「喀嚓」的声音，装上首发子弹后，以缓慢的动作将枪口对准了上空——也就是巨大的全息图面板。面板里最强的玩家ZED正在大笑着，而枪口就瞄准了他的额头。

「他」维持了一阵子这种动作之后，周围的人也发出一阵感到讶异的声音。

即便是没有PK限制的GGO，在街道里面也是没办法攻击别人。就算可以发射子弹，但别说要伤害到玩家了，就连物体都没办法破坏。

「他」这种无意义的动作让几个人发出了嘲笑声。但是「他」却完全不为所动，只是拿着黑色手枪持续用等边射击法站着。

而面板屏幕里的ZED依然说出充满轻视味道的发言。

ZED的肉身应该躺在现实世界某处，藉由头上的「AmuSphere」联机至MMO动向的虚拟摄影棚吧。所以他当然无法知道Gun Gale Online世界的首都「SBC格洛肯」购物街的某间酒店里，正有个人拿着枪对准电视里的自己。

但是这时「他」张开嘴，用尽所有力气大叫着：

「ZED！虚伪的胜利者啊！现在就是你接受真正制裁的时候了！」

在吓了一大跳的玩家们注视之下，「他」拾起左臂，用指尖依序碰额头、胸口、左肩与右肩，等于是划了一道十字架。

在他放下左手的同时，右手也扣下板机。

滑套整个向后滑动，黄色发射火焰闪烁。接着是尖锐的爆炸声响起。

在酒店有限灯光的微暗下，金属子弹直线飞去——直接命中全息图面板表面并引起小小的光线效果。

但产生的影响也仅止于此，画面中的ZED依然滔滔不绝的讲着话。

这次店内真的涌起了一阵嘲笑。可以听见「好痛哦～」　　「真的发射了耶」这些揶揄的话。但ZED的讲话声盖过这些声音继续说道：

『……所以说，无论是能力值还是技能，最后还是要看玩家本人的能力……』

但声音到此忽然就中断了。

客人们的视线回到面板上。

ZED只是张着嘴，瞪大了眼睛僵在那里。他的手慢慢举起，做出抓住胸口中央的动作。

接着他的身影忽然消失，只剩下由多边形所组成的椅子留在当场。主持人急忙慌张的说：

『哎呀，看来是断线了。我想他马上就会重新联机，请大家稍待片刻……』

但是店里没有任何人在听主持人说话。一片寂静当中，所有人又把视线移回「他」身上。

「他」将对着屏幕的枪收回来，维持水平握枪姿势。接着慢慢转过身体，眼神扫过店里面的玩家。

看完一圈之后，「他」再度高举黑色手枪大叫道：

「……这就是真正的力量，真正的强劲！愚蠢的人们啊，把我的名字随着恐怖牢牢记住吧！」

他用力吸了口气——

「我和这把枪的名字是『死枪』…………『death gun』！」

「他」将手枪放回皮套里，挥动左手叫出选单窗口。

「他」一边按下注销键，一边感受着胜利感与异常强烈的饥饿感。

** 第一章

「欢迎光临。请问是一位吗？」

我对殷勤低头的服务生回答「我跟人约好了」之后，环顾了一下宽广的咖啡厅。

结果店内深处的位子上马上就有人毫不客气地大叫着我的名字：

「喂——桐人，这边这边。」

响着优雅古典音乐的空间里原本只有些轻微的谈笑声，但这时全都停了下来，并以带着责怪的眼神看着我。我只好缩起脖子，快步走向声音的主人。穿着一件旧皮外套与破牛仔裤的我，跟这间大多数都是刚买完东西的贵妇的店内实在是很不搭，因此也让我在心里对把我叫来这里的罪魁祸首感到更加气愤。

如果对方是个妙龄美女也就算了，但很可惜的是，现在对我挥手的是个身穿西装的男性。我直接表现出不满的态度，用力往椅子上坐了下去。

服务生立刻从旁边递上冰水与毛巾，并且将菜单递了过来。当我拿起包着真皮的菜单时，对面位置上传来开朗的声音说道：

「今天我请客，想吃什么尽量点吧。」

「不用你说我也会这么做。」

我没好气的答完之后往菜单上一看，发现连最便宜的「奶油泡芙」都要一千两百日币，虽然差点直接回答综合咖啡一杯，但仔细一想，眼前这人可是坐享高薪的官员，而且他付的交际费也都是国民的血汗钱。觉得这实在太过分的我，极力以平静的声音不断点餐。

「嗯……我要巧克力圣代……还有覆盆子的千层派……然后加上榛果咖啡。」

好不容易说完一长串名称后，才发现我点的食物总共加起来共要二千九百日币。这实在让我很想对他说我吃汉堡和奶昔就好，请把差额用现金补给我。顺带一提，其实我根本不知道自己点的东西究竟长什么样子。

「好的。」

服务生以流畅的动作离开之后，我才松了口气抬起头来。

眼前这个正大口吃着上面有许多生奶油的布丁的男人，名字叫做菊冈诚二郎。他戴着黑框眼镜、顶着一头死板的发型。那张古板纤细的脸孔看起来就像个国文教师，但他其实是个货真价实的国家高级公务员。他所属的单位是总务省综合通信基盘局高度通信网振兴课第二个室，省内的名称是通信网路内假想空间管理课，简称「假想课」。

也就是说这个男人的任务是监视目前呈现无秩序混乱状态的VR世界……亦即国家的探员，但这其实是个很冷门的差事。他本人时常感叹自己的怀才不遇，但老实说，其实我也有同感。

这位被打落冷宫的菊冈先生一脸幸福地将最后一口布丁塞入嘴里后，终于抬起头来对我露出天真的笑容：

「哎呀桐人，不好意思哦，让你大老远跑一趟。」

「真这么想的话就别把我叫到银座来。」

「这家店的生奶油真的是超级美味。我要不要也点个泡芙呢……」

我边用散发着柑橘类芳香的毛巾擦手，边夹杂着叹息说道：

「……还有，你凭什么叫我桐人啊……」

「别这么说嘛。一年前你在医院里醒过来时，我可是最先冲到你身边的人呢。」

——很不幸的是，他说的是事实。从「那个死亡游戏」里脱出之后，最先来到我病房里的人就是担任对策小组国家探员的菊冈。

一开始我当然也对他很是客气，但当我注意到这个男人并不是基于善意才接近我之后，便自然而然变成这种不客气的说话方式了。或者应该说，是他故意让我变成这种样子的——不过这可能是我想太多了吧。

瞄了一眼正在犹豫要不要加点泡芙的菊冈，在心里告诫自己不要又被他拖去蹚什么浑水后，我开口说道：

「……新闻里说相模湾底部发现了某种稀有金属的巨大矿床，相关处室的高官们全都高兴地手舞足蹈了耶。你干嘛还在这里为了一个小小的泡芙而犹豫不决啊。」

结果菊冈抬起头来，眨了好几次眼睛之后才笑着说道：

「哎呀，不论可以拿到多少利润，都轮不到毫无相关的总务省啊。嗯……为了国家预算，我看还是忍耐一下吧。」

看见眼前的官员「啪嚓」一声合上菜单后，我又因为这家伙的炫耀行为而叹了口气。

「那可不可以进入正题了。不用说……应该又是虚拟犯罪的相关搜查了吧？」

「嗯嗯，桐人你真聪明，这样我也省事多了。」

菊冈大剌剌地回答完之后，便从放在旁边椅子上的公文包里拿出极薄的平板电脑。

——没错，总而言之这个男人就是利用我这个日本网络史上最大犯罪「Sword Art Online事件」的生还者来提供情报给他。

某些书籍里面似乎将公安警察的情报来源称为「协力者」或者是「眼线」，然后将给予这些人代价让他们不断提供情报的行为称为「营运」。如果按照这种说法，每次都被蛋糕引诱过来的我就是「菊冈营运之下的眼线」了。

想到这里虽然不是很舒服，但这个男人曾告诉我收容亚丝娜的医院，所以我还欠他一分人情。

如果没有那个情报，我便没办法在现实世界里快速找出结城明日奈。当然也就无法注意到须乡伸之的恶魔计划，更不可能阻止他将亚丝娜占为己有。

所以我才会暂时继续担任菊冈的「线民」。只是决定讲话不再客气，也会尽量点些高价的蛋糕。

这时候我的营运者不知道能不能理解我的心情，只见他用指尖戳着平板电脑然后慢吞吞地说道：

「哎呀，这个啊……最近虚拟空间相关的犯罪件数越来越多……」

「是吗？具体来说呢？」

「嗯……光是十一月接到假想财产的强盗与损毁案件就高达一百件以上。而且VR游戏里面的纠纷引发现实世界里的伤害事件有十三件。里面还有一件是伤害致死……这案件被媒体大肆报导过，我想桐人你也应该知道才对。就是自己将装饰用西洋剑磨利，接着在新宿车站到处挥舞造成两人死亡的事件。呜哇——刀刃有一百二十公分长然后重三点五公斤。竟然能挥得动这种东西。」

「听说是走火入魔的玩家在吸毒之后产生了错乱……光看这一件的话确实是让人觉得罪无可赦。但以整体来看的话这种件数……」

「没错。在全国所发生的伤害事件里面确实只是微不足道，我也不会因此而做出VRMMO游戏会造成社会不安这种短视的结论。但是呢，你之前不也说过……」

「——VRMMO游戏会让人降低在现实世界里伤害人的心理障壁。这点我承认。」

这时服务生再度无声无息地出现，然后在我眼前放下两个盘子与一个杯子。

「请问您的餐点都到齐了吗？」

我点了点头之后，对方便将写着惊人金额的账单翻过来放在桌子角落后离开。我先啜了一口带有榛果香味的咖啡之后继续说道：

「……一部份游戏里面PK行为已经被日常化了，在某种意义上来说，这可以说是在现实世界里杀人时的演习。某些比较极端的游戏里，只要手腕被切到便会喷血，肚子被割到甚至连内脏都会跑出来。听说迷上这些游戏的重度玩家甚至以自杀来取代按下注销键呢。」

听见有「咳咳」的干咳声后往旁边的桌子看了一下，发现两名上流社会的贵妇正狠狠瞪着我。我缩起脖子，小声继续说道：

「每天重复那种行为的话，总是会有出现想在现实世界里试试看的家伙。我也认为必须要想出什么对策来预防这种事情才可以。只不过利用法律规范行不通就是了……」

「真的行不通吗？」

「没错。」

我用金色汤匙慎重地挖起极薄的派皮以及叠了好几层的粉红色奶油，接着将它们放进嘴里。脑袋里不禁涌起这一口要价上百元吧的想法。我一边享受派皮逐渐溶化的口感，一边继续着血腥的话题：

「……除非进行网络锁国。VRMMO本身可以说对线路不会造成什么负担，所以就算国内再怎么取缔也只是造成使用者和业者全部移到海外去而已吧。」

「唔姆……」

菊冈严肃的视线看着桌上，沉默了数秒钟后开口这么说：

「……那个千层派看起来很好吃耶。可以分我吃一口吗？」

「…………」

我随着第三次叹气将盘子推到菊冈面前。这个政府官员高兴地挖走了大概有两百八十日币的份量然后放进嘴里。

「但是呢，桐人啊……我没办法理解为什么要PK呢。与其互相残杀，大家一起合作不是比较好玩吗？」

「……你也是ALO的玩家，所以多少有点了解吧。早在完全潜行技术出现之前，MM的基本就已经是互相掠夺了。说得更极端一点，我认为没有结局的网络游戏让玩家持续玩下去的最终原动力就是……追求优越感的冲动本能。」

「哦？」

菊冈一边嚼着千层派一边扬起眉毛希望我做进一步的说明。我虽然在内心咒骂着「为什么我得向你说明这种事情呢」，但还是带着要给他点颜色瞧瞧的心理这么说道：

「……不只是游戏这样而已吧。我想你也应该承认，这个社会的基本构造就是想出人头地对吧？你应该也有这样的经验才对。就算同样在总务省，但总是会嫉妒因为大学比你好就靠着派系力量快速升职的家伙，相反的，看见层级比你低的人对你鞠躬哈腰就会觉得飘飘然对吧。就是因为你的自卑感和优越感取得了平衡，所以你才能在这里悠闲地吃着蛋糕。」

菊冈吞下千层派之后苦笑着说：

「你真的是有话直说耶。那桐人你自己又怎么样呢，有取得平衡吗？」

当然我自己也有一大堆自卑感，但我完全不想对这个男人吐露。于是我装出一副平静的表情回答：

「嗯……至少我还有个女朋友。」

「说得也是，这一点我就真的是羡慕得要死了。下次在ALO里也介绍女孩子给我认识嘛。那个风精灵的领主是我喜欢的类型。」

「话先说在前面，你搭讪的时候要是说我是高级官员的话，可是会被砍死的哦。」

「我还真想被她砍一次看看呢。然后——？」

「然后在现实世界里要得到优越感其实还满困难的。要非常努力才有可能获得机会。比如说要拿到好成绩、要在运动方面有所表现、要让自己变得更帅气、更可爱……这些事情都得花上相当多的时间与力气，而且还不一定能得到结果。」

「确实如此。我当初拼命用功但还是考不进东大。」

看见边笑边这么说道的菊冈后，已经懒得吐槽他的我便马上接下去继续说道：

「这时候MM（注：大规模在线角色扮演游戏。）就是最好的良药了。这东西只要牺牲现实世界里的时间就一定可以变强，也可以得到稀有的道具。当然这也算是一种努力，但终究还是游戏。怎么样还是比用功与锻炼筋骨来得轻松多了。只要穿上高价的装备、显示出自己的高等级然后在大街上走动，弱小玩家们的羡慕眼神就会集中在自己身上……或者是说可以有这样的错觉。然后到练功场去时，可以用压倒性的力量解决怪物，解救遭受危机的小队。而这样也可以有被感谢、被尊敬的——」

「错觉？」

「……不过这只是我个人的看法。MMO游戏当然也有其他要素。但是以前也有过以交友为主要目的的网络游戏，却没有一个像MM那么成功。」

「……原来如此，也就是说这样的游戏没办法满足优越感啰？」

「没错。接下来——VRMMO游戏便出现了。而这种游戏走在路上可是能够实际感受到别人的眼神。再也不用隔着荧幕凭空想象了。」

「嗯嗯。确实如此，你和亚丝娜并肩走在世界树城市时每个人一定都会看你。」

「……你也是有话直说耶。总之只要花时间在VRMMO游戏上，无论是谁都可以得到优越感。而且这种感觉比成绩好、足球踢得棒、拥有大量金钱都要简单且原始，是属于人类本能的一种。」

「……那也就是……？」

「也就是『实力』。无论是物理或是肉体上的实力。那种能够用自己的手破坏敌人的感觉就跟毒品一样会让人上瘾。」

「…………『实力』……也就是最大的『力量』吗……」

菊冈以缅怀过去的口气接着说道：

「……每个男孩子都会有这种憧憬……像看了格斗漫画之后便与主角做出同样的修行等等。但大部分都会马上知道事情没有那么简单而把梦想转换到其他更实际的事物上……原来如此——如果是在VRMMO里的话，就能再度见到那个梦想了，我说得对吗？」

我点了点头，接着用咖啡湿润一下难得因为讲太多话而干枯的喉咙。

「没错。一部分格斗游戏为了追求真实性，甚至和真正的格斗技流派互相合作呢。」

「哦？怎么个合作法？」

「总之呢……就是在游戏里培育某个角色，最后便能够成为某某流空手道或是某某流拳法的达人。舞台也完全重现新宿或是涩谷等实际的地点，然后玩家能够在里面凭自己的双手痛扁那些不良分子。不过……游戏里面当然无法教导格斗家应该有的精神素养。所以完全沉浸在这种游戏里的玩家，就有可能会想在现实世界里使用由游戏角色那里学来的空壳技巧……最后也真的就使用了。我必须很痛心地承认确实有这种可能性存在。」

「是这样啊……VRMMO世界里的『实力』侵蚀到现实世界了吗？那个……我说桐人啊……」

菊冈再度很严肃地看着我。

「那真的仅止于心理上的侵蚀而已吗？」

「你这是什么意思？」

「不只是对暴力的心理障壁降低或者可以取得伤害人的知识与技术而已……实际上也可以给玩家真实世界里的肉体某种物理上的影响……会不会有这种可能性呢？」

这次换成我开始思考了起来。

「……你的意思是，比如刚才所说在新宿挥舞着三点五公斤重西洋剑的男人，他的肌肉会因为受到游戏世界的影响而变强壮……是这样吗？」

「嗯，没错。」

「嗯……完全潜行机器对神经系统的影响好像才刚开始被研究而已。基本上那只是躺在床上而已，基本体力应该会下降才对，不过如果是火灾场的蛮力的话又如何呢……说起来——这方面的事你应该比我清楚才对吧？」

「我到大脑生理学的医生那里去问过了，但完全听不懂他在说什么。刚才讲了那么多……其实这次约你见面的主题就是这个。你看一下这边……」

菊冈操纵平板电脑，然后把它朝我移了过来。

接过来后一看，马上就见到液晶屏幕上有一个男人的脸部照片与地址等个人资料。戴着银框眼镜的男人有着一头杂乱长发，脸颊与脖子上有厚厚的脂肪。

「……这谁啊？」

从我这里拿回电脑后，菊冈便用手指开始操纵了起来。

嗯……上个月……十一月十四日那天。东京都中野区某栋公寓里面，正在打扫的房东闻到了异臭。他按了发出臭味的房间对讲机但没有响应。而且里面也没有人接电话。但是房间里的电灯却还亮着。于是房东便解除电子锁进到房间里面，结果便发现这个男人……二十六岁的茂村保已经死在里面。之后分析出这时他已经死了五天了。房间里虽然很乱但不像是被搜过的样子，而遗体就躺在床上。然后头上……」

「戴着AmuSphere吗……」

其实我自己房里也有一台这种机器，这时我脑海里一边浮现这由两个圆环连结起来的头盔状完全潜行机器一边这么说道。而菊冈听见之后也点了点头。

「没错。房东马上联络家属——由于是相当怪异的死法，所以立刻进行了司法解剖。结果死因是心脏衰竭。」

「心脏衰竭？也就是心脏停止跳动吗？为什么停止跳动？」

「原因不明。」

「…………」

「由于已经死亡了一段时间，而且也不像是他杀，所以并没有进行精密的解剖。只是知道他几乎已经两天没有进食，一直联机在游戏里面。」

我再度皱了一下眉头。

老实说这种案例其实很常见。因为即使在现实世界里不吃任何东西，也只要在里面吃假想食物就会有虚伪的饱足感，接着就能够再撑好几个小时了。对被称为「废人级」的重度玩家来说，除了可以省下饭钱之外还能增加游戏时间，所以别说是一天了，许多人根本是两天才吃一次饭。

但是持续这种生活习惯的话，一定会对身体产生不良影响。他们几乎都有营养失调的毛病，要是发作起来晕倒又刚好是一个人住的话，就会这样直接死亡……但其实这也不是很稀奇的事情。

我闭上眼睛帮茂村氏悼念了一下之后，开口说道：

「……这确实是很可怜，但……」

「没错，虽然悲惨，但最近已经常可以见到这种事发生了。所以这宗怪异的死亡案件也没有成为新闻，而家人也因为想隐瞒是在游戏当中忽然死亡而不愿多谈。在某种意义上来说，这也是VRMMO所造成的死亡侵蚀……」

「……你不是为了让我听这种普通的论点才把我叫来的吧？这案件里有什么特别的地方？」

听见我的问题之后，菊冈便瞄了一下电脑然后回答：

「这位茂村先生的AmuSphere里面只有安装一款游戏而已。『Gun Gale Online』……你知道这款游戏吗？」

「那当然了……那是日本唯一有『职业』玩家的MMO游戏。虽然我没玩过就是了。」

「他在Gun Gale Online……简称GGO里面似乎是等级相当高的玩家。还在十月所举行的最强者决定战里获得优胜。角色的名称是『ZED』。」

「……那他就是在登入到GGO里面时死亡的吗？」

「不，好像不是。当时他用ZED这个角色，参加了『MMO动向』这个网络电视台的演出。」

「啊啊……MM0动向的『本周的优胜者』吗。对了，前阵子我好像也听说因为特别来宾断线而中断了节目……」

「我想就是那时候了。他在演出当中心脏突然出现了毛病。根据纪录可以知道发生这件事情时是几分几秒。但接下来就是未确认情报了……有玩家在部落格里写着在他发作的时候，GGO里也发生了一件很奇怪的事。」

「GGO内部也有播放MMO动向吧？」

「嗯嗯。在酒店里面可以看到。」

「GGO世界的首都，『SBC格洛肯』的酒店里也有播放。而发生问题的那个时间点，似乎有一名玩家出现奇怪的举动。」

「…………」

「据说他对着电视上的ZED大叫什么接受制裁吧、去死吧等等的，然后还对着屏幕发射子弹。看见这种景象的玩家偶然录下了声音档，然后把它上传到影片网站上。档案里面也记录着日本标准时间……嗯……对电视射击是在十一月九日下午十一点二十分两秒。而茂村他是十一点二十分十五秒时突然从节目里面消失的。」

「那是偶然吧……」

我一边将另一盘甜点拉过来一边这么说道。

用汤匙在茶色筒状物上挖了一口之后将它放进嘴里。结果马上就被它冰凉的程度吓了一大跳。原本以为是蛋糕的东西结果竟然是冰淇淋。尽力抑制甜味的浓密巧克力在嘴里散开，将菊冈的话题所带来的苦涩感给掩盖过去。

当我将圣代的三分之一给送进胃里之后，才继续说道：

「如果是GGO的顶尖玩家，那一定会比其他MMO遭受到更多的嫉妒与怨恨。要枪击现实世界里的本人是需要很大的勇气，但在游戏里对他开个枪应该也不是什么大不了的事吧。」

「嗯，但是另外还有一件类似的事件。」

「…………什么？」

这次我拿着汤匙的手终于停下动作，抬头看着还是面无表情的菊冈。

「这次是在十天之前的十一月二十八日。地点是琦玉县琦玉市市大宫区某处，这次也是从两层楼公寓的房间里发现一具尸体。报纸的业务员发现电灯没关却没有人响应，觉得里面的人假装不在而感到很气愤，一转门后发现没上锁。入门一看便见到有个戴着AmuSphere的人躺在床上，同样也发出异臭……」

这时刻意传来的「咳咳！」声打断了我和菊冈的对话，往旁边一看，结果是刚才那两名贵妇用类似眼球妖怪的邪眼瞪着我们。但菊冈这时候却发挥了令人意外的胆识，他只是对她们微微点了点头然后继续说道：

「……嗯，关于尸体的详细情形我就省略不谈了，只是这次的死因也是心脏衰竭。名字嘛……这个也跳过好了。简单来说死者是二十一岁的男性。而他也是GGO的顶级玩家。角色名称好像是……『薄盐鳕鱼子』？不知道正不正确就是了。」

「以前SAO里面有个叫『北海鲑鱼卵』的家伙，说不定是他的亲戚。那个鳕鱼子也上电视了吗？」

「没有，这次是在游戏里面。由AmuSphere的纪录文件里得知断线时间是在尸体被发现的三天之前，也就是十一月二十五日下午十点整。而死亡推定时间也是在那个时候。他当时好像正在格洛肯市的中央广场出席中队——也就是公会——的集会，当他在讲台上高谈阔论时，被闯入集会的玩家给击中了。由于是在街道里面所以没有受伤，但就在他愤怒地准备逼近枪击者时便忽然断线了。当然这也是写在网络留言板上的情报所以无法确定真实性……」

「发动攻击的玩家与『ZED』时是同一个人吗？」

「我想应该是吧。他也在讲出制裁、力量等话后报上了与上次一样的角色名称。」

「……什么名字……？」

菊冈看着平板电脑．皱起眉头说道：

「『死枪』……还有『death gun』。」

「death……gun……」

——就是死枪的英文直译吗。

将汤匙放在空盘上之后，我在口中重复呢喃了好几次那个名词。就算是再怎么搞笑的角色名称，也还是会创造出该角色的一部分印象。死枪这个名字最先让人联想起的是冰冷的黑色金属。

「……ZED与薄盐鳕鱼子确定都是死于心脏衰竭吗？」

「你的意思是？」

「脑部……没有任何损伤？」

一听见我这么问，菊冈马上就像了解我想说什么一样微微一笑。

「我也很在意这件事。问过负责司法解剖的医师之后，他表示脑部没有出血或者是血栓的异常现象。」

「…………」

「而且NERvGear那时候……啊，我可以说这件事吗……？」

「没关系。」

「……NERvGear在让使用者死亡时，是利用几乎能让信号组件烧断的高出力微波来破坏脑的一部分，但AmuSphere在设计上原本就没办法发出那么强力的电磁波。开发者断言那个机械只能用相当平稳的微波将听觉或视觉这些五感情报送进脑部。」

「你已经连制造商都问过了吗？菊冈先生你动作倒是很快嘛……这种偶然与谣传所创造出来的消息怎么能让你这么在意呢？」

当我凝视着菊冈眼镜深处的细长眼睛时，他脸上一瞬间没了表情，然后马上又咧嘴一笑：

「因为我这个被打落冷宫的人每天都很闲啊。」

「那下次就陪我一起攻略艾恩葛朗特的最前线吧。尤金老大称赞你有成为优良魔法师的资质呢。」

老实说我也不认为这男人真像他的外表与行事作风一样是个笨蛋官僚。他在ALO里制作了一个角色，并不是真的对游戏有兴趣，而是这样做比较容易收集VR世界里的情报。以前拿到的名片上确实写着总务省这种头衔，但其实我觉得这一点很可疑。他真正的所属说不定是与国家治安有密切关系的单位也说不定。

但先不论这件事，当现在的「假想课」还是「SAO事件受害者救出对应本部」时，就是这个男人到处奔走才能确立将所有玩家收容到医院里去的体制。而且再加上亚丝娜那件事欠他的人情，也让我目前是以六分好意四分警戒的态度来面对他。

不知道菊冈晓不晓得我目前的心情，只见他一边搔着后脑勺一边不好意思地笑了起来。

「哎呀，背咒文是还可以，只不过咏唱我就不行了。我从以前就不会说绕口令……话说回来，这件事我也认为有九成是偶然不然就是谣言。所以从现在起我要说的就是假设问题了。桐人——你觉得有没有可能因为游戏内部的枪击而让玩家本人产生心脏衰竭呢？」

菊冈这句话让我产生了某种想象，于是我轻轻皱起了眉头。

穿着一身黑而且看不见脸的狙击者……朝着虚空扣下手枪的板机。而发射出去的是黑色幻影子弹。子弹贯穿了假想空间的障壁，侵入数据错综复杂的网络世界。接着子弹又数次弯曲着直角由路由器经过路由器，再由服务器跳过服务器而不断往前突进。最后在某栋公寓的房间里，藉由设置在墙壁上的网络链接器实体化，然后射进躺在床上的男人心脏……

轻轻摇头甩开这种妄想后，我便竖起一根指头然后说：

「我觉得这根本不可能……假如说那个……叫做『死枪』的攻击者真对『ZED』与『薄盐鳕鱼子』的AmuSphere传送了什么信号……」

「唉唷，这里就是重点了。可能办得到这种事吗？」

「嗯……这是假设送出去的不是致命性力量而是正常的感觉信号……你还记得前阵子引起骚动的『想象力病毒』吗？」

「啊啊，那个吓人邮件的事件吗？」

所谓的『想象力』，是由个人所开发出来的AmuSphere专用邮件软件。用户可以潜入软件生成的假想空间，然后对着相机发出要传递的讯息，接着软件将会将文件压缩成邮件形式。收到邮件的人只要再生档案，眼前就会出现寄件人的虚拟形象然后讲出讯息，不久之后又进化成可以添加许多影像、音乐，最后甚至连触感都可以藉由邮件来传送，结果引发了一阵大流行。

但是不久之后软件被人发现安全漏洞，于是利用这个漏洞的病毒邮件便开始到处横行并且引起了骚动。收到邮件后当你潜入假想空间时，不论你在哪里邮件都会强制性被打开，然后眼前便会出现一大票不是色情就是血腥的吓人影像与声音——

当然马上就有修正档案被上传，事件也开始逐渐沉静下来……

「——几乎所有AmuSphere使用者都安装了『想象力』软件。如果有未知的防护漏洞，让人可以得知对象的邮件信箱或是IP位置的话……」

「我懂了……只要事先设定寄件时间，然后在枪击的同时寄送某种讯息——理论上来说这是可能的。」

菊冈将两手瘦巴巴的手指合起来，然后把下颚靠在上面并点了点头。

「那么我们就当他成功这么做了。但是——传送出去的不是带有致命诅咒的子弹，而是十分正常的感官刺激。」

「也就是能让心脏停止的触感……或是味道、气味……景象、声音……等等。我们一个一个来考虑吧。首先是触觉，也就是皮肤的感觉。」

我停止说话，用右手的食指划过左手手掌。然后回想起刚才原本以为是巧克力蛋糕但却是冰淇淋时的惊讶感。

「……如果传送非常寒冷的感觉呢？会不会引起像忽然跳进一大盆冰水里所引起的心脏麻痹？」

「嗯……跳进冷水里而引起心脏停止，是因为温度差的冲击造成全身血管收缩，进而对心脏造成负担……应该是这样才对吧？」

「——那这条路线也不行吗？就算脑部有了假想的冰冷感，也不会对手脚的毛细孔发生影响吧……」

「那你觉得这个情况如何……」

这次换成菊冈一边搓着手一边说道。或许是我想太多了吧，但总觉得他看起来很高兴。

「很小的虫子……跟甲虫比起来，可能线形虫类会比较适合。就像被人丢进满是毛虫或是蜈蚣的洞穴里那样的触感。当然也附上影像。呜哇，光是想象我就起鸡皮疙瘩了。」

「…………」

虽然不愿意但我也随着想象了一下。

悠闲走在练功场里时，脚底下的地面忽然消失，整个人跟着掉进深邃的洞穴里。而那里面有一大堆细长的生物蠕动着，它们除了爬满你全身之外，还从袖口或是衣领钻进衣服里面……

「这确实让人起鸡皮疙瘩……」

我摩擦着双臂并摇了摇头。

「但是这种程度的陷阱，在『想象力病毒』里面就有过了。像是忽然有巨大毛虫或是超大水母从头上掉下来。但我想没有任何人因此而心脏停止……说起来在登入VRMMO时，原本在无意识中就已经做好面对突发状况的心理准备了。因为练功场里可能突然就有怪物出现啊。如果这样心脏就停止的话，那根本就不用玩游戏了。」

「说得也是。」

菊冈耸了耸肩，拿起杯子后轻轻晃了一下。

「那接下来就是味觉与嗅觉了……像是嘴里忽然出现恐怖的恶臭什么的……比如说把kiviak的味道在嘴里再生。遭到这种攻击的人当然会马上想吐。然后这种呕吐的反射性动作直接影响到真正的肉体……」

「这样的话就不是心脏衰竭而是因为呕吐物窒息而死了吧？还有那个kiviak到底是什么？」

问完这个问题后菊冈眼里马上闪烁着喜悦的光辉，让我开始感到非常后悔。这男人最喜欢讲些恶心的兴趣了。明明是个社会精英却还交不到女朋友，可能就是因为这个缘故吧。

「哎呀，你不知道kiviak吗？那是爱斯基摩人的食物，首先呢在刚进入夏天时要抓些叫做海燕的候鸟，然后把它们塞进挖空海豹内脏后制成的皮囊。接下来将其放置在冰暗的地方经过好几个月之后，海豹的油脂便会渗入海燕里，然后整个发酵，或者应该说是腐败吧。这时候才把鸟拿出来，享受已经溶化为巧克力状的软绵绵内脏。听说味道似乎比鲜鱼罐头还要臭，不过一旦习惯之后就会上瘾的样子……」

「喀当！」一声巨响让我们往旁边看去，结果发现隔壁桌的两名贵妇正遮着嘴巴站起来落荒而逃。我重重叹了口气，打断菊冈的话开始说道：

「我有机会去格陵兰的话会试试看的。还有那个什么罐头的就不用说明了。」

「唉唷，真的不用吗……」

「别一脸遗憾的样子。再怎么样也不可能因为吃到臭气冲天的食物便心脏衰竭吧。讲下一个吧。接下来应该是影像……但是……」

我用咖啡的芳香消除菊冈所讲的臭味话题后才继续这么说道。

「与刚才毛毛虫的时候一样，要用带有某种主题的影像让人心脏停止我觉得还是有所困难，不论那是多么恐怖或是残酷的影像。而且这根本不可能调查得出来吧。」

「唔……你刚才说某种主题对吧？」

「嗯嗯。这是我出生之前就已经发生的陈年往事，所以知道得不算清楚。这事件好像是小孩子看着电视上播放的动画，结果全国就同时有好几个人昏倒了。」

「你说那个啊——我那时在念幼儿园，所以我当时有看见那个节目。」

菊冈很怀念似的笑着继续说：

「嗯……那应该是红色与蓝色光芒连续闪烁的画面，结果引起了某些儿童的病状发作。」

「应该就是那个了。跟那时候一样，如果是传送猛烈的闪烁光芒影像到他们面前的话呢。普通人在这种时候应该会马上闭起眼睛。但传送到脑里的话就算闭眼睛也没用吧。也有可能就是这样而引发了某种休克症状。」

「嗯，确实如此。」

菊冈点了点头，但马上就又摇着头说：

「——但是呢，这个问题当初在开发AmuSphere时好像就有被讨论过了。结果好像设置了应该说是安全装置还是限制器的东西。AmuSphere没办法产生固定振幅以上的信号影像。」

「喂——你啊……」

我这次用带着百分百怀疑的眼神瞪着菊冈的脸。

「你是不是早就把这些可能性全部都调查过一边了，总务省的精英们绞尽脑汁想过的问题，应该不用再来问我的意见吧。你到底想做什么？」

「哎呀哎呀，你别这么说嘛。桐人你的想法给了我很大的刺激与参考唷。而且我很喜欢和你说话啊。」

「我可不喜欢。至于听觉嘛——如果已经有限制器的话，听觉应该也会被纳入规范吧。那事情就到此结束了。结论——游戏内的干涉要让玩家心脏停上是不可能的事情，『死枪』他的枪击和那两个人的心脏衰竭只是偶然同时发生。我要回去了。谢谢你的招待。」

我有预感再继续谈下去准没有什么好事，于是快速道完谢之后便从位子上站起来准备离开。

但是菊冈却急忙叫住我。

「哇，等等嘛。接下来才要进入主题。你可以再点一道蛋糕没关系，拜托再听我讲一下吧。」

「…………」

「哎呀，桐人你帮我做出这个结论我就安心多了。我也跟你有同样的看法。这两件死亡不是因为游戏内的枪击事件所造成。因此呢，我要在这里拜托你——」

虽然我这时深深觉得自己不应该来的，但还是继续听他说了下去。

「可不可以帮我登入Gun Gale Online，然后接触那个自称『死枪』的男人……」

说完后这个公务员露出天真无邪的笑容，但我却用最冰冷的声音对他说：

「什么接触？你就老实说吧，菊冈先生。你是要我去让那个『死枪』射一下看看对吧。」

「没有啦，哈哈哈。」

「才不要哩！如果真有个三长两短怎么办！你就自己去让人家射中然后心脏衰竭吧！」

我说完后便再度站起身来，这时菊冈用力抓住我的袖子。

「刚才我们两个不是一致同意没有那种可能性了吗？而且这个『死枪』在挑选目标上似乎有很严格的坚持。」

「……坚持？」

我只好再度坐下然后回问道。

「YES。『死枪』在游戏里攻击的两个人『ZED』与『薄盐鳕鱼子』都是有名的顶级玩家。也就是他应该不会攻击没有实力的人。我的话不论花多少年都不会变强的。但是如果是连茅场都承认是最强的你……」

「我也没办法！GGO不是那么简单的游戏。里面有一堆职业玩家啊。」

「就是这个，你刚才也说过的职业玩家是怎么回事？」

我发现自己正被菊冈拖入这蹚浑水当中，但还是不情不愿地开始解释起来。

「……职业就是职业啊。那是一群靠游戏来赚钱的家伙。Gun Gale Online是所有VRMMO里唯一采取『游戏货币转换现实货币』系统的游戏。」

「……哦？」

即使菊冈他身为探员，但在游戏方面的知识却还是比不上我，所以我想他这次的疑问应该是真的。

「简单来说，就是可以把游戏里赚到的钱兑换成现金。正确一点讲的话应该是换成电子货币而不是日币，不过现在已经可以用电子货币进行所有付款，所以也是一样。」

「……但是这么做还能赚钱吗？营运业者应该也想要获利吧？」

「当然不是所有玩家都能赚到钱。这和柏青哥以及赌马一样。每个月的联机费需要三千元。这在VRMMO里算是相当高的价位。而玩家一个月平均能兑换的金额也不过是十分之一……大概只有几百元而已。但是……应该说它带有很大的赌博性质在吧……偶尔会有得到相当稀有道具的家伙出现。当他们把那种道具在游戏内拍卖掉，然后把得到的金钱经过转换，大概就可以得到数万或是数十万电子货币。只要听到有这种好事，就会觉得有哪一天也会轮到我对吧。所以说整个游戏内部就像一座巨大的赌场一样。」

「唔姆，原来如此……」

「而那些职业玩家就是每个月都能够赚取固定收入的家伙。顶尖玩家听说每个月都能赚到二十万到三十万的样子，以现实世界的基准来看或许没什么了不起……但已经足够过一般的生活了。也就是说这些家伙是从广大的玩家群所付出的联机费里赚取自己的收入。我刚才说GGO的顶级玩家比其他游戏更容易遭人嫉妒就是这个道理。因为他们就像利用国民的税收来吃贵死人蛋糕的公务员一样。」

「桐人你讲话还是这么严厉。不过我就喜欢你这种个性。」

我不理会菊冈装傻的发言，准备将整个话题做个结束。

「——就因为这个理由，所以GGO的高等级玩家灌注在游戏上的时间与热情，可以说让其他MMO玩家完全无法与之相比。像我这种没有任何知识的家伙，就算闯进去也没有人会理我。而且说起来那款游戏就如同它的名字一样是以枪械为主……而我最头痛的就是那种飞来飞去的道具了。抱歉，你还是另请高明吧。」

「等等嘛，我没有别人可找了啊。你是我唯一在真实世界里可以取得联络的VRMMO玩家。而且……如果你认为面对职业对手负担太重了，那你也把这个当成工作不就得了。」

「……啥？」

「我会以协助调查费的名义来支付你报酬。就跟……GGO顶尖玩家每个月所赚取的费用一样好了。就这个价钱——」

看见菊冈竖起三根手指的动作后——

老实说我不禁有点头晕目眩。只要有这份收入，我就可以组一台最新24核心级CPU的电脑了。但我心里同时也产生一个疑问。

「……这就有点奇怪了，菊冈先生。你为什么这么看重这件事？这无疑是穿凿附会的谣言，不然就是网络上常有的神秘现象话题。因为心脏麻痹的两人没有出现在游戏里面，才会开始有这种传说出现的。」

听见我直截了当的问题后，菊冈用细细的手指将眼镜戴好，顺便也隐藏住自己的表情。他一定是在考虑要对我透露几分真话几分假话。真是个滑头的家伙。

「——其实呢，是我的上头相当在意。」

开始讲话的高级公务员脸上又出现了常见的笑容。

「完全潜行技术对现实世界的影响，可以说是目前各个领域里最受瞩目的课题。除了对社会、文化有莫大影响之外，生物学上也正热切讨论着假想世界究竟会对人类生存方式产生什么样的影响。如果结论是有危险性的话，应该又会有制定法律来加以规范的动作出现吧。事实上SAO事件当时就已经几乎要提出这样的法案了。但是我——应该说假想课认为不应该让这股潮流开倒车。一方面也是为了你们这些享受VRMMO游戏的新世代着想。因此在这件事引发不必要的议论，进而被促进规范派拿来利用之前，我们想先了解整件事的正确内容。当然如果只是谣言那是最好了。但我们还是希望要有证据。这个理由不知道你能不能接受呢——」

「……我就把它解释为你了解VR游戏世代年轻人的理念与善意吧。但如果真的那么在意的话，怎么不直接和营运企业联络呢？只要分析纪录文件，马上就能知道枪击『ZED』与『鳕鱼子』的人究竟是谁了。就算游戏内的登录数据全部都是假的，只要用IP位置来询问网络业者，应该就能知道本名与地址了吧。」

「——我的管道再多，也没办触及太平洋的另一端啊。」

苦着一张脸的菊冈这次散发出真正的焦躁感。

「Gun Gale Online的开发•营运企业『ZASKAR』……这个来历不明的团体把服务器设置在美国。虽然游戏内对于玩家的支持做得相当完善，但现实世界里别说是公司的所在地了，就连电话号码与电子信箱都未公开。真是的，自从那个『种子』公开之后，奇怪的VR世界就如同雨后春笋般冒了出来？」

「是这样吗……」

我听了之后只是耸了耸肩膀。知道VRMMO开发支持程序套件「The Seed」由来的就只有我和艾基尔而已。同样的，一般社会大众到现在都还以为，突然出现在新生Alfheim Online里的浮游城艾恩葛朗特，目前仍然沉睡在已经消失的ARGUS所管理的旧SAO服务器里面。

「因此呢，想要得知事情的真相，就只有直接到游戏里面试着和对方取得接触了。当然为了以防万一。我们会准备好万全的安全措施。桐人你只要到我们准备好的房间里进行潜行就可以了，如果屏幕监控中的AmuSphere出力有了什么异常，我们马上就会切断联机。我不会要你去让死枪射射看，只希望你能够用亲眼见到的景象来判断究竟是怎么回事就可以了。你愿意尝试吗——？」

回过神来时，才发现目前已经不是我能够摇头拒绝的状况了。

真不该来赴约的……虽然我深深感到后悔，但同时也开始对这件事产生了一点兴趣。

由假想世界里干涉现实世界的能力……如果这真的存在的话，会不会就是茅场品彦所追求的世界改变的开端呢？三年前冬天开始的那个事件，难道到现在还没结束吗……？

如果真是这样，那我应该有见证这道洪流去向的义务才对。

我用力紧闭双眼，深深呼了一口气之后才这么说道：

「……好吧。虽然很不愿意陪你蹚这种浑水，但我就尽量试试看吧。不过我不知道能不能顺利遇上那个『死枪』哦。说起来我根本就怀疑他是否真的存在。」

「啊啊……关于这个嘛……」

菊冈那无邪的脸笑了一笑。

「我刚才不是有说过吗？最初的枪击事件里，当时在现场的玩家录下了声音档。我把文件压缩之后带过来了。这就是『死枪』的声音。你听一下看看吧。」

面对朝我伸出无线耳机的菊冈，我这次真的在心里咒骂着「最好你的心脏也停止」然后又狠狠瞪了他一眼。

「谢谢你的热心哦……」

接过耳机并将它塞进耳朵里后。菊冈便用手指在屏幕上按了一下。马上我耳朵里就听见了喧嚣的声音。

接着忽然间声音完全消失。一道尖锐的声音划破紧绷的沉默。

『这就是真正的力量，真正的强劲！愚蠢的人们啊，把我的名字随着恐怖牢牢记住吧！』

『我和这把枪的名字是「死枪」…………「death gun」！』

那是道不太像是人类，而且带着金属感的声音。

话虽如此，但我还是强烈感受到叫声是由活生生的玩家所发出来。因为声音的主人不是在扮演什么角色，而是真正散发出渴望杀戮的本能性冲动。

** 第二章

由千代田线大手町车站C10号出口来到地面上。接着往左手的手表看了一眼。

距离约定好的下午三点还有五分钟以上。当结城明日奈准备将手放下来时，忽然看见表面上显示日历的小窗子。

二〇二五年十二月七日，星期天。

其实今天也不是什么特别的纪念曰。但是明日奈的胸口隐约含有某种感慨的心情。她抬起头，开始在永代大道上朝着皇居正门走去，嘴里还无声地呢喃着：

——已经快要一年了……

当然前面还省略了「回到这个世界来」这句话。

明日奈先是被关进钢铁浮游城，接着又被转换到树上的鸟笼里，她是今年一月中旬才回到现实世界中的。假想世界里的记忆虽然逐渐变成回忆，但她偶尔还是会对自己生活在现实世界这件事感到不可思议。

整齐排列在宽广步道上的石材。行道树被冷风吹动的树梢。把脸埋在大衣衣领或是围巾里的往来行人。还有缓缓走在人群当中的明日奈本身。

这些全部都不是由数字码所建构的3D对象，而是真正的矿物、植物与生物。

但是「真实」的定义又是什么呢？如果是原子或分子的集合体，那假想空间里的多边形应该也是一样吧。因为那些存在也是停留在服务器记忆装置内的电子。只不过是基本粒子的不同而已。

这么一来就是可逆性的问题了吧。存在于现实世界里的东西不论是生物还是非生物，一旦被破坏之后就绝对不可能复原。但如果是在假想世界里的话，就能够很简单地将物体的每一个字节都完全重现。

…………不对。

也不是所有物体都能重现。那个世界——艾恩葛朗特里确实存在着永远无法挽回的失去。明日奈在浮游城生活的两年里所接触、感觉、得到以及失去的全都是不容质疑的「真实」。

这样的话……

「……现实世界与假想世界的分别……到底在哪里呢……」

无意识之中嚅嗫出这个问题——

「情报量的多寡啊。」

结果旁边马上有人这么回答，明日奈因此整个人轻轻跳了起来。

「哇、哇？」

急忙将视线往旁边看去后。发现那里有张正眨着眼睛的少年脸孔。

眼前的少年有着略长的浏海，以及纤细中带着一点敏锐的容貌。身上穿着没有图案的黑色毛线T恤以及黑色皮外套，下半身则是一条褪色的牛仔裤。

由于这副模样与他过去所使用的角色实在太过相像，让人觉得看不见他背后的长剑剑柄是件很不自然的事情。明日奈用深呼吸溶化自己心底深处涌起的甜蜜痛楚，然后笑着这么说道：

「……吓我一跳。怎么突然就出现了，你是用了转移水晶吗？」

结果少年——桐谷和人脸上露出了一个明显的苦笑。

「哪有突然出现。我只是准时在约好的地点出现而已吧。」

「咦……」

听他这么一说之后，明日奈才看了一下四周围的环境。

眼里映入午后柔和阳光照耀之下的步道以及闪闪发亮的壕沟水面。不远前方的桥连结着戒备森严的大门，这里确实是和人指定的皇居大门前面。自己一边想着事情一边向前定，不知不觉间就来到目的地了。

明日奈脸上的微笑变成不好意思的笑容，轻轻耸了耸肩然后说：

「啊哈哈，我怎么好像进入自动操纵状态了。嗯……还是要先打声招呼……午安啊，桐人。」

「这样太危险了吧，现实世界里可没有导航机能唷。午安啊……亚丝娜。」

互相打过招呼后，和人忽然间眯起黑色眼睛，一直盯着明日奈。

「怎……怎么了，为什么突然……」

觉得自己是不是有哪里不对劲的明日奈将双臂在身体前面重叠起来这么问道。结果和人急忙摇头，然后吞吞吐吐的说：

「啊，没有啦，那个……就觉得这身衣服很适合你，让人回想起以前的日子……」

「咦……？」

明日奈不由得低头看了一下自己的服装，两秒钟之后她就明白桐人所说的意思了。

今天是她今年冬天第一次穿上大衣。而那是一件白色的粗花呢大衣。大衣下面则是象牙色的毛线衫与红色菱形图案的裙子。

换言之整体色彩都是过去公会「血盟骑士团」的指定颜色。现在回想起来，在艾恩葛朗特里时，她几乎每天都穿着红色与白色构成的骑士服。和人应该是想起那时候的事情了吧。

用指尖碰了一下自己左腰附近后，明日奈再度微笑着说道：

「……是啊，不过没有细剑就是了……说起来——桐人你今天也是穿得一身黑啊。」

明日奈这么一说，和人也不好意思的笑着回答：

「我也没有双剑。哎呀……平时总是特别注意不要同时穿黑色的衣服，但今天早上小直把我的衣服全拿去洗了，所以只剩下这两件。」

「因为累积了一大堆衣服不洗才会有这种下场。」

她说完后便往和人的肩膀戳了一下，接着更将手绕上和人的手臂。

「那今天我们两个人偶然都穿上『那时候的颜色』这实在太巧了。」

明日奈看着和人那离自己稍微高一点位置的眼睛这么说道，结果他干咳了几声后以不带感情的声音回答：

「哎呀，一年里时常见面的话，总是会有这么一天的嘛。」

「真是的，这种时候只要说『就是啊』不就好了吗！」

轻轻噘起嘴之后，明日奈拉了一下穿着皮衣的手臂。

「快点走吧，不要一直站在这里说话。天色马上就要变暗了。」

「嗯、嗯……」

明日奈紧贴在点头的和人身边，然后两人开始走过壕沟上面的桥。

老早就开始下山的朱红色夕阳照着古意盎然的白色大门，并在桥上投射出一道漆黑的影子。虽然是礼拜天，但可能是季节不对的缘故吧，今天这里几乎见不到观光客的身影。

经过穿着厚重大衣的警察身边穿越大门后，他们在小小的售票亭拿取塑料制入场券。银色栅栏后面，是让人完全不敢相信这里是东京都心正中央的静谧树木群。

提出礼拜天到哪去走走的人是明日奈，而指定在「皇居大门前」相见的人则是和人。

皇居当然是不对外公开，但是壕沟内侧被称为「东御苑」的东北角每个礼拜固定有几天会开放给一般人进入——其实明日奈在今天之前一直不知道有这么回事，所以这当然也是她第一次到这里来。当她走在宽广又漂亮的步道上时，忽然又有种不可思议的感觉，于是她便问站在右边的少年说道：

「……话说回来，你为什么选在这里见面呢？桐人你对历史那么有兴趣吗？」

「嗯，不是那样啦。主要的理由嘛……是因为前阵子有点事被叫到这附近来……」

和人瞬间像是想起什么事情般地用鼻子轻哼了一声，但马上就又恢复成原来平稳的笑容然后说：

「这件事我等一下会跟你说。先别谈这个，你不觉得皇居是个很有趣的地方吗？」

「……有趣，哪边有趣了？」

明日奈眨了眨眼后，和人穿着皮衣的手臂便动了起来，他指着周围苍郁的森林说：

「这里南北约两公里，东西是一点五公里。与北之丸公园和外苑合起来的话面积足足有两百三十万平方公尺，这已经占了千代田区的百分之二十，整体来说可是比梵蒂冈或是白金汉宫要大得多了，不过还是比不上凡尔赛宫就是了……而且不只是平面而已，这里的地底下没有任何地下铁或是隧道经过，当然所有的飞机也禁止飞过上空。也就是说这个地方是垂直贯穿过东京中央的巨大禁区。」

说完之后，明日奈试着在脑海里描绘出东京的地图。她左手手指一边在空中旋转着，一边点头表示同意。

「确实，都心的干线道路大概都是环状几号线或是放射几号线这样的名字。它们的中心全都是这个地方吧……」

「对对对，也就是说东京不像京都那样呈棋盘状，而是一座呈同心圆状的放射型都市。而且它的中心不只是物理上的禁区。连情报也完全被屏除在外。就像是旧ALO的『世界树』那样……啊，抱歉。让你想起不愉快的经验了。」

「不会，我不要紧的。」

过去曾经被囚禁在旧世界树上很长一段时间的明日奈，摇了摇头要和人不用在意后马上接着问：

「物理上的禁止进入还能够理解……什么叫做情报上的禁区？」

「啊啊，那是因为……」

和人忽然迅速将视线往周围的树木上看去，接着以很小的动作指了几个地方说：

「你看，那里和那里都有监视器对吧，那套监视系统完全是与世隔绝的。这里有着独立的封闭网络。外界完全无法联机到里面去。」

「这样啊……话说回来，那些监视器的模样确实很奇怪。」

和人手指的前方，可以见到上端有黑色球体的竿子竖立在那里。它看起来的确不像监视器，而像个照明灯。

「我听说这是实验中的次世代保全技术……总之呢——……这个地方不但是东京的中心，同时也是被隔离的『异世界』……这么说或许有些夸张就是了。」

「啊哈哈，确实有点夸张。」

当他们进行对话当中，步道绕过巨大的石壁变成相当倾斜的上坡。默默爬了一阵子之后，视界一下子变得相当宽敞。

眼前是一片几乎看不清对面的大草皮。草地由于目前正是冬天而呈现枯萎的浅褐色，周围树木的叶子也几乎都掉光了，但如果是春天的话，这儿一定是幅赏心悦目的景象吧。

「这里就是江户城的本城遗迹。常在古装剧里出现的后宫，好像就是在草皮稍微靠北边的地方唷。」

「我们去看看吧！」

重新握好和人的手后，明日奈开始加快脚步。人影依然相当稀少，而且几乎都是外国观光客的样子。途中他们与带着一对可爱金发姐妹的夫妇擦身而过时，忽然就被他们拜托帮忙拍照。和人亲切地答应了他们，结果外国人太太便笑着说「也帮你们拍一张吧」，于是他和明日奈便有些不好意思的排在一起拍了张照片。

用手机接收了相片档之后，年幼的姐妹向他们挥手道别。看着在橘色夕阳中逐渐远去的一家人，明日奈不知不觉问叹了一口气。

「……累了吗？」

听见和人这么问之后，明日奈便轻轻瞪了他一眼。

「才—不—是—呢！我们将来，不知道能不能像他们……嗯……算了啦。」

不禁脱口而出的话让明日奈的脸颊发热，于是她开始往前跑去。

「喂喂，等等啊！」

与追上来的和人稍微比赛了一下后，马上就来到一条将草皮分为南北两部分的小路上。在分叉路口看见一张凳子后，两人在上面坐了下来。

但明日奈依然把脸别到旁边去，这时和人只好畏畏缩缩的开口说：

「嗯……那个……结衣一定会高兴有个妹妹的。」

听见和人这直截了当的说法，明日奈虽然再度脸红，但还是忍不住轻轻笑了出来。

「说、说得也是。」

「什么嘛，这时候笑出来也太过分了吧……」

「啊哈哈，抱歉抱歉。不过如果结衣也能在现实世界里和我们一起生活就好了……」

结衣是他们两个在旧SAO服务器里遇见的少女。她真实身份是玩家的精神状况自动管理程序，也就是所谓的AI。而她把明日奈当成母亲、把和人当成是父亲看待，在艾恩葛朗特崩坏的时候，和人让她的核心程序躲到自己的NERvGear里而免于被消灭，现在她则是在和人房间里特别为她准备的桌上型专用电脑里过「生活」。

但是基本上只能在完全潜行环境下——也就是在ALO里面才能和结衣接触。虽然现实世界里使用手机也能和她通信，但因为电池容量的问题让和人他们没办法「一直和她在一起」。

没错，就算明日奈有多疼爱结衣这个女儿，而结衣又有多喜欢这个妈妈，两个人之间还是一直存在着假想世界与现实世界的障壁……

这时和人忽然默默握紧明日奈的手。

「不要紧，总有一天。一定可以一起生活的。只要完全潜行技术更加进步，到时候扩增实境一定会更加普及。」

「嗯……一定……一定会的。」

「是啊。现实与假想的境界今后将会越来越暧昧。虽然现在还有情报量差异这个障壁在……」

听见和人的话后，明日奈一边深深点头一边用力回握他的手，但忽然又抬起脸来说道：

「话说回来，和人你刚才也说过这句话对吧。你说假想世界与现实世界最大的不同就是情报量的多寡。这究竟是怎么回事？」

「嗯……」

和人的视线瞬间游移了一下，接着才又往两人重叠放在板凳上的手看去。

「比如说在ALO里面像这样握手还是跟在现实世界里有所不同对吧？」

听他这么一说，明日奈便将注意力集中在左手上。

像是手贴在一起时的手掌弹力、足以驱散冬天寒气的体温等，都是ALO的妖精角色之间也能有的触感。但是那种皮肤吸在一起的黏着感以及掌纹的摩擦感，以及两个人血液同步之后所传出来的细微脉动，这些都是最尖端的完全潜行技术也无法重现的感觉。

「嗯……这倒是。真正的手可以有各种感觉……原来如此，这就是『情报量较多』的状况吗？」

「没错。但今后AmuSphere会越来越进化，最后连皮肤感觉与悸动也完全呈现出来时又怎么样呢？到时候光凭触感还能分辨出是真正的手还是游戏角色的手吗？」

「可以唷。」

明日奈毫不考虑的回答看来出乎和人的意料之外，他只是眨了几下眼睛而不知道该说些什么。但明日奈凝视着他的脸并补上了一句话：

「桐人你的手的话就能分辨得出来。如果是别人的手可能就没办法了。」

一听到这里和人的手温度稍微上升，整个人心跳也开始加速。明日奈露出「吓到你了吧」的笑容，接着继续说道：

「不只是触感，还有像外表、声音、口味、气味等都还是现实世界里的情报量比较多。所以……就算现在的AmuSphere装上了扩增实境机能……」

「嗯嗯。在一见到或是触碰到的瞬间，就能知道它是不是真的东西了。」

扩增实境机能也就是能在清醒状态下使用AmuSphere将现实的视觉、听觉与数字情报结合起来。只要能实现这个技术，现行的桌上型PC与手机都将遭到淘汰。因为直接可以在视线当中表示出假想的操作画面，可以立刻搜寻资料传送邮件，甚至是在道路上加上导航或是显示出人与物的情报标签，可以说有无限多的用途。

现在RECT这些主流情报机器制造公司努力研究当中的机体，仍然有身体的动作会造成电子脉冲波失焦或是必须额外附加大容量电池等许多问题，因此距离实用化还有很长一段距离。

「……可惜的是。有人表示现在的头盔型机器没办法实现扩增实境的普及化。但是总有一天会找出技术的突破口才对，只要我们在现实世界里也可以接收大容量的五感数字情报……或者不需要床与电源线就可以随时进入完全潜行状态……」

明日奈听见和人的呢喃后点了点头，然后接下去说：

「到时我们就能够超越世界的障壁，永远和结衣在一起了。那一天一定会来临的……」

「嗯嗯，一定会的。」

过去在艾恩葛朗特第二十二层想起暂别的结衣时，他们两人也曾说过与刚才类似的对话。注意到这件事的明日奈感到内心有一股暖流扩散开来，于是便将头轻轻靠在身旁的和人右肩上。

当时那个会再和她见面的誓言在几个月后便实现了。

所以刚才的那番话也一定会被实现才对。

接近冬至时的夕阳简直像坠落般隐藏在西方的树林后面。准备回巢的鸟群们飞舞在鲜红天空之中。

数百年前眼前的广大草皮上曾经有座城堡，而当时生活在里面的人可能也同样这么看着夕阳吧。而经过数百年之后，又是谁会在这个被隔离在时间洪流之外的异世界看着红色天空呢……

「…………啊啊……」

明日奈忽然感到胸口充塞着一股乡愁，于是轻轻地叹了口气。身旁的和人稍微往她看了一眼。两人眼神交会之后微微一笑。

「我似乎可以了解你带我来这里的理由了。」

「咦……是、是吗？」

「嗯。如果世界是由『时间』的直线与『空间』的平面所构成，那么东京……也就是我们这个现实世界的中心无疑就是这个地方。然后……现在因为『The seed』而不断扩张的假想世界，中心轴便是那座已经不存在的『城堡』。所以这种夕阳的景色才会这么让人怀念……」

听完明日奈所说的话之后，和人眨了两三次眼睛，接着露出大大的笑容。

「对哦……说得也是。其实我也没有这么具体的想法。只是……听完明日奈刚才的发言之后，我了解到一件事。」

「咦，什么事？」

「就是艾恩葛朗特的形状啊。那种层基圆锥状构造或许就是象征着『时间轴与空间面』吧。」

明日奈考虑了一下之后也慢慢点了点头。

「没错……或许真是那样吧。但这样的话，团长想要创造的世界将会越来越窄，最后整个凝聚起来并且消灭。不过他的预定却在中途就被某个人引起的大爆炸所破坏了。」

「不、不好意思哦……副团长大人。」

两个人同时默默笑了起来。几秒钟之后和人用力吸了口气，然后就这样握着明日奈的手由板凳上站了起来。

「那我们也该回去了。这里五点就要闭园了。」

「嗯。下次也带莉兹和莉法她们来吧。在那片草皮上吃便当感觉一定很不错。」

「说得也是，等春天的时候吧。」

借着和人的手站起来后，明日奈最后又抬头看了一下往四方扩散的红色天空。

这时她心里有了想回家的念头。这当然不是指位于现实世界世田谷区宫坂的结城家。而是两个人在旧艾恩葛朗特第二十二层里的那座「森林小屋」。

虽然那间小小木屋随着浮游城崩坏一起消灭了——但现在明日奈有个能让胸口感到一阵温暖的计划。在这个计划实现之前，在阿尔普海姆世界树上的「世界树城市」里所租的房子，便是亚丝娜和桐人以及结衣的家。

两人朝着北侧的平川门出口走去。这时明日奈对着和人问道：

「你今天晚上能登入吗？我想要跟结衣讲讲今天发生的事。」

「嗯嗯，可以啊。大概是晚上十点左右吧。」

笑着点了点头之后，和人脸上突然出现了有些为难的表情。

「咦……你有什么事吗？」

「没有什么事啦。今天晚上是没关系……那个……亚丝娜……我……」

难得和人会这样吞吞吐吐，但他在犹豫了几秒钟之后，立刻讲出让明日奈吓得心惊胆跳的话来。

「……我最近可能会将ALO的『桐人』转移到另一个游戏里去……」

「……咦、咦咦咦？」

可能是被明日奈的叫声吓到了吧，附近树梢上有好几只鸟儿飞了起来。

** 第三章

薄暮。

低垂的云层因为开始倾斜的太阳而染上一片黄色。

荒野上尽是岩石与黄砂，旧时代遗物的高层建筑废墟所留下来的影子慢慢拉长。如果再待机一个小时以上的话，就得考虑是不是要换成夜间战斗装备了。

由于使用夜视镜会削弱那种杀人或是被杀的紧张感，所以诗乃不是很喜欢这样的战斗。蹲在水泥阴影下的诗乃叹了口气，内心期望目标的队伍能在阳光消失之前赶快出现。其实现在和诗乃一起进行这郁闷伏击的五名同伴也跟她有一样的想法。

一名在小组里担任前卫的成员像是要说出所有人心情般，将小口径短机关枪放下来然后说道：

「真是的，到底要等到什么时候嘛……喂……戴因啊，真的会来吗？不会是假情报吧？」

那名叫做戴因的男人有着魁梧身材与粗犷脸孔，而他也是这个中队的队长。这时他一边移动挂在肩上的大柄突击步枪，一边摇着头说道：

「那些家伙这三个礼拜几乎每天在同一时间、同一条路线上进行狩猎。这可是我亲自确认过的。今天确实是有点晚了，但一定是因为拼命打怪而延迟了吧。但这样我们等一下也可以有更多的收获，你就别抱怨了。」

「但是……」

担任前卫的男人还是有些不满的噘起嘴唇。

「今天的猎物是我们上个礼拜才袭击过的家伙对吧？有可能会因为警戒而更换路线啊……」

「距离我们上次袭击已经过了六天了。那天之后他们还是一直到同一座练功场狩猎。因为他们是专门打怪的中队……」

戴因的嘴角浮现嘲弄般的笑容。

「所以不论被袭击几次，也会觉得反正再打怪赚回来就好了。对我们这种对人中队来说是再好不过的猎物了。我们可以再干个两、三票都没问题。」

「但我还是没办法相信耶。一般被袭击过一次之后都会想些对策的吧。」

「隔天或许会特别警戒，但马上就会忘记了啦。因为练功场出怪的规律每天都是一样。所以每天打怪的他们也就变得跟怪物一样规律了。真是一群没有自尊的家伙。」

诗乃越听越感到不愉快，原本就躲在围巾里的脸也就埋得更加深了。感情的起伏会让扣下扳机的手指产生迟疑。就算知道这一点，但内心还是对装出一副什么都懂的戴因涌起一股不快感。

嘲笑一成不变狩猎着怪物的队伍，对自己是PVPer（注：对人玩家）感到骄傲，但是这种不断袭击同一队伍的行为似乎不会伤到他的自尊心。与其在这种中立练功场耗费好几个小时，倒不如到地下遗迹的迷宫里面与高等级中队一战还比较有收获。

当然这么做的话，一败涂地然后掉装备「死亡遣返」回到街上的机率也大为增加。但是战斗不就是这么回事吗，只有在这样的紧张感当中，灵魂才能够得到锻炼。

诗因是在两个礼拜前被邀请加入戴因所率领的这只中队。但一参加之后她马上就后悔了。虽然对诗乃宣称他们是以对人为主的队伍，但却是个只攻击战力比自己低许多的队伍，只要稍微有一丁点危机马上就撤退，以安全为第一目标的集团。但是诗乃到目前为止完全没对中队的方针提出批评，她只是默默地按照戴因的指示扣下扳机。当然她不是为了显示出自己多有忠诚心。哪一天在战场上面对戴因时。诗乃会依照目前取得的情报来判断他的思考与行动，然后将必杀的一发子弹送入他眉间。

虽然很讨厌他这种性格，但这个在上一次Bullet of Bullets里得到第十八名的男人。无论是能力或是肩上那把稀有「SIG·SG550」突击步枪所发射的五点五毫米弹威力都确实让人不能小觑。所以现在只要闭上嘴巴，睁大眼睛观察戴因在毫无警戒下所透露出来的情报。

这时戴因继续这么说道：

「说起来……那些为了狩猎怪物而尽买些光学枪的家伙，不可能马上就每个人都准备好对人用的实弹枪吧。最多就是其中一个人准备多了一只支援的火力而已。为了把那个家伙干掉，我今天特别要诗乃把狙击枪给带来了。这次作战可以说完全没有死角。你说对吧，诗乃？」面对这忽然抛过来的话题，诗乃埋在围巾里的脸只是微微点了一下。但她还是紧闭着嘴巴，显示出没有意思加入谈论当中的态度。

戴因像是感到没趣般用鼻子哼了一声，但担任攻击手的家伙却对诗乃咧嘴一笑然后说道：

「这倒是真的。只要有诗乃的远距离狙击，我们就一定占优势了。倒是诗乃啊——」

攻击手脸上浮现松弛的笑容，但他还是趴在地上注意不让自己跑到掩蔽物阴影外面去。他就这样慢慢来到诗乃身边然后说。

「今天攻击完之后你有空吗？我也想要提升狙击技能，想说能不能请教你一些问题呢……要不要去哪里喝个茶？」

诗乃迅速看了一下男人挂在腰间的武器。这男人的主要武器是实弹系短机关枪「H＆K·UMP」。他似乎是属于AGI型，正面战斗的回避力算相当高。但无论是等级或是装备都不是需要特别注意的对手。花了一些时间想起对方的名字后，诗乃轻轻低下头说：

「抱歉……银狼先生。我今天真实世界里有点事……」

与现实世界里完全不像的清澈可爱声音响起，同时也让诗乃心里觉得很不高兴。就是这个原因让她不喜欢说话。那名叫做银狼的男性即使马上就被拒绝，脸上也还是挂着软绵绵的笑容。一部分男性玩家光是听到诗乃的声音便会出现这种表情。一想到这里就让诗乃有种不寒而栗的感觉。

首度投身于这个VRMMun Gale Online」时，原本希望能够选一个粗旷男性的外型。但她马上就被告知这款游戏没办法创造出与自己性别相反的游戏角色。于是只好退而求其次，希望能够变成一个高大魁梧、像个士兵一样的女孩。

但是随机选取所生成的却是一个娇小纤细，简直像个洋娃娃般的少女。虽然马上考虑要放弃这个账号然后重新创造一个角色，但邀请诗乃加入这个世界的朋友却强硬地对她说「太可惜了！」并要她别放弃。之后随着越来越热练，这个角色的等级也提升到无法回头的程度了。

因此她时常会遇见像这样让人十分困扰的邀请。对纯粹只是想战斗的诗乃而言，这只会让她感到相当忧闷而已。

「这样啊——诗乃在真实世界里还是学生对吧，是大学生吗，难道说是要写报告？」

「……嗯……算是吧……」

总觉得有一次在注销之前不小心提到学校，接下来的邀约就变得更加难缠了。所以现在就算杀了她也不想说出其实自己是高中生。

结果，至今为止一直蹲在地上操纵着数值视窗的另外两名前卫玩家，马上就像要牵制银狼般慢慢靠了过来。灰色镜片护目镜上垂下绿色前发的男人开口说道：

「银狼啊，你这样造成诗乃的困扰了吧。游戏里是不能提到现实世界里的事情唷。」

「对啊对啊。就算你在现实世界和这里都是单身也一样。

另一名斜戴着迷彩头盔的男人笑着说完之后，银狼便用拳头在他们两个头上边转然后边反击道。

「还敢说我。你们两个不也远离春天很久了吗？」

在哈哈笑着的三个人身边，诗乃一边将身体缩得更小一边感到非常不可思议。

既然玩游戏的主要目的是要与其他玩家对战，那么在待机当中应该还有集中精神或是检查装备这些有意义的打发时间方式，如果想利用转换钱币系统来赚取电子货币，那倒不如去加入专门打怪的中队还比较好。又如果是想要认识异性的话，根本不用选择这种单调且充满杀伐之气的世界，其他应该也有固定性别又浪漫美丽，里面还有许多女性玩家的游戏才对吧。他们到底是为了什么目的而来到这个世界的呢？

诗乃再度将脸深深埋进围巾里后。开始用左手指尖抚摸着架设旁边在脚架上的大型狙击枪枪身。

——总有一天我会用这把枪将你们的角色轰飞。看你们之后是不是还能像这样笑着对我搭话！

在心底深处这么嚅嗫完之后，焦躁的心情就像是被冰冷的酒桶吸进去般慢慢沉静了下来。

「过来啰——」

当用望远镜从快倒下来的水泥墙洞穴里不断搜寻着敌人的最后一名成员讲出这句话时，已经是又过了二十分钟之后的事情了。

三名前卫以及戴因的讲话声嘎然中止，现场立刻充满了紧张的空气。

诗乃瞄了一下天空。她发现黄色云层虽然已经逐渐转红，但光线仍然相当充足。

「终于出现了吗……」

戴因低声说完之后半蹲着移动到墙边，从负责监视的队员那接过望远镜。接着透过同一个洞口确认着敌人的战力。

「……确实是那群家伙。七个……比上礼拜多了一个人。拿着光学雷射枪的前卫有四个人。还有一个拿着大口径雷射冲锋枪。加上……唉唷，有个家伙拿着『MINIMI』。他上周还拿着光学枪，应该是急忙换成实弹枪了吧，这家伙应该就是狙击的目标了。最后一个人……罩着披风所以看不见武装……」

听见他这么说之后诗乃便采取伏射姿势。将自己的脸靠近狙击枪的高倍率瞄准镜。

诗乃他们的六人中队是潜伏在建立于高台上的前文明遗迹当中。斑驳不堪的水泥墙与钢筋刚好成为他们掩蔽物，可以说是最适合监视前方广大荒野的地形。

诗乃再度拾起头看着天空，确认过自己没有处于假想太阳会造成镜片反射的位置上后，她便将瞄准镜的前后可掀式护罩掀了起来。

直接将右眼靠在镜片上后，设定为最小倍率的视野可以看见几个移动中的小点。诗乃用指尖调节了一下倍率转盘，每当轻微的声音响起，原本像芝麻大的黑点便越来越大，最后变成七名玩家的模样。

正如戴因所说，当中有四个人拿着光学系突击枪，其中两个人还频繁地利用望远镜警戒着四周围环境。但是除非他们里面有人拥有相当高等级的搜敌技能，否则几乎是没办法发现诗乃他们的埋伏。

两名挂着大型枪械的成员走在集团中间。其中一名拿的是半自动的光学雷射冲锋枪，另一名则是实弹系轻机关枪「FN·MINIMI」。这是款在现实世界里日本自卫队也加以采用的优秀分队支援火力。由于光学枪的攻击力有一半以上会被防护罩抵消，所以对诗乃他们来说MINIMI的威胁性当然要高多了。

这款「Gun Gale Online」里登场的武器可以分为实弹枪与光学枪两种。

实弹枪的好处是每发子弹都带有很大的杀伤力，同时具有贯穿防护罩的能力。但缺点就是得带上好几个笨重又占空间的弹匣，而且弹道很容易受到风吹或是湿度的影响。相对的光学枪的好处便是枪支本身相当轻。而且射程远命中度又高。另外装在弹仓里的能源盒也相当轻巧，但缺点是遇上名为「防护罩」的玩家用防具后威力便会减弱。

因此对付怪物时用光学枪，对抗玩家时用实弹枪已经是游戏内的定律，但这两大类的枪械除了在性能面之外。在其他方面也有很大的差异。

那就是光学枪都是使用虚构的名称与造型，而实弹枪则是将现实世界里真正存在的枪械直接在游戏里登场。

因此GGO玩家里面便有许多像戴因与银狼这样的枪械爱好者身边时常带着实弹枪，只有在打怪的时候才会切换成光学枪。

现在贴在诗乃脸颊上的狙击枪也是属于实弹系的枪械。但是诗乃在来到这个世界之前可以说是对枪械一无所知。虽然为了要玩游戏所以已经把这些枪的名字当成道具背下来，但现实世界里的她绝对没有因此而对枪械产生兴趣。她除了认为这世界里几近无限的枪械都只不过是3D对象之外。也讨厌在现实世界里看见枪械。

她只是在这个杀戮世界里拼命地以假想的子弹摧毁假想的敌人。直到内心变得像石头般坚硬、血液像冰块般冻结为止。

为了达到这个目的，诗乃今天也将在这个世界里扣下扳机。

甩开多余的思考后，诗乃稍微动了一下狙击枪。敌人队伍的最后方有一名以巨大护目镜遮住容貌，身上披着迷彩披风的玩家正在往前移动着。正如戴囚所说，完全看不见这个人身上的装备。

那是一名相当魁梧的大汉。背上像背着登山背包般让整条披风夸张地鼓了起来。但从衣角可以见到他的双手部没有拿武器。他挂在腰间的最多也大概是短机关枪等级的武器而已吧。

「你说脸被披风遮住了吗？」

从背后传来银狼的声音。虽然他是想要开玩笑，但还是听得出他声音里带着略为紧张的心情。

「不会是那个家伙吧？那个传说中的……『death gun』！」

「哈，那根本是假的吧。」

戴因马上笑着回答道。

「而且人家说死枪是穿着吉利服的瘦小男性唷，眼前那家伙可是相当高大。至少有两公尺那么高吧，应该是……超级STR型的搬运工吧。背上的东西应该是赚来的道具或是弹药、能源盒之类的。我想他身上没什么大不了的武装，战斗时可以无视他的存在。

诗乃一边听着戴因这么说，一边由瞄准镜里紧盯着那个男人看。

庞大的装甲护目镜让人看不见他脸上的表情，整张脸只有嘴角露在外面。男人的嘴唇紧闭在一起，可以说完全没有任何动静。其他成员虽然也在警戒当中，但时常可以见到因为闲聊而露出的雪白牙齿，只有走在队伍最后面的男人从头到尾没有说过半句话。他只是默默跨出极为整齐的脚步。

诗乃半年来在GGO里培养出来的直觉告诉她，这个男人的威胁性远超过那个拿着MINIMI的成员。但除了背部的登山背包之外，他的披风便没有什么特别显眼的隆起了。会不会是藏着什么小型但威力惊人的稀有武器呢，但也只有光学枪才有这种类型的武器。而那在对人战斗里面没有办法成为决定胜负的力量。这么说从这男人身上感到的压力只是自己的错觉而已吗……

犹豫了一阵子后，诗乃还是小声说道。

「我觉得那个男人不太对劲。我想把最初的狙击目标换成那个男人。」

戴因的脸从望远镜上离开之后，扬起眉毛看着诗乃说：

「为什么？他身上没什么大不了的武装。」

「虽然没有根据……但是他身上的不确定要素让我相当在意。」

「要这么说的话。那把MINIMI才是真正的不安要素吧。被他缠住时雷射枪又接近过来的话就不妙了。」

就算防护罩能有效抵挡光学枪的攻击，但效果却会因为敌我之间距离缩短而减弱。在至近距离互相射击时，还是有可能会输给弹匣平均弹数较多的镭射枪。这时诗乃只好舍弃自己的主张。点了点头并开口说道：

「我知道了……第一目标还是放在MINIMI身上。可能的话第二发将瞄准那个披风男。」

诗乃虽然这么说，但只有在敌人还没有发现射手的状态下，第一发狙击弹才能发挥出效果。发射地点遭到确认之后，敌人便能看见狙击枪的「弹道预测线」，接下来的子弹将会轻易地被人躲过。

「喂。没有时间继续说话了。距离只剩下两千五百公尺。」

担任索敌的男人用从戴因那拿回来的望远镜看了一眼后这么说道。戴因点了点头头，接着转头对身后的三名攻击手说：

「好……一切就按照作战计划进行，我们前进到正面大楼的阴影处等待敌人吧。诗乃——我们开始行动后就看不见那些家伙了，如果情况有什么变化就通知我们。我会指示你狙击的时机。」

「了解。」

简短回答完后，诗乃便再度将右眼放回瞄准镜上。目标的队伍还是以略为缓慢的速度在荒野中前进，目前看不出有什么异状。

他们与诗乃之间隔着二点五公里宽的荒野。中央靠近诗乃他们中队的位置上耸立着一座巨大的高楼遗迹。戴因他们五个人便是利用它进入目标队伍的死角，然后准备一口气发动强袭作战。

「好——开始行动吧。」

听见戴因简短的命令之后，除了诗乃之外的成员都响应了一声。他们留下军靴踩着碎石地的声音后，由高台后方滑了下去。等到夕阳下的风将他们的脚步声带走之后，诗乃由脖子上的围巾底下拿出一组小型耳机并将它装在左耳上。

从现在起的数分钟里，诗乃必须独自一个人持续与身为狙击手的压力与孤独战斗，自己发射出来的一颗子弹将对今后的战局产生重大影响。能依靠的就只有自己的手指与不发一言的狙击枪而已。诗乃的左手滑过架在脚架上的巨大枪身。黑色金属将冰冷的沉默传递到她身上。

诗乃之所以会在这个世界里成为少数还算知名的狙击手玩家，其实这把实弹枪占有很大的原因。

它的名字是「PGM·Ultima Ratio HecateⅡ」。它是把全长一百三十八公分，重量达十三点八公斤的巨大枪械，使用五十口径，也就是直径十二点七毫米的巨大子弹。

听说它在现实世界里被归类为反物质狙击枪。也就是以贯穿车辆与建筑物为目的的枪械。由于威力实在太过于强大，所以依据某种名字一大串的条约来禁止在对人狙击时使用。但是这个世界里面当然没有这种条约。

诗乃是在三个月前，开始可以算是GGO资深玩家时得到这把狙击枪的。

当时诗乃随性地一个人潜入延伸在首都SBC格洛肯地底下的广大迷宫里，但却一个不小心触发了坑道陷阱。「Gun Gale Online」的舞台是设定在过去因为大战而文明毁灭殆尽的地球上。而玩家们便是参加移民宇宙飞船团回到地球上的人们。格洛肯这座城市原本是宇宙飞船。它的地下有在过去大战中崩坏的巨大都市沉睡着。都市还迹里有无数的自动战斗机械以及遭受基因改造的怪物蠢动着，等待梦想一获千金的玩家们前来冒险。而诗乃就是掉落到最危险的迷宫深处。

当然那不是一个人就能够脱出的地点。做好一遭遇怪物马上就会落败然后「死亡遣返」回到存档地点的觉悟后，诗乃开始谨慎地在迷宫里前进。这时她眼前突然出现一座像是广大运动场的圆形空间，还有一只像是异形般的怪物躲在里面。由体型以及名字可以判断出这应该是属于魔王等级的怪物，但诗乃过去在任何网站上都没见过它的模样，当注意到这一点时，诗乃心里那些微的游戏玩家魂便开始燃烧起来了。心里想着「反正不过一死，就跟这家伙大战一场吧」的诗乃躲进运动场上方的排气孔里。接着将来福枪对准了怪物。

但是战斗却有了出乎意料意之外的发展。魔王级怪物虽然拥有热线、钩爪、有毒瓦斯等乡种攻击手段，但每一种都以些微之差而无法攻击到诗乃。话虽如此，由于怪物所在位置也几乎在诗乃来福枪的攻击范围边缘，所以她也仅能对怪物进行相当微弱的攻击。依照身上所携带的子弹数量来判断，她得将身上所有子弹都击中怪物的弱点——也就是额头上的小眼睛才有获胜的机会。

而诗乃便靠着如冰块般的冷静与集中力完成了这项任务。当怪物终于被打倒，多边形巨大身躯爆散开来时，已经是战斗开始三小时以后的事情了。

从这只魔王级怪物身上所掉下来的，是一把从来没见过的巨大狙击枪。NPC或是玩家的工作室在游戏设定上没办法制造出强力的实弹枪，而在街上贩卖的仅是一部分低威力的枪械，所以想要中等以上的武器就只有自己到遗迹里去挖掘一途。诗乃入手的狙击枪——「Ultima Ratio HecateⅡ」在能挖掘出来的武器当中算是最为稀有的一种。

据说目前服务器里面被冠上反物质狙击枪名称的枪械，包含诗乃的黑卡蒂Ⅱ（HecateⅡ）在内也不过只有十把而已。之前拍卖会里出现的该类型枪械卖出了游戏内货币二十M点数，也就是有两千万的价值。而电子货币转换系统的汇率是一百比一，所以兑换过来之后可以得到日币二十万元这样的巨大金额。

诗乃在现实世界里是自己一个人过生活的高中生，每个月都得用家里送来的微薄生活费过日子，所以当她知道这把枪的价值之后真的感到非常犹豫。最近她才好不容易能赚到每个月连线费用的一半——也就是一千五百日币，但即使如此还是有一半得用上自己的零用钱。不过要是再多花一点时间在游戏上面的话，自己的成绩可能就很难维持下去了。但只要有这二十万日币，扣除至今为止用掉的连接费用后还是可以算大赚了一笔。

但诗乃最后还是没有将这把枪卖掉。她进入GGO的目的不是为了赚钱，只是为了打倒所有比自己还强的玩家并藉此来克服自己的弱点而已。何况这是她首次对单单只是道具的枪械有了「心灵相通」的感觉。

黑卡蒂Ⅱ因为拥有巨大的枪体与重量，所以在设定上需要相当高的STR值，但身为狙击手的诗乃已经将STR值提升得比AGI值要高，所以有惊无险的得以装备上这把武器。当诗乃首次带着这把武器上战场，透过瞄准器看见敌人时，她由手里这沉重又冰冷的铁块上感到了力量以及意志。它拥有渴求杀戮与死亡的冷酷灵魂。而诗乃梦寐以求的便是这种不屈服于任何人、不产生任何动摇也绝不流一滴眼泪的形象。过了一阵子之后，诗乃才知道「Hecate」是取名自希腊神话里掌管冥界的女神。这时她便决定以它作为自己最初同时也是最后的伙伴。

瞄准镜中的目标队伍不断向前移动。

抬起脸直接往荒野里看去之后，马上可以发现戴因他们五个人正往夹在中间的崩塌大楼前进。两个集团间的距离已经缩短到七百公尺左右。诗乃再度将右眼贴在瞄准器上，接着只要等候戴因的指示就可以了。

数十秒之后，由耳机里传来带有杂音的讲话声。

『准备发动攻击——』

「了解。敌人的路线以及速度都没有改变。与你们距离四百公尺。距离我大概一千五百公尺。」

『距离还很远。你没问题吧？』

听见戴因的问题后，诗乃冷冷地回答「没问题」。

『好……那开始狙击。』

「了解。」

简短对话之后诗乃闭起嘴巴。右手食指静静往大大的扳机护圈摸去。

瞄准器的视野里可以见到肩上扛着MINIMI的第一目标正一边说话一边向前进。

在上周的战斗中，诗乃不是担任狙击手，而是装备突击步枪负责直接支援的任务。所以曾在近距离下见过这个男人的脸孔，但他却没在诗乃记忆中留下任何印象。不过由可以装备支援火力这点就能知道他的等级相当高。

诗乃一边抑制忽然加速起来的心跳，一边移动瞄准镜里的十字线。考虑过距离、风向以及目标的移动速度之后将枪身往左上方移动一公尺以上固定下来，接着移动食指触碰扳机本体。

这时候诗乃视线里马上出现发出浅灰色光芒的半透明圆形。

周期性缓缓改变直径大小的圆形以男性胸部为中心，一直扩展到他的膝盖为止。这是只出现在诗乃视线里的攻击性辅助系统，也就是所谓的「着弹预测圆」。被发射出去的子弹将会乱数命中圆内侧的某个部位。现在圆的面积大概只有三成左右覆盖到男人的身体，也就是命中率只有百分之三十的意思。而且就算黑卡蒂Ⅱ拥有绝大的威力，只击中对方的手臂或是脚部这些末端部位也是无法让敌人立刻死亡，所以一击必杀的机率也会下降。

这个着弹预测圆的大小是根据与目标之间的距离、枪的性能、天气、光量、技能。能力值等要素来产生变动，但当中重要的指标还是狙击手心脏的鼓动。

AmuSphere能够接收现实世界躺在床上的玩家心跳，然后将档案传送到游戏系统当中。

心脏跳动的瞬间正是圆形扩展到最大范围的时刻。接着圆形将会慢慢缩小，然后在下次跳动时再度伸展。也就是说要提升命中率的话，就必须要在心脏跳动的低点时进行狙击。

但是放松状态下每分钟六十次——也就是每秒一次左右的平稳心跳通常在狙击时会因为紧张而上升两倍以上的速度，此时圆形也会跟着产生剧烈的缩放运动。在这种状况下根本无法在脉搏的低点进行狙击，这就是GGO里狙击手相当少的最大原因。

因为实在太难命中目标了。狙击时的紧张心情根本无法控制。当然接近战时也会因为心跳加快而让预测圆产生震动，但只要距离接近还是能够击中目标。如果使用的武器是全自动小型轻机枪或是突击步枪就更不用说了，但是距离超过一干公尺的远距离狙击通常预测圆都会扩展到超过人的身高好几倍。现在诗乃视线里所显示出来的圆形命中率有三成已经可以算是奇迹了。

但是——

诗乃在心里这么嚅嗫道：

这种压力、不安与恐怖又算得了什么。距离一千五百？这根本像把纸团丢进垃圾筒那么简单。没错——

跟那时候比起来的话……

她的头脑里开始降下一团冷气。心脏的鼓动奇迹似的平静下来。

——冰块。我是由寒冷冰块所制成的机械。

着弹圆的圆周变动速度瞬间缓了下来。同时诗乃的感觉也开始往外扩张，她可以确认圆形缩成最小的那一瞬间。

一……二……当第三次收缩的圆形集中在扛着MINIMI男人的心脏上那一瞬间，诗乃立刻扣下扳机。

宛若雷鸣般的咆哮震动了整个世界。

由设置在黑卡蒂Ⅱ枪口的防火帽爆发出巨大火花，发射出去的子弹超越枪声后直接向前突进。原本整只狙击枪以及诗乃的身体都将因为后座力而向后弹去，但她马上用紧踏住地面的双脚抵消这股力道。

瞄准线对面的那个男人或许是注意到发射时的火花了吧，只见他忽然抬起头来。他的视线因此和看着瞄准镜的诗乃互相交错——

下一瞬间，男人开始由胸口到肩膀，最后连头部都变成极小物体并开始粉碎与消灭。迟了一会之后，剩下来的身体部分也像被敲碎的玻璃雕像般四处飞散。倒霉的是他肩上的超高价轻机关枪似乎就是乱数掉装备的对象，可以见到它当场就滚落在沙地上。当这名男人重新复活回到街上时，一定得花上一番功夫才能由遭到一击杀害以及掉宝的双重打击中恢复过来吧。

无情地确认过这些事情后，诗乃的右手自动动了起来，她直接拉下黑卡蒂Ⅱ的枪栓。巨大弹药筒随着金属声退了出来，掉在旁边的岩石上后消失无踪。

在装填下一发子弹的同时，诗乃也微微将狙击枪往右边移动，这是为了将第二目标的巨汉收进瞄准镜内。这时男人覆盖在护目镜下的脸孔已经朝诗乃这边看了过来。诗乃将准星瞄准他身体略为上方的部位，手指再度放在扳机上。绿色的着弹预测圆再次出现，接着马上就往一点收缩。

从发射第一发子弹到现在不过三秒钟的时间。如果是半自动狙击枪的话就可以连射，但是单发的黑卡蒂Ⅱ没有这种性能。只不过一般玩家在发现自己同伴的身体忽然粉碎时必定会感到惊讶与僵硬，而要在这种状态下重新振作起精神找出狙击点并准备回避，至少也需要五秒钟的时间。原本觉得趁着这阵混乱，第二次狙击应该也有成功的可能性——

但是披风男丝毫没有露出慌张的模样，反而从大型护目镜深处笔直凝视着诗乃。这家伙果然是老手，诗乃心里一边想着他一定是个相当知名的玩家，一边直接扣下扳机。

这时候男人的视线里，已经可以见到一条淡红色半透明的光线，而那便是由即将袭击自己的子弹所画出的「弹道预测线」。这是游戏在枪击战斗里面为了增加紧张感所采用的守备性辅助系统。只要是拥有高人一等的反射神经与AGI值，而且心脏也比别人大颗的玩家，就能轻易躲过半数以上从五十公尺处发射出来的冲锋枪子弹。

狙击手这个职业最大的优势，就是对方眼里看不出最初一发子弹的预测线。但是诗乃已经攻击过一次而暴露出自己的位置，所以目前已经不再有这种优势了。

爆炸声再度响起。由诗乃指尖发射出来的冷酷黑卡蒂Ⅱ子弹，就像「死亡」结晶般撕裂淡黄色空气直接往敌人飞去。

但正如诗乃所想，男人冷静地向右跨出一大步。紧接着十二点七毫米弹便直接贯穿距离那巨大身体一公尺外的空间。遥远后方的荒野上原本有一块突出来的水泥墙，上面立刻就出现一个圆洞。

诗乃的右手无意识中继续行动，马上就装填好下一发子弹，但回到握把上的指尖却没打算扣下扳机。

因为继续狙击下去也没用了。如果一定要继续的话就只有移动位置，躲到男人的视线之外，然后静候六十秒让方位情报重新设定。但那时候这场战斗应该已经大势底定。诗乃依然看着瞄准镜，直接对着嘴边的受话器说。

「第一目标成功。第二目标失败。」

戴因马上就有了响应。

『了解。攻击开始。GOGOGO……！』

耳机内稍微可以听见戴因往地上一踢后冲出去的「沙沙！」声。此时诗乃才将憋在嘴里的一口气轻轻吐了出来。

她的任务就到此结束。由于黑卡蒂Ⅱ是极为稀有的枪械，所以背着它参加正面战斗而死亡掉宝的话。那真可以说是损失惨重。戴因也告诉她狙击行动结束之后只要待机就可以。第二次攻击失败虽然多少让人有点牵挂，但接下来就只能祈祷「不祥的预感」只是自己的杞人忧天了。

诗乃一边这么想一边再度移动狙击枪，调降瞄准镜的倍率将敌人队伍全部纳入视线当中。四名前卫急忙躲进附近的岩石与水泥墙等掩蔽物后面，而更后方带着大型雷射冲锋枪的后卫与那名披风男则是——

「啊……！」

诗乃不由得叫了出来。而这时巨汉正举起双臂，将迷彩披风从身上扯了下来，

男人的两手上与腰间都没有武器。

而他背上那原本以为是搬运道具用背包的物体这时候也整个露了出来。

一条弯曲的金属棒横跨他强壮的肩膀。而像悬挂着般着装在他身上的是某种粗中带细的金属制品。

那是被Y字型支撑框架所包围的圆筒型机关部。上面还有相当粗的手把突出来，而下方则伸束在一起的六根枪管。每根的长度都在一公尺以上。

装设在机关部上的弹带还与同样吊在金属棒上的大容量弹仓互相链接着。

诗乃过去曾一度在GGO情报网站的武器名鉴上看过见这把枪械过于巨大且狰狞的外貌。

它的名字确实是「GE·M134迷你炮机枪」。在武器中属于重机关枪的一种。是在Gun Gale Online登场的最大型枪械之一。六管枪身可以边高速回转边进行装填·发射·退匣等动作，所以足够以一秒钟百发这种疯狂的速度发射七点六二毫米弹，真可以说是宛若恶梦般的枪械——不，应该可以说是兵器了。

当然它本身的重量也相当惊人。光是本体就要十八公斤，如果再加上那些大量的弹药应该就超过四十公斤了吧。就算再怎么强化STR的玩家也无法在重量限制下装备上这把武器，所以在过重状态下的移动当然得付出代价。

那只队伍移动速度之所以会那么缓慢，不是狩猎延迟了时间。而是因为那就是巨汉尽全力之下的最快移动速度了。

诗乃带着惊讶的心情看着瞄准镜，在她视线中央的巨汉将右手绕到背后去直接握住机枪的握把。巨大机关枪顺畅地从金属棒上横移过来，在男人身体的右侧前方来了个九十度回转。巨汉张开双脚，做出将六管枪身由正面推出来的姿势后——护目镜下方的嘴巴才首次动了起来，他露出了相当狰狞的笑容。

诗乃急忙操纵转盘，将瞄准镜的倍率调到最小。

银狼他们三名攻击手拿着冲锋枪由视线左侧冲了过去。虽然由敌人前卫的雷射枪所发射出来的光弹已经拖着蓝白色尾巴朝着他们飞去，但只是在银狼他们面前一公尺左右的空中留下水面般波纹然后威力便减弱了。这就是高性能「对光弹防护罩」产生的效果。

实弹系的短机关枪也开始像是要报复般喷出火来，这时由岩石后探身出来的一名雷射枪男身上出现「啪啪」的深红着弹效果后便倒了下去。银狼他们再往前进，到最接近敌人的水泥墙后面去——

这时男人整个人腰部向下一沉。

迷你炮机枪的枪身开始高速回转，三秒钟后马上有闪烁着亮光的带状物爆发开来。

光是这一击就已经将银狼的角色就连同水泥掩体一起分解消灭了。银狼简直就像遭受水流冲击的泥偶一样。

「呜…………」

咬紧嘴唇的诗乃站了起来。她由地面上抱起黑卡蒂Ⅱ后顺势将脚架叠起并将背带绕过身体。

全长一百三十八公分的黑卡蒂Ⅱ整个被身高只有一百五十五公分左右的诗乃扛在肩上。但幸好这还在重量限制范围之内。加上辅助武器的超小型短机关枪「H&K·MP7」后之所以还能够不超出重量限制，都是因为诗乃除了STR值相当高之外，弹匣里还只携带了七发黑卡蒂Ⅱ的子弹而已。

现在肉眼也可以辨认出现在一公里半之外战场上的枪口火舌。诗乃无言地全速向前冲去。

事到如今战况已经是对戴因他们极为不利了。如果只是面对使用迷你炮机枪的男人，他们只要保持一定距离然后边高速移动边攻击就能够打倒他。但是使用雷射枪的敌人在机枪的援护之下，只要前进到防护罩失去效力的距离，就能够迫使戴因他们非得迎击不可。

虽然是中队的一员，但诗乃就算在这时候撤退将来也不会遭受到任何怨言。因为她已经顺利完成目标物的狙击任务。

但诗乃还是一直线朝着战场跑去。当然她不是为了救助同伴。而是那个机枪男脸上浮现的笑容让诗乃的脚不断向前迈进。

男人有着能在战场上露出笑容的实力。而且灌注在游戏上的时间已经足够让他获得迷你炮机枪这种与黑卡蒂同等级的稀有武器。当然他还有累积这种惊人STR值所需要的忍耐力。更重要的是男人也拥有足以冷静面对诗乃狙击的胆量。

与这种对手作战并且杀掉他们——诗乃便是希望藉此来消灭自己心中那总是在哭泣的另一个「朝田诗乃」。

她就是为了这个理由而投身于这个疯狂的世界。如果这时候逃走的话，至今为止累积的成果都将变成泡影。

诗乃用参数所允许的最快速度踩过干燥地面、撕裂充满尘埃的空气，只是一味向前跑去。

只见她有时闪避、有时跳越过碎石沙地上的岩石与半塌的水泥墙，仅花了数十秒钟便冲进交战区域里面。

诗乃完全没有考虑到隐藏身形的问题，将AGI参数支援发挥到极致之后便往前直线冲刺。敌人集团应该也已经捕捉到诗乃逐渐接近的身影了吧。

两支队伍的交战区已经和开始时有了一段很大的距离。节节败退的当然是戴因这一边。有了迷你炮机枪不分青红皂白的扫射支援，敌人集团的前卫得以慢慢向前逼近。为了逃离光学枪的有效射程，包含戴因在内的四名队员全都不断由一个掩蔽物退到另一个掩蔽物后面。

现在已经不可能冲出荒野直线往前逃走了。一旦暴露身影，马上就会被机枪那宛如瀑布般的子弹给打成蜂窝。而且戴因他们现在所靠着的水泥墙后面已经没有任何退路。剩下来的就只有一开始用来接近敌人的那些半数倒塌的大楼遗迹。只不过一旦逃进那里面，就会变得跟瓮中之鳖一样了。

瞬间理解这所有情报的诗乃，一口气便准备跳进戴因他们暂时苟延残喘用的墙壁后面。但下一刻马上就有三条淡红色光线出现在诗乃正前方。

「呜……」

她咬紧牙根，开始准备回避子弹，这应该是由担任攻击手的雷射枪男所发出的弹道预测线。

诗乃首先将身体蹲到最低来躲过最初的预测线。接着灼热的蓝白色热线便循着头上的预测线飞过。这时眼前又有了第二条预测线。诗乃立刻将全身力道灌注在右脚上往地面一踢，整个人便腾空眺了起来。接着腹部旁边马上又有一条雷射经过，瞬间视线只能见到一片白色。

第三条预测线与在空中的诗乃将在稍高的位置上交错。虽然她已经尽量缩起脖子来闪避热线，但淡蓝色短发的前端还是被扫到，头发马上就变成光粒四处飞散。

好不容易躲过雷射枪的连射，来到地面上的诗乃眼前——

立刻又被直径大约有五十公分的粗大线条给染成一片红色。

这无疑就是迷你炮机枪的弹道预测线。零点几秒后，那如暴风般的连射即将要袭击过来了。

奋力催动因为恐惧而僵硬的身体，诗乃刚触到地面的右脚马上伸直，让她再度往空中飞去。在空中一个转身之后，她便像跳高似的在空中一个挺身。

接着诗乃便感到宛如暴风般的能源洪流从她背后擦过。当闪烁白色光芒的实弹群通过她眼角后，稍远处一座废墟大楼的破墙马上又被挖空了一部分。

当背部快落在砂石地上时，诗乃再度转身改成以双手双脚着地。在这同时她更全力让身体往前方扑去。往前转了几圈之后，诗乃已经处身于戴因他们躲藏的水泥墙后面了。

中队队长以惊讶的眼神看着忽然出现在眼前的诗乃。无论再怎么往好处想，他眼神里闪烁的都不是感谢的光辉，而是看见一个自寻死路者时所感到的疑惑。

戴因马上别过脸去，看着自己手里的突击步枪。这时他说话的声音已是低沉且沙哑。

「那些家伙请了保镖……」

「保镖？」

「你不知道吗？就是那个用迷你炮击枪的大汉啊。那家伙叫做『怪兽』，是以北方大陆作为根据地的攻击狂。通常被有钱但怕死的中队所雇用。做些像是保镖的工作。」

虽然诗乃心里想着「至少还比你有骨气多了」，但她当然不会蠢到把话说出口。她反而看向戴因身后那些不时由掩蔽物后方探出脸来，朝着敌人集团发射无谓反击的三名攻击手，接着以只有同伴能听见的极小音量说。

「一直躲在这里也只有全灭一途。迷你炮机枪应该快没子弹了——我们全部一起发动攻击的话他或许会犹豫该不该疯狂进行扫射。而我们只有抓住这个时机干掉他才有活路。你们两个拿着冲锋枪往左边，我和戴因绕到右边，M4你就待在这里支援……」

当她说到这里时，戴因又用沙哑的声音打断她说：

「……没用的。对方还有三名拿着雷射枪的家伙。冲过去的话防护罩的效果就……」

「雷射枪的连射没有实弹枪那么快，大概可以躲过一半射击。」

「不可能！」

戴因再度顽固地拒绝，他摇着头说：

「冲过去只是让机枪打成蜂窝而已。虽然不甘心，但也只能放弃了……与其看那群家伙胜利的模样，倒不如在这里就注销……」

在中立练功场里注销的话也不会马上就消失。失去魂魄的角色会留在现场几分钟的时间，当然这时候也会遭到攻击。虽然机率较低但还是会随机数发生武器或防具的掉宝现象。

到目前为止只是觉得身为队长的戴因每次指示撤退的时机都太早了一点，但没想到他竟然会提出这种自暴自弃，简直就像小孩耍赖般的提议。诗乃有些难以置信的凝视着戴因那看起来像是身经百战的士兵脸孔。

戴因忽然咬牙切齿地叫道：

「搞什么，只是游戏而已何必这么认真！还不都是一样，就算冲出去也只是死路一条……」

「那你就去死！」

诗乃反射性大叫道。

「至少在游戏里面展现一下在敌人枪下丧生的勇气！」

唉~~自己怎么会对这个不过是猎物的家伙讲出这种话呢。不过这下子注定得要离开这个中队了吧。

诗乃一边在心底深处这么想着，一边抓起戴因迷彩衫的领口强行将他拖了起来。她同时瞪大了眼睛看着剩下的三个人，接着开口迅速说。

「给我三秒就够了，你们只要能吸引机枪男的注意，我就能用黑卡蒂解决他。」

「知、知道了……」

绿色头发垂在护目镜前面的攻击手吞吞吐吐地回答，剩下的两个人也跟着点了点头。

「好，那就分成两队由左右两边同时冲出去。」

诗乃一脸不高兴地推着戴因腰部，让他移动到掩蔽物角落去。当诗乃拔出左腰上的辅助武器MP7后便用手势开始倒数。

三、二、一。

「GO！」

说完的同时她便用力往地上一踢，奋力投身于一秒钟后那满是死亡危机的战场当中，

马上眼前就有好几条弹道预测线切过，诗乃让身体往后倒去，一边利用滑行来躲过子弹一边让敌人集团进入视线当中。右前方斜角大约二十公尺左右的墙壁后面躲着两名手拿雷射枪的敌人。而左边较远处还有一个。机枪男「怪物」则是在中央更往后十公尺的地方，这时他正准备将往左边冲出去的两名同伴收进他的射线当中。

诗乃边往右跑边将左手的MP7对准了雷射枪男。用力按上扳机之后马上就出现了着弹预测圆，但由于无法抑制快速的心跳，这时圆形几乎已经完全超出敌人们的身体。

但诗乃还是毫不犹豫地开始射击。手掌一边感受着无法与黑卡蒂Ⅱ相提并论的后座力，一边将弹匣里的二十发四点六毫米弹一口气全射光。

虽然两名雷射枪男已经因为他们这种不怕死的反击而急忙躲到墙壁后面，但还是有数发子弹击中他们的身体。虽然不会损耗他们多少HP，但也足以争取到数秒钟的时间了。

「戴因！援护！」

诗乃边叫边整个人往地面扑去，同时也用双手将黑卡蒂Ⅱ从背后拉了过来。她甚至没有张开脚架的时间。手里支撑着惊人重量的她直接就往瞄准镜里看去。

设定在低倍率的视野里占满了怪物的上半身。发现他的脸笔直往这里看过来之后，诗乃无法等待预测圆收缩便扣下了扳机。

必杀的闪光随着巨响贯穿整个空间——但子弹接着便从怪物头部旁边擦过。这时怪物的身体因为冲击而失去平衡，头上的护目镜也被轰飞接着变成碎片消失了。

咬紧嘴唇准备起身的诗乃，在瞄准镜中与怪物的视线交错。露出真面目的怪物，灰色双眼里发出灿烂光芒，嘴角依然挂着不屑的笑容。

诗乃全身已经被巨大的红色光束包围。

她瞬间判断已经无法回避。甚至从伏射姿势下站起身来往左右哪一边跳去的时间都没有。

至少要对着枪口死亡——

诗乃为了遵守自己曾说过的话，撑起身体后便笔直盯着怪物看。这时他巨大的身躯上忽然出现了好几个光点。

原来是来自于戴因的援护。他单脚跪地并举起举起突击步枪，提高命中度后直接往怪物身上射击。

在这种状况与距离之下还可以让这么多发子弹命中敌人，虽然人格不怎么样但射击技术确实不错，诗乃一边这么想一边用力往右边扑去。刚才身体所在的地方随即被数十发子弹给贯穿。

「戴因！再往右边一点……」

当诗乃这么叫道时……

再度由掩蔽物后面出现的两名雷射枪男，无情地对着站起身来的戴因发射热线。

此时他们之间的距离实在是太近了。戴因的防护罩立刻被贯穿，热线直接就打在他身上。

戴因瞬间看了诗乃一眼。但随即又将脸转向敌人——

「呜哦哦！」

叫了一声后便开始笔直地往前冲。

雷射立刻就如下雨般往戴因身上落下。但戴因躲过这些攻击后便蹲低了身子，继续往前猛冲。当然他不可能避过所有的子弹。

最后几秒钟里，戴因拔起腰间那拿来当成护身符的大型电浆手榴弹，接着将它丢进掩蔽物后面。同一时间里戴因的HP也全部消失，他就这么背对着诗乃变成无数多边形碎片往四处飞散。

接着就是一片闪光让整个世界变成白色。

空间里产生了宛若巨神之槌撞击大地般的冲击。蓝白色能源洪流到处肆虐，战场里漫天扬起灰蒙蒙的沙石。雷射枪男们的身体也夹杂在尘埃当中飞上天空，其中一人在掉落在地面之前便粉碎并消失了。

——有骨气！

称赞了退场的戴因一下之后，诗乃虽然因为扬起的尘埃而眯起眼睛，但她还是迅速环视过整座战场。

由左翼突击的两名伙伴里已经有一个人被迷你炮机枪干掉了。但原本应该在那里的一名雷射枪男也已经消失。

右翼的戴因因为自杀性特攻而丧生。但也同时带了一名敌人前卫下地狱，而另一个人应该是暂时无法动弹吧。

一阵子之后——当尘埃开始落定时，马上就出现一道直线往这里接近的巨大剪影。

这样一来就只变成诗乃和怪物的单挑了。但是在这种距离之下，狙击枪根本无法和机关枪抗衡。

诗乃得想办法进入迷你炮击枪的死角里并摆好射击姿势才行。但这种一对一的战斗哪里来的死角呢……

不对——

诗乃一时之间感到无法呼吸。现在四周围都被戴因手榴弹所卷起的飞尘所覆盖，这种情况下怪物应该也没办法判断出诗乃的所在地。当然诗乃也因为视线不佳而无法进行狙击，但她或许可以趁现在移动到这座战场里唯一不会受到那子弹风暴侵袭的地点。

一想到这里，诗乃马上就转头往耸立在战场正后方的残破大楼遗迹冲去。

冲进入口之后，发现大楼的后半部已经完全崩坏而可以看见黄色天空，但右手边墙壁旁确实有目标物——也就是通往上层的楼梯存在。诗乃小心翼翼地走着，尽量不让堆积在地面上的瓦砾崩毁而发出声音。

虽然金属制楼梯也到处部是缺块，但诗乃还是毫不在意的冲了上去。她在往楼梯间墙壁一踢后转换方向持续往上爬去。

花了不到二十秒时间就来到五楼的诗乃发现楼梯就到此为止了。而她的左手边出现一扇很大的窗户。

在这里的话，应该能在怪物没注意到的状态下争取到摆好射击姿势的时间。

诗乃一边这么想一边将黑卡蒂Ⅱ的枪拖抵在肩上，接着由窗口往下看着整座战场。但她的视线马上就被染成一片红色。

数十公尺下的地面上，怪物已经将迷你炮机枪尽量往上抬，目前已经瞄准了站在窗口的诗乃。他已经看穿诗乃的想法与所有作战。

诗乃根本没有后退或是趴下的时间。

实在是太强了。这家伙是真正的GGO玩家，不，应该说是士兵才对。

但这才是诗乃梦寐以求的对手。杀掉他。自己绝对要杀掉他。

她没有丝毫犹豫。不摆出射击姿势便直接将右脚踩上窗框一口气跳了下去。

同一时间宛如火焰般的能源激流已经由地面上冲了过来。「啪叽！」一声后诗乃的膝盖下方马上遭到强烈冲击。角色的脚部整个被轰飞，HP值也急遽减少。

但是她仍未死亡。越过迷你炮机枪的射线后，诗乃整个人腾空。这时她来到站立在当场的怪物上空。

或许是打算将弹仓里的所有子弹射光吧，怪物将身体往后顷，让自己的射线朝着诗乃追去。但是这时他发现射线根本抓不到诗乃。因为悬吊在背上金属棒的机枪没办法朝自己的正上方射击。

当开始落下时，诗乃便将黑卡蒂Ⅱ的枪拖靠在肩上，眼睛也贴上了瞄准镜。

视线里满是怪物那粗犷的容貌。这时笑容终于从他脸上消失。他咬牙切齿，双眼中燃烧着以惊讶与愤怒为燃料的熊熊烈火。

诗乃将所有意识集中在牵动自己的嘴角上。

这时反而变成她脸上出现了笑容。那是个狰狞、残虐且冷酷的微笑。

虽然仍在落下状态，采取的也不是安定的射击姿势，但两者间的距离实在是太近了。当枪口来到怪物头部大约一公尺左右的距离时，绿色的着弹预测圆整个收缩并固定在男人脸孔的中央。

「THE END！」

诗乃这么呢哺着的同时，手指也扣下了扳机。

带有这世界里最大能源的光箭由冥界女神的指尖发射了出来。

子弹瞬间在怪物脸上以及身体开了一个大洞，最后甚至深深贯穿满是瓦砾的地面。

类似爆炸的冲击声随之响起，怪物的庞大身躯也分解成圆筒状并且消失了。

** 第四章

一离开校门，又冷又干的风马上打在脸颊上。

朝田诗乃停下来把脖子上的白色围巾重新围好。

她将戴着塑料框眼镜的脸蛋一半埋到围巾里面之后才再度向前走去。快步走在满是枯叶的步道上，她在心里小声地呢喃道：

……这下子高中三年全部上课天数六百零八天里面，已经有一百五十六天结束了。

好不容易过了四分之一的日子。一想到这里，诗乃就又为了这苦行的日子实在太过漫长而不知如何是好。但如果把国中时代也算进去的话，这样的日子现在已经过了将近六成以上。总有一天会结束……总有一天会结束。诗乃像是念咒般不断重复如此念着。

其实就算高中毕业那天到来，诗乃也没有什么特别想做的事，当然也没有想从事的职业。但还是希望能从这个算被强迫进入的「高中生」集团里解放出来。

诗乃实在不能理解每天每天来到这个像监狱一样的地方，听着教师们有气无力的讲课。和一群令人怀疑是不是从幼儿期开始心灵就没有任何成长的家伙们排在一起做体操或是做些有的没的，究竟有何意义。当然也有少数几个让人觉得数学很扎实的教师。也有让人觉得值得尊敬的学生，但他们的存在对诗乃来说并不是那么重要。

现在诗乃实际上的监护人是祖父母。过去诗乃曾向他们提出不上高中马上就想出社会工作，或者是到职校去接受就职训练的想法。但老古板的祖父马上气得面红耳赤，祖母则是哭着对诗乃说希望你能念个好学校将来嫁个好人家，不然我们就太对不起你父亲了。于是她只好拼命用功考上了东京还算有名的都立高中。但一到学校就读之后诗乃就吓了一大跳。因为这里基本上和其他乡镇的公立高中并没有什么不同。

结果诗乃就与国中时期一样，每天离开校门时都会像仪式般数着还剩下多少日子。

诗乃一个人生活的公寓位在学校JR车站的中间。虽然是六张榻榻米大小加上一间小厨房的狭小房间，但因为处于商店街角落。所以购物相当方便。

下午三点半的商店街里还没有多少行人。

诗乃看了一下书店的平台之后，发现喜欢的作家有新书推出了，但因为是精装本，所以她还是忍耐下来离开了书店。在线预约的话，不到一个月区立图书馆里就可以借得到那本书了。

接下来她又在文具店买了橡皮擦与方格线笔记本。确认了一下皮包里剩下来的钱之后，诗乃一边考虑晚餐的菜色一边往商店街中央的超级市场前进。诗乃的晚餐基本上都是一菜一汤，只要能满足营养、卡路里、价格均衡这几个条件，外表或是味道就不那么讲究了。当诗乃决定晚餐是红萝卜芹菜汤加上豆腐排，经过游乐场前面准备进入旁边的超市时——

「朝田——」

从两栋建筑物缝隙当中的小巷子里传出呼唤诗乃的声音。

诗乃先是反射性地缩起身体，接着才缓缓往右边转了九十度。

巷子里有三名跟诗乃穿着同样制服——但裙子长度有些差异的女学生站在那里，其中一人蹲在地上按着手机。另外两个人则靠在超市墙壁上，一边笑一边看着诗乃。

看到诗乃只是沉默地站在那里，其中一名站着的少女用蛮横态度甩了一下睑。

「给我过来！」

但是诗乃还是没有动作。她只是小声问道：

「……什么事？」

这时其中一个人快速靠近，用力抓住诗乃的右手腕。

「少啰唆，过来就对了。」

她就这样把诗乃拖了过去。

诗乃直接被押进从商店街外面看不见的小巷子深处这时蹲在地上的女学生抬头看着她。她的名字叫做远藤，算是三人里面的头头。那黑色的眼线、上扬的眼睛以及尖锐的下颚，给人一种猎食性昆虫的印象。

远藤涂有大颗亮粉口红的嘴唇露出扭曲的笑容，只听她对诗乃说道：

「不好意思哦，朝田。我们刚才去唱歌结果把搭电车的钱都花完了。我们明天就还你，先借这样给我们吧。」

她说完便竖起一根手指。这不是一百也不是一千，代表着一万日币的意思。

现在才刚放学二十分钟而已，就算唱歌也花不了多少钱，何况这二个人应该都有电车的月票，最夸张的是为什么坐个电车得花一万日币呢。诗乃虽然在心中不断列举这些根本说不过去的矛盾之处。但她也知道就算直接把话说出来也是一点帮助都没有。

这已经是她第二次被这三个人像这样勒索金钱了。上次诗乃是以手边没钱的理由来拒绝她们。

虽然心里想着同样的理由可能没用了，但诗乃还是说：

「我手边怎么可能有那么多钱。」

结果远藤脸上的微笑瞬间消失，但马上再度笑着说：

「那你就去领啊。」

诗乃沉默地准备走向商店街，当她想着「这群人应该不敢跟到有别人在的银行，而且一旦离开这里之后谁还会这么笨又跑回来」时——远藤又继续这么说道：

「把书包和钱包都放在这里。只要有提款卡就可以领了吧。」

诗乃停下脚步，回过头来看着她。远藤的嘴上虽然还是挂着微笑，但眯起来的两眼里面却有着猫咪戏弄猎物时那种兴奋的光芒。

她曾经相信这三个人是真心想和她做朋友。一想到这里，诗乃就没办法原谅自己的愚蠢。

刚进到这所高中时，由于初来乍到而没有任何熟人也没有和同学的共同话题，于是诗乃只能每天默默待在教室里，而最初开口跟她说话的就是远藤。

她先是约诗乃一起吃午饭。最后变成四个人下课之后会一起去快餐店。诗乃通常只是听她们说话，虽然心里有时会对她们的话题难以认同，但她还是感到高兴。因为诗乃已经很久没有像远藤她们这种不知道「那个事件」的朋友了。她觉得在这个学校里应该可以过普通的学校生活。

诗乃是在很久之后才发现这三个人是因为从班级联络簿上得知她一个人独居，所以才会特意接近她的。

当她们问「可以去你家玩吗？」时。诗乃马上就答应了。远藤她们称赞诗乃的公寓、羡慕诗乃的生活，在她家聊天一直到天黑为止。

而她们隔天及再隔天也一样到诗乃家来。

不久后她们三个人变成在诗乃房里换完便服后才搭电车出去玩。这时候她们会把行李都放在诗乃房里，接着她们三人的便服开始塞满了诗乃的小衣橱。

鞋子、包包、化妆品等远藤几个人的私人用品越来越多。到五月的时候，出去玩的三个人喝醉了回来之后便会睡在诗乃家。

有一次诗乃终于畏畏缩缩地向她们抱怨每天来的话会打扰到她看书。

但远藤的答案就只有「我们是朋友吧」。隔天她便向诗乃要求也要一把她家里的钥匙。

而在五月底的某个周末……

当从图书馆回来的诗乃站在自己家门前时，听到从里面传来夸张的大笑声。而目笑声听起来不只有远藤她们而已。

诗乃屏住呼吸，竖起耳朵倾听房里的说话声。她对这种窥探自己房间的行为感到相当无奈与可悲。

里面明显传出好几个男人的声音。

自己的房间里竟然有不认识的男人在。一想到这里，诗乃就因为恐惧而整个人缩成一团。但接下来她心里便涌起了一股怒火。她终于了解事情的真相了。

她下了公寓的楼梯，利用手机报了警。赶过来的警察虽然对两造（录者注：原告与被告）的说法感到相当困惑，但诗乃只是不段重复着「我不认识他们」这句话。

被警察催促着先跟他到警察局去一趟的远藤恶狠狠地瞪着诗乃，留下一句「哼，是吗」之后便把所有东西拿走了。

之后她们的报复来得相当迅速。

远藤发挥出平时绝对看不出来的恶魔般调查能力，立刻把诗乃一个人生活的理由——五年前在遥远的某县里所发生，现在网络上也几乎都找不到的「事件」给查了出来。并且还透露给全校知道。

结果周围环境又回到跟国中时代相同了。

但诗乃心里觉得这样也没关系。

是渴望朋友的欲望蒙蔽了自己的眼睛。但其实只有自己才能解救自己。只有靠自己的力量变强，才能够跳脱那个事件所造成的伤害。只要能做到这一点。就算没有朋友也没关系。她反而希望她们是敌人。她的周围——全都是要与之对抗的敌人。

诗乃吸了一口气，笔直看着远藤的脸。

只见她眯起来的两眼里充满杀伐的光芒。这次远藤脸上终于完全没有笑容，改用低沉的声音说：

「搞什么。还不快点去——」

「不要。」

「……啥？」

「不要。我才不想借钱给你。」

诗乃目不转视直接这么回答。

强硬的拒绝应该更会引起对方的敌意与恶意吧。即使知道这一点，诗乃还是不想顺从她们的要求或是虚与委蛇之后才赶紧逃走。这不是针对远藤她们，而是她不愿意显露出「软弱的自己」。她想要变强，这一直是她五年来唯一的目标。在这里屈服的话。她的努力将完全白费。

「你这家伙……少瞧不起人了！」

右边眼角不断抽动的远藤朝着诗乃跨出一步。其他两个人迅速绕到诗乃身后。在至近距离下包围住她。

「我要走了——请你们让开。」

诗乃低声这么说道。她认为远藤她们再怎么做出暴跳如雷的架势，终究还是不敢真的动手。她们在家里也是很普通的好孩子，应该不想再次被带到警察局里去才对。

但是……

远藤她熟知诗乃的弱点——她很清楚知道该刺激什么地方才能够让她流血。

涂着夸张口红的嘴唇浮现嘲弄般的笑容。

远藤缓缓抬起右手，对着诗乃眼镜的中央伸了过去。接着从拳头里伸出食指与大拇指，做出小孩子比出手枪般的动作。这简直是低级又幼稚的讽刺。

但光是这样就足以让诗乃感到全身发冷了。

她的双脚逐渐失去力气。平衡感慢慢离她而去，小巷里的景象也失去色彩。这时远藤装成手枪的手指在她眼前晃来晃去，而她的眼神也没办法离开那发光的细长指甲。随着心跳加速，像由高频率音波所引发的耳鸣也越来越严重……

「磅！」

远藤忽然大叫。诗乃喉咙里立刻发出细微尖锐的声音。她打从心底深处感到恐惧。完全无法控制自己，全身发抖。

「哼哼……我说朝田啊……」

远藤的指尖依然对着诗乃。她接着边笑边对诗乃说。

「我哥哥呢，他有好几把模型枪。我下次带到学校来给你看吧。你应该很喜欢手枪吧？」

「…………」

舌头无法动弹。只能在完全干渴的嘴巴中缩成一团。

诗乃微微摇了摇头。如果在学校里忽然见到模型枪的话，她可能会当场昏倒吧。光是想象那种情形就让她胃部收缩，整个人无法忍受而弯下了腰。

「喂喂，你可别吐了啊，朝田——」

从后面也传来带着笑意的声音。

「你上次在上世界史时忽然又吐又晕倒的，之后可是引发了一阵大骚动啊~」

「不过也常有喝醉酒的老头在这里吐就是了。」

好想逃走。好想赶快逃离这个现场。但是我不能这么做。相反的两个声音不断在诗乃脑袋中响起。

「那今天先把你身上所有的钱交出来就好了。朝田你看起来不怎么舒服对吧。」

远藤的手朝着诗乃右手上的书包伸了过来，但她却完全无法抵抗。不能去想。不能去回忆。虽然这么告诉自己，但是记忆的屏幕上还是出现那道黑色光辉。那种沉重、湿濡的钢铁触感。还有刺鼻的火药味——

这时候从背后传来叫声。

「这边！警察先生，快点来！」

那是个年轻男人的声音。

这时远藤的手离开书包。三个人马上以非常快的速度往前冲，最后混在商店街人群里消失了。

这次诗乃的双脚真的失去力量，整个人像要昏倒般蹲了下去。

她拼命调整呼吸，想要将恐慌症发作的前兆给压下去。过了一阵子后，好不容易才又慢慢感觉到购物客人的喧嚣以及超市门口烤鸡肉串的香味，几乎要苏醒的恶梦开始逐渐远去。

就这样蹲在地上数十秒钟之后，背后才又有一道畏畏缩缩的声音传过来。

「朝田同学……你不要紧吧？」

诗乃最后用力吸了口气，才再度在无力的脚上灌注力道并站起身来。

重新戴好眼镜转过头去后，马上就看见一名瘦小的少年站在她眼前。

那是一名穿着牛仔裤与尼龙外套的少年，肩膀上还背着一个深绿色背包。那张戴着黑色棒球帽的圆脸让穿着便服的他看来像个国中生，但双眼里浓郁的阴影却又完全不符合他那稚嫩的外表。

诗乃知道这少年的名字。他是这城市里唯一能放心——至少感觉他不是敌人的存在。而且在这边之外的另一个世界里也可以算是诗乃的战友。

诗乃的心悸好不容易才平静下来，这时她露出些微的笑容说道：

「……不要紧。谢谢你，新川同学。警察先生呢？」

她看了一下少年的背后，但微暗的巷子里并没有其他人，而且也没有人会出现的样子。

新川恭二搔着戴帽子的头部笑着说：

「我骗人的啦。电视剧和漫画里不是常有这种剧情吗。我早就想试一次看看了，幸好有成功。」

「…………」

诗乃稍微呆了一下。然后轻轻摇着头说：

「……在那种紧急时刻亏你能演出这种戏。你怎么会在这里？」

「啊，我刚才在游乐场里面。结果从后门一出来就……」

恭二转头看了一下背后。巷子对面那道满是雨渍的水泥墙上，确实可以见到一扇银色小门。

「看见她们围住朝田同学。本来真的想打110报警……」

「没关系，还是得救了。真的很谢谢你。」

诗乃再度微微一笑，恭二见到之后一瞬间脸上也出现了笑容，但马上又恢复成一脸担心的表情。

「……朝田同学，你常遇见这种事吗……？那个……或许你会觉得我很鸡婆，但这种事还是跟学校报告比较好……」

「就算跟学校报告也没用。没问题的，如果她们太过分的话我就会去报警。不过你还有空担心我啊，我才想问你不要紧吧……？」

「嗯嗯……我不要紧。而且也不会再和那些家伙见面了。」

瘦小的少年这次有些自嘲的笑了起来。

新川恭二在暑假之前都还是诗乃的同班同学。但是自从下学期开始后就没来过学校了。

诗乃也只是听到谣言而已，据说恭二遭到参加的足球杜里高年级学生的严重霸凌。他体格娇小，家里又经营一家大医院，所以就被当成霸凌的最佳目标。那些人在金钱方面虽然不像远藤她们这样明目张胆，但似乎也逼迫恭二付了许多吃饭与玩乐的钱。

其实诗乃没有直接听恭二提过这件事。

他们两个人是今年六月在附近的区立图书馆里认识的。

诗乃在二楼阅览室里，看著名为《世界枪械》的大本图鉴。

这时的她好不容易才做到看见照片也不会诱发恐慌症。但看见刊载着「那把枪」的页数十秒钟左右诗乃就再也撑不住，就在她急忙把书盖起来的瞬间，有人从背后对她搭话道：

……你也喜欢枪吗？

过了一阵子之后她才注意到，问这句话的男孩是她同班同学。

诗乃马上想回答「怎么可能，我最讨厌枪了」。但是这么说的话，对方一定会产生那你为什么看这本书的疑问，而要捏造一个合理的解释似乎相当困难，所以诗乃便暧昧的把话题带过。

现在恭二虽然已经知道诗乃在现实世界里对枪械抱有极度的恐惧感，但他当时却弄错诗乃的反应，很高兴地笑着坐到诗乃旁边的位子上。

接下来他便指着图鉴上的照片不断诉说着枪械知识，诗乃内心虽然流着冷汗，但还是一直听着他的说明，在这当中恭二提到了关于「另一个世界」的事情。

诗乃原本就知道好几年前有完全潜行类型的游戏机发售，也曾经听过VRMMO这个名称。但是对从小就没有玩游戏习惯的诗乃来说，「剑与魔法的世界」只要存在于奇幻小说里面就够了，所以她对这种游戏也没有多大的兴趣。

但是恭二着迷般对初次见面的诗乃所说的假想世界，似乎没有剑也没有魔法。那里面有的只是——各式各样的枪械。

那个世界的名称是「Gun Gale Online」。那是将存在于现实世界，或者是曾经存在的各种枪械完全重现，而玩家们便带着这些枪械互相厮杀的凄惨荒野。

诗乃打断恭二的话，直接这么问道：

——那个游戏里面……有叫做00枪吗？

少年眨了一下眼睛之后才理所当然般地点了点头。

这时诗乃心里便有了一个想法。如果是在那个假想世界里，自己能够再度和「把枪」对峙吗？那把黑色手枪五年前在十一岁的自己心底留下深邃又难以抹灭的弹痕，而自己再度面对它时，能与它作战并且获胜吗……？

诗乃紧握住自己流满冷汗的手，用沙哑的声音再度对恭二提出问题。她问要玩那款游戏全部大概要花多少钱。

之后又过了半年。

由诗乃心中诞生的另一名叫做「诗乃」的少女，已经是GGO荒野里声名远播的冷酷狙击手了。

但很可惜的是她到现在还没遇过拿「那把枪」的敌人，所以诗乃还不清楚，不是游戏里的角色，而是现实世界里的朝田诗乃是不是真的变强了呢……？

她还没找出这个答案。

「……要不要喝点什么？我请客。」

恭二的声音将诗乃由想像当中拖回现实。她抬起脸来之后，发现照在小巷里的阳光已经带着残红。

「……真的吗？」

诗乃微微一笑后，恭二也很高兴似的不断点着头。

「商店街的小巷子里有一间很安静的咖啡厅，到那里跟我讲一下你前阵子活跃的事迹吧。」

几分钟以后，恭二便带着诗乃来到咖啡厅。当她在深处的位子上坐下来，两手包住散发着诱人香气的奶茶茶杯后，心情才稍微算是冷静了下来。她在内心告诉自己，反正远藤她们一定还会来找麻烦，所以到时也只能随机应变，现在担心这么多也没用。

「你前天的事情我已经听说了。大家都说你非常活跃呢！」

听见恭二的声音后抬起头来，马上就见到这个瘦小的少年一边用汤匙戳着冰咖啡里的香草冰淇淋，一边眼睛上扬的看着诗乃。

「……没那回事。作战算是失败了，我们六人中队里面有四个人被干掉。以伏击的结果来说，根本没办法算是获胜。」

诗乃耸了耸肩之后这么回答。明明在现实世界里只要想起真正的枪械便很容易引起恐慌症，但或许是在虚拟世界里练习的成效吧，最近只要是GGO内部的话题，诗乃就还可以保持平常心。

「但还是很厉害啊。听说那个使用迷你炮机枪的『怪物』至今为止还没有在团体战里被人干掉过呢。」

「是吗……原来他那么有名啊。我没在『Bullet of Bullets』的排行榜上看过他所以不知道。」

「那是当然啰，就算迷你炮机枪再怎么厉害，带着五百发子弹一定会超重而无法跑动。『BOB』是单人遭遇战，所以只要被人在远处瞄准攻击就完蛋了。不过集团战里只要有充分的支援他就可以算是无敌了。那种武器根本是犯规嘛！」

看见像个小孩般噘起嘴巴的恭二后，诗乃也不由得露出微笑。

「……老实说，我的黑卡蒂Ⅱ也常被人家说是超级犯规的武器啊。不过用起来其实有许多不方便。我想那个怪物先生一定跟我有相同的想法。」

「啧，真是奢侈的烦恼。那……下一次的BOB你有何打算？」

「我当然会出场。我已经收齐上次进入前二十名的玩家资料。我准备拿黑卡蒂出场。这次一定要把他们全部都……」

诗乃几乎就要讲出「杀掉」这两个字，但马上就把话收了回来。

「我会力拼进入前几名……」

诗乃在上上个月第一次参加GGO举行的第二次最强者淘汰赛「Bullet of Bullets」，虽然突破了预赛进入了三十个人的决赛里，但却只得到第二十二名这种无法接受的结果。

在广大地图上乱数配置玩家位置的BOB里，由于可能一开始就被卷入近距离战斗当中，所以当时她不是带着黑卡蒂II而是装备着突击步枪，结果反而在接近战斗中被装备「REMINGTON．M40K」狙击枪的狙击手至近距离给干掉了。

现在又过了两个月，她已经大致清楚该怎么操纵黑卡蒂这个顽皮的女神，而且现在又得到了稀有的轻量短机关枪「MP7」，在近距离战斗上也比较不成问题，所以她打算背着这把巨大狙击枪参加即将举办的第三次BOB大赛。基本上她的预定是只要躲在掩蔽物后，等待目标出现在视线里就把他们一个不剩的轰飞，即使被人说这种作战实在太过卑鄙也不要紧。

只要能在满是强力战士的GGO里打倒所有敌人，证明自己是最强的话——那个时候，一定就……

怀抱着朦胧想法的诗乃耳里这时传来恭二的感叹声，也顺便将她的意识拉回现实世界来。

「这样啊……」

诗乃眨了眨眼睛后看向恭二，但对方却反而像看见什么耀眼事物般眯起眼睛来看着她。

「朝田同学真是太厉害了。除了入手威力那么强大的枪械之外……能力值也很有远见地以STR为优先。明明是我邀你玩GGO的，但已经完全被你超越了。」

「没那回事……新田同学在上次的预赛里不也打进准决赛了吗？那场胜负只能说是你运气不好而已。真的很可惜，如果在预赛时能打进决赛，就能参加正式的BOB大赛了。」

「不……那是不可能的。除非运气很好，不然上次成绩已经是AGI型的极限。看来我的能力值分配是完全错了……」

听见恭二抱怨的口气之后，诗乃微微地皱起了眉头。

恭二的角色「镜子」是GGO初期主流的AGI，也就是全力提升敏捷力数值的类型。

这类型的角色在游戏开始营运后半年左右，就靠着压倒性的回避力与速射力——这里的「速射」指的不是枪支本身的连射速度，而是瞄准之后着弹预测圆安定下来的时间——凌驾于其他类型的玩家之上。但是随着地图逐渐被攻略也有越来越多的强力实弹枪登场，这类型的玩家由于缺乏STR也就是筋力值，所以无法装备这些新武器，而且枪支本身命中率的提高也让他们越来越无法随心所欲地避过子弹，在开始营运经过八个月的现在，这种类型的玩家已经不能说是主流了。

但只要能得到速射力超绝的稀有大口径步枪，比如「FN．FAL」或是「H&K．G3」等等，那就还能够在第一线里活跃，事实上在上次BOB里得到季军的「暗风」便是AGI提升到极限的类型。只不过——击败他而得到优胜的「ZED」是STR－VIT型也是铁一般的事实。

但是——

在诗乃的观念里，所谓数值上是什么类型怎么说也只是「角色的强度」而已，其实还有比这个更重要的要素存在。

那就是玩家本身的强度。也就是心的坚强程度。前天对战的「怪物」他总是能够冷静沉着地行动，而且作战时脸上还都能够保持着轻松的笑容。那男人实力的来源不是那把M134迷你炮机枪，而是脸上那狰狞勇猛的笑容。

所以诗乃有点难以认同恭二所说的话。

「嗯……那把稀有枪械确实很强……但那只是强者刚好又装备了稀有的武器而已，不是全部拥有稀有武器的人就是强者唷。实际上，上次大会里进入决赛的二十个人里，有一半左右都是使用挂在店头的一般武器唷，」

「那是因为朝田同学你已经有那种稀有武器，然后又是先提升过STR的平衡型所以才能这么说。武装真的会造成很大的差距……」

看着一边叹息一边搅着飘浮咖啡的恭二，诗乃觉得再多说什么也没用了，于是她便准备结束这个话题。

「那新川同学你是不打算参加下一次的BOB啰？」

「嗯……因为就算参加也没用。」

「这样啊……嗯……这也不能勉强。你正在参加补习班的大学检定课程对吧？模拟考成绩还可以吗？」

恭二从夏天以来就没有到学校上课，似乎也因为这件事和父亲有了很严重的争执。

恭二的父亲经营一所规模还算大的医院，所以从很早以前便命令这个从名字就知道是次男的恭二要考上医学院。诗乃之前就听说在一次剧烈争吵的家族会议之后，恭二虽然得到在家里学习的允许，但必须在后年参加大学同等学历检定考，然后不重考便进入也是父亲母校的某有名私立大学医学院就读。

「啊……嗯……」

恭二点了点头后笑了起来。

「没问题，排名都还维持在能上志愿学校的范围内。你不用担心我，教官。」

「那就好。」

开玩笑般回答完之后，诗乃也微笑了起来。

「新川同学的登入时间一直都很长，我还有点担心呢。不管我哪时登入都看到你在线上。」

「我白天时有在看书啦。时间的分配是很重要的。」

「这么长的游戏时间应该让你赚了不少钱吧？」

「没那回事……AGI型的话根本没办法一个人狩猎……」

由于对话好像又要转往不太妙的方向，所以诗乃便急忙插话道：

「不过只要能赚到连线费就够了啦。抱歉……我差不多该回去了。」

「啊对哦。朝田同学还得自己做饭对吧。希望下次能再有机会吃到你做的菜。」

「啊，嗯，嗯，没问题。过一阵子……等我再熟练一点。」

诗乃再度慌张的说道。

她曾经邀请恭二到家里吃她所煮的晚饭。吃饭的过程可以说是相当有趣，但饭后隔着桌子喝茶休息时恭二眼里的热度却越来越高，这着实让诗乃心里握了一把冷汗。就算是超级网路游戏狂又是枪械迷。但男孩子终究还是男孩子，诗乃当时确实反省了一下自己这种略嫌轻率的行为。

她并不讨厌恭二。与恭二对话的时间是她在现实世界里少数可以轻松下来的瞬间。但是在克眼自己心底深处的那段黑色记忆之前，诗乃根本无法考虑任何其他的事情。

「谢谢你的招待。还有……真的很谢谢你救了我。你那时真是帅毙了。」

诗乃一边站起来一边这么说道，恭二露出笑容并搔着头说：

「我可以一直保护你唷。那个……放学的时候……我到学校去接你吧？」

「不、不用了，不要紧的。我也得学会自立自强才行。」

诗乃这么回答完后便笑了起来，而恭二则再度像看到耀眼的东西般眯起了眼睛。

爬上长年被雨水侵蚀而染上浅黑色斑点的水泥阶梯后……

第一道门后面便是诗乃独居的公寓房间。由裙子口袋里拿出钥匙，接着将它插进旧式电子锁内。在小小面板按下四位数密码后转动钥匙，接着便响起「喀嚓」的沉重金属音。

进入微暗的玄关，顺手便将门关上。

转上门锁，确认过上锁的铃声后，诗乃才无声地说了句「我回来了」。当然里面没有任何回应。

细长的空间由入口门框处往内延伸了三公尺左右。右边是卫浴设备的门，左边则是小小的厨房。

将从超市买来的蔬菜与豆腐放进水槽旁的冰箱，接着来到里面六张榻榻米大小的空间后，诗乃才松了一口气。借着由窗帘透入的最后一点夕阳按下墙壁上的开关，电灯马上就亮了起来。

房间里面没有什么装饰品。木质系的防滑瓷砖地板加上没有任何图案的象牙色窗帘。面对右边墙壁处则有一张黑色折叠床与并排在里面的暗黑色书桌，对面墙边则有一个小衣柜、书架与全身镜，这就是诗乃房间里所有的摆设了。

诗乃将书包放在地板上，开始解开脖子上的白色围巾。随后脱下大衣并将它挂在衣架上，然后将它和围巾一起收进衣橱里。将带有光泽的暗绿色裙子由接近黑色的水手服里拉出来，当诗乃准备拉下左侧的拉链时忽然停下动作，开始将视线转向书桌看去。

今天放学之后虽然遇到了一连串的事故，但敢正面面对远藤她们的威胁让诗乃心中还留有一点点自信。虽然差点就引发恐慌症，但即使如此他还是一直坚持到最后都没有逃走。

而且两天前在GGO里，与至今为止所遇见过的最强敌人经过一番死斗并击败他这件事，也让诗乃感觉到心灵的强度又往上提升了一个层次。

新川恭二告诉她那个名叫怪物的男人在团体战里还未逢敌手。而那个男人身上也确实散发出名符其实的庞大压力。这让诗乃在战斗中曾数度有败北与死亡的觉悟——但最后还是奋力赢得了胜利。

说不定……

说不定现在已经能正面面对并且击败那个记忆了呢。

诗乃停止动作，一直盯著书桌的抽屉看。

数十秒之后，诗乃将右手上的围巾丢到床上，接着迅速走向书桌。

她深呼吸几次，将缠在背脊上的胆怯给赶跑。

接下来将手放在第三层抽屉的手把上，然后慢慢将它拉开来。

可以见到里面排着将各式文具分类放好的小收纳盒。随着把手慢慢被往后拉，抽屉内侧也露了出来。不久之后空间里终于不再是收纳盒，而是「那个」东西出现在诗乃眼前。那是闪烁着暗沉光辉的小小玩具。

原来是一把塑胶制的模型枪。但是看得出来制造得相当精细，连细部线条都完全重现的表面看起来就跟金属没有两样。

光是看见它的摸样，诗乃就得压抑自己开始加速的心跳，但她还是伸出了右手。先畏畏缩缩地碰到枪的手把，接着握住并将它拿了起来。她手上立刻有了沉重的感觉。吸一口房里的冷空气让她感觉整个人都像要冻僵了。

这把模型枪不是模仿现实世界实际存在的枪械所制造出来的。枪把由符合人体工学的曲线所构成，大型的扳机护圈正上方直接有大口径枪口延伸出来。上面开有散热孔的粗犷机关部直接就在手把后上方的位置，这种形状似乎被称为小牛头犬式的枪械。

枪支的名称是「前犬星SL」，是在Gun Gale Online里登场的光学枪。虽然属于手枪的一种，但却有全自动射击模式，许多人喜欢将它拿来做为对怪物战斗时的辅助武器。

诗乃在格洛肯的储藏库里也有一把这种枪械，但在现实世界里的这把模型枪并不是她自行购买的。说起来一般市面上其实也根本买不到。

那是两个月前参加Bullet of Bullets决赛，结果只获得第二十二名的几天之后。GGO营运公司「ZASKAR」忽然寄了封英文电子邮件到诗乃的帐号里。

辛苦地搞懂内容之后，才知道原来是参加BOB可以获得奖品，而营运公司要诗乃选择在游戏里获得赏金或是道具，又或者是在现实世界里领取前犬星SL的模型枪。

虽然只是玩具枪，但诗乃可受不了在现实世界里收到这种东西，于是她马上想要选择在游戏里领取奖金，但忽然又转念一想。

为了确认GGO这个「猛药」治疗的结果，将来还是需要在现实世界里触摸模型枪。但诗乃实在提不起勇气自己前往玩具店购买。虽然只要拜托恭二的话他一定十分乐意借给诗乃，但一想到拿起枪械后当场发作的可能性就又让诗乃感到犹豫。就算还有网路购物这种最简单的方式，但连在网站上看着一大堆枪械照片都会让诗乃感到心情沉重，所以也就一直无法付诸实行。当然经济上的问题也是一个重点。

如果GGO营运公司可以免费寄送模型枪过来的话，那不就刚好符合自己的需求吗——诗乃一直犹豫到将近截止期限时，才选择接受在现实世界里的参加奖。

一个礼拜后，一个沉重的国际快递包裹来到诗乃家。

明明已经决定要开封了，但最后还是多拖了两个礼拜的时间。

结果当时所产生的反应完全不符合诗乃的期待。于是她只好将模型枪丢进抽屉深处，然后连相关记忆也塞到脑袋的角落里。

而现在——诗乃再度拿起了那把前犬星。

枪上的冰冷触感由右手掌传达到上臂再到肩膀，最后像是要钻进诗乃心底深处一样。虽然是树脂制的模型却有着无比的重量。游戏里的诗乃可以用指尖轻松旋转的手枪，现实世界里拿起来后却感觉像被铁链锁在地面上一样。

手掌的温度逐渐被夺走，反倒是枪支开始发热起来。在冷汗所带来的潮湿微温里，诗乃确实感觉到某个人的气息。

是谁？

那是……那个……男人的……

心跳已经快到无法抑制，冰冷的血液发出沸腾声并且在诗乃全身到处奔驰。这时她的意识已经逐渐模糊。感觉脚边的地板开始倾斜并且变软。

但是诗乃的眼睛还是离不开枪支的黑色光辉。那道光线就在超近距离下冲进诗乃眼睛里。

她已经开始耳鸣了。不久之后声音变成尖锐的尖叫声。那是一名年幼少女被纯粹恐怖所掩盖时所发出的叫声。

是谁在发出悲鸣？

那是…………我。

诗乃没有看过父亲的长相。

不是现实世界里没有关于父亲的记忆。而是真的连照片或影像上都没见过那身为诗乃父亲的人物。

听说父亲在她两岁时就因为交通事故而去世了。

那人是双亲带着诗乃，一家三口为了回去母亲的老家过年而驾车行驶于东北的某县境上。当时车子是在沿着山坡斜面延伸的旧单线道路上行驶，离开东京之后时间已经过了半夜十一点。

由现场打滑的车胎痕迹判断出事故的原因是出自于对向车道来不及转弯的大卡车。

卡车驾驶当场冲破挡风玻璃掉在路面上立刻死亡。

而右侧面遭到卡车撞击的小型车则越过护栏掉落到山坡下，最后被两根树木挡住才停止下跌。这时候驾驶汽车的父亲虽然身负意识不明的重伤，但还不至于立即死亡，而在助手席上的母亲则只是左大腿单纯骨折而已，至于年幼诗乃则因为后座婴儿安全座位的安全带而几乎毫发无伤。但是当时的事情她可以说是一点印象都没有。

不幸的是地方上的人几乎不使用这条道路，尤其深夜更是人烟罕至，而车内的电话也因为撞击而破损了。

隔天早上，当经过这条旧道路的驾驶注意到有事故发生而报警时，已经是六小时之后的事情了。

这段时间里，诗乃的母亲只能在旁边看着因为内出血而身体逐渐冰冷，最后更因此而死亡的父亲。

这时母亲心底深处的某个部分便因此而崩溃了。

事故发生之后，母亲的心智年龄回到与父亲相识之前的十几岁左右。虽然母亲与诗乃离开东京的房子回到娘家去，但母亲随后便将父亲的遗物，像是照片或是影像等全部处分掉，也从来不向诗乃提及关于父亲的事情。

冀求平稳与寂静的母亲开始过着宛若乡下少女般的俭朴生活。虽然发生事故到现在已经过了十五年的时间，但诗乃还是搞不清楚母亲究竟是如何看待她这个女儿的。或许只是认为她是妹妹也说不定，但幸运的是事故发生之后母亲还是深爱着诗乃。她还记得每到夜晚母亲都会读绘本、唱摇篮曲给她听。

所以诗乃记忆里的母亲总那是副容易受伤的脆弱少女模样。自然也让诗乃从懂事开始，便时常告诉自己一定要坚强一点。自己要保护妈妈的安全才行。

过去曾发生祖父母不在时，难缠的推销员坐在玄关前不愿离开，让母亲感到相当惊慌失措的事件。这时年仅九岁的诗乃便对推销员说如果不离开我就报警，然后把他赶了出去。

对诗乃来说，外面的世界充满了打扰母亲平静生活的各种要素。她脑袋里总是想着自己一定要保护妈妈、自己一定要保护妈妈。

所以——诗乃心里觉得就某种意义上来说，她是命中注定会遇上那件事故的。这是不断被诗乃拒绝的外界事物对她的恶意报复。

十一岁，升上五年级之后的诗乃也不怎么在外面游玩，放学之后直接回家看从图书馆借来的书，可以说是他每天的习惯。虽然他的成绩很好但几乎没什么朋友。而且他对于外界的干扰异常敏感，曾经有男孩子恶作剧将她的室内鞋藏越来，结果诗乃便狠狠将对方揍到流鼻血为止。

时间是进入第二学期之后的某个星期六下午。

诗乃与母亲一起到附近的小邮局去。当时邮局中除了她们之外就没有其他客人了。

当母亲将资料拿到窗口去时，诗乃就坐在局里的长板凳上一边晃着脚，一边看着带过来的书本。现在她已经不记得那本书的书名了。

「叽」一声的开门声让她抬起头来，随即就看见一名男人走进邮局。那是一名穿着灰色服装，一只手上拿着波士顿包的瘦小中年男子。

男人在入口处停下脚步，往邮局内看了一圈。诗乃瞬间和他四目相对。这时诗乃心里还想着这人瞳孔的颜色真是奇怪。像个黑洞般的黑色瞳孔在泛黄眼白中央不停移动着。现在回想起来才知道，那是瞳孔已经异常放大的状态。事后发现男人在进入邮局之前已经先注射过毒品。

诗乃还来不及感到讶异，男人便直接朝窗口走去。

这时诗乃的母亲正在「储汇款」窗口进行手续，但男人忽然用力抓住她的手腕并将她拉了过去。接着又用左手将她狠狠推开。诗乃的母亲只能无声地往后倒，整个人还因为太过震惊而瞪大眼睛无法动弹。

诗乃马上站了起来。当她准备大声为心爱的母亲所遭受到的无礼暴力提出抗议时……

男人将波士顿包用力往柜台上一放，接着从里面抓出某样黑色物体。当男人用拿在右手上的物体指向窗口的男性职员时，诗乃才发现他手上的东西是把手枪。手枪——玩具——不，应该是真货——强盗？诗乃的脑袋当中瞬间闪过这几个单字。

「把钱放到包包里面去！」

男人用嘶哑的声音叫着。接着又马上叫道：

「把两手都放到桌上！别想按警铃！其他人也别乱动！」

他左右晃动手枪，牵制着邮局内部的其他职员。

诗乃这时考虑是不是要冲到邮局外面去求救。但因为放不下倒在地上的母亲而迟迟没有付诸实行。

当她正犹豫不决时，男人再度叫了起来。

「快点把钱放进去！有多少钱全部放进去！动作快一点！」

窗口的男性职员虽然绷着一张脸，但还是用右手拿了一叠大概有五公分厚的纸钞递了出去……

就在那个瞬间……

感觉邮局里的空气一口气膨胀了起来。接着双耳更感到阵阵麻痹，诗乃过了好一阵子之后才发现那是尖锐的爆炸声所造成的现象。接下来则是有「锵」的小金属声出现，某样东西弹到墙壁上后滚落到诗乃脚边。原来是一个金色的细长筒状物体。

再抬起脸来时，发现柜台内侧的男性职员瞪大眼睛，两手按住自己胸口。领带下方的白色衬衫稍微可以见到一片红渍。接下来男性职员随着椅子整个向后倒，身旁的文件收纳盒也跟着倒了下去。

「不是要你别按警铃了吗！」

男人尖锐声音的已经整个沙哑。握住枪的右手也开始不断发抖。诗乃鼻子里还闻到一股类似烟火的味道。

「喂，你—来这里把钱装进去！」

男人的枪口对准了两名呆立当场的女性职员。

「快点过来！」

男人尖锐的声音响起，但女性职员们除了轻轻摇了摇头之外就没有任何行动。虽然他们应该都有受过遭遇强盗事件时的应对训练，但是无论什么样的教战手册都无法抵挡眼前的子弹。

男人急躁地用脚踢了柜台下方好几次，接着可能是打算再对一名职员开枪吧，只见到他再度抬起握着枪械的右手。两名女性职员一边尖叫一边蹲了下去。

男人见状便半转过身子，改为面向客人使用的空间。

「继续拖拖拉拉我就再杀一个人！我会开枪哦！」

男人瞄准的目标是——倒在地上，以空虚眼神望着天花板的诗乃母亲。

眼前正在进行当中的事件所造成的负荷实在太大，所以母亲根本完全无法动弹。诗乃瞬间这么想着。

——我得保护妈妈才行。

这从幼儿期以来就一直是诗乃的信念，也让她开始产生一股展开行动的意志力。

丢下书本往前冲出去的诗乃一把抓住男人拿着手枪的右手，接着用力咬了下去。小孩子锐利的牙齿很简单便陷入男人的肌肉里。

「啊啊啊？」

男人发出惊愕的声音，接着将整只右手连同诗乃一起甩了起来。诗乃的身体被甩到柜台侧面上，同时也撞掉两颗乳牙，但她却浑然不知。因为这时从男人手上滑落的手枪滚到她面前来。诗乃不由自主地将它捡了起来。

好沉重。

两条手臂马上就感觉到金属的重量感。上面刻有横线的手把因为男人的汗而相当潮湿，更因为男人的体温而像生物般散发出热量。

即便以诗乃当时的知识，也能知道这是用来做什么的道具。只要使用这东西，就可以阻止那个可怕的男人。脑海里有了这样的想法后，诗乃便模仿刚才看到的姿势举起手枪。然后将两手的食指放进扳机里并对准了男人。

此时男人一边发出怪声一边往诗乃扑了过去，准备将手枪由诗乃手里夺下来般用自己的双手紧紧握住诗乃的手腕。

诗乃到现在仍弄不清楚男人做出这样的动作究竞是帮了她还是害了她。但单就事实来看，男人确实自己帮忙稳定了面对着他的手枪。

现在诗乃对于那把被用来抢劫的手枪——已经有了相当充分的知识。

一九三二年，也就是距今九十年以上的遥远过去，苏维埃陆军正式采用了「托卡列夫TT33」这款手枪。不久后中国便加以模仿并将其称为「五四式·黑星手枪」。这便是那把枪的名称。

它使用三十口径，也就是七点六二毫米的钢芯弹。后来出现的手枪是以九毫米子弹为主流，相较之下黑星的口径显得较小，但它的火药量却较多。因此子弹的初速可以超越音速，拥有手枪当中最强大的贯穿力。

但最后因为后座力过大，苏联便在一九五零年代时以使用小型化九毫米弹的「马卡洛夫」来取代了这款手枪。

所以一名十一岁的孩童怎么可能有能力操纵一把这样的手枪来射击敌人。但是当诗乃手腕被对方握住，脑里想着枪要被夺走了的瞬间，反射性地扣下了扳机。

猛烈的冲击由两手上往手肘、肩膀上传递，枪口应该已经被转往别处的后座力几乎全被男人的双手所吸收。这时空气里再度产生一股热流。

男人发出像打嗝的声音并放开诗乃的手腕，接着直接往后退了几步。

男人那花纹灰衬衫的腹部忽然有一道红黑色的圆形急速扩散开来。

「啊啊……啊啊啊啊！」

男人一边尖叫一边用两手按住腹部。可能已经伤害到动脉了吧，可以见到从他指间流出一条血迹来。

但是男人仍未跌倒。黑星所使用的小口径钢芯弹会马上贯穿人的身体，制止能力本来就比较低。

男人一边怪叫一边将沾满血的双手往诗乃仲去，想要再度抓住她。由伤口飞散出来的血液落到诗乃的双手上。

这时她的双手再度像痉挛般抖动，接着又再次扣下扳机。

这次手枪整个向上弹起，让诗乃的手肘与肩膀感到一阵剧痛。她的身体整个向后弹，背部用力撞击柜台而暂时无法呼吸。她已经不太能听见发射声了。

第二发子弹命中男人的右锁骨下方，接着再度贯穿身体击中他背后的墙壁。男人一个踉跄，因为自己流出来的血而滑倒，整个人倒在亚麻油地毯上。

「哇啊啊啊啊！」

但是男人的动作仍未停止，他发出愤怒的咆哮，用两手撑住地面准备站起身来。

诗乃因此陷入恐慌状态。她感觉这次如果不确实让男人「停止」动作的话，自己和母亲绝对会被男人杀害。

诗乃无视两条手臂与肩膀上的剧痛继续往前走了两步。这时男人正以脸孔朝上的姿势将上半身撑起了二十公分左右，而诗乃则是将枪口对准了他身体的中央部位。

诗乃的肩膀因为第三次射击而脱臼。这次已经没有东西可以挡住她因为后座力而往后弹的身体，于是她整个人翻了个筋斗后才倒在地上。但她的手却依然紧抓住手枪不放。

与刚才同样由不稳定手枪里发射出来的子弹完全偏离诗乃瞄准的目标，命中男人身体上方数十公分处——

刚好也就是男人脸孔的中央部位。男人的头部咕咚一声直接砸在地板上。然后再也不会动也不会发出声音。

诗乃拼命撑起身体，确认男人已经再也无法动弹。

——成功了。

她首先有了这个念头。自己成功地保护了母亲。

诗乃动着脸部，将视线朝倒在数十公尺外地板上的母亲看去。接着便发现最爱的母亲双眼里——

明显透露出对诗乃感到恐惧与怯懦的感情。

诗乃这时才往自己的手上看去。到现在还紧紧握住枪把的双手上沾满了红黑色的液体飞沫。

这时诗乃才张开嘴巴发出尖锐的悲鸣。

「啊啊啊啊…………！」

她一边由喉咙深处发出细微叫声，一边持续凝视着两手握住的前犬星SL。似乎可以见到从手背往指尖滴下去的血液。而且就算眨了好几次眼睛血液都还是没有消失。只见那浓稠状液体一滴一滴的滴落在脚边。

突然从她双眼里也冒出液体。视线一下子变得模糊，只能看见模型枪的黑色光辉而已。

从黑暗的深渊里出现了那男人的脸。

发射出去的第三发子弹便是往这张脸飞去。被子弹击中之后伤口却出乎意料之外的小，看起来就像颗黑痣一样。但是随即就有一阵浓烈的血雾飘敌在头部后方。脸上原本有的表情与生气瞬间便消失无踪。

但是他的左眼忽然动了起来．用那行如无底深渊的瞳孔瞪着诗乃。

他就这么笔直地看着诗乃的眼睛。

「啊……啊…………」

诗乃的舌头忽然紧贴在喉咙深处，开始感到无法呼吸。同时胃部也开始剧烈地收缩。

她咬紧牙关，用尽全部心力将前犬星丢在地板上，接着立刻摇摇晃晃的跑到厨房，用满是冷汗的右手拉开卫浴的门把。

拉起马桶盖，在弯下身体的同时，热辣的液体也从胃的匠部冒了上来。诗乃扭动身体不断痉挛，像是要将体内所有物体给排除体外般不停呕吐着。

当胃部的收缩好不容易开始停止时，诗乃整个人已经虚脱了。

她伸出左手，按下马桶上的冲水手把。辛苦地站起身并将眼镜拔下来后，开始不断用双手捧起洗面台里流出的刺骨冰水来洗脸。

最后她漱了漱口，从架子上拿了条干净的毛巾擦完脸才离开浴室。此时她的思考能力已经完全麻痹了。

她踩着虚浮的脚步回到房里。

诗乃尽可能地别开视线，然后用手里的毛巾盖在滚落在地板的模型枪上。隔着布将它拿起来后，马上将它塞进打开的抽屉深处。用力关上抽屉后，精神完全消耗殆尽的诗乃才整个人趴在床上。

由湿濡前发上滴落的水滴混杂着脸颊上的泪水在棉被上留下了痕迹。不知从何时开始，诗乃以细微的声音不断这么重复说着：

「救救我……谁来……救救我……救救我……谁来…………」

事件过后几天的记忆其实已经有些模糊。

像是穿着深蓝色制服的大人们以紧张的口吻要她把枪交出去时，她的手指因为僵硬而根本离不开枪支。

还有许多红色的旋转电灯与随风摇晃的黄色布条。布条后面则是有许多让人睁不开眼睛的白色闪光。

或者是坐上警车时才注意到右肩的疼痛，当她畏畏缩缩地告诉警方之后，警察才赶紧让她换乘到救护车上去——诗乃脑里大概就只有这些片段性的记忆。

躺在医院的床上时，两名女警不断询问诗乃事情的经过。虽然她一直要求想见母亲，但这个愿望在过了许久之后才得以实现。

诗乃三天之后便离开医院回到祖父母家里，但母亲却入院长达一个月以上。而事件发生之前的平稳日子，则是再也没有回到她们身上。

由于各家媒体的自我规范，让事件的详细经过没有被大肆报导山来。送交检察机关的文件里只注明持枪抢劫邮局事件的嫌疑犯死亡，此外也没有进行任何公开审判。但是祖父母的老家是个很小的城市。邮局里所发生的经过被详细地——应该说变成加了各种情节的谣言，就如同燎原之火般迅速传遍整个城市。

小学剩下来的一年半时光里，诗乃被冠上所有可以代表「杀人犯」的名词，而上了国中之后周围则变成完全无视她这个人的存在。

但是周围的眼光对诗乃来说其实没有什么影响。因为她本来就对加入哪个集团这种事情没有兴趣。

只是过了这么多年之后——事件在诗乃心中所留下来的伤痕还是一直让她感到非常痛苦，丝毫完全没有痊愈的迹象。

自从事件发生过后，诗乃只要看见枪械类的东西便会引起当时的鲜明回忆，让她整个人陷入剧烈的休克症状当中。不论是在路边看见小孩子手上的玩具手枪，或是在电视画面上看见枪支，都很容易引发呼吸急促造成全身僵硬、失去定向感、呕吐，严重时甚至会丧失意识等症状。

因此诗乃几乎不能观看戏剧或是电影。也有好几次因为看了社会科课程的教学用录像带而发作。国中时期她都是靠着在图书馆阴暗角落里看着比较安全的大开本小说全集——也仅限定于古早以前的文学作品——来打发时间。

当她对祖父母表示国中毕业就想到远方去工作，因而遭到强烈反对时，诗乃便说那至少让她到过去——当她还是婴儿时与父母亲一起生活过的那个东京某区去念高中。她确实是想到一个没有缠人的传闻与好奇视线的地方去。因为她可以确定，只要继续在这个小城市里生活，那么她的心理创伤将一辈子都无法痊愈。

当然诗乃的症状已经被诊断出是典型的创伤后压力症候群，四年来也已经接受过无数的心理咨询。而且她也乖乖按照医师的指示服药。但脸上似乎都带着相同笑容的医师们所说的话，都只能轻抚或是搔过诗乃心灵的表层，根本无法到达受伤的地方。他们在干净的诊疗室里不断说着「我了解，那一定很痛苦吧。真难为你了」这种话，但诗乃却是边听边在心里重复嚅嗫着：

——那你们有用枪杀过人吗？

如今她也已经自我反省，就是这样的态度造成自己无法信赖医生，让治疗一直无法收到成效。但即便是到了现在，那依然还是诗乃毫无掩饰的真心话。自己的所作所为究竟是好还是坏——或许诗乃只是想要听见他们对此提出确定的看法而已吧。当然没有任何一个医生能够回答就是了。

但是就算再怎么为记忆与发作所苦，诗乃也从没有过自己结束生命的念头。

她不后悔对着那个男人扣下扳机。当他拿着枪对准母亲时，诗乃也只能那么做了。就算现在再回到事件发生的瞬间，她也会做出同样的行动。

一旦选择了自杀这条逃避的路，那么那个男人也就白死了，诗乃是这么认为的。

所以她才会想要变强。想要获得能讲出「那种情况之下，我那么做也是理所当然」这种话的勇气。就像一个在战场上毫不留情打倒敌人的女战士一样。她会想要过独居生活也是这个原因。

国中毕业离开老家之前，诗乃告别的对象只有祖父母，以及跟事件发生前一样把她当成幼儿般拥抱并抚摸头发的母亲。

接着诗乃便移居到这个空气刺鼻水又难喝，什么东西都贵得要死的城市来。

而她就是在这里遇见了新川恭二以及VRMM——「Gun Gale Online」。

呼吸与心跳终于渐趋平稳，诗乃也将薄薄的眼睑抬了起来。

整个人趴在床上，左脸颊靠着枕头的诗乃，视线前方映入了一个长形物体。

镜子里有个前额贴着湿濡头发的少女正回看着自己。那名少女略嫌瘦削，但又有着一双大眼睛。除了小小的鼻子之外，两片嘴唇也相当单薄。总而言之给人一种营养不良小猫的印象。

只有体格与脸颊两旁绑起一小撮的短发和荒野狙击手诗乃雷同，但其他地方就找不出任何相似之处了。游戏里的诗乃就像只狰狞的山猫一样。

带着非常恐惧的心情登入GGO，然后被带到完全搞不清楚状况的战场上时，诗乃有了意想不到的发现。或许是与现实世界日本完全不同的异世界风景所造成的吧——她在这个世界里不论怎么触碰枪械，不，应该说就算用枪械来击倒其他玩家都只是感到有点紧张而已，那可憎的发作完全没有出现。

诗乃确信自己终于找到超越那些记忆的方法。实际上自从她进入GGO世界之后，只是看见枪械照片的话已经不会发作，也可以和恭二谈论起GGO里的武器。

其实还不只是这样而已。诗乃现在已经深爱着半年前入手，那把名为「黑卡蒂Ⅱ」的巨大凶恶狙击枪。就像同年龄的女孩子喜欢摸着宠物或玩偶一般，诗乃只要抚摸它平滑的枪管就能够冷静下来，只要将脸颊靠在那略圆的枪托上就能感到温暖。

只要能和它一起不断在假想的荒野里作战，伤口总有一天会愈合，恐惧也会消失不见。诗乃就是根据这个信念来以必杀的子弹终结无数怪物与玩家的生命。

但是……

——真的可以吗？真的这样就可以了吗？

心里有一道反问她的声音。

游戏中的诗乃已经名列数万名GGO玩家里的第二十二名了。大家都说操作反物质狙击枪的能力已经无人能出其右，而被她瞄准镜所捕捉到的玩家最终都只有死路一条。她过去强烈想成为「拥有一颗冰冷心脏的战士」的心愿，可以说是已经成功了。

但是——现实中的诗乃却还是连一把模型枪都拿不起来。

真的……真的这样就够了吗……？

镜中少女在眼镜深处的瞳孔摇晃着一股无所适从的感情。

从去年开始戴的这副眼镜其实没有度数。因为它不是矫正视力的工具而是诗乃的「防具」。由NT聚合物所制的镜片，就算被子弹击中也不会碎裂——宣传单上面是这么写的。虽然不知道是否属实，但节省生活费之后所配的眼镜还是给了诗乃些微的安心感。现在外出时如果没戴眼镜就会觉得心慌。

但这也就以为着她还得依靠这种小道具来让自己安心。

用力闭上眼睛之后，胸口再度产生了软弱的疑问。

谁来……告诉我……我该怎么办才好……？

——但是没有任何人会对我伸出援手！

诗乃为了驱赶软弱的声音在心里这么大叫着。她撑起身体，视线往床旁边的小桌子上看去。马上发现AmuSphere的银色圆环正在发光。

只是自己的实力还不够而已。问题就是这么简单。

那个世界里还有二十一名比诗乃还要厉害的枪手。只要击败他们，将他们全送进冥界，成为荒野里唯一的最强者，那个时候——

诗乃就能和游戏里的自己一体化，在真实世界里也可以得到真正的坚强。届时「那个男人」与「那把枪」将会被掩埋在所有被诗乃击毙的目标当中，再也不会出现在记忆里面。

诗乃捡起空调的遥控器，将暖气打开后一口气将制服上衣脱了下来。接着解开裙子挂勾由脚上将它脱下，然后全部扔到床上。最后拿下淡蓝色眼镜，轻轻将其放在书桌上。

她整个人躺到床上，拿起AmuSphere并戴上去。

用手摸到电源并按下，当宣告准备完成的电子声一响起，她马上就开口说道：

「开始联机。」

她呢喃的声音就像个哭累的孩子般，虚弱又沙哑。

** 第五章

打开浏览器的同时，马上就自动联机至设定为首页的网站，好几个卷标与窗口重叠着出现在屏幕上。

那些网站全部与Gun Gale Online相关，尤其是刊载「死枪」资料的网站更是全部都被收集到这里来了。

「他」用右手指尖操纵着3D鼠标，联机至目前最受瞩目的网站上。该网站首页就有「死枪情报总整理网站」的字样，死枪这两个字还特别使用红色字体。

首先看一下更新履历，确认过今天管理人还未更新情报后。接着便转到留言板去。前天晚上确认过之后又多了几篇新留言，记事标签上闪烁着「New」的字样。「他」开始依序往下看着内容。

——ZED与鳕鱼子一直都没出现耶。已经一个月了吧？这样账号应该已经过期了才对？真实世界里能和他们连络的人，有什么情报请PO上来吧。

——根本没人能联络得上他们。他们中队的成员不是也说过不知道他们真实世界里的联络方式了吗？应该说笨蛋才会在GGO里透露自己的真实情报呢。

——被死枪击中的日子与时间都相当清楚，如果他们两个真的死掉了，只要调查一下那个时间里有没有VRMMO玩家死亡不就能知道了吗？

——别又绕回原来的话题，去爬一下文好吗。一个人独居的话就算死了也没人会发现。而且也确认过警察根本不会透露相关情报了。顺带一提就算写英文邮件去问ZASKAR，对方也只是回些无法透露玩家个人情报的定型文件而已。

——这一定是ZED大大和鳕鱼子大大他们的引退恶作剧啦。两位再不出来承认的话差不多就要失去新鲜感啰！

——结果还是得有人亲身去体验才知道是不是真的。所以呢明天晚上十一点半时我会在胸前插朵红玫瑰然后再格洛肯中央银行前等待，死枪先生拜托来攻击我吧。

——勇者登场！不过死之前不把你的本名与地址透露出来就根本没意义了吧！

——倒不如在某间网咖里进行公开潜行吧。

……

「他」焦躁地咋了一下舌头，接着开始移动鼠标滚轮进入下一个窗口当中。但是不论哪个留言板或是情报网站都找不到「他」希望看见的情报与留言。

当初的预定是让第二个人死亡时，「死枪」拥有真正杀伤力的传闻便会在网络上传开，而GGO玩家们便会开始陷入下一个目标会不会就是自己的恐惧——接着不断出现退出游戏的玩家。

但是实际上到现在愚蠢的网络乡民们都还没发现「死枪」给人的真正恐怖，一直都在进行那种开玩笑的对话。GGO的玩家账号总数也完全没有减少。

现实世界里「ZED」与「薄盐鳕鱼子」的死亡完全没被报导出来可以说是出乎人意料之外，看来都内一天里都会有许多相当怪异的死亡事件，只要没有明显犯罪性的事件就不会登上新闻报导。

当然「他」很确定遭到自己枪击的两个人，现实世界里的心脏已经停止并且死亡。因为这就是「死枪」的威力。

把这个情报写进网站留言板的诱惑实在十分强大。但是「他」也无法提出具体的证据，而且这么做的话将会让「死枪」的传说性变薄弱。「死枪」是降临在那片荒野里最初也是最后的绝对强者，甚至可以凌驾营运公司，因为它才是真正的死神。

——算了。

「他」深深叹了口气，想办法让心情平静下来。

马上就要举行第三届「Bullet Of Bullets」了。「他」预定用「死枪」在这场大会里再结束两个人，可能的话三个人的性命。当然得先不靠那把枪来突破预赛才行，但靠着每天登入二十小时所锻炼出来的能力值，要达到这个目标应该不是太难才对。

BoB如今可以说是广受瞩目。在「MMO动向」里播放的现场实况转播除了GGO之外有许多VRMMO玩家会收看。自己除了要在那个大舞台里成为名符其实的最强者之外，还要让人家看见被那把枪击中的人再度从网络上消失，如此一来应该就没有笨蛋会质疑「死枪」的能力了。

不过吸引那么多目光之后，现在的账号就不能够再使用。但只要有那把枪，要成为新的「死枪」然后重新降临在荒野可说是轻而易举。

「他」接下来还要继续杀戮。自己的预定是要让七名玩家成为枪下亡魂。那时候应该会出现许多引退的玩家，不久后这款名为「Gun Gale Online」游戏将完全死亡。

而「死枪」将会变成传说。

虽然造成的死亡人数远远比不上那个被诅咒的死亡游戏「Sword Art Online刀剑神域」，但那只是一名狂人用电磁波将玩家的脑烤焦而已。

「死枪」拥有的才不是那种低次元的力量。由假想世界里发射出来的子弹能让现实世界里的心脏停止。能了解这个秘密的就只有「他」以及「他」的分身而已。「死枪」才是真正的最强者。那名传说中完全攻略SAO的「黑色剑士」根本没得比。「他」成为所有VRMMO最顶级玩家的时刻马上就要来临。

绝对的力量——传说中的魔王——最强——最强——最强——……

「他」这时才注意到自己右手上灌注的力道已经几乎要将鼠标捏破，于是他马上一边喘气一边放松紧绷的肩膀。

「他」迫切期盼那一天赶紧到来。只要能造就这个传说，他就不用再待在这无聊的世界里。也可以和老是找「他」麻烦的那些蠢货告别了。

将浏览器上的所有窗口关闭之后，「他」重新叫出了一份区域HTML文件来。

垂直排列的七张脸部照片——将在GGO内部拍摄下来的屏幕影像裁切下来后的照片罗列在屏幕上，每张照片的右边都写着名字与武装等情报。最上方的「ZED」与下面的「薄盐鳕鱼子」都已经变成黑白照片，然后上面还被打了个血红色大。

这就是「死枪」的目标名单，换句话说，就是装填在那把枪弹仓里的「死亡子弹」数量。这七个人全部都是GGO里赫赫有名的强力玩家。

「他」慢慢卷动文件，将放在最下方的照片移动到屏幕中央。那是七个人当中唯一一名女性玩家。

由右斜角拍下来的屏幕影像上可以见到该角色淡蓝色的短发，以及绑在脸旁的两撮头发稍微遮住脸颊的模样。虽然因为紧团在脖子上的那条土黄色围巾而看不见嘴角，但光是让人觉得像猫的蓝色眼珠就足以让她散发出迷人的魅力。

显示在右侧的名字是「诗乃」。主要武器是反物质狙击枪「Ultima Ratio HecateⅡ」。

「他」曾好几次直接在游戏内部见到这名少女。无论是在格洛肯街头购物的模样、在公图板凳上吃着路边摊热狗的模样，或者是背着巨大狙击枪在战场上奔走的摸样——她的每种姿态都充满诱发人占有欲的妖艳魅力。虽然几乎没有见过她的笑容，眼神里也总是带着某种忧伤，但这些都反而让「他」更加对她着迷。

其实「他」一直很犹豫该不该把这名叫做诗乃的少女选做「死枪」的目标。如果她不只在游戏中，连在现实生活里都愿意把身心交给「他」的话——

但是「他」的另一半，也就是「死枪」的另一只手臂一定很想亲自为少女带来死亡吧。诗乃在GGO里是个冷酷的狙击手，人称冥界女神的她是游戏里无人不晓的玩家。可以说是最适合当成造就「死枪」传说的牺牲品。

「他」伸出右手，用指尖轻轻抚过诗乃的照片。

在光滑面板所带来的触感当中，「他」确实感受到那名少女柔软的肉体与温度。

** 第六章

我打起方向灯，将车身往旁一压通过一道大门。

这时我立刻感觉到走在行道树道路两旁的行人投射过来的责备眼神，于是我只好赶紧将摩托车的速度放慢下来。

这辆泰国制一二五CC.2行程中古破烂摩托车是我靠着艾基尔的关系买来的。在这个电动速克达已经成为主流的年代，我的车子总是发出让人感到绝望的噪音，当直叶坐在后座时老是抱怨「又吵、又臭、又不好坐」。而每当她这么抱怨时，我都会借着「不懂这种声音的话就没办法变成风唷」这种话来蒙混过去．但其实我内心也暗暗觉得早知道就买台排气量规范之后的4行程速克达了。

尤其是现在正经过这种医院内用地，懊悔的想法也就更加浓烈了。

用老驴拖车般的速度缓缓在两旁都是行道树的道路上行驶一阵子后，前方终于见到停车场入口。我一边松了口气一边将机车骑进去。接着把车停在机车停车场角落。拔起现在已经很少见的两段式车轮匙并拿下安全帽后，随即有股消毒水味道乘着十二月的寒风飘了过来。

今天是跟菊冈进行高级蛋糕会谈一个礼拜后的星期六。

当他传来电子邮件告知登入Gun Gale Online的场所已经准备好了时，我才心不甘情不愿的开始行动，但不知为何他指定的场所竟然是干代田区里一间规模庞大的都立医院。虽然我平常不怎么会到东京都心来，但至少还知道该怎么到这间医院。因为当初从SAO里解放出来的我，便是在这家医院附设的复健中心里进行恢复肌力的练习。

我在将近一个半月的复健后便出院了，但是之后也因为各种检查而时常来到这里。虽然已经将近半年没到这里过，但一抬头看着这栋熟悉的白色建筑物，内心便会涌起一股不知是怀念还是不安的微妙感慨。我轻轻摇头将这股感伤由脑袋里赶跑，接着朝医院入口走去。

就在这时，六天前的礼拜天，我在医院附近的皇居行人步道上对明日奈说明整件事经过的对话又浮现在脑海里。

「……咦、咦咦咦？桐……桐人你不玩ALO了吗……？」

看见明日奈瞪大的眼睛开始有些湿润之后，我急忙用力左右摇着头说道：

「不、不是啦！只有几天而已，然后我就会再转回来了！其、其实……我因为有些事情得到别的VRMMO里去打探一下消息……」

听见我的追加说明之后明日奈才松了口气，但又立刻露出讶异的表情。

「打探消息……？但这之前你不是也用新设帐号做过好几次这种事情了吗？为什么这次一定得用桐人这个角色呢？」

「因为……这次是……那个总务省眼镜大叔的……」

我吞吞吐吐的告诉明日奈，约会地点之所以会选在皇居有一半是因为之前被菊冈诚二郎叫到附近，然后也把我和菊冈的一部分对话说了出来。

到达出口时刚好把整件事说明完毕，当我们将入场券还给收票窗口准备经过壕沟上的平川门桥时，明日奈用相当复杂的表情这么对我说道：

「是菊冈先生的请托吗……那就没办法了…………虽然我还是没办法完全信任那个人……但他确实帮了我们不少忙……」

「嗯，我也跟你有同样的看法。」

这时我们两个都露出了苦笑。

但是明日奈马上就恢复认真的表情，紧握住我的手说道：

「……那你要快点回来喔。我们的家就只有一个地方而已。」

我点了点头，看着壕沟的水面回答她道：

「那是当然。我马上就会回ALO了。我只是稍微探查一下『Gun Gale Online』这款游戏的内情而已。」

是的——

我没有向明日奈说出菊冈要我登入GGO的真正目的，其实是要和可能拥有某种神秘力量的玩家「死枪」做接触。因为我知道一旦说出来，她不是阻止我，就是会表示要和我一起进入那款游戏当中。

虽然这只是我自私的想法，但我绝对不会让她再靠近有任何一点危险性的假想世界了。

当然我认为「死枪」根本有九成九只是谣言而已。

由假想世界里造成现实世界里的人死亡。再怎么想也没办法相信会有这种事发生。

AmuSphere再怎么说也不过是比一般电视机还要进步一点的机器而已。「假想世界」与「完全潜行技术」虽然让人觉得好像是由科技中诞生出来的魔法一样，但实际上它们也只不过一种方便的道具罢了，绝对不是什么能够把人类的灵魂由肉体分割出来然后带进异世界的魔幻秘宝。

但是那仅存的一分可能性让我不得不来到这个地方。

几个月前，当我在整理PC硬盘内的电子杂志时，发现了身为ARGUS开发负责人的茅场晶彦在SAO开始营运前接受了简短访谈的记事。当时仍活在世上的那个男人曾这么表示……」

——所谓的艾恩葛朗特就是An Inating Radius，也就是「实体化的世界」的简称。各位玩家将在这里面见到无数的梦想化为现实。除了剑、怪物、迷宫这些游戏里才会出现的记号会被实体化之外，那个世界里还存在着足以让玩家本身产生变化的力量——

确实我和亚丝娜都因此而改变了。当然艾基尔、克莱因、莉兹和西莉卡他们在那个世界里生活的两年当中，一定也有足以彻底让他们人格产生变化的各种经验。

但是如果茅场所说的「变化」不只有这种意思而已呢……？托制作VRMMO程序套件「The Seed」的福，现在假想世界链接构造体已经不断无限增殖，如果在它角落里真的出现一种足以让假想世界与现实世界这种分类产生变化的因子呢……？

自动门发出「呜咿」一声后在我眼前打开，迎面而来的暖空气与消毒药水味打断了我天马行空的思考。

不论如何，既然如今现实世界里已经出现两名死者，我也无法断言与「死枪」接触不会发生任何危险。等我回到ALO后，向明日奈说明这一切时一定会让她大发雷霆。但我相信她最后一定会理解我为什么要这么做。

因为对我，也就是切断艾恩葛朗特原本应该已经结束的时间轴，让「The Seed」程序套件扩散出去的桐人来说——除此之外别无选择。

我先去上了厕所，然后才按照打印下来的邮件来到住院病房三楼的指定病房前面。门旁的牌子上没有病人的名字。我敲完门后把门拉开——

「哈啰！桐谷小弟，好久不见了！」

出来迎接我的，是在漫长复健期间一直照顾我的女性护士。

她护士帽下方的长发绑成一条大辫子，尾端的白色小缎带正随着走动而摇晃。身上穿着淡粉红的制服，除了以女性来说算是相当高挑之外，那玲珑有致的身段对住院的男患者来说实在是一种折磨。而左胸上可以见到一块写着「安岐」的小名牌。

她有着一副总是笑脸迎人的娇小脸庞，清秀得让人一见就觉得她简直就是白衣天使的最佳代言人，但是我很清楚她在必要时也能变身成恶鬼，所以我在僵硬一秒钟左右便马上低下头回答：

「啊……你、你好，好久不见了。」

这时安岐护士突然伸出双手，开始捏起我的肩膀、上臂以及侧腹等处。

「哇……哇啊？」

「哦——已经比较有肉了嘛。不过还不够唷，有没有好好吃饭啊？」

「当、当然有了。说起来为什么安岐小姐会在这里……」

我环视了一下房间里面，发现这小小的病房里除了她之外没有其他人在。

「事由我已经从戴眼镜的官员那里听说了。你要帮他进行假想……网络？的调查对吧？你才回来不到一年，竟然就要你帮这种忙。然后他还说希望负责桐谷复健的我，可以帮忙注意显示你身体状况的仪器，所以把我今天的班全都排开了。他好像已经和护士长说好了，真不愧是有国家权力的人。总之暂时要请你多多指教啰，桐谷小弟。」

「啊……那、那就麻烦你了……」

菊冈你这家伙，搞这种小动作不就好像我对美女毫无抵抗力一样吗~我在心中暗暗咒骂不在场的探员，然后笑着握了握安岐护士对我伸出来的手。

「……那个戴眼镜的官员不会来吗？」

「嗯，好像说有一定得参加的会议。不过他托我把这封信交给你。」

打开护士交给我的茶色信封，把一封手写信拉了出来。

『报告书就请你传到以往的那个信箱里。各种经费等到任务结束后会一起付给你，到时不要忘记申请。附记——不要因为和美女护士孤男寡女共处一室就压抑不住年轻人的冲动啊！』

我瞬间把信连着信封一起揉成一团，然后把它放进骑士外套的口袋里。这要是被安岐护士看到了，难保不会被她告我性骚扰呢。

对边眨眼睛边露出一脸讶异表情的她笑了一下之后，我开口说道：

「啊！……那我想赶快联机了……」

「啊，好的好的，已经准备好了。」

被带到凝胶床那里去的我发现床旁边排着一大堆有屏幕的电子仪器，头垫上那台全新的AmuSphere正发出银色的光芒。

「那把衣服脱掉吧，桐谷。」

「什……什么？」

「我要贴上电极片。反正你住院时早就被我看光了，所以不用不好意思——」

「…………那个……只脱上面可以吗……」

安岐护士瞬间考虑了一下，幸好她后来点头同意我的要求。放弃挣扎的我脱下外套与长袖T恤，接着便躺在床上。护士马上就在我上半身数个地方贴上心电图屏幕用的电极片。AmuSphere虽然也有显示心跳的机能，但菊冈很担心万一被黑客入侵而丧失那种机能时会我有危险。光从这一点来看，就可以知道他倒是真的很担心我的安危。

「好，这样就可以了……」

护士最后确认完机器的屏幕后点了点头，我则是伸手拿起AmuSphere，戴到头上后按下电源开关。

「嗯，那……我要开始了。应该会待在里面四、五个小时吧……」

「了解。我会仔细看着你的身体，你就安心的去进行任务吧。」

「那……那就拜托你了……」

为什么会变成这样呢……事到如今才有这种疑问的我开始闭上眼睛。

同时耳边也响起「叽叽」这种宣告准备完毕的电子音。

「开始联机。」

发出指令之后，早已习惯的白色放射光充满整个视线，我的意识也由肉体里被解放出来。

当我降到那个世界时，一开始便有了些微不适应的感觉。

而几秒钟之后，我马上就知道不适应的理由。那是因为头上是一整片带着淡红与黄色的天空。

我听说「Gun Gale Online」里的时间几乎与现实世界相同。也就是说才过下午一点的天空应该与我刚才透过医院窗户见到的蓝天一样才对。但不知为什么这里竟会是这种忧郁的黄色。

脑袋里虽然想象了各种理由，最后我还是耸了耸肩停止继续思考下去。成为GGO舞台的荒凉大地是设定成最终战争之后的地球。可能是为了给人一种世纪末日的气息才会这么做吧。

我再度把视线朝向伸展在眼前的雄伟都市——GGO世界中央都市「SBC格洛肯」看去。

不愧是SF系VRMMO里最知名的游戏，它的外貌与阿尔普海姆世界树上新设的首都「世界树城市」，或是过去艾恩葛朗特各层主要城市的奇幻风格街道完全不同。

带着金属感的高层建筑群像是要冲破天际般耸立于大地上，各建筑物之间的空中回廊就像网子般连结在一起。大楼间的凹陷处出现许多霓虹灯颜色的全息图广告，而越接近地面广告就越多，整体看起来就像个由色彩与声音形成的瀑布一般。

看了一下自己的脚边之后，发现自己脚下既不是泥土也不是石头，而是由金属板铺设而成的道路。

背后有看起来设定为初期角色出现位置的巨蛋状建筑物，眼前有一条类似主要街道的宽广道路往前延伸。道路的左右两侧罗列着一大堆奇怪的商店，看起来就像是秋叶原巷子里的模样。

而往来于街上的每个行人都散发出狠角色的气息。

这些人绝大部分是男性。可能是作为根据地的ALO女性玩家比例较高，或者是那个世界的玩家外表多是瘦小精灵的缘故吧，看见这么多穿着迷彩军事外套或是黑色护甲的魁梧大汉昂首阔步走在路上的光景后，实在不知道该说让人有压迫感还是有种充满活力的感觉，但老实说他们每个人都很邋遢。此外还都眼露凶光，根本没办法随便向他们搭话。

其实还有另一个理由让我无法随便开口。那就是大部分玩家的肩膀或是腰间都挂着黑光闪闪的杀人武器——也就是枪械。

与可以拿来当成装饰的剑或长枪不同，枪械就只有一种用途而已-那就是拿来当成武器、拿来打倒敌人。它被设计出来的形状与色彩就只是为了达成这些目的。

原来如此，枪械就等于是这个世界的全部吗？我在内心如此想着。

这个游戏世界里存在的就只有完全的「战斗、杀戮、抢夺」而已。在这里可以说见不到任何ALO所提倡的「享受幻想世界里的生活」等要素。

因此像是华丽或可爱的外表反而会变成对自己不利的要素。在战场上为了让敌人感到胆怯，像个凶恶士兵的外表也是重要参数之一。为此男人们多半蓄着大量胡须，不然就是脸上有个醒目的伤痕。

话说回来，我的角色究竟有着什么样的外形呢。

我到这个时候才低头看着自己的身体。为了吸引「死枪」注意并成为他的目标，当然希望自己能拥有一副类似好莱坞电影里那种强壮士兵的体格。

……但我忽然有种不祥的预感。

我发现两手的肌肤可说又白又滑，手指也是出乎意料之外的纤细。穿着黑色军服的身体甚至比现实世界体的我还要瘦小。以视点的感觉来判断，身高应该也不会太高才对。

正如前几天向亚丝娜说明过的那样，我当然不是用全新角色来潜入这款Gun Gate Online。那么做的话不知要到什么时候才能遇上只攻击强者的「死枪」。

利用VRMMO开发支持程序套件「The seed」所生成——更详细一点来说是在「Cardinal」系统上运作的游戏世界里，有一条唯一的最高原则存在。那就是「角色转换机能」。只要使用的是The seed，就绝对无法削除这个机能。

只要利用这个机能，就可以把在某个游戏里培养出来的角色档案与能力直接转移到其他公司营运的游戏里面去。就像只要有手机SIM卡在，就可以在其他手机上使用原本的电话号码一样。

比如说你在A游戏里培养出筋力100、敏捷度80这种数值的角色，然后将这角色移动到B游戏里去。这时游戏A里该角色的强度就会经过「相对平衡」的转换程序，按着在B游戏里变成STR 40、AGI 30这样的角色。更简单一点来说，就是将ALO里「中士」程度的「肉弹战士型」角色转生为GGO里「中上程度的战士」。

当然这不是复制角色能力的机能。进行转换的瞬间，原本世界的角色将完全消灭。而且能移动的就只有角色本体，道具类物品一概无法带出，所以这虽然是个相当方便的机能，但还是需要相当的勇气才能付诸质行。这次为了要将在ALO里使用的「守卫精灵•桐人」转换到GGO来，我事前就把手边所有道具都塞进艾基尔刚在新艾恩葛朗特五十层间的杂货店保管库里。如果没有这种足以信赖的朋友，那就得有失去全部财产的觉悟了。

因为这个转换机能，我在这个世界里也能拥有与ALO桐人相同的强度——话虽如此，但毕竟是一度初期化的角色，所以没有SAO里初代桐人那样恐怖的数值——但因为外表与道具都不能带出来，所以根本不知道由随机数生成的外表究竟会是什么模样。这么一来当然还是希望能有一副强壮士兵的身体——

我一边觉得不妙一边看着四周围，发现刚才走出来的巨蛋外璧上有镜面玻璃，于是我便朝那里走了过去。

接着我马上惊讶的瞪大了眼睛。

「这……这是怎么回事啊？」

照在玻璃上的身影与自己的希望可说是差了十万八千里。

身高明显比守卫精灵时代还要矮，而且还更瘦小。发色虽然还是黑色，但头发却从头顶一直柔顺地延伸到肩胛骨。脸则是和手一样是通透的白色，再加上一张鲜红的嘴唇。

眼珠的颜色虽然与头发一样，继承了ALO角色的黑色，但却是生得又大又亮。上缘有长长睫毛的眼睛由镜子里投射出纯洁又妖艳的眼神，我不由得忘了镜子里的人是自己而把视线移开了去。但马上又由正面看着镜子并长长地叹了口气。

虽然亚丝娜常说「SAO里的桐人长得很像女孩子」，但现在这副模样早就超出「像」的范畴了。正当我呆呆站在镜子前面，心想这副模样是要怎么做才能像个坚强士兵时，在离我稍远处吃着东西的男人忽然跑了过来，他从背后对着映照在玻璃上的我说道：

「哦哦，小姐你运气不错哦！这个角色是F1300系列的对吧！这类型真～～～的很少见呢。你刚刚才开始游戏吧，要不要整个账号都卖给我啊？我出二M点数！」

「…………」

我用思考停止的状态看着男人的脸一阵子之后，突然想起某种可能性而急忙用双手摸了一下自己的胸部。幸好那里还是像飞机场一样平坦，没有那种让我担心不已的触感。看来并不是恐怖的性别倒错事故。

最近的VR游戏几乎全面禁止玩家与角色改变性别。听说理由是因为常时间使用异性的角色将会对精神•肉体产生无法忽视的不良影响。虽然角色性别是根据玩家的脑波频率所判定，但还是会有极少数因为某种差错而被判定为异性，等到玩家潜行之后才吓了一大跳的事故发生。

现在回想起来，可以设定相反性别的初代SAO在一开始后，马上强制将玩家恢复为本来的性别，可能就是茅场早已预料到会有这种「不良影响」出现了吧……我的脑海里一瞬间想着这种完全不相干的事情，接下来才耸了耸肩，然后看着男人的脸对他说：

「啊……抱歉，我是男的。」

发出来的声音虽然算低沉，但也还是像女孩子的音调。我有气无力的回完话后，等待对方响应，结果对方张大嘴巴沉默了一段时间后，随即用比刚才还要夸张的态度说道：

『那、那……那是M9000系列的啰？太、太厉害了，这样我出四，不，我出五M点数。卖、卖给我吧，拜托你一定要卖给我！」

别说是卖了，要我送都没关系，应该说把你的外表换给我吧，虽然我的心里这么想，但事情还是不可能这顺利。

「那个……这不是初期角色，是从别的游戏转移过来的。所以我不想把它卖掉，抱歉了。」

「这……这样啊……」

男人带着一脸遗憾的表情由各个角度观察我，不久后才像是恢复冷静般这么问我：

「听说在账号上花许多时间才转换的话就比较容易获得这种稀有角色。可不可以告诉我你这个账号的游戏时间，好让我当成参考？」

「咦？游、游戏时间？」

我再次陷入了沉思当中。转换前的账号，也就是剑士桐人由SAO到ALO的总游戏时间，最少也有两年……也就是七百三十天乘以二十四小时……

「嗯……一万……」

差点就老实回答的我急忙把话收了回来。VRMMO类型的游戏才开始三年左右的时光，除了旧SAO玩家之外不可能有人会有超过一万小时的潜行经验。

「没、没有啦，大概一年左右。所以我看应该是偶然而已吧。」

「嗯——这样啊……好吧，如果你改变主意的话就卖给我。」

男人说完之后使交给我透明卡状的道具，按着便依依不舍的离开了。当我看着这写有角色名称、性别、所属公会等数据的卡片不久后，它便主动消失了，不过这些数据应该已经被纪录在系统窗口的联络名册里了吧。

我则是不死心地侧眼看着玻璃里的自己，心想不知道有没有什么办法可以补救，但最后还是做出无计可施的结论。

这次的转换纪录将会留在我的角色档案里，当我回到ALO时便会恢复成那个刺猬头守卫精灵•桐人的模样，而再度来到GGO世界时也还是会变成这个不知道是男是女的角色。

把「在不幸中找出幸运」当成座右铭的我之后又考虑了数分钟，好不容易才挤出一个这种模样的「好处」。

来到这个世界的目的是要跟那个谣传中的玩家「死枪」接触，虽然不想被他枪击但还是得要判别他的能力究竟是真是假。因此我必须尽量展现自己的实力并且吸引人的注意。

GGO这种类型的游戏，女性玩家应该相当稀少才对，这种乍看之下像美少女的模样虽然与我希望的方向不同，但无疑依然是非常显眼。虽然在战场上无法发挥出任何的压迫感，但也只有用战斗能力来弥补这个缺点了。

至于要怎么宣传自己的质力，我倒是已经有了一个主意。

通常利用进行游戏——也就是攻略迷宫还有我不是很愿意做的PK玩家来出名都得花上不少时间，所幸这款游戏几天之后便要举行「Bullet of Bullets」这个决定最强玩家的活动。届时我将报名参赛，然后想尽办法打入大混战形式的正式大赛当中。只要能打进前几名来闯出名号的话，「死枪」他应该会注意到我才对，当然很有可能他自己也参加了这场大赛。

虽然不知道在这个首次潜行的游戏里自己能拼到什么样的地步，但也只有试试看了。虽然与拿枪的对手作战不可能和面对ALO里的弓箭手或魔道士时一样，但只要是VRMMO的话，多少还是会有共通点才对。如果拼尽全力——却还是力有未逮的话，那就是菊冈的责任了，因为原本就是他把这件不可能的任务硬塞给我的。

总之还是先去报名参加大赛和买装备吧。

我最后看了自己的模样一眼，接着用鼻子哼了一声，才开始朝主要街道走去。走着走着才发现自己竟然在无意识当中用指尖撩起脸颊上的长发，整个人马上又陷入了忧郁的气氛当中。

——几分钟后，我立刻迷了路。

SBC格洛肯这座名字奇怪的都市看来是由好几个广大区域堆积而成的多层构造。在不知该往何处去的我眼前，有像缩小版浮游城艾恩葛朗特的楼层耸立着，而遥远上方的开口处可以见到小小的夕阳天空。高楼大厦就像是要贯穿每个楼层般并排着，而连接各大楼的空中回廊、电梯与手扶梯都闪烁着光芒，看起来是一幅相当美丽的景象，但质际上却是像迷宫一样复杂。

当然只要把主选单叫出来就可以看见详细的立体平面图，但要对照标示在上面的现在位置与眼前的景象实在相当困难。

如果这是单机版RPG的话，随便乱走就有可能回不到现在的位置，但所幸这款游戏是MMO。像这种时候还有一个手段可以用。

我从眼前川流不息的行人当中找出一个不是NPC而是玩家的箭头然后跑了过去，按着从背后向对方搭话道：

「那个——抱歉，可不可以让我问一下路……」

我当下立刻觉得情况不妙。

因为转过头来的是个女孩子。

柔顺的淡蓝色短发虽然没有经过任何设计，但绑在额头两侧的一小撮头发却相当显眼。清晰的眉毛下方那像猫科动物般的蓝色大眼睛正闪烁着光辉，更下方则是小巧的鼻子与淡红色的嘴唇。

等等，说不定眼前这个人也跟我一样其实是个长得像少女的男生，想到这里时我便以电光火石的速度往那人身体瞄去，但马上见到土包围巾下，外套拉练敞开露出的衬衫下方确实鼓了越来。而且仔细一看之后可以发现对方相当娇小。刚才之所以没有发现是因为我自己的视线也变低了。

VRMMO里男性玩家对女性玩家说「我迷路了」这种话时，通常有七成左右是要搭讪。

正如我所担心的，转过头来的女性脸上带着相当明显的警戒表情——但出乎意料之外的是，那种表情马上就消失了。

「……你第一次玩这游戏？想去哪里？」

她发出清澈声音的嘴角甚至还带着些许微笑。我正心想这到底是怎么一回事的时候，忽然想通原因在哪里。这个女孩子与刚才想购买我这个角色的男人一样误会我是女生了。这真是太糟糕了。

「啊——那个……」

我反射性地准备说出自己的性别，但又急忙把话收了回来。

这样对我来说或许比较方便。在这之后要再找个男性玩家，然后又被误认为是女性的话那可就有点麻烦了。基于「可以利用的事物就尽量利用」是我的第二座右铭，所以虽然对眼前这名女性不太好意思，但我还是暂时让她误会一下好了。

「对，我是第一次玩这游戏。我想要找便宜的武器店，然后还要去总统府这个地方……」

我用有点低沉又沙哑的声音回答完后，女孩稍微歪着头对我说道：

「总统府？你要去那里做什么？」

「那个……我要去报名即将举行的大混战活动……」

一听见我这么说，少女本来就很大的眼睛就瞪得更大了。

「那……那个，你是今天才开始玩这游戏的对吧？当然不是不能参加这个活动，但你的能力值或许不太够……」

「啊，这不是初期的角色。我是从其他游戏里转过来的……」

「原来如此。」

女孩子蓝色眼珠闪烁了一下，这次嘴角露出了明确的笑容。

「我可以问一下吗？你为什么会想到这个满是灰尘又充满油臭味的游戏来呢？」

「那是因为……我之前一直在玩奇幻系的游戏，所以偶而也想玩些未来类型的游戏……而且对拿枪战斗也有点兴趣。」

当然这些都不是谎言。我对用剑进行近身战斗所锻炼出来的VRMMO直觉究竟能不能在GGO里发挥功效多少也有些兴趣。

「这样啊——不过一开始就要参加BoB，你可真有勇气啊。」

女孩子嘻嘻笑了一下后便用力点着头说：

「好，我带你去吧。我也正好要去总统府。不过在那之前要先到枪械店去。你有喜欢的枪吗？」

「呃、嗯……」

忽然听到这个问题，我一时之间也回答不出来。看见我吞吞吐吐的模样后，女孩再度微微一笑。

「那我们就到有各式枪械的大卖场去吧。往这边走。」

她转过身后便往前走去，我则急忙朝她摇晃的围巾尾巴追了上去。

经过了一连串绝对不可能记住的弯曲小巷、移动步道与阶梯，走了几分钟之后突然来到了一条大马路。而正面就是一间看起来像外国连锁超级市场的明亮店铺。

「就是那里了。」

女孩子不断穿过人群往里迈进。

宽广的店内充满了各种颜色的灯光与喧嚣，简直就像游乐园一样。NPC店员全部是身穿暴露银色制服的美女，虽然她们对每个客人都露出天真浪漫的营业笑容，但让人吃惊的是无论她们手里或者四面墙壁上全部都是发出黑光的粗大手枪与机关枪。

「好……好夸张的店啊……」

听见我说的话后，身边的女孩也露出苦笑。

「其实跟这种适合初玩者的商店比起来，更专门一点的店家里才有比较好的发掘物。不过先在这里找到偏好的枪系统后，再到那种店里去就可以了。」

听她这么一说，我就注意到店里的玩家确实都穿着颜色鲜艳的服装，与女孩的沙漠色服饰比较之下，就给人一种初学者的印象。

「那你的能力值是哪种类型的。」

经她这么一问，我也开始考虑了起来自虽然是异世界之间的转换，不过角色的能力倾向应该也被继承过来了才对。

「那个……应该算是肌力优先，接下来才是敏捷度……吧？」

「STR—AGI型吗。那就选稍微有点重量的突击步枪或是口径较大的机关枪当主武器，然后辅助武器选中距离战斗用的手枪比较好……啊……但是你才刚转换过来对吧？那你现在有多少钱……」

「啊……对、对哦……」

我急忙挥动右手把窗口叫出来。就算能力可以转换，道具与金钱也无法带到这里来。也就是说仓库栏下端所表示的金额只有——

「嗯……只有一千点。」

「那根本就是初期金额嘛……」

我和女孩子面面相觑，彼此都露出了苦笑。

「嗯……」

马上恢复原本表情的女孩子把右手靠在嘴唇上，然后歪着头说：

「这点钱的话八成只能买把小型雷射枪吧……实弹系的话可能只有中古的左轮手枪……怎么办呢……那个——如果不嫌弃的话……」

我察觉她接下去要说什么，于是急忙摇了摇头。无论是在什么MMO里，菜鸟玩家接受老鸟玩家过剩的援助都不是一件值得鼓励的事情。虽然我不是来这个世界玩的，但这也是我身为游戏玩家不可退让的原则。

「不、不用了，不能这样麻烦你。那个……有没有什么可以迅速赚钱的地方。我听说这游戏里是有赌场的……」

结果女孩子终于露出有些无奈的笑容。

「那是在有多余的钱时，以绝对会输掉做前提去玩比较好唷。当然这里面到处都有或大或小的赌博场所。我记得这家店也有……」

她转过头指向店里深处。

「类似赌博的游戏唷。你看。」

她纤细指尖所指的前方，可以见到装饰着闪亮电灯的巨大装置。

接近一看之下，发现那是占据了墙壁一角，以游戏机来说实在太过于巨大的物体。

它的宽度大概有三公尺，长度大概有二十公尺左右吧。铺着金属板的地面被高及腰部的栅栏围住，最深处则有一个西部枪手模样的NPC站在那种。眼前的空间没有栅栏，但有一根金属棒与类似柜台的四角形柱子。

时常会从腰间拔出巨大手枪，然后用指尖一边转着手枪一边讲出挑拨性台词的枪手后面则是充满无数弹痕的砖墙，其上方还有霓虹灯写着「Untouchable！」字样。

「……这是？」

当我这么一问，女孩子便一边动着手指一边解释道：

「从眼前的闸门进去后，看你能躲过里面NPC的枪击前进到哪个位置的游戏。目前为止的最高纪录就是那里。」

伸出去的食指指尖指着栅栏内侧地面上一条发出红光的细线。那是超过全长三分之二距离的地方。

「这样啊。那一次要多少钱……？」

「嗯，我记得玩一次要五百点，突破十公尺可拿到一千，十五公尺则是两千点的赏金。如果可以碰到那个枪手的话，玩家至今为止贡献的所有金钱就全归那个人了。」

「全、全部？」

「你看、广告牌的地方有写现在的总金额唷。个、十……大概三十万多一点吧。」

「好……好高的金额！」

「因为根本不可能成功的啊。」

女孩子立刻这么回答，然后耸了耸肩后又接下去说道：

「当你超过八公尺线时那个枪手射击速度就会像魔鬼那么快。明明是左轮手枪，还能用超高速装填速度来进行三发连射。等看见预测线时根本已经来不及了。」

「预测线……」

这时女孩拉了拉我的袖子，小声地说道：

「看，又有不自量力的人出现了。」

将视线由枪手身上移回入口处时，发现有三名男子正往那里靠近。

其中一人穿着白底浅灰，应该是寒冷地带式样军用外套的男人一边提振自己精神一边站在闸门前面。他用右手掌在柜台上端的面板部分按了一下，可能这样就算付费了吧，按着马上出现观众的阵天欢呼声。店里各处马上有听见声音的十多名观众聚集了过来。

NPC枪手用英文说出「看我把你的屁股轰飞到月球上」的低俗发言，按着便将右手放在枪套上。寒冷迷彩男的前面出现了由绿色全息图表示的巨大数字「3」。数字随着效果音逐渐减少为2、1。当成为0的同时成为闸门的金属棒也就打了开来。

「呜哦哦哦哦啊啊啊！」

寒冷男大叫几声后便往前冲去——但马上又张开双脚紧急煞车。只见他睁大双眼，忽然呈现上半身向右倾斜，左手、左脚抬起来的奇妙姿势。

当我还以为这是什么舞蹈的瞬间，寒冷男的头部左侧十公分处、左脸下方以及左膝下方都有闪烁红色光芒的子弹经过。虽然寒冷男很漂亮地躲开了由NPC枪手的手枪后所发射出来的三发子弹——但看起来简直就像他能预知子弹要从哪里经过一样。

「……刚才那就是弹道……？」

我皱着脸小声问完后，淡蓝色头发的女孩便轻轻点了点头，按着同样小声回答道：

「对，那是藉由『弹道预测线』所做的攻击回避。」

寒冷男等火线消失后便再度往前猛冲，但马上又停了下来。他这次换成大大张开双脚，上半身弯曲九十度的姿势。

接着两发子弹便伴随着尖锐的声响一发经过男人头上，另一发穿过他的跨下。男人再次往前然后又停止。这简直就像在玩「一二三木头人」一样。

寒冷男展现敏捷的动作，马上就前进了七公尺左右。现在还差三公尺左右奖金就可以加倍了——但就在这个时候……

至今为止以相同间隔时间发射三发子弹的NPC枪手，忽然开始改变间隔时间先发射两发子弹，接着又射出一发。寒冷男虽然跳起躲过较晚过来的那一发子弹，但着地时却失去平衡而单手撑着地面。急忙准备站起来的他却已经为时已晚。枪手右手一闪，发射出来的火线便在男人白色背心上引发了橘色火花。

这时响起观众喝倒彩的声音。枪手则开始叫着低俗的胜利宣言，接着背后的总金额随着轻快的金属声往上升了五百点。寒冷男垂头丧气的来到闸门外。

「……看吧？」

身边的女孩子在围巾底下微微一笑然后再度耸了耸肩。

「如果能够左右大幅度移动那就还好，但几乎只能直线往前冲，所以大概到那边就是极限了。」

「嗯……原来如此。看见预测线时就已经太迟了吗……」

我低声说完后便跨步往闸门走去。

「啊……等等，你怎么……」

我扬起一边嘴角对瞪大眼睛叫住我的女孩笑了笑，按着便将用手放在柜台上。听见旧式收款机那种「喀锵」的声音后，马上就传来热闹的欢呼声。

不知道是因为又有新的笨蛋出现，还是因为我长得一副柔弱的模样，旁边观众与包含寒冷男在内的三人组开始骚动了起来。戴围巾的女孩则双手扠腰，表示无奈般的轻轻摇了摇头。

枪手在发出与刚才不同叫骂声的同时，我眼前也开始了倒数计时。

我沉下身子，摆也准备全力冲刺的姿势。数字归零，金属条打开的瞬间我便朝地上一踢冲了出去。

前进几步之后，枪手的右手立刻举了起来，而它手里那把手枪的尖端开始延伸出三条红线。线条各自喵准了我的头、右胸与左脚。

—一有这种感觉，我便不加思索地向右前方跳了过去。按着橘色火线立刻擦过我的身体左侧。我用右脚往金属地板一踢，整个人又回到中央。

这是我第一次在VRMMO游戏里面对枪械。

但是在ALO以及SAO里都有许多能进行弓箭、毒液、魔法等远距离攻击的怪物。而要躲过这些飞行道具只有唯一一种方法。那就是从敌人的「眼睛」判断出射线。而这应该是开发者茅场晶彦的坚持吧，在Cardinal系统上运作的VRMMO怪物全部都有将视线移往瞄准部位的特性。当然——这是仅限于该怪物有类似眼睛这种器官的时候。

眼前这名拿枪对准我的枪手应该也得遵照这个原则才对。

我完全不看向红色弹道预测线与黑色枪口，只是一直凝视着枪手的眼睛，试着从那随处移动的无机质眼睛里感觉子弹飞过来的轨道。我在感觉轨道的同时也以最小动作往左右或者是上下移动来不断躲过静静出现的预测线。当子弹实际经过时，我早已经进入继续往前冲刺的姿势了。

躲过两次三连发射击后的我已经超过十公尺线，这时似乎有的短暂的效果音响起。但我根本没有意识到这道声音。

枪手发射完六发子弹后把空的回转式弹仓退出来，当空弹匣往后方飞去的同时它也用左手一口气装进六发子弹，「喀嚓」的清脆声响后弹仓又被装回枪身里面，而这整个过程不过花了0.5秒的时间——这确实可以说是作弊般的快速——接着枪口马上再度对准了我。

接下来的攻击与之前那种间隔分明的三连射完全不同。子弹开始以不规则频率朝我袭来，先是两发接着才又有一发与三发子弹飞来。我有一半以上依靠直觉来躲过这些手弹，然后又往前推进了五公尺。耳边再度有欢呼声响起。同时枪手又电光火石的完成了半秒装填子弹。

距离还剩下五公尺，敌人已经近在眼前。或许只是错觉吧，总觉得可以很清楚看见NPC枪手那满是胡须的脸因为憎恨而扭曲了起来。

西部牛仔帽下面的黑色眼睛不断微微转动，往我胸部的高度看了过来。我做出无法左右回避的判断后，立刻将身体倒下然后在金属地板上滑行。穿过根本与机关枪没有两样的六条火线之后，我又缩短了两公尺半的距离。

这下子敌人又没子弹了。只要有装填子弹那0.5秒的时间，我就能够碰到它了。

一边起身一边这么想的我，马上感觉到枪手的眼睛露出了笑意。

我反射性改变往前冲的打算，整个人用力向上跳了起来。

左轮手枪没装填子弹就直接发射六发雷射贯穿我刚才站的地方。

这也太夸张了吧！我在嘴里这么叫着，然后空中一个转身后在枪手眼前着地。

虽然很想在这时候讲出一句耍帅台词来，但在敌人使出最后一招——比如说从眼睛里发出死光等等——之前，还是得先下手为强才行，所以我迅速往穿着皮背心的敌人胸口敲了下去。

就像店里的声音完全消失般的一阵寂静之后。

「OH MY GOD————————！」

枪手随着震天尖叫抱住了头，接着整个人跪到地上。同一时间扬起了一阵疯狂的观众欢呼声。

这时欢呼声中开始混杂着喀啦喀啦的声音，我抬头看是怎么回事之后，发现枪手身后的砖墙像由内侧爆发般整个崩毁。当我还来不及惊讶时，内部便有金币像下雨般不断流出来。它们一边发出清脆声音一边在在我脚边反弹起来，最后便消失无踪。

霓虹灯广告牌下面标示总金额的数字数字迅速减少，当它变成零时金色瀑布也停了下来。当更吵杂的声音在店内响起时，游戏已经重新设定，枪手也站起身来用手指转着手枪。虽然嘴里还是嚷着挑拨意味的低俗言语，但在刚才露了一手夸张的十二连射之后，我很怀疑还会不会有人想要挑战。

「呼……」

我喘了口气之后从左侧栅栏打开的出口离开游戏步道。

不知何时增加了一倍的观众群里立刻发出了震耳欲聋的欢呼声。到处可以听见「刚才那是怎么回事」「那女孩是谁」的声音。

由人群角落小跑步过来的蓝发少女瞪大像猫一般的眼神凝视着我。几秒钟后从她嘴唇里流出沙哑的声音。

「……你的反射神经也太恐怖了吧……？最后竟然还能躲过眼前……大概两公尺左右射过来的雷射……那种距离之下弹道预测线与实际射击已经几乎没有时间差了才对……」

「嗯，那个嘛……因为……」

我因为不知道该怎么回答而考虑了好一阵子，最后才说：

「因为这个闪避子弹的游戏不就是要预测弹道预测线吗？」

「预……预测弹道预测线？」

女孩可爱的叫声贯穿店内的空气。而其他围观的群众也都张大了嘴说不出任何话来。

几分钟之后，在人群好不容易散开的武器店一角，我看着展示柜里各式各样的步枪然后歪着头说：

「嗯～这把突击步枪明明口径比冲锋枪小，但为什么体积会比较大呢？」

当我对站在旁边的那名亲切女孩提出这相当简单的问题时，她似乎仍未从惊讶的心情中恢复过来，只见她像只怕生的猫一般以充满警戒心与好奇心的眼睛看着我。

「……连这种事情都不知道，但却有那种惊人的回避技巧……你说你是转移过来的对吧。之前是在什么样的游戏里？」

「嗯……就是很普通的奇幻系游戏啊……」

「是吗……嗯——算了。既然你要参加BoB初赛的话，就有机会能见到你实际作战的情形。你刚才说什么？突击步枪口径比较小的理由。那是由美国的M16步枪所开始的，籍由小口径高速弹提升命中准确度与贯穿力的设计思想……」

讲到这里时少女忽然闭上嘴巴，接着好像为自己的发言感到无奈般绷起一张脸。但这种奇怪的反应一瞬间就消失，她脸上马上又出现了些许微笑。

「……这种事应该不重要吧。来，快点把你的东西买一买。」

「好……那就麻烦你了。」

她将视线从感到讶异的我身上移开后，便从大展示柜前缓缓往前走去。

「有300K（三十万）点数的话应该就可以买很不错的武器了……不过最后还是要看个人的喜好与要求就是了。」

「要求吗……」

我跟在少女后面，不断看着各种闪烁黑色光芒的枪械，但都没有特别喜欢的感觉。其实这也不能怪我，因为我对枪械的知识全部就只有「手枪可分为左轮手枪与自动手枪」而已。

当我还在沉吟之际，不知不觉间就来到了店里密集的陈列架最尾端。这样的话干脆就拜托她帮我选吧——正当我这么想峙，眼睛正好看见了一样很奇特的物体。

长形展示柜的角落里排着几根很明显不是枪械的金属筒状物体。

它的直径是三公分，长度应该有二十五公分左右吧。一侧垂着像登山用扣环般的金属部分，另一侧则显得比较粗，中央还有像某种发射口般的黑色洞穴。既然陈列在这家店里，那应该也是枪械的一种吧。但却看不出有握把与扳机这些部位。只能发现筒子侧面上方有一道小小的开关。

「请问这是……？」

问完之后女孩子的眼神便往这里瞄了一下，然后再度轻经耸了耸肩膀。我想这应该是她的习常性动作吧。

「啊啊……那是光剑啦。」

「框、框剑？」

「是发光的光。正式名称应该是『光子剑』，但大家都随口叫它雷射光剑、光剑或者是光束军刀等等。」

『是、是剑吗？这世界里也有剑啊！」

我急忙把脸贴近展示柜。一听她这么说后，我便发现这的确很像古老科幻电影里，维护宇宙秩序的武士们手里所拿的武器。

「有是有啦，但实际上没有人在使用。」

「为……为什么？」

「那当然是因为得在超近距离才能击中对方，等到你接近之前早就被人家打成蜂窝了……」

女孩子讲到这里后便停了下来，稍微张开嘴唇直盯着我看。

原本差点大笑出来的我赶忙转换成微笑，接着开口说道：

「也就是说只要能接近就可以了吧。」

「虽、虽然你的回避技术是很厉害没错，但在遇上全自动的枪械时……啊……」

女孩仍未说完之前，我便从展示柜里的光剑里找到一把自己喜欢的暗黑色光剑，然后用指尖朝它点了一下。在弹出式窗口里选择「BUY」选项后，NPC店员马上以惊人速度飞奔过来，满脸笑容地把金属面板状的东西交给我。注意到面板中央有与刚才游戏柜台上相同的绿色扫描仪之后，我便把右掌压了上去。

轻快的结账效果音响起，呼一声就有一把黑色光剑实体化出现在面板上。我拿起来之后，店员便笑着说「谢谢惠顾～」并且行了个礼，然后用与刚才同样的速度回到位置上。

「……啊……买下去了。」

女孩以右斜上四十五度角的视线看着我并这么说道。

「当然每个人喜欢的战斗方式都不同啦。」

「没错。就算是剑，既然有在卖的话就表示一定可以派得上用场。」

我一边回答，一边用右手握紧短短的筒状武器，然后将它拿到我身体前方。用大拇指按下开关之后，蓝紫色能源光刃便随着「嗡」一聋的低震动音冒了出来。伸出去足有一公尺长的刀刃立即照亮了四周围。

「哦哦……」

我不由简短的叫了一声。虽说自己到日前为止已经握过大大小小不同的剑，但这还是第一次拿到剑身是由无实体光芒所构成的剑。

我凝视着它一阵子后，发现刀锋没有方向性，整个圆切面就像细长筒状一样。我试着摆比中段姿势，接着使出即使没有系统辅助也已经相当熟练的SAO时代单手剑技「水平方阵斩」。

光剑一边在手也发出悦耳的「嗡嗡」声，一边在空中划出复杂轨迹，最后倏然停止。当然我的手上没有感觉到任何因为剑的重量所产生的惯性抵抗。

「哇——」

女孩在我身边拍了几下手后，脸上出现了吃惊的表情。

「还颇像一回事的嘛。奇幻世界里的剑技吗……看来可不能小看你啰？」

「没、没有啦……不过这可真是轻啊。」

「那是当然啰。这武器除了轻之外就没有别的优点了。好吧——如果你主要武器要选那个的话，至少辅助武器也要有把SMG手枪比较好。也要有牵制性武器才能接近敌人嘛。」

「原来如此……这倒是真的。」

「你还剩多少钱。」

把窗口叫出来后发现原本有三十万点的我，现在已经剩下十五万点左右了。我将数字说出来后，女孩便眨了眨眼然后轻轻耸了耸肩。

「呜哇，光剑怎么会那么贵啊。还剩下一百五十K吗……还要加上防具与子弹的钱，也只能买手枪了。」

「其他的就全部拜托你了。」

「要参加BoB的话还是实弹系比较好……拿来牵制用的话，准确度应该比威力来得重要吧……嗯……」

女孩子一边干咳，一边在排着一堆手枪的柜子前慢慢走着，最后她指着其中一把说：

「虽然这样就快没钱了，但这把『FN.5-7』应该不错。」

纤细指头的前方是一只拥有平滑圆润握把且略为小型的自动手枪。

「5……7？」

「那是指口径。因为是5.7毫米，与普通的九毫米鲁格弹相比确质是小了一点，但形状与狙击弹相似所以命中率与贯穿力算是相当优良。因为是特殊子弹，所以只能和FN制的冲锋枪『P90』共享，不过你只有这把枪而已应该没关系吧……」

「这、这样啊……」

听见她这种毫无阻碍的解说之后。我又再度对这名淡蓝色头发的少女有了些微兴趣。

因为GGO是性别固定的游戏，所以现实世界里的她一定也是女性，但还是无法得知她的人种与年龄。只是依据我的感觉，她的岁数应该跟我差不多才对。

既然玩这款MM，熟悉游戏内道具其实是理所当然的事。像亚丝娜和莉法在提到ALO内的剑与魔法时，不讲个五十分钟是不会结束的。

但是——总觉得「枪」和那些东西完全不同。而且听说GGO里登场的枪械有大半是真正存在于现实世界里的武器。而这种武器很容易让人联想到血腥与杀戮。这名与我同年纪的女孩子潜入这样子的世界，然后还持续作战到变成了解所有枪械知识的老鸟玩家，我倒是对她的动机以及原动力感到相当有兴趣呢……

「喂，你有在听吗？」

「啊，有、有啊。」

我急忙中断思绪点了点头。

「那我就买这把。其他还有什么应该要买的东西吗。」

买下她推荐的「5-7」左轮，不对应该说是手枪之外，还按照她的指示买了预备弹匣、厚重的防弹夹克、皮带型的「对光学枪防护罩产生器」等小型装备，当购物完成时刚才玩避弹游戏赚来的三十万已经化为泡影。

我一边感觉右腰上光剑、左腰上5-7的新重量一边走出商店，来到外面之后才发现黄昏色天空开始略微泛红了。

「抱歉耽误了你那么多时间。真是太感谢你了。」

我低头致谢之后，女孩子在围巾底下微微一笑，接着又摇着头说道：

「不会，我在预赛开始之前也没什么事。啊……」

女孩说到一半便停了下来，然后急忙往左手上粗大的自动表看去。

「糟糕，三点就截止报名了。呜哇，就算用冲的到总统府可能也来不及……」

「咦，你也是接下来才要去报名吗？」

「嗯。」

被铁青着一张脸的少女所影响，我也朝刚买的数字表看去。上面显示的时间是——十四点五十一分。

我抬起头，慌张地问：

「那、那个……这里没有瞬间移动的手段吗？像是转移道具还是魔法，不然就是超能力什么的……

「一边跑一边跟你说！」

女孩子叫完之后便转过身子，朝着大路的北边冲了出去。我赶紧朝那摇晃的围巾追去。花了几秒钟赶上她之后，她朝我瞄了一眼，然后用紧张的声音说：

「……这个GGO里，发生在玩家身上的瞬间移动现象只有一种。那就是死亡回到复活地点时。格洛肯地区的复活地点是在总统府附近没错，但街道里HP是绝对不会减少的，所以没办法用那种方法……」

我们绕过往来于街道上的NPC与玩家全力往前冲刺，少女也同时不停向我解释着。而我则是得用上全部的心力才能够赶上她。除了不习惯变得比ALO时还低的视点之外，她跑步的速度也确实快到了极点。与其说是有能力的支持，倒不如说她那种熟练的动作，一看就知道是已经完全习惯完全潜行环境下的行动。

少女再度看了一下手表，然后指着前面的街道说：

「……总统府就在那个方向。因为是在市街道的北端，所以还有三公里左右。操纵报名机器大概要五分钟左右，所以不在三分钟内到达的话……！」

我看了一下往前笔直延伸的主街道，发现遥远前方有一座受到夕阳照射而发出红光的巨大高塔。虽然是直线道路，但要躲开行人然后一分钟赶一公里的路程，就算是在不会喘气的VR世界里也可说是难如登天。

我如果来不及报名也是事前没做好调查的报应，但跑在我身边的淡蓝色头发少女如果不是为了帮我的忙，早就可以轻松完成报名作业了。怀着罪恶感的我朝她瞄了一眼，结果看见她咬紧牙根，眼睛里露出拼命神情的侧脸。一道细微的声音挟杂假想的呼吸声传了出来。

「……拜托……拜托……一定要赶上啊……」

——我想对这名少女而言，接下来即将展开的「Bullet of Bullets」预赛应该不只是游戏，而是有着相当重大的意义吧。她一定有什么非得参加这次比赛的理由才对……

直觉理解到这一点之后，我拼命看着周围环境，希望能找出在三分钟里到达远方总统府的方法。

这时有一块广告牌映入我的眼帘。

左边宽广车道上有一块扩大过后的停车空间，那里停着涂有鲜艳红黄蓝三原色的三台小型车辆。而深处的直立面板上则有一闪一闪的霓虹灯显示着「Rent-A-Buggy！」字样。当然我一看就知道是什么意思了。

「……就是那个！」

我紧急抓住少女的左手，开始改变行进方向。惊讶地发出「咦？」一声的少女几乎被我拉得浮了起来，但我们还是越过行人穿越道冲进了「租借小车」的停车场里。

排在里面的车辆全部都是前面一轮，后面两轮的三轮电动车。我将少女往停在眼前的红色三轮车后踏板上一扔后，自己也跨上前面的座位。在时速表下面发现与购物时相同的掌纹扫描装置，将右手放上去后，引擎便随着结账声音发动起来了。

幸好三轮电动车的前半部与摩托车的构造完全相同，而且还是全手动操纵。我一握紧手把，二话不说催动节流阀。内燃机关旋即发出尖锐吼声，三轮车前轮先是整个浮起来，接着便像弹射出去般冲进车道。

「哇呀……！」

听见后座传来可爱的悲鸣，然后两只纤细的手绕过我腹部。

「抓紧啰！」

车子早已冲出去我才这么叫道。经过轮胎几乎要将地面擦出火来的右转弯后一来到车道上，我立刻将油门加到底。经过不断换档之后，时速表立刻超过一百公里。这时心里才深深觉得，现实世界里自己不是乘坐电动速克达而是需要打档的古档机车真是太好了。

当我一边闪过车道上左来右往的未来型四轮车，一边忙碌地换档时，听见女孩在我右边耳朵这么叫道：

「为……为什么？这种三轮车其实非常难操纵，连男性玩家都没什么人可以驾驶得好了……！」

——抱歉，其实我就是那个例外的男性玩家。

但这种情况下当然没办法说出实情，我只好含糊带过说：

「没…没有啦，我以前玩过赛车系的游戏……唉唷！」

前面的大型巴士忽然变换车道，我只好用后轮胎全力滑行来躲开。稍微降档之后再度加速，然后一口气超越它。确实，在这个2025年即将结束的时代，几乎没有什么人骑过手动打档的旧型机车也是很理所当然的。说起来驾训班吉本上都是电动速克达了。我是因为艾基尔的熟人愿意免费送给我，才会费尽心思去取得手排的中型摩托车驾照。但实际上在收下那台泰国制摩托车后过了好一阵子，才注意到这是帮前车主省下了一笔报废车的资金。因为听说几年之后即将要全面禁止使用汽油引擎的车辆了……

——当我想到这里时背后忽然传来笑声，我也因此而吓了一大跳。

「啊哈哈……真棒，好舒服哦！」

我花了好一段时间才认出这道声音是来自于那个猫眼少女。没想到这个有些紧绷又有些寂寞气息的女孩，竟然会发出这种笑声。

「嘿……再快一点！」

听见少女的叫声之后，我朝一公里外逐渐靠近的雄伟总统府高塔瞪了一眼，然后回答了一声「OK！」我低下头，将脚排档杆打到最高档。引擎发出「嘎啊啊啊」的吼叫，时速表上的指针立刻逼近两百公里。

这种速度的话，只要几十秒就能跑完一公里的距离。

但是少女在这短暂时间里所发出来的欢呼声，却让我留下非常深刻的印象。

我将三轮电动车横向打滑停在通往总统府的宽广阶梯前。

看了一下手表后，发现还有五分钟左右才到三点。

「这样应该来得及！往这边！」

由脚踏板上跳下来的少女握住我的左手开始跑了起来。那种像利刃——不对，应该说像高性能枪械般的锐利表情已经回到她侧脸上。我强迫自己不继续去想到底哪一种才是她真实的个性，跟着拼命爬着楼梯。

爬了二十阶左右后，一座异常巨大的金属塔便吃立在我眼前。它前后有细长的流线型广场，本身则随处可见像天线或是雷达盘的圆盘凸出来。

「这就是总统府，通称『Bridge』。你从里面出来的游戏开始地点是『纪念馆』，它就位于总统府的相反方向。」

女孩一边拉着我的手一边这么说道。

「Bridge？是桥吗……？」

我如此提出问题后，少女稍微歪着头这么回答：

「不是桥，应该是『舰桥』的意思吧？格洛肯是宇宙飞船时期的司令部，所以才会有这个名字。」

「宇宙飞船……啊啊，所以城市才会是长型的吗。」

「嗯。正式名称的『SBC』是『Space battle cruiser（字宙战斗巡洋舰）』的简称。像是参加活动的报名或是游戏相关手续都是在这里进行。」

当解释到这里时，我们刚好穿过高塔，也就是舰桥的一楼入口。

内部是一座相当宽广的圆形大厅。

排成十字状一直向上延伸至屋顶的圆柱看起来相当有未来感。周围墙壁上环绕着一圈大画面的平面屏幕，里面播放的各种活动预告以及现实世界的企业广告，在微暗大厅里投下原色系光芒。其中最鲜艳的当然就是正面大屏幕上播放的「第三届Bullet of Bullets」宣传影像。

但我现在根本没有仔细观赏的时间。少女拉着我往右边深处的一角前进。

墙壁边排着几十台细长的机器。它们的长相就跟放在便利商店里的ATM或是多媒体机台一样。

少女带我到一台机器前面之后，使快速地说：

「就是在这台机器上报名。它就跟一般的触碰式面板机器一样，你知道怎么操作吗？」

「嗯，我试试看。」

「嗯。那我在旁边报名，有不了解的地方就问我吧。」

少女说完便朝被板子隔开的隔壁机器台前进，我小声向她道谢之后便往画面看去。

屏幕上的主要画面显示着「SBC格洛肯总统府」的字样，惊人的是包含选单在内全部都已经日文化了。潜行之前在现实世界的网络上观看GGO的公式网站时，发现全都是英文而令我相当头痛，但游戏内部似乎已经经过一定程度的本地化。

我用指尖拖动了一下选单，立刻找到报名第三届Bullet of Bullets的按键。我当然马上按了下去。结果画面便转移成输入名字、职业等各种档案的报名表格。这时时间还剩下一百八十秒。

既然是在游戏里面，角色名称至少也自动帮忙填进去嘛，还有我的职业是什么啊……我内心一边不停抱怨一边看着表格，但立刻就发现最上方有一条惊人的但书。

它写着「以下的表格请填上玩家在现实世界里的姓名与地址等数据。当然空白或是填入假数据也可以参加本活动，但将无法领取入选前几名时的奖品」。

这让我的指头瞬间停了下来。虽然我的主要目的是要在大会里尽量突显自己，好成为「死枪」狙击的目标。但奖品这两个字还是让我的MMO玩家魂产生了犹豫。因为这种时候的奖品通常都是游戏里无法入手的超稀有装备……

当我的手指被姓名栏吸引过去，准备在出现的全息图键盘上打下「桐谷」的K时，好不容易才又说服自己不要这么做。

我这次可不是来这里玩的。和谜之玩家「死枪」接触并判断他的能力是真是假才是我的首要任务。如果「死枪」真的有什么力量的话，那在游戏里暴露自己的真实情报就不是什么明智之举。我不能否定「死枪」是营运公司的人，而且可以自由观看全玩家登录数据的可能性。

好不容易摆脱稀有奖品的诱惑，内心淌血的我将所有字段留白，然后按下最下方的SUBMIT按键。

画面再度切换，显示出我已经报名成功的文章与第一回合预赛的对战时间。想不到日期就在今天——而且是在三十分钟之后。

「结束了吗？」

水蓝色头发的女孩忽然从旁边这么问道。看来她也顺利完成报名了。于是我便放下心来点了点头。

「嗯嗯，总算是完成了。真的非常感谢你……还有……抱歉给你添了这么多麻烦。」

听见我道歉之后，女孩微微笑了起来。

「没关系啦，刚才的电动车之旅我还满高兴的。话说回来，你预赛是哪一组的？」

「嗯……」

我再度往画面看去然后回答。

「我是F组。F的三十七号。」

「啊……这样啊。因为我们是同时申请，所以我也是F组。而我是十二号……太好了，就算碰见也是在决赛的时候。」

「为什么说太好了？」

「只要能打进预赛的最后决赛，不论输赢都能够参加正式的大混战。所以有可能就是由我们两个获得参加大混战的权利。不过，如果真在预赛的决胜战里遇见你的话……」

她那像猫的眼珠发出亮光，接着开口说：

「我可不会手下留情唷。」

「啊啊……原来如此。如果真的碰上了，我当然也会全力以赴。」

我笑着回答完之后，将屏幕退回主画面。接着我又顺便提出一个问题。

「话说回来，虽然是外国的游戏，但这机器倒是全部日文化了啊？。明明公式网站还都是英文……」

『嗯嗯……营运公司『ZASKAR』虽然是美国企业，但日本服务器的工作人员里似乎也有日本人在。不过……你应该也知道，GGO无论是在日本还是美国都属于法律的灰色地带。」

「那是『货币转换系统』害的吧。」

听见我的回答之后，少女也露出些微苦笑并点了点头。

「对。在某种意义上来说，这也算是私营的赌场。所以公开的网页里只有最基本的情报，而且完全不刊载营运公司的所在地。此外像是角色管理、货币转换用的电子货币账号输入等关于游戏的手续都只能在游戏里进行。」

「我只能说……这游戏实在是太猛了。」

「所以这里与真实世界几乎可以说是完全分离……但是也因为这样，感觉现在的自己和现实里的自己好像是完全不同的两个人……」

感觉女孩的眼里似乎闪过一抹黑影，我眨了一下眼睛感到疑问。

「……？」

「没、没什么事啦，抱歉。我们该到预赛的会场去了——其实也只是在这里的地下而已。你准备好了吗？」

「嗯嗯。」

我点了点头，少女则再度牵着我的手说「往这边」，然后朝总统府一楼大厅的正面深处走去。那里的墙壁边排了好几台电梯，女孩纤细的手指按下最右边电梯门旁的下楼按键。

门马上就打开。少女顺势往里头一站，接着按下「B20F」的按钮。看来这座塔的上方与下方都有很长的空间。身体感觉到真实的落下感与减速感后，门便打了开来。

一见到门外的黑暗——我不由得屏住呼吸。

那是一座与一楼大厅同样宽敞的半球形巨蛋。里面光源相当稀少，只有几具被铁框罩住的弧光灯发出单薄的亮光而已。

地板或是柱子不是发出黑光的铜板就是赤茶色的铁网。巨蛋的墙壁边还排着一些粗糙的桌子。而屋顶部分则有多面巨大的全息图面板。但是目前画面呈现一片漆黑，只有用深红字体显示着「BoB3 preliminary」的字样与剩下二十八分钟左右的倒数计时。

然而让我感到紧张的不是这样的景色与低声流出来的金属系BGM。

正确来说应该是紧集在墙边桌子或是直立铁柱旁的那些黑影——所散发出来的气息让我感到不舒服。

明明是在游戏里面，但却没有任何大吵大闹的人。他们不是几个人众在一起窃窃私语，就是独自一人默默站在那里。一看就知道他们是即将开始的BoB预赛参赛者，而且也知道他们已经完全熟悉这个假想世界，算是彻头彻尾的VRMMO玩家。

——不对，如果要比总潜行时间的话，这个空间里应该没有人比得上我才对。因为前年和去年的两年里，我没有任何一刻是处于注销状态。

但是每个玩家都有所谓的「玩法风格」。像我就是专门PvE（与怪物对战）的玩家——而他们则与我相反，是一群热中于PvP（与玩家对战）的家伙。由他们没有光泽的头盔或是厚重头套下投射过来的锐利视线，就可以知道这群人正拼命想找出关于我的情报。

我自从今年春天ALO转移到现在的营运公司之后，就几乎没和人对战过了。这段不算短的空白时间，将会让我的PvP感大打折扣吧。我被这群男人们投射过来的眼神给压倒正是最佳的证明。

——这件工作越来越困难了啊，菊冈先生。

不由得在心里这么嘀咕着的我，右手肘忽然被轻轻推了一下。往旁边一看后，发现淡蓝色头发的少女正露出讶异的神情。

「……怎么了吗？」

「没、没有啦……」

急忙低声回完话之后，少女便轻轻点了点头，同样也小声地说：

「我们先到休息室去吧。你也得换上刚才的战斗服才行。」

于是她开始穿梭在玩家之间，脚步显得相当自然，感觉不出有任何的紧张。但这不是因为周围的众人忽略了她的存在。这群男人投射在她身上的浓烈战意跟看着我时简直无法相比。有个将巨大枪械放在膝盖上的家伙甚至还故意高声排出弹匣。

想不到这名少女竟然有这么大的胆识可以完全无视这种庞大的压力。我一边感到越来越惊讶，一边朝土黄色围巾追了上去。

巨蛋的深处见不到桌子，反而是几道冰冷的铁门并排在那里。少女打开亮着绿色指示灯的门，带我进到里面后便将背后的门关上并按起门内侧的操作面板。指示灯随着「喀嚓」的上锁声变成了红色。

门内部是略为狭窄的更衣室。当然除了我们之外就没有别人在了。

「呼……」

来到房间中央之后，少女轻轻吐了口气，接着呢喃般说道：

「真是……一群天真的家伙……」

「什……天、天真的家伙？你是说刚才那群杀气腾腾的人吗？」

我一边回想巨蛋里那群绷着一张脸的男人们一边这么问道，而少女却像理所当然般地点了点头说：

「对啊。比赛开始前三十分钟就拿主要武器出来炫耀，这根本就像请人家想办法来对付自己一样嘛。

『啊……啊啊……原来如此……」

「你最好在开始比赛之前才装备上光剑与5-7唷。」

一边微笑一边这么说的少女见到我轻轻点头后便转过身去。

接下来她就做出比刚才的台词更让我吓破胆的事情。

她挥动右手叫出主选单，随即按下一并解除所有装备的按键。

土黄色围巾、深卡其色的夹克、宽松的工作裤、没有任何图案的T恤依序消失了。

现在少女身上只穿着露出机能纤维光泽的小面积内衣。

「呜……呜哇啊？」

我发出沙哑的声音，急忙用右手遮住脸。接着从指缝当中看见少女一脸不可思议的看着我。

「你还在做什么？赶快换衣服啊。」

「好、好的，嗯……那个……」

即使面临潜入GGO以来最大等级的动摇，但我还是拼命想着对策。

在这种状况之下我能做出的选择已经不多了。要不就是找个借口逃出这个房间。再不然就是一路装成女生直接在衣服上装备护甲。不过这两种方法都算是欺骗了这名帮了我大忙的女孩子。

在不得已的情况下，我只好在这名少女继续做出武装解除的终极悲剧发生之前，咬牙进行了第三种选择。

我以最快速度低下头，同时从主选单里让名片实体化，然后用双手递给少女。

「那、那个……对不起！到现在都没自我介绍……这、这是我的名字！」

「咦？名……名字？」

名片随着感到不可思议的声音离开我的手中。

「桐……人。嗯……很有趣的名字嘛……………………咦……………………」

我在这世界没有加入公会，不对，在这里是叫做「中队」，所以名片上除了姓名之外——就只有标记性别而已。

「上面写着Male……咦……？你不是…………」

呆滞的声音传来的同时，低着头的我可以见到视线上端的小巧裸足往后退了一步。

「骗人…………这、这种模样…………竟然会是男的………………？」

接着则是一阵沉默。

我因为受不了笼罩在更衣室里的紧张气氛而准备抬起头。

这时立刻有个白色物体以猛烈速度飞了过来，在我的左脸颊上炸裂之后迸发出紫色效果光线。

当我因为冲击而像个陀螺般不断旋转，最后眼冒金星倒在地板上之后，才了解原来那是少女的手掌。

「别跟着我。」

「但、但是我不知道接下来该怎么办……」

「别跟着我。」

「但、但是我没有其他认识的人了……」

「别跟着我。」

在低声的对话当中，我依然拼命追着前面的水蓝色头发少女。

她的穿著已经变更为沙漠色军用外套与同包系防弹装甲以及军靴。与街上装备共通的只有脖子上那条围巾而已。与刚才给我的忠告一样，她还没有把武器实体化。

我的打扮也跟她差不多，但我全身都是称为夜间伪装的近黑色迷彩服。这次虽然想舍弃自己的喜好，选择用途较广的颜色。但因为战斗的地点是由随机数决定，而女孩表示以我的预算根本无法凑齐对应各种地形的迷彩服，所以我最后还是选择自己喜欢的颜色。

而给我建议的那个人，目前正在离我一公尺远的地方头也不回地往前走去。

我当然能理解她为什么生气，但我也没有谎称「我是女生」或是以女性的口气说话。利用了她的误会确实是我不对，但要换衣服时先跟我说一声的话，我也会有应对的方法啊……

我不禁开始一边在心里这么抱怨着，一边有些故意地紧紧跟在她身后，但少女却忽然停下脚步。这时广大的巨蛋已经被我们绕了半圈。

少女转过头来看着同样停下脚步的我。

她蓝色的眼珠狠狠瞪着我看。冰冷的眼神这时与其说像猫，倒不如说已经达到豹子的程度了。见到她小巧的嘴唇用力吸气时，我还以为会被大吼而缩起了脖子，但她却只是迅速地叹了口气。

她往旁边的包厢席上用力一坐，接着又将脸转往别的方向。我则是畏畏缩缩的坐到她对面。

抬头往中央的全息图面板看去后，发现距离预赛开始已经剩下不到十分钟的时间。而我完全不知道接下来该怎么办。预赛开始之前是不是还要移动到什么地方，还是需要进行什么样的手续，我甚至不知道该去哪里找到这些情报。

我只能缩着头焦躁不安的动着身体，而少女这时又瞄了我一眼。接着再度深深叹了口气。

「…………我跟你说明最基本的情报。但之后就真的算是敌人了。」

听见她用低沉的声音这么说完后，我不由得露出了笑容。

「谢、谢谢你。」

「可别搞错了，我没有原谅你哦。上面的倒数结束时——这楼的所有参赛者将会自动被转移到只有自己与对手两个人的预赛第一回合战场上去。」

「唔，原来如此。」

「战场是一块长宽各一公里的正方形空间，地形、气候、时间则是由随机数决定。一开始时两个人之间至少会有五百公尺的距离，而在战斗里获胜的一方将被转送到待机区域，落败的一方则被转送到一楼大厅。就算落败也不会随机掉武装。获胜之后如果下一个对战者的比赛已经结束，马上就会开始进行第二回合战斗。如果对方还在战斗的话，那就待机到对方结束为止。

F组共有六十四个人，所以只要嬴五场就能进入决赛并获得参加正式大赛的权利。我的说明就到此为止——也不会再回答任何问题。」

虽然讲话口气相当冰冷，但在她详尽的解释之下。我已经大概了解预赛到底是怎么回事了。我再度向少女道谢。

「我大致了解了。谢谢你。」

结果她再度瞄了我一限，然后就马上把脸往旁边转开了。少女接着张开嘴，以很小的声音说：

「——一定要打到决赛来啊。既然已经教你这么多了，希望还能教你最后一件事。」

「最后？」

「让你尝尝宣告败北的子弹是什么滋味。」

听见这句话后我不由得微笑了起来。这不是揶揄或者是苦笑，而是发自内心的笑容。我很喜欢像她这种个性的人。

「……我期待有那么一刻。不过，你确定自己能打进决赛吗？」

少女泠哼一声后小小呼出一口气。

「如果在预赛中落败的话我就引退。这次一定——」

感觉她凝视巨蛋里所有敌人的眼神，放射出强烈的琉璃色光芒。

「要把所有强手干掉——」

这句话几乎是在无声状态下说出来的，但些微的声波震动还是传进了我的耳朵。少女的嘴唇扬起，露出宛如狰狞野兽般的笑容。我的背脊涌上了许久不曾出现的冰冷战栗。

难怪这女孩会毫不在意那些男人所散发出来的压力。

因为她比那群人要强太多了。无论是身为VRMMO玩家的技巧——或者是支撑着本人的精神力。

少女瞄了一眼屏住呼吸、保持沉默的我之后，脸上的笑容旋即消失。她像在想什么事情般停住视线。接着又挥动右手叫出选单窗口。经过简短的操作之后，她的指尖上出现一张小小卡片。

她将卡片从桌上滑了过来，我接住之后少女开口说道：

「今天应该是我们最后一次像这样说话，所以我还是先报上名号吧。这就是将来要打倒你的名字——」

我默默朝卡片上看去。显示在上面的文字是——「Sinon」。性别当然是F。

「诗乃……」

我低声说完后，少女摇动水蓝色的头发轻轻点了点头。我也再度报上自己的姓名。

「我是桐人。请多指教。」

我无意识地在桌上伸出了右手，但名为诗乃的少女当然无视我的动作，直接将脸转往别的方向。我只好苦笑了一下并将手放了下来。

诗乃之后便保持着沉默，似乎不打算再开口说话了。

我抬头看了一下巨蛋屋顶的屏幕，知道剩余时间还有五分钟左右。这时我开始犹豫起该乖乖抱着膝盖坐在椅子上，还是硬着头皮再对她搭话一次比较好，但就在我做出结论之前，耳朵便听见朝这里走过来的脚步声。

我抬起脸，看见朝这张桌子直线走过来的，是一名额头上垂着银灰色长发的高大男性玩家。

他全身穿着比暗灰色还要稍亮一点的直线灰色迷彩服装。肩膀上挂着一把还算大的机关枪——应该不是冲锋枪而是突击步枪之类的武器，有着一张适合他高瘦体型的聪明脸蛋。由于身上几乎没有什么装甲，让人感觉他在战场上应该能以相当敏捷的速度移动。给人的感觉与其说像是身经百战的士兵，倒不如说像是特殊部队的成员。

男人完全不看静静坐在暗处的我，直接看着诗乃并露出了微笑。一瞬间原本看来相当干练的角色脸上出现了少年般的柔和态度，令我不禁轻轻眨了眨眼睛。

「哎呀，你怎么那么慢呢，诗乃。我还正在担心你不会迟到了吧。」

听见男人这种装熟的讲话口气，我一边在心里想着诗乃一定会给你钉子碰，一边缩起了脖子。但出乎意料之外的，原本缠绕在少女身上的冰冷气息瞬间缓和，她的嘴角甚至还露出了微笑。

「你好，镜子。因为一些意外而耽搁了点时间。咦，但是……你不是不打算出场吗？」

结果那个名叫镜子的男人尴尬地边笑边用右手摸着头。

「哎呀，不知道你会不会觉得烦，其实我是来帮诗乃你加油的。毕竟在这里还可以看大屏幕的实况转播。」

看来他们两个人是朋友，不然就是同一个公会的伙伴。诗乃移动身子后，镜子便理所当然般坐在她身边。

「话说回来，你刚才说的意外是怎么回事？」

「啊啊……就是带某人来到这里等等的……」

听见镜子的问题后，诗乃瞬间改用冰冷的眼神瞄了我一下。我一边觉得无可奈何一边把缩短的脖子恢复原状，然后对现在才注意到我存在的男性点了点头。

「你好，我就是那个某人……」

「啊……你、你好，请多指教。那个……你是诗乃的朋友吗？」

表面上看起来虽然不好惹，但这名叫做镜子的男性似乎与他那种精悍的外表不符，是个相当有礼貌的人。不然就是——他也把我当成女性了吗？

我一边想着该怎么回答比较有趣一边推敲着用词遣句，然而诗乃却马上简短的丢出一句：「别被骗了。那家伙是男的。」

「咦！」

我只好用一般的语气对瞪大眼睛的镜子报上自己的姓名。

「啊——我叫做桐人。我是男的没错。」

「男、男的……咦，这么说……那个……」

镜子用一副相当困惑的表情交互看着我和诗乃。看来是无法理解诗乃和男性玩家同行的状况吧。

心里想着原来是这么回事的我，因为恶作剧心理作祟而试着加油添醋的说道：

「哎呀，真是受到诗乃很大的照顾啊。」

这时诗乃马上用宛如蓝色雷射般的眼神瞪着我，接着粗暴的说道：

「喂……别胡说，我才没照顾你呢。说起来，什么时候允许你叫我诗乃了……」

「干嘛说得这么无情呢。」

「什么无情不无情的，你本来就是个陌生人！」

「咦——但你明明还帮我搭配了武装啊？」

「那……那是因为你……」

当我们对话到这里时……

巨蛋内原本的细微BMG这时忽然逐渐消失，开始响起由电吉他演奏的震耳乐曲。接着则是大音量的甜腻合成声音在几百人头上响了起来。

「让各位久等了。我们现在就开始举行第三届Bullet of Bullets的预赛。各位报名参赛的玩家在倒数结束后将会自动被传送到预赛第一回合的战场。在此祝各位好运。」

巨蛋里响起了震耳欲聋的拍手与欢呼声。在「喀哒哒哒」的自动枪械击发声与尖锐的雷射发射声后，一片五彩缤纷的灯光便像烟火般照耀着屋顶。

诗乃在吵杂声中站起身子，然后将右手食指对准了我。

「要打到决胜啊。到时我会把你的头轰飞。」

我也跟着站了起来，笑了一下之后这么回答：

「如果要找我约会的话，我当然是乐意之至了。」

「你、你这……」

倒数二十秒的时间即将要归零，我对诗乃挥了挥手后便转向前方准备被传送到战场上。这时我的眼神和一直凝视着我的镜子对上了。

他锐利的眼睛里明显带着警戒与敌意，当我觉得自己可能做得太过火了时——

我的身体被蓝色光柱所包围，接着视线也立刻化为一片蓝光。

最后我被传送到一块浮现在黑暗当中的六角形面板上。

眼前有一片淡红色全息图窗口，上面有大大的字体写着「KitoVS饿丸」。与名字只能使用英文字母的SAO不同，GGO里也可以使用日文。虽然对手姓名用汉字写着饿丸，但我当然没见过这个人。而窗口下半部则有一排写着「准备时间：剩余58秒  战场：被遗忘的古代寺院」的文字列。

这一分钟的准备时间应该是为了让人可以换上适合这战场的装备吧，当然这对预备的武装与地图都完全没有概念的我根本没有用就是了。我用右手叫出窗口，在与ALO相当类似的装备窗口主武器栏上组上名为「影光G4」的光剑，然后在副武装上组上「5—7手枪」。稍微确认一下有没有忘了装备的防具后便将窗口消去。

在等着数位数字慢慢减少的时间里，我朦胧地有了某种古怪的想法。

那个名为诗乃的少女一瞬间显露出来的狰狞微笑，以及凝缩成无坚不摧狙击弹般的杀气。

让我想起她那当时像直接在我脑海里响起的声音。

要把所有强手干掉——这直接了当的发言在某种意义上来看其实相当幼稚，但包含SAO时代在内我也没有过几次像当时那种战栗的感觉。我感受到由她娇小身躯里散发出超越角色扮演游戏的真实意志。

在电子信号所制作出来的假想世界里，我几乎没遇见过像她那样能散发出如此强烈意志力的玩家。在女性玩家里面，我所知道的就只有认真起来的亚丝娜而已。不对——即便是被称为「闪光」，甚至是以前被称为「狂剑士」的亚丝娜，也都没有给过我那种凶猛的印象。

有可能吗？会不会那名淡蓝色头发的少女就是我要找的「死枪」本人？

菊冈曾让我听过据说是死枪声音的声音档，但那种金属摩擦般的刺耳吼叫与诗乃那种清澈的声音完全不同。但是GGO怎么说也只是个和SAO不同的普通游戏世界。一个玩家拥有复数角色，每次登录都使用不同角色的事情可以说是层出不穷。

而且由说话的语气看来，诗乃对于进入正式大赛似乎拥有绝对的自信。如果我预测死枪绝对会出现在这场大会里的看法没有错，那嫌疑者就可以缩小到三十个人左右。而诗乃当然也是其中之一。

老实说我实在不愿意检讨这种可能性。带我到商店然后说明各种事项时的她，可以说完全感觉不到任何杀气。而且甚至让人感觉得到她所散发出的些许寂寞以及想与人亲近的感觉。

到底哪一边才是真正的诗乃呢。

——不对，现在想再多也得不到答案。只要持剑交手，不对，应该说拿枪互击应该就能得到些线索了吧。

当我想到这里而将伏下的视线抬起来时，剩余时间刚好归零。我的身体再度被传送效果给包围。

接下来我便被抛在一片阴郁的黄昏天空之下。

吹过身边的风带着宛如尖锐笛子的声音。上空有许多碎裂云层流过，脚下的枯草则是不断剧烈晃动。

我身边耸立着不知道是地中海式还是哥林斯式的巨大圆柱。它们大概以三公尺左右的间隔排成コ型。有些柱子上部已经崩毁，有些柱子已经完全倒塌，看起来就像消失文明的神殿废墟一样。

我先把身体靠在最近的柱子上然后迅速看了一下周围环境。

四周宽广的枯萎草原正被风吹得缓缓摆动，低缓丘陵的远方也看得见类似这里的遗迹。按照诗乃的说明，战场是长宽各一千公尺的正方形，但要到地平线那端看起来应该足足有数十公里。这里应该是个设置了小河或悬崖的移动限制领域吧。

我继续想着她的解说。对战者现在应该出现在距离我至少五百公尺之外的地点，但目前视线里还见不到任何人影。他一定和我一样就藏在某座遗迹里面吧。由于没有显示敌人所在的箭头，所以得先靠自己找出敌人才行。

虽然可以选择继续躲在这里，等敌人失去耐心才开始行动的作战方式，但「等待」实在是不符合我的个性。与其老是待在这里，倒不如全力冲刺到最近的另一处遗迹，然后借着对方的枪击来迅速确认其所在位置……我一边这么想， 一边顺势用左手确认了一下装备在腰间的「5—7」手枪触感。

这时刚好有一阵强风吹过，周围的草原开始剧烈地晃动起来。当强风停止，枯草再度挺立起来的瞬间……

距离我眼前大概二十公尺处的草地里突然有一道人影无声地站了起来。

视网膜瞬间看见由对方两手摆出来的突击步枪、靠在枪枝机关部上的茶色胡须、盖住大半边脸的附放大功能护目镜以及插着伪装用杂草的头盔。战场里只有我和对手存在，所以他一定就是「饿丸」了。

我完全不知道他是在何时拉近距离的。而他身上的迷彩服很明显就是他能办到这种事的理由之一。那身服装除了有与周围草丛完全相同的卡其色之外，还有细微的直线条纹。当我还想着「原来如此，这就是六十秒准备时间的效用吗」时……

敌人架在右肩的黑色步枪已经伸展出数十条红色「弹道预测线」——而且线条完全贯穿包含我在内的四周围空间。

「呜哇！」

我不由得发出悲鸣，同时用力往地面上一踢，整个人就此往预测线密度最低的方向——也就是上空跳去。

紧接着敌人的步枪便发出「喀哒哒哒哒哒」的轻快声音，而我的右脚踝部分也连续感受到两次冲击。我标示在视线左上方的HP条合计减少了大约一成左右。那么多的子弹当然不可能全部避开。我现在才想起诗乃曾经警告过我的「全自动射击」这句话。

我在空中翻了个筋斗，然后落在背后那根半折的圆柱上方。为了试着反击而用左手从皮套里拔出5—7手枪。

但敌人完全不给我瞄准的时间。立刻又有无数的预测线在我身体上出现。

「哇啊啊啊！」

我发出丢脸的悲鸣，直接滚落到圆柱后面。接着又有一发子弹擦过左腕，HP也同时无情地减少。

降下来的弹雨几乎都落到石柱上，结果造成一阵「哔叽哔叽」的声音并有细微的碎片飞散。我拼命缩起双手双脚，让全身躲在圆柱后面。

——这果然和剑对剑的战斗完全不同！

之前那避弹游戏里NPC枪手的枪击除了有间隔时间外，最多也只有六发子弹，但光是要躲开那些攻击就已经得用上全部精神，面对现在这种——一秒里有十发以上的连射当然就更是束手无策了。

要用将吊在我右腰上的光剑「影光」砍中饿丸的胡须脸， 一定得要接近到他眼前才行，但在那之前我便已经变成蜂窝，HP也早就完全消耗殆尽了。

如果没办法完全回避，那就只有想办法「防御」子弹。但很不幸的，这世界里就算有可以削弱雷射威力的「防护罩」，也没有能防御实弹的魔法盾牌这种东西。如果是在SAO ，就还有把剑代替盾来使用的「武器防御技能」……

这时我突然将手放到用扣环吊在皮带的光剑上。只要能用这把剑防御几发子弹就好了。这应该不是不可能的事吧，因为以前的SF电影大作上不就有人用光剑轻松地弹开子弹吗？如果这是由美国企业所开发的游戏，那就一定能重现那一幕才对。但要做到那种至难的技巧，就必须先准确地预测出攻击自己的子弹轨道才行……

等等——

这办得到。应该能办得到才对。因为「弹道预测线」不是已经完全将子弹的轨道告诉我了吗。

我吞了口口水，右手用力将光剑从皮带上拉了下来。

现在枪声暂时停止了。我想饿丸他大概是再度藏身于草丛当中，准备从左边或是右边绕过来吧。

我闭上眼睛，将精神集中在耳朵上。

风依然咻咻的吹着。这时我努力将这种吵杂的声音效果由意识当中排除。接着把精神集中在晃动草原的摩擦声上，试着由固定的频率当中找出不规则的声音来。

这是只有在各种声音成分都能够完全分离出来的VR空间里才能办到的技能，从SAO时代起，这招「系统外技能」就帮了我不少的忙。比如说3级食材的「杂烩兔」，就得用这种技能才能给予致命的一击。

但在这里究竟能不能成功呢——

这时我的耳朵捕捉到左斜后方，有一道不规则的音源由七点钟方向往九点中方向移动。他移动了两、三秒钟后便停了下来，开始探查我的位置。

敌人接着又开始移动、停止，当他准备再度移动的瞬间……

「冲吧……！」

我随着对自己的叫声用力往地面一蹬，一直线全力往敌人藏身的位置冲去。

饿丸他应该没料到我会朝着在草丛里匍匐前进的他冲过去吧。当他从枯草当中站起身子，单膝跪地摆好射击姿势后大概花了一秒半的时间。

原本我和敌人隔了大约二十五公尺左右，但这时我已经冲过一半的距离。我一边跑一边用右手拇指按下光剑开关。令人感到安心的「嗡」一声响起之后，闪着蓝紫色光芒的剑刃由剑柄里伸了出来。

由饿丸突击步枪所延伸出来的数十条着弹预测线第三度出现在我身上。

至今为止我都是反射性地找寻可以藏身的地点，但这次我只让自己的双眼注视着眼前，忍受脖子后方刺激着感官的恐惧感。在拼命观察敌人之后，我发现细小红线不是全部同时出现，它们之间都稍微有一点时间差。而这些差距就是子弹由步枪枪口冲出来的顺序吧。

我控制比现实世界里还要娇小许多的身体往前冲刺，此时总共有六条预测线瞄准我身体。

其他上下左右的预测线都稍微偏离了目标。以目前这么近的距离来看，敌人的步枪——还有射手本身的命中率其实都不怎么样。

久违的PvP战斗所带来的紧张感似乎也让我开始将自己切换到战斗模式。视线的余白部分呈现放射状往外延伸，只有目标的身影显得特别鲜明，就是这种加速感令我感到怀念。在逐渐减缓速度的时间当中，只有意识以猛烈速度奔驰着。

敌人步枪的枪口猛然冒出橘色火光。

这个瞬间，光剑的刀身准确挡住六条线当中第一发与第二发子弹的轨道。

随着「啪啪！」声响起，光刃表面也爆出两道鲜艳的橘色火花。当我注意到这件事时，右臂已经以电光火石般的速度将光剑叠在第三发、第四发子弹的轨道上。接着再度响起子弹被高密度能源弹开时的冲击声。

无视「应该打不中我」的子弹群在耳边发出的尖锐风声持续往前突进，其实是件相当耗费精神的事情，但我还是咬紧牙关继续挥动手里的光剑。

第五……接着第六发！成功用剑弹开所有可能会命中我的子弹后，为了一口气冲过最后这段距离而全力往地面一踢。

「不……不会吧！」

饿丸蓄着大量胡子的下颚整个掉了下来，张大的嘴巴露出惊愕声。但是这家伙的手并没有因此而停下来。他熟练地退出空弹匣，同时拔出腰间的预备弹匣并准备将它装进步枪本体里。

为了阻止他这么做，我把握在左手的5—7手枪对准了饿丸。当手指碰到扳机的瞬间，以敌人胸部为中心处出现了一个淡绿色圆形，这虽然让我吓了一跳，但我还是不管三七二十一的开了五枪。

出乎意料之外轻微的后坐力由手节肘传到肩膀，饿丸在半透明圆形内部的肩膀与侧腹各中了一发子弹。剩余的三发虽然消失在他背后的草丛里，但命中的子弹已经贯穿他的防弹装备并让他受到了伤害。画面上他的HP条减少了一成左右。饿丸一个踉跄，一瞬间动作稍微停了下来。

对我来说这样的时间就够了。

进入剑刃攻击范围之后，我微微将身体往右一扭——

当我用似乎要冲破假想大地的速度往前踏步的同时，直接将完全没有浪费一丝冲刺速度的全力突刺——在SAO世界里被称为「致命冲击」的必杀一击刺进敌人胸口。

整把光剑随着类似喷射引擎般的震动声轻松贯穿敌人身体。感觉无处可发泄的能源风暴瞬间在敌人体内到处肆虐。

接着，夸张的光芒与声音呈圆锥状从我右手边向外放射，敌人的身体也变成无数多边形碎片飘散在空气当中。

我一边感受令人全身麻痹的战斗余韵，一边慢慢撑起身体。

左右挥动光剑让它发出嗡嗡声后，一瞬间差点想把剑收到背后，但我还是急忙把开关给关上。

将剑吊在右腰的扣环上，左手上的手枪收进皮套后，我才深深吐出憋了很久的一口气。抬头仰望黄昏天空时，发现低垂的雪层像屏幕般浮现恭喜获胜的字样。

第一回合好不容易获胜了。发现能用光剑防御子弹对我来说是个好消息。只不过运剑需要无比的集中力，而我的神经这时已经开始烧焦并冒烟了。

还得进行四场这种累人的战斗——

传送蓝光开始包围我垂头丧气的躯体。寂寥的风声逐渐远去，当声音转变成许多人类所发出的喧闹声时，我发现自己已经回到待机区域来了。

看来我目前也与传送前一样在墙壁边的包厢席附近。我注意着左右两边，但就是没看见诗乃与镜子的身影。如果诗乃还在战斗中的话，那么那个让我有点在意与诗乃究竟是什么关系的男人是跑到哪去了呢？我将视线放宽到整个空间后，发现靠近巨蛋中央部位的地方有个身穿都市迷彩的熟悉背影。他没注意到我已经回来，只是专心看着天花板上的大屏幕。

与他一样抬起头之后，我发现预赛开始之前只是单调播放倒数时间的巨大画面上，现在正播放着几个战场的情况。荧幕上以类似动作电影般的角度播放出玩家们在沙漠、丛林或者是废墟里使用手枪、机关枪或是步枪进行战斗的画面。

这应该是由正在进行中的几百场比赛里，选出作战画面来转播吧。每当播放出玩家遭到枪击后四处飞散的画面，聚集在巨蛋里的无数玩家便会发出震耳的欢呼声。

我一边想着不知道有没有播放诗乃的比赛一边往前走了几步。我从右上角逐一确认每个画面，但由于摄影机不停转动而无法分辨出来。我聚精会神的想找出她水蓝色的头发。

——由于太过出神，所以当右耳听见突然发出来的声音时才会让我吓得心臓几乎要停止。那道低沉、沙哑、且带着金属性质的声音像是直接钻进我的脑袋里一样。

「你是、真货吗？」

「……？」

我反射性向后退了一步并回头看去。

一瞬间还以为眼前站着一只幽灵。

当然我不是指真正的幽灵，而是在艾恩葛朗特第六十五层的古城区域里，有一种夜间出没的「幽灵系」怪物。

眼前这人穿着破破烂烂的暗灰色长袍。压得很低的头套下是一片黑暗，只有深处眼睛部分露出一点淡淡红光。

在待机巨蛋阴暗的照明下，站在我眼前这名陌生人的外表实在与SAO的幽灵系怪物十分类似。所以我反射性想要飞退并拔出光剑应战。我甚至无法完全抑制住这股冲动，右手整个震动了一下。

我一边喘息，一边看着那家伙的脚底。破烂的长袍底端可以见到些许脏污的靴子尖端。

他不是幽灵而是玩家。确认过这里所当然的事实之后，我悄悄将屏住的气息呼了出来。

仔细一看之下，发现那红色眼睛其实也不是什么鬼火，而是盖住整张脸的黑色护目镜镜片上的光芒。由于对自己这种像菜鸟的反应，以及对方没礼貌的在极近距离忽然搭话的行为感到有些生气，于是我便冷冷地反问道：

「真货……那是什么意思？你又是谁啊？」

但是身穿灰色长袍的玩家还是没有报上姓名，他只是再次故意朝已经拉开距离的我靠近了一步。但我这次也不再退后，而是在仅距离二十公分的位置坦然接受他的视线。

那种像是使用某种声音效果，混杂着倍音在内的声音断断续续响起：

「我看了、比赛。你用了剑、对吧。」

「嗯……是啊。这没有违反规定吧。」

可恶的AmuSphere忠实呈现了我内心的动摇，让我回答的声音听起来有些沙哑。灰色长袍男像是看穿我的内心一样又往前进了几公分。

接下来他便以低沉的声音嚅嗫了一句话。由于声音相当细微，所以即使在这种距离之下也必须集中精神才能听见。

「再问你、一次。你是、真货、吗？」

在还没理解这句话的意思之前，我内心便被一道宛如雷击般的预感击中，让我只能呆立在那里。

——我认识这个家伙！

不会错的。我绝对曾在哪里见过他。也曾像现在这样面对面讲过话。

但那是在哪里呢。登入GGO之后我只有和出现地点旁边想买我角色的男性、带我去买东西与报名参赛的诗乃以及她的朋友镜子等三人讲过话而已。所以说我并不是在这世界里见过他。

那是在ALO里吗？在阿尔普海姆里，我和这家伙都用另一个角色见过面吗？我拼命搜寻着脑袋里的硬盘，想着他的语气以及气息与哪个认识的人相近。但我实在是想不出来。我不记得曾遇过像他这种光站在眼前，全身散发出的冷气就能让人起鸡皮疙瘩的像伙。

哪里……我究竟是在哪里和这家伙……

这时破烂长袍晃动了一下，接着由里面伸出一只纤细的手臂。我虽然准备再度飞退，但仔细一看之下，我发现那只手除了戴着与长袍同样破烂的手套之外就没别的东西了。

那只手在空中对着我叫出窗口，接着用缺乏生气的动作操纵着。现在进行当中的第三届BoB预赛里分为六组的对战一览表随即出现在窗口上。

那像细金属状的手指敲了一下F组。结果F组的画面立刻扩大为全屏幕。他又点了一下之后，屏幕就将对战表的中央部份更加放大。

我的视线被他手指所指的一点吸引了过去。

上面列着两个名字。

左边是「饿丸」。而右边则是「Krito」。右边的名字上有一条发出淡光的线条向上延伸。刚才那场比赛里我赢了饿丸而进入第二回合战的情报早已经被播报过了。

他的手指稍微动，由上往下摸了一下Krito的字样。接着再度响起声音——

「这个、名字。那种、剑技……你、是真货吗？」 我瞬间遭受第三次，同时也是最大的冲击。

这时我的膝盖开始发抖，我必须拼命撑住才能让自己不倒下去。

这名灰色长袍玩家——我确实认识他！

「桐人」这名字的由来，还有我打倒饿丸所使用的剑技。这两种情报这家伙都知道。

也就是说……我并不是在GGO也不是在ALO里遇过这个人。

而是在SAO，也就「Sword Art Online刀剑神域」里面。在那款死亡游戏的主要舞台浮游城艾恩葛朗特里，我曾在某处见过这个人。

这名藏在破烂长袍下的角色……不对，应该说戴着AmuSphere与这个角色联机的玩家和我一样都是「SAO生还者」。

我的心跳在不知不觉中已经快得跟敲木鱼一样。如果不是在阴暗的巨蛋当中，一定会被发现我的角色脸孔已经完全苍白了。

「冷静、冷静下来啊！」此刻的我只能在脑里不停重复着这句话。

就算遭遇SAO生还者，也没必要慌成这样吧。在艾恩葛朗特快崩坏之前，我的名字就因为特殊技能「二刀流」的报导以及和血盟骑士团团长希兹克利夫公开单挑而广为流传了。而且刚才对饿丸所使用的「致命冲击」算是相当普遍的单手直剑剑技。在艾恩葛朗特里达到高等级的玩家，从刚才比赛的影像以及对战表的玩家名字就可以推测出我可能就是SAO攻略组的桐人。如果是我的话，在这个会场里发现当初可能认识的玩家，也一样会跟他搭话然后一起叙叙旧吧。

所以我根本没必要害怕。应该不用害怕才对。

但我为什么会如此…………

下一个瞬间————消除对战表后准备缩回长袍内的细长手臂上有一个部位吸引了我的目光。

像把破烂绷带卷上去般的手套前腕部分，大约是手腕内侧再上面一点的地方有一道细缝。可以从那道缝里瞄到他苍白的肌肤。

而那肌肤上面还刻画着大约五公分左右的正方形刺青。

图案是用漫画手法所表现出来的西洋棺木。盖子上画着露出诡异微笑的脸。而且盖子还稍微被拉开，从内部的黑暗当中伸出白色手臂对看见的人招手。过去在另一个世界里，有个男人使用加毒的水让我麻痹并准备杀掉我，当时他手上也有个同样的刺青。

那是「微笑棺木」的纹章。

当认出那个图案后，我还能忍住不大叫着倒在地面上，或是因为脑波异常而被强制注销，真可以说是奇迹了。

破长袍底下的玩家那红色镜片凝视着站在那里不做任何反应的我，接着低声说道：

「你、不知道、我在问什么吗？」

我缓缓且慎重地点了点游戏角色的头。

「……嗯嗯。我是不知道。真货到底是什么意思？」

「………………」

灰色长袍无声的往后退了一步。红色眼光像是在眨眼般开始闪烁着。

感觉似乎特别漫长的几秒钟后，无机质感觉倍增的声音响了起来。

「…………那就、算了。不管、你是打着假名号的、冒牌货………还是真货……」

他一边向后转，一边留下最后一句话。

——总有一天、会被我干掉。

这句话让人感觉得到，他所说的并不是游戏内的杀戮。

破烂长袍简直就像真的幽灵般无声无息地远去——接着忽然就消失了。

周围完全不像几秒钟前还有玩家存在的模样。

我瘦小的身体现在才开始动摇，勉强撑住后整个人便像崩塌般往旁边包厢座位坐了下去。接着我抱住痩小的脚，将膝盖抵在额头上。

闭起来的眼睑里，明显地印着那个虽然只见到零点一秒左右，但却相当清晰的小刺青。

微笑的棺材。在艾恩葛朗特里只有一个使用此纹章的集团存在。

那就是杀人公会「微笑棺木」。

在长达两年的SAO攻略期间里，陷入经济拮据状况而从其他玩家那里抢夺金钱与道具的犯罪者玩家可以说在初期就出现了，但他们通常是以多人数围住少人数的一方并强行要求交出值钱物品，最多也只是使用麻痹毒药而已。

实际进行攻击而让人的HP值全部耗费殆尽的话，该玩家在现实世界里也会真正死亡，所以还没有一个人敢做出那样的行为。因为这一万名玩家基本上都是重度的网络游戏狂，在现实世界里一直都是与犯罪无缘的一群人。

但这条「决不让人HP归零」的不成文规定，却因为一名怪异玩家而被打破了。

那男人的名字是「PoH」。虽然是有点好笑的角色名称，但却意外——或许应该说正因为这样而让人觉得他有一种特别的吸引力。

第一个吸引人的就是PoH他除了拥有异国情调的俊美外表之外，还是至少精通三国语言的多语言用户。他可能是日本人与西洋人的混血儿，而他那种日文加上流畅英文以及西班牙俗语，简直就像职业DJ在唱Rap的说话方式，很容易就改变了他周围玩家们的价值观。最后他们由游戏玩家变成了一个冷酷、顽固且现实的非法集团。

而他第二个吸引人的地方其实很简单，那就是PoH本身的实力。

他是一位天才的短剑使。短剑到了他手上简直就像是手臂的延长一般，其刀刃不必经过系统辅助也可以切碎怪物——或者是玩家。尤其是在死亡游戏后期，当他得到一把名称相当恐怖的大型短剑「杀友菜刀」后，实力连攻略组玩家都得忌惮他三分。

仰慕PoH的法外之徒们便被他以与血盟骑士团希兹克利夫完全相反的吸引力，慢慢地、 慢慢地将心中的界线放宽了。

在游戏开始的一年过后，也就是二○二三年的除夕夜。

规模膨胀到接近三十个人的PoH一群人，袭击了在练功区的观光景点里举行野外派对的小型公会，并将他们全部杀害。

隔天，不被系统承认的「红色（注：指杀害玩家）」属性公会「微笑棺木」的成立通知，被送到艾恩葛朗特主要的情报商手里。

不过刚才与我接触的灰色长袍玩家应该不是PoH本人。那种没有抑扬顿挫且时常中断的说话方式，与PoH宛如机关枪般激烈且充满煽动性的口气完全不同。

但是「微笑棺木」里确实有以那种方式说话的家伙在。我和那家伙碰过面并交谈过——应该也交过手才对。而且他不是一般的组员，而是相当高层的干部。明明已经回想起这么多情报，但为什么就是无法想出他的容貌与姓名呢。

不，其实我早就知道，想不起来的理由是因为我本身拒绝想起。

「微笑棺木」在二〇二四年元旦组成，而在八个月后的某个夏日夜晚消灭了。

当然，它并不是因为自动解散或是内斗而消失的。是因为攻略组，也就是在最前线战斗的玩家们组成五十人规模的讨伐部队，靠着武力来将其消灭。

其实我们早就应该采取这种行动了。但因为一直找不到微笑棺木的基地，所以才会延宕了八个月之久。

玩家在艾恩葛朗特里所能购买的房子或房间，无论是在街道里面或是外面都能够在NPC的不动产公司里确认正确所在位置。攻略组猜测他们应该是买下较大的房屋或者是碉堡等级的建筑物才可能容纳三十人起居，所以接受攻略组委托的情报商人查遍了从第一层开始的所有大房子。

但是这里面虽然找到了几个中小规模犯罪公会的基地，最重要的微笑棺木基地却是花了好几个月都找不到。

其实也难怪他们会找不到。因为微笑棺木是把低层区域里早已被攻略下来、里面没有连结上层的高塔，而且程序设计者配置之后很容易便会遗忘的小洞窟安全区域拿来当作基地。攻略组玩家基本上只会参加迷宫区高塔的攻略，中级玩家也只会潜入人数较多的迷宫而已。当然偶尔会有发现该问题洞窟并且进到里面的玩家出现，但不难想象他们很容易就被微笑棺木给灭口了。

隐藏在如此隐密地点的微笑棺木基地之所以会在八个月后被发现，是因为其中一名成员可能是受不了杀人的罪恶感而向攻略组告密。而攻略组根据这个情报进行侦查并确定该洞窟确实是那些家伙的根据地后，终于开始组成大规模的讨伐部队。担任部队领袖的是最大公会「圣龙连合」的干部。而「血盟骑士团」与其他有力公会里也有许多实力坚强的玩家加入，当时身为独行玩家的我也受到委托加入了部队。

我们部队的人数与平均等级都高于微笑棺木许多。因此我们认为只要封锁成为他们基地的洞窟安全地带出入口 ，应该就有很高的机率让他们不战而降。 但是——就与他们里面出了密告者一样……

我们严重保密并历经多次研讨的作战计划也不知道经由什么样的管道被他们知晓了。当我们冲进迷宫时，没有任何一个微笑棺木的成员待在安全地带的大房间里。但他们当然不是早已闻风而逃而是躲在迷宫的支道里，反过头来从背后袭击我们。

他们已经精心准备了陷阱、毒品、欺敌道具等各种手段来出奇不意的打击我们。讨伐部队一开始虽然陷入严重的混乱当中，但面对突发状况时的对应正是攻略组最需要的能力。所以马上就重整态势的我们也开始猛烈地反击。

但是——微笑棺木与讨伐部队之间其实有出乎人意料之外的差距存在。

那就是对于杀人是否有罪恶感。当了解到陷入狂乱状态的微笑棺木成员无论HP被削减到什么样的地步都不会投降时，我们产生了非常剧烈的动摇。

当然我们事先就讨论过这种状况发生的可能性。而当时我们也做出了必要时就算让敌人HP归零也在所不惜的决定。但是包含我在内的讨伐部队成员，在面临对手的HP条降到全红状态时，没有任何人能毫不犹豫地给予最后一击。讨伐部队里面甚至有人丢下自己的剑而蹲在地上。

首先是讨伐部队里出现了几名牺牲者。之后同样陷入狂乱状态的攻略组也杀了数名微笑棺木的成员。

而接下去的战况可以说是血腥无比的地狱。

战斗结束之后，讨伐部队出现十一名，而微笑棺木出现了二十一名牺牲者。当中有两名玩家是被我亲手用剑杀害的。

但是死亡与遭到逮捕的敌人里并没有看见首领PoH的名字。

那场战斗之中残活下来的十二名敌人玩家之后全被监禁在黑铁宫里，如果刚才那个灰色长袍玩家真是其中一名生还者，那我有可能在战后处理当中的某个时间点曾和他说过话。之所以记得对方讲话方式却想不起容貌与姓名，全是因为我一直强迫自己遗忘曾经讨伐过微笑棺木的事件。

不对…………

不，说不定那长袍底下的……

是我亲手杀害的两个人其中之一。

想不到我竟然会产生这样的想法，于是我维持着在椅子上抱膝的姿势拼命摇着头。开始用尽吃奶力气咬紧牙根，努力想改变自己的想法。

人死不能复生。SAO事件的被害者四千人里，无论是我所爱的人，或是我所恨的人，都再也回不来了。所以那个灰色长袍男一定是微笑棺木十二名生还者的其中一人。我应该知道他们所有人的名字才对。我忍受着挖出埋蔵在心底回忆时的痛楚，试着回想起他们的资料。

但就在这个时候……

我又因为注意到一个新的可能性而喘起气来。

那名灰色长袍所发出来的金属性扭曲声音。刚才只是发出相当低沉嚅嗫声，如果他全力大叫的话又会是如何呢……

一个礼拜前从声音档里听见的吼叫声又在我耳朵深处响起。

『……这是真正的力量，真正的强劲！愚蠢的人们啊，把我的名字随着恐怖牢牢记住吧！』

『我和这把枪的名字是「死枪」…………「death gun」！』 完全相同。不会错的。声波可以说是完全一致。

那家伙就是——

那个灰色长袍男就是「死枪」吗？

如果是这样的话，我这次潜入GGO后尽量引人注目，然后成为「死枪」目标的任务很快就能达成了。

但是……但是……我完全没想到事情会出现这样的发展。

「死枪」就是SAO的生还者，而且还是原微笑棺木的成员——如果真是这样……

那么可能藉由游戏内部枪击杀害现实世界两名玩家的男人……

说不定……说不定……真有那种力量……

这时我的左肩忽然被打了一下，我整个人差点发出悲鸣。因为惊吓而边发抖边抬头往上一看，马上发现那头水蓝色短发正在眼前摇晃着。

「你的脸色怎么那么难看……」

少女——诗乃皱起眉头这么说道，而我只能勉强撑起脸颊，对她露出像笑容般的表情。

「啊……没、没有啦……」

「刚才的比赛有那么惊险吗？但你看起来满早前就已经回来了不是吗？」

听到这句话后，我才好不容易想起自己正在参加「Bullte of Bullets」的预赛。眨了眨眼睛，看了一下周围后，发现原本挤满广大巨蛋的玩家群在不知不觉间已经减少了一半。因为第一回合预赛几乎都已经结束，失败者也被传送到地面上去了。我接下来的对战者应该马上就会出现，而第二回合战也将随之展开。

但在这种情况之下，我不认为自己还能够作战。

我依序看着从较远处露出惊愕表情的镜子与站在眼前的诗乃，无力地由松开的嘴里吐出一口气。

诗乃瞬间露出非常认真的表情并且说：

「只是第一回合战斗就这么狼狈，我看你是绝不可能打进决赛了。给我振作一点……我一定要报被你欺骗的一箭之仇！」

她说完后便握起左拳，再度捶了一下我的肩膀。

我在无意识中用双手抓住了这只即将离我远去的小手。随即将它拉到自己胸前然后靠在额头上。

「等、等一下……你在做什么啊！」

诗乃急忙低声这么说道，并准备将手抽走，但我却还是紧握着不让她离开。

即使是由多边形角色上传来的热量，也能让现在的我感到言语无法形容的温暖。当感觉到盘据在自己心中的那股恐怖冰冻感时，我整个人也开始微微发起抖来。

「……你怎么了……？」

我先是听见感到困惑的声音响起，接着感觉到胸口那只又小又温暖的手开始慢慢放松。

** 第七章

右手食指上些微的疼痛让诗乃皱起了眉头。

她试着用大拇指中段部分把这种感觉擦掉。但是那种刺激手指内部的疼痛感却是久久不能消失。

诗乃当然知道为什么会这样。

原因就出在桐人身上，右手就是被那个无礼又粗鲁的菜鸟给用力握住才会变成这样。

当然脑袋里多少也知道，这在常识上来说是不可能发生的事。诗乃现在是使用AmuSphere来潜入假想世界，在这里面就算手被握得再用力，现实世界里的肉体也不可能会有血液不顺或是神经遭受压迫的情形出现。这个世界里发生的所有肉体感觉，都只是机器借着电子脉冲波直接传送到脑部的模拟信号罢了。

但是——

但明明已经过了两个小时，诗乃现在右手上却还残留着被黑发光剑使紧握住时的压力与体温。

诗乃放弃消除刺痛感，开始将放在脚架上的反物质狙击枪放回右手上。接着继续将食指扣在调松弹力的扳机上。一起历经无数战斗的爱枪「黑卡蒂Ⅱ」，它的握把手感已经如同自己身体延长般熟悉，但目前手部的轻微疼痛感却仍然无法消失。

诗乃现在趴在略高崖上一小撮灌木丛下方，静静等待着狙击的机会。

这座战场的名称是「旷野的十字路」。地形是中央有一座干燥的高地，另外有两条直线道路互相交叉。对战对手的名称是「Stinger」。目前是BoB预赛F组第五回合战的第一场准决赛，从比赛开始到现在大约过了十二分钟左右。

只要能赢得这场比赛，无论下一场比赛的结果如何，都可以得到明天星期日晚上BoB大混战形式的正式大赛参赛权。但Stinger不愧是能打入第五回合的对手，实力可以说是不容小觑。

虽然名字叫做「Stinger」，但他也不是真的装备着携带式地对空「刺针飞弹」。他的主要武器应该是「FN SCAR」突击步枪，但这也已经算是相当危险的武器了。它配备着高性能ACOG瞄准镜，因此集弹率可以获得很大的修正。只要让他接近到目视距离，身为狙击手的诗乃就完全不是他的对手了。

幸好这个地图上要从被道路分割为四等分的一个区块移动到另一个区块时，一定得经过中央十字路口。而两名玩家的出现位置最少也隔了五百公尺，所以不可能一开始就被配置在同一个区块里。

也就是说Stinger为了要将诗乃纳入SCAR的射程里，就一定得想办法突破中央的十字路口，反过来说，诗乃也一定得在Stinger准备突破十字路口时狙击成功才有获胜的机会。

因此可以预测Stinger应该会尽量拖延强行突破的时间，好消耗诗乃的注意力。但也不能完全否定他反其道而行忽然就冒出来的可能性。

所以诗乃只能持续紧绷着神经，像这样一直透过瞄准镜注意着四周围。

现在由A到O共十五组的预赛选拔里，有一半以上组别的决赛已经分出胜负，目前大概只剩下十场比赛在同时进行当中。因此待机巨蛋、一楼大厅以及街上的酒店里应该都实时转播着所有比赛，但看着这场诗乃对Stinger比赛的观众一定会觉得很无聊吧。因为从比赛开始到现在，双方根本还没有发射过任何一发子弹。

不过同时进行当中的F组第二场准决赛一定是比这场无聊对决更刺激几百倍的对战。

因为那边可是使用两把冲锋枪的近距离战专家，对上了更夸张的超近距离战武器——也就是光剑的战斗啊。

虽然知道自己绝对不能有一丝的松懈。但诗乃的思绪还是回到那名充满谜团的少女，不对，应该是少年的身上。

十分钟左右解决第一回合战，回到待机巨蛋后诗乃马上就受到镜子——新川恭二的祝福。

简短地道完谢并准备回到刚才包厢席的诗乃，看见待在那里的桐人后不禁感到有些吃惊，没想到他竟然会比自己还快获胜。正当诗乃准备靠过去座位对他说「还满有一套的嘛」时——立刻又发现另一些让人惊讶的事情。

桐人在比赛开始之前明明都是一副大剌剌的态度，但现在却紧抱着膝盖坐在板凳上，低垂的头部和瘦弱的肩膀还不断微微发抖着。

……明明获胜了还那么狼狈，跟拿枪的对手战斗有那么恐怖吗？

这么想的诗乃无意识中伸出了右手，轻轻敲了敲穿着夜间伪装夹克的肩膀。

结果桐人马上吓了一大跳并缩起了身体，接着用极度惶恐的动作抬起头来。

他那极容易被误认为女性，兼具楚楚可怜与聪明伶俐的角色脸上——出现简直像看见地狱深渊般的极度恐惧表情。

「你的脸色怎么那么难看……」

诗乃不由得如此说道，结果桐人用力眨了几下眼睛之后，脸上才露出个相当僵硬的笑容。

面对回答我没事的桐人，诗乃提出了第一回合战有那么棘手吗的问题，但是少年只是将表情隐藏在长长黑发下并虚弱地呼出一口气，接着没有做出任何回答。

原本诗乃也不需要再多问些什么。

因为桐人他只是个故意不说明诗乃对他角色的性别误会，然后藉此要诗乃带他去买东西，最后甚至还厚着脸皮和诗乃进到同一间更衣室里的家伙。

当然误认对方是女孩之后就没有要求他提出名片的诗乃也有不对。所以诗乃其实有一半是在生自己的气。

自从在现实世界里被同学们利用之后，明明就已经在内心发誓不再依赖别人也不再需要朋友了。但在GGO里被相当难得一见的女性玩家拜托带路时，自己竟然就轻易忘记了这样的决心。

当时其实真的很快乐。不论是在商店里买东西的时候还是坐在三轮电动车后座的时候，诗乃都感觉到自己在GGO里面已经很久没像这样笑过了。没错——诗乃其实不是因为桐人是男生而生气。她是无法饶恕和桐人在一起时变得如些毫无防备的自己。

所以当她知道桐人通过第一回合战斗时，可以说是打从心里感到相当高兴。

因为只要在决胜战时遇见他，然后用黑卡蒂的子弹击破那楚楚可怜的角色，自己就能变得比遇见这家伙前还要坚强。在诗乃有了这种想法的时候，眼前的桐人竟然就像变成另一个人似的陷入极度恐惧当中。

诗乃在无意识中用力压低自己的声音说：

「只是第一回合战斗就这么狼狈，我看你是绝不可能打进决赛了。给我振作一点……我一定要报被你欺骗的一箭之仇！」

然后她握起右拳，再度轻轻捶了一下桐人的肩膀。

但诗乃的拳头却忽然被一双白皙的手给包住。接着更被强行拉了过去，最后整个被紧紧贴在桐人穿着军队工作服的胸前。

「等，等一下……你在做什么啊！」

她反射性的大叫并准备把手抽回来。但这名为桐人的瘦弱角色，竟然以让人惊讶其STR值的力道持续握着诗乃的手。

当然他的双手就跟冰块一样，而呼在诗乃手背上的气息也一样冷到了极点。

这时候诗乃的视线里马上闪烁着申告性骚扰行为的图像。无论是用左手触碰图像或者是发出宣告，桐人的角色就会被传送到格洛肯的监狱区域里暂时没办法出来。

但是诗乃却没有任何动作也没有任何发言。

眼前这个握住自己手并全身发抖的瘦小角色，给诗乃一种强烈的熟悉感。她曾经在某处见过这种模样的女孩子。一这么想之后，她马上就发现到，那女孩就是她自己。

当然不是狙击手诗乃，而是现实世界里的朝田诗乃。害怕那夹杂着血腥与硝烟味道的记忆，躺在床上缩着身体，不断嚅嗫着「谁来救救我」的诗乃就是这种样子。

一发现这一点之后，诗乃在不知不觉之间便放松了手的力道。

「……你怎么了……？」

诗乃低声问道，但对方没有回答。不过诗乃还是可以感觉得出来。

紧抓住诗乃手的黑发角色——不对，应该说角色内心那个不知长相也不知名字的玩家，或许也和诗乃一样受困于某种黑暗当中。

于是诗乃准备问他究竟发生了什么事……

但就在她要开门之前，桐人的身体就被淡淡光芒包围并消失了。原来是他下一个对战对手终于出现，因此就被传送到第二回合的战场上去了。

照那种样子看来，他应该是没办法继续战斗了吧。诗乃这么判断并微微叹了口气。

失败者将从地下的待机巨蛋里被传送到地面上的总统府大厅去，所以如果桐人落败，今天——或者是从今以后就没有和他见面的机会了。

当然就算是这样也没什么大不了的。打从一开始他就不是诗乃的朋友，只是一个顺便带他到总统府的路人而已。今天过后，他的容貌与长相都将会被自己遗忘。

诗乃一边对自己这么说，一边默默地把悬在空中的右手收回胸口。

但是——

桐人却大出诗乃意料之外的以光剑与手枪通过第二回合、第三回合甚至是第四回合的战斗。

在等待自己比赛的时间里，诗乃唯一一次有机会由屏幕上观看桐人的比赛。他采取的是可以用鬼气逼人来形容的舍身特攻战法。即使面对拿着突击步枪迅速发射子弹的AGI型对手，他也是一面以小小的手枪——也就是诗乃推荐的5—7手枪来反击一边由正面突进。只见他无视击中角色末端部位的子弹，靠着仅甩光剑将致命子弹档开的超级技巧瞬间接近敌人身边，然后将对方连人带枪一起砍下去。

在第一届、第二届BoB里都没有任何一个采取像他这种作战方式的玩家出现。在充满欢呼声的待机巨蛋里。诗乃只能瞪大眼睛看着出现在眼前的景象。

照这种情况看来，桐人有很大的机会打进F组决赛。但是面对这种常识外的对手，自己应该怎么应战才好呢。

看完桐人的比赛之后，就算自己的准决赛已经开始，诗乃脑袋里也还是有一部分想着刚才的情形。当然她同时也忍不住想着关于桐人这名玩家的事情。

一起买东西时他那种充满好奇心的自然笑容、被发现是男性之后那种无所谓的大剌刺态度、一回战之后紧抓住诗乃的手并不断发抖的软弱模样。还有——蓝色光刃毫不留情地斩杀对手时宛若鬼神的形象。

到底哪一种模样才是真正的「桐人」呢。

而自己又为什么会一直想着这种事情呢。

诗乃心里开始涌起一股莫名的焦躁，于是右眼一直贴在瞄准镜上的诗乃轻轻咬住自己嘴唇。就在这个时候——

在她看向一公里外视线的左侧。忽然有道巨大影子由直立的悬崖阴影里冲了出来。

诗乃半自动性地微调整黑卡蒂的准星。现在风向是从左边吹来，风速大约是二点五公尺。湿度则是百分之五。接着她便将微微发光的瞄准线中心点稍微往上移，然后在弹预测圆第一次收缩时便毫不犹豫地扣下扳机。

立刻由枪口发出一道轰然巨响。

瞄准镜的视线当中可以看见五十口径弹像穿越空气中的热气隧道般往前飞去，接着朝左下方画出圆滑螺旋曲线的轨道随即命中了影子上部。

「唉唷……」

诗乃一边呢喃一边将黑卡蒂的退弹杆拉下。空弹壳马上由弹仓里排出，下一发子弹跟着进入药室当中。

瞬间无声消失的影子结果不是对手Stinger，而是直径约一公尺左右的巨大岩块。

下一个瞬间，由岩石飞出来的同一个场所里，有一道更巨大的剪影一边扬起灰尘一边往前突进。

那是辆四轮装甲车「HMMWV」。车辆系的道具并不是玩家个人所有物，而是像隐藏宝物般藏在战场里某个地方，先找到的人就可以乘坐上去。明明应该是全新的车辆，但诗乃迅速就发现目前出现的车子正面有道小小的凹陷。也就是说一开始飞出来的岩石是那台车子故意撞飞出来的。

应该坐在驾驶座上的Stinger知道诗乃的主要武器黑卡蒂Ⅱ是无法连射的手动枪机形式。而且也知道诗乃一定瞄准了自己非得通过不可的十字路口。

因此他先用HMMWV将岩石撞飞到十字路口并让诗乃狙击该目标，然后在她准备发射下一发子弹前通过十字路口。

这确实是很不错的作战。事实上当诗乃进行退膛动作时，车子已经来到了十字路口的中央部份。诗乃只剩下一发子弹的机会。而且根本没有仔细瞄准的时间。

但是诗乃并不慌张。

Stinger虽然夺走诗乃身为狙击手最大的武器「无预测线的第一击」，但他也给了诗乃相当贵重的情报。诗乃的视线里还残留着第一发子弹所画出来的弹道曲线。只要她不自乱手脚的话，第二发子弹也可以按照同样轨道发射出去。只要利用这一点，就可以进行比第一发子弹更加精准的狙击。

诗乃稍微动了一下枪身，静静地扣下扳机。空间里再度扬起震天巨响。

发射出去的子弹像被吸进去般命中HMMWV侧面的小窗户，更轻松地贯穿了厚重的防弹玻璃。

接着车辆便开始到处蛇行，最后开到路肩的岩石上整个翻覆。它由正面冲进深处的山崖，然后引擎盖上喷出红黑色火焰。

「……明明干脆从车上跳下来用跑的，就能看见预测线来进行回避了说。」

诗乃一边低声说着一边装填上第三发子弹。她的右眼依然没有离开瞄准镜，到现在还是一直透过刻度镜片看苦燃烧的HMMWV。等了几秒钟之后Stinger还是没有出现，虽然几乎可以确认他立刻就死在驾驶席上了，但诗乃还是没有改变射击姿势。

一直到黄昏色天空出现恭喜获胜的字样时，诗乃才由树丛的阴影里爬出并站起身来。

比赛时间共十九分十五秒。顺利突破准决赛。

这下子便按照计划拿下参加明天BoB正式大会的门票了。但是诗乃别说是胜利手势了，脸上甚至连个笑容都没有。因为她的思绪早已经飞到接下来即将开始的F组预赛决胜战上。

谜之来访者桐人无疑一定比诗乃还要快获得准决赛的胜利。他的对战对手是两手装配着SMG冲锋枪的近距离战类型。就算对方能发射再大量的子弹，只要让那名光剑使接近身边，在削弱他HP之前早就被足以致死的能源剑给干掉了。因为桐人他可是拥有「预测弹道预测线」这种恐怖的技能。要在正面战斗中击倒他，就真的只能拿M134迷你炮机枪才有可能。

因此诗乃就这样以双手抱着黑卡蒂，一动也不动地等待被传送到下个战场的瞬间来临。

数秒后，诗乃没有回到待机巨蛋就直接被传送到决胜战的准备空间里。正如诗乃所预料，浮在页框面板上的窗口果然显示出下一战对手是「Kirito」。

经过下一次的转送后睁开眼睛，马上就有一条直线延伸至远方的高速公路，以及公路末端立刻就要下沉的血红色夕阳映入眼帘。

这是名为「大陆间高速公路」的战场。虽然跟之前的战场一样是长宽各一公里的四方形但因为无法离开东西向横贯中央的高速公路，所以事实上是面相当单纯的细长形地图。

只不过有无数的乘用车、输送车与坠落的直升机被遗弃在路面上，还有许多铺设路面直接向上突起，所以没办法一眼看穿道路的底端。

诗乃马上往后转，确认自己是位于几乎算是东边底端的位置。也就是说对手桐人是出现在西方高速公路离诗乃至少五百公尺的地方。

接着她又环视了一下周围环境。然后马上跑了起来。她的目标是横跨在右斜前方的大型观光巴士。由半开状态的后门冲进内部之后，直接就向通往一楼座位的楼梯爬去。她先是像飞扑般将身体趴在中央走道的地面上，接着从肩上拿下黑卡蒂Ⅱ并架起脚架。最后将枪口朝向巴士前面的大型窗户设置好并摆出卧射姿势，再把瞄准镜前后的可掀式护罩掀了起来。

太阳目前就在诗乃正面。因此她藏在外面任何地方来架设狙击枪，都可能会有瞄准镜反射出太阳光而让敌人察觉藏身之处的危险性。而要压制暴露藏身位置的狙击手可以说是相单简单的一件事。

但是在这台巴士里面的话，贴上防晒纸的玻璃窗就可以帮忙掩饰瞄准镜的反射光。而且这台巴士算是制高点，所以几乎可以望穿路面上所有的掩体。

桐人应该会以高速在掩蔽物当中不断移动的方法来接近自己。而有弹道预测线的狙击一定无法打倒像他那样的敌人。因此诗乃的机会就只有赌在对方还无法掌握她所在位置时的首发子弹上。

我一定会打中——

诗乃一边在心底深处坚定地念着，一边将右眼靠在瞄准镜上。

其实连她自己也无法说明为什么会如此想要获胜。

诗乃确实是被隐藏自己性别的桐人欺骗而帮他带路与搭配各种装备。而且还在休息室里被看见她换衣服的模样。

但这也不是什么大不了的事。她的道具没有受到任何损害，被看见的也只是角色的内衣而已。要忘记从格洛肯路上相遇到待机巨蛋里分手这几十分钟的事情其实相当容易。

但是现在诗乃就是想要赢过桐人，因为他拥有让诗乃过去在GGO里所有战役都相形失色的实力。没错——连那个恐怖的迷你炮机枪使都比不上桐人。这个今天刚来到这个世界，甚至不是枪手而是使用旁门左道光剑的家伙，为什么会这么厉害呢……

不对……

等等，或许我早就已经知道理由了也说不定。

那是因为我内心某个部分还是没有把他当成「敌人」。因为当那坐在坚硬位子上的家伙以又冷又发抖的手握住我时，我就感觉内心产生了一种无以名之的感情。

是同情吗？不对。

难道是可怜？这也不对。

又或者是共鸣？这更不是了。

没有人能够引起我的共鸣。跟我一样背负着那种痛苦黑暗的人不可能存在。我之前虽然有所期待，但不是已经被背叛过无数无数无数无数次了吗。

能拯救我的就只有自己的实力而已。就是因为领悟到这一点，我才会在这里。

我根本不想知道桐人他究竟有什么心事，也没有必要去知道。我要用不带感情的一击将那个角色轰飞，然后将其埋葬在过去被我击倒的无数角色当中并加以遗忘。

这就是我应该做的事。

坚定自己的想法之后，诗乃凝视着瞄准镜里的视野，手指也一直扣在扳机上。

所以——

当那道黑色剪影在深红夕阳前面浮现时，诗乃瞬间忘记身为狙击手的自制而发出声音。

「……啊……」

从在微风当中摇晃的黑发、身穿夜间迷彩色军用工作服的纤细身躯、挂在皮带上的光剑剑柄来看，眼前这人确实是桐人没错。

但是他却完全没有奔跑。甚至可以说没有隐藏住身体的意思。他只是慢慢、慢慢地走在高速公路中央微微隆起的中央分隔岛上。那种毫无防备的模样与刚才比赛的时候完全不同。

——这表示就算没有弹道预测线，也可以随时避过我的狙击吗？

当思绪在脑袋里炸开的同时，诗乃瞄准镜里的刻度线已经叠上了桐人头部。在手指要扣下扳机之前——诗乃马上就知道一秒前的推测是错误的。

因为桐人根本没有看前面。他深深低着头，像虚脱般全身没有任何力道，只是机械式的交互动着双脚。与刚才那场比赛里那种鬼气逼人的突进完全相反，可以说是毫无气力的走路方式。

那种样子绝对不可能躲开诗乃的狙击。因为黑卡蒂Ⅱ发射出去的子弹远超过音速，当听见声音时就来不及了。而且头往下看的话，根本就无法察觉发射子弹时的火焰。

也就是说——桐人打从一开始就不准备躲开子弹。他故意要接受攻击，然后在自行认输的情况下结束这场比赛。只要完成得到正式大赛参赛权这个目的，接下来的事情……比如说和诗乃的决胜战就一点都不重要了。他应该就是这种意思吧。

「……别开……」

由诗乃的嘴里吐出沙哑的声音。

她将手指把在扳机上并开始用力。绿色的着弹预测圆随即出现并以桐人低垂的脸孔为中心高速伸缩着。激烈的变化正表示出诗乃的心跳相当紊乱，但现在是轻微的顺风，并且距离只有四百公尺。只要诗乃发射就一定可以击中才对。

食指底下的扳机弹簧发出轻微声响。但诗乃这时却松开了手指。接下来她又再度用力，扳机也再次发出声音。但她最后还是作罢。

「……别开玩笑了！」

她发出像小孩哭泣般的扭曲声音。

同一时间她还是扣下了扳机。五十口径狙击枪的咆哮瞬时充满了整台观光巴士，大块的挡风玻璃一边变成白色粉尘一边粉碎。

发射出去的子弹直线贯穿夕阳带来的深红色空气——接着通过离桐人右颊五十公分以上的空间，命中横躺在桐人遥远后方的乘用车腹部。车体先是冒起火柱。接下来冒出黑烟。

十二点七毫米弹从头旁边经过所造成的风压让桐人微微一个踉跄，但他站稳之后立刻就抬起头来。

那宛如少女般的较好容貌带着些许「为什么没射中」的疑问神情。诗乃一边凝视着映在瞄准镜中央的脸庞，一边进行退膛动作并迅速发射第二发子弹。

这次的子弹从桐人头上飞过然后消失在战场远方。

诗乃再度装填与击发。第三发子弹在黑衣少年脚边稍微偏左的柏油路面上留下巨大弹痕。接着诗乃便重复装填、击发、装填、击发的动作。

六个弹壳滚落在诗乃周围，隔了一段时间后消失无踪。

但桐人却还是毫发无伤的站在那里，诗乃透过瞄准镜可以见到他只是持续投射出充满疑问的眼神。

诗乃缓缓站起身，用两手抱住黑卡蒂，开始在巴士走道上迈开脚步。她直接穿过几乎不留痕迹的挡风玻璃后来到地面上，接着继续向前走去。

数十秒之后，当来到离桐人仅剩下五公尺的距离时，诗乃停下了脚步。

她从正面凝视着黑衣光剑使，接着开口说：

「为什么……」

桐人似乎可以理解这个问题些意思以及夹杂在其中的责难之意。他黑色的眼珠产生动摇，再度往脚底下看去。

不久后，他就像NPC般以不带感情的声音小声回答道：

「……我的目的只是要进入明天的正式大赛。现在已经没有继续战斗的理由。」

这是诗乃早已预测到的答案。但正因为如此，无可饶恕的感情才会充满她的内心，让她吐出接下去的话：

「那比赛开始后你用枪射击自己不就得了。你是舍不得子弹钱吗？还是觉得故意让我射死帮忙增加一个杀人数我就会感到满足了……？」

诗乃再往低着头的桐人靠近一步。

「你要觉得这只不过是VR游戏里的一场比赛那是你的自由！但不要把你的价值观强加在我身上好吗！」

诗乃用发抖的声音一边叫着，一边也觉得自己现在说的话其实同样没有道理。

现在的诗乃也是在将个人的价值观强行加诸在对方身上。如果自己无法原谅桐人这么做，那么只要在第一发子弹时让比赛分出胜负然后忘记这件事即可。但她不但没这么做，还故意发射六发子弹恐吓对方，然后还正面对他爆发出自己的心情。说起来或许是诗乃比较无理取闹也不一定。

但是——

就算有所自觉，诗乃还是阻止不了自己。她没办法阻止自己抱着黑卡蒂的双臂不断发抖、脸上表情皱成一团以及两眼下缘流下一滴眼泪。

背对着远方逐渐沉下地平线的夕阳，桐人已经有些变成黑影的双眼紧紧闭上，嘴角也完全黏在一起。

不久之后瘦小的角色忽然全身放松接着流露出虚弱但多少带点感情的声音。

「……感觉上……我似乎很久以前也曾经被某人这样责备过……」

「……」

瞄了无言的诗乃一眼之后，桐人又静静地低下头。

「……抱歉。是我不对。只不过是游戏、只不过是一场比赛，但正因为如此才要全力以赴……不然的话。就没有生存在这个世界里的意义与资格了。我明明知道这一点才对……」

这时来自于异乡的剑士抬起头来，以漆黑的眼珠凝视着诗乃并开口说道：

「诗乃，可不可以给我补偿的机会。现在开始和我一决胜负吧。」

听见这出乎意料之外的发言后，诗乃瞬间忘记愤怒而皱起肩头。

「就算现在要开始也……」

BoB预赛以及正式大赛都是从不知敌人位置的情况下开始的遭遇战。像现在这样不作战便碰面了之后，就不可能回到开始时的状况了。

但是桐人只是微微一笑，接着从左腰的皮套里拔出上5—7手枪。两手制止反射性做出备战动作的诗乃后拉下滑套卡榫。他敏捷地在空中抓住排出的子弹，然后再度将手枪放回皮套里。

桐人左手手指不停转着细长的五点七毫米弹，接着又开口说：

「你应该还有子弹吧？」

「嗯嗯…………还剩下一发。」

「那我们就以决斗形式来分个高下。这样吧……离开十公尺之后，你用枪而我用剑摆出战斗姿势。然后我会丢出这颗子弹，当子弹掉落在地面的瞬间便开始比赛。你觉得如何？」

诗乃与其说是吃惊，倒不如说是因为他的异想天开而感到无奈。诗乃没有注意到，自己刚才的愤怒感已经在不知不觉间被稀释，只是开口这么说道：

「我说啊……你觉得这样可以分出高下吗？只是十公尺而已，这把黑卡蒂的子弹绝对会打中你。再加上我的技能熟练度，数值补偿以及这家伙的性能，这是系统上绝对会命中的距离唷。你根本没有挥动光剑的时间。结果还不是和你自杀一样？」

「不试试看怎么知道。」

自傲的说完之后——桐人那鲜红的嘴唇露出了微笑。

看见他那副表情的瞬间，诗乃感觉背后闪过一道电流。

他是认真的。这个光剑使是真的认为就算和诗乃进行这种西部决斗也能获胜。

确实黑卡蒂Ⅱ的弹匣里只剩下一发子弹。或许他是觉得只要避过之后就能够获胜，但这实在是太天真了。面对必中必杀的子弹，根本没有「任何办法」能躲过。购物中心里「避弹游戏」的那个枪手所使用的老古董左轮手枪，无论是弹速、准度与威力都远远落后于黑卡蒂。

但是——如果桐人真有某种「方法」的话呢……

那我无论如何都想要见识一下。

下一个瞬间诗乃便点了点头，接着开口说道：

「好吧……就用这方式分个高下。」

于是她转身，在中央分隔岛上往东走了十几步，接着再度转身面对太阳。

两人的距离刚好是十公尺。诗乃举起抱着的黑卡蒂后，将枪托抵在右肩并打开双脚摆出射击姿势。

现实世界里的话，再怎么强壮高大的男人都无法以站姿来发射反物质狙击枪，但GGO里只要有充分的能力值就有可能办到。当然诗乃有可能因为承受不住巨大后座力而向后倒，但反正只有一发子弹而已，所以也没关系了。

拉下退弹杆，将留在弹仓里的最后一发子弹送进弹膛里。

把脸颊靠在机关部并将眼睛贴上瞄准镜后，发现就算在最低倍率之下桐人的身影也充满了瞄准镜。

那宛如少女的漂亮脸庞上，已经看不出数分钟前那种毫无气力的模样了。他那黑曜石般的外表发出绚烂光芒，嘴上还露出充满自信的笑容。

桐人以左手指尖夹住由5—7手枪取出来的子弹，维持着手臂往前伸直的模样，然后从右腰上拔下光剑。大拇指推上开关之后，闪烁蓝白色光芒的能源剑刃便随着震动音伸了出来。

目前在外面看着F组决赛的观众们一定搞不懂这两个人在做什么吧。但是诗乃根本不管他们怎么想。虽然是剑对上枪这种照常识来判断就能知道结果的决斗，诗乃后颈部却还是感到一股令人焦躁的紧张感。

——那家伙果然有某种「方法」。

有了这种直觉的诗乃将黑卡蒂的瞄准稍微移开了去。

刻度镜片后面的桐人张口这么说道：

「那要开始啰……」

他左手手指毫不犹豫地向上一弹。子弹一边回转一边高高飞上天空，受到夕阳照射之后在上空发出红宝石股的光辉。

桐人沉下腰部。摆出左半身在前方的姿势。他右手上的光剑则是微微向下垂。那是种从脚指到指尖部感觉不到一丝力道的放松站姿，但是却有一股类似拿枪瞄准对方心脏的压迫感由这瘦小的角色身上散发出来。

诗乃也感觉自己五感的敏锐度开始剧烈升高。空中的五点七毫米弹速度变得相当缓慢。所有声音全部消失，只剩下自己身体与黑卡蒂Ⅱ的感觉。不对，应该说连这两种感觉的界线都已经变得模糊。射手与枪械完全融为一体，变化成只为了让子弹击中目标的精密装置。

视线里的白色刻度镜片与绿色预测圆全部消失。

作为信号的子弹缓慢且宁静地掉落在维持站姿的黑衣剑士面前。即使子弹垂直切过瞄准镜里的视线并消失无踪，诗乃也还是能够感觉到它的存在。子弹慢慢回转慢慢接近地面——锐利的弹头接触柏油路面——判定两个对象接触之后，游戏系统便将产生声音效果的命令传达给AmuSphere——由信号组件发射出来的电子脉冲波刺激了诗乃的听觉皮质区——

叮。

当这道细微声音响起的瞬间，诗乃的右手食指扣下了扳机。

接下去一秒钟内所产生的好几种现象都伴随着鲜艳的色彩，在诗乃加速的意识里留下了深刻印象。

由黑卡蒂那大型防火帽里迸发出橘色火炎。

而对面有一道蓝白色闪电斜斜地割裂了夜色。

闪烁着流星般光辉的两个小物体分别由桐人左右两边向后飞去。

诗乃受到反物质狙击枪的后座力冲击，整个人一边向后倒去，一边才了解到自己所看见的光景究竟是怎么回事。

他砍断了。

当做为信号的字弹落地那一瞬间，桐人右手上的光剑便往上斜斩，将原本应该命中他的致命五十口径弹在空中切断。诗乃所看见的两颗流星就是被高密度能源所切成两半，然后掠过桐人身体两侧向后方飞去的子弹碎片。

但是——怎么可能会有这种事情！

如果是猜测子弹轨道然后赌博式挥剑造成的结果就还可以理解。但是诗乃选择的不是一般人都会瞄准的角色中心线，而是对准了桐人的左脚。

像黑卡蒂这样的大口径枪械，都拥有「冲击损害」这样的追加效果。在这种超近距离之下，就算只是被打中手或是脚，也会因为承受冲击所造成的范围攻击力而让HP瞬间归零。

今天才转移到GGO里来，而且对枪械毫无了解的桐人不可能知道这件事。所以如果要猜测弹道的话，一定会守住身体的中心线才对。

但是桐人的光剑却准确地捕捉住往自己左大腿飞过来的子弹。而且在这种距离、这种弹速之下，预测线的辅助可以说一点用处都没有。那他到底是——怎么办到的……

在感到讶异不已的一瞬间，诗乃的手臂也没有闲着。她虽然往后倒，但左手还是赶紧放开黑卡蒂，本能性地准备拔出腰问的MP7。

但在她拔枪之前……

以闪电般速度冲过这十公尺距离的桐人马上就来到诗乃眼前。他右手上的剑刀一闪，诗乃眼前染上了一片蓝色。

会被杀掉。

虽然有了这种预感，但诗乃还是努力不闭上眼睛。她睁开的双眼前方，可以见到光亮的黑发在巨大夕阳下画出扇子状弧形——

接下来一切全都静止了。

右手黑卡蒂与左手MP7都往下垂的诗乃虽然整个人向后倾斜，但过了好一阵子都没有倒在路上。那是因为桐人的左臂从后面支撑着她。

诗乃就维持着后仰的姿势，而剑士右手上的光剑剑刀就整个抵在她那毫无防备的咽喉上。

这时她耳朵里只能听见电浆的低声震动与远处的风声。

左脚整个向外踏并探出身子的桐人与整个人向后仰的诗乃就像在跳舞般紧贴在一起，他们甚至还维持这个动作好一阵子。

桐人漆黑的眼珠就在自己眼前。无论是在现实世界或假想世界。自己都没允许任何人接近到这种距离，但诗乃现在却不在意这一点，她只是凝视着桐人的双眼并且低声说道：

「……你是怎么猜出我瞄准哪里的？」

能源剑后方的嘴唇轻轻开启：

「我透过瞄准镜看见你的眼睛了。」

眼睛。也就是——视线。

黑衣剑士表示是根据诗乃的视线来读出弹道。

诗乃从没想过，这个世界里竟然有人可以办到这种事。一种近似战栗的感觉由她背部直接贯穿头部顶端。

太强了。桐人坚强的实力已经超过VR游戏的范畴。

但这就更让人感到不解了——为什么那时候他会在待机巨蛋的角落里抖得那么厉害，又为什么会用那么冰冷的手紧抓住诗乃的拳头。

从诗乃的嘴里流露出相当细微的声音。

「有这样的实力，你还在怕些什么？」

结果桐人的眼睛稍微产生动摇，经过短暂沉默之后．他才用压抑的声音回答：

「这不是实力，只是技术而已。」

一听到这答案，诗乃马上忘记抵在喉咙上的光刃而剧烈摇着头。

「骗人。别说谎了。光靠技术不可能砍得断黑卡蒂的子弹。你自己也应该知道才对。要怎样才能像你这么强呢？我……我就是为了像你这样才……」

「那我问你！」

桐人突然以低沉却隐含着类似青之火炎热量的声音说道：

「如果你的子弹真的能够杀害现实世界里的玩家……而且要是不杀了他自己或是相当重视的人就会被杀。在这种状况下你也能毫不犹豫的扣下扳机吗？」

诗乃忘记呼吸，瞪大双眼。

一瞬间诗乃有了「他知道吗」的想法。这名谜之来访者知道将诗乃过去染上一片黑暗的那个事件吗？

——等等，不对。应该不是那样。这个人过去……可能也曾经……

支撑诗乃背部的左手变得僵硬，但马上又放松了。桐人一边无力的摇头一边让前发碰着诗乃的额头，接着又低声说道：

「我已经办不到了……所以我一点都不强。我……甚至不知道那时候被我杀掉的两个人，不对，是三个人他们真正的名字……只是闭上眼睛、捣住耳朵，努力让自己把那一切全部遗忘掉……」

诗乃听不懂这段话的意思。

但是她可以确认一件事。那就是桐人内心也隐藏着和诗乃同样的黑暗以及恐惧。而他在待机巨蛋里等待下一场比赛时一定遇见了某件事情。某件让他埋藏在心里的黑暗再度涌出的事。

MP7由诗乃手上滑落到地面上。

空下来的手像被透明丝线控制般向上抬起，越过光剑剑刃后靠近桐人白皙的脸颊。

当她的手指快碰到桐人的脸之前——

桐人脸上忽然又出现之前那种目空一切的笑容。虽然瞳孔深处还残留着痛苦的光芒，但这名剑士还是轻轻摇了摇头，像是要阻止诗乃的手般开口这么说道：

「那么——决斗就算是我获胜了吧？」

「咦……？啊，嗯……」

诗乃的心情一时之间没办法回复过来，所以只能不停眨着眼睛，结果桐人把脸更加靠近并且呢喃着：

「那可不可以请你自己投降。我不是很喜欢砍女孩子耶。」

那种令人生气又没礼貌的嚣张说话方式轻易地让诗乃想起自己的现状。也就是自己目前正被背后的左手以及光剑压制，呈现整个人与对方紧密接触且无法动弹的丢脸状态——而这种模样还直接被实况转播给待在待机巨蛋以及酒店里的人收看。

诗乃马上感觉自己的脸颊开始泛红，于是她也用从紧咬的牙根里吐出来的声音低声回答：

「……我很感谢有机会能再度和你对战。明天的正式大赛一定要活到遇上我为止啊。」

说完后她便转过头去，大喊了一声「投降！」

比赛时间共十八分五十二秒。

第三届Bullet of Bullets预赛选拔F组决赛结束。

** 后记

我是川原 砾。非常感谢您购买本系列第五集，跟另一个系列合起来算是我第十本创作的《Sword Art Online刀剑神域5幽灵子弹》。

在网络游戏里面，除了MM之外也还有另外两种相当受欢迎的游戏类型。其中一种是「Real-time Strategy（实时战略）」游戏，而另一种就是「First Person shooter（第一人称射击）」游戏了。

虽然两种我都喜欢，但要谈RTS的话，这点篇幅根本不够所以只好省略（笑）。

而FPS就如同它的名称一样，通常是拿着枪械以主角（=玩家）的第一人称视点来进行战斗的游戏。它的发源地是美国，所以现在不论是游戏数量或是玩家人口都是美国占绝对多数，但只要在在线到处与人对战，就会遇见让人想说「你是席摩•海赫（注：芬兰陆军神枪手）转生吗！」的情形出现吧。大概就是我还在全力冲刺当中，就听见远方传来碰一声，接下来我便从额头喷出血来倒地而亡这样的情况。或者是在接近战里，我明明已经拿着突击步枪扫射了，但对方却左闪右躲的靠近我身边，然后用刀子轻松干掉我（这种时候就让人想大叫「你是史帝芬席格转生吗！」）。不过也有人说只是我太逊了而已！

MMO里的PvP会因为等级与装备的差异而产生相当大的影响，但FPS基本上角色能力没有什么太大的差异，完全倚靠玩家的技术。而想在《SAO》系列里表现出这种类型「实力」的动机，便是我创作这篇《幽灵子弹》的原因之一。

只不过最大的问题就是我虽然喜欢FPS，但对于枪械可以说是一窍不通……这次在文章里面虽然使用了一大堆枪械名称与专有名词，但全部都是临时抱佛脚的急就章知识。

对这方面相当了解的读者在看故事时，可能会发现有许多让你大喊「这哪有可能！」的场面，但还是希望大家多包涵，把它想成「反正是在游戏里面」就好了。

在相关职务越来越多当中，还一直耐着性子陪我修正原稿的担当编辑三木先生、这次也以插画完美呈现本集两位（笑）女主角魅力的abec老师，以及尽管上一集后记里就写着「接下来会进入暴走状态」也还是支持我的各位，请用额头接受我充满感谢的头槌射门吧。下一集也请各位多多指教了！

二〇一〇年六月十八日

川原 砾