#+title: 刀剑神域 第十五卷 Alicization Invading
#+setupfile: ./setup.setup
* 第十五卷 Alicization Invading

** 第十四章 盗魂者（Subtilizer）西历二〇二六年六月～七月

台版 转自 轻之国度

扫图：Naztar（LKID：wdr550）

录入：Naztar（LKID：wdr550）

修图：肾亏

狙击手有著一头浅蓝色头发。

少女般纤细的身体，与巨大的五十口径狙击枪呈现不可思议的调和感。

因为她以卧射姿势背对著自己，所以看不见她的脸。但她一定有宛如山猫般凛然、姣好的容貌吧。

右眼靠在瞄准器，食指按在扳机上，一动也不动地持续瞄准下方道路的集中力确实值得称赞。虽然很想再继续待在背后观看，但剩余的时间不多了。

离开躲藏地点，开始走在废弃大楼的地板上。慎重地回避散布在地面的小石头、木片以及金属屑等微小物体，在完全无声的状态下逼近少女背后。

少女的肩膀忽然震动了一下。

应该是感觉到声音或振动之外的某种现象吧。虽然有非常敏锐的第六感，但已经太迟了。

伸出去的右臂缠住她纤细的脖子，然后用左手压住后脑勺。

在宁静，但是带著坚决意志的情况下使劲往上勒。

发挥「军队格斗术」技能的效果，少女可视化的生命──HP条开始急遽减少。狙击手拚命挣扎，但是这款VRMMO游戏「Gun Gale Online」，只要STR没有太大的差距，几乎不可能空手逃过已经固定的裸绞。不过现实世界也差不多就是了。

其实早就预测到，名为「Bullet of Bullets」的大赛总共二十九名参赛者当中，最想战斗……不对，应该说最想猎杀的蓝发狙击手，会从这栋五层楼建筑物的上方进行狙击了。

问题是不论从四楼还是五楼，地图上的主要街道都在射程之内。必须迅速做出她埋伏在哪个楼层的选择。

就常识来说，应该会选择能尽早进入狙击态势的四楼。但是，看见四楼的图书室时，直觉与理论就同时对自己发出低语。第六感告诉自己，那个狙击手在现实世界里应该还是年轻的学生。是学生的话，理论上应该会避开让人联想到现实生活的图书室才对。

结果预测果然中的。蓝发狙击手浪费了多爬一层楼的数十秒，出现在五楼的仓库里。

而现在，她就像是迷途闯进蜘蛛网的蝴蝶，脆弱的生命马上就要消逝了。

啊啊，如果这不是假想世界里二进位档案的减算，而是夺取真实生命的魂魄……

如果在手臂里死命挣扎的不是游戏角色，而是玩家真正的肉体……

「那个瞬间」会有多么美好啊。

表示在视界右上角的狙击手HP已经不到百分之五。但少女还是为了脱离绞技而拚命挣扎。

即使确定败北还是不发出无谓的声音，也没有放弃挣扎而变得毫无力气。即使身为敌人，也觉得她这种尽力而为的态度相当惹人怜爱。

于是就像抱著恋人一样，从后面把嘴巴靠近少女的耳朵，低声呢喃：

──你的灵魂一定相当甜美吧（Your soul will be so sweet）。

1

缓缓睁开眼睛。

不知道什么时候睡著了。看来上周刚买的义大利制沙发有点太柔软了。身体依然沉在柔轫的皮革里，瞄了一下左手腕上的智慧型手表。

凌晨两点十二分。

站起来后，稍微伸展一下背肌，然后走向南侧的玻璃墙。一整面都是由瞬间调光玻璃构成的墙壁，目前是呈现透明状态，从四十三楼的董事室可以眺望河岸的夜景。

在点起灯的高楼大厦群光线照射下，港口静静地发出亮光。长长的栈桥上，拴了好几艘大型船舶。

那种直线、带压迫感的外型并不是豪华客船。它们是属于美国海军太平洋舰队第三舰队的战舰。

加州的第二大都市圣地牙哥，长久以来都是与军事基地息息相关的城市。有超过两万五千名军方人员居住在此地，此处的经济主要是倚靠巨大的海军基地支撑。

但近年来已经出现各种急遽成长的新产业。例如情报、通讯、生化科技等高科技产业。

此外也存在把军事与高科技同时做为武器的企业。也就是主要接受军方或大企业的委托，帮忙进行警卫、训练甚至是在战场直接战斗的民间军事公司（PMC）。

身为总公司位于圣地牙哥闹区的「Glowgen Defense System」的首席技术长（CTO），加百列‧米勒一面低头看著港口的夜景，一面不自觉浮现浅浅的微笑。

刚才那场短短假寐中作的梦，让他的心情有一点点激昂。

梦境是关于几天前在这间董事室里参加的，完全潜行型游戏内的活动。

加百列几乎不太作梦，不过只要一作梦，就一定是详细重现过去的某个场景。双臂依然残留著蓝发狙击手死命挣扎时的舒畅感觉。就好像那不是梦，而是现实一般……

错了，不是那样。因为那场战斗不是现实，而是在假想世界发生的事情。

完全潜行科技是非常了不起的发明。自己要对开发者Akihiko Kayaba表达无上的敬意。他如果还在世，不论花几百万美金也要把他挖角过来。就算他是世纪的超级罪犯也一样──不对，应该说正因为他是这样的人才值得挖角。

但是AmuSphere带来的体验越是真实，终究不是现实的空虚感就越强烈。简直就像是不管怎么喝都无法止渴的盐水一样。

GlowgenDS的最年轻董事兼大股东的加百列，过著物质上没有任何不满的生活。但是他内心深处抱持的，却是用金钱绝对无法满足的渴望。

「……你的灵魂一定相当甜美吧（Your soul will be so sweet）……」

再说了一次梦中的发言。

其实很想用三年前就开始学的日文这么对她呢喃。但对方应该认为HP条上挂著US标签的自己是美国人，必须避免给她太过强烈的印象。将来应该有好好对话的机会吧，到时候还有很多事情想问她。

不自觉浮现在嘴角的淡淡微笑消失后，加百列触碰埋在窗户数个地方的触控感应器来降低透明度。结果变黑成为镜子的玻璃上就映照出自己的模样。

将一头金发微微往后梳的他，有一双蓝色眼睛。六呎一吋（186公分）的身躯上，穿著白礼服衬衫与深灰色长裤。鞋子是以哥多华皮革特别订制而成。虽然一看就是一副强烈的白人既得利益者的模样，但加百列认为自己的外表也不过是一种符号。因为肉体只是包裹灵魂的空壳罢了。

灵魂。

几乎所有宗教都采用了灵魂的概念。当然基督教也有人死后灵魂将会按照生前的行为而被送往天堂或地狱的说法。但加百列相信灵魂的存在并加以深究，并不是因为他是基督徒或者天主教徒的缘故。

因为他曾经实际体验，亲眼见过灵魂的存在。

在自己的手臂当中，生命即将消逝的少女，确实从额头升起难以言喻的美丽光芒聚合体。

加百列‧米勒是一九九八年三月出生在加州洛杉矶近郊的太平洋帕利塞德这个城镇。

身为家中独子的他，在富裕的父母亲投注大量精神、物质的爱情下长大成人。虽然生活的宅邸相当宽敞，里面有许多可以游玩的空间，但幼年加百列最喜欢的地方是父亲的收藏品保管库。

他的父亲是Glowgen Defense Systems的前身，Glowgen Securities的最大股东兼经营者，平常的兴趣是搜集昆虫标本，宽敞的保管库里排列著数不清的玻璃箱。加百列只要有时间就会躲进保管库，一只手拿著放大镜来观察各种颜色的昆虫，或者是坐在房间中央的沙发上沉浸于茫然的幻想当中。

独自在天花板挑高的微暗房间里，在周围数万只沉默的昆虫包围下，年幼的加百列有时会产生奇妙的感慨。

房间里面所有昆虫在某个瞬间前都还有生命。在非洲草原、中东的沙漠或者南美的密林里元气十足地筑巢并且寻找食物。

但是到了某个时候就被搜集者抓住，遭到药水处理，经过数次的买卖，最后来到米勒家整齐地排列在玻璃箱里。也就是说，这个房间除了是昆虫标本的收藏室之外，同时也是排列著数万只遭杀戮尸骸的巨大墓地……

加百列闭上眼睛，想像周围的虫子忽然取回生命的景象。

它们的六只脚拚命地在空中踢动，也不停振动著触角与翅膀。无数「喀沙喀沙、喀沙喀沙」的细微声音重叠在一起，形成清脆的细碎波浪朝著加百列扑去。

喀沙喀沙、喀沙喀沙。

加百列瞬间睁开眼睛。感觉被钉在正面玻璃箱角落的绿色甲虫，脚好像正在动。他立刻从沙发上跳下来，虽然跑到玻璃箱前面死命凝视著甲虫，但它这时已经变回没有生命的标本了。

如同金属般鲜艳的翠绿色甲壳、长著锐利尖刺的脚、浮现极小网洞的复眼。加百列想著，过去究竟是什么样的力量在驱动如此精致的物体呢？

父亲说过，昆虫没有像人类这样的大脑。他询问那么它们是用哪里思考后，父亲就给他看了一部影像。

镜头当中是一对正在交配的螳螂。圆滚滚的母螳螂从背后压住小小的公螳螂，然后使交配器互相接合。母螳螂有好一阵子没有动作，但忽然无预警地用双臂的镰刀抓住公螳螂的上半身，接著开始大口咀嚼它的头部。公螳螂就在加百列带著惊愕心情的注视下持续著交配，等自己的头完全被啃光后才分开交配器。然后在母螳螂松开镰刀时，一溜烟地逃走了。

即使完全失去头部，公螳螂依然攀上树叶、爬上树枝，持续以灵巧的动作逃亡。父亲这时一边指著影像一边说。

包含螳螂在内的昆虫，全身的所有神经都是脑部。所以就算失去只是感觉器官的头部，也还能活一阵子。

看见这种影像后，加百列有好几天都一直思考著那么螳螂的灵魂究竟在什么地方。就算头被吃掉也还能存活，那么就算失去腿部应该也没什么问题才对。这么说起来，是在腹部还是胸部喽？但昆虫们就算柔软的腹部被压扁，或者胸部被大头针贯穿，脚也还是能充满活力地活动一阵子。

如果失去身体的某个部位都不会立刻死亡，那么螳螂的灵魂是不是薄薄地散布在全身呢？当时只有八或九岁的加百列，拿家里附近捕捉到的昆虫做了几次实验后，得到这样的结论。

驱动昆虫这种半机械机关的不可思议力量──也就是灵魂，不论破坏哪一个部位都还会顽强地停留在躯壳当中。但是到了某个瞬间，才会觉得已经无法撑下去而放弃，然后舍弃躯壳离开。

加百列热切地希望能亲眼看见离去的灵魂，可以的话甚至想把它抓住。但是不论怎么对放大镜睁大眼睛，或者是慎重地进行实验，都无法捕捉到从昆虫身体里脱出的「某种物体」，更不用说能看到什么动静了。即使在宅邸后方广大树林深处制作的秘密实验场里花了漫长的时间与庞大的热情，也没办法实现这个小小的愿望。

年幼的加百列本能上理解，父母亲不会喜欢自己做这样的实验。所以自从螳螂那件事之后，就没有再向父亲问过同样的问题，也完全没有透露关于实验的事情。但越是隐藏，这样的欲望似乎就越是强烈。

那个时候，加百列有个同年纪的好友。

那是一个名叫爱丽西亚‧克林格曼的女孩。身为企业家独生女的她，就住在邻接加百列家的宅邸里。两人当然念同一间小学，而且两家人也经常有交流。爱丽西亚是名内向、温顺的少女，跟在外面玩得脏兮兮比起来，她比较喜欢在家里看书或者录影带。

加百列当然也没有把秘密实验的事情告诉爱丽西亚，甚至连昆虫与灵魂的事情都没提过。

但他脑袋里还是持续思考著这件事。有好几次加百列都一边窥看著在自己身边露出天使般笑容并且专心阅读著故事书的爱丽西亚，一边想像著她的灵魂究竟在哪里。

昆虫和人类不同。人类失去头部就无法存活。所以人的灵魂应该在头部……也就是在脑袋里吧。

但是，加百列用了父亲的电脑上网搜寻后，早已得知脑受到损伤并不一定会造成死亡。也有被粗铁管直接从下巴往上贯穿脑部依然没有死亡的建筑工人，以及想要切除一部分脑部来治疗精神病的医生。

所以，应该是在脑的某个部分吧。加百列一边看著爱丽西亚被宛如棉毛的金发围起来的额头，一边这么想著。爱丽西亚的灵魂就藏在光滑的肌肤、坚硬的头盖骨与柔软脑组织的极深处。

自己一定会和爱丽西亚结婚吧，稚嫩的加百列心底规划著这样的未来。这样的话，说不定有一天能够亲眼看见爱丽西亚的灵魂。如同天使般美丽的爱丽西亚，灵魂一定是美得笔墨难以形容。

加百列的这个愿望，竟然很快地在意想不到的情况下实现了一半。

二〇〇八年九月，巨大投资银行的破产，扣下了世界金融海啸的扳机。

不景气的浪潮也吞没了洛杉矶郊外的太平洋帕利塞德。有好几间豪宅遭到出售，路上的高级轿车也变少了。

幸好Glowgen Securities的经营一向是走稳健路线，才得以把影响压抑到最小，但是隔壁的克林格曼先生经营的不动产投资公司就背负了庞大的债务。隔年四月，失去包含宅邸在内所有资产的一家人，为了投靠经营农场的亲戚，决定搬到遥远中西部的堪萨斯市去。

加百列感到很伤心。以十岁小孩子来说算是聪明的他，了解只是十岁小孩的自己帮不了爱丽西亚，也确实想像出今后有如何严酷的环境在等待著爱丽西亚。

拥有完美保全系统的宅邸、每天由熟练厨师制作的三餐、全是富裕白人小孩的学校，这些特权将永远离开爱丽西亚的人生，改由贫困与劳动来取代。更重要的是，爱丽西亚总有一天理应属于自己的灵魂，会受到某个不知名的人伤害并且失去光辉，这实在让加百列难以忍受。

所以他选择杀了爱丽西亚。

爱丽西亚在学校跟大家道别的当天，加百列把从回家校车上下车的她邀到自宅后面的森林里。他巧妙地避开设置在道路与家家户户围墙上的所有监视镜头，一边确认没有被任何人看见一边走进森林里，然后走在不会留下脚印的树叶上，引导爱丽西亚来到被浓密灌木林围起来的「秘密实验室」。

不知道过去曾经有无数昆虫在此丧命的爱丽丙亚，当加百列用两只手臂绕过她纤细的身体时，也用力地回抱著加百列。爱丽西亚轻轻地啜泣，然后说了不想到别的地方，只想和小加一直在这里生活。

加百列心里呢喃著「我会实现你的愿望」，然后把右手伸进上衣口袋，拿出事先准备好的道具。那是父亲处理昆虫用的，带有木制握把的四英吋长钢铁制长针。

他悄悄地把锐利的尖端伸进爱丽西亚的左耳，然后以左手按住她的右耳，在没有任何犹豫的情况下把针完全插了进去。

爱丽西亚像是不清楚发生什么事情般，愕然地眨了眨双眼，接著冷不防身体产生强烈的痉挛。数秒钟后，瞪大的蓝色眼睛失去焦点，最后──

加百列就看见了「那个」。

从爱丽西亚光滑的额头中央，出现了发出闪闪亮光的小小云状物体。它轻飘飘地靠近加百列的眉间，然后毫无抗拒地进到他的头里。

春日午后包围四周的柔和阳光消失了。几道白光从正上方贯穿高处的树梢降了下来，加百列感觉自己好像听见细微的钟声。

难以言喻的高昂感让加百列的双眼流下泪水。刚才自己看见了爱丽西亚的灵魂……而且不只是这样，加百列甚至直觉自己看见爱丽西亚灵魂正在看的东西。

光辉的小云朵花了像是永恒般的几秒钟穿过加百列的头脑，然后在从天而降的光芒引导下持续往上升，最后消失无踪。这时春日的日照与小鸟的鸣叫声又重新出现了。

加百列以双手抱住失去生命与灵魂的爱丽西亚，思考著刚才的体验究竟是真实，还是因为极度兴奋所产生的幻觉。同时他也确信，不论是真是假，自己今后的人生都将追求刚才所看见的东西。

加百列把爱丽西亚的尸体，放进事先在巨大栎树根部发现的一个深邃直立洞穴里。接著慎重地检查自己的身体，把附著在身体上的两根长长金发拿起来，一起丢进洞里面。长针则是洗干净后放回父亲的道具箱里。

即使地方的警察奋力调查，还是无法发现爱丽西亚‧克林格曼失踪事件的任何线索，最后事件只能无疾而终。

从短暂、深沉的回忆里醒过来后，二十八岁的加百列‧米勒把视线从玻璃镜子上映照出来的自己移开，直接走到放在西侧墙边的办公桌旁。一坐到挪威制的躺椅上，埋设在桌子玻璃桌面里的三十英吋萤幕面板就有电话型的图像闪烁。

一碰之下，随即出现女秘书的脸庞，同时也有声音传出。

「米勒先生，抱歉在休息时间打扰您。营运长（COO）弗格森先生想约您明天一起用晚餐。不知道您意下如何？」

「跟他说我行程都排满了。」

加百列立刻这么回答，平常总是很冷酷的秘书露出有点困扰的表情。因为COO可是副社长，也就是GlowgenDS的第二号人物。只不过是一名董事其中之一的加百列──原本不能拒绝这种高层的餐会邀约才对。

但是秘书困惑的表情一秒钟左右就消失，接著传出沉稳的声音：

「遵命，我会如此转达。」

电话挂断后，加百列就把身体深深躺进椅子里，接著交叠双脚。

加百列已经知道弗格森要说些什么了。他一定是想阻止自己参加某个「作战」吧。

但COO内心的想法绝对完全相反。那只老狐狸心里一定巴不得我愚蠢地跑去战场，然后登上战死者（KIA）名单。因为加百列是前任社长的亲生儿子兼公司的大股东。

当然，加百列自身也知道大企业的董事参加实弹到处飞舞的作战是相当愚蠢的行为。就算有从军的经验，CTO的工作也是在安全的总公司办公室里订定整体作战计划，根本没有必要将自身暴露于危险的战场上。

但是他无论如何都得参加这次有极大内情的机密作战。因为那个案件与加百列看见爱丽西亚的灵魂之后，就赌上人生追求的事物有直接的关联。

作战的委托人不是国防部这个老客户，而是几乎没有打过交道的国家安全局──NSA。

上个月，两名来到这间房间的NSA探员，让几乎没什么感情的加百列产生好几次惊讶的感觉。

首先，这次作战完全是非法的任务。因为是要Glowgen的战斗小队搭乘海军潜水艇，然后强行袭击同盟国日本的船舰。而且就算在交战中杀害了对方的船员也无所谓。

至于作战的目的是要夺取某种科技。

听见详细内容的加百列，因为过于惊讶──或许可以说欢喜，忍不住轻声叫了出来。幸好探员们并没有注意到。

「Soul translation teology」。是自卫队（JSDF）内名为「RATH」的组织所开发出来的，能够解读人类灵魂的惊人机器。

身为灵魂探求者的加百列，原本就对在日本出现的完全潜行科技有强烈的兴趣。在Gun Gale Online里和日本的玩家们战斗，还学了日文就是因为这个理由。他甚至花了好几万美金，买到一台应该全部遭到废弃的「恶魔机器」NERvGear──当然，不是买来戴在自己头上。

加百列预测到日本的完全潜行技术的开发，将会因为那款死亡游戏的骚动而渐趋式微。但是他却秘密地持续进行研究，终于快要得知人类灵魂的秘密了。

对加百列来说，NSA的委托就跟命运没有两样。

虽然是大企业，终究不过是民间军事公司的GlowgenDS，当然不可能拒绝现在权力比CIA还要强大的NSA所委托的案件。急遽召开的董事会里，以两票之差决定接下这次的任务。为了防止情报泄漏，参加作战的战斗员都是专门从事暗杀任务，而且个人经历有些污点的契约社员──

而加百列则自愿担任作战指挥官。

当然，公司不会告诉战斗员们加百列是Glowgen的董事这个事实。如果他们知道的话，很可能马上会开始研讨背叛公司，绑架加百列要求赎金的可能性，这群人就是这样的家伙。

加百列甘愿冒这样的危险，也一定要到现场去。

NSA的探员们曾经这么说过。RATH藉由STL科技，不只成功解读，甚至还复制了人类的灵魂。如果被赋予「A.L.I.C.E.」代号的人工灵魂完成的话，就会被搭载到日本制的无人兵器上，东亚的军事平衡也会就此崩坏。

远东地区──不对，应该说世界上哪个地方发生纷争都不关自己的事。但听见爱丽丝这个名字的瞬间，加百列就下定了决心。

一定要把它变成自己的东西。

无论如何，都要把保存在名为LightCube那个小小媒体里的灵魂弄到手。

「爱丽丝…………爱丽西亚…………」

身体依然靠在放下椅背的椅子上，加百列静静地呢喃著这两个名字。嘴角则不知不觉浮现出些许微笑。

由加百列的祖父开创的Glowgen公司，社名是带有「产生光辉的物体」这种意义的自创名词。祖父当时似乎是想著幸福的光辉，但身为后继者的加百列，浮现在脑袋里的却只有爱丽西亚濒死前从额头飘出来的金色光辉。

产生光辉的物体。也就是灵魂。

这一切全都是命运。

一周后，加百列就要和十一名战斗员前往关岛，搭乘停泊在海军基地中的核子潜艇入侵日本领海。在作战开始前转移到搭载的小型潜水艇（ASDS）上，对成为目标的超大型海洋研究母船「O Turtle」发动强攻。

虽然不清楚能不能在没有人员受伤的情况下成功占领，或者是哪一方──又或者是双方都会出现死伤者，但加百列已经确信自己将得到「爱丽丝」与STL技术。至于NSA，只要随便复制LightCube的资料给他们就可以了。

就快要……就快要成功了。自从爱丽西亚之后，不知道用了几个人来持续进行著实验，却还是无法接近灵魂的本质，但自己马上要亲手抓住成功了。

就能够再一次看见那美丽的云朵了。

「…………你的灵魂……一定相当甜美吧…………」

这次加百列换成用日文再度呢喃了一遍，然后闭上了眼睛。

2

担任海狼级核动力攻击潜艇「吉米‧卡特」舰长的达利欧‧吉利亚尼上校，是一名从清扫鱼雷管的小兵一路爬上这个位子的，彻头彻尾的潜水艇船员。首次搭乘的潜艇是古老的白鱼级柴电动力潜水艇，在快令人发疯的狭窄舰内，不论去到哪里都有轻油味与噪音。

跟它比起来，世界上最花钱的海狼级潜艇简直就跟劳斯莱斯一样。吉利亚尼从二〇二〇年被任命为舰长后，就对舰艇与船员投注了相当大的心力。在严格的训练下，目前高张力钢板的船体、S6W型反应炉以及一百四十名船员就像生物一样连结在一起，技术已经熟练到不论什么样的海洋，只要水深足够就可以在里面任意遨游。

「吉米‧卡特」已经跟吉利亚尼的小孩差不多了。很可惜的是，自己已经到了从第一线上退下来，选择上陆或者提早退休的年纪，但推荐接任的副舰长格思里一定能成功地指挥本舰才对。

但是──

短短十天前，该舰接到了一件像要让吉利亚尼晚节不保般奇妙又危险的命令。

吉米‧卡特是被设计为支援特殊作战用的潜艇，搭载了能与海军特种部队SEALs共同进行作战的各种设备。搭载在后甲板上的小型潜水艇（ASDS）也是其中之一。

在这之前已经数次载著SEALs的队员，航行到其他国家的领海深处。但目的都是为了保护美利坚合众国乃至于全世界的和平。要前往战场的男人们，无疑都和吉利亚尼的部下有共同的使命感。

但是，两天前从关岛登舰的那些家伙──

虽然吉利亚尼只去后部区块看过那些乘客一次，但他差点就命令部下把他们赶到深海里。那十几个男人完全没有纪律，有人躺在地板上，有人的耳机里传出巨大音乐声，也有人正在玩牌赌钱，甚至还能看见散落一地的啤酒空罐。那群家伙绝对不是正经的船员。甚至连有没有军人的身份都很可疑。

只有一个人，也就是为了队员纪律散漫向吉利亚尼道歉的高大队长似乎还有点礼貌。

但是那个男人惊人的蓝色眼睛──

回握男人伸出来的右手之后，眼神和他相交的吉利亚尼，随即再次感受到长久以来忘记的感觉。

没错，那是在加入海军之前，也就是少年时代发生的事。在出生并且长大的迈阿密海边游泳的时候，身边突然有一只大白鲨超越自己身旁。幸好当时没有遭受袭击，但吉利亚尼在近距离下看见那只鲨鱼的眼睛。那是能够吞没所有光线，宛如无底洞一般的眼睛。

男人的眼睛深处，也扩散著和那只鲨鱼同样的虚无……

「舰长，舰首声纳有反应了！」

声纳士忽然传出的声音，把吉利亚尼从回忆中拉了回来。

「是核子反应炉的涡轮声，比对中……声纹一致，确定是目标的巨大人工母船。距离十五英哩。」

吉利亚尼切换意识，迅速从发布战斗指令的舰长席做出指示：

「好，保持目前深度，减速至十五节。」

命令被重复了一次，接著就是一瞬间的减速感。

「知道护卫的神盾舰在什么位置吗？」

「目标西南西三英哩处确认到燃气涡轮引擎声……查核完毕，是海上自卫队（JMSDF）的长门舰。」

吉利亚尼死命盯著显示在正面大型萤幕上的两个光点。

神盾舰就不用说了，据说巨大人工母船是没有武装的海洋研究船。让这些武装的混混冲入那艘母船就是这次的命令，而且还是身为同盟国的日本船舰。实在很难相信这是总统或者国防部长承认的正规作战。

吉利亚尼脑海里重新浮现直接带来五角大厦命令书的黑西装男们所说的话。

──日本在那艘巨大人工母船里，进行著为了再次跟美国战争的研究。为了保持两国的友好关系，只能在极机密的情况下把这项研究毁掉。

吉利亚尼还没有嫩到会完全相信他们所说的话。

但年老的他同时也知道最后自己除了执行命令之外就没有其他选择了。

「客人准备好了吗？」

低声向站在旁边的副舰长做确认。

「在ASDS内待机中。」

「好……那就维持目前的速度，上升到一百英尺！」

压缩空气将压舱水箱内的海水推出，产生的浮力抬起「吉米‧卡特」的巨大躯体。和光点的距离缓慢但确实地减少。

日本人研究员会出现伤亡吗？恐怕难以避免吧。自己一直到死，可能都无法忘记曾经执行过这样的任务吧。

「与目标的距离剩下五英哩！」

拋开犹豫，吉利亚尼以毅然的声音下令。

「让ASDS脱离！」

微小的震动传到身体上，宣告著后甲板上的行李已经离舰。

「脱离完成……ASDS开始自力航行。」

带著一群野狗与一只鲨鱼的潜水艇速度越来越快，一直线朝著漂浮在海面的巨大海龟腹部前进。

** 第十五章 于北方之地 人界历三八〇年十月

1

把洗好的盘子放在晾干用的篮子里，爱丽丝‧辛赛西斯‧萨提一边用围裙的裙襬擦手一边抬起头来。

小小玻璃窗外的许多树梢，因为这几天的寒流，让上面已经泛红或者黄色的树叶散落了一地。和央都圣托利亚比起来，这里的冬天果然来得快多了。

就算是这样，从久违的蓝天照射下来的索鲁斯光线看起来还是相当暖和。正面树木的粗大树枝上，一对爬树兔正靠在一起，看起来很舒服般享受著日光浴。

带著微笑看著这种模样一阵子后，爱丽丝就转过头说：

「今天天气很好，我们就带著便当到东边的山丘去吧。」

但她没有得到回答。

只有两间房的圆木小屋里，兼具客厅、食堂、厨房功能的房间中央，放著一张简朴的白木桌子。

一名黑发年轻人坐在其中一张同样简朴的椅子上。爱丽丝的呼唤没有让他抬起头，只是持续茫然盯著桌子上的某一点看。

他本来就不是丰腴的体型，现在明显比爱丽丝还要纤瘦。即使隔著宽松的居家服，也能看出他骨瘦如柴的体格。没有内容物的右边袖子无力地从肩口往下垂，让他的模样更让人不忍直视。

与头发同样漆黑的眼睛里没有光辉。空虚的双眸只映照出他封闭的心。

压抑下不论感觉到多少次都无法习惯的胸口疼痛后，爱丽丝用开朗的声音继续说：

「外面有点风，还是穿厚衣服比较好。等一下喔，我马上就准备好。」

她脱下围裙，将其挂在流理台旁边的钩子上，然后朝旁边的寝室走去。

将金色长发绑在脑后，并且用棉质头巾盖住。依然没有视力的右眼则用一条褪色的黑色碎布缠住。穿上一件挂在墙壁上的毛织外套后，把另一件夹在腋下并回到客厅。

黑发年轻人完全没有动作。静静把手贴在他瘦削的背部加以催促后，他才用僵硬的动作从椅子上站起来。

但年轻人最多也只能这样了，他连一梅尔都没办法走。爱丽丝从后面把外套披到他身上，再绕到前面确实把脖子底部的皮绳绑好。

「再忍耐一下。」

对少年搭完话，她就急忙跑到房间角落。

放在那里的，是一张由亮茶色木材所制成的坚固椅子。上面还有大小两组铁制车轮代替四只椅脚。那是在森林里独居的，名为卡利塔的老人帮忙改造而成。

爱丽丝握住轮椅椅背上的把手，滚动轮子把它推到年轻人背后。接著让身体摇摇欲坠的年轻人坐到皮革椅面，再以厚厚的围毯确实盖住他的双脚。

「好！那我们出发吧。」

当爱丽丝砰一声拍了年轻人的双肩，握住把手准备把轮椅朝房间南边的门推去时──

年轻人的人忽然微微改变方向，以抖动的左手朝著东侧的墙壁伸去。

「啊……啊～」

低沉沙哑的声音根本不是任何单字，但爱丽丝马上了解年轻人的需求。

「啊，抱歉。马上帮你拿过来。」

年轻人伸出手的墙壁上，以坚固的挂钩挂著三把长剑。

右侧是爱丽丝拥有的金色长剑「金木樨之剑」。

左侧是过去年轻人腰间的的漆黑长剑「夜空之剑」。

正中间的则是主人已经过世的纯白长剑「蓝蔷薇之剑」。

爱莉丝首先把跟金木樨之剑差不多重的夜空之剑从墙上拿下来用左臂抱住。

接著拿起蓝蔷薇之剑。这把的重量只有黑剑的一半。因为收在剑鞘里的剑身已经有一半消失了。

而这把剑的持有人，身为年轻人好友的那个亚麻色头发的少年，现在已经不在人世……

她一瞬间闭上眼睛，然后才拿著两把剑回到轮椅旁边。默默把两把剑放到少年的大腿上后，年轻人就把左手放在上面，接著再次低下头。他只有在想要黑白双剑时，才会用声音与动作表达自己的意思。

「要抱好，不要掉喽。」

压抑胸口不论过了几个月都无法变淡的痛楚后，爱丽丝这么对他搭话道。然后推著増加重量的轮椅走出门外。

从门廊到地面的距离不是用阶梯，而是由厚厚的木板所构成。通过木板来到庭院里，立刻有冰凉的微风与平稳的日照包围两个人。

圆木小屋建在深邃森林深处一片开阔的草地上。是爱丽丝亲自砍下木材，刨皮并且组合而成。外表虽然不好看，但只使用高优先度树种建造的小屋可以说相当坚固。教导爱丽丝所有建造方式的卡利塔老人，当时不断重复说著从来没看过这么有力气的女孩子。

这片草地似乎是爱丽丝与尤吉欧孩提时期的秘密游戏场地。很可惜的是，自己完全想不起那个时候的事情。受到「合成秘仪」的影响，成为整合骑士前的记忆已经全被夺走了。

对于卡利塔老人以及其他村民，只简单地说了自己忘记过去的所有事情。但是现在的自己──整合骑士爱丽丝‧辛赛西斯‧萨提只不过是借宿在此地出生长大的爱丽丝‧滋贝鲁库身体里的短暂人格。如果可以还给本人，那么自己也愿意归还，但爱丽丝本来的记忆已经跟尤吉欧一起离开这个世界了。

「……那我们走吧。」

甩开一瞬间的沉思这么说完后，爱丽丝就从家门前推著轮椅前进。

直径三十梅尔左右的圆形草地几乎全被柔软的草皮所覆盖，只有东侧的一角，一根整个突出的树枝下堆了厚厚的一层枯草。简直就像巨大生物的巢穴──应该说根本就是巢穴，但目前看不见巢穴主人的身影。往那边瞄了一眼后，爱丽丝就一边想著它今天跑到哪里玩了，一边走过由南到北贯穿草地的小径进入森林。

道路在五十梅尔前方分为东西向。往西边走就可以到达名为卢利特的村庄，不过没特别的事情不会想过去。爱丽丝走向东边的道路，一边踩著从树叶缝隙照射到地面上的阳光，一边开始往前走。

她就这样缓缓走在十月将近尾声，逐渐从红叶转移到落叶季节的森林当中。

「会不会冷？」

虽然这么对年轻人问道，但是得不到回答。就算被极为寒冷的暴风雪包围，现在的他也不会发出任何声音。爱丽丝从他身后往前窥探，确认外套的衣领有确实拉紧。

当然，只要生成一两个热素就很容易能取暖。但卢利村里有觉得爱丽丝他们很可疑的村人，所以还是想避免造成滥用神圣术的谣言。

在经常有人走动的道路上留下新的轮子痕迹走了十五分钟左右，道路前方就变得明亮多了。树林到了尽头，眼前出现有点高的山丘。虽然道路也变成略为往上的坡道，但爱丽丝还是轻松地把轮椅推上去。

来到山丘顶端，视界一口气变得辽阔。

附近的东边可以看到鲁鲁湖的蓝色水面。更深处是广大的湿地，南方则是无限延伸的森林。往北方看去，就发现覆盖著皑皑白雪的「尽头山脉」贯穿天际耸立在远方。曾经骑著飞龙轻松飞越那些山峰的过往，现在好像是久远之前的梦境一样。

确实有用双眼看看美丽景色的心情。在这个充满地力与阳力的土地，应该可以治愈半年前在中央圣堂外壁失去的右眼。但是，目前实在没有独自用神圣术消除伤痕的心情。

因为即使面对无限宽广的晚秋风景，年轻人还是持续以空虚的眼睛茫然看著空中。

在轮椅旁边坐下来后，爱丽丝把身体靠在大大的车轮上。

「真是漂亮，比挂在中央圣堂墙上任何一幅画都美丽。」

她一边微笑，一边叫著年轻人的名字。

「……是你守护的世界喔，桐人。」

一只白色水鸟在湖水上划出点点波纹并且滑行，最后飞上天空离开。

不知道坐了多久。

回过神来，才发现索鲁斯已经升到相当高的地方。差不多该回小屋去准备午餐了。目前的桐人每次只能吃一点点食物，所以每一餐都不能够随便，否则他的天命上限会因此降低。

「差不多该回去了。」

当她站起身，一边这么对桐人搭话一边握住轮椅把手时──

就注意到踩著草皮爬上山坡的轻快脚步声，于是爱丽丝回过头去。

走过来的是一名穿著黑色修道服的少女。残留著稚气的可爱脸庞露出闪耀的笑容，并且使劲挥著右手。

「姊姊！」

兴奋的声音乘著微风传过来，爱丽丝嘴角也绽放出微笑并轻轻向对方挥手。

宛如飞行般冲上最后十梅尔距离的少女，停下脚步花了几秒钟调整呼吸，才再次用开朗的声音说：

「早啊，爱丽丝姊姊！」

她往旁边一跳，也元气十足地对坐在轮椅上的桐人打招呼：

「桐人也早啊！」

不在乎对方毫无反应的她，脸庞依然露出灿烂笑容。但在看见桐人放在大腿上那两把剑的瞬间，就出现些许悲伤的神情。

「……早啊，尤吉欧。」

她一边这么呢喃一边伸出右手，用指尖轻轻抚过蓝蔷薇之剑的剑鞘。不认识的人做出同样的动作，桐人就会稍微出现防御的反应，但目前则是乖乖地坐在轮椅上。

跟两个朋友打完招呼的少女，撑起身体再次转向爱丽丝。

爱丽丝意识到胸口深处产生不可思议的暖流，并且开口回答：

「早安啊，赛鲁卡。亏你知道我们在这里。」

当初是花了一个多月的时间，才能够不用赛鲁卡小姐来称呼对方。

半年前，在中央圣堂从桐人口中得知妹妹的存在后，就一直焦急地等待与对方见面的那一刻。但是，像目前这样实现愿望后，越是疼爱赛鲁卡，就越觉得自己──并非爱丽丝‧滋贝鲁库，而是名为爱丽丝‧辛赛西斯‧萨提的整合骑士，真的有资格成为她的姊姊吗？

不知是否注意到爱丽丝无法斩断的纠葛，只见赛鲁卡带著天真无邪的笑容说：

「我没有用神圣术找你们喔。到家里发现你们不在，然后今天的天气又这么好，我就想你们应该到这里来了。我把刚挤的牛奶和今天早上刚烤好的苹果起司派放在桌上了，等一下可以拿来当成午餐。」

「谢谢，真是帮了我一个大忙。我正烦恼不知道该做些什么菜呢。」

「凭姊姊做菜的技术，桐人哪一天说不定会站起来逃走喔！」

赛鲁卡说完就哈哈大笑，爱丽丝也笑著回答她：

「真敢说！我现在烤松饼已经不会烤焦了啦。」

「真的吗？明明一开始想用热素来烤松饼，结果却把它烧成了木炭。」

爱丽丝准备用指尖戳赛鲁卡的额头来警告她时，迅速躲过这一击的赛鲁卡直接就扑进爱丽丝怀里。看到妹妹用力把脸贴在自己胸口，爱丽丝温柔地把她的背抱过来。

只有这个瞬间，会强烈地希望能从心头承受的重压下逃走。

逃避整合骑士的责任，在远离人群的森林深处过著平稳的日子，如果能忘记这种行为带来的罪恶感，究竟会有多轻松呢？但爱丽丝同时也知道，自己绝对无法忘记这件事。和最爱的妹妹互相拥抱的这个瞬间，毁灭的时刻也一步步从尽头山脉后面逼进。

插图007

半年前，在公理教会中央圣堂进行那场激斗的最终幕──

受到足以耗尽天命的伤势，无法动弹的身体躺在大理石地板上的爱丽丝，隐约还记得战斗的结果。

最高司祭亚多米尼史特蕾达与手拿双剑的桐人之间的死斗。

被元老长裘迪鲁金妄执之火焚烧后，最高司祭因而消灭。

桐人的好友尤吉欧在肉体和爱剑一起断成两半后就此死亡。

看著尤吉欧咽下最后一口气的桐人，以激烈的口气对著出现在大厅北端的不可思议水晶板大叫。经过一段爱丽丝几乎无法理解是什么意思的对话后，桐人忽然像是全身僵硬，然后就直接倒在地上──接著世界就被寂静所包围。

当爱丽丝稍微回复一些天命，身体可以活动的时候，索鲁斯的曙光也正好从东边的窗户照射进来。以这道光做为神圣力的来源，爱丽丝首先治愈了倒地的桐人身上的伤势。但是他还是没有恢复意识，在没办法的情况下，只能先对自己施予治愈术，才调查他搭话的水晶板。

但是原本发出淡紫色光芒的表面已经完全失去光辉，不论如何触碰与呼唤，都得不到任何回答。

束手无策的爱丽丝只能瘫坐在地板上。

虽然相信桐人说的话，为了守护人界的人民与在边境生活的妹妹而与绝对的支配者亚多米尼史特蕾达战斗，但内心实在没想过自己能活下来。

当身体被最高司祭称为「巨剑魔像」的奇怪巨剑士兵深深贯穿时……

将自己的身体当成盾牌挡住降下的轰雷时……

以及挥下的剑刃正要了结桐人的性命，自己奋不顾身地冲出去时──

爱丽丝都有了死亡的觉悟。但是在贤者卡迪娜尔、不可思议的大蜘蛛夏洛特、尤吉欧的牺牲以及桐人的奋战守护下，终究还是保住了一命。

──既然救了我，就要负起责任啊！

对著躺在旁边的桐人这么大叫了无数次。但是黑发年轻人还是没有张开眼睛。接下来就自己思考，自己选择前进的道路吧……爱丽丝感觉他好像这么对自己说道。

抱著膝盖几十分钟后，爱丽丝终于站了起来。

不知道是不是大厅的主人已经消灭的缘故，升降盘也跟水晶板一样没有反应。用剑将其破坏后，就背著桐人往下跳到第九十九层。

从那里走下长长的阶梯，穿越众元老依然咏唱著术式的房间来到中央圣堂的大阶梯后，立刻前往被留在大浴场里的剑术师父──整合骑士长贝尔库利‧辛赛西斯‧汪的所在地。

被尤吉欧用武装完全支配术冻结起来的大量热水这时几乎完全融化。原本贝尔库利已经承受裘迪鲁金的石化术，幸好这时候他呈大字形漂浮在浴槽里的身体已经恢复原状了。

把巨大身躯拖到通道上，一边叫著「叔叔！」一边拍打他的脸颊后，魁梧的男性先打了一个大大的喷嚏才醒了过来。

贝尔库利先是以毫无紧张感的表情宣告「哦，天亮了吗」，爱丽丝才好不容易向师父说明状况。这时贝尔库利也不由得露出严肃的表情，听完全部的说明后就以极为有包容力的声音说了一句话。

他说：「辛苦你了，大小姐。」

之后骑士长展开了迅速的行动。把败给桐人他们，但是不知道为什么以毫发无伤的状态躺在玫瑰园中央的副骑士长法那提欧、同样被石化关住的迪索尔巴德与艾尔多利耶等整合骑士聚集在第五十层的「灵光大回廊」里，并且尽可能告诉他们所有的事实。

像是和北圣托利亚修剑学院的两名修剑士战斗后，最高司祭亚多米尼史特蕾达被打败并遭到消灭。

以及最高司祭本人正进行著把半数人民变成由剑骨组成的怪物兵器这样的恐怖计划。

还有理论上是骑士团上层组织的元老院，实质上只有元老长裘迪鲁金一个人，而他也和最高司祭一起死亡了。

只有整合骑士的来历──不对，应该说「制造方法」被隐瞒了下来。事先就对最高司祭「被从神界召唤下来」的说词感到怀疑的贝尔库利还能够承受知道实情的冲击，但他判断必须慢慢花时间来告诉其他骑士事情的真相。

但光是这样，艾尔多利耶与法那提欧等人还是产生了激烈的动摇。其实这也不能怪他们。拥有与神相同的力量，数百年来都以绝对支配者身份君临整个世界的最高司祭死亡的事实，原本就不容易接受了。

在经过极为混乱的讨论后，骑士们之所以选择暂时听从骑士长的指示，除了贝尔库利原本就拥有的声望与实力之外，可能也和「敬神模组（Piety module）」依然在运作有关吧。不论状况有什么样的改变，他们都还是效忠于公理教会的骑士，而亚多米尼史特蕾达与裘迪鲁金既然已经离开人界，骑士长贝尔库利无疑就是教会的最高层了。

而贝尔库利接下指挥权的瞬间，就开始将全部的精力投注于原本的任务，也就是「守护人界」上。他本身应该也有迷惑与纠葛才对。因为知道了自己被夺走的关于爱人的记忆，就存在于伸手可及之处。

但是他却把构成巨剑魔像的三十把剑以及三百多根水晶柱全都严密地封印在中央圣堂第一百层里，也决定暂时对骑士团之外的其他人隐瞒最高司祭死亡的消息。这是因为准备抵抗黑暗领域即将到来的猛烈侵略，比恢复自己以及其他整合骑士的记忆重要多了。

当贝尔库利尽力于重整已经崩坏了一半的整合骑士团，以及重新整编、训练虚有其表的人界四帝国近卫军等繁重工作时，爱丽丝当然也从旁提供了帮助。她的右眼绑著桐人帮忙制作的即席眼带，就这样在圣托利亚里四处奔走。

但她没办法一直留在中央圣堂。除了不少整合骑士之外，知道最高司祭死亡的众修道士里面，都开始出现应该对公理教会挥剑相向的反叛者──也就是桐人处刑的意见。

工作告刚一段落，爱丽丝就和桐人跨上飞龙离开央都。那是付出许多牺牲的激斗后，又过了两周之后的事情。

但接下来的日子也相当辛苦。露宿在外的不习惯生活当中，桐人还是一点都没有醒过来的迹象，虽然认为一直昏睡的他需要坚固的屋顶与温暖的床铺，但也没有足够的金钱可以住宿街上的旅馆，而且也提不起劲来使用整合骑士的权威。

这时候她才想起来，曾在中央圣堂外壁听桐人说过卢利特村这个名字。

就算失去记忆，只要是爱丽丝与尤吉欧故乡的居民，说不定会接受自己和桐人。于是她就在抱著一缕希望的情况下，将飞龙的缰绳朝向北方。因为必须照顾桐人的身体所以一次不能飞行太长的距离，结果花了整整三天才纵贯诺兰卡鲁斯帝国，到达位于尽头山脉山麓斜坡上的小村庄。

为了不吓到村人而降落在村子稍远处的森林里，命令飞龙在那里看守行李后，爱丽丝就背负著桐人徒步朝村子走去。

离开森林之后，穿越麦田进入小径，在那里遇见了几名村民。但他们都只是露出惊讶、怀疑的表情，没有任何人向他们搭话。

来到建筑在高台上的卢利特村，准备钻过木制的门时，一名高大的年轻人就从盖在旁边的守卫室里冲出来。还残留著雀斑的脸变得通红，挡住爱丽丝的去路后……

──等等，外人不准随便入村！

年轻侍卫一边大叫一边像要唤起注意般把手放在腰间的剑上，不过在看见爱丽丝背上的桐人后，随即露出怀疑的表情。嘴里低声呢喃著「咦，这家伙是……」并且再次凝视著爱丽丝，最后同时张大了眼睛与嘴巴。

──你……你该不会是……

听见他这么说，爱丽丝才稍微松了一口气。于是她便思考著用词遣字，对事隔八年似乎还记得自己的侍卫说道：

──我是爱丽丝。想找村长卡斯弗特‧滋贝鲁库。

或许应该自称爱丽丝‧滋贝鲁库才对，但她实在说不出口。幸好光说名字似乎就够了，脸色瞬间由红转蓝的侍卫，嘴巴开合了好几次后就冲回村子里去。因为他没有说等一下，所以爱丽丝钻过村子大门，朝侍卫跑走的方向前进。

刚过正午的村子里，立刻出现宛如蜂窝被戳到般的骚动。几十名村民挤在不算宽的道路两旁，当他们看见爱丽丝经过时，全都发出同样的惊呼。

但他们的脸上几乎都没有看见游子归乡时高兴的表情。甚至对身为女子却身穿金属铠甲的爱丽丝与她背上一直沉睡著的桐人感到怀疑、警戒以及恐惧。

坡度缓缓爬升的道路，最后与圆形广场会合。

中央有一座喷水池与水井，北侧则有一座上头挂著圆十字的小小教会。爱丽丝在广场入口停下脚步后，在远处观看的村民们立刻露出不安的表情并开始窃窃私语。

几分钟后，东侧的人墙分开，一名男性从深处踩著坚定的步伐走了过来。女孩马上就了解，这名将上唇灰色胡须整理得相当整齐的壮年男性，就是卢利特村村长以及爱丽丝以前的父亲卡斯弗特‧滋贝鲁库。

卡斯弗特在稍远处站定后，就以完全没有变化的表情依序凝视著爱丽丝与桐人。

经过十秒钟左右，才发出低沉但十分清晰的声音。

──是爱丽丝吗？

面对这个问题，爱丽丝只回答了一声「是的」。但村长没有走过来也没有对她伸出手，反而用更加严厉的声音继续询问。

──你为什么会在这里？你的罪过已经被赦免了吗？

这次爱丽丝就没办法立刻回答了。因为连她自己也不知道犯了什么罪，以及罪过究竟被赦免了没有。

桐人曾经说过，年幼的爱丽丝‧滋贝鲁库被整合骑士迪索尔巴德带到央都去的主要理由是「入侵黑暗领域」。那确实是违反禁忌目录的行为。但是禁忌已经无法束缚成为整合骑士的爱丽丝。因为对骑士来说，只有最高司祭的命令才是唯一的法律。但是最高司祭已经不在人世了。接下来他们得自己决定罪过、饶恕以及善与恶等概念……

爱丽丝一边这么想，一边笔直地回望村长的眼睛并且回答。

──犯了罪后，我受到的刑罚是失去了在这座村子里生活时的所有记忆。我不知道这样罪过算不算被饶恕了。但是现在的我，除了这座村子外就没有可以去的地方了。

这是爱丽丝没有丝毫虚假的真心话。

卡斯弗特闭上眼睛，嘴角与眉间出现深邃的皱纹。但过了一会儿就抬起头来的村长，随著锐利眼神宣告的，是极为冷彻严厉的发言。

──离开吧。这座村子容不下罪人。

可能是感觉到一瞬间横切过爱丽丝身体的僵硬感吧，赛鲁卡抬起脸，稍微歪著头说：

「姊姊……？」

面对以贴心的态度如此呢喃著的妹妹，爱丽丝边露出微笑边回答：

「没事啦。那我们差不多该回去了。」

「……嗯。」

点点头后松开手臂的赛鲁卡，稍微仰头看了爱丽丝一阵子，但马上又重新露出开朗的笑容。

「我帮忙推到岔路为止！」

刚做出这样的宣言，她就站到桐人的轮椅后面，以小小的双手握住把手。除了椅子本身就相当重之外，就算桐人再怎么瘦也还是一个人的重量，而且还要再加上一把半的神器级武器的重量。这对于只有十四岁，而且不做粗重工作的修女见习生来说实在太重了──她一开始挑战时爱丽丝虽然这么想，但是赛鲁卡整个人往前倾并且用力踩著地面后，轮椅就慢慢动起来了。

「现在是下坡，要当心一点喔。」

虽然赛鲁卡到目前为止都没有弄倒过轮椅，但爱丽丝还是用有些担心的声音这么对她说道，结果被她回了一句「没问题啦，姊姊怎么还是那么爱担心」。听说在卢利特村生活时的爱丽丝，自己虽然时常和尤吉欧一起去探险还是做实验，但却是个对妹妹有点保护过度的姊姊。

不知道是即使失去记忆基本的性格还是没变，或者只是单纯的偶然。爱丽丝走在以认真表情推著轮椅的赛鲁卡旁边这么想著。

来到山丘底部，平缓的下坡就变成了平坦的道路。这时赛鲁卡还是拚命推著重量增加的轮椅。当爱丽丝凝视著妹妹的侧脸时，思绪再次回到了过去。

被拒绝回到村子的那一天，沮丧的爱丽丝低著头离开了卢利特村，结果就是站在树荫底下的赛鲁卡叫住了她。如果没有赛鲁卡明知这是违反村长父亲旨意的行动，却还是如此做的勇气，以及她所介绍的卡利塔老人所发出的善意，爱丽丝现在应该还是像无根的浮萍一样到处飘零吧。

这对赛鲁卡来说，也绝对不是容易接受的事情。

好不容易回到故乡的姊姊，竟然忘记过去所有的事情。

两年前，虽然只有短短几天但是有了深刻交流的桐人陷入昏睡。

而等同于哥哥的尤吉欧死亡──

但赛鲁卡只有得知尤吉欧再也回不来的时候流过眼泪，之后在爱丽丝面前就一直保持著笑容。这让爱丽丝每天都因为赛鲁卡坚强的心灵与深切的关怀感到惊叹。她觉得这是比修道士的神圣术与骑士的剑还要强大且尊贵的力量。

在这同时，她也每天都体认到离开公理教会的自己是多么无力。

在卡利塔老人帮助下，选择在离村子两基洛尔的森林深处盖了一间虽然小但是十分坚固的小屋后，爱丽丝首先进行的工作是对持续昏睡的桐人施予大规模的治愈术。

她选择了广大森林中拥有最丰富提拉利亚恩宠的地点，以及天空中没有一片云可以遮住索鲁斯光线的日子，将地神与阳神赋予的庞大空间神圣力凝缩到十个光素里，然后把它们变为治愈之力灌进桐人体内。

爱丽丝全心全意进行的治愈术，规模大到别说是一个人了，甚至连飞龙庞大的天命都能瞬间恢复到最大值。她确信不论桐人身上有多严重的伤势，包含被砍断的右臂在内都会立刻回复，然后像什么事都没发生过一样醒过来。

但是──

炫目的灵光消失后，桐人确实是睁开了眼睛，但漆黑的双眸里没有意识的光芒。爱丽丝反覆呼唤著他的名字、摇动他的肩膀，最后还紧抓著他的胸口大叫，但他都只是以空虚的目光往上看著天空。爱丽丝甚至连他的右臂都无法治愈。

从那一天之后已经过了四个月，还是完全看不到任何桐人恢复意识的征兆。

赛鲁卡经常对爱丽丝说，姊姊这么尽心尽力地照顾桐人，他总有一天会复原的。但爱丽丝内心有些惶恐地想著，自己只是被最高司祭亚多米尼史特蕾达创造出来的存在……

说不定根本办不到这种事情。

由于默默推著轮椅的赛鲁卡说著「稍微……休息一下」并停下脚步，爱丽丝也因此而再次从沉思当中醒了过来。

看见额头冒出汗水而且气喘吁吁的妹妹，爱丽丝随即用左手温柔地摸著她的背部。

「谢谢你，赛鲁卡。接著换我来推吧。」

「原本想努力推到岔路的……」

「已经比之前多推了一百梅尔了。真的帮了我很大的忙。」

来到村子之后，学到了如果是年纪大很多的姊姊，这时似乎会给妹妹一些零用钱，很可惜的是口袋里连一枚铜币都没有。以目前的财政状况，就算只掉一席亚在森林里都会很辛苦，所以除了去购物之外，爱丽丝都不会把钱放在身上。

这时她以抚摸赛鲁卡亮茶色头发来代替奖励。呼吸平静下来的妹妹高兴地笑了起来，但是当爱丽丝注意到她的表情里带著一丝阴影时，就歪著头问道：

「怎么了，赛鲁卡？有什么困扰吗？」

一边握著轮椅的把手一边这么问完后，赛鲁卡犹豫了一会儿才开口说：

「……那个……巴尔波萨叔叔又想拜托姊姊帮忙处理开垦地的树木了……」

「什么嘛，原来是这种事吗？你不必为了这种事烦恼，谢谢你通知我。」

爱丽丝虽然带著微笑做出这样的回应，但妹妹却忽然从沮丧的表情转变成不满地噘起嘴。

「因为……那些人实在是太任性了。桐人你也这么认为吧？」

她对著坐在轮椅上的桐人这么问道，但低头的年轻人当然没有回答。但赛鲁卡就像得到他的同意般，加强语气继续表示：

「巴尔波萨先生和利达克先生都不让姊姊住在村子里，但是遇到困难的时候都想找姊姊帮忙。虽然把话带到了，怛姊姊可以拒绝没关系喔。食物我会从家里带来给你。」

赛鲁卡的话让爱丽丝忍不住笑了起来，然后才安抚鼓起脸颊的妹妹。

「赛鲁卡的心意我很高兴，但真的不用在意。我很喜欢现在的家，而且光是能让我住在村子附近就很值得感谢了。喂桐人吃完午饭……我马上就过去，地点在哪里？」

「……说是在南方的开垦地。」

小声回答完后，赛鲁卡就默默在轮椅旁边走了一阵子。

来到圆木小屋附近的岔路时，她才用坚定的声音说：

「姊姊，我明年研修期间结束后，就可以拿到一些薪水了。到时候你就不用帮忙那些人。姊姊和桐人……就由我……由我永远……」

赛鲁卡说到这里就无以为继，爱丽丝则轻轻把她的身体抱过来。

将脸颊靠在颜色虽然不同，但触感十分相似的茶色头发上，然后呢喃著：

「谢谢你……但只要你在我身边，我就觉得很幸福了，赛鲁卡……」

目送依依不舍地一边不停挥手一边离开的赛鲁卡，和桐人一起回到圆木小屋的爱丽丝迅速准备起午餐。

虽说最近好不容易已经可以做些家事，但做菜的技术还是上不了台面。跟金木樨之剑比起来，在村子里杂货店买来的菜刀就像玩具般脆弱，光是战战兢兢地切个食材都得花上二三十分钟。

幸好今天赛鲁卡送来了刚烤好的派，所以就把它切成一小口来喂桐人。用叉子把派靠近他嘴边，耐著性子等待一阵子后，他就会稍微张开嘴巴，届时再把派放进他嘴里。这时桐人就会像重现过去吃东西时的记忆一样，慢慢、慢慢地开始咀嚼。

在桐人咀嚼的期间，自己也慎重地品尝加了苹果与起司的派。这应该是由村长的老婆莎蒂娜‧滋贝鲁库所做。她就是赛鲁卡以及爱丽丝的母亲。

在中央圣堂生活时，人界各地的山珍海味都排满在大食堂桌子上任他们随意享用。跟那些食物比起来，莎蒂娜亲手做的派在味道与外观上都比较朴素，但是却觉得好吃了好几倍。虽然桐人的反应比爱丽丝亲手做的料理还要好让人有点生气就是了。

用完餐，收拾好餐具后，再次让桐人坐到轮椅上，并且把两把剑放到他的大腿上。

一离开小屋，就看见午后的日照让前面的庭院发出金色光芒。最近的白天已经变得相当短，拖拖拉拉的话天色马上就会暗下来。爱丽丝急忙移动到南边的岔路后，这次则是往西方前进。

走了一阵子来到森林尽头，眼前变成一大片等待收割的麦田。随风摇曳的沉甸甸麦穗后方，可以看见往上隆起的卢利特村。在并列的红色炼瓦建筑物正中央有一处高高突起的尖塔，那里就是赛鲁卡生活的教会。

赛鲁卡与管理教会的阿萨莉亚修女，都不知道统治人界四帝国公理教会组织的中央圣堂，现在已经是没有主人的空中楼阁。但同时也是孤儿院的小教会，目前依然顺利地营运著。

最高司祭的死没让中央圣堂陷入巨大的混乱，也没有对人们的生活产生影响。禁忌目录依然发挥著效用，持续束缚著人们的意识。这些人真的可以拿起剑来，为了守护人界而战吗？

只要用公理教会与帝国皇帝的名义下命令，他们就应该会遵从吧。但光是这样，还是无法在跟黑暗军队的战斗中获胜。至少骑士长贝尔库利已经理解到这个难以撼动的事实。

最后决定战局最大的因素，并不是武器的优先度，也不是术式的行使权限而是意志力。桐人颠覆绝望的战力差距，打倒数名整合骑士以及元老长裘迪鲁金，甚至消灭最高司祭亚多米尼史特蕾达的战斗表现就是最好的证明。

爱丽丝一边挺起胸膛，承受站在麦田中工作的村民们投射过来交杂著警戒与不安的视线，一边在心中对著自己的剑术师父呢喃著。

──叔叔，对生活在人界的人民来说，和平可能不是自己守护，而是永远被赐与的东西。

──而让他们变成这样的，一定就是……公理教会、禁忌目录以及我们整合骑士团。

骑士长贝尔库利在这个时候，一定也在央都圣托利亚为了四帝国军的训练与装备的制造而四处奔走吧。说不定已经把军队移动到应该是最大战场的伊斯塔巴利耶斯帝国边境，也就是「东大门」。不论是实务上的辅佐，还是开战后的战力，目前都是有越多骑士帮忙越好的状态。

──但现在的我……

陷入沉思的爱丽丝穿过麦田，来到村子南边的一大片开垦地。在被挖起的黑土前停下轮椅，开始眺望广大的土地。

据说短短两年前，前方还是规模比爱丽丝他们居住的东方森林还要大的一片茂盛树海。

但是做为森林主人的那棵高耸入云，并且像无底洞般不停吸取神圣力的「恶魔之树」基家斯西达已经被桐人与尤吉欧砍倒，所以现在村里的男人们都拚了命地开垦农田，赛鲁卡之前就以傻眼的表情这么对爱丽丝说明过了。

开垦地中央残留著巨大的漆黑树墩，南端则有十几名村民奋力挥动著斧头。其中的一个角落，可以看见一个挺著大肚子的男人，自己手里没有斧头，但是啰嗦地做出各种指示，他就是村子里最大农场的主人纳伊古鲁‧巴尔波萨。

虽然有点不愿意，但爱丽丝还是把轮椅推进被踩得相当踏实的小径。即使经过自己过去曾经砍倒的大树所留下的树墩旁边，桐人也没有任何反应，依然低头抱著两把剑。

首先注意到两个人往这里靠近的，是坐在刚砍倒的树干上休息的巴尔波萨一族的年轻人们。大概是十五六岁的三个人，毫无顾忌地眺望著在金发上绑了头巾的爱丽丝，然后把视线移到坐著轮椅的桐人身上。小声地互相说了些什么后，就发出低沉的笑声。

无视这几个人直接通过他们面前后，其中一个年轻人以懒散的声音大叫：

「叔叔～来了喔～」

结果双手扠腰，不停大呼小叫的纳伊古鲁‧巴尔波萨就迅速回过头，肥滋滋的圆脸上也露出笑容。他大大的嘴巴与细长的眼睛，让人稍微想起元老长裘迪鲁金。

但是爱丽丝尽量挤出笑容，并且轻轻点了点头。

「午安，巴尔波萨先生。我听说您有事找我……」

「喔喔、喔喔，爱丽丝啊，你来啦。」

他晃动著圆肚子张开双臂靠了过来，原本以为他会抱住自己的爱丽丝摆出警戒姿势，幸好他看见爱丽丝身前的轮椅后似乎就打消了念头。

纳伊古鲁改为站到右侧边五十限的地方，然后转动巨大身躯，用手指著耸立在森林与开垦地界线上的大树。

「看得见那棵树吧。我们从昨天早上就开始砍那棵该死的白金橡了，但是就算十个大男人挥动斧头还是只有这么一点进展。」

他以右手的食指和姆指比出一个小小的半圆。

树干半径应该有一梅尔半的白褐色巨树，根部牢牢地抓住地面，顽强地抵抗著开垦者们。目前也有两名大汉正交互挥动巨大的斧头，但砍进树干的深度大概还不到浅浅的十限。

脱掉上衣的男人们上半身已经是挥汗如雨。胸口与手臂的肌肉算是浑厚，但平常应该很少握斧头吧，可以看出动作有点僵硬。

在爱丽丝的注视下，其中一名大汉的右脚打滑，斜斜地砍中了其他地方。斧头的柄从中折断，整个人跌坐到地上的男人，随即遭到周围的伙伴毫无顾忌的讪笑。

「真是的，这个大笨蛋，到底在做什么啊……」

巴尔波萨低声咒骂，然后再次看著爱丽丝说：

「照这个样子，光要砍倒这棵树就不知道得花几天了。我们在这里浪费时间的时候，利达克他们那群家伙已经拓展了二十梅尔的正方形土地了！」

一提到规模仅次于巴尔波萨家的富农，纳伊古鲁就踢开脚边的小石子。他原本急促地喷著鼻息，但忽然间就露出满脸笑容，并且以温柔的声音说：

「事情就是这样，虽然约定好一个月一次，但这次可不可以破例帮个忙呢，爱丽丝？虽然你可能不记得了，但我在你小时候，经常会赏你糖吃……不对，应该说给你糖吃。以前的你真的是个很可爱的女孩子，当然现在也是很……」

压抑住叹息声后，爱丽丝打断了纳伊古鲁的话。

「我知道了，巴尔波萨先生。如果只有这一次的话。」

像眼前的白金橡一般，排除阻碍开垦的树木或者岩石，就是爱丽丝目前的天职──不对，应该说暂时的糊口方式。

当然，这不是正式的工作。在村子外围的生活稳定下来后又过了一个多月左右，发生一块大石头落下来，塞住通往西边放牧地道路的事件。刚好经过的爱丽丝独自把它从路上移开的事情在村子里传开，不知不觉间就开始接受这样的委托了。

实际上，既然要和桐人一起过生活，就多少需要一些现金，所以能够有工作当然相当感谢。但是赛鲁卡担心只要有人提出要求就帮忙出力的话，村子里的男人们可能会永无止尽地来找爱丽丝帮忙，所以决定每一间农家每个月只能委托一件工作。

应该被禁忌目录、诺兰卡鲁斯北帝国基本法、村民规范等所有规则束缚住的纳伊古鲁，即使知道规定也还是进行了第二次委托，但爱丽丝却不觉得惊讶。他当然并不是像爱丽丝或者尤吉欧那样突破了「右眼的封印」──根据最高司祭的说法是「Code 871」──只不过是认为爱丽丝的身份比自己低下罢了。与在村外破烂小屋里生活的前罪人之间的约定，根本不需要傻傻地遵守。

心里面虽然想著这些事，但爱丽丝还是再次向纳伊古鲁行了注目礼，然后离开轮椅旁边。爱丽丝先确认了一下桐人的反应，看来他并不在意周围的騒动。内心对他说了句「稍等一下喔」，然后走向那棵巨大的白金橡。

注意到爱丽丝走过来的男人们，有的脸上浮现轻浮的笑容，有的则明显咂著舌头。但现在已经没有人不知道爱丽丝的力量，所以他们全都默默地离开树旁边。

和他们交换位置站到大树前的爱丽丝，迅速以右手指尖划出神圣术的图样，叫出了「史提西亚之窗」。不愧是连十个大汉都束手无策的树木，天命的数值算是相当高。这种优先度的话，就不能跟之前一样使用借来的斧头了。

于是她先小跑步回到轮椅处，弯下腰对轻声桐人呢喃著：

「抱歉，桐人。希望你把剑借我用一下。」

右手一轻轻碰到黑色皮革剑鞘，就感觉抱住剑的左臂稍微变得僵硬。

但耐著性子凝视空虚的眼睛后，手臂终于放松力道，并且有沙哑的声音从喉咙发出：

「……啊……」

与其说是了解爱丽丝的意思，应该更接近是记忆的残留现象吧。那不是思考，只是留在桐人心中的回忆躯动著现在的他。

「谢谢。」

爱丽丝低声道完谢，从他手臂里拿起黑剑。确定桐人不会躁动后，再次回到白金橡旁边。这确实是一棵相当雄伟的树。虽然比不上耸立在央都圣托利亚各处的古老大树，但树龄应该也超过百年了吧。

在心里对树说了声对不起，接著爱丽丝站稳双脚。

然后右脚在前，左脚在后。左手将「夜空之剑」举到腰部的高度‧右手则轻轻贴在卷著黑色皮革的剑柄上。接著以左眼测量和树之间的距离。

「喂喂，想用那么细的剑砍倒白金橡吗？」

一个男人刚这么大叫，周围的人就开始跟著起哄。在「剑会折断啦～」「树没砍断天都要黑了」等等嘲笑声中，也参杂了纳伊古鲁‧巴尔波萨似乎相当担心的声音。

「啊～爱丽丝啊，可以的话希望在一个小时左右把事情解决。」

开始这份工作后已经砍倒了十棵以上的树，每一次大概都要花三十分钟左右。之所以如此耗时，是因为爱丽丝为了不弄坏借来的斧头而必须压抑力量。但今天就不用担心了。夜空之剑是优先度足以媲美金木樨之剑的神器。

「不用花那么多时间。」

呢喃般回答完后，爱丽丝就握住剑柄。

「……喝！」

随著简短的喊叫声，往下踩的右脚下方，像是爆炸一样卷起一阵土尘。

虽然很久没有挥动真正的剑，幸好还没有忘记剑技。从剑鞘里抽剑使出的左水平斩，化作黑色闪电横越天空。

周围的男人们似乎都看不见这一道斩击。即使爱丽丝已经从剑完全挥向右前方的姿势中站直身躯，他们也只是疑惑地皱著眉头。

白金橡光滑的树皮上，只有男人们砍出的些许切痕，除此之外就没有任何痕迹──看起来似乎是这样。

最后某个人说了「搞什么，没砍中啊～？」，接著就有好几个人发出笑声。爱丽丝瞄了声音的主人一眼，一边把剑收回剑鞘里一边说：

「要朝你那边倒了。」

「啥？你在说什……」

说到这里，男人就因为惊愕而瞪大了双眼。因为他看到白金橡的树干开始慢慢倾倒。周围的人全都发出「呜哇啊啊啊」的悲鸣然后朝后方逃走。

巨树随著强烈的地鸣声倒在三秒前男人所站的地方。

爱丽丝一边以右手挥开漫天尘沙，一边移动到树墩前面。全新的切断面上清晰地浮现出年轮，而且就像被仔细擦拭过般闪闪发亮，但是角落有一个地方稍微裂开了。

是剑技生疏了，还是因为失去右眼的缘故──爱丽丝边这么想边改变身体的方向。

下一刻，马上就忍不住将上半身往后仰。因为纳伊古鲁‧巴尔波萨张开双臂，发出巨大的声音跑了过来。

反射性抬起左手上的剑后，听见剑锷发出轻脆声响的纳伊古鲁立刻紧急煞车。但他脸上还是带著笑容，将张开的双手在身前互握并且大叫：

「太……太……太厉害了！竟然有如此高超的技术！侍卫长吉克根本跟你不能比！简直就是神技啊！」

又往前靠近了一梅尔左右的距离后，他就用同时带著感叹与欲望的表情继续说：

「怎……怎……怎么样啊，爱丽丝，我给你双倍的礼金，不要一个月一次，干脆一周一次……不对，每天帮助我一次吧！」

爱丽丝则是对高速搓著双手的纳伊古鲁轻轻摇了摇头。

「不用了，现在收到的金额已经够我们生活了。」

如果把金木樨之剑带过来并且使用武装完全支配术，那别说一天砍一棵大树了，甚至可能在短短几分钟内把这片森林变成一望无际的裸地。但是这么做的话，他们的要求将变为荒野翻土、粉碎岩石甚至是让老天爷下雨。

一面发出「嗯唔唔唔唔唔」的沉吟一边扭动身体的纳伊古鲁，在爱丽丝「请付费用」的声音提醒下才像回过神来般眨了眨眼睛。

「嗯……嗯，对喔，对喔。」

他把手伸进怀里，从看起来沉甸甸的皮革袋子里，抓出一枚约定好的一百席亚银币。

巴尔波萨把它放到爱丽丝手掌上，不甘心地继续表示：

「爱丽丝啊，那你看这样如何。我现在再付你一枚金币，你这个月拒绝利达克那个家伙的委托……」

爱丽丝把叹息声吞下去，准备再次拒绝对方时──

耳朵听见了「喀砰」的沉重声音。瞬时抬起脸来，就看见远处的轮椅已经翻倒，桐人的身体整个摔到地上。

「……桐人！」

爱丽丝以沙哑的声音大叫，跑著经过纳伊古鲁身边。

趴到地面的桐人，以拚命的动作伸直了左臂。他的前方可以看见原本在休息的年轻人当中，有两个人一起把收在白色皮革剑鞘里的长剑竖立在地上，然后以兴奋的口气大叫：

「呜喔，这把剑也太重了吧！」

「所以那个瘦弱的女孩才能一剑把白金橡砍倒吧。」

「别说那么多了，好好撑住！」

第三名少年大叫著，然后为了拔出蓝蔷薇之剑而用双手握住剑柄。

爱丽丝听见自己咬紧的牙根发出了「叽」一声。接著就从喉咙里迸出锐利的叫声：

「你们这些家伙……！」

听见她声音的少年们，只能茫然张大嘴巴看著爱丽丝。

她瞬间跑过剩下来的二十梅尔距离，在带著烟尘的情况下停止脚步。看见爱丽丝表情的三个人，开始慢慢往后退。

爱丽丝用力吸了一口气，尽力将快要爆发的感情压抑下来，首先帮忙趴倒在地上的桐人站起身子。重新让他在轮椅上坐好后，就压低声音命令道：

「那把剑是这个人的东西。快点还给他。」

下一刻，三个人脸上就浮现反抗的表情。准备拔出蓝蔷薇之剑的魁梧年轻人，歪著嘴唇用手指著桐人说：

「我们跟他说把剑借给我们了。」

坐回轮椅上的桐人依然将左臂朝著白剑伸去，然后发出细微的声音。

按住剑鞘的其中一名年轻人，像要嘲弄他般歪著嘴唇继续说：

「然后那个家伙就很豪爽地借给我们了。他当时是发出『啊～啊～』的声音。」

剩下来的一个人也配合他笑著说「对啊对啊」。

爱丽丝这时只能用力以右手握住轮椅的把手。因为这只手已经快要拔出握在左手上的夜空之剑了。

如果是半年前的自己，一定会毫不犹豫地把碰到蓝蔷薇之剑的六只手全部砍飞。整合骑士不受禁止伤害他人的禁忌目录束缚。更何况，突破右眼封印的现在，已经没有任何法律可以规范爱丽丝的行动了。

但是──

爱丽丝将牙根咬到发疼的地步，拚命与自己的冲动战斗著。

这些年轻人是桐人与尤吉欧不惜牺牲生命也要守护的人界人民。自己没办法伤害他们。而且他们两个人也不希望自己这么做。

爱丽丝就这样一动也不动地沉默了几秒钟的时间。但她恐怕还是无法掩饰左眼散发出来的杀气。三个年轻人脸上的笑容消失，像是很害怕般把视线移到旁边。

「……知道了啦，干嘛露出那么恐怖的表情。」

最后魁梧的年轻人心不甘情不愿地丢出这么一句话，然后手放开剑柄。剩下来的两个人恐怕也是再也撑不住了，只见他们以有点松了口气的表情放开剑鞘。蓝蔷薇之剑当场重重掉到地上。

爱丽丝默默走了过去，弯下腰部，故意只用右手三根手指轻松地把白色皮革剑鞘抬了起来。转过头的瞬间，狠狠瞪了几个臭小鬼一眼，然后才回到轮椅旁边。

用外套的衣襬擦了擦沾在剑鞘上的尘埃，再次把黑白两把剑一起放到桐人的大腿上后，他就紧紧抱住它们并且停止所有动作。

爱丽丝这时瞄了纳伊古鲁‧巴尔波萨一眼，结果他像是对骚动完全没有兴趣一样，早就专心指挥著男人们。微微向他不停呼喊的背部行了个礼，爱丽丝就推著轮椅从小径上朝著北方往回走。

许久没有出现在胸口的炽烈暴怒感，不知道什么时候已经被冰冷的无力感取代。

自从在卢利特村附近的森林里生活之后，已经不是第一次有这样的感觉了。村民们甚至不愿意跟爱丽丝说太多话，而且也不把失去意志的桐人当成一个人。

但是也没办法责怪他们。因为在他们心里，爱丽丝依然是违反了禁忌目录的罪人。光是默默让她住在村子附近，并且愿意卖给她食材与日用品，就已经很值得感谢了。

但内心的角落同时也忍不住浮现──到底是为了什么的想法。

到底是为什么，要承受那么大的痛苦和最高司祭亚多米尼史特蕾达战斗呢？另一名最高司祭卡迪娜尔、有意识的黑蜘蛛夏洛特以及尤吉欧丧失生命，桐人失去语言能力与感情，付出这么大的代价后究竟守护了什么？

这样的思考，最终只是得到一个绝对不能说出口的问题。

就是守护像巴尔波萨家的人们真的有意义吗？

这样的迷惑，就是让爱丽丝舍弃长剑隐居在边境之地的理由之一。

在这里过生活的现在，位于伊斯塔巴利耶斯帝国尽头的「东大门」后面，暗之国的军队也正一步步逼近。依照目前的情势来看，骑士长贝尔库利致力发展的新生「人界守备军」究竟来不来得及到现场设防都不一定了。身为整合骑士的自己仍未被解任──能够办得到的也只有死亡的最高司祭而已──爱丽丝或许应该尽快赶到东大门去才对。

但是金木樨之剑对爱丽丝来说已经过于沉重了。

原本深信是自己故乡的神界根本不存在，宣誓效忠的公理教会是建立于众多谎言之上，尤其是现在又知道太多人界的人民丑陋与卑鄙的一面。在对自己的正确性深信不疑的情况下挥剑，而且能向神明祈祷的日子已经是遥远的过去。

目前爱丽丝真心想守护的人可以说寥寥无几。父母亲、赛鲁卡、卡利塔老人以及桐人。只要能保护这几个人，就算背弃骑士的任务，一直在此地过著平稳的生活又有什么关系──离开开垦地，进入穿越麦田的道路后爱丽丝就停下脚步，对著桐人呢喃：

「可以顺便去村子里买点东西吗？我不会再让那种无礼的小鬼对你恶作剧了。」

虽然没有回答，但认为没有反应就是答应了的爱丽丝，随即推著轮椅往北方前进。

用赚来的一百席亚银币买了一个礼拜份的食材与生活必需品，准备回到森林小屋去时，天空已经完全染上晚霞的颜色。

当爱丽丝准备登上小屋的门廊，就注意到有低沉的风声靠近。于是连同轮椅稍微往后退，来到草地中央附近等待著声音来源。

最后从快要擦过树梢的低空出现在她眼前的，是有著巨大双翼以及长脖子与尾巴的大型兽类──也就是飞龙。它是把爱丽丝与桐人从央都运送到这里来的坐骑。名字叫作雨缘。

飞龙在草地上空回旋两圈后，轻轻地降到地上。它收起翅膀，先伸长脖子用鼻尖碰了一下桐人的胸口，然后用大大的头部摩擦著爱丽丝。

爱丽丝搔了搔它脖子下方微微带著蓝色的软毛，龙就用喉咙发出低沉的咕噜噜声。

「雨缘，你有点变胖了。不要吃太多湖里的鱼喔。」

带著微笑这么斥责它后，龙像是有点不好意思般呼一声从鼻子喷出鼻息，接著转动长长的身躯走回小屋东侧的床铺去。在铺著厚厚一层干草的床铺上，把尾巴绕到脖子上面，整个身体缩成一团。

半年前，决定在这块草地上建造小屋当天，爱丽丝就把挂在雨缘头上的皮革马辔拆下来，并且解除拘束术式。甚至对它说，你已经自由了，回位于西帝国的飞龙之巢去吧，但飞龙还是没有离开爱丽丝的迹象。

它自己收集干草制作了床铺，白天似乎就在森林里嬉戏，或者在湖里捕鱼，不过傍晚一定会回到这里来。明明压抑住飞龙高傲刚猛性格，让它遵从骑士命令的神圣术已经不存在了，爱丽丝无法理解它为什么不回故乡。

但是成为整合骑士后就一直跟自己在一起的雨缘，按照它自身的意志持续待在自己身边还是让人感到很高兴，所以也没有故意把它赶走。村民时常目击它在森林上空飞翔的模样，结果也成为爱丽丝风评不佳的原因之一，但事到如今在意这种小事也于事无补了。

对开始在干草上发出低沉鼻息的雨缘说了声晚安，爱丽丝就推著轮椅进入小屋里。

晚餐煮了炖半月豆与肉丸子。虽然豆子有点硬，丸子的大小有点不一，但感觉味道已经颇像一回事了。当然，桐人不可能跟自己说他的感想。用小汤匙把食物放进他嘴里，就会像想起来一样咀嚼并且吞咽。

心里虽然想著如果可以知道他喜欢和讨厌的食物就好了，但回想起来就会发现，自己和这个年轻人好好对话的时间根本短到连一天都不到。赛鲁卡两年前好像在教会里和他一起生活了一段时间，不过赛鲁卡说只记得他不论什么吃料理都会露出相当美味的表情。而爱丽丝也觉得那的确很符合桐人的个性。

花了一些时间终于让桐人吃完炖菜，接著就把他连人带椅子一起移到小型暖炉旁边，当爱丽丝自己到流理台洗碗盘并且把它们排在篮子里时──

平常都会静静睡到快天亮的雨缘，忽然在窗外发出噜噜噜的低鸣。

吃了一惊的爱丽丝停下手，竖起耳朵专心听著。穿越森林的夜风当中，可以听见混杂著不符季节的初冬冷风般的声响。那是又薄又大的翅膀在风中穿越时所发出的声音。

「…………！」

爱丽丝冲出厨房，确认桐人乖乖坐在椅子上后，就打开玄关的门。接著再次竖耳倾听，判断穿越风的声音越来越靠近后，就来到前面的庭院仰头看著夜空。

在满天星空作为背景下，呈螺旋状往下降的黑影无疑是一只飞龙。为了慎重起见看向草地的东边，马上就发现雨缘果然也趴在床铺上看著天空。

「不会吧……」

想到可能是黑暗领域的暗黑骑士越过尽头山脉，正想回去拿剑的时候，就看到龙的鳞甲在月光照射下发出银色光芒。这也让爱丽丝稍微放松肩膀的力量。虽然世界是如此辽阔，但能操控银鳞飞龙的，就只有公理教会的整合骑士而已。

但现在放心还太早了。到底是谁，又是为了什么专程飞到这样的边境来？难道要处刑桐人这个反叛者的论调过了半年还没平静，中央圣堂终于派人来追捕了吗？

可能是感觉到爱丽丝的紧张了吧，雨缘也从床铺里爬出来，昂起脖子再次发出低吼。但威吓的低沉吼叫立刻消失，变成让人胸口一揪的撒娇般咕噜声。

爱丽丝马上就明白它发出道种声音的理由。

继续回旋了三圈后，在草地南端著地的飞龙，脖子附近长著颜色和雨缘极为类似的软毛。那无疑是雨缘的哥哥，也就是名为泷刳的飞龙。这么说来，坐在它背上的就是──

爱丽丝随即用僵硬的声音，对著以轻盈动作降到地面，身穿白银铠甲与头盔的骑士搭话：

「……你竟然知道我在这里。找我有什么事吗，艾尔多利耶‧辛赛西斯‧萨提汪？」

排名比身为第三十位骑士的爱丽丝还要后面的唯一一名整合骑士没有立刻出声，先把右手靠在胸口深深行了一个礼。

然后挺直身子，缓缓摘下头盔。带有光泽的淡紫色头发轻轻在夜空中飘动，让他带有都会气息的华丽美貌露了出来。对方随即用以男性来说算高亢且圆滑的声音──

「久违了，吾师爱丽丝大人。虽然装扮不同，但您依然是那么地美丽。在今夜如此完美的夜色下，想到师父的黄金秀发一定会发出亮丽的光辉，我便感到兴奋难眠，于是带著秘藏的名酒来访。」

藏在背后的手迅速伸到前面，结果手上果然握著一支红酒瓶。

爱丽丝把叹息声吞下肚，回答这名不知道为什么会变成自己徒弟的男子。

「……伤势完全痊愈了是很好，但你的个性还是一点都没变。我现在才注意到，你说话的口气有点像那个元老长裘迪鲁金喔。」

她背对发出「呜咕」这种奇妙声音的艾尔多利耶，直接朝小屋走去。

「那……那个……爱丽丝大人……」

「有重要的事情就到里面说。没有的话就自己一个人把酒喝完，然后回央都去吧。」

隔了半年后再次相遇的泷刳和雨缘兄妹正高兴地互相摩擦脖子，爱丽丝抬头瞄了它们一眼，快步走回小屋里。

乖乖跟了过去的艾尔多利耶，以好奇的眼光环视狭窄的小屋，然后把视线停留在旁边低著头的桐人身上。但他对过去曾交过手的背叛者没有什么评论，只是快步走到桌子深处，替爱丽丝把椅子拉出来。

「…………」

觉得连道谢都很愚蠢的爱丽丝以叹息声来取代，然后重重坐到椅子上。艾尔多利耶自行坐到她对面，把红酒瓶放到桌上。面面相觑的瞬间，他的脸色之所以微微一沉，应该是看见依然绑在爱丽丝右眼上那条黑色绷带的缘故吧。但表情立刻恢复原状的艾尔多利耶，抬起脸后就轻轻动著鼻翼。

「……爱丽丝大人，怎么有好香的味道。话说回来，我因为急著上路，到现在都还没吃晚餐呢。」

「还说什么话说回来。应该说，从央都飞到这样的边境，带了酒却没带干粮的你到底是在想什么？」

「我已经向三神发誓一辈子不吃那种又干又粉的东西了。要用那种东西填饱肚子的话，干脆任由饥饿耗光天命算了……」

不把艾尔多利耶无谓的回答听到最后，爱丽丝就从椅子上站了起来。移动到厨房后，从放在灶上的铁锅里盛起剩下来的炖豆子与肉丸放到木盘上，然后回到桌子前。

艾尔多利耶以混杂著欢喜与怀疑的表情，凝视著放在眼前的木盘。

「…………冒味地请问，这不会是爱丽丝大人亲手做的吧……？」

「是啊。那又怎么样？」

「…………没有。想不到有一天能尝到吾师亲手做的料理，这比您传授我秘剑剑招时还要让人高兴。」

他以紧张的表情握住汤匙，然后把豆子放进嘴里。

爱丽丝再次对咀嚼食物的艾尔多利耶质问道：

「那么你到底是怎么找到这个地方的？这里和央都之间的距离，不论什么样的术式都无法到达……而且现在的骑士团也没有为了寻找我一个人就派出飞龙四处侦查的余力吧。」

艾尔多利耶没有立刻回答，只是低声说了句「想不到颇为美味」，并且拚命动著汤匙，最后从吃得精光的盘子上抬起头来，用不知道从哪里拿出来的手巾擦拭完嘴巴后，才笔直地看著爱丽丝。

「是顺著我和爱丽丝大人之间灵魂的羁绊而来……虽然很想这么说，但很可惜的，找到这里单纯只是偶然。」

他用演戏般的动作大大张开右手。

「从巡逻尽头山脉的骑士那里，传来了最近北方这边有许多哥布林与半兽人在偷偷蠢动的报告。虽然已经按照骑士长的指示把北、南、西的洞窟全部弄塌了，但它们可能学不会教训又想把洞挖开，所以我才来这里确认。」

「……挖开洞窟……？」

爱丽丝皱起眉头。

贯穿尽头山脉的四条道路里，南、西以及距离卢利特村颇近的北方洞窟都相当狭窄，做为黑暗军队主力的食人鬼与巨人无法从那里通过。因此预测敌军会在「东大门」外面集结，但骑士长贝尔库利为了慎重起见，在得到指挥权后就让这三个地方的洞窟崩塌了。

就是知道这件事爱丽丝才会到此隐居，但敌人要是重新把洞窟挖开的话，状况就又不一样了。卢利特村将瞬间从和平的边境，转变成最先笼罩在战火当中的最前线。

「那么……你去确认过黑暗军队的动态了吗？」

「我花了一整天在洞窟周围盘旋，结果不要说半兽人了，连一只哥布林都没看见。」

艾尔多利耶轻轻耸了耸肩，继续说道：

「大概是把兽群看成军队了吧。」

「……确认过洞窟内部了吗？」

「当然。我从黑暗领域那边看过了，岩石确实一直堆到洞窟顶端。想挖开的话一定得动用大部队。确认完之后……拉了缰绳准备回到央都去时，泷刳不知道为什么有点浮躁。让它自由飞翔后，就降落到这个地方来了。老实说，我也吓了一跳。真的完全是偶然……不对，应该说是命运的引导吧。」

不知不觉中艾尔多利耶演戏般的口气已经消失，这时他又用刚直的骑士表情继续说道：

「在这个得以再次相见的时机，基于职务我必须这么说。爱丽丝大人……请您回到骑士团来吧！对我们来说，您一个人的剑更胜过千名援军！」

像是要逃开骑士强烈的视线般，爱丽丝轻轻地闭上眼睛。

这些事情爱丽丝当然都知道。

包围人界的脆弱墙壁已经发出龟裂的声音，随时可能倒塌。想支撑住墙壁的骑士长贝尔库利与新生守备军目前正陷入苦战。

对于守护、教导自己的骑士长还有尚未还的恩情，而且跟包含艾尔多利耶在内的整合骑士团伙伴们也还有一体感。但光凭这些依然无法战斗。

实力是来自于意志。爱丽丝在中央圣堂的战斗里，发现到这个真相。虽然意志力能够像那个时候的桐人一样，逆转令人绝望的战力差距，但也可以让最强的神器变成废铁──

「……办不到。」

爱丽丝以细微的声音回答。

艾尔多利耶一听见，马上发出锐利的声音：

「为什么？」

他不等爱丽丝待回答，立刻用鞭子般锐利的视线看著坐在暖炉旁边的年轻人。

「是那个男人的关系吗？打破中央圣堂的牢房，对许多骑士、元老长，以及最高司祭大人挥出反叛之剑的那个男人，到现在还幻惑著爱丽丝大人的心吗？如果是这样，就让我帮忙斩断您困惑的根源吧。」

艾尔多利耶在桌子边缘握住的手开始用力，爱丽丝则用单眼紧紧瞪著他。

「住手！」

虽然是经过压抑的音量，但光是这样一句话，就已经让骑士的身体往后仰。

「他也是为了自己相信的正义而战。如果不是这样，为什么我们这些最强的整合骑士，乃至于骑士长阁下会全部被打倒呢？直接和他交过手的你，应该亲身体验过他手上长剑的重量吧。」

高挺的鼻梁上虽然因为懊悔而出现皱纹，但艾尔多利耶还是缓缓放松肩膀的力道。他一面把视线落到桌面，一面像呢喃般说出一段独白：

「……我也很难接受亚多米尼史特蕾达大人想将半数人民变成无魂剑骨士兵的计划。而没有那个年轻人……桐人和他的朋友尤吉欧出现，应该就没有人能阻止计划实现。更何况，引导他们两个人的，是过去与亚多米尼史特蕾达大人比肩而立的另一名最高司祭卡迪娜尔大人。如果贝尔库利阁下说的话是事实，那么事到如今我也不想再追究桐人的罪过。但是……如果是这样，我就更加不能理解了！」

像是要把至今为止压抑在胸口的想法全都吐露出来一样，艾尔多利耶大叫著：

「反叛者桐人如果真像爱丽丝大人所说的那样，是凌驾我们这些整合骑士的能人，那现在为什么不拿起剑来战斗呢！为什么沦落成这种丢脸的模样，把爱丽丝大人束缚在这种边境呢！如果是为了保护人民才刺杀亚多米尼史特蕾达大人，那么现在更应该赶到东大门去才对吧！」

艾尔多利耶炽热如火的一番话，似乎也没办法传达到桐人心中。映照在他半闭双眸当中的，就只有暖炉中摇晃的炭火光芒。

这时爱丽丝平稳的声音打破了堆积在现场的沉重沉默：

「……抱歉，艾尔多利耶。我还是没办法和你一起离开。和桐人的状况无关……是我的剑已经失去了力量，就这么简单。现在和你交手的话，我恐怕撑不了三回合。」

艾尔多利耶相当惊讶般地瞪大了双眼。这名高傲的年轻骑士，脸庞就宛如稚嫩的少年皱了起来。

最后那张脸又浮现出带著谛观之意的微笑。

「……这样啊。那么，我也无话可说了……」

他缓缓伸出右手，并且呢喃著神圣术的起句。以持续的高速咏唱生成两个晶素后，就把它们变成极薄的红酒杯。

从桌上拿起红酒瓶，只用指尖就把坚固的木栓弹飞。在两个杯子里各倒了少量的鲜红液体，然后放下酒瓶。

「……早知道是离别之酒，我就把秘藏的西帝国产两百年红酒带来了。」

插图008

艾尔多利耶拿起其中一只酒杯，一口气把酒喝光，接著静静把杯子放回桌上。行了个礼后站起身子，大大地翻动纯白披风。

「那么，就此告别了，师父。本人艾尔多利耶，一生都不会忘记您教导我的剑法与神圣术要诀。」

「……保重了。我会祈求你平安无事。」

好不容易挤出这些话的爱丽丝缓缓向对方回点了一下头，接著整合骑士的靴子就踩著响亮的脚步声离开了。他的背部散发出不可动摇的傲气，让爱丽丝只能够把视线移开。

骑士开门并且将其关上。泷刳在前面的庭院发出一声尖锐的叫声，接著就是拍动翅膀的声音。雨缘舍不得与哥哥分开的鼻音，让爱丽丝的胸口为之刺痛。

强劲的翅膀声远去，最后完全消失，但爱丽丝还是无法动弹，只能一直坐在椅子上。

在晶素生成的玻璃杯天命耗尽前，爱丽丝用指尖轻轻把它拿起来靠到嘴唇上。隔了半年才又尝到的红酒，在舌头上留下的不是甜味，而是苦涩的酸味。几秒钟后，两个空杯子就撒下微光消失了。

她把木栓再次塞回仍未喝完的瓶子上，然后站了起来。移动到暖炉旁边，对一直默默坐在那里的桐人搭话道：

「……对不起，你一定累了吧。平常这个时候早已经在休息了。来，到床上去吧。」

轻轻把手放到肩膀让桐人站起来后，就带著他来到隔壁的寝室。帮忙把黑色居家服换成原色睡衣，接著让他躺到窗边的床上。

即使拿起叠在脚边的毛毯盖住脖了以下的身体，半闭著眼睛的桐人也只是毫不眨眼地往上持续看著天花板。

吹熄墙壁上的油灯，室内就充塞著淡蓝色的黑暗。爱丽丝在桐人旁边坐了下来，温柔地抚摸著他消瘦的胸口与骨胳突出的肩膀，几分钟后，他就像是某种动力忽然消失般闭上了眼睛。

等待桐人的鼻息稳定下来，爱丽丝就离开床边，换上自己的白色睡衣。接著又回到客厅，从窗户确认雨缘的状况后，就熄灭两盏油灯，走回寝室当中。

她拉起床上的毛毯，钻到桐人身边，随即有些许温暖包围她的身体。

平常总是一闭上眼睛就能逃进睡梦当中，但今天却一直没有睡意。

艾尔多利耶步行离开时，背后晃动的披风那炫目的白色还残留在眼中，像针扎般刺激著眼睛。

自己的背部过去也像他一样充满骄傲。以自己的剑守护人界以及生活在其中的人民，并且维护公理教会的权威，这种无可动摇的确信变成了活力，在身体里四处流动。

但是自己已经完全失去这样的力量了。

真的很想询问──艾尔多利耶这名过去的弟子。教会与最高司祭的虚伪被揭穿的现在，你到底相信什么，又为了什么而战？

但是她终究没能那么做。因为除了爱丽丝与贝尔库利之外的整合骑士，并不知道最高司祭那恐怖计划的全貌。就拿艾尔多利耶来说好了，他也还不知道自己的「记忆碎片」被封印在中央圣堂最上层里，同时也不清楚「最爱的人」沦落成巨剑魔像的一部分这个事实。

因此他还能继续相信公理教会这个组织。期盼著三女神派遣新的最高司祭到中央圣堂，毫无谬误地领导人民的日子到来。

但知道神与神界的存在根本是天大谎言的自己，应该怎么办才好？

虽说是出于无奈，但骑士长还是对其他骑士隐瞒了一半的实情，让他们为即将来临的大战做准备。若是自己现在加入其中，爱丽丝怀抱于胸的迷惘一定会让其他骑士感到迷惑。

谁也不知道急就章的守备军是不是能挡得住黑暗军队的总攻击。如果东大门被突破的话，渴望人血的怪物最后一定会涌入这个边境村庄吧。真的没有可以回避这出惨剧的方法了吗──当爱丽丝这么想时，脑袋里一定会重新浮现一道声音。

和最高司祭决战之后，桐人在即将倒地之前，从不可思议的水晶板里发出来的两句话。

──到世界尽头的祭坛（World End Altar）去。

──从东大门出去后一直往南。

从来没听过「World End Altar」这样的神圣语名。但是自己知道走出东大门后有什么东西。那是有一整片炭灰般黑色地面以及血色天空的黑暗领域荒野。只要踏进一步，不论是要前进还是后退都相当困难。

就算克服难以想像的困难横断暗之国，到达那个叫什么祭坛的地方好了，那里又有些什么呢？真的有谁──或者什么东西能从黑暗军队手底下守护生活在人界的人民吗……？

爱丽丝在枕头上转过头，看向躺在床铺另一边的年轻人。

然后在毛毯里爬行，移动到桐人身边。稍微犹豫了一下后就伸出手，像作恶梦而害怕的小孩子般紧紧抱在他身上。

不论怎么用力把痩到惨不忍睹的身体拉过来，过去用如火焰般激烈的个性让爱丽丝内心产生动摇的那个年轻人都没有任何反应。缓慢跳动的心脏没有加速，甚至连伏下的黑色睫毛都没有震动。活在这里的……不对，或许应该说存在这里的，只是完全燃烧殆尽的无魂空壳罢了。

现在右手如果有剑的话──

干脆就同时贯穿两颗紧靠的心脏，让一切全部结束。

这一瞬间的思考，变成了眼泪从爱丽丝眼角溢出，滴到桐人的后颈并散开。

「桐人，教教我……我该怎么办才好……」

没有声音回答她的问题。

「我……该怎么办…………」

一滴又一滴落下的泪珠，淡淡地凝聚了由窗帘缝隙照射进来的月光。

2

天亮后的十之月二十二日，是这个秋天最冷的日子。

爱丽丝取消了散步，和桐人一起在暖炉边度过这段时间。虽然按照卡利塔老人教导，打算在冬天正式来临前准备大量的柴火，但现在看起来已经没有这个必要了。

光是写两张羊皮纸信件就花了一整天的爱丽丝，犹豫了一下后，才在泛用语写下的滋贝鲁库姓氏下方，再用神圣语签下了辛赛西斯‧萨提。

仔细地把信件摺好，用带子绑起来，在外面写上赛鲁卡的名字。然后和另一封给卡利塔老人的信并排在桌子上。

那是道别和谢罪的信件。自己已经没办法继续住在这间被整合骑士艾尔多利耶得知的房子里了。下一次恐怕就不是艾尔多利耶，而是骑士长贝尔库利本人过来说服自己。那个时候，爱丽丝将不知道怎么拒绝对自己有大恩的师父。

所以只能再次逃走。

叹了一口又细又长的气后，爱丽丝抬起脸来，看向坐在桌子对面的黑发青年。

「桐人，你想去哪里？听说西域的高原地带相当美丽。还是南域的密林地带比较好？据说一整年都很温暖，可以摘到各种水果喔。」

虽然试著发出更加开朗的声音，但桐人当然还是没有任何反应。

空虚的眼睛只是一直朝著桌子表面。想到又得带著这名受伤的年轻人过流浪的生活，爱丽丝心头就感到一阵刺痛。但是，也没办法把他丢在卢利特村不管。不能强迫身为修女见习生的赛鲁卡接下这种困难的任务，而且爱丽丝本身也不愿意这么做。因为照顾桐人，已经是爱丽丝活下去的唯一理由了。

「……好吧，就把去向交给雨缘决定吧。差不多该睡了，因为明天还得早起呢。」

帮桐人换衣服并且让他躺到床上后，自己也换上睡衣并且把油灯吹熄，接著爱丽丝就钻到毛毯底下。

在黑暗当中，竖起耳朵倾听桐人的呼吸声。知道他完全睡著后，爱丽丝悄悄移动身体。

把头靠在桐人骨瘦如柴的胸口后，紧贴在上面的耳朵就感觉到缓缓的鼓动。

桐人的心已经不在这里了。心脏的声音，也不过是过去留下来的残响。每天晚上都靠在他身边睡著的爱丽丝，这几个月来一直有这样的想法。但同时也有怦咚怦咚的声响深处，似乎还残留著些什么的感觉。

如果现在的桐人是思考完全正常，只是无法表达出来的话，应该要如何开脱自己这样的行为呢？想到这里爱丽丝就一边露出些许微笑，一边陷入浅浅的睡眠当中。

突然间，靠著的身体传来轻微的震动。

爱丽丝死命抬起沉重的眼睑。虽然左眼看向东侧的窗户，但从窗帘缝隙里看见的天空还是一片黑暗。感觉上大概只睡了两三个小时而已吧。

爱丽丝对身体再次绷紧的桐人呢喃：

「还是晚上喔……再睡一下吧……」

她一面再次闭上眼睛，一面抚摸著桐人的胸口想让他沉睡。但是当听见耳边发出细微的声音后，爱丽丝才终于注意到年轻人的异常。

「啊……啊……」

「桐人……？」

现在的桐人，已经没有自发性的欲求。应该不会因为寒冷或者口渴之类的事情醒过来才对。但是年轻人的身体却震动地更加厉害，简直就像要离开床铺般动著腿部。

「怎么了……？」

想到「不会是意识恢复了吧」的爱丽丝，迅速撑起上半身，甚至不愿意花时间点燃油灯，直接就生成一个光素。

在微弱白光照耀下，桐人的眼睛还是跟平常一样充满空虚的黑暗。看见这一幕后，爱丽丝沮丧地叹了口气。但这样的话，到底是什么让他──

这时爱丽丝的耳朵又听见从窗外发出的声音。

应该在空地角落睡觉的雨缘，这时发出了鸣叫声。那是带有要主人提高警戒之意的尖锐声音。

跳下床铺的爱丽丝，直接从寝室穿越客厅，推开了玄关的门。外面的冰冷夜风一瞬间灌了进来。原本应该只蕴含森林气味的风，这时却带有其他奇异的味道。这刺入鼻腔深处般的气味是，烧焦味──

爱丽丝光著脚跳到前面的院子里。环视夜空后，瞬间屏住了呼吸。

西方的天空可以看见火光。

不祥的朱红色光芒，无疑是由巨大火焰反射出来。凝眼一看之下，就能看见几道横跨星空的黑烟。

──森林火灾？

虽然一瞬间有了这样的想法，但立刻就打消。乘著焦臭的风一起传过来的，是细微的金属敲打声──以及大量的悲鸣。

这是敌袭。

黑暗领域的军队袭击了卢利特村。

「……赛鲁卡！」

爱丽丝发出沙哑的悲鸣，准备要冲回家去。但爬上门廊时就整个人僵住了。

无论如何都要救出双亲与妹妹。

但其他村民又如何呢？

如果想尽可能解救所有人，就一定得跟黑暗军队正面交战。但现在的自己真的还有这样的力量吗？

整合骑士爱丽丝力量的泉源，是对公理教会与最高司祭的盲目忠诚心。而这样的信仰已经随著右眼消失，现在的自己真的可以挥动金木樨之剑并使用神圣术吗？

整个人冻结的爱丽丝，耳朵──

听见小屋里传出「喀哒」的声音。

吓了一跳的她瞪大了左眼。在微暗的客厅中央，有一张椅子翻倒了，椅子旁边则有一名黑发年轻人正在地上爬。

「……桐人……」

爱丽丝驱动著快丧失力量的脚进入小屋内。

桐人眼里依然没有意志的光芒。但他缓慢动作的目的已经相当明确。伸出来的一只手臂，笔直地指著挂在墙壁上的三把剑。

「桐人……你……」

从爱丽丝胸口涌起的暖流塞住了她的喉咙。她花了一段时间，才发现让视界模糊的东西是眼泪。

「……啊……啊……」

发出沙哑声音的桐人，完全没有停下动作，只是全心全意地朝著剑前进。爱丽丝擦去眼角的泪水，一直线朝年轻人跑去，把他瘦削的身体从地板上抱起来。

「别担心，我会过去。我会去帮助村子里的人。放心在这里等我回来吧。」

迅速对他呢喃完后，爱丽丝就用力抱紧桐人。

怦咚、怦咚。靠紧的胸口，可以感觉到心脏的跳动。

这样的声响里，潜藏著就算心扉紧闭也绝不会燃烧殆尽的意志力。就算只是微弱的火光，爱丽丝的身体还是确实感觉到温度。

用力贴紧对方的脸颊后，爱丽丝就抬起轻盈的身体，让他坐到椅子上。

「救完大家后，我会马上赶回来。」

再次对他这么说完后，就先把一直收在柜子里的铠甲与剑带拖出来，直接套到睡衣上面。接著又跑到东侧墙边，毫不犹豫地抓下自己的爱剑。

隔了半年才又握住金木樨之剑，双手立刻就感觉到它沉甸甸的重量。把剑鞘上的挂钩钩在剑带上，一边穿上外套一边把脚放进靴子后，随即再次跑下门廊来到前院。

「雨缘！」

朝著东侧的床铺叫了一声，立刻有一道巨大的影子飞过来，对著爱丽丝低下头。

跳上长脖子底部的爱丽丝，用短促的声音下达命令：

「走吧！」

银色双翼「啪嚓！」一声拍打了起来，经过短暂的助跑后，飞龙一口气飞上夜空。

才上升到一定高度，马上就清晰地看见卢利特村的惨状。冒出熊熊火光的主要是村子北侧。袭击者果然是从黑暗领域穿越尽头山脉而来。

昨天晚上艾尔多利耶曾经说过，在贝尔库利指示下弄塌的「北方洞窟」没有异状。如果短短一天就能够撤去那么大量的瓦砾，那么为了这次袭击而动员的士兵数量就不只是十几二十人那么简单了。

自古以来，似乎就有少数部队趁著黑夜穿过贯通尽头山脉的三处洞窟，来到人界为恶的事情发生。桐人和尤吉欧也说过，在到央都之前，曾经在北方洞窟和哥布林集团战斗。但从来没听过有如此大规模且露骨的袭击。暗之国整体对人界进行总攻击的气势果然越来越高涨了吗？

当爱丽丝想著这些事情时，雨缘一口气飞越深邃的森林，来到卢利特村近郊的麦田上空。

虽然没有缰绳，但爱丽丝改用手掌轻轻拍了一下龙的后颈，做出滞空的指示。

接著她探出身子，凝眼观察村子的状况。南北延伸的大道上，北侧已经冒出红艳的火光，可以清楚地看见众多袭击者进逼的影子。以跳跃般动作行走的，是敏捷的哥布林。稍远处则有不少庞大的半兽人往此处推进。

中央广场的北侧附近，虽然筑起了由家具与木材堆叠出来的临时防御线，但哥布林的前锋部队已经抵达该处，越过障碍物互相交锋的刀刃不停闪出刺眼的光芒。

应战的是村子里的侍卫队。但是人数、装备与训练程度根本比不上哥布林部队。这样下去，马上就会被后方一面踩著沉重脚步一面往这里逼近的半兽人部队轻易地击溃。

爱丽丝压抑下想立刻纵身到战场中央的心情，继续确认状况。

村子的东侧与西侧也有几处著了火。但是广场南边似乎还没有受到伤害。除了侍卫之外的村民──当然赛鲁卡也是──应该都从南门脱逃到森林里避难了吧。

心里这么想的爱丽丝，再次凝眼看向广场，结果忍不住发出了声音：

「为什么……！」

教会前的圆形广场上，出现无数像要包围中央喷水池般的紧紧靠在一起人影。因为人数实在太多，导致于无法立刻注意到。卢利特村的所有居民应该都聚集在那里了。

他们为什么不逃到村子外面？

袭击者的本队到达防御线的话，侍卫们瞬间就会溃败吧。要是不立刻开始移动，就来不及避难了。

爱丽丝再次拍拍飞龙的脖子，让它前进到广场正上方后大叫了一声：

「雨缘，在我叫你之前，先在这里待机！」

然后就毫不犹豫地从高达数十梅尔的高度纵身往下跳。在外套衣襬强烈拍动的情况下，划过夜晚冰冷的空气落下。

围成圆形的三百多名村民可能还算有应战的意识吧，在外围配置了拿著锄头与大镰刀等农具的男性。这些人旁边有两名男性不停做出指示，而爱丽丝就在他们附近落地。

石头地板随著雷鸣般的轰然巨响呈放射状裂开。一阵强烈的冲击由脚底贯穿爱丽丝脑门，虽然减少了一些天命，不过确实发挥出效果。

两名男性──富农纳伊古鲁‧巴尔波萨与卢利特村村长卡斯弗特‧滋贝鲁库，都因为忽然从头顶降下来的人影而吓得沉默。

爱丽丝看见父亲的脸后感到有点难以呼吸，但还是没有错过自己造成的寂静大声喊道：「在这里没办法抵挡它们！请立刻让所有村民从南方的大道避难！」

听见爱丽丝的指示后，男人们脸上就露出更加惊讶的表情。

但回过神来的纳伊古鲁从嘴里发出来的，却是浑厚的怒骂声：

「别说蠢话了！怎么能拋下房子……拋下村子直接逃走呢！」

面对额头露出青筋的富农，爱丽丝立刻以尖锐的语气反驳道：

「现在避难的话，还可以不被哥布林追上顺利逃走！家产和生命究竟哪个比较重要！」

顿时语塞的纳伊古鲁只能发出「咕」一声，这时由村长卡斯弗特代替他以低沉紧张的声音说：

「是侍卫长吉克指示我们在广场围成圆形来加强防御。在这种情形下，身为村长的我也必须遵从他的命令。这是帝国法律的规定。」

这次换成爱丽丝说不出话来了。

在发生事故时，担任侍卫长天职者，得暂时取代村长或镇长掌握所有居民之指挥权。诺兰卡鲁斯北帝国基本法里确实存在这样的条文。

但名为吉克的侍卫长，不过是一个刚从父亲那里接下天职的年轻人。在这样的异常事态当中，不可能做得出冷静的指挥与判断。卡斯弗特脸上藏不住的焦虑，正表示他内心也有这样的想法。

只不过，对村民来说，帝国法律拥有绝对的权威。想让他们开始避难的话，只能把应该在广场北侧的防御线指挥战斗的吉克拖回来改变命令，但现在已经没有这种多余的时间了。

怎么办？该怎么办才好──

就在这个时候，一道稚嫩但坚毅的叫声冲进束手无策的爱丽丝耳朵里。

「爸爸，我们按照姊姊所说的去做吧！」

惊觉的爱丽丝移动视线后，就看见在人墙内侧，有一名娇小的修女正在用神圣术治疗应该是被火灼伤的村民。

「……赛鲁卡！」

心里想著「太好了，她平安无事」的爱丽丝，随即准备对疼爱的妹妹跨出脚步，但赛鲁卡已经先站起来，穿越人墙来到三个人旁边。

一瞬间对爱丽丝露出笑容的赛鲁卡，马上恢复严肃的表情，对卡斯弗特搭话道：

「爸爸，从以前到现在，姊姊有哪一次说错了？不对，应该说就连我也知道，这样下去大家都会被杀掉！」

「但……但是……」

卡斯弗特以苦涩的表情吞吞吐吐起来。嘴巴上方黑白混杂的胡须不停轻微震动，呆滞的视线也在空中游移。

代替说不出话来的村长，纳伊古鲁‧巴尔波萨再次爆发愤怒的声音：

「这不是小孩子能插嘴的事情！我们要保护村庄！」

充满血丝的双眼，目不转睛地盯著建在广场附近的巴尔波萨家宅邸。巴尔波萨脑袋里一定只想到秋天刚收成的大量小麦，以及长年累积下来的金币。

富农把视线拉回到爱丽丝与赛鲁卡身上，理所当然般以尖锐的声音激动地大叫：

「对……对了，我知道了！就是你让暗之国的怪物进到村庄里来的吧，爱丽丝！你以前跨过尽头山脉的时候，就被黑暗的力量污染了！魔女……这个女孩是恐怖的魔女！」

被粗大的手指一指后，爱丽丝顿时哑口无言。村民们的骚动、防御线响起的兵器击打声，以及怪物们逐渐从北方逼近的哄闹声都瞬间远去。

自从在村子外围生活后，爱丽丝就在纳伊古鲁的委托下帮忙砍过好几棵森林里的巨树。每一次这个男人都像快把身体扭断般地感谢她。但现在却为了守护自家的财产而说出那样的话，竟然有如此卑劣的人──

爱丽丝把视线从这名露出半兽人般丑恶表情的中年男子身上移开，在内心呢喃著。

──不用管他们了。

──我也只要按照自己的意思去做。只要带著赛鲁卡与卡利塔老人以及双亲离开村子，然后到远方找个新的住所。

她用力咬紧牙根，并且闭上眼睛。

心里继续想著：「但是……」

──纳伊古鲁‧巴尔波萨与其他村民之所以会如此愚味，全是因为公理教会数百年来统治所造成的结果。

禁忌目录以及其他无数的低位法与规范束缚了人们，虽然让他们沉浸在温水般的安宁当中，但是也夺走了重要的东西。

也就是思考与战斗的力量。

几乎等于无限的岁月里，这些人们持续被夺走的无形力量究竟累积到什么地方去了呢？

其实就是仅有的三十一名整合骑士的身体当中。

爱丽丝用力吸了一口气并呼出来，然后以要发出声音般的速度瞪大左眼。

视线前方的纳伊古鲁忽然像感到害怕般，脸色变成一片苍白。

相对的，爱丽丝则感觉身体深处充满了不可思议的力量。那股力量就像是虽然安静，但是比任何东西都要炽热的蓝白色火焰。也就是在中央圣堂最上层的决战后，就觉得已经消失的──让桐人、尤吉欧以及爱丽丝对抗人界最强支配者的力量。

爱丽丝用力吸了一口气，并且宣告：

「……我废弃侍卫长吉克的命令。我命令聚集在这座广场的所有村民，由拿著武器的人带领，全都退到南方森林去。」

声音虽然相当平稳，但纳伊古鲁却像是被看不见的手击中般上半身整个向后仰。但就算是这样，他还能是用颤抖的声音反问，而这也让人不得不佩服他的胆量。

「被……被赶出村子的女孩，能用什么权限做出这种命令。」

「骑士的权限。」

「骑……骑士是什么啊！这村子里根本没有这种天职！稍微会点剑法就敢随便自称骑士，要是被央都的骑士大人知道了不知道会……」

爱丽丝紧紧盯著口沫横飞的纳伊古鲁，用左手抓住外套的右肩部分。

「我……我的名字是爱丽丝。是统括管理圣托利亚市的公理教会整合骑士第三位，爱丽丝‧辛赛西斯‧萨提！」

她高声报出自己名号，同时也把外套拉下来。

覆盖全身的厚重布料被拿开的瞬间，黄金铠甲与金木樨之剑反射炽烈火焰的颜色，发出刺眼的光芒。

「什么……整……整……整合骑士……！」

纳伊古鲁发出完全沙哑的声音，以大吃一惊的表情一屁股坐到地上。卡斯弗特也跟著瞪大了双眼。

爱丽丝不可能报出假的名号。因为这个世界上，没有能诈称整合骑士──也就是能够否定公理教会权威的人存在。虽然办得到的大概就只有桐人与爱丽丝两个人而已，但从央都逃到这里的现在，爱丽丝也没有舍弃身为骑士证明的佩剑。

原本在周围騒动著的村民也瞬间安静了下来。从北方防御线持续传出的交战声，侍卫与哥布林之间的吼叫声也瞬间远去。

首先打破沉默的，是赛鲁卡的呢喃声：

「姊……姊……？」

把左眼朝向在胸前合握住双手的妹妹后，爱丽丝露出温柔的微笑。

「抱歉之前一直瞒著你，赛鲁卡。这就是加诸在我身上的真正惩罚。同时也是──真正的职务。」

听见这些话的赛鲁卡，双眼立刻浮现出泪珠。

「姊姊……我……我一直都相信你。我知道姊姊一定不是罪人。真的……好漂亮……」

接著有所行动的是卡斯弗特。

发出「喀」一声清脆的声音跪到石头地板上的村长，一边低下头一边以坚定的声音大叫：「谨遵整合骑士大人的命令！」

他迅速站起来，对著背后的村民做出简洁的指示：

「全员起立！在带著武器的人前导下往南门逃走！离开村庄后，就逃进开拓地的南方森林里！」

僵硬地站在现场的村民间，出现了不安的骚动。但一瞬间就消失了。村民之间原本就不存在违抗村长命令的选择，何况现在还是受到整合骑士的命令。

靠在外围的强壮农夫群站了起来，也催促女性、小孩与老人快点起立。爱丽丝叫住准备加入先头集团的卡斯弗特，压低了声音告诉他：

「爸爸，各位村民……赛鲁卡还有妈妈就拜托您了。」

卡斯弗特严肃的表情一瞬间产生动摇，然后也同样简短地回答：

「…………也请骑士大人保重您的贵体。」

这名父亲一定再也不会把爱丽丝当成女儿了。这也是获得力量后必须付出的代价。爱丽丝一边把这件事刻划在心中，一边推著赛鲁卡的背，让她走到轻斯弗特身边。

「姊姊……不要太勉强喔。」

微笑著对依然流著眼泪的妹妹点了点头后，爱丽丝就把身体朝向北边。她背后的村民已经一起展开行动了。

「啊……啊啊……我的……我的宅邸……」

发出这种丢脸声音的，是依然瘫坐在地上的纳伊古鲁‧巴尔波萨。他交互凝视著逃走的村民，以及火焰已经烧到附近的宅邸。爱丽丝这时不再理会他，转而把意识集中到整座村子上。虽然成功让村民开始移动，但怎么说也有三百个人。所有人要逃离村子需要花上好一段时间。但防御线似乎快撑不住，从东西两边都能听见敌人逼近的脚步声。

这时广场北侧传来年轻男性近似悲鸣的大叫：

「不行了！撤退！撤退──！」

声音的主人应该是侍卫长吉克吧。听到叫声的瞬间，纳伊古鲁‧巴尔波萨像是重新有动力般站了起来，对著爱丽丝逼问道：

「看吧……你看见了吧！应该围在广场进行防御才对！大家要被杀掉了！全都要被杀掉了！」

爱丽丝耸了耸肩，冷静地反驳：

「别担心，有这么大的空间的话，我会在这里挡住它们。」

「怎么可能！不可能办得到啦！就算……就算你真的是整合骑士，也不可能独自战胜那么一大群恶鬼！」

即使已经可以看见哥布林恐怖的身影从东西两侧逼近，纳伊古鲁依然不停大叫著。爱丽丝再次无视他的存在，稍微往后面瞄了一眼。村民的最尾端依然在广场里面，但已经离开爱丽丝等人所在的中央部分一段距离。

爱丽丝用力抓住纳伊古鲁的衣领，把他推向南边。接著把那只手笔直指向夜空，高声呼唤爱龙的名字：

「雨缘！」

立刻从上空传来充满力量的咆哮。爱丽丝一边将右手由西往东挥下，一边持续叫著：

「──把它们烧光吧！」

如暴风雨般的翅膀拍动声降下，呆立在现场的纳伊古鲁与冲进广场的众多异形亚人──哥布林同时抬头往正上方看去。

黑影穿越被火焰染红的天空后急速降下的巨大飞龙，大大地打开了下颚。喉咙深处开始有蓝白色光芒闪烁──

咻啪！

这样的声音响起后，就迸发出刺眼的光芒。击中西侧道路的热线，横越站在广场南侧的爱丽丝与巴尔波萨面前，直接扫到东侧的道路。

隔了一会儿后──

剧烈的火焰一直线往上窜，朝著夜空解放威力。被吞没的哥布林全都发出尖锐的悲鸣并且被轰飞。

飞龙的炙热光线瞬间屠杀了二十只以上的袭击者，同时也把广场中央喷水池里的水蒸发掉，让周围全是一大片白烟。爱丽丝对掠过水蒸气上方飞走的雨缘做出待机的指示，然后往背后瞄了一眼。

纳伊古鲁‧巴尔波萨可能是吓得脚软了吧，只见他再次跌坐到地上，两眼像是快要掉出来一样。

「什……什么……飞……飞……飞……飞飞龙……！」

松垮的双颊不停痉挛的中年男人让爱丽丝浮现他到底是怎么了的想法，这时又从漫天水蒸气后方传出拚命跑过来的脚步声。出现在眼前的，是多名穿著相同皮革铠甲的卢利特村侍卫队队员。迅速决定撤退就结果来说是相当好的判断，十几名侍卫身上虽然到处是轻微的伤痕，不过没有重伤者出现。

勇敢地跑在最后的高大年轻人──侍卫长吉克注意到广场几乎净空后，随即一脸愕然地大叫：

「村……村子里的人到哪去了？不是要他们死守这个地方了吗？」

「我让他们退到南方森林去了。」

爱丽丝刚这么回答，吉克就像首次注意到她的存在般眨了眨眼睛。视线从头到脚打量了爱丽丝好几次后，才用茫然的表情说道：

「你是……爱丽丝……？为什么你能这么做……？」

「没时间说明了。这就是所有的侍卫吗？没有人还留在那里吧？」

「啊……嗯，应该是没有……」

插图009

「这样的话，你也跟大家一起逃吧。对了，还有那边的巴尔波萨先生也麻烦你了。」

「但……但是……那些家伙已经来到那…………」

话还没说完──

「叽哔────！」

粗野的叫声就响彻整座广场。

「在哪里！白色伊武姆逃到哪去了！」

突破浓雾冲进广场的，是穿著粗陋板金铠甲，右手握著铁块般蛮刀，头上还插著长羽毛的哥布林们。它们和刚才从侧面通道出现，然后被雨缘烧死的哥布林似乎不同部族，体格看起来比较强壮一点。

爱丽丝打量著这群亚人，右手一边放到爱剑剑柄上。飞龙的炙热光线没有办法连发。在雨缘体内再次囤满热素之前，爱丽丝得独自面对敌人。

其中一只哥布林注意到穿著黄金铠甲的爱丽丝，发出黄光的眼珠立刻涌出强烈的杀意与欲望，并且大叫：

「叽哔！是女伊武姆！杀了她！杀了她然后吃掉！」

爱丽丝静静等待以长到不可思议的手臂举起蛮刀，并且一直线往这里冲过来的亚人，心底深处同时这么呢喃。

这副作为整合骑士的身体──

竟然被赋予如此恐怖的力量。甚至觉得存在本身就是一种罪过。

「叽哔──────！」

爱丽丝随便伸出左手，挡下边跳跃边往下挥落的厚重蛮刀。没有任何防具的手掌虽然承受沉重的冲击，但是没有骨折，甚至连皮肤都没有裂开。五根手指抓住不算锋利的刀刃，像是薄冰般将其捏碎。

在脆弱四散的金属片掉到地面之前，右手拔出来的金木樨之剑就已经横向扫过哥布林的身体。

黄澄色的剑风波及由后方慢慢逼近的三只哥布林，瞬间吹散一大片浓厚的水蒸气。四只敌兵像是不知道发生什么事情般瞪大黄色眼珠，然后在不发一言的情况下上半身与下半身份家，重重地掉落到地面。

爱丽丝退后一步避开迟了一会儿才喷上来的血柱，再次在心中自言自语。

──最高司祭亚多米尼史特蕾达，你果然错了。

──你把这样的力量集中在仅有三十人的整合骑士身上，然后封锁这些人的意志，把他们变成随心所欲操纵的傀儡。藉由这样的手段，掌握住原本应该分给人界中所有人民的力量。但这过于偏颇的力量，却迷惑、困扰了拥有这股力量的人，以及他们身边的所有人。就像你自己也被过于强大的力量吞没，变得不再是一个人类……

最高司祭亡故的现在，已经无法矫正这样的错误。

这样的话，至少要为了所有人民耗尽这股力量。

不是做为公理教会的整合骑士，而是以一名剑士的身份，自己思考并以自己的意志战斗。就像过去曾经这么做过的两位勇敢剑士一样。

保持挥完剑姿势的爱丽丝，这时毅然睁开闭起来的左眼。

同一时间，构筑在广场北侧的应急防御线也从另一侧被打得粉碎。

像是要掩盖整条大道一样，侵略者的本队冲了进来。可以看到超过五十只以上的哥布林，以及数量虽然比较少，但圆滚滚的巨大身躯上裹著厚重铁制铠甲，带著长大三叉戟的半兽人。

黄色眼睛发出绚烂光芒的亚人们，发出充满憎恨与欲望的吼叫声，而包含吉克在内的众侍卫与纳伊古鲁‧巴尔波萨看见它们这种模样后发出绝望的呻吟。

但爱丽丝的心却相当平静。

并不是仗势整合骑士的战斗能力。被如此多的敌人包围，并且被长枪从四面八方刺中的话，就算是骑士的身体也不可能只受轻伤。

给予爱丽丝力量的，是心中唯一的全新认知。

──接下来我将为自己冀求的事物而战。保护妹妹与双亲，并且为了桐人与尤吉欧想要守护的人界人民而战。

爱丽丝确切地感觉到，残留在心底深处那份对自己的怀疑与无力感已经在白光中逐渐蒸发。那道光线在身体里环绕，最后聚集在被黑色绷带覆盖住的右眼，产生强烈的热度。

「………………！」

咬紧牙根忍耐著从眼窝贯穿后脑勺的剧痛。但那是有点怀念与苦涩的痛楚。爱丽丝用左手抓住横越头部的绷带，一口气把它扯了下来。

那一天之后已经闭了半年的右边眼睑轻轻张了开来。黑暗视野中央出现呈放射状扩散的红光，最后变成晃动的火焰。左眼看见的，是家家户户著火的光景变成双重影像，虽然有些误差但逐渐消弭──最后完全重叠在一起。

爱丽丝以一双眼睛，看著左手握住的黑布。

经过重覆洗涤后已经褪色的眼带，是桐人撕下自己的衣服所制作。几个月来都是靠著这条布保护随著封印炸裂的右眼，但它的天命可能终于到界限了，只见它从底端开始溶解在空气中并消失。爱丽丝一边凝视著这脆弱又美丽的光景，一边领悟到一件事。

这半年来，她认为自己是在保护、照顾著失去右臂与心智的桐人。但实际上自己才是被守护的人。

「……谢谢你，桐人。」

爱丽丝把快要完全消失的黑布贴在嘴唇上，然后细声呢喃：

「……我已经不要紧了。今后一定也会因为各种事而迷惑、烦恼以及受到挫折……但我还是会往前进。为了你和我所追求的事物。」

黑布消失的同时，爱丽丝迅速抬起头来。

两眼确实注视的前方，有将近一百只左右的哥布林与半兽人，一边发出吼叫声一边像雪崩般涌入广场。背后则响起众侍卫与纳伊古鲁‧巴尔波萨逃走的脚步声。

独自迎战一群敌军的爱丽丝，内心没有任何恐惧。

她用力吸进带著焦味的空气，接著大叫：

「──吾为人界的骑士爱丽丝！只要我在这里，你们就绝对得不到冀求的血液与杀戮！现在立刻通过洞窟回你们的国家去吧！」

像是被凛然响起的巨大声音震慑住一样，跑在最前面的几只哥布林来势稍微减缓。但下一刻，待在集团中央附近的一名看起来应该是大将的魁梧半兽人，就一边抬起双手拿著的斧头，一边爆出残忍的吼叫声：

「咕啦啊啊啊！不过是一只小小的女白伊武姆，看本『砍脚的摩利卡』大爷马上就让你趴到地上！」

哥布林的气势随即因为这道声音再次高涨。爱丽丝把宛如黑色巨浪般朝自己逼近的大军引诱到足够的距离后──

「雨缘！」

一呼叫名字的瞬间，就有一道巨大的影子从上空急速降下。虽然还没囤积够足以发射炙热光线的热素，但飞龙改以躯体与打雷般的声音来威吓这些亚人，从快要碰到它们头部的高度猛然通过天空。吃惊的敌军比刚才还要惊慌失措。

爱丽丝不错过这个机会，高高举起右手的金木樨之剑，大叫道：

「──Enhance armament！」

虽然隔了半年才又咏唱，而且还是省略术式本体的「武装完全支配术」式句，但爱剑还是回应了爱丽丝的意志。黄金剑身随著清澈的金属声分裂成无数小剑刃，一边反射火焰的光芒一边飘上夜空。

「狂舞吧──花朵们！」

「唰」一声过后，黄金的花朵就像暴风雪般淋到敌军身上。

首先陷入一片血海的是自称摩利卡的大将半兽人。全身被好几朵花贯穿，瞬间丧失所有天命，随著轰然巨响往正后方倒去。站在它周围的半兽人，则不断发出悲鸣并趴到地上。

金木樨之剑是源自于创世时代就成长于人界中心的最古老树木，可以算是神器中的神器。它拥有「永劫不朽」的外号，即使用武装完全支配术分离成数百朵花瓣，每一朵花的优先度还是足以媲美知名工匠打造出来的名剑。粗陋的铸铁铠甲根本无法抵挡。

一瞬间失去包含大将在内的主力部队，侵略者们顿时不知所措。往前冲的气势为之一挫，在进入广场十梅尔左右的地方停下脚步。

当最前列的众多哥布林们还在犹豫该遵从欲望还是恐惧时，爱丽丝已经敏锐地挥动右手上的剑柄。「唰」一声轻快的声音过后，数百朵花飞舞到天空中，在爱丽丝与敌军之间排成了整齐的直条纹模样。

爱丽丝透过金碧辉煌的栅栏看著亚人们，然后静静地宣告：

「这是区隔人界与暗之国的墙壁。就算你们把洞窟挖开，只要有我们骑士在的一天，就不会让你们污染这块土地！选择吧──是要前进倒在血泊里，还是往后逃回暗之国！」

不到五秒钟的时间，最前面的哥布林就迅速回头逃走了。

3

由铁锤声构成的热闹合奏，在冬天清澈的蓝天中往上飞舞。

爱丽丝把手遮在额头上，看著麦田后面往上隆起的卢利特村。

被黑暗军队袭击之后，到今天很快地已经过了一周。

虽然村子里建在北侧的房子有许多都被烧毁，但几乎所有村民都在村长决定下暂时放下天职，投入重建作业，因此重建的进展相当神速。令人惋惜的是有二十一名来不及逃走的村民丧命，三天前也在教会为他们举行了肃穆的联合丧礼。

爱丽丝在邀请下参加了丧礼，之后乘坐飞龙前往确认北方洞窟的状况。

在贝尔库利命令下应该已经被弄塌的长长洞窟，目前已经被拓宽到连半兽人的巨大身躯都能轻松通过，在最接近黑暗领域的附近则可以看到长期夜营的痕迹。

袭击者不是只花了一晚就把洞窟挖开。应该是由黑暗领域这一边送进去一团工兵后，就再次只把入口的部分弄塌。整合骑士艾尔多利耶确认入口时，洞窟内已经潜伏著一团工兵，不停进行著开通作业。

这是在过去的哥布林与半兽人身上很难看见如此周到的行事与深思熟虑。从这件事来看，就能知道这次的侵略不像之前那样只是普通的侦察。

爱丽丝没有再次弄塌洞窟，而是暂时塞住从过去白龙巢穴的中央部分涌出的小河流，让洞窟内部完全浸在水中。之后又解放无数事先生成的冻素，不再用岩石而是以冰块把洞窟封印起来。

这样只要没有与爱丽丝同等级的术者以热素来融化冰块，就没有人能够进入洞窟。

把视线从卢利特村以及浮现在远方的雪白尽头山脉移回来后，爱丽丝把手中拿著的最后的旅行袋绑到雨缘左脚上。

「那个……姊姊……」

赛鲁卡之前都一直带著坚强的笑容帮忙准备行李，这时候却低著头开口说道：

「……爸爸他其实也很想来送行。今天从早上就一直给人心不在焉的感觉。我想……他心里一定对姊姊能够回来感到高兴。这一点请一定要相信他。」

「这我当然知道，赛鲁卡。」

爱丽丝抱紧妹妹娇小的身体，低声这么回答她。

「我以重罪人的身份离开村子，然后成为整合骑士回到这里。但下一次……等将来我完成所有任务后，我会以普通人爱丽丝‧滋贝鲁库的身份回来。那个时候，我想就可以确实地说出『爸爸，我回来了』。」

「……嗯。一定会有这么一天。」

以哭泣的声音呢喃完的赛鲁卡抬起脸，然后用修道服的袖口用力擦拭脸庞。

接著又转过身体，用充满精神的声音对旁边坐在轮椅上的黑发年轻人说：

「桐人也要保重喔。快点好起来，然后帮爱丽丝姊姊的忙。」

用双手包覆年轻人低垂的头部，在比完祝福的手势后，年幼的修女便退后了几步。

爱丽丝靠近桐人，轻轻从他怀里拿下两把剑，将其收到挂在雨缘鞍上的行李袋当中。接著又轻轻抬起瘦削的年轻人，让他坐在龙鞍的前面部分。

她也曾想过把桐人留在村子里拜托赛鲁卡照顾。只要前往应该会成为与黑暗军队决战之处的东大门，身为人界守备军一员的爱丽丝就会忙到分身乏术，不可能像现在这样成天跟在桐人身边。

但就算是这样，爱丽丝最后还是决定把他带走。

一周前敌军袭击的那个晚上，桐人确实想拿剑赶往村子里。桐人心中仍残留著为了他人而战的意志。这样的话，应该要到为了守护人界的战场，才能找到让他恢复心灵的办法。

到了紧急时刻，就算把他绑在背后也要保护他的安全。

爱丽丝最后又跟疼爱的妹妹紧紧拥抱了一下。

「……那么，我走了，赛鲁卡。」

「嗯，小心喔……一定要回来啊，姊姊。」

「我一定会回来……也帮我跟卡利塔先生说一声……你要保重，然后好好学习。」

「我知道啦。我一定会成为独当一面的修女……然后，总有一天也一定会……」

赛鲁卡没有把话说完，哭得唏哩哗啦的脸上一边流泪一边露出笑容。

爱丽丝温柔地摸了摸妹妹的头后才把身体移开，然后压抑下依依不舍的心情走向爱龙，直接坐到龙鞍上的桐人身后。

对地面上的妹妹点了点头后，爱丽丝把视线朝向蓝天。

轻轻甩了一下缰绳，飞龙就像完全感觉不到两个人与三把剑的重量般，以强劲的力道在麦田当中助跑。

将来一定要回到这座村子里。

就算倒在战场上，心也一定要回来。

爱丽丝拭去留在睫毛上的泪珠，发出短促的喊叫声：

「……喝！」

轻轻飞起。

随著飘浮感离开地面。

捕捉到上升气流的雨缘，一面回旋一面一口气飞上天空。

把宽广的田野与森林，以及位于其中央，新建的屋顶正闪闪发亮的卢利特村，还有边挥动双手边拚命奔跑的赛鲁卡深深烙印在眼里──

爱丽丝朝向东边的天空，也就是飞龙脖子的方向看去。

** 第十六章 袭击Ocean Turtle 西元二〇二六年七月

1

即使是自认为超级天才的比嘉健，也无法事先预测到这两个小时内所发生的各种事象。

但是，目前在比嘉眼前进行的，是这些事象当中最令人惊讶的情景。

一名年约十八到十九岁的纤细少女，竟然用细瘦的右手抓起一个男人的衣领，而且那个男人还比她高出十五公分。男人鲜艳的夏威夷衫就像要被扯破般绷紧，拖鞋也整个悬空。

结城明日奈一边用发出绚烂光芒的眼睛瞪著菊冈诚二郎二等陆佐，一边由惹人怜爱的嘴唇里丢出宛如刀锋般尖锐的发言：

「如果桐人的意识就此无法恢复，我一定饶不了你。」

菊冈的黑框眼镜反射天花板照明的光线，因此从比嘉的位置看不见他的表情。但这名柔道与剑道应该都是黑带的干部自卫官，却像是被明日奈说的话震慑住了一样。他吞了一大口口水，把双手举到脸的左右表示投降。

「我知道。基于职责，我一定会让桐人复原。」

紧绷的沉默，笼罩在整间微暗的副控室当中。

不论是坐在操控台前面椅子上的比嘉，站在旁边的神代凛子，还是留在房间里的数名RATH工作人员都说不出任何一句话。现场最年轻的少女散发出来的气势就是带有这样的压力。比嘉意识的角落浮现出「原来如此。这个女孩确实是战场『生还者』」的想法。

最后明日奈默默地松开右手。获得解放的菊冈露出几乎要瘫坐到地板上的模样呼出一口长长的气，明日奈也无力地退了几步。凛子立刻让白衣翻动冲过去撑住她的背部。

对比嘉来说是研究室学姊的女性物理学者，在穿著白衣的胸口抱紧明日奈，然后用坚定的口气呢喃：

「别担心，一定没问题的。他绝对会回到你身边。」

听见这番话后，明日奈紧绷到极限的表情瞬间扭曲。

「…………嗯，说得也是。抱歉……我一时乱了分寸。」

明日奈眼角浮现即使在之前的袭击中也没有出现的眼泪，而凛子则是温柔地用指尖把它拭去。

手动打开自动门的声音，让好不容易得到一此缓和的空气再次紧绷。冲进房间里来的，是中西一等海尉。

白色衬衫被汗水与灰尘弄脏，肩挂式枪套露出大型手枪枪柄的中西，稍微瞄了凛子等人一眼后，才以清晰的声调对站在深处的菊冈说道：

「报告！已确认第一、第二耐压隔板完全封闭，所有非战斗人员也已经退避到船首区块！」

菊冈一面整理夏威夷衫的衣领一边往前走，然后点著头说：

「辛苦了。隔板大概可以撑多久？」

「是的……虽然也得看那些家伙带来什么装备，但隔板不可能用轻兵器破坏。用圆锯机等工具来切割的话，最少也得花上八个小时。当然也有使用爆裂物来破坏的可能性……但他们应该不会这么做。因为中央隔板附近……」

「有LightCube Cluster在。」

菊冈接著把话说完，然后推著眼镜的镜桥，默默地思考了一阵子。

不过马上又抬起脸来，环视了一下狭窄的副控室。

「好，我们来整理一下状况。中西一尉，报告一下人员伤亡的情形。」

「是的。民间企画小组有三名研究员受到轻伤，目前在船首的医务室里接受治疗。自卫队的战斗员重伤两名，轻伤两名。同样在接受治疗当中，不过目前没有生命危险。能够战斗的人员，包含轻伤的两名在内共有六名。」

「在那么强大的火力攻击下，没有出现死者只能说是侥幸……那么，接下来报告船体的被害状况。」

「船底船坞的操纵室已经是千疮百孔。不可能从远距离进行关闭。从船坞通往主控室的通道虽然也是一样，但这应该只算是轻微损伤。严重的是主电源缆线被切断……虽说电力本身还是由副缆线稳定供给到各处，但不重新启动控制系统的话，螺旋桨就不会运转。」

「就像没有鳍的海龟，而且腹部还被鲨鱼咬住了吗？」

「是的。下轴的一号到十二号所有区块以及船底船坞都全部被占领了。」

留著一头短发，容貌直接让人联想到刚毅两字的中西很懊悔般绷起了脸；相对的菊冈则是撩起有点像教师的略长浏海，坐到旁边的操纵台上用脚尖晃动著木屐。

「主控室、第一STL室以及核子反应炉全都被占领了吗？不幸中的大幸是……那些家伙的目的不是破坏。」

「嗯……何以见得？」

「如果只是要破坏，就不必大费周章地使用潜水艇进行突入作战，只要发射巡弋飞弹或是鱼雷就能解决了。现在的问题是……那些家伙究竟是什么人……比嘉，你有什么意见？」

话题忽然被丢到自己身上，比嘉眨了好几次眼睛后，好不容易才让还残留著冲击余韵的脑部重新运作。

「啊～这个嘛，嗯……」

一边发出无意义的沉吟声一边转向操纵台，然后用右手操作滑鼠，把船内监视摄影机的录影画面叫到正面的大萤幕来。

打开的影片视窗虽然又暗又不清晰，但他在适当的地方暂停后，又调整了亮度与对比。结果浮现的是摆出往前弯身的姿势在船内通道移动的复数人影。他们穿著全黑色战斗服，脸孔上半部覆盖在附有多机能护目镜的头盔下，手上则拿著具威胁性的突击步枪。

「……正如萤幕上所见的，头部和身体都没有任何国旗或识别标志等东西。装备的颜色、形状也不像哪个国家的正规军。手上的步枪像是斯泰尔制，这种大量生产的枪械相当常见……唯一知道的是，从体格的平均值来推测，他们应该不是亚洲人。」

「也就是说这些家伙，至少不是属于我国的特殊部队吗？这可真令人高兴。」

随口说出危险发言后，菊冈搔了搔下巴。平常总是温和地眯起来的眼睛发出锐利光芒，仰望著大型蛋幕。

「还可以确定另一件事……就是这些家伙知道Project Alicization的存在。」

比嘉也同意菊冈的看法。

「嗯，应该是这样没错。因为他们从船底船坞闯入后，就毫不犹豫地冲上主控室。他们的目的也就是夺取STL技术的……不对，应该说夺取真正Bottom-up型人工智慧『A.L.I.C.E.』。」

也就是说，严重的情报外泄已经发生很长一段时间了。但比嘉没有把这件事说出口，也压抑确认副控室内所有RATH员工长相的冲动，故意以乐观的口气继续说道：

「幸好来得及封锁主控室。这样比物理破坏操纵台更能阻止他们直接操纵Underworld。不但不能介入模拟，也没办法把保存『爱丽丝』摇光的LightCube从Cluster弹射出来。」

「但是我们也一样没办法做到吧？」

「是啊。这间副控室也无法进行管理者权限的操作。不论是主控或者副控，都无法藉由外部操作把『爱丽丝』的LightCube弹射出来了。但是菊老大……这样就等于我们已经胜利了吧？那些家伙在物上和情报上都无法接近Cluster，再来就只要等护卫的神盾舰派遣援军攻入，那些家伙真的就爽翻啦。」

「虽然不知道你的爽翻了是什么意思……不过问题就在这里。」

菊冈依然带著严肃的表情，直接对中西问道：

「怎么样，『长门』有行动吗？」

「是的……关于这件事……」

中西在刚毅的嘴角灌注力量后回答：

「横须贺的舰队司令部，对长门发出了保持目前距离待机的命令。司令部似乎判断我们被攻击者当成人质了。」

「怎么会…………」

比嘉的下巴整个垮了下来。

「什么叫人质，船上的所有船员不是都撤退到耐压隔板这边了吗？」

这时以冷静声音回答的人是菊冈。

「那些浑身漆黑的家伙，恐怕和自卫队的上层有联络管道。长门是今天早上八点远离O Turtle，比那些家伙闯进来的时间早了六小时。上层应该会等那些家伙夺走『爱丽丝』的LightCube之后，才会对长门发出攻坚命令吧。当然，还是会有时间限制就是了……」

「这也就是说，那些家伙不是一般的恐怖分子喽。那就糟了……如果对方也有专家，说不定会注意到回收爱丽丝的密技……」

「从Underworld内部进行操作吗……那些家伙控制了第一STL室，也可以从设置在Underworld的虚拟操纵台进行弹出操作……」

「进行那个操作会怎么样？」

比嘉带著动作来回答凛子的问题：

「目标的LightCube会被从位于主轴中央的LightCube Cluster里取出来，然后经由空气管运送到任何一间控制室里。那里也有取出口喔。」

他用手指了一下操纵台桌面角落的四角形窗口，然后将视线移到设置在深处墙壁上的门。

铝合金制的门上用螺丝锁著一个小小的金属牌。牌子上刻著的文字是「第二STL室」。

门的另一边存在两台STL──也就是「Soul translator」。其中一台里面，躺著一名年轻人，旁边则有安岐夏树护士兼二等陆曹在看护。年轻人当然就是从Alicization计划初期就提供很大的帮助，目前甚至可以左右计划去向的桐谷和人了。

把视线移回来的菊冈，一边用双手环抱在胸前一边以沉重的口气说道：

「所以，又只能把最后的希望托付在他身上了。比嘉……桐人他的状况怎么样？」

听见细微的吸气声后，比嘉一移动视线，就和即使在凛子支撑下还是笔直看著这边的结城明日奈四眼相对。

比嘉犹豫著该怎么对似乎是桐人，也就是桐谷和人女朋友的她说明现状。但马上就有沙哑但是坚定的声音传进他耳里。

「我不要紧，请告诉我实情。」

深呼吸了一口气并呼出后，比嘉点了点头。

「用一句话来形容……就是只差一步就陷入最糟状态了……」

一面改变语调如此说明后，比嘉再次操纵起滑鼠。

众袭击者的静止影像消失，另一个视窗打开。出现在萤幕上的，是缓缓摇动的彩色三次元图表。

「这是把桐人小弟的摇光视觉化后的结果。」

房间里所有人都默默地凝视著萤幕。

「一周前，他在东京被注射了肌肉松弛药物，陷人心肺停止状态。虽然所幸保住了性命，但脑的一部分……正确来说是摇光网路受到了损伤。这是现有的脑医学很难治愈的损伤，但应用STL技术就有回复的可能性。于是我们为了促进新的网路生成，便尝试藉由解除保护装置的STL来活化桐人的摇光。」

喘了一口气后，从操纵台桌面拿起矿泉水宝特瓶，润了一下因为不习惯长篇大论而干渴的嘴巴。

「为了进行这种治疗，必须让他潜行到Underworld里面。因为若是不让摇光像在现实世界里那样活动，治疗就不会有效果。因此我们在六本木的RATH分公司让桐人小弟潜行的同时，也封阻了他的记忆，让他降到Underworld的边境……原本应该是这样才对。虽然正确的原因仍未明朗，但恐怕是摇光损伤的影响吧，他的记忆没有受到封阻。桐人小弟还是以现实世界当中桐谷和人的身份被丢到Underworld里面。不过这是到刚才，他从内部与我们联络时才知道这一点……」

「等……等一下。」

这时插话的人是凛子。

「那他是以桐谷和人的身份，在时间经过加速的Underworld过生活了？内部……过了几个月了……？」

「……大约两年半。」

比嘉一这么回答，在凛子支撑下的明日奈就整个人震动了一下。这对她来说应该是相当大的冲击，但比嘉还是相信她刚才说的话，继续说明道：

「桐人在那个世界里和人工摇光们有了这么长时间的接触。而且应该是在知道现行模拟结束后，那些摇光都会被删除的情况下……所以他才会前往Underworld中心，找寻过去设置在起始村子里的，能与现实世界联络的操纵台吧。菊老大，他是为了要求你保全所有的人工摇光。」

比嘉稍微往旁边瞄了一眼，菊冈还是在眼镜反射萤光幕光线的情况下凝视著三次元图表。于是他又把视线移回凛子与明日奈身上。

「……那应该不是件容易的事。因为联络操纵台，目前放在被称为『公理教会』的统治组织的根据地里。隶属教会的摇光们能力值占绝对优势，不是应该被设定为一般人民的桐人所能对抗。本来入侵教会后，他立刻就会『死亡』，并且登出Underworld……但是──他却成功抵达了。因为遭受袭击，所以无法确认详细的纪录，但他似乎有好几名协力者，当然全都是人工摇光……也就是说他应该有同伴。在和教会的战争当中，他的同伴几乎全都死亡，结果就是成功打开联络我们的线路时，就产生强烈的自责感。换句话说，也就是自己攻击自己的摇光。刚好这个时候，那群全身黑的家伙又切断电源缆线，因为短路而发生的过电流让STL的输出瞬间上升。结果桐人小弟他自我破坏的冲动变成现实……让他的『自我』非活性化……」

「让自我……非活性化？这是什么意思？」

听见凛子的问题，比嘉再次转向操纵台。

「……请看一下这个。」

他迅速敲打键盘，把显示桐谷和人摇光活性的即时影像放大。

以不规则形状摇晃的彩色云中心部分，横跨著一片黑暗星云般虚无的小小黑暗。

「和LightCube里面的人工摇光不同，距离完全解析人类活体摇光的构造还有很长一段距离。但已经有了大致上的构造图。原本在这个黑色洞穴位置的『主体』……就是所谓的『Self-image』。」

「Self-image……就是自己规定的自我形象吗？」

「是的。我们要做出理性决策时，似乎是经由摇光中『自己在这样的状况下是否要这么做』的Y/N回路。比如说，凛子学姊曾经在牛肉盖饭的店里连续吃两碗盖饭吗？」

「……才没有。」

「连还想再吃，可以再吃一碗的念头都没有过？」

「嗯。」

「这也就是凛子学姊的自我形象电路处理的结果。同样的，几乎所有的理性决策，都得经过这个回路才会有实际行动。以桐人小弟的状况来看，大部分摇光都没有受到伤害。但刚才提到的回路没有发挥机能，所以无法处理外部的输入，也无法输出自发性的行动。现在的他……大概只能根据深刻的记忆做出反射性动作而已吧。比如说吃饭或者是睡觉这种程度的行为。」

凛子紧咬嘴唇，露出了思考的表情，最后用呢喃般的声音说：

「那么……他的意识目前究竟是处于什么样的状况？」

「……很遗憾……」

比嘉暂时停止发言，低头后才又继续表示：

「他不知道自己是谁，也不清楚要做什么事，当然也不会主动说话或者有所行动……这就是他目前的状况……」

微暗的空间第三度笼罩在寂静之下。

2

「……Fu……」

接下去的音节被坚固的战斗靴踢中钢板所发出的巨大声音掩盖。

身为突击小队一员的瓦沙克‧卡萨鲁斯似乎对墙壁只有一两个地方凹陷感到不满意，用力踩下几十分钟前还在这间控制室里的某个RATH技术人员掉落的一袋零食包装，然后才停止满嘴脏话。

他撩起显示西班牙裔血统的微卷黑发，粗鲁地移动到操纵台前面，单手抓住站在那里的男人衣领并把他抬了起来。

「你这家伙，再说一次看看。」

吊在瓦沙克宛如鞭子的柔韧右臂上的，是一名异常瘦削的年轻人。把金发剃成平头的他，肌肤就像生病般白皙。

凹陷的脸颊上戴著金属粗框眼镜的这个男人，是小队里唯一的非战斗人员。他是Glowgen Defense Systems的Cyber Operation（CYOP）部门的约聘骇客，名字叫作克里达。

他是曾经被逮捕的网路罪犯，名字也不是本名而是网路上的昵称。不过瓦沙克其实也是一样吧。Vassago是中世纪魔法书《哥迪亚》里记载的七十二名恶魔中的一名，据说是地狱的王子。世上当然不可能有父母亲会帮自己的儿子取这种名字。他也是CYOP部门的工作人员，不过专门领域不是电脑，而是实战──当然是在完全潜行环境下。这个男人见不得光的经历也不输给克里达，不过VR战斗能力的确相当杰出。

实际上──

O Turtle突击小队的十二名成员，除了队长加百列‧米勒之外全都有犯罪经验，公司是以保证能有新的身份来让他们甘愿沦为走狗。

身为其中一名走狗的克里达，即使被瓦沙克举在半空中也丝毫没有害怕的模样，只是一边大声嚼著口香糖一边反驳：

「要我说几次都没问题。听好了，这个操纵台上的锁就像干掉的狗大便一样硬，用带来的膝上型轻便电脑，就算计算到你老死了阿也没办法解锁啦。」

「这不是重点，你这个四眼田鸡！你这家伙竟然敢说是因为我们突击的速度太慢，才会让操纵台被锁住！」

针锋相对之下，瓦沙克也骂出相当难听的脏话。他是个拚命努力的话说不定就能当模特儿之类的粗犷帅哥，但生起气来的表情还是相当有威胁性。

「喂喂，我只是点出事实哟。」

「你这家伙战斗中明明躲在后面发抖，现在还敢说大话！」

其他队员也没有阻止两个人的争执，只是笑嘻嘻地在旁边看戏。等到两人吵得差不多了，加百列便啪叽一声弹响手指吸引两人注意。

「OK，就到此为止吧，两位。没有时间让你们在这里追究到底是谁的责任。得想想接下来要采取什么行动。」

结果转过头来的瓦沙克，像小孩子一样噘起嘴唇说：

「但是兄弟，不给这家伙一点颜色……」

加百列把「别叫我『兄弟』」这句话吞了回去。瓦沙克之所以会以兄弟来称呼加百列，似乎是因为承认他在一对一VR战斗上的实力，但这种称呼不论听几次都觉得相当别扭。对加百列来说，什么朋友、伙伴的，都只是基于感情的暧昧人际关系，实在无法了解这种东西有什么用。

将来得到抽出‧保存灵魂的技术时，应该就能够把人类所有的感情，按照「光之云」的色彩与形状等情报来做出完整分类吧。加百列一边这么想，一边以符合队长身份的口气对两人说明：

「听好了，瓦沙克、克里达。我对小队至今为止的表现相当满意。因为我们这边只有盖瑞受到一点擦伤，而且成功占领了第一目标的控制室。」

听到这里，瓦沙克才心不甘情不愿地放开克里达的衣领，把双手扠在腰部开口表示：

「但是兄弟，重要的控制系统被锁住的话就没意义啦。那个最终目标，叫什么LightCube Cluster的是在铁墙后面吧？」

「所以我才说现在开始想破坏这道墙的方法。」

「但是，自卫队（JSDF）那群家伙也不会一直躲著吧？只要护卫这只大乌龟的神盾舰派出职业战斗员然后冲进来，光靠我们这十一个人加一个拖油瓶实在没什么胜算。」

不愧是被加百列拔擢为副队长的男人，瓦沙克拥有普通走狗所没有的状况掌握能力。稍微思考了一下后，加百列轻轻耸了耸肩。

「看来我们的客户和JSDF的上层已经做了某种交易。神盾舰要在二十四小时后才会有所行动。」

「……吁～」

轻声吹了一下口哨的人是克里达。像护目镜一样的眼镜深处，淡灰色的眼睛眯了起来。

「也就是说，这次的行动不单纯只是强盗……不对不对，还是别乱说才能明哲保身。」

「我也这么认为。」

带著浅浅的微笑点了点头后，加百列再次环视了一下小队所有成员。

「好，那么确认一下状况。目前时间是日本标准时间十四点四十七分，突入后经过四十分钟。我们目前在O Turtle的主控室。虽然成攻占领目标设施，但没能捕获RATH技术人员，这里的系统也被锁上了。接下来的目标是占领副控室……布里克，可以切断隔板的耐压门吗？」

被点到名的巨汉队员慢慢走出来回答：

「有点困难。门是由最新的复合原料制成，我们带来的手提式圆锯机，不可能在二十四小时内把它切断。」

「日本人在这种地方果然舍得花钱。汉斯，那可以用C4把隔板炸开吗？」

这次换成嘴巴上的胡须修剪得非常整齐的高大队员，以洒脱的动作张开双臂。

「建议还是不要这么做。LightCube Cluster的收纳间就在隔板后面。无法保证在不伤到内容物的情况下把门炸开。」

「唔……」

加百列双手环胸，思考片刻后又继续说道：

「……我们承接的任务是从庞大的LightCube中，找出唯一一个目标物，然后把它和装置一起带回去。已经知道Cube的特定ID。也就是说，只要能操纵操控台，很容易就能搜寻出那个Cube并把它弹射出来。现在我们早就一只手拿著啤酒，坐在回家的船上了。」

「真是的，这个软弱的四眼田鸡，还吹牛皮说入侵过五角大厦的伺服器，结果连这么一个小小的锁都解不了～」

「哎呀，这真是吓死我了。竟然被一个只会用虚拟枪械的游戏玩家指责。」

瞪了一眼再次准备吵架的瓦沙克与克里达，加百列才加强语气说：

「你们想空手而回，拿不到奖金而被人嘲笑吗？」

「No！」

所有人一起大叫。

「你们是连那些一般技术人员都比不过的窝囊废吗？」

「No！」

「那就快点想！证明你们脖子上的容器除了燕麦片还有塞其他东西！」

加百列一边半自动地演出「坚强的指挥官」，一边在自己心里暗暗思考。

对身为灵魂探求者的加百列来说，入手人类首次创造出来的真正人工智慧「爱丽丝」以及独占Soul translation teology都是此行最大的目的。他已经先订好计划，入手这两者后就用偷偷带进来的神经瓦斯处理掉小队所有人，然后先逃到澳洲去。

但在前进到那个阶段之前，NSA委托的作战与加百列的目的可以说完全一致。在使用管理者的系统操作被封锁住的现在，一定得想办法以其他手段入手「爱丽丝」的Lightcube才行。

爱丽丝……「A.L.I.C.E.」。

把这个代号名称传达给加百列的客户NSA的，正是「RATH」内部的间谍。

客户没有提供间谍的个人资料。但是想到背叛组织并且泄漏机密的动机是巨额的金钱，就能知道在这种情况下，对方一定不会甘冒曝光的危险有所行动。

也就是说，无法期待耐压隔板后面的间谍能够提供任何协助。必须靠目前的情报与装备，在极短的时间内达成目的。

时间──问题是时间。

加百列虽然已经可以完全控制焦虑与不安等种种情绪，但是大约二十三小时后就要来临的时间限制，确实是给了他某种压迫感。

NSA的探员在委托这件极机密的抢夺任务时，曾经这么对加百列说过。

他们说RATH的活动，会给日本与军事产业相关的利益带来巨大的冲击。因此自卫队高层也不乐见RATH的存在──甚至还有不少积极想妨碍他们的势力。

RATH基本上是由年轻的干部自卫官所构成，而他们都缺乏政治上的力量。于是NSA看准这一点，透过在大使馆执勤的CIA职员，和海上自卫队的某高官缔结了密约。护卫RATH根据地O Turtle的神盾舰「长门」，在袭击开始的二十四小时内会以人质安全为优先这样的名目来保持待机。

但是待机时间结束之后，为了接下来的媒体应对就一定得让神盾舰展开行动。一旦完全武装的战斗人员攻入，加百列率领的袭击小队在人数与装备上都比不上对方，一定马上就会被歼灭。

就算真的演变成这种最糟糕的结局，自己也打算独自搭乘小型潜水艇离开。但是，没有入手最重要的LightCube，探求人类灵魂的旅程就会出现再也无法弥补的倒退。

加百列对于完成这次作战后的人生，也已经做好相当缜密的计划。

首先和爱丽丝一起逃到澳洲，然后把LightCube和STL技术隐藏在疏芬岛上的别墅。再搭飞机回圣地牙哥，向NSA报告作战失败了。等风头过了之后再回到澳洲，将STL机器设置在别墅广大的地下室，按照自己的喜好来构建假想世界。

世界一开始的居民应该只有爱丽丝与加百列而已吧。但那样实在太寂寞了。为了研究灵魂这个目的，必须增加更多的素材才行。

在雪梨与凯恩斯附近寻找年轻有活力的灵魂持有者，绑架他们后，利用STL把他们的灵魂抽取出来并把无用的躯壳处理掉。将来甚至还想跨越海洋，远征出生地美国以及完全潜行技术的发祥地日本。

日本的VR游戏玩家们独特的精神性让加百列深深为之著迷。虽然不是所有人，但一部分玩家的行为就像那里是比现实世界还要真实一般，而且也毫不吝啬地挥洒最真实的感情。每当想起在Gun Gale Online遇见的狙击手少女，就会感觉到这股永远是如此强烈的欲望正在蠢动。

这恐怕和过去那个国家里只存在两年的「Real Virtual World」也有关系吧。那些年轻人全都体验过被开发者骇入，并且赋予真正生与死属性的死亡游戏。跟没有这种经验的人比起来，那些「生还者」的灵魂拥有适合在假想世界里活动的特质。

如果可以的话，希望能尽量获得──而且是被称为「攻略组」的顶级玩家们的灵魂。虽然不知道那名狙击手少女是不是攻略组，但当然也想得到她的灵魂。封入这些灵魂的LightCube，一定会放射出比任何宝石都耀眼的光芒吧。

那是不论世界上的大富翁丢出再多美钞，都绝对无法入手的究极光芒。把这些LightCube排在秘密房间里，将任意选择的灵魂读取到喜欢的世界，完全按照自己的意思摆布他们。

最棒的是，从人类身上抽取出来封入LightCube的灵魂，可以自由自在地拷贝或者储存。到时候可以轻易地复原损毁或者扭曲的灵魂，把它改造成加百列喜欢的形状。简直就像是雕琢原石，让它散发出顶级光芒一样。

到了那个阶段，加百列漫长的旅程就能画出一个大大的圆并回归原点吧。

他将会回到幼年时期，在森林的大树下，看见爱丽西亚‧克林格曼的灵魂散发出美丽光芒的那个瞬间。

虽然只是极短暂的想像，但已经让加百列闭上眼睛，背部也开始微微震动。

当他再次睁开眼睛时，如冰一般的冷静思考力就已经恢复了。

如果各国年轻人的灵魂，像是围绕在皇冠周围的红、蓝宝石以及翡翠，那么镶嵌在中央的巨大钻石一定就是「爱丽丝」了。只有爱丽丝那没有任何污秽杂质的灵魂，才能够当加百列永远的伴侣。事到如今，无论如何都要发现并获得她的LightCube。

但是不破坏LightCube Cluster收纳间的耐压门，就不可能以物理手段夺取LightCube。

这么一来，就只能从这里操作系统了。只不过主控室的锁似乎连一流的电子罪犯克里达都束手无策。

加百列踏响靴子开始移动，来到双手手指在键盘上高速飞舞的克里达背后。

「怎么样？」

得到的回答是双掌朝上高高举起的动作。

「以管理者权限登入可以说绝望了。大概只能羡慕地看著收纳在上面Cluster里的摇光们过著快乐生活的梦幻王国吧。」

克里达动了一下手指，正面墙壁上的大萤幕就出现视窗，接著映照出奇妙的光景。

那根本不是「梦幻王国」的影像。天空是令人不愉快的红色，地面就像刚制造出来的柏油一样漆黑。

画面中央可以看见几顶只是将皮革缝合，外观看起来相当原始的帐篷。帐篷旁边聚集了十只左右矮胖秃头的奇妙生物，而且似乎正引起骚动。

大致上有人类的外型，但不管怎么看都绝对不是人类。驼背的程度相当严重，手臂也长到几乎要拖地，相对的弯曲的脚则相当短。

「哥布林……？」

加百列一这么呢喃，克里达就轻轻吹了一声口哨，然后发出很高兴般的声音：

「哦，队长很清楚嘛。没错，看起来不像半兽人或食人鬼，所以应该是哥布林吧。」

「但以哥布林来说好像有点太大了。这应该是大地精吧。」

来到旁边的瓦沙克双手扠腰加了这样的意见。专长是VR战斗的他，似乎拥有一定程度的奇幻系RPG知识。

在加百列等人注视的前方，十几只大地精的骚动越来越是激烈。中央的两只互相抓住对方，用力地扭打在一起，在四周围观的家伙也高举双手不停吼叫著。

「……克里达。」

加百列一边感觉某个想法在心里慢慢成形，一边对坐在椅子上的平头男搭话。

「什么事？」

「这些家伙……应该说这些怪物是系统的一部分吗？」

插图010

「嗯～好像不是。这些家伙在某种意义上也是人类。拥有被读取到上面LightCube Cluster里的人造灵魂……也就是摇光。」

「真的假的！竟然有这种事！」

瓦沙克立刻发出大吃一惊的声音并探出身子。

「这些大地精是人类？和我一样拥有灵魂？弗里斯科的祖母听见的话一定会当场吓死！」

他啪啪拍著克里达的平头，继续叫道：

「竟然敢从事这种不怕遭天谴的研究。被收藏在LightCube里面的，不会全都是像这种哥布林或者半兽人吧？该不会连我们的小爱丽丝也是这样？」

「怎么可能。」

克里达像是感到很厌烦般把瓦沙克的手拨开，然后订正他的说法：

「听好了，RATH那些家伙所制作的Underworld，可以分为两个世界。中间偏西的是『Human Empire（人界）』，在那里生活的都是普通人类。然后人界外侧的『Dark Territory（黑暗领域）』则有一大堆像这样的怪物。爱丽丝当然是在人界的某个地方，但范围实在太广了，像这样在外面窥看根本不可能把她找出来。」

「那还不简单。只要是人类，应该就能用语言沟通吧？那我们就潜入这个叫什么人界的地方，找附近的人问『认不认识叫爱丽丝的女孩』不就得了？」

「呜哇，有个笨蛋。有个笨蛋在这里喔。」

「你说什么！」

「我说啊，制作Underworld的可是日本人耶。当然『附近的人』使用的一定是日文。你这家伙会说日文吗？」

面对露出轻视的微笑来如此诘问的克里达，瓦沙克带著有点扭曲的笑容回答：

「你可别小看我啊。」

一瞬间，不只是克里达，小队所有人员都瞪大了眼睛。因为瓦沙克所说的，是连加百列都大吃一惊的流畅日文。

带有西班牙血统的年轻人恢复成英文继续说道：

「沟通完全没有问题喔。四眼田鸡小弟，你还有什么话想说吗？」

「当……当然有了。」

从惊讶当中恢复过来的克里达随即用鼻子冷哼了一声。

「人界里有几万个居民在生活。你自己一个人，能够打探出什么消息……吗…………」

话刚说到这里，克里达就像是从自己的话里得到灵感，迅速撑起身体。被平头重重撞击下巴的瓦沙克又再次咒骂起来，但骇客根本不理会他，自顾自地大叫：

「等等。等一下、等一下。或许不用自己一个人调查……」

一听见他这么说，加百列脑袋里暧味的想法也开始收敛成初步的形状。

「……对喔。登入到Underworld的备用帐号……不可能全都是等级1的一般市民。我说的没错吧，克里达？」

「Yes。Yes，boss！」

键盘像打击乐器般发出喀哒喀哒的声音，接著立刻有几份名单在大萤幕上卷动。

「如果是给RATH的操纵人员登入到内部观察或者操作的帐号，应该准备了所有阶级的身份才对。军队的军官……不对，将军……不对不对，贵族、皇族……甚至是皇帝本人……」

「喔喔，那真是太酷了。」

瓦沙克一边摸著破皮的下巴一边这么表示。

「也就是说，以什么大将军、大统领的伟大身份登入，然后随心所欲地发出命令就可以了。全军整队！向右转！把爱丽丝给我找出来！大概就像这样吧。」

「……不知道为什么，被你这么一说，难得想到的好点子就变得很无聊了。」

克里达嘴里虽然这么抱怨，但还是用猛烈的速度卷动著名单。

只不过……

短短几秒钟后，名单的卷动就随著这名男人很少会说出口的咒骂声停止。

「可恶，不行吗？不只是这里的直接操作，连高等级帐号的登入也被加上密码了。很可惜，似乎只能用一般市民帐号潜行到人界。」

「……唔……」

克里达与瓦沙克的脸上出现明显沮丧的神色，但加百列的表情完全没有变化，只是微微歪著脖子。

剩下来的时间绝对不能算多。

但那只不过是设定在这个现实世界里的时间限制。在萤幕当中的一大片异世界Underworld里，时间是以比现实世界压缩了数百倍这样惊人的比例在流动。

换句话说，就是剩下来的二十三个小时，在Underworld里相当于超过一整年的岁月。有这么长一段时间，以一般市民的身份登入，找到并捕获爱丽丝，再由内部的情报操纵台让她弹射到现实世界也不是完全不可能。

但这的确是相当冗长的一段程序。要花这么长一段时间的话，倒不如直接从人界外侧接近可能还比较快。

「克里达，人界外面……黑暗领域里没有准备高等级的帐号吗？」

「……外面？但爱丽丝在那里的可能性相当低喔。」

即使嘴里说出这样的疑问，克里达的手指还是轻快地动了起来。

加百列一边抬头看著新出现的视窗，一边回答：

「嗯，我想也是。但区域境界线并不是完全不可侵犯吧？根据帐号被赋予的权限，说不定会有越过境界的手段。」

「喔喔，不愧是兄弟！想法果然和我们不同！你的意思是……不以人类将军的身份，而是做为众怪物的大将攻进人界对吧！这样才更让人热血沸腾啊！」

瓦沙克「咻」一声吹了一下口哨并且大叫，这时克里达以「你实在很烦」般的口气泼了他一盆冷水。

「你要热血沸腾我是管不著啦，但登入黑暗领域的话，就有可能是大地精或者是半兽人喔。嗯，虽然是很适合你这家伙……哎呀，哦，有了，找到了～」

他「哒」一声用力按下键盘，接著又有两个视窗浮现出来。

「嗯……和人界这一边不同，黑暗领域里只有两个超级帐号……太好了，没有锁密码！我看看……首先是名为暗黑骑士的身份，权限等级是……70！这绝对能派上用场！」

「喔喔，太好了，这个帐号就给我使用吧！」

无视大叫的瓦沙克，克里达又点出另一个视窗。

「然后另一个是……这是什么？身份是空栏位，也没有标示等级。只有设定名字而已。这家伙……要怎么念？……『Emperor……vector』？」

「呜哦，Emperor不就是皇帝吗？我看我还是用这个……」

瓦沙克说到这里，加百列就从后面轻轻拍了一下他的肩膀。

「等等，这个帐号就由我来使用吧。」

「咦？但是兄弟你会说日文吗？」

「没有你那么流利啦。」

这时加百列用学了三年的日文来回答他。虽然一开始就放弃了读与写的能力，但是对于日常生活中的对话则相当有自信。

「哇，不愧是兄弟。那皇帝就交给你，我来当暗黑骑士吧。事情越来越有趣了！喂，四眼田鸡，已经可以登入了吗？」

完全无视依然相当吵闹的瓦沙克，克里达只是持续敲打著键盘。萤幕上不断有情报出现，瞪著这些情报的他侧脸看起来相当认真，加百列走到他身边，以平静的声音问道：

「怎么了，克里达，其他还有什么问题吗？」

「…………不知道该说是问题还是有点在意……我看了一下档案，发现到处都有一个奇妙的名词出现。还不太清楚是什么意思就是了……」

「哦？什么名词？」

克里达吸了口气后，才回答加百列的问题：

「……『最终负荷实验』。」

3

比嘉以有些顾忌的口气，打破了包围副控室的沉默。

「嗯……那个……他的肉体，或者应该说现实世界里桐人小弟的状况呢，就像我刚才说明过的……绝对不乐观。」

看见被神代凛子抱住肩膀的结城明日奈纤细的身体震动了一下，他才急忙又加了一句：

「但……但还是有一点点希望！」

「……你的意思是？」

凛子以尖锐，但是有点像在祈祷的声音这么问道。

「桐人小弟依然持续著登入Underworld的状态。」

比嘉抬头看著比被夺走的主控室还要小很多的萤幕画面。击点数次滑鼠来切换显示，把由圆形的人界，以及包围它的黑暗领域所构成的Underworld整体地图叫出来。

「也就是说，自我形象虽然有所损伤，但他的摇光依然在活动，接受各式各样的刺激。这样的话，就算现实世界没有办法，或许可以从Underworld来治愈他的灵魂。只要某个人『宽恕』了他因为过于自责而自行损毁的灵魂……说不定就……」

比嘉也知道自己所说的话一点科学根据都没有。

但这的的确确是他的真心话。

Soul translator是NERvGear、Medicuboid等Brain Mae Interface不断进化后的成果。比嘉本身也参与开发的这台机器，虽然发现到人类的量子意识体「摇光」，但是关于摇光依然有许多谜团存在。

摇光算是物理现象吗？

还是现代科学无法说明的，纯概念的事象呢？

如果是后者，那么超越科学的力量，说不定也能治愈桐谷和人受了伤又筋疲力尽的灵魂。比如说──某个人的爱。

「……我愿意去。」

简直就像是跟比嘉的思考同步一样。

副控室里响起一道细微但是毅然的声音。

房间里的人全都屏住呼吸看向发话者。结城明日奈对撑住自己的神代凛子点了点头，向前走出一步后又重复说了一遍：

「我愿意到Underworld去。我想在那边跟桐人说『你真的很努力』。还有『虽然发生许多悲伤、痛苦的事情，但是你已经尽全力了』。」

明日奈淡茶色眼睛里噙著泪水还是这么说著的模样，美丽到连决定把一生奉献给科学的比嘉都说不出话来。

菊冈也以深受感动的表情看著明日奈，但马上就用眼镜的镜片遮住感情，把视线朝临室的门口移去。

「……确实还有一台无人使用的STL。」

静静地如此宣告的指挥官，这时露出复杂的表情继续表示：

「但Underworld目前的状况绝称不上平静。我们这边的时间再过几个小时后，就要开始进人预定实行的最终负荷实验的最后阶段了。」

「最终……负荷？会发生什么事？」

比嘉带著手势向皱起眉头的凛子说明道：

「嗯……简单来说，就是壳会破掉。数百年来分隔人界与黑暗领域的『东大门』耐久值将归零，怪物组成的军队会大举入侵人类世界。如果人类有充分的防御体制，最后就能够击退怪物的攻击。但这次的实验前，身为统治组织的公理教会已经被桐人小弟毁掉一半了……所以结果如何还很难说……」

「仔细一想，目前确实是我们之中一定要有人潜行到Underworld的状况。」

菊冈双手抱胸继续呢喃道：

「开始侵略的话，应该在人界某个地方的『爱丽丝』也有可能在混乱中遭到杀害。这样的话，封锁主控室来争取时间就变得没有意义了……如果可以利用高级帐号登入到里面，一面保护爱丽丝一面移动到『世界尽头的祭坛』，然后从那里把爱丽丝的LightCube弹射到这间副控室的话……」

「嗯……在发生事故之前，你也拜托桐人这么做对吧。」

凛子的话让菊冈很悔恨地点了点头。

「嗯。如果他平安无事，一定会顺利完成任务。因为那个时候爱丽丝就在他身边……」

「这样的话，就算现在内部时间已经过了好几个月，两个人依然在一起的可能性还是很大……是这样吗？」

比嘉回答了这个问题：

「……我想应该是这样。这样的话，可能真的应该由明日奈小姐来负责潜行……和桐人小弟之间的沟通能力就不用说了，想保护爱丽丝的话就需要在Underworld的战斗能力。在这里的人里面，最习惯假想世界动作的无疑就是明日奈小姐了。」

「这样的话，尽可能使用等级高一点的帐号比较好。」

点头同意菊冈的发言后，比嘉的手指就在键盘上敲打了起来。

「那真是应有尽有了。不论是骑士、将军还是贵族……有各式各样的高级帐号可以选择。」

「等一下。」

凛子忽然以有些紧张的口气插话。

「怎么了？」

「……袭击这里的家伙会不会想到同样的事情？你刚才也说过吧？确保爱丽丝的捷径，就是从内部进行操作。」

「嗯……是啊，那些家伙的确也可以这么做。因为下面的主控室里也有两台STL。只不过，那些家伙没有时间破解登入高级帐号的密码。能使用的就只有等级1的一般民众。那种能力值不太可能在最终负荷试验的严苛环境里活动。」

虽然迅速一边这么说明──

但比嘉一瞬间还是意识到是不是忘记什么事情的些许不安。

不过这样的想法在高速卷动的一大串帐号名单文字列影响下没有正式成形。

** 第十七章 黑暗领域 人界历三八〇年十一月

「RATH」是为了Bottom-up型人工智慧开发计划「Project Alicization」而伪造出来的企业，而自走式巨大人工母船「O Turtle」就是其根据地。

巨大金字塔型的该处，存在为了登入「Underworld」的「Soul translator」，在第一STL室里有两台，第二STL室里也有两台，总计有四台。桐人登入「Underworld」的「Soul translator」设置在第二STL室当中。

「O Turtle」的中心有保存「Underworld」众多居民的灵魂，也就是人工摇光的「LightCube Cluster」存在。

加百列等人的任务就是从庞大的LightCube群当中，找出爱丽丝的人工摇光并让它从空气管弹射出来。

1

暗黑骑士莉琵雅‧扎恩克尔在飞龙停止动作前就从它背上跳了下来，开始在联结起降台与帝宫之间的空中回廊上全力冲刺。

马上感觉呼吸困难的她，用右手脱下覆盖整个脸部的头盔。

莉琵雅又用左手将啪沙一声散开来的灰蓝色长发全部理回背后，然后继续加快速度。虽然想脱掉沉重的铠甲与披风，但还是不想让在帝宫里肆虐的执政官们看见自己任何一点肌肤。

急奔过弯曲的回廊，从竖立在右手边的圆柱缝隙中，露出了撕裂红色天空后耸立在该处的黑色巨城。

帝宫黑曜岩城是花了一百年的时间，挖开广大无边的暗之国里最高的──当然，不包含不祥的「尽头山脉」在内──岩山后建筑而成的城堡。

据说从最上层的「皇座之间」，可以看见微微浮现在西方地平线的尽头山脉，以及贯穿山脉岩壁的巨门。

但是没有人知道这个传说的真实性。

自从初代皇帝暗黑神贝库达在久远前的太古时代回归地底的黑暗之后，暗之国的皇座就一直没有主人。最上层的大门被拥有无限天命的锁炼封印，永远没办法打开。

莉琵雅硬是把视线从漆黑城堡的最上层移开后，对著近在眼前的守门食人鬼族卫兵大叫：

「我是暗黑骑士第十一位，扎恩克尔。快点开门！」

狼头人身的卫兵们虽然壮实，但脑袋有点驽钝，在莉琵雅快到铸铁大门前才终于开始旋转开关装置的把手。

门随著「轰、轰」的沉重声打开一条细缝时，莉琵雅就侧身穿了过去。

隔了三个月才回来的城堡，还是用跟以前一样的刺骨冷空气来迎接她。

打杂的狗头人每天都鲁直地把走廊擦过一遍，所以上面看不见任何灰尘。让鞋底在黑曜石地板上踩出喀喀声跑了一阵子后，就看到前方衣不蔽体的两名妖艳女性像在滑行般无声地往她靠近。

光润的波浪状头发上那顶大大的尖帽子，显示出她们是暗黑术师。看都不看她们准备擦身而过时，其中一名女性故意以尖锐的声音说：

「哎呀～地震了吗！不会是半兽人之类的怪物跑过来了吧！」

另一名女性立刻发出高亢的笑声回答：

「不是吧，照这种摇晃的程度来看，应该是巨人才对！」

──如果不是在禁止拔剑的城内，一定要把她们的舌头切下来。

莉琵雅心里虽然这么想，但只是用鼻子冷哼了一声就一口气跑了过去。

出生在暗之国的人族女性，训练学校毕业之后大部分都是加入暗黑术师公会。那是一个极重享乐的组织，上层下达的指示是「忘掉规律，学习放浪」，结果就是出现刚才那样，尽是一些只对打扮自己有兴趣的家伙。

自己明明是那副德性，却对选择了骑士道的女性有很强烈的对抗心。莉琵雅在幼年学校时，也曾经被同期交恶的女术师下了毒虫诅咒而不知道该怎么办。不过用剑把她自豪的辫子砍掉后，对方就变得乖多了。

反正这个国家里的人民，尽是一些没有前瞻性的笨蛋。

组织以及个人都经常发生争执，只会靠力量来决定优劣的暗之国根本没有未来可言。目前虽然藉由「十侯会议」保持了随时可能崩坏的平衡，但这样的状态不可能持续太久。和人界──半兽人与哥布林称为「伊武姆之国」之间的战争已经近在眼前，十侯当中有任何人在这场战争中丧命的话，均衡立刻会崩毁，腥风血雨的乱世将再度来临。

对莉琵雅诉说这种未来的，是十侯的其中一人，也就是她的直属长官暗黑骑士团团长，同时也是她心爱的男人。

而莉琵雅现在，心中带著他期盼已久的机密情报。

这个时候，已经没有空去理那些女术师所说的蠢话了。

一直线横越过无人的大厅后，她每一步都直接踩过两阶的大楼梯不停往上爬。经过锻炼的身体开始上气不接下气时，终于抵达目标的楼层。

藉由合议来治理暗之国全土的「十侯会议」里，人族占了五席，哥布林族两席，剩下的三席分别属于半兽人族、食人鬼族以及巨人族的首领。经过长达百年的内乱后终于缔结了算是条约的东西，交换了五族之间不分上下的约定。

因此靠近黑曜岩城最上层的十八楼里，设置了分属于十名诸侯的私人房间。稍微压底脚步声来跑过走廊的莉琵雅，用右手背在最深处一间房间的门上敲了三下。

「进来。」

立刻有低沉的声音做出回应。

看了一下走廊的左右两侧，确定四下无人后，莉琵雅迅速钻进门后面。

她一边对于将装饰物减到最少的房间里飘散的那股男人味感到怀念，一边单膝跪地并低下头来。

「骑士莉琵雅‧扎恩克尔，现在回到城堡里来了。」

「辛苦了。先坐下吧。」

莉琵雅在意识到因为浑厚的声音感到兴奋的情况下抬起视线。

那名稳稳坐在圆桌后方其中一张躺椅上，并高高翘著脚的男人，正是暗黑骑士长──别名「暗黑将军」的毕库斯鲁‧乌鲁‧夏斯达。

他有著以人族来说相当魁梧的躯体。宽度虽然不及，但光看身高的话绝对不输给食人鬼族。漆黑的头发剪得相当短，嘴角的胡须也修剪得十分整齐。

简素的麻质衬衫因为像是快要把钮扣弹飞般的强壮肌肉而高高隆起，但腰部周围却看不到一丝赘肉。很少有人知道，看起来完全不像超过四十岁的完美肉体，是藉由即使爬上骑士最高位也绝不松懈的严苛日常锻炼来维持。

隔了三个月才看见朝思暮想的人，让莉琵雅只能压抑立刻想扑进他怀里的冲动，并坐到夏斯达对面的沙发上。

撑起上半身的夏斯达，把放在桌上的两只水晶杯其中一只交给莉琵雅，接著打开看起相当有年份的红酒。

「因为想和你一起喝，所以昨天就从宝物库里把它偷出来了。」

夏斯达闭起一只眼睛，把带有浓香的深红色液体倒进玻璃杯。跟以前一样，他一做出这种表情，看起来就像是喜欢恶作剧的小孩子。

「谢……谢谢您，阁下。」

「说过好几次了，只有我们两个人的时候别这样称呼我。」

「但目前也算是在勤务当中。」

和像要表示「真拿你没办法」而耸了耸肩的夏斯达轻声互碰一下杯子后，就一口气喝下芳醇的红酒，让她顿时感觉因为长途旅行而消耗的天命正慢慢恢复。

「……那么……」

也喝光自己杯子里的酒后，恢复严肃表情的骑士长稍微压低声音问道：

「你派遣使魔通知我说有重要消息，内容究竟为何？」

「是的……」

莉琵雅的视线往左右一扫，接著探出身子。夏斯达虽然是个豪放磊落的男子汉，但他同时也相当细心。这间房间里设下了好几重防御术，就算是暗黑术师公会总长的那个「魔女」也没办法窃听才对。但就算知道这个事实，只要一想到自己得知的重大情报，就不由得压低声音。在夏斯达黑色眼睛凝视下，莉琵雅开始了简洁的报告：

「人界的公理教会最高司祭……丧命了。」

下一个瞬间，就连暗黑将军也忍不住瞪大了眼睛。

「呼──」一声浑厚的叹息打破了沉默。

「询问这个消息的真伪……只是侮辱了你。虽然不怀疑情报的真实性……但是……那个不死者真的……」

「是的……我了解您的心情。我也无法马上相信，整整花了一周的时间确认消息的真伪，但果然没有错。我让『耳虫』潜伏到中央圣堂，取得了实证。」

「你竟然做出这么危险的事。要是被顺著术式追踪，你根本就没办法离开央都，直接会被五马分尸了。」

「是的。但连我这种程度的术式都无法探知，更加证明了情报的真实性。」

「……唔……」

稍微呷了一口第二杯红酒，夏斯达低下刚毅的脸庞。

「那是什么时候的事情。还有，死因是？」

「大约是半年前……」

「半年。那个时候山脉的警戒的确暂时变得比较松懈。」

「是的。至于最高司祭的死因……这虽然有点难以置信，但据说是被剑所杀……」

「被剑杀死了──你是说有人用剑杀了那个不死者？」

「怎么可能。」

莉琵雅对顿时说不出话来的夏斯达用力摇了摇头。

「虽说是不死者，但我想应该是她的天命终于到了尽头。但为了保持最高司祭身为神明的灵性，才会说出这样的藉口……」

「唔……嗯，应该是这样吧。不过……最高司祭亚多米尼史特蕾达终于死了吗……」

夏斯达闭上双眼双手环胸，把上半身靠在椅背上。

他就这样默默思考了很长一段时间，最后才随著简短的一句话迅速睁开眼睛。

「机会来了。」

莉琵雅暂时屏住呼吸，接著用沙哑的声音问道：

「什么机会呢？」

她立刻得到答案。

「当然……是和平的机会。」

在这座城里算是极度危险的名词，迅速溶解、消失在房间的空气中。

「阁下……您认为有这种可能吗？」

面对莉琵雅低声询问，夏斯达看著玻璃杯中红色的液体，一边缓慢但用力地点了点头。

「不管可不可能，无论如何都要成功。」

他一口气喝干红酒，接著说道：

「从创世时代就一直分隔人界与暗之国的『大门』，天命终于快要耗尽。黑暗之国五大种族的军队，看见马上有机会一举入侵充满阳光与地力恩宠的富饶人界，目前已经像是煮沸的热锅了。上一次的十侯会议里，如何分配人界的土地、财宝以及奴隶已经引起很大的纷争。真是受不了……那群家伙的欲望就像是无底深渊。」

夏斯达毫无忌讳的发言，让莉琵雅缩起了脖子。

和被「禁忌目录」这一大册法典所支配的人界不同，暗之国只存在一条法律。也就是──靠力量夺取一切。

从这一点来看，跟即使爬上最高权力的宝座还是拥有无尽征服欲的其他九名诸侯比起来，考虑与人界和平共处的夏斯达才是异端分子吧。

但莉琵雅之所以会被这个男人强烈地吸引，也是因为这种异质的思考。和伺候其他诸侯的女人不同，莉琵雅并非他以强硬手段抢夺而来。夏斯达是拿著花朵对莉琵雅下跪，以真挚的言语向她求爱。

没有注意到爱人心中飘荡著这样的想法，夏斯达以沉重的口气继续表示：

「……但是，那些诸侯太小看人类了。尤其是这漫长的三百年来一直守护著人界的整合骑士团。」

一听见这个名词，莉琵雅就在脑袋即刻发冷的情况下点了点头。

「确实……那些家伙都是技艺超群的剑士。」

「真的可以说是一骑当千。在暗黑骑士团的漫长历史里，被整合骑士所杀的暗黑骑士可以说是不计其数，但反过来的情况是一次都没有。那些家伙的剑技不但精妙，连身上的神器也是强力无比……虽然我也曾数次把他们逼入绝境，但终究没能给予最后一击。当然，败走的经验已经数也数不清了。」

「那是因为……那些家伙会使用奇怪的术法，让剑放出火焰或者光束的缘故……」

「你说『武装完全支配术』吗？虽然也让我们骑士团的术理部研究了很长一段时间，最后还是无法解开这个谜团。即使派出一百名哥布林士兵，也无法抵挡那个技法。」

「但是……我方的军势多达五万。另一方面，整合骑士则只有三十人左右。应该能以数量压倒对方吧……？」

莉琵雅的话，让夏斯达蓄著美髯的嘴角扬起讽刺的微笑。

「刚才说过那些家伙是一骑当千吧。这样算起来，我们也有三万名上兵会丧命。」

「真的……会有如此严重的损伤吗？」

「嗯。虽然不喜欢这种战法，但前方战线由我们骑士团和食人鬼、巨人来支撑，然后暗黑术师群从后方持续施放远距离术的话，整合骑士终究会筋疲力尽吧。但当他们最后一骑倒下时，很难想像我们已经遭受多少损害。虽说可能不到三万，一万五千的话倒是很有可能。」

水晶杯发出「叮」一声清脆的声音后被放到桌上。

单手制止准备帮忙倒酒的莉琵雅，夏斯达把宽阔的背部靠到躺椅上。

「……而这样的结果，当然就是会让暗之五族的力量产生不平衡。十侯会议将丧失意义，五族平等的约定形同虚设。到那个时候，一百年前的『铁血时代』又将来临。不对，应该会比当时更惨。因为这次通往人界，有著饮不尽蜜汁大海的大门已经打开了。光是一百年的时间，还无法摆平争夺那块土地的支配权所造成的纷争……」

这正是夏斯达过去所戒慎恐惧，而且忍不住向莉琵雅重复说过好几次的最糟糕事态。而夏斯达以外的诸侯，都不认为这是最糟的未来──反而等不及那一刻来临了。

莉琵雅低下头来，凝视著叙任为骑士时得到的这套铠甲上，虽然满是伤痕但是擦得相当仔细的黑色光辉。

孩提时期相当矮小的莉琵雅，如果是在「铁血时代」，一定无法成为骑士吧。不是被以奴隶的身份卖给人口贩子，就是被丢在荒郊野外，然后就此结束短暂的一生。

但多亏订立了那个类似和平条约的东西，让她没有被卖到奴隶市场，而是进入幼年学校，结果在那里发现她大器晚成的剑术才能，因此获得就人族女性来说几乎是不可能的最高地位。

目前暗之国的穷乡僻壤依然有许多人口贩子横行，成为骑士之后，她就投入每个月的绝大部分薪水，从这些地方聚集被父母亲丢弃的孩童，并且营运类似育幼院的机构保护他们到进入学校为止的年纪。

这件事情她当然没有告诉过自己的同辈，甚至连夏斯达也不知道。因为连她本身也不清楚自己为什么会有这样的举动。

只不过──

莉琵雅内心的角落，一直感觉这个有力量者就能夺走一切的国家某个地方错了。和夏斯达不同，她没有能够明确表达出内心疑念的智慧，但就算是这样，她还是觉得这个国家──不对，应该是包含人界在内的整个地底世界都存在「更加正确的模样」。

莉琵雅隐约理解到，那个所谓的新世界，应该就存在于夏斯达提倡的和平国度的遥远前方。同时身为一个女人，她也想帮忙自己心爱的男性。

只不过……

「……但是，阁下打算如何说服其他诸侯呢？更何况……整合骑士团真的会接受和平的交涉吗？」

莉琵雅低声这么问道。

「……唔……」

夏斯达闭上双眼，以右手捻著光艳的胡须。最后才用苦涩的声音隐密地说著：

「我认为整合骑士那边应该有机会。如果最高司祭已经死亡，那么目前的总指挥大概是贝尔库利那个老头吧。那个男人虽然狡狯，但可以沟通。问题……果然还是出在十侯会议上。这一边的话……虽然有点矛盾……」

夏斯达张开眼睛，以隐藏著杀气的双眸注视著空中。

「──最少可能得干掉四个人。」

莉琵雅瞬间屏住呼吸，畏畏缩缩地问：

「您说的四个人……指的是两名哥布林族首领、半兽人族首领，以及……」

「暗黑术师公会总长。因为那个女人带有入手亚多米尼史特蕾达不死的秘密，将来自称皇帝的野心。所以应该不会接受和平的提议。」

「但……但是！」

莉琵雅挤出声音来反驳：

「这样实在太危险了，阁下！哥布林、半兽人的首领应该不是阁下的对手……但那个暗黑术师不知道会用什么奇怪的术式啊！」

即使莉琵雅闭上嘴巴，夏斯达还是沉默了好一阵子。

忽然开口的他，从嘴里说出令人意想不到的发言：

「莉琵雅啊。你到我麾下有多久的时间了？」

「什么？啊……呃，嗯……是从我二十一岁的时候开始……应该有四年了。」

「已经过这么久了吗？抱歉这么长一段时间都让你的身份处于暧味状态。怎么样……差不多该那个……」

视线到处游移用力搔了搔头后，暗黑骑士长才有些生硬地说：

「……要不要正式嫁给我？虽然要你委身于我这种大叔有点委屈你就是了……」

「阁……阁下……」

莉琵雅哑然瞪大双眼──

接著心脏附近有一道暖流扩散开来，让她忍不住想立刻飞越桌子，扑进心爱男人的怀抱里，但就在这个时候……

厚重的门后面，传出紧绷的尖锐声响。

「不得了了！不得了了！啊啊，竟然有这种事！诸侯大人们快点……快点出来啊！」

觉得有些熟悉的声音，是来自十侯其中一人，商工公会的头领。

莉琵雅的记忆当中，他有一副俨然是大人物的肥胖体格，但这时完全不符合这种形象的沙哑悲鸣还是持续叫著：

「不得了了！──皇……皇座之间！封印的锁炼！正在震动啊啊啊啊啊！」

2

以皇帝贝库达身份降到皇座之间的加百列‧米勒，带著某种感慨眺望著低头跪在自己脚下的人工摇光们。

他们是被封在一边两英吋的LightCube里头的光量子情报。在这个世界里，他们就是具备知性与灵魂的真正人类。只不过，跪在最前排的十个人里，有半数是容貌诡异的怪物就是了。

自称「诸侯」的十名将军，排在他们身后的骑士与术师们，以及屯驻在城外的五万军队，就是加百列所能掌握的战力。接下来他必须确切地操纵这些棋子，歼灭人界的防卫力并捕获「爱丽丝」。

但是这里和现实世界的即时模拟战略游戏不同，这些棋子不能够随心所欲地以滑鼠或者键盘来移动。必须以言语以及态度加以统率与施加命令。

加百列默默从皇座上站起来，移动几步后，看向贴在后方墙壁上的一面镜子。

映照在上面的，是穿著低俗品味服装的自己。

只有容貌与接近白色的金发依然是现实世界的加百列。但额头上戴著以黑色金属制成，上面镶有深红宝石的皇冠，另外在黑色合成皮革般的皮革衬衫与长裤上，还披著豪华深黑色毛皮长袍。腰上挂著一把散发出朦胧磷光的细细长剑，靴子与手套上都绣著精致银线的刺绣。背上甚至还有一件染了鲜血般的红色长披风。

把视线往右边移动，就能看见皇座往下一阶的位置上，有一名骑士正把双手交叉在脑袋后面四处张望著。

那套如同宝石一般发光的深紫色全身铠甲，主人正是和加百列一同登入到Underworld的瓦沙克‧卡萨鲁斯。虽然已经警告过他，在掌握状况前别得意忘形说出多余的话，但他还是露出极想用俗语表达心中感动的模样，而且还不停用指尖弹出喀哒喀哒的声音。

加百列轻轻摇了摇头，再次把视线移回镜子里的自己身上。

穿惯订制西装的他，实在无法习惯自己的这种模样。但在这个「Underworld」里，加百列已经不是民间军事公司的首席技术长（CTO）。

他是统领广大黑暗领域的皇帝。

而且还是神明。

加百列闭上双眼，深吸了一口气将其呼出。

把扮演的角色由坚强、冷酷的指挥官转变成无情皇帝的开关，已经在他意识里的某个地方被按了下去。

睁开双眼，啪一声翻转深红披风转过身子的加百列──暗黑神贝库达，一面睥睨十名将军，一面让毫无人类味道的声音响彻在皇座之间里。

「抬起头来，报上你们的姓名吧──就从最右边的你开始。」

一名体型肥胖，差点要把额头贴在地板上的中年男子，以出乎意料之外敏捷的动作撑起上半身后，就用流畅的日文报上自己的姓名：

「遵……遵命！我是担任商工公会头领的连基尔‧奇拉‧司科波！」

中年男子再次低头后，旁边宛如小山一般的巨大身躯就开始动了起来。

站起身后应该有十二英呎（三公尺半）的雄伟身躯上交叉缠著发出黑油油亮光的锁炼，腰间盖著兽皮的亚人，这时迅速抬起特别长的鼻梁，以地鸣般的低音报出姓名：

「巨人族首领，西古罗西古。」

当加百列细细咀嚼这个怪物身体里也存在知性与灵魂的事实时，第三个人刺耳的沙哑声音已经响起。

「……暗杀者公会头领……夫萨……」

跟旁边的巨人族比起来过于瘦削且没有存在感的套头长袍模样，让人连他的年龄与性别都无法判别。

加百列虽然一瞬间考虑过命令他露出面貌，但想到像这种暗杀者似乎都有不能以真面目示人之类的禁忌，于是就打消了念头，直接把视线移到下一位将军身上。

下一刻，他的眉毛差点就要皱起来，但还是忍住了。

确实体现了丑恶这个形容词的存在，就这样笨重地坐在地上。因为脚太短了根本无法用膝盖撑起身体。圆滚滚的大肚子上有闪亮亮的油光，一半埋在肩膀里的脖子上还挂著几个应该是小动物头骨的物体。

上面的头部应该说三分像人，七分像猪。有著往前凸出的扁平鼻子、牙齿外露的大嘴，不过小小的眼睛倒是闪烁著带有人类知性的光芒，但这也让他看起来更加恐怖。

「半兽人族首领～利鲁匹林～」

听见那道尖锐的声音后，加百列就想著这家伙究竟是男是女，但这次也马上就抛弃这样的念头。既然自称是半兽人，那就只是低等部队。反正只是用完就丢的家伙。

接著抬起头以灵敏动作行了个礼的，是一个年纪仍可以说是少年的年轻人。头上垂著金红色卷发，晒得黝黑的上半身只缠著皮带。下半身则是紧身皮裤与凉鞋，另外双手上还戴著附有四方形金属铆钉的手套。

「拳斗士公会第十代冠军，伊斯卡恩！」

加百列回看著少年充满干劲大叫的模样，接著在内心浮现出疑问。拳斗士指的是拳击手吗？空手真的可以担任士兵吗？

当他陷入沉思时，突然传出「咕噜噜噜！」的轰然巨响。

声音来源是躯体比不上巨人，但远超过人类的亚人族。上半身几乎全被长长的毛皮盖住。之所以知道那不是服装而是毛皮，完全是因为对方有著兽头的缘故。

那看起来跟狼十分类似。有著凸出的鼻梁、呈锯齿状排列的牙齿以及三角形耳朵。从垂著长舌头的嘴里，发出了很难听清楚的声音：

「咕噜噜……食人鬼……首领……弗鲁咕鲁……噜噜噜……」

虽然不清楚那是他的名字或者单纯只是低吼，加百列还是点了点头并看向下一个人。

一瞬间，响起极为刺耳的尖锐声音：

「山地哥布林首领，哈卡西！陛下，请务必将先锋的光荣任务交给我族的勇士！」

该名矮小的亚人，猿猴般的秃头两侧长出细长的耳朵。身高远矮于刚才报上姓名的巨人、半兽人、食人鬼，甚至连人类都比不上。

根据潜行前克里达的说明，这个黑暗领域里唯一只存在一条法律。也就是有实力者可以支配一切。这样的话，不论从哪一点来看都相当弱的哥布林，究竟是什么力量让他们可以和其他种族平起平坐呢？

虽然再怎么样也不过是地位比半兽人还要低的最低等步兵单位，但对他们多少有些兴趣的加百列看著山地哥布林的脸，内心忽然了解究竟是怎么回事了。因为丑陋亚人的小小眼睛里，可以看见猛烈暴风雨般的欲望。

山地哥布林首领的自我介绍刚结束，坐在他旁边的，只有肌肤颜色不同的亚人也同样以尖锐声音叫了起来。

「千万别听他的！陛下，我们比那些家伙有用十倍！小的是平地哥布林的首领，名叫酷毕力！」

「你说什么，这个专吃蛞蝓的家伙！脑袋被充满湿气的土地浸坏了吗！」

「你的脑浆才是被太阳给晒干了呢！」

开始互骂的两只哥布林鼻子前方──

「啪叽！」一声爆出蓝色火花，两名哥布林首领立刻发出悲鸣并飞退。

「──两位，现在是在皇帝陛下面前哟。」

随著妖艳声音将高举的右手缩回去的，是一名穿著暴露服装的年轻女性。火花则是女性的指尖像打火机的打火石般摩擦时就弹了出来。

缓缓起身的女性，像要夸耀丰满的肢体与妖艳的美貌般挺起腰部，以相当刻意的动作行了一个礼。这时在加百列右侧的瓦沙克低声吹了一下口哨，而加百列也可以了解他的心情。

身上只用黑色珐琅皮革盖住一丁点如同涂了油一般的茶褐色肌肤。靴子有著跟针一样尖的高跟。背上披著闪耀黑色与银色光芒的毛皮披风，上方豪奢的白金色头发则一路垂到腰部。

眼影与口红都是水蓝色的她，这时娇艳地眯起不输给这些颜色的鲜明蓝眼睛，并且报上了姓名：

「我是暗黑术师公会总长，蒂伊‧艾‧耶尔。我麾下的三千术师，以及我本人的身心都是属于陛下。」

虽然声音与动作确实相当妖艳，但完全没有涌起性冲动的加百列只是大方地点了点头。

自称蒂伊的魔女眨了眨眼睛，似乎考虑著该不该继续说些什么，但最后还是默默行了个礼并再次跪下。

加百列心里一边想著「这是聪明的举动」一边移动视线，往下看著最后一名将军个体。静静低著头的，是一名以人类来说体格极为优异的壮年男子。

包裹住全身的漆黑铠甲上有无数伤痕，发出钝重的光芒。垂下的脸上也能看见额头与鼻梁上有淡淡的伤痕。

男人没有抬起头就直接发出的，是沙哑的男中音：

「暗黑骑士团团长，毕库斯鲁‧乌鲁‧夏斯达。在献上我的剑之前……有个问题想请教皇帝。」

这时候才抬起头来的男人，脸上那种严厉表情让加百列联想到过去遇过的少数「真正的士兵」。

名为夏斯达的骑士，双眸里带著之前报上姓名的九位将军所没有的觉悟来凝视加百列，并以更低沉的声音继续说道：

「皇帝陛下在这个时候回归皇座，究竟所为何事？」

原来如此──这些家伙确实不是单纯的程式。

加百列在内心一边提醒自己要时时记住这件事情，一边以无情皇帝的形象冷冷回答：

「鲜血与恐惧、火炎与破坏、死与悲鸣。」

加百列宛如切割金属的硬质声音传出来的瞬间，将军们的表情立刻绷紧。

依序看著十个人的脸后，加百列翻动毛皮披风，高高举起右臂指向西方的天空。

充满征服欲的真心话几乎是自动从他嘴里发出：

「……西方之地充满将朕逐出天界的诸神之力，而保护该地的『大门』随时都要崩毁。所以朕这次回来……是要让地上所有人知道朕的力量！」

关于内部时间一周后就要到来的「最终负荷实验」，已经从克里达那里接受到尽可能详细的说明。加百列根据他所说的内容，以演戏般的口气继续自己的演说：

「大门崩塌之时，人界将成为我们暗之民的领土！朕唯一需要的，就只有同时出现在那个地方的『神之巫女』一个人！除此之外的人类，汝等可以随意烧杀、掠夺！现在就是所有暗之民期待以久的──约定之时了！」

插图013

一瞬间笼罩在现场的沉默空气──

被尖锐、野蛮的吼叫声打破了。

「叽────！要尽情地杀！我要杀光白伊武姆啊啊啊啊啊！」

双脚急速踩地不停叫唤的，是小眼睛里充满欲望与愤怒的半兽人首领。两只哥布林首领也随即高举双手跟著大叫：

「吼哦哦哦哦哦呜！开战了！开战了！」

「呜啦────！战争开始了────！」

充满斗志的声音，立刻影响了其他将军以及站在他们背后的众军官。暗杀公会那些穿著黑色斗篷的家伙缓缓晃动著如树枝般纤细的身体，暗黑术师公会的魔女集团也随著娇声发射出各种颜色的火花。

宽敞的大厅里，目前正充满了原始的野蛮叫声──

加百列注意到只有名为夏斯达的骑士依然一动也不动地低著头跪在地上。

从身穿铠甲的他那如同雕像般的模样，根本无法判断这是军人的自制心，或者是源自某种感情。

＊＊＊

「没想到兄弟竟然有这种才能！我看你应该去当演员比较好吧？」

瓦沙克一边面露微笑一边把红酒瓶拋过去，加百列则是用鼻子冷哼了一声来回应。

「只是因应需要。你才应该学点像样的演说方法，你的位阶比那些家伙还要高啊。」

接过瓶子后用指尖弹开木栓，含了一小口红宝石色的液体后，忽然思考起这样算不算是在作战中喝酒。

瓦沙克像是要表示不喝白不喝一样，把这看起来相当高级的陈年好酒当成啤酒猛灌，然后用力擦了一下嘴角才回答：

「跟发布命令还是演说比起来，我比较想在前线冲锋陷阵。难得能潜行到这么逼真的VR世界……这酒和瓶子就跟真的一样。」

「相对的，被砍中的话会感到疼痛，而且会流血。这里可没有什么疼痛缓和装置。」

「这样才好啊。」

对露出奸笑的瓦沙克耸了耸肩后，加百列把酒瓶放回桌上，并从沙发上站起来。

黑曜岩城最上层的皇帝居所，比GlowgenDS总公司大楼的董事室还要宽敞，从巨大的窗户可以清楚看见城下聚落的夜景。明亮度与鲜艳度虽然比不上圣地牙哥的夜景，但是带有奇幻气息。

自称诸侯的十名将军为了开战准备而离开城堡，从仓库里搬出物资的锱重部队正拿著火把不停地在大路上移动。由于已经命令负责补给任务的商工公会头领把城里储备的所有装备与食粮用尽，所以士兵们应该有很长一段时间不会受冻挨饿才对。

加百列把视线从无数的光芒上移开，走到房间角落后，用手触碰设置在那里的紫色水晶板──也就是系统操纵台。

他迅速地操纵选单，按下呼叫外部观察员的按钮。时间加速倍率瞬时降低，在回归等倍时间的奇妙感觉中，克里达急促的声音从画面里传出：

「是队长吗？刚才看完队长与瓦沙克的潜行，现在才刚回到主控室而已！」

「这边已经是第一天晚上了。虽然早有心理准备，但时间加速是很奇妙的感觉。总之目前一切按照计划进行。一两天以内就能完成部队的准备，预定两天后就要开始进军人界。」

「太棒了。请听我说，捕捉到『爱丽丝』后，请把她带到那里，然后从选单选择弹射到主控室的操作。这样『爱丽丝』的LightCube就是我们的了。还有，这一点请特别要叫瓦沙克那个笨蛋注意一下。」

可能是听见克里达的声音了吧，瓦沙克从后面发出简短的咒骂声。

「在无法操纵管理者权限的现状下，我没办法重置帐号。也就是说，队长和瓦沙克如果在内部死亡，就没办法再使用这两个超级帐号了。这样就真的得从一名小兵开始干起了！」

「嗯……我知道了，现在就先不要到前线去吧。自卫队有什么动静吗？」

「目前没有，似乎还没有注意到队长你们已经潜行到Underworld了。」

「好，那么我要切断通讯了。希望下一次联络时已经捕获爱丽丝了。」

「了解，期待你们的成功。」

关闭通讯视窗后，加速倍率再次随著些许不对劲的感觉恢复。

瓦沙克原本还是一边咒骂一边和铠甲的挂钩格斗中，最后终于把所有金属装备丢在地上，只穿著皮革衬衫与长裤站在现场。

「那个……兄弟啊，真的不能稍微去城里玩一下吗？」

「先忍耐一阵子吧，作战结束后会给你一个晚上的时间。」

「了解。杀戮和女人都只能暂时忍耐吗……那我就乖乖去睡觉吧。我用这边的房间喽。」

瓦沙克一边让关节发出喀叽喀叽的声音，一边消失在邻接的一间寝室里后，加百列才呼一声吐了口气，把皇冠从头上拿下来。

接著又把夸张的披风与长袍挂在沙发上，把剑扔到上面。

之前玩过的VR游戏，装备只要一解除就会回到道具栏里，但这个世界似乎没有这种便利的机能。这样下去的话，在这里生活一个月房间似乎就会变得凌乱不堪，不过反正后天就要离开城堡，下次回来应该就是为了登出了。

加百列一面解开上衣的钮扣，一面打开瓦沙克对面房间的门──随即又因为惊讶而眯起眼睛。

同样是异常宽敞的寝室里，豪华得让人傻眼的床铺旁边，有一道平伏在地上的小小人影。应该已经命令过，包含仆人在内的所有人，都不准到城里比皇座之间更上方的楼层来了。竟然有人敢违抗神明的命令，这究竟是怎么回事？

一瞬间考虑著是不是该把剑拿回来，但加百列最后还是刻意就这样走进寝室当中，然后随手把门关上。

「……是谁？」

他简短地询问来者身份。

传回来的是有些沙哑的女性声音：

「……今天晚上由我来侍寝。」

「哦……」

单边眉毛稍微挑动了一下后，加百列随即横越寝室，走到床铺旁边。

双手撑在地上的，是一名只穿著单薄衣物的年轻女人。灰蓝色头发高高盘起，用装饰的发带固定住。从微微透出来的身体线条上，感觉不到带有武器的气息。

「是谁的命令？」

一边坐到光艳的丝质床单上一边这么询问后，女人隔了几秒钟才压低声音回答：

「没有人命令，这本来就是我应该负责的工作……」

「这样啊。」

加百列移开视线，重重把身体躺到床中央。

几秒钟后，女人撑起身体，无声地滑到他右侧。

「失礼了……」

如此呢喃的女性，带有异国风味的美貌让加百列也忍不住在心中发出赞叹声。肌肤颜色虽然较深，但颧骨附近有种北欧式的高雅气息。

加百列一边往上看著她轻轻褪下单薄衣裳，同时解开固定头发的发带，内心也一边出现某种感动。

人工摇光甚至懂得做这种事吗？

连这样的女子，都还不能算是真正的AI吗？这样的话，已经是完成形的爱丽丝究竟到达什么样的高度？

让加百列心动的，不是女人献出自己身体的行为。

而是因为──

他早已预测到女人从飘散开来的头发中迅速拔出，并且高高举起的锐利小刀的存在。

轻轻松松就抓住女性右手的加百列，另一只手迅速掐住对方纤细的脖子，并把她拉倒在床上。

「咕……！」

女人即使已经咬紧牙根，依然剧烈反抗想刺出小刀。虽然拥有超乎想像的臂力，但依然不足以让加百列感到慌张。他的右手架住对方惯用手的关节，左手拇指稍微掐入对方喉头来封阻其动作。

脸庞虽然因为剧痛而扭曲，但女性灰色眼睛里的决心并没有因此变淡。从她凶猛的表情、拙劣的化妆以及肌肉的发达程度，就能知道她不是专业的暗杀者。这样的话，带有反意的就应该不是自称夫萨的暗杀者头领，而是其他九名将军的其中一人吗──恐怕是人族将军里面的某个人吧。

加百列把脸靠近女人，说出跟刚才一样的质问：

「是谁命令你的？」

低沉沙哑的声音也说出相同的回答：

「是我自己的……意志。」

「这样的话，你的长官是谁？」

「……我没有长官。」

加百列不带一丝感情，像机械一样进行思考。

「RATH」想要突破的人工摇光界限点。就是能否违抗上级给予的规则、法律与命令。

和被无数法律束缚的人界居民比起来，黑暗领域的民众乍看之下一直过得相当自由，但本质上其实没有不同。只是这一边的摇光只被赋予一条法律，所以看起来才很自由。

那条法律就是「用力量夺取一切」。这里是拥有较强战斗力者，就能够支配弱者的弱肉强食世界。只要RATH的实验照计划继续进行下去，就算加百列没有介入，崇尚秩序的人界与充满浑沌的暗之国也会发生冲突，而他们似乎就是预定以这场大战做为触媒，藉此来突破下一次的界限。

但不知道什么理由，在计划进行到此之前，人界就出现突破界限的摇光。但RATH里的间谍并没有传出暗之国也出现相同摇光的情报。

也就是说，拿一把小刀就企图暗杀皇帝的女人，一定也是被绝对法律所束缚的灵魂。但她在接受加百列的质问，不对，应该说命令之后也不肯说出自己主人的名字。这也就表示，跟身为皇帝与神明的加百列所发出的命令比起来，这个女人选择了对自己主人的忠诚心。换言之，她认为自己的主人比皇帝还要强。

为了让今后的作战能够顺利进行，似乎有必要好好在将军与干部个体前面展示战斗力，让他们事先知道加百列──皇帝贝库达是这个世界最强的存在。但也不能把所有将军都杀光。这下该怎么办才好呢？

──不对。

不论如何，一定得处分掉其中一名将军。让这个女人抱持暗杀之意的家伙一定得死。

那么该如何找出背叛者呢？再次联络克里达，要他从外部监视将军个体吗？不行，要这么做的话，就必须把时间加速固定在一倍，这样反而会浪费掉现实世界所拥有的宝贵时间。

那么──

一瞬间就想到这里的加百列，再次用钢铁色的眼睛凝视著女人。

「为什么要朕的命？被钱收买了？还是约定好要给你地位？」

没有想太多就做出这样的发言，但对方立刻说出超乎想像之外的回答：

「这都是为了大义！」

「哦……？」

「现在开始战争的话，历史将退后一百……不对，是两百年！不能再回到弱者就得遭受虐待的时代了！」

加百列再次感到些许惊讶。

这个女人，这样真的还是在尚未突破界限的状态吗？如果是这样，是她的主人让她说出这样的话吗？

插图014

加百列把脸靠过去，从近距离凝视著她的灰色眼睛。

决心、忠诚，另外隐藏在深处的这种感情是…………

啊，原来如此。

如果是这样，那就不需要这个女人了。正确来说，是不需要这个女人的摇光了。

加百列遵照自己所下的判断，不再说任何多余的话，掐住女人脖子的左手直接开始用力。

颈骨开始发出「哔叽」的碎裂声。女人睁大双眼，嘴里发出无声的悲鸣。

加百列确实地按住她挣扎的四肢，一边残忍地勒紧她的脖子，一边感受到跟刚才完全不同的惊讶。

这里真的是假想世界吗？传达到左手上的，肌肉与软骨逐渐被破坏的感触，由外露的肌肤放射出来的恐惧与痛苦的气味，都比现实世界更加强烈地刺激著五感。

身体在下意识中开始震动，左手也反射性开始收缩。

喀叽。随著这道钝重的声音，不知名的女人颈骨就这么被粉碎了。

这时候加百列看见了。

从紧紧闭上双眼，用力咬紧牙根的女人额头──涌出了七彩光芒。

这无疑是那个时候──年幼的爱丽西亚丧命时所看见的灵魂之云。

加百列瞬时张大嘴巴，把女人的灵魂全吸了进去。

先是由恐惧与痛苦产生的苦味。

再来是悔恨与悲伤的酸味。

接著加百列的舌头就浸在笔墨难以形容的天堂之蜜当中。

闭上的眼睑里，不停闪过朦胧的光景。

在老旧的两层楼建筑前院游玩的幼小孩童们。有人类、哥布林以及半兽人。小孩子一看到自己，脸上就露出高兴的光芒，张开双手往这里跑过来。

这些影像消失后，这次又看见一个男人的上半身。女人以柔情紧紧抱住那经过严格锻炼的厚实胸膛。

「我爱你……阁下…………」

出现这道细微的声音，然后回响并逐渐远去。

等一切全部消失后，加百列还是持续紧抱著女人的尸骸。

太棒了，竟然会有这么棒的体验。

加百列的大部分意识都因为无上的喜悦而震动，只有剩下来的一部分理性想为刚才的现象做出解释。

收纳女人摇光的LightCube与加百列本身的摇光，介由STL连结在一起了。因此天命，也就是生命值归零后解放出来的量子档案断片，可能就经由线路逆流回来了。

但什么原理之类的东西已经不重要。

自己终于再次体验到赌上人生追求的现象。自己将濒死的女人最后抱持的感情──也就是爱完全摄取、玩味过了。那简直就像是降在久旱沙漠中的甘霖。

不够。

完全不够。

还要多杀一点人才行。

加百列把身体整个往后仰，开始发出无声的哄笑。

＊＊＊

加百列满足地望著十名将军与各阵营的干部整齐列队，并且恭恭敬敬地低下头的模样。

他们完全依照命令，在两天内完成了进军的准备。说不定，这些将军个体还比现实世界里GlowgenDS总公司那些占据董事位子的家伙还要优秀。

甚至干脆想直接把他们当成完成品。除了无可挑剔的事务处理能力之外，还有如此的忠诚心。做为放在战争用机器人上面的AI，可以说再适合也不过了。

不过还是不能忘记，众将军的忠诚是来自于RATH一直相当执著的人工摇光问题点。正因为他们的灵魂都被烙印了，拥有最强力量者可以支配一切这个大原则，这十名将军才会遵从身为皇帝的加百列‧米勒，不对，应该说是暗神贝库达。这同时也表示，在对皇帝的力量产生怀疑的瞬间，就很有可能会出现背叛者。

而这样的担心已经变成现实了。

两天前的晚上，偷偷潜入寝室的女暗杀者。

那个女人想要杀死身为最高权力者的皇帝。她的心里应该存在比加百列更加上位的主人。就是她在临死前称为「阁下」的某个人。而且几乎可以确认，那个人就是排在下方的十名将军之一。

对她来说，自己的主人比皇帝贝库达还要强。这样的话，那个阁下本身也很可能不是真心效忠于加百列。在麾下有这种个体的情况下上战场，可能会出现在休息时遭到偷袭的情况。

因此出征前最后的任务，就是从十个人当中把那个阁下找出来。

同时也能向剩下的九个人展示皇帝的力量。永远在他们的摇光里刻下究竟谁才是最强者的印象。

这时候，加百列‧米勒完全没有考虑过自己逊色于下方十名个体──也就是一对一战斗时会落败的可能性。他依然有著Underworld不过是游戏延伸出来的VR世界，存在里面的所有个体都是人造物（NPC）的固有观念。

＊＊＊

毕库斯鲁‧乌鲁‧夏斯达保持垂头跪地的姿势，脑袋里想起了师父说过的话。那是二十多年前，在暗黑骑士团本部修练场所发生的事情。

「──我师父的师父，是头被砍掉而立刻死亡。我的师父是胸口被贯穿，在回城的半路上过世。至于我虽然被砍断了一只手，但还是像这样活著回来了。虽然这不是什么值得骄傲的事情就是了。」

在乌亮地板上正坐的师父，说完就对夏斯达展示手肘以下被漂亮切断的右臂。以药物止血，简单包扎著绷带的伤口让人惨不忍睹。

三天前才刚造成这个伤口的，正是暗黑骑士的宿敌，同时也是世界最强剑士，或许也可以说是最恐怖怪物的──整合骑士长贝尔库利‧辛赛西斯‧汪。

「你知道这代表什么意思吗，毕库斯鲁？」

当时只有二十多岁的年轻夏斯达只能露出疑惑的表情。师父把受伤的手臂拽回衣物怀里，闭上眼睛丢出一句话：

「终于逐渐追赶上了。」

「追赶上──是说那个人吗？」

年轻的夏斯达无法压抑声音里面的不信任感。因为贝尔库利的剑技就是带有如此压倒性的实力。即使过了三天，师父的右臂拖著鲜血高高飞起的瞬间，自己的背椎骨像是被冰柱贯穿般的冷气依然没有消失。

「我今年就五十岁了。但别说是挥剑的方式了，感觉自己就连握剑都还不敢说已经了解奥秘。我想再过五年、十年，等我要死的时候也还是一样。」

师父静静地继续说道：

「……那个家伙已经活了两百年，生命短暂的我们，不可到达那种境界。虽然很丢脸，但挥剑交手的瞬间，我心中确实有这种放弃挣扎的想法。但狼狈地败逃回来之后，我才了解到自己的想法错了。我的师父以及师祖们这么久以来持续挑战那个男人的努力都没有白费……毕库斯鲁啊──何谓究极的剑技呢？」

面对这突然的问题，夏斯达反射性地回答：

「是『无想之剑』。」

「没错。经由长年的修行后与剑合为一体，没有任何斩杀对方或者拔剑的想法，甚至没有经过思考就自然有所行动的一击才是究极的剑技。我的师父这么教我，而我也是这么教导你。但是……毕库斯鲁啊，其实并非如此。还有更进一步的阶段。我被那个怪物砍伤后，终于了解了这个事实。」

师父上了年纪的面容稍微闪过兴奋的神色。依然保持正坐姿势的夏斯达也忍不住探出身体。

「您说的下一阶段是……」

「无想的极端相反，坚固的确信。也就是意志力啊，毕库斯鲁。」

师父忽然高高举起手肘以下整个被切断的右臂。

「你也看见了吧。那个时候，我从右上段往下砍落。那确实是无想的斩击，也是我生涯最快的一剑。一开始的动作的确是我领先贝尔库利。」

「是的……我也这么认为。」

「但是，但是呢。他原本应该会被我的剑弹开的格挡，竟然反而把我的剑推开，砍断了我的手臂。你相信吗，毕库斯鲁……那个瞬间，那家伙的剑甚至没有碰到我的剑啊！」

夏斯达顿时说不出话来，接著僵硬地摇了摇头。

「怎……怎么可能有这种事……」

「这是事实。简直就像斩击的轨道，被看不见的力量错开了一样。那不是术式，也不是武装完全支配术。我想只能这样说明那种现象了。就是我的无想之剑，败给了那家伙花了两百年时间锻炼出来的意志力。那家伙想像自己的剑应该划出什么轨道的思绪实在太过强烈，结果就成为不变的事实！」

夏斯达无法立刻相信师父所说的话。

意志力这种无形的东西，究竟要如何弹开确定存在的，又重又硬的剑呢？

师父似乎也预测到夏斯达会有这样的反应。只见他端正自己的坐姿，在乌亮的地板上静静地命令：

「毕库斯鲁啊，我要傅授你最后的剑诀──杀了我吧。」

「您……您在说什么啊！好不容易才……」

夏斯达只能把「存活下来」这几个字吞了回去，因为师父的双眸忽然出现强烈的眼光。

「就是因为捡回一命，我才一定得死在你手上。在败给那家伙的一击之后，我在你心中已经不再是最强者。这样的我如果还活著，你就没办法以对等的身份和那个家伙作战。所以你也要砍了，不对，杀了我，和那家伙……贝尔库利站在同样的高度！」

这么说完后，师父就站起来，以被砍掉的右臂摆出握剑般的姿势。

「来吧，站起来！拔剑吧，毕库斯鲁！」

于是夏斯达砍了师父，亲手了断他的生命。

同一时间，他也亲身体验到师父所说的话究竟是什么意思。

握在师父右手上的透明利刃──名为意志的剑，在交错的瞬间和夏斯达的剑爆出剧烈的火花，而他的脸颊也真的被割伤，留下再也无法消失的伤痕。

在脸庞被泪水与鲜血濡湿的情况下，年轻的夏斯达站到了超越「无想之剑」的秘技，也就是「心念之剑」的起点。

岁月就这样流逝──到了五年前。

夏斯达终于挑战了暗黑骑士的宿敌，整合骑士长贝尔库利。时年三十七岁的他，感觉自己的剑技已经到达了巅峰。

虽然师父以一条手臂来换取生命，但夏斯达当时已经有不成功便成仁的觉悟。因为夏斯达没有收做为后继者的徒弟。他不想让年轻人背负斩杀师父，将来有一天也会丧命于弟子手上的命运。他决定以自己的性命来斩断这血腥的循环。

带著最大的决心与觉悟，也就是被称为「心念力」的剑，和贝尔库利的首招剑技由正面互抵，完全没有被对方弹开。但这个时候夏斯达已经有了落败的预感。他不认为自己能够再次挥出如此沉重的斩击。

但贝尔库利就在双方用剑互抵的情况下发出浑厚的笑声并低声说道：

「不错的剑招。纯粹只有杀意的剑，不可能挡住我的攻击。仔细想想我的意思，五年后再来吧，小伙子。」

接著整合骑士长就拉开距离，悠然离开现场。不知道为什么，就是没办法对他乍看之下满是破绽的背部挥剑。

想理解贝尔库利的言外之意，必须花上很长一段时间。但经过五年的现在，夏斯达觉得自己可以理解了。那个时候夏斯达的剑上要是只带著杀意与憎恨，恐怕在两把剑互抵的时候就已经输了。虽然只有短短一回合，但自己之所以能够和挥剑他互相抗衡，应该就是藏在心中的觉悟胜过杀意的缘故。

所谓的觉悟就是──对诸位先贤牺牲性命来传承剑艺的感谢之意，以及对那些将继承自己意志的年轻人的祈愿。

所以夏斯达接到最高司祭已死的情报时，马上就决定开始和平谈判。他确信那个贝尔库利一定会接受自己的和谈。

而自己也因为同样的理由──

必须斩杀一降临到黑曜岩城，就不由分说决定开战的皇帝贝库达。

夏斯达虽然垂著头跪在地上，但已经开始凝聚加诸在必杀之剑上的心念。

离开数百年后再次复活的皇帝，是一名简直像人界人民一般，拥有白色肌肤与金发的年轻男性。不论是体格或者容貌，都不是那么有迫力。

但只有那双特别蓝的眼睛，显示出皇帝绝非泛泛之辈。他眼睛深处是一片虚无。像是能吸收一切光芒的无底深渊。这个男人隐藏著巨大且邪恶的饥渴。

如果凝聚起来的心念之力完全被皇帝的虚无吞没，那么自己的剑就伤不了他。

那个时候，暗黑将军夏斯达将会死亡。但意志应该会被后继者继承下去才对。

目前心头唯一的牵挂，是莉琵雅昨天晚上没有到房间来，所以没办法向她传达自己的决心。不知道是忙于出征前的杂务，还是回到她相当看重的「家」里去了。

如果对她表明斩杀皇帝的计划，她一定会不听劝告，坚决陪自己一起行动。所以没有见到面反而是件好事。

夏斯达缓缓吸了口气并憋在胸口。

然后悄悄以左手指尖触碰从腰上解下来放在地板上的爱剑。

目前距离皇座大约十五梅尔，是只要踏两步就能到达的距离。

第一动绝对不能被发现，拔剑时必须进入无想的境界。

夏斯达开始由指尖朝著爱剑注入提升到极限的心念之力。然后让身体放空。

正当他────

左手准备抓起剑鞘的前一刻。

皇帝用让人联想到玻璃的坚硬、光滑的声音，随口说出：

「对了，前天晚上，有人潜入朕的寝室。而且头发里还藏著短剑。」

经过抑制的惊讶立刻骚动了大厅的空气。

排在夏斯达左手边的九名诸侯，有的屏住呼吸，有的从喉咙发出低吼，也有的把身体沉进厚厚的斗篷里。就连退居后方的干部群行列中，也传出好几道惊呼声。

夏斯达也同样感到惊讶。他保持著准备开始斩击的姿势，瞬间开始思考。

也有其他人做出必须铲除皇帝这个结论。可惜的是，由皇帝目前平安无事来看，就能知道对方没能得手──但九个人里面，究竟是谁派出刺客呢？

亚人五侯应该不可能。巨人、食人鬼、半兽人就不用说了，就连比较矮小的哥布林都不太可能避开卫兵的耳目潜入最上层。

把眼神移向人族的四侯后，首先就能排除掉身为拳斗士首领的年轻伊斯卡恩，以及商工公会头领连基尔。伊斯卡恩是以穷究空手斗技为唯一目标的直爽小鬼，连基尔则是认为开始战争就能大赚一笔。

从潜入寝室这样的手法来看，暗杀者公会的会长夫萨似乎相当可疑，实际上那个男人有时候确实让人摸不透他的想法，不过使用短剑就说不通了。

暗杀者公会躲在黑暗洞穴里不停研究的，是术式与剑技之外的第三种力量，也就是毒。夫萨一族是术式行使权限、武具操作权限都不突出的人们为了活下去而集结的团体。他们有自己独特的规范，能够使用的武器最多也只有涂了毒的暗器或者吹箭。而短剑并不包含在内。

跪在左侧的暗黑术师首领蒂伊‧艾‧耶尔也能用同样的理由将其排除在外。这个几乎可以说由权力欲所构成的女人，确实可能有干掉皇帝一口气成为暗黑界支配者的想法，但蒂伊派出的暗杀者应该不是使用短剑而是术式才对。

但这样的话，就不知道九名诸侯当中究竟是谁派出刺客了。

剩下来的就只有一个人，也就是暗黑骑士长夏斯达本人。

他当然没有做过这种事。因为他已经下定决心赌上性命，亲手挥剑来解决皇帝。不要说下令部下进行暗杀了，他甚至没有跟人提起过隐藏的决心──

不对。

等等……

难道说……

皇帝提出暗杀者的话题后，一瞬间就思考到这里的夏斯达，意识到放在剑鞘上的左手指尖迅速变得冰冷。

凝聚起来的意志力一瞬间变质。成为忌虑、不安、恐惧以及不祥的确信。

几乎是同一时刻，皇帝贝库达也说出第二句话：

「我不准备审问派出刺客的人。行使自己的力量来获得更强权力的志气确实值得鼓励。想要朕的脑袋，随时可以从后面偷袭。」

睥睨再次产生低声骚动的大厅，皇帝白皙的脸上首次出现类似表情的变化──那是浅浅的微笑。

「当然，必须知道做出这样的赌注也得付出相当的代价。比如说……像这样。」

从漆黑长袍里伸出来的手，轻轻做了一个手势。

设置在皇座旁边，从夏斯达的方向来看是东侧墙壁的门无声打了开来，一名年轻的女仆静悄悄地走了进来。她的双手上捧著一个大大的银盆，上面似乎放著某种四角形的物体，但因为被黑布盖著而看不出究竟是什么。

女仆把银盆放在皇座前面，对皇帝恭敬地低下头，接著再次走回门里。

紧绷的寂静当中，皇帝贝库达的嘴角带著某种扭曲的笑容，像是要踩踏盖在银盆上的布一样，以长靴的鞋尖把布挑开。

全身冻住的夏斯达，双眼捕捉到的是──

蔚蓝通透的冰块立方体。

被封在内侧的，是陷入长眠状态的心爱女性。

「莉……琵……」

雅。夏斯达只动著嘴唇说出这三个字。

甚至连包裹全身的冷气都消失，只有无尽深邃与黑暗的虚无充满胸口。

夏斯达知道暗黑骑士莉琵雅‧扎恩克尔暗地里经营孤儿院的事情。莉琵雅她不分种族地收养失去双亲、兄弟，只能在野外等死的孩子们，而夏斯达则觉得从她这样的行为上看见了未来的希望。

所以夏斯达只对莉琵雅说出自己的理想。解决和人界之间长久以来的战争状态，创造、孕育出不再互相争夺，能和平共存的世界，这就是夏斯达一直以来的梦想。

但就是这样的梦想驱使莉琵雅去刺杀皇帝，导致她在众人面前暴露出如此悲惨的模样。虽然杀了她的是皇帝──但同时也是夏斯达本人。这是无庸置疑的事。

虽然是一瞬间发生的变故，但也因此而让极为巨大的悔恨与自责的暴风雨在夏斯达空虚的心里肆虐。

不用花太多时间，暴风雨就转变成一股黑暗的情感。

也就是杀意。

一定要杀掉他。无论如何都要杀死那个翘脚坐在皇座上，脸上露出浅浅微笑的男人。

就算得牺牲自己的性命与黑暗领域的未来也在所不惜。

＊＊＊

那么，究竟哪个家伙是女人口中的阁下呢？

加百列带著些许兴趣，眺望著跪在眼下的十名首领个体。

那个女刺客打从心里爱著自己的主人。加百列完全吸收了女人临死前散发出的，类似琼浆玉露的感情，除了女性的思慕之外，他甚至了解那个阁下对女性的爱情质量──当然自己只把它做为参考数据而已。

所以他确定只要让这几个人看见女人的首级，被称为阁下的人物一定会有所行动。毫不容情地处分背叛的个体，藉由恐惧心来提升其他个体的忠诚度。就像现实世界里用来打发时间所玩的战略模拟游戏那样。

真是一群可怜又有趣的家伙。

具备真正的灵魂但是知性却遭到限制，而且不论怎么杀都能重新再生。当自己入手构成Underworld的大型电脑与LightCube时，一定就能尽情满足从小至今一直折磨著自己的饥渴吧。

把手肘靠在皇座扶手上的加百列，用手背撑著脸颊，然后放松心情等待著。

和个体们的距离大概有十五公尺左右。这样的距离下，不论对方用什么武器发动攻击，都能有充裕时间以装备在左腰上的剑加以迎击。

当然，这样根本不足以防备由「System call」开始的术式攻击。但加百列的不安在登入到游戏前就已经消失了。

超级帐号「暗神贝库达」是为了让RATH员工强制介入黑暗领域时使用。因此被称为天命的HP极为庞大，装备的剑也是最强。最重要的是，贝库达还拥有无法被指定为任何术式攻击对象的犯规特性。

如此多条件庇护下的加百列，在十个个体跪在最左端的漆黑铠甲骑士瞬间缩起背部时……

以及他的全身笼罩在淡淡影子般气息里时……

甚至连看见骑士左手如闪电般一闪，握住放在地板上的剑鞘，同时迅速抬起脸，由刚毅面容中央的双眸放射出非人深红光芒的时候也──

无法完全理解持续发生当中的事象。

这个世界除了是在物理伺服器内进行演算的程式之外，同时也是由和人类摇光同质的光量子所构筑的「现实梦境」。

因此黑色骑士所散发的纯粹且强烈的杀意，是从他的LightCube到Main Visualizer，然后经由量子通讯回线传达到连结在STL的加百列身上。

＊＊＊

夏斯达染成血色的视线中央，只能看见皇帝一个人的模样。

右臂以生涯最快的速度一闪后拔出了剑。

从剑鞘被解放出来的，不是由师父那里继承来的神器，长刀「胧霞」那熟悉的灰色刀身。正如它的刀名一样，类似夜雾的浓厚霭气围绕著长大的刀刃，不停形成漩涡与扭曲著。

夏斯达虽然没注意到这种现象的逻辑，就跟长年研究但还是无法理解的整合骑士究极奥义──武装完全支配术完全相同，但对他来说这已经不再重要了。

「杀！」

随著剎那的吼叫声，夏斯达把所有愤怒、憎恨以及哀伤贯注在爱刀上，将其高举过头部。

3

从人界北端到东域的尽头。

整合骑士爱丽丝以及出生在西帝国的雨缘，都是第一次到访四帝国当中充满最多谜团的伊斯塔巴利耶斯东帝国。

眼下峰峰相连的奇岩之间，可以看见琉璃般湛蓝的河水滔滔不绝地流动。有时会出现在河边的城镇或村庄，不像在北方见惯的石造，大部分是由木材建造而成。

仰望天空指著爱丽丝这边的人们，头发也几乎都是黑色。爱丽丝忽然想起，一直都和自己不对盘的整合骑士团副团长法那提欧就是出身自此地。

把视线移回前方后，就注意到靠在握著缰绳的爱丽丝身上，茫然眺望著天空的桐人也有一头漆黑的头发。说不定这个人也是出身于东域，虽然也想过降到街上让他和人们接触的话，说不定就能让他恢复意识，但目前还是得尽快赶到目的地才行。

夜晚在远离聚落的地方野营，吃著雨缘抓来的鱼与携带用的干果，马不停蹄地赶了三天的路之后──

在十一之月二日的午后，只有这一点和北方完全没有两样的高耸尽头山脉，以及像神明直接垂直砍断岩壁的峡谷就出现在前方。

「……看见了喔，桐人。」

爱丽丝呢喃著，轻轻地抚摸不得不背负沉重行李进行长途飞行的爱龙脖子。虽然在魔兽种类几乎完全消失的现在，飞龙已经是能以拥有最大等级天命为傲的生物，但背负两个人与三把神器的飞行依然是相当大的负担。这半年来尽情吃鱼而积蓄起来的力量，似乎也因为这次的飞行而几乎用尽。

爱丽丝心里想著到达野营地之后，无论如何都要让它尽情地享用喜欢的烫羊肉并甩了一下缰绳，雨缘也以感觉不到疲劳的声音回应，接著用力拍动翅膀。

由远处看感觉只有极细间隔的峡谷，靠近之后才发现自己太看轻它了。

山谷的幅度应该宽达一百梅尔左右吧。这已经足够半兽人与食人鬼的大军团排成横列往前突进了。

贯穿山壁笔直往前延伸的山谷，前方有一片宽广的草原像要包围住入口处一般，这时可以看见无数白色帐篷整齐排列在草地上，形成一处广大的野营地。此外到处可以看见炊烟升起，周边还有士兵们正在接受训练。长剑挥动时的光芒，以及发出的呼喊声甚至直达天际。

看来士气不像担心的那么低，但士兵的数量本身实在太少了。稍微环视了一下，就能知道总数大概不到三千人。另一方面，黑暗领域的侵略军应该不下五万。在人界里，士兵与侍卫是赐予极少数人的天职，但山脉后面的世界却不问男女老幼，只要能够作战就都是士兵。

在这种状况下，再加上爱丽丝一个人应该也不会有太大的改变。骑士长贝尔库利，究竟想到什么样的防卫作战呢……

这么默默思考著的爱丽丝首先飞越野营地，让飞龙前往沉浸在微暗当中的峡谷。

「抱歉喔，雨缘，再飞一下下。」

如此对龙搭话，而它也以咕噜噜的声音回应后，索鲁斯的光芒就被块状山脉遮住了。

一进入山谷的瞬间，身体就被足以令人打冷颤的寒气包围。左右两边直立的岩壁光滑到让人觉得这绝对是由神明所切割出来。上面别说是生物了，就连一株草木都看不见。

就这样低速飞行了几分钟──

漫长霭气后方，终于出现了无边巨大的构造物。

「这就是……『东大门』…………？」

垂直耸立的灰色大门，从下部到顶端应该足足有三百梅尔高吧。虽然比高达五百梅尔的中央圣堂还要矮，但压迫感可以说不相上下。

最惊人的是，左右两边的大门是从几乎看不出任何一丝接缝的一整块岩石所切割而成。这样的物体别说是经由人手所建筑了，甚至不可能藉由神圣术来加工生成。最高司祭亚多米尼史特蕾达生成的最大构造物是将央都圣托利亚分割为四等分的「不朽之壁」，但那些相连的壁面每一块都比这扇门要小得多。

这道大门，是世界开始之时由神亲手设置在此地的东西。这当然是为了分隔人界与暗之国──同时也是为了造成三百数十年后的这场惨剧。

「停下来吧，雨缘。」

让飞龙在空中停下来，爱丽丝再次从近距离仰视著门。

高达两百梅尔左右的地方，可以看到一些神圣文字像要连结成左右两扇门的灰色岩板般写在上面。

「Destruct……at……the、last、stage……」

好不容易才念出中间的一行，但完全不了解意思。

就在她露出狐疑表情的瞬间，突然有「哔叽叽」的强烈破碎声震动空气，让爱丽丝跟雨缘吓了一大跳。一边摸著龙的脖子一边凝睛的爱丽丝，随即看见刚才还相当光滑的门上，有几条宛如漆黑闪电般的细微裂痕划过。

延伸数十梅尔的龟裂好不容易停止，接著周边有几片岩石剥落，消失在遥远下方的谷底。

爱丽丝抬起脸来，再次将视线放在大门上。结果注意到平坦的岩板上几乎全都是网眼般的龟裂。

爱丽丝轻轻挥动缰绳，让坐骑飞龙尽可能靠近大门。

接著畏畏缩缩地伸出左手，迅速在空中划出史提西亚的印记，轻轻敲了一下门的表面。

浮现出来的紫色「窗户」上，记述著东大门所拥有的天命最大值与现在值。

左边的数字，即使在至今为止所看见的多数天命数值中也是最大等级──高达三百万以上。但右边则浮现不到其千分之一的2985这样的数字。当爱丽丝哑然凝视著这些数字时，现在值又在她眼前减少成2984。

手掌冒汗的爱丽丝，开始计算数字再次减少的时间。然后准备藉此来推算大概还有多久天命才会完全消失。

「……怎么会……」

无法相信自己脑袋里得到的答案，爱丽丝低声这么说道。

「……五天……仅剩下短短五天而已吗…………？」

三百年来一直严守岗位分隔两个世界的大门，将在短短五天后崩坏──真的可能发生这种事情吗？

脑袋里头依序闪过赛鲁卡光辉的笑容、卡利塔老人满是皱纹的脸庞，以及父亲卡斯弗特严肃的面容。短短几天之前，才击退袭击他们的哥布林，并用冰块封印住洞窟而已。而且她也相信，这样子卢利特村就能保持好一阵子的和平。

如果五天后大门崩坏，黑暗大军蜂拥而至时，守备军无法抵挡下攻势，那么渴望鲜血的怪物就会如洪水般淹没人界。而这巨大的洪水也将立刻到达北部边境，吞没卢利特这座小村庄。

「一定……得想办法才行……」

爱丽丝像呓语般这么呢喃，接著在下意识中拉紧缰绳。雨缘离开快要崩坏的大门，缓缓拍动翅膀往上升去。

到达高三百梅尔的大门最上部，再次让龙停留在空中。

门后方和人界这一边同样是切开岩壁的山谷笔直地往前延伸。但远方那一大片空间没有蓝色天空与绿色草原，而是血红色天空与黑暗领域那像撒满灰烬的荒野。

想把视线从不祥光景移开的爱丽丝，忽然间眯起眼睛。

因为她在黑色大地的稍远处，发现了隐隐约约晃动的光芒。

于是爱丽丝让雨缘飞到更高处，然后定眼凝视。结果光线不止一道。它们不规则地密集在一起，看起来似乎一直延伸到远方。

那些全是营火。

原来那是一片野营地。暗之军队的前锋，已经大举来到距离人界如此近的地方，等待著大门崩坏，前往人界的道路开通的时刻。

「还有……五天……」

爱丽丝以沙哑的声音，再度呢喃了一遍。

接著就让飞龙回过头。感觉继续看著这无数的营火，自己就会被焦躁感吞没，单骑直接冲进敌方阵地。

如果对方只是哥布林或者半兽人的步兵，那么爱丽丝就算这么做，也有自信可以杀个一两百只并平安无事地回来。但敌营里如果有食人鬼的弓兵，或者暗黑术师的大部队，那么事情就不会这么简单了。

就算整合骑士可以一骑当千，但终究只有一个人。被从剑技与术式无法伤及的后方集中使用远距离攻击的话也不可能毫发无伤，就算只是轻伤，持续累积下去终究会把天命全部耗尽。这正是骑士长贝尔库利长年来担心的，整合骑士圑──甚至可以说人界守护者的最大弱点。

推展将战力集中在一小群人身上的最高司祭亚多米尼史特蕾达早已过世，私藏在中央圣堂的大量武器防具也已经紧急分发给守备军。但剩下来的时间实在太少了。如果兵力有一万，准备期间有一年的话──

以叹息将无能为力的思绪甩掉后，爱丽丝对雨缘做出下降指示。

守备队的野营地中央，空出了一块宽广的草地。看见旁边并排著许多巨大的帐篷，就知道那里正是飞龙的起降场。

画著弧形往下降的雨缘，四肢的钩爪刚碰到绿色草皮，就把长长的脖子朝向帐篷，从喉咙发出「咕噜噜」的撒娇般声音。

立刻有稍微低沉一些的声音做出回应。那应该是它的哥哥泷刳吧。爱丽丝在龙还没完全停下来时就抱著桐人跳到草地上，把它双脚上面沉重的行李卸下来。雨缘立刻就踩著沉重脚步往帐篷冲去，和从厚布底下探出头来的哥哥互相摩擦著脖子。

忍不住露出微笑的爱丽丝，注意到后面有脚步声靠近，于是急忙绷起脸来。她整理朴素原色裙子的裙襬，把被风吹乱的头发理到背后。

在她回头之前，就有一道熟悉的男性声音响彻在起降场当中。

「师父！吾师爱丽丝大人！我就知道您一定会回来！」

一边在草地上发出「滋沙沙」的滑行声一边绕到自己前面的，正是十天前左右刚和他喝完诀别酒的整合骑士艾尔多利耶‧辛赛西斯‧萨提汪。虽然是在野营当中，他那波浪状淡蓝紫色头发以及白银甲胄依然是一尘不染。

「……看起来很有精神嘛。」

不对爱丽丝冷冷的回答感到气馁，像是极为感动而想说些什么的艾尔多利耶，嘴唇忽然间冻住了。

因为他注意到爱丽丝用左臂撑住的黑发年轻人。

单边脸颊有些抽筋，大大把头往后仰的年轻骑士，像是难以置信般发出低沉的吼声：

「为什么……把他带过来？」

爱丽丝也拚命挺直身子来回答他：

「这是当然，我发誓要保护他了。」

「但……但是……只要一开战，我们整合骑士就得一直在最前线作战。和敌兵短兵相接时该怎么办？总不可能背著他吧。」

「有必要的话我会这么做。」

像要让桐人无法自行站立的瘦削身体远离艾尔多利耶的视线一般，爱丽丝的右脚稍微往后退。但不知不觉间已经有休息中的士兵与下级整合骑士们三三两两地聚集在起降场附近，以怀疑的眼神看著并排站在一起的爱丽丝与桐人。

笼罩在如同波浪声的骚动声下，艾尔多利耶提出了尖锐的反驳：

「师父，万万不可啊！虽然有所僭越，但请容我一言。带著那种没用的重物战斗，不要说战斗力会减半了，甚至连师父的玉体都可能遭受危险！爱丽丝大人在即将到来的战争里……」

他暂停了一下，才又用金碧辉煌的银制护手指著周围的士兵说：

「……应该负起率领他们战斗的任务！这样的您，怎么可以让自己处于无法发挥全部力量的情况下呢！」

他说的一点都没错。但爱丽丝也无法轻易认同他的看法。于是只能用力咬紧牙根──思考著如何说明对自己来说两边──为了人类而战与保护桐人一样重要。

但爱丽丝同时也对弟子热烈的辩舌产生某种惊讶的感觉。

跟过去在中央圣堂接受爱丽丝指导剑术时比起来，他已经有明显的变化。当时的艾尔多利耶就像十分崇拜爱丽丝般，不论她说什么都不曾加以反驳。

这个世界的人类，全都被充满谜团的「外界之神」施加了右眼的封印，因此绝对无法违抗法律以及居上位者的命令。就爱丽丝所知，主动成功打破封印的就只有自己，以及目前已经丧生的蓝蔷薇剑士尤吉欧而已。就连拥有与神明同等权限的最高司祭亚多米尼史特蕾达与贤者卡迪娜尔，最后都没能反抗这个封印。

艾尔多利耶目前应该也受到那个封印的影响才对。但是他──虽然不是明确反抗爱丽丝所说的话──不过已经不像过去那样盲从了。他是以自己的意志来思考，并阐述自己的意见。

让他产生这种变化的人，恐怕就是桐人还有尤吉欧吧。

虽然只有极短暂的时间，但和除了是这个世界最大的反叛者之外，同时也是高强剑士的两个人接触，已经让艾尔多利耶的灵魂产生强烈的动摇。

现在想起来，生活在卢利特村的妹妹赛鲁卡，也经常对村子依然守旧的规则以及有力人士的不懂变通表示不满。还有像爱丽丝准备把桐人与尤吉欧从北圣托利亚修剑学院带走时，从里面跑出来的两个女学生。那两名年纪还小的少女，原本不可能做出叫住整合骑士的行为。

另外，当然──爱丽丝本身也一样。

从开始和桐人交手，到快要从中央圣堂外壁摔落的瞬间为止，她都完全没有怀疑过世界的构成、教会的支配以及最高司祭的神性。

但在不得已之下合作脱离危机，接受停战约定，然后开始攀爬外壁的时间里，爱丽丝却不停被桐人的话、剑以及漆黑的眼睛剧烈地刺激──最后终于让自己突破了右眼的封印……

没错，桐人简直就像对这充满虚伪和平的世界挥落的铁锤一样。他以潜藏在灵魂里的力量摇晃、撼动世界，最后把名为公理教会的，钉在人界中心的巨大老旧钉子整个敲坏。但代价就是他的好友尤吉欧与导师卡迪娜尔的性命，以及丧失了自己的心灵……

爱丽丝用力抱紧以左臂支撑住的纤细身躯，然后由正面回看著艾尔多利耶的双眸。

实在很想对他说，你能够有现在的样子，全是因为和这个人战斗过的缘故。但对方当然无法理解。对整合骑士团来说，桐人现在仍只是难以饶恕的反叛者。

面对无言持续站在那里的爱丽丝，艾尔多利耶露出承受著钝重疼痛般的表情，准备继续对她搭话。

就在这个时候。周围人墙的一处，简直像被透明巨人的手拨开一样分散开来。

从人墙深处传出来的，是让爱丽丝怀念到快要流下眼泪，同时也让她紧张到感觉疼痛的声音。

「哎呀，火气别这么大嘛，艾尔多利耶。」

把视线从迅速挺起背杆的年轻骑士身上移开后，爱丽丝缓缓转过身体，看向声音的主人。来者穿著带有东域风味的宽松前襟式服装，较低的位置上绑著一条宽大的腰带。左腰上则随意插著一把形式简单的长剑。穿在两脚上的是奇特的木制鞋子。

和周围的骑士与士兵比起来算是相当轻便的服装。但从他身经百炼的身体上散发出来的压力却比任何铠甲都要厚重。

用力摩擦了一下类似和服般淡蓝色而且剪得相当短的头发后，声音的主人嘴角就露出无声的笑容。

「嗨，大小姐。你看起来比我想的还有精神，这样我就放心了。脸是不是变圆了？」

「……叔叔，好久不见了。」

爱丽丝拚命不让自己渗出眼泪，然后向世界上最古老且最强的剑士──整合骑士长贝尔库利‧辛赛西斯‧汪行了个礼。

他是爱丽丝以整合骑士身份度过的六年里，唯一信任且尊为师父，甚至是父亲的人物。而且同时也是这个世界上唯一一个──除了桐人之外──爱丽丝确定自己绝对无法取胜的剑士。

所以现在不能让他看见自己哭泣的脸庞。

如果贝尔库利不准自己把桐人安置在这里的话，自己也得遵从他的命令。当然，就算是他的命令也无法强迫目前的爱丽丝。但在众人面前反抗他的话，骑士团与守备军的秩序将会产生动摇。在仅仅五天后就要面临决战的状况下，贝尔库利的指挥权绝对不容许受到一丝伤害。

像是看透这时爱丽丝内心的纠葛般，依然带著粗犷与温柔微笑的贝尔库利缓缓走了过来。

他先凝视著爱丽丝的眼睛，然后用力点了点头。

又瞥了一眼背后还想说些什么的艾尔多利耶来制止他，接著骑士长的视线就移到爱丽丝抱在怀里的桐人身上。

他收紧嘴角，双眸里带著如同蓝白色火焰的锐利光芒。

贝尔库利「嘶」一声长长吸了口气。爱丽丝立刻感觉周围开始出现刺痛肌肤的冷空气。

「……叔叔……」

爱丽丝挤出细微的声音。

贝尔库利正在凝聚剑气。准备使出比只传授给整合骑士的「心念技」……以心灵的力量来移动物体的「心念之臂」更加强力的秘术「心念之剑」。

那是把凝聚的意志力贯注在剑上后使出的招式。有时那透明的剑刃甚至能弹飞拥有实体的敌刃。骑士长所拥有的神器「时穿剑」，其甚至能够斩断未来的武装完全支配术，正是因为他拥有压倒性的意志力才能成立的术式。

这也就是说──贝尔库利打算砍了桐人吗？

如果他真的想藉由武力把这个问题一刀两断，那么自己绝对无法接受这样的做法。到了那个时候，自己就得拔剑保护桐人了。

在骑士长强烈至极的剑气压迫下，周围的士兵、艾尔多利耶，甚至连帐篷里的许多飞龙都静了下来。被严重压缩到难以呼吸的空气当中，爱丽丝拚命想移动右手手指。

但是在爱丽丝触碰到爱剑的剑柄之前，贝尔库利的嘴微微动了一下，接著响起类似意念的声音。

──别担心，大小姐。

「…………！」

当爱丽丝屏住呼吸的瞬间──

贝尔库利全身没有任何动静，但是双眼却放射出令人感到恐惧的强烈光芒。

同一时间，爱丽丝怀中的桐人也开始剧烈震动起来。

「锵！」一声清脆的声音响起，贝尔库利和桐人之间的空间爆出银色闪光。

──刚才那是？

爱丽丝因为过于惊讶而稍微喘了口气，但这时候贝尔库利已经发出浑厚的笑声，让人觉得刚才的剑气彷佛是幻觉。

「叔……叔叔……？」

面对茫然如此呢喃的爱丽丝，骑士长像是刚练习完剑术般，以指尖搔著下巴说道：

「大小姐，你看到刚才的情形了吗？」

「是……是的。虽然只有一瞬间……但是的确有交锋的光芒……？」

「嗯。我对那个年轻人施放的心念之剑，不对，应该说心念短剑。只要砍中的话，脸颊应该会被切下一层皮。」

「砍中……的话？这也就是说……」

「没错，年轻人用自己的心念挡了下来。」

爱丽丝忍不住看向左边怀里桐人的脸。

但她的期待马上就落空了。微微张开的黑色眼睛里，只映照出空虚的黑暗。脸上还是没有任何表情。

──但是，他的身体刚才确实震动了一下。

爱丽丝一边以右手抚摸桐人的头发，一边把视线移向贝尔库利。骑士长虽然摇著头，但还是以确切的声音做出这样的判断：

「年轻人的心似乎已经不在这里……但也还没死。听好了，大小姐，刚才这个小伙子想保护的不是自己而是你。所以我认为他总有一天会回来。大概是大小姐真正需要他的时候吧。」

爱丽丝必须以比刚才更加倍的努力，才能抑制再次要溃堤的眼泪。

──没错，他一定会回来。

──因为桐人……桐人他才是世界最强的剑士。因为挥动两把剑的他，甚至击毙了那个半神半人的司祭。

──我不会说……是为了我。拜托你为了生活在这个世界的众多人民回来吧……

爱丽丝终于忍俊不住，以双臂用力抱住桐人的身体。这时背后又响起骑士长带著告诫之意的声音：

「所以就是这样了，艾尔多利耶。别在意这些小事情，让她照顾一个年轻人也不会怎么样啦。」

「但……但是……」

鼓起足以令人称赞的勇气后，最新的整合骑士艾尔多利耶就向最古老的骑士贝尔库利阐述自己的意见：

「如果还有一点战力也就算了，但这种状态实在……而且就算恢复意识，一个学生的剑又能有什么帮助……」

「喂喂！」

贝尔库利的声音除了沉稳的笑意之外，同时也含有名刀般的锐利度。

「你忘记了吗？这小鬼的伙伴可是打败了我这个整合骑士长贝尔库利‧辛赛西斯‧汪呢。」

一瞬间周围就陷入寂静当中。

「那个叫作尤吉欧的小伙子……真的非常强。甚至让我使出时穿剑的完全支配术，而且还打败了我。就像打败你、迪索尔巴德和法那提欧时一样。」

这下子似乎连艾尔多利耶也无话可说了。其实这也是理所当然的反应，因为不但是整合骑士团，就连门外的黑暗领域里，也不存在一对一能赢过贝尔库利的剑士──公理教会的所有人都是如此深信不疑。

但这在某种意义上来说也是相当危险的发言。

骑士长贝尔库利是以最强者的威严打造出这只急就章的守备军。但是却宣示有尤吉欧这名打败自己的剑士存在──而且承认桐人的实力和尤吉欧相同，也就代表……

当爱丽丝想到这里而准备抬起头来时──

贝尔库利瞬间抬头望向天空。

「叔……叔……？」

骑士长这时以出乎意料之外的发言回答了爱丽丝的问题：

「遥远的地方一瞬间出现巨大的剑气然后消失……看来是我认识的某个人死亡了……」

4

构成暗之国十侯会议的十名诸侯，不论是性向、人格以及隐藏在心里的野心都完全不同，但他们还是拥有唯一一个共通点。

那就是比任何人都要了解「有实力者能支配一切」这一条唯一的法律。

应该说，就是因为幼年时期这条法律就深深刻划在灵魂里，才会持续不断努力──时时提醒要锻炼自己，排除防碍者──也才能在这个以暴制暴的世界里爬到几乎是顶端的位置。

因此……

和夏斯达并列的九名诸侯，在端坐于最右侧的暗黑骑士长随著撕裂棉帛般的吼叫声对皇帝拔剑时，内心都没有感到太大的惊讶。

反而有许多人都出现「在这时候发难吗？真是大胆」这样的理解。就连在这三百年当中让语言能力，也就是智能退化的半兽人族与食人鬼族的首领，野兽般的眼睛都因为认为如此就能知道皇帝这家伙的实力如何而发出锐利的目光。和夏斯达同样是求道者而对他抱持敬意的年轻拳斗士首领，内心甚至还帮他加油，想著「既然拔剑那就砍了他吧」。

在这些人当中，有两个人在数秒钟前已经预测到这样的事态。

一个是暗黑术师公会总长蒂伊‧艾‧耶尔。和夏斯达水火不容的她，早就计划过绑架暗黑将军的爱人，所以从以前就知道莉琵雅的长相。

所以在看见莉琵雅被冰冻的首级后反而是惊愕的感觉比较强烈。蒂伊当场预测到夏斯达可能会因为过于愤怒而拔剑，一瞬间思考起那个时候自己应该怎么办。

虽然考虑过从夏斯达背后施放术式来给皇帝做人情，但蒂伊最后还是选择冷眼旁观。因为夏斯达败给皇帝也无所谓，万一获胜的话，到时候正可以烧灼这名应该受到重伤的仇敌，然后自己掌握暗之国的霸权。蒂伊在内心露出了狡诈的笑容，为了隐藏自己的兴奋而轻轻舔了一下嘴唇。

这时候，还有另一名察觉暗黑将军叛意的人──

他则是立刻有所行动。

＊＊＊

夏斯达心里只有「杀」这个字，用力地挥动自己的爱刀。

如果只计算贯注在剑招里的心念强度，这一击确实已经超过过去与整合骑士长挥剑相抵的时刻。他强烈的愤怒与怨叹，立刻就引起了原本需要漫长术式的完全支配现象。

夏斯达手里的长刀「朦霞」是做为VRMMO程式套件的Underworld在两百年前左右自动生成的神器级物体。拥有「水」属性的它，呼应了夏斯达极强烈杀意的刀身，就在内含必杀威力的情况下失去实体，转变成雾状的影子。

朦霞在完全支配状态下的特性是，能够完全省略附属在所有剑上的「以剑刃切断或者贯穿对象物来给予伤害」的攻击过程。只要碰到延伸出去的长长带状雾，天命数值就会在那个时间点受到斩击属性的伤害。也就是说，除了回避之外的防御都起不了作用。

皇帝贝库达，也就是加百列‧米勒在夏斯达拔刀时也抽出自己腰间的长剑，准备弹开敌人的一击。

如果事态按照这样推移下去，夏斯达的雾刃应该已经穿越加百列的剑砍中他的身体，然后把浓缩的杀意全部灌进去了。

但就在夏斯达神速跨步，准备使出必杀斩击的前刻──

他的动作就像被冻住了一样停了下来。

不知道什么时候，暗黑将军身上铠甲的左侧腹，已经有一根飞针深深刺在厚重装甲上仅有的一丝接缝里。

在后方缓缓站起来的，是用深灰色斗篷包裹住全身，宛如幽灵般瘦削的男人。

他是暗杀者公会头领夫萨。这名十侯当中存在感最为薄弱，总是躲在阴暗处，在会议中也几乎没有发过言的人，在恐怕是人生当中受到最大瞩目的情况下徐徐走到前方。

夫萨之所以能事先察觉到夏斯达的反叛，完全是因为他是诸侯当中最胆小且神经质的人。

暗杀者公会是由一群无力者聚集起来的组织。这是天生在体力、术力、财力以及其他所有力量都不突出，但是又拒绝成为奴隶遭受严酷奴役的人们，为了钻研连在黑暗领域都被嫌恶的「毒技」所创造出来的集团。

地底世界里的一部分昆虫、蛇类以及植物等毒性物体本来就是被当成负荷实验的一环而配置在各地。因此其效果都有界限，大概都只到居民运用必须的智慧就能够充分回复的程度。反过来说，就是无法从它获得对抗术式或者剑技的力量。

但是组织暗杀者公会的这些人，编纂出RATH工作人员没想到的「浓缩」技法，花了漫长的岁月来生产、强化毒液。位于城堡外城市贫民窟地下深处的公会总本部里，有著上百年来持续熬煮毒果汁液的大锅子，以及从各地收集来的毒蛇在里面自相残杀的大壶。

但是终于完成的「致死毒」却造成了公会内暗杀横行这样的悲剧。和剑法与术式不同，迟效性的毒很难特定出加害者的身份。

当然，管束公会的首领不极其胆小的话根本就无法存活下去。他们甚至可以感应到潜伏在周围人群的视线，不对，应该说气息里的一丝丝杀意。

对夫萨来说，夏斯达看见莉琵雅首级的瞬间所散发出来的杀气，甚至比鲜血的味道还要清晰。

而且对夫萨来说，暗黑将军夏斯达正是他在这个世上最为憎恨的对象。

之前就不知道已经拟定并废弃过多少暗杀计划。甚至已经有能够杀掉他的自信。但只要被发现死因是中毒，任何人都会知道这是暗杀者公会干的好事。夏斯达断气的一个小时后，强力无比的暗黑骑士圑就会冲进本部，把所有公会成员杀光吧。正面战斗的话根本没有胜算。

但现在这个瞬间……

自己拥有光明正大将磨利的毒针刺进可憎敌人身体里的理由。因为在皇帝御前拔剑的瞬间，夏斯达就不再是暗黑将军或者十候，只是一个反叛者罢了。

夫萨从斗篷的怀里抽出来投掷的，是暗杀者公会首领代代继承下来的暗器。从「鲁贝利鲁毒钢」这种本身就会分泌麻痹毒的危险矿物削下来的极细毒针内部是中空状态，里面可以存积各种毒液。

而注入到里面的，同样是这个公会技术结晶的致死毒。是把五万只名为「血腐蛭」的稀有水蛭放在一起磨碎，再经过数次过滤浓缩所得到的一小滴毒液。由于让水蛭在饲育下繁殖的尝试全都失败了，所以要制造这一滴毒液可以说必须费尽千辛万苦。

虽然夫萨不可能知道，但生存在Underworld原野的动物，是系统基于面积大小的规定值所生成出来，除了被指定为家畜个体的牛羊之外，全都不可能经由人工繁殖。

也就是说，夫萨施放的毒针，不论是素材还是内部的毒液，都是将暗杀者公会所有力量浓缩在一点后所完成的产物。它同时也是数百年来遭受虐待的弱小者们怨念的结晶。

＊＊＊

夏斯达因为把意志力全都放在挥出去的刀上，所以完全没有意识到毒针深深插进肉里所带来的痛楚。

但是准备朝著皇座高高跃起的瞬间，就感觉到整个身体像是变成铅块一样沉重，也因此而瞪大了眼晴。

当双脚失去力量，单膝瞬时跪地后，才重新发现到左侧腹已经插著异物。

──是毒吗？

瞬间浮现这样的想法，在像冰一样冷的左手麻痹前就迅速拔出毒针。注意到称不上是武器的极细毒针上带著鲜艳绿色光泽的夏斯达，立刻了解这就是恐怖的鲁贝利鲁毒钢，而他也马上想咏唱对抗的术式。

但寒气以惊人的速度由左侧腹浸透到全身，甚至来到嘴部。还没咏唱完「System call」的起句，舌头就失去感觉，连咬紧牙根都办不到了。

这时左手也完全麻痹，从拳头里滑落的毐针掉到黑色大理石上发出细微的声响。

最后举起刀的右臂也开始缓缓落下，完全支配状态也同时解除，由灰色雾气变回实体的爱刀刀尖碰到了地板。

和挥刀攻击皇帝前一样，以低头左膝跪地的姿势僵在现场的夏斯达，视界里无声滑进一件黑色斗篷。

──是夫萨。

──没想到被这个男人摆了一道。

「……竟然败在这种不值一晒的小东西上……你一定这么想吧，毕库斯鲁？」

如磨擦般的咻咻声从头上降下，让夏斯达绷紧了唯一还稍微能动的眼角。

──你这家伙，没资格这样叫我的……

「你一定想说，我没资格这样叫你的名字吧？但是呢，我可不是第一次以毕库斯鲁来称呼你喔。」

暗杀者缓缓弯下膝盖，曲身来到同样高度的脸庞进入夏斯达视界当中。但整个往下拉的兜帽遮住光线，除了尖下巴之外全都隐藏在黑暗当中。

接著下巴像震动般动了起来，传出更加沙哑的声音：

「在幼年学校里……经常被你欺负的小孩子们，长相你应该都不记得了吧。同时也忘记有一个小孩因为太过屈辱而跳进河渠，永久从学校里消失这件事。」

──搞什么。这男人到底在说些什么？竟然提到幼年学校？

出生在普通骑士家庭的夏斯达，到了能握住木剑的年纪，就在个人意愿完全不受重视的情况下被送到骑士团附属的幼年学校里。之后就只有为了存活下去而不断努力修行的记忆了。在所有选拔考试中经常获得胜利，被任命为骑士团的军官，最后更得到师父前任骑士长赏识──可以说是根本没有空回顾过去的，宛如激流一般的半生。

三十多年前并排在一起挥动木剑的小孩长相，自己当然不可能记住。

「……但我没有一天忘记你。我漂流到地底的暗渠后，被暗杀者公会捞了起来。之后以奴隶的身份在那里被人使唤的漫长岁月里，也没有一天忘记过你……我不停累积知识，开发出许多新的毒药，最后终于爬上公会首领的位子。代价就是失去了许多东西……但全都是为了向你复仇啊，毕库斯鲁。」

扭曲的声音中断的同时，兜帽也微微倾斜，夫萨的真面目显露在夏斯达面前。

即使如此，夏斯达的记忆还是没有恢复。不对，应该说就算夏斯达完整地记住过去所有同学的长相，现在也想不起他的名字了。可能是受到毒液的影响吧，夫萨的脸溶化得非常严重，目前长相已经沦落成比半兽人还要恐怖了。

可以看见再次被深深拉下来的兜帽深处，只有一双眼睛放射出强烈的光芒。

「注入你体内的，是为了杀掉你而开发出来，耗费几乎令人发疯的时间一滴一滴储存起来的毒液。根据实验，一个小时就能杀掉天命超过三万的大型地龙。依照你的体力与天命总量，恐怕只剩下两三分钟的生命吧。我要把寄放在你这里的怨恨与屈辱一次全讨回来……」

──怨恨吗？

夏斯达把视线从夫萨的眼睛移开，凝视著掉在黑色大理石地板上的毒针。

──我在愤怒与怨恨的驱使下想要斩杀皇帝。夫萨也在这只针上贯注同样的力量想杀了我。所以我的招式才会停下来。「杀之心念」赢不了「义之心念」。以前和那个男人……整合骑士长贝尔库利交手过一个回合所掌握到的剑诀，我竟然在最后这个紧要关头忘记了……

夏斯达已经无法保持单膝跪地的姿势，从左肩垮倒到地板上。

逐渐朦胧的视界中央，毒针的后方──

可以看见放在银盘上的冰块立方体。

＊＊＊

夫萨，过去名为费留司‧萨尔加迪斯的复仇者，为了尽情享受期待以久的欢喜瞬间而死命睁开双眼。

恣意攫取无数荣耀的暗黑将军夏斯达，现在就躺在自己脚边。上了年纪却还相当有弹性的皮肤变成土黄色，锐利的目光逐渐消失，也只剩下断断续续的气息，这模样实在太狼狈了。可以说是丑陋又丢脸至极的临死时刻。

而夏斯达之死，同时也证明了毒杀技术优于剑术与暗黑术。使用了鲁贝利鲁毒钢加上血腐蛭的新型复合毒，只要轻轻刺一下就能让敌人陷入无法拔剑与咏唱的状态，让其迅速丧命。

坐在皇座上的皇帝贝库达，应该也会因为刚才那一幕而注意到暗杀者公会的价值吧。当新型毒的大量生产完成时，就不必再看骑士与术师的脸色了。届时也能取回原本的姓名，以全新支配者的身份回到舍弃自己的萨尔加迪斯家……

身体因为喜悦而震动的夫萨，完全没有注意到夏斯达滚落在他视界之外的刀，刀身已经再次开始幻化成雾气了。

＊＊＊

──莉琵雅。

夏斯达在天命快要归零之际，在心中呼喊著唯一一名心爱的女性。

莉琵雅之所以决心刺杀皇帝，一定是因为听了夏斯达所说的新时代到来后，想要帮忙实现这个愿望的缘故。她深信只要三百年来的战争结束，新的法律与秩序照亮这个黑暗之国，那么只能饿死或者成为奴隶的孤儿们也能够获得过著幸福生活的权利。

──夫萨啊。

──你说在幼年学校被我痛扁了？还说受不了屈辱而投身于河渠？

──但你这家伙至少还有过机会。拥有让你进入学校就读的双亲，足以填饱肚子的三餐以及温暖的被窝与挡风遮雨的屋顶。你知道这个世界有多少出生时就没有最低限度的权利，只能被当成垃圾对待并消失的年幼生命吗？

──莉琵雅赌上性命想要纠正这样的世界。自己不能因为你这家伙个人无谓的私怨，就辜负了她这样的心念────

「……不会让你阻止我！」

夏斯达应该完全麻痹的嘴里迸出巨大怒吼声的同时，就有灰色龙卷风般的物体以暗黑骑士的右手为中心高高回旋升起。

这正是连整合骑士都只有一小部分人能使用的，神器的记忆解放现象。夏斯达强力无比的心念，开始改写积蓄、演算全Underworld情报的Main Visualizer。

灰色龙卷风显现出没有任何属性的纯粹破坏力，分解所有触碰到它的物体。无法躲避就被龙卷风吞没的夫萨，厚重的斗篷发出「噗咻」的清脆声音后就像烟一样四处飞散。

从里面出现的瘦削中年男子，像要掩盖溶化崩塌的脸一样抬起双臂。下一刻，他的手臂就化成无数肉片迸散──接著全身化为浓密的血雾啪唰一声飞上天空。

＊＊＊

暗黑术师蒂伊‧艾‧耶尔在濒死的暗黑将军身体涌出奇妙龙卷风的瞬间，随即因为非常不妙的预感而用力往后飞退。同时用双手生成风素，全速往后方飞行。

预感在看见右脚被急速扩大的龙卷风碰到，立刻就从膝盖以下灰飞烟灭后转变成最大等级的惊愕。

蒂伊不论是在入浴还是睡眠中都持续以数十种防御术保护全身。因此术式就不用说了，她铁壁般的防御甚至可以反弹投掷的暗器、剑、毒等几乎是所有种类的攻击。

当然，如果是拥有同等级优先度的十侯所发出的全力攻击，确实有可能贯通障壁而伤害到她的肌肤。但绝对不可能出现障壁宛如不存在一般，光是碰到肉体就被削除的现象。

不论脑袋如何用力地否定，右脚还是迅速遭到速度比她全力退后更快的死亡龙卷风削除。虽然蒂伊这种程度的术者，就算被砍掉一只手或脚都能轻易用治愈术复原，但那也得还活著才行。

「咿……啊啊……！」

蒂伊嘴里终于忍不住迸出尖锐的悲鸣。

但她的声音却被同时尖叫的两只哥布林首领给盖过去。

排在蒂伊左边的山地哥布林首领哈卡西与平地哥布林首领酷毕力，全都死命动著短腿急速想从龙卷风旁边逃开。但是根本无法回避龙卷风连蒂伊的全速飞行都能追上的膨胀。

「咕嘎──！」

哈卡西的脚随著难听的叫声打滑，然后跌倒在地。他用尽力量伸出的左手，像是老虎钳一样抓住了酷毕力的脚踝。

「咿呀啊啊啊！放手──！快放…………」

啪唰。

两只哥布林族的支配者随即化成血雾。

噗滋。

蒂伊的整只右脚都消失得无影无踪。

在美貌因为恐惧与绝望而扭曲的暗黑术师公会总长的眼前，──龙卷风的膨胀奇迹似的停住了。

这时已经看不见夏斯达倒在中央的身体。以那附近为中心屹立不摇的倒圆锥形暴风，这时候直径与高度已经扩大到二十梅尔。距离较远的其他六名诸侯迅速退到西侧墙边，排在大厅南侧的各阵营干部们也在千钧一发之际保住了性命。

虽然意识极为混乱，但蒂伊的思考力在朦胧之中理解了龙卷风停止膨胀的理由。

那是为了要保护十几名上级暗黑骑士。也就是说，那道龙卷风是由夏斯达的意志所创造出来的东西。

就像要证实蒂伊的想法一样，龙卷风的上半部渐渐开始变形。

最后出现的是，由半透明雾气所形成的男人上半身。

虽然变得异常巨大，但那很明显就是暗黑将军夏斯达的分身。

插图015

＊＊＊

皇帝贝库达，也就是加百列‧米勒，这时候终于稍微有一点类似惊讶的感情，抬头看著似乎随时要压过来般屹立在那里的龙卷风巨人。

将女暗杀者的首级暴露在众人面前后，看见这一幕的瞬间左端的骑士将会拔剑，这些事情全在加百列意料当中。而且暗杀者公会的首领以毒液还是什么的让想斩杀加百列的男人麻痹，也没有让他感到太意外。

虽然无法达成一击击毙反叛者，藉此在剩下来的九名个体内心深植下忠诚心的企图，但自发性保护皇帝的行动确实值得称赞。加百列一边这么想，一边看著事情的发展──

但倒地的背叛个体身上忽然涌起灰色龙卷风，被它包围的暗杀者公会首领与两只哥布林将军一瞬间就被消灭，这样的情况让加百列不禁感到茫然。

每一名将军个体的能力值应该都差不多才对。这样的话，就算互相对战也不可能一瞬间分出胜负，而是会演变成不停互相削减HP并自行回复的长期战。

但想不到短短几秒钟就有三个个体被消灭。这个Underworld里，还有自己与克里达尚未得知的某种逻辑存在吗──

当他想到这里时。龙卷风巨人已经张开嘴，发出足以撼动天地的吼叫声。

装饰皇座之间墙壁的大部分窗户玻璃都因为承受不住压力往外侧飞散。

巨人握住足有汽缸本体那么大的右拳──

随著轰然巨响朝加百列挥落。

加百列判断用剑抵挡根本没有意义，而且也没有站起来躲避的时间了。视界的右端，可以看见担任副官的瓦沙克敏捷飞退的模样，这时加百列只是静静坐在皇座上等待灰色巨拳。

＊＊＊

夏斯达临死前心念所产生的死亡龙卷风，算是已经超越Underworld系统的现象。

它不是以数值上的攻击力来夺取夫萨与哥布林的天命，造成他们死亡的结果，而是藉由直接在他们的LightCube里灌进「死亡的印象」来破坏摇光，再由这个结果反推回来，让肉体完全消灭。

因此朝向加百列的攻击，也没有对皇帝贝库达的庞大天命造成任何影响。

但是，由夏斯达摇光生成的杀意，经由量子通讯线路到达加百列肉体躺在其中的STL里面──

由暗黑将军夏斯达这名Underworld屈指可数的剑士所凝聚起来的必杀意志，直接击中加百列‧米勒的摇光中枢，也就是所谓的「自我」。

这个时候，夏斯达的主观意识已经和自己挥出的全力一击同化，感觉自己正冲进皇帝贝库达的身体内部。

夏斯达原本肉体的天命明显已经用尽，于是他了解到这将是生涯的最后一击。

无法实现和整合骑士长贝尔库利再次交手的约定实在令人遗憾。但那个男人应该能够理解，暗黑将军希望什么，又为了什么背叛皇帝。

除了暗杀者公会头领夫萨之外，也同时击毙了诸侯中最好战的两只哥布林首领。虽然让暗黑术师公会总长蒂伊逃走算是相当可惜，但那样的重伤应该无法即时再生才对。再加上暗黑骑士团长以及皇帝贝库达的死亡，剩下来的诸侯一定会对与人界的决战感到犹豫。

至少要让他们和同样失去支配者的人界居民订定暂时的休战协定。如果可以因此不再用剑而是用言语来交流，让彼此之间产生某种共识的话……

希望接下来──莉琵雅渴望的和平世界能够到来。

和心念同化的夏斯达，贯穿皇帝贝库达的额头，冲进存在于内侧的灵魂中枢。

只要破坏这个地方，就算是喑黑神，应该也会和夫萨等人一样，存在整个遭到抹灭吧。

随著无声的吼叫，夏斯达的意识与皇帝的灵魂产生冲突──

紧接著，他尝到生涯最后的惊愕。

什么都没有。

如光云般的灵魂中枢，应该存在意识精髓的地方，竟然只有一片浓密的黑暗。

怎么会这样。就连与世隔绝的夫萨，灵魂都因为对生命的强烈执著而发出闪闪光芒啊。

夏斯达的心念就这样被皇帝内部一望无际的黑暗给吞噬。

只见他的身形逐渐消失、蒸发。

──这家伙，这个男人……

──不了解生命是什么吗？

不懂生命、灵魂以及爱情光辉的人，所以才会如此饥渴地求取他人的灵魂。

不论多强力的心念，只要是带有杀意的剑就无法击毙这个男人。

因为这个男人的灵魂虽然活著，却早已跟死亡没有两样。

得把这件事传达给某个将来注定跟这个怪物一战的人知道才行。

要传达出去──告诉某个人……

但这时夏斯达的意识已经被无限的深渊整个覆盖过去了。

…………太遗憾了…………

…………莉琵雅…………

最后爆出这样的思考后，暗黑将军毕库斯鲁‧乌鲁‧夏斯达的灵魂就完全消灭了。

＊＊＊

加百列‧米勒在极为强烈的灵魂光芒贯穿自己的瞬间，随即产生了盖过恐惧的欢喜感。

暗黑骑士的灵魂，充满著比两天前吸进的女暗杀者灵魂还要浓密的感情。像是对那个女人的爱，加上难以理解的类似范围更加广泛的慈爱感情，还有把这些当成动力来源的强烈杀意。

爱与憎恨，这个世上还存在比这更美味的东西吗？

这时候的加百列，可以说完全没有意识到自己的生命陷入危机当中。即使看见三个个体在暗黑骑士的攻击下变成肉片飞散，加百列依然把吸收骑士的灵魂看得比自身安全还要重要。

如果加百列畏惧骑士的攻击而希望自己能够生存的话，夏斯达的杀意就会经由STL破坏加百列的生存本能，然后产生连锁效应把他的摇光全部轰飞。

但是加百列‧米勒是个不知生命为何物的人类。对他来说，包含自身在内的所有生命，都不过是跟幼时大量杀戮的昆虫同样的自动机械而已。加百列唯一的愿望就是，查明成为机械动力源的灵魂，也就是充满谜团的光辉云层究竟有何秘密。

因此由夏斯达摇光所产生的破坏讯号，就只能平白通过加百列摇光里面的一整片虚无，没有发生任何冲突就消失了。

虽然加百列完全不清楚这样的道理，但他还是一边咀嚼骑士的灵魂，一边把两件事留在记忆里面。

首先是这个世界里，除了一般VRMMO里游戏藉由武器与咒文的攻击外，也存在另一种攻击方法。

而那种攻击方法似乎对自己没有效果。

之后得要克里达调查刚才那种现象的原理才行。加百列一面这么想，一面缓缓从皇座上站起来。

＊＊＊

存活下来的六名诸侯──暗黑术师公会总长蒂伊‧艾‧耶尔、拳斗士首领伊斯卡恩、商工公会头领连基尔、巨人族首领西古罗西古、半兽人首领利鲁匹林、食人鬼首领弗鲁咕鲁──他们有的靠在墙壁上，有的瘫坐在地上，有的正一边止著重伤的血，一边茫然抬头看著皇帝贝库达的模样。

所有人心中只存在恐惧这种感情。

暗黑将军夏斯达令人吓破胆的超级攻击──一瞬间把三名将军变成血雾，同时也把诸侯中被认为相当有实力的蒂伊右脚削除的一击，皇帝竟然挺身从正面承受下来，而且没有受到任何伤害。

有实力者支配一切。

皇帝贝库达拥有六名诸侯，以及他们背后一百名以上的军官加起也远远不及的力量已经是一目了然的事实。

如同微小的波浪往外扩散般，所有人都深深低下头，对皇帝表达恭顺之意。就连敬爱的骑士长遭到杀害的暗黑骑士团也不例外。

这时皇帝的声音流畅地响彻整座大厅：

「……失去将军的军队，马上由下一个位阶的人员接手指挥权。一个小时后，按照原定计划开始进军。」

皇帝没有因为出现反叛者而发怒或是责备众人。这样的事实让将军们更加感到恐惧。好不容易让右脚止血的蒂伊，高高举起连指尖都伸直的右手并大叫：

「皇帝陛下，万岁！」

隔了短暂的几秒钟后──

「万岁」的呼喊变成足以撼动整座黑曜岩城的轰然巨响，而且还重复了许多次。

5

爱丽丝环视了一下配给给自己的野营用帐篷，接著轻轻叹了口气。

简易床铺相当干净整齐，铺在地板上的羊皮是全新品，空气当中也只有太阳的味道。虽然这些都相当令人高兴，但这很明显不是为了爱丽丝而急遽空出来的帐篷。也就是说，骑士长贝尔库利为了爱丽丝加入阵营时能使用，事先就多设置了一个骑士用帐篷。

虽然也可以把这种行为当成是受到信赖的证明，但了解骑士长为人的话，就会觉得自己的想法与行动已经完全被对方看透了。

不对──应该不至于完全被看透。因为就连骑士长，似乎也没有预想到爱丽丝会带著桐人一起过来。所以这里只准备了一张简易床铺。

爱丽丝碰著桐人的背部，诱导他坐到床铺上。下一个瞬间，年轻人立刻从喉咙发出细微的声音并准备伸出左手。

「好好好，等一下喔。」

跑到放在入口旁边的行李袋前面，爱丽丝随即从里头抽出黑白两把长剑。接著回到床边，把它们放在桐人大腿上。结果他用左臂抱住剑后就安静下来。

爱丽丝坐到他身旁，一边脱掉靴子一边思考著。

虽然对艾尔多利耶说出有必要的话会背著桐人战斗这样的大话，但实际上确实有点困难。如果只有变瘦的桐人也就算了，再背上夜空之剑与蓝蔷薇之剑的话，行动就会因为重量而受到限制。

虽然也曾想过一直把桐人放在雨缘的鞍上，但既然敌人也有骑乘飞龙的暗黑骑士，那就会出现空中战的情况吧。这么一来，还是希望尽量减轻负荷的重量。

虽然不愿这么做，但战斗中请辎重部队的某个人帮忙照顾桐人似乎是最合理的选择。但问题是能不能这么顺利找到可以信赖的人。

旧识的众整合骑士一定全都会到最前线，而自己又不认识任何一般平民士兵。但事到如今也实在不想拜托艾尔多利耶帮忙寻找合适的人选。

「桐人……」

爱丽丝由正面窥看年轻人的脸，然后以双手轻轻包覆他的脸颊。

自己完全没有打算把桐人当成包袱。如果能够恢复意识，他一定会成为比任何人都要可靠的人界守护者。之所以会像这样带他一起来到前线，完全是因为觉得说不定能在这里发现让他恢复意识的可能性。

骑士长贝尔库利表示，桐人弹开了他施放的「心念之剑」。还说那是为了要保护爱丽丝。

真的可以相信他的发言吗？

首次在修剑学院相遇时，是逮捕者与罪人。在中央圣堂八十楼再次相遇时，是处刑人与反叛者。甚至在最上层诉说最后一句话的瞬间，两人之间无论再怎么美化，也只是暂时休战中的关系。

──从那场战争之后你就一直失去意识了，却还想从叔叔的剑气下保护我吗？

──你……到底是怎么看我的呢？

这个问题碰到桐人黯淡的眼睛后，反弹回爱丽丝自己身上。

那自己又认为和这个年轻人是什么样的关系呢？

如果要用一句话来形容在中央圣堂时的桐人，那么最适合的就是「面目可憎」了吧。敢对著整合骑士爱丽丝‧辛赛西斯‧萨提骂那么多次「笨蛋」的人，这名年轻人可以说是空前绝后了吧。

但是在最后一战时，桐人面对最高司祭亚多米尼史特蕾达时的背影──

看见那名剑士黑色外套下襬不停飘动，左右手各握著一把剑的背部，爱丽丝的心就产生强烈的震动。心中的想法就只有「竟然有如此坚强，但又哀切到让人觉得心痛的模样」。

这样的感情变成淡淡的刺痛感，到现在都还残留在爱丽丝内心深处。

但因为害怕知道疼痛的理由，所以一直遮盖著自己的心。

──因为我是被创造出来的存在。只不过是持续占据爱丽丝‧滋贝鲁库身体的战斗用人偶罢了。自己根本没有资格，去拥有战意之外的感情。

但是，说不定……

就是因为我压抑自己的心，你才会听不见我的声音？

如果我施放所有的「心念」，你是不是就会有所回应呢？

爱丽丝吸进满满的空气并屏住呼吸。

桐人被自己双手包覆的脸颊相当冰冷。不对，是自己的手掌太过火热。

爱丽丝轻轻把他的脸颊拉过来，从至近距离看著他的黑色眼睛。那简直就像黑夜一样阴暗，但又感觉遥远彼方可以看见一些闪烁的小星星。

爱丽丝一边凝视著那些星星，一边缓缓把脸凑过去──

忽然传出铃铛的清脆声音，让爱丽丝的身体弹了起来。

虽然急忙环视了一下帐篷内部，但当然没有任何人在。最后终于发现是挂在帐篷入口处的摇铃被人拉动了。

有客人来访。爱丽丝没来由地干咳了一声，整理好头发后迅速横越帐篷。

反正一定是艾尔多利耶又来抱怨了吧。这次一定得斩钉截铁地告诉他，无论说什么自己都不打算把桐人赶走。

帐篷的出入口有两层帷幕，把头伸出内侧的薄布后，爱丽丝就用左手一口气把外侧的厚重毛皮拉开。

而她正要张开的嘴唇也在这时候停了下来。

站在她眼前的不是整合骑士，甚至连一般兵都称不上。这让爱丽丝忍不住凝视著访客。

「那……那个……」

娇小的来访者怯生生地以细微的声音这么说道，双手同时递出盖著锅盖的锅子。

「骑士大人，帮……帮您送晚餐来了。」

「……这样啊。」

爱丽丝稍微瞄了一下天空。不知不觉间，傍晚的红霞确实已经退到西方的天空去了。

「谢谢……辛苦了。」

慰劳对方并把锅子接过来的爱丽丝，再次上下打量著对方的模样。

那是一名还很年轻，看起来只有十五六岁的少女。

长度大概到肩膀下方的头发是漂亮的红色。大大的眼睛同样是类似红叶的颜色，另外白皙的肌肤与高挺的鼻梁都显示出她有北方帝国的血统。

身上穿著轻装铠甲的女孩似乎也是守备军的一员，但铠甲下方的灰色上衣与裙子好像是哪所学校的制服。

竟然连这样的小孩都得上战场……如此想著的爱丽丝准备咬紧嘴唇时，忽然又觉得奇怪而眨了眨眼睛。

少女的长相有种似曾相识的感觉。但以前都在中央圣堂生活的爱丽丝，几乎没有和一般平民接触过。

这时候，躲在红发少女身后的第二名少女才畏畏缩缩地现出身影。

「那……那个……这是面包和飮料。」

听见有著接近黑色的深茶色头发与深蓝色眼睛的少女发出微弱声音后，忍不住露出微笑的爱丽丝跟著也接下她递过来的篮子。

「不用这么害怕，我又不会把你们抓来吃了。」

一说到这里，爱丽丝的记忆才苏醒过来。

她曾经听过这极为紧张的声音。这两个人就是那个时候的──

「你……你们不会是……北圣托利亚修剑学院的学生吧……？」

一问之下，两名少女才像是放下心头的大石般，让紧绷到极点的脸颊瞬间放松下来。但马上又端正姿势，靠拢穿著靴子的脚跟并报上姓名：

「是……是的！我……我是隶属人界守备军补给部队的缇洁‧休特里涅初等练士！」

「同……同一部队的罗妮耶‧阿拉贝鲁初等练士！」

爱丽丝反射性地回礼，在内心呢喃了一句「果然没错」。

准备把桐人和尤吉欧从学院带走时，请求允许跟他们道别的就是这两位女孩。

就算守备军的人手再怎么不足，应该还不至于会征召学生入伍才对。这样的话，她们应该是自愿从军，由熟悉的央都来到这危险的战地了？这两名稚气未脱的少女，为什么愿意做这种牺牲呢……

右手拿著锅子，左手提著篮子的爱丽丝认真地盯著两个人看，结果自称罗妮耶的深茶色头发少女就再次躲到名为缇洁的红发少女背后。缇洁虽然也缩起身体，但最后还是带著做出必死决心的表情开口表示：

「那……那个……骑……骑士大人……我……我知道这么问真的非常失礼……」

极为严谨的语气再次让爱丽丝忍不住露出苦笑，但她还是尽可能把苦笑变成温柔的笑容插话道：

「听我说，你们不需要这么拘谨。因为在这座野营地里，我也不过是一名为了守护人界而来的剑士而已。直接叫我爱丽丝就可以了，缇洁小姐……还有罗妮耶小姐。」

结果缇洁以及从她背后轻轻冒出头来的罗妮耶同时露出哑然的表情。

「……怎……怎么了？」

「没……没有……只是……跟以前在修剑学院见到您时的印象完全不一样了……」

「是吗……」

觉得奇怪的爱丽丝歪了歪头。自己虽然不是很清楚，但是住在卢利特村的这半年里，真的有什么样的改变吗？虽然骑士长说出脸变圆了这种毫无凭据的感想就是了。

现在回想起来，确实可能因为赛鲁卡所做的料理实在太美味而忍不住吃太多了……但应该不至于胖到连外表都改变吧……

差点要绷紧的脸颊再次露出笑容后，爱丽丝又继续表示：

「那……你们有事找我吗？」

「啊……是……是的。」

紧张的神情稍为变淡了一点的缇洁，一瞬间抿紧嘴唇后才又说道：

「那个……我们听说骑士大……爱丽丝大人在骑乘飞龙来到营地时，身边还带著一名黑发的年轻男性……然后，我们就想那位男性是不是我们认识的人……」

「啊，嗯……对喔，说得也是。」

爱丽丝这时才终于了解少女的来意，于是点著头说：

「你们在学院的时候就跟桐人很熟了……」

爱丽丝开口这么说的瞬间，两名少女的脸就像花蕾绽放般充满光芒。罗妮耶的蓝色眼睛里甚至渗出些许眼泪。

「果然是……桐人学长……」

罗妮耶以细微声音这么呢喃著，缇洁则是握住她的手以充满期待的声音大叫：

「那么……尤吉欧学长也在喽……！」

一听到这个名字，爱丽丝就猛然吸了一口气。

她们两个人完全不知道，半年前在中央圣堂展开的那场激斗以及最后的结果。根本不可能知道。因为关于最高司祭死去的消息，就只有整合骑士知道而已。

两个人往上看著说不出话来的爱丽丝，接著露出感到不可思议的表情。爱丽丝交互凝视著缇洁与罗妮耶的眼睛后，缓缓伏下了视线。

事到如今，不可能隐瞒她们了。

而且她们两个人有知道一切的权利。因为她们应该是为了再次与桐人以及尤吉欧见面，才会志愿参加守备军，来到这个营地……

爱丽丝下定决心后开口说道：

「对你们来说……可能会觉得很难过。但我相信身为桐人以及尤吉欧学妹的你们，一定可以承受这个事实。」

说完她往后退一步，抬起毛皮帷幕，催促两人进入帐篷。

让爱丽丝有点失望的是，即使缇洁与罗妮耶走进桐人视界当中，他依然没有任何反应。爱丽丝一边压抑失望的感觉，一边站在帐篷的墙边看著这悲壮的光景。

罗妮耶到坐在床上的桐人面前跪了下来，以娇小的双手包裹住年轻人的左手，脸上不停流下泪水。

但更让人心痛的是，整个人瘫坐在皮革地毯上，持续凝视著眼前那把蓝蔷薇之剑的缇洁。在传达尤吉欧的死讯时，她变得跟纸一样苍由的脸上没有任何表情。只是默默地往下看著从中折断的剑身。

爱丽丝本身几乎没有机会直接和名为尤吉欧的年轻人交谈。

交谈的机会大概就是逮捕他到中央圣堂并丢进地下监牢之前，以及在高塔的第八十层迎战他们时，再来就只有与亚多米尼史特蕾达进行最终决战时曾与他并肩作战了。

虽然对尤吉欧不仅只从骑士长贝尔库利手里赢得胜利，还把的身体化成剑来破坏巨剑魔像，最后更砍飞最高司祭一条手臂的意志力感到衷心佩服，但关于他的记忆大多是根据赛鲁卡叙述给自己听的回忆。

赛鲁卡表示，尤吉欧是相当温顺又思绪缜密的少年，似乎经常被青梅竹马的爱丽丝‧滋贝鲁库拖著去进行各种冒险。如果是这样的个性，那么和桐人一定是一对相当好的伙伴。

桐人和尤吉欧在修剑学院里一定也到处闯祸。就像爱丽丝本身一样，缇洁与罗妮耶就是被这样的两个人给吸引，并受到很大的影响。

──所以，拜托你们，一定要承受住这样的伤悲。桐人和尤吉欧他们是为了守护非常重要的事物而战，并因此而受伤、失去意识与生命。

爱丽丝一边在内心这么对两人说道，一边持续注视著她们。

在人界生活的人民，如果受到过于强大的恐惧与悲伤这种精神上的冲击，就有可能因为无法承受而罹患精神疾病。就像前阵子遭受黑暗军队袭击的卢利特村，似乎也出现了几名身体没有受伤，但是却卧病在床的村民。

缇洁她一定深爱著尤吉欧吧。

对如此年轻的她来说，接受心爱的人死去这种巨大的冲击绝对不是一件简单的事。

爱丽丝的视线前方，瘫坐在地上的缇洁右手忽然动了一下，然后开始一点一点靠近蓝蔷薇之剑。

爱丽丝带著一丝紧张看著她这种模样。蓝蔷薇之剑虽然从中折断，但依然是最高等级的神器。虽然不认为缇洁能够使用它，但过于深刻的绝望与悲伤有时候会引发预料不到的力量。没有办法预测到会发生什么事。

缇洁以僵硬动作伸直的手指，终于碰到淡蓝色剑身。她没有触碰剑刃，而是轻轻划过被磨得相当光滑的侧面。

就在这个瞬间──

折断的剑身发出微弱但是确实的蓝色光芒，推开从采光孔透进来的红色夕阳。

同一时间，缇洁全身震动了一下。

似乎感觉到什么的罗妮耶也回过头看向自己的朋友。紧绷的空气当中，缇洁的睫毛上缓缓出现透明水滴并无声滴落。

「……刚才…………」

粉红色嘴唇里发出细微呢喃声。

「……我听见了……尤吉欧学长的声音……他跟我说不要哭……他一直都在这里……」

眼泪潸潸不绝地滴落，缇洁最后终于把脸趴在剑上，像个小孩子一样发出剧烈的呜咽声。罗妮耶也把脸靠在桐人膝盖上嚎啕大哭。

虽然眼头因为这令人悲痛，但是又相当清纯的情景而发热，但是──

爱丽丝还是在脑袋角落想著「真的有这种事吗」。

她虽然没有听见尤吉欧的声音，但是确实看到剑一瞬间发亮。这样的话，缇洁听见的发言也不见得一定是幻听。

蓝蔷薇之剑上……真的残留著类似尤吉欧灵魂的物体吗？

插图016

爱丽丝在发动武装完全支配术时，也有一种金木樨之剑与自己的意识一体化的感觉。但尤吉欧则是实际让自己的身体与蓝蔷薇之剑融合，而且在这样的情况下受到致命伤。

所以说不定真的可能出现持有者的意识残留在半截剑上的情形。

但是刚才缇洁说尤吉欧呼唤了她。如果真是如此，那么残留在剑上的就不只是没有灵魂的残响，而是真正的意识──或者是心念吧。

是少女因为爱慕之情而产生的幻听吗？还是说……？

真是令人著急。如果是桐人，一定能帮忙找出这个现象的秘密吧。从这个世界的外侧，一大群神秘神明所居住的地方掉落到这里来的他一定没问题才对。

在不停旋转的思考水平面上，忽然浮现如小泡沫般的一句话并啪叽一声爆裂开来。

世界尽头的祭坛。

据说这个不怎么出名的地方，设置有通往世界外侧的门。

如果能到那里，所有的谜团就能够一瞬间获得解答吗？桐人失去的意识也可以恢复吗？但是据说祭坛是位于离开东大门后的遥远南方。也就是在暗之种族支配的黑暗领域遥远边境。

想到那个地方去，就不只是得防御在大门外布阵的敌人大军，甚至要突破包围才行。不对，就算突破敌阵，自己也不可能放下大门的防卫不管直接往南方前进。身为被赋予过大力量的整合骑士，爱丽丝必须负起守卫人界的责任。

还是干脆把自己当成诱饵来吸引所有敌军，一面让他们远离大门一面朝著祭坛迈进。但是对黑暗领域的人民来说，侵略人界是数百年来的悲愿，应该没有比这个愿望更有魅力的事情了……

果然就算要前往世界尽头的祭坛，也得先把黑暗军队完全歼灭才行。

最后得到的结论，让爱丽丝忍不住闭上眼睛。

虽然浮现歼灭敌人这种相当浩大的想法，但现状就连要抵御敌人的先锋都很困难吧。但为了守护缇洁、罗妮耶还有桐人，自己还是得这么做。

静静呼出一口气后，爱丽丝中止持续了数秒的默思，走到两名哭哭啼啼的少女身边。

6

索鲁斯的残照在很久之前就已经消失在西边的远方，但东大门后面看起来呈细长状的黑暗领域天空，却还一直固执地残留著不祥的血色。

简直就像要遮蔽这样的光景一般，人界守备军野营地中央──白天被当成飞龙起降场的草地上围起了一片纯白布幕。在布幕前方高处不停飘动的公理教会旗帜下，聚集了三十名左右的整合骑士与守备军队长，只见他们都一脸严肃地看著彼此的脸。

爱丽丝发现他们没有分成骑士与士兵后，随即因为有些惊讶而停下脚步。

整合骑士穿著光辉的银制铠甲，队长们则是穿戴华丽度虽然不及但优先度也相当高的钢铁铠甲，一群人同样单手拿著装有西拉鲁水的玻璃杯热烈地进行议论。竖起耳朵倾听的话，就能发现那些拐弯抹角的敬语已经完全被省略了。

「大小姐，以急就章的集团来说，已经颇像一回事了吧。」

身旁忽然传出低沉的声音，让爱丽丝急忙往该处看去。

把双手扠在东方风味服饰怀里的骑士长贝尔库利，以动作制止了准备敬礼的爱丽丝，接著说道：

「这支守备军里，已经省略所有的繁文缛节了。幸好禁忌目录里没有『一般民众跟骑士说话前，一定得仔细向对方问安』这样的条款。」

「这……这样啊……这确实是一件好事，但先不说这个了……」

爱丽丝再次把视线移回军议会场上。

「──其他整合骑士到哪里去了？目前看来，那边只有十名左右的骑士。」

「很遗憾，那些几乎就是全部了。」

「咦……咦咦？」

用手掌遮住忍不住提高的声音后，爱丽丝以有些苦涩的表情往上看著骑士长。

「怎么可能……骑士团包含我在内应该有三十一名成员才对。」

人数正如最新的整合骑士艾尔多利耶被赋予的萨提汪这个神圣语名所表示。

贝尔库利在参杂叹息声当中回答了一句「是没错啦」后，随即又压低声音表示：

「大小姐也知道吧。元老长裘迪鲁金对记忆产生问题的骑士施予『再调整』的处置。他死去的时候，在元老院再调整中的七名骑士仍未觉醒。」

「…………！」

爱丽丝忍不住瞪大眼睛。贝尔库利把视线从出现这种反应的爱丽丝身上移开，以更加苦涩的声音继续说道：

「知道再调整用术式的只有裘迪鲁金与最高司祭两个人。他们已经死亡的现在，就必须花时间解析术式才能让七名骑士觉醒，但我们现在根本没有这种时间。只有一名尚未进行再调整，单纯处于冻结睡眠中的骑士，我好不容易才让那家伙醒过来，只不过……」

感觉骑士长的语气有些吞吞吐吐，于是爱丽丝开口询问：

「那一个人是？」

「……『无声』的谢达。」

「…………！」

虽然是没有直接见过面，只听过几则轶事的名字，但爱丽丝还是不由得屏住了呼吸。因为那些轶事的内容都相当恐怖。

但是贝尔库利却像是表示这些事以后再说般干咳了一声，接著继续说明目前的战力：

「……总而言之，目前觉醒的整合骑士共有二十四人。当中有四个人留下来管理中央圣堂和央都，四个人被我派去负责尽头山脉的戒备。剩下来的十六人……就是能够用在这条绝对防卫线的上限人数了。当然也已经把我和大小姐算进去喽。」

「十六个人……吗？」

爱丽丝差点就加上「只有」几个字，但还是咬起嘴唇忍住了。

而且仔细确认这些人长相的话，就能发现目前在议场的十四个人里，有半数以上是没有神器──也就是无法使用武装完全支配术的下级骑士。光是以剑斩杀敌人的话，他们当然都是能够独自砍杀一两百只哥布林的勇士，但无法期待拥有改变全体战况的爆发力。

这时贝尔库利改变语气对沉默下来的爱丽丝说：

「对了，说到要找谁照顾那名年轻人嘛……我看干脆由我拜托后卫部队……」

「啊……不用了，不必担心这件事。」

爱丽丝一面对骑士长生疏的贴心举动露出微笑一面回答：

「刚好有在修剑学院担任他随侍剑士的志愿兵……我已经请她们开战后照顾桐人了。」

「哦，那真是太好了……那怎么样啊？黑发小子和过去曾有过交流的人接触后，有没有出现什么反应？」

爱丽丝脸上的笑容消失，无言地摇了摇头。

贝尔库利短短叹了口气，低声说了句「这样啊」。

「……这件事情我只跟你说。老实说，我觉得那名年轻人可能是决定接下来这场战役胜败的关键人物……」

爱丽丝惊讶地抬头看著骑士长的脸。

「就算有大小姐和伙伴的帮忙，他还是完成了以剑击毙元老长与最高司祭这种超乎想像的壮举。纯粹比较心念强度的话，可能连我都不及他。」

「……怎么可能有这种……」

事到如今也不可能再对桐人的实力感到怀疑，但骑士长贝尔库利的心念是花了两百年以上的时间锻炼出来的成果。相对的桐人只是尚未成年的学生。爱丽丝反而觉得，如果是剑技与体术就算了，只有心念这一个项目绝对比不上骑士长才符合常识。

但贝尔库利却以充满自信的动作否定了爱丽丝的发言。

「之前以心念互击时，我确实感觉到了。那个小伙子拥有跟我相同，甚至是超越我的实战经验。」

「实战……？这是什么意思……？」

「就是字面上的意思，也就是攸关生死的战斗啊。」

这才真的让人想回答「怎么可能呢」。

生活在人界的居民，全都受到禁忌目录与帝国基本法的保护，或者可以说束缚。就算可以用木剑比试好了，一般人从出生到老死大概都不会经历过以真正的剑进行某一方可能耗尽天命的实战。

唯一的例外就是整合骑士，因为他们会跟想侵略尽头山脉的哥布林以及暗黑骑士进行实战。但那在漫长的任期里最多也只有一两次，而且整合骑士方的战力占压倒性优势，老实说很难称为攸关生死的战斗。

考虑到这些事情后，就能确定人界里实战经验最丰富的，就是从骑士团规模比现在小很多的时代就一直和黑暗军队战斗的贝尔库利了。实际上，在他刚成为整合骑士时──虽然很难相信──似乎曾经惨败于当时的暗黑骑士手上，好不容易才拖著一条命逃了回来。

桐人他实战的次数会赢过这样的贝尔库利？

如果真的有这种事，那也不会是在这个世界的经验。

应该是在他真正的故乡，也就是「外面的世界」。但那里同时也是真正创造地底世界的诸神明所居住的世界才对。但在那边还有实战？到底是跟什么人赌上生死呢……？

不知道究竟该如何想下去的爱丽丝，稍微犹豫了一下才下定决心。

既然这样，就只能对贝尔库利说出一切了。像是外面世界的存在──以及世界尽头的祭坛存在通往那里的大门等事情。

「……叔叔……其实我和最高司祭战斗的时候……」

当爱丽丝选择用词遣字把话说到这里时──

骑士长后方突然传来尖锐的声音。

「阁下，时间到了。」

吓了一跳的爱丽丝看向声音的主人。

一名全身包裹在暗夜当中依然发出醒目淡紫色光芒的铠甲与头盔当中，左腰挂著白银细剑的整合骑士站在那里。

一看见完全遮住脸孔，带著猛禽翅膀形状的头盔，爱丽丝心中浮现的感慨──以极端一点的说法来表现的话，大概就是「呜恶」这两个字了。

对爱丽丝来说，来者恐怕是这个世界里和她最合不来的人物。那个人正是副骑士长，整合骑士排名第二的法那提欧‧辛赛西斯‧滋。

爱丽丝很努力地不把内心的感情显露在脸上，接著反射性将右拳贴在左胸，并把左手按在剑柄上行了骑士礼。

相对的法那提欧也喀锵一声震响铠甲做出同样的动作。但是与双脚稍微张开并且直立的爱丽丝不同，法那提欧是把重心放在右脚并且垂下左肩，摆出看起来比较柔弱的姿势。

实在没办法接受这个人的这种个性……爱丽丝一边放下手一边在心中这么自言自语。

虽然自认为已经以铠甲、头盔以及带著威严的语调来掩饰，但在同性的眼里看起来，法那提欧的动作就已经像一朵巨大的花朵，不断散发出难以掩盖的强烈女人味。而这正是孩提时期就被带到中央圣堂的爱丽丝终究无法学会的「技能」。

副骑士长法那提欧在中央圣堂第五十层与桐人、尤吉欧战斗，被桐人的武装完全支配术直接击中后身负濒死的重伤。爱丽丝从在现场的下级骑士口里听说过，桐人当时却对著费尽千辛万苦才打倒的法那提欧施加治愈术，甚至还用不可思议的术式把她传送到某个地方去。

虽然觉得这确实很像桐人会做的事，但内心还是觉得不以为然。

说起来法那提欧明明一心喜欢著骑士长贝尔库利，但是却还把对自己著迷的四名下级骑士编列为自己的直属部下。难道不觉得永远只能憧憬，一辈子都无法获得青睐的他们很可怜吗？至少应该时常摘下头盔来让他们看看脸庞吧。

当爱丽丝浮现这种稍微带著一点私怨的想法时，法那提欧就用双手抓住头盔的侧面，这样的举动让爱丽丝著实吓了一跳。

被解开的挂钩发出「啪叽、啪叽」的声音，接著淡紫色头盔就随手被往上拉起来。整个扩散开来的艳丽黑发，在营火照耀下发出丝绢般的光芒。

在中央圣堂时，只有在前往大浴场途中偶然遇见法那提欧才能看到她的真面目。记忆当中，这应该是副骑士长第一次在众人环视的环境下脱下头盔。

爱丽丝凝视跟以前比起来似乎变得柔和一些的美貌，并且理解到产生变化的理由。原来是圆润的嘴唇上涂抹了淡淡的口红。想尽办法要隐藏女性身份的她竟然会化妆──？

法那提欧对著茫然站在现场的爱丽丝露出平稳的微笑。

「好久不见喽，爱丽丝。看见你平安无事真令人高兴呢。」

「…………」

「喽」？「呢」？

说不出话的时间又加了三秒钟左右，接著爱丽丝才终于能够向对方打招呼：

「好……好久不见了，副长。」

「叫我法那提欧就可以了。对了，爱丽丝，我刚才听说……你把那个黑发的小子也一起带来了？」

以轻松态度说出的发言，让爱丽丝把惊讶丢到一边去，取而代之的是高涨的警戒心。虽然法那提欧的伤是由桐人与贤者卡迪娜尔治愈，但她不见得知道这个事实。她对打倒自己的桐人有所怨恨与憎恶也不是什么不可思议的事情。

「是……是的。」

爱丽丝简短地回答，而副骑士长则是带著嫣然微笑点了点头。

「这样啊。那军议之后，可不可以让我跟他见个面？」

「……法拉提欧阁下为什么要见他？」

「别露出那种表情嘛。事到如今，我也不会想杀害那个年轻人了。」

压抑下微笑中一丝苦涩的感情，法那提欧耸著肩并这么说道。

「我只不过是想跟他道谢，听说是那个小伙子帮受到致命伤的我治疗。」

「……你已经知道了吗？但我想没有必要跟桐人道谢。因为我听说帮副长疗伤的，是名为卡迪娜尔的前任最高司祭。很遗憾的是……那位司祭大人已经在半年前的战争中亡故了。」

稍微放松肩膀力道的爱丽丝一这么说，法那提欧便迅速把视线朝向天空并点了点头。

「嗯……我还有一些朦胧的记忆。我还是第一次接受那么温暖且强大的治愈术。但是，把我送到那位大人身边的就是桐人，而且……还有另一件事也想向他道谢。」

「另一件事……？」

「没错──就是和我战斗并且把我打倒。」

……她果然想找桐人算帐吗？

面对往后退了半步的爱丽丝，法那提欧一脸严肃地摇了摇头。

「这是我的真心话。因为那个小伙子，是我以整合骑士的身份活了这么久以来，第一个知道我是女性依然全力跟我战斗的男人。」

「啥……？你这是……什么意思……」

「我以前也像你这样，没有戴上头盔就以素颜直接战斗。但某一天我就注意到了。不论是担任模拟战对手的男骑士，甚至是进行生死决斗中的暗黑骑士，剑招都有些畏缩。因为我是女人这样的理由而留手，对我来说是比战败倒地还要大的屈辱。」

但这也是没办法的事吧。几乎没有什么男人可以抗拒由素颜的法那提欧所散发出来的女人味。

自从在卢利特村近郊过生活后才首次知道，人界大部分地方，女性都几乎不会从事握剑的天职。例外大概就只有贵族或者领主的子女，至于一般平民女性原则上只有结婚生子并在家做家事的生活方式可以选择。

如果这种守旧的观念和禁忌目录一样禁锢男人们的心，那就实在是太讽刺了。就是男人应该保护女人这样的先入为主观念，让他们的剑招在法那提欧的花容月貌面前变得迟钝吧。既然生活在黑暗领域的暗黑骑士也会娶妻生子，那就不可能是例外。至于外表完全不同的哥布林和半兽人等亚人族，则可能和人类有不同的价值观。

但同为女骑士的爱丽丝，之前从来没有注意到男骑士的退缩还是留手之类的事情。因为不论对方是留手还是尽了全力，她都有自己绝对比较强的自信。

──这样的愤怒，不就是你拘泥于自己是女性这件事的最佳证明吗？

当爱丽丝这么想的同时，法那提欧也低声说出完全相同的话：

「──我用这个头盔遮住面容与声音，为了不让敌人近身而学会连续剑技。但这正是因为我拘泥于自己性别的缘故。那个小伙子瞬间看穿这一点，然后全力跟我过招。在和他的战斗里，我使尽浑身解数的剑技与术式并被他打败。当托卡迪娜尔大人的福捡回一条命的我恢复意识时，心中无聊的坚持就消失了……总而言之，只要我拥有让对方无法留手的实力就可以了。那个小伙子让我注意到这单纯的事实，而且还让我活下来，想向他道谢也不是什么不可思议的事情吧？」

以认真的表情说到这里，法那提欧脸上忽然露出恶作剧的微笑。

「除此之外……也有点生气啦。小伙子竟然对著素颜的我说完全感觉不到一丝女人味。所以就想试试看，帮小伙子做各种服务的话，他会不会就醒过来了。」

「什么……」

在说什么蠢话啊。

如果桐人真的这样就醒过来，那么自己至今为止所做的努力不就太空虚了吗？而且桐人也确实有让人无法坚决否认这种可能性的部分。

毫不隐瞒眉间险恶的气息，爱丽丝以尖锐的声音反击：

「很谢谢阁下的心意，但他目前在帐篷里休息。所以就由我来帮忙传达法那提欧阁下的谢意吧。」

「哎呀……」

副骑长也轻轻动了一下眼角。

「要和小伙子见面还得要你许可吗？在中央圣堂的时候，你要求跟值勤中的骑士长阁下见面时，我不记得曾经因为私情而拒绝过你啊。」

「我才想说，我跟叔叔见面根本不需要法那提欧阁下的许可吧。说起来呢，如果想被男性骑士彻底打败，那么拜托叔叔不就可以了吗？」

「哎呀，骑士长阁下不能算数喔。他是世界最强的剑士，对所有人留手本来就是理所当然。他甚至还卖人情给暗黑将军呢。」

「哦，是这样吗？和我练剑时，叔叔总是浑身大汗而且相当认真喔。」

「……阁下！她说的是真的吗？」

「说起来都是叔叔太宠这个人了……！」

爱丽丝与法那提欧同时看向旁边。

但骑士长已经不在那里了。

几分钟前贝尔库利才站在那里的地方，现在只有一团枯掉的野草沙沙地滚动著。

从下午六点开始的军事会议，就受到担任司仪的副骑士长法那提欧‧辛赛西斯‧滋，以及新加入阵营的整合骑士爱丽丝‧辛赛西斯‧萨提所发出的剑气所影响，只能在极为紧绷的空气下进行。

结束简短自我介绍的爱丽丝，随即迅速坐到准备在最前排的椅子上。

「……爱丽丝大人。」

坐在旁边的艾尔多利耶畏畏缩缩地递过装有西拉鲁水的杯子，爱丽丝一把抓过去后，一口气把冰凉又酸甜的液体喝光。长长呼出一口气的她，好不容易才成功转换心情。

插图017

话说回来──

拥有神器的上级整合骑士真的太少了。知道名字与长相的，大概就只有骑士长「时穿剑」贝尔库利、「天穿剑」法那提欧、「霜鳞鞭」艾尔多利耶，以及「炽焰弓」迪索尔巴德。

再加上拥有「无声」异名的谢达‧辛赛西斯‧推鲁弗，以及非常年轻的少年骑士连利‧辛赛西斯‧推尼赛门似乎也有神器，但几乎是首次见面的缘故，根本不知道他会使用什么样的剑技。总之以上的几名再加上「金木樨」爱丽丝共七个人，就是上级骑士的总数了。

剩下来的九个人里，包含直属于法那提欧的「四旋剑」在内，全都是没有神器的下级骑士。而且也可以看见极会闹事，连贝尔库利都拿她们没办法的见习少女骑士里涅尔‧辛赛西斯‧推尼耶特以及费赛尔‧辛赛西斯‧推尼奈的身影。现在是乖乖地坐在角落的椅子上，但谁也不敢保证她们到时候会不会上战场。

总而言之，这仅有的十六个人，就是整合骑士团能投入这条绝对防卫线的所有战力了。

另一方面，共有三十名左右的人界守备军部队长参加会议。虽然士气不低，但一眼就能看出剑技的实力和整合骑士之间有很大的差距。爱丽丝等上级骑士就不用说了，就连下级骑士也可以连续跟他们三十个人比赛并轻松获胜吧……

「──这四个月来，我们检讨过各种作战……」

法那提欧不知不觉间就开始说起话来，而她的声音也把爱丽丝的意识拉回到现实。

「结果得到的结论是，以目前的战力要抵抗敌军的总攻击可以说相当困难。一旦被包围，我军就完全没有胜算了。」

以天穿剑细长的剑鞘代替指示棒，法那提欧在设置于军议场深处的地图上某一点敲了一下。

「正如各位所见，尽头山脉的这一侧只有往四方扩散的十基洛尔草原与岩石地。要是被推进到这里，再来就只能被五万敌军包围并且歼灭。因此必须在这条连接东大门的，宽一百梅尔长一千梅尔的峡谷里战到最后。我们将在此处布下纵深阵，单纯等待敌军的突击并削弱对方实力。这就是作战的基本方针。到这里有什么问题吗？」

立刻举起手的人是艾尔多利耶。晃著淡紫色头发站起来的年轻人，以压抑住平常那种绅士模样的声音问道：

「如果敌军是只由哥布林与半兽人组成的步兵，那么不管来五万还是十万都不成问题。但那些家伙也知道这一点。所以敌军里面也有装备了强大弓箭的食人鬼军团，以及更加危险的暗黑术师团。要怎么应付这些应该会从步兵背后发动的远距离攻击呢？」

「应对方式将会是危险的赌注……」

法那提欧暂停了一下，视线稍微瞄了爱丽丝一眼。爱丽丝不由得挺起背杆，听她继续说明下去。

「……即使是白天，阳光也照不到峡谷底部，所以地面是寸草不生。也就表示，空间神圣力相当稀薄。只要我们在开战前把神圣力全部用尽，敌军就没办法以强力的术式发动攻击。」

法那提欧大胆的意见，让众骑上与部队长产生一阵骚动。

「当然，我方也将无法使用术式。但我们原本就只有一百名左右的神圣术师。要是以术式互击的话，神圣力的消费量应该是对方远超过我们才对。」

法那提欧说的确实没错。但是──她的作战有两个问题点。

这时取代说不出话来的艾尔多利耶要求允许发言的，正是弓箭手迪索尔巴德。穿著红铜色铠甲的资深骑士，以沉稳的声音发问：

「原来如此，副长阁下说的应该没错。但神圣术不只能用来攻击。要是神圣力枯竭的话，不就连伤者的天命都无法回复了吗？」

「所以我才说是一场赌注。我们已经把积蓄在中央圣堂宝物库里所有的高级触媒与治疗药全搬到这座野营地来了。限定术式只使用治愈术，再加上药品辅助的话，光靠触媒就可以撑两天……不对，是三天。」

听见她这么说，随即响起超越刚才那一次的惊讶声。说到中央圣堂的宝库，大家都知道警卫森严的程度甚至还成为童话故事的题材。通常宝物只有被搬进去的份，这次应该是有史以来第一次被搬到外面来吧。

这时就连这名豪杰骑士，威严的脸上也浮现惊讶的脸色沉默了下来。等迪索尔巴德一边发出低沉的沉吟声并坐下后，爱丽丝就站了起来。

「还有另一个问题，法那提欧阁下。」

她决定暂且将刚才的争论放到一边，先提出第二个问题点：

「就算索鲁斯与提拉利亚的恩惠再怎么稀薄，峡谷也不是完全黑暗，而且也没有与大地隔绝。我想那个山谷里应该有长年累月积蓄下来的庞大神圣力。到底什么人可以在开战前这么短的时间内把这股力量使用殆尽呢？」

这次换成法那提欧无法立刻回答了。

贯穿山脉的山谷确实比野营地后方的那片草原还要狭窄，但是宽度也有一百梅尔，长度甚至有一千梅尔。要让充满如此广大空间的神圣力瞬间枯竭，必须要几百名术者同时使用高等神圣术，但法那提欧刚才已经说过，守备军里没有这么多术者了。

或者由少数人使用足以产生天地变异的超大规模术式也可以耗尽神圣力，但拥有这种力量的，除了已经死亡的最高司祭亚多米尼史特蕾达与贤者卡迪娜尔之外，应该就没有别人了。

但是副骑士长却一边用金褐色眼睛凝视著爱丽丝一边用力摇了摇头。

「你错了，的确是有。唯一有一个人能够办到这补事。」

「…………唯一一个人……？」

爱丽丝一边呢喃，一边环视守备军成员。

但法那提欧接下来所说的，竟是完全出乎意料之外的名字。

「就是你，爱丽丝‧辛赛西斯‧萨提。」

「咦……？」

「你自己可能没有发现，但你现在的力量已经超越整合骑士的范畴。现在的你，应该可以行使……足以开天辟地的真正神力。」

7

「上级整合骑士有那么强大的力量吗？」

坐在类似恐龙般的双头怪物所拖行的大型战车上──说是战车，其实只不过是没有炮台也没有履带的箱型四轮车──身体跟著晃动的加百列‧米勒如此问道。

即使是铺著高级坐垫的长椅依然无法消除震动，但是跟士兵时期经常搭乘的布莱德雷步兵战斗车那种几乎要把人杀掉的乘坐感比起来已经好太多了。大概就只是会让放在边桌上的红酒杯发出啪嚓啪嚓拍打声的程度。

从黑曜岩城出发到现在已经过了三天，虽然是现实世界里未曾经历过的长时间移动，但几乎感觉不到疲劳。虽说这可能跟战车的坐垫相当舒服无关，只是因为这里是假想世界罢了。加百列脚边，慵懒躺在厚厚地毯上的妙龄美女，一边抚摸缠著绷带的右脚一边点了点头。

「他们的实力无庸置疑。这个嘛……在长达三百年的战史里，我们暗之术师与骑士从来没有杀死过整合骑士──这么说您能够理解吗？当然，反过来的情况可以说多如天上繁星。」

「唔……」

代替闭上嘴的加百列，在宽广车厢墙边盘腿坐著，抱著一瓶蒸馏酒的瓦沙克发出疑惑的声音。

「但是蒂伊大姊啊。那群叫作整合骑士的家伙真这么强的话，为什么没有攻过来呢？」

暗黑术师总长蒂伊‧艾‧耶尔对瓦沙克露出更加艳丽的笑容，然后竖起食指说：

「问得好，瓦沙克大人。那些家伙确实是能够以一挡千的猛将，但怎么说也只有一个人而已。只要在广大空间被上万名军队包围，就有可能因为不断受到一些小伤害而耗尽天命对吧？所以那群家伙才会这么卑鄙，绝对不会越过没有被包围危险的尽头山脉。」

「哦……原来如此。就是防御力再怎么强的Mob，只要用简单的DoT伤害一点一点削除生命值，总有一天能够打倒它的意思……」

「什么……？Mob……?」

人工摇光的蒂伊当然不会懂瓦沙克的比喻，这时加百列狠狠瞪了他一眼，才轻咳了一声继续说道：

「总而言之，只要把那些整合骑士拖到够宽敞的战场，就能够加以包围并歼灭对吧？」

「理论上是这样。虽然哥布林和半兽人一定会出现超过万名以上的牺牲者就是了……」

蒂伊发出「呜呵呵」的笑声，从放在地板上的银杯里拿起一个颜色刺眼的果实，接著同样鲜红的嘴唇以舔食般的动作将其含进嘴里。

其实根本不用她说，步兵个体的损耗对加百列来说原本就无关痛痒。只要能够击破敌军，就算包含眼前蒂伊在内的黑暗领域大军全部牺牲，他也不会有任何怨言。这场战争在某种意义上，和Glowgen Defense Systems的战术研究所里日常举行的战术模拟练习没有什么两样。

越过成千上万的尸体，以新支配者的身份君临人界，对全土发出最初也是最后的命令。命令他们找出名为爱丽丝的少女并把她带过来。然后在这个奇妙世界里的任务就结束了。

一想到这里，就觉得这口味有点独特的红酒让人感到有点怀念。

加百特举起玻璃杯，一口气喝光浓紫色液体。

这个时候，「爱丽丝」浮现在灵魂猎人加百列‧米勒脑海里的模样，在无意识中就和名字极为类似的首位牺牲者爱丽西亚‧克林格曼那无垢、稚嫩且纤细的容貌重叠在一起。他认为爱丽丝一定是生活在类似故乡太平洋帕利塞德的城市里，而且是一名温柔美丽──又柔弱无力的少女。

因此加百列才没注意到某个可能性。

他完全没有想到，追求的「爱丽丝」会以整合骑士的身份率领著敌军。

皇帝旗不停飘动的指挥车排在最后方的长长队伍，就这样缓慢但确实地朝向西方边境持续行军。染著血色的远方天空中，宛如锯齿般尖锐的群山已经逐渐现出身影了。

移动开始的第四天，也就是十一之月七日。

黑暗领域军的本队来到一处山麓，从这个地方能够看见即将崩坏的大门。宽广的台地周边，已经排满了先遣部队准备好的黑色帐篷。

咚咚隆。

咚咚隆。

撼动地面的重低音是来自于巨人族击打的战鼓。

在最后方指挥车的屋顶上，加百列无言地注视著原本排成一列的本队，像被巨大心脏推动的无数血球一般整个散开的模样。

打先锋的第一连队，是由哥布林的轻装步兵大队与半兽人重装步兵大队共一万五千名所组成。他们配合贯穿尽头山脉峡谷的宽度排成了纵队。队列的各处都配置了宛如攻城塔一样高大的巨人，数量虽然不多只有仅仅五百名，但应该能发挥出主力战车般的功效，援护战场上的步兵队伍吧。

亚人族后方的第二连队，是由共有五千人的拳斗士团与同样为五千人的暗黑骑士团所组成。刚继承暗黑将军的年轻骑士可能是希望洗刷前代的污名自愿打头阵，但加百列否决了他的要求。这是因为预测到骑士个体的整体士气一定相当低落，所以要排除这种不稳定的要素。

第三连队由食人鬼的弓兵七千，以及全是女性的暗黑术师团三千所组成。从步兵后方冲进峡谷，藉由远距离攻击歼灭敌军就是他们的任务。据术师总长蒂伊所表示，就算距离遥远，只要能目视构成敌人主力的整合骑士，就可以集中火力于一点来打倒他们。

老实说，加百列也不是没有直接跟这些号称无敌的骑士战斗，然后尝尝看这些灵魂的欲望。但要是因为意想不到的事故而失去这个高等帐号，那就偷鸡不著蚀把米了。之后不论要生产多少Underworld人，也就是人工摇光都没问题。目前还是要以捕获「爱丽丝」并且脱离O turtle为优先目标。

登入到现在，内部时问已经过了八天，现实世界里是将近十五分钟左右。今后要完全支配人界，把搜寻爱丽丝的命令传达到全世界应该要花上十天左右吧。考虑到这一点，就会希望尽快结束这场战争──最长也只能花整整一天就要把事情解决。

「唉～结果没有我出场的机会吗？」

身边抱著已经不知道是今天第几瓶威士忌的瓦沙克这么抱怨著。瞄了他一眼后，加百列就用稍微辛辣的口气指责他说：

「我都看到了。那个叫作夏斯达的将军变成龙卷风时，你这家伙丢下我率先逃跑了对吧。」

「嘿嘿，不愧是队长，什么都逃不过你的眼睛。」

瓦沙克一点都没有愧疚的模样，直接咧嘴笑了起来。

「哎呀，我从以前就专门负责PvP。不擅长对付那种没有实体的怪物啦。」

听见部下说出这种不知道是认真还是开玩笑的藉口，加百列看了他一阵子后才简短地询问：

「瓦沙克，你为什么自愿参加这次的作战？」

「你说的作战是潜行到Underworld吗？那当然是因为好像很有趣啦……」

「不是，我问的是在这之前。也就是袭击O turtle的作战。你虽然是GlowgenDS的工作人员，但怎么说也是专门负责网路作战的吧。什么动机让你参加这种可能会吃真实子弹的任务？从你的岁数来看，也不可能是像汉斯与布里克那种从中东回来的佣兵吧。」

加百列难得会说出这么长一段话，但他当然不是对瓦沙克‧卡萨鲁斯有什么太大的兴趣。只是忽然想到这个年轻人轻薄的态度底下究竟隐藏了些什么。

瓦沙克轻轻耸了耸肩，回答了一句「都一样啊」。

「这个问题的答案，也一样是好像很有趣。」

「哦……」

「真要说的话，像你这种大学毕业的菁英分子跑到战场来才更夸张呢。就算是有从军的经验也一样。」

「我这个人是现场主义者。」

加百列一边回答，一边在内心呢喃著。

瓦沙克，对你来说什么叫作有趣？是用枪射击？还是……能够杀人呢？

当他想著要继续深究下去还是就此中断对话时，挂在指挥车后方的梯子就传来喀喀的高跟鞋声音，接著暗黑术师公会总长蒂伊‧艾‧耶尔就出现了。

她恭敬地行了个礼，舔了一下嘴唇后就开始报告：

「陛下，全军的配置已经完成了。」

「嗯。」

加百列放下翘著的脚，从暂时的皇座上站起来，朝著下方环视了一圈。

除了在前方展开阵形的三万五千名主力部队外，还有主要由哥布林与半兽人构成的预备军一万，以及商工公会的锱重部队五千在指挥车左右两侧待机。

这支总数达五万的军队，就是加百列拥有的全部兵力。所以如果丧失所有个体还无法攻破敌军的防守，那就得从头修正计划了。届时捕获爱丽丝的可能性也将变得极其微小。

但根据侦查的龙骑士所表示，敌军最多也只有三千人左右。也就是说只要能按照计划排除整合骑士，就不可能会败北。

「好，距离大门崩坏还有多久的时间？」

蒂伊保持低著头的姿势回答加百列的问题：

「大概还有八个小时左右。」

「那么，在崩坏的一个小时前让第一师团进入峡谷。在最靠近大门的地方分散部队，等大门一崩坏就一起展开突击。战线往前推进之后，就投入第二、第三师团，一口气歼灭所有敌人。」

「遵命。相信不用等到明天，陛下就能看见敌将的首级了。虽然很可能已经烧得焦黑就是了。」

蒂伊发出「呵呵呵」的微笑后，迅速对在背后待机的传令术师下达指令，接著再次深深行了个礼并走下楼梯。

加百列从指挥车的车顶眺望著屹立在远方的巨大石门。

虽然距离两英哩以上，但是却有种快要压在自己头上的重量感。那道门整个崩坏的时候，一定是相当壮观的景象吧。

但是真正的飨宴要从那时候才开始。爆散并且消失的数千个灵魂，一定会放出笔墨难以形容的美丽光芒。躲在O turtle上轴的那群RATH技术人员，应该会对无法在内部观赏自己策划的最壮观场景而感到遗憾吧。

咚咚隆。咚咚隆。

咚、咚。咚、咚。

节奏加快的战鼓，似乎更加强化了由数万军人所散发出来的饥渴与斗志。

8

「那……桐人就拜托你们了。」

爱丽丝依序凝视著两名年轻少女的脸这么表示。

初等练士，不对，应该说已经是一名正式剑士的缇洁‧休特里涅与罗妮耶‧阿拉贝鲁挺起背杆点了点头。

「好的，请交给我们吧，爱丽丝大人。」

「我们一定会好好保护桐人学长。」

刚回答完，缇洁就以左手，而罗妮耶则以右手用力握住新制轮椅的把手。

闪烁著银灰色光辉的细长轮椅，是爱丽丝以术式将物资帐篷里多出来的全身铠甲改变形状所制成。它比在卢利特使用的木制轮椅还要轻，而且也有足够的强度。

但是坐在上面的桐人紧紧抱住的两把剑所带来重量就实在没有办法处理了。心里虽然有点担心两名少女不知道能不能推动轮椅，但两个人配合得天衣无缝，笔直地把轮椅推到爱丽丝面前。

这样的话，就算接到立刻撤退的命令也不会落人后了。只不过，被逼得必须从峡谷撤退时，守备军就等于是陷入遭到包围歼灭的命运。

老实说，只要发现战况略呈败势，就希望她们能带著桐人逃向西方。但那也不过是把命运延后几个月──不对，应该说延后几周而已。

事先已经订好计划，只要守备军败北，保护尽头山脉的四名骑士也将跟著撤退，然后一边让各地的城镇与村子里的居民避难，一边将央都圣托利亚的城壁做为最后的防御线。但这只是无谓的抵抗。那个美丽的都市以及石灰岩制成的中央圣堂，不久后就会遭到侵略军蹂躏并烧毁。在尽头山脉这个封闭的墙壁内侧，众人将无处可逃……

爱丽丝跪了下来，从同样的高度下凝视著桐人的眼睛。

来到野营地的五天当中，只要有时间就会对桐人说话，甚至握住他的手与紧紧抱住他。但是到今天为止，都没办法让他产生太大的反应。

「桐人……这可能是我们最后一次见面了。」

勉强保持著微笑的爱丽丝，对著黑发年轻人这么呢喃。

「叔叔说你可能是决定这场战争胜败的关键人物。我也是这么认为。因为这支守备军就等于是你创造出来的啊。」

实际上，如果没有桐人和尤吉欧，目前在东大门布阵的就是最高司祭亚多米尼史特蕾达与整合骑士团，以及由那种恐怖的巨剑魔像所组成的军团了。

如果有两三千个拥有强大战斗力的巨剑魔像，五万的黑暗领域军队根本就算不了什么。但那也等同于人界的灭亡。因为巨人的素材就是好几万名人界的居民。桐人他们牺牲了一条生命与一颗心，才防止了这样的悲剧。

但是，贝尔库利率领的人界守备军就这样败北的话，人界依然会陷入不同形式的巨大悲剧当中。

「……我也会努力。会把你给予我的天命完全燃烧殆尽。所以……如果我被击倒，以最后的力量呼唤你时，请一定要站起来拔出你的剑。只要你能醒过来，有几千、几万名敌人都不是问题。你一定会再次产生奇迹，守护人界……还有大家。因为你是……」

──打倒那个最高司祭的最强剑士啊。

在内心深处这么呢喃后，爱丽丝就伸出双手，用力抱紧桐人瘦削的身躯。

松开分不清是一瞬还是数分钟的拥抱后，站起身的爱丽丝，注意到蓝色眼睛里晃动著复杂光芒的罗妮耶一直凝视这边的视线。一开始不知道是怎么回事的她眨了眨眼睛，但是马上就了解是怎么一回事。

「罗妮耶小姐。你……喜欢桐人吧。」

一边微笑一边这么说之后，娇小的少女就用双手遮住嘴巴，脸颊到耳朵附近也整个红透了。她随即伏下视线，以几乎快听不见的声音回答：

「没……没有，我……怎么配呢……我只不过是一名随侍初等练士而已……」

「哪有什么配不配的。罗妮耶小姐也是爵士家的继承人吧？我是出生在边境的小村子里，而桐人则是连出生地都不清楚……」

罗妮耶忽然用力摇头来打断爱丽丝所说的话。

「不是的！我……我……」

缇洁伸出右手来，温柔地支撑住双眼积蓄著大大泪珠且声音断断续续的罗妮耶。这时她红叶色的眼睛里也满是泪光，接著以颤抖的声音开始说道：

「爱丽丝大人……您知道桐人学长与尤吉欧学长犯下什么样的禁忌吗？」

「嗯……嗯。听说是因为在学院内发生争执……最后杀伤了其他学生。」

半年前，当时什么都不知道的爱丽丝依然是公理教会的尖兵。即使到了现在，她还是清楚记得自己接到元老院的逮捕令时那种震惊的感觉。因为就连在教会的史书里，都没看过央都的学院发生学生杀害学生这种重大的禁忌违反。

爱丽丝点头后，缇洁又继续追问：

「那么……您知道学长们为什么会犯下那样的禁忌吗……？」

「不……这我就不清楚了……」

当她摇头时，耳朵深处忽然重新响起一道叫声。

和桐人一起被拋到中央圣堂的外壁之后，他对著表示不需要罪人帮助的爱丽丝大叫了一段话……

「──就算禁忌目录没有禁止这么做……但你真的认为上级贵族就能够随心所欲地玩弄罗妮耶和缇洁那样的无辜少女吗！」

没错，我就是在那个时候听到这两个人的名字。

上级贵族，指的应该是桐人斩杀的学生吧。而被玩弄则是──

在瞪大双眼的爱丽丝面前，缇洁以发抖的声音开始说道：

「……莱欧斯‧安提诺斯上级修剑士与温贝尔‧吉杰克上级修剑士，不停对我们的朋友芙蕾妮卡‧歇丝基初等练士做出屈辱的命令。我们虽然对两位修剑士提出抗议，但那个时候却因为过于气愤而使用了足以被判定为失礼行为的言词。因此他们就发动了基于帝国基本法的贵族赏罚权……」

接下来的事情，光是回想也很痛苦吧。缇洁再也说不出话，而罗妮耶则是低著头发出呜咽声。

想要她们别再说下去的爱丽丝正准备开口时，红发少女又勇敢地继续开始说道：

「……当我们即将被施加难以忍受的惩罚时，桐人学长和尤吉欧学长就为了解救我们而挥了剑。如果我们聪明一点，就不会发生那种事了。学长他们就不会为了纠正法律而和教会战斗，也不会因此丧命了。我们……犯再也无法弥补的罪过。所以……就算脸皮再厚，我也不敢说自己喜欢学长……」

把心事全部吐露出来的缇洁，这时终于也流下眼泪。两名年轻的少女抱在一起，低声发出对这个年纪来说太过沉重的悔恨呜咽。

爱丽丝一面咬紧牙根，一面抬头看向采光用的小窗。

她自认为已经清楚占据著四帝国的上级贵族究竟有腐败了。他们饱食终日、累积私财且荒淫无道。

但是过去的整合骑士爱丽丝，认为详细知道这些罪过会让自己也遭到污染，所以故意不去注意这些贵族的所作所为。不论他们做什么，只要没有触犯禁忌就没关系──因为自己是被从神界召唤到这里的法律守护者。她一直都是这么深信不移。

但这种沉默的不作为才是罪过。虽然没有违背桐人憎恨的禁忌目录，但就是这样才罪孽深重。跟什么都没做的自己比起来，眼前的两名少女要勇敢多了。

爱丽丝深深吸了口气，以灌注力量的声咅说：

「不，你们错了。你们才没有什么罪。」

忽然迅速抬起头的人是罗妮耶。虽然这名少女给人总是躲在缇洁背后的印象，但现在眼睛里却带著强烈的光芒并大叫：

「爱丽丝大人……身为光荣整合骑士的爱丽丝大人不会了解！我们的身体被那两个男人玩弄，尊严也被罪过污染了！」

「身体只不过是心灵的容器。」

爱丽丝一边回答，一边以握住的右拳用力敲打胸口中央。

「只有心……灵魂才是唯一确实的存在。只有自己才能决定灵魂的模样。」

爱丽丝闭上眼睛，把意识集中在自己的内面。

大约两周前，卢利特村遭受袭击，爱丽丝以心灵的力量──也就是心念力取回了失去的右眼。她当时就已经亲身体验到，只要坚定并专注地想著，就能够不依靠术式让肉体产生变化。

但现在光是这样还不够。不光是肉体，必须用心念的力量让身上的服装也产生变化才行。

应该办得到才对。过去桐人不是展现给自己看过了吗？拿著两把剑和最高司祭亚多米尼史特蕾达对峙的他，身上那套和之前服装完全不同的异国风黑色皮革长外套就在眼前不停飘动。

一定要恢复。恢复成在陌生的全白巨塔里醒过来，为了消除丧失记忆的不安与寂寞，只能用厚厚冰层封闭自身心灵之前的爱丽丝。

──我也和你们一样喔，罗妮耶、缇洁。以人类的身份来到这个世界上，犯下许多过错，背负巨大的罪过，然后现在来到这里。如果说桐人和尤吉欧杀人是你们的罪过……那么在那之前，如果年幼的我没有忘记禁忌而碰到黑暗领域的土壤，桐人他们根本就不用以来到央都为目标了。

没错，那就是我的罪过。就算没有记忆，爱丽丝‧滋贝鲁库也不是不认识的其他人，确确实实是过去的我。在卢利特村的日子告诉了我这一点。

即使闭上眼睛，也清楚知道有温暖的白光正包围自己的身体。

爱丽丝缓缓睁开眼睛。

由于她低著头，所以一开始看见的是自己穿著的裙子。但那不是代表公理教会的纯白色，而是像秋天的天空般清澈的蓝色。

裙子上还有一件原色围裙。黄金铠甲与护手已经消失。把手往头上伸去，指尖就碰到大大的缎带。而且头发似乎也变短了一点。

一抬起头，眼睛就和露出茫然表情的罗妮耶与缇洁相对。

「……看吧？身体和外表，只不过是心灵的附属物罢了。」

当然这只是暂时性的变身。当集中的精神中断的瞬间，就会恢复成原本骑士的模样吧。但这样应该能把爱丽丝、桐人以及尤吉欧的心意传达给这两名少女知道。

「没有任何人能够弄脏自己的心灵。在边境出生的我，原本应该是以这种模样长大才对。但是十一岁的时候，以罪人的身份被带到央都，然后遭到术式删除记忆并成为整合骑士。我也曾经诅咒过这样的命运……」

爱丽丝所说的，是除了自己之外就只有整合骑士长贝尔库利知道的重大秘密。但是她相信这两个人应该能接受，所以又继续表示：

「但是……桐人教会了我，即使是这样我依然有办得到而且应该去做的事。所以我已经不再迷惑。我决定接受自己并往前迈进。」

爱丽丝举起双手，同时紧握住罗妮耶与缇洁的手。

「你们一定也有只属于自己的，宽广、漫长且笔直的道路。」

互握住的手上，滴落下几滴的泪水。

顺著少女脸颊滑下的泪，带著与刚才完全不同的彩色，发出了极为美丽的光芒。

插图018

最后再次抱紧坐在轮椅上的桐人，把他交给罗妮耶与缇洁后，爱丽丝就走出帐篷。

结果艾尔多利耶就像早在外面等待一般跑了过来，说出了夸张的赞辞：

「哦哦，真是太完美了……看起来简直就像是凝缩了索鲁斯的光辉一样……这才是吾师爱丽丝大人啊……」

「反正战斗个一个小时就会沾满尘土了。」

爱丽丝冷冷地如此回应，低头瞄了一眼自己的身体。

刚才的变身现象已经消失，黄金护胸与纯白裙子反射阳光后发出炫目的光芒。如果能活著回来，就在哪个地方加上蓝色布料吧，心里这么想的爱丽丝抬头看向西方的天空。

索鲁斯早已开始西下。大约再过三个小时左右，就会消失在地平线上。在那同时，东大门的天命也将消灭。三百年的封印终于要解除了。

能做的事都已经做了。

这五天里，爱丽丝也参加了守备军的训练，发现士兵们的战技已经被磨练到很难相信只经过半年的训练。更惊人的是，所有士兵都学会了不存在于传统流派的连续剑技。

一问之下，原来是副骑士长无私地教授众人她耗费漫长岁月所钻研出来的剑技。虽然最多只到三连击，但对上只按照本能挥动蛮刀的哥布林与半兽人应该是相当可靠的武器。

当然，拥有独特连续技的暗黑骑士对士兵们来说负担还是太重了。包含似乎拥有更高速连击的拳斗士在内，都只能够由整合骑士来对抗他们。

最重要的是，不能被一开战应该就会涌过来的亚人族大部队压制，以及必须在受到最小的损害下撑过食人鬼的大弓与暗黑术师的远距离攻击。

作战是能否成功的重任，现在就加诸在爱丽丝一个人肩上──

把视线从天空移下来后，就看见后方补给部队为了准备最后的餐点而升起的好几道炊烟。罗妮耶与缇洁应该已经快带著桐人到那边和他们会合了。

无论如何都要保护他们。

「爱丽丝大人，差不多了……」

听见艾尔多利耶的声音后点了点头，接著爱丽丝为了转头而一只脚往后退。

但这时又停下脚步，把视线移到唯一的弟子身上。

「……怎……怎么了吗？」

凝视著青年骑士像是感到困惑而眨眼的脸，爱丽丝原本绷紧的嘴唇稍微放松了一些。

「……艾尔多利耶，一直以来你真的是尽心尽力在帮助我。」

「怎……怎么忽然说这种话！」

爱丽丝把自己的右手轻轻放在哑然站在现场的骑士左手上，又继续说道：

「你待在我的身边，对我来说是很大的安慰。你是因为担心我……才不选择迪索尔巴德阁下那样资深的男骑士，而选择让没有太多实绩的我指导对吧？」

「没……没这回事，我怎么可能有那么傲慢的举动！我只是打从心底佩服爱丽丝大人的剑技……」

艾尔多利耶拚命摇头否认，爱丽丝则一瞬间握紧他的手又放开，然后再次露出微笑。

「就是有你的支持，我才能在这条险峻的道路上一直走到今天。谢谢你，艾尔多利耶。」

说不出话来的年轻骑士，眼睛里忽然冒出斗大的泪水。

「…………爱丽丝大人……为什么要说……到今天呢。」

他以沙哑的声音这么问道。

「为什么爱丽丝大人要用这种自己的道路好像要在这里结束般的说法呢。您……您还没有把所有的本事教给我啊。不论是剑技还是术式，我的实力都还跟您有天大的差异。接下来您还得一直、一直锻炼、指导我才行啊……！」

在他伸出不停发抖的右手快碰到自己之前──

爱丽丝忽然变成以严厉的声音大喊：

「整合骑士艾尔多利耶‧辛赛西斯‧萨提汪！」

「是……是的！」

骑士的手倏然停止，摆出直立不动的姿势。

「做为你的师父，接下来就是我最后的命令。你要好好活下去。活著见证和平到来，并且夺回你真正的人生与心爱的人。」

除了爱丽丝之外的所有整合骑士，「记忆的碎片」以及被变成剑的「心爱的人」都还是被封印在中央圣堂最上层里。一定有方法让它们恢复成应有的形状，回到应该存在的地方。

对保持立正姿势并无声落泪的艾尔多利耶点了点头，爱丽丝迅速转过身子。金黄色头发与纯白裙子直接撕裂秋天的冷空气。

正前方可以看见沉浸在微暗当中的大峡谷与东大门。

接下来爱丽丝将咏唱过去未曾经验过的超大规模神圣术。这全是为了将充满山谷里的神圣力一滴不剩地浓缩起来，藉此给予敌军痛击。

如果说错一句术式──不对，应该说意识稍微有点不集中的话，浓缩的神圣力就会爆炸，让爱丽丝整个人完全消失在这个世界当中。

但她完全不觉得害怕。这五天里，已经以整合骑上的身份和贝尔库利与法那提欧、艾尔多利耶等人度过了相当充实的时问，而且也以爱丽丝的身份在卢利特村和妹妹赛鲁卡生活了半年。

更重要的是，遇见了桐人与尤吉欧，藉由跟他们交手而有了心灵上的交流，更因此了解了人类的感情──也就是悲伤、愤怒以及爱情。

自己还有什么好奢求的呢？

爱丽丝高声震响著铠甲，一步一步笔直地走进等待开战瞬间来临的守备军中央。　　「RATH」是为了Bottom-up型人工智慧开发计划「Project Alicization」而伪造出来的企业，而自走式巨大人工母船「O Turtle」就是其根据地。

巨大金字塔型的该处，存在为了登入「Underworld」的「Soul translator」，在第一STL室里有两台，第二STL室里也有两台，总计有四台。桐人登入「Underworld」的「Soul translator」设置在第二STL室当中。

「O Turtle」的中心有保存「Underworld」众多居民的灵魂，也就是人工摇光的「LightCube Cluster」存在。

加百列等人的任务就是从庞大的LightCube群当中，找出爱丽丝的人工摇光并让它从空气管弹射出来。

第十七章 黑暗领域 人界历三八〇年十一月

1

暗黑骑士莉琵雅‧扎恩克尔在飞龙停止动作前就从它背上跳了下来，开始在联结起降台与帝宫之间的空中回廊上全力冲刺。

马上感觉呼吸困难的她，用右手脱下覆盖整个脸部的头盔。

莉琵雅又用左手将啪沙一声散开来的灰蓝色长发全部理回背后，然后继续加快速度。虽然想脱掉沉重的铠甲与披风，但还是不想让在帝宫里肆虐的执政官们看见自己任何一点肌肤。

急奔过弯曲的回廊，从竖立在右手边的圆柱缝隙中，露出了撕裂红色天空后耸立在该处的黑色巨城。

帝宫黑曜岩城是花了一百年的时间，挖开广大无边的暗之国里最高的──当然，不包含不祥的「尽头山脉」在内──岩山后建筑而成的城堡。

据说从最上层的「皇座之间」，可以看见微微浮现在西方地平线的尽头山脉，以及贯穿山脉岩壁的巨门。

但是没有人知道这个传说的真实性。

自从初代皇帝暗黑神贝库达在久远前的太古时代回归地底的黑暗之后，暗之国的皇座就一直没有主人。最上层的大门被拥有无限天命的锁炼封印，永远没办法打开。

莉琵雅硬是把视线从漆黑城堡的最上层移开后，对著近在眼前的守门食人鬼族卫兵大叫：

「我是暗黑骑士第十一位，扎恩克尔。快点开门！」

狼头人身的卫兵们虽然壮实，但脑袋有点驽钝，在莉琵雅快到铸铁大门前才终于开始旋转开关装置的把手。

门随著「轰、轰」的沉重声打开一条细缝时，莉琵雅就侧身穿了过去。

隔了三个月才回来的城堡，还是用跟以前一样的刺骨冷空气来迎接她。

打杂的狗头人每天都鲁直地把走廊擦过一遍，所以上面看不见任何灰尘。让鞋底在黑曜石地板上踩出喀喀声跑了一阵子后，就看到前方衣不蔽体的两名妖艳女性像在滑行般无声地往她靠近。

光润的波浪状头发上那顶大大的尖帽子，显示出她们是暗黑术师。看都不看她们准备擦身而过时，其中一名女性故意以尖锐的声音说：

「哎呀～地震了吗！不会是半兽人之类的怪物跑过来了吧！」

另一名女性立刻发出高亢的笑声回答：

「不是吧，照这种摇晃的程度来看，应该是巨人才对！」

──如果不是在禁止拔剑的城内，一定要把她们的舌头切下来。

莉琵雅心里虽然这么想，但只是用鼻子冷哼了一声就一口气跑了过去。

出生在暗之国的人族女性，训练学校毕业之后大部分都是加入暗黑术师公会。那是一个极重享乐的组织，上层下达的指示是「忘掉规律，学习放浪」，结果就是出现刚才那样，尽是一些只对打扮自己有兴趣的家伙。

自己明明是那副德性，却对选择了骑士道的女性有很强烈的对抗心。莉琵雅在幼年学校时，也曾经被同期交恶的女术师下了毒虫诅咒而不知道该怎么办。不过用剑把她自豪的辫子砍掉后，对方就变得乖多了。

反正这个国家里的人民，尽是一些没有前瞻性的笨蛋。

组织以及个人都经常发生争执，只会靠力量来决定优劣的暗之国根本没有未来可言。目前虽然藉由「十侯会议」保持了随时可能崩坏的平衡，但这样的状态不可能持续太久。和人界──半兽人与哥布林称为「伊武姆之国」之间的战争已经近在眼前，十侯当中有任何人在这场战争中丧命的话，均衡立刻会崩毁，腥风血雨的乱世将再度来临。

对莉琵雅诉说这种未来的，是十侯的其中一人，也就是她的直属长官暗黑骑士团团长，同时也是她心爱的男人。

而莉琵雅现在，心中带著他期盼已久的机密情报。

这个时候，已经没有空去理那些女术师所说的蠢话了。

一直线横越过无人的大厅后，她每一步都直接踩过两阶的大楼梯不停往上爬。经过锻炼的身体开始上气不接下气时，终于抵达目标的楼层。

藉由合议来治理暗之国全土的「十侯会议」里，人族占了五席，哥布林族两席，剩下的三席分别属于半兽人族、食人鬼族以及巨人族的首领。经过长达百年的内乱后终于缔结了算是条约的东西，交换了五族之间不分上下的约定。

因此靠近黑曜岩城最上层的十八楼里，设置了分属于十名诸侯的私人房间。稍微压底脚步声来跑过走廊的莉琵雅，用右手背在最深处一间房间的门上敲了三下。

「进来。」

立刻有低沉的声音做出回应。

看了一下走廊的左右两侧，确定四下无人后，莉琵雅迅速钻进门后面。

她一边对于将装饰物减到最少的房间里飘散的那股男人味感到怀念，一边单膝跪地并低下头来。

「骑士莉琵雅‧扎恩克尔，现在回到城堡里来了。」

「辛苦了。先坐下吧。」

莉琵雅在意识到因为浑厚的声音感到兴奋的情况下抬起视线。

那名稳稳坐在圆桌后方其中一张躺椅上，并高高翘著脚的男人，正是暗黑骑士长──别名「暗黑将军」的毕库斯鲁‧乌鲁‧夏斯达。

他有著以人族来说相当魁梧的躯体。宽度虽然不及，但光看身高的话绝对不输给食人鬼族。漆黑的头发剪得相当短，嘴角的胡须也修剪得十分整齐。

简素的麻质衬衫因为像是快要把钮扣弹飞般的强壮肌肉而高高隆起，但腰部周围却看不到一丝赘肉。很少有人知道，看起来完全不像超过四十岁的完美肉体，是藉由即使爬上骑士最高位也绝不松懈的严苛日常锻炼来维持。

隔了三个月才看见朝思暮想的人，让莉琵雅只能压抑立刻想扑进他怀里的冲动，并坐到夏斯达对面的沙发上。

撑起上半身的夏斯达，把放在桌上的两只水晶杯其中一只交给莉琵雅，接著打开看起相当有年份的红酒。

「因为想和你一起喝，所以昨天就从宝物库里把它偷出来了。」

夏斯达闭起一只眼睛，把带有浓香的深红色液体倒进玻璃杯。跟以前一样，他一做出这种表情，看起来就像是喜欢恶作剧的小孩子。

「谢……谢谢您，阁下。」

「说过好几次了，只有我们两个人的时候别这样称呼我。」

「但目前也算是在勤务当中。」

和像要表示「真拿你没办法」而耸了耸肩的夏斯达轻声互碰一下杯子后，就一口气喝下芳醇的红酒，让她顿时感觉因为长途旅行而消耗的天命正慢慢恢复。

「……那么……」

也喝光自己杯子里的酒后，恢复严肃表情的骑士长稍微压低声音问道：

「你派遣使魔通知我说有重要消息，内容究竟为何？」

「是的……」

莉琵雅的视线往左右一扫，接著探出身子。夏斯达虽然是个豪放磊落的男子汉，但他同时也相当细心。这间房间里设下了好几重防御术，就算是暗黑术师公会总长的那个「魔女」也没办法窃听才对。但就算知道这个事实，只要一想到自己得知的重大情报，就不由得压低声音。在夏斯达黑色眼睛凝视下，莉琵雅开始了简洁的报告：

「人界的公理教会最高司祭……丧命了。」

下一个瞬间，就连暗黑将军也忍不住瞪大了眼睛。

「呼──」一声浑厚的叹息打破了沉默。

「询问这个消息的真伪……只是侮辱了你。虽然不怀疑情报的真实性……但是……那个不死者真的……」

「是的……我了解您的心情。我也无法马上相信，整整花了一周的时间确认消息的真伪，但果然没有错。我让『耳虫』潜伏到中央圣堂，取得了实证。」

「你竟然做出这么危险的事。要是被顺著术式追踪，你根本就没办法离开央都，直接会被五马分尸了。」

「是的。但连我这种程度的术式都无法探知，更加证明了情报的真实性。」

「……唔……」

稍微呷了一口第二杯红酒，夏斯达低下刚毅的脸庞。

「那是什么时候的事情。还有，死因是？」

「大约是半年前……」

「半年。那个时候山脉的警戒的确暂时变得比较松懈。」

「是的。至于最高司祭的死因……这虽然有点难以置信，但据说是被剑所杀……」

「被剑杀死了──你是说有人用剑杀了那个不死者？」

「怎么可能。」

莉琵雅对顿时说不出话来的夏斯达用力摇了摇头。

「虽说是不死者，但我想应该是她的天命终于到了尽头。但为了保持最高司祭身为神明的灵性，才会说出这样的藉口……」

「唔……嗯，应该是这样吧。不过……最高司祭亚多米尼史特蕾达终于死了吗……」

夏斯达闭上双眼双手环胸，把上半身靠在椅背上。

他就这样默默思考了很长一段时间，最后才随著简短的一句话迅速睁开眼睛。

「机会来了。」

莉琵雅暂时屏住呼吸，接著用沙哑的声音问道：

「什么机会呢？」

她立刻得到答案。

「当然……是和平的机会。」

在这座城里算是极度危险的名词，迅速溶解、消失在房间的空气中。

「阁下……您认为有这种可能吗？」

面对莉琵雅低声询问，夏斯达看著玻璃杯中红色的液体，一边缓慢但用力地点了点头。

「不管可不可能，无论如何都要成功。」

他一口气喝干红酒，接著说道：

「从创世时代就一直分隔人界与暗之国的『大门』，天命终于快要耗尽。黑暗之国五大种族的军队，看见马上有机会一举入侵充满阳光与地力恩宠的富饶人界，目前已经像是煮沸的热锅了。上一次的十侯会议里，如何分配人界的土地、财宝以及奴隶已经引起很大的纷争。真是受不了……那群家伙的欲望就像是无底深渊。」

夏斯达毫无忌讳的发言，让莉琵雅缩起了脖子。

和被「禁忌目录」这一大册法典所支配的人界不同，暗之国只存在一条法律。也就是──靠力量夺取一切。

从这一点来看，跟即使爬上最高权力的宝座还是拥有无尽征服欲的其他九名诸侯比起来，考虑与人界和平共处的夏斯达才是异端分子吧。

但莉琵雅之所以会被这个男人强烈地吸引，也是因为这种异质的思考。和伺候其他诸侯的女人不同，莉琵雅并非他以强硬手段抢夺而来。夏斯达是拿著花朵对莉琵雅下跪，以真挚的言语向她求爱。

没有注意到爱人心中飘荡著这样的想法，夏斯达以沉重的口气继续表示：

「……但是，那些诸侯太小看人类了。尤其是这漫长的三百年来一直守护著人界的整合骑士团。」

一听见这个名词，莉琵雅就在脑袋即刻发冷的情况下点了点头。

「确实……那些家伙都是技艺超群的剑士。」

「真的可以说是一骑当千。在暗黑骑士团的漫长历史里，被整合骑士所杀的暗黑骑士可以说是不计其数，但反过来的情况是一次都没有。那些家伙的剑技不但精妙，连身上的神器也是强力无比……虽然我也曾数次把他们逼入绝境，但终究没能给予最后一击。当然，败走的经验已经数也数不清了。」

「那是因为……那些家伙会使用奇怪的术法，让剑放出火焰或者光束的缘故……」

「你说『武装完全支配术』吗？虽然也让我们骑士团的术理部研究了很长一段时间，最后还是无法解开这个谜团。即使派出一百名哥布林士兵，也无法抵挡那个技法。」

「但是……我方的军势多达五万。另一方面，整合骑士则只有三十人左右。应该能以数量压倒对方吧……？」

莉琵雅的话，让夏斯达蓄著美髯的嘴角扬起讽刺的微笑。

「刚才说过那些家伙是一骑当千吧。这样算起来，我们也有三万名上兵会丧命。」

「真的……会有如此严重的损伤吗？」

「嗯。虽然不喜欢这种战法，但前方战线由我们骑士团和食人鬼、巨人来支撑，然后暗黑术师群从后方持续施放远距离术的话，整合骑士终究会筋疲力尽吧。但当他们最后一骑倒下时，很难想像我们已经遭受多少损害。虽说可能不到三万，一万五千的话倒是很有可能。」

水晶杯发出「叮」一声清脆的声音后被放到桌上。

单手制止准备帮忙倒酒的莉琵雅，夏斯达把宽阔的背部靠到躺椅上。

「……而这样的结果，当然就是会让暗之五族的力量产生不平衡。十侯会议将丧失意义，五族平等的约定形同虚设。到那个时候，一百年前的『铁血时代』又将来临。不对，应该会比当时更惨。因为这次通往人界，有著饮不尽蜜汁大海的大门已经打开了。光是一百年的时间，还无法摆平争夺那块土地的支配权所造成的纷争……」

这正是夏斯达过去所戒慎恐惧，而且忍不住向莉琵雅重复说过好几次的最糟糕事态。而夏斯达以外的诸侯，都不认为这是最糟的未来──反而等不及那一刻来临了。

莉琵雅低下头来，凝视著叙任为骑士时得到的这套铠甲上，虽然满是伤痕但是擦得相当仔细的黑色光辉。

孩提时期相当矮小的莉琵雅，如果是在「铁血时代」，一定无法成为骑士吧。不是被以奴隶的身份卖给人口贩子，就是被丢在荒郊野外，然后就此结束短暂的一生。

但多亏订立了那个类似和平条约的东西，让她没有被卖到奴隶市场，而是进入幼年学校，结果在那里发现她大器晚成的剑术才能，因此获得就人族女性来说几乎是不可能的最高地位。

目前暗之国的穷乡僻壤依然有许多人口贩子横行，成为骑士之后，她就投入每个月的绝大部分薪水，从这些地方聚集被父母亲丢弃的孩童，并且营运类似育幼院的机构保护他们到进入学校为止的年纪。

这件事情她当然没有告诉过自己的同辈，甚至连夏斯达也不知道。因为连她本身也不清楚自己为什么会有这样的举动。

只不过──

莉琵雅内心的角落，一直感觉这个有力量者就能夺走一切的国家某个地方错了。和夏斯达不同，她没有能够明确表达出内心疑念的智慧，但就算是这样，她还是觉得这个国家──不对，应该是包含人界在内的整个地底世界都存在「更加正确的模样」。

莉琵雅隐约理解到，那个所谓的新世界，应该就存在于夏斯达提倡的和平国度的遥远前方。同时身为一个女人，她也想帮忙自己心爱的男性。

只不过……

「……但是，阁下打算如何说服其他诸侯呢？更何况……整合骑士团真的会接受和平的交涉吗？」

莉琵雅低声这么问道。

「……唔……」

夏斯达闭上双眼，以右手捻著光艳的胡须。最后才用苦涩的声音隐密地说著：

「我认为整合骑士那边应该有机会。如果最高司祭已经死亡，那么目前的总指挥大概是贝尔库利那个老头吧。那个男人虽然狡狯，但可以沟通。问题……果然还是出在十侯会议上。这一边的话……虽然有点矛盾……」

夏斯达张开眼睛，以隐藏著杀气的双眸注视著空中。

「──最少可能得干掉四个人。」

莉琵雅瞬间屏住呼吸，畏畏缩缩地问：

「您说的四个人……指的是两名哥布林族首领、半兽人族首领，以及……」

「暗黑术师公会总长。因为那个女人带有入手亚多米尼史特蕾达不死的秘密，将来自称皇帝的野心。所以应该不会接受和平的提议。」

「但……但是！」

莉琵雅挤出声音来反驳：

「这样实在太危险了，阁下！哥布林、半兽人的首领应该不是阁下的对手……但那个暗黑术师不知道会用什么奇怪的术式啊！」

即使莉琵雅闭上嘴巴，夏斯达还是沉默了好一阵子。

忽然开口的他，从嘴里说出令人意想不到的发言：

「莉琵雅啊。你到我麾下有多久的时间了？」

「什么？啊……呃，嗯……是从我二十一岁的时候开始……应该有四年了。」

「已经过这么久了吗？抱歉这么长一段时间都让你的身份处于暧味状态。怎么样……差不多该那个……」

视线到处游移用力搔了搔头后，暗黑骑士长才有些生硬地说：

「……要不要正式嫁给我？虽然要你委身于我这种大叔有点委屈你就是了……」

「阁……阁下……」

莉琵雅哑然瞪大双眼──

接著心脏附近有一道暖流扩散开来，让她忍不住想立刻飞越桌子，扑进心爱男人的怀抱里，但就在这个时候……

厚重的门后面，传出紧绷的尖锐声响。

「不得了了！不得了了！啊啊，竟然有这种事！诸侯大人们快点……快点出来啊！」

觉得有些熟悉的声音，是来自十侯其中一人，商工公会的头领。

莉琵雅的记忆当中，他有一副俨然是大人物的肥胖体格，但这时完全不符合这种形象的沙哑悲鸣还是持续叫著：

「不得了了！──皇……皇座之间！封印的锁炼！正在震动啊啊啊啊啊！」

2

以皇帝贝库达身份降到皇座之间的加百列‧米勒，带著某种感慨眺望著低头跪在自己脚下的人工摇光们。

他们是被封在一边两英吋的LightCube里头的光量子情报。在这个世界里，他们就是具备知性与灵魂的真正人类。只不过，跪在最前排的十个人里，有半数是容貌诡异的怪物就是了。

自称「诸侯」的十名将军，排在他们身后的骑士与术师们，以及屯驻在城外的五万军队，就是加百列所能掌握的战力。接下来他必须确切地操纵这些棋子，歼灭人界的防卫力并捕获「爱丽丝」。

但是这里和现实世界的即时模拟战略游戏不同，这些棋子不能够随心所欲地以滑鼠或者键盘来移动。必须以言语以及态度加以统率与施加命令。

加百列默默从皇座上站起来，移动几步后，看向贴在后方墙壁上的一面镜子。

映照在上面的，是穿著低俗品味服装的自己。

只有容貌与接近白色的金发依然是现实世界的加百列。但额头上戴著以黑色金属制成，上面镶有深红宝石的皇冠，另外在黑色合成皮革般的皮革衬衫与长裤上，还披著豪华深黑色毛皮长袍。腰上挂著一把散发出朦胧磷光的细细长剑，靴子与手套上都绣著精致银线的刺绣。背上甚至还有一件染了鲜血般的红色长披风。

把视线往右边移动，就能看见皇座往下一阶的位置上，有一名骑士正把双手交叉在脑袋后面四处张望著。

那套如同宝石一般发光的深紫色全身铠甲，主人正是和加百列一同登入到Underworld的瓦沙克‧卡萨鲁斯。虽然已经警告过他，在掌握状况前别得意忘形说出多余的话，但他还是露出极想用俗语表达心中感动的模样，而且还不停用指尖弹出喀哒喀哒的声音。

加百列轻轻摇了摇头，再次把视线移回镜子里的自己身上。

穿惯订制西装的他，实在无法习惯自己的这种模样。但在这个「Underworld」里，加百列已经不是民间军事公司的首席技术长（CTO）。

他是统领广大黑暗领域的皇帝。

而且还是神明。

加百列闭上双眼，深吸了一口气将其呼出。

把扮演的角色由坚强、冷酷的指挥官转变成无情皇帝的开关，已经在他意识里的某个地方被按了下去。

睁开双眼，啪一声翻转深红披风转过身子的加百列──暗黑神贝库达，一面睥睨十名将军，一面让毫无人类味道的声音响彻在皇座之间里。

「抬起头来，报上你们的姓名吧──就从最右边的你开始。」

一名体型肥胖，差点要把额头贴在地板上的中年男子，以出乎意料之外敏捷的动作撑起上半身后，就用流畅的日文报上自己的姓名：

「遵……遵命！我是担任商工公会头领的连基尔‧奇拉‧司科波！」

中年男子再次低头后，旁边宛如小山一般的巨大身躯就开始动了起来。

站起身后应该有十二英呎（三公尺半）的雄伟身躯上交叉缠著发出黑油油亮光的锁炼，腰间盖著兽皮的亚人，这时迅速抬起特别长的鼻梁，以地鸣般的低音报出姓名：

「巨人族首领，西古罗西古。」

当加百列细细咀嚼这个怪物身体里也存在知性与灵魂的事实时，第三个人刺耳的沙哑声音已经响起。

「……暗杀者公会头领……夫萨……」

跟旁边的巨人族比起来过于瘦削且没有存在感的套头长袍模样，让人连他的年龄与性别都无法判别。

加百列虽然一瞬间考虑过命令他露出面貌，但想到像这种暗杀者似乎都有不能以真面目示人之类的禁忌，于是就打消了念头，直接把视线移到下一位将军身上。

下一刻，他的眉毛差点就要皱起来，但还是忍住了。

确实体现了丑恶这个形容词的存在，就这样笨重地坐在地上。因为脚太短了根本无法用膝盖撑起身体。圆滚滚的大肚子上有闪亮亮的油光，一半埋在肩膀里的脖子上还挂著几个应该是小动物头骨的物体。

上面的头部应该说三分像人，七分像猪。有著往前凸出的扁平鼻子、牙齿外露的大嘴，不过小小的眼睛倒是闪烁著带有人类知性的光芒，但这也让他看起来更加恐怖。

「半兽人族首领～利鲁匹林～」

听见那道尖锐的声音后，加百列就想著这家伙究竟是男是女，但这次也马上就抛弃这样的念头。既然自称是半兽人，那就只是低等部队。反正只是用完就丢的家伙。

接著抬起头以灵敏动作行了个礼的，是一个年纪仍可以说是少年的年轻人。头上垂著金红色卷发，晒得黝黑的上半身只缠著皮带。下半身则是紧身皮裤与凉鞋，另外双手上还戴著附有四方形金属铆钉的手套。

「拳斗士公会第十代冠军，伊斯卡恩！」

加百列回看著少年充满干劲大叫的模样，接著在内心浮现出疑问。拳斗士指的是拳击手吗？空手真的可以担任士兵吗？

当他陷入沉思时，突然传出「咕噜噜噜！」的轰然巨响。

声音来源是躯体比不上巨人，但远超过人类的亚人族。上半身几乎全被长长的毛皮盖住。之所以知道那不是服装而是毛皮，完全是因为对方有著兽头的缘故。

那看起来跟狼十分类似。有著凸出的鼻梁、呈锯齿状排列的牙齿以及三角形耳朵。从垂著长舌头的嘴里，发出了很难听清楚的声音：

「咕噜噜……食人鬼……首领……弗鲁咕鲁……噜噜噜……」

虽然不清楚那是他的名字或者单纯只是低吼，加百列还是点了点头并看向下一个人。

一瞬间，响起极为刺耳的尖锐声音：

「山地哥布林首领，哈卡西！陛下，请务必将先锋的光荣任务交给我族的勇士！」

该名矮小的亚人，猿猴般的秃头两侧长出细长的耳朵。身高远矮于刚才报上姓名的巨人、半兽人、食人鬼，甚至连人类都比不上。

根据潜行前克里达的说明，这个黑暗领域里唯一只存在一条法律。也就是有实力者可以支配一切。这样的话，不论从哪一点来看都相当弱的哥布林，究竟是什么力量让他们可以和其他种族平起平坐呢？

虽然再怎么样也不过是地位比半兽人还要低的最低等步兵单位，但对他们多少有些兴趣的加百列看著山地哥布林的脸，内心忽然了解究竟是怎么回事了。因为丑陋亚人的小小眼睛里，可以看见猛烈暴风雨般的欲望。

山地哥布林首领的自我介绍刚结束，坐在他旁边的，只有肌肤颜色不同的亚人也同样以尖锐声音叫了起来。

「千万别听他的！陛下，我们比那些家伙有用十倍！小的是平地哥布林的首领，名叫酷毕力！」

「你说什么，这个专吃蛞蝓的家伙！脑袋被充满湿气的土地浸坏了吗！」

「你的脑浆才是被太阳给晒干了呢！」

开始互骂的两只哥布林鼻子前方──

「啪叽！」一声爆出蓝色火花，两名哥布林首领立刻发出悲鸣并飞退。

「──两位，现在是在皇帝陛下面前哟。」

随著妖艳声音将高举的右手缩回去的，是一名穿著暴露服装的年轻女性。火花则是女性的指尖像打火机的打火石般摩擦时就弹了出来。

缓缓起身的女性，像要夸耀丰满的肢体与妖艳的美貌般挺起腰部，以相当刻意的动作行了一个礼。这时在加百列右侧的瓦沙克低声吹了一下口哨，而加百列也可以了解他的心情。

身上只用黑色珐琅皮革盖住一丁点如同涂了油一般的茶褐色肌肤。靴子有著跟针一样尖的高跟。背上披著闪耀黑色与银色光芒的毛皮披风，上方豪奢的白金色头发则一路垂到腰部。

眼影与口红都是水蓝色的她，这时娇艳地眯起不输给这些颜色的鲜明蓝眼睛，并且报上了姓名：

「我是暗黑术师公会总长，蒂伊‧艾‧耶尔。我麾下的三千术师，以及我本人的身心都是属于陛下。」

虽然声音与动作确实相当妖艳，但完全没有涌起性冲动的加百列只是大方地点了点头。

自称蒂伊的魔女眨了眨眼睛，似乎考虑著该不该继续说些什么，但最后还是默默行了个礼并再次跪下。

加百列心里一边想著「这是聪明的举动」一边移动视线，往下看著最后一名将军个体。静静低著头的，是一名以人类来说体格极为优异的壮年男子。

包裹住全身的漆黑铠甲上有无数伤痕，发出钝重的光芒。垂下的脸上也能看见额头与鼻梁上有淡淡的伤痕。

男人没有抬起头就直接发出的，是沙哑的男中音：

「暗黑骑士团团长，毕库斯鲁‧乌鲁‧夏斯达。在献上我的剑之前……有个问题想请教皇帝。」

这时候才抬起头来的男人，脸上那种严厉表情让加百列联想到过去遇过的少数「真正的士兵」。

名为夏斯达的骑士，双眸里带著之前报上姓名的九位将军所没有的觉悟来凝视加百列，并以更低沉的声音继续说道：

「皇帝陛下在这个时候回归皇座，究竟所为何事？」

原来如此──这些家伙确实不是单纯的程式。

加百列在内心一边提醒自己要时时记住这件事情，一边以无情皇帝的形象冷冷回答：

「鲜血与恐惧、火炎与破坏、死与悲鸣。」

加百列宛如切割金属的硬质声音传出来的瞬间，将军们的表情立刻绷紧。

依序看著十个人的脸后，加百列翻动毛皮披风，高高举起右臂指向西方的天空。

充满征服欲的真心话几乎是自动从他嘴里发出：

「……西方之地充满将朕逐出天界的诸神之力，而保护该地的『大门』随时都要崩毁。所以朕这次回来……是要让地上所有人知道朕的力量！」

关于内部时间一周后就要到来的「最终负荷实验」，已经从克里达那里接受到尽可能详细的说明。加百列根据他所说的内容，以演戏般的口气继续自己的演说：

「大门崩塌之时，人界将成为我们暗之民的领土！朕唯一需要的，就只有同时出现在那个地方的『神之巫女』一个人！除此之外的人类，汝等可以随意烧杀、掠夺！现在就是所有暗之民期待以久的──约定之时了！」

插图013

一瞬间笼罩在现场的沉默空气──

被尖锐、野蛮的吼叫声打破了。

「叽────！要尽情地杀！我要杀光白伊武姆啊啊啊啊啊！」

双脚急速踩地不停叫唤的，是小眼睛里充满欲望与愤怒的半兽人首领。两只哥布林首领也随即高举双手跟著大叫：

「吼哦哦哦哦哦呜！开战了！开战了！」

「呜啦────！战争开始了────！」

充满斗志的声音，立刻影响了其他将军以及站在他们背后的众军官。暗杀公会那些穿著黑色斗篷的家伙缓缓晃动著如树枝般纤细的身体，暗黑术师公会的魔女集团也随著娇声发射出各种颜色的火花。

宽敞的大厅里，目前正充满了原始的野蛮叫声──

加百列注意到只有名为夏斯达的骑士依然一动也不动地低著头跪在地上。

从身穿铠甲的他那如同雕像般的模样，根本无法判断这是军人的自制心，或者是源自某种感情。

＊＊＊

「没想到兄弟竟然有这种才能！我看你应该去当演员比较好吧？」

瓦沙克一边面露微笑一边把红酒瓶拋过去，加百列则是用鼻子冷哼了一声来回应。

「只是因应需要。你才应该学点像样的演说方法，你的位阶比那些家伙还要高啊。」

接过瓶子后用指尖弹开木栓，含了一小口红宝石色的液体后，忽然思考起这样算不算是在作战中喝酒。

瓦沙克像是要表示不喝白不喝一样，把这看起来相当高级的陈年好酒当成啤酒猛灌，然后用力擦了一下嘴角才回答：

「跟发布命令还是演说比起来，我比较想在前线冲锋陷阵。难得能潜行到这么逼真的VR世界……这酒和瓶子就跟真的一样。」

「相对的，被砍中的话会感到疼痛，而且会流血。这里可没有什么疼痛缓和装置。」

「这样才好啊。」

对露出奸笑的瓦沙克耸了耸肩后，加百列把酒瓶放回桌上，并从沙发上站起来。

黑曜岩城最上层的皇帝居所，比GlowgenDS总公司大楼的董事室还要宽敞，从巨大的窗户可以清楚看见城下聚落的夜景。明亮度与鲜艳度虽然比不上圣地牙哥的夜景，但是带有奇幻气息。

自称诸侯的十名将军为了开战准备而离开城堡，从仓库里搬出物资的锱重部队正拿著火把不停地在大路上移动。由于已经命令负责补给任务的商工公会头领把城里储备的所有装备与食粮用尽，所以士兵们应该有很长一段时间不会受冻挨饿才对。

加百列把视线从无数的光芒上移开，走到房间角落后，用手触碰设置在那里的紫色水晶板──也就是系统操纵台。

他迅速地操纵选单，按下呼叫外部观察员的按钮。时间加速倍率瞬时降低，在回归等倍时间的奇妙感觉中，克里达急促的声音从画面里传出：

「是队长吗？刚才看完队长与瓦沙克的潜行，现在才刚回到主控室而已！」

「这边已经是第一天晚上了。虽然早有心理准备，但时间加速是很奇妙的感觉。总之目前一切按照计划进行。一两天以内就能完成部队的准备，预定两天后就要开始进军人界。」

「太棒了。请听我说，捕捉到『爱丽丝』后，请把她带到那里，然后从选单选择弹射到主控室的操作。这样『爱丽丝』的LightCube就是我们的了。还有，这一点请特别要叫瓦沙克那个笨蛋注意一下。」

可能是听见克里达的声音了吧，瓦沙克从后面发出简短的咒骂声。

「在无法操纵管理者权限的现状下，我没办法重置帐号。也就是说，队长和瓦沙克如果在内部死亡，就没办法再使用这两个超级帐号了。这样就真的得从一名小兵开始干起了！」

「嗯……我知道了，现在就先不要到前线去吧。自卫队有什么动静吗？」

「目前没有，似乎还没有注意到队长你们已经潜行到Underworld了。」

「好，那么我要切断通讯了。希望下一次联络时已经捕获爱丽丝了。」

「了解，期待你们的成功。」

关闭通讯视窗后，加速倍率再次随著些许不对劲的感觉恢复。

瓦沙克原本还是一边咒骂一边和铠甲的挂钩格斗中，最后终于把所有金属装备丢在地上，只穿著皮革衬衫与长裤站在现场。

「那个……兄弟啊，真的不能稍微去城里玩一下吗？」

「先忍耐一阵子吧，作战结束后会给你一个晚上的时间。」

「了解。杀戮和女人都只能暂时忍耐吗……那我就乖乖去睡觉吧。我用这边的房间喽。」

瓦沙克一边让关节发出喀叽喀叽的声音，一边消失在邻接的一间寝室里后，加百列才呼一声吐了口气，把皇冠从头上拿下来。

接著又把夸张的披风与长袍挂在沙发上，把剑扔到上面。

之前玩过的VR游戏，装备只要一解除就会回到道具栏里，但这个世界似乎没有这种便利的机能。这样下去的话，在这里生活一个月房间似乎就会变得凌乱不堪，不过反正后天就要离开城堡，下次回来应该就是为了登出了。

加百列一面解开上衣的钮扣，一面打开瓦沙克对面房间的门──随即又因为惊讶而眯起眼睛。

同样是异常宽敞的寝室里，豪华得让人傻眼的床铺旁边，有一道平伏在地上的小小人影。应该已经命令过，包含仆人在内的所有人，都不准到城里比皇座之间更上方的楼层来了。竟然有人敢违抗神明的命令，这究竟是怎么回事？

一瞬间考虑著是不是该把剑拿回来，但加百列最后还是刻意就这样走进寝室当中，然后随手把门关上。

「……是谁？」

他简短地询问来者身份。

传回来的是有些沙哑的女性声音：

「……今天晚上由我来侍寝。」

「哦……」

单边眉毛稍微挑动了一下后，加百列随即横越寝室，走到床铺旁边。

双手撑在地上的，是一名只穿著单薄衣物的年轻女人。灰蓝色头发高高盘起，用装饰的发带固定住。从微微透出来的身体线条上，感觉不到带有武器的气息。

「是谁的命令？」

一边坐到光艳的丝质床单上一边这么询问后，女人隔了几秒钟才压低声音回答：

「没有人命令，这本来就是我应该负责的工作……」

「这样啊。」

加百列移开视线，重重把身体躺到床中央。

几秒钟后，女人撑起身体，无声地滑到他右侧。

「失礼了……」

如此呢喃的女性，带有异国风味的美貌让加百列也忍不住在心中发出赞叹声。肌肤颜色虽然较深，但颧骨附近有种北欧式的高雅气息。

加百列一边往上看著她轻轻褪下单薄衣裳，同时解开固定头发的发带，内心也一边出现某种感动。

人工摇光甚至懂得做这种事吗？

连这样的女子，都还不能算是真正的AI吗？这样的话，已经是完成形的爱丽丝究竟到达什么样的高度？

让加百列心动的，不是女人献出自己身体的行为。

而是因为──

他早已预测到女人从飘散开来的头发中迅速拔出，并且高高举起的锐利小刀的存在。

轻轻松松就抓住女性右手的加百列，另一只手迅速掐住对方纤细的脖子，并把她拉倒在床上。

「咕……！」

女人即使已经咬紧牙根，依然剧烈反抗想刺出小刀。虽然拥有超乎想像的臂力，但依然不足以让加百列感到慌张。他的右手架住对方惯用手的关节，左手拇指稍微掐入对方喉头来封阻其动作。

脸庞虽然因为剧痛而扭曲，但女性灰色眼睛里的决心并没有因此变淡。从她凶猛的表情、拙劣的化妆以及肌肉的发达程度，就能知道她不是专业的暗杀者。这样的话，带有反意的就应该不是自称夫萨的暗杀者头领，而是其他九名将军的其中一人吗──恐怕是人族将军里面的某个人吧。

加百列把脸靠近女人，说出跟刚才一样的质问：

「是谁命令你的？」

低沉沙哑的声音也说出相同的回答：

「是我自己的……意志。」

「这样的话，你的长官是谁？」

「……我没有长官。」

加百列不带一丝感情，像机械一样进行思考。

「RATH」想要突破的人工摇光界限点。就是能否违抗上级给予的规则、法律与命令。

和被无数法律束缚的人界居民比起来，黑暗领域的民众乍看之下一直过得相当自由，但本质上其实没有不同。只是这一边的摇光只被赋予一条法律，所以看起来才很自由。

那条法律就是「用力量夺取一切」。这里是拥有较强战斗力者，就能够支配弱者的弱肉强食世界。只要RATH的实验照计划继续进行下去，就算加百列没有介入，崇尚秩序的人界与充满浑沌的暗之国也会发生冲突，而他们似乎就是预定以这场大战做为触媒，藉此来突破下一次的界限。

但不知道什么理由，在计划进行到此之前，人界就出现突破界限的摇光。但RATH里的间谍并没有传出暗之国也出现相同摇光的情报。

也就是说，拿一把小刀就企图暗杀皇帝的女人，一定也是被绝对法律所束缚的灵魂。但她在接受加百列的质问，不对，应该说命令之后也不肯说出自己主人的名字。这也就表示，跟身为皇帝与神明的加百列所发出的命令比起来，这个女人选择了对自己主人的忠诚心。换言之，她认为自己的主人比皇帝还要强。

为了让今后的作战能够顺利进行，似乎有必要好好在将军与干部个体前面展示战斗力，让他们事先知道加百列──皇帝贝库达是这个世界最强的存在。但也不能把所有将军都杀光。这下该怎么办才好呢？

──不对。

不论如何，一定得处分掉其中一名将军。让这个女人抱持暗杀之意的家伙一定得死。

那么该如何找出背叛者呢？再次联络克里达，要他从外部监视将军个体吗？不行，要这么做的话，就必须把时间加速固定在一倍，这样反而会浪费掉现实世界所拥有的宝贵时间。

那么──

一瞬间就想到这里的加百列，再次用钢铁色的眼睛凝视著女人。

「为什么要朕的命？被钱收买了？还是约定好要给你地位？」

没有想太多就做出这样的发言，但对方立刻说出超乎想像之外的回答：

「这都是为了大义！」

「哦……？」

「现在开始战争的话，历史将退后一百……不对，是两百年！不能再回到弱者就得遭受虐待的时代了！」

加百列再次感到些许惊讶。

这个女人，这样真的还是在尚未突破界限的状态吗？如果是这样，是她的主人让她说出这样的话吗？

插图014

加百列把脸靠过去，从近距离凝视著她的灰色眼睛。

决心、忠诚，另外隐藏在深处的这种感情是…………

啊，原来如此。

如果是这样，那就不需要这个女人了。正确来说，是不需要这个女人的摇光了。

加百列遵照自己所下的判断，不再说任何多余的话，掐住女人脖子的左手直接开始用力。

颈骨开始发出「哔叽」的碎裂声。女人睁大双眼，嘴里发出无声的悲鸣。

加百列确实地按住她挣扎的四肢，一边残忍地勒紧她的脖子，一边感受到跟刚才完全不同的惊讶。

这里真的是假想世界吗？传达到左手上的，肌肉与软骨逐渐被破坏的感触，由外露的肌肤放射出来的恐惧与痛苦的气味，都比现实世界更加强烈地刺激著五感。

身体在下意识中开始震动，左手也反射性开始收缩。

喀叽。随著这道钝重的声音，不知名的女人颈骨就这么被粉碎了。

这时候加百列看见了。

从紧紧闭上双眼，用力咬紧牙根的女人额头──涌出了七彩光芒。

这无疑是那个时候──年幼的爱丽西亚丧命时所看见的灵魂之云。

加百列瞬时张大嘴巴，把女人的灵魂全吸了进去。

先是由恐惧与痛苦产生的苦味。

再来是悔恨与悲伤的酸味。

接著加百列的舌头就浸在笔墨难以形容的天堂之蜜当中。

闭上的眼睑里，不停闪过朦胧的光景。

在老旧的两层楼建筑前院游玩的幼小孩童们。有人类、哥布林以及半兽人。小孩子一看到自己，脸上就露出高兴的光芒，张开双手往这里跑过来。

这些影像消失后，这次又看见一个男人的上半身。女人以柔情紧紧抱住那经过严格锻炼的厚实胸膛。

「我爱你……阁下…………」

出现这道细微的声音，然后回响并逐渐远去。

等一切全部消失后，加百列还是持续紧抱著女人的尸骸。

太棒了，竟然会有这么棒的体验。

加百列的大部分意识都因为无上的喜悦而震动，只有剩下来的一部分理性想为刚才的现象做出解释。

收纳女人摇光的LightCube与加百列本身的摇光，介由STL连结在一起了。因此天命，也就是生命值归零后解放出来的量子档案断片，可能就经由线路逆流回来了。

但什么原理之类的东西已经不重要。

自己终于再次体验到赌上人生追求的现象。自己将濒死的女人最后抱持的感情──也就是爱完全摄取、玩味过了。那简直就像是降在久旱沙漠中的甘霖。

不够。

完全不够。

还要多杀一点人才行。

加百列把身体整个往后仰，开始发出无声的哄笑。

＊＊＊

加百列满足地望著十名将军与各阵营的干部整齐列队，并且恭恭敬敬地低下头的模样。

他们完全依照命令，在两天内完成了进军的准备。说不定，这些将军个体还比现实世界里GlowgenDS总公司那些占据董事位子的家伙还要优秀。

甚至干脆想直接把他们当成完成品。除了无可挑剔的事务处理能力之外，还有如此的忠诚心。做为放在战争用机器人上面的AI，可以说再适合也不过了。

不过还是不能忘记，众将军的忠诚是来自于RATH一直相当执著的人工摇光问题点。正因为他们的灵魂都被烙印了，拥有最强力量者可以支配一切这个大原则，这十名将军才会遵从身为皇帝的加百列‧米勒，不对，应该说是暗神贝库达。这同时也表示，在对皇帝的力量产生怀疑的瞬间，就很有可能会出现背叛者。

而这样的担心已经变成现实了。

两天前的晚上，偷偷潜入寝室的女暗杀者。

那个女人想要杀死身为最高权力者的皇帝。她的心里应该存在比加百列更加上位的主人。就是她在临死前称为「阁下」的某个人。而且几乎可以确认，那个人就是排在下方的十名将军之一。

对她来说，自己的主人比皇帝贝库达还要强。这样的话，那个阁下本身也很可能不是真心效忠于加百列。在麾下有这种个体的情况下上战场，可能会出现在休息时遭到偷袭的情况。

因此出征前最后的任务，就是从十个人当中把那个阁下找出来。

同时也能向剩下的九个人展示皇帝的力量。永远在他们的摇光里刻下究竟谁才是最强者的印象。

这时候，加百列‧米勒完全没有考虑过自己逊色于下方十名个体──也就是一对一战斗时会落败的可能性。他依然有著Underworld不过是游戏延伸出来的VR世界，存在里面的所有个体都是人造物（NPC）的固有观念。

＊＊＊

毕库斯鲁‧乌鲁‧夏斯达保持垂头跪地的姿势，脑袋里想起了师父说过的话。那是二十多年前，在暗黑骑士团本部修练场所发生的事情。

「──我师父的师父，是头被砍掉而立刻死亡。我的师父是胸口被贯穿，在回城的半路上过世。至于我虽然被砍断了一只手，但还是像这样活著回来了。虽然这不是什么值得骄傲的事情就是了。」

在乌亮地板上正坐的师父，说完就对夏斯达展示手肘以下被漂亮切断的右臂。以药物止血，简单包扎著绷带的伤口让人惨不忍睹。

三天前才刚造成这个伤口的，正是暗黑骑士的宿敌，同时也是世界最强剑士，或许也可以说是最恐怖怪物的──整合骑士长贝尔库利‧辛赛西斯‧汪。

「你知道这代表什么意思吗，毕库斯鲁？」

当时只有二十多岁的年轻夏斯达只能露出疑惑的表情。师父把受伤的手臂拽回衣物怀里，闭上眼睛丢出一句话：

「终于逐渐追赶上了。」

「追赶上──是说那个人吗？」

年轻的夏斯达无法压抑声音里面的不信任感。因为贝尔库利的剑技就是带有如此压倒性的实力。即使过了三天，师父的右臂拖著鲜血高高飞起的瞬间，自己的背椎骨像是被冰柱贯穿般的冷气依然没有消失。

「我今年就五十岁了。但别说是挥剑的方式了，感觉自己就连握剑都还不敢说已经了解奥秘。我想再过五年、十年，等我要死的时候也还是一样。」

师父静静地继续说道：

「……那个家伙已经活了两百年，生命短暂的我们，不可到达那种境界。虽然很丢脸，但挥剑交手的瞬间，我心中确实有这种放弃挣扎的想法。但狼狈地败逃回来之后，我才了解到自己的想法错了。我的师父以及师祖们这么久以来持续挑战那个男人的努力都没有白费……毕库斯鲁啊──何谓究极的剑技呢？」

面对这突然的问题，夏斯达反射性地回答：

「是『无想之剑』。」

「没错。经由长年的修行后与剑合为一体，没有任何斩杀对方或者拔剑的想法，甚至没有经过思考就自然有所行动的一击才是究极的剑技。我的师父这么教我，而我也是这么教导你。但是……毕库斯鲁啊，其实并非如此。还有更进一步的阶段。我被那个怪物砍伤后，终于了解了这个事实。」

师父上了年纪的面容稍微闪过兴奋的神色。依然保持正坐姿势的夏斯达也忍不住探出身体。

「您说的下一阶段是……」

「无想的极端相反，坚固的确信。也就是意志力啊，毕库斯鲁。」

师父忽然高高举起手肘以下整个被切断的右臂。

「你也看见了吧。那个时候，我从右上段往下砍落。那确实是无想的斩击，也是我生涯最快的一剑。一开始的动作的确是我领先贝尔库利。」

「是的……我也这么认为。」

「但是，但是呢。他原本应该会被我的剑弹开的格挡，竟然反而把我的剑推开，砍断了我的手臂。你相信吗，毕库斯鲁……那个瞬间，那家伙的剑甚至没有碰到我的剑啊！」

夏斯达顿时说不出话来，接著僵硬地摇了摇头。

「怎……怎么可能有这种事……」

「这是事实。简直就像斩击的轨道，被看不见的力量错开了一样。那不是术式，也不是武装完全支配术。我想只能这样说明那种现象了。就是我的无想之剑，败给了那家伙花了两百年时间锻炼出来的意志力。那家伙想像自己的剑应该划出什么轨道的思绪实在太过强烈，结果就成为不变的事实！」

夏斯达无法立刻相信师父所说的话。

意志力这种无形的东西，究竟要如何弹开确定存在的，又重又硬的剑呢？

师父似乎也预测到夏斯达会有这样的反应。只见他端正自己的坐姿，在乌亮的地板上静静地命令：

「毕库斯鲁啊，我要傅授你最后的剑诀──杀了我吧。」

「您……您在说什么啊！好不容易才……」

夏斯达只能把「存活下来」这几个字吞了回去，因为师父的双眸忽然出现强烈的眼光。

「就是因为捡回一命，我才一定得死在你手上。在败给那家伙的一击之后，我在你心中已经不再是最强者。这样的我如果还活著，你就没办法以对等的身份和那个家伙作战。所以你也要砍了，不对，杀了我，和那家伙……贝尔库利站在同样的高度！」

这么说完后，师父就站起来，以被砍掉的右臂摆出握剑般的姿势。

「来吧，站起来！拔剑吧，毕库斯鲁！」

于是夏斯达砍了师父，亲手了断他的生命。

同一时间，他也亲身体验到师父所说的话究竟是什么意思。

握在师父右手上的透明利刃──名为意志的剑，在交错的瞬间和夏斯达的剑爆出剧烈的火花，而他的脸颊也真的被割伤，留下再也无法消失的伤痕。

在脸庞被泪水与鲜血濡湿的情况下，年轻的夏斯达站到了超越「无想之剑」的秘技，也就是「心念之剑」的起点。

岁月就这样流逝──到了五年前。

夏斯达终于挑战了暗黑骑士的宿敌，整合骑士长贝尔库利。时年三十七岁的他，感觉自己的剑技已经到达了巅峰。

虽然师父以一条手臂来换取生命，但夏斯达当时已经有不成功便成仁的觉悟。因为夏斯达没有收做为后继者的徒弟。他不想让年轻人背负斩杀师父，将来有一天也会丧命于弟子手上的命运。他决定以自己的性命来斩断这血腥的循环。

带著最大的决心与觉悟，也就是被称为「心念力」的剑，和贝尔库利的首招剑技由正面互抵，完全没有被对方弹开。但这个时候夏斯达已经有了落败的预感。他不认为自己能够再次挥出如此沉重的斩击。

但贝尔库利就在双方用剑互抵的情况下发出浑厚的笑声并低声说道：

「不错的剑招。纯粹只有杀意的剑，不可能挡住我的攻击。仔细想想我的意思，五年后再来吧，小伙子。」

接著整合骑士长就拉开距离，悠然离开现场。不知道为什么，就是没办法对他乍看之下满是破绽的背部挥剑。

想理解贝尔库利的言外之意，必须花上很长一段时间。但经过五年的现在，夏斯达觉得自己可以理解了。那个时候夏斯达的剑上要是只带著杀意与憎恨，恐怕在两把剑互抵的时候就已经输了。虽然只有短短一回合，但自己之所以能够和挥剑他互相抗衡，应该就是藏在心中的觉悟胜过杀意的缘故。

所谓的觉悟就是──对诸位先贤牺牲性命来传承剑艺的感谢之意，以及对那些将继承自己意志的年轻人的祈愿。

所以夏斯达接到最高司祭已死的情报时，马上就决定开始和平谈判。他确信那个贝尔库利一定会接受自己的和谈。

而自己也因为同样的理由──

必须斩杀一降临到黑曜岩城，就不由分说决定开战的皇帝贝库达。

夏斯达虽然垂著头跪在地上，但已经开始凝聚加诸在必杀之剑上的心念。

离开数百年后再次复活的皇帝，是一名简直像人界人民一般，拥有白色肌肤与金发的年轻男性。不论是体格或者容貌，都不是那么有迫力。

但只有那双特别蓝的眼睛，显示出皇帝绝非泛泛之辈。他眼睛深处是一片虚无。像是能吸收一切光芒的无底深渊。这个男人隐藏著巨大且邪恶的饥渴。

如果凝聚起来的心念之力完全被皇帝的虚无吞没，那么自己的剑就伤不了他。

那个时候，暗黑将军夏斯达将会死亡。但意志应该会被后继者继承下去才对。

目前心头唯一的牵挂，是莉琵雅昨天晚上没有到房间来，所以没办法向她传达自己的决心。不知道是忙于出征前的杂务，还是回到她相当看重的「家」里去了。

如果对她表明斩杀皇帝的计划，她一定会不听劝告，坚决陪自己一起行动。所以没有见到面反而是件好事。

夏斯达缓缓吸了口气并憋在胸口。

然后悄悄以左手指尖触碰从腰上解下来放在地板上的爱剑。

目前距离皇座大约十五梅尔，是只要踏两步就能到达的距离。

第一动绝对不能被发现，拔剑时必须进入无想的境界。

夏斯达开始由指尖朝著爱剑注入提升到极限的心念之力。然后让身体放空。

正当他────

左手准备抓起剑鞘的前一刻。

皇帝用让人联想到玻璃的坚硬、光滑的声音，随口说出：

「对了，前天晚上，有人潜入朕的寝室。而且头发里还藏著短剑。」

经过抑制的惊讶立刻骚动了大厅的空气。

排在夏斯达左手边的九名诸侯，有的屏住呼吸，有的从喉咙发出低吼，也有的把身体沉进厚厚的斗篷里。就连退居后方的干部群行列中，也传出好几道惊呼声。

夏斯达也同样感到惊讶。他保持著准备开始斩击的姿势，瞬间开始思考。

也有其他人做出必须铲除皇帝这个结论。可惜的是，由皇帝目前平安无事来看，就能知道对方没能得手──但九个人里面，究竟是谁派出刺客呢？

亚人五侯应该不可能。巨人、食人鬼、半兽人就不用说了，就连比较矮小的哥布林都不太可能避开卫兵的耳目潜入最上层。

把眼神移向人族的四侯后，首先就能排除掉身为拳斗士首领的年轻伊斯卡恩，以及商工公会头领连基尔。伊斯卡恩是以穷究空手斗技为唯一目标的直爽小鬼，连基尔则是认为开始战争就能大赚一笔。

从潜入寝室这样的手法来看，暗杀者公会的会长夫萨似乎相当可疑，实际上那个男人有时候确实让人摸不透他的想法，不过使用短剑就说不通了。

暗杀者公会躲在黑暗洞穴里不停研究的，是术式与剑技之外的第三种力量，也就是毒。夫萨一族是术式行使权限、武具操作权限都不突出的人们为了活下去而集结的团体。他们有自己独特的规范，能够使用的武器最多也只有涂了毒的暗器或者吹箭。而短剑并不包含在内。

跪在左侧的暗黑术师首领蒂伊‧艾‧耶尔也能用同样的理由将其排除在外。这个几乎可以说由权力欲所构成的女人，确实可能有干掉皇帝一口气成为暗黑界支配者的想法，但蒂伊派出的暗杀者应该不是使用短剑而是术式才对。

但这样的话，就不知道九名诸侯当中究竟是谁派出刺客了。

剩下来的就只有一个人，也就是暗黑骑士长夏斯达本人。

他当然没有做过这种事。因为他已经下定决心赌上性命，亲手挥剑来解决皇帝。不要说下令部下进行暗杀了，他甚至没有跟人提起过隐藏的决心──

不对。

等等……

难道说……

皇帝提出暗杀者的话题后，一瞬间就思考到这里的夏斯达，意识到放在剑鞘上的左手指尖迅速变得冰冷。

凝聚起来的意志力一瞬间变质。成为忌虑、不安、恐惧以及不祥的确信。

几乎是同一时刻，皇帝贝库达也说出第二句话：

「我不准备审问派出刺客的人。行使自己的力量来获得更强权力的志气确实值得鼓励。想要朕的脑袋，随时可以从后面偷袭。」

睥睨再次产生低声骚动的大厅，皇帝白皙的脸上首次出现类似表情的变化──那是浅浅的微笑。

「当然，必须知道做出这样的赌注也得付出相当的代价。比如说……像这样。」

从漆黑长袍里伸出来的手，轻轻做了一个手势。

设置在皇座旁边，从夏斯达的方向来看是东侧墙壁的门无声打了开来，一名年轻的女仆静悄悄地走了进来。她的双手上捧著一个大大的银盆，上面似乎放著某种四角形的物体，但因为被黑布盖著而看不出究竟是什么。

女仆把银盆放在皇座前面，对皇帝恭敬地低下头，接著再次走回门里。

紧绷的寂静当中，皇帝贝库达的嘴角带著某种扭曲的笑容，像是要踩踏盖在银盆上的布一样，以长靴的鞋尖把布挑开。

全身冻住的夏斯达，双眼捕捉到的是──

蔚蓝通透的冰块立方体。

被封在内侧的，是陷入长眠状态的心爱女性。

「莉……琵……」

雅。夏斯达只动著嘴唇说出这三个字。

甚至连包裹全身的冷气都消失，只有无尽深邃与黑暗的虚无充满胸口。

夏斯达知道暗黑骑士莉琵雅‧扎恩克尔暗地里经营孤儿院的事情。莉琵雅她不分种族地收养失去双亲、兄弟，只能在野外等死的孩子们，而夏斯达则觉得从她这样的行为上看见了未来的希望。

所以夏斯达只对莉琵雅说出自己的理想。解决和人界之间长久以来的战争状态，创造、孕育出不再互相争夺，能和平共存的世界，这就是夏斯达一直以来的梦想。

但就是这样的梦想驱使莉琵雅去刺杀皇帝，导致她在众人面前暴露出如此悲惨的模样。虽然杀了她的是皇帝──但同时也是夏斯达本人。这是无庸置疑的事。

虽然是一瞬间发生的变故，但也因此而让极为巨大的悔恨与自责的暴风雨在夏斯达空虚的心里肆虐。

不用花太多时间，暴风雨就转变成一股黑暗的情感。

也就是杀意。

一定要杀掉他。无论如何都要杀死那个翘脚坐在皇座上，脸上露出浅浅微笑的男人。

就算得牺牲自己的性命与黑暗领域的未来也在所不惜。

＊＊＊

那么，究竟哪个家伙是女人口中的阁下呢？

加百列带著些许兴趣，眺望著跪在眼下的十名首领个体。

那个女刺客打从心里爱著自己的主人。加百列完全吸收了女人临死前散发出的，类似琼浆玉露的感情，除了女性的思慕之外，他甚至了解那个阁下对女性的爱情质量──当然自己只把它做为参考数据而已。

所以他确定只要让这几个人看见女人的首级，被称为阁下的人物一定会有所行动。毫不容情地处分背叛的个体，藉由恐惧心来提升其他个体的忠诚度。就像现实世界里用来打发时间所玩的战略模拟游戏那样。

真是一群可怜又有趣的家伙。

具备真正的灵魂但是知性却遭到限制，而且不论怎么杀都能重新再生。当自己入手构成Underworld的大型电脑与LightCube时，一定就能尽情满足从小至今一直折磨著自己的饥渴吧。

把手肘靠在皇座扶手上的加百列，用手背撑著脸颊，然后放松心情等待著。

和个体们的距离大概有十五公尺左右。这样的距离下，不论对方用什么武器发动攻击，都能有充裕时间以装备在左腰上的剑加以迎击。

当然，这样根本不足以防备由「System call」开始的术式攻击。但加百列的不安在登入到游戏前就已经消失了。

超级帐号「暗神贝库达」是为了让RATH员工强制介入黑暗领域时使用。因此被称为天命的HP极为庞大，装备的剑也是最强。最重要的是，贝库达还拥有无法被指定为任何术式攻击对象的犯规特性。

如此多条件庇护下的加百列，在十个个体跪在最左端的漆黑铠甲骑士瞬间缩起背部时……

以及他的全身笼罩在淡淡影子般气息里时……

甚至连看见骑士左手如闪电般一闪，握住放在地板上的剑鞘，同时迅速抬起脸，由刚毅面容中央的双眸放射出非人深红光芒的时候也──

无法完全理解持续发生当中的事象。

这个世界除了是在物理伺服器内进行演算的程式之外，同时也是由和人类摇光同质的光量子所构筑的「现实梦境」。

因此黑色骑士所散发的纯粹且强烈的杀意，是从他的LightCube到Main Visualizer，然后经由量子通讯回线传达到连结在STL的加百列身上。

＊＊＊

夏斯达染成血色的视线中央，只能看见皇帝一个人的模样。

右臂以生涯最快的速度一闪后拔出了剑。

从剑鞘被解放出来的，不是由师父那里继承来的神器，长刀「胧霞」那熟悉的灰色刀身。正如它的刀名一样，类似夜雾的浓厚霭气围绕著长大的刀刃，不停形成漩涡与扭曲著。

夏斯达虽然没注意到这种现象的逻辑，就跟长年研究但还是无法理解的整合骑士究极奥义──武装完全支配术完全相同，但对他来说这已经不再重要了。

「杀！」

随著剎那的吼叫声，夏斯达把所有愤怒、憎恨以及哀伤贯注在爱刀上，将其高举过头部。

3

从人界北端到东域的尽头。

整合骑士爱丽丝以及出生在西帝国的雨缘，都是第一次到访四帝国当中充满最多谜团的伊斯塔巴利耶斯东帝国。

眼下峰峰相连的奇岩之间，可以看见琉璃般湛蓝的河水滔滔不绝地流动。有时会出现在河边的城镇或村庄，不像在北方见惯的石造，大部分是由木材建造而成。

仰望天空指著爱丽丝这边的人们，头发也几乎都是黑色。爱丽丝忽然想起，一直都和自己不对盘的整合骑士团副团长法那提欧就是出身自此地。

把视线移回前方后，就注意到靠在握著缰绳的爱丽丝身上，茫然眺望著天空的桐人也有一头漆黑的头发。说不定这个人也是出身于东域，虽然也想过降到街上让他和人们接触的话，说不定就能让他恢复意识，但目前还是得尽快赶到目的地才行。

夜晚在远离聚落的地方野营，吃著雨缘抓来的鱼与携带用的干果，马不停蹄地赶了三天的路之后──

在十一之月二日的午后，只有这一点和北方完全没有两样的高耸尽头山脉，以及像神明直接垂直砍断岩壁的峡谷就出现在前方。

「……看见了喔，桐人。」

爱丽丝呢喃著，轻轻地抚摸不得不背负沉重行李进行长途飞行的爱龙脖子。虽然在魔兽种类几乎完全消失的现在，飞龙已经是能以拥有最大等级天命为傲的生物，但背负两个人与三把神器的飞行依然是相当大的负担。这半年来尽情吃鱼而积蓄起来的力量，似乎也因为这次的飞行而几乎用尽。

爱丽丝心里想著到达野营地之后，无论如何都要让它尽情地享用喜欢的烫羊肉并甩了一下缰绳，雨缘也以感觉不到疲劳的声音回应，接著用力拍动翅膀。

由远处看感觉只有极细间隔的峡谷，靠近之后才发现自己太看轻它了。

山谷的幅度应该宽达一百梅尔左右吧。这已经足够半兽人与食人鬼的大军团排成横列往前突进了。

贯穿山壁笔直往前延伸的山谷，前方有一片宽广的草原像要包围住入口处一般，这时可以看见无数白色帐篷整齐排列在草地上，形成一处广大的野营地。此外到处可以看见炊烟升起，周边还有士兵们正在接受训练。长剑挥动时的光芒，以及发出的呼喊声甚至直达天际。

看来士气不像担心的那么低，但士兵的数量本身实在太少了。稍微环视了一下，就能知道总数大概不到三千人。另一方面，黑暗领域的侵略军应该不下五万。在人界里，士兵与侍卫是赐予极少数人的天职，但山脉后面的世界却不问男女老幼，只要能够作战就都是士兵。

在这种状况下，再加上爱丽丝一个人应该也不会有太大的改变。骑士长贝尔库利，究竟想到什么样的防卫作战呢……

这么默默思考著的爱丽丝首先飞越野营地，让飞龙前往沉浸在微暗当中的峡谷。

「抱歉喔，雨缘，再飞一下下。」

如此对龙搭话，而它也以咕噜噜的声音回应后，索鲁斯的光芒就被块状山脉遮住了。

一进入山谷的瞬间，身体就被足以令人打冷颤的寒气包围。左右两边直立的岩壁光滑到让人觉得这绝对是由神明所切割出来。上面别说是生物了，就连一株草木都看不见。

就这样低速飞行了几分钟──

漫长霭气后方，终于出现了无边巨大的构造物。

「这就是……『东大门』…………？」

垂直耸立的灰色大门，从下部到顶端应该足足有三百梅尔高吧。虽然比高达五百梅尔的中央圣堂还要矮，但压迫感可以说不相上下。

最惊人的是，左右两边的大门是从几乎看不出任何一丝接缝的一整块岩石所切割而成。这样的物体别说是经由人手所建筑了，甚至不可能藉由神圣术来加工生成。最高司祭亚多米尼史特蕾达生成的最大构造物是将央都圣托利亚分割为四等分的「不朽之壁」，但那些相连的壁面每一块都比这扇门要小得多。

这道大门，是世界开始之时由神亲手设置在此地的东西。这当然是为了分隔人界与暗之国──同时也是为了造成三百数十年后的这场惨剧。

「停下来吧，雨缘。」

让飞龙在空中停下来，爱丽丝再次从近距离仰视著门。

高达两百梅尔左右的地方，可以看到一些神圣文字像要连结成左右两扇门的灰色岩板般写在上面。

「Destruct……at……the、last、stage……」

好不容易才念出中间的一行，但完全不了解意思。

就在她露出狐疑表情的瞬间，突然有「哔叽叽」的强烈破碎声震动空气，让爱丽丝跟雨缘吓了一大跳。一边摸著龙的脖子一边凝睛的爱丽丝，随即看见刚才还相当光滑的门上，有几条宛如漆黑闪电般的细微裂痕划过。

延伸数十梅尔的龟裂好不容易停止，接著周边有几片岩石剥落，消失在遥远下方的谷底。

爱丽丝抬起脸来，再次将视线放在大门上。结果注意到平坦的岩板上几乎全都是网眼般的龟裂。

爱丽丝轻轻挥动缰绳，让坐骑飞龙尽可能靠近大门。

接著畏畏缩缩地伸出左手，迅速在空中划出史提西亚的印记，轻轻敲了一下门的表面。

浮现出来的紫色「窗户」上，记述著东大门所拥有的天命最大值与现在值。

左边的数字，即使在至今为止所看见的多数天命数值中也是最大等级──高达三百万以上。但右边则浮现不到其千分之一的2985这样的数字。当爱丽丝哑然凝视著这些数字时，现在值又在她眼前减少成2984。

手掌冒汗的爱丽丝，开始计算数字再次减少的时间。然后准备藉此来推算大概还有多久天命才会完全消失。

「……怎么会……」

无法相信自己脑袋里得到的答案，爱丽丝低声这么说道。

「……五天……仅剩下短短五天而已吗…………？」

三百年来一直严守岗位分隔两个世界的大门，将在短短五天后崩坏──真的可能发生这种事情吗？

脑袋里头依序闪过赛鲁卡光辉的笑容、卡利塔老人满是皱纹的脸庞，以及父亲卡斯弗特严肃的面容。短短几天之前，才击退袭击他们的哥布林，并用冰块封印住洞窟而已。而且她也相信，这样子卢利特村就能保持好一阵子的和平。

如果五天后大门崩坏，黑暗大军蜂拥而至时，守备军无法抵挡下攻势，那么渴望鲜血的怪物就会如洪水般淹没人界。而这巨大的洪水也将立刻到达北部边境，吞没卢利特这座小村庄。

「一定……得想办法才行……」

爱丽丝像呓语般这么呢喃，接著在下意识中拉紧缰绳。雨缘离开快要崩坏的大门，缓缓拍动翅膀往上升去。

到达高三百梅尔的大门最上部，再次让龙停留在空中。

门后方和人界这一边同样是切开岩壁的山谷笔直地往前延伸。但远方那一大片空间没有蓝色天空与绿色草原，而是血红色天空与黑暗领域那像撒满灰烬的荒野。

想把视线从不祥光景移开的爱丽丝，忽然间眯起眼睛。

因为她在黑色大地的稍远处，发现了隐隐约约晃动的光芒。

于是爱丽丝让雨缘飞到更高处，然后定眼凝视。结果光线不止一道。它们不规则地密集在一起，看起来似乎一直延伸到远方。

那些全是营火。

原来那是一片野营地。暗之军队的前锋，已经大举来到距离人界如此近的地方，等待著大门崩坏，前往人界的道路开通的时刻。

「还有……五天……」

爱丽丝以沙哑的声音，再度呢喃了一遍。

接著就让飞龙回过头。感觉继续看著这无数的营火，自己就会被焦躁感吞没，单骑直接冲进敌方阵地。

如果对方只是哥布林或者半兽人的步兵，那么爱丽丝就算这么做，也有自信可以杀个一两百只并平安无事地回来。但敌营里如果有食人鬼的弓兵，或者暗黑术师的大部队，那么事情就不会这么简单了。

就算整合骑士可以一骑当千，但终究只有一个人。被从剑技与术式无法伤及的后方集中使用远距离攻击的话也不可能毫发无伤，就算只是轻伤，持续累积下去终究会把天命全部耗尽。这正是骑士长贝尔库利长年来担心的，整合骑士圑──甚至可以说人界守护者的最大弱点。

推展将战力集中在一小群人身上的最高司祭亚多米尼史特蕾达早已过世，私藏在中央圣堂的大量武器防具也已经紧急分发给守备军。但剩下来的时间实在太少了。如果兵力有一万，准备期间有一年的话──

以叹息将无能为力的思绪甩掉后，爱丽丝对雨缘做出下降指示。

守备队的野营地中央，空出了一块宽广的草地。看见旁边并排著许多巨大的帐篷，就知道那里正是飞龙的起降场。

画著弧形往下降的雨缘，四肢的钩爪刚碰到绿色草皮，就把长长的脖子朝向帐篷，从喉咙发出「咕噜噜」的撒娇般声音。

立刻有稍微低沉一些的声音做出回应。那应该是它的哥哥泷刳吧。爱丽丝在龙还没完全停下来时就抱著桐人跳到草地上，把它双脚上面沉重的行李卸下来。雨缘立刻就踩著沉重脚步往帐篷冲去，和从厚布底下探出头来的哥哥互相摩擦著脖子。

忍不住露出微笑的爱丽丝，注意到后面有脚步声靠近，于是急忙绷起脸来。她整理朴素原色裙子的裙襬，把被风吹乱的头发理到背后。

在她回头之前，就有一道熟悉的男性声音响彻在起降场当中。

「师父！吾师爱丽丝大人！我就知道您一定会回来！」

一边在草地上发出「滋沙沙」的滑行声一边绕到自己前面的，正是十天前左右刚和他喝完诀别酒的整合骑士艾尔多利耶‧辛赛西斯‧萨提汪。虽然是在野营当中，他那波浪状淡蓝紫色头发以及白银甲胄依然是一尘不染。

「……看起来很有精神嘛。」

不对爱丽丝冷冷的回答感到气馁，像是极为感动而想说些什么的艾尔多利耶，嘴唇忽然间冻住了。

因为他注意到爱丽丝用左臂撑住的黑发年轻人。

单边脸颊有些抽筋，大大把头往后仰的年轻骑士，像是难以置信般发出低沉的吼声：

「为什么……把他带过来？」

爱丽丝也拚命挺直身子来回答他：

「这是当然，我发誓要保护他了。」

「但……但是……只要一开战，我们整合骑士就得一直在最前线作战。和敌兵短兵相接时该怎么办？总不可能背著他吧。」

「有必要的话我会这么做。」

像要让桐人无法自行站立的瘦削身体远离艾尔多利耶的视线一般，爱丽丝的右脚稍微往后退。但不知不觉间已经有休息中的士兵与下级整合骑士们三三两两地聚集在起降场附近，以怀疑的眼神看著并排站在一起的爱丽丝与桐人。

笼罩在如同波浪声的骚动声下，艾尔多利耶提出了尖锐的反驳：

「师父，万万不可啊！虽然有所僭越，但请容我一言。带著那种没用的重物战斗，不要说战斗力会减半了，甚至连师父的玉体都可能遭受危险！爱丽丝大人在即将到来的战争里……」

他暂停了一下，才又用金碧辉煌的银制护手指著周围的士兵说：

「……应该负起率领他们战斗的任务！这样的您，怎么可以让自己处于无法发挥全部力量的情况下呢！」

他说的一点都没错。但爱丽丝也无法轻易认同他的看法。于是只能用力咬紧牙根──思考著如何说明对自己来说两边──为了人类而战与保护桐人一样重要。

但爱丽丝同时也对弟子热烈的辩舌产生某种惊讶的感觉。

跟过去在中央圣堂接受爱丽丝指导剑术时比起来，他已经有明显的变化。当时的艾尔多利耶就像十分崇拜爱丽丝般，不论她说什么都不曾加以反驳。

这个世界的人类，全都被充满谜团的「外界之神」施加了右眼的封印，因此绝对无法违抗法律以及居上位者的命令。就爱丽丝所知，主动成功打破封印的就只有自己，以及目前已经丧生的蓝蔷薇剑士尤吉欧而已。就连拥有与神明同等权限的最高司祭亚多米尼史特蕾达与贤者卡迪娜尔，最后都没能反抗这个封印。

艾尔多利耶目前应该也受到那个封印的影响才对。但是他──虽然不是明确反抗爱丽丝所说的话──不过已经不像过去那样盲从了。他是以自己的意志来思考，并阐述自己的意见。

让他产生这种变化的人，恐怕就是桐人还有尤吉欧吧。

虽然只有极短暂的时间，但和除了是这个世界最大的反叛者之外，同时也是高强剑士的两个人接触，已经让艾尔多利耶的灵魂产生强烈的动摇。

现在想起来，生活在卢利特村的妹妹赛鲁卡，也经常对村子依然守旧的规则以及有力人士的不懂变通表示不满。还有像爱丽丝准备把桐人与尤吉欧从北圣托利亚修剑学院带走时，从里面跑出来的两个女学生。那两名年纪还小的少女，原本不可能做出叫住整合骑士的行为。

另外，当然──爱丽丝本身也一样。

从开始和桐人交手，到快要从中央圣堂外壁摔落的瞬间为止，她都完全没有怀疑过世界的构成、教会的支配以及最高司祭的神性。

但在不得已之下合作脱离危机，接受停战约定，然后开始攀爬外壁的时间里，爱丽丝却不停被桐人的话、剑以及漆黑的眼睛剧烈地刺激──最后终于让自己突破了右眼的封印……

没错，桐人简直就像对这充满虚伪和平的世界挥落的铁锤一样。他以潜藏在灵魂里的力量摇晃、撼动世界，最后把名为公理教会的，钉在人界中心的巨大老旧钉子整个敲坏。但代价就是他的好友尤吉欧与导师卡迪娜尔的性命，以及丧失了自己的心灵……

爱丽丝用力抱紧以左臂支撑住的纤细身躯，然后由正面回看著艾尔多利耶的双眸。

实在很想对他说，你能够有现在的样子，全是因为和这个人战斗过的缘故。但对方当然无法理解。对整合骑士团来说，桐人现在仍只是难以饶恕的反叛者。

面对无言持续站在那里的爱丽丝，艾尔多利耶露出承受著钝重疼痛般的表情，准备继续对她搭话。

就在这个时候。周围人墙的一处，简直像被透明巨人的手拨开一样分散开来。

从人墙深处传出来的，是让爱丽丝怀念到快要流下眼泪，同时也让她紧张到感觉疼痛的声音。

「哎呀，火气别这么大嘛，艾尔多利耶。」

把视线从迅速挺起背杆的年轻骑士身上移开后，爱丽丝缓缓转过身体，看向声音的主人。来者穿著带有东域风味的宽松前襟式服装，较低的位置上绑著一条宽大的腰带。左腰上则随意插著一把形式简单的长剑。穿在两脚上的是奇特的木制鞋子。

和周围的骑士与士兵比起来算是相当轻便的服装。但从他身经百炼的身体上散发出来的压力却比任何铠甲都要厚重。

用力摩擦了一下类似和服般淡蓝色而且剪得相当短的头发后，声音的主人嘴角就露出无声的笑容。

「嗨，大小姐。你看起来比我想的还有精神，这样我就放心了。脸是不是变圆了？」

「……叔叔，好久不见了。」

爱丽丝拚命不让自己渗出眼泪，然后向世界上最古老且最强的剑士──整合骑士长贝尔库利‧辛赛西斯‧汪行了个礼。

他是爱丽丝以整合骑士身份度过的六年里，唯一信任且尊为师父，甚至是父亲的人物。而且同时也是这个世界上唯一一个──除了桐人之外──爱丽丝确定自己绝对无法取胜的剑士。

所以现在不能让他看见自己哭泣的脸庞。

如果贝尔库利不准自己把桐人安置在这里的话，自己也得遵从他的命令。当然，就算是他的命令也无法强迫目前的爱丽丝。但在众人面前反抗他的话，骑士团与守备军的秩序将会产生动摇。在仅仅五天后就要面临决战的状况下，贝尔库利的指挥权绝对不容许受到一丝伤害。

像是看透这时爱丽丝内心的纠葛般，依然带著粗犷与温柔微笑的贝尔库利缓缓走了过来。

他先凝视著爱丽丝的眼睛，然后用力点了点头。

又瞥了一眼背后还想说些什么的艾尔多利耶来制止他，接著骑士长的视线就移到爱丽丝抱在怀里的桐人身上。

他收紧嘴角，双眸里带著如同蓝白色火焰的锐利光芒。

贝尔库利「嘶」一声长长吸了口气。爱丽丝立刻感觉周围开始出现刺痛肌肤的冷空气。

「……叔叔……」

爱丽丝挤出细微的声音。

贝尔库利正在凝聚剑气。准备使出比只传授给整合骑士的「心念技」……以心灵的力量来移动物体的「心念之臂」更加强力的秘术「心念之剑」。

那是把凝聚的意志力贯注在剑上后使出的招式。有时那透明的剑刃甚至能弹飞拥有实体的敌刃。骑士长所拥有的神器「时穿剑」，其甚至能够斩断未来的武装完全支配术，正是因为他拥有压倒性的意志力才能成立的术式。

这也就是说──贝尔库利打算砍了桐人吗？

如果他真的想藉由武力把这个问题一刀两断，那么自己绝对无法接受这样的做法。到了那个时候，自己就得拔剑保护桐人了。

在骑士长强烈至极的剑气压迫下，周围的士兵、艾尔多利耶，甚至连帐篷里的许多飞龙都静了下来。被严重压缩到难以呼吸的空气当中，爱丽丝拚命想移动右手手指。

但是在爱丽丝触碰到爱剑的剑柄之前，贝尔库利的嘴微微动了一下，接著响起类似意念的声音。

──别担心，大小姐。

「…………！」

当爱丽丝屏住呼吸的瞬间──

贝尔库利全身没有任何动静，但是双眼却放射出令人感到恐惧的强烈光芒。

同一时间，爱丽丝怀中的桐人也开始剧烈震动起来。

「锵！」一声清脆的声音响起，贝尔库利和桐人之间的空间爆出银色闪光。

──刚才那是？

爱丽丝因为过于惊讶而稍微喘了口气，但这时候贝尔库利已经发出浑厚的笑声，让人觉得刚才的剑气彷佛是幻觉。

「叔……叔叔……？」

面对茫然如此呢喃的爱丽丝，骑士长像是刚练习完剑术般，以指尖搔著下巴说道：

「大小姐，你看到刚才的情形了吗？」

「是……是的。虽然只有一瞬间……但是的确有交锋的光芒……？」

「嗯。我对那个年轻人施放的心念之剑，不对，应该说心念短剑。只要砍中的话，脸颊应该会被切下一层皮。」

「砍中……的话？这也就是说……」

「没错，年轻人用自己的心念挡了下来。」

爱丽丝忍不住看向左边怀里桐人的脸。

但她的期待马上就落空了。微微张开的黑色眼睛里，只映照出空虚的黑暗。脸上还是没有任何表情。

──但是，他的身体刚才确实震动了一下。

爱丽丝一边以右手抚摸桐人的头发，一边把视线移向贝尔库利。骑士长虽然摇著头，但还是以确切的声音做出这样的判断：

「年轻人的心似乎已经不在这里……但也还没死。听好了，大小姐，刚才这个小伙子想保护的不是自己而是你。所以我认为他总有一天会回来。大概是大小姐真正需要他的时候吧。」

爱丽丝必须以比刚才更加倍的努力，才能抑制再次要溃堤的眼泪。

──没错，他一定会回来。

──因为桐人……桐人他才是世界最强的剑士。因为挥动两把剑的他，甚至击毙了那个半神半人的司祭。

──我不会说……是为了我。拜托你为了生活在这个世界的众多人民回来吧……

爱丽丝终于忍俊不住，以双臂用力抱住桐人的身体。这时背后又响起骑士长带著告诫之意的声音：

「所以就是这样了，艾尔多利耶。别在意这些小事情，让她照顾一个年轻人也不会怎么样啦。」

「但……但是……」

鼓起足以令人称赞的勇气后，最新的整合骑士艾尔多利耶就向最古老的骑士贝尔库利阐述自己的意见：

「如果还有一点战力也就算了，但这种状态实在……而且就算恢复意识，一个学生的剑又能有什么帮助……」

「喂喂！」

贝尔库利的声音除了沉稳的笑意之外，同时也含有名刀般的锐利度。

「你忘记了吗？这小鬼的伙伴可是打败了我这个整合骑士长贝尔库利‧辛赛西斯‧汪呢。」

一瞬间周围就陷入寂静当中。

「那个叫作尤吉欧的小伙子……真的非常强。甚至让我使出时穿剑的完全支配术，而且还打败了我。就像打败你、迪索尔巴德和法那提欧时一样。」

这下子似乎连艾尔多利耶也无话可说了。其实这也是理所当然的反应，因为不但是整合骑士团，就连门外的黑暗领域里，也不存在一对一能赢过贝尔库利的剑士──公理教会的所有人都是如此深信不疑。

但这在某种意义上来说也是相当危险的发言。

骑士长贝尔库利是以最强者的威严打造出这只急就章的守备军。但是却宣示有尤吉欧这名打败自己的剑士存在──而且承认桐人的实力和尤吉欧相同，也就代表……

当爱丽丝想到这里而准备抬起头来时──

贝尔库利瞬间抬头望向天空。

「叔……叔……？」

骑士长这时以出乎意料之外的发言回答了爱丽丝的问题：

「遥远的地方一瞬间出现巨大的剑气然后消失……看来是我认识的某个人死亡了……」

4

构成暗之国十侯会议的十名诸侯，不论是性向、人格以及隐藏在心里的野心都完全不同，但他们还是拥有唯一一个共通点。

那就是比任何人都要了解「有实力者能支配一切」这一条唯一的法律。

应该说，就是因为幼年时期这条法律就深深刻划在灵魂里，才会持续不断努力──时时提醒要锻炼自己，排除防碍者──也才能在这个以暴制暴的世界里爬到几乎是顶端的位置。

因此……

和夏斯达并列的九名诸侯，在端坐于最右侧的暗黑骑士长随著撕裂棉帛般的吼叫声对皇帝拔剑时，内心都没有感到太大的惊讶。

反而有许多人都出现「在这时候发难吗？真是大胆」这样的理解。就连在这三百年当中让语言能力，也就是智能退化的半兽人族与食人鬼族的首领，野兽般的眼睛都因为认为如此就能知道皇帝这家伙的实力如何而发出锐利的目光。和夏斯达同样是求道者而对他抱持敬意的年轻拳斗士首领，内心甚至还帮他加油，想著「既然拔剑那就砍了他吧」。

在这些人当中，有两个人在数秒钟前已经预测到这样的事态。

一个是暗黑术师公会总长蒂伊‧艾‧耶尔。和夏斯达水火不容的她，早就计划过绑架暗黑将军的爱人，所以从以前就知道莉琵雅的长相。

所以在看见莉琵雅被冰冻的首级后反而是惊愕的感觉比较强烈。蒂伊当场预测到夏斯达可能会因为过于愤怒而拔剑，一瞬间思考起那个时候自己应该怎么办。

虽然考虑过从夏斯达背后施放术式来给皇帝做人情，但蒂伊最后还是选择冷眼旁观。因为夏斯达败给皇帝也无所谓，万一获胜的话，到时候正可以烧灼这名应该受到重伤的仇敌，然后自己掌握暗之国的霸权。蒂伊在内心露出了狡诈的笑容，为了隐藏自己的兴奋而轻轻舔了一下嘴唇。

这时候，还有另一名察觉暗黑将军叛意的人──

他则是立刻有所行动。

＊＊＊

夏斯达心里只有「杀」这个字，用力地挥动自己的爱刀。

如果只计算贯注在剑招里的心念强度，这一击确实已经超过过去与整合骑士长挥剑相抵的时刻。他强烈的愤怒与怨叹，立刻就引起了原本需要漫长术式的完全支配现象。

夏斯达手里的长刀「朦霞」是做为VRMMO程式套件的Underworld在两百年前左右自动生成的神器级物体。拥有「水」属性的它，呼应了夏斯达极强烈杀意的刀身，就在内含必杀威力的情况下失去实体，转变成雾状的影子。

朦霞在完全支配状态下的特性是，能够完全省略附属在所有剑上的「以剑刃切断或者贯穿对象物来给予伤害」的攻击过程。只要碰到延伸出去的长长带状雾，天命数值就会在那个时间点受到斩击属性的伤害。也就是说，除了回避之外的防御都起不了作用。

皇帝贝库达，也就是加百列‧米勒在夏斯达拔刀时也抽出自己腰间的长剑，准备弹开敌人的一击。

如果事态按照这样推移下去，夏斯达的雾刃应该已经穿越加百列的剑砍中他的身体，然后把浓缩的杀意全部灌进去了。

但就在夏斯达神速跨步，准备使出必杀斩击的前刻──

他的动作就像被冻住了一样停了下来。

不知道什么时候，暗黑将军身上铠甲的左侧腹，已经有一根飞针深深刺在厚重装甲上仅有的一丝接缝里。

在后方缓缓站起来的，是用深灰色斗篷包裹住全身，宛如幽灵般瘦削的男人。

他是暗杀者公会头领夫萨。这名十侯当中存在感最为薄弱，总是躲在阴暗处，在会议中也几乎没有发过言的人，在恐怕是人生当中受到最大瞩目的情况下徐徐走到前方。

夫萨之所以能事先察觉到夏斯达的反叛，完全是因为他是诸侯当中最胆小且神经质的人。

暗杀者公会是由一群无力者聚集起来的组织。这是天生在体力、术力、财力以及其他所有力量都不突出，但是又拒绝成为奴隶遭受严酷奴役的人们，为了钻研连在黑暗领域都被嫌恶的「毒技」所创造出来的集团。

地底世界里的一部分昆虫、蛇类以及植物等毒性物体本来就是被当成负荷实验的一环而配置在各地。因此其效果都有界限，大概都只到居民运用必须的智慧就能够充分回复的程度。反过来说，就是无法从它获得对抗术式或者剑技的力量。

但是组织暗杀者公会的这些人，编纂出RATH工作人员没想到的「浓缩」技法，花了漫长的岁月来生产、强化毒液。位于城堡外城市贫民窟地下深处的公会总本部里，有著上百年来持续熬煮毒果汁液的大锅子，以及从各地收集来的毒蛇在里面自相残杀的大壶。

但是终于完成的「致死毒」却造成了公会内暗杀横行这样的悲剧。和剑法与术式不同，迟效性的毒很难特定出加害者的身份。

当然，管束公会的首领不极其胆小的话根本就无法存活下去。他们甚至可以感应到潜伏在周围人群的视线，不对，应该说气息里的一丝丝杀意。

对夫萨来说，夏斯达看见莉琵雅首级的瞬间所散发出来的杀气，甚至比鲜血的味道还要清晰。

而且对夫萨来说，暗黑将军夏斯达正是他在这个世上最为憎恨的对象。

之前就不知道已经拟定并废弃过多少暗杀计划。甚至已经有能够杀掉他的自信。但只要被发现死因是中毒，任何人都会知道这是暗杀者公会干的好事。夏斯达断气的一个小时后，强力无比的暗黑骑士圑就会冲进本部，把所有公会成员杀光吧。正面战斗的话根本没有胜算。

但现在这个瞬间……

自己拥有光明正大将磨利的毒针刺进可憎敌人身体里的理由。因为在皇帝御前拔剑的瞬间，夏斯达就不再是暗黑将军或者十候，只是一个反叛者罢了。

夫萨从斗篷的怀里抽出来投掷的，是暗杀者公会首领代代继承下来的暗器。从「鲁贝利鲁毒钢」这种本身就会分泌麻痹毒的危险矿物削下来的极细毒针内部是中空状态，里面可以存积各种毒液。

而注入到里面的，同样是这个公会技术结晶的致死毒。是把五万只名为「血腐蛭」的稀有水蛭放在一起磨碎，再经过数次过滤浓缩所得到的一小滴毒液。由于让水蛭在饲育下繁殖的尝试全都失败了，所以要制造这一滴毒液可以说必须费尽千辛万苦。

虽然夫萨不可能知道，但生存在Underworld原野的动物，是系统基于面积大小的规定值所生成出来，除了被指定为家畜个体的牛羊之外，全都不可能经由人工繁殖。

也就是说，夫萨施放的毒针，不论是素材还是内部的毒液，都是将暗杀者公会所有力量浓缩在一点后所完成的产物。它同时也是数百年来遭受虐待的弱小者们怨念的结晶。

＊＊＊

夏斯达因为把意志力全都放在挥出去的刀上，所以完全没有意识到毒针深深插进肉里所带来的痛楚。

但是准备朝著皇座高高跃起的瞬间，就感觉到整个身体像是变成铅块一样沉重，也因此而瞪大了眼晴。

当双脚失去力量，单膝瞬时跪地后，才重新发现到左侧腹已经插著异物。

──是毒吗？

瞬间浮现这样的想法，在像冰一样冷的左手麻痹前就迅速拔出毒针。注意到称不上是武器的极细毒针上带著鲜艳绿色光泽的夏斯达，立刻了解这就是恐怖的鲁贝利鲁毒钢，而他也马上想咏唱对抗的术式。

但寒气以惊人的速度由左侧腹浸透到全身，甚至来到嘴部。还没咏唱完「System call」的起句，舌头就失去感觉，连咬紧牙根都办不到了。

这时左手也完全麻痹，从拳头里滑落的毐针掉到黑色大理石上发出细微的声响。

最后举起刀的右臂也开始缓缓落下，完全支配状态也同时解除，由灰色雾气变回实体的爱刀刀尖碰到了地板。

和挥刀攻击皇帝前一样，以低头左膝跪地的姿势僵在现场的夏斯达，视界里无声滑进一件黑色斗篷。

──是夫萨。

──没想到被这个男人摆了一道。

「……竟然败在这种不值一晒的小东西上……你一定这么想吧，毕库斯鲁？」

如磨擦般的咻咻声从头上降下，让夏斯达绷紧了唯一还稍微能动的眼角。

──你这家伙，没资格这样叫我的……

「你一定想说，我没资格这样叫你的名字吧？但是呢，我可不是第一次以毕库斯鲁来称呼你喔。」

暗杀者缓缓弯下膝盖，曲身来到同样高度的脸庞进入夏斯达视界当中。但整个往下拉的兜帽遮住光线，除了尖下巴之外全都隐藏在黑暗当中。

接著下巴像震动般动了起来，传出更加沙哑的声音：

「在幼年学校里……经常被你欺负的小孩子们，长相你应该都不记得了吧。同时也忘记有一个小孩因为太过屈辱而跳进河渠，永久从学校里消失这件事。」

──搞什么。这男人到底在说些什么？竟然提到幼年学校？

出生在普通骑士家庭的夏斯达，到了能握住木剑的年纪，就在个人意愿完全不受重视的情况下被送到骑士团附属的幼年学校里。之后就只有为了存活下去而不断努力修行的记忆了。在所有选拔考试中经常获得胜利，被任命为骑士团的军官，最后更得到师父前任骑士长赏识──可以说是根本没有空回顾过去的，宛如激流一般的半生。

三十多年前并排在一起挥动木剑的小孩长相，自己当然不可能记住。

「……但我没有一天忘记你。我漂流到地底的暗渠后，被暗杀者公会捞了起来。之后以奴隶的身份在那里被人使唤的漫长岁月里，也没有一天忘记过你……我不停累积知识，开发出许多新的毒药，最后终于爬上公会首领的位子。代价就是失去了许多东西……但全都是为了向你复仇啊，毕库斯鲁。」

扭曲的声音中断的同时，兜帽也微微倾斜，夫萨的真面目显露在夏斯达面前。

即使如此，夏斯达的记忆还是没有恢复。不对，应该说就算夏斯达完整地记住过去所有同学的长相，现在也想不起他的名字了。可能是受到毒液的影响吧，夫萨的脸溶化得非常严重，目前长相已经沦落成比半兽人还要恐怖了。

可以看见再次被深深拉下来的兜帽深处，只有一双眼睛放射出强烈的光芒。

「注入你体内的，是为了杀掉你而开发出来，耗费几乎令人发疯的时间一滴一滴储存起来的毒液。根据实验，一个小时就能杀掉天命超过三万的大型地龙。依照你的体力与天命总量，恐怕只剩下两三分钟的生命吧。我要把寄放在你这里的怨恨与屈辱一次全讨回来……」

──怨恨吗？

夏斯达把视线从夫萨的眼睛移开，凝视著掉在黑色大理石地板上的毒针。

──我在愤怒与怨恨的驱使下想要斩杀皇帝。夫萨也在这只针上贯注同样的力量想杀了我。所以我的招式才会停下来。「杀之心念」赢不了「义之心念」。以前和那个男人……整合骑士长贝尔库利交手过一个回合所掌握到的剑诀，我竟然在最后这个紧要关头忘记了……

夏斯达已经无法保持单膝跪地的姿势，从左肩垮倒到地板上。

逐渐朦胧的视界中央，毒针的后方──

可以看见放在银盘上的冰块立方体。

＊＊＊

夫萨，过去名为费留司‧萨尔加迪斯的复仇者，为了尽情享受期待以久的欢喜瞬间而死命睁开双眼。

恣意攫取无数荣耀的暗黑将军夏斯达，现在就躺在自己脚边。上了年纪却还相当有弹性的皮肤变成土黄色，锐利的目光逐渐消失，也只剩下断断续续的气息，这模样实在太狼狈了。可以说是丑陋又丢脸至极的临死时刻。

而夏斯达之死，同时也证明了毒杀技术优于剑术与暗黑术。使用了鲁贝利鲁毒钢加上血腐蛭的新型复合毒，只要轻轻刺一下就能让敌人陷入无法拔剑与咏唱的状态，让其迅速丧命。

坐在皇座上的皇帝贝库达，应该也会因为刚才那一幕而注意到暗杀者公会的价值吧。当新型毒的大量生产完成时，就不必再看骑士与术师的脸色了。届时也能取回原本的姓名，以全新支配者的身份回到舍弃自己的萨尔加迪斯家……

身体因为喜悦而震动的夫萨，完全没有注意到夏斯达滚落在他视界之外的刀，刀身已经再次开始幻化成雾气了。

＊＊＊

──莉琵雅。

夏斯达在天命快要归零之际，在心中呼喊著唯一一名心爱的女性。

莉琵雅之所以决心刺杀皇帝，一定是因为听了夏斯达所说的新时代到来后，想要帮忙实现这个愿望的缘故。她深信只要三百年来的战争结束，新的法律与秩序照亮这个黑暗之国，那么只能饿死或者成为奴隶的孤儿们也能够获得过著幸福生活的权利。

──夫萨啊。

──你说在幼年学校被我痛扁了？还说受不了屈辱而投身于河渠？

──但你这家伙至少还有过机会。拥有让你进入学校就读的双亲，足以填饱肚子的三餐以及温暖的被窝与挡风遮雨的屋顶。你知道这个世界有多少出生时就没有最低限度的权利，只能被当成垃圾对待并消失的年幼生命吗？

──莉琵雅赌上性命想要纠正这样的世界。自己不能因为你这家伙个人无谓的私怨，就辜负了她这样的心念────

「……不会让你阻止我！」

夏斯达应该完全麻痹的嘴里迸出巨大怒吼声的同时，就有灰色龙卷风般的物体以暗黑骑士的右手为中心高高回旋升起。

这正是连整合骑士都只有一小部分人能使用的，神器的记忆解放现象。夏斯达强力无比的心念，开始改写积蓄、演算全Underworld情报的Main Visualizer。

灰色龙卷风显现出没有任何属性的纯粹破坏力，分解所有触碰到它的物体。无法躲避就被龙卷风吞没的夫萨，厚重的斗篷发出「噗咻」的清脆声音后就像烟一样四处飞散。

从里面出现的瘦削中年男子，像要掩盖溶化崩塌的脸一样抬起双臂。下一刻，他的手臂就化成无数肉片迸散──接著全身化为浓密的血雾啪唰一声飞上天空。

＊＊＊

暗黑术师蒂伊‧艾‧耶尔在濒死的暗黑将军身体涌出奇妙龙卷风的瞬间，随即因为非常不妙的预感而用力往后飞退。同时用双手生成风素，全速往后方飞行。

预感在看见右脚被急速扩大的龙卷风碰到，立刻就从膝盖以下灰飞烟灭后转变成最大等级的惊愕。

蒂伊不论是在入浴还是睡眠中都持续以数十种防御术保护全身。因此术式就不用说了，她铁壁般的防御甚至可以反弹投掷的暗器、剑、毒等几乎是所有种类的攻击。

当然，如果是拥有同等级优先度的十侯所发出的全力攻击，确实有可能贯通障壁而伤害到她的肌肤。但绝对不可能出现障壁宛如不存在一般，光是碰到肉体就被削除的现象。

不论脑袋如何用力地否定，右脚还是迅速遭到速度比她全力退后更快的死亡龙卷风削除。虽然蒂伊这种程度的术者，就算被砍掉一只手或脚都能轻易用治愈术复原，但那也得还活著才行。

「咿……啊啊……！」

蒂伊嘴里终于忍不住迸出尖锐的悲鸣。

但她的声音却被同时尖叫的两只哥布林首领给盖过去。

排在蒂伊左边的山地哥布林首领哈卡西与平地哥布林首领酷毕力，全都死命动著短腿急速想从龙卷风旁边逃开。但是根本无法回避龙卷风连蒂伊的全速飞行都能追上的膨胀。

「咕嘎──！」

哈卡西的脚随著难听的叫声打滑，然后跌倒在地。他用尽力量伸出的左手，像是老虎钳一样抓住了酷毕力的脚踝。

「咿呀啊啊啊！放手──！快放…………」

啪唰。

两只哥布林族的支配者随即化成血雾。

噗滋。

蒂伊的整只右脚都消失得无影无踪。

在美貌因为恐惧与绝望而扭曲的暗黑术师公会总长的眼前，──龙卷风的膨胀奇迹似的停住了。

这时已经看不见夏斯达倒在中央的身体。以那附近为中心屹立不摇的倒圆锥形暴风，这时候直径与高度已经扩大到二十梅尔。距离较远的其他六名诸侯迅速退到西侧墙边，排在大厅南侧的各阵营干部们也在千钧一发之际保住了性命。

虽然意识极为混乱，但蒂伊的思考力在朦胧之中理解了龙卷风停止膨胀的理由。

那是为了要保护十几名上级暗黑骑士。也就是说，那道龙卷风是由夏斯达的意志所创造出来的东西。

就像要证实蒂伊的想法一样，龙卷风的上半部渐渐开始变形。

最后出现的是，由半透明雾气所形成的男人上半身。

虽然变得异常巨大，但那很明显就是暗黑将军夏斯达的分身。

插图015

＊＊＊

皇帝贝库达，也就是加百列‧米勒，这时候终于稍微有一点类似惊讶的感情，抬头看著似乎随时要压过来般屹立在那里的龙卷风巨人。

将女暗杀者的首级暴露在众人面前后，看见这一幕的瞬间左端的骑士将会拔剑，这些事情全在加百列意料当中。而且暗杀者公会的首领以毒液还是什么的让想斩杀加百列的男人麻痹，也没有让他感到太意外。

虽然无法达成一击击毙反叛者，藉此在剩下来的九名个体内心深植下忠诚心的企图，但自发性保护皇帝的行动确实值得称赞。加百列一边这么想，一边看著事情的发展──

但倒地的背叛个体身上忽然涌起灰色龙卷风，被它包围的暗杀者公会首领与两只哥布林将军一瞬间就被消灭，这样的情况让加百列不禁感到茫然。

每一名将军个体的能力值应该都差不多才对。这样的话，就算互相对战也不可能一瞬间分出胜负，而是会演变成不停互相削减HP并自行回复的长期战。

但想不到短短几秒钟就有三个个体被消灭。这个Underworld里，还有自己与克里达尚未得知的某种逻辑存在吗──

当他想到这里时。龙卷风巨人已经张开嘴，发出足以撼动天地的吼叫声。

装饰皇座之间墙壁的大部分窗户玻璃都因为承受不住压力往外侧飞散。

巨人握住足有汽缸本体那么大的右拳──

随著轰然巨响朝加百列挥落。

加百列判断用剑抵挡根本没有意义，而且也没有站起来躲避的时间了。视界的右端，可以看见担任副官的瓦沙克敏捷飞退的模样，这时加百列只是静静坐在皇座上等待灰色巨拳。

＊＊＊

夏斯达临死前心念所产生的死亡龙卷风，算是已经超越Underworld系统的现象。

它不是以数值上的攻击力来夺取夫萨与哥布林的天命，造成他们死亡的结果，而是藉由直接在他们的LightCube里灌进「死亡的印象」来破坏摇光，再由这个结果反推回来，让肉体完全消灭。

因此朝向加百列的攻击，也没有对皇帝贝库达的庞大天命造成任何影响。

但是，由夏斯达摇光生成的杀意，经由量子通讯线路到达加百列肉体躺在其中的STL里面──

由暗黑将军夏斯达这名Underworld屈指可数的剑士所凝聚起来的必杀意志，直接击中加百列‧米勒的摇光中枢，也就是所谓的「自我」。

这个时候，夏斯达的主观意识已经和自己挥出的全力一击同化，感觉自己正冲进皇帝贝库达的身体内部。

夏斯达原本肉体的天命明显已经用尽，于是他了解到这将是生涯的最后一击。

无法实现和整合骑士长贝尔库利再次交手的约定实在令人遗憾。但那个男人应该能够理解，暗黑将军希望什么，又为了什么背叛皇帝。

除了暗杀者公会头领夫萨之外，也同时击毙了诸侯中最好战的两只哥布林首领。虽然让暗黑术师公会总长蒂伊逃走算是相当可惜，但那样的重伤应该无法即时再生才对。再加上暗黑骑士团长以及皇帝贝库达的死亡，剩下来的诸侯一定会对与人界的决战感到犹豫。

至少要让他们和同样失去支配者的人界居民订定暂时的休战协定。如果可以因此不再用剑而是用言语来交流，让彼此之间产生某种共识的话……

希望接下来──莉琵雅渴望的和平世界能够到来。

和心念同化的夏斯达，贯穿皇帝贝库达的额头，冲进存在于内侧的灵魂中枢。

只要破坏这个地方，就算是喑黑神，应该也会和夫萨等人一样，存在整个遭到抹灭吧。

随著无声的吼叫，夏斯达的意识与皇帝的灵魂产生冲突──

紧接著，他尝到生涯最后的惊愕。

什么都没有。

如光云般的灵魂中枢，应该存在意识精髓的地方，竟然只有一片浓密的黑暗。

怎么会这样。就连与世隔绝的夫萨，灵魂都因为对生命的强烈执著而发出闪闪光芒啊。

夏斯达的心念就这样被皇帝内部一望无际的黑暗给吞噬。

只见他的身形逐渐消失、蒸发。

──这家伙，这个男人……

──不了解生命是什么吗？

不懂生命、灵魂以及爱情光辉的人，所以才会如此饥渴地求取他人的灵魂。

不论多强力的心念，只要是带有杀意的剑就无法击毙这个男人。

因为这个男人的灵魂虽然活著，却早已跟死亡没有两样。

得把这件事传达给某个将来注定跟这个怪物一战的人知道才行。

要传达出去──告诉某个人……

但这时夏斯达的意识已经被无限的深渊整个覆盖过去了。

…………太遗憾了…………

…………莉琵雅…………

最后爆出这样的思考后，暗黑将军毕库斯鲁‧乌鲁‧夏斯达的灵魂就完全消灭了。

＊＊＊

加百列‧米勒在极为强烈的灵魂光芒贯穿自己的瞬间，随即产生了盖过恐惧的欢喜感。

暗黑骑士的灵魂，充满著比两天前吸进的女暗杀者灵魂还要浓密的感情。像是对那个女人的爱，加上难以理解的类似范围更加广泛的慈爱感情，还有把这些当成动力来源的强烈杀意。

爱与憎恨，这个世上还存在比这更美味的东西吗？

这时候的加百列，可以说完全没有意识到自己的生命陷入危机当中。即使看见三个个体在暗黑骑士的攻击下变成肉片飞散，加百列依然把吸收骑士的灵魂看得比自身安全还要重要。

如果加百列畏惧骑士的攻击而希望自己能够生存的话，夏斯达的杀意就会经由STL破坏加百列的生存本能，然后产生连锁效应把他的摇光全部轰飞。

但是加百列‧米勒是个不知生命为何物的人类。对他来说，包含自身在内的所有生命，都不过是跟幼时大量杀戮的昆虫同样的自动机械而已。加百列唯一的愿望就是，查明成为机械动力源的灵魂，也就是充满谜团的光辉云层究竟有何秘密。

因此由夏斯达摇光所产生的破坏讯号，就只能平白通过加百列摇光里面的一整片虚无，没有发生任何冲突就消失了。

虽然加百列完全不清楚这样的道理，但他还是一边咀嚼骑士的灵魂，一边把两件事留在记忆里面。

首先是这个世界里，除了一般VRMMO里游戏藉由武器与咒文的攻击外，也存在另一种攻击方法。

而那种攻击方法似乎对自己没有效果。

之后得要克里达调查刚才那种现象的原理才行。加百列一面这么想，一面缓缓从皇座上站起来。

＊＊＊

存活下来的六名诸侯──暗黑术师公会总长蒂伊‧艾‧耶尔、拳斗士首领伊斯卡恩、商工公会头领连基尔、巨人族首领西古罗西古、半兽人首领利鲁匹林、食人鬼首领弗鲁咕鲁──他们有的靠在墙壁上，有的瘫坐在地上，有的正一边止著重伤的血，一边茫然抬头看著皇帝贝库达的模样。

所有人心中只存在恐惧这种感情。

暗黑将军夏斯达令人吓破胆的超级攻击──一瞬间把三名将军变成血雾，同时也把诸侯中被认为相当有实力的蒂伊右脚削除的一击，皇帝竟然挺身从正面承受下来，而且没有受到任何伤害。

有实力者支配一切。

皇帝贝库达拥有六名诸侯，以及他们背后一百名以上的军官加起也远远不及的力量已经是一目了然的事实。

如同微小的波浪往外扩散般，所有人都深深低下头，对皇帝表达恭顺之意。就连敬爱的骑士长遭到杀害的暗黑骑士团也不例外。

这时皇帝的声音流畅地响彻整座大厅：

「……失去将军的军队，马上由下一个位阶的人员接手指挥权。一个小时后，按照原定计划开始进军。」

皇帝没有因为出现反叛者而发怒或是责备众人。这样的事实让将军们更加感到恐惧。好不容易让右脚止血的蒂伊，高高举起连指尖都伸直的右手并大叫：

「皇帝陛下，万岁！」

隔了短暂的几秒钟后──

「万岁」的呼喊变成足以撼动整座黑曜岩城的轰然巨响，而且还重复了许多次。

5

爱丽丝环视了一下配给给自己的野营用帐篷，接著轻轻叹了口气。

简易床铺相当干净整齐，铺在地板上的羊皮是全新品，空气当中也只有太阳的味道。虽然这些都相当令人高兴，但这很明显不是为了爱丽丝而急遽空出来的帐篷。也就是说，骑士长贝尔库利为了爱丽丝加入阵营时能使用，事先就多设置了一个骑士用帐篷。

虽然也可以把这种行为当成是受到信赖的证明，但了解骑士长为人的话，就会觉得自己的想法与行动已经完全被对方看透了。

不对──应该不至于完全被看透。因为就连骑士长，似乎也没有预想到爱丽丝会带著桐人一起过来。所以这里只准备了一张简易床铺。

爱丽丝碰著桐人的背部，诱导他坐到床铺上。下一个瞬间，年轻人立刻从喉咙发出细微的声音并准备伸出左手。

「好好好，等一下喔。」

跑到放在入口旁边的行李袋前面，爱丽丝随即从里头抽出黑白两把长剑。接著回到床边，把它们放在桐人大腿上。结果他用左臂抱住剑后就安静下来。

爱丽丝坐到他身旁，一边脱掉靴子一边思考著。

虽然对艾尔多利耶说出有必要的话会背著桐人战斗这样的大话，但实际上确实有点困难。如果只有变瘦的桐人也就算了，再背上夜空之剑与蓝蔷薇之剑的话，行动就会因为重量而受到限制。

虽然也曾想过一直把桐人放在雨缘的鞍上，但既然敌人也有骑乘飞龙的暗黑骑士，那就会出现空中战的情况吧。这么一来，还是希望尽量减轻负荷的重量。

虽然不愿这么做，但战斗中请辎重部队的某个人帮忙照顾桐人似乎是最合理的选择。但问题是能不能这么顺利找到可以信赖的人。

旧识的众整合骑士一定全都会到最前线，而自己又不认识任何一般平民士兵。但事到如今也实在不想拜托艾尔多利耶帮忙寻找合适的人选。

「桐人……」

爱丽丝由正面窥看年轻人的脸，然后以双手轻轻包覆他的脸颊。

自己完全没有打算把桐人当成包袱。如果能够恢复意识，他一定会成为比任何人都要可靠的人界守护者。之所以会像这样带他一起来到前线，完全是因为觉得说不定能在这里发现让他恢复意识的可能性。

骑士长贝尔库利表示，桐人弹开了他施放的「心念之剑」。还说那是为了要保护爱丽丝。

真的可以相信他的发言吗？

首次在修剑学院相遇时，是逮捕者与罪人。在中央圣堂八十楼再次相遇时，是处刑人与反叛者。甚至在最上层诉说最后一句话的瞬间，两人之间无论再怎么美化，也只是暂时休战中的关系。

──从那场战争之后你就一直失去意识了，却还想从叔叔的剑气下保护我吗？

──你……到底是怎么看我的呢？

这个问题碰到桐人黯淡的眼睛后，反弹回爱丽丝自己身上。

那自己又认为和这个年轻人是什么样的关系呢？

如果要用一句话来形容在中央圣堂时的桐人，那么最适合的就是「面目可憎」了吧。敢对著整合骑士爱丽丝‧辛赛西斯‧萨提骂那么多次「笨蛋」的人，这名年轻人可以说是空前绝后了吧。

但是在最后一战时，桐人面对最高司祭亚多米尼史特蕾达时的背影──

看见那名剑士黑色外套下襬不停飘动，左右手各握著一把剑的背部，爱丽丝的心就产生强烈的震动。心中的想法就只有「竟然有如此坚强，但又哀切到让人觉得心痛的模样」。

这样的感情变成淡淡的刺痛感，到现在都还残留在爱丽丝内心深处。

但因为害怕知道疼痛的理由，所以一直遮盖著自己的心。

──因为我是被创造出来的存在。只不过是持续占据爱丽丝‧滋贝鲁库身体的战斗用人偶罢了。自己根本没有资格，去拥有战意之外的感情。

但是，说不定……

就是因为我压抑自己的心，你才会听不见我的声音？

如果我施放所有的「心念」，你是不是就会有所回应呢？

爱丽丝吸进满满的空气并屏住呼吸。

桐人被自己双手包覆的脸颊相当冰冷。不对，是自己的手掌太过火热。

爱丽丝轻轻把他的脸颊拉过来，从至近距离看著他的黑色眼睛。那简直就像黑夜一样阴暗，但又感觉遥远彼方可以看见一些闪烁的小星星。

爱丽丝一边凝视著那些星星，一边缓缓把脸凑过去──

忽然传出铃铛的清脆声音，让爱丽丝的身体弹了起来。

虽然急忙环视了一下帐篷内部，但当然没有任何人在。最后终于发现是挂在帐篷入口处的摇铃被人拉动了。

有客人来访。爱丽丝没来由地干咳了一声，整理好头发后迅速横越帐篷。

反正一定是艾尔多利耶又来抱怨了吧。这次一定得斩钉截铁地告诉他，无论说什么自己都不打算把桐人赶走。

帐篷的出入口有两层帷幕，把头伸出内侧的薄布后，爱丽丝就用左手一口气把外侧的厚重毛皮拉开。

而她正要张开的嘴唇也在这时候停了下来。

站在她眼前的不是整合骑士，甚至连一般兵都称不上。这让爱丽丝忍不住凝视著访客。

「那……那个……」

娇小的来访者怯生生地以细微的声音这么说道，双手同时递出盖著锅盖的锅子。

「骑士大人，帮……帮您送晚餐来了。」

「……这样啊。」

爱丽丝稍微瞄了一下天空。不知不觉间，傍晚的红霞确实已经退到西方的天空去了。

「谢谢……辛苦了。」

慰劳对方并把锅子接过来的爱丽丝，再次上下打量著对方的模样。

那是一名还很年轻，看起来只有十五六岁的少女。

长度大概到肩膀下方的头发是漂亮的红色。大大的眼睛同样是类似红叶的颜色，另外白皙的肌肤与高挺的鼻梁都显示出她有北方帝国的血统。

身上穿著轻装铠甲的女孩似乎也是守备军的一员，但铠甲下方的灰色上衣与裙子好像是哪所学校的制服。

竟然连这样的小孩都得上战场……如此想著的爱丽丝准备咬紧嘴唇时，忽然又觉得奇怪而眨了眨眼睛。

少女的长相有种似曾相识的感觉。但以前都在中央圣堂生活的爱丽丝，几乎没有和一般平民接触过。

这时候，躲在红发少女身后的第二名少女才畏畏缩缩地现出身影。

「那……那个……这是面包和飮料。」

听见有著接近黑色的深茶色头发与深蓝色眼睛的少女发出微弱声音后，忍不住露出微笑的爱丽丝跟著也接下她递过来的篮子。

「不用这么害怕，我又不会把你们抓来吃了。」

一说到这里，爱丽丝的记忆才苏醒过来。

她曾经听过这极为紧张的声音。这两个人就是那个时候的──

「你……你们不会是……北圣托利亚修剑学院的学生吧……？」

一问之下，两名少女才像是放下心头的大石般，让紧绷到极点的脸颊瞬间放松下来。但马上又端正姿势，靠拢穿著靴子的脚跟并报上姓名：

「是……是的！我……我是隶属人界守备军补给部队的缇洁‧休特里涅初等练士！」

「同……同一部队的罗妮耶‧阿拉贝鲁初等练士！」

爱丽丝反射性地回礼，在内心呢喃了一句「果然没错」。

准备把桐人和尤吉欧从学院带走时，请求允许跟他们道别的就是这两位女孩。

就算守备军的人手再怎么不足，应该还不至于会征召学生入伍才对。这样的话，她们应该是自愿从军，由熟悉的央都来到这危险的战地了？这两名稚气未脱的少女，为什么愿意做这种牺牲呢……

右手拿著锅子，左手提著篮子的爱丽丝认真地盯著两个人看，结果自称罗妮耶的深茶色头发少女就再次躲到名为缇洁的红发少女背后。缇洁虽然也缩起身体，但最后还是带著做出必死决心的表情开口表示：

「那……那个……骑……骑士大人……我……我知道这么问真的非常失礼……」

极为严谨的语气再次让爱丽丝忍不住露出苦笑，但她还是尽可能把苦笑变成温柔的笑容插话道：

「听我说，你们不需要这么拘谨。因为在这座野营地里，我也不过是一名为了守护人界而来的剑士而已。直接叫我爱丽丝就可以了，缇洁小姐……还有罗妮耶小姐。」

结果缇洁以及从她背后轻轻冒出头来的罗妮耶同时露出哑然的表情。

「……怎……怎么了？」

「没……没有……只是……跟以前在修剑学院见到您时的印象完全不一样了……」

「是吗……」

觉得奇怪的爱丽丝歪了歪头。自己虽然不是很清楚，但是住在卢利特村的这半年里，真的有什么样的改变吗？虽然骑士长说出脸变圆了这种毫无凭据的感想就是了。

现在回想起来，确实可能因为赛鲁卡所做的料理实在太美味而忍不住吃太多了……但应该不至于胖到连外表都改变吧……

差点要绷紧的脸颊再次露出笑容后，爱丽丝又继续表示：

「那……你们有事找我吗？」

「啊……是……是的。」

紧张的神情稍为变淡了一点的缇洁，一瞬间抿紧嘴唇后才又说道：

「那个……我们听说骑士大……爱丽丝大人在骑乘飞龙来到营地时，身边还带著一名黑发的年轻男性……然后，我们就想那位男性是不是我们认识的人……」

「啊，嗯……对喔，说得也是。」

爱丽丝这时才终于了解少女的来意，于是点著头说：

「你们在学院的时候就跟桐人很熟了……」

爱丽丝开口这么说的瞬间，两名少女的脸就像花蕾绽放般充满光芒。罗妮耶的蓝色眼睛里甚至渗出些许眼泪。

「果然是……桐人学长……」

罗妮耶以细微声音这么呢喃著，缇洁则是握住她的手以充满期待的声音大叫：

「那么……尤吉欧学长也在喽……！」

一听到这个名字，爱丽丝就猛然吸了一口气。

她们两个人完全不知道，半年前在中央圣堂展开的那场激斗以及最后的结果。根本不可能知道。因为关于最高司祭死去的消息，就只有整合骑士知道而已。

两个人往上看著说不出话来的爱丽丝，接著露出感到不可思议的表情。爱丽丝交互凝视著缇洁与罗妮耶的眼睛后，缓缓伏下了视线。

事到如今，不可能隐瞒她们了。

而且她们两个人有知道一切的权利。因为她们应该是为了再次与桐人以及尤吉欧见面，才会志愿参加守备军，来到这个营地……

爱丽丝下定决心后开口说道：

「对你们来说……可能会觉得很难过。但我相信身为桐人以及尤吉欧学妹的你们，一定可以承受这个事实。」

说完她往后退一步，抬起毛皮帷幕，催促两人进入帐篷。

让爱丽丝有点失望的是，即使缇洁与罗妮耶走进桐人视界当中，他依然没有任何反应。爱丽丝一边压抑失望的感觉，一边站在帐篷的墙边看著这悲壮的光景。

罗妮耶到坐在床上的桐人面前跪了下来，以娇小的双手包裹住年轻人的左手，脸上不停流下泪水。

但更让人心痛的是，整个人瘫坐在皮革地毯上，持续凝视著眼前那把蓝蔷薇之剑的缇洁。在传达尤吉欧的死讯时，她变得跟纸一样苍由的脸上没有任何表情。只是默默地往下看著从中折断的剑身。

爱丽丝本身几乎没有机会直接和名为尤吉欧的年轻人交谈。

交谈的机会大概就是逮捕他到中央圣堂并丢进地下监牢之前，以及在高塔的第八十层迎战他们时，再来就只有与亚多米尼史特蕾达进行最终决战时曾与他并肩作战了。

虽然对尤吉欧不仅只从骑士长贝尔库利手里赢得胜利，还把的身体化成剑来破坏巨剑魔像，最后更砍飞最高司祭一条手臂的意志力感到衷心佩服，但关于他的记忆大多是根据赛鲁卡叙述给自己听的回忆。

赛鲁卡表示，尤吉欧是相当温顺又思绪缜密的少年，似乎经常被青梅竹马的爱丽丝‧滋贝鲁库拖著去进行各种冒险。如果是这样的个性，那么和桐人一定是一对相当好的伙伴。

桐人和尤吉欧在修剑学院里一定也到处闯祸。就像爱丽丝本身一样，缇洁与罗妮耶就是被这样的两个人给吸引，并受到很大的影响。

──所以，拜托你们，一定要承受住这样的伤悲。桐人和尤吉欧他们是为了守护非常重要的事物而战，并因此而受伤、失去意识与生命。

爱丽丝一边在内心这么对两人说道，一边持续注视著她们。

在人界生活的人民，如果受到过于强大的恐惧与悲伤这种精神上的冲击，就有可能因为无法承受而罹患精神疾病。就像前阵子遭受黑暗军队袭击的卢利特村，似乎也出现了几名身体没有受伤，但是却卧病在床的村民。

缇洁她一定深爱著尤吉欧吧。

对如此年轻的她来说，接受心爱的人死去这种巨大的冲击绝对不是一件简单的事。

爱丽丝的视线前方，瘫坐在地上的缇洁右手忽然动了一下，然后开始一点一点靠近蓝蔷薇之剑。

爱丽丝带著一丝紧张看著她这种模样。蓝蔷薇之剑虽然从中折断，但依然是最高等级的神器。虽然不认为缇洁能够使用它，但过于深刻的绝望与悲伤有时候会引发预料不到的力量。没有办法预测到会发生什么事。

缇洁以僵硬动作伸直的手指，终于碰到淡蓝色剑身。她没有触碰剑刃，而是轻轻划过被磨得相当光滑的侧面。

就在这个瞬间──

折断的剑身发出微弱但是确实的蓝色光芒，推开从采光孔透进来的红色夕阳。

同一时间，缇洁全身震动了一下。

似乎感觉到什么的罗妮耶也回过头看向自己的朋友。紧绷的空气当中，缇洁的睫毛上缓缓出现透明水滴并无声滴落。

「……刚才…………」

粉红色嘴唇里发出细微呢喃声。

「……我听见了……尤吉欧学长的声音……他跟我说不要哭……他一直都在这里……」

眼泪潸潸不绝地滴落，缇洁最后终于把脸趴在剑上，像个小孩子一样发出剧烈的呜咽声。罗妮耶也把脸靠在桐人膝盖上嚎啕大哭。

虽然眼头因为这令人悲痛，但是又相当清纯的情景而发热，但是──

爱丽丝还是在脑袋角落想著「真的有这种事吗」。

她虽然没有听见尤吉欧的声音，但是确实看到剑一瞬间发亮。这样的话，缇洁听见的发言也不见得一定是幻听。

蓝蔷薇之剑上……真的残留著类似尤吉欧灵魂的物体吗？

插图016

爱丽丝在发动武装完全支配术时，也有一种金木樨之剑与自己的意识一体化的感觉。但尤吉欧则是实际让自己的身体与蓝蔷薇之剑融合，而且在这样的情况下受到致命伤。

所以说不定真的可能出现持有者的意识残留在半截剑上的情形。

但是刚才缇洁说尤吉欧呼唤了她。如果真是如此，那么残留在剑上的就不只是没有灵魂的残响，而是真正的意识──或者是心念吧。

是少女因为爱慕之情而产生的幻听吗？还是说……？

真是令人著急。如果是桐人，一定能帮忙找出这个现象的秘密吧。从这个世界的外侧，一大群神秘神明所居住的地方掉落到这里来的他一定没问题才对。

在不停旋转的思考水平面上，忽然浮现如小泡沫般的一句话并啪叽一声爆裂开来。

世界尽头的祭坛。

据说这个不怎么出名的地方，设置有通往世界外侧的门。

如果能到那里，所有的谜团就能够一瞬间获得解答吗？桐人失去的意识也可以恢复吗？但是据说祭坛是位于离开东大门后的遥远南方。也就是在暗之种族支配的黑暗领域遥远边境。

想到那个地方去，就不只是得防御在大门外布阵的敌人大军，甚至要突破包围才行。不对，就算突破敌阵，自己也不可能放下大门的防卫不管直接往南方前进。身为被赋予过大力量的整合骑士，爱丽丝必须负起守卫人界的责任。

还是干脆把自己当成诱饵来吸引所有敌军，一面让他们远离大门一面朝著祭坛迈进。但是对黑暗领域的人民来说，侵略人界是数百年来的悲愿，应该没有比这个愿望更有魅力的事情了……

果然就算要前往世界尽头的祭坛，也得先把黑暗军队完全歼灭才行。

最后得到的结论，让爱丽丝忍不住闭上眼睛。

虽然浮现歼灭敌人这种相当浩大的想法，但现状就连要抵御敌人的先锋都很困难吧。但为了守护缇洁、罗妮耶还有桐人，自己还是得这么做。

静静呼出一口气后，爱丽丝中止持续了数秒的默思，走到两名哭哭啼啼的少女身边。

6

索鲁斯的残照在很久之前就已经消失在西边的远方，但东大门后面看起来呈细长状的黑暗领域天空，却还一直固执地残留著不祥的血色。

简直就像要遮蔽这样的光景一般，人界守备军野营地中央──白天被当成飞龙起降场的草地上围起了一片纯白布幕。在布幕前方高处不停飘动的公理教会旗帜下，聚集了三十名左右的整合骑士与守备军队长，只见他们都一脸严肃地看著彼此的脸。

爱丽丝发现他们没有分成骑士与士兵后，随即因为有些惊讶而停下脚步。

整合骑士穿著光辉的银制铠甲，队长们则是穿戴华丽度虽然不及但优先度也相当高的钢铁铠甲，一群人同样单手拿著装有西拉鲁水的玻璃杯热烈地进行议论。竖起耳朵倾听的话，就能发现那些拐弯抹角的敬语已经完全被省略了。

「大小姐，以急就章的集团来说，已经颇像一回事了吧。」

身旁忽然传出低沉的声音，让爱丽丝急忙往该处看去。

把双手扠在东方风味服饰怀里的骑士长贝尔库利，以动作制止了准备敬礼的爱丽丝，接著说道：

「这支守备军里，已经省略所有的繁文缛节了。幸好禁忌目录里没有『一般民众跟骑士说话前，一定得仔细向对方问安』这样的条款。」

「这……这样啊……这确实是一件好事，但先不说这个了……」

爱丽丝再次把视线移回军议会场上。

「──其他整合骑士到哪里去了？目前看来，那边只有十名左右的骑士。」

「很遗憾，那些几乎就是全部了。」

「咦……咦咦？」

用手掌遮住忍不住提高的声音后，爱丽丝以有些苦涩的表情往上看著骑士长。

「怎么可能……骑士团包含我在内应该有三十一名成员才对。」

人数正如最新的整合骑士艾尔多利耶被赋予的萨提汪这个神圣语名所表示。

贝尔库利在参杂叹息声当中回答了一句「是没错啦」后，随即又压低声音表示：

「大小姐也知道吧。元老长裘迪鲁金对记忆产生问题的骑士施予『再调整』的处置。他死去的时候，在元老院再调整中的七名骑士仍未觉醒。」

「…………！」

爱丽丝忍不住瞪大眼睛。贝尔库利把视线从出现这种反应的爱丽丝身上移开，以更加苦涩的声音继续说道：

「知道再调整用术式的只有裘迪鲁金与最高司祭两个人。他们已经死亡的现在，就必须花时间解析术式才能让七名骑士觉醒，但我们现在根本没有这种时间。只有一名尚未进行再调整，单纯处于冻结睡眠中的骑士，我好不容易才让那家伙醒过来，只不过……」

感觉骑士长的语气有些吞吞吐吐，于是爱丽丝开口询问：

「那一个人是？」

「……『无声』的谢达。」

「…………！」

虽然是没有直接见过面，只听过几则轶事的名字，但爱丽丝还是不由得屏住了呼吸。因为那些轶事的内容都相当恐怖。

但是贝尔库利却像是表示这些事以后再说般干咳了一声，接著继续说明目前的战力：

「……总而言之，目前觉醒的整合骑士共有二十四人。当中有四个人留下来管理中央圣堂和央都，四个人被我派去负责尽头山脉的戒备。剩下来的十六人……就是能够用在这条绝对防卫线的上限人数了。当然也已经把我和大小姐算进去喽。」

「十六个人……吗？」

爱丽丝差点就加上「只有」几个字，但还是咬起嘴唇忍住了。

而且仔细确认这些人长相的话，就能发现目前在议场的十四个人里，有半数以上是没有神器──也就是无法使用武装完全支配术的下级骑士。光是以剑斩杀敌人的话，他们当然都是能够独自砍杀一两百只哥布林的勇士，但无法期待拥有改变全体战况的爆发力。

这时贝尔库利改变语气对沉默下来的爱丽丝说：

「对了，说到要找谁照顾那名年轻人嘛……我看干脆由我拜托后卫部队……」

「啊……不用了，不必担心这件事。」

爱丽丝一面对骑士长生疏的贴心举动露出微笑一面回答：

「刚好有在修剑学院担任他随侍剑士的志愿兵……我已经请她们开战后照顾桐人了。」

「哦，那真是太好了……那怎么样啊？黑发小子和过去曾有过交流的人接触后，有没有出现什么反应？」

爱丽丝脸上的笑容消失，无言地摇了摇头。

贝尔库利短短叹了口气，低声说了句「这样啊」。

「……这件事情我只跟你说。老实说，我觉得那名年轻人可能是决定接下来这场战役胜败的关键人物……」

爱丽丝惊讶地抬头看著骑士长的脸。

「就算有大小姐和伙伴的帮忙，他还是完成了以剑击毙元老长与最高司祭这种超乎想像的壮举。纯粹比较心念强度的话，可能连我都不及他。」

「……怎么可能有这种……」

事到如今也不可能再对桐人的实力感到怀疑，但骑士长贝尔库利的心念是花了两百年以上的时间锻炼出来的成果。相对的桐人只是尚未成年的学生。爱丽丝反而觉得，如果是剑技与体术就算了，只有心念这一个项目绝对比不上骑士长才符合常识。

但贝尔库利却以充满自信的动作否定了爱丽丝的发言。

「之前以心念互击时，我确实感觉到了。那个小伙子拥有跟我相同，甚至是超越我的实战经验。」

「实战……？这是什么意思……？」

「就是字面上的意思，也就是攸关生死的战斗啊。」

这才真的让人想回答「怎么可能呢」。

生活在人界的居民，全都受到禁忌目录与帝国基本法的保护，或者可以说束缚。就算可以用木剑比试好了，一般人从出生到老死大概都不会经历过以真正的剑进行某一方可能耗尽天命的实战。

唯一的例外就是整合骑士，因为他们会跟想侵略尽头山脉的哥布林以及暗黑骑士进行实战。但那在漫长的任期里最多也只有一两次，而且整合骑士方的战力占压倒性优势，老实说很难称为攸关生死的战斗。

考虑到这些事情后，就能确定人界里实战经验最丰富的，就是从骑士团规模比现在小很多的时代就一直和黑暗军队战斗的贝尔库利了。实际上，在他刚成为整合骑士时──虽然很难相信──似乎曾经惨败于当时的暗黑骑士手上，好不容易才拖著一条命逃了回来。

桐人他实战的次数会赢过这样的贝尔库利？

如果真的有这种事，那也不会是在这个世界的经验。

应该是在他真正的故乡，也就是「外面的世界」。但那里同时也是真正创造地底世界的诸神明所居住的世界才对。但在那边还有实战？到底是跟什么人赌上生死呢……？

不知道究竟该如何想下去的爱丽丝，稍微犹豫了一下才下定决心。

既然这样，就只能对贝尔库利说出一切了。像是外面世界的存在──以及世界尽头的祭坛存在通往那里的大门等事情。

「……叔叔……其实我和最高司祭战斗的时候……」

当爱丽丝选择用词遣字把话说到这里时──

骑士长后方突然传来尖锐的声音。

「阁下，时间到了。」

吓了一跳的爱丽丝看向声音的主人。

一名全身包裹在暗夜当中依然发出醒目淡紫色光芒的铠甲与头盔当中，左腰挂著白银细剑的整合骑士站在那里。

一看见完全遮住脸孔，带著猛禽翅膀形状的头盔，爱丽丝心中浮现的感慨──以极端一点的说法来表现的话，大概就是「呜恶」这两个字了。

对爱丽丝来说，来者恐怕是这个世界里和她最合不来的人物。那个人正是副骑士长，整合骑士排名第二的法那提欧‧辛赛西斯‧滋。

爱丽丝很努力地不把内心的感情显露在脸上，接著反射性将右拳贴在左胸，并把左手按在剑柄上行了骑士礼。

相对的法那提欧也喀锵一声震响铠甲做出同样的动作。但是与双脚稍微张开并且直立的爱丽丝不同，法那提欧是把重心放在右脚并且垂下左肩，摆出看起来比较柔弱的姿势。

实在没办法接受这个人的这种个性……爱丽丝一边放下手一边在心中这么自言自语。

虽然自认为已经以铠甲、头盔以及带著威严的语调来掩饰，但在同性的眼里看起来，法那提欧的动作就已经像一朵巨大的花朵，不断散发出难以掩盖的强烈女人味。而这正是孩提时期就被带到中央圣堂的爱丽丝终究无法学会的「技能」。

副骑士长法那提欧在中央圣堂第五十层与桐人、尤吉欧战斗，被桐人的武装完全支配术直接击中后身负濒死的重伤。爱丽丝从在现场的下级骑士口里听说过，桐人当时却对著费尽千辛万苦才打倒的法那提欧施加治愈术，甚至还用不可思议的术式把她传送到某个地方去。

虽然觉得这确实很像桐人会做的事，但内心还是觉得不以为然。

说起来法那提欧明明一心喜欢著骑士长贝尔库利，但是却还把对自己著迷的四名下级骑士编列为自己的直属部下。难道不觉得永远只能憧憬，一辈子都无法获得青睐的他们很可怜吗？至少应该时常摘下头盔来让他们看看脸庞吧。

当爱丽丝浮现这种稍微带著一点私怨的想法时，法那提欧就用双手抓住头盔的侧面，这样的举动让爱丽丝著实吓了一跳。

被解开的挂钩发出「啪叽、啪叽」的声音，接著淡紫色头盔就随手被往上拉起来。整个扩散开来的艳丽黑发，在营火照耀下发出丝绢般的光芒。

在中央圣堂时，只有在前往大浴场途中偶然遇见法那提欧才能看到她的真面目。记忆当中，这应该是副骑士长第一次在众人环视的环境下脱下头盔。

爱丽丝凝视跟以前比起来似乎变得柔和一些的美貌，并且理解到产生变化的理由。原来是圆润的嘴唇上涂抹了淡淡的口红。想尽办法要隐藏女性身份的她竟然会化妆──？

法那提欧对著茫然站在现场的爱丽丝露出平稳的微笑。

「好久不见喽，爱丽丝。看见你平安无事真令人高兴呢。」

「…………」

「喽」？「呢」？

说不出话的时间又加了三秒钟左右，接著爱丽丝才终于能够向对方打招呼：

「好……好久不见了，副长。」

「叫我法那提欧就可以了。对了，爱丽丝，我刚才听说……你把那个黑发的小子也一起带来了？」

以轻松态度说出的发言，让爱丽丝把惊讶丢到一边去，取而代之的是高涨的警戒心。虽然法那提欧的伤是由桐人与贤者卡迪娜尔治愈，但她不见得知道这个事实。她对打倒自己的桐人有所怨恨与憎恶也不是什么不可思议的事情。

「是……是的。」

爱丽丝简短地回答，而副骑士长则是带著嫣然微笑点了点头。

「这样啊。那军议之后，可不可以让我跟他见个面？」

「……法拉提欧阁下为什么要见他？」

「别露出那种表情嘛。事到如今，我也不会想杀害那个年轻人了。」

压抑下微笑中一丝苦涩的感情，法那提欧耸著肩并这么说道。

「我只不过是想跟他道谢，听说是那个小伙子帮受到致命伤的我治疗。」

「……你已经知道了吗？但我想没有必要跟桐人道谢。因为我听说帮副长疗伤的，是名为卡迪娜尔的前任最高司祭。很遗憾的是……那位司祭大人已经在半年前的战争中亡故了。」

稍微放松肩膀力道的爱丽丝一这么说，法那提欧便迅速把视线朝向天空并点了点头。

「嗯……我还有一些朦胧的记忆。我还是第一次接受那么温暖且强大的治愈术。但是，把我送到那位大人身边的就是桐人，而且……还有另一件事也想向他道谢。」

「另一件事……？」

「没错──就是和我战斗并且把我打倒。」

……她果然想找桐人算帐吗？

面对往后退了半步的爱丽丝，法那提欧一脸严肃地摇了摇头。

「这是我的真心话。因为那个小伙子，是我以整合骑士的身份活了这么久以来，第一个知道我是女性依然全力跟我战斗的男人。」

「啥……？你这是……什么意思……」

「我以前也像你这样，没有戴上头盔就以素颜直接战斗。但某一天我就注意到了。不论是担任模拟战对手的男骑士，甚至是进行生死决斗中的暗黑骑士，剑招都有些畏缩。因为我是女人这样的理由而留手，对我来说是比战败倒地还要大的屈辱。」

但这也是没办法的事吧。几乎没有什么男人可以抗拒由素颜的法那提欧所散发出来的女人味。

自从在卢利特村近郊过生活后才首次知道，人界大部分地方，女性都几乎不会从事握剑的天职。例外大概就只有贵族或者领主的子女，至于一般平民女性原则上只有结婚生子并在家做家事的生活方式可以选择。

如果这种守旧的观念和禁忌目录一样禁锢男人们的心，那就实在是太讽刺了。就是男人应该保护女人这样的先入为主观念，让他们的剑招在法那提欧的花容月貌面前变得迟钝吧。既然生活在黑暗领域的暗黑骑士也会娶妻生子，那就不可能是例外。至于外表完全不同的哥布林和半兽人等亚人族，则可能和人类有不同的价值观。

但同为女骑士的爱丽丝，之前从来没有注意到男骑士的退缩还是留手之类的事情。因为不论对方是留手还是尽了全力，她都有自己绝对比较强的自信。

──这样的愤怒，不就是你拘泥于自己是女性这件事的最佳证明吗？

当爱丽丝这么想的同时，法那提欧也低声说出完全相同的话：

「──我用这个头盔遮住面容与声音，为了不让敌人近身而学会连续剑技。但这正是因为我拘泥于自己性别的缘故。那个小伙子瞬间看穿这一点，然后全力跟我过招。在和他的战斗里，我使尽浑身解数的剑技与术式并被他打败。当托卡迪娜尔大人的福捡回一条命的我恢复意识时，心中无聊的坚持就消失了……总而言之，只要我拥有让对方无法留手的实力就可以了。那个小伙子让我注意到这单纯的事实，而且还让我活下来，想向他道谢也不是什么不可思议的事情吧？」

以认真的表情说到这里，法那提欧脸上忽然露出恶作剧的微笑。

「除此之外……也有点生气啦。小伙子竟然对著素颜的我说完全感觉不到一丝女人味。所以就想试试看，帮小伙子做各种服务的话，他会不会就醒过来了。」

「什么……」

在说什么蠢话啊。

如果桐人真的这样就醒过来，那么自己至今为止所做的努力不就太空虚了吗？而且桐人也确实有让人无法坚决否认这种可能性的部分。

毫不隐瞒眉间险恶的气息，爱丽丝以尖锐的声音反击：

「很谢谢阁下的心意，但他目前在帐篷里休息。所以就由我来帮忙传达法那提欧阁下的谢意吧。」

「哎呀……」

副骑长也轻轻动了一下眼角。

「要和小伙子见面还得要你许可吗？在中央圣堂的时候，你要求跟值勤中的骑士长阁下见面时，我不记得曾经因为私情而拒绝过你啊。」

「我才想说，我跟叔叔见面根本不需要法那提欧阁下的许可吧。说起来呢，如果想被男性骑士彻底打败，那么拜托叔叔不就可以了吗？」

「哎呀，骑士长阁下不能算数喔。他是世界最强的剑士，对所有人留手本来就是理所当然。他甚至还卖人情给暗黑将军呢。」

「哦，是这样吗？和我练剑时，叔叔总是浑身大汗而且相当认真喔。」

「……阁下！她说的是真的吗？」

「说起来都是叔叔太宠这个人了……！」

爱丽丝与法那提欧同时看向旁边。

但骑士长已经不在那里了。

几分钟前贝尔库利才站在那里的地方，现在只有一团枯掉的野草沙沙地滚动著。

从下午六点开始的军事会议，就受到担任司仪的副骑士长法那提欧‧辛赛西斯‧滋，以及新加入阵营的整合骑士爱丽丝‧辛赛西斯‧萨提所发出的剑气所影响，只能在极为紧绷的空气下进行。

结束简短自我介绍的爱丽丝，随即迅速坐到准备在最前排的椅子上。

「……爱丽丝大人。」

坐在旁边的艾尔多利耶畏畏缩缩地递过装有西拉鲁水的杯子，爱丽丝一把抓过去后，一口气把冰凉又酸甜的液体喝光。长长呼出一口气的她，好不容易才成功转换心情。

插图017

话说回来──

拥有神器的上级整合骑士真的太少了。知道名字与长相的，大概就只有骑士长「时穿剑」贝尔库利、「天穿剑」法那提欧、「霜鳞鞭」艾尔多利耶，以及「炽焰弓」迪索尔巴德。

再加上拥有「无声」异名的谢达‧辛赛西斯‧推鲁弗，以及非常年轻的少年骑士连利‧辛赛西斯‧推尼赛门似乎也有神器，但几乎是首次见面的缘故，根本不知道他会使用什么样的剑技。总之以上的几名再加上「金木樨」爱丽丝共七个人，就是上级骑士的总数了。

剩下来的九个人里，包含直属于法那提欧的「四旋剑」在内，全都是没有神器的下级骑士。而且也可以看见极会闹事，连贝尔库利都拿她们没办法的见习少女骑士里涅尔‧辛赛西斯‧推尼耶特以及费赛尔‧辛赛西斯‧推尼奈的身影。现在是乖乖地坐在角落的椅子上，但谁也不敢保证她们到时候会不会上战场。

总而言之，这仅有的十六个人，就是整合骑士团能投入这条绝对防卫线的所有战力了。

另一方面，共有三十名左右的人界守备军部队长参加会议。虽然士气不低，但一眼就能看出剑技的实力和整合骑士之间有很大的差距。爱丽丝等上级骑士就不用说了，就连下级骑士也可以连续跟他们三十个人比赛并轻松获胜吧……

「──这四个月来，我们检讨过各种作战……」

法那提欧不知不觉间就开始说起话来，而她的声音也把爱丽丝的意识拉回到现实。

「结果得到的结论是，以目前的战力要抵抗敌军的总攻击可以说相当困难。一旦被包围，我军就完全没有胜算了。」

以天穿剑细长的剑鞘代替指示棒，法那提欧在设置于军议场深处的地图上某一点敲了一下。

「正如各位所见，尽头山脉的这一侧只有往四方扩散的十基洛尔草原与岩石地。要是被推进到这里，再来就只能被五万敌军包围并且歼灭。因此必须在这条连接东大门的，宽一百梅尔长一千梅尔的峡谷里战到最后。我们将在此处布下纵深阵，单纯等待敌军的突击并削弱对方实力。这就是作战的基本方针。到这里有什么问题吗？」

立刻举起手的人是艾尔多利耶。晃著淡紫色头发站起来的年轻人，以压抑住平常那种绅士模样的声音问道：

「如果敌军是只由哥布林与半兽人组成的步兵，那么不管来五万还是十万都不成问题。但那些家伙也知道这一点。所以敌军里面也有装备了强大弓箭的食人鬼军团，以及更加危险的暗黑术师团。要怎么应付这些应该会从步兵背后发动的远距离攻击呢？」

「应对方式将会是危险的赌注……」

法那提欧暂停了一下，视线稍微瞄了爱丽丝一眼。爱丽丝不由得挺起背杆，听她继续说明下去。

「……即使是白天，阳光也照不到峡谷底部，所以地面是寸草不生。也就表示，空间神圣力相当稀薄。只要我们在开战前把神圣力全部用尽，敌军就没办法以强力的术式发动攻击。」

法那提欧大胆的意见，让众骑上与部队长产生一阵骚动。

「当然，我方也将无法使用术式。但我们原本就只有一百名左右的神圣术师。要是以术式互击的话，神圣力的消费量应该是对方远超过我们才对。」

法那提欧说的确实没错。但是──她的作战有两个问题点。

这时取代说不出话来的艾尔多利耶要求允许发言的，正是弓箭手迪索尔巴德。穿著红铜色铠甲的资深骑士，以沉稳的声音发问：

「原来如此，副长阁下说的应该没错。但神圣术不只能用来攻击。要是神圣力枯竭的话，不就连伤者的天命都无法回复了吗？」

「所以我才说是一场赌注。我们已经把积蓄在中央圣堂宝物库里所有的高级触媒与治疗药全搬到这座野营地来了。限定术式只使用治愈术，再加上药品辅助的话，光靠触媒就可以撑两天……不对，是三天。」

听见她这么说，随即响起超越刚才那一次的惊讶声。说到中央圣堂的宝库，大家都知道警卫森严的程度甚至还成为童话故事的题材。通常宝物只有被搬进去的份，这次应该是有史以来第一次被搬到外面来吧。

这时就连这名豪杰骑士，威严的脸上也浮现惊讶的脸色沉默了下来。等迪索尔巴德一边发出低沉的沉吟声并坐下后，爱丽丝就站了起来。

「还有另一个问题，法那提欧阁下。」

她决定暂且将刚才的争论放到一边，先提出第二个问题点：

「就算索鲁斯与提拉利亚的恩惠再怎么稀薄，峡谷也不是完全黑暗，而且也没有与大地隔绝。我想那个山谷里应该有长年累月积蓄下来的庞大神圣力。到底什么人可以在开战前这么短的时间内把这股力量使用殆尽呢？」

这次换成法那提欧无法立刻回答了。

贯穿山脉的山谷确实比野营地后方的那片草原还要狭窄，但是宽度也有一百梅尔，长度甚至有一千梅尔。要让充满如此广大空间的神圣力瞬间枯竭，必须要几百名术者同时使用高等神圣术，但法那提欧刚才已经说过，守备军里没有这么多术者了。

或者由少数人使用足以产生天地变异的超大规模术式也可以耗尽神圣力，但拥有这种力量的，除了已经死亡的最高司祭亚多米尼史特蕾达与贤者卡迪娜尔之外，应该就没有别人了。

但是副骑士长却一边用金褐色眼睛凝视著爱丽丝一边用力摇了摇头。

「你错了，的确是有。唯一有一个人能够办到这补事。」

「…………唯一一个人……？」

爱丽丝一边呢喃，一边环视守备军成员。

但法那提欧接下来所说的，竟是完全出乎意料之外的名字。

「就是你，爱丽丝‧辛赛西斯‧萨提。」

「咦……？」

「你自己可能没有发现，但你现在的力量已经超越整合骑士的范畴。现在的你，应该可以行使……足以开天辟地的真正神力。」

7

「上级整合骑士有那么强大的力量吗？」

坐在类似恐龙般的双头怪物所拖行的大型战车上──说是战车，其实只不过是没有炮台也没有履带的箱型四轮车──身体跟著晃动的加百列‧米勒如此问道。

即使是铺著高级坐垫的长椅依然无法消除震动，但是跟士兵时期经常搭乘的布莱德雷步兵战斗车那种几乎要把人杀掉的乘坐感比起来已经好太多了。大概就只是会让放在边桌上的红酒杯发出啪嚓啪嚓拍打声的程度。

从黑曜岩城出发到现在已经过了三天，虽然是现实世界里未曾经历过的长时间移动，但几乎感觉不到疲劳。虽说这可能跟战车的坐垫相当舒服无关，只是因为这里是假想世界罢了。加百列脚边，慵懒躺在厚厚地毯上的妙龄美女，一边抚摸缠著绷带的右脚一边点了点头。

「他们的实力无庸置疑。这个嘛……在长达三百年的战史里，我们暗之术师与骑士从来没有杀死过整合骑士──这么说您能够理解吗？当然，反过来的情况可以说多如天上繁星。」

「唔……」

代替闭上嘴的加百列，在宽广车厢墙边盘腿坐著，抱著一瓶蒸馏酒的瓦沙克发出疑惑的声音。

「但是蒂伊大姊啊。那群叫作整合骑士的家伙真这么强的话，为什么没有攻过来呢？」

暗黑术师总长蒂伊‧艾‧耶尔对瓦沙克露出更加艳丽的笑容，然后竖起食指说：

「问得好，瓦沙克大人。那些家伙确实是能够以一挡千的猛将，但怎么说也只有一个人而已。只要在广大空间被上万名军队包围，就有可能因为不断受到一些小伤害而耗尽天命对吧？所以那群家伙才会这么卑鄙，绝对不会越过没有被包围危险的尽头山脉。」

「哦……原来如此。就是防御力再怎么强的Mob，只要用简单的DoT伤害一点一点削除生命值，总有一天能够打倒它的意思……」

「什么……？Mob……?」

人工摇光的蒂伊当然不会懂瓦沙克的比喻，这时加百列狠狠瞪了他一眼，才轻咳了一声继续说道：

「总而言之，只要把那些整合骑士拖到够宽敞的战场，就能够加以包围并歼灭对吧？」

「理论上是这样。虽然哥布林和半兽人一定会出现超过万名以上的牺牲者就是了……」

蒂伊发出「呜呵呵」的笑声，从放在地板上的银杯里拿起一个颜色刺眼的果实，接著同样鲜红的嘴唇以舔食般的动作将其含进嘴里。

其实根本不用她说，步兵个体的损耗对加百列来说原本就无关痛痒。只要能够击破敌军，就算包含眼前蒂伊在内的黑暗领域大军全部牺牲，他也不会有任何怨言。这场战争在某种意义上，和Glowgen Defense Systems的战术研究所里日常举行的战术模拟练习没有什么两样。

越过成千上万的尸体，以新支配者的身份君临人界，对全土发出最初也是最后的命令。命令他们找出名为爱丽丝的少女并把她带过来。然后在这个奇妙世界里的任务就结束了。

一想到这里，就觉得这口味有点独特的红酒让人感到有点怀念。

加百特举起玻璃杯，一口气喝光浓紫色液体。

这个时候，「爱丽丝」浮现在灵魂猎人加百列‧米勒脑海里的模样，在无意识中就和名字极为类似的首位牺牲者爱丽西亚‧克林格曼那无垢、稚嫩且纤细的容貌重叠在一起。他认为爱丽丝一定是生活在类似故乡太平洋帕利塞德的城市里，而且是一名温柔美丽──又柔弱无力的少女。

因此加百列才没注意到某个可能性。

他完全没有想到，追求的「爱丽丝」会以整合骑士的身份率领著敌军。

皇帝旗不停飘动的指挥车排在最后方的长长队伍，就这样缓慢但确实地朝向西方边境持续行军。染著血色的远方天空中，宛如锯齿般尖锐的群山已经逐渐现出身影了。

移动开始的第四天，也就是十一之月七日。

黑暗领域军的本队来到一处山麓，从这个地方能够看见即将崩坏的大门。宽广的台地周边，已经排满了先遣部队准备好的黑色帐篷。

咚咚隆。

咚咚隆。

撼动地面的重低音是来自于巨人族击打的战鼓。

在最后方指挥车的屋顶上，加百列无言地注视著原本排成一列的本队，像被巨大心脏推动的无数血球一般整个散开的模样。

打先锋的第一连队，是由哥布林的轻装步兵大队与半兽人重装步兵大队共一万五千名所组成。他们配合贯穿尽头山脉峡谷的宽度排成了纵队。队列的各处都配置了宛如攻城塔一样高大的巨人，数量虽然不多只有仅仅五百名，但应该能发挥出主力战车般的功效，援护战场上的步兵队伍吧。

亚人族后方的第二连队，是由共有五千人的拳斗士团与同样为五千人的暗黑骑士团所组成。刚继承暗黑将军的年轻骑士可能是希望洗刷前代的污名自愿打头阵，但加百列否决了他的要求。这是因为预测到骑士个体的整体士气一定相当低落，所以要排除这种不稳定的要素。

第三连队由食人鬼的弓兵七千，以及全是女性的暗黑术师团三千所组成。从步兵后方冲进峡谷，藉由远距离攻击歼灭敌军就是他们的任务。据术师总长蒂伊所表示，就算距离遥远，只要能目视构成敌人主力的整合骑士，就可以集中火力于一点来打倒他们。

老实说，加百列也不是没有直接跟这些号称无敌的骑士战斗，然后尝尝看这些灵魂的欲望。但要是因为意想不到的事故而失去这个高等帐号，那就偷鸡不著蚀把米了。之后不论要生产多少Underworld人，也就是人工摇光都没问题。目前还是要以捕获「爱丽丝」并且脱离O turtle为优先目标。

登入到现在，内部时问已经过了八天，现实世界里是将近十五分钟左右。今后要完全支配人界，把搜寻爱丽丝的命令传达到全世界应该要花上十天左右吧。考虑到这一点，就会希望尽快结束这场战争──最长也只能花整整一天就要把事情解决。

「唉～结果没有我出场的机会吗？」

身边抱著已经不知道是今天第几瓶威士忌的瓦沙克这么抱怨著。瞄了他一眼后，加百列就用稍微辛辣的口气指责他说：

「我都看到了。那个叫作夏斯达的将军变成龙卷风时，你这家伙丢下我率先逃跑了对吧。」

「嘿嘿，不愧是队长，什么都逃不过你的眼睛。」

瓦沙克一点都没有愧疚的模样，直接咧嘴笑了起来。

「哎呀，我从以前就专门负责PvP。不擅长对付那种没有实体的怪物啦。」

听见部下说出这种不知道是认真还是开玩笑的藉口，加百列看了他一阵子后才简短地询问：

「瓦沙克，你为什么自愿参加这次的作战？」

「你说的作战是潜行到Underworld吗？那当然是因为好像很有趣啦……」

「不是，我问的是在这之前。也就是袭击O turtle的作战。你虽然是GlowgenDS的工作人员，但怎么说也是专门负责网路作战的吧。什么动机让你参加这种可能会吃真实子弹的任务？从你的岁数来看，也不可能是像汉斯与布里克那种从中东回来的佣兵吧。」

加百列难得会说出这么长一段话，但他当然不是对瓦沙克‧卡萨鲁斯有什么太大的兴趣。只是忽然想到这个年轻人轻薄的态度底下究竟隐藏了些什么。

瓦沙克轻轻耸了耸肩，回答了一句「都一样啊」。

「这个问题的答案，也一样是好像很有趣。」

「哦……」

「真要说的话，像你这种大学毕业的菁英分子跑到战场来才更夸张呢。就算是有从军的经验也一样。」

「我这个人是现场主义者。」

加百列一边回答，一边在内心呢喃著。

瓦沙克，对你来说什么叫作有趣？是用枪射击？还是……能够杀人呢？

当他想著要继续深究下去还是就此中断对话时，挂在指挥车后方的梯子就传来喀喀的高跟鞋声音，接著暗黑术师公会总长蒂伊‧艾‧耶尔就出现了。

她恭敬地行了个礼，舔了一下嘴唇后就开始报告：

「陛下，全军的配置已经完成了。」

「嗯。」

加百列放下翘著的脚，从暂时的皇座上站起来，朝著下方环视了一圈。

除了在前方展开阵形的三万五千名主力部队外，还有主要由哥布林与半兽人构成的预备军一万，以及商工公会的锱重部队五千在指挥车左右两侧待机。

这支总数达五万的军队，就是加百列拥有的全部兵力。所以如果丧失所有个体还无法攻破敌军的防守，那就得从头修正计划了。届时捕获爱丽丝的可能性也将变得极其微小。

但根据侦查的龙骑士所表示，敌军最多也只有三千人左右。也就是说只要能按照计划排除整合骑士，就不可能会败北。

「好，距离大门崩坏还有多久的时间？」

蒂伊保持低著头的姿势回答加百列的问题：

「大概还有八个小时左右。」

「那么，在崩坏的一个小时前让第一师团进入峡谷。在最靠近大门的地方分散部队，等大门一崩坏就一起展开突击。战线往前推进之后，就投入第二、第三师团，一口气歼灭所有敌人。」

「遵命。相信不用等到明天，陛下就能看见敌将的首级了。虽然很可能已经烧得焦黑就是了。」

蒂伊发出「呵呵呵」的微笑后，迅速对在背后待机的传令术师下达指令，接著再次深深行了个礼并走下楼梯。

加百列从指挥车的车顶眺望著屹立在远方的巨大石门。

虽然距离两英哩以上，但是却有种快要压在自己头上的重量感。那道门整个崩坏的时候，一定是相当壮观的景象吧。

但是真正的飨宴要从那时候才开始。爆散并且消失的数千个灵魂，一定会放出笔墨难以形容的美丽光芒。躲在O turtle上轴的那群RATH技术人员，应该会对无法在内部观赏自己策划的最壮观场景而感到遗憾吧。

咚咚隆。咚咚隆。

咚、咚。咚、咚。

节奏加快的战鼓，似乎更加强化了由数万军人所散发出来的饥渴与斗志。

8

「那……桐人就拜托你们了。」

爱丽丝依序凝视著两名年轻少女的脸这么表示。

初等练士，不对，应该说已经是一名正式剑士的缇洁‧休特里涅与罗妮耶‧阿拉贝鲁挺起背杆点了点头。

「好的，请交给我们吧，爱丽丝大人。」

「我们一定会好好保护桐人学长。」

刚回答完，缇洁就以左手，而罗妮耶则以右手用力握住新制轮椅的把手。

闪烁著银灰色光辉的细长轮椅，是爱丽丝以术式将物资帐篷里多出来的全身铠甲改变形状所制成。它比在卢利特使用的木制轮椅还要轻，而且也有足够的强度。

但是坐在上面的桐人紧紧抱住的两把剑所带来重量就实在没有办法处理了。心里虽然有点担心两名少女不知道能不能推动轮椅，但两个人配合得天衣无缝，笔直地把轮椅推到爱丽丝面前。

这样的话，就算接到立刻撤退的命令也不会落人后了。只不过，被逼得必须从峡谷撤退时，守备军就等于是陷入遭到包围歼灭的命运。

老实说，只要发现战况略呈败势，就希望她们能带著桐人逃向西方。但那也不过是把命运延后几个月──不对，应该说延后几周而已。

事先已经订好计划，只要守备军败北，保护尽头山脉的四名骑士也将跟著撤退，然后一边让各地的城镇与村子里的居民避难，一边将央都圣托利亚的城壁做为最后的防御线。但这只是无谓的抵抗。那个美丽的都市以及石灰岩制成的中央圣堂，不久后就会遭到侵略军蹂躏并烧毁。在尽头山脉这个封闭的墙壁内侧，众人将无处可逃……

爱丽丝跪了下来，从同样的高度下凝视著桐人的眼睛。

来到野营地的五天当中，只要有时间就会对桐人说话，甚至握住他的手与紧紧抱住他。但是到今天为止，都没办法让他产生太大的反应。

「桐人……这可能是我们最后一次见面了。」

勉强保持著微笑的爱丽丝，对著黑发年轻人这么呢喃。

「叔叔说你可能是决定这场战争胜败的关键人物。我也是这么认为。因为这支守备军就等于是你创造出来的啊。」

实际上，如果没有桐人和尤吉欧，目前在东大门布阵的就是最高司祭亚多米尼史特蕾达与整合骑士团，以及由那种恐怖的巨剑魔像所组成的军团了。

如果有两三千个拥有强大战斗力的巨剑魔像，五万的黑暗领域军队根本就算不了什么。但那也等同于人界的灭亡。因为巨人的素材就是好几万名人界的居民。桐人他们牺牲了一条生命与一颗心，才防止了这样的悲剧。

但是，贝尔库利率领的人界守备军就这样败北的话，人界依然会陷入不同形式的巨大悲剧当中。

「……我也会努力。会把你给予我的天命完全燃烧殆尽。所以……如果我被击倒，以最后的力量呼唤你时，请一定要站起来拔出你的剑。只要你能醒过来，有几千、几万名敌人都不是问题。你一定会再次产生奇迹，守护人界……还有大家。因为你是……」

──打倒那个最高司祭的最强剑士啊。

在内心深处这么呢喃后，爱丽丝就伸出双手，用力抱紧桐人瘦削的身躯。

松开分不清是一瞬还是数分钟的拥抱后，站起身的爱丽丝，注意到蓝色眼睛里晃动著复杂光芒的罗妮耶一直凝视这边的视线。一开始不知道是怎么回事的她眨了眨眼睛，但是马上就了解是怎么一回事。

「罗妮耶小姐。你……喜欢桐人吧。」

一边微笑一边这么说之后，娇小的少女就用双手遮住嘴巴，脸颊到耳朵附近也整个红透了。她随即伏下视线，以几乎快听不见的声音回答：

「没……没有，我……怎么配呢……我只不过是一名随侍初等练士而已……」

「哪有什么配不配的。罗妮耶小姐也是爵士家的继承人吧？我是出生在边境的小村子里，而桐人则是连出生地都不清楚……」

罗妮耶忽然用力摇头来打断爱丽丝所说的话。

「不是的！我……我……」

缇洁伸出右手来，温柔地支撑住双眼积蓄著大大泪珠且声音断断续续的罗妮耶。这时她红叶色的眼睛里也满是泪光，接著以颤抖的声音开始说道：

「爱丽丝大人……您知道桐人学长与尤吉欧学长犯下什么样的禁忌吗？」

「嗯……嗯。听说是因为在学院内发生争执……最后杀伤了其他学生。」

半年前，当时什么都不知道的爱丽丝依然是公理教会的尖兵。即使到了现在，她还是清楚记得自己接到元老院的逮捕令时那种震惊的感觉。因为就连在教会的史书里，都没看过央都的学院发生学生杀害学生这种重大的禁忌违反。

爱丽丝点头后，缇洁又继续追问：

「那么……您知道学长们为什么会犯下那样的禁忌吗……？」

「不……这我就不清楚了……」

当她摇头时，耳朵深处忽然重新响起一道叫声。

和桐人一起被拋到中央圣堂的外壁之后，他对著表示不需要罪人帮助的爱丽丝大叫了一段话……

「──就算禁忌目录没有禁止这么做……但你真的认为上级贵族就能够随心所欲地玩弄罗妮耶和缇洁那样的无辜少女吗！」

没错，我就是在那个时候听到这两个人的名字。

上级贵族，指的应该是桐人斩杀的学生吧。而被玩弄则是──

在瞪大双眼的爱丽丝面前，缇洁以发抖的声音开始说道：

「……莱欧斯‧安提诺斯上级修剑士与温贝尔‧吉杰克上级修剑士，不停对我们的朋友芙蕾妮卡‧歇丝基初等练士做出屈辱的命令。我们虽然对两位修剑士提出抗议，但那个时候却因为过于气愤而使用了足以被判定为失礼行为的言词。因此他们就发动了基于帝国基本法的贵族赏罚权……」

接下来的事情，光是回想也很痛苦吧。缇洁再也说不出话，而罗妮耶则是低著头发出呜咽声。

想要她们别再说下去的爱丽丝正准备开口时，红发少女又勇敢地继续开始说道：

「……当我们即将被施加难以忍受的惩罚时，桐人学长和尤吉欧学长就为了解救我们而挥了剑。如果我们聪明一点，就不会发生那种事了。学长他们就不会为了纠正法律而和教会战斗，也不会因此丧命了。我们……犯再也无法弥补的罪过。所以……就算脸皮再厚，我也不敢说自己喜欢学长……」

把心事全部吐露出来的缇洁，这时终于也流下眼泪。两名年轻的少女抱在一起，低声发出对这个年纪来说太过沉重的悔恨呜咽。

爱丽丝一面咬紧牙根，一面抬头看向采光用的小窗。

她自认为已经清楚占据著四帝国的上级贵族究竟有腐败了。他们饱食终日、累积私财且荒淫无道。

但是过去的整合骑士爱丽丝，认为详细知道这些罪过会让自己也遭到污染，所以故意不去注意这些贵族的所作所为。不论他们做什么，只要没有触犯禁忌就没关系──因为自己是被从神界召唤到这里的法律守护者。她一直都是这么深信不移。

但这种沉默的不作为才是罪过。虽然没有违背桐人憎恨的禁忌目录，但就是这样才罪孽深重。跟什么都没做的自己比起来，眼前的两名少女要勇敢多了。

爱丽丝深深吸了口气，以灌注力量的声咅说：

「不，你们错了。你们才没有什么罪。」

忽然迅速抬起头的人是罗妮耶。虽然这名少女给人总是躲在缇洁背后的印象，但现在眼睛里却带著强烈的光芒并大叫：

「爱丽丝大人……身为光荣整合骑士的爱丽丝大人不会了解！我们的身体被那两个男人玩弄，尊严也被罪过污染了！」

「身体只不过是心灵的容器。」

爱丽丝一边回答，一边以握住的右拳用力敲打胸口中央。

「只有心……灵魂才是唯一确实的存在。只有自己才能决定灵魂的模样。」

爱丽丝闭上眼睛，把意识集中在自己的内面。

大约两周前，卢利特村遭受袭击，爱丽丝以心灵的力量──也就是心念力取回了失去的右眼。她当时就已经亲身体验到，只要坚定并专注地想著，就能够不依靠术式让肉体产生变化。

但现在光是这样还不够。不光是肉体，必须用心念的力量让身上的服装也产生变化才行。

应该办得到才对。过去桐人不是展现给自己看过了吗？拿著两把剑和最高司祭亚多米尼史特蕾达对峙的他，身上那套和之前服装完全不同的异国风黑色皮革长外套就在眼前不停飘动。

一定要恢复。恢复成在陌生的全白巨塔里醒过来，为了消除丧失记忆的不安与寂寞，只能用厚厚冰层封闭自身心灵之前的爱丽丝。

──我也和你们一样喔，罗妮耶、缇洁。以人类的身份来到这个世界上，犯下许多过错，背负巨大的罪过，然后现在来到这里。如果说桐人和尤吉欧杀人是你们的罪过……那么在那之前，如果年幼的我没有忘记禁忌而碰到黑暗领域的土壤，桐人他们根本就不用以来到央都为目标了。

没错，那就是我的罪过。就算没有记忆，爱丽丝‧滋贝鲁库也不是不认识的其他人，确确实实是过去的我。在卢利特村的日子告诉了我这一点。

即使闭上眼睛，也清楚知道有温暖的白光正包围自己的身体。

爱丽丝缓缓睁开眼睛。

由于她低著头，所以一开始看见的是自己穿著的裙子。但那不是代表公理教会的纯白色，而是像秋天的天空般清澈的蓝色。

裙子上还有一件原色围裙。黄金铠甲与护手已经消失。把手往头上伸去，指尖就碰到大大的缎带。而且头发似乎也变短了一点。

一抬起头，眼睛就和露出茫然表情的罗妮耶与缇洁相对。

「……看吧？身体和外表，只不过是心灵的附属物罢了。」

当然这只是暂时性的变身。当集中的精神中断的瞬间，就会恢复成原本骑士的模样吧。但这样应该能把爱丽丝、桐人以及尤吉欧的心意传达给这两名少女知道。

「没有任何人能够弄脏自己的心灵。在边境出生的我，原本应该是以这种模样长大才对。但是十一岁的时候，以罪人的身份被带到央都，然后遭到术式删除记忆并成为整合骑士。我也曾经诅咒过这样的命运……」

爱丽丝所说的，是除了自己之外就只有整合骑士长贝尔库利知道的重大秘密。但是她相信这两个人应该能接受，所以又继续表示：

「但是……桐人教会了我，即使是这样我依然有办得到而且应该去做的事。所以我已经不再迷惑。我决定接受自己并往前迈进。」

爱丽丝举起双手，同时紧握住罗妮耶与缇洁的手。

「你们一定也有只属于自己的，宽广、漫长且笔直的道路。」

互握住的手上，滴落下几滴的泪水。

顺著少女脸颊滑下的泪，带著与刚才完全不同的彩色，发出了极为美丽的光芒。

插图018

最后再次抱紧坐在轮椅上的桐人，把他交给罗妮耶与缇洁后，爱丽丝就走出帐篷。

结果艾尔多利耶就像早在外面等待一般跑了过来，说出了夸张的赞辞：

「哦哦，真是太完美了……看起来简直就像是凝缩了索鲁斯的光辉一样……这才是吾师爱丽丝大人啊……」

「反正战斗个一个小时就会沾满尘土了。」

爱丽丝冷冷地如此回应，低头瞄了一眼自己的身体。

刚才的变身现象已经消失，黄金护胸与纯白裙子反射阳光后发出炫目的光芒。如果能活著回来，就在哪个地方加上蓝色布料吧，心里这么想的爱丽丝抬头看向西方的天空。

索鲁斯早已开始西下。大约再过三个小时左右，就会消失在地平线上。在那同时，东大门的天命也将消灭。三百年的封印终于要解除了。

能做的事都已经做了。

这五天里，爱丽丝也参加了守备军的训练，发现士兵们的战技已经被磨练到很难相信只经过半年的训练。更惊人的是，所有士兵都学会了不存在于传统流派的连续剑技。

一问之下，原来是副骑士长无私地教授众人她耗费漫长岁月所钻研出来的剑技。虽然最多只到三连击，但对上只按照本能挥动蛮刀的哥布林与半兽人应该是相当可靠的武器。

当然，拥有独特连续技的暗黑骑士对士兵们来说负担还是太重了。包含似乎拥有更高速连击的拳斗士在内，都只能够由整合骑士来对抗他们。

最重要的是，不能被一开战应该就会涌过来的亚人族大部队压制，以及必须在受到最小的损害下撑过食人鬼的大弓与暗黑术师的远距离攻击。

作战是能否成功的重任，现在就加诸在爱丽丝一个人肩上──

把视线从天空移下来后，就看见后方补给部队为了准备最后的餐点而升起的好几道炊烟。罗妮耶与缇洁应该已经快带著桐人到那边和他们会合了。

无论如何都要保护他们。

「爱丽丝大人，差不多了……」

听见艾尔多利耶的声音后点了点头，接著爱丽丝为了转头而一只脚往后退。

但这时又停下脚步，把视线移到唯一的弟子身上。

「……怎……怎么了吗？」

凝视著青年骑士像是感到困惑而眨眼的脸，爱丽丝原本绷紧的嘴唇稍微放松了一些。

「……艾尔多利耶，一直以来你真的是尽心尽力在帮助我。」

「怎……怎么忽然说这种话！」

爱丽丝把自己的右手轻轻放在哑然站在现场的骑士左手上，又继续说道：

「你待在我的身边，对我来说是很大的安慰。你是因为担心我……才不选择迪索尔巴德阁下那样资深的男骑士，而选择让没有太多实绩的我指导对吧？」

「没……没这回事，我怎么可能有那么傲慢的举动！我只是打从心底佩服爱丽丝大人的剑技……」

艾尔多利耶拚命摇头否认，爱丽丝则一瞬间握紧他的手又放开，然后再次露出微笑。

「就是有你的支持，我才能在这条险峻的道路上一直走到今天。谢谢你，艾尔多利耶。」

说不出话来的年轻骑士，眼睛里忽然冒出斗大的泪水。

「…………爱丽丝大人……为什么要说……到今天呢。」

他以沙哑的声音这么问道。

「为什么爱丽丝大人要用这种自己的道路好像要在这里结束般的说法呢。您……您还没有把所有的本事教给我啊。不论是剑技还是术式，我的实力都还跟您有天大的差异。接下来您还得一直、一直锻炼、指导我才行啊……！」

在他伸出不停发抖的右手快碰到自己之前──

爱丽丝忽然变成以严厉的声音大喊：

「整合骑士艾尔多利耶‧辛赛西斯‧萨提汪！」

「是……是的！」

骑士的手倏然停止，摆出直立不动的姿势。

「做为你的师父，接下来就是我最后的命令。你要好好活下去。活著见证和平到来，并且夺回你真正的人生与心爱的人。」

除了爱丽丝之外的所有整合骑士，「记忆的碎片」以及被变成剑的「心爱的人」都还是被封印在中央圣堂最上层里。一定有方法让它们恢复成应有的形状，回到应该存在的地方。

对保持立正姿势并无声落泪的艾尔多利耶点了点头，爱丽丝迅速转过身子。金黄色头发与纯白裙子直接撕裂秋天的冷空气。

正前方可以看见沉浸在微暗当中的大峡谷与东大门。

接下来爱丽丝将咏唱过去未曾经验过的超大规模神圣术。这全是为了将充满山谷里的神圣力一滴不剩地浓缩起来，藉此给予敌军痛击。

如果说错一句术式──不对，应该说意识稍微有点不集中的话，浓缩的神圣力就会爆炸，让爱丽丝整个人完全消失在这个世界当中。

但她完全不觉得害怕。这五天里，已经以整合骑上的身份和贝尔库利与法那提欧、艾尔多利耶等人度过了相当充实的时问，而且也以爱丽丝的身份在卢利特村和妹妹赛鲁卡生活了半年。

更重要的是，遇见了桐人与尤吉欧，藉由跟他们交手而有了心灵上的交流，更因此了解了人类的感情──也就是悲伤、愤怒以及爱情。

自己还有什么好奢求的呢？

爱丽丝高声震响著铠甲，一步一步笔直地走进等待开战瞬间来临的守备军中央。

** 后记

大家好，我是川原砾。目前是带著猛烈的焦躁感写著这篇后记。因为我在完全忘记还有后记的情况下又经过了相当长一段日子了！

呃～那么重新谢谢大家阅读这本《刀剑神域15 Alicization invading》。

上一集的「uniting」里，即使打倒了教会的大魔王，也就是最高司祭亚多米尼史特蕾达，依然在「待续」的情况下结束，而本集的内容就是接下来的结果了……故事跳出人界这个范畴，将舞台移到广大无边的黑暗领域当中。现实世界里也发生了亚丝娜等人所在的O turtle遭到袭击，菊冈先生从浴衣换成夏威夷衫等充满各种动乱的发展……

在这样的情况下，下一集里人界守备军与黑暗领域军的战争终于要开始了。从第9集就开始的Alicization篇也终于要朝著高潮一路猛冲，就请各位再多陪我一下吧！

关于我的近况嘛，就是我和负责插画的abec老师一起以来宾的身份参加了美国最大的动漫博览会「Anime Epo」。虽然是第一次到洛杉矶（应该说也只是第二次到美国），不过发现城市越大活动会场确实就越大！而且挤满整个会场的全美动画迷所表现出来的热情更是让人叹为观止！

当然也有许多SAO粉丝来到现场，让我非常感动。同时也再次体认到，就是有从网路时期到电击文库，再由动画化到游戏化的十几年来都持续支持著我的各位粉丝，才能让SAO这部作品成长茁壮到今天这样的地步。

本书出版的时候，电视动画的第二期应该已经开始播映了（注：此指2014年）。舞台虽然是和第一期完全不同的「枪的世界」，但是从导演到诸位配音员，都全力表现出枪战的帅气与绝对不变的SAO感，也请大家多多支持动画。

时间差不多快到了，谢词就简洁一点吧！帮本集不断登场的大量新角色们绘制魅力十足外表的abec老师、和我一起去LA的责编三木先生、我们不在的时候帮忙守护日本的副责编土屋先生，以及阅读完本书的各位，真的很谢谢你们！

二〇一四年七月某日 川原砾