#+title: 刀剑神域 第二十二卷 Kiss And Fly
#+setupfile: ./setup.setup
* 第二十二卷 Kiss And Fly

** The day

*** before

台版 转自 深夜读书会

1

艾恩葛朗特标准时间，二○二四年十月二十三日晚上九点。

我这个等级96的单手剑使桐人向等级94细剑使亚丝娜求婚，并且获得同意。

当然是仅限于Sword Art Online刀剑神域这款VRMMORPG的世界当中。现实世界的我和亚丝娜甚至没有见过面，而且我根本就还没有到达法定结婚年龄──亚丝娜可能有点微妙就是了。

我不知道首次采用「结婚系统」的是哪一款游戏，但是远从二十年前开始，MMO世界的角色之间可以结婚就变成主流的情形了。由于大部分的游戏里成为「夫妇」的角色都能获得某种特典，所以有许多人都是因此而结婚，当然也有认真作为角色扮演的一环而结婚的玩家，当中甚至有因为游戏内的婚姻成为契机，最后在现实世界也共结连理的例子。先说这只是我个人的想像，假如对全世界的MMO玩家做「有无游戏内结婚经验」的问卷调查，有结婚经验者应该会超过五成吧。

但很遗憾的是（不知道可不可以这么说就是了），我在至今为止玩过的MMORPG当中都没有跟任何人结过婚。

理由是──嗯，是因为我与他人之间的沟通技能低落的缘故，不过也跟我完全不知道该如何面对「游戏内的结婚」有关系。假设我这个名为桐谷和人的玩家所操纵的男性虚拟角色Kirito，与世界上某个实际存在的女性或者男性玩家（可能性相当大）所操纵的女性虚拟角色Dareko（假定）结婚，那我只要把那个某小姐当成永久固定小队成员就可以了吗？还是需要做出爱着某小姐这样的角色扮演？又或者是──必须意识到某小姐后面那个活生生的某个人呢……？

老实说，在SAO之前玩过的游戏里，也不是没有被登录为朋友或者公会成员的女性角色提出「我们结婚吧」的邀约。但是每次遇见这种情形，我都在萤幕前面流着冷汗并且僵住，给对方留下相当尴尬的回忆。

连我自己都觉得实在太紧张、太多虑、太胆小了。

但是，我沉溺在MMO游戏里的理由本来就是那是个假想的世界。所有虚拟角色后面都存在性别、年龄无法特定的陌生玩家。所以思考「这个人究竟是谁」也没有用。因为包含我在内，所有角色都不是真正的那个人。

只不过对我来说，「结婚」这个系统与我对结婚的认识产生了正面的冲突。就算只是在游戏里结婚，但只要和某个人有了特别的关系，无论如何就是对在现实世界操纵滑鼠、敲打键盘的「某个人」感到在意。

因此我一直避讳与网路游戏内的某个人组成永远的搭档，当然在这款异常的死亡游戏Sword Art Online刀剑神域应该也是一样。不对，由于这里虚拟角色的容貌与肉身完全相同，所以我可能跟别人保持了更远的距离。

但是慢慢融解我这种不自然的感觉──或者可以说是让恐惧变小，最后终于消失的人就是亚丝娜。

死亡游戏开始后过了两年左右，她虽然经常因为状况而改变立场，但从来没从我的视界中消失。一开始是暂时的小队成员，之后即使她隶属于公会血盟骑士团也还是攻略组的同伴。有时候会一起调查不可思议的圈内杀人事件，又有时候会替我烹煮S级食材道具。经过和这样的亚丝娜交流，我学到了一件事。

在这个世界──以及现实世界，说不定在SAO之前玩过的所有非完全潜行型MMO游戏也是如此，眼前的某个人是不是真正的那个人都是由我自己来决定。怀疑并且与其保持距离，那个人就会变成冒牌货；相信并且靠近，那个人就是真货。

现在，名为亚丝娜的剑士就在我眼前。

和她在一起就很快乐。战斗、欢笑、闹别扭的亚丝娜都能唤起我内心强烈的感情。希望她能一直待在我身边，也希望能跟她有确切的连结。看着亚丝娜的时候，我已经完全不会去想这个人究竟是谁了。

所以我才会向亚丝娜求婚。

老实说，并非所有的迷惘都已消失无踪。渴望亚丝娜的这种心情究竟是不是所谓的「爱情」，关于这一点我也还无法确定。总是会忍不住去想，在现实世界一直和家人保持距离，来到这个世界后也执着于独行的我真的有爱人的心吗？

但我觉得只要跟亚丝娜在一起，终究会找到这个最后问题的解答。

──到这里就是现在的我终于摸索出的「SAO里关于结婚的精神面」。

另一方面，即使是游戏世界，既然结婚了，物质面当然也一定会存在。具体来说就是新居该怎么办。

结婚后当然是要住在一起，但这个时候，我在第五十层主街区阿尔格特的巷弄里的狗窝就不用说了，亚丝娜在第六十一层赛尔穆布鲁克的公寓也有点狭窄。而且除了面积之外，还有其他原因也让我们无法继续住在至今为止的住处。

公会「血盟骑士团」副团长──「闪光」亚丝娜现在可以说是最大最强的偶像玩家。

在情报贩子发行的报纸里，所有玩家的人气投票永远是第一名，甚至存在复数粉丝俱乐部，听说某大型连锁杂货店对她提出了CD，不对，应该是RC<录音水晶>出道的提案，结果被用细剑抵住然后落荒而逃。

想到死亡游戏初期她经常罩着连帽斗篷的「小红帽」时代，就会有种恍如隔世的感觉，总之像这样的偶像一旦结婚的消息曝光，各家报纸一定会大肆报导。

许多粉丝会叹息、伤心，最后这些能量将转变成诅咒属性的攻击，让身为结婚对象的我幸运值一路降到负数──就算先不管这件事，到时候采访之类的事情一口气涌至，我们根本就没办法过新婚生活，所以尽可能想隐瞒已经结婚的事实。

当然，因为已经把消息告诉她诸多的朋友以及我少数的友人，所以不可能长期保持秘密，不过真要说起来，我们也没有立场一直沉浸在蜜月的气氛里。打倒七十四层的楼层魔王「闪耀魔眼」后才过了四天，应该还要一点时间才能发现目前最前线第七十五层的魔王房间。但是迷宫区的地图拓展也就算了，我和亚丝娜一定得参加魔王战。

因此在那之前有十天左右……不对，是两个星期左右的空档……可以的话，必须想办法找到能让两个人度过安稳时光的房子。

从经济面来看，我和亚丝娜在至今为止的游戏中所累积的道具群里，把大部分目前不需要的物品卖掉换成珂尔的话，应该还勉强足以买下圈内……也就是城墙内侧的独栋房子。但是在那种地方购买新居的话，当天就会被情报贩子发现了。最理想的是──在早就被攻略下来，几乎没有玩家会来的楼层里面，而且是建在角落，虽然不起眼但还算宽敞的房子。

虽然是很严苛的条件，不过在求婚之前我就看好理想的物件了。

艾恩葛朗特第二十二层还是最前线已经是远在一年半前的事情了。因为是低楼层所以面积相当大，整层几乎都是深邃的森林、草原以及湖泊这种美丽又没有高低起伏的地形，而且没有什么大不了的任务与练功区魔王。攻略组玩家们从主街区高拉尔村一直线就能到达迷宫区，冲上难易度不高的迷宫塔，以低于平均天数相当多的速度打倒了魔王。现在来到第二十二层的玩家，大概就只有以大小湖泊为目标的钓客以及收集木材的木工匠而已。

虽然我也有很长一段时间没有到那里去，但不知道为什么就是有一幅光景让我难以忘怀。

那是击败第二十二层魔王当天，想要尽可能消化在高拉尔村承接的任务而一个人到处奔走的时候。

我在清澈的湖畔，发现了一条不靠近就无法发现的小径。虽然和任务似乎没什么关联，但是在无意识中顺着那条小径往前走，最后在爬上山丘后的尽头处发现一栋以深邃针叶树森林作为背景的圆木屋悄悄矗立在那里。

作为墙壁的圆木到处都是青苔，屋顶上虽然伸出两三根新枝，不过完全没有腐朽的感觉。反而完全融入周围自然的环境当中，让人有种宛如精灵族房子的美感。

我静静打开木制的闸门（既然能够这么做就知道不是其他玩家的房子），以搜敌技能确认内部（发现无人时就知道也不是NPC的家），靠近到正面露台时才终于发现门把上挂着「FOR SALE」的木牌。

尚未到达40级的我，指着木牌上售价的位数算了一下，然后叹了一口气，依依不舍回头看了好几次才离开现场。而且还边走边幻想着有一天会有足以买下这间房子的珂尔塞满道具栏。

实际上，突破五十层然后升上70几级时稍微努力一下或许就可以买下来。但是身为攻略组，实在无法把距离最近的转移门单程就要二十分钟的房子当成攻略据点。结果我就把据点设在第五十层的主街区阿尔格特，到前几天都还是在那里起居。

发现第二十二层森林里的房子后又过了一年半──

下定决心向亚丝娜求婚，思考新居该怎么办时，我的脑袋里就率先浮现那栋圆木屋。也觉得它就是唯一的选择了。

我首先提出那栋圆木屋的情报来作为求婚的开头，接着提案搬家到那里，最后说出「我们结婚吧」。

我内心觉得，亚丝娜之所以毫不犹豫就回答「好的」，可能多少也受到了那间房子的保佑。

2

事情就是这样。

求婚的隔天，十月二十四日，下午两点过后。我和亚丝娜一起来到第二十二层。

趁昨天前往第五十五层格朗萨姆的血盟骑士团本部，两个人一起提出了暂时退团申请。虽说只是暂时，但系统上还是确实脱离了公会，所以两个人的颜色浮标上已经没有公会的红色十字标帜。

离开主街区高拉尔村的转移门后，首先朝西南方的某座大湖泊走去，然后我就随口对身边的亚丝娜问道：

「那个，亚丝娜加入KoB多久了？」

「嗯……」

细剑使摇晃着栗色长发并微微歪着头说：

「我记得是去年二月接到团长的邀约……已经过了一年多了吧。因为是第二十五层的魔王战刚结束时的事情……」

「这样啊……KoB是在『军队』半毁不久后组成的吧……」

我稍微瞄了一下上层的底部。

对众攻略组玩家来说，这个闲静的楼层仅仅往上三层的艾恩葛朗特第二十五层是继第一层之后的真正试炼。

离开主街区后马上就有即使跟第二十四层相比也异常强大的怪物阻挡去路，练功区的地形宛如迷宫般复杂，就连要前往下一座城镇的路上都出现了数名死者。给予情报的NPC数量稀少，相对地有许多毒沼泽、落穴等地形陷阱，好不容易踏遍楼层到达迷宫塔时，攻略组成员已经是疲惫不堪。

这时候不甘示弱而奋力鼓舞大家的是率领公会「艾恩葛朗特解放队<ALS>」──没错，当时还不是「解放军」──名为牙王的玩家。被他以关西腔不断地刺激后，每个人都浮现「这个臭家伙！」的心情，然后趁势站起身子。

但是当时无疑是整个攻略组领袖的牙王在面对第二十五层的楼层魔王战时，被某人流出的假情报所骗。光以不满一支联合部队的四十数名公会成员就先行闯入了魔王房间。结果解放队半数以上的成员死亡……这时候包含我和亚丝娜在内的攻略组主力才终于追上来，在我们也牺牲了不少成员的情况下，好不容易打倒凶恶的魔王。

但是胜利后没有任何人能因为超越艾恩葛朗特的四分之一地点感到开心。因为牙王充满怨叹的吼叫声响彻了整个魔王房间。

他在那里与攻略组分道扬镳，带着存活下来的伙伴前往遥远下方的第一层。然后与在起始的城镇活动的互助组织「MMO Today」会合──最后从这样的大集团里诞生出「军队」这个组织。

「……那个时候攻略组全体都陷入超级绝望的气氛当中……在最前线战斗的人数突然变成三分之二，而且那可能还是某个人所设下的陷阱，所以说起来也是理所当然会出现的情形……第二十六层的首次练功区魔王攻略会议时，大家都是一脸阴暗的表情……但这个时候新成立的公会KoB就气势磅薄地闯进来。所有人都穿着红色与白色的客制装备，给在场者相当强烈的冲击……」

我一边走在湖畔，一边断断续续地说出当时的回忆。不过因为身边显得特别安静，我便往旁边瞄了一眼，结果发现亚丝娜不知道为什么脸颊微红并且稍微把头别到一边去。我内心浮现「哈哈」的想法，然后继续说下去。

「……尤其是站在集团前头的副团长大人，让众人……我和克莱因也就算了，竟然连艾基尔都看得入迷了。和之前朴素的装备完全相反，穿着纯白无袖骑士服与鲜红迷你裙，再加上致命的白色过膝袜……那个瞬间，该怎么说呢，攻略组原本快四分五裂的心又重新凝聚……」

「咚滋！」一声，左肩受到几乎快产生伤害的打击属性攻击袭击，让我的发言为之中断。一看之下，那个副团长大人本人正满脸通红紧握右拳。

「真是的！那个时候真的觉得很害臊！我认为当然应该由团长站在最前面，但他还是跟平常一样一脸认真地说『由亚丝娜站在前头才能期待带来更多效果』，所以我才会自暴自弃地站出去！」

「这……这样啊……话说回来──那个装备当然是订制的吧？是谁设计的呢？」

「…………听说是除了我之外的公会干部，在瞒着我的情况下开了好几次秘密设计会议。一开始拿给我看时，我冷冷地回答『我没办法穿这种东西！』，结果大善先生噙着眼泪跟我说『你知道光是这套装备就花了多少费用吗！』，我才会自暴自弃地穿上……」

「……原……原来如此。」

现在的最强公会──血盟骑士团虽然是以铁之纪律而闻名，但在草创时期似乎也有相当愉快的氛围。不过当时攻略组整体的士气确实是因为KoB的登场而上升，而他们在那之后也一直站在死亡游戏的最前线──现在这个瞬间，身穿红白色装备的小队一定也在刚开通的第七十五层进行着激烈的战斗……

这时我再次瞄了一眼上层的底部。结果光是这个动作，亚丝娜似乎就看透了我内心的想法。她松开右手，一边温柔地握住我的左手一边说：

「桐人几乎是独自打倒了第七十四层的魔王。当时你的HP条只剩下最后的两三点像素而已。暂停攻略稍微休息一下，其他人也不会有怨言喔。」

「……休息的理由被发现的话，所有人就会疯狂抱怨了吧。」

在混杂着笑声的情况下如此回答后，我也回握住亚丝娜的手。副团长大人露出不知该生气还是该害羞的表情后，发出「呵呵」的简短笑声。

沿着直径一公里左右的广大湖泊绕了半圈，就看到一棵特别高大的杉树──应该说很像的针叶树耸立在前面。仔细观看粗大的根部附近，就能发现一条羊肠小径从湖畔的大路往西南方向分岔出来。

「……你发现这条小路？你还是一样很擅长发现这种隐藏路线耶。」

把这种感想当成是称赞之后，我就挺起胸膛说：

「我当时还没取得搜敌技能的『探知』Mod，所以是光靠眼睛和第六感发现的哟。爬上那座山丘后，马上就能看见房子了。」

结果这次换成亚丝娜的脸庞瞬间绽放出光芒。

「不知道是什么样的房子，真令人期待！快点走吧！」

「…………那个，亚丝娜小姐，那真的是再普通不过的圆木屋，还是不要抱有太大的期待比较好……」

「住在圆木屋是我从小的梦想嘛。只要有壁炉和摇椅，我就非常满足了！」

我加快脚步追上嘴里边这么说边快步爬上山丘的亚丝娜。摇椅在家具行就能买得到，不过我实在不记得里面有没有壁炉了。不对，都到这种地步了，不可能会没有。我在一年半前发现这栋圆木屋就是为了今天。如果这是命运的引导，那么里面一定会有壁炉才对。

我祈祷着圆木屋的屋顶设有烟囱，然后在晚亚丝娜几秒的情况下爬上山丘。站到默默直立在该处的亚丝娜身边，瞪大双眼来寻找烟囱。

────但是……

没有。

我指的不是烟囱。

我们眼前那一片覆盖在草地下的圆形空间里，没有任何种类的人工物件……也就是不存在房屋这种建筑物。

3

我弄错地点了。

由于这应该是最合理的解释，于是我便向亚丝娜道歉并走下山丘，然后花了两个小时探索周边的练功区。

但是不要说圆木屋了，就连新分岔出去的小径都没发现。我沮丧地再次爬上最初的山丘，再次环视着周边的地形。

「…………果然是这里，绝对不会错……」

嘴里无意识中发出这样的声音。

宽广且长满草皮的庭院（现在没有房子所以只是普通的空地），其后方那一整片苍郁的针叶树森林，森林远方屹立着支撑艾恩葛朗特外围部的柱子，最遥远的景色则是无垠的天空。即使过了一年半，这样的景色还是鲜明地留在我的记忆当中。

但唯一遗憾的是，最重要的圆木屋不存在了。虽然觉得不可能，但我还是试着踏入空地并走到正中央，但房子还是没有涌出的模样。

当我茫然呆立于该处，就有踩着草地的沙沙脚步声传过来，然后在我正后方停止。

我实在没办法回头。我们一起搬到第二十二层的圆木屋是我求婚时的发言。现在那栋房子不存在的话，求婚本身不就变成谎言了吗？

「亚丝娜……真的有──这里本来真的有房子。」

依然低着头的我无力地这么说。

绕到正前方的亚丝娜轻拍了一下我的双肩，然后用手掌夹住我的脸颊往上抬。栗色眼珠跟平常没有两样，里面充满温柔的光芒。

「那还用说吗，我当然相信你啊。」

她随即坚定地这么表示，放开手并且退了几步后又继续说道：

「一定是系统上有什么问题而把它撤走了。虽然很可惜，但就算没有房子这里也是很棒的地点，我很高兴你能带我来到这里喔。」

绿色草地上的她拖着裙子旋转了起来。长发、白银护胸以及腰上细剑「闪烁之光」剑鞘反射午后阳光的光景，美丽到似乎可以直接拿来当成游戏PV。

──虽然不是看透我的心思，不过亚丝娜面向我停下来后，就拍了一下右腰上的腰包说：

「对了，难得有这个机会，在这里拍张纪念照吧。我带了拍照水晶哟。」

「嗯……嗯嗯……说得也是……」

我虽然笑着这么回应，不过或许是从我的声音与表情里感觉到什么了吧，亚丝娜的脸上浮现出担心的神情。

「……房子不见了真的让你受到那么大的打击？」

「咦，没有啦，也不是这样……」

虽然我水平动着脸庞与双手，但亚丝娜脸上担心的表情还是没有消失。如此一来，已经不可能在内心粉饰自己的情绪，放弃挣扎的我只能点点头。

「那个……我今天本来有一些想法。但是现在这里没有房子就无法成立了……」

「咦？是什么样的想法？」

在大大的眼睛认真凝视下实在很难做出说明，但是都已经求婚了，现在才感到害羞也没有用。我轻咳了一声后，首先试着从系统方面开始说明。

「那个……SAO的『结婚』呢，以手续来说是相当简单。从主选单移动到沟通标签，按下在各种申请最下方的Marriage按键，然后指定对象……再来就只要等对方按下OK键就可以了。也不用跟公所提出书面申请……」

「也不用到女方家里去跟她的父亲说『请把女儿交给我！』对吧。」

亚丝娜唐突地加进这么一句话，让我忍不住想像起这种强制活动（而且不知道为什么，扮演岳父的是KoB的团长希兹克利夫），整个背肌开始发起抖来。看见这一幕的新娘子……不对，是亚丝娜就发出轻笑，于是我便再次刻意地咳了一声然后回归原本的主题。

「总……总之呢！结婚的手续本身只要五秒左右就结束了，那个，该怎么说……正因为这样，我才会一直想要完成一个让亚丝娜留下记忆的形式。但很可惜的是也不能盛大举行婚礼，所以才想说至少要购买新居，然后在那栋房子前面结婚是最棒了……」

后半段有些低头并且嘟嘟囔囔，但还是好不容易把话说完，接着我便呼出一口气。

下一刻，我就因为受到高速擒抱而脚步踉跄。意料之外的冲让我从背部倒到草皮上，但亚丝娜也没有从骑乘状态展开拳头攻击，只是把身体靠在我的胸口简短呢喃：

「…………好开心。」

「咦，没有啦，只是临时起意。」

「所以才开心啊。桐人如此替我着想，然后拼命地寻找我们两个人的家。」

一看之下，在至近距离露出满脸笑容的亚丝娜，双眼已经微微泛着泪光。这时我的胸口也有一阵情绪涌上来，于是以双臂抱住她纤细的身躯。

就这样在微风吹徐的草原上拥抱了两分钟以上，最后耳边又响起亚丝娜平稳的声音。

「我已经心满意足了。」

「咦……？」

「现在已经很幸福了。在这里完成结婚的操作，今天就回去吧？房子再找就可以了。」

为上层底部染色的午后阳光确实已经带着深黄色。再过一两个小时太阳就要下山了吧。

「说得……也是。」

我在抱着亚丝娜的情况下缓缓撑起身体，然后环视针叶树林中一大片绿色的庭园。

「盖在虽然是圈外但不会涌出怪物，而且人烟也不多的独栋房屋」，只要耐着性子寻找，一定还能找到其他满足这个条件的玩家房屋才对。也有干脆拜托情报贩子亚鲁戈这样的手段。我想就连那个「老鼠」，应该也不会把我们新居的座标卖给其他人吧，大概啦。

所以正如亚丝娜所说，没有必要执着于那栋梦幻圆木屋。这处草皮庭园就算维持现在这样也足以让人印象深刻，等哪一天SAO被完全攻略了──在这里结婚的回忆也会一直留在我和亚丝娜的记忆之中吧。

…………不过。

现在先别管这个了。我脑袋的角落一直有跟结婚无关的焦躁感盘踞着。真要形容的话，就像是记录视窗下方，进行到一半就停滞然后直接丢着不管的未完成任务。

「…………桐人？」

突然被叫到名字，吓了一跳的我把视线移回来。亚丝娜就在近处的脸庞，不知道什么时候浮现出「看透一切」的表情，让我的身体再次僵住。

「什……什么事？」

「…………你是在想『先别管房子』了对吧？」

惊。

似乎快要露出这样的表情，不过在千钧一发之际还是摆出一张扑克脸。

「咦，你……你在说什么啊？」

「你想找出原本在这里的房子消失的理由，这种小事不可能瞒得过我哟。」

──看来我没有装扑克脸的才能。由于学乖的我知道这时候否定也只会加深伤口，所以这次也轻轻点头并且说：

「嗯，那个，是的……因……因为实在是太不可思议了，玩家房屋竟然会消失。刚才亚丝娜提到可能是系统上的问题，但是SAO没有GM，所以管理者不可能亲自动手撤走房屋。就算是程式处理的结果，耐久度无限的房子应该不会腐朽才对，艾恩葛朗特也不会有地震或者森林大火……要说还能想到什么其他的理由……嗯～～…………」

由于我在讲话当中就快要进入正式的推理模式，这时亚丝娜就伸出食指来严厉地贴在我的嘴巴上。

「好了，暂时停止！嗯……都跟你认识这么久了。我早就学会桐人是没办法放着这种事情不管的人了……」

在轻声叹息尚未结束前，我就擅自解除了暂停。

「那……那么，虽然是在贵重的休假当中，是不是可以让我……稍微调查一下呢？」

亚丝娜小声地说着「我就知道会变成这样」、「主题整个改变了啦」等抱怨，然后才用力吸一口气，开口宣布：

「调查期限只有今天一个晚上而已喔！」

4

配置在艾恩葛朗特各层的无数地形物件，其百分之九十九以上都拥有「不可破坏<Immortal>」属性。除了树木之外的自然物、以家屋与城墙为代表的人工物等等，玩家全都无法刻意加以破坏。

虽然跟迷宫内部的设计也有关，不过里面时常会出现「能打坏的墙壁」，练功区里偶尔也会有「能打破的岩石」与「能挖掘的地面」，不过从来没听说过有「能打坏的房子」。说起来，买下能够破坏的房子那一天，就可能发生睡眠中墙壁突然开个大洞，然后大群盗贼公会的成员闯入的事件吧。又不是在演《三只小猪》。

因此我过去发现，梦想着将来要买下来当自己家的圆木屋，首先可以排除是被玩家动手破坏的可能性。

「……嗯，我也这么认为。」

听我推测到这里后，亚丝娜就点点头并且加了一句：

「没有发现特别技能『炒地皮』的话。」

「在……在这种地方炒地皮也没用吧。如果是塞尔穆布鲁克的湖畔也就算了。」

「啊～那边的湖畔确实很贵。大概是我那个房间的三倍左右……不过，对了，如果没办法找到这里的房子，那就在那边盖一栋新家吧。」

「凭……凭我的收入……可能有点……」

对铁青着脸的我说着「开玩笑的啦」并且笑了一阵子后，亚丝娜才恢复原本的表情。她有些进入攻略组的指挥官模式，一直凝视着空地。

「那么就排除被某个人弄坏的可能性吧……先确认一下，外墙和屋顶不包括在玩家房屋的客制化机能内吧？」

「咦……你的意思是？」

「就是买房子后，不是会有屋主专用的客制化选单吗？从那里的话，可以消除设置在里面的家具对吧？」

终于理解亚丝娜言外之意的我，点了点头表示「原来如此」。

「这样啊……其他的玩家买下那间房子，以客制化选项消除墙壁、屋顶和地板的可能性吗？嗯……我只住过公寓那样的地方，所以没看过独栋房子的客制化选单……」

「其实我也一样……对了，问问看莉兹吧。」

亚丝娜迅速打开主选单，接着快速打着传给好友铁匠莉兹贝特的讯息。

莉兹和我也很熟，而且也是帮忙打造爱剑逐暗者的恩人，所以是少数在亚丝娜和我结婚一事通知名单上的玩家之一。今天在这里买下房子并且结束结婚操作之后，原本预定要传讯息给包含莉兹在内的十几名玩家──没想到会变成向她询问住宅相关的问题。

回答似乎立刻就传了回来，亚丝娜看着只有她才能看见的视窗，然后轻轻点头说：

「外墙和屋顶果然没办法消除和移动。花大钱的话好像可以改变颜色或者是追加外窗、花坛这样的选项……」

「……说是改变颜色，应该没办法把整栋房子变成无色透明吧。」

而且最重要的是，我和亚丝娜已经把这块空地走遍了，也确认过没有留下任何痕迹。真的盖了一栋透明房子的话，我们的鼻子早就撞上去了。

「那么……是选项的问题吗？比如说有潜入地面的设备……之类的？」

亚丝娜这么说着，同时还用靴子的前端戳了一下脚边的草地，于是我便忍不住露出苦笑。

「哈哈，又不是什么邪恶组织的秘密基地。说起来呢，要是在艾恩葛朗特的地面挖个能够埋起整栋房子的大洞，那房子会直接掉到下一层去吧。」

「咦～那不是很棒吗？像哈比人的家那样。」

「那确实是在山丘侧面挖掘洞穴……地下的话应该是矮人吧？对了，十几层那边不是有个的矮人族巨大地下城吗？」

「我讨厌那个地方。不但潮湿，又有许多虫系怪物出没……说起来那个地下城实际上也是在练功区山地的内侧吧。」

「那就是艾恩葛朗特在构造上的缺陷啊～因为地面的厚度有限，所以没办法制作作为RPG醍醐味的巨大地下迷宫。」

「那种东西没有也没关系啦！倒是……真的可以继续闲聊吗？我是觉得很开心啦。」

在亚丝娜的提醒下，惊觉过来的我立刻看向外围部。破碎的云缓缓流过的天空已经变成相当深的橘色。再过两个小时太阳就要下山了吧。

「对……对喔，那个……如果不是透明化或者秘密基地化，再来就是……移动基地化？不可能，有那种选项的话就能从主街区轻松移动到迷宫区了……这么说来，也不可能是空中要塞化了……」

我逐渐从推测进入妄想的发言，让受不了的亚丝娜抬头仰望天空。我则是与她相反，整个人深深低下头，双手抱胸并且拼命思考。

「不像是利用客制化机能而消失。说起来，那样房子就已经被其他玩家买走了……果然是跟玩家没有关系的现象吗……」

「…………嗳。」

「如此一来……是具备地形物件破坏能力的练功区魔王……？等等，连第五十六层的『土地爬行者<GeoCrawler>』都没办法破坏村门了。第二十二层要是出现这么厉害的魔王，马上就会开始招募讨伐联合部队了吧……」

「我说桐人啊……」

大衣的袖子被拉了两下后，我便停止推测看向亚丝娜。

「……什么事？」

「…………那个……」

由于亚丝娜抬起戴着白色长手套的右手，我便顺着她食指的延长线看去。

空地北侧那棵特别大的杉树正上方，就存在着她所指的那个物体。

轻轻飘浮在几乎快接近上层底部的一栋房子──从地上的话因为角度的关系几乎只能看见底部，但是由上好圆木组合起来的构造，绝对就是我在找的那栋房子不会错了。

在我尚未因为如此简单就找到房子而感到喜悦之前，就先对它浮游在头上九十公尺处而惊讶不已，这时愕然的我呢喃了一句：

「…………为……为什么……房子会飞起来…………」

「…………应该不是刚才桐人说过的……空中要塞选项吧……」

亚丝娜的话让我凝眼望着豆粒般房子的各处，但是没有看到装有翅膀、气球或者螺旋桨的模样。

相对地，我经由技能强化过的视觉，发现了两个之前没有注意到的事物。

首先是房子下端有热气般晃动的空气漩涡。那栋圆木屋应该是乘着「固定的龙卷风」之类的东西而飞上天了。

然后还有另一个物体。

某个人从房子的南侧窗户畏畏缩缩地探出一张脸，然后拼命对遥远下方的我们挥手。

「有……有人！」

我用手指向该处后，亚丝娜也发出「咦」一声并探出身体。

「真……真的耶……这种距离看不出是NPC还是玩家……」

能够确实辨别玩家与NPC的外表差异就只有「颜色浮标」的颜色而已。但是距离这么远的话浮标不会显示出来。

虽然还是完全搞不懂房子为什么会飞上天，但那道人影如果不是NPC而是玩家的话，就不能丢下他不管。因为万一从那种高度掉下来，HP绝对会归零。

「到……到底是哪种身份……」

在我和亚丝娜吞着大口口水仰望之下──

突然间人影缩回挥动的手，然后立刻再次伸出来。放开握在手上的某种东西，接着该物体就反射着闪亮的黄色阳光。它画出平缓的弧形，朝着我们所在的空地落下。

「哎……哎呀……」

我往右跑四步、往前跑三步，然后双手接住来到掉落地点的小小物体。由于亚丝娜也立刻跑过来，所以就两个人一起窥看该物体。

「回复药水的……空瓶……？」

点头同意亚丝娜的话后，我再次仰望浮空的圆木屋并且大叫：

「──是玩家！」

喝光POT内容物后的空瓶，直接放着不管的话马上就会破碎并且消失。为了防止这一点，要把「空瓶」作为道具保存下来，就必须把它收进包包类或者是道具栏里。由于NPC不会做出这种行动，持有空瓶就表示被关在那间飞天屋里头的是玩家。

「得……得救他才行……」

右手依然握着小瓶子的我一这么说，亚丝娜就立刻反问：

「怎……怎么救？」

「………………」

这是个非常之好的问题。艾恩葛朗特，不对，SAO里原则上不存在飞天的手段。因为如果有那种手段的话，就能够无视迷宫塔直接飞到下一层……不对，是直接飞到最后终点，也就是一百层去了。

数个月前，我和亚丝娜刚才传讯息的对象铁匠莉兹贝特有过一起抓住白龙尾巴飞翔的经验，但是那无法选择目的地，而这一层也没有龙出没，最重要的是我再也不想有那样的经历了。

「…………总……总之先到那栋房子的正下方看看吧。」

听见我含糊的提案后，亚丝娜稍微露出微妙的表情，但立刻就点头同意。

从空地踏入森林后，上空层层堆叠的树枝就阻碍视线让人看不见飞天房屋，但我随即发挥系统外技能「第六感之直线移动」来笔直地前进。在看不见远方目标的森林里，这其实颇为困难。秘诀是让两只脚像是自动奔跑一样动作……以前这么跟亚丝娜说明时，她的脸上就露出「这家伙在说什么啊」的表情。

我的瞄准完全正确，短短两三分钟前方就出现一棵特别巨大的杉树。那无疑就是长在房屋正下方的树木了。一边走近一边抬头往上看，透过重重相叠的树枝后可以看到轻飘飘浮在空中的豆粒大小屋影。

「……现在该怎么办？就算爬上这棵杉树，也完全无法抵达那栋房子喔。」

听见边往上看边走的亚丝娜这么问，我便以同样的姿势回答：

「原本是想来到正下方的话，应该能听到一点叫声才对……不过看来是没办法……」

「对喔，能够对话的话，就能请对方说明是怎么回事了。那还是爬树看看吧？在树梢上可能就听得见叫声了。」

「但是要爬上这种针叶树的难度相当高……没有『特技』技能可能办不到……」

在仰头的情况下，来到距离杉树剩下五公尺左右的距离时。

突然从至近距离传来怪物般的咆哮声，我和亚丝娜就跳了起来。

「汪、汪汪汪！」

反射性握住背上爱剑阐释者的剑柄，但动作就此停了下来。因为吼叫声的主人是全长最多四十公分左右的四脚步行兽类……具体来说也就是「狗」。

稍长的毛是淡茶色，有着一双圆滚滚的眼睛，再加上绑有蓝色缎带的毛绒绒尾巴。颜色浮标是黄色──是给予NPC﹑驯兽师的宠物，或是不具攻击性的非主动怪物的颜色。

「哇啊，好可爱！」

看见亚丝娜叙述着符合年轻女孩身份的感想并且蹲下来朝狗伸出手，我便急忙制止她。

「等……等一下等一下！」

「为什么，它明明这么可爱。」

「说……说不定是某种陷阱啊！说起来呢，练功区里有狗实在太奇怪了。触碰到的瞬间就变形成恐狼怎么办？」

「别担心啦，你看它尾巴都摇成这样了。」

──当我们进行这样的对话期间，小型犬也持续在亚丝娜面前又叫又跳，像是在表示「快抱我快抱我！」一样。亚丝娜再次想屈身时，我就拉住她的剑带并且再次确认小狗的浮标。上面显示的名字是「Toto」。

「……托托？不是种族名吧……是这只狗的专有名称吗……？」

「哇，名字也好可爱！来，快过来吧，托托！」

「都说不行了……」

我拼命把已经像是中了魅惑异常状态般的亚丝娜拉回来，同时试着分辨小狗，也就是托托圆滚滚的眼睛里是不是藏有邪恶的企图。

然后迟了好一会儿才发现，小狗圆滚滚的头上二十公分处浮着一个小小的「？」符号。

「那是……任务符号？但是，为什么是在进行当中……？」

我一这么大叫，亚丝娜也像是注意到符号一样放慢了前进的速度。

「真的耶，有任务符号……」

艾恩葛朗特的各层里配置着实在难以全部完成的任务。通常可以向头上浮着「！」符号的NPC承接任务，与进行中的任务有关的NPC，头上符号则会变成「？」

也就是说这只小狗是进行中任务的关键人物，不对，应该说是关键动物。但问题是……我没有，亚丝娜应该也没有接到与狗有关的任务才对…………

「对……对了！」

亚丝娜突然这么大叫，让我吓了一跳并且放开她的剑带。细剑使转头过来以严肃的表情凝视着我，然后开口继续说：

「我们平常都把时间耗在迷宫区与楼层魔王攻略上，没什么在承接副本对吧？所以才会成为盲点。发生什么无法说明的情形时，原因通常是因为任务喔。比如说……房子飞上天之类的！」

「…………原来如此。」

由于认为是相当有道理的推论，我便点头同意，结果亚丝娜再次反转身体面对持续吠叫的小狗。

「也就是说，想要找出那栋房子飞上天的原因……就必须跟这只小托托接触才行！桐人你应该可以理解吧！」

丢出这种听起来很像充满冒险心与自我牺牲的发言后，亚丝娜就在我来不及再次抓住她前蹲下来并朝小狗伸出双手。

「汪汪汪！」

茶色小型犬随着听起来很开心的叫声跳进亚丝娜胸口，高速摆动尾巴并且不停舔着她的脸。

「啊哈哈，好痒喔！啊啊～真可爱！我原本就梦想养一只这样的小狗了！」

──幸好托托没有突然变成巨大的食人狼。

但是数秒钟后发生的现象，完全领先我的预测三光年左右。

突然我和亚丝娜脚边开始有风卷动。根本无暇抵抗强大的风力，身体就失去了平衡。因为脚步踉跄而离开地面──恐怖的是，不论怎么伸展都无法接触地面了。

「桐……桐人！」

我反射性握住亚丝娜在右手抱着托托的情况下朝我伸出的左手。两人一犬就这样被局部的龙卷风往上卷。周围的景象不停旋转，我的大衣与亚丝娜的迷你裙整个翻起（平常在练功区吹动的风绝对不会引发这种现象），但是根本没有多余的心思去注意这件事。

就在我发出「呜……呜哇……呜哇哇哇～～～～」的叫声……

亚丝娜发出「呀啊啊啊啊────」的悲鸣……

小狗很高兴般「汪汪汪！」叫着的瞬间。

我们就一直线朝着浮游在遥远上空的圆木屋飞去。

插图p044

5

「……你……你们也跑来这里的话就没意义了吧！」

这就是在圆木屋里等待救援的玩家所说的第一句话。

大约九十秒前──

被小型龙卷风吞没的我、亚丝娜以及小狗，暂时飞到浮空圆木屋的屋顶后，就排成一列被在角落张开嘴的烟囱吸了进去。经过又窄又暗的隧道后，一屁股坐到由白木板所组成的宽敞客厅地板上，这时有一名女性玩家露出惊愕的表情站在我们面前。

我好不容易才让大吃一惊而停止转动的脑袋再次运作，保持坐在地板上的姿势仔细凝视着先到此地者的脸。惊人的是那是我相当熟悉的脸孔，但是也没有再次露出惊愕表情的气力，于是就先试着向对方打招呼。

「午安。好久不见了。」

刚才的叫声就是对应我的招呼。事情的经过就是这样。

不论如何，还是先交换情报吧。

女性玩家垂下肩膀同意我这样的提案，然后用右手指向设置在客厅地板上的圆桌。我和抱着狗的亚丝娜并肩坐下后，她也拉大距离坐到我们对面。

这时候亚丝娜似乎也终于回归平常模式，对着我们都认识的女性玩家点了个头。

「好久不见了，亚鲁戈小姐。」

「……哈啰，小亚。顺便也跟桐仔问个好。」

以微妙表情轻轻挥着手的玩家，左右脸颊上以颜料各画着三根清晰的胡子。死亡游戏开始后大约两年，不对，包含封测的话还要再加一个月的时间里，一直都贯彻这种脸颊彩绘的她名字是「老鼠亚鲁戈」。她是艾恩葛朗特里拥有最高超技术的情报贩子。

我和亚丝娜从游戏初期就跟她有交集，向她购买、贩卖情报的次数已经数也数不清。除此之外也因为种种原因而互相帮助，而且我不记得跟她有过明确的敌对关系。所以亚鲁戈事到如今才像是警戒着我们般的态度实在让人纳闷，不过我还是决定先别管这件事，直接进入正题。

「……那么，亚鲁戈，这个到底是什么？」

提到「这个」时，我就轻轻转动右手，边指着目前依然飞行中的圆木屋全体并这么问道，情报贩子就眨了眨金褐色卷发底下的双眼。

「还问是什么，既然都来到这里，就表示桐仔也接了吧？当然是任务啦！」

「啊……噢……嗯……」

瞄了一眼被抱在亚丝娜胸口，目前正开始打瞌睡的小狗后，发现它头上的「？」依然亮着。那就表示某种任务仍在进行当中──

「但是，与其说是明确地承接了任务，倒不如说是被牵连了……」

我一这么说，亚丝娜就轻轻点头。

「是啊。我光是把这孩子抱起来，就被吹到这栋房子里面了。怎么说呢……就好像是……捡到某个人进行到一半就丢下的任务……」

她说到这里就倏然闭起嘴巴，然后跟我面面相觑。我也立刻了解她到底在想些什么。

如果是「某个人进行到一半就丢下的任务」造成现在这种状况，那么「某个人」绝对就是眼前的老鼠亚鲁戈了吧。

同时被我跟亚丝娜瞬移过去的视线盯着看后，亚鲁戈像是放弃挣扎般缩起脖子说：

「…………我从头开始说明吧。」

──我接到最近艾恩葛朗特的低楼层里出现好几个奇怪新任务的情报。像是不论打倒多少次都会重复涌出的蒙面食人鬼、一边旋转跳跃一边吐火的陆龟、从诅咒的讯息视窗里爬出的白衣女僵尸之类的。

在快要发行「全任务必胜导览手册」之前，我必须立刻网罗这些新任务的情报。所以我前天就到据说有新任务的第二十二层西南区域来调查，虽然顺利找到任务开始的地点，但是任务的内容就有点问题喽。没有带着故事进行所需的关键角色就冲进这栋房子里，房子就突然被龙卷风吹起来，让我吓了一大跳！之后整整两天，我都待在这栋飞天房子里等待有人来重置任务。

说明到这里，亚鲁戈就像很无奈般摊开双手。

所谓「任务重置」，是指利用选单操作来将进行中但长时间遭到放置的任务回归初期状态。由于SAO里有不少不能同时跟其他玩家一起承接的任务，所以准备了这样的机能。当然，必须要靠近成为任务起点的NPC才行。

也就是说，在那棵杉树底下发现名为「托托」的小狗时，注意到它头上的「？」就打开主选单的任务标签──那里或许就存在重置键。但是像现在这样加入进行中的任务之后，我和亚丝娜也没办法重置任务了。

「……嗯，大概可以了解状况……但还是充满谜团。亚鲁戈，你刚才说的『任务内容有问题』是指什么？」

我指出理所当然的疑问后，情报贩子再次露出之前那种微妙的表情，瞄了一眼亚丝娜的……正确来说是在亚丝娜怀里睡觉的小型活动物体。

「这……这个嘛……我也有个人的喜好呀……」

「噢，原来是这样！亚鲁戈小姐不喜欢狗吗！」

由于话说到一半就被亚丝娜笑着识破内心，情报贩子便缩起两颊的三根胡须。

「有……有什么办法嘛，只有这一点一直是初期能力值！说起来我也得到小亚你会害怕不死系Mob的情报了哟！」

「那……那是鬼魂吧！会害怕鬼魂本来就是理所当然的事。但是小狗很可爱吧？来，要不要抱抱看？」

「快……快住手！让它继续睡啦！」

──不理会上演这感情良好一幕的亚鲁戈和亚丝娜，我开始思考了起来。

亚鲁戈（明明是「老鼠」）不喜欢狗，而那只狗头上的任务符号依然亮着，这就表示……

「喔～原来如此。亚鲁戈，你虽然开启了任务，但是没有带着关键角色小狗就发挥所有AGI迅速逃走冲进这栋房子，结果房子因为任务进行而飞上天，但狗却无法进入房子内，任务进度就整个停滞了，你也被关在飞天房子里整整两天……事情就是这样吗？哈哈哈，你也有许多欢乐的经验耶。之后把经验谈集结成『亚鲁戈的大冒险』这样的书籍应该能赚一笔喔。」

我边笑边这么说，老鼠一瞬间露出「真的能赚吗？」的表情，然后才大叫：

「这有什么好笑的！事到如今，桐仔和小亚也要被关在这栋房子里一段时间喽！」

「太夸张了啦，真不行的话就用转移水晶移动到某个城市里就可以了吧。」

如此回答完就准备再次发笑时──亚鲁戈和亚丝娜就同时露出微妙的表情。以眼神互瞄了一眼后，亚丝娜就作为两个人的代表开口说道：

「……那个，桐人。我觉得亚鲁戈小姐不可能没试过这个办法。」

「咦？」

「虽然会因为任务而有所不同，不过像这样的强制任务当中，大致上都是禁止转移的喔。我没说错吧，亚鲁戈小姐？」

「那还用说吗！」

「…………真的假的？」

面对迟了一会儿才开始冒出冷汗的我，亚鲁戈露出了无奈的表情并且回点了一下头。

「嗯，最后的手段就是从窗户跳下去，在快撞上地面之前才用水晶转移到别处……不过实在不想尝试呀～」

「我……我也不想试……」

我瞄了一眼窗外广阔的天空后，开始有点太迟的思考。

说起来，这到底是什么样的任务？在森林里从小狗那里承接任务，和它一起进入房子后，房子就被龙卷风吹走？从这点来看，故事完全没有脉络可循。SAO的伺服器营运应该已经不属于作为开发企业的ARGUS，创作任务剧本的不可能是ARGUS的员工。那么如此不合理的发展到底是谁想出来的呢？然后在依然无法使用呼叫GM机能的情况下，我们到底该如何脱离这种状况……

「…………呃，不对，等等喔。」

我的话让摸着托托头部的亚丝娜，以及用警戒视线看着这边的亚鲁戈同时转动头部。

「如果这个任务停滞的原因，是因为狗……托托被留在地面上的话，现在这个问题应该解决了……这就表示──任务应该再次开始进行了吧……？」

「啊……！」

亚鲁戈啪叽一声打了一个响指，以敏捷到极点的动作跑向窗户，一往地面看就大叫：

「在……在动了哟！应该说，马上就要着陆了！」

「真……真的吗？太好了，在变暗之前能回去了。」

亚丝娜也走向窗户，以安心的表情这么说道，但我实在无法像她那么乐观。可以说是第六感使然吧。

以任务的导入来说，整间房子飞上空中算是相当大的场面。我不认为有如此盛大开场的故事，会这么简单就结束。恐怕……会一直持续「到那里去找什么」、「到那里去帮助谁」这样的发展。说起来呢，就算努力完成任务，也无法保证这栋房子能变回原本销售中的状态。如此一来，我和亚丝娜到底什么时候才能结…………

「呜！」

我发出低沉的呻吟，看向与亚丝娜（怀中的小狗）保持微妙距离的亚鲁戈娇小的背部。

虽然她是老交情的朋友了，但是不能提前被她看出我将和亚丝娜结婚一事。一旦被发现，最后一定会大大地刊登在「亚鲁戈周报」上，然后我将会被亚丝娜粉丝俱乐部的众成员诅咒到死。

如此一来，一起进行漫长的游戏攻略就很危险了。必须迅速完成攻略，在「老鼠」的嗅觉发觉什么之前就先跟她说「辛苦了！」才行。

在我下定决心而起身的同时，圆木屋就发出「滋滋嗯」的沉重声音，在某个不知名的地点着陆。

6

「……话说回来，这个任务的名字叫什么？」

听见我的问题后，亚鲁戈就打开视窗回答：

「叫作『西方魔女与三个秘宝』。」

「……真是普通。故事发展明明如此奇特……」

稳稳踏上对亚鲁戈来说隔了两天，对我和亚丝娜来说隔了十五分钟的地面后，下一个关键角色就在我们三个人面前摇晃着身体。

但是那家伙依然不是人类。那是由木棒组成十字的胴体，以及把物体塞入麻布后制成圆脑袋的人偶──也就是稻草人。虽然外表滑稽，但它是怪物的事实依然没有改变。属于恐怖系楼层里经常会配置的「威吓物」系Mob。

出来迎接的还不只有稻草人。左侧有一个全身铠甲内中空的「活铠甲」系怪物，然后右邻是人的身体上有一颗狮头的「狮面人」系怪物。三只怪物都没有发动攻击的迹象。颜色浮标也是显示非主动状态的黄色。

当我浮现「究竟是怎么回事」的想法时，稻草人突然开口说话了。

「喔喔，我们等好久了！」

配合这句台词，飘浮在稻草人头上的「！」就变成显示任务进行中的「？」。而小狗头上的符号则同时消失。

「你说……等很久了？」

我还是做出符合现状的回答，结果稻草人就更激烈地摇晃着头并且猛然开始说话。简单说来就是以下的内容。

──我们「稻草人」、「锡人」、「狮子」为了成为人类而旅行，途中我们的女伙伴被「西方魔女」抓走了。虽然想救她，但是稻草人的脑袋、锡人用来代替心脏的宝石以及代表狮子勇气源头的金色鬃毛被魔女夺走而无法战斗。这时候为了招募愿意一起跟魔女战斗的剑士而对女孩饲养的狗「托托」施加龙卷风咒语，然后把它送到墙壁外面。

「哦……哦哦……原来如此……」

我点点头后瞄了背后一眼。

根据地图，目前的所在位置是同为第二十二层的西北部。这里是被垂直耸立的悬崖包围，徒步不可能进入的区域。稻草人所说的「墙壁」，指的就是那面断崖吧。

虽然好不容易掌握任务的设定，但依然感觉整体来说是很奇怪的故事。说起来，在不存在魔法的SAO里出现「魔女」、「龙卷风咒语」之类的东西就很有问题了。而且稻草人和狮子也就算了，为什么活铠甲的名字是「锡人」呢？

──当我被这种说起来无关紧要的问题所困扰时，身旁的亚丝娜突然呢喃了一句：

「……我知道这个任务究竟是怎么回事了。」

接着亚鲁戈也点点头。

「我也知道了哟。所以房子才会飞起来。」

「咦？到底是怎么回事？」

从左到右依序看过去并这么问完后，亚丝娜就一边露出灿烂的笑容，一边说出完全出乎意料的发言。

「我想桐人你小时候应该也看过。虽然细节有许多地方不同，但这个任务……是根据《绿野仙踪》这个故事喔！」

「……啊……啊啊，原来如此！」

嘴里虽然这么大叫，不过老实说我无法想起整个故事的内容。身为主角的女孩子跟饲养的狗连同房子一起被龙卷风吹走，结果掉落在异世界，带领着稻草人、锡人以及狮子一起展开各种冒险的旅程，最后再次回到现实世界──故事应该是这样，大概啦。

了解这一点后，就能接受活铠甲为什么叫作「锡人」了，但是接下来的发展也让人感到非常担心。

「……如此一来，这个任务会非常之长吧……」

混杂着叹息这么说完后，亚丝娜就露出「为什么？」的表情，我便耸耸肩继续表示：

「因为以故事来说，接下来必须依序取回稻草人的脑袋、锡人的心脏和狮子的鬃毛吧？每一个都不知道要花几个小时……」

我一这么抱怨，亚丝娜和亚鲁戈就面面相觑，然后不知道为什么满面盈笑。

「桐仔，我看你是记不清楚整个故事了吧？」

「呜……嗯，是没错啦……」

「呵呵，我认为不用收集关键道具喔。直接跳过这些过程，立刻冲到魔女的城堡去吧！」

「咦……咦咦咦？」

配合我的叫声，感觉稻草人、锡人和狮子也露出「咦咦咦～」的表情，但那应该只是我想太多吧。

再次确认地图之后，椭圆形任务区域里标示了三个金色的「！」符号（接下来的目的地），其他还有一个灰色的「！」符号（虽然是最终目的地但是旗标尚未立起）。一般来说，不攻略三个金色符号就算前往最终目的地也没有用，但亚丝娜和亚鲁戈的脚步没有丝毫犹豫。

面对快步走在黄色砖瓦道路上的两个人，三名想成为人类的怪物和我只能踩着不安的脚步追上去。亚鲁戈之所以隔着微妙的距离，是因为亚丝娜怀里还抱着小狗的缘故吧。

头上的任务符号既然已经消失，托托应该就不是关键角色了，于是我和亚鲁戈就提议把它放在圆木屋里。但是亚丝娜却依然紧抱住小狗，眼睛往上看并且不断发出「呜呜～」的奇妙声音，所以也就没办法继续要求她这么做。老实说我根本不在乎带不带小狗，但是对于讨厌狗的亚鲁戈来说，精神上多少会受到折磨。

既然做到如此彻底，一定就跟她本人所说的一样，并非只是限定于这个世界的角色扮演。现实世界的亚鲁戈一定也不喜欢狗。但如果我是她的话，能够像那样老实地表现出自己的内在──真实的一面吗？或许会为了维持在这个世界里构筑起来的多重印象而强行压抑感情，努力装出不在意的模样吧。

这样的我，对于亚丝娜抱持的感情，真的能称为爱情吗…………

「…………你觉得呢？」

我以极小的声音对走在旁边的其中一名任务NPC，也就是被夺走「勇气」的狮子男这么问道。

配置在艾恩葛朗特内的无数NPC们，几乎都只会遵从演算法来重复事先输入的应答格式，和玩家之间的对话不可能成立。所以我也没有特别期待能获得回答。

「……你也被夺走什么了吗？」

由于狮子男细声这么反问，让我有点……不对，应该说相当惊讶。

「嗯……或许是吧。我在来到这里之前，不记得曾经真心喜欢上哪个人。」

一时兴起这么回答完，跟原本在四十层附近出现的狮面人族相比，外表显得十分寒酸的狮子男，这时脸上就露出更加悲伤的表情并且点了点头。

「这样啊。其实我也没有自信，不知道被魔女抢走鬃毛前的我是否真的拥有『勇气』。」

狮子男叹了口气并且垂下头，就看到后脑勺的一部分鬃毛像被推剪器直向推过一样完全消失不见。

特别仔细看之后，发现狮子男旁边跳着走路的稻草人，后脑勺有一处被撕裂然后随便乱缝起的针脚，他对面那个锡人的胸甲上也用OK蹦打了个叉来塞住巨大洞穴。应该全是「西方魔女」从他们那里夺走重要物品的痕迹吧。

当然我不记得曾被魔女夺走「爱别人的心」。如果在哪个地方弄丢了那个，也是从小就持续跟周围的人……甚至连家人都保持距离的我自己应该负的责任。

如此一来，我该去哪里找回那颗心呢？和亚丝娜结婚并且一起生活就能找到吗？但是如果正如狮子男所说，我这个人打从一开始就没有那种东西呢……？

就在这个时候，宛如感觉到我的不安一般，走在数公尺前方的亚丝娜回过头来。稍微歪了一下头后，脸上浮现跟平常没有两样的笑容。以抬起的右手显示前进方向，然后朗声叫道：

「看呐，桐人。已经看得到了！」

亚鲁戈立刻用装备在双手上的金属爪互相撞击了一下。

「既然是我不知道的任务，绝对是尚未有人进入的迷宫！里面有许多还没被开启的宝箱哟！」

「……我说啊，就算这样这里也只是第二十二层，一定没有什么大不了的宝物啦。」

我中断不符合性格的反省，为了追上两个人而加快脚步，同时抬头看向逐渐出现在树梢后方的城堡。好几座看起来特别细长的塔往上延伸，墙壁是接近黑色的灰色。以泛红天空作为背景耸立在该处的模样，确实散发出符合「魔女城堡」的气氛。

打倒待在最深处的魔女就算攻略这个任务了，但现阶段应该无法入城吧。按照常识来说，不解决稻草人、锡人、狮子被夺走的心等各地的副本，最终迷宫的门就不会开，或者魔王就不会涌出。不对，更重要的是，像这样无视三个人寻找的物品，感觉他们三个人有点可怜……

当我这么想的时候，亚丝娜和亚鲁戈依然在维持微妙间隔的情况下持续往前走，短短几分钟后前方就出现吓人的城门。高五公尺的黑色铸铁门扉紧紧关闭，果然没有打开的──

喀哩喀哩喀锵。

持续传出明确的开锁声，门也自动往左右两边打开，于是我只能张大嘴巴。亚丝娜怀中的小狗虽然不停汪汪叫，但应该不是这家伙把门打开的吧。

两名女性玩家像要表示「果然如此」般互相点了点头，但我还是搞不懂究竟是怎么回事。和脑袋、心脏以及鬃毛被抢走的稻草人等一行人面面相觑，耸耸肩后就踏入大门内部。

下一刻就传出凶暴的低吼声，四只怪物从城堡的前院涌出。那是巨大身体上有着黑豹头颅的豹人族。如果魔女是驱使黑猫的话，那么它们也算是合适的守门人了……大概啦。

「嘎哦哦哦哦呜！」

当黑豹们先叫了一声，然后拔出锯齿状刀刃的圆月刀时，稻草人等三个人就发出「咿咿咿」的丢脸悲鸣并且蹲下。不知道是陷入「恐慌」的异常状态或者只是真的感到害怕，虽然原本就不期待他们的战力，但一开始就这样的话，之后的魔王战就更令人担心了。

我不停摇头并且拔出背后的爱剑阐释者，同时以两只从右侧突进的豹人为目标。发动单手剑中少数单发．范围攻击型剑技「锯齿波浪」。

朝地面挥落的剑因高周波而振动，宛若锯齿刀刃般的特效光呈放射状扩散。两名豹男被光线淹没，脚步因而不稳。这招原本就是用来妨碍移动的剑技，造成的伤害不会太大，但对方不过是第二十二层的任务出现的怪物。在恢复体势之前HP就归零，接着黑豹们就依序爆散。

剩下的两只也被左手依然抱着小狗的亚丝娜，以及一对一其实相当强的亚鲁戈秒杀，战斗就此结束。一只豹人掉下带有任务道具符号的钥匙，我们便用它打开城堡本体角落的一扇小门。

钻过门前再次看了一下天空，发现朱色里已经开始混入紫色。距离夜晚只剩下一个小时左右了吧。由于城堡相当大，想在日落之前完成攻略看来很困难了。

──或许是再次看出我这样的思绪，亚丝娜拍了一下我的背部并且说：

「别担心，我带了很多便当来。」

呃，我不是在担心晚餐，只是在想能不能在今天之内结婚。

但是又不能这么回答，只能以微妙的角度点点头，这时候亚鲁戈以悠闲的声音说道：

「那真是令人期待！我确实掌握到小亚开发出酱油的情报了哟！」

冲入「西方魔女」的城堡后仅仅十分钟。

我、亚丝娜、亚鲁戈、稻草人、锡人、狮子以及小狗的六个人＋一犬的小队轻松到达应该是魔王房间的大门前。

当然也跟战力远超出任务的合适等级有关，不过特别犯规的应该算是亚鲁戈的机动力。原本应该绕远路才能爬上去的露台，或者连我都要犹豫该不该跳的狭窄立足点都轻松地直接跳过去，可以说疯狂地抄捷径。托她的福，从狭窄的窗户窥看到的天空还留着夕阳的残红。

「……等魔王战之后再吃便当吧。」

亚丝娜以有些难以置信的声音这么说完，亚鲁戈也一脸轻松地点头回答「说得也是」。虽然怪物三人组依然露出烦恼着这样真的没关系吗的表情，最后由稻草人代表众人跳出来前面，动着以单缝线缝在麻布头颅上的嘴。

「……『西方魔女』会使用许多恐怖的咒文。要不是我的脑袋变空了，就能想起咒文的种类了……」

……果然该从副本开始解决起吧。我虽然这么想，但亚丝娜却以冷静的模样拍了一下稻草人的肩膀（应该说是棒子）。

「别担心，只要你们三个人同心协力，一定能救出桃……你们的女性朋友。好了，我们走吧。」

话一说完就飒爽地转身，毫不犹豫地推开大门。

门后面是相当符合魔王房间气氛的长方形巨大空间。我们一踏进去的瞬间，高大天花板的水晶灯就亮起不祥的绿色烛光。从眼前到深处逐渐变得明亮，可以看到靠近正面墙壁处设置了巨大的铁牢。

铁牢里有一名被捆绑的女孩子躺着──她的旁边有一个内容物沸腾的大锅，以及用长柄锅勺搅动滚烫内容物的黑衣老太太。

「喔喔……完全符合巫婆形象的巫婆……」

我忍不住开口做出这样的感想。SAO原则上不存在攻击魔法，理论上来说也就不存在魔法师，所以这种外表的怪物算是相当稀有。

那么，那个老太太会发动什么样的攻击呢？当我这么想时──稻草人就突然大叫：

「啊啊，桃乐丝小姐！这样下去的话桃乐丝小姐会被煮成汤的啊！」

接着锡人也让铠甲的零件发出声响。

「桃乐丝、危险、快点、救她！」

最后狮子也奋力竖起一部分被剃掉的鬃毛。

「等等啊，桃乐丝！我们现在……我们现在…………」

但这时狮子的鬃毛就垂了下去，锡人的铠甲变得沉默，支撑稻草人的棒子产生扭曲。

代替陷入沉默的三人组，我、亚丝娜和亚鲁戈来到前面。我们慎重往侧脸朝向这边，依然不停搅动大锅的魔女靠近。

当小队来到大房间的中间地点时──

黑色斗篷的魔女抬起头来看向这边。发出黄光的双眼整个眯起，以尖锐的声音呢喃：

「你们也想喝这个女孩煮成的汤吗？喝一口就能返老还童，喝两口就能滋补强身，是非常非常美味的汤哟。咿～嘻嘻嘻。」

这时候要是不小心回答「YES」的话，强制剧情就会直接开始进行，名为桃乐丝的少女可能会被丢进滚烫的大锅里煮，于是我便大叫了回去。

「不是！我们是来救这个女孩的！」

「这样啊这样啊，那真是可惜了。如此一来……」

这时魔女以锅勺捞出内容物，然后呼一声对它吹了一口气。

「……也把你们煮成汤吧！咿咿咿～～嘻嘻～～～～！」

巫婆随着刺耳声音把锅勺里的内容物朝我们撒过来。结果热水立刻变成刺眼的紫色毒雾笼罩我们。

下一刻，视界左上角的HP条下部就亮起绿框的异常状态标志。是麻痹。

「呃……」

才刚发出呻吟，我、亚丝娜、亚鲁戈以及背后的稻草人等全都倒在地板上。从高等级的三个人都无法抵抗来看，这应该是强制麻痹剧情，但状况依然很危险。我急忙想从腰包里拿出治疗药水，但不知道怎么回事，连平常中了麻痹时应该能动的右手都无法动弹了。

「嘻嘻嘻……那么～要从谁开始煮呢……」

魔女挥舞着代替魔杖的锅勺，踩着跳舞般的脚步靠过来。这该不会是相当危险的场面吧，这么想的我拼命想站起来，但是身体却完全无法动弹。

「咿嘻嘻，没用、没用啦。只有狮子的吼叫声能够破解这个咒文。」

──噢，原来如此。

非常简单易懂的提示让我移动视线，好不容易才看向后方。稻草人跟锡人确实跟我们一样陷入麻痹状态，只有狮子身上没有异常状态的图标。只要他能吼个一声，所有人的麻痹应该就能解开了。

应该是这样啦。

但是这时候的狮子鬃毛竟然整个下垂，然后用双手抱住头部，蹲在地上不停发抖。喂喂，在心中这么吐嘈完之后，我终于注意到一件事。

也难怪他会这样。他依然处于「勇气」被魔女夺走的状态。如果已经取回勇气源头的黄金鬃毛也就算了，但在这种状况下他不可能振作起来。明明是可以预测到的事态，亚丝娜她们为什么会说不需要完成三个副本呢──

「汪、汪汪汪！」

小狗气势十足的吠叫声响彻整个空间，同时也中断了我的思考。

这时中断的不只有我的思考而已。狮子的发抖也倏然停止，萎缩到了极点的鬃毛也逐渐膨胀起来了。到底为什么？他应该已经失去勇气才对啊。

在依然躺在地板上的我瞪大眼睛注视之下，狮子缓缓站起来。虽然还是一脸穷酸相，但双眼确实带着光芒。

「我……我是来救桃乐丝的！」

一大声这么叫完，就鼓起胸膛吸满空气──接着狮子就发出「吼────！」的勇猛咆哮。我的麻痹图标就像是被狮子吼吹飞一样消失无踪。

魔女虽然又使出两次麻痹攻击，但继狮子之后，锡人然后是稻草人也站了起来帮忙阻止咒文的咏唱。最后可能是咒文宣告用罄了吧，魔女露出自暴自弃的模样，挥舞着锅勺猛冲过来。

穿着黑色斗篷与尖帽子的魔女，无论怎么看都不像有取得武器技能，但看到摆在头上的长柄锅勺发出红光后让我有些惊讶。不愧是这个世界的居民，看来她能使用长柄斧系的剑技。

「咕嘎耶耶耶耶──────！」

但是我的「圆弧斩」轻松挡下与刺耳叫声同时挥落的锅勺。把剑拉回来时顺势给予反击，面对被打得后仰的魔女，亚丝娜和我切换之后直接冲了过去。

虽然觉得到了这个时候左手实在不应该还抱着小狗，但即使如此还是能确实发动剑技，也只能说果然名不虚传了。承受无情的五连击后，魔女整个被轰飞出去。像是连着地的空档都不给一般，这次换成亚鲁戈往前突进。她以似乎超越亚丝娜的冲刺钻到魔女底下，双手的金属爪子发出「滋啪滋啪滋啪」的声音来使出乱舞系的剑技。

魔女虽然受到高等级的三个人发动的连续攻击，但只能说真不愧是任务魔王，还是在仅剩下些许HP的情况下撑了下来。即使一屁股跌坐到地上，还是没有晕眩直接站起来，然后朝大厅深处的大锅子跑去。看来是还想对充满谜团的锅子施咒吧，当我们解开技后僵硬就立刻追上去──但在追上之前。

突然从亚丝娜怀里跳出来的小狗，不对，是托托像子弹般追上魔女并且咬向魔女穿着黑色高跟鞋的脚踝。脚步踉跄的魔女往前扑倒，以很快的速度滚了好几次，然后从头栽进煮得滚烫的大锅子里。

几秒钟后，从锅子里喷出盛大的怪物死亡特效。

从监牢里被救出来的少女桃乐丝一边紧抱着爱犬托托，一边不停地对我们道谢。她为了寻找在这个世界某处的「翡翠城」，接下来也要继续跟稻草人一行人一起旅行。

在原本的圆木屋前目送桃乐丝一行人离开的我，就同时拍了一下似乎依依不舍（大概是跟小狗分离的缘故）的亚丝娜，以及放下心一般的亚鲁戈的背部（一样是狗的影响）。任务最后的「！」符号在圆木屋内部飘浮着。进入房子并且关起门后，应该就能回到原来的地点。

「那么，我们也回去吧。」

我边这么说边看向天空，发现夕阳才刚要沉入云海当中。

7

原本的《绿野仙踪》里，稻草人也同样追求大脑、锡人追求心脏，然后狮子追求勇气──在飞回去的路上，亚丝娜这么告诉我。

但是他们最后都没有获得这些东西。故事的最后，大魔法师奥兹是这么说的。在救出被魔女抓走的桃乐丝时，稻草人挤出了智慧、锡人表现出感情，狮子则是发挥了勇气。所以你们已经拥有追求的事物了──

「…………原来如此。所以亚丝娜和亚鲁戈才会知道就算没有解副本，狮子他们也会振作起来吗？」

我带着苦笑这么说完，女孩子们就一起骄傲地点点头，这时候房子也发出沉重的声音着陆了。

一来到外面，发现该处确实是我过去发现这栋圆木屋的森林空地。留下伫立于现场的我跟亚丝娜，亚鲁戈大步横越草皮并且回过头来，露出满足的微笑说：

「谢谢两位今天救了我。谢礼就是这件事会帮你们保守秘密，不会把消息卖出去哟。」

「啥？你说这件事……是哪件事啊？」

「那还用说吗！」

朝这边眨了一下眼睛后──

「祝你们幸福，桐仔、小亚！」

留下哑然呆立于现场的我们，亚鲁戈随即以媲美忍者的轻快动作消失在视界当中。

几秒钟后，由于亚丝娜开始发出轻笑，受到影响的我也跟着露出笑容。当我们一同发出「哈哈哈」的笑声时，感觉最后一根刺在心底深处的尖刺也消失得无影无踪。

──渴望的事物，在你为了追求而踏出第一步时，就已经握在手中了。

我祈求能够永远跟亚丝娜在一起并且向她求婚。所以那个时候开始，我就已经找到失去的物品，也就是一颗能够爱人的心了。

「…………亚丝娜。」

一叫出对方的名字，亚丝娜就带着微笑凝视着我。

在越过圆木屋屋顶的残照照耀之下，我笔直地望着发出闪亮美丽光辉的深栗色眼珠并且打开主选单。移动两次标签，静静地把手指放在目标的按键上。

按下「Marriage」的文字列，接着触碰「Asuna」这个名字。

亚丝娜的眼睛移动，看着出现在眼前的小视窗。接着抬起右手，以纤细的手指像在抚摸般放到视窗上──

「…………桐人。」

亚丝娜确实承受我的视线并且呢喃了一句，然后按下「YES」键。

是在短短几天之后，我们才得知支配这个世界的自律控制系统「Cardinal」的名字。

过了很久很久之后，才有人告诉我Cardinal具备了令人惊讶的「任务自动生成机能」。

（完）

插图p071

*** after

1

「差不多习惯那个虚拟角色了吧？」

突然被这么问，亚丝娜就从显示英文作业的视窗上抬起头来。

她以指尖捻起垂在自己右肩上水精灵族特有的蓝色头发并且回答：

「嗯……还要一点时间吧。真的很奇怪啊……长相跟体格都跟艾恩葛朗特时代一样，不同的只有发色与眼珠的颜色而已，但有时候就是会觉得不对劲。好像意识没有好好待在自己的身体上一样……」

「这样啊……」

很担心般皱起眉头的是漆黑头发呈怒发冲冠状的守卫精灵族少年。虽然说是少年，但里头的男孩子只比今年十八岁的亚丝娜还小一岁而已，由于虚拟角色的容貌感觉比现实世界的他还要淘气，所以会忍不住这么觉得。

并肩坐在沙发上的守卫精灵把自己眼前的全息键盘推到深处后，就把手肘靠在桌上并且凝视着亚丝娜。

「那可能跟习惯没有关系……你说过AmuSphere的BSIS等级之类的回应没有问题吧？」

「嗯。看过记录之后全都在平均值以上。」

「这样啊……」

点了一下头后，桐人就突然伸出左手来握住亚丝娜的右手。

「咦，做……做什么？」

虽然被奇袭攻击吓了一跳而这么反问，但对方却是一脸认真地摊开亚丝娜的手掌。然后将自己的食指缓缓接近该处，微微触碰到后就停了下来。

手掌中心产生的微妙搔痒感传到虚拟角色的背部，亚丝娜忍不住发出「嗯……」的细微声音。但是守卫精灵还是保持严肃的表情，仔细盯着手掌说：

「现在我这边产生了接触感觉，你应该也知道我在摸你吧？」

「嗯……知道。」

亚丝娜点完头，守卫精灵就一本正经地说道：

「好，那我一边动一边慢慢离开，感觉消失的时候就告诉我……怎么样，还有感觉吗？」

接触手掌的手指一点一点横移，变得更加微弱的感觉信号刺激着虚拟的神经。虚拟角色震动了一下并且呢喃：

「嗯……还感觉……得到。」

「是吗……那这样呢？」

「嗯……感……觉得到……」

「这样啊……果然BSIS的讯号等级是没有问题……」

「啊……有感……」

这时候亚丝娜终于发现自己的回答很可能会招致某种误会。

整张脸庞瞬时被强烈的炽热感包围。她迅速拉回右手并紧握成拳头。对着露出茫然表情的守卫精灵放声大叫：

「干嘛让我说这种话啊！桐……桐人你这个大笨蛋──────！」

插图p077

由于地点是在中立都市的旅馆屋顶，所以炸裂的右直拳没有造成数值上的伤害，但矮小的守卫精灵轻松就被从沙发轰飞到深处的墙壁上。

二○二五年六月二十一日，星期六，晚间八点三十分。

亚丝娜──结城明日奈在VRMMORPG「ALfheim Online」内的都市「世界树城市」外围部分某间旅馆的房间里和桐人──桐谷和人一起做着学校的作业。

从倒闭的RCT Progress公司接下ALO营运的新兴企业「YMIR」为游戏带来许多的改变，其中一个就是开放在有限制的情况下从游戏内世界<阿尔普海姆>连接外部网路。从选单里打开浏览器，就能和现实世界的PC或者手机一样阅览各种网站，也可以存取保存在云端空间里头的回家作业档案。万一有带着恶意的玩家想起动可疑的程式，「Cardinal系统」也会立刻检测到，所以不会损及精灵国度的治安。

虽然母亲对于亚丝娜再次开始使用完全潜行机器感到不悦，也不断表示「至少自己动手完成回家作业」，但是对于亚丝娜来说，现实世界的身体与虚拟世界的虚拟角色都是「自己」。处于能在周围尽情开启（严格说起来是有上限）视窗的虚拟世界写功课比较有效率，也不会出现眼睛疲劳、肩膀酸痛的情形。最重要的是，住在世田谷区宫坂的亚丝娜能够和远在埼玉县川越市的桐人一起看书……这个动机或许有点不妥当就是了。

总而言之，这一天晚上也以精灵的模样专心打着全息键盘时，桐人突然就开始检查起亚丝娜的感觉──这就是整件事情的经过。

当守卫精灵发出「呜呜呜」的呻吟并且撑起身体时，同样从沙发上起身的亚丝娜就严厉地双手扠腰并且表示：

「我说啊，要确认感觉讯号的话，应该还有别的方法吧！」

「……刚才那是最简单的啊……说起来，色……有奇怪反应的是亚丝娜吧……」

亚丝娜以更加严厉的眼神瞪着做出暧昧反驳的桐人。

「色……什么？你想说什么？你说说看，我保证不会生气。」

「绝……绝对不可能！应该说你已经在生气了……」

「我没有生气！如果结衣没有出门的话，我可能就真的会生气了。」

亚丝娜的话让摆出立正姿势的桐人抖了一下。

除了是高度的Top-down型AI之外也是两人的女儿，在ALO内是「导航妖精」的结衣，因为和好友克莱因以及莉兹贝特等人去狩猎，所以目前不在家。如果刚才那一幕被心爱的女儿看见……一想到这里亚丝娜的脸颊便再次发热，下一刻桐人就不知道为什么露出笑容并且以爽朗的口气──

「亚丝娜，你的脸好红。」

听见对方做出这样的评论，亚丝娜只能再次握紧铁拳。

当她朝着脸上浮现「糟糕」表情的桐人大步往前走了几步时──

「…………啊……」

亚丝娜随着小小的呢喃停下脚步。

又被那个感觉袭击了。灵魂短短一瞬间像要从虚拟身体上脱离的奇妙感觉。就好像再也不清楚手脚在哪里又该如何运动一样……也像是现在已经不再是现在。

应该是察觉到异变了吧，桐人以媲美瞬间移动的速度靠过来支撑住亚丝娜的身体。然后露出认真的表情凝视亚丝娜的眼睛并且呢喃：

「不要紧吧？」

「嗯……嗯，我不要紧。已经复原了。」

即使如此回答，亚丝娜还是把体重加诸于桐人的手，然后继续呢喃：

「只有……只有一点点不对劲的感觉。虚拟角色也不是无法动弹，不去在意就可以了……不对，说不定真的只是自己想太多…………」

「不行……还是仔细调查一下比较好。这是艾恩葛朗特时代不曾出现的感觉吧？」

「嗯。一次都没有……我想……」

桐人轻轻抱起点头的亚丝娜并把她运到隔壁的寝室。由于租借的是旅馆最上层的总统套房，所以能从房间宽敞的窗户看见世界树城市金碧辉煌的夜景，以及遥远下方那一整片阿尔普海姆的大地。但是桐人没有理会这样的景色，让亚丝娜躺在大床上之后自己也坐到旁边。他再次伸手静静地抚摸蓝色头发，同时开口说：

「……亚丝娜，虽然你应该不愿意想起……」

亚丝娜从犹豫不决的口气听出桐人的言外之意。于是就一边微笑一边轻轻摇头。

「不要紧的……连身为『蒂塔妮亚』时都未曾有这种感觉。所以我想不是伺服器<世界>变更了的关系。」

「这样啊…………」

点点头后，桐人这时终于把视线移到窗外。

他攻略了死亡游戏「Sword Art Online刀剑神域」，把存活下来的六千一百四十九名玩家从浮游城艾恩葛朗特解放出来的日子是二○二四年十一月七日。

但是包含亚丝娜在内的约三百名玩家却没有回到现实世界。须乡伸之这名原本担任综合电子机械制造商RCT公司要职的男人，为了进行违法的人体实验而把三百个人的意识绑架到设置在ALO内的虚拟研究设施里。

亚丝娜虽然没有成为实验台，但是却被关进挂在世界树树枝上的巨大鸟笼里。「蒂塔妮亚」这个名字，是在这个世界自称为「精灵王奥伯龙」的须乡所取。

身为囚犯的痛苦一直持续到二○二五年一月二十二日被桐人救出为止。虽然觉得那两个月的时间已经足以匹敌待在艾恩葛朗特的两年，但是那段期间从未出现感觉异变的自觉。

「……首次出现这种……怎么说呢，这种『抽离感觉』大概是在一个月前……」

亚丝娜小声这么呢喃完，桐人就稍微瞪大了眼睛。

「你记得第一次发生的时间吗？」

「嗯。因为是跟新艾恩葛朗特第一层的魔王怪物对战的时候。」

亚丝娜的答案让桐人眨了两三下黑色眼睛。

「那个时候吗──话说回来，你那时候使用魔法时失败过一次，难道……」

「亏你记得这么清楚。」

亚丝娜忍不住对搭档莫名强大的记忆力露出苦笑，同时点头说道：

「咏唱咒文时突然有抽离身体的感觉，嘴巴就不由得停了下来。因为马上恢复，战斗中也只出现过一次，我也觉得可能是自己想太多……但在那之后就经常发生……」

「……如此一来，果然不是习惯的问题了。因为第一层的魔王战时，距离亚丝娜首次以这个虚拟角色潜入ALO已经过了三个星期以上吧？如果是因为不习惯虚拟角色，应该一开始就会频繁出现这种感觉了。」

「说得……也是。但是，那原因到底是什么呢……」

亚丝娜躺在床上歪起头来，结果桐人就露出沉思的表情过了好一阵子，然后才说：

「待在ALO之外的VR空间时不会出现这个现象吗？」

「嗯……这个嘛。除了这里之外就不太完全潜行到其他地方，不过其他地点确实没有感觉到『抽离』的记忆。」

「那也不是NERvGear和AmuSphere的差异所造成了。再来就是……嗯……虽然认为不可能──但现实世界是否有同样的现象……」

「当然没有了。如果有的话就真的是灵魂出窍了。」

亚丝娜自己这么说完后，稍微觉得有点害怕而重新检查记忆，幸好想不出有类似的状况。但如此一来，就更想不出造成谜样「抽离现象」的原因了。虽然试着在网路上搜集资料，但是找不到报告出现同样故障的AmuSphere使用者，而且症状太过笼统，也没办法寻求RCT或者YMIR的协助。

发生这种现象的时间极为短暂，只要不去在意就可以了，也不是足以阻碍游戏进行的问题──但都在这里做出各种假设了，实在很难要自己不去在意。

侧脸对着亚丝娜而坐的桐人再度发出「唔嗯」的沉吟声，最后像是下定决心般开口说道：

「再来就只能跟结衣商量了。」

「……嗯……」

亚丝娜本身在发生第四、第五次的「抽离」时就有这样的想法，但是却一直犹豫到今天。要是知道亚丝娜的异常，结衣一定会非常担心，而且如果连结衣的能力都无法解决问题的话，将会给她的心灵带来很大的负担。

结衣是为了辅导SAO玩家的心灵层面而设计出来的实验AI。但是随着死亡游戏化而被冻结各种权限，只能够监视多达数千名玩家的负面感情。异常的负荷最后损坏核心程式，和亚丝娜他们相遇时几乎变得无法说话。

因此亚丝娜已经下定决心不让结衣担心，也绝对不伤及她小小的心灵分毫。

但是桐人却像是看透她的心思般点了一下头，然后再次把手朝着亚丝娜的头伸去。温柔但确实地灌注力量来抚摸她的头发──很少有玩家能够用虚拟角色办到如此细微的操作──同时开口说：

「我能理解亚丝娜的心情。但是……结衣要是知道亚丝娜不找自己商量的话，应该会因此而感到悲伤吧。」

「但是……真的没有什么大不了的。大概不久后就会习惯这种现象，然后就再也不会在意了。」

「……是这样吗……因为亚丝娜很敏感……」

这时桐人瞬间闭上嘴，急忙摇着头并继续开口表示：

「啊，不是啦，我没有奇怪的意思。」

「真是的，这我当然知道啊……然后呢？」

「然后……嗯，越是敏感的玩家就越无法无视感觉的微小异常。战斗中的话就更不用说了。我希望亚丝娜能够尽情享受这个世界……不是死亡游戏的普通VRMMO。因此不论是再细微的障碍都想把它清除……说到底这可能只是我任性的想法……」

桐人最后用呢喃般的口气说完就稍微低下头，而亚丝娜则是对他伸出右手。

把手放在紧身黑色上衣的肩口，然后用力把他拉过来。受到继承SAO时代的高筋力值拉扯而失去平衡，纤细的守卫精灵发出「呜哇」的声音并且跌落到躺在床上的亚丝娜胸口。

亚丝娜立刻用双手抱住对方，接着一边灌注力量一边呢喃：

「谢谢你，桐人……我现在很开心了喔。能够跟桐人、结衣一起到阿尔普海姆的各个国家与新生艾恩葛朗特的各个城市观光、购物、冒险，我真的非常高兴。今后也想一直一起在这个世界旅行。」

在亚丝娜缓慢的语调影响下，原本在怀里挣扎着的桐人也停下动作。最后畏畏缩缩地把手绕到亚丝娜背后。

现在想起来，SAO时代之后就没有像这样跟桐人相拥了。从虚拟世界的鸟笼解放出来的一月到四月底都持续在复健，之后就努力为了适应包含新学校在内睽违了两年的现实世界，两个世界都很难有两个人独处的悠闲时间。今天能够像这样，也是刚好两个人都有许多回家作业，平常的读书会就会有更多人参加了。

但是亚丝娜现在开始在心底深处拟订一个计划……或者可以说跟自己的约定。

虽然不知道会是什么时候，但现在只能爬到第十层的新生艾恩葛朗特要是开放第二十一层以后的楼层，一定要比任何人都早到达第二十二层，然后买下建在森林深处的小圆木屋。就是过去跟桐人一起度过短暂但是幸福的时光时所住的玩家房屋。

当然新旧艾恩葛朗特除了栖息的怪物、出现的道具之外，连地形也有微妙的差异，所以同一个地点不一定会出现同样的房子。但是亚丝娜确信那栋圆木屋一定在等待着两个人。只是不知道在购买之前是不是要再攻略一次「飞天房屋」任务就是了。

「……说不定……」

或许是亚丝娜悄悄的呢喃声传到耳朵里了吧，怀里的桐人微微歪起头来。呢喃了一句「没什么」后，亚丝娜又继续无声地说道。

说不定不可思议的抽离现象是因为内心太过渴望那栋房子的缘故。或许意识一瞬间离开虚拟角色，飞翔到第二十二层的森林去了……

当亚丝娜这么想时，耳朵就听见桐人的声音。

「……明天跟结衣商量看看吧。如果是结衣的话，一定能找到我们无法发现的障碍。」

「嗯……说得也是。」

点点头后，亚丝娜便缓缓放松拥抱。

紧贴着的脸颊离开，两人的视线在至近距离交错。虽然有些许预感闪过亚丝娜胸口，不过桐人和她对望了一阵子后就直接撑起身体，再次坐到床旁边然后回头表示：

「那么……接下来要做什么？要去跟克莱因他们会合吗？」

亚丝娜先是露出苦笑，接着摇了摇头。

「不行。功课根本还没做完吧。」

「啊……对……对喔……」

「全部结束之后大概快要十点了，明天才能狩猎了。艾基尔先生和莉法也说可以参加，多一点人一定比较有趣喔。」

「好的──」

像个小孩子一样回答完后，桐人就沮丧地垂下头并且自言自语着：

「唉……SAO时代，晚上十点才正式要开始狩猎呢……」

「别怀念那种奇怪的事情！说起来，你是不太进行『夜间狩猎』的人吧。但是等级却不断地提升，已经被当成攻略组的七大不可思议之一了。」

亚丝娜从床上撑起上半身一边这么表示，桐人则是逐渐露出微妙的表情并提出疑问。

「……那么其他六大不可思议是什么？」

「嗯……像是『黑衣剑士．无盾单手剑传说』、『黑衣剑士．获得太多LA传说』……」

「等……等一下等一下。怎么全都跟我有关？」

「别担心，第七个是『KoB团长防御太硬传说』之类的……但是只有这一点不是什么不可思议的事情就是了。」

一面回溯八个月前的记忆一面这么呢喃，看穿团长──希兹克利夫也就是茅场晶彦有何「不可思议」的黑发剑士就把伸出去的手轻放在亚丝娜头上。

「我才没有什么不可思议的地方呢。等级也是受到许多人鼓励与帮助才好不容易维持住……当然亚丝娜也帮了我很多忙喔。」

摸了两三下头部之后，桐人就从床上站起来伸了一个大大的懒腰。

「好了，快点把功课解决掉吧……所以这次也要请你稍微帮忙一下喽……」

「真拿你没办法。」

利用反弹力下到地板之后，亚丝娜就露出满足的微笑说：

「结束之后要到一楼的餐厅请我吃东西哟！」

从虚拟世界回到现实世界，一开始感觉到的是整个身体的重量。

换言之就是真正的重力大小。旧SAO里身为细剑使的亚丝娜，一直贯彻着重视速度的能力构成，所以虚拟角色的体感重量相当轻。每天都像疾风般奔驰在战场上，彷佛野马般跳跃过障碍物。在继承了能力值的ALO里，这样的情形也没有改变。不对，由于背上有翅膀，重力感可能更加希薄了也说不定。

因此在自己微暗房间的床上睁开眼睛的那一瞬间，压在全身的重量差点就让人感到窒息。被囚禁在死亡游戏的那个时候明明如此渴望「登出」，但无论如何就是无法喜欢这种感觉。这样的冲击过了一阵子后或许也会习惯吧。

花了整整十秒钟左右做好准备后，明日奈缓缓撑起身体。

从头上取下跟NERvGear相比纤细到惊人的完全潜行机器──AmuSphere。天花板的感应器察觉动作，自动点亮了间接照明的亮光。

双脚放到地板上后虽然慎重地站起来，但还是感到些许晕眩。虽说和让虚拟世界的亚丝娜感到烦恼的「抽离现象」有些类似，但相对于里面那种意识飞上天空的感觉，现实世界起身时的晕眩像是被往地面拉去一样。其不舒服的程度远超过抽离现象。

轻轻摇摇头甩开晕眩感后，明日奈穿上拖鞋走向南侧的窗户。

从窗帘缝隙眺望笼罩在六月夜晚沉重潮湿冷空气中的住宅区好一阵子。或许是下着毛毛雨吧，街灯的周围出现白色伞状光晕，不禁让人联想到虚拟世界的特效光。

「…………？」

突然有种一部分记忆受到刺激的感觉，让明日奈皱起了眉头。

夜晚的街道。夜雾里渗出的街灯。发出潺潺水声的水道。抱着膝盖蹲在水道旁边。虽然害怕得想逃走，却又无处可逃……

完全想不出这是什么时候在什么地方见到的情景。虽然想牢牢抓住朦胧的印象，但它就跟出现时一样唐突地消失了。

明日奈感受着残留在心底深处那不可思议的寂寞余韵，往下持续看着现实世界的夜景。

2

隔天六月二十二日，星期日，下午四点三十分。

亚丝娜在绕行阿尔普海姆上空旋转的巨大浮游城──新生艾恩葛朗特的第八层迷宫塔最上层──也就是所谓的「魔王房间」里。

在这个地方应该做的只有一件事。当然就是跟魔王怪物战斗。

发出「啾噜噜噜！」尖锐示警声的是全身长着蓝色羽毛的小龙「毕娜」。身为它主人的猫妖族玩家西莉卡立刻大叫：

「亚丝娜小姐，要召唤小兵了！」

「了解！大家聚集过来！」

亚丝娜举起右手的法杖对小队成员做出信号，接着迅速开始咏唱咒文。

「现身吧神圣的泉水<艾兹库．卡兹拉．芙雷茵．布鲁努鲁>，阻止火焰与毒的吐息<安达斯库．布兰多．欧咕．艾伊托鲁多>。」

最后一句高声咏唱完的同时，法杖就竖立在黑色大理石地板上。淡淡蓝光波纹扩散出去，大量的水像是要追上波纹一样涌出，立刻形成直径将近十公尺的水面。

「谢啦，亚丝娜！」

「谢谢你！」

握着锤矛的小矮妖莉兹贝特以及让毕娜坐在头上的西莉卡率先冲进水面，同样从SAO时代就是伙伴的大地精灵族斧战士艾基尔、火精灵族刀使克莱因则跟在后面。迟了一会儿，全身黑的守卫精灵桐人，以及现实世界中是他妹妹的风精灵族魔法剑士莉法同时从最前线回归。

这七个人已经是小队人数的上限，但在魔王房间里战斗的不只有亚丝娜他们。由于和其他四支小队组成了大规模强袭部队，所以圆形大厅里应该存在三十五名玩家，不过却没有丝毫拥挤的印象，这是因为魔王房间比旧艾恩葛朗特时加大了许多的缘故吧。

冲进具备HP回复效果与抗毒．抗火效果的水面，桐人就呼一声松了一口气，这时他肩膀上的小妖精结衣就对着亚丝娜挥舞小手。

「妈妈，你的咒文咏唱也有模有样了呢！」

「啊……啊哈哈……谢谢你，结衣。」

亚丝娜这么回答之后，水面周围就喷出几条火柱。火柱立刻形成龙卷风般的漩涡，从中心延伸出人型火焰，最后变成高一公尺左右的小小火焰妖精。

单体的话不是什么强敌，但数量实在太多了。整个宽敞的魔王房间里应该涌出三十只以上吧。而且火妖精只是普通的小兵Mob，铺设黑色大理石的大厅──以及浮游城第八层全体之主的魔王怪物也会同时发动攻击。

魔王的名字是「火焰蛇神．瓦吉特<Wadjet the Flaming Serpent>」。

最初的战斗之后经由调查得知瓦吉特是出现在埃及神话里的火之蛇神。外表也符合这个名字，是巨大响尾蛇头部融合了四手女神的模样。黑色基调的巨躯包裹在火焰之下，毫无防备就靠近的话会受到火属性的持续伤害<DoT>。

现在魔王本体是由亚丝娜他们之外的另两支小队在对付。在他们十四个人的HP还未耗尽之前，必须尽快解决杂兵才行。

右手的法杖依然撑在地板，亚丝娜迅速确认起周围的状况。

蛇神瓦吉特与两支小队在广大魔王房间的另一侧激斗当中。其他两支小队里，由女性火精灵队长所率领的一队，目前退避到跟亚丝娜一样的水精灵魔法师所创造出的水面。另一支小队似乎没有能够使用这种「纯净水面<Purified surface>」咒文的玩家。亚丝娜举起左手来对着他们叫道：

「尽量多拖住一些小兵，然后进入这边的水里吧！」

男性风精灵队长也挥手表示「知道了」。

在两人沟通之时，周围的六名同伴也把不断聚集过来的火妖精全都变成灰烬。虽说是魔王身边的杂兵，但依然是能够将一般物理伤害减半的强敌，只不过一旦进入魔法水面就会变得相当弱，就算这支只有少数魔法师的小队也能够顺利解决。

在打倒附近的所有火妖精之后，其他小队就拖着大量敌人冲进水面。直径十公尺的圆内待了十四个人确实略嫌狭窄，立刻冲出来的桐人与克莱因就把一半追加的火精灵吸引到自己身边，让成员能够使用所有水面来战斗。

看见周围不断闪烁的金属光辉，亚丝娜就很想把法杖换成细剑，但要保持魔法水面就得持续把法杖撑在地面上。亚丝娜之所以在ALO里成为接近治疗师的魔法师，除了因为觉得支援职业似乎也很有趣之外，也跟比伙伴晚一些加入小队时，队里已经充满物理攻击职业有关。

或许是察觉亚丝娜跃跃欲试的内心了吧，来到附近的莉法以感到很抱歉的口气表示：

「对不起喔，亚丝娜小姐。总是拜托你帮忙辅助。」

「别这么说，我没有心怀不满哟。咏唱咒文很有趣。」

「就是说啊！哥……桐人现在咏唱咒文还会害羞喔，下次请亚丝娜小姐好好说说他。」

稍微浮现的笑容立刻消失，莉法举起左手来表示：

「神圣的水啊请治愈他们<赛亚．费兹拉．黑伊拉库鲁．阿乌斯特鲁>，让冰冷的死亡远离吧<普罗特．斯帕鲁．巴尼>。」

开始回复咒文咏唱的她确实是有模有样。顺畅地咏唱完咒文后，开始有蓝色水滴从她左手降到周围，逐渐治愈水面的持续回复<HoT>效果无法顾及的剑士们所受的伤害。

一阵子之后，由于打倒所有火妖精了，亚丝娜就举起右手的法杖。蓝色水沫飞溅接着魔法水面消失，并排在HP条下方的几项支援效果图标减少了一项。

移动视线后，发现在右侧战斗的其他小队也刚好歼灭周围的所有火妖精。确认所有杂兵都处理完的克莱因随即对跟魔王战斗的十四个人大声叫道：

「嘿，杂兵都清光了！随时都可以交换喽！」

似乎是对方领队的高大暗精灵立刻大声回答：

「了解！下一次破防后就交换！」

下一刻，蛇型魔王就大大扬起蛇首。以背负着响尾蛇膨胀头部的形式与其一体化的黑色女神，四只手之中握着宽阔大剑的手高高举起。

结果魔王周围的空间就闪过紫雷，接着不断有半透明的巨剑实体化。密集在魔王前面的玩家们全部鸟兽散，拿着盾牌的人将其高举，持双手武器者则将武器高举过头。

「沙啾啊啊啊啊！」

随着奇怪的叫声，魔王──火焰蛇神．瓦吉特将剑挥落。多达八把幻影巨剑呼应其动作，发出轰然巨响朝着玩家们轰去。

有四个人成功挡下攻击，其余四个人连同盾牌与武器被整个弹飞出去。但是受到使用大技的影响，笼罩瓦吉特的火焰也变薄，在后方的魔法师们不错过这个空档，施放出完成咏唱的行动阻碍系咒文。

几乎所有魔王怪物对阻碍效果都有很高的抵抗力，但看准时机还是能让其停止动作十秒左右。咒文产生的蜘蛛丝、银锁链、黏稠沼泽等缠上瓦吉特的瞬间，暗精灵队长就大动作挥手。

「退下──！」

玩家们随着「唔喔──」的叫声一起跑了起来。被幻影剑轰飞的四个人好不容易才起身，一边叫喊着「别丢下我们！」一边加入后退的伙伴之中。

「好，轮到我们啦！」

架着刀子的克莱因率先跑出去，桐人跟艾基尔紧跟在他身后。

跟着他们一起跑的亚丝娜突然浮现这样的想法。

──大家看起来都很开心。

当然桐人和莉兹贝特他们也一样，不过看见其他四支小队后这种感觉就更强烈了。

他们二十八个人大部分都是今天才初次见面的玩家。被在第八层主街区「斐利潘」的转移门广场征求魔王攻略联合部队参加者的他们邀约之后，简单自我介绍完就往迷宫塔移动，快速爬上塔后就趁势冲进魔王房间。旧艾恩葛朗特时代完全无法想像会出现这样的突击方式。

以前在魔王攻略战之前都要经过多次的侦查与会议，检讨各种风险并且尽可能凑齐战力才正式开始攻略。虽然理解具备不能出现任何死者这个绝对条件的SAO与ALO的现况完全不同，但亚丝娜在今天的魔王战快开始之前还是忍不住浮现「真的要这样直接开始？」的想法。新艾恩葛朗特第八层目前是最前线，这也就表示魔王火焰蛇神．瓦吉特到现在都还没被打败过。她认为要挑战这样的强敌，至少要稍微举行一下作战会议，或者确认队形吧。

但是战斗开始已经经过将近三十分钟的现在，感觉终于能够了解为什么这么做了。

真正重要的不是打倒魔王本身，而是享受那个过程。

即使打倒魔王，也不能是由高压的领队集团──过去亚丝娜以副团长身份率领的公会「血盟骑士团」那样──进行单方面指挥所获得的结果。所有玩家同心协力，一起思考、作战、欢喜……或者是悔恨。这才是网路RPG的醍醐味，如果可以尝到这样的兴奋，就算落败一定也很开心。

待在后退的两支小队最后尾的男性暗精灵玩家，在和亚丝娜错身时抬起左手并且大叫：

「三分钟就能重整态势，在那之前就拜托你们了。」

迅速与对方击掌后，亚丝娜便回应：

「交给我们吧！拜托你们处理杂兵了！」

从响着铠甲离开的集团那里听见「别趁机吃豆腐！」「才不是哩！」的声音，跑在旁边的莉兹贝特忍不住噗哧一声笑了出来。

「真的一点都没变呢，亚丝娜。」

「什……什么啊。」

「以前在艾恩葛朗特，两个人一起走的时候也经常……」

「现……现在没必要提这种事情吧！看，魔王的攻击来了！」

有些慌张地这么回应之后，打破阻碍效果的瓦吉特再次开始动作。

跟在阿尔普海姆地下广大冰之国度幽兹海姆昂首阔步的邪神级怪物相比，新生艾恩葛朗特的魔王怪物尺寸上是比较小，但强度似乎远远凌驾于邪神级怪物。从浮游城实际上线到现在已经过了一个多月仍只被攻略到第七层就能证明这一点。听说第八层的魔王瓦吉特也是从一个星期前就有各种族的强者们组成七人×七小队的最大上限联合部队加以挑战，但是却全都被打得落荒而逃。

得知这一点后，光是仰望在天花板附近昂起蛇首的人面蛇身魔王怪物就受到强烈的紧张感袭击，但亚丝娜还是强颜欢笑来赶走恐惧。重要的不是获胜而是享受这个过程。不必害怕败逃，全力放手一搏就对了──

「沙噜啊！」

瓦吉特发出怪声，举起左下方手臂握着的权杖。

并排在大厅外围部分的圆柱回应其动作，随着轰然巨响开始旋转，露出藏在背面的大镜子。下一刻，刚才退后的两支小队不等待队长的指示就分散为数人一组，围住共八面的镜子。

瓦吉特的权杖从前端的水晶球发射带有即死级威力的光线。其实光是这样就已经是相当恐怖的武器了，但更棘手的是，光线会靠着外围的镜子形成复杂的反射，让人无法预测其轨道。

刚开始攻略魔王时，似乎是镜子一出现所有人就加以破坏。用武器不断打击的话确实能够击碎镜子，但它的耐久度相当高，在打破八面镜子之前就会被光线射中而出现复数的死者。

但是过了一周之后的现在，已经创造出一套比破坏更有效果的对应方法。

围住八面镜子的玩家们一从正面改变镜子角度之后就立刻退开，紧接着瓦吉特高举的权杖随即迸发出墨绿色光线。

击中房间西侧镜子的光线原本应该瞬时反射到其他镜子，而轨道上的玩家则是立刻死亡。但是角度被玩家调整过的镜子几乎在直角的情况下──也就是朝着瓦吉特把光线反射回去。被自身发射的光线击中后，魔王怪物就发出尖锐的悲鸣，多达七条的HP条开始大量减少。但是目前只减少到第二条的一半而已，不过至少目前尚未出现死者。以尚差两小队才达最大上限的即席部队来说，已经算是相当不错的战果了吧。

担任这次小队队长的克莱因似乎也有同样的想法，他举起刀子气势十足地大叫：

「很好，没问题哟！所有人，突击！」

架着双手斧的艾基尔与握着单手剑的桐人立刻冲出去，莉法与莉兹贝特也跟在后面。跟其他两支小队一起围住魔王长长的胴体，一起使出斩击、殴击与刺击。

亚丝娜这次也没有待在后方。不过当然不是拿着法杖来殴打魔王，而是使出魔法攻击。擅长高速咏唱的她口诵咒文，并且朝着瓦吉特的上半身挥动法杖，接着就有数根锐利的冰枪降下刺中黑色鳞片。由于即死光线的自爆让护身火焰暂时消失，魔王弱点的冰属性魔法完全发挥功效，配合着桐人他们的物理攻击使得HP条出现明显的减少。

受重伤而开始挣扎的瓦吉特，长长的蛇躯开始像弹簧一样卷起。从远处注意到这个动作的亚丝娜大声叫着：

「尾巴攻击要来了！大家准备跳跃！」

下一个瞬间，跟在魔王身边的攻击手们就整个飞退并且摆出防御姿势。说起来瓦吉特是属于属性攻击系的魔王，但物理攻击也十分猛烈，长尾巴在靠近地面处旋转三次的攻击技要是没有闪开第一击而跌倒就会连续被第二、第三击打中。

亚丝娜和伙伴同时轻弯起膝盖来计算时机。卷完尾巴的女神，双眸发出深红光芒。这时候……跳跃！

但就在这个刹那──

在虚拟角色快要跳起之前，亚丝娜产生只有意识被往上拉的感觉。是那个「抽离现象」。

竟然在这种时候──！亚丝娜屏息等待感觉恢复。现象应该只有短短一瞬间，但在这种状况下却漫长到令人心焦。积蓄在魔王体内的力量解放出来，尾巴发出破风声往众人迫近。不行……来不及了。

脚在被极粗的鞭子扫中之前，亚丝娜脑袋里闪过魔王战之前进行的对话。

在跟莉法与克莱因他们约好的时间前一个小时，桐人与亚丝娜登入到跟昨天一样的旅馆并且叫出结衣来商量这个状况。

从小小导航妖精恢复成原本白色洋装模样的结衣，在两人之间一直听着亚丝娜的描述，等说明结束后就呢喃了一句：

「意识……抽离……」

亚丝娜对着轻坐在沙发上瞪大双眼的结衣点点头。

「是啊。虽然很难用言语形容……不过我认为一定是跟虚拟角色的通讯出了某种问题。」

「……竟然出现了这样的障碍……对不起，妈妈。如果我能更早一些发现的话……」

「别这么说，这不是结衣的错。」

亚丝娜用双手包裹住少女垂下的脸颊。

「我才应该为没有早点跟你商量而道歉呢。一开始以为是因为不习惯虚拟角色的缘故。但是昨天和桐人谈过之后，觉得或许有其他原因……」

这时候坐在结衣另一边的桐人就开口表示：

「怎么样，结衣……你有没有想到什么原因……？」

「这个嘛……」

亚丝娜双手中的AI少女伏下长睫毛，露出陷入沉思的表情。虽然短短三秒钟后就抬起头，但表情却依然阴郁。

「很遗憾的是，光靠妈妈刚才说的情报无法特定出障碍的原因……另外，以我现在的权限，也无法直接检查妈妈的AmuSphere与ALO伺服器之间交换的封包。如果我在近处时发生该种现象的话，说不定就能获得一些档案……」

「说得……也是。抱歉喔，结衣，对你提出无理的要求……」

亚丝娜准备道歉时，结衣就用自己的手从外侧再紧握住她的手。把手从自己的脸颊移开，移到两个人之间后灌注强大的力道。

「但是可以做出一定程度的推测。」

「咦……真的吗？」

「是的。首先假设抽离现象的原因不存在于妈妈的AmuSphere以及妈妈本身。如此一来最先想到的就是伺服器方的障碍，但是目前Cardinal系统没有侦测到任何异常，也没有任何使用者提出发生同种障碍的报告。」

亚丝娜带着暗暗的感慨，凝视着握住自己双手就开始俐落说起话来的少女。

昨天桐人和亚丝娜还担心这件事情会给结衣带来很大的负担。但是看起来是杞人忧天了。结衣除了承认自己无法立刻解决问题之外，还拼命地想办法对应。她也随着日子不停地成长。

「因此问题的现象，我推测原因是ALO伺服器方……也就是存在阿尔普海姆内的某样事物对妈妈进行非正规的干扰。至于究竟是玩家还是物件，又或者是否刻意进行干涉，目前这个阶段仍无法判断。」

「非正规的……干扰……」

这次换亚丝娜重复了一遍结衣的话。

假如引起亚丝娜抽离现象的是人类，那么绝对不可能是普通玩家。因为不存在能办到这种事的魔法与道具，所以绝对是拥有高级权限者……怪客<Cracker>，或者是GM干的好事。

想到这里时，浮现在亚丝娜脑海里的是再也不愿回想起的一个男人的脸庞。把亚丝娜监禁在鸟笼里长达两个月的精灵王奥伯龙──须乡伸之。

但是那个男人目前仍关在东京拘留所内，无论怎么想都无法干扰ALO伺服器。桐人应该也想到同样的事情了吧，他的表情一瞬间绷紧，但立刻轻轻摇摇头。然后以平常的表情看着结衣的眼睛并且问道：

「结衣，你刚才说干扰亚丝娜的也有可能是物件对吧？这……到底是怎么回事？特定的道具或者地形超越系统的框架影响玩家，真的可能发生这种事吗……？」

结果年幼的少女像是在考虑该如何说明一般微微歪起头，然后才缓缓开始说话。

「我想爸爸和妈妈都已经知道，我原本是照顾SAO玩家精神状态的『Mental Health Counseling Program』的实验版本。这也就表示NERvGear不只能读取着装者的感觉．运动讯号，甚至还拥有读取感情的能力。旧SAO的Cardinal系统会监测所有玩家的精神状态，并且累积档案……」

到这里都是亚丝娜已经知道的事情。初次见面时，结衣简直就像两三岁的幼儿般无法说话，那是因为无法处理庞大的玩家负面感情而让主程式受损的缘故。

依序看了一下两人的脸之后，结衣又以清晰的声音继续表示：

「只不过，跟感觉．运动的讯号比起来，表露感情的讯号解析进展相当慢。能够判别的只有累积档案量最多的『愤怒』、『悲伤』、『恐惧』与『绝望』等负面情绪，除此之外的感情就连Cardinal……以及其次级程式的我，当时都无法加以解析。于是Cardinal在有特异且高强度的感情格式输入时，会把其RAW档案连同周边环境保存起来。发出讯号的玩家ID就不用说了，甚至连时间、地点以及所持道具都会被保存下来。」

「…………！」

亚丝娜微微吸了一口气，和桐人面面相觑。

还是第一次听见这种事情。虽然结衣的说明有点难懂，但简单来说应该是这样吧。管理旧SAO伺服器的Cardinal系统在玩家产生强烈的特别感情时，记录的并非解析格式后的压缩档而是RAW档案……也就是记录了「感情本身」。但在某种层面上来看，这算是复制玩家灵魂──虽然是极表层的部分──的行为吧。

现在的完全潜行技术真的能办到这一点吗？这么想的瞬间，亚丝娜就回忆起某件事。自己与桐人说不定曾经目击过这种现象的实际例子。

「……对了……桐人，你还记得吗……？以前我和你一起调查圈内杀人事件时的事……」

结果似乎想着同一件事情的桐人立刻点了点头。

「嗯。解决事件之后，在第十九层练功区的某座山丘上确实看见了。坟墓的旁边站着被杀害的葛莉赛达小姐。那个……不是幻影，而是保存在坟墓……不对，是连结到一直埋在坟墓底下的戒指后保存于其中的……葛莉赛达小姐的心吧……」

事到如今已经无法证明真伪。结衣也没有对这件事发表任何评论。最后桐人静静伸出左手来触碰持续保持沉默的结衣娇小背部。然后以沉稳的声音再次问道：

「结衣的意思也就是旧SAO里，当玩家产生强烈感情时，其档案就会跟地形或者道具相连结并且保存下来……是这样吧？」

桐人又继续对轻轻点头的结衣提问。

「那么结衣刚才所说的，成为抽离现象原因的物件就是指这个喽？亦即是……寄宿在某种道具上的玩家之心在干涉亚丝娜……？」

这次连结衣也无法立刻回答。但是亚丝娜感觉她的沉默并非是因为在选择用词遣字，而是对自己口中所说的推论感到困惑。

「……现阶段没办法回答YES……」

以细微的声音这么回答之后，结衣便抬起头，接着以坚定的口气说：

「但是，爸爸跟妈妈就不用说了，我和莉兹贝特小姐、莉法小姐、克莱因先生、艾基尔先生以及其他许多人说话、一起冒险后学会了一些事情。也就是人的心与完全潜行包含了远超过现在的我所能理解的可能性。因此爸爸的问题我也无法说NO。正如我一开始所说，我认为可以推测出这样的答案。」

某个玩家。

或者是玩家寄宿于道具甚至是地形物件的「心之碎片」。其中之一就是造成谜样抽离现象的原因──

虽说只不过是推论，但是在魔王战之前结衣曾经这么说过。由于这时候已经到了约定好的时间，所以没办法继续探讨下去，但是在移动到新艾恩葛朗特之前，亚丝娜试着自行解释了一下结衣的话。

这就表示，有人在呼唤自己吧。现在玩着ALO的某个人……或者玩过SAO的某个人正在呼唤亚丝娜。意识就是因为这样而被拉扯，造成快要脱离虚拟角色的结果。如果这是事实，那个不知道是男是女的他一定没有恶意吧。只是因为无法选择时间与地点，才会变成亚丝娜玩游戏时的障碍。就像现在这个瞬间一样。

虚幻的浮游感降临的瞬间，周围的光景也产生变化。

黑色大理石的魔王房间瞬间变淡，眼前映照出完全是另一个房间的幻影。

淡茶色砖头随机排列组成的墙壁以及同颜色的地板。充塞四周围的大量怪物……像是把漆黑岩石雕刻成人型般的矿石妖精，以及五短身躯加上十字镐般武器的黑暗矮人们。感觉确实在某时某地看过这彷佛热气般摇晃的光景，但就是想不起正确的时间与地点。和昨天晚上看着窗外夜景时降临的奇妙感觉完全一样。

也就是说，这不是亚丝娜的记忆，而是属于呼唤亚丝娜的某个人的……？

看见幻影房间与怪物的时间极其短暂。在它们消失的同时，意识也回到虚拟角色身上。瞬间瞪大的双眼，捕捉到火焰蛇神瓦吉特在靠近地板处宛如割草镰刀般飞过来的强韧尾巴。

待在范围攻击内的伙伴一起垂直跳跃。但只有亚丝娜踢向地板的时机晚了一些──但这已经足以致命。不行，来不及了…………

「亚丝娜！」

突然间，不是来自前方而是侧面的冲击随着这道声音袭来。身体被用力抬起，下一刻，瓦吉特的尾巴掠过靴子尖端。亚丝娜甚至忘了确认自己的HP，直接看向稳稳抱住自己的黑衣守卫精灵的脸庞。

「桐……桐人，为什么……」

面对这代表「为什么知道发生『抽离』的时机」的一句话，桐人迅速对着亚丝娜呢喃：

「结衣在前一刻感应到了。」

接着坐在桐人肩膀上的小妖精就以严肃的表情补充道：

「八秒钟前，有某种讯号朝着妈妈发出。还需要一点时间才能解析出来。」

「……真的是某个人对我……」

茫然这么呢喃后，亚丝娜终于注意到自己和桐人在空中滞留了几秒钟的时间。一看之下，桐人从背上伸出的灰色翅膀正发出朦胧的燐光。

阿尔普海姆的九种精灵种族里，甚至连跟天空无缘的大地精灵与小矮妖都具备飞行能力。五月的升级改版撤除了RCT Progress时代存在的滞空时间限制，所以现在不论要飞几个小时都不成问题，但还是存在例外。也就是冰之地下世界幽兹海姆与各地的迷宫。当然新生艾恩葛朗特的迷宫塔也是飞行禁止地区。

但还是有例外中的例外。只有擅长寻宝的守卫精灵拥有即使在地下也能飞行一定时间的专用上级技能。虽然也跟熟练度有关，但效果时间相当短暂，刚才桐人就为了拯救亚丝娜而发动了只有紧急时刻才会使出的王牌。

「谢谢你，桐人……」

亚丝娜源本来想继续说声「对不起」，但是桐人已经先悄悄摇头打断了她。

地面上将近二十名玩家整齐划一地连续跳跃来闪躲第二、第三次的尾巴攻击。瓦吉特的范围物理攻击结束的同时，桐人就抱着亚丝娜降落到地面。技能失去效果，灰色翅膀无声地消失。这种能力的冷却时间长达五六百秒，所以要再次飞行已经是很久之后了。在那之前要是再次受到抽离现象袭击，桐人就没办法出手相救了。

或许是察觉亚丝娜内心这样的想法吧，结衣从桐人的左肩轻跳到亚丝娜的右肩，把嘴巴靠近耳朵后呢喃：

「妈妈，我已经记住讯号大致的格式了，下一次可以更快做出警告。」

「嗯，拜托你了，结衣。」

小声这么回答完，亚丝娜就对着伙伴们叫道：

「抱歉，脚绊了一下！下次会确实躲过！」

莉兹贝特立刻举起左手来回应「别在意！」。这时候桐人也离开亚丝娜身边，朝着陷入硬直状态的瓦吉特跑去。

桐人和发出「唔喔呀啊啊！」叫声的克莱因等人一起默默挥着剑，亚丝娜看着他这样的背影并且皱起眉头。

不知道为什么，这次魔王战期间，感觉桐人似乎比平时还要安静。不对，从战斗前把小队队长交给克莱因负责开始，他似乎就不怎么说话了。虽然想跟右肩上的结衣确认，但是又立刻闭起快要张开的嘴巴。现在必须集中精神在战斗上。

毫发无伤就躲开尾巴攻击的攻击手们一起反攻，让瓦吉特的七条HP条里的第二条进入红色区域。蛇身女神发出愤怒的叫声，然后举起握在右下方手臂上的铜制火把。

「要召唤小兵了！」

在克莱因这么叫之前，亚丝娜已经稍微后退并且开始咏唱「纯净水面」咒文。光靠退到后方的两支小队，无法对付从整个大厅里涌出的火焰妖精。把魔王交给火精灵领队与风精灵领队的小队，亚丝娜的小队应该去处理杂兵。

克莱因应该也做出这样的判断吧。他转过头来准备对亚丝娜做出指示，发现亚丝娜已经开始咏唱咒文后就咧嘴笑了起来。

「好了，我们退下处理火妖精吧……喂，桐字头的老大！」

视线朝发出慌张声音的克莱因看去，就发现稍远处的桐人夹杂在其他两支小队当中准备突袭。跑了几步后听见克莱因的声音便停下脚步。

桐人像要表示「抱歉」般举起左手并赶了回来，持续咏唱的亚丝娜则是一直凝视着他的脸。平常的他在魔王战当中不可能犯下这种错误。

是因为太过注意亚丝娜的抽离现象，导致于欠缺集中力吗？或者是──还有其他的原因呢……

即使在脑袋角落思考着这种事情，嘴里还是以超高速咏唱完咒文，亚丝娜随即把右手的法杖高声插在地面。透过靴子感受涌出冰冷圣水的她，终于无法忍耐而对着右肩的结衣呢喃。反正在保持这个魔法的期间也不能做其他事情。

「结衣，桐人的样子好像……」

结果小妖精像是早就在等待她这么说般点了点头。

「是的，爸爸跟平常有点不同。」

「我想也是……到底是怎么了……」

「我也不清楚……」

某方面来说，结衣比亚丝娜还累积了更多桐人这个人类的情报，既然连她都这么说了，那么今天的桐人绝对「跟平常不一样」了。而他不寻常的原因想必跟亚丝娜的抽离现象有关。

──等战斗结束之后，再跟桐人好好聊聊吧。把昨天晚上跟刚才看见的不可思议光景全说出来。

内心如此决定后，亚丝娜就用力握住法杖，将意识集中在眼前的战斗上。

大约三十分钟后──

似乎支撑到最后的桐人与克莱因两个人被传送到迷宫塔一楼的存档地点。虚拟角色才刚实体化，刀使就握住双拳大叫：

「咕哇啊啊啊──真可惜────！HP条只剩下一条而已啊──！」

结果和亚丝娜他们在同一个时间点「死亡回归」的艾基尔就一边苦笑一边吐嘈道：

「就是那一条最困难啊。听说瓦吉特跟下面那层的魔王一样，HP剩下最后一条时攻击模式就会改变了。」

「我当然知道，但都到最后一条了，不会觉得靠气势就能一鼓作气干掉魔王吗？」

「怎么可能！应该说实际上也失败了吧！」

这宛如短剧般的对话，让莉兹贝特和莉法以及共组联合部队的四支小队玩家都发出大笑。

「抽离现象」在那之后就没有出现，亚丝娜也尽了全力来战斗，但是第八层魔王攻略挑战还是以全灭作为结束。不过大家脸上的表情都很开朗。联合部队募集者的风精灵队长带响着钢铁护脚走了过来，在带着笑容的情况下向克莱因搭话。

「哎呀，我觉得已经很有机会了。七支小队的话应该就能打倒了吧。」

「嗯，我也这么认为！连携的感觉也很不错，如果那个时候火妖精的涌出没有异常集中的话……」

「哎呀，没有你们的话，在那之前的雷射就已经全灭了，你们确实很有一套喔。」

克莱因发出「嘿嘿」的笑声，迅速握住风精灵伸出的右手。

放开手后，联合部队队长先是露出些许思考的表情，接着把视线移到艾基尔与莉兹贝特等人的身上并且开口说：

「那个，你们愿意的话，要不要先回城里然后再次挑战？这个时间的话，说不定还能再找到两支小队。」

「嗯，我当然没问题喽！老兄你呢。」

在克莱因询问之下，艾基尔用英文回答了一句「Why not」，面对转过头的两个人，其他四名女性也迅速表情赞同之意。

身穿红色武具的刀使咧嘴一笑，开始说到「好，就这么决定……」时，就轻抬起头巾下方一边的眉毛。因为他注意到平常一定会率先同意的一个人持续保持沉默。看向站在稍远处的桐人，保持纳闷的表情对着他搭话。

「喂，桐字头的老大应该也要去吧？」

结果黑衣的守卫精灵像弹起来一样抬起头。彷佛都没听见之前的对话般露出笑容──但那在亚丝娜眼里还是有些僵硬──并且表示：

「嗯……嗯嗯，当然了…………」

但这时视线立刻在空中游移。稍微紧闭的嘴角最后终于微微动了起来。

「…………不对……我之后有点事。抱歉泼大家冷水，但我必须先走了。」

「哦……噢，是没关系啦……」

克莱因似乎想继续说些什么，但宛如要阻止自己一样不停摩擦着下颚凌乱的胡子。接着再次咧嘴一笑并开口说：

「好吧，之后就交给我们吧！我会传抵达第九层的照片给你！」

接着旁边的艾基尔也说出似曾相识的台词。

「我也会写八百个字的感想，告诉你瓦吉特掉了那些宝。」

「我很期待。」

稍微苦笑了一下后，桐人便对风精灵队长点了点头并且改变身体的方向。虽然一瞬间跟亚丝娜四眼相对，但却像是要道歉般眨了眨眼，然后就快步朝着位于南方的迷宫塔出口走去。

亚丝娜可以感觉到坐在右肩的结衣娇小的身躯瞬间紧绷。下一刻，亚丝娜在无意识中也有一只脚准备往前跨，但最后还是忍住了。她是小队唯一的魔法师。不能在这个时候离队……

「亚丝娜小姐，你过去看看吧。」

突然间听到这样的声音。惊讶地转过头去，发现不知道什么时候已经站在后方的莉法一边微笑一边抬起右手，然后轻推了一下亚丝娜的背部。

「别担心，我会找到两个人来加入。哥哥就拜托你了。」

「…………但是……」

这么呢喃的亚丝娜左右移动脸部，结果莉兹贝特、西莉卡、艾基尔以及克莱因都笑着依序点头。

用力吸了一口气，内心做出决定后，亚丝娜就深深低下头去。接着撑起上半身，对伙伴以及联合部队成员大叫：

「抱歉，请让我在这里离队吧！」

结果在旁边注意事态发展的数十个人就传出几道「辛苦了！」「下次也请多多指教！」「虽然不知道怎么回事，不过要加油喔！」的声音。再次低头行礼后，亚丝娜迅速转过身子。

从存档的房间往南延续数十公尺的通道上已经看不见桐人的身影。但是肩膀上的结衣却以坚定的声音说：

「爸爸朝南方的外围部飞过去了！」

「谢谢你，结衣。」

如此呢喃着回答她后，亚丝娜迅速打开视窗收纳右手的法杖，接着朝迷宫塔出口跑去。

3

练功区曾几何时已经笼罩在夜色之中。

阿尔普海姆的日夜是十六个小时轮回一次，所以并没有跟现实世界同步。现在时刻是下午五点过后，才刚过夏至的这个时期天空应该还是蓝色，但是精灵乡内甚至连残照都已经消失。

艾恩葛朗特第八层是森林的楼层。第三层虽然也是以森林为设计概念，但相对于该处存在不少草原以及岩石地，第八层则完全是森林。最重要的是不存在地面这种东西。楼层表面被深水覆盖而无法步行，不过有极度巨大的树木（当然比世界树伊格德拉修还要小得多）往四面八方伸展粗大的树枝，而且架了无数的人工吊桥，玩家将利用它们在空中通道移动。

旧SAO时代要是不小心掉下去，就得在水中东奔西跑来寻找有梯子的树，但现在没必要担心这件事了。亚丝娜从成为迷宫区容器的焦黑巨木跑出来后，立刻无视设置在附近树上的螺旋阶梯，强力振动背上的翅膀。

不只有迷宫塔，之所以就连周边树木都焦炭化──就设定上来说，这全都是新的楼层魔王火焰蛇神．瓦吉特干的好事。旧时代的魔王怪物完全不同，而且这边附近的树也相当茂盛，应该是新营运企业YMIR程式设计师拼命把它们弄焦的吧。

几乎是垂直上升了五十公尺左右，当视界有了一定程度的开阔后就进入水平飞行。由于耸立于这层的巨树树梢触碰到第九层底部，所以就算再飞五十公尺也无法出现在森林上空。也就是说，旧SAO时代这里是少数努力爬树的话就能直接用手触碰下一层底部的楼层之一，当然没有人能在上面挖洞。

亚丝娜穿梭飞在直径应该有十公尺的树干之间，同时对从肩上移动到胸口的结衣问道：

「桐人到哪里了？」

「马上就要抵达外围部。再离远一点就无法探测到爸爸了！」

「了解！真拿他没办法，果然很快。」

亚丝娜把双臂用力贴紧身体然后全力加速。虽然立刻习惯ALO独特的飞行系统，两天就不用辅助控制器，但认真的飞行还是比不上桐人与莉法。靠着挂在树木间的吊桥上燃烧着的油灯光芒，在几乎快撞上障碍物的距离下一边闪躲一边飞行。

最后前方透出了蓝色光芒。月光──马上就要到外围部了。桐人应该早就飞出浮游城了吧。当亚丝娜这么想时，结衣就再次大叫。

「爸爸沿着艾恩葛朗特的外墙往上飞了！」

「咦……」

亚丝娜稍微瞪大眼睛。由于桐人说「之后还有事」，原本以为是为了登出而前往世界树城市。但是仔细一想就发现，如果是急着登出，只要到第八层各处的城镇旅馆就能完成，就算要到世界树城市，现在只要到第一层的起始的城镇就能直接传送了。

也就是说，桐人的目的地是ALO的……不对，是艾恩葛朗特上层的某处。

但是六月二十二日的现在，艾恩葛朗特的最前线就是这个第八层。第九层以上的楼层都从外围部完全封锁，没有办法从外面入侵。亚丝娜以前曾经跟桐人、莉兹贝特等人一起试着要飞到应该存在于第一百层的「红玉宫」，但是到了第五十层附近就抵达飞行高度界限，唯一能参观到的就是无限延伸的钢铁外墙。

桐人应该知道无法进入上层，那么他到底要到什么地方去呢……

这么想着的亚丝娜，从第八层南端开口处飞向无限的天空。

一抬头仰望就发现天空中挂着巨大满月。月光让浮游城封闭的外墙发出蓝白色光辉。一道小小的黑影正在快要碰到墙面的距离下往上升。看起来很快就抵达第十五层附近。一直线的飞行让人感到某种紧绷感，亚丝娜一瞬间犹豫自己是不是该追上去。

「桐人……」

无意识中这么呼叫的同时，从短袍领口探出头来的结衣也呢喃着「爸爸……」。听见这道细微声音时，亚丝娜内心就做出了决定。她弯曲双脚，全力往空气踢去。笔直地伸展身体，像支蓝色的箭一样紧急上升。

跟桐人的距离是艾恩葛朗特的七层楼那么远──也就是七百公尺。旧SAO时代的话，七层以上就等于是另一个世界，但那也是过去的事情了。现在的亚丝娜拥有四片发出水蓝色光芒的翅膀。

亚丝娜拼命飞翔追着心爱的人，内心同时有了预感。虽然不知道桐人要到哪去，但是那个地方一定有解开这种「抽离现象」的答案。他应该是藉由跟结衣的对话获得某种假说，然后现在正准备加以确认。

遥远的上空中，撕裂虚拟大气往前飞行的桐人，即使超过二十层也没有放慢速度。就连有两人的「森林之家」等待着的第二十二层也没有停止，而且瞬间就通过大规模公会「艾恩葛朗特解放队」崩溃的第二十五层。究竟要到什么地方去呢……当亚丝娜这么想的瞬间，黑影就以锐角完成了空翻。身体整个冲向耸立在旁边的黑色钢铁外墙。

「啊……！」

预测到会猛烈冲撞，亚丝娜就发出简短的叫声，但是桐人在撞上墙面之前就张开翅膀紧急减速。虽然没有用足以减少HP的速度撞上去，但桐人双手敲打墙面的冲击还是传递到仍在遥远下方的亚丝娜身上。

那个地方是……第二十七层。

主街区的名字记得是叫「隆巴尔」。整个楼层都是凹凸不平的岩山，城镇与迷宫是挖穿山脉所建立。由于可以获得丰富的矿石道具，所以SAO时代职业是工匠的玩家很喜欢这一层，但是亚丝娜对它没有太深刻的印象。金属元素系的魔王怪物还算是棘手，但她记得只在这一层待了短短几天。

这部分的情况，同为攻略组的桐人应该也一样才对。但是为什么他现在会来到第二十七层呢？

亚丝娜专心凝视着的前方，可以看到黑色剪影双手按着钢铁外墙一动也不动的模样。简直就像是祈祷墙壁就会打开一样。

但是无法破坏的障壁当然没有回应他的要求。亚丝娜在抵达第二十六层附近时就放慢速度，最后几乎是在任由上升气流带动的速度下抵达桐人的身后。

没有办法开口搭话，胸口的结衣也保持着沉默。这个高度也几乎不会出现飞行型的怪物，所以存在于三人周围的就只有森森洒落的月光、吹拂而过的夜风以及钢铁的浮游城。

最后桐人把双手从第二十七层的外墙上移开。缓缓放下双手，微微振动翅膀转过头来。

「……亚丝娜、结衣。」

呼唤两人名字的嘴角带着浅浅笑容。在认识两年八个月的岁月之中，不太常看到他露出这样的表情。

「桐人……」

如此对他呢喃完后，亚丝娜稍微拉近距离，但是犹豫着是不是要继续靠近。虽然有许多事情想问，但是却不知道从何开口。

把视线从呆立在空中的亚丝娜身上移开，桐人环视周围后指着右下方说：

「我们到那里去聊吧。」

一看之下，从浮游城的外墙上出现宛如桥梁般的突起。长度大概只有三公尺左右，但是已经足以充当长椅了。点点头后，亚丝娜就跟桐人一起移动，然后静静在钢铁桥梁上坐下来。

就坐在左边近处的桐人抬起右手，以指尖温柔地抚摸只从亚丝娜衣领露出脸来的结衣头部。在保持内心带着某种伤痛般的微笑之下，以平稳的口气开始诉说。

「……抱歉喔，结衣。另外……也让亚丝娜你担心了。」

结衣从亚丝娜的衣服里面窜出后轻坐到桐人右肩来取代回答。圆滚滚的黑色眼珠笔直地看着亚丝娜，像在做出「妈妈，快一点啊」的催促。

对她点了一下头后，亚丝娜便下定决心开口问道：

「桐人……这里……第二十七层发生过什么事？」

虽然暂时闭上嘴，但稍微思考一下后，又重新说出后半句话。

「…………以前的第二十七层……发生过什么事……？」

刹那间──

自己的话变成打开记忆的钥匙，亚丝娜大大地张开双眼。

这一层确实有事发生过。亚丝娜过去曾经从桐人那里听说过。虽然没有具体说出是在第几层，但现在已经极为明显了。这一层一定……发生过造成桐人拒绝公会与小队，持续以攻略组唯一独行玩家战斗的那个事件…………

「嗯……没错。」

应该是从表情察觉到亚丝娜的内心了吧，桐人微微点头肯定了她的想法并且表示：

「我初次加入的公会『月夜黑猫团』就是在第二十七层的迷宫区里全灭……」

桐人在两人于森林房子前结婚的前两天，告诉亚丝娜一直深藏在内心的黑猫团悲剧。也就是二○二四年十月二十二日的事情。

在第二十二层的森林里首次遇见结衣是在当天的一周之后，到了现在结衣也还只是知道那件事大略的经过。桐人没有再次详述过去的情形，只是用沉静的声音开始说起目前的事情。

「……今天结衣告诉我玩家的强烈感情可能会以寄宿于地形或道具的形式保存于SAO伺服器时……我就有了这样的想法。那么黑猫团众成员的感情或许也残留下来了……在第二十七层迷宫区的隐藏房间里，被矿石妖精与黑暗矮人杀害的瞬间所产生的恐惧与绝望…………」

────！

听到这句话的瞬间，亚丝娜脑海里就清晰地浮现和瓦吉特战斗时降临的幻影。

由砂岩砖块随机堆成的外观，无疑是属于旧艾恩葛朗特第二十七层迷宫区。然后挤满狭窄房间的大量妖精与矮人。那不就是现在桐人所描述的光景吗？

「…………桐人。」

亚丝娜从喉咙挤出细微的声音。原本伏下脸部的桐人抬起头来，亚丝娜便试图向他说明不可思议的现象。魔王战中所看见的，应该成为月夜黑猫团灭团舞台的隐藏房间所出现的光景──昨晚登出之后，从自己房间所见到的城镇夜景。潺潺水道与渗出夜雾的街灯……

「………………」

这时就连桐人都感到惊讶，有好几秒钟说不出话来，最后还是缓缓点点头。

「……我想不会错了。夜晚的城镇……是黑猫团唯一一名女性玩家的记忆吧……这也就是说……让亚丝娜产生『抽离现象』的是因为……」

说到这里就一瞬间停了下来，然后用更加细微的声音继续说：

「──幸在呼唤的缘故吗……但是──为什么不是我……而是亚丝娜呢…………」

回答这一半是对自己所说，一半是茫然呢喃的是自今为止都保持沉默的结衣。

「我想那是因为……现在的爸爸使用的是跟SAO时代不同的帐号与角色。」

「…………！」

下一个瞬间，桐人就像弹起来般撑起上半身，然后往下看着自己戴着黑色皮革手套的双手。亚丝娜知道那双手掌与手指的形状跟SAO时代有些许的不同。

为了在ALfheim Online开始非死亡游戏的普通游戏生活，亚丝娜就不用说了，就连莉兹贝特、西莉卡、克莱因、艾基尔以及其他许多的生还者几乎都是把SAO时代的虚拟角色与帐号资料直接转移到ALO。但是只有桐人一直使用为了把亚丝娜从鸟笼救出来而新创的，外表看起来有些淘气的守卫精灵。

如果桐人让以前的帐号复活，那么名为幸的女子或许保存在新艾恩葛朗特第二十七层某处的情感──呼唤的就不是亚丝娜而是桐人了吧。可以预测那个时候发生「抽离现象」的也会是桐人。

但是幸为什么会选择，不对，应该说为什么可以选择亚丝娜来代替桐人呢？

她在亚丝娜跟桐人结婚的一年多前应该就过世了。当时亚丝娜作为新创公会「血盟骑士团」的副团长，只努力朝强化公会与楼层攻略的道路迈进。和桐人只有在作战会议以及魔王攻略战时才会碰面，完全不知道他曾经加入「月夜黑猫团」，以及那个公会除了他之外的成员已经全灭的事实。反过来说，黑猫团的幸甚至没听过亚丝娜的名字才对。

这次换成结衣来回答这个疑问。

「妈妈现在使用的角色……严格说起来，现在依然跟爸爸以前的虚拟角色处于结婚状态。因为目前ALO里没有结婚系统，所以状态上没有显示出来……但角色档案还是跟以前的爸爸有关连。」

「是……是这样吗？」

即使在这种状况之下，亚丝娜还是因为过于惊讶而叫了出来。

桐人虽然也瞪大眼睛，但一阵子后才呢喃了一句「这样啊……」。

「……幸过世的时候……我也在现场。幸临死之前的感情不只在第二十七层迷宫区的那个地点，也跟我以前的虚拟角色有所连结并且保存于伺服器内了吧。但我已经换了虚拟角色……所以幸的感情所发出的讯息，目标就变成依然跟以前的我连结在一起的亚丝娜……应该是这样吧……」

这些是到目前为止还算可以理解的事情。但是依然有搞不懂的部分。

「……但是，为什么是『现在』呢……」

亚丝娜把视线移向耸立于左侧近处的浮游城外墙并且继续说道：

「抽离现象是我首次潜行到ALO后经过三周左右才第一次出现。而且最近发生的频率越来越高。也开始产生之前没有过的记忆混杂般现象……」

「…………那是因为……」

只说了一句话后，桐人突然就打开视窗。凝视着时间显示一阵子后才吸了一大口气，以有些紧绷的声音宣告：

「……幸是在二○二三年六月二十二日过世……也就是两年前的今天。时间是……下午五点四十五分。再过三分钟后……」

「…………！」

亚丝娜不由得屏住呼吸。坐在桐人肩膀上的结衣也把黑色眼睛瞪大到极限。

桐人消除视窗，抬头看着曾几何时整个布满星星并且开始发亮的夜空，静静地开始诉说。

「…………我……在SAO里见过许多玩家的死亡，甚至有用自己的剑了结生命的人。所以……原本决定不再把黑猫团和幸的死当成特别的事件。在之前的艾恩葛朗特时，黑猫团作为据点的旅馆前面有一棵树，我把它当成墓碑而经常前去参拜……但现在旅馆所在的第十一层以及众人过世的第二十七层都还无法进入……所以决定今天和大家一起玩时到了那个时间就稍微默祷一下……然后就把这件事做个了结……但是听见结衣的话……发现造成亚丝娜抽离现象的原因可能是幸保存在伺服器的感情，就忍不住想要亲自过来确认……」

桐人双手放在大腿上，然后紧握起拳头。在深深垂下头的情况下，以压抑的声音继续往后说下去。

插图p126

「…………如果那个瞬间幸的感情……恐惧、绝望、悲伤被记录在伺服器里，现在也想传达给某个人的话……那就是独自活下来的我应该负起的责任。但是我却换了虚拟角色，舍弃了过去……就因为这样，害得幸失去目标的感情……转移到亚丝娜身上…………」

「………………桐人。」

亚丝娜一边不断摇头一边呼唤爱人的名字。由于有太多想要传达给他知道的事情，反而不知道该从何说起。正当亚丝娜因为过于焦躁而感到呼吸困难时──

「你错了，爸爸！」

凛然这么大叫的是结衣。她从桐人的肩膀上飞起来，移动到他脸部正面后，紧握住小小的双手并且拼命诉说：

「Cardinal系统记录的是无法解析格式的特别感情。这么说或许不太好，但SAO内玩家临死前的恐惧与绝望并不是什么特别的感情。系统运作后短短两个星期，绝望的RAW档案就不再被保存下来了。所以，如果幸小姐的感情残留在伺服器里面……那就绝对不是绝望与恐惧才对！」

结衣拼命的呼喊让桐人稍微抬起一点脸庞，然后以沙哑的声音呢喃：

「…………那么…………幸残留的感情是…………」

亚丝娜没办法把这句话听完。

六月二十二日，下午五点四十五分十三秒。发生了至今为止最大的「抽离现象」。

臀部下方钢铁梁柱的硬度、气流吹过高空的冰冷程度、魔法师用布装备的触感等一切全都远去。强烈的浮游感笼罩全身，虚拟身体的重量消失无踪。

而亚丝娜的意识终于完全脱离虚拟角色了。漆黑浮游城的巨躯、满天星光也都被白光覆盖过去。

灵魂被吸进光之回廊，然后被带到某个地方去……

回过神来才发现站在没看过的房间里。

房间不算太宽敞。家具也只有一张简朴的床与木制的桌子。从唯一的窗户可以环视让人联想到欧洲乡下城市的街景。石头与铁的盖子取代天空往四处延伸。这里不是现实世界……而是艾恩葛朗特的某个城市。感觉各个家庭的屋顶与墙壁都似曾相识。大概是第十一或者第十二层的主街区。也是现在应该尚未开放的楼层。

虽然是夜晚，但照明只有墙上的一盏油灯，所以略显昏暗。这里应该不是玩家房屋，而是旅馆的一间房间吧。亚丝娜绕过床铺，走向大门并把手朝门把伸去，但是手却穿越过去而完全无法握住。看了一下自己的身体后，惊人的是已经不再是水精灵魔法师了。身上穿着白色与红色基调的骑士服。另外还有同色的长手套与长靴。腰间虽然没有细剑，不过这无疑是血盟骑士团时代的服装。但是全身却像幻影一样透明。

当心里想着「到底怎么回事」而抬起头的瞬间──

床铺上的空间开始摇晃，并且出现朦胧的人影。

那是一名体格纤细的女性玩家。她背对亚丝娜坐在白色床单上。身穿浅蓝色女性紧身上衣与迷你裙。身上没有配戴防具。整齐地剪到肩膀上面一点的头发是略为泛蓝的黑色。光是靠背影就能知道是年纪相仿的女孩子。

女孩子似乎正左右摇晃着上半身。刚浮现「是在唱歌吧」的想法，耳朵就听见温柔的歌声。是有名的圣诞歌曲。对方很可爱地一个字一个字缓缓持续歌唱。

听着歌唱当中，亚丝娜的视界开始有几个光粒摇动着。曾几何时，双眼已经盈满泪水。强烈的感情让胸口揪紧。女孩子的心情乘着旋律流入内心。丝毫不存在恐惧或者绝望的心情。盈满温暖且宛如春阳般感情的，只是纯粹的……

当一滴泪水从亚丝娜右眼滑落的同时，歌声也结束了。

女孩子站起来，无声地转过身子，隔着床铺与亚丝娜相对。

因为双眼溢出的光芒而看不清楚对方的脸。只能看见露出微笑的嘴角悄悄动了起来。

耳朵听见了声音。

你帮我传达吧。

就说我很幸福。

再次有纯白的光芒包裹住亚丝娜。女孩、房间与街景逐渐远去。

把身体交给浮游感的亚丝娜了解到──这应该是最后的「抽离」了。

亚丝娜缓缓抬起眼睑。

无数的星星正在泛蓝夜空中闪烁着。耸立的钢铁之城以及挂在其前端的巨大满月。

稍微移动视线，就看见桐人与结衣以担心表情窥看着自己的脸庞。亚丝娜的身体被桐人的右手支撑着。

「……谢谢，我不要紧了。」

呢喃完撑起身体后顺便瞄了一眼自己的服装，发现当然已经恢复成原本的蓝色短袍了。

「亚丝娜…………」

在带着担心与询问的口气呼唤之下，亚丝娜再次看向桐人。虽然稍微犹豫了一下该从何说明起，但立刻就注意到应该说的事情已经存在心中。

「幸小姐她脸上挂着笑容喔。」

亚丝娜一这么说，桐人的双眼就瞪得老大。

亚丝娜笔直地回望着星星的反射光逐渐增加的黑色眼睛，同时灌注所有心意来说出女孩子托付给自己的话。

她就像幸一样，唱起了圣诞歌曲。

4

「那一天」的隔天──六月二十三日，星期一，晚上九点。

亚丝娜再次待在新艾恩葛朗特第八层主街区「斐利潘」里。

昨天亚丝娜与桐人离开后所举行的第二次魔王攻略战依然是功亏一篑。但是已经发现HP条剩下最后一条时的攻略法，因此组成联合部队的所有人约好隔天要第三次挑战魔王。

这次桐人和亚丝娜当然会参加，而且还有尤金将军与朔夜领主各自率领一支火精灵阵营与风精灵阵营的最精锐小队加入，这时作为集合地点的转移门广场就笼罩在比昨天更加热络的气氛当中。

「话说回来，真的很惶恐耶……」

如此对克莱因搭话的是这次依然担任联合部队总领队的风精灵剑士。虽然一开始不愿意在部队内有种族领主的情况下出面担任指挥官，但是确实没有几个在朔夜本人随着媚眼说了一句「拜托你了」之下还能拒绝的玩家──如果是男性就更不用说了。

「能够同时把朔夜小姐和尤金将军找来，你到底是何方神圣？」

风精灵队长这么询问后，克莱因就笑着回了一句「哎呀，没那么夸张啦，哈哈哈」，结果被艾基尔吐嘈「不是你的人脉吧」，当亚丝娜以无奈的心情看这种光景时，就听见身后桐人和结衣的声音。

「咦……咦咦？改变发型？」

「没错！」

亚丝娜回头对两人问道：

「桐人、结衣，怎么了吗？」

「没有啦，其实呢……」

守卫精灵抓起一撮冲冠的黑发，以困扰的表情说：

「结衣说这样很难坐在我头上，所以要我改变发型……但是发型变更并不便宜……」

结果站在桐人肩上的结衣就两手扠腰来提出反驳。

「我觉得偶尔可以把钱用在武器防具和赌场之外！而且待在高处也有助于我收集情报的效率！」

「等一下，结衣。你刚才说武器防具还有什么……」

「哇──好啦！我知道了！等今天的魔王战结束我立刻就换！」

似乎突然改变主意的桐人这么大叫，但结衣却还是摇了摇头。

「距离集合时间还有十分钟！有这么多时间的话，已经足够到那边的理发厅去改变发型了！」

「是是是……那么亚丝娜──抱歉喔，我去去就来，再来就拜托你了。」

「嗯……嗯。路上小心。」

挥手目送两人离开的亚丝娜突然想着。

现在的守卫精灵虚拟角色虽然长相和发型都跟SAO时代不同，但是把倒立的黑发放下来的话，氛围倒是颇像以前的桐人。

虽然不至于希望他变回SAO时的模样，但那倒是颇令人期待，于是亚丝娜就对刚好从转移门现身的莉兹贝特、西莉卡与莉法招手。

「大家快点过来！」

「怎么了吗？」

亚丝娜一边对露出疑惑表情的莉兹贝特等人招手一边笑着大叫：

「那个啊，桐人他呢……」

（完）

** 彩虹桥

1

染上紫色的天空远方，浮着发出暗红色光辉的城堡。

新生艾恩葛朗特实际上线后明明已经过了两个月，像这样从阿尔普海姆的海平面往上看，依然每次都会产生不可思议的感觉。实在很难相信那个小小的构造物，和过去存在于其他世界空中的浮游城是完全一样大。

只要张开背上的翅膀起飞，朝着遥远上空的新生艾恩葛朗特上升，最后城堡当然会变成无法尽收于视界的雄伟模样。从外围开口部降到第一层时，该处已经是有山脉与湖泊的广大练功区了。从这一头走到另一头的话，应该得花跟旧艾恩葛朗特一样的时间吧。

即使知道这一点，我还是忍不住想起一些事。

像是被关在那个城里两年。浪迹于没有道路的荒野，与凶恶怪物战斗，还有跟许多人相遇以及别离。在第七十五层与希兹克利夫战斗，和他同归于尽来终结死亡游戏。还有这些事情真的都是现实吗？

或者是──

为了追踪持续昏睡的亚丝娜而降落到阿尔普海姆，经过短暂却忙碌的旅程后从恶意的监牢里把她解放出来。和过去的伙伴与新朋友一起往来于现实以及虚拟世界过着安稳的生活。而这些事情真的都是现实吗？

当我转动这无止尽的思绪，默默往上看着夕阳照耀下的浮游城时──

突然从脚边涌起「咕哦哦哦哦────嗯」的号角般巨大声响。灰白色地面剧烈晃动，我只好踏稳虚拟角色的双脚。反射性举起双手，以右手抓住亚丝娜，左手抓住克莱因的手。

「呜哇，怎……怎么了？」

莉兹贝特这么大叫……

「不……不会要把我们从这边甩下去吧？」

克莱因如此叫唤……

「到时候飞起来就好了。」

就在艾基尔冷静地这么吐嘈之后。

原本就存在于前方地面的小洞一口气扩大，然后有大量的水宛如间歇泉一样迅速喷出。

「啾────！」「哈哇哇────！」

这样的悲鸣来自于刚好在洞穴正上方的小龙毕娜，以及跨坐在毕娜身上的小妖精结衣。虽然被突如其来的水流抬高五公尺以上，但这时候毕娜张开双翼来取得平衡，然后在喷水顶端轻轻地盘旋。两秒前的悲鸣就像骗人一样，结衣正发出欢喜的笑声。

我以左手挡住降下的细小水滴，一边和亚丝娜面面相觑，然后嘴角同时露出微笑。

「……嗯，本来就会喷水了吧。」

结果亚丝娜也点点头并且回答：

「因为怎么说都是只鲸鱼啊。」

没错。搭载由我和亚丝娜、莉法、西莉卡、莉兹贝特、艾基尔、克莱因等七个人加上结衣与毕娜组成的小队在海上游泳的，是身躯巨大到连邪神级怪物都要赤脚逃走的白鲸。

当所有人都点头同意后，随着喷水结束从上空降下来的结衣就边移动到亚丝娜左肩边说：

「现实世界的鲸鱼先生，实际上不会从喷气孔排出海水喔。只是在海面附近喷气时连同海水一起喷上去而已。」

「这样啊──！」

七个人异口同声地这么表示。

依然展现着博学多闻一面的结衣很自傲般把娇小的双手扠在腰上。觉得那种模样很可爱的我，再次抬头看向飘浮在夕阳天空中的钢铁之城。

由于新生艾恩葛朗特是在遥远上空以很快的速度绕着阿尔普海姆旋转，所以外观已经变得比刚才看见时更小。我凝眼看着下方五分之一处的地点──充满回忆的第二十二层附近。

目前虽然只开放到第十层，但是将来一定会开放第二十层以上的楼层。再次看见那栋盖在积雪深厚的森林深处的圆木屋时，我应该会有某种感概吧。感觉到过去的艾恩葛朗特消失在记忆远方，以及自己回到游戏是用来游玩的世界了。

白鲸把我们从漂浮在阿尔普海姆西南海上的托雷岛载到风精灵领地内的海滩，接着就发出宛如巨大低音号般的声音催促我们下来。以温柔眼神看着小队从背上跳下后就悠然反转，带着随从海豚朝着水平线那端的鲜红夕阳游去。

「鲸鱼先生──谢谢你──！下次也请让我们坐在你背上喔────！」

白鲸再次以高高的喷水回应结衣的呼喊，然后巨大身躯就一点一点沉入海里，最后完全消失不见。坐在亚丝娜肩膀上的结衣也轻轻放下拼命挥动的手。

我微笑着对略显寂寞的侧脸搭话道：

「一定还能见面。感觉刚才的任务应该还有后续。」

「哦，没错哟，桐字头的老大！」

大声插嘴把离别的余韵全部打散的当然是克莱因。他摩擦着粗糙的凌乱胡渣，以纳闷的表情继续表示：

「说起来那个任务究竟是怎么回事？人鱼公主是老爷爷，然后老爷爷又是大章鱼，大章鱼又是深渊之王兼什么神族的，我真的完全摸不着头脑。」

「一开始的人鱼公主单纯是你的愿望吧。」

虽然反射性这么吐嘈，但我也无法立刻回答克莱因的问题。稍微瞄了一下众伙伴，发现过去被称为攻略之鬼的亚丝娜，还有对北欧神话相当了解的莉法、智慧型坦克艾基尔、莉兹贝特以及西莉卡都双手抱胸发出沉吟声。

今天──二○二五年七月二十五日，星期五。

我们为了实现结衣「想看鲸鱼」的愿望而挑战听说会出现巨大水栖型怪物的任务「深海掠夺者」。

在NPC的老爷爷请托下到迷宫里寻找道具──原本以为是这种常见的跑腿任务，但其实老爷爷才是幕后黑手，我们在不知情的情况下抢走封印在海底神殿里的宝物，不过这说起来也是常见的故事，但接下来的发展不知道该说是紧急还是超级，总之老爷爷变成拥有七条HP条的超巨大章鱼型怪物「深渊之王．克拉肯」，然后才举一只手，不对，是一只触手就轻轻松松把我们逼入濒死状态，刚浮现「没救了」想法的瞬间，又从上方降下名为「海王．利维坦」的超巨大大叔，两人进行了一段难解的对话后克拉肯就沉入深海，利维坦则回收我们从神殿拿出来的珍珠（实际上是一颗大蛋），然后就响起乐声宣告任务结束──现在想起来，依然是让人丈二金刚摸不着头脑的任务。

即使一片茫然，还是对传闻中的水栖型怪物原来是克拉肯感到失望，结果自称海王的大叔就召唤白鲸把我们送到这片沙滩来，总算是达成了让结衣看鲸鱼这个初期目标。虽然已经很值得庆祝，但也很了解克莱因表示「摸不着头脑」的心情。

沉吟了一会儿之后，我就环视伙伴们的脸并且说：

「有人正确地记住章鱼老爷爷说的话吗？」

如果是固有的MMORPG，只要在讯息视窗上卷动滑鼠滚轮就能参照任务中的对话，但是VRMMO基本上没有那么方便的机能。因此就有以水晶录下可能含有重要情报的活动对话这样的技巧，但这次实在没有这样的时间。

听见我的问题后，六个人同时歪起头来，接着就摇了摇头。

「唉，果然是没有魔法师，只有一大堆前卫的小队。」

当我夹杂着叹息这么评论时，莉兹就以投手的投球动作抬起右手，然后用食指连续指着我三次。

「你也一样！没有资格！说别人吧！」

「……是的，对不起。」

但这时候从亚丝娜肩膀上飞起来的结衣，一面摆出利维坦降临海底般的姿势一边降落在我头上。

「真拿你们没办法。虽然有点作弊，但是就由我来重现对话吧！」

随着所有人「喔喔～」的感叹声，挺起胸膛发出「耶嘿！」的声音后，小妖精才灵活地模仿章鱼与大叔的口气开始说起话来。

利维坦：「久违了，老友啊。还是一样喜欢打坏主意吗？」

克拉肯：「我才想问你这家伙要当阿萨神族的走狗到何时呢。海王的名号都在哭泣了。」

利维坦：「能够当王，我已经很满足了。而这里是我的庭院。你明知道这一点，还是想战斗吗，深渊之王？」

克拉肯：「……我今天就先离开吧。但老友啊，我可不会放弃。哪一天一定会把圣子之力占为己有，给可恨的诸神一点颜色瞧瞧，那个时候再见了……」

利维坦：「那颗蛋将来会成为支配所有海洋与天空的伟大存在。必须将其移至新的圣所才行，把它还给我吧。」

「……以上就是刚才的对话了！」

结衣结束对话的重现后，七个人就一起拍手，坐在西莉卡头上的毕娜也不停拍动翅膀。

「谢啦，结衣。」

对优秀的女儿道谢后，我再次陷入沉思并继续发言。

「嗯……令人在意的专有名词是『阿萨神族』和『圣子』吧。感觉好像在哪里听过……」

「我知道！」

迅速举起手来的是风精灵族的魔法剑士莉法。成员里面对于神话与传说类造诣最深的她，往前走一步后流畅地开始解说。

「阿萨神族是北欧神话里出现的神明一族喔！主神奥丁、雷神索尔还有喜欢恶作剧的洛基等大家应该都听过吧？」

「听过听过。」

看见六个人点头同意后，莉法也用力点头回应众人……

「那么圣子是……」

「嗯嗯嗯。」

「完全不知道！」

「唰」一声很够意思地做出跌倒的模样后，所有人就再次思考了起来。

接着发言的是猫妖族的驯兽师──西莉卡。

「嗯……也就是说，克拉肯老爷爷虽然看阿萨神族不顺眼，但是现在还赢不了祂们，所以想获得『圣子的力量』来变强……应该是这样吧。」

「连那只大章鱼的惊人怪力都敌不过，阿萨神族到底有多强啊……」

小矮妖莉兹贝特甩着带有金属光泽的粉红色头发说道。

「那是当然，对方可是神明耶。」

水精灵族的亚丝娜如此附和。这时以骄傲口气插话进来的是火精灵族的克莱因。

「没错哟，像你这样的年轻家伙可能不知道，但是奥丁可是最强等级的神明。一被召唤出来就会『滋啪』一声把怪物一刀两断……」

「喂喂，那不是神话故事了吧。」

大地精灵族的艾基尔露出傻眼的表情这么吐嘈，包含结衣在内的所有人都笑了起来。

可以理解克莱因的台词出自何处的我则是露出苦笑，然后思考起为什么这段对话总是让人感到不对劲。

答案立刻就降临了。

克拉肯与利维坦怎么说都只是任务中登场的NPC──就算其实是魔王级怪物也一样。他们的对话应该只是营运ALO的企业「YMIR」的剧本家所写的情节。

但是我们却觉得克拉肯他们说话时像是存在自己的意识一样。

其理由恐怕是因为他们说的话实在太像人类了。克拉肯嘴硬地说着「我可不会放弃」时那种悔恨的模样，足以让人觉得「这只大章鱼应该经历了许多苦难」。

或许……克拉肯与利维坦不只是普通的NPC？

我和亚丝娜在旧艾恩葛朗特的攻略初期曾经遇见女性黑暗精灵骑士并且跟她一起冒险。名为基滋梅尔的她明明是NPC，但绝不是只会重复固定台词的可动物件。她具备自然地与我们进行对话的能力……甚至拥有可以称为意识的存在。

ALO和旧SAO运用的体系结构几乎一模一样。也就是说，光看控制系统<Cardinal>的能力，还是存在跟基滋梅尔同样「高度AI化NPC」的空间。

但是，如果是这样……克拉肯就成为虽然是任务NPC，但是不按照任务剧本来行动的存在了吧？获得什么「圣子之力」，然后对阿萨神族揭起反旗是那只大章鱼自身的意志……？

「…………不会吧。」

自觉己身的思考已经逐渐进入荒唐无稽的领域，我便如此呢喃来中断推测。刚好在这个时候，正奋力在对西莉卡他们解说美好的古老年代当中，奥丁和巴哈姆特有多强大的克莱因，突然发出反常的叫声。

「啊啊啊！糟糕！我预约了十点要送披萨来！」

「喂喂，只剩三分钟喽。从这里飞到司伊鲁班要十分钟喔。」

艾基尔冷静的责难让克莱因抱住头部全力仰起身体。

「本大爷的海鲜披萨和生啤酒啊──！」

我对这很久前听过的台词感到怀念，同时走向刀使，拍了一下他和风铠甲的宽大袖子。

「我们在这里保护你的角色到消失为止，你就在这里登出吧。这次得好好地收下才行。」

结果克莱因眨了一下眼睛后，像是理解我的话代表什么意思般发出「嘿嘿」的笑声。

「说得也是。那我就不客气了，今天就在这里跟大家告别喽。」

「帮我跟披萨上的虾子、螃蟹、花枝和章鱼问声好。」

克莱因因为莉兹的发言再次露出微妙的表情，接着便打开主选单。

「那么各位，辛苦了！」

按下登出键后，火精灵的虚拟角色就自动进入单膝跪地的姿势，闭起眼睛静止不动了。

ALO里为了防止对人战的「登出脱逃」，采取了即使在练功区登出虚拟角色也会暂时留在现场的方式。当然也会被怪物当成攻击目标，下一次登入时变成残存之火的可能性相当高。

因此在圈外登出的话，一般会由伙伴来保护虚拟角色直到限制时间结束然后角色消失。幸好这片沙滩附近不会涌出太强大的怪物，于是我把视线从克莱因身上移到大家身上并提案：

「有其他人想登出的话也没关系喔。我会在这里守护到最后。」

结果亚丝娜率先露出不好意思的表情并举起右手。

「那个……我也可以登出吗……」

我虽然还没碰过面，但是听说过亚丝娜的母亲是相当严格的人，于是急忙点头。

「当然可以了，今天辛苦了！」

「嗯，今天也谢谢大家，大家辛苦了！」

迅速操作登出手续的亚丝娜进入待机姿势，接着就是表示得准备明天食材的艾基尔、有想看的电视节目的莉兹，还有要完成今天回家作业的西莉卡希望立刻登出，所有人同时离开了精灵乡。

等西莉卡进入待机姿势，毕娜就像要保护她的虚拟角色般在她头上开始左顾右盼，心里想着「真了不起……」的我就伸了一个大大的懒腰。

结果就和同时摆出相同姿势的莉法四眼相对。

不知道为什么同时笑了起来后，我就朝西方的水平线看去。

曾几何时太阳已经完全消失，水平线附近只剩下深红色。坐在我头上的结衣以肩膀作为跳板来跳进我胸口的口袋，然后可爱地打了一个呵欠。

「……鲸鱼先生真的很大呢，爸爸。」

小妖精以睡意十足的声音这么说道，我则是用指尖轻轻抚摸她的头部。

「嗯嗯。哪天再让它载一程吧。」

「好的……」

点完头就闭上眼睛的结衣，立刻就发出细微的鼻息声。

其实结衣是独立于ALO系统之外的AI，并不需要像人类一样睡觉，但是有大量的情报输入，而且没有需要紧急处理的案件时，她大多会像这样子进入睡眠状态来整理记忆。现在结衣应该在梦里回顾今天的冒险吧。

隔了一会儿，先是克莱因，然后是亚丝娜、艾基尔、莉兹、西莉卡以及毕娜都变成光粒消失了。

我随意对莉法伸出右手并且表示：

「那么小直，我们就一起飞回司伊鲁班吧。」

结果我的妹妹就轻噘起嘴来说：

「我说哥哥啊，又不是在水里，不用牵手我也会飞喔。」

「啊……对……对喔。抱歉，一不小心就……」

但是金发魔法剑士又轻抓住我准备缩回去的手。

「但是我比哥哥更擅长飞行，接下来就由我拉着你吧！」

「……那……那就拜托了。」

我们同时张开翅膀，飞离逐渐染上紫色的沙滩。

把视线往东北方移去，就看见世界树以开始闪烁的星空作为背景的巨大剪影浮现，其前方的绿色光群就像宝石一样辉煌。是令人怀念的风精灵族首都──司伊鲁班。

确认结衣确实待在口袋里头之后，我就跟莉法互相点点头，然后开始乘着海风缓缓飞了起来。

2

「…………延还虎此……」

我用力咬着弹力十足的乌龙面，同时以模糊的声音这么呢喃。

结果坐在餐桌对面的直叶就抬眼看向这边。

「哥哥，这样太没教养了。」

右手拿着筷子左手拿着平板电脑的状态确实不应该在用餐时出现。但是我把嘴里的乌龙面一口吞下之后……

「我认为乌龙干面是可以边做别的事边吃的哟。」

「……那咖哩乌龙面呢？」

「不行。」

「……豆皮乌龙面呢？」

「可以。」

「……锅烧乌龙面呢？」

「不行。」

「完全搞不懂你的基准……」

插图p151

叹了一口气后，直叶就啜了一口凉拌乌龙干面（配菜是温泉蛋、蒸鸡肉、水煮虾、秋葵、海带芽根部、青紫苏、碎海苔）。

我们大约是在十五分钟前登出ALO。母亲就跟平常一样还没有回家，所以虽然时间已晚，还是由我们两个人自己煮晚餐，不过感觉最近太过于偏向「立刻能煮好事后收拾也简单」的路线。

明天至少煮个三样菜──如此暗暗下定决心后，桌子对面就再次有声音传过来。

「那么，到底是什么原来如此？」

花了一秒钟才理解这个问题是对我「延还虎此」的发言所提出。

「……亏你听得出来刚才那是『原来如此』耶……没有啦，我是在说阿萨神族的事情。」

「啊，你马上查了吗？」

「其实只是大概看了一下。」

把线上百科全书显示该当项目的平板电脑递给直叶后，我就开始检讨是要夹破保留下来的温泉蛋，让蛋汁流到乌龙面上，还是直接把蛋一口吃下。但是在我得出答案之前，直叶就骄傲地用鼻子发出哼哼的声音。

「……怎么了？」

「哥哥你这样不行喔。怎么可以因为这点情报就说原来如此呢。上面明明只写了一点皮毛呀。」

「是……是这样吗？」

「嗯。真的想知道的话，就得从主神奥丁的父亲巨人包尔，以及他的父亲──最初的神明布利开始才行……嗯，首先呢，北欧神话里面，世界的起源是从名为金伦加鸿沟的巨大裂缝开始……」

「停……停下来。世界的起源等下次有时间时再好好听你讲解吧。好了，不快点吃的话乌龙面会变软喔。」

被我打断之后，直叶脸上虽然露出不满的表情，但还是乖乖放下平板电脑再次拿起筷子。她毫不犹豫就夹破温泉蛋，让面浸到浓稠的蛋黄里。那金黄色的光辉实在太美丽，于是我也跟她做出同样的动作，然后大口吸起乌龙面。

虽然对打断难得的讲座感到不好意思，但目前并不需要那么详尽的知识。因为我目前在意的──并不是或许存在于ALO的阿萨神族之国，而是「深海掠夺者」任务究竟有没有后续。

完全被克拉肯欺骗的我们从海底神殿取出「圣子之蛋」，而利维坦则说要把它「移至新的圣所」并且把它带走。但是感觉事情并非到此就有完美的结局。完全搞不懂那个圣子之类的到底是什么──既然是从蛋里生出来的，应该不是人类吧──克拉肯也似乎还没有放弃，最重要的是不对那只大章鱼报一箭之仇实在难消心头之火。

虽然多少参杂了一点私情，但那果然不是单次的任务，而是活动任务的导入部分吧。

通常活动任务是在解完一个任务后就会给予下一个任务，标示会明示新的目的地。但偶尔会有必须自己从之前获得的情报推测该前往何处以及该做什么事的情况。

如果这次的活动是这种类型的话，克拉肯与利维坦的对话当中，应该会提示承接下一个任务的地点……才对……

「……哥，哥哥啊。」

直叶叫了好几次之后，陷入沉思的我才终于回过神并抬起头来。

「啊，什……什么事？」

「我想你应该没有忘记，明天从早上就要开始道场的大扫除喔。今天晚上不能熬夜，必须早点睡才行。」

我当然已经忘记，但完全没有表露出来就点头回答：

「了解了，一点……不对，两点就一定会睡了。」

迅速躲开妹妹怀疑的视线后，我就随着吃完的空盘子逃到厨房。

躺在自己房间的床上，从反方向往上看着床头板上的闹钟。

二十三点三十分。旧艾恩葛朗特时代，这个时间正处于「夜间攻略」当中，我通常都躲在高效率的练功场持续挥着剑。

当然，在阿尔普海姆也必须努力提升实力（虽然ALO没有等级）。由于我曾经重置过一次继承自SAO的能力值，所以也有为了追上亚丝娜他们而努力狩猎的时期。

但是过去那样的危机感──为了存活而升等这种紧张的动机已经不复存在了吧。

不用说也知道这是很幸福的事。我绝对没有「想回到那个世界」的想法。

但是我的内心某处似乎持续冀求着某种是游戏也非游戏……某种在虚拟世界的箱庭里带来令人屏息的「真实」的事物。

被克拉肯一击逼入濒死状态，差点就要全灭时，利维坦的三叉戟从天而降的那个瞬间，我感觉到了「某种」气息。感觉像是结局早已固定的活动，但实际上是不属于任何人为剧本的偶发性发展…………

「……没有啦，只是觉得如果是这样就很有意思……」

像是要隐藏害羞般如此自言自语，我就为了明天的大扫除而关上电灯准备早点就寝。

经过十秒钟左右，我便用手摸到AmuSphere并且把它戴到头上，小声咏唱出语音指令。

「开始连线。」

3

以我的基准来说，两点就寝已经算很早睡了。

做出这样的藉口一边降落到司伊鲁班的我，发现该处跟现实世界一样已是夜幕低垂。

只不过对大部分的网路游戏玩家来说，接下来才是黄金时段，风精灵领地首都司伊鲁班的大路上聚集许多精灵而显得相当热闹。当然大部分都是风精灵，但是跟以前相比已经能看到不少其他种族的玩家了。

从用来登出的旅馆窗户眺望马路，发现其他种族的玩家果然是以缔结同盟的猫妖为大宗。接着是领土靠近的音乐精灵族与暗精灵族。虽然地理上来说也与火精灵的领土相邻，但现在官方依然处于战争状态，所以当然看不见红色的头发。

我隶属的种族守卫精灵虽然没有跟风精灵敌对，但领土是在隔着世界树的边陲。而且原本就是不怎么有人气的种族，所以跟火精灵一样，大路上看不见任何守卫精灵。

我思考着怎么做才能在不引人注意的情况下移动到目的地，最后从道具栏取出连帽斗篷来套了上去。接着又咏唱了幻影魔法「月影潜行」才蹑手蹑脚地走出旅馆。

虽然月影潜行魔法是只有在月亮形成的阴影里面才比较不容易被人注意到（也就是说月光原本就照不进去的迷宫根本无效）这种性能微妙的隐蔽咒文，但我的魔法技能最多就只能做到这样。幸好今天有朗朗满月挂在天空绽放光芒，由于司伊鲁班里头的狭窄巷弄多到了极点，所以我便尽量不离开影子并小跑步前进。

移动了几分钟后来到市中心的我，先是在阴影里停下脚步，接着看向前方。

眼前有一条直径应该有一百公尺以上的圆形道路，其中央耸立着司伊鲁班最美的建筑物──风精灵领主宅邸。三层楼高的宅邸被深邃的护城河包围，只靠北方与南方两条桥梁与道路连接。整条圆形道路在蓝白色月光照耀之下，根本没有任何可以藏身的影子。

两条桥的尽头都有看起来非常强大的两名NPC守卫高高举着斧枪站在那里。只有登录在领主宅邸名簿上的名字才能通过那里。

虽然我记得莉法也登录在上面，但就算组成小队，外人依然无法进入。既然有翅膀，似乎可以从守卫的视线之外飞越护城河，但是当然无法使用如此简单的手段，领主宅邸用地内张设了让外人包含飞行能力在内的所有魔法全都失效的结界。

虽说本来就不是要来这里偷东西，只要抓住出入的工作人员请他帮忙入内通报一声才合乎礼仪，但是想极力避免今晚的访问之后变成谣言传达出去。

「…………！」

思考到这里时，我就察觉等待的瞬间来临，于是压低了身体。

从右侧开始有黑影覆盖在夜空一角发出蓝白色光芒的月亮。是阿尔普海姆每天晚上都会发生的人工月蚀。在高空绕着阿尔普海姆公转的浮游城艾恩葛朗特，有短短数十秒钟会和月亮重叠。而且仅有五秒钟的时间会完全遮住月光。

蓝白色圆盘缓缓出现缺角，最后所有的光芒完全消失──也就是司伊鲁班完全陷入艾恩葛朗特影子的瞬间，我就从巷弄里冲出去。

这个商店较少的区域行人也比较少，但是绝对不是完全没有其他玩家。使用「月影潜行」的我应该不会被看见，不过还是一边祈祷脚步声不会被耳朵灵敏的猫妖族听见，一边瞬间横越圆形道路。在两条桥的中间地点将右脚放到分隔护城河与道路的铸铁栏杆上然后全力跳跃。

来到漆黑的水面上时，已经无法使用翅膀与魔法。根据传闻，宽将近十公尺的护城河里面躲藏着恐怖的水栖型怪物，会在水底把掉落的玩家变成无人闻问的残存之火。届时残存之火的出现地点是在护城河前面，如果变成这样，想要入侵的意图就会被发现了。

即使是身轻如燕的守卫精灵，也不可能在没有飞翔力的帮助下跳过十公尺的距离。我在空中拔出背后的剑，在坠落的情况下尽力把它往前伸。剑尖在千钧一发之际刺中对岸的石砖。

如果这是滚落在练功区上的岩石，那么大师级铁匠莉兹贝特的剑应该能轻松将其切开吧，但是城里的建筑物是不可破坏物件。于是我便反过来利用这一点，用力把剑尖往下压到砖头上，再利用反弹的力量让身体浮起来。

左手好不容易以追加的小跳跃构到对岸。我把剑收回背上后迅速爬了上去。剑尖压到石头上时虽然发出细微的金属声，幸好桥上的守卫没有动作。

再次压低身体跑了起来，当我躲到庭院树木阴影的瞬间，短短的月蚀也结束了。

「…………呼。」

轻呼出一口气的我，仰头看着眼前的领主宅邸。目的地就是最上层的中央部。虽然不清楚想找的对象在不在那里，但不在的话也只能等待一阵子了。

接下来已经无法获得月影潜行咒文的保护。祈祷着建筑物里面不要有守卫，同时把背后的剑收纳到道具栏之后，我就偷偷摸摸地朝开阔的正面入口前进。

五分钟后──

在好不容易抵达领主宅邸三楼一扇雄伟的双开式大门前面，我再次确认着左右的状况。

宽敞的走廊上看不见人影。看来大部分执政部玩家都在二楼大厅谈笑当中，虽然在没有被任何人发现的情况下爬到这里，但接下来要见的人物不在的话一切努力就白费了。祈祷幸运能持续到最后的我，把头罩往后掀后就敲了两下门。

隔了一会儿……

「请进。」

一道听过的声音如此回答。松了一口气的我拉动银色门把，在最小的缝隙下钻进门内。

当我随手把门关上时，在正面的大桌子前操作领主专用视窗的女性玩家也正好抬起头来。

身穿优美和服般装束的风精灵族女性领主──朔夜认出是我后，首先皱起形状姣好的眉毛接着歪起头，最后倏然立起右手的食指。

「为了慎重起见，我可以先确认一下吗？」

「请尽量问。」

「你不是被火精灵族雇用……到这里来取我首级的吧，桐人？」

「咦……系统上可以这么做吗？也就是说，身为守卫精灵的我，把杀死领主的奖励让给火精灵……可以做到这种事情？」

「可以喔，只要成为正式的雇佣兵。不过那个时候会跟火精灵一样，街上的守卫会有所反应，没有通行徽章的话应该走不到一百步吧。」

「这样啊……啊，没有啦，答案当然是NO。」

举起双手来显示没有敌意，同时说出来到这个地方的目的。

「其实是有件事情想请教朔夜小姐。」

「…………只是因为这个理由就入侵领主宅邸？」

「呃，嗯……因为我没有跟朔夜小姐登录为朋友，所以无法传送讯息……而且也不想问的事情被别人听见……」

以类似恋爱喜剧中女孩子会说的台词来说明整件事情后，领主大人先是轻轻摇头才又点头说：

「…………原来如此。但是我怎么说也是领主。就立场上来说，能跟身为异种族的你说的事情有限。就算你是救命恩人也一样。」

「啊，这你不用担心。因为我不是要你告诉我风精灵族的军事机密。而且，我当然也准备了等价交换用的情报。」

「哦？你要告诉我什么？」

「潜入风精灵领主宅邸的方法与对策。」

结果朔夜眨了眨眼睛，接着高声发出「哈哈哈」的笑声。只能祈祷她的笑声不要传到楼下去了。

我小口啜着领主亲手帮忙倒的，看起来很高级般的葡萄酒，然后再次从头说明没有联络就到此访问的理由。

默默听着我说话的朔夜，当我叙述完毕后就缓缓点头。

「十天前左右，我也完成『深海掠夺者』任务了。」

「咦，领主大人亲自……吗？」

「我偶尔也会想潜入迷宫啊。而且，我不是也参加过好几次艾恩葛朗特的楼层魔王攻略了吗？」

「对……对喔。」

「但是…………」

行动派的领主一口气喝光葡萄酒，然后微微歪着头说：

「我和执政部成员们一起进行那个任务时，克拉肯和利维坦都没有出现喔。」

「咦？」

「把在神殿发现的那个不知道是珍珠还是蛋的物体交给老爷爷NPC后，他很平常地道谢然后任务就结束了。然后那个老爷爷就召唤出巨大的大王乌贼，那个家伙用触手把我们抓住并且送到海边……老实说不是什么愉快的体验。」

「大……大王乌贼吗？老实说那还真的有点想看看……不对，那个……总之就是要不要把珍珠交出去所造成的剧情分歧吗……」

「看来是这样。应该说，一般都会交出去吧。」

面对苦笑的朔夜，我也露出苦笑来回应。

「没有啦，我本来也准备交出去……但是快交出去前就被亚丝娜拿走了……」

「哈哈，真的不能小看她的第六感。」

看着不停点头的我笑了一阵子后，朔夜又帮我倒了一杯葡萄酒并且开口表示：

「关于任务的分歧路线一事我知道了。那么……你到底想问我什么事情呢？」

「嗯……总而言之，就是想问你知不知道利维坦所说的『新的圣所』在什么地方……比如说，除了之前那栋海底神殿之外，其他的海底是不是有类似的建筑物呢……」

「唔嗯……我一时也想不出来……」

领主稍微思考了一下后就操作起专用视窗，让一张地图显示在整张桌面上。那张阿尔普海姆全图比我们这些平民百姓所能叫出来的详细了好几倍。

「其实这说起来也算是机密，不过就算了吧。这张地图上记载了已经发现的任务，以及看起来有古怪的建筑物、石碑、捷径等所有特异点。在这里搜寻『圣所』的话……」

雪白手指在地图上闪动，搜寻视窗上立刻显示出结果。搜寻结果是零。

「那么『圣子』……也没有。『克拉肯』……『利维坦』……两个都没有。」

「『蛋』的话呢？」

「那样搜寻范围太大了吧……你看，有一百个以上符合的结果。找寻、保护、毁坏、烹煮某种蛋的，这类型的任务有一大堆呢。」

「这……这样啊……嗯……」

我一边凝视着精灵乡的平面图，一边在脑袋里重播海王与深渊之王的对话。

久违了，老友啊……要当阿萨神族的走狗到何时……哪一天一定会把圣子之力占为己有……将来会成为支配所有海洋与天空的伟大存在…………

──所有的海洋与天空。

「那……那个，朔夜小姐。」

「什么事？」

「那张地图记录了特异点的三次元座标吗？」

「那是当然。」

「那么可以请你先告诉我位于最低处的点吗？啊，幽兹海姆除外。」

点完头的朔夜迅速把情报分类。

「最低的座标是负九十八公尺。任务名称是……『深海掠夺者』。」

领主的眼睛闪过光芒。我也向她点点头，然后说出下一个要求。

「那么接下来是最高处的点。艾恩葛朗特除外。」

「……这个就根本不用搜寻。」

「咦……？」

「因为答案很清楚了。位在阿尔普海姆最高处的谜团……」

美貌的领主以左手大拇指指着背后的大窗，咧嘴笑着说：

「那就是世界树的顶端。」

4

三个月前──二○二五年四月。

VRMMORPG「ALfheim Online」由新营运公司YMIR进行了大规模的改版。

浮游城艾恩葛朗特的上线、旧SAO帐号的统整，以及废除飞行时间限制。

过去连世界树最下方的树枝都无法自行抵达的精灵们，现在甚至可以飞到遥远高空中的艾恩葛朗特。但是获得无限飞行力的玩家们率先前进的不是新的浮游城，而是阿尔普海姆最高处──世界树的顶端。

但是就结果来看，不要说抵达了，甚至连看见该处都无法实现。

那是因为世界树顶端被巨大的积雨云覆盖，猛烈的暴风与雷电顽强地拒绝所有入侵者。从树干爬上去也是相同的结果，闯入云层几秒钟后，不是被雷公劈死，就是被大风吹到虚空中。

虽然应该是取自某名作动画的发想，不过那些玩家间称为「雷龙之巢」的巨大积雨云，已经很久没有不怕死的冒险者赶去挑战了……

「……嗳，桐人啊。」

站在旁边的亚丝娜笔直仰望上空这么说。

「冲进那些云里已经死几次了？」

「嗯……死不到十次吧，应该啦……」

「那么，每次都用魔法帮忙回收残存之火的是谁？」

「是亚丝娜小姐……」

「那么，陪你狩猎弥补死亡惩罚的又是谁？」

「亚丝娜小姐……」

「很好，记得很清楚嘛。」

我以僵硬的笑容来回应露出灿烂微笑的水精灵回复术师。

「那……那是当然了。我感谢亚丝娜的次数，比克拉肯八只脚上面所有吸盘加起来还要多喔。」

「……听了也不会觉得高兴的比喻耶……」

以微妙表情这么呢喃完，亚丝娜就再次仰望天空。

七月二十六日星期日，下午两点。

新设置在世界树中央部的空中都市，世界树城市南端展望台上，除了我们之外就看不见其他玩家的人影。以前就有多数的挑战者从这里出击，但是现在包围世界树顶端的巨大积雨云仍跟过去存在于根部那个守护骑士的巨蛋一样属于无法突破的区域。

那个巨蛋是前ALO管理者须乡伸之，为了隐蔽私人流用伺服器资源与违法实验而把难易度提升到不合理程度后的产物。但是新营运企业YMIR不可能把什么人幽禁在世界树的顶端才对。

之所以无法突破积雨云，是因为没有满足设定条件……反过来说，只要能够立起旗标，就可以在肆虐的暴风与激雷当中打开一条路吧……

「久等了～！」

突然从下方传来气势十足的声音，下一刻，一道绿色影子就像擦过展望台的扶手般横越视界。

在头上灵巧地空翻后降落到我和亚丝娜眼前的，是速度中毒者的风精灵剑士小姐。看来是从昨天登出的司伊鲁班全力飞翔到这个世界树城市来了。

稍微瞄了一眼时间显示的莉法，很懊悔般说了一句「还是超过四十分钟了吗～」。两地的距离大概是七十公里左右，所以不保持时速一百公里的话就无法在那个时间内抵达。

「哇啊，不愧是莉法。我和桐人花了将近一个小时喔。」

亚丝娜以惊讶的表情这么说，我那个纯朴的妹妹就骄傲地挺起胸膛表示：

「这是有诀窍的哟。风向会因为高度与时间而改变。为了尽量处于顺风状态，必须不断修正轨道才行。」

「这么说你记住所有风向了吗？太厉害了……桐人甚至边飞边打瞌睡，直接就冲进一群赛拉斯梅杜莎里面。」

结果莉法的态度为之一变，改成以险恶的目光看着这边并且说：

「这个人昨天晚上似乎独自再次登入，在司伊鲁班不知道做了些什么。突然就想再次挑战『雷龙之巢』似乎也是因为获得了新的情报喔，然后还不愿意告诉我详情。」

结果连亚丝娜都露出怀疑的表情，我只能以刻意的干咳声来把事情蒙混过去。

之所以被直叶发现我在深夜中潜行，是因为今天早上两个人在剑道场大扫除时，我不停打着大大呵欠的原故。当然我没有提及昨天晚上干的好事──入侵领主宅邸，但是感觉这件事不久之后也会露馅。

不过冒了这么大的危险也算值得了。如果不和朔夜见面，让她给我看了极机密的世界地图，绝对不会注意到「新的圣所」可能存在世界树的顶端吧。

然后一旦发觉了当然不可能按兵不动。大扫除结束之后就呼叫平常的伙伴──只不过很可惜的是因为在白天，艾基尔与克莱因无法参加──来到这个展望台集合。

当我想着「莉兹和西莉卡可不可以快点来」，并且漫无目的地眺望着流过的云时，我胸口口袋就轻轻飞出救赎的女神。

她伸直小小的双臂，伸了一个可爱的懒腰之后才发出银铃般的声音飞起来。她降落在亚丝娜的左肩后，带着笑容对我们打招呼。

「爸爸、妈妈、莉法小姐，早安！我有点睡过头了。」

我们家这个以腼腆表情发出「嘿嘿嘿」笑声的女儿看起来实在可爱极了。原本进入追究模式的两名女性也立刻展现笑容。

就这样谈起昨天那只鲸鱼的回忆，最后莉兹贝特与西莉卡也从西南方飞过来。成员到齐了之后就开始进行作战会议。

「……说起来也不是什么大不了的作战……我会冲进『雷龙之巢』，阵亡的话就请用魔法帮忙回收，大概就这样吧……」

玩家死亡后的残存之火基本上必须由小队成员用手抓住才能移动，但使用一部分高等魔法或者稀有道具，就能够从远距离进行回收。想要直接回收留在「雷龙之巢」里面的残存之火，有很高的机率会出现新的牺牲者，所以必须从云外用魔法把残存之火拉出来。

当然经过一定时间后，就会在记录的位置自动重新复活，但是跟让其他人复活的情况比起来，死亡惩罚将会大幅增加。虽然有了死亡一两次的觉悟，但能减少一些惩罚当然比较好。

──听见我的攻略计划后，女孩子们暂时面面相觑，然后首先由莉兹贝特开口说：

「呃……我想先确认一下很基本的事情……你之所以想到世界树的顶端去，是因为那个巨大珍珠，不对，是『圣子之蛋』可能在那里对吧？」

「嗯。」

点完头后，这次换成西莉卡抖动三角形耳朵开口询问：

「但是桐人哥，如果找到蛋的话，你打算拿它怎么办呢？不会想再次把它偷出来吧？」

「嗯……嗯。」

我再次点头，然后追加说明。

「目标也不能说是蛋啦……正确来说，我在想是不是能承接昨天进行的『深海掠夺者』的后续任务。我实在不认为那是一般的单次任务……」

结果这次换成亚丝娜以思索的表情晃动着水蓝色头发。

「或许是这样没错……但是一般来说，有后续的任务在地理上也会有关连吧？昨天的海底神殿到今天的世界树顶端，直线距离有一百公里以上喔。就算『所有的海洋与天空』是提示，得出的结果也太跳跃了吧。」

不愧是在旧艾恩葛朗特被称为「攻略之鬼」的玩家，提出的论点相当合理。

存在于阿尔普海姆的所有特异点当中，最深的是昨天去过的海底神殿，最高的就是「雷龙之巢」了──虽然想说出这样的根据，但是这个资料是风精灵执政部的机密情报，而我本来是不可能得知这样的情报。

当我犹豫着是不是该坦承昨天晚上偷偷闯进领主宅邸一事时──

「…………那个……」

吞吞吐吐地这么说道的，是坐在展望台扶手上的莉法。

她环视四个人的脸庞，再次从感叹词开始发话。

「那个……我昨天晚上作梦了。是从天空很高的地方降下彩虹桥的梦。大步从那条桥爬上去后，前方可以看到一座非常大又很漂亮的门……但是在到达那里之前我就醒过来了。」

说完就露出有些害羞的微笑，同时将视线移向蓝天。

「之所以会作这样的梦，一定是昨晚在风精灵领地的海岸上和大家一起谈到阿萨神族的缘故……根据神话，阿萨神族是住在名为『阿斯嘉特』的国度……」

「那是跟阿尔普海姆与幽顿海姆同样意思的『国家』吗？」

我这么插嘴问道后，莉法就看向我点了点头。

「嗯。北欧神话里的世界分为九个国度，其他还有华纳神族居住的『华纳海姆』、冰之国的『尼福尔海姆』等等……然后在遥远上空的阿斯嘉特有一座连结地上的彩虹桥。桥的名字叫作『碧芙雷斯特』……」

风精灵魔法剑士晃动着金色马尾，再次仰望头顶。

「……我从一开始看见『雷龙之巢』，就不由得想像说不定那些云里面有一座彩虹桥，然后连结着阿斯嘉特……」

「哇……好浪漫啊！」

让毕娜坐在头上的西莉卡，这时候眼睛闪闪发亮并这么大叫。

「如果是这样，我也绝对想看看……不对，是想走走看！」

莉兹、亚丝娜以及结衣都笑着点点头。

另一方面，我则是发出沉吟声并且思考了起来。

从克拉肯与利维坦的对话来看，这个ALO世界存在阿萨神族NPC的可能性相当高。如此一来，或许……他们的国度阿斯嘉特也确实存在，但是从MMO游戏的角度来思考，有新的大规模地图上线了却没有大肆宣传的情况实在不太可能出现。

实际上，地底世界幽兹海姆公开时，官方网站与新闻网站都进行了大量的宣传，甚至还举行了纪念活动。说起来呢，明明花了不少预算与时间制作了新地图，却用无法突破的暴风来覆盖移动用的大门让任何人都无法通过究竟有什么意义呢？

──不对。

现在在这里做出一连串否定的推测也没用。积雨云的后面是彩虹桥还是圣子的蛋，又或者两者都有……一切都得等到突破云层之后才能知道。

「那么我会看个清楚……」

「所以我也要去！」

莉法迅速举起右手来打断我的话。结果除了亚丝娜她们之外，连结衣都同样高高地举起手来。

「既然这样，那就大家一起去吧！」

「就这么决定了～！」

我急忙对着气氛热络的女孩子们搭话道：

「等……等一下。如果全灭的话，谁要负责回收残存之火啊？」

「我偶尔也想离开后援的位置到前卫去呀。」

听见亚丝娜以稍微闹别扭的口气这么说，每次都靠她在后方支援的我当然无法反驳。

亚丝娜立刻恢复笑容，开朗地表示：

「如果全灭的话，回到城里之后再大家一起去狩猎即可。这些成员的话，马上就能取回死亡惩罚丧失的经验值了。」

──把人找过来后才说「自己要去危险的地方请在此待机」确实太过自私了。比解开任务的谜更重要的是──大家一起享受冒险。

「……说得也是。那就大家一起去吧！」

我点完头后，四个人与结衣、毕娜就同时气势十足地叫起来。

「喔～！」

确认装备之后就从展望台起飞。

从像迷宫般互相纠缠的巨大枝叶之间飞向天空。组成由我领头的V字形编队，一直线往上升。

今天的阿鲁恩高原天气晴朗，周围的天空看不见一丝云朵。但是沿着世界树的斜面持续飞了几分钟后，前方就开始弥漫着白色霭气。竖起耳朵就能听见远方传来隆隆雷声。

「马上就要到喽！」

对众伙伴这么大叫完，我便放慢速度。穿越作为警告区的薄霭层后，视界就全部都是巨大的纯白块状物──也就是「雷龙之巢」了。锐利地往上伸展的世界树前端笼罩在直径和高度都有五百公尺的积雨云底下而完全无法目视。

张开翅膀煞车后开始在空中悬停。

现实世界的巨大积雨云，其直径有十公里，高度似乎也是它的两三倍，但像这样在至近距离下往上看，就觉得虚拟世界的积雨云在迫力上也不输给现实世界。虽然以前就冲进去过好几次，但现在也再次因为兴奋而发抖──

停在左侧近处的西莉卡以快活的口气表示：

「哇啊，好厉害！看起来好像生奶油一样美味耶！」

莉兹贝特也赞同她的感想。

「真的很想把它放到松饼上，然后淋上满满的糖浆来吃吃看。」

接着在右边停下来的亚丝娜则边笑边说：

「啊哈哈哈，那等这里结束我们就去吃吧。世界树城市似乎开了很美味的松饼店。」

「真的吗？我超爱松饼！我要吃十片！」

最后是莉法这样的发言为话题做总结。

是该为她们的轻松感到可靠还是不安呢。话说回来，受到死亡惩罚后要去狩猎的话题怎么消失了？

不对不对，那是全灭时的事情。我们要顺利突破云层，找到后续任务与彩虹桥，然后用松饼来好好庆祝。

重新振作起来的我……

「那我要吃一百片！」

做出这样的宣言后，再次把粗略的作战传达给众伙伴。

「就我死过十次的经验，不可能避开雷击。与其胡乱变更路线而浪费时间，倒不如以最快速度突破还比较好。云朵里面根本看不见东西，为了笔直飞行，让我们排成『星星』吧。」

「了解！」

亚丝娜她们点点头，结衣就跳进我胸口口袋，毕娜则像推进器一样紧贴在西莉卡背后。

五个人围成一个小圈圈，然后不是跟身边的莉法与莉兹贝特，而是跟正面的亚丝娜与西莉卡牵手。大家都一样这么做的话，十条手臂就会交叉画出星形。这是名为「星形结合」的团体飞行技，人数虽然仅限五人，但是跟水平结合与圆形结合比起来，不但可以形成坚固的一体化，还能提升速度与直行的安定性。

问题是就这样水平飞行的话，至少有两个人会变成背面飞行，于是就由较有经验的我和莉法来负责。在组成队形的情况下缓缓前进，到达积雨云的高度后，为了慎重起见──或者为了能放宽心而让亚丝娜咏唱增加雷电抗性的咒文。

「好……开始倒数。5、4、3、2、1……」

最后由所有人共同大叫……

「「「「「Go！」」」」」

五对翅膀迸发出五色光辉，我们就像被大炮发射出去一样开始加速。

在三百公尺的助跑下达到最快速度，直接冲入巨大积雨云中。一开始染白的视界立刻逐渐变暗，空气跟着增加湿度与密度，让飞行速度变慢。

「……要来喽！」

在我这么大叫并咬紧牙关的同时──

传出「嘎嘎啊啊啊啊嗯！」的惊人巨大声响，短短三公尺外的空间被粗大的紫雷贯穿。首次闯入「雷龙之巢」的莉兹与西莉卡虽然发出细微的叫声，但是加速没有中断。所有人的手还是紧紧互握，像暗夜一样一直线刺入黑暗空间。

接着袭击过来的是横向暴风。只有一个人的话或许会因为遭到猛力吹动而失去前进方向，但我们则靠着五个人的重量与推力来突破难关。

极近距离再次出现炫目的闪电，然后又接连两次。

闪电的轨道看起来是不规则，但应该不是这样。因为人数应该多达数千人的挑战者毫不例外地全被击退了。入侵这些积雨云的玩家，快的话一秒，慢的话也在十秒内绝对会被闪电击中而立刻死亡。根本无法回避与防御。

但是──如果我的推测正确的话。

利维坦所说的「新的圣所」存在于这些云层后面的话。

我们就能突破这阵风暴。虽然没有根据，但我是如此相信的。甚至能超越系统规定的死亡区域的「某种东西」……一定可以触碰到在创造出来的虚拟世界里，产生真正故事的「某种东西」……

嘎嘎嘎啊啊啊啊嗯！

不知道是第几道的紫雷从前方袭击，像龙一样扭动身躯掠过我们身边往后方冲去。在视界被烙印成一片白色，所有声音逐渐远去当中，持续以甚至可以甩开恐惧的速度飞行。

还没经过十秒钟吗，还是已经超过了呢？这些雷云到底要持续到什么时候……

此时在我右边的莉法以超越雷鸣的声音大叫：

「正下方有强风吹过来了！不要抵抗，乘着风飞行吧！」

下方──这就表示对背面飞行的我们来说是背后这一侧。有了这种认识的同时，猛烈的暴风就袭击了过来。我们拼命握紧呈星形结合的手，抵抗着剧烈的摇晃。

「………………就是现在！」

莉法出声的同时，我便用尽全力振动翅膀。

从水平飞行急转弯后开始上升。虽然振动变弱了，相对地飞行速度却加速到过去未曾体验过的领域。好几道闪电从前方降下来。要是胆怯而减速一定会被击中。

「冲……啊啊啊啊────！」

我挤出声音来吼叫。

星形结合除了直接握手的两个人之外，手臂也确实跟其他两个人交错。从触碰的肌肤传来伙伴们的勇气。

我们变成拖着五色尾巴的彗星往前猛冲。四道闪电贯穿前后左右，再次将视界染成蓝白色。这次的视觉特效久久没有消失。周围甚至越来越白，越来越明亮──

下一刻，甚至连声音都消失了。

暴风的怒吼、雷电的闪光等等全都远去。在像作梦般的寂静当中，我瞪大了原本眯起来的双眼。

首先看到的是垂直耸立的白色墙壁。这形状不固定的萤幕映照出我们持续上升的影子。

把视线移向在正面互握着手的亚丝娜和西莉卡，发现两个人也瞪大了眼睛。虽然在意她们看见了什么，但是在星形结合的状态下，我无法看向自己的背后。

「……我想已经可以解开编队了。」

由于亚丝娜以呢喃声这么说，我就一边减速一边放开双手。星星一分离，莉法和莉兹就同时转过头。

纯白色的广大球形空间就在眼前。

直径大约是三百公尺左右。有一根绿色柱子垂直贯穿中心部。柱子的根部陷入白色墙壁中，可以看见尖锐的顶端在天花板附近。

不会错。那根柱子是──

「世界树的……顶端……」

莉法以沙哑的声音这么呢喃。

也就是说，我们突破击退所有玩家的「雷龙之巢」了。这里是包裹住世界树前端的巨大积雨云内部。

「好像在作梦……」

依然瞪大眼睛的亚丝娜也按住嘴角并做出这样的发言。我们面面相觑，一点一点露出笑容，同时为了大叫「成功了～！」而大口吸进空气。

但是──

在大叫之前，从我胸前口袋飞出来的小妖精就以紧张的声音喊道：

「爸爸，有什么东西过来了！」

「…………！」

所有人立刻摆出备战姿势。我从背后拔出剑，眼睛在四方巡梭。

云之巨蛋几乎笼罩在完全的寂静当中。在背后的云里面发出巨响的雷鸣也完全传不到这里。能听见的就只有巨蛋内的微风让世界树树叶摇晃的安稳摩擦……

──不对。

不知道从哪里传来一道「喀滋、喀滋」的声音。那不是金属声，而是像用木棒击打厚实玻璃板般刚中带柔的声响。

「啊……那里！」

莉兹贝特指着斜上方这么说。

虽然看不见太阳，但是充满云之巨蛋最上层的白色光辉让我眯起眼睛。光芒之中有一道小小的剪影靠近。看起来不是怪物。穿着宽大长袍的来者，跟我们一样是精灵……不对，是人类……？

背上明明没有翅膀，却像空中有透明阶梯一般，响着喀滋喀滋脚步声走下来的是一名高瘦的青年。泛蓝的银色长发整个往后竖起，额头上戴着细长环饰。对方看起来没有携带长剑或是法杖，但是我们却遭到足以令人屏息的压力袭击，只能一点一点往后退。

相对地青年还是维持一样的速度，往下走到同样的高度后，就在仅仅五公尺外的空中停下脚步。伶俐的俊美容貌中，金褐色眼睛绽放出锐利的光芒。

在青年发出声音的同时，他的头上也出现浮标。

「把剑收起来，精灵们。」

优美的声音令人联想到经过锻炼的钢铁。显示出来的名字是──「Hraesvelg the Sky Load」。

「……空之王……赫拉斯瓦尔格……」

我右侧的莉法如此细声说道。

感觉好像是在哪里听过的名字，但是在挖掘记忆之前，我就先用手肘戳了一下露出茫然模样的妹妹左侧腹。

「呜咕……做……做什么啦！」

「剑啦，把剑收起来！」

小声做出指示的我，同时也神速把右手的剑收回背上的剑鞘当中。莉法和亚丝娜等人也同样解除临战状态。

先不管他的真实身份，这个赫拉斯瓦尔格先生一定跟利维坦是一伙的。也就是说，一旦开始战斗的话，他应该隐藏了挥一挥手指就把我们吹飞的能力值。

把剑收起来的我，再次凝视着青年的头上。但是只有标示着名字的浮标，没有黄金的「！」符号──开始任务的NPC标志。

这里不是承接活动任务第二章的地点吗？但是，那为什么赫拉斯瓦尔格会现身呢？

自称空之王，身高足有一九○公分的青年往下看着受到这种疑问煎熬的我，然后轻轻点头发出「唔嗯」的声音。

「原来如此。还在想小小精灵究竟是如何突破我的暴风结界，原来是受到海王的加护。」

「咦……您……您说的海王是……利维坦吗？」

或许是急忙加上敬称的效果吧，即使提出粗鲁的问题，空之王的表情也没有改变，只是点了点头。

只不过，那个巨大的大叔虽然召唤鲸鱼把我们送到岸上，但我不记得他曾经对我们施加法术。到底是何时受到什么加护的呢……难道说这正是任务正在继续的证据吗？

「但是精灵们啊。」

突然间，赫拉斯瓦尔格的声音稍微变得严厉了一些。

「就算你们得到海王的知遇，也不许靠近『空之圣所』。难道说，你们是深渊之王派来的盗贼？」

「不是的！」「千万别这么说！」「怎么可能！」「别开玩笑了！」「才不是呢！」「啾噜！」

幸好空之王似乎确实分辨出这同时发出的六种否定之词，再次点头发出「唔嗯」的声音。

「这样啊。那么你们速速离开吧。」

「………………」

这次所有人都静了下来。

刚才赫拉斯瓦尔格确实说了「空之圣所」这个名字，而那绝对就是利维坦说的「新的圣所」了。

也就是说，克拉肯想抢夺的「圣子之蛋」目前就安置在这个巨蛋的某处。在这个前提下望着世界树的树干，就发现下部有类似门的构造物。粗大树干的内部应该跟海底神殿一样是一座迷宫。

未发现的迷宫！好想进去！正确来说是想尽情打开还没有人发现过的宝箱。

这时妹妹似乎无法理解我内心的纠葛。

突然间飘然来到前面的莉法，对着空之王放声大叫：

「那个！那个……在回去之前，请告诉我一件事吧！」

「什么事呢，精灵少女？」

「这里……没有连接阿斯嘉特的那座彩虹桥吗？」

下一刻，空之王让人联想到猛禽类的金褐色眼睛就发出锐利的光芒。

「你为什么想知道这个？难道是想渡桥去谒见阿萨神族吗？」

我即使屏住呼吸，也还是意识到某件事。

空之王赫拉斯瓦尔格的会话能力远远超过单纯的聊天机器人。他以及克拉肯还有利维坦，应该都是具备拟似自我意识的AI。是与过去曾经在浮游城遇见的黑暗精灵基滋梅尔，以及现在连眼睛都潜入我胸口口袋的结衣相近的存在。

是营运企业YMIR创造出他们并且导入ALO的吗？还是说……是控制这个世界的真正神明所干的好事……？

因为跟我不同的理由而沉默一阵子的莉法缓缓摇着头说：

「不，我没有想跟神仙碰面。只是……想知道而已。这里是世界的尽头吗……或者前方还有其他国度。」

对方会如何解释这种抽象性的答案呢──

空之王突然浮现些许微笑并且说：

「女孩啊，对于娇小的精灵来说，这个愿望是太过头了。因为就连名为空之王的我都还没看过九界的尽头。」

「……是的……」

「但我可以告诉你一件事。彩虹桥确实是从阿斯嘉特所产生，但是通往的并非你们的国度。」

「咦……？」

这下子不只是莉法，连其他四个人都瞪大了眼睛。说是其他国度，但目前实际上线的也只有地底世界幽兹海姆而已。难道是直接跳过阿尔普海姆，直接从空中连结到地底吗？

但是空之王似乎不打算继续给提示了，只见他带着谜样笑容往后退了一步。

「那么，回到你们的城市去吧。」

「咦……还……还得穿越那阵暴风才行吗……？」

西莉卡发出微小的声音。结果空之王再次露出严厉的表情……

「没有这样的觉悟就来挑战我的结界吗？」

所有人像要表示「您说得是」般缩起脖子，幸好没有愤怒的落雷打下来。

「……看在跟海王友谊的份上，这次就特别送你们到外面去吧。听好了，精灵们。在没有正确职责的情况下，不准再到这个地方来。」

「遵命！」

面对异口同声乖乖这么回答的我们，感觉──空之王似乎微微渗出苦笑。

但是立刻就恢复威严的表情，从长袍的袖子伸出右手并高举起来。

难道是跟利维坦一样要召唤送我们回去的交通工具吗？如此一来，这次是巨大的鸟还是龙，又或者是飞天的圆盘呢──

我充满期待的推测立刻就遭到背叛。

「再见了，小人们啊。」

充满威严的声音如此宣告之后，空之王赫拉斯瓦尔格就轻轻挥动右手。

挥动的轨迹上可以看见透明的猛禽翅膀──当这么想的下一个瞬间，就有猛烈的龙卷风涌起并将我们吞没。

「呜哇……哇……哇啊啊～～～～！」

幸好不是只有我发出这样的叫唤。四名女性也发出尖锐的悲鸣，同时一边旋转一边被往上卷起。虽然本能地张开翅膀来试图脱离龙卷风，但是推进力完全发挥不了效果。

空之王立刻离我们远去，相对地巨蛋的天花板部分则是越来越近。心里想着「即使如此，云里面还是有狂猛暴风吧」时，天花板就开了个小洞。光是这样看，无法得知洞的后面是安全通道，或者依然是紫雷卷动的即死区域。

莉兹握住像要被洞穴吸进去般的西莉卡的左手。接着莉法握住莉兹，而亚丝娜则握住莉法的手……

「桐人……！」

我以右手握住亚丝娜伸过来的左手。

可惜连锁到这里就结束了。因为没有能够抓住我的第六个人。

但是死不放弃而胡乱挥动的左手碰到了某样东西。

反射性牢牢地抓住。在被暴风吹动的情况下把视线移过去后，发现是垂直延伸的细长树枝。前端带着两片可爱的叶子──是世界树的最顶端。

「唔……唔唔唔唔……！」

用尽吃奶的力气握紧树枝来抵抗空之王创造的龙卷风。在我正上方的亚丝娜大叫：

「那个，桐人……」

「放心吧……！我绝不会放手……！」

「不是啦……总觉得好像会遭天谴……」

「咦……？」

往上一看，在露出复杂表情的亚丝娜后面，莉法也大叫：

「对啊哥哥，那根大概是不能抓的树枝啦！」

莉兹说：「快放手啊，桐人，国王会生气喔！」

「折断的话桐人哥要负责喔～！」西莉卡如此表示。

「啾～～～～！」毕娜发出叫声。

「怎……怎么这样……我是想救大家……」

正当我试着以狼狈的声音做出反驳时──

距离我握住的细枝相当遥远的下方。从世界树树干的一角迅速飞出一道影子。

那并非空之王赫拉斯瓦尔格。体型远超过人类，拥有两片翅膀与长脖子、长尾巴的那个物体，是即使在辽阔的阿尔普海姆也很难目击的最强等级怪物──龙。

无数鳞片像蓝宝石般发出光芒的龙翻转身体后笔直往上看着我们，然后发出宛若多重雷鸣的咆哮。外露的利牙缠着紫色火花。

「看……看吧，它生气了啦，桐人！」

听见亚丝娜从上方落下的声音，我也只能点点头。

「知……知……知道了啦，数到三就放手！一、二、三……」

啪叽────！

发出痛快的声音后，我握着的树枝就漂亮地折断了。

真的发出雷声的雷龙，蓝色双眼燃烧着火焰并往上飞来。但是不知道该不该说幸好──失去救命绳的我们以猛烈的速度被天花板的洞穴吸进去。

在连成一排的状况下，以超高速冲进黑暗的细长管状空间。已经无法确定是在上升还是下降。每当左右转弯时，灵魂就像要被从虚拟角色里弹出来一样。

「呀啊啊啊啊！」

虽然不知道是谁发出的悲鸣……

「呀呼────！」

这道欢呼声的源头绝对是莉法吧。

在被意料之外的尖叫游乐设施玩弄了三十秒以上，前方终于变亮了。但是速度却完全没有减缓，我们就这样冲进白光当中。

随着「嘶波波波波嗯」声响被喷出去的前方，是一片无限延伸的钴蓝。

前后左右全都是天空、天空、天空。张开双手与翅膀，让姿势稳定下来后往正下方看去，看见很远的地方飘浮着纯白的积雨云。其下方则是呈模糊绿色的世界树枝叶。

「桐人！」

从正面听见呼唤我的声音，在做出会继续挨骂的觉悟下抬起头来，结果就看见亚丝娜灿烂的笑容。

我也对她抱以笑容，然后以右手握住她伸过来的左手。莉法抓住亚丝娜的右手，接着莉兹和西莉卡也牵起手来，五个人排成一列在空中浮游。最后从我胸前口袋跑出来的结衣则坐在亚丝娜左肩。

超高空的气流从耳边吹过，倾注的阳光让众人的头发与装备发出闪闪亮光。

好一阵子没有任何人说话。

大家一定都想起在「雷龙之巢」的不可思议体验了吧。

结果还是没能承接「深海掠夺者」的后续任务。但是空之王在临别之际这么说了。

在没有正确职责的情况下，不准再到这个地方来了。

我想……那就表示，只要有正确的职责就能再到那里去。应该是任务的旗标仍未充足吧。故事的后续仍在世界的某处等着我们。如此一来，哪一天一定能够发现。

而且不只是任务。根据空之王的话，直叶所说的「彩虹桥」似乎也存在于这里之外的其他地方。

我的视线移向右侧，对马尾缓缓飘动的风精灵剑士搭话道：

「莉法，没找到彩虹桥真是太可惜了。但是将来一定可以……」

「啊……关于这件事。」

像是从沉思中醒过来般眨眨眼睛后，莉法就看着我这边说道：

「赫拉斯瓦尔格先生说过了喔。彩虹桥虽然是从阿斯嘉特开始，但是连结的并非阿尔普海姆。我听见后就想起来了。神话里的彩虹桥确实是连结了阿斯嘉特与中土世界。」

「中土……世界？」

这不常听到的名字，让莉法之外的四个人同时歪起头来。

莉法微笑了一下后就以一句话来回答。

「人类的国度。」

「……人类……」

重复呢喃了一遍她的话，想着那不就是我们所在的这个地图时就注意到一件事。阿尔普海姆当然不是人类的国度。玩家与NPC全都是尖耳朵且拥有半透明翅膀的精灵。

但如此一来，ALO里就不存在能被称为人类国度的地点──这就等于彩虹桥不会出现了吧。接着就和似乎跟我有同样想法的亚丝娜、莉兹、西莉卡面面相觑。但是五个人正中央的莉法的脸上依然挂着微笑。

「啊……我知道了！」

如此大叫的是坐在亚丝娜肩上的结衣。

「结衣，你知道了什么？」

「人类的国度在什么地方！」

从肩膀上浮上来，移动到能跟我们相对的位置后，小妖精就骄傲地挺起胸膛来指着天空的一角。

所有人同时看往那个方向。

无边无际的深蓝色天空。别说彩虹桥了，在这个高度下就连飞行型怪物都看不见────

不，不对。天空的遥远彼方，几乎在同样的高度下浮现小小的影子。侧面是微微弯曲的圆锥台形。

新生艾恩葛朗特。

「啊……对……对喔……！」

我一边瞪大双眼一边大叫。

艾恩葛朗特里也有无数的NPC过着生活。他们没有翅膀，也没有尖耳朵。另外还有过去在那个世界里战斗过的玩家。

「……艾恩葛朗特是这个世界的人类之国<中土世界>……？」

如此呢喃的是亚丝娜。

「我是如此推测的！」

结衣坚定地这么说道，莉法则对她用力点了点头。

「我也这么认为。当然，现在彩虹桥尚未连结到艾恩葛朗特……但是将来一定会，说不定攻略到一百层时就会从天降下彩虹桥……」

「没错，一定会的！」

西莉卡这么大叫，亚丝娜与莉兹贝特也迅速点头。

虽然我忍不住在心中大叫「一百层吗！」，但还是用握在左手的东西笔直指着艾恩葛朗特说：

「好，我们要率先闯入第一百层！」

喔──！

没能听到这样的附和声。

觉得奇怪的我往右边一看，发现四个女孩子、结衣甚至是毕娜，都用相当微妙的视线回望着我。

「……我……我说错什么了吗……？」

「是没有啦……桐人，你把那个拿来了吗……」

受到亚丝娜指谪，我就看向自己用来指着艾恩葛朗特的东西。

那是一根长一公尺半左右的细长木棒。树皮是相当细致的白色，前端附近呈纤细的螺旋状，最后有两枚大大的叶子正闪闪发亮。

世界树最高处的树枝。

「啊…………不……不小心把它带回来了……」

急忙低头看着下方的积雨云，目前没有发怒的空之王或者龙追过来的迹象。

「……呃，这个该怎么办？」

「谁知道啊，你自己负起责任想办法！我可不想受到天谴的牵连喔！」

被莉兹贝特这么责备完，我就想着各种解决的办法，但感觉不论是丢掉、烧掉、煮来吃掉都会受到天谴。

「……那么卖给艾基尔，让他承接天谴这个办法……」

「……不是送而是卖吗……」

「因为这可是世界树顶端的树枝啊！可不是简单就能得到的东西……」

顺势这么回答的我，同时随手用食指点了一下树枝的中段附近。

结果随着轻快的声音打开属性视窗。原本是想──道具名称应该是「树枝」之类的吧。

「咦……有个很长的名字耶。嗯……『世界树之顶<Crest of Yggdrasill>』……？分类是……双手杖……！」

迅速抬起头后，发现亚丝娜等人也同样瞪大眼睛。我重新把树枝，不对，是长杖朝向她们并用兴奋的声音说明：

「看来这似乎是武器……而且性能高到吓人……大概是传说武器等级……」

「我……我也没看过这样的长杖喔。也就是说，这个世界只有这一根……？放到阿鲁恩的拍卖场的话，不……不知道能卖多少钱……」

和突然燃烧起商人魂的莉兹贝特面面相觑后──

就听见「咳咳」的干咳声。莉兹旁边的西莉卡不停动着三角耳朵，以告诫的口气表示：

「桐人哥？如果是武器应该就没有什么天谴，我想要怎么处理它应该很清楚了吧？」

「啾呜呜～！」

头上的毕娜也上下点着头。

「我……我……我当然知道喽。」

我点点头后，放开至今为直一直握着的亚丝娜的左手。

稍微横向移动到前方，在结衣身边转过身子。在我正面的亚丝娜，脸上露出惊讶的表情笔直凝视着我。

或许是察觉我的意图了吧，莉法、莉兹与西莉卡也移动到我左右两边。

面对依然搞不清楚目前状况的亚丝娜，我端正姿势后以双手捧着世界树顶端的树枝来递给她。

「这就交给亚丝娜来使用吧。我想一定会对你有所帮助。」

「咦……我……我可以收下吗……？」

点头表示「那是当然了」后，亚丝娜就战战兢兢地伸出手来接下长杖。

虽然外表依然是树枝，但因此而给人极优美印象的长杖，非常适合水精灵的治疗术师。

我对左右的莉法等人使了个眼色，在异口同声下大声说：

「亚丝娜，谢谢你总是提供援护！」

「「「谢谢你！」」」

听见我们的唱和──

插图p198

亚丝娜就把世界树的长杖紧抱在胸口，同时脸上露出了灿烂的笑容。

5

朝世界树城市缓缓降下的我，最后再一次抬头看着笼罩世界树顶端的白云。

那个地方找不到我所寻找的后续任务以及直叶寻找的彩虹桥。但是这两个东西说不定完全一样。

就克拉肯与利维坦的对话听起来，任务将会卷入尚未见过的阿萨神族，变成一个壮大的故事才对。如此一来，渡过七色彩虹桥，朝远方的阿斯嘉特前进的日子一定会来临──当然是很久之后的未来。

攻略新生艾恩葛朗特第一百层时，会从天空中降下彩虹桥碧芙雷斯特。

这个理想在我心中留下微小但确实的热量。

冒险是永无止尽的。不论何时都存在「后续」。即使变成大人，离开ALO的时候来临，只要抬头看向天空就一定能发现彩虹桥。

「桐人啊！」

在旁边飞行的亚丝娜以兴奋的声音大叫：

「之前不是有因为我的回复跟不上而无法攻略的迷宫吗？晚上大家到那里去看看吧！有这根长杖的话，我想这次应该能完成攻略喔！」

结果在我回答之前，前面的莉兹贝特就回头说道：

「在那之前，应该到世界树城市吃松饼吧！桐人，你说要吃一百片，好好加油喽！」

「呜……可……可不可以减少到五十片……」

我的回答让西莉卡等人同声笑了起来。

灵活地转身变成背面飞行的莉法，以促狭的笑容说：

「真拿你没办法。要减少的话可以，不过必须老实说出你昨天在司伊鲁班做了些什么！」

「呜……」

是应该做出吃不下晚餐的觉悟来挑战一百片松饼呢，还是放弃挣扎老实说出入侵领主宅邸的恶行呢？

被迫面对这用来帮长达两天的冒险做结实在有些丢脸的两种选项，我不由得发出沉吟声，这时坐在肩膀上的结衣就帮忙提出了完美的解决方法。

「别担心哟，爸爸！只要把一百片的分量一次烤熟，就只要吃大大的一片喔！」

「……原来如此，这的确是不错的方法。」

看来心爱的女儿最近迷上了「巨大物体」，这时我便用指尖轻轻摸了一下她的头。

想着哪一天一定要让她看看真正的鲸鱼，然后朝着前方微微可以看见的树上都市用力拍动背上的翅膀。

（完）

** Sisters’ Prayer

很清楚记得最先连线到Medicuboid实验一号机的日子。

一号机是把既成品的凝胶床与大型头套组合起来的丑陋机械，五颜六色的数十根管线垂到地上，周围还有大量的萤幕装置。它没有正式的代号，取用「医疗用完全潜行试验机一号」的字首后称为「MFT1」。

受到仅仅三个月前发生的「SAO事件」目前仍未解决的影响，躺在床上的时候会觉得有点恐怖。但是姊姊蓝子在旁边握住自己的手，主治的仓桥医师也保证「绝对安全，不会有任何痛苦」，所以就忍受着不安期待那一刻来临。

巨大头盔般的机械从上面降下，由头部盖住整个脸庞，眼睛闭起来后用力握住姊姊的手。

「不要紧的，木绵季。」

稍微可以听见这样的声音，于是左手便确实地回握对方。不可思议的「咻呜呜嗯」声变大，姊姊的手传来的感触与凝胶床的弹力都逐渐远去。最后明明闭着眼睛，眼前却出现一片彩色光芒──接着绀野木绵季就以新的身体降到VR世界这个异世界。

那是因为耐药性HIV感染所引起的AIDS症状出现后过了一年三个月──她十二岁九个月时的事情。

1

「咦……！」

蓝子<兰>突然发出这样的叫声，躺在山丘斜面打盹的有纪就吓得跳了起来。

「怎么了，姊姊？」

「啊……抱歉把你吵起来了，小有。新闻网站的内容让我吓了一跳……」

姊姊拿在左手的是宛如将水晶削下来装在银制框架上一般的半透明薄板。在两个人潜行进来的VR安宁病房「宁静花园」里，这是用来浏览外部网路用的情报装置型物体。

「咦咦，是什么样的新闻？」

面对探出身子的有纪，兰虽然有点犹豫，但还是把水晶板递给她。

一看到二○二四年五月十一日的头条新闻标题，有纪就惊讶地发出「咦」一声。上面大大地写着「警察厅 检讨一次救出所有SAO事件受害者的可行性」。

发生大约一万人的玩家被关在虚拟世界这种空前绝后的大事件之后，很快地已经过了一年半。当初由政府主导检讨各种软体面的救出方法，但是却无法解除首谋者设置的多重陷阱，原本以为──就只能静观其变了。

「要怎么做才能一次救出所有人……」

有纪一边呢喃一边看着新闻的内文。虽然没能到国中上课，但是她持续在虚拟世界里学习，而且原本就喜欢看书，所以阅读新闻并不是什么难事。

「嗯……警察厅似乎在检讨从外部以物理方式破坏七千名SAO事件生存者所着装的NERvGear……？」

出声读到这里，有纪再次发出「咦咦」的声音。

有纪把视线从水晶板上移到姊姊身上，然后开口询问：

「但是犯人确实说过，想要破坏NERvGear的话，那个瞬间就会产生电流对吧？」

「不是电流，是电磁波喔。」

以老师般的口气如此订正完，兰的脸色就沉了下来。

「光是从这则新闻来看，从外部一瞬间就破坏电池的话，能造成着装者脑部损伤的电池波就无法发生……好像是这样……」

「这样啊……」

有纪一直凝视着内文旁边作为参考用的NERvGear照片。Medicuboid实验一号机使用的简陋头套是NERvGear的雏型，所以跟照片上的极为相似。

虽然目前使用，不对，应该说进入的实验二号机外型与大小都有很大的不同，但还是对「破坏戴在使用者头上的VR头盔」这件事感到害怕，同时再次提出问题。

「……具体来说，要如何一瞬间破坏呢？不能够引爆或者是用榔头用力敲打吧。」

「这个嘛……大概是用精密的钻头在外壳上开洞，然后切断电池的正极线吧？但是感觉那个犯人应该偷偷设置了备份线路。」

「这……这样啊……」

「而且犯人的声明文里应该也提到了想破坏NERvGear来解放玩家的话，将危及其他玩家的安全。也就是说，想实行这个作战的话，必须要在分秒不差的情况下一次切断七千台NERvGear的线路才行。真的能办到这种事吗？」

「……应……应该很困难吧。」

虽然好不容易做出这样的回答，但姊姊的话很快就逐渐超越有纪的理解能力了。

平常的话，差不多要随着「姊姊好厉害」的发言停止思考了，但有纪这时再次把视线移到水晶板上。两个人住的医院里好像也收容了数名SAO事件的受害者，所以实在无法不关心这件事。

「……兰姊姊，那个叫茅场的人为什么要做这种事呢？」

兰没有立刻回答有纪的呢喃，只是把视线移到前方。有纪也抬起脸看向遥远彼方的蓝色模糊棱线。

两个人目前并肩坐在广大宁静花园的东部一片名为「提尔山丘」的区域。被绿色覆盖住的平缓山丘连绵不绝，其间散布蓝色湖泊与小村庄的光景，美丽到让人能永远眺望下去。

VR安宁病房，也就是为了帮末期患者提供安宁缓和医疗用的VR世界而从二○二三年九月开始营运的宁静花园，大部分开发资源都投注在「世界的美景」上。相对于同年六月发售的AmuSphere用软体全都是ADV或者FPS，宁静花园完全不存在战斗要素，不过可以体验到精致且富含变化的情景。宽广的世界地图其东部是绿色山丘、北部是雪原、西部是高山、南部是深邃的森林，而中央则配置了拥有欧洲风街道的首都，想徒步观赏整个世界的话应该得花上一个星期吧。

有纪与兰的双亲去年底相继去世了。两人直接的死因虽然是肺炎，但其他也受到复数的机会性感染侵袭，所以为了减轻痛苦而投予大量止痛剂，从秋天结束时开始就一整天都处于睡眠状态。

这样的双亲只使用过一次AmuSphere来到宁静花园里面。

AmuSphere的体感扫描机能无法完全消除疾病的疼痛，所以能在一起的时间只有短短一个小时。即使如此，从街上的广场缓缓散步到郊外草原的那段时间，在有纪与兰的胸口刻画下一段难以忘怀的回忆。父亲边吃边称赞有纪她们做的便当很美味，母亲因为美丽的风景而噙着泪水并且唱了好几首姊妹喜欢的童谣与赞美歌。

没有完全潜行技术与VR世界存在的话，就绝对不可能实现这种事。

而几乎是独自开发出这种技术的，正是SAO事件的犯人，亦即名为茅场晶彦的男人。

而且不只与双亲的回忆而已。有纪作为受验者所连结的Medicuboid实验机是在医疗机器厂商的主导下进行开发，而兰用来潜行至宁静花园的，是将电池缩小容量并且安装限制器来完成修改的NERvGear。两人能够像这样在虚拟世界里接触，也全是靠那个世纪的超级罪犯。

像要放松有纪复杂的感情般，兰举起左手来温柔地抚摸着有纪的背部。

「姊姊我也搞不懂这件事。但是小有不需要觉得难过。小有是为了将来Medicuboid能够造福大量的病患，才会作为测试者帮忙开发。」

「…………嗯……」

有纪点点头后就静静地靠在姊姊肩上。

虽然是姊姊，但是兰──蓝子是跟有纪同一天诞生的双胞胎。不过从懂事时开始，有纪就以妹妹的身份倚靠着兰并且向她撒娇，而身为姊姊的兰也温柔地包容有纪并且保护她。

有纪之所以能够成为Medicuboid的受验者，也是因为姊姊强烈如此主张的关系。

纤细的机密机械Medicuboid实验机，是设置在两人所住的横滨港北综合医院的无尘室当中。室内的细菌与病毒远少于外界。这也就表示，能够大幅度减低AIDS患者最为害怕的机会性感染的风险。

作为受验者进入无尘室的话，能够延长存活的时间。即使知道这一点，兰还是为了有纪而让出这个机会。从那一天后又过了一年三个月的现在，住在一般病房个室内的兰，病况比有纪恶化了一些。即使是像现在这样，兰应该也对NERvGear无法消除的疾病感到恐惧才对。

仓桥医生提出作为Medicuboid受验者进入无尘室的提案时，应该可以表示「我不用了，姊姊你去吧」，但是有纪却说不出口。不过兰却没有丝毫犹豫就表示「有纪你进去吧」。

当有纪紧闭起嘴唇时，兰突然迅速站起来。

长发跟着微风晃动的她大大地伸了一个懒腰。两个人的虚拟角色都是系统根据照片自动生成，但兰的虚拟角色惊人地重现了现实世界的容貌，穿着的少女风衬衫式洋装也很适合她。

笑着对有纪伸出手来的兰，以充满元气的声音说：

「来吧，有纪，我们去摘香草。感觉今天可以发现超稀有的品种。」

「…………嗯！」

有纪点点头后，紧紧握住姊姊的手。

2

宁静花园虽然没有战斗要素，但并不代表就只能观光而已。

最大的游戏要素是「盖房子」。这个世界的首都是位于中央的「赛雷尼蒂」，将给予使用者此处一定面积的土地，让他们能够依自己喜欢的设计来在此建立房子。只不过外墙的砖瓦只能选择颜色适合街道的几个颜色，所以盖房子时主要是享受内装。

内装的素材与家具可以从街上的NPC商店里购买现货或者订做，但是必须要有名为「卡连」的点数。听说是货币<Currency>的略称，但是无法让渡给他人，唯一取得的手段是「采集」。收集在世界地图各处涌出的可以加以采集的植物与矿物，或者捕捉昆虫把它们带到街上的商店，按照稀有度来交换成卡连。其他还有直接从素材制作成各种道具，养育抓到的昆虫参加名为「昆虫大战」的大会，能够做的事情出乎意料地多。

有纪跟兰在赛雷尼蒂的高台上拥有两人共同的房子，虽然花了半年的时间来布置，但是距离完工还有很长一段距离。现在为了在客厅设置大型暖炉而储蓄点数当中，不过目前才终于累积到目标点数的七成左右。

话说回来，采集作业本身其实颇为有趣，所以不会觉得辛苦。享受着美丽的环境景色并专心摘取香草，转眼一两个小时就过去了。宁静花园的利用者全都在与「还能够活多久的」沉重压力战斗，所以能够忘记恐惧的长时间采集内容相当受欢迎。和有纪感情很好的老婆婆，一整天都在世界地图里奔波采集大量的素材，然后在赛雷尼蒂最贵的地段盖了一栋四层楼的豪宅。

虽然没有那么疯狂，但是为了实现用壁炉来烤地瓜的愿望，没有一天可以偷懒。

两人从暖洋洋的山丘斜面移动到小池塘池畔这个秘密的采集地点后，一只手拿着篮子茫然摘着香草的有纪……

「……啊。」

因为姊姊这样的声音而抬起头。

「怎么了，姊姊？」

对在稍远处的姊姊这么问道，结果对方以手势表达「安静」，于是有纪便闭上嘴巴。虽然循着半蹲僵在该处的兰所发出的视线看去，但仍未能得知她到底发现了什么。

放下篮子蹑手蹑脚地慎重移动到姊姊身边，凝眼看向草丛后面的瞬间──

「……啊。」

有纪也忍不住轻叫了一声。

生长在池畔的古老宽叶树树干上，停着一只带有深邃蓝色亮光的锹形虫。全长将近十公分左右。有纪曾经在宁静花园的昆虫大图鉴里看过除了这两根雄伟的大颚之外，还从头部正后方延伸出长大胸角的模样。

「不觉得那只锹形虫看起来有点稀有吗？」

姊姊的发言……

「何止是稀有，那可是皇家崔顿锹形虫喔。」

让有纪立刻这么回答，结果又听见紧张中带着些许傻眼的回应。

「竟然连名字都记得。」

「因为好好养育的话能成为锹形虫系最强呀！」

「……小有对昆虫大战有兴趣吗？」

「其……其实我很喜欢呢。」

像这样低声交谈的期间，蓝色锹形虫开始缓缓爬上老树的树干。前进方向有金色的树液渗出，看来它的目标是那里。

「姊姊，你有带捕虫网吗？」

「今天只打算摘香草，所以没有带来耶。」

「我也是……」

宁静花园为利用者准备的道具栏容量很小，想把花数小时采集的素材道具全带回去的话，就没有空间装多余的东西。加上有纪和兰是专门采集植物，所以早就决定只有发现极稀有的个体才会向昆虫出手。

不过目前在短短五六公尺外的皇家崔顿锹形虫是最稀有的昆虫，抓住后拿到昆虫商店换钱的话，即使购买大型壁炉也还有余额。所以当然要想办法抓住它。

「姊姊，我试着用手抓住它吧。」

如此低声搭话完后，兰就露出吃惊的表情倒吸了一口气。

「小有……你敢空手摸那个吗？」

「…………」

──话说回来，姊姊在现实世界也跟妈妈一样对于虫完全没有抵抗力。我从院子里抓到蚱蜢带回家时，两个人都一起尖叫然后到处逃。

有纪以怀念的心情回想起幼年时期，同时快速回答：

「这个世界的虫不会咬人、螫人或者发射奇怪汁液，所以我完全不怕喔。姊姊在这里等一下。」

有纪轻拍了一下兰的肩膀，接着脱下凉鞋，维持屈身的姿势开始移动。

虽然瞒着姊姊，不过自己一个人时也抓了不少虫子。想抓稀有昆虫时的铁则有三，一、不急着行动。二、不从头部附近靠近。三、不发出不自然的声音。

因为是在比膝盖高的草丛里移动，所以无法避免发出摩擦草丛的声音。灵巧地把这样的声音混在风吹草动的声音里面，然后一点、一点地前进。

爬上树干的极稀有锹形虫，到达渗出金色树汁的地方就停下脚步。虽然进食的瞬间是最大的补获机会，但就有纪的经验，稀有昆虫的进食时间相当短暂。大概十五秒左右就会张开翅膀，嗡一声飞走了。

距离树还有三公尺。跟之前一样配合风声移动的话绝对会来不及。但是随便奔跑而发出巨大噪音的话，锹形虫绝对会逃走。

──怎么办？得想办法不碰到草来移动……

视线一瞬间往左右移动的有纪，视线确认到某样东西。右侧近处的池畔，有在大约一公尺的间隔下并排的木桩。木桩顶端比草丛还要高，跳到上面的话就能在不出声的情况下移动了。

问题是木桩的直径仅仅只有五公分左右。只要稍微失去平衡，不是跌到左边的草丛就是倒栽葱摔进右边的池子里。而且没有时间一步一步慎重地取得平衡。

「……只能硬着头皮上了！」

默默地这么对自己说完，随即配合下一次的风吹横向移动。计算时机站起来后，「嘿」一声跳到细细的木桩上。

──要上了！

在不出声的情况下加快速度，安静地从这根木桩跳到下一根。好不容易才没有跌落，到达最靠近老树的木桩那一瞬间，结束用餐的锹形虫完全张开发出宝石般光辉的翅鞘与透明的后翅。

对着拍动翅膀「嗡！」一声准备飞起来的锹形虫──

「嘿呀！」

不再压低声音的有纪奋力往前一跳。全力伸长的右手指尖紧抓住锹形虫的长长胸角。

现实世界的话，锹形虫这种大型甲虫不会因为背部被抓住就放弃挣扎，但这里是易用性优先的虚拟世界。响起获得稀有昆虫时的英勇效果音，锹形虫也收起翅膀乖乖待在手中。

有纪「沙」一声降落在草地上。

「成功了───！抓到皇家崔顿锹形虫了！」

用力往上举起左拳后，兰就以八分惊讶两分恐惧的表情靠了过来。

「……小……小有太厉害了。真的空手就抓到了。」

「嘻嘻嘻，我也吓了一跳哟。来，姊姊要不要拿拿看？」

递出右手上巨大锹形虫的瞬间，兰就一脸严肃地边摇头边后退。

「还……还是算了吧。但真的恭喜你了，有纪。你准备如何处置那只锹形虫？卖掉吗？还是要养它？」

「嗯……嗯嗯嗯～～～～」

发出沉吟声的有纪，把角被抓着就乖乖不动的蓝色锹形虫拿到眼前。想抓它时只想到要换成点数，在宁静花园度过了半年的采集生活，还是首次入手如此稀有的道具。而且仔细看锹形虫的脸，就开始觉得圆滚滚的复眼似乎有点可爱。

只不过，要在这个世界饲养昆虫的话，也必须付出饲料费等各种经费。长大到能在昆虫大战里获胜的话，或许可以自己赚到饲料费，但就算喜欢观赏大会，自己参加的话各方面的门槛都太高了。

「怎么办才好呢……」

有纪和不停动着大颚的锹形虫面面相觑，然后沉思了一阵子。就在这个时候──

「啊啊啊啊啊────！」

这样的巨大悲鸣声从左侧涌至，有纪的身体不由得往右倒。

「怎……怎么了！」

和这么大叫的兰一起看向左边，不知道什么时候，稍远处已经站着一名女孩子。当然对方也是虚拟角色，但宁静花园无法变更性别，容貌也是从真人的照片所生成，所以可以推测应该是跟现实世界的玩家极为相似的模样。

将长长的绿色头发绑成马尾（发型与发色就可以自由更换了），身穿茶色系迷彩T恤以及有着许多口袋的工作裤，一看就是做昆虫猎人打扮的女孩子，左手拿着的捕虫网不停震动，同时以右手食指严厉地指着有纪。

「那只皇崔！是我花了一个小时追踪的目标！」

花了三秒钟才理解「皇崔」不是什么黄色花朵或者吹奏乐器的名字，而是皇家崔顿锹形虫的略称后，有纪一边把右手的锹形虫藏到背后并且如此反驳：

「这……这是我抓到的喔。」

依照宁静花园的规则，采集道具不论是花草、石头或者昆虫都是属于最初获得的人，所以「这个地方是我的」或者「这边是我先发现的」等主张没有任何效力。应该知道这一点的迷彩服女孩虽然暂时被逼得说不出话来，但随即再次开口说：

「但你看起来不像昆虫猎人吧？没有捕虫箱的话，你打算怎么把那只锹形虫带回去？」

这次换成有纪说不出话了。

抓到的昆虫要是不放进女孩子挂在腰间的那种专用捕虫箱就无法收纳到道具栏。但是只用手抓住的话，锹形虫将会越来越虚弱。虽然放到箱子里给予饲料和水就能立刻恢复，但从现在这个地方到最近的村子最快也得花上二十分钟。虽然不知道这段期间锹形虫会减少多少生命值，但万一要是因此而害它丧命的话将会懊悔不已。有纪不参加昆虫大战最大的理由，就是因为害怕有什么突发事故而失去爱虫。

兰悄悄地把手放到保持沉默的有纪左肩。同时出声说：

「……小有。」

光是这样，有纪就了解姊姊想要说的话。她把拿到身后的皇家崔顿锹形虫再次移到面前，在心中向它道别之后，就把它递给昆虫猎人的女孩子。

「好吧，就让给你。」

结果马尾女孩像吓了一大跳般瞪大了眼睛。

「咦……可……可以吗？」

「不是你要我让出来的吗？」

有纪随着苦笑往前踏出一步，女孩子就以更加慌张的模样低头看着自己的身体。

「但……但是我没有任何能交换那只皇崔的道具……」

宁静花园里面，玩家之间无法进行点数<卡连>的交易。把道具实体化的状态下虽然可以以物易物，但应该没有玩家会带着足以跟最稀有昆虫交换的物品吧。

有纪露出笑容来向对方说道：

「不用交换没关系喔。这孩子让像你这么认真狩猎昆虫的人养育也比较幸福。」

「…………」

但那个女孩子一开始咄咄逼人的模样完全消失，只是丧气地闭着嘴巴。原本应该只是试着把追踪的锹形虫被人抓走后的怒气发泄出来，但是本人也没料到对方真的会让出吧。

即使能够预测到对方的心理，有纪也不知道该如何继续向对方搭话，这时兰就代替她以平稳的声音如此提案。

「那么就由小有帮这个孩子取名字，作为交换的代价如何呢？」

下一刻，女孩子脸上就露出喜悦的光辉并且不停点头。

「嗯……嗯，当然好哟！你帮它取名字吧！」

「咦……我吗？」

嘴上虽然如此回应，内心其实慌了手脚。老实说，有纪对于自己取名的品味完全没有自信。宁静花园里的虚拟角色名称，相对于姊姊用了「蓝<Ai>」音读后同音汉字的「兰」，她只是直接用了本名读音的其他汉字表记「有纪」。

但这时候放弃的话将会让一切前功尽弃，于是她便拼命想着。花了整整十秒以上所想出来的名字是──

「……嗯……那么，就叫作『罗伊』如何……」

──根本就是皇家的读音直接转过来的嘛！

虽然有了被这么吐嘈的觉悟，但马尾女孩只是露出灿烂的笑容点了点头。

「不错呢，我也喜欢这种简单的名字！那么，我就把这孩子的名字登录为『罗伊』喽！」

「嗯！」

点点头后，有纪就在内心对锹形虫说了声「要保重喔」，接着再次把它递给女孩子。

双手像是将其包裹住般接过锹形虫的女孩，彷佛极为感动般着迷地盯着皇室蓝的光泽好一阵子，最后以慎重的手势将虫子移进捕虫箱里。接着打开视窗，连同箱子一起收纳到道具栏当中。这下子锹形虫的生命值应该就不会减少了。

拿起放在地上的捕虫网，接着也把它收进道具栏的女孩子，端正姿势后深深鞠躬。

「──真的很谢谢你把它让给我！它是我来到这里就一直在寻找的虫子，我真的非常、非常高兴！」

注意到「这里」指的不是提尔山丘，而是作为VR安宁病房的宁静花园后，有纪就随口询问：

「你来这里多久了？」

「刚开始营运就来了，已经八个月……啊，真是的，我连名字都没有说呢。初次见面，我是梅利达。请多指教！」

插图p223

粲然一笑后伸出右手和梅利达握手，有纪同时也报上姓名。

「我是有纪！请多指教！」

接着兰也跟梅利达握手。

「我是兰。是有纪的姊姊，请多指教，梅利达小姐。」

「叫我梅利达就可以了。我想我应该比你们年长一些。能够认识你们真的很开心，今后让我们好好相……处…………」

梅利达的声音突然产生摇晃并且中断。

有纪急忙用双手帮忙撑住拖着绿色马尾整个倾斜的身体。

移动到锹形虫，不对，是「罗伊」之前停住的树荫底下，让她坐到草地上后，梅利达立刻就回复了。

眨了几下眼睛后，注意到露出担心表情的有纪与兰，梅利达就像很惶恐般缩起脖子。

「……抱歉，我因为有纪把罗伊让给我而感动，好像有点太兴奋了。」

虽然配合发出「嘿嘿嘿」笑声的梅利达露出微笑，有纪还是无法压抑担心的情绪。

宁静花园里，官方不称利用者为「玩家」，利用者之间也有避免使用这个名称的倾向。那是因为大家都不是单纯为了游戏而来到这个世界。

VR安宁病房的任务是缓和医疗──减轻生病的疼痛与辛苦并且提升生活品质，所以利用者全部都是重症患者。说起来，如果不经由住院的医疗设施，甚至没办法登录帐号。也就是说，梅利达是从日本的某家医院里潜行到这个世界来的。

不清楚梅利达的病名是什么。但是VR世界里的虚拟角色倒下，就表示不单纯是晕眩或者贫血，而是连接AmuSphere的脑部本身产生病状。

当然，如果真的是很严重的状况，AmuSphere会自动断线而虚拟角色也会消失。像这样立刻就恢复意识，就表示正如梅利达所说的，并非立刻会危及生命的事态吧。但是另一方面，梅利达那种极为冷静的模样也增幅了有纪的担心。她已经习惯这种现象……也就是说，经常会发生这种事。

像是藉由支撑背部的手察觉了有纪的内心一般，梅利达再次笑了起来。

「啊哈，真的不要紧。只要休息一阵子，马上就会变好……你看，已经完全没问题了。」

梅利达迅速撑起上半身，利用反作用力弹跳起来。那顺畅的动作，只能说真不愧是最为古老的玩家。但是仔细一想，从营运开始就参加了宁静花园，就表示需要长时间缓和医疗的状态一直持续着。

挂念着梅利达病情的有纪也站了起来。结果梅利达往后退了一步，然后再次以认真的视线看着有纪。

「怎……怎么了吗？」

和姊姊一样的可爱洋装果然不适合自己吗？这么想的有纪缩起了脖子，但是梅利达却以开怀的笑容说道：

「抱歉抱歉，不应该这样盯着你看。那件洋装虽然很可爱，但是不适合狩猎昆虫，所以我才想亏你能够抓住皇家崔顿锹形虫。那种锹形虫只要听到一点脚步声就会立刻逃走，你穿这件洋装是如何在草丛里静静移动的？」

「这个嘛……」

当有纪歪着头想「是怎么办到的」时，兰就随着轻笑声回答：

「有纪不是在草丛里移动，而是灵活地不断在立于池畔的木桩上跳跃喔。」

「啊，就是那样。」

忘记仅仅十几分钟前的行动让感到害臊的有纪发出「嘿嘿嘿」的笑声，但梅利达反而收起笑容发出「咦咦～」的叫声。

「从那么细的木桩上？有纪小妹，你能办到这种事啊？」

「嗯……嗯，是啊。还有也叫我有纪就可以了！」

「那……那么，有纪……你可以在那边单脚独立一下吗？」

「咦？嗯……」

不了解梅利达的意图，即使感到茫然还是按照吩咐弯曲左脚来用右脚独立。有纪一边张开双臂取得平衡一边对梅利达说：

「肌肉在这个世界不会疲劳，我可以一直单脚独立喔。姊姊也能办得到吧？」

「这……这个嘛……因为我没尝试过……」

虽然露出没什么自信的表情，但兰也同样以单脚站立。一开始虽然有些摇晃，但立刻就让身体安定下来。

在小学四年级被迫转学之前，有纪和兰也很正常地在学校上体育课。因为是双胞胎，所以身高的成长速度差不多，但奔跑的速度、球技的熟练度，真要说的话连同考试点数都是由兰稍微占上风，有纪内心一直暗暗感到懊悔。

她暗暗下定决心「至少在虚拟世界的独立对决要获胜！」并且持续保持着平衡，但是经过短短的一分钟，梅利达突然就盛大地拍手并且大叫：

「有纪和兰都好厉害！我还是第一次在这边看到能单脚独立那么久的人！」

和姊姊两个人因为这听起来有些夸大的发言而感到茫然，梅利达就像是很焦急般握住双手。

「FC数值这么高的话，一定可以成为优秀的昆虫猎人的啊！嗳，即使是现在也还不太迟，要不要转职成昆虫猎人？我可以教你各种知识喔！」

面对连珠炮般说出一串话的梅利达，依然单脚站立着的兰举起双手表示「先冷静一下」，然后以温柔的声音问道：

「梅利达，首先FC是什么？」

「我也没听过耶。」

看见同时露出狐疑表情的两个人，梅利达像是要让自己冷静下来一样先深呼吸一次后才开始说明。

「抱歉，是我太着急了……我老是这个样子。嗯……所谓的FC呢，就是Full-dive Conformation……亦即虚拟世界的适合度，单脚站立就是最简单的测试方法。这边的平衡感与重力感和现实世界有微妙的差异，只有能调整这些差异的人，才能长时间单脚站立。虽然我的累积潜行时间已经很长了，但四十秒左右就是极限了吧。」

「是……是这样啊……」

有纪对于梅利达关于完全潜行技术的知识量感到有些惊讶，同时低头看一下自己的右脚。确实有最初使用实验一号机时因为跟现实世界的些微差异而感到困惑的记忆，但是在因为色彩鲜艳的虚拟世界而兴奋地又飞又跳当中，应该立刻就习惯了。姊姊兰也没有提到过感觉上的差异才对。

「……这就表示，那个FC有个人的差异喽？」

有纪随口这么询问，结果梅利达就一脸认真地点点头。

「是啊。虽然很少见，但是也有最初的连线测试，就被判定为FNC……不适合完全潜行的人。都花大钱买了NER……AmuSphere了，被做出这种判定的话会大受打击吧。嗯……不过现在购买之前能够先尝试的店家变多了。」

「这样啊……」

虽然事到如今才为了自己和姊姊并非FNC感到放心，但有纪也知道自己产生了淡淡的罪恶感。现在使用的Medicuboid二号机就不用说了，就连兰的修改版NERvGear都是医院帮忙准备的产品。虽然仓桥医生表示「考虑到两个人罹病的经过，这点小事根本算不了什么」，但是像这样跟宁静花园的其他玩家交流时，总是会忍不住这么想。原本应该要买下两台昂贵的AmuSphere，才能跟姊姊一起来到这个地方。

没错──仔细一想就会觉得姊姊的运动神经本来就很好，而自己之所以能像这样单脚站立好几分钟，完全是靠性能比AmuSphere好许多的Medicuboid吧。

这样的想法浮现在脑袋里的瞬间，有纪就对于跟兰较劲感到疲倦而准备放下左脚。

但是在那之前……

「啊～撑不住了！」

兰边这么大叫边从右侧抱住有纪，于是两个人就一起倒到草地上。

「哇，姊姊你做什么啦！」

「先碰到地面的是小有，所以单脚独立是我赢了！」

「呜哇，真狡猾！我本来还能继续撑下去的耶！」

忘记数秒钟前的沮丧如此反驳兰之后，原本瞪大眼睛的梅利达突然发出开朗的笑声。

「啊哈哈，你们两个的感情真好。好羡慕喔，我也好想有个姊姊或妹妹……」

说到这里后，梅利达脸上的笑容瞬间消失并且沉默了下来。应该是想到姊妹一起参加VR安宁病房代表什么意思了吧。

有纪虽然想对她说「不用在意」，但一时却说不出话来，于是兰就代替有纪以开朗的口气表示：

「梅利达的话应该能成为很棒的姊姊。因为你很帅气，又懂很多东西。」

兰站起身子，把有纪拉起来并继续说：

「梅利达好像对完全潜行游戏很熟悉，除了宁静花园之外，还有玩其他的游戏吗？」

「嗯～现在主要是宁静花园吧。因为忙着狩猎和养育昆虫。」

梅利达虽然再次恢复笑容这么回答，但是笑容里却带着些许阴影。

「宁静花园之前还玩了另一个游戏……但是开始正式营运之前就发现生病了，来不及继续玩下去。」

「这样啊，是什么游戏？」

不清楚其他VR世界的有纪兴致勃勃地这么问道，结果梅利达就带着内含苦涩感情般的笑容，提出了另外一个问题。

「两位还有时间吗？」

「嗯……」

瞄了一眼显示在视界右下的时间，上面写着下午三点半。到晚餐时间的六点还有一段时间，今天两个人也没有检查或面谈的预定。

「应该还有两个小时的时间。」

有纪这么回答完，昆虫猎人女孩就轻轻点了一下头。

「那么要不要到村子里去喝茶然后继续聊呢？」

3

宁静花园世界里，除了首都赛雷尼蒂之外，东西南北各个地方都配置了一座城市或者村庄。位于东部提尔山丘的是名为「洛伊提」的村庄，中央广场上设置了转移门，一瞬间就能回到首都。

在有纪和兰前面钻过村庄大门的瞬间，梅利达就转过头来表示：

「两位，可丽饼和冰淇淋，你们比较喜欢哪一种？」

立刻回答「可丽饼！」的声音完全同步，让梅利达瞪大了眼睛。

「毫……毫不犹豫耶。」

「嘿嘿嘿。」

有纪笑着和姊姊短暂交换了一下眼神。可丽饼是去世的母亲最拿手的点心。以稍微烤成淡茶褐色的饼皮来裹住奶油与水果的甜可丽饼，或者卷起起司、火腿的咸可丽饼，又或者是把叠起来的饼皮浸在温柳橙风味酱汁里的火焰薄饼，都是喜欢到可以每天吃的点心。

住院之后，虽然有一阵子在医院的咖啡厅里可以吃到比不上母亲亲手制作，但还算美味的可丽饼，但是进入无尘室后就无法品尝了。

至于兰则通常是吃医院的餐点，也可以到咖啡厅去。但是她似乎为了配合有纪，决定只在虚拟世界吃可丽饼。有纪有一次抱怨说「不用在意我，在现实世界也可以吃」，结果被她以「一个人吃也不好吃」给反驳了。

不清楚这些内情的梅利达或许也感觉到什么了吧，只见她迅速点点头并且拍了一下穿着迷彩T恤的胸膛。

「好，我就带你们到珍藏的可丽饼店去吧！」

「咦……这个村子里除了广场的餐厅之外，还有那种店吗？」

听见兰的问题，梅利达只是盈满微笑就直接往前走。

洛伊提村是建筑在略高的山丘上。望着彷佛阿尔卑斯山村的砖瓦墙房子并且爬上石头铺成的主要干道。宁静花园的同时上线人数最多就只有一千人左右，从全国住在安宁病房的患者有超过三万人来看，就能知道实在不能说是普及，由于整个世界就只有五座城市和村庄，所以路上往来的行人倒是还不少。

但是梅利达在离开聚集许多商店的大路来到迷宫般的巷弄之后，就踩着俐落的脚步持续在巷子里左弯右拐。

在没有详细地图机能的宁静花园里，能够像这样毫不迟疑地行走，除了完全掌握洛伊提村错综复杂的地形之外，应该也是因为很习惯虚拟世界的缘故吧。感觉再次对梅利达在宁静花园之前玩的游戏产生兴趣的两人持续走着，当终于分辨不出现在位置的时候，眼前突然变得开阔。

山丘的西侧斜面上凸出着半圆形小露台，从该处可以瞭望整个午后阳光照耀下闪闪发亮的草原。远方呈淡蓝色相连的是峡湾状海岸，也就是世界的尽头。

露台上只放了一张设有遮阳伞的桌子，桌子后方的小咖啡厅正飘出甘甜香味。

「真幸运，外面的桌子空着！」

笑着回过头来的梅利达绕到两人后面推着她们的背部，让她们坐到能眺望草原的椅子上。自己则坐在对面，按了一下桌子上的菜单。

「这里是洛伊特村我最喜欢的店。今天我请客，你们尽量点吧！」

一起被眼睛下方的绝景吸引住的有纪与兰，同时把视线拉回来后开始不停摇头。

「都带我们到这么棒的店来了，怎么还能让你请客呢……」

梅利达做了一个手势阻止急忙准备起身的兰。

「你在说什么啊，这里的可丽饼完全比不上皇家崔顿锹形虫喔。至少让我请这一顿吧！」

「……那我们就不客气了。」

兰再次坐下时，有纪的视线已经移向软木制的菜单上面。

因为是虚拟世界，所以店内的冰箱拥有无限大的容量，但是菜单上实在排了太多的文字列了。根据注意事项，似乎有五种饼皮、十种奶油、二十种水果、三十种酱料、五十种配料可供自由选择。也就是说可以组合的模式实际上是无限大。

「太厉害了……但是，这么多的话就无法决定了……」

有纪才刚做出软弱的发言，兰便朗声说出一连串选项。

「那我的面皮要这个『湿润甜心』，奶油是『绵密生奶油』，水果我要『红宝石草莓』和『清爽橘子』，酱料要『浓稠巧克力』，最后配料是『新鲜开心果』和『焦糖饼干』！」

「………………」

有纪哑然看着不停按着触碰式面板菜单的姊姊。坐在对面的梅利达也瞪大了眼睛。虽然有许多事情都比不上姊姊，但差距最大的应该就是决断力了吧。有纪到目前为止，几乎没有看过兰三心两意、犹豫不决的画面。

结束选择的兰抬起头来说道：

「小有你呢？」

「……跟姊姊一样吧。」

以竖起白旗投降的心情搭便车之后，梅利达也接着说「那我也一样！」。

点头的兰在数量的地方输入3……

「那么就让你破费了。」

接着就递出菜单。接过菜单的梅利达按下点餐键，支付三人分的卡连之后，短短十秒钟NPC女侍就从店铺内端了三个盘子过来。

盘子上的可丽饼外形是见惯了的三角锥，但是比想像中大很多。奶油与水果豪迈地满出淡黄色饼皮，酱料与配料则是发出闪亮的光辉。

「呜哇，看起来好好吃！」

这么大叫的有纪，在胸前握起双手完成简略的祈祷后，就用双手拿起可丽饼。现实世界的话，要在不崩坏的情况下品尝这庞然大物是极困难的任务，但这里只要不自己放开手……就不会发生奶油或水果掉下来沾到衣服的惨剧。

「开动了～！」

和兰异口同声地唱和之后，就把嘴巴张到最大来一口咬下。湿润又极薄的饼皮畅快地破开，从里面飞出软绵绵的奶油与大颗草莓。

刚刚来到这个世界时，对于吃以程式形成的食物这种行为感到很不对劲，但是马上就习惯了。虽然要跟现实世界一样咀嚼、品尝味道需要一定的诀窍，但闭起眼睛，不太需要动舌头，只要用一定的力量咀嚼，就不会发生太严重的「感觉错乱」。

口中的饼皮与奶油、草莓融合并且滑落喉咙的感觉消失之后，有纪就瞬间张开眼睛并且大叫：

「梅利达，这个可丽饼非……非常好吃！和转移门广场前面的那家店完全不一样。」

结果刚认识的朋友就露出发自内心的笑容说：

「对吧！我想是因为档案的量很大，才会在这种没什么人来的地方。我一开始发现这家店之后，可是花费了一番功夫才能不迷路就来到这里呢……兰你觉得呢？还能接受吗？」

听见问题的兰，从马上咬了三口的可丽饼上抬起脸庞并且用力点点头。

「决定了。我要经常来光顾，直到吃完这里所有种类的可丽饼。」

「啊哈哈，虽然很辛苦但加油喔！已经来这里半年的我，尝试过的组合可是连一半都不到哟。」

「那下次把你推荐的组合告诉我吧。」

有纪听着两个人的对话，同时持续减少巨大可丽饼的面积。

很可惜的是，还是不认为它比母亲烤的可丽饼美味。因为地球上任何地方都不存在这样的可丽饼了。但是，光是能和在这个世界偶然相遇，刚刚变成朋友的女孩子一起品尝，感觉吃起来应该就比它原本的味觉档案美味好几倍了。

尚未发病之前──在小学上课时，身边有许多好朋友。每天都很期待在教室里把桌子并起来，大家一起热络地聊天并且吃着同样菜色的营养午餐时间。

但是这样的乐趣也在有纪是HIV带原者的传闻散开那一瞬间就消失了。没有同学愿意与自己并桌，有纪每天只能一个人在教室角落孤单地吃营养午餐。原本最喜欢的猪肉咖哩、冬粉汤以及牛奶布丁都变得不好吃了。

现在想起来，自从住院之后这还是第一次和「朋友」一起吃东西。即使双手拿着的是虚拟可丽饼，也不清楚对方的本名与真正的容貌，然后地点还是异世界的露天咖啡厅──就算是这样，现在揪紧有纪胸口的酸楚与温暖都是真实的感情。

「…………有纪。」

突然被梅利达叫到名字而张开眼睑的有纪，发觉自己边吃可丽饼边噙着眼泪。她急忙把吃到一半的可丽饼放回盘子上，然后用双手揉眼睛。但是眼泪却一直无法停下来。以前兰曾经告诉过自己，虚拟世界的感情表现有些夸大，因此好像很难忍住泪水。

「我……我没事，只是有点……有点…………」

如此呢喃着并且擦拭眼角，旁边的兰就温柔地拍着有纪的背部。或许是从小就这样被安慰而变成了反射条件吧，这时候眼泪终于止住了。

「……抱歉喔，梅利达，突然就掉眼泪。因为可丽饼实在太好吃，还有真的很开心……」

好不容易露出笑容之后，梅利达也以像是在忍耐些什么的脸庞展现微笑。她把最后一块可丽饼放进嘴里并且吞下去后就呼出一口气。

「…………我前阵子自己一个人也经常掉眼泪。不对……即使是现在，只要想起来就会觉得很难过。又难过又懊悔又郁闷，真的很想像个婴儿一样哭闹。」

梅利达静静地这么说着，视线同时朝向远方的草原。太阳的颜色不知道什么时候已经变得很浓，让宽广的草原发出金色光辉。

「……回想起来的，是在来到宁静花园之前玩的那个游戏吗……？」

兰的问题让深绿色马尾稍微晃动了一下。

「嗯。我只玩了一个月……而且不是正式营运，而是封闭测试。时间是二○二二年八月，算是宁静花园开始营运前一年吧。我戴的不是AmuSphere而是NERvGear，靠着它成为了世界第一款VRMMORPG的玩家……」

这番话经过了一段时间的延迟，才传达到有纪的意识当中。

兰在开始采集香草之前让自己看的新闻内容重新在脑内苏醒。于是她便以沙哑的声音轻轻呢喃着那个名字。

「……Sword Art Online……？」

轻微但确实点了点头的梅利达，嘴角依然挂着哀戚的微笑。

「没错。我在SAO封测的时候加入了中等规模的公会。那真的很有趣……一个月的封测转眼间就结束了，最后一天大家约好十一月正式开始营运时绝对要再次碰面。但是不久之后我的脑部就发现肿瘤。由于实在不是玩游戏的时候，所以NERvGear就被拿走了。」

「…………但是，那样的话……」

应该是从简短的呢喃就体会出兰的言外之意了吧，梅利达再次点了点头。

「嗯。托肿瘤的福，我才没被关进那款死亡游戏里面。父母亲和医生都说既然是拯救了生命的肿瘤就一定能治好……但是世界上的事情并非全都如此顺利。我的脑肿瘤是在无法动手术的地方，虽然持续进行化学疗法与放射线治疗，但是都一直无法消除。它已经陪我一年半的时间了。」

发出「呵呵」的笑声后，梅利达就像探索自己的脑袋当中一样，以指尖摸着太阳穴附近。

这时候不只是有纪，就连兰都无法立刻开口说话。

梅利达之所以在捕捉锹形虫的树木附近倒下，果然是因为脑部的疾病。恶性肿瘤，也就是所谓的癌症，对有纪她们来说也是很大的威胁。因为免疫力由于AIDS发病而下降之后，血液中的淋巴球变成癌症的风险将会升高。目前有纪和兰在定期检查时都没有发现肿瘤，但就算进入无尘室也无法防止细胞的肿瘤化。

放下手的梅利达把身体靠在椅背上，一边看着蓝色与淡黄色混杂在一起的天空一边继续说道：

「……我最近有个绝对不能跟父母亲说的想法。觉得与其这样因为肿瘤而死，倒不如被关进SAO……艾恩葛朗特里面，在那里跟公会的伙伴们一起战斗……」

「…………！」

有纪和兰同时屏住呼吸。

「艾恩葛朗特」这个名字，应该是成为Sword Art Online刀剑神域舞台的那座浮游于空中的巨大城堡。正式营运开始的同时，大约有一万名玩家被囚禁在该处，然后课以「无法登出，HP归零时玩家本身也会死亡」的规则。之后的一年半里已经出现超过三千人的死者。以个人所引起的事件造成的牺牲者数来看，应该是日本历史，不对，应该是世界历史上最多的吧。

为什么要自愿进入那么恐怖的游戏当中──有纪她们无法对梅利达这么说。

罹患恶性脑肿瘤后在五年内的生存率平均来说大概是百分之三十左右。概略算起来，五年当中有七成的患者将会失去生命。这个数字远远超过SAO大约三成的死亡率。

「……也是啦。」

这么呢喃的是兰。回过神来的有纪看向身边，发现姊姊的侧脸虽然还是平常一样安稳，但深蓝色眼珠似乎增加了些许光辉。

「如果我经历过Sword Art Online刀剑神域的封测，可能也会跟梅利达有同样的想法。对于疾病就只能忍耐，但是怪物的话就能以自己的力量来战斗了。」

听见兰这么说，梅利达像是有些惊讶般瞪大双眼，接着视线就落到桌面的空盘上。发出纯白光芒的盘子，让人不敢相信刚刚上面还放着加了一大堆奶油的可丽饼。

「…………嗯。与其就这样悄悄死在医院的病床上……真的很想立刻冲进SAO里，为了其他人战斗而死。总觉得……如此一来……说不定就能找到我活着的意义了…………」

透明水滴滴落白色盘子发出「啪答」一声。在西下的阳光照耀下，短暂地发出美丽光芒然后消失得无影无踪。

活着的意义。

这句话深深地刺进有纪心里。

虽然没有对过世的双亲甚至是姊姊提过，但从很久以前就反覆思考着同样的事情。自己为什么活着呢？让父亲与母亲痛苦，学校的老师与同学困扰，没有留下任何东西应该就会在成为大人之前死亡的自己，现在活着究竟有什么意义。

这个问题目前还找不到答案。说不定到最后的瞬间都无法找到，但是有纪还是无法点头同意梅利达的话。当她很想把从心底深处涌出的感情化为言词，持续不断地吸入空气时，兰的手就温柔地抚摸着她的背部。下一个瞬间，有纪就从嘴里发出巨大的声音。

「不行……不能这样啦，梅利达！你这么做的话，就再也无法见到爸爸和妈妈了。不能让他们伤心难过啦……因为……因为……」

跟我和姊姊不一样，梅利达随时都可以跟父母亲见面啊。

梅利达似乎感受到有纪没有说出口的话了。她抬起被泪水湿濡的脸庞，持续以大眼睛凝视着有纪，最后嘴角出现些许笑容并且点了点头。

「……嗯……说得也是。抱歉喔，有纪、兰，我不该说这种奇怪的话。」

像刚才的有纪那样以双手擦拭脸庞数次来甩落泪水。破涕为笑之后，梅利达就用充满元气的声音继续表示：

「别担心！因为接下来还有好好养育罗伊，在下一届昆虫终极淘汰赛里获得优胜这个目标！而且……实际上现在也没办法到艾恩葛朗特去。何况只有NERvGear才能运作SAO，能够连线的IP也仅限于目前那些玩家使用的位址。」

听她这么一说， 就想起自从事件受害者使用的之外所有NERvGear强制遭到回收后，确实就没听过有自愿登入SAO的人了。有纪这才放松肩膀的力道，脸上也浮现笑容。

「淘汰赛我会去帮你加油。一定要获得优胜喔！」

「交给我吧！」

「咚」一声拍了一下胸膛的梅利达伸了一个大大的懒腰后，像是突然想起什么般表示：

「对了，有纪和兰还有玩什么VR游戏？」

兰代替刚把剩下来的可丽饼吃进嘴里的有纪回答：

「没有，我们一开始就只有来这里。」

「咦～太可惜了。明明可以单脚站立那么久！我想应该可以活跃于所有动作系的游戏才对……」

她的话让姊妹面面相觑。

她们知道这一年里发售了许多对应AmuSphere的游戏。几乎和宁静花园同一时期开始营运的「ALfheim Online」这款MMORPG游戏，变成精灵来翱翔于天际的概念受到相当大的欢迎，其他还有跟僵尸战斗的恐怖射击游戏，或者探索遗迹的冒险动作游戏等常见的类型。

但是至今为止，有纪根本没有跟兰提到过想玩玩看其他游戏。理由应该是因为使用Medicuboid「单纯只是玩游戏」，总是会觉得有种罪恶感。而使用免费提供的修改版NERvGear的兰恐怕也有同样的感觉吧。

当犹豫着该如何跟梅利达说明时，兰就微笑着说：

「虽然很高兴听到你这么说，但AmuSphere用的游戏软体很贵吧？我们的零用钱实在买不起。」

兰所说的也算是事实。双亲亡故后又过了一阵子，两个人便彼此商量要缩减零用钱的金额。因为想尽可能把双亲留下来的遗产捐给支援重症儿童的NPO团体。因此实在不会想去购买将近一万日币的游戏软体。

但是梅利达眨了眨眼睛后就大动作摇摇头。

「啊，这你们不用担心！现在也有使用者免费但是道具需要付费的游戏喔。」

「咦……你的意思是游戏软体本身是免费吗……？」

惊讶地这么问完，这次梅利达换成用力点了点头。

「YES！下载软体并且安装就能玩了。想购买支援道具或者帅气装备就要花钱了，但我也完全没有课金哟。」

「这样啊……是什么样的游戏？」

兰出乎意料地以感兴趣的口气这么问道。梅利达在左腰附近做出握住某种东西的动作后，随即「咻」一声把右手伸到桌子上。

「最近很久没玩了，那是名为『飞鸟帝国』的和风MMO。成为武士、忍者或者巫女来战斗。风景和宁静花园完全不同……有大到极点的城堡以及非常漂亮的神社，真的很有趣喔。」

「……战斗……」

有纪忍不住这么呢喃。

因为是游戏，所以战斗本来就是理所当然。但还是对于在虚拟世界里拿着刀或枪等武器和其他玩家战斗感到害怕。和萤幕上面的角色不同……对方除了是虚拟角色之外也是真正的人类。在知道这一点的情况下，实在不认为能认真地砍杀、打击或者殴打对方。

但这个时候，兰再次做出令人意外的发言。

「听起来很有意思耶。」

「对吧！」

梅利达眼睛闪闪发亮，从桌上探出身子。

「嗳，不介意的话，要不要到飞鸟帝国来看看？我可以帮你们带路！」

「这个嘛……」

「穿上巫女或者武士的装备后我帮你们拍照吧！你们两个很适合那种打扮！」

「这个嘛……」

「还有，馅蜜、汁粉和蕨饼可以吃到饱哟！」

「…………！」

有纪没有错过姊姊肩膀震动了一下的反应。不只在宁静花园，连在医院咖啡厅都吃不到的麻糬汁粉，是继母亲亲手烤的可丽饼之后姊姊最喜欢的食物。

为了帮助被玩游戏的罪恶感、对未知世界的憧憬以及汁粉的诱惑夹在中间的姊姊，有纪下定决心来叫道：

「姊姊，难得梅利达如此邀约，我们就去看看吧！医生一定会答应的！」

结果兰就以有些惊讶的表情看了一下有纪，然后脸上露出难得一见的百分百笑容并且点了点头。

「那好吧……我们去看看！」

「太棒了！」

梅利达高声拍了一下手，接着瞄了空中一眼。

「今天……应该没办法了。我会先把安装飞鸟帝国的方法寄到宁静花园的帐号，明天下午一点可以吗？」

「嗯，好喔。」

兰点完头后，梅利达就拖着马尾轻轻跳跃来迅速站起身子，接着伸出左右两边的手。

「有纪、兰，能跟你们两个成为朋友我真的很开心。今后也请多多指教！」

觉得对方直率的视线与发言相当炫目的有纪和姊姊一起站起来，然后和这名隔了好久才又交到的朋友紧紧握手。

4

隔天五月十二日是星期日。

由于外来诊疗今天休诊，感觉整间医院比平常安静了一些。只不过只有因为检查与入浴而从Medicuboid里出来时，才能感受到这些事情。

由于有纪无法使用感染风险高的病房大楼内的共用浴室，所以在邻接无尘室的灭菌室设置了吊舱式的特殊入浴设备。虽然浴槽部分极为狭窄，与其说是入浴倒不如说是受到洗涤，但是能用热水洗身体和头实在很舒服。

宁静花园里也存在超巨大澡堂，或许应该说温泉饭店般的地点，但热水的感觉还是跟现实世界不同，另外虽说是虚拟角色，在他人面前裸体还是有抵抗感。虽然经常被兰取笑「你想太多了吧」。

星期日上午的入浴时间结束，感觉清爽多了的有纪在全身消毒后穿上代替睡衣的检查衣回到无尘室，然后躺到Medicuboid试验二号机的高密度凝胶床里。相对于被称为「MFT1」的试验一号机，正式名称是将医疗与立方体结合起来所形成的二号机，正如它的名字一样本体部分是巨大的箱型。现在正在开发中的三号机似乎更为庞大，但有纪已经不知道能不能看到它正式上市了。

躺着茫然想着这些事情，脑袋里就重新响起细微的声音。

──如此一来……说不定就能找到我活着的意义了……

活着的意义。

几乎所有参加宁静花园的高龄玩家，一旦来到自己要求进入的VR世界，就会有惊人的活动力，但偶尔还是会听到一些消极的发言。

──反正也治不好了，希望能赶快死一死。

──反正也不会有什么好事了，活下去也没用。

兰每次遇见这样的老年人们，都会拼命鼓励来让他们恢复元气。但是有纪却一直没办法像姊姊这样。这是因为她内心也被类似的虚无感盘据着。

到半年前，光是靠着不想让父母亲伤心这个理由就能一直努力下去。不论再怎么辛苦，在双亲面前都能保持精神十足的模样。觉得只要能让最喜欢的爸妈露出笑容，自己什么事情都办得到。但是现在双亲已经不在了。

现在最爱的姊姊还能待在自己身边。绝对不想说出让姊姊伤心的话，也不愿意做出这样的事。只不过──假如、万一要是发生兰丢下有纪先到双亲身边去的情况。实在不觉得接着还能找到活下去的理由。

不对，兰不可能丢下有纪一个人不管。只要有纪还活着，兰就不会死去，反过来也是一样。

别再乱想了。难得梅利达招待我们到新的游戏去。不想露出阴郁的表情。

VRMMO游戏「飞鸟帝国」的应用程式，在仓桥医生的允许下──强调必须保密是Medicuboid的测试者──已经完成安装并且制作好虚拟角色。有纪确认完时间后就把头放到靠枕上，手动降下头套部。

闭上眼睛，听着「咻咿咿咿」的细微机械杂音，咏唱NERvGear与AmuSphere唯一共通的完全潜行开始指令。

「……开始连线！」

从应用程式启动装置里选择的并非平常的宁静花园，而是新追加的飞鸟帝国图标，接着有纪的意识就开始往数位的黑暗坠落。

脚边开始有光圈靠近，钻过该处的瞬间，一片光线就在视界里散开。

两脚接触到地面的同时，有纪眨了一下眼睛。一抬起头就有风雅的色彩映入双眼。

红与黄、朱色以及橘色。包围四角形空间的，是颜色鲜艳的树叶随微风沙沙摇动的无数树木。

天空是具透明感的蓝色。地面覆盖白色碎石，移动脚步就发出「叽窸叽窸」的轻快声响。前方耸立着一座巨大鸟居，上面涂着比红叶更深一轮的红色，鸟居前方延伸着铺有砂石的参道。

「……这的确跟宁静花园有很大的不同。」

由于听见这样的声音，有纪就往旁边瞄了一眼，结果该处站着一名女孩子，身上穿着简朴但外形可爱的和服。长相跟现实世界以及宁静花园有微妙的差异，但是从发型、声质以及气氛就瞬时了解那是兰。目前周围看不见其他玩家的身影。

有纪确认自己也穿着同样造型但颜色不同的和服并且点了点头。

「果然有浓浓的和风感。」

「真的。姊姊我开始觉得很期待了。」

「你的目标是汁粉吧？」

「那是当然了！」

当她们悠闲地对话着时，就从鸟居那边传来「咻哒哒哒」的轻快脚步声。以剧烈前倾的姿势往这里跑过来的是一名拖着长长马尾的女孩子。

钻过鸟居后就高高跃起，在空中完成连续转身的动作，最后降落到两个人的眼前。

「喔喔～」

有纪和兰拍起手后，全身穿着符合忍者形象亮绿色装束的女孩子就夸张地行了个礼。视线一直对准她之后，头上就浮现「Merida」这个角色名称。这是宁静花园不存在的机能。

「久等了！欢迎来到飞鸟帝国！」

抬起头来的梅利达，一看见两人的瞬间，那比昨天稍微精悍一些的虚拟角色就像很感动般轻轻往后仰。

「有纪和兰都很会创造角色耶！两个人都很可爱，而且很像宁静花园的角色哟。」

「是……是吗……只是稍微改变一下基本套件里的模组而已……」

如此回答的有纪，这时才终于发现视界左上角浮着不曾见过的东西。

细长的蓝色棒子与绿色棒子上下并排，下方显示着「Yuuki」这个名字。持续聚焦视线后，绿色棒子上就浮现「LP 350／350」，蓝色棒子上则是「SP 100／100」等文字。

应该是从视线的方向察觉到有纪在看什么吧，梅利达竖起食指来表示：

「只玩过宁静花园的话，应该是首次见到吧。绿色的是Life Point，也就是生命力。而蓝色的是Soul Point，就是使用法术或技能会减少的东西。目前还是『新人』所以两个人的数值一样，但是在城里接受入门任务并且决定职业之后，其中之一就会大量增加了。」

「这样啊……梅利达是什么职业？嗯，从你的打扮大概就能猜出来了。」

兰一这么问，梅利达就露出满足的笑容，双手迅速组成复杂的形状。这也就是所谓的结印吧。

「喝！」

最后发出一声喊叫。下一刻，一阵淡蓝色烟雾包裹住梅利达，她的身影也消失无踪。兰同时左顾右盼注意着周围，但是根本连影子都找不到。只响起踩着碎石的脚步声，然后从正后方感觉到气息──当这么想的瞬间，有纪已经被从后面紧抱住了。

「有纪Get！」

再次有烟雾随着这样的声音涌出，抱住有纪的双臂跟着出现。

「哇啊，我不是锹形虫啦！」

开始挣扎之后，梅利达就发出开朗的笑声并放开双手回到原来的位置。兴致勃勃地看着这一切的兰则一边点头一边表示：

「也就是说，梅利达是忍者对吧？」

「答对了！正确来说，忍者是盗贼的上级职业。新手玩家都是从『剑士』『盗贼』『术士』其中之一入门，然后转职成武士、弓师、忍者、巫女和僧兵等各种职业。」

「这样啊……那我要当什么才好呢？」

「烦恼该选什么职业也是MMO的乐趣哟！」

梅利达咧嘴笑了起来，指着鸟居说：

「来，我们走吧！那边有飞鸟的首都喔！」

飞鸟帝国这个游戏，是古代近畿地方兴起的大和王权持续统治了千年以上这样的设定。首都净御原是建设成棋盘状的广大都城，面积足有宁静花园首都赛雷尼蒂的三倍吧。

同时最大上线人数也是仅次于VRMMO最受欢迎的ALfheim Online，所以星期日午后的首都充满了穿着和风装束的玩家。首次看见虚拟世界聚集了那么多玩家的有纪与兰，在钻过南大门时就说不出话来只能呆立在现场。

而且不只是人数而已，不知道该说是生气勃勃还是龙蛇杂处，充满虚拟街道的能量和宁静花园完全不同。宽三十公尺左右的主街道上有热闹谈笑的集团、气势汹汹地吵架的集团，甚至有人在路边摆摊做生意。

「呼哇……好多人啊……」

有纪一这么呢喃，梅利达就做出「对吧！」的回应。

她催促姊妹继续前进，一边稍微放低音量接着说道：

「刚发生SAO事件的时候，大家都很害怕VR游戏，还出现限制完全潜行技术的言论……但这个世界果然拥有过往的游戏所没有的『某种东西』。一旦尝过它的甜头之后，就再也回不去萤幕和游戏控制器了……」

有纪也能理解梅利达想说什么。

虽然不清楚今后会不会继续玩飞鸟帝国，但是没办法到宁静花园去的话，每一天都会变得无趣许多吧。和兰聊天、吃点心、寻找采集道具、一起用功……因为她每天都深刻地体验着这些幸福。

虽然世界不同，但飞鸟帝国里的几千名玩家们一定也是这样。不是单纯拿来杀时间，也不是逃避现实世界的地点。至于梅利达应该也一样才对。正因为在这里找到些什么，才会努力到成为似乎是上级职业的忍者。

但是梅利达昨天在洛伊提村的可丽饼店里，却做出似乎想回到Sword Art Online刀剑神域的发言。她说如此一来说不定就能找到活着的意义并且流下眼泪。也就是说，在这个飞鸟帝国里面，梅利达没有找到真正想要的东西吗？如此一来，同样是VRMMO游戏的飞鸟帝国与Sword Art Online刀剑神域到底有什么不同呢……

「看，那里就是『入门处』喔！」

梅利达充满元气的声音把有纪从沉思里拉回来。一看之下，通道右侧耸立着具备三个入口的特大建筑物。

「剑士、盗贼和术士，有纪和兰想成为哪一种？」

「这三种职业有什么不同？」

梅利达仔细回答着对游戏不甚熟悉的兰所提出的问题。

「剑士是到队伍前面以武器或格斗来战斗以及抵挡敌人攻击的角色。盗贼是以敏捷动作扰乱并且从事其他各种工作的角色。术士是在后方以魔法进行攻击或者援护的角色……大概是这样吧。」

「唔嗯唔嗯，原来如此。」

脖子和兰歪向同样的方向，思考了五秒钟后有纪就做出了决定。

「那我选剑士！」

「我来当术士吧。」

听见两人回答的瞬间，梅利达就发出「呵呵」的笑声。

「我就觉得是这样。那么有纪走正中央，兰从右边的入口进去，在里面承接任务吧。我也会帮忙，让我们立刻解决入门任务吧！」

「喔──！」

举起右拳来大叫完，和兰互相点了点头的有纪开始跑了起来。

挥舞自己手上的武器，与真实的怪物战斗这样的经验带来相当大的冲击。

一开始时，每当足有大型犬那么大的老鼠冲过来，都会一边尖叫一边逃窜，但是被咬到也不会痛──会感到稍微有点不舒服的震动──即使砍中对方也不会流血──相对地会有红光飞溅──知道这些事情之后，就能够不觉得害怕来战斗了。至于兰则是打从一开始就没有露出动摇的模样，不断地击退大老鼠。

在熟练的忍者梅利达帮助之下，两个小时就结束多达五个阶段的入门任务。有纪顺利成为剑士，兰则是成为术士。梅利达邀她们去吃东西庆祝时，兰率先表示想吃的当然就是汁粉了。

「呼哇哇哇……」

冒着热气的漆碗被端过来的瞬间，兰就发出奇妙的声音来表达感动。

「好厉害，太完美了，梅利达。不论是麻糬的焦度、红豆的颗粒分明、作为配料的盐昆布还是店里的气氛，一切都无可挑剔。」

「……你……你能喜欢真是太好了。」

「要是知道有这么美味的汁粉，我就会早一点过来了……」

以感触良多的口气这么呢喃完，有纪就合起双手来献上祈祷，然后拿起涂漆的筷子。

先等姊姊吃了一口后，有纪也把汁粉凑到嘴边。甜味适中的红豆沙充满整个嘴巴，麻糬的香味随后又追了上来。虽然不像姊姊那样喜欢包馅料的食物，但这个确实很美味。

三个人在几乎没有对话的情况下吃完汁粉，然后同时呼出一口气。

放下筷子的兰啜了一口茶之后就说：

「……真的很美味。梅利达，谢谢你带我们到这里来。」

「听你这么说，我也很开心喔。」

「话说回来……净御原这个城市，是设定为在现实世界的飞鸟地方吧？」

「对啊，怎么了吗？」

面对露出狐疑表情的梅利达，兰指着桌子上的菜单说：

「把使用红豆沙的汤品称为『汁粉』的主要是关东地方。关西的话，红豆沙是『善哉』，使用红豆泥并且汤水没有颗粒的才是『汁粉』喔。」

「原来是这样啊！那么红豆泥在关东就是『善哉』喽？」

「这个嘛，关东的话不论是红豆沙还是红豆泥都是『汁粉』，『善哉』是没有汤汁的红豆沙加到麻糬或者汤圆上面。」

「原来如此！我虽然是东京人却不知道这件事呢。这么说来，我们点了汁粉结果来的是红豆沙，就表示这家店是关东式喽……」

面对露出佩服表情的梅利达，兰以一本正经的表情摇摇头。

「不，也不一定是这样。说不定正如梅利达所说的，情况是完全相反……」

这时候灵机一动的有纪边窥看姊姊的脸边大叫：

「啊，我知道了！姊姊，你说了这么多，其实就只是也想点点看这里的善哉对吧！」

「嘿嘿嘿，被识破了吗？」

看见轻吐舌头的兰，梅利达也开心地笑了起来。

加点的「善哉」并非红豆泥也不是没有汤汁，而是红豆沙汤汁里加了栗子，但这种形式也相当美味，所以三个人把它一扫而空，当她们离开店里时太阳已经快要下山了。

「啊，在这种时间还吃了两碗汁粉，晚餐不知道还吃不吃得下……」

梅利达摸着肚子这么发着牢骚。

「真是不可思议，明明是虚拟世界的食物，却真的会觉得很饱。」

有纪深深点点头并且表示「就是说啊」。

「听说吃东西时，完全潜行机器会全力刺激脑的咀嚼中枢，因此让连动的满腹中枢产生了错觉。」

「原来如此……等等，我从刚才就一直在佩服你们！有纪和兰的知识比我丰富多了。」

「没有啦，我只是把仓桥先生说的直接搬出来而已。（注：日文里医生与老师皆可称为「先生」）」

看见缩起肩膀的有纪，梅利达短短一瞬间出现从梦中醒来的表情。应该是因为发现刚才有纪说的仓桥先生不是学校的教师，而是医院的主治医师吧。

离开跟昨天的可丽饼店一样是私房景点的甜点店后，三个人并肩走在无人的巷弄里。兰所穿的白木木屐，在石头地板上传出喀啷叩隆的寂寞声响。

一会儿后，梅利达就以变得低沉一些的声音说：

「原来……有纪的主治医生能够理解完全潜行啊。」

「嗯……」

其实哪还有什么理解不理解，有纪目前使用的Medicuboid，就是仓桥医生建议她成为受验者。还年轻的他，对于利用完全潜行技术的癌末医疗抱持很大的希望。但有纪因为有保守秘密的义务，所以不能让梅利达知道这些事情。

「……梅利达的主治医生呢？」

如此反问之后，穿着灰绿色忍者装扮的肩膀就轻轻缩了起来。

「我的医生……没有太好的脸色。要登录宁静花园的帐号时，也拼命拜托他好几次……他似乎认为使用VR的安宁治疗跟QoL的提升没有关联。」

QoL是Quality of Life的简称，安宁疗养的目的是缓和病症带来的身体上、精神上以及社会上的痛苦藉此提升QoL。AmuSphere具备取消体感的机能，而且能够阻绝一定程度的病痛，因此有许多人期待它能代替具副作用与倚赖性的止痛剂。

但另一方面，完全潜行中的患者从外部看的话就跟一直躺在床上的状态没有两样，「这样能算是提升生活品质吗」的意见也确实存在。梅利达的主治医师应该也是这么认为吧。

现在的有纪不清楚究竟是谁对谁错。宁静花园与飞鸟帝国都是充满魅力的世界，确实感觉和兰在那里度过的时间相当宝贵，但是与现实世界的蓝子接触的时间已经可以说等于零了。如果可以不进入虚拟世界与无尘室，一整天都跟真正的姊姊待在一起，那么这种情况或许比较幸福……有纪在极偶尔的情况下会这么想。

代替低头陷入沉思的有纪，兰开口说道：

「……现在SAO事件仍未解决，对于完全潜行技术有不好的印象也是没办法的事。但是……我想相信这个世界的可能性。因为有宁静花园才能遇见梅利达，今后应该也能遇见更多人才对。就算只有虚拟世界的连结也没关系……因为我认为我们感觉到的才是真实。」

「嗯…………说得也是。」

梅利达把手放在自己胸口并点了点头。

「能够和有纪与兰相遇我也很开心喔。与两人一起度过的回忆将会一直留在这里……不是虚拟角色，而是我真正的心。」

梅利达的口气听起来很开朗，但是「回忆」这个词在夕阳下的巷弄里留下沉重又酸楚的声响。

她说过开始治疗脑肿瘤已经过了一年半的时间。这段期间，她应该一直思考着自己还剩下多少时间吧。正因为这样，梅利达才会想要在虚拟世界寻找自己活着的意义。

「……我也很开心。」

这么低声说完，有纪就举起右手，静静握住走在身边的梅利达的左手。

「我自从开始玩宁静花园就一直跟姊姊以外的人保持距离。因害怕伤害到他人与自己……但是──昨天梅利达直接给我们很大的冲击。所以才能够这么快就成为朋友。」

结果梅利达一瞬间瞪大眼睛，然后脸上露出灿烂笑容并且用力回握有纪的手。

「谢谢你，有纪！能听到你这么说，我真的很高兴！但是……我昨天脑袋里可能只想着锹形虫……」

「只能说是半斤八两，有纪和我的脑袋里也只想着可丽饼和汁粉啊。」

由于兰握着梅利达的右手同时这么说道，三个人就大声笑了起来。当她们尽情欢笑的时候，有纪感觉到有一股舒服的风吹遍自己的内心。

能够像这样大笑的话，这里究竟是现实世界还是虚拟世界就不重要了。

剩下来的时间里，要尽可能让自己多笑一点。就像梅利达对自己做的那样，希望下次自己也能够直接给某个人冲击。

住院之后──不对，从小学转学后，有纪首次有这种强烈的想法。

5

「话说回来，马上就是你的生日了。」

由于拿下听诊器的仓桥医生突然这么说，有纪不由得把视线朝右下方移去。

但是现实世界没有显示时间的视窗，无尘室的墙上也不可能挂着月历，于是她便往上看着医生并且询问：

「那个……今天是五月几日呢？」

结果仓桥就在无尘衣的厚厚面罩底下露出笑容。

「十六日喔。我记得木绵季和蓝子都是二十三日出生的吧。」

「是的。」

有纪扣着无尘素材检查服的扣子同时点了点头，仓桥隔了一会儿后才以感触良多的口气表示：

「木绵季也十四岁了吗……真的长大了呢……」

「咦……就我自己来说，还是希望能再长高一点。」

「哈哈哈，别担心，还会再长高的。」

仓桥以温柔的声音笑了一下，摸了摸有纪的头后就站起来。

「那下星期见了。」

「好的，再见了，医生。」

目送仓桥直到灭菌室的门关闭，然后就躺到凝胶床上。

自己是在前年生日刚结束后住到港北综合医院，到现在已经过了两年。期间有一半以上的时间，有纪是在这间无尘室里度过。

到稍早之前为止，结束跟仓桥医生每个星期一次的面谈后──都会产生一股冲动，想跟在他后面冲出门外，确认现实世界是不是跟原本一样存在。但是这几天却不太有被关在灰白色密室里的感觉。

理由一定是因为在四天前受到梅利达邀约而闯入的新世界和许多玩家有所接触的缘故。虽然只是在城镇或练功区打招呼，然后交谈个一两句的交流，但还是能感觉到他们的热情。即使发生过SAO事件，世界上还是有这么多人在享受VR游戏，每天都有无数新的冒险与故事诞生。

维持躺在凝胶床上的姿势移动身体，把头放到靠枕上。今天一定要转职成上级职业，有纪下定这样的决心并且降下头套，接着闭上眼睛。

「嘎噜哦哦哦嗯！」

身高足有三公尺的鬼型怪物一边发出奇怪的吼叫声，一边挥舞着简陋的野太刀。从贯穿粗糙蓬发的两根角迸出蓝黑色特效光来包裹住厚实的刀身。

「小有，技能要来了！」

听见兰的声音后……

「交给我吧，姊姊！」

有纪回喊并且把自己的刀举到上段。

转职任务的最后魔王「恶路王」是会使用五种太刀系范围攻击剑技的难缠对手。只是回避攻击的话，将会遭到之后在周围扩散开来的飞溅伤害，无法展开反击。

剑士作为「墙壁」的任务不是回避敌人的攻击，而是尽可能把它挡下来。还只是一阶职业，能力值偏低的有纪想要做到这一点就不能单纯用武器防御，自己也必须使出技能来与其冲突，藉此抵消威力。

应该瞄准的时机是从恶路王挥落野太刀开始，到攻击技能的威力出现这零点几秒的时间。

睁大双眼、屏住呼吸来瞪着敌人的短刀。敌人的动作随着「叽咿咿咿」的耳鸣般声音一点一点变慢。最近精神集中到极限时，这种感觉就会降临。巨大的野太刀结束「蓄力」，即将开始动作的瞬间。

────就是现在！

有纪在心中这么大叫，同时以左脚踩踏地面。

在飞鸟帝国里，是以名为「踏地之圆<Ground Circle>」的系统来发动剑技与灵术。在架着武器的状态下用力踩踏地面，脚边就会出现可以使用的技能／灵术的环状图示，第二步踏下其中之一的图示来做选择并且加以发动。

一开始都要先把视线移到地面，用眼睛确认之后才能踏到目标的图示，最近终于可以不用看就直接做出选择了。

「呀啊啊啊啊啊！」

有纪发出终于比较像样的吼叫声，右脚踩下图示，同时全力跳了起来。发动对空系剑技「日向」，刀身开始发出橘色光辉。

「加加啊啊！」

恶路王迸发第二次的咆哮。但这个时候，有纪的对空技能已经猛烈击中野太刀的中段部分。橘色闪光撕裂蓝黑色特效光，令其烟消云散。野太刀整个被弹回去，恶路王的身体跟着往后倾倒。

「姊姊、梅利达，就是现在！」

落下的有纪这么大叫的瞬间，从后方飞来的白色短签──兰的「咒符」贴到了恶路王的额头上。符纸发光后展开复杂的立体魔方阵，然后引起巨大的爆炸。

三道剪影以眼花撩乱的速度在发出呻吟并且脚步踉跄的魔王怪物脚边乱窜，用忍刀刻划出无数的伤痕。是梅利达的分身攻击技能。魔王的LP条被大量砍除，最后只剩下一点点。

这时恶路王从技能中断的行动延迟中回复，有纪的待机时间也同时结束。她把刀摆在左腰并且再次踏步。一感觉到踏地之圆出现，就以右脚踏穿配置在正面的图示。

「喝啊啊啊啊──！」

居合系剑技「墨薙」的长大攻击范围捕捉到魔王弱点的角并且将其斩飞。LP条终于归零，恶路王的巨躯化为蓝色火焰往四处爆散。

宣告长达二十分钟以上的战斗终于结束的吹奏声，与三人的欢呼重叠在一起。

到净御原向NPC报告完成任务，顺利转职为上级职业的「武士」与「巫女」后，离开建筑物的有纪和兰就眺望着装备全部更新的彼此好一阵子。

和平常在宁静花园穿的简朴服装完全不同，符合RPG形象的华丽装扮让人又开心又害臊，互相窃笑了一阵子后，就从头上降下熟悉的声音。

「有纪、兰，恭喜转职成功！」

抬头一看，发现坐在建筑物屋檐上的梅利达正在挥手。轻轻跳下来并且在空中一回转，最后在两人面前着地。

「两个人都很努力呢。四天就到达上级职业真的很快哟！」

「都是靠梅利达每天帮忙我们好几个小时。谢谢你。」

看见微笑着如此回答的兰，有纪也同样说了声「谢谢你！」。结果梅利达露出腼腆的表情并摇了摇头。

「没有啦，是我邀你们到飞鸟帝国来的，这点小忙不算什么……应该说，我自己也玩得很开心。因为平常几乎没有跟人组队。」

由于这四天里已经增加了不少飞鸟帝国的知识，所以也知道梅利达的职业，也就是忍者在所有上级职业中据说是最适合独行游戏的职业。另外有纪也能想像得到她这么选择的理由。

和组队认识的人登录为朋友，甚至更进一步加入公会的话，就会增加谈到游戏之外个人情报的机会。话题谈到现实世界的生活时，有纪、兰还有梅利达将被迫做出痛苦的选择。是要直接说出因为重病而住院，玩VR游戏是安宁疗养的一环，还是把事情蒙混过去呢。表明的话其他人将会特别关照自己吧，但那就跟说谎一样痛苦。

四天前，有纪希望自己能够像梅利达一样直接对人造成冲击。但那不是件简单的事情。梅利达本身一定也还在跟自己筑起的心墙战斗当中。

有纪不知不觉间低下头，兰则是轻轻拍了拍她的背部。

「好了，小有，梅利达说要去庆祝转职成功。」

「咦……啊……嗯！那我想到之前那家店去！」

「OK！那里还有许多美味的食物哟！」

脸上露出灿烂笑容后，梅利达就率先往前走。

有纪点的是奶油馅蜜，兰点了葛饼，梅利达则是抹茶百汇，三个人互相品尝了一些其他人的甜点来试味道，吃完后啜了一口热茶，然后三个人同时呼出一口气。

「啊～真幸福……和菓子和绿茶真的是绝佳的组合……」

面对闭起眼睛这么呢喃的兰，有纪和梅利达也默默点头同意。可丽饼适合咖啡、红茶或者牛奶，但不像红豆沙和绿茶一样是最佳搭档。

「提到最棒的组合，兰和有纪真不愧是姊妹。战斗中的连携可以说是天衣无缝，看起来实在不像VRMMO新手。」

由于梅利达突然这么说，有纪就和姊姊面面相觑，然后同时耸耸肩。

「我……我只是在前面挥动刀子，全是靠姊姊配合我的时机……」

有纪这样的发言以及……

「我只是在后面使用法术而已，而且可以看见有纪的动作……」

兰这样的发言可以说是同时响起，在旁边听着的梅利达便噗哧一声笑了出来。

「看吧，真的合作无间！嗯，厉害的不只这一点而已啦。你们两个人都可以不看脚边就使用技能了吧？我可是花了一个月左右才能办到喔。」

「那是因为……这款飞鸟帝国是我和小有第一次玩的VRMMO。梅利达之前就玩过别的游戏了，要切换应该很费工夫吧？还是说VRMMO的战斗系统都一样呢？」

兰一这么问，梅利达就先笑着点头，然后再摇摇头。

「啊～这的确有可能……因为战斗系统完全不一样。」

瞄了一下周围，确认甜点店内没有其他玩家后，才小声地继续说道：

「Sword Art Online刀剑神域正如它的名字所显示，里面没有魔法，只有使用武器的战斗，只要摆出姿势就能发动剑技……『Sword Skill』，然后技能也跟飞鸟帝国不同，不是只有单发而已。」

「不是单发而已……？」

兰无法想像这句话的意思而歪起头来，梅利达就以右手握住百汇用的细长汤匙，迅速地往直向、直向然后横向移动。

「嗯。也就是『连续技』。飞鸟帝国里面，技能之外的普通攻击是可以持续挥舞刀子，但SAO的魄力完全不同。摆好武器发动剑技的话，身体会半自动地活动……以异常的速度把剑「啪啪啪！」地连续挥动三四次。飞鸟帝国的战斗是拿起刀子，然后脚踩来叫出圆圈，接着再次出脚踩下图示，最后才终于能使出单发技能，我一开始时就觉得很缓慢……转职为忍者可能有一半是因为身体轻盈可以到处移动吧。」

梅利达这么说完就露出开朗的笑容，这时候有纪和兰都无法开口询问「那另一半的理由是什么？」。只能跟梅利达一起笑着。

「啊哈哈，梅利达乱窜的速度确实很惊人，刚想说人在那边，下一秒就出现在这里了。」

对兰的评论做出「这是忍者的基本功是也！」这样的回答后，梅利达突然露出严肃的表情。像是回想起跟魔王的战斗般缓缓眨了眨眼睛，然后再次开口：

「……那个，我觉得真的很厉害的，是有纪和兰的看破能力。尤其是今天的有纪……终局时，完美地看出恶路王使用范围攻击技能时的『初动』对吧？就连最顶尖的玩家，也没什么人可以连续十次以上破坏魔王的大技喔。在宁静花园抓到皇家崔顿锹形虫果然不是偶然。」

听见这出乎意料的发言，有纪只能茫然张开嘴巴。

至今为止，在这种场面获得称赞的都是姊姊。不论是考试分数、绘画的水准、跑步的速度都是兰占上风。这在虚拟世界也是一样。如果梅利达的眼里认为有纪比兰厉害，那么只能想到一个理由。就是姊姊使用的NERvGear和自己使用的Medicuboid二号机在性能上的差异。

「不……不是的，梅利达。」

有纪拼命摇着头，并且开口表示：

「其实我使用的不是AmuSphere……」

但这时回过神来的有纪瞬间屏住呼吸。要到飞鸟帝国去时，仓桥医生已经说过，千万不能泄漏正在进行Medicuboid实验的事实。

这时梅利达露出惊讶表情等待有纪说下去，结果果然还是兰出手解救没有说任何话只是一直保持沉默的有纪。

她以沉稳、温柔的声音开口说「那个……」。

「……梅利达。原谅我们至今为止一直瞒着你。但正如刚才小有所说的，我们没有使用AmuSphere。是医院的医师帮我们准备的修改版NERvGear。」

有纪也知道只能这么说了。但这有一半是谎言。一号机的话也就算了，现在有纪使用的二号机，并不是能称为NERvGear修改版的物品。

因为自己粗心的发言使姊姊得帮忙圆谎，这让有纪感到强烈的懊悔。当她在大腿上紧握起拳头，姊姊的指尖就温柔地抚过。像是在表示「没关系喔」一样。

梅利达似乎没有注意到姊妹在桌子底下的沟通。她瞪大了眼睛，几乎不成声地呢喃：

「NERv……Gear……」

眨了几次眼睛后，才又用有点沙哑的声音继续说：

「修改的意思是，变安全了吗……？」

「嗯……我是这么听说的。把电池的容量变小，并且装进限制器，让它无法发出危险的电磁波。我和有纪因为医院的方针而积极地采用VR安宁治疗，所以医院就帮忙准备了这样的设备。」

「这样……啊……」

应该是终于从惊讶当中清醒过来了吧，梅利达点了两三次头后才说：

「……我首次使用AmuSphere时，确实也觉得反应比NERvGear慢了一些，感觉情报似乎也有杂质……但是光靠硬体性能是没办法像那样战斗的。有纪和兰还是很厉害哟。」

对方露出灿笑并且这么说的话，姊妹两个也很难继续否认。

看着露出微妙表情保持沉默的姊妹，梅利达脸上就浮现更灿烂的笑容。

「总之恭喜你们转职成功！还有时间的话，我们到帝宫去拍照吧。上级装备真的很适合你们呢！」

「嗯，说得也是，我们走吧！」

由于穿着巫女装的兰迅速点点头，有纪也终于能够露出笑容。

这一天，在「天皇」居住的华丽宫殿入口拍摄纪念萤幕撷图──虽然VR世界不存在「萤幕」这个概念──后就解散了。

有纪和兰、梅利达之后也继续开心地玩着飞鸟帝国。有时候会回到宁静花园让梅利达向她们展示锹形虫的成长程度，或者是一起到之前那间秘密的咖啡厅吃可丽饼。梅利达虽然出现两次的晕眩症状，但总是很开朗，脸上也一直挂着笑容。

充实的时间过得特别快，到了后天就是有纪与兰十四岁生日的五月二十一日傍晚。

两人接到了梅利达完全出乎意料的提案。

6

「还是那么煞风景耶，至少墙壁与天花板也设定一下嘛。」

出现在有纪「房间」这个私人VR空间里的兰，环视着四周后以傻眼的口气这么表示。

以现状来说，就只有有纪跟兰两个人可以到访Medicuboid二号机的主记忆体所建构的房间。如果这个除了无机质的地板之外就没有固定的物件，周围的黑暗中随便浮着几个视窗的空间能够称为房间的话。

有一半的视窗是显示Medicuboid的各种数值情报，剩下来的则是随意显示的电视与新闻网站。正面最大的视窗上映照出装备在二号机上的相机所捕捉到的无尘室即时影像，变成从虚拟世界窥探现实世界的窗口。

穿着睡衣躺在坚硬地板上的有纪，抬头往上看着同样打扮的兰并且回答：

「这样就可以了！把这里像宁静花园的家那样完全订制的话，将会变得不清楚自己目前是在现实还是虚拟世界里。」

用手掌在自己身边空着的位置拍了两下，有纪又继续说「更重要的是……」。

「姊姊，你好久没有唱那个了。」

「好好好，小有真是爱撒娇。」

把头放在边笑边跪坐的兰膝盖上后闭上眼睛。有纪放松身体的力量，呢喃般的歌声开始随着柔软的手抚摸头部的感触传出。

那是鹅妈妈里名为《Hush little baby》的摇篮曲。也是两人的母亲经常唱给她们听的歌曲。虽然是购买镜子、公羊、载货马车等各种奇妙的东西给小婴儿的不可思议歌词，但有纪就是中意这一点。

虽然虚拟角色的声音和脸孔同样是以现实世界的声音为范本合成出来的结果，但是几乎没有不对劲的感觉。平稳的歌声像细浪一样扩展开来，盈满没有墙壁与天花板的空间。

So hush little baby, don’t you cry.

Daddy loves you and so do I.

Daddy loves you and so do I.

反覆唱完摇篮曲最后一节的兰，就这样继续摸着有纪的头好一阵子。

由于时间已经超过晚上十点，有纪开始迷迷糊糊地打起瞌睡，这时兰就用指尖弹了一下她的额头。

「喂，小有，不能睡着哟。还没讨论重要的事。」

「呜喵……啊，对喔……」

努力抬起沉重的眼睑，接着嘿咻一声抬起上半身。和姊姊相对而坐，双手环抱胸前并发出沉吟声。

「嗯…………──怎么办呢，姊姊？」

平常总是能立刻做出决定的兰，这次也没办法立刻回答。

傍晚时梅利达突然开口说出了一个提案。内容是两天后的二十三日，为了庆祝有纪和兰的生日所以想来探病。当然不是在虚拟世界，而是现实世界的横滨港北综合医院。

梅利达住的医院是位于东京的品川区，开车的话应该不用一个小时。她的家人当然会一起来，所以梅利达这边没有太大的问题才对。

但是有纪和兰没办法立刻回答「很欢迎你来」。因为就算她专程过来了，只要有Medicuboid的保秘义务，有纪就不能跟梅利达见面，也没办法跟她说明无法见面的理由。

就算不能直接见面，梅利达能够到医院来还是觉得很开心。即使只有兰可以跟她见面，光是之后听她说两人见面时的事情，有纪就不知道会产生多么幸福的心情了。

但是，如果只说一句「有纪没办法跟你见面」无法让梅利达接受呢……？要是因为这样而失去好不容易才交到的朋友呢……？

「…………相信梅利达吧。」

兰打破漫长的沉默这么说道。

「姊姊……但是……」

「梅利达的话，一定能够理解是有原因有纪才会想见也无法跟她见面。我想她绝对不会因为这样就生气。而且……请梅利达把AmuSphere带过来，从我的病房一起潜行的话，就能够到这个房间来了吧？」

「咦，要……要找她来这里吗？」

有纪忍不住大叫之后，兰就以恶作剧的表情点点头。

「在小有的房间办生日会的话，梅利达一定会很高兴喔。」

「嗯……嗯……稍微改造得像女孩子的房间一点吧……」

有纪环视充斥虚拟感的黑暗空间并这么呢喃，兰在拍了一下她的肩膀后就站起来。

「那就得快一点才行。因为就是后天了──话先说在前面，我可不会帮忙喔。」

「咦咦～～……」

「小有随自己高兴来改造就可以了，这样梅利达一定也会感到高兴。那么，我差不多要回去了。我会传讯息给梅利达说很欢迎她来喔。」

「……嗯！」

有纪也站起来用力点点头。与其因为害怕伤害他人与受伤而后退，倒不如全力一搏。这是梅利达自己教会有纪的事情。

兰挥手道声晚安后就离开房间，有纪便再次环视自己的虚拟房间。要举行生日会的话，至少需要桌椅吧。在那之前，当然也得有墙壁跟天花板。

虽然只有一天就会重置，但这是为了重要的朋友而改变摆设，就全心全力地改造吧。如此下定决心的有纪就面向一直没有收起来的设定视窗。

五月二十三日，星期四下午两点。

梅利达搭乘母亲驾驶的车子来到横滨港北综合医院。

腿部受到脑肿瘤影响而麻痹的梅利达虽然坐着轮椅，还是让母亲在医院的咖啡厅等待，自己移动到兰在医院八楼的个人病房里。带过来的托特包里，装着两份生日礼物与AmuSphere，两个人原本预定要从兰的床上潜行到有纪的私人VR房间去。

但是──

有纪和兰都没注意到梅利达一直隐藏在心底深处的计划。

在潜行前上完厕所，回到个室的兰见到的是放在床上的亲笔信，以及旁边已经开始潜行的梅利达。因为抗癌剂的副作用而失去秀发的头部，戴的不是她带来的AmuSphere，而是兰的NERvGear。

从「兰、有纪，真的很抱歉」起头的信，写着梅利达真正的心情，以及NERvGear的插槽里插入了「Sword Art Online刀剑神域」游戏卡的事实。

「咦…………！」

从独自出现在改造成可爱VR房间里的兰口中听见事情经过之后，有纪花了几秒钟才能理解整个状况。

梅利达没有使用带来的AmuSphere，而是戴上了NERvGear。理由是──AmuSphere无法驱动「SAO」的关系吧。也就是说梅利达的潜行并非一时冲动，而是从一开始就打算这么做才会把SAO的游戏卡带过来。她主动冲进了虚拟世界的死亡就等于真正失去生命的死亡游戏。

兰的NERvGear是经过缩小电池容量，以及追加限制器等安全对策的修改版。但是通常NERvGear是使用电源线。玩家在SAO内部HP归零时，破坏着装者脑部的电力是来自于墙壁上的插座。当然也不能利用梅利达来实验限制器能不能确实发挥功用。

「姊……姊姊！快点把梅利达的NERvGear脱下来！」

感觉虚拟室温急速下降的有纪这么大叫，而使用梅利达的AmuSphere潜行至此的兰则是迅速摇了摇头。

「不行……考虑到万一的情况，还是不能从外部强行把它脱下来。」

「为什么？姊姊的NERvGear已经把电池容量改小了吧，拔掉电源线再脱掉的话，应该无法发出危险的电磁波才对……」

「梅利达的脑有肿瘤喔。只要有一瞬间暴露在规格外的电磁波底下，就不知道会发生什么事情。不能光靠我们的判断就强制解除。」

「那么得快点去通知医生……！」

对于连这种时候都相当冷静的姊姊产生抗拒，有纪挤出所有的声音来这么大叫。

但是兰这次也没有同意。反而像是要有纪冷静下来般，把双手放到她肩膀上并且呢喃：

「我也认为应该这么做。但是在这之前，先给我一点时间吧，五分……不对，三分钟就够了。」

「三分钟……要做什么？」

有纪如此反问，兰则持续回望着她的眼睛并且回答：

「现在的话应该还来得及。和我一起来吧，有纪。」

把同时是应用程式启动装置的门叫到VR房间里之后，和兰一起钻过门的有纪因为降下的明亮光线而眯起眼睛。

宁静花园东部的洛伊提村。NPC小乐团演奏着闲静的BGM，坐在中央广场板凳上的玩家们正融洽地谈笑当中，这时变身成蓝色洋装模样的兰就猛然冲过广场。有纪也急忙跟在她的身后。

有纪完全搞不懂姊姊究竟要去哪里，说起来根本不知道为什么要到宁静花园来。梅利达早就已经到作为Sword Art Online刀剑神域舞台的浮游城艾恩葛朗特去了才对吧？无论怎么想，宁静花园都不存在通往SAO的大门。

但是兰却持续以感觉不到丝毫疑惑的脚步奔跑，钻过村门之后来到绿色山丘峰峰相连的提尔山丘。在铺设砖瓦的小路跑了一阵子，最后离开道路往左边前进，一直线冲过绿色草原。

越过几座山丘，前方出现闪烁蓝色光芒的小小水面时，有纪才终于察觉姊姊前往这个地方的理由。

直径二十公尺左右的池塘周围被短桩围住，水边还长了一棵树。

这里是有纪抓到皇家崔顿锹形虫的地点。

同时也是初次遇见梅利达的地点。

有纪瞪大到极限的双眼捕捉到蹲在树根旁的娇小人影。绿色马尾随风摇摆并且发出亮光。

拼命追过姊姊，跑在池畔的有纪大声呼唤名字的同时，人影也刚好站了起来。

「────梅利达！」

转过头来的朋友露出惊讶的神情，接着又哭又笑地瘫了下去。呼唤有纪她们两个人名字的声音，比之前听到的任何声音都要脆弱。

「…………有纪……兰。」

有纪慢慢放慢速度，在距离梅利达稍远处停下脚步。兰也立刻来到她身边。

打算要到SAO去而戴上NERvGear的梅利达，为什么会潜行到宁静花园呢？理由就存在梅利达的脚边。

打开出入口盖子的捕虫箱，以及依然停在上面的琉璃色锹形虫。培养到比初次见面时整整大了一圈的锹形虫，像在对饲主提问般缓缓动着触角。

随着有纪的视线往下看向锹形虫的梅利达，依然以忍住泪水的小孩子般的笑容说：

「…………罗伊无论如何就是不肯飞走。其实原本是想还给有纪，但是决定饲主的昆虫就没办法让渡给他人……于是就想在这边把它放走的话，哪一天可能还会被有纪抓到…………」

梅利达以沙哑声音如此宣告，有纪注意到她眼里噙着大粒泪珠时，胸口也涌起一道热气。身边的兰也同样用忍住泪水般的声音回答：

「罗伊怎么可能逃走。梅利达每天都那么细心地照顾它。它一定会在大会获得优胜。所以……和罗伊一起回来吧，梅利达。现在的话还只有我和有纪知道。」

一听到这里，有纪终于了解姊姊不把状况通知仓桥医生的理由。

就算在仓桥的判断下把NERvGear从梅利达头上取下，身为医师的他还是得把发生的事情告诉梅利达的家长。如此一来，梅利达恐怕就会被禁止接受使用AmuSphere的VR安宁疗养，再也无法潜行到宁静花园与飞鸟帝国里了。为了回避这样的事态，兰才会赌上能在这个地点说服梅利达的可能性。

深吸了一口气后，有纪也以灌注了所有感情的口气对好友说道：

「……拜托了梅利达，不要到SAO去。我还想继续跟梅利达一起冒险。想跟你到各种地方，欣赏各种事物。所以……所以……！」

但是梅利达却缓缓伏下眼睛，像是挤出每一个字般说：

「……抱歉了，有纪。抱歉了，兰。难得的生日却给你们添麻烦……真的很对不起。我没资格要你们原谅我。但是……我……我无论如何都…………」

上衣底下的肩膀开始蓄力并且微微震动。如同单薄玻璃般脆弱、紧绷的声音持续在午后的草原流动。

「……我在前阵子的新闻里看到了。警察订立计划要强制取下全国SAO事件受害者的NERvGear。但我不认为这样鲁莽的计划能够成功。绝对会出现许多牺牲者的……」

姊姊是在十几天前拿这样的新闻给自己看，地点是在这附近的山丘。就跟现在的梅利达一样，兰也说出同样的担心。

「……之前说过，我在封测时期加入的公会，有好几名成员现在就在SAO里面对吧。正式营运开始时，我原本也应该要参加的。但是因为发现生病了，所以只有我获救……但这件事一直、一直让我很痛苦。如果……如果现在也能到艾恩葛朗特去的话，我就可以把剩余的生命奉献给大家了。如此一来……或许就能留下我生存的意义…………」

「…………梅利达……」

有纪边叫对方的名字边往前一步。但是梅利达却猛烈地摇头并且往后退。飞溅出来的泪水反射阳光发出金色光芒。

「……拜托了，有纪、兰。让我到艾恩葛朗特去吧。这间医院也有SAO的受害者入住，可以通过IP位置的防火墙。虽然会让父母亲伤心，但我想他们能够理解。我……我无论如何都想找到自己诞生在这个世界的意义……！」

深切的独白横越过草原融化在微风中，最后在虚拟的大气中扩散开来。

初次相遇的那一天，梅利达也说过同样的话。而有纪这次也找不到该对她说些什么。想找到自己活着的意义──因为这也是秘藏在有纪自己心里的愿望。

这时兰默默来到呆立现场的有纪身边。

她轻轻蹲下，从捕虫箱上捞起罗伊。以右手指尖静静抚摸乖乖待在掌中的锹形虫那光艳的翅鞘，同时以平稳的声音开始说道：

「不论是在这个宁静花园还是飞鸟帝国，甚至是现实世界，都有许多梅利达活着的意义喔。除了把罗伊培育到如此雄壮之外，带我跟有纪到新世界也是你的功劳。今后一定也会找到很多生命的意义。」

「………………」

梅利达以盈着大量泪水的双眼持续凝视着兰，以及她手掌上的锹形虫。

最后稍微年长一些的少女嘴角浮现淡淡的微笑──然后开口说：

「……如果我有为你们两个人带来些什么，我会觉得很高兴。但是……我真正想要的，不论是这里、飞鸟帝国还是现实世界一定都找不到。我……想要战斗。不是静静在医院的病床上等待结束……想用这双手和比病魔更巨大……像是命运或者世界这样的对手战斗，把自己的生命燃烧殆尽然后才死亡。所以……拜托了，兰。让我走吧。」

「………………梅利达…………」

听见姊姊呢喃般声音的瞬间，有纪就了解了。

兰……蓝子她拥有远超过有纪的「共鸣之力」。那是能够陪伴、理解他人的痛苦与悲伤，并且加以接受的力量──

因此兰甚至能够对梅利达现在的心情产生共鸣。忍不住会有让她完成心愿的想法。

但是。

────但是。

这时候让梅利达离开的话，兰之后一定会很痛苦吧。会对自己的发言与选择感到懊悔，然后持续背负着无法补偿的罪过。

所以现在有纪一定得开口。不能像平常那样把一切都交给姊姊，要用自己的发言与意志来让梅利达打消主意。

有纪用力握紧双手，像要让身体中心产生震动一样大叫：

「…………梅利达！」

有纪直盯着因为突然的巨大声音而惊讶地眨了眨的翡翠色双眼，再次大叫：

「那就让我来帮你找吧！我会帮梅利达找到能够燃烧生命的东西！所以……所以，不要走啊，梅利达！」

听见这句话的梅利达再次眨眨眼，然后浮现淡淡的微笑。

「…………你要怎么帮我找呢，有纪？」

面对这沉静的提问，有纪也不清楚自己为什么会那样回答。但是接下来这句话也决定了有纪自己的命运。

「在飞鸟帝国和我战斗吧，梅利达。如此一来，我想你一定就能理解了。」

7

把放着罗伊的捕虫箱收回道具栏，从宁静花园登出的梅利达，不一定会按照有纪的希望不选择Sword Art Online刀剑神域，而是登入飞鸟帝国。

但是有纪却在首都净御原约好见面的地点，也就是耸立在郊外的巨大杉树底下相信梅利达一定会来而持续等待着。

周围一望无际的草原让人联想到刚刚还待在那里的提尔山丘。但是稍远处有一大片宁静花园不存在的芒草，此刻正随着冷风摇摆。

经过几分钟之后，耳朵听见熟悉的「咻哒哒哒」脚步声，有纪便回过头去。

忍者虽然身穿熟悉的鲜绿色装束，但是跟平常碰面时不一样，一开始就蒙住了大半脸部。忍者放慢速度，在距离有纪和兰五公尺左右的地方停下脚步，然后默默地看向这边。

「…………梅利达……」

有纪原本想说「谢谢你过来」，但是却无法说出口。从梅利达全身散发出来的那股提升到极点的锐利气息，正形成无形的压力朝有纪袭来。

有纪仍没有所谓「对人战」的经验。她当然知道有这样的系统存在，也曾经在城镇上观看公会成员之间类似运动竞技般的对战，但是她对认真和真人化身的玩家对战这样的行为有强烈的排斥感。

但这次的单挑是有纪自己所期望。

梅利达希望获得足以燃烧生命的目标而想前往SAO。那应该是某种虽然在虚拟世界却不是虚构的东西吧。存在于即使身患重病，也能跟其他玩家一样活动的虚拟世界的真实。

变成死亡游戏的SAO里，许多玩家在生与死的狭缝中战斗。有纪也稍微可以了解前封测玩家的梅利达即使主动变成死亡游戏的囚犯，也要为了过去的同伴……或者所有生存者而战斗的心愿。

但是同时也强烈地感觉那是一种错误。要说命运的话，因为发现生病而没有被囚禁在SAO里才是梅利达的命运吧。

在这边的世界一定还有可以做也应该做的事情才对。虽然不清楚是什么事，但绝对有。为了传达这个想法，有纪选择的不是言语而是战斗。

花了一些时间把累积在肺部的空气全部吐出，然后把虚拟世界的冷风吸满肺部，接着有纪就挥动右手叫出选单视窗。

触碰至今为止从未摸过的「决斗」按键。由于会出现挑战可能范围的玩家总览，就从那里选择梅利达并按下OK键。

至今为止都默默望着有纪的梅利达把视线朝下。抬起右手来触碰只有她看得见的视窗。有纪的视窗内出现「对方接受决斗请求」的讯息。

两人的中间地点开始三十秒的倒数。有纪以流汗的右手拔出左腰的刀子。分类是「打刀」，专有名称是「墨流」。刀身浮现黑色大马士革钢的纹路，虽然不是太稀有，不过是很容易使用的刀子。

迟了一会儿，梅利达也拔出爱刀。分类是「忍刀」，专有名称是「朱月」。它是拥有深红色直线刀身的稀有武器，虽然比有纪的刀小了一倍以上，但整体性能占了上风。

被忍刀锐利的刀尖对准的瞬间，有纪感觉胸口深处整个揪紧。

不可能躲开梅利达这个敏捷忍者的所有攻击。那把武器马上就要刺入、撕裂有纪的身体了。而有纪也必须用自己的刀来攻击重要的朋友。因为是虚拟世界所以感觉不到疼痛，只会减少数值化的虚拟生命，但这依然是真正的「战斗」。

真的能办得到吗？首次的对人战斗就面对梅利达，自己真的能好好地作战吗？

明明是主动要求的单挑，心情却不断地萎缩。呼吸开始急促，视界也跟着变得狭窄。

「…………呜……」

当有纪不由得开始发抖并且慢慢想要后退时，她的背部──

就被应该在几公尺外注视两人决斗的兰发出的声音推了回去。

──不要紧的。

──小有只要认真挑战。你的心意一定能传达给对方。

「…………姊姊……」

当口中这么呢喃的瞬间，有纪就不再发抖了。

这场单挑，挑战者如果不是有纪而是兰的话，胜算应该比较高吧。身为巫女的兰能准确地驱使各式各样的咒符，甚至还能以打击武器「大币」进行近距离战斗，其战斗力明显高于有纪。角色的等级方面梅利达当然还是比兰还要高出许多，但是飞鸟帝国里面，就算等级上升，能力的数值也不会增加太多。

但这时候要是跟平常一样倚赖姊姊，就算决斗获胜了，有纪的心意也一定无法传达给梅利达知道。

没错──要把有纪心中所有的感情与意志全部传达给对方。

有纪一直凝视着剩下五秒钟的倒数数字一边发出强烈的光芒，一边变成四、三、二、一逐渐减少。

数字零变成光环扩散并且消失的瞬间──

「咿……呀啊啊啊啊啊啊！」

插图p291

有纪把所有的勇气变成叫声喊出来，同时朝地面踢去。

武士的动作虽然不如忍者灵敏，但是唯有斩击时的突进力占上风。一步飞越五公尺的距离，摆在上段的刀子朝着直立不动的梅利达挥落。

但是──

近距离看见蒙面底下那跟宁静花园一样是绿色的眼睛，双手瞬间受到下意识的僵硬所袭击。墨色刀身微微震动，使得轨道往右偏移。面对怪物的话，这种程度的失误根本算不了什么，但是熟练的玩家梅利达不可能错过这个机会。

空气发出「咻」一声，梅利达以瞬间移动般的速度往左边回避。有纪的斩击只能徒然撕裂虚空，洒下淡淡的特效光。

下一刻，左肩就受到强烈的冲击袭击。有纪轻松被轰飞然后滚落地面。视界边缘捕捉到LP条减少一成左右，有纪顺势持续在地上滚动，拉开距离后才站起身。

再次架起剑的有纪看见的不是右手的忍刀，而是伸出左手手掌的梅利达。

忍者虽然有体术技能，但是体认到对方空手，而且还是透过保护肩膀的袖铠依然一击就能削除自己一成左右的生命值后，有纪不由得屏住呼吸。

虽然早就知道──但真的很强。

不对，只是自己觉得了解而已。至今为止的游戏经验里，梅利达总是专注于辅佐有纪与兰。自己极力不给怪物伤害，让两个人能够分配到最大限度的经验值。

梅利达只是展露一丁点的实力。光是这样就无法再次发动攻击，只能整个人僵住的有纪，耳朵听见沉静的声音。

「……我一开始时也是这样。」

蒙面底下的嘴角浮现出淡淡笑容。

「在SAO里首次和玩家单挑时，我的手臂缩成一团而且攻击完全打不中。这和攻击萤幕里面的角色不一样。即使脑袋理解不是活生生的人类，只不过是虚拟角色，但身体还是跟不上脚步……经过整整两个星期，我才比较能跟人单挑。」

「……后来为什么可以战斗了呢？」

有纪忍不住向身为对战对手的忍者这么问道。结果梅利达像要窥探记忆般抬头看着布满云朵的天空并且呢喃：

「……和跟我同样使用单手剑的人对战时，对方这么跟我说了。他说单挑不只是互相残杀，也有可以藉由剑与剑的碰撞传达给对方的事物。还说那跟既存的网路游戏、VRMMO，甚至是现实世界的运动竞赛都一样……所以刚才有纪跟我说『战斗吧』的时候，我真的有点吓一跳。」

没错──有纪确实有事情想传达给梅利达。那是虽然无法顺利化为言词，但是在心底深处卷动着的火热心情。认为藉由剑与剑的对谈，说不定可以把心情传达出去，所以才会对梅利达提出单挑的申请。

打从一开始就缩着手臂的话，将无法传达任何心意。必须克服恐惧与犹豫勇往直前。前进、前进，不断前进……直到靠近梅利达的心为止。

「……必须猛力冲撞才能传达出去对吧。」

像是听见有纪对自己发出的呢喃声一样，梅利达也点点头。灵活地将右手的忍刀换成反手握住，接着斜斜摆在身体前方。相对地有纪则再次把刀举到上段。

这次换梅利达率先发难。

身体整个前倾，化身为鲜绿色强风从正面冲过来。这次应该不会手下留情了。必须想办法防御或者回避忍刀使出的超高速斩击并展开反击。就在要凝视微微反射阳光的红色刀身时。

──不是刀子，必须注意梅利达全身喔，小有！

感觉从后面传来这样的声音。瞬间，有纪瞪大眼睛拓展变得狭窄的视野。

梅利达的右手在前面架着忍刀。左手被刀子的阴影遮住而看不清楚，但握住的拳头里有某种物体发出亮光。

──刀子是障眼法。初击是左手的……手裏剑！

梅利达的左手变得模糊的刹那，有纪就朝一瞬间看见的反射光挥落双手握住的刀子。

「铿！」一声，尖锐的金属声响起，白色火花四处飞溅。被有纪刀子弹开的十字手裏剑，一边旋转一边弹回梅利达身边。是武士的固有技能「回击」的效果。

「呜……！」

忍者简短地呼出一口气，同时以右手的忍刀再次弹开手裏剑。意识不再注意往右斜上方消失的反射光，有纪朝向失去平衡的梅利达全力跨出一大步。

距离完全没问题。也不再犹豫了。

不是因为想获胜，也不是因为憎恨或者想杀害对方而出刀。这是经由梅利达锻炼过的技能……因为想传达存在于技能之后的意义，所以才挥剑。

「呜……呀啊啊啊！」

边叫边翻转手腕从下段往上砍。黑色刀刃陷入即使从不安定的姿势也想往后跳来拉开距离的梅利达怀里。

沉重的手感随着「嚓咻！」的效果音贯穿手部。深红色光芒从有纪高高挥尽的刀身上朝天空的高处延伸。显示在梅利达头上的LP条减少了一成五左右。

如果是对怪物战的准则，这时候应该叫出踏地之圆来发动剑技，给予僵硬中的敌人莫大的伤害。但光是被轰中一击，应该无法让梅利达露出那么大的破绽。追击应该要用普通攻击──但是要用上自己的全力。

有纪第三次把爱刀举到大上段。

另一方面，梅利达则是利用承受上砍攻击的力道准备使出后空翻。

为了不错过落地那一瞬间产生的转瞬空档，有纪奋力往地面踢去。

「喝啊啊啊────！」

从腹部深处迸发吼叫声的有纪，就快要使出浑身的一击之前……

空气发出「当！」一声。

在空中缩起身体的梅利达笔直地往下看着有纪，双脚同时踢向空无一物的虚空。这是忍者的固有技能「两段跳跃」。

「霎啊啊！」

这场战斗中首次放射气势的梅利达朝着有纪冲去。右手的忍刀变成朱红色闪光，迫近有纪的喉咙。

斩击的速度本身是忍者梅利达比较快，但是先发招的是有纪。以现状来说，双方的时机是不分轩轾。但这时候要是输给恐惧感而动作稍有停顿，就会遭受反击的猛烈痛击。

有纪想传达给梅利达的心意。

也就是我会变得更强给你看。

封闭的死亡游戏SAO外侧，世界是无限的宽广。不论是虚拟世界还是现实世界，还有许多的邂逅、发现与故事在等着你。

────我会带着你到任何地方。

────我会帮梅利达发现新的命运。

────所以…………！

「…………────啊啊啊啊啊啊啊啊────！」

一片白光呈放射状有纪的视界里散开。光辉的粒子像小星星一样从虚拟角色全身散开。被刀刃压缩的空阻增强到极限，突破空阻般的感觉降临──

在完全的寂静当中，有纪的刀刃变成一道闪光往下挥落。

迟了一会儿，梅利达的忍刀抚摸过脖子左侧并且穿透到后方。

维持刀子挥落姿势的有纪一动也不动。整个世界的声音恢复之后，从脖子的伤口「咻啪」一声喷出深红色伤害特效光，LP条又减少了两成以上。

踩着踉跄脚步回过头，梅利达依然维持挥尽忍刀的姿势僵在那里。

突然间，穿着忍者装束的左肩到背部无声地裂开，接着从该处迸发出大量红色特效光。梅利达原本剩下八成五的LP条开始急遽减少，在稍微低于五成的情况下停了下来。

宣告单挑结束的视窗忽然随着「咚咚！」的太鼓声出现，有纪惊讶地发出「咦」一声。虽然眨了好几次瞪大的双眼，但视窗上确实大大地写着「胜利者：有纪」。

「为……为什么……还没……」

当有纪慌了手脚时，缓缓撑起身体转过头的梅利达就把忍刀收回腰间的刀鞘一边笑着说：

「飞鸟帝国的单挑，除了战斗到死为止的『生死斗』模式外，还有LP减半就结束的『比试』模式。接受挑战的我选择了比试模式，所以这场单挑完全是有纪的胜利……恭喜了，你真的很强。吓了我一跳。」

「……那……那个……」

认为接下来苦战才要开始的有纪却面临突然的结束，只能够茫然呆立在现场。

似乎在单挑中获胜了。但不知道是不是已经把自己的心意传达给梅利达知道。梅利达站在那里露出平稳微笑的模样，似乎立刻就要融化在日照当中一样脆弱，有纪甚至忘记把刀子收起来，不顾一切就开口说：

「……如果真的是我比较强的话，也全都是托梅利达的福喔。因为梅利达教会了我许多东西，我才能够变强。我说了要帮梅利达找到能够燃烧生命的事物吧。虽然还不知道那是什么……但是我可以保证。我会变得更强，会带你到任何地方……不论什么地方都没问题…………」

虽然好不容易把战斗中感觉到的事情化为言词说出口，但声音到这里就中断了。面对吸了好几口气后，依然想开口继续说话的有纪──

梅利达拉下蒙面并露出灿烂的笑容。那种笑容跟初次在宁静花园遇见她时所看到的完全一模一样。

「传达给我了哟，有纪。」

「咦…………」

「有纪的心情透过武器确实传达给我了。不只是对我的心意……其他还有许多、许多的事情都传达给我了。嗯……我的脑筋不是太好，所以不知道该怎么说就是了。有纪的强大……不对，是某种更大的，那个……」

这次换成梅利达在思考该怎么形容而吞吞吐吐起来。

「……可能性。」

这道沉静的声音，让梅利达与有纪同时移动视线。

声音的主人是站在高大杉树底下注视着两人决斗的兰。露出平常那种温柔微笑的巫女，以滑行般的步伐靠近两个人并且再次说道：

「是可能性对吧，梅利达？」

「对，就是那个！」

梅利达啪叽一声打了一下响指，同时不停点头。

「有纪的内心塞满了各式各样的东西。单挑时的强大实力只不过是其中一部分……有纪今后将会变得更强、更大。有一天，各个世界的人都会知道你的名字。」

「…………怎么可能……像我这样的……」

虽然含糊其辞，但有纪还是一直凝视着梅利达的脸。

上面已经没有钻牛角尖的表情。但是感觉透明的虚无感仍未完全消失。

梅利达取消到SAO去的主意了吗，或者还是没有改变决心呢？当有纪打定主意准备开口询问的时候。

站在右侧的兰就把手放到她的肩膀上，同时说出意想不到的发言。

「梅利达、有纪。我从之前就有一个想法了。」

「……什么想法呢，兰？」

「我想由我们三个人来创一个公会。然后一点一点地增加伙伴……朋友，然后我想把这个小圈子逐渐扩大。」

这么说完后，兰就以左手握住有纪的右手。接着对站在稍远处的梅利达笔直地伸出右手。

下意识当中，有纪也对梅利达伸出左手。

往下看着两只手的梅利达，以有些犹豫的表情回答：

「但是，兰……我们……」

没错。这也是有纪感到在意的地方。

在VR安宁病房相遇的三个人，具备跟重病战斗的共通点。假如在飞鸟帝国组成公会，并且有新成员愿意加入，也不可能永远把生病的事情瞒着他们吧。哪一天需要向他们说明的日子一定会来临。或者在那之前──强制离别的时刻就到来了。

跟公会成员越熟，到时候双方将会越痛苦才对。甚至很可能会造成公会分崩离析的情形。兰应该也了解这一点。

「…………虽然会想哪一天、哪一天能够战胜病魔，把这个圈子不断扩展下去…………」

先以呢喃般的口气说到这里，兰接着又用坚定的声音继续表示：

「一开始想先邀请跟我们有同样境遇的人。我想宁静花园里一定还有许多像我们一样，想要看看外面的世界，想到更远处看看的人存在。邀请这样的人加入公会，大家一起到虚拟世界的尽头去看看吧。就像梅利达拉住我和有纪的手那样。」

兰在伸出去的右手依然没有任何摇动的情况下把话说完。

梅利达像是略感惊讶般瞪大双眼，然后默默地凝视着兰。

风儿吹动，巨大杉树的无数叶子沙沙作响……草原上已经看不出单挑过的痕迹。碎片云静静流过颜色与宁静花园有些不同的蓝天。苍穹高空有一只老鹰翩然飞舞。

飞鸟帝国的世界地图，目前是以近畿地方为中心，东边到富士山，西边到关门海峡──当然游戏内的名称不同──作为尽头。但听说接下来的改版将追加关东地方与九州地方。这个世界将会不断扩大，另外像ALfheim Online等VRMMO游戏也会不断增加吧。

──一定、一定能找到的，梅利达。

──应该去的地方。应该见的人。以及足以燃烧生命的命运。

有纪把左手伸到极限，然后在心中拼命对梅利达搭话。

最后──

梅利达翡翠色的眼睛像水面一样开始晃动。清澈的光芒变成水滴，潺潺从脸颊流下。

只有这部分跟宁静花园的颜色完全相同的眼泪无声流着，梅利达同时以沙哑的声音回答：

「…………真是伤脑筋…………听见这些话之后…………就没办法丢下你们两个人不管了啊…………」

穿着足袋的脚当场紧踩地面数次，最后像下定决心一样往前走。

一步、两步、三步……以缓慢但是决然的脚步来到两人面前的梅利达，举起双手后非常用力地握住兰的右手与有纪的左手。

「……真的是很小的圈圈。」

梅利达以笑中带泪的表情这么说道，有纪则是用尽全身的力量来回握她的手。

「但是跟只有我和姊姊围起来的圈圈相比，已经大了许多喔。」

脸上浮现笑容的同时，有纪双眼也溢出泪水。即使想擦拭也因为双手被握住而无法如愿，当她就像个孩子一样簌簌流着眼泪时，呈现七彩且扭曲的视界里，还是能看出梅利达脸上露出更加灿烂的笑容。

「啊哈……有纪，你的脸太夸张了。哭成这样的话，现实世界也会流眼泪喔。」

「没关系啦。因为我真的很高兴啊。」

原本拼命想靠着眨眼睛来甩开泪水，结果兰一瞬间放开有纪的手，以巫女服的袖子帮忙擦了她的脸。

「明明那么强了，怎么还是个爱哭鬼呢，小有。」

这么说道的姊姊脸颊上也有两行闪亮的液体。再次握住兰的手后，有纪就抬头看向天空。

刚才的老鹰已经不知道飞到哪里去了，至于天空还是那么美丽。她觉得这是一片连结了宁静花园与现实世界的天空。

走吧。让我们牵着手一起到天涯海角。为了将要到访的世界以及将要邂逅的人们。

有纪感觉自从小学五年级被迫转学之后，就一直关上的心门已经一点一点打开了。

不知道自己还剩下多少时间。但是，如果生命比别人短的话，只要比别人跑得更快、更大步就可以了。虽然现实世界里只能躺在床上，但虚拟世界是无限宽广。

「……差不多该回去了。」

这么说的是梅利达。像是要赶走有纪和兰的不安一般，最后又用力握了一下她们的手才放开。

「因为我跟妈妈说三点要回咖啡厅…………有纪、兰，难得的生日却被我做出这种事情搞砸了，真的很抱歉。」

梅利达正准备深深低下头来时，兰已经紧紧按住她的肩膀。

「不用道歉喔，梅利达。这是个非常、非常棒的生日。因为梅利达到这里来跟我们见面了。」

听见这句话的瞬间，有纪就大叫：

「我也……我也很开心！所以……所以梅利达，在外面的世界跟我碰面吧！」

对以惊讶表情回过头的兰点点头后，有纪就继续说道：

「那个，我因为一些原因必须住在无尘室。所以可以从隔壁的观察室透过玻璃见面……虽然不能握手，但是我想跟梅利达见面。」

因为对于Medicuboid有保密义务，就算是隔着玻璃，也不知道仓桥医师会不会允许会面。但是有预感仓桥医生应该会同意。因为怎么说今天都是她十四岁的生日。

「…………嗯！回到现实世界后就立刻去见你喔，有纪。」

迅速点头的梅利达，脸上已经感觉不到一丝脆弱的模样了。

8

「木绵季，可以了吗？」

听见从扩音器传出仓桥医生的声音，回答了一声「请吧！」后，分隔有纪所在的无尘室与隔壁观察室的瞬间调光玻璃就立刻变成透明。

几乎跟通道一样的狭窄房间里，可以看见不跟平常一样穿着无尘衣而是白袍的仓桥医生、穿着睡衣的兰，以及坐在轮椅上的一名宛若少年般的女孩子。

「……生日快乐，有纪！」

插图p307

首次在现实世界听见的梅利达的声音，只比虚拟世界稍微沙哑了一点。淡绿色毛帽下的脸相当瘦削，肌肤也是一片苍白。但是大大的眼睛带着强烈的光辉。

「谢谢……谢谢你，梅利达。」

虽然禁止触碰玻璃，但有纪还是尽可能把身体靠近并且这么回答。结果梅利达也推着轮椅前进了数十公分，在脸几乎快碰上厚厚调光玻璃的情况下露出微笑。

「兰和有纪都跟虚拟世界的你们好像……抱歉，虽然给你们带了花来，但是听说不能拿到那个房间里。」

如此说着的梅利达，膝盖上确实放着一束小小的花束。

「没关系啦，能够像这样看见我就很满足了！真的很漂亮……太谢谢你了，梅利达。」

有纪急忙道完谢后，梅利达就从花束底下伸出右手来靠到玻璃附近。她的手上似乎拿着什么小东西，有纪则一直把视线放在轻轻握住的拳头上。

「那个……有纪还有兰。我用一个约定来代替礼物吧。我……再也不会说想到那个世界去了。这个就当成证明。」

抬起左手的梅利达，从右手抓出一片薄薄的四角形物体──记忆卡。

有纪的眼睛清楚地看见标签上米粒大小的文字商标。

Sword Art Online。

闭着眼睛的梅利达嘴唇轻启。麦克风虽然没有收到声音，但有纪的耳朵确实听见「再见」的声音。

梅利达的手指用力，开始微微震动──最后记忆卡发出细微的「啪叽」声并且断成两半。

结果由警察厅订立的SAO事件受害者的NERvGear强制解除计划并没有实行。因为在计划的准备完成之前游戏就被完全攻略，大约有六千名生存者回归到现实世界。

那是有纪和兰的十四岁生日，以及公会「沉睡骑士」组成当天又过了约半年之后的事情。

（完）

** 后记

谢谢大家阅读Sword Art Online刀剑神域第22集〈Kiss and fly〉。

本书是继第8集〈Early and late〉以来的短篇集，收录了四篇作为动画的蓝光光碟＆DVD用特典小说的新故事。对于购买实体光碟的各位很不好意思，但因为是学生很难下手购买的价格，所以只选择发售后经过数年的故事作为文库本来出版。还请各位多多见谅！

稍微再提一下本书的标题。所谓「Kiss and fly（zone）」是欧美机场内送行车辆专用的停车区，似乎是「互相亲吻后起飞」的意思。当然本书里不会出现飞机与机场，但「Kiss」这个单字代表艾恩葛朗特内甜蜜的日子，「Fly」这个单字则是代表阿尔普海姆里令人雀跃的冒险，整体则代表着「下次见面之前短暂的别离」。

这次重新看原稿时，发现我竟然不是很讨厌创作短篇。基本上我很不擅长收尾，本篇的故事是一连串的「待续」「待续」。相对地，在三十到五十页稿纸内必须完成起承转合的短篇不知道为什么就能按照预定在篇幅内结束……说不定这是我把SAO的短篇当成「1任务」的缘故吧。那可能真的是游戏内的任务，也可能是现实世界里袭来的困难，不过我也重新体认到，描写挑战一个门槛并且加以克服的模样果然还是故事的基本。

今后桐人、亚丝娜他们以及身为作者的我和各位读者一定还会遇见无数的困难，但是只要不慌不忙地一个一个面对，就一定能够克服才对。在检查这篇后记的责任编辑先生面前应该也挡着出版日程表这道高墙，不过还是希望他能够顺利克服……！（可以听见「还不都是你害的」这样的吐嘈了……）

最后，本书是第22集的话，那么第21集〈Unital ring〉的后续怎么办呢？我想大家应该都会这么想吧，不过隔不了多久应该就会出版的第23集就会回到Unital ring的世界了。这一边也要请大家多多指教！

二○一九年九月某日    川原 砾