#+title: 刀剑神域 第十七卷 Alicization Awakening
#+setupfile: ./setup.setup
* 第十七卷 Alicization Awakening

** 第二十章 各自的战斗 西历二〇二六年七月七日/人界历三八〇年十一月七日

台版 转自 轻之国度

图源：linpop

录入：Naztar（LKID：wdr550）

修图：Naztar（LKID：wdr550）

1

上午五点。

位于VRMM「ALfheim Online」世界地图中央的中立都市阿鲁恩，其中央有一棵高耸入云的世界树，目前有超过三千名玩家聚集在世界树根部的巨蛋当中。

过去守护巨蛋顶端大门的有翼骑士怪物已经被撤除，这个地点目前是九个种族的精灵之间举行会议、交涉或者进行活动时的空间。

这时仅仅只有四名玩家面对突然被招集来参加大规模会议的三千人。

他们是大地精灵族的巨汉艾基尔、火精灵族的武士克莱因、猫妖族的驯兽师西莉卡、小矮妖族的铁匠莉兹贝特──也就是潜行到异世界「Underworld」后就陷入昏迷的「黑衣剑士」桐人的伙伴们。

当克莱因、莉兹贝特以及西莉卡等人在凌晨四点二十分传送讯息给所有朋友时，登入在ALO里的领主级玩家仅仅只有三个人而已。但是在拜托他们以及在他们手下负责某些职务的玩家，使出从现实世界与其他人联络的禁忌手段后，短短四十分钟就找来了如此多人数的玩家。

半球形的广大空间里，或站或飘浮的玩家当中，有将近三成左右是使用刚刚才创立的角色。但他们并非VRMMO的初学者。他们全是在使用The Seed规格的游戏当中的资深玩家，是应拥有ALO帐号的朋友要求而潜行来到这里。

也就是说，聚集在世界树巨蛋里的三千人是日本人VRMMO玩家里面精锐中的精锐，同时也是Top-down型AI「结衣」寄予一缕希望的，Underworld人界守备军能够得救的唯一战力。

一片寂静的巨蛋当中，小矮妖族的铁匠莉兹贝特藉由魔法增幅的声音响彻整个空间：

「──这绝对不是什么谎言或者玩笑！日本的某个研究机关，在国家的支援下创造了The Seed规格的虚拟世界『Underworld』，现在已经有数千名美国人玩家在不知情的情况下潜行到里面，准备把那个世界的居民全部杀光！」

莉兹贝特虽然对自己煽动国族主义的发言感到愧疚，但还是鞭策自己「现在已经到了必须利用这种手段的时刻」，然后继续大叫：

「生活在Underworld的居民都不只是一般的NPC！是根据我们所玩的许多VRMMO世界的档案所产生的真正人工智慧！Underworld的人们也跟我们一样有感情与灵魂！为了守护他们，拜托大家把力量借给我们！请把大家现在使用的游戏角色『转移』到Underworld！」

结束五分钟演讲的莉兹贝特，带著祈祷般的心情环视众玩家。

聚集在巨蛋里的妖精们脸上，全都浮现同样的困惑表情。也难怪他们会这样，在没有任何基础理解的情况下，听见这样的说明实在没办法明白整件事。莉兹贝特本身从结衣那里听到Underworld的构造以及居住在该处的「人工摇光」之后，现在也还有许多暧昧不明的部分。

从露出疑惑表情且产生骚动的人群当中，一条手臂优雅地举起。

往前走出来的是，高挑身材上包裹著绿色和风长大衣的风精灵族领主──朔夜。

「莉兹贝特，我不认为你和你的朋友会单纯因为恶搞而做出这种事情，最重要的是桐人已经有将近十天左右没有登入游戏，看来事情确实是非同小可。但是……」

朔夜总是流畅冷静的声音，这时因为困惑而摇晃著。

「……老实说，真的有点难以相信。和人类一样拥有灵魂的AI，想要夺走它的美军……这实在太没有真实感了……不对，直接登入你所说的Underworld，应该就能确认是否为实……不过你刚才说过，潜行到该处还有几个问题点对吧？可不可以先说明一下这些问题点？」

──终于到了这个瞬间。

莉兹贝特吸了一大口气，然后暂时闭上眼睛。

紧要关头到了。要是在这里失败，就没有人会去救援了吧。

莉兹贝特瞪大双眼，环视眼前的朔夜、其他领主以及无数的ALO玩家，并且以清晰的声音宣告：

「好的──Underworld的用途并非是普通的VRMMO游戏。所以在潜行时会发生几个问题。首先是Underworld不存在能操作的UI。也就是说，无法主动登出。」

巨蛋里的骚动一口气变大了。

无法主动登出。这句话不由得令人联想到过去曾经存在的死亡游戏「Sword Art Online刀剑神域」。现在包含ALO在内的所有The Seed规格的游戏，都是同时可藉由UI操作与语音指令来登出。

「登出的方法就只有在内部『死亡』。但是，这时候就会产生第二个问题。Underworld里……没有设定疼痛缓和装置。受到足以让HP归零的伤害时，应该会感觉到相当强烈的疼痛。」

听见莉兹贝特的话之后，玩家们的骚动又更加强烈了。

疼痛缓和装置也是现行VRMMO的必须机能。在不存在这种机能的虚拟世界里，要是被剑砍中或是被火焚烧，就会感受到与现实世界差不多强度的痛苦。有时候肉体的皮肤还会暂时发红。

但是，伴随潜行发生的问题还不只是这样而已。

等待骚动稍微止歇，莉兹贝特终于说出第三个，同时也是得付出的最大代价。

「──还有另一个问题。就是Underworld目前处于开发者也无法操作的状态。也就是说……无法保证各位转移的角色能不能再次转移回原来的游戏当中……根据情况，也有可能会发生丧失角色的结果。」

一瞬间的沉默之后──

广大的巨蛋空间里就充满了声量惊人的怒吼。

并排站在空间中央的莉兹贝特、克莱因、西莉卡、艾基尔四个人，以及变身成娇小导航妖精坐在克莱因肩膀上的结衣，就这样持续默默地承受著来自于四面八方的怒吼巨浪。

会出现这样的反应是意料当中的事。

三千名顶尖玩家为了培育自己的角色，不知道花了多少的时间与努力。以ALO来说，就算拚命砍杀怪物一个小时，也不知道能不能提升少少的一单位熟练度，而他们就是这样每天进行著宛如用水桶汲取湖水般的作业。

听见可能丧失呕心沥血锻炼出来的角色，他们怎么可能继续保持平静。

「别……别开玩笑了！」

从集团里冲出来的一名玩家，以食指指著莉兹贝特这么大叫。

那是穿著深红的全身铠甲，背上背著战斧的火精灵。他应该是地位仅次于领主蒙提法、将军尤金的指挥官。

火精灵掀起头盔的面甲，露出燃烧著怒火的双眼，接著用足以让背后庞大集团沉默下来的巨大声量继续说道：

「在这种时间找来一大堆人，还要人潜行到莫名其妙的伺服器，光是这样就很过分了，现在还说可能会失去角色？消失的话你们可以赔偿吗！还是说这是让整个种族弱化的陷阱？」

「…………呜！」

以左手制止脸色大变并准备吼回去的克莱因后，莉兹贝特尽可能以冷静的声音回答：

「抱歉，我们没办法补偿。我很了解你们培养起来的角色不是能用钱买到的东西。所以才会拜托你们帮帮我们……请救救我们目前在Underworld拚死抵抗美国攻击的伙伴吧。」

莉兹贝特的声音不用大叫也传遍巨蛋的每个角落。火精灵虽然一瞬间露出无法呼吸的表情，但立刻就又把情绪变成怒气并吐出来。

「你所说的伙伴，就是被称为SAO生还者的家伙对吧，他们总是露出『自己在VRMMO玩家当中也比较特别』的表情！我很清楚，你们这些前SAO玩家，在心里都瞧不起其他的玩家啦！」

这次换成莉兹贝特说不出话来了。

莉兹贝特至今为止从未感觉到火精灵所指责的这种心理。但是听他这么一说，似乎也无法断言绝对没有过这样的想法。根据地不是地上的都市而是在天空中的新生艾恩葛朗特，而且几乎不降落到地面，只和以前认识的玩家进行交流，这些都是不容否认的事实。

或许是看穿莉兹贝特的动摇了吧，火精灵毫不容情地继续说道：

「什么侵略、人工智慧、灵魂之类的又关我们什么事！别擅自把现实世界的事情带进VRMMO里！这种事情，光靠你们这群在现实世界也是了不起的生还者大人自己去处理就可以了吧！」

集团里面也有几个人像是要呼应火精灵的指责般，发出了「没错，滚回去」的骂声。

──不行了。

我的话完全无法打动他们。

莉兹贝特拚命忍著不露出眼眶含泪的模样，以寻求帮助的心情看著有私交的ALO原生实力者──风精灵族的领主朔夜、火精灵族的将军尤金、猫妖族的领主亚丽莎‧露等人的脸。

但是即使视线对上了，他们似乎也不打算说话。

他们只是用带著强烈光芒的眼睛持续凝视著莉兹贝特。简直就像在对她说「展现你的决心与觉悟吧」一样。

莉兹贝特大大地吸了口气，接著再次闭上眼睛。然后想著在遥远异世界拚死持续战斗的亚丝娜、受伤的桐人，以及先一步冲进Underworld的莉法与诗乃。

──以我的实力，就算转移了也无法像亚丝娜他们那样战斗。但一定还是有我能办到的事情。现在这个瞬间、这个地点就是我的战场。

莉兹贝特迅速睁开双眼甩开泪珠，接著再次开始说话：

「……没错，这确实是现实世界的事情。而且正如你所说的，SAO出身的人可能都容易把现实和虚拟混在一起。但是，那绝对不是因为我们自认是英雄。」

站在右侧的西莉卡眼睛浮现泪水，莉兹贝特握住她的手后继续表示：

「我和这个女孩子，就读的学校里全是你所说的生还者。被原本的学校当成是退学，所以我们根本没有选择的余地──生还者学校的学生，每个月一定要接受一次心理谘商。在戴著AmuSphere一边观察我们脑波的情况下，一边接受『是不是丧失现实感』、『会不会想伤害他人』等讨厌的问题。也有几个人在不愿意的情况下被迫服用药物。对于政府来说，我们全都是将来有可能变成犯罪者的监视对象。」

不知不觉间怒骂声已经止歇，巨蛋里笼罩著紧绷的寂静。就连眼前的火精灵也因为这出乎意料的发言而瞪大了眼睛。

莉兹贝特也不清楚有多少人能听进自己的话。她只是拚命地把溢出的感情、意志变换成言词。

「但是，其实不只有生还者学校的学生才受到这样的待遇。VRMMO的玩家或多或少都被人用有色的眼光注视著。被批评是对社会没有贡献的寄生虫、不缴税与国民年金的现实逃避者……甚至出现应该恢复征兵制，强制让他们贡献社会的议论。」

笼罩在巨蛋里的紧张感急遽升高。用针一刺的话，一定会爆发比刚才强烈数倍的怒气。

但是莉兹贝特依然把左手贴在胸口并继续大叫：

「不过我很清楚！而且我也相信！现实就在这个地方！」

离开胸口的手，指向世界树底部的巨蛋──以及后方的阿尔普海姆全土。

「这个世界，以及与这里连结的许多虚拟世界，绝对不是虚构的逃避地点！对我们来说，是存在真正的生活、朋友、邂逅、离别、笑容与眼泪的真实世界！大家应该都是这样吧？就是相信这个世界是另一个真实世界，才能如此努力吧？既然如此，要是被贬低为一般的游戏……只不过是虚拟的假货，那么我们的真实又在什么地方呢……！」

莉兹贝特的眼睛里终于流下泪水。莉兹贝特没有把它们擦掉，继续挤出最后的发言：

「……大家培育起来的许多世界，像这颗世界树般聚集起来，然后发芽，现在终于开花结果变成Underworld，我真的很想保护它！拜托你们……把力量借给我们吧！」

莉兹贝特把双手伸向巨蛋的天花板。

几千名精灵的翅膀上掉落下来的磷光，在她因为泪水而模糊的视界里闪闪发亮。

＊＊＊

银色光芒一边闪烁，一边在破晓的天空中划出大大的弧形。

一秒钟后，粗大的绳子就随著清脆的声音从中被切断，然后像黑蛇般在空中扭动。抓在上面的数十名敌兵，就在嘴里发出悲鸣的情况下跌落无底深渊。切断绳子的神器「双翼刃」以锐利的角度回转，回到主人整合骑士连利‧辛赛西斯‧推尼赛门手中。

黑暗领域军为了渡过峡谷所拉起的十条绳子当中，连利很快已经切断了五条，但他的脸上却没有任何骄傲或者成就感。反而对于必须割断受到无情命令而舍身横越峡谷的敌兵名符其实的救命绳而感到痛苦。

在连利身旁握住白马缰绳的亚丝娜也有同样的心情。

当亚丝娜和连利、整合骑士爱丽丝‧辛赛西斯‧萨提、整合骑士谢达‧辛赛西斯‧推鲁弗，以及骑士长贝尔库利‧辛赛西斯‧汪等五个人骑马奔驰到这里时，已经有数百名敌兵渡过峡谷，而他们为了保护剩下的绳子果敢地发动了攻击。虽然几乎都被实力在敌人之上的贝尔库利、谢达、爱丽丝等三个骑士砍倒，但还是有几个人从侧面攻击连利，让亚丝娜为了保护他而不得不挥动细剑。

虚拟世界「Underworld」是以The Seed program为基盘，所以可以直接使用在SAO时期学会的剑技与骑马技术。

此外使用超级帐号「创世神史提西亚」的亚丝娜，各项数值几乎都到达上限，而且装备的细剑「灿烂之光」也被赋予超越众整合骑士神器的性能，就连基本技「线性攻击」都能一击就轻易贯穿敌人暗黑骑士的厚重铠甲以及拳斗士的强壮肉体。

但是敌人士兵从伤口迸发出来的鲜血、充满怨叹的悲鸣，以及失去的性命全都是真货。

生活在Underworld的人们，不论是人界人还是暗黑界人，都跟亚丝娜一样拥有本质完全相同的灵魂──也就是摇光。对手明明是真正的人类，但是自己却藉由游戏里才会出现的身体数值与武器性能的加持，一击就把他们杀掉，这样的事实给亚丝娜的心带来难以承受的疼痛与不对劲的感觉。

而且脸上带著悲壮决心不断扑过来的暗黑骑士与拳斗士，绝对不是因为自己的意志而做出这样的行动。

他们这些人工摇光，拥有绝对无法抗拒上位者命令的性质。被和亚丝娜一样使用超级帐号「暗神贝库达」登入的现实世界人命令，即使知道是无谓的牺牲还是进行攻击。从另一个角度来看，他们也是被卷进现实世界科技争夺战的受害者。

但是亚丝娜还是用尽所有的精神力把这样的想法赶到意识之外。

目前最重要的是保护贝库达追求的「光之巫女」爱丽丝──以及位在后方野营地的桐人。

听说在敌将贝库达指挥之下的黑暗领域军，战力就只剩下这个拳斗士公会与暗黑骑士团而已。只要反过来利用对方鲁莽的峡谷横越作战来消耗敌人的兵力，贝库达应该就无计可施了。

「──好，砍断第六根吧！」

骑士长贝尔库利强而有力的声音打断了亚丝娜的思绪。比即刻回答的爱丽丝、谢达、连利晚了一会儿，亚丝娜也回叫了一声「好的！」。

当她转过马首准备往西方移动时，后方的角笛就高声响彻整座战场。

回头一看，就看到了人界守备军诱饵部队的卫士们排著整齐队形从距离一公里左右的山丘上往下冲。大概比骑士们晚了十五分钟左右就完成武装与编队，从野营地发动了攻击。

「真是的……那些家伙就不能乖乖待著吗？」

贝尔库利虽然以苦涩的表情看著那群卫士，但渡过峡谷的敌兵数量已经到达五百名左右，在这个时间点出现援军还是让人感到心情轻松多了。只要卫士们帮忙牵制敌兵，要切断剩下来的五条绳子就不会太辛苦。

──贝库达先生，看来这场战争是我们赢了。

当这句呢喃尚未从亚丝娜心中消失时。

她的双眼就看见了奇妙的现象。

有不可思议的东西从因为朝霞而染上血一般颜色的天空降下。

那是比天空还要光亮的红线。而且不只一条。数量有数十……数百。

不对，是数千吗？

无数的线条各自像是由细微的圆点所组成。拚命凝眼观看，就能知道每个圆点都是数字或者英文字母。

身份不明的文字列集团无声地降到峡谷这一侧，距离战场东方一两公里的地方。

曾几何时，不只是亚丝娜，就连其他整合骑士，甚至是黑暗领域的暗黑骑士与拳斗士都停下脚步专心地看著那种奇妙的现象。

第一条刺进干燥地面的红线，变成不规则的形状并且开始蠢动──

短短几秒钟的时间，那红色物体就变成人形。

＊＊＊

拳斗士团长伊斯卡恩一瞬间忘记了在内心奔腾的愤怒。

──那是什么？

峡谷的对岸，好不容易爬过绳子的五百名黑暗领域士兵正果敢地准备朝五名整合骑士进攻。

但是他们却突然停止动作，以惊讶的表情看著战场外面。

被他们吸引而移动脸庞的伊斯卡恩，看见的是降到距离他们东方两基洛尔处的深红雨滴。

无数的红线一边发出奇妙的震动声一边从天而降。

这些红线在和地面接触的瞬间就开始膨胀，然后转眼间变成人类的模样。

出现的是全身穿著暗红色铠甲，手拿长剑、战斧或者长枪等武器的士兵。

先不管颜色，他们铠甲的形状与暗黑骑士团十分相似。一开始的想法是，皇帝贝库达以神力送来援军了吗？

但下一刻就有难以言喻的不对劲感袭上伊斯卡恩心头。

红色士兵们毫无规律与统御的站姿，实在不像受到亡故的暗黑将军夏斯达锻炼的骑士团成员。他们有的大动作地和身边的士兵说话，有的直接坐在地上，有的甚至没有接到命令就拔出武器来挥舞。

最重要的是他们的数量。

奇妙的红雨终于止歇时，出现在大地上的士兵集团，已经膨胀到让人有点不敢相信的规模。大略看一下也轻松超过一两万……甚至可能到达三万人。如果暗黑骑士团有这样的预备兵力，十侯会议应该早就徒具形式，夏斯达也早就成为暗黑界的实质支配者了。

而且在峡谷这一边等待渡过绳子的暗黑骑士之间也发出了惊讶的声音。他们也不清楚那个军团的身份。

这样的话，那些红色士兵果然是皇帝兼暗神的贝库达利用秘术从地底或者什么地方召唤出来的真正「暗之军队」吧。

认识到这一点的下一刻，伊斯卡恩的惊讶就转变为深刻的愤怒。

能够召唤这种大军的话──

为什么不早一点实行。这样的话，因为鲁莽横越作战而丧命的拳斗士与暗黑骑士，看起来不就只是为了把敌人从营地里引诱出来的诱饵吗？

不对──或许真的是这样。

皇帝只是为了吸引能让自身军团打倒的敌人，就命令我们进行那种根本是自杀一般的横渡作战吗？

…………不对。

不只是这次的作战。从对「东大门」发动攻击开始，暗黑界军的被害就太过严重了。即使哥布林队、巨人队、食人鬼队以及半兽人队与暗黑术师公会队都几乎全灭，皇帝别说是哀悼他们的死亡了，甚至连表情都没有改变过。

这也就表示，对于皇帝贝库达来说，多达五万的暗黑军打从一开始就只是弃子罢了。

年轻拳斗士团长伊斯卡恩，是一名至今为止只对锻炼肉体、提升技能以及发展自身部族有兴趣的年轻人。

现在这个瞬间，他首次得到俯瞰的视点，得以纵观包含自己所属的暗黑界与人界在内的地底世界全体。这样的见地，在他心中产生了不可能解决的矛盾。

皇帝贝库达是绝对的强者。自己绝对得遵从强者。

但是。

但是──

「呜……！」

右眼产生前所未见的剧痛，伊斯卡恩用手掌盖住右侧脸部并发出呻吟。

脚步踉跄，膝盖跪地的拳斗士团长视线前方，多达三万人的深红军队一边嚷著未曾听过的语言一边开始跑动。

他们前进的方向，从峡谷南侧下来的约一千名人界守备军士兵正摆出与整合骑士会合并且开始迎击的态势。

而两者中间的五百名拳斗士与暗黑骑士，则是以不知道该如何行动的模样呆立在现场。

就算皇帝贝库达再怎么冷血，这下子那五百人的性命应该能得救了。

伊斯卡恩用力压著右眼，在意识的角落这么想著。

但是他到了这个时候，还是错估了贝库达的冷酷程度。

皇帝召唤的三万名军队率先袭击的不是人界军，而是那仅仅五百名的暗黑界军。

无数的剑、斧头、枪在红色朝阳下发出闪亮光芒──

随著渴望鲜血的叫声，对著应该是伙伴的拳斗士与暗黑骑士们挥下。

＊＊＊

「那……那群家伙是什么人？」

亚丝娜不知道该如何回答骑士长贝尔库利惊讶的声音。

突然从战场东侧降下……不对，是潜行过来的三万名士兵，很明显是皇帝贝库达呼唤过来的军队。

但他到底是从什么地方找来如此多的战力？

是生成作为怪物的NPC士兵并投入战场吗？但是O Turtle主控室里的操纵台已经被锁上，不可能用管理者权限来直接操作了。最多就只能像亚丝娜这样，指定座标后自己潜行到这里来而已，而贝库达那一边能使用的「Soul translator」就只有两台。

一瞬间袭击亚丝娜的混乱──

被逼进到数百公尺前方的红色士兵吼叫声给融化了。

「Charge ahead！」

「Give"em hell！」

──英文！

他们是现实世界的人类，而且从发音听起来是以美国人为主的集团。但为什么会有这种事。这里应该是隐蔽的封闭式VR世界才对。

不对。

不对──

Underworld对于经由STL的潜行者来说，是比现实世界更加真实的，名为「泛用视觉化记忆」的真正异世界。但是它在开发时使用了泛用VRMMO程式套件The Seed。也就是说，只要有AmuSpher就可以潜行到这个世界……而O Turtle里具备大容量的卫星线路。

这样的话，就只要临时抱佛脚做出用户端程式，然后在现实世界散播出去。

就能够呼唤数万甚至是数十万的军队到Underworld来了。

红色士兵的行动，证实了感到愕然的亚丝娜所做出的推测。他们率先袭击了应该是友军的暗黑界骑士与拳斗士，毫不犹豫地对他们挥下剑与斧头。

「做……做什么……！」

「你们不是同伴吗……？」

骑士们虽然一边发出惊愕的声音一边抵挡攻击，但是数量的差距实在太大了。尤其是红色士兵们的武器与铠甲性能似乎高于暗黑界军，所以他们高举的剑与盾牌不断被折断、击碎。两军发生冲突的地点立刻开始迸发出悲鸣与鲜血。

「Dude, that"s awesome！」

「Pretty gore！」

感到兴奋而大叫的现实世界人，应该不知道这场战争的真实情形──恐怕认为只是VRMMO游戏的封测而潜行到这里来的吧。

那些美国人玩家对于Underworld人不可能有什么敌意。因为他们相信眼前的暗黑界人只不过是目标NPC。只要花时间跟他们说明Underworld以及人工摇光的实情，应该有一大半的人会愿意登出才对。

但是现在没有这样的时间。即使亚丝娜冲到战场上试著用英文说服他们，大概也只是会被当成NPC在大叫被设定好的台词吧。如果听见正式营运之后将根据打倒目标获得的点数赠送稀有道具的说明，就算是日本人玩家也一定会做出同样的行为。

现在已经无法用言语来说服他们了。

美国人想杀害的不是NPC，而是拥有真正灵魂的人工摇光。杀光暗黑界军之后，接下来就会对人界军诱饵部队发动攻击吧。这样的话，现场唯一拥有虚构生命的自己更应该要战斗。

如此下定决心的亚丝娜，把右手的细剑往上举起，然后迅速咏唱咒文。

「System call！Create field object！」

细剑上带著七彩极光。

不能和昨天晚上一样创造出无底的峡谷。这样会断了人界军的退路。

相对地，亚丝娜一边想著如枪一般锐利的巨岩一边猛烈把剑挥下。

「啦────────」一声庄重的效果音响彻现场。七彩光芒从剑尖射出，刺进美国人与暗黑界人冲突点稍微往前一点的地方。

地面突然开始震动，接著是灰色岩石往上抬头。它立刻上升了将近三十公尺，把待在那里的红色士兵们高高地弹飞。

接著又一口气升起四座岩山。大地晃动当中，数百名红色铠甲的士兵飞上空中。在尖锐的咒骂声之下，他们有的被岩石压扁，有的猛烈撞上地面而喷洒出大量的血肉。

亚丝娜没有多余的心思去推测他们是如何感受自己的死亡。

因为忽然有一道灼热的剧痛贯穿她的脑袋中心，让她整个人倒到马背上。

银色火花在视界里爆散，无法呼吸的她开始喘息。痛楚比昨天晚上在地面制造峡谷时要强烈多了。切身感觉到在庞大的地形档案流经的过程中，灵魂……摇光不断地损耗。

──但是，自己不能在这里倒下。

如果这样能够受到和桐人一样的伤害也算了了心愿。亚丝娜心里一边这么想著，一边咬紧牙根从马鞍上撑起上半身。

从战场东侧推进的美国人玩家，来势似乎因此稍微受到顿挫。但是五座并排的岩山宽度最多只有五百公尺。数万名玩家应该会立刻从两侧迂回过来吧。

再次在南侧制造岩山墙，让人界军从内侧脱离现场吧。

在反覆著急促呼吸的情况下，亚丝娜再次准备高举起手里的剑，这个时候──

发出金色光辉的护手确实地按住了她的右臂。

「……爱丽丝……！」

她以沙哑的声音叫著黄金骑士的名字。

姣好容貌上露出坚定决心的整合骑士爱丽丝，这时迅速摇了摇头说：

「别太勉强了，亚丝娜。再来就交给我们整合骑士吧。」

「但……但是，那些红色士兵，是现实世界……是从我们的世界而来的敌人……！」

「……就算是这样，盲目追求鲜血并且胡乱挥剑的家伙，不论来几万人都不足为惧。」

「没错。也让我们有些表现的机会吧。」

骑士长贝尔库利在爱丽丝的发言之后发出豪爽的笑声。

在这样的状况中还能保持轻松心情的骑士们确实相当有胆量，但亚丝娜也从他们的表情察觉出比之前更加强烈的觉悟。

成为红色海啸排山倒海而来的敌人，数量是人界军的三十倍。这已经不是靠气魄就能解决的阶段了。

但是，骑士长高举磨得晶亮的长剑后，就发出强韧的声音：

「好吧！全军，采取密集阵型！要以单点突破来突围喽！」

＊＊＊

「喔……喔，喔……」

从伊斯卡恩嘴里发出来的不是人类的言语。

「喔……喔喔喔喔喔喔喔喔喔──！」

从他用尽所有力气紧握的双拳不停滴下血来。但是年轻斗士却不觉得疼痛，只是持续发出野兽般的咆哮。随侍在侧的副官达巴也像是能够理解伊斯卡恩的苦恼般深深低著头。

死去，不断地死去。

没有接到命令，甚至无法战斗的同族斗士们，不断成为胡乱挥落的刀刃底下的亡魂。

但是剩下来的五条粗绳上，横渡峡谷的士兵们依然没有停止动作。因为皇帝「到对岸去」的命令依然有效。接受绝对上位者命令的他们拚命爬过绳子，但是之后就被红色军队包围，然后残酷地砍杀。

为什么皇帝贝库达不中止拳斗士和暗黑骑士的横渡作战，并且命令红色士兵停止攻击暗黑界军呢？

这样下去，部族的斗士们不过只是诱饵。

只不过是献给召唤过来的军队的活祭品吗？

「必……必须跟皇帝……」

必须跟皇帝禀报才行。必须请求他中止这次的作战。

在愤怒、绝望以及右眼产生的剧痛煎熬之下，伊斯卡恩为了迈向最后方的地龙战车而走了一步。了解族长意图的达巴抬起扭曲的脸来似乎想说些什么。

就在这个瞬间──

一道巨大的影子横越上空。伊斯卡恩与达巴反射性抬头望向天空。

──飞龙。

而乘坐在龙背上的是身披奢华毛皮披风，金色长发随风飘逸的皇帝贝库达本人。

「啊……啊啊……！」

可能是听见伊斯卡恩无意识中发出的叫声了吧，皇帝从飞龙的鞍上稍微往地面瞄了一眼。

他的眼睛里没有任何感情。那冷落冰霜的一瞥，对于呆呆死去的暗黑界士兵们没有一丝的怜悯，甚至可以说没有任何兴趣。

皇帝贝库达把视线从伊斯卡恩身上移开后，就直接让龙飞翔到峡谷的另一边。

那就是神。那正是所谓的支配者。

但是，如果身为支配者。如果是力量无人可及的绝对强者。

就应该负起与能力相对应的责任吧。

统率军队、领导人民，为国家带来更大的繁荣。这应该是支配者的责任。平白拋弃几千几万条性命，还对这一切没有任何的感觉，这样的人竟然敢自称是皇帝……右眼……敢自称是支配者……右眼好痛……他有什么资格…………！

「呜……喔……喔喔喔啊啊啊啊啊啊！」

伊斯卡恩高高举起右拳。

然后把指尖弯曲成钩爪状。

接著毫不犹豫地刺进妨碍思考的剧痛源头，也就是自己的右眼。

「族……族长！你做什么！」

以左手制止飞奔过来的达巴，年轻斗士随著简短的尖叫一口气把右眼球挖出来。白色球体虽然不断在拳头里发出红光，但是被捏碎的同时光芒也就消失了。

这个时间点，伊斯卡恩并不像爱丽丝和尤吉欧那样，达到主动解除右眼封印，也就是「Code871」的境界。

因此他还是无法形成直接反叛皇帝的意识，没办法废弃目前被赋予的「继续横渡峡谷作战」与「自己不能爬过绳子」的两个指示。

但是年轻拳斗士在几乎与反叛皇帝无异的情况下，强行挤出了回避皇帝命令的手段。

伊斯卡恩缓缓回头，低声对以哑然表情低头看著自己的达巴说：

「关于那些红色士兵，皇帝没对我们做出任何指示对吧？」

「是……关于这一点，确实是如此。」

「那么，就算我们痛宰他们，也跟皇帝一点关系都没有吧。」

「…………冠军…………」

以左眼狠狠瞪了说不出话来的达巴一眼后，伊斯卡恩就做出这样的命令：

「听好了……峡谷上一架上桥，就全军展开突击。无论如何都要解救对岸的伙伴。」

「什么……？到……到底要如何架桥……」

「这还用问吗？我会去拜托办得到的家伙。」

静静地丢出这句话后，伊斯卡恩重新转向峡谷。

他强壮的双脚突然包裹在鲜红的火焰当中。

拳斗士一边留下熏黑的足迹，一边猛然朝著峡谷跑去。

──不能爬过绳子的话……直接用脚飞越就可以了吧！

在胸中如此大叫完，伊斯卡恩就在宽一百梅尔的深渊前用力往地面踢去。

跳跃是拳斗士重要的锻炼之一。

修行是从沙地安全的跳跃开始，最后藉由飞越并排的刀刃以及滚烫的油来强化对自己跳跃力的自信，也就是形成「心念」。

如果是一流的拳斗士，最后将获得达到二十梅尔的跳跃力。在这个禁止用术式飞行的世界里，这已经是肉体跳跃距离的上限了。

但是现在伊斯卡恩投身的目标，是宽度比距离上限多出五倍的无底峡谷。

在空中拖著长长火焰尾巴的拳斗士只是一直瞪著前方，然后用双脚踢著空气。

十梅尔、二十梅尔。身体还在继续往上升。

三十梅尔、三十五梅尔。乘著从峡谷底下吹上来的强风，像是有看不见的翅膀从后面推进一样继续往高处爬。

四十梅尔。

再一点──再往前一点点的话……就能从该处利用惯性到达对岸了。

但是──

差一点就要到达峡谷正中央的时候，风无情地停了下来。

身体骤然失去势头。跳跃的轨道到达顶点，开始进入往下的曲线。

──还差了五梅尔。

「唔喔……喔喔喔！」

伊斯卡恩大叫，像是要抓住什么般伸直右手。但是当然不可能有什么能让手脚施力的地方，只有从脚底下的黑暗往上爬的寒气抚摸著他的身体。

这个剎那──

「冠军啊啊啊啊啊──！」

如雷般的吼叫声击打著伊斯卡恩的耳朵。

稍微往后方一看，就发现副官达巴以右臂抓住比自己头部大好几倍的巨岩，目前已进入投掷态势。

族长立刻了解长年随侍在侧的忠实部下有什么企图。但是，人族无法把那么巨大的岩石丢超过五十梅尔以上的距离……

达巴的右臂「咕哇」一声膨胀了起来。像是把全身的力量都集中在该处一样，肌肉整个隆起，血管也浮了上来。

「喔喔喔喔！」

巨汉发出吼叫，助跑了几步之后，将自己的右臂挥尽。

岩块就像被投石器丢出去般震动著空气──下一刻，达巴的右臂立刻撒出鲜血与肉片，整个爆散了开来。

把副官重重往前扑倒的模样烙印在左眼当中，伊斯卡恩咬紧牙根，只把意识集中在一直线朝自己飞来的岩石上。

「……啦啊啊啊啊！」

左脚脚掌随著吼叫声用力把岩石踢飞。

岩石「磅喀──！」一声四散，伊斯卡恩的身体藉由反作用力，像被弹开来一样再次加速。对岸那些剑士的身影已经在眼前了。

＊＊＊

「Damn！」

把细剑从发出简短骂声后重重倒下的美国人玩家身上抽出来，马匹上的亚丝娜开始急促地呼吸著。

不像面对暗黑界人时那样，夺走性命会有沉重的心理压力。成为过去「闪光」或者「狂暴补师」绰号由来的高速连续剑技，已经击倒超过十名以上的红色士兵。

但是敌人的数量实在太多了。

不只是亚丝娜，人界军的卫士们，尤其是四名整合骑士战斗的模样已经足以比拟鬼神。他们站在组成密集阵型的卫士前面，为了往南方开出一条血路而杀得积尸成山。

但还是无法把绕过亚丝娜创造出来的岩山后不断涌过来的士兵逼回去，最多只能停下脚步互相抗拮。

不久后他们应该会发现，被砍倒的敌人尸骸数十秒后就消失得无影无踪，现场甚至不留下一滴血迹的事实。同时也会发现自己面对的是没有性命的幻影军队。

「呜哇……不行了……呜哇啊啊啊──！」

背后突然传来的尖叫让亚丝娜猛然回过头去。

结果看见卫士们的防卫线有一部分被攻破，红色士兵从该处涌入。

红色士兵一边嚷著粗口一边对卫士们发动攻击，把人包围起来后就出手砍杀。现场血肉飞溅，悲鸣也变成临死前的尖叫。

过于真实的死亡模样似乎更加刺激了红色士兵的欲望，他们立刻就聚集到下一个目标身边。

「住手……住手啊……！」

亚丝娜大叫。

现在是无视少数牺牲者，专心往南方突进的时刻。虽然理性很清楚这一点，身体却擅自从马背上跳下来。

「住手啊啊啊啊啊啊！」

亚丝娜宛如要将喉咙喊破般大叫著，独自往涌至的红色奔流前端砍杀过去。

美国人玩家没有恶意。只不过是被袭击者利用──这样的理解也被如同骇浪般沸腾的感情给掩盖过去了。

滋喀喀喀！

右手一闪，「灿烂之光」就连续贯穿红色头盔的面甲。头部遭到致命一击的四个人，手上的剑直接掉落，然后一边发出呻吟一边倒了下去。

从这个反应就知道，利用AmuSphere潜行到这里的他们，明显没有受到疼痛缓和装置的保护。早就察觉这一点的亚丝娜，至今为止都尽量一击破坏对方的心脏，让对方立刻登出游戏，但这样的理性也在不知不觉间消失了。

最高优先度的细剑在空间中纵横，直接贯穿、撕裂铠甲，有时候也连同敌剑一起砍断。

美国人眼里所见的全都是多边形组成的身体以及伤害特效的血液。但是对以STL潜行的亚丝娜来说，他们也是活生生的人类，飞溅到自己身上的是温热血液，而且带有令人反胃的铁锈味。

这时亚丝娜的右脚因为不知道什么时候累积在地面的血滩而一滑。

无法保持身体平衡而跌倒的亚丝娜眼前，出现一名高大的战士。

「Take this！」

亚丝娜往右滚动来躲开猛然往下挥落的战斧斧刃。

但还是无法完全避开，左臂被厚厚的斧刃砍中。

喀滋。

随著钝重的声音，左臂手肘以下的部分被砍断并飞上天空。

「呜……啊…………！」

猛烈的剧痛让视界一点一点反白。亚丝娜停止呼吸，全身紧绷。

她抱住血流如注的左臂不停地喘息。无法抑止的眼泪后方，可以看见围住自己并且举起武器的四五个人。

突然间──

拿著战斧的大汉头部像是爆炸般飞散开来。

钝重的打击声持续响起。想给亚丝娜最后一击的步兵们身体接连粉碎，然后消失在视界当中。

「嘿……一群没用的家伙。」

承受著剧痛，好不容易撑起身体的亚丝娜，看见的是一名有著精悍容貌与火焰般红发以及浅黑色肌肤的强壮年轻人。

──是黑暗领域人！

一瞬间忘记痛楚的亚丝娜用力吸了一口气。肌肤的颜色、只绑著皮带的上半身，这无疑是到刚才为止都还在交战的暗黑界拳斗士。

但是，为什么应该在贝库达支配下的人，会攻击同样被贝库达召唤过来的红色士兵呢？简直就像要帮助亚丝娜一样。

往下看的拳斗士只有一只眼睛。右眼残留著就像直接被刨开来般的惨烈伤痕，脸颊上还有一缕已经干掉的红黑色血痕。

年轻人以独眼狠狠瞪了再次想进逼的众美国人一眼，然后高高举起右拳。

骨节突出的拳头上包著鲜红火焰。

「呜……啦啊啊啊啊！」

拳头随著撕裂绵帛的吼叫声往地面轰去。

随著「咕哇」一声出现火焰壁般的半圆形冲击波，毫不费力就把前方的士兵全都轰飞。

──好强大的威力！

亚丝娜不禁瞠目结舌。现在战斗的话，自己会输……

但是拳斗士默默地伸出手臂抓住亚丝娜的铠甲。强行让她站起来后，左眼就在近处凝视著她。

「……来交易吧。」

亚丝娜无法立刻理解年轻，但是带著深刻苦恼的声音所说的话究竟是什么意思。

「交……交易？」

「没错。那些岩山还有巨大的裂痕是你创造出来的吧？听好了……就算狭窄也没关系，在后面的裂痕上架一条稳固的桥。这样的话，在把那群红色士兵全部摧毁之前，四千名拳斗士都会和你们一起战斗。」

一起战斗──黑暗领域军吗？

真的可能发生这种事吗？暗黑界人，不对，这个世界的人类，应该会因为右眼的封印──Code871而无法反抗上位者的命令才对。

亚丝娜一边这么想，一边再次把视线朝向拳斗士右眼的伤痕。

那道伤痕是他自行解除右眼封印的痕迹吗？他也像爱丽丝一样进化成突破界限的摇光了吗？

但是爱丽丝昨天晚上说过，持续抗拒Code871的话，「右眼本身会爆裂且消失得无影无踪」。另一方面，拳斗士的伤痕与其说是从右眼内部破裂，看起来比较像是用手硬是把眼球挖出来一样。应该如何思考──判断这个年轻人所说的话才好呢？

亚丝娜感到犹豫时，耳朵就听见即使在这种极限状态中依然极度冷静的声音。

「那个人应该不会说谎。」

一边用极为纤细且相当有弹性的漆黑剑随手把红色士兵的头砍掉，一边做出这种发言的，正是灰色的整合骑士谢达‧辛赛西斯‧推鲁弗。

看向谢达的拳斗士，咧嘴露出充满自信──但是又带著点害羞的笑容，并且回应了一声「嗯」。

这个瞬间，亚丝娜就做出了决定。

──相信他吧。

这大概是最后一次使用史提西亚帐号的地形操作能力了吧。这样的话，不单纯把这股力量用在破坏上，拿来生成某些事物似乎也是不错的选择。

「……我知道了。我会在峡谷上架桥。」

右手离开被砍断的左手后，亚丝娜就朝天空高高举起珍珠色的细剑。

啦────

庄重的天使和声响彻现场，七彩极光降到荒野上。

光芒一直线往北突进，直到峡谷的对岸为止。接著是震耳欲聋的地鸣，大地开始震动。

悬崖两侧突然有岩柱突出。这些岩柱水平地延伸，在峡谷中央结合起来后，变成一座粗壮的桥。

「呜呜呜呜呜呜呜、啦啊啊啊啊啊啊啊！」

四千名拳斗士们发出的吼叫声以数倍声量盖过伴随地形变化出现的地鸣。

在独臂巨汉率领之下，精壮的斗士们争先恐后地开始急奔。

行使神力的代价朝著亚丝娜袭来，虽然一瞬间像要因为被灼热长枪贯穿脑袋般的头痛而昏过去，但亚丝娜最后还是重新握好细剑。

这时已经看不见应该站在人界守备军最前方打开一条血路的爱丽丝身影。现在只能相信她平安无事……以及拳斗士们真的会如红发年轻人所说的那样和守备军一起战斗，然后持续对抗红色士兵了。

──桐人，我现在就过去。

在心中呼唤著心爱的人后，疼痛就稍微缓和了。

＊＊＊

大约一分钟前。

整合骑士爱丽丝已经不清楚自己究竟砍了多少前仆后继涌过来的红色士兵。

──这些家伙……根本是异常。

完全没有身为军队的纪律，嘴里叫唤著从未听过的言语，并且踢开同伴的尸骸不断地冲过来。简直就像完全不顾伙伴甚至是自己的生死一样。

如果这就是现实世界的人类。

那么的确就如亚丝娜所说的，外面绝对不是什么神的国度。

面对永无止尽的杀戮以及不停出现的敌人，就连爱丽丝的思绪也在不知不觉间变得迟钝了。

──够了。这根本不是战争。

希望早点冲散敌人的战线，从包围当中脱身。

「让开……给我让开啊啊啊！」

尖锐地这么叫完，就以金木樨之剑横扫而出。

敌人的脑袋与手臂接连飞上天空。

「System call！」

爱丽丝立刻咏唱神圣术的起句，生成十个热素。接著又用术式把它们融合成细长状，在左手上创造出火焰长枪。

「Discharge！」

轰隆隆！

虽然不及迪索尔巴德的火焰炽焰弓，但灼热的火线还是笔直地贯穿敌军，轰飞将近十个人后在包围线上开出一个洞。

洞的后方──

看见了。黑色大地以及隆起的山丘。

一口气跑到那座山丘，使用能把从这鲜血淋漓的战场散发出来的庞大空间神圣力全部用尽的「反射凝聚光线」术式，一口气把红色步兵全部烧毁。

「让开啊啊啊啊！」

爱丽丝一边从喉咙迸出吼叫声，一边朝地面踢去。

「……大小姐！」

背后的骑士长贝尔库利发出尖锐的叫声。

但是接下来的一句「别莽撞」已经无法传到爱丽丝耳朵里了。

──快穿过去了。再一会儿就能突破人墙。

在没有停下脚步的情况下砍倒出现在前方的最后一个人，爱丽丝终于穿过敌人似乎永无止尽的包围网来到无人的荒野。

将酷使的爱剑收进剑鞘里，用力吸满不带鲜血味道的空气之后，她便全力奔驰了起来。

忽然间，周围变暗了。

一瞬间以为朝阳被云遮住。

下一刻，一阵猛烈的冲击打中爱丽丝的背部。当她注意到自己被紧急降落的飞龙从后面用脚抓住时，双脚的脚尖已经离开地面了。

爱丽丝立刻举起金木樨之剑，准备发动武装完全支配术。

但在她咏唱式句之前，视界就先变暗，接著全身被足以把人冻僵般的寒气包围住。飞龙的骑手使用暗黑术──不对，不是这样。爱丽丝的意识本身被吸进无底深渊般的黑暗当中。

这是敌人的心念。和骑士长贝尔库利经过淬炼的钢铁般强韧心念，以及最高司祭亚多米尼史特蕾达烧尽万物的雷击般炽烈心念完全不同，那是能吞噬、捕捉一切事物的虚无心念……

浮现这样的念头之后，爱丽丝的意识就中断了。

＊＊＊

对于皇帝贝库达，也就是加百列‧米勒来说，这个局面完全是一场赌博。

但他还是确信只要让潜行到战场的数万美国人玩家包围人界守备军，「光之巫女」爱丽丝一定会为了再次使用那种大规模的雷射攻击，而单独或者带著少数人离开守备军。

加百列跨上暗黑骑士团准备的黑色飞龙，一边在战场的遥远高空盘旋，一边持续等待著。这是潜行到Underworld之后，感觉最为漫长的一段时间。

但是终于有一道小小的黄金光芒穿过行军蚁群体般的包围网，开始朝著南边的丘陵地带移动。

「爱丽丝……爱丽西亚。」

加百列脸上浮现以他来说相当罕见的真心笑容，并这么呢喃著。

他甩了一下缰绳，命令飞龙下降。

加百列那虚无却又拥有压倒性强度的想像力，也就是心念，已经完全侵蚀高傲飞龙的AI，所以能够随心所欲地操纵它。飞龙叠起翅膀像箭一样紧急下降后，右腿的钩爪就一把抓住急奔的黄金骑士背部。

飞龙随即展开双翼并叫了一声，然后再次往高空飞去。

加百列的意识连一秒钟都没有朝向自己造成的惨烈战场。对他来说，黑暗领域军、人界守备军以及召唤过来的现实世界人都已经不关他的事了。

再来就只要专心朝南边距离目前所在位置最近的系统操纵台──「世界尽头的祭坛」飞翔就可以了。从该处把爱丽丝的灵魂排出到现实世界，然后自己也跟著登出。

稍微把视线往下移，就看到被飞龙的脚捕获而丧失意识的爱丽丝那随风飘扬的金发。

真想早点触碰她。真想尽情地享受她的身体与灵魂。

到系统操纵台的路途相当漫长。就算是飞龙个体的移动力都得花上数天吧。就趁著这段时间，享受爱丽丝还具备Underworld肉体的模样也算别有一番乐趣。

加百列感觉甜美的冲动爬上背肌，嘴唇也再次上扬。

＊＊＊

没想到──

会为了掠夺一名少女这个目的，就把五万黑暗领域军以及新召唤的三万名步兵全都浪费掉。

身为整合骑士团首领，同时是最长寿人界人的贝尔库利‧辛赛西斯‧汪，从感觉到皇帝贝库达虚无心念的那个瞬间开始，就认为自己一直著保持最大限度的警戒。但是结果就是爱丽丝整个人被绑走了，才知道自己完全没有看出贝库达的企图。

爱丽丝在距离数十梅尔远的地方被黑色飞龙的钩爪抓住的瞬间，贝尔库利就做出连自己也不知道究竟隔了多少年未曾出现的行动。

他从丹田发出真正的愤怒声：

「你这家伙，想对我的弟子做什么！」

空气倏然为之一震，周围甚至爆出白色电光。

但是捕获爱丽丝的皇帝贝库达却连头也不回，直接一直线往南方的天空上升而去。

贝尔库利用力握住爱剑「时穿剑」，准备朝著飞龙追去，但是爱丽丝用术式在敌人战线上开出的洞已经被填补起来，一大群深红色步兵一边吐出奇怪的骂声一边靠了过来。

「给我……」

在贝尔库利吼出「让开」之前，一道炫目白银光芒已经越过他的头顶。

那是边发出尖锐清澈的「叽哩叽哩叽哩」声边在空中飞翔的两枚飞刀。也就是整合骑士连利的神器「双翼刃」。

背后可以听见少年骑士尖锐的声音：

「Release recolle！」

绽放出一瞬间的光芒后，飞刀在空中融合。变成十字飞翼的刀刃，一边超高速旋转著一边以自由自在的轨迹飞翔，把挡住去路的众敌兵全都砍倒。

「骑士长，请快点过去吧！」

贝尔库利保持背对著连利的姿势来回应他的叫声。

「抱歉！再来就交给你了！」

他迅速沉下腰部，右脚全力往地面踢去。

瞬间，穿著东方风服饰的骑士长就化成一道蓝色疾风。贝尔库利一口气突破在一大群敌人中再次打开的缝隙。他急奔的速度，远超过黑暗领域的拳斗士藉由长时间战舞才能锻炼出来的跑动速度。

皇帝贝库达抓走爱丽丝的飞龙，这时早已变成高空中渗出的一个小黑点。

贝尔库利一边奔驰，一边用左手贴在嘴角然后发出尖锐的哨声。

几秒钟后，银色飞龙就从前方的山丘飞起。那是贝尔库利的坐骑──星咬。

不过回应口哨的龙不只有一头而已。爱丽丝的坐骑雨缘，以及在东大门丧命的骑士艾尔多利耶的坐骑泷刳也跟在后面。

「你们……」

贝尔库利把原本想对后面两头龙发出的待机命令一口吞了回去。

滑过低空靠过来的星咬一个转向，把脚对著贝尔库利伸出去。

骑士长把左手放到钩爪上，接著一口气把自己拋上龙的背部。一跨到鞍上，就猛然挥下右手上的剑。

「冲吧！」

才刚叫完，星咬、雨缘与泷刳就同时拍动翅膀，飞上染了紫色的清晨天空。

三头龙组成了楔形队型来飞翔，而飞在遥远前方的黑龙脚下附近，一瞬间闪动了一下金黄色光芒。

＊＊＊

四千名拳斗士一口气跑过亚丝娜生成的石桥，和好不容易存活下来的两百人左右的同伴会合之后，随即从人界军旁边经过，简直就像巨大的攻城槌一般猛烈地撞向敌军中央。

他们十人一组紧密地排成一横列，然后以完全一致的动作把右拳往后拉来摆出备战姿势。

「「「呜、啦！」」」

随著完全重叠在一起的吆喝声所挥出的十记正拳突刺，直接折断、轰裂了红色士兵的剑与铠甲。二十名以上的敌军在发出悲鸣的情况下，喷出血雾往后方飞去。

十个人施放完贯注全部斗气的突刺后，迅速往旁边退开让出空间，正后方的十个人立刻从缝隙冲出来组成紧密的横列。

「呜啦啦！」

这次变成以完全一致的动作击出前踢。再次有大量的敌人像遭到炮击般被轰飞。

「……好厉害。」

亚丝娜一边用昨晚刚背下来的治愈术指令治疗左臂的伤口，一边忍不住这么呢喃著。在旁边喝著水的谢达，侧脸上也渗出些许感到佩服的气息。

拳斗士们的轮值，与过去在Sword Art Online刀剑神域里攻略组对上魔王时所实行的「切换」相当类似，但是更加地洗炼。几个由十人排成十列的百人集团，简直像工地用重机械般蹂躏敌人的模样，让看见的人忍不住觉得相当可怕。

「光是佩服我们会很困扰哟。直接往南贯穿敌阵之后该怎么做？就算是我们，也很难在这里歼灭那么大量的敌人。」

站在亚丝娜身边双手环抱胸前的红发族长，这时以严肃的表情这么说道。

光看往前的突进力的话，拳斗士队看起来确实是难逢敌手，但也已经出现被数倍的敌兵从侧面突击后阵型崩毁的集团。毕竟目前被召唤到这里来的美国玩家人数也还是超过两万人。

「…………南向突破敌阵之后，请直接一口气前进和敌人拉开距离。我会再次制造峡谷来隔离敌人。」

亚丝娜以沙哑的声音这么回答。

真的办得到吗？刚才光是制造一座小小的桥就快要昏倒了。要是再次进行延伸到地平线为止的大规模地形操作的话，真的有可能被强制登出，一个搞不好甚至会对肉体的脑部造成物理性伤害……

亚丝娜用力咬住嘴唇来斩断一瞬间的犹豫。只能硬著头皮上了。召唤美国人玩家应该是皇帝贝库达最后的计策了吧。这样的话，只要击溃这条策略，就算亚丝娜在这时候脱离，他也没办法再对爱丽丝出手了才对。

就在这个时候，一名卫士从南边往停留在北端的亚丝娜与谢达跑过来。

「传令！传令──！」

似乎在移动中负伤而半边脸孔染血的卫士，在亚丝娜面前跪下后就用沙哑的声音大叫：

「来自于整合骑士连利大人的传令！整合骑士爱丽丝大人，被敌人总大将乘坐的飞龙绑走了！飞龙似乎直接朝著南方飞去……！」

「什…………」

亚丝娜说不出话来。

怎么会──难道说，这种状况是为了诱使爱丽丝独自离开人界军……！

「你说……皇帝飞走了？」

以奇妙的破碎声音回应的，不是亚丝娜也不是谢达，而是拳斗士的族长。唯一残留下来的左眼浮现异样光芒的他继续挤出声音。

「这么说来，刚才坐在飞龙上……不是只为了看热闹吗……喂，女人！」

年轻人以发出锐利光辉的独眼凝视亚丝娜，然后著急地逼问她。

「那个叫爱丽丝的就是『光之巫女』吧？皇帝为什么想要得到那个家伙？光之巫女落入皇帝手中的话，到底会发生什么事？」

「这个世界……将会毁灭。」

亚丝娜简短地回答。拳斗士的左眼因为惊愕而瞪大。

「暗神贝库达获得光之巫女爱丽丝并且到达『世界尽头的祭坛』时……这个世界，不论是人界还是黑暗领域，包含居住在这里的人们全将回归虚无。」

亚丝娜脑袋的角落意识到自己这时所说的话，带有极为浓厚的RPG游戏剧本的味道。

但这是无庸置疑的事实。获得爱丽丝的皇帝贝库达，也就是现实世界里强行突袭O Turtle的队伍，毫无疑问地会把收纳Underworld所有居民摇光的LightCube Cluster完全破坏。

──啊啊，该怎么办才好？史提西亚帐号并没有附加飞行能力。该怎么做才能追上乘著飞龙的皇帝贝库达……

回答亚丝娜内心烦恼的，是站在旁边的灰色骑士谢达。把喝光的水袋挂回腰带上之后，有著沉稳容貌的女骑士便这么说道：

「飞龙无法永远飞行下去。连续飞行最多只能够撑半天。」

结果瞄了谢达一眼后立刻把脸转回来的拳斗士族长，啪一声用拳头击打手掌后大叫：

「这样的话，你们就只能咬紧牙关追上去了！」

「什么追上去……你……」

亚丝娜茫然看著敌将年轻的容貌。

「你是黑暗领域军的人吧？为什么会像这样站在我们这一边……」

结果敌将用鼻子哼了一声，接著丢出这么一句话：

「皇帝贝库达确实在我们十侯面前这么说了。他说自己想要的就只有光之巫女，只要能获得那个家伙，其他事情他就不管了。从捕获到巫女的那一刻起，皇帝的目的就达成了……也就是说，我们的任务也全部结束了。再来我们要做什么……就算是从皇帝手中把巫女夺回来还是帮助人界军都是我们的自由了吧！」

竟然有如此牵强附会的说法。

亚丝娜哑然看著拳斗士的脸。但是出现在他脸上的却是和气势发言相差甚远的悲壮决心。

拳斗士的左眼笔直看著亚丝娜，然后开口表示：

「……我……我们无法直接违抗皇帝。他具有压倒性的力量……因为他连手指都没动一根，就杀掉说不定比我还强的暗黑将军夏斯达。如果皇帝再次下达和你们战斗的命令，我也只能遵从──所以，我们拳斗士团就在这里挡住这些红色士兵。你们人界军去追皇帝吧。然后……把皇帝……把那个家伙……」

年轻人忽然不再说下去，脸孔则像是因为不存在的右眼产生疼痛而扭曲。

「帮忙告诉那个家伙，我们不是你的玩偶。」

刚好在这个时候，一声特别高亢的拳斗士喊声从战场南侧响起。前头的部队终于突破红色步兵团的包围，到达后方的荒野。

「很好……」

年轻族长右脚「滋当！」一声往下一踏，然后用惊人的声量命令：

「你们这些家伙，把那个突破口撑住！」

接著把视线拉回来亚丝娜身上，快速地说道：

「你们快点离开这里！我们没办法撑太久！」

亚丝娜用力吸了口气并点了点头。

──这个人也是人类。

就算是人工摇光，依然是拥有强韧、高傲灵魂的人类。明明对于冷血砍断一族横渡峡谷时的绳索，斩杀了百名以上族人的我们，应该也有想发泄的怨恨与憎恶。

「……谢谢。」

好不容易挤出这么一句话，亚丝娜就转过身子。

这时背后的整合骑士谢达对她搭话：

「我也留在这里。」

不知道为何已经有这种预感的亚丝娜，回过头来对著灰色女骑士轻轻笑了一下。

「我知道了。就麻烦你殿后了。」

＊＊＊

伊斯卡恩默默地目送栗色头发的不可思议女骑士，以及剩下七百名左右的人界军跑过一族的斗士们维持东西战线来撑住的突破口。

接著把视线从土尘上移开，看向站在身边的灰色整合骑士。

「……真的没关系吗，女人？」

「已经说过我的名字了。」

被狠狠一瞪后，伊斯卡恩才耸耸肩重新说道：

「没关系吗，谢达？不知道能不能活著回去哟。」

瘦削的骑士耸肩让全新的铠甲发出「锵」一声。

「要干掉你的是我。不会让给那些家伙。」

「嘿，真敢说。」

这次伊斯卡恩真的发出快活的笑声。

想帮助无谓惨死的伙伴。原本只希望做到这一点的自己，现在却为了从红色军队手中守护人界军而赌上部族全体的命运，虽然这实在有点不可思议，但是胸中却吹起一股爽朗的风。

──嗯，这样的死法也不错啦。

如果是为了守护整个世界，在故乡的老爸和弟妹们应该也能理解吧。

「好啦──！你们这些家伙，打起精神来啊！」

立刻就有「呜啦啊！」的吼叫声回答他。

「组成圆阵！全面防御！把那些靠过来的蠢蛋全部轰烂！」

「冠军，真令人热血沸腾。」

无声回到背后固定位置的达巴，让沾满血的左拳发出喀叽喀叽的声音。

＊＊＊

越过南边的山丘，撤退到补给队等待的森林里时，亚丝娜从少年骑士连利那里得知骑士长贝尔库利随著三匹飞龙一起去追踪皇帝贝库达了。

「……你认为能追得上吗？」

面对亚丝娜的问题，连利残留著稚气的脸上出现严肃的表情并回答：

「老实说，有点难判断。因为原则上飞龙是以同样的速度飞行，也必须在同样的时间休息……不过，皇帝贝库达的飞龙因为搬运爱丽丝大人，所以天命的消耗应该会增加一些才对。反过来骑士长阁下可以轮流骑乘三匹飞龙来减低它们的疲劳，所以应该能慢慢拉近距离……」

事到如今，再来也只能祈求骑士长在贝库达到达世界尽头的祭坛之前追上他了。

但是，就算能顺利捕捉到皇帝──

骑士长贝尔库利单独一人真的能赢得了暗神贝库达吗？

没想到连袭击者都是用超级帐号登入的亚丝娜，没有听说贝库达被赋予了什么样的能力。但是，如果贝库达拥有和史提西亚的地形操纵同等的力量──那么就算是能够以一挡百的整合骑士长，要与他单挑应该也很难获胜吧。

当亚丝娜想到这里时，连利就用斩钉截铁的口气说：

「如果能追上，骑士长阁下一定会把爱丽丝大人救回来。因为那位大人是世界最强的剑士。」

「……嗯，说得也是。」

亚丝娜也坚定地点了点头。

到了这个时候，也只能相信对方了。不是才刚目击到Underworld人的意志有多么坚强吗？

「这样的话，我们也全队往南前进吧。幸好前方好像是一大片平坦的土地。虽然追赶不上贝尔库利先生，但或许能帮上什么忙也说不定。」

「我知道了，亚丝娜大人。那么我立刻让他们进行出发的准备。」

连利加快奔跑的速度，抢先消失在森林当中。

亚丝娜一边目送他的背影离开，一边对著自己说道。

绝对要保护桐人，以及他想保护的爱丽丝和所有人界人。不论受到多少次伤害──不论得承受多大的痛楚。

＊＊＊

这个时候──

现实世界里漂浮在太平洋上的海洋研究用自走式巨大人工母船「O Turtle」的主控室里，袭击队伍中负责电子战的队员克里达正准备让新的第二波多达两万人的美国人玩家潜行到Underworld里。

但座标却是追随加百列﹒米勒的现在位置，变更为比第一波的投入地点更往南十公里左右的地方。

2

「…………呜！」

瓦沙克‧卡萨鲁斯随著锐利的呼吸声迅速撑起身子。

一边乱甩著绑成马尾的卷发一边快速确认周围。

发出钝重光芒的金属墙。施加了防滑树脂加工的地板。微暗当中朦胧浮现出来的无数萤幕与指示器。

接著认真地看了一会儿坐在眼前椅子上那名瘦削的平头男子后，瓦沙克才终于想起来这里是O Turtle的主控室。

平头男──克里达用鼻子哼了一声后才用尖锐的声音说：

「哎呀呀，醒过来了吗？我还以为你的脑细胞都烧焦了呢。」

「……Shut the fuck up.」

瓦沙克一边以呢喃声回应，一边低头看著自己的身体。目前是躺在铺于墙壁边的薄垫上，肚子上还随便盖著一件夹克。

像是不知道究竟是怎么回事般用力摇了摇头后，脑袋中央就传来刺痛感。他再次咒骂了一声，然后对房间另一侧坐成一圈打著牌的数名队员搭话道：

「喂，有没有人带了阿斯匹灵？」

结果满脸胡须的突击队员布里克默默在口袋里找了一会儿，然后丢了一个小小的塑胶瓶过来。瓦沙克单手接住后，扭开瓶盖就随手把药丸倒进嘴里并将其咬碎。

足以让舌头麻痹的苦味终于让他的一些记忆变得比较鲜明。

「对喔……我掉到无底的深渊里……」

一这么自言自语，克里达就带著满脸笑容对著他问：

「你在里面到底是怎么死的？竟然昏了整整八个小时。」

「八……八小时！」

感到惊愕的瓦沙克甚至忘了头痛直接跳起来。

瞪著左手腕上的G-SHOCK手表，得知目前是日本标准时间上午六点三分。距离日本的神盾舰「长门」以及自卫队员冲进O Turtle的期限大约剩下十二个小时。

不对，更重要的是──

昏过去八小时的话，在时间经过加速的Underworld里应该已经过了漫长的岁月才对。人界对暗黑界的战争……以及捕获「爱丽丝」的任务究竟如何了呢？

但是，克里达像是看透瓦沙克的惊讶般，啧一声咂了一下舌头。

「少在那里瞪大眼睛了。放心吧，你在里面挂掉的时候，时间加速已经降到等倍了。」

「你……你说等倍？」

这样的话，那边的状况应该没什么太大的变化吧。不对，等一下，这也算是个大问题吧。

「喂，四眼田鸡，你到底懂不懂啊。再十二个小时，JSDF的海军就要冲进来喽！」

像是感到很厌烦般扫开瓦沙克用力晃动自己平头的手，克里达接著回答：

「那还用说吗～这全部都是米勒队长的指示啦。」

他接下来说明的「作战」，连身经百战的VRMMO玩家瓦沙克都感到惊讶。

指挥袭击小队的加百列‧米勒在远离黑暗领域东部的帝宫黑曜岩城里的系统操纵台前，已经秘密地对现实世界的克里达留下指示。

他要克里达制作宣传无视法律规范的新暴力型VRMMO──当然指的是Underworld──的封测宣传网站，并且准备好连线用的用户端程式。然后在七月七日凌晨十二点左右把加速倍率降到等倍，同时在全美国募集封测玩家。

「……靠这个被锁住的操纵台，只能知道队长和你的座标，以及个体的大略分布。所以这个作战是人界方的抵抗比预测来得强烈时的保险手段。」

克里达细长的手指在键盘上跳动，让Underworld的全体地图显示在正面萤幕上。

锐角变圆的倒三角形世界地图上，东边的角落有两条红线开始延伸，逐渐往西方移动。

「这就是你和队长的移动履历。看好了，你这家伙在帝国东侧的大门附近乱绕，然后在这个地方丧命。」

一条红线在「东大门」稍微往南方一点的地方变成×号然后就中断了。

「但是队长现在越过你死亡的地点，继续往南方前进了。而且是把黑暗领域全军丢在北边，单独南进。至于这是什么情形嘛……」

「不是在追『爱丽丝』，就是已经抓住她了吧。」

瓦沙克发出沉吟声后，克里达也点点头并继续说明：

「原本的作战呢，是剩余时间剩下八小时，或者人界军全灭时就再次把加速倍率恢复成一千倍。光是这样，内部就已经过了一年。加速恢复的时候，潜行到里面的美国玩家就会因为延迟而全部被登出，不过只要战争能够获胜就没关系了。」

「这样的话，现在就恢复倍率如何啊？人界守备军已经没剩下多少兵力了。」

「事情没这么简单。你看看这个地方。」

克里达敲打键盘，扩大一部分地图。

分隔人界与暗黑界的东大门，从该处往南方数公里的地方，直向并排著平地、山丘与森林等地形。而森林里还潜伏著人界军……该处也就是瓦沙克死亡的地点。

但不知道什么时候，森林与平地之间出现了长达五十公里以上的东西向巨大峡谷。在峡谷周边蠢动的极小圆点集合体，分别以红、白、黑等三种颜色来显示。

「这个红色所表示的就是丢进Underworld的美国人玩家集团。虽然减少了许多，但还剩下两万左右。然后有一半被红色包围的黑色集团就是黑暗领域军。大概有四千人左右。」

「喂……喂喂，怎么看红色都在袭击黑色吧。」

「因为在假的封测宣传里，只写了能够尽情残杀超真实的NPC而已。从美国潜行的家伙，无法区别人界军与暗黑界军啦……但是，不知道为什么，黑色减少的速度比想像中还要慢。对于皇帝绝对忠实的暗黑界军，绝对不可能抵抗算是被皇帝召唤过来的美国人玩家才对啊。」

「我看是只顾著一点一点地虐杀敌人吧。」

「嗯，反正这黑色的四千人不久后就会全灭吧。问题是，这边有一点点白色的集团吧。」

克里达移动浮标。确实有一个小小的白色集团，就像是要追赶往南直线前进的皇帝贝库达，也就是米勒队长一样正在移动。

「这是人界军。地图上看起来虽然小，但还是有七百人左右。这些家伙追上队长的话会很麻烦，得想个办法阻止他们才行。」

「你说阻止……但要怎么做呢？」

不直接回答瓦沙克的问题，克里达简短地嘻嘻一笑后，又继续操纵起键盘。

地图上打开了新的视窗。以全黑色为背景的视窗上，可以看见巨大的红云正不停地蠢动。

「这些家伙是来不及赶上第一次连线，正在等待第二次连线的美国玩家。到达两万人时，就把他们丢到人界军的座标上。战力比是一比二十八，一瞬间就能歼灭对方哟。之后再把加速恢复成一千倍，队长也还是有充足的时间抓住爱丽丝并且到达最南端的系统操纵台才对。」

「……能这么顺利就好了。」

瓦沙克一边摩擦著下巴一边提出反驳。

「人界军比你想的还要难缠。尤其是那些叫作整合骑士的家伙更是疯狂，他们把黑暗领域军的前锋杀得片甲不留。不然的话，我怎么可能会这么……狼狈…………」

当瓦沙克说到这里时。

终于想起来自己是被什么人用什么方法所杀。

他瞬间屏住呼吸并且瞪大双眼。从遥远夜空中低头看著自己的女神般模样鲜明地在脑海里复苏。忘我的他，脱口而出的不是英文而是日文。

「──『闪光』……！对了……不会错的，那绝对是那个女人……！」

「啥？你在说什么？」

克里达露出疑惑的表情，瓦沙克则紧抓住他的平头，接著恢复成英文丢出一大串话。

「喂，你这个阿宅，躲在第二控制室不出来的RATH那些家伙也实行了跟你一样的作战哟！人界军里面有日本人的VRMMO玩家！」

「什么～？」

不理会露出怀疑表情的克里达，瓦沙克单边脸颊上扬起了狰狞的笑容。

「既然『闪光』亚丝娜在那里，说不定那家伙也潜行到里面了……真的假的，不能继续待在这里了……喂，我也要再回去那边！把我和那两万援军一起降到那个白色集团的座标上！」

「什么回去，已经没有被你白白浪费掉的黑骑士帐号喽。和援军一样的士兵帐号是要多少有多少啦。」

「帐号的话……我有特别保留下来的。」

在喉咙深处发出「咕咕」的笑声后，瓦沙克就捡起掉在操纵台上的代餐条包装纸，然后迅速动著从克里达胸前口袋拔出来的笔。

「听好了，用这个ID和密码登入日本『The Seed连结体』的综合入口，把保存在里面的游戏角色转移到Underworld。我要用它来潜行。」

留下这句话后，瓦沙克往通往STL室的门走了几步。

但是，这时候又忽然停下脚步。

再次回头的瓦沙克嘴角，已经挂著连知名电子犯罪者克里达都忍不住背脊发凉的，残酷且残忍的笑容。简直就像几秒钟前那种粗俗、开朗、聒噪的佣兵，只不过是他表面的人格之一而已。

瓦沙克踩著猫一般的无声脚步回到操纵台旁，又在克里达耳边简短呢喃著追加的指示。几秒钟后，骇客就茫然凝视著这次确实吞噬了瓦沙克的STL室大门，而他手上则残留著小小的纸片。

纸上写著三个英文字母以及八位数字。克里达并不清楚S、A、O三个字后面的文字列代表什么意思。

＊＊＊

冲过进行出发准备的卫士之间进入补给队马车里的亚丝娜，这时看见的是横向倒在地上的银色轮椅、左手微微动著的黑衣青年，以及趴在他身上的两名少女。

听见脚步声迅速抬起脸的罗妮耶，一确认来者是亚丝娜，就扭曲被泪水湿濡的脸颊大叫：

「亚……亚丝娜大人！桐人学长他……好几次、好几次都想到外面去……」

亚丝娜咬紧嘴唇点了点头，然后跪到地板上，以平安无事的右手紧握住桐人的左手。

「嗯……爱丽丝小姐……被敌人的皇帝给绑走了。我想桐人一定是感觉到这件事了。」

「咦……爱丽丝大人她！」

这么大叫的是缇洁。白色脸颊变得更苍白了。

这时打破一瞬间沉默的是桐人软弱又沙哑的声音。

「啊……啊……」

左手动了起来，想要去触碰亚丝娜受伤的左臂。

「桐人……你在担心我吗……？」

当亚丝娜忍不住这么呢喃时，注意到她伤势的罗妮耶才发出类似悲鸣的声音。

「亚、亚丝娜大人！你的手臂……！」

「不要紧。因为这伤对我来说就像假的一样……」

呢喃完后，亚丝娜就静静地举起手肘以下已经消失的左臂。

关于形成Underworld的「泛用视觉化记忆」科技，已经接受过RATH的比嘉健粗略的指导。虽然所有的物体都和ALO一样是由The Seed program所生成，但是对使用STL潜行的亚丝娜、桐人，以及缇洁等人工摇光来说，这个世界的万物都是从Main Visualizer下载下来的「共有记忆」。是藉由想像力具现化的另一个现实。

赋予超级帐号──史提西亚的天命，也就是HP是相当庞大的数字。几乎到达可以设定的数字上限，所以如果是通常武器的攻击，就算有一百把剑贯穿亚丝娜，她的天命也不会归零。

但是红色士兵挥落的巨大战斧直接砍中左臂时，亚丝娜还是打从心底感到恐惧。被这么大的斧头砍中的话手臂一定会被砍掉，她自己这么想像，而想像力也就把它变成现实。

就和桐人的右臂是一样的情形。数值上的天命明明早已经恢复，但是手臂却没有复原。这是因为桐人一直在处罚自己的缘故。

亚丝娜把自己的右手举到绑著绷带的左手切断面前。

然后集中意识，坚定地告诉自己。

我不会再感到害怕了。在桐人以及这个世界安全之前，我再也不会……输给任何人。

啪一声伤口出现白光。温暖的光辉无声往前延伸，失去的左臂就这样逐渐复原。

对像是看见奇迹而瞪大双眼的两名少女报以微笑后，亚丝娜就用恢复原状的左手轻轻抱住桐人的头，接著对心爱的人呢喃：

「听我说，我不要紧了。也一定会救出爱丽丝小姐给你看。所以……那个时候，桐人也不要再责备自己了……」

虽然不知道说的话能不能传到对方心里，但可以感觉到紧绷的瘦削身体逐渐放松。亚丝娜再次紧抱桐人，然后就迅速抬起脸来说：

「我们接下来要去追敌人的皇帝。现在贝尔库利先生已经骑飞龙追过去了，一定会在哪个地方追上他才对。在那之前，桐人就拜托了……罗妮耶小姐、缇洁小姐。」

「好……好的！」

「请交给我们吧，亚丝娜大人！」

亚丝娜对点头的少女露出微笑，然后一边忍著眼泪一边把桐人交给罗妮耶，自己从马车上跳了下去。

结果就在这个时候，昨天晚上和亚丝娜、罗妮耶等人一起参加回忆爆料大会的高个子女性剑士跑了过来。虽然她银色的铠甲上沾满血迹与尘土，额头上也缠著绷带，不过看起来不是太严重的伤势。

「太好了，你平安无事，索尔缇莉娜小姐。」

亚丝娜朝对方这么搭话，剑士就迅速回以Underworld风格的敬礼并回答：

「亚丝娜大人也平安真是太好了……不过──据刚才听见的传闻，爱丽丝大人似乎被敌人的总大将绑走了……」

「是的。刚才也告诉过缇洁小姐她们了，皇帝贝库达完全拋下自己的军队，独自一人袭击了爱丽丝小姐。实在没想到他会有这样的行动……」

「……竟然有这种事……」

亚丝娜以刚治好的左手，用力抓住愕然睁大双眼的索尔缇莉娜右肩。

「但是，事情并不会这样就结束。贝尔库利先生骑飞龙去追贝库达了。我们也马上要追上去。」

「了解了。」

互相点了点头后，两个人就一起赶往守备军诱饵部队的大本营。

根据整合骑士连利的指示，七百名卫士们几乎快完成移动准备了。以治疗完伤患的术师队与补给队为中心，流畅地组成队型。

亚丝娜这时对前来报告完成准备的连利说：

「现在残留在部队里的整合骑士就只有你而已了，连利先生。出发的指示就由身为指挥官的你来发布吧。」

「好……好的，我知道了。」

以紧张的面容点了点头的少年骑士，随即高举起右手，以清晰的声音大叫：

「爱丽丝大人在大门的战役当中保护了我们！现在轮到我们为了爱丽丝大人而战了！一定要从敌人手中夺回爱丽丝大人，和她一起回到人界！」

立刻涌出「喔！」的坚定喊叫声。连利点了点头，接著猛然挥落右手。

「──全军，出发！」

连利的飞龙风缝开始在队伍的前头跑了起来。四百人的前卫部队以骑马与步行的方式前进，载著补给物资的八台马车与三百名后卫部队也依序开始移动。

只有一头整合骑士谢达的飞龙，无论如何都不愿意离开现场。在没办法的情况下解开它的缰绳，灰色鳞片与主人发色相似的飞龙叫了「咕噜噜噜」一声后，就朝著反方向的北边──谢达留下来的峡谷南侧战场飞去。

马车列的前面，和索尔缇莉娜同样在马背上摇晃的亚丝娜思考著。

要战斗的敌人就只有皇帝贝库达一个人。

他的真面目是和亚丝娜一样拥有虚假生命的现实世界人。这样的话，就算同归于尽也一定要打倒他。这样才不会对不起为了防止红色士兵们追击，而留在死地的骑士谢达与独眼拳斗士族长，以及那四千名拳斗士。

几分钟后，一整片枯木的森林消失，前方出现磨钵状的巨大洼地。一条细长的道路贯穿宛如陨石坑般的地形往南方笔直延伸。

如果按照RPG的规则，顺著这条路的前方应该设置有城市或者遗迹之类的固定设施才对。但是暗黑领域的南部似乎不存在亚人们的领土。也就是说，这条路的终点就是「世界尽头的祭坛」，而皇帝贝库达与整合骑士爱丽丝就在这条路上的某个地方。

皇帝的飞龙就不用说了，现在连库尔贝利骑著追上去的飞龙都已经不见踪影。但是已经减少到剩下七百人的人界军卫士们还是踩出脚步声，并且尽可能以最快的速度在干枯的道路上往前进。

越过陨石坑边缘，跑向下坡，当部队快来到磨钵底部的这个时候──

可以感觉到某种低沉的震动。

那是「嗡嗡嗡嗡……」的虫子拍动翅膀般的震动声。

「…………？」

亚丝娜稍微抬起视线。环视左右接著确认背后。

再次凝视正面时，终于可以看见声音的来源。

那是又红又细的线。

从空中出现几百条不规则明灭的记号罗列往地面延伸。

「…………不会吧…………」

颤抖的嘴唇漏出细微的声音。

──骗人。不要这样。别再出现了。

但是……

唰啊啊啊啊！

类似骤雨般的巨响一口气炸裂。降下的无数红色线条往左右两边散开。沿著陨石坑边缘形成高密度的帘幕，把部队完全包围在里面。

明明才刚发誓不再害怕，亚丝娜却感觉双脚瞬间失去力量。

出现在红线聚集处的当然就是是那只凶暴的深红军团──从现实世界被叫过来的VRMMO玩家了。

「全……全军，不要停下脚步！突击！突击──！」

整合骑士连利在前头做出这样的指示。从快要产生动摇的人界军各处传出「呜喔喔！」的战斗吆喝声，移动速度也开始增加。部队笔直地冲上陨石坑的斜面。

但是，简直就像预先看出他们会有这样的行动般，新出现的红色军队在南侧配置了最多的兵力。光是挡住道路的士兵们就有一千……不对，是两千人吧。

还是应该冒著登出的危险再次使用史提西亚的地形操作吗？但随便出手的话，也可能妨碍到人界军的进攻。

飞龙的吼叫声贯穿了亚丝娜一瞬间的犹豫。

队伍的前头，由骑士连利乘坐的风缝，从嘴巴两侧闪著火光一口气往前猛冲。

「糟糕……连利大人想牺牲自己来制造突破口……」

亚丝娜身边的索尔缇莉娜以悲痛的声音这么表示，而连利就像听见她的声音一般在龙背上稍微回头看了一眼。

──再来就拜托了。

少年的嘴唇这么动著。

转向前方的骑士，抽出腰间那一对美丽的回力镖后，就以双手摆出备战姿势。

就在他投掷出武器之前──

陨石坑正上方的天空忽然改变了颜色。

染上血一般红色的黑暗领域天空忽然呈十字形裂开，亚丝娜看见后方是一整片深蓝色的天空。

不论是密集在陨石坑边缘，似乎立刻就要突进的无数红色士兵，还是持续突进的人界兵，甚至是跑在前头的骑士连利都同时抬头仰望天空。

宛如延伸到宇宙一般的无限苍穹。

从遥远的地方降下一颗白色的闪耀星星。

不对，那是一个人。穿著与天空同样的深蓝铠甲以及云一般的白色裙子。剧烈摇晃的短发是蓝色。发出白光的是握在她左手里的巨大长弓。脸庞因为逆光而看不清楚。

──那是谁……？你到底是谁？

就像要回答亚丝娜无声的问题一样。

从空中降下的某个人，把几乎跟她身高一样的长弓举向天空。

右手拉紧同样发出朦胧光辉的弓弦。

一道极为猛烈的闪光。弓与弦之间出现发出纯白亮光的光箭。

不论是人界军还是红色步兵都在不知不觉中停下脚步。在所有人都说不出话来的寂静当中，身边的索尔缇莉娜再次呢喃道：

「…………索鲁斯大人……？」

宛如回应她的呼唤一般。

炫目的光箭被笔直朝空中发射出去。

光箭瞬时分裂并往各个方向扩散。

画出锐角弧形后翻转，变成白热的雷射往地面降下。

卫士长索尔缇莉娜‧赛鲁鲁特的话有一半正确。

出现在陨石坑上空，不对，应该说登入到这里的现实世界人所使用的是超级帐号02「太阳神索鲁斯」。

赋予该帐号的专属能力是「广范围歼灭攻击」。

＊＊＊

当诗乃/朝田诗乃随著战栗感往下看著自己造成的压倒性破坏现象时，与叫作比嘉的技术人员进行的通话也在她脑里复苏。

「那个，诗乃小姐，虽然超级帐号的确很强，但绝对不是万能哟。是为了无论如何都要在Underworld进行大规模的操作时，能够用该世界的居民大概还可以勉强接受的形式，才会准备这样的帐号。」

「嗯……意思就是并非GM（Game master），而是非常强的PC（Player character）而已吗？」

谜样新兴企业RATH的六本木分部当中，横躺在宛如最初期完全潜行实验机的巨大STL机器里面时，诗乃反问比嘉从扩音器里传出的声音。结果听见的是「啪叽」这种应该是响指的声音。

「Yes，正是如此。所以让你使用的『索鲁斯』帐号也无法跳脱设定在Underworld里的空间力这个大原则。用弓进行攻击时，一定会需要消费空间资源。因为还有自动填充能力，所以白天的话不可能发生能源枯竭的情况，但还是请把它当成无法连射吧。」

正如比嘉所说的，握在诗乃左手上的纯白长弓，在大规模攻击之后光芒就变淡了。虽然再次逐渐从两端出现发光特效，但应该要再过两三分钟才能再次进行全力攻击吧。

──不能连射？哼，那算什么问题。

跟全自动比起来，我比较习惯单发的武器啦。

在胸中放出这样的豪语后，诗乃就确认起爆炸火焰逐渐止歇的地面情况。

全长应该有一公里的陨石坑边缘上，烧成焦黑的尸体不断变成光粒然后消失。一次的全力攻击似乎就排除了五千以上的敌兵。老实说，幸好那不是真正的Underworld人，而是和诗乃一样从现实世界登入到这里来的美国人。相信是免费的封测，结果一连线的瞬间就被烧死的玩家们，现在一定在外面的世界感到一肚子火吧。

陨石坑中央，和红色军队比起来规模实在太小的部队再次开始前进。虽然还整整残留了一万名以上的敌人，但当中有将近半数都因为害怕下一次的射击，或许应该说轰炸而看著上空的诗乃一动也不动，所以他们应该有办法突围才对。

诗乃眯起双眼，凝视著「人界」的队伍。

立刻就注意到队伍正中央附近，跨坐在白马上那名笔直往上看著这边的栗发少女。

忍不住笑了一下之后，诗乃才试著控制附加在索鲁斯帐号的专属能力之一──「无限制飞行」。听到比嘉说「用想像力飞行」时，还觉得那怎么可能办得到，但实际尝试后才发现跟ALO的任意飞行差不多。少女立刻朝正后方的马车一直线降下。

鲜蓝色靴子的脚尖踏上帆布料的车顶时，就举起右手这么呼喊：

「让你久等了，亚丝娜。」

结果穿著珍珠色铠甲套装的少女，眼睛立刻浮现珍珠般的眼泪。灵活地站到还在奔驰的马背上，直接跳到马车屋顶……

「────小诗诗……！」

一边发出挤出来般的声音一边张开双臂。

被用力抱住的诗乃，轻轻地拍了拍好友纤细的背部，然后呢喃：

「你很努力了。不要紧喽……再来就交给我吧。」

她在被只比自己高一点点的亚丝娜抱住的情况下，把左手终于填充两成力量的弓朝向前方，然后右手轻轻拉弦。

赋予索鲁斯帐号的GM装备，长弓「歼灭光线」能够以拉弦的强度以及弓的角度来设定攻击的威力与范围。拉了十公分左右停下来后，就出现比刚才细了许多的光箭。诗乃把箭尖对准挡住前方奔驰大龙去向的敌人集团。

「噗咻」一声细微的发射音响起。

由往右倾斜二十度左右的弓所发射出去的箭，一边分裂一边击中直径十公尺的范围，引起不输给拖式反装甲飞弹的爆炸。红色铠甲被轰上高空，然后在空中消灭。接著龙立刻冲进因此而造成的空隙当中。残活下来的十几名士兵，也在龙用头部以及钩爪的横扫与踢腿攻击下轻易被打倒。

这时剩下来的敌兵好不容易从雷射攻击的冲击当中恢复过来，注意到原本要打倒的猎物已经准备要逃走了。士兵们从嘴里发出叫骂声，化成红色海啸由陨石坑的斜面往下方急奔。

诗乃把弓挂到手臂后就将手放在亚丝娜双肩上，然后静静地移开身体。

「亚丝娜。我看到从这边往南五公里左右的地方有一座遗迹般的废墟。道路就从中央贯穿那座废墟，左右两边并排著一些巨大的石像。到那边的话，应该能在不被包围的情况下迎击敌人。想办法在那个地方击退这些家伙吧。」

亚丝娜怎么说也是身经百战的战士，听见诗乃的话后立刻露出严肃的表情。擦去泪水后就开口表示：

「知道了。小诗诗……诗乃。就算美国的VRMMO人口再多，应该也无法立刻准备更多的人数了。击退那一万数千人的话，我想……敌人应该就无计可施了。」

「知道了，交给我吧……还有，先不提这些……」

确认人界军最尾端终于穿越敌人的包围网后，诗乃就小声询问自己的好友。

「……那个，桐人在这个部队里吗？」

这个行动让亚丝娜也不由得露出些许苦笑。

「事到如今也不需要再用那么见外的问法了吧。桐人他在这里。」

举起来的右手食指，指向两人的脚边。应该是在马车里的意思吧。

「这……这样啊。那么……我去跟他打个招呼。」

干咳了一声之后，诗乃就移动到盖住大型马车的车顶后端，稍微使用飞行能力让身体滑进内部。

等待亚丝娜也下来，就朝著叠著木箱的深处移动。

首先进入视界的是，在让人联想到学校制服的服装上穿戴了防具的两名少女。她们一起瞪大双眼，然后发出细微的声音。

「索……索鲁斯大人……？」

诗乃往下瞄了一眼自己显眼的打扮后，才耸耸肩向两人打招呼。

「初次见面，两位好啊。虽然外表看起来像索鲁斯，但内在不是。我的名字是诗乃。」

好不容易挤出笑容并自报姓名后，两个人就眨了眨眼睛，但看见她身后的亚丝娜似乎就了解是怎么回事了。诗乃这时也对她们点头，接著继续说：

「没错，我也跟亚丝娜一样是现实世界人。同时也是桐人的……朋友。」

「是这样啊……」

红发少女依然保持惊讶的模样，但深茶色头发的少女却露出微妙的表情并且小声呢喃著：「全都是女生……」

想著「还不只这几个呢」的诗乃暗暗露出苦笑，然后穿越站在左右两边的少女之间，往马车深处前进。

那里可以看见一名坐在简朴轮椅上，用仅剩的一条手臂抱住两把长剑的黑衣年轻人。

比嘉健已经跟她说明过桐人的状态。但是看见他这种受伤的模样后，胸口还是涌起强烈的感情，双眼也跟著渗出眼泪。

「……啊…………」

空虚的眼睛虽然没有直视诗乃，但是却从稍微打开的嘴里发出细微的声音。站在过去的强敌兼战友，同时也是救命恩人的面前，诗乃静静地跪了下去。

剑士靠在轮椅椅背与扶手上的身体，瘦削到让人犹豫是不是能够直接触碰。诗乃把长弓放到马车的地板上，伸出双手温柔地把纤细的肩膀抱过来。

可以说是桐人的灵魂──摇光核心的「主体」，也就是Self-image似乎受到严重的损害。比嘉以沮丧的声音表示目前还找不到回复的手段。

但是诗乃一边用力眨眼让泪珠从脸颊滑落，一边在内心深处呢喃「那再简单不过了」。

像是与桐人待在一起时的回忆，以及对桐人的强烈心意，许多人心里，这些东西应该都多到快无法容纳了吧。只要把这些一点一点收集起来，放回桐人的心里就可以了。

──看，能感觉到吧……在我心中的你。喜欢讽刺、恶作剧，顽固又天真……同时也比任何人都强都温柔的你。

一瞬间甚至忘了在后面注视著这一切的亚丝娜，诗乃改变脸孔的方向，确实地把嘴唇印到桐人的脸颊上。

这个时候──

朝田诗乃不知道自己带著感伤的思考，已经极端接近让桐谷和人的灵魂复原的唯一方法了。

如果诗乃对于Underworld与摇光的构造有充分的知识，或许就能得到解答。但是诗乃在潜行之前接受的指导，仅限于世界的现状与索鲁斯帐号的使用方法。

因此她便没有追究嘴唇触碰到脸颊时和人稍微震动身体，以及传递过来的体温也微微上升的理由。

立刻把身体从桐人身上移开的诗乃，站起来看著背后的三个人。

「别担心，当大家真的需要桐人的时候，他马上会恢复健康了。」

亚丝娜和两名少女在含著泪水的情况下点了点头。

「那么……我先一步飞到南边的遗迹去确认地形。桐人就拜托你们了。」

诗乃这么搭话完就准备往马车后方走去──

这时亚丝娜突然用力抓住了她的肩膀。

看见她眼里透露出极为迫切的光芒，诗乃不由得屏住了呼吸。

「亚……亚丝娜，怎么……」

虽然一瞬间浮现「要逼问我为什么亲桐人吗」的想法，但是当然没有发生这种事情──

「诗……诗乃啊，你刚才说『飞』吗？你……你能飞吗？」

面对这急切的提问，感到困惑的诗乃点头回答：

「嗯……嗯。好像是索鲁斯帐号的专属能力。听说也没有任何时间限制……」

「这样的话，想请帮忙你拯救的不是我们！去追爱丽丝……去追被皇帝抓走的爱丽丝小姐吧！」

亚丝娜接下来说明的状况，比诗乃想像中还要来得紧急。

成为事件关键的整合骑士爱丽丝，被同样从现实世界使用超级帐号潜行至此的皇帝贝库达绑架，目前正乘著龙往遥远的南方飞去。现在只有叫作骑士长贝尔库利的剑士正在追赶贝库达。

「就算是骑士长先生，要独自面对使用超级帐号的对手恐怕还是力有未逮。如果没办法在皇帝到达世界尽头的祭坛前救出爱丽丝，这个世界就会整个被破坏掉。诗乃，拜托你，去帮助贝尔库利先生吧！」

好不容易了解整件事情，把骑士长贝尔库利的长相牢牢记住的诗乃，从马车直接升空之后就一口气拉高距离。

七百人界军就这样扬著土尘南下。

从北边以怒涛般速度追赶过来的红色军队，人数应该有他们的二十倍吧。

──救回爱丽丝后，我马上会赶回来，在那之前要加油啊……亚丝娜。

在内心如此对好友呼唤完之后，诗乃就转向南方，挤出全身的想像力来加速。她变成拖著长长尾巴的白色流星，撕裂红色天空往前飞翔。

诗乃俯瞰著眼睛下方那一片无尽的漆黑荒野，忽然想起一件事。

话说回来──

应该同时登入的莉法，到底跑到哪里去了呢？

3

美国人玩家追赶著整合骑士连利率领的人界军。

距离他们相当遥远的北方，在亚丝娜生成的峡谷南岸，伊斯卡恩和拳斗士团，以及整合骑士谢达正持续与目前仍剩下一万以上的红色军队苦战著。

这个战场的更加北方之处。

一个亚人伫立在可以眺望到残留鲜明激战痕迹的东大门的荒野中。

矮胖身体包裹在钢铁铠甲底下。皮革披风正随风飘荡。圆滚滚头部的两侧垂著薄薄的大耳朵，扁平的鼻子往正前方突出。

那是半兽人族的族长──利鲁匹林。

让仅剩的三千名士兵在后方待机，他独自走到能清楚看见东大门的地点。之所以连一名护卫都没带，是因为不想让人看见自己在地面到处爬的模样。

在沙地里挖了数个小时，利鲁匹林终于找到自己冀求的物体。那是施加了简朴雕刻的银制耳环。

静静捡起后放在手掌上的耳环，平常总是在接受皇帝命令，成为暗黑术祭品的半兽人族公主骑士莲茱的耳朵上闪闪发亮。

这是她唯一的遗物。荒野上不要说和公主一起死亡的三千半兽人兵的尸骸了，就连铠甲的碎片都没留下来。暗黑术师的恐怖邪术不只把半兽人们的肉体，甚至连装备都转换成暗黑力，然后一滴不剩地把它们用尽了。

至于行使那残酷至极术式的女术师蒂伊‧艾‧耶尔，以及下达命令的皇帝贝库达都已经不在这里了。

暗黑术师公会的总长蒂伊，被卷入进行反击的「光之巫女」那又恐怖又美丽的广范围攻击而死，皇帝则是追著巫女飞往南方去了。他甚至没有解除利鲁匹林的待机命令。

光靠残存的三千名半兽人兵，实在无法胜过守护东大门的人界军与整合骑士。暗黑界五族的悲愿，也就是征服人界的梦想已经破灭。

──这样的话。

到底是为了什么？

为什么利鲁匹林的青梅竹马莲茱，以及成为祭品的三千人，还有参加大门初战的两千名半兽人兵就得牺牲性命呢？他们的死又给暗黑界带来了什么呢？

答案是无。什么都没有。

只因为比人族丑这样的理由，多达五千名的同族平白地死亡。

利鲁匹林用双手把小耳环抱在胸前，颓然跪到地上。愤怒、不甘以及压倒性的悲哀涌上胸口，当这些感情就快要变成眼泪与呜咽──

在这之前……

背后就传来「咚滋」的轻响。

急忙站起身转过头的半兽人族长所看见的是，一屁股跌坐在地上而绷起脸的年轻人族女性。她有著光鲜的金发、透明般的白色肌肤，以及嫩草色的装束与金碧辉煌的铠甲……那不是暗黑界人。毫无疑问是人界人。

利鲁匹林率先感觉到的，不是对方唐突出现的惊讶，也不是对人族的愤怒，而是「不要看我」这种近似羞耻的感情。

这是因为眼前的女孩实在太美了。

首次近距离看见的白伊武姆年轻女性，和身材高大、魁梧，而且带著浅黑色肌肤的暗黑界人女性简直就像是不同种族一般。手脚像是轻碰一下就会折断一样纤细，头发在微弱日光下依然发出炫目的光辉，以惊讶表情笔直往上看的大眼睛，就像经过千锤百炼的翠玉一样。

利鲁匹林忍不住觉得这娇小又孱弱的生物美丽到令人发抖，而他也诅咒著产生这种感觉的自己。

同时也恐惧女孩的眼里立刻会充满厌恶的感情。

「别……别看！不要看我啊啊！」

他一边叫唤一边用左拳遮住自己的脸，右手则是握住了剑柄。

干脆在听见悲鸣之前，就先用剑砍下她的首级吧。

在冲动驱使下准备拔剑的瞬间，就感觉还握在左手的耳环刺了一下手掌。遭到简直就像被莲茱阻止的感觉打动，整个人倏然停止动作的利鲁匹林，耳朵听见出乎意料之外的声音──或许该说是发言。

「那个……午安。还是应该说早安呢？」

女孩以轻快的动作起身，一边拍了拍裤脚宽敞的短裤一面露出满脸笑容。

利鲁匹林从盖住脸的拳头后方，哑然往下看著这个娇小的女孩并且不停地眨眼。

女孩眼里看起来没有嫌恶或者侮蔑，甚至是任何的恐惧之意。对于白伊武姆的小孩子来说，暗黑领域的半兽人应该是食人的恶鬼才对啊。

「为……为什么？」

从嘴里流露出来的发言带著不知所措的感情，听起来完全不符合暗黑界十侯之一的身份。

「为什么不逃？为什么不发出悲鸣？你明明是人族，为什么会这样？」

结果这次换成女孩露出像是惊讶又像是困扰的表情。

「哪有为什么……因为……」

接著就像在说「大地是平的，天空是红的」一般，理所当然地继续表示：

「你也是人类吧？」

这个瞬间，利鲁匹林不知为何感觉背脊闪过一道深沉的震动。亚人族长依然用力握著大剑剑柄，难受地说道：

「人……人类？我吗？说什么蠢话，一看就知道吧！我是半兽人！被你们这些伊武姆咒骂是半人半猪的半兽人！」

「但还是人吧。」

女孩把手扠在纤细的腰上，宛如母亲在告诫小孩子般重复了一遍：

「因为，能够像这样对话不是吗？除此之外还需要什么？」

「你……你说什么…………」

利鲁匹林不知道该如何反驳她才好。绿色眼珠的少女充满自信所说出来的话，对于至今为止对人族充满劣等感与怨叹的半兽人族长来说实在太过于怪异了。

……能够说话就是人类？

「人类」的定义这么简单吗？如果会说话就行，那么哥布林、食人鬼、巨人族也都会说话。但是包含半兽人在内的四个种族，出生在暗黑界的时间点就被称为亚人，和人类之间有著不可抹灭的区隔。

少女用一句「这不重要啦」，就把呼吸急促呆立在现场的利鲁匹林内心感受的冲击与混乱赶走，她环视了一下周围并开口问：

「……这里是什么地方？」

＊＊＊

莉法/桐谷直叶推测自己出现在与原本座标有很大误差的地方，于是恨恨地往上看著红色天空。

听说被分配到的STL六号机是刚出厂，甚至连塑胶套都还没拆下来的新成品时就有种不祥的预感了。直叶绝对不会在比赛时使用新竹剑，同样也不会相信刚从盒子里拿出来的电子产品。不知道为什么，从以前就维持著抽中出厂不良品的超高中奖率。

由于设定的登入座标应该和进入旁边的STL试作一号机的诗乃一样，是先行进入Underworld的亚丝娜目前所在地，现在周围看不见她们的身影很明显是发生了什么错误。但是荒凉的原野上不是完全没有人，眼前就有一个圆滚滚身体以及脸孔与猪非常相像的类人类──也就是「半兽人」站在那里。

根据刚潜行时才有效的颜色浮标，可以知道眼前的半兽人并非目前的敌人，也就是美国的VRMMO玩家。他是生活在Underworld的「人工摇光」，亦即结衣口中所说的真正的Bottom-up型人工智慧。

在听到关于Underworld人的说明时，莉法就决定只要不是无论如何都一定得那么做的状况，自己都不会对他们拔剑了。

这是理所当然的事。怎么能够杀害哥哥桐人想要保护的人类呢。因为人工摇光在这个世界死亡后，灵魂就会完全消灭而再也无法复活。

不过话又说回来──

ALO在多数The Seed连结体中一向以最高水准的视觉影像为傲，而站在眼前的半兽人，真实程度连出身于该处的莉法都觉得震惊。像是粉红色大鼻子的动作与潮湿的模样，包裹巨大身躯的金属铠甲与皮革披风的质感都无可挑剔，而最重要的是小小黑色眼珠里浮现的丰富感情，在在显示出寄宿在深处的确实是无庸置疑的真正灵魂。

虽然先对不知道为什么感到畏缩般把脸别开的半兽人询问这里是何处，但是对方没有回答。想著那就从更基本的地方开始，于是莉法就开口提出另一个问题。

＊＊＊

「那个……你叫什么名字？」

陷入极端混乱当中的半兽人族长，反射性回答了白伊武姆女孩第二次提出的问题。自己被赋予的所有事物当中，或许只有名字是唯一不讨厌的吧。

「我……我叫利鲁匹林。」

自报姓名后马上就后悔了。利鲁匹林回想起很久以前，首次造访帝宫黑曜岩城时，听见自己名字的人族骑士与术师们开口大笑的事情。

但女孩还是露出满脸天真无邪的微笑，然后用清澈的声音重复了一遍利鲁匹林这个名字。

「利鲁匹林……真好听的名字。我叫莉法。初次见面，请多指教。」

下一刻，对方就做出不知道第几次令人惊讶的举动。

她笔直地伸出柔嫩雪白的右手。

利鲁匹林当然知道握手这种打招呼的方式，半兽人之间也经常这么做。但是之前从未听过伊武姆与半兽人握手这种事情。

──这个人类究竟是怎么回事？这是什么陷阱吗，还是术师干的好事？自己是什么时候中了幻惑术呢？

利鲁匹林只能凝视著伸出来的小手发出低吟，女孩也整整看著他将近十秒钟，最后才像有点丧气般把手放了下去。不知道为什么，那种模样让利鲁匹林的心底深处刺痛了一下。

继续和这个女孩说话的话……不对，光是看著她，脑袋似乎就要烧掉了。利鲁匹林虽然已经没有砍杀女孩的想法，但是决定采取除此之外最不必使用头脑的解决方法，于是开口说道：

「你是……人界军的卫士，不对，是骑士吧。这样的话，你将成为我的俘虏。我要把你带到皇帝那里去！」

年纪虽然轻，但女孩装备的铠甲与左腰上的长剑，怎么看都不会是给予一介士兵的物品。从精致的雕工与绽放出来的炫目光辉来看，应该比利鲁匹林的装备还要高级许多。

听见利鲁匹林的大嗓门，女孩依然没有露出任何惧怕的模样，只是像在考虑什么事情一样，最后她轻轻耸了耸肩并询问：

「你说的皇帝，指的是暗神贝库达吧？」

「没……没错。」

「我知道了。那你就把我带到皇帝那里去吧。」

女孩点点头，然后把握拳的双手一口气往前伸。再次疑惑了一阵子后，才了解那不是握手而是催促自己把她绑起来的动作。

──真的没有任何企图吗？

利鲁匹林从腰带上拉出一条装饰用绳子，粗暴──但是稍微放松了一些来绑住少女的双手。当他握住绳子的一端并用力一拉后，才终于想起皇帝已经不在暗黑界军的大本营里了。

但是继续思考更困难的事情，脑袋的中心似乎就要烧起来了。就算皇帝不在，身为副官的那个行为轻挑的黑骑士，或者商人公会的会长连基尔应该会代为做出处置吧。

利鲁匹林随即转过身子，稍微放轻力道来一边拉著绳子一边往前走，短短几秒钟后──

周围忽然出现一整片黑色霭气般的物体。还有令人厌恶的气味刺激著鼻子。视界立刻看不见任何东西，利鲁匹林开始小心翼翼地环视著周围。

「啊……！」

发出简短惊叫声的，无疑是那名自称莉法的女孩。

迅速回头的利鲁匹林看见的是，浓密霭气深处忽然伸出的一条手臂，抓住莉法绑起来的头发粗暴地往上拉的光景。

下一刻，手臂的主人就撕裂霭气现出身形。

站在该处的那名应该已经死亡的女人──暗黑术师公会总长蒂伊‧艾‧耶尔，红色嘴唇正露出冷酷的笑容。

＊＊＊

为什么会追不上？

整合骑士长贝尔库利，同时感到焦躁与惊讶。

利用三头飞龙的追踪已经持续了两个小时以上。

飞越人界守备军野营的森林，以及其南方那一片广大的圆形洼地，通过奇怪巨像林立的遗迹，即使前所未见地深入黑暗领域南部，与敌人的距离还是简直没有缩短的迹象。皇帝贝库达绑架心爱弟子整合骑士爱丽丝的飞龙，依然是浮在地平线上的一个极小黑点。

皇帝只有一头飞龙，而且是负载他自己以及爱丽丝等两个人来飞翔。

相对地贝尔库利是轮流骑乘星咬、雨缘以及泷刳这三头飞龙，尽可能地减少了飞龙们的疲劳。理论上来说，应该快要追上对方了才对。

到底为什么会追不上？皇帝能够自由操纵飞龙的天命吗？

不可能有这种事情。天命的直接操纵，是连最高司祭亚多米尼史特蕾达都无法办到的最大禁忌不是吗？

再怎么样，也不可能照目前的速度无限地飞下去吧。在到达黑暗领域最南端的世界尽头的祭坛之前，最少也得让飞龙休息两次才行。但是贝尔库利乘坐的飞龙也同样得休息。如果速度一样的话，距离永远不会缩短。

看来──没办法了。

毕竟贝尔库利无法操纵射程到达地平线彼方的术式。要说能够打破现状的可能性的话，那唯一就只有……

骑士长用右手轻轻地抚摸左腰上的爱剑。

冰冷、坚硬又令人安心的手感。但是光靠感觉就能知道，距离剑的天命完全回复还有一段遥远的距离。在东大门使用的大规模武装完全支配术的消耗比想像中要大得多。

贝尔库利接下来要使用的术式，算是神器「时穿剑」的最终奥义，所以将消耗掉庞大的天命。

能使用的次数只有一次。必须以超过穿越针孔以上的精密度让这一击命中才行。

贝尔库利轻轻拍打骑乘的泷刳脖子来慰劳它的辛苦，接著轻巧地跳到星咬的背上。

长年与自己共同作战的搭档，不用握住缰绳就能了解自己的意思，开始慎重地调整高度。

瞄准的是遥远地平线上渗出的沙粒般黑点。

虽然很想直接瞄准皇帝本人，但在看不见对方模样的这个距离下，失手的危险性太高了。所以他就把所有精神集中在好不容易能看见动作的黑色飞龙单边羽翼上。

像门神般站在鞍上的贝尔库利，右手缓缓动了起来。

从长期使用的皮革剑鞘当中流畅地拔出全体由同一素材打造的长剑。

在身体右侧竖立起来的钢铁剑身带著些许光芒。没有任何句式就发动了记忆解放术。如热蒸气般摇晃的长剑，随著飞龙的前进在后方留下无数残像。

刚毅的嘴角简短地动了一下，对著没有罪过的龙呢喃歉意。

下一刻，淡蓝色眼睛瞬间眯起──世界上最古老的骑士贝尔库利以撕裂绵帛般的吼叫声喊著：

「时穿剑──里斩！」

长剑「滋」一声以沉重但猛烈的速度挥落。蓝色残像沿著斩击的轨道发出无数光辉然后依序消失。

远方的空中，皇帝贝库达骑乘的黑龙，左翼就这样无声地被从底部切断了。

＊＊＊

「闻得到……闻得到啊……竟然有如此甜美的天命香味…………」

抓住人族女孩的头发，把她的身体整个吊在空中的蒂伊‧艾‧耶尔，从嘴唇里掉出零碎的声音。

对利鲁匹林来说，她应该是可恨到了极点的暗黑术师，但利鲁匹林这时却只能茫然看著她的身影。

涂了香油而发出光亮的浅黑色肌肤、奢华的波浪状漆黑头发现在全都惨不忍睹。全身就像是被锐利刀刃割过一样伤痕累累，而且不停地渗出血水。每当蒂伊的身体一动，各处的伤口就会裂开并迸出鲜血。但是缠在术师身上的黑色霭气立刻聚集在伤口上，咻一声散发出令人厌恶的臭味并且帮忙止血。

霭气的来源是挂在蒂伊腰间的小皮袋。仔细一看就能发现，袋口不时会有虫子般奇怪生物露出脸来然后吐出一大堆黑色霭气。这一定是抑制天命减少的暗黑术。

瞄了一眼因为过于厌恶而皱起鼻子的利鲁匹林，蒂伊嘴唇的两端就再次上扬。

「抓到了很棒的猎物嘛。干得好啊，猪猡。就让你看点好东西作为奖赏吧。」

当蒂伊刚用沙哑的声音这么说完──

她钩爪般的右手手指就陷入被吊在空中而露出痛苦表情的女孩衣领里面。

银色铠甲以及下面的嫩草色上衣一瞬间被拉下来掉到了地面。

炫目的白色肌肤外露，让女孩的脸部更加扭曲。这种模样让蒂伊露出残虐的笑容，并且发出「咻咻」的笑声。

「怎么样啊，还是第一次看见人族女孩的身体吧？对于猪猡来说，应该是巴不得想看到吧。不过，有趣的现在才要开始哟…………！」

蒂伊右手的五指忽然像没有骨头一样蠢动著。

不知不觉间，它们不再是手指，而是变成像细长的虫一样。前端张开了细细牙齿排成一圈的嘴巴，然后不停恶心地蠕动著。

「看哟……！」

蒂伊大叫的同时，五根手指──不对，五只长虫就伸长了几十倍，将女孩的身体卷了起来。一封住对方的行动，前端就弯曲成镰刀状，头部像要从肌肤各处钻进去一样咬住女孩。

「啊啊……！」

大量的鲜血飞溅，名为莉法的女孩瞪大绿色眼睛发出细微的悲鸣。虽然动著手想要把长虫撕下来，但因为上半身被层层卷住，手腕又被利鲁匹林的装饰绳绑起来，所以根本无法动弹。

从五处伤口喷出的血似乎一瞬间就止住了。但利鲁匹林察觉实际上并非如此，而是连结著蒂伊右手的长虫正在喝女孩的血。

暗黑术师仰起喉咙，以尖锐的声音咏唱著术式：

「System call！Transfer human unit durability……right to self！」

「啵 」一声，女孩的伤口出现蓝色光辉。光辉就像配合血液的流动般传递到长虫上，最后被吸进蒂伊的手里。女孩变得更加苦闷，纤细的身体往后仰到像快要折断了一样。

「哈啊……太棒了……太棒了！竟然这么浓稠……甘甜！」

摩擦金属般尖锐的声音贯穿利鲁匹林的耳朵。

因为这样的疼痛而回过神来的半兽人族长痛苦地大叫：

「你……你做什么！那个女孩是我的俘虏！我要带到皇帝身边去！」

「给我安静，这只臭猪！」

蒂伊瞪大布满血丝的双眼，然后以极度疯狂的声音叫唤著。

「你忘了皇帝把作战的指挥全权交由我来负责了吗！我的意志就是皇帝的意志！我的命令就是皇帝的命令！」

「咕」一声，利鲁匹林的喉咙被堵住了。

「你说的作战老早以前就失败了吧」，这样的反驳涌到了他的喉头。但是，皇帝没有留下任何命令就从战场上消失了。这样的话，就没有足够的证据能够颠覆蒂伊所有命令依然照旧的主张。

无法动弹的利鲁匹林眼前，持续发出细微悲鸣的人族女孩动作越来越微弱。另一方面，刻划在蒂伊肌肤上的无数伤痕则是从一端开始痊愈并且逐渐消失。

「咕……咕咕……」

从咬紧的牙关当中发出被压扁般的呻吟。

曾几何时，利鲁匹林的眼里，女孩被吸取天命的样子，就跟公主骑士成为祭品而丧命时的模样重叠在一起。

女孩眼睛里的光辉开始变淡。肌肤的颜色早已白得发青，双臂也是无力地往下垂。但是蒂伊右手的长虫像仍不知满足般蠢动著，准备把对方的血吸得一滴不剩。

会死……会死掉啊。

难得抓到的俘虏……

不对，应该说第一次看见自己也不害怕或者鄙视的人类。

就在这个时候──

发生了令人惊愕的现象，让利鲁匹林瞪大了双眼。

地面……暗黑领域像炭灰般的黑色不毛大地，从被吊起的女孩脚边发出绿色光芒。

应该只在极有限地域才能看见的柔软嫩草一起发芽，此外还开起了无数各种颜色的小花。空气中飘荡清凉的芳香，就连血色的阳光都变成安稳的乳白色。

从小片草地上升起的浓密天命，一边旋转一边被吸进女孩的身体里面。

苍白的肌肤立刻恢复血色，瞳孔也再次出现光辉。

当地面的绿色消散，太阳也恢复原本的颜色时，利鲁匹林直觉女孩的天命已经完全恢复了。他的胸口立刻充满理当不会出现的放心感。

但是，这样的感觉立刻就被撕裂了。

「竟然会这样……涌出来了……又涌出来了啊啊啊！」

这时伤痕几乎完全痊愈的蒂伊，再次用刺耳的尖锐声音叫唤著。

她移开抓住女孩头发的左手，同时手指也转变成丑恶的长虫。

钝重、潮湿的声音过后，新出现的五只触手就刺进女孩的肌肤当中。

「呜……啊啊啊……！！」

再次发出的悲鸣被蒂伊的哄笑声掩盖过去。

「啊哈哈哈哈！啊──哈哈哈哈哈哈！是我的……！这是我的哟────！」

＊＊＊

──必须撑下去。

不论是现实世界还是ALO里都从未体验过这种令人目眩的剧痛，而莉法就在这样的煎熬中持续地想著这件事。

潜行之前已经听过赋予超级帐号03「地神提拉利亚」的能力。那是「无限制自动回复」。自动从周围的广泛空间吸取能源，然后回复自己以及其他动态、静态物体的耐久度。原本就拥有庞大HP数值的帐号再加上这样的能力，几乎不可能因为HP的减少而死亡，叫作比嘉的技术者这么表示。

正因为如此，莉法才会甘冒成为俘虏的危险来抢先与暗神贝库达碰面，希望能够与他对战，同时也是因此而决定绝对不对Underworld人拔剑。

现在绑缚莉法，给予她激烈痛苦的女性也和利鲁匹林同样是Underworld人──也就是人工摇光。用剑斩杀的话，她的灵魂就会完全消灭。在不知道她为什么受伤并且想要回复的情况下，实在没办法与她战斗。

啊啊，但是……

天命被吸取的压倒性疼痛感，已经让上半身衣服几乎都被剥光的自己连感到羞耻的心思都没有了。

这真的是与现实的肉体分离的虚拟感觉吗？

＊＊＊

「……住手。」

利鲁匹林无法立刻发觉那是来自于自己口中的发言。

但他随即确实地张开嘴巴，震动著喉咙说：

「快住手！」

瞳孔缩得跟针孔一样细的蒂伊，这时用眼睛狠狠瞪著利鲁匹林。半兽人族长忍受从腹部底端涌上来的寒气继续表示：

「你的天命已经完全回复了吧。没有必要继续从这个伊武姆身上吸取天命了才对！」

「……你这是什么意思，是在命令我吗～……？」

蒂伊加上走音歌曲般的抑扬顿挫后这么呢喃著。

这段期间十只触手也剧烈蠢动，持续绑紧女孩的肌肤贪婪地吸著血。暗黑术师的伤口完全愈合，肌肤取回涂了油般的光泽，黑发也长得比过去还要茂密。

甚至还有剩余的天命化成蓝色光粒从她全身发散到空中。但是蒂伊依然用邪术捆绑比自己娇小许多的女孩，也不停止继续虐待对方。

「我说过了吧，猪猡。这个俘虏已经是我的了。我要吸取多少天命，在猪猡面前侮辱她，或者当场勒死她都和你没有关系吧？」

蒂伊从喉咙深处发出「咕咕、咕咕咕」的沉闷笑声。

「嗯……不过，说得也是喔。人是你找到的，我是不是该稍微有点让步呢？想要我让步的话……你现在就在这里脱光吧。」

「你……你在说什么啊……」

「我呢，打从第一次看见时，就觉得你穿著那种夸张的铠甲和披风真的很恶心。明明是只猪，为什么打扮得跟人一样呢？在这里乖乖地脱光，趴在地上发出猪叫声的话，说不定我就会把这个女孩子还给你哟。」

刺痛。

视界的右半部突然闪著红光。同时有铁针从右眼深深插入般的疼痛贯穿头部。

──明明是只猪。

──像人一样。

蒂伊的发言与名叫莉法的少女所说的话重叠在一起。

──你也是人类吧？

──除此之外还需要什么？

不能让蒂伊杀了这个女孩。不对，是不想让她杀掉。只要能办到这一点……只要能办到这一点……

利鲁匹林的右手抓住皮革披风的环扣。然后啪叽一声把它撕裂。

披风掉落到地面后，利鲁匹林继续把手放到铠甲的皮带上。

忽然可以听见细微的声音。

「……住手。」

瞬间抬起头来，就和笔直看著自己的莉法眼神相交。

因为疼痛而含著眼泪的翠玉眼珠，缓缓地左右晃了晃。

「我……不要紧。所以，不要做这种……」

声音无法持续到最后。蒂伊突然伸长了脖子，用牙齿轻咬住女孩的脸颊。

「再说些无聊的话，我就要咬破你可爱的脸蛋喽。难得可以看见有趣的表演。喂，你是怎么了，猪猡。快点脱啊。还是说因为人族的裸体而兴奋起来啦？」

「呀哈哈哈哈」的尖厉笑声持续著。

利鲁匹林握住铠甲皮带的手不停发著抖。

右眼的疼痛完全没有止歇的迹象。但是，和在胸中肆虐的愤怒与屈辱比起来，那点痛楚已经不算什么了。

「我……我……我……」

突然有液体从双眼溢出并顺著脸颊滴落。从脸庞左边滴落的是透明的水珠，右边的却是呈深红色。

右手从皮带上离开──朝著左腰上的剑伸去。

「我是人类啊！」

大叫的同时，至今为止最为强烈的痛楚袭击右眼，眼球啪擦一声从内部破裂。

利鲁匹林减半的视界边缘确实持续捕捉著蒂伊的身影。这时女术师残虐的笑声中断，嘴巴茫然张开。

利鲁匹林冷不防地对著蒂伊毫无防备的双脚发动全力攻击。

但是因为一只眼睛才刚消失，所以距离感产生了紊乱。

剑尖只稍微擦过蒂伊右脚脚踝，接著利鲁匹林就失去平衡，从左肩倒到地面。

抬头一看，露出穷凶恶极模样的蒂伊‧艾‧耶尔正扭曲著嘴唇丢出这句话：

「臭猪猡……竟然敢伤害我……！」

蒂伊把女孩的身体丢到后方接著高举起双手。十只触手「锵」一声发出坚硬的声音，瞬间变成发出乌光的十把刀刃。

「把你切成碎片后混著稻草拿去当山猪的饲料！」

半兽人族长只能等待整个往左右两边扩展开来的刀刃落下。

咚。

咚嗯。

两声细微的声音几乎是同时响起。蒂伊的动作瞬间停止。

术师的双臂从肩膀以下整个与身体分离，发出钝重的声音滚落在地面，而利鲁匹林只能茫然眺望著这一切。

蒂伊本人同样也浮现出惊愕的表情。左右两边的肩膀撒出瀑布般的鲜血，高挑的术师缓缓改变身体的方向。

莉法发出白色光辉的模样映入利鲁匹林的眼帘。

以那副几乎看不到什么肌肉的纤细身体几乎无法操纵的长剑已经往前挥落。双手手腕明明还被装饰绳绑住，但是这个女孩很明显瞬时砍断了蒂伊的双臂。

蒂伊以沙哑的声音说：

「人族……为了救一只猪而砍了人……？」

坚定地看著像要表示难以置信而不停摇著头的暗黑术师，莉法这么回答她。

「你错了。是为了帮助人而斩杀邪恶。」

她随即以流畅的动作把长剑举到上段。

咻喀。

女孩从看起来实在不像能命中的距离挥出斩击。

竟然──有如此美丽的动作。

从两手手指到双脚脚尖都没有使用任何多余的力量，但速度却快得吓人。这是经过千锤百炼的极限之技。

利鲁匹林因为再次浮现──不过这次是感动的泪水而模糊的视界里，最强暗黑术师同时也是十侯最强实力者的蒂伊‧艾‧耶尔，躯体就从脑袋开始无声地垂直裂成两半。

4

黑色飞龙挤出最后的力量用单边羽翼缓慢著陆之后，就轻叫一声并咽下最后一口气，而加百列‧米勒只是毫无感动地低头看著它。

当他移开视线时，龙的存在已经完全从记忆与思考当中排除。表情没有变化的他环视了一下周围。

坠落的地点是排列著无数圆柱状怪石的区域当中，几乎是耸立在中央的一根岩石顶端。高度大概是一百码（约九十公尺），直径也应该有三十码（约二十七公尺）左右。

直接跳下去可能有点太鲁莽了。这个世界的生成素因并加以操作的魔术也很难说已经熟习。当然更不可能丢下脚边依然失去意识横躺在地上的光之巫女爱丽丝。

如果有坚固的绳子、锚钉以及安全环的话，即使在现实世界加百列也很容易就能用绕绳下降的方式克服这种程度的山壁，但现在没有必要勉强从山壁上下去。因为不知道用什么手段击坠加百列的敌人，正伴随著三只飞龙从北边往这里靠近。处理完敌人，然后再支配新飞龙的AI，接著再南下就可以了。

把视线移往正上方。贴在红色天空上的虚拟太阳，这时已经升到相当高的地方。

距离克里达再次开始时间加速应该没剩下多少时间了。问题是投入战场的美国人封测玩家能不能在被再次加速踢出Underworld前歼灭人界军，不过封测玩家的人数多达五万人。应该只剩下不到千人的人界军，不可能做出什么像样的抵抗。

真要说有什么不确定的要素的话，果然还是那些叫作整合骑士的家伙吧，怎么说他们也击退了占压倒性多数的暗黑界军。不过其中一分子爱丽丝已经像这样落入自己手中，接近中的追踪者应该也是骑士才对。留在北方战场上的最多也只有一个或两个人。

判断问题大概都已经克服之后，加百列最后再次眺望著躺在地上的整合骑士爱丽丝。

仔细看后就觉得──真的非常美丽。

几乎让加百列无法抑制在内心深处蠢动的兴奋。

为了预防她醒过来，加百列有些犹豫是不是该完全解除她的武装并且确实地捆绑住比较好。就合理的判断来说当然应该这么做，但在敌人逼近的情况中，以慌乱的手法对待这样的美少女实在令人感到犹豫。

果然还是等再次时间加速后再仔细地作业。即使只是解开铠甲的带扣，也要用优美、严肃且具象征性的动作才行。

「……暂时这样睡下去吧，爱丽丝……爱丽西亚。」

温柔地这么搭话完，加百列就为了迎击敌人而走向桌子状的岩山中央。

不论是使用超级帐号04「暗神贝库达」的加百列‧米勒，或者是发现帐号的克里达都不清楚原因，不过最强等级的整合骑士爱丽丝之所以被飞龙一踢就昏过去数个小时都没醒过来，完全是因为附加在贝库达身上的特殊能力所造成。

设定在Underworld里的四种超级帐号，是为了各自能对世界与居民行使神迹般的直接操作而存在。

实行改变地形的史提西亚。

破坏动态个体的索鲁斯。

回复物体耐久度的提拉利亚。

而贝库达的操作对象则是居民，也就是人工摇光。

具体来说是居民们的记忆──亦即改变摇光中的动态记忆，重新配置在遥远的地点，让他建立新的家庭。

就行为来说是以掳走居民的形式，所以和其他三神不同，比较难成为信仰的对象。因此除了有最高优先度的装备与最大的天命数值之外，还施加了「不会成为术式的对象」这种强力的保护。Underworld人以童话的形式流传下来的「贝库达的肉票」，就是源自于过去进行过的居民操作。

而暗神贝库达的能力在加上加百列‧米勒特异的想像力，也就是心念后，就产生了连RATH技术人员都无法预测的加乘效果。

不用行使术式就能吸取人的意志。

爱丽丝人工摇光的活力暂时被夺走，所以陷入强制的昏睡状态。

过去之所以能够完全吸收暗黑将军夏斯达的必杀心念，也是因为贝库达与加百列的力量互相融合的缘故。

而现在，夏斯达长年的宿敌，整合骑士长贝尔库利也正被导向同样的结局。

＊＊＊

贝尔库利看见了敌人皇帝的飞龙坠落在无法立刻脱逃的高大岩山上。

他随即用气力甩开使用绝技后产生的强烈疲劳感。

「很好……再飞一下子就可以了，星咬、雨缘、泷刳，拜托你们了！」

贝尔库利刚这么叫，三头龙就更用力拍打翅膀来加快速度。只要敌人静止不动，十基洛尔的距离对于飞龙来说，只不过一眨眼的时间就能飞抵。

贝尔库利把战斗前仅剩的一点时间用在近似于冥想的思考上。今天早上作过的梦鲜明地在他脑袋里复苏。

──曾经有过死亡的预感吗？

在梦中这么说的最高司祭亚多米尼史特蕾达，对于和她认识了几百年的贝尔库利来说，到最后都还是充满谜团的存在。

从冻结处理中被解放出来，再由爱丽斯那里得知最高司祭的死亡时，贝尔库利并不觉得特别惊讶。大概就只有「长时间以来辛苦你了」这样的感慨。反而是元老长裘迪鲁金的死让他比较讶异。

所以他也没有特别向爱丽丝询问亚多米尼史特蕾达最后的战役与死亡的模样。有一部分是因为忙于突然就加诸到自己双肩上的人界防卫的重任，感觉也有一部分是因为自己不想知道那个银发银眼的半神人，欲望、执著与罪业究竟有多深重。

对于贝尔库利来说，亚多米尼史特蕾达是一直那么慵懒、没耐性又善变的公主。虽然服从于她，但不像裘迪鲁金那样认真地崇拜这个人。

但是──

自己绝不讨厌作为她手下这件事。

「没错……只有这一点，你一定要相信我。」

呢喃完后，最古老的骑士就瞬间瞪大双眼。

可以清楚地看见横躺在岩山上的爱丽丝身上的黄金铠甲，以及她前方像条影子般静静站在那里的皇帝贝库达。

「好……你们在上空待机！如果我被干掉，就回北边去和部队会合！」

低声对三头龙做出指示，接著贝尔库利就从星咬背上轻轻跳了下去。

＊＊＊

像要追踪留下流星般白光轨迹而飞走的诗乃一样，七百名人界军拚命地持续往南前进。

从后方踩出地鸣追上来的红色军团逐渐地被拉开距离。但是卫士们的马也无法一直这样跑下去。

亚丝娜站在载著桐人、缇洁与罗妮耶的马车屋顶，像祈祷般持续凝视著南边。

前进了二十分钟左右，正如诗乃所说的，地平线上浮现类似巨大神殿的遗迹影子。

没有包含人类和亚人在内的巨大生物的气息。只有风化的石头静静沉睡于此。

笔直延伸的道路两旁，躺著两栋平坦的神殿。高度大概是二十公尺左右，而一栋的宽度则有三百公尺以上吧。作为防止敌军包围的障蔽来说，已经是相当充足的规模。

道路穿越两栋神殿中间直接往南方延伸。之所以给人参拜道路的印象，是因为道路两侧并排著几尊奇怪的巨像。

那不是东洋风的佛像，也不是西洋风的神像。真要说的话，是让人联想到南美遗迹的低矮四角外型。脸上雕刻了正圆形的眼睛与巨大嘴巴，短短的手在胸前合十。

那是在设计Underworld时，RATH的工程师们所设计的吗，还是The Seed program自动生成的呢？

又或者是──过去在此地生活的暗黑领域种族，从岩山上雕出来的呢？比如说，作为要献给死者的巨大墓碑……？

亚丝娜以简短的吐息来屏除不祥的思考。

这时骑士连利正坐在跑在部队前头的飞龙背上，亚丝娜便大声对他传达讯息：

「在那条参拜道路的中段迎击敌人吧！」

立刻有「知道了！」的声音回传。

几分钟后，部队没有减慢速度就冲进神殿包夹下的道路。四角形巨大神像从左右两侧默默地往下看。马蹄和卫士的靴子踩在从土壤变成石板的地面后发出坚硬声响。

连利撕裂冰冷的空气，以雄赳赳的声音命令：

「好了，前卫部队分为左右两边停下来！让马车队与后卫部队通过！」

八台马车走过迅速分开的前卫中间，以修道士为主的后卫也跟在马车后面，来到参拜道路最深处就停下脚步。从设置在那里的大门咻一声吹过的干燥风摇晃著亚丝娜的头发。

寂静只维持了极短暂的时间。美国人玩家的大部队踩出的轰隆地鸣传到参拜道路，左右神像上纷纷落下细微的沙子。

亚丝娜一从马车上跳下来，就对从车蓬内侧露出脸的少女们，以及站在旁边的女性剑士搭话道：

「这就是最后的战役了。桐人就拜托你们了。」

「好的！请交给我们吧，亚丝娜大人！」

「我一定会保护他！」

「──不惜牺牲性命也会完成使命。」

罗妮耶、缇洁与索尔缇莉娜握紧拳头靠在胸口，亚丝娜一边以同样的动作回礼，一边报以短暂的微笑。

「别担心，绝对不会让敌人通过这里的。」

这句话有一半是对自己所说。亚丝娜轻挥张开的右手，接著转过身子。

连利正在前卫部队的前头俐落地配置卫士。

参拜道路的宽度大约有二十公尺。对于守军来说有点太宽了，但是以这样的人数来完全抵挡敌军并且进行部队轮值并非完全不可能。

一切就看能不能在退到后方的修道士们行使支援魔法的期间，尽力抑制牺牲者并削减这一万数千名敌人了。幸好红色步兵里完全看不见魔术师的身影。应该是判断短时间内不可能让玩家们学会Underworld神圣术的复杂指令系统吧，总之这种状况对己方相当有利。

到了紧要关头──

靠我一个人也要干掉敌人全军。

亚丝娜大大吸了一口气，然后把它和决心一起存在身体底部。

只要有史提西亚庞大的天命与最高优先度的装备，应该就不会被数值上的伤害累积所打倒。问题是能不能承受受伤时那种恐怖的剧痛一直到战斗结束。心灵要是输给疼痛的话身体也会受到沉重的伤害，虽然还能够活命，但是会露出无法拿剑作战的狼狈模样。

亚丝娜闭上眼睛，想著受伤的桐人。想著他承受的疼痛以及背负的悲伤有多大。

再次往前走时，她的心里已经没有一丝恐惧。

这场战争里，应该是最后的大规模激斗就在高高升上天空的太阳底下开始了。

为了追求宣传网站里保证会出现的真正血腥与悲鸣，二十人左右的重武装美国人玩家率先冲进遗迹的参拜道路。

但是迎击他们的，并非无视分级来提供他们娱乐的可怜NPC。而是内心决定要拯救世界以及敬爱的黄金整合骑士的真正勇士们。握著的剑虽然已经伤痕累累，却因为坚定的意志力而充满光辉，它们确实挡下了敌人的武器，并且摧毁对方的铠甲。

这时有一道人影从高处往下看著单方面被歼灭的红色铠甲玩家们。

将金属铠甲减低到极限，上下穿著赛车服般紧身黑色皮革服装。乌亮的皮革所到之处全打著消光银制铆钉。

武器只有挂在左腰上那把宛如中式菜刀般的大型刀具。目前看不见他的长相。因为他罩著一件近似雨衣，同样也是皮革制的斗篷，而且把兜帽拉下来盖住整张脸。

稍微露出来的嘴唇上浮著扭曲到极限的笑容。

瓦沙克‧卡萨鲁斯。

再次登入Underworld的他，之后轻松地避开诗乃施放的广范围雷射攻击，然后混在美国人当中追赶人界军诱饵部队。但是他不参加初期的突击，灵活地爬上西侧神殿的墙壁后，站到神像头部这个能俯视战线的位置，决心从这个特等席欣赏这场表演。

「呵呵，那个女的还是一样抓狂就下手不留情。杀吧杀吧。」

像是无法压抑愉悦的心情一般，一边摇晃肩膀一边这么呢喃。

眼睛下方的远处，身穿珍珠色铠甲，栗色头发随风飘扬的少女剑士──「闪光」亚丝娜正如同瓦沙克遥远记忆里的模样一样，右手上的细剑刺出令人眼花撩乱的攻击。

那个时候，瓦沙克也一样隐藏身形眺望著亚丝娜的战斗。然后一边在内心坚定地发誓「世界终结之前一定要干掉你」。

当然是连在她身边展现更猛烈战斗模样的黑衣剑士也一起干掉。

＊＊＊

从骑乘的龙背上跳下来时，贝尔库利脚下还有将近两百梅尔左右的空间。直接这样落下的话，就算是他也无法承受剧烈撞上岩山时的冲击。

但是骑士长就像是空中有透明阶梯存在般，一边划著螺旋轨道一边从空中跑下来。

实际上，他每一步都在脚底下生成风素并且将它炸裂，藉由产生的反作用力才减缓降落的速度。他早在好几十年前就从元老长裘迪鲁金身上偷学到把脚也变成素因控制媒介的秘术。

皇帝贝库达就站在遥远下方宛如人造高塔的岩山上，最古老的骑士这时一边尽力往对方的视界之外跳跃，一边把手放到爱剑的剑柄上。

──第一击就要决胜负。

这是一百五十年前斩杀上上一任暗黑将军之后，整合骑士长贝尔库利再次凝聚必杀的心念。经过如此漫长的一段时间，都没有出现能唤起他纯粹杀意的敌人了。

在中央圣堂里，名为尤吉欧的年轻人独自挑战了贝尔库利。在那场战斗当中，贝尔库利虽然认真与他对战，但还是没有浮现杀气。不对，真要说的话，就连对长年的宿敌暗黑将军，他都没有抱持过愤怒与憎恨等负面的心念。

也就是说，贝尔库利在漫长的生涯当中，这还是首次在爱剑的剑刃上灌注真正的怒气。

他确实生气了。打从心底产生激烈的怒气。不只是因为爱丽丝被绑架的缘故。

从名为现实世界的外面世界而来的外人，让原本可能订定和平条约的暗黑界人上战场，平白无故地牺牲了数万条生命。这对持续守护这个世界两百年以上的贝尔库利来说，是无论如何都无法饶恕的罪行。

──皇帝贝库达，我不知道是什么理由让你这么做。

但是，看见那个叫作亚丝娜的女孩，就知道现实世界人并非每一个都是像你这样的恶鬼。

也就是说，你这家伙身为人类的本质，早就是无可救药的恶劣了。

这样的话，就接受你该有的报应吧。

让你知道暗黑将军夏斯达、整合骑士艾尔多利耶，以及在战场上丧生的许多人，其生命究竟有多重。

就用这一击……让你彻底了解！

「喝……啊啊！」

在高度十梅尔处踩完最后一步，骑士长贝尔库利将灌注了全身意志的斩击朝著皇帝贝库达毫无防备的脑门挥落。

燃烧起来的大气发出白色光芒。剑刃产生出来的光线过于强烈，让整个世界失去了颜色。

这无疑是过去出现在Underworld的所有剑技当中，内含了最大等级威力的一击。Main Visualizer内的泛用视觉化记忆档案覆写优先权，甚至超越系统控制命令的档案，也就是足以让数值能力无效化的，名符其实的必杀一击。

甚至能够消除设定在超级帐号04──暗神贝库达身上，几乎等于无限大的天命数值。

不过那是在能命中的情况下。

即使注意到致死流星从天而降的瞬间，贝库达的表情也没有任何改变。

那是最多只能抬头往上看的超快速剑技。不论任何反应、应对，应该都不可能避开那个剎那。

贝库达包裹在黑水晶铠甲里的身体轻轻往旁边滑开。

往唯一可能避开的方向，千钧一发下能够避开的距离移去。

贝尔库利的剑只能碰到随风飘扬的红色披风。外围的皮毛以及厚厚的布料，全都分解成细微的粉尘──

随著「滋喀────！」的雷鸣般巨响，坚硬的岩山顶端被刻划出深邃的伤痕。整座巨大的岩山都产生震动，有几块岩块从侧面剥落。

──能躲过这样的一击吗？

即使瞠目结舌，贝尔库利的身体还是没有停下任何一秒钟。他早就已经脱离在战斗中遇见突发状况思考就因此而停滞的阶段。

他最后再次踢了一下空气，一边绕到皇帝侧面一边著地。立即又发出一记横扫。即使灌注全身精力的大技挥空，他也花不到半秒钟就发动下一道攻击。

但贝库达就连这记追击都避开了。

简直就像被风吹走的烟一般，没有任何准备动作就轻轻在地面滑行。剑尖只扫过铠甲表面，爆散出无谓的火花。

但是……

贝尔库利这次确定自己已经获胜了。

从上空施放出来的那记用尽全力的初击，并没有因为挥空就消失。他已经发动爱剑的武装完全支配术「时穿剑‧空斩」──亦即「斩断未来」的力量。也就是在中央圣堂的战斗里让尤吉欧陷入苦战，只有斩击的威力留在轨道上，碰到该处的人将被透明剑刃砍倒的绝技。

皇帝贝库达由背部开始被吸进无法认知的斩击滞留的空间。

一开始时，他奢华的白金色头发「啪」一声散开。

戴在额头上的宝冠也随著些微的金属声碎裂。

贝库达的双臂像要求饶般高高举起。

贝尔库利有强烈的预感，他裹在黑色装扮下的高大身躯会被直向砍成两半。

磅。

清脆的爆破声。

源头来自于完全没有往后看的皇帝互相击打的手掌。

──竟然空手就夹住「空斩」。而且还背对著攻击。

不可能。暗黑界的拳斗士之间虽然流传著用双手包住剑来挡下攻击的奥义，但那是他们经过锻炼后比铁还要硬的拳头才能办得到的技巧。而且在这之前，「空斩」停留在空间中的威力，应该连拳斗士的族长都无法空手挡下来才对。

这样的思考虽然仅花了剎那的时间，但是贝尔库利的动作终于在这个时候停下来了。

因此他也只能默视著接下来发生的现象。

如海市蜃楼般在空中摇晃的透明斩击，直接被皇帝的双手吸进去。

同一时间，皇帝的蓝色双眸开始染上深沉的黑暗。

在那些黑暗底部，闪烁著无数的──那是，星星吗……？

不对。

那是灵魂。这个男人一路吸取过来的人类灵魂都被囚禁在里面。暗黑将军夏斯达，以及身为他副官的女骑士，灵魂应该也在那里……

「……你这家伙能吞噬人的心念吗？」

面对如此呢喃的贝尔库利，吸收完「空斩」威力后随意放下双手的贝库达这么回答：

「心念？原来如此……心灵（mind）与念力（will）吗？」

那是非常寒冷，完全感觉不到一丝活人气息的声音。发出这种声音的单薄嘴唇，形成了类似微笑般的外形。

「你的心就像老年份的葡萄酒一样。黏稠、浓密……又相当有分量，会在口齿间留下长长的余味。虽然不符我的兴趣……但是作为主菜前的开胃酒也算不错了。」

苍白的右手握住腰间长剑的剑柄。

缓缓从剑鞘里抽出的细长剑身，包裹著一层蓝紫色磷光。不觉得自己的剑有什么了不起的皇帝贝库达，一边把它垂下一边再次露出微笑。

「那么，再让我多喝一点吧。」

＊＊＊

厚实的大剑擦过亚丝娜左臂。

立刻有被烧红的金属棒贴到身上的感觉。

──才不痛呢！

她坚定地这么想著。下一刻，刻划在肌肤上的伤痕迅速消失。

这时她的右手已经像烟一样闪动，对准眼前士兵的右肩到左侧腹轰出四记连续的突刺技。男人的脸孔扭曲，发出惊人的咒骂声后倒向地面。

已经数不清刚才干掉的是第几个敌人了。

甚至无法确定古代遗迹的战端开启到现在究竟过了几十分钟。唯一可以确定的是，从参拜道路入口雪崩般涌入的红色士兵，依然残留著近似无限的数量。

──这种程度的持久战根本算不了什么。因为旧艾恩葛朗特里，魔王战持续三四个小时也不是什么稀奇的事。

面对越过伙伴开始消失的尸骸飞扑过来的新敌人，在内心发出如此豪语的亚丝娜，用细剑把对方手中的斧头扫开。

对著身体失去平衡的敌人心脏轰出准确的一击，将视线往左右两边瞄了一下。

在参拜道路中央奋战的亚丝娜右侧，整合骑士连利交互投射双手上的回旋镖，造成敌人大量死亡。其威力与准确度令人感到惊恐，看来这边暂时交给他应该没问题吧。

但问题是左侧的战场。虽然以索尔缇莉娜为中心配置了队长等级的卫士，但可以看出战线已经慢慢被敌人压制了。

「左翼，加快轮替的间隔！治愈术也请以左边为主！」

「亚丝娜大人，我还没有问题！」

在最前线大叫著回答的索尔缇莉娜，发动了两手剑用范围剑技「龙卷风」。带著浅绿色光辉的长剑以超高速转了一圈，一口气把三名敌兵轰飞出去，但接下来索尔缇莉娜自身也脚软而跪了下去。昨天晚上，在回忆爆料大会的空档期间闲聊时听说过，贵族出身的剑士们特别擅长一对一的礼仪性决斗，似乎不习惯这种看不见终点的长期混战。

事实上，莉娜的剑确实流丽又雄壮，在才刚来到这个世界一天的亚丝娜眼里也是太过于光明正大了。由于完全不使用假动作或者让敌人失去平衡的招式，只是一味发动大技，所以技前技后的僵硬时间就会被敌兵乱挥的武器划中而受到小伤害。她的铠甲已经满是伤痕，紫色的卫士服也各处都渗出血来。

「莉娜小姐，退下去治疗吧！相信自己的伙伴！」

听见亚丝娜的指示后，莉娜咬牙点了点头，留下「我马上回来！」的声音就退往后方。立刻有替代的卫士长填补她空下来的战线。但是他的脸上也浮现浓浓的疲惫之色。

除了左翼的疲态之外，还有另一件事让亚丝娜相当在意。

现在战斗中的红色铠甲士兵们，绝对不是单纯的演算所操纵的人形怪物。而是MM起源国──美国里身经百战的玩家。早就习惯对人战的他们，差不多该发现光靠单纯的突击没办法分出胜负，应该采取战术性的攻势才对了。

如果自己站在他们的立场会怎么做呢？亚丝娜一边闪动细剑一边思考著。

按照常规来说，应该是从后方进行远距离攻击。但是红色军团里看不见魔术师职业的玩家，就算有也无法在战场上立刻熟悉Underworld复杂的术式指令吧。

如此一来就只能用弓了，对人界军来说相当幸运的是，对方似乎无法准备弓兵的帐号。再来就是把手上的武器丢出去了，但玩家心里应该都对这种行为有很大的抗拒感吧。因为丢出武器的人将再也无法参加战斗。

看来可以判断敌人无法打破这种胶著状态了。

这样的话，就只有按照当初的计划，把这一万数千名的敌人全部打倒。

就在亚丝娜重新下定决心的这个时候──

参拜道路的入口处忽然变暗。

照射进来的朝阳，被横排成一列的巨大盾牌以及宛如旗杆般林立的骑枪挡住了。

──重枪兵！

「枪……枪要突击过来了！请仔细看著枪尖，然后回避初击！只要近身就能打倒他们！」

当亚丝娜对左右两边的伙伴这么大叫的同时，就传出「喀锵！」的轰然巨响，巨大骑枪一起被架了起来。

「「「Assaaaaaaaaalt！」」」

横列上整整排了二十人的重枪兵，随著浑厚的吼叫声开始突进。

类似红色海啸的压力，让卫士们产生了浮动。亚丝娜心里一边念著「大家拜托了，冷静下来！」，一边凝视著朝自己冲过来的敌兵。发出凶恶乌光的骑枪带著一击必杀的威力逼近。

让它接近到最后一刻──格挡！

细剑一边爆出黄色火花一边朝骑枪侧面滑去。尖锐的枪尖从亚丝娜脸庞右侧经过并且往后方刺去。

「……喝啊！」

随著吼叫声，有如抬头往上看一般把细剑刺入高大敌人喉头铠甲之间的缝隙。瞬间传来相当写实的手感。头盔底下也跟著喷出鲜血。

但传出来的悲鸣不只来自于敌兵。

左翼的数名卫士无法避开骑枪而被贯穿了身体。

「呜…………！」

亚丝娜咬紧牙关，离开负责的地点往左边跑去。敌兵准备从丧命的卫士身上拔出骑枪时，亚丝娜就以单发突刺「线性攻击」连同他胸口的铠甲一起贯穿。接著重新摆好染血的剑，用二连击突刺「平行刺击」砍下一名敌人的双手。

接著又以垂直跳跃避开第三名敌兵随著咒骂刺出的骑枪。落在枪上后立刻往上冲，脚一踩到敌人肩膀，就以左手抬起头盔，将细剑深深插进对方露出来的脖子里。

亚丝娜依然站在连悲鸣都发不出来就丧命的敌兵背上，直接开口大叫：

「受伤者退到后方！以最优先的顺序治愈他们！」

再次确认周围后，看见在骑士连利与卫士们的奋战下好不容易击退了二十名重枪兵，但己方也有六名卫士受到骑枪的直击。当中有三个人眼看是救不活了。

──对方重复这种战法的话，人数占绝对劣势的人界军终将无法维持战线。

再次传出的地鸣把亚丝娜这样的战栗变成了现实。接下来的二十名重枪兵从参拜道路入口往前突进。

亚丝娜把视线硬从涌至的骑枪群移开，看向本来是自己负责的战线中央。

该处有一名依然稚气未脱的少年卫士双膝一边发抖一边摆出手里的剑。

「啊…………！」

亚丝娜发出尖叫并往右边跑去。

冲进了从左侧逼近的骑枪与呆立在现场的少年卫士之间。已经来不及用细剑格挡了。她试著用左手来抓住骑枪闪亮的枪尖。

如果这是通常的VRMMO游戏，具压倒性反应速度与筋力数值的亚丝娜应该可以成功挡下攻击。但是Underworld里存在无数SAO与ALO里可以无视的参数。

光滑的钢铁骑枪在被喷出的血濡湿的左手中一滑──

钝重的冲击晃动全身。在无法出声的情况下，亚丝娜低头看著深深贯穿自己侧腹的巨大金属。

＊＊＊

以最小限度的动作来发挥最高效率的剑。

骑士长贝尔库利，从皇帝贝库达那种与至今为止所见过的流派都不同的剑技上产生这样的感觉。

首先是他的脚几乎没动。躲避己方的攻击时，只在地面微微滑行。另外，在攻击时也几乎没有准备动作。右手轻握住的剑，会突然流畅地从最短距离飞过来。

也就是说，几乎无法预测他的动作。皇帝绝算不上快速与强力的五次攻击，身经百战的贝尔库利都完全无法反击。

但是，光靠这五次就够了。

从庞大的战斗经验当中，已经掌握贝库达技巧与呼吸的贝尔库利，在第六次攻击时展开了初次的反击。

「嘘！」

贝尔库利也发出最低限度的叫声，抢在贝库达的上段斩之前同样使出了上段斩。

蓝白色火花点缀了剧烈的金属碰撞声。

两把剑在空中交错。从现在开始就是比拚力量了。没有受到太大的抵抗，敌人的剑就往下沉去。高大的贝库达像是承受不住压力般弯下膝盖。

──机会来了！

贝尔库利把凝聚的心念灌注到爱剑里。熟悉的钢铁剑身开始带著银色磷光。把贝库达的黑剑一点一点往下压的时穿剑，剑尖碰到敌人肩膀并且陷入铠甲表面──

瞬间，贝库达的剑发出奇怪的光辉。

蓝紫色磷光像是生物一样蠢动，缠上了时穿剑。同一时间，原本强力放射的白银光芒就萎缩并且消失。

──这是什么？

不对……

说起来，我到底想……做什么……

左肩随著「哔滋」的尖锐声音感觉到冻僵般的寒气，贝尔库利瞬时瞪大双眼。他拉开双方的距离，深深吸了口气，把一瞬间快要失去的意识恢复过来。

──刚才那到底是怎么回事？

我这个贝尔库利竟然会在战斗当中恍神……？

愕然如此自问之后，就觉得事情绝对没有那么简单而摇了摇头。

简直就像连自己为什么会在这里，自己究竟是谁都忘记了一样，意识被一片强制的空白所侵蚀。

「你这家伙……从剑上直接吸取了我的心念吗？」

贝尔库利以低沉的呻吟声这么问著。

得到的回答却只有淡淡无声的微笑。

贝尔库利咂了一下舌头，往左肩一瞥。以擦伤来说有点太深了。

「哼……皇帝陛下，你倒是很会给我找乐子嘛。没办法挥剑互击吗，这场战斗还真是麻烦。」

咧嘴回报以笑容的贝尔库利充满自信地说完后，贝库达反而收起笑容并且呢喃：

「……唔。说起来，真的都没试过呢。」

接下来右手的长剑随便往前刺出。但那完全是在攻击范围之外。剑刃不可能砍伤对方──

蓝黑色黏液般的光线从停在空中的剑尖直接往前伸。

……竟然从远处也能攻击。

这样的思考闪过脑袋的瞬间，光线也触碰到贝尔库利的胸口。

彷佛蜡烛的火焰熄灭一般，意识瞬间离他而去。

骑士长只能呆立在现场，眺望著轻快地往自己靠近的长剑，偷偷地潜入左臂下方。

剑随便地往上一弹。

沉重又湿濡的声音响起，贝尔库利粗壮的整条手臂就这样被砍了下来。

＊＊＊

「咕……呜……呜呜！」

亚丝娜好不容易才把从喉咙溢出来的悲鸣压成低沉的呻吟。已经不只是疼痛。腹部宛如被高温喷火器持续烧著一样，超过容许范围的感觉爆炸了。

──才不痛呢。

这点伤势，一点都不痛！

发出乌亮光芒的骑枪深深贯穿左侧腹。应该从背后凸出了一公尺以上吧。

越过肩膀稍微确认一下，发现正后方的少年卫士只被枪尖稍微擦过脸颊而已。亚丝娜用尽全身的精神，对著脸色苍白朝上看著自己的少年挤出微笑。

──和这个孩子性命的重量相比……我这只是虚拟的伤势！

「呜呜……啊！」

左手依然握著贯穿身体的骑枪，这时亚丝娜把所有的力量灌注到上面。

直径超过五公分的金属发出「啪锵！」的声音在手掌里碎裂。手接著绕到背后，抓住凸出的枪然后将其拉出。

眼前火花四溅，宛如电击般的痛楚从脑门贯穿到脚底。但亚丝娜还是没有停手，全力拉出骑枪后，直接把它丢到地上。

虽然从腹部巨大的伤口以及嘴里同时迸发大量鲜血，但是脚步完全没有虚浮的亚丝娜用左手擦拭嘴角，然后抬头看著茫然站在眼前的敌兵。

手握折断骑枪的大汉，像感到很疑惑般眨了好几次头盔深处的眼睛。

「Oh, gosh.」

同样一句话又重复了一次，接著就快速用英文说著：

「……搞什么嘛……这种游戏一点都不好玩。我要登出了。」

听见对方这么说的亚丝娜，右手的细剑就准确地贯穿大汉的心脏。巨大身躯崩落到地面，随即被消灭特效包围住。

没有因为伤痛而流出的眼泪，现在不知道为什么从双眼中渗出。

覆盖这座战场的痛苦与憎恨，原本根本没有存在的必要。

美国人玩家与人界守备军的卫士之间没有任何互相残杀的理由。相遇的状况有所改变的话，这些人应该能够做朋友才对。就像亚丝娜本人一样。

虚拟世界……VRMMO不是为了这种事情而诞生。

「救……命……」

日文的悲鸣停止了亚丝娜的思考。把视线移过去后，就看到巨大骑枪正准备朝倒在地面的卫士刺下去。

「呜……啊啊啊啊！」

把激动的情绪换成吼叫，亚丝娜朝著大地踢去。

右手上的细剑全力往前刺出。从剑间溢出的白光覆盖住她全身。

双脚离开地面，变成炫目彗星的亚丝娜在空中飞翔。这是细剑剑技最高等级的突进技「闪光穿刺」。

想要杀害卫士的枪兵被高高地弹上空中。而后面的敌人也面临了同样的命运。接著又有一个人被撞飞。

把第四个人的身体钉在神像脚边，剑技才终于结束。震动肩膀喘息著的亚丝娜回过头去。

重枪突击的第二波攻击，似乎让人界军出现五个人以上的死伤者。但是，参拜道路的入口已经准备好第三波展开突击的二十人了。

从开始消灭的敌人尸骸上拔出细剑后，亚丝娜放声大叫：

「全员死守自己的岗位！连利先生，请移动到中央！」

注意到亚丝娜侧腹持续流出的鲜血，年轻骑士不禁绷起脸来。为了让他安心，亚丝娜先是对他微笑了一下才又接著说：

「──我要独自一个人杀进敌阵。没被干掉的漏网之鱼就拜托你了。」

「亚……亚丝娜大人！」

对著发出喘息般声音的连利与其他众卫士举起紧握的左拳。

亚丝娜随即一直线往前跑去。

＊＊＊

重心不稳而脚步踉跄的贝尔库利，踩到自己滚落到地面的左臂。

脚上传过来的真实触感抢在痛觉之前唤回了他的意识。

「呜……！」

再次全力往后跳来拉开距离。

左肩伤口上落下的血在显白的岩石上画出深红弧形。

──天啊。

光是被剑对准意识就停止了吗……

握著时穿剑的右手竖起两根手指，一边把手指对著左肩的伤口，贝尔库利一边转动脑袋。这段期间，无咏唱就发动的治愈术已经发出蓝色光芒来止住出血。但是这座荒凉的岩山上，没有足够的神圣力让被砍落的左臂重新长出来。

──该如何对抗？

曾经展现过的武装完全支配术「时穿剑‧空斩」恐怕已经不管用了。只会让停留在空中的心念斩击完全被吸收而已。

还剩下来的手段，就只有记忆解放术「里斩」了。但是要发动那招有两个困难的问题。第一个是敌人不可能默默看著自己悠长的攻击动作。第二个是，要特定攻击的地点可以说比登天还难……

贝尔库利眨眼来甩开从额头流下来的汗水。

然后忽然间注意到。

──我陷入拚死的状态了。

曾几何时，我已经没有一丝从容不迫的感觉了。

也就是说，现在，这个地方正是我的死地。是生死的关头。

「……嘿。」

整合骑士长贝尔库利‧辛赛西斯‧汪即使正确地体认到自己陷入九死一生的状况，依然露出了粗豪的笑容。

他把视线从缓缓往这边靠近的皇帝贝库达身上，移到横躺在战场一隅的黄金骑士爱丽丝‧辛赛西斯‧萨提身上。

──大小姐啊。

我没办法满足大小姐打从内心冀求的事物吧。也就是所谓的亲情。因为我连自己的双亲都记不得了。

但是，只有这一点我相当清楚。

父母亲会为了保护自己的孩子而死。

「你这种家伙……永远不会了解吧，臭怪物！」

贝尔库利大叫并朝著地面踢去。

在没有任何的策略下，最古老的骑士只是把自己的一切灌注在爱剑上然后笔直往前跑。

＊＊＊

「喀……哈……」

随著急促呼吸一起吐出的大量血液飞溅在脚边。

只有插在地面的细剑是自己唯一的支柱，但就算是这样，亚丝娜依然持续站著。

虽然好不容易把重枪突击的第三、第四波人马全部砍倒，但全身受的伤已经超过十处。闪耀珍珠白光芒的上衣与裙子被残酷地撕裂，也因为自身及敌人的血而染红。

很难相信受到骑枪直击而全是孔洞的身体，到了这个时候竟然还能动。实际上，庞大到不合道理的HP，并不允许亚丝娜因此而力竭。

──只有心灵撑不下去，这副身体才会倒下。

这样的话，我会永远站下去。

全身已经可以说没有感觉了。只有燃烧起来般的热气在神经里奔驰，让视界产生扭曲。

亚丝娜微暗的视界一捕捉到敌人第五波的突击，就把细剑从地面拔出来。

已经无法做出敏捷的回避动作了。只能用身体承受骑枪，然后以剑技来反击。

原本像羽毛般轻的细剑，这时重得跟铅条一样。亚丝娜用双手摆出细剑，弯下上半身来等待著敌人。

「──GO！」

地面产生震动，二十名重枪兵开始突进了。

咚、咚、咚咚咚咚……

立刻加速的脚步声里。

从四面八方混入尖锐的震动音。

亚丝娜像是被吸引过去般抬头往上看。

从红色天空中延伸出一条红线。那是细微的数位符号的罗列。

──敌人的……援军……？

「…………啊啊…………」

吐出的气息里，混杂著极少量放弃的想法。

但是──

线条的颜色并非至今为止所见的红色。就像黎明前的天空一般，闪烁著深邃的蓝色光芒。

亚丝娜已经无法推测这样的颜色代表什么意义了。她只能瞪大双眼，等待结果来临。

线条在高十公尺左右的空中凝聚，经过一瞬间的闪光后变成人的模样。

嗡。

空气忽然发出低吼，人影以几乎看不见的速度旋转，像龙卷风般发出猛烈的低吼再次开始下降。

站在正下方的二十名重枪兵，曾几何时也停下脚步抬头看著天空。

鲜艳的蓝色龙卷风轻轻降到他们中央──

突然间染上了深红色。

那是鲜血。被龙卷风卷进去的步兵，瞬时遭到分尸，往广范围喷洒出鲜血。

呈放射状被打倒的枪兵中央，龙卷风缓缓停止旋转，最后恢复成人的模样。

背对这边站著的人影，有著略为纤细的高挑身材。光润的和风铠甲在逆光之下显得闪闪发亮。左手放在腰间的剑鞘，右手则拿著一把长得恐怖的剑，不对，应该是刀，而目前刀已经横向挥尽了。

亚丝娜曾经在除此之外的世界看过刚才的攻击。

剑技。

大刀广范围攻击「旋车」。

缓缓撑起上半身的人影，把长刀扛在右肩上，轻松地把脸转过来。

鲜艳的头巾底下有著满脸胡渣的脸庞，目前正咧嘴露出笑容。

「哟，让你久等了，亚丝娜。」

「克……克莱因……？」

亚丝娜无法听见自己沙哑的声音把话说完。

世界突然间充满了无数震动音造成的尖锐共鸣。明明是和美国人玩家出现时同样的声音，但亚丝娜耳朵里听起来却像天使的欢呼声一般。

像雨一般从红色天空降下来的，是带著鲜艳蓝色光辉的几千条符号线条。

＊＊＊

挥动斩击。

意识变得模糊。

因为受伤的痛楚而觉醒。

已经不知道重复几次这样的过程了。

皇帝贝库达宛如故意要延长战局般不给自己致命伤，但贝尔库利知道从无数伤口流出的血液，也就是天命的量已经差不多快到界限了。

但他还是挤出在超过两百年的时间里磨练出来的精神力，不考虑也不惧怕任何事情，脑里只是持续执行著唯一一项工作。

也就是数著数字。

正确来说是测量著时间。

拥有察知时刻这种特技的贝尔库利，正使用这样的超感觉，在脑袋里拚命数著时刻。就连思考因为皇帝的剑而变得混浊当中，贝尔库利也在无意识的情况下累积著数字。

──四百八十七。

──四百八十八。

贝尔库利一边一秒一秒正确数著时间，一边反覆进行鲁直的攻击。有时甚至还会丢出挑衅的发言。

「……看来……你的剑技倒是不怎么样嘛……皇帝陛下。」

──四百九十五。

「砍中这么多剑还不能打倒我……只能算二流，不对，应该算三流的剑士吧。」

──四百九十八。

「看招，我要继续攻击喽！」

伴随喊叫声从正面砍了过去。

──五百。

剑触碰到在皇帝周围扩散的蓝紫色光芒。

心念遭受吸食，思考忽然中断。

回过神来时，已经一只脚跪在地上，左脸颊新增的伤势滴落鲜血到地面后发出了声响。

──五百八。

快要到了。再撑一会儿吧。

摇摇晃晃地站起身子，贝尔库利重新转身面向背后的皇帝。

至今为止从未表露过任何感情的贝库达，这时脸上稍微浮现出厌恶的表情。贝尔库利因为刚才的攻击而飞溅出来的一滴血，似乎沾到了他雪白的脸颊。

用指尖把染红处擦掉后，贝库达便呢喃：

「……有点腻了。」

他踩著贝尔库利造成的血滩往前踏出一步。

「你的灵魂太沉重也太浓厚了。味道会整个黏在舌头上。而且还相当单调。一心只想著要杀掉我。」

皇帝一边以平板的声音这么说著，一边又往前走了一步。

「消失吧。」

无声举起的黑剑，上面缠著黏液般的光芒。

贝尔库利的表情完全没有改变，只是轻咬住牙根。

──再一下就可以了。再三十秒。

「嘿……别……别这么说嘛。我还没……玩够呢。」

身形不稳的贝尔库利朝没有任何人的空间踏出数步。然后无力地举起右手的剑。

「哪里……你……你跑到哪去了。哦，那里吗……？」

两眼浮现空虚光芒的骑士长挥舞著剑。

「喀滋」一声以剑尖敲打完全不对的地方，结果身体因此剧烈地摇晃。

「咦……是这边吗……？」

再次挥出没有一丝风声的攻击。即使拖著一只脚，依然持续地动著。

因为大量失血而丧失视力，连思考都陷入朦胧状态──看起来就是这种模样。

但这是骑士长一辈子只有一次的演技。

半闭状态的灰蓝色眼睛，依然确实地捕捉住某样东西。

也就是足迹。

十分钟里随便的攻击，让绝对算不上宽广的岩山顶上，已经撒满了贝尔库利的血液。在经过皇帝的靴子与骑士长的皮革拖鞋踩踏之下，形成两种明显不同的足迹。

换言之，这是两者详细的移动纪录。

表演陷入错乱状态的贝尔库利，寻找的是十分钟前左臂被砍下来时，皇帝已经变干且泛黑的足迹。

无意识下的时间测量就是从那之后开始。

也就是说皇帝贝库达在十分钟前是站在那个地方。足迹就忠实地记录著接下来他从那里往哪个方向移动。

──五百八十九。

──五百、九十。

「哎呀……找到了……哟……」

贝尔库利虚弱地呢喃，一边左右摇晃，一边对完全无人的空间挥动时穿剑。

这应该是不折不扣的最后一击了。

剑与主人所剩下来的天命都已经像是风中残烛。

贝尔库利耗费剩余的所有天命，准备发动神器──时穿剑的记忆解放术。

「时穿剑‧里斩」。

与在空间中保持斩击威力来斩断未来的「空斩」完全相反，里斩是斩断过去。

Underworld的Main Visualizer里，所有人类个体的移动履历都会记录六百秒，也就是十分钟的分量。

时穿剑‧里斩将干涉移动履历，让系统误认现在的情况是十分钟前正确的位置情报。

结果就是，外表看起来只是斩过虚空的剑刃，将会砍在过去曾经存在这个位置的人现在的身体上。这是无法回避与防御，可以说是背叛所有技术与努力的一击。

因此贝尔库利多年来一直避讳使用里斩。就连和尤吉欧对战，输给蓝蔷薇之剑的记忆解放术时，只要使用这一招应该就能获胜，但他还是没有这么做。即使知道这样会被认为是对元老长裘迪鲁金与公理教会的背信行为。

但是，如果面对的是同样能操纵非人力量的皇帝贝库达，那就不用客气了。

斩落皇帝贝库达的飞龙时，贝尔库利利用敌人以同样速度一直线飞行的动作，正确地测量出十分钟前敌人存在的座标。但是，互相接近的混战，要特定敌人的座标将困难好几倍。

当然可以记住十分钟前的一瞬间敌人存在什么地方。但使用这种方法的话，一旦剑技的发动遭到阻挠，就又得重新数六百秒了。

就跟现在这个瞬间一样。

「你有什么企图吧。」

皇帝贝库达像滑行般接近，蓝黑色心念的波动从他的长剑上朝贝尔库利延伸。由于不能碰到它，贝尔库利在没有办法的情况下，只好用跟刚才完全不同的敏捷动作避开了去。结果「十分钟前的一秒」就这么过去，永远不会回头了。

──错过了吗？

贝尔库利重新摆好快要施放记忆解放术的时穿剑并在内心如此呻吟。

这下子真的是万事休矣。

既然被发觉还有秘策存在，皇帝贝库达就不会给自己再次发动大技的时间了吧。实际上，现在就不断有心念的光线从长剑上朝著贝尔库利伸过来。

但骑士长还是全力回避这样的攻击。

垂死挣扎。

挣扎再挣扎，然后狼狈地倒下。很久以前就决定，大限来临时就要这样死去。

三次、四次。

贝尔库利躲过皇帝的攻击多达五次。

但接下来蓝黑色光芒终于擦过他的身体。

意识突然间中断──

再次睁开眼睛的贝尔库利，见到的是贝库达深深刺进自己腹部的长剑。

剑刃一被拔出去，最后的天命就化为深红的液体往外喷出。

缓缓往后倒下的骑士长，双眸当中……

映出一头从遥远高空撕裂大气急速降落的飞龙。

──星咬。

喂喂，不是要你在上面待机吗？你这家伙，至今为止从未违背过我的命令吧。

从飞龙大大打开的下颚当中，迸发出一条笔直的蓝白色火焰。

这样的热线带有一击就能烧尽百名士兵的威力，但是却被皇帝贝库达随便举起的左手挡了下来。

呈现半透明的黑色手背，很轻松地把热线弹开。往四方飞溅的火焰，在大气里留下无数的轨迹。

皇帝右手上的剑立刻放出蓝黑光芒，击中星咬的额头。虽然受到轻易就支配暗黑骑士团飞龙的技能──但贝尔库利的骑龙还是没有停下来。

它把天命变成白色光辉从双翼上放射而出，朝著皇帝猛然撞去。

贝库达脸上出现厌烦的表情。

他把剑大大地往后拉，接著刺进星咬准备撕裂自己的嘴巴里。黑光开始肆虐，一边吸取飞龙的天命一边把它巨大的身躯从各处撕裂。

星咬牺牲性命才创造出短短七秒时间──

但贝尔库利没有浪费它的牺牲。

即使鲜明地感觉到和自己度过漫长岁月的爱龙正在背后丧失生命，骑士长还是在记忆解放状态下高高举起拖著蓝色残像的时穿剑。

只靠记忆「十分钟前敌人的位置」这个方法的话，十分钟才会有一次攻击机会。

但是，在地面上刻划下血痕的移动纪录，就能够连续追踪十分钟前的敌人。

贝尔库利对著显示方才失败的地点七秒钟后皇帝贝库达所在地的血脚印，施放了用尽全力的斩击。

时穿剑‧里斩还有另一个特性。

也就是，因为是干涉系统本身，所以威力会直接影响对象的天命数值。没有办法藉由心念来防御。

因此，皇帝贝库达能把所有心念攻击无效化并加以吸收的能力，只有这个瞬间没有发动。

首先，系统上设定的贝库达庞大的天命归零了。

而这样的结果就是，皇帝的身体从左肩口到右腰完全被砍成两段。

在自己的身体从切断面滑下来的期间，皇帝贝库达的表情也像是完全没有变化。淡蓝色眼睛只是像玻璃珠一样空虚地眺望著天空。

在掉落下来的上半身快要接触到地面之前。

漆黑的光线从心脏附近炸裂，宛如墓碑一般高高往天空延伸。

在光线止歇的时候，地面上已经没有留下任何皇帝存在过的痕迹。

迟了几秒钟，贝尔库利右手里用尽天命的时穿剑也随著细微的金属声碎裂了。

＊＊＊

……好温暖。

真想在这样的环境下再待一会儿。

整合骑士爱丽丝让意识飘荡在快从朦胧状态醒过来前的浮游感当中，脸上同时露出淡淡微笑。

日照晃动著。

宽阔的大腿承受著身体。

粗犷的手温柔地摸著自己的头发。

…………爸爸。

不知道有多久没有像这样让自己靠在膝盖上了。这种安心感……有很长一段时间都忘记这种完全被保护，没有任何事情需要担心的感觉了。

啊啊……但是，差不多该起来了。

于是整合骑士爱丽丝静静地抬起睫毛。

看见的是闭著眼睛，面露微笑俯瞰著自己的壮年剑士脸庞。

从粗壮脖子延伸到胸口的几道旧伤痕。上面刻划著无数的全新剑伤。

「…………叔叔？」

意识好不容易恢复清晰的爱丽丝简短地呢喃著。

──对了，我被皇帝贝库达的飞龙抓走了。真是的，怎么会那么粗心呢。竟然没有警戒背后就随便往前跑。

但不愧是叔叔。竟然从敌人总大将手里把我救出来。只要有这个人在，就什么事情都能安心了。

再次露出微笑并撑起上半身的爱丽丝，注意到骑士长不只有脸部和胸口受伤后，不由得屏住呼吸。

左臂从肩口被砍掉了。东域风的战斗服被血染成鲜红。而且裸露的胸部下方，有一道深到令人惨不忍睹的伤口。

「叔……叔叔……！贝尔库利阁下！」

爱丽丝大叫并伸出手。

她的指尖碰到骑士长贝尔库利的脸颊。

接著爱丽丝才了解，伟大的最古老骑士，天命早已经用尽了。

＊＊＊

……喂喂，别哭成那样啊，大小姐。

这一刻总有一天会来的，不是吗？

整合骑士长贝尔库利‧辛赛西斯‧汪往下看著抱住自己尸骸痛哭的金发少女并且准备这么说，但是声音却完全传不到地上。

……大小姐的话一定不要紧。你已经可以独立了。

因为你是我唯一的弟子……也是我的女儿啊。

眼睛下方的光景距离自己越来越远。对心爱的黄金少女骑士报以最后的微笑，贝尔库利就把视线看向遥远北方的天空。

然后把思念移到应该在下方的另一名女性骑士身上。

虽然不知道能不能传递到，但心中只有在历经几乎是无限的日子之后，终于来临的死期所感觉到的深切感概。

……嗯，也算是不错的死法了。

「没错，有这么多人为你哭泣，应该要觉得很幸福了。」

因为这忽然响起的声音而回头，就发现飘浮在那里的是，一名只有长长银色头发覆盖在柔软裸体上的少女。

「……什么嘛，你果然还活著吗？」

贝尔库利一耸肩，眨著银色眼睛的最高司祭亚多米尼史特蕾达就轻声笑了起来。

「怎么可能。这是你记忆当中的我。是保持在你灵魂里的，亚多米尼史特蕾达的记忆。」

「哦，虽然不是很了解。但是……在我记忆当中的你，能够像这样子笑真是太好了。」

贝尔库利咧嘴笑了起来，然后看向旁边。

曾几何时已经出现在那里的星咬，开始用长长的脖子摩擦他。

搔了搔飞龙银色透明的脖子后，骑士长就轻轻跳到它的背上。接著伸出手，让最高司祭坐在自己前面。

漫长生涯当中唯一服侍的主人，没有回头就直接歪著脖子问道：

「你不恨我吗？这个把你关在无限的时间监狱里，还数次夺走你记忆的我？」

贝尔库利稍微思考了一下，然后这么回答：

「虽然确实长到令人厌烦，不过也算很有趣的一生了。嗯，我是这么认为喔。」

「……这样啊。」

把视线从简短如此回答的亚多米尼史特蕾达身上移开，贝尔库利握起星咬的缰绳。

飞龙展开透明的双翼，朝著无限宽广的天空缓缓拍动翅膀。

＊＊＊

遥远的北方天空底下──

过去叫作东大门而广为人知，现在已变成瓦砾堆积在干枯大地上的巨大遗构东西两侧，一万名黑暗领域军后备兵力，以及四千名人界守备军本队正在各自的阵营当中互相对峙。

黑暗领域军里已经看不见皇帝贝库达的身影，因此他们不可能自行判断来发动攻击，但不知道实情的人界军也无法动弹，双方陷入了漫长的胶著状态。

只有干燥的风不停作响的大门旧迹上，可以看见一名女骑士站在那里。她是负责指挥守备军本队的整合骑士法那提欧‧辛赛西斯‧滋。为了接下来的战斗，已经让卫士和修道士们去休息，但待在帐篷里的自己实在是睡不著，所以独自走到东大门的旧址来。

夜晚的黑暗早已远离，索鲁斯的光线在黑暗领域的天空是红色，而在人界这一边则是让天空染上了蓝色。

很快地，距离骑士长贝尔库利率领的守备军诱饵部队，离开大门后往黑暗领域南部前进已经过了半天以上。虽然知道他们的任务不是那么简单就能结束，但只能在此等待的自己还是感到很著急。

当法那提欧准备向三女神祈祷至少要让部队平安回来而合起双手，接著准备闭上眼睛的时候──

忽然就又睁开眼睛。

感觉耳边响起心爱男人的声音了。

──抱歉，法那提欧。看来已经见不到你了。

──之后就拜托你了。要让那个孩子过幸福的生活啊……

法那提欧在这个地方和骑士长贝尔库利分离之前，他也曾经说过同样的话。

装备著银色护手的双手静静地抚摸下腹部。

是在三个月前发现自己怀了新的生命。一百多年来都顽固地拒绝与法那提欧发生关系的贝尔库利，或许是在解除这个禁忌时就已经有这种预感了吧。

预感自己将会死亡。

了解骑士长贝尔库利在遥远的天空底下结束漫长生命的法那提欧，缓缓跪到地面，然后用双手覆盖脸部。

无法忍住的呜咽从喉咙流出。

从很久以前就听过贝尔库利拒绝法那提欧以及其他任何女性的理由。

在人界里，只有受到公理教会司祭正式承认婚姻的男女，结合之后才能获得子嗣。但是整合骑士因为具有司祭的资格，所以不需要举行大费周章的婚礼。只要宣示彼此相爱并且结合，就有可能怀孕。

但是这个孩子会比接受天命冻结处理的双亲还快衰老与死亡。但因为这样就要最高司祭对孩子施予同样的处理也是相当残酷的事情。

贝尔库利是在最高司祭驾崩之后才接受法那提欧的心意。也就是说，他决定在有限的生命当中，守护自己孩子的成长。

这样的话──

「……请放心吧，贝尔库利阁下。我会好好地养育这个孩子。让他成为跟阁下一样雄壮而且高尚的人。」

忍住呜咽后，法那提欧把自己的决心说出来。

──但是只有现在。

现在先允许我大哭一场吧。

整个人趴到地上，握紧骑士长贝尔库利奔驰过的土壤，法那提欧开始放声大哭。

5

「虽然我跟你们没有私人的恩怨……」

把长刀笔直对著红色军队的克莱因，嘴里所说的话响彻古代遗迹。

「但好友被你们痛扁的这笔帐一定要跟你们算。我看要三倍奉还……不对，是千倍奉还啦，你们这群臭家伙！」

丢出这一串话后，就笔直往敌军冲去。那种鲁莽的程度，让身受重伤的亚丝娜也一瞬间因为傻眼而忘记疼痛，但之后就立刻有新的符号线条降落在克莱因身边并且变成人形。

出现的是提著大型战斧，有著巧克力色肌肤的巨汉。

「……艾基尔先生！」

亚丝娜以沙哑的声音呼唤对方的名字。

过去不论是在战力面或者补给面都一直给予SAO攻略组强力支援的「战斗商人」，看见亚丝娜后，相貌堂堂的他就咧嘴露出笑容并竖起右手大拇指。

接著立刻转身，追著克莱因猛然往前冲。

第三与第四个人则是出现在亚丝娜眼前。

先是以红豆色为基调的服装上穿戴著胸甲，腰间挂著银色锤矛的短发女孩。接著是身穿鲜蓝色束腰外衣与裙子，头发绑成双马尾的娇小女孩子。

「──莉兹！西莉卡！」

这时候亚丝娜的双眼终于溢出泪水。

全身脱力的亚丝娜好不容易才能站稳身子，然后对著由强力羁绊所联结的伙伴们伸出双手。

「你们……你们来帮我了吗……」

「我们当然要来喽！」

「那还用说吗！」

两人同时绽放出灿烂笑容，接著莉兹贝特用力握住亚丝娜的右手，西莉卡则是用力握住左手。两人这时变成又哭又笑的表情。

「──怎么这么乱来……还让自己浑身是伤……你拚过头了啦，亚丝娜。」

「再来就交给我们吧。因为大家都来了。」

光是被莉兹贝特与西莉卡从两侧抱住，亚丝娜就感觉全身的伤痛被温暖地融化并且逐渐消失了。

「谢谢……谢谢……」

在不停溢出的眼泪后方，可以看见符号线条形成的骤雨降落在遗迹的入口附近。

出现的是身穿鲜艳色彩服装的几百名剑士。

「那些红色的家伙是敌人！」

「前卫，突击！把战线推回去！」

「后卫暂时退后确认咒文！」

一著地就用Underworld语……不对，是用日文交互大叫，然后把剑、斧与枪对准前方的红色士兵们砍去。

其漂亮的个人技巧，以及有纪律的集团行动，再再都显示出他们是全是熟练的VRMMO玩家。

──原来如此。

亚丝娜以终于再次开始运转的脑袋理解了目前的状况。

从美国人玩家出现在战场的时间点起，Underworld的时间加速就因为袭击者方的操作而固定成等倍了。这也就表示，从日本也能使用AmuSphere潜行到这里。

但是从援军装备的剑与铠甲所发出的强烈光辉来看，就能知道他们使用的不是预设的卫士帐号。

也就是说──他们使用了转移。

一定是把耗费漫长时间与莫大努力培养出来的角色，移居到Underworld来了。

明明还不确定能不能再次回到原本的VRMMO世界啊。甚至──只要考虑到Underworld的构造，就能知道角色也有可能在死亡的瞬间便遭到删除啊！

「各位……对不起……对不起。」

亚丝娜以哭声对眼前的两名好友，以及把前线给推回去的众多剑士们道歉。

「你在说什么啊，亚丝娜。」

莉兹贝特的回答里，充满了不可动摇的坚定意志。

「我们之所以在SAO和ALO里一路努力过来，一定就是为了现在在这个地方守护重要的事物啊。」

「嗯……说得也是…………谢谢…………」

亚丝娜一边以呢喃声传达谢意，一边深深点了点头。

但是还有另外一件无法理解的事情。到底是谁告诉现实世界的莉兹他们Underworld的危机，请求他们藉由转移来提供援助的呢？躲在O Turtle副控室里的菊冈和比嘉，实在不像有多余的心思能想到这样的作战并加以实行。

「……莉兹、西莉卡。是谁帮忙把大家带到这里来的……？」

亚丝娜一这么问，两人先是互相瞄了一眼，才同时笑著说：

「亚丝娜啊，这种事情还用说吗！」

「是结衣啊！结衣她拚命跟我们解释Underworld，以及生活在这里的人们的事情！」

听到这些话的瞬间，胸口深处就猛烈地揪紧，双眼也不停流下泪水。

结衣。在旧SAO诞生的Top-down型AI，同时也是亚丝娜和桐人的女儿。没错……除了她还会有谁。察觉亚丝娜和菊冈都没有料想到的袭击者们的计划，并采取了对抗的行动。

「…………谢谢你，结衣。」

以灌注了全部心意的声音这么呢喃，当她站起来的时候，被砍断的左手已经完全再生，全身的伤痕也几乎都消失了。

这时候，有畏畏缩缩的声音从背后向她搭话。

「那个……亚丝娜大人？这两位到底是……还有那些骑士们……」

以哑然的表情站在那里的是整合骑士连利。他身后那些从险境当中被拯救出来的卫士们也同样瞪大了眼睛。

亚丝娜的视线在连利与莉兹贝特她们之间往返，然后随著微笑这么回答：

「是我重要的伙伴们。从现实世界来帮助我们了。」

连利眨了数次眼睛，然后一直凝视著莉兹贝特与西莉卡──

稚气未脱的脸上，浮现明显放下心来的表情。

「……是这样啊……真是太好了……我还以为外面的人类，除了亚丝娜大人之外都是那种恐怖的士兵呢……」

「喂喂，怎么可能有这种事嘛！」

莉兹贝特随著有点遗憾，但是带著亲切的笑容拍打连利的肩膀。

「我叫莉兹贝特，请多指教喽，骑士小弟。」

「啊……好……好的。初次见面，我叫作连利。」

一边微笑一边看著这种景象的亚丝娜，忽然间有了一种相当确实的预感。

自己一辈子都不会忘记这种光景吧。

出生在两个不同世界的人们相遇、交谈并且开始建立关系的这个瞬间。绝对不能让从现在开始才要揭开漫长序幕的这个故事，因为悲伤而直接落幕。

亚丝娜大大吸了口气，然后改变语气对著莉兹贝特问道：

「莉兹，转移过来的总共有多少人？」

「啊……嗯。大概有两千多一点吧。虽然很努力了……但不是所有听过说明的人都愿意转移……」

亚丝娜轻轻拍了拍咬紧牙根的好友背后。

「已经很足够了。但是……为了对应再次转移的可能性，还是应该避免消耗战。不要把前线战场拉得太大，尽量增加补师的人数吧。莉兹和西莉卡退到两百人左右的后方建立支援部队。」

把意识切换到战斗模式，亚丝娜迅速对连利与卫士们做出指示。

「各位虽然不愿意，但是现在请与修道士队会合，然后行使治愈术吧。因为现实世界的剑士们不熟悉神圣术，如果能教会他们术式的话会有很大的帮助。」

「好……好的，亚丝娜大人！卫士队，正如你们所听见的！我们要支援援军的众骑士！」

连利一这么大叫，因为连续战斗而疲惫不堪的卫士们也以强而有力的声音回答。

「……那么，亚丝娜小姐有什么打算呢？」

面对如此询问的西莉卡，亚丝娜眨了眨一只眼睛并且回答：

「当然是在最前线杀敌喽。」

已经完全不觉得己方会战败了。

跑到最前线后，在该处看见ALO里熟悉的脸孔──风精灵领主朔夜、猫妖族领主亚丽莎、火精灵将军尤金等人，亚丝娜就坚定自己的决心并且和他们互相用力点了点头。

不对，不只有从ALO里转移过来的伙伴。

以极为准确的十字弓连射来提供剑士们强力援护的，应该和诗乃一样是Gun Gale Online的玩家们吧。

而紧密聚在一起，像暴风般横扫敌人的是玩遍各种VRMMO的最强公会「沉睡骑士」的众人。

魔术师朱涅找到亚丝娜后就咧嘴对她送出笑容，而亚丝娜则是一边扬起右手来回应，一边忍住再次快要渗出的泪水。

他们都知道可能会丧失宛如分身的虚拟角色，还是毅然来到这里帮忙。这样的话，唯一一名被超级帐号保护的自己，就必须得冒最大的危险，把他们的牺牲压抑到最小的程度才行。

亚丝娜一边飞奔过战场一边不断对援军做出指示，过于宽广的前线逐渐缩小，以遗迹参拜道路的入口为中心，重新建构起半圆形的战线。

就算两千名转移组的装备与能力再怎么强力，美国人玩家们依然残留著超过一万人的数量。陷入消耗战的话，应该就会出现许多死亡者，也就是可能丧失档案的玩家吧。

此外，还有另一件绝对无法忽视的担忧。

也就是只要在Underworld战斗就无法避免的，真实的疼痛感。

和大部分感受到疼痛时就已经死亡、登出的美国人玩家不同，重复著负伤、退后、回复过程的日本人，必须经常置身于痛苦当中。亚丝娜才刚切身感受过，这样的过程会如何地侵蚀心灵。

──各位，拜托了，在一万名敌人被打倒前要好好加油啊。

这样的话，这次袭击O Turtle的那些人能够投入Underworld的战力真的会用罄。再来就只要等诗乃追上应该已经被骑士长贝尔库利拖住脚步的皇帝贝库达，然后把爱丽丝抢回来就可以了。

亚丝娜在最前线闪动著细剑，持续用尽全力大叫著：

「没问题……能获胜的！有大家的力量，我们绝对能获胜！」

＊＊＊

身为日本人VRMMO玩家的广野孝，到这个时候才产生「我到底为什么要来这种地方」的感觉。

凌晨五点被朋友的电话吵起来后，之所以会在登入的ALO里回应过于唐突的转移要求，绝对不是因为拚命演说的女孩子很可爱，也不是因为对她的主张有共感的缘故。

老实说，最大的理由是「不知不觉就来了」。

另外再加上一点「以国家预算制作出来的VRMMO会是什么样的世界」的好奇心。升上高中后首次的段考，成绩糟得一蹋糊涂，反正不久之后AmuSphere就会被没收，所以也有一点自暴自弃的心情。再来就是──稍微有点预感，或许在那个世界里，自己真的能发现至今为止玩过的游戏里都未曾有过的「某种东西」。

转移自己花了两年的时间培育出来的角色，登入听都没听过的伺服器后，等待著孝的是阻挡在眼前的红色铠甲大汉、发音标准的英文粗话，以及无情挥落下来的斧枪。

虽然在悲鸣卡在喉咙里状态下往后飞退，但斧枪的前端还是命中左脚的防具，稍微把装甲击碎并且刺入小腿。大概是小学生时，骑脚踏车跌倒结果骨折才感受过这样的疼痛。

孝一边在内心大叫著「没听说会这么痛啊──！」，一边死命钻过斧枪的追击，然后好不容易用超稀有装备的单手剑把壮汉击退，当他正因为脚上流出大量真实的血液而快要吐出来时，就被拖到支援部队驻扎的后方去了。

──已经够了，我要登出！

孝忍不住这么嚷著，而负责治疗他的，是一名穿著淡蓝色僧侣服，亦即应该是司祭的同年纪少女。

一看见这个女孩子，不知道为什么就有种不可思议的感觉。

「马上替您治疗，请稍微忍耐一下喔，骑士大人。」

细声这么说完，女孩就对左脚上的重伤──以孝的标准来看──扬起娇小的双手并且咏唱咒文，这时孝一瞬间以为她是NPC。

但灰中带茶色的眼睛里浮现出的认真度、像东洋人也像西洋人的动人容貌，以及治愈伤口的温暖白光。这些全都告诉孝这个女孩子不是NPC，也不是正在角色扮演的日本人，而是真正生活在这个世界里的人类。

真的有这种事吗？会说日文但不是日本人，而且也不是NPC。这样的话，这个女孩子到底是什么人呢？

左脚被斧枪直击而产生剧痛时还没有这种感觉，是女孩子用魔法逐渐治愈出现的伤口时，孝才终于有了自己正处于某件重大事件当中的强烈意识。

「好，这样就不要紧了，骑士大人。」

当穿著僧侣服的女孩子露出些许自傲的表情把双手移开时，长达五公分左右的伤口已经完全愈合，只留下一点点淡茶色的痕迹。而且也感觉不到痛楚了。

「谢……谢谢你……」

孝虽然吞吞吐吐地，不过还是向对方表达了谢意。即使急著想说些比较符合「骑士大人」身份的台词，但只是脸部发热而舌头却动也不动，回过神来才发现，他竟然做出自己也意想不到的行动。他伸出双臂，静静地把少女纤细的身体抱过来。

如果这个世界是一般的VRMMO世界，孝的行为将会被认为是「对于NPC的不适切行为」，并且遭到系统的警告。

但是穿著僧侣服的少女在孝的臂弯里只是身体一震，然后像感到惊讶般轻轻吸了口气而已。几秒钟后，孝就感觉到少女的手臂畏畏缩缩地绕到自己背后，虽然轻微但是确实有压力加诸在上面。

「没问题的，异国的骑士大人。」

耳边传来了平稳的呢喃声。

「连只是见习修女的我，都能像这样尽自己的棉薄之力了。骑士大人在战场上的成果比我出色、勇敢好几倍。请您一定要记得……自己是为了守护众多的人民与这个世界而拿著剑战斗。」

接著少女就用右手温柔地抚摸孝的背部。

对孝来说，不论是在现实世界或者虚拟世界，这都是第一次和女孩子互相拥抱的经验。但是他有预感，就算将来在现实世界有机会交到女朋友，可能也无法获得超过这个瞬间的感动了吧。

如梦境般的一瞬间过去，双方移开身体之后，孝便下定决心这么问道：

「那个……可……可以告诉我你的名字吗？」

结果僧侣见习生的白色脸颊微微染上红晕，并点了点头。

「好的……我叫作芙蕾妮卡。芙蕾妮卡‧谢斯基。」

「芙蕾妮卡……」

呢喃完这听来不可思议，但对眼前少女来说再熟悉也不过的名字后，孝很难得地用清晰的声音自报姓名。他说的不是威利欧斯这个角色名称，而是他不甚喜欢的本名。

「我的名字是孝……广野孝……那个……这场战争结束之后，还能见到你吗？」

芙蕾妮卡微微扬起眉毛，然后温柔地眯起下方的眼睛点了点头。

「那是当然了，骑士孝大人。等战争结束，和平到访的时候，我们一定能再见。我会向三神祈求您的武运昌隆。」

用娇小的双手轻轻包裹住孝的左手之后，芙蕾妮卡就迅速站起身子。

一边目送芙蕾妮卡翻转蓝色僧侣服下襬，为了治疗其他伤者而跑走的背影离开，孝一边产生强烈的意识。为了能挺起胸膛──以骑士的身份再次站在她面前，到最后一刻都要奋勇作战才行。这个世界已经不是游戏了。它拥有和孝出生长大的现实世界同样的质量，是另外一个现实。

即使在战斗中用尽HP，不对，是用尽生命而被从这个世界丢出去的时刻来临，在那最后一瞬间都要面向前方，持续握著手里的剑。不论受到多严重的伤、承受多激烈的痛楚都一样。无法办到的话，一定再也无法跟芙蕾妮卡见面了。

孝站起身子，叫了一声「要上了！」，然后不是为了游戏任务而是为了尽自己的使命而再次朝最前线奔去。

** 第二十一章 觉醒 西历二〇二六年七月七日/人界历三八〇年十一月七日

1

「赶得……上吗……」

比嘉健甩著过度使用而紧绷的双臂这么呢喃。

短短不到一个小时的时间里，就成功把从日本的The Seed网路突然送到O Turtle来的约两千个帐号转移到Underworld里。键盘的感触似乎还紧贴在双手的指尖上。

「一定能赶上的。」

神代凛子博士一边递出运动饮料一边以坚定的声音回答。

接过宝特瓶，以失去握力的右手辛苦地把瓶盖扭开后就大口喝了起来。即使流进嘴里的液体有些温热，还是确实地传递到身体的每一个角落。

喝完半瓶后呼一声吐出一口气，比嘉才无力地摇了摇头。

「真是的……我竟然这么粗心……」

从突然出现在RATH六本木分部的两名自称莉法与诗乃的女高中生那里，得知袭击者们准备让现实世界的美国人VRMMO玩家潜行到Underworld时，脑袋整整有五秒钟的时间停止思考。

但是听见察觉这一点的是结城明日奈手机所联结的既有型AI，比嘉也只能全面承认自己真的是毫无判断能力。

让自称是菊冈二佐朋友的两名高中生，从六本木的STL使用剩余的超级帐号潜行到Underworld，之后又进行庞大的转移作业，好不容易才把两千名援军降落到结城明日奈目前所在的座标。

如果不能排除总数超过五万的美国人玩家，「爱丽丝」几乎可以确定会被敌人夺走。实际上，了解现况的菊冈二佐与中西一尉，确实检讨过以人力爬上O Turtle外壁，然后直接破坏卫星天线的可能性。

但是想要前往外壁，就必须把上下隔开主轴的耐压隔板解锁长达数十分钟。要是被袭击者察觉这一点，很可能会招致连这间副控室都被对方压制的最糟结果。

因此菊冈与比嘉只能把一切托付给使用「创世三女神」帐号潜入Underworld的三名女高中生，以及甘冒丧失帐号危险而志愿参加援军的日本VRMMO玩家。

从接受他们连线的时间点起，Alicization计划的机密情报就已经有一半以上公诸于世了。

但是跟爱丽丝被袭击者们，以及应该在那些家伙背后操纵一切的美国军事工业复合体夺走，导致终将来临的无人兵器时代又被他们完全支配比起来……

这种事情已经算不了什么大问题了。

「没错……」

比嘉一边让身体重重沉进椅子里，一边以没人能听见的音量自言自语。

「爱丽丝已经不是一般用来控制UAV的AI了。她是诞生在真正异世界里的新人类……你早就了解这一点了。对吧……桐谷小弟。」

他把视线从表示Underworld南部状况的主视窗，移到角落显示桐谷和人摇光的萤幕上面。

微微摇动的放射光，中央的部分依然抱持著一片空荡荡的虚无。那是受伤后失去的主体……自我形象。

无法承受一直开著这个视窗，于是比嘉操纵滑鼠把视窗最小化。

在他击点左键之前，手指突然停了下来。

「嗯……？」

接著抬起圆眼镜，凝眼看著表示在视窗下方那个显示摇光活性的变动纪录。

短短四十五分钟前，至今为止没有任何变化的曲线图，刻划著唯一一个锐角。他急忙重新握好滑鼠，把纪录往左边拖动。结果回朔到十个小时前左右，还存在一个更大的锐角。

「凛……凛子学姊，过来一下。你可以看看这个吗？」

「别用那种称呼方式叫我。」

神代博士随著厌恶的声音把脸转向主萤幕。

「这是显示桐谷小弟摇光的萤幕吧？这个变动是什么？」

「应该是……显示他丧失的意识一瞬间有了活性，但是不应该发生这种不应该有的事才对。」

「你的日文太奇怪了吧──会不会从外部受到什么强烈的刺激？」

「但是，处理这种刺激的回路已经处于完全停止的状态了啊……嗯，这个时间是……」

比嘉击点锐角部分，让时间显示出来。但就算确认这个时间，也不知道此时Underworld内部发生了什么事。

但就在这个时候──

「等一下。」

神代博士发出带著紧张感的声音。

「这个时间。这个……两者都是那些女孩们用STL潜行的时候吧？第一个锐角是明日奈小姐，第二个锐角是出现在六本木的诗乃小姐与莉法小姐……」

「咦，真的吗……呜哇，真的耶。」

比嘉也屏住了呼吸。曲线图刻划了两个锐角的时间，确实正是女高中生们刚刚降临到Underworld的时候。

「咦，这是怎么回事……？单纯是显示『有熟悉的人出现，所以产生强烈反应』的情况吗？不对……桐谷小弟受到的，应该不是因为这种情绪上的理由就能恢复的伤害……一定有某种理由……某种物质、逻辑上的理由才对……」

从网状椅上起身后，比嘉就在操纵台前焦急地来回走著。或许是注意到他的气息，在稍远处椅子上真的已经累趴了的菊冈，以及瘫坐在墙壁边的众技术人员都用疑惑的视线看著他。

但是比嘉没有注意到他们，只是不停转动脑袋。

「自我……主体……自己规定的自我形象……某个地方存在其量子模式的备份……？不对，不可能啊……从来没拷贝过桐人小弟的摇光，就算拷贝了，也不可能做出从里面切割出自我形象并且写入的行为……能够和他的摇光连线的有效量子模式……在哪里……在哪里……」

「喂……喂，比嘉啊。」

叫了好几次比嘉的名字，他才终于抬起头来。

「什么事？」

「你之前就一直说的，主体的丧失，具体上是什么情形？」

「嗯……也就是呢……」

花了几秒钟来切换思考，比嘉才快速回答：

「『观察者、知觉者』……也就是心中的自己哟。以哲学来说，就是主体──客体问题。透过感觉所接受的，处理所有情报的主要处理程序。」

「哦……也就是说，你使用STL来统合唯物论与二元论喽。嗯，这不重要。我想说的是，所谓的主体和客体，真的能那么容易地分割开来吗？」

「……啥？」

这预料之外的发言，让比嘉不停眨著双眼。

菊冈和技术人员也持续闭著嘴巴，目前只有冷却扇低沉旋转声的房间里，流出神代博士沙哑的声音。

「知觉者、主体。被知觉者、客体。这只是表现事物之间关系的哲学概念，我不认为它们可以直接套用到我们每个人以摇光这种形式可视化的意识构造上。人类是社会性的动物，不是以唯一个人的形式存在于世上。自己心中的他人、他人心中的自己……你不觉得，这些在某种程度上都经由某种网路类型联结在一起吗？」

「他人……心中的……自己……」

转换成言语的瞬间，比嘉就自觉这个概念是属于自己最为忌讳的种类。

别人是怎么看待自己。和人比较起来又是如何。

神代凛子是怎么看自己的。

和茅场晶彦比较起来又如何呢。

──对喔……

──我连自己的脸都记不太清楚。如果要画自画像的话，大概会出现似是而非的成品吧。这是因为我一直避讳著自己──不论是外表和内在，就算再怎么挣扎都无法与茅场学长比较的狼狈模样。我心中的主体，不过是这种程度的东西罢了。

没错，收集周围的人心中的「比嘉健」并且合成起来的话，大概就能够完成相当高的重现度吧，我的主体不过就是这种程度的东西……

被摆了一道了，比嘉原本想露出混杂著自嘲的苦笑──

结果到这个时候才终于了解神代凛子发言的真意。

「……自我形象的备份。」

这么呢喃，然后瞬间抬起头来的时候，丢脸的自我厌恶感已经不知道消失到哪里去了。

「对喔……确实是有啊。有档案能够补完桐人小弟被轰飞的主体！就在他身边的人的摇光当中……！」

比嘉这么大叫，然后以快到极限的脚步左右走著。

「但是要抽出这些档案就需要STL……而且只有一个人的话重现度太单薄。至少要两个，不对，是三个……人…………」

比嘉用力吸了口气并且把它屏在胸口。

认识桐谷和人最深，灵魂里保存著详细印象的人物。那无疑就是结城明日奈了。而且她现在就躺在和人身边的STL里。

而六本木支部的STL里面，也还躺著两名应该与和人相当亲近的女孩子。

比嘉把视线朝向菊冈二佐，然后用沙哑的声音问道：

「菊老大。从六本木支部潜行的女孩子们……是与桐谷小弟有关的人吧？」

「……嗯，没错。」

菊冈也闪烁著黑框眼镜的镜片并点了点头。

「诗乃是在半年前的『死枪事件』里，和桐人一起解决问题的伙伴。而莉法则是桐人的妹妹喔。」

一瞬间的沉默之后，比嘉也让圆眼镜的镜片发出了光芒。

「……有了。有了哟，就是这个！没问题……桐人小弟的自我形象或许可以复原了！抽出应该保存在她们摇光内的桐人小弟的印象，然后和丧失领域联结起来的话……这有效档案就会融入桐谷小弟的摇光并且活性化，这样应该就能回复本来的主体了……」

在从身体深处涌起的热气驱动下，比嘉啪一声合起双手。

接著，一秒钟后──

这股热气就无声无息地被夺走，感觉身体逐渐变冷。

「啊……啊啊……不会吧……啊啊啊……」

「怎……怎么了，到底怎么回事啊，比嘉！」

把视线移往激动、快速地这么说道的凛子身上，比嘉像说梦话般呢喃著：

「能够进行这种操作的……就只有主控室而已呀……」

沉重的沉默再次像灰尘一样降落，累积在副控室的地板上。

这时发出深沉叹息的，是身为指挥官的菊冈。

「是啊……这是理所当然的事……哎呀，别这么沮丧嘛，比嘉。光是桐人小弟的治疗又出现光明就很值得高兴了。实际的操纵就等到状况结束，把那些家伙赶出O Turtle之后再进行也……」

「这样……就太迟了……」

依然低著头的比嘉打断了菊冈的话。

「突击队从护卫舰『长门』攻进来，在主轴内部发生大规模战斗的话，副电源应该也会断掉吧。说不定主控室的设备也会遭到破坏。当然，桐谷小弟的STL就会关机，而他也会在意识不明的状态下从Underworld登出。如此一来……恐怕桐人小弟就再也无法与STL连线了。因为现在的状态只是通过初期阶段而已……要治疗的话，无论如何都要在他和三个女孩子潜行于Underworld时实行才可以。」

平淡地这么说著时，比嘉再次感觉到身体深处逐渐涌起某种决心。

这种时候，自己会怎么办。

如果是稍早之前，比嘉的主体应该会这么回答。我怎么可能有办法。又不是茅场学长。

但是，这并不是真正的自我形象。只不过是在逃避，替自己找藉口。

如果是我所知道的比嘉健，那个设计出STL与Underworld的超级天才，一定会这么说才对。

「……菊老大，让我过去吧。」

「你说过去……是要去哪里？」

把身体整个转向身穿夏威夷衫绷起脸来的指挥官，比嘉用力吸了一口气之后才继续说：

「我不是想杀进被占领的主控室啦。听我说……现在旁边那间桐谷小弟所在的第二STL室和耐压隔板下面的主控室，是由贯穿O Turtle主轴船尾侧的光纤导管所连接起来。然后呢，光纤线路上应该有一处检修用的电子连接器。从第二STL室入侵导管然后从梯子下去，把检修用电子连接器接到笔电上，就可以操纵桐谷小弟的STL了。」

听见比嘉的点子后，菊冈一瞬间像要表示「我怎么没想到」般瞪大黑框眼睛底下的双眼，但立刻就恢复严肃的表情并且反驳：

「但检修用电子连接器确实是在分隔我们与袭击者之间的耐压隔板外面。想要到达连接器，就必须暂时解锁现在封闭导管的隔板。从主控室旁边的第一STL室也可以到达导管，被发现解锁的话我们的作战就会被识破，也有可能会被从下方攻击。」

「关于这一点，就用诱饵作战来解决吧。」

「你说……诱饵？」

虽然菊冈的眼光变得更加锐利，但比嘉很快地摇了摇头。

「当然不是投入贵重的人力哟。解除隔板的封锁之后……就让那个从导管另一侧的人类用阶梯冲进去。」

「原来如此……是『一卫门』吗？幸好那保存在上轴的仓库里。哪个人帮忙去把那个搬过来。」

在菊冈的指示下，坐在墙边听他们说话的两名工作人员就小跑步离开房间。另一方面，神代博士则用很担心的表情开口说：

「等等……你们说要拿一卫门当诱饵，但那应该还只能缓缓上下楼梯而已。不可能做出吸引敌人注意之后，立刻跑回来的动作。」

一卫门，正式名称是「Electroactive Muscle Operative Mae1」，它是人工摇光搭载用人形机械身躯的实验机。由聚合物人工肌肉来驱动金属骨骼，也就是所谓的人形机械人。由于是实验机，因此并没有附加任何漂亮的外装，机械与钢丝完全外露，所以一点防弹性能都没有。

昨天，被比嘉拜托帮忙调整一卫门自律步行用平衡器的凛子，嘴里虽然不停地抱怨著但还是相当认真地进行工作，所以对于「一卫门诱饵作战」应该也有一些想法吧。当然比嘉本身也感到很可惜，但现在不是舍不得这些机材的时候了。

「……虽然对一卫门很不好意思，但也只能让它拚一下了。不过，外表看起来是那种模样，敌人说不定会害怕爆炸而不敢一下子就开火射击。」

「……说得也是……」

当他们进行这样的对话时，电动门便横向移开，接著一台大型台车发出滚动的声音被推了进来。以蹲坐的姿势被放在上面的，是粗犷的头部装载了三个镜头的高大机器人。

神代博士以复杂的表情眺望著一卫门，然后立刻转过头来。

「……嗯，这种外表确实能发挥很大的功效，应该能让对方觉得我们有什么不得了的计划吧……」

「至少没办法无视它吧。趁著敌人对应一卫门的期间，我就入侵光纤导管下部，然后从检修用电子连接器操作桐谷小弟的STL。问题是，这家伙能争取到几分钟的时间呢……」

听见比嘉这么说的菊冈，就以交叉的脚尖晃动著木屐并且说：

「没办法干脆连『二卫门』都出动吗？」

「很可惜，那真的没办法。」

比嘉一边大动作耸著肩一边立刻这么回答。

「就机体性能来说，二卫门确实较佳，因为那家伙是完全以人工摇光来控制作为前提，和一卫门不一样，没有搭载自律平衡器。以目前的状态，刚开始下楼梯就会跌倒了吧。」

「这样啊……」

把视线从点著头的指挥官身上往右移，就发现凛子不知为何以奇妙的表情看著地板的一点，但马上就又以回过神来的模样询问：

「但是比嘉，就算可以用这招来蒙混过隔板已经解锁，你被发现的危险性也不是完全消除了吧。还是带著护卫一起到光纤导管去比较好吧？」

「……不，现在这个时候，自卫官工作人员是相当重要的战力。何况能在那么狭窄的导管迅速移动的，就只有瘦小的我而已吧。我会快去快回啦。」

虽然以平常的口气这么回答，但想像具体的状况之后，心跳就有点加快。

如果被敌人发现，从导管下侧开枪的话，根本没地方可以逃。O Turtle被袭击的时候，也是只听见枪声，甚至连敌人战斗员的模样都没看见。

──但是……

我……不对，应该说RATH这整个组织都欠桐人小弟一个很大的人情。

比嘉健再次把这个想法刻划在脑袋里面。

虽说封锁了记忆，还是强迫他在现实世界里进行了三天，Underworld内长达十年的潜行。可以说就是他给了人工摇光们重要的契机。突破界限的人工摇光「爱丽丝」之所以能诞生，绝对是因为和人从头到尾都与她有深厚关系的缘故。

加上之后虽说是为了治疗，但让他与解除限制的STL连线，结果导致他的摇光受到重大伤害。而且那是他为了保护爱丽丝而不断与支配Underworld的组织苦战，因此失去许多伙伴所造成。这样的话，只要有机会能治疗他，不论要冒什么样的危险自己都得挑战才行。不然的话，会一辈子没有脸见他。

比嘉健把双手紧握成拳头，然后对菊冈点点头。

就在这个时候──

第四道声音在副控室里响起。

「那个～……我也和比嘉主任一起去……」

众人视线所集中的目标是，至今为止一直坐在墙边垫子上的其中一名RATH技术人员。

个子与比嘉差不多矮小的他，把长长的头发在后脑勺绑成马尾。虽然提出这种相当有勇气的请求，却以有点僵硬的动作站起来，接著继续表示：

「我也是这样瘦巴巴的……不过，至少还能帮主任挡子弹吧……而且，至今为止一直保养导管等设备的，也都是我……」

比嘉认真地凝视这名以很难听清楚的声音说话的男性员工脸庞。

年纪比自己大许多，大概是三十五六岁左右吧。以搭乘O Turtle好几个月的人员来说，皮肤算相当白。记忆中他确实是从大游戏开发公司离职后加入RATH的人物。

战力上来说当然比不上自卫官，不过，有人能跟著自己内心就踏实多了。比嘉从椅子上站起来后，就对工作人员深深低下头来。

「……老实说，我也不太记得检修用电子连接器的位置在哪里了。那么就麻烦你跟我一起去吧，柳井先生。」

2

回归现实世界的加百列‧米勒从STL二号机当中缓缓抬起眼睑。

正确来说不是回归，而是遭到预定之外的放逐。依然躺在软胶床上的加百列，品尝著嘴里那些许的惊讶味道。

没想到自己会在虚拟世界的一对一战斗中落败。而且对手不是人类而是AI。

败给那个骑士的理由是什么，加百列花了贵重的几秒钟来思考这个问题。

意志的强度？灵魂的羁绊？连结人与人的爱情力量……？

──太愚蠢了。

加百列的嘴角出现微微的冷笑。不论是在现实世界还是虚拟世界，如果有什么看不见的力量，那唯一就只有──引导自己的命运之力。

也就是说，失败是必然的结果。因为有这个必要。命运希望加百列不要用暗神贝库达这个借来的虚拟角色，而是用他自己的模样来战斗。要求他以正确的方法再次降临到那个世界里。

这样的话，只要那么做就可以了。

加百列结束思考，无声地从床垫上走下来。

看向另外一台STL，就意外地发现副官瓦沙克‧卡萨鲁斯依然继续潜行著。原本以为他早已死亡并且登出，看来这个男人也又找到什么冀求的事物了吧。

──嗯，随他高兴吧。

耸耸肩后，加百列就打开通往隔壁主控室的房门。对著操纵台的平头队员抬起头来，对他发出毫无紧张感的声音：

「辛苦了，队长。哎呀，被干掉了呢。」

「状况呢？」

冷冷地这么一问，克里达就稍微改变表情，回覆了这样的报告。

「呃～按照指示依序投入从全美国找来的五万名玩家。目前虽然有半数已经损耗，但应该能达成歼灭人界军的目的。至于不确定的要素……就是RATH方也采取同样的手段……战场上确认到来自日本的大规模连线。数量大概是两千左右，应该不是什么太大的问题才对。」

「唔……？」

加百列扬起单边眉毛，然后抬头看著主萤幕。

上面表示著显示Underworld南部的地形图。从「东大门」一直线往南延伸，在×符号处中断的黑线，应该就是暗神贝库达，也就是加百列的移动纪录吧。虽然到达存在于世界南端的系统操纵台还有一半以上的距离，但爱丽丝现在应该还停留在×符号的地点才对。

而有一条粗大的白线像要追赶黑线般也跟著南下。这应该是人界军吧。现在紧密地聚在一起并且停止移动了。

由红色所表示的大军正准备击溃这些白色人界军。如果这就是美国人VRMMO玩家，那么在白色与红色之间像是防火墙般散开的蓝光──应该就是来自日本的两千名连线者了吧。

「这些日本人所使用的，是人界军的预设帐号吗？」

「我想应该是吧。怎么了吗？」

「没有……」

加百列一边把克里达递过来的宝特瓶矿泉水放到嘴上一边思考著。

日本的VRMMO中毒者们，真的有可能把一半的自己，不对，应该说把某种意义上比现实世界的自己更加重要的角色，直接转移到Underworld里面来吗？

不，怎么可能呢。加百列再度浮现冷笑。

在半个月前左右参加的，VRMMO「Gun Gale Online」日本伺服器的PvP大赛里，那些年轻人只拥有被加百列轻易全灭的实力，就算他们觉得有趣而连线到Underworld，应该也不愿意冒任何丧失自己角色的危险吧。

简短回想起大赛的最后一幕时，虽然那个被必杀的裸绞缠住依然到最后都不放弃的蓝发女狙击手稍微闪过脑袋，但加百列立刻把思绪拉回来。

「──好，我也要再次潜行。把这个帐号转移到Underworld去。」

在刚好放在系统操纵台上的纸片写上ID与密码并交给克里达后，他就出现奇妙的表情。

「哎呀，队长也是吗？」

「也……的意思是？」

「没有啦，瓦沙克那个家伙也曾经因为死亡而回来。但不知道为什么，露出一脸很高兴的表情，又转移自己的帐号潜行回去了。」

「……哦？」

加百列看向掉落在克里达脚边的纸片。在应该是瓦沙克ID的前头，可以看见并排的三个英文字母鲜明地浮现出来。

「……原来如此。原来如此啊。」

「呵呵」，加百列很难得地从喉咙发出真正的笑声。克里达则露出更为疑惑的表情，这时加百列拍了一下他的肩膀，然后说：

「不用在意。别看他那样，那个男人……应该也有自己的因缘要处理吧。那么，就拜托你了。」

在转身再次朝STL室前进的这段期间，加百列的嘴唇上依然一直挂著扭曲的笑容。

＊＊＊

同一时刻，瓦沙克‧卡萨鲁斯也在黑色斗篷底下咧嘴笑著，眺望著眼睛下方的战场。

站在遗迹参拜道路入口的神像头上，可以把美国人玩家与日本人玩家进行著血战的情况一览无遗。

不对，用正确的表现来说，应该是单方面的杀戮吧。

以参拜道路入口为中心，围成宽广半圆阵形的两千名日本人，在几乎没有损耗的情况下把杀到的红色步兵集团砍倒。虽然装备的性能与配合度也有很大的差异，但最重要的是后方支援体制的人数多寡。负伤的玩家立刻被运送到建构在参拜道路深处的阵地里，利用回复咒文来治愈伤势，然后又元气十足地冲回前线。

在存在和现实世界同等疼痛的Underworld，他们高昂的士气确实令人佩服。不过真要说的话，多达两千名玩家转移自己的主要游戏角色到此参战这件事本身就是很大的奇迹了。

这种连加百列‧米勒都认为不可能出现的状况──

瓦沙克‧卡萨鲁斯却几乎完全预料到了。

可以从美国连线的话，日本方面也会有人界军这边的援军前来才对。而瓦沙克也看穿他们应该会利用转移角色来作为援军。

他从现在骁勇善战的日本人玩家当中，认出除了「闪光」亚丝娜之外的熟面孔后，就打从内心感到高兴。

因为原本已经放弃，认为再也无法体验到的那个死亡游戏，竟然会以另外一种形式再次出现在自己眼前。

不对，当然即使在这个世界死亡，现实世界里的玩家们也不会被夺走真正的生命。

但是Underworld里，有那座浮游城当中不存在与存在的东西。

也就是──

存在著「痛苦」。

不存在「禁止犯罪指令」。

这样的话，应该可以大大地享受一番才对。或许可以获得更胜于亲手夺走生命的兴奋。

「呵呵、呵呵呵、呵呵呵呵……」

再也忍不住的瓦沙克从斗篷底下发出隐密的笑声。

＊＊＊

──没赶上吗？

诗乃无言地凝视著壮年剑士浑身是伤的尸骸，以及趴在上面哭泣的黄金女骑士。

骑士身边有两头巨大的飞龙像是同样感到悲伤般低垂著头。

为了赶上影响整个世界命运的「光之巫女」爱丽丝、掳走她的暗神贝库达，以及追赶两个人的骑士长贝尔库利，诗乃拚尽全力飞行。虽然发挥在ALO里猛烈特训过的任意飞行技术，以系统允许下的极限速度朝著南方前进，但终于追上的时候战斗早已结束了。

不对──这时应该称赞的是贝尔库利的力量吧。

因为他不但追上贝库达不可能被赶上的飞龙，甚至还击毙了应该不可能死亡的超级帐号。

但是，这里有一件很非常不合情理的事情。

就是骑士长贝尔库利死后，他的灵魂将永远消失。但是同样死亡的暗神贝尔库利，灵魂却不是这样。

这时爱丽丝好不容易停止哭泣，不过还是虚脱般低著头，虽然诗乃必须告诉她危机不是这样就消失，但是却不知道如何开口。

珍贵的数分钟在沉默当中流失，结果先出声的是骑士爱丽丝。

诗乃不由得因为爱丽丝即使被泪水濡湿了脸颊，还是凄绝美丽的模样屏住呼吸，而爱丽丝则用宛如水面般的闪亮钴蓝色眼睛直视著她。樱桃色嘴唇微动，发出银铃般的声音：

「你也是……从现实世界来的吗？」

「嗯……」

诗乃点点头，好不容易才开口说：

「我叫诗乃。是亚丝娜和桐人的朋友。原本是为了从暗神贝库达手里救出你和贝尔库利先生……但很抱歉，没能赶上。」

爱丽丝对跪在留下激斗痕迹的岩山上低下头来的诗乃静静摇了摇头。

「不……是我太愚蠢了。全是没有警戒背后，像个小孩子一样被绑走的我不对。叔叔的……伟大的整合骑士长的性命，跟我这种人的生命明明根本无法相比。」

声音里带著的深切悔恨与自责，让诗乃顿时说不出话来。爱丽丝以拚命忍住泪水的表情，提出了另一个问题：

「目前的战况如何？」

「……亚丝娜和人界军，正想尽办法防堵著现实世界来的红色军队。」

「这样的话，我也回北方去吧。」

爱丽丝摇摇晃晃地站起身子，朝著其中一头飞龙走去，结果诗乃叫住了她。

「不行喔，爱丽丝小姐。你直接朝南方的『世界尽头的祭坛』前进。触碰祭坛上的操纵台……不对，触碰水晶板的话，现实世界那一边应该就会呼唤你。」

「为什么？皇帝贝库达已经死了吧。」

「……事情……不是这样的。」

接著诗乃便向爱丽丝说明了一切。现实世界的人，就算在Underworld死亡，也不会真正失去生命。寄宿在皇帝贝库达身躯里的敌人，现在这个瞬间也很可能会得到新的身体再次袭来。

至于爱丽丝本人，就像是至今为止好不容易才压抑住的所有感情一口气爆炸一样，表现出剧烈愤怒的反应。

「你说叔叔他……不惜舍弃性命与他同归于尽的敌人竟然没死？只是暂时消失，之后又会像什么事都没发生过一样苏醒……你的意思是这样吗？」

黄金铠甲发出「喀锵」一声后，爱丽丝整个人逼近到诗乃身边。

「怎么……怎么可能有如此荒谬的事情……！这样……叔叔究竟是为什么……为了什么而必须牺牲性命呢！另一边根本不用赌命的对决，简直……简直就像一场闹剧嘛…………」

诗乃只能凝视著蓝色眼睛里再次涌出泪水。

在GGO和ALO的战斗里，已经不知道死过多少次的我。而在这个世界也和暗神贝库达一样即使丧命也不会真正死亡的我──

──没有资格说些什么。

但是诗乃还是用力吸了口气，然后确实看著爱丽丝的双眸说：

「这样的话……爱丽丝小姐，你是说桐人的痛苦也是虚假的喽？」

瞬间，黄金骑士猛烈咽下气息。

「桐人也是现实世界的人喔。即使在这个世界丧生，也不会失去真正的生命。但是，他受的是真正的伤害。他感受的疼痛、受伤的灵魂全都是真货。」

又隔了一会儿，她的嘴唇便露出淡淡的笑容继续表示：

「……我喜欢桐人。非常喜欢。爱丽丝你也一样吧。其他还有许多喜欢他的人。这些人全都在担心桐人。拚命地祈求他能恢复健康。而且，嘴里虽然不说，内心也都想著『为什么桐人得牺牲到这种地步呢』。」

诗乃轻轻地把手放到爱丽丝双肩上，然后以清晰的声音说：

「桐人会受伤都是为了救你喔，爱丽丝。就为了这一点，他便努力到让自己变成那样。你真的要连他的心意都说是虚假的吗……？不，不只有桐人。骑士长先生也是一样。为了救你而这样浑身是伤，牺牲性命制造了这个机会，帮忙争取到让你从敌人手中逃脱的时间。」

诗乃没有立刻得到回答。

爱丽丝默默地凝视著贝尔库利躺在地上的尸骸好一阵子。

眼里再次落下斗大的泪水──接著黄金骑士用力闭起眼睛，像在忍耐什么一样抬起脸来。直接以沙哑的声音发问：

「诗乃。我……我从『世界尽头的祭坛』到现实世界去之后，还能再次回到这个世界来吗？可以再次跟心爱的人们见面吗……？」

诗乃心中没有相关的知识可以确实回答爱丽丝迫切的问题。可以确定的，就只有爱丽丝落入敌人手上的话，整个Underworld就会遭到破坏、消灭。

只要保护世界和爱丽丝，愿望就一定能实现。现在只能这么相信了。

所以诗乃缓缓点了点头。

「嗯。只要你……以及这整个地底世界平安无事的话。」

「……我知道了。这样的话，我就往南方前进吧。虽然不知道『世界尽头的祭坛』有什么在等著我……但如果这就是叔叔以及桐人的意志……」

爱丽丝轻轻扬起白色裙子跪了下去，温柔地抚摸了一下躺在地上的贝尔库利的头发，接著在他额头一吻。

当站起身时，女性骑士全身就散发出变了一个人般的气息。

「雨缘、泷刳。再努力一下喔。」

对两头飞龙这么搭完话，爱丽丝就把视线对著诗乃。

「诗乃小姐……你接下来有什么打算？」

「这次换我使用这条生命了。」

诗乃咧嘴对她露出微笑，接著又说道：

「我想暗神贝库达会在这里复活。我会尽可能打倒他……至少也要帮你争取到充足的时间。」

爱丽丝轻咬嘴唇，低下头来说：

「……拜托你了。我绝不会浪费你的心意。」

目送往南方飞去的两头飞龙离开之后，诗乃把挂在右肩上的长弓拿回手上。

据说袭击O Turtle的很可能是由美国政府机关所支援的民间军事公司。而其中一名战斗人员寄宿在超级帐号04──暗神贝库达身上袭击了爱丽丝。

现实世界里只不过是一名高中生的诗乃，实在无法对抗这样的对手。

但如果是在这个地方。如果是虚拟世界的一对一战斗的话──

不论来者是谁自己都会获胜。

向自己做出如此坚定的誓言后，诗乃便等待著敌人再次潜行至此的瞬间。

＊＊＊

从挥尽的右拳上，传来最后的骨头折断的清脆声响。

拳斗士团团长伊斯卡恩，把视线从护胸正中央被打穿后呈大字形倒在地上的敌人移开，无言地眺望著自己的右手。

在那里的已经不是能够打碎所有物体的钢铁拳头。有的只是粉碎的骨头、撕裂的肌肉，以及血液阻塞后肿起来的松垮皮囊。

左拳在稍早之前已经陷入同样的状态。双脚也已经沾满鲜血而且全是瘀青，不要说踢人了，根本连走路都不可能。

「……冠军，你战斗的模样真是威猛。」

副官达巴沙哑的声音让伊斯卡恩往后面瞄了一眼。

瘫坐在地面的巨汉，在失去双臂之后依然持续只以头锤与身体冲撞来战斗，脸庞与身上那多道的刀伤就是最佳证明。经常散发斗志与智慧光芒的双眼已变得朦胧，显示达巴的天命已经快要用罄了。

伊斯卡恩为了向勇士的灵魂表达敬意，举起碎裂的右拳回答：

「哎，这种死法，接下来在另一个世界遇见先代团长也不会丢脸了吧。」

他拖著脚来到副官身边，像崩塌般坐了下来。

超过两万人的红色军队，经过长时间的激战后已经减少到只剩下三千人左右。但代价就是拳斗士团也仅仅剩下三百人左右。而且所有人都是满身疮痍，已经无法顺利组成阵型，只能聚在一起等待被对方击溃的命运。

团团包围住他们的三千敌兵，之所以没有一气呵成发动最后的突击──

全是因为在伊斯卡恩与达巴视线前方，宛如战神般持续战斗著的一名骑士与一头飞龙的存在。

＊＊＊

肉体与精神的消耗早已超过界限。

整合骑士谢达‧辛赛西斯‧推鲁弗即使在这种情况下，只要模糊的视界里出现敌人的影子，就还是会动著宛如铅块一样重的右臂，挥舞著黑百合之剑。

「咻」一声迟钝的风声。

极细的剑身刺进敌人铠甲的肩口。后座力让她从手腕到手肘都爆出像是被无数细针刺中般的痛楚。

「喝……啊啊啊啊啊啊！」

从喉咙里挤出完全不符合「无声」绰号的沙哑吼叫声。剑好不容易割开厚重装甲，把底下的肉体一直线撕裂。

从随著听不懂意思的咒骂倒下的敌兵身上抽出剑身后，谢达急遽喘著气。

如此疲惫困顿的理由，除了敌人似乎是无限的数量之外，还有刺中红色士兵们时的奇妙手感。

心念很难发生作用。明明武器和铠甲和谢达的神器比起来都是优先度远远不及的物品，但是在砍断之际都会有令人不快的抵抗感。敌人的攻击也有同样的感觉。明明尽是一些靠著蛮力所挥出的粗劣斩击，但不知道为什么就是很难看出动向。

简直就像在和影子战斗一样。宛如从远方把这些其实不在现场的人映照到这里的皮影戏军队。

和他们的战斗一点都不有趣。谢达自觉应该只为了斩杀而生的自己，对于杀害这些影子有强烈的厌恶感。

──为什么呢？

──不论对手是影子还是真人，甚至只是一般的石像，只要坚硬应该就能满足我才对。我明明是只知道斩杀的人偶……

极细剑身里带著最高等级优先度的神器，黑百合之剑。它是只为了切断而造出的道具，同时也是谢达自身的影射。停止斩杀的话，将会完全失去存在的意义。

谢达从暗黑界的古战场带回来了一朵黑百合，最高司祭亚多米尼史特蕾达改变它的分子结构后变成一把剑。然后把它下赐给谢达并这么说。

──这把剑是把刻划在你灵魂的诅咒变成实体后的成品。从性状遗传参数的变动中产生的，名为杀人冲动的诅咒。就用它持续不断地斩杀吧。或许……只有在那条充满鲜血的道路尽头，才存在解除你诅咒的关键。

那个时候，谢达不了解最高司祭这么说的意思。

谢达按照她所说的，在几乎等于无限的岁月当中不停地斩杀。而现在终于遇见了最棒的敌手。那是比至今为止透过剑刃接触的任何人、任何物体都要坚硬的一名拳斗士。

想再次和那个人一战。因为和他战斗的话，或许终于可以了解些什么。

只是在这个冲动的驱使下，谢达就和人界军分离而留在这座战场上。但是，看来已经无法再次和那名红发的拳斗士战斗了。

把仅剩下的一口水灌进喉咙，她便一边把空皮袋丢掉一边往后方瞄了一眼。

结果看见满身伤痕的拳斗士族长坐在远处的岩石上。左眼里不知为何浮现悲伤感情的他，也一直往谢达这边望过来。

胸口忽然感到一阵刺痛。

──这股疼痛是怎么回事？

──我明明想砍掉那个人。想再次体验那种能够烧尽一切般的战斗，也想斩断那比金刚石还要硬的拳头，明明只有这些才是我的愿望。但是我的胸口……为什么会像这样被揪紧呢……

哔叽。

右手忽然传出细微的声音。

谢达举起黑百合之剑，无言地望著它。彷佛吸尽所有光线般的漆黑剑身中央，出现了一道比蜘蛛丝还要细的裂痕。

啊啊……

原来如此。

谢达大大吸了口气，然后露出微笑。

现在所有的疑问都解开了。谢达终于领悟，亚多米尼史特蕾达所说的话的意思，以及所谓的诅咒究竟是什么了。

把视线移回沉重的地鸣上，就看见接下来的敌兵正举著粗犷的战锤往这边突进。

谢达以流畅的脚步回避敌人的初击，右手的剑跟著刺进红色铠甲中央。

最后的攻击简直没有一丝声音。像是滑入心脏一般，柔韧地结束敌人生命的黑百合之剑──从中段附近化作无数黑色花瓣，到最后都没有发出任何声音就碎散开来。

谢达像是感到很惋惜般，把手中纷纷崩落的剑柄靠近嘴边并且呢喃：

「……长久以来，谢谢你了。」

一瞬间，似乎有清爽的花香飘荡在空气中。

长年跟在身边的骑龙宵呼，这时正在右侧以尾巴的一击轰溃敌兵。

灰色鳞片因为从无数伤口溢出的血而染红，爪子与牙齿也几乎都掉光了。热线早已吐尽，动作也缓慢到让人难以置信的地步。

确认敌人的突击暂时中断，谢达就走到爱龙身边，把右手顺著它的脖子抚摸著。

「也要谢谢你，宵呼。你累了吧……可以休息了。」

接著谢达和飞龙就互相帮助对方，朝著拳斗士团残存者聚在一起的低矮山丘前进。

依然坐在地上的拳斗士族长，举起肿得像是立刻要爆开的右手来迎接谢达。

「抱歉……让你把那么重要的剑弄断了……」

听见对方的道歉，谢达就摇了摇头回答：

「没关系。因为我终于知道，自己为什么要持续斩断所有东西了……」

谢达双脚一软就跪到地面，然后抬起双手，用十只手指静静夹住年轻斗士的脸。

「是为了寻找不想砍的东西。为了找到想守护的东西，我才会持续战斗。而那就是你。所以已经不需要那把剑了。」

一瞬间，从拳斗士瞪大的左眼中涌出透明的泪水，谢达则是有些惊讶地凝视著这一幕。

年轻人用力咬紧牙关，一边响著喉咙一边呢喃著：

「啊啊……可恶。真想跟你结婚生子。一定可以生出很强的小鬼。可以比前任还有我更强的最强拳斗士……」

「不行喔。我要让那个孩子成为骑士。」

两人简短地凝视对方，然后同时露出微笑。在露出温柔表情的巨汉守护下，谢达和伊斯卡恩一瞬间互相拥抱，接著并肩坐在一起。

三百名拳斗士和一名整合骑士以及一头飞龙，就这么默默地等待红色士兵一点一点地缩小包围网。

＊＊＊

「这下看来是……大势已定了。」

亚丝娜听见同时回到后方阵地的克莱因这么说，就回答了一声「是啊」。

担任魔法职的日本人玩家，以刚学会的神圣术治愈出现几处负伤的两个人。虽然无法模仿正职的Underworld人修道士那种利用心念来增幅效果的技术，但因为是把高等级角色转移过来，所以拥有相当高的术式行使权限，以需要的治愈力来说已经相当足够了。

「谢谢你来帮忙。」

对女性术师玩家道完谢，亚丝娜也同样对身边的克莱因这么表示。

「也要谢谢你，克莱因。不知道该怎么感谢你才好……」

克莱因看著说不出话来的亚丝娜，有些不好意思般摩擦著鼻子下方。

「喂喂，太见外了吧。我欠你和桐人那个家伙的人情，不是这点小事就能还完的吧……那家伙也在吧，人在哪里？」

亚丝娜静静对压低声音的克莱因点点头。

「嗯。战斗结束后就让你们见面。要视克莱因丢出平常那种无聊的冷笑话，他说不定会因为忍不住想吐嘈而醒过来呢。」

「啊～太过分了吧。」

即使以常见的开朗表情露出笑容，克莱因眼里还是带著深沉的担心。他也早就已经知道，桐人的灵魂受到重伤的事情了。

──啊啊，不过，说不定……

顺利解决一切事情，将敌人从O Turtle里击退，在诗乃、莉法以及克莱因等前SAO攻略组、朔夜与亚丽莎等ALO组……以及爱丽丝、罗妮耶、索尔缇莉娜等人包围之下，桐人就真的会忍不住张开眼睛了。

为了能在那个瞬间用笑脸迎接他，现在必须得好好努力才行。

伤势一痊愈，亚丝娜就再次向术师玩家道谢然后站起来。

正如克莱因所说，战斗可以说大势已定。红色美国人玩家的数量已经减少到跟日本人差不多，像是丧失战意一般只是不停进行自暴自弃的突击。

但是，这座古代遗迹的战斗只不过是前哨战而已。

问题是被皇帝贝库达绑走的「光之巫女」爱丽丝。在骑士长贝尔库利以及诗乃想办法绊住他脚步的时候，必须追上皇帝并且把爱丽丝夺回来才行。到时就从转移组里面组织最精锐的队伍，然后借人界军的马全速南下。

只要能追得上，就算敌人使用的是超级帐号，也不可能敌得过集结日本顶尖玩家所组成的代表队。他们就是具有能让亚丝娜如此断言的压倒性力量。勇猛作战的剑士们，长剑、盾牌与铠甲反射阳光后发出七彩光辉的模样，简直就与北欧神话里的英灵战士一样……

拭去快要渗出的泪水，亚丝娜把视线从前线移到最后方去。

遗迹参拜道路入口附近，补给队的马车也从深处被拉出来，建构出即席的阵地。受伤的日本人被Underworld人用术式治愈的模样，也让人有种无法用言语形容的神圣感。

「……没问题，一切都会顺利的……一定会。」

旁边的克莱因也强力地肯定亚丝娜的自言自语。

「是啊。那么，我们也再去努力一下吧。」

「嗯。」

点点头后就再次转向最前线的亚丝娜──

注意力被掠过视线角落的某样东西吸引，倏然停止动作。

──是什么呢。某种，又黑……又暗，像污渍般的……

让视线徘徊了一会儿的亚丝娜，终于找到了那个东西。

并排在参拜道路路口的巨大神像。

其右侧最前面的石像头上站著某个人。

因为逆光的缘故看不太清楚。像是从黑暗领域的红色天空中渗出一般的摇晃黑影。

是从战场逃走的美国人吗？还是自愿前去侦查的日本人？

疑惑的亚丝娜凝眼一看，就了解那道剪影之所以会诡异地摇晃，是因为罩著一件黑色短版斗篷的缘故。由于兜帽被深深拉下来，所以完全看不见对方的脸。

但是……

「克莱因啊，你不觉得……」

克莱因准备往前线跑去时，亚丝娜就一边拉著他的衣袖一边伸出左手。

「站在那里的那个人，有种似曾相识的感觉？」

「咦……？哎呀，竟然在那种地方看好戏。真是的，到底是谁啊……问我有没有见过嘛，穿著那种雨衣的话，脸……怎么……」

克莱因的声音突然中断了。

亚丝娜把视线移过去，就看见满是胡渣的脸已经苍白得跟纸一样了。

「喂喂，你是怎么了。你想起来了吗？那个人是谁？」

「不……不可能。不可能有这种事……我看见……亡灵了吗……？」

「亡……亡灵……？这是怎么回事？」

「因……因为，那件黑雨衣，不对，是皮革斗篷……是微笑棺木的……」

听到这个单字的瞬间──

亚丝娜也有脑袋中央逐渐变得像冰一样冷的感觉。

微笑棺木。正式名称「Laughing Coffin」。从死亡游戏SAO的中期到后期，一直在浮游城艾恩葛朗特里散布恐惧的最强杀人者公会。

「赤眼沙萨」与「Johnny Black」等知名PKer多隶属于该公会，他们对无数的一般玩家伸出毒手……最后在与攻略组玩家的共同讨伐队进行死斗后遭到毁灭。

那场战役之后，几乎所有微笑棺木的成员都不是战死就是被送进黑铁宫里，但是只有一个人成功脱逃了。不知道为什么突袭的基地当中看不到公会会长，那名不论是直接、间接都是在SAO内杀了最多玩家的男人。而他的名字是──「PoH」。

经常穿著黑色皮革斗篷，装备著切肉菜刀般大型刀具的杀人鬼，经过两年的时间后，在Underworld当中低头看著亚丝娜与克莱因。

「…………不会吧。」

亚丝娜也只能用沙哑的声音这么呢喃。

那是幻觉。自己看见亡灵了。

消失。快消失啊。

但是在太阳热气底下摇晃的黑色剪影，就像是在嘲笑亚丝娜的愿望一般，缓缓地抬起右手。然后以调侃的动作轻轻左右挥了挥。

接下来的光景──

可以说是至今为止遭遇的最恐怖的恶梦。

黑色斗篷的身边，像渗出来一样出现了两三条新的人影。

接著神像背后邻接的巨大遗迹宫殿屋顶，就出现了一大群红色集团。左侧的宫殿屋顶上，一下子就涌出数十人规模的影子。

────不要啊。已经够了。

亚丝娜拚命地祈祷。她的心灵已经无法承受更多的绝望了。

但是……

新出现的红色军队，却像是永无止尽般不停涌出。一千、五千、一万人。

终于超过三万人时，亚丝娜就放弃掌握人数了。

不可能。

才刚让多达五万名美国人玩家伴随著痛苦登出Underworld而已。应该不可能在这么短的时间内重新准备如此庞大的军队。而且也不可能是日本人。要是在日本以假网站诱导玩家前来Underworld的话，克莱因他们一定会率先注意到才对。

这是幻觉。那全是用术式制造出来的，没有实体的影子。

不知不觉间，在前线和美国人玩家的战斗中几乎已经获胜的日本人玩家们也停下手回过头来。广大的战场上，垄罩在奇妙的寂静当中。

鼓噪鼓噪。鼓噪鼓噪。

完全掩盖宫殿屋顶的红色庞大军队所散发出来的鼓噪，彷佛不祥的风声般传到亚丝娜耳朵里。

无法立刻听出混杂、融合在一起的声音是什么语言。拚命竖起耳朵之后，才好不容易听出由几道较大的声音说出的句子。

……우리나라를지키라（保护我们的国家）

……피겁한일본인（卑鄙的日本人）

……干掉你们。

那不是英文。也不是日文。

这个时候，旁边的克莱因以几不成声的声音呢喃著：

「啊啊……糟糕……这下糟了……那群大军的来源不是日本也不是美国……」

亚丝娜一边感觉冷汗从背后流下，一边听著他接下来的话。

「…………而是中国与韩国。」

3

首尔市钟路区清进洞的某间VR房，可能是因为附近的大学才刚放暑假的缘故吧，里面显得有些混杂。

完成入店手续，在饮料吧用纸杯装了可乐之后，赵月生就在包厢的总统座椅上躺下来，然后呼一声吐出长长一口气。

感觉最近时常叹气。理由他自己也清楚。今年二十岁，大学二年级的月生，到了明年就得休学进入军队服两年兵役。

因为只要三十岁之前入伍就可以，所以如果想延役的话也完全不成问题，但没有在就学中完成兵役的学生，在求职时将背负极为不利的条件。身边的学生们几乎都在二年级时休学并且入伍服役，父母亲也要自己这么做，所以也无处可逃了。

啜了一口碳酸不足的可乐后，再次叹了口气。

虽然也对没有体力的自己能否撑过严格的训练、会不会在部队里遭受霸凌感到有些不安，但最让人忧郁的是要被夺走现在的生活长达两年的时间。不过他所说的并非现实世界的生活。而是刚入学在朋友邀约下有了初次体验之后，就持续让月生著迷的虚拟世界──没有办法潜行到里面，对他来说可能比任何训练都要痛苦。

「…………部队里如果能有这个……」

这么呢喃完后，就拿起挂在桌子挂物架上面的完全潜行用机器──「AmuSphere」。因为是许多人利用的VR房里的备品，所以不论外装或者内装都相当老旧，但在月生眼里它还是发出像天使光环般的亮光。

三年前在日本──二〇二三年发售的这台机器，隔年就开始在全世界贩售，即使在原本线上游戏就相当兴盛的韩国也造成了很大的轰动。原本被称为「PC房」的网咖不断变成设有AmuSphere的「VR房」，年轻人们都为日本制或美国制的VRMM而著迷。

月生持续玩了一年半的「新罗帝国」，也是在韩国厂商将日本开发的「飞鸟帝国」本土化后发行的游戏。不只是将内容翻译过来，连街道、角色以及任务内容都修改成韩国古代的新罗王朝，开始营运之后一直保有最受欢迎游戏的地位。

另一方面，玩家之间也一直传出希望能有纯国产游戏登场的声音，也有不少企业准备利用完全免费的「The Seed」程式套件来开发新VRMMO游戏。但是该程式套件本来就是日本制，而且也有不连线到建构在日本的庞大「The Seed连结体」就无法发挥所有机能的问题，但是现在日本的VRMMO又几乎都阻绝来自韩国与中国的连线。因此一直很难有品质能与「新罗」等输入游戏并驾齐驱的新作，韩国人玩家目前持续处于欲望无法得到满足的状态当中。

──看来在入伍之前玩到国产游戏的愿望是无法实现了……

把这样的思考随著再次的叹气屏除在外，月生重重倒到座椅的椅背上后，就将AmuSphere戴到头上。

「……开始连线！」

说出唯一全世界共通的声音指令，接著闭上眼睛。

穿越七彩放射光，输入VR房的使用者ID与密码，降落到个别捷径工具空间的月生，立刻准备击点新罗帝国的图像。

但是在那之前，就注意到浮现在黑暗空间右侧的SNS视窗，正以猛烈的速度卷动。看来是追踪的数百个帐号，全都持续在回推同一个消息。

「…………怎么了？」

觉得奇怪的他把捷径工具组移到左边，将SNS移到正面。点了一下消息并且加以扩大。接著发出声音念出显示在上面的推特。

「嗯……韩国、美国、中国的民间志愿者共同创立的全新VRMMO封测伺服器……现在被日本玩家骇入，封测玩家正遭到攻击……！有这种事？」

老实说，内容有点让人难以相信。但是推特尾端附上了似乎是影片的URL，于是月生就在半信半疑的情况下点击网址。

播放视窗打开，下一刻──

「前卫，突击！」

传出大声量的勇猛叫声。对于经常观看日本动画的月生来说，光听声响就立刻了解那是日文了。

画面上，身穿银色装备，看起来像日本人的玩家们，正在袭击全身是暗红色装备的玩家，然后不断把他们干掉。每当发出光芒的剑挥动就会有大量鲜血飞溅，接著是英文的咒骂声与悲鸣响彻现场。

由于完全没有对残酷表现加上限制，所以这是封测伺服器不会错了。正如推特上所写的，日本人玩家看起来正单方面虐杀美国人玩家。

经过三十秒，动画结束之后，月生有好一阵子都处于茫然状态当中。

说到「伺服器攻击」，一般都是增加负荷来让营运停止，或者是窜改网站，还是第一次听说……直接潜入VR世界，对封测玩家进行实际攻击的例子。如果相信动画内容的话，情况应该正如消息当中所描述，但不知道为什么就是有种不对劲的感觉。

没错……影像里装备性能与能力值都占上风的日本人玩家几乎是单方面驱逐著美国人玩家。但是飘荡著拚命气氛的，并非遭到攻击的美国人，而是发动攻击的日本人。伺服器攻击明明是相当常见的恶搞，看起来却像真正的……赌上性命的战斗……

这时候，响起「哔啵」这种尖锐的铃声，让吓了一跳的月生抬起头来。

注意到月生上线的「新罗」内公会的伙伴，向他提出语音聊天的要求。按下允诺键后就出现新视窗，一道迫切的声音呼唤著月生的角色名称。

「喂，Moon Phase，你看到那条推特了吗？」

「嗯……嗯嗯，刚才看到了……」

「那你怎么还这么悠闲，快点下载用户端程式啊！」

「用……用户端程式？」

急忙把视线移回SNS上，让推特接下来的消息显示出来。

上面写著──为了营救遭到日本人卑劣攻击的封测玩家，现在征求韩国的VRMMO志愿者。希望愿意提供帮助者下载连线用用户端程式，并且安装到AmuSphere里面。

「……这个吗……──桓雄，你觉得这是真的吗？」

「那还用说吗，你没看到刚才的动画吗？在跟你说话的这段期间，我们的同胞也正被杀害啊！」

「我是看了……但是，那个动画……」

月生虽然准备说明刚才内心不对劲的感觉，但马上就被打断了。

「别管那么多了，快点安装吧！明完和Heli都潜行进去了，我也在那边等你喔！」

结束语音聊天后，捷径工具空间就被寂静所包围。

虽然还有许多无法接受的部分，但公会伙伴好像几乎都参加了，所以要是这样无视到底的话，之后不知道会遭受什么样的批评。潜行进去看看应该就能获得更多情报吧──而且，仔细一想就觉得，也有可能这场骚动全都是那款新游戏的突发性活动。这样的话，不去参加的话就亏大了。

下定决心的月生点击下载键，接著将用户端程式安装到AmuSphere里后，捷径工具组就出现新的图标。点击只在红色且没有图案的背景并排著「HELP US」几个黑字的图标，月生的意识就被吸进另一个世界里去了。

＊＊＊

克里达即使把来自中国与韩国的大量连线引导至Underworld，也依然处于半信半疑状态。

按照瓦沙克‧卡萨鲁斯再次潜行前的指示，也在位于日本西北方的两个国家里撒下大量的Underworld连线用用户端程式，但是在作业当中有好几次都感到怀疑。

──因为，日本人和韩国人不是都一样吗？

在美国，有许多人不知道日本与韩国的国土没有邻接。也有人认为它们都是中国的一部分。克里达虽然没有那么夸张，但一直认为三国是相当友好的国家。不像EU的国家之间那样有错综复杂的关系。

所以克里达完全无法理解瓦沙克留下来的指示。

由于没有时间制作新的假网站，所以便利用SNS来扩散情报。一开始的推特，内容是「由美中韩的志愿者共同创立的私人VRMMO伺服器遭到日本攻击！」。

接著又在推特上加了「想独占The Seed连结体的日本人玩家骇入伺服器，擅自产生强力的角色来攻击美国、中国与韩国封测玩家。伺服器里还没有疼痛缓和装置与伦理规范，因此同胞们正随著剧烈的痛苦遭受虐杀」的说明，然后又上传撷取自Underworld之内的战斗影片。

映照出来的，其实是人界的骑士与士兵击退美国人玩家的画面，但Underworld人也是说日文。影片似乎造成相当大的冲击，回推数以猛烈的速度增加，美国玩家下载用户端程式的速度根本完全无法比较。

哑然的克里达心里想著。

──这种情况，简直就好像日本和中国‧韩国的VRMMO玩家的感情不好嘛。

＊＊＊

──看起来，甚至可以说彼此之间互相憎恨呢。

以过去率领杀人公会「微笑棺木」时的角色──「PoH」再次潜行到Underworld的瓦沙克‧卡萨鲁斯，黑色兜帽底下的脸庞咧嘴浮现出笑容。

他高举起右手，用韩文对著背后红色玩家们大叫：

「──给那些入侵者好看！好好地痛宰他们，让他们再也不敢对我们的同胞出手！」

应该不下五万人的庞大集团，随即以两种语言爆出愤怒的咆哮。在他们眼里，遭到日本人玩家杀害的美国人集团，应该都变成同国籍的封测玩家了。

瓦沙克忍受发出哄笑的冲动，猛烈地挥落右手。

发出「沙啊啊啊啊啊！」的雪崩般声响，深红的庞大军队朝著眼睛下方的日本人跳下去。

──来吧，互相残杀吧。丑恶地、狼狈地、滑稽地跳舞给我看。

＊＊＊

「……来了。」

诗乃在嘴里这么呢喃。

终于可以看见黑色虚线如丝线般往这里延伸。

这个时间点已经把「歼灭光线」装填到最大威力，希望能在敌人实体化之后就立刻把他轰飞。这样的话，应该就无法防御与回避才对。

但是，现在应该做的是帮忙争取时间。如果敌人可以无限生成高等帐号的话，立刻让他死亡根本没有意义。

先让对方与自己进入持久战，然后确认敌人的对应。如果露出珍惜生命的模样，就能判断是只可使用一次的宝贵帐号。那个时候再全力攻击，让他再也不能用同一个帐号登入就行了。

但是，万一是量产型的帐号，就不能直接把他杀掉。必须尽可能把战斗延长下去，帮爱丽丝争取移动到「世界尽头的祭坛」的时间。

因此诗乃没有拉动弓弦，只是在空中盘旋等待著敌人完成实体化。

黑色符号线条降落到几分钟前骑士长贝尔库利的遗体所躺著的地点。

整合骑士爱丽丝把骑士长的遗体放在另一头飞龙的鞍上。据说是要把他托付给在人界等待著的女性整合骑士。

一询问「是情敌吗？」，爱丽丝就稍微露出微笑来这么回答。她说：「我的情敌是你。」

────真是的。

听她这么说，可就没办法随便登出这个世界了。在桐人清醒的那个瞬间来临前，无论如何都要留在这个世界里。

诗乃再次把决心刻划在胸口，持续凝视著岩山。

黑线和平坦的顶端中心部接触，逐渐形成黏液质的水滩。

它有著宛如通往地狱的无底洞般浓厚、深沉的颜色。

线条最后被水滩吸进去，然后──

噗通。

表面扬起小小波纹，下一刻，一只右手无声地伸出。看见细长的五根手指头在空中蠢动，诗乃背后就闪过一道类似恶寒的战栗。

忍受著现在立刻把他烧尽的冲动，诗乃静候敌人完成实体化。

左手也接著右手之后流畅地出现，抓住了水滩的边缘。

发出潮湿水声的情况下，出现了男人的头部。

──意外的是，那是脸部没什么特征的虚拟角色。至少不是什么俊男的感觉。头上顶著紧贴著般的短金发，另外还有细细的鼻梁与单薄的嘴唇，虽然是白人族群的外表，但莫名给人平淡的印象。

这真的是那个原本操纵暗神贝库达这个超级帐号的人重新出现的姿态吗……当诗乃感到疑惑的时候──

上半身从水滩里爬出来的男人，那蓝色玻璃珠般的眼睛就到处乱动，接著捕捉到上空的诗乃。

诗乃瞬间觉得奇怪。

好像在哪里看过那双眼睛。宛如反射一切，然后又可以将一切吸收进去般，没有任何感情的眼睛。

看见诗乃的那双眼睛稍微瞪大。接著嘴唇露出有些扭曲的微笑。

不会错。我曾经看过。我知道这双眼睛……这副脸孔。而且还是最近才在某个地方──

诗乃茫然往下看的前方，水滩在男人一口气爬出来时发出「噗通」一声黏稠的声音。

外表看起来也有点奇怪。可能是至今为止的装备自动转移过来吧，身上完全看不到华丽的金属铠甲。在上下半身同样是深灰色的服装上套著皮革背心，脚上则穿了双军靴。看来简直就像现实世界里的士兵所穿的战斗服。武器则是左腰上的长剑与右腰上的十字弓。

即使男人完全脱离，黑水滩也没有消失。惊人的是那滩水竟然从地面剥离，像是生物般蠢动著。不对，实际上就是生物。剥离的部分细细地往外伸长，化成羽翼急速拍打翅膀。

那是和鸟与飞龙完全不同的奇怪模样。如脸盆般平坦的身体前部，黏著四颗圆滚滚的眼球。左右两边则是蝙蝠般的翅膀，然后后面还有一条宛若蛇一般的尾巴。

谜样的有翼生物，载著身穿战斗服的男人拍打翅膀离陆后，就上升到跟诗乃同样的高度。

生物就在距离诗乃正面三十公尺处的位置盘旋，而该生物背上的男人则再次露出浅笑。

不知道有什么打算，只见他把空著的双手往前伸出。认为他可能是要使用咒文还是某种手段的诗乃摆出戒备的姿势，但并不是这样。男人把双手弯成抓住诗乃脖子般的形状后，就做出勒紧的动作。

瞬间，诗乃终于想起来了。从她的嘴唇里发出沙哑的声音。

「…………Subtilizer…………」

不会错的。那个男人是在短短两周前举行的Gun Gale Online的PvP大赛，「第四届Bullet of Bullets」决赛里，从诗乃背后以裸绞干掉她的美国人玩家。

但是，为什么那个男人会在这里？

诗乃忘记架起弓箭，只是持续因为愕然而瞪大双眼。

＊＊＊

金字塔形的自走式人工母船O Turtle中央部，是被高强度钛合金制的坚固主轴所贯穿。

高达百公尺的圆筒状轴体最底部，存在著被复数防护墙保护的主机、压水式反应炉。其上方则是被占据的主控室以及第一STL室。

Underworld，甚至可以说是Alicization计划中枢的LightCube Cluster就摆设在更上方的位置。到此为止就是下轴的部分。

轴体在Cluster上方被水平延伸的耐压隔板阻隔开来。被称为上轴的隔板上侧，设置了巨大冷却设备、RATH工作人员前来避难的副控室，以及桐谷和人与结城明日奈使用中的第二STL室。

七月七日上午九点。一架人形机器人开始自行从设置在上轴船首侧的阶梯往下走。它是RATH开发出来的实验机「一卫门」。三名武装的自卫官像是守护著脚步蹒跚的它一样跟在后面。

同一时间，两名矮小的人类正以僵硬的动作，从设置在轴体船尾侧光纤导管内的梯子往下爬。

──没有密室恐惧症、惧高症与黑暗恐惧症真是太好了。

比嘉健虽然试著这么鼓励自己，但是也有种在这种极限的状况之下，有没有恐惧症根本无所谓的感觉。

因为在橘色的紧急照明灯照耀之下的导管，一直往正下方延伸了长达四十公尺。要是被汗濡湿的手一滑，或是发抖的脚没有踩稳的话，将会与遥远下方封闭导管的耐压隔板猛烈撞击，品尝到让人高兴不起来的感觉。

早知道是这样的话，就应该让柳井研究员先往下爬。这样至少可以不用一直在直向洞穴里看著正下方。

──说起来呢，明明表示要帮忙挡子弹，结果到了这里就说「你先请吧」，这到底是怎么回事。

比嘉以有些怨恨的思绪，往上瞄了一眼攀在数公尺上方梯子上的柳井。

但是看见他白皙的脸变得更苍白，以拚死的表情紧握著梯子的模样后也就没办法抱怨了。其实光是自愿参加这个危险任务就相当了不起，另外插在柳井先生皮带上的自动手枪也多少让人觉得胆子大了一些。

再次把视线往下移的同时，左耳的耳麦就传来冷静的声音：

「怎么样啊，比嘉。有没有问题？」

声音是来自从头上的舱口把头伸进导管里注视著两个人的神代博士。

比嘉以沙哑的声音对嘴角的麦克风呢喃：

「嗯……嗯嗯，还可以。应该再五分钟左右就可以下到耐压隔板的地方了。」

「了解。等你们那边准备好，就会对一卫门小组做出闯入的指示。比嘉你们要在敌人的注意力被一卫门吸引过去并且开始攻击时才能打开隔板喔。」

「了解。呜哇喔，开始有种『不可能的任务』的感觉了。」

「拜托把任务变可能吧。我有种Underworld内部状况的变化，也与桐人小弟的复活有很大关系的感觉……抱歉，柳井先生，那个孩子就拜托你了。」

听见神代博士后半段发言的对象‧柳井研究员以沙哑的声音回答了声「了解！」，比嘉就露出了苦笑。

──那个孩子吗？

比嘉摇了摇头，用曾几何时已不再流汗的手掌紧握住钢铁梯子。

一往正下方看去，发现不知不觉间隔板已经相当靠近了。

＊＊＊

克里达茫然望著从中国、韩国潜行过来的玩家在萤幕上形成巨大云朵蠢动的模样，这时突然响起的警报让他瞬间跳了起来。

「怎么了……！」

急忙环视操纵台周围，就注意到右侧副萤幕上有一颗红色警示灯正在闪烁。

「喔哇……耐压隔板的封锁被解除了！谁……谁去看一下通道！」

才刚叫完，高大的突击队员汉斯就抓起突击步枪，以脱兔般的动作跑了出去。

「喂，我才刚拿了一手好牌啊，可恶！」

抱怨了一声，把凑成同色的扑克牌丢到地上的大胡子布里克也从后面追了上去。

难道装备的火力占绝对劣势的RATH，竟然自暴自弃地发动了神风攻击？还是有什么计策……？

克里达也离开操纵台，往主控室的门靠去。现在电梯的电源已经关掉，真发生什么事情的话应该是从楼梯吧。汉斯与布里克似乎也做出这样的判断，所以可以听见用力踢著金属踏板的脚步声。

脚步声忽然中断，接著响起粗豪的吼叫。

「Woah！」

「Are you kidding？」

然后是步枪的连续射击声。

＊＊＊

比嘉已经感觉到透过光纤导管传来「喀哒哒哒哒」的自动步枪清脆射击声。

现在主轴的另一边，可怜的一卫门全身的肌肉筋膜与钛金属骨骼应该都被开了不少洞。但是，电池与控制系统都装设在背部，所以就算被击中也还能行动一阵子才对。

「可以了！打开耐压隔板的舱门！」

在耳麦响起神代博士声音的同时，比嘉就灌注全身的力道，旋转阻隔导管的耐压舱门上面的把手。油压阻尼器随著「噗咻」一声动了起来，举起厚重的金属盖。

隔板的后方，下轴侧的导管也在昏暗的橘色紧急照明灯照耀之下。在轴体另一侧的楼梯间所进行的战斗声，音量忽然大为增加。

比嘉吞了口口水，然后重新背好装有小型笔电的背包，钻过比导管还要窄的舱门。接著再次把脚放到梯子上，重新开始往下爬。

──这种时候，动作电影都会夸张地大叫吧。

「……GOGOGO！」

在嘴里这么呢喃，就从耳麦当中传来凛子疑惑的声音：

「咦，你说什么？」

「没……没有，没什么……距离导管的检修用电子连接器只剩十公尺……啊，看到了，就是那个！」

配置在导管壁上的数条粗大光纤线，直接被黑色面板箱所吞没。把笔电连接到里面的检修用电子连接器，理论上就可以直接操纵第二STL室的三号机与四号机，以及放置在距离遥远的六本木分部里头的五号机与六号机了。

──等著吧，桐谷小弟。现在就让你醒过来！

忘记了恐惧心，再次拚命持续从铁梯往下爬的比嘉，耳麦里再次传出声响。

「那我到副控室监控桐人小弟的摇光。比嘉，加油！」

被神代博士──过去称呼为凛子学姊的人，用简直像是回到学生时代般的方式鼓励，比嘉忍不住就抬头往上看。

但是进入视界的，却是以拚死的表情爬下铁梯的柳井。

感到无奈的比嘉只能把视线移回靠近的面板箱上。

＊＊＊

从留下激斗痕迹的岩山顶上出现的战斗服男，把视线往南方移去后，就用无机质的口气呢喃著：

「……爱丽丝逃走了吗？算了，马上就能追到……」

接著再次看著诗乃，脸上露出浅笑。

「……我和你确实是在Gun Gale Online的大赛里战斗过吧。名字应该是……『诗乃』吧？没想到会在这种地方遇见你。」

一边听著暗神贝库达，同时也是Subtilizer的这个男人发出某种不像人类的声音，诗乃一边拚命想压抑下双手的发抖。但是手指却变得僵硬，手掌渗出汗水，随便乱动的话好像连索鲁斯之弓都要掉到地上了。

搭乘在圆盘状有翼生物背上的Subtilizer，在依然挂著无温度笑容的情况下，以流畅的日文继续表示：

「这是怎么回事呢？我听说日本国内已经没有STL存在了……你是RATH的相关人员吗？还是说，你是连这种地方都要来的佣兵？」

诗乃好不容易动著干到极点的嘴唇，以沙哑的声音询问：

「Subtilizer……我才想问你为什么会在这里！」

「当然是因为，这是必然的结果啊。」

Subtilizer像是难以抑制高兴的心情般张开包裹在灰色战斗服下的双臂，接著继续说：

「这是命运。是灵魂的力量让我和你互相吸引。」

他的口气逐渐改变。连发出的声音温度都开始变低。

「没错……我想得到你。所以才会像这样相遇。这样应该可以了解许多事情了吧。像是介由STL，除了能从人工摇光之外，究竟能不能从现实世界的人类身上吸取灵魂……还有，你在GGO的大赛里无法让我品尝的灵魂，究竟会有多么甘甜。」

听见这异样的一段话，诗乃脑袋里瞬间就重新浮现眼前这名男人在第四届BoB的最后决胜负阶段发出的声音。

──Your soul will be so sweet.

──你的灵魂一定相当甜美吧。

诗乃的身体变得更冷。除了全身僵硬之外，甚至连呼吸都变得不规则。

「那么……过来这里吧，诗乃。把一切全交给我。」

Subtilizer的蓝色眼睛发出冰冷的光芒。

「滋」一声沉重的声音过后，世界整个歪斜了。

空气、声音甚至连光线都一边扭曲，一边被吸进Subtilizer眼里。

「这…………」

这是怎么回事？

甚至连这样的思考，都被强烈的磁力吸进去。

──不行。必须抵抗。我得要战斗。

在内心角落这么大叫的声音，不知道为什么却显得极为细微。

最后，诗乃包裹在蓝色铠甲底下的身体，就开始被Subtilizer张开的手臂吸引了过去。

失去力量的左手指尖，好不容易才维持挂在弓弦上的姿势，而诗乃则无声地在空中横移。

几秒钟后，在朦胧的意识当中，诗乃感觉自己的身体被名为Subtilizer的浓稠黑暗包裹住。

男人的左手绕过她的背后。右手指尖掠过脸颊，把盖住耳朵的头发拨开。

Subtilizer单薄的嘴唇靠近露出来的左耳，宛如冰冷黑水般的声音直接潜入脑袋里。

「诗乃。你曾经想过『Subtilizer』这个名字是什么意思吗？」

「…………？」

依然全身脱力的诗乃左右摇了摇头。

「很像从美国人会喜欢的『Satori』这个名字改过来的吧？但是呢，这是货真价实的英文。拼法是『Subtilizer』。意思是『研磨者』『磨薄之物』『选择者』……以及『偷盗者』。」

Subtilizer在诗乃眼前近处的双眼发出更强烈的光芒。

「我要把你偷走。我要偷走你的灵魂……」

＊＊＊

赵月生降落的地点是满是龟裂与青苔的石头上。

那不是天然石而是经过加工的物体。看来是在神殿般超大型建筑物的屋顶。四周围挤满先潜行到此的韩国人玩家，数量有数千……甚至超过一万人以上的规模。

由于没有选择虚拟角色的程序，所以细部和武器虽然有所不同，但所有人的装备都统一成暗红色。月生望了一阵子自己戴著同色护手的双手，然后才把视线移到前方。

虽然因为人墙而看不太清楚，但神殿前方的平地上，战斗现在似乎依然持续当中。但周围的韩国人之所以一动也不动，是因为大局早已底定了吧。似乎是日本人玩家的彩色集团，几乎把和月生他们同样是全红色的集团驱逐殆尽，部队虽然已经重整，但完全听不见感到痛快的声音。

果然有点不对劲。但是又无法立刻说出究竟是哪里奇怪。

至少不是潜行前所想像的那样，是某种新游戏的促销活动。全是泛红天空与黑色地面的练功区实在单调到了极点，潜行前完全没有显示注意事项也都是正规活动不可能出现的情形。

但就算这样，也无法完全相信推特的内容。说起来，进入封测伺服器内，在游戏里杀掉封测玩家究竟有什么意义？即使可以给对方一时的痛苦与屈辱，游戏开发也不可能因为这样而延迟或者是中止吧。

月生周围的韩国人也有将近半数露出狐疑的模样。「该怎么办才好？」「那些家伙真的是日本人吗？」开始可以听见一些这样的声音。

──但是，就在这个时候。

「同胞们！」

从右前方可以听见用韩文的呼唤。

虽然挺直背杆把视线移过去，还是被大量的玩家遮住而看不见发言者。但是人墙的上空，可以看见飘浮著「LEADER」这样的红色浮标。从那个方向再次传出同样的声音。

「非常感谢你们回应我的呼唤！很可惜的──原本在这个地方进行封测的玩家们，已经被日本人的入侵者，不对，应该说侵略者给杀了！但是那些家伙准备移动到其他测试地点去做同样的事情！」

下一刻──

月生感觉到数千人的集团产生了明确的怒气。

点起韩国人玩家怒火的，应该是侵略（침략）这个名词吧。不少玩家原本应该感觉到的犹豫与困惑迅速烟消云散，逐渐换成带著热气的敌意支配现场。

「……卑鄙的日本人（피겁한일본인）！」

某个人这么大叫，接著又有零碎的怒骂声。等声音止歇后，「LEADER」再次用响亮的声音发言：

「日本人骇入伺服器，随心所欲地制造出高性能的装备！而管理者权限被夺走的我们，只能为各位同胞准备预设的装备！但是你们的正义与爱国心，应该不输给任何剑与铠甲才对！」

随即有更大的叫声回应了这样的呼唤。

「……保护我们的国家（우리나라를지키라）！」

接著距离右侧相当遥远的地方也响起韩文之外的巨大怒骂声。

「干掉你们！」

虽然不了解意思，但月生也听得出那是中文。看来也有与韩国人差不多数量的中国人玩家聚集在这里。

在急遽升高的热气当中，月生的不对劲感依然没有消失。但同时也直觉没有任何人可以阻止现场的趋势了。

人墙后面，「领队」高举起戴著黑手套的右手。

「────Go！」

受到韩国人与中国人都能了解的命令，燃烧著熊熊怒火的红色军队，就像一只巨大的生物般带著剧烈震动开始行动了。

＊＊＊

「人……人界军！补给队！全速前进──！」

亚丝娜在挤满东西侧遗迹宫殿屋顶的红色大军有所动作之前，就挤出声音来这么大叫。

人界守备军的补给部队正布阵在遗迹参拜道路入口。而宫殿就往参拜道路的两侧延伸。也就是说，数万名敌军正挤在补给部队的正上方。

「舍弃物资，马车和术师现在立刻跑过来！」

虽然又做出这样的指示，但还是来不及了。新加入战局的，应该是中国与韩国的连线者们，已经跨越巨大神像的头部，往补给部队的正中央跳下来了。

亚丝娜咬紧牙关，高举起右手的细剑。

把想像力集中在剑尖，然后猛烈挥下。七彩极光一直线迸出，直接击中并排在参拜道路两侧的巨大神像。

虽然有快要把意识轰飞般的剧痛贯穿头部，但拚命集中想像力后，众石像就发出地鸣开始动了起来。它们张开四角形的嘴，挥舞著短手臂，开始攻击挤满宫殿屋顶的玩家们。

站在最前面的红色士兵急忙飞退，结果和后方挤过来的同伴撞在一起，像骨牌一样连锁跌倒。趁著这个空档，八台马车与两百人左右的修道士队、补给队开始移动。

亚丝娜能操纵神像的时间只有短短的三十秒左右，虽然因为再也无法忍受痛苦而跪到地上，但人界军的后方部队也总算脱离死地，成功退避到遗迹北侧广大的荒野上。五百人左右的卫士队与两千名日本人玩家往前进，摆出从两侧包围后方部队般的阵型来准备应战。

但这个地点没有什么太特殊的地形，面对数万名敌人只能被迫进行绝望的圆周防御。之所以能辛苦地击退数量远优于己方的美国人玩家，完全是因为利用遗迹宫殿的墙壁把前线限定在一处，然后组成深厚回复轮值的缘故。被四万将近五万名中国、韩国人玩家包围的话，前线崩坏只是时间上的问题。

「呜…………」

亚丝娜挤出残存的一点点力量站起身子，然后再次举起细剑。

──拜托，最后……让我制造能够守护大家的坚固墙壁。

她一边祈祷，一边试著集中想像力。

但是──

随即受到强烈电流贯穿全身般的冲击，亚丝娜再次倒到地面。把涌上喉头的液体吐出来，结果发现是少量的血。

「亚丝娜，别勉强自己！也给我们一些表现的机会！」

克莱因气势十足地叫著……

「没错，这里就交给我们吧。」

艾基尔也以浑厚的声音回应。

站在亚丝娜面前的两个人，摆出长刀与两手斧备战的下一刻──

从一时混乱中恢复过来的红色军队，这次真的开始从宫殿屋顶跳下来了。由于距离地面的高度有二十公尺，所以也有不少无法顺利著地而四肢负伤，更因此而无法动弹的人出现，但后续的士兵就以受伤者为肉垫，毫发无伤地降落到地面。

「돌격（突击）──────！」

「突────击────！」

亚丝娜虽然没有学过韩文与中文，但直觉告诉她两种怒吼都是「突击」的意思。

深红军队往左右两边延伸并挤压过来，而率先迎击他们的是克莱因与艾基尔。

「嘿呀啊啊啊啊啊啊啊！」

「喔……啦啊啊啊啊啊！」

随著足以让空气产生震动的吼叫，施放出长刀与斧头的广范围剑技。白色与蓝色的光线特效双重闪烁，多达几十名的敌兵随著鲜血飞上天空。

在他们的左右两侧，ALO的领主们以及他们的心腹，还有沉睡骑士的强者们也开始全力战斗。

宛如机关枪一般穿透全场的金属声。沉重响亮的单发爆炸声。长剑、斧头、长枪发出低吼，每当各种颜色的剑技炸裂，红色士兵们就不停地被砍倒在地。

遭到压缩的空气发出摩擦声，大军的突进一瞬间停下来。

但那只是──

空手想挡住溃堤浊流淹没自己般无谓的努力。

依然蹲在地面的亚丝娜，听见从席卷著悲鸣与怒吼的战场天空传来细微尖锐的哄笑声。

移动迷茫的双眼，就看到遗迹宫殿的屋顶上，黑色斗篷男像在跳舞一样扭动著身体。

＊＊＊

比嘉一边听著从主轴另一侧断断续续传来的枪声，一边以最快的速度走下梯子。

终于到达在橘色光线照耀下发出钝重光芒的面板箱前面，就用僵硬的指尖把盖子打开。

内部设置著挤满杂乱光纤线的配线盘，一看见的瞬间难免觉得有些脱力，但比嘉还是拨开这些线找到了检修用电子连接器。

终于要开始了。

用力吸了口气，让思考冷静下来后，就从背包里拿出连接线与笔电。接著把连接线的一端插进检修用电子连接器，另一端插进电脑里，再以祈祷般的心情起动操纵STL用程式。

全黑的视窗打开，左上方的浮标像要吊人胃口般开始闪烁。最后往右边移动，显示出目前的状态。

STL#3、eg…………OK。

STL#4、eg…………OK。

首先是邻接副控室的第二STL室的两台回传了正常的讯号。

接著也确定与经由卫星线路与O Turtle连线的六本木分部的五号机、六号机连上线。

「……好！」

比嘉低声呢喃著。这样子应该就能操纵桐谷和人与三名少女使用的四台STL了。

可惜的是从主控室只能拦截连接第二STL室以及卫星天线的线路，所以无法对第一STL室的两台出手。如果办得到的话，就可以把从一号机与二号机潜行的袭击者赶出Underworld了。

比嘉在这里止住汹涌的思绪，为了赶紧进行作业而把右手放在小小的键盘上。

──要上喽！

在他打起精神的同时，头上就传来尖锐的叫声。

「…………不……不要动！」

那是柳井的声音。在这种状况下，忽然说这是什么蠢话啊。

焦躁地抬起头来的比嘉，看见的是在短短三公尺前方发出蓝黑色光芒的自动手枪枪口。枪口后方，小小双眼布满血丝的柳井再次叫道：

「把手从笔电上移开！不移开的话，我就要开枪了！」

「…………啥？」

茫然自失的时间不到半秒钟。

比嘉瞬时了解状况，开始推测起他为什么这么做。

────就是这家伙！

这个男人，柳井就是把Alicization计划的情报外流给美国人的间谍。

但很可惜的是，没办法想出对策。从他干渴到极点的嘴里，发出完全没有意义的问题。

「……柳井先生。为什么？」

苍白的额头满是斗大汗水的技术人员，嘴唇稍微痉挛了一会儿后，才挤出纤细的声音：

「话……话先说在前面。可别把我当成什么背叛者喔。」

──什么叫当成，你分明就是啊！

就像听见比嘉内心的狂吼一样，柳井又继续说了下去。

「我只是贯彻自己的初衷而已。老大的遗志就由我来继承……我就是为此才潜入RATH的。」

「老……老大的遗志？你指的是谁啊……」

茫然这么问完，柳井就用左手扫开垂在额头的头发，一边露出带著些许疯狂的笑容一边回答：

「是你也很熟的人……就是须乡先生。」

「什…………」

──什么────！

受到比看见手枪时更强烈的冲击，比嘉瞪大了双眼。

须乡伸之。与比嘉、神代凛子，以及那个茅场晶彦同一时期一起在东都工业大学的重村研究室里就读的男人。持续对于身为特异天才的茅场表现出露骨对抗心，但是终究没能超越对方，不知道是不是这个缘故，竟然做出利用数百名SAO玩家来做违法人体实验的犯罪行为。

他的阴谋在桐谷和人的活跃下被公诸于世，而遭到逮捕的须乡对于一审有罪的判决提出上诉，目前还在东京高等法院打官司当中。

「……那个人还没死吧。」

忍不住这么呢喃，柳井就发出「嘻嘻」的尖锐笑声。

「也跟死差不多了。最少也要被关十年吧，这对研究者来说就跟死没两样。我也差点就被抓了，是把罪全都推给另一个员工，才好不容易逃过法网。」

「那么你也……和须乡的人体实验有关……？」

「什么有关而已，实际上记录数据的就是我啊。像虚拟触手之类的呢……还真是有趣的研究……」

──菊冈二佐为什么会没有检查出这个罪犯的身份呢！

比嘉随著急促的鼻息这么想著，但立刻又觉得也不能怪他而叹了口气。

伪装企业RATH设立的意图，就是在几乎由美国执牛耳的防卫技术基盘上，开出一条纯国产的新路线。也就是会给既存的财阀型制造商与国防军事公司的权益带来威胁的存在。

因此，要寻找技术方面的工作人员可以说相当辛苦。几乎没有来自知名企业的应征者，也难怪他们会非常欢迎曾经在RCT这种大公司的潜行技术研部门工作的柳井来此工作了。

比嘉视线的前方，柳井似乎暂时沉迷于过去的回忆当中，但立刻就又重新举好手枪。握柄旁的安全装置也确实已经解除。菊冈连技术方面的人员都施行过射击训练的周全准备，这时候却造成反效果。

幸好柳井似乎还有尚未吐完的牢骚，所以用尖锐的声音继续著对话。

「……嗯，老大的人生已经到了终幕，但那个人接上的线却还有效。这样的话，我不加以善加利用，就浪费了那个人的苦心了。」

「你说接上的线……指的是哪里？」

比嘉反射性这么问道，柳井稍微露出犹豫的表情，但最后还是咧嘴笑著回答：

「美国国家安全局。」

「你……你说什么！」

比嘉虽然露出惊讶的模样，但内心却想著果然如此。

美国国家安全局在日本进行窃听与讯号拦截等活动已经是公然的秘密，所以他们不可能对日本领先的完全潜行技术没有兴趣。从原本是须乡部下的柳井这里获得Alicization情报的NSA，甚至租借了海军的潜水艇前来夺取「A.L.I.C.E.」。

柳井以丝毫不感到愧疚的模样继续炫耀著：

「……下面的那群美国人顺利回收爱丽丝的话，对方也保证给我庞大的奖金以及在那边的职位。这正是须乡先生所作的美国淘金梦啊。」

──不过之后世界就会因为美军应该会配备的超高性能无人兵器而感到战栗了。

比嘉拚命压抑下想这么反驳的冲动。现在必须尽量延长对话，抓住仅存的一点机会才行。

──凛子小姐，拜托一定要注意到啊！

强烈这么冀求之际，左手差点就要放到笔电上，结果比嘉急忙又把手拉了回来。

「不……不要动！」

下一刻，柳井立刻用变调的声音叫唤著，然后把枪口对准导管的壁面扣下扳机。黄色亮光一闪，膨胀的空气让两耳产生刺痛的麻痹感。

导管的金属壁上弹出火花──

剧烈的冲击击打了比嘉的右肩。

「咦！」

柳井发出惊讶的声音。

＊＊＊

诗乃茫然眺望著近在眼前的两颗蓝色眼睛当中，宛如黑洞般旋转的漆黑漩涡。

那与黎明时作的梦十分类似。

必须做些什么才行。应该做了些什么才对，但那是在作梦其实什么都没做。只是一直重复著幻影的轮回。

冷冰冰的手指抚摸过她的脖子。内心产生强烈的厌恶感与恐惧，但是连这些情感都立刻被从意识当中吸出，换置成灰色的空虚。

──不行。

这已经不是在虚拟空间里发生的非现实事故了。

这样的认识，像红色警戒灯一样在头脑角落闪烁著。虽然想把意识集中在上面，但黏稠的黑色液体不知不觉间已经连腰部附近都吞没了。自己已经无处可逃。甚至没有办法抵抗。

男人的脸孔更加靠近。单薄的嘴唇噘起，嘶一声吸进空气。感情、思考，甚至连灵魂都随著空气一起被吸出去。

──住手。

──别把它们偷走。

连这样的恳求都立刻被夺走，剩下来的就只有迟钝的麻痹感。

「住……手…………」

男人的嘴唇靠近诗乃如此呢喃著的嘴唇。

啪叽！

这样的冲击，突然间用力拍打诗乃的意识。

瞪大的双眼，捕捉到从自己上衣领口飞散的银色火花。

──好烫！

类似电击的灼热感，一瞬间超越了男人的吸引力。诗乃将稍微恢复的思考像子弹的雷管一样炸裂，然后挤出全身的力量从男人的怀抱当中脱身而出。

她发挥索鲁斯的飞行能力，与对方拉开相当遥远的距离。

「…………呜……」

诗乃一边剧烈喘气，一边用右手从上衣内侧拉出持续爆出火花的某样东西。

那是吊在纤细炼子上的泛白金属板。直径一‧五公分左右的圆盘，边缘开了个洞并且穿过炼子。

「为……什么……这个会……」

──在这里。

诗乃感到惊愕并发出沙哑的声音。

这是现实世界的朝田诗乃一直挂在脖子上的项炼。它并不是什么高价的物品。炼子是不锈钢制，金属则是一般镀了银的铝。

但是，这对诗乃来说是相当有意义的物品。

去年年末时诗乃被卷进「死枪事件」里。

身为犯人集团其中一人的同班男生，以装了猛毒Suylcholine的高压注射器袭击诗乃时，赶过来的桐谷和人──桐人为了保护诗乃而左胸被注射了药物。

之所以能防止剧毒侵入身体，靠的是他忘记从胸口撕下来的心电图用电极。

诗乃在事件之后发现它掉落在房间的地板上，就把胶带从电极上剥除，再把银色的金属元件加工成坠饰。总是挂著这条自制项炼这件事情她一直都瞒著桐人和亚丝娜，在RATH的六本木分部也是直接穿著衣服潜行，所以叫作平井的工作人员根本没有看见这条项炼的机会。

所以不可能发生这条项炼在Underworld里被实体化这种事情才对。

──但是……

桐人在Dicey Café里这么说过。他说STL制造出来的虚拟世界，不单纯只是多边形的物体。

他表示──那是由记忆与想像力所创造出来的另一个现实。

所以这条项炼，是诗乃自身的想像力让它出现的。

诗乃轻轻用银色坠饰碰了一下嘴唇，然后把它放回衣服底下。

接著把完全恢复过来的意识，移向在远处空中盘旋的黑色有翼生物。

生物背上，Subtilizer正默默地望著自己的右手。诗乃看见些许白烟从他的指尖冒出。

可能是感觉到视线了吧，抬起脸来的Subtilizer嘴角，稍微浮现出感到不愉快的感情。诗乃确实看著男人的脸，然后开口说道：

「你不是神也不是恶魔。只不过是人类。」

Subtilizer确实具有压倒性的力量。他应该是用具有惊人强度的想像力来干涉诗乃的精神……也就是摇光。

──但是，想像力和集中力的话，自己也不会输给他。

因为那对狙击手来说是最重要的力量。

诗乃用双手握住索鲁斯帐号的GM装备「歼灭光线」后，就凝眼瞪著它看。

闪耀白色光芒的长弓中央部位，开始变化成带著蓝光的黑色。

随著变色范围扩大，光滑弯曲的弓开始变成完全的直线。闪烁蓝黑色光芒的长形筒状物是钢铁的枪身。枪口、握柄、枪托依序出现，最后巨大的瞄准器像涌出来般实体化。

这时在诗乃手中的已经不是流丽的长弓。

而是粗犷、狰狞又无比美丽的50口径反器材步枪──「Ultima Ratio HecateⅡ」。

拉起独一无二搭档的退弹杆发出尖锐的声音后，诗乃就咧嘴笑了起来。

Subtilizer的鼻梁出现浅浅的皱纹，嘴唇带著愤怒而扭曲起来。

＊＊＊

能称为交战的情况，只持续了短短的七分钟。

之后的状况是先经过三分钟的防御战，再来就转变成单方面的杀戮。

「死守下来……！无论如何都要保护Underworld的人们……！」

亚丝娜无视脑袋深处持续著的疼痛，一边在最前线挥动细剑一边放声大叫。

但是已经听不见整齐且令人放心的回答了。

周围转移过来后身穿各种颜色装备的日本人玩家，一个一个被穿戴血一般红色铠甲的邻国人包围，然后用剑与枪乱刺一通。怒吼、悲鸣以及临死前的叫声不停响起。

和这比起来，美国人的重枪突击还算是有办法能够应对。

新出现的大军，不知道是从两个国家潜行至此的缘故，还是因为燃烧著异常炽烈的怒火，让他们不顾一切只以歼灭为目标。以复数人抓住目标的脚后将其拉倒，然后扑上去夺走对方的自由。以这种战斗方式的话，战术终究是无法克服庞大的数量差距。

眼看著两千人围成圆形的防御阵形遭到侵蚀并逐渐变薄。

亚丝娜拚命用细剑斩杀永无止尽般挤过来的士兵，一边贯穿敌人的身体，一边在内心呢喃著从昨夜潜行到Underworld以来首次的绝望发言。

谁来救救我们啊。

＊＊＊

在绝望的战况当中，持续有著较活跃表现的部队之一，是由在ALfheim Online里担任风精灵族领主的女性玩家──朔夜所率领的绿剑士队。

风精灵族原本就擅长活用机动力的高速联手攻击。这种为了对抗把重点放在重装玩家发动突进攻击上的火精灵族而锻炼出的战法，在这样的混战当中也发挥了一定程度的机能。轻装的剑士们藉由令人眼花撩乱的动作互相掩护，让敌人无法特定目标，总算能够防止被一个一个拉倒。

「──好，由我们来打开突破口！龙胆队、铃兰队，把战线推向右边！」

自身也一边在前线朝四面八方舞动细长长刀的朔夜这么大叫。

和应该在右翼方向战斗中的火精灵队会合，利用他们的突进力一口气突破敌阵。让支援部队再次逃进遗迹的参拜道路，把战线限定在狭窄的入口处的话，说不定就能像美国人时那样，解决这数量庞大的敌人了。

「要上了！准备『同时剑技』！倒数，5、4、3……」

当朔夜指示到这里的时候──

从负责的战场左侧传来清晰明瞭的悲痛声音。

「──大家不要放弃，尽量争取一些时间！」

朔夜瞬时停止呼吸，将视线往左方移去。

装备以黄色为基调的日本人部队已经快要崩坏，似乎立刻就要被红色巨浪给吞没。在最前方则可以看见装备在双手上的金属爪被按住，整个人被拖倒到地上的娇小身影。

「亚丽莎！」

朔夜大叫著。瞬间，她就从冷静沉著的指挥官，恢复成一名普通的女大学生。

「快住手──────！」

叫完后便单独往左跑去。砍飞左右两边挡住去路的敌人，专心一志地往好友身边突进。

猫妖族领主亚丽莎‧露即使被长剑贯穿胸部与腹部，在注意到接近的朔夜后立刻发出急迫的声音：

「不行，小朔快回去！回去指挥部队！」

留下这最后一句话，从黄色头发伸出来的三角耳朵就从朔夜的视界里消失了。

「亚丽莎────！」

朔夜一边迸发出近似悲鸣的声音，一边只身闯入快要把猫妖队击溃的敌人庞大集团里。她不断使出剑技，在造成鲜血与肉片像雨水般飞溅的情况下不停前进。还差一点就要到好友刚才倒下的地方了……

咚喀。

随著这样的冲击把视线往下移，就看到从背后贯穿右腹部后往前延伸的枪尖。

在虚拟世界首次尝到的剧痛闪过神经，把全身的力量夺走。

即使如此她还是往前走了四步，但这时候虚拟角色却脱离意识的控制，直接往前倒下。

下一刻，憎恨的风暴就吞没了朔夜。爱刀被从右手夺走，左臂被从一半的地方砍飞，身体也不断被锐利的金属贯穿。

＊＊＊

潜行到现场的两千名──虽然急遽减少中──日本人玩家当中，最能正确掌握目前状况的是公会「沉睡骑士」的第三代会长安施恩/朱涅。

父亲是在日韩国人，母亲是日本人的朱涅能够说两国的语言。因此断断续续地听见从红色士兵口中丢出来的愤怒发言，让她推测出他们是受到什么样的情报所煽动。

日本与韩国的网路使用者之间出现断绝与冲突的情形，似乎是从朱涅出生之前的二〇〇〇年代初头开始。这其中当然有许多原因，但网路的发达或许是加速断绝的要因。

而这样的发展，也不分青红皂白地侵蚀了朱涅和伙伴们喜爱的线上游戏世界。即使在二〇二六年的现在，主流VRMMO的国际伺服器里，日本人和韩国人或者中国人玩家互相争夺练功场而造成严重冲突已经不是什么稀奇的事。最近的游戏几乎都像ALO那样挡掉来自海外的连线，甚至让人感觉与邻国之间的隔绝逐渐加深了。

在同时接触韩国与日本双方文化之下成长的朱涅，长期以来都对于这种状况感到相当痛心。在VR安宁病房里邀请朱涅到新世界的沉睡骑士众伙伴，知道朱涅的身世之后也还是跟以前一样亲切地对待她，所以她内心便想著……为了大家，总有一天要亲手连接起虚拟世界里断绝的桥梁。

但是现在却……

目前依然从遗迹宫殿屋顶眺望著战局的某个人，以花言巧语煽动韩国与中国的VRMMO玩家，点燃他们的敌忾心，想要造成VRMMO的历史上最大的憎恶与悲剧。

──我……我必须得想办法才行。日本人玩家当中，大概就只有我会说韩文了。

──不勇往直前，就没办法传达给对方知道。是这样吧，有纪。

在心中呼唤三个月前死别的前任公会会长后，朱涅大声对站在周围的四名伙伴做出指示：

「各位，拜托了，只要一次就可以了，帮忙制造一个突破点吧！」

在前头如战神般持续奋战著的双手剑士阿淳立刻大叫：

「知道了！提奇、达尔肯、小纪，同时施放大技吧！倒数，2、1！」

完美地在同一时间使出的单发高威力剑技，引起足以晃动大地般的爆炸，把数十名敌人轰得往后退。

在一瞬间的寂静与停滞当中，朱涅跑向现场看起来像是领队的高大韩国人玩家，然后以左手接下挥落的长剑。

手掌立刻裂开，鲜血从上头溢出。

但是虚拟的疼痛和朱涅过去接受白血病的骨髓移殖与鸡尾酒疗法时的痛苦相比根本不算什么。朱涅只是稍微绷起脸，接著便一直凝视著对方的眼睛，以韩文大叫：

「──听我说，你们都被骗了！这个伺服器是属于日本企业，而且我们不是骇客而是正规的连线者！」

她的声音在广大范围内回响，让沉默稍微变得长了一些。

被朱涅空手握住长剑的韩国人，虽然气势有点被盖过去而往后仰，但马上就又用尖锐的声音反驳：

「──少骗人了！我看见了，你们刚才把和我们同样颜色的玩家都杀光了！」

「那是和你们一样因为假情报而潜行到这里的美国人玩家！你们才是妨碍日本企业开发工作的人！请重新仔细地想一想……这些愤怒、憎恨，真的是发自你们的内心吗！」

韩国人似乎因为朱涅的发言而感到困惑，也因此安静了下来。

从人墙后方传来一道尖锐──但是带著疑惑的提问再次打破了寂静。

「你说的话是真的吗？」

边以韩文这么大叫边跑出来的，是外表和其他士兵看起来完全没有两样的一名玩家。来到反射性摆出戒备姿势的朱涅身边之后，像要表示自己没有敌意一样垂下右手的剑，并且把头盔的面甲往上抬。

「我是『Moon Phase』，你的名字是？」

忽然就被询问名字的朱涅虽然感到惊讶，但自称Moon Phase的男人，双眼当中带著相当认真的光芒。

朱涅将左手离开挡下来的剑尖，把滴著虚拟鲜血的手掌在胸前握紧，然后开口表示：

「……我叫朱涅。」

「这样啊，朱涅小姐，我本来就觉得这件事有点奇怪。」

Moon Phase一迅速地这么说，周围的韩国人玩家就发出愤怒的声音。但是Moon Phase藉由用力将右手的剑收回剑鞘里来封阻这些声音，接著往前走出一步。

「──有办法证明你所说的话吗？」

「…………呜……」

朱涅不由得屏住呼吸。

这个「Underworld」是受到政府支援的日本企业作为研究开发用的VR世界，袭击者是想夺走新世代AI这种研究成果的美国人──朱涅原本就不怀疑朋友莉兹贝特在ALO的世界树巨蛋里含泪诉说的这些话。但被要求证明之后就顿时说不出话来。

虚拟世界里不可能有什么物证。真要说的话，大概就只有某个人的证词，但日本人这边无论说什么都没有用吧。朱涅在说不出话来的这段期间里，也能感受到周围韩国人的敌意已经再次燃烧起来。该怎么办……哪里才有…………

「──朱涅，Underworld人啊！」

突然，左后方的小纪这么大叫。

「让他和这个世界的居民Underworld人见面，让他看见居民说的是日文，应该就能理解这里是日本的伺服器了！」

「啊…………！」

这样的话的确有可能。朱涅他们本身也只和待在圆阵中央的Underworld人士兵们说过一两句话而已，但灵魂还是因为他们明显不是现实世界人也不是NPC的感觉而受到强烈冲击。即使语言不通──说不定正因为不通，韩国人们也能够有同样的感受。只要能敞开心胸，和他们见面并且交谈的话，应该就没问题。

朱涅准备把小纪用日文说的话翻译成韩文传达给Moon Phase等人。

但就在那之前，他的后方就闪起一道狠毒的红色光芒。

「啊……危………」

朱涅虽然拚命想警告对方，但还是来不及了。虽然短但是相当厚的刀刃深深刺进Moon Phase背后，直接把他轰飞到十公尺之外。

「咕啊…………」

取代痛苦地扭曲身躯的Moon Phase站在朱涅面前的，是原本应该在宫殿屋顶的黑斗篷男。

他以握在右手上那把宛如中式菜刀般的刀具指著Moon Phase，然后用韩文大叫：

「这座战场不需要背叛者！」

随即直接用菜刀依序指著周围的韩国人说：

「你们别被骯脏的日本人骗了！」

从他的声音里，可以感觉到沉重、强烈、冰冷，但是又带著某种嘲讽的感情。

菜刀最后指的是愕然呆立在现场的朱涅。

「如果这里是日本的伺服器，而你们又是正规的连线者，那为什么只有你们拥有那么高级的装备？根本发出跟GM装备差不多的光芒嘛！一定是用作弊的手法擅自创造出来的啦！」

随著他的发言，周围传出了「没错、没错！」的叫声。

朱涅拚命地否定男人说的话。

「……不是的！装备之所以不同，是因为我们把自己的主要角色转移到这个世界来了！」

一听她这么说，黑雨衣男就发出尖锐的嘲笑声。

「哈，怎么可能会有把主要角色转移到封测伺服器里的笨蛋！骗人，全都是谎言！」

「是真的，相信我！我们是带著失去主要角色的觉悟来到这里……」

「咻」一声撕裂空气的声音响起。

当飞过来的匕首深深刺进自己右肩时，朱涅感受到的绝望完全盖过了疼痛感。朱涅无法理解投掷武器的男人凶狠叫唤出的言语。

看见中国人玩家组成的小集团，打破暂时停战的状态从右侧展开突击，待在附近的韩国人领队也随著叫骂声把朱涅踢飞。

倒到地面的朱涅虽然听见伙伴们从背后赶过来的脚步声，但是却再也站不起来了。

＊＊＊

──为什么？

整合骑士连利‧辛赛西斯‧推尼赛门切身感觉到覆盖战场的深沉憎恨，然后只在内心重复著一句话。

──为什么他们明明同样是现实世界人，却必须如此憎恨对方，并且互相残杀呢？

不对，或许连利也没有资格说这种话。因为住在地底世界的人，自己也分成人界人与暗黑界人，几百年来都持续著鲜血淋漓的战斗。短短几天前，在东大门所流的鲜血量，应该足以匹敌渐渐濡湿这座战场土壤的血液吧。连利自己也用挂在两边腰间的神器「双翼刃」夺走无数哥布林族的性命。

但是，正因为如此。

他才很想相信，据说是在地底世界外面的那片现实世界，是没有任何的争执与憎恨，绝对不会发生战争这种事情。

但是，很明显这只是自己的幻想。现实世界人亚丝娜和她的同伴明明和地底世界人说著相同的语言，但是再次袭击过来数万名军队，口中大喊著的却是连利无法理解的叫声。如果连语言都有如此大的差异，根本不可能进行休战或者和解的交涉了吧。

也就是说，只有战争才是人类的本质吗？

不论是这个世界，还是外面的现实世界，甚至是如果存在的更外侧的世界，人类都一直持续著永无止尽的互相残杀吗？

──怎么可以允许这种事情发生！

连利用力握紧双手，忍住快要渗出的泪水。

整合骑士谢达为了守护原本是敌人的暗黑界拳斗士团而独自留在死地。那个人一定透过剑与拳头与暗黑界人互相理解了。在满是鲜血的道路另一端，一定还存在希望。

这样的话，现在就必须战斗下去。不是只呆呆站著被人保护的时候。

当连利为了救援死命持续著防御战的现实世界人部队而准备往前线走去时──

忽然有一道细微的声音从背后响起。

「骑士大人，我也一起去。」

转过头就看到，站在那里的是隶属于补给部队的红发少女练士缇洁。她紧握著一口小巧的剑，以悲壮的表情紧闭著嘴角。

「……不行，你必须保护那个人……」

「这个任务让给罗妮耶……我最喜欢的尤吉欧学长他……」

缇洁枫叶色的眼睛渗出光亮液体，接著又继续说：

「那个人为了保护重要的事物而丧命。我也想继承他的遗志。」

「…………这样啊。」

连利用力咬紧嘴唇。

就连身为整合骑士的自己，都不确定能在那个惨烈的战场上存活下来。实在不认为甚至连正式卫士都不是的缇洁能平安无事。

但是这个时候又有新的声音响起。

「骑士大人，我也一起去吧。」

从缇洁旁边走出来的，是把茶色头发绑在后面的高挑女性卫士长。应该是一路奋战过来的缘故吧，她的衣服骯脏，铠甲也全是伤痕，但是英挺脸庞上的斗志依然没有消失。

「……我也还没履行和桐人之间的约定。不能在这里放弃那个孩子变成这样也要守护的人们……还有世界。」

「索尔缇莉娜学姊……」

缇洁以发抖的声音叫著这个名字，卫士长也带著些许微笑对她点点头。

不是为了尊严或者名誉，而是为了应该守护的事物而战。

连利感觉到两人这样的决心也渗进自己心中，让自己产生了共鸣。

他用右手轻轻碰著神器，然后深深点了点头。

「……我知道了。这样的话，我会保护你们……绝对不要离开我身边。」

「好的！」

「拜托你了，骑士大人！」

缇洁和索尔缇莉娜坚定地回应，并从左腰拔出剑来。

同样用双手握著一对神器的连利，这时在心底深处呢喃著。

──艾尔多利耶先生、谢达小姐，以及贝尔库利骑士长。

──像你们一样，我似乎也终于找到用掉这条生命的场所了。

接著整合骑士连利，就和两名女性剑士一起跑向满是悲鸣与绝望的战场。

4

神代凛子一跑回副控室，就坐到比嘉健刚才坐著的那张网状椅上。

从显示在正面大萤幕上的几个视窗当中，注视著下方的小窗。表示在上面的是显示桐谷和人摇光状态的立体图表。

呈现七彩渐层的放射光中央，表示「主体缺损」的一片黑暗渗了出来。

现在比嘉健正操纵四台STL，准备利用三名与和人有深厚关系的少女脑袋里的记忆来修复造成问题的缺损。为了完成这个任务，他独自──不对，是仅仅只有两个人便潜入被敌人占据的下轴。

目前袭击者们依然专心迎击作为诱饵从楼梯闯入的「一卫门」。但是被步枪疯狂射击之后，就算是钢铁制的机器人也没办法撑太久。一卫门遭到破坏的话，敌人也会开始思考这些日本人到底想做什么吧。

──比嘉，快一点啊！

在心里这么祈求的时候，房门「咻」一声横移，穿著夏威夷衫的男性「喀哒喀哒」踩著木屐跑了进来。

「桐……桐人他怎么样？」

「现在比嘉刚开始操作。诱饵作战还顺利吗？」

一如此反问，菊冈诚二郎就上下震动肩膀喘著气，然后把滑落的眼镜推上来。

「从一卫门后面把所有的烟雾弹都丢进去了。应该还要一点时间烟雾才能从通道里排出去吧，之后不再次封锁隔板就有危险了。没什么时间了。」

「比嘉他说再久也是五分钟就能有结果了……」

凛子闭起嘴巴，再次把视线移回萤幕上。

桐谷和人的摇光依然没有变化。她握紧双手，以相信美国主妇所说的谚语「心急水不沸（a watched pot never boils）」的心态，把视线移向大萤幕中央。

结果上面依然打开著宛如虚构的奇幻世界地图般──不对，某种意义上来说确实是奇幻世界的Underworld地形图。

几天前刚来到O Turtle时就立刻给自己看过人界全体图，现在显示的是更加外侧的部分。从包围人界的山脉一直南下之后，可以看到把两个四角形并排起来的遗迹般人工地形。上面有显示结城明日奈现在位置的明亮光点、表示人界军队的蓝色小点聚合体，而以白色小点聚合体表示的，日本连线中的援军玩家，这三者正紧密地靠在一起。

而包围他们的庞大红色聚合体，应该是被袭击者们煽动而潜行至此的美国人玩家──但规模实在有点太大了。几乎有日本人的二十，不对，是三十倍吧。

这样真的没问题吗，除了明日奈之外的两个人究竟到哪去了？心里这么想而环视画面，就在距离遗迹相当远的南端发现一个淡蓝色光点。这应该是朝田诗乃吧。

这样的话，桐谷直叶人在哪里？更仔细地眺望地图后，终于找出来的黄绿色小点是在距离主战场相当遥远的北方发出亮光。亮点附近确实也有红色敌方集团，但比嘉确实说过要让两个人潜行到明日奈的座标处。那为什么会……想到此便皱起眉头的凛子──

忽然注意到像是被直叶光点强烈的光芒遮住一样，还有另一个白色小点也在闪烁著。

「…………？」

应该已经没有从RATH这里以STL潜行的人类了。这样的话，这个小点是什么呢？

反射性移动滑鼠，慎重地把浮标对准小点并且点击了一下，就打开了新视窗。凛子凝眼看著细微的英文符号。

「嗯……限制、对抗指数……检测界限值……报告？这是什么……」

正当她准备继续说「看不懂是什么意思」时──

「什……什么──！」

到刚才都在注意桐谷和人图表的菊冈忽然大声叫唤，让凛子差点从椅子上跳起来。

「怎……怎么了？」

但是菊冈什么都没说，一把滑鼠抢过去就扩大凛子刚打开的视窗。然后探出身子，像沉吟般快速呢喃著：

「呜……不会错了，是新出现的突破界限的摇光……！但为什么会在这个时间点……！」

凛子瞪大眼睛往上看著正在用力搔头的菊冈脸庞。

「咦……这就表示，是第二个『A.L.I.C.E.』？」

「没错，正是如此……啊啊，不对，等一下……这是……」

菊冈高速卷动显示详细记录的视窗，然后再次发出沉吟声：

「……严密来说，它和『爱丽丝』的等级不同。似乎不是经由理论回路而是藉著情绪回路来突破人工摇光的限制……但依然是相当贵重的样本。如果可以这样乖乖待著就好了……啊啊，不行，往南边的美国人集团跑过去了！」

把滑鼠从用双手抱住头部的菊冈那里抢回来，凛子也注视著成为焦点的人工摇光突破界限时的详细记录。

「原来如此……感情区域里有新的节点发生了连锁反应……嗯──？欸，菊冈先生？」

「什……什么事？」

发出懊恼声音扭动著身体的菊冈，只把脖子转向萤幕。

「这个插入此处的外部命令是什么？给人特别不对劲的感觉……总之就是很刻意……简直就像要妨碍回路的新生一样……」

凛子眯起眼睛，用眼睛追著以细小符号表示的程式。

「在右视觉皮层……注入拟似痛觉？这样即使人工摇光快要突破界限，整个过程也会因为疼痛而取消吧。你们甚至给Underworld人设下这种限制吗？」

「没……没有，我们没做这种事。怎么可能这么做呢，这是和目的完全相反的行为……应该说，很明显妨碍了我们的目的。」

「说的也是……而且这个程式的写法和比嘉的习惯不同……啊，一开始的地方有注释……『Code871』？871是什么？」

「871？我没听过这个编号……不对，等等……等一下喔，好像最近才在……哪个地方……」

菊冈突然踩著木屐跑了起来，然后一把抓起挂在稍远处椅背上的一件微脏白袍。啪一声把它摊开，然后凝视著衣领内侧。

「喂，怎么了，你在做什么？」

凛子一这么问，在黑框眼镜底下瞪大双眼的菊冈就把白袍的衣领递出来给她看。

上面用黑色油性签字笔清楚地写了「871」三个数字。

「这件白袍是……刚才和比嘉一起到下面去的工作人员柳井先生的……」

这么呢喃的凛子，听见自己发出的声音逐渐变小。

柳井。Yanai。

「…………871？（注：柳井的日文发音与871相近）」

凛子和菊冈同时站起来大叫。

＊＊＊

拳斗士族长伊斯卡恩用朦胧的左眼捕捉到逼近的红色军队。

说著奇妙语言的士兵们，把包围网缩小到仅剩下二十梅尔时，可能是确认拳斗士们已经没有斗志了吧，只见他们互相点了点头。

下一刻，他们便发出听不懂意思的威猛叫声，然后一起往地面踢去。

伊斯卡恩用骨头碎裂的左手，用力握住坐在旁边的女骑士的右手。立刻就有回握的感觉，麻痹的手一瞬间感觉到令人愉快的痛楚。

为了迎接最后一刻，在他准备低下头来闭上眼睛的瞬间──

「…………那是……？」

谢达的声音让他再次抬起头来。

连绵于战场北方的峡谷后面，可以看见一大群扬起土尘往这里杀到的军队。

他们有著高大圆润的身体、扁平突出的鼻子以及下垂的耳朵。

那是半兽人。

「……为什么。」

伊斯卡恩茫然如此呢喃。半兽人军受到皇帝贝库达的命令，应该一直在北方遥远处的「东大门」待机才对。既然皇帝已经消失，那道命令就不可能被解除。事实上，残存的暗黑骑士们就鲁直地持续停留在峡谷的另一侧待机。

不知道究竟是怎么回事，只能凝眼看著半兽人大军的伊斯卡恩，这时注意到笔直跑在最前面的娇小人影。

那不是半兽人。来者拖著黄中带绿的头发，而且由嫩草色服装伸出的手脚雪白到令人觉得刺眼。那绝对是人族，而且是人界人的年轻女性。

但那样看起来，简直就像娇小的女剑士独自率领著半兽人全军一样啊。

可能是注意到朝这边杀到的大军了吧，包围拳斗士团的红色士兵们也停下动作。

下一刻，跑在半兽人军前头的女孩冲进架在峡谷上的石桥。

一道炫目的光芒出现。女孩从背上拔出银色的长剑。

一瞬间可能感觉到什么了吧，谢达被伊斯卡恩左手握住的右手震动了一下。

人族的女孩来到桥中央附近，就高高地举起长剑。这时她距离红色士兵们还有两百梅尔以上的距离。

但是──

女孩的剑与双臂就像烟雾一样消散。即使以伊斯卡恩的眼力，都无法看见她的斩击。银色亮光闪烁，下一刻就出现让人惊恐的现象。

一条炫目的光线在漆黑的地面上奔跑──才刚看见这一幕，站在延长线上的红色士兵就有十几个人的身体无声被砍断，甚至连悲鸣都发不出来就倒下去了。

往下挥落的长刀在女孩手中反转一圈，再次以令人战栗的速度往上弹起。光线再度贯穿红色军队，重武装的士兵们连同铠甲被劈成两半。

「…………好厉害。」

谢达以几乎不成声的声音这么呢喃。

＊＊＊

诗乃以没有一丝犹豫的动作，架起由索鲁斯之弓变化而成的爱枪黑卡蒂Ⅱ。

与Subtilizer之间的距离不到二十公尺。用反器材步枪进行狙击的话，这种距离实在太近了。在这样的距离下，很难持续用高倍率瞄准器捕捉移动的敌人。

因此诗乃决定在Subtilizer开始移动前分出胜负，所以透过瞄准器镜头看见黑影的瞬间就扣下扳机。

闪光。轰然巨响。

强烈的后座力袭击了在空中盘旋的诗乃。她拚命控制以倾斜轴心旋转的身体。每次射击身体都会像这样失去平衡的话，实在没有办法连射，但只要刚才那发子弹命中一切就结束了。

好不容易让身体安定下来，诗乃的视界看见了Subtilizer。

然后因为惊愕而瞪大了眼睛。

站在有翼生物背上的男人抬起左臂，把五只手指弯曲成钩爪状。

手掌里光与暗混杂在一起后形成强烈的漩涡，而中央那个微小但是发出强烈光芒的物体，无疑就是诗乃发射出去的子弹了。

50口径反器材步枪发射出去的，足以贯穿两公分厚钢板的子弹……

会像诗乃的意识一样被吸收进去吗？

诗乃的心里稍微产生了一丝怯懦。就像与她的感情变化同步一般，从Subtilizer左手放射出来的黑暗更加强烈了。

「不要输啊……」

诗乃无意识中这么呢喃。接著又叫了一声。

「不要输啊，黑卡蒂！」

滋啪。

发出这样的声音后，光芒贯穿了黑暗。

Subtilizer的左手开了一个大洞，鲜血与肉片呈漩涡状飞溅开来。

────行得通！

诗乃大大吸了口气，然后拉下黑卡蒂Ⅱ的退弹杆。排出的空弹壳一边闪闪发亮一边落下。

Subtilizer默默低头看著受伤的左手。虽然黑暗像黏液般逐渐填满开了个大洞的手掌，但那不是那么容易就能治愈的伤势。

他抬起笑容消失的脸来盯著诗乃看。

接著右手从腰间拿下十字弓。

「……哼。」

诗乃用鼻子轻哼了一声。那种东西怎么可能对抗得了反器材步枪…………

歪斜扭曲。

十字弓突然扭曲了起来。

往左右两旁突出的弓体往内折叠，整体长度则伸长了一倍。原本是木制的框架，开始带著灰色金属光泽。

短短一秒钟后，Subtilizer的右手上就握著一把与黑卡蒂同样巨大的步枪。诗乃立刻就认出这把枪械的名称。

巴雷特M500狙击步枪。

虽然和黑卡蒂Ⅱ同样是50口径，不过是属于更新世代的反器材步枪。

Subtilizer的嘴角再次刻划著扭曲的笑容。

「……好样的。」

诗乃这么呢喃完，就把黑卡蒂Ⅱ的枪托用力抵在右肩上。

＊＊＊

「呜哇……不……不要紧吧？」

柳井像是真心替人担心的声音，让比嘉一瞬间忘了疼痛而大叫：

「喂……喂，自己开的枪，说的好像不关你的事一样……！」

「没有啦，我没打算射中你，这是真的。我还不至于想背一条杀人罪在身上，好不容易能在西岸买下帅气的豪宅，得战战兢兢地过生活就没有意义了吧？」

一了解柳井说的应该是真话，脱力感就袭上心头，让比嘉的手臂失去力量。心想「这样不行」而重振精神后，才畏畏缩缩地确认右肩的伤势。

从导管的壁面反弹回来的子弹，似乎命中锁骨的正下方。跟疼痛比起来，这时是冰冷的麻痹感开始蔓延到整条右臂。衬衫的侧腹部分早已染成红黑色，看来不是什么擦伤才对。

对于现在的状况，以及今后发展的恐惧这时终于从胃部下方附近一点一点往上涌，让比嘉反覆急促的呼吸。数公尺上方的柳井依然以一副志得意满的表情继续说道：

「原本只是想稍微妨碍比嘉先生的作业，然后破坏检修用电子连接器就从下面的主控室逃离。因为我应该也能搭上潜水艇～RATH这边也没有死者，这样只要能回收爱丽丝，就能有快乐的结局了～」

「你说……没有死者……？」

比嘉再次忘记伤痛，驳斥柳井的发言。

「……现在不趁这个机会治疗桐谷小弟的话，他的意识就再也不会恢复了！杀死他灵魂的就是你啊，柳井先生！这样你还敢说没有杀人的打算吗！」

「啊～啊～……这个嘛……」

柳井脸上忽然变得没有任何表情。在橘色紧急照明灯的照耀下，满是胡渣的脸抽搐了两三下。

「嗯……那个小鬼死了也没关系。」

「什…………」

「因为呢～那个家伙杀了我重要的小亚亚啊。」

「小亚……亚……？」

比嘉因为这生疏的名字而露出疑惑的模样，柳井则低头看著他愤慨地大叫：

「就是公理教会最高司祭，亚多米尼史特蕾达猊下啊！我和她约好了，要提供那个女孩子完全支配Underworld的最大支援。还有就算伺服器被格式化，也会确实地保存那个女孩的LightCube。」

比嘉愕然瞪大了双眼。

公理教会是Underworld内统治人界的组织名称。藉由极为严厉的法律以及强大的武力来完全支配居民。

比嘉他们之所以察觉突破界限的摇光「爱丽丝」出现还是无法确实得到她，就是因为在时间加速的Underworld里，公理教会一瞬间就带走爱丽丝，对她的摇光施加了记忆更改处置。

没错，他们的手法实在太迅速也太准确了。

简直就像完全熟知人工摇光是什么东西一样。

结果真的是这样。公理教会──至少可以知道似乎是他们最高层的，名为「亚多米尼史特蕾达」的人工摇光，已经了解整个世界的构造了。

「……就是你污染了Underworld吗……」

比嘉一低声这么呻吟，柳井就故意咂舌发出了啧啧声。

「等一下，一开始是那个女孩自己跟我接触的哟。在我值班的时候，忽然从扩音器里传出女孩子的声音，那时真是吓了一大跳……她是自己发现Underworld的指令表，打开与这边的内线。真要说起来呢，是忘记消除呼叫表格指令的比嘉先生自己的错啊。」

柳井发出「嗯呵呵呵」的笑声，像是想起什么事情般以沉醉的眼神继续说道：

「我一开始觉得，这样现在的Underworld应该马上就会被完全格式化了。既然所有人都要消失应该就无所谓，所以就偷偷用STL去跟小亚亚见面。结果呢……啊啊，我还没看过那么漂亮的女孩子呢。虽然须乡先生关在ALO里的女孩也很可爱，但小亚亚不论是性格、声音、动作等一切都正如我的理想……──那个女孩和我约好了。提供帮助的话，就让我当首席仆人。还说有一天要连现实世界也一起支配，然后让我担任国王……」

────不对。

被污染的是这个男人。

比嘉因为战栗感过于强烈而感觉全身寒毛直竖。柳井虽然是愚蠢的背叛者但不是普通的笨蛋。能够让这种人如此迷恋并且加以支配的亚多米尼史特蕾达，究竟是什么样的存在？

这时似乎沉浸在回忆里的柳井，表情再次从脸上消失。

「……但是，那个女孩却死了。被同时也阻碍须乡先生实验的那个小鬼杀掉了……不帮小亚亚报仇的话，她就太可怜了……」

柳井瞪大布满血丝的双眼，再次用手枪对准比嘉。由于自动手枪在射击出一发子弹后，击锤就会自动被压下，所以扳机比第一发时轻多了。食指稍微一用力，子弹应该就会再次被发射出去。

「……没错……就是这样，我要是不杀个人，怎么对得起那个女孩子呢……」

柳井瞪大的眼睛中央，收缩的瞳孔产生细微的震动。

……糟糕。这次是认真的了。

比嘉忍不住闭起眼睛。

＊＊＊

──来不及了。

莉法感觉到远方的亚丝娜、克莱因以及莉兹贝特等人陷入险境，忍不住紧咬起嘴唇。

但是眼前却有多达将近三千名左右的红色铠甲士兵挡住去路。

请求似乎是半兽人族长的利鲁匹林，为了营救亚丝娜和桐人而朝著南方前进，结果终于发现的并非原本要营救的人界守备军。

眼前有仅仅数百名的男女被应该是从现实世界潜行至此的军队包围，利鲁匹林表示他们是和半兽人一样隶属于暗黑界军的拳斗士。知道这件事之后，莉法就拋开一瞬间的犹豫，决定要帮助他们。

「由我独自杀进敌人阵营。利鲁匹林你们和拳斗士会合，只要打倒想到那边去的敌人就可以了。」

这么指示完，利鲁匹林就猛烈地提出「我们也要一起战斗！」的抗议。但是莉法却用力摇了摇头，然后一边握住半兽人粗犷的手一边说：

「不行喔，我不希望你们继续增加牺牲者了。我没问题的……那种家伙，来几万个我都不会输。」

这么笑著说完，莉法就独自面对红色军队。

早已确认过提拉利亚的HP拥有几乎无限的回复力。而且前方的现实世界人，同样也是拥有虚拟生命的人们。既然已经赶不及去救援桐人他们，莉法实在没办法让这些半兽人平白死在这里。

以超长范围的二连击砍杀数十名敌人的莉法，没有停下脚步就直接冲入敌阵当中。

她不断施放不知道为什么攻击范围比ALO扩张了好几倍的剑技。每当从提拉利亚的GM装备「鲜果灵魂」绽放出鲜艳的闪光，就会有血花呈放射状飞溅出来。

但还是无法消除剑技与剑技之间产生的僵硬时间，无数刀刃就趁著这个时候袭击过来。由于无法回避所有攻击，结果莉法的身上就被刻画上好几道伤痕，灼热的剧痛让她感到晕眩──但是……

「嘿────！」

随著撕裂绵帛的吼叫声，右脚用力朝地面踏去。从脚边冒出一片轻飘飘的绿色光辉，一瞬间就把她全身的伤治好。

莉法承受著实在无法消除的疼痛余韵，专心一志地挥舞著剑。

就算受到一万处伤害，也要想办法把这个地点的敌人赶回现实世界去。

如果说因为座标偏差而被送到意外地点的自己有什么任务的话，那一定就是尽量拯救Underworld的人了。自己必须拯救桐人喜爱并且想要保护的这些人。

「She"s such a boss！」

莉法用左臂挡下随著这种叫声猛烈刺出来的剑。

「嘿啊啊！」

反击的一剑，一口气就了结了持剑者的性命。

莉法用嘴咬下刺在手臂上的剑后，就随著鲜血一起把剑吐掉。

＊＊＊

第二发子弹几乎是在同一时间发射。

从两把反器材步枪发射出去的子弹，在几乎快要触碰到的距离下擦身而过，接著弹道整个产生变化而朝虚空飞去。

诗乃这次没有狼狈地失去平衡，双脚确实踢著空气抑制住后座力。视线前方能看到Subtilizer也在猛烈拍动翅膀的有翼生物背上踩稳了脚步。

对诗乃来说，还是第一次像这样在上下左右完全开放的空间里，互相拿著反器材步枪攻击对方。由于在GGO里并没有辅助飞行，所以这也是理所当然的事，没想到基本上是竖起两脚架进行卧射的黑卡蒂，在空中的后座力会这么大。

这场比试──

先抑制后座力，比敌人快上一瞬间发射下一发子弹的人就能获胜。诗乃一边退弹一边这么想著。

Subtilizer应该也有同样的企图吧。飞翔的诗乃这时试著要绕往右方，而他则是拚命要取得相反方向的位置。

虽说不是有什么讯号，但双方几乎是在同一个时机下开始高速移动。

在不失去平衡的前提下，于空中反覆以锐角转向，持续地无定向飞行著。在枪口紧紧追随著敌人的情况下，也强烈意识到自己也一直在敌人射线当中。

Subtilizer架起来的巴雷特可能终于预测出诗乃的行动了吧，只见它以令人眼花撩乱的速度移动著。

──要来了！

诗乃咬紧牙关，瞪大了双眼。

巴雷特的枪口迸出火光。

诗乃以界限速度飞翔，并将身体往左边扭。

致死的子弹一边发出低吼，一边通过足以烧焦胸口的距离。蓝色护甲发出「哔叽」一声裂开。

────闪开了！

最初也是最后的机会。在Subtilizer为了抑制后座力而静止的那一瞬间射击！

准备架起黑卡蒂的诗乃所看见的是……

从正面飞来的下一发子弹。

连射──为什么？

啊啊……糟糕。

和每发射一发子弹就得拉起退弹杆的黑卡蒂不同，巴雷特是半自动射击步枪。

这样的思绪在脑袋里爆开的同时，诗乃的左脚也像从膝盖上方爆炸一样变成了碎片。

＊＊＊

抵抗绝望的状况，到最后都持续站在战场上的，是受到超级帐号保护的亚丝娜，以及Underworld人整合骑士连利、他的骑龙，再加上在骑士与龙的保护下持续果敢挥著剑的少女练士缇洁与卫士长索尔缇莉娜。

亚丝娜因为极度疲劳与痛苦而模糊的视线里，一直捕捉到骑士连利鬼气逼人的战斗模样。

十几分钟前，小个子的骑士一出现在前线就让十字回旋镖自在飞翔，把蜂拥而至的敌军全都砍倒。其恐怖的威力，甚至足以将邻国人满腔怒火的突击挡回去几分钟。另外，巨大飞龙发射出来的热线也让敌人相当害怕，完全证明了他们是在Underworld这个异世界出生长大的真正龙骑士。

但不久后敌人也注意到了。骑士连利在投掷、操纵回旋镖的时候本人几乎是处于毫无防备的状态。

当回旋镖不知道第几十次的飞翔，准备扫倒红色军队最前列的瞬间，就从后方投掷出无数的长枪。和美国人玩家战斗时，亚丝娜暗暗担心的战法，现在终于被实现了。

长枪宛如黑雨般从红色天空降下。

这时连利的飞龙以张开羽翼的身体挡下最初的攻击来保护主人。

飞龙就在剥落的鳞片与鲜血四溅的情况下直接往旁边倒去。

新的一阵枪雨立刻落下。

一瞬间往上看了一下发出「沙啊啊」声朝这里袭来的无数枪尖，骑士连利就转过身子抱住身后的缇洁，让她躲在自己身体下面。

下一个瞬间，背上被两只枪插入，连利像要趴在缇洁身上般往前倒。失去控制的十字回旋镖，绽放短暂的光芒后分裂为二，然后刺入远处的地面。

这个时候，战场其他地方的战斗也几乎都结束了。

红色士兵群聚在筋疲力竭而倒地的日本人玩家身边，争先恐后地以剑刃朝他们身上招呼。鲜血、肉片，以及细微的悲鸣飞溅，最后安静下来。

另外也有许多盾牌与铠甲全遭到破坏，光著身体被按在地上的人。他们脸颊上流下来的悔恨泪水，和从伤口流出来的血同样让人心痛。

两千名转移组的防御阵几乎遭到无力化，至今为止被保护在中央的人界军终于开始露出来了。

大约四百名人界军卫士，为了保护非武装的补给部队与修道士队而举剑围成一圈。他们每个人脸上都充满悲壮的觉悟，面对一点一点逼近的红色军队，静静地等待著发动决死突击的时刻。

「…………住手…………」

亚丝娜听见从自己嘴唇里掉出来的声音。

那不是因为全身受到的伤痛，而是因为绝望与哀伤而失去斗志的声音。

「拜托……不要再打了……」

右手上的细剑随著呢喃滚落到地面。从脸颊滴落的泪滴掉在满是伤痕的剑身上后轻轻弹起。

挡在眼前的红色人影，随著充满敌意的骂声把两手剑高高举起。

──这个剎那。

宛如雷鸣般的巨大声音响起，让准备对亚丝娜挥落的剑刃，以及在战场各处进行中的所有战斗都停了下来。

以难以衡量的音量叫出「STOP────！」的，是至今为止都在远处看著这场战斗的黑斗篷男。也就是杀人公会──微笑棺木首领PoH的亡灵。

邻国人玩家们似乎因为浮标还是某种原因认为黑斗篷男是指挥官，在百般不愿意的状况下还是放下了武器。原本准备斩亚丝娜于剑下的男人也随著猛烈的咂舌收起剑，改成让她尝尝随脚使出的踢击。

从背部倒在地上的亚丝娜，拚命以无力的手臂撑起身体。

视线四处巡梭之后，就看到晃动黑色皮革下襬往这边走过来的高大男人。他以低沉但响亮的声音对周围的红色玩家搭话，但因为是韩文所以无法了解意思。

周围的红色士兵不停点头，开始对周围的伙伴传达些什么消息。

突然间，站在旁边的男人抓起亚丝娜的头发并且往上拉。虽然忍不住发出悲鸣，但男人根本不理会，直接用力拖著她往前走。

周围也进行著类似的行为。看来他们是打算把还活著的日本人玩家聚集在一起。

黑斗篷男满不在乎地走近现在依然举著剑的人界军卫士们，接著转头举起一只手，再次对抓住亚丝娜头发的男人下达了某种指示。

被人粗暴地往背后一踢，亚丝娜飞出数公尺的距离然后滚落在地面。周围一直站著的日本人玩家也被推倒。

生存者的人数已经不到两百人。

HP的量应该直接与生存率连结吧，果然有许多高等级的玩家还残留著。稍微环视一下现场，立刻就发现ALO的领主们以及沉睡骑士的成员。

他们的所有武装不是被破坏就是被夺走，身上只有破破烂烂的衣服。外露的肌肤上全是伤痕，许多人身上依然插著折断的刀刃。但他们脸上全都浮现著同样深沉的无力感与失败感。

不想再看任何东西了。真想直接趴在地上，到最后的瞬间都闭起眼睛。

但亚丝娜还是透过渗出的泪水，想把转移到此帮忙的众玩家身影烙印在眼里。

视线绕过一圈后，就发现稍远处有一名抱住两脚膝盖，肩膀不停震动的女性玩家。粉红色短发上全是灰尘，红豆色的服装也到处是破洞。

亚丝娜爬著靠近那个背部，然后用双臂绕过好友的身体。

莉兹贝特一瞬间全身绷紧，但随即把头靠在亚丝娜身上。被血与泪水濡湿的脸颊颤抖著，然后发出沙哑的声音。

「大家……我……我害大家被……」

「不是的……不是这样的，莉兹！」

亚丝娜也以含著泪水的声音轻轻叫道：

「不是莉兹害的。是我不好……考虑得更周全一点，应该就能预测到才对……」

「亚丝娜……我……完全不知道。战争是这么恐怖……战败是这么痛苦……我真的完全不知道……」

不知道该如何回话的亚丝娜只能再次抱紧莉兹贝特。从双眼溢出的泪水不断从脸颊滑落。

这时又听见细微的啜泣声，往该处看去，就发现倒在地上一动也不动的艾基尔，以及蹲在他身边的西莉卡。

艾基尔身受让人觉得这样HP竟然还没有归零的重伤。为了保护西莉卡，应该是经过一番激战吧。巨大身躯上刺著好几把折断的剑与枪，四肢看起来也几乎全被敲烂了。之所以紧咬著牙根，一定是因为承受著超乎想像的痛苦吧。

他们附近也能看见盘腿垂颈而座的克莱因。他肩膀下方的左臂被砍断，伤口缠著作为他注册商标的头巾。

所有生存者几乎都是差不多的状态。

黑斗篷男睥睨著趴在地上这两百名武器、铠甲以及斗志都被剥夺的敌人──从兜帽深处露出的嘴巴露出无声的灿烂笑容。

他迅速翻转身躯与人界军的卫士们相对。

亚丝娜带著恐惧的心情，等待他举起右手做出杀掉所有人指令的瞬间。

但是，他对人界人所发出的，竟是内容令人意外的日文。

「放下武器投降。这样的话，我就不杀你们和后面的俘虏。」

卫士们的脸闪过一瞬间的惊讶，接著是深沉的愤慨。往前走出几步来和黑斗篷男相对的是女性卫士长索尔缇莉娜。应该是一直和连利一起在最前线战斗吧，只见她的剑剑刃已毁，额头上也流下鲜血。

即使如此还是无损美貌的索尔缇莉娜，以毅然的声音叫道：

「……别开玩笑了！到了这个时候，还以为我们会为了活命而……」

「照这个人所说的去做──！」

亚丝娜打断索尔缇莉娜说的话拚命大叫著。

她在紧抱著莉兹贝特的情况下，抬起被泪水濡湿的脸庞拚命恳求著。

「拜托……你们要活下来！不论受到什么样的屈辱，请都要活下去！因为这是……这是我们的……唯一的……」

唯一的希望啊。

胸口揪紧的亚丝娜无法把话说完。

但是索尔缇莉娜与众卫士已经紧闭起嘴巴、扭曲著脸庞，身体震动了一阵子后才缓缓垂下肩膀。

看见发出「喀锵喀锵」的声音被丢到地上的剑后，四周围重重包围卫士的邻国人玩家之间就发出高昂的胜利叫声。叫声立刻又变成连续呼喊著自己国家的名字。

黑斗篷男迅速举起一只手呼唤数名玩家，然后做出某种指示。男人们立刻点点头，推开投降的人界军往圆阵深处跑去。

才兴起「到底想做什么……」的念头，黑色斗篷男就发出沙沙的脚步声走过来站在亚丝娜面前。

即使在这样的距离之下，依然看不透兜帽深处的黑暗。好不容易才能看见顽强的嘴角以及垂在脖子附近的黑色卷发。

他的嘴巴浮现扭曲的笑容，接著发出带著某种开朗气氛的声音：

「……嗨，好久不见了，『闪光』。」

────这个男人，果然是！

屏住呼吸的亚丝娜从胸口深处挤出话来。

「……你是……PoH……！」

「哎呀，真令人怀念的名字。很高兴你还记得哟。」

这个时候，右手撑在地上一点一点靠过来的克莱因，以燃烧烈火般的眼睛往上看著黑斗篷男。

「是……是你这家伙吗。你这杀人狂……竟然还活著！」

男人的靴子随便就把想用单手抓住自己的克莱因踢飞。

亚丝娜咬紧牙根，以低沉的声音问道：

「这是……复仇吗？对我们攻略组毁灭微笑棺木的复仇……？」

「…………」

PoH默默无言地往下看著亚丝娜一阵子。这时亚丝娜注意到他的肩膀不停微微震动。

几秒钟后，他像是再也无法忍耐般剧烈笑了起来。斗篷下的身体扭动著，他则是持续发出「呵呵呵、哈哈哈」的笑声。

发作般的嘲笑终于止歇，PoH伸出右手的食指后就愉快地继续说道：

「啊～呃……这种时候用日文要怎么形容啊……因为一直待在美国，粗话之类的都给忘记了呢。」

不停转动的手指，忽然弹出「啪叽！」的声响。

「对了对了，是『你傻了吗？』，真是太好笑了，这个嘛……」

瞬时弯下膝盖的男人，从至近距离窥看著亚丝娜的脸庞。这时只能看见他兜帽深处闪闪发亮的眼睛。

「……我就告诉你吧。向你们这些攻略组密告微笑棺木秘密基地的就是本大爷哟。」

「什…………」

亚丝娜、克莱因，甚至连濒死的艾基尔都瞪大眼睛。

「为什么……怎么会…………」

「当然有一部分是因为想看猴子自相残杀……但最大的理由应该还是这个吧。我呢……很想让你们变成『杀人犯』哟。你们这些装出一副清高的勇者模样，骄傲地站在最前线的攻略组大人。要策画这一切真的很费工夫哟……还得看准没办法逃走但来得及迎击的时机警告微笑棺木那群家伙。」

──那场秘密基地突袭作战之所以会事先走漏消息，就是因为这个原因吗，亚丝娜虽然感到愕然但还是继续思考。

就因为这样，战斗刚开始时等级与装备优于对方的攻略组反而屈居下风，甚至出现几名死者。之所以能改变劣势，是因为虽为独行玩家但实力受到肯定的桐人奋战不懈，在他砍倒一名微笑棺木的主力后，状况因而逆转……

「……那就是……你的目的吗？」

亚丝娜以断断续续的声音呢喃著。

「为了让桐人……背负PK行为的罪过……？」

「Yes. Absolutely yes.」

PoH以带著热气的声音做出肯定的答案。

「我以隐蔽技能躲在旁边观赏了那场战斗哟。黑漆漆先生失去理智干掉两个人时，我差点因为爆笑而被识破隐蔽呢。按照计划，接下来是要利用麻痹毒把那家伙和你无力化，然后好好访问一下当时的情形……没想到会在第七十五层就结束了。」

瞬时沸腾的愤怒，让亚丝娜忘记伤口的疼痛。

「你……你知道那时候的事情让桐人多么痛苦与烦恼吗！」

「哦，那真是太好了。」

与亚丝娜形成对比，PoH的声音带著冰一般的寒气。

「不过，这就奇怪了。那家伙真的感到后悔吗……一般来说，应该会连看都不想看到VR游戏吧？因为觉得对不起杀掉的家伙。我很清楚哟，那家伙也在这里吧。我可以感觉到喔。虽然不知道为什么躲在马车里……算了，直接问他吧。」

咧嘴对说不出话来的亚丝娜笑了笑，PoH就迅速站了起来。

在周围依然不断涌出的欢呼声作为背景下，宛如冰一般寒冷的声音流出。

「It"s show ti────me！」

说出在SAO暗中作乱时的惯用句，并猛然举起右手的PoH身后──

可以看见红色士兵们粗暴推著的轮椅，以及拚命跟在后面的灰色制服少女。

啊啊……

住手。

只有这件事绝对不行。

亚丝娜胸中充满悲痛的恳求。克莱因虽然像跳起来般准备起身，但立刻又被压下去。

PoH轻轻弯曲上半身来窥看著被推到自己眼前的轮椅。

「…………嗯嗯？」

随著感到疑惑的沉吟，用脚尖戳了一下从椅子上往下垂的瘦弱腿部。

「这是怎么回事……？喂，黑漆漆的，快起来啊。听见了吗，黑衣剑士大人？」

被叫到过往绰号的桐人──这时依然没有任何反应。

透过黑色上衣也让人不忍卒睹的瘦弱身体靠在椅背上，脸孔则是深深地下垂。空无一物的右边袖子随风摇摆，抱著两把剑的左手也因为骨瘦嶙峋而相当显眼。

被推到亚丝娜身边的罗妮耶不停眨著哭肿的鲜红眼睛，然后小声地说：

「桐人学长……在战斗当中，不停、不停地想站起来……最后好像用尽力气而安静下来……但是……只有……只有眼泪一直流个不停……」

「罗妮耶小姐……」

亚丝娜伸出左手，把啜泣的罗妮耶那纤细的身体抱过来。

然后猛然抬起脸，对PoH丢出尖锐的发言：

「这样你知道了吧。他不断地作战再作战，让自己变得满身疮痍了。所以别再打扰他了！让桐人安静地休息吧！」

但是黑色斗篷男却像是听不见亚丝娜说的话一样，从至近距离窥看著桐人的脸。

「喂喂喂，不会吧！这样的话根本没办法收尾嘛！喂，快起来！嘿，Stand up！Good m！」

PoH的右脚忽然放在银色车轮上，然后无情地把轮椅踢倒。

瘦削身躯从随著吵杂的金属声往旁边倒的轮椅上被拋到地面。

亚丝娜与克莱因虽然同时想站起来，却被士兵的剑压住。艾基尔也发出低沉的愤怒声，莉兹贝特、西莉卡与罗尼耶则是发出细微的悲鸣。

但是PoH还是没有罢手的样子，走近桐人后用脚尖粗暴地把他翻过来。

「搞什么……真的整个人坏掉了吗？那个勇者大人变成一个傀儡？」

从现在依然紧抱著两把剑的手臂当中夺走白色剑鞘。被粗暴拔出的剑身，暴露出从中折断的狼狈模样。

PoH随著盛大的咂舌声准备把剑丢掉时──

「啊……啊……」

桐人带著细微的沙哑声音，虚弱地将左臂朝著白剑伸去。

「哦？动了耶！怎么，你想要这个吗？」

PoH像要吊人胃口般移动著白剑，然后随手把它丢出去。接著一把抓住桐人在空中随著剑移动的左臂，然后把他拉起来。

「喂，说句话啊！」

PoH的左手赏给桐人耳光后发出「啪啪！」的声音。

亚丝娜的视界因为过于愤怒而染上淡红色。但比再次准备站起来的她快了一步，克莱因呕血般的吼叫声已经响彻现场。

「臭家伙！你这臭家伙不准碰桐人────！」

想用单手抓住对方的克莱因，背部被一把大剑贯穿，无情地把他钉在地上。

即使「喀」一声吐出大量鲜血，克莱因还是撕裂自己的身体，继续想往前进。

「只有……你……！绝对……无法原谅…………」

咚喀！

钝重的声音响起，第二把剑贯穿克莱因的身体。

让人不敢相信到现在竟然还没干枯的眼泪不断地从亚丝娜双眼溢出。

＊＊＊

在一只脚不知道被轰到哪里去的疼痛之前，诗乃先尝到了无法顺利飞行的恐惧。

至今为止，诗乃是以脚踢著空气的感觉来控制任意飞行。结果只靠右脚来尝试的急速回避，变成了狼狈的圆锥状旋转。

「呜…………」

诗乃一边咬牙，一边进行著唯一可能的迅速行动，也就是不断笔直往后退。从左脚流出的鲜血在空中拉出一条红线。

尽可能以最快的速度拉开与敌人的距离，并且瞄准Subtilizer，发射了第三发子弹。

但以宽裕表情追上来的敌人，手中的步枪也同时开火射出第四发子弹。

在同一直线上往前突进的两颗子弹，交错的瞬间发出尖锐的不协调音与鲜艳的火花并且偏离轨道，各自往遥远的虚空飞去。

拉下退弹杆把持续在胸口深处扩散的恐惧随著弹壳一起排出，诗乃接著发射第四发子弹。

两道雷鸣声又再次同时响起。子弹接触的瞬间，巨大能量在空中扩散，画出螺旋轨迹往外飞去。

第五射、第六射。

结果都是一样。Subtilizer明显是故意配合诗乃的射击来扣扳机，不断让子弹互相冲突。

现实世界就不用说了，就连在GGO里也办不到这种事。但是，这个世界一切以想像力为优先。本来就有此企图的Subtilizer就不用说了，因为就连诗乃也预想会出现这种结果，因此以超音速飞行的子弹互击这种不可能的现象也变成现实。

即使如此，诗乃也只有拉退弹杆、瞄准、扣扳机这三个动作可以做了。

第七发子弹边撒著哀戚的声音边大大地往右边错开并且消失。

退弹、瞄准。

──喀嚓。

撞针配合著诗乃手指的动作发出空虚的「喀嚓、喀嚓」声。

黑卡蒂Ⅱ的装弹数，一个弹匣是七发。没有预备的弹仓。

相对的，巴雷特M500的装弹数是十。目前还剩下两发。

诗乃清晰地看见了，在距离一百公尺以上的地点，Subtilizer脸上浮现的冷笑。

架在手上的黑色枪械喷出火来。

继左脚之后，诗乃的右脚也从底部被轰飞。

这一瞬间，就连一直线的飞行都办不到，诗乃的身体慢慢开始往下掉。

抑制了后座力的Subtilizer，为了发射最后一击而把右眼贴在瞄准器上。被镜头扩张到最大的蓝色玻璃般眼睛，笔直地贯穿了诗乃的心脏。

──对不起。

对不起了，亚丝娜。对不起了，结衣。对不起了……桐人。

诗乃在嘴里这么呢喃之后，M500的第十发子弹就从它的下颚解放出来。

空中拉出一条红色火焰的螺旋，正确地顺著Subtilizer的视线飞过来的子弹，粉碎了诗乃的铠甲、蒸发了她的上衣，前端碰到她的肌肤──

啪叽！

再次迸出那道火花。

睁开快要闭上的双眼，出现在诗乃眼前的是，小小的银色圆盘挡住高速旋转的细长子弹。

旋转的白色火花当中，厚度不到两公厘的金属，像是在展现坚定的意志般发出光辉，看见这一幕的瞬间，诗乃的双眼就溢出泪水。

──不能放弃。

绝对不能放弃。要相信自己和黑卡蒂，以及透过这个金属与自己连结在一起的一位男孩。

随著更加激烈的闪光，银盘与步枪子弹同时蒸发掉。

诗乃以坚定的动作架起黑卡蒂Ⅱ，并把食指放到扳机上。

就算因为想像力而让这把武器变成枪的形状，但是系统上赋予武器的特性应该还是持续存在才对。也就是自动从周围的空间吸收资源，化成攻击力装填进去的索鲁斯之弓──「歼灭光线」的力量。

这样的话就能射击。不论弹匣的子弹是否用尽，黑卡蒂都会回应自己。

「去……吧────────！」

诗乃扣下扳机。

发射出去的并非带著金属的穿甲弹。

凝缩无限能源所形成的白色光线，一边从枪口制退器放射出七彩极光，一边一直线飞奔过天空。

笑容从Subtilizer的脸上消失。当他准备往右横移来闪避的瞬间，白光直接击中巴雷特的枪身。

橘色火球往外膨胀，完全吞没了Subtilizer──

轰然巨响。爆炸。

肌肤感受著蜂拥而至的热风，诗乃就像石头一般落下，数秒钟后猛烈地撞上满是岩石的地面。

不要说飞行了，就连爬行都办不到。被轰飞的双脚带来强烈的疼痛，甚至让诗乃要保持意识都很困难。

即使这样，诗乃还是抬起眼睑，想要看清浑身解数的一击有什么结果。

飘荡在遥远空中的黑烟被风吹走。

从中出现的是──Subtilizer持续盘旋著的身影。

但他不是毫发无伤。被卷进步枪爆炸的右臂完全消失，从肩口冒出淡淡的白烟。原本光滑的右脸也被烧焦，从嘴唇垂下一条血迹。

Subtilizer的脸上终于浮现凶恶的杀意。

……没问题。不论来多少次我都会当你的对手。

诗乃挤出剩下来的所有力气，准备举起黑卡蒂。

几秒钟后，Subtilizer的视线忽然移开。有翼生物转身改变方向，拖著一缕细烟一直线往南边飞去。

诗乃轻轻地把快要无法保持外型的反器材步枪放到地面上。一触碰到地面的瞬间，它就变回原本的白色长弓。

诗乃用最后的力量举起右手，抚摸著留在胸口的炼子底端。

「…………桐人……」

在呢喃的同时，眼泪也顺著脸颊滑落。

＊＊＊

莉法已经没有多余的心思把插在身体上的数把刀刃拔出来丢弃了。

全身的疼痛融合在一起，就像是直接用针刺激著完全外露的神经一样。

好几道伤痕已经很明显可以称为致命伤了。一有动作贯穿腹部的两把剑就会割伤内脏，从背部贯穿胸口的一把剑则确实地刺中了心脏。

但是莉法还是没有停下来。

「唔……喔喔啊啊啊！」

大量鲜血随著吼叫声迸出，她发动了不知道是第几十次──或许是第几百次的剑技。

长剑「鲜果灵魂」带著绿色光辉，在空中往四面八方砍去。凝聚在周围的光之圆弧，经过一瞬间蓄力后无声往外扩散，跟著就有无数敌兵的身体开始崩坏。

看准施放大技后的僵硬时间，数名敌人一起杀到。虽在千钧一发之际往后飞退而避开大半的攻击，左臂还是因为长斧枪的一击被砍掉了。

好不容易才站稳脚步，没有因为冲击而跌倒……

「嘿呀啊啊啊！」

快速的横扫一次砍翻三个人。

莉法捡起掉在地上的左臂，把它按在伤口上之后用力踩下右脚。

地面随著绿色闪光冒出花草并且消失。HP跟著恢复到上限，虽然留下惨不忍睹的伤痕，但是左臂已经再次接上了。

这种状况之下，提拉利亚帐号赋予的无限回复能力已经无法称为神的恩宠了。

反而应该说是诅咒还比较合适。不论受多少伤，尝到多少剧痛都不能够倒下。虽然是不死但不是不可侵犯，因此得承受难以想像的折磨。

支撑著莉法的，唯一就只有一个信念。

──哥哥的话。

绝对不会因为这点伤而倒下。

这样的话，我也不会倒。不过是三千名敌人，看我独自把他们全都干掉。因为我是……哥哥的……「黑衣剑士」桐人的…………

「────妹妹啊啊啊啊！」

架在左手上的长剑刀尖迸发出鲜红光辉。

随著「喀咻！」的重金属声被刺出来的刀上，施放出巨大的光之枪，笔直地贯穿战场达一百公尺以上。敌兵的身体「啪嚓！」一声弯成圆形往外飞散。

「……呼……呼…………」

急遽吐出的气息，立刻变成大量的鲜血。

莉法擦拭完嘴角，摇摇晃晃地站起身时，随著低吼飞来的长枪直接贯穿她的左眼然后从后脑勺透出去。

虽然往后踉跄了几步──但莉法还是没有倒下。

她以左手握住枪柄，一口气将其拔出。疼痛之外的另一种异样感觉穿透头部内侧。

「呜……呜呜呜喔喔喔！」

她边叫边猛烈踏步来回复自己的HP。暂时欠缺的左侧视界，随著「噗滋」一声复活了。

一看之下，不知不觉间敌人也只剩下一百人左右。

莉法咧嘴笑了起来，把满是鲜血的左手往前伸，将手掌朝上之后，动起了并拢的手指。

面对发出自暴自弃的吼叫声往这边突进的集团，她滋一声以沉重的动作挥落长剑。

「咿耶……啊啊啊啊啊啊！」

剑光一闪。

鲜血喷起，莉法毫不畏惧地闯入遭到阻断的敌人集团中央。

大约三分钟后，最后的敌人倒下时，莉法身体也增加了十把插在上面的金属。

四肢失去力量，摇摇晃晃地往后倒去，结果被贯穿到背后的剑与枪撑住而在途中停住。

听著利鲁匹林等人以近似悲鸣的声音呼叫自己名字，并且往这里奔跑过来的脚步声，莉法闭起眼睛并且小声呢喃著：

「我……尽力了……哥哥…………」

＊＊＊

从左耳的耳麦听见经过压抑的叫声时，柳井手上手枪的扳机也同时动了起来。

「比嘉，快闪开！」

咦？

闪开……是要我闪子弹吗？

刚浮现这种愚蠢的想法不久，比嘉就听见从很高的地方有某种物体撕裂空气掉下来了。

喀啊！

这道声响并不是枪声。而是从头上遥远处的导管入口丢下来的某样物体，直接击中了柳井的脑门。

柳井瞪大的双眼瞬间往上飘。握住梯子的左手也整个滑落。

「呜哇……等等……」

比嘉忘记肩膀的痛楚而用右手握住梯子，然后尽量把身体贴在导管的壁面上。

首先落下来的是，让人很想说到底从哪里弄来的巨大扳手。接著是还飘荡著硝烟味的小型手枪从眼前横越。

最后是丧失意识的柳井，身体刚好被夹在比嘉与导管壁面之间而停了下来。

「咿……咿！」

比嘉忍不住缩起肩膀，更用力将背部往壁面挤去。

柳井的身体慢慢滑落，汗臭味就这样一边抹在比嘉的衬衫上一边通过──

「…………啊。」

比嘉这么呢喃的同时，他已经掉到正下方深约五十公尺左右的直向洞穴里去。传出数次与壁面以及梯子撞击的声音，最后才是「咚滋」的沉重碰撞声。

「…………嗯……」

死掉了吗……？不，照那个样子来看，大概断了两三根……不对，是五六根骨头吧……

这时是耳麦里传来近似悲鸣的通讯，打断了比嘉这种快要停止的思考。

「比嘉……喂，比嘉！你没事吧？快回答我啊！」

「…………没有啦，只是有点吓了一跳……凛子学姊也会发出这种声音吗……」

「你……还有心情说这种闲话！受伤了吗？有没有被打中？」

「啊～嗯……」

比嘉再次望著右肩的伤口。

出血量逐渐让人觉得有点恐怖。右臂虽然能动但已没有感觉，而且还觉得很冷。感觉也没办法像平常那样思考。

但比嘉还是大大吸了口气，把力量积蓄在腹部之后，尽可能以充满精神的声音说：

「没有啦，我完全没事哟！只是擦伤而已。我要继续作业，拜托学姊帮忙观察桐人小弟的状况喽！」

「……真的不要紧吧？我可以相信你吧？说谎的话可饶不了你喔。」

「当然……请相信我吧。」

比嘉仰起头，对著在数十公尺前方舱门探出头来的凛子慎重地挥了挥了挥手。在这种距离与阴暗度之下，对方应该无法确认到自己流血的状况才对吧。

「那么……我就回主控室了，图表有什么变化的话我会立刻冲过来！拜托你了，比嘉！」

剪影缩回去的瞬间，比嘉忍不住轻轻呼叫了对方一声。

「啊……凛……凛子学姊。」

「怎么，有什么事吗？」

「没有啦……那个，嗯……」

──你知道学生时代不只是茅场学长和须乡那个混帐，连我也深深为你著迷吗？

比嘉虽然想这么说，但是感觉说出这种话生还机率就会大幅度降低，所以就用其他的话来把事情带过。

「那个，这场大骚动全部结束之后，一起去吃顿饭如何？」

「……我知道了，不论是汉堡还是牛肉盖饭我都请你吃到饱，好好加油吧！」

然后神代博士的身影就从比嘉的视界里消失了。

──太廉价了吧。

应该说，两者都很像要挂掉的家伙会说的话。

比嘉露出苦笑，接著把视线移回左手的笔电上。将指尖麻痹的右手放到键盘上面，慎重地开始输入指令。

四号STL……连接到三号。五号、六号……连接。

或许是失血的缘故吧，眼前的文字忽然变成双重，比嘉摇了摇头并在心底深处呢喃著。

──好了，桐人小弟，差不多到起床的时间啦。

＊＊＊

亚丝娜透过泪水的薄纱，专心一志地凝视著爱人的模样并且祈祷。

──桐人，拜托你。我的心与生命，什么都可以给你……所以，快醒过来吧。

──桐人。

＊＊＊

──桐人。

＊＊＊

──哥哥。

＊＊＊

…………醒来吧……桐人……

5

桐人。

感觉有人在叫自己的名字──

意识被从浅浅的假寐当中拉回来。

抬起眼睑，就看见在橘色光芒中浮游的无数细微粒子。

朦胧的视界慢慢聚集焦点。

摇晃的白布──是窗帘。

银色的窗框。老旧的玻璃。

晃动的树梢。缓缓在染著夕阳颜色的天空中延伸的飞机云。

吸了一口满是灰尘的空气撑起身体，就看见穿著水手服的背影站在深绿色黑板前。发出「咻咻」声从黑板上滑过的板擦，把用白粉笔写上的文字清除掉。

「……那个，桐谷同学。」

再次被叫到名字而移动视线，就和以有些怯懦又有些焦急的表情低头看著我的另一名女学生四目相交。

「我想搬桌子了。」

看来我是在班会中睡著，一直睡到了打扫的时间。

「噢……抱歉。」

呢喃了一声，把挂在桌旁的包包用手指勾起来，我也跟著起身。

感觉脑袋昏昏沉沉。

有种刚看完时间相当长──长到难以想像的电影之后的疲劳感。明明想不起任何的情节，却有深沉粗暴的感情残渣紧紧黏在脑袋里，让我用力摇了摇头。

我把视线从露出疑惑表情的女学生身上移开，一边朝著教室的后门走了几步，一边轻轻呢喃著。

「什么嘛……是梦吗…………」

** 后记

很感谢您阅读《Sword Art Online刀剑神域17 Alicization awakening》。

（请注意：接下来将会透露一大堆剧情！）

从上一集「eploding」开始就让大家等待了许久，真的非常抱歉。本集的副标题「awakening」是「觉醒」的意思，因此大家可能会认为「我们从第15集开始就一直沉睡的桐人先生终于要醒过来了吗！」，但很抱歉的是因为各种原因，只能在「醒来了吗……？还在睡吗……？」的情境之下等待下一集揭晓。其实我也很想收录到「第二十一章 觉醒」结束，但这样的话就会变成本集的分量相当厚，而接下来的第18集相当薄这种极不平衡的构成，于是只能在百般不愿意的情况下在此收尾。虽然不能说是「相对地」，但下一集不会让大家等太久，将依「下一本」再「下一本」的顺序出现在大家面前，还请各位再稍待片刻……！

接下来要稍微提一下本集的内容。在加百列、瓦沙克、克里达邪恶的计划之下，美国、韩国与中国的VRMMO玩家大举攻入地底世界，与人界军和日本人玩家展开连番激战，我大约十年前左右在网路版写到这部分情节时，是存在「如果能成为让大家重新思考当时网路游戏世界排斥外国人玩家的风气」……这样的意图。但是长期以来都对自己描写的能力不足，导致反而只煽动了敌忾心这样的结果感到很愧疚。

在作为电击文库版加写与修改时，曾经想过把这些情节整个变更，但是又觉得这样也算是在逃避……结果，大致上的情节还是没有什么改变。面对从Progressive就暗中开始活跃的「煽动PKer」瓦沙克/PoH所产生的恶意，桐人将会带来什么样的结局呢，关于这一点也请大家静待到下一集就能了解了。

SAO系列从网路的一隅诞生到现在是第十五年了，虽然有真的持续了很长一段时间的感慨，但接下来还会藉由剧场版、游戏以及其他许多的企画来扩展SAO世界，所以请各位今后也要陪著我继续走下去。最后还是要谢谢帮冲进地底世界的莉法与诗乃绘制凛然又美丽插画的abec老师，以及以编辑身份开始全新挑战的责任编辑三木先生！

二〇一六年三月某日 川原 砾