#+title: 刀剑神域 28 Unital ring Ⅶ
#+setupfile: ./setup.setup

* 刀剑神域 28 Unital ring Ⅶ（个人尝鲜翻译）

观前提示，仅供尝鲜阅读！仅供尝鲜阅读！仅供尝鲜阅读！认真阅读的话还是等拉斯翻译吧，一切翻译以拉斯的和简中为准。本人对日本的谚语几乎是一窍不通，一定会有不少出错的地方，请用爱包容

固有名词采用拉斯和简中的翻译，本卷出现的新固有名词我会在旁边写上原文

标点含义：（）小括号内为片假名的英文，或者是没有说清楚，由我来补充的事

{}大括号内的为译注

翻译：B_Meow

简介：桐人vs诸多谜团的《枪手》伊斯塔尔，爱丽丝vs皇帝阿格马尔。以宇宙军基地和中央大圣堂为舞台的不断扩大的战斗中，曾经《Under World》的守护者们，终于觉醒了。

整合骑士第二位法那提欧・Synthesis・Two，以及《古代七骑士》的一人，她的名字是——

另一方面，现实世界的明日奈也有了意想不到的再会。

「……对不起，亚丝娜。这两年间，一次也没有联络。」

新的邂逅和等待再会的《Unital ring》篇第七章！

川原砾：距离sao在2024年11月7日被通关的时间越来越近了！桐人他们现在正在60层左右努力吧，我今年也想做很多努力！

abec:啊呸嘘？

插图：

「还需要一个欺骗呢」 伊迪丝：最高祭司过去亲手冻结的《古代七骑士》的其中一位，是神器《斩暗剑》的使用者

「如果是桐人的话，绝对会做些什么的」 爱丽丝：整合骑士第30号，在200年后的uw也被继续歌颂为《金木樨骑士》

法那提欧：过去存在于《under world》的整合骑士团的第二代团长，是神器《天穿剑》的使用者

「有个想见亚酱的人サ」 帆坂朋：sao的封测玩家，也是手段高明的情报贩子，通称“鼠之阿尔戈”，在《Unital Ring》中支援桐人他们的战斗

「......难道是」 结城明日奈：桐人的恋人，在sao通关后和桐人一起在归还者学校上学，也一起在ur和uw战斗

「......亚丝娜」

能力值

ur世界的南部地图

本世界的形状为半径约700千米的巨大圆形，有着三段同心圆的构造。所有玩家的目标地点为圆的中央——第三阶层。第一阶层和第二阶层的高低差虽然高达200米，移动方法只有爬上阶层地下城（迷宫）

「这虽然是游戏，但可不是闹着玩的。」

——Sword Art Online刀剑神域开发者 茅场晶彦

** 1

「我来帮你喽，艾欧。」

我一边呼唤着用左臂抱着的剑士，一边注视着满是汗与血的白皮革面具。

在Under world里，想要知道他人的状态的话，最确实的手段是呼出「史提西亚之窗」，但只靠眼睛看的话也能感觉到某种程度。

整合机士团长艾欧莱恩・赫伦兹的面具窥视孔中镶嵌的薄玻璃深处，双眼正痛苦地眨着。青蓝色的眼睛看上去还有力气，但体力与精神力都差不多快要消耗殆尽是显而易见的。

虽然现在就想立刻帮他治疗，但我没有慢慢生成元素的余裕。因为距离我7、8米左右的地方，将艾欧莱恩逼到如此绝境的罪魁祸首正挂着冷笑。

我循着艾欧莱恩的气息打开的心意之门前方，是像宽敞办公室一样的房间。左右的墙壁上成排地摆着书架，正面有厚重的木制办公桌。我认识那个靠在桌面上，披着暗灰色外套的黑发丽人。是在伴星阿多米娜的秘密基地遇到过的诸多谜团的「枪手」托科伽・伊斯塔尔——

跟全身湿透的艾欧莱恩相比，伊斯塔尔的头发一根都没有乱。之所以会这样，大概是办公室里到处都有的异形尸体吧。

尖锐突出的头部与异常长的手臂。不论是皮肤还是从伤口里流出的血液都是和墨一样的乌黑。尸体的数量高达六具。

我曾经与这些尸体无比相似的怪物战斗过，但不是这个时代。在由最高祭司Administrator统治的两百年前，我在中央大圣堂的外壁与人造生物「米尼翁」战斗过。虽然细节有所不同，也装备了金属制的防具，但是同一种类应该是不会看错的。

虽然还不知道伊斯塔尔能率领米尼翁的理由，但因为她在阿多米娜的基地里不断重复着对神兽的孩子进行残酷的生物实验，所以倒也不是很惊讶。米尼翁跟两百年前相比应该也强化了，即使这样也一个人打倒了六只，艾欧莱恩会如此疲劳也是理所当然。

虽然身负整合机士团长的要职，却还是不以跟部下会合为目标而战斗的原因，我大概能推测出来。

房间里还有一位Under world宇宙军的队员。我对那张精悍的长相有印象——是送我从圣托利亚到森林宅邸的拉吉・昆特二级操士。他靠在书架上勉强地直着身子，右肩有相当重的伤，而且还被有毒的米尼翁的血淋到了。艾欧莱恩大概是为了保护无法行动的拉吉才孤军奋战的吧。

不能让他的努力白费，只要使用光元素术式，米尼翁的毒之类的五秒就可以净化，但托科伽・伊斯塔尔可不是能轻松应对的对手。不单是因为他能与艾欧莱恩势均力敌地使用军刀的能力，更可怕的是他右腰上的黑色手枪所释放的武装完全支配术。如果他使用了巨大的「心意无效化空间」，我的战斗力会减少五成，不，会减少七成。

理所当然的，在无效化空间内伊斯塔尔也无法用心意这点是对等的，但现在的我能否在纯粹的剑技和术式上赢过Under world的武人呢？

简直就像是看穿了我那不能算是恐惧、一瞬间的担忧。

伊斯塔尔的红唇边的笑意又加深了。

「我还以为你不是出现在基地就是中央大圣堂……没想到选择了这里吗？」

随着分辨不出性别的沙哑美声。长睫毛下浅蓝的双眼向这里投来了仿佛体温都会下降的寒冷光芒。

现在是现实时间十月三日的晚上十一点四十分左右。伊斯塔尔在伴星阿多米娜消失时已经是下午四点之后了。也就是说，从那之后只过了七个半小时。不敢相信在这么短的时间里就完成了四架大型机龙的整备，并从阿多米纳斯飞到了卡尔迪纳。他们恐怕早在很久之前就做好了卡尔迪纳的进攻计划，我和艾欧莱恩将基地和一架机龙无力化只是导火索大概是不会错的。

感觉艾欧莱恩想要说些什么的样子，我往抱着他肩膀的左手稍微注入了一些力气，回答伊斯塔尔。

「中央大圣堂有比我更强的骑士守护哦，你才是，不去那边好吗？现在，威斯达拉斯六世还是七世的机龙已经坠毁了也不是不可能的哦」

我一半是谎言，一半是认真地说着，但伊斯塔尔的脸色一点也没有变，只是浮现浅笑。

「即使如此，也与我无关。不过那大概是不会发生的呦……中央大圣堂那里只要有一架アーヴス级机龙坠落的话，圣托利亚市区就会变成火海。」

「也就是说，意图是将市民当作人质使用吗。这可不是自称皇帝的人该做的事呐。」

这次我以为他多少会被激怒，但浮现在白面上的微笑一点也没有动摇。

「不管是皇帝家还是贵族家，与高洁无缘这点应该还是知道的吧。如果你真的是星王桐人再临的话。」

「……为什么那么想？」

我想着应该没在这家伙面前说过名字，但伊斯塔尔泰然地回答道：

「在阿德米那召唤的女骑士们，不是将你称为桐人吗？」

「……原来如此，呢。」

说起来的话，在伊斯塔尔和艾欧莱恩对峙的咫尺处，确实有亚丝娜和爱丽丝叫我名字的记忆。但是，即使如此——

「星王在三十年前就从Under world消失了，一般来说，别人应该只会认为是名字一样的人而已。」

「一般来说是这样。但是，看见那种把人当成笨蛋的心意强度的话，或许……就会这么想。」

我迅速地看了一眼正在说话的伊斯塔尔的右手。

想要发动心意无效化的武装完全支配术的话，必须将黑色手枪从右腰的枪套里拔出来，摆好姿势，说出「enhance armament」。不论再怎么快，应该都得花三秒，还是我这边用心意将伊斯塔尔拘束起来比较快。

但如果有万一，心意被封锁的话。我就只能跟伊斯塔尔用剑战斗。

「……你们的目的是什么，真的认为只用四架机龙就能制压整合机士团和宇宙军还有地面军吗？」

我用低沉的声音质问，但伊斯塔尔的微笑没有消失。

「至少皇帝是这么打算的。实际上，占领中央大圣堂的所有楼层、将星界统一会议赶出去的话，现在的支配体制会从根本上产生动摇。因为那座塔是权威的象征……星王桐人最大的失败就是没有把大圣堂破坏掉。」

如此断言的丽人，用冰蓝色的双眸向我刺过来。

现在的我没有星王时代的记忆，我……不，他（星王）没有将大圣堂破坏的真正理由我并不清楚。但是可以想象。大概是因为充满了回忆吧。不论是和尤吉欧一起走的大阶梯、还是和他用剑认真交锋的第九十九层、亦或是他的血染红的最上层，将这些消去，无论如何也做不到吧……

我的视线一瞬间落在手臂中的艾欧莱茵身上。他不知道什么时候失去了意识，面具底下的双眼已经闭上。

甩开胸中刹那的想念，我反驳伊斯塔尔：

「那个自称皇帝从一开始就没想过占领大圣堂，他可是抱着将大圣堂变为空地的势头用导弹攻击啊。」

「导弹……是说热素喷进弹吗？我也呈报过至少不用心意弹头而用通常弹头，但皇帝很害怕古代的整合骑士团复活呢。有即使会招致圣托利亚市民的反感也要将九十五层以上消去的打算呢。」

我目不转睛地凝视着呀嘞呀嘞耸着肩的伊斯塔尔。

过去的整合骑士们和飞龙，以石化冻结的状态被封印在大圣堂的最上层，皇帝到底是怎么知道的。

还有，托科伽・伊斯塔尔为什么会毫不吝惜地说明对皇帝而言的最大级机密情报——

拖延时间吗？但为了什么拖延？不管Minion再怎么强力，只凭一架机龙运输的数量就完全制压宇宙军基地应该是不可能的。

皇帝阿格马尔・威斯达尔斯6世率领的奇袭部队，目标首先是破坏被封印的整合骑士所在的大圣堂上层，再来是绑架或者杀害整合机士团长艾欧莱恩来使全军的指挥命令系统混乱——我是这么想的。但是守护大圣堂的是不论攻守都相当卓越的爱丽丝 Synthesis Thirty，还有从漫长的睡眠中醒来的法那提欧・Synthesis・Two，她们两个相加的话应该不会轻易被破坏，对艾欧莱恩的绑架虽然一度很危险，但已经像这样阻止了。

在奇袭已经失败的前提上，拖延时间只会让状况变得不利。在阿德米那爽快地宣布逃走的伊斯塔尔，应该不可能不理解这一点。也就是说即使在这种状况下，他依然有胜算。

在转移到基地之前，我尽可能地把情报传达给刚醒过来的法那提欧，然后跟她约好「我会在零点之前回来」。还有二十分钟左右的余裕，但我不认为继续对峙下去是好办法。另一方面，伊斯塔尔也有等着我行动的可能性。

是要现在马上用心意拘束他，还是继续对话等待增援呢。

Unital ring的世界里，为了救出被兽人绑架的结衣，我毫不犹豫地挥剑了。明明那之后才过了不到一小时——明明状况也有某种程度的相似，胸口深处的犹豫却怎么样都无法消除。

注视着沉默的我，伊斯塔尔稍微眯起眼睛，开口表示：

「你大概，星王不是那样的人吧。」

「……为什么，那么认为？」

我刚一勉强回应，对方就露出特别冰冷的笑容。

「因为你少了传说中星王所怀有的苛烈……而且，你不理解皇帝之血的继承者们的无情。」

这些话就像是某种暗号。

突然间，伊斯塔尔背后的夜景被纯白的闪光涂满，接着窗户的玻璃哔哩哔哩地震动了起来。

「……！」

我屏住呼吸，凝视着光芒消失后的窗户。

正面偏左，也就是东南偏南的夜空中，染上了淡红色。再仔细一看，远方央都圣托利亚方向升起的火焰，即使距离十公里以上也能清楚目视。

火焰的源头不是圣托利亚的市区，而是耸立在街道中央的白色高塔最上部。

中央大圣堂正在燃烧。

** 2

对于整合骑士爱丽丝 Synthesis Thirty来说，贝尔库利 Synthesis One是敬爱的师父，也是像父亲一样仰慕的存在，但爱丽丝对于副骑士长法那提欧・Synthesis・Two正直的地方，比起尊敬的念头还是不擅长对付的心态更大一些。在中央大圣堂生活的时候，甚至觉得她是所有的骑士和修道士中最合不来的对手。

但是和暗黑界的战争开始后，在东大门的共同战斗中，爱丽丝知道了法那提欧的高尚与深情。在使用完「反射凝集光线术」，力气彻底消耗完后，把从雨缘的鞍上滑落的爱丽丝接住的法那提欧所说的话，还依然在耳边回荡。

——漂亮的术式，还有心意哟，爱丽丝。

——敌人撤退了，这是你引导的胜利哟。

在那之后，爱丽丝作为诱饵部队的一员突入了暗黑界，也没有和留下来防卫人界的法那提欧交谈的机会，就这样通过终结祭坛从Under world里脱离了。再次回到Under world时已经过去了两百年，与法那提欧和其他的骑士们再会已经是没办法实现的事了，虽然一直这么告诉自己，但是——

「……法那提欧阁下。」

爱丽丝一边用沙哑的声音再次呼唤着那个名字，一边拼命睁开渗出眼泪的双眼。

比乘坐飞行盘的爱丽丝和艾尔莉所在的10Mel还要高的中央大圣堂的百层，用奢华的银色栅栏围起来的露天阳台上。

在阳台上站着的高挑女性骑士，爱丽丝是不会看错的。在夜风中波动起伏的黑发，淡紫色的铠甲和紫罗兰色的披风、还有如同西洋剑一样细的长剑。整合骑士第二位，法那提欧・Synthesis・Two就在那里。

在大圣堂的九十九层，让与十五位整合骑士一起石化冻结的她觉醒的，一定是桐人。桐人在见到法那提欧之后就打开了「门」、「我回来的话就会让那些家伙强制着陆，在我回来之前坚持住」留下话之后就移动到了宇宙军基地。

在大圣堂西侧的天空中，三机大型机龙的黑压压的巨大身躯停了下来。仅仅数十秒前一起发射的十八枚导弹，全部被桐人的心意防壁击坠了，但大概并不是因为剩余的导弹用尽了才决定停下来。

坐在中央机龙里的那个自称是皇帝阿格马尔・威斯达尔斯6世的男人，目的恐怕是歼灭被封印在九十九层的骑士们。虽然他说过如果打开大圣堂所有的防御活动遮板并表现出投降的意思就停止攻击，但这些话不能全盘接受。也存在打开活动遮板的瞬间，剩下的导弹就全部打进来的可能性……不对，首先一定会这么做。

就算「非法占据者」摆出彻底抵抗的姿势，皇帝应该也装载了能摧毁活动遮板与大圣堂最上部的导弹。但是刚才大方地一起射出的十八发导弹却一发都没有碰到大圣堂，这应该是意料之外的事。机龙的下部发射装置没有装载新导弹的动作，保持着沉默。

皇帝就算想再次用言语威胁，中央机龙装备的 立体影像投射用圆盘 也被法那提欧用神器「天穿剑」的光破坏了。如果不能沟通的话，不论是交涉还是胁迫都不可能成功，皇帝剩余的选项只有总攻击与撤退两个，但他无法立刻决定要选择哪一个。

考虑到两三分钟内还是继续这样的胶着状态，爱丽丝将金木樨之剑收入剑鞘后就立刻对站在后面的艾尔莉低声说道：

「艾尔莉，能上升到法那提欧殿下在的地方吗？」

「好的。」

点头回应的艾尔莉增加了飞行盘下部喷出的空气流量。钢铁圆盘以百层为目标强力上升着。

过去的中央大圣堂因为有最高祭司Administrator布下的数重妨碍术式，别说飞龙了，就连鸟也无法靠近上层。但妨碍术式在这两百年间被谁解除了吧，如果那个术式还有效的话，说不定即使是导弹攻击也能防御下来。

爱丽丝甩开刹那的念头的同时，飞行盘跨越了阳台的栅栏。

连降落都等不及就跳了下来，在白晃晃的大理石瓷砖上踏出高亢的脚步声，向着曾经的朋辈跑去。

青白色星光照耀着的法那提欧的脸，爱丽丝刚一看到法那提欧浮现出和东大门紧紧抱住的时候别无二致的笑容的时候，就感到胸口一下子热了起来。

爱丽丝停下脚步，压抑住想要就这样张开双臂飞扑过去的心情，用微微颤抖的声音说到：

「好久不见了，法那提欧殿下」

右手放在机士团制服的前方，左手放在剑柄上行礼的时候——

「真的是好久不见了呐，爱丽丝」

法那提欧一边这么说，一边伸出双手抓住爱丽丝的肩膀拉了过来。将双手放在向前摔倒的爱丽丝的背后，用铠甲发出摩擦声的程度的力量抱住爱丽丝。

仔细一想，主观时间上爱丽丝和法那提欧在东大门分别之后过了三个月，但据艾尔莉所说，法那提欧希望石化冻结的时候是人界历475年，也就是对于法那提欧来说其实是相隔九十五年的重逢。

爱丽丝也抱住法那提欧的身体，确实地注入力气，如果再次相见的话，绝对要亲口说出认为必须传达的话语。

「……法那提欧阁下，真的很抱歉。贝尔库利阁下为了帮助被皇帝贝库达绑架的我而……」

「爱丽丝。」

以温和而坚定的声音打断爱丽丝的话，法那提欧轻轻放开爱丽丝的身体。略带金色的褐色眼睛从近处窥视爱丽丝的眼睛，继续说道：

「我知道哟，你和阁下都是为了保护Under world而做了应该做的事。现在必须继承阁下和艾尔多利耶、达基拉……以及在那场战争中失去生命的勇敢的人界与暗黑界士兵们的遗志，面对新的敌人。」

「……好的。」

拼命压下即将从胸口溢出的热度，爱丽丝点了点头。无论如何也要守护大圣堂——这就是两人被赋予的使命。

「法那提欧阁下，了解状……」

爱丽丝的问题在中途被法那提欧打断了。

「嗯，从星王陛下……从桐人那里听说了许多事情哦。原本打算亲眼见证最后的黑皇帝被讨伐，作为他们灵魂替身的宝石被破坏……到底是怎么复活的……」

「……」

爱丽丝没有经历过异界战争后爆发的「四帝国大乱」以及更后面的「黑皇战争」。但是，在公理教会统治的圣托利亚市域统括骑士就任的时候，早就看腻了皇帝家的放纵与骄傲。皇帝在某种程度上是超过最高祭司Administrator的欲望化身，即使变成怪物也要得到Under world的支配权也并不令人惊讶。

假设阿格马尔用某种手段复活了黑皇帝，并继承了「前世」记忆的话，憎恨与恐惧曾经将自己杀死的整合骑士团是当然的吧。

针对大圣堂的导弹攻击开始的时候，赛尔卡完成了五瓶解冻药。即使其中的一瓶给法那提欧用了，也还剩下四瓶，这么想着的爱丽丝急忙提出建议。

「法那提欧阁下，我认为皇帝阿格马尔最优先的目标是歼灭被封印的整合骑士团。即使全员解冻是不可能的，但趁现在让其他的骑士们觉醒不是应该的吗？」

「是呢……但是……」

稍微停顿一下之后，法那提欧继续说道：

「如果敌方的高位术士使用心念的话，即使隔着中央大圣堂的墙也应该能探查到骑士团的觉醒。知道觉醒正在进行的皇帝，不否定会做出先下手为强的暴行。」

「暴行……也就是说，皇帝还有比心意导弹……比喷进弹还要高威力的攻击手段吗？」

对哑然的爱丽丝轻轻点了点头，过去的副骑士长的视线投向了三架机龙。

「……我所知道的黑皇帝们，在挑起战斗时一定会有杀手锏，并且还会准备进一步的杀手锏。虽然也不是不能说他们是战略家，但归根结底这就是他们的习性哟。而且皇帝们被看起来只是个小鬼的桐人所率领的人界统一会议给打败了，这成了他们绝对无法治愈的旧伤吧。」

「原来如此……」

爱丽丝也点头，将视线移到了西方的天空中。

明明之前的导弹攻击已经经过了三分钟以上的时间，机龙仍保持着令人害怕的沉默。

因为不能让它们坠落到市区，所以这边也不能出手，但桐人从基地回来的话，就会让它们强制着陆到大圣堂的前院。虽然不是马上就能相信用心念之手移动那么巨大的物体，但他既然说能办到就一定办得到吧。

在ALO和UR的世界……不对，即使是在Under world，也不想在剑和术式的能力上落后，但关于心意力有了压倒性的差别。虽然有些令人生气，但状况平静下来得拜托修炼心意呢——

在不经意间思考多余的事情的爱丽丝耳边，传来了静静的脚步声。接着是平静但带有隐隐真情的声音。

「法那提欧大人，好久不见」

法那提欧回过头，一下子绽开了脸并迈了一步。

副骑士长面对在前面行礼的艾尔莉，为了不让自己的铠甲将她弄伤而温柔的抱住，低语道：

「你也很有精神真是太好了，艾尔莉」

「非常抱歉。变成了法那提欧大人不得不醒来的这种状况……」

「不要道歉。真的应该谢罪的，应该是明知你会变成一个人管理封印阶层，却还是交给你的深度冻结的我才对。」

打断艾尔莉的话后，法那提欧松开了拥抱。向爱丽丝那边送去一瞬间的视线后，用变得截然不同的紧张声音干脆地下达指示。

「皇帝阿格马尔现在，应该犹豫到底是在这里使出绝招，或者是期待撤退后卷土重来。我们的职责就是在桐人回来之前延长皇帝的犹豫……然后是，紧急的时候将被害降到最小哟。艾尔莉，请你回到九十五层，帮助赛鲁卡。」

「了解了。」

立刻点头的同时，艾尔莉就回去了。当爱丽丝想着要怎么回到大圣堂里面时，露天阳台的一角打开一个四边形的洞穴，深处似乎有通往下面的楼梯。

「法那提欧小姐，那个楼梯是……？」

过去的中央圣堂应该没有这样的出入口才对，爱丽丝边想边这么问，副骑士长微微皱起眉头回答：

「你可能也知道，元老长丘德尔金在从九十六层到九十九层的墙壁里建造了相连的隐藏楼梯哟。在将过去的长老院改装为飞龙的睡房时，对于如何处置那个楼梯产生了意见分歧……最后桐人说：存在的东西就要有效利用，于是亚丝娜的地形操作就把楼梯连接到屋顶了。」

「……是这样啊。」

关于隐藏楼梯的事情，爱丽丝也有清晰的记忆。追赶逃跑的元老长丘德尔金，和桐人一起跑上去仿佛还是不久前的事。

如果是成为星王的桐人希望将楼梯保存下来的话，是因为想起了再也见不到的爱丽丝还有尤吉欧才这么做的吗？因为现在的桐人已经不可逆地失去了星王时代的记忆，所以应该无法确认了。

目送完跑下楼梯的艾尔莉后，爱丽丝又问出新的问题：

「赛鲁卡在做什么呢？」

「正在用现有材料制作解冻药。」

虽然回答很简洁，但副骑士长的侧脸却隐约带着忧郁的神色。

果然正如法那提欧所想，皇帝比起撤退，还是选择总攻击的可能性比较高。如果让骑士按顺序觉醒，就有被敌人探测到而发动总攻击的危险。所以在战况陷入胶着的期间，要制作能让所有骑士和飞龙同时觉醒的解冻药，打算在看见敌人要使用杀手锏的时候就立刻使用吧。

当爱丽丝这么思考时，又浮现新的问题，于是她第三次对法那提欧问道：

「法那提欧小姐。桐人……不对，星王为什么要将深度冻结的解冻术式与解冻药藏在阿德米娜呢？如果是为了安全，那么考虑到像这次的紧急事态应对性的话，放在大圣堂不是更好吗……」

十个小时前，爱丽丝在九十层的大浴场里，对亚丝娜问过完全相同的问题。但是和桐人一样，失去作为星王妃记忆的亚丝娜只是微微歪起头。注意到艾尔莉的话一定知道理由的时候已经太迟了，但这么说来，法那提欧应该也知道才对。

果然，副骑士长用不知为何有些复杂的表情看了爱丽丝一眼。

「……嗯，这是理所当然的疑问呢。我也曾问过桐人一样的问题。」

「那么，他说了什么……？」

「他说，那么简单就能得到的话不是很无聊吗。」

「……」

确信自己和法那提欧露出了一样的表情后，爱丽丝就点头了。虽然没有和星王本人面对面过，但桐人就是桐人，就是这么回事吧。虽然也有在像是迷惑人的话语背后藏着某些深意的可能性，但现在也不是进行长时间考察的状况。

应该是考虑到同样的事情了吧，副骑士长快速摇了摇头，同时开口表示：

「现在先把精力集中在眼前的敌人身上吧。虽然这么说，但我们这边也不能发动攻击就是了。」

「是这样呢。」

点头的爱丽丝注视着机龙的编队。虽然还没有动作，但那是因为正在选择下一步该怎么走呢，或者是正在推测时机呢。

「天穿剑的激光……不对，武装完全支配术还能射击多少次？」

爱丽丝望向机龙如此问的同时，感觉到法那提欧抬起了头。

「因为是夜晚，所以还能射击四次吧。」

「四次……吗？」

爱丽丝也抬头望向如同烟熏一般的天空。

武装完全支配术的每次发动都会大幅损耗神器的天命，只有在空间神圣力丰富的场所才能回复。在回复的时候，每个神器对神圣力的供应源也有不同的相性，前世是世界上最古老的树的金木樨之剑喜欢阳光与草木繁盛之地，艾尔多利耶说过，由栖息在湖中的神兽化成的霜鳞鞭喜欢清净的水。

法那提欧的天穿剑是最高司祭Administrator在过去试做的，前世是用一千面镜子将阳光反射集中到一点、从而生成超高温火焰的兵器。在现实世界也存在与其结构相似的叫做「定日镜型太阳炉」的发电装置，但不知道最高司祭是否知道那个。

总之，天穿剑因为那样的出身，在所有的神器中是最喜欢太阳光的，骑士团时代也曾听说过天穿剑在夜晚的天命回复速度是肉眼可见的下降。

看着一半被云覆盖的天空，爱丽丝说到：

「我的剑还能防下十二发喷进弹。但如果皇帝的杀手锏是一起发射超过十二发的喷进弹的话，可能要让法那提欧殿下……」

——击坠一架机龙。

将这样的话和冰冷的空气一起吞下。

失去在正下方的第九十九层沉睡的十五位整合骑士是绝对不能接受的。但是，击坠一架机龙的话，圣托利亚市民的牺牲人数绝对不止十五人吧。如果是打破「右眼的封印」之前的爱丽丝，应该会因为感性和义务的两头为难而受到强烈痛楚的侵扰吧。

想着法那提欧会怎么样的爱丽丝，快速地看了一眼法那提欧。

从表面上看，虽然分辨不出来有没有封印，但法那提欧像是完全看穿了爱丽丝的担忧似的，点头说道：

「不能让机龙坠落到市区。如果那么做的话，就算守护住了大圣堂也是我们的失败——放心吧，你防不下的喷进弹就由我来全部击坠。」

「但是……」

天穿剑的武装完全支配术和ALO的光属性魔法「穿刺光」一样，都是特化贯通力的激光攻击。将呈现面状攻击的导弹群作为对手的话，因为发动一次只能破坏一发导弹，所以效率低下。

但法那提欧也深知这点才对。在此之上还说出「交给我」，单纯只是信任曾经并肩作战的朋辈吧。

「好的，后面的戒备就拜托了。」

「了解了，你也是，不要再勉强自己了。」

「不……」

爱丽丝摇了摇头，正想告诉法那提欧这是骑士的职责的时候，爱丽丝的耳朵捕捉到了细微的机械音。

像是被弹了脸一样，爱丽丝把脸转了回来。从滞空的机龙机翼下方的爆弹仓内，新的导弹一个接一个的伸了出来。看来皇帝阿格马尔似乎是选择了孤注一掷。

法那提欧一边将天穿剑的剑鞘放到左手上，一边说：

「像那样彻底使用喷进弹的话，如果防御下来那就是我们的胜利……如果没有的话就是他们的胜利了。」

「嗯。」

爱丽丝突然注意到什么，于是语速很快的问：

「法那提欧殿下，我们怎么联络赛尔卡她们……？」

不知不觉间忘记了在Under world里只能靠声音和书信联络，无论在大圣堂外面的爱丽丝发出多么大的声音……即使使用扩声术，也无法传达给在塔内工作的赛尔卡和艾尔莉吧。即使有解冻骑士的必要，现在赶去的话会赶不上吗？

但法那提欧明明刚从近百年的沉睡中觉醒，似乎也一直在毫不疏忽地思考。

「我下达了『大圣堂再被一发喷进弹打中的话，在那时就立刻中止制作解冻药，并开始将骑士们解冻』的指示哟。」

原来如此，但点头的爱丽丝又因为新的疑问而轻轻吸了一口气。

「……解冻的顺序是按照……？」

「从编号靠后的骑士开始哟。」

爱丽丝一瞬间凝视了立刻回答的法那提欧的脸。在第九十九层被封印的整合骑士中，编号最靠后的是和爱丽丝完全不同的菲洁尔 Synthesis twenty-nine。如果从她开始解冻的话，有可能会轮不到在两百年内陪伴法那提欧的迪索尔巴德 Synthesis Seven，以及爱丽丝连名字都不知道的「古代七骑士」们。

但是，如果去确认迪索尔巴德的想法的话，果然还是希望从年龄小的骑士开始避难吧。

点头的爱丽丝将视线移回到机龙身上。

一架机龙上挂着六发导弹，三架总共十八发。果然是准备用最大火力来一决胜负。确认这一点的爱丽丝握住了爱剑的剑柄。

金木樨之剑的天命还剩下八成左右，但心意导弹会因为「覆写效果」，爆炸的威力会变得越来越大。正如自己刚才所说的，同时挡下十二发已经是极限了。剩下来的六发只能拜托法那提欧用仅剩的四发激光去击落了。

发出沉重的声音，最后的导弹已经悬挂在发射装置上了。

同一时间，爱丽丝和法那提欧各自拔出自己的剑。

「enhance armament！」

首先，爱丽丝发动了武装完全支配术。金木樨之剑发出金色光芒，在光芒中，剑身份解成数百枚花瓣。

宽度不满1cen的花瓣，初期状态是像金木樨的花一样，有着圆边的十字型。用现实世界的游戏风格来说的话，就是攻击力50、防御力50的平衡型，但这个形态不适合迎击心意导弹。

爱丽丝集中意识的同时，摇荡在空中的所有花瓣就发出清脆的声音变形了。十字形的前端变得尖锐，成为攻击力90的形态。

这个时候，在中央机龙的司令室里，皇帝阿格马尔应该高举着右手吧。

明明应该听不见，但耳朵深处却隐隐约约听见了「发射！」的怒吼——在这一瞬间，爱丽丝将右手中仅剩的剑柄大大地挥动。

发出「嚓！」一声的花瓣集群往左右扩展。

接着十八发导弹一起发射了。轰响着让人联想到怪物咆哮的异样声音，导弹朝着大圣堂外壁的一点涌去。

突然间，爱丽丝的脑里闪过些许的违和感。但是没有迷惑的时间了。花瓣集群分成四个小组，各自朝着目标全力投射。

在之前的攻防中，破坏心意导弹的花瓣集群被卷进爆炸里受到了较大的损伤。因此这次不是以盾的阵型去挡住导弹，而是以枪的阵型去瞬时贯穿的作战。

化为黄金投枪而突进的花瓣集群，和先锋的导弹交错。虽然看起来像是没有任何反应就穿过去了，但被锐利的花瓣刺穿外皮的导弹都摇摇晃晃地打乱了姿势，然后一个接一个地爆炸了。虽然爆炸时花瓣集群已经飞走了，但还是没有完全回避狂暴的火焰，被卷入的花瓣啪啦啪啦地掉了下去。

爱丽丝一边感受着爱剑的痛苦，一边将幸存的花瓣集群重新制成新的投枪，继续迎击导弹。七发、八发、九发……十发。距离和法那提欧约定好的十二发还有两发。

「喝啊！」

发出裂帛般呐喊的同时，将右手用力挥下。飞行的两根投枪描绘出黄金的轨迹。

抓住了——刚这么想的瞬间。

两发导弹如同生物一般扭动着身体，回避了投枪的攻击。

爱丽丝虽然感到惊愕，但还是在无意识中改变了花瓣集群的阵型。细长的投枪变形成拥有巨大翅膀的鸟，变形的花瓣集群急速改变路线，继续追赶导弹。两个翅膀的巨鸟瞬间拉近距离，想要用锐利的喙突刺，但在这个时候，两发导弹分别往右往左闪身。

依靠密封的热素来飞行的喷进弹，应该做不到像那样的动作。那恐怕是击坠桐人和艾欧莱恩所搭乘的泽凡十三型的诱导弹——将神兽刚生下来的孩子改造而来的生体导弹。

仔细一看之下，和已经击落的喷进弹不一样，生体导弹没有金属外皮，而是覆盖着发黑的鳞片。这就是之前感到不对劲的原因吧。

如果早点注意到的话，但没有如此后悔的余裕。不用说在花朵集群下四处逃窜的两发，看样子从左右逼近的六发也是生体导弹。旁边的法那提欧虽然没有动摇的气息，但比一般的喷进弹更难瞄准这点是确实的，因此，无论如何也至少要击坠眼前的两发。

爱丽丝一边用右手操控花瓣，一边将左手向前伸出，尽可能地竭尽了自己的心意力。爱丽丝的「心意之手」是骑士长贝尔库利直传的本领。即使出力不及桐人，但如果是精密的话并没有输的打算。

没有错过两发生体导弹接近到1Mel以下的距离的那一瞬间，爱丽丝以一下子紧紧抓住的印象快速握住左手。

据桐人所说，在阿德米娜的基地生产的生体导弹，似乎同时具备作为飞行型生物的机动力与侵蚀破坏心意防壁的力量。爱丽丝猛然放出的心意之手虽然确实捉住了导弹，但左手却有种又黏又滑的感觉。

即使如此，两发导弹也确实有一瞬间的迟钝。

不能错失这个机会，爱丽丝将右手狠狠地向下甩。

两个翅膀的巨鸟突然急速下降，用鸟喙将生体导弹贯穿。导弹激烈地扭动身体之后，四散出了漆黑的火焰。不是热素，而是暗素的解放现象（burst）——虽然金木樨之剑的暗耐性比火耐性要高，但即使如此被卷入爆炸中心的花瓣集群也不可能平安无事。失去光辉、变成黑色的花瓣如同雨一样落下。

爱丽丝一边将残余的花瓣往手中召回，一边大喊：

「法那提欧小姐——剩下来的拜托了！」

「了解！！」

作为替换，向前迈步的法那提欧从左腰噌地拔出天穿剑。

剩下来的六发生体导弹，以三发为一队从左右两边袭击过来了。虽然认为用仅剩的四发激光将横向扩展的导弹全部击坠是不可能的，但法那提欧用完全没有迷惘的动作将剑挥下，大喊：

「Release recollection！」

不是武装完全支配术。而是整合骑士的最大奥义，记忆解放术——

「磅！」厚重的震动声响彻云霄，天穿剑的剑身迸发出纯白的辉线。不是激光，而是长达50Mel左右的光之剑。

这个技能，爱丽丝也只远远地见过一次。异界战争初期，在能眺望东大门的峡谷中展开的与暗黑界军的攻防战中，法那提欧曾经将巨人族族长西古罗西古给一刀两断。但在那时，剑长只有10Mel左右，而如今法那提欧手中升起的光芒，是那时的五倍还多。这已经不能称之为剑，而是柱子……如果是桐人的话，大概会命名为激光之柱（laser pillar）吧。

空气再次振动了起来。

描绘着如同纯白色极光的轨迹，光之柱先是向左倒，接着向斜后方拉。

「喝啊啊啊啊！」

发出激烈的吼声后向前踏出一步，法那提欧向前挥出了光之柱。

逼近到30Mel内的生体导弹，因为对强烈的光产生反应而采取了回避行动。如果只是直线贯穿的光线的话还说不定可以回避，但扩大成面的激光将空间横扫一通后，左侧的三发依序被光之轨迹给吞没，无声地被分割开来。

刹那之后，立刻连续爆炸。被释放的大量暗素在夜空中穿出了漆黑的洞。产生的虚无引发了逆向的爆风，似乎想要吸入世间所有东西。

爱丽丝一边立刻站稳双脚，一边将爱剑换到左手，用空出来的右手抓住了法那提欧的剑带。

「谢谢！」

副骑士长一边喊着，一边将光之柱进一步挥出，狙击目标是右侧的三发。生体导弹们，在空中飞出了像飞虫一样不规则的轨迹，想要钻进超高温斩击的空子里。

但法那提欧用无比精密的手法让光之轨迹上下波动，被熔断的第四发和第五发几乎同时爆炸了。爱丽丝再次低下腰来承受刮起的爆风。

第六发——不，从一起攻击的时候开始算的话是第十八发的生体导弹，仿佛知道自己是残余的最后一个似的，开始了乱七八糟的到处飞行，但无法从分量几乎消失的光之柱下逃脱，终于，生体导弹和光之柱接触了。沐浴在纯白之光下的漆黑鳞甲，瞬间蒸发了——

但在那时，光剑像星星一样忽闪了起来，最终消失了。

最后的生体导弹即使消失了一半也没有爆炸，笔直地朝着大圣堂突入了。不管是爱丽丝的金木樨之剑还是法那提欧的天穿剑，都已经到了天命的极限，如果再次使用武装完全支配术的话，不知道还能不能承受一次斩击。

这时。

在两人的背后，淡淡乳白色的光辉轻轻地蔓延开来了。

光芒变成了极薄的膜并不断扩大，将站到最后的爱丽丝和法那提欧给吞入。别说冲击了，就连被什么东西触碰的感觉都没有，只是全身的肌肤隐隐地被温暖拂过。

光之膜用不到一秒的时间变成了巨大的球体，将大圣堂的最上部包入。

紧接着，生体导弹猛地撞上了膜，扩散出透明的波纹后停了下来。此时距离第九十九层的外壁仅有2Mel。

是冲击的缘故吧，已经破破烂烂的躯体发出「baki」的声音后就折成了两半。从折断的地方喷出了黑紫色的能量——爆炸。

爱丽丝她们反射性地背过头去，但光之膜也将暗素的爆发给防御了。但那就到达极限了吧，光之膜就像溶入到空气里似的消失了。

「……刚才的是，法那提欧小姐做的……？」

爱丽丝用嘶哑的声音询问，但法那提欧摇了摇头。

「不……我还以为是你的心意……」

面面相觑后，两人一齐回头。然后，同时强烈地咽了一口气。

中央大圣堂的最上层，在广大露天阳台的中央镇坐的圆形堂的圆形屋顶正在微弱地发着光。眼看着光变得稀薄，最后消失了。这不可能是错觉。

那个圆形堂曾经是最高司祭Administrator的寝室。在那里，爱丽丝、桐人和尤吉欧，以及贤者Cardinal一起与Administrator战斗过。

圆形屋顶的内侧里，有以Under world的创世神话为主题的天花板壁画，在那之中埋藏着像星星一样闪耀的水晶。但那不只是宝石，而是最高祭司用「整合秘技」，从成为整合骑士的人的摇光中抽出的结晶体——爱丽丝就这么呆立着，因为无止尽的思考而徬徨。

因此，当她注意到时已经太迟了。

空气再次哔哩哔哩地震动。这已经不是暗素，而是热素的咆哮。

法那提欧再次摩擦着肩头往后看去。深红的火焰发出轰鸣声燃烧着，而解放（burst）现象的残渣则是在其后方摇晃着。

从爱丽丝的角度来看，火焰的发生源是在右侧滞空的大型机龙。厚厚的主翼后部内藏的，共计六座热素引擎正在全力驱动着。

是看不见胜算，打算将部下作为盾而逃走吗……虽然有一瞬间这么想，但皇帝阿格马尔应该在中央的机龙才对。那么，难道是右边机龙乘员的独断逃亡……？

不对，那是不可能的。Under world的居民，即使是公理教会结束统治的两百年后，人工摇光也被「绝对不能违反上位存在」的旧疾所困。也就是说机龙的全力驱动是皇帝的命令，而机龙瞄准的是——

「糟糕……它打算撞进大圣堂里！」

爱丽丝大喊的同时，旁边的法那提欧身体猛然一震。

「怎么可能！」

即使发出沙哑的声音，法那提欧也将左手向前伸出，爱丽丝也将自己的右手重叠上去。

gooo！轰鸣着沉重的喷射音，大型机龙开始动了。一旦开始加速，黑色巨躯就急速地增加了速度，像是山崩地裂的暴威就直线突进了。

阿普斯级机龙全长20Mel，翼展达到了40Mel。总重量虽然没有头绪，但最可怕的是，即使再少也至少超过十人的乘员还在上面。皇帝下达了让他们全员赴死的命令。

无情而冷静透彻的判断。皇帝让机龙突击的原因，不只是因为导弹用完了。大圣堂外壁被赋予了最大等级的优先度，本来的话，即使大型机龙猛撞也会平安无事吧——所以机龙才搭载了心意导弹——但它的保护也不完美。

即使是没有习得心念的人类，如果在临死前感受到恐惧与绝望的话，也会产生强烈的心念力。就像在东大门之战的时候，濒死的巨人族族长西古罗西古被法那提欧束缚住的时候一样。阿格马尔6世打算将机龙的乘员们代替成心意兵器吧。

爱丽丝也是，如果下界是无人的荒野的话，也说不定会为了守护大圣堂和骑士们而将机龙击坠。因此也没有提出像圣人一样的主张的资格，但尽管如此也绝对不能容忍那种把部下当成一次性用品的司令官。

将从心底里涌出的愤怒当作力量，爱丽丝再次尽可能的竭尽了自己的心意力。

从和法那提欧重叠着的手中，也感觉传来了决然的波动。

两人展开的心念防壁，和突进的机龙的前端接触了。

连又重又硬的感觉都没有，心意防壁被粉碎了。

一秒后，机龙猛烈地撞上了第九十九层的外壁。机首的装甲板被撞破、开裂、接着四处飞散——在其中急速膨胀的大红色火焰，将爱丽丝的视界全部染成了红色。

** 3

「父亲，拜托了！送我到六本木！」

明日奈在脸前用力地双手合十，父亲——RECT集团（集团）会长、结城彰三将正在脱高尔夫夹克的手停了下来，右眉渗出困惑，左眉渗出担心的同时说道：

「六本木？在这个时间？明日奈，你……不是在玩什么奇妙的游戏吧？」

「不是啦！」

先是斩钉截铁地否定，然后突然陷入沉思。Under world的下位阶层是众多VRMMO和都是the seed构筑的世界构建的，从父亲的角度来看，Under world和game——和游戏是差不多的吧。但是在那个世界生活的人们，是和明日奈一样拥有灵魂的人类，为了潜行到Under world的Soul Translator（STL），是RECT也参与开发的NerveGear的直系子孙。

虽然那么说，但已经是深夜的十一点三十分了。高中生的女儿在这个时间说出「想要去繁华地区，用车送我」之类的话，大部分父母不是阻止就是生气吧。虽然想哪怕早一秒也要从家里出去，但不好好说明理由是不行的。

吸入玄关大厅冷飕飕的空气，明日奈说道：

「那个，我在拉斯……海洋资源探查所研究机构的六本木支部进行职场参观的事，父亲也知道的吧」

刚一说出拉斯的名字，彰三不愉快的表情一下子加深了。

「和那里有关吗……虽然我从你母亲那里听说了职场参观的事，但如果考虑在那里就职的话我是不赞同的哦。因为那个组织，让你和桐谷君遭受了不得了的事呐」

彰三表现出厌恶感也是没办法的事。明日奈与和人在今年七月，陷入了在Under world里维持潜行的昏睡状态，醒来时已经是大约一个月之后的事了。如果没有和人的双亲和明日奈的母亲京子的劝说的话，彰三一定会决心起诉拉斯的吧。

从那之后过了两个月的现在，彰三对拉斯的态度。虽然只有一点点，但正显示出软化的迹象。不只是因为亚丝娜不断重复着去Ocean Turtle是自己的想法，应该还有一个理由。也就是“A.L.I.C.E.”——爱丽丝。

从属于拉斯的她，是世界上第一个、恐怕也是唯一一个的“强AI”。不仅是制造业，教育和娱乐，以及行政服务都在大范围活用传统型AI的现在，全世界都对拉斯的说不定能从根本上变革产业和社会体系的技术投来了热烈的视线。当然RECT也不例外，但按照拉斯现在的责任者、凛子博士的指示，拉斯拒绝了所有取材和面谈的申请。

因此，由RECT的AI研究开发部门率领的「RECT DATA SCIENCE研究所（雷克特数据科学研究所RDSL）」，着眼于ALO的爱丽丝和明日奈的交友关系，似乎向彰三请示过能不能用那个关系联系上拉斯。明日奈不是从彰三本人而是从哥哥浩一郎那里听说的，虽然彰三当场就狠狠地拒绝了请求，但RDSL也不轻易退缩，又因为即使是彰三也认识到次世代AI关系到集团全体的浮沉，所以现在似乎陷入了左右为难的状态。

虽然要利用父亲两难的立场有些于心不安，但现在也没有说三道四的时间了。重视礼节的爱丽丝在这个时间联络说「需要桐人和亚丝娜的力量」，那么Under world一定发生了很大的紧急事态。

「……我知道父亲对拉斯抱有厌恶感，也知道这是没办法的事」

明日奈一边努力不要说得太快，一边说

「但是，那是因为父亲对拉斯的事……是什么样的组织、做什么样的研究不太清楚才会这么想的」

「嘛……这倒是没办法否定呢」

虽然像是很勉强的样子，但彰三还是点头了。明日奈也轻轻的点头，继续说明。

「那个呢……我现在，在拉斯帮忙调查Under world。因为，没有比我与和人君更熟悉那个世界的人了。」

「说起Under world的话，不是在那个研究船里构建的假想世界吗？说是存在数万和爱丽丝相同等级的AI……是不能马上就能相信的事呢……」

彰三的理解有90%是对的。现在，克服「不能做出违反规则和命令的思考」这一人工摇光脆弱性的真正的泛用人工智能（AGI）只有爱丽丝一人，除了她以外的Under world人都没有到达那个等级。虽然和艾欧莱恩、罗妮耶、缇洁、艾尔莉他们交流的时候，完全没有感觉到他们的思考被限制，但那是因为他们本来就不被那个世界的大部分规则和法律束缚吧。但即使有再多的时间也不够说明这些的，所以暂且肯定了。

「是这样的，Ocean Turtle被封锁的现在，AI们往现实世界移动是做不到的。但是……在那个Under world里，稍微发生了一些问题……」

「问题？又被奇怪的家伙袭击了吗？」

「不是不是，说到底还是假想世界的问题哦。因为事情变得错综复杂了起来，所以没办法简单的说明……刚才，从在Under world里潜行的爱丽丝那里，收到了希望去帮忙的联络」

「……姆……」

亚丝娜将视线从哼哼着的彰三脸上，转移到天然石制成的装饰墙里埋入的模拟时钟上。十一点三十五分……差不多是母亲也回来的时间了，那样的话，就要再重复说明一遍事态，绝对不能变成那种情况。

「拜托了，爸爸！爱丽丝是我重要的、重要的朋友！」

如果这样还不行的话就放弃……明日奈一边想着只能装作什么样子，勉强从家里溜出去，一边再次将双手合十。

彰三有着重视人的缘分的信条——虽然这个信条也被须乡伸之给利用了——从以前就对明日奈和浩一郎说「要好好珍惜朋友」，而且也不能无视身为集团全体的舵手RATH的要求吧。而且，明日奈猛然说出的「爸爸」似乎也有若干效果，彰三深深地叹了一口气后说道：

「已经半年没有亲自开车了呐，即使乘坐不舒服也不要抱怨啊」

「谢谢爸爸！」

明日奈道谢后，父亲将刚脱下来挂在衣架上的切斯特大衣穿上，明日奈自己也将萨克斯顿布料的P外套披在身上，将运动鞋穿上。

桐人在Unital Ring收到爱丽丝的救援请求是十一点二十五分。明日奈花了三分钟做好外出的准备，正要在携带终端的出租车配车app上叫车并冲下楼梯时，就正好碰上了打完高尔夫回来的父亲。

虽然花了七分钟说明并说服父亲，但在这个时间叫出租车的话绝对会花七分钟以上吧，（UW的问题）如果还没结束就好了……不，还什么都没有结束。总而言之，现在去六本木才是最重要的。

结城家的车库里，停着父亲的大型SUV、母亲的两厢车、还有哥哥的两座车。明日奈朝着还在微微散发着热量的SUV走去，但肩膀被背后的父亲抓住了。

「借用浩一郎的车哟。现在开全尺寸的车有点吃力」

「是吗，明明都这么累了，抱歉呢」

「今天只打9洞（half）所以没问题」

「得分呢？」

「别问了」

彰三轻轻笑着，同时按下了车钥匙的解锁按钮。

现在乘坐的纯油跑车虽然感觉有些硬，但正用令人兴奋的加速往世田谷飞驰，离开了246号线。

沿着六小时前，菊冈城二郎开车送明日奈回家的道路的反方向行驶、穿过涩谷山手线的铁路桥。星期六深夜的上行车道空着，驾驶座的父亲也露出了放松的神态。

但明明真皮座椅有靠垫，空调的暖风也很舒服，却不可思议地没有想睡觉的感觉。即使是因为肾上腺素在血管里奔驰，造成这样的原因也恐怕不止是爱丽丝发来的救援请求。

在Unital Ring的世界中，明日奈和从叫「Apocalyptic Date」的VRMMO里来的兽人们打了一仗——虽然这么说，但实际交战的几乎只有和人一个——将被拐走的结衣救了回来。在那时，被拘束的ApD玩家们，说出了一个令人吃惊的情报。

明日奈她们是从呈三段蛋糕状的Unital Ring世界的第二层南侧开始攀登，而从西侧开始攀登的ApD组，因为受到NPC集团的奇袭，阵型崩溃后就撤退了。

那些NPC，是拥有百发百中的弓术与浅黑色肌肤的精灵，将自己称为「琉斯拉」。

琉斯拉王国。那是在遥远的过去，在某个大陆存在的暗黑精灵王国的名字。琉斯拉王国与森林精灵建立的卡雷斯・奥王国共同达到了魔法文明的荣华，但两国的关系因为某个理由恶化，最后揭开战争的序幕时，两国的大陆被切割分离，放逐到了虚空中。

失去魔法的精灵们，为了追求将大陆归还的方法而到处搜寻。将擅长剑技的骑士送到危险的探索中，其中有许多人丧命。

「绮兹梅尔……」

不由得将刻划在记忆中的名字嘟囔出来，幸好因为引擎的声音而似乎没有传到父亲的耳朵里。对自己说现在必须集中到爱丽丝的救援上，并注视着车前窗。

不久，在前方见到六本木十字路口。按照导航的指示，在十字路口左转。不到一分钟，导航地图上就出现了目的地的图标。

「我去打开停车场的入口，稍微等一下。」

明日奈这么说道，彰三打开双闪灯代替回答，把车靠左移动。

幸好凛子还在公司，在携带终端上联络后就打开了地下停车场的活动遮板。沿着昏暗的斜坡往下行驶的车，停在了地下二层的访客用空间内，明日奈向父亲道谢后打开车门。

紧接着下车的彰三，露出了仿佛要进入敌区一般的表情，明日奈差点就要说出「稳重一点」了。但重新思考了一下，父亲似乎不是那种在情况危急时还引起骚动的人，于是向自动门走去了。

因为在大楼内的智能锁内，给了明日奈除机密区域外的所有区域的访问权限，进行终端认证和人脸认证后，乘坐电梯到达五层，再次通过安全门的时候，正好碰见凛子从道路的深处跑过来。

「抱歉，这么晚才来对不起」

凛子对连忙行礼的明日奈，大大的摇了摇头。

「稍微从爱丽丝那里听说了一点事情わ。对不起呐，在这个时间把你叫过来......」

说一半就中断了，恐怕是看到明日奈后接着看到了彰三吧。凛子睁大双眼，接着深深的行了一礼。

「久疏问候了，结城会长」

「这边才是，很抱歉在半夜才来，神代博士。女儿说无论怎么样也要过来，但这个时间肯定不能让她一个人外出呐」

「应该的。这是本机构的照顾不周，非常抱歉」

彰三用双手阻止了准备再次低头的凛子。

「不不，是因为女儿说出任性的话才送她来的」

「等等父亲，我并不任性......」

亚丝娜刚要反驳，就想起现在不是站着慢悠悠说话的时候了。

「凛子小姐，STL可以用吗？」

「嗯，亚丝娜平常用的那台已经启动了，进入了待机模式わ」

「十分感谢！」

明日奈道谢后就小跑到道路的深处了。虽然很在意彰三和凛子会说什么样的话，但按照现在的氛围的话应该不会说什么可怕的话吧。

飞奔进STL室，映入眼帘的是爱丽丝躺卧在中间的躺椅的身姿。和明日奈在傍晚从这个房间出去时，不管是服装还是姿势都没有任何变化。

在躺椅左右镇座的两台STL上，不管是哪台都没有人。和人从埼玉县川越市的家过来的话，无论是叫出租车还是骑摩托车飞驰而来，都得花一个小时以上吧，因此，不管Under world里发生了什么，也只能坚持到他到达为止。

将P外套脱下挂到衣架上，省略换上专用长袍的时间，在右边的STL上躺下。虽然穿着学校的制服潜行就有些踌躇，但像现在穿的棉针织衫和弹力牛仔裤这种随便的样子，即使起皱了也没问题。

明日奈刚躺到待机模式的STL下部的头枕上，上部的区块就自动地开始向下移动。上部区块的内侧凹陷处的，用和光立方相同素材制作的超高密度光学元件矩阵，正和星星一样闪烁着。简直不像精密机械，而像艺术作品一样美。

即使是引领民用XR机器市场的RECT，也被新兴厂商KAMURA开发的AR潜行机器「Augma」给夺走了市场占有率，现在是RECT想用第三世代机「AmuSphere2」卷土重来的状况。当然，更进一步的次世代机器也在研究开发，似乎是追求超过Augma的穿戴性的超小型机、和超过NERvGear的表现力的大型机，以这两方面为轴心进行开发。

前者的话需要很多技术革新吧，而后者已经被STL具现化了。即使对一般家庭来说太大了，但和用多边形构建的假想世界有着根本性不同的STL的记忆视觉情报，如果投入到XR市场的话，也一定会带来不输给2020年代初期“完全潜行革命”的震撼吧。

换言之，拉斯拥有泛用人工智能（AGI）和新世代VR技术这两个对于全世界企业来说都十分垂涎的革新技术。

果然拉斯……神代凛子和比嘉健，以及创始者菊冈诚二郎，想要一直隐藏这两个技术吧。据菊冈所说，开发小猫型机器人的理由似乎是「确保独立收入来源」，但不论是AGI还是STL，只要和大企业签订使用许可协议的话，也都能获得无比巨大的利益才对。

话虽如此，但拉斯本来就是官民合办的独立行政法人，因此菊冈也没办法独断地和企业签订协议。现在，文部科学省和总务省，以及防卫省之间展开的主导权争夺战结束的话，也说不定会有新的展开，被卖给民间企业还算比较好的，但在最糟的情况下，Under world被封闭废弃的可能性也不能说完全没有……

停止悲观的想象，轻轻地呼出一口气。

紧接着，STL的上部区块到达了指定位置，马达的驱动音停止了。取而代之的是如同温柔地敲响铁琴的奇妙声音将头——不，是将灵魂包了进去。

感到现实世界的重力正在远去，明日奈不出声地嘟囔了。

——现在就过去ね，爱丽丝。

** 4

猛然撞上第九十九层外壁的大型机龙，内藏的大量永久热素变成了火球，开始解放爆发。

爱丽丝一边看着以要把中央大圣堂上层全部吞没的势头膨胀的火焰，一边想用无咏唱生成所有能生成的冻素。

但是却无法立刻感应到应该充满周围的空间神圣力。可能是因为心意防壁刚刚被破坏，以及也有被当场死亡的乘员们临终的心意接触到的原因，精神没办法好好集中。于是只好咏唱术式，吸入因吹上来的火焰而变得火热的空气。虽然喉咙和肺部火辣辣地疼痛，但不能在意这些。

「「System call！」」

旁边的法那提欧似乎也在思考完全相同的事情，也异口同声地喊了出来。

但是，比说出剩下的句式还要快，火焰已经沿着大圣堂的外壁到达了两人站立的塔顶边缘。现在再生成冻素是绝对来不及了，但因为穿着拥有铠甲般防护性能的机士团制服，就算被火焰吞没也不会当场死亡。就算露出的皮肤与头发被烧焦，只要能在天命全损前做出冰的屏障的话——

「「Generate cryogenic element……」」

如此喊着的时候，猛火的前端已经舔舐到爱丽丝的发梢，一瞬间就被烧成了炭。

想象到全身被烧时的剧烈痛苦，爱丽丝本能地绷紧了身体。

但是，一秒过去了，两秒也过去了，却没有感觉到热度和疼痛。逼近到眼前的火焰，突然在仅1Mel远的地方倒退，在那里停下了。

想着是不是法那提欧做的心意防壁，但瞥了一眼旁边，副骑士长也在不断地眨眼。再次看向前方的爱丽丝，因为注意到了奇怪的现象而紧皱眉头。

像是因没将二人燃烧殆尽而愤怒的凶暴的火焰，被浅灰色的纱给阻挡了……不，是被吸收了。这不是心意防壁。是暗素做成的球形的壳，将火焰的能量给消除了。

暗素有着将一切挖去的性质，即使是热素的火焰也不例外。但一般情况下，能和热素一对一抵消的只有冻素而已，而一个暗素并不能完全吸收一个热素的能量。

因大型机龙的爆炸而解放的永久热素的数量超过了一百个。即使产生的火焰没有全部向爱丽丝她们的方向过来，将两人保护住的术士也至少同时生成了十个以上最难取悦的元素，然后将其变成巨大的球壳，并一直维持补充着和火焰抵消的暗素。在这种极限状况中，还能用出如此绝技的暗素使，在过去的整合骑士团中也能单手数的过来……

爱丽丝拼命忍住了想要回头看一下应该在背后的术士的冲动。现在必须想办法对付眼前的火焰。

抬起双手，总算用已经麻木的脑袋集中心意。高举右手，溶入到挡在打旋着的火焰前面的暗素生成的球壳中。虽然将火直接转换成暗是高等技术，但连这种程度都做不到的话就没法自称是整合骑士了。

和法那提欧一起拼命地生成了十秒钟元素。

凶暴火焰的势头慢慢地减小、依依不舍地远去——最终消失了。

像是看到火焰消失了，暗素球壳也云消雾散了。刚一消失，干燥的热风就涌来了，但不是会让天命减少的温度。

将温热的空气深深吸入，爱丽丝让自己重新振作起来了。虽然解放的永久热素全部升华为了空间神圣力，但大圣堂的外壁还是缠绕着通红的火焰。因为机龙的油压系统和润滑系统使用的油附着到了外壁上，那些油的燃烧是没有这么简单就能消除吧。虽然外壁的大理石被付与了自动修复术式，但热量还是能传到塔中，而且外壁在机龙的冲撞和爆炸下，也应该受到了不少损伤。冻结中的骑士们……以及在九十五层的赛尔卡和艾尔莉没事吗。

想现在就回到塔中，但不能将视线离开皇帝阿格马尔搭乘的机龙。说不定还有剩余的导弹，而且在最坏的情况下，也有对剩下的僚机下达突进命令的可能性。

但是，应该还是有看一眼将两人从困境中救出来的暗素使的脸的余裕吧。爱丽丝确认滞空的两架机龙没有动作后，快速的回过头。

然后，因为受到了比见到在一百层的露天阳台上站着的法那提欧的时候同等的、不，在此之上的惊愕而站了起来。

不是神圣术士。而是穿着和法那提欧相同设计、白银中镶嵌着墨黑色的铠甲，佩戴着细长曲刀的高挑女性。用黑色缎带绑起来的长发，像是在牛奶中注入了大量咖啡尔茶一样的颜色。

整合骑士……但是，不管是名字还是编号都不清楚。要问为什么的话，对那眉清目秀的脸庞一点印象都没有。

勉勉强强地残留着那凛然站着的身影的记忆，一定是在九十九层长眠的某位冻结骑士吧。再加上即使是爱丽丝也不知道名字，那就可能是在过去由最高祭司Administrator亲手石化冻结、封印在隐藏房间内的「古代七骑士」中的一人——

这么想的时候，女性骑士用晚霞色的眼睛，先是注视了法那提欧，接着注视了爱丽丝，眨了一次眼后就露出了微笑。虽然容貌十分凛然，但表情却温柔的让人吃惊，爱丽丝咽了一口气。

代替说不出话的爱丽丝，法那提欧向女骑士搭话了：

「不知道有几百年不见了……很高兴能再次见面，伊迪丝 Synthesis Ten。」

「你也很有精神呢，法那提欧 Synthesis Two。」

虽然应该没听说过「伊迪丝」这个名字，但被叫做「Ten」的话那就是骑士编号的第十位。果然是古代七骑士中的一人，那为什么没有陷入永眠而是醒来了呢。

法那提欧下达了「大圣堂再被一发喷进弹打中的话，在那时就立刻中止制作解冻药，并开始将骑士们解冻」的指示——虽然不是喷进弹而是被机龙冲撞了，但即使是在被冲撞的同时就中止制作解冻药，然后从九十五层移动到九十九层并马上开始解冻，伊迪丝的出现也有些过于早了。再加上冻结骑士中编号最大的是二十九号的菲洁尔，最开始解冻的应该是菲洁尔才对。

但不管解冻的原因是什么，如果伊迪丝没有用暗素球壳防御的话，爱丽丝和法那提欧就会变成焦炭吧。爱丽丝轻轻地吐出塞满胸口的气，想要对大前辈传达谢意。

但在就要说出口的时候，伊迪丝突然眉头紧锁地向法那提欧问道：

「稍……稍等一下。你刚才，说了「几百年不见」？现在是人界历多少年？」

「582年，似乎是这样呢。顺便一提，人界历变成了星界历わ。」

「……582年……」

看到张口结舌的伊迪丝，爱丽丝也把想说的话给吞了回去。虽然无法知道她被冻结的正确年份，但爱丽丝从就任整合骑士的人界历375年开始的五年间，应该一次也没听谁说过伊迪丝的名字。假设在那个时候，早就过了熟识她的人已经死去了的程度的时间的话。{译：长难句，大伙明白什么意思就行} 那伊迪丝被石化冻结的时间可能至少超过了三百年。

据艾尔莉所说，古代七骑士的灵魂处于不安定的状态——说不定这就是最高祭司将七人冻结封印的原因吧——即使是星王时代的桐人，似乎也判断没有安全觉醒的方法。不管觉醒的理由是什么，(灵魂不安定的)状况也应该没有改变，最坏的情况下，伊迪丝的摇光可能会承受不住心理冲击而崩坏。

在爱丽丝担心地注视伊迪丝之前，伊迪丝就慢慢地改变身体的方向，眺望着滞空的机龙。

「……怪不得，有没见过的物品漂浮在空中哇。那是什么？看起来像是人造的，是怎么飞起来的？」

面对接连不断的问题，法那提欧流畅地回答道：

「机械的飞龙，简称机龙哇。翅膀的里面封藏着热素，利用热素的压力来飞行哟」

「机龙……哼。刚才的热素爆发就是那个捣的鬼呐。敢攻击大圣堂，是暗黑界军干的吗？明明有你在，还能容许它侵入到圣托利亚中心？」

伊迪丝的声音里带着一些责备的意思。但法那提欧似乎不在意，以稳定的语调继续说明：

「乘坐那个的不是暗黑界军哇。虽然还没有确定是不是真的，但似乎自称是西帝国皇帝家的末裔。老实说我也是刚从深度冻结中醒来，所以没有完全把握住状况呐。」

「那个……」

下定决心后，爱丽丝插嘴了。虽然已经不再对法那提欧感到胆怯，伊迪丝的态度也没有压迫性的地方，但被两名前辈注视的时候，呼吸还是变浅了。

但是，现在也不能说「果然还是没有什么事」。爱丽丝往下腹部灌注力量，用比平时稍微低一点的声音说明了：

「敌方部队的指挥官，是自称皇帝阿格马尔・威斯达尔斯6世的人。虽然要求是（让我们）离开中央大圣堂，但我认为真正的目标是将石化冻结中的整合骑士全部歼灭。」

「阿格马尔6世……」

伊迪丝咕哝着将右手的手指一根一根地弯折。

「我所知道的西帝国皇帝是阿尔达斯3世，如果他的孩子是阿格马尔4世、アル4世、阿格5世、アル5世、阿格6世……过了5代吗。虽然作为我冻结三百年的代替来说有点少，但从机龙里拖出来看一下脸的话，就能知道是真的还是假的了吧。」

这些话似乎是认真的，伊迪丝将右手伸向酷似现实世界日本刀的长剑。但伸到一半就停了下来，改为认真地窥视爱丽丝。

「话说回来，你是谁？」

「嗯、嗯……我是整合骑士爱丽丝・辛赛西斯・萨提。」

「Thirty！？」

伊迪丝发出怪叫后，将脸更加靠近。

「你说Thirty，是三十号吧？成为骑士多少年了？在你之后还有多少人？」

「大、大约五年……在我之后，还有叫艾尔多利耶・辛赛西斯・萨提汪的骑士，但他已经在人界历380年，和暗黑界军战斗时牺牲了。」

轻轻用手指碰了一下右腰上的霜鳞鞭后，爱丽丝继续说道：

「在他死后，蒂洁・修特连Thirty-two和罗妮耶・阿拉贝鲁Thirty-three继任了，在那之后，听说在人界历441年将整合骑士团给解散了。」

「解散～！？」

高声叫着的伊迪丝，瞥了一眼镇座在露天阳台中央的圆形堂，然后立刻逼问法那提欧：

「解散是，骑士团已经不存在了吗！？是Administrator大人同意的吗！？还是说，解散是猊下的指示！」

「最高祭司大人……」

爱丽丝立刻了解法那提欧语塞的理由。

静静伫立着的白色圆形堂里，已经没有主君了。那位神人，最终在两百年前圆形堂中展开的激斗中，被狂热的火焰灼烧后崩溃了。虽然直接的死因是元老长丘德尔金的执念，但爱丽丝把剑朝向了曾作为骑士宣誓忠诚的统治者这点也是肯定的。

如果向伊迪丝说明最高祭司死去的来龙去脉的话，一定会不知不觉间触碰到爱丽丝反叛的事。法那提欧是在犹豫这个吧。

虽然很感谢副骑士长的关心，但如果伊迪丝哀悼最高祭司的死，责备爱丽丝的谋反的话，那也是自己必须好好承受的事。

如此思考的爱丽丝，下定决心向前踏出了一步。

但是，在即将开口的时候，受到了预想之外的阻碍。

「栖居在中央大圣堂的鼠贼们哟。」

在夜空中飞舞的大量火之粉，刮出了阴沉的声音。

爱丽丝反射性地翻身，看向了在西侧天空漂浮的机龙。

简直像是在等着一样，从右侧的机龙投射出了白色的光，显露出了四十岁左右的男性的胸像。装饰着夸张的肩章和无数的胸章的外套、宽广突出的额头和刀削般的鼻梁——不会弄错的，是自称阿格马尔・威斯达尔斯6世的男人。

立体影像一直在一闪一闪的。大概是让部下紧急修理了被天穿剑的激光破坏的投影装置吧。旁边的法那提欧像是不想再听戏言一样，想要将剑拔出来，但拔剑的手被伊迪丝抓住了。

「让那家伙再说几句。」

** 5

爱丽丝、赛鲁卡、艾尔莉、法那提欧。

我的脑海里依序浮现应该在中央圣堂守护着的四个人的脸庞。

不，不只有她们。在第九十九层还有十几名整合骑士、在下面的厩舍也有几乎相同数量的飞龙处于深度冻结状态，长耳湿地鼠纳兹也在。

即使在距离十公里以外的宇宙军基地，也能清楚地看见被火焰包围的大圣堂。虽然不认为被赋予了最大优先度的大理石外壁会烧起来，但热量与冲击肯定会传到内部，而且说到底，爱丽丝、艾尔莉以及法那提欧应该在塔外。

「……即使是一百发心意导弹，那样的爆发……」

以沙哑的声音自言自语后，双眼的焦点重新回到靠在办公桌上的托科伽・伊斯塔尔身上。

刚才伊斯塔尔说过：你不是星王桐人本人——因为你不懂皇帝血统继承者们的无情。

那些话真正的意思，我终于理解了。

「不是导弹……而是被机龙撞上了。」

我挤出不成声音的话。在传送到这个地方之前，虽然我用心意防壁阻挡了三架机龙射出的共计十八枚导弹，导弹的破坏力确实很惊人，但爆炸本身马上就平息了。现在，因为将大圣堂吞入的火焰一点也没有要消失的感觉，所以解放的热素数量恐怕不止20或30个。阿鲁斯级大型机龙的每边机翼上搭载着三座热素引擎——在里面的密封罐中封入的，合计可能超过一百个的永久热素，全部解放爆发了，只能这么想了。

因为爱丽丝和法那提欧应该不会击坠在圣托利亚市区正上方滞空的机龙，那剩下的可能性就只有一个。皇帝阿格马尔命令自己忠实的部下们，和机龙一起突入了大圣堂。

虽然Under world人没办法违逆上位者的命令，但摇光中掌管感情的机能——也就是「心」，和现实世界的人完全没有区别。受到皇帝的命令而指示决死的突击的机长、以及听从机长而拉动操纵杆的操纵士，究竟感受到了多大的恐怖与绝望。

「……自爆的机龙乘员，也是你的部下吧。」

我用不能再低的声音向保持沉默的伊斯塔尔问道。

又继续沉默了三秒后，黑衣丽人用同样低的声音回答：

「全员，都知道是决死的任务还从事了这个作战。」

「应该是，被强制从事吧。」

我反驳后，从正面注视着伊斯塔尔的脸。

虽然想马上带着失去意识的艾欧莱恩与负伤的拉吉回到大圣堂，但不想办法解决伊斯塔尔这个干练的枪手，就没办法制作「门」。而且基地内应该还有丝缇卡与罗兰涅，以及前去救援的缇洁与罗妮耶才对。

当我下定决心，准备赌一把用全力的心意拘束伊斯塔尔的时候。

伊斯塔尔发出了更加冰冷的声音：

「即使如此，没有一个人是没做好舍命觉悟的。不论是自爆了的三号机乘员，还是我……在基地上空滞留的四号机乘员也是。」

这些话像是暗号一样。

突然间，办公室的墙壁与天花板开始哔哩哔哩地震动了起来。

原本一瞬间以为是地震，但我没有在Under world经历过地震的经验。而且震动的发生源不是下面，而是上——不是地面，而是天空在震动。

…………不会吧。

我反射性地将右手朝正上方伸出，放出了心意波动。被极限稀薄化的心意波虽然没有物理效果，但是可以穿透几乎所有的物体，而且可以反馈感知，因此可以像雷达一样使用。但因为心意波接触心意使用者的话可能会被注意到，所以不能滥用，但如果是这种情况的话就没关系了。

心意波瞬间穿透天花板的建材与更上面的屋顶，像空中扩散开来。

然后，得知了我一秒前的担心变成了现实。

飘浮在司令部大楼正上方的大型机龙，两翼前缘排列的六座制动用逆喷射喷口一边喷出轰鸣声与火焰一边慢慢地向前倾斜。将机首往地面倾斜的那个机体姿势，想做什么是很清楚了。

「混蛋……！」

我一边大骂不把部下性命当一回事的皇帝，也同样是在骂没能预想到这种事态的我自己，然后将心意波的出力一口气提升到极限。右手前方的空间像是火焰一般扭曲，办公室的天花板与上面的横梁以及屋顶粉碎后被吹飞。透过屋顶上开的巨大洞口，群青色的夜空扩散开来。

耸立在夜空正中央的是，倒三角形的巨大影子。是机翼的逆喷射喷口闪耀着红光的倒立机龙。现实世界的重型轰炸机绝对办不到的机动，借由借助即使在静止状态也能挤出最大推力的热素引擎，巨躯强行直立了。

随着机龙完全进入垂直状态，逆喷射停止了。经过一瞬间的漂浮状态，机龙机翼后方的主喷口伸出长长的热素火焰，开始全力加速。

满载永久热素与导弹，全长超过四十米的大型全翼机全速撞击的话，不只是这个司令部大楼，邻接的建筑物也免不了倒塌吧。虽然张开小型心意防壁屏障的话，我和艾欧莱恩就能生还，但不可能舍弃拉吉和罗妮耶她们，以及在基地各处和Minion战斗着的数百名机士与操士们。

「唔……哦哦哦啊啊啊——！」

一边从肚子底部发出吼声，我一边在机龙的机首处展开了心意防壁。

零点一秒后，防壁和整流罩接触了，在夜空中扩散出了巨大的波纹。

和接下宇宙怪兽Abyssal Horror的能量弹时差不多的冲击，把右臂到大脑深处都给贯穿了。

即使如此，压力也不足以打破防壁。如果像这样继续维持心意力制成的超硬质防壁的话，机龙在数秒后就会因自己的重量和推力而压溃，然后爆炸吧。

但是。

在机龙的整流罩产生了放射状裂痕的瞬间——不，正确的说是，感知到了破裂了的外板深处的，十人以上的乘员的瞬间，我在无意识中改变了防壁的性质。从持有绝对硬度的钻石，变味了具有弹性和延展性的厚厚橡胶。

防壁像是漏斗一样凹陷，维持着机龙形状的同时减速。但是，六联装的大型热素引擎挤出的力量太过惊人了，防壁逐渐地被向下拉伸。和司令部屋顶的距离，转眼间就到了50米。

直觉地感到了只靠防壁无法阻挡的我，在心中道歉「艾欧，抱歉！」后，将抱着艾欧莱恩的左臂也往上方伸出了。放出心意波，虽然想感应引擎中的永久热素，但却被很厚的装甲和结实的密封罐给阻挡了连接。

失去支撑的艾欧莱恩瘦弱的身体往后倾倒。虽然想用心意之手让他软着陆到地板上，但完全没有同时发动两种想象的余裕。和现实世界不一样，不会出现撞到哪里会受伤的情形，我一边在脑袋的角落这么思考，一边将心意波的感度打磨到极限。

在漆黑的机龙轮廓中，六个橙色光点成群并排浮现。应该看不见的永久热素，在我的视界中重叠在一起。

「…………！」

屏住呼吸，将一百多个热素全部用想象的线路连结起来。然后，左手变得像是被火焰直接烤一样热。我清楚地感受到，被最大量的神圣力供给的热素，正用连密封罐都变得火热的温度熊熊燃烧着。

永久元素被「即使没有术士的控制也能继续存在」的术式加工了，比普通的元素还要难控制。因为强行压制会有爆炸的危险，所以我试图用心意之壳包裹住所有热素，切断作为能量源的神圣力。

维持弹性防壁的同时，还要进行一百个以上的元素的隔离，这是快让我的脑袋裂成两半的困难工作。但要是失败的话，基地全体就会变成火海。皇帝是认为就算牺牲一架机龙和十几名部下，只要能无力化宇宙军与机士团的话也很划算了。绝对不能让这种只看到得失的计策成功。

知觉被加速到极限，一切都变得极为缓慢。倒下去的艾欧莱恩的头发缓慢地波动着，飞散的汗珠在空中闪闪发光，我一边在视野的角落看着这些，一边将热素的一部分封入胶囊中。

隔离了大约五成后，引擎的推力迅速下降了。心意防壁已经拉伸到极限，机龙的尖端已经逼近到我头顶20米处。视野的九成被漆黑的巨影所覆盖，也能清楚地看到逐渐破裂的尖端装甲板所弹飞的铆钉。

——给我停下！

我一边全力进行热素的隔离，一边拼命的祈愿着。

六成……七成……八成。机翼后方伸出的喷射焰逐渐变短，然后不规则地闪烁——消失了。

但是，要松口气还太早。拦截着神圣力的胶囊消失的话，永久热素就会再次开始燃烧。我仍然一边进行隔离，一边将心意防壁进一步强化。

机龙的整流罩，发出「啪嚓」的令人厌恶的声音的同时被压碎了。但是，终于停下了垂直降落。

在仅仅不到十几米的驾驶舱窗户的深处，看到了像是很年轻的操士的脸。睁大了的双眼中浮现的，是巨大机体在空中静止了的惊愕，又或者是对做到这一点的我的恐惧呢。

无论有多么恐惧我，我也没有打算让他们完成皇帝阿格马尔的无慈悲到极限的命令、以及让他们因此而牺牲。我振奋精神，为了不继续破坏机龙，而慎重地托起机龙来。

因为同时维持胶囊与防壁的操作让我的意识完全集中了，我没有注意到艾欧莱恩完全没有倒下的声音。

左脸颊感到了空气的流动，在那半秒钟后。保持着脱力的艾欧莱恩的身体，像是在地板上滑动一样移动了。

他没有醒来。而是被念动力——心意之手牵引了。

「艾欧……！」

我一边用沙哑的声音喊道，一边也想要用念动力将艾欧莱恩拉回来，但在那个时候，黑衣的手臂已经缠绕住伙伴的身体。

「就这样别动。」

以冰冷的声音对我做出命令的同时，托科伽・伊斯塔尔左手一闪，用小刀刺在艾欧莱恩的喉咙上。刀身不到十公分，但很容易就能切断机士团长纤细的喉咙吧。只要小刀的主人愿意的话。

伊斯塔尔冰蓝色的双眸一瞬间往上看了一眼，接着看向我后说道：

「你那股让人觉得是笨蛋的心意强度还是没变。竟然能阻挡アーヴス级的全速降落。」

我无视这句讽刺后，压低声音指出：

「你伤不到艾欧莱恩吧，伊斯塔尔。」

「你在说什么呢。我和这个男人在阿多米娜互相砍杀的事，你也看见了吧。」

面对浅笑的伊斯塔尔，我立刻反驳：

「订正。你没办法伤到失去意识的艾欧莱恩。」

「……那就试试看吧。」

伊斯塔尔的笑容消失后，用小刀碰到了艾欧莱恩的肌肤。皮肤仅仅如此就裂开，无声地浮现一滴血。

「住手！」

这么大叫的不是我，而是将受伤的身体靠在书架上的拉吉・昆特二级操士。明明Minion的毒在全身循环，光是说话应该都很困难了，他却还是拖着腿往伊斯塔尔的方向迈了一步、两步。

但那大概就是极限了吧，拉吉突然无力地跪到地板上。

用冰冷的眼瞳瞥了一眼这样的景象后，伊斯塔尔再次看向我，说道：

「皇帝给我的命令有三个……绑架整合机士团长、如果困难的话就杀掉、都不可能的话就争取时间，等到四号机实行自爆攻击一起去死。桐人，你也知道吧。身为Under world人——不，身为人工摇光的我，除了听从那个命令之外没有别的选择。」

「…………！」

我用力吸了一口气。

这个男人，认识到自己是被现实世界人所制造的人工智能。而且——似乎还认识到「无法违抗命令和规则」这个人工摇光构造上的宿命。

爱丽丝知道这件事的时候，因为对创造了Under world的人感到愤怒而让「右眼的封印」活性化，最终导致了眼球破裂。伊斯塔尔的右眼看起来没有受伤，而且他说无法违抗命令就表示封印还健在吧，既然这样，他是怎么妥协自己是意志被限制了的被造者的呢？

我将头脑中仿佛要满溢而出的疑问给强行压下。现在，必须考虑夺回艾欧莱恩的事。

伊斯塔尔的右手抱着艾欧莱恩，左手则是用小刀抵着他。那个姿势的话，没办法瞬间拔出我最警戒的大型手枪。

虽然能全力使用心意的话，是有可能在一瞬间只液化碰到艾欧莱恩喉咙的小刀，但现在头顶上的机龙占据了我99%的心意力，不能确信用剩下的1%来做到无害化小刀。如果伊斯塔尔有决定听从皇帝的命令而死的觉悟的话，在我打算做什么的瞬间，可能就会真的深深地割裂艾欧莱恩的头，从而造成致命伤。

突然——

视野中，一瞬间闪过深红色的光。

并不是现实中的光。而是我的记忆中复苏了的色彩。是血的颜色……伤口中止不住地流出、堆积在地板上的鲜血的颜色。

温暖的、虚幻的，尤吉欧的血。

我无法忍受，全身激烈地颤抖了起来，心意防壁上的机龙因此向背面倾斜，响起了和雷鸣一样的「bakibaki」的破坏声。

我立刻改变心意防壁的角度，想要回复机龙的平衡，在这个时候。

伊斯塔尔右手抱着艾欧莱恩，往斜后方跳跃，飞跃了巨大的办公桌。虽然是令人吃惊的身体能力，但桌子后方有着似乎很坚固的固定格子窗，窗户的另一侧则是高度二十米以上的空中。

即使用什么手段破坏窗户后下降，然后再使用在阿多米娜公布的风素减震法而无伤着地，我认为他也做不到从宇宙军基地的正中心，抱着失去意识的艾欧莱恩逃走。将伊斯塔尔运到了这里的亚鲁斯级大型机龙，外板裂开，骨架弯曲，也绝对不可能再次飞行了。

即使如此，我也一边继续让机龙的倾斜度回到原来的角度、一边朝着艾欧莱恩喉咙旁的小刀投掷了心意之刃——不，是比心意之刃要更小更快的心意子弹。

不可视的子弹，准确地命中了小刀，发出尖锐的声音后从伊斯塔尔的手中掉落了。

但是紧接着。又发生了超出我的想象的事。

伊斯塔尔背后的两扇窗户同时被打破，和金属制的井字格一起吹飞到了外面。一瞬间，还以为是伊斯塔尔用心意破坏的，但并不是那样。是某人从外面抓住井字格并使劲拉开了。

伊斯塔尔仿佛知道窗户会破坏一样，没有踌躇地踢了地板，和艾欧莱恩一起投身于了外面的虚空。

「艾欧……！」

激烈的振翅声打断了我大喊的声音。

快要掉下去的伊斯塔尔与艾欧莱恩的身体，被像是黑色绳索一样的物体卷了起来。尖端稍细的形状，并不是单纯的绳索，而是生物的尾巴。沿着那个往上看，终于注意到悬停在空中的、黑得仿佛能混进夜空中的人形有翼生物。Minion——而且比曝尸在室内的战士型要纤弱得多，恐怕是飞行特化型。

那家伙一定从一开始就潜伏在办公室外面，在伊斯塔尔靠近窗户的时候帮助他逃跑吧。

虽然很惊讶应该没有知性的Minion能理解这么复杂的命令，但绝对不能让他就这么逃走。再次将心意子弹装填到想象的枪中，瞄准着被破坏了的窗户外面，正要拍动翅膀的Minion那如同蝙蝠一样的翼膜根部。受到一根翅膀无法自由活动程度的伤害的话，应该不会头朝下的坠落。

在我想要扣下想象中的扳机的那一刹那。

我的脑中回想起刚才伊斯塔尔说的话。

——绑架整合机士团长、如果困难的话就杀掉、都不可能的话就争取时间，等到四号机实行自爆攻击一起去死。

假如，被阻止了用飞行型Minion逃跑的伊斯塔尔，在地上发动了武装完全支配术——心意无效化空间的话。而且，无效化空间能影响到在七层的我的话。

不论是包覆热素的胶囊，还是支撑机龙的心念防壁都会消失，阿普斯级的巨躯在一秒后就会冲入这座建筑物当中。就算变成那样，我也能保护我自己和跪在身边的拉吉，但应该在司令部某处战斗的罗妮耶、缇洁、丝缇卡、罗兰涅……以及同样在视野外的艾欧莱恩，恐怕就无法立刻用护盾保护了。

在极短，但又像是连灵魂都撕裂了的逡巡（犹豫）之后，我把心意弹的准星往下移动。从Minion的翅膀变为了伊斯塔尔左腰上的大型手枪。

无声被发射的子弹，准确地命中手枪，贯穿了皮革制的枪套并撕裂了机关部。

然后，Minion猛然拍动翅膀，和用尾巴一圈圈缠住的伊斯塔尔与艾欧莱恩一起，瞬间从四边形窗框中消失了。

——不要放弃。艾欧莱恩还在仅仅十几米远的地方。

对自己这么说之后，我解放了全部的心念力。

将橡胶状的防壁变成巨大的心意之手，将刚回复直立状态的机龙整个抓住，这次则是往腹侧倾斜。虽然满身疮痍的巨躯再次发出悲鸣，像是金属片与螺栓之类的东西啪嗒啪嗒地落下，但一边勉强回避决定性的伤害，一边回到了水平状态。

然后立刻让机龙往横向滑行，移动到从司令部的窗户能一览无遗的跑道正上方。虽然想尽可能平稳地降落，但可能是因为焦急而操作得太过粗枝大叶了吧，接触了路面的起落架无法完全吸收冲击，全部折断了。我慌忙地增加支撑力，轻轻地让机身底部着陆。这次就没问题——刚一这么想之后，左侧的机翼就从根部折断，发出夸张的声音落在跑道上。

幸好，导弹和引擎没有诱爆。虽然变成了有些暴力的着陆，但这下即使永久热素复活了，机龙也无法移动。

在我解除几乎持续全力发动的两种心意之后，我一边忍受着反作用的晕眩，一边往前跑。对跪伏着的拉吉说「再稍微忍耐一下！」后跳起来，飞跃到办公桌的另一侧。我扑向连井字格和玻璃都被拆掉了的窗户，把身体探到外面，注视着夜空。

伊斯塔尔和艾欧莱恩消失后，还没有经过二十秒。即使那个Minion真的是飞行特化型，运着两个成年男性的话，能移动的距离顶多数百米——明明应该是这样。

「…………」

我一边咬紧牙关，一边眺望着夜空，即使如此也没有看到Minion的身影。不满意的我，飞出窗外后用心意急速上升到了一百米左右。再次环视一圈，确认所有方向都没有相似的身影之后，用球形的心意主动雷达照射四周。

以惊人速度扩散的心意波，依序捕捉到建筑内外的所有人类与Minion。如果是熟悉的人，甚至可以透过心意波掠过时的感觉来识别。不到一秒钟的时间，我就知道罗妮耶、缇洁、丝缇卡、罗兰涅四人正身处于连接办公室的通道上。看来她们正准备突破被网状固态物封锁的通道。

虽然司令部的下层与其他地方都持续着激烈的战斗，但入侵基地的Minion似乎顺利地被驱逐。搁置在跑道上的机龙中的敌兵们，也没有要出来的样子。

心意波到达方圆3千米的基地外，感知到森林中栖息着的如山一样多的动物们后消失了。

但是，直到最后也没有感觉到艾欧莱恩。

因为心意波是以半球状扩散，所以就算伊斯塔尔假装逃到上空，再降落到地面上，也不可能看漏。既然如此，没有探知到的理由只有一个——不对，是两个。

一个是，Minion用超过机龙的速度来加速，二十秒移动了一千米以上。

然后另一个是，伊斯塔尔也掌握了在阿多米娜的秘密基地时艾欧莱恩用过的，将自己与触碰者从他人的认识中完全消除的「空之心意」秘技。恐怕使用了那个的话，即使心意波捕捉到他们，我也注意不到。

距离看不见艾欧莱恩，已经快要经过一分钟了。

我一边用浑身的力气握紧拳头，一边蔑视并承认自己是个骄傲自满的混蛋。Under world中的我，拥有着只是想象就可以操作所有现象的规格外心意力。跟在Unital ring的世界里连生火都很困难的桐人（キリト）相比，简直是如同神一般的力量。

因此，我在这个世界的话，什么都能做到——无论是黑皇帝还是反叛军，我认为只要认真的话就没有解决不了的问题。在艾恩葛朗特也好，Alfheim（阿尔普海姆）也好，然后在Under world也罢，明明正是这种自满导致了许多无法挽回的事态，我却又一次……

不，现在不是责备自己的时候。基地内还有机士操士们正和Minion战斗着，大圣堂也还在燃烧。

——艾欧莱恩。绝对会去救你。

以仿佛要烧焦摇光的强度如此自言自语后，我以自由落体下降了100米，只在最后稍微调整角度后滑进了办公室。

着地的同时生成了20个光素，朝着跪在地板上的拉吉飞去。使用光素解毒的基本是，如果是口服毒的话就变成液体后喝下去，皮肤吸收的毒的话就直接渗透到伤口中，但拉吉被毒侵入已经有一段时间了，出血量也很多。于是我将光素全部变为雾状，将拉吉包入进去。

不幸中的大幸是，这个房间里流着大量被艾欧莱恩打倒的Minion的血液。因为即使是毒血也可以生成空间神圣力，所以光素不够的话还可以继续生成。

确认吸入光之雾的拉吉脸上稍微取回了一些血气之后，我跑向了正面的门。旋转用了很久的门把，打开门的一瞬间，在眼前浮现的是异常的光景。

宽广的走廊明明开着灯却还是很昏暗。像是发黑的细绳一样的物体，像是巨大的蜘蛛网一样，从天花板到地板、从墙壁到墙壁之间都密密麻麻地布满了发黑细绳，将走廊完全堵住了。我抓住离我最近的细绳想要扯下来，但细绳简直像是合成树脂一样硬，即使用全部的体重压上去也只是略微弯曲，没有要折断的样子。

我准备使用心意而举起的右手，在空中停下了。用手能完成的事却用心意去做，就是这个招致了自满。爱丽丝不是也说过吗，「并非所有事情都能用心意来解决」。

我从左腰拔出夜空之剑，在这个时候。

「前辈！？是桐人前辈吗！」

从走廊的深处，传来了耳熟的罗妮耶声音。回想起来，刚才的心意雷达察觉到罗妮耶她们在这条走廊上。

明明被蜘蛛网区域挡住而完全看不到身影，对面是怎么推测出这边是谁的呢，我一边感到不可思议，一边大声回应道：

「是我！你们四个都从走廊离开！我要用秘奥义把蜘蛛网吹飞了！」

「不行！这个网是Minion的血凝固而成的，即使是我们的秘奥义也没用！」

接着是蒂洁的声音：

「而且，风、火、冰也都没有效果！」

「……真的假的……」

虽然没有仔细地去看罗妮耶她们的剑，但既然两人都被任命为上位骑士了，那应该具备着神器级的优先度吧。既然这样，夜空之剑被弹开的可能性也很高。

果然还是只能用心意剥落吗，一边这么想一边差点抬起了左手，但这次还是忍住了。既然是暗属性的Minion的血硬化而成的网，用反属性的光素就会让其劣化……不，比起这个。

我压抑住想要赶快去大圣堂的心情，仔细地注视其中一根黑色细绳和墙壁的接合部分。飞散的Minion的血接触到墙壁和天花板的石材后就瞬间凝固，然后似乎就产生了极不合理的拉伸力，但并没有渗透进石材内部的样子。那么——

「我要稍微试一下！大家，离开一点！」

再次喊道，听到罗妮耶回答「明白了！」后，我将右手的剑摆为了上段的架式。发动了单发垂直斩击基本剑技「垂直斩（Vertical）」。

「滋啪！」一声清脆的声音过后，蓝色斩击垂直喷出。瞄准的不是黑色细绳，也不是细绳与墙壁的接合部分，而是右侧墙壁内侧一毫米的地方。虽然没有使用心意，但在Under world中剑技会擅自被心意强化。在ALO与Unital ring里，因为是通常攻击，所以连十公分都扩张不到的垂直斩（Vertical）的射程，在这里伸长了五米以上，将墙壁的表面薄薄地削去了一层。

我站起身后，右边的墙壁就开裂了，厚度一毫米的薄片啪嗒啪嗒地剥落。虽然跟细绳的接合部分还残留着，但接着把左边的墙壁也用垂直斩剥离后，失去支点的细绳就先后落下。虽然天花板与地板间的细绳还存在，但因为整体上去除了大约四成，所以矮个子的人应该不难从缝隙间钻过去吧。

这么想的时候，穿着机士团制服的少女们就已经开始往这边移动了。灵巧地扭动身体来穿过狭小的缝隙，不到十秒就来到我面前。

整合机士丝缇卡・休特里涅与罗兰涅・阿拉贝鲁快速地敬礼后一起说道：

「桐人大人，团长……」

「艾欧莱恩阁下没事吧？」

一瞬间语塞之后，我对两人深深地低下头，回答：

「抱歉。艾欧莱恩被托科伽・伊斯塔尔绑走了。」

尖锐的吸气声。抬起头的我所看见的是，双眼大大睁开并僵住的丝缇卡与罗兰涅。

当然，两人打从心底对艾欧莱恩的敬慕之情，只是共同行动了一天的我都清楚地理解了。一定，是必须守护艾欧莱恩的念头，才让她们登上了徘徊着Minion的司令部大楼的七层吧。

任何责难我都愿意接受，我等待着两人说话。

但丝缇卡和罗兰涅比我想象的要成熟得多，她们既是机士，又是骑士。

「了解了。镇压残余的Minion和救出艾欧莱恩阁下（的任务），就交给我们吧。」

罗兰涅用冷静的声音如此承诺后，丝缇卡也用力眨了一下眼睛、刚强的补充道：

「桐人大人请和罗妮耶大人、缇洁大人一起回到中央大圣堂。不能允许奸贼继续横行下去了。」

从她们仰望我的眼瞳中，之前的冲击与动摇的神色已经消失，只有纯粹的决意在猛烈地燃烧着。

「……知道了。」

我点头后，看向了走廊的尽头。因为铠甲的原因而稍微花了点功夫拨开蜘蛛网区域，才刚过来的罗妮耶她们，似乎听见了所有的对话，交换视线后点头表示同意。

我也无言地回了个点头，小跑步回办公室，对刚好站起来了的拉吉问道：

「没事吗？」

「是……非常抱歉，明明有我跟着，机士团长阁下却……」

「反省会就等救回艾欧莱恩的时候再开吧。你对丝缇卡她们说明在这里发生的所有事情。」

「了解了。」

对迅速敬礼的拉吉，我也快速地回礼。明明没有在现实世界做过这种动作的记忆，手臂却非常流畅地动了，虽然心想「咦？」，但现在不是注意这种小事的时候。

最后再看了一下窗外的夜空后，我往房间的中央举起右手。因为这是唯一的替代方案，所以要回到大圣堂只能依赖「心意之门」。留下一具用来调查的，将六具Minion的尸体全部变换为大量的晶素。然后将其凝缩为一扇很大的门，放在地板上。距离约定的零点，还有不到一分钟。

「罗妮耶、缇洁，回去了！」

我一边对背后的两人喊道，一边用念力拉开大门。刚一拉开，就袭来了突然的晕眩感，但要趴下还早得很。

连接起来的空间另一侧，是像广场一样的地方，整齐排列的大理石瓷砖，被蓝色的星光与红色的火光照耀着。那应该是中央圣堂的屋顶吧。正前方的是，背对着这边站着的三名骑士。

我那已经踏入大门的脚突然停了下来。因为我是沿着爱丽丝的气息而制作的门，所以一个应该是爱丽丝，一个是从石化冻结中醒来了的法那提欧才对，第三个人到底是谁呢？

不论是谁，那形状特殊的铠甲明显是整合骑士的东西，没有必要警戒吧。我对罗妮耶她们点头后，这次才跨过了水晶的门框。

紧接着——

头顶的夜空中，闪耀了通红的光。

** 6

「让那家伙再多说几句。」

听到伊迪丝这么说的法那提欧，简短的回答「嗯嗯」，将手从天穿剑的剑柄上拿开了。

是看到这边发生的事情了吗，阿格马尔的立体影像瞄准时机再次发出了声音：

「余之无私的救国决心，和余之精兵们的殉国之志，共同刻入到了余的心底。但是，余的仁慈平等的倾洒在所有人民上。逆徒们哟，余再次赐予你们一次改过自新的机会。在零点的时钟响起来之前，将年代经久的剑和铠甲扔出塔外，把头抵在地板上表示恭顺就好。否则，净化的火焰将会再次刮起，那样的话就会烧的一个也不剩吧。」

叽、叽叽……发出这种声音的立体影像开始不安定，最后消失了。

爱丽丝在脑袋的角落想，如果桐人在这的话，「从哪里开始吐槽好呢」会说出这样的讽刺吧。阿格马尔的话太自以为是了，所以爱丽丝没有浮现出认真的感想来。

茫然站着的时候，右侧的伊迪丝嘟哝了：

「那个，大概是真的呐。」

「这么想的理由是什么？」

左侧传来了法那提欧提出的疑问。伊迪丝发出轻微的声音耸耸肩，回答道：

「没有明确的根据哟。但是，那个人和我曾数次对话的阿尔达斯3世，不管是脸还是口气都一模一样。如果是假的话，那他可以去南圣托利亚的大剧场当招牌演员了哟。」

「戛拉齐欧（ガラキオン）歌剧院的话，在你沉睡后大约三十年就被关闭了哟。既有新作演出的题材不敬的原因，也有丘德尔金小气的原因呐。」

啧一声，伊迪丝高声咂了一下嘴，狠骂道：

「那个白ツルコ饼，这次见到的话一定要把他伸的又长又平。」

两人的对话里包含了连在Under world出生的爱丽丝都不知道的词语，虽然是这样的情况，但不知不觉间就回话了：

「伊迪丝殿下，白ツルコ是什么？」

于是黑色缎带的骑士，在一瞬间将皱着的脸变成了笑脸。

「哎呀，爱丽丝酱不知道ツルコ饼是什么吗？这样的话，在东圣托利亚有做的很好的店，收拾完这个骚动后一起去吃吗？我推荐放了煮的很甜的阿兹拉（アズラ）豆的，和将谷子搓成丸状再包进去的呐。」

听到这些的法那提欧立刻插嘴：

「虽然豆子和谷子的也不错，但我认为放了肖科尔（ショコル）的才是第一呐。」

「肖科尔（ショコル）？虽然我也很喜欢，但对于ツルコ饼来说不是邪道吗？」

「这么说的话，那王道就是什么也不放的白ツルコ吧。」

爱丽丝哑然地旁观着开始争吵的两人。如果阿格马尔听到了这段对话，他的额头上一定会爆出青筋吧。虽然应该不会因为这个就把时间限制提前，但距离皇帝宣言的零时也已经迫在眉睫了。

爱丽丝对现实世界中机械身体的状态监视器一直显示在视野中这点，虽然老实说很郁闷，但还是不得不承认时间显示——不，还有天气预报和地图应用——是很便利的东西。Under world里大概还是主要靠三十分钟响一次的时钟来确定现在的时间，阿拉贝尔家的起居室虽然装饰着大型的挂钟，但可以携带的怀表和腕表似乎还没有开发。理所当然的，在场的三人谁都没有带着表。

也就是说，只能用体感来估计到时间限制前还有多少分钟。大概还有十五分钟——不，比十五分钟还少。

「那个，法那提欧殿下、伊迪丝殿下」

爱丽丝下定决心打断了还在继续交谈着ツルコ饼的两人。

「要怎么应对皇帝的要求呢？我认为到零点我们还不降伏的话，皇帝恐怕打算让剩下的机龙也冲撞大圣堂……」

因第一架机龙的冲撞而起火的九十九层外壁，现在也还被火焰包围着。根据伊迪丝没事这点来看，大圣堂内部大概损伤不深，但如果第二架也撞上的话，没办法保证还能承受住。但是——

「哎」

伊迪丝有了反应，伊迪丝盯着吃了一惊的爱丽丝后，轻轻耸肩后说了：

「阿格马尔不是在那个叫机龙的东西里吗？那么只要取下他的项上人头不就好了？那样的话，士兵们就会全员投降吧」

「哎」

爱丽丝也提高了声音。确实，只要用实力将皇帝排除，部下们就有很高的可能性承认这边的上位者，但说到底，就是因为没有登上机龙的方法才一直进行着拼命的防卫战。

法那提欧似乎也在想着一样的事，接连不断地扔出了问题：

「你准备用什么方法登上相隔接近1Kilol的机龙？即使是你，凭自身的力量也做不到跳上去吧？而且，就算有能在空中飞行的手段，皇帝也能监视我们哟。如果皇帝察觉了这边的意图，在察觉的同时就让机龙突击也不是不可能的わ」

全都是理所当然的指摘。不过硬要说的话，这个时代有爱丽丝没有习得的风素飞行术，但蒂洁说过风素飞行术会发出很大的声音，所以没办法隐秘行动。{译：桐人的手法更高级些，可以做到几乎无声飞行} 但伊迪丝再次用冷静的声音断言道：

「忘了我是骑士团最强的暗素使吗？有的是在黑暗中悄悄接近的方法わ」

「那么，移动手段是？」

「早就决定了吧，用飞龙……」

突然，伊迪丝强烈地吸了一口气，向法那提欧的方向迈了一大步。

「对了，我的『雾舞』呢！？还在飞龙厩的地下冻结着吗！？」

「飞龙厩在很久以前就拆除了哟。」

「骗人的吧……那么，雾舞……」

「放心吧，和我的『藤结』以及猊下的『雪织』一起维持着冻结状态，转移到九十六层了」

「……这样啊……」

伊迪丝深深地吐出安心的气息，又微微皱起眉头。

「……九十六层？为什么转移到元老院里？」

「说来话长了……总而言之，飞龙不能用人类的解冻药，所以现在做不到让飞龙立刻觉醒」

「那么，你打算怎么办？」

在靠近一步的伊迪丝斜后方，爱丽丝也一动不动地等着法那提欧的回答。副骑士长以平静的表情看着两人，断言道：

「陛下……不对，桐人和我约好在零点前回来。那么他一定会回来的，我们只要忍耐到那个时候就可以了。」

「桐、人…………」

不是很流畅地说着“桐人”这个名字的伊迪丝，诧异地歪了歪头。

「有叫那个名字的骑士吗？还是说，是像爱丽丝酱一样在我冻结之后才成为骑士的孩子？」

「不是骑士哟。桐人是全Under world的……」

法那提欧正要说出真相时。

像是同时轰响了数百道雷声一样，猛烈的重低音将大圣堂哔哩哔哩地震动着。三人整齐地回转身体，看向了东北偏北的天空。

包围圣托利亚市区的圆形墙壁的另一边，在漆黑的森林与湖泊的更深处，垂直地喷出了鲜红的火柱。一瞬间还以为是火山喷发了，但圣托利亚的郊外并没有火山，而且仔细一看，是六根火柱排成了一条直线。

「那是……机龙的热素引擎……？」

勉勉强强地在轰鸣中听见了法那提欧的说话声。

不会弄错的。那是在宇宙军基地上空扎营的大型机龙，正在将六台引擎全力喷射。但是，火焰是垂直向上喷出的，那么机首就是垂直向下。也就是说，那架机龙——

「……打算自爆！」

拼命喊着的同时，爱丽丝注意到了。

大型机龙在仅有数百梅尔的高度上倒立着。如果在那个状态下引擎全开的话，应该一瞬间就冲撞到基地中了。然而那架机龙已经维持了十秒以上的全力喷射。究竟是什么东西在承受着上百个永久热素产生的推力，再加上机龙本身巨大的重量呢。答案只有一个——桐人的心意。

爱丽丝和法那提欧面面相觑，从副骑士长张大的双眼中，看见了和自己相同的担心。基地上空的机龙也收到了自爆命令，如果是桐人一个人阻止的话，那么就有在时间限制的零点之前回不来的可能性。

「那个……是不是有点不妙啊？」

就连应该不知道状况的伊迪丝都发出担心的声音。

「相当不妙！」

爱丽丝立刻回答，同时拼命凝视着远方。几乎伸到云层中的火柱，将像是箭头一样的大型机龙以及在正下方耸立的金字塔状宇宙军司令部照得通红。

实在不认为司令部具备跟中央圣堂相同程度的优先度。机龙撞上并且爆炸的话，应该就会消失得无影无踪吧。那个时候，心意防壁被打破的桐人恐怕不可能毫发无伤，待在司令部某处的罗妮耶、缇洁、史提西亚、罗兰涅就更危险了。

不，如果是桐人的话，绝对会做些什么的。

不论是在Under world与最高祭司Administrator以及暗神贝库达的决战，又或者是Unital ring与The Life Harvester以及魔女穆塔希娜的激战，桐人都绝对不会放弃，而是会与强大的敌人对抗。这次也一定，无论被逼到什么地步，他都会连不是同伴的敌兵都救下来。

——我也是，不那么做不行。

爱丽丝一边紧握着爱剑的剑柄，一边强烈地斥责了自己。

不论时代怎么改变，爱丽丝・辛赛西斯・萨提都是人界的守护者——整合骑士这一点是不会改变的。即使自称阿格马尔・威斯达拉斯6世的男人真的是西帝国皇帝家的末裔，对无辜的市民施加危害的人也都是骑士的敌人。骑士怎么可以因为屈服于威胁而舍弃剑呢，不能允许继续伤害大圣堂，以及强迫部下进行自爆突击了。

但凭爱丽丝的心意力无法阻止机龙的突击，爱剑的天命也只剩下一点了。就算想混进黑暗中也没有飞行手段，当然也做不到击坠机龙。

真的有不对市区造成伤害地让剩下的两架机龙着陆的方法吗？

现实世界的航空器是让石油精炼的燃料燃烧来飞行的。所以，如果在飞行中的时候燃料泄漏就必须紧急着陆。但Under world中的机龙不是靠油箱中储存的燃料来飞行的，而是靠着机龙外部存在的空间神圣力来飞行的。有什么办法能将眼睛看不见、对心意也没有反应的神圣力资源的供给给断绝呢。

想到这里时，爱丽丝的脑袋里响起了微弱的声音。

——峡谷里，即使是白天也照不到阳光，也几乎看不到植物。也就是说，空间神圣力比较薄弱。

——在开战前，把空间神圣力给消耗殆尽的话，敌军就不能用强力的术式攻击了。

想到已经是遥远过去的，在东大门和暗黑军决战的事。在开战之前的会议中，副骑士长法那提欧这么说了。

虽然贯穿终结山脉的荒凉峡谷不能和在人界最富饶的土地上建立的央都圣托利亚相比，但据罗兰涅的弟弟费鲁西所说，圣托利亚似乎从数年前就出现了神圣力枯竭的问题。更何况现在是深夜，自然供给量应该已经降到最低了。

如果像东大门之战中爱丽丝做的一样，用大规模术式将周边的神圣力资源给消耗殆尽的话，机龙就会浮不起来。并且因为热素引擎的出力也会逐渐降低的缘故，也给予了让机龙紧急着陆到市区外的余裕。

问题是，应该用什么样的术式。如果皇帝正在监视三人，不可能不注意到制作巨大镜面球体的「反射凝集光线术」，而且隐藏除此之外的其他术式大量生成的素因所散发的灿烂光辉也很困难。

只有一个例外，暗素几乎不会发光……但，没有比大量的暗素更恐怖的东西了。如果脱离控制并同时全部解放的话，爱丽丝她们连带着周围的空间，都会不留一根头发的消失吧。

但是伊迪丝刚才说了「忘了我是骑士团最强的暗素使吗」。虽然相遇还不到十分钟，但总觉得要相信那句话。{译：游戏线的记忆真的觉醒了 笑}

「伊迪丝殿下。」

保持着注视在西方天空中飞行的两架机龙的姿势，爱丽丝小声地呼唤了黑色缎带的骑士。

「怎么了，爱丽丝？」

「同时生成的暗素数量，最多能有多少？」

「嗯……努力的话有二十个吧。怎么了？」

正想要对反问的伊迪丝说明意图的时候，但就在那个时候。

「原来如此，用和东大门之战一样的方法吗。」

爱丽丝对着低语的法那提欧点头了。但伊迪丝发出了惊讶的声音：

「东大门？在那样的地方，是谁和谁战斗了？」

「是在你沉睡的时候发生的事件，之后会好好的给你说明，现在先忍耐着。——爱丽丝考虑的是，能不能用大量生成的暗素，将大圣堂周边的神圣力给消耗殆尽哟。」

因为法那提欧针对不明白的地方进行了说明，爱丽丝只是无言的点头同意。但伊迪丝惊讶的表情还是没有消失。

「为什么是暗素？如果要大量生成的话，容易操控的光素或者水素不是更……」

说到这里时，伊迪丝像是明白了一样点头了。

「啊啊，是元素的光会暴露我们的位置。确实，如果是暗素的话，即使大量生成也能隐藏在黑暗的夜晚中，但想要将半径1Kilol内的神圣力给消耗殆尽的话，别说二十个，就连两百个……不，考虑到刚才解放的热素的话，即使有三百个也不够吧。只凭三个人来生成是远远不及三百个的吧？」

伊迪丝的想法很有针对性。爱丽丝之所以在东大门之战能让峡谷的神圣力枯竭，是因为使用了将大量光素封入镜子做成的球体中的「反射凝集光线术」。但是，能安全储存可以将所有物质削去的暗素的容器，在爱丽丝所知的范围内并不存在。即使封入很厚的钢铁中，暗素也能从内侧向外侵蚀，只要数量够多的话，总会开出洞来的。

以上的这些，爱丽丝也知道。

「正如伊迪丝殿下所说的，只是生成暗素的话，无论如何也是无法耗尽空间神圣力的。所以，生成暗素后就立刻处理掉，然后再生成新的暗素……像这样不断地重复cycle（循环）的话……」

虽然在无意中用了现实世界的单词，但爱丽丝想要说明的循环似乎有好好的传达到了。但即使这样，也是熟练神圣术师的老骑士们并没有接受。

「你说的『处理』，只是解放的话不就又变回空间神圣力了吗？不封入到某物里再让其抵消的话是不行的。但暗素的捕获器即使在大圣堂的宝物库里也只有一两个，要说能和暗素发生反应的物体，手边有的大概也就是我和法那提欧的铠甲吧。」

爱丽丝再次对毫不犹豫指出疑问点的伊迪丝点头。

虽然对能保存暗素的容器确实存在感到惊讶，但在这个时代，宝物库里恐怕已经没有暗素捕获器了吧。而且，即使两人铠甲的优先度再高，仅靠铠甲也做不到让数百个暗素抵消。

但是，在现在的地方，存在着持有不得了的体积和优先度的物体（object）。不论是数百个还是数千个暗素都能泰然地接受吧——人界最大最古老的被造物。

「有即使不能将暗素储存也能将其抵消的方法。」

以此为开场白，爱丽丝向二位骑士前辈说明了主意（idea）的核心。

「要使用中央大圣堂。我们脚下的材料，不仅设置了超高优先度，而且还付与了自动修复术式，因此碰上暗素也不会简单的破坏。再加上自动修复也会消费空间神圣力，比起单纯的生成元素，能更快地消耗神圣力。」

「……但是，大圣堂不是公理教会，以及最高祭司大人的……」

仿佛至今为止的豁达都是骗人的一样，伊迪丝一边发出老实（译：原文 神妙 注音为しんみょう，因此为老实）的声音，一边看向背后的圆形大堂。爱丽丝注意到她的侧脸浮现出像是吓了一跳的表情。

但那表情一瞬间就消失了，红色眼睛里重新寄宿了下定决心的光芒。摇了一下绑起来的头发后转身，伊迪丝就对爱丽丝与法那提欧重重地点了点头。

「对不起，应该守护的是大圣堂内的人们，而不是建筑本身。我认为爱丽丝的作战应该能顺利进行……但是，除了夜晚的黑暗之外，还需要一个欺骗。」

「欺骗……？」

在皱起眉头的爱丽丝前方，伊迪丝把长刀连同剑鞘一起从剑带里拔出，轻轻放到脚下。确实，皇帝如果看见这个动作的话，大概会解释成投降的准备吧。耿直的迪索尔巴德大概会愤慨地表示：「竟然把如同骑士灵魂的神器放到地上！」但他现在依然在第九十九层沉睡当中。

看见左边的法那提欧也把天穿剑连同剑鞘一起拔出，爱丽丝的手也碰到了剑带。把剑鞘连同小小的铁环从Under world称为「猫钩（ねこかぎ）」，现实世界称为「茄子环（ナスカン）」的挂钩上取下来。在心里对满身疮痍的爱剑说了声「稍微忍耐一下」后，就把它放到冰冷的大理石上。

挺直腰杆，一瞬间看向北方的天空。

从宇宙军基地向天空伸出的六根火柱，变得更长了。已经维持了差不多三分钟的那个状态。不仅阻止了大型机龙的突进，而且还没有让机龙自我瓦解，虽然不得不惊叹桐人的心意力，但只是维持那个状态就应该会有很大的消耗。至少是为了让桐人专心守护基地，也绝对要阻止对大圣堂的第二次自爆攻击。

爱丽丝、伊迪丝、法那提欧三人排成了一条直线，注视着正面的机龙。

双手放到身后，昂然挺胸。虽然把剑放下了，但把铠甲和制服脱下对骑士来说是难以忍受的吧——就像是这样，皇帝应该看到了。

距离时间限制的零点，大约还有五分钟。

两人（译：爱丽丝和法那提欧）将步调一致，在背后的双手的指尖，无咏唱生成了十个暗素。就这样放飞到后方约3Mel处，切断控制后任凭暗素掉下去。

啪、啪、持续发出了干脆的炸裂声。暗素碰到了露天阳台的大理石，挖出球状的坑后消失了。

从左右两边也听到了一样的声音，爱丽丝和法那提欧各自同时生成十个，加上伊迪丝生成的一共有四十个。这些暗素一起产生反应，简直像大颗冰雹猛烈击打地板一样热闹，但这声音应该传不到皇帝的机龙上。

仔细听的话，能听到混杂在暗素破裂声中的，像是用指甲弹水晶一样的高音。是大理石块自动修复的声音。现在，因为被机龙自爆攻击伤到的中央大圣堂九十九层外壁也在修复中，所以消费的空间神圣力大概数量十分庞大。问题是，五分钟内空间神圣力枯竭区域能不能到达1Kilol外的机龙。

不……绝对会到达给你看。

爱丽丝竭尽全力地用心意生成着暗素，然后继续放飞。假如在稍微远一点的地方观察三人的话，就能观察到像三人的存在本身升华了一样，淡紫色的光点正不断地飞舞散落。

仿佛削减灵魂般的一分钟过去了，正要过去两分钟的时候。注意到眼下的市区变得像两百年前一样暗了。永久光素的灯光因为神圣力资源的切断而一个个的熄灭了。

不只是路灯，使用元素的机车、冷暖机和送风机之类的机械也都应该停止了，虽然避难行动中的居民大概会感到更加混乱和恐怖，但现在只能忍耐了。黑暗转眼间扩大了，从西圣托利亚的行政区到商业区再到居住区，全都被黑暗吞入了。

在爱丽丝生成的暗素正好超过一百个的时候。

轰响了像是地鸣一样的重低音，机龙的巨躯开始向前移动了。虽然距离零点大概还剩两分钟，但皇帝也不是会看漏地上发生的异变的蠢人。

现在就是决定胜负的紧要关头。

大概是有了同样的直觉吧，右边的伊迪丝大喊：

「喝啊啊啊啊！」

像是不服输一样，爱丽丝和法那提欧也鼓起劲来。如果神圣术师阿优哈弗利亚在这里的话，应该会说「大声喊出术式只会造成干扰哟」，但也有「大声喊出来就能竭尽全力」的说法。

因为已经没有隐藏动作的必要了，所以将双手从背后移到了前方，生成的暗素碰到了眼前的大理石地板上。发出破裂声与微弱闪光的同时将大理石挖出无数个小洞，但小洞也被修复术式给慢慢地填补上了。但再怎么说也是有三人份的力量，大理石比起修复来说还是侵蚀更快，不过在将很厚的大理石开出对穿的洞之前，空间神圣力资源就会枯竭了吧。

枯竭的瞬间，在仅仅数秒后就来了。

正要全力加速的机龙的喷射焰，不安定地摇动着。

正在爱丽丝指尖生成的暗素，也忽闪着消失了。

能收集空间神圣力资源的距离，是靠「史提西亚之窗」中的术式行使权限（SC）等级来决定的。爱丽丝的SC权限值在打倒神话级宇宙兽「Abyssal Horror」时超过了70，法那提欧和伊迪丝应该也在60左右。因为记得收集距离在SC等级达到50时就能超过1Kilol，所以在这个瞬间，以大圣堂为中心生成了半径接近1.5Kilol的神圣力资源枯竭空间也不奇怪。即使机龙的收集器性能再怎么优秀，应该也无法确保让六座引擎正常运转的空间神圣力。

首先，左边的机龙摇摇晃晃地乱了姿势，靠着机翼下方的滞空用喷射口的推力转了一圈后才好不容易恢复了平衡。紧接着，右边的机龙也向前倾斜，靠着向下方喷射才维持了姿势。

「快点退下，要坠落了哟！」

应该不是听见了伊迪丝说的话，但两架机龙保持着向下方喷射的同时，机翼前沿的逆喷射口喷出了火焰，开始慢慢地向后退了。因为喷射完全不稳定，每当喷射中断时，巨大的身躯就会突然下沉。如果坠落的话居民区就会变成一片火海，所以只有现在不得不对他们应援加油。

三人放下双手，咽了一口口水，在三人注视的前方，市区的天空中两架机龙正慢慢地后退，越过圣托利亚的城墙花了大约三十秒。城墙的对面，广阔地分布着和两百年前一样的耕地和草原。

逆喷射停止了，下方的喷射也变弱了。两架机龙一边摇晃着机翼，一边生硬地下降，最后用落下般的气势将巨躯埋入到了草原中。因为离得很远又很黑，所以不了解详情，但机体应该受到了不小的损伤。即使重新供给空间神圣力，也做不到立刻起飞吧。

暂且吞下了安心的气息，爱丽丝接着急忙地看向了北方的天空。

基地上空的火柱不知何时消失了，宇宙军司令部也还建在。看来桐人不仅阻止了机龙的全力突击，似乎还将机龙给紧急降落到某处了。

爱丽丝这次深深的吐了一口气，接着看向了法那提欧，再看向了伊迪丝。虽然想对她们道谢，但她们和爱丽丝都是背负相同义务的整合骑士。想要守护圣托利亚和央都的心情是一样的吧。

「……两位，干得漂亮。」

将道谢给取而代之的是赞赏的话，法那提欧将右手伸出，轻轻地敲了爱丽丝的左肩。

「你也是呢，爱丽丝。还有，将圣托利亚的神圣力消耗殆尽的作战，连我都想不出来呢。简直就像是桐人的思考方式……」

就在这个时候。

听着两人对话的伊迪丝，像是感觉到了什么而抬起了头。

「……那个，是什么……？」

爱丽丝也往发出沙哑声音的伊迪丝视线方向看去。

夜空的正中央，染上了连一颗星星都看不见的漆黑。虽然像是有什么东西遮住了星星一样，但无论再怎么仔细看，都无法知道大概漂浮在离地面多高的地方，也不知道到底是生物还是人造物。

一瞬间，虽然做好了是新的机龙的准备，但没有听见热素引擎的驱动声，也没有看见喷射焰。而且影子的形状是细长的楔形，和亚鲁戈级机龙完全不同。没有机翼的机龙，不，航空器，不仅是在Under world，在现实世界也应该没有。

——突然，影子的前端发出了红色的光芒。

然后急剧地变亮，简直像是因无法承受压力而崩开一样，闪耀着十字的光芒。过了一会，像是远雷的低沉轰鸣传到了耳中。

爱丽丝皱起眉头，就在这个时候。漂浮在夜空中的黑色碎云碰到了红色光芒，一瞬间就被吹成环状。

那不是单纯的光，而是从超高处发射的超高温火球。{译：天基武器 这就是uw}

也就是说贴在夜空上的细长楔形黑影，果然是类似机龙的东西。但是，因为漂浮在比云层还要高的地方，没办法清楚地确认的话，那么全长恐怕不止一二百米。如此巨大，而且还没有机翼的钢铁疙瘩，是怎么不靠下方喷射而滞空的呢。

不，现在不是思考这些的场合。如果让看起来少说也有五十个热素量的大火球给直击的话，不仅爱丽丝她们也不可能无事，被暗素削去不少的大圣堂屋顶也可能崩落。

爱丽丝向火球的方向伸出右手的同时，法那提欧和伊迪丝也做了相同的动作。因为大圣堂周边的神圣力已经消耗殆尽了，所以没办法再次做出暗素球壳了。虽然只有心意防壁是挡不住的，但在迄今为止的战斗中，感觉脑中产生心意力的地方已经消耗到了接近极限的程度。

……是错觉吧。Under world人的灵魂，不是在活体大脑中，而是在光立方里储存着，所以不会积攒疲劳物质。

爱丽丝这么对自己说，接着想要从意识的所有角落里集中力量。

在那个时候——

爱丽丝和伊迪丝的中间，第四只手高高的举起了。兼具柔软和坚强的五指前端，空间像波纹一样颤抖着。

其中隐藏着可怕的强度，然后，在哪里感受过的温暖心意和爱丽丝三人的心意融合了，做出了完全覆盖着大圣堂屋顶的巨大心意防壁。

刹那之后，和轰鸣声一起落下来的火球直击到了心意防壁，引起了几乎能照亮全圣托利亚的大爆炸。通过心意回线，热和冲击逆流到了右手上。

似乎弄错了。爆炸的规模和大型机龙自爆时差不多。也就是说，火球内蕴含的能量，换算成热素的话最少也在一百个以上。

将夜空染上赤红的爆焰，像是因什么都没破坏而愤怒似的，盘旋了十多秒后慢慢地消失了。

解除心意防壁的爱丽丝，想要回头对帮助了自己的人道谢。但在开口前，后面站着的穿黑衣的人影突然摇晃，向前倾斜了。

「桐人！」

一边叫着，一边立刻抓住桐人的左腕。右腕也有伊迪丝支撑着。

遵守了和法那提欧的约定、在零点之前回来的桐人，只在一瞬间把全部体重压在了两人身上，接着抬起身子。

「抱歉，久等了」

用嘶哑的声音向爱丽丝道歉，接着将视线投向了右边。

「............那个......」

和歪着头的桐人一样的惊讶，伊迪丝也说了：

「你，是谁？」

「我是桐人」

「那个衣服，是加尔米耶缝制的骑士服吧。你是整合骑士吗？」

「加尔米耶……是谁？话说回来，你是……？」

对不得要领地进行对话的两人，法那提欧插嘴了：

「桐人、伊迪丝，之后会好好介绍的，现在先想想那个该怎么办」

因为这句话，爱丽丝再次抬头望向了天空。

楔形机龙仍然处在抓不住的距离，考虑到机龙在云上、以及神圣力枯竭区域的半径约1.5Kilol的话，楔形机龙应该距离这里有2Kilol左右。然而，却比右手的食指还要大，只能认为楔形机龙的全长超过了300Mel。与其相比，全长40Mel的アーヴス级机龙都是小型机了，真是难以相信的规模。

当然，装甲也一定很厚吧，至于总重量，连估算都不可能。说到底这边的心意和术式也碰不到那边，真的有可以解决的方法吗。

站着的爱丽丝的耳边，传来了舒缓的钟声。一天之中最安静的旋律奏响了——是零点的钟声。

虽然零点是皇帝阿格马尔宣告的时间限制，但爱丽丝她们已经将两架アーヴス级机龙给强制着陆了，头顶上的超大型机龙也投下了火球爆弹，所以已经没有对话的余地了……虽然这么想，但是。

超大型机龙的下腹放射出了几条白色光线，白色光线重合描绘出了巨大的立体影像。出现的仍然是皇帝阿格马尔・威斯达尔斯6世。看来皇帝不是在紧急降落的机龙里，而似乎是乘坐在潜藏于超高度黑暗中的超大型机龙中。虽然法那提欧的右腕抽搐了一下，但即使是天穿剑的激光也够不到2Kilol外的上空。

皇帝从高处睥睨着爱丽丝她们，静静的开口了：

『将余的亲卫机全部击退的事，就表扬一下你们吧』

刚一听到如同隆隆雷声一样的声音的时候，爱丽丝和法那提欧支撑着的桐人用嘶哑的声音狠骂道：

「真敢这么说啊，明明是自己发出的突击命令」

这句话应该传不到皇帝那里，皇帝继续用高傲的语气说着话：

『但是，アーヴス级就如此手忙脚乱的话，那恐怕是伤不到这架“Principia（プリンキピア）”的哦。而且余之温情也快消失了。在被猛火烧尽的数秒内，极力后悔自己的愚蠢就好』

嘲笑似地抬起细细的胡子，皇帝的立体影像融入到夜空中消失了。接着，桐人用低沉的声音说道：

「Principia……是『原理』吗。是对抗公理教会才这么命名的吧，到底是谁……」

虽然伊迪丝和法那提欧露出了惊讶的表情，但爱丽丝能理解桐人说的话。

Under world中用的人界语是现实世界的日语，而神圣语则是英语，但现实世界还存在许多其他的语言，据说达到了五千以上。虽然爱丽丝现在正在学英语和德语，但「Principia」这个单词恐怕是大多数欧洲语言的祖先——拉丁语中的单词吧。不用说，Under world中是不会用拉丁语的。

也就是说桐人考虑的是，到底是谁教给了皇帝一派意思为「原理」的拉丁语单词。

而且，教这个的说不定就是菊冈拜托桐人调查的、来自现实世界的侵入者。如果是这样的话，侵入者就在皇帝的近处……说不定现在就和皇帝一起在超大型机龙里——

爱丽丝正准备把瞬间的推测传达给桐人。

但是在开口前，上空再次闪耀着红光。

超大型机龙开始准备第二次的火球攻击了。但是跟第一次发射时的样子不太一样。虽然发光的地方没有变，但初期状态的亮度完全不同，而且明明是发射前，却已经听到了高昂的共鸣音。

「……到底，将多少热素……」

面对如此呢喃的法那提欧，桐人用更加沙哑的声音回答：

「一千个。」

「一……千！」

这次换成伊迪丝发出叫声，桐人看着她点头：

「嗯，那个机龙虽然储存了六千个左右的热素，但那不是飞行用的。现在，其中的一千个正在阶段性加压。距离发射大概还有五分钟。」

「五分钟……」

爱丽丝几乎不出声地重复了一遍，然后再次抬头仰望上空的Principia。

从炮口露出来的热素光芒，将机龙的地面照得通红。细长的楔形中央，似乎纵向排列着两个巨大的纹章。上面的纹章图案是盾与飞龙——是过去存在的威斯达拉斯西帝国的纹章。然后下面的纹章图案是，八根锐利的纺锤呈放射状排列的八芒星。不论是现在还是两百年前都没见过。

红光逐渐增强。已经到了眼睛直视会感到疼痛的程度，如果这个再持续三分钟会怎么样呢。

有三分钟的话，完全可以联络赛尔卡和艾尔莉，和她们一起到大圣堂外避难。不论是法那提欧还是伊迪丝，恐怕连桐人都想过这个选择，但谁都没有说过要逃跑。将冻结骑士们舍弃，独自逃跑之类的没有讨论的价值，在场的全员都是这么想的吧。

虽然赛尔卡她们正在九十九层制作骑士们的解冻药，但在这么短的时间里制作完供两三人用的就已经是竭尽全力了吧。在没办法攻击距离这里2Kilol远的Principia的前提下，能做的只有防御。也就是说，无论如何也要将一千个热素压缩成的巨大火球给阻挡下来或者让它偏转方向……但是找不到偏转的方法。

从原理上来说，只要用一千个冻素做成盾牌就能和巨大火球相抵消。但现在，大圣堂周边的神圣力完全枯竭了，在完全没有补给手段的前提下，别说一千个冻素了，生成十个冻素都没有把握。又变成了不得不依赖心意的状况了，但不仅是爱丽丝她们，桐人似乎也到极限了。

「……呐，法那提欧。」

支撑着桐人右腕的伊迪丝，快速地看了背后的圆形堂说：

「在这种状态下，Administrator大人还没有醒来……难道，猊下已经……」

「…………」

被问到的法那提欧一瞬间低下头，接着像是下定决心一样挺直了背。

但是在副骑士长开口前的瞬间——

响起了两个重叠的忙碌脚步声。接着是紧张的叫声：

「姐姐大人！」

爱丽丝急忙想要回头，但因为右手支撑着桐人所以只能侧着身子。察觉到的桐人说道「我没事」，于是爱丽丝对桐人点头后就将手拿开，重新将身体转过去。

从延伸到塔内的开口处内，飞奔出了两个人影。虽然屋顶因为停电的原因而黑漆漆的，但脱下了长袍的赛尔卡、和抱着纳兹的艾尔莉的身影还是一目了然的。开口处的附近，也有和桐人一起转移到基地的蒂洁和罗妮耶的身影。

注视着飞奔而来的最爱的妹妹的时候，爱丽丝的脑中浮现出了「说不定这会成为最后的接触」的想法。虽然即使爱丽丝在这里死去，也不会影响到在拉斯六本木支部的机械身体里的光立方，但恐怕Unit ID会失效，因此无法再潜行到Under world中。

明明好不容易才再次相见，如果接着就见不到的话，难道不是很悲伤吗，但一定能忍受住的。如果将其作为救了赛尔卡她们的代价的话。

压抑住想要紧紧抱住跑到眼前的妹妹的想法，取而代之的是深深地吸了一口气，爱丽丝开始说道：

「赛尔卡，好好听着。这个地方马上就要落下来威力有一千个热素的火焰弹。你和艾尔莉，用飞翔盘逃出去吧。」

「怎么可能丢下姐姐大人你们而逃走呢！」

拒绝了爱丽丝的恳求后，赛尔卡用紧张的语调滔滔不绝道：

「比起那个，先好好听着。因为刚才机龙的冲撞，大圣堂的最上位命令解除了。」

「最……最上位？」

「详细的由艾尔莉说明！」

按着赛尔卡的背的艾尔莉，像是打了个趔趄一样走到前面来。手臂中抱着的长耳湿地鼠纳兹，在这个状况下也依然惬意的睡着。

艾尔莉迅速地行了一礼，接着用比平时快两成左右的语气开始说：

「因为没有时间了所以就简洁的说明。刚才，因为中央大圣堂的天命减少到了规定的数值，所以最上位的系统管理命令解除了。」

「那个是，和刚才你发动的『Emergency Mode』是不一样的吧？」

面对不由得插嘴的爱丽丝，艾尔莉快速地点了点头。

「是的，Emergency Mode能做的只有展开防护壁和强化修复机能，最上位命令则在包含了以上能力的同时，还能使用攻击机能和退避机能。」

「攻击机能……使用那个的话，能将那架超大型机龙击退吗？」

「大概可以。但是，因为无法调整攻击威力，可以预料击坠会给圣托利亚造成极大的损伤。」

「…………」

和法那提欧她们对视后，同时摇了摇头。明明细心地注意不击坠亚多米尼史特蕾达级的机龙，怎么可能反而让接近亚多米尼史特蕾达十倍大小的Principia坠落到市区呢。

「不能攻击。退避机能可以让大圣堂内的所有人退避吗？包括冻结中的骑士和飞龙们吗？」

「是的，可以。」

「…………」

再次说不出话来。退避机能大概是在塔内制作传送门的机能吧，但先不论骑士们，石化的巨大飞龙应该怎么通过传送门？

不，现在没有问这问那的余裕了。既然一直守护着大圣堂的艾尔莉说能做到，那就只需要相信她就可以了。

似乎得出了相同结论的法那提欧，代替爱丽丝下达了指示：

「艾尔莉，现在立刻发动退避机能。距离火焰弹发射剩下不到三分钟了。」

「知道了。」

艾尔莉把抱着的纳兹托付给赛尔卡，接着稍微张开双手并向前伸出。毫不犹豫地吸了一口气，用坚定的声音——

「System call！Activate supreme system supervisor order！」

buunn……伴随着低沉的振动声，出现了闪耀着蓝紫色光芒的巨大视窗。

和爱丽丝在Under world见过的视窗有着完全不同的设计。不论是文字还是数字都不存在，像是纹章的图片占满了视窗。纵向排列的两把剑，以及将四周包围的蔷薇和金木樨的花朵……是星王的纹章。

菱形纹章下方排列着三个四边形框，但框里面是空的。艾尔莉将视窗固定在空中，接着后退两步说道：

「最上位系统管理命令……别名『SSS（triple S） Order』，需要桐人大人、亚丝娜大人以及一位骑士认证才能解放所有机能。请把手掌放在下面的框上，没有规定顺序。」

「……但是，亚丝娜还没……」

刚一听到爱丽丝说话，艾尔莉就像被弹起来一样抬起头来，看见在有些距离外站着的伊迪丝 Synthesis Ten后。惊讶地皱起眉头的同时瞪大了双眼。

「咦……伊……伊迪丝大人？」

「是的呢。你是升降士酱吧，好久不见。」

「好……好久不见。但是，为什么……」

看见艾尔莉打从心底感到惊讶的模样，爱丽丝有了些推测。

艾尔莉大概因为屋顶很暗而把伊迪丝误认为亚丝娜了。这么说来，让伊迪丝觉醒的不是赛尔卡她们。只觉醒一个冻结骑士是不可能的，到底是谁，怎么做到的——

不对，现在更重要的是……

「艾尔莉，只有桐人和骑士两个人不能认证吗？」

法那提欧比爱丽丝更早这么问。但是，艾尔莉迅速摇了摇头。

「桐人大人和亚丝娜大人两位是必要的。」

「…………」

爱丽丝抿着嘴唇看向天空。

Principia的热素炮发出令人联想到沸腾熔岩的灿烂光芒。距离压缩了一千个热素的烈火倾注下来，还有不到两分钟。

虽然桐人向亚丝娜传达了救援邀请，但从她家到拉斯六本木支部的直线距离有7Kilol、不对，有7千米以上。光是移动就要二十分钟，再加上准备的时间的话，花上好几个二十分钟也不奇怪。

这么说来，住在距离六本木支部30千米的桐人不可能比亚丝娜还要早潜行。这点稍后再问就可以了。虽然好不容易解除的最上位命令无法使用实在可惜，但现在必须绞尽脑汁思考其他对策。

爱丽丝思考着乘坐飞翔盘飞行，只身突击Principia并舍命破坏热素炮的事……就在这个时候。

突然，至今为止一直保持沉默的桐人，用瞬间移动般的势头跑向了楼梯的入口。当然不是逃跑，桐人在楼梯开口处停下并伸出右手，发动了心意之手。{译：老婆雷达发动了 笑}

「咔啊啊！？」

和悲鸣一起，和字面意思一样飞出屋顶的是——穿着和爱丽丝相同机士团制服的栗色头发的女性。

「……亚丝娜！」

爱丽丝大喊的时候，桐人已经把亚丝娜抱在怀里了。停下悲鸣的亚丝娜，盯着桐人发出了高亢的声音：

「欸欸……桐、桐人君！？为什么在这里……！？」

「等等再说明！」

桐人接着猛冲（dash）回来，在窗口面前停下并喊道：

「亚丝娜，下面的四角框，随便哪个都行，用手碰一下！」

虽然亚丝娜处在不知道发生了什么的情况下，但她从桐人的表情中看出了紧迫性，于是什么也不问就把右手伸了出去。放到了右边的框上，bunn……响起了很短的振动音，四角框隐约发出了青紫色的光。

接着，桐人触碰了左侧的框后就迅速退下。作为交换而向前走的爱丽丝，用右手敲击中间的框后，所有的框发出炫目的闪光就消失了。

纹章的中央——被两把剑包围的三个「S」，发出pasi、pasi、pasi的干脆声音浮上来了。

「还剩下一分钟！」

法那提欧喊着。

在急速后退的爱丽丝面前，艾尔莉飞奔过去。窗口上的纹章消失了，取而代之的是好几个子窗口。

「佩特拉斯，可以开始了吗？」

谁？

几乎没有去想的时间，展开的子窗口之一就响起了不太清楚的低沉声音。

『全部引擎燃料罐，检查完成。随时可以出发。』

「了解，开始倒数（countdown）。」

艾尔莉用力敲击中央的子窗口的同时，画面就出现了【20】的数字，接着马上变成了【19】。

「喂……喂，引擎在哪里……」

面对桐人的提问，艾尔莉用不容分说的语调打断了他。

「桐人大人，请把在场的全员用心意固定在地板上！」

「固、固定？」

即使发出奇怪的声音，桐人也依然张开了双手。爱丽丝的下半身随即被不可视的垫子（cushion）给包住了。

随着窗口的数字减少，不知为何脚下传来了gongongon……像是地鸣一样的声音，大理石地板也微微震动着。

距离火焰弹发射还剩三十秒。窗口上的倒数还剩下五秒。

事已至此，爱丽丝终于明白了。艾尔莉所说的退避机能，并不是制作传送门，恐怕是将中央大圣堂本身——

「紧急退避序列，开始第一阶段！三、二、一……发射（lift off）！」

艾尔莉大喊的同时，倒数归零了。

地鸣声急剧地增强了，大圣堂的广大用地被照得通红。大圣堂哔哩哔哩的震动起来，全身的重量一口气增加了。

这就是，现实世界中说的重力加速度吧。

换言之，中央大圣堂离开了地面，正像是火箭一样急速上升。隔着大圣堂的压檐墙俯视圣托利亚市，眼看着在停电范围外的街道的灯光变小了。

「欸……欸，飞起来了？」

对着发出声音的亚丝娜，艾尔莉用十分昂扬的语气回答道：

「是的！在地下十层设置的36座大型热素引擎，将会让大圣堂上升到30000Mel！」

「30000Mel~~？」

这么大喊的是伊迪丝。对于来自没有机龙的时代的她来说，这是超越想象的高度吧。虽然这么说，但爱丽丝对于30000Mel的高度，除了搭乘丝缇卡的机龙从宇宙回来时之外也没有经验。再加上肉身站在不管是天花板还是墙壁都没有的屋顶上，要是掉下去绝对救不了。

而且，上升就意味着会靠近在2000Mel高度滞空的Principia。

爱丽丝一边忍耐着耳边强烈加速度的震耳欲聋的轰鸣，一边环顾四周，不管是法那提欧还是桐人，蒂洁和罗妮耶也都死死的注视着正上方。爱丽丝也抬起头，也盯着黑漆漆的楔形影子。

影子比在地面上的时候大了两倍左右，影子前端的发射前的热素炮，发出了像是地狱里煮罪人的锅一样的光。接近到这个地步，终于可以看清热素炮的形状了。炮并不是一个洞，而是从半球形的炮塔中伸出的粗短的炮身，可动的炮身，依然在瞄准着上升的大圣堂。

「不……不会撞上吗！」

赛尔卡的喊声，被艾尔莉用冷静的声音接上了：

「没问题，预定在敌机右舷的20Mel处通过。」

「20Mel~~！」

伊迪丝再次喊叫着。这是理所当然的——Principia全长400Mel，而中央大圣堂全高500Mel，这个规模的物体高速地擦肩而过，区区20Mel的空隙几乎等同于没有。

但是，达36座之多的热素引擎集群发出的咆哮无止境的高涨着，将白色的巨塔推上了太空。Principia的影子将整个天空都覆盖上了，从炮口漏出的光焰灼烧着眼睛的深处。

大圣堂的前端，也就是圆形堂的半圆形屋顶，将要和Principia的底面发生冲突——爱丽丝如此确信的瞬间。

持续追踪着瞄准大圣堂的炮身，发出重重的声音到达了可动范围的极限。

咕哦！空气震动着，塔右侧的咫尺处，和Principia如同刀一样的右舷擦身而过了。

和艾尔莉说的一样，空出来的间隔仅有20Mel，两个巨大的构造物就这么交错过去了。但大圣堂的下端，距离偏离热素炮的射程外，恐怕还有两三秒。要是在那时发射火焰弹的话，大圣堂可能在空中折成两半，最坏的情况下甚至会消失得无影无踪。

「要发射了！」

听见桐人的喊声的同时，将爱丽丝包住的透明心意垫也变硬了。

** 20

Mel的间隙被赤红的光填满了，像是无数的金属弦崩开一样，「磅！」发射声被轰响了。

胃的下面被比冻素还冷的颤栗贯穿了——

经过了像是永恒的一秒后，有谁……大概是蒂洁在大喊：

「打偏了！」

爱丽丝因为那句话而快速地转动头，看向了左侧的天空。漆黑的夜空中，赤红的大火球正飞翔着。明明距离屋顶上的爱丽丝应该已经有1Kilol了，露出的肌肤却还是能感到火焰弹的热量。

拖着红色轨迹远去的火球，大约五秒钟后无法维持球状，一千个热素的能量在什么都没有的空中全部解放了。

作为单一的爆发来说，远远超过了爱丽丝在Under world目击过的同样现象。可以称之为小型太阳的火焰块，在2000Mel的高空中照亮了地面，过了一会，惊人的轰鸣声和冲击波将大圣堂哔哩哔哩地震动着。地面上大概是被爆风往下刮的程度吧，但也可能出现果园的损失。

振动逐渐远去，爱丽丝将冰冷的空气深深地吸入到空空的肺中，然后再慢慢地吐出。同样做着深呼吸的伊迪丝，用沙哑的声音说道：

「……那种东西，要是命中了大圣堂的话，Prin什么的也会被爆炸卷进去吧……」

「不……Principia的装甲完全隔绝了我的心意。大概不只是厚的原因，装甲也可能被强化成了和心意兵器类似的构造。」

如此回应的桐人的声音中，似乎带了些自责的语气，爱丽丝不由得注视着他的侧脸。正想要开口问在基地发生了什么的时候，艾尔莉说话了：

「已到达高度5000Mel，一分钟后脱离大气层。桐人大人，非常抱歉，（请生成）光素防壁……」

「不，那由我们来。」

发言的是罗妮耶。罗妮耶和缇洁对视后，无咏唱生成了十个光素。然后将其变成了半球状的薄膜，把在屋顶上的所有人包裹起来。

急剧下降的气温略微上升了。因为在Under world的宇宙空间中虽然可以呼吸，但却非常冷，不采取任何对策的话就会被冻住。当然，塔内的温度应该也很低，石化冻结中的骑士们和飞龙们大概没有问题，但如果有肉身的人类的话就可能会冻死。

事到如今才开始担心的爱丽丝向艾尔莉问道：

「大圣堂的下层有人吗？像是星界统一会议的职员，或者警备员之类的……」

「不，在大圣堂工作的所有人，有着『下午六点下班』的规则。即使是赫伦兹科长也不例外。」

「这……这样啊……」

要是让在零点后工作也不罕见的神代博士和比嘉主任听到的话，究竟会说什么呢……想到这里之后，爱丽丝突然增加了一个疑问：

「但是，刚才联络的人是？那个……」

「佩特拉斯不是统一会议的职员。他过去担任着大圣堂地下监狱的看守这一职务。」

「咦咦！」

桐人发出了惊讶的声音。

爱丽丝也跟他一样震惊。虽然中央圣堂的地下存在过监狱这件事，以及常驻在那里的魁梧看守都还有记忆，但没想到他在两百年后的现在还健在。看来他似乎由监狱看守调职成了热素引擎的保护人，依然继续在地下生活的样子。

把将在北圣托利亚修剑学院引起伤害事件的桐人和尤吉欧押送交给地下监狱的看守，虽然是遥远的过去，但就好像是昨天发生的事一样。如果没引发事件的话，他们两人一定会以修剑学院的第一名和第二名的身份毕业，四帝国统一大会也一定会胜出，然后以见识骑士而不是罪人的身份，踏入中央大圣堂的门吧。

如果是那样的话……一切都会不一样吧。不论是爱丽丝反叛公理教会，还是尤吉欧丧命，都不会发生吧……

甩开刹那间的念头，爱丽丝再次对艾尔莉问道：

「那位佩特拉斯，在大气层外也没问题吗？」

「是的，地下十层的引擎室施加了大气层外飞行的防护，与其说冷，倒不如说因为无法排除引擎的热量而很热。」

艾尔莉回答完后，就转过身子看向窗户，继续说道：

「脱离大气层，完成。全引擎停止燃烧，进入惯性飞行。」

用纤细的手指操作一个子视窗后，热素引擎集群的驱动声渐渐变低，最后中断了。

将爱丽丝的身体压在地板上的重力加速度消失了，桐人的心意垫接着也消失了。身体变得像骗人一样的轻盈之后，接着长靴的靴底也离开了地板。重力几乎不存在了。

「哇，这、这是怎么回事」

是踢了地板吗，法那提欧快速地将漂起来的伊迪丝抓住了。赛尔卡、蒂洁和罗妮耶大概有过无重力的经验，所有并没有表现出慌张来。

最后看到一直站着的亚丝娜，榛色的眼瞳正注视着头顶的夜空，不对，正注视着头顶的宇宙空间。因为亚丝娜的影响而抬头的时候，因为数不清的星星点缀着的天穹而惊讶到了，吞下了一口气。现实世界的东京几乎看不到星星，像这样的星空有好久没见了。

因为Under world是假想世界，所以那些星星也可能只是单纯的背景图片，但过去被称为月亮的星星，在乘坐机龙到访后也发现是盛开着黄色花草的行星。这么说的话，点缀在夜空中的几万、几十万星星，如果实际去看看的话……

切断奇怪方向的思考，爱丽丝慎重地踢了地板，往亚丝娜的方向移动并小声说：

「亚丝娜，你能来真的太感谢了。这个时间从家里移动到拉斯很费劲吧」

将脸转回来的亚丝娜，在看到爱丽丝后张开双手，轻轻地拥抱爱丽丝并低语到：

「完全没问题哟。爱丽丝和大家没事真的太好了……我除了将手放到窗口上之外就没干别的了」

「不，要是亚丝娜没来的话，不管是大圣堂还是我们，都会被热素炮烧成黑炭吧」

作为回应，爱丽丝也紧紧的抱住亚丝娜。不知为什么在感受到和现实世界一模一样的香气，和隐约的温暖后，身体内的紧张感缓和了不少。这位亚丝娜，拥有的让人安心的力量已经是魔法的领域了……一边这么想，一边拿开手臂，轻轻地吐了一口气。

艾尔莉所说的「紧急退避」，虽然没想到居然是让中央大圣堂本身像火箭一样飞起来，但总之先从Principia的威胁下逃离了。但Principia大概也是能在宇宙飞行的机龙。执念十分深的皇帝阿格马尔，放弃消灭整合骑士是怎么也不可能的。

艾尔莉说过，大圣堂要上升到30000Mel，也就是30Kilol的高度。虽然是不得了的高度，但距离行星卡尔迪纳和伴星阿多米娜之间的50万Kilol还差得远。对从阿多米娜飞奔而来的Principia来说，30Kilol不过只是散步罢了。

如果Principia追到重力圈之外的话，就不用担心它坠落到圣托利亚了，所以可以尽情攻击，但看见之前的巨大爆炸后，实在不认为正面对射能赢。还是说，解放「SSS（triple S） Order」的所谓攻击机能，具备比Principia热素炮还要大的威力和射程呢。

就这么怀抱着数个疑问，爱丽丝看着操作窗口的艾尔莉那小小的后背。

艾欧莱恩将艾尔莉称为，整合机士团第一机龙工厂的初代厂长，艾尔莉・特鲁姆大人。过去被称为「升降士」的少女，一定在星王与星王妃任职的两百年间，积累了众多知识与经验吧。无论是哪一位骑士、术士都无法企及……或许，甚至比最高祭司Administrator还要…………

「方位、角度、速度正常。紧急退避序列（sequence），第二阶段（stage）开始」

艾尔莉的平静声音，在光素防壁内扩散开来。在大家无言地注视下，艾尔莉进一步操作窗口并说道：

「佩特拉斯，距离逆喷射还有一分钟」

『展开机构、燃料罐残量、均正常』

接着是不太清楚的声音。看守过去戴着完全包住头部的金属面具，现在说不定还在戴着相同的东西。

「了解。逆喷射引擎，开始展开」

随着艾尔莉的手指跃动，大圣堂的下部响起了机械声。虽然不知道大圣堂基部发生了什么，但恐怕是在大圣堂的外侧展开了几座热素引擎，通过逆向喷射来减慢速度吧。

「引擎展开完成。准备好了」

刚一听到佩特拉斯的报告，艾尔莉就回过头来。桐人什么也没说就竖起右手的大拇指，点了点头。

「固定就交给我吧」

「麻烦了，桐人大人」

在对话之后，再次用心意垫将爱丽丝的下半身包入。如果不是这种状况的话，即使是心意之手，将下半身紧紧抓住也不是能泰然处之的事，但现在涌上来的只有感谢的心情。

「很累了吧，非常感谢，桐人」

听到爱丽丝说话，桐人回过头后再次竖起大拇指笑了笑。但桐人的表情中果然还是有消耗和焦躁的影子。

仔细想想的话，桐人只和蒂洁和罗妮耶一起从宇宙军基地回来这件事就不太自然。袭击基地的大型机龙的目的是捕获或杀害整合机士团长艾欧莱恩，不和护卫艾欧莱恩的罗兰涅和丝缇卡一起回来是很奇怪的。

在迷茫着到底要不要问基地里发生了什么的时候，艾尔莉回头大喊道：

「逆喷射还有十秒！准备应对冲击！」

全员点头后将身体靠在心意垫上。窗口上的数字【10】刚到零的时候——

比起离地时要小——但还是响起了让大圣堂微微震动的轰鸣声，爱丽丝的身体浮了起来。如果心意垫没有将身体固定在地板上的话，大概就会飞向宇宙空间了吧。

逆喷射持续了十秒以上，没有预告就停下了。

「喷射结束，速度正常……第三阶段，开始」

因艾尔莉的报告，爱丽丝眨了眨眼。如果升空和加速是第一阶段，减速和停止是第二阶段的话，那紧急退避不是已经结束了吗。

——不，大圣堂还没有停下。一边维持着比逆喷射前要慢的速度，一边继续上升着。

艾尔莉一瞬间抬头看了前进方向，然后展开了新的子窗口并呼叫道：

「这边是，White Cosmos 01。Black Lotus 02，可以听到吗」

不久后——

『……这边是，Black Lotus 02。传声感度良好哟，艾尔莉。没想到，这个时刻真的会到来呐』

是平静的，并略带沙哑（husky）的女性声音。虽然感觉像是在哪里听过，但想不起是谁的声音来。

在歪头的爱丽丝的斜右前方，桐人微微地将身体绷紧了。似乎知道声音的主人是谁，但还来不及提问，对话就继续了。

「预定在三分钟后对接。请解除隐蔽模式」

『了解。Black Lotus 02，解除隐蔽』

因为亚丝娜再次抬头，爱丽丝也跟着仰望大圣堂的行进方向。

和之前一样，只有漫天的星星而已……不，那个是。

星空的一个角落，正在摇晃着青紫色的光。波动起伏的光环，宛如心跳一样不断地扩大，随后渐渐淡去。每当重复着鼓动的时候，就有什么……令人不敢相信的巨大物体显现出被隐藏的身姿。

「……莲花……？」

亚丝娜喃喃自语道。

确实是这样，椭圆形的花瓣向八方展开，是在宇宙中盛开的莲花。当然是人造的，基部是稍微切掉正方形角的八角形。在中间，开了同样是正方形的洞。从「对接」这个词来推测，中央大圣堂大概是要正好的嵌入那个洞，和莲花一体化吧。

也就是说，洞的边长和大圣堂一样是50Mel。基部的边长大概有洞的五倍，因此是大约250Mel的四方形吧。再加上一朵花瓣有基部两倍的长度，所以计算出莲花全体长1200Mel左右。

「那个……究竟是什么……？」

爱丽丝忍不住叫出声来，艾尔莉只是稍微回头说道：

「黑莲二型宇宙要塞，代号（call sign）为『Black Lotus 02』。」

「………………」

全员暂时说不出话来。是为了什么而制造的，是怎么运到宇宙的，一型又是什么样的等等疑问在爱丽丝的脑中盘旋，但也不知道该如何说起。

终于——已经忍耐到极限的法那提欧瞪着桐人，大喊道：

「陛下！！你是什么时候造出来那种东西的！」

「我、我不知道，不知道啊！」

桐人悲痛的抗辩，被无限的星空吸入了。

** 7

「呜哇……好……好惊人的景色呐……」

站在旁边的莉兹贝特，一边深深吸气一边呢喃：

「确实呐……」

西莉卡也深深点头，然后往前走一步。刚一往前走，莉兹贝特就抓住了西莉卡皮革盔甲的皮带（strap）。

「等等，危险！」

「又不是小孩子了……」

不由得苦笑之后，老实地回到了原处。

两人站着的地方再往前走两米，岩石地面就突然垂直切断，暴露出锐利的山脊棱线。其下方是高度200米的断崖，在不能在空中飞行的Unital ring里，掉下去的话免不了即死。

但是，因为断崖南边的景色实在过于壮观，光是看着就忘记了摔落死亡的恐惧。近景是郁郁葱葱的大森林，以及在中央与右边蜿蜒流淌的大河。远景是辽阔的大草原，和在大草原一角耸立的异常险峻的岩山。再加上，静静地照着万物的苍白满月——

原野（field）的规模感和阿尔普海姆没有什么不同，那个世界也存在高低差200米的悬崖。说到底，西莉卡她们生活与冒险的据点——新生艾恩葛朗特，可是漂浮在10000米高的天空中。

然而，注视着的Unital ring世界的风景，却袭来在ALO没有体会过的，像是把灵魂吸进去的感觉。并非单纯的视觉分辨率高……轻抚脸颊的微风触感、土壤与草以及水的香气、从远方传来的野兽叫声，输入五感的情报具备压倒性的真实感（reality），感觉到宛如在真正的异世界里站着一样。如此的异域感，说不定是自从被SAO囚禁以来第一次体会到。

不，正确来说是第二次。想忘也忘不掉今年七月七日的早晨，接受结衣的邀请而潜入的真正异世界——Under world。西莉卡她们虽然出现在被称为「黑暗领域（Dark territory）」的不毛荒野，但是却因为仿佛将所有沙粒都再现的高精细度而感到惊愕。

在现实世界，从那之后已经过了快三个月。西莉卡虽然不清楚异界战争的全貌，但听说在那场血流成河的战争之后，时间加速的Under world似乎仍持续着动乱。在没有登出（log out）的桐人和亚丝娜的尽力下，终于迎来了和平的时代，虽然认为至今也保持着和平……

西莉卡回头望向北方。{译：以下内容请结合卷首地图来看}

左前方，有着崩塌一半的石造亭子——是连接上下断崖，高大的地下城出口。

从小屋开始，隐约可见的小径贯穿荒地，往北延伸。沿着小径跑的话，就能碰上虽然比不上下面的马鲁巴河，但依然算是很大的河川。河川的对岸有着小规模的村庄废墟，除了莉兹贝特以外的同伴们——诗乃、克莱因、莉法、结衣、霍格、萨利翁、西西、弗利司柯尔以及宠物阿蜥和小黑，还有登出的桐人与亚丝娜也在那里。

西莉卡和莉兹贝特特意渡过河，跑了2千米回到这个地方，是为了重新侦察从小屋到废墟的道路（route）。

虽然还不清楚总体情况，但Unital ring似乎是三段原野叠加而成的构造。ALO组的起始地点是位于第一段原野南端的斯提斯遗迹。从那里往北走25千米就是「原桐人镇」的「拉斯纳里奥」。再往北走3千米，耸立着高度200米的断崖——「终焉之壁」。从阶层地下城登上断崖的地方，也就是西莉卡她们现在站着的地方，是第二阶层的开始。

Unital ring所有玩家的目标，是比任何人都快地到达还没看见的第三阶层的中心——「极光指示之地」。当然，西莉卡她们的目标也是第一名，但这个世界没有天真到只要突破乌云就能到达终点。

这个世界存在饥饿值（SP），口渴值（TP），以及充实到异常的技能树，正如以上所见，Unital ring的本质是生存（survival）RPG。也就是说在这个世界里，做好补给是比什么都重要的。因此登上第二阶层后首先要考虑的，就是建立新的据点，以及确保从大本营拉斯纳里奥到这里的补给线。不断往返于怪物横行的阶层地下城，效率实在太低下了。

「从这里到废墟的小路上，几乎不会涌出怪物哦。」

西莉卡一边抚摸左肩上快睡着的毕娜，一边回应莉兹贝特：

「是这样啊……果然，第二据点还是在那个废墟里建造比较好。」

「也能利用原本的建筑。剩下来的就是怎么跟拉斯纳里奥连起来呢～不能在悬崖上造楼梯吗～」

「桐人桑说，有妨碍建造楼梯的机关（gimmick）所以不能那么做呐……好像是悬崖的半路上，有非常强的怪物筑巢……」

「啊——这样啊。毕竟只是建造房屋就会有熊或者野猪袭击过来呐……唔——嗯……」

哼哼了好一阵子后，莉兹贝特再次转过身体面对悬崖。她继续发出哼声，并且开始快步走。西莉卡因此慌张地大喊：

「等……等等！说危险的不是莉兹小姐吗！」

「哎……啊，抱歉抱歉。」

莉兹贝特吐了一下舌头，打开了仓库（storage）。从中取出的是，捆在棒子上的绳子。

刚转移到这个世界的时候，用的还是随处可见的叫做天根草的植物的叶子制成的「粗糙的细绳」但拉斯纳里奥的商业区有了发展的现在，用的是三条亚麻纤维制成的「坚固的麻绳」，换言之就是可以在巴欣族经营的店中可以买到的亚麻绳（linen rope）。

莉兹贝特将比天根草绳子要强韧的多的亚麻绳解开，把一端系在附近生长的灌木的树干上，另一端穿过自己的皮带后，将绳子扔向了西莉卡。

「你也把绳子穿过皮带，然后系在那棵树上。」

「……知道了。」

按照莉兹贝特说的做，并保险起见用力拉了拉绳子。因为是假想世界，所以只要绳子、皮带和灌木的耐久没有降到零就没问题，虽然理解这点，但因为亚麻的扎手感太真实了，所以还是忍不住去确认了。

「已经系好了……难道，不是在悬崖上下降吗？」

「不是不是！如果要下降的话，绳子是完全不够的吧。」

莉兹贝特说出十分有道理的话，接着靠近悬崖边，趴下身子，只将头伸出悬崖边，窥视着正下方。

不会只是想感受惊险（thrill）吧……西莉卡一边这么想，一边将毕娜放到地上，也在莉兹贝特旁边趴下了。一步步的往前爬，同样地看向了断崖的下方。

刚一看到下面，就袭来了轻轻的头晕。说起200米的话，已经和东京都的瞭望室差不多高了。即使没有路灯，也靠着对于假想世界来说很亮的月光和夜视技能，清楚地看着下面的森林。

广大的杰鲁艾特里奥大森林的一角，拉斯纳里奥正发出温暖的柑橘色的光。将视线由拉斯纳里奥移动到正下方，将圆形的枝叶大大展开的漂亮的阔叶树进入了眼帘。在那棵树的树冠中的圆顶状空间中，有着叫「Gilnaris Hornet」的蜂型怪物做建造的巨大巢穴。明明这边有二十四人，却还是差点有牺牲者出现，因此从后来合流的桐人他们那里，听说巢穴中没有再次涌出蜂群时，从心底里松了一口气。

但是，也不能保证之后不会复活，圆顶再往内走的阶层地下城似乎也一直涌出着杂兵怪物，为了确保安定的补给线，需要构建一条迂回圆顶和地下城的路线。而且，西莉卡驯服的棘刺洞穴熊米夏的体格也无法通过地下城，如果要送到第二阶层的话，其他的移动手段是必要的。好不容易可以在UR里进行艾因格朗特和Alfheim都不允许的「自由建筑」，不活用那个是不可能的。

「悬崖几乎是垂直的，只要有材料的话好像就可以设置楼梯了呐……」

西莉卡喃喃自语道，莉兹贝特似乎点了点头。

「是吧——但是呢，你看，那边……看到了吗？」

莉兹贝特一边说话，一边又伸出身体15厘米左右，用手指着绝壁上的一点。

仔细想想的话，因为和莉兹贝特系在同一根绳子上，如果莉兹贝特滑落下去的话，自己也会被连带着……西莉卡一边这么想着，一边也稍微往前爬了爬，目不转睛地盯着莉兹指的方向看。

悬崖的半山腰，大约100米的高度上，有着饭团型的凹陷——似乎是这样。

凹陷的宽和高，都像是二层楼的房子。虽然不知道深度有多少，但从阴影的感觉来看，好像比宽高的长度还要深的样子。

「那么大的凹陷，为什么从下面往上看的时候没有注意到呢……」

西莉卡自言自语着，视野中的莉兹贝特的手指轻轻地动了一下。

「那个森林，树冠之间完全没有空隙。在森林里走的时候，几乎看不见悬崖，到了森林的边缘，又因为角度太陡而看不见吧。」

「原来如此……那么莉兹桑是怎么注意到的？」

「在爬地下城的楼梯时，好像听到了像是野兽的吼声。我还以为一定是BOSS的声音，但BOSS不是巨像吗？」

「欸，因为这个就认为悬崖外面有什么吗？」

「因为，就是这样吧。」

因为莉兹贝特的断言而感到哑然，但确实如此。在完全潜行之前的开放世界RPG里，「微弱的脚步声和低吟声」也是经典的提示与警告。既然听到了声音，那么发出声音的东西一定在附近。

「……桐人桑的推测，似乎是真的呢。在那个凹陷里潜伏着极强（ゲツツヨ）的怪物，攀登悬崖就会袭击过来……」

「问题是，怪物的探测范围有多大呢。」

「不是单纯的球形吧……这个悬崖往东西延伸了数百公里，所以一只怪物应该覆盖了相当大的范围。」

「爬到悬崖中间就会袭击过来吧——」

「要是有安全地去检查(check)的方法就好了……」

两人同时发出“唔姆”的声音思考着。

制作出这个游戏的某个人，说不定是不想让玩家简单的往来「终焉之壁」，让玩家在第二阶层再次从零开始建造据点。但是根据绑架结衣的「Apocalyptic Date」的兽人们所说，除了桐人小队之外，似乎就没有在距离悬崖仅仅几公里的地方建立大规模据点或者成功建立街道的势力。如果是这样的话，无论如何也要发挥这个优势（advantage）。

「至少，只是看到怪物的脸也好——」

「唔——嗯……」

西莉卡再次歪着头，同时不经意地打开仓库。用指尖滚动着从强制转换（convert）到现在的一周内不知不觉间积攒下来的道具。一半以上是石头和木头之类的素材类道具，第二多的是水和食物。曾经持有的几乎能够在ALO中开店的漂亮装备品一个也没有。

好像没有可以用的东西啊……一边这么想着，一边将物品栏变成按入手时间排序，并且滚动到最底部的时候。在细绳和小石头中，发现有一个「素烧的壶」孤零零地存在着，西莉卡将头歪了歪。

饮用水应该全部保存在拉斯纳里奥的小木屋制作的「素烧的壶」中，道具名也应该变成「装有水的素烧的壶」才对。虽然认为只是单纯的空壶，但那样的话道具名应该是「素烧的壶（空）」。

西莉卡一边慢慢后退一边抬起身子，点击壶的名字让其实体化。在窗口上出现的小壶，壶盖被像蜡一样的物质密封着。再次点击，看着浮现出的属性视窗。在耐久度的下面有着小小的说明文字——

【装着什么的素烧的壶。不打开盖子就不知道里面是什么】

「这是什么啊！」

西莉卡不由得叫了起来，莉兹贝特对此投向了惊讶的表情。

「西莉卡，那是什么？」

「就是不知道才叫的哟……既然这是按入手时间较早的顺序的话，入手的时间似乎是第一天」

「唔嗯……打开看看吧」

莉兹贝特轻松地说道，西莉卡则一下子用双手将壶递出。

「既然这样，那就请莉兹桑打开吧」

「为什么是我！？这是你的壶吧」

「就送给想知道里面装了什么的莉兹桑吧」

「哦，说了呐！就算里面装了宝石也全都是我的呐！」

莉兹贝特一边笑着，一边接过了壶。从皮带里将小刀——当然不是石器，而是自己做的钢铁制小刀——拔出，切入封印着壶盖的蜡。

刀尖绕了一圈，壶整体就发出了微弱的闪光（flash）。道具名应该也变了，但还是打开比较快。

莉兹贝特像是吊人胃口似的，慢慢地把小刀收回到刀鞘中，用指尖抓住了壶盖。再经过了大约三秒的焦灼时间，突然将壶盖拿起。刚一拿开壶盖——

「「好————臭！！」」

两人一起叫了起来。在附近的草上躺着的毕娜，也发出了「啾呸！」这种闻所未闻的声音。

真是可怕的味道。并不是单纯的恶臭和腐败味，而是将无数种气味成分凝缩到极限，应该说是超级浓厚的发酵臭，从鼻腔痛击到头顶。

「卓，卓是夏沫！」

莉兹贝特用不清晰的声喊叫着，西莉卡一边不用鼻子呼吸，一边叫着：

「略兹桑，钙，钙！」

「钙是……啊啊，壶盖吗」

即使莉兹贝特合上了壶盖，气味也依然顽强的继续抵抗夜风，大约十秒后才终于消失了。

数次重复着「斯——哈——」的深呼吸后，西莉卡再次伸出右手点击壶，呼出了属性视窗。和预想的一样，道具名已经变了。由【素烧的壶】变成了【装着完全熟成的五浦草汤的壶】。

「「完全熟成的五浦草汤……？」」

再次和莉兹贝特异口同声地叽咕着，然后面面相觑。说起五浦草的话，应该是在基约尔平原上生长的草的名字……不，还有一个名字。

「芋梗！」莉兹贝特喊道。

「芋荷杆！」西莉卡也喊道。然后两人近距离对视着。

据结衣所说，不管是芋梗还是芋荷杆，似乎都是芋茎——也就是芋属植物的茎的别名。在基约尔平原生活的叫做巴欣族的NPC们，爱吃的东西就是将五浦草编成绳状后煮成的料理，吃起来的口感和芋茎炖菜一模一样。西莉卡和莉兹贝特以及结衣，在第一天的晚上和巴欣族见面了，邀请到帐篷里，招待西莉卡她们的就是五浦草汤，西莉卡还多喝了一碗。虽然确实想再喝一次，但为什么要放到仓库里，而且还散发出这种可怕的味道呢。

一边扭头，一边读属性视窗的解说文本。

【密封在壶中，花费一周的时间发酵熟成的五浦草汤。成功率很低，大部分壶都会在熟成的过程中破裂。完全熟成的汤被巴欣族奉为最高级的美味，独自喝完一壶的人将被称为勇者】

「要是在仓库里破裂会怎么样呢？」

一边想象着那个惨状，一边颤抖着身体，西莉卡说道：

「虽然不知道五浦草汤的壶是怎么进到我的仓库中的，但似乎是花了一周的时间熟成的呢……不过仓库中的食物应该不会腐坏才对，所以熟成是指另一回事吗……」

「明明是最高级的美味，和『喝完就是勇者』之间不是很矛盾吗？」

莉兹贝特的疑问是理所当然的，但不向巴欣族打听是不会明白的。不管怎么样，既没有打算进行全部喝完挑战（challenge），再放回仓库也是敬谢不敏。

「莉兹桑，你要吃吗？」

姑且确认了一下，但因为莉兹贝特无言的激烈摇头，所以西莉卡拿起壶，放到了附近的岩石上。虽然不知道壶的耐久度能维持多久，但绝对不能说没有救了快要饿死的谁的可能性。

时间快要到零点了。虽然不能把悬崖中潜藏的怪物给引诱出来，但只是确认从亭子到废墟的路程是安全的就已经不错了。

「那么是时候……」

西莉卡咽下了想说的「回去了吧」。注视着刚放下的壶，然后将视线转到莉兹贝特身上：

「呐，莉兹桑。」

「果然还是要吃？」

「不吃！不是那样……我是想，要是把那个壶扔到凹陷处会怎么样？」

「…………」

暂时沉默之后，莉兹贝特说道：

「如果是有嗅觉的怪物的话，我认为会发火吧。」

「会爬到这里吗？」

「爬上来的话，把绳子切断跑到亭子里的楼梯上不就好了？再怎么说也不可能追到地下城里吧。」

「……就相信你了，莉兹桑！」

西莉卡一边微笑着，一边再次拿起了【装着完全熟成的五浦草汤的壶】。确认穿过皮带的安全绳结实地系在了灌木树干上后，慢慢地走到悬崖边并往下看。

问题是，凹陷的底面仅仅突出悬崖1米。虽然沿着悬崖扔下壶的话就能碰到突起，但要是瞄准过头了，就会碰到崖壁的凹凸处，随后就会破裂或者弹飞到突起之外吧。

将拿着壶的双臂伸出悬崖边，慎重地瞄准。要是一点点施加横向的力的话，就不知道飞到哪里了。为了让壶垂直落下，把神经集中到从双手传来的重量上，在感到均等了的瞬间轻轻地放开手。

刚一放开手，西莉卡的身体就摇摇晃晃地往前倾斜了。但是，背后的莉兹贝特和预想中一样拉住了安全绳，所以好不容易避免了摔死。

冒险是值得的，壶用完美的加速度进行直线运动，然后转瞬间在黑夜中消失了——大约4.5秒后，听到了「啪哩」的微弱破碎声。

和走过来的莉兹贝特一起，将鼻子抽动着。虽然认为实在不可能离着100米也能传过气味来，但那个难以言说的发酵臭还是随着上升气流微微地传来了。

不由得往后退了一步，在那时。

像是高速地挥舞着长皮带一样，异样的声音击打着耳朵。花了一些时间才注意到那是生物的咆哮。

和莉兹贝特对视后，战战兢兢地窥视悬崖下。

几乎同时，在悬崖半山腰上的凹陷里，飞奔出了一个漆黑的影子。

宽3米多，长则是接近两倍的6米左右。虽然不确定细节，但既不是野兽、也不是鸟、也不是龙（dragon）。简单的长椭圆形的身体两侧，看起来像是微微地起伏着。那是........脚。数十根又细又短的节肢长在身体侧面，但即使这么说也有50厘米了，节肢牢牢地抓着岩石的表面。整体的印象是，超巨大的海蟑螂{フナムシ 海蟑螂科是一种常见的岸栖甲壳类，平常绝少在海中活动，但遭遇危险会逃入海中。在全球广泛分布，可以吃 呕}或者鼠妇一样{ワラジムシ 等足目卷甲虫科卷甲虫属节肢动物 大伙应该都知道}。

巨大节肢动物，在凹陷——巢穴的几米上静止着，摇动了长长的触须。马上就感觉到了什么，然后吼出「biulululuuuu!」的奇怪声音，用和巨躯不相符的速度，沿着垂直的悬崖笔直地飞奔而来。

「......那个，是不是要来这里？」

西莉卡说道，而莉兹贝特则是「也许是」如此点头同意道，在两人中间的毕娜窥视悬崖下方之后，也发出了「啾依{译：原文 きゅいー}」的鸣叫声。

大概是因为熟成的五浦草汤的芳香造成了攻击判定，巨大海蟑螂的头上浮现出了深红的纺锤状光标。HP条和三天前进行殊死搏斗的超大型怪物“The Life Harvester”一样，都是三段，固有名称是【Genoligia】。ジェノリジア（jilenorijia）……大概是这么读，但不清楚是什么意思。

Genoligia一边簌簌地起伏着节肢，一边飞驰着，转眼间就跑完了一半的路程，然后继续往上爬。

「快逃吧！」

西莉卡大喊完就抱起毕娜。莉兹贝特似乎也没有异议，迅速拔出小刀切断安全绳。两人同时转身，冲刺到亭子——正要这么做的前一刻，像是涟漪一样的Genoligia的脚步声中断了。

维持向前倾的姿势，侧耳倾听着。但是，听到的只有夜风和周围的灌木摇晃的声音。

那家伙绝对是让我们疏忽大意，但其实已经到眼前了吧……虽然这么想，但西莉卡还是慢慢地靠近悬崖边，然后在一瞬间往下看了。

于是就看见了，Genoligia停在大约30米的下方，也就是高度170米左右，体长一半左右的触须在摇动着。从这个距离来看，月光把Genoligia的细节照的十分清楚。

全长6米的巨躯分成了无数个体节，脚的数量实在是数不清。圆圆的头部上排列着两个弯曲复眼以及四个单眼，从嘴里突出了像是液压剪切器一样的大颚。被那个大颚夹住的话，即使是有着厚装甲的独角仙人——扎利昂，也撑不了三秒就会被切成两半吧。

Genoligia明显感知到了西莉卡她们——不仅如此，还像是理解到西莉卡她们就是往巢穴扔下剧臭炸弹的罪魁祸首，但Genoligia并没有继续爬完剩下的30米。几秒后，像是不满一样，改变身体的方向，慢慢地爬下悬崖。

莉兹贝特缓缓地吐出一口气，右手握着小刀说道：

「看来，似乎是不能从那条线继续往上移动了。」

「是啊。垂直方向的移动范围，感觉是巢穴的上下70米。」

「是啊。但，水平方向上大概就能移动几千米吧。仔——细一看那家伙停下来的地方，悬崖的颜色……或者说是质感，不觉得上下有点不一样吗？」

说起来，Genoligia停下来的线往下的岩石表面，确实感觉表面的光泽感稍微强一些。

「……那家伙爬行的区域，岩石表面似乎因为摩擦而变亮了……是这样吗？」

「大概吧。我认为白天在森林中视野很好的地方检查的话，就能锁定移动范围吧」

「那么，只要充分地离开移动范围，说不定就能安装楼梯了……」

「不一定啊……即使回避了那个混蛋大海蟑螂的地盘，还有别的怪物也守护着悬崖的可能性很高哟。」

「也是……帕特鲁族和巴辛族都有『不能攀登终焉之壁』的规矩，说不定不管在哪里爬，都会被那种怪物袭击，或许是这样吧。」

「唔嗯。虽然很可惜，利用这个悬崖建立补给线是不行的吗」

莉兹贝特说道，西莉卡则是点了点头。在高200米的悬崖上和不仅能在垂直的悬崖上自由自在的高速移动、而且有着三段HP条的BOSS级怪物战斗，是十分危险的。或许还有其他的方法——比如在悬崖边上往海蟑螂的巢穴里灌入油，然后再点燃之类的——要是用那样的奇计的话，越过势力范围攻击过来的可能性不能说没有。毕竟，只是扔了稍微有点味道的汤就生气成那样。虽然，可能不是「稍微」吧。

「……只是得到悬崖BOSS的情报也不错啦。」

作为回应，西莉卡双臂中抱着的毕娜被放到头上。

最后再一次注视着眼下的广大森林，以及在大森林一角亮着的拉斯纳里奥的灯光。以后，要是在第二阶层建立新的据点的话，说不定就暂时回不到拉斯纳里奥了。

小木屋坠落到资源丰富的地方似乎是偶然，受到坠落的冲击而没有损坏也是，能够在数次的危难下守护住也是，发展成如此大的街区也是，都是多亏了伙伴们的努力，再加上相同程度的幸运吧。

虽然小木屋的所有者是桐人和亚丝娜，但对于西莉卡来说、大概对于莉兹贝特和其他伙伴们来说也是，那个小木屋是重要的家（home）……是假想世界中另一个可以称为「自己家」的地方。

——绝对会回来的。

在心中对拉斯纳里奥的灯光这么说道，西莉卡回过头。

然后，看见莉兹贝特的双手拿着刚才切断的麻绳，目不转睛地盯着看。

「……绳子，很抱歉让你切断了。我还有『麻的纤维』，回到废墟后就修理……」

对于西莉卡的谢罪，莉兹贝特则是大大地摇头否定了：

「啊，不是不是，不是那样……我在想，这个世界的绳子最长能延长到多少米呢？」

「咦？」

面对预想之外的问题，西莉卡眨了好几次眼睛后回答：

「……让同种类的绳子首尾相连的话，用素材道具就能连接起来……和现实世界一样，只是延长的话，不论多长都没问题吧？只是……」

西莉卡一边想象着无尽的长绳，一边继续说道：

「只是延长的话绳子就会变重，不知不觉间，绳子本身的重量就会超过耐久度，可能到了最后，只是在空中拉起绳子来就会断裂。」

「也是啦……」

似乎得到了相同的结论，莉兹贝特深深点头后说道：

「这样的话，如果有超—轻超—坚固的绳子，就能架设到超远的距离了吧。」

「那……那是……——『远』是指100米吗？」

「唔嗯，3千米。」

「3……3千米！」

西莉卡不由得叫了起来。

确实，记得箱根的缆车全长有4千米左右，但缆车绳索是用很粗的钢丝制成的，而且应该也有十根以上的支柱。虽然不知道在没有支柱的情况下，最长架设了多少米绳索的世界纪录，但3千米不管怎么说都是不可能的吧。连现实世界的科技水平都做不到，那目前只能做麻绳的Unital Ring就更不可能实现了。而且说起来，莉兹贝特为什么（特别指出是3千米）——

考虑到这点的时候，西莉卡的脑内浮现出了一个想象。

快速回头，再次望向拉斯纳里奥的灯光。转回身去，注视着莉兹贝特手中垂下的绳子。

「难道是，从这里到拉斯纳里奥，用那个……在倾斜的绳子上咻啪地滑下去的东西……」

「滑索（ZIP-LINE）。」

「那个！你想用滑索连接吗？」

「Yes！」

西莉卡茫然地注视着猛然举起双手中绳子的莉兹贝特。

过了五秒后，我开口指出一个错误：

「……3千米的绳子不够哦。因为这里比拉斯纳里奥高200米，按照勾股定理……」

「啊，这样啊。嗯……底边长3000，高200，斜边的长度是……嗯……」

「莉兹小姐，你是考生吧？」

「不要让我想起讨厌的事哟。」

虽然露出苦涩的表情，但莉兹贝特还是以相当快的速度进行心算。

「3000的平方是九百万，200的平方是四万，加起来就是九百零四万，再平方根是……三千零六吗？几乎是误差吧！」

「如果加上绳子垂下的部分和用来捆绑的部分，至少要加上（plus）一百米左右吧。而且……倾斜度也只有四度左右，不知道能不能顺利滑下去……」

「别小看四度坡哟！没有助力（assist）的自行车爬起来可是很辛苦哟！」

「好的好的。」

西莉卡点头后，再次看向了拉斯纳里奥的灯光。

虽然刚听到的时候觉得很乱来，但脑海中浮现的画面却没有消失的迹象。甚至相反，随着时间经过反而越来越鲜明了。

如果将这里和拉斯纳里奥用绳子给连接起来，然后再用飞快的速度滑降下去，那该有多么爽快啊。而且，用滑索的话也不用靠近悬崖。即使Genoligia有远程攻击能力，降到30米线的时候，也已经距离悬崖400米以上了。无论是什么样的远程攻击，也不可能到那个距离吧。

「……能否实现先暂且不论，但有和大家商量的价值。」

西莉卡俯视着拉斯纳里奥说道，在旁边往前走了几步的莉兹贝特用唱戏一般的语调背诵道：

「如果相信能做到的话，那就相当于做到了一半……西奥多・罗斯福」

** 8

刚从白金台站的二号出口来到地上，就正好开始下雨了。

明日奈将粗呢套袖大衣（Stenlanda）的扣子系到脖子处，从挎包（shoulder bag）里拿出折叠伞并打开，开始沿着目黑区的步道往东北方向步行。

** 10

月4日星期天，上午10点40分。因为附近没有值得一提的商业设施和观光景点，所以即使是休息日也见不到多少路人。

在白色基调的高级公寓和办公大楼林立的街道上快步前进。虽然差不多有四年没走过这条路了，但风景几乎没有什么变化。

不久在街道的左侧，出现了涂成绿色，代表是学校区域（school zone）的岔道。沿着那条岔道继续走五分钟，就能走到明日奈以前就读的学校——私立艾特露娜女子学院的校门。但明日奈只是看了一眼岔道就继续走了，就这么走下通往高轮方向的坡。

在缓慢地右转弯途中，通过人行横道到达马路对面。耸立在眼前的老字号城市酒店就是目的地。

横穿暖气开得恰到好处的主门厅（main lobby），到达休息咖啡厅（lounge cafe）。告诉服务生（waiter）「和人约好了」后继续往里走，因为事前已经通过邮件告诉了桌子的位置，所以没必要一个个去找。

宽敞的店内，正面的一整面墙壁是玻璃做的，种有漂亮枫树的中庭一览无余。玻璃窗前的两人位有一半以上是空的，但约好的席位是墙边的四人位。明日奈向那边靠近的同时，也许是感受到明日奈来了吧，一个人坐着的等待对象抬起头来，浮现出亲切的笑容。

「嗨，小亚」

「你好，阿尔戈小姐」

压住要站起来的“鼠”之阿尔戈——帆坂朋，明日奈脱下了大衣。在圆桌周围摆着两把扶手椅（armchair）和一个沙发，因为朋（阿尔戈）坐的是靠近墙的椅子，所以明日奈将大衣和挎包放在沙发的一角后坐下。

「抱歉呐，大清早的」

道着歉的朋（阿尔戈），穿着的是鼠色马海毛针织毛衣（mohair knit）和黄褐色的露肩连体裤（bare top salopette）这种秋天的打扮。成为注册商标（trademark）的芥子色冲锋衣（shell parka 冲锋衣似乎不太准确，21卷结尾插图中穿的）叠成圆形放在了桌子下面。

「不不，完全没有。昨晚睡得很好」

「是吗，那太好了」

估计两人寒暄完了，女服务生将冷毛巾和菜单放到中间的圆桌上，行了一礼后就退下了。因为朋（阿尔戈）面前只有装着水的玻璃杯，大概是一直等着明日奈来吧。

「今天由我（俺 ore）来请客，有喜欢吃的就随便点吧。虽然想这么说，如果能点蛋糕套餐的话就太好了」

不由得对率直的发言苦笑之后，明日奈回答道：

「不用哟，请客什么的。蛋糕套餐也不便宜」

「不不，让约出来的对象花钱可是有损情报屋的名誉哟」

「……都说到这份上了，那谢谢你请客了」

做出让步后，明日奈打开菜单。食物几乎都超过了3000日元，饮品也在2000日元左右，不夸张的说，比归还者学校食堂的贵了一位数。在其中，蛋糕套餐是合理的2200日元……虽然怎么也不能说，但朋（阿尔戈）既是高中生，听说也作为游戏媒体「MMO Today」的撰稿人兼调查员而活跃着，所以应该得到了和天生的情报收集能力相符的收入吧。说到底，指定这个城市酒店为见面地点的就是朋（阿尔戈）。

明日奈仔细地注视着蛋糕套餐，说道：

「我要pomme verte（法语“青苹果”的意思，这里是蛋糕名字）和大吉岭」

「那我要……提拉米苏和卡布奇诺就好了。」

向女服务生示意完成点餐后，将背靠在丝绒质地的沙发上。不知道是天气还是时间的原因，客人只有三成左右，比起谈笑声，还是咖啡厅中央设置的泉水的水声更大。听到那令人怀念的声音，不知不觉间沉浸进去的时候——

「亚酱不是第一次来这里吗？」

突然被这样问，明日奈在眨眼后回答道：

「欸……阿尔戈小姐不是知道这点才选的这家店吗？」

「不——，一点也不知道。即使是我，也不会做挖出朋友的现实信息的事哟。」

「这样啊……也是。——我直到四年前，都在离这个旅馆很近的学校就读。」

明日奈如此说明，朋（阿尔戈）快速地看了一眼左侧——艾特露娜女子学院的方向，但马上就将视线转回来了。说起四年前的话，马上就能明白是在被囚禁在SAO之前的意思吧，阿尔戈无言地催促明日奈继续讲下去

「当然，小学生和初中生的时候都没有一个人来过这种店，但因为家长会或者活动之类的，母亲来学校的机会很多，在那样的日子，回去的时候就经常带着我来这里。嘛……但我认为与其说是为了我，倒不如说是母亲自己很满意这里呐。」

「原来如此呐。」

朋（阿尔戈）附和着的同时，左臂托着托盘的女服务生出现了。她小心地将蛋糕与饮料摆在圆桌上，往明日奈的茶杯里倒入红茶，将账单翻过来后就离开了。

「趁还没凉快吃吧。」

明日奈点头说出「我开动了」后，就拿起装有大吉岭的茶杯，享受着橙白毫茶叶的奢华香气。小学的时候光点果汁和苏打水，上了初中后就完全喜欢上红茶了，即使到了现在也没有改变。

所以昨天在Under world的时候，听说星王妃开发出跟咖啡很像的咖啡尔茶的新品种，并且命名为「夕月夜」时稍微吓了一跳。如果星王妃真的是在那个世界留下来的自己，那么比起咖啡尔茶，难道不应该勤奋地进行红茶的品种改良吗？

但是，经过了这么长的时间，星王与星王妃的喜好也会改变吧。一开始觉得苦而不加任何东西的红茶，不知不觉间就变成最喜欢的饮料了。

含了一口大吉岭，享受着跟以前一样精心提取的清淡味道后，明日奈把茶杯放回茶托上。因为朋（阿尔戈）很早就开始吃提拉米苏了，所以明日奈也拿起叉子，轻轻地取了一些带有绿色巧克力脆壳的青苹果慕斯蛋糕。

一入口，青苹果的清爽香气，以及白巧克力的醇厚甜味在嘴里扩散开，随后就化开了。这家店的蛋糕会因季节的变化而变化，但对在艾特露娜女子学院上学的时候也仅有一次的，品尝过的蛋糕的味道还记忆犹新。

而且那时候也一起点了红茶，所以不是小学时，而是上了初中以后吧。但，明日奈那时穿的是学校制服而不是私服……和明日奈一起来的也不是母亲。那天是星期一，走出校门后，一边在意着其他学生的目光一边到了这家店。在艾特露娜女子学院时做出这种事，八年间——正确来说是七年半间，只做过一次……

「嗯～是和价钱相符的味道呐。」

因为朋（阿尔戈）的低声评论，明日奈突然回过神来，点头道：

「嗯嗯，非常好吃。」

「但是，量就有点美中不足了呐……小亚，在UR里能再现吗？」

「欸，将提拉米苏……？姑且不论ALO，在Unital Ring里是不行的哟。毕竟没有小麦粉、奶油和巧克力。」

「尼嘻嘻，说得也是。」

朋（阿尔戈）像恶作剧般笑着的同时，把最后一块提拉米苏塞进嘴里。仔细品尝后，把卡布奇诺也一口喝完。

「唔……虽然从保谷市来这里很麻烦，但来了还是有意义的。」

「对了，我记得阿尔戈小姐是在学校附近租了公寓吧。真好啊，这么近。」

「亚酱是在世田谷区的宫坂町吧？」

「嗯。」

「现在的学校上下学也很花时间吧，以前的学校不也很辛苦吗？那个，先是坐世田谷线到三轩茶屋町，然后再坐田园都市线到涩谷区，再然后坐山手线到目黑区，再坐三田线到白金台……不对，是从三轩茶屋町坐半藏门线直达永田町，然后再坐南北线……是这样吗？{译：感兴趣的可以自己去搜一下}」

「真亏你什么都不看就能搜寻到这么复杂的线路。」

明日奈不由得佩服之后，稍微缩起脖子说道：

「其实，小学的时候都是用车送到洗足。从中学开始才坐电车和公交车。」

「啊——从洗足的话，到白金台就不用换乘了。」

朋（阿尔戈）像是理解了一样地点点头，明日奈重新询问：

「但是，如果是这样的话，为什么要选这家店呢？像是吉祥寺或者荻洼町之类的，干脆去新宿不是更好吗……」

「这个嘛，嗯……」

轻轻耸肩的同时，朋（阿尔戈）把茶托上的小饼干（biscuit）拿起来了。

朋（阿尔戈）对明日奈说「星期天的上午，在现实里见面吗」，是昨天——是今天的凌晨两点，在Unital Ring中的事。

星期六是十分动荡的一天。马上要到星期天的时候，乘坐父亲开的车到六本木支部的明日奈，就这么直接潜行到了Under world中，然后在中央大圣堂的屋顶上，什么都不知道地就用右手碰了谜之窗口。紧接着，大圣堂就像火箭一样起飞了，擦着上空漂浮着的超大型机龙的右舷到达了宇宙，然后在宇宙中和莲花模样的宇宙要塞对接了。

因为是超乎想象的事情，所以明日奈惊呆了，但没有吃惊的只有艾尔莉而已。不——正确来说还有一人，那就是管理宇宙要塞的名叫莉莉露（リリールー）的女性，但没有进行自我介绍的机会。因为明日奈用超级账号的地形操作能力生成了岩石，然后桐人用心意将岩石转换成钢素和晶素，再然后艾尔莉用元素对大圣堂的外壁进行了修复……自愿进行了这样的工作。

但制作了二十几块岩石后就有些头痛了，虽然明日奈说了没关系，但桐人和爱丽丝坚决地不让明日奈继续使用能力，于是明日奈向刚觉醒的整合骑士法那提欧和伊迪丝匆匆地打过招呼之后就登出了。不知道现实世界的事的伊迪丝，露出了相当惊讶的表情。

结果，在Under world中潜行的时间还不到四十分钟，虽然明日奈感觉没有起到什么作用，但据艾尔莉所说，如果明日奈没有将那个不可思议的纹章窗口给解除的话，中央大圣堂就没法起飞，大圣堂的上层好像就会被超大型机龙的炮击给吹飞。

对躺在自动调节椅子（reclining chair）上的爱丽丝说了「加油呐」后，明日奈走出了STL室。过道上虽然没有凛子和彰三的身影，但能听到微弱地说话声，明日奈走向声音的方向，敞着门的接待室里，两个人在友好地谈笑着。

没有关门就表示着凛子「没有打算谈生意（business）相关的事」吧。彰三也理解了意思，聊天似乎也只停留在有关政治和经济的事上。但坐车回去的时候，彰三说了「神代博士是相当杰出的人呐」，作为经营者来说似乎有了很大的感触。

回到世田谷区的家时已经是一点十五分了，即使是母亲京子也已经回到家，但多亏了彰三袒护着说「我邀请明日奈去兜风了」，所以才没有挨训。

回到自己房间的明日奈，为了将放置着的虚拟角色移动到安全的场所，一边忍受着困意一边再次潜行到Unital ring里。

但令人惊讶的是在明日奈不在的仅仅两小时内，伙伴们就收集了大量的素材，将满是窟窿的破屋墙壁给修复了。虽然似乎也可以修屋顶，但据阿尔戈所说，将原有的破屋完全修复后就会作为「主体建筑物」而登记上去，一方面会产生加护效果，另一方面似乎也会吸引区域支配者的怪物。因为预测到第二层的支配者应该远远强过第一天袭击过来的棘刺洞穴熊，所以只修复完墙壁就暂且停下了。

即使如此，厚厚的石壁也具备了阻挡杂兵怪物的强度，拉斯纳里奥已经证明了这一点，所以明日奈她们在凌晨两点结束冒险，决定解散了。在干草床上躺下，准备再次登出的时候，阿尔戈小声地搭话了，问说上午能不能见个面。

那位阿尔戈，也就是朋，漂亮地剥下饼干的玻璃纸，发出咯吱的声音说道：

「其实呢，亚酱。选择这家店的，不是我啊。」

「咦……？什么意思？」

「出其不意这点虽然很抱歉……但有人想要见亚酱……」

「想要见我……？」

面对意想不到的发展，明日奈盯着朋（阿尔戈）的脸。

当然可以哟，这句话卡在喉咙里没有出来，可能是因为对自己的交流能力变得没有自信的缘故吧。

短短几天前，明日奈还认为自己总体来说是个善于交际的人。即使是初次见面的人也不会胆怯地说话，只要说话就会自然而然地成为朋友。

但是，当神邑樒邀请说「明天一起吃午饭」的时候，虽然欣然承诺了，但还是感觉到了些拘束感。这不是错觉。要问为什么的话，第二天知道樒缺席的时候，明日奈在内心的某处松了口气。明明，她是依靠着来自同一个中学的明日奈也说不定。

想到这里，难道是……如此思考着。

朋（阿尔戈）所说的，想要见明日奈的人难道是神邑樒吗。

既然她是从艾特露娜女子学院转学到归还者学校，那么知道这家酒店的休息室也完全不奇怪。

朋（阿尔戈）将像是惊讶的视线投向了陷入沉默的明日奈。是谁？明明只要问一下就好了，但开不了口。

就在这时——

背后响起了硬鞋底踏在绒毯上的「咚咚」脚步声。明日奈左后方的入口处，有谁笔直地接近着。明日奈的身体绷紧了，一动不动地听着那个声音。过了既不长也不短的数秒，脚步声在很近的地方停下了。

「……亚丝娜。」

听见这个招呼，明日奈小小地咽了一口气。

和樒的冰冷高音（high tone）完全不同。是有些嘶哑却能听清，低沉而有力的声音。在过去，确实在哪里听过的声音……

好不容易用深呼吸解除身体的紧绷状态，明日奈战战兢兢地把身子转向左边。

最开始见到的是，被茶色皮革的长筒皮靴和紧身裤包裹着的两条纤细的腿。然后是穿在黑色包边针织衫外面的青紫色（鸠羽色）骑行夹克，脱下来的军用大衣用左手抱着。

明日奈眨了一下眼睛后，看向了用名字称呼自己的对方的脸。

「…………！」

猛然吸了一口气。扎成马尾的长发、光滑的额头与笔直的鼻梁、微微泛着绿色的细长眼睛——虽然比记忆中的容貌要成熟一些，但不可能会看错的。在无意识中站了起来，向前迈出一步，用颤抖的声音呼唤道：

「米……」

和对方同时踏出一步，张开双臂，紧紧抱在一起。淡淡飘出的柑橘类香味，和在艾恩葛朗特里爱用的香水很相似。

就这么抱了五秒以上，明日奈才终于放开了手。但没有拉开距离，而是在近处注视着脸。

「……看起来很有精神呢。」

明日奈用有些鼻塞的声音低语道，对方也眨了一下稍微湿润的眼睛，说道：

「亚丝娜也是。……很高兴能再次见到你。」

「唔嗯……我也是。」

明日奈终于向后退了一步的同时，注意到了在通道上待机的女服务生。于是让旧友在沙发上坐下，自己也在旁边坐下。

女服务生在桌子上摆好冷毛巾与菜单，回收空盘子与杯子的时候，明日奈也没有将视线从清凉的侧脸上移开。

米特，也就是兔泽深澄，和明日奈一样都是SAO生还者（survivor）。但是，她在艾因格朗特中却以别的名字而闻名。大裁缝师（chaeisma tailor）阿修雷——比谁都更快的完全习得了裁缝技能，换言之就是熟练度到达1000的传说中的生产系玩家。

桐人在SAO通关时穿的长大衣“黑龙大衣（Blackwyrm Coat）”，以及亚丝娜的红白相间的骑士服“セリーン コルサージュ”（Serene corsage）都是出自阿修雷之手。黑龙大衣正如它的名字一样，是以黑龙型的特殊怪物的皮和鬃毛为素材，仅仅缝一针似乎就花了十秒。但是，她经常抱怨说亚丝娜的骑士服更花时间。花时间的理由，好像是——

「……一这样我就想起来了呢」

因为点完餐的深澄，一边深深地靠到沙发上一边这么低语着，所以明日奈回过神来反问道：

「欸……想起了什么？」

「亚丝娜订购有公会颜色（特色）的衣服的时候。被告诉要不改变现在的衣服的设计，只将规格提升到最高，可为难了哟」

看来，深澄似乎也想起了完全一样的事。明日奈笑了笑之后，轻轻地摇了摇头：

「那时候也是，在店里的沙发上像这样并排坐着呐。结果，是怎么再现衣服设计的呢……？」

「取得之前衣服的纸样后，先用被指定为纸样的布料自动制作（auto craft）衣服后，然后将制作的衣服全部分解为零件，再将衣服零件的形状抄写到新的布料上，再剪下来手工缝制的哟。不管是在那之前还是在那之后，都只有那一次做了这么麻烦的事」

「哇啊……只是听就觉得很麻烦了呐」

「你以为是谁订购的？」

「抱歉抱歉，那因为是工会制服所以才不能改变设计。不过，无论如何也想让阿修雷……米特做」

「真狡猾呐，这种说法」

深澄稍微用余光注视明日奈之后，露出了和以前一样平静的笑容，但笑容就像太阳底下的薄雪一样，一瞬间就消失了。

「……抱歉，亚丝娜」

深澄突然说出这句话之后，将视线投向了自己的膝盖继续说道：

「两年间，一次也没有联络。其实是、在那个世界的期间，双亲擅自把手机号解约了，账号也注销了。似乎认为我涉足SAO是因为朋友的错。其实应该反过来才对吧……」

「…………」

明日奈一下子大大地摇头，说道：

「我潜行到SAO中，并不是米特的错哟。家人拿到了当天没法用的NERvGear，然后我一时冲动就带上了……真的只是这样。」

「但是，告诉亚丝娜SAO的事的就是我……如果没有告诉的话，不就不会一时冲动了吗？」

没办法立刻否定这句话。深澄告诉明日奈Sword Art Online的名字的时候，现在也还记得很清楚。

明日奈和深澄，曾经是艾特露娜女子学院的同一级学生。小学的六年间几乎没有说过话，只是知道深澄的个子高很显眼的程度而已，但八年级，也就是初中二年级的时候被分到了一个班里……然后一个月后的某一天，发生了意想不到的事件。

因为那天是星期六所以不上课，但为了自主学习的学生，还是开放了数个设施，明日奈上午在图书室查完东西离校后，为了买东西而顺路到了涩谷。前往目标店铺的途中，经过游戏中心的门口时，门口的大显示屏上映出了店内正在举行的格斗游戏大会的状况。但当时的明日奈对游戏完全不感兴趣，所以打算直接离开，却不知为何在意视线边缘的影像而停下了脚步……然后在屏幕里看到了，用令人眼花的手速操控着手柄和按键，像是兔泽深澄的女性玩家的身影。

因为露娜女校的校规严格禁止进入游戏中心之类的设施，所以认为只是长得像而已，虽然这么想，但明日奈还是隔着玻璃往店内窥视着。问题玩家虽然是穿着连帽卫衣并戴着帽子这种随便的打扮，以及有像是少年一样锐利（鲜明）的侧脸，但肯定是深澄。

虽然明日奈很惊讶，但比起惊讶，感到更多的是与羡慕相似的感情。埋头于对战中的深澄的身姿中，有像是要传到店外一样的高涨热气，不禁想想自己到现在为止有没有埋头于某件事当中呢。

但当然不可能进店里和深澄打招呼，明日奈离开了游戏中心门口。在那一瞬间，深澄像是感觉到了什么似的回过头去，笔直的看向了明日奈。

虽然没有向本人确认，但深澄的内心恐怕正纠结着到底是“就这么继续对战”还是“追上同学并封口”吧。深澄选择了后者，从店里飞奔而出并挡住明日奈的去路——暂时无言地对视之后说了。星期一的放学后，稍微抽出点时间来。

过了一天，深澄将在校外碰头的明日奈，带去了城市酒店的休息室。正是现在两人坐着的这家店。虽然都穿着艾特露娜女子学院的制服，但店员可能是认为要等监护人，所以什么都没说，将两人带到了窗边的桌子上。

深澄看着菜单上写的价格，用非常悲壮的表情向明日奈提出了交换条件。请你吃蛋糕之后，就忘掉星期六的事——

当时，对于只是个初二学生的深澄来说，两人份蛋糕套餐的4400日元绝对不是便宜的东西才对。但是，不这么做的话，就没办法完成封口，这样的话，深澄也放不下心来，考虑到这点的明日奈狠下心来点头，点了gateau chantilly aux fraise——也就是草莓海绵蛋糕（shortcake）和大吉岭。

虽然奶油是明日奈喜欢的口感，草莓也很新鲜，但说实话不太清楚味道。几乎没有对话就吃完了，从酒店出去的时候，明日奈对深澄耳语道「多谢款待，这样我也是打破校规的共犯了，所以放心吧」然后踏上了归途。没想到从那天开始，明日奈和深澄的奇妙的朋友关系就开始了——

「……米特告诉我SAO的事，是在第二学期开始后过了一段时间的时候吧。那一天的事我还记得很清楚……」

像是自言自语一样说完这些话后，明日奈深深地吸了一口气，重新说道：

「但是，我潜行到SAO，也不是米特的错哟。大概，我认为即使没有和米特成为朋友，在那一天也会带上NERvGear。」

明日奈伸出左手，和在沙发上无力垂下的深澄的右手重叠。

之前低着头的米特抬起头来看着明日奈，然后再次左右摇头。

「即使如此，也必须在现实世界面对面地好好道歉……以及、道谢。因为将那个死亡游戏通关，将我们解放的是亚丝娜。仅仅是联络方式而已，明明想要调查的话就能调查出来……」

「将游戏通关完全不是我一个人的力量，而且没有去见面这点我也是一样的。回到现实世界之后，尝试联络过米特一次，但不管是电话还是邮件，通信应用也联络不上……虽然向艾特露娜女子学院的人问一下说不定就能知道……」

「不，不会知道的哟。我、复学一年了，也没有把新的联系方式告诉学校里的任何人。」

深澄低语道，明日奈踌躇片刻后说：

「米特……复学到艾特露娜女子学院了呐。」

为什么没有来归还者学校，虽然想要继续这么说，但是忍住了。不管是监护人的意向，还是深澄自身的选择，轻易地询问都不是一件好事。

深澄也只是点了点头，然后将视线从明日奈转到了朋（阿尔戈）身上。

「阿尔戈……不，帆坂小姐，感谢你今天能答应我的任性要求。」

深澄点头致意，朋（阿尔戈）则是张开了沉默了有一会的嘴：

「不不，该道谢的是我サ。说实话，我已经做好了被拒绝三次的觉悟哟。就像是在那边（SAO）委托定制的时候呐。」

「……这么说简直像是我在摆架子一样，只不过是订单积压的太多而已呐。」

「明明说过好几次雇人了サ……NPC店员都不用呐—」

「一个人更轻松。这么说的话，你不也一直都是一匹狼，不，是一匹鼠吧」

听着两人高速的争吵，简直感觉像是回到了SAO时代一样，明日奈眨了眨眼睛。大量使用木材的装修，和烟雨朦胧中的枫树，再加上泉的潺潺水声，突然不知道这里是现实世界还是虚拟世界了。

轻轻摇了摇头之后，明日奈打断了两人的对话。

「阿尔戈小姐，米特……那个，今天在这家店集合是为了什么……？」

两人一起注视着明日奈，然后快速地交换视线，朋（阿尔戈）先开口了：

「嗯—呐……我正在寻找某位SAO生还者的事，之前对小亚也说过吧。」

「嗯嗯……」

轻轻点头。

朋（阿尔戈）被拉斯的菊冈诚二郎委托的，似乎是调查某个VRMMORPG游戏。虽然发行这个游戏的是开发了Augma的KAMURA的子公司，但从同时连接用户数（CCU）来推测的话，营收明明是赤字，却既不宣传也不停服，就这么悄悄地运营着。虽然确实很不可思议，但像这样的事也不是完全没有，而且菊冈在意到会特意雇佣调查员的程度的理由，要说是谜的话也是个谜。

这位调查员朋（阿尔戈）要求的调查报酬，是总务省假想课所持有的机密情报——也就是特定SAO生还者身份的情报。这些就是之前听说过的，但朋（阿尔戈）没有透露那位生还者是谁，明日奈也没有问。

朋（阿尔戈）像是切断犹豫一样，喝完了凉水后，就这么拿着杯子直接说道：

「那家伙，不管是本名、玩家名还是性别都不知道呐。线索只有两个，一个是几月几日几点几分在艾因格朗特的某处的位置信息，以及一个不确定的绰号而已。然后，我请那位假想课的大叔（菊冈），对保存在旧SAO服务器中的所有玩家的移动记录进行分析，虽然那个结果终于在昨天送到了……」

对不由得探出身子的明日奈和深澄，朋（阿尔戈）则是轻轻地耸了耸肩：

「没有符合的玩家，就是这样サ」

「欸……？有那样的事吗……？」

在明日奈之后，深澄也困惑地说：

「移动记录应该是不会搞错的，位置信息也是对的吧？」

「啊啊，毕竟是我亲眼所见呐。那家伙，和微棺的成员说话的时候呐……」

「…………！！」

明日奈听到自己吸气的声音。微笑棺木——正式名称是「Laughing Coffin」。是在艾恩葛朗特里穷凶极恶的杀人公会。即使死亡游戏SAO被通关后，微笑棺木散播的恶意依然在The SEED连结体（nexus）中持续投下黑色的影子。

明日奈注意到自己的嘴里突然变得很干，于是将左手伸向了玻璃杯。然后，又注意到茶壶里还有红茶，于是往空茶杯里倒入红茶。虽然早就凉了，但对于现在来说，这个温度刚好。

咕咚咕咚地喝下大吉岭，明日奈向朋（阿尔戈）问道：

「阿尔戈小姐寻找的生还者，也是微笑棺木的成员吗？」

「不……我认为不是正式的成员呐。那家伙的浮标是正常的绿色，也没有微笑棺木的公会图标呐……」

「啊啊，这样啊……在SAO里，只能看到没有任何关系的玩家的HP条和公会图标呐。」

「就是那样哟……不管是在那之前还是之后，都只见过那一次呐。差点就要从隐藏的地方冲出去和那家伙决斗了哟，决斗的话就能看到玩家名了呐。」

「等一下，不要这样啊！」

明日奈无意中发出了很大的声音，然后压低声音继续说道：

「决斗PK是那些家伙的拿手好戏哟。虽然不是怀疑阿尔戈小姐的本事，但特地去决斗什么的是自杀行为哟。」

「亚酱，已经回到现实了哦。」

对于朋（阿尔戈）的指摘，明日奈发呆了一会才注意到。这里是现实世界，微笑棺木也在很久以前就破灭了。

轻轻碰了一下放下心来的明日奈的右臂，朋（阿尔戈）说道：

「谢谢你为我担心。但是没问题，已经不会再做危险的事了哟……我只是，想要结束在艾恩葛朗特里没完成的事而已。」

「……这种感情我明白哟。」

这么说的是深澄。

「大概，几乎所有的生还者，都还对那个世界有着大大小小的留念吧。我也是，现在也在想着当时那样做的话，当时没那样做的话……但是，阿尔戈虽然刚才说不会再做危险的事了，但我认为追查微笑棺木的有关人员已经足够危险了。去年年末Gun Gale Online发生的事件，应该不会忘记吧？」

「那当然，不会忘记。即使查到了对方的身份，也不会一个人去突击的哟。把情报交给合适的人就结束了。」

朋（阿尔戈）耸了耸肩这么说道，明日奈想要问合适的人是谁。但在那之前，深澄点的生芝士蛋糕和柠檬马鞭茶就送来了，所以暂且闭上了嘴。{译：verbeine 学名是Aloysia citrodora，柠檬马鞭草，虽然名字里有柠檬，但实际上和柠檬没有什么关系，只是有和柠檬相似的香气，原产自南美洲}

深澄喝了一口有着和柠檬相似的香气的柠檬马鞭茶，松了一口气后看向明日奈。

「亚丝娜你们已经吃过了吧？抱歉呐，迟到了」

「不，完全没有......要是知道米特来的话，就不点餐先等着了」

听到这个回答后，深澄轻轻地瞪着正咬着第二块饼干的朋（阿尔戈）。看来朋（阿尔戈）虽然事先邀请了深澄，但为了让明日奈吃惊而保密了吧。

但说到底，朋（阿尔戈）是怎么联系上深澄的呢。两人是在SAO中认识的，难道是在SAO中交换了联系方式吗。

就像是感受到了明日奈的疑问一样，朋（阿尔戈）再次开始了说明：

「......嘛啊，正因如此，最后的希望的移动记录也扑空了サ。委托人大叔似乎也觉得不太好，于是就和我说要追加报酬，所以我就用那个权利，多管了一个闲事サ......」

说到这里，朋（阿尔戈）看向吃着芝士蛋糕的深澄，然后低下了头：

「抱歉呐，米酱。我从假想科的数据库里，调查了你的现实情报」

「我就知道是这样」

深澄扑哧一笑，用指尖灵巧地将叉子转了一圈。

「请我个芝士蛋糕就行了。我在以前，也是在这里用蛋糕套餐拉拢亚丝娜的」

「啊—，所以才指定这家店吗。原来如此，是两人有回忆的地方呐」

明日奈看着像是理解了一样点头的朋（阿尔戈），然后沉浸在无言的感慨中。

虽然再会是一周前，但朋/阿尔戈恐怕在很久以前，就一直将亚丝娜和米特的事记在心上了吧。然后在知道桐人团队里没有米特之后，才用突然的追加报酬，像这样将两人拉到一起吧。

「......谢谢，阿尔戈小姐」

明日奈传达谢意后，朋（阿尔戈）面带笑容地说道：

「不—，只是顺其自然而已サ。我才是，还以为是我多管闲事了，能这么说真是帮大忙了哟。而且，我也不是没有私心呐」

「私心是......？」

「其实，我有想问二位的事さ」

朋（阿尔戈）的笑容突然消失了，隔了一会才继续说道：

「那个，我不是要寻找某位SAO生还者吗。刚才，知道的有位置信息，和不确定的绰号而已……我是这么说了吧？」

「是这么说了呐。是什么样的绰号？」

提问的是明日奈，旁边的深澄也探出身子。

朋（阿尔戈）卷卷的刘海深处的眼睛，再次闪过刹那的踌躇后说道：

「——“薄荷醇（menthol）”。在SAO时代，有没有，听说过这个名字？」

「哈……？」

不由得和深澄对视后，明日奈向朋（阿尔戈）确认道：

「薄荷醇（menthol），是那个“嘶”的，有薄荷（mint）成分的.....？」

「大概呐」

「.......如果是薄荷（mint）桑的话，并不在血盟骑士团里，虽然记得圣龙联合里有叫meltonwool（麦尔登呢）的人，但menthol这个人就没听说过呐……」

「一样」

点头的深澄将头向左歪了：

「呐阿尔戈，为什么知道那不是玩家名，而是绰号呢？」

「那当然是因为，我仔细调查过黑铁宫的“生命之碑”，将玩家名读起来像是menthol的所有玩家，全都跟踪调查过了呐。但是，所有人都落选了」

「……连这样的事都做了？」

明日奈一边目瞪口呆，一边继续询问：

「虽然微笑棺木确实是死亡游戏的最大障碍，但头脑派只有PoH、沙萨、强尼・布莱克三人，其他的成员就像是忠实的……不，就像是被洗脑的部下而已。为什么要对那个薄荷醇这么执着……？」

「……确实，我曾经也是这么想的哟……在当时呐。」

用略带苦涩的声音低语的同时，朋（阿尔戈）简直像是在警惕偷听一样，快速地看了一眼周围，然后降低声音继续说道：

「接下来的没有任何证据，只是我个人的推测哟。微笑棺木创造出来的各种杀人手法……除了单纯的MPK和毒PK之外，像是决斗PK、睡眠PK、回廊PK等等巧妙利用游戏系统的方法，可能几乎都是那个薄荷醇想出来的。」

{译：MPK，利用怪物杀死玩家。毒PK不清楚。决斗PK，发起半血决斗并将受害人的血量压到一半左右，再使用大威力剑技将受害人剩下的血量一口气清空，详见进击篇第二卷。睡眠PK，在受害人睡着的时候申请决斗，然后拿起受害人的手接受决斗，并在睡梦中将被害人杀害。回廊PK，将回廊水晶的出口设定为必死的地点，并让受害人使用}

** 10

「请喝吧，爱丽丝酱。」

爱丽丝双手接下递过来的杯子。

「非常感谢，伊迪丝殿下。」

道完谢后，虽然认为没有用，但还是说道：

「请称呼我爱丽丝。因为我还是成为骑士还不满十年的新手。」

「哎呀，我不是根据编号的大小来决定称呼方式的哟。我称呼法那提欧也是直接叫法那提欧吧。」

「那么，是为什么……」

「因为可爱才决定的吧。」

若无其事地回答后，伊迪丝让爱丽丝坐在沙发上，自己也坐在旁边。用极其自然的动作伸出右手，轻轻地抚摸爱丽丝的头。

「而且，爱丽丝酱昨晚非—常努力了呢，作为骑士前辈，得好好地表扬你。」

——赛尔卡有时也会因为我的纵容而露出为难的表情，原来是这样的感觉啊。

一半放弃地思考着这样的事，爱丽丝等着伊迪丝摸到满意。

两人所在的地方，是横向很长的房间中。黑色基调的内装虽然很朴素，但墙壁和天花板是黑色大理石，地板上则铺着南帝国特产的黑羊毛织成的绒毯，沙发的皮也是同样的羊皮革，看起来像便宜货的地方连一平方Cen都没有。

沙发是能坐三个人的尺寸，对面的墙壁是一整面的玻璃。玻璃并不是垂直的，而是从前面的地板向天花板前方倾斜了四十五度。窗户的另一侧，是无数星星静静地闪耀着的夜空。但并不能打开窗户。因为这个房间，是在央都圣托利亚的上空30000Mel漂浮着的，「黑莲二型宇宙要塞」的底部的观景室。

充分地抚摸爱丽丝的头之后，伊迪丝终于放下了右手。把背靠在松软的沙发上，呼……吐出了长长的气息。

脱下了和爱丽丝一样的铠甲，身上只有黑色无袖骑士服和同色的打底裤，以及很细的剑带而已。虽然是三百年前的衣服，但布料完全没有损坏，设计也没有感到很古老。感觉和桐人在这个世界爱用的骑士服的整体设计很相似。

端正的侧脸看上去比爱丽丝年长少许，但不认为有年长到把爱丽丝当成妹妹看待的程度。话虽如此，对于天命被冻结了的整合骑士来说，年龄之类的就像是不存在一样。说是距离现在三百年前的话，那就是是星界历——不，是人界历280年左右吧。虽然整合骑士团的创立还要再早一百年，但迪索尔巴德在以前经常说「以前的骑士团的纪律和礼法比现在严格多了」，所以伊迪丝该严厉的时候也一定会严厉。要注意不能没规矩……爱丽丝思考着的时候。

伊迪丝就这么靠在沙发上，右手伸向矮桌的方向，用心意力将桌子上放着的自己的杯子浮了起来。

用手抓住在空中飘过来的杯子，靠近嘴边。但没有喝，而是慢慢地品味飘着的热气。

「唔—嗯，真香……以前的咖啡尔茶，不管怎么仔细地泡，都只有一点淡淡的香气呐……」

呆住了的爱丽丝，轻轻地摇了摇头后回应道：

「似乎是亚丝娜改良了的，名叫『夕月夜』的品种。」

「嘿欸……亚丝娜酱是和桐人一起当过人界、不，是Under world的王和王妃吧？摆弄土壤之类的，和Administrator猊下有很大的不同呐……」

像是自言自语般说完后，伊迪丝喝了一口咖啡尔茶。

「好喝。」

小声说完后，将视线投向窗外的星空。

爱丽丝也将双手拿着的杯子放到嘴边。这个咖啡尔茶也是，说了好几次由我来泡，但伊迪丝说「好了坐下吧」才不得已的听从了。喝了一口，有点浓但没有杂味的顺滑味道在嘴里扩散开来。确实比爱丽丝泡的要好上一两级。

「好喝。」

「对吧。」

笑着回答的伊迪丝，右手依然拿着杯子，左手的指尖敲响了沙发的扶手。然后，空中展开了半透明的视窗。虽然是以前并不存在的技术，但因为存在着「史提西亚之窗」的全息视窗（Hologram Window 日本人自己造的词，Holography的缩写+window），所以伊迪丝也很快就习惯了。触碰菜单好几次后，正面的视窗切换成远程影像。

映照出来的是央都圣托利亚的中心部。也就是半天前中央圣堂还耸立着的地方。

影像上是从东南方向俯瞰的广大用地。当然不存在白色的巨塔，取而代之的是长宽50Mel的方形洞穴张开大口。因为现在是十二点四十分，所以索鲁斯应该几乎在圣托利亚的正上方，但整个用地都被某个东西的影子给盖住，导致光线无法到达。

巨大的深穴被像是从地面凸出来的金属制隔墙围得严严实实。围墙周围拉起了一圈黄色的绳子，绳子的外面，等距离地站着身穿灰色制服与制帽的卫士们。虽然不知道他们收到了怎样的命令，但时不时就往上看，大概不是因为任务，而是因为不安吧。

伊迪丝再次操作视窗，影像就急速缩小，映照出圣托利亚市的全景。将视点缩小到这个地步，终于知道大圣堂用地是被什么的影子给盖住了。

是全长达到了300Mel，楔形的人造物。自称皇帝阿格马尔・威斯达尔斯6世搭乘的超巨大机龙，「Principia」。

昨天晚上是在2Kilol的高空中漂浮，但现在下降到了500Mel左右的高度。是和原本在那里的中央大圣堂最上层差不多的高度，这绝对不是偶然。

圣托利亚市民，特别是警备大圣堂用地的卫士们，应该很担心机龙掉下来吧。因为即使在白天仔细去看Principia，也完全没有热素引擎喷射的样子。

似乎在思考同一件事的伊迪丝，一边歪头一边说道：

「昨天晚上，突入了大圣堂的机龙，似乎是喷出热素火焰来飞行的……但那个大的，是怎么浮起来的？」

「完全不清楚。因为现在艾莉她们正在进行解析，所以总会得到某些推论的……」

「这样啊……」

伊迪丝又喝了一口咖啡尔茶，再次操作影像。将影像再次放大，并放低视点。不久，整个窗户就映照出用红色砂岩建造而成的南圣托利亚街景。明明距离北圣托利亚连1Kilol都不到，但不论是路上往来的人们的服装，还是行道树的种类都完全不同。

影像靠近了在现实世界被称为露天餐厅（opencafé）、在屋外有座位的快餐店（轻食店）。因为正好是中午，所以八成的座位都有人，但人们的脸上没有笑容。而是将头靠在一起，一边时不时地抬头看向北方天空中漂浮的黑影，一边窃窃私语着。虽然听不到声音，但对话的内容能简单地想象出来。在讨论到底是去圣托利亚外面避难，又或者是留在市里。

虽然皇帝阿格马尔在昨天晚上，用立体影像宣言了自己才是「全人界的正统统治者」，但自那以后除了将Principia下降到那个位置以外，就没有进行任何宣告了。恐怕，中央大圣堂的飞翔以及大圣堂和宇宙要塞的对接，对于皇帝来说也是远远没有料想到的事态吧。虽然昨天晚上漂浮在大圣堂上空2Kilol处的Principia发表了胜利宣言，但现在大圣堂则是在自己头上30Kilol处漂浮着，在这种情况下，肯定难以决定是否要再次宣布胜利。

话虽如此，这边也同样陷入了困境。黑莲二型虽然搭载了大大小小如山一样多的兵器，但如果Principia坠落的话，对圣托利亚造成的伤害不是亚鲁戈级机龙所能比拟的。搭载的数千个热素全部解放的话，毫不夸张地说，东西南北全市区都会变成火海。

因此，现整合骑士团——虽然这么说但只有五名觉醒的骑士——的指挥官法那提欧，下达了「观察皇帝的态度」的决断。虽然有些消极，但如果是爱丽丝来指挥的话，也会这么做吧。至少，皇帝如此执着地要歼灭的冻结骑士们全都平安无事，所以还是有等待敌人行动的精神上的余裕。

接受了法那提欧的决断，桐人和亚丝娜在早晨来临前就登出了。爱丽丝她们也轮流洗完澡之后，将监视Principia的任务交给黑莲二型的管理人莉莉露，就到大圣堂九十二层的好几个两人用寝室休息了。

因为房间是按蒂洁和罗妮耶、法那提欧和伊迪丝、爱丽丝和赛尔卡、艾尔莉和纳兹来划分的，所以对爱丽丝来说，很想和再会的赛尔卡好好地交谈一番，但从躺在床上之后就没有记忆了。

原本想小睡一下，结果却足足睡了六个小时，被赛尔卡叫醒时已经超过十点了。敌方机龙即使天亮了也没有动作，大家一起在九十四层吃完早饭，然后在联络之前都是以待机为名的自由时间。

快要到再不从Under world里登出就会给神代博士添麻烦的时间了，而且也很在意Unital Ring的状况。但是，现在离开赛尔卡的话，再次回来的时候如果发生了什么不得了的事，恐怕又会变得遥不可及……实在无法甩开这种不安。要是一边左思右想，一边缠着再次开始制作解冻药的赛尔卡的话，「太碍事了，去个什么地方吧！」，会被这么说吧。

沮丧地走下大阶梯后，伊迪丝追了上来，因为想直接看行星阿多米娜，所以邀请爱丽丝一起去黑莲二型底部的观景室。没有拒绝的理由所以就同行了，通过升降洞从八十层下降到一层，从到昨晚为止还连着前庭的正门进入要塞中，然后沿着道路左拐右拐，最后终于到达了这个观景室，直到现在——就是这样。

如果不登出的话，有很多事情可以做。确认爱丽丝不在的两百年间开发的新术式、学习星界历之后的历史和地理，或者干脆打扫大圣堂好了。但是，靠在仿佛要把人吸入的沙发中小口地喝着咖啡尔茶后，站起来的气力就渐渐变弱了……

「三百年、吗……」

伊迪丝的声音让爱丽丝猛然抬起越来越重的眼皮。

轻轻地往左看去，黑色缎带的骑士的眼瞳中浮现出摇荡的光芒，目不转睛地看着南圣托利亚市区的影像。

「……虽然知道经过了这么长的时间，世上会有很多变化……但没想到公理教会和整合骑士团都消失了，路上行驶的是没有马的马车，还有从暗黑领域来的观光客呢。」

话说回来，影像中随处可见哥布林族和食人鬼族的身影。爱丽丝在一瞬间的犹豫后，小声地补充道：

「伊迪丝殿下，我认为那些亚人不是观光客，而是移居者和移居者的子孙。」

「咦……这样啊……」

伊迪丝虽然似乎有些吃惊，但表情中没有厌恶的感觉。漏出微弱的吐息后，再次低声说道：

「但是，最吃惊的是……贝尔库利阁下和Administrator猊下去世了的事情。」

「…………是啊。」

爱丽丝只能这么回答。接着伊迪丝就动着右手，砰砰地拍了拍爱丽丝放在沙发上的左手。

「我不是在责备爱丽丝酱哟。虽然确实吓了一跳……但是，我感觉总有一天会变成那样……」

「……为什么呢？」

畏畏缩缩地这么问之后，伊迪丝就把视线朝向观景室的天花板继续说道：

「……Administrator大人拥有非常……大到极限的力量。正因为如此，除了自身之外就没有真正信任的人了。所以，如果有猊下的力量也应付不了的危难降临的话…………」

虽然没有把话说完，但爱丽丝理解伊迪丝想说的话。

异界战争，又叫「最终负荷试验」，就是那个「危难」。最高祭司为了对抗从东大门涌至的暗黑界军，不是强化整合骑士团与四帝国军，而是打算实行将一半的人界居民转换成巨像的疯狂计划。桐人、尤吉欧、爱丽丝以及贤者卡迪娜尔和她的使魔夏洛特之所以与最高祭司战斗，就是为了阻止这个计划。

……不对，仔细一想，整合骑士团本身就是Administrator疑心的产物。因为想要最强的护卫集团，又害怕被背叛，所以为了强迫他们永远不会动摇忠诚心而编写了「整合（Synthesis）仪式」。摇光被改变，整合骑士相信自己是从神界召唤而来的，最高祭司Administrator的忠实仆人。

爱丽丝的摇光中也残留着模组。虽然有可能去除，但在这种情况下如果不插入被夺走的记忆碎片，摇光就无法正常工作……也就是是可能会丧失部分记忆，最坏的情况下似乎则会一直昏睡。另外，即使取回了记忆碎片，也很有可能丧失现在的爱丽丝 Synthesis Thirty的人格。话虽如此，爱丽丝被夺走的记忆碎片在和最高祭司的战斗中消失了，所以已经没办法去除模组了。

伊迪丝也是，被夺走了爱着的某人的记忆，埋入了敬神模组。法那提欧大概也没有详细说明仪式的事情吧。总有一天，伊迪丝也会知道自己对最高祭司抱持的感情是半强制性的。

爱丽丝无意中移动左手，握住了伊迪丝的右手。啊，虽然这么想，但已经晚了。面对露出不可思议微笑的前辈，一边寻找话语一边说道：

「伊迪丝阁下……虽然由我这个将剑指向最高祭司大人的家伙来说可能不太好，但那位大人是用那位大人的方法爱着Under world。然后那份『爱』，也确实对着我们骑士……我是这么相信的。」

「…………」

虽然伊迪丝沉默了很久，但不久后就翻过右手，回握了爱丽丝的左手。

「……是啊。即使是坏了就会被丢弃的人偶……猊下曾经也很珍惜我们。我啊，并不后悔作为整合骑士活着的岁月。」

「…………是。」

轻轻点头的同时，爱丽丝将身体向左倾斜，靠在了伊迪丝的肩膀上。两位整合骑士，暂时就这样继续眺望着影像中映出的美丽街景。

** 9

耳边响起的轻快旋律，将我的意识从深邃的黑暗中拉到表面。

保持着半睡半醒的状态，思考着这里是三个世界中的哪一个。ALO虽然有自动断线机能，但Unital ring没有这样的保护，即使睡着了虚拟体也会留下来，被攻击的话就会跟平常一样死亡。因此没有硬要在UR里睡觉的理由，而且现在躺着的地方也不是在干草上铺上粗布的硬邦邦还会发出沙沙声的床。

虽然没有自动断线机能的还有Under world，但中央圣堂的床，连见习清洁员的床都是难以相信的滑溜溜软绵绵的。现在在身体下面的东西，既不是硬邦邦也不是滑溜溜的，而是涤纶褥子与高反弹聚氨酯床垫。也就是说，这里是我在现实世界的卧室。

这个理所当然的结论，足足花了六十秒以上才得出来，我眨了两三次眼睛后，抬起沉重的脸。

从窗帘缝隙中照进来的光是淡淡的灰色。仔细听之后，能听见细微的沙沙声。外面似乎正在下雨。

就这么躺着，用手摸索到携带终端然后放在脸前。锁屏画面上显示着用小猫照片当头像的来信图标，这是谁来着……一边皱起眉头一边看名字，是亚丝娜。终于注意到图标照片并不是真正的小猫，而是精巧的幼猫型机器人，也就是拉斯谨制的「小四」。看来，似乎是将昨天才暂存的小四设置成了通讯应用程序的头像。

一边不由得露出了微笑一边触碰画面，以人脸识别解除锁定。启动了的应用程序显示着亚丝娜传来的信息，但正文只有一张照片。

以漂亮的枫树为背景，两位女孩露出笑容站在一起。右侧的是，穿着米黄色立领外套的亚丝娜。但对左边的，披着灰紫色骑行夹克的女孩并不眼熟。比亚丝娜要高3公分左右，长发绑成了马尾。是我不知道的归还者学校的朋友吗？但是，那样的话正文应该会写些什么的。

……不对。我对马尾女孩的冷静容貌稍微有一些印象。到底是在哪里见过——不是在学校的话，那就是拉斯的有关人员，但那也太年轻了，而且和亚丝娜合影的理由也是个谜。

虽然只剩下假想世界了，但不论是Unital ring还是ALO，虚拟体的模样都跟现实世界完全不同，所以看到在现实里拍的照片刺激到记忆是不合道理的。莉兹和西莉卡她们虽然是例外，但那是因为她们现在也使用着跟旧SAO中生成的跟肉身很像的虚拟体——

「…………啊！」

终于想到正确答案的我发出了小小的声音。

不会搞错的。虽然不是归还者学校的学生，但这个女孩也是SAO生还者。刚一如此确信，久远的记忆就连锁地复苏了，这次则是发出了「啊啊……」的叹息。

她是阿修雷。是将我持有的有固有名称的龙型怪物（named dragon）的素材，缝制成黑龙大衣（Blackwyrm Coat）的艾恩葛朗特第一精明能干的裁缝师。要是没有她做的防具和莉兹贝特做的剑，我就没办法继续在最前线战斗。虽然跟阿尔戈一样，在SAO通关后就消息不明了，但看来是平安无事地回到了现实世界。

我点击通讯应用程序的输入栏，发出【能再会真好呐。阿修雷看起来也很有精神，告诉她我也很高兴】后，将终端放到无线充电底座上。

时间是上午十一点五十分。虽然足足睡了将近六个小时，但亚丝娜要是没发信息过来的话，说不定还要再睡两小时左右。

刚一这么想，胃部就被像是上升的感觉袭击了。

其实现在不是能贪睡的状况。必须尽快救出在Under world的宇宙军基地里被绑架走的艾欧莱恩・赫伦兹才行。

他恐怕——不对，一定被监禁在超大型机龙「Principia」里面。因为他是整合骑士团长，同时也是星界统一会议长欧瓦斯・赫伦兹的儿子，是超重要人物，所以应该不会被拷问，更不用说立刻处刑了，但皇帝阿格马尔是会让自己的部下乘坐机龙发动特攻，像过去的皇帝贝库达一样的冷血之人。艾欧莱恩要是不顺从自己的话，无法预测他会用出什么残暴的手段。

这样的话，虽然是很矛盾，但只能将希望寄存在拐走艾欧莱恩的托科伽・伊斯塔尔身上了。伊斯塔尔虽然用小刀划伤了艾欧莱恩脖子上的一层皮，但我却不知为何确信小刀不会继续划下去。互相称呼为「科伽」与「艾欧尔」的那两个人之间，恐怕有他人不知道的因缘。即使因为右眼的封印而无法违逆皇帝，伊斯塔尔也不会危害艾欧莱恩，应该会在可能的范围内想办法吧。

我压下焦急的心情，从床上下来。

在眼前的地板上，放着一个奇妙的物体。将铝切削而成的表面发出微弱的光芒，是长30公分，宽50公分左右的长方体。不像看上去那么重，用在上面的螺栓固定的提手（Carrying Handle）就可以勉勉强强地搬运。

长方体下面有电源和通讯的插口，目前两个插口都插着电缆。插口的对面，有着操作面板和电源按钮。打开电源的话，中间稍微靠下的地方的横切线就会将整个长方体一分为二，然后上半部分就自动上升，露出内部的接口来。

触摸式操作面板下面有激光蚀刻出来的极薄图案，是拉斯的标志（Logo）和【STLP1.0】这样的字母和数字。「Soul Translator Portable version1」（STL便携型1）的略写。

昨天傍晚，从拉斯六本木支部出来的我和亚丝娜，坐菊冈诚二郎开着的车回到了各家。但应该说是理所当然吗，菊冈并不只是亲切地送我们回家，在车里还装着不得了的礼物。

给亚丝娜的是，幼猫型机器人小四。给我的则是这个STLP。

正如名字所写的一样，是将六本木支部里的巨大的STL，缩小成努力的话就能搬运的大小和重量的物品。读取灵魂的分辨率不用说肯定比STL要差，但能好好的用助记图像潜行到Under world中，也能用心意力。要是没有这个的话，昨天晚上爱丽丝发来救援邀请的时候，我就得骑一个小时以上的摩托去六本木了。当然，那样肯定就阻止不了アーヴス级机龙突入到宇宙军基地里，不敢想象在那种情况下基地会——艾欧莱恩和罗妮耶他们会怎么样。

菊冈到底是预想到了Under world的情况才将STLP送到我家呢，又或者是单纯的偶然呢。

应该是偶然呐.........我一边这么想，一边再次看向了时钟。突然，感觉似乎忘了什么东西而皱起眉头，在那时。

房间的门被「咚咚！」地高速敲响了，紧接着以猛烈的势头打开了。飞奔进来的是穿着运动服的直叶。

「哥哥，你要睡到什么时候！」

这么叫着的直叶，把拿着托盘的左手笔直地伸向了我的眼前：

「好了，赶快吃吧！」

「等......等等等等。首先，我已经醒了」

「五分钟之前还在睡吧！」

被这么说的话，只能点头说「是」。

赶忙接过托盘，托盘上面的是冷绿茶和黄瓜三明治。

「哦哦，thank you」

道谢过后坐到床上。将托盘放到小桌上，用绿茶润了润干渴的喉咙后，拿起一块三明治。

这是在美国单身赴任的父亲，桐谷峰嵩的得意料理。虽然是食材只有黄瓜的朴素三明治，但全都切成片的黄瓜是用盐、胡椒、酒醋腌制，仔细地控去水分后，然后薄薄地涂上黄油再夹入面包中入味的……意外的费事。

直叶一定是打算一起吃才做了这个三明治吧。然而，却让没起床的我睡到了极限为止，那至少，要仔细地品尝一下——虽然我这么想。

「这种的一口就能吃完吧！快点快点！」

被坐在旁边的直叶催促着，于是我只好将手里拿的一块三明治囫囵吃下。享受着控去水分的黄瓜的爽快口感和清爽的风味之后咽下，说道：

「好吃，技术提高了呐」

「欸，真的？」

欸嘿嘿……地笑了后，直叶立刻绷紧了身体：

「不是这个，只剩下五分钟了哟！」

「十二点有什么事吗……？」

「果然忘了。是要和ApD组见面吧！」

「…………啊」

我大大张开的嘴里，被直叶塞进了一块新的三明治。

吃完饭，收拾完并刷牙后，我直奔二楼的房间。

刚一打开门就听到「快点快点！」的催促——没想到，直叶正坐在床上，用不可思议的目光注视着地上的谜之物体。不好……虽然一瞬间缩起了脖子，但仔细想想也不是什么不好的东西。

「哥哥，这是什么？」

「上面写着吧。」

「所以说，STLP是什……咦？」

说出口后，看来似乎终于明白那四个字母代表着什么了。直叶像是从床上掉下来一样靠近长方体，窥视着正面的面板。

「难道说，这个是STL的袖珍版吗？用这个的话，就能在这里潜行到Under world里吗？」

「嗯。昨天，菊冈先生送来的。」

这么回答的同时，昨晚的记忆再次复苏。

装在EV轿车后备箱的STLP，即使用了专用的手提箱，一个人拿也有点重，因为母亲还在公司，直叶也还潜行在Unital Ring中，所以是菊冈帮我运到了二楼。

穿着西装的菊冈诚二郎出现在这个房间里，实在是不可思议，或者说是太没有现实感的光景，我呆呆地注视着正在进行STLP初期设定的菊冈。仔细想想的话，让除了双亲和直叶、亚丝娜，以及快递事件的爱丽丝之外的人进来，可能是从小学以来的第一次。

结束设定的菊冈，不知道为什么一边浮现难以解释的微妙微笑，一边环视着我的房间，说出「是很棒的房间啊」的感想后就回去了。不禁想着到底哪里棒，但他的个人生活似乎也接近极简主义者，说不定是出乎意料的认真。哪一天会奇袭他似乎在东云地区的家，来确定他的感想是不是奉承……

「欸，昨天几点左右？」

因为直叶的声音而从沉思中醒过来的我，看了一眼墙上的时钟后回答：

「大概是小直攻略阶层地下城的时候吧。」

「啊，这样……有好好地端茶给他吗？」

「没有，马上就回去了哟。」

「是很忙的人呢……」

像是理解了一样点点头后，直叶抚摸着STLP外面的面板。

「这个，下次也让我用吧。」

「是可以啦……你确实有提拉利亚的账号……」

「好了，现在是Unital Ring的时间哟！」

站起身的直叶，戴上AmuSphere后就躺到了床靠墙的一侧。虽然想说「在自己的房间潜行吧」，但时间已经超过十二点了。

我也戴上AmuSphere，在直叶的旁边躺下，异口同声地喊出「Link Start！」。穿过七彩的隧道，刚一感觉到双脚触碰到虚拟的地面，就猛烈地站了起来，然后，

「太慢了！」

降下了这样的声音，我缩起了脖子。

往上一看，肩上挂着滑膛枪的诗乃正坐在粗粗的横梁上。在她旁边，抱着短弓的结衣也坐在那里。两人头上的屋顶有七成崩落了，因此可以清楚地看到略微有些阴的天空。

「爸爸，早上好！」

我将右手握成拳状，回应笑着挥手的结衣：

「抱歉迟到了！谢谢轮班看守了！」

我登出Unital Ring是在昨晚——是今天早上四点。之后的八个小时，基本上都是结衣一个人在看守这个据点。我不想把结衣当作方便的AI，虽然这么说，但却让她以这种方式看守，实在是有些羞愧，但自从艾因格朗特诞生以来就一直是观察员的她，在变成了和我们一样都是玩家的现在，怎么能阻止她希望能最大限度地发挥自己能力的愿望呢。

一边再次看向将视线投向远方的结衣的身影，一边这么想，这时，背后响起了咚咚的柔和脚步声。回头一看，是巨大的黑豹跑了过来，将头在我的胸前摩擦，刚一挠痒它的下颚，它就高兴似的呜咽。

「你也thank you呐，小黑。」

「嘎呜！」

不知道它能理解我说的话到什么程度，背琉璃暗豹小黑就地坐下，然后像催促般摇动着长长的尾巴。我一边苦笑一边打开仓库，取出肉干后交给它。

话说回来，一起潜行进来的直叶在哪呢……我环视周围。

我目前身处在还算大的建筑物当中。虽然不论是刚发现时还是现在，都是崩塌的破屋，但因为用手头的素材修复了石砌墙和铺着木板的床，作为临时据点来说已经具备了十足的强度与舒适感。虽然屋顶还有洞这点有些遗憾，但如果修复屋顶就会被判定为主体建筑物，领主怪就有可能袭击过来。

看来这个建筑物不是普通的民家，而是士兵的执勤室之类的，几乎没有隔间的墙壁，只有一个大房间和似乎是仓库的小房间而已。大房间的墙边，整齐地摆着「粗糙木头与干草的床」，登出的同伴们——亚丝娜、阿尔戈、西莉卡、霍格、扎利昂、西西正躺在上面。我之所以在地板上待机，只是因为床位不够而已，但即使是Unital Ring，脚也不会因为长时间蹲着而发麻。

不在床上的伙伴们现在应该在潜行中，但房屋内只有我、结衣、诗乃、小黑，还有钻进西莉卡床里的毕娜，以及在亚丝娜身边的地板上缩成球状的阿蜥而已。

{译：以下内容配合卷首的地图能更好理解}

总而言之，先和小黑一起出去。天空虽然有些阴，但气温很舒适，从南边的河面吹过来的微风舒服地轻抚着脖颈。

这个废墟里，除了作为临时据点的执勤室之外，还有石造的监视台和木造的厩舍。因为监视台面向南方，所以恐怕是为了监视通往第一阶层的道路的设施吧。话虽如此，但我并不认为有那么多人能突破入口有巨大蜂集群，出口有巨像守护着的阶段地下城。

反过来说，设置了这个监视所的人们，就是有这么的警戒着下层的侵入吧。 如果是这样的话，把阶段地下城整个埋起来似乎就可以了，但或许出于某种原因，似乎有从上面下去的必要。

无论是人为的三段同心圆构造，还是第一阶层到处都有的正圆型盆地也好，这个世界到底是怎么回事。Apocalyptic Date（ApD）的先遣部队在第二阶层西侧的森林里遭遇的暗黑精灵，为什么又要报上琉斯拉的名字……

就这么在执勤室前面站着，思考到这里的时候。

「o—i桐人~，这边这边！」

听到了莉兹贝特的声音，我转动了视线。于是看到了聚集在一起的同伴们。也有应该是一起潜行进来的直叶的身影。

小跑着靠近时，发现大家似乎正面对着谁。刚从站在左边的克莱因旁边露出脸来，就漏出了「啊嘞」的声音。

在稍微有些距离的地方站着的，是细长的四肢上覆盖着有光泽的暗红色毛皮，双足行走的狐人。是昨天绑架了结衣的ApD四人组中的一位，阿兹奇。

「阿兹奇，你为什么在这里？应该是在西边的桥上等着吧？」

听完我这么说后，阿兹奇立起尖尖的鼻子，以猛烈的势头滔滔不绝地说了起来：

「说的是什么话哟！你到了约定的时间还没出现，所以我才来看看情况吧！」

「啊—，那抱歉了」

一边搔着头一边道歉。我虽然在昨天告诉阿兹奇他们「明天正午前到废墟西边的桥」，但视野右下角的数字时钟显示着已经到了十二点十分。

「欸......阿兹奇，你从那座桥到这里花了十分钟吗？」

无意之中这么问了，阿兹奇则是有点得意似的挺起胸膛：

「不要小看我的脚呐。来到第二阶层的两百名兽人当中，我是跑的第五第六快的」

那为什么拐走结衣的是猴人马萨尔呢，虽然觉得很不可思议，但一想起来还是会生气，所以保持了沉默。恐怕，是因为阿兹奇力气不够吧。

「呐呐，第一快的果然是猎豹兽人吗？」

对于莉法的孩子气问题，阿兹奇点头说「是呐」后继续说道：

「但是猎豹没有持久力呐，虽然我也没有罢了。综合速度的话，是像跳羚这种的羚羊系吧......啊，不要一脸平静地打听情报啊，要收钱哟！」

环视一圈呆住了的大家后，阿兹奇最后看着我，说道：

「那么，桐人，让我听听你的回答！是和我们一起奋斗，还是不一起奋斗！？」

「一起」

「先说好，我来这里可不会接受拒绝之类的呐......欸？刚才，说了“一起”？」

「一起」

「..................」

阿兹奇呆住了，长长的睫毛忽闪了好几次之后点头了：

「......这、这样，谢谢。那—个......既然是这样的话，就见一次我们的领队吧。还有，为了联络，也要登陆成好友哟」

「了解」

打开窗口，完成和阿兹奇相互登陆成好友。刚一完成，莉法和莉兹贝特就从左右两边逼近了。

「我也要登陆！」「我也要我也要！」

「............嘛啊，是可以啦」

阿兹奇如此回答，就在那时。

沉默到现在的克莱因，右手伸向正上方大喊：

「我、我的也拜托了！」

当时在场的所有人都沉默了的理由，是感叹还是惊愕，又或者只是单纯的惊讶到了极点，我一时之间判断不出来。

率领ApD组的四十人先遣部队的似乎是“凯茜帕鲁格”——通称凯茜帕的猫人。

阿兹奇和莉法、莉兹贝特、克莱因他们登录完好友后，当场就给凯茜帕发送了信息，然后看了一眼马上就收到的回信说道：

「会谈的地点，是这里和我们营地的中间地点。时间是今天晚上九点。可以吗？」

「稍等一下。中间地点，距离多少千米？」

「这个，300千米左右吧」

「300…………」

我暂时忘词了。虽然理解很远，但用语言表达出来的话，想象就追不上了。这是在现实世界是需要乘坐新干线的距离。

「也就是说，你们为了拐走结衣移动了600千米？花了几个小时……不，几十个小时……？」

「这~~~~个……」

暂时停顿之后，阿兹奇像是没办法一样回答道：

「有让速度和持久力变成三倍的道具……秘药哟。喝了那个的话，连浣熊人拉尔卡斯都能跑出时速90千米。所以花了大概不到七个小时吧……」

「时速90千米！？那为什么马萨尔拐走结衣时，不用那个逃跑呢？」

「你们坐在宠物上追过来，是我没料到的。」

阿兹奇看了一眼坐在我旁边的小黑后继续说道：

「那种秘药，只对兽人和兽类有效果。所以，让宠物喝下药，然后你们再坐在上面移动。可以骑乘的宠物除了这个孩子、之前的蜥蜴酱之外没有别的了吗？」

「这个……」

代替难以判断米夏能不能移动到这里来的我，外交负责人弗里斯克尔回答：

「虽然还有很大的熊，但速度没有那边的黑豹快，说到底熊也无法通过阶段地下城。」

「啊——那个地下城，好像成了宠物尺寸的区分装置呐。」

阿兹奇他们似乎也很辛苦，鼻尖伸出的胡须微微的动着。

「唔嗯，现在开始再驯服附近的怪物的话，（宠物）等级和亲密度也不够吧……这样的话，到会谈地点的就只有你和另一个人了呐」

「那个『另一个人』，不就是自然而然的结衣了吗？有和黑暗精灵对话可能性的只有结衣一个人而已啊……」

「那孩子的大小，可以坐在奥托（狮虎）的背上。如果不讨厌的话呐。」

「……得问一下本人呢……」

我歪着头说道，在这时。距离这里20米以上的执勤室那边，传来了结衣竭尽全力的大喊：

「我没事哟—！我很期待坐在虎先生的背上！」

于是阿兹奇像是明白了一样，向结衣挥手致意，然后看向我说道：

「嘿欸—，在那里还能听到这种音量的对话？比我的耳朵还好呢。」

「唔姆，差不多是这样（嘛呐）。」

我一本正经地点了点头，但结衣是通过周波解析来复原人体大脑无法识别为语言的微弱信号，所以有些人可能认为这是作弊。但这个和用弓的能力一样，都是在这个不知道为什么就被扔进来的世界中，为了保护自己和伙伴们而竭尽全力而已。而且说到底，就算说出结衣是AI，阿兹奇他们也不会相信吧。

阿兹奇再一次快速地看了一眼结衣和诗乃，然后卷起了毛茸茸的尾巴。

「明明是这么好的孩子，却做了会让她害怕的坏事呐……」

「确实。要是一开始就稳妥地交涉就好了哟。」

克莱因如此哼着，而阿兹奇则是送去了湿漉漉的视线。

「能说出这样的话，是因为你们没有和旁边的邻居发生冲突哟。ApD组被左边的“SoulSo”和右边的“BluePara”攻击，在最初的三天就减少了三成的玩家呐。」

「哦、哦哦……那可真是有够受的呐。」

SoulSo也就是“Soulless Soil（ソウルレス ソイル 直译为无魂之地，疑似捏他黑魂系列）”，是凭借着和名字“没有灵魂的大地”相似的厚重且凄惨的世界观，和一次失误就会立刻死亡的难度而被核心玩家们支持的VRMMO。

另一个BluePara也就是“Blue Parallelism（ブルー パラレリズム 直译为蓝色平行）”，凭借着VRMMO中少见的赛璐珞动画风的卡通渲染，和时髦且干净的世界观在年轻人中颇有人气。不管是哪个都在The Seed连结体中有着靠前的同时连接用户数，如果被这两个游戏夹击的话人口确实会减少三成……虽然我也这么想。

「但是阿兹阿兹，ApD从一开始就几乎没有内部纠纷吧？为什么一开始没有发生主导权的争夺战？」

对于弗里斯克尔的提问，阿兹奇反击道「谁是阿兹阿兹哟！」，然后再次转过了身子。

「那当然是因为，有最好的领队吧！」

「是刚才说的凯茜帕鲁格吗？」

「不是，虽然凯茜帕鲁格也是很好的领队，但在凯茜帕鲁格之上还有一个人哟。只有通关非常难、而且像笨蛋一样长的连续任务才能成为“上位幻兽人（high mitherian或者是high metherian）”……在其中也是最难完成的“古龙人（Elder Dragonewt）”，ApD史上第一个转生了的……」

说到这里就突然闭上了嘴，阿兹奇用有可爱肉球的右手严厉地指向弗里斯克尔的脸。

「所以我说了，不要打听情报吧！真是的，话已经说完了，我要回去了！」

「稍、稍微等一下！」

我慌忙地阻止了回过头来的阿兹奇。

「什么时候拿那个秘药？还有，不能带路到会谈地点吗？」

「啊，是啊。那个……」

再次叫出环形菜单，窥视通讯栏之后，阿兹奇说道：

「我们这边也要做各种准备，所以下午四点在之前崩塌的桥那里碰头吧」

「了解。再请教两个问题……首先，那个秘药没有副作用吗？比如说会减少最大HP，或者喝了就有几率死亡之类的……」

「那种东西，我们怎么可能会喝呢。」

阿兹奇用吃惊的声音说道，然后干咳一声继续说：

「虽然肯定有副作用，但只是会加快TP和SP的消耗而已。所以只要携带大量的水和食物就没问题了哟。」

「这样啊。还有一个问题……秘药对鸟也有效果吗？」

「有的哟，ApD里也有鸟人（avisham）的兽人哦。……难道说，不会是想要驯服这附近的鸟，然后抓着它飞行吧。事先说好，秘药提升的只有速度和体力而已，力量是不会提升的呐！」

「知道了知道了。」

即使我不停地点头，阿兹奇也还是暂时怀疑地抽动着三角耳，但不久后回答道「是这样就好了」。她轻轻地往后方一跳，然后轻轻举起右手：

「那就四点见了。下次不要迟到了哟！」

好好地嘱咐之后，敏捷地翻过身后跑走了。不愧是豪言道是第五第六的人，眼看着纤细的人影逐渐远去，最后被平缓的山丘挡住看不见了。

数秒后——

「「好……好可爱～～～～！」」

莉法和莉兹贝特齐声喊道。

「看到了吗莉兹小姐！？耳朵和胡子，和真正的狐狸一样动了哟！」

「看到了看到了！而且还有那个滑溜溜软乎乎的毛皮……啊，真想拜托她让我摸一下～～！」

「下次见到的话绝对要拜托她！」

「应该说，即使被拒绝也要摸！」

看着气氛高涨起来的两人，我当然不会说出“我在那位狐狸小姐的脸上打了一发‘腐蚀弹’”这句话，而是横向移动到克莱因和弗利司柯尔旁边搭话道：

「那个……去和对方领队会谈的似乎是我和亚丝娜以及结衣，但单程300千米很难当天去当天回，而且也可能会根据交涉的进程而直接前往ApD组的营地。如果是那样的话，可能有三天左右回不来」

「也是呢。我也想去……猫人凯茜帕也很可爱吧……」

不理会将视线投向远方的克莱因，我继续说道：

「但是，我来之前看过拉斯纳里奥的状况了，感觉很混乱撒……艾基尔似乎也预想过，移居过来的ALO玩家们总有一天会要求NPC们迁出居住地……」

「啊——那个啊……我也试着调查过，拉斯纳里奥的等级3的加护的事情，在斯提斯遗迹里传得很广呢……」

所谓的加护，就是指成为拉斯纳里奥主体建筑的小木屋被赋予的特殊效果，等级3就是「半径50米以内的所有附属建筑物追加最大十万的耐久度」。现在，一个人能建造的木头或石头小屋的耐久度最多也就3000到4000左右，用树枝搭建的简易棚屋的耐久度连1000都不到，所以十万的追加耐久度确实是很破格、有额外奖金的地方了。{译：原文 大ボーナスもいいところだ 这里翻译的不是很准确}

不知道什么时候从梦世界回来的克莱因，懒散地摩擦着胡子哼哼道：

「加护的范围内，特别是埋没在墙壁内那块呐。现在，一间小屋的交易价格似乎是800到1000艾尔。」

「800……！？我，连100艾尔都没有哦。」

「啊—，桐老大没有参加Gilnaris Hornet（蜜蜂boss）的战斗呐。蜂巢里的金银财宝可是哗啦啦地掉落了呢。」

克莱因的嘴角浮现出满意的微笑，而我则是咕奴奴地咬着牙。连建在墙壁外的一间小屋都有1000艾尔的话，那如果把拉斯纳里奥本身卖出去的话能有多少钱呢……我用一声鼻息甩去这个无用的思考，回到正题：

「……因此，在真的提出迁出居住地的要求前，无论如何也要改善……根本性的对策有两个。在距离小木屋500米以上的地方建造新家，再将那边的等级也提升到3，或者将小木屋的等级提升得更高。可以的话，在我和亚丝娜出发前的三小时之内，先完成其中一个。」

「唔嗯，三小时吗……」

弗利司柯尔短短地哼了一声，露出思考的表情继续说道：

「这里往返拉斯纳里奥要一个小时，所以在那边能用的时间只有两个小时。老实说不管是哪个都很难，提升等级不知道还能不能行。移居集团在河边建的家被野猪怪物撞飞的事，听说过吧？野猪怪似乎非常强。」

「虽然有想要战斗的心情，但可以的话不是打倒，而是想将其驯服。也就是说，要提升小木屋的等级吗……问题是，扩建多少才会提升等级呢……」

「实在没有这么深的情报，说起来大概全UR中也没有等级4的玩家住宅哟。起始地点附近的素材完全不够，离开的话又有超强的领主怪袭击……听说到达第二阶层的Asuka和ApD，也放弃了在第一阶层建立中间据点，而是组织了一百人规模的拿货物（porter）的部队勉强维持着补给。」

「嘿欸……」

我用大脑的七成来理解弗利司柯尔的情报，剩下的三成则是在回忆往事。

第一次和这位长脸的火精灵族（salamander）见面是去年一月，在阿尔普海姆（Alfheim）的叫做「鲁古鲁回廊」的巨大洞窟里。他是袭击目标是世界树的我和莉法的，火精灵族大部队中的一员。只剩下他一人的弗利司柯尔爽快地接受了我提出的交易，虽然我当时认为分别了就不会再次见面了，但过了一年零九个月又在别的世界中偶然相遇，最后成为了伙伴，人生真是不可思议啊……

——现在不是沉浸在感慨中的场合。现在是十二点三十分，如果要回到拉斯纳里奥的话，最晚得在一点出发，但也想好好地整理一下情报。

「拿货物（porter）的部队……也就是说，是将武装减少到极限，特化了搬运补给物资的部队吧。那些人，是在起始地点和第二阶层不断来回吗……虽然应该是确保了路线的安全，但听起来很危险呐。」

「不，实际上就是很危险吧。」

克莱因快速地看了一眼南边的天空：

「我也想在拉斯纳里奥和马尔巴（マルバ）河之间造出一条安全的路，所以立了栅栏用墙壁围了起来，但我觉得越是这样做，越会有很强的暴徒（mob）靠近呐。虽然不知道ApD组和Asuka组是用什么方法来确保安全的，但武装不充分的大部队能不断地往返，我不认为这个游戏有这么天真。」

「同意。」

「一样。」

三人一起「唔姆」着。

Asuka组是完全的竞争对手，ApD组到最后也会变成那样吧，但不想在这个可能构筑合作关系的阶层受到巨大损失。会谈的时候，不能忘记问一下是怎么确保补给路线安全的，但大概不会告诉吧……我正这么思考的时候。

「桐人桑，关于那件事。」

从背后传来了搭话声，我回过头去。

然后，看到了不知何时潜行进来，头上顶着毕娜的西莉卡正和莉法、莉兹贝特站在一起。

「早安，西莉卡……那件事是？」

「是补给路线的事。我们也有从拉斯纳里奥到这个据点运送食物和材料的必要吧？」

「是啊……我记得断崖上有像是海蟑螂一样的BOSS巢穴吧？我不认为能在垂直的断崖上战斗，只能老老实实地爬上爬下地下城了吧……」

我一边想起今天早上侦察完断崖后回来的西莉卡和莉兹贝特传达给大家的价值千金的情报，一边如此说道，然后两人对视之后忍不住笑了。

「也许可以不做呦，爬上爬下」

对于西莉卡的这番话，不仅是我，克莱因和弗里斯克尔也歪着头。

然后这次是莉兹贝特，将双手握着的长约50厘米的黄褐色绳子「乒！」地拉了一下绳子后说道：

「这个，是亚麻纤维和尼迪桑的丝各占一半所编成的试做品。我用这个试了一次。」

「试了一次……是？」

对于我的提问，西莉卡和莉兹贝特一起喊道：

「「滑索（ZIP-LINE）！」」

** 11

十月四日，下午一点三十分。

在格外大的年轮松木旁边停下脚步的我，看到久违——话虽如此，但不在的时间只有十八个小时——的拉斯纳里奥，一时之间说不出话来。

虽然昨天晚上在这里登入的时候也因为变化而吃了一惊，但仅仅过了一天不到的时间，规模还在扩大。

虽然拉斯纳里奥的商业区被半径30米的墙壁围起来了，但因为中央的小木屋产生的「古树的加护」的效果范围是半径50米，所以墙壁外的20米内，匆忙建造的小屋密密麻麻地排列着，就像「市中」和「市外」的样子——虽然这么说，但那是到昨晚为止的状况。

现在，市外区域扩张到了到加护线外侧20米处。密集的建筑物几乎全都是，未经加工的原木——或者说仅仅只是树枝建造而成的「粗糙的木制小屋」，当然没有受到加护，所以耐久度大概只有一千。即使是低等级的玩家，用一把石斧也能轻易地破坏。

虽然无法携带的道具或者在里面登出是完全无法放心的，但恐怕是超密集状态导致的相互监视状态……也就是，即使趁着家主不在或者登出的时候将房子破坏了，也大概率会被其他人看到，因此借此勉强维持着治安吧。但是，无论如何也不认为这种状态能长久的保持下去。他们是期待着加护范围的扩大，或者再次分售墙壁内的土地，所以才在那个地方排队等着。

「唔嗯，这下不抓紧就麻烦了……」

我如此呢喃着，亚丝娜也在大树的阴影中眺望商业区，点头说道：

「是啊，这样的话今天可能就会发生大纠纷。」

「而且，移居过来的家伙似乎还在增加。因为我们到达第二层的事情，已经在斯提斯遗迹传开了。」

在后面这么说的是阿尔戈。在她旁边，西莉卡瞪大了眼睛：

「咦，是这样吗？明明才过了一天，是哪里传过去的情报……」

「网游的传闻啊，是能在一天之内从地图的一端传到另一端的哟。只是，这次确实传的有—点快。队伍里的人也没有在SNS上炫耀……」

「咦，阿尔戈小姐，检查了大家的SNS吗？」

亚丝娜惊讶般地问道，情报贩子不知何时复活了胡须涂装的脸颊微微动了一下：

「这是基础哟，基础。Insecsite组的账号也一直关注着呢。」

豪语之后，立刻收起笑容继续说道：

「但是，昨天接触的ApD组就实在无法推断了。有经由他们传开情报的可能性。」

「或者是被ALO的玩家监视了吗……」

因为队伍里的某个人逐一向外部传达了进展情况——吞下这样的猜测后，我继续说道：

「……如果是被监视的话，有九成的可能性是穆达希娜指使的吧。虽然破坏了『绞轮』的法杖，但我不认为那样就放弃了。总有一天她会做点什么的。」

「是啊。」

点头的亚丝娜，担心地看向拥挤的拉斯纳里奥的市外区域。

「既然没办法用『绞轮』的话，就很难组织像之前那样大的军队了吧，只要有心思的话，能做的事情还有很多。比如煽动移居过来的人们引发暴动，或者从很远的地方引来Life Harvester级别的怪物……或者更单纯点，可能会暗杀桐人。」

「喂喂，再怎么说也……」

虽然露出苦笑，但仔细一想就觉得不夸张。（说的这些手法）仿佛令人想起了旧SAO的杀人（红名）公会，微笑棺木的手段，但对于没有防止犯罪代码的Unital Ring来说，倒不如说是比SAO还要容易煽动或暗杀的游戏。

「不……我知道了。我会好好地警戒身边的，亚丝娜也要注意哟。」

我如此说道，亚丝娜就微微一笑，「嗯」一声点了点头。

接着，后方的西莉卡就咳了一声，开口表示：

「这个，我有点在意，穆达希娜小姐的愿望是把ALO组的玩家集中在一起，然后再成为领队吧？」

「唔嗯……大概就是这样吧。阿兹奇说ApD组有龙形兽人的最高领队（top leader），Asuka组大概也……」

「听说（Asuka组）有强悍的主大将、和有才干的军师。」

对亚鲁戈投以感谢的视线后，我再次看向西莉卡：

「所以穆达希娜的目标也是那个位置，而且把我们视作麻烦……应该说，想要让拉斯纳里奥服从自己，拉入到自己的势力当中吧。」

我如此回答之后，西莉卡就微微歪着坐着毕娜的头，沉思般说道：

「如果是这样，为什么不以普通的方法成为最高领队（top leader）呢？能使用那么强力的大魔法，继承的技能也好，所持有的装备也好，本人的战斗力应该也有相当高的等级。不用窒息魔法来胁迫，而是堂堂正正地构筑信赖关系的话，我认为成为ALO组领队的可能性已经足够充分了……」

我倾听着西莉卡的声音，同时回想起过去在斯提斯遗迹听见的对话。

——用这种混蛋魔法威胁同伴，就是所谓的最好的选择吗？会场里还有假想研究会的成员吧？

这么质问穆达希娜的，是队伍「广播酱粉丝俱乐部」的领队，双手剑士津风吕。

对于这个抨击，穆达希娜则是浮现出冰冷的笑容回答道：

——你们在这个地方聚集的理由，不就是因为利害碰巧暂时一致吗？我可以断言，就算现在约定好要合作，但到了靠近终点的时候，首先、队伍和队伍之间就会产生纠纷，再然后队伍中就会互相残杀哟。不过，至少在我的魔法发动的期间里，能回避那样的事态。如果目标是通关的话，这不就是最好、最有效率的手段吗？

我轻轻地摇头，将魔女的声音从耳朵里甩出去，对西莉卡说道：

「穆达希娜说过，无论多么团结的队伍，到了终点附近也一定会产生纠纷，为了防止那样才用窒息魔法……。确实，我也没法保证我们的队伍不会变成那样，但因为那样就将威胁同伴使其服从视为什么最好的方法，这是绝对不可能的。穆达希娜也知道这种程度的事吧……」

「那么……为什么，还要做那种事……？」

对于西莉卡的疑问，我再次左右摇了摇头。无论是什么样的玩家，只要面对面交谈的话，也能多少窥见内心，但即使我在那个魔女眼前发动剑技的那一瞬间，也完全没有看到她的内心。体会到那种感觉，或许是皇帝贝库达、也就是加百列・米勒以来……不，加百列有无限的虚无这点，我在和他战斗的时候清楚地感觉到了。但穆达希娜的眼瞳，就像是反射率100％的镜子一样……

「桐人哥……？」

西莉卡的呼唤让我猛地抬起脸来：

「啊啊，抱歉。——穆达希娜的行动原理，我连想象都做不到哟。现在能说的是，她肯定又要搞些什么吧。」

「既然如此，我们也得超越对方的设想吧！」

带着笑容说完后，西莉卡将视线投向了拉斯纳里奥：

「好了，先想办法解决那个混沌状态吧！然后再开始滑索（ZIP-LINE）的实验！」

「啾噜——！」

西莉卡头上的毕娜也发出有精神的叫声。确实，不能老是在这里站着说话。不在三点四十五分之前回到第二阶层的据点就赶不上四点的碰头了，所以能留在拉斯纳里奥的时间还有一小时四十分钟。在这期间，必须完成小木屋的等级提升。

我打开仓库的时候，阿尔戈后退一步说道：

「那么，就在这里分别吧。」

「咦，你要去哪里？」

这么问完后，阿尔戈快速地看了一眼亚丝娜后说道：

「我去一下斯提斯遗迹哟。虽然能在今天回到拉斯纳里奥，但那时亚酱和桐仔已经去ApD组的营地了吧，下次在这边见面可能还要有一段时间呢。」

「这样啊……小心安全哦。」

「你们也是！」

留下这句话后，阿尔戈就用像忍者一样的动作消失在森林深处。

重新打开仓库，取出「粗糙的披风（cloak）」后披在身上。亚丝娜和西莉卡也用同样的斗篷将头到膝盖下面都包了起来。

西莉卡将大背包实体化，把毕娜放进去后背了起来。这样的话，乍看之下应该认不出是谁。幸好，在头发和衣服不会简单风干的Unital ring里，为了避雨而装备披风（cloak），也就是带着兜帽（hood）的斗篷（manteau 法语）的玩家很多，因此即使是这样的三人队伍也不引人注目。

离开大树，靠近拉斯纳里奥的市外区域。虽然大多数建筑物都只是小屋，但小路旁边也有很多小摊子，谜之串烧和谜之炖菜、还有谜之包子都散发出一股很香的味道。

「不会买的哟。」

亚丝娜小声地对我这么说道，我回答「我什么都没说啊……」后，就沿着不到两米宽的小路前进。虽然看起来像是贫民窟，但气氛却出乎意料地明快，随处可见的小空地上，像是打猎回来的玩家们正拿着烤肉串和素烧杯子叽叽喳喳地说着话。

前进了二十米后，小屋的等级就肉眼可见地提高了。进入「古树的加护」效果范围内了。虽然不管是用树枝或是用木板做，还是用石头做，都会被赋予耐久度的附加价值，但这不是为了占地方而临时居住，而是正式的自己的家，所以某种程度上也想盖个像样的房子吧。

再前进二十米，穿过拉斯纳里奥的西北门。前面的是统称为「十时路」的道路，因为是星期天，感觉比昨天更热闹。

道路的右侧是巴欣族的居住地，排列着好几个帐篷。其中的一个帐篷里隐藏着隧道，那是能出入被高高的围墙围着的小木屋的通路。我们通过十时路半道上的巨大木门，正要进入巴欣族的居住地。

但就在那个时候，听见前方左侧传出了「哇——」的许多人的声音，于是三人面面相觑。左侧是厩舍区，除了我们的四只宠物外，也提供移居者的宠物寄养服务，因为小黑和阿加留在了第二阶层，所以现在只有米夏和阿铅，以及两三只

寄放的宠物……应该是这样。

离开木门，小跑地靠近声音的方向。然后，看到在厩舍广阔的前庭部分上有许多人，听到在人群深处有尖锐的金属声。

从人群间的缝隙中钻进去的我们所见到的，是预想之外的光景。

扇形的前庭中央画了一个大圆，在圆圈中央，两名玩家正对峙着。左侧的男玩家的武器是单手剑和圆盾，右侧的则是双手剑。虽然还以为是拳击或者剑击表演之类的，但双方头上漂浮的锥形光标的HP条，双手剑士还剩下八成，单手剑士则不到七成。作为表演来说是不是减的稍微有点多了。

我靠近在最前面声援的穿着皮革铠甲的男玩家，就这么带着兜帽问道：

「呐，这是在干什么？」

「啊啊？是决胜战哟！」

「决胜战是、什么的（决胜战）？」

「明明正到高潮，真烦人呐，那边写着吧！」

这么说的男玩家手指的方向是，圆圈的右侧深处。在树荫处立着一块之前没有注意到的临时制作的看板，是写着淘汰赛的所谓的告示牌。出场者有八位，也就是说在我们来之前，已经进行了四场的半决赛和两场的准决赛，现在的确似乎是决胜战的高潮时刻。

我快速地看了一眼正慢慢横向移动的剑士们，然后再一次凝视淘汰表。

告示牌的顶端，在表示优胜者的一条线上，还写着难看的【VS】的文字。也就是说，优胜者还要和谁战斗吗。VS上面也连着一条线，线则是连着——虽然告示牌的最上边也写着巨大的文字，但因为字迹潦草，再加上树叶空隙间照过来的阳光在不断摇晃，怎么也看不清。

就在这时，其中一位对战者尖锐的喊道：

「Sya！」

单手剑士一边举起圆盾一边拉近距离。双手剑士如果攻击的话，就用盾牌架开那一击，如果向左或向右避开的话，就用盾牌撞过去，使双手剑士的姿势崩溃，是这样的作战吧。圆盾是还算厚的金属制成的，即使受到双手剑的强攻击也不会碎。这是面对大型对手就打破间隔的基本作战策略。

但假如双手剑士也有对人战经验的话，那应该已经习惯了想要进行接近战的对手才对。到底打算怎么应对呢，我不由自主地探出了身子。

「哦！」

发出粗犷吼声的双手剑士，进行了连我都预测不到的行动。

轻易地扔下剑，向前迈出一步地同时用双手结实地抓住了圆盾的沿。幸好他的体格比较大，即使身体大幅度后仰也能抵挡对手的突进。然后、

「欧啦！」

一边再次发出吼声，一边将盾牌向左转动。单手剑士虽然也试图反抗，但因为一根手臂和两根手臂之间的力量差距，身体开始不稳定地倾斜。

我从SAO时代开始，就几乎没有在VRMMO里用过盾牌。但是，我知道在爱用大中小盾牌的玩家之中，“到底是把盾牌固定在胳膊上还是不固定”是老生常谈的问题。

几乎所有的盾牌内侧都装有皮带，将皮带固定在前腕部，然后再用手握住把手——这就是基本的装备方法吧。在SAO中，直接将盾牌放在装备人偶上，然后再实体化的话应该也是固定在腕部的状态。将皮带固定在腕部的话，即使放开把手，盾牌也不会掉下，因此手可以在某种程度上自由活动，也有可以防备抢夺技能的优点。

另一方面，在战斗中解开皮带并不容易，要是因某种理由而想要放下盾牌——比如被巨大的怪物咬住，又或是盾牌上沾了毒或油——的时候，也有着不能马上从手腕上取下的缺点。在SAO中，有人从怪物那里逃走的时候，盾牌在细长的洞穴中被挂住了，焦急地想要松开皮带却松不开，然后就那样……听说过这样的事。自那以后，似乎有相当多的持盾玩家用“快速切换”mod来进行盾牌的穿脱而不是武器的穿脱。

看来，抓住圆盾的单手剑士是皮带固定派的，因此姿势转眼之间就崩溃了。但是，发挥了还算不错的平衡感，横着踩一脚来避免了摔倒。

变成这样，很难说双手剑士更有优势。毕竟为了抓住盾牌而将剑舍弃了。接下来就看是单手剑士先回复体态，还是双手剑士先拿起剑——

我这么想的时候。

双手剑士迅速抬起右脚，然后，掉在地面上的剑就轻轻地浮了起来，剑柄收回到了右手中。看来，虽然看起来像是扔下了剑，但似乎是将靴子的鞋尖插在了刀身下面。

这个招数，让观众「哇」地沸腾起来了。虽然像是精巧的骗术，但这是比看起来难得多的高等技术。如果没有将自己剑的重心记在身体里，然后没有正确地踢在重心上的话，剑是不会垂直飞起来的。

双手剑士一边把左手也放到剑柄上，一边将剑水平架了起来。没有装饰却看起来很坚固的剑身，被红色的光包住了。是剑技「台风（cyclone）」。对手还没有从摇摇晃晃的状态中恢复过来。要碰上了——

正当我如此确信的时候。

「到此为止！！」

响起了粗犷的声音，双手剑士将马上要发动的台风故意打偏了。然后，单手剑士也站起身子「可恶啊啊啊——！」发出悔恨不已的声音。

在比刚才大数倍的欢呼声与鼓掌声中，从看板附近走出来一个玩家。是穿着鳞甲，左腰上挂着弯刀的体格很好的男性。似乎在哪里见过，在我皱起眉头的时候，后面的西莉卡小声说道：

「咦，是迪克斯先生哟。」

「啊……真的。」

那个弯刀使确实是队伍「杂草啃食者」的领队，迪克斯。

虽然听说昨天在Gilnaris Hornet（蜜蜂boss）攻略战时提供了协助，但他在这里做什么呢……还没来得及想，迪克斯就往双手剑士的方向握起拳头，大喊道：

「优胜者是……津风吕（图布罗）！」

我一边听着再次响起的欢呼声，一边大大地张开了嘴。因为整套防具都换了所以没有注意到，但我对那极粗的眉毛与方下巴有印象。不会弄错的，是「广播酱粉丝俱乐部」的领队，津风吕（图布罗）。

迪克斯与津风吕，再加上「绝对存活队」的领队霍尔加，他们三人曾经为了让ALO一致团结起来，在斯提斯遗迹举办了大规模的联谊派对。但在那里，魔女穆达希娜发动了大魔法「不祥者之绞轮」，使派对变成了充满悲鸣的地狱。

在那之后，三个队伍重新编为穆达希娜军，向拉斯纳里奥进攻。我们在马尔巴河的河滩上迎击大军，在死斗的最后将穆达希娜的法杖破坏了。从「绞轮」中解放之后，迪克斯和霍尔加留在了拉斯纳里奥，津风吕则是回到了斯提斯遗迹……虽然我之前是这么想的。

那位津风吕为什么会在这种地方参加淘汰赛，说到底这个大会是什么，我一边歪头，一边再次看向了淘汰表。在同一时间，薄云遮住了太阳，在看板上跃动的阳光变弱了。

告示牌的最上边大大写着的，预定要和优胜者战斗的人的名字是——【黑衣剑士桐人】。{译：翻译到这的时候没绷住}

「啊，是桐人君」「是桐人桑呢」

我僵硬地回过身去，小声地向异口同声低语的亚丝娜和西莉卡问道：

「那个啊……我、有约好要参加那样的活动吗？」

「在我所知的范围内，应该是没有……」

「也是呐……」

「啊，迪克斯先生好像要说些什么哟。」

我因西莉卡的声音而再次转过身，看向圆圈的方向。

宣布优胜者是津风吕的迪克斯，向前迈出一步后喊道：

「获得优胜的津风吕，给予的赏品是一百个杂草团子以及和桐人先生的挑战权！但因为桐人先生现在正攻略第二阶层，没有决定回到拉斯纳里奥的日期！因此挑战比赛的日期，决定后就会立刻在这里公布！」

什么啊—、不是今天吗—，我一边听着纷飞的起哄声，一边想要慢慢地往后退。但后退了连50厘米都不到的距离时，双肩被后面牢牢地抓住了。

「桐人，既然如此，那现在就战斗吧？」

「欸欸……？」

越过肩膀往后一看，亚丝娜在兜帽深处的脸微微一笑后继续说道：

「大概，迪克斯先生有在考虑些什么哟。要是去了ApD组的据点的话，就不知道什么时候才能回来了，就先解决能解决的事吧」

「那倒也是……话是这么说……」

我一边点头，一边冷静地思考。

确实，我认为迪克斯应该不是单纯的为了热闹、而且在没有与当事人的我商量的情况下举办这样的活动。大概，和现在拉斯纳里奥的状况有某些关系吧。带着疑问去ApD的据点并不舒服，而且——如果是被要求参加比赛的话，总比谈判和演讲强一些。

「那么……就稍微去一下」

告诉两人后，我从人墙中大步地走出去。

「那是谁？」「是乱入者吗？」

我一边听着这样的交谈声，一边笔直地接近迪克斯。

弯刀使虽然一瞬间露出惊讶的表情，但发现兜帽里的人是我后，将眼睛瞪圆了。但惊讶马上就消失了，接着用下定决心似的表情靠近我：

「桐人先生，等等再说明。现在先什么都不要问，和津风吕对战好吗」

「那倒是没关系，要是我输了会怎么样？」

「那就会很麻烦了，所以可以的话就赢吧。拜托了……但裁判是公平的呐」

小声说完「真是难以想象的情况」后，迪克斯从我身边离开，大声地喊道：

「Ladies and 混蛋们！」

在圆圈外面喝了恢复剂的津风吕迅速地转过身来。站起来离开的观众们，也「怎么了怎么了」地再次聚集到一起。

「你们真是lucky啊！居然，现在决定要再进行一场比赛了！」

「哈……？那家伙，是谁？」

津风吕皱起眉头，即使看向我的头顶也没有改变惊讶的表情。

Unital ring里面原则上除了队伍成员（party member）和团队成员（raid member）之外不会显示光标。例外只有处于敌对状态的玩家，以及在系统选项中更改光标的公开设定的玩家。刚才的津风吕和单手剑士，应该是为了让裁判迪克斯和观众们能把握HP还剩下多少，才更改成「HP条全体公开」吧。我也叫出环形选单，更改光标的显示设定。

迪克斯向露出不理解表情的津风吕伸出左手，大喊道：

「蓝方……队伍『广播酱粉丝俱乐部』的领队，『求道的声音御宅』……津风吕哦哦哦——！」

津风吕以破罐子破摔的气势高高举起右手，周围的观众们也送出了气势磅礴的声援。

声援平静下来后，迪克斯向我这边举起右手——

「红方……拉斯纳里奥的现任领主，『黑衣剑士』……桐人哦哦哦——！」

为什么要干这种事……我一边这么想一边抓住兜帽，啪一声扯了下来。

欢呼声平息了，不久后压力提高……爆发了。快速地看了一圈周围，十时路和二时路，连后方的内圈道路上也渐渐聚集起观众。

在声援声中，津风吕迈着大步靠近了。双手剑就这么收在后腰上的鞘里，双手似乎也为了表示是空手而张开手掌。

「桐人先生，你回来了啊。」

面对露出无畏的表情搭话的津风吕，我也空着手回答：

「嗯，刚回来。」

「这样的话，你还不知道发生了什么吧。虽然在这种状态下要和我战斗这点很抱歉，但既然出来了，那就没办法了。」

用普通的声音说完这些后，津风吕猛然指向我的脸，用所有观众都能听见的粗哑声音喊道：

「桐人先生，虽然很感谢你将我们从穆达希娜的狗屎魔法下解放出来……但这个居住区已经到极限了！要是我赢了的话，就干脆地把统治权让给我！」

什么么么！

我差点这么大叫，好不容易才压了下来。虽然想到了这个突发的决斗淘汰赛和拉斯纳里奥的过密状况有关系，但没想到居然要赌上统治权。也就是说，如果我输掉这场比赛的话，作为拉斯纳里奥主体建筑物的小木屋的所有权，就会让渡给津风吕吗。

只向右转动眼球，看向在观众前列站着的亚丝娜。事情变成这样果然是出乎预料，兜帽下的嘴微微张开着。

一瞬间还以为她会冲进圈内大喊「不能做这种事情！」，但亚丝娜马上就把嘴合上，然后轻轻耸了耸肩。简直像在说「赢了就没问题了哟」。

就算这么信赖我……我一边忍不住露出苦笑，一边呼出环形视窗，装备上「上等的钢制长剑」。左腰上增加了可靠的重量。

应该是明白这个动作是答应了的意思吧，津风吕嘴角上扬地说道「必须这样才行」。然后走到后方的圆圈东侧上的起始线后回过头来。

我也向后退，将右脚尖对准西侧的起始线。

迪克斯从圆圈中出去，高高地举起握着小锅的左手，和握着大勺的右手：

「比赛时间没有限制！为初击决胜规则，走出圈外也算输，有TKO（technical knockout 技术性击倒 拳击用语，未打倒对方但对方受重伤，无法招架，由裁判员停止比赛，就是TKO）！双方，拔剑！」

津风吕将背上的双手剑拔出，我则是将左腰上的单手剑拔出，两人都摆出中段的架式。和刚才的决胜战的武器组合是一样的，不同的只有我没有拿着盾牌这一点。

津风吕目不转睛地盯着我的手部动作。他将视线固定住，是因为有什么作战而不想让我察觉到的心理在作祟吧。但我并没有什么计策，思考的只有一件事……别在无意识中想用心意。

大约过了五秒，迪克斯猛地用大勺敲击了小锅的底部。砰硿—，响起了略微有些不合拍的声音的瞬间，津风吕就一口气向前突进了。

拿着大剑缩短和自己的距离是无视理论的行为。是打算趁我大意的时候冲撞过来——这在剑道中被称为「打咬」——然后直接将我撞出圈外吧。虽然也可以向左或向右闪避，但我感觉津风吕似乎也想好了如何应对。

我瞬间做出决定，用全力踢了地面。既不是向左也不是向右，而是向前。

在圆圈的几乎正中央，剑与剑发生了激烈的碰撞，「gii—nn！」轰响了像是要袭击耳朵一样的金属声。

虽然武器的大小方面输了，但可能是因为「击退敌方概率上升」的「反弹」能力的效果，我和津风吕以相同的速度向后方弹去。

津风吕踉跄地站稳身子，接着稍稍举起双手剑，然后又放了下来。恐怕是考虑在姿势回复的一瞬间发动剑技，但又觉得间隔不够吧。

在决斗中，避免剑技的「乱放」——也就是避免听天由命地单次使用剑技是最基本的。用通常技使对手的姿势崩溃，再在即使能防御也不能回避的时机发动。如果剑技落空了，因为被赋予了硬直时间的缘故，仅凭这一点就足以决定胜负。也就是说津风吕的判断是正确的。

但是，在这个系统中，有着在ALO才第一次接触剑技的玩家们所不知道的深奥之处。

我趁着上半身还在晃动的时候，将剑往右肩上方移动。

所有的剑技，都是把武器以固定的角度放在固定的位置，再经过规定的蓄力时间后发动，放出速度和威力被特殊化的攻击后，最后经过规定的硬直时间（delay time）结束。

大多数玩家，都认为从剑技发动时到解除硬直所需的时间是系统固定的，但在这一串动作中，规定的只有蓄力时间和硬直时间而已，除此以外的都可以靠玩家的技术来缩短。比如说，只要身体中心线的位置和角度正确的话，即使在被击退的途中或是在跳跃中，也都可以发动剑技。

在回复姿势前就输入完蓄力动作的我，将所有神经都集中在从背后摆好姿势的爱剑的剑柄中传来的轻微震动上。因为在蓄力时间中会产生鲜艳的光效与尖锐的音效，所以在以前会用那个光效与音效来预测蓄力完成的瞬间，但因为光效与音效在剑技发动后也会持续，所以除非使用秒表，否则无论如何都要靠直觉。但是，震动在蓄力时间开始时会同时出现，但在蓄力到中间时会变得最强，在结束的同时消失。虽然是相当细微的变化，但只要能感受到这种二次函数式变化的话，就能用相当高的精度来预测出蓄力时间结束的瞬间。

在我脑海的一角，我一边感到鞋底紧紧抓住了地面、后倾的躯干向前倾的同时，一边将力量集中在左脚上。假如、即使踢向地面的时候比蓄力时间结束快了零点一秒，剑技也会中断。传到右手上的震动开始衰减、变得更弱……消失了、在这个瞬间。

「……！」

伴随着无声的气势，我全力地用左脚踢向地面。包裹着爱剑的剑身的蓝色光芒，变为了强烈的闪光。发动成功——

不知道前方的津风吕是否已经从踉跄的状态中回复过来，他的双手剑也还浮在半空中。我一边看着他粗眉毛下面瞪得圆圆的双眼，一边用全身的肌肉力量来推动剑技的系统辅助，几乎垂直地挥出了剑。

发出了清脆的声音，右手传来明确的命中感。由于调整为只有剑尖能命中，所以威力大概只有原本的七成吧，但应该给予了足够判定初击决胜的伤害。

我解除剑技硬直后站了起来。左胸上被刻上深红的伤害痕迹的津风吕，就这么保持着仰身的姿势，看着左上方——自己的HP条。

我也抬头看着津风吕头上的纺锤状光标。描绘出圆弧的HP条，正悄无声息地减少。两成、三成、在超过四成的时候多少吃了一惊，但在接近五成的时候停了下来，我不由得松了一口气。

「……抱歉，稍微减的有点多了」

我刚一如此道歉，在圆圈外面发愣的迪克斯慌忙地用大勺击打单手锅，用有些变调的声音喊道：

「到此为止，到此为止！胜者……桐人！！」

在短暂的寂静之后——

哇啊啊啊！这样的欢声包围了厩舍的前庭。

「那个速度是什——么啊！从摆出架式到挥完有两秒吗！？」

「比起这个是射程（更惊人）吧！明明只是『垂直斩（Vertical）』，却像『音速冲击（Sonic Leap）』一样跳了哦！？」

「不如说是威力吧！明明只是擦过，为什么会减少那么多哟！」

我一边听着观众们七嘴八舌的喊叫声，一边将剑收回到剑鞘中。我轻轻地拍了拍还在发呆的津风吕的左手肘：

「辛苦了，最开始的咬啮相当不错哟。」

「…………不，没关系……」

津风吕无力地摇头，像是转换心情一样用力收回双手剑，从正面看着我：

「虽然决斗是完败了，但这个居住区有点不妙也是真的。说起来，举行这样的大会的原因是……」

「不，我大概知道。」

我点头后，朝着圆圈的中央移动。环视一圈还在吵嚷着的观众们，我深深地吸了一口气——

「各位，抱歉我一直没有在家！」

我大喊过后，不知何时已经增加到一百人以上的观众们都突然沉默了。

「关于拉斯纳里奥的情况我已经理解了！虽然打算在今天再提高一级加护等级，但不知道附加耐久度的效果范围会不会扩大！」

刚一说完，就传出了「欸欸——」「那就把中间的土地开放啊——」的声音。我等到声音平息后，再次开始告知：

「但是，有别的解决方法！其实，现在在第二阶层的起始点，正在进行新据点的建设准备！地点已经定好了，在做好应对怪物袭击的时候，就预定完成为主体建筑物！」

刚一说完，这次则是响起了充满期待的喊叫声。我对站在前列的亚丝娜和西莉卡送去视线后，进行了总结：

「下一个据点，完全是攻略的最前线！从那以后，不管是地形还是生活的怪物，都完全不明白！所以比拉斯纳里奥要危险的多，但即使这样也OK的话就欢迎移居过去！去也没关系的家伙们，现在就在这里尽情大喊吧！」

我的声音伴随着回音消失了，几秒钟后。

呜哦哦哦哦哦——！这样的大吼声让拉斯纳里奥全体震动了。

因为被吼声刺激到了吧，从中央厩舍的窗户中，棘刺洞穴熊米夏探出头来，「咕噜哦哦哦哦哦——！」如此的吼叫了。

** 12

整合机士团长艾欧莱恩・赫伦茨，别说真正的双亲的长相了，就连双亲的名字都不知道。

自己是星界统一会议的现任议长——虽然当时是地面军的总司令官——欧瓦斯・赫伦茨的养子这件事，是在北圣托利亚幼年学校小学三年级时知道的。在与年长一岁的哥哥卢古兰（ルグラン）因为无聊的事情吵架的时候，激动的哥哥怒吼了。你明明是个领养的孩子，这么吼道。

看来，欧瓦斯似乎禁止他的三个亲生孩子中比艾欧莱恩年长的两个——卢古兰（ルグラン）以及比他大两岁的姐姐，说出艾欧莱恩是养子这件事。

也就是说卢古兰在那个瞬间，虽然是因为冲动，但还是打破了上位者的命令。他当场倒下，捂着鲜红的充血右眼哭喊着，然后发高烧躺了三天三夜。

被欧瓦斯和母亲吉尔（ジル）问道发生了什么的艾欧莱恩，只能传达了事实。然后两人小声商量一会后，让艾欧莱恩坐到沙发的正中间，一边从左右两边牢牢地抱着艾欧莱恩，一边告诉他事实。

艾欧莱恩和卢古兰说的一样，并不是两人亲生孩子的事。真正的双亲已经不在人世的事。以及、即使没有血脉相连，父亲、母亲也深深地爱着艾欧莱恩的事。

听见这些话后觉得很高兴，但也觉得很抱歉。因为艾欧莱恩在得知自己是赫伦茨家的养子时，比起震惊与悲伤，首先感觉到的是理解了的感觉。至今为止在这个家里生活时，偶然感觉到的细微违和感的理由就是这个吗。

在已经二十岁的现在，也很明白卢古兰哥哥如此敌视自己的理由。

赫伦茨家是由既是初代整合骑士团长、也是传说中的武人贝尔库利・赫伦兹所建立的历史悠久的名家。虽然贝尔库利和第一次黑皇战争的英雄、第二代当家贝尔切・赫伦兹的剑术才能，都继承给了第六代的已故养祖父狄里安和第七代的养父欧瓦斯，但继承最浓厚的血的，恐怕不是长男卢古兰和三男伊德利斯，而是长女弗尔菲斯吧。

她现在正担任着Under world三军之一的黑耀军副司令官而待在奥布西蒂亚市。{译：奥布西蒂亚市，桐人和罗妮耶在19卷中前往的暗黑界首都，名字来源于黑曜石“Obsidian”，UW三军：地面军、宇宙军、黑耀军。另外，请注意这里的“黑耀军”并非黑曜石的“曜”，而是照耀的“耀”}

黑耀军的前身是在异界战争中和人界军战斗的暗黑界军。虽然在讲和成立之后，构成军队的亚人和暗黑界人也没有简单地消除对人界人的反目感情，但在暗黑界军初代总司令官伊修凯恩和成为了他的伴侣的整合骑士谢塔・Synthesis・Twelve，以及两人的女儿，第二代总司令官莉泽塔・扎勒的努力下，在（人界历）400年前半以统一人界军驻留部队和暗黑界军的形式而创设了黑耀军。

自那以后，黑耀军就持续着总司令官是暗黑界人、副司令官是人界人的传统，去年——星界历581年的春天，地面军第三方面部队长弗尔菲斯・赫伦兹被任命为了新的副司令官。

她当时年仅21岁。16岁时加入地面军，仅仅三年就晋升为统领千名士兵的部队长，又在两年后获得了大提拔。但是，「难道不是因为偏袒她这个星界统一会议长的女儿才进行人事变动吗」，这种的猜疑声却几乎没有。这是因为她年仅15岁时就获得了统一武术大会的优胜这样压倒性的实绩吧。不过最年少记录在数年后就被天才剑士丝缇卡・休特里涅和罗兰涅・阿拉贝尔给轻松地更新了。

虽然这么说，弗尔菲斯也从小就表现出超群的剑技和学问，被传言道会成为赫伦兹家的第八代当主。但因为赫伦兹家直到欧瓦斯这代，一直都是由长男继承家业的家族，所以卢古兰应该感到了相当大的重压和劣等感。一定，积攒的阴暗感情所能发泄的对象，只有没有血缘关系的弟弟艾欧莱恩而已。

了解这些时虽然已经十几岁了，但在艾欧莱恩被说是「领养的孩子」之前，就用幼小的心灵感受到了哥哥的郁闷，因此一直无意识地试图避免引人注目。几乎没有朋友，上完课后就直接回家，在赫伦兹家后院中耸立的巨大黑色杉树下面一个劲的挥舞木剑。

但是，在那个事件的几个月后——升到幼年学校的四年级的时候，姐姐弗尔菲斯少见地出现在后院，注视了一会艾欧莱恩的空挥后，就强行把他拉到了修练场。从那天起，即使不能每天都抽出时间来，也还是开始指导了艾欧莱恩。姐姐的指导是脱离常轨地严格，是连作为武人而出名的父亲欧瓦斯都提出了劝告的程度，但艾欧莱恩很高兴。无论被木剑多么激烈地击打，也一次都没有发出泄气话，贪婪地吸收着从初代贝尔库利连绵传承下来的赫伦兹家的技术。{译：虽然贝尔库利没见过自己的儿子就是了}

不久后，指导触及到了神圣术和心意术，这段严格却又满足的日子，一直持续到了弗尔菲斯晋升到地面军的部队长为止。艾欧莱恩当时16岁，成为了北圣托利亚修剑学院的首席上级修剑士。

那一年，艾欧莱恩比姐姐晚了一岁获得了星界统一武术大会的优胜，因此特例立刻毕业加入了宇宙军。因此，现在的艾欧莱恩，全部——虽然不能这么说，但至少有九成是多亏了姐姐弗尔菲斯。

但没想到，因为前一代的指名而就任了整合机士团长，在指挥系统上甚至是能指挥黑耀军副司令官的姐姐的立场。

然后，也没想到这成为了现在是地面军一级队士的哥哥卢古兰、和父亲欧瓦斯不和的原因……

咔啦。

融化了的冰发出的声音在室内回响，艾欧莱恩睁开了面具下闭着的眼睛。

房间的内装虽然很简单，但有着和宇宙军基地的私室差不多大的面积。家具是床和桌子、沙发、写字台和椅子，以及衣橱。不管哪个都是轻金属制的，并用螺栓结实的固定在了地板上。理所当然——因为这个房间处在空中漂浮的机龙内部。

桌子上的是，不久前由士兵送来的装着午饭的托盘。豪华到不由得想「是不是送错地方了」，主菜是充分地浇上浓厚水果酱汁的烤（roast）鹿肉。但是，被软禁着的俘虏，是不可能会仔细享用这种东西的。明明像是诺尔基亚（ノルキア）瓜三明治之类的就可以了......一边这么想，一边只吃了圆面包和汤，还有冰水，剩下的都放在那里了。

——不，如果是桐人的话，在这种状况下也一定会一下子全部吃完吧。

清楚地想象出那个样子，艾欧莱恩靠在沙发上小小的笑了。

在宇宙军基地的办公室里昏迷，到在这个房间里醒来后，已经过了六小时以上的时间。虽然墙上的时钟指示着下午两点，但因为室内没有表示日期的东西，所以不能保证今天是袭击的第二天，也就是12月8日。士兵所告诉的，只有这个房间是皇帝阿格马尔・威斯达尔斯6世的座机，超大型机龙「Principia」的内部，以及艾欧莱恩变成了俘虏而已。

因为连一扇窗户都没有，不管是外部的状况还是机龙现在的位置都不知道。但恐怕，既然是滞空着的话，那就没有从圣托利亚上空移动吧。虽然很担心中央大圣堂和宇宙军基地变成什么样了，但大圣堂有整合骑士爱丽丝，而基地有桐人在。拥有着连艾欧莱恩都望尘莫及的力量的两人，一定能守护住两边才对。

正因为如此确信，才难以饶恕在战斗中失去意识、轻易地被俘虏的自己的孱弱。

艾欧莱恩感觉到自己变得容易疲劳是在5年前，入学到修剑学院的时候。眼睛的皮肤对索尔斯的光变得敏感，不得不在白天戴上面具也是在那个时候，但还是疲劳的问题更严重。如果勉强一下的话，即使天命数值没有怎么减少，全身也会轻飘飘的、变得使不上力。简直像是，自己的存在本身变得稀薄化了一样的奇妙感觉。

明明从在办公室昏迷到在这里醒来，应该睡了接近八个小时，却依然略微残留着那种感觉。但是，不能吐出泄气话。就这么一直被软禁着的话，不久之后就会被桐人就出去吧。但在他那不讲道理的心意力将Principia给撕裂成两半之前，可能的话想要靠自己来逃离。

门只有一扇，在外面站着两个士兵。打开门的话，虽然可能用「将自己从他人的认识中完全消去」的「空之心意」来逃脱掉，但发现艾欧莱恩从房间中消失了的士兵也明白（发生了什么），立刻就会将警报给拉响吧。在那种状况下，到底能不能到达机龙中连接外部的门呢。

空之心意对艾欧莱恩来说，比战斗时的消耗都要大。但在阿多米娜的秘密基地中，仍然不敢相信居然持续了那么长的时间。

那时，为了使桐人也受到隐蔽效果而牵住了他的手。感觉到从那明明看起来很纤细，但却有力而温暖的手掌中，像是流入了某种力量一样。而且在那之后还剩下了和托科伽・伊斯塔尔战斗的力气，如果实际上真的是桐人的功劳的话，那解开这个现象说不定就能知道疲劳的原因。

「……真是的，不可思议的家伙呐。」

从嘴里，发出了微弱的声音。

艾欧莱恩注意到自己又在微笑了。只是想起来桐人手掌的温暖，虽然只有一点，但感到体力好像回复了一样。

他是否真的跟星王桐人是同一个人，现在也没有确信。

星王是直到一百年前都在统治着Under world的真实存在的人物。养祖父

狄里安・赫伦茨似乎从作为骑士来侍奉星王的（养祖父的）父亲和祖父那里听说了许多故事。然而，存在的神秘性在某种意义上比贝尔库利还要高。近年来，认为星王是童话中的登场人物的孩子们不在少数——据丝缇卡她们所说。

那位传说中的统治者突然回到了Under world中，而且说自己失去了记忆，一时之间是难以接受的。交谈过后，只认为他是同年代的极为普通的年轻人……但，那可怕的心意力，和达到了三位数的权限数值并不寻常。

艾欧莱恩想要在这个世界中他最喜欢的地方——隐藏在宇宙军基地附近的森林中的宅邸，准备好美味的葡萄酒和奶酪，只和桐人两个人一起尽情地交谈。既想要了解他的事情，也想谈论自己的事情。至今为止没有跟任何人说过的，不知道自己到底是谁的不安感，想要如实地说出来……

因为突然涌上来的强烈冲动，艾欧莱恩的身体小小地颤抖了，在这个时候。

门被打开了，穿着制服的士兵走进了房间。

虽然以为肯定是来撤饭的，但士兵在入口停下，向艾欧莱恩敬礼后，用谨慎的语气说道：

「整合机士团长殿下，请您同行。」

「……明白了。」

虽然很在意如果说不愿意的话会怎么样，但别说剑了，连一把小刀都没有，而且士兵的腰带上挂着大型的电击剑。于是老实地点头，站起身来。

虽然感到有些头晕，但摆出假装不知道的表情站稳脚，走到了入口。士兵再次敬礼后，从门边出去了。

外面的走廊异样地长，这说明了机龙的巨大。金属地板上响着两人份的脚步声，走了接近100Mel后，在走廊的尽头向右拐登上楼梯。又前进数十Mel后，终于出现了像是目的地的门。

表面贴着玻璃，用银来镶边的奢华的双开门，无论如何都不认为是机龙的设备。右边的门上埋着的是盾和飞龙的纹章，左边的门上则是八根锐利的菱形呈放射状排列的八芒星的徽章。虽然右边的是在遥远的过去灭亡了的威斯达尔斯西帝国的纹章，但对左边的就没有记忆了。门的两侧，等候着佩戴的不是电击剑，而是真正的剑的士兵。

将艾欧莱恩带到了这里的士兵敬礼后，左侧的士兵回礼后按下了墙壁上的按钮。听到了风素密封罐的工作声后，门往左右两边打开了。

「请进。」

士兵如此说完后就退到了旁边。艾欧莱恩点头后就跨过了门的导轨。

是非常深的房间。地板上铺着镶有银线的黑底绒毯，左右的墙上似乎有窗户，但都被装甲板封闭上了。灯光只有埋在天花板里的几个光素灯而已。

挺起胸膛，向着绒毯的中央移动。前方深处的地板呈阶梯状上升，在阶梯前面站着4名守护的士兵。

在高了两级的台上，安置了椅背异常高的椅子，在上面坐着一个男人。

衣襟呈褶状展开的衬衫和黑色裤子。脸像是刀削一样锐利，蓄着细细的胡子。双眼则是，像冰一样冷的灰色。

椅子的右后方，也站着身穿暗灰色大衣的年轻人。即使不看他像是波浪一样光润的黑发和惊人的美貌，光凭气息就知道是谁，是和艾欧莱恩在修剑学院时代就有因缘的，托科伽・伊斯塔尔。

艾欧莱恩将视线再次转回正面的同时，男人开口了：

「虽然不会说要你跪下，但至少把那煞风景的面具取下来如何……艾欧莱恩・赫伦茨先生？」

「非常抱歉，皮肤很脆弱，所以只能这样失礼，阿格马尔・威斯达尔斯6世陛下」

艾欧莱恩如此回应后，男人——皇帝阿格马尔哼了一声：

「无所谓——伊斯塔尔就没必要介绍了呐？」

「是的」

点头后再次看向了伊斯塔尔，但脸上保持着完全没有表情的样子。

「那么，只介绍她吧」

……她？

艾欧莱恩一边感到惊讶，一边凝视着椅子的左侧。然后，稍微吸了一口气。

不知何时，和伊斯塔尔相对的位置上，出现了新的人影。但房间的后面没有门，而且也没有听到脚步声。仿佛，像是从一开始就站在那里却没有认识到一样——

是女性。身穿像是古代的神圣术师一样的纯白长袍，并披着同色的披肩。胸前有闪耀着银色光辉的锐利八芒星徽章。看起来像是和在门前上描绘着的纹章完全相同的形状。

长发是浓紫色，小小的脸蛋比起伊斯塔尔有过之而无不及，有种超凡脱俗的美。俯视艾欧莱恩的双眸也是紫色，但简直像是镜子一样，完全无法窥视到内面。

突然，女性薄薄的嘴唇上浮现出了淡淡的笑容：

「我自己报上名字吧，陛下。」

像是转动冰所做成的铃铛一样的，清澈的美声。

「是吗？」

阿格马尔耸了耸肩后，女性向前迈出一步，轻轻地行了一礼。

抬起头，用深蓝紫色的眼瞳目不转睛地注视着艾欧莱恩——

「初次见面，艾欧莱恩・赫伦茨大人。我是，诺兰高尔斯皇帝家的后裔……穆达希娜・穆伊奇里」

（待续）

后记

（以下括弧中的内容，都是川原本人写的，并非译注）

经过非常非常非常漫长的等待后，Sword Art Online刀剑神域第28集〈Unital ring Ⅶ〉终于送到各位手上了。

居然是距离上一集1年又8个月的新刊，这恐怕是SAO史上最长的等待记录了……虽然说是更新了记录，但对于这次的更新还是有在反省，所以下一集想要早点更新！现在在心底这么发誓！

（请注意，以下内容会触及到本篇的内容。）

关于故事方面也有稍微提到。主要是发生在Under world的事情。在上一集登场时，散发出差不多二十二分钟后就会丢下「别以为这样就赢了哟！」这种台词然后逃走的气场的皇帝陛下，但意外地很努力呢！似乎在下一集也会发挥像是反派角色的样子。

然后这一集，有了SAO原作本篇没有前例的「来自其他衍生作品的合流」，实现了两个角色的登场。

首先第一位是，手机游戏「Alicization Blading」也就是「Unleash Blading」中的原创女角色，整合骑士伊迪丝 Synthesis Ten。因为在上一集写了「第十位整合骑士」在中央大圣堂被冻结着，所以确定了总有一天会登场的整合骑士。虽然稍微烦恼过到底是完全设定一个新骑士，还是用「UB」的伊迪丝来逆输入，但考虑到还是有不少读者大人喜欢伊迪丝 Synthesis Ten这个名字，所以让她在这一集登场了。但当然有很多设定和「UB」中的不一样，这一点我会在后面说明。

然后第二位是，「剧场版Sword Art Online刀剑神域 Progressive无星夜的咏叹调/黯淡黄昏的谐谑曲」中登场的米特/兔泽深澄。她是个由来相当复杂的角色，虽然在至今的采访中，我都是回答了「在制作这次的电影时，接受了『想要登场一位亚丝娜在现实中的挚友地位的新角色』的要求而做了设定」，但其实不是从零开始想的。

收录在第8集的〈圈内事件〉中，玩家名为阿修雷的能干裁缝师虽然只出现名字，但还是登场了。她的「和亚丝娜在现实世界也曾经是朋友」、「亚丝娜和桐人的小队关系解除后，在这个精神上的痛苦时期成为精神上的支柱」的设定从web版开始就存在了，我一直想在此基础上写亚丝娜和阿修雷的故事，但一直没有实现，但在听说剧场版Progressive要有新角色时，最先想到的就是阿修雷。然后，我重新以阿修雷的设定为基础，再进行加工，最终诞生的就是米特。

之所以一直保密到现在的理由，是因为我希望第一次提到「米特=阿修雷」的情报是在作品中，而不是在采访或者SNS中（虽然在十周年纪念活动「full dive」的朗读剧中稍微触碰到了一点），但在两部剧场版中也没有真正进展到这一步，虽说如此，让她在Unital Ring篇中登场这件事，也没有确信这是必然的而不是强行加入的，所以我认为这可能暂时无法实现，但在我写着这个28卷时，直觉突然告诉我「不是现在吗？」，于是名正言顺地让她和亚丝娜的重逢变成了现实。

话虽如此，要完全沿袭剧场版Progressive米特的背景还是很困难，她和伊迪丝一样，电影和原作中的设定都变得不一样了。总而言之，可以归纳成下面这样。

【伊迪丝】

・三百年前（Alicization篇的一百年前）被石化冻结，在那以后的事情，特别是有关异界战争的事情完全不知道。和爱丽丝也是初次见面。

【米特】

・在SAO初期没有和亚丝娜碰面，当然也没有在尼本特森林里将亚丝娜抛弃。{译：第一层发生的事}

・没有参加第一层、第五层的BOSS攻略。{译：完全被打成平行世界了}

因为在尼本特森林里的事是剧场版米特的根基部分，所以我在想整件事情都没发生会怎么样，但剧场版的烙印是在是太大了，所以原作版的米特不如也想要消除罪恶感，如此考虑后就这么写了。虽然这么说，但在艾因格朗特里面也不是完全没有痛苦的事情，米特正确的来说是「第二代阿修雷」，从初代那里继承了阿修雷的名号。至于发生了什么，我想总有一天会在本篇里告诉大家。虽然可能是画蛇添足，但米特从SAO中被解放以后就没有玩VRMMO了，阿修雷的名字传到了第三代。

虽然只打算写一点后记，但没想到写了这么长，我希望大家能像游戏版和剧场版中的一样支持上述出现的小说版伊迪丝和米特，这样我会很高兴的。

然后，这一卷首次出现了以艾欧莱恩为视角的章节，稍微了解了一直被谜包裹住的，他的主干。因为菊冈先生在意的像是「侵入者」的人登场（再登场？）了，所以希望大家一边想象两个世界会发生什么关系，一边享受其中的乐趣。

这一卷的日程应该很充裕，但结果还是勉强了，给担当编辑三木先生和安达先生，插图的abec先生等相关人员的大家添了很多麻烦。读者大人们也是，我会继续努力的，请大家多多支持！

2024 年4月某日 川原砾

译者后记

大家初次见面，我是B_Meow，也可以叫我B喵。

可能有人在贴吧里经常看见我吹水，但我认为还是第一次见到我的多。这是我第一次翻译，有很多不足，甚至有好多不懂的句子，这点请大家多多包涵。由于整卷是我一个人翻译的，并没有校对，我也不知道到底有多少句子偏离了川原想要表达的意思，只能私密马赛了Orz。

我为什么想要翻译刀剑呢？在我听说rkl大佬单刷完18卷的时候，我就想总有一天自己也要翻译完一本刀剑。但在那时我甚至还没有开始学日语，因此只能等下去，直到现在。几个月前我听说28卷的发售日期正好在假期中，我就知道我一定要翻译完28卷了。这就是川原后记中所说的“直觉突然告诉我「不是现在吗？」”吧。

但当我真的拿到书的时候，我还是退缩了，接近300页的内容、各种片假名、各种新固有名词都在阻止着我翻译，我也曾考虑过只翻译完UW的部分就跑路，但最终还是翻译完了（虽说翻译的不好就是了）。

翻译这件事真的很难，意译的太多就会偏离作者想要表达的意思，在本次的28卷中，前4章意译的比较多，最后的几章基本都是直翻，连日语的语序基本都没有改，因此可能会觉得读起来有些不通顺，这就是取舍的问题了。

正在读这个后记的想必也都是热爱SAO的人吧，希望大家还是能去看拉斯翻译的（这次也给拉斯添了不少麻烦）。

B_Meow 24年8月8日


