#+title: 刀剑神域 第二十三卷 Unital Ring Ⅱ
#+setupfile: ./setup.setup
* 第二十三卷 Unital Ring Ⅱ

台版 转自 深夜读书会

论坛：ritdon.com

书名：Sword Art Online 刀剑神域

作者：川原 砾

插画：abec

————————————

内容简介

★在个人网站上连载时创下650万人次浏览记录！

★未知的新章节！融合了所有VRMMO的「VRMMOSVG」！

桐人和亚丝娜、爱丽丝被强制转移到谜之VRMMO游戏「Unital ring」时。

诗乃也被召唤到同样的世界里。

「我竟然会被逼入这样的状况中……」

经过数次失误之后，诗乃陷入没有伙伴、装备，

「Thirst Point」也仅剩些许的绝境当中，并且得为了生存而和魔王怪物战斗。

另一方面，桐人等人也分为两队，分别执行防卫家园与搜索诗乃的行动。

但是前方却有严酷的自然现象、强大的怪物以及准备袭击桐人他们的黑影在等待着──

** 第一章

喉咙好渴。

极为真实的口渴感让人难以相信这是AmuSphere所产生的虚假感觉。舌头失去水气，每次呼吸时喉咙也会感到疼痛。甚至会怀疑躺在现实世界的真正肉体是不是真的出现脱水症状。

想要先登出，把冰冰凉凉的水倒到杯子里再一口气喝光……虽然这么想，但是这个充满谜团的「Unital ring<UR>」世界里，脱离中的玩家虚拟角色也不会消失。虽然「口渴指数」会停止减少，但是即使在现实世界里面喝完水再登入，指数依然会维持减少状态。在缓冲期间已经结束的现在，一旦死亡就再也无法登入UR，所以最惨的情况可能是一次就失去所持道具以及角色。这是绝对得回避的情形。

因此诗乃／朝田诗乃一边忍耐着虚拟口渴感，一边为了寻找饮用水而在不毛的荒野里拼命奔跑。

跑步的话口渴指数的减少速度也会变快，但就算用走的也于事无补。现在只能相信在仅剩下一点点的口渴指数<TP>归零之前能找到水源然后继续奔驰了。荒野是起伏较少的地形，目测一公里左右的前方耸立着一座小岩山，其表面可以确认到一些类似植物的剪影。在那周围没有找到饮水处的话一切就都完了。

「……真是的……我竟然会被逼入这种状况当中……」

从干渴的喉咙里挤出沙哑的声音，同时回想起犯下的数个错误判断，诗乃接着便猛烈地咂了一下舌头。

六个小时前──二○二六年九月二十七日，星期日下午四点五十分左右。

诗乃登入到VRMMORPG「Gun Gale Online<GGO>」里，然后在高难度迷宫中狩猎会掉落稀有金属素材的机械型怪物。

自从在朋友们主要游玩的「ALfheim Online<ALO>」里开设帐号后，在那边游玩的时间就增加了，但诗乃还是完全没有从GGO里引退的打算。她还是认为只有黑卡蒂Ⅱ能够真正成为自己的分身，而且也想在下一届的Bullet of Bullets里获得完全优胜。之所以单独收集稀有金属，也是为了不让竞争对手们知道自己正准备强化黑卡蒂。

当好不容易将掉宝率不到三％的金属收集到距离目标个数仅剩下一个的时候，迷宫的地板就开始剧烈的震动，视界被七彩光芒笼罩，接着诗乃就被强制转移到地面。

出现的地方是某个不知名的都市角落。从略显阴暗的天空中撒下来的微弱阳光静静照射着灰色城镇。往前后延伸的道路上看不见任何人影。

自己也算是把GGO世界的地图整个逛过一遍了，但不记得曾经看过这样的街景。建筑物的外壁不是水泥而是用老旧的石头堆积而成，道路也不是柏油而是铺设了龟裂的砖瓦。茫然呆立在现场的诗乃周围不停有其他GGO玩家被传送过来，但每个人都只是呆呆地环视周围。里面也没有任何熟识的面孔。

虽然完全无法掌握事态，但是不喜欢这种被陌生男人们包围的状况，于是诗乃就准备潜入附近的建筑物里，确认里面没有居民后就躲藏在二楼的小房间内。她紧抱住黑卡蒂，竖起耳朵听地上的说话声。

十名左右的GGO玩家聚集到一处，开始商量起究竟发生了什么事。最后某个人注意到系统选单的UI完全不同，虽然试着联络营运企业但是也没有回应。

如此一来，就只能先登出到现实世界去收集情报了。GGO的社群网站以及各种SNS这时候应该都出现不少关于这场变异的留言了吧。听他们这么一说，诗乃也兴起登出的念头，但不知为何就是有不祥的预感，于是便先忍耐下来。

建筑外面的十个人不断操作奇妙形状的选单回到现实世界去了。再次降临的寂静当中，诗乃从没有玻璃的窗户往下看着道路，接着忍不住发出「咦」一声。

十个人的虚拟角色没有消失，而是呈现单脚跪地的姿势。这是经常在GGO与ALO里见到的待机姿势。许多的VRMMO当中，为了防止被怪物或者PKer追赶时「登出逃亡」，所以采取在户外即使登出，虚拟角色在几分钟内也不会消失的形式。现在既然适用这条规则，就表示这个都市不是受到保护的「城镇」，而是户外的练功区。不对，根本没有居民NPC存在的迹象，说起来这里根本不是什么城市，只不过是遗迹之类的地点吧。

如果是这样──

屏住呼吸的诗乃，耳朵听见某种喀沙喀沙的摩擦声。将视线往右移动，就看到几道细长影子从小路里爬出来。在灰色日光照耀下出现的是体长八十公分左右，将蜈蚣与蠷螋综合起来一般的昆虫型怪物。

从尺寸来看应该不是什么强敌。但是被锁定的GGO玩家们全部都处于登出状态。虽然他们背上发出乌亮光芒的突击步枪与雷射枪都算是不错的武器，但是无法扣下扳机的话就一点用处都没有。

「快点回来啊……！」

诗乃用力抓住窗框如此呢喃，但十个人都还是蹲着没有任何动静。蜈蚣们无数的脚在石头地板上发出喀沙喀沙的声音并确实地靠近。诗乃反射性把手往腰部后方伸去，想从枪套拔出副武器MP7。

但是在最后一刻就停手了。潜伏在附近的蜈蚣可能不只目前能看见的五只而已。枪声有可能会引来一大群怪物。虽然有为了这种时候所准备的MP7用消音器，但是因为在收集素材，所以为了减轻装备重量而把它收在道具栏里。已经没有时间操作选单视窗将其实体化，然后安装到枪口上。

当诗乃无法有所行动的期间，领头的蜈蚣就爬上其中一名玩家的背部，巨大的下颚深陷入其毫无防备的脖子内。深红特效光就像血一样滴落。蜈蚣们不断聚集到其他玩家身上。

诗乃认为就算在毫无抵抗的情况下持续被咬，他们应该还是能撑几分钟。蜈蚣怎么看都是低等怪物，而且男人们身上穿着的防具也算高级。

但是──

短短十几秒后，最初被咬的玩家就很轻易地变成蓝色多边形并且消散。其他玩家也不断地死亡。实在太快了……难道蜈蚣是出乎诗乃意料的强敌，还是说……

突然注意到某件事的诗乃，随即以生疏的手势打开环状选单。从八个图标当中触碰似乎是能力值的人型图示。看了一眼展开的视窗，诗乃立刻猛吸了一口气。

等级1。HP的最大值只有200。能力值遭到初期化了。

而且不只有这样。白色HP条下方还有绿色的MP条，然后再下方则出现蓝色「TP」条与黄色「SP」条。MP也就算了，根本不清楚TP、SP是表示何种数值。

但现在没有探究的时间了。再次从窗户往下看，发现已经有五名玩家的身影消失。蜈蚣群正逼近还活着的五个人。再这样下去，很有可能在有人回归之前就会全灭。

「……真是的……！」

小声咒骂了一下后，诗乃便拔出MP7。立起前握把并且拉出枪托，把选择器从保险的位置移到半自动。拉动枪身后部的枪机拉柄把首发子弹送进膛室，接着身体靠在窗框上来瞄准前头的蜈蚣。手指靠在扳机上并且微微用力。

「咦……？」

下一刻，她立刻从嘴里发出惊讶的声音。GGO里最具特色的两大游戏系统之一，也就是「着弹预测圆<Bullet circle>」没有出现。

是Bug、系统障碍，还是……等等，没有空犹豫了。遇见拥有妨碍着弹预测圆能力的怪物时，也有过靠着枪械瞄准镜来射击的时候。虽然是从二楼往下射击，但这种距离不用考虑弹道的变化也没关系。

诗乃对准蜈蚣准备咬下新猎物的头部并且扣下两次扳机。红黑色甲壳破裂，绿色黏液飞溅出来。第二发虽然有些偏移，但是出现在蜈蚣头上的奇妙形状HP条急遽减少，最后直接归零。临死前发出「叽咿咿！」悲鸣的蜈蚣整个后仰之后就跌落路面──却没有变成蓝色碎片往四处飞溅并消失。但是确实是死亡了。

迅速准备瞄准下一条蜈蚣的诗乃再次咂了一下嘴。剩下来的四只头上全都出现红色浮标。「被盯上了」的直觉果然成真，四只怪物改变前进方向往诗乃所在的建筑物爬过来。诗乃要自己不要焦急，对第二只蜈蚣扣下两次扳机夺走其生命。

接着剩下来的三只就发出喀沙喀沙的声音垂直爬上石墙。将选择器移到全自动发射，接着从窗户探出身体瞄准正下方。清脆的连射声响起，被4.6毫米弹轰中的第三只蜈蚣一边喷洒黏液一边掉落地面。

虽然第四只也步上同样的命运，但第五只却爬到了窗框。从口中长出的锐利大颚以及扬起的尾剪同时朝诗乃逼近。

诗乃不强行射击，只是用力朝窗框踢去。在后空翻的状态下重新架好MP7，着地的同时就开枪射击。一半侵入房间的第五只蜈蚣头部爆裂，细长身体无力地挂在窗框上。

「呼……」

诗乃下意识中确认着弹匣的残弹，并呼出一口气。

突然响起生疏的吹奏乐声，蓝色光环从脚边涌出直达头部。眼前出现讯息视窗。

【Sinon的等级上升为2。】

「等级2……」

忍不住叹了一口气。GGO内的诗乃在三天前才刚到达等级107。虽然营运企业ZASKAR发现异常事态后应该会将整个伺服器进行回溯，但是以单纯的系统障碍来说，这里的地图与怪物都太过正式了。简直就像不在GGO，而是被丢进完全不同的游戏里一样……

依然架着MP7的诗乃慎重地靠近蜈蚣的尸骸。用枪口戳了好几下后果然没有任何动静。于是她的左手便松开前握把，以指尖轻敲了一下尸体。

属性视窗随着「咻哇」的声音打开。窥看之后──

【赤腹剪刀蜈蚣的尸骸 素材 重量5．82】

赤腹应该是红色肚子的意思吧。跟背部比起来，侧腹部确实呈现鲜艳的红色。然后既然是素材，就表示……

诗乃把MP7放回枪套里后就准备从腰带上拔出小刀。但是手却碰不到握把。看了一下右腰，发现原本装备爱用野外求生小刀的地方已经空无一物。

「…………」

诗乃看了一下立在墙壁上的黑卡蒂Ⅱ并且歪起脖子。主武器、副武器以及防具类全都健在，只有小刀消失究竟是怎么回事呢？是后空翻的时候掉下来了吗──应该不会发生这种事情才对──心里这么想的诗乃环视室内，虽然没有找到小刀但是发现设置在墙壁边的柜子。

走过去一看之下，发现和GGO内常见的金属橱柜在外型上完全不同。真要说的话比较像是阿尔普海姆里头的老旧木制橱柜。拉开略显脏污的柜门，发现里面几乎没有东西，不过还是有一些碎裂的食器、一个内容不明的瓶子以及一把小型菜刀。

诗乃试着拿起菜刀。那看起来实在不像能够在战斗中使用的物品，最多只能用来削果皮，不过刀刃还是保持着锋利度。右手握住泛着铁锈的菜刀回到蜈蚣尸骸旁边。犹豫了数次之后就把菜刀用力抵在体节与体节之间的缝隙。

「沙喀」一声，令人感到畏惧的手感传到右手，让诗乃忍不住想放下菜刀，幸好只要一个动作蜈蚣的尸体就发出蓝色闪光消失了。同一个地点分别掉下几样道具。

【获得肢解技能。熟练度上升为1。】

诗乃看了一阵子这样的讯息后就耸耸肩把它消掉。躺在地板上的是数片红黑色板子以及两根弯曲的刺。捡起来点了一下后，各自显示为【劣质蜈蚣甲壳】与【劣质蜈蚣剪刀】。虽然不知道有什么用处，但是带在身上应该不会有损失。诗乃打开主选单，把甲壳与剪刀收到道具栏里。接着将菜刀插在腰带上，背起黑卡蒂离开房间并走下楼梯。

诗乃从玄关确认外面的模样。最后虽然以全自动模式大量开火，但是没有其他蜈蚣和怪物的气息。

蹑脚走到外面后，诗乃发现拯救的五个人仍处于待机姿势。于是她便先走到躺在附近的四只蜈蚣尸体旁边，以菜刀进行肢解并且将素材收纳到道具栏。

「蜈蚣的甲壳没办法强化黑卡蒂吧……」

这么呢喃完并深深叹了一口气时，终于发现到被蜈蚣杀害的五个人消失之处，掉落着五个黑色的袋子。

「…………」

即使感到犹豫还是靠了过去，把右手的菜刀插到腰带上后触碰其中一个袋子，结果袋子就变成环状光芒消失了。接着视界里就显示了新的讯息。

【获得AK74M。获得战术背心。】

「…………」

两者都是GGO常见的装备。早就已经猜想到黑色袋子里面应该是死亡玩家的掉宝。当然杀人的并非诗乃而是蜈蚣，但盗取遗留品总是让人感到不舒服。想着要把它们放回去而准备打开道具栏时才发现某件事。

几乎在所有VRMMO里，放置在练功区的道具经过一定时间后就会消失。虽然不清楚死亡的玩家会在哪个地方复活，但是发现武器掉落的话一定会尽快赶回来，所以在那之前还是先代为保管比较好吧。

如此判断之后，诗乃就停止将最初捡起来的掉宝道具实体化，改为回收其他四个袋子。因为对于道具栏剩下的容量感到不安而重新打开视窗，结果发现显示所持重量的标示甚至不满两成。

在受到不祥预感袭击下显示内容后，发现收纳的只有回收的十个遗物以及从蜈蚣那里入手的素材而已。原本在GGO世界里持有的道具已经消失得无影无踪。

「……真是的……」

诗乃叹了一口气并关上视窗。

虽说等异常事态结束之后道具应该就能复原，但到现在营运公司连公告都没有，这种情况确实让人感到奇怪。由于希望避免在这种状况下死亡而失去黑卡蒂与MP7，所以在开始回溯之前必须和爱枪协力存活下去才行……想到这里，诗乃就猛烈地吸了一口气。

道具栏的内容物全部消失了，就表示完全失去累积许多库存的黑卡蒂用12.7毫米弹与MP7用的4.6毫米弹。剩下来的子弹就只有黑卡蒂弹匣里的7发，以及腰带上交换用的MP7弹匣约40发。这些子弹射完之后，诗乃剩下的武器就只有在废屋的橱子里找到的一把生銹菜刀。

不对，正确来说，刚才回收的五人份掉宝武器以及子弹也在道具栏内。但是这时候带着它们逃走的话就真的变成捡尸者了。

早知道这样就不应该以全自动模式对蜈蚣开火……如此感到后悔的诗乃就静候待机状态的五个人重新登入。蜈蚣应该不久之后会再次涌出，六个人不同心协力的话很难存活下去。再次从枪套里拔出MP7，靠在废屋墙壁上着急地等待了三分钟。

终于有一名玩家的身体震动了一下，然后迅速站了起来。

「各位，要移动喽！这个遗迹的正中央……」

大叫到这里才终于发现听他说话的只有诗乃一个人。环视了一下周围后才压低声音对诗乃搭话。

「我说你啊，这里不是还有五个人吗？你知道他们到哪里去了吗？」

「很遗憾，他们全死了。」

诗乃耸耸肩这么回答，接着准备说明蜈蚣袭击的事件。

但是在她这么做之前，眼前的玩家──上下穿着灰色基调数位迷彩的光学枪使──就把挂在肩上的突击步枪朝向诗乃。

「你这家伙……是PK吗！」

「啥？」

发出内含惊讶与愤怒声音的诗乃，这才注意到刚才自己的发言在某些人耳里听起来就像是在扮演杀手。而且自己的右手还握着MP7。于是急忙放下枪口加以否定。

「不是我，杀死他们五个人的是蜈蚣！」

「根本没有那种东西吧！」

「为了保护你们，我把它们全干掉了！」

如此回答的诗乃为了将作为证物的甲壳实体化而准备打开视窗。但是男人突然就扣下步枪的扳机，发射出来的黄绿色雷射在诗乃右侧的墙上留下焦痕。

「喂！」

「别乱动！太卑鄙了，竟然趁人登出时下手！」

「就说人不是我杀的了！」

按耐下怒火如此反驳之后，愤怒的男人依然没有把手指从扳机上移开。还想再动的话，接下来应该就会毫不留情地开枪了吧。等级1──不对，刚升上等级2的诗乃，就算是单发子弹威力较低的光学步枪也可能会立刻死亡。这个时候，如果黑卡蒂掉宝的话，男人一定会把它当成战利品。

为了保护搭档，应该先发制人干掉对方吗？但是该怎么做？

新的声音扰乱了紧绷的空气。

「喂喂喂，这下不得了了！不只有GGO……」

其中一名待机者如此叫唤着并且站了起来，注意到拿枪相向的男人以及被瞄准的诗乃就夸张地仰身表示：

「你……你在做什么啊？」

「看就知道了吧！这个女人趁我们登出的时候杀了五个人！」

「咿咿……」

露出惊讶表情的第二个男人，从枪套里拿出大口径左轮手枪──应该是Sturm Ruger公司的Blackhawk。当进退两难的诗乃拼命寻找活路时，剩下来的三个人也接连觉醒了。

这时已经完全失去先发制人的时机。再来就只能祈祷其中有一名能够冷静听人说话的玩家存在了……当诗乃这么想时──

她的耳朵就听见熟悉的清脆声音。一瞬间动了一下视线，看见从五名男人左后方的某个道路裂缝中冲出两条长长的触角。一开始触角先摇晃了一阵子，最后长着巨大利齿的头与细长身体就爬上路面。赤腹剪刀蜈蚣重新涌出了。

男人们因为光学枪使不停大声嚷嚷而没有注意到危险。在内心呢喃着今天已经不知道是第几次的「真是的」后，诗乃便压低声音说：

「后面。」

「啥？你说什么？」

诗乃再度催促重新架好步枪的光学枪使。

「后面！」

「谁会上这种老掉牙的当啊，在被击中前先把捡来的道具……」

浑厚的悲鸣打断了男人沙哑的怒声。

「呜喔哇啊啊！」

「搞什么，怎么这么吵……」

稍微瞄了一下后方，结果连光学枪使都发出「嗯哦！」的怪声。他终于注意到从道路左侧爬过来的蜈蚣了。而且数量多达十只以上。

五个男人大大地往后飞退并且一起举起枪来。

就是现在……这是唯一脱离的机会了。赤腹剪刀蜈蚣的外表虽然恐怖，但是就只有被两三发MP7的4.6毫米弹击中就会死亡的HP。男人们的装备在中等以上，大量开火的话应该只要短短数十秒就能收拾它们。

听到第一声枪声的瞬间，诗乃就朝地面踢去。她一边把MP7放回枪套内，一边朝战场的反方向全力冲刺。明明被降到等级2却能背着超重量级的黑卡蒂Ⅱ奔跑确实是很不可思议，但是必须先存活下来才能弄清楚这种现象的原因。

不到五秒钟，就听见混杂在盛大扫射声中的喊叫。

「啊，那个女的逃走了！」

「可恶，快点把这些家伙干掉追上去！」

事到如今只能希望蜈蚣们多加油了，但最多也只能再撑十秒左右吧。在那之前必须先离开视野良好的主要道路才行。

光学枪使刚登入时曾经喊过「各位，要移动喽！这个遗迹的正中央……」。按照他所说的推测，接下去应该是「正中央有安全地点」才对。这样的话当然想到那边去，但是在被误会为PK的状况下实在很难到人多的地方。如此一来应该前往的就是城镇──遗迹外面了。

诗乃的脑海浮现一瞬间从废屋二楼所眺望的街景。记忆里窗子正面方向，也就是现在跑着的道路左侧聚集了巨大的建筑物。如果那里是市中心，那么郊外应该是右手边方向。

背后的枪声逐渐止歇。必须在被男人们看见前离开大路。小巷、小巷……有了。在五公尺前方。

诗乃全力倾斜身体，几乎是以连滚带爬的速度完成九十度转弯来冲进狭窄的巷弄里。在废屋与废屋之间，有一条宽一公尺多的窄路往前延伸。如果前面是死巷的话那就真的是走投无路了，但现在也只能相信自己的运气继续前进。

压抑脚步声跑了一阵子后，看到前方有三个半毁的木箱叠在一起。诗乃冲到箱子后面蹲了下来。

不到十秒，大路那边就有战斗靴子的沉重脚步声靠近。同时还可以听见透漏着焦躁的喊叫声。

「可恶，那个女的逃到哪里去了！」

「不是躲在那边的房子就是小巷子里吧？」

「要一间一间找吗，太麻烦了……」

「别抱怨了，她可是杀了我们五个人喔！」

「而且那个女人的狙步超稀有的哟。如果没有回溯，就算我们五个人平分也能大赚一笔。」

……诗乃皱起眉头想着「狙步是什么啊」，接着才注意到是狙击步枪的简称。以黑卡蒂的稀有度来说，在GGO里确实是最高等级，但是绝对不愿意让它被这群用如此俗气称呼的家伙卖掉。

如果男人们排成一列进入巷子的话，黑卡蒂的12.7毫米弹或许可以一口气射穿他们五个人。但这么做的话，就算是为了自卫也会沦为真正的PK。而且不想在这里用掉只剩下7发的子弹。

──别进来！

像是感应到诗乃这样的思绪一般，脚步声在巷弄入口放慢了速度。虽然看不见男人们的身影，但是可以强烈地感受到他们正在看这边。

诗乃在木箱后面悄悄卸下背上的黑卡蒂并用双手拿住。想着事到如今还是先把1发子弹装进膛室的诗乃，直接把右手放到枪栓上。五个人进入巷弄的话，必须等他们靠近到极限时才即刻上膛，然后在那群家伙对击铁声产生反应前射击。

一秒、两秒……三秒后。

「喂，有人躲在那些破箱子后面……」

冲锋枪轻快的发射声掩盖了这样的声音。贯穿木箱的实体子弹掠过诗乃的头发与战斗靴子。虽然反射性想从躲藏处冲出去，但还是硬挤出意志力来让虚拟角色持续静止不动。

「没人啊。」

「真是的，别突然就开枪啊。」

这样的对话与轻率的哈哈大笑声重叠在一起。即使五个人的脚步声远去，诗乃还是蹲着等了三十秒，然后才慎重地撑起身体。受到子弹射击的木箱出现许多裂痕，似乎轻推一下就会完全崩塌。

──你们马上就会对这次浪费子弹的行为感到后悔了。

在心中这么对男人们呢喃，接着诗乃就往巷弄深处跑去。

幸好狭窄的巷弄并非死巷，确实连接着新的小路。过去应该有许多居民在上方走动的石板道路，这时只有带着土尘的风吹过。到底发生了什么事才会让城市变成遗迹呢？说不定到中央部就能知道原因，但是目前已经无法靠近。

诗乃不知不觉间意识到自己开始认为这个世界并非系统错误或者人为失误所生成的异常地图，而是正规的VRMMO世界，同时持续朝着城市外面前进。虽然经常遇见蜈蚣、蜘蛛、蝎子型的怪物，但因为不能浪费剩下不多的子弹，只能够拼命奔跑来逃亡。早知道会这样，就应该把副武器从MP7换成光子剑……但这也只是事后诸葛了。

专心回避战斗并移动了二十分钟以上，眼前就出现高大的石墙。感觉得出明显是围住城市的城墙，不过是由平坦的石砖在毫无缝隙下堆积而成，一看就知道不可能爬上去。

诗乃捡起脚下的小石头，以拇指将其弹向正上方。由于落下的石头滚向右侧，于是她便顺着石墙往那个方向前进。

不到一分钟，前方就出现一扇巨大的门。祈祷着不要上锁并且靠过去后，立刻就知道自己是白操心了。厚重的两扇木门其中之一仍然健在，但另一边已经脱离铁制门框倒在地面。

诗乃暂时停下脚步，思考着自己离开这个城市的判断是否正确，但终究无法得到答案。唯一可以确定的是，在被认为是PK的误会解开之前，不能够靠近被转送到这里的其他GGO玩家。

现在需要的是能够登出的安全地点。既然就连城内都有蜈蚣与蝎子等怪物徘徊，就只能到城外去寻找避难处了。

终于做出判断后，诗乃就朝大门走去。她踩过倒塌的木门，钻过城墙来到外面。

下一个瞬间──

「…………呜哇……」

从她嘴里流出细微的声音。

好宽广。

眼前是一片规模庞大到难以形容的原野地图。

熟悉的GGO地图也绝对不算狭窄。包围首都SBC格洛肯的荒野就以想徒步横越的话得花上五个小时以上的规模为傲。但是这个充满谜团的世界不单纯是宽广而已，画质的精细度还高到了极点。不论是哪个VR世界，超远景都会变得模糊不清，但是延续到地平线的干枯大地以及横跨远方的山脉都清晰地映照在眼前。自从潜行到那个「真正的异世界」Underworld之后，就没有感受过如此高的规格了。

诗乃下意识中举起右手来触摸自己的侧头部。当然现在并不存在，但是在现实世界躺在床上的自己所着装的是一年半以来经常使用的AmuSphere。就性能来说它已经算不上是最先进的机器，到底是如何创造出这样的光景呢？

果然还是得快点登出去确认究竟发生了什么事。眨了眨眼切换意识之后，诗乃再次仔细地眺望夕阳照耀下的荒野。

地面有七成是干枯的大地，剩下的三成是褪成白色的植物，而这到处可见仙人掌般植物的模样让人联想到墨西哥的索诺拉沙漠──当然诗乃没有实际去过。里头也确实栖息着怪物，光是肉眼就能见到两只巨大的蝎子与一只巨大蜥蜴。看来要躲开捕食者的反应圈同时寻找安全地带不是件简单的事，这么想的诗乃随即注意到某件事。虽然绝对不能浪费黑卡蒂的子弹，但是搭档能办到的不只是在敌人身上轰出洞来。

诗乃以立射姿势架起黑卡蒂并且窥看瞄准镜。接着转动倍率调整轮盘，把倍率调整为最低的五倍。然后直接缓缓从左到右移动枪械来寻找安全地带。一般来说，靠近地面的地点绝对不行。希望该地点是在蝎子与蜥蜴爬不上去的高处，而且具备完全隐藏身影的遮蔽物。

虽说如此，但也不认为能轻易就找到如此优良的地点，所以至少也要是上面平坦的台地般地点──

「…………啊。」

诗乃发出细微的呢喃声，先把眼睛离开瞄准镜，然后再次窥看。接着把倍率提升到十倍。浮现在瞄准线中央的是突兀地耸立于大地的灰色岩山。上部虽然相当尖锐，但稍微往下的地方可以看见似乎是洞窟的地点。可以爬到那里的话，应该可以成为很棒的避难所。粗略看来距离应该是七百到八百公尺左右。

放下爱枪后，诗乃就下定决心从倒地的门板上走下来。靴底一踏上干枯的土壤就发出细微的摩擦声。这下应该有好一阵子不会回到城里来了吧。在异常事态得到解决之前，必须靠自己一个人的力量存活下来。

走了十公尺左右之后，就以经过压抑的速度跑了起来。前方一看到怪物就以远超过需要的距离绕过去，朝着灌木远方隐约可见的尖锐岩山前进。

幸好没有被蝎子与蜥蜴缠上，诗乃顺利地抵达目的地。从正下方往上看的岩山，高度大约是十五公尺左右。侧面几乎是垂直，大概只有城里的那种蜈蚣才能爬上去吧，不过上面也有不少裂缝以及凹凸处等可以作为施力点的地方。诗乃数次开合双手，同时在脑海里描绘到达稍微可见的洞窟入口的攀登路线。觉得可行之后就以右手抓住最初的支撑点。靴子的尖端挤进裂缝中然后用力抬起身体。

GGO里──说不定现实世界也是──狙击手是「如何确保高处」的职业，所以攀岩根本是家常便饭。VRMMO里的攀岩诀窍是在疲劳判定出现之前不断往上爬。当她一次都没有停下来，一口气爬了五公尺左右时。

【获得攀登技能。熟练度上升为1。】

这样的讯息突然出现在眼前，让诗乃没能抓住看好的支撑点。身体迅速往下滑落，千钧一发之际左手勾住小小的缝隙才免于掉落。咂了一下嘴后就消除视窗然后再次开始攀爬。

即使熟练度只有1，攀登技能还是有一定的效果，接着诗乃就顺利地爬到洞窟入口。一边小心翼翼地不让黑卡蒂撞上直径六十公分左右的微暗洞穴一边让身体滑进去。现实世界的话可能会因为不够深而无法使用，但是游戏世界里的话像这种洞穴几乎不会出现虚有其表的例子。

果然不出所料，洞窟慢慢地变宽并且延续到深处。如此一来就必须考虑到或许是怪物巢穴的可能性，于是诗乃从枪套里拔出MP7，然后打开安装在侧面导轨上的小型手电筒。白色光芒迅速推开了黑暗。

洞窟是高一公尺半，长三公尺左右的茧型。里面没有怪物，地板上也没有堆积着筑巢用的素材。不过深处的墙边孤零零地放着一只以金属补强过的木箱。

「…………宝箱？」

诗乃这么呢喃并且弯腰靠近。以MP7的枪口戳了戳盖子，就传出「喀喀」这种又重又硬的声响。应该长年放置于此却完全没有腐朽的迹象，感觉──这就是它身为宝箱的证据了。这样的话就只能打开它了吧，这么想的诗乃准备伸出左手，然后才注意到前面的金属部分有钥匙孔。

还是不死心的诗乃试着抬起盖子，但是却像是黏住了一样没有任何动静。叹了一口气后她就朝钥匙孔里窥看。

GGO世界里也存在宝箱──那里称为藏宝箱──然后大多是上锁状态。而且分为电子锁与物理锁两种类型，甚至有宝箱上了两种锁，想打开就必须同时具备开锁技能与骇客技能。只有物理锁的话，也有用枪射击钥匙孔的粗暴方式但是成功率相当低，不是再也无法打开，就是连内容物一起遭到破坏。

诗乃交互望着右手的MP7与宝箱的钥匙孔，然后击退了赌一把的诱惑。要是浪费了贵重的子弹又连箱子也一起粉碎的话，应该会沮丧好一阵子吧。虽然想至少试试看开锁，但是库存在道具栏里的开锁工具已经消失了。目前拥有的只有倒楣男人们的遗物与生锈的菜刀，以及从蜈蚣身上取到的素材。

「…………」

突然有个奇妙的点子，诗乃就用生疏的手势打开环状视窗与道具栏。在稀少的持有道具一览里选择【劣质蜈蚣剪刀】，然后只实体化其中之一。

出现的是长十五公分左右的红黑色螯肢。两根弯曲的锐利尖刺在底部合而为一。以双手拿着就能加以开合，不过实在不知道可以拿来当成什么素材。但现在只要前端是尖的就可以了。

诗乃以其中一根尖刺的前端插进宝箱的钥匙孔里。静静动了一下就感觉钩到了什么。虽然开锁性能比不上专用的工具，但是宝箱等级不高的话，用这个似乎也有办法打开。

为了移动钩住的东西而固执地操作尖刺，眼前就再度出现讯息。

【获得开锁技能。熟练度上升为1。】

看来这个世界也存在各式各样的技能。虽然终于开始觉得不是系统故障，不过目前还是得集中在眼前的钥匙孔上。

「呜……可恶……」

细声咒骂了一句并且持续挖着钥匙孔三分钟。在出现解锁技能上升为2的讯息时，宝箱也传出「喀嚓」的清脆声音。蜈蚣的剪刀似乎刚好耗尽耐久度，于是就在诗乃的手里碎裂了。

诗乃屏住呼吸，静静地抬起宝箱的盖子。随着细微摩擦声打开的箱子，里头是──一把硬币、一只老旧的皮袋以及一把生锈的钥匙。

诗乃首先捻起只有一枚的银币来仔细观察。直径两公分左右的圆盘，和在GGO世界里使用的点数货币以及ALO世界的尤鲁特货币都不一样。其中一面刻着100的数字，背面则是两棵树的浮雕。点了一下后就涌出【100耶鲁银币 货币 重量0．1】的属性视窗。

「耶鲁……？」

不曾听过的货币名。诗乃耸了耸肩，把剩下来的铜币全部收纳到道具栏里。接着拿出来的是生锈的钥匙。把手部分有着花形镂空雕刻，算是相当讲究的一把钥匙，但是完全不知道要用在什么地方。诗乃还是试着点了钥匙一下。【青铜钥匙 道具 重量0．72】──情报量几乎是零。

把钥匙也丢进道具栏后，诗乃拿出最后的皮袋。沉重的手感加深了期待。是箱子里没有看到的金币，还是强力的魔法道具呢？诗乃打开皮袋袋口把右手伸进去。指尖碰到几个圆形物体，于是便拿出其中一个。

「…………这是什么？」

在手掌上发出暗沉光芒的是跟小钢珠同样大小的金属球。这漆黑的质感是铁，不对，是铅吗？怎么看都不像是高价的物品。看了一下袋子里面，发现全是相同的珠子。感到沮丧的诗乃不死心地击点金属球。出现的属性视窗里──

【劣质的毛瑟枪子弹 武器／弹药 攻击力 贯穿28．42 重量3．67】

「只是子弹吗……」

练功区洞窟涌出的宝箱，内容果然不怎么值得期待吗？感到失望的诗乃原本准备丢下珠子，但手突然停了下来。

「……毛瑟枪？」

GGO存在这种分类的实弹枪吗？

根据诗乃的知识，毛瑟枪所指的是前膛．燧发式的原始长枪。虽然是长枪却不称为来福枪的原因是枪身内没有来福线<膛线>的缘故。就技术上来说，大概只比火绳枪进步了一些。

GGO世界里，设定上是文明水准因为最终大战而衰退，因此几乎失去所有高度的金属加工技术。好不容易才能制造出大部分零件是塑胶的光学枪，再厉害的NPC都无法制造需要金属冲压与切削的实弹枪，只能够在大战前的都市遗迹里搜寻。诗乃爱用的黑卡蒂Ⅱ与MP7也是自己在首都地下的一大片遗迹迷宫里获得。

但是从都市遗迹出土的枪就算再古老也是二十世纪初期的样式，从没听过有人发现可以回溯到十七世纪的毛瑟枪。说起来每开一枪就得重新装填火药与子弹的话，就连对上最弱等级的怪物都会相当辛苦。

也就是说……

「这个世界有毛瑟枪吗……？」

这么呢喃完，诗乃就再次看向右手上的铅球。几秒钟后才将子弹收回皮袋内，然后把开口束紧并且收回道具栏里。

──虽然没有出现什么像样的宝物，但光是能打开宝箱就算不错了。

这么对自己说完，诗乃就靠到呈平缓弯曲的墙壁上。时间是下午六点。看来这个洞窟不会涌出怪物，得先登出然后确认究竟发生了什么事才行。

但在那之前先休息片刻吧。再五分，不对，三分钟像这样待机，进行最后的安全确认后才登出。回到现实世界要先补给水分，然后吃点东西……冰箱里还有什么食物呢？记得昨天晚上还剩下一些猪肉味噌汤，把它加热一下再烤一片祖母送来的黍饼……

诗乃没有注意到自己不知不觉间已经闭上眼睛，迅速地沉进深沉温暖的黑暗当中。

突然觉得听见奇怪的声音。

像是无数铃铛在远处响起一般，也像是玻璃碎片缓缓落下堆积般虚幻的音色。

数次在眉间用力之后，好不容易才抬起眼睑。看见的不是自己房间的白色壁纸而是凹凸不平的岩壁。虽然一瞬间不清楚自己身在何方，但立刻就注意到没有从虚拟世界的洞窟登出而直接睡着了。

视界角落显示的时间是晚上九点五分。算起来在这里睡了三个小时。也就是说这个世界不存在检测出睡眠状态就自动将玩家登出的自动断线机能。不对，如果会自动断线的话可能会躺在身体熟悉的床铺上睡满八个小时，所以反而可以说是幸运。

话说回来，依然可以持续听见的奇妙声音究竟是什么，内心这么想的诗乃同时看向洞窟入口。

下一刻，她的睡意就瞬间消失了。

从太阳应该早就下山的练功区上有鲜艳紫色光芒照射到洞窟里。那不是夕阳的颜色。宛如紫水晶般的冰冷燐光……而且还不规则地摇晃着。

抱着立在岩壁上的黑卡蒂后在地板上爬行。抵达入口后就先采取卧射姿势，接着慎重地看向天空。

可以确定是夜晚了。但是看不见星星或者月亮，相对地有光之窗帘层层重叠在一起。极光……奇妙的声音是从整个空中降下。

突然间，极光产生剧烈晃动，然后可以听见某个人的声音。

「种子发芽，开枝散叶，形成环状大门。被招待至渴望之地的众人啊，坚守你们唯一的生命吧。承受大量的苦难，在艰难困境中存活，并且最先抵达极光指示之地者将能获得一切。」

诗乃无法立刻理解像是稚气未脱的少女，也像是思绪缜密的贤者般的声音究竟在宣布些什么。脑袋里只剩下「极光指示之地」「获得一切」等单字。

极光应该指的是北极光吧。诗乃再次仔细地凝视夜空，就发现紫色窗帘们呈放射状并排在一起。中心应该是北，不对，东北方向吧。想正确判断方位就必须离开洞穴。

诗乃下定决心后准备站起身子。

但是却办不到。

当在空中摇晃的极光像是开关被切断般消失的瞬间，无比沉重的重量就加诸于背上。一瞬间还以为是被人给压住了，但并非如此。重的是装备在腰部后面的副武装MP7。一秒钟之前还像小猫般的重量，现在却像是被狮子给踩住了一样。

「呜咕……」

边发出呻吟声边把右手绕到背后，握住MP7突出枪套的握把，好不容易才把它丢到地上。但是重量仍未消失。爱用的战斗服──正式名称「狙击手夹克」似乎也超重了。

她以右手打开环状视窗，操作装备人偶把服装移到道具栏里。连靴子与围巾都解除之后，身体终于变轻，于是诗乃才松了一口气。

事情应该是这样吧。从被强制转移到这个世界的下午五点左右，到谜样声音的世界广播举行的晚上九点左右，这四小时是装备重量超重也能够行动的缓冲期间。但现在已经结束，诗乃的负重界限降低到符合目前等级2的水准。结果就承受不住稀有装备的MP7与狙击手夹克的重量了。

以简朴内衣的模样站起身子，低头看向放在地板上的黑卡蒂Ⅱ。

虽然早知道结果，但还是抓住枪身与枪托试着把它抬起来。但爱枪就像被螺丝锁在地板上一样纹风不动。因为它即使在GGO世界里多数的枪械中也是属于最重类别──比不上怪兽爱用的迷你机枪炮──的反器材狙击枪，这也是理所当然的事，所以今后没有办法扛着爱枪在荒野里奔驰了。不对，装备能力值也不足，所以应该也不能摆设在地面进行射击了。

她单脚跪在洞窟地板上，静静抚摸着黑卡蒂优美的木制枪托。

「……稍微休息一下吧。」

这么对爱枪呢喃完，就以食指轻敲一下并从涌出的选单里选择收纳。巨大枪械包裹在光芒中并且消失后，就把另一个搭档MP7收进道具栏里，然后叹了长长的一口气。当她想以虚拟空气来补满变空的肺部，就意识到喉咙的干渴。

下意识中想从腰带上解下小型水壶的左手扑了个空。和求生小刀一样，水壶也消失不见了。这样的话，就只能忍耐到可以补给水分为止了。虽说在这样的荒野要找到水源并不简单，但是在VR世界里喉咙干渴也只会感到不舒服，并不会因此而死──

「咦……」

突然注意到视界左上角传出危险的氛围，将视线集中在该处后诗乃就轻叫了一声。

标示着TP的蓝色长条开始一点一点减少。其下方的黄色SP长条也在减少当中，但减少的速度是TP比较快。诗乃直觉TP长条的减少与觉得渴的喉咙有关。

T应该是「Thirst」的略称……如此一来就不难想像等长条全部消失时会发生什么事。倒向地面死亡，装备道具掉落并且被传送到某个地方。把爱枪收到道具栏里就不会掉落应该是过于乐观的预测吧。

诗乃再次瞪着蓝色长条。减少速度大概是一分钟一％左右。算起来要过一百分钟才会归零，但是感觉这种速度会依环境与状态而变化。离开洞窟寻找水源的话，减少的速度一定会加快。

但就算是这样，似乎也无法选择待在这里不动。极光消失后的夜空点缀着无数星星，一百分钟内完全没有降雨的模样。不自行寻找水源的话一定会死亡。

但还有另一个问题。诗乃现在处于上下只穿内衣加上一条腰带的状态。能称为武器的就只有在遗迹里找到的生锈菜刀。光靠这个别说是蜈蚣了，就连一只老鼠都无法打倒。

「…………两害相权取其轻吗？」

轻声这么呢喃完就打开道具栏。

她不是要取出黑卡蒂与MP7。只见她卷动短短的道具一览表，在并排着五个黑色袋子的立体图标处停下手来。

图标右侧各自标记着「艾尔卡密诺的遗物」「斯特科斯的遗物」「炼炼的遗物」「密修卡的遗物」「增冈一郎的遗物」等道具名。如果是从主动打倒的玩家身上掉下来的道具就无所谓，但是对原本打算先帮忙保管的遗物出手就让人有点不舒服了。

但这样的犹豫也敌不过刺着喉咙一般的口渴感。依序检查袋子内部，寻找等级2的能力值也能装备的武器与防具。和诗乃一起被传送到这里的玩家们看起来都不是菜鸟了，装备掉宝品所需的能力值应该也不会太低，不过五个人里面如果有能力构成是极度偏重AGI的玩家，说不定就……

结果是名为斯特科斯的玩家回应了诗乃的期待。包含在掉宝品内的武器「猎户座SL2」与防具「鼬皮上衣」，即使全部装备上去也在些许差距下没有超过重量界限。

立刻把这两个装备拖到人偶上，腰带左侧就出现细长雷射枪，身体则是穿上黄褐色战斗服。猎户座虽然是自己不怎么喜欢的光学枪，而鼬皮上衣的露出度也有点高，但是总比只穿内衣裤加上一把菜刀要好多了。爱用的围巾因为是超轻量所以就直接留着。

GGO的话装备枪械后视界右下就会显示出残弹数，但这个世界没有这样的机能，所以诗乃就拔出雷射枪，确认内藏在枪身内的能源表。目前还剩下六十三％。由于不熟悉这把枪，所以不实际射击看看就无法得知一发会减少几成的能源。

把雷射枪放回枪套里并且关上环状选单。下一刻，意识到口渴的感觉变得更强烈，诗乃不由得咳嗽了起来。在TP条归零之前虽然还有时间，但是在那之前感官方面似乎会先撑不住。好不容易才找到这个避难处，但现在必须离开这里去寻找水源才行了。

瞄了一眼打开盖子的宝箱后，诗乃就从狭窄的出入口冲到干枯的荒野里。

然后到了现在──同日晚上十点过后。

离开洞窟后已经移动将近一个小时了，诗乃依然无法发现水源。TP条剩下不到两成，口渴的程度已经快让人无法忍受。目标的岩山周边如果找不到水源，那里就是自己的丧命之处了吧。虽然希望死亡后还能在某处复生，但是不可思议声音宣告的「坚守你们唯一的生命」令人相当在意。如果意思是玩家只有一条性命，在缓冲期间已经结束，也不可能复活的现在，死亡的话可能就会把道具遗留在这个世界然后回到GGO，最惨的是可能会连虚拟角色都失去。

诗乃是犯下了三个重大的错误判断，才会陷入现在这种危机的状况。第一个错误是好心地想帮忙保管蜈蚣嘴下亡魂的遗物。第二个错误是发现洞窟时没有马上登出，不小心在里面睡着了。然后第三个错误是离开洞窟时没有走回遗迹的方向，而是做出更加远离的选择──

现在想起来，仔细调查遗迹中的民家，说不定可以找到水井之类的水源。练功区之所以像这样找不到水源，应该是地图设计为在遗迹补充饮水后，才在水源耗尽之前探索荒野。查觉到这件事是在TP差不多减少到一半的时候，所以就算想折返回遗迹也没办法了。

目标的岩山如果没有水源的话……不，现在也只能相信自己继续前进了。事到如今绝对不想犯下被怪物纠缠住这样的错误，于是凝眼看着黑夜持续奔跑着。稍早之前取得了「夜视技能」，所以眼睛在黑夜里稍微能够视物，但是光靠星光无法看透物体的阴影。于是诗乃就大大地绕过看起来很像躲藏着蝎子等怪物的岩石，尽可能压低脚步声来持续奔跑。

表面长着灌木的岩山终于靠近到前方一百公尺的时候。

诗乃的眼睛和耳朵同时捕捉到重要情报。于是立刻弯下身体。

眼睛所见到的是在岩山底部闪烁摇晃的微光。某种东西反射了夜空中的星光。这样的荒野里不可能有金属与玻璃。那一定是水面不会错了。

然后耳朵听见的是类似雷鸣的咆哮。轰天的重低音不可能来自蜥蜴或老鼠。以VRMMO常见的情况来说，能够发出那种声音的是大型的──可能还是练功区魔王级的怪物。

诗乃反射性想抓住黑卡蒂Ⅱ的背带，但右手却扑了个空。无法装备的搭档已经收纳到道具栏里，目前可以依靠的就只有左腰的猎户座SL2而已。但是只有轻量这个优点的光学手枪可能跟魔王怪物抗衡吗？

染上鲜红色的TP条慢慢只剩下一成左右。继续这样犹豫下去，十几分钟后也会归零。现在才去找其他水源实在太不合理了，只剩下在这里渴死或者赌一把前往岩山两个选项。

──至少在游戏里面展现一下在敌人枪下丧生的勇气！

过去的GGO里，曾经对身为雇主的中队队长丢出的话突然重新在耳朵深处浮现。诗乃忍不住苦笑了一下后就迅速撑起身体。既然难逃一死，与其脱水而死，宁愿跟敌人战斗而失去生命。

狰狞的吼叫声再次响彻荒野。诗乃拔出猎户座并解开保险。

她持续凝视着一百公尺前方的岩山。既然要战斗，至少得看清楚怪物的模样，在这种距离之下只能看到某种巨大物体在岩山底部动着。

诗乃突然注意到某件事，于是就蹲下来打开环状选单。她击点道具栏内的MP7，从副选单将附加零件的手电筒实体化。接着把出现在视窗上的小型手电筒安装在猎户座的下侧导轨上。重量……还差一点就要超过。虽然连一颗石头都没办法拿了，但在限制内的话行动还是能够跟空手时一模一样，这就是VRMMO的好处。

手电筒的性能虽高，光线还是无法照到一百公尺前方。为了更靠近一点的诗乃慎重地前进。她一边注意杂兵怪物，一边绕过岩石、钻过仙人掌，最后把距离缩短到五十公尺。

在远方时觉得很小的岩山，靠近之后发现也有十层楼建筑物的大小。几乎是垂直耸立的岩壁到处可见藤蔓类植物垂下，也可以听见潺潺流水声。看来有些许流水从岩山表面流下，在底部形成了小小的水塘。

确认水源存在的瞬间，诗乃就被特别强烈的口渴感袭击。脖子被勒住的感觉让她忍不住轻咳了起来。TP条剩下八％左右……剩下的八分钟内不喝到水的话就会死亡。

将视线移到岩山周边，立刻就看见吼声的主人。矮壮的巨大影子，在岩山底部以逆时钟方向移动着。简直就像在保护自己的地盘──不对，实际上就是这样吧。不想办法解决那只怪物就无法喝到水。

在发动决死的特攻之前，诗乃思考过是不是要尝试发射一发子弹让怪物盯上自己，然后把它拖到远方后再逃走的作战。就算无法完全甩开，只要让它离开岩山一分钟，应该就能够喝到水了。

继续前进的她把距离缩短到剩下三十公尺。对于身为狙击手的诗乃来说，这已经是令人呼吸困难的近距离，但是用剑战斗的桐人与亚丝娜等人接下来还会冲过去砍杀。

大家现在在做什么呢？是在现实世界里用功，还是在ALO里悠闲地升等呢？希望快点回复TP，找到新的避难处然后跟他们取得联络。把一连串发生的事情说出来后，桐人可能不会惊讶而是会感到羡慕吧。为了看到他那张脸──

「……我一定要活下去。」

呢喃这么一句话后，诗乃就把上半身靠到合适的岩石上，然后用双手架起猎户座。由于不会出现着弹预测圆，而且这把枪也没有安装瞄准镜，所以必须用原始的照门与准星来瞄准。幸好光学枪的弹道跟实弹枪不同，不会受到风与重力的影响，发射出去的雷射就命中瞄准──正确来说是往下一公分的地方。

从岩山后面现出身影的大型怪物画出平缓的弧线步行着，然后把头部朝向诗乃。虽然不论击中哪个地方都能让它盯上自己，但是为了不想浪费能源，还是想击中可能是要害的地方。

微微动着左手，以指尖触碰手电筒的开关。点灯三秒钟后就瞄准目标并且开枪射击。诗乃深深呼出一口气，接着吸气点亮手电筒──

在那之前──

「哒哒哒哒哒──！」的爆炸声持续响起，吓了一跳的诗乃整个人缩成一团。那是实弹枪的发射声，而且是大口径的。

最先想到的是被蜈蚣袭击的GGO玩家们为了抢回遗物而追过来了。但诗乃是花了一个多小时从遗迹移动到这里。没有被安装跟踪器的话不可能追上来。

大型怪物的吼叫声应证了她这样的想法。这跟之前似乎是主张自己地盘的远吠声不同，明显是异常愤怒的咆哮。凝眼一看之下，巨躯的各处都落下血液般的红色伤害特效光。

再次传出雷鸣般的发射声。然后这次就看见了。岩山的东南方，从诗乃这边来说是右侧的略高山丘上，有几道橘色亮光闪烁。一瞬之后，命中怪物胴体左侧的子弹产生特效光，巨躯跟着晃动了一下。

特效光虽然立刻就消失了，但诗乃的眼睛还是清楚地看见了怪物的模样。用一句话来形容就是「恐龙」。

诗乃位于文京区汤岛四丁目的自宅公寓邻接着上野恩赐公园，觉得难得住这么近的诗乃，有空的时候会到美术馆或者博物馆去。她最喜欢的是国立科学博物馆，对于今年夏天举行的恐龙展虽然没太大的兴趣，还是随兴地过去参观了一下。最大的看点是名为「恐手龙」的恐龙全身实物化石，当时诗乃就着迷地看着其巨大的手臂与钩爪，心里想着难怪它的名字会带有「恐怖的手」的意思。

保护岩山的怪物就跟那只恐手龙十分相似。像小山一样隆起的背部、长长的脖子、尖锐的头部以及强壮的手臂与腿部。但是跟在恐龙展看见的恐手龙想像图不同，全身没有长羽毛，而是被凹凸不平的铠甲般皮肤覆盖着。体高五公尺，全长大约有十公尺左右。

被大口径枪械一阵乱射的恐龙虽然暂时脚步踉跄，但是马上就重新站稳。把头朝向攻击者们所在的山丘，然后发达的前脚在地上拨动数次后才猛然突进。每当不少于五吨的巨躯踢向地面，震动就会传到诗乃脚边。

山丘前面是陡峭的悬崖，就连那只恐龙应该也冲不上去吧。应该趁现在开始第三、第四波同时射击，但山丘上不知道为什么却保持沉默。说起来那些攻击者究竟是什么人？如果不是追着诗乃的那支中队，难道是先跑到这里来的其他GGO玩家？但是为什么枪械的发射声会全部一样呢？

感到困惑的诗乃，视线前方的恐龙维持突进的速度，强壮的头部直接撞上悬崖。随即响起极激烈的地面震动声。悬崖上出现放射状龟裂。

恐龙低着头后退，再次摆出突进的姿势。这时候终于开始第三次齐射，恐龙隆起的背部爆出几道红色闪光。但是长着厚厚突起的背部可能防御力相当高吧，这次没有露出脚步踉跄的模样。

「吼啊啊啊啊呜！」

发出剧烈吼叫的恐龙，宛如巨树般的后脚踢向地面。头部猛烈撞向悬崖的同一个地方。龟裂到达崖顶，干燥的土块开始崩落。

突然有种听见悲鸣的感觉，诗乃就拼命凝眼看向该处。

一道人影随着土块滚落高低差十公尺左右的斜面。悬崖边缘的一名攻击者似乎被卷入崩坏当中。

「…………真是的……」

忘记口渴感咒骂了一声后，诗乃就从躲藏处冲出去。虽然不清楚攻击者们的身份，但是要排除恐龙喝水的话，和他们合作应该是最妥善的方法了。虽然考虑过趁战斗进行中偷偷靠近到泉水附近，但要是被恐龙盯上又被攻击者们认为是敌人就得不偿失了。

在双手握住猎户座的情况下往前冲刺，从南侧靠近悬崖。掉落的玩家似乎被岩石压住而站不起来。虽然从崖上开始第四次的枪击，但是弹数稀少。恐龙完全不当一回事，朝着倒下的玩家举起长着凶恶钩爪的右手。

「这边！」

诗乃一这么大叫，就先打开手电筒的开关。纯白光芒撕裂黑暗，直接射中恐龙的头部。没有错过一瞬间动作停止的空档，诗乃瞄准黄色眼睛后扣下猎户座的扳机。

黄绿色光弹随着「哔咻！」这种跟实弹枪比起来实在不怎么可靠的声音发射，准确地贯穿了恐龙的右眼。

「嘎哦哦哦哦嗯！」

尖锐的咆哮声。或许是扭动身体太过用力而失去平衡，恐龙猛烈撞上斜面。悬崖再次崩落，大量的土壤与岩石掉落。像鳄鱼也像鸟类的头部虽然出现红色环状浮标，但是根本没多余的心思去看名字。

放下枪并且关上手电筒的诗乃，跑到倒下的玩家旁边后，用身体撞开了压在对方左脚上的大岩石。

「站起来！」

这么叫完就伸出左手──

结果她的双眼就瞪大到了极限。

对方不是人类。广义来说不是类人类，至少在GGO里不存在这种外表的虚拟角色。

倒在地上的是矮壮身体上全部被茶色羽毛覆盖，拥有猛禽类头部的所谓「鸟人」。比在ALO里出现的哈耳庇厄系怪物更接近鸟类。但是身体上穿着由布料与皮革制成的防具，右手确实地抱着粗糙的步枪。这应该不是玩家或怪物而是NPC吧。

诗乃再次伸出忍不住想回缩的左手。就算外表有七成是鸟，同样使用枪械者之间应该能互相理解……这种没有根据的一厢情愿能不能传达给对方知道呢？

鸟人眨了一眨老鹰般的眼睛后，就以左手握住诗乃的手。把他拉起来之后，诗乃的身高还比他高出五公分左右。

「你能跑吗？」

面对提问的诗乃──

鸟人以甚至不像言语的奇妙声音回答：

「NNNN。」

虽然完全不清楚对方说什么，但已经没有反问的时间了。撞上悬崖的恐龙猛烈震动身躯来甩落堆积在身上的土尘。

「这边！」

叫完就开始朝着山丘后方跑去。鸟人也以没有穿鞋子，宛如鸵鸟般的脚踢向地面追了上来。虽然从左脚落下红光，但是似乎没有受到严重的伤害。

山丘的直径是三十公尺，高十五公尺左右的圆形，侧面虽然是垂直的悬崖，但某处应该有鸟人们爬上去的道路才对。不对，说不定是飞上去的……虽然一瞬间这么想，但他的翅膀几乎都退化了，或者应该说进化成手臂，光靠从肩膀长到手肘的装饰般羽毛应该没办法飞吧。

拼命奔跑时，鸟人突然在后面大叫些什么。

「NNN！」

回过头去就看到他以长着钩爪的左手指着悬崖。虽然因为阴暗而看不见，但似乎设置了梯子之类的东西。把身体倾倒到极限后往左转弯，接着跳上梯子。那不是临时的绳梯，而是以确实打进墙面的木桩来作为脚垫。这也就是说，鸟人们不是今天晚上偶然攻击那只恐龙，而是至今为止已经多次尝试从这座山丘上攻击了。

诗乃一边这么想，一边全速爬上梯子。由于猎户座已经放回枪套内，如果鸟人从下方攻击的话将会来不及对应，但应该不会到了这个时候才背叛吧。

这样的预测果然成真，诗乃没有受到妨碍就爬上十五公尺的梯子。山丘上只长着稀疏的矮树，其他大部分是岩石与沙子。找不到稍微怀抱着希望的水源。TP条只剩下四％。

原本忘记的口渴感增加了数倍后重新复苏，诗乃当场跪了下去。接着以沙哑的声音对迟了几秒后才抵达山丘上方的鸟人问：

「你有水吗……？」

但鸟人只是露出困惑的表情眨着眼睛，即使看向他的身体，发现皮带上也只挂着两个道具袋般的物体，似乎没有水壶。如果是NPC的话应该无法使用道具栏，现在能看见的就是他全部的装备。

也就是说，在四分钟……不对，三分几十秒内不打倒恐龙并且抵达岩山底部的话，诗乃就会死亡。

──哪能死在这里！

诗乃打起精神站起身子。摇摇晃晃地跑向岩山西侧。结果立刻就看见几道沿着崖边站立的人影，不对，是鸟影。他们背对着这边，正以步枪对准悬崖下方。应该是准备对恐龙发动第五次齐射，但是……

恐龙显示在诗乃视界下方的HP条仍然维持在八成左右。算起来一次齐射甚至没办法减少一成。只要待在这座山丘上确实就不会受到恐龙的直接攻击，但能够瞄准的也只有受到厚厚皮肤覆盖的背部，所以无法给予太大的伤害。从道具袋的大小来看，他们剩下来的子弹应该也不多了。

「等等！」

诗乃一这么大叫，横向排列的鸟人们背部就震动了一下，脖子附近的羽毛整个倒竖。鸟人迅速转身，把枪口对准诗乃并且大叫：

「NNN？」

「NNNNN！」

诗乃立刻举起双手同时拼命地对他们说道：

「我不是敌人，希望能帮忙你们打倒那只恐龙！」

「NNN！」

比同伴高了一颗头的鸟人如此大叫着回答，然后重新架起步枪。看来是完全无法理解诗乃的话。

TP条只剩下三％。

──到此为止了吗？

当诗乃的肩膀失去力量时，整座山丘就随着爆炸性的冲击声剧烈晃动了起来。恐龙再次用头部撞击了山丘。悬崖边缘大量崩坏，鸟人们发出悲鸣并且飞退。恐龙的咆哮震动着夜晚的空气。

这道声音唤醒了诗乃几乎快要耗尽的斗志。

等死掉后再绝望就可以了。只要TP还剩下一丁点，我就要为了生存而挣扎。把己身的意志传达给鸟人们，然后合力打倒怪物。一定有完成这件事的办法才对。

桐人在这种时候会怎么做呢？一定不会倚靠言语吧。他总是以行动──充满压倒性意志力的剑光来鼓舞众人。诗乃虽然没有剑，但是有搭档。在这种状况下能够倚靠的就只有她了。

她迅速以右手打开环状选单并移动到道具栏。击点数小时前收纳进去的爱枪名称，选择将其实体化。

一看见出现在视窗上的巨大反器材步枪，鸟人们就发出惊讶的声音。他们的枪是适合诗乃在遗迹发现的子弹，也就是旧式的毛瑟枪，跟现代制枪技术结晶的黑卡蒂Ⅱ根本无从比较。不过说起来鸟人会使用枪械本来就是件很奇妙的事，所以现在应该趁他们被吓破胆时让他们顺着自己的意思来行事。

「你还有你！从左右两边支撑住枪身！」

诗乃指着似乎是领袖的高大鸟人以及站在他身边的另一个人并这么大叫，结果他们就一起歪起头来。那种动作看起来真的像鸟一样，诗乃一瞬间差点就要笑出来，好不容易才忍住并且再次大叫：

「快一点！必须趁恐龙用头冲撞还在头昏时射击才行！」

但是鸟人们完全没有动静。言语果然完全无法沟通。GGO里也存在使用谜样语言的人造人NPC，但是从任务中获得言语转换晶片之后就能用日文沟通。应该也能利用类似的手段跟鸟人们谈话才对，但现在根本不可能去寻找这样的任务。

「拜托，只要帮忙支撑就可以了！」

当诗乃第三次发出声音时。从背后冲进视界的娇小身影──诗乃拯救的鸟人就以右肩扛起黑卡蒂长大枪身的中段。下一个瞬间，藉由视窗的维持状态结束，巨大重量压到鸟人的肩上。

鸟人发出「咕哇」的悲鸣，诗乃也急忙把手朝爱枪伸去。虽然以右手撑住木头枪托，左手撑住枪身，但是用上两个人的力量也只能不让它掉落到地上而已，根本无法把它运到悬崖边。

TP条剩下两％。

「呜……咕唔唔……！」

诗乃一边发出呻吟一边拼命想把超过重量限制的反器材步枪往前方移动。HP条右侧的红色砝码符号剧烈闪烁。眼前打开小小的视窗，显示出【获得强健技能。熟练度上升为1】的讯息，但现在根本没空理它了。

扛着枪身的鸟人似乎也挤出全身的力气，但是身体却反而逐渐往下沉。每次挣扎就会有小小的羽毛从肩膀脱落，最后甚至加上了伤害特效。

诗乃的努力也抵达界限，整个人快要从膝盖崩落的瞬间──

巨大的手确实地握住了枪身前端附近。

砝码图标的闪烁趋缓。抬起头后眼神一瞬间跟鸟人领袖相对。

「NN！」

领袖似乎叫了些什么，然后用力抬起枪身来放在左肩上。虽然超重状态仍未解除，但这样总算可以搬运了。

三个人摇摇晃晃地前进，把巨大步枪移动到悬崖边。虽然想打开黑卡蒂的两脚架将其设置在地面，但是这样就无法瞄准底下的恐龙了。

「蹲下来就这样撑住！」

虽然言语应该无法沟通，但两名鸟人还是迅速跪到地上。诗乃用尽吃奶的力气把黑卡蒂贴在脸颊上，然后把枪口微微向下。

但恐龙这时候已经从身体冲撞后的踉跄状态恢复过来。它依然把看起来很强壮的头朝向这边，然后开始慢慢后退。是下一次冲撞的准备行动……不妙。现在悬崖被撞的话，可能会连同黑卡蒂一起滚落山崖。

形状是圆环与柱子组合起来的HP条，固有名称也是以片假名标记。「史提罗克法罗斯」──听起来确实像恐龙的名字，但完全搞不懂意思。

恐龙史提罗克法罗斯的头受到厚厚的甲壳状装甲保护，说不定连黑卡蒂都无法粉碎。而且最重要的是，在超重的状态下硬是开枪射击几乎不可能瞄准并且射中头部。

这么一来就只能瞄准巨大的胴体，可以的话希望可以射中心脏。但是史提罗克法罗斯不要说腹部了，似乎连侧面都不打算露出来。从背部真的可以贯穿心脏吗？

TP条残量剩下一％。诗乃的生命再过六十秒就要终结。

「……开枪了！」

诗乃从比荒野的砂石还要干燥的喉咙里挤出简短的一句话。

但在她的手指放到扳机之前，支撑枪口的鸟人领袖就迅速举起右手，开口大叫了些什么。

「NNNNN！」

伙伴的鸟人们并排到诗乃左右，再次架起毛瑟枪。连膛线都没有的旧式枪械，最多就只能伤到恐龙的表皮，根本无法击中它的心脏。但是领袖的「N！」声音响起的瞬间，鸟人们就一起扣下扳机。

装设在击铁前方的火石摩擦触发杆后产生火花，火花再点燃火药池里的火药。隔了短暂的时间后，枪身中的火药炸裂，传出「哒嗯──！」的枪声。

同时发射的子弹几乎都没有命中恐龙。相对地刨开脚边的地面，喷洒出大量的火花特效。

「吼耶啊啊啊！」

吼叫的史提罗克法罗斯以后脚站立，并且高高地举起双臂。没有被厚厚皮甲保护的泛白肚子露了出来。

──就是现在。

诗乃透过瞄准镜瞄准应该是史提罗克法罗斯心脏的地方，毫不犹豫就扣下扳机。足以让毛瑟枪变得像玩具一般的巨响。从枪口制退器迸发出橘色火焰。即使用上三个人的力量也无法压抑强烈的反作用力，诗乃与两名鸟人连同黑卡蒂一起被吹到后方。

但就算是这样，诗乃还是确实看见了。发射出去的.50BMG弹贯穿史提罗克法罗斯胸口正中央，令其喷出庞大伤害光芒的模样。

当诗乃他们从背部跌落到地面的同时，史提罗克法罗斯的HP条就开始以猛烈的速度减少。HP持续地减少，颜色从黄色变成红色──最后归零。

从悬崖下方传来巨躯崩落到地面时的震动。眼前出现【Sinon的等级上升到16】的讯息视窗。「16……？」，对这样的等级感到惊愕的时间极为短暂，诗乃立刻就对TP条说不定会随着升级回复而有所期待。但很可惜的，变得像丝线一样细的TP条没有回复到右端的模样。距离归零还有四十……不对，三十秒。

诗乃以震动的手指击点就躺在右侧的黑卡蒂，把它收回道具栏里。

以这个动作为契机，鸟人们一起高举起毛瑟枪发出尖锐的叫声。在附近跌坐于地上的领袖与诗乃拯救的鸟人也站起来加入欢喜的行列。

但是诗乃根本没有时间观看这样的景象。当然也没有时间走下后方的楼梯。

站起来的诗乃往前方的悬崖跑去。甩开恐惧感从十五公尺的高度一跃而下。已经上升到等级16，单纯的落下可能还可以撑得住，但诗乃不打算冒这么大的风险。她的目标是横卧在地上的史提罗克法罗斯尸体。

双脚从看起来比较柔软的侧腹部着地，一边弯曲膝盖一边往斜前方滚动尽可能吸收冲击。听桐人说The seed规格的VRMMO里，从高处落下时一般的着地与摆出受身姿势的着地受到的伤害量会有所不同，所以在ALO里确实地练习过了。托练习的福HP条只减少一成左右，但是TP条却真的只剩下一丁点。

从恐龙的侧腹部滑下去后站到地面。不知道是受肾上腺素还是真的受到系统效果的影响，感觉世界开始模糊。距离岩山底部闪闪发亮的泉水还有大约两百公尺的距离。冲刺的话大概十几秒钟就能到达。

诗乃咬紧牙根并踢向地面。一步、两步，到了第三步准备开始全力奔驰时……TP条无声地消失了。

至今为止最严重的口渴感变成火焰焚烧着喉咙。耸立的岩山变成双重影像，诗乃忍不住闭上眼睛。

──在这里结束了吗……

一边迎接死亡的降临，诗乃一边对道具栏里的黑卡蒂Ⅱ说道。

──如果掉了，我也绝对会把你拿回来。

身体开始失去力量。整个人往前扑倒到地面。混杂着小石头的沙子触碰到脸颊。虚拟角色变成蓝色多边形后四散………………

结果没有出现这种情形。

相对地，诗乃看见视界左上角的HP条开始减少。也就是说，TP条归零也不会立刻死亡，HP似乎会从那个时候开始减少。倒在地面的诗乃瞬间瞪大眼睛并且呢喃：

「……那一开始就说清楚啊。」

由于没有人回答，她便霍然撑起上半身。虽然暂时免于死亡，但没有时间闲晃了。HP条以眼睛能清楚辨认的速度不断减少，重新获得的缓冲时间最多也只有一分钟。

此时视界依然是双重影像，这似乎是显示即将死亡的特效。摇摇晃晃地站起身子，再次开始朝着岩山跑去。被小石头绊倒几次还是在花了三十秒跑完两百公尺的距离，这时HP条已经剩下不到一半。

岩山底部盛开着动人的花草，它们后方的清澈水面正在摇晃。如果出现这其实是个毒沼的结局，自己一定要找出这个谜样世界的营运者并且把他射成蜂窝，内心如此发誓的诗乃横越花田后跪到池畔。

由于没有杯子，她便将双手插进池子里。捞起冰冷到吓人的水，把它抬到嘴边之后完全不试味道就一口气喝光。

「啊…………」

嘴里发出沙哑的声音。诗乃急着再次捞起一口水来喝下。然后不断重复同样的动作。

虽然HP条停止减少，TP条慢慢开始回复，但是有股强烈到可以无视这些数值变化的复生感扩展到全身。最后觉得用手捞水太过麻烦，直接用嘴巴靠着泉水，像动物一样消除口渴。

看来有一段时间无法离开这座岩山，很想干脆盖房子在这里住下来。内心这么想的诗乃没有注意到TP条已经回复，只是不停地把水往喉咙里送。

** 第二章

我和亚丝娜、莉兹贝特、西莉卡就读的所谓「归还者学校」，是修改因为合并、统合而废校的公立高中校舍而成。

因此校园内的构造特别复杂，有好几个不知道存在就无法抵达的RPG游戏般地点。我现在所站的小绿地就是其中之一，必须爬上教室栋二楼后走到走廊尽头，从紧急逃生门走下外部楼梯沿着绿篱走一阵子，穿越很容易忽略的狭窄缝隙才能够进入。

被高大的绿篱与教室栋、图书馆栋包围的绿地是长宽约十公尺的正方形，稍微隆起的中央部并排耸立着雨树以及白檀，其周围则点缀着季节的花草。地面覆盖柔软的草皮，而且几乎看不到杂草，所以一定有人在维护，但是我从未看过维护者的身影。

今年入春刚发现此处后，我和亚丝娜就把这里取名为「秘密庭园」并且隐瞒情报，之后被莉兹贝特察觉异状，所以现在她跟西莉卡也会利用这个地方。而目前站在我身边的这个成为第五名──不对，包含身份不明的管理者的话就是第六名「知情者」的人物，正一边环视四周一边以独特的声音表示：

「哦～这是个很棒的约会地点耶。带我过来真的没关系吗？」

「有什么办法，谁教你以吓死人的方式登场……」

忍不住如此反驳到一半，随即不停地摇头。

「不对，这里不是什么约会地点，所以带你过来完全没问题。」

「什么嘛～这么久不见了却净说些冷淡的话耶，桐仔。可以来个重逢的拥抱哟？」

丢出这样的台词并且摊开双手的是黑色水手服上加了卡其色运动外套，还背着一个小小背包的娇小女学生。说是娇小也只比亚丝娜矮一点，跟西莉卡并排的话应该比她高一两公分吧。跟经常碰面的时期比起来，身高似乎长高了一点……这就表示原本认为比我年长许多的她，在当时也是成长期吗？然后说不定现在也是。

「老鼠」亚鲁戈。

在浮游城艾恩葛朗特被如此称呼的高超情报贩子，在短短数十分钟前突然出现在归还者学校的我们教室里。男女比例完全失衡──当然是男生比较多──的这座学校里，陌生女孩子穿着其他学校制服登场怎么可能不受到瞩目。在被班上的男生们包围之前，我就拉着亚鲁戈的手从教室里逃出来，但是现在才刚到午休时间，走廊上到处都是学生，所以只能来这片绿地避难。但一旦只有两个人独处，就涌起了另外一种紧张感。

我一点一点跟笑着摊开双臂的亚鲁戈拉开距离。

「还……还是等下一次吧。」

「怎么还是一样胆小呢，桐仔。」

「我就是胆小啦！倒是……说起来，你为什么会在这里？」

我好不容易提出最初的问题后，亚鲁戈就把摊开的双手伸进运动外套口袋里，并咧嘴笑了起来。我忍不住认真地凝视着她的脸庞。

褪色卷发下的脸庞，确实长得跟艾恩葛朗特里熟悉的「老鼠」一模一样。但或许是受到两颊没有老鼠胡须的彩绘，或者是将近两年……不对，从死亡游戏开始时算起已经过了长达四年的时间所影响，她的模样变得成熟许多。老实说，我在艾恩葛朗特首次跟老鼠接触时，不由得浮现「究竟是男是女？」的想法，但现在眼前的人物就算没有穿水手服也明显是女性，甚至让我犹豫是不是该跟以前一样以「你这家伙」来称呼她。

不知道是不是看穿我这样的胆怯，亚鲁戈脸上浮现出调侃的笑容，然后再次缩短距离并且说道：

「哪有为什么，当然是因为转学过来了啊。」

「啥……啥啊啊啊？」

忍不住这么大叫，但又急忙闭上嘴巴。我压低音量，再次开口问道：

「你说转学……为什么从SAO解放出来都过两年了才转学呢？而且在这之前，你为什么完全没有跟我联络？我还以为你已经……」

虽然没有办法继续说下去，但亚鲁戈却带着笑容震动着娇小的肩膀。

「我怎么可能会挂掉呢。说起来，你自己还不是没跟我联络。凭桐仔的人脉，应该很容易就能入手我在现实世界的情报了。」

「…………」

确实是这样没错。

SAO时代，我不清楚亚鲁戈的本名、地址和电话号码，但是知道「Argo」这个角色名称。把它告诉总务省假想课的菊冈诚二郎的话，应该可以从使用者登录档案里找出各种情报才对。

但不仅限于亚鲁戈，我没有积极地去调查在SAO里认识又不确定生死者的下落。在第七十五层魔王战顺利存活下来的攻略组众人应该平安登出了，至于除此之外的──比如西田先生，或者是牙王、涅兹哈、马霍克尔等人的生死，我到现在都不清楚。之所以没有去调查，是因为很害怕。害怕从菊冈口中听见该名玩家没能生还的事实。

因为同样的理由，我兴不起调查亚鲁戈现实世界情报的兴趣。当我准备为了自己的怯懦道歉而准备低下头──但是……

亚鲁戈用跟SAO时代差不多的速度缩短距离，竖起右手的食指和中指戳在我的额头上并且用力把头推回来。

「喂喂，我可没要你道歉哟。只是想说我们都没有联络对方。桐仔没有改名字就在ALO和GGO里大闹了一番，我愿意的话也能跟你取得联络。」

移开手指的亚鲁戈后退了一步。我摸着额头，同时犹豫好一阵子该如何回应，最后就直接问道：

「没错……你为什么不来ALO？以你这家伙的个性，不可能会从此害怕完全潜行机器吧？」

「你太小看我了吧。」

苦笑着这么说完之后，亚鲁戈再次把双手伸进口袋，然后前后摇晃纤细的身体。

「嗯～～其实有很多理由啦。我也不是完全没兴趣哟。听见ALO里可以复活旧SAO的角色时，真的差点忍不住……但是呢，就算再次在ALO里挂起情报贩子的看板，感觉也不会有像那时候那样的动力了……」

「……这我也不是不能理解……」

虽然用这种说法，但其实我非常了解她的想法。

Sword Art Online刀剑神域是疯狂天才茅场晶彦所创造的真正异世界，被关在石头与钢铁的浮游城里的众玩家，被强迫在「HP归零就等于真正死亡」的恐怖规则下，以完全攻略游戏为目标。

几乎没有一天不感到恐惧、绝望、焦躁与悲伤。但是那并非一切。升级时的欢喜、获得稀有道具时的兴奋、打倒魔王怪物时的痛快都是和SAO之前玩过的游戏完全不同的真正感情。虽然不愿意承认，但就算我觉得现在主要游玩的ALO是无比的欢乐，还是没办法像SAO时那么认真了……

甩开刹那间的感伤，我再次提出问题。

「……那这两年来，你都在哪里做些什么？」

「当然是在老家当学生呀。」

「…………啊……」

听她这么一说就觉得确实是如此。我在攻略完SAO之后，虽然发生了许多事情，但基本上也是「在老家当学生」。

「你老家在哪里？还有你是几年级啊？」

听见这些问题，亚鲁戈突然就对我伸出右手。

「两个问题要一千珂尔哟。」

「嗯嗯……」

在准备要从制服口袋抓出一千珂尔金币，回过神来才停下动作的我面前，亚鲁戈露出了愉快的笑容。

「喵哈哈哈……开玩笑的啦。老家在神奈川的左下方，学年是高三哟。」

「左下……」

我这么呢喃，同时在脑袋里摊开神奈川县的地图。在西南部的有小田原、箱根、热海……已经是静冈了吗？不论如何，跟东京绝对不算近。然后高中三年级的话就是长我一个学年，跟亚丝娜和莉兹一样半年后就毕业了。

「……为什么现在才转学到这里来？」

「嗯嗯～～」

发出简短的沉吟声后，亚鲁戈就说了句「好吧」并耸肩，然后把手伸向背着的小型背包。灵巧地反手打开口袋取出四角形盒子。从黄色皮革制的盒子里拿出一张灰色卡片来交给我。

接过来的那个就是所谓的名片。我的眼睛被印在中央的名字吸引过去。

「帆坂……朋……这是本名？」

「抱歉喔，有个不像本名的名字。」

「没……没有啦，我不是这个意思……只是没想到你会如此轻易就告诉我本名……」

「既然转学过来了，也没什么好隐瞒的吧。」

我的视线从稍微噘起嘴的亚鲁戈，也就是帆坂朋的脸庞移回名片上。

名字右下方印着电子信箱与手机号码。然后左上角是职称。凝眼一看之下──上面写着「MMOToday 记者／调查员」。

「咦，真的假的？」

光听见我惊讶的声音就察觉我对什么有所反应般，亚鲁戈轻轻点了点头。

「真的哟。」

「MToday的记者……那我看的新闻里有些就是你写的吗……？」

「或许吧。」

「等等，但是MToday基本是以The seed的新闻为主吧？没玩过也可以写新闻吗？」

「我负责的不是个别的游戏，而是The ssed连结体的综合新闻还有硬体方面。嗯，偶尔也会创角色进行潜行，不过取材结束后就立刻砍掉了。」

「哦……」

吐了长长的一口气后，我再次看向亚鲁戈的脸。比我年长一岁这件事没有让我受到太大的冲击，但听到她现在是VRMMO界最大网路媒体的MMOToday的记者，就让我这个甚至没打过工的一介学生感到相当大的差距。

「……看来以后不能用你这家伙来称呼你了……今后要改用帆坂小姐……」

「别这样！轻松一点就可以了啦。」

一脸认真地说完后，亚鲁戈就对着我抬起下巴。

「然后呢？只叫我报上本名，你自己不说吗？」

「嗯？啊，噢……」

这时候才终于发现我还没说出自己真正的姓名。虽然这时候再自报姓名实在有点不好意思，但我也没有名片，所以也没其他办法了。

「呃……我叫桐谷和人。今后请多指教。」

「嗯，请多指教。」

亚鲁戈咧嘴笑着并伸出右手。这次手掌是直向，所以应该不是跟我要情报费。于是我畏畏缩缩地伸出手来跟她握手。

透过强力被握住的手感觉到己身之外脉动的那个瞬间──

「……真的还活着呢。」

原本实在无法说出口的话语就这样从口中掉落。

结果亚鲁戈也浮现带着另一种言外之意的温柔微笑说道：

「都是托桐仔的福。其实我总觉得自己活不到一百层。如果不是桐仔在第七十五层就攻略了游戏，我一定不知道在什么地方就挂掉了。」

「不光是我一个人的力量……」

突然被胸口揪紧的感觉袭击，好不容易才开口回答她。实际上，能在艾恩葛朗特第七十五层打倒希兹克利夫──茅场晶彦，是因为许多玩家支持、鼓励、引导我才能完成的结果。而眼前的亚鲁戈当然也是其中一个。

──她还活着真是太好了。

深切地体认着这一点并且放开手。深吸了一口有森林味道的空气，然后把残留在胸口的感慨一起呼出之后，才把话题拉回来。

「那么……亚鲁戈转学到这里的理由，和担任MToday记者这件事有什么关系呢？」

「啊，关于这个嘛……」

但亚鲁戈这时候就闭上嘴，朝「秘密庭园」唯一出入口的绿篱间隙看去。几乎在同一时间，我也听见轻快的脚步声。

几秒钟后，冲进绿地的是右手上握着手机的亚丝娜。移动到这里的路上，我已经先传了讯息给她。在草皮上停下脚步的亚丝娜先看了我一眼，然后把视线移到旁边的亚鲁戈身上──

「……骗人……」

然后这么呢喃。瞪大的栗色眼睛在透过树叶缝隙的阳光照射下闪闪发亮。亚鲁戈也眨了眨眼睛，然后举起右手开合了一次。

「嗨，一切都还好吗，小亚……」

但是她没能把话说完。以宛如被SAO时代的「闪光」附身般的速度猛冲过来的亚丝娜，全力抱住了比自己矮一点的亚鲁戈。我好不容易才在空中接住从亚丝娜右手滑落的手机。

亚丝娜把脸埋在亚鲁戈的肩口，接着以细微的声音说：

「我一直相信……我们绝对会再次见面。」

「……抱歉这么长一段时间都没联络呀，小亚。」

对着亚丝娜这么呢喃的亚鲁戈，温柔地拍了拍她穿着衬衫的背部。然后两人的身体才终于分开，亚丝娜仔细地望着亚鲁戈的脸一阵子后，才说出十几分钟前我刚提过的问题。

「那么……亚鲁戈小姐为什么到这里来呢？」

归还者学校的午休时间是十二点四十分开始到一点三十分的五十分钟。以高中来说算是长的了，但仍不足以尽情地闲聊过去的往事。而且怎么说也还是在成长期，不吃午饭实在是相当痛苦的修行。

因此我事先传了「到学校餐厅买三人份的食物，然后到秘密庭园来」的讯息。亚丝娜买来的是潜艇堡，其中一个夹了卡芒贝尔干酪＆火腿＆芝麻菜，第二个夹着奶油起司＆烟熏鲑鱼＆番茄，最后一个则是虾子＆酪梨＆罗勒。在白檀树下铺上极薄塑胶垫后坐下来，亚丝娜就给亚鲁戈优先选择的权利。

「亚鲁戈小姐，选你喜欢的吧。今天我请客。」

「哎呀，这怎么好意思呢……」

面对推辞的亚鲁戈，亚丝娜笑着递出三个潜艇堡。

「不用客气喔。当我跟桐人在第二十二层购买森林小木屋时，亚鲁戈小姐也帮忙完成任务。这是那个时候的谢礼！」

「……啊，确实发生过这种事呢。」

很怀念般眯起眼睛后，亚鲁戈就露出灿烂的笑容。

「那我就不客气喽。我……选这个。」

说完就伸手去拿的是夹着烟熏鲑鱼的潜艇堡。由于转过头来的亚丝娜对着我问「桐人要哪一个？」，我便思考这两个的话亚丝娜应该会选择酪梨，于是回答「火腿起司！」。

这算是我的坏习惯，明明从SAO里解放出来已经过了两年──然后在那个世界和亚丝娜一起生活只有短短两个星期，还是无法抛开两个人共有道具栏时的习惯，这种时候很容易就忘记付亚丝娜帮我垫的费用。刚接过潜艇堡才终于注意到这件事，于是急忙拿出手机。因为亚丝娜也买了三人份的冰红茶，我就在结帐应用程式里输入加上这些费用后除以二的金额，然后让亚丝娜的手机读取显示的条码。虽然使用Augma就能轻松完成个人间转帐，但急忙冲出来的我把它放在教室的包包里了。

当我想到这里的瞬间。

「……啊！」

我在右手拿着手机左手拿着潜艇堡的情况下发出叫声。

这次的午休已经决定好在餐厅和莉兹以及西莉卡一起讨论昨天震撼The seed连结体的异常状态。而且这场会议连在大宫的高中念书的直叶，还有就读于上野附近高中的诗乃也预定戴上Augma来参加，现在她们应该等不及我和亚丝娜前往餐厅了吧。

面对整个人僵住的我，亚鲁戈露出了纳闷的表情，不过亚丝娜则是以「真拿你没办法」的模样开口说：

「果然忘记了吗？别担心，我已经联络大家希望把会议延到放学之后了。」

「这……这样啊……给你添麻烦了……」

在我道歉之后，亚鲁戈也轻缩起脖子。

「哎唷，你们两个人本来有事吗？那真是不好意思啦。」

「没关系，反正我原本就觉得只有午休时间完全不够了。」

如此回答的亚丝娜把装冰红茶的杯子递给我们。

「我们还是快点开动吧。都快饿扁了。」

关于这一点我当然也同意。于是急忙打开包装纸，从食材满出来的边缘大口咬下。餐厅内的轻食摊是由本地的熟食店经营，虽然没办法说是刚出炉，但潜艇堡的外皮相当香蔬菜也很新鲜。默默吃了两三口之后又喝了口红茶把食物吞下肚。

亚鲁戈也瞬间吃掉半个，然后以满足的表情做出评论。

「这不是学校面包的水准呢。转学到这里果然是对的。」

「餐厅的食物也都很好吃喔……不是啦……」

轻咳了一声后，我才再次丢出遭到中断的问题。

「差不多该告诉我们亚鲁戈在这个时期转学过来的理由了吧。」

「时期没什么好奇怪的吧。这个学校分为上下学期来招收转学生，今天是下学期的入学日啊。」

「咦，是这样吗？这样的话……干脆就别用三学期，改采两学期制不就好了……」

「这样寒假会消失哟。」

「当我没说过。」

看见立刻这么回答的我，亚丝娜就一边发出轻笑一边做出解说。

「这间学校是今年八月才开始有转学生制度的。所以暑假结束时好像已经来不及，紧急变成从九月底开始招收。亚鲁戈小姐算是转学生第一号吧。顺带一提，听说即使不是前SAO玩家也能够转进来。」

「这样啊……但是──会有普通学校的学生特别转学到这里来吗？社会大众好像把这里当成隔离设施吧……」

「关于这一点呢，因为这里是职业学校，所以有许多实作的课程对吧？而且是学分制，可以选择真正有兴趣的课上……这些事情经过媒体报导之后，对本校有兴趣的人似乎变多了。我们班上也有转学生。那个女孩子就是这么说的喔。」

「这样啊……那亚鲁戈也是因为同样的理由……」

当我说到这里，我才注意到一件事。

预定和莉兹她们讨论的异常事态──大量玩家被从无数的The seed规格游戏里强制转移到同一个世界的「Unital ring」事件，是在昨天也就是九月二十七日发生。

然后在MMOToday写The seed连结体相关新闻的亚鲁戈突然转学过来的今天是九月二十八日。

这是偶然吗？刚才亚鲁戈说过「是下学期的入学日」，但我不认为这是唯一的理由。

「亚鲁戈，你这家伙难道是因为Unital ring才……」

当我说到这里，亚鲁戈就迅速举起左手的食指戳着我的嘴角。

「哎呀，别这么急嘛，桐仔。我会好好说明，而且现在时间也不太够。你刚才说过放学后要开会之类的，到时候我也可以参加吗？」

「咦……咦咦？」

我忍不住跟亚丝娜面面相觑。

SAO时代，亚鲁戈虽然以情报贩子的身份对死亡游戏的攻略做出很大的贡献，但是中层以后就贯彻居于幕后的做法，连我见到她的机会都变得很少。西莉卡和莉兹或许听过她的名字，但她们应该没有买卖情报的经验，至于莉法与诗乃则是完全没有交集。

但是现在想起来，莉兹她们跟莉法也是一年半前才认识，诗乃更是在短短九个月之前。但现在却像是老朋友一样熟稔，所以和亚鲁戈应该也能够打成一片才对。我和亚丝娜互相点点头然后重新转向亚鲁戈。

「当然可以喽……不过，怎么说呢，你可别胡言乱语啊。」

「怎么样叫胡言乱语？」

「这个就要交给你的良心去判断了。」

一脸认真地这么请求完后，我再次吃起剩下的潜艇堡。亚鲁戈和莉兹贝特她们应该能成为好朋友才对……即使如此相信，内心还是被某种不祥的预感袭击。

下午三点三十分的班会时间结束之后，我就迅速离开教室，急忙赶往第二校舍三楼北端的电算机教室。

虽然是名字听起来相当有威严的教室，不过只是这栋建筑物仍是都立高中时曾在这里进行过情报相关课程，并非有什么巨大的大型电脑在此坐镇。而且当时设置的桌上型电脑现在几乎都已经撤走，所以甚至有种名不符实的感觉。

修了机械电子学的我和两名修同一门课的男学生组成研究小组，正式向学校借用电算机室作为研究室。我们三个人各有一把教室的钥匙，不过另外两个人说今天要去秋叶原购买零件，我便趁着这个机会在这里举行会议。

跑过走廊爬上楼梯来到三楼。原本以为我是最早到的，结果莉兹贝特也就是篠崎里香的身影已经出现在电算机室门前。

「太慢了！」

面对一看见我就这么大叫的莉兹，我竖起右手来表示道歉并且如此回答：

「没有啦，是你太快了……我班会一结束就立刻冲出来了。」

「因为我们班导师出差了，所以今天没有班会啊。」

「那就在教室杀杀时间再过来啊……」

「就觉得慢慢走过来时间会刚好嘛！」

虽然跟在ALO里面一样以熟稔的口气说话，但在这间学校里我是二年级，而莉兹是三年级，所以还是会有些顾忌。我明明在现实世界连跟比自己年长许多的克莱因与艾基尔都能轻松对话，所以说学校这个地点所拥有的力量真的很恐怖。当我想着「用The seed制作以巨大学校为舞台的游戏说不定会很受欢迎，不对，应该早就有了吧」的时候。

「还发什么呆，快点开门啊。」

背部被莉兹打了一下，我便点头回答「啊，嗯」。从口袋里拿出附有褪色塑胶标签的钥匙并插进钥匙孔内。转动滞涩的圆筒锁后打开拉门，接着把右手贴在胸前行了个礼。

「请进，莉兹贝特大小姐。」

「辛苦你了。」

接着就随大剌剌这么回应的莉兹走入电算机室。虽然平常已经尽可能用吸尘器打扫了，还是无法消除古老教室特有的阳光气味。透过白色窗帘的午后阳光在教室内形成强烈明暗对比，我做出没有必要点灯的判断。

「哦，感觉很不错嘛。我很喜欢这种气氛。」

初次来到电算机室的莉兹做出这样的评论，我则因为已经看惯了而没有什么感想。如果是木造建筑物的话或许还值得拍一下照片，不过第二校舍还不至于那么古老。墙壁是有些龟裂的水泥，地板是磨薄了的油毡，并排在一起的桌子也是便宜的美耐板制。但莉兹像是很稀奇似的一边四处张望一边横越教室，然后在深处的窗边回过头来露出隐含深意的笑容。

「不觉得这样好像校园动画吗？男孩和女孩放学后在旧校舍里独处……」

当我因为她突然的胡言乱语而吓得后仰时，她便以右手的食指对着我并且说：

「然后以华丽的能力大战。」

「大战吗……」

我一放松肩膀的力道，莉兹也放下右手嘻嘻笑着说：

「不然你以为要做什么？」

「没有啦，没什么……倒是大家怎么这么慢。」

我这么说的瞬间，前面的门就喀啦一声被拉了开来。

「久等了～」「让大家久等了！」

同时这么说并且走进来的是亚丝娜和西莉卡。两人的身后……没有第三个人的身影。

明明自己说要参加会议，亚鲁戈那个家伙该不会翘头了吧。原本想还是联络一下而准备把手伸向手机，这才发现尚未交换联络方式。短短两个小时前在秘密庭园分手的「老鼠」，身影逐渐消失在从树叶透下的阳光当中。简直就像我和亚丝娜在那个时间看见的是幻影一样……

「安安～」

结果亚鲁戈本人就随着这种脱线的招呼声从打开的门口走进来。害我差点就跌倒。亚丝娜笑着跟她挥挥手，莉兹和西莉卡则是愣住了。

还是穿着运动外套的亚鲁戈，注意到她们两个人后就轻轻点头致意，接着朝我看来。

「喂，快点帮我介绍一下呀。」

「噢，嗯……莉兹、西莉卡，这家伙是亚鲁戈。今天起转学到这间学校来，和我们一样是SAO生还者，在艾恩葛朗特是……」

说明到这里的瞬间，亚鲁戈便插话进来。

「在艾恩葛朗特是桐仔的大姊姊。」

莉兹大叫：「桐仔？」

西莉卡则是叫着：「大姊姊？」

我横向冲刺到亚鲁戈身边，拉着外套的兜帽把她吊起来……虽然很想这么做，但还是按耐下冲动，以凶狠的口气呢喃：

「我说过别乱说话了吧！」

「什么嘛，这不是事实吗？」

「哪里是事实了！只是客人与老板的关系吧！」

「啊～这种说法太过分了。亏我好几次都给桐仔你特别待遇……」

当我们这么争执时，背后的亚丝娜就发出「拿你们没办法」般的声音。

「别再吵了，差不多该进入主题了吧？我觉得等会议开始再介绍亚鲁戈小姐比较好。直叶与小诗诗都是首次见到她。」

「啊，嗯，说得也是……所以……」

我看着目前仍瞪大眼睛的莉兹与西莉卡说道：

「马上就能说明这家伙是什么人，可以先帮偶准备一下开会吗？」

「你的语气变得很奇怪喔。」

被西莉卡以阴暗的眼神盯着，我只能往后冲刺来退避到自己的书包旁边。

电算机室的桌子跟教室里的不同，属于三人座的长型桌，所以在房间中央将两张桌子合并起来完成即席的会议桌后我们便坐在桌子周围。长边的上座是亚丝娜与亚鲁戈，下座并排坐着莉兹与西莉卡，我则是坐在走廊侧的边缘。

所有人一起戴上Augma──亚鲁戈的除了涂上芥末黄之外，后脑勺的电池部分还画着老鼠图样──完成起动后，桌上就出现妖精大小的结衣。

「爸爸、妈妈、莉兹小姐、西莉卡小姐，午安！」

以可爱声音打招呼的结衣把目光放在亚鲁戈身上。

「咦，这一位是……」

「啊～这个嘛，我马上就会说明，还是先开始会……」

当我说到这里时，结衣就眨了一下眼睛并且咧嘴笑着说：

「是亚鲁戈小姐吧！爸爸和妈妈在SAO里受到很多照顾。我的名字叫作结衣。」

亚鲁戈张大了嘴，同时以认真的眼神盯着低头行礼的结衣看。

「那个……为什么知道我是亚鲁戈呢……？」

「SAO的角色档案与生物辨识有九十八％一致！」

「……我在这两年里长高了不少耶……」

「是加上成长预测模拟后才进行辨识！」

这时亚鲁戈似乎终于发现明确回答着的结衣不是真正的小孩而是AI了。她沉默了三秒钟之后就对着桌上伸出右手。

「嗯……嗯，今后也请多多指教。」

「好的，请多多指教！」

结衣以娇小的双手抓住亚鲁戈的指尖。现在想起来，对于在现实世界也从事情报贩子般工作的亚鲁戈来说，应该会对结衣那活生生的人类绝对无法比拟的情报收集能力感到垂涎三尺吧。得小心别让她找结衣去打什么奇怪的工……当我这么想时，视线前方的结衣就回到桌子中央并且摊开双手。

「那么现在和诗乃小姐与莉法小姐连线！」

「啪哩啪哩」，空中描绘出蓝白色火花般的特效，桌子的窗户那一侧出现诗乃与直叶的身影。两个人都穿着制服，各自坐在外表不同的椅子上。

今天是首次使用结衣帮忙建构的「AR会议系统」，但彷佛两个人真的在眼前般的真实度实在令人大吃一惊。诗乃她们似乎也跟我一样，一边瞪大了眼睛一边环视着电算机室。

「……哦，这里就是归还者学校吗……」

如此呢喃的诗乃准备从椅子上站起来，我便急忙用双手阻止她。

「喂，不能乱动啦。现在诗乃与小直的视界被Augma覆盖过去了，这样会撞到那边的物体然后跌倒喔。」

「啊……对喔。顺带一提，我是在视听教室，如果有其他学生进来的话，就会看到我对着空无一人的空间说话吧？」

听见诗乃的问题，结衣便回答「没有错！」，结果旁边的直叶就绷起脸来。

「呜哇，我是从保健室连线的。这期间绝对有人会来啦。」

「咦，小直，你不用去社团吗？」

我一这么问，剑道社员就稍微吐出舌头来说：

「我把今天变成休息日了。」

「喂喂，这样没关系吗？之后不会被三年级的处罚吗？」

「不用担心啦！应该说，三年级的学生在八月的大赛后就引退了，我现在是副社长喔。」

「咦，真的假的？早点说嘛，都还没有帮你庆祝耶。」

「当上副社长没什么好庆祝的啦。不过十一月的新人战如果获得好成绩的话就要帮我大大地庆祝一番喔！」

当兄妹轻松地进行对话时，西莉卡就露出惊讶的模样对着直叶问道：

「莉法小姐是副社长的话，表示有人比你更强喽？」

「当然有了。练习时互有胜负，但我的剑法有些自创流派的部分……社长果然还是得正统派的人才行。」

听见这些话后不免再次担心霸凌的问题，但是没有人望的社员应该不会当选副社长吧。举行全国大赛的八月上旬我还在住院当中，所以没办法去帮忙加油，但新人战一定要去观战……如此下定决心的我提高声音表示：

「那么，本来就没什么时间了，我们差不多该开始会议了。首先呢，要介绍这个家伙……不对，是这个人。」

被我指着的亚鲁戈，稍微起身向大家点头致意。

「这个人是今天转学到归还者学校的帆坂朋小姐……SAO里的外号是『老鼠』亚鲁戈，职业是情报贩子。」

一听见我这么说，莉兹和西莉卡就同声大叫「啊！是发行攻略册的！」，诗乃与莉法脸上露出疑惑的表情表示「什么是攻略册？」，至于亚鲁戈本人则是有点害羞般发出「咿嘻嘻」的笑声并且站起来和除了我、亚丝娜以及结衣以外的四个人握手──远距参加的两个人由于没有触碰判定所以只是做出握手的模样。我看着这种模样，内心忍不住想着这下子队伍的男女比例又要更加失衡了。

这间学校的男学生也有许多VRMMO玩家，想招募成员的话随时都没问题，但实在无法付诸实行。理由一定是因为在度过长达两年时光的Underworld里已经遇见生涯最佳友人的缘故吧。不认为今后还能遇见像他那样值得信赖的同性、同年代的好友，而且也不会想再找一个了。当他在激斗的最后丧失生命时，我内心的一部分也跟着死去了。而这个伤口可能一辈子都无法痊愈。

深深吸了一口带着蜡油味的空气，压抑下胸口的疼痛后，我便开口表示：

「既然自我介绍结束了，我们立刻进入主题吧。首先想知道的是，ALO以外的玩家的状况……GGO的诗乃也被强制转移到『Unital ring』了吧？」

「嗯。」

所有人的视线集中到点头的诗乃身上。

「为了慎重起见还是问一下，你知道登出后虚拟角色也会留在里面吧？能够确保自身的安全吗？」

「嗯……应该没问题。因为鸟人会帮忙保护我。」

包含我在内的所有人都从头上冒出问号，诗乃也像要表示「我自己也搞不懂」般耸了耸肩。

** 第三章

从吉祥寺车站北口出发的巴士难得会这么空。坐在车门附近位子上的明日奈把书包放在大腿上并呼了一口气。

心底深处还残留着没想到能再次跟亚鲁戈相遇带来的温暖。但同时也存在些许不舒服的感觉。让明日奈产生这种感觉的是跟另一名转学生──神邑樒的邂逅。

樒没有对自己散发出敌意。虽然只有进行短短几分钟的对话，但对方的态度一直很沉稳。据说明明被编到隔壁班却还是特地来跟亚丝娜打招呼的理由是幼年时期曾经在电子工业界团体的派对当中见过面。明日奈已经不记得了，不过神邑樒是RCT的竞争对手，也就是Augma开发厂商「CAMULA」创业者的女儿。

但是让明日奈心情产生紊乱的并非她的出身。

她所穿的是──属于港区的小中高直升制的私立学校，圣永恒女学院高中部的制服。也就是明日奈在成为Sword Art Online刀剑神域的囚犯前所就读的学校。

明日奈虽然只念到国中，但是不记得同学年里有姓神邑的学生。这是相当罕见的姓氏而且对方的容貌又相当吸睛，不可能三年里都完全没注意到吧。

也就是说樒是从校外转学到圣永恒女学院高中部，然后在毕业的半年前又转学到归还者学校。

询问这样不会对学测有不良影响之后，樒表示预定是到国外留学，似乎已经取得大学预科课程的国际文凭以及SAT测验的正式成绩单。听说美国的大学把写作水平看得跟分数一样重要，所以能够理解她为了拥有个人特色的内容而体验归还者学校生活的选择，但也无法否定这样的想法有点太离奇，感觉自己像是被视为特殊生一样，老实说这实在令人不怎么愉快。

之所以会有这种感觉，应该也是受到樒所穿的制服影响吧。没有发生SAO事件的话明日奈可能也穿着那套灰色西装外套制服。圣永恒女学院国中部的制服是没有特征的背心裙，所以缝合深蓝色衣领的高中部西装外套看起来特别时髦。实际上被母亲要求参加外部高中学测的明日奈可能没有穿上它的机会，但突然出现在眼前果然还是会忍不住胡思乱想。

对于就读归还者学校一事不感到自卑，也不希望人生从四年前重新开始。只不过穿着那套制服的神邑樒，简直……简直就像是没有被囚禁在SAO内，继续就读于圣永恒女学院的自己……

「……真像个傻瓜。」

小声这么呢喃完，明日奈就闭起眼睛。公车还要九站才会到达吉祥寺车站。今天晚上似乎也会熬夜，所以要趁能睡的时候先睡一下才行。

虽然把头靠在巴士的内壁上，但是却一直没有睡意。神邑樒那近乎完美，但不知道为什么让人产生些许不安的伶俐美貌一直烙印在脑海里。

对于目前的境遇没有不满。因为遇见了打从心底喜爱、信赖的和人与结衣，以及最棒的伙伴里香、珪子、诗乃以及直叶。樒应该是走在不会有丝毫过失的菁英路线上，但不论她用什么样的眼光看我，我都能断言自己相当幸福。

──当想着这种事情时，就表示内心已经乱了。

明日奈吐出又慢又长的一口气，然后要自己只想开心的事情。

被强制转移到「Unital ring」这个谜样VRMMO世界给The seed连结体带来了大混乱，但现在明日奈并不感到不安与恐惧，挑战未知的游戏反而让她有种强烈的高扬感。即使是死亡一次就再也无法登入这种极度严苛的规则，也无法让身为SAO生还者的明日奈感到胆怯。

现在包含ALO的营运公司YMIR在内的许多企业都彼此合作来试着解决事情──由于亚鲁戈这么表示，这个事件总有一天会结束才对。在那之前无论如何都要保护森林之家与众伙伴，然后有时间的话还要解开世界之谜。

可惜的是亚鲁戈表示短期内还不打算加入Unital ring的行列，但她转学过来的理由似乎也不是跟UR毫无关系。据说她在一阵子前就掌握了UR事件的预兆，为了找出隐藏在事件背后的真相而下定决心转学到归还者学校。

不会说出未经实证的情报似乎依然是亚鲁戈的坚持，而会议的时间也有限，所以她也不再透露更多的内情，但她似乎打算从外部调查Unital ring的秘密。在学校分开之前，她咧嘴笑着这么说。内部的调查工作就交给小亚你们哟。听她这么说，也只能好好努力了。

虽然不曾对漫长的通学时间感到痛苦，但只有今天明日奈才兴起家里离学校近一点就好了的念头。不知不觉间，让心底深处一阵骚动的感觉消失了。

** 第四章

「我回来了。」

边说边拉开玄关玻璃门的瞬间，「欢迎回来！太慢了吧哥哥！」的声音就飞了过来。

一看之下，身穿运动服站在木头横挡上的直叶，这时将双手在胸前握住并且垂直跳动着。

「有什么办法嘛，我的通勤时间是你的一倍。我已经是从车站全速冲回来了喔。」

实际上九月已经结束了，我的额头上却还浮现汗珠。六分钟就骑着脚踏车跑过本川越车站到桐谷家大约两公里的距离几乎已经是自我最佳纪录了，但直叶似乎不到五分钟就能完成，所以在她面前不能太嚣张。但我的贤妹没有责备哥哥缓慢的脚程，反而对我递出原本在身后的毛巾。

「来，这个！」

「哦，谢啦。」

接过来擦拭汗水后，这次换成矿泉水的宝特瓶出现了。

「来，还有这个！」

道完谢接下打开瓶盖递过来的水后，我一口气喝掉大半瓶。

「呼～活过来了……」

「那现在开始冲刺！」

被推着背部爬上二楼来到自己的房间。当我在换上T恤与短裤时，直叶没有敲门就直接冲进来。

「准备好了吗？那我们马上出发吧！」

连珠炮般说出一串话的妹妹，右手上抱着老旧的AmuSphere。

「什么出发，你想从哪里潜行啊。」

「当然是从这里喽！不配合彼此的时间，在里面变成独自一人的话可能会遭遇危险吧。」

「哪有那么夸张……又不是时间加速中的Underworld，就算错开也只有一两分钟吧。而且莉兹和西莉卡应该已经在里面了。」

「别说这么多了，快点快点！」

啵一声在我头上罩下AmuSphere后，直叶用足以让底板的木制弹簧发出摩擦声的速度跳上床。没办法的我只能躺在她旁边。直叶抬起右手，竖起三根指头。

「倒数三声后出发哟！三、二、一……开始连线！」

我同声咏唱着指令，而且想着「这样直叶的手掉下来不就会打中我的侧腹部」。不过我当然无法确认这个结果。

张开眼睛后，看见全新的木板屋顶。

今天早上四点左右还开了个足以看见天空的大洞，不过现在已经消失无踪。从艾恩葛朗特连同土台一起分离、坠落时受到极大损害的圆木屋──我心爱的「森林之家」在会合的莉兹与西莉卡的帮助下顺利地完成修复。

真的真的太好了……当躺着的我沉浸在这样的感慨当中时，侧腹突然就被戳了一下。

「快点起来啦桐人！有很────多事情要做喔！」

「是是是……」

带响着莉兹贝特帮忙打造的铁铠甲站起身子并且看向旁边。同时潜行的直叶──莉法依然穿着简朴原始布料制成的洋装。

我接着又环视室内。由于所有家具都消失了，所以显得相当空旷的客厅里看不见其他玩家的身影。亚丝娜应该还在回家途中，不过莉兹和西莉卡，以及当我们到学校去时轮流看守这个房子的爱丽丝与结衣到哪里去了呢？

当我这么想的瞬间，就听见窗外传来「锵！」的尖锐声音。那是铁锤敲打铁砧的声音……不对，是武器互击的声音。

「怎么了！」

我急忙站起来，打开门后冲到外面。

看见的是被各种生产设施包围的前院正中央，有两道拿着剑朝对方攻击的身影。这个Unital ring世界的时间是跟现实同步，所以红色夕阳形成逆光，无法清楚看见两个人的容貌。其中一道人影的身高跟我差不多，另一道则特别娇小，看起来就跟孩子一样。

「呀啊啊！」

小孩子随着稚嫩但勇猛的叫声挥落两手握住的剑。速度虽然快，但大人却悠然以右手握着的剑挡下。「锵」的撞击声再度响起。编成较粗辫子的金发反射夕阳后发出美丽的光芒。

这时我才终于发现大人是爱丽丝。而面对最强整合骑士依然毫不胆怯地发动攻击的黑发少女，正是我跟亚丝娜心爱的女儿，同时也是最高等级的Top-down型AI──结衣。

「喂……喂，你们两个在做什么……」

当我反射性想插身而入时，莉法就抓住我的肩膀。

「等等，那只是在练习吧？」

「练……练习……？」

我瞥了一眼妹妹的脸庞后，再次看向庭院中央。

爱丽丝确实挡下了结衣的砍击，但是完全没有进行反击。甚至每次双方的剑互击后还给予结衣各种建议。

「看，没问题吧？」

「唔……唔嗯……」

虽然对着妹妹点头，但我至今为止从未见过结衣拿剑战斗……正确来说是在艾恩葛朗特第一层的地下迷宫里，以GM武器消除最强等级魔王怪物「致命镰刀<The Fatal-scythe>」后就没见过了。由于现在的结衣是被当成一般玩家，所以跟我们一样有HP条，即使爱丽丝没有反击，要是被自己的剑伤到还是会受到损失。

我提心吊胆地看着两个人的练习，结果一脸认真地听完爱丽丝的建议后，结衣就再次缩短距离。她把外型带有异国风情的短剑摆在基本的中段──

「呀啊！」

随着稚嫩但凛然的声音往地面踢去。下一个瞬间，连我也忍不住发出「哦」一声。

VRMMO初学者在以剑攻击时，容易分为「举起」「挥落」两个阶段的动作。根据状况，这不是什么错误的行动，但几乎所有时候都能顺畅连结举起到挥落动作的话，速度与威力都会有所提升。结衣使出的就是确实按照这个办法的斩击，实际上爱丽丝防御时左脚也必须往后退半步。

再次响起「锵！」的清澈金属声。一瞬间静止的两个人灵活地拉开距离。

「刚才那招很不错喔，结衣。」

爱丽丝一如此品评，我也跟着拍了手。两人同时看向这边之后，爱丽丝似乎有些不好意思，结衣则是露出直率的笑容。

「爸爸！欢迎回来！」

我急忙制止右手举着短剑就直接跑过来的结衣。

「喂喂，先把那把剑收起来。」

「啊，对喔！」

紧急煞车的结衣把剑收到左腰的剑鞘内。抱起再次冲过来的心爱女儿，把她高高举起后才让她坐到左臂上。

「我回来了，结衣。那个……为什么突然开始练剑……？」

「当然是为了战斗啊！单手剑技能的熟练度刚刚上升为7了！」

「喔喔，你很努力嘛。」

用右手摸了一下她的头，结衣就像很高兴般发出「嘿嘿嘿」的笑声。

我从ALO带过来的单手剑技能熟练度虽然已经到达封顶的1000，但除此之外新获得的技能都只有2或3左右，以一天就能到达熟练度7来看，她确实相当了不起。

「提升到这种程度的话，是不是能够使用剑技了呢？」

「嗯……」

迅速以右手打开环状选单的结衣，移动到技能视窗后窥看了起来。

「啊，能使用『垂直斩』、『平面斩』和『斜斩』！」

「喔喔，这三招是所有剑技的基础。熟练度再上升一点之后，就教你夺命击或者咆哮八音符等帅气招式吧。」

「好的！」

结衣开朗的回答……

「桐人，关于这件事……」

和这道声音重叠在一起，我便移动自己的视线。穿着白色洋装的爱丽丝不知为何以郁闷的表情走了过来。

「嗨，爱丽丝，谢谢你帮忙看家和指导结衣……那么，你说的这件事是？」

「你也看看自己的技能视窗吧。」

「咦？喔……嗯。」

点完头后就以右手指尖在空中画圆。从随着「沙啷啷」的音效打开的环状选单选择右上的技能图标。打开的视窗里显示获得的技能一览表。由于是按照熟练度顺序排列，最上面的当然就是单手剑技能……

「……咦？」

我瞪大双眼凝视着熟练度的数值。昨天看的时候确实是上限值的1000，现在却少了一个零。

「一……一百？为什么……」

「看来是昨天晚上缓冲时间结束时，带过来的技能其熟练度也下降了。随着熟练度下降，上位剑技也全部无法使用。」

「不会吧……」

在发出呻吟的我旁边，莉法也打开视窗并且大叫「啊，我也一样！」。兄妹差点同时沮丧地低下头，但我在最后一刻撑住了。

「不……不对，等等喔……昨天晚上缓冲期间结束后还跟那群PK战斗了对吧？那时我确实使出了夺命击啊。那招可是挺上位的剑技耶。」

「你也看看剑技一览表吧。」

在爱丽丝催促下，我击点了单手剑技能。打开的副选单里列举了可以使用的剑技。最上面是基本单发技的「垂直斩」、「平面斩」、「斜斩」，接着是二连击的「圆弧斩」、「水平弧形斩」和下段突进技「愤怒刺击」，上段跳跃技「音速冲击」，三连击技「锐爪」……发亮的文字就到此为止。再往下的「垂直四方斩」变成了灰色，击点后打开【使用可能熟练度：150】的小视窗。先不管数值跟SAO与ALO不同这件事，这样的话将无法说明为何可以使用上位技的夺命击。

卷动一览表后，名称在很下面的夺命击果然变成了灰色。使用可能熟练度是……700。和目前的数值100有天与地般的差距。

「到底怎么回事……难道只是重现动作而已……？」

在如此呢喃的我怀中，结衣也稍微歪着头并且说：

「昨天的战斗里，爸爸使用的残暴施力点以及夺命击都确实产生了特效光。我想不可能只是模仿动作才对。」

「就是说啊……」

我点点头后把结衣交给莉法，接着移动到庭院正中央。拔出外型简朴但沉甸甸重量相当可靠的「高级铁制长剑」并且沉下腰部。把左手往前伸，然后右手的剑举到肩膀上往后拉，但剑技的前导特效没有降临。

「呜呀！」

还是不愿放弃的我试着刺出长剑，但只是单纯的单手刺击，完全没有夺命击的如血般光辉以及媲美喷射引擎的巨响。我又试了一次……然后再一次。结果都一样。

「桐人……这样看起来有点逊喔。」

「偶……偶知道啦！」

以孩子气的话回答爱丽丝看不下去的声音后，挥出附赠的第四次──

咻轰哦哦哦哦沙叽咿咿────嗯！

「呜喔哇啊啊啊啊！」

身体被带着深红光芒的剑拖走，我在空中飞行了三公尺左右才从胸部往下跌落。

「咕噁！」

视界左上方的HP条微微减少。当我维持青蛙般姿势发出呻吟时，爱丽丝就冲过来对我伸出手。

「不……不要紧吧？」

「嗯……还可以啦……」

在她帮助下站起身后，就认真地盯着右手的剑看。接着跟爱丽丝面面相觑，战战兢兢地问道：

「刚才发动了对吧？夺击……」

「你们这些现实世界的年轻人不要什么名词都简略化。」

由于对方生气的点很奇怪，我就回答了一句「真的拍谢」，爱丽丝用宛若冰霜的眼神瞪了我一眼后才恢复认真的表情。

「确实……是发动了。到底是怎么一回事呢……」

「请爱丽丝小姐也试试看吧！」

这么发言的是被莉法抱住的结衣。往那边瞄了一眼的爱丽丝，说了句「那么……」并点头拔出腰间的剑。外表和我的剑一样，应该是目前人不在现场的莉兹所打造的吧。

我退到莉法身边后，爱丽丝就以长剑摆出八相的姿势。

由于来自SAO的剑技也以「秘奥义」这个名称存在于她出生的Underworld里，所以在ALO当中也能自由自在地使出多种剑技。但是跟高速连续技比起来她似乎喜欢一击必杀系，目前准备发动的也是单手剑上位单发技「飞矛之剑」。

一边踏出左脚，剑往右后方用力举起。本来这个时候应该会出现蓝紫色特效光，但是剑没有发亮。即使如此，爱丽丝还是……

「呀啊！」

一边发出尖锐的喊叫，一边把剑刺出般猛然挥落。虽然是漂亮的斩击，但没有发动飞矛之剑。爱丽丝把剑拉回来后，又做出一模一样的动作。两次、三次、四次……当我开始觉得刚才的夺命击只是系统错误之类的时候。

爱丽丝大概是第七还是第八次往上举起的剑垂直迸发出蓝色火焰般的光芒。往前踏步后挥出斩击。传出彷佛冰河崩坏的沉重巨响，蓝紫色轨迹在空中摇晃。那无疑是飞矛之剑的特效。

「咦，发动了耶！」

我不停点头同意莉法的话。虽然尚不清楚是系统错误或者原本就是这种规格，但即使是熟练度不足的上位剑技，只要执抝地尝试似乎就能发动。但是机率大概只有一两成左右。实战时拿来使用会让人有点担心，而且不清楚理由更是让人不舒服。

忍不住看向被莉法抱着的结衣，但现在她是没有系统登入权限的普通玩家。所以又想偶尔得自己动脑思考一下……

「爸爸，这个现象的原因说不定不是玩家或者道具，而是跟地点有关。」

由于结衣一脸认真地这么说道，我便一边指着自己的脚边一边询问：

「地……地点？这个空地有某种特殊效果吗？」

「不，不是空地……」

顺着结衣移动的视线看去，发现经过修复的圆木屋在夕阳底下发出闪闪光芒。我终于理解结衣想说什么，小跑步回到房子旁边后用指尖击点墙壁。打开的属性视窗里，第一行是「柏木小屋」的建筑物名，其下方是所有者我和亚丝娜的名字，再下面则是耐久力的彩条。明明今天早上应该完全回复了，叠在彩条上的数字却是【12433／12500】，显示Unital ring世界的建筑物耐久力会自动减少。虽然是麻烦的规格，但减少速度一天大概是120左右，所以算起来完全丢着不管也可以撑一百天。

视窗下部并排着四个按键。从左边开始依序是【情报】、【交易】【修复】以及【分解】。内心确信永远不会按下交易与分解键的我按下情报键。爱丽丝与莉法、结衣从左右两边窥看视窗。

随着轻快声音打开的副选单里，列举了房子简单的说明、地板面积、仓库栏容量、对各属性防御力等数值档案，其下方则有着【特殊效果】栏。

想着「就是这个」的我专心阅读着。显示的效果只有一个。也就是──【等级1／森林的加护：在建筑物中心部半径三十公尺以内，所有者以及其朋友玩家、小队成员能在低机率下使用未满使用条件的攻击技能。】

「……哦，原来如此……」

这么呢喃完我就再次摸了摸结衣的头。

「结衣的推测完全正确。这个『森林的加护』，在ALO的时候就存在了吗……？」

「不，ALO里不存在这样的系统。」

结衣摇摇头后，莉法就插话进来表示：

「嗳，这里写着等级1对吧。这就表示也有等级2和3的特殊效果喽？」

「应该……有吧。虽然无法想像怎么样才能解锁就是了。」

爱丽丝稍微瞄了一眼歪着头的我。

「就跟我们一样，好好培育它就可以了吧？」

「你说……培育房子？要怎么做？」

「像是增加房间、强化构造之类的。我在卢利特附近的森林盖房子时，也是从只有简单屋顶与墙壁的小屋开始，然后一点一点扩大的喔。」

「喔……哦～这样啊。」

我的回答多少变得有点僵硬，但这也不能怪我。在爱丽丝的房子里，她似乎照顾心神丧失的我长达好几个月。当时的事情几乎不记得了，但是还依稀记得她用汤匙喂我吃饭、帮我躺到床上睡觉等事情，所以除了感谢之外也同时涌出了不好意思的感情。

「嗯……嗯，总之这就是上位剑技有时能用有时不能用的原因不会错了。昨天晚上的战斗能够一次就使出夺命击算是运气相当好了。」

「这样要做的事情又增加了。」

莉法的话让我皱起眉头，结果妹妹就理所当然般说道：

「提升房子的等级啊！等级2和等级3的特殊效果很让人在意嘛！」

「啊……噢，嗯，说得也是……」

我虽然点着头，但是对于增建、改建圆木屋还是有点抗拒。因为我比任何人都清楚，亚丝娜从SAO时代就持续对这间房子投注爱情。

但是结衣像是看穿我这样的犹豫般坚定地表示：

「不用担心喔，爸爸！妈妈不是会拘泥于外表的人，只要本质存在，就算房子的形状改变我想她也完全不会在意！」

「本质……是什么？」

「当然是爸爸、妈妈、我和莉法小姐、爱丽丝小姐、莉兹小姐、西莉卡小姐、诗乃小姐能够放心休息的地方！」

「……对喔，说得也是。」

我缓缓点头，然后再次抚摸结衣的头。

「但是……要增建应该是很久之后的事了。首先得巩固整个占地的防御才行……」

我再次环视广场。深邃的森林里突然出现这块直径十五公尺的空间，东半部被圆木屋占据，西半部则排着高炉与铸造台、素烧窑等大型生产设备。这些设备只要有素材道具就能轻松制造出来，但是要搜集素材一点都不轻松，可以的话还是想防御整个广场。今天我们到学校去时，结衣、爱丽丝以及亚丝娜驯服的长喙大鬣蜥──阿蜥帮忙看守房子，但光靠两人与一只动物实在很难抵挡昨天让我们陷入超级苦战的尖刺洞熊与新敌对玩家集团的袭击。

自傲的骑士大人似乎也了解这一点，爱丽丝也跟我一样移动着视线并开口说：

「想先从这块草地的外围部分开始建筑一道墙壁。可以的话不要用木头而是石头。」

「说得也是……但要围住整个草地的话不知道需要多少石头。如果亚多米尼史特蕾达猊下在这里的话……弹指之间就可以制造出钢铁之墙了……」

那个半神光靠神圣术就制造出直径一千五百公里的「不朽之壁」来把人界分成四等份，我一提到她的名字，爱丽丝就狠狠瞪了我一眼。

「你拜托最高司祭大人这种无聊的工作试试看，可能会被变成蟋蟀之类的小虫吧。」

「是这样吗，感觉请她吃两三块昂贵的蛋糕，她就会愿意帮忙了。」

──你说是吧，尤吉欧。

在内心这么呼唤亡友，接着轻轻摇头时突然就想起来。昨天爱丽丝说RATH的神代凛子博士有留言要给我。内容是「二十九日，十五点。高级蛋糕店」……这种近似暗号的讯息，真正的发信者恐怕不是神代博士。为了确认事实，二十九日也就是明天下午三点必须到银座的咖啡厅去，但说起来明天完全是平日。从归还者学校的西东京市搭乘西武新宿线到高田马场，再换乘地下铁东西线，然后到日本桥车站再次换乘银座线在银座下车的这条路线，需要的时间大概是八十分钟。不翘掉下午的课绝对来不及。

为什么会指定这样的时间──我先把这样的抱怨吞进肚子里，然后将意识集中在眼前的课题上。既然没有最高司祭猊下那样的超级力量，就只能老实地收集材料来建筑墙壁了。

幸好已经知道建造墙壁不用一个一个把石头堆起来了。初级木匠技能的制作选单里就存在「粗杂的石壁」。虽然粗杂这个形容词让人感到有些敬谢不敏，但是在技能熟练度上升前也只能忍耐了。

「……那么，大家先到河边去捡石头吧。」

我消除圆木屋的属性视窗并这么说道，爱丽丝、莉法以及结衣听见后就一起点点头。

「虽然有点担心，不过就拜托阿蜥……咦？那家伙到哪去了？」

我环视了一下广场，却不见原本应该在看家的长喙大鬣蜥──阿蜥的踪影。不会是驯服状态解除又变回野生了吧，当我慌张地想着这样亚丝娜会很失望的这个时候，从后方传来「咕呱！」这种相当有特色的叫声。急忙转过头去，就看到阿蜥从通往南边河岸的道路上跳着走过来。而且它的后面还能看见西莉卡与莉兹贝特。

两个人发现我和莉法后就小跑步跑过来。

「桐人，太慢了吧！不会是回家路上跑去买东西吃了吧？」

正当莉兹以凶狠眼神瞪着我，旁边的西莉卡就露出苦笑。

「桐人哥住在离学校很远的地方，就是得花这么多时间嘛。」

阿蜥打开嘴巴发出「咕哇」的叫声，坐在它头上的毕娜也发出「啾咿」一声，不过不清楚它们是同意莉兹还是西莉卡的看法。不论如何，阿蜥的驯服状态似乎没有遭到解除的样子。

「你们上哪去了？」

我先开口这么询问，莉兹则是边摸着阿蜥的脖子边回答：

「这孩子似乎一天不玩水几次HP就会减少。所以带它到河边去，顺便收集石头回来。」

「喔喔，真是辛苦了。不过这家伙明明是蜥蜴，却有这么麻烦的体质……」

「爸爸，现实世界有许多半水生的蜥蜴喔。像莫顿巨蜥以及巴氏棱蜥就是有名的种类。」

由于结衣立刻加以注释，我便说了句「这样啊……」并点点头。现在想起来，初次遭遇阿蜥时它就是从水里出现。像鸭子般的喙正是水栖种的证明。

「这下子得快点挖井才行了。要做的事情实在太多！」

我摇了摇头并且确认视界右下角的时针。下午五点五十分──看来今天是没办法潜行到将近天亮了，预定在深夜十二点，不对，凌晨两点结束的话，能使用的时间大概是八个小时再多一点。我忍不住有点怀念可以一整天都用来攻略游戏的SAO时代。

叹了一口气转换心情后，我也为了收集石头而准备前往河岸，结果还抱着结衣的莉法就用手把我挡下来。

「哥哥，如果是这样的话，我觉得应该优先跟诗乃小姐会合比较好吧？以长远的眼光来看，人手多一点作业的速度比较快，战力上也比较可以安心。」

「嗯，是没错啦……」

我摆出微妙的角度点头同意莉法的意见。

放学后举行的会议里，诗乃数次让我们吓一跳。她主要游玩的「Gun Gale Online」也有许多玩家被强制转移到这个世界──虽然已经如此预测，但诗乃他们似乎可以把枪械带到这个世界来。

当然，我们这些ALO玩家都把剑与枪带过来了，GGO的玩家如果无法把武器带过来就太不公平了，但他们的武器是枪械。而且GGO世界里不只有火药式实弹枪，也存在能发射雷射的光学枪。引发这起事件的某个人，到底打算如何维持世界观的整合性呢？

只不过，这不是现在要担心的事情。以ALO来比喻的话，诗乃的爱枪黑卡蒂Ⅱ的超强攻击力甚至足以匹敌三十句咒文等级的最高级攻击魔法。预备的子弹似乎全都消失了，但是既然能带枪进到这个世界，应该就能在哪个地方获得补给，能够和她会合的话据点的防卫将会轻松许多。

但最大的问题是──

「……但完全不清楚诗乃说的那个鸟人村落是在哪个方位啊……」

我耸了耸肩，这时西莉卡也很担心般点着头说：

「诗乃小姐说完全没有注意到艾恩葛朗特坠落时的冲击声。这样的话，我想GGO玩家的起始位置应该跟我们距离很远。」

「唔嗯……」

我发出沉吟时，莉兹贝特就叫出环状选单并且击点左下方的地图标示。摊开的地图和我跟莉法所持有的相比，有相当大的范围已经有颜色了。

「呃……这里是成为ALO玩家起点的遗迹对吧。艾恩葛朗特的掉落地点是这里，然后它的北边有巴辛族的村庄，从该处一直往东北前进就会遇见这间圆木屋……我和西莉卡从村子一路走到这里，但没看过诗乃所说的巨大恐龙与蜈蚣型怪物……」

西莉卡也点了一下头，然后又像发现什么般用手指着地图。

「但是从巴辛族村庄走到这里来时，一开始是沙漠般的荒野然后渐渐变成草原，渡过这条大河就又变成了森林对吧。诗乃小姐表示所在的区域几乎都是沙漠，所以很难找到水源，差点就要渴死了。因此我认为就方向来说，很可能是在森林的另一侧。」

「唔嗯唔嗯……」

我、莉法以及爱丽丝同时点头。西莉卡的意见虽然具说服力，但就算方向正确，不知道大概的距离的话也无法轻易去寻找。除了HP之外，还存在SP、TP的这款游戏，要长距离移动时必须先准备充分的水与食材。

想到这里的瞬间，就稍微意识到空腹与口渴。怎么说在登出时数值也是维持不变的状态，目前SP条只减少两成、TP条则是三成，但一旦开始作业就会不断减少了吧。附近就有河川，食材的话应该还残留了一些熊肉，不过还是得尽快完成安定供给的机制才行。

「……得开拓森林来开垦田地……不知道能不能耕田就是了……」

我一这么呢喃，结衣就一脸认真地回答：

「也把它加进待办事项里面喽！」

「谢……谢啦……顺便问一下，现在清单大概有几项？」

「我没有列出优先顺位，目前有『建筑防壁』『增建圆木屋』『制作所有人的武器防具』『提升等级』『增强驯服的怪物』『挖井』『开垦田地』『与诗乃小姐会合』以及『到达极光指示之地』！」

「………………」

所有人默默地面面相觑。最后一项是最终目的，所以可以先不用理会，但除此之外都是优先事项。

「……先从建筑防壁开始吧。」

重新打起精神的我这么说道，莉兹贝特也轻轻点了一下头。

「正有此打算，所以捡来许多石头喽。我试着制作一下墙壁吧。」

「嗯，拜托你了。」

对着我竖起大拇指的莉兹，先是关上开着的地图，然后打开技能视窗。从初级木匠技能可以制作的道具一览表里选择「堆石墙」后，就出现淡紫色通透的残像物体。莉兹以生疏的手势滑动残像，在广场与森林的境界处停了下来。

「盖在这里可以吗？」

「等一下。」

我走到通透的石墙旁边，慎重地评定位置与角度。

「再往内十五公分……然后稍微往右转。」

「这……这样？」

莉兹微微动着手指，残像也跟着一点一点移动。来到我中意的位置那一瞬间，我便大叫：

「这里！」

莉兹握起右手的瞬间，就有数颗灰色石头从空中落下，在完全与残像重叠的位置实体化。出现的墙壁高度与宽度约一．五公尺，厚度则是三十公分左右。大小石头毫无缝隙地堆叠起来，没有想像中那么粗糙。为了慎重起见稍微推了一下，也没有摇晃或者石头掉落的现象。

「这样应该可以防御一些怪物吧。」

我一边拍着石墙一边这么说着，结果爱丽丝就以担心的表情回应：

「是没错……但是应该无法挡下尖刺洞熊的突进，如果是玩家的话也会翻墙进来吧。」

「只能祈祷那只熊最近不要到附近来了。至于玩家的对策……」

我把脸朝向莉兹贝特继续说道：

「莉兹，这一面墙壁要用多少石头？」

「嗯……在河岸边能捡到最多的『灰崩岩』三十个，还有五个『粗糙的灰色黏土』。」

「还剩下多少灰崩岩跟黏土？」

「石头一百二十多个，黏土二十个。」

莉兹刚回答完，旁边的西莉卡也举起右手。

「我也捡回一百颗石头跟十五个黏土！」

「谢啦，西莉卡。这么说来，光靠你们两个人的存量就能制造出七面墙了。莉兹，试试看在这面墙上再叠上一面墙。」

「好～」

点头的莉兹贝特再次操作视窗。移动出现的残像壁到最初的墙壁附近后贴齐机能发生作用，首先连结到右侧。准备从该处往左错开时，残像就轻轻堆叠到上方。

「啊，看来没问题。」

「好，拜托你了。」

再次传出「喀咚咚嗯！」的沉重声响，新的墙壁降下来与最初的墙壁重叠。这样高就有三公尺。虽然无法说是完全的防御，但除了身体特别灵巧的玩家之外，应该都会犹豫要不要翻墙吧。

当然，现状与其说是墙壁，倒不如说是薄薄的柱子。直径十五公尺的广场圆周大约四十七公尺。要以宽一．五公尺的墙壁围住全体的话需要三十二面，再往上堆高的话需要加倍也就是六十四面墙壁。当我想着……不想计算要几块灰崩岩时。

圆木屋的门迅速被打开来，穿着白色洋装的亚丝娜从里面冲出。

「各位抱歉！我来迟了！」

「亚丝娜，你来得正好！六十四乘以三十是？」

我立刻用手指着她，亚丝娜愣了一下子后就回答「一千九百二十」。然后逐渐露出纳闷的表情并且加了一句：

「……为什么要这么问？」

「是要用墙壁围住整个广场需要的石头数量喔。」

我把朝向亚丝娜的右手食指移动到屹立在高炉附近的灰色石墙。

「噢……」

亚丝娜像是可以接受般点了点头……

「哥哥，刚才的算式没办法心算也太糟糕了吧？」

莉法很担心般这么说道。

所有人一起移动到河岸边，靠着快下山的夕阳尽可能捡拾灰崩岩与黏土然后回到广场，由习得初级木匠技能的我与莉兹制作墙壁……重复这样的工程一个小时。好不容易用高三公尺的墙壁围住整个广场时，太阳已经完全下山了。

实际上因为南北各设置了一个木门，所以需要的石头数量比亚丝娜计算的要少了一些，但这依然是相当累人的作业。因此墙壁完成时的达成感特别强烈，包含爱丽丝在内的所有人都击掌了好几次。

「有墙壁后果然安心多了！」

喧闹一阵子后西莉卡就做出这样的评论，而我也深深点了点头。

「真的是这样。古代希腊人之类的在城墙完成时可能也是这种心情吧。」

「跟古雅典以及科林斯比起来这里小多了。」

由于亚丝娜加了一句这样的吐嘈，我便咧嘴笑着回答：

「不能这么说，今后要不断地扩张，总有一天要发展成跟古雅典，不对，是跟圣托利亚一样的大都市给你看。」

下一个瞬间，这次换成被爱丽丝吐嘈。

「哦，很敢说嘛。我很期待喔。」

「交……交给我吧。」

我拍了一下自己的胸膛，然后迅速转换话题。

「那么，这样就解决一件待办事项了吧。接下来是……」

「我啦，我有话要说！」

举起右手挥舞的是莉法。

「我也想要剑跟铠甲！」

「……嗯，我想也是啦……」

当前只有我自己一个人全身穿着铁制铠甲，所以无法直接反驳这个提议。莉兹与西莉卡装备着从巴辛族那里获得的皮铠与金属武器，结衣与爱丽丝虽然没有防具但是都有铁剑，只有莉法跟亚丝娜还穿着天根草纤维制的洋装，然后装备着石刀与石斧。

幸好有从ALO继承打铁技能的莉兹在，技术方面绝对没问题。问题是应该需要相当多分量的铁矿石。为了修复圆木屋，昨天从尖刺洞熊的巢穴里入手的矿石与那群PK身上掉落的铁装备几乎都用光了。要获得新的铁矿石就得再次进入洞熊的巢穴，但是洞穴的主人应该早就重新涌出了吧。昨天是用从圆木屋屋顶掉下大量圆木这样特殊方法才干掉它，我不认为还能再用一次同样的方法。

「结衣啊，巴辛族有没有提到在哪里获得铁矿石？」

我对七个人中唯一能理解NPC谜之语言的结衣这么问道，但少女只是轻轻摇摇头。

「抱歉，爸爸。我没有获得这个情报……」

「不需要道歉喔，请他们告知能取得珪砂和亚麻的地点时，是我忘了顺便也询问铁矿石的所在地。没关系，会有办法的。」

「是啊，结衣。桐人会努力想办法解决的。」

亚丝娜抱起结衣并对她露出温柔的笑容。结衣虽然轻点了一下头，但还是以担心的表情再次看向我。

「……具体来说要怎么做呢，爸爸？」

「当然是以正攻法来打倒尖刺洞熊啊……不对，等等喔。」

我把身体往右转，看向脑袋上坐着毕娜的西莉卡。

「不要打倒，如果可以驯服它是最好了。我想这样大概就会停止涌出了。」

「咦咦咦？驯服熊吗？」

面对吓得后仰的西莉卡，我咧嘴笑着表示：

「就连没有驯兽技能的亚丝娜都能把那边的鸭子恐龙变成宠物了。从ALO继承驯兽技能的西莉卡，应该很轻松就能把熊……」

「桐人哥，很遗憾的是我继承的是短剑技能。」

「咦，是这样吗？你短剑技能的熟练度比较高吗？」

老实地露出惊讶的模样后，西莉卡就像闹别扭般噘起嘴来。

「桐人哥，要把驯兽技能的熟练度提升到1000是很困难的喔。就我所知，熟练度提升到极限的就只有猫妖族领主亚丽莎小姐而已。」

「那真是不好意思……这么说，目前是亚丝娜的驯兽技能比较高喽……」

把视线移过去后，亚丝娜先是眨了两三下眼睛，然后才不停地摇头。

「驯……驯服那只熊，我也办不到啦。」

听见这使用倒置法的言词，让我思考起该如何拢络……不对，应该是说服她。

「要……要勉强亚丝娜小姐的话，还是交给我吧！」

不知道是因为装备着巴辛族制的防具，还是身为驯兽师的尊严使然，西莉卡这时往前走一步并且做出这样的宣言。亚丝娜似乎还想说些什么，但西莉卡迅速伸出双手来阻止了她。

「不用担心，亚丝娜小姐。我虽然没有见过那只熊，但动物型怪物的话难易度应该比虫型和恶魔型还要低才对。我会努力提升驯兽技能的熟练度，一次就成功驯养它给大家看！」

──我觉得尖刺洞熊大概跟西莉卡想像的熊有很大的差异。

虽然感觉亚丝娜、莉法和爱丽丝也跟我有同样的想法，但是在她们开口说些什么前我就走到前面紧紧抓住西莉卡的肩膀。

「不愧是SAO里威名远播的偶像驯兽师西莉卡。听你这么说我就放心多了，那就拜托你喽！」

「嘿嘿嘿……我会加油的。」

虽然看见露出害羞笑容的西莉卡右斜后方的亚丝娜叹了口气，但是我又趁势继续表示：

「亚丝娜，麻烦你教西莉卡驯兽技能的取得方式。刚刚从河岸边回来时，森林里有狐狸般的怪物，我想可以用它当作练习。我、莉兹、爱丽丝以及莉法在TP条进入危险状态前先来挖井吧。」

「是可以啦……但这款游戏可以擅自挖掘地面吗？」

莉兹贝特的问题让我不由得一瞬间静止。

包含ALO在内的许多VRMMO，练功区都是设定为不可改变。因为允许玩家这么做的话设计地图就没有意义，而且摆明会有路上出现大洞这种恶质行为横行。

虽然这款Unital ring在许多方面都不算是普通的游戏，但实在不认为可以改变练功区……我记得昨天曾经思考过这一点。但是出乎意料的是，初级木匠技能的制作选单里面确实有──

「……看，有掘井的选项。」

我对莉兹贝特她们显示打开的视窗。手指着的地方正如我的记忆存在着「叠石小型水井」的文字列。

「应该像高炉那样，只要完成设置就能使用水井了吧？」

由于莉法如此表示，我忍不住就提出反驳。

「咦咦，这么简单可以吗？如果拥有材料就能一瞬间设置水井，那么TP条就没有意义了吧。」

「跟我说也没用啊。倒是现在试试看不就知道了。」

听她这么一说才想到确实是这样。于是我就确认制作水井需要的素材数量与种类。总共是石头三百颗、制材过的圆木二十根、黏土十个、铁钉五十根、铁炼一条。

「呜咿，素材完全不够。石头和圆木只要收集就可以了，但是铁就……」

「看来没那么简单呢。」

亚丝娜耸耸肩，然后瞄了高炉一眼。

「看来不论要做什么都得先确保铁矿的来源。西莉卡的驯兽应该还得花一段时间，我看还要跟尖刺洞熊战斗个一次才行吧？」

「嗯嗯～……如果这是普通游戏的话，就算承担全灭的风险也可以进行挑战……」

我刚发出沉吟声，爱丽丝等人也露出阴沉的表情。

Unital ring一旦死亡就再也无法登入。而且也不能回到ALO。被卷入事件的VRMMO世界，其伺服器内的游戏档案全都遭到覆盖，目前处于停止营运状态。有几款游戏似乎挑战回溯，但就算重新安装The seed系统程式也无法正常起动……亚鲁戈是这么说的。就连被称为逞强、荒唐、鲁莽三冠王的我，在这种状况下也不敢以赌博的心态挑战超强敌尖刺洞熊。

「铁矿……铁矿吗～～～～」

我双手抱胸并仰望着夜空。不论是SAO还是ALO，在最初的城市里都能买到大量的铁制武器与道具，所以一点都不觉得稀有。怪物身上也会掉下大量铁制道具，所以拿不动的就会直接丢弃，现在真的很想把过去丢掉的全部捡回来。

到附近的练功区拼命寻找的话，在洞熊的巢穴之外应该也能找到铁矿石才对。但是按照游戏的脉络来看，这边附近入手铁矿的难易度应该被设定为「能稳定打倒尖刺洞熊的等级」，因此可以判断光靠野外露出的铁矿是不足以稳定供给我们的需求。在没想办法解决那只熊之前，铁器文明不会真正来到这块土地。

「……去找诗乃吧。」

我一这么呢喃，不只是爱丽丝她们，就连在稍远处说着驯兽技能的亚丝娜、西莉卡以及结衣也看向这边。这时亚丝娜认真的声音打破了紧绷的寂静。

「我也想早点跟小诗诗会合……但不清楚她的所在地与方位。要怎么寻找呢？」

「如果是西莉卡她们遇见的巴辛族，或许知道和诗乃一起的鸟人。此外也想要铁矿石的情报，我看就先到巴辛族的村子去问问看吧。」

我依序看着伙伴们的脸并且决定方针。

「希望亚丝娜、西莉卡和爱丽丝留下来帮忙防守圆木屋。村子就由我和莉法、莉兹以及结衣前往……这样如何？」

「亚丝娜和西莉卡还有驯兽技能的事情要处理，所以能够理解。但为什么连我都要留下来？」

面对爱丽丝有些不满的提问，我老实地说出自己的心情。

「因为你帮忙保护这个家我才能觉得放心啊。」

「……听你这么说就没办法拒绝了。好吧……但下一次的远征我绝对要参加。」

坚决地如此宣告后，爱丽丝就转身走到亚丝娜、西莉卡旁边。亚丝娜用右手触碰爱丽丝的背部，同时以让人想起血盟骑士团副团长时代的清澈声音说道：

「我们会好好保护房子，桐人你们也要平安回来。就这么说定喽。」

「……嗯。」

我点完头，莉兹也回应「一定会把诗乃找回来！」，结衣跑到亚丝娜身边并紧紧抱住她。我看着她们的模样，然后为了实行以前的想法而打开道具栏。

我把事先从房屋仓库栏里移动过来的长剑「黑色鞭痕」实体化。这把继承自ALO的爱剑，需要的能力值实在太高了，即使升上等级13的现在也无法装备。我在它飘浮于视窗上的状态下，移动到莉兹贝特面前。

「莉兹……这是你精心帮我打造的剑，这么说真的很不好意思，不过可以把它熔掉吗？」

「咦咦？」

身为黑色鞭痕制造者的铁匠不停眨着双眼。

「这……这当然得由身为持有者的你来决定……但我无法保证在这个世界能打造出跟它同等级的剑喔。」

「我知道。但是我想大概要到等级40或者50才能装备上这个家伙。与其在那之前都把它放在道具栏里当仓管，倒不如现在拿来帮助大家。」

「……嗯，我知道了。」

莉兹贝特灿烂一笑后，右手就朝着视窗上的黑剑伸去。

「哎呀等一下！一碰就会掉到地面拿不起来喔。」

「啊，对喔。」

「等一下，我直接放到高炉里。」

我在打开视窗的情况下走到广场西侧，叫出高炉的操作视窗后，把黑色鞭痕丢进去。浮在空中的爱剑洒下光粒然后消失不见。在炉子的燃烧室设置柴火，然后由莉兹贝特接下去操作。

铁匠像是要悼念自己打造的剑一样一瞬间合起双手，然后才以打火石点燃柴火。立刻有红色火焰晃动，最后传出轰隆的声音开始炽烈燃烧。

昨天晚上设置铁矿石时几乎数十秒就开始熔化，但黑色鞭痕却持续承受火焰将近两分钟的时间。但最后还是从注入口流出白色闪亮铁水，累积在长方形的铸模内。盈满后就噗咻一声消失，然后再次开始累积。

由于只设置了一把单手剑，原本以为能够获得十个铸铁就很不错了，但是Unital ring里面高等级的装备经过分解后材料的个数似乎也会增加。铁水不断流出，当我放弃数制造出来的铸铁数量时才终于停止。

「……结束了。」

如此呢喃的莉兹贝特打开高炉的视窗。

「嗯，制成的素材有……『高级钢铸块』六十二个、『上等银铸块』十八个、『上等陨铁铸块』九个、『秘银铸块』六个、『黑龙钢铸块』两个。」

「呜哇……好像出现一堆稀有金属耶……」

我听着莉法带着敬畏的呢喃声，一瞬间想着……如果黑色鞭痕能够制造出这么多材料，要不要连另一把继承武器「断钢圣剑」也一起熔掉算了。但最后决定把大费周章才得到的传说级武器熔毁当成最后手段，于是就对莉兹搭话道：

「这些金属可以制造亚丝娜、爱丽丝和莉法的装备吗？」

「嗯……因为我的打铁技能熟练度也降成100了。可能没办法处理太高级的金属……」

以带着不安的声音如此回答的莉兹贝特，把所有铸块移动到自己的道具栏后坐到铁砧前的小椅子上。接着将「高级钢铸块」丢到铁砧的视窗里并打开制作选单。

「啊，好像刚好可以制作钢铁武器。那我先制作爱丽丝的剑喔。混种剑就可以了吧？」

「拜托你了，莉兹。」

「OK。」

对骑士竖起大拇指后，莉兹就握住打铁榔头。然后迅速敲打出现在铁砧上的银褐色铸块。

我听着「当当」的清澈金属声，一边祈祷新生的剑们也能够像消失的爱剑黑色鞭痕一样强韧。

** 第五章

──幸好潜行前什么都没吃。

诗乃看着眼前滋滋作响的肉块，同时心里这么想着。

半熟的肉排厚达八公分，直径则是有三十公分。在现实世界是连相扑选手都没办法吃完的尺寸。但是围坐在巨大桌子前的鸟人们正豪迈地用刀子切着同样尺寸的肉排并大口咀嚼着。

当然因为这里是虚拟世界，所以不论吃再多东西都不会进入真正的胃里面，但完全潜行技术神奇的地方是确实会发生饱足感，而且登出之后还会持续一阵子。对于原本食量就小而且没有特别喜欢吃肉的诗乃来说，这种尺寸的半熟肉排是相当大的考验。更重要的是它不是牛肉或者猪肉。

诗乃确认左右两边的鸟人都专注在肉排上后，迅速地击点了一下它。浮现的属性视窗显示【史提罗克法罗斯的尾巴肉排】。这片肉是来自诗乃用黑卡蒂Ⅱ射穿心脏打倒的恐龙。

昨夜没有饿死而是差点渴死之前才好不容易喝到水的诗乃，打倒史提罗克法罗斯后就在狂喜的鸟人们拥簇下来到他们的村庄。

虽然还是完全无法理解他们说的话，但简直像救世主般受到欢迎的诗乃被带领到村子中心部的一间漂亮房子里，于是得以在那个地方登出。今天傍晚，一回到家就喝了水直接潜行到游戏里，然后被半强迫地参加这场宴会……这就是事情的经过了。

有点，不对，应该说相当意外的是鸟人们的文明水准相当高。村子的每户人家都整齐地由红砖所盖成，几乎是正圆形的外围部也由坚固的石墙包围。铺设磁砖的道路连结位于中心部的一座大集会场，其周围甚至存在商店街。

现在想起来，鸟人们既然能运用毛瑟枪，那么具备同样等级的文明也不是什么不可思议的事情。这样的话，就算留下大部分的恐龙肉排，应该也不会被怪罪没有礼貌才对……当诗乃这么想的时候。

「NNNN？」

来到身边的儿童般鸟人一边在诗乃面前的杯子倒下像酒一样的红色液体一边说了些什么。似乎是对自己提问，但是依然无法理解内容。

「抱歉，我听不懂你在说什么。」

如此回答之后，小孩很疑惑般稍微打开黄色鸟喙。诗乃原本打算再次道歉，但是在她开口之前──

「那个孩子是在问你不吃肉排吗？」

从左边传来这样的声音，吓了一大跳的诗乃随即看向该处。

发言者是鸟喙两侧垂着长长灰色羽毛的老人般鸟人。

「听……听得懂我说的话吗？」

诗乃以沙哑的声音这么问道，结果老人就扬起了嘴角。

「是啊，老身年轻时曾经跟人族一起在大陆的各地冒险。对了……巨龙肉排不合你的胃口吗，人族的女孩啊？」

巨龙应该是包含史提罗克法罗斯在内的所有恐龙型怪物吧。

「啊，没有……我开动了。」

诗乃有所觉悟后就右手拿起刀子、左手拿起叉子。切下树桩般牛排边缘稍微烧焦的地方并且送进嘴里。

咬下烤得酥脆的表面后，出乎意料的弹力把牙齿推了回来。但一用力咬就轻松地把肉撕断，油脂的甜味在嘴里扩散开来。吃起来就像牛肋排加上了纤维感与野性口味。虽然没有淋酱，但辛香料发挥了作用，味道其实还不错。

「那个……你们的语言『好吃』该怎么说呢？」

对老人提问后得到「咻佛鲁」的回答。诗乃重新转向小孩子，重复一遍老人教她的单字。但小孩子依然歪着头。

「错了，是咻佛鲁。」

「啾佛鲁。」

「还差一点，咻佛鲁。」

「咻佛鲁！」

重复好几次之后，似乎终于传达自己的意思了，小孩子露出灿烂的笑容并且大叫「咻佛鲁！」，很开心般点了好几次头后就离开了。

下一个瞬间，眼前──

【获得欧鲁尼特语技能。熟练度上升为1。】

浮现写着这个讯息的视窗。诗乃眨了眨眼睛后，竖起耳朵听着大房间里此起彼落的交谈声。大部分跟之前一样听起来是奇妙的啼声，不过偶尔混杂着「这样南边的牧场就……」或者「再给我一杯红酒……」等等可以理解的片断字句。

放学后的会议里，结衣曾经这么说过。Unital ring世界的NPC所说的谜样语言，实际上是The seed规格JA语言套件──也就是日文，因为加上了层层滤波器才会听不懂。大概是获得欧鲁尼特语技能后有一部分滤波器得到解码，所以才能听得出是日文吧。继续提升技能熟练度的话，滤波器应该就会完全解除。

就算是这样，到底该如何提升熟练度呢？

吃了一口恐龙肉排，诗乃一边咀嚼一边在脑内再生获得技能前的对话。一把肉吞下去，她就再次转向老人。

「那个，欧鲁尼特语的小刀要怎么说？」

「嗯？叫作『菲吐』喔。」

「菲吐。」

「不对，是菲吐。」

「菲吐。」

「都说是『菲吐』了。」

「我就是说『菲吐』啊！」

诗乃忍不住粗暴地说道，结果眼前就浮现【欧鲁尼特语技能的熟练度上升为2】的讯息，刚才的小孩子跑过来对诗乃递上新的小刀。这样就能确定──要提升欧鲁尼特语的熟练度，似乎需要完美重现解码之前的单字。诗乃想着为什么需要如此麻烦的方式，再次对老人提问。

「……欧鲁尼特语的『谢谢』要怎么说？」

四十分钟后。

从宴会场回到住宿处的诗乃，直接往前倒到床铺上。

幸好鸟人也就是欧鲁尼特族不存在把没有吃完宴会食物的客人烤来吃的野蛮风俗。诗乃一边向老人学习语言一边拼命地把恐龙肉排送到虚拟的胃里，但吃完一半时满腹中枢就让她不得不放弃了。但就算是这样，她应该也吃了1公斤的肉。不要说游戏世界了，就连在现实世界，她都暂时不想吃肉了。

不过参加宴会相当有意义，欧鲁尼特语技能的熟练度已经提升到10，而且获得更加贵重的情报。转过身体变成仰躺后，诗乃打开环状选单击点地图图标。

打开的地图上只显示着起始位置的废墟城市，其东方的一大片荒野、打倒巨兽史提罗克法罗斯的岩山，以及从该处往北一阵子后的欧鲁尼特族村落。虽然自认为移动了相当大的范围，但是用两根手指缩小地图后明亮的部分就不断缩小，最后变成跟沙粒一样的大小。如果以世界地图等倍显示这种状态，诗乃拼死所穿越的距离根本就不到整个世界的一％。

但目前的问题不是到世界尽头的距离，而是现在位置距离桐人与亚丝娜他们有多远。

宴会尾声时，诗乃几乎问遍所有列席者知不知道巴辛族这个名字。教导她欧鲁尼特语，过去曾在整个世界旅行的老人回答「未曾听过」时虽然很沮丧，但唯一有一名列席者表示曾经听过，于是诗乃就驱使提升到熟练度10的欧鲁尼特语技能向那名鸟人询问详细的情报。

他本身也没有真正见过巴辛族，只是曾经从祖父那里听说过这个种族，但光是获得「巴辛族的村落在越过遥远东南方那片『基幽鲁平原』的前方」这个值千金的情报，一切辛苦就都不算什么了。由于亚丝娜他们的圆木屋掉落在巴辛族居住的土地附近，只要朝东南方前进──或许就能与他们会合。当然，如果世界地图的各处都存在巴辛族村落的话，就有可能朝完全错误的方向前进，但现在也只能相信一定能碰面然后迈开脚步了。

「……好吧！」

诗乃收起地图后，迅速从床铺上起身。

她已经跟欧鲁尼特族的人们说过今天晚上就要出发了。他们之所以会鲁莽地挑战强敌史提罗克法罗斯，听说是因为那只恐龙经常袭击村子南边的牧场，把贵重的「普西蛸」乱吃一通的缘故。

虽然不清楚普西蛸是什么样的家畜，但至今为止挑战多次却完全不是史提罗克法罗斯对手的鸟人们知道打倒巨兽的诗乃这么快就要离开村子都感到很遗憾。可以的话诗乃也很想暂时把这里当成据点来提升等级──因为住宿与食物都是免费──但是想尽快跟伙伴们会合的心情还是比较强烈。坠落的圆木屋对诗乃来说是相当喜爱的地点，而且感觉不是跟亚丝娜以及桐人他们一起挑战Unital ring世界之谜就没有意义了。

重新装备上猎户座SL2与鼬皮上衣，离开住宿处的诗乃先环视了一下周围。对面的宴会场已经没有灯光，圆形广场上也几乎看不到人影。时间才刚过十九点而已，欧鲁尼特族似乎没有夜游的文化……当诗乃这么想的瞬间，嘴里就呢喃了一声「糟糕」。原本想以仅有的一百耶鲁货币购买干粮与饮用水，但是并排在广场南侧的商店已经全都关上店门。不论ALO还是GGO，NPC商店一般都是二十四小时营业所以才会掉以轻心，但VRMMO的常识根本不适用于这个世界。

「……如此一来，也不保证这个村子能够使用耶鲁货币了吧……」

再次这么呢喃完的诗乃沮丧地垂下肩膀。由于才刚刚吃喝到肚子再也塞不进食物的地步，所以TP条与SP条都已完全回复，但是食物也就算了，实在不愿意再次犯下没有带水就到荒野行走的愚行。看来还是等到明天早上商店开门后再出发，不然就是在村子某处找到可以免费汲水的地方……当这么想着的诗乃呆立于现场时。

「诗乃小姐！」

突然被叫到名字的诗乃迅速往右看去。此时小跑步过来的是欧鲁尼特族的年轻人以及小孩子。一开始时觉得他们所有人的长相都一样，但现在已经可以从羽毛颜色、模样、双眼以及鸟喙的形状做出一定程度的辨识。

年轻人是在史提罗克法罗斯战时诗乃拯救的枪手。小孩子则是宴会时担任服务生的少女。在眼前停下脚步的年轻人，伏下两眼上的饰羽并且对诗乃问道：

「诗乃小姐，你要NNN了吗？」

欧鲁尼特语熟练度好不容易才提升到10，所以还有一部分听不懂，但可以推测他是在问自己是否要出发了，于是诗乃就点点头。

「嗯，我必须到巴辛族的村子去。」

年轻人似乎听懂诗乃的回答，只见他以担心的表情点头说道：

「这样啊……我没有NNN过巴辛族，但是要横越东南方的基幽鲁平原的话必须准备NN。诗乃小姐，请带着这个吧。」

年轻人说完后递出来的是发出乌亮光芒的毛瑟枪。诗乃不由得眨了眨眼睛，然后用力摇了摇头。

「不行，这是你重要的枪吧？」

「不是喔！」

这么回答的是身上长着淡茶色羽毛的少女。她往上看着年轻人以双手拿着的毛瑟枪并且继续说道：

「那把枪不是哥哥的，它是属于死去的祖父。爸爸也说没有NN的人了，所以就NN村子的恩人诗乃小姐。」

「正是如此。虽然是把老旧的枪了但品质可是NN。当然远远比不上诗乃小姐的枪，但用威力如此强大的枪来对付小型野兽与昆虫实在太浪费了吧？」

他说的一点都没错。黑卡蒂的.50BMG弹只剩下6发而已，没遇见重大的情况绝对不能乱用，猎户座的能源条也只剩下六成左右。两者今后获得补给的机率都很低。

「……那我就恭敬不如从命了。」

诗乃如此回答完，年轻人就很高兴般递出毛瑟枪。一接过来，可靠的重量就传递到手上。年轻人接着又把挂在肩上的皮革包包拿给诗乃。

「这是子弹和炸药。如果用光的话，子弹可以用铁NN，炸药只要用炸裂黄金的分泌液与碳粉混在一起，干燥之后就能制作了。」

「炸……炸裂黄金？」

看见诗乃皱起眉头，年轻人的妹妹就以双手做出一个大大的圆形给她看。

「在NNNN仙人掌的根部喔！不小心踩到的话会爆炸然后受重伤，你要小心哟！」

「嗯……嗯，我会小心。」

很遗憾的是无法听出仙人掌的专有名词，不过诗乃原本就不打算靠近任何仙人掌。

诗乃背起枪，把弹药包挂在肩上，这次换成少女从脚边提起一个大布袋。

「这是水和烤硬的面包！是我和妈妈以及奶奶一起做的！然后还放了毛毯，NN来袭的时候记得要用喔！」

这个时候还客气的话反而显得没礼貌吧。虽然在意「NN来袭的时候」内容究竟是什么，但也没办法反问，所以只能慎重地道谢并且接过布袋。结果少女就露出灿烂的笑容又加了一句：

「硬面包虽然不怎么好吃，但可以保存很久！NNN的时候用炭火烤，然后涂上奶油就会变得NN一点喔！」

「……嗯，我会试试看。真的很谢谢你。」

弯下腰并再次向少女道谢后，诗乃就用自己的双手包裹住少女的手。

「嗳，可以把名字告诉我吗？」

「可以哟！我叫费琪。哥哥叫作乌费鲁姆喔！」

「费琪……还有乌费鲁姆。我将来一定会回到这个村子，到时候我会带很多礼物回来。」

「嗯！」

诗乃凝视着用力点头的费琪，同时在内心决定一定得实现这个诺言。

晚上七点三十分。离开欧鲁尼特族村庄的诗乃首先叫出地图视窗，寻找往东南方明显的目标。幸好夜空中的巨大月亮正发出蓝白色光芒，加上夜视技能的辅助后至少可以分辨出地形。凝视东南方后，注意到一座外形宛如闸门般的岩山存在于远方。

「……好！」

发出喊声来鼓舞自己后，诗乃的右脚就朝着干燥的大地踏去。虽然不知道那个叫作基幽鲁平原的地方直径有多少公里，但是今天晚上一定要突破该处抵达巴辛族的村庄。藉由打倒练功区魔王史提罗克法罗斯，等级一口气上升到了16，另外还有背上的毛瑟枪与左腰的猎户座SL2这两种武器。虽然再也不想跟大型恐龙战斗，但不认为自己会败给蜈蚣或者蝎子等对手了。HP也上升了，能力值也……想到这里，诗乃才又想起这个Unital ring不存在STR与AGI等能力值。

相对地，除了技能之外还设定了各式各样的能力。藉由升级累积了15点能力点数，因此想单独突破危险的练功区的话，就不能囤积着点数不用。

「……我很不擅长选这种东西啊……」

这么呢喃完，诗乃就把地图画面切换成能力取得画面。放学后的会议里，桐人说过一旦取得能力可能就没办法重来了。关于这一点，GGO虽然也是一样，但Unital ring的能力选项实在太多了。

还是应该先回欧鲁尼特族的村子，在安全地点登出然后用网路搜寻能力的情报比较好吗？不行……Unital ring事件发生到现在也不过二十四小时又多一点，不能完全相信目前发表在网路上的情报。应该自己思考并且决定要让自己如何成长──这是被死枪<Death gun>杀死的GGO玩家「ZXED」所留下来的教训。

「……总之先用10点吧。」

如此呢喃之后，诗乃右手食指就在四个初期的能力名称上方徘徊着。

** 第六章

「……我很不擅长选这种东西啊……」

我瞪着能力取得画面并且这么呢喃，在旁边喝着水的莉兹贝特以傻眼的口气表示：

「凭感觉就可以了吧。我和莉法都很干脆就点下去喽。」

「就是没办法凭感觉啊……」

我这么嘟囔着，同时紧盯着视窗看。

中央的四个图标排成十字形。从上面依照顺时钟方向来看分别是「刚力」、「顽强」、「才智」、「俊敏」。然后这些图标又分别延伸出两条线来连结新的图标。「刚力」连结到「碎骨」与「坚守」。「顽强」是「忍耐」与「抗毒」。「才智」延伸出「集中」与「博学」。「俊敏」则是「远奔」与「巧手」。

击点图标就会显示说明文。根据说明文的内容，「刚力」是增加近身中型大型武器伤害与装备负重量、搬运负重量。同样的，「顽强」是增加HP值、TP值、SP值以及状态异常抗性。「才智」是增加MP值与魔法威力。「俊敏」则是增加远距离武器伤害、近身小型武器伤害以及跳跃距离。

也就是说攻击手是从刚力开始发展能力树，坦克是顽强能力树，魔法师是才智能力树，斥侯则是俊敏能力树，以中型近身武器的单手剑为主要武装的我，应该什么都不用考虑就选择刚力能力即可，但事情不是这么简单。要在身为生存RPG的Unital ring存活下来，最重要的就是HP、SP以及TP值。今后可能会有一两次，不对，可能是十次左右在快要饿死或渴死之前浮现「早知道就把『顽强』点满……！」的念头。

我叹了一口气，然后对同伴们问道：

「那么……你们凭感觉点了什么能力？」

结果莉兹贝特回答「我是『顽强』」，莉法回答「我是『刚力』～」，坐在我旁边的结衣则是笑着回答「我是『才智』！」。我眨了眨眼后就跟心爱的女儿确认。

「点了『才智』……结衣是想成为魔法师吗？」

「是啊！我要以妈妈那种能揍人的魔法师为目标！」

「这……这样啊。很可靠嘛。」

在ALO里以狂暴补师之名令人畏惧的亚丝娜，其战斗模式之所以能成立，是因为她具备强大的防御／回避技巧，但认为不能破坏小孩子梦想的我克制自己，只是摸了摸结衣娇小的头部。不是说绝对不可能，而且不论她要选择什么能力，我只要在旁边好好地守护她就可以了。

为了能够保护女儿，是不是应该选择坦克的能力呢……我再次陷入举棋不定的困境，只能抬头仰望天空。离开圆木屋时西方的天空还留有夕阳的残照，现在已经完全消失，漆黑的云不断流过朦胧的星空。

「嗯嗯～如果也可以知道衍生能力的内容就好了……」

由于只有现在可取得能力才能读取说明文，所以我才会发出这样的牢骚，结果在正面啃着小小树果的莉法就傻眼地说：

「那你问我们不就得了。」

「咦……啊，对……对喔……」

她们三个人都取得最初的能力了，所以可以看见衍生能力的说明文。为了掩饰尴尬而干咳了几声后，我才依序看向三个人。

「那么要麻烦三位指点一二了。」

「真拿你没办法……」

耸了耸肩的莉兹迅速打开环状选单。

「嗯，『顽强』的衍生能力呢，『忍耐』是强化格挡时的伤害减少效果，『抗毒』正如同名字一样是强化减少毒性伤害的效果。」

「唔嗯唔嗯。」

接着换莉法凝视视窗。

「『刚力』的衍生能力，『碎骨』是增加格挡时的贯穿伤害，『坚守』是强化格挡时回弹减少效果。」

「唔嗯……？」

接着结衣则是在完全没有看视窗的情况下进行解说。

「至于才智的衍生能力嘛，『集中』是增加MP条回复速度，『博学』是加快语言技能的熟练度上升。」

「唔嗯～～～～」

语言技能应该是能够跟NPC对话的技能，不过只要结衣在的话就还不需要。由于实在没有打算成为魔法师，所以「才智」能力树可以从候补名单内移除，但即使知道「刚力」与「顽强」的衍生能力内容后还是很烦恼。

「嗯……感觉『坚守』与『忍耐』的性能很相似啊。减少回弹与减少伤害为什么是不同的能力树呢……？」

「『坚守』大概不是盾牌而是以武器格挡为主吧？阻挡攻击之后身体没有失去平衡的话，就能比较快反击啊。」

莉法的说明让我点头想着「原来如此」。

「『刚力』能力树也不完全偏向攻击吗……那么，我果然还是点这边的能力吧……」

「不能一次选两个系统吗？」

莉兹贝特对我这么问道，我则是再次发出沉吟声。

「嗯～也不是说不行，但是像这种的通常都是钻研单一系统最后才会比较强喔。」

「那桐人你就完全强化攻击就好啊。这才最符合你的个性。」

莉兹的话让莉法咧嘴发笑，结衣则是笑眯眯地点头。不论是在SAO还是ALO，我都不是纯正的攻击手才对啊……心里虽然这么想，但她们三个人的意见似乎相同，我想亚丝娜、西莉卡和爱丽丝如果在这里的话也不会有异议吧。

「……我知道了，不过辅助就要拜托你们喽。」

「好好好，我会守住你的背后。」

我一边听着莉兹的回答，一边再次触碰「刚力」图标，然后按下说明视窗最下方的「取得」键。按下将消费1点能力点数的确认对话框的Yes键，视窗就随着带有爽快感的音效发出光芒，原本是黑白的「刚力」图标变成红色。

这样就能够取得「碎骨」与「坚守」两种能力了，但是它们必须得消费2点能力点数。由于每个能力都有十个等级，这时是要先把「刚力」提升到第10级，还是先取得「碎骨」就是值得思考的地方了。虽然能力点数还剩下11点，但是把它们全部用光也让人感到犹豫。

犹豫了一阵子后，我决定先取得「碎骨」能力。于是前方又出现两个衍生能力。

其中之一是「乱击」，效果是连续攻击时增加第二击开始的伤害值。另一个是「远击」，效果是增加范围攻击的距离。虽然早就料到，不过想取得两个能力都必须付出3点。也就是说，想把「刚力」「碎骨」「乱击」全都提升到等级10的话，就必须投入60点能力点数才行。而且能力树应该还会继续延伸。

「真是一条漫长的道路……」

我忍不住这么呢喃，同时把「刚力」提升到等级5。这样就消费了7点，目前还剩下5点。回到能力值画面后，「刚力」的效果似乎立刻显现，装备负重量表与搬运负重量表的使用率都降低了许多。由于这款游戏必须携带大量的水与食物、素材，所以这种能力虽然不起眼，但是相当有用。

「……好，我取得能力喽。」

如此宣言并关上视窗后，莉兹就以轻松的口气对着我问：

「还剩下几点？」

「5点吧？」

「看，果然剩下5点以上！打赌是我赢了！」

「……啥？」

在哑然的我面前，莉兹朝莉法伸出右手。莉法则在那只手掌上投下大量树果。看来她们是打赌我会剩下多少点数。

「真是的！哥哥！留下那么多要干什么，是男人就要一口气全用光啊！」

当我遭到妹妹不讲理的斥骂时，结衣就像要安慰我一样摸了摸我的头。

我们用完餐后，就从成为即席安全地带的大岩石上来到地面，然后再次往西南方向前进。就算没有照明，单靠星光还是能看见自己的脚边。

我们早已穿越森林，周围是一大片干燥的草原。或许因为是夜晚吧，出现的怪物主要是以鬣狗与蝙蝠等夜行动物为主，虽然不至于能轻松获胜，但也没有吃到什么苦头。当然这是因为有莉兹帮忙制造的铁制武器与防具，如果还是拿着石头小刀与草衣的话，可能根本无法离开森林吧。

饮用水的话已经用亚丝娜帮忙制造的素烧水壶在河川里装满了水，但食物就只带了一点紧急时使用的熊肉干，基本上必须在途中自行觅食。鬣狗的肉即使烤过了也无法入口，但经常可见的矮树上长着胡桃般的树果，虽然要把壳打破有点辛苦，但它的味道倒还算不错。出发后经过了两个小时，目前TP条与SP条都还维持在八成左右。

「莉兹，还要多久才抵达巴辛族的村子？」

依然叫出地图视窗的莉兹走在前方，我对她这么问完后，铁匠没有回头就直接回答：

「好不容易才走完三分之一哟。前面有一个两棵超级大树并排在一起的地方，那里就是中间点了吧？」

「你说大树，是像阿尔普海姆的世界树那么大吗？」

听见莉法的问题后，莉兹就一边苦笑一边摇头。

「当然没有那么大了。昨天看到时已是深夜，所以没能看得很清楚，不过大概是一百公尺左右吧？」

「话说回来……巴辛族他们在通过可以看到那两棵大树的山丘时，曾经停下脚步来祈祷对吧。」

这时插话的是和我牵手走路的结衣。莉兹贝特也点头表示「啊，没错没错！」。

「……向巨树祈祷吗……」

这么呢喃的瞬间，就感觉记忆深处受到连续刺激，但是连自己都不清楚是联想到什么。原本想开口要结衣搜寻VRMMO相关的资料库，但立刻就打消念头。现在的结衣不是导航妖精，跟我一样被赋予了玩家帐号。而且她似乎对这一点感到很高兴。可以的话，希望尽量不把她当成便利的AI。

于是我本来打算询问结衣她们是否一起祈祷了来取代刚才的问题，但从北方吹来的湿冷风让我反射性缩起脖子。

「风景像是热带草原，夜晚却这么冷吗……结衣，你会不会冷？」

「嗯，我不要紧。因为莉兹小姐帮忙制作了铠甲。」

正如她所说的，从昨天再次见面时就一直只穿一件白色洋装的结衣，现在胸前装备着薄薄的胸甲，双手双脚上也装备着同样外观的手套以及靴子。铠甲下面依然是洋装，而这样的打扮看起来并不保暖，不过莉兹贝特的打铁技能熟练度有100──虽然下降了但现状已经算很高了──说不定打造的铠甲还附加了防寒效果。

而莉兹贝特本人则继续使用从巴辛族那里获得的皮甲与单手用锤矛，熔解黑色鞭痕所制成的铸块只做了小型圆盾给自己。另一方面，莉法则跟我一样获得了四件一组的金属铠甲与单手／双手兼用的长刀，跟只有一把石头小刀石比起来可以说有天壤之别，已经变身成重装战士了。但是走在我前面的莉法，一被北风吹到就全身缩起来叫了一声「好冷！」。

拖着金色马尾转过身子，然后灵巧地面对着我往后走并且说道：

「桐人啊，不能用鬣狗的毛皮做披风之类的吗？」

「别强人所难了，我又没有裁缝技能。」

「那就用跑的吧！也可以缩短时间！」

「咦咦……你在社团是经常跑步没错，但我又没参加社团……」

「我说啊，虚拟世界跟有没有参加社团无关吧！」

面对莉法的指谪，发现确实如此的我还是干咳了一声来把事情带过。

「而……而且跑步的话会平白让TP与SP减少……现在又看不清楚地面，这样很危险……」

「爸爸，我有火把喔！」

突然这么大叫的结衣，打开道具栏后拿出一根棒状物。仔细一看之下，是在树枝前端卷上枯草所做成的物品。在圆木屋使用的照明是简单的枯枝，所以算是进化了一级。

「这是结衣做的吗？」

「是啊，但想出制造方式的是莉兹小姐。」

「哦～不愧是工匠职。」

「称赞我也没有奖品喔。」

边走边看向这边的莉兹贝特，稍微隔了一阵子才继续说：

「但是，还是做好奔跑的准备会比较好。昨天巴辛族的人曾经说过。这里……好像是基幽鲁平原吧？偶尔会吹起冰风暴，那时候如果不裹着毛皮，或是到附近的洞窟避难就会冻死。」

「啥！你为什么不早点说呢？」

「因为是好几年才会发生一次啊。」

「我说啊，游戏世界的话这种情况都是以一天一次的频率……」

当我话说到这里时，身边的结衣就发出不安的声音。

「对不起，爸爸。我也听说这件事了，但是没有把它分类为重要情报。」

「没……没有啦，结衣你没有错喔。说起来热带草原怎么可能会吹冰风暴呢。」

「喂！跟我的对应也差太多了吧！」

正当莉兹贝特鼓起脸颊的时候。

北方再次有强风袭来，让我们四个人同时缩起上半身。感觉似乎比刚才还要冰冷，而且还带有些许水气。仰望天空就发现漆黑的碎片云以猛烈的速度从北往南流动。

「……我有种不祥的预感。」

我对莉法的话回应了一句「赞成」，然后低头看向结衣。

「结衣，让我点燃那根火把吧。」

「了解了。」

严肃地点点头后，结衣就把卷着枯草的前端朝向我。我从腰部的道具袋里取出打火石并且用力碰撞。现实世界的打火石，不和名为火镰的铁片互相敲击的话就不会出现火花，但在这个世界里，即使两边都是石头也可以使用。就算没有取得才智能力树，总有一天一定要学会火属性魔法……这么想的我拼命击打后，在第七下终于成功点火让枯草开始燃烧起红红的火焰。

把打火石放回袋子里，然后高高举起结衣交给我的火把。由于风势很强，火焰也跟着剧烈摇晃，但似乎不会轻易熄灭。

我迅速环视周围，寻找看起来有洞窟的地方，很遗憾的是因为光量不足而无法看到远方。但还是能看见东边有类似岩山的细长剪影，西方则是平缓的山丘棱线，于是开始思考该往哪一边走。

虽然还不能确定真的是冰风暴要袭来，但等真的发生才要找避难所就太迟了。要有洞窟的话岩山的机率应该比山丘还要大。但是像塔一样的岩山就算有洞窟也可能不够深……这时在犹豫不决的我右侧──

结衣突然发出尖锐的叫声。

「爸爸，有什么从北方过来了！」

「什么……」

当我急忙将火把朝向顺风处时，一道巨大的影子同时也在光线中无声地冲进来。

在仅仅五公尺前方停下来的影子，压低了身体发出「咕噜噜……」的低吼。那不是至今为止战斗过好几次的鬣狗。包裹在黑色毛皮底下的胴体虽然纤细，但是远比鬣狗还要大，前脚也强壮许多。它不是犬科而是猫科……以圆形耳朵来看应该是豹类。

「嘎噜哦！」

发出极凶猛声音的黑豹以发出淡淡蓝光的双眼瞪着我们四个人。虽然浮现「竟然在这种时候！」的念头，但它似乎不是能够逃走的对手，而且明显对我们有敌意。没办法的我只能把火把移到左手，然后右手握住剑柄叫道：

「要战斗喽！」

莉法同时拔剑并往前走出一步。我对从腰带扣环解下锤矛的莉兹呢喃「结衣拜托你了」，就听见「包在我身上」的可靠回答。

看见我的长剑与莉法的长刀之后，黑豹就露出锐利的牙齿。虽然没有剑齿虎那么夸张，但是比现实的豹牙长了三倍。毛皮是比夜色更浓的漆黑，从脖子到背后都带着泛蓝光泽。

黑豹把身体压得更低，开始进入跳跃姿势。攻击的目标是我。决定以剑技迎击的我也把剑举到右肩。

突然间，巨大咆哮声刺进耳里。来源不是黑豹。是风声──

一阵猛烈到之前的风都只是小儿科般的强风袭来，我只得踏稳双脚加以抵抗。一直撑到刚才的火把终于被吹熄，视界陷入一片黑暗当中。坚硬的颗粒不断打在外露的脸和手上。这是冰……冰雹。

虽然想着「豹和雹一起来吗！」但是没有机会说出口。伏在地面的豹用力跳了起来。我反射性要发动剑技「垂直斩」，但是在跨出脚步前就停止攻击并转过身子。

黑豹以惊人的跳跃力一次跳过我们四个人并且在后方着地。它再也不把我们当成目标，直接朝南方跑去。

「嗳……它是不是在逃避冰风暴啊……」

我跟莉兹有完全一样的想法。推测没有错的话，混杂着冰粒的阵风是连怪物都得避难的冰风暴即将袭来的前兆，而那只黑豹应该知道可以避难的地方。

「……要追上去喽！」

一叫完，我就把剑收回剑鞘里，然后用右手握住结衣的手开始跑起来。莉兹贝特与莉法也从后面跟上来。黑豹的剪影融化在黑暗中，再被拉开数公尺恐怕就会跟丢。

由于火把熄灭了，所以无法确认脚边是否安全。四个人里要是有谁踢到坑洞或者石头而绊倒，这场追踪就要结束了。我一边祈祷真正的幸运能够降临一边拼命跑着。原本想把结衣抱起来，但既然同样是玩家，那么敏捷力就不会有太大的差距，她没有落后而是确实地跟了上来。

追着轻盈奔驰的黑豹两分钟后。前方出现一座小山丘。黑豹朝着山丘底部用力跳去后，直接就像被吸进去般消失无踪。迟了一会儿后我们也抵达该处，发现底部有一个高一公尺左右的洞穴正张开黑漆漆的大嘴。

停下脚步的瞬间，从后方降下的冰雹就击中我的铠甲发出当当的声响。虽然现在的直径不到一公分，但这场冰雹不可能这样就结束。气温应该也骤降了许多吧，呼出的气息已经变成白色。

看了一下HP条，发现已经开始慢慢减少。不必思考也能理解在HP条右侧闪烁着的冰晶模样异常状态图标是什么意思。

「爸爸，我们到里面去吧！」

我对结衣紧绷的声音点点头。洞穴一直延续到深处，这时我也只能祈祷黑豹到更里面的地方去了。

放开结衣的手，为了慎重起见拔出剑来靠近入口。即使往里面窥看也因为一片漆黑而看不到任何东西。就算点亮火把，在这样的强风下也撑不到一秒就会被吹熄。我下定决心，往前弯下身体后进入洞内。

洞穴是呈平缓的下坡，越往里面前进天花板也变得越高。地上的山丘虽然不高，但洞穴的本体似乎在地面下整个扩展开来。稍微放下心来的我慎重地往前进。

往下十公尺左右地面就不再倾斜，我便停下了脚步。撑起前屈的身体，即使将右手的剑举向正上方也碰不到天花板。看来我们来到相当宽敞的空间了。而且也感觉不到黑豹的气息。

确认HP条后，HP已经停止减少，冷气图标也消失了。呼一声吐出一口气，接着看向后方。洞穴里是一片黑暗，视界几乎等于零。

「大家都在吗？」

如此呢喃后，就听到「是的，爸爸」「我在喔」「在哟～」的回答。我为了先再次点燃左手的火把而准备把剑放回去。但就在这个时候。

「啊，那个……」

莉法发出沙哑的声音，我迅速地反转身体。

依然什么都看不见。当我拼命瞪大眼睛，就出现【获得暗视技能。熟练度上升为1】的讯息，黑暗则稍微变淡了一些。下一刻，我也注意到那个了。

洞穴深处浮着两道蓝光。想着到底是什么而继续凝视后，光芒一瞬间消失然后再次亮起。简直就像在眨眼……等等，不是好像那真的是眨眼。那是先进入洞穴的黑豹的眼睛。

黑豹似乎察觉我们注意到它了……

「咕噜噜噜……」

于是发出这样的低吼。蓝色双眸轻轻浮动。原本躺着的豹似乎站起来了。黑暗中的视力对方应该比我们强上数倍，在这样的状况下开始战斗的话我们根本没有胜机。

「结衣，帮忙把火把点着。」

一这么呢喃完，我就把左手的火把往后伸去。

「好的。」

这么回答的结衣接过火把。虽然准备继续把打火石交给她，但是在这之前就听见奇妙的声音。

「锵、锵」的尖锐摩擦声。我不认为黑豹能发出这样的声音。一边警戒前方一边迅速回头，就看到洞穴入口方向有发出白光的极小粒子降下。

站在最后面的莉兹贝特一碰到粒子就「哈啾！」一声打了个喷嚏，接着莉法大叫「好冷！」，结衣发出「哈呜……」的声音，最后我则是剧烈地发起抖来。那不只是用冷所能形容。冷气图标再次点亮，HP开始以明显的速度减少。这个地方无法阻断从入口涌入的冷气。竖起耳朵就能听见类似悲鸣的细微寒风声。我实在不愿意想像外面变成了什么模样。

「哥哥，得到更里面去才行！」

莉法发抖的声音让我回叫着「我知道但豹挡在前面！」。占据洞穴深处的黑豹虽然没有发动攻击，但还是一样持续发出低吼。可以想像得到只要稍微靠近它就会扑过来。

HP条已经减少超过一成。按照这个速度来看，应该不到三分钟就会归零。即使知道不利也只能跟黑豹战斗了吗……我咬紧嘴唇后，发现在那之前还有一件事可以尝试。

我静静地放下长剑，把手伸进道具袋内，然后拿出薄板状的道具。那是亚丝娜帮忙制作的熊肉干。虽然是贵重的干粮，但在这里冻死或是战死的话就再也没有机会品尝了。

「来，很好吃哟～来吃大餐～」

我对着发出蓝光的眼睛这么呼唤，然后静静丢出肉干。豹的视线移向发出细微声响掉落到地面的肉干。然后……再次眨了眨眼睛。

蓝色双眸无声地朝向肉干靠近。感觉它正在闻肉干的气味。经过紧张的几秒钟后，可以听见咬下的声音。黑豹撕裂了肉干。下一个瞬间，黑暗中出现发光的环。简直就像车辆时速表的环，从左下方开始有三成左右变成红色，前端正不停地上下变动。是亚丝娜在驯服阿蜥时表示看到的驯兽计量表。

我从袋子里拿出新的，同时也是最后一块肉干并且丢出。黑豹立刻咬下，计量表又上升了一成左右。

「大家把肉干给我。」

我把右手往后伸，结衣就立刻把肉干放到我手上。估算黑豹吃完的时机，丢出第三片肉干。计量表继续上升，终于达到五成。最初的一片三成，接着一片能够上升一成的话，结衣应该还有一片，莉兹和莉法应该各有两片，所以应该还足够才对。

相信自己的计算，持续对黑豹丢出肉干。和驯兽计量表的上升呈反比，我们的HP不断减少。等级13的我HP总量比等级4～5的结衣她们还要多，这时她们三个人排在视界左上方的HP条已经不到五成。

虽然焦急地想着「快一点、快一点……」，但这种游戏的驯兽最重要的应该就是时机。喂完一个饲料后，当计量表上升期间再喂下一个饲料……时机不论太快或太慢都会失败。

把得自结衣以及莉兹的肉干都丢出去后，驯兽计量表就上升到八成。亚丝娜在驯服阿蜥时，应该只喂了三片熊肉就让计量表全满了，但这只黑豹的上升效率实在不怎么样。因为不是生肉而是肉干的缘故吗，或者是因为怪物的等级比较高呢？

「莉法。」

「OK。」

我丢出放在右手上的第九片肉干。黑豹大口吃下，计量表上升到九成。

「莉法。」

「我没有了喔。」

「…………啥？」

我转过头去，对在黑暗中依稀可以看到剪影的妹妹逼问：

「怎么会没有，亚丝娜不是给我们一人三片吗？刚才休息的时候每个人吃了一片，这样应该还有两片……」

「因为我刚才吃了两片。」

「啥？」

「有什么办法嘛，我肚子饿了啊！」

「什么……」

虽然感到愕然，但没有的东西就是没有。事到如今才想不应该把鬣狗的肉丢掉也太迟了，何况也不认为黑豹会想吃那种臭到令人绝望的肉。

转向前方后，浮现在黑豹眼前的驯兽计量表正在九成上下变动着。这样放着不管的话将会开始下降，至今为止的努力就白白浪费掉了。

僵住的我耳边传来结衣细微的声音。

「爸爸……我的HP已经……」

「结衣……」

我丢下左手的火把然后把心爱的女儿拉过来，然后用双臂紧抱住她。即使透过铠甲也能感觉到娇小的身体冰冷到极点，目前正不断微微发抖。确认HP条后，残量只剩下一成左右。绝对不能让她在这个地方冻死。

我下定决心后就抱着结衣一点一点地前进。越往洞窟深处寒气就越趋缓和，但黑豹又开始发出低吼。驯兽计量表一边摇动一边开始减少。

已经没有可以喂食的饲料。但是提升计量表数值的方法不是只有喂食而已。

「不用害怕……我不是敌人……」

我一边对黑豹这么呢喃一边继续靠近。黑豹的低吼声虽然变大了，但是没有逃走也没有要袭击过来的迹象。

双方的距离剩下两公尺……一公尺……五十公分。靠到这么近之后，终于可以看见黑豹的身形。它正低下头，似乎随时都可能扑过来。驯兽计量表已经降到剩下八成。

我带着手可能被咬掉的觉悟伸出右手。碰到黑豹强壮的脖子后，它的身体就震动了一下。

「乖孩子，不用怕喔……」

我用指尖静静摸着它光艳的毛皮。「咕噜噜噜……」的低吼没有消失。驯兽计量表也持续一点一点下降。但这时候要是露出恐惧的模样应该就会立刻遭到袭击吧。左手依然抱着结衣的我，只是专心动着右手。黑豹的肌肉紧绷、放松然后再次紧绷。

「咕噜噜……噜噜噜噜……」

黑豹的头随着变低沉的吼声垂下。这是攻击的前兆还是……

「噜噜噜……呼噜噜噜……」

突然注意到原本没有间断的吼声，曾几何时音调已经改变了。「呼噜噜噜……」这种浑厚的低音，听起来简直就像猫咪从喉咙发出的声响。

强壮的肌肉完全放松的同时，驯兽计量表也停止减少并再次开始上升。黑豹整个躺到地面后就任凭我抚摸了。计量表再次到达八成，随即超过九成。

「很好很好……乖孩子……」

我一面呢喃一面把左手往后伸。看过成功驯服阿蜥那一幕的莉法，立刻把天根草的绳子交给我。

像要吊人胃口般缓缓增加的驯兽计量表终于到达十成的瞬间，我就把绳子的一端绕过黑豹的脖子做成项圈。好不容易以僵硬的指尖打好结后，黑豹巨大的身体就发出光芒，头上跟着出现绿色立体浮标。环状HP条下方以片假名显示着种族名称。名称是【贝流离暗豹】。接着视界中央又浮现【获得驯兽技能。熟练度上升为1】的讯息。

──先不理会不是黑豹而是暗豹一事，贝流离又是什么意思？

但是根本没有多余的时间去追究这个问题。我对着莉法与莉兹贝特表示：

「贴在豹身上！」

一叫完自己也像是要把结衣压在豹脖子上一样抱住了它。莉法她们也趴在暗豹长着柔软毛皮的腹部。

豹的体温相当高，热量慢慢传到原本快要冻僵的身体上，我这才轻吐了一口气。HP终于停止减少，冷气图标也消失了。入口处依然有冰粒吹进来，但是无法抵达洞穴深处。

终于感觉舒服多了后，我便随口询问：

「……贝流离是什么？芹菜吗？」（注：贝流离的日文发音与芹菜相似）

结果莉法抚摸豹泛蓝的背部并且回答：

「背部的毛是琉璃色的意思吧？」

「啊……背琉璃吗……」

听见我的呢喃后，莉兹贝特就对我问道：

「那么，你要帮这个孩子取什么名字？」

「嗯？这个嘛……『小黑』吧。」

考虑了两秒后一这么回答，莉法与莉兹就同时大叫「太随便了！」。但是结衣却说「我觉得简单的名字很不错」，于是我就询问当事者。

「很不错的名字吧，小黑？」

结果黑豹简短地发出「嘎呜」的吼叫声。

** 第七章

「……果然应该问个清楚的……」

这么呢喃完，诗乃就举起紧紧裹在身上的毛皮边缘并窥看外面。

数分钟前还是干燥草原的练功区染成一片白色。伸手掬起白色物体后，白色细微颗粒就从指尖不断落下。堆积的不是雪而是冰粒。

欧鲁尼特族的少女费琪把这件毛皮送给自己时，说过「NN来袭的时候记得要用喔」。因为语言技能的熟练度不足而没能听出来的单字应该是「冰风暴」之类的吧。或许是「地狱的极寒暴风雪」也说不定。眼前的暴风雪确实强大到让人忍不住浮现这种想法。即使钻到岩石底下的凹陷处，再用厚厚毛皮披风裹住全身，HP还是被削除了将近五成。

确认打开披风也没有亮起冷气图标后，诗乃就从岩石底下钻出来。环视月光照耀下的白银世界然后发愣了一阵子。

从欧鲁尼特族的村子出发已经过了一个小时，由于尽可能持续地奔跑了，在被卷进冰风暴之前应该移动了二十公里吧。看见连地平线都埋在冰粒底下的模样，就开始担心起村子的安危了。不过当然不能回去。虽然不清楚距离巴辛族的村子还有几公里，但今天晚上不抵达该处的话，就得在基幽鲁平原的正中央登出了。虽然VR游戏界的Unital ring事件是继二○二二年的SAO事件以来的紧急事态，但诗乃还是没有胆量以它作为翘课的理由。

压抑下现在立刻再次开始移动的心情，诗乃再次坐到岩石的阴影底下。将毛皮披风收进道具栏里，然后取出费琪送的硬面包，开始一点一点啃着。虽然硬到像是要让牙齿崩断而且也没什么味道，但是为了节省火烤的时间还是忍耐着继续吃下去，结果HP与SP就开始一点一点回复。好不容易让HP回复到八成后，就喝起水壶的水。由于在奔跑当中消耗了不少水，差不多得寻找水源来补充了……

「……啊，说不定……」

这么呢喃完就用双手掬起附近堆积了许多的冰粒来装进水壶里。等了一会儿后冰开始融化，水量跟着回复。重复同样的作业之后水壶立刻装满了水。由于气温开始上升了，地面上的冰应该马上就会融化了吧。如果有容器，现在就能尽情补给饮用水了……这么想的诗乃咬牙环视着周围。附近当然没有水壶掉落，也没有能制作容器的素材，当然诗乃也没有制作的技能。

仔细看着欧鲁尼特族的水壶，似乎是由经过防水加工的皮革所制成。至今为止都没有注意到，不过跟里面的水比起来，这个轻量且坚固的水壶可能更加贵重。不论是毛瑟枪还是近代化建筑物，为什么他们拥有如此高度的技术虽然令人在意，但应该要很久之后才能再次回到那个村子了。

诗乃先把刚才融化的冷水大口喝下让TP条完全回复后，再次把冰粒放进水壶里面。快速跑动的话，在冰粒完全消失之前应该还能补给个一次吧。

背起靠在岩石上的毛瑟枪，确认左腰上还挂着雷射枪后，诗乃就猛然在白银的平原上跑了起来。

诗乃将储存了15点的能力点数消费了10点所取得的能力是「俊敏」能力，以及从该处衍生的「远奔」与「巧手」。就效果来说，「俊敏」是增加远距离武器伤害、近身小型武器伤害以及跳跃距离。「远奔」能缓和奔跑中的TP、SP条减少。「巧手」是增加远距离武器命中率与开锁成功率。虽然「远奔」衍生出来的能力「疾驱」与「轻功」，「巧手」衍生出来的能力「要害瞄准」与「熟练」也令人在意，但是要取得第3阶的能力必须花3点所以就忍了下来。虽然觉得以自己的个性来说留下5点似乎有点太慎重了，但感觉今后也会出现需要「俊敏」技能树之外的能力──尤其是「顽强」技能树的场面。

总之目前「远奔」的缓和TP．SP减少效果相当大，只提升到第2级减少速度就明显变得缓慢多了。没有取得它的话，实在没办法一个小时就跑完二十公里。

为了弥补受暴风雪牵连而停下脚步的时间，诗乃拼命地跑着。至今为止除了躲避怪物之外，连看起来似乎躲藏着怪物的地形都必须回避，但它们可能为了躲避冰风暴而躲到地底下去了吧，由于完全看不到会动的东西，所以诗乃便持续朝着东南方猛冲。累积了二十公分左右的冰粒，虽然一踩上去就会发出沙沙声，但是跟雪不一样，因为结构相当结实，所以没有想像中那么棘手。

跑了十五分钟左右，脚边的冰层慢慢变薄了。冰粒随着气温上升开始融化。诗乃停下来喝水壶里的水，回复了TP后再以残留的冰粒补充饮用水。在进行这样的作业期间冰粒也不断地蒸发，接下来得另找水源了。可以的话希望在那之前就能横越基幽鲁平原……这么想着的诗乃随即看向前方。

然后就注意到再次出现星光的夜空地平线附近浮现漆黑的棱线。那是山脉……不对，是断崖吗？断崖就像一道墙壁一样，分隔一路延伸了将近三十公里的苍茫草原练功区。

基幽鲁平原是在那里结束吗？这样的话巴辛族的村子就在那道墙壁的附近喽？

如此期待的诗乃，从北到南一直盯着断崖的底部看。但是看不见人工光线般的东西。现在的时刻是将近夜晚的九点。感觉村子里的亮光要全部消失好像还太早了，现在也只能这么相信然后继续前进。

一旦开始融化之后冰粒就迅速开始蒸发，草原恢复原本的模样。为了躲避寒气而躲藏起来的野兽与昆虫应该也会再次开始活动吧。接下来要注意怪物的气息──诗乃即使这么对自己说道，小跑步中的双脚还是没有停下来。

靠近之后，发现断崖的规模比想像中还要大。

高度随便就超过五十公尺，由于几乎呈完全垂直状，所以不可能爬上去。就算想从北或者南边绕过去，也因为断崖延续到能看见的范围之外，无法判断该往哪一边。

虽然诗乃没有直接看见的机会，但是据说Underworld的人界是被称为「不朽之壁」的境界墙分割为四个帝国，就连贵族甚至是皇帝都不允许越过那道墙。之所以能够实行如此蛮横的规则，也是因为那个世界不是游戏的关系。既然这个Unital ring还算是游戏，墙壁的某一处应该会有穿越墙壁的道路才对。

诗乃环视周围，找到平坦的岩石后就爬到上面。确认过附近没有怪物，诗乃就打开道具栏将爱枪黑卡蒂Ⅱ实体化。

即使知道是白费力气，她还是试着要举起稳稳镇座在岩石上的反器材步枪，结果枪械没有丝毫移动。即使升上等级16，装备重量还是超出自己能负荷的范围许多。诗乃吞下叹息，以卧射姿势窥看瞄准镜。当然也可以从黑卡蒂上把它拆下来当成迷你望远镜来使用，但这么做的话再次装上时，就必须重新调整轴线与归零校正。虽然跟现实世界的步枪比起来调整作业已经简略化许多了，但因为需要试射，所以现在实在办不到。

因此诗乃才会辛苦地改变黑卡蒂的方向，仔细地检查着五百公尺前方的断崖。泛黑的壁面凹凸少到不像是天然地形，想徒手攀登果然是自杀行为吧。虽然到处长着小树，想抓住它们往上爬的话数量又明显不足。由于观察北侧后没有发现任何东西，所以用黑卡蒂的两脚架作为支点来使劲改变方向，开始眺望起南侧。结果──

「……啊……」

发出细微的叫声后，诗乃调升了瞄准镜的倍率。一部分断崖上被凿出阶梯般的斜坡。心跳加快的诗乃以视线追上去后，发现斜坡的最上部被一个漆黑的横向洞穴吞没。

找到穿越断崖的通路产生的兴奋与身为狙击手不想钻进狭窄洞窟的不安同时在内心涌现。但不论如何，除了进到那里去之外也没有其他选择了。把黑卡蒂收回道具栏并站起身子。HP已经藉由硬面包回复，TP与SP也还有将近九成。虽然想有效利用一直全满却无处可用的MP，但目前完全不清楚习得魔法技能的方法。

难得继承了狙击枪技能，不能当魔法剑士当个魔法枪手也不错……诗乃一边这么想一边朝着巨大的断崖跑去。

** 第八章

冷冽蓝色月光照耀着覆盖在纯白冰粒下的平原，即使知道这是虚拟的光景，它依然美到令人默默看着它入迷，但刚加入小队的背琉璃暗豹小黑用头轻戳着我的腰部让我回过神来。

「噜噜噜……」

喉咙发出这样的声音，似乎在说我们快走吧。我边搔着它的脖子边回答：

「也是啦。再一下下就要抵达巴辛族的村子了。」

实际上村子并非最终目的地。我们要在那里收集与诗乃遭遇的鸟人相关的情报，然后就必须再次开始移动。在今天凌晨十二点前能够跟诗乃会合就已经是谢天谢地了，应该要这么想比较好吧。

托冰风暴的福，杂兵怪物全都消失无踪了，所以我想着要趁现在尽量多赶一些路并且准备宣布出发的号令。但莉兹贝特却比我快一些发出带有不安的声音。

「桐人，关于这件事呢……」

「你指的是……巴辛族？」

「嗯。我和西莉卡以及结衣曾经在巴辛族的帐篷里面吃饭……那时候地板上铺着许多毛皮地毯。」

「然后呢……？」

「里面好像也有混杂着黑色与蓝色的地毯……」

「…………」

我把视线从莉兹的脸移到小黑的背上。正如种族名称，漂亮的琉璃色毛皮点缀着乌亮的黑毛。很快就跟小黑打成一片的结衣，一边摸着它的背部一边以认真的表情补充道：

「帐篷的角落确实铺着这种配色的地毯。颜色成分有九十七％与小黑先生的毛皮相同。」

结衣的记忆绝对不可能出错。看来可以确定巴辛族会在平原上狩猎背琉璃暗豹了。

就算是这样，一般游戏的话NPC绝对不可能攻击玩家驯服的野兽，但是无法保证这样的常规适用于Unital ring。

「嗯……这样的话就让哥哥和小黑在村庄附近等待，我们几个人去收集情报过来吧？」

由于觉得莉法的提案相当合理，我就准备开口说「如果村庄有食物可以吃的话也帮我带一份吧」。但结衣却快了我一步再次开口说道：

「爸爸，说不定根本没有必要到村子去喔。」

「咦？这是什么意思？」

「刚才的暴风雪规模相当大。如果诗乃小姐也遭遇到暴风雪的话，现在位置在这个基幽鲁平原另一侧的可能性就很高了。」

「……原来如此，确实有这种可能……但是，那要怎么跟诗乃取得联络？没有登录为朋友，而且也不是小队成员，根本没办法传送讯息啊。」

听见我的回答后，结衣就露出灿烂笑容并且说：

「不是在Unital ring内，直接在现实世界里联络如何呢？」

遵从心爱女儿的建议，我一暂时登出就撑起上身跳了起来。从白银色平原瞬间移动到自己无机质的房间让我感到有些晕眩，但还是低头看向旁边。床铺的左侧，头戴AmuSphere的直叶正露出毫无防备的睡脸……但她当然不是真的睡着了。现在这个瞬间，直叶就在遥远的虚拟世界里保护着我的虚拟角色。虽然确认过周围没有敌人，但经常存在涌出危险怪物的危险，所以没有时间发呆了。

我抬起自身头上AmuSphere的眼罩，从床头板上抓下手机。操作因为Augma的登场而逐渐跟不上时代的电子机械来打电话给诗乃。

她应该也潜行到UR世界里面了，但AmuSphere具备与手机同步，告知有电话打进来的机能，只要打开这种机能的话──然后不是在战斗中或者近似于战斗的状态，她应该就会接电话才对。耐着性子听着铃声持续响了三十秒。

「拜托长话短说！」

这种省略了许多细节的声音就从手机里传出来。由于那绝对是诗乃的声音，我就回应她的请求直接进入主题。

「你遇见冰风暴了吗？」

「二十分钟前左右差点冻死了。」

「那么诗乃目前是在基幽鲁平原对吧？」

「是啊，从西北方往东南方前进。」

「了解，那我们从东南往西北前进！有没有什么显眼的地形？」

「有喔，大概是平原的正中央，有一面南北向的天然巨大墙壁。我现在从墙上的洞窟进到里面往前走了一些距离。」

「墙壁的洞窟……怪物呢？」

「到处都是。我尽可能在看起来安全的地方登出了，但随时都可能从旁边涌出怪物。」

数十秒前也有完全一样的想法，但是跟被伙伴与宠物保护着的我不同，诗乃只有自己一个人。登出期间受到攻击的话马上就会死亡。

「了解了。我们也会从东侧进入墙内，你再加油一下吧。」

「了解，那就拜托了。」

这句话之后电话就挂断了。我只喝了一口水就再次躺到床上，然后放下AmuSphere的眼罩。

回到月夜的平原后，当我登出的几分钟里，地面的冰已经开始融化。莉兹贝特她们用双手收集残余的冰粒，把它们装进素烧水壶里。看来旁边没有涌出怪物。

「我回来了！」

我边叫边站起来后，小黑就再次用头过来蹭我。外表看起来虽然凶猛，但一旦驯服之后似乎就很亲近人。由于熊肉干已经全部被它吃光，必须尽快想办法准备这个家伙的饲料才行。

我直接对聚集过来的莉兹贝特、莉法以及结衣说出诗乃说过的话。

「天然的墙壁……？」

如此呢喃的莉法一直盯着西北方向看。我虽然也跟着这么做，但地平线已经沉没到深沉黑暗当中，所以根本无法看透。心里虽然不安地想着「会不会有什么重大的误会……」，但现在也只能相信诗乃拼死送给我们的情报了。

「快赶路吧。」

简短地说完后，三个女孩子就同时点头，小黑也发出「嘎呜」的吼叫。

拼命在平原上奔跑当中，遇上了两次熟悉的鬣狗以及一次野牛般的牛型怪物。牛虽然有点棘手，但是靠着小黑以玩家不可能具备的机动力进行扰乱，然后趁机轰出剑技这样的战法才好不容易削光HP，莉法她们都提升了1级。

从牛身上获得大量生肉，幸好小黑津津有味地吃了起来。这样就有好一阵子不用害怕因为空腹而解除驯服了。

之后就没有被怪物缠上，当移动时间超过三十分钟时。结衣迅速指着前方大叫：

「看到墙壁了！」

停下脚步凝眼一看之下，确实可以看见垂直站立在平原上的断崖。南北向的巨大断崖，规模足以让人联想到Underworld的不朽之壁。

「诗乃潜入的洞穴就在那面墙的某处对吧？」

虽然点头同意莉兹贝特的发言，但仔细一想就发现要从南北连绵数十公尺规模的断崖上寻找小小洞穴不是件容易的事，而且就算找到了也无法保证那就是唯一的入口。

我压抑下焦燥的心情，思考着该怎么办才好。

「……爸爸，虽然有点犯规，不过我就强化视觉情报来搜寻洞窟吧。」

如此宣言的结衣，随即瞪大了圆滚滚的双眼。

四个人当中，我、莉兹贝特和莉法是以自己的脑来「看见」AmuSphere所给予的视觉情报，所以不可能加工，只有身为AI的结衣可以自由自在地调整视界的亮度与对比。可以的话实在不愿意把她当成方便的工具，但无论如何都必须跟诗乃会合，而且如果按照最初的计划到巴辛族村落去的话也要拜托她帮忙翻译，所以现在才阻止她这么做实在不合理。

「麻烦你了……」

我这么呢喃完后，结衣就一瞬间往上看着这边并露出微笑，然后立刻把脸移回去。几秒钟后，她就指着前方的一点──

「找到了！这个方向有阶梯和洞窟的入口！」

「谢谢你，结衣！」

莉法抱紧结衣，莉兹也轻摸着她的头。

从这个位置无法看出断崖的深度，不过应该不会有好几公里吧。就算内部是迷宫，规模应该也不大才对。

──诗乃，再撑一下啊！

如此祈祷完，我们就一直线往结衣所指的方向跑去。

越是靠近淡淡浮在地平线上的断崖，其存在感就越是增加，当四个人抵达断崖底部时，全都因为它雄伟的模样而说不出话来。它的高度大概是五十公尺左右，阿尔普海姆里其实有更多落差更大的地形，但是南北的长度可以说非比寻常。如果是其他游戏，或许会觉得从视界的这一头一直线延续到另一头的断崖是设计师偷懒的结果，但不知道为什么在Unital ring世界就是会让人老实地感叹大自然的惊奇。

漆黑岩石表面相当光滑，怎么想都不可能空手爬上去。或许能以手工艺技能来设置梯子，但附近完全没有可以作为素材的树与藤蔓，所以这也是相当困难的作业。看来果然只能使用结衣帮忙找到的阶梯了。

那条阶梯是将岩石表面凿出短短三十公分所制成，也没有任何的扶手。到达洞窟入口处大概有二十五公尺左右，要是不小心踏空而跌落，甚至有可能立即死亡。可以的话希望能在墙上设置导向绳，但是想到跟诗乃联络后已经过了将近一个小时，就觉得不能再让她等下去了。

「小黑，你能爬上这条阶梯吗？」

一这么问，黑豹就回答「嘎呜」，接着毫不畏惧就一瞬间爬上长三公尺的阶梯。它像要表达骄傲之意般挥舞长尾巴的模样，让身为饲主的我也无法示弱。

「好……要走喽。」

做出这样的宣言之后，身后的莉兹贝特则以受不了的声音说「快点走好吗」。

没有发生跌落事故就平安爬完楼梯的我们，进入在壁面张开大口的洞窟就同时松了一口气。由于阶梯是人工打造，原本以为洞窟应该也是如此，但它似乎是天然形成。也就是说有人凿了这条阶梯一路通到断崖中腹的洞穴。当然这么做的应该不是玩家而是NPC吧，不清楚是传闻中的巴辛族还是其他种族就是了。

不论如何，这是昨天的强制转移之后首次进行正式的迷宫探索。因为不认为有抢在我们前面的玩家，如果有素材和宝箱的话，应该还没有被人拿走才对。一想到这里就很想把洞穴整个翻遍，但现在还是以跟诗乃会合为最优先事项。

由于到这里之前已经跑了相当远的距离，所以SP条剩下不到六成，TP条则不到五成。饮用水虽然相当充足，但食物则只有生的野牛肉。于是只先喝了水，然后以水和生肉喂食小黑，决定等跟诗乃会合之后才进食。

「桐人啊，我们的小队实在不怎么平衡，队列该怎么排呢？」

把水壶收起来的莉法对我这么问道，我稍微考虑了一下后回答：

「我和小黑打头阵，中间是莉兹和结衣，就拜托莉法你殿后了。火把由我和结衣来拿。」

下一个瞬间，莉兹贝特就出现有话想说的表情。因为只有她装备了盾牌，所以想作为坦克站在前卫吧，但我希望她以保护结衣为优先。她似乎能够了解我的用意，没有反驳就点了点头。

「了解，一有危险就立刻切换喔。」

「嗯，全靠你了。」

互相点点头后，立刻迅速排出2─2─1的队列。

VRMMO玩家里面有不少人认为战斗开始之后才摆阵形也绰绰有余，在移动时就刻意先排好是愚蠢且难看的一件事。我也认为一百次的战斗里面有九十九次确实是这样，但是艾恩葛朗特里只要有一次松懈就会酿成无法挽回的悲剧──尤其是在容易变成混战的迷宫内──所以即使是从死亡游戏解放出来的现在，我也一直没有办法轻忽队列。

「发现怪物的话要通知我喔。」

我搔着小黑的脖子并且这么对它呢喃，黑豹则发出「嘎呜」的短吼来回应。

诗乃在电话里面说过「到处都是怪物」，结果她说的一点都不夸张。潮湿的洞窟内不断出现滑溜的两栖类般怪物，让我们感到很厌烦。幸运的是小黑的搜敌能力相当强，在敌人现身前就会发出低吼来警告我们，所以可以提前做好准备来迎击。结衣也发挥跟爱丽丝进行特训的成果，勇敢地以短剑应战，拿出实力证明一切都是我白操心了。

我们就一边把巨大壁虎与巨大蚓螈、巨大墨西哥钝口螈等劈成两半，一边往深处前进。很可惜的是没有遭遇到宝箱，不过倒是发现不少铁、铜等矿石，把它们全丢进道具栏并且继续前进了二十分钟。

SP开始让人感到不安了，但实在不想生吃壁虎肉……当我边这么想边走路时，最后面的莉法就开口表示：

「不过真的很奇怪耶。」

「哪里奇怪了？」

「先不管为什么只出现两栖类怪物，明明有那么多壁虎和山椒鱼，但最常见的那个……」

哒嗯────

某种清脆的声音在远处形成回音并且传了过来，莉法倏然停止继续说下去。

在这座迷宫，或许应该说在Unital ring世界从来没有听过像这样的声音。小黑的身体整个紧绷并发出低吼。刚才那应该是火药的炸裂声──也就是枪声。

「是诗乃！」

压低声音这么叫完，我便转过头去。

「结衣，知道声音来源的方向吗？」

「我来分析回音……是从前方右侧的通道传过来的！」

对以坚定口气如此表示的结衣说了句「谢啦！」之后，就加快移动速度。到了双岔路就选择右边，然后在呈大角度弯曲并且逐渐往下的通道上小跑步前进。

视界突然一口气变得开阔。我们来到巨大圆顶状空间的上部。其直径应该将近五十公尺吧。这已经远超出火把能够照亮的距离，之所以能够看到对面，是因为巨蛋墙面上宛如光苔般的地衣类发出微弱光芒的缘故。

墙上有一条狭窄的斜路从我们所在的地点呈环状延伸到巨蛋底部。底部是潮湿的岩石与蓝黑色水洼各占一半面积，正中央附近的岩石上可以看见一道人类般的剪影。

那个人身穿紧身衣型防具以及白色围巾。以双手架着细长棒状物──是枪械。这种地方不可能偶然出现其他使用枪的玩家。我们终于跟诗乃会合了。

「诗……」

本来想叫她名字的我闭上嘴巴。

枪使的背后也有复数的人影。不对，虽然直立着但不是人类。尖尖的鼻子和又圆又大的耳朵……头部长得跟老鼠一模一样。另外双手则拿着像草叉的武器。鼠人一边摇着细细的尾巴一边慢慢朝枪使靠近。数量是两……不对，是三个。

「诗乃，后面！」

我重新这么呼唤，然后尽可能以最快速度跑下沿着巨蛋墙面的斜路。小黑和莉兹贝特她们也从后面跟上来。

枪使──诗乃迅速抬头看向这边，接着又看向后方。她和鼠人之间的距离已经不到五公尺了。就算击中其中一个，也会被其他两个人的叉子刺中。

「嘿呀！」

我从斜路途中跳起，对准浅浅水洼落下。溅起大量水花后，HP条虽然稍微减少，但没空管这种小事了。我先准备朝最靠近诗乃的鼠人丢出左手上的火把──

「桐人，不对！他们不是敌人！」

听见这样的叫声，我便反射性重新握好火把。然后急忙对快要扑向其他鼠人的黑豹做出指示。

「小黑，停下来！」

黑豹紧急煞车之后，三个鼠人就发出「NNNN！」的尖锐悲鸣并且飞退到墙边。除了我们一路走过来的通道之外，他们附近也能看到开了另一个出入口。

往旁边一看之下，就跟占据岩石上方的枪使四目相对。发尾整个翘起的蓝色短发，使人联想到猫咪的上扬眼睛让我确定她是诗乃本人。但是双手举着的步枪外型看起来相当复古，和她的搭档「PGM Ultima Ratio HecateⅡ」完全不一样。就算跟我的黑色鞭痕与断钢圣剑一样，黑卡蒂也因为重量限制而无法装备，不过那把枪到底是从何处得到……当我这么烦恼之后，就发现现在这种事情根本不重要。

「诗乃，鼠人不是敌人的话，那你在跟谁战斗？」

当我这么问时，莉兹贝特、结衣以及莉法也抵达巨蛋底部。看见踢着水洼跑过来的三个人，诗乃的表情一瞬间放松了下来。但立刻再次绷起脸大叫：

「大家快从水里上来！尽可能到高的岩石上！」

那强硬的口气让我把问题吞了回去，开始准备爬上附近的岩石。但「哔咻」的水声比我快了一瞬间传出。

水面下方有某种东西以惊人的速度靠近。来不及闪躲冲击就往我的右脚踝袭来。被咬了……不对，是被某种东西缠住了。

右脚突然间被惊人的力量拉扯，我整个人倒到水洼里。火把脱手飞了出去，发出「噗咻」一声熄灭了。虽然想以右手的剑切断卷在脚踝上的像是绳子的物体但是却不够长。这样下去会被拖到水深的地方──

「嘎噜哦！」

短吼了一声的小黑把头栽进水里，咬住拉着我的物体把它从水里拖出来。那不是绳子。是发出滑溜光芒的粉红色触手般物体。

「哥哥！」

莉法举起长刀，发动了剑技「音速冲击」。水面「咻啪！」一声一分为二。不是我自夸，这真是妹妹提升到界限的完美一击。闪着绿色光芒的刀刃痛击小黑咬住的触手──但无法直接把它切断。

莉兹贝特锻造的钢铁长刀只砍进粉红色触手几公分就停了下来。如橡胶般绷紧的触手发出「哔嗯──」的声音反弹回来。

「呀啊！」「嘎呜！」

莉法跟小黑同时被弹飞并且溅起水花。但两人的攻击没有白费，触手解放了我的右脚再次消失于深水之中。

我急忙帮助莉法起身，这次真的爬上附近的岩石。结衣与莉兹贝特也各自退避到岩石上，起身的小黑则是一跳就移动到我身边。

「诗乃，刚才那是……？」

再次询问后，枪使就在举着旧式枪械的状态下回答：

「马上就会从水里出来了！它会到处乱跳，不要跟丢了！」

当她的话还没说完时。

「哗啦！」的盛大水声响起，一道黑影从遥远的水面窜出。黑影相当巨大，全长两公尺……异样强壮而且长的后腿完全伸直的话应该会加倍吧。但是前脚却相当瘦弱，头部与胴体连在一起。

巨大生物以令人眼花撩乱的速度从这个水坑跳到另一个水坑，最后贴在巨蛋的墙面上静止不动。我和莉兹贝特、结衣、莉法异口同声地大叫：

「青蛙！」

不理会尺寸的话，完完全全就是一只青蛙。有着巨大突出的双眼以及菱形的胴体。从折叠起来的四肢伸出的手指，前端像是吸盘一样鼓起。

这时我终于理解在听见枪声前莉法想说些什么了。出现一大堆壁虎和山椒鱼却没有半只青蛙。

「太棒了，真的有青蛙喔。」

我抬头看着贴在墙上的两栖类代表性动物并这么呢喃，结果莉法就以苦涩的声音回应：

「我又没希望它一定要出现……何况又是这么大只的……」

「这绝对是这个洞窟的魔王了……」

我绝对不是没有任何根据就这么呢喃。由于右脚受到触手攻击，巨大青蛙头上已经显示着环状浮标。专有名称是【Goliath rana】。目前为止遭遇的怪物包含小黑在内名字全是日文，那只青蛙是英文名字是不是有什么意思呢？说起来那真的是英文吗？

「……Goliath是巨人对吧？那rana是什么意思？」

听见我的呢喃，结衣立刻告诉我说「应该是赤蛙的意思」。那只巨大青蛙的胴体确实是暗红色，双眼也像炽焰一样发着光。

Goliath rana突出的眼睛眨了一下后，就开始缓缓爬上墙面。跟牛差不多大的巨躯垂悬在墙上顺利移动的模样给人奇妙的无重力感。

「诗乃，现在是射击的时机了吧？」

面对把枪架在腰部而没有任何动作的枪使，我即使知道这是多嘴也还是开口这么问道。结果诗乃依然维持往上看着青蛙的姿势，然后以浮躁的口气回答：

「我射击过好几次了。但那家伙背部的皮太坚固了，这把毛瑟枪没有办法打穿。」

我记得毛瑟枪应该是《三剑客》时代左右使用的旧式枪械。枪身没有膛线，所以无法称为来福枪。虽然反而令人在意她是在哪里得到这种武器，但现在没有多余的心思去问跟战斗无关的问题了。

「……要不要用几个人支撑黑卡蒂，然后硬撑着开枪？」

新的提案也立刻被驳回。

「没办法，在天花板时无法取得射角，下来后动作又太快了根本无法瞄准。」

「原来如此……」

虽然对在僵在后方的鼠人身份感到在意，但不是敌人的话之后再查探就可以了。现在得想出解决那只Goliath rana的办法才行。

「桐人，艾恩葛朗特里的青蛙怪物通常腹部都是弱点吧。」

举着锤矛的莉兹贝特提出的建议让我快速点点头。

「确实是这样。想办法让它露出肚子，然后攻击那里吧。」

莉法表示「该怎么做呢？」。

当我发出「呃……」的沉吟声时。巨大青蛙抵达了高应该有三十公尺的巨蛋最高点，然后在完全倒栽葱的状态下以红色双眸瞪着四处。

「要来喽！」

几乎跟诗乃发出叫声的同一时间。青蛙强壮的双脚往岩石踢去，以超乎想像的速度朝我落下。

「呜喔哇！」

本能地后空翻才好不容易闪过直击，但前一刻我还站着的岩石已经消失无踪，飞溅的碎片击中我的全身。HP只减少了三％左右，不过如果没有穿着金属铠甲的话应该就不只受到这样的轻伤了。不对，就身边没有任何药水的现状，轻微的伤害累积起来也会致命。

确认结衣等人的HP条没有减少之后，又注意到忘记相当重要的事情。我继续后退并且叫出环状选单，击打社群标签里的邀请键后把它滑向诗乃。对方立刻承认，新的缩小HP条出现在视界左上方。

实行陨石般跳水攻击的Goliath rana在该处蹲了三秒钟左右就立刻有所行动。它跳进附近的水面消失无踪了。

「到岩石上面！」

在诗乃的指示下，我们再次跳到附近的岩石上。以视界边缘捕捉到待在一起的结衣与小黑也爬到岩石上后，我就向诗乃确认。

「那家伙的攻击模式是重复潜入水中的触手攻击以及爬到天花板上的跳水攻击吧？」

「目前是这样。还有那不是触手是舌头。」

「啊……原来如此。」

也就是说刚才缠上我右脚的Goliath rana不单纯只是想让我溺水，它其实是想把我吃了。即使是一次都不能死亡的Unital ring，我也全力拒绝这样的死法。

一直待在岩石上不动后，青蛙终于冲出水面并再次爬上墙面。虽然我们没有攻击方法，但只要能躲过跳水攻击就不会受到太大的伤害……不对，不是这样。它每跳一次就会有一块岩石遭到破坏，最后能躲过舌头攻击的安全地带将完全消失。

「莉兹、莉法，躲过下一次跳水之后，在那家伙行动前就要发动剑技。尽量瞄准身体下侧把它翻过来。」

「嗯。」「了解了。」

听见两个人的回答，我就继续做出指示。

「诗乃、结衣，等青蛙露出肚子你们就加以追击。小黑你负责保护结衣。」

「了解。」「我了解了！」「嘎呜。」

其他两个人也就算了，虽然不清楚黑豹能了解几成指示，但现在也只能相信它了。

Goliath rana以带有巨大吸盘的四肢黏着岩石往上爬。看来还要十秒钟才能到达顶端。能不能以手边的素材在青蛙落下的地点设下陷阱呢？像是以圆木制造长枪阵之类的……只不过也要木工技能的制作选单里有这个选项就是了……

「桐人！」

诗乃的叫声让我倏然瞪大双眼。Goliath rana明明尚未抵达巨蛋的最顶端，两脚就已经开始膨胀了。

「咕喔！」

我拼命往后跳的同时，青蛙也刚好往墙壁踢去。以宛如炮弹般速度冲过来的巨躯粉碎眼前的岩石，拳头大的石块痛击我的右肩、腹部和左脚。铁铠甲凹陷，HP出现明显的减少。

──这个臭家伙！

我为了挽回失态而在空中进入下段突进技「愤怒刺击」的发动体势。由于这招本来需要把身体前倾到几乎快要碰到地面才行，在跳跃中发动算是相当高超的技术。

在浅水滩着地的同时，我的剑就发出淡蓝色燐光。剑技发动的瞬间，我更踢向地面来加强威力。在左右两边扬起白浪的状态下，长剑朝着陷入弱晕眩状态的Goliath rana喉头冲去。

莉法与莉兹贝特也几乎跟我同步从右边与左边冲过去。两个人都依照作战发动了下段剑技。一次受到这么多攻击的话，就连那只巨大青蛙也会被翻过来才对。

但我这样的确信──

在零点一秒后就变成了战栗。

突然间，Goliath rana像小山一样的巨躯像是没了骨头一样往下沉。变平的身体紧贴在地面，脖子与肚子都看不见了。但剑技已经无法停止。我的剑命中青蛙的鼻梁，莉法的长刀与莉兹贝特的锤矛命中左右两边的肩膀附近，让它暗红色的皮肤整个凹陷。

感触就像是砍中一大块橡胶一样。剑尖明明沉进去了却没有传来撕裂的感觉。当反弹力急遽上升并超越了剑技突进力的瞬间──

我、莉兹贝特以及莉法各自发出不同的尖叫声并且被快速弹飞。身体浮在空中无法摆出防御姿态。Goliath rana这时大大张开嘴巴。成鲜艳桃色的舌头暂时内缩──在快要像枪一样发射出来之前。

「哒啊啊啊嗯──！」的巨大声响击打我的耳朵。诗乃的毛瑟枪开火了。子弹贯穿青蛙的舌头，让其迸发出深红色伤害特效光。HP条只减少了一成左右，但是青蛙却发出「呱咿」的声音并且往后仰，露出了看起来很柔软的喉咙。

「呀啊啊！」「嘎呜！」

结衣发动剑技「垂直斩」，小黑也露出巨大牙齿冲了过去。剑与尖牙从左右两边撕裂青蛙的喉咙。HP又减少一成左右。

结衣与小黑的同时攻击造成的伤害值虽然不大，但能继续让它失去平衡就是一件好事。青蛙就这样往后仰，从背部落到水里。

虽然想着「得继续攻击才行！」，但我和莉兹、莉法都还没从后仰状态恢复过来。青蛙不停摆动短短的前脚与强壮的后腿，看来立刻就可以起身了。诗乃也还在装填子弹，没办法再次开火。

刚才的连携几乎是偶然之下的产物，应该无法确实重现吧。这时候错过追击的机会，胜利将大大离我们远去。我咬紧牙关拼命想要站稳身体。将左手往前伸，以手指抓着空气，但虚拟角色还是无情地往后仰──

「叽咿咿！」

这个时候传出一道尖锐的吼叫声。

那不是青蛙的叫声，也不像哪个伙伴发出的声音。虽然焦急地想着难道又有新的怪物涌出，但从后方冲出来的并非两栖类。娇小身体包裹在简陋的服装底下，两手握着生锈草叉的是已经完全从我脑袋里面消失的三名鼠人。

他们跑向翻倒的Goliath rana，手里的草叉深深地陷入青蛙苍白的腹部。

「呱咕哦！」

发出愤怒咆哮的青蛙全身剧烈收缩后一直线后仰，然后用像弹簧一样的动作起身。鼠人们叫着「NN！」，然后逃回巨蛋外围。

看来他们并非正式参战，但愿意帮忙追击就已经是谢天谢地了。青蛙的HP条总计减少了四成，一开始全是白色的HP条变成了深黄色。

起身的Goliath rana溅起水花跳着贴在墙壁上并且开始攀爬。一屁股坐到地上的我和莉兹、莉法急着站起身子，准备闪躲青蛙的跳水攻击。

看来Goliath rana是「很难瞄准弱点，一旦成功就能削减大量HP」类型的怪物。只要再两次，幸运的话再一次成功让它翻倒就能获胜。为了办到这一点，首先必须对它的嘴巴造成伤害才行。

「诗乃，帮忙瞄准那个家伙的嘴巴！」

听见我的指示后，完成装填毛瑟枪的诗乃就回应「了解了」。我接着又对莉兹贝特喊道：

「那家伙要是开始跳水攻击，莉兹就不管三七二十一用锤矛轰它的头！虽然会被弹开，但这样就能诱发舌头攻击……应该啦！」

「应该啦～～？」

莉兹贝特虽然绷起脸，但也只有极短暂的时间。她重新握好钢铁锤矛，气势十足地大叫：

「没办法了，就试试看吧！」

像这种必须紧绷神经的战斗，有莉兹贝特这种开心果般的存在很是令人放心。我一边想着「只有这个真的没办法模仿」一边做出第三道指示。

「莉法、结衣、小黑等青蛙翻倒就用最大威力的剑技轰它！注意不要被后腿踢中了！」

「交给我吧！」「好的！」「嘎呜！」

听见两人一兽发出干脆的回应后，我就瞄了墙壁边一眼并且做出最后的呼唤。

「也拜托你们发动跟刚才一样的攻击！」

对象是三名鼠人。虽然没有回答，但还是相信他们能听懂并且把视线移回巨蛋上部。Goliath rana已经爬到墙壁的七成左右。随时都可能发动跳水攻击了。

「下次一定要确实躲过」，下定这种决心的我紧紧瞪着青蛙。它四肢的动作停了下来。突出的眼睛发出红光。

但下一个瞬间就发生料想不到的现象。

Goliath rana背上出现五六个像是藤壶般的隆起，然后从该处喷出鲜红火焰。火虽然立刻变小，但没有消失而是持续晃动着。没有时间想那究竟是什么，青蛙就朝着巨蛋底部张开嘴巴。

双方距离有二十五公尺以上。就算青蛙的舌头再长也无法攻击得到……当我这么想时，整个张开的嘴巴前面就出现发出红光的圆。圆形里面画着某种复杂的图样。

「魔法阵……？」

莉法以紧绷的声音掩盖了我的呢喃。

「大家快躲开！」

当她话还没说完时，青蛙口中就发射出巨大火球。我本能地往右边跳跃，抱着结衣扑进附近的水面。

轰然巨响。视界染成红色。背部遭到热浪袭击，HP开始慢慢减少。

爆炸才刚结束，我就抱着结衣站了起来。

「大家都没事吧？」

结果诗乃、莉兹贝特、莉法同时做出肯定的回应，小黑也发出强力的吼叫声。青蛙发射的火球命中巨蛋底部的中央，将该处的一个水洼蒸发掉了，不过没有伙伴被直接打中。退到墙边的三个鼠人也平安无事，但全部都一屁股坐到地上。

往上一看之下，Goliath rana依然贴在岩石上鼓缩着喉咙，看起来暂时没有下来的打算。

「……青蛙加上火，不就跟对蛞蝓洒盐一样吗……」

我一这么咒骂，莉兹贝特就说「你又随便乱用惯用句……咦，没用错耶」。我的国文能力虽然获得评价，但是战况却相当严苛。我方的远距离攻击手段只有诗乃的单发毛瑟枪，青蛙要是持续从天花板发射刚才的爆炸火球，我们将会逐渐陷入困境。

其实也不是非得打倒青蛙才行，只要能跟诗乃一起从基幽鲁平原的东侧离开就可以了，但我们通过的洞窟入口在巨蛋很上面的地方，所以必须从墙面的斜路爬到那里才行。而青蛙不太可能会眼睁睁让我们离开。

斜路……

「……各位，我会爬到墙壁的斜路然后跳起来以剑技把青蛙轰落，你们就以刚才的程序进行追击！」

直接把想到的点子说出口，伙伴们脸上就同时露出不安的表情。

「这么做的话哥哥也会掉下来喔。从那种高度坠落的话可能会死掉耶……」

我坚定地否决了莉法的担心。

「别担心，只要掉到水深的地方就不会受伤。只剩这个办法了。」

「…………」

莉法虽然闭上嘴巴，但是绿色眼睛里依然渗出担心的情绪。实际上，我也无法确定是否能掉到水深充足的地方。

当我为了实行这赌运气的作战而准备放下右臂抱住的结衣时──

「爸爸，这个任务就交给我吧！」

听见结衣突然做出这样的宣言，吓得我瞪大了双眼。

「等……等等，但是……」

「爸爸是小队里攻击力最高的成员，应该负责的不是初击而是追击才对。」

「但是结衣还无法使用音速冲击……」

「先进到洞窟里然后助跑的话，垂直斩也能击中对方！」

「但是……」

结衣一直凝视着不断发出逆接接续词的我，说道：

「爸爸，我不愿意只是被保护。」

「…………」

结衣的表情相当严肃，我突然感觉她很像亚丝娜。自己或许看不出来，不过大概也有点像我。

「……好吧。拜托你了。」

这么对她说完，把娇小身躯放到地板上的同时，稍远处的诗乃就放声大叫：

「开始动了！」

往上看向巨蛋的天花板，就看到Goliath rana正慢慢地往水平方向移动。第二次的火球攻击应该马上就要来了吧。爬上斜路途中的结衣也可能成为目标。

这时莉兹贝特的声音吹散了我的担心。

「我会让它盯上我，让结衣出发吧！」

坚定地这么说完后，她就以锤矛敲打圆盾。从盾牌发出些许波纹般的特效，应该是我不知道的时候获得的挑衅系技能造成的效果吧。

移动的Goliath rana停了下来并且改变身体的方向。

「我出发了！」

结衣大叫完就一只手拿着短剑开始奔跑。以连我都感到惊讶的速度跳过岩石与水洼，抵达墙壁的斜路后就毫不犹豫地冲上去。

青蛙用力举起上半身，大大地张开嘴巴。它明显是以莉兹贝特为目标。

「大家快离开！」

我遵从莉兹贝特的指示退后，同时开口大叫：

「莉兹，你要好好躲开啊！」

「相信我做的盾牌吧！」

这难道是……当我这么想的瞬间，Goliath rana的口中就出现红色魔法阵并发出炫目光芒。

震动的空气发出「咕啊！」一声，炽烈燃烧的火球发射出来。但是莉兹贝特没有移动。她以左手高举起圆盾，右手的锤矛则撑在盾牌后面。

那面盾牌是熔化黑色鞭痕后出现的「高级钢铸块」作为素材。加上制作者莉兹贝特的打铁技能熟练度，应该具备相当高的防御力才对。但就算是这样，实在不认为能毫发无伤地挡下应该属于练功区魔王的Goliath rana所发射的火球。

我的右脚震动，自行准备往地面踢去。但我却用右手抓住膝盖附近，拼命地把它压抑下来。这时候要是冲出去然后被卷进爆炸里面的话，应该追击时可能会无法起身。只能相信莉兹以及结衣的决心继续沉住气了。

直径应该有五十公分的火球直接命中圆盾，一边扭曲一边放射强烈的光芒。最后开始冒出红色火焰与黑色烟幕，直接掩盖莉兹的身影。爆炸的冲击波袭来，我随即用双手遮住脸庞。

视界左上方莉兹贝特的HP条开始减少。七成、六成，瞬间剩下不到一半……在剩下四成时停止减少。

「莉兹！」

抬起脸来这么大叫后，在爆炸中央蹲下来的莉兹贝特就举起右手并且竖立大拇指。明明可以冲刺躲开爆炸的她之所以刻意选择防御，应该是为了绝对不让火球朝着结衣发射吧。

这个时候结衣已经几乎爬完呈螺旋状沿着巨蛋外围的斜路。就连我也很难在毫不畏惧的情况下全力冲上那条没有扶手的狭窄通道。但是结衣却能发挥出那样的速度，这并非因为她是AI的缘故，而是她花时间培育出来的真正心灵与勇气所带来的结果。

到达斜路最上方的结衣，为了争取助跑距离而冲进墙面的洞窟内。

「呱咕哦……」

发出低鸣的Goliath rana回转身体准备面向洞窟。糟糕……要是它用舌头迎击，结衣会在空中被击落。

「这边喔！」

这么大叫的是诗乃。装填好毛瑟枪后，她立刻对着贴在天花板上的青蛙扣下扳机。打火石溅出火花，隔了一拍后传出轰然巨响。

发射出去的子弹命中Goliath rana的右眼。

「呱咕咕哦！」

发出悲鸣的青蛙再次开始转变身体的方向。

下一刻，一道纯白人影从洞窟里飞出。

拖着长长黑发，短剑举在右肩。剑身虽然带着蓝色光辉，但是正不停地闪烁。对于不曾练习过的结衣来说，在姿势不稳定的状态下于空中发动剑技是高难度的技巧，但是特效光还是在千钧一发之际保持了下来。

「呀啊啊！」

勇敢的喊叫声传到了地面。以右脚踩踏空气，结衣发动了「垂直斩」。系统辅助让娇小的身体加速，短剑在淡淡黑暗中画出鲜艳的轨迹。剑尖陷入青蛙的侧腹部，虽然无法撕裂皮肤，但四肢的吸盘已经因为冲击而脱离吸附的岩石。

青蛙皮肤足以媲美橡胶的反弹力把结衣大大地弹飞出去。青蛙也在四肢胡乱挥舞的情况下掉落。

结衣能够掉在水里的话就没关系，但掉在岩石上的话就会死亡。要是去接住她的话，就来不及追击青蛙了。

在开始战斗之后最大的焦虑袭击下，我的耳朵听见一道生疏──不对，是莫名熟悉的声音。

「小结衣就交给我吧！」

──虽然不知道是谁但就交给你吧！

在心中这么向对方大喊后，我就进入目前能使用的最大威力剑技，三连击技「锐爪」的准备动作。旁边的莉法也准备发动同样的剑技，从爆炸伤害中恢复过来的莉兹贝特也举起锤矛，诗乃此时拿的并非毛瑟枪而是小型雷射枪，小黑也露出了尖锐的牙齿。

掉落下来的Goliath rana从背部猛烈撞上一根石柱并且大大地反弹起来。当它再次掉落在地面的瞬间，我就开口大叫：

「──就是现在！」

我、莉法、莉兹贝特、小黑从四面八方对青蛙毫无防备的腹部挥出剑、锤矛与利牙。青蛙的HP瞬间大量减少，最后剩下不到两成。四个人才刚离开，鼠人们就随着尖锐叫声冲过来以草叉突刺。

HP剩下一成。

我抵抗着发动剑技后的行动延迟，想要以普通攻击结束青蛙的生命。但依然翻倒的青蛙却快了一步张开嘴巴。

「呱咕咕咕哦哦哦────！」

愤怒的咆哮产生大型的魔法阵。糟糕，在这种极近距离之下，它要是发射火球就躲不开了……

「别作梦了！」

诗乃发挥恐怖的蛮勇，直接冲到青蛙正面。右手的雷射枪伸入魔法阵当中然后扣下扳机。

黄绿色能源弹随着「咻咻咻咻嗯！」的科幻世界般发射声不断被射入Goliath rana的嘴里。HP条一点一点减少。包裹诗乃手臂的魔法阵发出特别强烈的光芒。青蛙口中的火焰开始摇晃，接着呈漩涡状卷动，最后不再是火球而是龙卷风……

HP归零了。

「呱咕咕！」

在短短死亡悲鸣响起的同时，深红魔法阵也变成黑烟并且烟消云散。与ALO里咏唱魔法失败时的现象十分类似。

巨大身躯不停痉挛，然后渐渐脱力……最后完全静止。

SAO或者ALO里的话，死亡的怪物会变成蓝色多边形然后爆散，但这个世界尸体会直接留下来所以无法立刻解除警戒。虽然担心结衣，但首先要确认青蛙是不是死透了，于是我就举着剑往前走了一步。

这个时候，发生了奇妙的事情。

某种发出红光的物体从翻倒在地上一动也不动的巨大青蛙心脏附近浮上来，在淡淡黑暗中轻飘飘地上升。至今为止打倒过差不多强大的尖刺洞熊等许多怪物，但是从未见过这种现象。

「桐人，那个……！」

像是被诗乃的声音推动背部一样，我跑了两步后就全力跳起，朝着红光伸出手。但是指尖触碰到的瞬间，光芒就跟泡泡一样破碎并且消失。着地之后看向左手，但手掌里什么都没有。

突然间，小队成员所有人都包裹在蓝色环状光芒底下。一瞬间还焦急地以为是什么陷阱，但立刻就发现是升级的演出。看来青蛙确实已经死亡了。眼前浮现传达升上等级16的讯息，不过我只是急忙关上讯息并且仰望上空。

在微暗当中那身白洋装也相当显眼的结衣就挂在洞窟入口的正下方。某个呈倒栽葱状态的人抓住她纤细的左手。该名玩家的右脚上绑着绳子，而像门神般站在洞窟入口处的另一名玩家则拉住绳子。

挂在空中的结衣与身份不明的闯入者正左右缓缓摇晃，微微可以听见的摩擦声──是绳子无法支撑两个人的重量，已经快要断裂的声音。

站在洞窟入口处的高大男人开始一点一点拉起绳子。我急忙冲向结衣的正下方，同时对着上空大叫：

「喂，别逞强啊！」

下一个瞬间，拉绳子的男人发出的浑厚声音就传了下来。

「绳子不够长无法放到地面，这样下去耐久度只能再撑二十秒而已！」

听见这段话后有所反应的是抓住结衣手臂的另一个男人。

「大哥，不会到这个时候才让我摔死吧！快想办法拉我们上去！」

──感觉两道声音都相当熟悉。

把这种既视感，不对，是既听感丢到一边后，我就以双脚来紧急煞车。就算在正下方等待，也无法同时接住结衣和另一名男人。如此一来就只能准备垫子了，但光凭收在道具栏里的鬣狗毛皮，应该无法吸收从那种高度掉下来的伤害吧。

现场唯一能够当成垫子的物件就只有一个。我转身全力跑回去，然后对莉兹贝特她们叫道：

「大家快过来帮忙搬！」

我这么叫完后就抓住的是横躺在地面的Goliath rana的右脚。所有人似乎立刻就察觉我的意图，诗乃来到我前方，莉兹贝特与莉法扑向左脚，四个人开始拼命拉起巨大的尸体。

小黑低吼了一声后也咬住青蛙的侧腹来帮忙移动，甚至连三名鼠人都丢下草叉来帮忙推头部。一旦有了势头，青蛙的巨躯就以超乎想像的速度在湿濡的岩石上滑动。一边全力拖行一边看向后面，发现距离洞窟大约十公尺的结衣他们已经上升到一半左右，不过也看得出绳索的损耗相当严重。

到两人的正下方还剩下一点距离时……「啪叽！」的无情声音响起。

「桐人，抱歉！想点办法吧！」

如此大叫的是试着拉起绳子的巨汉。根本没有时间对他叫出我的名字感到不可思议。

「喔哇啊啊啊啊！」

另一个男人则发出有点丢脸的悲鸣掉了下来。但是在掉落中还把结衣的身体拉近，抱住她后让自己的身体变成在下方，真是很有男子气概。这样的话，我们也该有所回报才行。

「喔呀啊啊啊！」

我边叫边挤出最后的力量。眼前浮现【强健技能的熟练度上升为4】的讯息，青蛙的尸体稍微浮上空中。最后掉进水洼里停了下来。

一秒钟后，男人与结衣就掉了下来并且陷入Goliath rana的腹部。即使变成尸体依然具备橡皮般的弹力，两个人啵一声反弹了一公尺以上才再次落下并且静止。

「爸爸！」

吊在空中甚至是掉落时都完全没有发出声音的结衣，这时候伸出双臂飞扑了过来。我接住她娇小的身躯后，就在注意不让金属铠压迫到她的力道之下紧抱住她。

「你真的很努力喔。能空中发动『垂直斩』实在太了不起了。」

这么对她呢喃完，开始和Goliath rana战斗之后结衣的声音首次出现动摇。

「……是的，我真的很努力！」

对于至今为止都没有战斗过的结衣来说，练功区魔王战的恐惧与压力应该超乎我的想像才对。那绝对不是身为AI的结衣能够利用学习就模仿出来的拟似感情表现。现在的结衣已经超越Top-down型AI的界限，获得了真正的感情……我是这么相信的。不是这样的话，她为什么能够实行牺牲自己的作战呢？

当我沉浸在这样的感慨中不断抚摸结衣的头发时──

「哎呀呀……真是九十九死一生耶……」

嘴里说着奇怪谚语，呈大字型躺在青蛙肚子上的男人起身了。

以红豆色头巾将短短茶色头发竖起。头巾下面的脸庞略长，下巴还长了一小撮胡须。防具是皮革制，左腰则挂着弯刀。

从一开始听见声音时，我的心中就反覆想着「说不定」和「不可能吧」的想法，但是看起来「说不定」这一边才是事实。

「……克莱因，你在这里做什么啊？」

于是我先这么提问，结果从SAO时代就认识的刀使，不对，是弯刀使就摊开双手如此抗辩。

「喂喂喂，这样太过分了吧，桐字头的老大！就是觉得你们会很辛苦，我才急着赶过来帮忙的耶！」

「那真是谢谢你了。」

莉兹贝特插嘴这么表示。

「你怎么会知道我们在这里？没有人在现实世界跟你联络吧？」

「关于这一点就由我来说明吧。」

从上方传下来这样的声音，于是我们就一起抬起头来。

一名有着雄伟身躯，顶着一颗光头而且面容凶恶的男性玩家慎重走下沿着巨蛋外墙的斜路。那是同样是彼此相当熟的斧使兼商人艾基尔。但是背上看不见成为他注册商标的双手用大斧，而是将一把较小的──即使如此依然比我的剑大上许多──双刃斧插在左腰。防具跟克莱因一样是皮铠。

「哈啰，艾基尔。」

和来到地面的巨汉轻轻互碰了一下拳头，顺便也跟克莱因打了同样的招呼之后，我才再次问道：

「那么……你们是怎么到这里来的？你们两个人也跟其他ALO玩家一样是从南方的遗迹开始游戏吧？」

「嗯。而且我和克莱因还慢了一天。今天傍晚好不容易登入进来一看，缓冲期间早已经结束，附近的练功区也被狩猎殆尽……好不容易跟克莱因会合之后，就想前往你的圆木屋……」

「咦，你们也不知道圆木屋的位置吧？」

「亚丝娜传了手绘地图给我们。」

「哦，是这样啊……」

不愧是前KoB副团长大人，做事真是细心……当我像这样感到佩服时。

「我看桐字头的老大早就忘了我们吧。」

依然坐在青蛙肚子上的克莱因发出愤恨的声音。虽然他说得一点都没错，但是当然不能点头承认。

「没……没有啦，我怎么可能忘了你们。哎呀，因为克莱因跟艾基尔平日都要工作……所以就想等状况稳定下来后再跟你们联络……」

下一刻，艾基尔就双手抱胸并且说道：

「我的店今天休息喔。」

接着克莱因也说：

「我今天下午也请了假。」

「Dicey Cafe是不定期店休，而且我怎么可能知道克莱因今天下午休假呢！」

当我们这样互相争辩时。

进行着毛瑟枪装填作业的诗乃就轻轻干咳了一声。

「可不可以继续说下去了？我也有许多事情要忙。」

「哦，抱歉抱歉。」

艾基尔道歉完就把话题拉回来。

「然后我们在弄到最低限度的装备后就从遗迹出发到森林，在那里突然被PK三人组袭击。我们是石头武器对方是铁制武器，防具也有差异，本来以为完蛋了。」

「这时候靠得就是我跟大哥磨练出来的合作默契了，从左右两边轻轻松松就把那群PK家伙给解……」

艾基尔以低沉浑厚的声音打断克莱因气势十足的发言。

「喂，你这家伙只是躲在后面吧。」

「有什么办法嘛，本大爷继承的技能是……」

但这时候克莱因就不自然地闭上嘴。我一边想像应该是「继承了熟练度封顶的大刀技能所以不适用于弯刀」，一边把视线移到艾基尔身上。

「那你们击退PK了吧？」

「嗯……那群家伙似乎是临时凑在一起的三人组，所以完全没有合作默契可言，好不容易才打败他们。不过一时忘记缓冲期间已经结束，不小心用范围剑技一次把他们三个人全部干掉了……」

艾基尔说着就绷起脸来。完全将「心地善良的巨人」具现化的他，如果PK三人组逃走的话应该是打算放过他们吧。靠过来的莉法拍了拍他粗壮的手臂。

「不用难过啦，艾基尔先生。PK们应该也有可能会遭到反杀的觉悟了，我们昨天也受到PK集团的袭击，但是桐人毫不留情地把他们全干掉了哟。」

「喂……喂喂，可不是我一个人打倒他们全部的喔。」

急忙做出这样的注释后，才又说「然后呢？」催促艾基尔说下去。咧嘴露出笑容的艾基尔轻轻拍打了一下乌亮的皮铠。

「很幸运的是PK家伙们掉下这件皮铠、铁斧和弯刀，我们就心怀感谢地拿来使用了。靠着地图好不容易抵达圆木屋，亚丝娜就说担心桐人你们，拜托我们两个前来帮忙。」

「原来是这样啊……」

在心中感谢自己的伴侣后，我又微微歪着头说：

「等等，但是亚丝娜她们也不清楚我们的移动路线吧？艾基尔跟克莱因是怎么来到这座洞窟……？」

当我重新提出这个疑问，艾基尔就再度咧嘴笑了起来，然后用下巴指了指克莱因。刀使，不对，是弯刀使隔着头巾搔了搔脑袋，像是下定决心般开始说道：

「关于这一点嘛，其实是靠我的继承技能……」

「啥？你继承的是大刀技能吧？那跟来到这里有什么关系？」

我脑袋里也想着跟莉兹贝特完全相同的问题，我看莉法和诗乃应该也是一样吧。集所有人视线于一身的克莱因，脸上浮现难以形容的表情说道：

「不是大刀喔。」

「啥？」

「我继承的是『追踪』。」

「啥啊？」

所有人同声大叫了起来。

ALO的追踪技能可以让玩家或怪物的足迹浮现，而且比较容易找出属意的素材道具，算是相当方便的技能，但是修练需要相当有耐性，所以没有什么玩家会特别去锻炼它。但克莱因应该把大刀技能的熟练度提升到封顶的1000了才对，从继承技能不是大刀来看，他追迹技能的熟练度也封顶了吗……

「你为什么要锻炼那种技能的熟练度……」

原本以傻眼口气这么呢喃的莉兹贝特，像是发现了什么般大叫：

「啊，你不会是想靠它追踪可爱的女孩子吧？」

「才……才不是哩！我呢，是为了攻略诗寇蒂小姐给我的追逐任务才会……」

「…………啥？」

除了艾基尔以外的所有人再次发出这样的声音。

诗寇蒂是在阿尔普海姆地底下的广大幽兹海姆遭遇的NPC。她是让人联想到北欧神话女武神的英挺美人，话说回来，我记得临别之际克莱因好像从她那里拿到了什么。那个物品是开始任务的道具，而要攻略任务就需要将追踪技能练到封顶……事情应该是这样吧。

「……那么，你顺利攻略那个任务了吗？」

听见我的问题后，克莱因就以充满悲伤的表情摇了摇头。

「还差一点就要结束了……但是现在却变成这样……诗寇蒂小姐她不知道是不是平安无事……」

顺利完成那个追踪任务的话究竟会发生什么事呢……我先把这个疑问吞回肚子里，直接把话题拉回来。

「也就是说，克莱因用继承的追踪技能来追上我们吗？但是熟练度不是调降到100了？亏你们还能追踪到这里耶。」

「嗯，还好啦……熟练度100的话没办法选择特定玩家的足迹来加以追踪，但残留在这片平原上的就只有一个小队人数的足迹。我想这应该就是桐字头的老大你们，所以才追到这里来。」

「原来如此……」

终于了解事情来龙去脉的我，再次向艾基尔与克莱因低下头来。

「真的帮了我们大忙。不是艾基尔跟克莱因帮忙接住的话，结衣就跟青蛙一起坠落了。」

「艾基尔先生、克莱因先生，谢谢你们！」

结衣也轻轻点头行了个礼，结果两名好汉就同时浮现害臊的笑容。

「如果能赶上战斗就更好了。」

艾基尔一这么说……

「哎呀，我不喜欢对付那种滑溜的怪物啦～」

由于克莱因以看起来不像是在开玩笑的表情这么说道，我便指着弯刀使盘腿坐着的代用垫子说：

「但那是青蛙的尸体喔。」

「咦？……呜唷哇啊啊啊啊！」

看见发出悲鸣并且灵巧地直接从盘腿状态垂直跳跃的克莱因，连诗乃都忍不住笑出了声音。

** 第九章

和诗乃一起战斗的三名鼠人是Unital ring世界里名为「帕特鲁族」的少数民族，仅仅只有一百人左右居住在这个境界壁内部的洞窟。

诗乃在这座洞窟里遭遇到他们，然后从懂得人族语言（也就是日文）的长老那里听说了帕特鲁族的历史。根据历史，很久很久以前帕特鲁族曾在基幽鲁平原北部建立了雄伟的都市，但是却因为恐怖的天地异变而一夜消灭，残余的生存者们也被在平原肆虐的巨大肉食恐龙驱赶，最后变成只能在墙壁的洞窟里面生活。

帕特鲁族有越过墙壁后，在遥远东方土地有一片肥沃森林的传说，一部分年轻人虽然想要移居到那片森林，但是想穿越墙壁东侧就必须通过潜伏着狰狞巨大青蛙的巨蛋。过去有许多勇猛的战士挑战青蛙，但是全部遭到杀害，包含长老在内的年长帕特鲁族已经放弃越过墙壁的梦想。但是诗乃为了跟我们会合，不论如何都得穿越东侧，所以就和三名勇敢的──虽然是以帕特鲁族的基准来看──年轻人一起试着要打倒青蛙。

大青蛙也就是Goliath rana比听说的还要强大，倚赖的毛瑟枪效果不大，就连诗乃都考虑要撤退了。这时候我们四个人和小黑冲了进来，好不容易才打倒青蛙……诗乃说出了整件事情的经过。

不论如何，今天晚上最大且最后的目标「与诗乃会合」就这样成功了，虽然说是附加赠品可能有点过分，不过也顺利跟克莱因以及艾基尔会合，原本以为再来就只要从来时的道路回到圆木屋就可以了，但等着我们的却是意料之外的发展。不只是参加Goliath rana战的三个人，多达二十名帕特鲁族希望与我们同行。

「……桐人啊，这会是某种任务吗？」

莉兹贝特对着走在已经无法称为小队的大集团前头的我这么呢喃。

我考虑了一下后就摇了摇头。

「不……我想应该不是……刚才看过选单的任务标签了，上面没有写任何东西……」

「你觉得抵达森林之后就可以跟他们道别吗？」

「…………唔嗯唔。」

「在这之前，你觉得他们所有人可以平安到达森林吗？」

「…………唔嗯唔。」

「你的『唔嗯唔』是否定还是肯定？」

「两者皆是。」

「唉……」一声大大地叹了一口气后，莉兹贝特就对走在旁边的莉法说：

「莉法啊，你哥哥不要紧吧？」

「啊哈哈……哥哥有时候会退化成小孩子……」

虽然被说得很难听，但现在连抗辩的时间都没有了。因为自从帕特鲁族的二十人表示想要同行开始，我就专心一志地思考着究竟该怎么做才能让一切顺利。

虽然没办法对莉兹的问题做出确定的回答，但我不认为帕特鲁族们能够在圆木屋所在的森林──他们称为「赛鲁耶提利欧大森林」──存活下来。该处的水源与食物虽然丰富，但也因此而怪物众多，要是遇见应该比Goliath rana更强大的尖刺洞熊，二十人应该就会全灭了吧。

目前仍未检验过这个世界的NPC死亡后会出现什么样的情形，说不定经过一定时间后就会复活，但即使是这样也不能丢下他们不管。没有只靠草叉就拼命战斗的三个人就无法打倒Goliath rana，也就不能像这样跟诗乃会合了。

但是话又说回来了，实在没办法让二十名帕特鲁族都住进圆木屋里。从面积来看或许刚好能塞得进去，但是我方的人数也增加了，将会形成无法躺下来睡觉的超拥挤状态。该怎么办才好呢……当我一边烦恼一边往后面瞄，就看见跟诗乃并肩走在一起的结衣。

能够再次相遇似乎让她很开心，她紧握住诗乃的左手，带着笑容热烈地谈着天。虽然应该不可能有这种事，但是感觉她似乎长高了一些，这可能是因为她今天展现了身为剑士的醒目成长的缘故吧。虽说她本人表示想成为魔法师，但是感觉跟「才智」比起来，或许取得「刚力」或是「俊敏」的能力比较好。说起来呢，游戏开始到现在已经过了一天半的时间，到现在连魔法的习得方式都还不知道。

当我想到这里时，突然浮现某个想法，于是急忙叫出了环状选单。

我移动到道具栏标签，将内容排序改为入手时间，最上面就出现生疏的道具名称。

「火之魔晶石」。

击点这让人雀跃不已的名字后叫出了属性视窗。道具名跟耐久度底下显示了简短的说明文。【凝固火之魔力后生成的结晶石。能够习得火魔法技能。已经习得的话熟练度将略为上升。】──

出现啦──！

虽然想这么大叫，但是会让神经质的帕特鲁族吓一大跳，所以还是忍耐了下来。他们连对走在我前面的小黑都感到有点害怕了。

火之魔晶石是什么时候进到我的道具栏已经很明显了。从Goliath rana的尸体浮上来的红光……抓住那个的瞬间，它就直接收纳到我的道具栏里了吧。

尖刺洞熊的尸体没有出现光芒，Goliath rana的尸体却出现光芒的理由。是因为那只青蛙使用了魔法的缘故。也就是说，要在这个世界习得魔法技能，就必须打倒使用该种属性魔法的怪物。还不清楚只要杂兵怪物即可，或者必须是某种程度的魔王怪物才行。

继续击点持续显示着的属性视窗，Tips视窗就随着叮铃铃的声音出现了。

【要使用本道具，需要将其实体化后放入口中咬碎。】

「…………」

虽然是相当狂野的使用方法，但只要想到是从怪物身体里浮现就也不是不能接受。消除Tips后，我就按下属性视窗下部的实体化按键。

实体化后的魔晶石不像接住时那样的无实体光芒，变成直径一．五公分左右的透明宝石。颜色是鲜艳的深红，中央部分封闭着小小火焰。把它像糖果一样咬碎之后应该就能习得火焰魔法，但我当然没有放进自己口中，而是转头把它递给结衣。

「来，结衣。这个给你。」

「……？这是什么？」

歪着头接过魔晶石的结衣以认真的表情看着它之后就笑着说：

「哇，好漂亮啊！这个要给我吗？」

「嗯。」

「谢谢爸爸！我会珍惜它的！」

「不，我不是要你保留……你放到嘴里吃吃看吧？」

「…………什么？」

这时不只是结衣，连诗乃、莉兹贝特与莉法都露出疑惑的表情。虽然是应该把事情从头到尾说明一遍的场面，但最后还是输给希望把魔法技能当成惊喜礼物的欲求，没有说明就催促起结衣。

「吃吃看就知道了，试着把它咬碎吧？」

「…………」

结衣虽然露出跟亚丝娜对我的言行感到怀疑时完全一样的表情，但还是乖乖地把宝石放进嘴里。鼓起脸颊在嘴里滚了一阵子后，才以模糊的声音说：

「爸爸，没有任何味道。」

「喂，桐人。真的不要紧吧？」

拍胸脯对瞪着我的诗乃做出「不要紧不要紧」的保证后，又把视线移回结衣身上。

「结衣，不是用舔的，直接把它咬碎。」

「……好……好的。」

结衣露出有所觉悟的表情，以右侧的牙齿咬住魔晶石，然后闭上眼睛用力咬下。结果没有出现我预想的「喀哩」声，反而传出了「啪铿───」的尖锐清澈声音──

突然间，从结衣的嘴里喷出鲜红色火焰。

「呼哇啊啊啊啊！」

结衣因此发出悲鸣，而我惊讶的程度大概是她的一半，不过她的HP没有减少。莉兹贝特大叫「火灾火灾火灾」，然后准备让结衣喝水，但这个时候火焰已经熄灭了。

「哥哥！这样的恶作剧实在太过分了！」

我急忙对举起拳头的莉法用力摇头。

「不……不是啦！结衣，应该出现习得的讯息了吧？」

「呼哇啊……啊，出现了……写着习得了火魔法技能……咦！」

瞪大双眼的结衣以眼睛看不见的速度打开环状选单，然后移动到技能标签处。敲打习得技能一览表的最上方，瞥了一眼打开的视窗──

「哇啊，好像可以使用名为『火焰箭』的魔法！」

诗乃等人以哑然的表情凝视着发出兴奋声音的结衣。我露出满意的笑容，然后催促心爱的女儿说：

「马上用用看吧。」

「好的！这个世界的魔法和ALO不同，似乎只要用手势就能发动。嗯……」

从视窗上抬起头的结衣，把娇小的双手举到身体前面。

「首先这是火属性魔法的基本手势。」

伸直五只指头的右手从斜上方贴在握拳的左手上。结果两手都出现淡淡红色气息。

「以接下来的手势指定发动的魔法。」

一边打开左手一边将其往正前方伸去，以拉弓般的动作将右手移动到肩膀上方。结果一条发出微弱光芒的红线就像是要连结双手般出现了。结衣迅速环视周围，把左手朝向前方二十公尺左右的岩石。

「然后这是发动的手势。三个手势的动作与节奏越正确，魔法的威力与命中准度似乎就越高。」

她打开的双手同时用力握紧。在她左手前方展开了小小魔法阵，红色光线变成了火焰箭，随着「咻砰！」的声音发射出去。画出平缓抛物线轨道的箭准确地命中岩石，引发了轻微的爆炸。我们发出「喔喔！」的感叹声并且拍手。原本以为帕特鲁族会感到害怕，但他们似乎没有胆小到那种地步，正发出吱吱的声音似乎在谈论些什么。

虽然威力和华丽度远远比不上ALO里大师等级的魔法师们使用的高位魔法，但在这个世界里除了Goliath rana的火球之外首次见到的魔法还是给了我很大的勇气。而且魔法技能似乎不只有反覆使用才能提升熟练度，摄取魔晶石也能达到同样的效果，看来有许多地方比武器技能更加有趣。我将来也想习得魔法，不过目前还是先辅助结衣的成长吧。

「结衣，刚才那支箭减少了多少MP？」

「呃，我最大的MP是157，现在减少了15所以大概是一成左右。」

「唔嗯唔嗯……自然回复的速度呢？」

「『集中』能力在等级1的状态下，回复1点需要花六．二秒。计算起来要回复一发『火焰箭』分量的MP得花上九十三秒，所以不太能够连发……」

结衣说完就伏下眼睛，我则是搔了搔她的头部。

「不需要沮丧喔，光靠自然回复的话大部分的游戏都是这样。我想应该马上就能入手MP回复药水，或者是能从素材调合出药水。」

「如果是这样就好了……」

「这方面我一定会想办法，结衣你不用担心。总之只要MP完全回复就使用魔法，尽量提升技能熟练度吧。」

「好的！我会努力！」

看见终于露出笑容的结衣，莉法也以元气十足的口气表示：

「好，我也要快点习得风魔法！桐人啊，如果入手风魔法的石头要送给我喔！」

「是是是。吃下风之石嘴里不知道会跑出什么喔～」

只不过是说出单纯感到疑惑的问题，没有装甲的左侧腹就被莉法用力戳了一下，我则是夸张地发出「呜咕」的苦闷声响。下一刻，和艾基尔一起担任庞大小队殿后工作的克莱因就从后方传来这样的呢喃。

「唉～结果在Unital ring也是这样吗～」

跟来时相比，从基幽鲁平原往东走回去的回程可以说平稳到让人难以置信。或许是因为知道路径，以及前方有欢乐的家在等着的安心感所致吧，众人甚至有欣赏风景的心情。

虽然还是经常有鬣狗与蝙蝠发动攻击，但我们的战力已经增强许多，因此能顺利击退它们，也没有再受到那阵恐怖的冰风暴袭击。最担心的事项也就是水与食物，也靠着肢解Goliath rana入手的大量青蛙肉以及洞窟大量涌出的泉水获得充分的补足──虽然女孩子们对于烤蛙肉似乎没有什么食欲就是了。

幸运的是洞窟内不只有水和食物，也采取到大量的铁矿石与铜矿石。这些矿石就交给不愿意将蛙肉放进道具栏的女孩子们，以及背负着小小背包的帕特鲁族负责搬运，回到据点后把它们熔掉的话，应该就能有好一阵子不缺铸块了。

时间经过二十二点三十分时，我们终于再次横越基幽鲁平原，来到赛鲁耶提利欧大森林的入口。再来就是在森林中走一阵子，渡过河川后就能回到圆木屋。

前方看见巨大树木的瞬间，二十名帕特鲁族就跳起来互相拥抱，其中甚至还有人哭了出来。对他们来说，赛鲁耶提利欧大森林是代代相传的「约定之地」，所以也难怪他们会如此兴奋了，但森林绝对不是安全舒适的理想乡。

请唯一习得帕特鲁语技能的诗乃传达还不能放松的讯息后就踏入森林当中。一边打倒种类完全变得不同的怪物一边专心往东前进，最后前方就稍微能看见摇晃的光芒。

「啊，是河！马上就要到家了！」

发出欢呼声的莉法快速跑了出去。

「别跑啊！河川里面也有怪物……」

我这么呼叫着她，然后跟小黑一起准备追上去，但是莉法突然紧急煞车，我也跟着急忙停下脚步。

「喂，你是怎么了……」

「哥哥，你看那个！」

我也往上朝莉法所指的方向看去。下一个瞬间，我就被心脏停止般的感觉袭击。

河川对岸一整排树木后方的夜空正炽烈燃烧着。我反射性叫出地图来确认位置。那个方向是……我们的圆木屋。竖起耳朵听之后，还能听见混杂在火焰爆炸声之中的些微金属声。闻到隐含在夜风内的焦臭味后，小黑就发出「咕噜噜……」的低吼。

「亚丝娜……西莉卡……爱丽丝！」

我快速呼唤应该守护着家园的三个人，然后开始拼命奔跑。莉法跟莉兹贝特等人也跟在后面。

冲过覆盖着大小石头的河岸，选择浅滩处渡过河流。东岸的树林里残留着艾恩葛朗特断片落下时造成的一直线裸地，圆木屋就在这个痕迹的前方。

来到这里后，就能清楚看见树木深处炽热燃烧的火焰。金属声──刀剑互碰的声音也清楚地传了过来。应该是受到某人，恐怕是跟昨天晚上的摩库立等人同样的PK集团袭击了。

虽然想立刻赶过去，但是必须先决定该如何处置二十名帕特鲁族。他们的防具是简陋的布衣，武器全是草叉、割草镰刀等有一半像是道具的东西，依Goliath rana战时所见整体的能力值大概是等级2或3左右。要是被卷入剑技此起彼落的混战里，很可能会出现死者。

「诗乃，告诉帕特鲁族的人躲在这附近！」

点头的诗乃虽然传达了我的话，但是帕特鲁族们短短交谈了两秒钟后就一起摇了摇头。虽然很难从圆滚滚的黑色眼睛读取感情，但是能从「NNN！」的叫声里感觉到他们的愤慨。

「……他们说『偶们也要战斗』。」

诗乃的翻译让我忍不住反问了一句「偶们？」，但是随即转念想着「详情之后再问吧」。虽然依然感到不安，但是没有时间鼓动唇舌来说服他们改变心意了。

「我知道了，那么至少告诉他们二十个人要聚在一起不要分散了。」

等待诗乃翻译完后，我就看向莉法、莉兹贝特、克莱因、艾基尔以及结衣的脸庞。

「虽然不清楚袭击者的身份与规模，但慢吞吞地进行侦查的话亚丝娜她们会有危险。只能趁敌人大意时冲过去，然后随机应变与其战斗了。」

「这种一次决胜负的战斗就交给我吧！」

克莱因拍了一下穿着皮铠的胸脯。这时候要是吐嘈「你继承的是『追踪』技能吧……」就太不给面子了。

迅速互相点点头后，我们开始跑了起来。

全速冲过从河岸往东北方延伸的裸地。前方立刻就能看见鲜红火焰。幸好燃烧的不是圆木屋而是围住圆形院子的旋松老树。在前往基幽鲁平原前大家一起建筑的三公尺高石墙与木制大门依然健在。

此时有银色光芒在那道石墙上闪烁着。是刀剑互击的光芒──亚丝娜她们在宽只有三十公分的墙壁上与袭击者交战。燃烧的树木底下有十名，不对，是二十名以上应该是玩家的人影不断冲向石墙并且往上攀登。对旋松放火应该是用来作为照明吧。

「锵！」特别激烈的金属声响起，其中一名袭击者从墙上滚落到地面。拖着栗色长发的亚丝娜迅速反转将手中的细剑朝爬上来的另一名袭击者刺去。稍远处也能看到爱丽丝与西莉卡正在奋战。看来她们三个人只是专心把敌人击落到墙外。

亚丝娜她们的意图很明显。拖延时间──相信我们和诗乃会一起来救援，在那之前只是持续努力想尽办法挡住敌人的入侵。

从旋松的燃烧状况来看，战斗已经进行三十分钟以上了。袭击者可以在地面休息，但是持续在狭窄立足点战斗的亚丝娜等人不要说HP了，就连精神力应该也快到达界限。当我死命奔跑并且这么思考着时，新的敌人又从亚丝娜背后逼近。西莉卡与爱丽丝都在跟眼前的敌人战斗而没有注意到。由于笼罩树木的火焰发出轰然巨响，就算在这里大叫声音也传不过去。

即使如此，我还是为了警告亚丝娜而在胸口吸满空气。

但是在发声之前，身后就快一步传出了枪声。

想要悄悄靠近亚丝娜的敌人像被弹开般后仰，踩了几步虚浮的脚步后掉到墙壁内侧。是诗乃用毛瑟枪进行了狙击。虽然技巧依然十分高明，但敌人跌入墙内的话，大门的门闩将会被打开。

结果一道狰狞的「咕哇！」吼叫声扫除了我的担心。那是阿蜥的叫声。亚丝娜的宠物长喙大鬣蜥似乎正在处理掉入石墙内的敌人。

毛瑟枪的发射声被旋松的爆裂声掩盖，敌人似乎没有注意到我们的存在。我用手势催促诗乃停下来再次装填子弹，并提升奔跑的速度。

与敌人集团的距离是十公尺。

「小黑，保护结衣！」

「嘎呜！」

一听见可靠的吼声，我就把右手的长剑举到肩上。

昨天的战斗当中，武器只有石头小刀，防具只有一件内裤的我对上PK时陷入了相当的苦战，但今天就不一样了。剑微微地震动并且带着黄绿色光芒。感觉到剑技发动的瞬间，我就用尽全力往地面踢去。这招是音速冲击。

这时终于有一名袭击者注意到我们的接近。

「喂，后……」

但零点一秒后，我的剑就深深地撕裂那个男人的左肩。所有袭击者应该组成了联合小队，所有敌人头上都显示出红色HP条。

我攻击的男人防具是皮革制，武器是铁制单手斧。虽然不清楚是从ALO继承还是从这个世界入手的武器，但是跟昨天的摩库立等人一样等级绝对不低。

即使如此，应该是「刚力」第5级以及「碎骨」第1级的效果吧，我的一击就夺走了男人八成以上的HP。被轰到地面又因为反弹而稍微浮起的男人，左胸被从后面飞来的橘色火线贯穿。诗乃的枪击──不对，是结衣的「火焰箭」。仅存的HP飞逝，男人再次倒到地面。环状浮标一边高速旋转一边巨大化，在原本HP条的位置刻上【00001：01：41：26】的数字。

一天又一个小时四十一分二十六秒。这就是这个男人在Unital ring世界存活的时间。

旋转的数字消失的同时，成为浮标中心轴的锐利纺锤形就往正下方射出，贯穿了男人的身体。失去灵魂的虚拟角色连同装备变形成无数圆环，圆环立刻分解成极薄缎带升上夜空。

这样的现象似乎成为了契机。

「敌袭！敌袭────！」

「从后方攻过来了！包围并且歼灭他们！」

附近拿着盾牌的玩家以及似乎是领队的长枪使依序这么大叫。

虽然被对方大叫敌袭实在有点不满，但是以言语沟通的阶段早已过去。袭击者们从呈弧形的石墙左右两边举起剑与长枪涌至。铁制武器大概占一半左右，其他都是石制武器。能够生产铁的话，应该会制作所有人的武器才会攻过来，大概是像摩库立他们那样，继承武器没有超过重量限制，或者是从哪里买来、捡来甚至是抢来的吧。

就算是这样，他们到底是从哪里入手圆木屋的情报呢？看起来不像跟摩库立等人一样是沿着河川北上才偶然发现。虽然没有确证，感觉像是知道这里筑起据点，在尽可能准备之后才往这里进攻。是遭到全灭的摩库立还是其伙伴为了泄愤而流出情报？但那群家伙看起来不像会做这种不会给自己带来任何好处的事──

在受到压缩的时间当中，耳朵深处再次响起摩库立的轻薄声音。

──这是老师的教导啊。不要只看对手的某个部分，要掌握全体。老师说……这样就能知道对方想做什么、讨厌什么了。

在一对一战斗中曾经将我逼入绝境的摩库立确实这么说过。老师……也就是指导摩库立对人战心得的某个人还存活在Unital ring世界里。如果是那个老师什么的在暗地里策动这次的袭击，那么二十名以上的敌人应该都对于PvP有一定熟悉度才对。

问题是那个老师的指导是不是只针对一对一互砍，还是也指导了集团战。不对，应该认为指导过集团战了。

在不到一秒钟的时间就想到这里的我，随即对伙伴们做出指示。

「冲进森林！别让那些家伙合作！」

但是艾基尔立刻大声叫着回答：

「不可能，森林里连地面都着火了！」

「…………！」

屏着呼吸的我迅速环视左右，燃烧旋松的火焰已经蔓延到草地，冲进那种地方的话一瞬间就会被烧死。

这时我才终于了解，袭击者们燃烧圆木屋周边的森林不只是为了照明，也是为了封锁游击战术。像是要印证我的推测一般，从左右两边涌至的敌人集团，最前面的是两名持大盾的坦克，左右两边是装备剑与斧头的攻击手，后方则是持长柄武器的减益手，可以说组成了范本一般的阵形。看起来没有魔法师算是不幸中的大幸，但就算是这样，状况还是一点都没有好转。

石墙上方的亚丝娜等人依然在奋战当中。亚丝娜一瞬间把脸朝向往上看着这种模样的我，两人互碰的视线就像爆出了火花一般。

看来亚丝娜也没有能够一举逆转的妙计，但可以感受到她传来绝对要守住我们家的坚强意志。残留在圆木屋的三个人相信我们一定会来救援，就这样持续不断把爬上墙壁的敌人击落。我们必须回应她们的努力才行。

我方的优势是莉兹贝特帮忙制作的高品质铁制武器、结衣习得的火属性魔法、二十名帕特鲁族以及诗乃的搭档黑卡蒂Ⅱ。其中具备将压倒性人数差距翻盘潜力的就只有黑卡蒂Ⅱ，但是诗乃说过专用的子弹只剩下六发。击中要害的话，黑卡蒂Ⅱ的威力甚至能够屠龙──实际上诗乃似乎真的打倒了巨大恐龙──但是六发子弹恐怕不足以击退超过二十名以上的玩家。另外也不能在此就耗尽即使在Unital ring世界应该也是最强等级的火力。

「喂，桐字头的老大，现在该怎么办！」

站在旁边的克莱因举起细长弯刀，同时以真的感到焦急的声音对我问道。

「要赌一把直接冲入敌阵的话，我会紧跟着你哟！」

「现在自暴自弃还太早了，一定有什么逆转的方法才对。」

「话虽如此，但是靠正攻法可无法破解巩固到那种地步的防御啊。」

正如克莱因所说的，敌人集团没有产生动摇，只是把盾牌摆在正中间然后一点一点缩短距离。我们要是沉不住气使出剑技的话，对方应该会用坦克确实挡下来，然后以反击来一口气决定胜负。这种进攻方式，让人觉得他们似乎一开始就知道我们的阵容攻击手偏多。

应该撤退到河岸边吗？不行，这样只会让袭击者继续攻击圆木屋。或许是感觉到敌人的压力吧，在后方守护着结衣的小黑发出「咕噜噜……」的低吼。然后聚集在更后方的帕特鲁族们也泄漏出不安的声音。

如果我是那种极度冷血无情的领袖，或许就能订立让他们突袭敌人集团来制造混乱状态，然后趁机来排除坦克的作战。但是我当然无法做出这样的决定。他们打倒了Goliath rana这个长年的仇敌，好不容易才刚刚抵达赛鲁耶提利欧大森林这个约定之地。虽然这个区域也栖息着恐怖的怪物，但让他们因为卷入玩家之间的纷争而出现死者的话，之后绝对会遭受良心谴责……

「…………啊！」

我发出低沉的叫声。

虽然不知道能不能称之为优势，但这座森林里还存在一个极大的不确定要素。如果能把那个要素吸引过来，袭击者们应该也没办法再这么好整以暇了吧。

「克莱因、艾基尔。」

我小声对站在我左右两侧的两个人做出指示。

「把你们身上所有的青蛙肉都丢进附近的火里。」

我不等待他们回应就迅速叫出环状选单，把塞在道具栏里面的大量Goliath rana肉实体化。抓住不断在视窗上实体化的鲜红色肉块，一把丢进在左侧炽烈燃烧的火焰里。

只比我晚了一会儿，克莱因他们也开始同样的作业。在这种九死一生的状态下，为何要做出这种意义不明的举动──没有这么提问是因为相处已久的结果。只不过这个作战要是失败，我的信用度也会大幅下降吧。

「……那些家伙在做什么？在这种状况下整理垃圾吗？」

敌阵的其中一人说出这样的疑问后，其他玩家就回答：

「在烤肉耶。难道是想用食物来引诱我们？」

「不会以为我们是NPC吧。」

在这些言语此起彼落之中，Goliath rana的肉也不断在火焰之中烤着，附近开始飘起很香的味道。虽然粉红色的色泽实在有点太鲜艳了，但是青蛙肉是等级相当高的食材，光是用火烤就发出胡椒混合了迷迭香一般的强烈香味。

但是光靠这样的香味当然无法让袭击者们失去战意。身为队长的长枪使从后方传出冷静的声音。

「……在继续做出古怪举动之前就收拾掉他们！开始计划2！」

接到这个指示，集团成员口里就叫出「喔喔！」的声音。

但是我们无法得知计划2是什么作战。因为从森林深处传来了旋转巨大石臼般的声响。

「吼噜噜噜噜……」

──来了。

地面微微震动。新的战栗让我背后流出冷汗。托青蛙肉的福，看来是成功将「不确定要素」吸引过来了，但这是一把双面刃。

分为两边的敌人集团，待在左侧的人露出明显的动摇。

「喂，后面好像有什么……」

「咕噜啊啊啊啊啊！」

宛若雷鸣般的吼叫声响起，一棵燃烧中的旋松从根部折断。从火焰当中冲出来的是即使前脚着地，头部距离地面依然有两公尺高的超巨大四脚兽。昨天晚上将我们推入恐惧深渊当中的森林支配者──尖刺洞熊。或许是烤青蛙肉的味道刺激了它的空腹感吧，粗大的牙齿间不停滴下唾液，红色眼睛里带着饥饿的光芒。

「呜哇啊啊啊！」

发出悲鸣的敌人攻击手胡乱刺出手里的铁剑。但是洞熊没有丝毫害怕的模样，以不符合巨大身躯的敏捷身手扑过去后，右手随兴扫开了攻击手。

「咕啊！」

宛如破布般被吹飞的攻击手，猛烈撞上圆木屋的石墙后发出恐怖的声音，弹回三公尺左右才滚落到地面。浮标的中心射出，分解的虚拟角色变成缠绕在一起的缎带被夜空吸去。

虽然算不上重武装，但一击就能杀害具备一定水准防具的玩家，看来尖刺洞熊的能力值比我想像中还高。我想它应该不会使用魔法，但是光看物理攻击力绝对超过Goliath rana。

昨天晚上以「屋顶滚落圆木作战」打倒它确确实实是一个奇迹……我重新有了这样的体认，同时和克莱因、艾基尔一起慢慢后退。

原本预想目击伙伴遭到瞬间杀害的袭击者们会陷入恐慌而到处逃窜，但是并没有如我所愿。最快从冲击里恢复过来的长枪使，举起明显是继承武器的考究曲镰戟，然后以浑厚的声音大喝：

「别慌张！A队B队会合，对魔王阵形！」

长枪使的头发是红黑色，肌肤则是赤铜色。在ALO里绝对是火精灵族。虽然不曾见过，但应该是尤金将军麾下，在种族战争里隶属于长枪兵部队的其中一人吧。

如果是这样，竟然能够唆使这种核心玩家的「老师」究竟是什么人呢……

当我再次陷入疑问当中时，视线前方原本分为两队的袭击者们迅速会合，形成了巨大的联合部队。这次依然是坦克、攻击手、减益手这种范本般的排列，连在石墙上跟亚丝娜她们战斗的三个人都跳到地面来加入阵形当中。

「吼噜噜哦哦哦！」

再次发出吼声的尖刺洞熊，以钩爪抓了几次地面之后猛然往前突进。是连圆木屋的墙壁都能破坏的身体攻击──

「喀铿───！」的冲击声震动空气。四名坦克排成横列把盾牌连结在一起，好不容易才把洞熊的猛烈突进挡下来。我忍不住发出「喔喔……」的惊叹声。

但是没有时间感到佩服了。在这种混乱的状况下，我们也必须采取最适当的行动。

「喂，桐人，现在怎么办！」

我在左手被莉兹贝特拉着的情况下拼命转动脑袋。敌人集团对我方露出侧腹，当然会想攻击该处，但随便靠近后连我们都被洞熊盯上的话可就本末倒置了。

虽然不愿意，但还是就这样观看尖刺洞熊与袭击者们的战斗，如果是洞熊获胜当然很好，就算输了敌人玩家们应该也会蒙受莫大损害，到时候再包围起来加以歼灭……

当我准备说出这合理又冷酷的方针时──

「桐人哥。」

有人从右侧这么叫我，于是我便看向该处。不知道什么时候已经站在艾基尔背后的是原本待在石墙上的西莉卡。原本想要慰劳长时间奋斗的西莉卡，但是她却迅速以右手阻止了我。

「桐人哥，那只巨大的熊就是希望我加以驯服的尖刺洞熊吧。」

「啊……嗯，是没错。但那是将来的希望……」

「就算是这样，我现在也不愿意舍弃将来可能会当成宠物的孩子。」

西莉卡以认真表情这么说道，她头上的小龙毕娜也简短发出「啾……」的叫声。

──不论那只洞熊是输还是赢，将来要挑战驯服的都是再次涌出的其他个体喔。

我把这句话吞了回去。对于从SAO时代就一直是驯兽师的西莉卡来说，这不是能够用道理说明的问题吧。现在在这里把尖刺洞熊当成弃子的话，就算将来成功驯服其他个体，也没有办法做到真正的心灵相通……我可以理解也愿意尊重这样的心情。

我接受西莉卡笔直的视线后，看向并肩站在远方石墙上的亚丝娜与爱丽丝。手拿细剑与长剑，长发正随风飘扬的两个人，简直就像是赞同我的决定一样一起对我点了点头。

「……我知道了。前面就交给洞熊，我们从后面进攻。」

把脸移回来并如此宣告后，西莉卡就点头表示「好的！」，克莱因也拍着我的背部说「就是得这样才行啊！」。

前方尖刺洞熊与袭击者们正展开激战。洞熊的主要攻击手段是双手横扫以及突进，四名持盾玩家则拼命挡下这些攻击，然后剑使由左右两边，长枪使则由后方给予它伤害。整然有序的合作看起来完全不像是临时组成的联合部队，但是我还没有跟洞熊接触，所以不清楚它被削除了多少HP。根据我们参战的时机，届时将会对上元气满满、怒气到达顶点的尖刺洞熊，但是也只能临机应变了。

用眼神跟伙伴们沟通过之后，我就缓缓举起右手的剑，等洞熊不知道开始第几次突进攻击的瞬间就迅速把剑往下挥落。

我、艾基尔与克莱因排成横列往前冲刺。目标是在敌阵后列中央进行指挥的队长长枪使。艾基尔先发动双手斧的范围攻击「漩流」，横扫保护着队长的两个人。

「呜喔……」

「攻过来了！」

被打倒的两个人嘴里这么大叫，后列的所有人便看向这边。另外两个人就以令人佩服的反应速度攻向处于技后僵硬中的艾基尔。

「别作梦了！」

克莱因发动单手弯刀的基本技「掠夺者」，我也以「垂直斩」冲了进去。完美同步的斩击砍倒两名敌人。

这样就有四名敌人陷入翻倒状态，继艾基尔之后我跟克莱因也开始技后僵硬。敌人领袖这时把曲镰戟整个往后拉并且大叫：

「这不是适合发动攻击的时候吧，桐人！」

──为什么每个家伙都认识我啊。

我在心中这么咒骂，同时瞪着曲镰戟带着蓝绿色光芒的锐利枪刃。双手用长枪的范围攻击技「涡流」。威力虽然比双手斧的「漩流」低，但是带有眩惑的异常状态效果。

这个时候我才终于可以看见敌人队长的HP条上显示出【Schulz】这个名字。念作……修鲁兹吗？虽然没见过，但应该会跟摩库立一样成为难以忘记的名字吧。

就在「涡流」即将一次扫倒我们三个人时。

后方传出两种炸裂声，两条火线直接击中修鲁兹的胸口与右肩。是结衣的魔法与诗乃的子弹。修鲁兹的范围技消灭，身体整个往后仰。莉兹贝特与西莉卡扑了过去，锤矛与短刀的普通技完成追击，把他击倒在地面。

这时终于从技后僵硬中解放出来的我，一边把身体前倾到极限一边举起剑来。

三连击技「锐爪」全部击中的话，应该能让修鲁兹的HP归零。但是以一般的方式发动的话，斩击无法击中倒在地面的敌人。这个时候就要压低身体来使出剑技，但要是太过倾斜就会被判定为异常体势，剑技也就不会发动。

两脚脚尖像要刨起地面一样支撑着身体，把身体压低到容许的极限后输入动作。铁剑一边发出高周波一边闪耀红光。

踢向地面的瞬间，我的视线和倒地的修鲁兹相对。

他的眼里透露出惊讶、懊悔以及另一个感情。是疑惑……？对什么感到疑惑？

到了这个时候，我才突然兴起与他谈话的念头。是从谁那里听说圆木屋的所在地？是如何组成如此大规模的部队？为什么二话不说就发动攻击？但已经太迟了。我不能够停下发动的剑技。

在系统辅助与加成下，我一瞬间就跳过五公尺的距离。修鲁兹没有勉强起身，在仰躺的情况下以两手举起曲镰戟来抵挡，但是太高估我斩击的轨道了。从宛如在地上爬行的冲刺所发出的锐爪，初击就钻过了长枪的柄陷入修鲁兹的脖子内。

反弹回来的剑无视惯性挥出第二、第三击。刻划在空中的鲜红爪痕与血色伤害特效混杂在一起。修鲁兹的HP条急遽减少，最后一下子就消失了。

「桐人……你真的……」

如此呢喃着的修鲁兹，身体被HP条射出的纺锤贯穿并分解成无数的环。

──「我真的……」怎样啦！

虽然很想这么大叫，但又觉得这句话不适合送给奋战到最后才永远离开这个世界的男人，于是便忍了下来。而且目前战斗仍未结束。

我撑起身体，环视周围的敌人并且大声呼叫：

「你们的队长死了喔！要逃走的话我们不会追击！」

在Underworld的卢利特村附近的洞窟与哥布林集团战斗时，这么叫完敌人就落荒而逃了，但我附近的玩家只是一瞬间露出疑惑的表情，随即就大叫着如此回应。

「少啰嗦！怎么可能现在才逃走呢！」

由于他挥舞着短枪冲了过来，我便急忙做出抵挡。重新告诉自己「嗯，也是啦」之后，我就以浑身的力量把对方推回去，接着用「垂直斩」把他轰飞。

接下来就是毫无秩序与合作的极度混战了。

由于有一半的敌人在跟尖刺洞熊战斗，我便一边注意不要靠近该处一边专心砍倒另一半的敌人。最让人感到安心的，是诗乃的毛瑟枪与结衣的火焰魔法会确实将试图一招扭转战局的敌人准备使出的大技剑技摧毁，所以能够集中精神对付眼前的敌人。当然敌人也不是笨蛋，其中也有人试着要击沉诗乃与结衣，但是小黑与帕特鲁族们帮忙确实地阻止了他们。

最后决定战况的是判断已经没有人要攻击圆木屋后，从墙壁上跃下的亚丝娜与爱丽丝。她们像是要散发被迫长时间防守的压力般肆虐战场，不到五分钟，敌人的八名后卫就从战场上消失了。

呼一声松了口气后，我便为了慰劳亚丝娜与爱丽丝的奋斗而开口表示：

「两位辛苦了，抱歉来迟……」

「吼嘎哦哦哦哦！」

跟之前比起来音量与狰狞度又往上提升的咆哮打断了我的话。

往左边一看，残存的八名敌人前方，尖刺洞熊正大大地张开双臂。昨天也看过那个动作。接下来要使出的攻击是──

「糟糕……所有人趴下！」

我才刚大叫完就扑向地面。伙伴们迟了半秒左右也跟着我趴下。

下一个瞬间，洞熊胸口浮现的闪电图样就发出白光。

放射状发射出去的无数飞针吞没了八名敌人。

昨天晚上爱丽丝即使穿着继承装备的板甲，面对这招恐怖的广范围攻击还是损失了一半的HP，这时我无法看清楚它造成什么样结果。因为流弹，不对，是流针从头顶掠过，我只好赶快把脸贴到地面上。

周围的土壤与树木、岩石不断传出被金属针刺中的声音。即使处于这种姿势还是能确认小队成员的HP，我便祈祷不要有任何人死亡并且等待着攻击结束。

从左后方传来「好痛！」的悲鸣，克莱因的HP跟着大量减少。接着艾基尔也受到伤害，而我的左肩也遭到贯穿。如果连趴在地面都还有针会飞过来，那么要避开这种攻击的方法就只有飞天或者遁地了。游戏平衡完全崩坏了吧……虽然很想这么说，但是等级1就落到起始地点二十五公里外的我们说起来也有不对的地方。我拼了命地祈求「这一点我也承认但请给我们认真提升等级的机会吧」。

「哔唏！」一声刺中我鼻子前方几公分处后，飞针雨终于结束了。

畏畏缩缩地抬起头来，就看见尖刺洞熊将前脚放到地面来静止不动，它面前的八名敌方玩家则是僵硬地站在原地。四名坦克并肩举着盾牌来掩护背后的四名攻击手。竟然能撑过极近距离之下发射出来的飞针，即使是敌人其判断力与防御力依然值得敬佩……

锐利的纺锤从显示在他们头上的环状浮标往正下方射出。八名虚拟角色同时遭到分解，变成无数缎带之后被吸入夜空当中。

缎带消失之后，黑色遗物袋就不断降下来堆积在同一个地方，但现在根本没有多余的心思去拿这种东西。依然趴在地上的我呻吟了一句「不会吧……」。

尖刺洞熊发出简短的「咕噜……」吼叫声。发出红光的双眼狠狠瞪着我们。明显是以我们为攻击目标，但是无法立刻做出该逃跑还是作战的判断。

由于中了一发飞针，所以我的视界里显示了洞熊的浮标。残余的HP是六成再多一点。虽然认为袭击者们已经打了一场漂亮的仗，但果然正如我所担心的，洞熊依然是元气十足。虽说以这些成员来战斗也不是没有机会获胜，不过没有能全员存活的确信。

──不对，等等喔。我记得不是要跟熊战斗……

这个时候，一道娇小的人影就从依然趴着的我和克莱因、艾基尔后方冲出来。是西莉卡。右肩上坐着毕娜，手上连短剑都没拿就朝着尖刺洞熊靠近。

「喂……喂，西莉卡！」

急忙爬起来这么呼叫，但西莉卡依然背对着我们并且以压抑的声音说：

「请交给我吧！」

这边的「交给她」当然不是「干掉」而是要「驯服」的意思吧。但老实说，这应该比打倒它还困难。我能够驯服背琉璃暗豹已经是万分之一的奇迹了，不过那个时候我们跟小黑都被卷入冰风暴之中差点就要冻死，因此无法否定这样的状况影响了成功判定的可能性。

但眼前的尖刺洞熊正因为受到长时间的烦人攻击而充满愤怒，即使瞬间击杀八名袭击者，怒气也完全没有减弱的模样。以状况来说跟驯服小黑时是完全相反，老实说实在不认为是并未继承驯兽技能的西莉卡所能驯服的对象。

但西莉卡丝毫没有露出恐惧的模样，直接就朝露出牙齿低吼的洞熊走去。她的双手似乎握着巨大的块状物。那是……在火里面烤得熟透了的青蛙肉。

注意到这一点的瞬间，我终于想到自己应该做什么了。

「克莱因、艾基尔，收集森林里面的肉吧。」

「好……好喔。」

「了解了。」

以视界边缘捕捉西莉卡的身影，同时为了不刺激到洞熊而缩起身体行动。修鲁兹他们放的火在不知不觉间已经把圆木屋周边的旋松焚烧殆尽，火势几乎已经熄灭了。于是我便从焦黑的地面捡起发出咻咻声的青蛙肉来放进道具栏里。

另一方面，西莉卡前进到距离发出低吼的尖刺洞熊两公尺左右时，就静静地扔出左手的肉块。

「吃饭喽，熊先生。」

对于这句话的反应……

「嘎吼噜啊啊啊啊啊！」

是这样的怒吼。

尖刺洞熊以后脚站立起来，并且举起长着小刀般钩爪的手。直立的话随便都超过三公尺的熊，和伙伴中身高只赢过结衣的西莉卡，体格上的差距确实令人感到绝望，当然VRMMO的角色身高与战斗力并不成正比，即使如此我还是看见被洞熊手臂横扫的西莉卡跟袭击者们一样遭到分解的幻影。

但是──

洞熊缓缓放下举起的双臂，直接恢复成四脚步行状态。闻了一阵子掉在前方的蛙肉气味后就大口咬下，嚼了几下就直接整个吞下去。

「…………」

我忍不住停下捡拾肉块的手，专心看着洞熊与西莉卡的模样。这时西莉卡的视界应该出现驯兽的圆形计量表了。西莉卡计算时机后也丢出右手的肉。洞熊立刻咬下。

看见两手空空的西莉卡打开道具栏，我就急忙小声拜托艾基尔他们说：

「把捡来的肉块传给我。」

结果立刻不只有艾基尔与克莱因，连莉兹、莉法、亚丝娜都传来交易视窗。连续击打YES键全部接受之后，就蹑手蹑脚朝着西莉卡走到交易射程距离的二．五公尺处。我传送过去的交易视窗立刻得到回应，这样烤青蛙肉就全部传送到西莉卡的道具栏里了。

再来我们能做的就只剩下向天祈祷。

西莉卡遵从只有她能看见的计量表，不断把青蛙肉丢出去。洞熊也不厌其烦地咬住并且吞下肉块。交易给西莉卡的肉块应该有三十块以上，以这种速度喂食的话，不到三分钟就会被吃光了。要是在这之前没有完成驯服，就必须选择是要逃跑还是战斗了。我从西莉卡背后凝视着显示这在道具栏里的【烤Goliath rana肉】剩余个数。十块变成五块，然后是三块、两块、一块……零块。

投出最后一块烤肉的西莉卡，以紧绷的声音呢喃：

「计量表从刚才就一直停在九九％。」

「……知道了。应该有一两块没捡到的肉吧，我去找找。」

我这么回应并且急忙准备回到森林。但西莉卡却迅速摇了摇头。

「不行，我想同样的肉无法提升这最后的一％。我要在这个状态下挑战驯服。」

不知道什么时候，西莉卡的左手已经准备好一条长长的绳子。把它套在尖刺洞熊的脖子上并且绑起来的话驯兽就算成功，但我认为最后那一％就是决定胜败的关键。

「等一下，看看还有没有其他食物……」

我打开道具栏胡乱卷动。明明来到这个世界才过了一天半，里面已经塞满了杂乱的素材道具，但是却没有什么正常食材。鬣狗的肉、山椒鱼的尾巴、蝙蝠的翅膀……每一种都不像能满足巨熊的胃口。说起来熊喜欢吃什么呢？鲑鱼？苹果？竹笋？每一种都不曾在这个世界看过。

只能在九十九％的状态下挂上绳子了吗……正当我打算放弃时──

「西莉卡，这个给你。」

不知道什么时候靠到我后面的诗乃，这么说完就递出一个拳头大小的蓝壶。不知道里面装了什么。但也只能相信和我们从不同地点开始游戏，并且横越广大基幽鲁平原的诗乃了。

接过蓝壶的西莉卡，毫不犹豫就把右手伸进去并且拿出内容物。出现的是某种泛白的半固体块状物。由于相当软，所以无法直接丢出去，于是西莉卡就直接朝着洞熊靠近。

「来，很好吃喔。」

尖刺洞熊狠狠地瞪着西莉卡一边这么呢喃一边伸出去的右手。

「吼噜唔……」

熊短吼了一声就开始嗅了起来。但是似乎不打算做出更多的反应。这时诗乃以沙哑的声音呢喃：

「生的素材可能不被接受吧……」

确实有这个可能。尖刺洞熊虽然称不上是练功区魔王，但明显是稀有种怪物，想驯服它的话或许就只能用加工过的饵。但那个白色块状物要如何加工呢？

突然间，一道小小的影子奔过我和诗乃之间。从尺寸来看原本以为是结衣，但并非如此。是缠着茶色毛皮，长着细长尾巴的其中一名帕特鲁族。是那个用「偶」来自称的领袖。

以让人觉得果然是鼠人的速度跑向西莉卡的帕特鲁族，将双手抱住的黄色壶朝西莉卡右手上倾倒。带黏度的金色液体黏糊糊地流下，覆盖住白色块状物。结束作业之后，鼠人再次以猛烈的速度跑回后方。

「………………？」

我和诗乃同时茫然张开嘴巴。在这之后──

尖刺洞熊再次动鼻子闻了一闻味道，然后舔了一口就让西莉卡手上难以言喻的物体消失了。

刹那间，西莉卡的左手有了动作。长绳挂到洞熊粗大的脖子上，环绕过去后就用双手打结。尖刺洞熊的巨躯发出闪光──

原本发出鲜红色光芒的环状浮标变成绿色。

寂静之中，西莉卡当场瘫软到地上。

「嘎呜！」

简短叫了一声的熊，不断以巨大舌头舔着西莉卡的脸颊。

当我茫然看着这一幕，身后就传出了声音。

「……这是成功了吗？」

站在那里的是爱丽丝。在夜里也保持着碧蓝的蓝宝石色眼珠依然浮着怀疑的光芒。虽然我也无法立刻相信，但是洞熊的环状浮标从红色变成绿色是事实。

「应该……成功了吧？」

「老实说我本来觉得不可能成功。如果是西莉卡的话，说不定连西帝国的野生飞龙都能驯服喔。」

「哪一天带她到Underworld去试试看吧。」

这么回答完，我就把视线移到诗乃身上。

「……那么，那个白色的东西是什么？」

「是奶油喔。」

「奶……奶油？你在哪里拿到那种东西的？」

「欧鲁尼特族的小孩子给我的。」

「…………这样啊……」

轻轻摇摇头后，我又看向后方聚在一起的帕特鲁族们。

「……那么，那些鼠人淋到奶油上的是什么？」

「谁知道呢……」

代替耸肩的诗乃回答的是和亚丝娜手牵手的结衣。

「那好像是蜂蜜喔，爸爸。」

「蜂……蜂蜜？在哪里拿到那种东西……」

「听说帕特鲁族很久很久以前就是在基幽鲁平原养蜂。他们说过那些蜂蜜是一族继承了几百年的宝物。」

「几百年的骨董蜂蜜吗？为什么会用掉这么贵重的东西……？」

我一边再次看向帕特鲁族一边这么呢喃，这时结衣也微微歪起头来。

「我没有问得那么仔细，现在问问看吧？」

「我觉得还是不要问比较好。」

在我回答之前，亚丝娜就微笑着这么说道。

「桐人被问到帮助别人的理由时也会感到困扰吧？」

「……嗯，或许吧……」

──在心里想着「其实是老是受到别人的帮助才对」并且点了点头，结果小黑就用头摩擦我的右腰，同时发出抿着嘴笑一般的叫声。

「不过呢，如果是这样的话，也难怪小熊会被驯服了！」

莉法的发言让莉兹贝特露出疑惑的表情。

「为什么？」

「因为是蜂蜜奶油啊！怎么可能抵抗这种诱惑呢！」

「那只有你吧……」

当我准备这么吐槽时，肚子就传出「咕噜～～～～」的叫声。艾基尔与克莱因毫不客气地哈哈大笑，女孩子们也跟着笑了起来。

结果还是没有机会询问修鲁兹他们为什么要来攻击圆木屋。

但是必须要做好有二就有三的心理准备。然后所有人都认为，第三次应该会是更大规模的攻击才对。

因此我们没有因为成功和诗乃、艾基尔以及克莱因会合而高兴太久，立刻在圆木屋的前院围着营火开始讨论起今后的防御事项。

在高大石墙包围的庭院西南角落，尖刺洞熊米夏（西莉卡命名）正侧卧着巨躯睡觉，小黑和阿蜥也像是埋在它异常柔软的腹部毛皮里般熟睡着。这是让人觉得墙外发生的激斗像是作梦一般的温馨场景，不过要是因为饲料不足而让米夏的驯服状态解除的话，那个瞬间地狱的景象就会复活，所以等会议结束之后就得去寻找熊喜欢吃的食物才行。

二十名帕特鲁族们目前在圆木屋的客厅休息。但是在登出这款游戏之前我们也必须在安全的地点睡觉，所以之后还是得为了帕特鲁族们盖新的建筑物。虽然待处理的事项还是堆积如山，但现在的课题是──

「果然还是只能强化墙壁吗？高度也提升两倍左右……」

克莱因摊开双手这么说完，亚丝娜也轻轻点了点头。

「刚才的敌人毫不犹豫就爬上来了……看来需要落下会受到莫大伤害的高度才行。还有要尽量把上面的凹凸不平处弄平。」

听见这言外之意为「理想是中央圣堂的白亚之壁」的发言，我忍不住就要露出微笑，好不容易才忍下来。但还是无法瞒过骑士大人敏锐的感觉，被她狠狠瞪了一眼。

「桐人，怎么一直保持沉默，你没有什么意见吗？」

「抱歉抱歉，我在想很多事情。」

我轻轻动了一下头，干咳了一声后继续表示：

「嗯……我对于加强防御没有异议，但这个方向总有一天会有极限。墙壁再高只要架上梯子就会被克服，今后玩家等级提升之后，远距离攻击的手段也会增加……」

「那么该如何保护这个地方呢？」

面对莉兹贝特急性子的提问，我提出接受帕特鲁族同行时就想好的点子。

「不觉得之所以不断遭到袭击，是因为只有一间玩家房小屋孤零零地在这里吗？」

「啥？你是打算增加房子？」

「是啊。但不是一间两间。我要在这里盖一座城市。」

「………………」

包含结衣在内的九名伙伴全都露出哑然的表情。

最先开口的是亚丝娜。

「桐人，光是盖许多建筑物还是无法成为城市喔。必须有居民才行。」

「反正帕特鲁族也需要房子吧？盖五六间他们的房子，应该就有点样子了吧？」

「要把帕特鲁族当成盾牌吗？」

诗乃以尖锐的声音这么问道，我则是急忙摇头回答：

「不是不是，当然也会保护他们啊。只不过，从玩家不容易袭击这里的层面来看，或许可以算是利用了他们吧……」

我环视面露难色的众伙伴并且继续说明：

「横越基幽鲁平原到一半时，我就觉得这个地点的资源相当丰富。因为盖房子需要的石头与木材几乎是取之不尽。最令人担心的是铁矿石，但是西莉卡帮忙驯服了尖刺洞熊，这个问题应该也获得解决了。」

当我把话说到这里，莉法就插嘴进来说：

「咦……熊不会再涌出了吗？」

「被打倒的话就会，但是驯服的话应该就不会了。因为如果会的话，就能不断把那种强度的Mob变成宠物啦。收集十只组成洞熊军团的话就所向无敌了吧。」

「我可不想再挑战一次了。」

西莉卡抖动一下身体后，原本在她头上睡觉的毕娜就张开一只眼睛，像要表示「就是说啊」一般发出「啾呜」的叫声。随即响起一阵和睦的笑声并且止歇。

「嗯，再涌出这件事之后再到巢穴去确认……总之呢，我认为增加建筑物不是那么辛苦的事。不过只靠帕特鲁族的话，形成城市的居民明显不足，将来还是得挖角其他的NPC才行。」

「巴辛族他们愿意搬家过来的话就太好了！」

结衣刚这么说完，莉兹贝特就用力点点头。其他的VRMMO里绝对不可能出现让NPC搬家的情形，但是感觉这个世界或许可以用交涉来达成目的。巴辛族固然相当可靠，但可以的话希望诗乃在基幽鲁平原西部遇见的鸟人，也就是欧鲁尼特族能够搬过来居住。能够使用毛瑟枪的他们愿意参加的话，城市的守备将坚固数倍……

「但是桐人……」

艾基尔突然叫我的名字，于是我便连同身体一起转向他。

「你也是打算完全攻略这款游戏吧？以昨天系统广播所说的『极光指示之地』为目标的话，总有一天得离开这座森林吧？」

很丢脸的是，在他指出这一点之前我已经完全忘记公告的事，于是眨了两下眼睛后才不停点头说：

「呃，嗯……确实是这样。但是出远门时，有没有安全据点将会造成很大的差异。尤其我们还拥有重到极点的继承装备……一直放在自己的道具栏将会大幅压迫容量，要放在房屋的仓库栏里的话就必须想尽办法来巩固防御才行……」

下一个瞬间，伙伴全都露出严肃的表情。诗乃的黑卡蒂Ⅱ是这种装备的代表，不过对每个人来说，继承武器与防具都是自己珍惜的搭档。很可惜的是我的爱剑黑色鞭痕已经成为众人铁武器的素材，但是绝对要守下另一把断钢圣剑，而其他人应该跟我有同样的想法才对。

「我基本上是赞成桐人想建造城市的想法。大家呢？」

爱丽丝做出这样的宣言后，其他人也重复着「赞成」的回答。她轻轻点头表示理解后再次看着我说：

「……但是要从设计开始做起的话，将会是很大的工程。花上一个星期，不对，是一个月也不奇怪吧？在那之前要是遇见第三次的袭击该怎么办？」

「不！」

我一迅速站起来，随即高声握紧装备着铁制护手的右手。

「哪能花到一个星期！现在是二十三点，呃……到凌晨三点的四个小时就要打造出城市的原形！」

坚定地这么说完，爱丽丝就大叫「什么？四个小时？」，亚丝娜也苦笑着说「看来今天得熬夜了」，结衣则是鼓励大家说「一起加油吧！」。

** 第十章

隔天九月二十九日星期二，下午一点三十五分。

我在西武新宿线的急行电车里摇晃着，同时与袭来的睡魔战斗。

可以的话希望能有效利用这段时间来消除睡眠不足，也就是爆睡一阵子，但是却无法如愿以偿。这是因为旁边坐着谜样转学生帆坂朋──亦即「老鼠」亚鲁戈的缘故。要是睡着而把头靠在她的肩膀上，然后差点把口水流到她身上的话，今后一定会被她取笑好几年。

因此当我拼命抬起擅自降下的眼睑时，就听见了隐含笑意的声音。

「桐仔，你似乎很想睡耶。我帮你点眼药水吧？」

「不……不用了，谢谢你。说起来，你为什么老是想帮人点眼药水啊。」

「我可不是对每个人都这么做哟。」

「这样啊……──但话又说回来了，你为什么跟来啊。」

「啊～这么说就太过分喽。是我指导你不用翘课就能离开学校的密技吧？」

「唔……」

听她这么一说，倒是真的无法发脾气。

平日的下午三点到银座，为了回应这种对高中生来说是强人所难的要求，虽然不愿意但还是打算翘掉今天的第五节和第六节课。但开始上课前随口对跑来找我的亚鲁戈提起这件事情，她就告诉我只要向学校提出「求职前职场参观」的申请，下午的课就能请假。

当然申请书必须获得参观企业的电子认证，但我已经请找我的那个男人捏造了。申请顺利通过，虽然成功回避了无故旷课的烙印，但无法上课的事实依然无法改变。

于是我便下定决心，这下子要是没什么大不了的事，我就要不断把高级蛋糕塞进肚子，直到人体的极限为止。

「倒是听说你们昨天很累啊？被庞大的联合部队进攻据点了？」

突然被亚鲁戈这么问，我沉默了一秒钟后就反问她：

「………………你怎么知道的？」

「参加联合部队的玩家在SNS投稿了详情哟。虽然是上锁的帐号，但是那对本亚鲁戈大人根本没用啦。」

「真的假的……」

之所以发出这样的呻吟，并不是因为亚鲁戈的情报收集能力，而是因为有人「投稿了详情」。这样在Unital ring世界存活下来的所有前ALO玩家，不久之后就会知道我们的据点所在之处了吧。

把叹息吞回去后，我重新回答亚鲁戈的问题。

「真的很累人喔。那些家伙过来的时候就做好攻下据点的准备了……因为阵容里没有魔法师才好不容易挡了下来，如果有两三个魔法师的话，我们就输了吧。」

说到这里之后，才对自己的发言感到疑惑。

「说得也是……为什么找了那么多人，却没有半个魔法师呢？起始地点应该有一大堆继承了魔法技能的家伙吧……」

「光是继承魔法技能是无法使用的哟。」

「咦？是这样吗？」

「技能本身存在于已习得的清单当中，但是处于封印状态，想解封就需要名为『魔晶石』的道具。知道这一点之后，起始地点的斯提斯遗迹周边，就为了寻找能掉落魔晶石的怪物而引起了一阵大骚动。」

「……这……这样啊。」

不由得做出僵硬的回应后，才又急忙接着说：

「但是，这种规则对魔法职的玩家不会太严苛了吗？这等于是在没有继承技能的状态下开始游戏吧？」

「我也这么认为，应该是没有设限的话就会变成魔法职太过强大的状况吧。因为强制转移到缓冲期间结束的四个小时里，熟练度1000等级的最高等魔法师将可以为所欲为吧？像是尽情狩猎强大Mob来提升等级，或者是随自己高兴来屠杀其他玩家。」

「啊……嗯，也是啦……」

实际上因为MP的回复速度会赶不上，所以不可能从一开始就尽情使用魔法，但只要等级提升就能解决这个问题。正如亚鲁戈所说的，不设限的话现在Unital ring很可能已经变成魔法师无双的游戏了……但是除了继承技能熟练度下降到100之外，还必须吃下魔晶石才能解锁实在有点太过严苛。

急行电车抵达上石神井车站，少数几名乘客上下车后再次开动。尖峰时段时难以想像车内乘客会有这么少的时候，午后阳光从正面窗户照下来后在地板上留下格子状影子。悠闲地坐在长椅子上的我，再次受到睡意的袭击。

结果昨天，不对，应该说今天早上也一直拼到凌晨五点。虽然为了达成「四小时建立城市」的宣言而努力，但是收集水井的素材就花了一个小时，寻找可以种植在田里的植物也花了一个小时，预定也因此而延后。

但所有人的努力没有白费，好不容易筑成了足以称为城市──当然是以游戏世界的感觉来看──的成果。

目前圆木屋是被直径十五公尺的石墙所包围，我们开拓了石墙外侧那一大片森林（大树被袭击者烧光了所以作业本身很轻松），另外盖了一座圆形的墙壁，然后把内部分成东西南北四个区域。东区域是帕特鲁族的居住地，西区域是将来其他种族NPC的居住地，南区域是商业地域，北区域是田地与宠物们的厩舍。西区域目前只有石头地基，南区域也没有任何可以开始营业的商店，但我认为外表已经很像城市了。这种将正圆形分成四等份的构造与Underworld首都圣托利亚几乎一样，在爱丽丝指出这一点之前，我都没有发现这个事实。当然我们的城市直径只有六十公尺左右，以面积来说甚至连北圣托利亚的一个街区都不到。

即使如此，之所以能够一夜就完成比当初预想中更加正式的城市，可以说全是靠西莉卡的新搭档──米夏的福。米夏装备亚丝娜用裁缝技能与木工技能制作出来的「大型兽用搬运袋」后，就像是毫无搬运重量限制般帮忙搬运了大量的石材与圆木。当然越是让宠物工作SP条的减少就越是快速，所以确保稳定的饲料就是课题，但是这也靠亚丝娜制作的渔网获得解决，在南方的河川使用时一开始都是零收获，但随着撒网技能的熟练度上升，就能捕获一些大鱼了。由于阿蜥与小黑也喜欢吃烤鱼，所以宠物的食物问题可以说暂时是解决了。

再来就是能不能让总有一天会再次来袭的玩家们产生「袭击城市并加以破坏」的忌讳感了。我的话是绝对不想干出这种恶行，但是也有反而会因此而热血沸腾的玩家，所以关于这一点还是得看到结果才能知道。说不定当我坐在摇晃的电车里时，新的袭击者们已经悄悄靠近城市了。

──问题果然还是那个「老师」吗……

把头靠在座位边缘的扶手上──思绪跑到可能躲在一连串袭击背后的谜样玩家身上。一听见PvP的，不对，是PK的指导者，总是会闪过在艾恩葛朗特暗中活跃的杀人公会「微笑棺木」以及其会长「PoH」的影子，但是摇光在Underworld受到不可逆损伤的那个男人，实在不可能这个时候还出现在Unital ring里头热衷于「游戏的PK」。而且「不要只看对手的某个部分，要掌握全体」这种精神论的指导也不是PoH的风格。先以三寸不烂之舌拉拢，再让人喝下加了毒的水才是那个家伙的做法。

如此一来，那个老师到底是……

「亚鲁戈啊。」

一这么呼唤，不知不觉间把头靠在我左肩上打瞌睡的亚鲁戈便发出「嗯啊？」的声音并抬起头来。

「什……什么事？」

「你看见的上锁帐号，有没有提到进攻我们据点的理由呢？」

「嗯～？理由吗……记得好像只写了是认识的火精灵族的邀约。」

「唔嗯……」

那个火精灵一定就是修鲁兹吧。如此一来，跟「老师」接触的可能只有他一个人而已。

──桐人……你真的……

永久退场的瞬间，修鲁兹留下这么一句话。思考了一整晚还是想不出「你真的……」后面是什么内容。当然修鲁兹并非真的死亡，在现实世界按照线索与其接触，就有可能把事情问个清楚……

「亚鲁戈啊。」

「喂，我差不多要收情报费喽。」

「我请你吃银座的高级蛋糕。所以……你知不知道ALO玩家里，哪个人的外号是『老师』的啊？」

「知道哟。」

没想到她会立刻这么回答，让我忍不住窥探她卷发之下的脸庞。

「真……真的吗？」

「嗯嗯。是名叫『黑漆漆老师』的家伙。」

「…………」

我从鼻子发出「呼嘶」的气息。我也知道拥有这个外号的玩家，但可以确定不是那名问题人物。

「忘掉那个家伙吧。其他的呢？」

「嗯……」

沉吟了一会儿之后，她才缓缓摇摇头。

「没有，想不出来了。被转移到Unital ring的众ALO玩家好像已经组成了几支队伍，或许是其中一支队伍的领袖，但没有调查就无法得知。」

「队伍？是像公会那样的吗？」

「比公会还要松散一些，大概是以交换情报为主的集团。名字也很随便哟……像是『绝对存活队』啦、『广播小姐粉丝俱乐部』啦、『啃杂草者』啦、『假想研究会』等等……」

「的确是很随便的队名……嗯，那你就帮忙调查一下这些小队的队长吧。」

「只有一个蛋糕根本不够哟。」

我望着噘起嘴唇的亚鲁戈那没有胡须彩绘的光滑脸庞，继续问道：

「倒是亚鲁戈，你在昨天的会议里说过尚未登入到Unital ring里头对吧？但你对游戏内的事情也太清楚了吧？」

「仔细地收集散布在网路上的情报就能了解大概的情形喽。跟只能靠自己的脚去四处调查的SAO比起来实在轻松许多，我都要变胖啦。」

虽然这么瞎扯，但是运动外套与水手服底下的腰身却跟SAO时代一样纤细，即使很想边说「哪里胖了」边用右手钻着她的腹肌，不过这家伙已经不是性别不详的「老鼠」，而是高我一个年级的女高中生，于是便告诉自己忍耐下来。

「……不过呢，我也觉得差不多该登入去看看了。桐仔，你会从起始地点护卫我到你们的据点吧？」

「嗯……我也想看看那个叫斯提斯遗迹的地方，所以护卫是没问题啦……」

「好，那就今天晚上吧！」

看来今天的冒险也会相当漫长了……心里这么想的我往上看着车门上方的讯息板。电车正好从鹭之宫车站发车。

在高田马场车站转乘地下铁，我们终于来到银座，今天虽然是平日，这个地方依然相当热闹。经过精心打扮的妇人与外国观光客相当显眼，身穿高中制服的我们则看起来有些突兀，但不是感到胆怯的时候了。

在充满高级品牌旗舰店的中央大路大步往南前进，进入七丁目十字路口角落一栋相当具特色的红色建筑物。对方指定的店就在这里的三楼。走出电梯之后，稀释了「高级」这两个字般的空气就随着微弱的古典乐涌至，以心念之力将其推回去后就闯入店内。

「欢迎光临，请问是两位吗？」

对恭敬低下头的服务生表示「我们来找人」后，我就环视着宽敞的咖啡厅内部。

立刻有人从深处窗户边的座位上以毫不客气的巨大声音叫着我。

「喂～桐人，这边这边！」

在心里吐嘈「你是故意嚷嚷的吗！」并且横越楼层，快步朝着声音来源前进。

明明才快要三点五分，很快就将桌上水果三明治吃掉一半的是身穿深棕色西装，打着华丽斜纹领带加上黑框眼镜的男人。

初次见面时是总务省公务员，接着是自卫队二等陆佐，然后现在不知道在做什么，我认识的人当中最为可疑的人物──菊冈诚二郎带着满脸笑容对我举起右手──注意到我身边的亚鲁戈后，就在眼镜底下不停眨着眼睛。

「唔嗯……算了，先坐下来吧。」

我和亚鲁戈并肩坐在他的正面，女服务生放下冰开水离去后，菊冈再次「唔嗯」地呢喃。

「不是明日奈、直叶或者诗乃吗……桐人，这位小姐是？」

在我开口之前，亚鲁戈就咧嘴笑着回答：

「你应该早就认识我喽。终于见到你了，克里斯海特先生。」

（待续）

** 后记

谢谢大家阅读这本Sword Art Online刀剑神域第23集〈Unital ringⅡ〉。

首先要借这个地方为第21集〈Unital ringⅠ〉之后是第22集〈Kiss and fly〉，然后才是这本第23集的古怪构成跟大家致歉。虽然也有不把短篇集的〈Kiss～〉编上集数，然后把本集作为第22集的提案，但是第2集与第8集也是短篇集，所以总是很在意与它们的整合性，这次才会变成这样的构成。还请各位多多见谅！

那么……让各位等了一年，本集就是Unital ring的后续故事。上一集是在制造出铁后结束，原本这一集是希望以所有同伴会合为目标，但很意外地一路写到了建造城市。不过仍只是开拓土地并且把建筑物盖好而已，下一集我想要创作的是桐人他们的城市是否能发挥城市的机能，在游戏攻略上又负起什么样的责任。

本集主要是在二○一九年的八～九月进行创作，刚好是动画Alicization篇的后半季「War of Underworld」即将播映之前，动画将播放躲藏在卢利特村的爱丽丝照顾心神丧失的桐人，为了赚取生活费而打工伐木并且将艾尔多利耶赶回去等内容，会让人忍不住产生「与Unital ring篇的爱丽丝差距真大！」的感想。但是她的内在跟Underworld时代完全没有改变，只是实行「全力活在当下」的主义而已，所以她今后也会成为桐人小队的精神支柱才对。

然后最终节里那个戴眼镜的人也登场了，这让人有种Underworld也将再次跟故事扯上关系的预感！人界与黑暗界的情况究竟如何，就连我也相当在意，希望下一集也可以描写这些内容……但是Unital ring世界也是让人无法等待的状况，所以到底该怎么办呢？下一集我会努力创作，希望不要再让大家等待一年了！

至于我个人的近况嘛……隔了五年左右才又重新开始骑久违了的自行车，一开始光是骑上河岸边的坡道脚就发出悲鸣了，几个月后就能在速度没有掉太多的情况下骑上去，让人觉得人类的身体真的很了不起。希望今后能够不偷懒，好好地持续下去。然后这次的档期也很危险跟自行车完全无关，纯粹是宇宙的真理。责任编辑和abec老师真的很抱歉！

二○一九年十月某日 川原 砾