#+title: 刀剑神域 Progressive 9 青蓝水月的夜想曲（上）
#+setupfile: ./setup.setup

* Progressive 9 青蓝水月的夜想曲（上）

网译版 转自 huanmengacg.com 转自贴吧

(文字主要来自第三方网站，根据贴吧发布的pdf进行了部分修正)

第九卷 青蓝水月的夜想曲（上）

作者：川原砾

插图：abec

译者：B_Meow

————————————————

固有名词及人名采用简中的翻译（简中错误的地方我会修正），本卷出现的新固有名词及人名我会在旁边写上原文。

由于是时隔三年以上的进击篇，我推荐大伙重新看一遍进击篇小说后再看SAOP9。

本小说禁止私自转载到其他平台、禁止私自放到资源合集中。

擅自将本卷变成有声书的斯个募。

本小说只由B_Meow发布在贴吧以及界之星的群聊中。

如有必要转载，请联系我。

本小说仅供个人学习交流使用，禁作商业用途。

如发现用作商业用途，下次的SAOP10将只会发给信得过的人。

epub版将在台版发售前一个月公布，请注意时间。

转载请保留译者信息。

桐人化为吸血鬼眷属后的第八层攻略，开幕——！

经历了第七层楼层 BOSS 战之后，桐人变为了《夜之民》——也就是吸血鬼的眷属。在获得强大力量的同时，桐人也被赋予了 「太阳光」 这一致命的弱点。刚吸血鬼化的桐人与亚丝娜、绮兹梅尔一同前去追踪夺走了精灵战争关键道具《五把秘钥》的堕落精灵。

但是，桐人一行人所抵达的地方，竟然是曾经攻略过的第四层。

「有件事，能拜托你们吗？」

以上一任白檀骑士团团长拉维克的委托为契机，桐人一行人被卷入了与精灵们过去的恩怨相关、完全超乎想象的事态之中。

他们早已不是单纯的 AI 了——！

川原砾：2024年的大晦日（12月31日）和2025年的元旦（1月1日），我都是一个人在写原稿……嘛、这已经成每年的例行事项了呢！今年也会提升独行等级的哦—

abec：啊呸嘘？

** 第1章

「桐人君，你又在顶牙齿了」

被临时搭档亚丝娜指出来后，我把刚才放在右上犬齿上的舌头移回到了原处。

然而还不到三秒钟，左上犬齿又开始发痒了。虚拟体（Avatar）的牙齿按理来说应该和现实世界的牙齿一样，都是没有感觉的，可我如今要是不用舌头顶一顶或者碰一碰，心里就怎么也平静不下来。

这个问题的原因来自于我的犬齿——特别是上方的两颗，这两颗犬齿在几小时前一下子伸长了将近五毫米。说来也奇怪，咬合方面倒也没出现什么问题，但我的意志力还远没有能强大到无视这两颗已经不能叫做牙齿、而应该叫做獠牙的白色物体。

「毕竟有……这个东西啊」

我如此回答之后，「伊—」地一声露出牙齿来给她看，坐在我左边的亚丝娜马上把脸凑了过来，直勾勾地盯着我的牙齿看。

我突然涌起了恶作剧的念头，想要咬住她那纤细的脖颈，但一

想到她可能会大声尖叫，最终还是作罢了。虽说这里是安全屋，但我们所在的地方可是迷宫（Dungeon）——迷宫塔的深处呢。

「哇……虽然到这时候才说，你说话的时候不会咬到舌头吗？」

面对亚丝娜那双满是担忧的大大榛色眼眸，我一边想着还好没做那么孩子气的恶作剧，一边点了点头：

「嘛，似乎是不会啦。不过吃饭的时候就不知道会怎么样了」

「啊啊……桐人君变成吸血……不对，变成《夜之民》之后，还只在沃尔普塔的沙滩上喝了点水果宾治（水果番趣酒）而已呐」

「叫吸血鬼就可以啦，妮露大人又不会听到」

我苦笑着回应之后，「这样啊」亚丝娜微笑着说道。总感觉她的笑容中似乎包含了一丝淡淡的寂寞，这想必不会是我的错觉。

我和亚丝娜以及黑暗精灵骑士绮兹梅尔，在大约三小时前、也就是日期刚变成一月九日的时候从浮游城艾恩葛朗特第七层的赌场都市沃尔普塔启程了。

因为我们是一月五日上午到达的第七层，所以在第七层停留的时间还不满四天。然而就在这几天当中，无数的回忆深深地刻在了我的心里。当然，亚丝娜也是、绮兹梅尔或许也是吧。

身为沃尔普塔大赌场的实际支配者——妮露妮尔·纳克托伊，以及她的护卫兼女仆——奇欧，她们热情地招待了无依无靠漂泊至此的我和亚丝娜。妮露妮尔甚至还提议说「干脆别去第八层了，就在这沃尔普塔生活下去吧」，我当时还真的认真考虑了一下这个提议。

她之所以会这么劝说，并不单单是因为很中意我们。在一连串难以避免的机缘巧合下，我将血献给了《夜之主（Dominos Nocte）》——也就是吸血鬼妮露妮尔，因此变成了她的眷属《夜之民（Civis Nocte）》。

在封测时没有发生过这样的事件，而且封测时我也没见过妮露妮尔和奇欧，更没有听说过玩家吸血鬼化的传言，所以这个夜之民状态大概是正式运营后才实装吧。也就是说，有关这个状态的情报，就连《鼠》之阿尔戈都没有掌握到。

当然，妮露妮尔把她所知的一切都告诉了我们，不过在她长达三百多年的人生当中，绝大部分时间都没有离开过赌场，所以我没能从她那得到像是与各种怪物的相性、以及对其他属性参数的影响之类的实战数据。

目前能知道的特性，有《害怕银》《不会老化》《不定期饮血的话就会衰弱》《暴露在阳光下就会即死》，其实和现实世界的虚构作品里登场的吸血鬼大差不差。硬要说的话，比起人血，龙血的效果更好这一点倒是很独特，也正因如此，我在一段时间内就算不用吸别人的血也能存活。因为妮露妮尔用第七层楼层BOSS《火岩巨龙阿基艾拉（Aghyellr the lgneous Wyrm）》所掉落的大量龙血，帮我制作出了纳克托伊家秘传的《龙血药剂（Dragon Blood Potion）》。

用度数很高的烈酒稀释龙血，再加入几种草药就是这种药剂的做法。据说只要每周喝上一管，就能避免衰弱死亡。而药剂足足有三十管，算下来足够我用半年多了，就算万一用光了，只要回到沃尔普塔就可以得到补充。

因此，看样子是可以不用我的獠牙吸血了，关于银的话，只要多加留意避免接触就好了，但问题还是在于阳光。据妮露妮尔所说，要是被阳光直射到，似乎不出十秒就会烧尽，随后化作一团灰烬随风散去。〔译：布嘎！〕

除了艾恩葛朗特的最顶层之外，每一层的上方仅一百米处就是下一层的底部。所以从理论上来讲，阳光照进来的时间应该只有清晨和傍晚的一小段时间而已。但不知是凭借着游戏里独有的奇妙力量，又或者是某种魔法设定，在晴天的时候，太阳光就仿佛能穿透浮游城的所有楼层一样，从上方的楼层底部十分灿烂地倾洒下来。

因此，如果在白天毫无防备地走到屋外，我就会必死无疑。就算是穿上有厚实兜帽的披风，再将全身都紧紧地包住，并且一直待在阴影处，但只要被阳光漫反射到，也还是会陷入《日光中毒（Sun Poisoning）》的状态，在这个状态下，不仅所有属性值都会下降，还会持续削减HP值。

也就是说，在找到解除吸血鬼状态的方法前，我都只能在夜间行动。我本以为在迷宫里就是安全的，但迷宫里偶尔也会有阳光照射进来的地方，所以也并非绝对安全。妮露妮尔、奇欧、亚丝娜和绮兹梅尔也都反复叮嘱我「白天的时候绝对不能到外面去」。我也明白安全是最优先要考虑的事——毕竟如果真的被阳光照到、化作灰烬之后，我在现实世界里的大脑也会被NerveGear给烧焦——但要是从早到晚都只能闷在拉着窗帘的旅店房间里的话，那就实在是太难受了。

不过话又说回来，吸血鬼化所带来的并不只有负面影响。力量值、敏捷值、以及技能熟练度都会上升，视觉上也会给予很大的黑暗补正，因此在迷宫中并不需要光源。不仅如此，还可以毫无副作用地使用在沃尔普塔得到的传说级长剑《哀伤夜想曲（Doleful Nocturne）》。〔译：简中翻译为《忧郁小夜曲》，但doleful更多的是「哀伤」「悲伤」的意思，而nocturne是夜曲，小夜曲则是serenade，完全是不一样的东西。改成「哀伤夜曲」的话会有些不通顺，因此直接用日本那边对「nocturne」的翻译，也就是「夜想曲」〕

现在装备在我背后的剑，是展示在大赌场的最高级奖励、有着《沃尔普塔之剑（Sword of Volupta）》别名的剑。想要换到它得需要十万枚筹码、换算成钱的话就是一千万珂尔的这样一笔巨款，当然，这把剑也有着与价格相称的效果，不仅基础数值很高，还有着毒免疫、HP自动恢复、暴击率上升这三种特殊效果。

虽然攻略集团的主力公会，《龙骑士团（Dragon Knight Brigade）》以及《艾恩葛朗特解放队（ALS）》都想要得到这把剑，但经历了一番波折之后，最终还是由我成为了这把剑的所有者。然而说实话，比起得到一件强力新武器的喜悦，我更担心的是如何让DKB和ALS接受这个事实，不过以事后诸葛亮的角度来看，在我手里或许才是最好的结果。

因为这把沃尔普塔之剑，或者该说哀伤夜想曲，是有着「持续削减装备者经验」这一恐怖负面效果的魔剑。不过如果装备者是吸血鬼的话，就不会削减经验值，并且要是用双手全力挥剑的话，还会飞出赤红的光之刃。

我和亚丝娜、阿尔戈以及绮兹梅尔，能从沃尔普塔出发后仅仅不到两小时就到达第七层迷宫区的最上面的安全屋，也是多亏了魔剑哀伤夜想曲的强劲性能。虽然没能用上「毒免疫」的效果，但光是在战斗中能自动恢复HP、以及有效命中必定会暴击这两点就已经足够有用了。即使一次性碰上多只怪物，用出水平四连击剑技《水平四方斩（Horizontal Square）》也能将怪物一扫而空，就算不能一口气将怪物的HP削减到零，也肯定能把怪物击退或者击倒在地，因此，我们以昨天攻略时完全想象不到的乱来打法，在迷宫区中不断突进。

但令人有些意外的是，本应是哀伤夜想曲的最强能力——光之刃，其实是一种十分难以操控、字面意思上的投掷型道具。

射程距离有十米以上，威力也远远强于单发剑技。虽然只要击中，几乎所有怪物都会被秒杀，但不想让光之刃击中——比如敌人的身后有队友时——的情况也并不少，而在这种情况下，我就无法使用《双手持剑的全力斩击》了。虽说我原本就是单手剑士，哀伤夜想曲在系统分类上也是单手直剑，但因为剑柄的长度比起一般的单手直剑来说长了一些，所以在要以普通攻击造成巨大伤害时，我就会本能地想用双手握住剑。实际上，这一路走来的途中，我使出浑身解数的双手斩击时，大概有三次不经意地发射出了光之刃。不过幸好没有伤到亚丝娜她们，但要是继续像这样《手滑发射光之刃》的话，迟早会出意外的吧。

要不干脆为了不让我双手握剑，直接改变我的信条，转变成持盾单手剑士得了……就在我思考着这类事情的时候。

我的左肩突然增加了些许重量。我微微转头后，发现亚丝娜的头靠在了我的肩膀上，正发出「呼、呼」的轻微鼻息。

从歪掉的连帽斗篷的缝隙间，露出了亚丝娜那白皙的后颈，这副毫无防备的样子不禁让人心头微微一颤。我又下意识地舔了舔牙齿，但倒也没有产生咬上去吸血的冲动——至少现在还没有。即使如此，我觉得一直盯着看也不太好，便急忙把脸扭了回去。虽然我的身体稍微动了一下，不过亚丝娜依然熟睡着。

这也难怪。我们昨天上午打败第七层楼层BOSS后，直到日落前都一直留在迷宫区当中，然后晚上回到沃尔普塔跟妮露妮尔以及奇欧她们道别，过了晚上十二点后再沿着原路返回，又一直打到了迷宫区最上层附近，日程的安排就是如此高强度。

现在的时间是凌晨两点十五分。因为我和亚丝娜在之前一直都是在白天攻略的类型，平常早就在这个时间睡觉了。虽然我很想让她像这样再睡一会，却又不能这么办。

即使如此，至少再睡十五分钟、不，三十分钟就好……在我这么想的时候，这次则是从右侧传来了脚步声。

走进了安全屋的，是身着黑银相间的铠甲和浅黑色斗篷的黑暗精灵。也就是琉苏拉王国槐树骑士团的近卫骑士、绮兹梅尔。

我们是在第三层的《精灵战争 战役任务（Campaign Quest）》中初次见面的，至今已经相处了将近一个月的时间。但直到现在，我看到她那凛然的身姿时，也还是经常会被她的存在所深深吸引。

绮兹梅尔是Sword Art Online这个MMORPG中的角色——也就是NPC。但她现在留意到靠在我身上睡觉的亚丝娜时，所露出的温柔微笑，任谁都无法认为这只是预设好的表情。

绮兹梅尔将视线移到了我身上，用极其微弱的音量低声说道：

「让她再睡一会吧」

「嗯。侦查辛苦了」

我也小声道谢。虽然我们大概在十五分钟前才来到这个房间，但绮兹梅尔放下行李之后就说要查看前方的情况，马上就又出去了。当然，我和亚丝娜也想跟着一起去，但却被她以「那样就不算是侦查了」为由而拒绝了。绮兹梅尔虽然是近卫骑士，但也擅长隐秘行动——所以才被允许单独执行任务，她钟爱的斗篷上也被赋予了强力的隐身效果，夜视能力虽说不如吸血鬼化的我，但也算是很高了，所以哪怕是一个人也能在狭窄的迷宫中搞定绝大多数怪物。

问题在于遭遇敌对玩家或者NPC的时候，不过她和我们约定了「碰到的时候不硬拼，会直接折返回来」。但从她的表情来看，似乎是没有碰上敌对玩家或NPC。

绮兹梅尔微微点头后，几乎没有发出声音地在我的右侧坐了下来。悦耳而略带沙哑的低语声再次传进了我的耳朵当中：

「从这里到隐藏房间的通道里，只有三只覆铠蜥蜴（鎧トカゲ）在徘徊。妮露妮尔大人在白天设下的「蜘蛛」也纹丝未动，看来堕落精灵似乎也没有回来过」

「这样啊……」

这次则是我轻轻点了点头。

所谓的「蜘蛛」，就是妮露妮尔凭借能力驯服的一种名为《小巧潜伏蜘蛛（Tiny Lurking Spider）》的怪物。从外观上来看，它是一种体长约五厘米的纯黑色蜘蛛，要是出现在现实世界中的家里的话，别说是我妹妹直叶了，就连我肯定也会发出惨叫吧。不过，作为这个世界里的怪物而言，它可以说是最小等级的了。妮露妮尔给那只蜘蛛下达了「感到危险就逃跑」的简单命令，然后让它潜伏在隐藏房间的门附近的暗处当中。要是门有开关动作的话，蜘蛛就会对震动产生反应而逃跑，所以要是蜘蛛还待在原地的话，就可以证明门没有被动过。

虽然我认为用些更简单的方法就好，比如在门缝里夹上一小片纸之类的。但仔细想想的话，在这个世界当中，《被放置在野外的物品》从原则上来说会不断削减耐久值、最终必定会消失。仅仅一小片纸估计连半天都坚持不了，而要是用耐久值更高的金属片之类的东西作为标记的话，又会有被堕落精灵发现的危险。

而在这一点上，如果是使役状态的怪物，HP就不会自行减少。不过作为代价，如果不给它们喂食的话，忠诚度就会不断降低，直到最终解除使役状态。但妮露妮尔的使役能力极为强大，所以即使让它们处于待机状态而置之不理，也能维持一天以上……说出这段话的并不是妮露妮尔本人，而是一脸得意的奇欧。

总而言之——

「……门没有打开也没有关闭的话，也就是说这一层的秘钥果然在昨天就被夺走了吧」

「看来是这样了……不知道回收秘钥的是白檀骑士团还是枸橘骑士团，只能祈祷没有出现牺牲者了」

「毕竟堕落精灵刚在第六层的加雷城损失了近三十名士兵，我认为他们应该没有正面袭击骑士团精锐的余裕哦。那些家伙大概是用擅长的毒和烟幕来制造混乱，趁机只把秘钥夺走了吧」

「确实……呢。在那次袭击过后，那些堕落精灵为了从我这种不成熟的人手里抢走秘钥，还特意派副将军来了呐」

我从她的话中感到了一丝自嘲之意，我半无意识地伸出右手，用指尖轻轻地触碰放在冰冷石砖地面上的绮兹梅尔的左手。

「绮兹梅尔是我们在艾恩葛朗特遇到的人当中，最出色的……不、呃，是极其、无比出色的两位骑士中的一位哦。仅仅只输了一次而已，没有必要这么贬低自己」

「……呼呼……」

我刚说完，绮兹梅尔就发出了轻微的笑声，随后马上道歉道，

「不，抱歉。我只是觉得桐人也变得能立刻说出这种安慰人的话了呐……」

「这、这种程度的安慰，我在之前应该也说过吧……」

绮兹梅尔听了我的反驳后，再次微笑了起来，但却轻轻地歪了歪头：

「不过，另一位骑士是谁？是拉维克·冯·科尔塔西奥斯大人吗？」

「啊—……」

我眨了眨眼，回想起了在哈林树宫见到的那位留着胡子的黑暗精灵骑士。

据说在树宫的监狱中被关了三十年的他，在一开始的几分钟里对我们相当冷淡，但当他得知亚丝娜的细剑是自己的弟弟打造并强化的之后，他便干脆利索地越狱了，并帮我们营救出了绮兹梅尔。

他那超群的剑技和智谋、以及可靠的英雄气概，完全就是我心中的骑士模样。然而，刚才第一时间浮现在我脑海里的却是另一个人的面孔。

「那位大叔也确实是一位出色的骑士，而且我也受了他很多照顾。不过毕竟相处的时间连半天都不到，就把他和绮兹梅尔相提并论，这还是有点……」

我刚回答完，绮兹梅尔就好奇地继续问道：

「所以是谁？」

「呃……虽然其实算不上骑士就是了，他和我都是冒险者，是个叫迪亚贝尔的人」

「迪亚贝尔……我没有见过他呢」

「嗯。我和亚丝娜认识绮兹梅尔之前，他就在和第一层的楼层BOSS……守护兽的战斗中死去了」

我用余光看到绮兹梅尔略微瞪大了眼睛，然后继续说明，

「将一团散沙的冒险者们，凝聚成攻略集团的就是迪亚贝尔。要是没有他的话，不管是我还是亚丝娜，说不定都还留在第一层」

「原来如此……确实可以称得上是位了不起的人物。愿骑士迪亚贝尔的灵魂能在圣大树的身旁安息」

绮兹梅尔闭上了眼睛祈祷着，我也效仿着闭上了眼睛。

恐怕名为迪亚贝尔的玩家，已经在现实世界的日本某处、被NerveGear烧毁大脑而死亡了吧。但假如真的存在灵魂的话，迪亚贝尔的灵魂会不会为了亲眼见证这个世界的终局，而以某种形式残留在SAO当中呢。

他在临死前留下了这句话「之后就拜托你了、桐人先生」。他既做过隐藏身份试图买下我的锻炼之刃的事，也做过为了抢夺楼层BOSS的LA奖励而孤身冲出去的事，虽然他显露出了这样人性的一面，但他想要将游戏通关——想要将囚禁在SAO中的一万人解放出来的心情绝非伪物。正因为DKB的领队林德、以及ALS的领队牙王都感受到了那份心情，所以他们才继承了迪亚贝尔的遗志并日以继夜地奋斗着。虽说我很想改变他们一有事就针锋相对的情况就是了。

因为祈祷中混入了杂念，于是我睁开眼睛看向视野右下角。凌晨两点二十五分。因为出发时间是三十分，所以差不多该把亚丝娜叫醒了。

我将手伸向靠在我左肩上熟睡着的搭档，犹豫了一会后，轻轻地戳了戳她的脸颊。从指尖传过来的触感是难以置信的光滑与柔软，我一瞬间完全呆住了，但事到如今也没法把手缩回去了。

我接着又用食指进行了两三次突刺攻击后，亚丝娜的眉毛微微地动了动。我迅速把手缩了回来，然后呼唤她：

「亚丝娜，到时间咯」

「嗯……姆咿斯……」

亚丝娜一边发出谜之声音，一边抬起眼皮来，随后大概只用了三秒左右就明白了自己是靠在什么东西上，并以完全不像是刚睡醒的反应速度，飞快地挪开了身体。她将侧坐的姿势迅速改成正坐，然后一脸严肃地开口说道：

「……就不能一下子把我叫起来吗」

「哎呀—，你呼呼大睡的那副模样实在是让人不忍心叫醒哦」

「才没有呼呼大睡呢，也就是小憩一会吧」

「不不，倒不如说你是睡得很沉的类型哦」

「什么类型？」

看到亚丝娜疑惑地皱起眉头，我回应道「什么都没有」，然后将视线转到了右边。我察觉到绮兹梅尔似乎想要说些什么，便急忙开口道：

「差不多该出发了吧」

绮兹梅尔点了点头站起身来。我和亚丝娜也紧跟着她，猛地站了起来。要是在现实世界的话，这样做很可能会让大脑的供血不足、从而眼前一黑晕过去，但就算是SAO也没有把如此细致的生理现象模拟出来。

绮兹梅尔拍了拍斗篷上的尘土，随后一脸认真地看向这边：

「——桐人、亚丝娜」

刚一被叫到名字，亚丝娜就立刻接上了话：

「绮兹梅尔，不管你问多少次，我和桐人君的回答都是不会改变的哦。不管前方等着的是怎样的危险……不，要是有危险就更不用说了，我们是不会让你一个人去的。因为，我们是……我们是、那个……」

我转头看了一眼欲言又止的亚丝娜，同时也在寻找着能恰如其分地形容我们三人之间关系的话语。

在第三层的森林当中，我和亚丝娜发现了战斗着的森林精灵骑士和黑暗精灵骑士，并且站到了后者——当然指的是绮兹梅尔——那边为其助阵。在封测时我也做出了同样的选择，但森林精灵骑士用他的刚剑不断地削减我的HP，就在我觉得「这下完了」的瞬间，黑暗精灵骑士发动了自爆攻击，两个NPC最终同归于尽了。

我本来以为正式运营时也会是同样的发展，但没想到亚丝娜以有如神助的剑技扭转了败局的剧情走向，在绮兹梅尔用出杀手锏之前，我们就把森林精灵骑士给击败了。绮兹梅尔那时目瞪口呆的表情，我至今都难以忘记。

总之，我和亚丝娜从那以后就开始协助绮兹梅尔完成回收秘钥的任务了。所以客观来讲，应该算是《雇主和打工的》的关系，但我并不想把这段关系看成是纯粹基于金钱的关系。就连被困在SAO之前就是个网瘾游戏玩家的我都是这么想的，对于平等地把每个NPC都当作真人来对待的亚丝娜来说，肯定更是如此吧。

在我们沉思着的时候，绮兹梅尔突然浮现出了一抹笑意，开口说道：

「我把亚丝娜和桐人当作一生的朋友哦。恐怕连蒂涅尔也不会相信我有一天会对人族抱有这种感情吧」

听到绮兹梅尔说出了已故妹妹的名字，亚丝娜猛地冲上前去，紧紧地抱住了她。然后就这么在她的耳边嗫嚅道：

「我也把绮兹梅尔当作一生的朋友哦。所以，别再说「一个人去」了」

「……啊啊，我知道了」

绮兹梅尔也抬起双手，温柔地拍了拍亚丝娜的后背。紧接着，她朝我这边伸出右手，用眼神示意我也过去接受拥抱。

以前的我大概只会紧张得直晃脑袋吧，不过绮兹梅尔已经拥抱过我好几次了，而且我也鼓足勇气拥抱过亚丝娜，反过来被她拥抱的情况也有那么几次了。于是我收紧腹部，大步走上前去，将紧紧依偎着的亚丝娜和绮兹梅尔一起抱在了怀里。

一瞬间，亚丝娜的身体猛地颤抖了一下，不过幸好她的身体没有抗拒，也没有出声拒绝。绮兹梅尔也用右臂环住了我的后背，略微用力地抱着我。

由于骑士的臂力实在是太大了，我被迫紧紧地贴在了两人身上。

虽说我们三人都在上半身穿了金属防具，但身体各处的柔软与温度还是不由分说地传递了过来，我不由得心跳加速了起来，但在这时也无法脱身了。

这只是虚拟体、这只是虚拟体——我在脑内反复默念着，继续拥抱了大约五秒。终于，绮兹梅尔的手臂从我的身上离开了，于是我赶紧拉开了距离。亚丝娜也结束了和绮兹梅尔的拥抱，往后退了一步，还稍稍瞥了我一眼。

虽然我试图解读那对榛色眼眸中所蕴含的情感，但亚丝娜很快就把脸转开了。我将无处安放的视线移到右下角，发现已经二点三十分了。

「好……好了，走吧！」

对于我那稍显生硬的宣言，绮兹梅尔应了声「嗯」，而亚丝娜则默默地点了点头。

** 第2章

刚一走出安全屋，又冷又干的空气就缠上了我的脖子。

因为这个第七层是常夏楼层，在攻略过程中，我感觉自己每隔一小时就会嘟囔一句「好热」，不过迷宫区内倒是相当凉爽。因为昨天攻略迷宫区的时候我并没有这样的感觉，所以可能是因为火龙阿基艾拉被打倒了，因此迷宫区内的气温才下降了吧。明明最后一击是我打出来的，在得出这个推测的瞬间，我的心中却无端地涌起了一阵落寞，但现在可没有沉浸在感伤里的闲工夫。

就算楼层BOSS已经死了，杂鱼怪也还是会不断出现，而且其他队伍也有可能在这里狩猎。不过，现在最应该警惕的还是NPC——堕落精灵。

堕落精灵副将军《剥伐的凯萨拉》曾以强得不讲道理的剑技将我们击溃，虽然她不太可能出现在这种地方，但堕落战士和堕落斥候也有着不容小觑的力量。可以的话我还是想不碰到他们的，所以绮兹梅尔才主动进行了先行侦查，但只要稍有大意，敌人就会精准地瞄准我们的破绽发动攻击，所谓SAO就是这样的游戏。

因此，我全功率地运行我那吸血鬼化后所强化的五感，确信周围没有玩家和NPC的气息之后，才对身后的两人点了点头。我将哀伤夜想曲从背后的剑鞘中拔出来，以我在最前方、亚丝娜和绮兹梅尔并排站在我身后的正三角形队形沿着道路前进。

和绮兹梅尔说的一样，我们在走了五十米后碰上了三只覆铠蜥蜴——正式名称是《板甲巨蜥（Armour Plated Monitor）》。由于它身上那泛着金属光泽的板甲外皮，本来的话除了打击武器之外是很难造成什么伤害的，但我用哀伤夜想曲的光之刃就直接秒杀了一只，剩下的两只也进入了眩晕状态，亚丝娜和绮兹梅尔立刻靠上前去，瞄准了覆铠蜥蜴的弱点——头部下方，然后一人一只巧妙地将其击败了。

第七层最强级别的杂鱼怪物都能如此轻易地获胜，实在是让人想在这多刷一会经验值。但是，「利用光之刃进行先制攻击」的战斗方法，在无法提前发现远处敌人的情况下很难使用，贪心可是禁忌啊……我这样告诫自己，随后继续前进。

之后，我们再也没有遇到怪物，顺利地抵达了目的地——死胡同尽头。

尽头处的石壁乍一看和左右两边的墙壁没有任何区别，如果之前不是妮露妮尔注意到了的话，我是绝对不会知道这里还有一扇隐藏门的吧。我在石壁前停下脚步，仰起头来。

我定睛凝视着天花板附近，只见靠近天花板的暗处有一只小孩拳头大小的黑色蜘蛛贴在那里。那就是妮露妮尔作为警报装置而设置的《小巧潜行蜘蛛》。在野生状态下，这种蜘蛛会悄无声息地从洞窟等地的天花板上落下来，试图去咬玩家的后颈，是SAO「令人不快的害虫怪物排行榜」上的常客。

然而，一想到它是遵从着可能再也见不到的主人的命令，在这个地方一动不动地待了半天多的时候，我心里就不由得产生了一丝怜悯。现在我也能理解妮露妮尔在下达待机命令时，为什么对着蜘蛛用小得只有我能听见的声音说「抱歉呐」了。

「另一边似乎没有别人的气息」

听到绮兹梅尔的声音后，我回过神来点了点头：

「我也什么都没听到，不过开门的时候还是先躲到旁边吧」

「那么我在左边，桐人和亚丝娜在右边吧」

绮兹梅尔的判断很合理。打开那扇暗门的时候，门两侧剩下的墙壁宽度最多也就四十厘米左右，身穿铠甲的绮兹梅尔是无法和另一个人藏在一起的。

话虽如此，几乎全身都是布制装备的我和亚丝娜也不是小孩子了，在四十厘米宽的地方硬挤的话，就只能前后紧紧贴在一起了。我转过身向搭档确认站位：

「前面和后面，你选一个吧？」

随后，亚丝娜原本看向黑蜘蛛的脸转了过来，花了两秒钟左右理解问题的含义之后，皱着眉头回答道：

「后面……不、前面吧……果然还是后面吧」

我对此没有异议，所以马上同意了。我将剑收回到剑鞘当中后，带着亚丝娜走到死胡同右边的角落，并站到了她的面前。在确认绮兹梅尔也在另一侧藏好之后，我伸出左手，用指尖沿着石壁的缝隙摸索。

正如记忆中的那样，移动的手指在一个地方卡住了，我不由得松了一口气。这个直径不到一厘米的小洞就是打开隐藏门的钥匙孔。

我收回左手，摸索着腰带上的皮制飞针套（holder）里的飞针。五根中的四根都是我之前一直在用的市售钢制飞针，只有最左边一根的形状是与众不同的。

我谨慎地将其抽出来，这东西长度不到十厘米，宽约八毫米，与其说是飞针，倒不如说是钉子。它的横截面呈六边形，带有轻微的螺旋纹路。整体近乎纯黑，表面散发着的湿润光泽比起金属，倒更像是贝壳或者昆虫的甲壳。

这个飞针道具的名字是《休马尔格亚之刺（Spine of Shmargor）》，是只有极少数堕落精灵才会装备的稀有物品。飞针本身会持续分泌等级2的麻痹毒，因此毒性无论使用多少次都不会消失，是一件相当麻烦的东西〔译：这里和之前的设定冲突了，SAOP5中提到飞针上的麻痹毒只能使用三次〕。

虽说绮兹梅尔戴着黑暗精灵女王陛下赏赐的解毒戒指，而我和亚丝娜也能用《冥想》技能给自己上耐毒buff，但要是一个不小心刺到自己的手指而麻痹，那可就不只是被笑话这么简单了。我一边小心翼翼地注意着，一边将毒针的尖端插入墙壁的孔中。

由于孔的断面也是六边形的，所以我一边将螺旋状的毒针向右旋转，一边缓缓推进。不一会，针的尖端就碰到了一个坚硬的东西。尽管我在十几个小时前就做过完全相同的操作，但此刻还是会不免地感到紧张。我一边感到身后的亚丝娜紧紧地抓住了我的外套，一边用力地推了一下毒针的底部。

嘎锵，响起了一声细微的金属音——就在听到这个的瞬间，石壁的中央部分开始发出沉重的震动声、开始向下滑动。我抬头看去，只见被震动惊扰的黑色蜘蛛，遵循着妮露妮尔的命令——「感到危险就逃跑」，迅速沿着天花板逃走了。

等到使役状态解除之后，那只蜘蛛应该就会回到原本的工作上、也就是从上方落下咬住玩家的脖子。我抱着「辛苦了」的慰劳心情，同时也抱着「千万别咬我们」的深切愿望目送着蜘蛛离开，然后将目光又转回到石壁上。

三列横向排列的石块组成的宽约七十厘米的隐藏门，正好完全沉入了地面当中。一阵格外沉重的震动「咚」地一声隔着短靴传了过来，随后，周围又恢复了寂静。

我们躲在暗门的两侧，暂时探寻着里面的动静。我用强化过的听觉确认里面既没有呼吸声也没有衣服摩擦的声音后，我拔出了插在墙里的飞针。随后一边用手摸索着插回到皮带上，一边用眼神向对面的绮兹梅尔示意，迅速进入了隐藏房间当中。

我们三人刚一通过，石壁就又从地面中开始缓缓上升了。这里应该是没有传感器的，所以大概是设置成了拔出飞针后几秒便会自动关闭的模式吧。内侧的墙壁上应该也有相同形状的孔洞，但现在并没有必要去找它。

里面是一个横向宽度不到三米的小房间，不出所料，既没有人类，也没有精灵和怪物。取而代之的是镇座在房间中央的巨大物体。

一个直径九十厘米、厚约十厘米的圆盘固定在地面中央，安装在外围的四根细细的柱子，支撑着在两米高处的另一个圆盘，圆盘和柱子呈现出一种黯淡的金绿色光泽，我无法确定那是金属材质还是打磨过的木材。上下两个圆盘上都雕刻着精细的同心圆状花纹，其中心还刻有两条交叉的锯齿状线条。也就是堕落精灵使用的「冰与雷的纹章」。

据妮露妮尔所说，这似乎是《古代转移装置》。昨天听到这里时，我还惊讶于SAO里居然会有这种科幻风格的机关，但仔细想想的话，每一层的主街区也都有着功能完全相同、只是外观不同的《转移门》。再加上黑暗精灵和森林精灵也会使用《灵树》在各楼层间往来，所以转移本身似乎不是什么特别稀奇的东西。

但问题是，我们完全不知道这个转移装置究竟连接着哪里。

昨天从黑暗精灵骑士团那里抢夺到秘钥的堕落精灵，肯定是使用这个转移装置转移到了某个地方。虽然刚才在安全屋里和绮兹梅尔聊起这件事的时候，不得不使用了假定形，但这件事其实已经可以确定了。因为作为精灵战争 战役任务第五章《红玉秘钥》的任务日志被连续更新了，上面清楚地写着这件事。

【黑暗精灵部队回收的红玉秘钥被堕落精灵夺走了。追踪他们并夺回秘钥吧】

【夺走秘钥的堕落精灵在迷宫区消失了踪迹。去查明他们的去向吧】

【发现了可能是夺走秘钥的堕落精灵使用过的转移装置。追踪他们并夺回秘钥吧】

游戏系统应该是不会说谎的，所以可以认为这个圆盘就是转移装置，而且夺走秘钥的堕落精灵使用过这个转移装置也是确凿无疑的。只是，任务日志上轻松地写着「追踪他们并夺回秘钥吧」，却完全没有保证转移后的目的地是安全的。

「……这个东西、是站上去就会转移吗」

亚丝娜喃喃道，绮兹梅尔对此点了点头：

「因为没看到类似操作盘的东西，那估计就是这样吧。……我有个提……」

一听到这里，我和亚丝娜就异口同声地宣言道：

「「一起去吧！」」

「……但是，我们完全不知道传送的目的地是个什么样的地方、又会出现什么状况哦」

「正因如此才要一起去哦」

我向绮兹梅尔靠近一步，压着声音说道，

「不管是怎样的状况，比起一个人，肯定还是三个人要更安全的。转送装置有可能是单程票，也有可能使用过一次之后就暂时用不了了，而且……」

——在这种剧情展开当中，如果只有一个人先传送过去，肯定会发生意外导致无法与队伍汇合的，这种套路实在是太经典了啊。

我正想这么说下去，但最终还是咽了下去，转而说出了另一句话：

「而且，如果我说要一个人先去的话，绮兹梅尔也会反对的吧？」

「……确实是这样呢」

绮兹梅尔轻轻地呼出一口气后，挺直了背继续说道，

「不过，如果转移到的地方很危险的话，必须要听我的指挥哦。要是我让你们逃走，就一定要逃走，明白了吗？」

「…………」

我和亚丝娜对视了一瞬间后，再次同时做出了回答：

「「知道了」」

绮兹梅尔的表情马上缓和了一些，用怀念般的语气说道：

「小时候，我和蒂涅尔要是像这样同时回答的话，母亲总是会数落我们『光这时候答应的挺快呢』」

「啊—……我也被这么说过」

「外婆也这么说过我」

我和亚丝娜这么回应之后，绮兹梅尔应了声「这样啊」，随后收起了笑容再次面向转移装置：

「那就出发吧」

「嗯」「好」

我和亚丝娜再次同时说完之后，我站到了绮兹梅尔的左边，亚丝娜则站到了右边。

虽说挤一挤的话还是能让三个人同时站在圆盘上的，但支柱与支柱之间的间隔只有六十厘米多一点，所以没法横着并排走上去。绮兹梅尔首先登上了圆盘，我和亚丝娜也紧跟其后。考虑到可能会在目的地发生战斗，我觉得最好提前把剑拔出来，但反过来想，拔出剑来也很可能会惹来麻烦，所以我最终只是做好了拔剑的准备。

封测时期经常发生这样的麻烦事：玩家手持武器传送后，在目的地与其他玩家发生摩擦，或者全速冲进转移门导致在目的地引发碰撞事故。因此，就产生了「在转移时要收起武器、慢慢走进转移门」的规矩，而且这一规矩也延续到了正式运营阶段。当然，现在并不是在意这种规矩的时候，但从绮兹梅尔没有拔出军刀的举动来看，精灵们或许也有类似的经验法则吧。

我一边想着这些事，一边调整身体方向，让自己和两人背靠着背。就在这时——

脚下和头顶的圆盘上刻着的纹路开始从外侧发出青色的光芒。随着光芒向内侧扩散，我们的身体也被相同颜色的磷光包围。BUN、BUN，低沉的震动声和磷光同步脉动着。

我低头看着脚下的圆盘，心想「只有堕落精灵的纹章没有发光啊」的那一瞬间。

青色的光芒急剧增强，将整个视野都给涂满了。一瞬间，我感到身体仿佛飘了起来，随后短靴底部又再次触碰到了坚硬的平面。

还没等青色的光芒消散，我就蹲下身子，同时抬起右手，以便在必要时能立刻拔出背上的剑来。

被染成青色的视野，仿佛是故意让人着急似的，缓缓地恢复了色彩。最先映入我眼帘的是质地粗糙的石壁。由于和几秒前所在的隐藏房间的墙壁几乎一模一样，我一度以为是又转移到了原来的地方，不过我又注意到整体的色调有些微妙的不同。

「总觉得是个很相似的房间呢……」

亚丝娜在我背后轻声说道，紧接着传来了绮兹梅尔「是啊」的回应声。就像两人说的一样，不管是房间的构造和大小，还是头顶上方和下方的圆盘，都和转移之前别无二致，但建造房间所使用的石材种类看起来似乎稍有不同。先不说传送到了哪里，至少房间内没有敌人。

我向前走出一步，等亚丝娜她们从圆盘上下来之后，又再次站到了圆盘上面。

「等等、桐人君！」

我向慌张呼喊的亚丝娜示意「没关系」后，便低头看向脚下。在确认最外侧的纹路开始发出青色的光之后，我立刻就从圆盘上下来了。

大概是察觉到了我的意图吧，亚丝娜等到光芒完全消失之后，才压低音量继续抱怨道：

「你要是打算做什么的话，就不能先说一声再去做吗」

「抱歉抱歉。只是先确认一下能不能用这个东西回去啦」

亚丝娜瞪了一眼道歉的我，说了句「真是的」后，环顾了一下房间：

「这个房间里也没有门呢……」

「应该是和刚才的房间相同构造的隐藏门吧」

「也就是说，打开的时候也会发出很大的声音吧。附近要是没有敌人就好了……不过说到底，这里是第几层啊」

亚丝娜歪着头说道，我眨眨眼后回答：

「欸，难道不是第八层吗？」

「也不一定吧。转移门不是也能通往很远的楼层吗」

「嘛，话是这么说啦……但从剧情发展来看，真的有不是第八层的可能性吗……」

就在我自言自语的时候，响起了绮兹梅尔疑惑的声音：

「既然不知道的话，那调查一下不就好了？」

「欸……就算说调查，可该怎么调查？」

我和亚丝娜同时转头看向绮兹梅尔，只见骑士微微耸了下肩，然后用右手的手指在空中晃了晃：

「当然是用《幻书之术》了。幻术之术不是即使身处在没去过的地方，也能告诉我们当前在哪一层吗？」

「…………」

我和亚丝娜再次对上了视线。这么一说还真是。虽说要是在初次来到的楼层打开菜单窗口的地图的话，整个地图都会呈现灰色，只能看清极近处的地形，但楼层数还是会清楚地显示出来的。

因为亚丝娜用眼神催促我赶快去看地图，于是我清了清嗓子，抬起右手，将食指和中指并拢竖直划下，呼出菜单窗口，然后立刻切换到地图选项。

「「欸……!? 」」

不仅是我，就连伸过头来看的亚丝娜也发出了惊讶的声音。

点开的地图是一片灰色——我原本如此确信，不，是已经做好了这个觉悟，但地图却散发着蓝色的光芒。看来房间外面似乎是迷宫，复杂交错的通道以及其他房间都被详细地标注了出来，未探索区域还不到两成。从当前所在的房间到最近的通道的地图虽然也是灰色，但距离最多不过三米。也就是说，我曾经从离这个房间很近的地方经过过。

我在一秒钟内确认了这些信息后，便将视线移到了地图的右上角。在那里显示着的楼层数是——

「「第四层!? 」」

我又一次和亚丝娜一起叫了出来。听到层数的绮兹梅尔也不禁轻呼了一声「嚯」。

我一边听着绮兹梅尔逐渐靠近的脚步声，一边用两根手指不停地缩放地图。地图的比例尺随即缩到了最小，迷宫的地图缩小不见了，圆形楼层的全貌显现了出来。

我们所在的位置是楼层的最南端。也就是说，这个迷宫恐怕就是迷宫塔吧。

迷宫区的西北方是山岳地带，东北方则有着巨大的湖。那条流入湖泊的河流，蜿蜒着横穿了整个楼层，一直延伸连接到最北端的主街区。从这独特的地形来看，这里肯定就是令人怀念的第四层。

「第四层的迷宫区里居然有这种隐藏房间啊……」

我如此自言自语之后，突然意识到了什么，又补充了一句，

「也就是说，如果在攻略的时候就发现了这个房间的话，是不是就可以跳过第五层和第六层，直接前往第七层呢……？」

「不至于这么简单吧。要么就是隐藏门打不开、要么就是装置启动不了，这两点总得占一个吧？」

亚丝娜如此指出后，我觉得也确实是那么回事。而且说到底，就算以攻略第四层时的等级和装备转移到了第七层的迷宫区，别说BOSS火龙阿基艾拉了，就连杂鱼怪也赢不了吧。

我用手指将地图放大，把显示内容再次切换回迷宫内部，接着再用两根手指搓动地图。地图随即向后倾斜，变成了迷宫塔的各楼层堆叠在一起的立体显示图。

「这个房间在……总共二十层中的第十八层吗。下去得花多少时间啊……」

我刚不经意地说完，亚丝娜就用略带严肃的声音回应道：

「对啊，离天亮就剩不到三小时了。根本不可能在三个小时内从塔里下去，再前往主街区洛比亚吧……」

「也是啊。虽说攻略这座塔时用了还不到三十分钟，但那时是因为有阿尔戈和子爵大人呢」

「毕竟子爵大人实在是太强了啊」

就在我和亚丝娜四目相对的时候，绮兹梅尔用有点像是闹小脾气的声音说道：

「以防万一我确认一下，你们没忘记我也在那里吧？」

「怎、怎么可能会忘啦！」

在我用力摇头的同时，亚丝娜也在我身边慌忙地跟着附和：

「只是在用那时候的队伍构成和现在来比较啦。怎么可能会忘记绮兹梅尔也帮了我们呢」

「……呼呼，只是开玩笑哦」

绮兹梅尔轻轻笑了笑，随后表情变得认真起来，

「确实，子爵大人的实力自不必多说，阿尔戈的潜行技巧也很厉害。不过我和亚丝娜也变强了，至于桐人，现在的实力应该能抵得上当时三人的总和吧」

「哎呀，最多也就2.5人吧」

亚丝娜用眼神示意我别再自夸了，于是我清清嗓子，继续说道，

「嘛，我们既知道路线，这个迷宫里应该也没有特别难缠的怪物，所以我认为就算再久，一个小时之内也能出去了。不过，就像亚丝娜刚才说的那样，不管怎么想也不可能在两小时内到达洛比亚吧，所以要不把目标定在更近一些的乌斯克村怎么样」

「不行！」

亚丝娜立刻大声反驳。她甚至没留给我反应的机会，便气势汹汹地继续说道，

「就算是乌斯克村也有四千米左右的距离吧。而且，你不会忘了我们只能用船在这个楼层的水上移动吧？虽说塔前面的码头上应该停泊着好几艘攻略集团的船，但因为要逆流而上前往乌斯克村，所以不能保证两个小时之内就能到达哦」

「…………确实」

面对亚丝娜条理清晰的主张，我只能点头同意。然而今天距离日落还有将近十四个小时。在堕落精灵使用的隐藏房间里度过这段时间太危险了，所以我们应该先回到第七层的迷宫区，在安全屋里小憩一会，又或者顺着第四层迷宫区的BOSS房间里的楼梯爬到第五层，前往主街区卡尔鲁因——就在我这么思考的时候。

「什么啊，因为你们刚才一直在说子爵大人的事，我还以为你们本来就打算那么做呢」

因为绮兹梅尔说出了这种话，我和亚丝娜都不由得歪起了头。

「那个打算……是？」

「就算不特意前往人族的城镇和村庄也没事，去尤菲尔城不就行了吗。虽然确实需要逆流而上一段距离，但行程的一半以上都可以顺流而下哦」

「…………」

和说出「打开楼层地图不就行了吗」时一样，我和亚丝娜再次对视了。

所谓的尤菲尔城，是建在迷宫区东北方向的湖泊上的一座黑暗精灵城堡，刚才我们谈话中提到的《子爵大人》——列休连·泽德·尤菲里斯卿就是那座城堡的城主。他的剑术实力在我遇到的NPC中属于顶尖水平，也是能在我个人主观的「好人排行榜」中进入前五名的高尚之人，但问题是，他真的会在凌晨四五点被叫醒后，还能愉快地迎接我们吗。

「嘛……子爵大人好像是夜行性的人，所以应该没问题吧？」

亚丝娜似乎读出了我的思考，于是这么说道，但她的表情并不是百分百的确信。而且说到底《夜行性》也只是一种印象吧。

不过绮兹梅尔却一脸平静——甚至还浮现出一丝微笑回应道：

「没有问题，你们可是和森林精灵的湖上战中的大功臣啊。不管是清晨还是半夜，都会盛大地款待你们的吧」

「款待……倒也不至于这样吧」

我苦笑之后，最后再看了一眼楼层地图，将第四层南部的地形记在脑子当中。随后关掉窗口，用力挺直身体。现在距离凌晨三点还有十几分钟的时间。

「好，用一小时下去，再用三十分钟前往尤菲尔城吧」

对于我提出的这个高难度目标时间，亚丝娜和绮兹梅尔毫无紧张感，只是轻松地回答「嗯」「了解」。

** 第3章

我们花了不到三十秒就找到了隐藏门的钥匙孔。

以防万一，我还是先隔着墙壁探寻了一下周围的气息，然后才将《休马尔格亚之刺》插入钥匙孔里，启动了开门装置。石壁的一部分随即沉到了地面当中，和第七层迷宫区的隐藏房间完全一样。

也就是说，将飞针从钥匙孔中拔出来的话，门不到五秒钟就会开始关闭，所以我让亚丝娜她们先出去后，才将飞针拔了出来。我一边感受着背后传来的墙壁升起来的声音和震动，一边确认周围的情况。

这种湿乎乎质感的石壁，毫无疑问就是第四层迷宫区的感觉。作为楼层BOSS的半马半鱼的怪物、《海马·维斯格（Wythege the Hippocampus）》已经被打倒了，而且从陆路也很难到达这里，所以我觉得应该不会有玩家特意跑到这里来狩猎……但还是有必要保持警惕的，因为堕落精灵随时有可能会从隐藏房间里出来、或者正准备进入隐藏房间啊。

在确认暂时是安全的后，我向两人示意，开始沿着通道前进。

仅仅走了五六步，我们就来到了一条稍宽的通道上。从地图上看，我们之前似乎走过这里，但我却并没有明确的记忆。我们当时之所以没有进入这条通往隐藏房间的通道，是因为这里明显就像是死胡同，而且当时也急着去BOSS房间吧。

总之，因为我们知道该怎么往下走，所以一边小心留意着，一边尽可能地快速前进。虽然不可避免地会遭遇一些杂鱼怪，但现在的我们也不可能会在第四层的敌人面前陷入苦战，我们一遇到怪物就立刻将其解决掉，然后继续赶路。

正如预定的那样，我们只花大概三分钟就能突破一层，于是转眼间就到了第十层。我们决定在这一层的中央安全屋里稍微休息一下，在查看地图确定了路线之后，我们朝着安全屋以最短路线前进，就在只差一个拐角就能到达的时候——

「……！」

我迅速举起左手，示意身后的两人停下来。我又小心翼翼地往前挪动了两三步，嗅着空气中的气味。

在第四层的迷宫区，到处都有着从墙壁和天花板里流下来积聚的水，所以空气中弥漫着一丝潮湿的味道。要是其中混杂着不同的气味，那就是怪物出现的前兆了。

然而，我的嗅觉在此刻捕捉到的那一丝微弱气味，不、应该说是香气，毫无疑问是人工制造出来的香气。那股香气就像是在烤肉和香草……不，或许不是「像」，这根本就是烤肉和香草的味道吧。我转过身，轻声对亚丝娜和绮兹梅尔说道：

「总感觉……有股很香的气味？像是烤肉一样的……」

「欸……？唔—嗯，这么一说……」

「既像是有烤东西的味道，又像是没有……」

看着两人抽动鼻子的含糊表情，我并没有从中感受到疲惫的神色。我也觉得自己还能继续战斗，所以完全可以放弃休息直接前往下一层，但话虽如此，我也想知道这股香气究竟是饥饿导致的幻觉，又或是真的有人在烤肉。〔译：吃货桐人上线了（笑）〕

「……要不稍微从远处看一下安全屋怎么样？就只看一眼」

我这么一问，亚丝娜就微微歪了歪头：

「嘛……没问题吧？安全屋里面不可能有怪物，堕落精灵也不会在迷宫里烤肉吧」

这么一说的话，其实其他NPC也不会这么做吧，更不用说玩家了。不过光在这里干想也没用。我一边在脑海中描绘出前方的地图，一边小声地下达了指示：

「在下一个拐角右转，有个二十米左右的笔直通道，在通道中间偏左的位置就是安全屋的入口。我们蹑手蹑脚地走到那里，然后往里面偷看一眼吧」

我用眼神回应了点头的两人，然后再次开始移动。到达拐角之后，我小心翼翼地探头查看前方。

和记忆中一样，昏暗的通道笔直地往前延伸，中间偏左的墙壁上有着一个小小的出入口。甚至无需定睛细看，就能确认有淡淡的橙色光芒从那里透了出来。而且，光源的位置相当低。

因为安全屋里并没有常设的篝火之类的东西，所以几乎可以确定是有人在里面点了火。我仔细确认怪物没有刷新之后，十分小心翼翼地沿着通道向前走去。

还没走出三米远，我就得到了确信。果然有一股像是在烤肉的气味。而且，我曾在某个地方闻到过极其相似的香气。

我努力压制住想要加快速度前进的双腿，蹑手蹑脚地走完了剩下的七米，随后将后背紧紧地贴在入口旁的墙上。我瞥了一眼右边，确认亚丝娜和绮兹梅尔也做出了相同的动作后，正准备悄悄地朝里面窥探一下的时候——

「不用躲在那里了，进来聊聊怎么样」

一个男人的声音突然从房间里传了出来，我吓得身体一颤。

那低沉的声音虽然有些沙哑，却依然清晰有力，仅凭这一点就足以说明对方绝非等闲之辈。更何况，他到底是怎么发现我们藏在这里的？我们已经将脚步声和衣服的摩擦声压制到了极限，即使我们身上会散发出某种气味，也该被这浓郁的烤肉味给掩盖了才对。

先不管他是怎么发现我们的，「安全屋里的男人已经看穿了我们的存在」这一点是确凿无疑的。虽说我们也可以选择后退，拉开安全距离之后再一口气冲向通往下一层的楼梯。但如果那个男人是堕落精灵的话，那他就有可能带着被夺走的秘钥。而且迷宫的安全屋只是「怪物无法进入」，并没有防犯罪代码的保护，所以如果真的打起来，室内战斗的不确定因素要比在通道上少不少。

「……怎、怎么办？」

听到这句话，我回头看了一眼，只见亚丝娜略带不安，而绮兹梅尔则一副若有所思的表情。我只是简单地说了一句「走吧」，随后将哀伤夜想曲紧紧地握在手中，走进了安全屋当中。

首先映入眼帘的是微微摇曳的火焰。只有三根粗细约两厘米、长约三十厘米的树枝堆在一起，形成了一个像是过家家般的篝火。在篝火上架着一个十分精致小巧的烤架，而在烤架上放着的小平底锅当中，小小的肉块正发出轻微的滋滋声。

我用一瞬间确认了这些细节后，终于将视线移向篝火后方坐着的人影。



由于平底锅挡住了火光，所以他的脸处于阴影当中，但勉强可以看到修剪整齐的胡子和健壮的脖颈。果然是男人——而且从脸部轮廓来看，他那突出的尖耳，毫无疑问是精灵的耳朵。

他是堕落精灵吗，我全身紧绷地想着这个问题。

几乎与此同时，我身后的绮兹梅尔发出了充满惊讶的声音：

「拉维克大人!? 」

「哈!? 」「欸!? 」

我和亚丝娜也同时叫了出来。紧接着，男人头顶上方终于出现了黄色的光标，但此时我的夜视能力已经适应了篝火的亮度，阴影中的脸也逐渐清晰起来。

正如绮兹梅尔所说，悠然地注视着我们的人，正是我们在哈林树宫遇到的黑暗精灵囚犯、同时也是前任白檀骑士团团长——拉维克·冯·科尔塔西奥斯，这是不可能看错的。

在拉维克的催促下，我、亚丝娜和绮兹梅尔在小小的篝火旁坐了下来。我强忍住被平底锅吸引的视线，重新将目光转向这位原骑士团团长。

除了原本十分浓密的络腮胡和唇须被剪短、以及衣着稍微整洁了一些之外，他的样子和我们在第七层分别时一模一样。不过仔细想想，那次越狱事件发生在一月六日的上午七点左右，到现在还不到三天。对于长寿的精灵族来说，容貌是不可能在短短几天内就发生巨大变化的。

比起那个，本应踏上旅途的拉维克，为什么会出现在迷宫区呢？而且，又为什么在烤肉之类的东西呢？

不，准确地来说并不是单纯的肉。而是把肉糜、洋葱还有香料混合在一起揉好，再捏成椭圆形肉排的料理。我只在艾恩葛朗特见过一次这样的料理。这道料理是隐居在第六层的加雷城、自称《大贤者》的布弗鲁姆老人的拿手菜、富利卡特尔（Frikadeller）——也就是汉堡排。

明明其他该问的东西如山一样多，我却怎么也无法抑制食欲——不，是求知欲，我开口向拉维克问道：

「请问，这个是富利卡特尔吧」

一直盯着平底锅的拉维克，露出有些惊讶的表情看向了我，

「你居然知道呢，桐人。富利卡特尔的名字和做法，就算在第九层的王都里也已经失传很久了。你是在哪听谁说的？」

「呃……是在第六层的加雷城，从一位叫布弗鲁姆的爷……贤者大人那听说的」

我刚回答完，拉维克就抬起了右边的眉毛，接着嘴角微微一动，露出了笑容：

「原来如此。那你也接受过那个老头……贤者大人的试炼吗」

「欸……嗯，嘛。也就是说，拉维克先生也……？」

回答就只有这个，但我已经明白了。眼前的这位原骑士团团长，也曾被老人施加过《将刚出炉的富利卡特尔放在眼前，还得保持内心平静三小时》的地狱试炼。

「顺带一提桐人哟，你试炼合格了吗？」

被再次询问之后，我稍微犹豫了一下，然后点了点头。我努力克制住想要看向坐在左边的亚丝娜的视线，把目光牢牢地固定在前方。关于那个试炼，我是用《整整三小时一门心思地想着亚丝娜》的方法通过的，不过，我实在是没有那个胆量告诉她本人。

拉维克露出了像是在咬紧牙关忍着什么的表情，然后一本正经地宣言道：

「剑士桐人哟，那么你也有资格享用这个富利卡特尔」

他接着看向绮兹梅尔和亚丝娜，

「骑士绮兹梅尔、剑士亚丝娜，抱歉，我不能分给你们。这不是在故意刁难你们，而是我和贤者大人之间的约定」

「好、好的……不，这倒是没关系……」

绮兹梅尔难得用一副跟不上状况的表情回应之后，清了清嗓子继续说道，

「其实我们没有太多时间可以慢悠悠地待着了」

随后不到两分钟，绮兹梅尔就对拉维克说明了目前的状况——我们正在追踪夺走秘钥的堕落精灵的事、我变成了《夜之民》的事、以及必须在天亮之前抵达尤菲尔城的事。

听完了这一切的拉维克，用前所未有的严肃表情对我开口道：

「为什么不早点说这些呢。现在可不是聊富利卡特尔的场合吧」

「那、那个，可是气氛好不容易才……」

「没时间在这磨磨蹭蹭了，一分钟之后就从这里出发。你们也赶快做好移动的准备吧」

「那、那个，刚刚您说我有资格……」

在拼命解释的我面前，拉维克不知从哪掏出一把银色的叉子，猛地插进那色泽诱人的富利卡特尔当中，然后举起了滴着肉汁的汉堡排。

「啊……啊啊！」

他完全不顾我的惨叫，大大地张开了嘴，仅仅一口，不算小的富利卡特尔就消失了一半，不到三秒之后，剩下的一半也消失在了他的胡子当中。〔译：只是你不想分给桐人吧（笑），桐人何时才能吃上汉堡排〕

「啊啊啊啊啊！」

原骑士团团长一边咀嚼着富利卡特尔，一边熟练地收拾好平底锅和烤架，并往篝火上浇了水将火扑灭。奇怪的是，尽管这三根树枝在我们来之前就已经在燃烧了，但烧焦碳化的却只有最前端的一小部分，而且地板上也完全没有落灰。

拉维克小心翼翼地把树枝捆好，放回到皮袋当中，然后猛地站起身来。他拿起靠在墙上的那把大型军刀——我记得名字应该是《Sabel of Santalum Knights（白檀骑士军刀）》——挂在左腰上，接着转过身来：

「让你们久等了。从这里开始我也和你们同行吧」

已经站起身来的绮兹梅尔和亚丝娜同时低下了头：

「感谢，拉维克大人」

「谢谢你，拉维克先生」

他们三人随后朝着出入口走去，我摇摇晃晃地起身，恋恋不舍地深吸一口飘散在空中的余香。

毕竟拉维克曾经率领着守护琉苏拉王国的、三大骑士团中和槐树骑士团与枸橘骑士团并驾齐驱的白檀骑士团，他的剑术只能用「豪壮」来形容。

与舞蹈般流畅美丽的绮兹梅尔的剑截然不同，那是一把追求一击必杀的刚剑。也正因如此，他在挥剑结束时会出现些许破绽，当同时面对多个怪物时，敌人就有可能靠近到他身旁，但即使敌人逼近到眼前，他也丝毫没有慌张的样子。如果来得及就用剑来应对，要是觉得来不及，就连踢踹和冲撞等手段也会用出来，以便拉开距离，他战斗的方法可谓是灵活多变。

回想起来，我在哈林树宫也只见他挥过两次剑而已，第一次是砍断门锁的时候，第二次则是击倒卫兵的时候。光这两次就足以让我确信他绝非普通人，不过有些东西也只能在实战中才能体会到。

在第三次遭遇怪物时，拉维克只用了一记突刺就将一只坚硬的螃蟹型怪物给粉碎了，在这时，我突然感觉记忆受到了某种刺激。

我总觉得以前在什么地方见过类似的剑法。然而，我却怎么也想不起来是谁的招式。说起使用军刀的人，那自然会想到绮兹梅尔，但她的剑法和拉维克完全不同，曾经袭击第六层加雷城的堕落精灵指挥官也装备着一把军刀，但他的剑法并没有给我留下深刻印象。如果把范围扩大到使用弯刀的人，堕落精灵的副将凯萨拉装备着一把罕见的日本刀，可她也只是在施展范围型剑技《旋车》的时候挥舞过那把刀而已。拉维克没有使用过同样的剑技，说到底，军刀也不可能用出日本刀剑技。

我甚至想干脆问问拉维克的流派或者师父是谁，但他正为了我而着急赶路，我有点不好意思聊些无关紧要的话题，就这样犹犹豫豫间，我们已经下到了迷宫塔的第一层。从二十层下来大概花了二十分钟，这速度比之前快了不少，不仅弥补了在安全屋里消耗的几分钟，甚至还有富余。

虽说现在还是凌晨三点五十分，从迷宫塔的入口望去，视野中的野外区域也被黑暗所笼罩着。不过再过一个小时，东边的天空就会泛起鱼肚白吧。

「你们三人不休息也没事吗？」

拉维克这样问过我、亚丝娜以及绮兹梅尔后，我们三人同时点了点头。明明他是我们中最年长的，而且还一直在前方持续战斗着，却依然十分地镇定自若，享受了轻松的我们可不能说出泄气的话。当然，勉强自己可是绝对不行的，所以我用余光偷偷看了一眼亚丝娜的样子，不过她的站姿依然稳健。

「那走吧」

拉维克利索地说完之后，将军刀收到鞘中，然后朝着迷宫塔外走去。

一从入口大厅走到外面，凉爽的夜风便轻拂着脸颊。看到亚丝娜和绮兹梅尔都一脸惬意地深呼吸，我也不甘示弱，尽情地舒展了一下身体。

虽说在迷宫区内没有特别留意，但其实这里的气温和第七层完全不同。那边即使到了夜晚，体感气温也超过了二十五度，而第四层的晚上满打满算估计也就十五度左右吧。虽然还称不上寒冷，但如果可以的话，我还是不想在河内游泳的。

我一边祈祷着ALS或者DKB的凤尾舟还留在原地，一边沿着在支撑着迷宫塔的岩盘上开凿出来的楼梯往下走。再往前就是一条深邃的峡谷，沿着流淌在峡谷当中的溪流逆流而上，应该就能到达将整个第四层连接起来的一条大河。

楼梯上没有照明之类的东西，下了三十级台阶后，四周就变得漆黑一片。以我被强化的视力都只能勉强看到脚下，更不用说亚丝娜了，精灵们想必也是……就在我这么想的时候，走在最前面的拉维克手中，悄无声息地亮起了光芒。

我定睛一看，在构造简单的灯罩当中，一个小小的蘑菇正散发着淡淡的绿色光芒。这毫无疑问就是只生长在第七层《摇岩之森》的送火茸。这种十分脆弱的蘑菇摘下来不到三十秒就会枯萎，拉维克到底是怎么让它在灯里存活下来的呢。

——不，我在以前也有过相同的疑问。我记得从沃尔普塔的中央广场通向位于大赌场的妮露妮尔宅邸的秘密通道当中，也是用封入了送火茸的灯来照明的。当我询问是如何让蘑菇存活的时候，女仆奇欧就颇为得意地回答我「如果你不向妮露妮尔大人宣誓效忠、成为纳克托伊家的侍从的话，那我可不能告诉你哦」。

我虽然没有成为妮露妮尔的侍从，但眷属应该也有着差不多的分量吧。真后悔在离开沃尔普塔之前没有询问蘑菇灯的制作方法……我一边懊悔着，一边沿着曲折的楼梯往下走，不久便听到了哗哗的水流声。转过最后一个拐角，一个大型的码头便映入了眼帘。

刚一看到码头，走在我前面的亚丝娜就猛地转过身来：

「你看，我就说吧！这里应该有船的！」

我一边嘟囔着「我可没说没有吧……」回应这位一脸洋洋自得的细剑使，一边走下了最后的几级台阶。

这个码头只是把峡谷的岩壁削成了细长的凹字型，再用石头砌出了靠岸处而已。话是这么说，如果算上背后的楼梯，单靠人力建造这样的工程也一定十分费力。不过这么说的话，那么高达百米的迷宫塔——精灵们所说的《天柱之塔》究竟又是谁建造的呢。

如果精灵战争任务继续推进，这些设定或许也会逐渐揭晓，但那也是夺回被抢走的秘钥之后的事了。虽然堕落精灵的足迹在迷宫区的隐藏房间里中断了，但如果他们转移的目的地不是第八层而是第四层的话，那我对他们的去向倒是有些头绪。不过显然是不可能贸然闯入的。因为那里可是有……

「嚯，还真是相当气派的船呢」

拉维克的声音打断了我的思考。

只见前任骑士团长站在码头的边缘，比较着两艘在波浪中微微摇曳的凤尾舟。

右侧停泊的是将船体涂成蓝色、船舷涂成白色的凤尾舟，这是DKB建造的「利维坦号（Leviathan）」。左侧的则是将船体涂成苔绿色、船舷涂成深灰色的凤尾舟，这是ALS建造的「解放号（Liberator）」。两艘都是无愧于其华丽名字的、可搭乘十人的超大型船只——当然，是作为凤尾舟而言。

「真的能擅自使用这样的船吗？」

就连拉维克似乎也有些担心地回头看了看，我立刻点头回应：

「没关系的，船主们暂时不会使用……应该说他们再也不会用了吧」

「真浪费啊。既然不用，应该能卖不少钱呢」

「那些家伙一到了下一层，就会马上把上一层的事给忘得一干二净哦」

「这还真是，简直就像是枸橘骑士团的那些猪头一样呢」

我看着哈哈大笑的拉维克和强忍着笑意的绮兹梅尔时，亚丝娜戳了戳我的侧腹：

「呐，桐人君」

「我刚想起来，用绳索或船锚固定的船，不是只有船主才能开动吗……？」

「啊啊……」

我瞥了一眼两艘大型凤尾舟。因为码头边没有系船柱，所以两艘船都抛下了船锚。确认这点之后，我向一脸不安的亚丝娜回答道：

「确实如此，用绳索停船的时候会一直保持锁定状态，不过用船锚停船是有时间限制的。我记得好像是七天……不对，十天吧……第四层攻略完是在十二月二十七日，今天是一月九日，不管怎么算，锁定状态应该都已经解除了」〔译：这是新加的设定，SAOP3里并没有时间限制的设定〕

「欸，是这样吗」

「蒂涅尔号(Tilnel)的说明书上是这么写的……大概……」

突然没了自信的我，为了确认记忆而朝着两艘凤尾舟靠近。两艘船除了颜色之外完全一样，所以其实选哪艘都行，但比起DKB的林德，ALS的牙王忘记船的事情的概率似乎微妙地要高一些，所以我选择了左边的解放号，纵身一跃跳上船。

我抓住从船首的固定装置上垂下来的锁链，用力一拉，瞬间就感受到了一股沉重的阻力，不过锁链还是伴随着轻微的声响开始动了起来。确认到船锚从河底被拉起的手感后，我立刻松开了手：

「似乎能开！」

我大声呼喊过后，亚丝娜他们便依次从岸边跳上了船。等三个人各自在想坐的位置上安定下来后，我再次握住了锁链。这次我将船锚直接拉了上来，然后把鹤嘴锄形状的船锚横放在船底。

虽然已经能够顺利地操控凤尾舟了，但系统上的所有者依然是牙王。我的脑海中浮现出了他的刺猬头，在心里默念「稍微借用一下啦」，然后走到了船尾。

我握住收起来的长桨，把桨叶沉入到水中。幸好驾船的方法还刻在我的身体当中，不用思考，双臂就自然而然地动了起来。

我让凤尾舟缓缓后退，离开了码头，利用河水的流向将船头转向了上游。足有蒂涅尔号两倍大小的船体的反应有些迟钝，但也正因如此，它非常稳定，即使稍微粗暴地操控、船只也不会摇晃。

「好，出发！」

听到我的说话声，亚丝娜头也不回地用悠闲的声音回应道「好—」，绮兹梅尔转过身说「拜托你了」，拉维克则默默地举起了右手。

我重新握紧船桨，用全力划动，解放号便逆着水流、强而有力地向前行进了起来。

从贯穿山体的支流进入在平地上蜿蜒的宽阔主河道，大约花了二十分钟。

之后我们顺流而下，只用了十分钟左右就到达了目的地的湖泊。虽说如此，距离上也不过五千米，换算成时速还不到每小时十千米。或许用脚跑还更快些，但那也是在碰不到怪物的前提下，而且第四层根本就没有像样的道路。

当然，河里也会出现螃蟹、青蛙、鳌虾等水生怪物，不过那些试图跳上凤尾舟的家伙都被可靠的乘客们一一击退了。等解放号的船头滑进广阔的湖水中时，应该差不多就是预定的四点三十分。这样一来，天亮前应该能从容地进入尤菲尔城了，就在我松了一口气的时候。

「不好意思，能让我那边的岸边下船吗」

拉维克突然说出这样的话来，我下意识地竖起了船桨。凤尾舟慢慢减速，在离湖约五十米的地方——副本区域的边界稍靠前的地方停了下来。

「为什么，拉维克大人不是也要去尤菲尔城吗？」

绮兹梅尔毫不掩饰困惑如此问道，原骑士团团长罕见地含糊其辞：

「唔姆……嘛、确实是这样，不过有些情况让我难以从正面拜访……」

亚丝娜小声叫道，转头看了我一眼，然后又看向精灵们，

「难道是因为在第七层越狱了……吗？」

「啊……」

我也后知后觉地反应过来。

我们四人已经从哈林树宫中越狱三天了。最迟昨天，传令兵应该把通缉令送到了各层的城堡和要塞。尤菲里斯子爵作为城主，也不可能无视这件事。

我对歪着头的绮兹梅尔犹豫地开口道：

「呃，绮兹梅尔和拉维克先生，还有我和亚丝娜，都是从哈林树宫的地下监狱里逃出来的越狱犯……如果尤菲尔城已经得到这个情报的话，可能会有点麻烦吧……」

「啊啊，这件事啊」

绮兹梅尔点点头，略带歉意地继续说道，

「我应该早点告诉你们的。虽然不能说是绝对，但九成是不用担心的」

「欸……为什么？」

面对一脸茫然的亚丝娜，这次则是拉维克苦笑着解释道：

「哈林树宫的那些神官们，总是喜欢放大骑士团的失态，到了自己失态的时候，无论多小都会尽力隐瞒。像是从树宫中一次性逃出四名囚犯这样的大失误，他们怎么可能对外泄漏呢」

「原、原来如此」

看来黑暗精灵的神官们就像是许多奇幻作品中常见的《宫廷官僚》那样的人物。虽然在攻略第四层时曾在尤菲尔城的大食堂里瞥见过他们，但由于没有直接接触，我从未想过他们竟是如此自私的一群人……想到这里，我才终于想起了一件事。

在第六层的加雷城，我们遇到了公会《Q扎古》的四名成员。他们自称是专注于完成任务的公会、和我们一样选择了黑暗精灵阵营来推进精灵战争 战役任务，为了接受第六层的秘钥回收任务而来到了加雷城。

那时的我，陷入了存在论（Ontology）的困惑。第六层的神社中封印的《玛瑙秘钥》在那时已经被我、亚丝娜和绮兹梅尔回收了。但任务的关键道具会根据接受任务的玩家或队伍数量而生成。也就是说，如果Q扎古完成了任务，他们也会带回玛瑙秘钥，这样一来，本应是独一无二的秘钥却会同时存在多个。绮兹梅尔和其他精灵们该如何解释这个矛盾呢——

然而，绮兹梅尔似乎察觉到了我的困惑，主动解释道，在各层神社的真秘钥被回收之后，神官们会制作仿造的秘钥放回神社，再由其他黑暗精灵士兵或接受委托的冒险者们多次回收。这是对森林精灵的欺瞒行动，实际上，运送假秘钥的黑暗精灵士兵遭到森林精灵士兵袭击而丧命的情况也确实出现过。

听到这里，我被一个超过了这个矛盾本身的疑问所困扰：究竟是ARGUS的员工为了消除复数秘钥的矛盾而不惜牺牲多个NPC，还是游戏系统本身要牺牲多个NPC呢，当时我并没有深入思考绮兹梅尔说的话。但现在回想起来，绮兹梅尔在那时就已经告诉我，策划并执行这种无情的欺瞒作战的正是那些神官们。

如果是那样的一群人，试图掩盖自己的失态——比如越狱事件——也就不足为奇了。然而，这样一来他们会不会在事件曝光之前就偷偷解决掉问题呢……这种可能性也不是没有……

「但是，拉维克大人」

听到绮兹梅尔的声音，我不由自主地抬起了盯着脚下的视线，看向两位黑暗精灵。

「如果您认为城里不知道越狱的事，那为什么还犹豫去拜访呢？」

被这么一问，拉维克一边摸着短短的胡须，一边思考了大约五秒钟，随后轻轻摇了摇头：

「现在还不能解释」

「这……样啊」

绮兹梅尔看上去没有完全接受，目光转向我和亚丝娜。这时，拉维克突然深深地低下了头：

「虽然有很多事不能说出来让我很过意不去……但、还有一件事能拜托你们吗」

「……什么事？」

我小心翼翼地开口问道，这位原骑士团团长缓缓抬起头：

「今晚，希望你们能把城主尤菲里斯卿带到我下船的地方。不要告诉他我在这里、也不要带护卫或随从，就只有他一人……可以吗」

** 第4章

在夜雾——也有可能是晨霭当中，湖面笼罩着一层白色的薄纱，我们缓缓向南前进，前方不久就出现了一个巨大的影子。那就是黑暗精灵在第四层的据点——尤菲尔城。

由于北侧没有停船的地方，我们绕过城堡西侧，从南面接近。城的四周耸立着高高的尖塔，屋顶则覆盖着石板。五层高的城馆既优雅又厚重，黑暗精灵的审美在每一个角落都得到了充分体现。

支撑城堡的是一座天然小岛，不过前面用花岗岩块平整过，一座宏伟的大栈桥从那里延伸到湖水中。栈桥两侧各停泊着两艘比解放号稍大的凤尾舟，悬挂在栈桥尽头的灯所散发出来的光芒在水面上反射，闪烁着微光。

这幅景色就像风景画一样美，但上次来访时，黑色的凤尾舟总共有八艘。然而其中的一半在与森林精灵的湖上战斗中被击沉了。即使第二天它们悄无声息地复活，包括我在内的玩家大概也不会抱怨什么吧，不过这个世界要是能允许这种事情发生的话，那秘钥重复的问题也就不会设定地那么复杂了。

借着青白色的灯光，我缓缓地将船靠近。右侧的东边天空似乎开始微微泛白了，但目前还感觉不到明显的变化。如果进不了城可能会有点麻烦，但真到了那时候，只要自曝越狱犯的身份、让他们把我关进地下牢房就行了。

我一边想着这些，一边操纵解放号向大栈桥的右侧靠近。正门两侧和四座尖塔顶部都有着卫兵的身影，但目前还没有响起警戒的号角声。

在经过停泊的两艘黑色凤尾舟，正准备调转船头的时候。

「太好了！！」

亚丝娜突然叫了起来，我急忙刹住船问道：

「咋、咋了？」

「你看，那边！」

亚丝娜从左侧船舷探出身体，指向栈桥的根部。我定睛一看，晨霭中隐约浮现出一个白色的影子。

我再次放倒船桨，以极慢的速度前进，白色的影子逐渐显现出来了。那是一艘纯白与翠绿相间的凤尾舟。虽然比解放号小得多，但那艘宛如工艺品般优美的船，正是我们的爱船——蒂涅尔号。

这次我将解放号向左掉头，在船头即将碰到栈桥的瞬间停下。

「桐人君，辛苦了！」

「驾船辛苦了！」

亚丝娜和绮兹梅尔一边说着，一边跳上栈桥。虽然我想立刻追上她们跑向蒂涅尔号，但得先固定好解放号。

在将缆绳系在栈桥的系船柱上后，除了所有者牙王之外的玩家将永远无法解开。问题在于，我不清楚抛下船锚会发生什么。如果当前的解锁状态能持续下去就好了，但如果又要等七天或十天才能移动，那将船开回到原处的时间就会大大延迟。

……嘛，莫得事莫得事〔译：桐人此处是在模仿牙王的关西腔〕。

我在心里默念着，将船锚抛入湖中，随即跳上栈桥，急忙朝亚丝娜她们的方向赶去。

两人站在蒂涅尔号系泊的系船柱旁，目不转睛地凝视着纯白的船体。我也站在绮兹梅尔身旁，眺望着我们的爱船。虽说停泊期间的耐久度当然会收到保护，不过船身上连一丝污渍都看不到，涂装依旧光鲜亮丽。

「虽然在这种情况下说有点奇怪……但能再次看到这艘船，真是太好了」

绮兹梅尔突然低语道。

仔细想想，我们之所以会来到尤菲尔城，是因为第七层迷宫区的隐藏转移装置连接着第四层。也就是说，如果堕落精灵没有抢走秘钥，我们也就不会像这样与蒂涅尔号重逢吧。虽然在这种状况下确实不能一味地高兴，但如果一直紧绷精神的话，在关键时刻就无法集中注意力。

「在城里睡一觉之后，绮兹梅尔你下午就和亚丝娜一起乘船吧」

我这样提议，绮兹梅尔一瞬间露出了想说些什么的表情，但马上就微笑道：

「嗯，就这么办吧……要是能醒来的话」

两人在蒂涅尔号上乘船游玩的光景一定很美吧，但遗憾的是，我不仅不能同行，甚至连在栈桥上远远眺望都不被允许。所谓的夜之住民到底意味着什么，看来我以后就会逐渐体会到吧……正当我沉浸在这不合时宜的感伤中时——

从城堡方向传来了「喀嚓」一声轻微的金属声，我们不约而同地朝那边望去。

我眯起眼睛看向昏暗的远处，只见巨大的拱形正门——不对，是正门右侧的便门打开了，一个纤细的人影从中出现。他左手提着灯，但那光芒反而干扰了我的视线，我只能勉强看清人影的轮廓。

正门两侧全副武装的哨兵一看到人影，立刻哗啦一声转过身去，行了黑暗精灵式的敬礼。人影简短地对哨兵说了几句话，就独自朝我们走来。

哨兵们如此恭敬，难道是城主尤菲里斯子爵本人吗——想到这里，我才注意到对方的身高和肩宽似乎要比子爵小了两圈。我继续盯着看，只见对方的头顶上出现了颜色光标。

光标的颜色当然是代表着NPC的黄色。HP条下方则写着【Cetrann;The Heir of Yofel】。

名字大概读作赛特兰（セトラン）吧。尤菲尔当然是城名。但遗憾的是，我的脑内词典当中并没有「heir」这个单词。

「呃……」

我刚这么嘀咕了一声，不知何时已经站到我旁边的亚丝娜低声说道：

「「heir」是嫡子或继承人的意思哦」

我由衷地表示感谢，再次看向黄色光标。也就是说，那行文字的意思是《赛特兰，尤菲尔城的继承人》吗。

…………继承人？

我皱起眉头的同时，那个人影也开口了：

「绮兹梅尔大人、亚丝娜大人、以及桐人大人，对吧」

是个清爽的男性声音……不如说是少年的声音。停下脚步的人

影放下左手的灯，之前一直被遮挡着的月光在此时照亮了他的脸。



果然，是个和我年龄差不多大的年轻人。那一头卷曲的头发，还有脸上残留的稚气，让我一瞬间以为他是个女孩，但简朴的棉衬衫和黑裤子勾勒出的身形显然是少年——吧，大概。不过，既然是黑暗精灵，那光凭外表是无法推测年龄的。

在现实世界的ACG当中的精灵，既有《从婴儿时期就成长缓慢》的模式，也有《在成年之前以和人类相同的速度成长》的模式。为了了解SAO中的精灵属于哪一种，我曾经问过绮兹梅尔现在多少岁，结果却被说「在精灵族中，当面询问他人年龄是不礼貌的行为」。如果是前一种模式，那这个少年的实际年龄很可能比我要大得多。

然而，和《夜之主》妮露妮尔与实际年龄相符的威严相比，这位少年的举止完全没有架子。面对外表和气质都像是同龄人的他，我正烦恼着能不能好好用敬语的时候，绮兹梅尔上前一步，郑重地敬了个礼：

「槐树骑士团所属、近卫骑士绮兹梅尔，以及协助者人族剑士桐人、亚丝娜。我们在执行任务的途中，想借宿一晚，所以唐突拜访尤菲尔城」

听到这话，少年也将右拳贴在棉衬衫的左胸上，挺直后背报上名字：

「我是尤菲尔城城主列休连的长子，赛特兰·吉·尤菲里斯。正准备朝课的时候，注意到了有船渡湖而来，因此冒昧前来询问来意」

所谓的「朝课」大概是早晨的练习吧。我瞥了一眼他的左腰，发现上面挂着一把细长的细剑。也就是说，这位少年习惯在太阳还没升起的时候就开始练剑，并在准备过程中注意到有船靠近城堡，所以才独自一人前来询问。明明我们可能是伪装成黑暗精灵和人族的森林精灵或堕落精灵，他却连像样的防具都没穿，只带了一把练习用的细剑。

是外表老实却轻率傲慢的类型，还是拥有与行动相匹配的实力呢……我忍不住好奇开口说道：

「呃……我是桐人。我该怎么叫……怎么称呼您呢？」

「叫我赛特兰就好哦，桐人大人」

少年微笑着回答。不过我已经在艾恩葛朗特多少懂得了一点分寸，现在还不至于天真到立刻直呼其名。

「呃，赛特兰大人……」

「请叫我赛特兰」

「啊……那，赛特兰殿下……」

「赛特兰就好」

「…………」

我向亚丝娜和绮兹梅尔投去求助的目光。亚丝娜一眼就能看出在憋笑，而绮兹梅尔虽然表情严肃，但作为长期相处的伙伴，我能看出她也在暗自觉得有趣。

「……那么，呃……我也叫你赛特兰，所以你也叫我桐人，可以吗」

「当然可以！」

赛特兰的脸上顿时绽放出光彩，朝我伸出了右手。我知道精灵也有握手的习惯，但对几乎没什么交流的人族也如此随和，或许正是少年的天真无邪吧。

我一边想着这些，一边脱下了右手的露指皮手套，小心地不用太大力气回握了他的手。

一瞬间，我就改变了一秒之前的看法。少年的手掌皮肤厚实，指根处有着坚硬的老茧。这是每天都坚持严格训练的人的手。我们玩家无论挥剑多少次，既不会长茧、也不会增加肌肉——补充一句，无论是暴饮暴食还是绝食，体重都不会增减一克。自从被困在这座浮游城以来，我第一次为自己光滑的手感到羞愧，随即松开了手。

我后退一步，看向赛特兰的脸时，心里暗叫不妙。因为少年露出了些许惊讶的表情，目不转睛地盯着我，这恐怕不是因为我的手很柔软，而是异常地冰冷。

我想着在他注意到我苍白的皮肤和尖锐的犬齿之前，应该由我说明一下情况才对。但赛特兰瞬间就收起了惊讶的神色，微笑着看向亚丝娜她们。与两人握手后，他微微鞠躬：

「能迎接《尤菲尔湖之战》的英雄们，是我家最大的荣幸。来，这边请」

他用右手指向城堡，随后再次举起灯来，开始带路。

跟在后面时，我的心里又涌现出了新的疑问。赛特兰刚才提到的尤菲尔湖之战，大概是指两周前与森林精灵的湖上战斗吧。虽说感觉已经过去很久了，但以持续了数百年的精灵战争的时间跨度来看，两周不过是微不足道的一瞬而已。比起那个，我更好奇的是城堡的警备为什么如此松懈。

我还有一个疑问。在湖上战斗中，我并没有见过赛特兰。像他这样毫不怯场、而且对自己的实力相当有自信的年轻人，会在那种状况下躲在安全的地方吗。还是说他的父亲尤菲里斯子爵严令他不准出去……？

谜团一个接着一个，但我至少弄清楚了两件事：尤菲尔城还不知道越狱的事、以及这座湖和城堡同名……我在心里默默总结道。

虽然我做好了出示通行证戒指——《琉苏拉的纹章（Sigil of Lyusula）》的准备，但两名哨兵完全没有怀疑，直接就让我们通过了。

赛特兰带我们来到城堡东侧四楼的一间顶级客房。和上次入住时完全一样，这是一间带有一个客厅和两间双人卧室的豪华套房。

「请好好休息一下，城内的设施也请随意使用」赛特兰说完后便离开了。亚丝娜连武器都没卸下，就冲进了右侧的卧室。我正纳闷发生了什么，跟进去一看，发现她正在关窗外的百叶窗。我慢了一拍后也明白了她想干什么，便在房间另一侧的窗户也进行同样的操作。

尤菲尔城作为黑暗精灵的防御据点，百叶窗也是用金属加固的厚木板制成，非常地坚固。上下滑轨没有一丝缝隙，内侧还有固定用的插销。时间刚过凌晨五点，太阳再过一小时就会升起来，不过这样的话，一丝阳光都不会透进来吧。

「呼……」

在关好所有的百叶窗和窗户，连内侧的窗帘也拉上，仔细确认没有其他开口后，亚丝娜终于松了一口气，

「这个房间应该是没问题了。不过第一天就差点赶不上时间……明天无论如何，最晚凌晨三点之前必须回到这里」

接着，站在门口的绮兹梅尔也严肃地补充道：

「紧急情况下，我本来打算用《碧叶斗篷》和我的披风把你全身都包裹起来，但即使如此，也不能保证完全挡住白天的阳光……正如亚丝娜说的那样，必须要提前进入室内，而且为了以防万一，最好还是要准备一下应对阳光的手段」

两人的语气就像是在教导冒失弟弟的深思熟虑的姐姐一样，不过她们确实是真心地为我着想，所以我老实地回答「知道了！」后，又看向绮兹梅尔补充了一句：

「要是有应对阳光的手段就好了，但如果真的存在的话，妮露大人应该早就发现了吧？」

「嘛，确实……——不过，说不定真的有应对手段……」

说到这里，绮兹梅尔微微眯起眼睛，仿佛在看向远方，

「……我记得在妮露妮尔大人的宅邸里稍微提到过，我小时候曾在第九层的王城里远远地见过夜之主。当时我被那比雪还白的皮肤和融银般的头发惊呆了，旁边的父亲告诉我「那是夜之主，是比精灵活得更久的存在」。我当时有点害怕，所以躲到了父亲身后，但现在回想起来，那似乎并不是在夜晚、而是在白天发生的事」

「欸……」

亚丝娜轻呼一声，看了一眼拉上的窗帘后问道，

「是在王城中某个阳光照不到的地方吗……？」

「我希望亚丝娜有一天能亲自去看看，王城的结构非常开放，能完全遮住阳光的地方只有王族居住的宅邸」

——啊，确实确实。

我差点如此附和道，但还是赶紧闭上了嘴。我在封测时去过的王城确实有很多开口，就连谒见女王的大厅当中，阳光也透过树叶倾洒了进来——但现在可不能说这些。

绮兹梅尔似乎没注意到我欲言又止的样子，继续讲述着往事：

「我父亲也是近卫骑士，他曾经的上级退役后担任了幼年学校〔译：「幼年学校」在现实中是从小培养士兵的学校，为日本在世界大战期间效仿德国设立的学校机构，这里无需带入现实〕的剑术教官。那天我去王城是在向教官打个招呼入学后的回家路上。也就是说我当时六岁，顶多七岁……很难想象有人在半夜把那么小的孩子带到王城中去。所以我看到夜之主的时候应该是白天，最多也就是傍晚吧……」

亚丝娜再次惊呼，不过这次却带着微笑，

「幼年学校是在王城里面吗!? 」

「不……不是，虽然学校用地和王城相邻，但不能说是在王城当中」

「那也很好啊！从教室的窗户能看到王城吗？」

「嘛，能看到是能看到……但对小孩子来说，那不过只是个很大的建筑而已。不到一年就习惯了」

绮兹梅尔的回答让亚丝娜略显不满，但很快又微笑起来：

「呼呼，也许吧。我的学校里也有座很漂亮的教堂，刚入学的时候我还觉得有点吓人呢……」

亚丝娜说到这里突然停住，飞快地瞥了我一眼，然后慌张地继续说道，

「那、那个话题以后再聊吧。呃……在绮兹梅尔六岁的时候，太阳还没下山就在王城里见到了夜之主，对吧。也就是说，那位夜之主有某种方法抵抗阳光吗……？」〔译：答案是艾哲红石〕

「只能说是可能有……不过，如果当时见到的夜之主是女王陛下的客人的话……——你看，妮露妮尔大人不是说过吗？森林精灵之王或者我们的女王陛下，可能知道让夜之民变回人类的方法。如果这是真的，那他们知道夜之住民抵抗阳光的方法也不奇怪」

「……确实」

我点点头。然后又回想起了封测时的记忆，黑暗精灵的女王大人还是一位非常非常厉害的药剂师，只有她能制作的灵药在战役任务的最终章里起到了重要作用。如果这个设定在正式运营中也保留了下来，那就像绮兹梅尔说的那样，女王大人能制作出让夜之住民抵抗阳光的药、甚至是可以变回人类的药也并不稀奇。

但遗憾的是，我们目前没有办法前往第九层，即使有办法，在夺回被抢走的秘钥之前，别说谒见女王大人了，就连王城都不可能靠近。毕竟我们三人可是不折不扣的越狱犯啊。

「嘛，只要我小心点就没问题啦。现在的最优先事项还是夺回秘钥，之后再考虑应对阳光的措施就行了」

我这么告诉绮兹梅尔之后，这位骑士的脸上就露出了四成担心，六成愧疚的表情：

「……真的很抱歉。都怪我的力量不够，才让你们陷入了不必要的危险……」

「这种话题不是已经结束了吗！」

亚丝娜跑过去紧紧地握住绮兹梅尔的双手，

「我们只是在做我们想做的事而已。比起这个，我们去洗澡吧！在沃尔普塔的沙滩玩完后没洗成，一路上我都特别想去、特别想去……」

「啊……啊啊，也是。这个时间的话应该没人」

听着两人的对话，我纠结了两秒。在这个世界当中，就算穿着衣服跳进海里，上岸后的一瞬间也会连内衣都完全干透，连盐分的黏腻感都不会残留下来。也就是说，亚丝娜诉求的不适感其实只是错觉罢了，但在SAO中也确实存在仅靠理论无法解决的问题。比如我的脖子和后背现在所感受到的僵硬感。

「我也去哦」

我话音刚落，正跑向走廊门的亚丝娜就用一副奇妙的表情回头看向我。绮兹梅尔则微笑着点了点头：

「嗯，这样也好。离天亮还有些时间」

亚丝娜露出奇妙表情的原因，直到一分钟后我才明白。

尤菲尔城的大浴场位于城堡西侧的三楼。以带有植物雕刻装饰的拱门为界，走廊上的红色绒毯变成了大理石瓷砖，从深处传来了微弱的水声。

更衣室当中摆放着观叶植物的盆栽和带脚凳的藤椅，圆桌上还准备了凉水和新鲜水果。尽头处是通往大浴场的第二道拱门……拱门只有一个。

「啊……」

我终于想起来了，这个大浴场没有男女之分，于是瞥了一眼站在旁边的搭档。与此同时，亚丝娜也用余光看了过来，我立刻试图解释：

「那、那个……我上次都没能进赌场的大浴场……」

「我什么都没说吧」

「在你们悠闲泡澡的时候，我可是去调查怪物厩舍了……」

「我什么都没说吧」

我们小声嘀咕着，已经解除了八成装备的绮兹梅尔疑惑地转过头来：

「你们在干什么？再不快点脱衣服就来不及了哦」

「好、好的，知道了」

我迅速避开依然把我当成弟弟看待的绮兹梅尔的视线，压低声音向身旁的亚丝娜问道：

「那、那个，我们是不是又要穿着泳衣进去……？」

「啊——真是的，别管泳衣了，桐人君你先进去！」

似乎已经等不及的亚丝娜这样命令道，我立刻回答「好、好！」并迅速移动到左侧的墙边。

固定在墙上的架子上摆满了藤编的衣物篮，但对能使用《幻书之术》——也就是道具栏的我来说完全就是多余的。我躲在观叶植物后面打开窗口，开始点击解除装备按钮，依次移除金属防具、布制防具和内衣后，我便赶在绮兹梅尔前面冲进了浴场当中。

在铺着白色石灰岩的地面尽头，有一个用黑色玄武岩堆砌而成的巨大浴池，从金色的出水口涌出的热水如瀑布般倾泻而下。正如绮兹梅尔推测的那样，浴场里并没有其他人。我利用这个机会，飞快地跑过地面，一头扎进了浴池中央。水花顿时四溅而出，不知道几十升的热水从浴池边缘溢出，蒸腾而起的水汽把浴场染成了一片白色。

这样一来，在一段时间内我们都只能看到彼此模糊的身影。我退到浴池的角落，将脖子以下完全浸到热水当中。温热的水逐渐舒缓了我长途跋涉后冰冷的身体。

「突然跳进热水里对身体不好哦」

绮兹梅尔夹杂着苦笑的告诫声和水流的声音重叠在一起。在这个世界里，应该不会发生热休克——我是这么认为的，但既然有《麻痹》这种负面状态，那或许也存在《心脏麻痹》。不过，仅仅因为跳进热水或冷水之中就立刻死亡，那对于一场赌上真实生命的死亡游戏来说，未免也太过苛刻了。

我试图回忆封测时有没有人因跳进浴池而死，但压倒性的舒适感让我无法保持思考。我将背部和后脑勺靠在光滑的玄武岩上，手脚也尽情舒展，嘴里不由自主地发出了「呜哇～～」的声音。

然而，这种放松状态并没有持续太久。因为两声水响过后，我隐约看到亚丝娜和绮兹梅尔正将身体浸入到浴池当中。而且，尽管被浓密的蒸汽遮挡，或许是视力增强的缘故，我清楚地看到不仅是绮兹梅尔，就连亚丝娜也没有穿泳衣。

我迅速移开视线，嘛，穿着泳衣的话，这种泡澡的快感也会减少三成吧……我这么想道。浴池的宽度大概有八米左右，如果她们俩能走到对面去，那我应该就什么都看不到了吧。

然而，水声不知为何却越来越近。我还没来得及警告，亚丝娜就已经拨开了一团格外浓密的蒸汽，出现在了我的面前。她在一瞬间意识到我的存在后，马上就将身体浸到脖子处：

「等……你为什么在这里啊！」

「是、是你自己过来的吧！」

「那里可是整个浴场里视野最好的地方！」

她说得没错，我占据的位置是长方形浴池的右下方角落。在我的背后，朝南的大窗户和朝西的大窗户呈直角相接，从这里可以一览无余地看到广阔的尤菲尔湖、湖畔的森林、还有在远处险峻的岩山后方耸立的迷宫塔——当然，仅限于白天。

「天还黑着呢，什么都看不见吧……」

我一边移开视线一边反驳，亚丝娜却转过身面向南方「才不是那样呢！」。我也跟着看过去，但窗外依然一片漆黑，而且玻璃的绝大部分都蒙着白雾，根本看不到什么景色。

尽管如此，亚丝娜还是固执地用右手擦拭窗户，擦出一小块透明的区域，然后往外窥探着。我也学着她的样子试了试，但即使以我的视力，也只能勉强看到湖面上反射的月光。

正当我们俩对着窗户东张西望的时候，亚丝娜身后的绮兹梅尔再次用劝诫的语气说道：

「亚丝娜、桐人。你们还年轻，我能理解，但如果你们打算继续当冒险者的话，最好还是习惯一起泡澡哦。毕竟不是每次都能住在尤菲尔城、加雷城或妮露妮尔大人的宅邸这样的地方……」

「啊，你看，那边！」

亚丝娜突然叫了起来，用食指指着窗户。

我顺着她指的方向看去。然后不禁也「啊」了一声。在尤菲尔城的西南方向，湖畔森林的一角，孤零零地亮着微弱的光芒。那不规则晃动的橙黄色光芒，大概是篝火吧。

「……那绝对是拉维克先生吧」

听到亚丝娜的低语声，我默默点头。那个位置离他下船的地方很近。他大概是打算在野外露营，等待着今晚的到来吧。

「让尤菲里斯子爵一个人过去、吗……而且还不能说出拉维克先生的名字……」

我复述着拉维克的请求，亚丝娜从窗户上收回手来，小声嘀咕：

「唔～嗯……——就算我们去请求子爵大人，也不太可能不说明理由就让他跟我们走吧……」

「确实不可能吧」

绮兹梅尔点头附和，

「森林精灵的袭击才过去不到两周。虽然他应该不会怀疑在那场战斗中立下大功的你们，但偶然遇到敌人的可能性还是存在的。尤菲里斯阁下虽说是我无法望其项背的剑术高手，但他也同时是守护这片土地的城主。他不会轻易地做出有可能会招来危险的事吧。而且……」

她越过亚丝娜的肩膀望向漆黑的湖面，继续说道，

「即使阁下同意了，要想在不被任何人发现的情况下把他带到岸边也相当困难。从栈桥划船出去的话，无论如何都会被哨兵看到的」

「是啊……」

亚丝娜低声应道，哗啦一声转过身去，背靠在了浴池边缘。我一边用大部分的处理能力寻找解决这个难题的方法，一边漫不经心地看向她，结果却被她瞪了一眼：

「喂，干嘛这么明目张胆地……」

「欸……啊，不，没看没看。因为有水汽和反光，我只能看到肩膀以上」

「这不就是在看吗！」

亚丝娜把手伸出水面，用弹脑瓜崩的要领迅速地弹了一下中指。或许是得益于她锻炼出的敏捷值，又或者是学了水枪技能，从她手指间射出的水弹直接命中了我的眉心。

我夸张地叫了一声，脑海中突然浮现出了某个情景，于是我又看向了旁边。

我急忙把视线从正准备无声发射第二发水弹的亚丝娜身上离开，快速问道：

「呐，你还记得吗？尤菲里斯阁下在第四层楼层BOSS战时，曾经在水面上奔跑过吧？」

「…………记得，不过那又怎么了？」

「我记得阁下的鞋子里编入了水灵（Undine）……中一种叫薇……薇……」

就在我笨拙地咬着嘴唇说不出话的时候，绮兹梅尔向我伸出了援手：

「是薇丽（Villi）吗？」

「对！是将薇丽的头发编进到鞋子里，靠那种魔力才能在水面上行走的吧」

「我是这么听说的……」

亚丝娜回答的同时，绮兹梅尔也肯定道「没错」。

「那如果让阁下穿上那双鞋，我们用绮兹梅尔给的《薇丽之水滴》，不就能在不被哨兵发现的情况下走到岸边了吗？」

只有这个办法了吧！我如此认为并说出了这个想法，但骑士却用犹豫的语气回应道：

「从可行性的角度来说还是有可能的……但我不是说过《水滴》是非常珍贵的物品吗？」

「……是、是说过……」

「剩下的应该不多了吧？我还是希望你们能把它留到生死攸关的时刻」

被她这么一说，我也只能回答「您说得对」了。确实，《薇丽之水滴》的小瓶里只剩下六七滴左右了。如果在我们三人的鞋上各滴一滴的话，瓶子就会空了。

「嗯～这样的话，该怎么去岸边呢……」

我再次陷入了沉思，我感到亚丝娜瞥了我一眼——的气息。

「既然从一开始就是个很难的请求，那让子爵大人自己一个人去拉维克先生那里不行吗？」

「也不是不行……」

我把鼻子之下都浸入到水中，抬头看着浴场的天花板。这种和地板相同材质的石灰岩瓷砖，在现实世界中恐怕很快就会从接缝处开始发霉吧，但这里虽然有些岁月的痕迹，却依然保持着乳白色的光泽。

在那天花板上方数米、主馆的五层就是尤菲里斯子爵的办公室和卧室。身为近卫骑士的绮兹梅尔当然可以自由出入五层，而我和亚丝娜的左手上也都戴着子爵给的琉苏拉印章戒指，所以见到他应该也不难。

然而，想象一下这样的场景：说声「打扰咯」后走进办公室，再对子爵大人说「不好意思，湖对岸有个叫拉维克的越狱犯在等着您，能请您一个人穿过湖面去见他吗」，我完全无法想象他会回答「好啊」，而且——

「……亚丝娜小姐」

「……什么事？」

「你难道不想知道吗？原骑士团长拉维克和尤菲里斯子爵之间到底有什么因缘」

我感到她似乎被我的话噎住了。过了一会，从亚丝娜的方向传来了夹杂着气泡声的回答：

「当然想知道啊。可是，我们不坐船就不能到岸边去，所以只能让子爵大人一个人去了，不是吗」

「……说不定也不是没有办法」

绮兹梅尔低声说道。我不禁看向了骑士，同时也不可避免地看到了亚丝娜的身影，但水弹并没有飞过来。因为亚丝娜自己也正看着右边的绮兹梅尔。

「欸，那该怎么渡过湖呢？」

亚丝娜从水中探出身子，绮兹梅尔却反问了一个出乎意料的问题：

「……你们知道一种叫凯尔派（Kelpie）的妖精、或者魔兽吗？」

「凯尔派!? 呃……名字倒是听说过……」

在亚丝娜回答之后，我慢了一拍也想起了叫「凯尔派」的动物，不，应该说是怪物。我记得它是一种栖息在河里的肉食性马，根据作品的不同，有的身上长有鳞片，有的没有；有的下半身是鱼的样子，有的则保持着马的形态。也就是说，它和第四层的楼层BOSS Hippocampus很相似，但两者之间具体有什么区别我就不知道了。〔译：凯尔派是苏格兰传说中的淡水精灵，总体来说还是善良的。而Hippocampus（海马）则是希腊神话中的海中怪兽，在现实中海里生活的真海马、以及大脑中的海马体都是以此命名〕

但我至今应该还没有在艾恩葛朗特当中遇见过凯尔派，也许之后有可能会碰到，也有可能只是我没经过它的栖息地而已。不过，既然绮兹梅尔知道这个名字，那说不定——

「绮兹梅尔，你见过凯尔派吗？」

亚丝娜问出了我也想知道的问题，所以我静静地等待着答案。

绮兹梅尔在水面上划动了一会指尖，然后突然点了点头：

「嗯，见过……应该。而且就是在这尤菲尔城里……」

「欸，什么时候？」

「是我和蒂涅尔从士官学校毕业的那一年……已经是快三年前的事了。在毕业后即将服役的年轻人们，通常会在毕业之前的春假里进行一周左右的旅行。嘛，算是从幼年学校开始、十二年间的学习和训练的奖励吧」〔译：绮兹梅尔入学幼年学校时才六七岁，也就是说绮兹梅尔现在才21岁左右〕

现实世界的学生好像也会去毕业旅行，不过我只是在脑中想了一下，当然没有说出口来。亚丝娜肯定也想到了类似的事情，但也默默听着没有说话。

「年轻人在那个时候才被允许第一次使用灵树。不过大部分人还是会选择去第九层的某个地方，但蒂涅尔说想去第四层。那孩子从小就喜欢水，每次看到城市里的湖和运河上的游览船，都会吵着说「我要坐、我要坐」……啊啊，我之前是不是也说过这些话」

绮兹梅尔歪着头，我和亚丝娜默默地点了点头。绮兹梅尔微笑着，目光游离在空中，

「她就是那样的孩子，所以自从听到、也许是读到第四层有一座被湖环绕的城堡后，就一直想去看看。不过，虽然在第九层的王国内几乎没有什么危险，但在其他层可能会被怪物袭击。所以在使用灵树转移的时候，选择相同目的地的人会一起移动，还会有几名骑士护卫。其实我本来对第六层的加雷城很感兴趣，但蒂涅尔一直说想去第四层，最终还是没拗过她……」

绮兹梅尔似乎沉浸在了回忆当中，话语停顿了下来。我和亚丝娜都没有催吐她继续说，只是静静地等待着。

绮兹梅尔的双胞胎妹妹蒂涅尔，在我们开始精灵战争 战役任务的时候就已经去世了。所以我当然没有和她聊过天，也完全不清楚她的长相，但不知为何，我的脑海中却浮现出了蒂涅尔在绮兹梅尔面前撒娇的模糊身影。她的笑容，莫名地让我觉得有点像亚丝娜。

「…………我和蒂涅尔，还有其他毕业生以及护卫骑士队，通过灵树顺利地传送到了第四层，平安无事地抵达了尤菲尔城」

绮兹梅尔又开始讲了起来，我和亚丝娜便看向她，认真地听着，

「那时正值春天，湖畔开满了鲜花，景色非常美丽。蒂涅尔仿佛要把那副景色永远记住一样，一直站在那里看着……之后，我们乘坐迎接的凤尾舟到了城堡，四处参观了一番，然后洗了澡、吃了饭，就住在了士兵用的双人间里。我还是第一次睡上下铺，床铺也有些硬，但可能是太累了，我很快就睡着了……在天快亮的时候，蒂涅尔把我叫醒了。我虽然还想睡，但妹妹一直说想去湖边看看，我只好不情愿地起床，只在睡衣外面披了件斗篷就出了城堡。当时的晨雾浓得伸手不见五指。因为走大栈桥太危险了，我们就沿着城墙走，结果就走到了城堡后面的一个小沙滩上」

绮兹梅尔在这里稍微停顿了一下，然后轻声继续说道，

「那时，明明没有风，晨雾却突然向两边散开了。露出来的湖面就像是镜子一样……而在那里，站着一匹天蓝色的马。鬃毛和尾巴是透明的鳍，皮肤上隐约浮现出鳞片，马蹄的位置是长着蹼的钩爪。我们在训练中护卫各种怪物战斗过，也见过很多长得像马、牛、鹿的魔兽，但像那样的生物，不论是在那之前还是在那之后都没有见过。我和蒂涅尔都惊讶地说不出话来，只是一动不动地站在那里。那匹天蓝色的马盯着我们看了一会，后来就像是对我们失去了兴趣一样，转过身朝湖深处走去。它每走一步，水面上就会泛起圆圆的波纹……最后，它悄无声息地滑入到了湖中。我们后来也在白天去确认过，但水下并没有隐藏的岩石或树木之类的东西。也就是说，那匹蓝色的马是在水面上行走的」

「那就是……凯尔派吗？」

亚丝娜小声问道，绮兹梅尔微微耸了耸肩：

「我虽然是那么认为的，但也不能确定。在城堡里住了几十年的士兵和杂役们也都说没见过那样的怪物……我们第二天早上，还有回城的那天早上都去了那个沙滩，但那匹天蓝色的马却再也没有出现过。不过蒂涅尔回去之后在图书馆查阅了各种文献，发现尤菲尔湖有个关于凯尔派的传说。我们还约定以后两个人再来第四层寻找凯尔派，但最终也没能实现……」

「…………」

亚丝娜抬起右手，握住了还停留在水面上的绮兹梅尔的左手。虽说我也想加入进去，但我实在是没有胆量将手越过亚丝娜的身体。

于是，我在水中稍稍抬起腰，说道：

「呐，我们现在去那个沙滩看看怎么样。正好天快亮了，说不定凯尔派正在湖面上走呢」

虽然可能性肯定很低吧，但要是能远远地看到那匹蓝色的马，那就能判断它到底是不是凯尔派了。毕竟我和亚丝娜能看到颜色光标。如果光标上写着凯尔派——我虽然不清楚拼写，但亚丝娜应该知道——的话，那就绝对没错了。这次我觉得肯定是个好方法，但绮兹梅尔的回答却很冷淡：

「欸……为什么……」

「你忘了吗，天马上就要亮了哦」

我看向南边的窗户，左侧——也就是东方天空已经染上了从群青色到堇色的渐变，很快就会从下方出现茜色吧。距离阳光照到尤菲尔城，大概还有二十……不，十五分钟吧。

「糟了，我忘了！」

亚丝娜叫了一声，猛地从水中站起来，又立刻扑通一声沉了下去，

「桐人君，你先上去穿好衣服！」

要是我先上去的话，岂不是得用我的屁股对着两位女士，这实在是有伤风化……但我也不能让她们先出去。我将脖子以下完全沉入到水中，以最快的速度翻过浴池边缘，然后一路狂奔。虽然在我的脑海中闪过了有可能会在湿漉漉的地面上狠摔一跤的场景，但石灰岩瓷砖即使有水也没有失去摩擦力，我最终还是跑到了更衣室里。〔译：直接在浴池里打开窗口穿上衣服不就得了……〕

虽说身上的水什么都不做也马上就会干，但既然这里准备了浴巾，所以我还是用浴巾擦了擦身上的水珠。这时，从浴场那边传来了两位女士啪嗒啪嗒的脚步声。我急忙躲到盆栽后面，隐藏起自己的气息的同时，隐蔽(Hiding)技能也擅自发动了。

要是在这时回头去看，那就纯粹是偷窥了，但我当然不会做那种事。我打开窗口，装备上内衣、衬衫和裤子。并习惯性地打开道具栏，确认其他装备是否都齐全。

然后，当我在按获取时间排列的清单上方，看到了《日暮之剑（Sword of Eventide）+3》的瞬间，我的手一下子停住了。这把剑是尤菲里斯子爵作为任务报酬而赐予我的尤菲尔城传世名剑，从第五层初期到第七层的楼层BOSS战，它都一直作为我的主武器大显身手。性能放到现在依然是一流水平，强化次数也还有剩余，但由于魔剑哀伤夜想曲的暴力性能，它被降为了备用武器。

比起就这么把它扔在道具栏里，倒不如更有效地利用它……我一边想着，一边转过身从盆栽背后走了出来，就在这时。

「呀啊！」

一声惨叫伴随着划破空气的声音。我刚从窗口上抬起头来，有个东西就以极快的速度飞进了我的嘴里。

「嗯咕!? 」

我一边发出惨叫，一边条件反射地咬紧牙关，紧接着，在一种独特的口感过后，酸甜的果汁就溢了出来。这东西吃起来像木瓜，味道又有点像是猕猴桃或者荔枝之类的东西，我也不能吐出来，只能拼命地咀嚼着，在这时，雷声般的怒吼在我身前落下：

「你干嘛躲在这种地方啊！要是在更衣室里找不到你的话，我还以为你回房间里了呢！」

我定睛一看，亚丝娜正用白色浴巾勉强遮住身体前面，右手正准备拿下一个水果。我以最快的速度咽下嘴里的水果，试图解释道：

「不、不是，我不是故意躲起来的，只是为了避免看到你们从浴场里出来的样子……」



「那你在那边背过身去不就好了！」

「嘛、嘛……确实是这样」

被轻易反驳之后，我迅速地转过身去。背后传来了亚丝娜「哼」的一声，绮兹梅尔则叹了口气。

我们回到东侧四楼的客房时，已经临近早上五点五十五分的时间限制了。

当然，并不是说阳光一到上午六点就会丝毫不差地照进楼层当中，这只是我在艾恩葛朗特里生活了两个月后，直觉上感觉天差不多会在这时候亮起来罢了，实际上阳光照到地面的时间也会因楼层地形而有所不同。从这个意义上来说，由于第四层东侧外围有着连绵的岩山，日出大概会稍晚一些，但目前我还无法亲眼确认。

跟着我和亚丝娜走进房间的绮兹梅尔，仔细关好厚重的房门后转过身来，长舒了一口气。虽然客厅的百叶窗和窗帘都关着，但由于亮着灯，因此并不是完全的黑暗。在摇曳的灯光下，绮兹梅尔直视着我，严肃地说道：

「那么，从现在到日落前的十二个小时，桐人你绝对不能从右边的房间里出来。明白吗？」

被这么一说，我不禁觉得「好长啊—！」，但这就是夜之住民力量的代价。在变回人类之前——甚至不确定能否变回——我都只能乖乖接受。

「我向圣大树发誓，在天黑之前绝不离开房间」

我这么回答之后，绮兹梅尔用一本正经的表情点头「唔姆」。然后看向亚丝娜。

「那么，亚丝娜你可以也在同一个房间里吗？啊啊，你不需要一直待到日落，但离开房间时要小心检查一下客厅的窗户是否开着……」

「欸……那个，我和绮兹梅尔住一个房间也没事的」

亚丝娜插话道，绮兹梅尔立刻摇了摇头：

「虽然可能性很低，但假如白天有人打破百叶窗或墙壁、让阳光照进房间的话，桐人很可能会因为灼烧的痛苦而无法动弹。在那时就必须有人立刻把桐人带到阴影处，但如果我们都在另一个房间里休息的话就来不及了吧？……当然，也可以我和桐人一起睡，你怎么想？」

绮兹梅尔将最后的问题抛给了我，不过我在一时之间也无法回答Yes或No。就在我的眼皮以0.3秒的间隔一开一合的时候，亚丝娜拖长了声音回答：

「那～～～～～～～～～～个，那我睡这边吧……」

她手指的方向是右边——也就是我将要待到日落的卧室。再次听到这个决定后，身为一名初二男生的我不免有些慌乱，但我四月就要升初三了，而且这也不是第一次在同一个房间或帐篷里睡觉了。我尽量保持平静，点了点头：

「那，不好意思，到时候就拜托你照顾我了」

我感觉自己的发音有点含糊不清。不过意思应该传达到了。我对绮兹梅尔道了声晚安，走进了右边的卧室。这里虽然没有开灯，但客厅的光线透了过来，因此不需要使用夜视能力。

我溜到并排的两张床中的里面那张，迅速把毯子拉到鼻子附近，闭上了眼睛。

几秒钟后，我听到门轻轻关上的声音。接着是轻微的脚步声，再然后是从右边床上传来的衣物摩擦声。

我都快初三了，在这种情况下怎么可能睡得着啊……我正这么想着，意识却突然模糊起来。不知不觉间，我心中的紧张感消失了，取而代之的是一种从心底里渗出来的安心感。这不仅仅是因为坚固的石墙和厚重的百叶窗保护着我吧。自从在第一层相遇以来，一直和我一起冒险的搭档——虽说前面还挂着「临时」两字——就在身边，光是想到这一点，各种不安就像泡沫一样消失了。

几小时前在第七层迷宫区的安全屋中，靠在我身上睡着的亚丝娜或许也有同样的感觉吧……想到这里，我的意识中断了。

** 第5章

下一瞬间，我便猛地睁开了双眼。

从身体的感觉来看，真的就像是只过了几秒而已。果然不可能这么容易就熟睡啊……我一边想着，一边瞥向视野的右下角，随后我顿时就瞪大了眼睛。在一片漆黑当中，白色的数字清晰地显示着17:52——下午五点五十二分。

我记得上床的时间差不多是早上的同一时间，也就是说，我竟然一口气睡了整整十二个小时。不，该不会是整整一天加十二个小时吧，我慌忙检查日期，幸好还是一月九日。

确实，自从来到艾恩葛朗特之后，我发现自己睡的要比在现实世界中沉不少，但即使如此，像这样一头死猪般的睡眠也是很久都没有过了。

虽然我确实很累，也睡眠不足，但一口气睡十二个小时还是让我有些担心。更重要的是，原本应该睡在旁边床上的亚丝娜为什么没有叫醒我呢。难道她和绮兹梅尔一起去吃饭了吗——我一边胡思乱想着一边想要起身，在这时才突然注意到。

就在我的右侧不到二十厘米的地方、也就是我的床上，有人正躺在那里睡觉。虽然头埋在毛毯里看不到脸，但在这种状况下我也只能想到一个人。

不过我还是轻轻掀开毛毯，用夜视能力确认一下侧脸后再将毛毯盖了回去。毫无疑问，就是我的临时搭档大人。

两张床之间大约有十厘米的间隙，床本身的宽度也有一百二十厘米左右，她居然能睡到这么靠近的位置……不，难道。

我小心翼翼地左右看了看，确认不是自己钻进了亚丝娜的床上，这才松了一口气。回想起来，在沃尔普塔的《琥珀月酒店（Amber Moon INN）》也发生过类似的事情。虽然订了带独立卧室的高级房间，但亚丝娜半夜因为睡不着而跑来叫醒了我，「现在应该能睡着了」，她说完这句话后就在床边蜷缩成一团，真的就那样睡着了。再往前追溯的话，在尤菲尔城度过的圣诞夜，也有过睡不着的亚丝娜来到客厅里和我一起挤在沙发上、盖着同一张毛毯——准确来说是《亚尔基洛的薄布》——依偎着睡觉的记忆。

也许与我相反，亚丝娜在这个世界里很难熟睡吧。这也是理所当然的，毕竟被困在HP归零就会真正死去的极限死亡游戏当中，现实世界中所珍视的一切也都被夺走了。每晚都被不安、恐惧和焦虑所折磨，怎么可能睡好呢。

如果我能成为让她远离这些困扰的助力，那我当然会由衷地感到高兴。不过我肯定不可能直接说「以后每晚都一起睡吧」，就算说了也只会被她说「你是笨蛋吗」吧。我能做的，也就只有在这种情况下尽量让她多睡一会罢了。

得出这个结论后，我慢慢地、慢慢地向左侧移动，小心翼翼地下了床，尽量不吵醒亚丝娜。我光着脚蹑手蹑脚地穿过地板，缓缓地转动门把手，听到「咔锵」一声轻微的金属声后，轻轻拉开门。从没法再小的门缝中钻出去，再次关上门后长舒了一口气。

就在这时，我听到了一声「早上好」，于是抬起头来。

在只亮着一盏灯的客厅中央，绮兹梅尔坐在曲木框架沙发上。她穿着一件泛着光泽的灰色睡袍，看起来也是刚起床不久。

「啊……啊啊，早上好绮兹梅尔」

虽然已经是傍晚了，但我还是这么回应了，绮兹梅尔微微皱起了眉头：

「比约定的下午六点早了五分钟哦。不过太阳已经下山了」

「欸……啊，这样啊。不，我只是不想吵醒亚丝娜……」

说完后我心里一阵慌乱，但即使是绮兹梅尔似乎也没有看穿「我和亚丝娜睡在同一张床上」的情况。她轻轻点头，用右手指了指旁边：

「别站着了，坐下吧？」

「嗯……嗯」

我点点头，绕过同样是曲木的矮桌，在绮兹梅尔右边隔开一点距离坐下。骑士动了动眉毛，似乎想说些什么，不过我想要毫无顾忌地坐在只穿着一件薄睡袍的大姐姐旁边的话，大概还得再等三年吧。〔译：三年后的26年1月是圣母圣咏时期〕

「看来你睡得很好」

绮兹梅尔一边说着，一边拿起桌上的水壶给我倒了一杯冷水。

「嗯，醒来的时候我吓了一跳。绮兹梅尔你睡得好吗」

「当然。在任何情况下都能好好睡觉、好好吃饭可是骑士必备的素质……虽然我想这么说……」

她喝了一口自己的水，然后继续往下说，

「但实际上可没那么容易做到啊。在怪物出没的地方露营时、在重要作战之前……还有，想起妹妹时的夜晚，我其实很难马上入睡哦」

「…………这样啊」

我点点头，同时短暂地思考了一下，对NPC来说，睡眠到底是什么呢。是单纯模仿人类的行为，还是在进行类似数据结构优化的处理呢，又或者……

不，思考这些没有意义。绮兹梅尔虽然是AI化的NPC，但也是在这个世界中生活的一名黑暗精灵骑士。是拥有真实的思考和情感、与我们玩家别无二致的存在。如果不把这种认识牢牢记在心中，恐怕精灵战争 战役任务……不，这个死亡游戏就无法通关。

——嘛，虽说绮兹梅尔她们也有一些玩家没有的能力就是了。比如即使没有时钟也能准确掌握现在的时间之类的。

我在心里补充了这点后，拿起杯子将凉水一饮而尽。

冰凉的柑橘味水冲走了我长时间睡眠的倦怠感。虽然感觉从傍晚开始攻略有点奇怪，但被困在SAO里之前，在放学后直接回家、做完自己负责的家务和当天的作业、再吃完晚饭后才是我每天的黄金时间。

而且就在此时此刻，尤菲尔湖西岸的森林当中，原骑士团团长拉维克应该还在独自寂寞地露营。我想尽快——不如说是就在今晚——想办法让他和尤菲里斯子爵见面。

首先得先和子爵会面——不，在那之前，得先找到一种不被任何人发现就能渡过尤菲尔湖的办法。子爵可以用魔法靴，可我们三人该怎么办呢……

「……啊」

我低声「啊」了一下，绮兹梅尔立刻转头看向我。在她问怎么了之前，我就转头看向左边，对绮兹梅尔问道：

「呐，绮兹梅尔，昨天你为什么在浴场里说凯尔派的事？」

「嗯……？没什么特别的，不是你说想知道怎么渡过湖吗？」

「所以那和凯尔派有什么……」

就在我准备继续追问时。

从沙发的左前方传来了一声沙哑的声音：

「我知道了哦」

我抬头一看，原本应该关着的卧室门半开着，亚丝娜摇摇晃晃地从里面走了出来。她纤细的身体裹在一条蓝色连衣裙样式的睡衣里，平时扎成半束发的头发散乱地垂下来，如果以这幅模样出现在昏暗的迷宫里的话，恐怕会被误认为是鬼魂（Wraith）或亡灵（Wight）吧。

亚丝娜最讨厌那种灵体系怪物了——这个念头让我心里冒出了一点恶作剧的想法。要不要一边滚到地上，一边大喊一声「有鬼啊～～～！」呢，我思考了大约0.001秒后，就迅速地否决了这个念头。尤菲尔城可不是圈内，如果亚丝娜发现是我在恶作剧的话，大概会把我的HP减少九成左右吧。

当然，绮兹梅尔完全没有恶作剧的意思，她示意亚丝娜坐到沙发中间。我把屁股往右挪了二十厘米，亚丝娜摇摇晃晃地绕过桌子，一屁股坐了下来。她朝我瞥了一眼，脸上浮现出一种微妙的表情，我一度以为她发现了我刚才的恶作剧念头，但很快就意识到并不是这样。

亚丝娜在卧室醒来时，一定发现自己睡在了和昨晚不同的床上吧。先醒来的我不可能不知道这件事，但亚丝娜也没必要自己主动提起，正因如此，她才露出了这种难以描述的表情。我当然也不会在这种时候像个小孩一样拿这件事开玩笑，于是我们通过0.0001秒的眼神交流达成了「双方都保持沉默」的共识，然后一起背靠着沙发。

等亚丝娜喝完绮兹梅尔倒的水，我终于开口问道：

「所以，你说「知道了」是什么意思？」

「……呃……」

亚丝娜用有些沙哑的声音开了个头，然后依次看了看左边的绮兹梅尔和右边的我，解释道，

「我觉得绮兹梅尔的意思是，我们三人可以骑着凯尔派渡过湖去对岸」

「哈啊!? 」

我惊叫一声，绮兹梅尔平静的声音随即响起：

「嚯，不愧是亚丝娜。正是如此」

「哈啊啊!? 」

我又惊叫一声，然后对两人发问，

「不、不不不，凯尔派可是怪物啊。虽然在战斗中应该可以强行骑上去，但谁知道它会跑到哪里去啊、搞不好还会潜进湖里……」

「才不会做那么乱来的事哦」

亚丝娜喝了冷水再说了这么一大段话后，似乎终于清醒了，她用一贯的无奈表情瞥了我一眼，然后不知为何得意地说道，

「是要驯服凯尔派。对吧，绮兹梅尔？」

「就是这么一回事」

「哈啊啊啊!? 」

我再一次的发出惊叫，但这也不能怪我。驯兽师（Tamer）是从古至今的许多RPG中的经典职业，甚至有不少游戏以它为核心玩法。然而，SAO目前并没有开放驯服技能，如果有的话，大概也是像《体术》或《冥想》那样有特殊条件的额外（extra）技能——情报贩子阿尔戈也这么说过。

我正苦恼着该怎么向她们解释这一点，但突然想起了一件事。

我们刚刚才在第七层遇到过拥有驯服能力的NPC。那就是共同统治沃尔普塔大赌场的科尔罗伊家的当家巴丹、以及纳克托伊家的当家妮露妮尔。

巴丹在第七层是我们的死对头，他显然不会帮助我们。也就是说——

「……呃，难道说、要请妮露大人来这里吗……？」

「不—是—！」

亚丝娜抬起右手，用食指戳了戳我的左肩，

「「为了驯服一只不知道能不能找到的怪物，特地把妮露大人叫到第四层来」，绮兹梅尔怎么可能这么想啊」

「也、也是呢。但是，那要怎么……」

「真是的，桐人君一遇到自己的事情就变得特别迟钝呢」

亚丝娜故意叹了口气，然后转了转戳在我肩膀上的指尖，

「如果找到凯尔派的话，就由你来驯服它！」

「……哈啊啊啊啊!? 」

我第四次发出的惊叫声，在桌子上的水壶里激起了小小的波纹。

由于太过震惊，再加上我的饥饿感已经到达了极限，于是我暂且把各种事情都搁置一边，向她们两人提议先去食堂吃饭。

亚丝娜和绮兹梅尔也几乎一整天没好好吃饭了，自然是没有异议。我们整理好衣服后，便前往城堡西翼二楼的大食堂。

推开对开的大门，香气和轻柔的谈笑声便迎面而来——但我总觉得和记忆中的有些不同。我正疑惑的时候，旁边的亚丝娜就小声说道：

「啊嘞……没有音乐呢」

确实如她所说。上次来到这里时，宽敞的食堂深处设有舞台，四五人的弦乐队演奏着悠扬的音乐。虽然我以为是时间还早的缘故，但仔细一看，连舞台本身都已经不见了。

取而代之的是之前没有的东西。厨房附近的墙壁旁设置着一个自助餐台。上面的各种菜肴摆得像一座小山一样高。餐具和餐盘也一应俱全，显然是自助餐的形式。而上次则是女仆们依次将菜肴端到桌上的套餐形式。

难道仅仅两周的时间，大食堂就进行了成本削减吗。即使如此，我对自助餐形式也没有什么不满，甚至可以说是非常欢迎。

——毕竟是自助餐啊。

我在心里默默嘀咕着，一位路过的女仆在这时注意到了我们，微笑着说道：

「哎呀，是近卫骑士大人和人族的剑士们。好久不见」

「你、你还记得我们吗？」

亚丝娜惊讶地问道，双手各摞着好几个空盘子的女仆小姐灵巧地耸了耸肩：

「当然记得了哦，你们可是从森林精灵手下拯救了城堡的英雄啊。哎呀，不好意思，耽误你们时间了。士兵们再过半小时就会挤满这里，你们最好早点用餐哦。今晚的推荐菜是炸河蟹和科尔（kool）汤。祝你们用餐愉快！」

她一口气说完之后，便轻快地走向厨房。我和亚丝娜对视一眼，默契地点了点头后就直奔自助餐台。

我用最大号的盘子装满了推荐的炸河蟹、烤鸡、烤鹿肉和土豆泥，然后将装满美食的盘子放到床边的桌子上。接着又去拿了所有种类的面包和推荐的乳白色浓汤。

我和亚丝娜同时坐下，一言不发地等着绮兹梅尔。看着眼前热气腾腾的美食，我感到一种仿佛拧紧内脏的饥饿感。虽然我在以前也多次思考过，但还是难以相信这是由NerveGear生成的虚拟饥饿感。

等绮兹梅尔拿着酒瓶和三个杯子回来时，我主观上感觉像是等了漫长的十分钟一样，但根据视野右下角现实的时钟来看，实际上才过了两分钟。

「什么啊，你们明明可以先吃的」

她一边说着一边坐下，并在我和亚丝娜面前也放好杯子，然后从已经开瓶的酒瓶里依次往三人的杯子中倒入深红色的液体，

「既然你们等我了，那就干杯庆祝一下吧。嗯……」

她拿起自己的杯子，微微歪了歪头，

「庆祝新年已经有点晚了，一想到桐人付出的代价，又觉得庆祝打倒第七层的守护兽也有点不合适……唔姆……」

见绮兹梅尔陷入沉思，亚丝娜用克制但略带颤抖的声音提议道：

「那么，就不当作庆祝了，而是许愿怎么样？比如希望我们在这一层的任务能顺利完成之类的……」

「原来如此，这样也不错。那么……」

绮兹梅尔举起杯子，用郑重的语气说道，

「愿我们能顺利夺回被抢走的东西、愿桐人能不用远离阳光，干杯」

「干杯！」

「干……干杯」

虽然这确实是我现在最需要注意的事情，但这么说总感觉我像个不死族似的，不，我现在确实已经算是不死族了吧。我在心里对自己吐槽着，同时和她们一起举起杯子。绮兹梅尔在真心关心我的安危是毋庸置疑的，所以我抛开杂念，认真祈祷夺回秘钥的任务能够成功，然后抿了一口深红色的葡萄酒。

在这两个月里，我有机会品尝了各种各样的酒，但最喜欢的还是冰镇啤酒。遗憾的是，在艾恩葛朗特里并没有冰箱、制冰机或冰属性魔法，所以能喝到冰镇生啤的机会并不多。不过，即使是常温啤酒，在常夏的第七层喝起来也别有一番风味。

相比之下，葡萄酒——尤其是红葡萄酒，总给我一种「大人的味道」的感觉，对于我这个「小孩舌头」来说，实在是难以体会它的美味。每次倒酒味道都会产生变化的《莫测葡萄酒》（Fickle Wine）〔译：出自SAOP4〕、或者蒂涅尔喜欢的《月泪草酒》之类的虚构酒，大多都偏甜且清淡，我还能轻松地喝下去。但那些可能还原了真实味道的红葡萄酒，往往带有苦涩味，一入口我就忍不住皱起眉头。

不过，既然是绮兹梅尔特意准备的酒，那就算不好喝我也不能表现出来。我深吸一口气，做好了心理准备后一口将其咽下。

「…………啊嘞」

我不由得发出了这样的声音。这酒既没有苦味、也没有涩味……不，其实两者还是存在的，但在甜味和酸味的掩盖下显得非常温和，完全没有刺激舌头的尖锐感。整体的味道浓郁而顺滑，令人陶醉的香气从鼻腔中溢了出来。

「怎么样，很好喝吧」

在我愣住的时候，绮兹梅尔得意地说道，

「这是第九层的皇家酿酒厂酿造的九十年……不，九十一年陈酿。上次在这里用餐时，我在储藏室里看到这瓶酒后就一直惦记着」

储藏室应该是指厨房旁边的那个巨大的酒窖。既然可以从食堂自由进出，那大概是个让用餐者随意挑选喜欢的酒的系统吧，但既然是这么珍贵的酒，士兵们难道不会先喝光吗——

我的疑问似乎写在了脸上，绮兹梅尔小心翼翼地把酒瓶推到我面前：

「标签已经褪色得几乎看不清了，但你摸摸这里」

我用右手中指轻轻地抚过绮兹梅尔指出来的标签底部，感受到了指尖传来的细微凹凸感。

「那是皇家酿酒厂的压印。仔细看右边，还能隐约看到酿造年份」

「诶……」

我拿起酒瓶，仔细端详已经风化的标签。那些曾经手写的酒名、产地等信息几乎完全褪色，只留下了极为淡的痕迹。亚丝娜也从旁边凑过来看，但很快摇了摇头：

「我完全看不清哦」

我也放弃了辨认品牌等信息，转而盯着绮兹梅尔说的压印右侧。要是能有更亮的光源就好了……就在我这么想的时候，夜视补正似乎生效了，我的视野亮度提高了。在棕褐色的标签上，隐约浮现出四个阿拉伯数字。

「呃……2、4、0……7，对吧」

「嚯，不愧是夜之……不好」

绮兹梅尔突然闭上嘴，迅速左右张望了一下。附近的桌子都空着，应该没人听到我们的对话，但还是尽量隐瞒我夜之民的身份比较好。

绮兹梅尔无声地耸了耸肩，我也回以同样的动作，然后把酒瓶放回到桌子上。

「绮兹梅尔你也很厉害啊，居然能注意到这么模糊的数字呢。也就是说，这瓶酒的酿造年份是二四……」

这次轮到我突然闭嘴了。2407年～～!? 我差点尖叫出声，但还是勉强忍住了，我转头看向亚丝娜，发现她也瞪大了眼睛。

刚才绮兹梅尔说这瓶酒是九十一年陈酿，也就是说，今年是黑暗精灵历法的2498年。绮兹梅尔似乎把我们的沉默理解为对酒龄的惊讶，她露出恶作剧般的笑容，低声说道：

「大概是本应献给子爵阁下的酒，因为某种差错混进了隔壁的储藏室，然后就一直被遗忘在了那里吧。毕竟太老的葡萄酒通常又酸又涩，爱喝酒的士兵也不会碰它吧」

比起刚认识时，绮兹梅尔的性格似乎变得柔和多了……我沉浸在了无法说出口的感慨当中。绮兹梅尔随后放下酒杯，拿起刀叉：

「好了，趁热吃吧」

「啊……嗯、嗯」

我正想着黑暗精灵历法的漫长历史，被绮兹梅尔这么一说，就突然想起了被遗忘的饥饿感，胃里开始翻腾起来。我迅速抓起刀叉，和两人一起说了声「我开动了」。

亚丝娜优雅地从沙拉开始吃，而我则根本没拿沙拉。我一口咬下裹着薄薄面衣、炸得金黄的小河蟹。

我本以为外壳会很硬，但圆滚滚的蟹壳一咬就碎了，汁水四溢的蟹肉立刻涌入口中。香料的味道很浓郁，完全没有腥味。我狼吞虎咽地吃完之后，又往嘴里塞入一整块五分熟的烤鹿肉。虽然是几乎没有脂肪的瘦肉，但肉质却鲜嫩多汁，浓郁的肉汁酱更是锦上添花。烤鸡只用盐来调味，但正因如此，酥脆的鸡皮才能被完美地展现出来。

我们在第七层吃了很多异国风味的料理，比如打抛饭（Kaphrao rice）、海南鸡饭、叶包饭（Dolma）、慕莎卡（Mousska）、面包炖饭（Pot stew），当然，它们都非常地好吃，但像现在这种《字面意思上的大餐》所带来的满足感是无可替代的。幸好成为夜之民之后，我的味觉、食欲和咀嚼能力都没有受到影响。〔译：打抛饭 泰国料理，将用九层塔（罗勒）和鸡肉（或猪肉牛肉）炒制而成的肉沫放到米饭上；叶包饭 中东料理，可以理解为用葡萄叶包的肉粽子；慕莎卡 希腊料理 用茄子来代替面皮的肉酱千层面；面包炖饭 SAOP7中桐亚鼠三人吃的料理〕

在尽情享用完肉类和螃蟹之后，我开始品尝汤。女仆小姐说这乳白色的汤是《科尔汤》，但我不确定「科尔」是什么食材。我舀了一口尝了尝，温和的甜味和独特的香气在口中扩散开来。肯定不是土豆、洋葱或玉米，但我喝了几口后也还是没猜出来是什么。

这大概和亚丝娜在浴场里扔向我的神秘水果一样，都是现实世界中不存在的奇幻蔬菜吧……我正这么想的时候。

「啊，这样啊……」

喝了同样汤的亚丝娜恍然大悟般地嘀咕了一声，我向右歪了歪身子问道：

「科尔是什么东西？」

「我猜，大概是花椰菜吧」

「啊、啊—……原来如此……」

听她这么一说，这确实是花椰菜的味道。花椰菜平常只作为炸物或肉类的配菜而出现在盘子的角落，我对那种松散的口感也不太喜欢，但做成浓汤之后，花椰菜的香气和滋味都得到了充分的展现。

「不过，为什么花椰菜会被叫成科尔呢？」

我歪着头问道，亚丝娜小声地给我解释：

「我记得花椰菜（cauliflower）的词源是kool flower，kool在荷兰语里是卷心菜的意思……应该是这样。大概是「卷心菜类的花」的意思吧」

「啊，原来凉拌卷心菜（coleslaw）的「col」是这个意思啊……嗯？这么说，这不是花椰菜汤，而是卷心菜汤吧？」〔译：coleslaw是英语，源自荷兰语koolsla〕

「味道完全不一样好吧」

真的有那么不一样吗……？虽然我这么想，但我可不敢在味觉方面和亚丝娜争辩。再补充一句，游戏以外的知识和人际交往能力我也完全不是她的对手，但她从不会让我感到不适，这就是亚丝娜的人格魅力吧。

总而言之，不管这个浓汤是花椰菜还是别的什么，美味程度也都不会改变。我很快就把浓汤和刚出炉的面包一起吃光了，然后喝干了杯子里剩下一半的葡萄酒，暂时沉浸于余韵之后，我随即再次向自助餐台发起进攻。

我最后添了两次菜，亚丝娜也添了一次，绮兹梅尔虽然没有添菜，但一个人喝掉了大半瓶九十一年陈酿的葡萄酒。不久后，食堂开始拥挤起来，我们向女仆小姐道谢后就迅速离开了。

我们出去的时候，走廊里也挤满了饥肠辘辘的士兵，但一上到四楼，就一个人——不，一个精灵都没有了。

走在安静的走廊里，我认真地想着：如果每天都能尽情享用那样的美食，那把尤菲尔城当作据点也不错啊，有没有什么办法能便利地往返于这里和最前线呢……身旁的搭档也一言不语，我以为她沉默的原因和我一样，但似乎并非如此。

「呐，绮兹梅尔」

亚丝娜转过身，用略带犹豫的语气向绮兹梅尔问道，

「上个月我们来的时候，是女仆小姐把菜端上来的吧？为什么现在改成自助形式了呢。我倒是一点也不讨厌这种方式，每道菜也都非常好吃，我只是有点在意这件事……」

确实，我也想知道这件事。即使是因为系统调整，如果是SAO的话，也肯定会在游戏内给出合理的解释吧。

然而，绮兹梅尔的回答却出乎我的意料：

「啊啊……因为那天是约鲁祭啊。城堡里的所有人都能享用特别的料理。我们当时正好在场，算是很幸运了」

「哇，原来是这样！」

亚丝娜的声音里带着一丝兴奋。很显然她对约鲁祭有所了解。当然，我还是第一次听说，所以毫不犹豫地问道：

「约鲁是什么？」

「就是圣诞节哦」

亚丝娜低声解释道，还主动提供了一些信息，

「在现实世界的北欧，Christmas被称为Yule（尤尔）。它原本是冬至的节日，后来与基督教的圣诞节融合了。约鲁大概是古语的发音」

「哦……原来如此。这么说，那天下的雪和在食堂演奏的弦乐队，可能都是圣诞节的限定活动吧……」

等我们的对话告一段落，绮兹梅尔再次开口：

「那天，子爵阁下的孩子们也在大食堂吧？贵族的孩子本来是不可能和仆人或士兵一起用餐的，但约鲁祭的夜晚是特别的。当然，也有人不喜欢这个传统……」

「是说那天在大食堂的神官们吗？」

亚丝娜发问后，绮兹梅尔苦笑着低声回答：

「正是如此，但在琉苏拉的土地上谈论他们时最好还是小点声。毕竟隔墙有耳啊」

「明白了」

亚丝娜耸了耸肩，突然想到什么似的补充道，

「这么说，赛特兰那天也在大食堂的某个地方吗」

「不……」

绮兹梅尔恢复了严肃的表情，轻轻摇了摇头，

「我比你们早两天到达尤菲尔城，但在那期间没有见过赛特兰大人。因为城堡很大，所以也有可能只是错过了……」

「这样啊……」

亚丝娜若有所思地喃喃自语，我问道：

「你很在意赛特兰吗？啊……说是在意，当然不是恋爱的那种在意……」

我补充了一句后，随即意识到有些画蛇添足了，于是不由得缩了缩脖子。亚丝娜只是冷冷地瞥了我一眼，无视了我补充的话：

「我只是在想，如果赛特兰在约鲁祭这个特别的日子离开了城堡，会是什么原因」

「呼姆，确实。传说在约鲁祭的夜晚，魔物们也会成群结队地游荡。因此，就连王城的哨兵也会被解除外勤任务，留在室内与同伴和家人们共度时光。那个年纪的年轻人不回家，一般来说实在是难以想象……」

「魔物……是什么样的？绮兹梅尔你见过吗？」

提问的当然是我，如果魔物游行真的存在的话，那可能就是一年一次的限定活动、也有可能是限定任务。然而，绮兹梅尔露出了极度无奈的表情，左右摇了摇头：

「怎么可能见过呢，毕业前我每年都在家里过，成为骑士后也从不在约鲁祭的夜晚外出。不过有着各种传说哦，比如成群的亡灵啦、魔女的集团啦、还有骑着黑马的冥府猎人之类的。而且，我在之前应该也说过……」

绮兹梅尔说到这突然停住了，我凑过去问道：

「说过什么？」

于是，骑士先来了句「别想着去找哦」，然后才告诉我：

「……据说在约鲁祭的深夜，在艾恩葛朗特的某片森林里会出现一位被黑暗侵蚀的邪恶圣者。他背上的麻袋里装满了在约鲁祭夜晚独自外出的孩子们，也有人说里面残留着曾经被他盗走的圣大树果实碎片。……我事先说好，虽说他已经堕落了，但毕竟还是神的眷属。就算拥有《夜之民》的力量也无法战胜他哦」

「我、我不会去找的啦……诶，神的眷属吗……」〔译：SAOP5就已经暗示圣诞BOSS是偷走小女孩礼物的圣人了，现在终于实锤了。结果桐人最终还是去单刷了……〕

我突然意识到，绮兹梅尔很少谈论与神有关的话题。

两族精灵都深深信仰着黑圣树和白圣树这两颗巨树，我原本以为它们就是神的替代品，但或许还存在更高层次、或者另一种形式的神明。从《眷属》这种说法来看，似乎并不是严格意义上的一神教〔译：只信奉一个神明的宗教，比如基督教〕……正当我的思绪开始跑偏时，亚丝娜的声音把我拉了回来；

「那么，赛特兰为什么不在城堡里呢。而且……对了，赛特兰和其他孩子的母亲……尤菲里斯子爵的夫人，我们也没见过吧？」

「啊……」

我一边想着确实如此，一边抬头看了看走廊的天花板。

如果有孩子的话，那应该也有他们的母亲才对。作为贵族的夫人，她可能只在城堡顶层活动，不与下层的人接触，但即使如此，她的存在感也还是稀薄到了不自然的程度。

「我也很在意这件事……」

绮兹梅尔压低了声音，低声说道，

「其实就连子爵阁下本人我也知之甚少。上个月停留在这里的时候，我才第一次知道他有三个年幼的孩子和一个继承人。关于夫人的事，我更是从未见过她的身影，也没有听说过她的名字。当然，我们也不能随便去打听这些事」

「这样啊……」

亚丝娜点了点头，陷入了沉思。

在传统RPG当中，这种时候只要挨个去和城堡里的NPC说话，总会有一两个人告诉我们关于子爵夫人的事情。但在SAO当中，如果不注意礼仪和常识的话，说错一次话就可能引发无可挽回的局面。就连绮兹梅尔，在第一次见到我们时也说过「别在这里碍事！立刻离开！」

约鲁祭夜晚缺席的赛特兰、精灵们信仰的神明、从未露面的子爵夫人——虽然有很多事情让人在意，但眼下最重要的事情是帮助在寒冬的湖边独自露营的拉维克原骑士团团长。我们还没找到不被哨兵发现就能渡过湖的方法，但在此之前，我们必须先和尤菲里斯子爵谈一谈，让他同意「不问理由、不带护卫，独自前往湖对岸」的无理要求才行。

我一边想着这些事情一边走着，不知不觉间就来到了主馆的大楼梯前。如果沿着走廊一直往前走，就能回到我们借住的东侧客房，但回去了也没什么事做。

「那么……差不多该去子爵大人那里了吧？」

我停下脚步提议道，亚丝娜和绮兹梅尔都紧张地点了点头。

我们顺着铺有红色绒毯的大楼梯登上五楼，进入了一个比下层要气派不少的大厅。正面的墙上挂着一副描绘湖和城堡的巨大油画，左右两侧是厚重的木质拱门。右边的走廊通向尤菲里斯子爵的办公室，左侧——我并没有去过。

也许左侧的走廊通往子爵一家的居住区，夫人可能也住在那里，但即使如此，我们也不能贸然闯入。

绮兹梅尔毫不犹豫地穿过右边的拱门，我们乖乖地跟在后面。沿着昏暗的走廊走了一会后，很快就看到了一扇黑色的双开门。门前站着两名全副武装的卫兵，他们即使在室内也放下了头盔的面甲，因此看不到他们的脸。

虽然散发着有些吓人的气氛，但这两名卫兵在尤菲尔城攻防战中曾与森林精灵士兵奋勇作战、在楼层BOSS战中也是可靠的坦克。绮兹梅尔在他们面前停下，行了个简短的礼，然后问道〔译：回看了一下SAOP3，还真提了一嘴有两名黑暗精灵士兵参加了楼层BOSS攻略战。这种细枝末节的设定都能记住，休马尔格亚之刺的设定是怎么记错的……〕：

「请问子爵阁下在吗？」

两名卫兵无比整齐地行礼，身着的铠甲发出哗啦一声。之后，左边的卫兵用低沉的声音回答：

「在的。阁下吩咐过，如果骑士大人和客人来访，可以直接进去」

「这样啊，谢谢」

看来子爵大人早就知道我们要来。虽然很抱歉让他等了半天，但我们也有不得已的理由。

绮兹梅尔用力敲了敲右侧的半扇门，等了两秒后转动门把手，推开了门。她大步地走了进去，亚丝娜紧随其后，我则是最后进去，并顺手关上了门。

明明子爵的办公室在面积和家具陈列上都与之前来访时别无二致，现在所散发的氛围却截然不同了。我很快就明白了其中的原因——正对着的墙壁上的三扇格子窗，正中间那扇的窗帘被完全拉开了，苍白的月光倾泻而入。我上次造访是在白天，所有的窗帘都紧闭着，反而显得比现在要昏暗许多。

照明依旧只有一盏台灯。在古旧办公桌的边缘、摇曳着的灯火对面，站着这间屋子——不，这座城堡的主人。到昨天为止的我恐怕只能看清轮廓，但如今多亏了夜视能力，我连他五官的细节都能一览无余。

波浪般的漆黑长发、温润中暗藏锋芒的俊美容颜、以及从额头处经过左眼、延伸至嘴角的旧伤。毫无疑问，正是尤菲尔城城主列休连·泽德·尤菲里斯子爵。

绮兹梅尔向前迈了两米，右拳抵胸深深行了个礼。我和亚丝娜也连忙效仿。

当我们三人抬起头时，子爵轻抚厚重的长袍下摆回礼，然后不紧不慢地开口说道：

「诸位平安无事就好，骑士绮兹梅尔、剑士桐人、剑士亚丝娜。不过……桐人的脸色似乎比之前要差了一些呢」

「哎呀、嘛、欸、呃……」

我一边吐出一连串的语气词，一边用右手挠了挠后脑勺。在这么暗的环境下，子爵仅仅瞥了一眼就能看穿我夜之住民的身份，他的洞察力实在是令人叹服。

「是因为一些不得已的情况才变成这样的，不过我当然不会对尤菲尔城的各位造成任何危害……」

我好不容易才挤出解释的话语，子爵随即露出了淡淡的微笑：

「我并非是怀疑此事，我反倒是担心你在逗留的期间会不会不慎暴露在阳光下」

「感谢您的关心，子爵大人。我已经在准备的房间住下了，因为窗户装有百叶窗，我想应该是没问题」

「那就好」

子爵点了点头，神情突然一变，

「但有一件事我必须要问清楚。把你收为眷属的夜之主的家族名是什么？」

这个问题让我瞬间绷紧了神经，如果我如实回答，子爵会不会突然拔出细剑向我袭来呢。因为妮露妮尔的女仆奇欧曾经说过，在大斗技场中战斗的怪物，都是纳克托伊家和科尔罗伊家从属于黑暗精灵版图的摇岩之森中捕获而来的，所以现在黑暗精灵一发现这两家的捕获部队就会发动袭击。

不过，那片森林中心的哈林树宫是黑暗精灵神官们的据点，他们和骑士应该是互相敌对的关系。而且，据说妮露妮尔从出生以来就从未离开过沃尔普塔，很难想象她会和相隔甚远的尤菲里斯子爵之间有个人恩怨。

「……是纳克托伊家」

我鼓起勇气如实回答道。子爵微微歪了歪头，像是在搜索记忆一样，然后露出了一副恍然大悟的表情点了点头：

「啊啊……是那位《屠龙者》法尔哈利的后裔啊。既然如此，那你在本城逗留不会有任何问题」

这语气仿佛在说「如果是其他家族就有问题」一样，但我既没有胆量去探究其中的详细缘由，也没有那个时间。

妮露妮尔的祖父法尔哈利在第七层去世应该是三百多年前的事了，尤菲里斯子爵是曾经和他有过直接交情呢、还是说当时法尔哈利也在第四层屠过龙呢……各种疑问涌上了我的心头，我强行将其压下，再次低下了头：

「非常感谢，您的恩情我铭记于心」

紧接着，绮兹梅尔和亚丝娜轻轻地呼了一口气。她们大概是担心我会说出什么奇怪的话、从而把这次会面搞砸吧。虽然我觉得有点被看扁了，但我也很清楚如果继续说下去很可能会出岔子，所以就把正事交给她们两人吧。

「那么……你们来这里不只是为了问候我吧？」

Lucky，子爵把话题引了过来，我后退半步说道：

「是的。接下来的事情由亚丝娜为您说明」

「等……」

我好像听到亚丝娜发出了不情愿的声音，但她还是毅然地向前迈出一步，站到了绮兹梅尔的旁边，

「今天冒昧前来，是有事想请求尤菲里斯阁下」

亚丝娜流利地说完开头之后，子爵也同样流畅地回应道：

「诸位可是从森林精灵军的奇袭中拯救了我的城堡、家人、众多士兵和仆人的大功臣啊。按理说，就算是女王陛下亲自嘉奖你们也不为过，但由于我的一些原因而没能实现。我一直觉得仅仅在讨伐守护兽时帮了点忙，还远远不足以报答这份恩情，所以只要是我能做到的事，那无论是什么都可以」

「非常感谢阁下的宽大之言」

亚丝娜低头致谢后，终于切入了正题，

「那么恕我冒昧。希望尤菲里斯子爵能在今晚九点、独自一人与我们同行。目的地是尤菲尔湖的西岸，有人正在那里等着阁下」

「…………呼姆」

不知道子爵是不是真的吃了一惊，他的表情几乎没有什么变化，只是低吟了一声，

「独自一人……也就是说，不带随从，是这个意思吧？」

「是……是的」

或许是再次意识到这是在向至今遇到的黑暗精灵中、身份地位仅次于加雷城城主梅朗·加兹·加雷奥恩伯爵的贵族所提出的无理要求，亚丝娜的声音逐渐变小了。

这时，绮兹梅尔开口了：

「我们深知这是个极其无理的请求。但是，委托我们传达这个口信的人对我有非同一般的恩情。我就算拼上性命也会保护子爵阁下的安全。请您务必要和我们同行」

绮兹梅尔低下了头，我和亚丝娜也拼命地挤出声音附和道：

「那个，我也会尽全力保护阁下的！」

「我也会保护您的！」

过了一会，我感觉子爵露出了苦笑：

「你们三人都把头抬起来吧。我虽然已经离开战场很久了，但还不至于被湖边附近出没的魔物打败哦」

「实……实在是非常抱歉！就连天柱之塔的守护兽都被子爵阁下轻松地制服了，我却说出了如此冒昧的话……」

绮兹梅尔慌慌张张地辩解着，尤菲里斯子爵举起右手制止了她：

「我不是在怀疑你们的能力。护卫的事，就拜托你们了」

「那……也就是说，您同意和我们同行了吗？」

「在回答之前，请让我问两个问题」

子爵收起了一直挂在脸上的微笑，

「在湖岸等着我的那个人的名字，不能告诉我吗」

「……是的」

绮兹梅尔痛苦地点了点头。

不能带上随从，也不能透露自己的名字，却要求把子爵带过来，拉维克的这个委托确实十分无理。假如子爵拒绝了的话，是否该为了能与拉维克见面而报上他的名字呢……就在我这么想着的时候。

「那么，这是最后一个问题了」

尤菲里斯子爵先这么说了一句，然后用平静的声音开口道，

「那个人，是琉苏拉的骑士吗？」

虽然是疑问句的形式，但在我看来，子爵几乎已经确信了。绮兹梅尔大概也有同样的感觉，在短暂的沉默过后，她回答道「是的」。

听到这个回答，子爵眨了一下独眼，然后出乎意料地干脆答应了：

「……我明白了。那我就去见见那个人吧」

我暗自松了一口气。但子爵却没有停顿，紧接着说出了他的担忧，

「……不过，就算我说不需要护卫，卫兵们……尤其是门外的泽拉（ゼラ）和戈特拉（ゴートラ），恐怕也不会同意的吧。如果只有我一人的话，倒是有办法神不知鬼不觉地渡过湖去，但你们要是同行的话……呼姆……」

看着陷入沉思的尤菲里斯子爵，我忍不住问道：

「那个，您说的渡过湖的方法，是子爵大人您在与楼层BOSS……不对，是与守护兽战斗时穿的那双能在水面上行走的靴子吧」

「没错。在城堡的后面穿上那双靴子走到对岸的话，城堡里的人应该发现不了吧」

「呃……有没有另外三双同样的靴……」

说到这里，我被亚丝娜和绮兹梅尔狠狠地瞪了一眼，于是立刻纠正了自己的话，

「……应该是没有吧，抱歉」

「很遗憾，确实没有」

子爵微微苦笑着点了点头，然后目光稍稍扫向身后的窗户，又再次看向我们，

「没办法了，你们先登上大栈桥那里的船，再绕到城堡的后面，在那里接上我吧。虽然还是有可能引起卫兵的怀疑，但似乎也没有其他能渡湖的办法了」

「……啊啊，原来如此……」

我和亚丝娜、绮兹梅尔同时点了点头。

只是登上自己的船应该不会被追究吧，我们完全没想到这个办法。虽然绕到城堡北侧说不自然的话也确实有些不自然，但要是说去欣赏夜景或许也能说得通。至少比去寻找可能根本不存在的凯尔派、再尝试也许根本无法成功的使役作战要现实得多。

我正这么想着。

「那个……子爵大人」

亚丝娜有些犹豫地开口问道，

「请问您见过在湖面上行走的马吗？」

尤菲里斯子爵似乎有些惊讶，睁大了右眼微笑起来，

「你居然知道尤菲尔湖的水马……凯尔派的传说呢。我还以为这座城堡里已经没有人知道这件事了呢」

「呃……」

绮兹梅尔代替支支吾吾的亚丝娜解释道：

「……我以前在士官学校的毕业旅行时，曾和妹妹一起到访过尤菲尔城。当时，我于清晨的时候和妹妹一起在城堡周围散步，然后有那么一小会看到了一匹在湖面上行走的蓝色的马……那个是不是就是凯尔派呢……」

「这可真是……简直是三重幸运呢」

看着加深笑容的子爵，绮兹梅尔疑惑地问道：

「您这话的意思是……？」

「那匹马肯定就是凯尔派吧。我也只在年轻时见过一次。凯尔派平时都待在很深的水底里，只有在深夜到清晨的这段很短的时间里才会浮出水面……而且，只有在出现像牛奶一样的浓雾时才会现身」

「……确实，那天的雾浓得伸手不见五指」

「是吧。尤菲尔湖在一年中，也就四五天能有那么浓的雾」

也就是说，三年前住在尤菲尔城的绮兹梅尔和蒂涅尔，是偶然在一年中只有几天的浓雾天里出去散步的。这确实可以说是幸运——不过说实话，这种程度的幸运，恐怕每隔几年就会出现一个偶然满足条件的人吧。恐怕还有其他的条件。而且既然说是三重幸运，那就还有两个条件才对。

没想到事情居然朝着解谜的方向发展，我觉得有些有趣，一时之间竟忘记了紧张，向尤菲里斯子爵问道：

「……不过，仅仅有雾的话也见不到凯尔派吧？是不是还有其他条件呢？」

「嚯，你的直觉很准啊，桐人。没错……你能猜到是什么条件吗？」

「那个、呃……」

我在脑海中回忆着绮兹梅尔讲的那段往事。黎明时分，被蒂涅尔叫醒的绮兹梅尔，只穿着睡衣披上斗篷就离开了城堡，来到了城堡后面的沙滩上……

「……是没有带武器……吗？」

「答得好……虽然我想这么说，但只对了一半」

子爵微笑着，摸了摸装饰在自己长袍上的银色别针，

「正确地来说，是身上不能带有任何金属制品。凯尔派的嗅觉极其灵敏，而且很讨厌金属的味道。哪怕只是一枚应该没有气味的金戒指或白金戒指，它也能嗅出来……骑士绮兹梅尔，你和妹妹看到凯尔派的时候，身上有金属制品吗？」

「…………没有，一点也没有。虽说作为受过骑士教育的人，难免会被指责粗心大意，不过我当时连一把短剑都没有带。我记得睡衣和斗篷上的纽扣也都是用胡桃壳加工而成的」

绮兹梅尔的回答让子爵深深地点了点头：

「住在这座城堡的人，包括卫兵、甚至连仆人们都被要求「在离开城堡时携带最低限度的武器」，这是为了让大家时刻记住此处是为了守护湖泊而建成的堡垒，随时都有可能遭到森林精灵的袭击。当然，由于作为城主的我长期放弃职责，一直隐居在城堡深处，这样的规定也变得形同虚设了……」

说起来确实如此。在两周前，我和亚丝娜到达尤菲尔城时，整个城堡的氛围相当悠闲，绮兹梅尔还曾抱怨「这座城堡的驻军真是松懈到了极点」。

不过现在单看卫兵们的站姿，就觉得他们比之前要更挺拔了。经历了那样大规模的战斗，会有这样的变化也可以说是理所当然的，但尤菲里斯子爵时隔数年、也可能是数十年再次出现在士兵面前，展现出勇猛无畏的战斗姿态，恐怕对他们的影响才更大吧。

总之，尤菲尔城的黑暗精灵们，即使在规矩松懈的时候大概也没有忘记佩剑。所以谁都没能遇到凯尔派。

这样一来，子爵所说的三重幸运中的两个已经弄清楚了。我拼命地思索着剩下的一个幸运是什么。是因为她们是两个人呢、还是因为都是女性、又或者是当时没有说话呢……似乎都不太对。

思考了五秒之后，我便干脆地放弃了，直接向子爵求证：

「那个，子爵您刚才说有三个条件，那剩下的一个是什么……？」

「三个条件……？」

子爵露出疑惑的神情，皱了皱眉头，随后轻轻笑了起来，

「哈哈……是因为我刚才说有三重幸运吗。第三个幸运和看到凯尔派的条件可没有关系哦」

「欸……那到底是什么样的幸运……？」

「当然是没有被凯尔派袭击的幸运了」

子爵若无其事地说出这句话的瞬间，绮兹梅尔微微向后仰了仰身体。子爵随即用温和的语气继续解释道，

「凯尔派的主食虽然是鱼，但它也会上岸袭击野兽。当然，人类和精灵也不例外。传说中，如果它觉得对方没有威胁，就会靠近并引诱对方骑到它的背上，而那些傻乎乎地骑上去的愚者就会被它直接拖进水里」

「……这么说，我和妹妹也有可能被凯尔派袭击吗？」

绮兹梅尔一脸惊愕地问道，子爵再次对她微笑：

「没发生那种事真是幸运啊。我那时候……不，这件事以后有机会再说吧。总而言之……」

子爵把视线从绮兹梅尔身上移到亚丝娜身上，提问道：

「亚丝娜，你这么想了解凯尔派，是因为你在考虑能不能骑着凯尔派渡过湖吧？」

「是……是的，就是这样」

或许是预想到会被这样质问，亚丝娜缩了缩脖子。然而子爵一脸严肃地沉默了一会后，又将视线放到了我身上：

「原来如此，是想把夜之住民所拥有的使役之力用在凯尔派身上啊」

「这、这实在是有点乱来吧。我还从来没有使役过什么东西呢」

我抢先回应道，但子爵的回答却出乎我的意料：

「也不能说得这么绝对哦。夜之住民的使役，和「用食物驯服野兽」有着本质上的区别，那是一种类似魔术的支配之力……我的一位驭狼者朋友曾经这么说过」

「……类似魔术的支配……」

我鹦鹉学舌般地喃喃道，思考着这句话的含义。

妮露妮尔用使役之力捕获的蜘蛛，按照她的命令在同一个地方一动不动地待了半天。如果只是单纯的驯服，不可能让它等这么长的时间，说到底，也很难想象能用食物驯服一只成年的蜘蛛。

而所谓的驭狼者，应该就是指黑暗精灵中稀少的职业《黑暗精灵驯狼者（Dark Elven Wolf Handler）》吧。我曾在封测中见过几次，一人一狼以深厚的羁绊为纽带、配合默契战斗的样子，总是使我看得入迷。既然连子爵的驭狼者朋友都这么说，那夜之住民的使役应该不是单纯的驯服，而是可以归类为魅惑或者支配的特殊能力吧。

「……如果是那样的力量，是不是就不需要什么熟练度和技巧了……即使是在实战当中直接使用，只要满足条件就能成功，是这个意思吗」

「正是如此」

子爵似乎很满意地回答道，继续说了下去，

「补充一点，据说使役的成功率是由自己和目标的能力差距来决定的。简单来说，比自己强大的魔物很难使役、而越弱小的就越容易使役……就是这么一回事。凯尔派虽然是非常稀有的魔物，但并不是很强大。如果在陆地上或者在船上战斗，它应该不是现在的桐人的对手吧」

「也就是说，只要能找到它并把它引诱到陆地上或船上，使役成功的可能性就很高……对吗？」

听了绮兹梅尔的话，子爵又点了点头。

我原本觉得驯服凯尔派的计划太过荒唐，但现在却渐渐有了实现的可能性，但最大的问题依旧还存在着。凯尔派只在一年中出现四五次的浓雾里现身。就算往高了估算，今天恰好是那种日子的概率也不到百分之二。虽然我在之前就已经多次见识过亚丝娜的好运气，但今天要是还能发挥强运的话，就连游戏之神都会发怒吧。

我踮起脚尖，从子爵背后那扇拉开窗帘的窗户向下俯瞰尤菲尔湖。皎洁的月光反射在漆黑的湖面之上。别说是浓雾了，就连一缕薄雾都看不到。

「……看来凯尔派今晚不会出现了呢」

我放下脚跟说道，子爵也看向湖面，随即摇了摇头：

「至少接下来的几个小时都还是这样吧。黎明前有可能会起雾，要等到那个时候吗？」

亚丝娜和绮兹梅尔默默地看着我。拉维克拜托我的是「今晚将尤菲里斯子爵带到湖对岸」，如果对「今晚」这个词扩大解释的话，感觉上是可以拖到黎明前的。但就算拉维克会等我们，太阳可不会等着我们，如果拖得太晚的话，我就会有被朝阳照射到的风险。

「不……」

回答的是绮兹梅尔，

「就按照原计划的九点出发吧。移动方法就按照阁下您提议的、把船绕到城堡后面的方法」

嘛，也只能这样了……就在我轻轻地叹了口气的时候。

亚丝娜悄悄靠近过来，快速地小声说道：

「桐人君，根据子爵大人的说法，只要起雾了话，凯尔派就算不在岸边也会出现的吧？」

「大概吧……我是这么认为的……」

「那这样的话，乘船到起雾的地方不就好了吗？」

「在哪才能找到那种地——」

说到这里，我突然停住了嘴。

如果只是在尤菲尔城等待的话，恐怕不管是今天、明天、还是后天，都不会恰好地出现浓雾。但是，如果我和亚丝娜乘坐凤尾舟笔直地在湖上前进的话，肯定会在某个地点被浓雾笼罩起来。那就是伸手不见五指、有着《副本区域边界》之名的浓雾区域。

** 第6章

一月九日，晚上八点。

我和亚丝娜正久违地乘坐蒂涅尔号，沿着尤菲尔湖直线南下。

我们已经跟守卫在城堡正门的哨兵们说过「稍微去看看夜景」了。虽说驻守在四座尖塔上的瞭望兵们大概也注视着这艘船，但只要我们没有可疑举动、只是径直离开的话，那应该就不会被警戒。

【副本区域/专用领域】的边界、设定在距离半径将近一千米的尤菲尔湖岸边仅一百米左右的线上。区域内部是各个玩家或队伍专用的地图，就算现在有其他队伍乘坐凤尾舟前往尤菲尔城，他们到达的也是与我、亚丝娜和绮兹梅尔身处的尤菲尔城所不同的《平行世界的尤菲尔城》。

虽然在内侧无法看到边界线，但当玩家靠近时就会迅速地涌起浓雾，借此来提示边界线的存在。

问题在于这雾究竟只是单纯的视觉效果，又或者是真正的雾。虽说就算是Sword Art Online，也几乎不可能把构成雾的数以亿计、数十亿计微小液滴的每一滴都当作物体来生成。也就是说，所有的雾其实都是没有实体的视觉效果，或许根本就不分真物或伪物——这就是我琢磨出来的结论。

我一边祈祷着事实确实如此，一边不停地划着船桨，在离城堡大约五百米远的地方暂时停了下来。

「好了……就在这把所有的金属制品都脱掉吧」

我这么一说，坐在凤尾舟中央的亚丝娜就低头看了看自己的身体：

「你说的「所有」，是真的所有吧」

「嘛、那当然是……所有吧」

我如此回答着，同时迅速检查了一下这位细剑使的行头。

明显的金属装备只有轻薄的胸甲和配有腰甲的皮质腰带。她外面披着的红色连帽斗篷、里面穿着的淡粉色束腰外衣、以及深棕色的百褶裙，这些都是布制或皮质装备。只要取下胸甲、腰带、耳朵上的耳环、还有双手食指的戒指，应该就没有金属制品了。哎呀差点忘了，挂在左腰上的细剑《骑士轻剑（Chivalric Rapier）+7》当然也要取下来。

虽然除了凯尔派之外不太可能出现其他水生怪物，但如果不把武器随时准备好，以便能够随时装备的话……我一边这么想着，一边打算接着检查自己的装备。然而——

「……呐，桐人君」

「这条裙子的布料里好像有硬硬的东西，这也是金属吗？」

这突如其来的问题让我一下子愣住了，我直愣愣地盯着亚丝娜的皮裙。到这时我才突然想起来，这件装备的正式名称是《护板皮革短裙（Pleated Leather Skirt）》。「在皮革面料和布制内衬之间缝入了许多又细又薄的金属板，兼具了柔韧性和防御力」……应该是这么描述的。

「……确实是金属呢」

我回答着，再次仔细端详起搭档的行头。由于夜视能力发动，我接连发现了之前没能注意到的金属光泽：

「啊—，那个斗篷的搭扣，看起来像是银的呢。靴子上也有铆钉，束腰外衣的纽扣好像是黄铜的……」

「几乎全都得脱掉啊！」

我被亚丝娜狠狠地瞪了一眼，于是连忙补充道：

「不、不是，那双过膝袜应该没——」

还没等我把「没问题」说完，亚丝娜的眼神就变得更加锐利了，于是我清了清嗓子，提出应对方案，

「要不，穿上那种能把脚完全遮住的布制长袍之类的，在里面把装备都解除掉不就行了吗？」

「…………」

亚丝娜默默地打开道具栏，快速滑动浏览着装备列表。不久，她似乎就找到了目标物品，随后用手指点了几下。

于是，红色连帽斗篷消失了，取而代之实体化的是一件宽松的白色连衣裙。连衣裙是无袖的设计，垂下的布料在胸前和背后自然地形成了褶皱，看起来像是古希腊的希顿服（Chiton）。

「……你什么时候买了这么一件衣服啊？」

亚丝娜一边继续操作着窗口，一边回答道：

「在第七层的时候，为了泡澡之后穿才自己做的」

「原来如此……看起来很凉快，不赖」

在我们自然而然地继续交谈的过程中，亚丝娜在连衣裙下面的装备也接二连三地消失了。先是胸甲、再是束腰外衣和裙子、靴子和饰品也消失了……这样一来，所有的金属制品应该就都去掉了。

换上连衣裙的亚丝娜，用余光瞥了我一眼后说道：

「你那边打算怎么办？感觉你身上的金属比我还多哦」

「我披上这个，在里面解除装备哦」

我回答后拿起了放在眼前横板上的布。这个整齐叠着的布块，是名为《亚尔基洛的薄布》的魔法道具，能给覆盖上的东西带来强力的隐蔽效果。

因为周围不被水环绕的话就无法发挥效果，所以一直没有什么用武之地，但在船上的话就完全满足条件了。

「原来如此……帕库奇！」

亚丝娜点了点头，突然可爱地打了个喷嚏，我急忙把亚尔基洛的薄布放回到原处。因为我现在全副武装着，所以几乎感觉不到寒冷，但现在可是隆冬时节的晚上八点多。就算不像埼玉、川越的一月那样冷，只穿一件无袖连衣裙的话，体感温度估计也在十度以下了吧。不能因为亚丝娜说话带有东京腔——或者因为很熟悉《位于千叶但属于东京》的某主题公园〔译：迪X尼〕，就断定她和我都是关东人。

「抱歉，我划快点」

我这么说了一句，再次划动船桨。

蒂涅尔号追着倒映在湖面上的月光笔直前行，不久，前方就出现了黑压压的森林的轮廓……我刚这么想，周围就无声地涌起了雾。这就是之前说的边界效果。

就算从副本里出去应该也不会有什么问题，但如果可以的话，我还是想在边界内侧完成任务。雾眼见着越来越浓，等蒂涅尔号的船头装饰都看不见的时候，我才停下了船桨。

「帮我把船锚扔下去」

我小声请求道，亚丝娜半蹲着走到船头，双手拿起船锚，轻轻地抛入水中。锁链哗啦作响一阵后停了下来。

回来的亚丝娜，稍微瞥了一眼船头之后，小声地说道：

「那个……就算我们把身上的金属制品都拿掉了，蒂涅尔号上也还是有船锚、冲角，以及其他各种各样的金属部件吧。如果凯尔派讨厌金属的气味，那是不是不离开船就不会出现啊……？」

「唔嗯，这点我也很在意啦……」

我稍微停顿了一下，在脑海中整理了一下目前为止获得的情报后继续说道，

「准确地来说，凯尔派应该不是本能地讨厌金属的气味，而是根据金属的气味来判断是否有危险吧。毕竟当绮兹梅尔和蒂涅尔在岛上的沙滩上看到凯尔派的时候，她们身后的尤菲尔城应该也散发着浓重的金属气味才对」

「啊……确实是这样呢。这么说凯尔派能够分辨出环境中的金属气味、和人或精灵身上携带的金属的气味……？」

面对睁大双眼的亚丝娜，我一瞬间有些犹豫该如何回答。因为这里是游戏世界，因此凯尔派并不是真的通过嗅觉来分辨气味，只不过是游戏系统读取了玩家的装备数据而已……这样的道理浮现在我的脑海当中，但我还是把这个想法推到一边，说出了另一个答案：

「既然凯尔派能在水面上行走，那应该也是类似的魔法力量吧」

「这样啊……毕竟它就像是妖精一样呢」

亚丝娜像是理解了似的喃喃自语着，然后突然打了个哆嗦。在这个世界里不用担心感冒——应该吧，但还是有可能会受到寒冷伤害。

「好了，差不多该开始了」

听到我这么说，亚丝娜点点头再次走到船头附近站好。

我在船尾蹲了下来，展开亚尔基洛的薄布，从头上套了下来。HP条旁边随即就亮起了表示隐蔽状态的图标，视野下方的《隐蔽率（Hide Rate）》指示器则显示为百分百。虽说很少能看到这样的数值，不过凭借自身的隐蔽技能再加上魔法道具的效果，那达到这种程度倒也不奇怪。

我在这种状态下打开菜单窗口，把武器和防具一件件地脱掉。当然，上下身的内衣还是留着的，不过我已经确认过这些衣物上没有金属了。接下来，就只需等着凯尔派出现了。

我在薄布上留出一个小缝，从中窥探着亚丝娜的情况。即使在不规则摇晃着的凤尾舟上，她也能一直笔直地站着，她的平衡感还真不是盖的。

清冷的月光把亚丝娜白色的连衣裙和白皙的肌肤都染成了青色，蒂涅尔号的船体、以及笼罩在周围的雾气也都是同样的色调，简直就像是只用几种颜料画出来的画一样美。光是远远地看着，我的意识就仿佛要被吸进去了，我不由自主地握紧了手中抓着的薄布。

突然，我想起了曾经和妹妹一起看过的一部纪录片，讲的是在伪装帐篷里等待拍摄稀有动物的故事。在那部纪录片当中，摄影师会耗费好几个月的时间来等到目标动物出现，但那毕竟是现实世界里的事情。在游戏世界当中，只要满足严苛的出现条件，那些稀有怪物就会有很高的概率出现，这就是游戏世界的法则。

大概过了五分钟听不到任何声音的奇妙时间后——

笼罩着凤尾舟的浓雾突然毫无预兆地分开了。在亚丝娜的正前方，也就是我的左前方，出现了一条大约三米宽的雾之隧道。

紧接着传来了啪沙、啪沙的轻微水声。从隧道的深处，一个泛白的影子逐渐靠近。凯尔派——如果是的话——比我想象的要大不少。因为它是妖精的一种，我本以为它大概和小马驹差不多大，但它的体型却和在第六层穆尔茨奇村看到的三峰骆驼差不多、甚至还要更大。

为了能在关键时刻能立刻通过「快速切换」来装备上剑，我抬起右手等待着。那个影子不紧不慢地、一步一步缓缓靠近我们。

最先映入眼帘的是它的右前腿。

正如绮兹梅尔所说，腿下方长着的不是蹄子，而是像鸭嘴兽一样的蹼和爪子。它每踩一下水面，就会伴随着水声泛起波纹。〔译：马+鳍〕

啪沙、啪沙……不知迈了多少步之后，我终于能够看清它的全身了。

即使月光并没有多么明亮，也能清楚地看到它的体色是略带绿色的青蓝色。皮肤质感宛如天鹅绒般光滑，上面隐约浮现出鳞形的花纹，以及那如同琉金金鱼〔译：日本的一种金鱼〕的鱼尾般飘动的鬃毛，这些都和绮兹梅尔描述的一样。

不知不觉间，凯尔派和亚丝娜之间的距离已经不足五米了。虽说它是稀有种，但毕竟是在第四层出现的怪物，以亚丝娜现在的实力，就算不穿防具挨上一击，HP应该也不会大幅减少，话是这么说，我的呼吸还是因紧张而急促起来。

当青蓝色的马又向前迈出一步的时候，它的鬃毛上方终于浮现出了彩色光标。

上面显示的名字是……【Morvarc'h the Lake Kelpie（湖之水马 莫瓦克）】

————这不是BOSS吗！！

我在脑海中发出无声的尖叫，试图打开窗口。

然而就在即将打开的瞬间，亚丝娜微微抬起左手制止了我。

在这时我才终于注意到，光标的红色对于一个BOSS来说有点太浅了。从色调上来看，比起纯正的大红色要稍微明亮一些，应该说是珊瑚红吧。这意味着它的综合数值应该略低于我。尤菲里斯子爵也说过「应该不是现在的桐人的对手」……不，那句话有着「如果在陆地上或者在船上战斗」的前提条件。

再观察一会吧——虽然不知道这个固有名称该怎么读，但在凯尔派明确表现出敌意之前，先继续待机吧。

做出这个决定之后，我稍微放松了一下握住薄布的右手。

一直以每两秒一步前进的凯尔派，在距离亚丝娜不到两米的位置停了下来。它伸出头，反复抽动着大大的鼻孔。似乎是在确认她连衣裙下面有没有藏着金属物品。

这个动作简直和真正的马一模一样，但从我这边看到的它的右眼，既没有虹膜也没有瞳孔，鱼鳍状睫毛下方的眼球本身散发出淡淡的蓝色光芒。现实世界里可不会有这种东西……嘛，在SAO当中，像灵体系之类的幻想怪物可是如山一样多。

在几个小时前我就想过，亚丝娜并不擅长应对灵体系怪物。眼前的凯尔派也是介于生物和幽灵之间的存在。虽然现在担心为时已晚，但细剑使只是纹丝不动地凝视着眼前的魔兽。

不久，凯尔派似乎确信亚丝娜没有持有武器，于是又靠近了两步，庞大的身躯也向右旋转了九十度。我差点以为它发现了躲在船底的我，但看来不是。它把身体靠在蒂涅尔号的左舷，折叠四肢蹲下后，对亚丝娜发出了轻柔的嘶鸣：

「布噜噜噜……」

那低沉而温和的声音，就连我也明白是在说「来、骑上来吧」。如果我没有听子爵讲过凯尔派的传说——「如果它觉得对方没有威胁，就会靠近并引诱对方骑到它的背上，而那些傻乎乎地骑上去的愚者就会被它直接拖进水里」的话，我可能就会因好奇心的驱使而直接骑上去了。

瞬间，亚丝娜轻轻地握紧了左手。这就是之前约定好的、执行作战计划的信号。

我扯下亚尔基洛的薄布单膝跪地，然后突然想到：

——说是使役，可我该干什么呢？〔译：合着你没想过啊……〕

妮露妮尔在第七层的迷宫区使役小巧蜘蛛时，只是静静地盯着它看而已。既没有念什么咒语，也没有伸手去触碰它之类的动作，天花板上的蜘蛛就自己爬过来完成了使役。真该在那个时候问问她做了什么……但现在后悔也来不及了。

注意到我的凯尔派，发出了「布噜噜！」的凶猛叫声，想要站起身来。不知道它是想逃跑还是要发动攻击，但现在留给我的时间就只剩几秒了。

我破罐破摔地朝凯尔派伸出右手，试图发射使役光线之类的东西。但并没有发射出那种东西，而且也没有那个必要。

当凯尔派发光的蓝眼和我的视线交汇的瞬间，我的视野就染上了淡红色，原来显示《隐蔽率》的位置，现在则出现了一个新的指示器。

我凭直觉明白了这就是所谓的《使役进度率》指示器。看起来，据说只有夜之住民及其后裔才能使用的使役能力，似乎只要和目标对上视线就能发动。那这样的话，如果是没有眼睛的怪物该怎么办呢？我的脑海中浮现出了这样的疑问，但这种事现在根本就不重要。

凯尔派保持着前倾的起身姿势静止不动。我也维持着类似的姿势，拼命地和它对视。在我视野的下方，使役计量器在缓缓上升着，我只能用余光确认到这个。恐怕只要视线移开一瞬间，使役挑战就得重新开始，而且也不一定有机会再次从正面看到凯尔派的眼睛。笼罩我视野的神秘红色光芒越来越强，HP条、时间等各种系统UI几乎都看不见了。

很久很久之后，『在那个时候，要是一直看着双眼闪着红光的桐人君的话，我都担心自己也要被你驯服了哦—』亚丝娜一边温柔地笑着，一边如此说道。

当然，并不会发生那种事情——说到底在SAO的系统当中，是不可能给玩家施加魅惑、催眠之类的精神操作类负面效果（Bad Status）的——我用余光注意到视野右侧的亚丝娜向后退了半步。

不知道是这个动作干扰了凯尔派的抵抗，又或者只是单纯的巧合。僵持在70%左右的指示器，一口气冲到了最右侧的100%。我视野中的红色逐渐变淡、指示器不久后也消失了。

「布噜噜」

凯尔派简短地叫了一声。而声音之中已经没有了刚才的凶猛。这语气反而像是在说「哎、呀嘞呀嘞」，不过这可能只是我的错觉吧。

我轻轻地站起身来，先看了看右边的亚丝娜，又看了看凯尔派，随后再次看向亚丝娜：

「呃……这样应该算是使役成功了吧……？」

我小声地问道，亚丝娜头也不回地回答：

「别问我呀」

我觉得她说得有道理，当我第三次看向凯尔派时，光标颜色就仿佛看准时机般，由偏亮的朱红色变成了沉稳的黄色。

我在大赌场的科尔罗伊家的马厩当中、发现的处于使役状态的锈迹杂色狼（Rusty Lykaon）——不过其实是它的上位种暴风杂色狼（Storm Lykaon）——的光标颜色也是黄色。虽然大概是使役成功了，但对方毕竟是带有定冠词的BOSS级怪物。要是我做了什么惹它不高兴的事，说不定一下子就会解除使役状态。

当我不知所措地站在原地的时候，亚丝娜瞥了我一眼后说道：

「要不喂点饭吃？」

「啊……啊啊，也是」

确实，喂食是提高使役怪物友好度的常用方法，我打开道具栏调出与食物有关的物品，乱七八糟的各种物品就一下子填满了列表。

子爵说过「水马的主食虽然是鱼，但它也会上岸袭击野兽」。那它应该也会吃这个吧，我这样想着，将《大蟹的蟹爪肉》给实体化。

从窗口上出现的是，大概超过了六十厘米的超巨大蟹爪。钳子部分还带着红黑色的甲壳，不过驱动钳子的粗壮肌肉已经剥去外壳，纯白的纤维反射着月光闪闪发亮。

掉落这个蟹爪的，是出现在第四层东北部水路迷宫里的螃蟹型怪物《凿船螃蟹（Scuttle Crab）》。这种怪物展开双钳的体宽足有四米，实在是很难想象它和我在尤菲尔城食堂里吃到的一口大小的河蟹是同一类生物，不过昆虫和植物之类的生物一旦怪物化就会变得巨大，这也算是游戏世界里约定俗成的事了。

我用右手抓住钳子的一端，把它举了起来。然后关掉窗口，将沉甸甸的蟹爪伸向凯尔派。

「那个—，可以的话，吃点这个吧……」

我知道对已经使役完成的怪物没必要这么客气，但话已经说出口了也就没办法了。要是妮露妮尔看到了，不知道她是会哈哈大笑还是会目瞪口呆呢……我一边在脑海的一角中想着这些，一边等着BOSS怪物大人的反应。

凯尔派怀疑地眨了眨眼，然后伸长脖子闻了闻蟹爪的气味。

「布噜噜……」

——嘛，就吃一点吧。它似乎是带着这样的情绪哼了一声，然后突然长大了嘴。

随之露出来的一排排牙齿全都是肉食动物的尖锐牙齿，我差点反射性地把手缩了回来，但最终还是忍住了。凯尔派一口咬住了有着橄榄球那么大体积的蟹肉，用惊人的切割力和咬合力咬下了大约四分之一，然后发出响声咀嚼起来。

仅仅五秒钟它就把咬下的部分吞了下去，接着是第二口、第三口，凯尔派以猛烈的速度把蟹肉消灭掉了。吃到第四口的时候，它把钳子根部的肉也吃光了，然后从鼻子里喷出一口气。

我轻轻地举起剩下的蟹爪壳，出于谨慎确认了一下：

「那个，这个吃……」

「布噜！」

「不吃对吧」

我立刻把钳子缩了回来。亚丝娜在这时轻轻地笑出了声，我心想「要是凯尔派大人生气了该怎么办啊！」但当事人、不，当事马却一副若无其事的样子。

我松了口气，低头看了看剩下的蟹爪壳。

锋利的尖端带着黑色的金属光泽，内侧也排列着无数的锯齿。

确实，吃了这个的话，说不定胃都会被吃出个洞来。据亚丝娜所说，蟹爪的原主人《凿船螃蟹（Scuttle Crab）》名字里的Scuttle，似乎是有着《在船底凿洞让船沉没》意思的动词，这蟹爪确实有着与之相称的凶狠锐利。

也许加工一下能成为厉害的武器，我把吃剩的壳再次放回到道具栏中，又重新看向凯尔派。

虽然我想确认一下它吃了蟹肉后有没有提高友好度，但它只是一脸平静地左右摇晃着长长的鱼鳍状尾巴，完全看不出心情好坏。不过既然使役作战成功了，我和亚丝娜接下来就必须骑着凯尔派大人到尤菲尔城的后方去。

「……呐，桐人君」

亚丝娜侧着身子靠了过来，一边用手掌摩擦着裸露的双臂，一边小声说道，

「已经可以穿上防具了吧？」

「啊—……」

听到她的话，我也意识到了寒冷。亚丝娜只穿着一件薄薄的连衣裙，我也只穿着衬衫和裤子。难怪刚才搭档大人一直不往这边看。

如果「凯尔派讨厌金属是为了躲避危险」的说法是正确的话，那么它应该不会在意作为同伴的我们的剑和铠甲。但突然变成全副武装，别说凯尔派可能会受惊了，就连我都有些不放心。

「稍微试一下吧」

我这样告诉亚丝娜，然后再次打开了窗口菜单。从所持物品里随便选了个不知道哪捡的《金戒指》实体化。

就算金戒指出现在了窗口之上，凯尔派也完全没有看它一眼。我试着把戒指戴在手指上，结果也还是一样。

「……应该是没问题」

我和亚丝娜点了点头，随后就争先恐后地把装备恢复成了原来的样子。寒冷一消失，我们俩都不约而同地吐了口气。看到嘴边的白色水蒸气消散后，我们默默地对视一眼，同时笑了起来。

突然，我感觉自从成为夜之民——不，自从吸血鬼化后，一直盘踞在我心底里的那一丝恐惧正逐渐消散。

不是有可能被阳光烧死的恐惧。而是害怕在系统上已经不算是人类的我，会被亚丝娜给抛弃掉。当然，这种话我到死都不会对本人说的。

——你这家伙，总是想得太多了啊。

我在心里责备着自己，然后说道：

「绮兹梅尔会担心的，差不多该去集合地点了吧」

「也是。——把蒂涅尔号留在这里没问题吗？」

「这里是副本区域的内侧，所以抛下船锚就没问题。差点忘了，这个也得收起来呢」

我拿起亚尔基洛的薄布放回到道具栏里。在确认船上没有留下任何东西，船锚也好好地抛下了之后，我再次看向凯尔派。

「呃……该怎么称呼这家伙好呢……」

我一边嘀咕着，一边再次看向HP条上方的名字。【the Lake Kelpie】应该是《湖之水马》的意思，但【Morvarc'h】……我连怎么读都不知道。

「我也不太好说……莫瓦克，可能是这么读吧」

「哦哦……那，就叫阿哞吧」

我刚说出这个简单直白的提议，亚丝娜就夸张地皱起了眉头：

「欸欸—？总觉得听起来像是牛啊？」

「祖先不都是一样的嘛。好，就叫你《阿哞》了！」

我对凯尔派如此宣告之后，它就回了一声「布噜噜！」。虽然完全听不出有高兴的意思，但也不像是在拒绝。

「呃……阿哞，能让我和亚丝娜骑上去吗……」

凯尔派、也就是阿哞，再次蹲了下来，把背靠近凤尾舟的船舷。看起来似乎是愿意让我们骑上去，但——

「那个，你刚才说了「哼」对吧？对吧？」

「…………」

我正想追问扭过头去的阿哞，亚丝娜就猛地拉了一下我大衣的后颈。

** 第7章

骑乘凯尔派的感觉，比我预想的要舒适许多。

我本已做好了像是坐在湿漉漉的长椅上那样，连屁股都会被湿气彻底浸湿的觉悟。然而它那如同天鹅绒般的皮毛手感十分干爽，而且还带着微微的暖意。它身上的鳞片也并非真正的鳞片，只是短毛以鳞片的花纹生长着而已。虽然是没有马鞍和马镫的所谓「裸马」，但骨头倒也不会硌得慌。

当然，因为没有缰绳，所以我只能用嘴来传达指令。不过，阿哞能准确地按照诸如「在前面左转」「稍微慢一点」的模糊指令来奔跑。但说是奔跑，也并非是让它全力疾驰，只是保持着让马蹄轻敲水面、发出Qiapu Qiapu轻快节奏的速度，从迎面吹来的夜风的感觉来判断，时速大概能到十公里左右。

「哇……真舒服呢……！」

坐在后面的亚丝娜发出了有些雀跃的声音。如果可以的话，我真想让她坐到前面来，但我担心凯尔派只听我这个系统上的使役者（Master）的命令，而且我也有些害怕尝试。要是能顺利完成委托的话，那到时候想让她坐多久就坐多久……我在心里暗自下了决定后，集中精力驾驭阿哞。

我们左侧的湖心上矗立着灯火通明的尤菲尔城，阿哞则紧贴着副本区域边界的内侧逆时针前进。先向南绕了一大圈之后，再朝着城堡的后方前进。

塔楼的哨兵们会密切留意渡湖的船只，但水面上行走的马大概不在他们的警戒范围内吧。而且从北侧靠近的话，城堡会遮住月光，所以除非有着与夜之住民相当的夜视能力，否则绝无可能发现我们。

我们降低了速度，在一片漆黑的阴影中小心翼翼地前进。尤菲尔城所在的岛屿北侧是陡峭的悬崖，而悬崖正下方有一片小小的沙滩。我定睛一看，勉强能辨认出沙滩上有两个人影。

「绮兹梅尔他们在吗？」

亚丝娜向我问道，她大概什么都看不到吧，我点了点头：

「嗯，等等就能看到光标了吧」

阿哞的脚下一边发出Qiapu Qiapu的水声，一边靠近沙滩。那里应该就是绮兹梅尔和蒂涅尔在三年前看到凯尔派的地方。

说不定我和亚丝娜在夜雾中穿越了时光，出现在了毕业旅行中的那对姐妹面前……我在脑海中闪过了这么一瞬间的想象。但这当然是不可能的，在数十秒后出现的两个彩色光标，果然如预想的那样，是绮兹梅尔和尤菲里斯子爵的。

亚丝娜大概也在同时确认了两人的名字吧，她在我身后轻轻松了口气，小声说道：

「绮兹梅尔也能骑到这孩子身上吧？」

「肯定很轻松吧，这家伙可是和松风一样大哦」

「哈？……呃，我记得是前田利益的马来着。你可没见过吧！」〔译：别名前田庆次，日本战国时期的武将〕

她隔着大衣戳了戳我的侧腹，我自言自语地嘟囔道「确实是这样啦……」

凯尔派似乎并不是只能在水面上行走——至少阿哞不是这样，快要到沙滩的阿哞，踩着沙子发出沙沙的声音上了岸。

因为没有马镫，所以我像是跳马运动员一样，从阿哞的背上跳了下来，然后伸手帮亚丝娜下马。之后，我转身面向黑暗精灵们。绮兹梅尔变回了往常的铠甲加披风的装扮，尤菲里斯子爵则穿着现实世界中大概叫拿破仑夹克的、带有肩章和装饰绳的立领上衣，下半身则是大腿部分比较宽松的骑马裤，完全是一副盛装的打扮。当然，两人的左腰上都带着剑。

我深深地低下头，向恐怕已经等了我们三十多分钟的城主大人谢罪道：

「让您久等了，实在是非常抱……」

然而，子爵迅速举起右手打断了我的话，毫不掩饰地感叹道：

「……真是美啊……」

他向前迈出一步，抬头看着比身材高大的子爵还要更高一些的阿哞的脑袋。

「这正是我在小时候遇到的那只凯尔派。这家伙应该不记得它曾经想要吃掉我了吧」

「「欸」」

我和亚丝娜同时叫出声来。在子爵身后，绮兹梅尔也瞪大了眼睛。

「不用担心，我对这家伙没有遗恨哦。都怪那时傻乎乎地骑上去的我太愚蠢了」

就在这时，阿哞仿佛是听懂了这番话的意思，它转动着脖子，看着子爵「布噜噜」地低鸣了一声。听起来像是在说「就是这样」，不过我还是当作是自己的错觉，随后我向子爵问道：

「您、您没事真的是太好了。您是游泳逃走的吗？」

「不……是有人救了我。不然的话，我大概已经成了这家伙的早餐了吧」

「没、没发生那种事真是太好了」

我不知道我这句朴素的回答有没有传到子爵的耳朵里。因为子爵的视线难得地飘向了远方，完全不知道他在想些什么。

但这也只持续了几秒而已，尤菲里斯子爵眨了眨他那灰绿色的右眼，然后看着我再次微笑起来：

「虽然我说过能做到，但说实话，我没想到你在今晚就能引出凯尔派来、甚至还能成功使役啊，桐人。把你收为家臣的纳克托伊家的家主真有眼光呐。早知道会这样，我就算硬来也要把你和亚丝娜都招到尤菲里斯家来为我效力了」

「不、不，实在是不敢当」

我说的话不知为何染上了时代剧台词的腔调。同时，我也在思考「我真的算是妮露妮尔的家臣吗」，虽然我并没有正式宣誓效忠，但「她是主人、而我是眷属」这点是确定的，一般来说这也算是主从关系吧……就在我暗自思索的时候。

「那就很让人为难了，阁下」

绮兹梅尔用七分认真，三分玩笑的语气说道，

「桐人和亚丝娜可是预定要在王城谒见陛下、并被任命为最初的人族近卫骑士呢」

————什么？

我还没来得及反应，子爵就轻声笑了起来：

「呵呵呵，那我只好退出了呢。我会在这里向圣大树祈祷的，期待着那一天的到来」

我完全看不透他们俩到底有几分是认真的，不过很遗憾，我和亚丝娜成为近卫骑士的那一天大概不会到来吧。虽然我在封测中完成了精灵战争 战役任务，也谒见过黑暗精灵女王陛下，但她并没有任命我为骑士。

不过，我当然不会对亚丝娜说这种扫兴的剧透，所以我把它藏在了心中的一角。与此同时，子爵也收起了笑容，微微抬头看了看漆黑的天空：

「……那么，差不多该出发了吧。要是特意来见我的人被熊袭击了，那我晚上可就睡不好了」

如果是原骑士团团长拉维克的话，说不定反而会把熊打倒吃掉呢……我这么想着，然后又想起第四层的熊之森中栖息着一只身高八米的喷火熊。虽然熊之森离这里有一段距离，但那家伙说不定偶尔也会想吃尤菲尔湖的鱼呢。

子爵走到沙滩和湖水的交界处，随后毫不犹豫地迈出了右脚。他那高挑削瘦的身子就这样在湖面上前行，他走路时发出的水声比凯尔派行走时还要轻微。我当初用《薇丽之水滴》在第六层的塔尔法湖上行走时，只能弓着腰慢慢前行，而子爵的背却挺得笔直，这显示出他对自己的技术以及脚上穿着的魔法靴有着绝对的自信。

看到尤菲里斯子爵在前方大约五米的地方停下了脚步，我也靠近阿哞，轻轻拍了拍它的脖颈。凯尔派虽然有些不太情愿地喷了下鼻子，但还是在原地跪坐了下来。我也单膝跪地，用双手当作踏脚的地方，先让亚丝娜坐到它那宽阔的背部中间，然后让绮兹梅尔坐在亚丝娜后面，最后，我按照跳高的要领，稍微助跑之后跳到了最前面。

不出所料，三个人骑在上面也没有觉得拥挤。当然，四个人的话肯定就很勉强了，不过脖子处应该还能坐一个小孩子。但骑手们的体积和重量又是另一回事了。

「阿哞，能站起来吗？」

我这么一问，阿哞就「哼」地喷了一下鼻子，完全没有表现出吃力的样子就将庞大的身躯直立起来了。与其说是用四肢的力量站起来，倒更像是轻飘飘地浮起来了一样。说不定凯尔派的魔力并不是能在水面上行走，而是某种有限定范围的飞行能力……虽然我这么想，但现在并没有时间去验证。

「跟在子爵身后走吧」

我如此下达指令之后，又担心它可能不知道子爵是谁，不过阿哞毫不犹豫地就开始走了起来。它从岸边踏上湖面，就这么Qiapu Qiapu地朝着尤菲里斯子爵的方向走去。

这样一来，必然就变成了从上往下的俯视状态，但城主大人似乎并不在意。

「要稍微快点了」

子爵这么说完，就开始朝着尤菲尔湖的正西方跑了起来。虽然不是全速冲刺，但也是慢跑的速度。阿哞则在子爵后面快步追着。

一切都按照计划进行——虽然是这样，但这样看起来，简直像是尤菲里斯子爵是马夫，而我们才是贵族一样。不管怎么说，这也实在是有些……亚丝娜大概也有相同的想法吧。她在我身后小声地对绮兹梅尔说道：

「呐，绮兹梅尔，让子爵大人一个人跑着，他不会生气吧……？」

我本期待绮兹梅尔能立刻否定我的担心，但这位骑士的回答却有些模棱两可：

「唔姆……我也没有过这样的经验呢。嘛……不过这个凯尔派在以前似乎想吃掉阁下，说不定阁下根本就不想骑吧……？」

「也、也是呢……」

我想阿哞大概也听到了她们的对话，但它那悠闲的步伐并没有改变。不过，看着子爵在前方两米处晃动着的发辫，我越来越担心阿哞会不会突然心血来潮冲上去咬子爵了。

到时候我要拼尽全力去拉住眼前的鬃毛或背鳍，在做好了这个觉悟之后，我把视线再次投向了更前方。

我们很快就要走出城堡的阴影了，但我们没有携带任何发光的东西，而且和船不同，我们也不会留下航迹。如果哨兵们没有夜之住民那样强大的夜视能力，那应该是发现不了我们的。

唯一让人担心的，就是湖里会不会突然跳出怪物来，不过我完全没有感觉到那样的气息。也许是子爵用了驱赶魔物的咒语之类的东西，又或者是身为BOSS怪物的阿哞让那些杂鱼怪们感到害怕了，还有可能是两者皆有。

总之，我们四人一马平安无事地渡过了湖面，到达了目标地点——尤菲尔湖西岸。

这一带的水比较浅，上岸很容易。子爵放慢了速度，走过了湖岸线，在白色沙滩的中间位置停了下来。

我也让阿哞再往前走了一段距离才停下来。我迅速跳下马，伸手帮助亚丝娜和绮兹梅尔下马，然后长长地舒了一口气。

我接受的委托是《今晚让尤菲里斯子爵不带护卫地来到这里》。现在的时间是晚上八点五十五分，虽然不算早，但也不算太晚。

我抚摸着阿哞的脖颈，安慰它说「辛苦你了，谢谢啦」，然后环顾了一下四周。白色的沙滩南北延伸了约二百米，但完全看不到人影。今天早上从大浴场的窗户眺望这里时，确实看到这附近有闪烁的篝火，现在却连一点痕迹都没有留下。

「……到底去哪了呢……」

亚丝娜疑惑地小声说道。难道他真的被喷火熊《巨震地懒（Magnatherium）》给袭击了吗……正当我开始担心的时候——

尤菲里斯子爵默默地朝着北方走了五步左右，然后将身体向左转了过去。前方是一片茂密的夜之森林。森林深处暗到连我的夜视能力都无法看清。

突然，灌木丛沙沙作响，我的右手猛地一动，但就在我的指尖即将碰到哀伤夜想曲的剑柄的瞬间，一个悠闲的声音响了起来：

「哎呀，服了服了……」

拨开灌木丛走出来的，是一个穿着素色衬衫、外面套着茶色皮革背心、下身则是麻布裤子和黑色皮靴的黑暗精灵。他摘下粘在脑后发辫上的树叶，砰地弹飞出去，然后对着在稍远处站成一排的我、亚丝娜和绮兹梅尔，露出了毫无恶意的笑容，

「让你们久等了，真是不好意思。我看到一只很肥的角兔（Horned Rabbit），没忍住就去追它了，结果还是让它跑掉了」

说出这番悠闲话语的，毫无疑问就是拉维克原骑士团团长。看起来他似乎没有遇到喷火熊。

「不，我们也是刚到。倒是我们这边让您久等了，非常抱歉」

拉维克只是轻轻地点了点头，然后终于把脸转向了正前方。

他一看到站在前方仅三米处的尤菲里斯子爵，那留着短须的嘴角的笑容就消失了。

子爵也不知道什么时候收起了笑容，从我这边只能看到他的左脸，因此无法知道他的独眼现在闪烁着怎样的光芒。

一阵冷风吹动了两人的发辫。我这才第一次注意到，两人的身高几乎是一样的。

大概过了五秒、说不定有十秒的时候，子爵终于开口了：

「真是好久不见啊，拉维克·冯·科尔塔西奥斯」

子爵轻抬左手，用指尖抚过从额头延伸到脸颊的旧伤，

「从骑士绮兹梅尔那听说事情的缘由时，我就确信了肯定是你（そなた）把我叫到这种地方来啊。「三十年前没能夺走我的性命，这次一定要……」是为了这种事情吗」

「…………！」

在一旁的我们同时屏住了呼吸。

我其实也不是完全没有想过尤菲里斯子爵的左眼是被拉维克原骑士团团长给砍伤的可能性。两人的脸上分别有着一道竖着的旧伤和一道横着的旧伤，就算不是在游戏世界当中，任谁也都会想象这是两人互相砍杀的结果吧。

但从第四层迷宫区的安全屋相遇、再到在尤菲尔湖岸边下船为止，我完全没有感受到拉维克有哪怕一丝一毫的复仇念头。而且，要是他打算和仇敌决斗而大老远地从第七层来到这里，也应该选一个更好一点的地方才对。这里的沙滩很狭窄，宽度还不到四米，并且沙地十分地湿滑。既然是一名身经百战的骑士，那应该会希望在一个能充分发挥自己练就的剑技的舞台上来战斗吧。

果然，在听到子爵的话后，拉维克露出了大大的苦笑：

「用来点燃遗恨火焰的灯油早就干涸了啊。而且，在单人牢房里反省了三十年之后，我也能看清楚曾经看不到的东西了」

刚说完，我们就松了一口气。看起来拉维克并不是为了和尤菲里斯子爵战斗才来到第四层的。要是拉维克有那个意思的话，那我们可就变成骗子爵来和刺客见面的帮凶了。

但这样的话，原骑士团团长为什么要把子爵叫到这种地方来呢——而且还是不带护卫的前提下。

「列休连〔译：子爵的名字〕」

拉维克突然收起笑容，他的声音和表情前所未有地认真，

「就像我刚才说的，我心里已经没有对你的怨恨和憎恶了。我弟弟……兰德伦，据说也作为一名出色的铁匠生活着」

「……你见过兰德伦了吗？」

「没有。但是，我看到了那小子锻造的剑」

拉维克一瞬间看了一眼亚丝娜。这么说来，他当初在哈林树宫的牢房里，只是对着微弱的光线看了一眼亚丝娜的《骑士轻剑》，就看穿了「这确实是兰德伦锻造的剑」。我记得一开始对我们的态度极其冷淡的他，后来不惜越狱也要帮忙寻找和营救绮兹梅尔，也是因为这个契机。

尤菲里斯子爵也看了亚丝娜一眼，然后像是认可了一样点了点头：

「原来如此，亚丝娜的剑是兰德伦打造的啊……」

「唔姆。我虽然没有锻造的才能，但还是能看出来「如果挥舞锤子的手臂有迷茫的话，是绝无可能锻造出如此好剑的」」

拉维克用平静的声音说完这些后，再次从正面直视尤菲里斯子爵，

「再说一遍，我心中的遗恨都已经扔到树宫的牢房里了。在此之上，列休连……我有一个请求」

「……说吧」

在子爵的催促下，拉维克突然挺直了背，右手握拳放在左胸上，用毅然的声音说道：

「琉苏拉骑士拉维克·冯·科尔塔西奥斯 ，赌上名誉向尤菲尔城城主列休连·泽德·尤菲里斯子爵提出决斗。明晚九点，在第四层的天柱之塔的守护兽房间，恭候大驾！」

————给我等等啊啊啊！

为了不大喊着冲进他们两人之间，我用力地握紧了双手。



明明刚才还说已经没有仇恨和憎恶了，那还有决斗的必要吗。既然说是「赌上名誉」，那肯定就不是用木剑或者点到为止的比试，而是用真剑的认真战斗吧。我很想设法阻止这场决斗，可他们两人现在散发出来的气氛根本容不得旁人插嘴，而且说到底，我们完全不知道他们之间到底有什么样的恩怨。

我往旁边一看，亚丝娜和绮兹梅尔也都呆呆地站在原地，阿哞则一副事不关己的样子躺在沙滩上。事已至此，就算无法阻止决斗，也得想个理由来让决斗延期。这一层的迷宫区里有堕落精灵的转移装置，要是拿这件事来说的话，说不定……当我拼命地想出这个理由的时候。

尤菲里斯子爵同样流畅地举起右拳，咚地一声敲在了左胸上：

「决斗的事，我就接下了」

子爵用平静的声音宣告之后，甩动着黑发，背对拉维克悠然地离开了。子爵在湖岸边停下脚步，望着湖面呼唤着我们的名字，

「骑士绮兹梅尔，剑士桐人、亚丝娜。我深知你们在此地也有其他必须完成的使命，但能否请你们明晚来见证这场决斗呢」

「……呃、这……既然是阁下的吩咐，那我们自当遵从，但是……」

绮兹梅尔露出了十分为难的表情，子爵轻轻举起右手打断了她的话：

「我没有其他可以拜托的人了。要是城堡里的近侍知道了决斗的事，你们也知道会发生什么吧」

「…………好的」

绮兹梅尔吃力地挤出这两个字后，突然又提高了声音，

「如此重任，我们就郑重地接受了」

我和亚丝娜也只能低头表示接受。尤菲里斯子爵松放心似的呼出一口气，然后朝着身后的拉维克喊了一声：

「连着两天在隆冬时节野营，就算是你也会很辛苦吧。我会想个办法掩饰你的身份，今晚你就在城里泡个澡养养精神吧」

「虽然是个很有魅力的提议……」

拉维克突然露出一丝微笑，轻轻摇了摇头，

「但还是算了吧，不然我的决心可能会变钝的。不用担心，和满是霉味的地下牢房相比，这湖畔简直像是天界一样」

「……原来如此。当我从长年幽闭的昏暗房间里走出来的时候，也是这么想的」

尤菲里斯子爵同样嘴角放松地回答着，然后又看向了我们，

「我要回城了。你们打算怎么办？」

「当然，我们会护送您的」

绮兹梅尔立刻回答道。确实，驯服凯尔派的原因本来也有一部分是为了护卫子爵，实在是没理由让他独自回去。虽然我非常想留下来向拉维克询问事情的缘由，但就算问了，我也不觉得他会老实地告诉我。

我强忍着涌上喉头的不适感，正打算让阿哞站起来的时候——

「拉维克先生！」

亚丝娜用几乎要喊破喉咙的音量叫住了他。她接下来的提问更是完全出乎了我的意料，

「您打算怎么从这里回到天柱之塔呢？就算拉维克先生您再怎么厉害，游过湖泊和河流也太过危险了」

确实如亚丝娜所说。连接尤菲尔湖和迷宫塔的河流里，会出现第四层最强的野外怪物。虽然拉维克从迷宫塔下来的时候已经充分展示了他的强大，但就算是他，在水中遭遇巨大鲶鱼和巨大鳌虾袭击的话，也不可能用剑技一下子全部解决掉。

然而拉维克瞥了一眼迷宫塔所在的西南方，就面无表情地断言道：

「翻过那座悬崖就能到达天柱之塔。嘛，爬上去应该是不成问题吧」

「欸…………」

在亚丝娜一脸惊愕的同时，我也把视线转了过去。

在环绕尤菲尔湖的阔叶林深处，矗立着一座黑黢黢的断崖。虽说高度顶多也就五六十米，但崖壁表面完全没有可以借力的横向裂缝，并且坚硬到连钢铁岩钉都无法固定。也就是说，这就是RPG游戏中常见的《无法翻越的墙壁》，但拉维克似乎打算攀爬上去。

不过仔细回想一下，拉维克从哈林树宫越狱的时候，曾在近乎垂直的外壁上完美地展现了堪比攀岩选手的垂悬下降技术。虽然很难想象骑士会进行登山训练，但说不定他真的有能爬上去的实力。

「……请千万不要做太勉强的事情呐」

对于亚丝娜的话，拉维克应了一声「唔姆」，然后又看向我和绮兹梅尔，深深地低下了头：

「真心感谢你们能把列休连带来。要是在塔上见不到你们的话，那我就只能游过湖爬上城堡的外墙、撬开窗户锁偷偷溜进那家伙的房间里了」

「千万别」

尤菲里斯子爵用从心底里感到厌恶的表情回应道，然后稍微犹豫了一下后，向拉维克问道，

「……在和我决斗前，你不想先见见兰德伦吗」

「我可没脸见他。你呢」

「我就有脸见他吗？」

对话在这里就结束了。子爵用眼神示意我后，我连忙让阿哞摆出坐姿，帮亚丝娜和绮兹梅尔上马。我想拉维克大概也是第一次见到听从人类指令的凯尔派吧，但他只是饶有兴趣地摩挲着下巴上的胡子。

尤菲里斯子爵大步地朝着湖边走去。我也纵身一跃，跳到阿哞的脖颈根部，让它站起身来。

当阿哞自行追赶子爵的时候，我回头望去，骑士已经开始往森林里走去了。树丛只发出沙沙一声，高大的身影便融入黑暗中消失不见了。

精灵族在干燥贫瘠的土地上会逐渐失去生命力，但在绿意盎然的森林中却会焕发惊人活力。对我而言只是寒冷的严冬森林，而对于拉维克而言，说不定还真没有逞强，完全就是天国般的地方。

即使如此，我还是默默祈祷他能够平安无事，然后将身体转向阿哞前进的方向。

突然，背后的亚丝娜用几不可闻的声音嘟囔道「怎么办……」，她大概是觉得让拉维克和子爵碰面……不，还要往前一些，她大概是觉得在哈林树宫里帮助拉维克越狱，所以才导致了两人的决斗，因此而感到自责吧。但要我说的话，谁都不可能预料到这样的发展。

我依旧面朝前方，用子爵听不到的音量轻声说道：

「到了关键时刻，我会出手阻止最坏的结果的」

我的声音压得很低，还以为亚丝娜没有听到，但几秒钟后，同样细微的回应在我的左耳旁响起：

「到时候，我也会帮忙的」

「…………」

要是贸然介入身为最强等级NPC的拉维克和尤菲里斯子爵之间的决斗，十分有可能会受到重创吧。虽然我想说「交给我就好」，但亚丝娜的决心也很坚定吧。我默默点了点头，暂时结束了对话。

我们沿着原路穿过湖泊、抵达了尤菲尔城后方的沙滩，先帮绮兹梅尔下了马。之后我和亚丝娜得还去取回停泊在副本边界的蒂涅尔号……我在这时才突然意识到。

「啊……这家伙该怎么办……？」

我一边抚摸着阿哞的脖颈，一边自言自语，子爵转过身来说道：

「据我观察，这只凯尔派似乎并不抗拒使役之术。就算让它回到湖中，只要桐人你呼唤的话，它应该还会出现的」

「这……这样啊」

关于使役之术，我仍然有很多不明白的地方，但我之前在科尔罗伊家的厩舍里救出来的风暴杂色狼，在使役状态解除、光标变回红色之后也没有攻击我，而是不知跑到了何处。如果使役并不仅是单纯的状态变化，还存在着隐藏参数之类的东西的话，那么即使和我分开也能维持一天左右的使役状态吧。

「那么，稍后再见」

我向子爵鞠躬致意，又看了看绮兹梅尔，随后让阿哞转过身去。我们再次借助城堡的阴影移动到湖泊的北面，再沿着副本区域的边界顺时针绕圈，一直跑到了最南端。虽然我确信船应该不会消失，但当我看到出现在前方的蒂涅尔号时，我还是不由得松了口气。

身后也传来了「太好了……」的喃喃声，我差点就要回一句「我就说没事吧」了，但又觉得没必要，便默默地让阿哞减速。

我跟在亚丝娜后面，跳到蒂涅尔号上，然后抬头看向阿哞。它那泛着淡蓝色光芒的眼睛里，依旧看不出任何感情。

「……呃……辛苦了。还要吃蟹爪吗？」

我姑且试着问了一句，凯尔派「哼」了一声作为回答。

当蒂涅尔号缓缓驶入尤菲尔城的大栈桥时，时间刚过晚上九点半没多久。

出发的时候是八点，这样算来大约花了一个半小时。虽然和对哨兵说的「稍微去看看夜景」没多大出入，但万一被怀疑了该怎么回答呢……我一边这么想着，一边把凤尾舟系在系船柱上。随后带着一副若无其事的表情走近正门，说了声「我们回来了」，哨兵只是轻轻点了点头。

从右侧的便门穿过入口大厅，刚一踏入主馆一楼的大厅，我就忍不住高举双手大大地伸了个懒腰。拉维克的「让我在没有护卫的情况下将尤菲里斯子爵带到湖边」的委托好歹是完成了，可现在又出现了一个难度更高的任务，那就是要妥善地结束两人的决斗。

最理想的解决办法当然是阻止决斗本身，但我完全不觉得能通过言语来说服他们。退而求其次的话，那就是无论如何都要避免他们中的某一人或者双双丧命的这种最坏结局。为此，就得在决斗照常进行的同时，看准致命一击的时机，施展巧妙的手段来进行干预……

「回来了啊」

听到这个声音，我把仰望着天花板的脸转了回来。只见全副武装的绮兹梅尔快步穿过空无一人的大厅走了过来。

「嗯，绮兹梅尔你也辛苦了」

亚丝娜慰劳过后，绮兹梅尔也微微一笑回应道「你们也辛苦了啊」，但很快就神情一肃，低声说道：

「阁下在等你们」

「……嗯」

亚丝娜也紧张地点了点头。如果只是单纯慰问的话，那刚才在沙滩上说就行，特意把我们叫过去肯定是有什么重要的事要谈……这点就连我都明白。

绮兹梅尔转身走去的方向，不是大厅正前方直通五楼的大楼梯。她穿过右侧的门，沿着走廊往城堡的东侧走去。走了一段距离后又左转，经过了另一处楼梯，但绮兹梅尔也没有上楼梯，而是继续往前走，打开了走廊尽头的一扇小门。

这扇门似乎很少有人使用，嘎吱……门发出有些刺耳的声音打开了，在门后面是一个铺着黑色石板的中庭。或许是因为这里白天也照不到阳光，中庭各处还残留着积雪。近乎正方形的中庭被蔷薇树丛分割成了迷宫状，中央耸立着一颗如长枪般尖锐的针叶树。

月光被高耸的屋顶所遮挡，只有建筑的窗户里透出来的光、以及为数不多的几盏户外灯勉强地照着这个迷宫。绮兹梅尔一脚跨进树丛的缝隙，用毫不犹豫的步伐在宽度不到一米的小径上前行。

我们在开满了稀疏黑色小花的蔷薇回廊当中，不停左转右转地走了两分钟，再穿过前方出现的一看就是出口形状的拱门后，才终于来到了针叶树的根部。

树东西南北四个方向上各摆着一张背靠着树的青铜长椅，其中一张——朝北的长椅上坐着尤菲里斯子爵。他似乎沉浸在思绪当中，即使我们走近，他也纹丝不动。

「……阁下」

绮兹梅尔轻声呼唤过后，子爵眨了眨独眼，然后抬起了头。即使看到了我和亚丝娜，独眼中摇曳着的光芒也久久没有消散，但过了一会之后，他的声音还是和往常一样沉稳：

「桐人、亚丝娜。给你们添麻烦了啊……关于这次行动的褒赏，稍后我会在办公室给你们，但在那之前，能否稍微陪我稍微聊聊往事呢」

「不、不，我们也不是为了褒赏才做的……而且，拜托我们的是拉维克先生，不用子爵大人您来给报酬」

我慌张地回答之后，亚丝娜也连连点头。然而子爵却嘴角上扬，微微摇了摇头：

「话可不能这么说哦。反正拉维克肯定连一柯尔的报酬都没给你们吧？」

「嘛……嘛，虽然是这样啦……但这次的事情，本来就是为了报答拉维克先生之前对我们的帮助……」

「如果说所谓的「帮助」指的是协助你们从哈林树宫中逃脱出来的话，那可谈不上什么人情往来哦。要是没有你们相助，拉维克自己也是绝对无法从那个被称为《永恒牢狱》的地方逃出来吧」

——咕呃。

我拼命地把差点发出来的声音咽了下去。一直以来，我们都是以尤菲尔城还不知道我们越狱的事为前提而行动的，但子爵看起来早就洞察一切了。

不光是我，就连亚丝娜和绮兹梅尔也都愣住了。子爵一拍手，几十名卫兵就从周围的迷宫中冲了出来——我虽然想象出了这样的展开，不过当然没发生这种事情。

「你们三个，别露出这样的表情啊」

子爵微笑着说完这句话后，又用更加温和的声音和表情继续说道，

「这一切都只是我的想象，而且我也不会仅凭想象就呼叫银骑士的哦。在尤菲尔城的逗留期间，你们的安全由我来保证」

「银骑士……？」

听到这个之前没听过的名称，我歪了歪头，绮兹梅尔在这时小声地给我解释道：

「是神官团直属的骑士们。正式名称是木莲（モクレン）骑士团，但因为他们都穿着白银铠甲，所以被称为银骑士。明明从来没有实战过，却还吹嘘自己能教导白檀、槐树、枸橘三大骑士团，都是些傲慢的家伙」〔译：木莲，拉丁学名Manglietia fordiana，木兰科木莲属植物〕

「从我的立场上来说，就当没听到刚才的那番话吧」

听到子爵的话后，绮兹梅尔低下头说了句「我失言了」。子爵像是要强调自己并非真的在责怪她一样，稍微抬起右手，然后端正了坐姿说道：

「总之，你们就收下奖赏吧。不过，把你们叫到这里来可不是为了说这件事。既然我委托你们做决斗的见证人，那我认为就有义务把所有情况都向你们说明一下」

「…………」

我没法立刻回应，所以只能闭上了嘴。我一直都很想知道尤菲里斯子爵和原骑士团团长拉维克之间的因缘，但真到了要听的时候，我又觉得自己是不是不该如此深入地打听。

别太代入进去了啊，这不过是NPC剧情而已……虽然我这么告诫自己，但并没有什么效果，不过好歹还是压制住了踌躇，回答道：

「那……那就洗耳恭听了」

子爵点了点头，然后让我们把长椅搬到东边。我心想这种东西应该是位置固定的物体吧，但当我和亚丝娜抬起长椅的两端时，这张青铜长椅很轻松地就离开了地面，我们把它搬到了子爵所坐的北侧长椅的右斜前方。

我和亚丝娜并排坐下，绮兹梅尔则有些拘谨地在子爵旁边坐下。在我们头顶上方伸展着的针叶树的枝叶，在夜风中轻轻摇曳着，飘来了阵阵清新的香气。

我记得这种树叫欧刺柏（juniper），蒂涅尔很喜欢从它的果实中提取的精油，绮兹梅尔曾在我上一次来到这个中庭的时候告诉过我这件事。说不定生活在这个世界中的NPC们——就连那些没有AI化的卫兵和店员们，也都拥有着各自的记忆和故事吧……

正当我陷入这样的思绪时，尤菲里斯子爵的声音把我拉了回来：

「……桐人、亚丝娜。你们见过赛特兰了吧」

我只能点点头，而亚丝娜则用冷静的声音回答道：

「是的，在今天早上刚到达城堡的时候见过。他迎接了我们，还把我们带到了四楼的房间中」

「这样啊。……那么，「我们精灵是如何成长的」，你们也已经知道了吧？」

这个问题则由我来回答：

「大概在二十岁左右之前，成长速度和人类是一样的吧……？」

「正是如此。赛特兰今年十五岁了」

我之前猜测他和我差不多大，看来这个猜测是正确的。不过他的精神年龄肯定比我要成熟得多吧。

但是，为什么要突然说起这个来呢……尤菲里斯子爵大概是察觉到了我的疑惑，开始说起了正题。

——我被凯尔派引诱并骑上它的背时，比现在的赛特兰还要年轻一些……那是我十一岁的时候。

当时的我，作为尤菲尔城的继承人，生活十分地无忧无虑，完全就是个在娇生惯养中长大的任性妄为的小鬼，肯定比桐人十一岁的时候要愚蠢得多吧。父母和侍从都反复告诫过我，在湖边看到凯尔派时绝对不能靠近，可我却觉得自己是特别的……一心认为自己能够驯服这匹美丽的马。

——载着我的凯尔派，轻盈地在飘荡着雾气的湖面上疾驰……沉浸在其中的我，丝毫没有察觉到自己正渐渐远离城堡。直到本应在脚下的水面浸湿了我的鞋子，我才意识到凯尔派既不是把我当作朋友、也不是当作主人，而是当作猎物……但为时已晚，水马已经深深地潜入了湖中。

——被拖入水中的我，拼命地想要浮出水面。我本来很擅长游泳，可不知为何，当时无论我怎么划水都使不上力，呼吸也渐渐地困难起来……我在恐慌中回头时，看见幽暗的湖水深处，有两只发着青白色光芒的眼睛正朝着我靠近。

——啊啊，我马上就会被凯尔派吃掉了吧……就在我要放弃的时候，有谁从背后抱住我开始游了起来。即使现在回想起来，游动的速度之快也实在是难以相信……我甚至看到了自己超过了一群鳟鱼。不可思议的是，呼吸也不再困难了，我只是任由着自己的身体随着水流飘动……等我回过神来，已经躺在原来的沙滩上了。

——起初，我以为这一切都只是一场梦。然而我全身都湿漉漉的、头发上还缠绕着水草……我呆呆地坐起身来，回头一看，他正坐在湖岸线旁边。

「……他？」

我不禁脱口而出是有原因的。

刚才在专注地听尤菲里斯子爵讲述往事的同时，我也想起了绮兹梅尔在第六层的塔尔法湖时告诉我们的事情：

「子爵的魔法靴中编织进了水灵的头发」

「据说在很久以前，子爵曾与一位水灵少女有过一段因缘」

将这些信息与刚才听到的故事连在一块，我便先入为主地推测

救下子爵的应该就是那位水灵少女。按绮兹梅尔的说法，女性水灵才被称作薇丽（VIlli）……反过来说，薇丽似乎只有女性。然而，子爵所用的人称代词不是《她》，而是《他》，所以我才不自觉地有了反应。

幸运的是，子爵的心情看起来似乎并没有变差，他点了点头，继续讲了下去：

「嗯。从凯尔派手中救了我的，是一个看起来和我年龄相仿的少年。然而，他既不是人类也不是精灵。而是住在尤菲尔湖的水灵」

——虽说我也从父母那里听说过湖里住着水灵，但和凯尔派一样，我从未当真。然而，眼前少年的皮肤泛着青白色，长长的头发是比湖水还要鲜艳的深蓝色，双腿也都被闪耀着银色光芒的鳞片所覆盖。我战战兢兢地问他「你是水灵吗」，少年点点头后说道「可真是个敢骑在凯尔派身上的蠢货。要是我（僕）不在的话，你现在可就在那家伙的肚子里了哦」……

——除了父亲之外，还从未有人和我如此随意地说话。所以我一时冲动，反驳道「我又没求你救我，就算我一个人也能游着逃出来」。少年随后就挑衅地说「那就来比赛吧，看谁能先游到湖对岸怎么样」。骑虎难下的我脱掉湿透的衣服，接受了游泳比赛的挑战，可他转瞬间就消失地无影无踪了……当我放弃并折返时，他早已回到了沙滩上，看着四肢着地气喘吁吁的我，他放声大笑起来。我更加生气了，只穿着内衣就跑回了城堡，结果母亲发现后狠狠地骂了我一顿。我泡在浴池里温暖着身体，想着大概再也见不到那个水灵少年了……但当我第二天傍晚去北边的沙滩时，他又出现了。第三天也是、第四天也是。

——他叫阿尔马克（アルマルク），一开始他只是不停地嘲笑我，但没过多久，他就开始给我带在湖岸森林里采摘的稀罕水果，还有在湖底找到的漂亮贝壳之类的东西。作为回礼，我也会把在厨房偷藏的点心、或是在庭院里捡到的旧硬币送给他，就这样，我们渐渐变得亲密起来……也因为城堡里没有和我年龄相仿的孩子，不知不觉间，我们已经到了互称「马克」和「泽德」的关系了。

——第二年，我进入了王都的士官学校，但因为休息日我会回到尤菲尔城，所以和马克的来往也没有中断。水灵属于精灵，当然不会去学校上学，所以马克总是饶有兴趣地听我讲王都和学校里的事情。而另一方面，只要是与水相连的地方他都可以去，他也会给我讲许多关于我不能靠近的人族城镇和村庄……甚至还有森林精灵堡垒的故事。

——这样的日子持续了好几年……我十六岁那年，在王城举行的约鲁宴会上，我被介绍给了某个伯爵家的千金。当时我们双方的父母也都在场，我也是在那时才第一次知道，我和她从出生起就已经被定下了婚约。

——现在回想起来，那位小姐真是位我高攀不起的淑女啊……但当时我只是感到十分困惑。宴会结束，我回到城堡之后，那种心里堵得慌的感觉也一直挥之不去……我明白，娶她为妻、在这座城堡里共同生活、生儿育女并继承家业才是我应尽的责任，但我怎么都无法将其视为我所期望的未来。

——那天晚上，我偷偷溜出了城堡。当我坐在沙滩上时，马克像往常一样出现了，我们一边吃着无花果派一边聊天。我和他讲了在宴会上谒见女王陛下的事、水槽里游着一种长着鸟翼的鱼的事……但是，关于未婚妻的事我却怎么也说不出口。就在我思考这到底是为什么的时候，我突然意识到了，我所期望的，是想要这样的时光能一直持续下去。我在学校里交了很多朋友，那位小姐也完全无可挑剔，但我真正想见的人、每次见面都会让我心动的人，只有马克……

——然而，当时的我还不明白这背后的原因，我给这份感情命名、并接受它，已经又过了一年的时候。我……

说到这，尤菲里斯子爵沉默了片刻，像是咬紧了牙关地继续说道：

「我、爱上了身为同性、且是不同种族的阿尔马克」〔译：关于这部分的看法，详见译者后记〕

我不知道该说什么，只能用右手紧紧地攥住了大衣。亚丝娜和绮兹梅尔也都没有开口说话。

子爵微微看了一眼地面——不，是看了一眼自己脚上穿着的靴子，然后继续用比寒夜还要沉冷的语气独白道：

「在第二年的约鲁宴会的前一天，我向父母坦白了。「我不会和伯爵家的千金结婚。因为我无法对着圣大树立下誓言，保证用我的一生去爱她……」当然，父母十分地震惊和慌乱，不停地质问我原因。但我无法回答……「我打算和住在尤菲尔湖的水灵年轻人共度一生」，我可不能这么说吧」

我一边听着，一边反复咀嚼着一个注定无解的疑问。

子爵所讲述的这些事情，是在这个世界实际——也就是说，是正式运营之前就在SAO服务器里实际发生过的吗？

又或者，这一切都只不过是在正式运营的那一瞬间赋予子爵的、名为记忆的虚构之物吗？

如果是后者的话，为每一个在各阶层存在的高度AI化NPC设定详细的过往经历、并且还要确保不产生矛盾，脚本家的工作量一定十分巨大吧，但我却无法毫无保留地对此表示赞赏。如果不仅仅是尤菲里斯子爵，还有背负着父亲的罪过的米娅〔译：SAOP6中出现的角色〕、险些作为孤儿饿死的奇欧、以及失去了最心爱的妹妹蒂涅尔的绮兹梅尔他们，都只是为了剧情精彩才被赋予了痛苦过往的话……那在我看来，这实在是太过残酷了。亚丝娜想必也是这么认为的吧。

我看了一眼亚丝娜，发现她的手放在裙摆上、紧紧地攥成了拳头，随后我再次看向了子爵。

「……父母用尽了各种办法来让我回心转意」

仿佛是在等我驱散杂念一样，子爵又开始说了起来，

「与阶级更高的伯爵家解除婚约固然是极为失礼的事情，但更让父母从心底里感到忧虑和恐惧的是、尤菲里斯家的爵位会在我这代断绝。因为这意味着对两个精灵族来说都是重大禁忌的《时间凝滞》」

「时间……凝滞？」

亚丝娜小声地重复了一遍这个陌生的词语。

我看向子爵身旁挺直了背的绮兹梅尔。在这位的骑士的双眼中，似乎隐隐地透露出了一丝恐惧，这大概不是我的错觉。

「刚才说过「精灵在二十岁左右之前，成长速度和人类是一样的」吧」

子爵的话让我和亚丝娜同时点了点头。

「那么，精灵在二十岁之后是如何变老的呢。精灵们常说《如同树苗长成大树》《如同雨滴汇成江河》之类的话。不管是树苗也好、雨滴也罢，如果被封闭在容器当中，就无法再继续生长。只有完成赋予我们的使命、不断地积累生存的证明，我们才能迎来《时光流转》……也就是老去」

「迎来……老去？」

这次则是我鹦鹉学舌地又嘟囔了一遍。虽然每个字我都能理解，但脑海中却没有具体的印象。

「呃，「不完成使命就不会变老」……听起来像是这样……」

「正是如此。实例就在二位的眼前哦」

尤菲里斯子爵微笑地说出来的这句话，让我不禁目瞪口呆地看向了他。

我这时才想起来两周前造访这座城堡的时候，绮兹梅尔说过的话。她当时确实说了《子爵即使在黑暗精灵中也是活得很长的精灵之一》。那时我只是觉得「因为是精灵啦，所以无论年龄多大都显得很年轻」，但现在我才意识到，我也见过《精灵的老人》。隐居在第六层加雷城的贤者布弗鲁姆——他留着长长的白胡须，消瘦的脸上也刻着深深的皱纹，他的外貌就证明了精灵也是会正常变老的。

「……您说的「使命」，是类似于什么特别的仪式吗……？」

我战战兢兢地问道，子爵面带笑容摇了摇头：

「不，是每个精……不只是精灵，是矮人和人类也都在做的、再平常不过的事情。比如生儿育女、继承家业；又或者磨练锻造、陶艺的技术成为名匠；修炼武艺成为剑豪；钻研学问成为贤者。通过不断重复这样的活动，我们的时光才会流转，终有一天会回到圣大树的身边」

「…………」

即使听到这里，我还是没能完全理解，因此只能在脑海中拼命地整理着这些信息。

也就是说精灵是通过养育孩子或者努力工作等社会责任来逐渐变老，如果什么都不做就会一直保持年轻——是这个意思吗。不过，究竟是以什么样的标准来确定衰老速度的呢。是孩子长大一岁自己也会变老一岁吗？如果是这样，那假设有十个孩子的话，岂不是转眼间就……不，因为是精灵所以没关系吗……？

就在我思绪万千的时候，亚丝娜在我耳边轻声说道：

「说不定是类似于「立场会影响外貌」的感觉」

「立场……？是说有了孩子就会看起来像父母，有了孙辈就会看起来像爷爷奶奶吗？」

我用余光看着轻轻点头的亚丝娜，嘴里嘟囔着「原来如此」。精灵的老化系统也许并不像我想象得那么严谨，大概像是当获得《父母》《爷爷奶奶》《店主》《队长》之类的属性时，身体上就会变老一些，就是这么比较粗略的机制吧。

但这么一来，反过来说的话——

「那个……子爵大人」

我把脸转向左边，说出了任何人听到这里都会产生的疑问，

「听了您刚才的话，想要永葆青春似乎很容易实现啊……」

就像沃尔普塔的巴丹·科尔罗伊，虽然同为法尔哈利的后裔，但他无法接受只有自己独自衰老，甚至还想要杀死妮露妮尔。对他来说，如果能永葆青春，那他肯定就会毫不犹豫地选择不生孩子不工作的无为人生。

此外，第六层主街区斯塔奇翁的原领主 派萨格鲁斯，他似乎是靠着楼层BOSS——据说原本是古代魔法兵器——的一部分，也就是正中央的黄金立方体来维持长寿。因为这股力量泄漏，导致整个城镇都逐渐布满了智力游戏，即使居民苦不堪言，直到被弟子塞隆杀死之前，他也都没有放弃那个立方体。

尤菲里斯子爵听了我的话，微微扬起右边的眉毛，转而向我问道：

「你也希望那样吗，桐人？」

「欸……不，我还只是个小鬼，没想那么多……」

「但如果是你的话，是能够实现那个愿望的哦。只要放弃变回人类，继续作为夜之住民生活下去就好了」

「啊，是、是这样啊」

我虽然点了点头，但我知道这实际上是不可能实现的。就算在这个世界里的我不会变老，可在现实世界里戴着NerveGear的我却不会如此。除非NerveGear搭载了超越目前人类科技的技术，让这个世界的一天只相当于现实世界一分钟的话，否则我是不可能像妮露妮尔那样活上几百年的。而且，就算有可能——

「……但我果然还是想变回人类。就算我能永远地活下去，要是亚丝娜会死的话也就没意义了」

我刚说出这话——

「欸!? 哈!? 什!? 」

我身旁的亚丝娜发出了前所未有的惊叫声，我吓了一跳，朝旁边看去：

「欸？咋、咋了？」

我还没来得及反问，亚丝娜的脸就涨得通红，对我喊道：

「才不是「咋了」吧！你、你突然说些什么啊！」

「说什么……所以说我要永远……」

我呆呆地说到这里才终于反应过来。我刚才说出口的台词从某种角度上也许会被解读成「我想和亚丝娜永远在一起」。

「不、不是，我不是那个意思啦……只是从搭档的意义上……」

糟了，应该在《搭档》前加上《暂时攻略》的前缀才对——当我意识到这点的时候，亚丝娜的手肘已经准确地命中了我的右臂。

——她到底是怎么每次都能把力度控制在刚好不造成伤害的程度的呢。

我一边想着这种事情，一边放弃了纠正这位临时攻略搭档的误解，转身面向黑暗精灵们。绮兹梅尔一如既往地露出了无奈的表情，尤菲里斯子爵也面带微笑，看起来并没有生气。

「对、对不起，打扰到大家了」

听到我的谢罪，子爵的笑容又加深了一些：

「没关系。要好好地珍惜那份心意啊，桐人」

「啊……好、好的……」

我总觉得子爵也误会了什么，但现在也只能这么回答了。

子爵点了点头，随后表情严肃了起来：

「在遥远的过去，我们琉苏拉的子民中……以及卡雷斯·欧的子民当中，都曾出现过追求永恒青春的人」

马上就要讲重要的事了——预感到这个的我竖起了耳朵。身旁的亚丝娜也通过深呼吸来平复稍显急促的喘息。

「他们在提升魔力和剑术的同时，还在探寻着保持青春的方法。很多人都嘲笑他们在干些不可能的事。因为就算没有子嗣，只要作为骑士或者术士的位阶上升，衰老就是无法避免的。在屈辱中苟活或在荣光中逝去……这才是圣大树的旨意，除了他们之外的所有人都是这么想的，连巫女大人也不例外」

听到这里，我终于意识到子爵讲述的《遥远的过去》，是《大地切断》——也就是浮游城艾恩葛朗特诞生之前的故事。虽然具体年代不明，但今年按黑暗精灵的历法是2498年，所以就算是五百年或是一千年前发生的事也不奇怪。

「但……还是存在漏洞吧？」

听得入神的我忍不住插嘴问道，子爵缓缓点了点头：

「没错，有一种极为禁忌的方法。——我刚才说过「只要位阶上升」，而所谓的「位阶」，在获得广泛的敬意后就会自然地上升。「既然这样，那如果用恐惧来掩盖敬意，位阶不就不会上升了吗」。如此考虑的他们，引发了精灵两族历史上最严重的亵渎事件」

「……难道说」

在亚丝娜自言自语的同时，我也想起了曾经从绮兹梅尔曾讲述的传说。

「他们对圣大树……？」

就在我低声说出这句话的同时，我看到绮兹梅尔似乎在念着祈祷的话语。

子爵再次点了点头，继续说了下去：

「正是如此。即使拒绝变老，也依然无法避免武器所造成的伤害。于是，他们想要亲身验证一下古老传说的真实性——「巫女大人将树皮浸泡在圣大树树汁里数年后酿成了《灵酒》，初代琉苏拉王饮用了灵酒之后获得了刀枪不入的肉体」。他们爬上《禁域之壁（禁域の壁）》，潜入了巫女大人所在的《晓之宫（暁の宮）》，砍伐了黑之圣大树的分枝、剥下了树皮。这一暴行让所有国民恐惧不已，他们因此作为失去了圣大树恩宠的《堕落之精灵》、获得了永不衰老的诅咒」

「…………」

至今所听到的零散信息在我的脑海中瞬间串联了起来，我一时之间有些恍惚。

恐怕作为触发衰老板机的《位阶》，用游戏术语来说的话，应该不是数值类的等级，而是通过累计名誉值提升的称号系统。按照刚才的推测，如果获得了《父母》《店长》之类的属性，就会因此从周围人那里获得名誉值、也就是敬意值，从而提升位阶……我认为应该是这样的系统。这样的话，一般家庭的父母和大型商店的店长所获得的敬意值可能会相差过大，但也许是调整成了「从家人那获得的敬意值比从其他人那获得的更多」吧。

关键在于精灵似乎都认为年老而死是上天的恩赐和荣誉。确实，封测时我在第九层的王城里见到的那些看上去很有威严的黑暗精灵，虽然不像布弗鲁姆老人那么老，但也很能让人感觉到他们的年龄。然而，站在王国顶端的女王陛下，虽然是最长寿的黑暗精灵，却有着非常年轻的外表。她应该聚集了比任何人都多的敬意值、达到了最高位阶却没有完全衰老，而且大家还都对她怀着深深的崇敬之情，这是为什么呢……

虽然我还有很多想要确认的事情，但还没等我决定从何问起，亚丝娜就先开口了：

「那个……我记得只要吃了圣大树的果实就能获得永恒的生命吧？既然都辛辛苦苦地潜入神殿了，为什么还只弄下树汁和树皮，干脆拿到果实再吃下去不就……我是这么想的……」

「嚯……我还以为知道《小蛇与圣大树果实》传说的人已经不多了呢，你是在哪听说的？」

回答这个问题的不是亚丝娜，而是绮兹梅尔：

「阁下，是我告诉他们两人的……难道有什么不妥吗？」

「怎么会呢，完全没问题。我只是在感叹你们居然这么了解」

「因为我以前经常和妹妹读古老传说的绘本……」

知道蒂涅尔已经去世的子爵，向绮兹梅尔投去了慰藉的视线后继续说道：

「那么你们应该也知道，「吃了圣大树果实的小蛇虽然获得了永恒的生命，但却因毒咒变成了邪恶的龙」吧。那些堕落精灵们大概也不希望承受「入口之物皆为剧毒」的诅咒吧，而且据说圣大树数十年才结一个果实。我也不太清楚详细情况，似乎和巫女大人的继任仪式有什么关系……——总之，堕落精灵因为伤害圣大树而被王国放逐了，但这也是他们所期望的。他们的蔑称《纽西安（ネウシアン）》不仅有「既不是黑暗精灵也不是森林精灵的异类」的意思，也有着「无为者」的意思」

子爵自言自语般地说完之后，他的嘴角一瞬间似乎闪过了一丝自嘲的神色，但很快就消失了。

纽西安这个词似乎还有「浪费粮食之人「」游手好闲之人「之类的含义。堕落精灵们应该也是为了某种目的——尽管是歪门邪道——而行动的，所以被称呼「游手好闲之人」肯定会很生气吧。就算我能再见到凯萨拉，我也不会对她说出「纽西安」这个词……我想到这里的时候，脑海中又浮现出了一个新的疑问：

「子爵大人，我们在第六层和一个叫《剥伐的凯萨拉》的堕落精灵剑士战斗过，难道她就是那个剥下圣大树树皮、砍下分枝的人吗？「剥伐」的别名是从这里……？」

「…………」

子爵微微瞪大了眼睛，沉默了一会后微微摇了摇头，

「「剥伐」的别名确实是源自那个传说，但不清楚她是不是当事人。如果她真的伤害了圣大树的话，那她就已经活了一千多年了，而且传承别名也并不奇怪。只是……」

子爵停顿了一下，压低声音继续说道，

「堕落精灵将军诺尔扎确实是讨伐了吃了圣大树果实而中了毒咒的小蛇——也就是邪龙休马尔格亚的人。所以至少他是在《大地切断》之前就活着的真正长寿者。和剥伐的凯萨拉战斗后还能活下来固然值得骄傲，但绝对不要和诺尔扎战斗啊」

「好……好的」

我回答之后，身旁的亚丝娜也默默地点了点头。

我虽然完全没打算和那个彩色光标几乎算是黑色的诺尔扎战斗，但还是有再次和凯萨拉战斗的可能性。如果被夺走的秘钥还在她手里，那很难不战斗就从她那里拿回来秘钥。

如果是这样的话，就算被说是卑鄙，也得为了获胜而用出能用的一切手段……比如在高处连续发射哀伤夜想曲的光之刃之类的……我正想着这些没什么意义的事时，亚丝娜又开口道：

「……我们虽然没能和凯萨拉战斗，但袭击第六层加雷城的堕落精灵士兵还是可以被剑和枪伤到的。也就是说，他们没有做出《灵酒》来……可以这样认为吗？」

「应该……是这样吧」

子爵点了点头，但看起来并不是百分百地确定，他的表情中略带思考，继续说了下去，

「我也没听说过堕落精灵能用肉体弹开刀枪的事情。但是……如果抢夺圣大树树皮和树汁的传说是真的，那很难认为抢走的那些东西没有任何效果。也许是成品的效果不完全、也有可能是制作出了不同效果的东西……嘛，现在能知道答案的人，恐怕只有诺尔扎将军了吧」

「……他们为什么把秘钥……」

轻声说出这话的，是坐在子爵左边的绮兹梅尔。但她很快就轻轻的摇了摇头，抬起了一直低垂着的头，

「不，失礼了。——阁下，刚才听您讲述的时候，我也有一件觉得很奇怪的事……是关于拉维克大人的事情，如果您不方便回答的话也没关系……」

「是他外貌的事吗？」

子爵这么一问，绮兹梅尔就露出了有些惊讶的表情，然后点了点头：

「是……拉维克大人虽然贵为白檀骑士团团长，却仍有着那般的年轻容貌，这是什么原因呢……现在的槐树和枸橘骑士团的团长，两位都已步入肉桂和榛树之年了……」

——肉桂（ニッケイ）？榛树（ハシバミ）？

我正暗自困惑的时候，亚丝娜在我耳边小声地解释道：

「应该是用艾恩葛朗特的十二个月的名字来比喻年龄哦。我记得肉桂好像是八月、榛树是九月……换算成人类年龄的话，大概是六十岁或七十岁左右吧」

「原来如此……」

这么一说，我也想起了这样的设定，然后继续听子爵的回答。

「这是个理所当然的疑问呐。虽然由我来说明并无不妥……」

子爵深吸一口气，随后把视线投向北方的夜空。像星星一样闪烁着的东西，大概是第五层底部反射的月光吧。时间刚过了晚上十点，不知不觉间，尤菲尔城的灯光已经少了很多。

子爵微微吐出一口白气，然后缓缓地开始讲述：

「……要讲拉维克的事情，得先从我的……我和阿尔马克的故事说起。当时我和父母说「我不能和伯爵家的千金结婚」。桐人和亚丝娜现在也明白我的父母为什么惊慌失措了吧。如果不结婚、不生孩子、又不加入骑士团，只是在城堡里无所事事地生活的话，作为家族继承人的我就会「时间凝滞」……就和堕落精灵一样。这对于琉苏拉贵族来说是最大的耻辱，甚至可能会导致家族的衰败」

「…………」

我根本无法插嘴，只能屏住呼吸听着。

因为我也是桐谷家的长子——虽然是养子，所以要是我在将来宣言「我不结婚」的话，母亲和父亲肯定不会高兴的吧。因此，我也不是不能理解尤菲里斯子爵说的话，但听到这甚至是「有可能导致家族断绝的耻辱」时，我还是不禁感受到了黑暗精灵社会的严酷。

但是，子爵的外貌依然很年轻、尤菲里斯家也还存在，所以他的父母最终应该还是认可了吧……不，这样的话，那赛特兰和其他孩子的母亲又是谁呢，我想到这里的时候——

子爵冷冽的声音打断了我的思绪：

「新年、一月、二月都过去了之后，父母也不再试图说服我。只是，父亲无论是工作时还是吃饭时，总是露出一副失魂落魄的空洞表情。我当时刻意回避了他，而没有更认真地面对他、和他把话说清楚……我后来是有多么地后悔，已经无法用语言来形容了」

向来表情平和的子爵罕见地绷紧了嘴角，但马上又恢复了原样，紧接着，他又用落寞的语调继续往下说道，

「金合欢（Acacia）月到来的时候，城堡的雪和湖面的冰都开始融化了。安息日的那天，我从王都回来，像往常一样早起去了北边的沙滩，等待着阿尔马克。然而，平常不到五分钟就会从湖里出现的马克，过了一个小时、两个小时后也没出现……因为以前也不是没有过这种情况，所以我就回到了城堡。但是，那天傍晚、第二天早上、下一个安息日，马克也都没有露面。然后……一段时间以来都有些不对劲的父亲，有一天突然患上了奇怪的病倒下了」

绮兹梅尔的双肩猛地颤抖了一下。她似乎察觉到了什么，但我还无法预见故事的发展。

「……父亲的皮肤和嘴唇都干裂得很厉害，虽然非常想喝水，但喝下去马上就会吐出来。不管是茶、奶还是酒，都是如此……虽然从王都请来了很厉害的药师、开了很贵重的药，可就算把药溶在水里，他也喝不下去。把药粉含在嘴里，也只会一个劲地咳嗽，父亲眼看着越来越衰弱了。不久后连声音都发不出来了……第二位药师在这时来了，他给父亲诊断后摇着头说，「这个症状简直像是薇丽的诅咒一样」。听到这句话后，我终于全都明白了」

子爵的话尾微微带着一丝战栗，他深深地吸了口气，又慢慢地呼了出来，

「……父母不知什么时候已经查明了我不结婚的原因是阿尔马克。然后趁着我去王都的时候，父亲用某种方法把马克叫到了北边的沙滩……再杀了他。结果，父亲受到了薇丽的诅咒，变得无法喝下任何液体……药师回去之后，我问父亲，他是不是杀死了马克。父亲微弱而明确地点了点头，几天之后，他便去世了」

子爵说出这番话时，声音已经不再颤抖了，但我仍能真切地感受到，那份悲伤至今仍未消散。而且，这还不是悲剧的全部。

「父亲葬礼举行的那天晚上，母亲从大栈桥跳进了尤菲尔湖当中。我当时不在现场，但据跑过去想救她的卫兵说，母亲只在水面上飘了短短几秒，随后就像被什么东西拽下去了一样，立刻沉入了湖底深处。……母亲的遗体一直没有找到。那已经是距今两百七十二年前的事了」〔译：话说NPC和玩家死了之后不就化作碎片消失了吗……哪来的遗体〕

** 第8章

「呐，桐人君」

坐在我对面的亚丝娜突然轻声问道，

「尤菲里斯子爵，是AI……对吧？」

我稍微想了想之后，点头回答：

「我也不是很了解AI的事……不过我认为应该是这样的。在SAO中，有和现实世界中普及的对话型服务AI同水平的NPC，还有我擅自称为《高度AI化NPC》的，像是绮兹梅尔、妮露妮尔、尤菲里斯子爵这样达到AGI（Artificial General Intelligence）水平的NPC」

「AGI、是通用人工智能……吧？是指拥有像人类一样的思考能力和判断能力的AI……但现在还没开发出来吧？」

「至少在2022年11月6日前是没有的。不过，已经有不少企业和研究所都很接近完成AGI了吧，而且开发SAO的可是茅场晶彦啊……他很有可能秘密地完成了AGI，并趁着正式运营的时候实装到了SAO里」

我一提到茅场的名字，亚丝娜就露出了极为厌恶的表情：

「就算那个人是世界上第一个完成AGI的人，他让搭载了AGI的NPC承受那样的痛苦，也是绝对……绝对不能原谅的」

她的这番话，听起来就像是比起「茅场把自己困在不能登出的死亡游戏里」的事，她对尤菲里斯子爵他们所遭受的痛苦要更加愤怒，但我现在也不觉得这是不合常理的了。

「不过……我们肯定也有能为他们做的事哦」

说完这句话后，连我自己都觉得这回应有点苍白无力了，但亚丝娜缓缓地点了两下头，用稍微冷静下来的声音说道：

「……是啊。首先要把秘钥夺回来呢……」

我简短地回答道，然后将杯子里剩下的红茶一饮而尽。

我们所坐的位置，是位于尤菲尔城西侧二楼大食堂最边上的一张桌子旁。用餐时间早就结束了，厨房里一片漆黑，大厅里的大部分灯也都关掉了，光线十分昏暗。不过好在自助餐台尽头的巨大铸铁热水器能无限量供应热水，只要自备茶叶和茶具就能泡茶。当然，准备这些东西的不是我，而是亚丝娜。

我的道具栏中虽然也放着各种各样的储备粮和点心之类的东西，不过因为大约四小时前，我们刚在这把肉和螃蟹吃得饱饱的了，所以实在没胃口再吃东西了。

绮兹梅尔在第六层确实说过「包括薇丽在内的水灵对精灵而言与树灵是同样重要的存在，如果有人杀了薇丽，那么一整个家族都会被诅咒」。

子爵的父亲杀死了年轻的薇丽阿尔马克，结果受到了无法喝水的诅咒而死去。之后，子爵的母亲投湖自尽，大概也是通过牺牲自己的性命来防止薇丽的诅咒降临到儿子身上。也就是说，父亲的凶行和母亲的自尽，都是出于对孩子未来的担忧而做出的决定。这实在是令人唏嘘不已。

而且，尤菲里斯子爵讲到这里的时候，身体就支撑不住了。虽然他本人说没事，但我们再三劝说让他早点休息，好不容易才让他接受了。很遗憾，子爵的故事还没讲到他与原骑士团团长拉维克之间的因缘，但能了解到关于精灵的社会规范与衰老机制就已经帮助很大了。在正式运营中实装的高度AI化NPC，应该有不少居住在第八层的森林精灵王都、以及第九层的黑暗精灵王都当中吧，所以现在比封测时要更注意举止得体才行。如果见到看起来年轻的精灵就随口夸赞「如此年轻就这么厉害啊！」之类的奉承话，而那位精灵其实是因为某种原因陷入了《时间凝滞》状态的话，那后果简直不敢想象。绮兹梅尔曾说过「在精灵族之间，当面询问他人的年龄是非常不礼貌的行为」，我深刻地认识到了这绝非玩笑话，我再次把这句话深深地记在了心里。

「亚丝娜，要再来一杯吗？」

我一边站起身一边问道，似乎沉浸在思绪当中的亚丝娜抬起了头：

「啊……嗯」

我拿起已经空了的茶壶，走到了餐台旁边。

直接放在地板上的热水器是个高约一米半的圆筒状物体，和现实世界的饮水机有点相似。它的下半部分似乎兼作炉子，通过炉门的缝隙能看到像煤炭一样的矿石正在里面烧得通红，以此来加热上半部分的储存的水。

我把茶壶放在圆筒中部安装的水龙头下面，打开颇具古风的阀门，热水就咕嘟咕嘟地流了出来。我等茶壶七分满的时候关上了阀门，回到了桌子旁。

这个世界的茶叶，原则上来说在萃取完成的同时就会溶解消失，可以说是很方便的设定了，因此我从陶制的茶罐里直接往茶壶中倒了适量的茶叶，然后盖上盖子稍作等待。

正当我听着茶叶在热水中翻腾的细微声响时——

「让你们久等了，两位」

说话声伴随着硬鞋跟踩地板的啪嗒啪嗒声传到了我的耳边。

走进大食堂的，是全副武装的绮兹梅尔。她快步穿过大厅，在我和亚丝娜对面坐了下来。

「绮兹梅尔，子爵大人没事吧……？」

亚丝娜问道，骑士微微点了点头回答道：

「看起来只是有点累了。毕竟来回都是靠双腿在不稳定的水面上奔跑啊……」

「这样啊」

亚丝娜放心地吐了一口气，在她旁边的我突然想到了一件事。

我和亚丝娜的肉体——或者说虚拟体其实也会感到疲劳。这个世界当中存在着《疲劳度》的隐藏参数，如果搬运超过力量值的物品、或者以超过敏捷值极限的速度持续奔跑，就会被赋予《疲劳》的负面状态，行动在一段时间内就会受到限制。

所以，以慢跑的速度往返于湖岸的尤菲里斯子爵会感到疲惫也不奇怪，但我觉得疲劳的时间点总有些不对劲。如果NPC的疲劳机制和我们玩家一样的话，那在沙滩的时候就应该进入了疲劳状态才对，可子爵的状态是在中庭的长椅上聊了将近二十分钟之后才变差的。

说不定这不是负面状态的身体疲劳，而是精神上的消耗吧。可是，「AI的精神会感到疲劳」，这种事情真的有可能发生吗……

「茶差不多好了吧？」

听到亚丝娜的声音，我猛地抬起了头。

「啊……啊啊，也是」

我在绮兹梅尔面前准备了一个新杯子，从茶壶里倒上刚泡好的红茶。再给亚丝娜和我的杯子也倒上之后，茶壶正好就空了。

绮兹梅尔道谢过后拿起杯子喝了一口，然后微微瞪大了眼睛，

「真好喝啊……这香味，是妮露妮尔大人的茶吗……？」

「嗯，我请奇欧把妮露大人爱喝的茶给了我们一些」

亚丝娜耸了耸肩微笑道，她什么时候做了这种事……我一边想着这个，一边也把嘴凑到了自己的杯子上。那股类似麝香葡萄的奢华芳香，确实和在大赌场的时候奇欧泡的红茶一模一样，但我总觉得有些美中不足，大概是我没有料理技能的缘故吧。

即便如此，这也是足够好喝的红茶了，我和亚丝娜、绮兹梅尔同时喝完过后，我看了看视野右下角的时间。晚上十点十分。

昨天的这个时候，我们还在沃尔普塔大赌场附属的私人沙滩上，一边穿着泳衣躺在躺椅上一边喝着冰凉的水果宾治呢。因为季节感相差得实在是太大了，不禁让人怀疑「这真的是前一天发生的事吗」，不过系统UI是不会说谎的。

总之，离天亮还有将近八个小时。对于正处于强制昼夜颠倒状态的我们来说，今天的攻略才刚要正式开始呢。

「那么……差不多该出发了吧」

我这么一说，亚丝娜和绮兹梅尔就像「就等着你这句话了」一样站了起来。

虽然这已经是今晚第二次外出了，但或许是因为有绮兹梅尔同行，在正门驻守的哨兵们非但没有感到惊讶，反而主动向我们敬了个礼。

绮兹梅尔一边回以简礼，一边用坚定的声音说道：

「我们要执行任务外出。若天亮前还没回来，请立即禀报子爵阁下」

骑士向齐声回应的哨兵们点了点头，便飒爽地朝着大栈桥走去，我和亚丝娜也一脸严肃地跟了上去。

今晚的主要任务是侦查，所以我在船体较大但不太显眼的解放者号、和船体较小但通体雪白的蒂涅尔号上犹豫了片刻，但最终还是选择了机动性和熟练度更高的爱船。万一遇到紧急情况，用亚尔基洛的薄布把船整个盖起来就好了。

解开系留绳后，我们依次跳上了船。确认亚丝娜和绮兹梅尔都在船上坐好后，我就轻轻地划动了船桨。先以低速前进了大约十米左右，然后用力划桨，蒂涅尔号随即就如滑行般在平静的水面上前进。

望着在蓝黑色水面上摇曳的月光，我不禁想起了很久以前在这座湖上发生的悲剧，但现在必须集中精力完成眼前的任务才行。假如无法夺回秘钥，绮兹梅尔很有可能会被解除近卫骑士的职务、再次被关进监狱当中。如果发生了这种事，那她也不是没有陷入《时间凝滞》的可能性。

也就是说，对于精灵族而言，长期的监禁的刑罚其实是一种既剥夺自由又剥夺正常衰老的双重惩罚。无论如何，我都不能让绮兹梅尔遭受那种事。

我一边坚定着决心，一边把船桨向左划动。蒂涅尔号随即转向了西北方。

这么径直穿过副本区域边界的话，就能到达流入尤菲尔湖的河——似乎是叫乌尔河——的河口。沿着河流逆流而上、穿过位于楼层中央的卡尔特拉湖，再向东北方向前进，就能看到我和亚丝娜与喷火熊巨震地懒战斗过的那片大森林，而我们的目的地就在森林前方。沿着一条不仔细留意就很难发现的细支流一直走下去，能在尽头处找到一个水路迷宫。堕落精灵的隐藏据点就在迷宫深处。

如果在第七层从黑暗精灵回收部队手中抢走《红玉秘钥》的堕落精灵，通过转移装置移动到了第四层的话，那他们的去向也只可能是那个据点了。毕竟才刚过去一天，移动到其他地方的可能性很低，而且被凯萨拉夺走的那四把秘钥，也有很大的概率保管在同一个地方——应该说是我很希望这样。

由于那个据点位于广阔的水路迷宫深处，所以探索起来并不容易。不过好在大约八成的区域都已经探索过了，出现怪物的等级也比现在的我们要低不少，这是我们的优势。

盘踞在据点里的堕落精灵士兵们想必也有这两个优势吧，但我们当然没打算一进去就大开杀戒。毕竟如果潜入行动暴露得过早的话，他们很可能会在我们查明秘钥的具体位置之前就从后门溜走、而且尤菲里斯子爵曾再三警告过我们不要与其交战的诺尔扎将军也有可能还留在那里。

因此，虽然我们会清理一些在据点外面碰到的怪物，但进入据点后就必须要进行完全的隐蔽行动。说实话，我不太擅长这种行动，但我也只能充分利用夜之民的夜视能力努力去做了。

亚丝娜和绮兹梅尔大概也在给自己鼓劲吧，她们俩都没有说话，但背都挺得笔直。我感觉蒂涅尔号的速度也比平时要更快一些。

我们冲破了前方弥漫的浓雾，离开了副本区域，在前方果然出现了河口。从那里沿着乌尔河逆流而上，到达目的地大概需要一个小时左右的路程。

「原则上会直接无视怪物前进哦！」

我向乘客们喊了一声，两人都竖起大拇指表示了解。

就在我准备全力划桨、让蒂涅尔号以最大速度前进的时候——伴随着轻微的音效，视野中央的信件图标亮了起来。看来是收到了好友消息。

「啊……抱歉，稍微等我一下」

我把船桨竖起来让船减速，同时点击图标。发信人是……情报贩子、《鼠》之阿尔戈。

【抱歉打扰了，等等能不能在第八层的主街区碰个面？发生了很不妙的事】

读了两遍这条短文后，我终于才意识到了。我们才刚离开尤菲尔城就收到了消息绝非是偶然。虽然好友消息和即时消息不同，即使对方身处在其他楼层也能发送，但迷宫和副本区域内则处于消息发送范围之外。恐怕阿尔戈从好一阵子前就一直想联系我或亚丝娜了，只是因为我们一直待在尤菲尔城内，所以她才无法发送消息吧。

也就是说，发生了相当紧急的事态……我一边想着，一边迅速敲击虚拟键盘。

【得看情况有多糟了。现在在第四层进行作战】

我花五秒钟打完的消息，阿尔戈用四秒就回复了过来。

【相当糟。DKB和ALS的大半成员都因为和森林精灵的冲突而动弹不得】

「哈啊!? 」

听到我的惊叫声，亚丝娜和绮兹梅尔都露出了疑惑的表情。我示意她们稍等一下，然后继续输入消息。

【有生命危险吗？】

【似乎甩掉追兵躲到了洞窟里，所以暂时没什么大碍。但之后会怎么样就得看林牙的决定了】

【到底干了什么？】

【在森林精灵的王都区域内砍倒了一棵大树】

「蠢……」

我把骂人的话硬生生地咽了回去，回了一句【和同伴商量一下，给我五分钟】就关上了窗口。不知不觉间站起身来的亚丝娜，用按下了倍速播放按钮般的声音接连问道：

「谁发来的!? 出什么事了!? 」

「阿尔戈发来的。似乎出了点麻烦事」

以此为开场白，我接着把消息的内容告诉了她们两人。

刚听完，绮兹梅尔就深深地叹了口气，说出了我没能说出口的话：

「真是干了件蠢事啊……要是被抓住的话，指挥官肯定会被处死，其他人就算能保住性命，也免不了要进监狱啊」

「是啊……那些家伙明明应该也知道「砍伐活着的树木对精灵来说是最大的禁忌」吧……」

我说完后突然想到，他们说不定还真不知道。ALS和DKB虽然在第三层开始了精灵战争战役任务——我记得ALS选择了黑暗精灵，而DKB选择了森林精灵——，但两个公会如此选择的原因其实是神秘PK集团成员之一、穿戴着锁链头巾的摩尔特在暗中用虚假情报诱导的结果。多亏了我、亚丝娜和绮兹梅尔的介入，才勉强避免了两大公会的全面对决，之后他们也都放弃了战役任务，所以他们应该既没去过尤菲尔城、也没去过加雷城。如果他们和精灵的对话只停留在任务交接和报告的程度的话，也不是没可能完全没听说过有关禁忌的事情。

不，就算真的从来没听说过，只要在第八层的主街区认真收集情报的话，也应该知道森林精灵们的脾气有多么暴躁——尤其是在他们的领地内砍树或污染水源、这可是性命攸关的大事，遍地的NPC都会这么警告。至少封测时是这样的。

总之，在这里瞎猜也只是浪费时间罢了。让阿尔戈给我的五分钟只剩下一半了。

「唔～～嗯……」

我快把脑袋想破了，随后给出了自己的想法，

「虽然对林德他们很抱歉，但我们就算现在赶过去也没用啊。绮兹梅尔当然不能进入森林精灵的地盘，我和亚丝娜也因为在尤菲尔湖和森林精灵交战过，很有可能已经有敌对标识……呃，很有可能已经被当作敌人了。要说可能性的话，也就是让攻略集团中的人从现在开始成为森林精灵的协力者，帮他们做各种事情来提升信任度，然后去拜托那些有影响力的大人物，让他们把事情妥善解决了吧……」

「这样的话……得花上多少时间啊」

亚丝娜用有些沙哑的声音低语道。确实，从在第三层的迷雾森林开始战役任务、再逐个完成各层的秘钥回收任务、最后获得尤菲里斯子爵级别的大人物的信任……得花上一周？不，说不定得十天？

阿尔戈也写了「之后得看林德和牙王的决定」，但我完全不认为躲藏在洞窟里的ALS和DKB的成员能坚持十天之久。最糟糕的是，几乎所有的洞窟都被当作了迷宫，所以即时消息和好友消息都无法收到。也就是说，我们没法告诉他们「我们正在推进救援任务，一直躲着就好」。

那阿尔戈到底是怎么了解到情况的？我虽然很在意这点，但现在并不是考虑这个的时候。首先，得决定怎么回复阿尔戈的消息。就算没法提供帮助，至少也得赴约听一下详细情况吧。但如果现在就打算去第八层的话，要么使用第四层主街区洛比亚的转移门；要么爬上迷宫塔使用堕落精灵的转移装置移动到第七层迷宫区，再利用BOSS房间的往返楼梯爬到第八层。不管选哪条路线都相当耗费时间，所以我觉得今晚是别想着去调查堕落精灵的据点了。更糟的是，秘钥很可能在这一天的时间里转移到别的地方去。

还剩一分钟。

我抬起右手，打算问问阿尔戈能不能再等一天。就在这千钧一发的时候——

「桐人、亚丝娜。你们去见阿尔戈吧」

绮兹梅尔用冷静的声音说道。

「欸……那绮兹梅尔你要干什么呢？」

「我就按原计划去侦查堕落精灵的据点。我会查明秘钥在没在那里，要是在的话，至少也要查出藏的具体地点来」

话还没说完，亚丝娜就大声反对：

「不行！我们连敌人有多少都不知道，一个人去太危险了！」

「本来的方针就是尽量避免战斗吧？我不是把你们当作累赘，但如果是隐秘行动的话，有时候我一个人反而更容易突破」

「也有不利的时候吧！」

我看着坚持己见的亚丝娜的侧脸，将我做出的决定告诉她们两人：

「亚丝娜，你和绮兹梅尔一起去吧。我一个人去见阿尔戈就行」

亚丝娜猛地转过头来，她眼中的担忧变成了不同意义的担忧。她担心的不是我会败在怪物手下，而是担心我能否在天亮前回来。

「没事啦，单程用不了一个小时，听完情况后我马上就回来，肯定能在晚上回到城堡的」

我提前保证道，但亚丝娜脸上担忧的表情还是没有消失：

「但是……」

她在这时突然停住了话语，大概是把各种不安都咽了下去吧。然后取而代之说出了实际存在的问题，

「可是，如果分头行动的话，你该怎么移动呢？先回城堡一趟、再开解放者号过去吗？」

「不，这里还算是尤菲尔湖的范围哦」

我笑着说完，把弯曲的拇指和食指放在嘴边，响亮地吹了声口哨。

把手放下之后，我脑子里闪过一个念头，是不是还得叫一下它的名字才可以呢。幸好，船左舷方向的水面没过几秒就翻腾起来，尤菲尔湖之主——凯尔派露出了脑袋。它那湿漉漉的鬃毛、不，背鳍下方的马脸明显是一副不耐烦的表情，不过我还是将其当作错觉，然后转身面向亚丝娜她们：

「我骑着这家伙去迷宫区，亚丝娜你们就继续用蒂涅尔号吧」

「……这孩子可以到湖外面吗？」

对于亚丝娜的提问，阿哞用「呼哼」的鼻息作出了回答。

** 第9章

到达第四层迷宫塔下方的码头后，我从阿哞的背上跳了下来。

操作完道具栏后，我转过身对着站在波涛汹涌的水面上也纹丝不动的水马，小心翼翼地伸出了右手。在我手掌上放着的是、先在尤菲尔城的大食堂里偷拿——不，是外带出来的炸河蟹。阿哞先是闻了闻气味，然后用锋利的前齿叼起来，发出嘎嘣嘎嘣的爽脆咀嚼声吃了起来。

它将我留在窗口界面上剩余的七个炸河蟹也一下子吃光后，「哼」地喷了一下鼻子。我一边祈祷着这是「就再陪你一会儿吧」的意思，一边开口道：

「我会在两……不、三个小时内回来，能在这附近等我一会吗」

听到这个指示，或者说是请求之后，阿哞回了声「布噜」，然后向左转身划入到了水中。目送它离开后，我把一直开着的窗口切换到了信息发送页面，给亚丝娜发了条【已到达迷宫区】。

随后我马上就收到了【这边也马上要到卡尔特拉湖了】的消息，所以我又叮嘱了一句【我认为野外BOSS应该还没刷新，但总之还是别靠近湖中间啊】，等她回复了【OK】后才关闭了窗口。

想必在SAO的开发阶段，开发团队一定考虑过是否要在消息功能里添加表情或者emoji吧……我一边这么想着，一边朝着码头深处跑去。我两步并作一步地跑上之字形的阶梯，快速地确认了一下岩架上的迷宫塔周围没有人后，便踏入了漆黑的入口。

这已经是我第二次——算上下来的话就是第三次进入这座塔了，再加上塔的结构也不是很复杂，所以我打算沿着最短路线全力冲刺过去。或许是因为状态值得到了提升，即使不休息一直奔跑，也没有要进入疲劳状态的迹象，而且强化过的夜视能力也能让我在远处就发现怪物。

要是在封测时也有这种开挂般的吸血鬼力量，第十层的《千蛇城》肯定早就通关了吧……我不禁产生了这种想法，但我肯定会因为不小心晒到太阳而死个十次、不，二十次吧。但在正式运营中，哪怕只是一次不小心就会直接Game Over，果然还是该尽早变回人类啊。

我用舌尖舔了舔已经逐渐习惯的尖牙，然后加快了奔跑的速度。

从第十层开始，我尽可能地避免战斗，只清除了那些无法绕过去的怪物，不知为何，其中大部分都是昨天没遇到的半鱼人型怪物，而且还都是稀有的《半鱼人耕种者（Ichthyoid Cultivators）》。多亏了它们，我得到了十多个珍贵的红薯，但现在可没有烤红薯的余裕。

我比预定时间稍微提前了一会就到达了目的地的十八层，于是我决定休息一分钟，稍微思考了一会。

选择迷宫区路线时，我本来打算用堕落精灵的转移装置直接飞到第七层，但仔细想想的话，其实也可以通过第四层BOSS房间里的往返楼梯上到第五层，然后从主街区卡尔鲁因的转移门移动到第八层。虽然两种方法所需要的时间相差不大，但出现在前者路线上的怪物会稍微强一些，而且还有遇到堕落精灵的风险。

这么看来，还是经过第五层的路线要更合理一些，但原骑士团团长拉维克或许为了和尤菲里斯子爵决斗而已经在第四层BOSS房间里待机了。倒不是说我对他有什么芥蒂——不如说我对他还挺有好感的，但正因如此，我很难甩下一句「我赶时间！」就直接跑过去，但也没时间停下来慢慢聊天。

思来想去，我决定还是按原计划走经过第七层的路线，作出判断后，我再次跑了起来。

我只和突然出现的半鱼人战斗了一次，将其他怪物全都绕了过去，等我来到熟悉的通道时，时间已经是晚上十一点十五分了。从离开尤菲尔城到现在，刚好过去了一个小时。

如果绮兹梅尔和亚丝娜进展顺利的话，应该也差不多快到水下迷宫了。我很想发个消息确认一下，但由于我现在身处迷宫当中，因此发不了消息。

我只能强忍着各种情绪，向她们发送完「别太勉强啊」的脑电波后，正准备朝着通往隐藏房间的狭窄道路走去的瞬间——

从隐藏房间的岔路当中，出现了一个模糊的人影。我条件反射地跳到了右边，贴在了凸出石壁大约十五厘米的柱子后面。

隐蔽状态的图标随即亮起，隐蔽率指示器也显示了出来。数值是72%。对方明明还在二十米开外，可隐蔽率却如此低，大概是因为我躲藏的柱子不够凸出吧。

即使就这么藏着不动，等对方逼近到眼前时，我的隐蔽率也将跌破50%。也就是说，我很有可能会被识破。而且，既然是从通往隐藏房间的岔路出来的，那肯定就是堕落精灵了。虽然一对一战斗的话我并不认为我会落败，但绝对不能变成「被发现→对方逃走→跟丢目标」的情况。虽然不清楚那些家伙是怎么在只有水路的第四层移动的，但要是因为我的缘故让堕落精灵据点的警戒程度上升的话，那亚丝娜和绮兹梅尔也会陷入危险当中。

如果以「不让对方逃走」为最优先事项，那就应该趁着对方还在通道深处的时候先发制人。每当轻微的脚步声传过来，隐蔽率数值就会一点点地稳步下降。利用这一点的话，就算藏在柱子后面，也能精准地推测出和对方的距离。

十五米……十二米……十米。

就当我往右脚里蓄力的瞬间，一股寒意贯穿了我的脊髓。遗漏了什么的预感在瞬间变成了确信。

到目前为止，我见过几次单独行动的堕落精灵呢？

我们在第五层〔译：简中SAOP4的156页把堕落精灵军官翻成了森林精灵军官，台版也是，差点错怪川原了〕击杀的军官身边有好几个护卫，在第六层闯入米娅家中的、还有在第七层的白骨平原出现的都是两人组。单独行动的堕落精灵、我只见过一次而已。

然而，我已经往柱子外面探出了将近一半的身子。事到如今也没办法再重新躲起来了。

——只能上了！

我给自己鼓劲道，然后猛地跳了出去。

我拔出背后的剑、同时落在了通道中央。正如我所料，和人影的距离还不到十米。我一边再次摆出跳跃的姿势，一边把剑举到右肩上方。叽——一阵尖锐的声音响起，淡绿色的闪光照亮了通道。

在系统辅助即将发动的前一瞬间，我用全力蹬地突进。

凭借我现在的能力值，全力使用单发跳跃技《音速冲击（Sonic Leap）》的话，应该可以勉强跨过这十米的距离。对手应该也想不到有人能从那么远的地方飞过来吧。

没错……如果是普通对手的话。

我拖着炫目的光之轨迹，以超越SAO精密物理演算的速度和轨迹飞翔，在到达顶点的瞬间，我将肩部扭转和手臂挥动所产生的力量全部灌注到了剑技之中。

吸血鬼化后提升的力量值和敏捷值；

单手直剑技能的熟练度；

魔剑哀伤夜想曲的性能；

以及蹬地和挥臂所带来的威力提升。

综合以上的所有因素，这一击无疑是我在艾恩葛朗特挥出的无数次剑技当中、蕴含着最大威力的一击。

但那个苗条的人影，用左腰的拔刀斩、也就是最为基础的普通攻击来迎击。

和持有者同样纤细的弯刀毫无悬念地被弹飞，魔剑的剑尖就这么深深地撕裂了对方的左肩——本应如此。

锵！伴随着这澄澈得如同水晶般的尖锐金属声，我的突进就像撞上了巨大铁块一样戛然而止了。

由于右臂承受了过大的负荷，我用余光瞥见了HP条微微减少了，同时我也试图去抵消这股反作用力。要是在此刻被反作用力弹飞倒地的话，这种对手可绝不会放过这个机会。

音速冲击那庞大的能量，在刀刃与刀刃微小的接触点上化作耀眼的光芒不断消耗着。如果是我到昨天还在用的日暮之剑+3，就算因承受不住而直接折断也不足为奇。不断飞溅的大量火花刺痛着我的双眼，但只要眨一下眼，瞬间就会连人带剑地被弹飞吧。

我咬紧牙关，等待着剑技的威力耗尽。闪光和高频震动逐渐减弱，火花也断断续续地消失……就在一切都消失不见的瞬间，我借助对方试图把剑推回来的力而向后跳开。

我好不容易才成功着地，然后又再次向后跳跃，并重新摆好握剑的姿势。我缓缓吐出一直憋着的一口气，然后又深深地吸了一口气。

站在三米外的敌人，不紧不慢地放下了细长的弯刀——不，是日本刀。

「真是个灵巧的家伙」

她的声音如同千锤百炼的钢铁般冷冽，却又带着一丝淡淡的甜美回响。

她那惊人的纤细身躯，从肩膀以上都被一件暗影般的连帽斗篷所覆盖着。防具则是同样暗灰色的铆钉皮甲。由于是那种紧束身躯和四肢的紧身衣样式，所以一眼就能看出是女性的体型。

和我一样没有持盾的左手举了起来，将兜帽向后掀开。

光泽亮丽的灰色头发采取了不对称刘海，后面则编成了好几条三股辫，是一种很奇特的发型。虽然现在看不到，但我甚至还知道被刘海遮住的右眼戴着黑色眼罩。

这位日本刀使先是眨了眨深蓝紫色的左眼，然后那打磨得锐利而精致的脸庞上浮现出了一丝苦笑：

「……是你啊，人族的小鬼。在之前我就说过了吧？别再掺和到精灵之间的因缘之中了……」

「确实是说过，但你说晚了一个月」

我用强压颤抖的声音回应道，同时明知没有必要，但还是看了一眼她的彩色光标。

颜色是如鲜血般的深红宝石色。

显示出的名字是，【Kysarah;Fallen Elven Adjutant】——

有着「剥伐」别名的堕落精灵副将凯萨拉。她曾经用一招范围型剑技就把我、亚丝娜、绮兹梅尔、米娅，以及Q扎古的四人击飞了出去。作为预料之外的对手，她的棘手程度仅次于诺尔扎将军……不，对我而言是同样不愿碰到的强敌。

……嘛，虽说上次连被当作敌人的资格都没有就是了……

我在心里暗自嘀咕着，同时试着将对方全身乃至周围的空间都纳入视野当中。面对这种水平的高手，要是只盯着剑的话，对攻击的反应就会迟缓。如果不通过感知前后、左右，或者上下的微妙重心变化来预测对方的行动，就来不及进行防御或躲避。

对于习惯了决斗的玩家来说，此刻早就该用假动作来干扰预判了，但凯萨拉只是自然地放下日本刀，保持着静止的姿势。我不禁怀疑她是不是不想战斗，但她可不是那种能让我抱有这种乐观想法的对手。

凯萨拉一直紧紧地盯着我，然后再次开口说话了：

「要是想去守护兽的房间的话，那你绕得还真够远的啊。而且守护兽也应该早就被打倒了吧？事到如今你在这里干什么？」

只要愿意的话，随时都能轻易地杀了你——她应该是这么想的，可为什么还会在意「我在这里的理由」呢。这刹那间的困惑，马上就变成了确信。

凯萨拉是想确认我是否知道前方有转移装置，但她自己又不想暴露它的存在。也就是说，如果她认为我对装置一无所知，就会毫不犹豫地过来杀我。

话虽如此，就算我表明知道装置的事，情况也并不会好转。届时我恐怕会被活捉，然后逼问出所有知道装置存在的人的名字。我既不知道她打算对感知不到疼痛的玩家使用什么样的拷问手段，也完全、一点都不想知道。

结果到最后，不把她打倒或者让她撤退的话，就无法摆脱这个困境。

我下定决心回答道：

「人族冒险者在迷宫里的理由，不就只有一个吗。当然是在狩猎怪物了啊」

「在第四层吗？对你来说太轻松了吧」

这直击痛点的反驳让我吃了一惊，但自认为比除了亚丝娜之外的所有玩家都要更熟络高度AI化NPC的我，可绝对不能语塞：

「住在这里的半鱼人拿着很好吃的红薯，我偶尔也会想吃几个呢。你要是想吃的话，我也不是不能给你也烤一个哦」

听到我的回答，凯萨拉又一次浮现出了一丝苦笑：

「不用。反正人族大概也不知道什么像样的烹饪方法吧」

我差点就要脱口而出「只是扔进火堆里就足够好吃了吧」，不过加雷城的大贤者布弗鲁姆老人，就连用平底锅煎过的红薯也只是评价「还凑合」，但他也说过「放上黄油的话就无敌了」。

我相信你啊老爷子，我在心里默念之后开口说道：

「别小瞧人啊。把红薯切成片、用平底锅煎得金黄酥脆香气四溢之后、再放上大量的黄油。这可比那些普通的甜点要好吃上好几倍呢」

「…………」

凯萨拉沉默了大概两秒钟，然后一本正经地点了点头，

「听起来确实挺诱人的」

「那就到第十层的安全地带……」

我这番急中生智的提议，还没来得及说完就被打断了。

「不，还是杀了你直接拿走吧，就像你对半鱼人做的那样。你也不会有什么怨言吧」

「…………」

这次轮到我沉默了。对精灵来说，半鱼人难道不是和水灵一样，都是神圣的存在吗，我一瞬间想到这个后又马上否定了。毕竟不管是绮兹梅尔还是拉维克，在斩杀半鱼人的时候都完全面不改色。

虽说如今已经无法避免战斗，不过率先发起攻击的人是我。明明有机会察觉到对方是谁，我却没有察觉到，所以事到如今也不能抱怨了。

对方能从容地挡住我全力以赴施展出的剑技，我实在不觉得能正儿八经地和这种对手战斗并取胜。也就是说，我或许很快就要死了，但不可思议的是，我的内心却很平静。大概是因为亚丝娜现在没有和我在一起吧。看来比起自己的死亡，我似乎更害怕临时搭档的死去。

亚丝娜也许会因我的死亡而受到打击，但即使如此，如果是她的话也一定会为了游戏通关而战斗下去吧。而且总有一天，她肯定会站在攻略集团的最前列，成为能给所有玩家带来希望的存在。

「……啊啊，确实没有怨言哦」

我这样回答后，便将哀伤夜想曲摆出了中段架势。虽然相处的时间还不足以将它称为爱剑，不过红色皮革包裹的剑柄非常贴合我的手掌，黑曜石般深邃的剑身也传来了令人安心的重量感。作为这场或许是终局之战的战斗伙伴，我对它没有一丝一毫的不满。

凯萨拉也后撤左脚，侧身对着我，将日本刀置于正中线。

三米的距离对剑道比赛来说太远了，但在这个世界里完全就是「一足一刀」的距离了。如果我主动进攻却被对方弹开或躲开，那肯定就会受到致命的反击。〔译：一足一刀的距离，剑道用语，指往前迈一步就能砍到、往后退一步就能躲开的距离〕

不过，要是凯萨拉用太刀招架的话，我还能有一线生机。为此，必须要制造出「无法化解也无法闪避」的时机，以及足够的杀气。如果凯萨拉只是个普通的士兵，那么这种类似虚张声势的气势对决或许是行不通的，但如果是和人类同等的高度AI的话——

在我感觉那把刀尖瞄准我眉心的日本刀、向上移动了大概一毫米的八分之一的那一刹那。

「唔哦！！」

我在最短的咆哮声中注入了最大量的杀气，同时挥动了手中的剑。

连近在咫尺的怒吼声也没能让凯萨拉左眼那冰冷的光芒产生一丝的动摇。但紧接着，她像是察觉到了什么，微微睁大眼睛的同时，把日本刀微微向左倾斜了（从我这边看）。她摆出了防御姿势——

在用出全力上段斩的前一瞬间，我的左手也紧紧地握住了剑柄。

双手持剑的全力斩击。

往下斩去的哀伤夜想曲迸发出了血色光芒。就这么重重地撞上了凯萨拉的日本刀。异常澄澈清脆的冲击声再次响亮地回荡开来。

但这次并没有就此结束。

魔剑的剑身中释放出来的赤红光之刃，穿透了格挡的日本刀，沿着凯萨拉左肩到右腰划过。被斩成两半暗灰色的连帽斗篷在空中飞舞着，固定皮甲上身部分的两条皮带也同时崩断，不知飞到了何处。

HP虽然连一成都没有减少，但或许是因为这突然的冲击，原本占据上风的凯萨拉也没能稳住身型，往后踉跄了几步。因为我没有使用剑技，所以没有受到剑技后摇的硬直影响，立刻就进入了追击状态。

目标是由于铠甲破损而暴露在外的腹部。如果能在那里用出全力的突击技，肯定能造成巨大的伤害。

我深深地吸了口气，打算再次发力——就在这时。

在我视野的最下端，发生了奇妙的现象。



凯萨拉及膝的皮靴突然被空气漩涡吞没了。不——并不是被吞没，而是皮靴本身产生了一个小型龙卷风。

被龙卷风吹飞的凯萨拉那纤细的身躯在空中不自然地减速。在翻飞的刘海深处，锐利的左眼骤然闪过蓝光。

虽然我心想不妙，但已经无法停下了，而且就算能停下来也肯定会遭到反击。我用力蹬地的同时，将右手滑到剑柄的最末端。这样一来，攻击距离就能延长将近十厘米。

「哈啊啊啊！！」

伴随着怒吼，我用出了全力的突击技。

「哈啊啊！！」

凯萨拉也迸发出锐利的气势，缠绕着龙卷风的双腿猛踏虚空。

在同一条直线上刺出的日本刀的刀尖和哀伤夜想曲的刀尖擦出火花后交错而过，我的剑划过凯萨拉的左腹，她的刀则掠过我的左颈，双双溅出了鲜红的飞沫。

紧接着，我们两人的身体猛地撞在一起，纠缠着摔倒了地上。算上装备的话，应该是我的重量要稍微大一些，但或许是因为她借着龙卷风跳跃的势头更猛一些，结果是凯萨拉压在了我身上。

「……！」

我本能地将右手握着的剑抵在了凯萨拉的后颈处。几乎在同一时间，我的后颈也传来了利刃切入的刺痛。

仅仅二十厘米外的那只暗绿色的独眼，即使在这种情况下也依然闪着如冰般澄澈的光芒。在那幅身处绝境也若无其事的冷峻面容上，浮现出了一丝不耐烦的表情。

凯萨拉突然把左手靠近我的嘴，用拇指粗暴地顶起我的上唇。

「干、干啥……」

「果然……这是法尔哈利的剑吧」

她轻声说着，同时终于把拇指缩了回去。我这时才终于意识到，她是在确认我有没有獠牙，事到如今也无法掩饰了，而且也不知道是否有必要掩饰。

「……没错」

我点了点头，下一个问题马上就抛了过来：

「成为夜之住民，是为了战胜我们吗？」

「不……」

我轻轻摇了摇头，然后再次诚实地回答道，

「是为了帮助我的主人」

「哼……」

凯萨拉轻哼一声，又露出了不耐烦的表情，

「……我以前欠了法尔哈利一点人情，但还没来得及偿还、他便消亡了。所以，这次就再放过你一次吧」

「放……放过我，具体☝是指……？」

「站起来、转身离开」

也就是说不让我接近有转移装置的房间。虽然我必须改变前往第八层的路线，但这点麻烦和性命来说完全不值一提。

「……明白了」

我回答完后，刺入我后颈的锋利刀刃就离开了。我也慢慢地抬起了握着剑的右手，放到了地上。

随后，凯萨拉便露出坏笑，一边说着「你这小鬼真蠢啊」一边用日本刀割开了我的喉咙——我一瞬间想象到了这样的展开，但这位堕落精灵副将并没有违背约定。她以轻盈得让人感受不到重力的动作站起身来，向后退了三步。我也利用腹肌的力量撑起上半身，左手撑地迅速站了起来。

我缓缓地拉开超过三米的距离，正打算转身的时候——

凯萨拉的尖锐声音让我全身紧绷了起来。

「……什么事？」

「把红薯留下」

「…………」

在艾恩葛朗特的两个月里，我已经学会了在这种时候不说多余的话。我打开窗口，从道具栏中取出六个《半鱼人薯》和一张羊皮纸，然后先把纸铺到地上，再把红薯堆成金字塔状放在上面。〔译：桐人打到了十几个红薯，却只给了凯萨拉六个，在这种时候还敢克扣几个（笑）〕

我再次站起身来，凯萨拉就立刻用下巴示意我的背后：

这次我真的转过身，用最快的速度朝着通道出口跑去。

直到爬上了通往迷宫塔十九层的楼梯后，我才终于能深深地吸入一口气。

紧张感刚一略微缓解，我双手的指尖就开始颤抖了起来。虽然说起来实在是有些窝囊，不过就算继续战斗下去，胜率最多也就只有三成……不，恐怕只有两成吧。

即使如此，当初在第六层连同伴也一起被她轻易击倒的时候，我可是确信完全无法战胜她的，所以现在的差距应该要缩小了一些。但这并非是因为我自身的成长，而是靠的吸血鬼之力和魔剑之力。

说起失算的地方，果然就是那个「龙卷风靴」了吧。对于能通过踩踏空气来移动的对手，我在之前一点点积累起来的对人战经验根本派不上用场。在下次战斗之前，必须要想出办法来封住她那麻烦的能力才行——

「……真是的……」

我不由得轻声嘟囔了一句，尽管双手因恐惧而麻木，可我的大脑却已经在思考下次该怎么战斗了。「这可是好不容易才捡回来的命啊」，虽然我想这么告诫自己，但为了夺回那五把秘钥，凯萨拉就是无法回避的对手。恐怕凯萨拉等等就要从迷宫塔下去，然后通过某种方式前往楼层东北方向的据点……

「…………！」

我猛地瞪大双眼，同时再次奔跑起来。我必须要警告可能正在据点里潜伏的亚丝娜和绮兹梅尔才行。她们要是在水路迷宫的出口附近碰上凯萨拉就完蛋了。

第四层迷宫区的第十九层的结构很简单，三分钟我就突破到了二十层。楼梯正前方的巨大门扉敞开着，向那些好奇的访问者宣告楼层BOSS《海马·维斯格》已被讨伐。

不过我还是先在入口处窥探了一下里面的情况，确认没有任何气息之后才走了进去。我还以为原骑士团团长拉维克说不定已经在里面等着了，不过宽敞的大厅里空无一人。仔细想想的话，目送拉维克进入尤菲尔湖西岸的森林也不过是两个半小时之前的事。就算是再厉害的高手，要爬上超过五十米高的断崖再翻越后面的石山也绝非易事吧。或许他打算今晚也在湖岸露营，明天再继续赶路呢。

我强行打断了仿佛现在就要奔赴明晚决斗的思绪，径直穿过大厅，随后一个劲地沿着房间深处的螺旋楼梯往上跑，这时，气温和气味开始发生变化。这种空气本身在切换的感觉，我在从第七层移动到第四层的时候也感受过。

每当我从往返楼梯出来，踏上新一层的土地时，我都会涌起一种别样的感慨。不过到达第五层已经是两周前的事了，所以我毫不停留地冲进了野外区域，随即打开了窗口。

我在消息界面的收件人一栏里输入亚丝娜的名字，然后全速输入正文。

【我在迷宫区的隐藏房间前遇到了凯萨拉。我虽然没事，但没能打倒她。凯萨拉应该会在一小时内前往据点】

要是亚丝娜她们还在水路迷宫里的话，就会弹出【对方处于无法联络的区域、或者没有登录】的错误信息。我怀着祈祷般的心情，正要按下发送按钮时却僵住了。发送按钮是灰色的，根本就按不了。

「…………」

直到这时，我才终于意识到自己犯了个初级错误。我虽然和亚丝娜从第一层开始就一直组着队，可却没有加好友。所以只能用即时消息来联络，但即时消息和好友消息不同，是无法跨楼层发送的。

也就是说，要是想把遇到凯萨拉的事告诉亚丝娜，就必须重新回到第四层，而非上楼前往第五层。

「嗯……嗯嗯嗯嗯……」

我一边低着头，一边只转动眼球看向视野左上角。由于队伍成员即使分散在不同的楼层也不会解散队伍，所以在我的HP条旁边，还显示着亚丝娜和绮兹梅尔的HP条。

自从我们分开行动以来，她们两人的HP都没有减少超过一成 ，而且现在也都是满的。反倒是我的HP因格挡凯萨拉的剑技、以及刀刃擦过我脖子时造成了一点伤害，不过在哀伤夜想曲的自动回复效果下，应该马上就能回满了。

也就是说，目前我们双方都没有什么值得担心的事。但即使如此，我还是想把凯萨拉来到第四层的事告诉她们。早知道会这样的话，我就不该觉得难为情而不加她的好友了……所谓的「后悔莫及」形容的就是这种情况吧。

「嗯嗯嗯……」

我一边再次沉吟着，一边转过身看着半毁小屋里面的螺旋楼梯。要是再冲进那里，然后从第四层的迷宫塔一直跑到最下边，我应该就可以给亚丝娜发消息了，但即使走最短路线恐怕也得花四五十分钟。而且还有可能在路上再次碰到凯萨拉。

「嗯～～……」

为了找到解决这个难题的线索，我又转动了一下身体。

这时，我看到在小屋东北方矗立着的漆黑要塞都市。

这座半毁的要塞一片黑暗，但下面的街道却被五颜六色的灯光照亮着。那是第五层的主街区卡尔鲁因。我本来是为了用那里的转移门转移到第八层，然后去见阿尔戈才来到这里的，但要是不先给亚丝娜发送警告消息，那我根本就没法静下心来听阿尔戈说话。

「…………啊」

我再次意识到自己又犯了一个初级错误，不由得轻轻叫出了声。

堕落精灵的转移装置是固定目的地的，我们发现的那个装置只能在第四层和第七层之间往返，但主街区的转移门可以自由地前往已经开通的楼层。也就是说，我可以先从卡尔鲁因的转移门转移到第四层主街区洛比亚，给亚丝娜发完消息后再马上转移到第八层就行了。这样也就才多花一两分钟吧。

接二连三的粗心大意，肯定是因为和凯萨拉的战斗耗尽了我的精力吧。绝对是这样……我一边说服自己，一边朝着令人怀念的卡尔鲁因跑了起来。

** 第10章

让我松了一口气的是，当我发送消息的时候，亚丝娜和绮兹梅尔已经从堕落精灵的据点撤离了，现在正沿着乌尔河航行。

她们之所以这么快就结束了侦查，似乎是因为一潜入据点就立刻偷听到了重要情报。由于情报内容有点复杂，在凤尾舟上长时间打字发消息会很危险，所以我们约好在尤菲尔城汇合后，再听她们两人详细说明。

我刚发送碰到了凯萨拉的消息，一秒后就收到了【快逃！】的回复，为了让她相信我已经身处安全的地方，着实费了我一番功夫。虽然很难想象凯萨拉会乘船或者在乌尔河里游泳，但我还是再三叮嘱她们一定要多加小心后，才关闭了窗口。

我抬起头，环顾着洛比亚的转移门广场。面向水路的广场被许多商店环绕，白天还会增设不少摊位，但现在临近午夜，大多数店铺都已关门，也看不到玩家的身影。

我走向广场中央的转移门，登上短短的台阶，触摸着闪着蓝光的椭圆形门。因为这是正式运营后首次前往第八层的主街区，我一时竟想不起它的名字，在一阵慌乱后终于说出了口：

「转移、弗利本」

艾恩葛朗特的第八层是森林楼层。

虽说第三层也是森林楼层，但和第八层的风格完全不同。第三层是保持自然风貌的原生林——不过比现实世界的原生林要好走得多，而第八层则是经过精心打理的管理林。不仅是所有的树木、似乎就连树根处长出的蘑菇和岩石上的苔藓也都是被照料的对象。

由此营造出了一种童话般的幻想美感，但对玩家来说，这里也像是一片地雷区。只要走出砖砌的小路，哪怕只是踩坏了一个蘑菇，轻则罚款，甚至还可能有牢狱之灾。

不过攻略第八层也不是非得要进入森林。这一层被一座环形人工湖分成了狭窄的外苑和广阔的内苑，人族的主街区和迷宫塔都在外苑，管理林则在内苑。环形人工湖上只有南北两座桥，过了桥之后，无论是从地理上还是观念上，都最好把那里当作另一个世界。

因为直径达六公里的第八层内苑、包括森林在内的整个区域，都是卡雷斯·欧王国的首都——斯鲁瓦。

从转移门出来后，我深深地吸了一口弥漫着清新树木香气的夜风。

第八层的主街区弗利本，建在位于外苑最南端的一座巨大岩山上。说是巨大，其实长宽也就只有五十米乘三十米左右，远远比不上那座仿佛能触碰到上层底部、十分恢宏的森林精灵王城，但也有小型商业大楼的规模了。

转移门广场只是把岩山山顶削平的一块空地而已，转移门所在的地方也不过只是一块天然石台。我顺着字面意义上的简陋台阶向下走，同时环顾四周。

直径约二十米的广场上既没有店铺也没有摊位，虽然主街区刚开放不久，但也没有玩家的身影。不过从下面隐隐地传来了热闹的谈笑声。

我打开窗口，给阿尔戈发了条消息【久等，我到弗利本了】。随后马上就收到了【我在十二层的橡实屋】的回复，我犹豫了一瞬，然后回复【OK】，便关闭了窗口。

我所在的转移门广场在东、西、北三个方向上都有通往岩山内部的下行楼梯。到底哪条楼梯能到十二层呢……我烦恼了一会后，最后随便选了东边的楼梯。

我沿着由于长年累月的踩踏而变得光滑的楼梯往下走，来到了一条弯曲的狭窄通道中间。通道内侧杂乱地排列着形色各异的门，在这个时间里，从其中的几扇门里还透出温暖的灯光和欢声笑语。〔译：话说SAO的门不是绝对隔音吗，就连第二层的美国西部酒馆类型的门都是隔音的〕

通道上也有数名闲庭信步的玩家。他们大概不是攻略集团的一员，而是随着主街区开放而从下层上来的观光客吧。弗利本在岩山内部塞进了大大小小一百多家店铺，其中六成都是餐饮店——或者该说是酒馆，属于是喜欢的人会非常喜欢的类型。

而且由于以前的人毫无计划地乱挖通道，所以虽然名义上有楼层数，但这些楼层并没能好好地连接起来。比如从第十层的楼梯下去可能就到了第七层，从那里再上另一段楼梯又到了第九层，而且每层还被分割成了多个无法直接通行的区域。在封测时期，熟悉内部构造的玩家甚至还做起了收费导游的生意，由此可见内部构造是有多么复杂了。刚才我之所以犹豫着要不要回复OK，也是基于这个原因。

我凭借着模糊的记忆沿着通道往右走，然后顺着左边的楼梯下去，走了一会又往上走，就在我差不多该给阿尔戈发送求助消息时，通道尽头出现了一扇有点眼熟的茶色门扉。

门上镶嵌着的小块磨砂玻璃透出了微弱的光，下方则有一块模仿橡实造型的青铜牌子。虽然没有店名，但这里肯定就是阿尔戈指定的店铺。

我推开发出KoloKolo的干涩声音的门。

昏暗而狭窄的店内只有三个吧台座位、以及深处的一张能坐三个人的半圆形桌子而已，但这样的小店在弗利本十分常见。

在吧台后面，身材极其矮小的店主正在擦拭杯子。但他既不是小孩也不是人类，而是有着茶色皮毛和尖尖鼻子的獾类兽人。

店主用又黑又圆的眼睛瞥了我一眼，然后用与体格不相称的低沉声音说道：

「呃……已经约好了」

听了我说的话，店主的黑鼻子轻轻向右动了动，这个动作让我觉得有点像凯萨拉说「走吧」时的样子，笑意和恐惧感同时涌上了心头，不过我还是勉强绷住了，用严肃的表情点点头后朝着点里面走去。

半圆形桌子是分成两半的巨大原木切片，漂亮的年轮在上面清晰可见。桌子上有一个用木头削成的盘子和两个杯子。盘子里面放着小小的茶色果实，乍一看像是带壳的橡实，仔细一看也确实是橡实。

椅子也是用原木直接砍成的，一个身材娇小的玩家坐在其中的一把椅子上，朝着走过去的我咧嘴一笑：

「终于来了吗」

虽然这位玩家的上半脸还藏在兜帽的阴影之下，但那独特的尾音和鼻音毫无疑问就是阿尔戈。我尽力板着脸，用早就准备好的话来回敬她：

「可不是「终于来了」吧，为什么要在这家店见面啊。找个更显眼的店，或者干脆在转移门广场见面不就好了吗」

「我觉得桐仔会喜欢这种店啦」

阿尔戈刚说完，我就听到了一声像是刻意咳嗽的「咳咳」声，在这时我才终于注意到，在柱子阴影当中的里侧座位上还坐着另一个人。

说不定这就是那个告诉阿尔戈ALS和DKB陷入危机的玩家吧……我这么想着，同时倾身探头看去。

坐在那里的，是一个比我要稍微高一些的男性玩家。红色的头巾将短发树立起来，下巴上长着短短的胡子。身穿用金属板加固的皮甲，武器则是一把略细的弯刀。

但这些情报没能进入我的大脑当中。在和这个男性玩家目光交汇的一瞬间，我就因巨大的冲击而彻底僵住了。

头巾男微微举起杯子打了个招呼。

我听到自己的嘶哑声音时，才发现嘴巴已经张合了两下。

「…………克莱因…………」

（待续）

** 后记

〔译：后记中的括号都是川原写的〕

非常感谢您阅读《刀剑神域 Progressive》第9卷《青蓝水月的夜想曲（上）》。

在桐人成为吸血鬼——不对，是《夜之民（Civis Nocte）》后，虽然在作品里还没过半天的时间，可在现实里竟然已经过去了三年零九个月。我一时之间也不敢相信，还通过网络和实体书确认了第8卷的发行日期，看来确实是没错……真的是让您久等了！

（以下涉及正文内容）

一提到吸血鬼化，虽然经典的展开是一边呻吟着 「血……我要血……！」 一边袭击同伴。但 SAO 并无法通过系统操控玩家的思想和欲望（因此也没有睡眠或凶暴化的负面状态），桐人也没有真的想要去咬亚丝娜的脖子，这该说是很遗憾吗？另一方面，夜之民和现实世界的吸血鬼一样，一旦沐浴到日光就会立即死亡，所以桐人在一段时间内似乎都只能被迫在夜间进行攻略了。副标题「夜想曲」当然就是基于这样的含义来取的。而且整个故事的氛围，也与名为「狂诗曲」的第七层中四处奔波的状态截然不同，变得更加沉稳了。我再次认识到，标题确实有着强大的力量啊……

关于故事内容，桐人他们从第七层暂时回到了第四层，着手于夺回秘钥、以及解决尤菲里斯子爵和原骑士团团长拉维克之间的恩怨。虽然我也非常想快点看到他们前往第八层，但在精灵战争 战役任务进入高潮之前，还是有必要在一些地方提及一点关于精灵们的社会和历史的内容，所以如果您能暂且陪伴他们在第四层展开冒险的话，我将不胜感激。

话虽如此，在本卷的最后一节中，只有桐人提前一步移动到了第八层，并且在那里终于与在第一层起始城镇分别的最初的朋友——克莱因重逢了。虽说在作品中是时隔两个月的再会，但在作品之外，这是自第1卷（不是进击篇，而是本篇！）发行以来，和克莱因整整十六年的重逢场景。我写到这时也有「这样真的没问题吗……？」的犹豫心态，但既然克莱因出现了，我打算让他在下一卷中大放异彩。

最后，我要向大家道个歉。之前进击篇的上下卷，我都是连续发行的，但这次由于各种原因，下卷预计需要一些时间才能发售。我会尽最大努力尽快发行，还请大家稍作等待。本卷的日程延迟也给负责插画的abec 老师、责任编辑三木先生和安达先生带来了很多麻烦，下卷也请多多关照！

二〇二五年一月某日 川原砾

** 译者后记

大家好，我是B_Meow，也可以叫我B喵，可能不是初次见面了吧？

首先，先对看过我翻译的28卷之后，还能相信我翻译的读者们说声感谢及抱歉。总感觉每次的译者后记都在道歉……

每当我一个人干所有活的时候，我总是会感叹独行玩家果然还是有极限的，真是恨不得把自己掰成好几瓣用……但我又不会求助别人，这可以说是我的坏习惯了……

而且本卷说是个人翻译，但r大也指正了非常多的地方，没有r大指正的话，估计我就会发出错误百出的SAOP9了，看来不是独行玩家有极限，而是等级低的独行玩家有极限啊……

自发出28卷的翻译以来，我就一直在后悔着，特别是过了半年翻译完迷宫馆外传之后，回头再看一遍28卷（甚至没脸看完），翻译的完全就是史，实在是过于「原汁原味」了。不仅如此，还影响了拉斯翻译的速度，真的是十分抱歉……S大也对本次的修图给予了十分宝贵的建议，实在是万分感谢。

个人翻译并不代表低质（虽说我翻译的28卷完全就是低质……），也不能是低质的借口，说到底菜就是菜。

所以本卷从翻译、润色、排版再到修图，都尽我所能地让它更接近我心中的模样了。希望本次SAOP9的翻译可以让大伙看得开心，SAOP10没有特殊情况的话我应该也还是会翻译的。

以下是关于SAOP9的分析（包含剧透及猜测）。

SAOP8发售时，进击篇所描写的还是未来的故事，而三年多后才发售的SAOP9，所描写的就已经是过去的故事了，每当现实时间一步步超越SAO时，我不禁总是会感叹时间易逝……等现实时间超越AW时，我又会有什么感受呢，希望那时候SAO能完结吧（笑）。

本卷几乎都是在填之前的坑，因此可能会觉得少了点什么，不过这起码证明川原没有忘记之前挖的坑。

从很久之前就开始铺垫的黑暗精灵女王也终于又补充了一点设定，作为目前艾恩葛朗特可能活的最久的人/精灵（诺尔扎将军一千岁起步），她的存在显然是非常特殊的。而根据目前进击篇和UR篇同步进行的策略来看，当桐人在进击篇当中见到黑暗精灵女王时，在UR篇也很有可能（80%）同时见到黑暗精灵女王，UR篇中的女王甚至有可能保留了SAO的记忆，让我们敬请期待吧。不过正篇29卷还要和ApD开会，见到黑暗精灵至少30卷，见到女王得31卷了。

但这同时又引出了一个新的疑点，当前的UR世界，显然是已经完成了大地切断的状态，从这个角度来看，那见到女王的概率就微妙地变小了一点，但我还是认为能在UR世界里见到女王。

从21卷开头来看，茅场并没有直接参与UR事件里，那么还有谁能重现茅场梦想中的Uniel大陆呢？我在此提出一个有些异想天开的想法，重现大陆的就是——卡迪纳尔系统。

种子（The SEED）发芽，在吸收了众多VR世界的精华之后，再反哺The SEED的根本，一切的起始——Uniel大陆。

但究竟是卡迪纳尔系统有了自我意识，还是有人利用卡迪纳尔，我目前还不好说。

本卷也首次提到了黑暗精灵历法，这在UR篇中估计也会马上提及。已知法尔哈利屠龙时艾恩葛朗特已经建成了，那艾恩葛朗特的历史至少有400年了（法尔哈利300多年前去世，再加上他本人的年龄），目前黑暗精灵历法是接近2500年，再假设法尔哈利出生前几十年发生了大地切断，那么按黑暗精灵历法来算，大地切断的时间就很可能就是黑暗精灵历法2022年（也是现实中SAO开始的时间），黑暗精灵女王所持有的情报真的是越来越重要了。

然后是尤菲里斯子爵的问题，我实在是想阿米诺斯，可毕竟川原不惜吃书也要将阿尔马克设定为男性，我觉得肯定是有什么意义在里面的。可我左思右想、前思后想、东想西想，就是没想出来为什么非得是男男。尤菲里斯子爵悲剧的核心是什么？当然就是《禁断の恋》，单纯的异族恋就完全足矣，往上加个男男buff我是没想明白的。在这里不妨逆向思考一下，如果阿尔马克是女性，会对整体造成什么影响吗？显然是没有的，以我个人的角度来说甚至还要更好一些。而且子爵的父亲明确表示是「受到了薇丽的诅咒」，已知只有女性水灵才叫「薇丽」，好，那我问你、那我问你，阿、阿尔马克，你是男的还是女的？如今唯一的解释就是子爵的靴子里面并不是阿尔马克的头发，而是另一位女性水灵的头发，但就算这样也足够让我反胃了，看下一卷能不能解释了。

再然后是克莱因，川原在后记中写「打算让他在下一卷中大放异彩」，这就实在是不禁让人遐想了。黑猫团时期桐人依旧没有和克莱因和解（只是桐人单方面没和自己和解），如果川原不想吃书的话，那克莱因应该不会成为进击篇常驻角色，估计也就是在SAOP10中流星一闪了。

最后，再说一下个人的感慨。

对一个东西保持热爱其实是一件相当难的事，生而为人就会不可避免地被各种东西约束，因此热爱也会不断地被消耗。我接触SAO满打满算也就7年，真正开始细读则只有6年，而r大已经有十多年了。在这十多年里r大还能不丧失对SAO的热爱、一直为爱发电持续输出着翻译，这实在是一件非常非常幸运的事，不仅对SAO的读者们是幸运的事，对SAO这部作品本身更是幸运的事。

那么，就让我们「下次」再见吧。

B_Meow

2025年4月22日

----

（注：下面是进击篇部分固有名词的简中翻译）

人物

N'ltzahh;Fallen Elven General 堕落将军诺尔扎

Kysarah;Fallen Elven Adjutant 凯萨拉（剥伐的凯萨拉）

Eddhu;Fallen Elven Foreman 艾都

奇欧 妮露妮尔 巴丹·科尔罗伊

绮兹梅尔 白檀骑士团团长 拉维克·冯·科尔塔西奥斯 弟弟 铁匠 兰德伦

列休连·泽德·尤菲里斯子爵Yofilis;Dark Elven Viscount

艾基尔 沃尔夫冈 耐让 洛巴克

丽特恩 斯瓦塔 欧可坦 涅兹哈

黑森林蛋糕 辛肯 哈夫纳

布克森姆 摩尔特 丈

加雷城 布弗鲁姆 梅朗·加兹·加雷翁伯爵

洛摩罗老人

--

其他

NerveGear Sword Art Online 琉苏拉 琉苏利安 卡雷斯·欧 卡雷斯安 沃尔普塔 莱克西奥

暗夜外套 强化胸甲 紧身衬衫 暗影长裤 尖刺短靴 体力戒指

骑士轻剑 针织连帽斗篷 薄胸甲 击剑短袍 护板皮革短裙 腾跃之靴 涟漪耳环 烛光戒指

白檀骑士团 槐树骑士团 枸橘骑士团

Slashing Ray

--

第四层

洛比亚 主城 卡尔特拉湖 乌斯克村 尤菲尔城

凤尾舟 蒂涅尔号Tilnel 炎兽冲角 裴庞德号Pequod

亚尔基洛的薄布

--

第八层

弗利本

（Doleful Nocturne）（Sword of Volupta）（Spine of Shmargor）
（Wythege the Hippocampus）（Frikadeller）（Leviathan）
（Sigil of Lyusula）（Undine）（Sword of Eventide）
（Dark Elven Wolf Handler）（Chivalric Rapier）
（Pleated Leather Skirt）（Rusty Lykaon）（Scuttle Crab）
（Magnatherium）（Ichthyoid Cultivators）（Horned Rabbit）
（Artificial General Intelligence）
