#+title: 我的青春恋爱物语果然有问题 短篇集1 雪乃side
#+setupfile: ./setup.setup
* 短篇集1 雪乃side

** 那个答案随风而逝。

台版 转自 深夜读书会

发布：深夜读书会

论坛：ritdon.com

作者：石川博品／插画：切符

「自闭男，你真的很恶……」

「亏你会有那么恶心的想法。真想敲破你的脑袋看看里面——不，还是算了。反正里面装的东西也一样恶心。」

被人骂成这样，无地自容的我，冲出侍奉社社办。

哪句话是谁说的，应该不用我说明吧。简单却直击心脏的那句是由比滨，冗长又直击心脏的那句是雪之下。

我忽然想到，我身边的女性都是唱出来的歌词（在不好的意义上）会直击心脏的宛如奈奈的存在耶……不如说，多达半数的人类都是奈奈。我看地球干脆改名叫水树奈奈座长公演「水树奈奈纵情歌唱（注1）」好了。总有一天，跟外星人自我介绍的时候我要说「您好，我是来自水树奈奈座长公演『水树奈奈纵情歌唱』的比企谷八幡」，对方可能会吓得心想「这家伙住的星球的统治者自我主张欲超强的」。

我摆脱的不是地球引力，而是社办的引力，但我不知道要去哪里，便决定先去二年F班的教室看看。

天气很热，因此我打开窗户，风灌进空荡荡的教室，把窗帘整个吹起来。

我随便找了个位子坐，环视教室内的桌椅。眼角余光瞥见窗外满溢夏日阳光的景色，导致没开灯的教室显得更加昏暗。

现在这情况让我想起……放学后，跟我单恋的她告白的那一天……呃，这也是会直击心脏的情境。

过去和现在都在对我的心灵造成伤害。如果我是史古基，八成会在未来的幽灵造访前就心碎。（注2）

我晃着双腿沉思。

仔细一想……为什么我刚刚非得被由比滨和雪之下骂成那样？

我只是说了句「我觉得千叶君（注3）好色」啊。

因为，那东西怎么看都是用来挑起性欲的吧？全身红色明显是发情的证据。许多动物到了发情期体色都会变鲜艳。有一种说法是女性用红色的口红和腮红，也是因为能藉由类似发情的表情吸引异性或同性的目光。

除此之外，从嘴巴吐出来的舌头、往上翘的鼻子——肯定也是在暗喻某种突起物。

再加上千叶君的布偶装和图片的风格不同，肉肉的，看起来超好抱。当面看到他，应该没多少人有办法抵抗那肉感的魅力。

而且cheeba<千叶>一词在英文中是大麻的俗称。既然如此，我不得不断定那家伙等于是会行走的快乐物质。

——我滔滔不绝地述说完以上的意见时，社办的空气降到冰点。

在法国大革命的庆功宴不小心说了句「不觉得玛丽･安东妮挺可爱的吗？」气氛大概都不会这么僵。

不过玛丽真的很可爱。最后还会觉醒成王妃。《凡尔赛玫瑰》我整套都看过了，所以我很懂这方面。我有自信就算我在这个瞬间转生到那个时代，也会从比企谷八幡变成神秘的没落贵族罗兰･德･戈利拉（注4）存活下来。

我怀着这样的心情，产生看见三色旗在远方法国的天空随风飘扬的幻觉，就在这时。

「八幡，你为何在此处彷徨？」

有个人影站在教室门口。在这个大热天穿大衣戴露指手套，光看到他的身影就觉得热。

「喔，是材木座啊。」

我一叫他的名字，那家伙就往这边走过来，不知为何看起来有点高兴。

「顺带一提，八幡啊，彷这个字是指人牵着一只牛在旁边走——」

「啊，不用跟我说明。」

中二病喜欢用复杂的词汇，一有机会就会用在对话中，想跟人说明语源。至于我为什么知道呢，因为我也曾经罹患那种病（用罹患这个词就是）。国中写的作文满是汉字，凄惨无比。「附近的吉娃娃在咆哮」、「在公园跌倒的小孩恸哭着」、「地面的蚂蚁专横跋扈」，跟魔界一样的城市出现在稿纸上。

材木座坐到我旁边的座位，压得桌子吱嘎作响。

「你有烦恼吗？不妨和吾谈谈，强敌<吾友>啊。剑豪将军的意见箱一直是开放状态喔。」

我真的很不擅长应付这种「男人间的友情」的调调。

跟材木座商量侍奉社那件事，八成不会得到有用的意见。毕竟这家伙比我还废。

然而，有点想看他的废物样的邪恶想法浮现脑海。

「其实……这样这样那样那样如此这般欲穷千里目自挂东南枝。」

「呣……」

材木座抱着胳膊，闭目沉思了一段时间。看来他思考得比我想像中还认真。我有点愧疚。

不久后，材木座瞬间瞪大眼睛。

「八幡，你…………原来是兽控吗？」

「嗯？」

我歪过头。把我刚才的愧疚之情还来。

材木座把手放到我肩上。

「没事没事。别看我这样，我也懂你这类型的人。轻小说家必须精通各种性癖。」

「轻小说家还真辛苦。」

总觉得我想表达的意思完全没传达给他。

「不过……先不说你的性癖，被两位女性嘲笑却选择忍气吞声，有点窝囊喔。你就不能抬头挺胸地反驳『单纯的兽耳娘不行，我只会对有动物口鼻的真正兽人兴奋！』吗？」

「呃，我不喜欢那种——」

「堂堂男子汉岂能如此软弱！给我直接回呛她们！」

「别强人所难了。那你有种当面和由比滨跟雪之下呛声吗？」

听见我的问题，材木座「呵」笑了声。

「你觉得想当轻小说家的人有办法呛女生吗？」

「轻小说家还真辛苦。」

「再说，我不擅长跟那两个人相处。尤其是雪之下这位女士，老实说有点可怕。」

这家伙果然很废。一点用都没有。

我开始觉得自己像个白痴，站起来望向窗外。

尖锐的笑声传入耳中。往下面看过去，打扮得花枝招展的三位少女边聊天边走向校门口。

我灵机一动，拿出手机。现在时间下午三点四十分。

「看那个位置……是时候了……」

「什么东西？」

材木座走到我旁边。

我指向地面。

「看得见那三个女生吗？」

「嗯。」

「十五秒后，那三个人内裤会被看光光。」

「说什么蠢话。」

材木座傻眼地摇头说道：「现在这个时代，连爆死的动画都不会随便发生幸运色狼事件。八幡，你因为太过憎恶女人而发疯了吗？你就是因为这样才会——」

这时，一阵风吹起。

伴随呼啸而过的风声撼动校舍。我背后的窗帘甚至被吹到天花板上。

尖叫声响起。

「哇——！」

「这是怎样啦～」

「讨厌～」

地上的三人用双手按住快被吹起来的裙子。

我揉了揉被风吹得泛泪的双眼。

「虽然我刚才说被看光光……从上面根本看不见嘛。」

我觉得自己显得很可笑，忍不住笑出来。

望向材木座，方形眼镜底下的眼睛瞪得大大的。

「风、风之继承者･风精恶戏<EulenSylpheed>･第二章<Chapter Two>……你果然也是能力者吗……」

「也？」

「方才那阵风是你召来的对吧？」

「怎么可能。单纯是预测。我收集了很多五月的网球比赛结束后，关于风向的资料。靠统计算出午休时间和放学后会从哪个方向吹来什么样的风。」

「原来如此……这样的话……」

材木座跑到黑板前面，拿起粉笔不知道在写什么东西。「只要有这个能力……呵呵，很好……复仇的机会掌握在吾等手中！」

这家伙到底在碎碎念什么？我站到他背后。

黑板上乱七八糟地画着箭头跟神秘的火柴人，以及同样神秘的算式。

「八幡啊，用你的能力让由比滨和雪之下哭着求饶吧。」

「你在说什么？」

「听好——」

材木座拿粉笔敲敲黑板。「首先，你把她们俩叫到适当的地点，然后等到那个时刻来临。如此一来，风就会吹起裙子露出小裤裤，我们看了则在内心呜呼呼。」

「嗯……」

我收集风向的资料，只是基于好奇心。绝对不是因为想看谁走光这种不良意图。

「如何？八幡啊，要执行这个计划吗？」

「嗯……」

我再度望向窗外。白云在高空随风飘动。

云真好。不用工作也可以靠风的力量去往任何地方。

以前人类也会利用风力，例如风车或帆船。工业革命后就开始依赖各种燃料，不再使用风力。

革命有利有弊。生活是变方便了没错，但环境也因此遭到污染，失去和大自然的连结。

此时此刻，人类是不是该跟大自然联手，建立一段新关系了？没错，例如藉助风之力吹起女生的裙子——

「八幡革命！揭开序幕！」

我伸出手，以带领人类前往新的舞台。

「呵，就等你这句话。」

材木座用力用沾满粉笔灰的手握住我的手。

——日后，这起事件被称为「总武高中<High School>之誓」。

隔天放学后，我和材木座约在脚踏车停车场后面会合。

这里离我平常吃午餐的地方很近，是我待很久的地方，所以风向资料也很齐全。

脚踏车停车场设置了高达腰部的铁板，我跟材木座蹲在地上躲在那后面。

「那么八幡啊，你要叫由比滨还是雪之下出来？」

「在那之前——」

我将放在地上的书包拿到手边。「我想做个实验。」

看见我从中取出的东西，材木座惊呼出声。

「那、那……那不是裙子吗！」

我手中的是裙摆部分缝了白线的百褶裙。

材木座目瞪口呆。

「莫非是你偷——」

「不是啦。跟我妹借的。」

说是借，当然没征求过她的同意。要是老爸知道，八成会被断绝亲子关系。搞不好还有可能逼我出家。「八幡」感觉可以直接拿来当和尚的法号耶，其他和尚会说「这家伙就叫八幡了」之类的。总有一天我要独立，开一间初代八幡寺。还要开连锁店掀起寺庙系风潮。

「实际穿上那件裙子，让风吹吹看的意思吗？反覆验证这一点还挺科学的嘛。不过……要由谁来穿？我可不要。」

「裙子和我的眼睛都会被玷污，所以我不会叫你穿。」

「那到底要由谁……？」

「人刚好到了。」

我稍微起身，朝脚踏车停车场的对面挥手。一名在左右张望的学生发现我们，小跑步跑过来。（←好可爱）

「八幡，原来你在这。我找你找好久。」（←看吧好可爱）

户冢彩加（←名字好可爱）来到脚踏车停车场后面，对我展露微笑。（←已经抵达尊的境界）

我从昨天到现在一直在看材木座的脸，因此户冢的可爱度比平常更能感动我。光一天就这么严重，如果我出家后再直视他的可爱，只能脱离佛教，改创户冢教了。世界三大宗教……够资格当我的对手。

「啊，材木座同学也在呀。」

「喔、喔喔，是户冢氏啊。呣呣，原来是这么一回事。」

被叫到的材木座带着邪恶的淫笑对我使眼色。真的好恶。

不，等等……我自己看不见，该不会我在户冢面前也是这种表情？拜托不要……

材木座等于是反映我自身的镜子。如果我是魔女，比起白雪公主，一定会先把这种镜子扔到森林深处。

我刻意装出严肃的表情。

「不好意思，在社团活动前把你叫出来。」

「不会啦，别客气。」

户冢露出有点腼腆的笑容。

「谢谢你愿意来。」

「嗯。」

「谢谢。谢谢。」

「嗯、嗯……」

「谢谢。」

「真的不用客气喔？」

户冢不知所措，真心感谢上帝。我心中的人气排行第一名到第十名都由户冢独占。因为我每日会投一万次感谢的票。

「所以，你找我有什么事？」

「嗯，就是——」

我拿出妹妹的裙子。「拜托！什么都别问，穿上它吧！」

「咦～？」

户冢明显感到困惑。

好吧，这反应很正常。

「户冢氏！这是为了科学！为了科学！」

材木座目光异常锐利。这家伙怎么比我还激动？

「可是……」

户冢看起来还无法接受。

「好，我知道了。那我也脱吧！」

「也？」

我当着一头雾水的户冢的面，脱掉白衬衫和长裤，身上只剩一件内裤。

「八幡……太厉害了……」

户冢的眼神落在我的下半身上。「你的内裤好花俏！」

「对吧？」

不知为何，我买内裤的时候都会不小心失控，选择花俏到极点的内裤。男用内裤很有立体感，超帅的说。还分各种材质跟机能性。

在这方面，女用内裤一点魅力都没有，那根本是一坨皱巴巴的布，蕾丝也只会碍事。男用内裤果然最赞了。是说户冢不知道穿什么样的内裤。

「你的内裤上面有很多星星，挺帅的。」

材木座似乎也是男用内裤派。

「这是最潮的部分。」

「到魔界应该会很有地位。」

「嗯。晚餐吃什么都是由我决定！」

我和材木座畅谈内裤话题时，户冢依然一脸困扰。

「穿裙子有点……因为，我是男生耶？」

这句话太中肯了。

但我可不能在此退让。毕竟事关户冢穿裙子的模样。

「你在说什么？穿女装可是只有男人有资格去做的真正有男子气概的行为喔？」

既然户冢这么拘泥于男子气概上，我也要用男子气概说服他！

如果我昨天在社办也能这么会辩，而不是落荒而逃就好了。「你们说千叶君不色？那来看看我的千叶君啊。（脱）」……我看最好的结果是退学。最坏的结果是遭到雪之下「那是千叶君？顶多只是中之岛吧」的冷眼看待，因为太难过而跑去中之岛大桥跳海。

顺带一提，用千叶君来譬喻的话，中之岛是位于胯下附近的小岛，是可以捡贝壳的优秀娱乐地点。可以经由全日本最高的天桥中之岛大桥到岛上，但这座桥被指定为「恋人的圣地」所以我完全不推荐。

「穿女装有男子气概……是、是这样吗……」

户冢把手放在胸前，看着地面，看起来相当动摇。我的内心也在动摇，不过这不重要。

应该要再推他一把。

我抓住户冢的肩膀。

「这件事只能拜托你。靠男人的友情和我缔结羁绊的你。」

现场气氛害我不小心说出「男人的友情」这种词汇。

我们在极近距离互相凝视，过没多久，户冢的脸颊染上一层淡红色。

「既、既然八幡都这么说了，可以喔……」

好耶！那得先去你家跟你爸妈打声招呼才行。戒指那些要怎么办？

「那裙子借我吧。」

户冢从我手中拿过裙子。

啊，你答应的是这个啊……我刚刚一瞬间成了未来都市Diversity的居民。天空的颜色是空频道的颜色……

户冢在我们背后换衣服。基于绅士协定，我不会回头。

旁边的材木座在喘气。

「欸，八幡啊，奥菲斯从冥府回来的途中，是不是也是这样的心情？」

「谁知道。」

这家伙干么擅自跟我产生连带感。现在户冢穿的是我妹的裙子，我等于是户冢的哥哥喔。外人给我闭嘴。

不久后，换上裙子的户冢出现在我们面前。

「喔吼……」

材木座发出灵魂出窍般的声音。

「如、如何……」

户冢抓着裙摆，双腿互相摩擦。上半身是短袖运动服，但这样反而营造出一种中性风，或者说像个不做作的女生，满不错的。

是说他的腿真好看，膝盖也好光滑。如果有出「户冢的膝盖滑鼠垫」，真想买二十个贴满全身，化为妖怪——户冢的膝盖小僧在附近徘徊。

「户冢氏，很适合你。」

我也差点说出「像真正的女生」。然而户冢刚才拘泥于男子气概上。也就是说，「像女生」是禁句。我该以理性的态度面对。

「好，符合实验条件。那么麻烦你移动到那个位置。」

「嗯、嗯，知道了。」

户冢略显迷惘地走向我指的方向。

等他走到离校舍十公尺的地方，我用手势叫他停下。

户冢在担心被网球场的社员们看见，不停偷瞄那边。这个感觉也好色喔。

我旁边的材木座又在喘着粗气。

「呼……户冢氏……」

「很吵，可以请你只吸气不要吐气吗？」

户冢看着我，用眼神询问「还没好吗？」。

我拿出手机看时间。

「五……四……三……二……一……就是现在！」

一阵风吹过。

远方的网球场传出尖叫声，沙尘盖过另一侧的景色——世界以慢动作运行。

裙子如同起飞的鸟儿般随风飘扬，缓缓掀起。连纤细白皙的大腿根部都露出来了，他急忙用小手压住。

「哇！」

户冢整张脸都红了。

我的灵魂直达天际，飞往无垠的宇宙。

「啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊！」

比企谷八幡，炸裂 全文完

我瞬间回到地面。

刚才好像有什么东西「结束」又「开始」了，是错觉吗？

材木座神情陶醉，在我旁边大叫。

「八幡——！」

这家伙干么叫我名字？还有，为什么语气跟电影《火线追缉令》里面犯人说的那句「警察先生——！」一样？

声嘶力竭的材木座坐倒在地。

「我刚才……碰触到了世界的秘密……」

「哦……你也抵达那个『领域』了吗？」

在我们进行这段令人兴奋的帅气对话时，脚踏车停车场的另一侧传来不怀好意的声音。

「看，那个人明明是男生还穿裙子耶。好可爱～」

「我记得他是网球社的，被人叫做王子。」

「下面穿什么？让姊姊看看？」

疑似三年级的三位辣妹围住户冢，竟然抓住他的裙子想把它掀起来。

「别、别这样……」

户冢试图抵抗，可惜寡不敌众，大腿逐渐露出。

「呣唔唔……多么卑劣的手段！」

材木座咬紧牙关。「我很想伸出援手……但现在还是先静观其变吧。」

有道理。我也想静观其变——说得更具体一点，我想观察掀起来的裙子底下有什么东西。

然而，我和户冢之间有着男人的约定。在他陷入困境的时候坐视不管，枉为男人啊。

「唔喔喔喔喔喔喔喔！」

我呐喊着从脚踏车停车场后面跑出来，直接冲向户冢。

「住手——！要脱的话先从我的内裤开始脱——！」

包围户冢的三名女性纷纷往我这边看。

「哇！」

「那家伙是怎样⁉」

「裸族冲过来了！」

她们尖叫着逃跑。大概是被我的气势吓到。

我跑到户冢身边。

「没事吧？有没有被她们怎么样？」

「没、没事……可是，为什么你还没穿衣服？」

「伊甸园的人类都是裸体的——我能说的只有这句话。」

最初的人类叫什么名字？亚当和亚当？上帝果然什么都没禁止嘛万岁——！

户冢下半身穿着裙子，我的胯下则只用比无花果的叶子更具功能性的布料遮住，奇装异服的两人平安回到脚踏车停车场后面。

迎接我们的是带着诡异笑容的材木座。

「实验成功。」

「是啊。」

「终于。计<Project>画<rt/>即将执行。」

「咦？喔……」

呃，你干么擅自叫它Project啦，不过听起来超帅的所以就这样吧。

「八幡，你流好多汗。」

经户冢这么一说，我发现自己满身是汗。因为我刚才跑得很拼。户冢的额头也冒出汗水，或许是因为被一群女生包围，吓到他了。甜美♥的香气窜入鼻尖。吃什么东西才会发出这么香的味道？蜂蜜或花粉之类的？根本是蜜蜂嘛。嗡嗡嗡～噗滋！这是我的心被刺中的声音♥

材木座跟平常一样是成天流汗座。听起来像成吉思汗，真酷。

三个男人汗水淋漓。这样的话，要去的地方只有一个。

「好～我请你们去超级澡堂～」

材木座露出奸笑。

「泡完汤的咖啡牛奶也包含在请客范围内吧？」

「这还用说。」

「为你的男子气概干杯。」

我和材木座用力握手。

「所以我们是来这边做什么的？」

户冢一脸疑惑。

我和材木座面面相觑。

「呃……我们来这边干么的？」

「刚才好像提到计划……」

「啊～对喔。好吧，那就来吧。」

「嗯，就这么办。」

我拿出手机，检查风向的资料。

「喔，十五分钟后好像会吹起一阵不错的风。」

我决定先把感觉比较好骗的由比滨叫出来。

按下播号键，她一下就接了。

『喂？』

「是我啦，比企谷。」

『怎么了吗？』

「你在社办吗？」

『对呀……』

「可不可以到走廊上一下？」

『嗯、嗯。』

有雪之下在的地方不能讲秘密。她可能会靠神秘的力量立刻察觉到。

电话另一端传来拉开拉门又关上的声音。

『自闭男，那个……关于昨天那件事，我有话想跟你说……』

「我也有话跟你说。你现在有办法到我这边吗？」

『咦……？是可以……你要跟我说什么？』

「见了面再说。不方便用电话谈。是很重要的事。」

具体上来说是「给我看内裤～♥」，这可不能用电话讲。万一被录音拿去法庭上当证据就太可怕了。

『重、重要的事……？可是，我还没做好心理准备……』

「咦？什么东西？」

『没事。我马上到。』

我将地点告诉她，挂断电话。

户冢把身体凑过来。

「八幡，你好擅长用电话把人叫出来喔。跟电话诈欺的犯人一样。」

「咦，是吗？」

这个可爱的小恶魔又想让我背负罪名吗？除了比上帝更爱户冢外，我没有犯下任何罪喔？

「好，在由比滨来之前，我和户冢留在这待命。材木座负责冲去最近的ATM——」

「八幡啊，别叫朋友当车手。」

我们蹲在脚踏车停车场后面，等待时机来临。

「欸，到底要做什么？」

面对户冢的疑惑——

「你不必知道。And stay with me……」

我巧妙地唬弄过去。

不久后，由比滨抵达我指定的地点。

她先是扫了四周一眼，拿出镜子。对着镜子拨弄明亮的褐发，整理好像有点拉太开的衬衫领子——花了五分钟整理仪容。

材木座附在我耳边说：

「她好认真。」

「女生都这样吧。我妹每天早上也都要弄那么久。」

听见我们的对话，户冢轻声笑了出来。

「我觉得要看她要见的对象是谁。」

「对象？」

材木座指向我。「对象是这个男人耶。」

「对啊。是我耶。」

「正因为是你吧。」

户冢微笑着凝视由比滨。

什么意思？户冢真的是宇宙的神秘。

资料记载的时间逐渐接近。

我打开手机的时钟，开始倒数计时。

「要上了……五……四……三……二……一……就是现在！」

然而……并没有起风……！

网球社的击球声传入耳中。半点风都没有，裙子一动也不动，当然看不见内裤，今天斗争也没有从世界上消失。

「不可能……怎么会这样……」

我为这个不合理的世界感到愤慨，不停比对资料和时间。这个时间应该会刮强风才对。

「难、难道……」

我忍不住从脚踏车停车场后面冲出来。身后传来材木座「八幡，回来啊！」的呐喊声，我却已经进入全速飞奔状态。

踮着脚尖，脚后跟抬起来又放下，在做神秘运动的由比滨发现了我。

「自闭男，嗨啰——呃，你怎么没穿衣服⁉」

她瞪大眼睛，我站到她旁边环视周遭。

「糟、糟糕——！」

视线前方是一群打乱我计策的元凶。

「大家好——！京城工业高中柔道社二十名社员，现在到达！」

「小凑学园高中柔道社三十名社员，打扰了！」

「欢迎——！共同练习的会场在这里！」

壮汉集团从眼前经过。带领他们的那个长得像番薯的人，我好像见过他，不过距离太远，看不清楚。

没有跟资料所示的一样起风，就是因为那群人。风被他们散发出的浓郁男性荷尔蒙吸走了。

风会从气压高的地方吹向气压低的地方，同时也会往男性荷尔蒙浓郁的地方吹。每年台风会北上，也是因为北海道人不论早晚都在大吃成吉思汗烤羊肉（注5），导致身体表面分泌男性荷尔蒙，把台风吸引过去。有一种说法是元日战争的时候，所谓的「神风」也是元军发出的男性荷尔蒙引来的。

柔道社这个出乎意料的要素，破坏了我的计划。柔道社真的很烦耶……再也不想跟他们扯上关系。

「自闭男，你在干么？而且还没穿衣服。」

由比滨提心吊胆地走过来。

糟糕……得想个理由骗过她。

我不仅没有遮住身体，还展开双臂挺起胸膛，故意秀给她看。

「其实……我在做现在流行的男性荷尔蒙美容法。」

「那什么东西⁉」

你觉得是什么？我才想问呢。

「就是……全身暴露在空气里的男性荷尔蒙之中，让肌肤光滑、体脂肪锐减、吃得好睡得好、驱邪避魔、一攫千金的梦幻美容法。我就是想告诉你这办法，才把你叫出来。」

「哦～」

由比滨逼近我。「你皮肤确实满好的。」

碰触我的胸膛。

「啊嗯……！」

手指冰冷的触感，害我忍不住叫出声。

「真的很光滑耶～」

由比滨的手向下抚摸，接着又往上移动。

「啊、啊、啊……」

我的体内荡起酥麻的波纹。

接着掀起一阵巨浪，我乘浪飞往更高的地方。

「啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊！」

比企谷八幡，炸裂混合吧（注6） 全文完

「自闭男，你还好吗？」

由比滨拍拍我的肩膀，我于地面复活。

「呼……看来男性荷尔蒙摄取过度，会害人做出异常行为。」

「那这个美容法根本不能用嘛。」

她笑着说道。

近距离一看，她皮肤真好。人家好嫉妒喔！刚才的反弹害人家体内的女性荷尔蒙迅速增加，比企谷八幡子<读音省略>嫉妒得咬牙切齿。

「那、那个，自闭男，刚刚在电话里提到的那个……」

由比滨手指在胸前戳来戳去。

「昨天那件事吗？」

「我觉得我昨天对你说得太过分了。用那种眼光看千叶君又不会怎样。」

「原来是要讲这个啊。」

我搔搔头。「已经无所谓了。」

「是吗？」

「因为千叶君是千叶县的官方吉祥物，我只不过是个平凡的高中生。怎么想都不相配。」

「你好认真⁉」

「而且我现在心里有其他人了。」

「这、这样呀……」

由比滨把手背到身后。「顺便、顺便问一下，那个人是怎样的人？」

「我想想……我注意到他的契机，是他陪我打网球的时候，他总是陪在我身边，看到我犯蠢会对我笑。就算我像现在这样没穿衣服。」

听见我的回答，由比滨立刻变得满脸通红。

「大概……大概啦，那个人一定也对你有意思。」

「是吗？」

咦，户冢喜欢我吗？万岁！

「那赶快来袒裎相见吧。」

「咦⁉」

由比滨大声惊呼。「会不会……太赶了？」

「为什么？」

「因为，我们还只是高中生。」

「高中生就不行吗？没关系吧。」

超级澡堂有规定高中生不能去吗……？时间也是早上就有在营业，现在去不嫌赶。

难道由比滨没去过超澡？所以才会产生奇怪的误会。跟户冢袒裎相见培养感情，顺便邀这家伙一起去吧。

「欸，你等等有没有空？」

我一问，由比滨就「咦咦⁉」发出更大的惊呼声。

「有空的话，跟我一起——」

「不不不不不，等一下等一下等一下。不行啦不行啦不能这样啦！」

她用力挥手，转身跑走。

那家伙干么啊……正常人会对超澡这么排斥吗？还是她背上有超大片的刺青？

我回到脚踏车停车场后面。

「由比滨好像情绪不稳。她突然叫超大声，有点恐怖。」

「『女人心和御宅族的本命』可是善变的代名词。」

材木座得意洋洋地说。

「就我看来，八幡情绪也满不稳的。」

户冢露出复杂的表情。

先不说这个了，这样剩下的目标只有雪之下。我能否攻略那如同铜墙铁壁的裙子？看她平常那个完美超人样，光碰到她的裙子八成就会断两、三根手指，好可怕。

她们家感觉就是真的有在继承自古以来的「能力」及「宿命」的一族。

总之我决定先联络她看看。我透过户冢取得她的手机号码。

「喂——」

『哎呀比企谷同学，真巧。我有件事想问你。』

「咦……？」

莫非她发现我在调查「一族」了……？我、我什么都不知道！是有人跟我说打这个号码就给我十块钱……

『由比滨同学有点奇怪，你知道原因吗？她突然离开社办，碎碎念着「完蛋了完蛋了」跑回来，然后就拎着书包回家了。』

我、我真的什么都不知道！我对圣母玛利亚发誓——嗯？我知道……

「大概是某种荷尔蒙分泌异常。」

『真令人担心。要不要帮她介绍医生呢？』

「洗个澡睡一觉就会恢复了吧。」

『那就观察到明天吧。』

看来由比滨的事勉强蒙混过去了。

「我打电话给你是想问，你方便过来一趟吗？」

中间隔了短暂的沉默。我隔着电话感觉到她在不耐烦。

『你这人挺老套的嘛。竟然在放学后把人叫出去告白。』

「才不是。是更重要的事。」

『哎呀。』

她的语气变柔和了。『意思是，你要跟我坦承比昨天那个更脱离常轨的事实啰？我顿时有兴趣了。』

真的假的。没想到她评价这么高。早知道不逃了。

「那你到我说的地方来。」

我指定那个地点，挂断电话。解放感使我自然而然吁出一口气。

「呼呼呼……准备完毕。我要靠风之力揭露雪之下的The･Scanty。」

「The？」

户冢歪过头。

雪之下一如往常，释放出拒人于千里之外的气势从校舍走出来。

她站在跟户冢和由比滨同样的地方。

我所在的位置看得见她的侧脸。笔直的视线、随风摇曳的黑色长发、雪白剔透的肌肤。俨然是青春恋爱喜剧的女主角——只要没有那根毒舌。

但那可不是用一句「只要没有」就能带过去的事。我听她说过，她从小就因为外貌出众的关系被同性排挤。若能回到过去保护她，是不是就不会变成现在这样？不过搞不好会因为有大哥哥保护她的关系，害雪之下身边的女性统统嫉妒她，更加讨厌她，雪之下也会因为有个眼神死的男高中生不知为何缠着自己不放，被吓到，忍不住对他讲出尖酸刻薄的话——啊，这是逃不掉的命运。只能从法国大革命的时间点附近改写人类史才挽救得了。这样她可能会说出「巴黎大猩猩（注7），没面包的话吃甜点不就行了」这种话。

「八幡啊，还没要起风吗？」

经材木座一问，我望向手机。

「再等两分钟。只要雪之下没在那之前回去——」

「欸，你们看。」

户冢指向网球场。

仔细一看，起风了。

不对，「起风了」这说法太优雅。正确地说，是轰隆隆卷起一阵旋风的状态。

树叶、树枝、网球社社员的毛巾被风卷起。褐色尘土从地面吹向空中，玷污蔚蓝的天空。转眼间就看不见网球场了。

「龙、龙卷风……⁉」

材木座站起来。「莫非这也是你的力量……？」

「怎么可能。」

他到底觉得我是谁啦。

是说这个异常气象是怎样？地球怎么搞的？昨天我叫它水树奈奈座长公演，惹它生气了吗？可是除了奈奈以外，能靠座长公演让新宿KOMA剧场和太阳广场塞爆的知名歌手，我只认识巴布･狄伦耶。狄伦可不可以在舞台上演时代剧？

网球社社员尖叫着逃进校舍。

雪之下站在原地。明明只是站在那边，却因为逆着人流的关系，看起来像在面对狂风。风吹乱她的长发。

「那家伙为什么不逃？」

我抓住脚踏车停车场的柱子。

「八幡……这样下去雪之下同学会……」

户冢的声音在颤抖。

龙卷风正往这边接近。变大到直径十公尺左右，超可怕。

只能由我去救雪之下了吗……把她叫到那边的人是我。仅仅是为了看内裤这个无聊的目的。

「你们觉得危险就乖乖进学校吧。」

我抛下这句话冲出去。飞过来的沙子直接砸在身体的正面上，连呼吸都有困难。雪之下站在比我离龙卷风更近的地方，一动也不动——彷佛希望自己遭到吞噬。

「快逃！龙卷风要来了！」

我站到她旁边。

她抬起手臂挡在脸前面，发现我来了，瞥了我一眼。

「你用错词了。」

「什么？」

「龙卷风的上空会有积雨云。规模更大，天气也会变差。这个没有云，所以是尘暴。气象用词叫尘旋风。是晴天地表空气升温时会发生的现象。」

「两个都没差吧？」

「气象预报说会是白色圣诞节，结果却下大雨的时候，你会说『两个都没差吧』吗？想像一下。圣诞老人淋成落汤鸡，装蛋糕的纸箱因为湿气的关系变得软趴趴的，迪士尼乐园跟地狱一样——」

「有差……太悲伤了……」

看到我无法反驳，雪之下微微扬起嘴角。

「我之所以不离开这里，是因为跟你有约。」

「咦？」

「我和你这种随便的人不同，一定会遵守约定。只要我说了会去，不管是哪里我都会前去赴约。绝对不离开那个地方，直到达成目的。那就是我的人生态度。」

她说得很对。约定就是该遵守。

不过与此同时，我觉得很沉重。那顽固的人生态度，会让旁观者如坐针毡。

还有，她很美。

刚才在脚踏车停车场看到迎风而立的她，我觉得很美。头发被吹乱，衣服随风摆荡，全身沾满尘土，她依然笔直地站在那里，对自身没有任何怀疑。这身姿使我看得出神。

然而，她的美是不是非得在面对危机之时才会产生？当她投身于暴风中，她的美才会趋于完美？

若是如此，我并不想看见。一定看不下去。

「可是，除了跟你有约外，一部分原因也是因为我从来没近距离看过尘暴，挺好奇的。我都不小心看呆了呢。」

还有，这家伙真是个怪人。老实说，应该跟我有得拼。

「如果我是随便的人——」

我笑着回她。「遵守跟那个随便的人的约定的你又是？不就只是个笨蛋吗？」

我这句话令她的视线稍微动摇。

「说得也对。那赶快离开这里吧。」

她快步转身离去。看来她其实挺害怕的。

我也转身背对暴风。嘴巴里都是沙。

「话说回来，你为什么没穿衣服？」

「现在才问这个？过很久了耶。」

「你刚才说我『只是个笨蛋』，可以收回吗？在这种地方裸体的你更——哎呀，那是……」

她的视线从我身上移开。我跟着看过去。

「喂，不会吧……」

那里竟然有只朝气蓬勃地往尘暴跑过去的可爱小猫（搭配合成得超烂的脚步声）！

动物真的很笨。虽然很可爱。总觉得我在关键时刻都会撞见陷入危机的动物。是不是去拜一下比较好？

「不可以靠近那边！」

雪之下正准备去追小猫。

我立刻抓住她的手，柔软的小手在我手中被捏成一团。

「雪之下，别过去！」

「放开我！」

她转身瞪着我。

我抓着她的手用力一拉，她的脸近在眼前。

「进学校去。我来救那只猫。」

「可是你没穿衣服。」

「这可不是单纯的没穿衣服。」

我挺起胸膛。「我的皮肤由满溢而出的男性荷尔蒙强化过。」

听见这有趣的玩笑，她的嘴角动都没动一下。不仅如此，还垂下目光，咬住下唇，露出像在后悔，像在忍受某种情绪的表情。

「你真傻。总是只会开这种玩笑……」

「对啊，我很傻。比你傻了那么一点。」

真是……不晓得是谁第一个想去救小猫的。

雪之下小跑步跑向校舍。目送她离去后，我才跑去追小猫。

风愈变愈强，飞过来的沙子在肌肤上留下如同针刺的疼痛。

「喂——过来。很危险喔。」

我趁猫坐在地上时试着把它叫过来，麻烦的是，小猫看了我一眼，冲向尘暴的中心——也就是天空之城里面的「龙之巢」。

这家伙……比我还蠢。好吧，猫也只不过是尼特族的高阶版。

继续前进太可怕了。不过，我也只能硬着头皮上。

「唔喔喔喔喔喔喔喔！风精恶戏<EulenSylpheed>･最终章<TheFinal>！」

我咆哮着冲进旋风之中。

眼前一片昏暗。飞扬的沙尘挡住阳光，风声也遮蔽了听觉。喘不过气，肌肤的疼痛转为像在被刀砍的痛楚。

我感觉到有东西碰到我的脚，慢慢蹲下，将它用手包覆住。毛皮底下的娇小身躯在发抖。

这只猫刚刚才被我吓跑，现在却任我摆布。或许它并不是真的对我解除心防了。但在这阵强风中，比起解除心防，解除身体的防备还比较好。

我缩起身体护住猫。几乎什么都感觉不到，只有手中的温暖明确地传达过来。

过了一阵子，我才发现风停了。耳朵因为残响的关系怪怪的，肌肤一阵阵的刺痛，只感觉得到周围的亮光。

我仰躺在地上，把手中的小猫放在胸口。仔细一看，是只漂亮的白猫。不知道是谁家的猫。

「你没受伤吧？」

猫舔了下我的脸，大概是在回答我。痒痒的，不过很舒服。

猫真好。没工作却那么可爱。如果当不了专业主夫，我想成为一只猫。

「比企谷同学！」

雪之下冲过来。

她蹲在我旁边，观察我的脸色。

「你太乱来了。」

「不过这家伙得救了。」

我将猫放到她手上。她用有点僵硬的动作把猫抱在怀里，抚摸它的背，表情是前所未有的温柔。我看着她问：

「欸，雪之下，刚才的约定还算数吗？」

「嗯。」

她用脸颊磨蹭猫，点头。「因为我还不知道你要说的重要的事是什么。」

「喔，就是——」

可爱的声音打断我即将说出口的话。

「八幡～没事吧？」

转头一看，户冢正在从校舍的方向跑过来。

猫是很可爱没错，但户冢也很赞。真想被户冢养，当猫或主夫都可以。

「八幡～挺身保护猫的兽控的气魄，我见识到了！」

材木座也发出「咚咚咚」的脚步声跑过来。希望这家伙被真正的龙卷风吹到彩虹的另一端。

在我心想「应该没人会再叫我了吧」的时候，我听见女人的声音在呼唤「牛奶！」，瞬间想了下我什么时候多了牛奶这个花名。

「牛奶，原来你在这里。」

听见那个声音，小猫从雪之下手中跳出去，扑到一名人妻风的丰腴美女身上。她穿的牛仔裤绷得紧紧的。这种人在弹性牛仔裤发明前不知道都穿什么。

「是你救了牛奶吗？」

把牛奶抱在怀里的丰腴美女问我。

「嗯，算是。」

我坐起身子。

「谢谢你。虽然称不上什么谢礼，请务必到我家一趟，我帮你准备一套干净的衣服。不介意的话还可以冲个澡。我老公出差了，现在不在家。」

「呣……这个情境，不会有错……」

材木座咬牙切齿地说。

我站起来，拍掉身上的灰尘。

「谢谢您的好意，但我等等跟重要的人有重要的约定。」

「比企谷同学……」

雪之下看着我。

我对她微笑。

没错，我跟人有约。

「好～你们两个，来去超级澡堂啰～！」

然后冲向材木座和户冢。我现在全身都是汗水跟沙子，有够不舒服，真想快点洗个澡清爽一下。

「呣。那我就先不摄取水分，把胃留给泡完汤喝的咖啡牛奶吧。」

「走吧走吧。」

他们也兴致十足。

「八幡男人祭！要开始啰！」

我们三个勾肩搭背，迈步而出，这时雪之下追过我们。

「你说的重要的事，下次有机会我再听。」

她转过身，表情恢复成一如既往的冷淡。

「总有一天会告诉你。」

我刚才讲到一半的，是非常老套的台词。老套到我自己都觉得恶心。同样的话如果对象是户冢或猫或千叶君，明明能随口说出来的说——呃，三个里面有两个是动物。户冢也跟蜜蜂没两样。我果然是兽控吗？还是连昆虫都能接受的类型。

「总有一天吗？反正八成是随便的约定。」

看着她逐渐远去的背影，户冢露出淘气的微笑。

「八幡挺天兵的耶。」

「我吗？是喔……天兵……豚骨（注8）……讲一讲肚子都饿了。」

材木座听了笑出声来。

「那泡完澡我请你们吃拉面。有家店我很推荐。」

「加面也包含在请客范围内吧？」

「这还用说。」

我和材木座用力握手。

男人的友情果然最棒了！

我们发出「Rassera<裸裸>——Rassera<裸裸>——」（注9）威猛的吆喝声，慢步走向男人祭的会场超级澡堂。

另外，雪之下蹲在我身旁时我不小心看到她的内裤，这是秘密。

完

1注  水树奈奈的个人演唱会名称。

2注   梗出自《小气财神》。主角史古基在过去、现在、未来的圣诞幽灵出现后痛改前非。

3注   千叶的吉祥物。

4注   Lowland gorilla为低地大猩猩的英文。

5注   北海道的乡土料理之一。

6注   《七龙珠》中达尔制造月亮时说的台词。

7注	  「巴黎先生」为刽子手的代名词。

8注  「天兵（Ponkotsu）」与「豚骨（Tonkotsu）」日文音近。

9注  青森睡魔祭上人们会发出的吆喝声。「ra」音同「裸」。

** 将棋真有趣!!!

作者：相乐总／插画：ももこ

那一天，雪乃一如往常来到侍奉社社办，映入眼帘的是难以用「一如往常」形容的景象。

两位陌生男性坐在社办的正中央。

他们隔着一张桌子相对而坐，面色凝重，低头沉吟着。

往桌上一看，是日本最大众的桌上游戏。

他们在下将棋。

「这里什么时候变成将棋社了？」

雪乃轻声——至少对她而言已经有在控制音量——叹息，戴眼镜的男生似乎吓到了，身体向后仰去。

「啊，啊，啊？」

对不起、不好意思——听不清楚的软弱道歉声，落在社办的地上。

「你说什么？我一个字都听不见。讲清楚一点。」

雪乃温柔地——至少对她来说没有比这更亲切的语气——回问，戴眼镜的男生都快哭出来了。

「——啊，啊，啊！」

他留下另一名男生，逃也似的冲出社办。

明明没人会对他怎么样。

单纯的问题都能让他慌成那样，八成是因为提问者的表情太恐怖。当然，从雪乃本人脸上挂着和蔼可亲的微笑这一点来看，理论上来说，怎么想都是眼镜男孩看见幻觉了。

玩将棋会看见幻觉。真可怜。法律应该禁止这种游戏。

雪乃悲伤地摇头，然后清了下嗓子，调整心情。

「所以，请问你哪位？」

说起来，她原本就没打算质问眼镜男孩。

是因为另一位陌生男性厚颜无耻，不慌不乱地坐在那里，她才忍不住叹气。

全是依然待在社办的这男人的错。

「你好像没打算跟他一样逃走。请问你来侍奉社有何贵干？」

「……呃，啥？」

留下来的男子在雪乃的注视下，发出比表情更厚颜无耻的声音。

一副自己是这间社办的主人的态度。

这么说来，打从一开始，他就是旁若无人地坐在这里，不像眼镜男孩那样。只想得到他企图靠暴力手段夺取社办，在这里创立将棋社这个可能性。

下将棋会变野蛮。真可怕。联合国应该禁止这种游戏。

雪乃摇摇头，为暴力的桌上游戏的恐怖之处低下脸。

视线就这样落在男子的室内鞋上，「哎呀」了一声。

「仔细一看，这不是比企谷同学吗？你今天真早来。」

「……不要靠室内鞋上的名字才终于认出对方啊。」

比企谷八幡不耐烦地撑着颊。

「对不起，因为你的脸让人不太想留下印象。下次见面时我会努力记住。」

「根本是对待从来没见过面的人的态度……」

「我无时无刻都这么希望。」

「真巧，我也每天都在这么想，要我现在就当成我们从来没见过面都没问题。」

八幡回以讥讽。

离升上高中二年级，已经过了数个月。

以侍奉社的身份共同解决的各种委托，仍然记忆犹新。尽管她也不想，八幡特有的死鱼眼实在无法轻易忘记。

因此，说什么长相不会让人留下印象是一种玩笑。当然了。

与友人的交流，就是由这种无拘无束的玩笑构成的吧——雪乃在内心偷偷这么想。

不过比企谷八幡并非她的朋友，拿来举例一点都不适合。这人为什么一副跟我很熟的样子？

「先不说这个了，你到底在做什么？」

「看就知道了吧，下将棋啊。雪基百科不知道吗？」

「我知道。」

雪乃摇摇头，手指抚上桌上的将棋盘。

「将棋这个要用脑的游戏，和比企谷八幡这个特殊人类的组合，我实在无法接受……对不起。我平凡的想像力无法补足你欠缺智慧的外表，我真的很心痛。」

「别用那么诚恳的语气跟我的外表道歉……」

八幡无力地说。

一直是这样。

雪乃跟他讲话时，八幡一定会像这样板着一张脸。

简直像在对拿聊天当藉口逗自己的朋友以上恋人未满的女生感到不耐。

当然，比企谷八幡对雪乃来说是认识的人以下人类未满的存在，该不耐烦的是她才对。别再让她觉得更烦了。

「那个人是来委托我们的。」

八幡冷淡地说，指向眼镜男孩逃往的走廊。

「委托呀……」

雪乃跟着看过去，这次轻声叹息。

不晓得是不是又是平冢老师介绍来的。

解决了几件委托后，其他人好像误会了。侍奉社可不是打开来就会冒出魔法咒语的玉手箱。

「如果设计成偶尔会有腐烂的比青蛙跳出来，无意义的咨询会不会减少呢……」

「我听不懂这句话，不过别用那种期待我做些什么的眼神看我。」

「可是，这次不就是因为你吓到人家的关系，委托人才一句话都没跟我说就回去了？」

「可以请你不要窜改记忆窜改得这么自然吗？他找我商量时就很正常，是因为你冰冷的语气跟态度才吓跑的耶？」

「再讲下去也没意义。比起那个，把委托内容告诉我吧。」

「唉……」

八幡仰天长叹。

大概是意识到怎么说都没用。证明他认同雪乃是对的。说实话，她不讨厌老实的八幡。

但也一点都不喜欢。这部分可别误会了。

「你……算了……就是，他想改变社团的气氛。」

八幡望向远方，仔细地述说。

眼镜男孩是真正的将棋社社员。

雪乃并不知道总武高中有将棋社，不过大部分的学校，将棋和围棋这类型的社团都用不会进入女性的视线范围的特殊迷彩处理过。这一点没什么问题。

问题在将棋社内部。

「听说他们直到去年都还是和乐融融的和平社团。」

「跟我们社团一样？」

「……是我幻听吗？你说跟侍奉社一样？」

「噢，不好意思。这不是该跟非社员说的话。请继续？」

「我百分之百是社员好吗……总之有个棋力高达全国等级的转学生加入将棋社。那个人透过关系，找来年轻时就以职业棋士为目标的奖励会出身的顾问，导致社团的气氛整个变了。」

具体上来说——

他们决定以团体战的形式，在「高中龙王战」这个高中将棋界最大的比赛中打进全国大赛。

在此之前都走轻松路线的文系社团，蜕变成认真严肃的社团。

每天都要参加社团活动自不用说，还以晨练及中午练习为由叫人解好几盘棋局，假日也规定要看将棋书和去将棋道场——认真下将棋自然而然成了义务。

「……往更高的地方迈进未必没有好处吧。又不是每个人都跟某人一样，会藉由贬低自己反过来肯定自己。」

「要看方法吧。只要不是跟某人一样，藉由排挤他人维护秩序就好。」

「太好了。比企谷同学还知道自己被人排挤呢。」

「我放心了。你知道自己在排挤他人……」

将棋跟以前侍奉社社员玩过的「大富豪」这种纸牌游戏，有着一个决定性的差距。

也就是否为「双人零和有限确定完全情报游戏」。

将棋分出胜负时，完全不存在运气要素。

反映在棋盘上的，只有理所当然的实力差距。

强者获胜，弱者落败。仅此而已，纯粹又残酷的世界。

因此——

跟棋力差距过大的弱者下棋，对强者来说没有任何好处。

「起初他们好像想大家一起切磋琢磨。但将棋到头来就是只凭实力说话的游戏。最后特别会下棋的人，只会跟特定的对象下棋。无视较弱的社员……不仅如此，还彻底把他们当成『不存在的人』。」

「这社团说不定很适合你。」

「这句讽刺真是有够直接……」

或许是彻底习惯雪乃的挖苦了，八幡看起来没什么反应，拿起手边的棋子放到棋盘上。

「于是，社内现在完全没有交流。棋力低落的社员渐渐不来参加社团活动。听说还有人甚至变得讨厌将棋。刚才那名学生就是担心将棋社的现状，才来找我们帮忙。」

「……原来如此。」

雪乃竖起食指抵着脸颊，摆出思考的动作。

「认真下将棋的他们，相信那是通往全国大赛的必要之举。为了达成符合高中生身份的目标，某种意义上来说他们在以『正确的方式』努力对吧？」

「嗯，这样说是没错。委托人也是因为这样，才一直不敢开口。」

「不过，你不喜欢那个『正确的方式』。所以想接下委托……事情就是这样。」

雪乃瞄了八幡一眼。

经过短暂的沉默，八幡明显移开视线。

「……别讲得像你都看在眼里一样。」

「这点小事不用看也知道。」

雪乃耸耸肩膀。只要待在八幡身边，谁都看得出来。不是只有我特别理解他——或者说，想要理解他。绝对不是。这严重损害我的名誉。快给我道歉。

「可是问题在于……这种事基本上该由社团的人亲手解决。」

八幡也点头同意雪乃的说法。

这跟插手处理朋友之间的纠纷不同。

这次的委托事关其他社团根本上的经营方针。随便插嘴的话，搞不好会换成委托人本人沦落到退出社团。

「也不是想不到方法……在那之前，比企谷同学。」

雪乃指向桌上的将棋盘。

推测是将棋社的委托人说明状况时顺便带过来的。她从来没碰过这么正式的棋子，连拿法都很生涩。

然而，八幡刚才的动作比自己熟练许多。虽然她并不想承认，真不甘心。

「你会下将棋对吧？」

「嗯，会一点。」

「我想也是。任何生物都至少有一个长处。例如黑猩猩会梳毛，大猩猩可以把香蕉连皮一起吃下去。你大可引以为傲。」

「比较对象不是人啊……」

八幡苦笑着说，但受到他人的称赞，他应该很高兴吧。

他缓缓清了下喉咙，用指尖拎起将棋给雪乃看。

「既然是土生土长的千叶人，会下将棋是当然的。」

「为什么？」

「因为那个伟大的十三世名人——关根金次郎就是千叶人。」

「……关根，金次郎？」

「改革维持三百年传统的名人制，创立将棋联盟的『近代将棋之祖』。关根一门一脉相连的系谱中，有『棋界的太阳』十六世名人中原诚、『超越羽生的男人』十八世名人森内俊之、『史上最强』的十九世名人羽生善治、上了年纪依然处于全盛期的『一二三』加藤一二三，还有一肩扛起下一代的『天才』藤井聪太等等，多到数都数不清。现代的将棋风潮，说是由千叶带起的都不为过。」

「……我没问这么详细。」

「当然，千叶在现代也是知名棋士辈出。于四十六岁夺得王位，睽违四十六年更新了最年长的初头衔获得者纪录的木村一基、下棋时吃饭的模样引起话题，被找去拍食品广告的丸山忠久、让顺位战从来没输过的藤井聪太第一次吃败仗，逼他原地踏步一年的近藤诚也、以「三间飞车（注10）藤井系统」这个让三间飞车派狂喜的战法引来注目的佐藤和俊……每个人都是千叶出身。甚至可以说全世界所有的千叶人，或多或少都跟将棋有关系。」

八幡滔滔不绝地说。

老实说挺烦的——雪乃心想。

大概是将棋拥有能让人脑袋出问题的特殊魔力吧。例如不相信他人的高中生仅仅是被夸几句，就会忍不住一直聊将棋。例如会在某作品的短篇小说集里硬塞将棋梗。

下将棋会入魔。真惊悚。小学馆（注11）应该禁止这种游戏。

雪乃叹了口气，平静地说。

「比企谷同学最近有点像那个……叫材什么的人呢。」

「…………」

顶着一张臭脸的八幡瞬间陷入沉默。

雪乃知道只要在他讲个不停的时候搬出这个人名，他就会安静下来。材木什么的与剪刀必有用。

「总之，我知道你算会下将棋了。那还有办法。」

雪乃将掌中的棋子放回将棋盘上。看来这次的委托，或许没有她出场的机会。

「既然是将棋社内部的问题，从内部发声就行了。对吧？」

「……果然只能用这招吗？」

八幡应该也跟雪乃想到同样的主意。他「喀」一声让棋子前进，发出今天最响亮的声音。

意即——实际加入将棋社。

幸好总武高中没禁止加入复数社团。将棋社应该也不会像运动社团那样，严格规范中途加入。

「以眼还眼，以牙还牙，以猛毒攻猛毒。」

「有必要在汉摩拉比法典上加入多余的东西吗？」

「不过这样会给人家添麻烦，达成目的后就尽快回到侍奉社吧。」

「……尽快啊。」

雪乃只是在担心被比企谷八幡这个稀世毒素入侵的将棋社而已，啊啊，他在误会什么呢。

八幡讽刺地笑了。

「你刚才还说我是非社员咧，怎么？果然还是承认我是社员吗？」

「你、你脑袋有问题？别误会，我是真的真的很讨厌你。真希望现在就能看见你凄惨的死状。」

「别装成傲娇结果只是在用言语伤人好不好？」

偶尔反击一下，立刻就会变成这样。

听着八幡碎碎念的声音，雪乃轻声笑了出来。

嘴角不受控制地上扬。

她心想，和朋友愉快的交流，果然就是像这个样子吧。

但她并不愉快，这男人也如她刚才所说，不是她的朋友，所以跟她一点关系都没有。比企谷同学，别再硬是插进与你无关的话题了。

隔天放学后，雪乃一如往常来到侍奉社社办，映入眼帘的是一如往常的景色。

「……你为什么还在这里？」

八幡独自坐在社办，盯着手机。

不是要去加入将棋社吗？别再假装看不会有人打过来的手机了。看他可怜，要不要传个讯息给他呢——雪乃如此心想。在这辈子多积点德，好让我下辈子活得坦率一点。呃，不是说我现在就不坦率喔。

「我本来也打算今天过去。」

八幡摇摇头，将视线从手中的手机移到雪乃身上。

「没那么容易就能入社——听说要接受测验。」

「……入社测验？」

八幡在午休时间前去提交入社申请书，结果社长单方面决定测验日期订在后天，叫他改日再来。

「真可惜。亏我还想说总算可以摆脱麻烦。」

「不要用真的很遗憾的语气说好吗……」

仔细一想，这很正常。

只因为太弱这个理由，就把目前的社员当成「不存在」的人，对于想加入的人不可能不设限。

「于是，得知有入社测验的你便夹着尾巴逃回侍奉社……你在做什么？」

雪乃小步走向八幡，从旁窥探手机。八幡在认真观看的，似乎是什么东西的影片。

「干么？你靠好近。」

他吓得向后仰去，雪乃为此感到不满，将脸凑得更近。

要是他在侍奉社看什么下流的影片就糟了。瞧这男人猥亵的眼神，无疑是会做那种事的禽兽。必须尽快检查。内容、类别、偏好、喜欢的类型等等。是黑色长发还是褐色中长发？毒舌冷酷系还是笨蛋小狗系？比企谷同学，你喜欢哪一种？

「让我看看。」

「之后再说。」

「现在立刻给我看。视情况而定，我可能会告你性骚扰。」

「为什么啦，哪里有性骚扰要素。」

雪乃慌张地伸出手，用胸前的某个部位卡住八幡的手臂。

「喂！碰到了……不对，没东西可以碰……」

不知为何，八幡忽然面露忧伤，雪乃抓准这个机会，勉强成功让手机萤幕朝向这边。

萤幕中的是黑色长发的冷酷系美少女……

不对，是一群看起来很内向的黑发眼镜少年。

「……你的喜好真独特。」

「什么东西？」

八幡把手机放到桌上，似乎放弃挣扎了。

「这是那个委托人传给我的。他们跟外校将棋社比赛时的影片。」

「啊，原来如此。哦……」

雪乃揉了下眼角，驱散不良的想像及些许的安心，认真地重看影片。

的确是将棋社社员的影片。

推测是拍来研究用的。不只盘面，连苦恼时表现出的态度、被逼入绝境时使用时间的方式，或是判断局势时有没有不小心表现在脸上，他们下将棋的模样被巨细靡遗拍了下来……的样子。

雪乃看得一头雾水。

这是当然的，因为她对于将棋这个游戏一窍不通。

「你在靠这个影片制定入社测验的对策吗？」

「嗯，没错。」

八幡轻轻点头。

「入社测验的对手是目前的团体战正式选手。每个人当然都有段位，听说还有并不常见的四、五段这种业余高段。」

「段位……？」

雪乃脑中浮现跳箱的层数（注12）。四层的话，小学时期的我应该也跳得过去，毫无难度。

「虽然我不是很懂，以你的程度总会有办法吧？」

「不好意思，我的棋力没强到哪去。我之前差点输给初段的委托人，顶多二、三级吧。」

「级……？」

雪乃脑中浮现英检的等级。二级差不多是高中毕业程度。看来你有资格报考将棋大学喔，比企谷同学。

「我还是没概念。意思是小学生的段，比高中生的级还弱啰？」

「……？」

八幡头上瞬间冒出问号。

「跟年龄无关吧。棋力是绝对的。尤其是高段者。」

「所以比起英文能力，会运动对将棋比较有用。」

「…………？」

八幡头上又冒出一个问号。

「或许吧……毕竟顶尖对决最后好像也是要靠体力决胜负。」

「你连四层都跳不过去的话，要不要加入体操俱乐部？」

八幡头上冒出第三个问号。

「我们是在讲将棋吧？」

「当然是在讲将棋呀。」

「……是吗……」

八幡陷入沉思。

大概是累积至今的人生经验使然，他习惯推测他人的言外之意。连这么直接的对话，都会想去嗅出隐藏在其中的恶意及讽刺的味道，下意识警戒起来。

雪乃心想，这是你的坏习惯。对话节奏是人类的魅力之一。是因为对象是我才有办法忍耐，换成其他人肯定会对你幻灭吧。所以比企谷同学才会不受女生欢迎。太好了。

总而言之——

「你的原则是不做多余的事对吧。」

「嗯？喔，是吗？」

「但你还特地拿了比赛影片来看，观察对手。」

八幡这么做，代表影片里充满比去体操俱乐部训练跳跳箱更重要的资讯。

「我想将棋的战法大概有很多种。像你刚才也有提到三间飞车？这个我听不懂的词汇。所以你是在用这个影片调查对手的战术啰？如果我在乱发表意见，先跟你说声对不起。」

「不，这是目前最正常的意见。」

八幡明显松了口气。

「但你猜错了。到了这个等级，花几百小时研究自己擅长的战术再正常不过。就算我临时抱佛脚制定对策，最后也只会被反杀。」

「那就不行了。」

雪乃有点失望。

「因为我不想看见你输掉。你已经是人生的输家，再不至少在将棋比赛中获胜的话，未免太可怜了。」

「可以不要假装鼓励我其实是在伤害我吗……咦，是说，你要来看比赛喔？」

「怎么可能。与其把时间花在将棋这种地方性的小众游戏上，人生有更多有意义的事。」

「别从根本上否定这件事好不好，会害我想死。」

八幡嘴上说着丧气话，实际上却高傲地晃了下翘起来的腿。

「将棋或许是地方性又小众的游戏没错，不过本质跟人与人之间的交流一样。即使对于制定战术没用，也能看出很多事。打个比方。」

八幡抬起下巴，指向在萤幕最右边下棋的少年。

每下一步棋就会左顾右盼，不安地窥探隔壁的盘面。一和队友四目相交，少年便谄笑着急忙将视线移回自己的棋盘上。

「这坐立不安的模样、注意周遭的方式，跟那家伙很像。」

「……谁？」

「由比滨结衣。」

「会吗……」

雪乃给予模棱两可的回答，八幡没有理会她，手指继续移动。

由比滨（暂定）旁边的社员体型微胖。用戴着露指手套的手掌装模作样地从驹台拿起桂马，以彷佛要把棋盘砸碎的力道下在棋盘上。

「看看这个下出引以为傲的一步棋的男人。超大的下棋声、超吵的咳嗽声、无谓的大笑声，没有一个地方不烦对吧。材木座义辉存在于世界各个角落。」

「呃，嗯，是啊……」

「接着是这位少年。」

材木座（暂定）旁边的社员，身材非常娇小。

他似乎在注意队友的下棋声，扭扭捏捏的，下起棋来十分谨慎。和对手对上目光时，会抬起视线腼腆一笑。

「没错，是户冢彩加。户冢更可爱好不好白痴东西，这家伙和户冢根本不能比。别小看户冢了。」

「……呃……」

户冢（暂定）对面的社员则在不耐烦地抖脚，以粗鲁的手势移动棋子。对材木座（暂定）咂舌，立刻让他安静下来。

「这个自以为女王的态度，怎么看都是三浦优美子。」

「………………」

「虽然他是个平凡的男性啦。现实中的将棋社社员全是黑短发眼镜男。不能抱太大的期望。」

八幡开玩笑似地笑着说。

雪乃回以沉痛的沉默。先不说期望了，她完全不知道八幡看见了什么。所有人都跟本人一点都不像呀……

是因为一直被同学无视，导致他终于将人际关系寄托在陌生人身上了吗？就算只有她一个人也好，或许该对他温柔点。

在雪乃尝到生平第一次的后悔滋味时——

「好。」

八幡咕哝道，关闭手机萤幕。

「大致确认完毕了。」

「……那个……」

你确认了什么？你该确认的是医院的门诊时间喔。

雪乃慢慢移动手，八幡不知道误会了什么，脸上浮现十分阴险的笑容。

「没问题的，雪之下。」

我是没问题。但你的脑袋问题可大啰，比企谷同学。

「普遍认为将棋不会受到运气的影响。这是事实，但不是事实。」

八幡无视雪乃怜悯的目光，接着说道。

棋力是绝对的。

但那只是理论上来说。

如果人类是机器，高中的级位对上小学的段位，胜算近乎于零吧，然而——

「实际上的比赛，手段要多少有多少。」

八幡露出嘲讽的笑容。

真希望他不要在别人为他担心时耍帅。其他人看了搞不好会误会。

看来我还是得去看一下，免得他在将棋社做什么怪事。比企谷同学好歹是社员。别说好歹，已经只剩下歹了，但他还是社员。

雪乃默默做好觉悟。

入社测验的日子到来。

雪乃从侍奉社所在的特别大楼四楼依序走到一楼，终于发现将棋社社办。

为什么会在这么难找的地方？如果有个路痴加上不擅长问路的女学生，肯定会浪费好几十分钟在找路。不对，连不是路痴的我都浪费好几十分钟在找路了，路痴肯定会花更多时间。路痴真可怜。

雪乃有点烦躁地打开将棋社的门。

测验似乎已经开始了。

八幡和将棋社的某人，正在社办角落比赛。

剩下的社员则围在旁边观战，有的人坐着，有的人站着。

「……这个气氛是怎么回事？」

雪乃愣了下。

社员们不知为何——感觉起来杀气腾腾。

雪乃眨眨眼，想寻找异状的源头，离门最近的眼镜男孩惊慌失措地站起来。

「啊，啊，啊！」

大概是在说「是来参观的吗」、「欢迎来到将棋社」。

眼镜男孩说着语意不明的话迅速接近。看来他知道雪乃是侍奉社社员。

「……啊，啊，啊……」

他带领雪乃入座，对她投以求助的目光。

求求你别说是我去委托你们的——

「谢谢，打扰了。」

雪乃回以微笑。她根本不知道这个人是谁。对于一般的女高中生来说，将棋社社员统统都长一样。这是个小知识。

在雪乃眼中，只有正在比赛的八幡看起来跟其他人不同。

他没注意到这边，应该是在专心下棋。跟平常一样，带着宛如死掉的鲷鱼的表情，大胆地面对棋盘。

塑胶棋盘旁边，放着神秘的像电子钟的东西。每下一步棋，八幡就会按下计时器的按钮，换成对手的时间开始倒扣。

「那是什么……」

「啊，啊，啊！」

听见雪乃不经意间的自言自语，眼镜男孩悄声回答「那是棋钟，大会上也会用到的比赛计时钟」。

时间超过十五分钟就算输。遇到千日手（注13）的话先后手替换，以剩下的时间重下一局，和棋的话未满二十七分的那一方输，同分的情况下算先手输，有人给建议当场算输，视总共五场的入社测验的结果判断能否加入。

规则是这样的——眼镜男孩念了一堆将棋咒文，雪乃当然没听进去。

她坐到最近的椅子上，单单凝视着那位特别的参赛者。

坐在八幡对面的将棋社社员，是影片里被他说是「由比滨结衣」型的那个人。虽然雪乃本人无法区分，总之就是这样。

那位由比滨（暂定）看起来非常坐立不安。

明明在比赛，他却四处张望，跟对手四目相交时竟然还露出谄媚的笑。

感觉像要设法改善社办内杀气腾腾的气氛。

「……到底发生什么事？」

雪乃歪过头。

「啊，啊，啊……」

现在是入社测验的第二局，第一局发生了一些问题——眼镜男孩小声回答。

「比企谷同学存在本身就类似问题儿童，不过这个情况有点异常。」

「啊，啊，啊！」

或许吧，他也有他的优点，可是，那个，这次的手段有点游走在犯规边缘……委托人低声帮八幡说话。

雪乃惊讶地望向眼镜男孩。这个人为何一直自己在那边跟我说悄悄话？我的嘴巴没打算跟比企谷同学以外的人说话。

「——唉唷！」

这时，八幡大声惊呼。

这步棋大概是决定胜负的关键，他用力将棋子下在棋盘上的瞬间，不小心力道过猛，弹飞对手的棋子，连着驹台一起掉在地上。

「抱歉抱歉。」

八幡嘴上在道歉，却没去动手捡棋子。

「换你了。」

他若无其事地按下棋钟，连雪乃都看得出盘面乱七八糟，根本不是可以下棋的状况。

比赛已经进入终盘。对手所剩无几的时间一秒一秒减少。

吱吱喳喳——很容易就能感觉到，周围的将棋社社员气得脸色都变了。杀气浓度又提高一阶。

「……啊，啊，啊！」

就是这个，就是这种手段……眼镜男孩低着头说。

第一局他也是用这种肮脏的做法耗光对手的时间，赢得胜利。

也有社员抱怨这样违反礼节，或是帮忙捡棋子，他却说「帮助比赛选手的你们几个，才会违反不能给建议的那条规矩一秒出局吧」，连规则都被拿来利用，得意洋洋地说「赢了就是赢了」……。

「哦。」

雪乃抱着胳膊。

难怪气氛这么糟。

真符合他的作风。在揣测弦外之音的这方面，他可是稀世奇才。他八成会坦荡荡地宣言，是没把规则订仔细的将棋社有问题。

将别人对自己的好感度全数拿去牺牲。

不过本来就没人对你有好感，这个攻击机会实际上等于零成本，感觉挺划算的。比企谷同学，这主意不错嘛。

「好、好了啦好了啦……没关系的，大家别介意。」

由比滨（暂定）露出讨好的笑容，以安抚杀气腾腾的同伴。

他说着「没关系没关系」，连忙趴下来捡起掉在地上的棋子。

掉在八幡脚边的棋子则因为他的脚挪都不肯挪一下，费了好一番工夫才收集起来。

「啊哈哈，那换我下啰……」

由比滨（暂定）却半句话都没抱怨，只是苦笑着说。

对于把察言观色这个技能点满的由比滨（暂定）而言，如何收拾局面应该比输赢更加重要。

尽管完全无法集中精神，他还是急忙重新排好棋子，将放回驹台的棋子下在适当的位置。

下一刻——

「好，我赢了。」

八幡说。

「……咦？」

由比滨（暂定）愣了一瞬间，战战兢兢地回问。

八幡指向他刚放到棋盘上的棋子。

「你算算看。那是第五个香车。你犯规了。」

「——咦？」

由比滨（暂定）用不同的语气说出同一个字，瞪大眼睛。

雪之下也弯起手指计算。角落一个，上面一个，比企谷同学那边两个，刚才下的一个。原来如此，确实有五个。将棋这个游戏是凑到五个一样的算输吗？看来规则跟扑克牌有点出入。

「怎、怎么会……啊、啊啊，刚刚的⁉」

由比滨（暂定）似乎发现了什么，指向八幡脚边。

「我就想说怎么会掉在那种地方！这该不会是你带进来的棋子吧⁉故意弄掉棋子，让它们混在一起，害我看不出来……！」

「我不知道。」

八幡耸了下肩膀。

「啊，啊，啊！」

社员们的怒吼声四起，眼镜男孩小声地说。

那是在以前的将棋道场必定会看见的大叔战术，偷偷从旁边的棋盘拿走棋子……让对手在不知情的情况下这么做，诱导人犯规吗？如果是外面的比赛，绝对会出问题，竟然想得到如此恐怖的计策……

然而雪乃还是一样，听不太懂他在说什么。

确实有那种提到感兴趣的领域，话就会突然变多的人。这人应该很喜欢将棋。

入社测验继续进行。

将棋社社员为是否要承认刚才的比赛结果争论了一番，由比滨（暂定）苦笑着说「犯规就是犯规……」他们便勉为其难接受了。

更重要的是——

「呵哈哈哈哈！战友被干掉了吗……不过，那两个人在我们将棋五虎将之中是最弱的……竟然输给这种货色，真是丢光了将棋社社员的脸！」

第三位对手非常有干劲。

八幡看影片时说他是材木座（暂定）型，雪乃依然无法区分。但她觉得有那个味道。

「呼呼呼……禁忌棋子的操纵者啊，若你以为我和刚才那两个人一样，就大错特错了。你那卑劣的计策，对本人五虎将首领——振穴将军可不管用！」

材木座（暂定）用戴着露指手套的手摆出十字架，哈哈大笑。

「……啊，啊，啊……」

眼镜男孩说，事实上，以他们的棋力，应该不会算错手上的棋子有多少。

除非跟刚才的对手一样，完全无法集中注意力……不过现在这个对手虽然有点吵，下棋时的专注力却是全社团最高的。

不出所料，比赛似乎以材木座（暂定）的步调进行。

八幡一直盯着棋盘苦思。明明轮到他下了，他的手却一直没动。看来现在的他没有余力弄掉棋子。

「看到我的飞角二刀流，怕了吗⁉你再怎么烦恼，都无法攻破我那有如铜墙铁壁的四穴熊金刚城！呼哈哈哈哈哈！」

材木座（暂定）已经在为胜利欢呼。不管在哪个世界，材木座（暂定）都很吵。

雪乃盯着八幡的侧脸。她不懂将棋，八幡果然处于劣势吗？看他不停搔头沉吟的模样，总觉得不像平常的比企谷同学。太不自然了，真无趣——

……不对？

由于太不自然，雪乃歪过头。

仔细一看，八幡的嘴角微微扬起。其他人都没发现，但雪乃看得出来。不，这样讲好像他们之间有什么特别的羁绊，好羞耻。比企谷同学总是像这样在我身上寻求真正的理解，伤脑筋。

「下啊，下啊，怎么啦怎么啦！你的力量就只有这点程度吗！」

材木座（暂定）完全没发现这个小细节，不断愉悦地大笑。

然后像突然想到什么似的，望向棋钟。

「呃啊啊啊啊！」

大惊失色。

正在减少的，是材木座（暂定）的时间。

「啊，啊，啊……」

眼镜男孩喃喃说道「他忘记按棋钟了」。那个人常因为太专注在盘面上，下完棋就忘记按自己的按钮。

不过，通常对手都会提醒。偶尔——真的是偶尔——会有明知道对手没按棋钟却不下下一步棋，一直等对手的时间减少的人……

「卑、卑鄙小次郎！竟然不敢跟我堂堂正正一决胜负！」

材木座（暂定）现在才着急地按下按钮，可惜为时已晚。

只要有持子时间用完就算输这条规则，局势再怎么对自己有利都没关系了。

即使他将一直只选择拖延时间的下法的八幡逼入绝境，也无法挽回失去的时间。

「好，我赢了。」

通知时间耗尽的铃声响起。

「下、下一个是我。请多指教……」

第四名对手户冢（暂定）非常紧张。

看起来是在想八幡这次会做什么，担心过头了。

雪乃摇摇头。

这样不行。被这个野蛮的男人看见你破绽百出，不用想都知道他会用什么手段凌辱——

「——哈啾！」

「哇！」

果然，一瞬间就分出胜负了。

户冢（暂定）拿起棋子的瞬间，八幡打了个大喷嚏。

他的手抖了一下，棋子不小心掉出来，滚到跟本来想下的地方不同的方向。

「你走两步。是我赢了。」

八幡理所当然似的宣布胜利。

「各位，抱歉……我没打算那样下的……」

户冢（暂定）咬着下唇跟其他社员道歉。

那双大眼盈满豆大的泪珠，讲话抽抽噎噎，都快哭出来了，将棋社社员纷纷轮流安慰他。

户冢（暂定）在这个社团中，肯定也是吉祥物般的存在。

他们一下叫他不要放在心上，一下说八幡不遵守礼节。

社员们温柔安慰输给卑劣手段的同伴，频频瞪向八幡。若要尽量用委婉一点的词汇形容——就是充满污蔑及憎恶吧。八幡毫不介意从四面八方刺在身上的视线。

仅仅是孤高、超然地，稳稳坐在针毡上。

比企谷八幡这个人，总是活在这样的世界中。

明知道自己不对，还刻意选择不正确的做法，以导正只会走在正确道路上的将棋社。

雪乃心不在焉地想。总觉得——那是非常纯粹的人生态度。虽然她不知道原因，也绝对不想代替他的位置，不知为何就是这么觉得。

「——无聊。」

远方传来不屑的骂声。

围住户冢（暂定）的社员惶恐地让开一条路。

他们的行为意味着，声音的主人是将棋社绝对的统治者。

「垃圾在那边互舔伤口，输了就是输了吧。但我<本小姐>不会承认的。」

是三浦（暂定）型。

团体战的主将兼改变社团气氛的女王蜂……他当然是男的。也不会像三浦那样用「本小姐」自称。

搞不好是因为比企谷同学的关系，导致我的眼睛跟耳朵也出问题了。雪乃感到愤怒。我要你负起害我身体产生变化的责任。

「赢了我，我就同意你入社。如果你输了，就不准再踏进这里。」

三浦（暂定）语气尖锐，锐利如刀刃的视线忽然落在雪乃身上。

「——你也是。」

正确地说，不是雪乃——

「啊，啊，啊……」

她旁边的眼镜男孩像被刺中一样，瑟瑟发抖。

他知道是我找他来的？怎么会。那我之后该怎么办？

这么频繁地跟雪乃说话，自然会被怀疑跟侍奉社有关系。你也该发现我都没在回话了吧。

「好了，快把棋子排好。」

一将棋子放回初期配置，三浦（暂定）就忽然高高举起棋子。

没有问候，也没有宣布比赛开始。

第一步棋就用力砸在棋盘上，将八幡的棋子远远弹飞。紧接着拉倒隔壁的桌子，让其他棋盘的棋子也掉在地上，跟原本的棋子混在一起。

然后按下棋钟，开始倒数计时。

那卑鄙的举动——无疑是八幡刚才对社员做的事。三浦（暂定）直接将八幡的挑衅原封不动地还给他。

面对惨不忍睹的棋盘，八幡摇摇头。

「……原来如此，原来如此。」

「你有意见吗？」

「没啊？怎么可能有。这样就对了。」

三浦（暂定）瞪着八幡，八幡嘴角扯出扭曲的笑容。

「啊，啊，啊……」

脸色苍白的眼镜男孩吓得嘴唇都在打颤，依然做好了解说员的工作。

刚才的社员也都有段位，但这个人是特别的。业余五段，还做为高中生的千叶县代表参加过全国大赛。以我的等级，就算他让我飞车和角这两个棋子，也会输得很惨。

雪乃完全是左耳进右耳出，不过千叶代表这头衔挺帅的。只要冠上千叶代表四个字怎样都帅。例如千叶代表猫咪，真是太棒了。可惜现在不是想那些的时候。

极其偶然的情况下，会有优先顺位比猫更高的事。

例如——欣赏眼前这场化为激烈互殴的比赛。

三浦（暂定）八成是相当好胜的人。

八幡下棋的瞬间，他会迅速接着下。弹飞他的棋子，用力拍打棋钟，不管在棋盘上还是棋盘外，都正面回击八幡卑鄙的计策。

以眼还眼，以牙还牙，以猛毒攻猛毒。

「……啊，啊，啊……」

没救了——眼镜男孩嘀咕道。

棋力差距太大的对手对自己使出同样的手段，不可能赢。

「——4五桂喔，4五桂。」

再加上就算八幡将他的棋子远远弹飞，三浦（暂定）也会立刻开口。无法亲手将棋子下到棋盘上的话，用指的说出自己要走哪一步棋也可以，正式规则有这么一条，的样子。

八幡则不能如法炮制。以他的棋力，非得把棋子放回棋盘上才能想下一步棋。因此他的时间一定会比三浦（暂定）更紧凑。

三浦（暂定）下的棋，确实是最适合将死八幡的下法。

啪，啪。每当棋子掉落、棋钟摇晃，社员们都会大声嚷嚷。

逼死那个异类。打倒那个卑鄙小人。

啪，啪。每当拳击般的敲打声响起，社员们都会握紧拳头。

排除不正确的东西。在他走上正确的道路前别让他加入。

雪乃对将棋一窍不通。

可是她看得出来，八幡真的陷入苦战。

他的身体在微微晃动。眼球充血，脸颊发红。在受到这么多人抨击的情况下孤军奋战。

输掉吧。输掉吧。输掉吧。不正确的家伙给我输掉吧。

听着将棋社社员激情的大合唱，置身于惊人的疏离感之中。

「……比企谷同学。」

雪乃下意识握紧双拳。

就算全世界的人都排挤你。就算全世界的人都对你不抱期望。

我——就我一个人，偶尔也不是不能诚心为你祈祷。

比企谷同学。即使你性格乖僻，不受欢迎，仍然是我的——只属于我的，比企谷同学。

——加油。

这时，所有的声音都消失了。

比赛结束。

再怎么看棋盘，雪乃也看不出是谁赢了。计算了一下，没有凑齐五张牌的样子。还能怎么分胜负呢？

雪乃连忙左顾右盼。

「……？」

然后疑惑地歪过头。

身边的将棋社社员，看起来也都搞不清楚状况。

众人都目瞪口呆，只有一个人。

「我还没下。」

只有八幡脸上带着浅笑。

「……啊？什么？」

三浦（暂定）惊讶地回问，八幡当着他的面拿起角落的步兵。

敲在棋盘边缘，格子外面的地方。

「我只是假装有下，棋钟也只是拍了按钮旁边而已。」

那个动作在对方眼中，怎么看都是下完棋了。三浦（暂定）原本就判断这是场跟时间的竞赛，两人跟拳击一样正在高速互殴。

因此他才迅速下了下一步棋——

「你等于连走两步。是你输了。」

「——什么⁉」

「这样我的入社申请就通过啦。以后请多指教。」

三浦（暂定）气得脸色发紫。是危险的颜色。

「你这人，到底有多卑鄙！」

他踹倒椅子，抓住八幡的领口。没人阻止得了他。不可能去阻止。因为社员都跟三浦（暂定）有同样的心情。棋子多出来、时间耗尽、连走两步，尽是用卑鄙的手段引人犯规，笑着接受的人才奇怪。

正当他激动地举起拳头——

「好了，到此为止。」

鼓掌声传来。

众人反射性望向门口。

将棋社的顾问站在那里。不知道什么时候来的。

他穿着与修长身躯相衬的整齐西装，缓缓走到社办中央。是会自然而然引人注目的人种。三浦（暂定）立刻安静下来，大概是社员也对他另眼相看。

用八幡的说法，就是叶山隼人（暂定）型吧。那名顾问又拍了一次手，这次是为胜者献上掌声。

「分出胜负了。到此为止。真是场有趣的比赛。」

叶山（暂定）直盯着八幡，对他微笑。

「你是叫比企鹅同学？你的棋力我没有仔细确认过……但我认为你为今天的比赛认真锻炼过。你很强。应该能变得更强。」

然后像理解一切似的，瞥了眼镜社员一眼。

「不过，他说得没错。将棋是在跟对手对话。胜利就是正义，但并不代表正义之人什么都可以做。你是想表达这个意思，才下了『叫比企鹅同学过来』这步妙棋对吧？」

「啊，啊，啊！」

「将棋棋手没有力量就无法生存。可是，光有力量不具意义。看来我的指导方针有问题，真对不起大家。」

平静的声音，温柔地传遍社员们的心。

他们眼泛泪光，双手握拳，自然聚集到叶山（暂定）身旁。

顾问环视众人，微微一笑。

「我们大家都输了。所以，要不要现在开始重来一遍？」

「啊，啊，啊……」

「因为——真正的将棋是非常有趣的！」

所有人都欢呼出声。

三浦（暂定）、户冢（暂定）、材木座（暂定）、由比滨（暂定）一起抱住叶山（暂定），又哭又笑，有的人跟对方道歉，有的人跟对方重修旧好。

高洁正确美丽，青春的一切都浓缩于此。

五战全胜的八幡身边，没有半个人。

「……回去吧。」

八幡跟平常一样，理所当然似的，独自起身离去。

委托人说他改天会再来郑重为此事道谢。带着所有社员拜托八幡「求你千万不要加入将棋社」的道歉信。

唯有眼镜男孩带过来的将棋盘和棋子留在侍奉社社办。

似乎是一点心意。

在那之后，八幡从来没碰过将棋。

亏他那么努力……亏他实现了我的祈愿。

她仅仅是觉得棋盘放在社办桌上的角落积灰尘很可惜，心里完全没有一丝鼓励或安慰之类的心情——

「偶尔要不要下一局？」

雪乃停下在翻阅书页的手，瞄了八幡一眼。

「……跟你？」

「不要就算了。」

雪乃并未说明理由，因此八幡歪过头，接着移开视线。

「……好吧，也不是不行。」

他没有多问，轻轻点头，着手将棋子排成初期配置。

雪乃也有样学样，笨拙地排好棋子。凑到五个步兵算输对吧？

「那，请多指教。」

「嗯。」

她彬彬有礼地低下头，头上传来简短的回应。看他没打算找棋钟，这次他似乎愿意好好下棋，而不是引诱人犯规。

雪乃发着呆等待，八幡露出「我先吗？」的表情。没错，你先。因为我其实不太懂将棋。

只知道八幡之前说过的那句话。

『将棋到头来就是只凭实力说话的游戏。』

跟弱者下棋没有意义。跟连规则都不懂的雪乃下棋，八幡也得不到任何好处。

既然如此，这段时间又是什么？

我纯粹是心血来潮，完全没有深意。

他又是怀着什么样的心情陪我下将棋的呢？

「……呵呵。」

雪乃轻轻摇头。

想也没用。因为我们的青春无时无刻都走在错误的道路上。

雪乃不知不觉间露出柔和的微笑。

一直，一直等待他的那步棋。

10注  将棋战法的一种。

11注   《果青》日文版的出版社。

12注  跳箱层数及将棋段位，日文皆写成「段」。

13注  指同样的走法重复四次的情况。

** 雪之下雪乃和比企谷八幡出乎意料的第一次上台演出

作者：天津向／插画：うかみ

我，比企谷八幡边走边烦恼。理由要追溯到不久前在教职员办公室的对话。

一走进教职员办公室，平冢老师就对我招手。

「你来啦。」

「您有事找我，我当然会来。不过看您的表情，我知道不会是什么好消息。」

「是吗？既然你已经知道，那就好说了。」

平冢老师毫不在意我最高级的讽刺，从桌上拿起一张纸递给我。上面写着「地区亲睦会举办通知」。

「呃……请问这是？」

「就算是你，光看这个也看不出来吗？」

「那当然。于好于坏您都对我评价过高了。」

平冢老师把手撑在桌上，露出「是喔」的表情，我看不出她的真意。

「市内要召集当地的小孩举办亲睦会，我接获委托，希望侍奉社的人帮忙表演某个节目。」

原来如此。听起来真麻烦。

「表演啊。为什么非要由我们来？这种东西要由专业人士负责才行，外行人来弄会死得很惨，这可是定论喔。」

「别一开始就否定。听我说完。」

「那个表演是人偶戏之类的吗？由比滨感觉很擅长那种东西。雪之下大概也不会不擅长。」

「别巧妙地排除掉自己。」

唔唔，果然被抓包了。或许就是因为于好于坏她都对我评价过高，才会导致我动歪脑筋的时候被发现。

当事人平冢老师一副「你在想什么我都看穿了」的态度，面不改色地看着我。

「而且对方想请你们表演的不是人偶戏，而是搞笑节目。」

「……搞笑节目？」

我讶异地回问。不，如果真的是字面上的意思，她刚才说的可是最糟糕的委托。

「没错。以漫才、短剧、单口相声、落语等等广为众人所知的那个搞笑节目。」

「原来如此。那比起侍奉社，找落语研究会之类的应该更适合。所以我先告辞了。」

我正准备转身走出教职员办公室，手臂就被人用力抓住。

「比企谷，你也知道吧，我们学校没有落语研究会。」

「咦？是吗？在我知道的世界观，本校好像有落语研究会、漫才研究社、短剧社等社团喔。」

「你再怎么穿越时空，这件事要麻烦你们侍奉社的事实都不会改变。」

听见她的觉悟，我垂下肩膀，放弃挣扎。大叹一口气转过身，平冢老师微微扬起嘴角看着我，彷佛看穿了我的心情。

「那老师，我想针对这件事直接问您几个问题。」

「好啊。」

「为什么要帮侍奉社接下这起委托啦！搞笑节目是什么鬼！我们根本没经验！」

我提出听见这件事时就产生的疑惑，眼前的老师却依然神情自若。

「没经验不代表不适合。」

这什么薛丁格的想法。「没试过所以无法判断适不适合」，太不合逻辑了。

「而且比企谷，你之前不是说过吗？」

「我？」

「看到班上的同学在闹，你说『那种人就是会觉得自己很搞笑，试着表演漫才，结果把气氛搞得超尴尬啦，活该w』。」

……糟糕。我想起来了。肯定是户部那群人。那些家伙觉得在耍白痴的自己任谁来看都会觉得有趣，我为此感到不满。

「接到这起委托后，我稍微调查了一下『搞笑表演』，看来『搞笑』这种事比起开朗的人，内心阴暗的人更适合。既然如此，我想委托我心中阴暗、阴沉人类的代表比企谷率领的侍奉社帮忙。」

「阴暗的人比较擅长搞笑」这个说法是有道理的，某位不断想出创新笑点的艺人曾经说过，这是因为阴暗的人会从扭曲的角度看待事物。所以我明白这个道理。但性格阴沉跟这件事一点关系都没有吧。

「总之，我已经跟人家讲了，侍奉社会负责表演某种搞笑节目。」

「原来是先斩后奏啊。」

「客人是町内会的小学低年级生到中年级生，男女约三十人的样子。日期是两周后。交给你们啦。」

事已至此，平冢老师是不会退让的。没办法。哎，找由比滨商量看看吧。那家伙搞不好会兴致勃勃地说「漫才！不错呀，试试看吧试试看吧——！」。搞不好还会顺势说出「我来讲单口相声——！」减少我的负担。哇，如果她真的这么做，由比滨根本是女神。我要推爆她。

我边想边走向门口，平冢老师远远对我举手。

「对了！万一人家说侍奉社的搞笑节目有够烂，害我们未来的学生变少就糟了，所以无论如何都要让表演大成功喔！完毕。」

她在最后塞了个大难题过来。

我思考着该怎么处理这个强人所难的委托，走向侍奉社社办。因为我认为，最好将我现在的心情如实告知其他成员。我一口气拉开门，看见由比滨在里面滑手机。

「啊，自闭男。嗨啰——」

「嗨，你跟平常一样忙着滑手机呢。」

「对呀——收到一堆简讯。可不可以等我一下？有简讯要回。」

我望向正在用双手回简讯的由比滨，心想「现充得花真多时间跟人交流」。我坐到由比滨对面，等待她跟朋友传简讯玩完确认游戏。

「这样就都回完了。」

「朋友多也很辛苦呢。」

「你在讽刺我吧。」

跟我相处久了，现在她也能听出我的言外之意。我发自内心感慨。

「跟她们当朋友，我真的很开心，你应该一辈子都不会明白就是了。」

「是吗？我只是无法接受又没有深交，就只有在那边互传讯息道早安的这种关系而已。」

「你想太多了啦。像我们刚才就约好之后要去购物中心玩。」

我听了更加畏惧现充这种生物。半强制性地被迫跟仅仅是碰巧同年碰巧同班的人打好关系，连假日都不得不一起度过，根本是苦行。上辈子到底造了什么孽才要受这种苦？我深深叹息。

「自闭男，你在想什么都反映在脸上了。」

由比滨眯眼看着我。

「是喔。那你知道我在想什么吗？」

我盯着由比滨。由比滨立刻别过头，大概是受不了我的视线。

「不要盯着我看……」

「干么？这么不想被眼神凶恶的人盯着看？」

「我又没那样说！」

由比滨鼓起脸颊否认。是吗？那就好。虽然是我自己说的，如果她真的不想被我盯着看，我会难过得要命。

「先不开玩笑了。刚才平冢老师跟我说，有人委托侍奉社在为当地的小孩举办的亲睦会上表演搞笑节目。」

「咦？什么东西？听起来超有趣的。」

果然跟我想的一样，由比滨很感兴趣。

「对吧？你也有一两个喜欢的艺人吧。」

「嗯！我喜欢那个艺人！会用『金滴不好意素』道歉的人！」（注14）

举了个比想像中还冷僻的例子。是说那是很久以前的搞笑艺人耶。听说他现在仍在努力。

「这可是能跟你喜欢的艺人做同样的事的宝贵机会。你有兴趣的话要不要试试看？」

「好呀！我要！什么时候？」

「两周后的星期六。」

「两周后的星期六是吧！那就是下个月月初的……啊。」

始终面带笑容的由比滨面露忧郁。

「……抱歉，那天可能不方便。」

「怎么了吗？」

「我跟人有约了。」

由比滨秀出手机萤幕给我看，上面写着——

『那就决定下下礼拜六，大家一起去逛那家购物中心啰！不准像之前那样拒绝。』

寄件人贴心地写着「优美子」。肯定是三浦优美子。由比滨嘿嘿苦笑。

「这……非去不可吗？」

「这还用说！她都说不准拒绝了。」

「呃，我知道……但这不是搞笑时会故意在那边『装』吗？」

「装？」

由比滨歪过头。

「我之前看到一个搞笑艺人在电视节目上说，叫人不要推的时候，反而是要人推他。跟这是同样的道理吧？」

「当然不同！优美子才不会跟搞笑艺人想的一样！」

由比滨摇头否认，看她这个反应就能知道三浦是什么个性。好吧，总之就是这样。

「真的是刚才那封简讯才决定好日期的，时机真不巧。」

明明有这么有干劲的人，时间却对不上，我难以服气，但这也没办法。冷静一想，由比滨喜欢的搞笑艺人是「Desuyo。」，再加上她听不懂我刚才说的「装」，上了台说不定也只会冷场。

「真的对不起！」

由比滨双手在面前合掌。我告诉她「没关系」，吸了口气，做好觉悟。

嗯，来想单口相声的剧本吧。

我和由比滨道别，离开侍奉社回到家，在房间对着笔记本沉吟，想单口相声的剧本。选择单口相声的理由只有一个。由比滨没空。这样就只剩下雪之下。可是雪之下不可能接受这起委托，那就由我来讲单口相声。照理说，这是最有建设性的解决方式。虽然我很不甘愿。真的很不甘愿。超级不甘愿。

然而，对着笔记本思考了两小时，我惊讶地发现自己什么都想不到。咦？剧本要怎么写？「好笑」是什么？想得出梗的搞笑艺人该不会都超有才华的吧？搞笑艺人真的厉害到只能以尊敬两字形容！

……就算我这样想，值得尊敬的搞笑艺人也不会帮我写剧本。

不过仔细一想，要表演的又不一定要是我写的剧本。对象是小学生。表演给小学生看的梗，会让他们觉得「啊，那个梗我看过喔」吗？不，不可能。

好。

去抄别人的吧。

一下定决心，我就用电脑打开影片投稿网，寻找默默无闻的单口相声演员的影片。既好笑，又带有看起来像高中生所写的粗糙之处的剧本……

我用电脑找了一小时左右，找到一个不错的剧本。内容是不知名的艺人以「沙包」的身份故意讲惹人厌的话，让别人揍自己。就是它。感觉很像讲话惹人厌的我会想出来的剧本，这个梗也有逻辑性。

我看了好几次那段影片，把台词写到笔记本上。一写完就马上看着笔记本开始练习。

「我是沙包。随时可以揍我。那我要上啰……你穿的衣服全是你妈在义卖会买来的吧？咚！」

我像影片一样做出被打的动作。嗯，不错喔。感觉会受欢迎。

之后，我不断拿这个剧本练习。练习了好几次。

练习得愈多次，我心中的疑惑愈来愈强烈。

这个梗好笑吗？

光看影片是挺好笑的，但我愈是练习就愈无法判断是否真的好笑。我觉得这很有趣，可是会不会只有我一个人这么认为？莫名的孤独感折磨着我。

「如果有人能帮我看看就好了。」

不过现在这时间能帮我看的人……

不。只有一个。虽然不知道会被说成什么样子，为了缓解我的不安，还是让她看一次比较好。

我如此心想，走出房间。

「哥哥，小町觉得那个梗一点都不好笑。」

看完我的表演，小町开口第一句话就让我心灵受挫。

「呃，哥哥突然叫小町看你表演的时候，小町还在想『这个人在说什么啊？』怀疑哥哥脑袋有问题，看完后小町还是觉得哥哥脑袋有问题。这是什么？某种惩罚游戏吗？」

「不是惩罚游戏，但类似。」

「小町不懂哥哥的意思。不过改成更容易受小学生喜爱的内容会比较好吧？还有，你说这是惩罚游戏，但被惩罚的反而是要看哥哥表演的小町喔。」

虽说不是自己想的梗，被人批得一文不值，还是会非常沮丧。艺人都得承受这种批评吗？竟然得面对这么不负责任的批评，搞笑艺人真的厉害到只能以尊敬下略。

「哎，虽然不知道哥哥为什么在做这种事，劝你开心一点比较好。不要摆着一张臭脸。小町觉得这样分数比较高。」

我开不了口告诉小町「我有在刻意露出笑容耶」。

隔天放学后，我一面思考「剧本要怎么办呢」，来到侍奉社社办，雪之下站在里面看书。

「辛苦了。」

听见我的声音，雪之下抬起头，一句话都没说就把视线移回书上。

「不要无视我。我会受伤。」

「哎呀，这样啊。我还以为这点小事你已经习惯了。」

「习惯归习惯，还是会难过。」

雪之下阖上书望向我。今天她的表情也一样冷静严肃。

「你昨天没来。」

「老师有事找我帮忙，所以我去了那边一趟。是以侍奉社的身份进行的活动，所以不成问题。」

「哦——是喔。」

雪之下用锐利的视线看过来，我被她的气势震慑住，忍不住移开目光。

「由比滨同学呢？」

「在教室跟同学聊天。他们聊得很起劲，可能会晚点才来。」

「是吗？那么最好趁由比滨同学不在的这段期间解决。」

雪之下这句话害我有点紧张。什、什么东西？

「比企谷同学。」

「干、干么？」

雪之下平静地说，看起来异常成熟，我的心跳瞬间加快。

「让我看看你想到的梗吧。」

「……梗？」

这个怎么想都不可能从她嘴里说出来的词汇，使我大吃一惊。

「梗，是指那个梗吗？」

「对。是用来搞笑的梗。不是寿司的馅料。」（注15）

「感谢你贴心的说明——不是啦。你怎么知道我要表演？」

「我不是说昨天老师找我吗？」

听雪之下这么说，我明白了。

「那个老师是平冢老师啊。」

「没错。然后，她还跟我说了之后要办亲睦会。」

原来如此。既然她已经知道，那就好说了。

「是说，你愿意帮我看喔？你喜欢搞笑节目吗？」

「不，并不喜欢。几乎没看过。但我想看看你打算表演什么。」

所以是完美超人雪之下雪乃的好奇心使然啰。

「总之谢了。我也正好想表演给其他人看，看看他们的反应。」

讲到这边，小町昨天的反应闪过脑海。

「不过比起严格地审视，我比较希望你抱持着在看有趣的东西的心态。」

「说得也是。毕竟你等等就要表演有趣的东西逗我笑。没问题。」

这女人在提高难度，不晓得是不是故意的……也罢。难度提升到这个等级，我反而无所畏惧了。

「那我就来表演一下。短剧《沙包》。」

「……就这样，今天沙包的工作到此结束。谢谢大家。」

我低头一鞠躬，雪之下送上寥寥无几的掌声。我抬头擦掉额头的汗水。不是热出来的，这些全是冷汗。

因为雪之下在我表演的期间表情都没变过。谁来看都称不上笑容。

好，别问她感想了。反正早就知道会受伤，何必多此一举。任何生物都明白这个道理。

「好，表演完了，那我回去——」

「挺有趣的。」

「不用跟我说感想……咦？」

我没想到雪之下的感想会是这句话，为此不知所措。

「等一下。你刚才说有趣？」

「嗯。我觉得挺有趣的。至少对我来说。」

「真的吗？」

我高兴得不小心提高音量。

「具体上来说，是哪些地方有趣？」

「这个嘛，沙包这个设定有点老，不过让人打的理由是惹火对方，这个主意满好的。沙包的台词很有真实感，观众容易引起共鸣，这一点我也觉得不错。」

嗯，夸人有必要说得那么复杂吗？简单地说就是这个部分和这个部分不错嘛。虽说不是我自己写的剧本，真没想到被人称赞会这么高兴。

「你评价这么高我很高兴，可是你完全没笑耶。」

「哎呀？是吗？我还以为有表现在脸上。就算我没笑，我很赞赏你把这个梗写成如此完整的剧本。」

雪之下淡漠地说明。她不是会奉承人的个性。既然她这么认为，应该是真的觉得有趣。

「那你还有其他看法吗？具体上的批评之类的。」

「噢，这个嘛。嗯——就我看来，总觉得有点说明不足。如果有人能帮忙做出反应，解释现在是什么状况，应该能更加明确地将主旨传达给观众。」

雪之下又讲得这么复杂。我边想边咀嚼她想表达的是什么意思。

「也就是说……有个人在旁边说明就行了？」

「有的话，观众应该能理解得比较快。」

我脑中浮现一个问题，不如说可能性。说不定雪之下会答应这个提议。

「雪之下，我有个提议。」

「什么？」

「方便的话，可以在这个搞笑节目上——」

「不要。」

「反应太快了！你还没听我说完吧！」

看我这么激动，雪之下叹了口气。

「我知道你要说什么。八成是要我跟你一起表演搞笑节目对吧？」

「嗯。可以当我的搭档，跟我一起上台吗？」

「为什么我要做那种事？我拒绝。」

雪之下一副这个话题到此结束的态度，再度翻开书，视线移回书页上。糟糕。怎么办？

老实说，雪之下的意见我深有同感。看到这个短剧的影片时，我也觉得如果有个人负责吐槽会比较好懂。都练习到这个地步了，我不希望场面被我搞僵。如果雪之下愿意帮忙是最好的，我该怎么做……

「这样啊这样啊。眼前有人需要帮助，雪之下同学却不肯伸出援手。」

我用显而易见的言词刺激雪之下。然而，雪之下决定无视一切。

「真想不到。我还以为你是会稍微帮一点忙的人。这样啊这样啊。明明有解决方案却不去做，你的器量就只有这点程度。」

「……这话什么意思？」

好，上钩了。雪之下很强。正因为很强，有解决方案却不付诸实行这种事，她应该做不到才对。

「而且这不是我一个人的问题。孩子们照理说都在期待这场表演。考虑到他们的心情，不觉得很可怜吗？」

我故意垂下肩膀。我演得很烂已经没差了。重点在给予情报。不出所料，雪之下不知何时阖上了书，双臂环胸。

「……原来如此。既然是为了孩子们，那就没办法了。我也来帮忙。」

「真的吗？谢谢。」

「不过，我完全不懂搞笑，这部分你要负责想办法。」

「好。那我演一遍刚才的短剧，你即兴吐槽一下。」

「吐槽就是否定，或是补充的意思对吧。知道了。」

好严肃的解释方式，没问题吗？她行吗？不过头都洗一半了，也只能试试看。

「短剧《沙包》。」

「现在他要带来的，是『短剧』这个独自为各位带来欢笑的表演。」

「欢迎光临。噢，我是做沙包的。」

「所谓的沙包，是指以一次一百元的定价让人殴打的人。话虽如此，并不是真的要被打，通常也可以躲开对方的拳头。因此大多数都是由退休后的拳击手担任。至于这个行业的起源——」

「太长了太长了太长了！」

我受不了，制止雪之下说明。

「现在是在演短剧，不必把沙包说明得那么细。」

「为不知道的人说明比较贴心吧。」

看到雪之下露出「干么阻止我？」的表情，我明白她是真心这么认为。原来如此，她对搞笑一窍不通到这个地步。

「放心，用不着讲这么多观众也听得懂。那继续啰。你也要加进来演。」

「照这个设定对吧。知道了。」

雪之下同意了，因此我继续表演。

「总之要不要揍我看你自己。要试试看吗？」

「说起来，你现在在桥上做生意，有先跟警察征求许可吗？」

「咦？」

我回问。

「这种事情如果不跟警察申请道路使用权的话，真的会违法，请问你有先去申请吗？」

「呃，我说，雪之下。」

「你自己要触犯法律做什么事，是你家的自由，但我觉得把其他人牵连进去不太好，这部分请你多加留意。」

「你还没动手我就被骂到遍体鳞伤了！」

我放声大吼。

「短剧的内容完全不一样！变成抢走沙包的工作痛骂他的剧情了！你在干么啦。」

「我只是在说明理所当然的常识。这就叫吐槽吧？」

竟然会直接见识到雪之下在这种意义上的深闺大小姐感。我有点想笑。

「不是吗？」

她不安地询问，我慢慢摇头。归根究柢，要和对搞笑只有这点知识的人一起表演，根本不可能。

「没事。是我不该找你帮忙。我一个人来就好。谢啦。」

每个人都有做得到和做不到的事，跟叫乌龟跑快一点也没用，叫马长出翅膀飞天也没用一样。对雪之下来说就是吐槽，仅此而已。

「那我先回去了。」

「……」

雪之下头低低的，没有看转身离去的我一眼。

隔天放学后。我收拾好东西，打算今天直接回家，走出教室时发现雪之下站在门口。

「喔。怎么了？找由比滨有事？」

「不是。我要找的是你。」

「找我？」

「等等到侍奉社的社办。这是命令。」

说完她就快步走向社办……咦？什么啦，什么命令啦。算了……去就去。

我跟着走向雪之下前进的方向，然后拉开侍奉社社办的门，回头一看，雪之下气势汹汹地站在眼前。

「我来了，你要干么？」

「演短剧给我看。」

雪之下的回答再度出乎意料，我的大脑都跟不上了。

「什么意思？」

「再演一次昨天的短剧。」

「为什么啦，莫名其妙。」

「别问那么多，演就对了。」

看她这么顽固，演短剧似乎是强制事件。没办法。我站到雪之下面前，清了一次喉咙。同样的短剧再演一次，很难逗人发笑吧。

「那开始啰。短剧《沙包》。」

「沙包是指收钱给人打的人。」

「欢迎光临。我是做沙包的。钱我会收下，不过揍不揍得下去就看你自己了。要试试看吗？」

「好呀。我刚好心情不好，让我试试看吧。」

雪之下慢慢站到我面前。

「可是要你揍不认识的人，你也揍不下手吧。所以我会说一些让你比较揍得下去的台词，你听了后再试试看。」

「知道了。」

「那我要说啰……咦？你的头发是不是剪坏了？没有？不不不剪坏了啦！绝对剪坏了啦！」

语毕，雪之下的巴掌用力往我脸上搧过来。因为她实在太认真，我拼命闪了开来。

我们照这个感觉继续演下去，我勉强闪掉一次又一次的巴掌，平安演完这出短剧。我为一件事震惊不已。演短剧的期间，雪之下的吐槽技能一直在提升。

「喂，怎么回事？你跟昨天判若两人，变得会吐槽了。为什么？」

「我回家研究了搞笑。」

仔细一看，雪之下的眼睛旁边有淡淡的黑眼圈。

「我一直在影片网上看各种影片，学习吐槽的方式。这样应该有进步一些。」

「岂止一些。和昨天差太多了。」

没错。没有比雪之下雪乃更不服输的人。昨天我在离开前这么说。

『没事。是我不该找你帮忙。我一个人来就好。』

这句话对她来说应该非常刺耳。不过，才隔一天就能吐槽得如此精准……不愧是雪之下。

「雪之下，你的吐槽技术变得这么厉害，可以直接上场了。请务必跟我一起上台。」

「这还用说。」

雪之下的表情看起来异常得意。

「啊，对了。有件事想问你。」

「什么事？」

「我看到有人表演了跟你的短剧内容非常像的短剧，那个人是谁？」

喔，她看到原作的影片了吗？

「那是职业的搞笑艺人。这个梗也是我跟他借来的。」

「……咦？」

雪之下明显面露嫌恶。

「这个剧本不是你自己写的吗？」

「咦？喔，不是啊。我直接拿那个人的梗来用。」

「……竟然盗用他人的智慧财产。」

雪之下气得发抖。

「呃，没有啦，我想说只不过是亲睦会，用同样的梗也没差吧。」

「别小看小孩了。那种骗小孩的伎俩，肯定会被看穿。所以要演的话得想全新的剧情才行。」

我不知道雪之下为何变得对搞笑如此热衷，然而听见这句话，我发现她明显开启了某种开关。

「明天给我写一份新的剧本出来！」

我在内心后悔，自己是不是找了个很可怕的人搭档。

隔天放学后。我拉开侍奉社社办的门，雪之下和由比滨结衣都在里面。

「自闭男，嗨啰——」

「喔，由比滨。你今天来啦。」

我话中带了些许的讽刺，由比滨却一脸不介意的模样。

「我听说了！你要跟小雪乃一起表演漫才对吧！」

「嗯，不一定是漫才，但我们要一起上台表演。」

「所以我带了这东西来！」

由比滨指向两个金色大领结。

「我跟戏剧社借来的！不觉得戴上这个会很有专业漫才师的味道吗？」

现在这个时代，几乎没有搞笑艺人会戴这么大的领结吧。为什么会来这间社办的女生都跟搞笑艺人不熟？硬要说的话，搞笑艺人的狂热粉丝应该是女性比较多啊。

「虽然不知道用不用得到，由比滨，谢啦。」

「咦——⁉可能用不到吗？机会难得，戴一下啦！」

「可是根本没艺人会戴这种领结。那只是想像。」

「有什么关系。」

雪之下忽然介入我跟由比滨的对话。

「对象是小孩子，以想像为优先比较好。所以这个领结我会心怀感激地拿来用。」

「真的⁉小雪乃，谢谢你！」

我无视握住雪之下的手的由比滨，因为雪之下的搞笑知识大幅提升而感到恐惧。我说不定找了个很可怕的伙伴。

「那么该来练习了。新剧本写好了没？」

「嗯，好不容易写好了。但我有点没自信。」

「那边看剧本边演也没关系，试试看吧。由比滨同学，可不可以帮我们看一下？」

「嗯！可以呀！」

「所以我的愿望是死在榻榻米上。」

「你够了喔。」

「「下台一鞠躬。」」

我和雪之下深深一鞠躬。一抬起头，由比滨就带着佩服的表情鼓掌。

「由比滨同学，感想如何？」

「总觉得超像在讲漫才的！」

「这哪门子的感想……」

她的表达能力之差，害我忍不住吐槽。不过，由比滨的反应应该算不错。昨天我写了好几份剧本，摸索着哪种风格才能逗人笑，如今努力似乎有了回报，我诚心感到喜悦。这样一个礼拜后的亲睦会也能顺利搞定吧。

「由比滨同学喜欢就好。」

「是说小雪乃，你的动作很有漫才师的感觉耶。」

「嗯。我看了许多搞笑节目的影片学习。」

「自闭男反而显得演技很差！」

真的假的。我挺喜欢搞笑节目的说。我以前就会看搞笑节目，所以满有自信的，没想到居然输给只认真钻研了两天的雪之下。不，说不定雪之下本来就有搞笑才能，不过我跟雪之下比也没意义。剧本已经写好了，这样应该就没问题了。

「那么换下一个吧。」

「是啊……咦？下一个？」

雪之下说的下一个是什么？在我疑惑之时，雪之下从书包拿出两张纸。

「接下来换表演我写的剧本。」

「……咦——！你、你也写了吗？」

「嗯。因为我想体验一下写剧本是什么感觉。」

我被雪之下那深不见底的热情吓得往后缩。这家伙不只提升了演技，还连剧本都写出来了。多么惊人的能力。这就是完美超人吗？

「由比滨同学，方便再看一次吗？」

「嗯！」

于是，我们又演了一次雪之下写的剧本。

「那去海边也没好处吧。」

「我不是那个意思。算了。」

「「下台一鞠躬。」」

我们跟刚才一样弯腰鞠躬。抬起脸，由比滨用比刚才大五倍的音量鼓掌，从椅子上站起来。想不到她会起立鼓掌。竟然能在这种地方见识到，我不禁感到佩服。但我的佩服转瞬即逝，由比滨的反应跟刚才差太多，我无法接受。

「好厉害！这是小雪乃想的吗？超有趣的！」

「我看了许多表演，考虑到观众的喜好想出来的，听你这么说我很高兴。」

「真的好厉害！跟刚刚那个比起来根本是天……啊。」

由比滨捂住嘴巴。我瞪向由比滨。

「讲啊，讲出来没关系啊。跟我写的剧本比起来是天什么？」

「呃、呃——天气不错耶！哈哈哈。」

转得有够硬。但我也隐约察觉到那个差距了。我写的剧本也是还算笑得出来的等级，不过跟雪之下的一比，差距显而易见。

引导观众进入状况的流畅度。用俐落的吐槽推动剧情。主题也符合流行，自然地加入装傻和耍笨的情节。后半段还回收了刚开始不知道是什么东西的伏笔。大概称得上品质非常高的剧本。

「这个剧本很厉害。正式上台时肯定没问题。」

「是、是吗？」

雪之下有点害臊。她应该很高兴吧，想掩饰喜悦，嘴角却挂着笑容。

「这样观众一定会笑得很开心——！」

由比滨开心地摆出胜利姿势。我和雪之下见状，露出微笑。

在那之后过了一星期，到了星期日。现在时间十二点半。我们待在公民馆的亲睦会工作人员等候室。

马上就要轮到我们上台。连我自己都感觉得到我在紧张，不停伸手摸由比滨跟戏剧社借来的领结。

『小孩子大约三十个吧？还有数名家长。』

亲睦会的工作人员所说的话浮现脑海。是吗？也对，当然还会有大人在场。意思是总共四十人左右啰。一想到人还挺多的，就愈来愈紧张。

「快换我们了。」

为了缓解紧张，我和雪之下搭话。雪之下却没有回应，坐在椅子上碎碎念。

「……书店没有书。书店没有书。」

似乎是在复习剧本。

话说回来，这一个礼拜，雪之下像魔鬼教练一样逼我练习。我跟她说只是三分钟的表演而已，应该不会有问题，她却回答「舞台上栖息着魔物喔」，不肯减少练习量。

是说你怎么知道舞台上栖息着魔物？你应该是第一次上台讲漫才吧。

算了，慎重一点不会有坏处。所以就算我现在这么紧张，应该也不至于忘词。

这时，等候室的门打开，工作人员探出头。

「马上就要轮到两位了，麻烦准备一下。」

「好，知道了。」

雪之下开口回应，静静起身，走出等候室。这家伙真可靠。我跟在雪之下后面准备离开，发现桌上放着一个大领结。

……那家伙忘记戴了！

虽然表面上看不出来，搞不好她会紧张。思及此就觉得那冷静的表情也挺可爱的。我拿着她的领结走出等候室。

走了一会儿，前面是通往举办亲睦会的大房间的门口。雪之下和工作人员站在那边。

「喂，你忘记领结了。」

「谢、谢谢。」

雪之下态度僵硬地拿走领结戴上。

『那么，大哥哥大姊姊马上就要来为大家表演啰——准备好了吗——？』

「「「好了——」」」

我听见孩子们在大声回应。

「终于。」

「是啊。」

或许是因为这一个礼拜，我们一直在密集排练吧，我莫名产生了一种同伴意识，不知道是不是只有我这么想。我甚至觉得，既然雪之下一脸泰然自若的样子，就不必担心了吧。

「那么，接下来轮到两位上台。麻烦了。」

「「好的。」」

工作人员打开眼前的门。有一堆小孩在看我们。

「大家好——！」

光是看到孩子们的视线集中在身上，大脑就快要变得一片空白，我拼命抑制住紧张感，跑到舞台上。

「大家好——今天我们是来讲漫才的。请多指教。」

雪之下温柔地打招呼，观众也配合她大声回应。嗯，感觉不错。

「那么加油吧。」

「那个，臭脸同学，方便问个问题吗？」

「叫人臭脸也太过分了吧。雪之下，我叫比企谷喔。」

「我想当当看幼稚园老师。」

尽管有点紧张，讲漫才的节奏并没有乱掉。好，看这情况应该不会出错。

「那就来试试看吧。」

「谢谢。那我来当幼稚园的老师，你来当幼稚园。」

「幼稚园⁉」

我试图靠动作演出幼稚园。

「呃，谁有办法当幼稚园啊！为什么要我当幼稚园！让我当幼稚园生吧！」

「咦——你好恶心。」

「哪里恶心！」

这里是由比滨也笑得很开心的地方。

然而，发生一起出乎意料的事件。

没人笑。没人笑啊。不对，有小孩子在笑，但只有两、三个而已。糟糕。继续演，继续演。

「那我来演幼稚园生。」

「好，小熊班的小朋友——」

「在——」

「太小声了，小熊班的小朋友——」

「在——」

「……小熊班的小朋友——」

「？……在——」

「小、熊、班、的、小、朋、友‼」

「好可怕！不要给幼稚园生这么大的压力！」

这是回答的音量大小，老师不停对小孩子施压的桥段。我第一次看到剧本时也有喷笑。

可是……没人笑。搞砸了。

糟糕。为什么？往旁边一看，雪之下也有点着急。不晓得是不是因为着急的关系，她的语速感觉变得比练习时还要快。

眼前的孩子们一脸失望地看着我们。惨了。怎么办？

「啊——」

其中一名孩子转身想走出房间，被工作人员制止。

「再看一下嘛——大哥哥大姊姊很努力喔。」

看到工作人员讲话的速度，我意识到了。工作人员语速很慢。没错。跟小孩子讲话时，速度大多都会放慢。一定是因为要配合小孩的语速。我们的表演内容和语速却都是以大人为基准。这样不行。

「你认真一点，好不好——」

我放慢语速，想将这件事传达给雪之下。雪之下却露出「你讲话干么这么慢」的表情，用跟练习时一样的速度说话。

不行。这样孩子们听不懂。快发现。快发现啊。

这时，雪之下脸上浮现非常悲伤的神情。

不是因为自己为漫才所做的努力、所花的时间都白费了，纯粹是因为眼前这些孩子那么期待这场亲睦会的表演，出于对他们的愧疚。

至少我是这么觉得。

是啊。不能回应孩子们的期待，很难受对吧。

我脑中瞬间浮现一个起死回生的主意。但用了这招，雪之下八成又会变得讨厌我。

可是这样做是为雪之下好，也是为孩子们好。

我下定决心。

「那，比企谷弟弟在画什么呢——？」

现在演到在幼稚园画画的桥段。本来是我回答我在画妈妈，雪之下说「啊——是妈妈在对韩系偶像挥手的模样呢，哎呀画得还真细」。

「咦？比企谷弟弟在画什么？」

我没有立刻接台词，所以雪之下以为我忘词了，又问了一遍。

「嗯，我在画的是……大便！」

「咦⁉」

意想不到的回答，导致雪之下对我露出惊讶占两成，鄙视占八成的表情。大概是因为就算是即兴发挥，这个回答也太莫名其妙了。不过。

「「「「哈哈哈哈哈哈。」」」」

雪之下望向笑声的来源。孩子们同时笑了出来。

没错。小孩子最喜欢低级梗。

有办法加进对话的话就尽量加进去。

「看，这是我的大便。这是田中的大便。这是佐藤的大便。」

我不管三七二十一，疯狂使用大便这个词。

雪之下带着难以形容的表情看着我，孩子们则笑个不停。

「然后，这是大便在大便的图。统统都是漂亮的大便！这也是大便、大便、大便、大便、大便……」

每讲一次大便，笑声就愈来愈大。小孩子最喜欢低级梗和重复梗。我看过亲戚的小孩因为这样一直笑，所以我知道。

「大便、大便、大便、大便，只有这个是鸡鸡。老师，我画得好吗？」

在一阵爆笑声中，我看着雪之下眨了下眼。她似乎察觉到了我的意图，叹了口气。

「太低级了吧！够了。」

我们对台下一鞠躬，孩子们便送上热烈的掌声。甚至还有人仍在捧腹大笑。

「跟大哥哥大姊姊说谢谢，一、二、三——」

「「「「谢谢！」」」」

我们听着众人的感谢声，回到等候室。

「我现在的心情糟透了。」

回到等候室，雪之下开口第一句话的语气十分沉重。

「你在想什么？擅自把剧本改编成那种连我的品行都会受到质疑的样子。」

「抱歉啦。可是气氛僵成那样，我不得不出此下策。」

「在那之前场面是很僵没错，不过之后的笑点说不定能逗笑观众呀。」

我不认为雪之下是真心这么觉得。但她就是想这么说。可见她有多么认真地对待这场表演。

「不过，幸好孩子们笑得很开心。」

「……或许吧。」

她喃喃说道，拿下领结，露出松了口气的温柔表情。

「好了，要怎么跟平冢老师说呢。」

「由你负责想。我不知道该怎么说。」

「嗯——就说大受好评吧。」

「万一她听了后说『既然评价那么好，在我们学校也办一场吧』怎么办？」

「到时再配合调整剧本。把大便改成排泄物。」

「烂透了。」

我和雪之下自然而然用讲漫才的节奏交谈，因此我们愣了下，然后轻声笑了出来。

14注  指日本搞笑艺人「Desuyo。」。

15注  「梗」及「馅料」日文皆为Neta。

** 曾几何时，雪之下雪乃的头发随着那一天的风摇曳。

作者：水泽梦／插画：春日步

曾几何时，雪之下雪乃说过「说不定，没有人来委托，就这样平静地度过，反而比较好」。

现在我重新感受到这句话的重量。

理由很简单……有委托就会忙起来。

闻名世界的狙击手迪克･东乡（注16），藉由同时处理好几件委托，一年完成了一百件以上的任务。

也就是趁委托A的待命时间及移动时间，处理另一件工作B。不，还得同时为C和D做事前准备，才能勉强达到这个数字吧。

连黑社会的大人物和各国总统都另眼相看的超人，才做得到如此完美的多工处理……区区一介平凡无奇的高中生，自然没那个能耐。

不能要求高中生多工处理。希望没有工作可以做反而才是正常的。

我——比企谷八幡加入的侍奉社，最近几天异常忙碌。平常明明几乎不会有人来，总是悠悠哉哉，现在却像那位狙击手一样，沦落到非得同时处理好几件委托的地步。

主要原因是顾问平冢老师突然加入的烦恼咨询信箱服务。

至于她是在哪里征求来信的，依然是个谜，不过多亏这个用不着直接到侍奉社社办就能轻松倾诉烦恼的系统，之前偶尔会接到的委托，现在从未间断过。

运气不好的是，这几天的委托叠得跟松饼一样高。

导致我们得四处奔波，行程整个被打乱。

我看差不多有可能形成平行世界了。那些诸多委托，另一个世界的比企谷八幡应该会想办法解决……

撑过如此的苦行，今天终于成功迎来风平浪静的放学后。

我和雪之下在安静的侍奉社社办看书，由比滨在滑手机。最近频繁出入社办的一色，今天似乎没来。

今天死都不开电脑。就算有人写信来咨询，只要没看见就等于不存在。

「呼……」

雪之下吁出一大口气，将文库本放到桌上。然后用手摩挲肩膀，确认肩膀有多僵硬。

「累的话要不要今天就到此解散了？」

「谢谢你的关心。不过我没事，比目鱼同学。」

「只剩下『比』这个字一样了……」

只要对一个字就行的话，我到最后是不是有可能被叫成Twitter同学？

我、我可不是在担心雪之下。我只是真的累到不行，想早点回去而已。别误会了！

……这种傲娇的固定台词在近代日本逐渐褪流行了，好哀伤。很哀伤对吧？

「辛苦了～小雪乃！我帮你按摩肩膀！」

由比滨精力十足地绕到雪之下的座位后面。

「没关系的，由比滨同学……我不累。」

雪之下明显在逞强。因为我知道她这几天也忙到不行。

我不会虚张声势，因为我真的很累。昨天我还一个人用电脑回了多达十五封咨询信。虽说侍奉社的回信平均只有两行，没得肌腱炎真是不可思议。

由比滨没有理她，把手放在雪之下肩上，夸张地做出惊讶的反应。

「喔——这个！你肩膀很硬喔～！」

她将身体向前倾，大概是为了施加重量。

雪之下好像放弃挣扎了，任凭由比滨帮自己按摩。

我偷瞄了一下，雪之下全身一动也不动。应该是因为就算加上身体的重量，由比滨的力气还是太小。那样看来一点按摩功效都没用。

「怎么样，小雪乃？有用吗～？」

「嗯，很舒服。谢谢你。」

尽管如此，朋友愿意帮自己按摩应该还是挺令人高兴的，雪之下微笑着道谢。

「咦？」

由比滨忽然停下按摩肩膀的手。

她将脸凑近雪之下的后脑勺沉吟。本以为是在闻她头发，结果好像不是。

「啊，果然。小雪乃有白头发。」

由比滨似乎找到了白头发，灵活地捏起一根头发。

雪之下的头发长及腰部，要将捏起来的头发拿到本人面前给她看毫无难度。雪之下看了——

「……真的。」

显得不知道该做何反应。也是啦，总不可能说「哇，谢谢你帮我找到白头发！小雪乃好开心喔～！」。

由比滨「嘿嘿嘿」笑着询问雪之下：

「欸欸，可以拔掉吗？」

「……随便你。」

掌握白头发命运的由比滨，慎重又大胆地一口气把它拔掉。

「嘿！」

「嗯……」

雪之下肩膀一颤，轻轻叫了声。

她的声音害我觉得有点色，尴尬得望向其他地方。

由比滨一副砍下敌方首级的态度，高高举起白发。

「小雪乃连白头发都好漂亮～」

的确。一根白发在社办的白色灯光照耀下，闪烁如同绢丝的光芒。

「谢谢你，由比滨同学。我的肩膀舒服多了。」

雪之下呼出一口气，又开始看书。

由比滨在雪之下道谢后依然站在她背后，用更严肃的声音说：

「啊，还有一根白头发。」

「咦……？」

雪之下手中的文库本差点掉下来，在千钧一发之际接住它。

「这根我也拔掉啰。」

由比滨立刻拔掉第二根白发。

然而，俗话说有一就有二，有二就有三。

「……咦，又一根。」

由比滨的神之手找到第三根白头发，迅速拔掉的瞬间，雪之下终于惊讶地转过身。

「——可、可以等一下吗？由比滨同学。那真的是白头发？有可能只是光线造成的。」

雪之下努力维持冷静的态度说明，却掩饰不住内心的动摇。

「没错喔，你看，是白头发。我小时候常帮爸爸拔白头发，所以很会找。」

说句「真的耶是我误会了，嘿嘿☆」然后闭上嘴巴不就得了。由比滨平常很懂得察言观色，是因为曾经身为白头发猎人的习性，导致她失去冷静的判断力吗？

不过，连雪之下看起来都受不了了。

「谢谢你，但已经够了。虽然白头发拔了会变多这个说法，在现代遭到否认，一次拔太多白头发会对头皮造成负担吧？」

「会吗？……这样啊，所以爸爸才会……」

由比滨缓缓抬起视线凝视空中，哀伤地眯起眼睛。

咦，等等，你爸怎么了？一次拔太多白头发，对头皮造成负担的结果是？

「小雪乃感觉还有白头发……」

由比滨好像觉醒了奇怪的使命感，想继续搜索白头发。

我不禁觉得雪之下太可怜，若无其事地插嘴。

「适可而止吧。你想拿雪之下的头发做小提琴吗？这样没完没了。」

我自己都觉得这句话满有梗的。拿雪之下的头发当弦做小提琴啊，想必会演奏出恶魔般的美丽音色吧咿嘻嘻嘻。

「……！说、说得也是，对不起小雪乃。以前我和爸爸最常靠拔白头发交流……所以我不小心想起来了……」

「没关系，别放在心上。很温馨的孩童时期呀。」

雪之下乍看之下并不介意，可是……

过没多久，告知离校时间的钟声响起。

不知为何，好不容易从忙碌的生活下得到解放，今天感觉却异常疲惫。

「我的白头发……什么时候变那么多了……」

雪之下用微弱的声音咕哝道。

听起来像丧气话的那句自言自语，残留在耳中。她果然有点受到打击吧。

白头发啊……我也得注意才行。

「嗨啰——」

隔天放学后。由比滨接在雪之下和我后面走进侍奉社社办。

「嗨啰——」虽然是很神秘的招呼语，每天都在听的话就能藉由嗨啰的嗨啰程度，掌握嗨啰由比滨的精神状态及身体状态。

今天的嗨啰粗估有8.5嗨啰……不，差不多8.7嗨啰吧。

跟基本值10嗨啰比起来有点低，不至于沮丧，但情绪有点低落的数字。

以上全是我现在随便想出来的设定。八幡，你累了……

简单地说，我只是想表达由比滨似乎有点在意昨天的事。

当事人雪之下在看书，看起来并没有特别放在心上。可是考虑到昨天回去前发生的事，这个态度也挺微妙的。

这时，社办的门突然打开。平冢老师飒爽地走进来。

「平冢老师，请记得敲门……」

雪之下这句话讲到一半就没了气势。由于讲了好几次依然没用，她几乎放弃了。

平冢老师坐在空着的椅子上，双臂环胸，翘起脚来。

我们等待着她开口，她却沉默不语，只是坐在那边。没办法，我们只好继续做自己的事。

过了十分钟左右，平冢老师仍然一句话也没说。

反而在盯着我……

「………………」

咦？干么？她甚至在对我抛媚眼。好可怕。

由于目光交流并未成立，我决定代为陈述平冢老师的用意。

「嗨，挖喜平冢静。今年三十岁左右的资深女教师。因为一直没对象的关系，结婚的希望愈来愈渺茫，超着急的啦。」

「哈哈哈我也是因为有苦衷才结不了婚的喔，小心我杀了你。」

面对在这个时代还敢满不在乎地放话说要杀掉学生的战斗民族，我只能「啊、啊啊啊……」吓得瑟瑟发抖。

不过，请看。拜其所赐，平冢老师终于愿意开口。

偶尔也好，希望各位想起来。仅仅是个平凡地球人的比企谷八幡这个男人，勇敢对抗过凶恶的外星人。

「老师，怎么了吗？你一直默默坐在那里，就算不是自闭男也会好奇耶。」

头部右方装备了斤斗云的Z女子由比滨，向我伸出援手。虽然希望她在平冢老师对我释放杀气前就这么做，有总比没有好。得救了。

「我可是侍奉社的顾问，待在社办也没什么好奇怪的吧。」

那还真不可思议。除了塞问题——更正，塞委托给我们的时候，你根本不会出现耶。

阖上文库本的雪之下也面露疑惑。

平冢老师夸张地叹气，像在谴责我似的往我身上瞪。

「比企谷，今天的咨询信是不是还没看？」

有股强烈的不祥预感。我用眼神制止立刻准备从抽屉拿出笔电的雪之下。这次的目光交流成功了。

「最近电脑怪怪的……今天也开不了机。所以咨询信下次再看。」

平冢老师塞给我们的笔电，是开机要花好一段时间的旧机种。某一天突然坏掉都不奇怪，隔几天突然恢复正常，也一点都不会不自然。

「是吗？」

平冢老师却以手抵着下巴，「呣」了一声点点头，讲出惊人的发言。

「放心，咨询信不是只能用那台电脑看。帐号和密码我都记得，趁这机会加进你手机的邮件APP里吧。」

「咿！」

我忍不住紧张地哀叫了一声。

开什么玩笑。要是咨询信会寄到我的私人手机，我绝对会变神经病。那个想当轻小说家的常客，会用连明信片职人都望尘莫及的频率寄信过来喔。

「…………不过，差不多修好了吧。雪之下，麻烦你开一下电脑。」

我灵机一动，为这台电脑加上连黄金圣衣都没有的自我修复能力。没有引人怀疑，成功化解危机。

照理说是这样的……重新从抽屉拿出笔电的雪之下，却对我投以冰冷至极的目光。

「是吗？嗯，能用电脑看最好。」

平冢老师也露出怀疑的表情。希望没被发现……

「平冢老师，咨询信姑且算是私人情报，我认为设定成能随便用学生的手机看不太好。」

雪之下叹着气说出超中肯的意见。

「咨询信是匿名的，看不出个人情报。」

平冢老师信心十足地回道。

问题是，那些匿名信之中，九成都可以轻易猜出是谁寄的。

「话说回来，这台电脑是真的很旧。光是想上网速度都会变慢，再说，它装的是已经停止更新的作业系统耶……安全性没问题吗？」

「应该没有不能流出去的情报。比企谷，如果里面留着你在网路上买色色的书的纪录，就另当别论了。」

「并并并并并并并并没有！」

我是有多惊慌啦，这样显得更可疑了。

雪之下和由比滨眯起眼睛看着我，欲言又止。我没买A书啦！哪个时代的学生会这样啊！

………………平冢老师那个时代的学生吗……我哀伤地下达结论。

可是像平冢老师这种觉得自己的电脑里面没有不能流出去的情报，所以用旧机种就行的人很多，作业系统才会一直无法全面更新吗？盖兹家的比尔弟弟应该也很头痛。

我将笔电拿到自己的位子，雪之下和由比滨也把椅子拉到我旁边。由比滨将脸凑近萤幕。

「……那我来念啰。第一封是……笔名：阿腐同学的来信……啊哈哈，又是姬菜呢。」

看，个人情报立刻外泄！

〈笔名：阿腐同学的来信〉

我得了腐治之症。看到班上某两位男同学（H山同学×H企谷同学），我的心就悸动不已。

H人同学×H幡同学，简称Heart to Heart的这两位，以为大家都没发现吗？他们有时会偷偷热情地互相凝视。

感觉都听得见我的心跳声了，好难为情。为什么呢？不符合我的个性对不对……？

这样下去我的左胸可能会变得特别大！我该怎么办？

呃，这已经不是「某两位男同学」了吧。根本没简称到。打码毫无意义。

我们并没有互相凝视。更重要的是，超符合你的个性。

不行，吐槽不完。

E老名同学虽然偶尔才会寄一封信，破坏力却非常高。

「在说你喔，H企谷同学。」

「姬菜观察你们观察得很仔细呢。」

如果她真的有睁大眼睛看，就不会寄这种信来了。那个人的眼镜八成有附带外星人制造的特殊滤镜。

「所以海老名同学是想咨询什么？治好这个病吗？」

「她自己也知道这病没药医，别管她了吧。」

H菜同学的来信，导致我精神上的疲劳在侍奉社里面是最为突出的，各位现在知道了吗？

「呣……呣……」

由比滨咕哝着沉思。你要呣多久啊，你是牛吗？

最后，她似乎终于得出一个答案。

「对了！是不是在担心两边的胸部大小会变得不一样⁉」

「最后一句八成是这封信的重点」的着眼点没错。不如说就当成是这样吧，咨询时间结束。

「那不是病吧。跟心跳剧烈与否和速度无关，胸部本来就是左右两边大小会不一样的东西。因为惯用手之类的要素，会导致身体两侧肌肉的发达程度不同。」

平冢老师认真地反驳。

接着把手掌放在左右胸下方，轻轻让胸部上下弹跳。

「哦～我都没注意过……」

由比滨听了也一样碰触自己的胸部确认。

喂……这两个人干么突然玩起胸部。

大小差距没严重到随便摸一下就摸得出来吧……

「…………」

我感觉到一阵刺骨的寒意，回过头，雪之下面无表情地在看书。明明她刚才手上还没书。

平冢老师和由比滨没发现雪之下的变化，仍在检查左右胸的大小差异。

阿助阿格（注17），够了吧。

胸部跟GAGAGA文库的封面一样平的小雪乃会难过。

不对，GAGAGA文库封面以外的部分也都是平的，硬要说的话GAGAGA文库之外的轻小说也都是这样。意即雪之下是轻小说。

「咨询信只有那一封吗？」

雪之下承受着大宇宙的不合理，声音微微颤抖，催促我继续说。

「喔、喔……总之我先回一下这封信。」

我轻快地敲打键盘，采纳由比滨的意见写好回信。

〈侍奉社的回答〉

试着让阿腐同学的心脏再增加一颗如何？这样胸部大小也会平均，还能跟您信中提到的一样，Heart的数量×二，一举两得喔。

「要让心脏变多吗⁉」

由比滨大吃一惊。

呃，虽然这样讲像在自夸，我觉得这回答不错啊。左右各一个比较平衡吧。虽然心脏其实好像几乎位在正中央。

「第一封就把体力耗光了……」

由比滨把疲惫不堪的我晾在一旁，从旁窥探萤幕。

「我看看……接下来是第二封。笔名：猫咪同……」

讲到一半，由比滨不禁歪过头。

可是，过没多久她脸上就绽放笑容，语调上升了两个等级。

《笔名：猫咪同学的烦恼》

最近我的发质好像变差了，请问有推荐的处理方式和护发方式吗？

刚念完，由比滨就冲向雪之下。

「小雪乃好可爱——‼」

然后整个人扑上去抱住她。

「呃……这是匿名咨询信吧⁉」

看到被由比滨黏住，困惑不已的雪之下，平冢老师满意地点头。

是雪之下的咨询信。她希望我发现，才一直热情地注视我。

「喂，猫乃。叔叔觉得这笔名太装可爱了喔。」

「那名字又不是猫乃……！」

雪之下被由比滨抱着，看起来很不自在，依然开口反驳。

由比滨则不满地鼓起脸颊。

「真是——干么写信，直接讲不就行了——！早知道昨天去小雪乃家住一晚！」

看见她们感情这么好，平冢老师露出苦笑。

「其实昨天，雪之下有来找我商量。我试着说服她最好也问一下你们两个的意见……结果决定采用这个方式。」

原来如此。尽管很迂回，她是考虑到用咨询信这个方式，会比较方便以侍奉社的身份应对吧。

「你们基于侍奉社的理念，陪许多学生商量烦恼。当你们有烦恼的时候，身为顾问的我提供协助很正常吧？」

话虽如此，平冢老师常常都会提供建议给我们。

「尤其是雪之下这次的烦恼，我相信我也能帮上忙。」

平冢老师把手放在额头上，彷佛在唤起年轻时期的记忆。

「这是之前——我照顾亲戚的女儿时发生的事。那孩子很黏我，挺可爱的……但她特别喜欢摸我头发。」

讲到这里，平冢老师用手捞起光泽亮丽的黑发，低头看着它。

「啊……我懂！小时候我超向往大姊姊有一头漂亮的长发！」

「嗯，我一开始也怀着这样的期待……结果那孩子带着灿烂的笑容说，『你有白头发，我帮你拔掉啰』……」

由比滨「唔！」了一声，大概是想到昨天自己的所作所为。

「她把一根长长的白头发放到我手上，我当场愣住，接着头部又传来轻微的刺痛感。两根……三根……她告诉我『还有很多喔～』……」

哪来这么惹人厌的番町皿屋敷（注18）啦。

「之后那个女孩叫我的方式就从『静姊姊』变成『静阿姨』……！呜呜……明年起休想要我给你红包……」

雪之下神情悲痛地听着她的亲身经历。

真的好可怜——那个女孩子。红包的供给来源少一个很伤的喔。

「从那天开始，我就憎恨起白头发，开始一场消灭自己的白头发的战争。」

平冢老师是因为这样才成了千叶的复仇者吗？等她PU的时候抽一下好了。（注19）

「雪之下，你的烦恼很正常。不能因为自己还年轻就大意。身体的异状早期发现，早期治疗是基本。尤其是我们这种长头发的人，千万不可以放着白头发不管。」

「……嗯。昨天洗完澡，我非常仔细地检查过了……」

哎，这举动很正常。问题是白头发很难自己找到。如果能靠自己的力量找到一堆，到时说不定已经没救了。

「呜呜～小雪乃对不起！都是因为我多管闲事……」

「不是由比滨同学的错。我想我迟早会自己发现。」

不过，减少白头发的手段……护发啊。不好意思，没我出场的份。今天赶快闪人吧。

我从制服口袋里拿出手机，看了萤幕一眼，先演出用手指滑过萤幕的小动作后才将它拿到耳边。

「喂，小町吗？什么？小雪要生了？好，我马上回去。」

我将手机拿在耳边，用视线告诉平冢老师「那我先走了」，行了一礼。飒爽起身。

「比企谷，把你那半通电话都没接到的手机收好，坐下。」

她毫不留情地宣言。

啧……为什么会被发现。

「自闭男也帮忙想啦——！」

「我哪可能帮得上忙。平常我就没什么在护发。」

我搞不好会不小心碰触到敏感话题，你们小女生就自己聊自己的吧。各位有发现吗？我刚才把平冢老师也归类在小女生之中喔，出血大放送。

「是说，要聊这种话题的话，身为男性的我在场，本来能讲的也会变得不方便说吧。」

「我不会觉得你碍事。如果你也愿意帮忙……我会很感谢你。」

她难得用这么诚恳的态度拜托我，我搔着后颈以掩饰害羞。

「比企谷，问题不只在于护发。」

平冢老师严肃地告诫我。

「白头发和压力有密切关联，这是可以肯定的。雪之下忽然开始长白头发，我这个顾问也会觉得自己该负责。」

那就废除咨询信制度啊……刚才那封信确实让我的头发有几根变白了喔。

「我不认为原因是社团的压力。」

这应该是她无法退让的大前提。雪之下斩钉截铁地反驳。平冢老师似乎读懂了她的心，用力点头。

这时由比滨突然站起来，困惑地面向我。

「呃！小雪是公的吧⁉哪可能要生了‼」

「这是几分钟前的话题⁉」

我忍不住大声吐槽。

在连聊天机器人都能几乎即时回应的这个时代，你的演算法执行速度到底有多慢？

同学，这样人类的工作会统统被AI抢走喔。

但我反而希望AI能多多取代人类。

真心希望可以把悠哉地逛购物网的时候，不停从萤幕角落弹出来的「向客服询问」视窗删掉。害我每次都在担心万一不小心点到，跟客服人员接上线怎么办。

可是如果上面注明「客服人员由AI担任」，就能放心了。

结论是，咨询信服务也导入AI系统吧。

那么，该怎么办呢？关于头发的烦恼啊……女生自然是愈多愈好。在场三人中，雪之下和平冢老师偏有烦恼的那一方。

一色偏偏就是在这种时候没来。

我都想请户冢来担任特别讲师了。

户冢的头发，简称户冢发实在太过柔顺，会有点吓到。他只是微微歪头，头发都会轻盈摇晃。同班同学随随便便就能重现出天女的羽衣，害我头好痛，不，并不痛。

「……这样讲跟我刚才说的有矛盾……不过虽说有个人差距，白头发每个人都会有。尤其是雪之下，你还只是十万根头发里面有两、三根而已。本来根本用不着在意。」

平冢老师先讲了句开场白安慰她。或许是她觉得自己刚才用「早期发现早期治疗」这个严肃的说法并不恰当。

虽然我觉得这句话有点像在对自己说。

「我当然也明白……」

「放心啦小雪乃！担心也没用，一起解决这个问题吧！」

雪之下温驯地低下头，由比滨拼命鼓励她。

这种事往往是愈担心就愈会有压力的恶性循环。

然而说实话，这次我也不是不能理解雪之下的烦恼。

十万根之中的三根……○･○○三％。以数字来说等同于零，但异质的存在再怎么低调都会引人注目。

数十万画素的液晶萤幕中少了一、两个点，会在意的人还是会在意。就算说明书上写着「这是制造时会有的正常现象，并非产品缺陷」这条注意事项，听说触碰式的掌上型游戏机刚出的时候，店员也费了好一番工夫处理客诉……

异物混进和谐之中，就叫瑕疵品。

被抓到的异物会恼羞成怒地跟周围的人说「我就是瑕疵品啊，有意见？」。

而避免落得如此下场，也是一种处世术。

「呣……整理心情很重要啊。」

平冢老师抱着胳膊，视线沿着雪之下的头移动。

「白头发的原因首先是不规律的生活、饮食不均……头发没洗干净、洗完头发没吹干——这些基本的部分，我……当然，雪之下应该也有顾虑到才对。虽然饮食不均这一点，我有点没自信。」

毕竟平冢老师晚餐固定吃拉面。但我希望这点小事就别算在饮食不均的范围内了。

「剩下就是广为人知的……压力……」

平冢老师似乎还是挺担心社团活动对雪之下造成的负担。

「果然……是因为压力吗？」

由比滨的手握在胸前，不安地凝视雪之下。

从昨天开始，这家伙就有过度内疚的迹象。八成是觉得自己让雪之下发现白头发，带给她更大的压力。

我下意识大叹一口气。

「不一定只有精神上的压力吧，也很有可能是身体上的压力。」

我自然地插嘴，雪之下点头。

「你说得没错。光是留长头发，就不免对头皮造成负担……造成压力。」

「是啊，头发的重量……」

听见平冢老师的附和，雪之下对我使了个意味深长的眼色。

「也就是自作自受。」

「我没说到那个地步……」

由比滨拍了下手，大概是听懂了。

「对了，沙希之前也说过她觉得自己的头发很长很烦。头发长果然很辛苦……」

「沙希……噢，是那个人啊。川……川……川西同学。」

「？川七？」

由比滨以绝妙的准确度，展现出如同现代影片网的自动字幕功能的听力。你疑惑地看着我也没用，叫沙希的人我只认识虹野同学（注20）……

有啦，我脑中有浮现她的脸。可是名字……她叫川什么同学？算了，记得川和沙希就够了吧。

「那个人头发也挺长的。」

「嗯，她绑高马尾头发还跟小雪乃差不多长。放下来说不定会到平冢老师的长度。」

是说那家伙既然觉得烦，干么特地留长发？家规吗？

「我为白头发烦恼的时候，也不是没考虑过剪短头发，减轻负担。想说干脆剪成超短发，这样就不会有留恋……」

原因会不会就是长发本身——讨论到这里时，平冢老师也烦恼地叹气。

「超短发⁉太可惜了啦，老师，你头发那么漂亮～！」

由比滨紧张地阻止她。

「我自己当然最舍不得。因为以转换心情来说，剪成那个长度需要勇气啊……」

「您有自觉的话……把剪头发当成像修剪树木一样，是不是会比较轻松？」

我尊重平冢老师的意见，雪之下和由比滨却同时眯眼瞪过来。

「平冢老师的头发长及膝下。也就是说，有一公尺左右长。光是把头发留到那么长要花多少时间……你能想像吗？」

一时之间无法想像。我自不用说，小町也没把头发留得像雪之下那么长过。

「虽然有明显的个人差距——头发平均一个月只会长一公分喔。从我开始留长到现在……也花了五年以上。」

雪之下用手心捞起自己的黑发，彷佛在感受岁月的重量。

认为自己的价值观跟一般的女高中生有出入，为此感到自卑的雪之下，对于头发却有着与年龄相应的审美观及感情。

仅仅五年，但也称不上短。

打个比方。如果有个小时候希望头发快点变长的少女……应该会觉得五年十分漫长。

「……我没打算剪短。因为我不讨厌自己的头发。」

也许光泽亮丽的黑色长发，同时也是她的矜持。

那么，只要以此为前提想办法即可。

「虽然你一直都留长发，总有最近才产生的变化吧。」

三人的视线都集中在我身上。

「一直绑头发的人突然不绑头发的话，白头发好像容易变多…………小町说的。」

「哦，不愧是小町。」

雪之下没有怀疑，称赞小町。

其实这是我昨天自己在网路上搜到的知识，但还是别说好了。

死都不说是因为她们开始讲白头发的话题，害我也担心起来。

顺带一提，关于这点众说纷纭。这句补充很重要。非常重要。

「也就是说，你前阵子不是还一天到晚把头发绑成双马尾吗？会不会是你现在不绑头发造成的？」

「双马尾……？」

雪之下微微歪头。

你不知道这发型叫什么，还绑成那样啊。虽然这绝对不是一般的叫法。

雪之下最近都没有绑双马尾。

不久前我还会心想「雪之下的双马尾在晃」……不晓得从什么时候开始，这个想法就消失了。

直到现在特别去注意前，我都没发现。

平冢老师得意地竖起食指，对雪之下解释：

「那个啦。用最近的动画说明就是……对了，星野琉璃（注21）的发型，这样你就知道了吧？」

不，我觉得她不会知道。NADESICO已经迎接二十周年了喔，不是最近的动画。虽然我会等它的续篇等一辈子。

「是初音未来的发型喔，小雪乃！」

由比滨口中迸出出人意料的名字。初音未来的知名度真的好高。连派对咖JK都知道。

可是，雪之下并没有被未来未来掉（注22），而是更加困惑。

「呣……」

平冢老师手放在下巴处点了下头，缓缓起身，从两侧拨起长发。

「像这样，这种发型。比企谷说得没错……虽然扎头发的位置不同，你之前也满常把头发扎成两束的啊，雪之下。」

接着拿捏成圆圈的手指扎头发，当场绑了个双马尾。

「呃啊！」

无法抑制的反射动作害我发出痛苦的声音，平冢老师人如其名，静静回头。

「比企谷，你那是什么反应？」

啊哇哇哇视我的回答而定她可能会拿双马尾当双节棍对我发动攻击。

「没、没有，我只是觉得您绑马尾的速度很快，很熟练……」

我惊慌失措地想出一个理由。好像有用，平冢老师信心十足地挺起胸膛。

「嗯，因为我到国三为止都是绑双马尾。现在身体也还记得绑法。」

请您不要后来才帮自己加上这种不负责任的设定。这样谁要负责啊。

「……的确，我绑头发的频率可能有下降……虽然我没有刻意不绑……」

她话讲得吞吞吐吐。这是雪之下的真心话吗？

「顺带一提，不只是少了绑马尾时对头皮的适度刺激，精神上的影响也包含在内。本来该有的东西不在，害人感到不安，造成严重压力——的样子。」

我说的只是在网路上搜寻就能查到的简单小知识，由比滨却露出表情符号般的表情，表示这超出她的理解范围。

没办法，改编一下让她比较好懂吧。

「例如，这是我听材木座说的……」

「光听见这句话就不想听下去……」

雪之下用手按住额头，彷佛头很痛。

别这样说嘛虽然我也有同样的心情。

「看书的时候，不是会有特别注意的地方吗？」

雪之下稍微用力地点头，回答我的提问。

「看轻小说的时候，特别注意有没有双马尾角色出现的人，似乎也不稀奇。」

「我听到这边就已经听不懂了……真的不稀奇吗？」

不懂得怀疑他人的比滨同学，竟然对我投以如此怀疑的目光……

体谅一下啦，世上也会有只追求双马尾的阅读体验吧。

「尤其是系列作，那个倾向会特别明显。第一集在二九四页，第二集在二十八页，第三集在九十八页——之类的感觉，会只在有出现『双马尾』一词的页数贴便条纸标记。」

「……对不起，我完全无法理解。不如说……」

「总觉得好恶心……」

由比滨接在雪之下后面说道，「啊哈哈」露出僵硬的笑容。

只用「好恶」两字形容还不够吗？你这是真心觉得恶心耶……

「特地在书上贴便条纸太娘了。喜欢的页数会回翻好几次，所以自然而然就会翘起来，无意间做了记号……那就是读者的矜持，不是吗？」

平冢老师带着得意的笑容提出自己的主张。亲身经历过少年漫画黄金期的世代，也会对原则异常执着。

「我倒觉得有好好珍惜书的话，看多少次都不会翘起来……」

爱看书的雪之下回以现实的意见。不过小说和漫画比起来，回头翻喜欢的部分的频率截然不同啦。

我在心中投给雪之下的意见一票，将话题拉回来。

「总之如果那部作品从某一集开始突然不再出现『双马尾』一词，那类型的读者会很错愕吧。第四集应该是巧合？咦，第五集也没有。第六集、第七集……还是没有。超过第十集的时候，那名读者会像故障的收音机一样重复同一句话。『没有双马尾……没有双马尾……』。」

「变成怪谈了⁉」

由比滨吓得瑟瑟发抖。这行为的确是彻头彻尾的妖怪。

喂，材木座，这个故事真的不稀奇吗？

「唉，那又不是绑头发的当事人的经历……总之，理解成光是换发型都有可能造成压力就行了吧。」

最后她下达这个结论，我也无话可说。我发自内心后悔讲到一半要举这个例子。

「……嗯，你举的例子虽然很极端，我绑头发的频率减少是事实。既然如此，或许可以假设远因是那个。」

雪之下神情严肃地沉思。由比滨展开双臂，从背后靠到她身上。

「意思是偶尔把头发绑起来比较健康对吧？那小雪乃，赶快来绑头发吧！」

对喔，她有时会帮雪之下绑头发。

才刚宣言完，由比滨就冲出社办。

过了几分钟，她喘着气抱着一个纸箱回来。

「这是我自己的……还有跟别人借来的‼」

她打开纸箱，将道具放在桌上，除了疑似私人物品的发圈、发夹、梳子外，还有定型喷雾、发卷等等，甚至连离子夹都有，不晓得从哪弄来的。

还有洗发精和润发乳，推测是跟社团活动结束后会冲个澡的运动社团借来的，她该不会打算在这洗头吧。

「那先从双马尾开始……」

看到由比滨十指动来动去逼近自己，雪之下倒抽一口气。

「…………等一下。那个发型……可以先不要吗？」

「……？这、这样呀。那我来找适合每天绑的发型‼」

或许是因为雪之下强烈制止她的关系，由比滨没有继续坚持，开始找其他发型。

雪之下那家伙，都解释得那么详细了，还是讨厌双马尾吗？

不，听见材木座分享的案例，会产生排斥反应也不奇怪……所以是我害的啰？

由比滨以流畅的动作将雪之下的头发整理成一束，插进叼在口中的数根发夹。

「嗯嗯，小雪乃果然也很适合绑马尾——体育课以外的时间也可以绑呀。」

她将高马尾的根部绑成一颗丸子。由比滨帮忙绑头发的时候，有高机率会附赠丸子，而不是月亮。

「干脆把浏海也往上梳吧。」

「我、我觉得……不适合我……」

雪之下不知所措，大概是在想像露额头小雪乃的完成图。然而因为她拒绝得不够坚定，浏海被人梳起来，用那个不知道叫什么的东西喀嚓一声固定住。

她直盯着我，大概是发现我在看她。

我、我没兴趣好不好。你叫我别看我就不会看啊？

…………实际上，我国中时期只是瞄了换发型的女生一眼，就被人家用超认真的语气说「你可不可以不要一直看」喔？

「顺便帮你按摩头皮～！」

由比滨说着「打起精神吧」，用手指在友人的头皮上跳舞。

雪之下苦笑着接受她的身体接触。

这样是很好，不过——

「比企谷，有空的话帮我也按摩一下。顺便帮我按肩膀。」

女教师见状，对我提出强人所难的要求。她将身上的白袍往下拉了些，露出肩膀。

我打着用「我现在指甲很长」这种随便的理由拒绝的如意算盘。

「！等、等一下，帮小雪乃按摩完之后我来帮平冢老师按摩！自闭男不用动‼」

但在那之前，由比滨先自告奋勇了。看来这么着急，果然是因为担心让我来按摩，会对头发带来不好的影响吗？

「嗯，由比滨同学的按摩诚意十足，非常温暖。平冢老师要的话，我认为请由比滨同学帮忙比较好。」

正在接受她诚意十足的温暖按摩的雪之下，对我投以极度冰冷的眼神。我做错了什么？你和由比滨组成了热循环器吗？

不管怎样，感谢她的救援。

虽说称不上答谢，我用还没收好的笔电搜寻发型，来支援很快就没灵感的由比滨。

「由比滨，这个如何？」

「咦，你要指定吗？」

她用雀跃的语气回问，小跑步跑向我。看到她的视线移到电脑萤幕上，我加以补充：

「升天天马MIX头——是在发型界中追求冲击性的顶点之一。」

简单地说，就是头上有个大钻头的发型。

雪之下瞄了萤幕一眼，用带有谴责意味的眼神问「你认真的吗」。

这可是曾经风靡一世的发型耶，虽然我从来没在千叶看过有人顶着这颗头……

「呃——可是这种发型，刚开始要先用一堆发卷把头发弄卷，还得喷一堆强效定型喷雾……里面是不是还有用钢线固定呀……？」

由比滨设计师看着萤幕沉吟。

凭这张解析度低的照片就能分析出施术难度，了不起。

「可以不要认真考虑吗……⁉」

某种程度上任人摆布的雪之下，也对这个发型再度产生强烈的排斥感。

「给头发造成过大的负担，不就本末倒置了？」

当事人都这么说了，由比滨只能闭上嘴巴。

不过，我还以为这个发型是想呈现出独角，为什么名字不是叫升天独角兽，而是升天天马？

我望向旁边，平冢老师拎起自己的头发，做成尖尖的钻头状，稍微重现了一下。你要剪那颗头的话，我会为你加油……

雪之下看了，客客气气地说：

「那个，由比滨同学，你已经帮我按很久了，也去帮平冢老师按摩吧……」

「还不够！是我害小雪乃不安的。我要好好补偿你！」

「就说不用放在心上了……」

「由比滨说得没错，雪之下。收下她的好意吧。」

平冢老师好像也在尝试各种发型，秀了其中一种给我看。

「比企谷，你看你看，怎么样？挺清纯的吧？」

她把头发编成麻花辫，垂在胸前，确实满有味道的。

不错喔。有股人妻感。讲得更仔细一点，有股寡妇感。

我开不了口，她似乎把我的沉默误会成其他意思。

「这样啊，很奇怪吗……」

平冢老师陷入消沉，我急忙安慰她。

总觉得这人明显愈来愈脆弱。

常听人说坚强地活着的人，遇到能让他展现出脆弱一面的对象就会变脆弱……平冢老师也遇见了这样的人吗？

既然如此，对方就该负起责任娶她回家。真是，那人在拖拖拉拉什么啊！

过了一段时间。雪之下头上闪过各种发型。

现在告一段落了，由比滨轻轻用手梳理雪之下放下来的头发。

「小雪乃的头发果然很漂亮。」

接着忽然从背后温柔地诉说。

「完全没有受损，保养得很好喔。」

那是给雪之下的咨询信的答覆。

「不过，偶尔也像这样换个发型转换心情吧。我随时奉陪‼」

平冢老师也满意地点头。

「……嗯。」

雪之下露出柔和微笑。

昨天给由比滨按摩肩膀的时候也是……由比滨的存在，对雪之下来说不仅不是压力，还能让她心情平静。

这样的话，果然还有一件事悬在心上……

平冢老师最后留给雪之下一句「别输给高压社会，加油吧」，不知道适不适合由老师给学生的忠告，离开社办。

由比滨似乎是去还不知道从哪借来的理发道具。

社办里只剩我和雪之下，迎接不需要降噪的清澈静寂。

雪之下默默坐着，没在做事。短时间内变幻出各种模样的头发，现在梳理得整整齐齐，披散在背后。

看她那透出一丝安心的表情，可见由比滨的造型服务，对雪之下的身心都带来了正面影响。

可是，她到最后都没绑双马尾。看得出由比滨也在想办法引诱她绑。

刚才虽然几句话就把那个话题带过去了，我重新思考起来。雪之下雪乃绑双马尾的频率明确下降，是从何时开始的——

印象最深刻的，是跟小町一起去幕张展览馆看动物，偶遇这家伙，最后变成去帮由比滨买生日礼物的时候。

雪之下的头发在比平常高的位置绑成两束，大概是假日模式。说到双马尾就是那种发型，平冢老师重现的那个。

美丽女帝突然展现的放松状态，甚至散发一股稚气……不过那样也异常适合她。

然而，愈是回忆就愈觉得，雪之下绑双马尾的频率以那一天为分界点锐减。说不定可以假设那一天就是转捩点。

当时这家伙发生了什么事吗？

是把在「东京猫狗展」上看见的鹫、鹰、隼威猛的翅膀，跟自己的双马尾重叠在一起了吗？

不对，如果她因此深受感动，反而会平常就在绑双马尾吧。

——对喔，我和阳乃第一次见面就是在那一天。

虽然这是个无聊愚蠢的推测，假如她留长头发的部分原因就在阳乃身上……被姊姊看见自己在同学面前绑成这么放松的发型，或许有那么一点影响。

她因此不敢绑本来心情好就能绑一下的双马尾，无自觉地造成压力……不是不可能。

经过漫长的沉思，我看了雪之下一眼，她好像刚好在同一时间看过来，我们不小心四目相交。

雪之下尴尬地开口。

「为这种事沮丧，真不符合我的个性——你在这样想吗？」

「哪会。再说，没人有办法定义为什么事沮丧符合当事人的个性吧。那种东西会视情况变来变去，不负责任的。」

海老名的咨询信里也提到「这样不符合我的个性」，不过符合自己个性的做法，连当事人都未必明白。

更何况，不难过才像自己？连难过这个行为都去在意，硬是压抑住的话，才会引发压力吧。

像我这种人，光是看到光之美少女撞在墙上哭泣都会超难过。

「可是，我还给由比滨同学添了许多麻烦……」

雪之下用微弱的声音说道。

这家伙为了解决众多学生的烦恼奉献了自己的时间，换成自己需要帮助时，却连这点小事都觉得麻烦到人家，为此感到愧疚。

真是容易吃亏的个性。

「发质受损、头发变长、聊了天……对由比滨而言，仅仅是下课时间跟其他女生聊天的话题之一吧。在社团活动的闲暇时间跟社员闲聊——哪会添麻烦。」

似乎是平冢老师叫她写信的，所以我不会直接跟她说「像你这样特地写信咨询，太小题大作了啦」。那个人自己应该也想咨询同样的问题。

「……是吗……不过，和我闲聊占用了她的时间是事实，所以我想要一个结论。不然太对不起她了。」

雪之下面色凝重地思考着。

呃，谁会为闲聊下结论……虽然讲这种话有性别歧视的疑虑，通常那是男生的想法吧？

我搔着头……咦，这样是不是会伤到头皮？总之搔完头后，我掰出一个她想要的结论。

「如果你下次又觉得白头发变多，就当成是身体发出求救讯号，像今天一样放松一下不就得了？」

出乎意料的是，雪之下点头表示同意。

「……以你来说，这意见非常有建设性。我会参考的。」

这么随便的意见被说有建设性，我还真不知道该做何反应。我平常可是在身体发出求救讯号前就先行放松。

甚至可以说我一直维持在放松状态。

总之，姑且算解决了。

那么，尽管是多此一举，咨询信那边也给予同样的回覆吧。

隔天放学后。

我跟平常一样来到侍奉社社办，发现不起眼的异状。

宛如数十万根黑发里面，只有数根的白头发。

没注意到就没差，一旦发现便会立刻被夺去目光。

那细微的异状——是雪之下雪乃的双马尾。

从走廊吹进的风，轻轻吹起两束黑发。轻盈到感觉不出绑起来的头发的重量，彷佛从重力的束缚下得到解放。

窜入鼻尖的洗发精香味，将我的双腿钉在原地。

雪之下只是坐在平常的座位，跟平常一样低头看书，这幅画面却美得像一幅画。

「可以快点关门吗？」

她冷冷斥责我，我努力保持冷静，关上门。死都不能被她发现我不小心看呆了。

「……昨天，由比滨同学不是说想看我绑这个发型？她特地陪我商量，我觉得一直无视她的要求有失礼节。」

雪之下在我开口前先发制人，如此说明。

「是吗？」

我简短回答，坐到位子上。

我不是对此漠不关心，而是好不容易才挤得出这句话。

这家伙把头发绑成两束，其实应该一点都不罕见才对。是物以稀为贵效果吗？

「……而且，比起一直放在心上，换个心情对头发也会比较好。」

雪之下的头发随着她耸肩的动作摇晃。

「其实你偶尔还是会想绑这个发型对吧。」

因为意气用事的关系封印住的发型，需要「让头发喘口气」这种夸张的藉口才能解除封印吗？

所以白头发才告诉她「嘿嘿嘿，雪乃妹妹，忍耐对身体不好喔——」。

干得好，人体。

雪之下将书签夹进文库本阖上书，用手捧起右边的马尾。

「由比滨同学看见不知道会说什么。」

她露出淘气的微笑。

的确，昨天雪之下那么不甘愿，肯定会是出人意料的小小恶作剧。

不过，由比滨会说的话猜都不用猜。

「很适合你——吧？」

「那我会回她『谢谢称赞』。」

嗯，说吧。在本人面前。

雪之下的双马尾再次静静摇曳。大概是有风从缝隙间吹进来。

或者，吹动她头发的……说不定是我用来掩饰害羞的叹息。

16注  漫画《骷髅13》的主角。

17注  指《水户黄门》中的佐佐木助三郎和渥美格之进，两人同为侍奉水户光圀的家臣。

18注  名为阿菊的亡灵「一个盘子……两个盘子……」数着盘子的日本怪谈。

19注  梗出自手机游戏《Fate/Grand Order》。PU为Pick up之意，指抽到特定角色的机率提升。

20注  游戏《纯爱手札》中的女角。

21注  《机动战舰NADESICO》中的女角。

22注  梗出自初音未来的歌曲〈让你未来未来〉。

** 然后，雪之下雪乃（29）重新自问

作者：裕时悠示

『杀了你们。』

男人在电话的另一端说道。

『我要杀了你们。竟然寄那种文件过来，害我老婆和小孩都发现了。你们要怎么赔我？啊？杀了你们，杀了你们——』

我听着从耳机传出的抱怨操作滑鼠。盯着浏览器显示的猫咪影片，是收录各种影片的精选集。

「真的很抱歉。」

我一面任由鼓膜遭到强暴，在脑内跟猫咪嬉戏。单凭声音的话，要怎么跟人道歉都行。这是为了在这个地狱生存下去，社畜锻炼出的演技。

「由于您过了还款日依然没接电话，我们只能寄送书面文件——」

『还敢辩啊！肮脏的高利贷！』

「真的很抱歉。」

喔，是曼切堪猫。

名字很色腿很短眼睛圆圆的。性骚扰虽然是犯罪，它这么可爱也有罪。

『什么丸菱卡贷啊。我看上面有银行的名字才去申请，结果被骗了。根本只是高利贷！』

「真的很抱歉。」

喔喔，布偶猫啊。整只毛茸茸的。不过它太大只，没办法养在家里。

世上存在如此可爱的生物。所以存在一、两个肮脏的高利贷也没关系。这样就达成平衡了。

过没多久，男人安静下来。推测是骂累了。愤怒这种情绪固然激烈，却不持久。是暂时性的。既然如此，让他把怨言吐出来即可。

轮到我了。

我关掉浏览器，跟猫咪道别，开启脑内的开关。

「那么客人，请问您什么时候能还款？」

感觉到男人畏惧了。

『这——』

「若您一直无法如期还款，我们也只能停掉您的卡。本公司同时也有与其他公司共享客户的信用情报，所以您拥有的其他张卡应该也会被停掉。」

感觉到他用手遮住话筒。

「一次有好几张卡被停掉，您会感到困扰吧？有些客人还会因此破产。尽管说这种话逾越了我的本分，我想现在就是一个分歧点。」

他的手从话筒上拿开。

『……可是，六十三万这么大一笔钱，这个月我付不出来。』

语气忽然变温和了。

我乘胜追击。

「那么，要不要考虑分期付款？」

『咦？可以吗？』

「虽然跟平常的规矩不一样，毕竟情况特殊，我们可以商量看看。」

电话另一端传来长长的叹息。

剩下就简单了。我成功和对方讨论出分期的金额及期限。男人乖乖听我说话，起初喷火般的气势不晓得跑哪去了。

挂断电话后，我用电脑打着报告书。

简单整理好事情经过，点开「回收可能性」的资料夹。我输入的是「可能性低」。那人恐怕连分期付款都会拖欠。只要对照电脑中的资料跟我的经验，一目了然。还不出来是迟早的事。不到三个月，他就会冲进日本司法支援中心或消费者中心。分期付款仅仅是把死期往后延。

我叹了口气。

我在这家客服中心已经工作十年了。这种案例看过无数次。不过，至今依然无法习惯。这股徒劳感。彷佛在亲手填好自己挖出来的洞的空虚感。哪习惯得了。

这时，我感觉到背后有其他人的气息。

一名陌生女子低头看着我。

柔顺的黑发。

皮肤很白，瞳色很深。纤细的身躯以深蓝色西装为武装。没错，武装。这个词最适合形容。她的眼神就是如此锐利，站姿也毫无破绽。棘刺过多的蔷薇。冰之蔷薇。

「七十三分。」

她平静地说。在充满电话铃声及客服人员声音的职场，她的声音不知为何清晰可闻。

「冷静的语气是很有说服力没错，但细微的遣词用字还是有不备之处。考虑到你是资历十年的老手，实在称不上令人满意的分数。另外，在处理客诉时浏览与工作无关的网站，违反工作规则喔。」

「你是谁？」

女子递出名片。这么简单的动作，看起来却相当优雅。

「丸菱银行总务部视察委员，雪之下雪乃……噢，是本店的人啊。」

我重新注视眼前这名女子。

丸菱是代表这个国家的巨大金融机构。我们旗下企业的员工，会称呼身为其中心的「丸菱银行」为「本店」。写成汉字是本店，但意思有微妙的差异。

「很不巧的是，我的名片用完了。我是丸菱信贩股份有限公司借贷部门･初期催促组的SV<Supervisor>，松谷七介。」

「我知道。因为我从你电话讲到一半的时候就在监听了。」

看来没必要讲敬语。她的年纪应该跟我一样，或是比我小一点。

「那么，本店的人为什么会在这里？」

「视察。」

雪之下直言。她的声音跟名字一样，冰冷如雪。

「去丸菱集团旗下的各企业视察，吸取经验及改善点。发现化脓的地方就让他们吐出来，清洗干净。就是这样的工作。」

「噢，脓啊。」

我怀着挑衅的意图回望她。

「为此偷听别人讲电话，帮人打分数，还沾沾自喜。视察委员这头衔听起来挺了不起的，结果居然是这么小家子气的工作。」

「要讽刺人的话，该等到你工作做到完美再说。松谷监督。」

「要对现场工作人员指指点点的话，该等到你在这边上过班再说。雪之下。」

听见我这么说，本店的菁英大多都会退缩。八成会将现场工作人员不服从的态度记在心中，跟上司报告。我的考核分数又要被扣了，但我才不管。升迁这种希望，早就被我扔进垃圾桶。

然而，雪之下却点头「嗯」了一声。

意外的是，她看起来并没有被惹火。甚至还在感慨。

「我会记住刚才那句话。」

这时传来柔和的声音。

「那个，不好意思，可以打扰一下吗？」

跟我同一个团队的同事，战战兢兢地举起手。弓滨优梨。是年资五年的主力社员。她轻轻揪住宽松毛衣的袖口。

现在虽然是七月，我们公司冷气开得很强，因此怕冷的女性必须穿厚一点御寒。她身材圆润，经常在哀叹没有适合自己的尺寸。

「松松，刚才那位客人的问题，解决了吗？」

「嗯，我用分期付款让他同意了。」

弓滨的手放在丰满的胸部前，松了口气。圆嘟嘟的雪白脸颊浮现笑容。那张圆脸和白皙的肌肤，让人联想到「雪人」。看了心情会平静下来的雪人。

「真的谢谢你，松松。总是代替我处理客诉。」

从她口中说出来，客诉<Claim>听起来像是「鲜奶油<Cream>」。我每次都会听成鲜奶油，或许只有我这么觉得就是了。

「是对方叫男人来接的，这也没办法。」

「嗯……不过——」

「你有你擅长的领域，这种事就乖乖拜托SV吧。」

弓滨露出意义不明的笑容，然后瞄了雪之下一眼。雪之下轻轻点头致意，弓滨也连忙低下头。

「看，有客人在排了。回你座位去吧。」

「嗯！」

弓滨又说了一次「谢谢你」，回到自己的隔间。

雪之下紧盯着我的脸看。

「刚才那通客诉，原本是她负责的吗？」

我啧了一声，点头。

「是啊。」

「那你要先说呀。」

「最后是由我接手的，所以是我的工作。有问题吗？」

雪之下叹了口气。

「这种事不先说，不觉得很卑鄙吗？前提有改变的话，我说教的内容也会随之改变。」

结果还是要说教嘛。

「你跟我认识的人很像。」

「啊？什么东西？」

「需要注意的意思。」

雪之下转过身，彷佛在表示她不打算继续多说。黑发如同黑暗的面纱般于空中飘扬，害我不小心被夺去目光。

「我会在这边视察到八月。请多指教，松谷监督。」

视察委员讲完想说的话就走了。

我得在那女人的监视下度过一个月以上的时间吗……

本以为没有更惨的职场，结果现实永远超出我的想像。看来这个地狱深不见底。工作地狱。客诉地狱。社畜地狱。

真是，我该堕落至何方。

感情劳动。

继肉体劳动、头脑劳动后的第三概念。

所谓的服务业大多都包括在内。再怎么讨厌的客人，都得以笑容接待。除了肉体、头脑外，得奴役感情——尊严，方能成立的工作。便利商店店员、饭店的柜台人员、护理师、卖报纸的、公家机关的服务人员等等。

以及——客服中心的客服人员。

这恐怕是压力最大的工作之一。某国的资料显示，在负责感情劳动的职业中，客服人员也是堂堂的第一名。完全高兴不起来的冠军。

而在客服这一行之中，我的职场是最惨烈的。立于顶点。

职务内容是催促。

打电话给迟缴卡债的客人催他还钱。我隶属的团队是「初期催促」，以迟缴三个月以内的顾客为对象。

是什么样的工作呢？

简单地说就是「无法得到客人感谢的工作」。

全世界的工作基本上都能藉由「帮上别人的忙」来得到报酬。因此，除了金钱外还能得到「感谢」。谢谢帮忙扫垃圾的清洁人员，谢谢帮忙照顾卧病在床的奶奶的看护。很自然的事。连被人叫作高利贷的缺德金融业者，借钱的时候都有遇过说谢谢的人吧。

然而，催款的工作不存在「感谢」。

有人会哭，有人会怒吼，有人会责骂，其中甚至有会认真跟你说教的顾客。「不能做这种工作喔」、「讨债不是正常人会做的事」。严格来说，催款和讨债不同。这是我进公司时人事部跟我说的。「我们的工作不是讨债喔！放心吧！」。的确不是讨债。因为只有「催人还钱」而已，不是讨债。

我们牺牲感情，获取薪资。

时间已过晚上十点。

我理所当然似的加班了五小时，哀声连连。恶毒的内线电话抓准我终于可以回家时袭来。「松菇SV，请到课长室一趟。」

我一面诅咒神明一面敲门，在里面等我的是叶冈有人课长。他和我同年，但这位可是菁英人士。在这个年纪已经升职到管理阶层。他是丸菱银行的常务还是专务的儿子，据说在现场累积过经验后，就有与之相应的地位在集团的上级企业等待着他。

「抱歉，在你要离开时把你叫过来。」

课长五官端正的脸上浮现笑容。大部分的女性兼职员工，都会因这有如演员的笑容而沦陷。他是女性员工占七成以上的本部门的绿洲。我们跟其他部门比起来，离职率低了一些，据说就是拜他的笑容所赐。

身为男性的我完全无法从中获利，被他任意使唤。

「今天，丸菱银行的视察委员有到你那边对吧？」

课长不会用「本店」这个俗称。他就是这样的人。

「嗯，是的。一个姓雪之下的人。」

「她好像是某位议员的千金。丸菱银行似乎也觉得她很有前途。」

我只回了句「这样啊」。感觉不到表现出敬佩的必要性。外表、能力、身份，全是跟我活在不同世界的公主殿下。

「那位雪之下小姐希望以你的团队为中心视察。明天起麻烦帮她准备她的座位。」

「请她找个喜欢的地方坐就行。上个月有两个人辞职，我这边空到不行。」

叶冈露出苦笑。人手不足对他来说也是烦恼的源头。

「麻烦你啰，松菇。」

「我性松谷。」

「松谷，明天上午的会议我也会请她来参观。」

我好不容易才忍住不要发出「呜呃」的声音。

「是我建议的。你的团队感情很好，最适合给人视察对吧？」

叶冈笑咪咪的。他是知道「真相」呢，还是不知道呢？这个人的心实在很难猜。

「……后果自负喔。」

扔下这句话就是我的极限，反正我无权拒绝。

早班、上午班、下午班、夜班。

我们基本上都是以这四种型态排班。

上午班是十点要到公司，所以时间比较充裕一些。前一天熬夜看深夜动画也无所谓。只不过，最近连熬夜这件事本身都让我有点吃不消了，还会不小心在电视前面睡着。本来想说那就录起来假日再看，但假日我会睡一整天，到头来还是没办法看。宅宅就是这样慢慢变成社畜。

于是，上午班。

我在离上午十点只差那么一点的时间来到公司，一名长发女子正坐在我的座位上处理客诉。

这名女子不是公司员工，也不是打工的。

雪之下雪乃。

她挺直背脊坐在那里。

戴着耳麦，冷静地对麦克风说话。嘴上反覆说着「十分抱歉」、「失礼了」等道歉的话，表情及身体却一动也不动。

即使是讲电话，道歉的时候依然会忍不住低头。弓滨优梨经常像有点诡异的节拍器一样，头晃来晃去。我也会微微收起下巴。

这个雪之下却不动如冰雕。

不对，该称之为「冰墙」吧。她用那冰冷的美貌，将顾客的抱怨反弹回去。

数分钟后，电话挂断。

处理完客诉通常都会叹口气，她却连一口气都没吐。神情自若，以流畅的动作开始打报告书。

「……你在做什么？」

我开口询问，雪之下瞥了我一眼。

「看不出来吗？在处理客诉。」

「我问的是为什么身为本店员工的你在做这种事。」

雪之下歪过头。

「是你说的呀。『要对现场工作人员指指点点的话，该等到你在这边上过班再说』。我只是听从你的忠告罢了。」

我怀着看见新种动物的心情，凝视眼前的女人。

「你真不像本店的人。」

「这句话我就当成称赞了。」

她拿下耳麦，轻轻甩了下头。清爽的香气随着她的动作飘散。

「客诉内容是？」

「住在千叶的四十岁男性。因为文件没寄到而打电话来。发现是顾客自己误会后，转为抱怨我的态度。」

「常有的事。那种客人只是想靠找别人的碴发泄自己的压力。」

「他跟我抱怨『为什么你的声音不是东山奈央』，由于实在太有趣，我就回了『为什么您的声音不是江口拓也呢』。」（注23）

「……你满有种的嘛。」

原来如此，看来她不是一般的千金大小姐。

雪之下从座位上起身。

「接下来要开会对吧？松谷监督，小心不要迟到。」

然后转身离去，长发在空中拖出一条尾巴。

回过神时，周围的员工都在盯着这边。在这个时段上班的人全是女性，照理说不会为雪之下看得出神，不过，她似乎拥有引人注目的某种特质。

我清了下喉咙说：

「三十分钟后开始开会。麻烦大家到第一会议室。」

她们「是——」给予有气无力的回应。

说是会议，其实结果早就能预料了。千篇一律的业务联络、根本没必要说的注意事项。小学班会搞不好都比较刺激。年纪愈大，感性就会被磨得愈来愈迟钝。

然而，今天总觉得会发生什么事。

平常不会发生的事。

宛如盛夏的白雪。

我踏进会议室时，已经有十位左右的员工在里面集合。

会议室的座位也能如实呈现人际关系。资历十年以上的老鸟统统集中在窗边最后面的位子。另一侧稍微靠后的座位，是能干的年轻职员，其他新人和业绩不怎么样的员工则分散各处。据说三个人聚集在一起就能形成派系，看到这个画面，可以说一目了然。

「嗨，松松。」

弓滨优梨在窗边最前面的位子轻轻挥手。用像猫一样微微握拳的手对我招手，叫我过去。身为一个猫控，不可能抗拒得了这个诱惑。

我坐到她旁边，她开心地跟我搭话。

「欸，今天的会议要讨论什么？」

她总是面带笑容，不知道有什么好开心的。在这如同地狱底层的职场，大方地散播阳光。

「反正八成跟平常一样。倾听课长宝贵的建议和公布上个月的业绩。」

「这样呀——好像在上学喔。」

弓滨趴到桌上。

「好烦喔。我上个月业绩也是勉强才达标——」

「有达标不就得了？因为还不还钱得看顾客的意愿。」

催促员工的业绩，会用「回收率」来表示。简单地说就是「自己负责的客人有没有还钱」。一百名顾客中有一百人还钱，回收率就是百分之百。不过这种事不可能发生。业绩好的人，回收率大多落在百分之六十五到百分之七十。

「可是——还是有回收率很高的人呀？小胜美之类的。」

「……是啦。」

弓滨轻飘飘的头发在毛衣的肩膀处摇晃。她的肩膀不时会发抖，那个位子会直接吹到冷气。既然如此，换个地方坐就行了，可是开会的座位是靠派系决定的，不能自由移动。明明她比其他人更怕冷。这种重要的事不先说，我觉得有点卑鄙……咦？这是谁说过的话？

「那里很冷吧，我跟你换位子。」

「哇，松松好温柔！」

弓滨睁大眼睛。

「万一你感冒，班表就会空出来。到时被课长骂的是SV。」

SV就是所谓的现场监督。听从课长的指挥，在现场统率兼职人员。管理班表也是工作之一。

在我们换好位子时，背后传来声音。

「你们感情还是一样好呢。」

「咦？」

弓滨回过头，视线前方是一名浓妆女性职员。

相扑胜美。

她带着三名跟她一样浓妆艳抹的伙伴——不，是手下，奸笑着。我实在不喜欢这个笑容。手下在旁边窃窃私语的声音也非常刺耳。还有香水的味道。呛鼻的味道。

「没有啦，不是你想的那样。」

弓滨用不着化妆就很白的脸颊染成红色。

「咦——？那是怎样呢？嗯？」

她回头征求手下的附和。然后对我投以意味深长的目光，再度露出奸笑。

真是……

就是因为这样，我才讨厌女人的职场。

讲几句话就会传出无凭无据的谣言。你是光跟女生说话就会认定那两个人在交往的小学生吗？弓滨说得没错，这里是学校。充满屁孩的小学。

我正准备开口反驳，会议室忽然恢复静寂。

雪之下雪乃走进会议室。

走路没发出半点脚步声的姿态、静静摇曳的黑发，令众人停止呼吸。我也不小心看得出神。有种看见白雪纷纷飘落的感觉。

雪之下看见我，脚步停止了一瞬间。然后瞥向相扑。相扑明显被她的气势震慑住，像被推倒似的往后退。雪之下兴致缺缺地移开视线，坐到对面靠走廊那一侧的最前方。坐在她隔壁的男性学生打工族吓得往旁边挪了一个座位。

「那是怎样。」

相扑不爽地咕哝道。大概是被雪之下的态度或外貌，抑或两者皆是而惹怒了。她命令手下坐下，占据走道侧偏后方的位子。

会议室的门再度打开，叶冈课长走了进来。踩着彷佛要秀出一双长腿的步伐，站到白板前面。全员的视线都集中在他身上，他先是打了声招呼，开始召开会议。

宣布完几项联络事项后，接着公布上个月的业绩。对员工来说就是成绩单。成绩好的人能拿到奖金，对想转正职的兼职人员而言，则是人生的分水岭。

叶冈用帅气的声音朗读。

「六月的回收率第一名，是相扑胜美小姐。」

周围涌起掌声，相扑得意洋洋地站起来。在帅哥的注视下，化了妆的脸泛起一抹红潮。

「相扑小姐，如果有什么回收的秘诀，可以请你跟大家分享吗？」

相扑左右扭动她过瘦的身体。这啥？求爱舞？

「咦咦？没有啦。人家……我最重视的是跟客人聊得开心，说不定是这个工作态度碰巧带来了好结果？」

她讲话跟纳豆一样，每个字都黏在一起。

虽然我真的很讨厌她，她的业绩优秀是事实。我监听过她跟顾客的对话，内容很普通，不知为何回收率却高得吓人。

因此，她在这个团队拥有极大的发言权。

连身为SV的我都反抗不了她。

这也是还是年轻兼职人员的她，能以「女王」身份君临此地的原因。

业绩公布完后，叶冈看着雪之下说：

「我想大家应该都知道了，银行的人从昨天开始要到我们这边视察。」

雪之下一站起来，我就感觉到大家屏住气息。听见旁边的弓滨吞口水的声音。

「我是丸菱银行总务部的雪之下，会做好视察委员的工作。」

她说完这句话就坐下了。

周围传来吱吱喳喳的交头接耳声。还听得见「这人感觉好讨厌喔」这样的窃窃私语。用不着回头都知道是谁说的。

叶冈清了下嗓子，以掩饰尴尬的气氛。

「就是这样。请大家和她好好相处。」

是——众人给予懒洋洋的回应。唉，愈来愈像小学了。

雪之下的职位就是「风纪股长」吧。

那么。

身为屁孩代表的我，该如何行动呢？

一星期后。我按照惯例加班，时间超过晚上十点时。

「班表管理得太松散了。」

啊——回家吧回家吧快点回家吧，在我登出的时候，降下一阵冰雪。这家伙也加班啊。

「请问本店小姐有何贵干？」

我毫不留情地冷冷回问，她却文风不动，将工作用平板拿到我面前。

「你的团队班表遵守率低于八成的有五个人。这种随便的出勤状况，你怎么有办法允许？」

「管太严的话他们会辞职，这样就得不偿失了吧。本来就是靠不足的人手在想办法排班了。」

「这跟那是两回事。没秩序的地方拿不出亮眼的成绩。」

累到不行的时候有人来找你高谈理想，会燃起一把无名火。

在我心想「今天绝对要直接跟她说清楚」而站起来的时候，听见好笑的喷嚏声。我和雪之下反射性望向声音来源。是已经关灯的休息室。

「啊，喂，我还没说完……」

我无视雪之下的制止，迈步而出。踏进只有间接照明的昏暗休息室，看见一个雪人在角落的冰箱前面窸窸窣窣动来动去。

「……弓滨，你在做什么？」

拱起来的背部抖了一下。

弓滨优梨拿着尼龙纤维抹布，回头露出苦笑。

「擦冰箱。」

「呃，看就知道了。」

我搔着头回忆。员工会轮流一个月清一次共用冰箱。记得这个月应该是轮到相扑胜美才对。

「小胜美说她今天有事，请我代替她。」

「有事？」

「她说她要跟审查部的人去涩谷喝酒。」

「啥？之前不是才喝过？」

「嗯……他们感情好像很好。」

弓滨朝发红的手哈气。尽管现在是盛夏，帮冷冻库除霜还是会冻成这样。

「不过，为什么会选在这种时间？」

「我忙传真忙到刚刚。今天超多的——」

「可是今天轮班的本来就不是你啊。」

「嗯，那也是小胜美她说……」

我再度叹息。

然后对晚来一步的雪之下说：

「刚才那句话我收回。」

「什么？」

「班表得好好遵守才行。你说得没错。」

我从冰箱旁边的收纳柜拿出酒精喷雾和厨房纸巾，用喷了酒精的纸巾擦掉冰箱外侧的污垢。

「松松？」

「快点搞定吧。」

弓滨「唔」哽咽了一下，接着「嗯！」露出笑容。

我抱着有棱有角的大冰箱奋力擦拭，一只雪白的手忽然伸过来，将如同象牙工艺品的手指探进积满灰尘，谁都不想碰的墙壁与冰箱的缝隙间。

「雪之下，怎么连你都——」

「不是要快点搞定吗？」

我们默默拼命擦拭冰箱。成熟的大人暂时埋头于连加班费都拿不到，不在工作范围内的「侍奉」上。

看着好不容易变干净的冰箱，弓滨「好！」高兴地微笑。光是看见她的笑容，就有种疲劳得到缓解的感觉。

话说回来——雪之下开口说道。她正在用手帕擦拭额头的汗水。

「弓滨小姐为什么要听相扑小姐的话？拒绝不就行了？因为她业绩优秀吗？」

听得出她的言外之意是「你是不是被她握住什么把柄？」。

弓滨的回答很简单。

「因为我跟胜美是同期。」

「就因为这样？」

「她是我唯一的同期。同年进公司的人，已经只剩我和胜美了。」

就我看来，相扑是个讨人厌的人，弓滨却有其他看法。果然会对同期有特别的感情。我那两位同期也全灭了。一个人转行，另一个人得了心病。不知道他们现在在哪里。

「我明白了。」

雪之下平静地说。

「可是，有时这种善意对对方反而不会有好处。劝你最好记住。」

「嗯……谢谢。」

雪之下看着跟自己道谢的弓滨，眼神忽然变得温柔。彷佛在注视怀念之人。

「刚才我听见你打了个喷嚏，还好吗？」

「啊，嗯。没事没事。」

「这间公司冷气太强了。松谷SV，请你想点办法。」

「去跟大楼的管理公司说。」

对我倒是冷漠得毫不留情。

弓滨的治愈气息，连本店小姐都受不了吗！

隔天下午。

上晚班的弓滨来到公司时，早班的相扑大步走向她，面带怒色。

「我接到这位客人的投诉。」

弓滨错愕地盯着相扑递给她的传真纸。

「你把这份文件传真到其他客人那边。搞错编号了对吧？」

「咦，真的假的。」

弓滨接过传真纸，用自己的电脑搜寻编号。她盯着萤幕看了一段时间，不久后沮丧地垂下肩膀。

「对不起……原来是同姓的客人。」

「那又怎样？发送前念一遍名字和顾客编号，不就能预防了吗？你害我被骂了一顿耶。欸，你要怎么赔我——？」

相扑喋喋不休地责问她。她的语气及用词都令人不悦。附近的员工也都皱起眉头，但相扑一瞪过去，他们就连忙移开视线。在这个职场，惹到女王意味着死。

我从SV座上起身，介入其中。

「适可而止吧。大家都在看。」

相扑狠狠瞪了我一眼，扬起过于鲜红的嘴唇。是爬虫类的笑容。

「好好喔——优梨，SV先生会护着你耶——跟人家打好关系，这种时候就很有用对不对——？嗯——？」

弓滨不知所措，视线在我和相扑身上来回移动。

我克制住想对这个埃德蒙女（注24）怒吼的冲动，表面上无视她，指向墙上的电子布告栏。上面显示着排队人数——「有几位客人在线等候」。

「有五位客人在等，请尽快协助！」

弓滨猛然回神，反射性按下电话的开关。「您好。我是丸菱信贩卡贷部门的客服人员，敝姓弓滨。」在这种状况下，她依然能立刻用平常的语气接电话。温柔的声音缓和了听者的情绪。弓滨乍看之下靠不太住，其实是个非常优秀的员工，我很清楚。

相扑忿忿不平地瞪着弓滨。我又喊了一次「请尽快协助！」相扑便心不甘情不愿地回到自己的座位上。

真是……

相扑的回收率虽然是第一名，我对她的评价却很低。在回答顾客问题和处理客诉的部分，远远不及其他客服人员。例如像刚才那样，电话响个不停的时候，她也不会第一个接电话。她拿拔群的业绩当盾牌，不听SV的指示。

疯狂的来电告一段落时，背后传来冰冷的声音。

「相扑小姐的存在，对这个职场而言称不上有益处。」

喔，是吗——我边用电脑边回答。不必回头也知道。我只认识一个女人能发出如此冰冷的声音。不知道她从何时开始监视的。

「你竟然会讲这种话。真意外。」

「意外？」

「因为，相扑的回收业绩超好的喔。对你们本店的人来说，远比弓滨更有用吧。」

「——前提是她的业绩是真的。」

她的语气转为轻声呢喃。

我下意识回头，抬头注视雪之下白皙的脸庞。

「这话什么意思？」

「我监听过好几次她接待顾客的电话，找不出特别之处。跟照稿念一样——不，考虑到她有时会忘记讲敬语，或是口气变随便，分数差不多位于中下。这样回收率还能那么高，只能说不可思议。」

「用不着你说我也明白。可是，她业绩好是事实啊。」

是吗？雪之下像在自言自语般嘀咕道。她将雪白的手放到脸颊上，彷佛在沉思。

「你在想什么？」

她没有回答。

「不懂现场的本店能看出什么啦。拜托你别闹事。」

我故意挖苦她，却被雪之下无视。她的思绪已经飘到另一个世界。即使在同一个空间，脑袋里想的事也不一样。价值观不同，着眼点不同。看着她小巧的脸蛋，我深深体会到人类有显而易见的差距。

站在遥远高处的冷酷女神，会对这个地狱下达什么样的制裁——

于地面爬行的社畜无从得知。

一星期后的午休时间。

我在休息室角落吃便利商店的饭团，手中是预计明年度开始采用的新讲稿资料。好像是雪之下以这次的视察为依据，跟高层建议的。哦，确实写得很好。好到让人火大。海苔屑散落于白纸上。等等跟这份资料一起扔进碎纸机吧。

挤了约三十人的休息室，充满嘈杂的交谈声。毕竟这个职场女性比例高，跟女校一样吵的环境，男性不可能受得了。因此绝大多数的男性员工都会逃到外面吃饭。我也是这类型的人，但我这个月在手机游戏上花太多钱，现在手头很紧，所以无法逃离。

五人的女性团体，占据了充满女性的休息室的正中央。

是业绩第一的相扑胜美大人一行人。

她们用如同栖息在丛林深处的珍鸟的声音，吱吱喳喳叫个不停。「男人」、「年收」、「升迁」等词汇断断续续地传来。啊——烦死了。早知道就去吃牛丼。

弓滨也在那个小团体之中。不过，听不见她的声音。她始终只有轻轻点头应声。我也想过这样真的开心吗？但她的角色在团体中是不可或缺的。女性聊天时会希望得到「这样呀，好厉害！」之类的附和。

粗野的大叔声音突然介入尖锐的交谈声中。

「相扑！有空吗？」

是个顶着快要撑破的大肚子，六十岁左右的大叔。油光满面的脸上挂着懒洋洋的笑容。是涩谷的审查社社长，记得名字叫……叫什么来着？我记得他的绰号是「惠比寿」。

「咦——部长，找我有事吗？」

相扑发出陪酒女般的声音站起来。惠比寿社长也笑咪咪的。你是有寄瓶喔。

「我有事要跑一趟千叶，就来顺便看看你。你在涩谷的评价也不错喔？大家都说你是连续三个月回收率第一的王牌。」

「讨厌啦——别说了——大家都在看耶——」

相扑亲昵地拍着部长的肩膀，脸上写着「继续！继续夸我！当着大家的面夸我！」。在这个地狱待久了，别人的真心话都会以字幕的形式显示出来。

「怎么样？要不要九月考考看升正职？（译：如你所愿夸你几句，收下吧。）」

「嗯——我确实觉得是时候了，可是我应该考不过吧～（译：既然你这么说，应该会给我一些方便吧？嗯？）」

「选你准没错，我会帮你做担保！（译：如果你因为我的关系考上正职，知道该怎么感谢我吧？咿嘻嘻。）」

「意思是审查部会帮我推荐啰？太棒了♪（译：这跟那是两码子事吧？算了，等那个职位到手就是我的啰——咕呼呼。）」

唉……

能满不在乎地进行这么不要脸的对话，金融机关听了都会傻眼。之前那个顾客说得没错。肮脏的高利贷。

惠比寿社长离开后，相扑的跟班们异口同声拍起她的马屁。「好好喔——正职！」「我也想离开千叶这种鬼地方——！」先不论她们心中是怎么想的，每个人都面带笑容。

只有一个人例外。

弓滨优梨。

她勉强扯出笑容，不过远看都看得出她的笑容很僵硬。

「小胜美要去涩谷吗……？」

无精打采的声音很不像她。

相扑坦率地点头。残酷的是，只有这个时候，她的笑容显得很可爱。

「因为人家一直想去审查部嘛！所以才这么努力催款。现在终于有了回报！（译：谁要在千叶这种乡下地方跟人讨钱啊。我先闪了。）」

看来字幕还没关掉。

然而，这么好懂的真心话，就算不是我也看得出来吧。

「这样呀……太、太好了！」

弓滨脸色很差。

同期要去涩谷，令她大受打击——看起来不只是因为这样。仔细想想，最近她的状况一直不太好。

吃完午餐，相扑她们回去工作了。弓滨却独自坐在椅子上，呆呆凝视手中的手机。圆圆的背部显得比平常更加娇小。

正当我出于担心，想跟她搭话时，她的身体忽然倒下。

趴在桌上一动也不动。

「喂，弓滨？没事吧？」

「嗯，我没事。我……没事。」

走近一看，她额头冒汗。眼睛也像小狗一样水汪汪的。她发烧了。

「今天我算你早退，去里面的午休室睡一觉吧。」

「不行啦——这样没人补我的空缺。」

「你工作到一半昏倒才更麻烦。」

我半强迫性地带弓滨到休息室旁边的午休室。约两坪的昏暗空间中，放着一张大沙发床和棉被。我把门开着。

「对不起喔，松松。」

弓滨坐在沙发上说。她将代替枕头的靠垫放在大腿上，身体缩成小小一团。看到总是朝气蓬勃的她这么没精神，我也于心不忍。

「刚才那件事，你受到打击了对吧。」

我问，她略显犹豫地点头。

「你可能会觉得我是个嫉妒朋友出人头地，心胸狭窄的女人……」

「不会啊。」

我明白原因不是那个。她是在为其他事受到打击。

「原来只有我把她视为同期，对她产生同伴意识。单相思。哈哈，我被甩了。」

「……」

我不知道该跟她说什么。那句话宛如冰冷的石头，沉入我的心中。单相思。

敲门声传入耳中。

转头一看，雪之下雪乃抱着胳膊站在那里。

「松谷监督，在这种地方和女性员工两人独处，是不是太欠缺考量了？」

「所以我没关门啊。」

呣——雪之下点头。「以你来说还挺聪明的。」她边说边蹲在弓滨旁边，看着她的眼睛。

「你看起来很不舒服，所以我之前才提醒过你。」

语气温和。这家伙果然很宠弓滨。

「啊哈……对不起。该怎么说呢，有点，精神受到打击。」

「精神？」

雪之下的视线移到我身上。彷佛在叫我说明。

我将在休息室的对话一五一十转述给她，雪之下板起脸来。

「审查部的部长为什么跟区区一个客服中心的员工那么熟？我觉得不太自然。」

「小胜美人脉很广，她常去参加派对和联谊。」

我同意弓滨这句话。

「每年会跟涩谷的本公司举办几次类似联谊会的活动，撮合那边的年轻男性社员和我们这边的女性兼职人员。也有几位员工因此而结婚。」

让男性社员早点结婚，努力工作——这似乎就是本公司的方针。不过在客服中心上班的我，从来没享受过这种好处。

「那位部长六十岁左右了吧？还没结婚吗？」

「当然结婚了啊……不过，嗯，你知道的。」

男女一旦相遇，有时会建立起不恰当的关系。难道办派对也是为了这个目的——这样想好像太牵强了。

然而，雪之下并没有被说服。

「上午，我又调查了一遍相扑小姐的通话纪录。」

「你还真烦人。问几次都一样。我也监听过好几次她的电话。」

「嗯，通话内容没有可疑之处。我注意的是更之前的事。」

「更之前？」

雪之下点头。

「打电话催款前，她会花很多时间准备。登入好几次顾客资料库，搜寻资料。次数是其他员工的好几倍。我记得工作守则上写的是『按照系统给的顺序打电话给顾客』对吧？」

「嗯，基本上是这样。」

系统会显示「先打电话给这位顾客吧」、「接下来是这个人」、「下一个换他」。员工要听从指示打电话。

「但她没有听从指示的迹象。特地在打电话之前搜寻顾客资料，仔细调查某些情报。我必须说这个行为相当不自然。意即——」

雪之下的视线变得更加锐利。

「相扑小姐在挑客人。藉由某种手段区分出比较好催款的客人，以那些人为重点打电话。我得出这样的结论。」

我忍不住叹气。

旁边的弓滨也一脸错愕。

「还以为你发现什么了不起的秘密，原来是这点小事……」

「这点小事？」

「我说，大家多少都会挑客人啦。根本没人会对系统的指示照单全收。」

犹豫了一下，弓滨也跟着开口。

「我也会稍微挑个……我实在不擅长应付讲关西腔的客人，所以如果系统叫我打电话给他们，我都会跳过去。」

在我们这边是常有的事。很多女性员工不喜欢讲话比较粗鲁的关西地区的客人。有时候会因为大家都跳过他们的关系，由我加班一次把关西腔听个够。

雪之下无法接受，继续发表她的见解。

「可是弓滨小姐，你不会为此刻意登入资料库查询吧？」

「是没错。」

弓滨困惑地将视线移到我身上。

「不过雪之下，你的假设有很大一个漏洞。」

「漏洞？」

「她怎么看出好催钱的顾客？如果能做到这种魔法般的事，我们也用不着那么辛苦。」

凭单纯的资料就能区分愿意还钱的顾客，再怎么说都不可能。讲过电话后是可以判断出这个人有希望或没希望，但在那之前是办不到的。

这次，雪之下没有反驳。她只喃喃说了句「是啊」就陷入沉默。

「啊，不、不过，小胜美直觉很敏锐，说不定她真的有那种力量。超能力之类的！」

弓滨彷佛在给她台阶下，着急地摆动四肢。体态圆润的她做这种动作，看起来像倒在地上拼命试图爬起来的雪人。

雪之下嘴角浮现一抹浅笑。

「不好意思，打扰你了。弓滨小姐，好好休息吧。」

我们一同离开午休室。

休息室已经没有半个人。鸦雀无声。

「她是个好孩子。」

雪之下轻声说道。我不认为有必要特地赞同。

「既然你这么觉得，就别管相扑了。就算她那副德行，对弓滨来说，她还是重要的同期。」

「这两件事不能混为一谈。」

雪之下说道，嘴角的笑容已经消失不见。

「我只会把我的工作做好。履行视察委员的职责。无论会被谁怨恨。」

这种说法莫名令人火大。

我面向冷酷的雪女，瞪着她。

「真了不起。摆出一脸自己最干净、纯洁无垢的表情，像这样高高在上地鄙视我们，很好玩吗？」

「我并没有鄙视你们。你会这么觉得，是因为自己有自卑感吧？」

「这种态度就叫鄙视。」

我好不容易才控制住音量，不能吵醒在午休室的弓滨。

「在你眼中，这里或许是扭曲的职场，不过包含相扑的存在在内，全是必然的调和。那种女王哪个职场都有。相扑离开后，又会有另一个女人坐到那个位子上，对其他人颐指气使。如果有看不顺眼的人就要一一排除，客服中心根本无法运作。所以维持现状就行。什么都不变是最好的。」

我怀着「你懂吧？」的意图凝视她。

雪之下却一口回绝我的「要求」。

「我之前就想问，你对于做这份工作感到自豪吗？」

「怎么可能。」

我不屑地说。

「怎么可能。做这种工作哪可能自豪。牺牲感情、牺牲尊严换取金钱。工作了近十年，从来没被客人感谢过。去死、守财奴、恶魔，这种骂人的词汇倒是听过几万遍。每个人其实都不想借钱的，会想一直隐瞒下去。而故意揭发这个秘密就是我们的工作。对这种工作感到自豪？少乱扯这种好听话！」

我再也控制不住音量。

「雪之下，你又如何？摆出一副『我是本店大人喔』的架子，自以为风纪股长，评论旗下企业的失误及缺点，跟上头告状。为其他人的工作态度打分数，以此为乐。你说得出自己对这样的工作感到自豪吗？你说啊⁉」

雪之下一语不发。垂下修长的睫毛，嘴唇抿成一线。我还以为她会激烈反驳，这句话这么有效吗？

她再度开口。

「再说一次。」

「……啥？」

「再说一次你刚刚说的话。」

我回望雪之下的脸。

「『少乱扯这种好听话』？」

「不是那句。再前面一点。」

我想了一下后回答：

「『每个人其实都不想借钱的，会想一直隐瞒下去』这边吗？」

雪之下点头。

「是吗……原来如此。『想一直隐瞒下去』。原来如此，我都没想到。」

「什么东西？」

雪之下轻描淡写地说：

「我从来没借过钱，也没贷款过。所以才会没想到。原来如此，债务人会有这样的想法呀。」

「……」

就说了，这种态度就叫鄙视……

呃，这女人好像有点天然。本店、视察委员那些头衔都是后来才附加上的。她天生就是活在云端的人。

雪之下将傻眼的我晾在一旁，快步离去。

「喂，你在想什么？」

她没有停下，于背后摇晃的黑发逐渐远离。

「说话啊！雪之下雪乃！」

她终于回过头。

从她口中传出的话语却冰冷如雪——

「讲什么都没意义。」

她拿出卡片解除门上的电子锁。

「就算我说出类似解答的话，你也不会服气吧。人不会因为言语而行动，不会因为言语而改变。」

「那你要怎么做？」

「重新自问。」

她如此说道，彷佛要告诉自己。

「没错。我要重新自问。无数次地重新自问青春时期的那个问题。」

在那之后，平安地度过了一个礼拜。

我还想说雪之下肯定会有动作，所以挺意外的。本以为她会揭发相扑业绩第一的秘密，开会谴责她。然而，她只是默默继续视察，仔细寻找失误，跟我抱怨。一如往常。

结果，并没有发现不正当的行为。

什么事都没发生令我松了口气，同时也觉得有点遗憾。我为这样的自己感到惊讶。我在期待那个冷血女做什么？改变这个地狱吗？可笑至极。没有比社畜作的梦更可笑的东西。

弓滨的身体状况也恢复了，表面上跟平常一样在工作。她和相扑的关系也没有变化。尽管孕育着各种欺瞒，只要她还待在这个地方，她们就是同事，是同期。一如往常。这样就好。

八月也快过完了，雪之下的视察剩下数日。

今天一大早就排了定期会议。除了跟上个月一样会公布业绩优秀的人外，还会公布跟员工募集的「提升职场士气的标语」。这是叶冈课长提议的。「大家」一起想，「大家」一起努力。人人为我，我为人人。那位大少爷菁英很喜欢这种好听的题目。

带着温和笑容站在台上的叶冈，对聚集在会议室的我们说：

「总共收到十五封来信。谢谢大家在百忙之中抽空参与活动。每个人想的都很好，不过我想跟各位介绍我特别喜欢的一句——相扑胜美小姐。」

是——相扑发出兴奋的声音站起来。

「可以帮我念一下你想的标语吗？」

「咦——我有点不好意思耶。」

「没什么好不好意思的。那句标语非常棒。」

相扑被叶冈夸得红了脸。跟被那个惠比寿部长称赞时判若两人，是发自内心的。尽管想出人头地，女人果然对帅哥没抵抗力。

相扑清了下喉咙，得意洋洋地说：

「『绊～大家同心协力的客服中心～』。」

我差点忍不住发出「呃啊」的声音。

这家伙脸皮真的有够厚……

其他员工也都眼神死了。相扑把一堆杂务丢给弓滨做，是众所皆知的事实，只是大家都因为害怕她，装作没看见。不知情的人只有课长一个。

「我觉得很棒。羁绊。正因为是流动率高的职场，才要多加珍惜。」

叶冈一拍手，其他人也跟着鼓掌。相扑愈来愈得意，鞠躬行了一礼。全是闹剧。这里没有任何东西是真的。没有真物。全是伪物。

这时，一只雪白的手静静举起。

彷佛要对这场充满虚伪的舞台剧提出异议，笔直举起的那只手——是雪之下雪乃。

叶冈问：

「雪之下小姐，请问有什么事吗？」

「其实我也想了一个标语。接在相扑小姐后面实在不太好意思，不过方便让我发表吗？」

相扑挑了下眉。

「那真是太棒了。请说。」

「谢谢。」

雪之下站起来，紧盯着相扑。由于相扑也盯着她，刚好形成两人互瞪的情况。会议室充满令人窒息的沉默。

「『人～仔细一看，半边的人在纳凉的客服中心～』。」

世界冻结。

没人出声。相扑、叶冈都只是愣在原地，我当然也一样。弓滨的嘴巴甚至张大到下巴都快脱臼了。

「……可以请你说明吗？」

叶山终于开口。

雪之下冷静地说：

「我们常说『人』这个字是两个人互相依靠——其实是其中一人靠着另一个人。容忍某些人的牺牲。没错，例如把麻烦的杂务扔给同事，自己靠不当手段提高业绩，企图一个人升迁。我认为这句标语很适合有这种人在肆虐的职场。」

叶冈整张脸垮了下来。

「那句标语真的是你想出来的吗？雪之下小姐。」

「不。是我的——高中同学想到的。」

她的目光忽然变得柔和，像在缅怀遥远往昔的目光。

下一瞬间，那抹温柔消失了。

视察委员冰冷的视线贯穿相扑。

「相扑胜美小姐，你知道我在指什么吧？」

「啊？」

尖锐的声音自相扑的薄唇传出。

她接着用甜美的声音对叶山说：

「我听不懂她在说什么。这个人误会了。」

「现在是我在说话。给我面向这边。」

雪之下语气严厉地说。

「相扑小姐，你在工作方面有不正当的行为。」

「所以？什么行为？」

「你业绩第一的秘密。」

会议室一阵骚动。每个人都为雪之下扔下的炸弹大吃一惊，瞪大眼睛。我也很惊讶。我有自信我是在场的人里面最惊讶的。

难道她发现了？

「魔法」的机关？

在众人的注目下，雪之下从公事包里拿出一叠厚厚的文件夹。随便找一家文具行都有卖，平凡无奇的东西。蓝色塑胶封面上一个字都没写。

「这是这半年来，你打电话催款的顾客清单。」

雪之下顺口说出的那句话，又在会议室内引起一阵骚动。

我们一天会打一百通以上的电话。那是规定门槛。她把半年份的资料调出来了？就算有重复的顾客，数量也不会只有一、两万而已。而她独自将那些资料统统调查过了吗？

「我仔细看过这份清单，发现一件事。你成功拿回借款的顾客，将近半数都符合某个条件。人数多到无法以巧合来解释——你自己心里有数吧？」

「你够了喔！」

相扑尖声大吼。

「什么条件？能讨回借款的条件？哪有那种东西！在这里工作的人都知道吧？根本没有那种魔法！」

「不。有的。」

雪之下说道。

她静静望向我。

「非常遗憾的是，这不是我靠一己之力想到的。要是没有工作经验丰富的松谷SV的意见，我大概想不到这个答案。」

大家的视线集中在我身上。

但我毫无头绪。我给过她意见？什么意见？

「他跟我说过，『借钱是丢脸的事，不会想被别人知道』。本来就没钱可还，或是没打算还钱的顾客暂且不提，这个初期催促组的顾客，大多是程度较轻微——『有钱还，不过想拿它当生活费』的人。意即只要有那个意愿就还得出来。只要加上『绝对不想被其他人知道』这个理由，会怎么样呢？即使有点勉强，客人也会愿意还钱吧？」

「满有道理的。」

叶冈说。

「可是，绝对不想被其他人知道的借款是什么？我们负责的主要是购物贷款，金额顶多数十万到百万日圆。这点钱就算被家人或职场知道，也不会有多严重的后果。」

「但其他人总是会问的吧。『你买了什么？为什么借钱？』对不对？相扑小姐。」

相扑像在看待仇敌似的瞪着雪之下。

叶冈着急地问：

「我抓不到重点。买了什么东西会不希望被任何人知道？你说的『某个条件』是？」

「答案是——」

雪之下开口。

说出决定性的答案。

「包茎。」

所有声音顿时从会议室中消失。

和刚才的沉默截然不同。大家带着忽然被人赏了一巴掌的表情注视雪之下。

这家伙刚才说什么？

包、包……

某议员的千金，在本店工作的菁英说了那个词？包、包……

雪之下接着开口。丝毫不觉得难为情，光明正大地让声音传遍四周。

「最多的项目是包茎手术，接着是美容整形，然后是丰胸手术、阴茎增大手术等等。相扑小姐藉由某种手段，取得用贵公司的信用卡支付这些款项的顾客清单。以一般员工的权限无法调查这些资料，不过对于职位更高的人应该只是小事一桩吧。没错——例如审查部的部长。」

相扑肩膀一颤。

她垂下涂了睫毛膏的睫毛，不肯抬起视线。

「这些手术的费用偏高，有些似乎还得花上数百万。要一次付清有难度，所以很多人会使用信用卡。相扑小姐催回借款的顾客中，这些人的比例高得异常。例如上个月二十号，你打电话给五十位动了包茎手术的客人催款。这是巧合吗？」

相扑依旧沉默不语。

然而，她的脸红到脸上的浓妆都盖不过。

「全是巧合——不可能吧？通常不会只打电话给动过包茎手术的顾客，还是你有千里眼？光看名字就分辨得出动过包茎手术的男性？」

「闭嘴！」

相扑忍不住大吼。

「东、东一句包茎西一句包茎，吵死了！你没有羞耻心吗？本店的菁英讲这种话都不觉得丢脸吗⁉」

「并不会。」

雪之下挺直背脊。

宛如一朵蔷薇，在这如同地狱的职场绽放。

「我的工作不会得到任何人的感谢。没有人看到银行派人来视察会高兴吧，是不会有人跟自己道谢的工作。」

这时，她瞄了我一眼。

「不过，这就是我的工作。在职场视察，找出问题点，为创造更好的职场做出贡献。相信最后一定会反映在各位的幸福上。谁会觉得丢脸呢？这是我的工作，我的骄傲。」

相扑张开嘴巴，接着又闭上了。

「今后应该会着手调查相扑小姐是从哪弄到那份清单的——我说完了。」

雪之下说完这句话便坐回椅子上。

胜负已定。

尴尬的沉默持续了一段时间，没人出声，现场气氛让人连叹口气都不敢。弓滨担心地凝视大受打击的相扑，其他人则看都不看她一眼。

「啊——那个……呃……」

叶冈清了好几次喉咙。

「这件事先由我处理，麻烦两位等等到课长室来。」

会议到此结束。

唉，雪之下的工作方式只能以惊人一词形容。

没想到她会以这种形式揭发相扑的秘密。

竟然把相扑联系过的顾客资料统统查出来了，这种事还有谁做得到。何况她还从中发现特殊的共通点，根本是超人。

不过——

雪之下究竟有没有注意到。

任何人、任何事，都没有得到救赎。

隔天，相扑胜美没来上班。

直接旷职。

因为生病等原因当天必须请假的时候，会先通知SV。但过了公司规定的上班时间早上九点，相扑还是没有任何消息。她从未迟到、请假过。照理说是一起小小的事件，职场上却弥漫一股「不出所料」的气氛。

当着众人的面被批成那样，哪可能还有办法来上班。

我打电话给相扑，结果她手机没开。想必是现在不想跟公司的任何人说话。本想问问弓滨，但她今天没排班。

相扑大概会顺势辞职吧。

许多员工就是这样消失的。某天突然旷职，持续几天后跟我说他想离职。甚至有当事人得了忧郁症，不方便亲自出面，所以由家人代替他来公司的案例。这里就是这样的职场。

相扑旷职很快就牵连到了其他人。

毕竟我们这边人手不足，光是少一个人就会出问题。而且今天正好是月底的发薪日过后，是付款方面的电话最多的日子。不出所料，电话从早就响个不停。连其他部门的员工都跑来支援，却负担不了这个数量。「放弃」（电话没人接，客人直接挂断）的数量光上午就达到五十八件。是我当上SV后业绩最差的一次。

午休时间，大部分的员工喉咙都干了。我的声音也变得沙哑，最后服务的客人还关心我「感冒啦？」。我在休息室喷喉咙喷雾。没有食欲。午餐可能会只靠喉糖和蜂蜜水解决。

我瘫在沙发上，感觉到有人接近的气息。亮得发光的黑色高跟鞋的鞋尖映入眼帘，留着一头长发的影子在地毯上摇晃。

「这样你满意了吗？」

我低着头说。

「你履行自己的骄傲，结果就是这个惨状。相扑辞职，职场不再有不正当的行为。对你来说这样就行了。因为你可以带着功劳回本店去。但我们还剩下什么？少了相扑这名员工，就这样。而这件事的影响波及到了我们。你回到伟大的巨型银行后，我们还是得在这个地狱里工作。」

人影依然没有说话。

「你的做法拯救不了任何人。什么都不会改变。你做的事仅仅是排除掉一个人。那种做法连小孩子都会。职场失去战力，弓滨失去同期。为什么你只会采取这种手段？啊？讲话啊——雪之下！」

我抬起头。

与雪之下对上目光。

弓滨优梨站在她身后，一脸困惑。

而弓滨旁边——

「咦？」

相扑胜美站在那里。

她的表情像个被骂的小孩，尴尬地移开视线，咕哝道：

「对不起，我上午没来。下午我就会回到工作岗位了……真的很抱歉。」

我目瞪口呆，一句话都说不出来。

为什么？为什么相扑会在这里？

「我带着弓滨小姐去她家接她。」

雪之下用一如往常的冷淡语气说道。

「为了给其他员工做一个好榜样，有必要在那个时候严格谴责她。不过，没做好善后工作就称不上完美。要麻烦今天没班的弓滨小姐，我很抱歉，谢谢你愿意跟我一起去。」

「不会啦，我完全不介意！」

弓滨笑咪咪地挥动右手。

「我也不希望小胜美辞职呀！」

我望向相扑。

「那你不会辞职啰？」

相扑战战兢兢地点头。

「辞职了人家也没地方去……雪之下小姐又说她会帮我跟上头说话。」

雪之下若无其事地说：

「其实这起事件，相扑小姐在某种意义上是受害者。」

「……啊？」

「审查部的惠本部长对她纠缠不清。他拿那份清单当成跟他交往的回报。相扑小姐一时鬼迷心窍，现在为那件事深感后悔。清单也还给部长了，打算洗心革面认真工作。对吧？」

是的——相扑用细不可闻的声音回答。

雪之下接着说：

「我不会说相扑小姐完全没错，但我认为煽动她的惠本部长责任比较大。可以说是一种职权骚扰、性骚扰了。比起一名员工的问题，那是丸菱信贩体制本身的问题。相扑小姐多少也会受到一些惩罚，不过惠本部长应该会受到更严重的处分。」

听她这么说，我明白了。

也就是说——她打算把事情经过设计成这样。

那是雪之下所写的「剧本」。

从之前在休息室的对话来看，惠比寿——更正，惠本部长和相扑肯定都是你情我愿。我不认为是职权骚扰或性骚扰。不过，要设计成这样。相扑的处分停留在谴责程度，利用她的证言将手术刀伸进高层，加以肃清——

那就是雪之下的计划。

真正的目的。

仔细一想很正常。揭发区区一个兼职人员的不<作弊>当<rt/>行为就完事，本店的视察委员不可能满足于这种微不足道的成果。不追究相扑的过失，以更大的猎物为目标。就是这样。

「这叫那个吧，认罪协商之类的……好卑鄙。」

「我对你的看法没兴趣。」

雪之下冷漠地说，面向相扑。

「之后拜托你认真工作啰，相扑小姐。不管是传真文件还是清理冰箱，都请你对自己的工作引以为傲。不要推给其他人。」

「…………是。」

「大声点。我听不见。」

「是！」

相扑自暴自弃地大叫。

看见这样的同期，弓滨笑了出来。

事件平安落幕。

干得漂亮。

视察最后一天。

雪之下在这个地狱度过的最后一天，弓滨建议「我们三个一起办送别会吧！」。雪之下微微皱眉，最后却没有拒绝，跟我们来到站前的居酒屋。

这家店我们常来，因此店家让我们坐包厢。我们拿中杯啤酒干杯，闲聊了一会儿，但七成都是弓滨在说话。从「有个客人好奇怪」这种工作的笑话，到她最近迷上的写小说减肥，话题五花八门。每句话雪之下都会认真点头回应「原来如此」、「的确」、「挺合逻辑的」。

不久后，场面安静下来。

喝了两杯啤酒就醉倒的弓滨，趴在桌上睡着了。

雪之下将外套盖在她肩上。

「你真的很宠弓滨。」

「看到她，会让我想起以前的朋友。」

连坐在居酒屋的时候，雪之下都是挺直背脊。一举一动连醉意都看不见。平静的演歌于店内流淌，不时被醉客的笑声盖过。

「我高中遇过类似的事。」

「啥？」

「这次的事件。高中时期发生过类似的事。」

雪之下看着熟睡的弓滨说。

「当时也是由名侦探雪之下大人解决吗？」

然而，她摇头否认。

「当时的我什么都做不到。无计可施。因为无聊的竞争心而心力憔悴，差点被过多的工作压垮。不过——那个时候，我被『他』拯救了。」

他。

她的语气有点甜蜜。

「就是你的恩人啰？」

雪之下再度摇头。

「我虽然得到了救赎——却觉得『他』的做法是错误的，我不想肯定。所以，我动不动就会重新自问，换成现在的我会怎么做。」

重新自问——雪之下这么说。

不停拿青春时期的那个问题重新自问。无数次地——

「真想见见你说的那个他。」

能让这位雪女说出这种话的人，是怎样的男人？我对他产生兴趣。那人头脑有多么明晰？胸襟有多么宽广？有多么……

雪之下斩钉截铁地否认。

「你全猜错了。」

不要读别人的心读得这么自然好不好。好恐怖。

「跟你有点像。可是，果然不一样。」

雪之下看着我的脸。看着我，却不是在看我。恐怕是在透过我看着「他」。

「既然是那么好的男人，抓住他不就得了。」

我半开玩笑地说，雪之下摇摇头，嘴角勾起自嘲的笑。

「现在回想起来，他会不会是只存在于我的青春时期的虚幻幻影——如同逐渐融化的白雪的存在呢。为了让我保有自我，他是必须的存在。但现在不同。我们已经不是少年少女了。所以我不得不重新自问，以免再度犯下错误——」

雪之下一口气讲到这边，闭上嘴巴。

她像要中断话题似的摇摇头，站起身。从鼓鼓的钱包里拿出钞票及零钱，以一元为单位均摊餐费。不愧是银行员。

「这一个月，承蒙你的关照了，松谷SV。」

她深深一鞠躬，我也低下头。「辛苦了。」遇见她的时候想都没想过的话语，自然而然脱口而出。

「最后告诉你一个不错的情报。」

「什么？」

「喜欢猫的话，去家乐福……噢，现在变成永旺了。去那边的宠物店逛逛吧。会有许多收获。」

我无法控制自己不脸红。初次见面时，我在工作时间看猫咪的影片。没想到她会在这个时候拿出来讲。

「我知道。因为我常去那家店。」

雪之下听了噗哧一笑。很棒的笑容，在最后留下的惊喜。呃，我真的吓到了。这女人也会笑出声啊……

「祝你和弓滨小姐幸福。」

看来那就是道别。

雪之下离开后，我喝光剩下一些的啤酒。

变温的啤酒酸味强烈，非常难喝。不过，我现在尝到的是另一种苦涩。

「在哪里搞错了呢。」

工作满十年，我自认我把该做的事都做好了。

然而，无法对自己的工作感到自豪的我……果然在哪里搞错了方向也说不定。

我有办法再次重新自问吗？

跟她一样。或者跟「他」一样。

人生无论何时都无法挽回。

搞错的答案一定会永远维持原状。

若想推翻那个答案，除了找到新的解答外别无他法。

因此，再重新自问一次吧。

为了知晓正确的答案。

为了在与她重逢时——

可以挺起胸膛告诉她。

我不会再搞错了。

完

23注  东山奈央为由比滨的声优，江口拓也为比企谷的声优。

24注  游戏《快打旋风》中的相扑力士角色。

** 于是，新的敌人现身于他面前。

作者：渡航

俗话说，男人踏出家门就会多出七个敌人。

尤其是边经营公司边当县议员的。身兼二职，忙得焦头烂额，树立两倍的敌人。

同伴当然也很多，不过在阳奉阴违的人赌上尊严的伏魔殿中，不能寄望建立起能坦诚相待的关系。再说，从出社会后到现在，我就不记得自己有在不权衡利害关系和不在心中盘算的情况下，真心诚意跟人相处过。和有无头衔无关，世上一般的大人，应该有很多人都有这种感觉。

因此，我经常对「男人踏出家门就会多出七个敌人」这句话深有同感。

但我没笨到公然讲出这句话。以现在的风潮来看，不难想像光是性别限定男人就会被骂过时，此外，把身边的人都视为敌人这一点，也可能被当成一种偏见。

更重要的是，万一不小心在我家讲出这种话，她一定会用那端正得吓人的美丽面容带着浅笑说「哎呀，意思是家里就没有敌人啰」。

无法立刻否定这个问题，真的让人很不甘心。我完全没有把她们视为敌人，但令人烦恼的是，我也无法肯定她们是同伴。

平常的妻子及两位女儿，必须以圣人君子和贤妻良母来称之。但有时她们会露出远远凌驾于邪恶暴虐之王的恶鬼般的一面。

所以，嗯，相抵过后就用小恶魔来形容她们吧。

……不，这个词或许稍嫌不足。她们的存在规模有点太过庞大，不适合以小恶魔称呼。可怕的时候超级可怕。尤其是妻子，真的很可怕。长女最近也非常可怕。次女在不为人知的地方很可怕。

然而，正因为可怕，展现出可爱一面时才会更有破坏力。轻易粉碎我的理性之墙，跟浅间山庄事件的铁球一样（注25）。

无法分类为敌我方，称之为小恶魔太过可爱，过于可怕的她们。

既然如此，叫她们女神应该是最适合的。

在数不清的神话及英雄传说中，女神未必是同伴。有时也会是恐惧及混沌的象征。

妻子和女儿也如同诸多神话中的女神，兼具慈爱及恐怖这两个极端的性质，随意夺走庶民的心。英气十足的美貌自不用说，偶尔展现出的少女般的可爱模样也颇有女神风范。

男人踏出家门就会多出七个敌人。

回到雪之下家就会看见三位女神。

因此，即使回到家中，我的心情也无法平静。因为今天我八成又会被阴晴不定的她们耍得团团转。

从后座的车窗看出去，夜樱在月光的照耀下，于流逝而去的景色中纷纷飘落。

红灯亮起，司机慢慢停车，由街灯照亮的樱花，树枝前端的嫩叶稍微探出了头。

四月已经快要过一半了。我一直待在事务所和办公室工作，所以没注意到时间的流逝。

迈入新年度的忙碌期也告一段落，我的心情似乎放松了一些。之前一直都在家里、办公室、事务所、出差地点轮流跑，现在终于能喘一口气。

我心不在焉地看着窗外的景色，车子再度静静驶向前方，大概是绿灯亮了。和缓的加速过程及平稳的煞车，都在在反映出专业人士的技术。我年轻时虽然也常开车载人，果然比不上以此维生的专家。跟着岳父开始工作的时候，我迟迟无法习惯由别人当司机，现在则一点都不觉得奇怪。

车子开到家门前，司机下车绕到后座帮我开门，也已经习以为常。

谢谢。辛苦了。晚安。明天见。

我连自己刚才说了什么都不知道，在完全无意识的情况下说出道别的招呼语，走下车。

司机默默行了一礼，目送我离去。我用眼神代替点头，向他致谢，穿过家门。

习惯这种东西真可怕。

司机的存在、异常辽阔的宅邸、县议员及公司的工作、新的姓氏，起初都令我深感困惑。

归根究柢，也是因为这种生活本来与我无缘。我并没有打算从政或经营公司，只是妻子家碰巧是这样的世家。

现在女性政治家虽然变多了，当时的政治家还是男性占绝大多数，妻子家希望我入赘继承家业。

我家也不是需要有人继承家业的显赫家族，对方说这是结婚的条件，我二话不说就答应了，仅此而已。

要去更换驾照、银行帐户等各种文件固然麻烦，其实也只有这些东西要处理，于是我不知不觉成了雪之下家的人。

报上新的姓氏，继承岳父的职位及地盘，还生了两个女儿。

埋头工作的过程中，也习惯了议员和社长的头衔，如今产生了这就是我的日常生活的自觉。

不过，丈夫及父亲的身份，我至今仍然无法习惯。

从结婚时算到现在，应该有二十年以上的经验，但要我挺起胸膛说自己有把该做的事做好，还是有点没自信。两位女儿正值青春期就更不用说了。

阳乃和雪乃。

两位女儿很像妻子，成长得既美丽又聪明，正因如此，身为她们的父亲有时会担心。她们会不会因为才貌双全的关系招人嫉妒、雪之下家会不会成为沉重的负担、会不会因为太可爱的关系有奇怪的虫子靠近她们……

担忧的种子如同沙滩上的细沙，数都数不清，可是我不敢对她们说三道四，如果又被用不耐烦的眼神看待，我会难过，因此我到现在还没办法跟两位女儿聊太深入的话题。

父亲虽然不怎么可靠，母亲却严格又温柔地为她们灌注满满的爱。而她严格的处事态度，矛头第一个指向的是我，而不是女儿。至于有多严格，差不多和现在的股市一样。会不会太严格了？（注26）

继承了雪之下家的家业的那一刻起，比起早早就决定退休享福的岳父，妻子对我的工作批评得更加严厉。托她的福，我变得可以独当一面，代价是当时的我会不敢回家。不对，现在也有点害怕。

我在踏进家门前将神经绷得比工作时还要紧，打开门。

门后，妻子已经站在玄关的台阶上等待我。

「你回来了。」

身穿和服，将头发绑得整整齐齐的妻子，带着平静的笑容缓缓鞠躬。那抹柔和的微笑跟我初识她的时候一模一样，不，比当时更加美丽。

「嗯，我回来了。」

她伸手想帮我拿外套和公事包，我嘴上道着谢，却轻轻摇头拒绝。我原本就是极其平凡的中产家庭出身，对于这种特地来迎接我的行为和大和抚子般的举动没有免疫力。过了二十年以上还是一样。

不过，妻子并未放下伸向我的手，默默微笑。

我输给那「在你把东西交出来之前，我会一直维持这姿势喔」的坚定意志，只将怀里的公事包递给她，她才终于退让。

我其实不是讨厌给她拿公事包，她的贴心之举总是让我很高兴，但这是从新婚时期养成的习惯，没办法。尽管现在我的公事包不会装什么东西，也经常两手空空地出门，年轻时期可是因为背负着期待、责任、干劲的关系，公事包沉甸甸的。随着时间经过，我开始将各种东西托付给她，却因为觉得不能再让她背负多余的负担，至今依然自己拿公事包。

哎，简单地说就是，想帮我拿东西的妻子和想自己拿东西的我，都一样顽固。

我边想边看着妻子静静走在从玄关延伸出去的长廊上，下意识露出淡淡的苦笑。这时，妻子回头看了我一眼。

「今天阳乃也回来了喔。」

「这样啊，真稀奇。」

直到前阵子都还是一个人住的次女回来了，接着轮到长女搬出去住。我也因为工作的关系经常不在家，所以上一次全家人齐聚一堂，是新年的时候。久违的家族团聚的预感，使我加快脚步，妻子的步伐则跟我形成对比，变得有点沉重。

「也不能这么说，那孩子常常回来。」

妻子用纤细修长的手指按住太阳穴，彷佛在为此感到头痛，叹出一口分不清是无奈还是疲惫的气。

「不晓得她到底有没有打算搬出去……」

「……这也挺稀奇的。」

听见这句话，妻子疑惑地歪过头。这孩子气的动作及表情，从我认识她的时候就没变过。

妻子对阳乃抱持期待，因此经常对她严格以待。阳乃虽然有不耐烦的迹象，却甘于接受，或许是出于长女的责任感。

然而，从妻子的语气听来，两人的关系似乎产生了些许变化。

若是之前，妻子八成会反对阳乃出去住。现在仅仅是因为她是自己住在我们家的公寓才同意。但刚刚那句话，可以视为她允许阳乃未来可以搬出去。妻子这种态度果然很罕见。

看来在我不知道的时候，她跟阳乃之间发生了什么事……我边想边解开领带，正好经过客厅。

走进寝室前，我偷看了一下客厅的情况，雪乃和阳乃没在说话，只是坐在沙发上各自消磨时间。

阳乃单手拿着威士忌杯看电视，开心地咯咯大笑。雪乃则斜斜坐着，拿着茶杯看文库本。不过，她偶尔会像想到什么似的拿起手机，露出温和的笑容，雀跃地打起字来。

这也挺稀奇的。还以为雪乃只会在看《岩合光昭的猫步走世界》的时候，才会露出这种表情。是在社群网站上看到了猫咪影片吗？不对，这样的话那略显娇羞地摆动双腿，把脸埋进抱枕的行为太不自然。再说，雪乃在家把手机放在身边就已经称得上稀奇。除此之外，她做出那种诡异的举动，阳乃却没有调侃她，而是一副这样很正常的态度视而不见，同样极度不自然。

愈想愈疑惑。我一步步爬上寝室所在的二楼，想像在这个过程中逐渐成形。

在抵达寝室的同时，不小心想到了答案。

……不会吧——我正准备开口，帮我把外套挂进衣橱的妻子却率先说道：

「对了，她们两个好像有话跟你说……」

我瞬间有股不祥的预感。

刚才雪乃的行为，再加上还要特地跟我说，内容自然有限。

「……我换好衣服就马上过去。」

我拼命控制住快要打颤的声音，努力故作镇定。可是，妻子似乎看穿了我自作聪明的拙劣演技，轻笑出声。

「嗯，那我先去泡茶。」

我看着妻子先行走出寝室，慢慢开始更衣。

理应已经穿习惯的西装，此刻变得异常沉重。

我慢吞吞地花了一堆时间换好居家服，彷佛要一层一层检查楼梯，慢吞吞地下楼。

非得花这么多时间，才有办法做好觉悟。

毕竟至今以来，我从来没跟女儿聊过恋爱话题。那两个孩子外表美丽个性又可爱，想必受到许多异性的关注。然而，聪明的她们知道自己外貌出众，巧妙地应付追求者。

更重要的是，她们有叶山家的隼人这个青梅竹马。隼人从小就深受男女老少的欢迎，周遭的大人也对他评价很高，只要亲眼看过他，一般的男生应该根本不会被放在眼里。我都有点同情被拿来跟他比较的诸位男性了。

不，等一下？也有可能就是要跟我讲隼人的事。

我们家从上一代就跟叶山先生家很熟，我和妻子对隼人的印象也很好。如果女儿要跟谁交往，最佳人选就是他。身为父亲感觉虽然很复杂，假如万一倘若他跟我女儿在一起，我大概也不是不能说我不排斥。嗯。

简单地说，我其实不太想听那方面的事。然而，女儿都说有话要跟我说了，我也不好意思拒绝。正因为我明白自己是个不够格的父亲，才想尽力实现女儿的要求。

情绪愈来愈低落，我的脚步声也变得愈来愈轻。连转开客厅门把的时候，都没发出半点声音。

我怀着忧郁的心情打开客厅的门，红茶的香气扑鼻而来。以晚茶来说虽然有点晚，妻子和两位女儿依然在一同品茶。

「都跟我们一起吃过饭了，接下来果然该轮到爸爸了吧？」

「绝对不要……不如说，他绝对不会愿意。」

阳乃整个人陷进皮革沙发里，把茶点扔进嘴巴，说了耐人寻味的话。疑似谈话对象的雪乃则用指尖拿起茶杯，眉头紧皱喝着红茶。

「刚开始都是这样。你爸爸也是，起初非常不甘愿。不过，要如何巧妙地引诱……」

话讲到一半，妻子发现我像亡灵一样站在门旁，便将后半句话吞回去，往空茶杯里倒红茶。

阳乃和雪乃也转头望向我，大概是因为妻子的动作而注意到了。

「啊，你回来了——」

「你回来了……」

阳乃语气轻快，雪乃则尴尬地跟我打招呼。很久没有全家聚在一起，我下意识吁出一口安心的气。

「……嗯，我回来了。」

我端起妻子为我泡的红茶，同样坐到沙发上。用了很久的皮沙发，变得一坐下去就会慢慢凹陷，将我温柔包覆住。或许家人也是这样。起初僵硬又紧绷，经过长久的时间仔细保养，最后就能完美融合。呵呵，幸好我每晚都把它擦得亮晶晶的……

我暗自窃喜，正在享用茶点的阳乃配红茶把它吞下去，继续刚才的对话。

「……哎，我能理解他不想，可是总不能拖太久吧。干脆直接制造既成事实逼死他会不会比较快？反正那孩子又逃不了。」

突如其来的词汇害我差点从沙发上滑下去。呵呵，看来我每晚擦沙发擦过头了……呵呵，好滑喔。呵呵，拜其所赐，「那孩子」、「既成事实」这些词汇也顺利从我的耳朵滑出去。呵呵，幸好我每晚都把它擦得亮晶晶的……

我打起精神，重新坐好，妻子彷佛算准了这个时机，手指抵在嘴边做出沉思的动作。

「也要视既成事实的种类而定。再多深入瞭解他一下，对你们也比较好。得调查得更详细，确定他未来有一定的发展性再说……」

「这样小心他被其他人抢走喔。对不对？」

阳乃对旁边露出带有调侃意味的笑容，雪乃噘起嘴巴，不悦地回望她。然而，妻子的眼神却比她更加锐利。

「……不是不可能。尤其是那两个孩子。」

「啊——那两个人呀——」

「我觉得不会……」

雪乃慌张地开口打圆场。但雪乃自己好像也对这句话没自信，「唔唔」低头陷入沉思。

看到雪乃这样，妻子跟阳乃都扬起嘴角。像在表示自己看见了令人会心一笑的画面。

我也一样面带微笑，内心却焦虑不安。从刚刚到现在，我就从对话的各个地方感觉到危险的气息。

我小口喝着红茶，看准对话中断的瞬间，缓缓开口。

「你们在说什么？」

「不、不知道……」

雪乃别过头。哎呀，好久没看见这么孩子气的反应。我两个女儿都很可爱，今天却特别可爱。我老婆？我老婆无时无刻都很可爱。

不过，多亏雪乃做出这么可爱的反应，我不祥的预感几乎转为确信。

事已至此，我也不得不做好觉悟。

「……对了，妈妈说你们有话跟我说。」

我维持着父亲的威严，沉稳地询问，静静放下茶杯。客厅迎来瞬间的静寂。

……本来应该要是这样的，神奇的是，茶杯和杯碟却在我手边发出喀嚓声。

啊啊，不要……我不想听……

我不敢直视雪乃的脸，紧盯着泛起波纹的红茶。

这时，有人轻轻清了下嗓子。

我抬起头，开口的是阳乃。

「关于那件事……我会回家住一段时间。」

她轻描淡写地说，我忍不住露出笑容。

「怎么？厌倦独居生活了？」

什么嘛——有话跟我说的原来是阳乃。什么嘛——太好了，爸爸放心了。我的语气中带着笑意，阳乃却像在思考似的轻声沉吟。

「也没有，只是有点事想做。」

我瞄了妻子一眼，她优雅地帮我倒了杯新红茶。看她没有意见，妻子应该也知道阳乃要回来住了。

既然如此，我也没什么话好说。不如说，考虑到阳乃以前过着违反门禁是家常便饭、未经许可就在外过夜的生活，反而该欢迎她回家住。不，不只欢迎。是热烈欢迎光临全家便利商店。

「虽然不知道你想做什么……你爱怎么做就怎么做吧。」

「嗯，我会的。我也想准备留学的事。」

我差点喷出嘴巴里的红茶。不如说已经喷出来了。

「留、留学⁉」

红茶像吐出来的血一样从嘴角流出，滴滴答答滴到矮桌上。雪乃递出卫生纸盒，阳乃抽了两、三张迅速将桌子擦干净，接着把卫生纸揉成一团，扔进垃圾桶，面向我歪过头。

「我没说吗？」

「没有呢……」

我一脸疑惑，顺便望向妻子。妻子却毫不惊讶，优雅地喝着茶。

「我是反对的喔。」

她看都不看我一眼，若无其事地小声说道。流露出一丝交给我判断的言外之意。

从她的语气推测，妻子和阳乃应该已经争论过。在这个基础上交给我下达最终判断……

嗯……以前的话，通常是妻子的意见是绝对的，阳乃虽然不愿接受，还是会以自己的方式找到妥协点乖乖听话。不过现在看来，妻子似乎也在尊重阳乃的意见。

好吧，阳乃也二十岁了。差不多该把她当成一位大人对待，而不是只会唠唠叨叨。八成是因为这样，妻子才没有劈头就反对，而是给我们一个谈话的机会。

可是，不管到了几岁，女儿就是女儿。父亲就是父亲。不会改变。此乃不变的真理。

好——爸爸要卢她一下啰。因为我是希望女儿待在家的类型。

我试着做出些微的抵抗。

「你之前不就到国外念过语言学校了？没必要现在去吧……」

两位女儿曾经去国外留学过。她们是归国子女，所以选了有教国际教养的高中。如果是为了学外文，没必要再去留学吧？待在家里啦……我正准备说下去，阳乃笑了笑，打断我说话。

「是没错，但我这次打算去久一点。我想学习更专业的知识，可以的话想去个一年。」

阳乃随口说道，彷佛这已经是决定事项。这种说法真的很像妻子。这样的话，我的反对不可能被听进去，只能愁眉苦脸地点头。

「……是、是吗？嗯……呃，不过，钱啊……」

若要为她准备能专注在课业上的稳定环境，得花上数百万日圆。实在不是随便就能拿出来的金额。

不，既然是为了女儿，也不是不能想办法，但比起金钱方面，我的心情更加难受。因为时间可是长达一年喔？还是到国外喔？爸爸会担心啦。而且又是阳乃。绝对会出问题。

阳乃是会直接把事情闹大的类型。雪乃则经常在不知不觉间陷入进退两难的状况。也就是说，她们俩都容易出问题。我妻子？我妻子别说出问题了，她更容易造成别人的心灵创伤（注27）。

我支支吾吾，面有难色，阳乃大概是失去耐性了，满不在乎地说：

「把公寓卖掉不就得了？」

「那是爸爸的房子……」

「不过是登记在我名下。」

妻子彷佛在问我「你该不会忘了吧？」迅速补了一刀。对喔，买房时我们一起商量后决定的。我笑着转头望向妻子，表示「我知道，我当然记得」，阳乃趁机顺口补充一句：

「可是，迟早会变成我的房子呀。」

「嗯、嗯，或许吧……」

她讲得一副理所当然的样子，态度过于坦荡，所以我也无法否认。的确有可能给你继承，但我们家的女儿不只有你一个啊……

我闷闷不乐地心想，这时，另一位继承人谨慎地举起手。

「姊姊要回来住的话，我想搬进去……」

雪乃像在观察气氛般，战战兢兢地说，阳乃一脸惊讶。

「咦，是吗？」

我的表情大概也跟她一样。咦，是吗？为什么？留在家里啦。拜托啦。好不容易回来了……

我努力将怨言吞回口中，维持父亲的威严咳了一声。

「雪乃想跟我说的是这件事吗？」

妻子刚才是说「她们两个有话跟你说」。既然如此，雪乃应该也有事想跟我商量。

「嗯、嗯……这件事也包含在内……不过不只这个……」

然而，雪乃的答覆有点含糊不清。

她平常是个有话直说的孩子，因此我对这个反应有点疑惑，紧盯着她，雪乃低下头，似乎难以启齿。

她的嘴巴动来动去，好像想说些什么，却没将其转化成明确的话语。我默默等待她整理好思绪，不久后，雪乃慢慢抬起视线，自言自语似的咕哝道：

「…………不行吗？」

当然可以！有什么问题！只要是雪乃的愿望，爸爸统统愿意为你实现！我故作镇定，将差点放声呐喊出来的话吞回去。

「嗯，目前也没计划要用到……」

我边说边斜眼偷瞄妻子，她也没有反对的意思。代表这也该由我下达判断吧。

「……随便你。」

我在千钧一发之际拿出父亲的威严，大方地点头。雪乃脸上瞬间绽放笑容。

「谢谢。」

能看到这抹笑容，一间公寓根本不算什么。虽然把它租给人的话，可以租到不错的价格，雪乃的笑容远比那种东西有价值。女儿的笑容，无价。

事实上，雪乃鲜少提出要求。有事拜托我和妻子的时候，她会井井有条地说明理由。因此要是她像现在这样无缘无故提出要求，我根本无法抵抗。

尽管方法不同，雪乃跟阳乃都很擅长拜托我。会害我不禁觉得为了可爱的女儿，赴汤蹈火在所不辞。我妻子？我妻子当然也会让我觉得赴汤蹈火在所不辞。她总是在把事情办好后特地告诉我「我买了一间公寓」、「我把名义转到我名下了」、「存定存也赚不了多少钱，所以我拿去买美债啰」，这部分挺可爱的，所以可以说非常可爱。愈可爱就愈可怕。

可是雪乃好不容易愿意回家住，这么快又要搬出去了吗？好寂寞……我垂下肩膀，阳乃在同时歪过头。

「雪乃，你没必要回那边住吧？」

我点头赞同。没必要回去住吧？没必要吧？住家里就行了吧？住家里嘛。爸爸希望你住家里……

「住那边上学比较方便。我本来就是因为这个原因才出去住……」

雪乃叹着气说道，事实却并非如此。

说起来，雪乃是在入学后才决定住进那间公寓的。不是因为一开始就追求便利性才独自搬出去。

上学变方便是结果才对，因和果是相反的。

雪乃之所以一个人住，最大的原因在于入学前的交通事故。值得庆幸的是雪乃没有受伤，不过应该还是对她的精神造成了一些冲击。由于必须跟受害者道歉及善后，我和妻子都有点忙不过来，便建议她自己搬出去住，也能远离那些纷纷扰扰。

当时的雪乃有点神经过敏，想让她和关系不佳的阳乃保持距离也是理由之一。

在我心中，雪乃是个纤细的孩子。

当然不代表阳乃就不纤细。阳乃也很纤细，但性质跟方向不同。阳乃是玻璃艺术品般的纤细，一旦碎裂，碎片就会刺伤碰到她的人。雪乃则带有一碰到就会消失的梦幻感。

我妻子？我妻子当然也很纤细。至于其性质及方向，打个比方，就是碰到她的人即死的危险物。对待她需要相当纤细（可以的话最好要有处理危险物品的证照），不得不说她是位非常纤细的女性。

问题是纤细的她们，有会随便互相伤害的倾向。

现在，阳乃也带着有如柴郡猫的笑容，靠在雪乃身上不停闹她。

「从我们家过去也没多远吧～真的只是因为这样——？」

「没其他理由了吧。不过学校明明离家那么近，却不怎么去上课的人，应该不会明白就是了。」

雪乃将往她身上靠的阳乃推回去，顺便回嘴。

这时，一直置身事外，优雅地喝着红茶的妻子，忽然停止动作。

「阳乃……你没去上课吗？」

她慢慢放下茶杯，以冰冷至极的声音低声说道。脸上依然挂着柔和的笑容，显得更加恐怖。本以为就算是阳乃大概也逃不过这一劫，她却像要打马虎眼似的，大口喝下红茶，很快地解释道：

「无所谓吧，我从来没被当过呀。」

雪乃或许是判断这是个好机会，笑着追击。

「哎呀？那么常来管我们的事，竟然还没被当过……不愧是伟大的姊姊。」

「反、反正又不会被留级！」

阳乃连忙跟我和妻子辩解。不会被留级，反过来说就是只有取得最低学分数吗……

算了，阳乃是聪明的孩子，学业方面我不怎么担心她。但那仅仅是我的意见，妻子似乎不这么认为。她温柔地呼唤阳乃的名字。

「阳乃……你给我算一次大学的课一堂要多少钱。」

妻子头痛地用手指抵着太阳穴，深深叹息。然后对阳乃投以冰冷的目光。

阳乃「唔！」瞬间语塞。雪乃在旁边愉快地挺起胸膛。

面对二对一的不利局面，阳乃噘起嘴巴望向我求助。

但不好意思，我也有同样的经验，因此一句话都说不出来。

很久以前，我被念过一模一样的话。

她跟现在一样，以尖酸刻薄的语气及冰冷的目光，训了大白天就窝在弥漫烟味的麻将馆的我一顿。

回想起当时的画面，我忽然想起二十年前戒掉的香烟的气味。当时香烟的价格只有现在的一半左右，我一天会抽掉一包，不过阳乃出生后就戒掉了。

「……哎，跷课要适可而止。」

我苦笑着说，妻子冷冷瞥了我一眼。可是跟学生时期那令人结冻的眼神比起来温暖了一些，不枉我跟她相处了二十年以上。

本以为我讲的话挺中立的，阳乃却不悦地嘟嘴，鼓起脸颊别过头。坐在旁边的雪乃则得意地拨了下头发，为胜利而骄傲。

好久没看见雪乃赢过阳乃了。

然而，敌人也并非简单人物。

阳乃好像想到什么，张开紧闭的嘴巴，然后扬起嘴角。饱满的双唇勾勒出弧线。

那遗传自母亲的残虐微笑，从客观角度来看还是很美。不过母亲随着年纪增长，变得会打开扇子来掩饰，应该是想努力维持扑克脸，阳乃却依然会故意展现给别人看，藉此威吓对方。

看见那压迫感十足的微笑，雪乃自然也戒备起来。或者有可能是给对方时间戒备的阳乃特有的温柔。

两个女儿都是本性温柔的孩子。我妻子？我妻子当然温柔啰。没有原因，我也完全举不出具体案例，但我不得不说她温柔。没啦，她很温柔喔？真的真的。

「啊，对喔……」

阳乃奸笑着喃喃说道，又往旁边靠过去，手指卷起一绺雪乃的黑色长发，然后用那根手指戳雪乃的脸颊。

「毕竟住家里就不能随便叫那孩子来了。」

「什——」

雪乃的背瞬间抖了一下，直接僵住。我也整个人僵住了。咦，等等。等等等等我撑不住好痛苦等等。

不行喔，不可以，爸爸不准喔。把那家伙的姓名住址跟身份证字号告诉我。顺便帮我准备一下稻草人和大钉子，我会用铁锤直接攻击他。

我很想严厉地这么说，然而因为打击过大，我只能像金鱼一样嘴巴一开一合。

冷静，冷静点。先喝口红茶，再去找铁锤。

我和雪乃几乎在同一时间端起杯子喝红茶。雪乃吐出一大口气后，滔滔不绝地说：

「嗯、嗯，是啊。住家里的话，由比滨同学确实就不能随便来过夜了。不过，那不是原因。事实上，有时候也会由我去她家过夜，我纯粹是因为上学比较方便才想住那间公寓。」

语毕，雪乃喘着气，缓缓将空空如也的茶杯放到杯碟上。妻子马上为她重新倒了一杯茶。

她性格太直率，太不会骗人了……

但故作无知也是父母的职责。

再说，逐一确认女儿的交友关系未免太过度干涉。从雪乃的语气判断，那位由比滨同学似乎是女性朋友，感情好到会去彼此家玩，平常就走得很近。交友圈不怎么广的雪乃交到能让她这么信赖的朋友，反而该高兴。

我设法安抚自己，坐在对面的阳乃却愉快地咯咯笑着。她一把搂过雪乃，脸凑到她耳边，故意用我们也听得见的音量呢喃。

「不是啦，我不是在说比滨妹妹。」

「姊姊不要说话。闭嘴。」

雪乃转过头，用双手按住阳乃的嘴角。阳乃的脸颊被揉成一团，像只做了坏事的狗。

好久没看见她们嬉戏了。

我沉浸在感慨中，一直无奈地旁观的妻子慢慢开口。

「你们都给我住手。」

她一用平静的声音说道，雪乃便不甘不愿放下双手，阳乃也松开搂着雪乃肩膀的手。

等两人终于准备好听她说话，妻子盯着雪乃。

「包含那种事情在内，最好都要谨慎处理。你该做个了断。」

妻子的语气不是过去那温柔宠溺、彷佛在劝导人的语气，而是转为说服人的语气。

「……那样，绝对会被讨厌。」

雪乃轻咬下唇，用比平常随便一些的措辞接着说道。那稚嫩的讲话方式，让我想到小时候的她。

「而且，万一他觉得我很难搞、给人很大的压力……我会很伤脑筋。」

她垂下头，眼中充满困惑、恐惧，或是思慕之情，感觉随时会倾泻而出。

竟敢让我女儿露出这种表情……虽然不知道你小子是谁，我要杀了你……

我用力握紧放在大腿上的双手，手被人用扇子敲了下。我反射性望向旁边，妻子微微摇头。

不行不行，差点露出本性。我反省过去后，发誓要当个沉默寡言的好父亲、好丈夫。

身为她的父亲，该对哀伤地垂着头的女儿说些什么？在我思考之时，我还没开口，阳乃就有动作了。

阳乃说着「对不起喔，一直逗你」，轻拍雪乃的头安抚她。

「不用担心吧。这点小事他也明白。不如说，你本来就给人超大的压力超难搞的。」

雪乃的头被乱揉一通，别过脸。接着害羞地咕哝道：

「姊姊没资格说我……你也很难搞……」

真是。自己去闹人家，事后又特地安慰她，这种爱情表现未免太扭曲了。到底是像谁呢。我苦笑着守望两位爱女，阳乃眯眼瞪着雪乃，伸手戳她脸颊。

「比那孩子好——他可是会在别人从城外包围他的时候，在城内挖地道逃走的类型。就算找他来，他也会用各种手段四处逃避吧？」

「……嗯，大概。」

雪乃叹出一口分不清是放心还是无奈的气。

这时，妻子「啪」一声敲了下扇子，满意地点头。

「那就只能把他逃跑的手段统统封住了。」

满面笑容，甚至可以说是心情愉悦的妻子明明语气轻快，我的背脊却爬上一股寒意。

不只是因为她的说法很可怕，也不只是因为她说着这么可怕的台词，两眼却闪闪发光。

应该是因为我对那个感觉有印象，才会不寒而栗。超过二十年前尝过的猎物被逼入绝境的感觉浮现脑海。

这种极度私人的感觉不可能有办法跟他人共享。事实上，雪乃正纳闷地歪过头，大概是还不明白妻子想表达的意思。

「……是吗？那得先堵住雪乃的后路才行。」

「什么？咦，等一下，姊姊。你想做什么？我不知道你想做什么不过绝对不会是好事所以拜托不要。」

阳乃忽然扔出这句话，导致雪乃更加困惑。她不安地抓住阳乃的手。然而，阳乃说着「乖啦乖啦」制住雪乃，露出灿烂的笑容转头望向我。

「欸，爸。雪乃说想让你见一个人。」

「……咦？」

雪乃张大嘴巴，当场愣住。接着大概是理解阳乃的意思了，脸颊逐渐泛起红潮。

刚才是因为我一直都被排除在外，才有办法在她们提到那方面的话题时，依然能充耳不闻。不过，她都直接点名我了，我实在无法装作没听见。我挺直背脊，凝视雪乃的双眼。

「雪乃……是吗？」

「咦，这，不，没有……」

她一下挥手，一下不停用那只手整理浏海、往脸上搧风、梳理头发，静不下来。

「雪乃。」

可是，妻子以沉稳的声音呼唤她，雪乃便放下手来。低着头掩饰红通通的脸颊，不久后似乎放弃挣扎了，做了个深呼吸，像在窃窃私语般以细微的声音说道：

「呃……那个，我和他都不太习惯那种场面。不擅长应对，也不喜欢，所以，大概得等很久……不是现在……」

她娇羞地别过脸，不时偷偷观察我的脸色，然后又立刻将视线移开，断断续续地说。

我只能默默倾听。如此认真、慎重，留意着绝对不能说错话，诚恳地向我诉说的女儿，又有谁忍心打断她说话呢。

「总有一天，我会，跟爸爸……介绍。」

更重要的是，看见她那么开心、腼腆的微笑，不可能有办法拒绝。

「嗯……噢，是吗……」

我感到一阵鼻酸。呼出来的气息带着感伤，异常沉重。

女儿出生时，我就知道总有一天会来临的这一刻，来得比想像中还快，并且毫无征兆。

如果不讲点话，我八成会一直叹气。那样实在太难堪了，因此我决定先点头，讲些听起来像人话的话。

「这样啊，嗯，我知道了……不过这段时间我也有事要忙，等事情处理完……然后，嗯，到时再说……」

没错。到时我也能慢慢习惯吧。习惯女儿要离开身边。

所以，希望这段时间可以再持续一下……

我才刚这么想，妻子就「喀嚓」合上扇子，擅自做出决定。

「是啊。六月中旬的话就有空了，订在那时候吧。」

「为什么是由你决定……」

我用颤抖着的声音询问，微微泛泪的双眼看见妻子露出微笑。

「不这样的话你会逃走。得先下手为强。」

熠熠生辉、目光笔直的双眼，如同坠入爱河的少女、准备出门约会的少女，从我认识她的时候就没变过，至今依然美丽又惹人怜爱。

都过了二十几年，我还是不觉得自己敌得过那抹离纯洁无垢相去甚远，隐隐透出可爱心机的小恶魔般的诱人笑容。

我目瞪口呆，眼角余光瞥见阳乃在跟雪乃讲悄悄话。

「雪乃，就是要那样。」

「受教了……」

看见雪乃不停点头，我默默同情起尚未见过面的他。

总有一天，他也会跟我一样被逼入绝境，沦落到束手无策的状态吧。甚至连嘴巴都动不了。

现在，雪之下家的三女神把我晾在一旁，想像着不久后的邂逅，随心所欲地聊着天。

「但用正常的方式邀请他，那孩子八成不会来。」

「如果能制造一个契机就好了……」

阳乃边说边将酒倒进威士忌杯，雪乃把手抵在柔软的唇上，陷入沉思。从她眉间的皱纹看来，这个问题似乎挺困扰她的，妻子却轻轻打开扇子，立刻说出答案。

「契机呀……原来如此。若是舞会之类的活动，我和爸爸都有可能自然地跟他扯上关系。」

「嗯。只要拿工作当藉口，那个人大部分的事都会接受。」

雪乃无奈却略显骄傲地提到那个人，妻子把手放在脸颊上，高兴地笑了。

「哎呀，真是好消息。是个理想的劳动力。」

「是说，最好换个时期吧？通常都会因为要考试的关系，没空处理其他事。那家伙可是会拿考试当藉口，说出『为了我们好，最好先保持一段距离』这种噁心台词的类型喔。」

阳乃大笑着说，雪乃脸上却完全没有笑容。

「他真的有可能讲那种话，伤脑筋……」

「不然就是由雪乃说出口。」

阳乃毫不客气爆笑出声，雪乃明显不太高兴。妻子看着两人，露出柔和的笑容。

「说得也是……他的成绩如何？你有听说他要考哪所大学吗？」

「嗯、嗯……大概会跟我考同一间……」

在妻子的逼问下，雪乃不知所措地回答，阳乃拿这当下酒菜，晃着威士忌杯愉悦地扔出一句：

「不同的大学……新的邂逅……偶然的重逢……前途堪忧啊。」

「姊姊你闭嘴。」

我不顾又要吵起架来的两人，默默离开客厅。

再继续听这几个小女生聊天，对我的心脏不好。用不着我多说，我老婆当然也年轻得可以用小女生称之。

离开前，我望向壁钟，离深夜还有一段时间。现在店应该还开着。

很久没有想一个人喝酒了。

跟从寝室下来的时候不同，我踏着变轻一些的步伐走上二楼。赶快换好衣服，去我常去的那间酒吧吧。

我从衣柜里拿出妻子帮我挂好的外套，迅速穿上，蹑手蹑脚走到玄关。回家时我一定会喝到站不稳。

我静静关上门，慎重地走在石头地上，以免踩到铺在地上的小圆石。

穿过大门，樱花在皎洁的月光下纷纷飘落。

男人踏出家门就会多出七个敌人。

企图将爱女从父亲手中夺走的我的仇敌。

即将与我一同和女神们对峙的我的强敌。

——看来今天，我的敌人又多了一个。

完

25注   一九七二年发生于日本浅间山庄的绑架事件。警方使用起重机挂着铁球，击碎山庄的墙壁攻入其中。

26注   日文的「严格（厳しい）」另有严峻、严重之意。

** 后记

后记（石川博品）

男人的内裤果然最棒了。

要我先推荐一件的话，就是GUNZE家的BODY WILD系列立体成型四角裤。缝线少、弹性高、透气性佳，完美无缺。一千日圆这个价格甚至能跟UNIQLO拼。先发名单以它为中心，肯定不会有错。硬要说缺点的话，就是基本上没有花纹，喜欢鲜艳内裤的人不会爱，囊袋部分也只有一块布，所以那话儿容易歪掉，这点令人不安。

UNIQLO的四角裤太紧，我不喜欢（这两、三年的款式我就不知道了）。

最近BODY WILD出的AIRZ系列，合身感根本是异次元等级，穿起来只能用「好色」形容。只不过，可能是因为原料包含嫘萦，感觉会稍闷。只要解决这个问题，应该会是款站在内裤界顶点的好内裤。

瑞典品牌的FRANK DANDY以时尚的花色为卖点。囊袋没什么立体感，而是横向展开，制造出空间感。或许只有我买的内裤会出现这种情况，不过缝在腰间松紧带上的标签太刺了，我干脆直接把它剪掉。整体上来说CP值偏低……的感觉。

听说ANDREW CHRISTIAN的四角裤囊袋部分颇有解放感，因此我买来穿过，与其说解放感，外观更接近Q弹的感觉。我纳闷着这到底是怎么一回事，上官方网站一看，发现有卖「显大」的内裤、只有臀部开了个洞的内裤、只遮得住乳头的坦克背心等等，理解了一切。推荐给想在更衣室独占众人目光的人。

我的兴趣是徒步旅行，因此也有在关注户外系的底衫。最喜欢的是Phenix的四角裤（型号忘了）。网状布料透气性超好。触感也滑滑的。这是我的决胜内裤，在Comike看到的时候希望大家会觉得「喔，今天他也穿着那件内裤耶」。

我想说穿起来会比四角裤好走路，也买了Montbell的美利诺羊毛三角裤。但它边缘有点压迫到鼠蹊部，走起路来怪怪的。很小一件，适合用来当备用内裤。

最近我还买了ICEBREAKER的美利诺羊毛四角裤，明明应该是外国人尺寸，腰围却特别紧。我还在考虑要不要拿它投入实战。

男人的人生就是一段寻找理想内裤的漫长旅程。

是说户冢不知道穿什么样的内裤。

石川博品

后记（相乐总）

从将近九年前看过《果然我的青春恋爱喜剧搞错了。》第一集的时候开始，我就一直在想。

雪之下雪乃这个女人，到底在想什么？

比企谷八幡讲话虽然经常隐瞒真意，这个故事好歹是从他的视角出发。由比滨结衣一开始就会坦率地吐露情绪。一色伊吕波在某种意义上来说很好懂（※众说纷纭）。户冢彩加很可爱。材木座义辉就算了。

可是我觉得，雪之下雪乃那种让人疑惑「她为什么会在这个时候讲这种话？她是抱持着什么样的感情，对八幡那样说的？」的台词，跟其他人比起来稍微多了些。

当然，一切的答案都在作者渡航心中。

不过，难得有机会参加短篇小说集企划，是不是可以允许我写出雪乃的一种可能性？有多少读者的主观，就有多少雪乃。

我基于这样的心情，写了这篇短篇小说。希望大家能怀着「某处说不定有这种思考回路的雪乃」的想法，对此一笑置之。

顺带一提。

原作里有提到雪乃应该懂将棋的片段，不过请各位乖宝宝绝对不要去找。在我的世界中，雪乃不懂将棋。

相乐总

后记（天津向）

大家好。我是天津向。感谢各位阅读《果青短篇小说集》。

竟然有人来问我这种在艺人界角落苟延残喘的人「要不要参加那个果青的短篇小说集？」他还真敢赌。虽然不知道这场赌局是赢是输，在那之后我就没看过那个来找我邀稿的人了。但愿他过得好。

这次要写的是雪乃的短篇小说，从作家阵容来看，我应该是文笔最烂的那个，所以我试着寻找只有我写得出来的题材，结果就是「漫才」这个类别。

本来是因为这样的理由才开始写的，没想到雪乃和八幡平常的对话就跟漫才有相似之处，我写得又顺又愉快，顺利写到了最后。

我写的轻小说《クズと天使の二周目生活》的责编看了后，感想是「比平常的クズと天使の二周目生活有趣太多了！」。真不知道他是在夸我还是在嘲讽我。

希望大家也会觉得有趣。谢谢。

天津向

后双马尾记（水泽梦）

初次见面的读者，初次见面，我是水泽梦。

我平常写的是这本书出版的时候，或许已经完结的双马尾的故事。写双马尾故事的时候我都是写后双马尾记，所以这次也是后双马尾记。

果青的作者渡航老师是个亲切又照顾后辈的人，他对我也很好，因此这次有人来找我写短篇小说集时，我也给予了「我很乐意！」的答覆。

例如，数年前，我在书店跟渡老师一起办过签书会。

当时渡老师在签名下面写了留言，对我说「作家（和插画家不同）没办法加上画，所以签名时多写几句留言，读者会很高兴」，给了我这样的建议。

以此为契机，我也开始尽量在自己的签名下面加上搞笑的留言。

我都分享了这么温馨的故事，希望各位果青的读者能对于我在本书里写了有点愚蠢的故事一事睁一只眼闭一只眼。

水泽梦

后记（裕时悠示）

写完这篇短篇后，我浏览器的广告充满「包茎」。

死都不原谅渡航。

长达约九年的战斗，真的辛苦了。

裕时悠示

后记（渡航）

各位好，我是渡航。

前阵子，我写完《果然我的青春恋爱喜剧搞错了。》第十四集，本以为这样暂时就不会有写后记的机会了，结果过没多久又要再写一篇。

结束了——！我自由了——！再也没有人可以阻止我了！当时我还这么神气，彷佛是一场梦。

我至今依然在这个地方，写着那一天的后续。没错，在神保町的小学馆（注28）…………之前那段时间是假释吧？

不过，假释期间我也认真做了许多与《果青》有关的工作，我自己有「不写不行……」的强烈使命感。在我心中，完全没有这个故事已经结束的实感，未来的故事和自动浮现脑海的小篇章，一直在心里打转。

仔细一想，费时约九年，快要十年了。我和他们跟她们相处了那么久，不可能因为写完最后一集就丢下一句「好，再见啦」，不时会忽然产生「那家伙现在不知道过得如何……」跟想到国中同学一样的感觉。

我想，未来我大概也会一有机会就思考他们和她们的将来吧。然后每次都会拿起笔，撰写那一天的后续。

〈于是，新的敌人现身于他面前。〉就是这样诞生的。

由于这次要出的是短篇小说集，我想说「嗯，这种故事也不错……」便写了这篇出来，写本篇不太常写到的角色和剧情很愉快，希望还有机会写这样的短篇。

啊，没错。是啊。这是短篇小说集耶。制作人！是短篇小说集喔！短篇小说集！（注29）

是邀请许多作家、插画家创作许多果青作品的企划，之前我不小心把我的幻想「我心目中的最强果青短篇小说集」讲出来，结果不小心成真了。

由喜欢的人和崇拜的人帮自己的作品写短篇小说集，既喜悦又害羞，我的冷汗都流成瀑布了甚至直接失禁。尿出来惹。

这个《果然我的青春恋爱喜剧搞错了。》短篇小说集，是预计总共会出四集的超荒谬企划。我喜欢的人还会继续登场喔！

除了雪乃side外，结衣side、allstars、onparade也请各位多多关照。

以下是谢辞。

石川博品老师、相乐总老师、天津向老师、水泽梦老师、裕时悠示老师。

感谢各位这么有趣这么好看的作品。我以一名果青读者，而非作者的身份看得非常开心。大家都知道这部作品和这个作者难搞得要命，我明白会给各位添许多麻烦，但我很幸福，所以万事OK。

うかみ老师、春日步老师、切符老师、ももこ老师。

我怀着新鲜的心情欣赏角色们的美图。太棒了吧？一张张看下来，我的心灵都被幸福填满了。根本是合法的某种药物。真的十分感谢。

ponkan⑧神。

感谢神。封面太赞了，神。虽然快要十年了，希望二十年三十年生病的时候健康的时候，也能继续跟您合作。请多指教啰！我的伙伴！谢谢！

责编星野大人。

谢谢您为我实现我随口说出的企划。谢谢您愿意奉陪我这种会提出「出个四本吧！」这个荒谬意见的任性作家，真的是感谢感激暴风雨（注30）。不过短篇小说集和其他各种企划都还会继续喔！之后也陪渡航到地狱旅行一趟吧。放心，下次一定能轻松搞定啦！呵哈哈！

GAGAGA编辑部的各位，以及提供协助的各家出版社。

基于「因为！我喜欢！」这种无厘头的理由去向各个作家、插画家邀稿，真的非常感谢您们协助编纂本书。在此向于百忙之中抽空参与本企划的各位致上深深的谢意。

以及各位读者。

《果然我的青春恋爱喜剧搞错了。》完结后，仍然推动了各种企划，无疑是多亏有大家的支持。今后，果青的世界还会再往前走一段时间，慢慢扩展开来，如果各位愿意陪我走完这段路，会是我无上的喜悦。正因为有大家的声援，这个故事才能继续下去，没有结束。因为有你，才有果青的存在！

写到这边，篇幅也用完了。我要假装放下笔杆，去写下一篇原稿。

接下来让我们在《果然我的青春恋爱喜剧搞错了。onparade》见面吧！

二月某日 激动MAX睡意MAX地喝着MAX咖啡

渡航

28注   小学馆位于东京都的神保町。

29注   改编自偶像大师中的角色天海春香的台词「制作人，是巨蛋喔！巨蛋！」。