#+title: 我的青春恋爱物语果然有问题 短篇集2 ONPARADE
#+setupfile: ./setup.setup
* 短篇集2 ONPARADE

** 千叶的高位压迫果然搞错了。

台版 转自 深夜读书会

发布：深夜读书会

论坛：ritdon.com

作者：白鸟士郎／插画：しらび

「八幡——！」

天使在闸门后面对我挥手。

……咦？奇怪。

我今天应该是跟同班的男同学有约啊……怎么有天使在？

我停下脚步揉眼。

……咦？奇怪。（以下无限轮回）

「八幡——！我在这里——！喂——！」

天使跳着对站在原地揉眼睛的我挥手。啊啊～我的心也在扑通扑通跳～

不对。

他不是天使。

而是我的同学——户冢彩加。

「哇！好可爱的美少女……」

「是那个眼神很恐怖的男人的女朋友吗？好扯……」

穿过闸门的人们对挥着手跳来跳去的户冢投以惊愕及羡慕的眼神，然后看见我的脸，将疑惑及怨叹的声音砸在我身上。

户冢彩加从肉体上来说是男性。

当然也可能是我误会。证据就是来车站的人八成没半个认为户冢是男性，每个人应该都深信他是百年难得一见的美少女。

既然如此，户冢已经可以归类成女生了吧？

「八幡——！后面！后面塞车了啦！为什么要站在闸门前发呆⁉快过来！」

好，我要去了！收下吧‼

为了与天使见面两秒就合体——不对，为了与天使会合，我调整好心情，朝他踏出一步。差点要去了……

我穿过闸门，微微对户冢低头。

「抱歉。我太晚到了。」

「没有啦。你没迟到。是我太期待跟你一起出门，早了一班电车过来！」

讲完这句话，户冢略显害羞地「嘿嘿嘿」笑着低下头。

「⁉」

好险……

差点激动得抱住他跟他告白……

我望向旁边，以免变红的脸被他看见，开启另一个话题。

「嗯，那个……就是，苏我站原来变成这样啦？」

「啊哈哈。很可爱呢。」

可爱……与否，每个人看法不同吧。

还没穿过闸门，我就看到车站里全是足球。

车站的墙壁上装饰着写满留言的队旗，到处都是足球队的代表色黄色、绿色、红色。

要说的话，JR车站里面比较多枯燥乏味的灰色，苏我站却明显不同。

连站内面包店的阿姨都穿着黄色制服结帐，这副模样再怎么说都称不上「可爱」。实在有种……被迫穿上的感觉。

而且我刚才从月台瞄到，站前的圆环甚至立了一尊吉祥物的雕像。两只狗踢足球踢得不亦乐乎的雕像。

户冢由下往上窥探我五味杂陈的表情，问：

「八幡……难道你第一次在苏我站下车？」

喂……快要可以从你的上衣领口看见胸部了啦！我偷瞥了户冢的胸口一眼，看着旁边有点冷淡地回答：

「因为苏我是连转车都几乎不会用到的中间站。而且我不太会在假日搭电车。」

「我参加社团活动的时候会坐电车。假日偶尔也会在车站和电车上看见穿制服的人。」

「嗯，因为离学校很近嘛。」

没错。

离总武高中最近的稻毛海岸站，跟苏我站只有两站的距离。

苏我又只要五分钟就能到千叶站，离东京站约四十分钟，跟大都市圈也靠得很近，是内房线、外房线、京叶线、京叶临海铁路临海本线这四条路线交会的总站。

基于它的地理位置，苏我站周边的这块区域，听说预计发展成继千叶都心、幕张新都心之后的第三都心。第三新千叶都心。

……但这里目前放眼望去全是工厂，感觉很冷清。

我和户冢之所以来到平常不太会来，跟附近的亲戚家一样的苏我站——

「谢谢你们今天愿意过来。」

看见那位面带清爽笑容静静出现的人物，我差点下意识「咦！」了一声。

叶山隼人。

足球社社长，是把我和户冢叫到苏我站的人。

他平常是无论制服便服都能穿得很好看的现充……今天却穿着几乎整件都是黄色的足球球衣，脖子上也围着类似黄色围巾的东西。

以硬要说的话，感觉比较喜欢穿得朴素点的叶山而言，这身打扮非常高调。

「哇！叶山同学，你把球迷衣和毛巾都装备上去了，全副武装耶！很有球迷的感觉。不愧是足球社！」

「球迷……衣？」

「给球迷穿的球衣。」

叶山爽快地回答，又跟我说了一次「比企鹅同学，谢谢你今天愿意过来」。

「嗯，我自己也很惊讶。」

我老实回答。

竟然要在体育场看足球比赛，超现充的行为。

那种活动都是派对咖凑在一起唱那首「ole」之歌（注1）对吧？一直我来我去，自我主张太强烈了吧？是「是我是我诈欺（注2）吗？到底多喜欢自己？

「因为JR东日本也是千叶队的赞助商。」

「嗯？」

我跟不上忽然转换的话题，回问道。

「你们刚刚在讨论苏我站对吧？」

「你听见了？」

「没有。不过我从气氛感觉得出来。」

事情的起因是我和户冢在讨论假日要不要出去玩时，叶山不知为何跑来插嘴。

我有免费的入场券，一起去看足球吧，离学校也很近，一点都不可怕啦……我被他的花言巧语说服，所以这奇妙的三人组才会共同度过假日。

好吧，至少比被材木座或川什么的同学缠上来得好……但可以的话，我想和户冢两个人一起去遥远的地方。没有任何人……只有我们两个的场所……

因此，我现在心情非常复杂。

不过假如我一个人回去，就会留户冢跟叶山两人独处……这样叶山八成会喜欢上户冢。世上不可能存在跟户冢独处时，还有办法抵挡他魅力的人类。

户冢不顾烦恼不已的我，带着天真无邪的表情询问叶山：

「对了，叶山同学，你为什么叫我们带保鲜盒来看足球赛？」

「到那边就知道了。」

叶山露出神秘的笑容，走在我们半步前方带路，往体育场迈进。

我真该在这个时候就发现的。

今天……不对，从邀请我们到体育场的那一瞬间开始，叶山就有点不对劲。

车站到体育场似乎走直线就能到，可是有一段距离，所以我们三个边走边聊天。

然而，我们平常根本不会一起去某个地方，也没有共通话题。

因此气氛有些僵硬。跟在学校的体育课上踢足球时一样僵硬。

「……话说回来，你们两个平常会看足球赛吗？」

叶山这问题感觉像硬挤出来的话题，户冢和我分别回答。

「我只会看国家代表队的比赛。世界杯每次都会让人忍不住熬夜看耶！」

「我也只会看千叶银杯。」

千叶银杯如名字所示，由千叶银行集团担任冠名赞助商，是与世界杯和欧洲冠军联赛齐名的世界三大杯之一。

千叶和柏市的足球队几乎每年都会举办，分出谁才是千叶县最强的最强决定战。实际上可以说是世界最强决定战，所以把它跟世界杯相提并论也很合理！

……我讲了网路上常有人开的玩笑，叶山听见我的回答却两眼发光，反应异常激动。

「你有看千叶银杯吗⁉那你对千叶的选手也很瞭解啰？可以问你喜欢谁吗？」

「利特巴尔斯基（注3）吧。」

「好厉害！比企鹅这么久以前就在支持千叶队啊？」

「呃，利特巴尔斯基是我出生前的选手耶。我只是随便讲一个听过的球员……你要发现啊……」

今天的叶山有点太过主动，不如说会直接贴过来，我的讽刺和耍蠢毫不管用，很难掌握距离感。

顺带一提，利特巴尔斯基是二十年前以上隶属于千叶队的德国选手，网路上说他在日本退休后跑去当教练。第二位太太是日本人，记得是荻原健一的第一任太太。本人日文也讲得很好。这部分是每位千叶县民都知道的基本知识。

讲到这边，叶山终于发现我对看足球赛没什么兴趣。

「难道……你讨厌足球？」

「与其说讨厌足球，不如说我讨厌会在涩谷大吵大闹的那种人。我能理解选手赢了比赛会高兴，但其他人也跟着为这件事发疯的心态就无法理解了，觉得给别人添麻烦也能得到原谅的想法则更是搞不懂。」

以前有位担任国会议员，自称自己长得像深田恭子的自恋女，在跟国内屈指可数的大型足球俱乐部的粉丝起冲突时，呛过这句话。

『别把自己的人生强加在别人身上。』

真理经常出自于垃圾口中。

因为假如你对垃圾说的话有那么一点赞同，由其他人口中说出来就更难反驳了。

因此，我也试着用非常尖酸刻薄的说法表达意见，然而——

「是啊。说得没错。」

想不到叶山竟然同意我的看法。

「虽然每个人喜欢足球的方式不同，我也不喜欢在体育场外面群聚，给其他人添麻烦的人，不想被当成跟他们一样的球迷。」

「是吗？」

「再说，我觉得看都不看国内球队的比赛，只支持代表队跟国外球队很奇怪。正因为有国内联盟这个让选手能放心成长的环境，才有到国外挑战的机会。你不这么觉得吗？今天是个难得的好机会，希望你亲眼看看国内联盟的水准有多高。有很多优秀的选手喔。」

「喔、喔……原来如此。嗯。我懂了。」

今天的叶山真的很难掌握距离感……

我将视线从叶山身上移开，环视周遭，有一堆衣服带有黄色的人，正在朝同样的方向前进。

宛如朝圣地耶路撒冷迈进的巡礼者。好啦，我没看过巡礼者，不过应该差不多就是这种感觉。

我愣愣地看着那群人，像在自言自语似的说：

「黄色是千叶队的粉丝……在足球圈是叫球迷<Supporter>对吧？」

「嗯。跟我们同方向的人大部分都是。不然在这一带都是开车的。」

足球圈叫Supporter，篮球圈叫Booster。

根据叶山事先跟我说明的知识，看足球赛时，主要是靠拍手或配合太鼓的节奏唱叫做「应援歌」、「口号」的类似改编歌的歌曲，帮喜欢的球队加油。

在电视上看代表战的时候，会听见背景隐约有「喔喔～日本～日本～日本～日本～」像念经的声音，那就是应援歌。

户冢兴奋地说：

「我在YouTube上找了应援歌听，学了几句来喔！」

「YouTube上还有那种东西啊？」

我问，叶山再度激动地说明。

「是球迷团体录起来传到网路上的。因为支持球队，终究只是球迷自发性的行为。户冢学了哪首歌？」

「嗯——『共同——迈进吧——』那首。」

「〈奇异恩典〉啊。那是选手入场时唱的。」

我完全听不懂他们在讲什么，但能听见户冢唱个几句，真是太赞了。

俨然是天使的歌声。

希望他在比赛开始前独唱国歌的等级。

可是，要我唱歌就另当别论。我询问叶山：

「一定要唱吗？」

「视观赛地点而定。有大声唱歌会比较好的区域，也有太大声会被嫌弃的区域。因为来看比赛的人各式各样。」

呣。本以为会去体育场的人大多都喜欢热闹点，看来并非如此。

「球门后方是最热情的区域，但那边的人基本上都是全程站着，不方便观赛，所以不适合第一次去的人。」

「不方便？为什么？」

「足球这种运动，从横向看的话两队的球门都看得见，从纵向看却只能看见其中一队的球门。」

噢。原来如此。

「不过踢球的时候都是从纵向看，对我来说从这个角度看比赛也会有收获。」

平常只会用电视看球赛的我，根本没想过从哪个角度看足球赛比较好。

户冢看着走向体育场的人，咕哝道：

「大部分的人都有带应援物耶。我们在体育场会不会显得格格不入……？」

「不介意的话，要不要我借你们？」

「咦⁉可以吗？」

户冢发出高亢的声音，眼睛闪闪发光，有如一只乐得竖起耳朵的小狗。

可是。

在高兴之前，我不知为何先起了戒心。

或许是因为叶山那句「要不要我借你们」……听起来像在等待猎物落网的蚁狮。虽然我觉得是错觉。

开心得跟小狗一样的户冢，也因为其他原因面露忧郁。

「啊……可是，这样你不就没应援物可以用了？」

「对啊。还是别跟你借——」

我话还没说完，叶山就从包包里抓出黄色球衣。

「放心。球衣我买了室内用跟室外用，守门员穿的版本我也买了室内和室外用，所以每年都至少会买四件。这很正常吧？」

「喔、喔……是喔。」

一件就够了吧？

这句话差点脱口而出，然而其他人要在兴趣上砸多少钱，外人不该批评。

如果小町在家骂我「哥哥，你看的轻小说封面都长一样，买同一本书有什么乐趣吗？咦？这些全部是不同作品？」我也会不爽。

「有点太大件……怎么样？适合吗？」

叶山的球衣对户冢来说尺寸太大，因此他只是直接套在上衣外面。

户冢「锵锵！」原地转了圈。

「不错啊？对吧，比企鹅。」

「嗯……太棒了！」

女生穿过大的棒球球衣等衣服时，有时会显得异常可爱，户冢现在就是这个状态。

我那即将萌芽的对叶山的戒心，被球衣户冢绽放的圣光烧尽。

户冢很可爱，所以今天是户冢纪念日。

「哇！比赛还要两个小时才开始，已经这么多人在排队啦⁉」

我们抵达体育场，眼前是难以置信的队伍。

真的假的……看这人数，差不多有一万人吧？

叶山对惊讶的我们说：

「离比赛开始还有两小时，但一小时前球员就会开始在足球场上练习。所以实际上已经是一小时前。」

「「？？？」」

他轻描淡写地说出好像能理解又好像不能理解的道理，我和户冢愣了下，因为「既然叶山这么说，那就是这样吧」的信赖感更加强烈，就没再继续追问。

「虽然要视体育场而定，想认真看球赛的时候在换日的瞬间就会有人来排队啰。」

「喂叶山……要排进这个队伍喔……？」

「不需要。想在最前排观赛的话要排，不过今天我想让你们体会一下体育场本身的气氛。」

太好了……如果答案是要，我真的打算直接掉头回家。

我用叶山借我的毛巾（我只借了毛巾。球衣我坚持不穿）擦拭冷汗，环顾会场，一股刺激食欲的香味乘风而来。

「两位，进体育场前先填饱肚子吧。」

叶山事先跟我们说过「午餐在体育场吃吧」，所以我没带任何食物来，我却对他的提议提不起兴致。

「可是这种地方通常大多是价格订很高，味道却不怎么样的摊……唔…………⁉」

身为CP值最高的萨利亚的发源地——千叶的居民，对食物的CP值抱持绝对不容许妥协的严格心态。

但有个东西能让我顽固的心瞬间融化。

那就是——

「胜浦担担面！那不是胜浦担担面吗！」

竟然连闻名全国的B级美食胜浦担担面都来摆摊，不容小觑啊。

虽说最近千叶市内也吃得到胜浦担担面了，那可是鲜少有机会给胜浦市民以外的人吃到的梦幻拉面……逐渐后悔到这边来的我也迅速兴奋起来。胜浦担担面的潜力就是这么厉害！平冢老师看见可能会喷鼻血。

叶山连每家摊贩都瞭若指掌。

「那家店的串烧是用从鸭川直接送来的海鲜做的，那家店每次都会卖拿千叶特产当料的炒面。全是在美食节得过奖的实力派。」

「我还以为跟祭典摊贩一样……结果这么正式？」

「因为最近体美食的竞争也很激烈。」

补充说明一下，体美食是「体育场美食」的简称。

我走近摊贩观察。

「哇！这个好可爱。」

户冢发现做成似笑非笑的狗脸形状的大判烧，忍不住尖叫。

可爱……吗……？

「杰菲烧的外型仿照千叶队的吉祥物，是很受欢迎的商品，有红豆、巧克力、卡士达三种口味。得花一段时间才能烤好，最好趁现在还没有太多人在排队的时候买。」

叶山冗长又琐碎的说明，也因为大判烧的狗脸笑容完美中和了它，因此我不怎么介意。

「嗯～口味有三种啊。好烦恼……」

户冢皱眉沉吟，转头问我：

「八幡喜欢哪种口味？巧克力？卡士达？」

「你…………红豆吧。」

我将「我喜欢的是你！」这句话吞回去，不小心点了没多喜欢的红豆口味。带回家给小町好了……

「叶山，你推荐的是哪摊？」

「这个。」

叶山从包包里拿出巨大保鲜盒，敲了下秀给我看。

呃，我不懂你想表达的意思耶？

他踏着轻快的步伐走向铁板上堆着一座小香肠山的摊贩，请店家装满整个保鲜盒，走回这边。

「那摊『喜作』如果自备保鲜盒过去，店家会帮你装到满。很棒吧？」

呃，这也装太满了吧……跟棒球社便当里的白饭一样塞得密密麻麻……小香肠看起来像饭粒……

买到笑脸狗的大判烧，乐得眯起眼睛的户冢，立刻瞪大眼睛。

「哇。所以你才叫我们带保鲜盒来。」

「户冢有记得带保鲜盒对吧？要不要去买一下？」

「有呀。可是我吃不了那么多……」

「那比企鹅呢？」

「呃……那个，我忘记带了。」

「不是真正的保鲜盒也没关系。你看，也有人用装三明治的盒子代替。」

「真熟练……」

经验丰富的球迷去对街的购物中心购买附盒子的轻食，用空盒装了快要满出来的小香肠，淋上大量的番茄酱。

「可是机会难得，我要选择这红通通的胜浦担担面！」

我用这句话摆脱缠人的叶山，走到担担面的摊贩前排队。

胜浦担担面也很受足球粉丝的欢迎，必须按照顺序等待。

然而，光是闻着胜浦担担面特有的那种麻油系担担面无法提供的辣油香……温暖在港都胜浦工作的渔夫渔女身体的深红色汤头的芳香，排队时间一转眼就过去了。

「这就是胜浦担担面吗……跟宝石一样！」

充满大量辣椒及辣油的汤头，在户外看起来如同红宝石般闪闪发光。

先从汤开始品尝吧……

我慢慢吸吮装在廉价塑胶容器中的宝石。

「⁉比想像中还辣……不过，好吃‼」

完全不像麻油系那么温润。毫不妥协的辣度刺痛舌头。强烈的美味伴随那股刺激炸裂！

我瞬间成为胜浦担担面的俘虏，专心吃着面。很辣，所以没办法一口气吃下去！可是好好吃！

在我沉迷于担担面之时，附近忽然变吵了。

「…………嗯？」

有人在用扩音器演讲。

我望向声音来源，一名长发大叔……不如说是已经迈入初老的男子，握紧扩音器站在梯凳上，针对今天的比赛发表「绝对不能输」、「拼命声援吧」之类的演讲。

旁边还有个用安全帽和围巾遮住脸，打扮得像革命家的人。

基本上跟祭典一样的会场中，只有那块区域气氛特别凝重。那是所谓的球迷骚乱吗？

「他们是核心球迷。」

叶山以惊人的速度吃完多到让人觉得无穷无尽的小香肠，不知何时走到吃担担面的我旁边。

「是在球门后面负责管理应援行为的人。他们不会使用暴力……但比企鹅感觉就不太喜欢那种调调吧？」

「老实说，没错。让我有种『有这么多吵死人的人啊……』的感觉。而且应援行为不是该被人逼着做的吧？」

「你讲话真不留情。」

叶山苦笑着说。

「可是如果你要这样说，侍奉社的活动不也跟那差不多吗？」

「不一样。」

「哪里不一样？」

「我们是被平冢老师逼的，你们是自愿这么做的吧？」

「呵呵。你这人……讲话真的很不留情。」

叶山脸上挂着笑容，眼中却不带任何笑意，跟刚才判若两人。

户冢敏锐地察觉到这一点，指向稍远处的地方问：

「叶、叶山同学，我问你喔！聚在那边的人在做什么⁉」

「那是……在等游览车。」

「等游览车？」

「他们要迎接球员坐的游览车。比赛开始前就为球员打气，提升他们的斗志。」

竟然做到这个地步。

偶像圈中好像也有「出待」、「入待」（注4）这种名词，我倒没听过在游览车外面声援的。

「哦——有用吗？」

我怀着些许恶意回问，出人意料的是，叶山详细地为我说明。

「踏进足球场后，选手的注意力会全放在球上，听不见加油声。不过坐游览车的时候还有空看外面，所以有人觉得在车外声援的效果反而比较好。」

「……想得还真多。」

「因为球迷也只能动脑子想了。这是他们的辛酸之处。」

这句话让我觉得他怪怪的。

叶山本人也有在踢足球，应该是满厉害的球员。就算没到叶山这个程度，踢过足球的人照理说都会想拿自身经验当例子才对。例如户部。

不过，叶山始终站在旁观者的角度诉说。异常聒噪，却是从旁观者的视角出发。绝不动摇。

简直像……我在学校的立场。

不久后，游览车似乎来了，聚集在一起的球迷集团的呐喊声，如远雷般响彻四方。

「他们在喊什么？」

叶山看着远方，简短回答户冢的问题。

「WIN BY ALL。」

我们穿过入场闸口，踏进体育场，里面是另一个世界。

「喔喔……！」

我下意识惊呼出声。

鲜艳的绿色球场，以及看起来比想像中还近的蓝海。

再加上体育场是钵形结构，让人觉得自己所在的位置出乎意料地高。

我感受着强风扑面而来，忍不住咕哝道：

「……怎么这么陡？」

「嗯、嗯……有、有点可怕……耶？」

户冢在我耳边轻声说道，然后用小小的手指抓住我的袖子，露出惹人怜爱的笑容。

「不过有八幡陪在我身边，所以我不怕！」

……足球太赞了吧？要不要买季票呢。

叶山帮我们占了三人位，问：

「怎么样？第一次到体育场的感想是？」

「（户冢）太棒了。（户冢）有够赞。」

「听你这么说，不枉费我邀请你来。」

叶山看起来很高兴。太好啰！大家都很幸福！

我坐到位子上环顾体育场，立刻发现异状。

「喂，叶山。正面看台怎么都没人……」

「喔。千叶把正面的座位价格设定得有点高，所以大多都会在后方看台区观赛。今天人还算少的呢。」

「这样叫少……？」

我们所在的后方几乎被挤满了，而且观众仍在陆续进场。人会变得更多，让我跟户冢紧贴在一起吗……赞。

「喔。那人是不是户部？」

我在球场角落发现一群人穿着熟悉的制服，在里面看见一个认识的人。对方似乎也发现我们了。

户部翔。跟叶山一样是足球社，经常和他混在一起的成员之一。

「隼人——！喂——！耶嘿——！」

给人一种轻浮感的户部边跳边耶嘿叫，朝这边挥手，叶山只是苦笑着轻轻举手回应他。

不只户部，其他足球社社员也对叶山挥手或低头致意。

「那是我们学校的足球社对吧？他们为什么在球场里面？」

户冢问道，叶山回答：

「县内的足球社社员会轮流在比赛时帮忙。捡球或搬担架之类的。」

「哦——！好好喔，可以参与职业选手的比赛！如果网球社也有就好了。」

不愧是对网球着迷到特地去网球教室打球的户冢，他好像非常羡慕能跟职业选手交流的机会。

我提出内心的疑惑：

「你不去找他们吗？」

「我国中就经历过了。再说，这种事最好趁低年级的时候体验。因为跟职业选手站在同样的球场上，大多能提升参加社团活动的干劲。」

叶山的回答堪称标准答案。

简直像事先想好的，没有一丝让人反驳的漏洞。虽然叶山平常就是完美的人，不知为何，今天他这么无隙可乘，反而让我很在意。

选手在球场内练习完后，开始举办赛前的各种仪式。

县内自治团体的大人物上台致词。捐赠特产。

在赞助商企业的年轻社员主导的应援练习上，整个观众席的人都在甩动毛巾，将体育场大部分的区域染成黄色。挺壮观的。例如兴奋地挥舞毛巾的户冢。

每项表演都很豪华，气氛热闹得令人惊讶。

害我下意识觉得不对劲。

最后，两只狗型吉祥物（布偶装）牵着年纪差不多是小学生的孩童，朗读公平竞赛精神。那孩子精神百倍地这么说：

『我出生后千叶队从来没晋级过，希望今年一定要晋级！』

这个瞬间，热闹的体育场被沉默支配。小孩子率直的话语，总是会深深刺痛大人的心……

而且看到年纪跟千叶待在乙组（注5）的时间一样长的小孩，球迷在开赛前好像就受到了心灵创伤。千叶队球门后方的那群一直加油得很大声的球迷，稍微变安分了……不如说变消沉了。

「叶山？」

「嗯？」

「为什么千叶回不到甲组？」

我开门见山地问。

没错。千叶在国内联赛不是甲组，而是乙组的球队。

我察觉到的异状就是这个。

明明是乙组，为何这么亢奋？

「如果是我自以为是的想像，先跟你道歉，千叶应该更强吧？今天来体育场的观众也很多，都有JR当赞助商了，资金来源应该也很充足。连更乡下的地方，感觉没什么钱的球队都在甲组不是吗？为什么——」

「是啊。以前千叶的确也很强，在国内联赛甚至是最强的。虽然是多亏来自东欧的某位名将的力量。」

「叶山同学，你说的是那个还当过日本代表教练的——」

「……他的名字我就不说了。讲出来会产生留恋。千叶必须怀着骄傲迈向前方，而不是紧巴着过去的荣光不放……」

叶山说的是谁，连不懂足球的我和户冢都大概想得到。

因为我小时候……是足球风气在千叶非常盛行的时期。

正因如此，叶山这种「校内运动神经最好的人」和户部那种「校内最轻浮的人」，才会都加入足球社吧。

社团也有阶级制度。

其中足球位在最顶端。做为上级国民叶山加入的社团，可谓完美无缺……虽然叶山本人应该完全没考虑这些，纯粹是喜欢踢足球吧。

叶山隼人深爱着足球。

因此，与足球有关的所有事物，对他而言应该都是珍贵、特别的。

就算是我和户冢能轻易叫出的名字，对叶山跟聚集于此地的自称球迷的人来说，肯定是不能随口说出的重要存在。想要静静收藏在心中的珍宝。

恐怕是过再久都不会褪色，甚至如同恋情的存在。

可是这样的话，对我而言折本就是……嗯……我只是因为很烦才不想说耶……

因此我也没说出那名选手的名字，转换话题。

「今天的对手是……岐阜吗？是怎样的队伍？」

我连岐阜在哪都不太清楚。呃……是名古屋县的殖民地？

「嗯，很难称得上强……吧？」

不会伤害任何人的形容，很符合叶山的作风。

「从来没升上甲组。每年都会在乙组争夺最后一名，目前的排名也是垫底。不过，他们的踢法很有趣。虽然不久前换教练后，好像就换成走现实路线了。」

「实力弱还能踢得有趣？」

「贯彻理想的足球……我不知道这样形容贴不贴切，总之他们经常传球，是很像足球的足球。看了你一定就能明白。」

「哦——？」

像足球的足球啊。

「那也有不像足球的足球啰？」

「你真的是……特别会戳别人的痛处。」

叶山面露苦笑，眼中却不带笑意。

他接着举例说明「不像足球的足球」。

「派一堆人堵在球门前，守得密不通风，一抢到球就直接长传到对手的球门前。一抢到球就趁对手阵型还没重整前杀向球门。看了大概也不会有趣。」

「我觉得很合理啊。」

让人挡在球门前就绝对不会被得分了吧⁉外行人应该都有过这种想法。

户冢默默听我们聊了一段时间，边吃洋芋片边问：

「叶山同学，那千叶用的是什么战术？」

「高位压迫。」

「高位……压迫？」

陌生的词汇令户冢「唔咦咦？」纳闷地歪过头。唔咦咦……好可爱喔……

不不不。高位压迫是什么东西？

「把防线推前。也就是将防守的战力也统统挪去进攻的战术。」

呣……

相当刺激中二魂的战术。名字也很有科幻小说名作的感觉。

「只不过，这个战术想用得好需要各种条件，风险也非常大。所以现在是被封印的梦幻战术。刚开始用的时候挺受到瞩目的，成果也不错，但对手一采取对策，经常就会失败。」

「我对足球的战术不熟，不过——」

我先给他打了一针预防针，才说出自己的看法。

「总之先在敌方的球门前塞一堆高大的球员，不是会比较有利吗？像篮球那样。」

「试过了……」

「试过了呀……」

脸上瞬间绽放笑容的户冢，发出叹息般的声音。

「他们从北欧找来身高二零四公分，联盟史上最高的外国选手，让他站在球门前面。」

身高超过两公尺，又是从北欧来的，光听这个条件就好兴奋。我好奇地问：

「顺便问一下，当年的名次是？」

「第六名。要前三才能晋级……」

根据叶山的说明，那位选手刚开始状况是不错，之后因为受伤的关系就踢不好球了。要不要再试试看？

这次换户冢提议：

「那干脆直接豁出去，连续几年都委托同一位教练如何？」

「试过了……」

「这也试过了呀……」

户冢露出悲伤的眼神低下头。

过去一看成绩不好就疯狂辞掉教练的千叶队，终于发现这样下去不行，请来看似颇有前途的教练，基于培养人才的心态让他带了几年队。

「那名次如何？」

「第三名→第九名→第十一名。」

「反而愈变愈差耶。」

「第三年途中果然还是换教练了……」

顺带一提，足球界当中好像有「教练解雇加持」这个解雇教练后，成绩会暂时提升的神秘法则。信不信是您的自由。

不过，既然换教练也没用——

「都做到这个地步还没救，干脆把选手统统换掉试试看？」

「咦咦⁉八、八幡……再怎么说这也太不讲理了吧！足球是团队竞技喔？这样队伍会整个散掉啦！」

「试过了……」

「这也试过了吗……」

户冢的表情超越傻眼，甚至透出一丝怜悯。

虽然是我自己提出的主意，要是把成员全部换掉就能改善现状，每支队伍都会疯狂换人吧。

「足球是一队十一个人的竞技对吧？连九人一队的棒球都那么重视团队合作了。我不认为短期内有办法加强这个部分。」

「在这方面，他们当然也考虑了对策。」

「哦？什么对策？」

「似乎是想藉由贯彻『如果是实力相等的选手，选择比较爱千叶的那一个』这个强化方针，弥补队员间的默契不足。」

「去用MAX咖啡洗把脸再来啦。」

如果对千叶有爱、球技就会变好，Jaguar先生（注6）先生都能当上J联赛的签约球员了。加油！加油！千叶！

想不到主意的我，带着些许自暴自弃的心情说：

「那我看只能那样了。从改变食物下手怎么样？」

「那个也。」

「已经试过啦……」

重复的对话。恶性循环。连户冢的语气都不再惊讶。

「所以？怎么个改变法？从吃饭换成吃面包之类的？」

「统统换成糙米。」

「他们是想跟筱田麻里子结婚吗？」（注7）

糙米婚在前阵子蔚为话题。

以糙米为契机的邂逅挺有冲击性的，这段婚姻给了所有吃米的人希望。我也每天都会吃白米，所以可以跟吃白米的艺人结婚对吧？不可能？是喔。

「那结果呢？」

「哎，对部分选手似乎有效果，可惜对名次的影响不大，所以现在恢复原状了。」

「这样啊……这个结果比你跟我说『超级有效』还能让人接受。」

「移籍的选手在其他俱乐部也会帮忙推荐吃糙米，可以说是唯一的救赎……」

「单纯只是被人拿来当笑柄吧？」

人称糙米法师的那位教练，在第三年的第四场比赛前后被炒鱿鱼，结果掉进乙组时的教练又回来带队，似乎就是现在的状况。

这就是千叶十年来的轨迹。

换教练、换前线工作人员、换选手，连食物都换了。

仍旧拿不出成果。

「我……一直在思考，如何取回千叶破坏掉的东西。不过——」

苦恼的叶山挤出声音说道。

「……最后，还是会回到同样的场所。」

巧的是，跟连接内房线和外房线的苏我站一样，这栋体育场似乎也受到圆环之理的支配。

开球的瞬间比想像中还无聊。

「咦？已经开始了吗？」

比赛开始前，双方的球迷就一直在跳来跳去声援，因此没什么「比赛开始了！」的感觉，而是「啊，在踢球了」。

主场千叶队的声援声量远胜对手。

岐阜的应援团也在靠少数菁英努力，但终究是地方的下级俱乐部，在各方面都看得出他们心有余而力不足。

可是说到最重要的比赛内容——千叶跟岐阜都差不多。

千叶持球时间比岐阜长，却一直在传球，不肯射门。

岐阜只会守在球门前，抵御千叶的攻击。本以为是想伺机反击，抢到球之后选手的动作却很迟缓。

赛况僵持不下，可是剑道也就算了，足球的赛况僵持不下也一点都不有趣。

开赛前叶山说的「不像足球的足球」于眼前展开，使我不禁苦笑。

起初高兴地欢呼「哇！」「冲啊冲啊——」的户冢，也从途中开始就不再说话，最后甚至都在看于后方看台声援的球迷，而不是比赛。

「球迷真努力。两边都一直大喊……好厉害。」

户冢说得没错，声援声量很厉害。

体育场的气氛很棒。演唱会般的魄力。

但这反而让赛况显得更加空虚。两队都不停回传，都攻到球门前了，依然迟迟不肯射门。

周围那些看起来很和善的观众，三十分钟过后也开始不耐烦，加油声逐渐消失，怒骂声及嘘声四起。

「搞什么鬼啊⁉」

「不射门哪赢得了‼」

上半场结束的哨声响起，来自观众席的怒骂，如秋雨般朝着离场的选手降下。

「…………看完上半场的感想如何？」

宣布上半场结束的哨声响起后，过了一会儿，叶山硬挤出这句话。

用来替换球员的选手现身于球场上，在为下半场的比赛练习。

「嗯……」

户冢思考着该怎么回答叶山的问题。这个反应就已经是回答了。

我直接将内心所想说出口。

「老实说，很无聊。」

「八、八幡……」

户冢不知所措。比起比赛，我更想一直看户冢。那是我真正的心情。不知所措的户冢超赞。

「我不太喜欢边看运动比赛边抱怨。再努力一点？选手肯定比观众更努力。让我看看你们的感情？想看表现感情的运动，给我去看花式溜冰或韵律体操。我是这样想的。」

一口气说完后，我接着说道：

「可是刚才的比赛，我根本看不出两队想做什么，那不是有领薪水的职业球员该有的表现。我有说错吗？」

「…………不。你说得对。」

我知道自己看免钱的比赛还讲这种话太自以为是，叶山却诚恳地承受住我的话语。

他一定有比我更多的意见。

但这家伙还是在努力为千叶队说话。

「千叶队背负着在主场不能输给最后一名的压力。所以为了不白白浪费机会，会等到决定性的那一刻才射门。不过犹豫反而害他们丧失了射门的机会。」

「恶性循环……」

户冢显得很难过。难过的户冢超级可爱，看到那样的户冢，是上半场唯一的收获。

平常光这样我就很满足了……但可以的话，我还想看见为千叶队的胜利欢呼的户冢。

「叶山，怎么做才能打破这个僵局？」

「换掉动作迟钝的选手，从阵型本身下手是最快的。」

「原来如此。」

「可是上半场的赛况虽然无聊，却是由千叶掌握主导权。所以很难判断该更换哪个部分，再说，连该不该在这个时机换人换阵型都是个问题。也不知道现在的教练有没有能力做出判断……」

叶山担心的事发生了。

先有动作的，是透过上半场的比赛意识到自己占下风的对手。

「⁉喂，岐阜队到了下半场动作怎么突然变俐落了？」

「八幡说得没错！为什么⁉」

下半场开始的哨音响起的瞬间，千叶就面临危机。

明明上半场千叶还略胜一筹啊……？

坐在位子上观察危机的叶山，以平静却有把握的语气说出答案。

「……是位置。」

「「咦？」」

「岐阜下半场换战术了。看，刚才有三个人守在最后，现在变成四个人了对吧？」

经他这么一说，的确，岐阜的最终防线是由四个人排成整齐的一条线共同行动，轻而易举从千叶队前锋的脚下将球抢走。

接着干脆地把抢来的球传到前线。之前只会横向移动的球，变得会纵向移动了。

「改变防御阵型……能加强攻势吗？」

「足球的攻击从防守方抢走球开始。也有这种看法。」

「……原来如此。『防守是攻击的第一步』的意思。」

这想法挺有趣的。

这样的话，也可以理解为何双方上半场都不怎么射门了。

那是在敌阵防守。

听见叶山的说明，户冢困扰地垂下眉梢问：

「可是……那千叶队该怎么办？」

「不好说。」

叶山抱着胳膊沉吟。

「最好的方式我也不知道。不过，千万不能——」

这个瞬间。

划破空气的尖锐笛声响起。

「糟糕！我才刚说……！」

叶山屁股从座位上抬了起来，放声大叫。

好像是岐阜队的前锋抓准千叶队防线露出破绽的瞬间，杀到球门前时，千叶队的选手撞了他。

「咦？发生什么事？咦……？」

注意力都放在跟叶山谈话的户冢，似乎漏看了那一刻，有点恐慌。

「咦⁉犯规⁉千叶吗？」

「嗯。阻止得分……岐阜的前锋在无人防守的状态下来到球门前，那位球员从后方干扰了他。裁判一定会发牌。问题是发哪种颜色的牌。」

体育场内鸦雀无声，彷佛刚才的喧嚣从未存在过。

然而，看见裁判举起的牌子是什么颜色，状况瞬间一变。

「直接发红牌⁉」

「主审搞什么鬼‼有没有长眼睛啊⁉」

一直乖乖坐着观赛的后方看台区观众同时起立，用嘘声和指笛跟裁判表达不满。

千叶队的选手也围住裁判激烈抗议。连教练都指着主审举起的红牌，对附近的副审怒吼。理应要在旁边负责抬担架的户部也嚷嚷着「喂！不是吧——⁉」跟教练一起对裁判抗议。你小心被赶出去喔。

主审却置之不理，没有要改变判决的迹象。

「裁判有问题吗？」

「……不。那是正当的判决。」

叶山的语气冷静得吓人。

「那是千万不能采取的行为……但在那个状况下是必须的。因为不这么做对手一定会得分。」

「你这句话真可怕。意思是叫人欢迎违反规则啰？」

「那就是足球。违反规则也是规则之一。我相信你懂吧？」

「……」

说实话，今天我对叶山彻底改观了。

与此同时，对足球也彻底改观了。

因为，必须在熟知规则的前提下违反规则……跟我至今以来的所作所为如出一辙。

我对于这个事实抱持难以言喻的情绪，户冢则跟我形成对比，只顾着为千叶队担心。

「欸欸！裁判举牌了耶⁉红牌耶⁉之后会怎么样⁉」

「一人退场，千叶要靠十个人继续比下去。」

「那不是超不利的吗⁉」

「是啊。不过，这样比赛终于会变有趣了吧？」

「咦……？」

户冢感到疑惑。

叶山这句话的真意，很快就反映在球场上。

观察状况的我，如此形容眼前全新的攻防战。

「……没想到比赛变得挺精采的耶？」

「少了一个人，整个千叶队的精神都统一成『战况对我方不利』。之前混杂着『我们占上风』和『势均力敌』这两种，所以攻守交替时无论如何都会产生时间差。现在却不会。」

「就是在瞧不起岐阜啰？」

「你真的都不斟酌措辞的。」

叶山苦笑着用这句话表示肯定。

然而——

「竟然还有人数变少，赛况反而会变得更有利的时候……」

「很有趣吧？比起精神不统一的十一个人，精神统一的十个人更强。」

「嗯……有趣。」

不行。我愈来愈喜欢足球了。

在绿色草坪上进行的，是一场大规模的实验。类似于用人下的西洋棋。

没错。西洋棋。

既然如此……战斗的结果不言自明。尽管千叶看起来暂时压制住了对手——

「可是……这样下去赢不了。」

「你总是在最短的时间内看穿本质。没错……这样下去赢不了。」

听见我和叶山这么说，户冢一脸惊讶。

「咦？为什么？」

「冷静一想就知道，岐阜比较有利。」

单纯的计算问题。

「千叶靠统一精神变强了。那岐阜也统一精神不就得了？」

「要怎么做？」

「喊出来就好。像那样。」

我指向球场。

手臂上戴着黄色队长标志的选手，从最后方高声呼喊。

岐阜那因为过于亢奋而缺乏统一感的阵型，再度凝聚起来。千叶的攻势立刻减缓。

「比企鹅说得没错。沟通不足可以靠那种方式弥补，少掉的选手却无法补充。」

「那、那叶山同学！该怎么做才好！」

「…………」

叶山陷入沉思，闭上眼睛。

不久后，静静、缓缓地睁开眼。

眼中闪烁着异样的光芒。

「……我觉得，果然该再试一次高位压迫。」

「叶山。」

「不是吗⁉高位压迫可是理论上最强的战术！攻击就是最好的防御，这个道理连小孩都明白吧⁉你也明白吧⁉」

激动的叶山带着明显失去理智的表情，向坐在后面的亲子的小孩子征求同意。

那个小孩吓得要命。我想也是。

「冷、冷静点，叶山同学！」

「对啊叶山！这样真不像你会做的事——」

「不像我会做的事？你又懂我什么？」

叶山露出冷笑，接着热情地诉说：

「乱来又怎样⁉再怎么被其他人否定，都不会放弃挑战，那就是千叶的骄傲吧⁉奥西姆（注8）传承给我们的精神，不就是这个吗⁉」

你把奥西姆的名字说出来了啊……

叶山隼人什么都不缺。

本人虽然表示否定，无论是选手还是前线工作人员，他应该都能拿出水准以上的成绩。

想让千叶再度夺冠，也不是不可能。叶山隼人就是如此优秀。

他却没有这么做。

能当上主角的男人……没拒绝担下这个职责的男人，在体育场里选择只当区区一个路人。即使是简单的协助比赛进行，都坚持不插手。

正因如此，才会这么狂热。才会这么渴望。

正因为遇见了单靠自己一个人的力量无能为力的事物，叶山才有办法认真到这个地步吧。

有这样子的对象……我甚至开始羡慕他。

「不……不对。不只叶山……」

「八幡……？」

我下意识喃喃自语。旁边的户冢担心地看着我。感觉到他的视线落在脸颊附近。有种脸颊在被人戳的感觉，好舒服……

对自己以外的人抱持期待。

世上存在全心全意为他人声援，不求回报的人们。

我有点期待这个名为体育场的空间，会帮我否定从我过去的人生经验得出的结论。

不对。

这是第一次来体育场的我自私的妄想。仅仅是「但愿如此」的希望。把自己的愿望强加在别人身上是不对的。现在正在加油的人，输掉的话肯定会对选手们破口大骂。跟聚集在涩谷路口的集团一样，追求胜利快感擅自兴奋，完全没考虑到选手的心情，不负责任地大叫「一定要赢啊」。

在我如此心想的瞬间。

「嗯？这首歌是……？」

面临最大危机的千叶队的球迷选择的应援曲——不是激情的歌，也不是节奏轻快的歌。

那首歌化为平静的旋律传入耳中。

我在前往体育场的途中，得知它的名字。

「奇异恩典……」

不是战斗——而是祈祷的歌。

无论面临多么艰难的道路、多么痛苦的时间，都要共同迈进。

无论现在处于什么样的状态下，都不会移开目光。

或许他们在战力及战术上累积而来的东西都崩溃了，失去优势。

或许他们在乙级联赛这个类别里，连惊人的资金都失去了。

即使如此。

还是有一个绝对不会消失的东西。

就是……绝对不会忘记的回忆，以及荣耀。

将怀着热情尊严持续战斗的决心，透过平静旋律唱出来的人们。

那个存在本身就是奇迹。

它在球场上又制造出了另一个奇迹。

「⁉八幡……你看！八幡‼」

「那、那是……⁉喂叶山！那到底是什么状况⁉」

「防线……在往前推……？」

叶山瞪大眼睛，彷佛看见难以置信的画面，摇摇晃晃地站起来。

其他观众也一个个起身，我和户冢也站了起来。

为了亲眼见证球场上的「奇迹」。

「八、八幡……这是……这是……‼」

「嗯。这大概就是——高位压迫！」

不会错。

我正在见证奇迹。遭到封印的梦幻战术。

宛如在白天现身的龙，防线强势地在球场上不断推进。以彷佛有生命寄宿在其中，拥有自身意志的动作。

连守门员都离开自己该防守的球口，前进了一大段距离。

穿过禁区，移动到近乎中线的地方。

再怎么说也太前面了。

守门员背后是广大的绿色草皮。空无一人的空间。

「这……真的是足球吗……？」

户冢还不敢相信眼前的画面，不安地揪住我的衣服。我也还不敢相信……这么可爱的人竟然是男生……

「WIN BY ALL‼WIN BY ALL‼」

带头喊口号的人握紧扩音器，在后方看台炒热气氛，整座体育场以此为爆炸中心，剧烈震动。

这个时候我才知道，人类的声音有办法制造出如此剧烈的震动。

球迷的声音撼动空间。

以及……人心。

「这样才是千叶！我们的骄傲！」

「共同奋战吧！无所畏惧！」

周围的观众也明显情绪激动。

他们将毛巾高举在头上站起来，一个个加入〈奇异恩典〉的大合唱。

户冢也在唱他刚学会的应援歌。

叶山则边哭边唱。

众人的歌化为力量，给予千叶的选手一对翅膀！

「好厉害……！好厉害喔八幡！跟上半场比起来，简直是不同的球队！」

「嗯！千叶彻底压制住岐阜了！」

这才是千叶真正的力量吗？

明明人数比对手还少……看起来却有比对手更多的人在踢球。整个把岐阜压着打。

叶山揭露这个魔术的手法。

「藉由让守门员一起传接球，弥补人数不足。这就是高位压迫的价值所在。」

「！原来如此……所以守门员才会跟着跑到那么前面。」

至今以来，我一直以为守门员只会站在球门前。不用动就行，是最轻松的位置。

所以体育课上足球的时候，我也都自愿担任守门员……不过看到千叶队的守门员，我的既有观念遭到粉碎。

他的位置大幅超出禁区，不能以手触球，因此是用头槌撞球。踢角球的时候还会冲到敌人的球门前争取得分机会，同时兼任守门员及前锋。比球场上的任何人都忙。

叶山兴味盎然地看着被守门员的动作夺去目光的我，说：

「比赛开始前，你觉得我连守门员的球衣都有买，很奇怪对吧？」

「呃，那是……」

「现代足球中最需要技术的，无疑是守门员。正因为有那名守门员在，千叶队才能选择高位压迫这个战术。」

看见独自穿着跟其他人不同色的球衣，比任何人都还要自在地于球场上奔走的身影，我很能体会叶山想要守门员球衣的心情。如果要我挑一件球衣，现在的我八成也会选守门员的。

另一方面，岐阜的外国人守门员怒吼着，如鬼神一般不停挡球，但他光是把球弹开就竭尽全力了，没那个余力接住球。

而每一颗被挡掉的球都由千叶队接到，再度发动攻势。反覆这个过程。

不过，千叶队仍未进球。

大约第二十次的射门被挡下来，户冢抱头大叫：

「啊啊！都射门这么多次了，为什么进不了⁉」

叶山低声给予令人难以置信的回答。

「岐阜比赛时，岐阜县出身的Mr. Maric（注9）一定会在日本某处发送意念，所以守门员可以发挥超水准的实力……的样子。」

念力吗⁉

「但那仅仅是迷信！只要维持这个节奏就能赢！」

听见叶山信心十足的发言，我和户冢都点了下头。

比赛过了九十分钟，就算进入了补时时间（现在似乎叫加时），我们仍然相信千叶会获胜，持续呐喊。相信每个人的声音多少能将球迷的心意传达到球场上。这股冲动简直像恋爱。

有机会得分的时候，不知不觉我也将叶山借我的毛巾拿在头上甩动，感受着难以形容的团结感。在涩谷大吵大闹的意义我不明白，但我现在能理解在体育场拍手高呼的心情了。

直到最后一刻，千叶的猛攻都从未停歇！反覆进攻！球被弹开后又继续进行波状攻击！球不停在岐阜的球门前来来回回！

对手被逼得传出一记长传，在球场上画出如同彩虹的抛物线，从跑到中线的守门员头上飞过去，直接进门。这一分成了决胜关键，千叶队输了。叶山像断线的木偶般瘫坐在椅子上，比赛结束后还是没能马上站起来。

防御脆弱得跟塑胶一样。高位压迫果然搞错了。

完

1注	  指世界杯足球赛的主题曲《Ole ole ole ole we are the champion》。「Ole」为日文的「我」之意。

2注   电话诈骗手法，通常以「是我啦是我啦」开头。

3注   德国足球员，一九九三年加入千叶队。

4注   等待偶像出场、进场的意思。

5注   日本职业足球联赛分为甲级、乙级、丙级联赛，各级之间设有升降级制度。

6注  千叶的知名音乐人、当地艺人、实业家。

7注	  前AKB48成员筱田麻里子及其丈夫都吃糙米长大。

8注 日本魔术大师。

9注  伊维卡･奥西姆，二○○三年受邀担任千叶市原队的教练，二○○五年率领队伍夺得史上第一个日本联赛杯冠军。

** 义辉的野望･全国版

作者：伊达康／插画：红绪

吾名为材木座义辉。

经常有人误会成「木材座」或「材木屋」，「材木座」才是正确的。

惨一点的时候还会被人说「喔，就那个啊，那个名字很像五金行的人」，但我叫材木座。

顺带一提，我查过星座，没有材木座这个星座。没办法。就算有，圣衣<Cloth>八成也是木制的。遇到火焰系招式只有死路一条吧。

……他人无法正确认知我的真名<Mana>，是有原因的。

因为我材木座义辉乃孤高之人。是不会结党成群的独行侠。

我在教室几乎不会跟班上的人说话……有点太爱面子了。差不多可以说没说过话……我又在顾面子了。根本没说过话。

恐怕是因为我身为剑豪将军的威猛霸气，会令一般学生本能性地畏惧我。

类似人称「圆」的念能力，范围长达半径四公尺。那部漫画什么时候才会出下一集啊。（注10）

因此，谁都不会靠近我。真的没人会靠近我。人少到听得见「那家五金行迟早会倒闭吧？」的窃窃私语声。

但那也是无可奈何。

吾乃复苏于现世的剑豪将军。拥有过于强大的力量，背负必须不断战斗的宿命之人。

众人只要享受和平的日常即可。我会守护世界，今晚我要做的也只有将魔物斩杀殆尽。钱存得差不多了，我要去买水镜之盾了（注11）。

总而言之。

我每天都过着崇高的生活，却要付出代价。

上下学、下课时间、午餐时间……在校园生活的各种局面，我都经常被迫单独行动。做什么事都是单骑走天下。

其中最麻烦的，是体育课。

或许各位会感到意外，我其实很会流汗。排汗功能比一般人还要好。也容易喘气，这是因为我必须分一部分体力压制从右手溢出的邪气。

不，这不重要。

体育课让人难熬的不是体力方面，反而是精神方面——

「好——自己找朋友两两一组。」

体育老师残忍的指示，对我而言如同恶梦。

不是我在自夸，这种时候我有九成九的机率会没组。剩下那零点一成是跟老师一组。嗯，这不是自夸，是自虐。

每次我都会期待「说不定今天会有失去理智的人来找我一组？」可惜那样的救世主从来没出现过。俗世真的是艰辛啊。

「不能设法改善这个不良风习吗？」

一名沉默斗士怀着冰冷的心独自站在那边，凝视众人甚至跨越班级的藩篱纷纷组成一组。也就是我。

在我宛如于黑暗中摇曳的火光伫立于原地时，大部分的人都找到人一组了。将我这个剑豪将军晾在一旁。

「呣……剩下的人还有十个左右吗？」

没错。真正伤人的现在才开始。

卖剩的人即为在众人面前出糗的人。与昭告天下「我的朋友很少」无异。对青春期的人来说，是非常丢脸的一件事。

因此剩下的人会感到焦躁，拼命寻找搭档。妥协再妥协，硬是随便找一个人组队。

就像堕入饿鬼道的亡者。事已至此还没人来找我，究竟是怎么一回事？怕了吗？

「真是，一个个都如此肤浅。就这么讨厌只身一人吗？真该学学平冢老师。」

你们没有尊严吗？

不，正因为有尊严，才忌讳孤独。不惜贱卖自己。

无论如何，到这个阶段，「找朋友一组」这个宗旨已经失去意义。如果一开始就说「按照座号两两一组」，就不会有任何人受伤了。

「再说，这个世界未必能跟喜欢的人结合。正因如此，NTR这个类别才会有一定的人气吧？」

在我忍不住口吐诅咒时。

我的双眼捕捉到一名男子。

那家伙跟我一样，至今仍独自伫立。没去找搭档，跟地缚灵似地站在那里，散发出负面情绪。

「呵，是彻头彻尾的边缘人吗。可怜啊……」

他也是体育课不良风气的受害者。没有挚友<朋友>，没有强敌<朋友>，没有认识的人<朋友>，在极少数的情况下，甚至连可以打招呼的人<朋友>都没有的单身贵族。

「不，从那不起眼的外表来看，是单身平民吗？和身为将军的我一组，对那人而言或许负担太重，但这也称得上缘分。我就施舍他一些慈悲吧。」

我判断该对那只迷途的羔羊伸出援手，故作自然地走近他。

尽管提不太起劲，总不能对弱者见死不救。由我来成为你的救世主。所以给我等着！别跟其他人一组喔！不然我会哭喔！求您大发慈悲！

不晓得是不是我的祈祷奏效了，边缘人依然是自己一个。过没多久，他似乎发现我在接近了。

「…………」

「…………」

边缘人讶异地看着停在离他两公尺左右的距离的我。

印象最深刻的，是他的眼神十分混浊。像只死掉的鱼。我昨天晚上吃的煮岩鱼，眼睛就是长这样。

「…………」

「…………」

我们像要决斗般对峙着，经过数秒的沉默。

双方默默无言。对方应该知道我走过来的理由，却坚持等待。我都走到你旁边了，不能由你开口邀约吗！

「…………」

「…………」

漫长得恍若永恒的互瞪，又持续了三秒左右。

对方仍旧一语不发。我也是。既然如此，就要比毅力了。

要不要跟我一组？……我们都在拒绝说出这句话。说了就输了。

「…………」

「…………」

我判断这样下去没完没了，决定采取行动。

拖着步伐慢慢拉近距离，向对手施压。我还下意识在心中念起「卡巴迪，卡巴迪，卡巴迪（注12）」。

敌人却并未上钩。我拉近多少步，他就退后多少步，维持同样的距离。如同海市蜃楼。

……这男人，不简单。

不过，竟敢跟我比心理战，可笑至极。平民自以为赢得了将军吗？

既然如此——我稍微清了下嗓子。接着偷瞄四周，对他使出「看，大家都找到搭档啰？剩下我们啰？」的精神攻击。

但敌人也不容小觑。他缓缓蹲下，使出重系鞋带的招式。喂，那么明显就别演了。你鞋带又没松掉。

……这个边缘人不怕自己是边缘人吗？

那还真是可怕的精神力。根本是边缘人专家。如果他是卡巴迪专家怎么办？

然而，我可是剑豪将军。可不能让不败传说蒙羞。因此，我直接靠眼神对敌人那双死鱼眼诉说。

——边缘人啊，放弃无谓的挣扎。你已经没时间了。

——你也一样吧。

——给我说。邀请我跟你一组。现在不是挑对象的时候了吧！

——就说了，你也一样吧。

——别意气用事！放自己一马！你已经很努力了！

——怎么有个难搞的家伙凑过来啊……

就旁人看来，只会觉得是两个捡剩的人在拖拖拉拉吧。

事实上，我们之间进行了这样子的心电感应。大概。

如履薄冰的牵制又持续了五秒钟左右时，比赛以意想不到的形式落幕。

「那边那两个，别再拖了。你们就一组吧。」

体育老师失去耐性，一句话收拾了这个局面。

可恶的体育老师。还不都是你害的。竟然还敢打断我俩的战斗，究竟有何居心！反正都要插手了，不能快一点吗！

于是，我只得跟这个眼神死的边缘人一组。

男人名为比企谷八幡。

未来将与我共度无数堂体育课之人——

「今天我朋友请假，所以我偶然，碰巧，奇迹似的剩下来。」

记得我对他说出的第一句话，是彷佛在虚张声势的辩解。

我好歹是剑豪将军。不能被区区平民瞧不起。不，以这男人不畏惧当边缘人的胆量，搞不好是武士。搞不好是下级武士。

「啊——不用跟我找藉口。」

对方却一副没兴趣的样子，懒洋洋地扔回一句失礼的回应。还是一样顶着那双死鱼眼。我三天前吃的鲷鱼烧，眼睛就是长这样。

老师叫我们两人一组做伸展运动，因此我们也效法其他人，磨磨蹭蹭地开始做伸展。我先张开双腿坐到地上，让边缘人帮我压背。

「你柔软度好差。文风不动耶。」

「肚子卡住了。别在意，体育课与战斗不同。我擅长的是后者。」

「那个肚子战斗时也很碍事吧。」

我忍不住对喋喋不休的下级武士「呣」了一声。不久后换成我来帮他压背。

「是说你啊，似乎是相当有名的边缘人。」

「闭嘴。因为边缘而有名超惨的吧。」

「是我失言了。吾名为材木座义辉。室町幕府的第十三代将军——足利义辉灵魂的继承人。」

「啥？」

听完我的自我介绍，边缘人发出错愕的声音。

「足利义辉？对喔，他在《信长的野望》里有出现过。」

「哦，你认识他吗？我继承了他的灵魂。」

「继承了吗？」

「正是。」

「原来如此……虽然我早就隐约察觉到了，你果然是那方面的人。」

边缘人伸展完后站起身，脸上不知为何带着淡淡的苦笑。接着不知为何拍了下我的肩膀。

「你、你那看着被雨淋湿的弃犬的眼神是什么意思？」

「不错啊？你们名字一样嘛。」

总会觉得自己跟那人有点关系嘛，我懂我懂……他的眼神彷佛在这么说。

「住手！别用那种怜悯腐烂的眼神看我！」

「腐烂是多余的。」

这个边缘人未免对跟他一组的将军太失礼了。我只是基于同情才跟你一组喔！不是谁都行喔！不过……谢谢你愿意跟我一组。

「无论如何，我已经自我介绍完了。你也报上名来。」

「比企谷八幡。不用记住也没关系。」

听见他冷冷说出的这句台词，我立刻瞪大眼睛。

「是那个吗！『你这家伙马上就要死了，会被我打倒，所以没必要记住』的意思吗！」

「不，并不是……算了，就当成是那样吧。」

「而且，你说你叫八幡？说到八幡大菩萨，祂可是受人尊敬的武神！呵呵呵，是吗，原来是这么一回事。」

我低声笑着，单手用力一挥，掀起大衣。然后在下一秒想到我现在穿着体育服，所以没穿大衣。

「这么一回事是怎么一回事？」

「你为了与我并肩作战，转生到了现世对吧？」

「不，并没有。」

「让我为误以为你是平民一事道歉。我真是看走眼了。」

「呃，我是平民没错。」

「此刻，我取回了遥远往昔的记忆。没错，记得我身旁的确有你的存在。我的爱刀——大般若长光……那就是你的前世对吧！」

「至少把我的前世设定成人类。」

「来吧，我的伙伴！让我们像过去一样，再度征服天下！与我剑豪将军一同！呵哈哈哈哈！」

八幡大菩萨冷眼看着放声大笑的我。那眼神彷佛在注视蛔虫，一点都不像菩萨。

「……足利义辉确实被称为剑豪将军。拿这一点当人设的基础，我认为还不错。」

「呣？」

「但反过来说，也可以视为你逃避靠原创设定决胜负。也是啦，跟史实借设定比较快也比较轻松。」

「咕噜咕噜！」

我不小心咳了一大声，比企谷八幡却接着说道：

「还有，足利义辉用过一阵子的大般若长光，现在依然收藏在东京的博物馆喔。它不是我的前世吗？」

「哥摩拉哥摩拉！」

「如果再加上八幡大菩萨的设定，整个漏洞百出耶？」

「杰顿杰顿！」

「这什么咳嗽声。」

明明是初次见面，他的批评却毫不留情。我有点受伤。

这家伙到底是什么人？到底有没有社交能力？人类是有办法如此失敬的生物吗？是能随便说人肚子大的生物吗？

「我、我不说话，你当我是哑巴啊……！」

「你有说话啊。你不是喊了怪兽的名字吗？」（注13）

「速速跟我道歉！跟我义辉道歉！也要跟那个义辉道歉！」

「烦死了。」

「呣！接招吧，『雷神<Mjolnir>碎霸拳<Break>』！」

「啊——好痛好痛。还有好中二。」

边缘人还没中招就给予这种回应，无视我快步离去。体育老师不知何时叫人集合了。

之后很快就开始今天要上的排球课，下课钟响之前，我们都没再交谈过。

下课后，他只简短告诉我一句「拜啦」就迅速走进校舍。我只能像安娜一样，咬牙切齿地看着他逐渐远去的背影。（注14）

「比企谷八幡吗……没想到总武高中有这么一号人物。」

下意识脱口而出的声音，因为打排球的关系变得沙哑。体育服也满是汗水。

真是个奇妙的男人，但我们不会再碰面了。不对，体育课还是得上，所以说不定又会再见面。

「那家伙，一直叫我去捡球……」

——那就是我和比企谷八幡的相遇。

数日后，体育课再度到来。

「今天我朋友又请假，所以我偶然，碰巧，奇迹似的剩下来。」

不知是否为命运的恶作剧，我和比企谷八幡这次再度同组。在我跟上次一样以卡巴迪的方式一步步逼近他，跟他互瞪时，体育老师下达那样的指示。

「就叫你别找藉口了。」

「呵呵呵，比企谷八幡……看来我和你果然前世有缘。来吧，帮助我做伸展操！我的背后就交给你了！」

我坐到地上张开双腿，比企谷八幡叹了口气。似乎听见他在碎碎念「这人好烦」，大概是我幻听。

「嗯哼，像这样让随从精心服侍真不错。你是否也想起了那个时候？将一切奉献给对主人的忠诚，不断战斗的遥远往昔。」

「换人了。接着换你服侍我，随从。」

「嗯哼。」

真想现在就叫他切腹，没办法，我只得协助他做伸展。我俩才见面第二次，这男人真不懂得客气。

我们默默做完伸展操后，开始上课了。

今天也是排球课。

「我不擅长排球。万一我一不小心使出全力攻击，可能会导致地面炸裂。力道难以控制。」

「是喔。辛苦你了。」

「足球也不擅长。万一我一不小心使出全力射门，守门员可能会分解成原子等级。冲击力就是这么大。」

「世界杯加油啊。」

「网球也不擅长。万一我一不小心发动材木座领域，一、两只桦地（注15）根本算不上什么。」

「别用『只』当桦地的量词。」

看其他人比赛的期间，我和比企谷八幡闲聊着。

……事到如今我才发现，他从未主动与我攀谈过。

尽管态度很差，他姑且会回我几句。但几乎不会自己开话题。

这就是边缘人之所以是边缘人的原因吗？虽然不关我的事，真担心他的未来。这家伙让人难以接近的气场，是不是在我之上？

「你一直都是这副德行吗？这样在社会上很难生存吧。」

「放心。我只有对你会这么随便。」

「呣哼？为何对我如此冷淡？你是那种会忍不住想欺负喜欢的将军的类型吗？无妨，把理由说来听听。」

「就是你这一点。」

「呣哼。」

「中二病也该有个限度。」

「呣哼哼。」

尽管我们才认识没几天，我明白了一件事。

这个叫比企谷八幡的男人……是不是高二病？

他说我是中二病。这个词是指对漫画、动画、游戏中的能力抱持憧憬，装成自己也有那种能力的人。

而高二病主要是指脱离中二病后，因为反弹的关系变得异常现实主义的症状。厌恶曾经是中二病的自己，特别看不起人的现象。

若是这样，他未免太愚蠢了。

边缘人不就是边缘人吗？我和你有什么不同？仅仅是一直得同样的病，和罹患新的疾病的差别吧！虽然我真的是剑豪将军啦！

「呵呵呵，比企谷八幡……我摸透你的底细了。如此程度怎可能征服天下！不退缩！不献媚！不回头！将军就是这样！」

「那不是将军，是圣帝吧……」（注16）

边缘人一脸不耐地反驳我的强力主张。就是因为这样你才会沦为边缘人！

「要我讲几遍都行！将军不退缩！」

「你是让人吓到退缩的那个吧。」

「不献媚！」

「因为献媚也没用。只会让你变得更恶心。」

「不回头！」

「求你浪子回头吧。我认真的。」

「你、你这个笨徒弟——！」（注17）

高二病患者又说了没礼貌的回应，在我用要让他石化的气势瞪向他的瞬间。

一颗排球直接砸在我的侧头部上，还以为脸要爆炸了。

「呜呃噗！」（注18）

我听见「啊，抱歉」的道歉声，呈大字形倒在地上。此生有无限的悔恨（注19）。

看来是比赛途中用力击出的球，不小心飞到其他地方砸中我了。谁技术那么烂！不要像什么事都没发生一样继续比赛好吗！

我感觉到脸颊阵阵发麻，空虚地凝视蓝天，过了一会儿。

「喂，你还活着吗？」

比企谷八幡探头观察我的脸色，用小树枝戳我。这家伙，竟敢把举世无双的剑豪将军当成大便戳。

「呼，太大意了……我什么都看不见……包括你的脸……」

「不是因为眼镜掉了吗？」

「连坐都坐不起来……」

「不是因为肚子太大吗？」

「连脸都抬不起来……咦？真的抬不起来。」

「啊，我踩到你的头发。谁叫你留那么长还绑起来。」

「你这家伙在干么啊！」

他无视坐起身子怒吼的我，快步走向体育老师。

经过十秒左右的交谈，比企谷八幡再度走回我旁边。出乎意料的是，他对仍然坐倒在地上的我伸出手。

「站得起来吗？老师说你可以去保健室。」

「喔喔，你……其实在为我担忧吗？呣哈哈哈，想不到你会以这种方式表现出娇的一面。虽然一点都不可爱，我就原谅你吧。」

「托你的福，有藉口让我不上课了。」

……绝不原谅。

之后，我便让比企谷八幡搀扶着离开操场。一进到校舍，那家伙就迅速放开我，扔下一句「你自己走得动吧？就算走不动也给我自己走」。

看来这家伙不只眼神，连人格都彻底腐烂了。如果让他打格斗游戏，他肯定会脸不红气不喘地用连段把新手接到死。

不过，我对这个叫比企谷八幡的男人，开始产生难以名状的兴趣。

剑豪将军的直觉告诉我。他一定是我的同类。能理解我的梗，是这一侧的居民。

认识圣帝、玩过《信长的野望》，连桦地都知道，就是再明显不过的证据。

若这男人真的是高二病，过去很有可能是中二病。很可能是沉浸在次文化中的宅企谷同学。

此时此刻，可否请你取回当时的自我？

可否请你取回那个纯洁无垢的你，那个花了三天三夜认真烦恼该娶毕安卡还是芙萝拉（注20）的你？

这个愿望实现时——我俩或许能成为人称朋友的关系。

这家伙搞不好真的会娇给我看。

到时，未必不会迎接我们在体育课以外的场合也会交流的未来来日方长长命百岁岁岁平安。

我也不喜欢跟人打好关系，但学校有个人可以陪我聊这一期的动画里面的爱妻<女角>有多有魅力，也无伤大雅。想要有人陪我聊。

为此，再观察这男人一阵子吧……我走在通往保健室的走廊上，下定决心。

我望向旁边的玻璃窗，自己的身影倒映在其上。

脸上有被排球砸过的痕迹。

数日后。体育课的时间再度到来。

体育老师叫大家两两一组的瞬间，我就用高速卡巴迪接近比企谷八幡。

那家伙慌张地左顾右盼，试图找其他搭档，然而为时已晚。他还是被我逮住了。

「呵呵呵，真巧，比企谷八幡。今天我朋友又刚好——」

「你的朋友直到毕业大概都不会出场。」

他大概是投降了，深深叹息，抬起下巴对我一指。叫我赶快坐到地上开脚的意思。

我利用短暂的伸展时间，立刻着手试探他。

首先，最重要的是……看看这男人对漫画、动画、游戏有多精通。

「我说，八幡啊。」

我直接用名字叫他，结果遭到无视。呣，有点太急了吗？

「听见零这个名字，你会想到谁？南斗那位？新世纪福音战士那位？火星仙子那位？」

「阿姆罗。」（注21）

「那么听见凛<Rin>这个名字，你会想到谁？姓星空的？姓涩谷的？还是姓远坂的？」

「克林<Kuririn><rt/>。」

「那么听见桦地这个名字，你会想到谁？打网球的？念冰帝的？还是会学其他人招式的？」

「不都是桦地吗？」

如我所料，那家伙一个个回答我的问题。我藉机深入话题。

「电击应该会继续称霸吧。」

「我相信总有一天会是GAGAGA的天下。」

「哦，轻小说也行吗？那么严格挑选出你喜欢的三位绘师说来听听。顺带一提，我是——」

「喂，要集合啰。」

讲到这边，八幡无情地离去。

这家伙守备力真高。如果能至少得知他喜欢的作品，就能从这边一口气发动攻势了。好吧，光是知道他喜欢GAGAGA文库就够了。

没关系，体育课才刚开始。有充分的时间……本来是这么想的，却发生一个问题。

今天竟然不是上排球，而是跑步。而且还是马拉松。

不是我自夸，我不擅长长距离跑。也不擅长短距离跑。可以的话连路都不想走。爬楼梯也是，超过五层就会忧郁。

该死的体育老师。动不动就妨碍我的计划！马拉松没必要组队，这样我怎么跟他讲话！这家伙绝对会把我晾在一旁！

我担心的没错，八幡果然抛下我了。

直到途中我们都还是一起跑步，接着我慢慢落后，对他说「别管我，你先走！绝对不要回头！」结果他还真的照做。那家伙绝对不会回头。

多么无情的人。如果有部轻小说是以你为主角，绝对红不起来。绝对不可能成为GAGAGA的台柱。

我在内心抱怨，正准备放弃今日的八幡研究时。

一度从视线范围内消失的八幡的背影出现在前方。他似乎放慢了不少速度。好，这样就追得上了！义辉涡轮，解除限制器！

我压着晃来晃去的肚子，勉强跑在八幡旁边。他只是瞥了我一眼，半句话都没说。真无情。

「噗嘻，怎么啦八幡？噗嘻，我不是叫你别管我，自己先走吗？噗嘻。」

「谁会努力跑马拉松啊。」

「噗嘻，是吗？噗嘻，那我们就一起跑吧。噗嘻嘻。」

「你在发出奇怪的声音喔。」

「别在意。是义辉涡轮的副作用。噗嘻嘻嘻。」

「比平常恶心三成。」

尽管我跟千代富士（注22）一样感觉到了体力的极限，依然不屈不挠地进行八幡研究。

这次我将话题转为恋爱游戏，好确认他的兴趣范围。这段期间，涡轮的副作用仍在持续。噗嘻。

「……于是，我成功攻略了女主角。在结局的毕业典礼上，由她主动跟我告白。」

「如果你也能就这样从恋爱游戏毕业就好了。」

「你不玩这类型的游戏吗？意外地颇多名作喔。」

「某天我忽然意识到。到头来，游戏的男主角并不是我。」

「噗嘻？」

「再怎么提升游戏中的学力、体力、魅力等素质，我的素质也不会提升。」

「噗嘻嘻？」

「不要用涡轮声回应。」

我和八幡慢吞吞地跑着，被附近的学生接连追过。这速度已经可以说是单纯的快走。

「跟游戏一样温柔的女人，现实中并不存在。不对，游戏里的女人说不定也一样喔？跟你告白的女主角，也向其他玩家告白了喔？」

「你、你这家伙！给我向所有恋爱游戏的女角道歉！先跟藤崎诗织（注23）大人道歉！」

「那你叫她在传说中的大树下等我。」

「不要趁机想跟人家在一起！」

「说起来，非得跟你告白不可，对女主角而言可以说是惩罚游戏喔。」

「别歧视将军！呣！接招吧，『伟大的神罚･炎灭击掌<Nemesis Bolt>』！」

「就跟你说中二病要适可而止了。」

这时，八幡异常严肃地注视我。两眼依然无神，但这或许是他第一次好好看着我的脸说话。

「材木座，人生和角色设定统一一下啦。」

「噗嘻？」

他留下这句话，加快脚步离去。

遗憾的是，我追不上他。我的涡轮已经到达极限，熄火了。

「统一，人生和角色？」

我咕哝着这句话反覆咀嚼，看着他慢慢变小的背影。过没多久，就看不见八幡的身影了。

不是因为他被跑马拉松的人遮住。

而是热气让我的眼镜起雾了。

之后，我和八幡每堂体育课都会一组。

但我们感情并没有变好。那家伙对我的态度还是一样随便，一逮到机会就想把我塞给其他人。甚至说只要不超过两百日圆，他愿意付移籍费。

根据之前的八幡研究，我得知他比想像中更熟漫画、动画、轻小说。特别喜欢GAGAGA文库。

事后我才知道，他的国文成绩排名是全年级第三名。

真令人惊讶。看来看GAGAGA文库的书，有助于提升国文成绩。

「……八幡啊，跟你讲这些也没意义，不过——」

那一天。幸运的是，体育课又是上排球。

我边看比赛，边跟旁边的八幡搭话。那家伙看都不看我一眼，只是随口应了声。

「前几天，有位陌生的女性在站前送我礼物。那人说不定是我前世的妻子。想不到历经风霜，我俩再度相遇了……」

「那个礼物是卫生纸对吧。」

「你怎么知道？」

「想点新梗吧。」

「还发生这样的事件。站前有位陌生的女性对我说『请让我为你祈福』。那人说不定是我前世的妻——」

「连梗都没塞。」

「那么这个如何。前几天，担任生活指导教师的平冢老师说『你也是问题儿童之一』。莫非她才是我前世的妻——」

「不可能。就算是前世，我也不觉得那人嫁得掉。」

「你会被杀喔。」

这时轮到我们上场比赛，因此闲聊暂时中断。

随便打一打球，继续观察八幡吧……我的计划却以意想不到的形式告吹。

不知为何，对手非常认真。我军彷佛受到了刺激，跟着对比赛认真起来。

「好，绝对要赢喔！」

「好耶，偶尔拿出真本事吧！」

「和马拉松比起来，根本是天国跟地狱的差别！」

呼声四起，比赛愈来愈白热化。

看这个气氛，我也不得不加油了。万一我混水摸鱼，可能会被踹屁股。将军的尊严不能允许。

「噗嘻！噗嘻！」

每当为了拦网而跳起来，我的肚子都会弹来弹去。今天是我最痛恨自己不是巨乳美少女的一天。

除此之外，还发生了谋反事件，我方的发球于我的后脑勺炸裂。是八幡干的。

等到比赛终于结束，我累得精疲力竭。

一走出球场就呈大字形倒在地上，像鲤鱼似的嘴巴一开一合。探头观察我的，正是那个谋反的边缘人。

「哎呀，抱歉抱歉。手滑了一下。」

「你、你这家伙……绝不饶你……噗嘻。」

「真可惜。本来想说顺利的话又能去保健室。」

尽管很想宰了他，我已经没有那个体力了。

也罢。下克上乃世间常理，我要以宽大的心胸包容他。算他欠我一个人情。但我哭出来了，因为我是将军嘛。

数分钟后。我好不容易有力气坐起来，询问八幡：

「是说八幡，你之前说过。」

「什么啦。」

「人生和角色设定统一一下……你曾经对我这么说过，那是什么意思？」

「喔，那个啊。你不是继承足利义辉灵魂的剑豪将军吗？」

「正是。」

「但实际上是边缘又中二病的材木座义辉吧？」

被这家伙说边缘，会比平常火大三倍。跟红心大人对我说「给我减肥啦死秃子」一样火大。

「我只是觉得现实跟理想的自己，最好再磨合一下。没有深意，你别放在心上。」

「现实跟理想的自己……」

的确，我是举世无双的剑豪将军，却会因为区区排球和马拉松累得噗嘻噗嘻喘气。还会熬夜打恋爱游戏，喜欢女仆咖啡厅。

要是足利义辉公知道，搞不好也会哀叹。搞不好会跟被三好长庆逼得逃出京都时一样悔恨。

不过，那我该如何是好？

我是剑豪将军･材木座义辉——事到如今，可不能变更这个设定。不对，那不是设定。我真的是剑豪将军。

我以常在战场的精神为信条。既然如此，本来应该得将肉体锻炼得如钢铁般坚固。事实上却是这种肥胖体型……真怨恨怠惰的自己。不如说怨恨肉肉的自己。

之后我便陷入思考的迷宫<Labyrinth>，一语不发。

直到下课前，我都忘记要跟八幡交谈。回过神时，那家伙已经不见了。竟然如此忘我，失策失策。

其他学生还在旁边，但不知为何，全是陌生的面孔。

这时我发现了。他们是下一堂课的学生。

不只下课了，连下一堂课都即将开始。

「至少跟我说一声吧！那个冷血的家伙！」

我挤出所剩无几的体力，立刻撤退回校舍。

从比企谷八幡口中得到神秘的忠告后。

我沉思的时间愈来愈多。不知为何，那家伙说的话一直在脑中徘徊不去。

统一人生和角色设定。究竟是什么意思？

现实的我和剑豪将军相去甚远……我明白。再说，我从来没拿过日本刀。跟没握过球拍的桦地没两样。

当然也没和邪恶的敌人战斗过。只玩过游戏。跟只玩过马里○网球的桦地没两样。

我会一直这样甘于度过和平的日常吗？连我持有的十二神器都没用过，就这样从总武高中毕业？

思及此，一股难以形容的焦虑袭上心头。屁股好痒。

……在那之后的体育课，我也一直和八幡一组。

但我们的对话量大幅减少。只要我不主动搭话，就不会触发跟他的对话事件。瞧他毫不介意的模样，真是个没良心的边缘人。

「我身为剑豪将军，能在这个现实世界做到什么……？」

我在教室抱着胳膊，不断沉思。

应该有很多女学生被我忧郁的神情弄得小鹿乱撞，却没人跟我告白。她们似乎想等到毕业典礼那天。

我烦恼不已，再度迎来体育课的时间。

我理所当然似的跟八幡一组，按照惯例开始做伸展操。最近没什么跟他说话，随便闲聊几句吧。

「八幡，你知道『蓬莱轩』这家拉面店吗？这家店在新舄，清爽的汤头十分美味。」

「哦，之后去吃吃看好了。」

我开启话题，八幡便正常地回应。但他绝对不会邀我一起去。我也不是基于这个目的告诉他的。

总有一天，可能会有这样的未来，不过我们现在并非朋友。

为了让自己在体育课分组时不会剩下的互惠关系……我和八幡仅仅是这样的同伴。仅仅是相互勾结。

「八幡啊，现实……真无趣。」

我让他帮我压背，忍不住唉声叹气。

「啊？干么突然讲这个。」

「搞不好，现代没有剑豪将军的出场机会。得知我投胎转世，企图取我性命之人……至今仍未出现。」

「正常吧。」

「我所期望的校园生活不是这样。起初态度冷淡，随着相处时间的累积会慢慢用笨拙的方式跟我撒娇的美少女，究竟身在何处？」

「那种传说中的神兽不存在啦。」

「一开始好感度就很高的胸大少女，究竟身在何处？」

「那种有形文化财不存在啦。」

「那种让人怀疑『咦，你真的有那根吗？骗人的吧？』的可爱伪娘，究竟身在何处？」

「你在讲什么鬼话。」

比企谷八幡用看待黏在鞋底的口香糖的眼神瞥了我一眼。一副想叫我去死的样子，可惜那种唾骂对我无效。我已经有抵抗力了。

本想顺便跟他商量这几天的烦恼，最后还是决定作罢。

这家伙也说「没有深意」，应该给不了我答案吧。更重要的是，跟这男人讨教，有损剑豪将军的名誉。

吾乃孤高之人。一直是这样生活的。

虽说我俩同为边缘人，向他人寻求教诲这种没面子的行为，我可做不出来……我这么告诉自己。

「材木座，你这种妄想癖，明明大可用在更有用的地方。」

——八幡应该是出于无心的一句话，使我豁然开朗。

那无疑是大菩萨的启示。

「八幡啊……你说什么？」

「咦？喔，要去吃吃看那家拉面店？」

「不是那么久以前的话题！你刚才说什么！」

「喔，世上不存在会跟你撒娇的美少女？」

「不是，蠢货！刚刚说的那句！」

「喔，去死。」

「你才没说这句话！只是用那种眼神看我而已！」

算了。不问这个垃圾边缘人了。用不着确认，这家伙说的那句话深深烙印在我脑中。

「是吗……原来如此……！」

「咦？」

「原来如此，八幡！」

「什么东西？」

「就是这样，八幡！」

「听我说话！」

「如此！原来！」

「哪门子的倒装句！」

我无视八幡的吐槽，一口气站起来。接着放声大笑。有种脑内的迷雾瞬间散去的感觉。

「哈——哈哈哈！八幡啊！你说不定很适合解决他人烦恼的工作！」

「莫名其妙……」

「此刻，我找到了自己该踏上的道路！你那句话！那莫名现实的观点！喜欢GAGAGA文库的这一点！为我带来了一道光！」

我无视目瞪口呆的八幡，转身走向校舍。

不能继续坐以待毙。打铁趁热，必须立刻采取行动。

有了。找到了。我剑豪将军在现代征服天下的方法！统一现实及理想的手段！

「呵呵呵……可以想像众人臣服在我材木座义辉面前的模样。」

我踏着信心十足的步伐，意气风发地离开操场。

然而数秒后，我的领子就被体育老师一把揪住。公然企图跷课，让我挨了顿前所未有的痛骂。

该死的体育老师。竟敢让我剑豪将军流下男儿泪。

还下达「你今天跑马拉松」的死刑判决。

我望向八幡求救。他的回答是彷佛在叫我去死的视线。

自那天起，我就不再犹豫。

——材木座，人生和角色设定统一一下啦——

比企谷八幡之前对我说的那句话。面对那令我深感迷惘的精神攻击，我得出了明确的答案。

「早该这么做的。没错，我……该以成为轻小说家为目标。」

不是我自夸，我对妄想有自信。

上下学、下课时间、午餐时间……甚至连上课时间和睡前，都在埋头想像。没有做其他事。

即将到来的战斗，会是什么样的战斗？

敌人是谁？有何目的？

我在那场战斗中会如何活跃？

围绕在我身边争宠的美少女们，有什么样的类型？

幸运色狼事件要以什么样的形式发生？

于何时、何地、跟谁触发幸运色狼事件？

惨烈的战斗过后，有什么样的幸运色狼事件在等待我？

从比例上来看，幸运色狼的梦想太多了，但对于轻小说家这个职业而言，连那都是武器。不如说是必备技能。

「各式各样的大纲在我脑内完结……若将其化为实体，以此维生，不就与人生胜利组无异了吗？」

这正是让现实和理想的自己磨合。

既然是轻小说家，继续当剑豪将军也不奇怪。轻小说家这种职业，应该全是这类型的人。

……其实，我也不是从来没想过走上这条路。

小学时期，我的梦想是漫画家。可是用不着多少时间，我就察觉到自己的画技极限在哪里。

国中时期，我的梦想是小说家。但我从来没正式写过小说，只会一直想设定。一动笔就觉得麻烦，毫无干劲，懒得要命，才几页就放弃了。

仔细一想，是我觉悟不足。

真的「想创作故事」的认真度不足。

以前八幡说过，我逃避靠原创设定决胜负……或许真是如此。

我说不定只是在依赖史实。不，这也没办法。我身为剑豪将军也是没办法的事。

所以至少在轻小说中，我必须靠原创的想法决胜负。

否则足利义辉公也会生气吧。跟遭到松永久秀他们袭击的时候一样超级生气。

「来写吧。让人热血沸腾的壮阔异能战斗。美少女晃来晃去的胸部让人热血沸腾的轻小说！」

于是，我全心全意投入在写小说上面。抒发满溢而出的妄想。

舞台是现代，日本的某座地方都市。秘密组织及异能者们在那横行霸道。主人公觉醒隐藏的力量，勇敢地与他们对峙……基本设定就这样吧。

「好，可以。有点既视感大概是错觉。大概是因为这是王道路线。」

这一个礼拜，我大部分的时间都用在构思剧情上。没想过其他事。顶多只有得奖感言。

……我自己也很惊讶我的手从来没停过。

不仅如此，还愈写愈兴奋。这就是所谓的打开开关现象吗？难道我挺有才能的？是不是能得个芥川奖？

「开心……好开心！写小说这个行为，竟是如此有趣！」

能从写作中得到乐趣。这是作家最大的天赋吧。顺带一提，我查了一下，有趣是「饶有趣味」的意思。幸好有在出道前发现。

开始写作后，每天都非常充实。

体育课的时候，我把时间拿去构思。尽管于心不忍，我实在没空陪八幡。抱歉了，伙伴。

可是，八幡毫不介意，满不在乎的样子。事后我才知道，他刚好在那段时期被迫加入「侍奉社」这个社团。

……过没多久。

我终于把小说写完。有股难以言喻的成就感。

「太棒了……没想到处女作就写出了一部最高杰作。」

竟然写得出这种作品，我果然是天才吗？我是剑豪将军兼文豪将军吗？这部力作、自信作、超级巨作，就是优秀到这个地步。

我很想马上把它寄去投新人奖，却压抑住了急躁的心情。且慢。稍待片刻，巨擘材木座义辉。心急误事。

该先找人看过再说。

但不能放到网路上。那些家伙毫不留情。我当然有自信，不过我还是第一次拿自己的小说给人看。第一次最好是温柔的人。不要太粗暴。

「通常是找熟悉的朋友吧。」

问题在于，我没有朋友。想不到身为孤高独行侠的坏处，会反映在这种地方。

怎么办？干脆去找在站前给我卫生纸的前世的妻子？还是愿意为我祈福的前世的妻子……我为此烦恼了好几天。

「等等，材木座。那是小说的原稿吗？」

某天午休时间。我走在走廊上，想找个安静的地方重读自己的着作，有个人从后面叫住我。

是担任生活指导教师的平冢老师。我前世的第三个妻子。不对，这个人再怎么说都不可能。将军的骄傲不允许他成为家暴受害者。

「啊，那个，是啊……」

我吞吞吐吐地回答看见我手中原稿的平冢老师，跟家暴受害者一样吓得发抖。

「哦，原来你有这种兴趣。其实我学生时期也写过几篇小说。虽然是绝对不能给人看的东西。」

恐怕是超级虐待狂主角不断虐待弱者的故事。

不过，平冢老师看我的眼神意外温柔。还以为她肯定会骂我「有时间写小说不如给我念书！」捡回一条命了。

「那你给人看过吗？」

「没有，那个……」

结果，我一五一十地招了。听见我在找人帮我看小说，平冢老师不知为何点了下头。

「……好，我命令你去侍奉社。」

「侍奉社？」

「那里有跟你同症状的人。是二年F班的比企谷——」

没想到那正是我的伙伴所属的社团。

听平冢老师说，那是用来给学生咨询烦恼的地方。而且八幡也是成员之一，我都感觉到缘分了。

——非去不可。

他够格当第一个看我小说的人。因为为我指出这条道路的不是其他，正是那个男人。

仔细一想，也许我在内心某处期望着。也许我想看见那家伙感动得颤抖不已的表情。也许我想叫他今后要对我用敬语。

好，出征！时机到来！仅此而已！

放学后，我立刻来到位在特别大楼的侍奉社社办。

我好像太早来了，里面半个人都没有。没办法，先等一下吧。

既然是社团，代表成员不可能只有八幡一个。

说不定还会有女生。看到我的作品，她会不会不小心爱上我？哎呀呀，伤脑筋。不能等到两人独处的时候再跟我撒娇吗？

我边想边独自窃笑。

这时，社办的门忽然打开。走进来的果然是我熟悉的那位眼神死的伙伴。

下一刻，自窗户吹进的风吹散我的原稿。宛如从变魔术的魔术帽里飞出的数只白鸽。

「呵、呵、呵，会在这个地方见到你，真教人惊讶——我等你很久了，比企谷八幡！」

我在飞散的白纸中抱着胳膊，以符合剑豪将军身份的威风姿态大胆地笑着。

……来吧，比企谷八幡。大受震撼吧。

让你瞧瞧我笔下的世界，轻小说的地平线！

呵哈哈哈哈哈！咕啦——哈哈哈叭叭叭！

——于是，我征服了天下。

看完我的小说，侍奉社的人感动落泪，跟我要签名，纷纷称赞我是天才。毕业后，我站在轻小说家的顶点，有十部作品动画化——

「喂材木座，那什么东西？」

这时，突然有人从背后呼唤我，我因此停笔。

来者何人？比企谷八幡。吾之随从、爱刀、伙伴。

「别碍事，八幡。我正在为迟早会公开的自传整理回忆录。」

「别在侍奉社社办写那种东西。」

他边说边拿起我的原稿。大略看了一下后，对我投以看见脏东西的眼神。是想消毒的眼神。

「……捏造得真厉害。我遇见你的情况是这样的吗？」

「逸闻都会加油添醋。」

「再说，那篇小说明明被大家批得——」

「别说！再说下去会触犯禁忌！万万不可！」

「你因为大受打击而翻白眼——」

「闭口！将军不会回头！不会回首过去！」

「那就别写回忆录。」

吾名为材木座义辉。

举世无双的剑豪将军，立志成为轻小说家。

正在征朋友。

完

10注  指漫画《猎人》，最新一集的日文版于二○一八年十月九日发售。

11注   游戏《勇者斗恶龙》中的装备。

12注  源自印度的运动，类似老鹰抓小鸡，进攻方必须一直呐喊「卡巴迪」。

13注  咕噜为《魔戒》中的角色，哥摩拉、杰顿皆为《超人力霸王》中的怪兽。

14注  《草莓棉花糖》中的安娜･柯普拉因为被人用「穴骨洞」（音近「柯普拉」）称呼的关系，露出咬牙切齿的表情。

15注 漫画《网球王子》中的角色。

16注  「不退缩！不献媚！不回头！」为《北斗神拳》中圣帝沙乌刹的台词。

17注  《机动武斗传G钢弹》中东方不败的名台词。

18注  	《北斗神拳》中红心大人死前的惨叫声。

19注  改编自《北斗神拳》中拉奥的名台词「此生无悔」。

20注  两者皆为《勇者斗恶龙5》的女角。

21注 分别指《北斗神拳》的雷、《新世纪福音战士》的绫波零、《美少女战士》的火野丽、《机动战士钢弹》的阿姆罗･雷，四人名字读音皆相同。

22注  相扑力士，宣布引退时表示「体力达到了极限」。

23注  恋爱游戏《纯爱手札》的女主角。

** 比企谷八幡的教法比想像中还要直指核心。

作者：田中罗密欧／插画：户部淑

考试时期将近。

当然不是我，而是小町的。

……好吧，我的考试时期也逐渐逼近，但我只是高二生，现在又是十月，还不到着急的时候。补习班我也有去上，成绩维持得很好。完美无缺。但没人知道考试时会发生什么事。要说完全不担心是骗人的。

可是未来的我，高三的我一定会想办法解决……‼

因此，我每天都过得轻松惬意。至少现在是这样。未来的我，拜托啦麻烦您了。

不过，小町是国三生。当事人。急迫性的程度不同。

「…………」

小町正在庭院发呆。惊人的是，她带着一双死鱼眼。

我为之战栗。

死鱼眼不是我的专利吗？没想到是遗传。我们的祖先是鱼类？原来如此，难怪每次拍团体照我的眼睛都跟鱼一样肿肿的！谜团统统解开了！

……必须斩断这个恶性循环。

为此，我得避免小町留下子嗣。因为我们家只有小町可能有后代。

具体上来说，每当小町的男友候补出现，我都必定会对他采取高压面试法，逼得他得恋爱忧郁症。溺爱小町的老爸应该也会全方面提供协助。

可是，她到底在我们家狭小的庭院中，找到何种侘寂的景色可看？我产生疑惑，小町咕哝道：

「……蚂蚁。努力过着你们小小的蚁生吧……」

看来她在藉由观看渺小的蚂蚁，得到内心的安宁。

啊啊，累积了不少压力，你真像个考生。

哥哥也经常观察跟虫子一样的人类，以求内心的平静喔。我们这对兄妹真像。

小町难得散发出如此强烈的负面情绪。身为哥哥，我想为她做些什么。然而，考试是跟自我的战斗，我无能为力。顶多只能教她念书，但小町可以说是破洞的水桶。再怎么灌输知识，也会不断漏出来。讨厌，太笨了好可爱。对了，再来帮她写作业吧。

不不不等一下等一下。这样看起来是为她好，其实帮不了小町。太过度保护了。但没办法，谁叫小町太可爱。

「……好，该回去看书啰！」

小町将死鱼眼切换成香菇眼，站起来。可以顺便把嘴巴做成栗子形喔。可爱是正义。

不过明显看得出她在勉强自己。

「我说，要不要我教你一些念书方式？」

咻‼

小町对我随口说出的一句话，做出激烈的反应。

跟平野老师画的不正常的人侦测到同类时回头的情境一样。表情也差不多。不是吸血鬼，顶多是半鱼人的我，忍不住抖了一下。喂喂喂，你搞错作品类别啰……（注24）

「哥哥终于要把佐佐木补习班津田沼高中用的应试秘诀传授给小町了吗⁉」

「呃那是考大学用的。考高中用不到。」

「难过……」

小町用全身表现出失落。恶意卖萌。

「哥哥愿意教小町，小町是很高兴啦，不过这是吹了什么风？」

「喔，因为小町有点……那个（A）对吧？我觉得你用一般的方式念书会那个（B）。所以要教你的话，果然就是要教这个（C）吧。」

「……请分别回答ABC所指的内容。5×3分。」

竟然问这个吗？可恶，没办法……

「A笨，B无法理解，C笨蛋也懂的读书方式。」

「呜哇——！例句变得跟在骂人一样！」

「我也不想说得这么难听……」

这种人很常见。自己叫人讲实话，结果一听就震怒。

「……但哥哥说得没错。小町承认。小町书念不进去。小町是笨蛋！」

「也不用讲到这个地步……」

看来她精神挺疲惫的。

「所以，那个笨蛋也懂的方法是什么？」

「喔，没多厉害啦。你之前都是把看不懂的地方个别提出来不是吗？然后我也个别跟你说明，我想这个方式可能不太对。」

「所、所以是怎样？快说啊，哥哥！」

「喔、喔……」

她太激动了，有点恐怖。

「每种科目念书的方式都不一样吧？例如数学在彻底理解那一页的内容前，绝对不能翻到下一页。因为刚开始会教基础，再从那之中出应用题考你。」

「对呀。可是每堂课教的东西愈来愈多，光是把范围看过一遍就忙不过来，没时间重看基础部分。」

「就算这样，还是要从基础开始打稳。反过来说，世界史和国文这种科目，从会的地方看起也没问题。每种科目的诀窍不同。」

「哦哦哦哦哦。」

小町有点性急。而这一点造成了不好的影响，导致她没学会正确的念书方式。

「我现在虽然没在管数理科，考试时还挺努力的，今天我要把数理科的应试方式正式传授给你。」

「喔喔喔……」

小町的蘑菇眼发出光芒。已经超越蘑菇，而是松茸眼。

「既然是那么赞的方法，可以把小町的同学也叫来听吗？」

「咦？为什么？」

「现在班上因为考试期的关系，大家超级焦虑。大概是因为这样，在教室念书的时候紧张感会传达过来，没办法好好念书。所以实际考上总武高中的人的应试方式，应该满值得参考的。」

「你该不会叫我一起教他们吧？」

「不行吗？」

说实话，我不太想。老实说，只要有这么可爱的妹妹就好了。但最近我也会把认识的人叫到家里，不太好意思拒绝。

「好。虽然我不是当讲师的料，我试试看。」

「谢谢！那小町去叫人来。」

小町马上拿出手机，叫出类似联络网的东西开始传讯息。

……不愧是次世代型边缘人。小型又高性能。喜欢独处，但也能维持交友关系的感觉。这个大型哥哥太废了。比哥哥优秀的妹妹存在于此。

「哥哥，大约有十个人要来！」

「好多！那别在房间教，改到客厅吧……」

「啊，对了……这个要先跟你说。小町的同学，那个，全是派对咖。」

「你说……什么？」

我的灵压消失了。

「而且还是走嗨咖路线。」

我的灵压没有呼吸了。

「嗨咖路线的派对咖是人类恶的具现化吧。竟然跟那种人混在一起，我和爸爸不会同意喔。」

「哥哥，同学是不能选的啦。」

「那你干么主动邀他们来？」

「大家虽然是派对咖，人其实不坏呀……只不过对哥哥来说或许会有那么一点不自在……」

我开始嫌麻烦了。

尽管对小町不太好意思，打个招呼就闪人吧？

可是这么做会害她没面子。

驳回。

「……行啊。来就来。把那群派对咖叫来啊。」

「谢谢。真的感激不尽。」

小町合掌道谢，愧疚地低下头。

于是，下午决定召开紧急读书会。

「那小町来介绍一下！这是小町的同学！大家，这位是小町的哥哥。」

好随便的说明！根本称不上介绍……

「啊，我叫（每位同学的名字）……今天要麻烦您了……」

就这样，每个人都用固定句型做完自我介绍。

这些人也好随便。是没差啦，反正我不会记他们的名字。长相也不知道能不能记到晚上。

总之阵容是六男五女。再加上小町，我的学生共有十二人。喂喂喂跟补习班名师一样。

……不，我不可能当上名师。这些国中生统统在想「咦？这人看起来超难相处耶？」「他的眼神是罪犯的眼神耶？」「说起来，他感觉不像跟小町同学有血缘关系耶？」这种失礼的事（绝对）。

我给人的第一印象差不是一天两天的事，不过不愧是国中生，情绪表达得真明显。

「我有问题！哥哥大人现在是总武高中的学生对不对！」

看起来像班长的眼镜女孩飒爽地举手提问。

「嗯，总武高中二年级。代替自我介绍说一下，我的成绩（仅限国文这科）是全年级第三名。」

喔喔——众人的惊呼声重叠在一起。前一秒还对我抱持怀疑的眼神瞬间发光。这里是蘑菇田吗？

不愧是考生。会无条件崇拜成绩好的人。

话说回来，这些人是派对咖？嗨咖？

面带强烈的不安，驼背，肩膀下垂。还有很多人睡到翘起来的头发没整理好。分岔的头发也很明显，整体上显得狼狈不堪。阴暗。太阴暗了。

用国民动画（注25）的三年四班譬喻，就是藤木和野口。派对咖明明是大野或城崎那类型的人。究竟是怎么一回事？

小町说：

「……以前很有精神的大家被考试的压力压垮，现在变成这样了。」

这么严重啊。真正的嗨咖不就是要连考试的压力都能抵抗吗？

可是，这样的话我反而比较好教。

「嗨——！哥哥你好——！今天要拜托你咧——！念书太没劲了，我可不可以先来聊一下恋爱话题啊⁉」

「咦——！哥哥在学校是边缘人吗——！就算成绩好，边缘不就完了——！你知道不耀眼的人没人权吗？」

如果他们用这种态度跟我讲话，我的杀意会爆表。

「…………啊，你好……今天……了……」

「…………不好意思……这题……那个……我不会……」

这样给我的印象会非常好。不如说喜欢。我的标准应该跟正常人相反就是了。

若是现在的他们，我应该也能勉强维持正常心。

「各位，这可是伟大现役总武高中学生的应试秘诀继承仪式！要注意听喔！」

小町发号施令，这群国中生用有气无力的声音回答「……喔——」把手举高十公分左右。

呃，既然你们是派对咖，给我举高个三十公分吧。

我将所有人带到客厅，立刻召开读书会。

看这状况，必然是由我来教大家。人数这么多，不可能一下就教太难的。我稍微讲了一些考试时留意的地方，以及考上后觉得「幸好有这样做」的事。

我一面回想当时的情况，一面分享经验，不知不觉过了三十分钟。

「非常值得参考……」

「重写一份长期读书计划好了……」

「原来如此，还可以选择放掉不擅长的科目……」

总武高中是一所榜单挺亮眼的高中，但还称不上足以代表日本的超级名校。因此不用以完美为目标，只要念书的效率不错，要考过及格线并不难。

「那大家赶快听从哥哥大人的教诲，分头念书吧。」

眼镜女孩激励众人。

虽然不是很重要，可以不要叫我哥哥大人吗……这种叫法感觉挺瞧不起人的喔。

十二名国中生开始认真念书。

喀喀喀喀。

自动笔在笔记本上写字的声音，如果有好几人份重叠在一起，还挺有魄力的。这正是大考模式。

我当时也是这种感觉。

偶尔有人遇到瓶颈，会由懂的人帮忙指导。学习态度挺积极的。尽管我是临时讲师，已经在脑内化为遗产的数理系问题我可答不出来，所以我很感谢他们。

这几个人程度不错啊。

为何念得如此认真，还会紧张成那样？

理由很快就揭晓了。

「呼。」

我一下就看出，专心念书的人之中有一个人松懈下来了。

原来教师视角是这样啊。挺新鲜的。

那个男生从笔记本上抬起头，疲惫地扭动脖子。本以为他会继续念书，他却从桌子底下拿出手机，开始高速滑动。

……我犹豫了一下该不该制止他，可是自主学习的时候管得这么严也不太好，所以我没多说什么，想说之后他会自己复活。

结果他一直在滑手机。

咦？他在干么？打王⁉喂喂喂你可是考生啊得先打倒自己这个王再说吧？这家伙搞屁啊。

在我为之恐惧时，又多了一个。

「呼。」

第二个偷懒的出现了。

那人也一样扔掉自动笔，开始做伸展。然后偷偷摸摸从桌子底下拿出手机，开始高速下略。

学生以为没被发现，其实站在讲台上看得一清二楚。嗯——如果我是老师，这里是教室，绝对必须加以叮咛。放过他们是怠忽职守。但我没道理做到那个地步。

因此，虽然有股不祥的预感，我仍然保持沉默。

不久后，两人的怠惰慢慢朝周围扩散。

「嗯——」「呣。」「呼啊。」

逐渐感染其他人。注意力分散的症状透过空气感染。流行病。

整个客厅蔓延「呼」模式，还在拼命念书的只有两个人。

两个完全没在念书的。约八个人不至于在摸鱼，却因为缺乏集中力的关系进度停滞。整体的学习效率一口气降低。

好厉害。竟然能这么明显地看见怠惰在班上传播开来。

「哥哥，过来一下。」

小町把我叫到走廊。在这边讲话就不会被听见。

「才过三十分钟，大家都懒了。」

「您发现了吗，兄长。没错。一直都是这样。在教室自习的时候也是，起初大家都很认真，然后就愈来愈松懈。」

「结果比想像中还念不进去，他们又会着急，才会导致紧张的气氛弥漫教室。」

「对呀。本来以为在小町家跟现役高中生一起念书，会比较能维持紧张感……还是老样子。」

讨厌——小町抱头呻吟。

「我在旁边看也发现了，同一个空间内有人偷懒，会影响其他人。」

「就算要偷懒，如果休息一下会再继续念书，倒还没问题。」

「每个人之间有差异嘛。不过连三十分钟都撑不过，未免太快了。」

「对啊。怎么办？这样跟平常一样的说。」

可恶，那几个偷懒的家伙，竟敢害我妹难过。

「如果你不介意用我的做法，这部分我也可以一起指导他们……可是……」

小町的反应跟看见猎物的鳄鱼一样激动。

「真的吗⁉那就麻烦你了，哥哥大人！」

「别叫我哥哥大人。但我的指导法可能会有点严苛喔。」

「没关系！尽情发挥哥哥在侍奉社锻炼出来的问题解决技术吧！不然小町也可以帮点小忙！帮点小町忙！」

那个谜之可爱的忙是什么东西？你打算让世界染上小町色吗？住手，小町，染上小町色的只要有我一个就够了。

「……好吧。那我尽量试试看。看我让那几个天真的家伙见识一下自主学习的地狱。」

看我面带奸笑，小町一瞬间露出「没问题吗？」的不安神情。

「两位可以过来一下吗？」

「我、我吗⁉」

我拍拍在桌子底下玩手机的两人的肩膀。当然是降职意义上的拍肩膀。感到恐惧吧。

「到这边来。」

「你、你要把我们带去哪里⁉」「我们会被教训吗⁉」

「过来就对了。」

我把两个偷懒的人带到我房间。

「欢迎来到自我负责的教室。」

「哇，这个房间好多轻小说！」

「漫画也好多！而且都是狂热者喜欢的作品！看这些收藏，哥哥大人真的很内行！」

「你们非常优秀。所以我允许你们在环境更好的这个房间自习。就当成升级吧。」

听我这么说，两人瞬间露出笑容。

「真的假的！我平常都跟弟弟共用房间，超向往自己一间房的！」

「在这个房间念书，应该也会很有效率！」

「好好集中精神吧。你们一定做得到。我看得出来。身为总武高中学生的我看得出来。」

「哥哥大人！」「大人！我们会让你看见成果的！」

实际上是隔离。

箱子里有烂掉的橘子，会影响整箱的橘子。必须把烂橘子扔掉。拥有一对死鱼眼的我的房间，正适合当橘子房。

「那我就尊重你们的自主性，去盯着其他那些下级考生。这里的书和参考书可以自由使用。」

「非谢！」「不尽！」

那个连简称都称不上的答谢词是什么鬼。

「那个，哥哥。这个处分……该不会是？」

小町在楼梯下面等我。她似乎发现我做了什么。

「嗯，很遗憾，就是你想的那样。偷懒的考生被我排除了。」

「咦咦——那他们会怎么样？」

「小町，我无法平等救助所有人。我能做的只有避免有干劲的人受到影响。客厅的状况如何？」

「嗯、嗯。托哥哥的福，大家又像种子发芽一样打起精神了。」

「是吗？那就好。上面那两个回去前我会跟他们说，叫他们最好更有危机意识一点。」

「嗯，就这样吧。因为他们两个想考东大。」

不可能啦！从学习意志来看，已经看得出不可能了啦。哪个同学帮忙告诉他们现实啊。不讲明白反而很残酷喔。

十二个人里面，将两个不认真的人隔开，只留下认真的考生。这样就能维持住读书会的神圣性。

……理应如此。

「哥哥，又出状况了。」

我去了便利商店一趟，回家时，烦恼脸版本的小町前来迎接我，让我有种赚到的心情。我要把它保存在内心的截图资料夹，心里暖暖的。不，现在不是做这种事的时候。

「那两颗橘子该不会下楼了吧？」

「哥哥在心中是这样叫人家的呀……没有啦，你看了就知道。」

我从走廊透过门上的玻璃窗，观察客厅的情况。

「……喂喂，怎么又有人在偷懒。」

两个女生趁我和小町不在，光明正大滑着手机。一个人在玩通讯软件，另一个好像在玩游戏。为什么这些人都那么爱打王？现在还在用功能型手机的我完全无法理解。

跟刚才一样，她们俩的怠惰也传染给其他人了。

里面的人一个接一个拿出手机，读书会变成滑手机会。

「要降落在哪里？留前面观察一下情况再出发吗？」

「这次选渔村好了？」

其中还有人在打荒野行动。

这偷懒方式太夸张了吧！别给考生智慧型手机啊‼……呃，我认真的。大考时期如果有那种诱惑机，根本无法训练集中力。小孩子因快乐而堕落的速度，跟往低处流的水一样。

「怎、怎么办哥哥，这样下去大家会上不了东大的！」

「原来所有人都是以东大为目标啊！那还滑什么手机！那些家伙的危机意识未免太低了吧……？」

「在学校聊志愿的时候，大家因为受到气氛影响的关系，一半以上的人都变得想以东大为目标。」

「超像派对咖会干的事。」

本来因为他们太阴暗的关系，我还不敢相信，现在我瞬间接受了。

「那么，那两个在摸鱼的女生平常是怎样的人？」

「班上的开心果。」

「刚才那两个被隔离的男生呢？」

「班上的开心果。」

「你的班级只有开心果吗？」

那个班到底有多欢乐。我一定受不了。不过仔细一想，小町也能当开心果耶。只是不会自愿去做。

那类型的人，果然容易缺乏专注力吗？

「怎么办呢……」

「没办法。这次换成借你的房间行吗？」

「咦？该不会……」

「嗯，橘子就是要送进收容所。小町，把那两个人请到你房间。理由不用照实讲。说『你们很努力，所以升级成特别班』就行。」

「呜呜，好黑喔……好黑喔……」

小町咕哝着去找那两个带起偷懒风潮的女生。

这样留在客厅的七个人，应该就能恢复专注力。

「……呵，赢了。呼哈哈。」

好好见识比企谷补习班惊人的隐蔽力、彻底的隔离力吧！

「哥哥大人，我有问题想问！」

那个眼镜女孩叫住我。

「喔，好啊……哪一科？」

「数学！」

「嗯，数学啊……」

数学不仅不是我擅长的科目，还是不擅长的顶点。每次考试都只有一位数。

不过这样就好。我所有的力量都投资在擅长科目上。专精型角色。每种技能都东学一点西学一点，只会样样通样样松，无法对头目造成伤害。

意即我是攻略组。为了攻略人生的那一天，大胆地将点数全砸在特定素质上。

「所以，有人会数学吗？」

「什么叫『所以』？」

「我想说你看起来很聪明，提出来的问题等级应该也挺高的。」

「看起来很聪明……？」

眼镜女孩变得怪怪的。

她目光游移，脸泛红潮，呼吸紊乱。可疑到如果我这样走在大马路上，会立刻被警察抓去问话。

她在害羞？为何？

「不是我自夸。」她清了下嗓子。「小六的时候，我得过班上最认真读书的奖。」

「完全是在自夸。」

不过小学时期确实有那种名字长得莫名其妙的奖。换个名字换个方式，颁奖给全班的人，是现在的风潮。但拿到那种奖我也不会高兴，每个人价值观不尽相同。

「我确认一下。你不懂的是哪个部分？」

「二次方程式。」

「什么？」

咦，二次方程式是什么时候教的？

国二？还是国三？

不管怎样，那可是国中数学的重点。我记得有很长一段期间都在教这个。

现在几月？大考？咦？是不是不太对？

「二次方程式的哪里不懂？」

「整体上来说都不太明白。说起来，『二次』是指什么东西的二次，查了我还是看不懂。」

喂喂喂喂！这孩子没问题吗！

这不是现在该产生的疑惑吧⁉

「呃，因为那是二次式的方程式啊？」

「二次式这个词我知道，但也只是知道这个词而已，不太能理解……」

「x乘两次是二次项对吧？y则是一次项。这条方程式里面未知数的最高次数是二，就叫二次方程式。」

其实二次方程式的应用题我就不知道解不解得出来了，如果她继续追问，我没自信答得出来。

眼镜少女面色凝重。

「……什么意思？我不懂那个概念。」

竟然问意思啊。

「意思……我也不知道。根本想不到二次方程式实际上要用在哪里。」

「这、这样呀，大人也不知道吗？」

「你是那个啦，想不通就没办法跟机器一样解方程式的类型。」

「可能吧……」

「那放弃应用题吧。我不会害你，现在只要念基础就好。光这部分就能拿到不少分数。」

「……咦咦咦咦咦。」

她好像受到了打击。

「数学那么惨的话，其他科目必须非常努力。用擅长科目补足那部分的分数比较现实。跟我一样专攻文科吧。」

「……喔。」

好险。

她看起来很聪明，害我误会了，这孩子笨得可以跟小町拼。

亏她那么认真，凡事真的不能尽如人意啊。

「以剑桥大学为目标，从基础开始加油吧。」

这话不能当没听见，但我决定不管。

……太恐怖了。这里是魔窟吗？

我上楼观察二楼（隔离）组的情况。

先来到我的房间偷看。

「Fu！Fu！Fu！」

「这部漫画超好看的——！」

如我所料，他们整个玩疯了。

明明我带他们来这边还过没多久，桌上已经堆满轻小说及漫画，笔记和课本被晾在一旁。

那两个男生不知为何上半身全裸，用手机播放疑似跳舞影片的东西，双手拿着漫画和轻小说狂舞。

我说，你们这样看得清楚字喔？文字会晃动，内容看不进去吧。

……看来他们因为考试压力的关系，精神崩溃了。

这两个人没救了。幸好有隔离开来。

接着是小町的房间。

这边总不会也把衣服脱了吧。要是我撞见那种场面，这一集就结束了。看见女生脱衣服还能得到原谅，是出包的男主角的特权（注26）。

我提高警戒，正准备确认里面的情况。

「不能偷窥喔——」

小町潜行到我背后，吓得我差点跳起来。

「……你、你！害我差点大叫！」

不愧是我妹。边缘人技能也没忘记学。

「你鬼鬼祟祟的在做什么？」

「我在检查那几颗橘子的状况。」

「直接进去不就行了？」

小町门都没敲（那是她自己的房间，当然有权不敲门）就打开房门。

「你们在念书吗？」

「啊，小町。没耶，现在在休息。」

「你也在这边休息一下如何？」

幸好她们没脱衣服。不过，她们正在边看手机边吃巧克力。

「真是——这可是读书会耶，不趁现在弄懂一个人念书搞不懂的问题，之后就糟了喔？」

「嗯，会啦会啦。再休息一下就去念书。」

「这款零食很好吃喔。新出的！」

八幡知道。这是最后并不会念书的模式。

「要适可而止喔。小町等等再来。」

我们走出小町的房间。

「……总觉得没有读书会的味道了。感觉像一堆人来我们家，各自找地方玩。」

「对不起，哥哥，演变成这么奇怪的情况。」

「不，不是演变成奇怪的情况，是你们本来就很奇怪。」

「大家都是乖孩子！虽然变成得了考前忧郁症的派对咖，他们人都很好！我对他们的第一印象不怎么样，不过相处过后，大家都挺友善的，是跟花轮一样的稀有人才。」

「……的确，刚开始会觉得花轮是个讨厌的做作男。」

大部分是小夫害的。

「走吧，顾好剩下七个就达成任务了。加上你共八个人。」

这个结果离「达成任务」有点出入。尽管如此，我已经很努力了。

我有工作狂属性耶。明明这么讨厌工作，要是我成为上班族，可能会变成社畜，好可怕。

我回到客厅。

包含小町在内，总共八个人。他们是从严格的筛选制度下存活下来，以东大这扇窄门为目标的菁英。嗯，不可能。在书桌前面连三小时都坐不住，情况不妙。一个弄不好可是会走错路，跌到最底层的。

至少想让活下来的这些人考上第二志愿。我如此心想，静下心专心当个指导者。

数理科我没什么把握，但除此之外的科目丝毫难不倒我。

喀哩喀哩，喀喀哩喀哩。

八人发出跟搞笑艺人组合一样的写字声（注27），贪婪地吸收知识。他们挺专注的。是隔离了橘子四人组带来的结果。

过了一小时左右，他们依然没有分心或聊天，专注于念书上。之前他们过没多久就会偷懒，因此感觉起来努力了很长一段时间。

我的佛心也萌芽了。

「大家会不会渴？要不要喝点什么？」

「啊，经你这么一说，喉咙好干喔……」「如果有甜甜的饮料可以喝就好了……」「对啊，想喝甜的。」「大脑干涸……」「麻烦哥哥大人了。」

「OKOK。我可以回应你们的期待。」

甜甜的饮料？

既然你们提出这个要求，答案只有一个。

仅此一个的明晰答案，是我早就料到会发生这种事……不对，我是边缘人，所以完全没料到会发生这种事……是我自己买了一整箱的饮料。

「啊，好甜……这是什么？」「咦，咖啡？咖啡牛奶？」「呜，好、好像有点太甜……」

没错，是MAX咖啡。

来我家想喝甜饮料的话，我会拿它出来可谓自然的哲理，跟苹果从树上掉下来一样。

苹果还会掉在儿子的头上，上面刺着一支箭（注28）。

「喝习惯就会上瘾，也很适合拿来补充糖分。而且总武高中的人大家都在喝喔。」

「这、这样啊！真是有意义的情报……」「那努力喝下去吧……」「这样一想，总觉得变好喝了。」「会想再喝耶。」

呵，又不小心跟人传教了。

但愿我一步一脚印的贡献，能带来厂商送我MAX咖啡一年份的美妙奇迹。

「好了——大家，补充完糖分，一口气提升10个偏差值吧！」

小町一声令下，七个人「喔——！」将拳头举高二十公分。派对咖度比刚来的时候恢复了一些喔。念书念得顺利，精神果然也会比较稳定。

考生们再度开始振笔疾书。

一切顺利。我的侍奉力似乎也提升了不少。

然而，事情没有那么简单。

「呼。」

叹了口气，堕落到去滑手机的人，竟然是以剑桥大学为目标的眼镜女孩！唔咦咦咦咦咦咦⁉刚才认真向学的态度跑哪去了……

记得这家伙不是在班上得过最有班长气质的奖吗？好像不是这个奖，应该差不多。为什么感觉会站在认真界顶点的人，才念一下书就不行了！

「呼。」

还有小町。

等等等等，等一下等一下等一下。

喂喂小町同学，这究竟是吹什么风？

「喂喂小町同学，这究竟是吹什么风？」

能将内心所想直接说出来，正是家人的好处。我将小町叫到走廊上，毫不保留地说出真心话。

「……呜呜，左边好像传来懒洋洋的波动……小町没有抵抗，注意力就中断了。好神奇！」

「那就是懒惰波动的可怕之处。被它的巨浪吞噬就别想考试了。」

「真丢脸……」

「是说为什么你班上的人固定有一定数量的人在偷懒？那才神奇吧。」

「唔唔，不知道，从很久以前就是这样。」

是小町的同学共通的特性吗？再怎么排除烂掉的考生，又会有其他人偷懒。这样隔离就没意义了。

「为什么会发生这种事？」

「可能是因为大家是派对咖，容易被当下的气氛影响。」

「呣——」

这道理说不通，但一直逼问小町也没用，所以我没讲出来。

如果是会被气氛影响的班级，大家都在专心念书的时候，不会有人偷懒吧。既然重视气氛，就算不想也会去念书吧。

事已至此，我甚至怀疑他们是不是出于本能在偷懒。

本能……这时，我恍然大悟。

「啊，我知道了。蚂蚁。」

「咦？」

「你们是蚂蚁！」

小町的眼睛睁得跟盘子一样大。一下是鱼一下是蘑菇一下是松茸一下是盘子，她真忙。

我立刻着手重编读书会的队伍。

将共十二名蚂蚁考生分成三组四人队伍。A组在我房间，B组在小町房间，C组在客厅。

「分好了，这有什么意义？」

「要解释的话，必须说明一下工蚁的法则。」

「蚂、蚂蚁？」

「蚂蚁跟人类一样，是会建立社会的生物。可是不是所有蚂蚁都会认真工作。也有偷懒的蚂蚁。」

「我还以为偷懒的是蟋蟀。」

「嗯，蟋蟀被那则寓言害惨了。不过啊小町，实际上的蟋蟀完全不会偷懒喔。它可是戒心强，努力活在每一个瞬间的虫。」

「……喔喔。哥哥对昆虫挺瞭解的嘛。」

「我有一本不错的昆虫图鉴还满贵的这不重要！现在在讲蚂蚁。你听好，据说在蚂蚁社会，只有两成的蚂蚁会拿出全力工作。」

「两成……」

「那两成就是蚁界的社畜。由它们拼命努力，解决大部分的工作。」

「剩下的蚂蚁在做什么？」

「剩下的蚂蚁里面，六成是凡人蚂蚁。也是会工作，不过比起工作，更重视私人时间，是会准时下班的类型。只会把最基本的工作做好。」

「喔喔，是散发出『别找我说话』的气息的人……」

万一我未来要去公司上班，我也打算当那样的人。

「认真的占两成，缺乏生产性的占六成，而最后那两成……完全不会工作。任何蚂蚁集团都看得出这个倾向，所以叫工蚁法则。」

「蚂蚁的世界也有尼特族问题呀。」

「不，这两成偷懒组，紧要关头时会死命工作。从生物学的角度来看，似乎是一种保险。如果所有人同时工作，生产性是会暂时提高没错，但他们会同时耗尽精力，社会反而会变弱。那两成偷懒组就是用来为了防止这种事发生的。」

「……噢——好周到的机制。」

知道这件事的时候，我不禁深受感动。

边缘生活在社会上也有其正当性！太棒了，我做到了！……这种感觉。冷静一想，紧要关头会被操得比其他人更厉害，根本划不来，不如说平常很轻松，忙碌期就是地狱，实在称不上过得好。

然而，所有人为了一个目标猛烈工作的时候，我可不想扯上关系。我讨厌人人为我，我为人人的气氛。

所有人被一个人扯后腿，一个人被所有人扯后腿……这样倒是挺符合我所知道的现实，非常能认同。

不管怎样，假如遇到那种情况，平冢老师应该会指名我，将不合理的要求塞过来。

当然是强制侍奉！黑心社团！而隶属于那个社团的我是社畜，得不到救赎。

「欸欸，如果召集那两成优秀的蚂蚁，不是会变得很壮观吗？全是能干的蚂蚁耶。大胜利。」

小町说的是经常有人提出的意见。

可惜现实没有那么简单。

「那个情况下，仍然会分成两成、六成、两成的比例。也就是说即使全是菁英蚁，其中的两成还是会自动偷懒。」

「什么！」

「集团心理就是这样吧。」

「……人类真糟糕。」

「嗯，有史以来人类没有不糟糕过的。翻开世界史课本就知道。几乎每一页都会见血。」

「那大家一起考上东大是不可能的啰……」

「因为你的班级不是后段班辣妹，而是后段班啊。」（注29）

连身为全班智慧象征的班长（虽然不知道她是不是班长）都那副德行。

「只不过，既然工蚁法则在你班上发动，代表不是个人的问题。那也不是没办法解决。」

「所以才把大家分组吗？」

「没错。然后啊，我等等要去每一组巡视，做某件事。今天大家要念到几点？」

「小町跟他们说六点，还有四小时左右。」

「四小时啊。OK。看好我的计划会不会发挥效果吧。顺利的话，说不定连在学校都能派上用场。」

「嗯、嗯。那为了避免吓到大家，小町先去跟大家说哥哥要在各个房间晃来晃去？」

「不必，让他们害怕比较好，不用跟他们说。」

「……咦咦，哥哥要做什么？」

那么，这场实验是否会顺利呢。

每组分成男女各两个人。

首先来到我房间。A组在这里念书……并没有。

「Fu！Fu！Fu！」

「Hi！Hi！Hi！Hi！」

漫画跟轻小说，零食跟手机。以及不用担心父母在盯着自己的房间。

此处正是国中生应该会向往的堕落环境。

所以这个唱唱跳跳的极乐世界也是无可奈何……怎么可能啊！

「大家好——伟大的讲师来了喔——」

我门都没敲，杀进房间，四人瞬间藏起手机正坐。

然而，他们没时间藏漫画和轻小说，无法掩饰偷懒的痕迹。

「啊——没关系没关系。别介意。我也要写功课，大家别管我。」

「那、那个……你不生气吗？」

其中一名男生提心吊胆地问。

「你们是在自主学习，我没道理生气啊。而且对考生来说休息也很重要。按照自己的步调念吧。」

我坐到书桌前面，然后真的开始写功课。

蚂蚁考生们露出松一口气的表情，不过我在认真写功课，他们不敢继续玩乐的样子。有个人提议「那，差不多该继续念书了」，那些家伙便慢慢打开课本及笔记。

不是继续念书，是开始念书吧。我将吐槽留在心中。接着在内心告诉他们。

……现在开始，你们将成为受刑人，而不是考生。在三座监狱里被迫遵循法则念书，与自身的意志无关。

过了约十分钟。

包含我在内的五个人，都还在专心动笔。

不过，我的斜眼雷达侦测到有个女生开始扭来扭去。注意力分散了。是时候了。好，动手。

「……呼啊～！」

我故意打了个大哈欠。

四个人同时吓到，挺有趣的。

「啊啊～累死我了，写不下去啦～休息一下！」

我用力躺到床上。

四人睁大眼睛，凝视形迹可疑的我。

「啊——抱歉，可以把那本漫画拿给我吗？」

我随便指向一本漫画。

「给、给你……」

少女将漫画递给我。

「那个零食看起来很好吃耶。可不可以分我一点？」

我未经许可，擅自将人家的零食扔进口中。

看见我跟他们一点都不熟，还敢做出各种暴行，四位国中生连眨眼都忘了，愣在那边。

「啊——好累！真的好累。谁想念书啊。对不对？」

我向碰巧跟我四目相交的少女征求同意。

「不、不不不……书还是要念……」

她不停摇头。

我露出奸笑，尽量让眼神显得颓废。

少女用「这个废人是怎样……」的目光看着我。就是要这样，傻眼吧。把高一个等级的我的废人样烙印在眼中吧。这样这个房间的懒蚁宝座就是我的了。

那四个人大概是不太想跟我有交流，面面相觑，逃去专心读书。这也叫逃避现实吗？

蚂蚁跟人类都以二、六、二的比例分成菁英、平凡、废物。所以只要分成四人一间房，我一个人故意耍废，废物的位置就会被我占走。

问题也解决了，还能偷懒。可谓一石二鸟的奇策。

我尽情耍废了一段时间，承受足够的轻蔑。

接下来换小町房间的B组。

「抱歉小町，突然跑来打扰，我要在这里写作业。」

小町和眼镜少女都安排在这间房间。

「嗯、嗯。哥哥，当然可以呀。哥哥突然跑到妹妹的房间写作业，是非常自然的行为。用小町的书桌吧。」

我们事先商量过，却没准备剧本，导致小町的语气超级僵硬。明显有鬼，但我决定硬着头皮上。

「嗯，借一下。大家不好意思啊。别理我，念你们的就好。」

小町以外的三个人，因为事发突然而瞪大眼睛。

我跟刚才一样，开始写作业。等了十分钟。尽管B组还没有松懈的迹象，我依然启动了耍废模式。

「啊——好累——真的好累——没干劲啦——」

我扑到小町床上。

「唉——哥哥真的好废。」

「小町，拿你房间最好看的漫画给我看。」

「别看漫画了，去写作业啦。」

「没关系啦，作业随便写就好。我要看漫画！」

我随便从书架里抽出一本书。

那不是漫画，而是某本入门书。

《每个人都能靠一日五分钟的训练学会！ 蘑菇眼的做法》

你、你在看这种书啊？原来那是人工的光芒。有这种东西，女孩子的可爱记号我一个都不信了……我在内心感到恐惧，但把它放回去又有点那个，便悠悠哉哉地看起来。

……挺有趣的。感觉我也做得到。是吗，重点在于泪腺的用法……原来。噢，不行不行，得记得散发松懈的气息才行。

我边看边从全身释放懒人气息。到我这个等级，就能自在操控懒气。「懒气」这个词念起来挺可爱的，语意当然一点都不可爱。用拟声词来表达就是油腻腻、黏答答、乱糟糟。

「唔……？」「这、这是……？」「这股气是什么……？」

不愧是容易受到影响的人。挺会读空气的。他们应该明白我是这间房间最废的男人了。

哎呀，这个计划真有效。太有效了，害我笑得停不下来。这种态度使我显得更加诡异，B组的两位男生吓得脸色苍白。

我对他们两个说：

「没考上高中会更惨喔。毕竟会沦落得比我更废。」

「啊哇哇。」

他们瑟瑟发抖，拿我当反面教材，重新认真开始念书。

最后是C组。都第三次了，我也习惯了。

在这边我也完美地耍了废。耍废技术提升，从进入房间到耍废，只需要短短五分钟。而且一点都不会不自然，我肯定有耍废的才能。

C组一面留意着我这个脱队者的存在，一面拼命点燃念书动力，避免变得跟我一样。

可喜可贺可喜可贺。

但这些家伙的忍耐力持续不久。光巡一遍无法统统解决。

「嗨，各位考生，又要麻烦你们啦。」

「又、又来了吗——⁉」

突袭A组。你们该战斗的敌人不在手机里面，在这里。我就是你们要打的王！

接着便是重复这个过程直到六点。

「小町同学，今天谢谢你。总觉得比平常还要能集中精神。」

「……不、不会。没什么好谢的。有提升大家的读书效率就好。」

「超有效率的。这样应该能考上第一志愿。」

眼镜女孩一鞠躬，其他人慢了半拍，也跟着僵硬地低下头。

「谢谢比企谷学长！托你的福感觉考得上东大啦！」「比企谷学长，真的谢哩！」「……也谢谢哥哥大人。」「……那个，嗯，谢啰。」

喂喂喂你们对比企谷兄妹的道谢明显有温度差喔。真心话再掩饰一下啦。

算了，他们应该把我当成非常识讲师而不是临时讲师（注30），这反应很正常。

「你们几个，以后读书会人数要压在四个人以下喔。」

「咦？为什么是四个人？」「……谁知道？」

那群国中生疑惑地踏上归途。

「这样委托就达成了。」

「嗯——是没错，可是没关系吗？大家都把哥哥当成怪人了。」

「无所谓，反正应该不会再见面了。而且我觉得只有这么做才能让他们集中精神。」

「是啦。哥哥帮小町解决问题，嗯，小町很感谢。不过被班上的人误会，有点可惜的说——」

「事情本来就很难做到完美。再说你可是伟大的妹妹喔？这种时候就乖乖感谢哥哥吧。光这样就差满多的。」

「差满多……什么东西差满多？」

我没回答。因为讲出来有点不识趣。

不过真的有差。跟我在侍奉社做的事真的有差。我完全不觉得自己有为此牺牲。对那些国中生的印象也不差。反而心生同情。因为他们绝对考不上第一志愿……

为什么会有差呢？

一定，大概是因为，小町对我而言是如假包换的家人。

这种话的确说不出口。事关哥哥的面子。

然而，小町似乎察觉到了。

「谢谢哥哥。」

「……嗯。」

看，果然只要有这句话就足够。

「感谢归感谢……但在小町这边并没有加分喔。」

「……别在最后玩梗啊。」

小町露出天真烂漫的笑容。

完

24注  指漫画家平野耕太的作品《厄夜怪客》。

25注   指《樱桃小丸子》。

26注   指漫画《出包王女》。

** 平冢静和比企谷八幡某天假日的度过方式。

作者：天津向／插画：うかみ

我，比企谷八幡醒来的时候，已经过了下午一点半。

我思考着自己为何会睡到这种时间。

对喔。昨天我用手机随便载了款小游戏玩，结果比想像中还沉迷，想着「明天放假，干脆能玩多久就玩多久好了」，结果不小心玩到天亮。话说回来，难得的假日睡到下午才起床时的倦怠感真惊人。浪费掉一整天的感觉苛责着我。

……然而，我很快就转念一想，这种事只是家常便饭。不如说上礼拜我傍晚才起床，浪费掉一整天。考虑到这一点，我今天反而算起得早耶。太棒了。意思是我会捡到三文钱啰（注31）。睡这么久还能捡到三文钱，真是太棒了。

对喔，三文钱换算成现在的钱是多少？我用手机搜寻「三文 现在的价值」。我看看……嗯嗯，每个时代各不相同，差不多一百日圆左右……不错啊。意思是我免费赚到一百块啰？很幸运嘛。问题是那一百块钱现在在哪里。

想着想着，我肚子叫了。好，去找一百日圆前，先填饱肚子吧。我走向客厅。

「喂——小町。有早餐吃吗——？」

我边想「现在好像不是吃早餐的时间」边呼唤小町，客厅却半个人都没有。嗯？平常会懒洋洋地看电视的小町跑哪去了？这时我想起昨天小町在客厅说过的话。

『明天小町要跟学校的朋友出去玩，哥哥要自己吃喔！反正哥哥一定会熬夜到天亮，睡到下午才起床，还觉得自己没睡到晚上真是赚到了。』

哇——这家伙有超能力吗？还是说我变得跟只会按照固定模式行动的bot一样了？两种可能性都好讨厌喔。

我想着「不知道哪个比较讨厌」，但比起那种小事，现在要先解决我肚子饿的问题。怎么办呢？嗯——我打开冰箱，没有能直接吃的东西。我又不想在只有一个人的时候开伙。小町说「我想吃这个——！」的话，我是会想煮给她啦……

那么，我该如何是好？在我烦恼之时，发现餐桌上有张纸条，便将它拿起来。

『留言！反正哥哥八成会觉得「自己煮好麻烦，小町在的话我倒是可以煮给她吃啦」，小町把妈妈给的餐费放在这里！不要乱花喔！』

原来如此。看来可以确定我不是bot，而是小町有超能力。这样她可以说是超能力者小町了，去当模特儿给爸爸画都不奇怪的等级。（注32）

我边想边抽走放在纸条旁边的千元钞票。嗯，如果能把午餐的消费压在九百块以内，真的能赚到三文钱。

于是，我换好衣服踏出家门。烦恼了一下要去哪吃饭，最后决定去站前新开的拉面店。吃我家附近的定食店也不是不行，不过我想度过「假日开拓了一家新店耶」这种有现充感的一天。顺带一提，这句话我没打算跟别人说。

好啦，不只这个念头，我要再说一遍，千叶是拉面的激战区。意即将拉面店开在千叶，等于是选择踏上有一堆好吃店家的「修罗之道」。我必须去尝尝那份觉悟的滋味。顺带一提，这也不是因为有人跟我说过。

走到车站差不多要十分钟吧。我悠哉地走向车站。

红灯亮起时，我拿出手机玩昨天载的游戏。嗯——到底哪里好玩啊？不停用菜刀切飞出来的蔬菜的游戏。是深夜时段太亢奋了吗？喔，掉下来的萝卜、红萝卜那些蔬菜还算好切，嗯，等一下，这是莴苣，还有四季豆？四季豆太小，不好切，所以要仔细瞄准……看招——！

……没砍中。游戏结束。好，我可不能这样就放弃。我准备按下继续游戏的按钮。

这时。

「喂，少年。你在这种地方干么？」

我抬起头，熟悉的面孔戴着墨镜，坐在停在路边的车子里，从车窗对我挥手。

那个人是平冢静。我高中的国文老师，兼任生活指导老师，是把我塞进侍奉社的罪魁祸首。

「早就绿灯啰。」

往上方一看，绿灯已经开始闪烁，在我心想「啊」的瞬间转为红灯。

「平冢老师，您问我在做什么，答案是切蔬菜。」

「这句话由你说出口，听起来像奇怪的妄想……」

「那您又在做什么？」

「喔，我要去吃拉面。」

「咦？」

我惊呼出声，平冢老师愣了下。

「怎么了？我看起来不像不会吃拉面的人吧。」

「没有，我也正想去吃拉面，觉得很巧而已。」

「你也是？这样啊……好。」

平冢老师拿下墨镜，竖起大拇指指向车内。

「先上车。」

「咦？」

「我们的目的都是吃拉面。在这边遇到也是有缘，一起去吧。」

「咦？可、可是。」

我想了许多，判断八成会惹事上身，打算拒绝这个邀约。对喔，我想到她还出了国文作业。珍贵的假日要被老师念东念西，我可受不了。

「哎呀——我觉得学生和老师走在一起不太好，这次还是算了吧。」

「我请客。」

「我不客气了。」

与其被她继续纠缠，我选择了口袋里的一千元，也就是三十文。

这辆车大概是没打算用来载人，后座放着纸箱，完全不像女性的车子。

「光看这辆车，就看得出老师没有跟男性交往的经验。」

「比企谷，算你有种讲出这句话。小心我把你在校内的评价到处跟人说喔。」

这人怎么有办法用如此平静的语气，讲出这么不讲理的话。这根本是职权骚扰吧。

「所以，你本来打算去哪家店？」

「啊，站前那家新店。」

「啊——那家啊。原来如此。原来如此。原来如此。」

平冢老师说了好几遍。

「怎么了吗？」

「比企谷，你搞不好被拉面之神爱着。」

「咦？拉面之神？」

我纳闷地看着正在开车的老师。

「嗯。你在那边遇到我，就是这么一回事吧。」

说完这句话，平冢老师忽然打方向盘在前面的十字路口掉头，开往我要去的拉面店。

「那个，老师，刚才那句话的意思是？」

「等到了再说。」

我一头雾水，直盯着前方。

开了五分钟左右，我们抵达站前。平冢老师坐在车上，把车停在看得见店家的位置。

「中午的营业时间快结束了。看得见吗？」

我望向预计要去的那家店。招牌上印着大大一张店长跟疑似拉面师傅的人的合照。

「招牌真壮观。」

「是没错，但我要你看的是那个。有没有看见？」

平冢老师边说边打开我坐的副驾驶座的窗户，解开安全带，探出上半身往车外看过去。呃，您有点靠太近。胸部就在我的脸前面，这么近即使是我也会心跳加速。

「你看。」

我不知道她叫我看哪里，脸颊有点发烫，马上意识到她指的是拉面店，望向那边。招牌上的店长本人在站着抽烟。

「虽说已经过了午餐的尖峰时段，这里可是站前。店长却在外面。」

「……意思是，没有客人吗？」

「嗯，或者是——」

平冢老师开口的瞬间，店里走出一名客人。店长并未特别跟那位客人点头致意，只是默默抽着烟滑手机。

「让其他人负责煮拉面。看来是后者。」

「不过，也有可能是煮完面了才到外面来。」

「可是不会想看客人吃完的反应的拉面店店长，不可能是一流的。他对刚刚离开的客人就连声招呼都没打啊。」

平冢老师说得没错。自己煮的东西——例如小町点的菜，我也绝对会想看小町吃的时候是什么反应，甚至连吃完的反应都想看。

「看他把自己跟师傅的照片印在招牌上，是在借别人的兜裆布熬拉面汤头吧。」（注33）

不是相扑而是熬汤，这人改编得真好。在我心想之时，平冢老师坐回驾驶座上，吐出一口气。表情看起来有点悲伤。

「虽然我不太想相信给店家打分数的软件，这家店在那个软件上的分数也全是低分。上面写着『味道普通，不过店长那傲慢的态度让面吃起来都变难吃了』之类的评价。」

「这样啊。」

没想到平冢老师这么热爱拉面。

不对，之前跟她一起去吃拉面的时候就有感觉，现在重新体会到了。

「也就是说，我不想带你来这家店。你觉得呢？」

「您问我意见……听您这么说，我的确变得不太想去了。」

「对吧对吧。」

平冢老师高兴地点头，可是看到老师这样，我有点想逗她一下。

「只不过，我对您有点幻灭。」

「幻灭？」

平冢老师挑眉瞪过来。

「您的心情、心得，如实传达给我了。但我觉得您身为国文老师，只靠资料及网路上的评价为一间店打分数，不太符合您的作风。」

平冢老师闻言，不再瞪我，而是望向挡风玻璃前面。

「将透过自身经验得到的感想转化成言语，才像国文老师吗？」

「至少我认为您有这样的一面。」

「你这个人真的是……百闻不如一食，那你看看这个。」

平冢老师从挂在肩上的包包中拿出钱包，抽出一张卡片。

上面写着眼前这家拉面店的店名，是盖了两个章的集点卡。

「咦？这是。」

「我有那家店的集点卡，自然只有一个意思。」

「老师，您去过那家店吗？」

「我以为拿资料跟你说明会更有说服力，才用那种形式介绍那家店，如果讲明白一点比较好，我就直说了。」

平冢老师将脸凑近。

「那家店很难吃。」

「……瞭解。」

「好，那我开车啰。」

车子倒退了一段距离，平冢老师转动方向盘，继续向前开。

最后决定直接开往平冢老师今天想吃的店家。

「老师真的很喜欢吃拉面。」

「之前也有过这样子的对话。」

没错。记得当时是……

「在您表妹的结婚典礼上。」

「喔，对对对。记得是家人在婚礼会场疯狂对我施压，我想逃跑时遇见你。是吗……都过这么久了。」

平冢老师忽然望向远方。这眼神是怎样？什么样的情绪？

「之后我表妹很快就怀孕了，前阵子还怀了第二胎。」

「这样啊。恭喜。」

听见我的回应，平冢老师目光变得更加惆怅。

「前阵子我去参加亲戚的法事时，那些亲戚也东一句『小孩子好可爱』，西一句『小静不结婚吗』。」

呃啊……虽然我没遇过这种事，她八成觉得如坐针毡吧。等我毕业变成尼特族的话，也要注意绝对不能去亲戚的聚会。但我本来就几乎不会去参加聚会。

「自从那一天起，我的父母就会用LINE拼命传表妹的小孩的照片给我看，大概是跟她交换了联络方式。一句话都没说。」

「一句话都没说？」

那就是最大的暗示……我如此心想，却没说出口。

「我能做的最大抵抗，就是对那些照片已读不回。」

平冢老师。你看着远方绝对很危险，先不要吧。我看你都有可能看不见眼前的车了。

我设法改变话题。

「对了！没想到当时的约定会以这种形式实现。」

「约定？……喔，去吃我推荐的拉面店吗？我记得。不过这次不算啦，这次比较接近衍生作。」

「是吗？」

「是啊。等你毕业想带你去吃的拉面计划，制定得差不多了。像今天这种突发状况也算的话，我的计划就白费了。」

计划？这么夸张啊？平冢老师对拉面确实热爱到随口问一句，她会给予十倍——不，百倍的回应。

「因为我已经把店家候补删到剩下四十家。」

「删过了还有四十家？很多耶！」

「说什么傻话。根据资料显示，二○一八年千叶县有一千两百九十八家拉面店。我可是从中挑出了四十家。」

「呃，不过——」

「好了好了。总之敬请期待毕业后。」

平冢老师笑得这么开心，使我感到恐惧。老师长这么漂亮却没男人缘的原因，线索说不定就藏在这里。

「但我刚刚也说过，今天算是偶遇的外传。我也只是去自己想去的店家而已，不用那么紧张。」

「这样啊。那好。」

我松了口气，望向窗外的风景。

「到了，就是那家。」

平冢老师将车子停在停车场，走没多久就看见一家拉面店。

「咦……老师，那家店是——」

「没错。那家名店。」

我对那家店的第一印象是红色，从墙壁到招牌全是红色。招牌还用了金色，浮夸得令人却步。

招牌上写着一行字。

『日本第一美味辣味拉面 蒙古汤面中本 船桥店』。

「这家店不是中本吗！」

「就知道你听过。」

「当然听过。这家是常上电视的辣味拉面。」

对喔，听说中本最近到千叶开店了，没想到是开在船桥。

「我也还没来过，想说今天要来看看。」

「是吗？不过吃辣的没问题吗？」

平冢老师呵呵一笑。

「嗯，应该不会辣到那个地步。你放心。」

「我想也是。」

说是这么说，这家店都上过电视了，表示有一定的辣度吧。我有点不安。

「先去排队吧。」

我跟在老师后面。尽管称不上一条人龙，前面有几个人在排队，因此我们移动到最后面。

「是说这个队伍真壮观。」

「不不不，平冢老师，这种程度还好吧。」

「笨啊，比企谷。看看现在几点。」

经她这么一说，我望向时钟，现在时间下午两点半过后。

「下午两点到下午五点，对拉面店来说是不会有客人的『空闲时间』。这个时段店家经常休息。」

确实，根据我的印象，那三个小时很多拉面店都没开。

「这家店在空闲时间却有人排队。表示不会有问题。」

「这样啊，原来如此，我懂了……不过平冢老师，这您又怎么说？」

我指向贴在店面外墙上，推测是店长的帅气大叔穿着红色道服竖起食指的照片。

「刚才在站前那家店，您不是说过把自己的照片印在看板上有点那个吗？」

「噢，原来。但我记得他是白根社长，蒙古汤面中本的第二代传人。所以没关系吧。」

……呃，那个理由我完全无法理解耶？这样好吗？你对这家店会不会有点太偏心？

想着想着，队伍前进的速度比想像中还快，我们马上进到了店内。

「「「欢迎光临！！！！」」」

店员也干劲十足地招呼我们。像我这种阴沉的家伙一个人来，恐怕在入口就会被他们的干劲吓到折返。

店内的色彩以白色为主，柜台是ㄈ字形。整面玻璃墙让店内采光充足，感觉十分明亮。我左顾右盼，平冢老师站在餐券贩卖机前面。

「您要点哪道？」

「呃，老实说我很烦恼……这个叫北极的似乎最有名。」

我望向餐券的按钮，有注明辣度。上面写着「北极拉面 辣度9」。

「老师，这道拉面辣度9耶，您受得了吗？」

「放心。最高辣度是10。大概还行。」

「是这样吗？」

「那个有名的拉面美食家『面田边留藏（注34）』先生也说过吧……踏进拉面店就要去感受拉面店的心意，顺着店家的想法走，才是真正的吃拉面。」

「我才没听过那种名言！那个叫『面田边留藏』的人是谁啊，这名字怎么看都是乱取的！」

「总之我要点北极。你呢？」

「『面田边留藏』先生说的话没能撼动我……所以我要点这个辣度5的蒙古汤面。」

听见我的选择，平冢老师垂下肩膀。

「你真的很胆小……所以才一直做不出选择。」

「做不出选择？」

「……没事。我在自言自语。」

老师按下餐券的按钮递给我。我不知道该如何是好，像个可疑人士一样东张西望，和店员对上目光。

「两位请。」

店员亲切地带我们入座。我和平冢老师并肩坐在柜台座。店员走到我们面前，我们便将餐券递给他。

「不好意思，北极要『面半』。」

「瞭解。」

「还有LINE的『切蛋』。」

「瞭解！」

笑着接待客人，精力十足的店员回到厨房。

「好，接下来就等面送上来了。」

「呃老师，您整个超像常客的！」

平冢老师过于流畅地念出我只在这边听过的词汇，害我大吃一惊。

「您真的是第一次来这家店？」

「当然。」

「那为什么您讲得那么顺？」

「到从来没去过的店，预习是很重要的。」

老师挺胸回答。

「预习吗？」

「没错。去中本之前，我在网路上搜寻许多资料，『面半』是指面量减半，LINE的『切蛋』是只要拿有加中本LINE官方帐号的画面给店员看，就会免费送一颗切片水煮蛋的样子。」

原来如此。是这么一回事啊。我都没想过要预习。不过，经她这么一说，只要事先预习，能像老师那样流畅地答出这些情报，或许并不奇怪。

我环视店内。店里贴着社长上电视时的照片，还有许多艺人的签名。可见这家拉面店有多么受到瞩目，还有媒体帮忙宣传。

可是，期待值上升的同时，我也有种「如果店家只是因为方便利用才上电视，这样好讨厌喔」的想法。再说，跟第一家店的店长一样，把店交给其他人顾的同时，「这样不对吧？」的感觉就在我心中挥之不去。

「……侍奉社运作得还顺利吗？」

老师忽然提问，我将视线移回她身上。她拿起桌上的水瓶，往我的杯子里倒水。

「谁知道呢？我不这么认为。」

「为什么？」

「顺利的话，待起来应该会更不舒服才对。」

平冢老师闻言，露出成熟的微笑。

「不能尽如人意才是青春啊。」

她高兴地用左手揉乱我的头发。我不知道她在高兴什么。她开心是很好啦，但如果不能尽如人意才是青春，早一秒也好，我想尽快脱离那个青春舞台，在尼特舞台度过快乐的生活。能让爸妈养多久就耍废多久。

「这是您的蒙古汤面。」

在我们聊天时，店员拿着大碗站到我面前。咦，上餐速度比我想像中还快耶。

我边想边望向放到眼前的蒙古汤面，哑口无言。

「不好意思，你是不是送错餐了？我点的是蒙古汤面，北极是旁边这位小姐的。」

「啊，没错喔。那就是蒙古汤面。」

店员笑着回答，我倒抽一口气。因为蒙古汤面的汤头红到害我误会，看起来非常辣。

目所能及之处堆满红色的麻婆豆腐，勉强能从麻婆豆腐的缝隙间看见高丽菜等蔬菜。

「看起来好辣……不过，好好吃的样子。」

我感觉到美味的香气凌驾赤红汤头的瞬间，从大碗散发出的香气，带有味噌的风味及蔬菜的甘甜，让人想快点开动。

「久等了，这是您的北极面半，附赠LINE的切蛋。」

这时，平冢老师的拉面送上桌了。看到那碗面，我恨不得收回自己刚才的发言。

我在说什么啊。没错。这才是北极。

老师面前的，是在鲜红汤头上放着豆芽菜的面，白色豆芽菜与红色汤头形成美丽的对比，同时也将汤头的红衬托得更加明显。

「喔——好红。看起来不错吃。」

看到那碗面，平冢老师显得异常兴奋。

「老师，您吃得下去吗？看这颜色，应该颇辣的喔。」

我战战兢兢地问。

「哎，只能吃吃看啰。」

平冢老师话刚说完就离开座位，从餐券贩卖机旁边拿了两件纸围裙给我。

「谢谢。」

「好，开动吧。」

我们同时对眼前的拉面合掌。

我先用汤匙舀了一口汤。将参杂麻婆豆腐的汤送入口中时，我满脑子只有一种情绪。

「好吃！」

这碗面给人的感觉很辣，所以我本来还在担心，我的不安却瞬间被驱散了。汤头就是如此浓郁，一起吃到的麻婆豆腐确实很辣，但不会被辣味盖过的美味，支配着碗中的内容物。

接下来吃的是蔬菜。蔬菜也炖得很烂，入口即化，跟汤头非常搭。我心想「可能是因为我昨天玩切蔬菜的游戏玩到天亮，让我对蔬菜莫名有爱的关系，才会觉得蔬菜吃起来特别美味」，接着立刻发现这两件事毫无关联。

最后是面。

这道料理不是淋了麻婆豆腐的蔬菜汤。其中的主角——面条能跟其他食材较量到什么地步，这一点才重要。我可不希望迎接「除了面条都很好吃」的可悲结局。

我害怕地夹起面，放入口中。然后慢慢咀嚼。

这……

太美味了。

中粗面很有嚼劲，咬断面条的瞬间，小麦的风味扩散开来，支配口中。跟汤头的滋味融合在一起，和蔬菜也很搭，又不输给麻婆豆腐的个性。没想到会是这么完美无缺的面。

「老师，这什么东西啊。超好吃的。」

「是啊。说到中本先生，大家容易着重在辣度上，不过单从拉面的角度来看，这家店也很美味，所以才会这么受欢迎。」

语毕，平冢老师豪迈地吸起面来。我偷偷观察她。

她毫不犹豫吃着染成红色的面条。额头都冒汗了，把头发拨到耳后的模样却异常性感，害我因为吃辣之外的原因而脸红。

「嗯？怎么了？」

平冢老师察觉到我的视线，一面用餐巾纸擦嘴，一面看过来。

「啊，没事没事。什么事都没有。」

我大口吃着眼前的蒙古汤面，以掩饰害羞。

吃到一半左右时，我感觉到辣度在慢慢累积。麻婆融入汤头，味道自然会产生变化。美味的拉面变成辛辣美味的拉面。

我吃得满头大汗，却还是沉浸在它的美味中，专心致志地吃着面。

「谢谢招待。」

不知不觉，平冢老师已经把北极吃完。我也吃了九成左右，因此我急忙吃完剩下的面，合掌说道「谢谢招待」。

「好吃。」

「蒙古汤面就已经很辣了，您真厉害……可以分我一口汤吗？」

「好啊。」

我用汤匙舀了北极的汤喝下去。吃完蒙古汤面后，对辣味也习惯了，应该没问题吧。看，还行啊……

这个想法只维持了一瞬间，辣味迅速充斥口中。

「好、好、好辣！」

「比企谷，你未免太夸张了。没那么辣吧。」

「没、没有！真的很辣！」

我急忙将水杯里的水一饮而尽。可是喝完水后，比刚才更辣的第二波辣味紧接着袭来。

「！～＃＄％＆＠＆＄％！！！」

「啊，忘记跟你说，吃辣的时候喝水会觉得更辣，要小心喔。」

「太晚说了！」

我的脸立刻冒汗，率先走出店门。

我和平冢老师回到车上。开车的途中，我因为嘴里的辣味尚未消退，吐出舌头，用手搧风。

「你不擅长吃辣耶。」

「不不不，我一直不觉得自己不擅长吃辣，这个是例外啦。」

「可是很好吃吧？」

平冢老师骄傲地说，我缓缓点头。

「确实超好吃的。最后那口北极的汤也是，辣度令人印象深刻，底下却喝得出汤的美味，受不了。」

「说得好，说得好。」

老师强烈赞同。

「不仅好吃，分量也很惊人。那个量是怎样？我肚子饱到不行。」

「对啊。中本先生分量多，视情况而定，CP值高到一天吃一餐就够。」

「……平冢老师，您真的是第一次吃中本吗？」

「嗯，对啊。怎么了？」

「没有，只是觉得您未免太清楚了。」

哈哈哈哈——平冢老师宏亮的笑声于车内回荡。

「就跟你说是事先调查过。你想太多了啦。」

「是吗？」

「对了，我还有家店想去，你方便吗？」

「啊——嗯……反正就算我说不想，大概也拒绝不了，我就奉陪到底吧。」

老师斜眼看见我无奈的表情，微微扬起嘴角。

「那就出发啰。」

「好的。」

车子打了方向灯左转，过没多久，开上高速公路。

「等一下，要去那么远的地方吗？」

「也不会。我只是觉得快点到比较好。」

「这样啊。」

或许是我的语气透露出些许不安，平冢老师再度笑出声来。

「我又不会吃了你。」

「是没错。」

高速公路上没什么车，车速逐渐加快。

「对了，之前拜托你表演的漫才还顺利吗？」

「那个啊。真的超累人的。」

前阵子，侍奉社不知为何接到「在市内举办的以当地孩童为中心的亲睦会上表演搞笑节目」这个委托，搞得我和雪之下不得不上台讲漫才。

「观众有笑吗？」

「有啊，笑得超开心的。开心到可怕的地步。前所未有的大爆笑。」

「你讲得这么夸张反而像在说谎，不过顺利就好。」

是真的有笑，所以我没说谎。但我逗观众笑的方法，平冢老师可能不会接受就是。

「拜托别再那样乱来了。」

「不不不，叫你们侍奉社乱来是应该的。」

老师重新戴上墨镜，大概是嫌从对面照进来的阳光刺眼。

「乱来才叫青春。年轻人才有资格这么做。」

「大人总是会对青春抱持莫名的期待。那种东西不存在于青春时光内啦。青春是跟春天一样无色的东西，全是青涩的果实。」

听见我个人的主张，平冢老师冷冷望向我。

「你的说法真的让人很不爽……不如说不爽……或是不爽。」

「全是不爽嘛。」

「算了。好，快到啰。」

车子下了高速公路，又开了一会儿，停在停车场。

「比企谷，在这。」

我跟着平冢老师走了五分钟左右。接着大概是抵达目的地了，老师转头望向我。

「到了。」

「……等等，老师。您说还有一家店想去，该不会……」

「嗯，就是这里。」

眼前的店家跟刚才看见的景色类似，有种既视感。

我望向招牌上的文字。

『日本第一美味辣味拉面 蒙古汤面中本 锦糸町店』。

「又是中本！」

我大声吐槽，老师却一副「谁管你啊」的态度，摆出若无其事的表情。

「呃，我们不是刚刚才吃过中本吗！」

「比企谷，我们确实吃过船桥的中本先生。」

「咦？什么意思？」

「但锦糸町的中本先生还没吃过吧。」

我听不太懂她在说什么，是因为我现在不是冷静状态吗？

「不不不，平冢老师。中本是连锁店，吃哪家都一样吧。」

「咦？比企谷，你说什么？」

「呃，就是说，中本是连锁店吧，所以——」

「中本先生是连锁店？」

前一秒还神情自若的平冢老师，脸上浮现怒意。

「老师，怎么了？」

「我说啊，中本先生啊，是由店员亲自甩锅炒菜的。所以就算是同一道料理，每家店的味道都会有些许变化。吃中本先生就是要享受那个变化，所以绝对不要称呼它为连锁店。」

「咦？呃，可是——」

「道歉。」

「……老师，那个。」

「道歉。」

「……呃。」

「道歉。」

「……对不起。」

我开口道歉，平冢老师笑咪咪地走向店门。

「好，那走吧。还有你可能不知道，每家中本先生都有该店特有的『限定』菜色，品尝限定菜色也是店铺巡礼的乐趣。」

「限定吗？」

我望向餐券贩卖机，按钮配置确实跟刚才那家船桥店不同。我环视店内，发现船桥店没有的菜色。

「这是限定菜色吗？叫北极火山的这个。」

「答对了。」

平冢老师边回答，边按下餐券贩卖机的北极火山按钮。

「您是来吃这个的吗？」

「对。你也要吃吗？」

「不，我很饱，不用了。再吃辣的我也撑不下去。」

平冢老师用真的很不屑的眼神鄙视我。

「你是男生吧。还能再吃一些吧。」

「您吃得下是因为您在船桥店面量减半了吧！我吃的是正常量，吃不下很正常。」

我们在店里低声争执。

「我刚才不是在车里说过吗？青春就是要乱来。」

「就算这样，吃不下就是吃不下！」

「所以说新手就是这副德行……瞭解。那这么办好了。」

老师按下餐券贩卖机的按钮，将餐券递给我。

「把酱油冷汤面的面改成豆腐。这样就吃得下了吧。因为你是男生。」

「辣度呢？」

「这是叫做非辣的拉面，所以完全不辣。辣度0。」

我为那个数字感到惊讶。

「还有这种拉面啊？」

「船桥店也有啊。你没看餐券贩卖机吗？」

对喔，好像有又好像没有……

「走吧。」

在我回忆时，平冢老师已经坐上柜台座。我跟着坐到老师旁边，店员来到面前，我便把餐券递给他。

「顺便问一下，北极火山的辣度是多少？」

「12。」

「12⁉呃，最高不是10吗？」

「总会有个超出极限，类似Bug的存在吧。」

不不不，有Bug怎么行。我如此心想，刚开始产生的疑惑转变为确信。

「老师……我想问一下。」

「什么事？」

「您……常吃中本对不对？」

老师停下穿纸围裙的动作。

「不，这是第二次来。」

「怎么可能。我说中本是连锁店的时候，只有超喜欢的人才会气成那样吧。」

「不，我只是先查过。」

她故作无知，不晓得从哪里拿出橡皮筋把头发绑起来，我的视线被她的后颈夺去，但现在可不是看那些的时候。

「在船桥店的时候，我就觉得奇怪了。您拿纸围裙的动作太过熟练。没去过的人速度不可能那么快。」

「只是碰巧看到。」

或许吧。可是，我等等要说的并非巧合。至少要对这家店抱持某种心情，才会这么做。

「这个我就不认为是巧合了，您从途中开始就把中本叫成『中本先生』。未免太尊敬这家店了吧。这到底是怎么一回事？」

「跟对初次见面的人用敬语一样吧。」

这个老师还要继续装傻啊。对学生说谎成这样，从伦理学的角度来看不太对吧。

「就当成是您说的那样吧。那最后我说我吃不下两碗拉面时，那句话又怎么解释！您说『所以说新手就是这副德行……』。表示您不是中本的新手吧！」

听完我的推理，平冢老师仍然不动如山。她从肩背包里拿出一个东西，叫住店员。

「不好意思，可以帮我盖章吗？」

「看，果然常来！」

老师彻底无视我，让店员帮她盖章。

「我们去我打算吃的那家站前的新店时！您自己说过『有点数卡代表去过那家店』！」

平冢老师眯眼看着我，我搞不清楚她的意图。

「平冢老师，您也该承认了吧！」

沉默降临我们之间。

「……你会嘲笑一把年纪的女性，在藉由一个人吃辣味拉面得到刺激吗？」

「……咦？」

「比企谷，你会跟我那些亲戚一样，说『有时间迷上一个人吃辣味拉面，不如去更容易认识男人的地方』、『「辣」字左边的辛，真不知道是在指辛辣还是辛酸呢——』吗？」

她的表情充满愤怒及悲伤。

这时我终于发现。原来如此。老师因为迷上吃辣而被亲戚嘲笑，又因为还没结婚而受到责备吗？所以……才会忍不住采取这种行动。

意思是，我不小心踩到了她的地雷。得想点办法才行。

「呃……我不太明白……但我觉得能表明自己喜欢什么，性格直率的平冢老师，是不错的大人。」

「……你这安慰人的话说得挺有模有样的嘛。」

「不，不是安慰……是真心话。」

平冢老师的表情转为惊讶，接着忽然露出微笑。

「呵呵，由感觉不太会说真心话的比企谷这么说，还满有用的。谢谢。」

「不，没什么好谢的。」

容易让人觉得「看起来很爱说谎」、「看起来不会说真心话」的这张脸，第一次让气氛变好了。

「不好意思打扰了，这是面换豆腐的酱油冷汤面，还有北极火山！」

聊到一半，店员充满活力地为我们送上拉面。

我的酱油冷汤面面换豆腐版，是清澈的褐色汤头加上推测刚炒好的鲜脆蔬菜，汤头底下看得见豆腐。俨然是小小的火锅。

更重要的是平冢老师的拉面。

豆芽菜堆得跟山一样高，旁边淋着麻婆豆腐，大概是想做成岩浆，与北极火山这个名字十分相衬。最上面放着萝卜婴，可能是在营造山顶清爽的感觉。如此壮观的模样，可以理解为何会设定成辣度12这个妖怪般的数字。

老师看了，转动几下右肩。

「有压力的时候果然就是要吃辣。好，我开动了。」

语毕，她马上开始喝汤，我也跟着合掌开动。

我跟刚才一样，按照先汤后蔬菜的顺序享用眼前的酱油冷汤面，在心中佩服不辣的汤原来也能这么浓郁。而鲜脆的蔬菜也如平冢老师所说，跟刚才那家店的蔬菜风味截然不同，让人不觉得是在吃同一家店，或许是因为这是店员刚炒好的。要说共通点的话，就是「美味」吧。

这次就是量比较少的我先吃完了。我瞄了平冢老师一眼，她正在喜孜孜地推倒火山，大嚼面条跟豆芽菜。神奇的是，这副模样让我有种她是在爬山的恍惚感。

过没多久，老师吃完了。

「谢谢光临——！」

店员的声音从身后传来，我们走出店家。

「今天谢谢您的招待。」

「不会。我才要跟你道谢。」

在那之后，老师开车送我到我家附近。

「还满开心的。」

「呵呵，这么坦率的比企谷有点恶心。」

「这句话真过分。」

「哎，如果你能老实把想法说出来就太好了。谢谢你今天陪我。」

老师有点神清气爽，是因为刚流过汗吗？

「啊啊——」

平冢老师在驾驶座上大声叹气。

「怎么突然叹气？幸福快乐的结局近在眼前却叹出这么沉重的一口气，感觉会发生什么事件喔。」

「没有，单纯是在『想像』。如果同年代有跟你一样的人就好了——」

「跟我一样的大人……肯定不会有多像样。」

听见我的回答，平冢老师「噗噗噗」笑了出来。

「我想也是。在职场上不工作，在餐会上说一堆人的坏话，毫无大人样。」

咦，你不否定吗——？我觉得你只是在说我坏话耶。

「无所谓，这样就好。因为没必要勉强自己成为大人。你只要继续做自己，向前迈步就行。」

「……您今天对我的评价标准还真宽松（注35）。」

「对啊。可能是因为刚吃过辣。」

平冢老师望向前方。

「关于你毕业后的拉面。」

「是。」

「可以往后延一些时间吗？」

往后延？她还要查有哪家拉面店的意思吗？

「拉面单独吃是最棒的食物。不过，你可能不知道，它也可以拿来当酒会的收尾。」

「酒会？」

「等你能喝酒的时候，一起去吃拉面吧。拜啦。」

她高兴地轻轻挥手，开车离去。当时老师的表情，要是没有年龄差——不，就算有年龄差，在我看来也非常清爽，害我心动了一下。

俗话说，早起可得三文钱。

但我不只得到了三文钱，还得到无价的笑容。

……明天也早点起床好了。

完

** 我所想的健全的叶八

作者：丸户史明

「咦？什么？你开始抽烟了？」

「嗯，只有喝酒的时候啦。很奇怪吗？」

「呃，是不会……」

奇怪，非常奇怪。

太奇怪了，害我很想立刻震惊地吐槽「你都超过二十岁了不知道香烟对身体有害吗⁉」什么啦我们是Conte Leonardo喔。搞不好连作者都还没出生。（注36）

「我才想问，你明明不抽烟，为什么会来这里？」

「……呃，那个，有点事。」

不过，以在这个地方进行的对话来说，眼前这个文质彬彬的男子的疑问明显更合理。

毕竟这里是居酒屋店外的吸烟区。在这个到处都全面禁烟的时代，遭到迫害的尼古丁中毒者们能大发慈悲共享小小烟灰缸的唯一绿洲。

不是像我这种在挂着「本日包场」的牌子，热闹不已的店内找不到容身之处，企图混进烟雾中隐藏身姿的人可以待的地方。

先不说这个了，最好注意一下有在抽烟的作家。扔下「烟没了所以我写不出来」这句必杀台词从禁闭房消失，之后再也没人看过他的案例层出不穷，想着「既然这样，帮他准备吸烟室好了」，却半点进度都没有，无人能敌。写一下啦工作一下啦定期出书啦。只有薄薄一本也好。

「算了。你现在过得如何？」

「……还行。」

「意思是过得不错，挺开心的，还算幸福啰。」

「你对『还行』这句话太乐观了吧。」

「但虽不中亦不远矣吧？毕竟你都来参加同学会了。」

「因为来自各方面的压力太恐怖了。」

「现在的你身边的人多到会有人对你施压……那不就代表你过得很好吗？」

「……现在萤幕下方出现了『这是个人的感想』这行字幕喔。」

没错，这家伙说得没错，包下这间居酒屋举办的，是「总武高中第●●届2年F班同学会」这个大家一起缅怀往昔，大声欢笑，极度团体主义又怀旧，全是嗨咖的活动……Always（注37）。

对于从在学的时候起，就决定所有活动都要无视，结果被迫以侍奉社成员的身份担任幕后工作人员的我来说，面对如此丑恶的活动的举办通知，怎么可能回覆「我要参加～麻烦大家噜！」——呃谁擅自帮我回信的啦。再说擅自把同学会的通知寄一份副本给我的干事在搞什么啊。

说起来，为什么是2年F班的同学会？这样三年级的班级不是很没面子吗？

而且我是三年几班啊？就是因为这样，我才跟编辑部说把截稿日定在完结篇出之前很令人困扰。

是叫我怎么办啦别说完结篇了现在连十三集都还没出喔。不是预计要出了吗？

「那你呢？叶山，你又过得如何？」

哎，这位在吸烟区跟我聊垃圾话的，是在这种活动上和我形成对比，感觉会担任总干事（不如说他确实是总干事），公认位于旧2年F班阶级金字塔最上级，顺利从大学毕业，目前踏入社会第一年的叶山隼人。

本来他不可能待在这种地方……事实上，不久前他还被以前的同班同学拉着展开名片争夺战，是过了五年人气依然未减的大红人。

顺带一提，我第一次经历毕业数年后在同学会上交换名片的活动，今昔地位高低的变化及行业形成的温度差如实反映出来，我都看不下去了。「哇～外资系～」、「哇银行～」、「你自己创业吗？好厉害～！」、「啊，制造业，是喔～这样啊，哦～」诸如此类。你们知道职业无分贵贱吗？

外资系不拿出好一点的成果会立刻被炒掉，银行会因为内部人员互扯后腿最后调职，创业是破产的最短路径，你们知道职业无分贵贱吗？专业主夫果然是最强的吧？

不过，搬出「啊～我去念研究所了～」、「我还没毕业耶～」这种免罪符的家伙暂且不提，跟其他「没有头衔的人们」比起来……呃，别聊这个了好不好？

「嗯，跟你一样，还行吧。」

不晓得叶山是不是得出和我一样的结论，他符合我的期望，迅速结束这个话题。

「你依然是个不会说真心话的家伙。」

这家伙在察言观色这方面无人能及……好吧，在其他各种方面也是无人能及，令人火大，不过叶山意料之中的回答，使我有些怀念，苦笑着开玩笑回去。

然而……

「跟你一样。」

「……顺便补一句，你依然是个只有跟我讲话会带刺的家伙。」

叶山接下来那句话带着利刺，有点超出我的预料。

「你反驳得了吗？从以前到现在，不管是说出来的话还是内心所想，你都不会把最重要的事表达出来……不对，当时大家都不会说真心话。」

「这个嘛……」

靠无谓的闲聊敷衍过去的计划宣告失败，不太愉快的回忆在不知不觉间被唤起，我们都摆出一张臭脸。

这也是总在不经意间——不对，总是故意不把话讲清楚，将复杂又难以理解的心情藏进更深沉的迷雾中，于好于坏刺激到喜欢考察的读者，自己在那边窃笑或恼羞成怒的原作者害的。

这部作品真的很难搞。

「你没有变……始终如一到让人生厌的地步。」

「不是『让人生厌的地步』，你就是讨厌我吧？」

弥漫于吸烟区的烟雾，不如说那染上白色的空气，沉重又混浊。

竟然会在寻求一个人的空间而抵达的场所，建立如此恶心至极的人际关系，真是最烂的意外。

唉，早知如此，真不该逃到外面。

啊啊，同学会开始的三十分钟内都还很愉快的……好短暂的欢乐时光。

因为干杯时，我旁边坐着天使……外表体型声音都与高中无异，更重要的是没有长胡子的户冢。我只不过是离开座位一下去拿饮料，就有一群女生围住他，抱着他大叫「讨厌～你都没变耶～」、「好可爱～」根本无法靠近。

阔别多年的重逢，我们应该要在聊天的过程中不小心重燃过去的热情，户冢牵着我的手问我「欸，八幡……要不要一起偷偷跑掉？」静静离开才对，为什么会变成这样……

「放心，我也讨厌你。当时我们就只有这点互相认同吧？」

莫名愤怒的回忆，使我的表情及言行扭曲得更不友善。

叶山似乎也感应到了我的怒气，恢复成高中时代，绝对不会对我以外的人露出的那个表情。

我们两个踏进一触即发，不是激烈交锋，而是用冰冷的刀刃互砍的领域，下一刻……

「赞，赞，就是这个！阔别多年的重逢，在聊天的过程中不小心重燃过去的爱与憎恨与快乐与痛苦，将最真实的情绪暴露出来的两人！叶八回来啦！」

「……喔。」

「……姬菜。」

让我发自内心后悔自己不小心太激动的兴奋声音，从我们背后传来。

「嗯～糟糕，学生之间青涩的交流是很棒没错，不过长大后成熟的关系也好赞。身材强壮，也比较有野性。硬要说的话，我希望你们穿西装打领带，抓着领带强吻对方超香的不是吗？」

「……呃。」

「啊哈哈……」

「开玩笑的啦。嗨啰嗨啰，比企谷同学，你过得好吗？」

「……还、还行。」

跟五年前比一点都没变……不对，守备范围从男孩子扩展到大叔，更加进化的海老名，带着灿烂的笑容凝视我们。

「那、那个，姬菜怎么会在这？」

「啊～嗯，我好像有点喝醉，再加上不想待在人多的地方，所以出来呼吸新鲜空气。啊，看，连鼻血都流出来了。」

海老名用手帕遮住脸，表示自己身体状况不佳。我说，那个鼻血肯定是刚流出来的吧？

「还有，大家在吵隼人怎么不见了，我顺便来找你……」

「噢，原来，过那么久啦。那我……」

「不过别担心！我怎么忍心夺走对我来说珍贵的……不对，对你们来说重要的时间呢！」

「不是，那个……」

而且她明明表现出不舒服的模样，现在却精力充沛地制止叶山，拿出手机，镜头对着我们狂按快门。

「放心。我会设定成比企谷同学喝得烂醉在外面狂吐，隼人在照顾他。这样大家就不会想到外面来了吧。」

「呃，我说……」

完全无法放心耶。我好不容易把存在感压得这么低，这样又会跟高中时期一样，把大家的仇恨值吸过来。

「所以请两位慢慢享受～三十分钟内绝对不会有人出来。拜拜～」

「啊。」

「啊。」

海老名怀着暴风雨般的误会（但在她心中是事实），拉开居酒屋的拉门，迅速钻进店内。

「…………」

「…………」

留下两位困惑又尴尬，茫然杵在原地的男性……

这个气氛是要我怎么办啦。海老名过了五年也还是一样超过。如果有人问我有没有办法推她，我只能说办不到。

什么叫培育不起眼的女主角啊不起眼的人哪可能变成偶像或女主角书腰上的推荐文是谁写的啊。（注38）

「……你也要抽吗？」

「不，不用。我没抽过烟。」

「这样啊，那我也别抽好了。」

「我不介意啊。」

「没关系。我本来就抽不多。」

「是吗……」

不说话还是不可能心灵相通的我们两个，总不能一直默默站在这边，迫于无奈，只得遵循日本人的美德，继续从社交辞令开启对话。

互相试探彼此的气氛，逐渐用无足轻重的话题慢慢拉开距离，摸索能尽快结束这段对话的流程。

为此，像刚才那种冷嘲热讽绝对要禁止。要是再度营造出险恶的气氛会很麻烦。

「对了，海老名不知道从什么时候开始乖乖叫我比企谷了。」

「嗯？她不是一直这样叫你吗？」

「没有，以前她叫我比企鹅同学……你刚开始不也是这样叫吗？」

「喔，那个啊……」

因此，我绞尽脑汁，开启一个超无聊的话题，好让这成为最后的谈笑。

「是说，比企鹅同学这个叫法就是因为你传开的啊。创始人都改掉了，其他人却还是固定这样叫。」

我一直有那么一点在意，但真的只有一点点而已，所以事到如今，这应该是谁听了都会左耳进右耳出的小笑料，或是没人记得的无聊话题……

「也是啦。我的姓氏太拗口，所以不能怪——」

「当然是故意的。」

「……喂。」

我的「有那么一点在意」却起到了反作用。

「你不会不知道吧？我不可能叫错别人的名字。」

「呃，现在也就算了，当时我怎么可能知道……」

「那你现在不就知道了？」

「这……」

没错，叶山隼人为了维持叶山隼人的形象，连那么一点小错误都不能原谅。即使对方对他来说是无关紧要的人。

……不对，有点出入。愈是不重要的人，就愈不能容许那种小错误。

因为这家伙的人生态度是「给予所有的生物爱与慈悲与平等」。

「比企鹅不是绰号。其中没有爱也没有亲昵之情，单纯是失礼的念错字。大家都跟着我一起这样叫，但那其实是无自觉的霸凌。若你主张那是骚扰，肯定会被承认。」

「别说了，过了这么久我怎么可能还会在意。」

「意思是你当时会在意啰？就算只有那么一点。」

「你今天怪怪的喔……」

这样跟以往相同……不如说，跟五年前的立场相反。

……不，也不能这么说。尤其是在「那家伙家」的问题浮上台面后。

「我再说一次。我是故意的。明知道其他人八成也会跟着叫，还是选择这么做。我承认，当时的我怀着明确的恶意。」

「够了。还有以后别再喝酒。然后把今天的事情忘了，我也会忘记。」

「不，我不会忘……酒的话，我的酒量在大学时期锻炼得不错喔。」

呃完全没锻炼到吧看你这么缠人。这家伙大学时期绝对列在「死都不能让他喝酒的学长名单」上。甚至有可能只有他一个没收到酒会的邀约。

说起来，通常霸凌人的那一方都会忘得一干二净，讲出「咦～有这回事？嘿嘿♪」这种话，害人更火大吧。为什么你记得那么清楚？

「叶山，你想干么？希望我揍你吗？」

然后在被我痛揍好几拳后恼羞成怒地大骂「我没叫你做到这个地步吧！」予以反击，两个人打成一团，过没多久同时笑出来，最后搂着肩膀大笑——你是想要这种介于青春剧和偶像剧之间的展开吗？是说那完全是昭和风耶，现在连平成都结束啰？

「没有，我只是觉得，不把这句话说出来心里就怪怪的……」

然而，这家伙果然是平成年间出生的，没有逃去使用暴力，而是对我投以锐利的目光，以代替拳头。

「我打从心底讨厌那个时候的你。」

曾经在我面前宣言要「永远扮演好叶山隼人」的这个人……

不知为何，只有在我面前不肯扮演我所期望的他。

「就叫你别说了……就算是我，也不可能对那种毫不掩饰的恶意无动于衷喔？」

是啦，当时我确实在被迫做出各种决定的时候，故意承受他人的恶意，尽管如此，依然逞强着迈向前方。

但那是因为有着明确的目的……

「嗯，我知道。你比别人所想的更加纤细、胆小，是个滥好人。」

「既然如此……」

「可是我知道，无论你受了多重的伤，都不会屈服。也知道你会靠自身的力量克服，知道你会再度向前迈进。」

所以才会拼命咬紧牙关，想着「只要是为了达成那个目的」……

「只要是为了保护重要的事物或重要之人。」

「……那有什么不好？」

「我没说不好。只是不喜欢。」

对喔，以前这家伙也因为类似的原因生过我的气。

记得当时他是责备我「为什么你只会用那种方法」。

「因为那是其他人……不，至少是我绝对做不到的事。」

本以为他纯粹是在否定我笨拙的行动……

「……那个，就我听来，只是在嫉妒吧？」

「嗯，没错。」

「你竟然还承认……你真的是那个叶山隼人吗？」

「因为，你不会嫉妒我吧？从来没羡慕过我任何一次吧？」

可是，就算是因为喝了酒，就算是因为以前的回忆朝错误的方向增幅。

「但我看到在班上显得格格不入的你，有办法接受这一点的你，感觉很差。彷佛在被迫观看自己想成为，却绝对不可能成为的人的可能性，令人作呕。」

如果他现在说的话及感情不带半点真实，我觉得我这辈子都无法再相信人类。

「喂……还是给我一根吧。」

「你不是不抽烟吗？」

「这种愚蠢的对话，哪可能靠酒就盖得过去。」

叶山毫不畏惧我像在瞪人的视线，从口袋里拿出一盒香烟递给我。

我抽出一根烟，他理所当然似地把打火机的火凑过来。

光这个行为就感觉得出以前的叶山隼人的作风，但我压根没想到跟他一起抽烟这个状况会发生在自己身上，怪别扭的。

这是什么？这什么东西？

「……噗哈。」

「劝你最好别吸进肺里。你是第一次抽吧？」

「啰嗦。」

叶山也叼了一根烟点燃，露出介于嘲笑与担心之间的表情，看着我第一次抽烟的丑态。

充满胸口的烟，无情地持续刺激我的支气管，现在咳嗽未免太难堪，因此我拼命将烟雾吞下去，一口气吐出。

……我看衣服绝对会沾上烟味。那家伙八成会注意到。

「你变得很难堪喔。」

「是吗？」

肺终于稍微适应烟雾了，心情逐渐平静。

随着心情恢复平静，刚才受到的不合理对待点燃的冷静怒火，转为困惑支配我的大脑。

「许久不见的同学硬要跟我聊不愉快的回忆，用一副要跟人吵架的语气对我说教。还是在酒会上……根本是烦人的大叔。加个秃头属性就完美了。」

「那还真令人高兴……我的梦想就是成为平凡的大叔，埋没在众人之中。」

抽了口烟，他似乎也稍微冷静下来了，之前感性的话语变得较为理性……不对，是带有讽刺的味道。

这家伙是怎样？他果然没打算改掉跟我对呛的态度嘛。

「随便找个人结婚，随便找份工作做，开始打高尔夫球，在小孩的运动会上疯狂录影，一面被老婆骂一面在阳台抽烟，参加酒会时被部下缠上，可是一聊到小孩的话题就会变和善……我想成为这样的人。」

的确，叶山述说的梦想我也能产生共鸣……前提是不用工作的话。

不过……

「那我换个说法……你无论是现在还是以前，都很难堪。」

我那冷静的怒火一旦燃烧起来，是不会轻易平息的。

「完全没有成长，完全没看开。你到底要瞧不起人到什么时候、什么地步啊。为什么是以能结婚生子为前提？为什么在酒会上纠缠你的人是部下啊你何时升迁的少在那边摆上司架子啦混帐东西。」

我在内心羞耻得大叫「哇连我都好难堪！」然而话一说出口就收不回去了。

「不管是以前还现在，你应该都能成为自己想成为的人才对。只要你认真起来，绝对有办法成为无聊的大叔。」

而且，我连接下来的话都吞不回去，跟联谊时喝醉的大学生一样，滔滔不绝。

「但你不是真的想成为那样的人，所以什～么都做不到。全～部细心地用无聊的藉口去掩饰。」

叶山却没有打断我一句接一句的话语，仅仅是冷静地等待我说完。

「我保证。你死都无法成为无趣的大叔。你哪能成为那么高格调的人。」

现在回想起来，这家伙好像一直在等我这么做。

「你刚才说我不会嫉妒你对吧？废话。我怎么可能嫉妒那么无趣的人。不管是现在还是以前。」

也就是，我被算计了……？

「你真的，真的……很难堪。」

「具体上来说，是哪些部分？」

「察言观色的方式很奇怪。为了避免其他人受伤，为了不让任何东西被破坏，你未免太坚持要维持现状了。」

「维持现状有那么不好吗？」

「你要为了达成这个目的压抑自我，没人管得着，可是你的情况，会连其他人都跟着压抑。例如户部，连三浦也是。」

「噢，嗯，确实也有这么一回事……」

「而且你还会为此后悔、道歉，显得更加难堪。你就是个善人和恶人都没办法当好的疯子。」

传遍全身的，是酒，是烟，还是险恶的气氛呢……

叶山促使我变成跟他一样，逐渐沦为爱说教的大叔。

「啊哈哈，不错啊……我确实是个不上不下的疯子也说不定。」

被我责骂的当事人看着我失去理智，显得异常愉悦，轻松地催促我继续口吐恶言。

……我果然被算计了？

「做那种事哪里开心？身为有钱的帅哥，给我再沉迷于私欲一点啊。你可是站在金字塔最顶端的人，得展露出卑劣的本性才行。在大学的校草选拔大赛上夺得冠军，却因为性骚扰而遭到逮捕，才叫胜利组吧。」

平常我只会在心里想，绝对不会说出来的话，再怎么忍耐还是接连脱口而出，我既兴奋又烦闷。骂人好爽喔。

「欸，比企谷……那我该怎么办？」

表面上被骂得体无完肤，可是这家伙心底大概是截然不同的表情，叶山哀伤地移开目光，又拿出一根烟点燃。

「不对……我该怎么做才好？」

「谁知道。自己去烦恼一辈子吧。」

「我想也是，你就是这样的人。」

连这种彻底过时的昭和风动作，都让人觉得有那么一点有模有样，就是这家伙一辈子不能原谅的原因。

「我不是说过吗？我们小学的时候，如果你跟我们同班，『她』不晓得会怎么样。」

「啥？那个，有这回事……？」

「…………」

「有啦我记得啦不要露出那种表情！」

……我之前都没发现，香烟这种东西是只要默默向上吐烟，就能对人施加无言的压力的方便道具。

「若是如此，『她』是否就能改变，是否就能得到救赎……噢，现在讲这些可能有点失礼。毕竟她是因为有过那样的人生，现在才……」

「不要动不动就讲题外话害我觉得别扭。」

不如说，请不要讲完结篇可能会提到的设定。就是因为这样，我才跟编辑部说把截稿日定在（下略）。

「不过就算那样，我们到最后还是不会有任何改变吧……你没想过吗？」

「怎么可能想过，麻烦死了。」

「即使我没有扭曲自我，没有改变身边的人；即使你没有扭曲自我，改变了身边的人。即使我无视了许多人的心情，即使只有特别之人对你抱持特别的感情……到头来，我们两个还是会跟现在一样不堪吧。」

「……这次你想表达的意思是什么？」

「我们是存不存在于彼此的世界都不重要的人……」

「当然啊。因为我对你又没兴趣。」

「有人当面跟你说这种话，不会很火大吗？」

「是你自己开启这个话题的还怪我⁉」

啊啊够了，真的是……这家伙今天有够烦。

老实说，叶山散发出的忧郁气息，害我不禁怀疑他是不是不适应现在的工作，没问题吗？

据说从未受过挫折的人，脆弱到稍微折一下就会断掉，求你不要让我在之后的独白讲出「那是我跟那家伙最后一次交谈……」这种话喔。

「来，啤酒。」

「不好意思……」

我将在附近的便利商店买来的罐装啤酒递给他，叶山露出有点尴尬的表情，但还是乖乖接过。

他拉开拉环，气体从罐口冒出来的爽快声音响起，然后是铝罐碰在一起的沉闷声响，啤酒通过喉咙的豪迈声音接在后面，最后，我们再度「噗哈～」发出带有浓浓大叔味的叹息声。

是说在居酒屋门口喝罐装啤酒，是妨碍营业吧。还有单手拿着啤酒边喝边聊天，实在不是二十岁出头的人会干的事喔。我们到底在干么。

「可以不必管我，自己先回去啊？」

「没关系，反正那里我也待不下去。」

从刚刚开始，我们的对话就一点意义都没有，只是不计形象地互相否定，却在演变成互相中伤前回头，不断比赛谁较为胆小。

「是吗？我倒觉得其实很多人想跟你说话。尤其是部分女性……」

「你的需求度照理说比我高上几百倍吧。要回去的话你回去啊。」

「现在有点不方便……要恢复成平常的我，大概还得花上一些时间。」

「随你便。」

没能立刻结束这场互骂，是因为眼前的「失魂落魄自暴自弃叶山隼人」太过罕见……不如说，是让人无法置之不理。

没错，绝对不是因为进店里跟许多以前的同学接触的话，会提高设定跟原作者互相矛盾的风险。是说这个梗都快用烂了。

「冷静一想，我们两个现在这副德行太废了吧……适合这种样子的，可是小静那个等级喔。」

「噢，我也有邀平冢老师，不巧的是，今天刚好跟她朋友的婚礼撞期。」

又被朋友超车啦而且都过这么久了。简直像在马拉松大赛上跟自己约好「我们要一起跑到终点喔」的挚友，于最后关头突然加速……不，是约好「我们要永远都不跑到终点喔」的朋友。算了，怎样都好。不对，是怎样都不好。

「对了，老师还是很关心你。顺带一提，她的近况是……」

「闭嘴。我不想听。」

因为我觉得听了后，无论那个人幸福还是不幸，我都会受到打击一蹶不振……这是什么前女友之感啊。五年不见重逢后一口气重燃爱情把家人朋友恋人统统抛下跟对方一起逃到国外的女主角？（注39）

不晓得是天气还是脑中的想法害的，我感到些微的寒意，决定中断跟叶山的对话，拿出手机打起讯息。

叶山也望向自己的手机，彷佛在配合我的逃避行为。

过了一会儿，我们都默默滑着手机，度过对我而言称不上幸福无比，不过某种意义上来说很有我风格的时间。

话虽如此，跟以前不一样的是，萤幕另一端一直都有人在。而这也是常态……

「……她过得还好吗？」

不久后，大概是累了吧，理应在专心滑手机的隔壁那位，咕哝着对理应在专心滑手机的我提出直指核心的问题。

「喔，说到这个，小町那家伙最近的最强妹妹度愈来愈高已经可以就任全国国民的妹妹，但她还是决定一辈子都只当专属于哥哥的妹妹，推掉五年三十亿的报酬，宣布继续留任……」

「我没打算陪你逃避。不想说的话直说就行了。」

「你这家伙搞什么鬼小心我○了你喔。」

小町会就这样顺利地讴歌大学生活，朋友擅自推荐她去参加选美大赛，理所当然获得冠军。本人明明想去千叶电视台上班东京的放送局却不肯放她走从气象播报员姊姊当到晨间新闻主播最后被人叫做比鸡谷跟职业棒球选手结婚，这恶梦般的未来在等待着她，这男人却……

至少挑千叶罗德海洋队的选手吧，这样我还能接受……不，哥哥还是不想接受我该怎么做才好。

「哎，看你在同学会期间还在跟她传讯息，应该很顺利吧。不好意思，问了不用问也知道的问题。」

「顺不顺利我不清楚啦，但我现在的话题全是对你的抱怨喔。」

「那她怎么说？」

「……叫我传我们的合照过去。她最近好像缺少能让她捧腹大笑的笑料。」

「要拍吗？」

「谁要啊！」

这男人不晓得知不知道我有多懊恼，完美判读气氛，精准地讲出惹火我的台词……

早知如此，乖乖被大宴会厅的喧嚣淹没，当个边缘人，会有多轻松啊。

「对了，我之前就想问……」

「她过得很好。不管你是在指谁。」

我不甘心只有我一直被他惹火，因此……

「结果你的本命到底是姊姊还妹妹？」

「…………」

我也完美判读气氛，使出只能用一次，用了比赛就到此结束的最终兵器。

这样他应该会安分一阵子。不，也有可能永远不说话。

「……………………」

叶山先是深吸一口烟，花了很长一段时间吐出来。

「………………………………」

接着又花了很长一段时间，吸出残留在罐底的啤酒。

「干么不说话？总不会是妈妈吧？」

「…………………………………………」

结果烟酒都没了，他本想再拿出一根烟，发现整包空了，焦虑地捏烂纸盒，两手空空的状态维持了一阵子，然后……

「你这人还是老样子，恶劣到了极致！」

「能得到您的称赞真不敢当～」

至今从未有过的慌张语气……

让通过喉咙，已经变温的啤酒，滋味变得十分芳醇。

「所以，我还是不能认同你……你懂吗？」

「你今天是怎样？现在的工作做得不顺吗？」

「我啊，超享受现在的人生。可是跟你说话的时候，就会想起以前的伤口，只会觉得非～常不愉快。」

「是你自己要来找碴害我心情也变差好吗你这个●●给我适可而止喔。」

两个大男人在居酒屋前面，脚边堆满大量的空罐不停碎碎念，已经可以说是完美无缺的妨碍营业。证据就是从刚刚到现在都没半个新客人进来。喔对喔这家店被我们包了。那我们在干么？喔，同学会。

是说，我记得我们一开始喝的是铝罐装的啤酒，现在堆在脚边的，怎么看都是大罐的STRONG系角嗨耶。要是之后转为喝烧酒加汽水，就开不了车啰。不对早就开不了车了。

「再说，明明是我更讨厌你，为什么我要被你骂得那么莫名其妙？也让我多抱怨几句啦。」

「再说，我才觉得莫名其妙吧。我想跟大家好好相处，事实上也一直是这么做。为～什么你一开始就讨厌我……」

「当然讨厌啊。谁会喜欢拿协调性这种独善其身的理由企图操纵他人的伪君子？啊，还有我讨厌你的脸。那种像在说自己『我没打过手枪喔♪』的脸。」

「哇，比企谷你变了，高中时期的你唯独不会开黄腔。」

「我只是因为没朋友，没人陪我开黄腔啦～你朋友那么多却没开过黄腔对吧？这种做作的地方我也无法接受。」

「什么嘛所以你其实很想开黄腔啰？那我问你你现在一星期打几次手枪？」

「啊～啊～各位观众～有个帅哥在现在这个反骚扰社会的时代狂讲打手枪这种词汇喔～？」

「以你的个性一定知道『※<帅哥限定>』的用法吧？就是这样啰～」

「那是高中时期的梗吧！用过时的梗还用得那么开心你是中年大叔吗！」

简直像处男高中生或爱去风俗店的大叔……呃我以前是前者啦，不过至今以来从未讲过的蠢话，竟然会跟面前这个看起来一辈子都不会开黄腔的人说，还是在双方的香烟的烟会碰在一起的距离，这个状况已经不能用「因为我们都醉了」来解释。

所以是怎样？我跟叶山不知不觉间成了能真心交流的关系吗？还是我们都是处男高中生或喜欢去风俗店的大叔？咦，这家伙高中时期是处男吗？

话说回来，我们的话题是不是有点在无限轮回？不，没有吧。好像有。

「啊～够了，我还是回去吧。谁想待在这种鬼地方～」

「店里你不是待不下去吗～？」

「至少比这里好！」

不晓得骂了第几句，我摇摇晃晃地站起来……呃，还以为我们是站着喝酒，结果不知何时蹲到地上了。真是人中之垃圾。

「是吗，那今天就放你一马。」

「不只今天。我绝对不会再跟你一起喝酒……同学会也是，死都不会再参加。」

我从自己开不了口回嘴「你根本被我压着打好不好！」这一点，判断结果是两败俱伤，扔下一句话就摇摇晃晃地转过身。

喝得这么醉，回去应该也绝对不会有人愿意理我，之后只要瘫在角落，等到人不知不觉都走光了，让店员叫醒我即可。

总觉得好糗好难堪，在喝醉的案例中属于最惨的类型，但这也没办法。

「不，不只同学会。别再把我牵扯进无谓的活动中。例如同班同学婚礼结束后的聚会。」

「……你的话不是受邀者，而是主办方……」

「你少说几句话会死喔！我绝对不会参加也绝对不会当主办方。」

毕竟一切的元凶就在于不小心跟这家伙撞在一起，只能斩断源头。

也就是说，只要一辈子不再跟他扯上关系就行。

「……那，这就是我们最后的对话啰。」

叶山坐在地上，低着头喃喃说道。

他的态度及动作散发出一股寂寥，不过也可以视为单纯只是醉昏头，所以我决定放弃推测他的真意。

「是啊……喔，不过你的葬礼我不是不能参加。因为葬礼就不用说到话了。到时再迎接我们阔别三十年的再会吧。」

「三十年……我的寿命会不会有点短？」

「那就一百年。」

「你打算活到几岁？」

「我是专业主夫，不会有压力，可以活很久。」

一如往常……直到最后都不认同对方，很适合拿来当几乎不会见面，又一直合不来的我们最后的交流。

「……你直到最后都是个惹人厌的家伙。」

「彼此彼此。」

「嗯……那一百年后见。」

「嗯，拜啦。」

于是，我们……这次真的说了最后一句话，断绝彼此之间的交流。

我背对叶山，走回热闹的同学会会场。

这家伙等等应该也会跟我一样回到店内，然而到时候，我们的对话及目光都不会再相交。

无论喝得多醉，叶山肯定都会坚持扮演好平常那个领导者。

而我不管多想跟他人接触，肯定都会坚持扮演路边的石头。

欢乐的同学会，会在叶山的致词下散会。

那家伙会被他的跟班抓去续摊，我则回到有……在等待我的地方……

「好～那大家辛苦啰～！」

「注意别忘了带东西～」

「要续摊的人来这边～」

「咦。」

「咦。」

我刚朝店门伸出手，门就开了，人潮伴随热闹的交谈声从中涌出。

「喔，隼人。还有比企谷也在这啊？」

「你们抽烟抽好久……呃，那么多空罐是怎么回事？你们醉得彻底耶。」

「隼人一直没回来，所以我们先宣布散会啰？」

在人群中负责带队的三人发现叶山瘫在路边，走了过来。

是五年前在叶山集团中特别显眼的三笨蛋，茶渡、大和、大冈……噢抱歉不是茶渡是户部。

「散会了？这么快？」

「『这么快』……隼人，你看看时间？快换日了吧？」

「咦？真的假的我怎么不知道。」

户部错愕的态度及回答，使我急忙拿出手机看时间，这个瞬间，时间正好跳到○○：○○。

咦？所以是怎样？我跟这个醉汉两个人聊了将近四小时吗？难道我也喝醉了？呃是没错。

这样的话，如果把这篇短篇小说里「×××」之间的未收录对话统统写出来会有几页啊。

「户部，他们交给你了。我带其他人去续摊。」

「我去拿他们的东西。麻烦啦。」

「哇咧～你们是怎样？把这两个醉汉塞给我，自己落跑？」

我和叶山呆呆看着三人轻浮却俐落地分配工作。

高中时期，没有叶山就什么事都无法决定的这三个人，如今成长到同学会……不对，至少收尾和带人去下一间的工作都一手包办，还能照顾叶山（附带我）。

那陌生的画面，让我感觉到五年的差距。

因此我和叶山的表情跟感慨地看着孙子长大的失智症老爷爷一样。不过我们都失智，很快就会忘记。

「隼人，站得起来吗？」

「嗯、嗯……」

相较之下，被户部搀扶着，摇摇晃晃站起来的叶山是多么不可靠啊……嗯，五年的差距真残酷。

「嘿咻……比企谷，你自己一个人走得动吗？」

「嗯、嗯，我还撑得住。」

「那你从另一边帮我扶着隼人……」

「不要。」

「啊～我想也是～你就是这样的人～」

就这样，被抛下的户部散发出「拿你没办法」的大哥气息，一面抱怨一面辛勤地照顾叶山，还不忘关心我。

拜他所赐，叶山格调降低的感觉愈来愈强烈。

「是说，你们今年好像也聊得挺开心的嘛。」

「……怎么可能。」

「……真是最痛苦的时间。」

不知道户部是不是出于好意，但这句话听起来反而像在挖苦我们，导致我和叶山同时臭着脸回答。

一股又酸又苦的滋味在喉咙深处扩散开来，我勉强吞了回去。不快点去便利商店补充姜黄就糟了。不，现在哪有时间担心宿醉，这可是紧急情况。

「你～们在说什么啊。这五年你们每次都这样。」

「…………我不记得。」

「…………同右。」

我正在「这边交给我，你先走……呕恶恶恶恶」帅气地跟名为从喉咙涌上的胃液的敌人战斗，唯有不会看气氛这一点一如从前的户部，又开了个令人不爽的话题。

「因为你们每年同学会，一定会两个人一起消失啊。然后找个莫名其妙的理由，每次都大吵一架。」

「………………就说不记得了。」

「………………你也该闭嘴了吧。」

「问隼人明年同学会要不要停办，他绝对不会停办。比企谷也是，不想来的话大可不要来，你却每年都乖乖参加……你们是牛郎与织女吗？」

「我我我我是因为有很多人对我施压。」

我急忙打断要是不小心被海老名听见，她会激动地问「那谁是织女⁉」的玩笑话。

「是吗？我只有前两年有找人对你施压喔？」

「你为什么要挑这种时机讲这种话⁉」

照理说已经喝得烂醉的叶山，却依然毫不掩饰敌意，开口刺激我。没错这是敌意不要误会喔。

是说再怎么想，不知为何要举办二年级的同学会，而且还是年年举办，干事显然有问题吧。所以牛郎是……算了还是别想了。

还有电线杆后面怎么好像有类似眼镜的物体闪了一下，这也当作是错觉好了。

「就是因为这样，今年连隼人都没有女生敢靠近。」

「……这家伙只是在拿我当驱虫剂吧？」

「有其他女生跟你搭话，你也会很头痛吧？毕竟你似乎随时都处在她的监视下。」

「才没有～是我自己要跟她报备的。」

「你不知道吗？那种类型交往愈久，嫉妒心就会愈重，变得很难搞……」

「好好好～到此为止！剩下的到下一家再聊！」

这时，户部因为不知何时会结束的战斗感到不耐，硬是介入我们之间。

顺带一提，每年都会这样闹到早上。从去KTV续摊，到去萨利亚续续摊……

一年之中，三百六十四天不会见面的我们，仅此一天的争执。

未来不知道会持续多久。不对，我一点都不希望持续下去。

不过，只要我们之间的争执仍在持续，唯有这家伙，我绝对不能输。

「叶山，你其实超喜欢我的吧？对吧？」

「如果我回答『其实……』你会不舒服吧？所以别问这种问题。」

「不是叫我别问这种问题你也否认一下好不好喂。」

最后，我要再解释一次，这是在完结篇出之前写的故事。

所以，当时还没确立关系的人不会出现。

在这之中，这是我希望能这样发展的可能性。

无论「他」选了谁。

无论「那家伙」走上什么样的道路。

都与那无关，这是「我」所想像的可能性。

感谢您的阅读。

完

** 果然只要有妹妹就好了。

作者：渡航

风吹动走廊的窗户。

往社办走去的我暂时驻足，望向窗外，晚开的樱花彷佛在惋惜春天的结束，翩翩起舞为它送别。

四月也已经过了一半，薰风的季节即将到来。

高中最后的春天很快就要迎接尾声。不，不只春天，许多事情都准备划下句点。再不到一年，我就要从高中毕业。

离考大学剩不到十个月。大学入学共通考试剩下九个月。咦，糟糕，怎么回事？时间超赶的耶，真的完蛋了。

考虑到考试的话，现在开始准备别说太慢，甚至有可能太迟。

大脑知道必须立刻翻开课本，身体却不听使唤。嘿嘿嘿，嘴上这样说，身体倒是挺老实的嘛……好不甘心！嗯啊嗯啊！

然而，就算我的身体是个任性的老实人，一个字都不念也不太好。突然开始拼命念书难度太高了，不过至少该先做个准备吧。

于是，放学后，我在去社办前绕到升学辅导室一趟，将各家补习班的招生简章收集起来。

反正那个社团闲到不行。思考的时间要多少有多少，正好拿来打发时间……是不是该利用那段时间念书？

正常的想法闪过脑海一瞬间，我却将其驱散，握住社办的门把。

拉开拉门，熟悉的景色映入眼帘。

雪之下雪乃正在以优雅的动作泡红茶，由比滨结衣从书包里拿出煎饼，窸窸窣窣堆在盘子上。坐在两人对面的，是以手托腮看着手机，不是社员，不知为何却待在社办的一色伊吕波。一色的存在有点算是特例，但这画面挺常见的。

唯一一个明显的差异，就是一色旁边坐着我妹——比企谷小町吧。

小町身穿崭新的制服，哼着歌擦桌子，把雪之下和由比滨的杯子放在一起，拿出新纸杯，勤奋地做事。

看来侍奉社在新社长的带领下，以新的机制开始运作了。说不定总有一天，这股红茶的香气也会传承下来，由小町来泡红茶。对了，一色同学又在做什么呢？来喝茶的客人？

这时，一色听见开门声，转头看过来。

「啊，学长。你好慢喔——」

她鼓起脸颊装可爱，我点头随口应声「是是对不起喔」，走向老位置。

「自闭男，嗨啰——」

「你好。」

由比滨轻轻挥手，雪之下在我的茶杯里倒满红茶。我简短回答「嗨，辛苦了」，拉开椅子。

雪之下将冒着温暖蒸气的茶杯放到我面前……的前一刻。

「啊——雪乃姊姊，请等一下。」

小町叫住了她。

「咦？什、什么事？」

忽然遭到制止，雪之下显得不知所措，小町对她投以带有几分愧疚的微笑。

「小町觉得这对哥哥来说还太早了。」

「嗯、嗯……确实，比企谷同学或许还无法理解红茶的滋味，不过……只给他一个人用等级较低的茶叶也不太好……」

雪之下边说边瞄向放在社办的茶叶。

「嗯……怎么看都是帮哥哥准备的廉价茶叶……」

小町那微妙的表情，彷佛在说「不愧是雪乃姊姊……」。哎，事实上，我的确喝不太出来每种茶叶的差异，所以雪之下是对的。不如说她特地准备我专用的茶叶，我还有点感动呢。

「……不是味道，是温度啦。嘿嘿嘿……」

「温度……啊……」

由比滨张大嘴巴歪着头，似乎想到了什么，发出感叹声。雪之下也几乎在同一时间点头。

「是啊，他怕烫。」

「两位都答对了～！鼓掌鼓掌鼓掌！」

小町笑咪咪地拍起手来，然后立刻装出一本正经的态度，晃动手指开始说明。

「小町家的人大多都怕烫，所以喜欢喝更凉一点的红茶。还有，喝没加糖的红茶时，建议搭配甜食当茶点。能记得的话小町觉得分数挺高的。」

「是、是吗……下次我会记住……不对，我会铭记在心。」

「突然变成讲敬语了⁉不过，我有点理解小雪乃的心情！」

雪之下惶恐地将托盘抱在胸前点头，由比滨迅速挺直背脊。

坐在对面的一色则吓到了。

「小米好可怕，根本是小姑嘛……这种事超麻烦的，我不喜欢……」

「呣……伊吕波学姊不用记也没关系吧？小町家对宝特瓶装的茶没有特别的坚持，哪一牌都没差！太好了呢！」

「不不不，茶我还是会泡的。啊，雪乃学姊，请问有热开水吗？我想给小米喝。」

「那只是烫死人的白开水吧！小町怕烫，请住手！」

小町拼命阻止伸手去拿热水壶的一色。

我无视玩得很开心的两人，拿起仍在冒烟的茶杯。

茶烫不烫，茶点是什么，我都不介意。

我家是我家，社办是社办。有只有这里才尝得到的味道。

我朝热呼呼的红茶吹气，小口啜饮，喀滋喀滋吃起煎饼。

「嗯，赞。茶和茶点都很赞，所以都可以啦……」

我轻轻吐出一口气，咕哝道，并肩坐在一起的雪之下和由比滨面面相觑，扬起嘴角。

「……『都可以』最让人伤脑筋了。」

「真的。」

她们轻笑出声，坐在对面的另外两位则开始窃窃私语。

「出现了，做作的台词……」

「哎，哥哥一直是那样……」

刚刚还吵得那么凶，现在却像要讲秘密似的，板着脸凑近对方讲起悄悄话，冷冷看着我。感觉怪别扭的，因此我跟打开报纸的昭和风父亲一样，打开补习班的招生简章。

「自闭男，那是什么？」

「刚才我去升学辅导室拿的。要看吗？」

由比滨疑惑地看着这边，我拿了几本简章给她，她便兴奋地翻起来。雪之下也从由比滨旁边探出头，沉吟着阅读上面的字句。

这方面的资料、简章，现在这个时代网路上要多少有多少，不过想跟其他人一起看、动手翻阅比较不同之处的话，纸本资料还是方便一些。

一色和小町也从对面伸手表示想看，我把简章沿着桌面滑过去。一色看了一眼，毫无干劲地说：

「喔，已经要准备考试啦。真辛苦——」

「你一副事不关己的态度……明年你也要烦恼这些事喔。」

听我这么说，隔壁传来非常严肃的声音。

「对呀～我现在也超烦恼的……」

我立刻望向旁边，由比滨面色凝重，低头看着简章，然后深深叹息。

「……我想做什么呢。」

「这问题好沉重……」

可是，嗯，会认真思考这一点，很符合由比滨的个性。像我就只想着考上哪里就去哪里……

由比滨板着脸呻吟，比较各家补习班的简章，雪之下大概是看不下去，温柔地对她说：

「选学校未必跟将来的志愿有直接关联，我觉得可以不用想那么多。」

「嗯、嗯……是没错……但我就是会烦恼嘛～」

由比滨「哇——」一声抱住雪之下。雪之下虽然在抱怨「好近……」还是拿出笔电敲着键盘搜寻起来。

「先从由比滨同学想念的大学和学院查起吧……」

她们俩肩并着肩，边讨论边调查大学的资讯，小町满意地看着这个画面，忽然转头看向一色。

「伊吕波学姊有想念的大学吗？」

「嗯……果然是有名的大学吧？『青学』或『上智』或『丽教』之类的？」

「喔喔～好厉害——！虽然你的讲法听起来脑袋很差，想念的都是很好的大学呢！」

「啊？我又不会在大学念书，跟脑袋好不好有什么关系？打扮得漂亮可爱更重要吧。」

「喔、喔……小町有点太小看伊吕波学姊了……夸张到这个地步，反而觉得这个人好帅喔……」

一色信心十足的宣言，令小町为之颤栗。呃，我也有点吓到。伊吕波真的全是单凭印象在说话……

不过，嗯，这个出发点倒也不算错。我每次去全家的时候都会想说要去念帝京平成大学，考驾照的时候要去报名驾照集训营WAO‼（注40）……那个广告真的超让人印象深刻……已经可以说是灌进大脑里不如说是阈下刺激等级差不多算洗脑了。

而旁边有个人受到了另一种洗脑。

「知名度，有名大学，打扮漂亮……」

「由比滨同学，别被扰乱了。踏踏实实地选择吧。住手，别去搜寻跨校社团和跨领域社团这些词，会害我非常不安。」

雪之下边说边从由比滨手中拿走笔电传给我。好，干得好，雪之下。我也非常担心由比滨未来会走上什么样的道路，所以我要马上把她打开的网页关掉！

我瞪向一色，叫她废话少说，一色清了下喉咙唬弄过去，将话题矛头指向小町。

「小米呢？你有想过要念哪所大学吗？」

「小町想等哥哥落榜后再决定！」

「咦……以我会落榜为前提……」

小町面带究极笑容，活力十足地摆出胜利姿势。过于坚定的宣言导致我垂下肩膀。不过啊，从兄姊的失败中学习是弟妹的特权。我就努力让自己的失败起到作用吧。

「哎，小町还有时间，船到桥头自然直啦……」

我带着淡淡的苦笑说道，由比滨和雪之下似乎也听见了我们的对话，点头附和。

「嗯，小町才高一嘛。还有很多时间可以玩！」

「我认为你该建议她念书比较对……」

由比滨激动地将双拳举到胸前，雪之下有点疲惫地叹了口气。

「先不说小町了，一色呢？你的成绩没问题吗？」

「我吗？喔，嗯。我打算走推荐入学……」

「喔——推荐入学。不错喔！」

「哼哼，我学生会长可不是白当的。小米要不要也以推荐入学为目标？毕竟你看起来很笨。」

「哇这个人怎么讲这种话人格真的有缺陷……可是推荐入学听起来很吸引人，小町现在决定要参选学生会长。小町会在今年的选举上击败你。」

「哈哈，我不觉得自己会输耶——」

「真期待今年的选举，呵呵呵。」

一色嗤之以鼻，小町露出意味深长的微笑。两人默默互瞪，接着，一色的笑容突然蒙上阴霾。

「……咦，等等？你不会真的跑去参选吧？要是学长他们站在小米那边，我会心碎的……」

「谁知道呢……对不对？哥哥？」

「学长，到底是怎样……」

小町带着甜美笑容用撒娇的语气呼唤我，一色的声音因不安而颤抖着，对我投以无助的眼神。

「哥哥♪」

小町刻意卖萌的天真声音，轻快得彷佛在跳舞，闪闪发光的双眼寄宿着全面的信赖，歪过头的动作像只用头蹭过来的小猫，使我觉得不能背叛这孩子的期待。

「学……长……」

一色形状姣好的饱满双唇，用类似炙热吐息的声音吐出断断续续的话语，水汪汪的大眼抬起视线凝视我。哀伤地揪紧胸前制服的动作如同祈祷，纤细修长的手指微微颤抖。

妹妹和学妹「你要站在谁那边？」的无言质问，已经可以说是压力。

不过，有别于从前方涌上的可爱压力的另一种压力自身边传来。

我往旁边偷瞄了一眼，雪之下跟由比滨面无表情地看着我。

「…………」

「…………」

不要不说话好不好？札幌雪祭的雪雕表情都没那么冰冷。

用膝盖想也知道怎么回答都不会有好事，所以我只能「啊哈哈」发出没有任何意义，只是用来填补沉默的干笑。

不晓得过了一秒还是两秒。抑或是永恒的时间。

在我即将于热情与冷静之间遭到抵消时，结束的时刻终于到来。

叩叩。

过了这么久，这间社办的门再度被人叩响。

敲门声令众人回过神来，面面相觑。接着望向门。

我趁机「呼啊啊啊啊啊啊啊啊」叹了一大口气。好险——还以为真的会断气……我的救命恩人到底是谁？我怀着感谢的心情往门口看过去。

然而，那扇门始终没有打开。我感到不解，这时门后又传来「叩，叩……」听起来参杂些许困惑的敲门声。

「小町，你要回答人家呀。」

「啊，好！请进——！门没锁——！」

小町大声呐喊，访客提心吊胆地打开门。

「打、打扰了……」

一名头发黑中带蓝的男学生用细不可闻的声音说道，慢慢踏进社办。

是川什么的同学的弟弟，川崎大志。

大志看了社办内部一眼，瞬间退缩。看来是被女性比例之高吓到了。他犹豫着要不要走进来，由比滨向他挥手，亲切地跟他打招呼。

「喔——是大志。好久不见——」

「请进。」

「啊，谢谢不好意思谢谢。」

雪之下催促他进到社办，大志难为情地搔着头和脸颊，频频低头致意，露出腼腆的笑容。

嗯——好啦，可爱的学姊亲切地跟自己挥手，会不小心做出那种反应，我可以理解。

是可以理解没错，但这跟那是两码子事……

你笑得那么爽干么？小心我跟你姊告状。可是要主动找川什么的同学说话难度太高了。没办法，放你一马吧。给我好好感谢我的社交力之低和你姊的恐怖指数。

我虽然放过了他，却有个人不肯放过他。

「他是谁呀？」

一色一脸纳闷，瞥了大志一眼，马上将视线移回我身上，语带怀疑地问。

「川崎大志。川崎的弟弟。」

「是喔……不对，我连川崎是谁都不知道。」

她拉长声音，用听起来毫无兴趣的语气回应，似乎压根没有印象。

「你看过好几次吧……办舞会的时候她在服装方面帮了很多忙。」

「啊——那个感觉很可怕的人……」

一色一回想起来就迅速移动椅子，跟大志拉开距离。君子不立于危墙之下。挺聪明的判断。因为弟弟被贬低的话，川什么的同学会真的生气喔！

然后，小町辛辛苦苦搬来一张折叠椅放在没人坐的地方。

「你先坐下吧。」

她拍拍椅子叫大志坐下，回到自己的座位上。

「谢谢你，比企谷同学……」

大志神情恍惚地道谢，紧接着似乎想到了什么，露出恍然大悟的表情，异常激动地说：

「啊，哥哥也在场，叫比企谷同学会搞混耶。是不是最好换个叫法？对吧？」

「咦？没关系啊不会搞混啊？放心啦。维持原样就好。你都叫哥哥『哥哥』呀。」

「……也对。」

大志灰心地坐到椅子上，肩膀垮了下来，跟最终回的丈一样燃烧殆尽。（注41）

由比滨心痛地看着他，「唔……」为之语塞，雪之下则轻声呢喃「……叫名字呀」，默默垂下视线。

她们的反应透出一丝同情及共鸣。

不不不，大志这种货色，要用名字叫小町还太早了啦。光之美少女都要花上八话的时间了（注42）。嗯，这种事要按照顺序来。到底要在什么样的时机改成叫名字比较适合？各位觉得呢？

一色无视为自己烦恼的我，将椅子移到小町旁边，讶异地附在她耳边问：

「小米，你认真的吗？」

小町愣了下，然后立刻露出得意的笑容，竖起大拇指。

「哼哼，当然呀。」

「哈哈，看不出是不是耶——」

听见一色的干笑，我们只能回以苦笑。哎呀，有时候真的搞不懂小町……

「小町，最好问一下人家的来意。」

「啊，对喔。」

听见雪之下的叮咛，小町突然面向大志。然后夸张地清了下嗓子，摆出源堂姿势，郑重其事地开口。

「咳咳……那么，请说。」

「没有啦，那个，不是什么重要的事，不如说我也没多烦恼，只不过，想跟大家商量一下……」

大志害羞地扭来扭去，边说边偷看小町。然而，因为他这个样子的关系，话题毫无进展。

小町沉吟着装出一副正经八百的态度，我却有点不耐烦。雪之下和由比滨也安分地听他说话，我忍不住开始抖脚。至于一色，她根本没参与对话，无聊地滑着手机。不时会笑一下，结果是在逛社群网站……这个在垃圾联谊上的垃圾女作为是怎么回事……

「其实我有点烦恼要加入哪个社团……想征求一些建议……你、你们觉得呢……」

在我闷闷不乐地心想「卡紧共啦……」时，大志终于进入正题。

「这样啊。去棒球社吧，棒球社。比起那点小事，去打棒球吧。好，决定了。」

「立刻回答⁉而且超随便‼」

「至少问一下他烦恼的理由……」

由比滨大吃一惊，雪之下一脸无奈。我也不是随便说的。

是经过审慎的思考才如此建议。

毕竟当上棒球选手就能跟声优结婚。机率远比轻小说家高。不如说轻小说家是最不可能的吧。连广播节目的脚本家都跟声优结婚了。我也想在年底宣布结婚。

我在脑内跟职棒新人选秀会缴交职业球员申请书时，认真听他说话的小町「呣——」了一声。

「你去体验入社过了吗？」

「呃，去了也有点搞不清楚……因为就算我问问题，对方也不会老实回答吧。表面上说『我们这边很轻松喔』，实际情况又没人知道……」

大志苦笑着望向我。直接跟小町说话，他似乎会紧张。我懂……

「姊姊开始去补习班上课了，所以我得帮忙照顾京华。这样的话，最好别选太严格的社团。不如说管比较松的……」

「……原来如此。」

大志已经转为和我交谈，结果变得得由我应声附和。

好吧，青春期的男生面对喜欢的女生和高年级美少女会紧张，也是无可奈何。他像要求救似地看着我，我自然无法置之不理。

不过，话虽如此，身为青春期男生，就算方法很迂回，果然还是会想展现自己的优点呢！

「我啊？也都上高中了嘛？觉得要多帮家里一些忙比较好。」

大志边说边偷看小町。言外之意是「怎么样？别看我这样，我考虑得很多喔？」。

小町点头听着那渺小又十分催泪的自我宣传，不久后用力点了下头，转身面向我。

「哥哥，这是那个对吧。」

「是那个没错。」

我们同时点头，四目相交，☆无言･嗯。（注43）

兄妹俩无视一头雾水的大志、雪之下、由比滨，擅自心灵相通，一色大概是觉得奇怪，终于提出疑问。

「『那个』是什么？」

「「四月病。」」

「没听过的疾病……」

「你家的《家庭的医学》特别厚呢……」

我和小町异口同声地说，由比滨露出参杂无奈的苦笑，雪之下以手按着太阳穴叹气。至于一色，她兴致缺缺地扔下一句「喔，是喔」，又彻底无视我们了。

只有大志目瞪口呆。没办法，说明一下吧……

「所谓的四月病，是国中生、高中生、大学生，或者社会人士，在进入新环境时太有干劲，开始做多余的事的疾病。『我已经是大人了……』像这样进行半吊子的意识改革，跑去学英文、写日记、去健身房等等，总之就是做起多余的事。」

我巨细靡遗地解释，由比滨「嗯——」皱着眉头，感到困惑。

「听起来没什么不好呀……」

「那些人可是抱持着『四月了所以来做点事吧』这种天真的想法喔。哪可能持续太久。结果就是冒出一堆不会碰的吉他或吃剩的蛋白粉……」

四月病的恐怖之处，在于事后依然会慢慢造成伤害，跟慢性毒一样。例如大扫除的时候，看见吉他、蛋白粉等梦想的残骸，会觉得「我什么事都做不好……」陷入自我厌恶之中。半途而废的梦想的一块碎片，会忽然伤到自己。其中日记的威力最大。偶……活……我的日记结束在这里。

然而，不会结束就是四月病的后遗症。

「只是自己一个人静静发病的话，小町是不会有意见啦，不过患者通常会『炫耀自己开始做某件事』，得意的方式很吵，身为家人必须说有点烦。」

小町表情超级严肃。咦咦……小町原来是这样想的吗……哥哥有点受到打击……

「不、不是……我没有，那种想法……那个，我以前，也有认真参加社团活动……虽然成绩马马虎虎而已……」

我望向讲话结巴的那人，大志整张脸都红了。

嗯，男生总会有一、两次那种经验吧。对不起喔？有种害你当众出糗的感觉。尽管称不上赎罪，我得更专注地倾听他的烦恼才行。

「你国中是什么社？」

从他刚刚那句话听得出，大志参加过社团。他都特地讲出来了，表示那对大志而言是挺重要的回忆吧。我询问这方面的资讯，大志迅速抬头，带着开朗的表情回答：

「软式网球！我们有打进县大赛喔！」

他顺便瞄向小町，不忘展现自己有多厉害。小町「喔～」随便拍手回应。好吧，大志打起精神就好。非常好。但我听见一个令人在意的词汇。

「……这样啊。那网球社就得排除了。」

「咦，为什么⁉」

大志完全搞不清楚状况。可是有疑问的人只有大志。其他人都理所当然似地点头赞成。

「啊——户冢学长……」

「户冢哥哥呀……」

「小彩的话就没办法了呢……」

一色一脸不耐，小町感慨地说，由比滨则快要抵达顿悟的境界。讨厌，我被放弃治疗了……但无论她们怎么想，我都不能让大志这种轻浮的家伙加入那个神圣的网球社。我想守护那个笑容……

然而，只有一个人没有感到疑惑，也没有点头赞成。

雪之下拨开垂落在肩膀上的长发，露出得意洋洋的笑容。

「我倒觉得有新社员加入，户冢同学会很开心喔？」

「呣，确、确实有可能……」

不愧是雪之下……完美命中我的弱点……不仅如此，她的攻势还丝毫没有减弱。

「要是他知道你破坏了获得新社员的机会，应该会十分悲伤吧……」

雪之下的语气变得更加沉痛，静静垂下目光。这个动作夸张得像在演戏，不过由雪之下这样的美人做出来还挺有模有样的，令人困扰。

而且，雪之下说得没错。这样我也不方便继续插手插嘴了。好啦，我还是会插几句话。

「不必担心。想个折衷方案，只要我现在去加入网球社，减一再加一，正负相抵等于零……」

可惜这句话也没能说到最后。

「比企谷同学。」

雪之下直盯着我。

脸颊微微泛红。嘴角绽放灿烂的笑容。轻轻张开好看的粉色双唇。

如同一朵华丽又温柔地盛开的花，对我说道：

「驳、回。」

我想也是。我知道，我讲爽的而已。不如说要是你没驳回，我还真不知道该怎么办。

「……好吧，跟户冢商量也不失为一个办法。虽然我想尽量避免用这招。」

我宣布投降，大志静静举手。好的，大志同学，请问有什么问题？

「那个，网球社很忙吗？」

「嗯——不知道耶。感觉练习得挺勤的。小彩午休时间也会去练习喔。」

「对啊，他超努力的。我邀他去玩，他也会说很忙，一直抽不出时间。」

尤其是最近这段时间，户冢好像因为要照顾体验入社的学生和拉新社员，忙得不可开交，没空出去玩。只要没有工作，我就能跟户冢玩到爽了……我恨，我恨工作。我恨截稿日。全是工作害的……我没有错，错的是工作。

可是，为何伊吕波歪着头，彷佛对此存疑？那种「是这样吗——我觉得不是耶——」的反应，是不是不太对？

思及此，一色摆出一副独自想通了什么的态度，开口说道：

「哎，没兴趣的人约自己的时候，大部分都会那样讲啦～『等事情处理好』、『最近很忙』、『我睡着了——学校见——』之类的。」

「只有你会干这种事吧……」

最后那个是怎样……是晚上八点左右被已读不回然后在隔天早上收到的LINE吗……明明传了问题过去，对方却对它只字不提，只是随便附上一个贴图搭配那句话，岂止是话题结束，根本不会再有机会跟对方传LINE……

绝对只有你会干这种事……我如此心想，扫了周遭一眼，所有人都神情凝重地沉吟着。

「咦咦……大家怎么都不说话……」

「有其他事要处理、有安排了……我的确会用这种理由……不，我是真的有其他安排，才会这样回绝对方……」

雪之下手放在嘴角，烦恼地说，由比滨苦笑着玩起头上的丸子。

「我、我不太常那样说啦，不过如果是要约我出去玩，我会说『好呀——！下次大家一起去吧——』……」

「啊——这理由真的超常用。」

小町点头笑着附和，我和大志却笑不出来。

「下次被这样拒绝，我真的会有点难过……」

「干脆直接拒绝都还比较好。」

我和大志初次产生连带感。让我们将其命名为羁绊……

在我为男人美丽的友情深受感动时，旁边传来的声音迎头浇下一桶冷水。

「你也很常说『有空我就去』呀。」

「对……那个真的很让人困扰，到底是要不要去……」

转头一看，不只雪之下，由比滨也不悦地噘起嘴巴。两个人加在一起，寒意也是两倍，已经不是冷水，而是液态氮。

「没有其他行程还要先拒绝对方一次，非常不可取。」

「嗯，反正你最后一定会去……」

雪之下和由比滨看着对方，歪过头「对吧——？」表示赞同。

然而，她们马上意识到不对劲，「……咦？」这次往反方向歪头。

「……由比滨同学，那是什么时候的事？」

「什么时候……」

经她这么一问，由比滨望向上方，张开嘴。但她很快就闭上嘴巴，双手伸向前猛挥。

「啊，没有啦没什么……嘿嘿嘿。」

由比滨收回前言，腼腆一笑，抚摸丸子头以掩饰害羞。

哈哈哈，是什么呢？有什么事吗？不过，她都说没有了。是说到底是什么。哪件事啊。在什么时候发生了什么事啊……

我内心无愧，也毫无头绪，可是轻轻用手指掩住嘴角，移开目光的由比滨那娇羞的表情，以及锐利如冰柱，却带有一丝忧伤的雪之下的眼神，导致我的胃发出悲鸣。

必须想点办法——我从内脏深处挤出自己想得到的所有解释。

「不是，误会，虽然我不知道是什么误会，总之一切都是误会。我也有真的不想赴约的时候。意即可以说是得等到当天早上观测过后才能确定答案的叠加态。这个道理在人称薛丁格的猫的思想实验中也得到了证明。」

「薛丁？那是什么？」

听见陌生的词汇，由比滨头上冒出问号，雪之下则沮丧地垂下头。

「……那个实验为什么要用猫呢？我很心痛。」

「因为猫会跳进盒子里嘛。」

小町随口安慰她，旁边的一色傻眼地看着我。

「好厉害的敷衍法……」

「哈哈哈你在说什么呢哈哈哈。」

我冷汗直冒，发出干笑，一色「嗯——」双臂环胸，看着下方不知道在想什么。

「所以之前那次也要保密啰。瞭解——☆」

「哈哈哈哈哈你在说什么呢哈哈哈哈哈哈我完全状况外耶哈哈哈哈呃我是真的不知道你在说什么耶？」

一色抛了个媚☆眼，做作地对我敬礼。接着迅速放下手，竖起食指放在唇前。轻轻「嘘——」了一声，微微眯起的两眼中闪烁着淘气的光，表情转为小恶魔般的笑容。

……糟糕。我开始觉得真的有什么了。真的不妙。雪之下和由比滨一直怀疑地看着我，情况非常不妙。连大志都带着「这家伙是怎样……」的表情注视我。男人的友情真短暂……

在我跌入绝望深渊时，对面的小町无奈地叹气。然后露出灿烂的笑容，面对一色。

「网球社的情况小町明白了，那足球社如何？很忙吗？」

干得好，小町！我也只能乘上这波巨浪了！我效法小町望向一色，一色边想边开口。

「练习量普普通通，不过要适应上下关系和跟学长相处，或许会有点累。」

「咦——好意外。足球社感觉不会有这种情况的说……」

由比滨惊讶地张大嘴巴，但我一点都不意外。

「不，我能理解。是那个对吧？叶山会温柔地对他说『大志，你觉得那样做对吗？』这种话对不对？那家伙明明不肯告诉人家正确答案，却总爱高高在上地发表意见，一副自己说了什么名言的态度。确实挺累的……」

「好严重的偏见！」

「不是，是经验。」

我冷静回答由比滨的谴责。

实际尝过一次那种滋味，就不会觉得那叫偏见了……我感慨地心想，雪之下喃喃说道：

「……跟姊姊一样的论述法。」

对对对，真的。我默默点头，一色见状，摆出一张臭脸。

「你们把叶山学长想成什么样子了……我说的不是他，是户部学长。」

「户部啊……户部就，嗯，呃，嗯……」

由比滨似乎想到了什么，移开目光，支吾其词。她真温柔……

「那个人超爱摆学长架子的……可能是多了学弟很开心，或是想装大哥吧，整个人跩到不行，自以为高人一等……」

可是，为什么伊吕波要说出来呢？还讲得很难听耶？

「啊——那种自大仔啊……」

小町一脸很懂的样子，随口附和。那什么啊迪士尼乐园的新游乐设施吗（注44）？太恐怖了吧……看，大志也吓到苦笑了……

「我对那种人有点……」

本想骂他「你这个现代的小鬼……」但我也对那种人有点……没资格说他。

「我觉得运动社团都会有类似的状况。走体育系路线的人，无论如何都无法逃避上下关系和纵向社会……这样的话，考虑文系社团如何？」

雪之下手抵着下巴，陷入沉思。可是，听见她的喃喃自语，一色却露出浅笑。

「……文系社团的那种文化更根深柢固喔。而且很多文系社团不分性别，所以更容易起争执。」

「那是你的亲身经验？哪个社啊？」

她的语气异常真实，超级恐怖，害我反射性询问。不过，一色只是面带微笑，一句话都不肯说。咦咦……好好奇……难道是我知道的社团……

我东想西想，跟我一样在思考的大志忽然开口。

「文系社团啊……那、那个，比、比企谷同学是侍奉社的吗？」

「嗯。不如说，小町是社长呀。」

「这样啊，哦……啊，那——」

大志的话讲到一半。不用听我都知道他接下来要说什么。

正因如此，我才打断了他。

「用不着那么急啦。再多考虑一下吧。那今天就此解散。我去上个厕所。」

「咦……」

我趁大家还在错愕时迅速从座位上站起来，活动肩膀，顺便朝大志用下巴指了下走廊。我的意图似乎正确传达到了，大志也连忙起身。

「那、那，我今天也先告辞了……」

「啊，嗯，再见！」

我和大志听着小町她们的道别从身后传来，走出社办。他应该不会想在喜欢的女性面前听我说教，我就稍微体贴他一下吧。

我们在走廊上走了一段时间，来到声音传不到社办的地方后，我转头面向大志。

「你真的打算加入这个社团？」

「……可以的话……从哥哥的角度来看，果然不赞成吗？」

大志搔搔头，害臊地笑着。

的确，对于接近小町的男人，我有话想说。以小町为目标企图加入侍奉社，万万不可饶恕。但这件事等下次再说好了。

「……先把小町的事放在一旁，这是我身为哥哥的经验。」

听见我的开场白，原本轻浮地笑着的大志表情瞬间一变。

看他这个反应，我在内心确信。

就是因为这样姊控才值得信赖。

他一定能理解我想表达什么。

「……弟弟用那种方式为自己顾虑，你姊不会高兴吧。」

「哈哈，姊姊应该真的会不开心。」

大志快活地笑了。不是刚才的害臊笑容，取而代之的是深深的爱情。

「不过，不是那样的。不是在顾虑姊姊，只是我想要报恩而已……而且，我觉得如果我加入的是这个社团，姊姊也会为我高兴。」

「啥？为什么？」

他一脸神清气爽，我对他投以充满疑心的视线。大志咧嘴露出讨厌的笑容，开玩笑似地用手肘轻轻撞我。这家伙好烦……

「讨厌——别逼我说出来嘛。哥哥。」

「别叫我哥哥小心我杀了你我说真的快滚之后再联络你。」

我没耐心继续应付大志，啧了一声，甩手赶走他，转过身去。大志对大剌剌地走向厕所的我呐喊：

「谢谢！麻烦了！」

爽朗的道谢声于身后响起，我举起一只手，不耐烦地挥了挥。

真是，就是因为这样姊控才不好处理……

我遵照我的宣言，上完厕所回到社办，三位女性正聊得不亦乐乎。

「可是，我有点能体会大志的想法。如果我有妹妹，应该也会考虑这些。好好喔……我也想要一个哥哥！」

「啊，我懂我懂。对独生子来说很令人向往呢。」

由比滨和一色兴奋地聊着，我随口应声，坐到自己的座位上，笑容满面的小町讲出一句很过分的话。

「小町不要哥哥，想要姊姊。真心的。」

「啊——姊姊好～可以互借衣服和化妆用品，一起出门逛街。」

「不错耶～衣服和化妆品等于半价～CP值超高的。」

「我觉得不太对……」

理由各不相同，不过大家都纷纷诉说对姊姊的向往。只不过，在场唯一有姊姊的雪之下，好像无法释然。

「是这样吗……我倒认为姊姊没有你们说的那么好。」

「不好意思，雪乃学姊家的那位没有参考价值，可以请你安静一下吗？」

「……这、这样呀。」

一色无情地说，雪之下垂下头。

伊吕波的意见我深有同感，讲得也没错，可是好歹换个说法吧？例如可以改成这样说。我清了下喉咙，示范给她看。

「嗯，那个人有点异常，不如说超出规格……不能一般而论。」

「对！没错。那个人有点异常。」

雪之下猛然抬头，展露微笑。不知为何还有点得意。

对喔，这家伙挺喜欢阳乃的……姊姊也喜欢这个妹妹。虽然她们的爱情都很扭曲，我完全无法理解……

正当我在思考雪之下姊妹的关系时，由比滨将话题抛给我。

「自闭男呢？你不会想要哥哥或姊姊吗？」

「不会。那可是我的哥哥和姊姊耶。肯定很那个。」

「这句话明明等于什么都没说，却带有惊人的说服力……」

我立刻回答，害雪之下吓到了。不用仔细说明对方也听得懂，好轻松喔，真棒……

「确实，哥哥的话搞不好会很那个……但我觉得自闭男和姊姊会处得不错耶……不如说，自闭男跟像大姊姊的人很合得来，嗯。」

由比滨不知为何挺起胸膛。呃，你用全身表现得像个大姊姊也没用……

我如此心想，雪之下在旁边抚摸柔顺的长发，露出比平常更加成熟的微笑。

「的确。你应该需要能容许你的废人度的包容力。」

「对对对，而且自闭男超爱我妈的！跟年纪大的人很合得来啦！」

「笨蛋你在说什么啊，全世界没人不喜欢那个人。大家都喜欢她啦你够了喔我说真的。」

「我因为莫名其妙的理由被骂得好惨⁉」

我当然会生气啊，我最喜欢比滨妈妈了。喜欢到无法坦率表达自己的心意，会忍不住避开人家。我正准备继续高谈阔论，眼角余光瞥见雪之下摆出理解一切的表情。

「要说合得来的话，我的母亲也不遑多让。你被她深深喜爱着。」

「可以不要用被动式吗？还有可以不要在这边公布新情报吗？」

我至今依然觉得雪妈很可怕喔。

小阳乃也满可怕的，最近我还重新认知到小雪乃果然也很可怕……哎，觉得可怕不代表不喜欢啦，但感觉好复杂。这是怕馒头理论吗（注45）？

我现在更怕一杯茶耶……我将手伸向茶杯，一色彷佛看准了这个时机，笑出声来。

「可是，学长喜欢年下吧～」

一色悠哉地喝着茶，雪之下思考起来。

「年上年下的定义是……」

「呃还能有什么定义不就比自己大或比自己小吗……」

这家伙在说什么啊……我感到不解，雪之下默默移开视线，用手梳理长发。黑发如同帘子般挡住她的脸。不过，从缝隙间可以窥见她微微泛红的脸颊。

「是、是吗……以出生年月日为基准的话……我姑且，也算比你小。」

……没这回事喔？

雪之下支支吾吾的，大概是在压抑羞耻的心情，像在试探似地说道，可惜没这回事。因为年上年下通常是以年级为基准区分喔？不管讲话的语气有多可爱，你跟我都是同年级喔？

好险好险。我差点觉得「的确！她或许算得上年下！」。再一下就要失去冷静了……然而，我的安心只维持了一瞬间，已经有人失去冷静了。

「看生日的话太那个了，那换成看那个呢？精神年龄！这样的话我觉得我比较低！自闭男就是哥哥了！」

「呃这理论不对吧。」

可惜我的声音似乎无法传达。由比滨正在反覆咀嚼自己刚才所说的话。

「哥、哥哥……哥哥啊……好像不错。」

她害羞地说，抚摸淡粉色的丸子头，露出幸福的微笑。修长的睫毛缓缓盖下，看起来十分柔软的脸颊笑容满面，红润的双唇反覆呢喃那个词。

她这样一直重复，搞得跟全家便利商店的店内广播一样，我不禁心想「……难道，我是哥哥？」摇头驱散这个念头。不，怎么想由比滨的精神年龄都比我大。你超成熟的喔……也可能是我太幼稚。

由比滨好像也发现不对劲了，猛然回神，睁开眼睛。

「啊，哥哥大概不行。」

她讲这句话是什么意思，我只能用推测的，但我刻意不去解释，而是讲出自己心中的原理原则。

「喔、喔……对、对啊……我不需要小町以外的妹妹……」

谢了，我的LIL SISTER（注46）。托你的福我才没失去理智。我用断断续续的声音述说的话语，想必十分诚恳。

坐在对面的小町用双手遮住嘴巴，眼泛泪光，感动得哭出声。

「哥哥……呜呜，虽然有点非常恶心，谢谢你。小町也只要一个哥哥就够了。不如说太多了，无法负担……」

「小米好过分……」

小町讲话过于恶毒，连一色都对我表示同情。当事人小町却满不在乎的样子。

「对妹妹来说，哥哥就是那样的存在啰。」

「的确。对妹妹来说，姊姊或许也是那样的存在。」

小町和雪之下看着对方，莞尔一笑。或许是只有妹妹才会产生的共鸣。彷佛在共享秘密的微笑，散发出旁人不容轻易介入的气氛。

「妹妹……果然很棒……」

「是吗？你有妹妹的话属性会跟我重复吧？年下多到要塞车啰？」

由比滨带着充满无限憧憬的眼神凝视两人，一色则在看着她们杞人忧天。呃，真的是杞人忧天……放心啦，伊吕波是Only one……顺带一提，我家的小町是妹系角色的Number one！（据我调查）

「啊，小町想到一件事，可以说吗？」

「当然。你是社长呀，小町。」

雪之下呼唤她的声音中，带有对她的信赖，小町高兴地抖了一下，不停点头。呆毛随着她的动作晃动。

「那么，现在开始召开作战会议，请大家把耳朵借小町一下……」

小町刻意对我们招手。这间社办里面就只有我们几个，她却想讲悄悄话的样子……好吧，这样比较有作战会议的味道。我们面面相觑，不禁苦笑，向前凑过去听小町所说的计划。

不过，由于大家都凑在一起，吹在耳朵上的气和搔弄鼻尖的甜美香气害我心神不宁，重要的计划只听进一半左右。

作战会议在我左耳进右耳出的过程中结束。

糟糕，没问题吗……我不安地望向其他人，除了我以外，大家似乎都有听进去。那我就放心了。剩下两位社员应该会帮忙看着，安啦！

「……原来如此。这手段很符合你的作风。」

雪之下静静点头，小町略显害羞地搔着脸颊。

「是吗？」

「是呀。不是明确的解决方案，却会让人心情轻松一些的温柔做法。」

「嗯。我觉得很棒！」

由比滨也微笑着抚摸小町的头。得到她们俩的称赞，小町看起来既高兴又有些难为情。

「不错啊……虽然我不是社员，跟我没关系。」

一色有点像在闹别扭，但她对于作战计划并无不满的样子。她轮流瞄了下我和小町，扬起嘴角。

「……你果然跟学长很像。」

「不，一点都不像。」

小町挥挥手，认真回答。

咦咦……好顽固……你就承认我们两个很像不就行了吗……

隔天放学后，我和小町在去社办前先绕到正门口一趟。

委托人川崎大志也在旁边。大志不安地往校门外瞄来瞄去，频频叹气。可以理解他会担心。

毕竟我们没有详细的计划。小町提出的策略单纯至极。要说多单纯，单纯到可以用「THE 小町」当名字做为Simple系列发售的地步。（注47）

因此，只要最少的人力便足矣。我和小町就够了。当然也是因为顾虑到人少一点，对方应该会比较愿意开口。我们即将面对的人不好应付，难以预测对方会有什么样的反应。至少我大概没办法进行正常的交涉。

负责交涉的小町却并未特别担心。她唱着「还没到吗还没到吗——」望向校外，从容不迫，不仅如此，好像还在盼望对方的到来。

不久后，那名交涉对象抵达了赴约地点。

黑中带蓝的长发用发圈绑成马尾，慢慢摇晃，两根小辫子以慢了一拍的节奏，在空中轻快地弹来弹去。

是川崎沙希和她的妹妹，川崎京华。

看见我们的瞬间，京华挥着手小跑步冲过来。

「小町——！」

「京华——！」

小町温柔抱住京华，揉着她的头。京华害臊得眯起眼睛，心情看起来非常好，川崎则相当困惑。

「你们叫我把京华带过来，所以我照做了，不过……那个，现在是要干么……」

她八成是没搞清楚状况，就被大志叫出来了。川崎看着我和小町跟大志，眉毛垂成八字形。好吧，事已至此，跟她说明清楚会比较快。

「喔，抱歉。大志在烦恼要加入哪个社团。你想想，我们这边也有很多事吧？所以……」

「啊——！停停停，哥哥！你在说什么啊！」

大志嚷嚷着试图打断我说话，介入我和川崎之间，接着对我投以谴责的目光。呃，你又没叫我保密……

而且，恐怕用不着我说。

「……你不必担心那种事。」

川崎眉头紧皱，噘起嘴巴，语气却很温柔。看来在我说明前，她就察觉到大致的情况了。

「呃，可是……」

被她用温柔却带有一丝悲伤的眼神凝视，导致大志语无伦次，讲到一半的话也消失在口中。

「……可是，身为弟弟妹妹，还是会担心嘛。」

帮他接下去说的是小町。大志用力点头赞同。

「啊，嗯。我懂……但那是我该负责的……」

川崎有点困扰地解释，小町对此一笑置之。

「……所以，小町想尊重弟弟妹妹的意见。」

小町蹲下来，和京华视线持平。川崎和大志同时面露疑惑。然而，没什么好奇怪的。

小町的交涉对象，打从一开始就是京华。

「京华，跟你说喔。姊姊之后会有一点忙，可能会没时间去接你。在家的时候能一起玩的时间说不定也会变少。」

再怎么费尽唇舌跟年幼的京华说明，也不知道她能理解多少。

但不能因为这样就不告诉她。更重要的是，不能因为对方年纪还小就无视她的意愿。

小町委婉地告诉她，京华眨了两、三下眼睛，点点头。

「这样呀……」

她的大眼浮现困惑及悲伤，不久后泛起泪光。川崎见状，露出忧郁的神情，伸手想拥抱京华。

在那之前，小町先紧紧抱住京华。

「可是，大志或许会代替姊姊陪你喔！」

接着用俏皮、愉悦、轻快的语气说道，京华也笑了出来。然后不知道在模仿谁，挺起胸膛，故作成熟地说：

「志志啊……嗯，好吧，没办法。」

「咦？没办法……咦？……京华讨厌哥哥吗？」

大志声音打颤，京华瞥了他一眼，冷淡地回答：

「普通。」

「普通……这、这样啊。不是讨厌就好……」

「你真乐观……」

「啊，那个，我觉得京京挺喜欢大志的……」

川崎有点慌张地帮忙说话，小町听了笑出声来。

「是啦。开不了口说喜欢对不对？因为哥哥有一堆缺点。」

「我懂——！小町也是吗？」

「嗯，对呀——从来不打扫也不会帮忙整理家里，心血来潮却会突然清起地毯上的毛发，真的有够烦。」

「真的。男人明明很龟毛，却一点都不贴心。」

小町语气温柔，讲出来的话却颇为毒舌。另一方面，京华的语气虽然像在装大人，她说的搞不好是正确的。川崎默默点头。

之后她们仍然继续抱怨。我和大志一同垂下肩膀反省，小町的语气忽然趋于和缓。

「……不过，偶尔也会觉得哥哥不错啦。我们啊——会一起看光之美少女喔。」

「喔——恩典天使……」

「对对对。然后一起模仿她们玩。」

小町说出这句话的瞬间，川崎惊恐地看着我。

「你在做什么……」

「没有啦，那个，是以前的事……」

我辩解的瞬间，京华充满活力的声音响起。

「我也会喔！跟沙沙一起！对不对？」

忽然被提到的川崎因为过度羞耻，用手遮住脸。呃，没关系啦，我明白……你是个好姊姊……自然会愿意模仿光之美少女……

我备感温馨地看着川崎和京华，我家的光之美少女轻轻咳了一声。噢，糟糕，作战计划被我忘得一干二净……我也咳了一声表示瞭解。

大军师比企谷小町的计策即将揭晓。It’s Party Time！

「我哥很厉害喔。会教我念书，跟我一起做菜，还会帮助遇到麻烦的人……挺帅的。」

「京华的哥哥也是！京华的哥哥也很厉害！跟你说，志志很会打网球喔。超帅的。」

这是兵法三十六计之一的「无中生有」。又名炫耀哥哥大赛。

把哥哥压根不存在的优点讲得跟真的一样，从京华口中问出哥哥的长处……竟然想得出如此愉悦的计策，那家伙是派对咖军师（注48）对吧？

「这样啊。不错呀。很帅。」

「嗯！京华喜欢帅气的志志喔？」

小町微笑着望向这边，京华也跟着看过来。映入眼帘的是妹妹最可爱的笑容。俨然是两朵绽放的花。

「咦，喔、喔喔……」

大志已经连话都讲不清楚，感动到哭出来。那么，再推他一把就是我的工作了。

「……你也听见了。让妹妹看见自己帅气的一面，也是好哥哥的任务喔。」

我在真正意义上推了他一把，大志摇摇晃晃朝京华踏出一步。只不过，仅存的理智令他忍不住回头。

「呃、呃，可是这样对姊姊不太好意思……」

呣。还差一步吗……好，那么就来收尾吧。

「有什么关系。你姊这么努力，应该也是想表现给弟弟跟妹妹看。」

「喂、喂……！」

川崎连忙抓住我的肩膀，想要阻止我，却没有否认。光是这样，对大志来说就够了。他搔着鼻头，「嘿嘿！」笑了下。

「……我，要打进全国大赛。」

接着万分帅气地宣言，冲向京华。

哎，网球社的话，只要跟户冢商量总会有办法吧。他一定会帮忙找出最适合大志的折衷方案。尽管把事情都丢给他不太好意思，总之任务达成了。

这个解决方式绝对称不上好。问题应该也没有排除。

不过，这个帮助人的办法很有小町的风格。雪之下说得没错。

我松了口气，小町小步走过来对川崎说：

「沙希姊姊，如果你在兄妹关系方面遇到什么问题，请来找小町！因为小町是专业的妹妹。放马过来！虽然小町不确定扯到别人家的事，小町能负责到什么地步！」

「什么嘛，你太诚实了。不过……嗯，有事我会考虑来找你……谢谢。」

小町讲得太直接，导致川崎露出苦笑，最后转为温柔的微笑。她小声跟我们道别，轻轻挥手，走到大志和京华身边。

我们目送并肩而行的川崎姊弟妹逐渐走远，小町突然咕哝道：

「……帅气的哥哥真好。小町有点向往。」

「这样讲听起来好像我一点都不帅。」

「小町是这个意思没错……哥哥身上哪里有帅气要素呢……」

她一脸失落，我故意做出帅气的表情。

「只要闭上眼睛和嘴巴，我的脸还算能看吧。」

小町努力从各个角度端详我的脸，不久后死心地垂下肩膀。

「哥哥太信赖心眼了吧……就算有小町这双眼睛也看不穿……」

「哈哈哈，修行不足喔……主要是我修行不足。」

「真的……那回社办吧。」

小町转身走向校舍。穿过正门时，她的脚步转为哼着歌的小跳步。

「……好啦，之后我会让你见识哥哥帅气的一面。毕竟我们还会在一起一年。」

小町跑上通往大门口的大楼梯，我对她的背影说道，慢慢跟在后面。

操之过急就太可惜了。因为这是我和小町在同一所学校度过的最后一年。让我好好享受，直到厌倦为止吧。

我稳稳地一步步走上楼梯，终于追上小町，她在最上层转过身，裙摆于空中飞扬。

「不是一年，是一辈子……所以，要一直让小町看见哥哥帅气的一面喔。」

语毕，小町按住随风飘逸的头发，脸上浮现成熟的微笑。连跟她相处十五年的我都从未见过的美丽姿势，害我不小心看得出神。

「……开玩笑的啦，刚才那句话小町觉得分数很高喔！」

才刚这么想，她就俏皮地用双手在脸颊旁边摆出横着的V字手势，展露灿烂的笑容。

直到厌倦为止？说什么蠢话。怎么可能厌倦。想好好享受的话，我的人生还嫌太短呢。一辈子都不够。

我看，果然只要有妹妹就好了……对吧？

完

** 后记

后记（伊达康）

各位好，我是伊达康。

这次我在《果然我的青春恋爱喜剧搞错了。》的短篇小说集中，写了材木座的故事！

我从来没想过自己能有这个机会参加，感到荣幸之余也觉得很紧张。某种意义上来说，我投注了比写自己的作品时更多的干劲……大家还喜欢吗？

写这篇的时候，我在文库本里有材木座出场的地方贴上便条纸，重点式地重看那些段落，重新加深了对材木座义辉的感情。便条纸这种东西，我连课本和参考书都没贴过呢。

但愿能为大家多少带来一些欢乐。

尤其是各位材木座粉，我衷心祈祷不会遭到「我的义辉才不是这样！」「少看不起材木座宝贝了！」「我不承认这样的材材！」之类的批评。

最后，《果青》完结真的辛苦了。

在此对写出这部经典大作的渡航老师，致上深深的敬意——

伊达康

后记（田中罗密欧）

恭喜果错（我专用的简称）完结。

本篇完结后的短篇集真不错。我也写了两篇短篇庆祝完结。短篇小说集好像共有四本，应该会收录在不同集吧？希望各位看得开心。

话说回来，本作的主角八幡非常喜欢吃拉面，我对定食的热情跟他一样。

开拓个人餐饮店也很好，但由于地理位置的关系，我满常吃弥生轩的。在高圆寺一带的时尚咖啡厅常见的把面包、生菜、腌黄瓜等馅料放在大盘子上，叫人自己组合起来的汉堡，对于我这个会大骂「给我端成品上桌啊！」为此感到愤慨的难搞中年男性而言，定食才是完美无缺的经典外食选择。

弥生轩我推荐茄子味噌和烤鱼定食。唯一的选择。

茄子味噌就够美味了，还附带烤鱼和冷豆腐，连免费的腌渍物都有，再多碗饭都不够配。值得高兴的是，弥生轩的白饭不用钱。希望各位至少吃三碗，把吃太多饭会想睡的我的份也一起吃下去（包括女性）。放心。配菜的量很够。

对于去十次弥生轩，九次都会点茄子味噌的我而言，弥生轩等于是「茄子味噌和烤鱼定食轩」。

田中罗密欧

后记（天津向）

各位好，我是天津向。这次有幸参加《果青短篇小说集》，真的十分感激。谢谢各位的阅读。

接获邀约时，我最先想到的就是这篇平冢老师跟八幡的故事。

我很喜欢平冢老师，喜欢到快发疯的地步。因此我愈写愈开心，写到最后甚至在自言自语「我不是天津向。我是比企谷八幡。而八幡真正的幸福结局是和平冢老师在一起」。

哎呀——根本是可疑人士。

所以该怎么说呢，我笔下的平冢老师充满我个人「希望她这样」的愿望，或许会有不像本传的平冢老师的部分。

对不起。请原谅我。但那是我的愿望，请原谅我。

我还写了「雪之下雪乃篇」和「川崎沙希篇」。这两篇我也写得很愉快，请各位务必看一下。

有这样的机会，都要多亏GAGAGA文库的编辑们，更重要的是渡航老师。真的感激不尽。

天津向

后记(丸户史明）

各位好，我是丸户史明。

我跟渡航老师在某部动画的BD特典短篇小说集中合作过，很荣幸这次有这个机会……呃，起初接获邀约时，我哭着跟他说「不不不你的作品的粉丝统统很恐——统统是具有文学素养的人所以像我这种娱乐小说作家会怕啊！」却回绝不了，导致我玷污了末座。

不过啊，在我百般抱怨之下，好不容易取得了主要角色的选择权，最后写出这么一篇不知道谁看了会高兴的短篇小说。

这也是因为我是（身为男性）不太守规矩的读者，从这部作品的第一集开始，最关注的角色就是这篇小说的主角叶山隼人。

所以第四集的那一段和第六集的那一段，我也看得很兴奋……在那之后，不晓得是不是因为他的立场太接近核心，作者似乎也有许多顾虑，他讲话变得非常爱绕圈子、充满谜团，导致我陷入妄想爆发、痛苦不堪的恶性循环……可是那不重要吧因为我比作者还要早一年交稿（禁句）。

托他的福，校稿时我不得不补上「现在连平成都结束啰」这一句你要怎么补偿我真是的……

丸户史明

谢辞（渡航）

白鸟士郎老师、伊达康老师、田中罗密欧老师、天津向老师、丸户史明老师。谢谢。收到各位的作品，各种情绪于我心中交织在一起。

一言以蔽之，就是多幸感。

うかみ老师、しらび老师、红绪老师、户部淑老师。

每次看见各位的图，我都心跳不已，被揪心甜蜜的幸福感笼罩。这已经超越恋爱了。连爱都无法形容的满心谢意及感情on Parade了。真的十分感谢。

Ponkan⑧神。谢谢神。3Q神。感谢神。请多指教神。

责编星野大人。谢谢您！放心，下次一定能轻松搞定啦！呵哈哈！

GAGAGA编辑部的各位，以及同样提供诸多协助的各家出版社，十分感谢各位向各作家、插画家邀稿，协助编纂本书。

在此致上深深的谢意。

以及各位读者。如同这个短篇小说集企划，果青的世界依然在继续扩展，都是多亏大家的支持。

多亏有你拿起这部作品阅读，我才会至今仍在写作。真的满怀感激。谢谢。因为有你，才有果青的存在！

接下来让我们在《果然我的青春恋爱喜剧搞错了。短篇小说集3 结衣side》见面吧！

二月某日 字数MAX页数MAX手中的罐装咖啡也是MAX

渡航