#+title: 我的青春恋爱物语果然有问题 短篇集4 allstars
#+setupfile: ./setup.setup
* 短篇集4 allstars

** 即使我们的青春恋爱喜剧搞错了。

台版 转自 深夜读书会

发布：深夜读书会

论坛：ritdon.com

作者：石川博品／插画：エナミカツミ

穿过闸门后，我自然而然走向车站一楼的书店。

以前在同一栋大楼二楼的补习班上课时，我总是会在上课前绕去这家书店。尽管我现在只有盂兰盆节和新年会回老家，身体仍旧记得当时的习惯。

这家书店当然跟东京的大书店没办法比，可是对高中时期的我而言，已经够大间了。我常梦想能把架上的书全买下来。

凭微薄的零用钱该买哪本书才好，需要询问内心的深处才能做出决定。喜欢看书的人大多会自我省思，原因或许就在于此。

我走到轻小说区一看，去年十一月出的《果青》十四集铺在平台。

第一集就是在这里买的，我记得很清楚——连那一天是二○一一年三月二十一日都记得。

根据纪录，东日本大震灾时，这里的最大震度是五级。地震害这家店的书全毁了，因此休业了几天，三月二十一日才重新开店。记得《果青》好像也是因为震灾的关系才延期发售。

基于些许的好奇心，我来到书店，站在轻小说专区前，那本书的封面映入眼帘。这个黑色长发的女生就是女主角吧。看起来挺清纯可爱的。旁边眼神凶恶的男生应该是男主角。书名是……「青春恋爱喜剧」「搞错了」是什么意思？我翻到封底阅读大纲。主角叫八幡啊。女主角叫雪乃……不晓得八幡是姓氏还名字。

看来是部创新的校园恋爱喜剧。是我喜欢的类型。主角是边缘人这一点也很赞。有能跟主角产生共鸣的部分，会是我决定购买一本书的原因。

我翻开彩页。是有点傲娇味的结衣和偏男孩子气的彩加。两个人都好可爱。

正文前面是八幡写的作文。大略扫过一眼，感觉是个难搞的人。

我暂时放下那本书，看了下其他新作，结果还是买了这部最先看见的作品——没想到未来会跟它相处将近九年的时间。

我之所以在借她《果青》第一集的时候附上一封信，是因为我深深着迷于这个以八幡的作文为起头的故事。虽然我的文笔没好到能重现那独特的乖僻个性。

我写这封信的原因，是想告诉你我有多喜欢《果然我的青春恋爱喜剧搞错了。》这部作品。

我口才不好，在你面前一定无法仔细说明这部作品的好看之处。

这个故事的主角——比企谷八幡是边缘人。但他并不会因此表现得低人一等（即使其他人把他骂得跟什么一样）。

他说他想证明「边缘人不可怜」、「边缘人不比别人差」。同为边缘人，我觉得他很帅。

女主角雪之下雪乃也是边缘人。她以自己的美貌及才华为傲，是个看似正宫，却像个反派的角色。

他们两个都很毒舌，却始终走在自己的道路上。我就是喜欢这一点。

记得去年你主动跟我搭话的那一天吗？

我坐在自己的座位上看轻小说，你跟我说「那部作品很有趣」，然后我们就聊轻小说聊了一段时间。

那本书是我跟哥哥借来的。好看归好看，对我而言仅仅是「哥哥的书」。

我想要「自己的书」。追着进度看，期待出下一集的书。

《果然我的～》（太长所以省略掉）书名后面没有写集数，作者后记也说不定会有后续，希望可以继续出。

出了第二集我再借你看。

希望到时你已经出院了。

公车抵达圆环。天气很冷，所以我在车站大楼内待到最后一刻才上车。

以前去高中的时候和去站前补习班的时候，我都是骑脚踏车，所以搭公车从车站回家，使我有种堕落的感觉。当时我明明没有目的地，还会骑脚踏车在刮强风的河边飙车。

公车开在县道上南下。窗外是综合医院的大楼。

升上高二的第一节班会，我得知她住院了。班导只有告诉我们这个事实，是什么疾病则一字未提。

之后，我花了三天写完两张信纸的信，骑脚踏车飙到综合医院。如今回想起来，想找人分享《果青》感想的心情，似乎比想为卧病在床的她排解无聊的心情更加强烈。

她的病房是六人房，用米色窗帘明确地隔开每位病患的空间。

我打了声招呼，拉开窗帘，她就坐在里面。

「杉元同学？你来啦。」

盐原真夏是个朴素乖巧的女生，像《果青》里面的海老名同学再去掉腐要素，现在她看见我，却露出灿烂的笑容。

病房的个人空间光线不足，只有外面的灯光隔着窗帘上面的蕾丝照进来。床边有个附抽屉的矮柜。她的眼镜折起来放在上面。小电视和阅读灯设计成可以靠机械手臂个别移动。剩下的空间狭窄到只能供一个人勉强通过，而坐在椅子上的宇都宫堵住了那条路。

隔壁班的宇都宫是个隶属于不良团体的女生。长得像去掉卷卷头的三浦优美子和川什么的同学的综合版。

她好像带了饼干来探病，正拿在手中吃。

「医院里面可以吃零食吗？」

我询问盐原，宇都宫也看向她。

「咦？不行吗？」

「本来就不能带食物进病房。」

盐原的语气带有几分调侃的意味。

「真假。早说嘛。」

宇都宫将饼干扔进嘴巴。

我觉得不太自在。进来后一步也动不了的狭窄空间、其他住院病患的咳嗽声、病床发出的吱嘎声、盐原和宇都宫意外亲密的举动，都令我喘不过气。

「那个，这本书，借你看。有兴趣的话可以拿来打发时间。」

我将书连同书店的塑胶袋递出去。如果没用袋子装，连跟书放在一起的信都会被宇都宫看见。

「谢谢。」

她笑着接过袋子，想窥探里面的东西。感到难为情的我急忙转身离开。

「喂。」

有人从背后叫住我。

转头一看，宇都宫抓了几包饼干拿给我。

「你叫杉元是吗？给你。这里不能放食物。」

「谢、谢谢……」

我藉由奇怪的物物交换得到饼干，离开病房。

第二集在暑假前夕出了。

考虑到之后的出书间隔，四个月已经撑得上短，可是我当时迫不及待看到下一集，觉得这段时间相当漫长。

而她还在住院。

期待已久的《果青》（粉丝好像都是这样简称）第二集出了。

这次，侍奉社正式开始运作，对外采取许多行动。看着书中世界逐渐扩展开来，令人兴奋不已。

你喜欢的材木座也很活跃喔。

结尾的部分写到雪之下就算不被任何人理解，依然没有放弃，而由比滨从来不放弃理解别人，这一段我印象深刻。我大概是不属于任何一方的半吊子。但我也没像八幡那样放弃希望。

侍奉社三人组性格极端，可能是因为这样，他们才那么有魅力。

这一集的最后，我感觉到他们的关系会变得愈来愈复杂。期待下集。

我家位在外观类似待售屋林立的街区。以前我还觉得家里很寒酸，不过以我的薪水，一辈子都盖不了同样大小的房子吧。

父亲在门口迎接我，母亲在厨房做散寿司。要吃大餐的时候一直都是这样。

「你要去盐原同学家对吧？」

「下午再去。」

我爬上二楼，走进自己的房间。搬家时留在这边的轻小说，仍旧在书架上互相较量书背的鲜艳程度。我坐到床上，松开领带。

在她的病房中，我从来没坐过那张床。

「我得的病叫恶性淋巴瘤。」

某一天，她这么告诉我，语气彷佛在聊喜欢的音乐家。

「那是怎样的病？」

「好像是血液里的淋巴球变成癌细胞了。」

我一句话都没说，只有点了下头。

她在接受化疗的过程中，失去了美丽的长发。头上的薄毛线帽在这个季节显得有点闷热。

病房又小又暗，戴不习惯的口罩让人觉得很闷，闷到不能讲太久的话，如果要聊喜欢的书，写信最适合。

第三集有约会（？），有战斗（？），内容十分丰富。剧情很有梗，颇符合这部作品的风格，不过还算满「青春恋爱喜剧」的吧。

结衣对八幡的好感满明显的，可是，小雪乃又如何呢？她对猫的好感倒是很明显。

这样「谁才是正宫」这个问题就浮上台面了。我在第一封信上说小雪乃是正宫，是根据「第一集封面的角色是正宫」这个法则判断的，可是我开始不确定《果青》适不适用这个法则。或许是因为主角八幡一直在回避那类型的恋爱喜剧要素。即使如此，他还是会被牵扯进恋爱喜剧之中，老实说我好羡慕。我最近想要小町那样的妹妹（笑）。

你喜欢的材木座这次也好燃。超越燃变成烦的地步。

他那句「因为喜欢才想成为作家」宣言感动到我了。

我也想试着将自己的心意说出口。虽然我的「喜欢」跟「成为」无关。

吃完午餐，我走出家门。

搭上通往车站的公车，看到有五个穿着母校运动服的女生占据了最后面的位子。看那个包包，应该是软式网球社。时值冬天，她们却全都晒得皮肤黝黑。不晓得现在的学生是不是还会在正门前的坡道跑步练习。

《果青》第四集跟第一集一样，于三月发售。

都要升高三了，她依然没回学校上课。

这一集是暑假的故事。反观我们连第一学期都还没开始，书中的时间过得真快。

不过他们还只是高二生，或许该说我们的时间过得比较快才对。

叶山一直在讲意味深长的台词。本以为他跟三浦一样是反派角色（？），看来他是个意外重要的角色。他以前好像经历过什么事件。

我的人生平凡无奇，没有黑暗的过去这种东西。所以我有点向往。

最后八幡选的解决方案虽然很糟，我觉得那样就行了。八幡说过「改变自己，即可改变世界——这种说法是骗人的」，我也这么认为。我也有想毁灭世界的时候，像他那样。

但我是个凡人，做不到那种事。

「杉元同学是边缘人呀？」

盐原坐在床边，晃着双腿问我。光溜溜的脚尖快要碰到我了，因此我把椅子往后拉了些。椅子在地上摩擦的声音于病房内响起。

「《果青》的读者全是边缘人吧。」

「是吗？」

「不知道。说全是我太夸大了。」

她笑了出来。身体状况看起来非常好。

她脱下披在睡衣外面的开襟衫，放到枕头旁边。她之前说过，穿前开式的衣服比较好，以便看诊时脱掉。架子上的手机的通知灯在闪烁。她拿起旁边的宝特瓶喝水。什么东西都放在她构得到的范围内。

电视在播公方公园桃花祭的VTR。

「我本来每年都会去参加，加上今年已经连续两年没去了。」

她戴上眼镜盯着电视。昏暗的病房中，她淡淡的影子映在窗帘上。几根头发从毛线帽底下露出。

「我长大后就没去过了。」

男高中生不可能理解桃花这种朴素的花的魅力。可是当时我觉得，跟她一起看的花一定很美。世上美丽的事物就是为了和心爱之人一起看而存在的。

好看的书亦然。

不晓得我是先喜欢上《果青》还是先喜欢上她。至今我依然无法分辨。

坐在教室里的座位上时，坐在容易发出吱嘎声的补习班的座位上时，趁读书的空档躺在床上时，阅读《果青》时，我总是在想她。

她出院了。

「骑脚踏车出去晃晃吧。」

我之前提过我会沿着河边的道路骑脚踏车，因此她这么提议。

「那去滞洪池好了。」

那一天是晴天，不过因为梅雨季延长的关系，风中带有水气。在雨水的灌溉下长高的杂草被风吹得窸窣作响，我们低头看着河岸，骑在河堤上的道路。

她似乎很喜欢装在我的越野脚踏车上的拨链器，不停换档，把它弄得喀嚓喀嚓响。从短裤底下伸出来的双腿，白得像在拒绝阳光。膝盖的骨头明显凸起，彷佛周围的肉都被挖掉了。

风拨乱她的头发。她的头发还有点短，发型跟八幡类似。

「好累喔～该多运动了。」

我们坐在能看见滞洪池的人工湖的长椅上。她直接对着瓶口灌下运动饮料，叹了口气。虽然附近也有自行车道，我们都骑脚踏车骑到这里了，决定稍微休息。

这个地方因为人工湖是心形，被拿来当约会胜地的卖点，但我不知道有没有效。从我们所在的位置看过去，就只是平凡无奇的辽阔湖面，隐约看得见对岸的景色。

「你决定要考哪所大学了吗？」

「嗯。」

我讲了几所东京的大学。

「考上的话你要一个人住？」

「我是很想啦，不过家人叫我通勤上学。」

「我想也是。毕竟一小时就能到新宿了。」

「八幡上大学后应该也是通勤吧。」

「他看起来就是不想搬出去住的类型。」

「小雪乃才高中就一个人住了，真了不起。」

「她感觉会把自己照顾得很好。」

我竟然在跟她聊这个，挺不可思议的。我们不久前还跟八幡他们一样，在度过高二的暑假。真不敢相信高三生的「决定未来的夏天」马上就要来临。

她拿下眼镜揉眼睛。骑脚踏车的期间，风一直迎面吹来，所以她的眼睛红通通的。

「我决定放弃明年的大考。因为以现在的状况来说我准备不足。」

「这样啊。」

我不知道该怎么回答，学她揉起眼睛。

「可是我一定会去念大学。」

「嗯。」

「好想三年就从高中毕业喔。我真的无法接受小我一岁的人不用敬语跟我说话。上大学我应该就不会介意了。」

「我懂。」

风吹过湖面，为汗涔涔的我们带来一阵凉意。

第五集一样是暑假的故事。这次在七月出版，时间刚好对上。

这一集写到八幡和好几位角色的互动，本以为是走轻松向，最后却有大魔王在等待着我。

雪之下阳乃第三集也有一些戏分。我当时对她的印象是阳光的姊系角色，看来有点出入。

我不太喜欢她。她会为周围带来变化。害有着一双死鱼眼，开口闭口都是扭曲言论的八幡，变成无害的小弟弟。害身为孤高存在的小雪乃，变成比不上姊姊的弱女子。害懂得察言观色，一下子就融入侍奉社的比滨同学，变成单纯的外人。

企图拆散逐渐加深羁绊的三人。

我明白故事往往会产生变化。起承转合、序破急之类的，也明白少了这些会变成无聊的故事。可是，我想再多看一下八幡、小雪乃、比滨同学在侍奉社社办闲聊的样子。

八幡说「如果我们不改变，便不会产生悲伤」。我害怕变化。你说得对，我是边缘人。不过我喜欢在热闹的下课时间，待在教室一个人看书。喜欢在补习班下课后，骑脚踏车于昏暗的街道上狂飙。喜欢跟你聊《果青》的感想。

我希望现状不要有任何变化。

有点害怕看到下一集。

暑假期间，她又住进医院了。

我去探病的时候，她抱着膝盖躺在床上。我以为她在睡觉，看着背对我的她时，她抬起头，转头用眯细的眼睛望向我。

「外面好热。我骑脚踏车过来的，所以流了一堆汗。」

我边说边坐到椅子上。她没有回答。驼起来的背跟墙壁一样，挡住我的视线。

「对了，《果青》好像要动画化。第五集的书腰写的。」

「播放时间是凌晨吧？这边九点就要关灯了。」

「我录起来烧成DVD给你。」

「没有播放器。」

「我带笔电过来。」

对话中断。吸进汗水的口罩黏在肌肤上。听见医护人员在走廊上推推车的声音。

「我可能没办法从高中毕业了。」

她的声音软弱无力，听起来像隔着窗帘在跟她说话。

「是吗？不过——」

喉咙好干。「还有高认测验（注1）啊。你一定能上大学。」

「有那么容易吗？」

她叹出一口微弱的长气。

我抽出插在背包侧袋的宝特瓶，想起这里禁止饮食，仅仅是注视着运动饮料在宝特瓶中摇晃。

第六集的主题是校庆。

准备校庆的剧情中，再次证明了小雪乃有多厉害。不仅成绩优秀、眉清目秀、运动全能（虽然缺乏体力），还这么会做事，好惊人。她感觉没什么人望，倒是挺适合以副手的身份掌控全局。

另一方面，我真的看不下去（几乎可以说是）新角色相模的无能样。她那天真、不负责任的态度，使我看到自己的影子。我连打工的经验都没有，却开始担心工作后会不会变得跟她一样。

她害计划逐渐出现漏洞的过程异常写实。很少在轻小说里面看见这种剧情吧？其他作品中大概也找不到讲得出「时间会解决一切——这种说法是骗人的」这种话的主角。

而那位主角八幡，这一集非常帅气。他一直在幕后做事，紧要关头会（用符合他风格的做法）果断地将问题处理掉。是边缘人常妄想的情境。跟「独自反抗占领学校的恐怖分子」同样喜欢的展开。

可是，直到最后都没有机会给我大显身手。校庆六月就办完了，恐怖分子也从未出现过。

八幡说的那句「安逸的改变不是成长」，深深感动了我。我把那样子的妥协、放弃，跟「长大」画上等号。可是，他首先叫我们肯定现在的自己。

我没办法那么肯定现在的自己。

八幡很坚强。所以我才会崇拜他吧。

下课时间，我坐在自己的位子上看书时，有人来跟我搭话。

「喂——」

宇都宫美织站在我的座位前面。都十一月底了她还穿着迷你裙，腿看起来很冷。她一只手插在毛衣的口袋里，另一只手拿着书店的塑胶袋。

「她叫我把这还你。」

她将塑胶袋放在桌上。我伸手一摸，摸得出里面装的是书。

「真夏说她不想看了。」

宇都宫望向窗外，我也跟着看过去。微阴的天空不知为何刺得眼睛发疼。

「她还叫你别再来了。」

「是吗？我知道了。」

听见我的回答，宇都宫闷闷不乐地点了下头，走出教室。

打开袋子一看，里面装着我三天前借给盐原的《果青》第六集，以及未拆封的信。

我不会逼别人看我喜欢的书。对阅读喜好相近的哥哥，也从来没做过那种事。所以既然她说了不想看，我也不会逼她。即使是我最喜欢的《果青》。

八幡和小雪乃在校庆结束后，终于知晓「彼此的存在」。经过故事里的半年和现实世界的一年半个月，我和盐原对彼此加深了多少瞭解呢。

人生永远无法倒带重来——这是第六集最后，八幡内心的独白。这句话真的最令我印象深刻。虽然我没能写进写给她的信中。

我将装书的塑胶袋收进抽屉。教室里没人看见这一幕。

第七集在三月发售。新书总是在我的环境产生变化时出版。

我考上第一志愿，从高中毕业。毕业典礼上有叫到她的名字，然而她本人并未到场。

我写下不会有人看的信。

首先要为我这段时间都没去探病道歉。我没去询问你那句「别再来了」真正的用意，之后也没去问你是否改变心意了。因为我害怕再度遭到拒绝。

我想，我还会继续写信给你。这会使我想起跟你分享对《果青》的感想的时候。对我而言，和你讨论的乐趣也是那本书的魅力之一。

希望总有一天，这封信能被你读到。

回归正题，第七集写的是毕业旅行。

虽然气氛有点僵，看起来好愉快喔。我毕业旅行的时候没发生那种告白事件，也没有偷跑出旅馆吃拉面。因为我是边缘人吗？可能是京都和冲绳的差别吧。

海老名同学做的决定，我可以理解。既然现在的关系是舒适的，会不想改变也很正常。看完第五集后，我也在信里写了「我不喜欢变化」。

不过，我从高中毕业，脱离了八幡所说的「狭窄到可笑的地步的世界」、「短促到教人无奈的时间」。不得不去思考，未来该如何在大学这个崭新的世界中生存（我实在没什么干劲）。

在那之后，应该也会有新话题能跟你聊。期待那一天的到来。

当时的我说着「我实在没什么干劲」，其实心里应该充满对新生活的期待。因为我没意识到，她正被囚禁在那个用窗帘隔开的昏暗狭窄空间中，那稍纵即逝的时间中。

我的内心期待着新生活，骨子里却是个讨厌变化的人类，因此到头来，我的生活依然没有变化。通勤方式虽然从骑脚踏车换成了搭电车，只要滑个手机，到东京的一小时车程只是眨眼间的事。默默坐在教室里听老师上课，九十分钟也是一下就过了。

我去过一次必修课的班级揪的聚会。搬到东京开始独居生活的寂寞导致的过度热情，以及土生土长东京人的从容不迫，都跟我扯不上关系。与LINE贴图一样简洁易懂的无害发言，在居酒屋一句接着一句。真怀念八幡和小雪乃勾心斗角、充满恶意的对话。

《果青》的动画于四月开播。我总是熬夜到凌晨，边看边录影。希望即使她在病床上缩着身体、抱着膝盖、闭着眼睛，也能听见有了声音的八幡他们所说的话。

七･五集是短篇集。描写了至今以来的剧情间发生的故事。时间没有按照顺序，所以不搭配开头的月历看会有点乱。

封面居然是三浦。我本来在猜该不会有三浦回吧，结果果然没有。

阅读从未在书中提及的小故事的期间，我觉得八幡他们彷佛是实际存在的人物。

我想起你的时候也有同样的感觉。抱怨晚餐的煮鱼很难吃时愁眉苦脸的表情、雪白脚背透出的蓝色血管、模仿材木座咳嗽的怪声——我会在日常生活中不经意地想起那些景象，重新体会到与你共度的时间确实存在过。

篇幅最长的短篇的最终头目，是柔道社的毕业生。我看的时候把感情投射在八幡身上，不过仔细一想，我也跟毕业生一样是大学生了。目前我不会想逃避大学。就算想逃避，边缘又没参加社团的我也没办法逃回那所高中。

我感觉得到我在逃避你。我有好几次都来到了综合医院门口。其实上礼拜也有绕去医院一趟。但我踏不出那一步。我害怕面对你。害怕你对我说出决定性的那句话，我们将永远断绝关系。

八幡说过「他为自己『逃避』的事实所逼」。说得没错。

我有很多话想当面跟你说。

我开始在东京的家庭餐厅打工。工作机会远比老家那边多，时薪也不错。

服务业的经验告诉我，世上有许多怪人。竟然有带着老婆和年幼的儿子来的男人，把桌上的牙签连同容器一起偷走，在做这份工作前，我想都想不到。

《果青》里面也有许多怪人，但他们不会加害他人，从这一点来说好太多了。这些人都有办法出社会，八幡一定也能找到工作。

第八集是从毕业旅行结束的数日后开始，害我有点错愕。

第七集是三月出的，现实世界已经过了八个月。原来本篇隔了这么久才出，由于有动画跟七･五集可以看，我还有种一直在看《果青》的感觉呢。

八幡在开头说「因为终将失去，才显现其美丽」。我还没办法那么豁达。

明明再也见不到你，为什么我还要一直写这种信？是八幡不屑的自我怜悯吗？唯一可以确定的是，《果青》这个故事仍会继续下去。我打算看到最后。如果你能在未来的某一天追上来，我会很高兴。

这一集，八幡、小雪乃、比滨同学对于学生会选举一事意见产生分歧。我看了非常难过。我还是希望那三个人在一起。

总是将问题拖到之后才处理的习惯，导致八幡遭到孤立。我觉得我也有将许多事拖到之后才面对，藉此逃避现实。上大学后依然没在念书，茫然地度过出社会前的这段宽限期。和你之间的问题也一直没处理，结果还是找不到和好的机会。

我觉得我隐约可以明白八幡渴望的「真物」。「无需话语即可心意相通，无需行为即可瞭解对方，无论发生什么都能永保完整」。它一定存在于我能触及的地方。

她的死讯，我是透过LINE得知的。

毕业时班上创的群组早被我忘得一干二净，突然跳出一堆通知，我便点开来看了下，全是为她哀悼的讯息。

对我来说，群组内外都没有人能与我分享她的事。大家的感情灌进心中，无处宣泄，等同于死胡同。用英文来说就是Dead End。

Dead letter是指空文，或者无法投递的信件。

这件事发生在一月中旬，在新年前三天去世的她，葬礼只有家人参加。

同学们在群组里计划去她的灵堂前上香。我没有参加。

过了几天，我独自来到她家。

她家是县道旁边的豪宅。古风的门上加装了类似屋檐的东西，以前可能是当地的村长之类的。

我将脚踏车停在马路对面。附近没有行人，呆站在那边太不自然，因此我假装LINE收到讯息，边滑手机边侧目观察她家。

记得她说过，她的家人只有双亲和祖母。三个人在那么大的房子中，过着什么样的生活呢？少了照理说会活最久的她，她的家人该如何度过之后的每一天？

我在病房见过她的母亲好几次。所以只要按门铃说清楚原因，她应该会让我进门。可是，我没有这么做。我觉得一旦做出那种事，我和她的关系就会沦为平凡的世间俗物。

这个世界上，只有我跟她共享《果青》这个故事。是特别的羁绊。我们之间的交流无人听见，无人看见。在那个过程中得到的事物、失去的事物，只属于我们两个。相较之下，悼念和供品都显得没有价值。

我用手机打开我们去滞洪池时拍的照片。她在初夏的阳光底下微笑。离置身于寒风中的我太过遥远。关于她的记忆模糊，曾经交谈过的一字一句消失不见，只剩这张照片和几封信。

我骑上脚踏车。无人的道路，正好可以让我不用拭去夺眶而出的泪水。

第九集是在准备圣诞节活动。这些人一直在办活动耶。

接续上一集的内容，八幡跟小雪乃、比滨同学分头行动，不过他们在途中会合了。这三个人果然就是要在一起。

请两人帮忙的那一段，八幡终于忍不住说出「想得到真物」。

根据之后的描述，小雪乃跟比滨同学好像也渴望得到「真物」（不知为何伊吕波也来参一咖，结果碰了钉子）。

「真物」会让我联想到你。你的死就是对我而言的「真物」。

死亡不会改变。也没有个人差异。不可逆，又是绝对的，打个比方，就像光线和声音都传达不到的深不见底的大洞。我觉得我一直在沿着这个洞的边缘走。视线范围内的一切通通微不足道，扔进洞里就没了。

小雪乃在游乐设施的车厢滑落的前一刻，对八幡说「总有一天，要来救我喔」。八幡还有机会救她。

我没能拯救你。没有那个机会，也没有那个力量。我能做的只有继续写信。

有时我会试着窥探洞底。你在那里，但那不是你。虽然我早就知道了。

升上大二，我的生活仍旧没有变化。

大学和打工场所都没有人陪我聊天。习惯不了东京的生活，一直觉得喘不过气。除了平常会去的地方，其他地方我都怕得不敢踏入。

坐在通往家乡的电车上时，我才终于松了口气。感觉像在搭乘从地底深处的坑道回到地面的电梯。狭长的轨道延续着我的生命。光芒朝外界的黑暗四散，留给我的只有微弱的光。我在那底下看《果青》。从第一集到第九集。看完后又从头看起。终点并非终点。正因为知道故事还会继续下去，才能重新开始。

她的故事中断了。面对这个事实，我该如何找到妥协点？

我在熟悉的车站下车。电车留下我开走了。

六･五集要把时间往回推一点，是校庆后的运动会。跟七･五集这本短篇集不同，是长篇＋短篇的形式。

这次都是相模在惹麻烦。这家伙真的是……跟校庆的时候比起来一点成长都没有。自己什么都不做，却要求其他人提出意见，实在很会惹火人。

这种人将来会怎么样啊？还会继续给身边的人添乱吗？搞不好她会在上大学后改变心态，过得很开心。

然而，她这个人的个性该说莫名写实吗，我也有跟她相似的部分，所以没办法真的讨厌她。例如只有自我评价特别高，失败后会闹脾气这一点。被朋友无视也是每个人都会经历的事……啊，我没有。幸好我没朋友！

八幡和小雪乃依然精明干练。感觉可以直接出社会了。（虽然我是边缘人）最近我也开始听别人聊到就职，所以我会站在那种角度看他们。我也能成为和他们一样的优秀人才吗？

我再也无法用跟高中时期一样的角度看《果青》了。难搞的相模、温柔的比滨同学、认真工作的小雪乃、在倒竿比赛上使出游走在犯规边缘（已经一脚越过犯规的那条线）的手段的八幡，在我眼中都可爱又惹人怜爱。感觉像坐在观众席看小孩比赛的家长。过去，我身在侍奉社的社办中。如今则是远远守望年纪比自己小的朋友的存在。

我为此感到有些寂寞。

时光流逝，我的年纪跟八幡他们愈差愈多。

也和不会长大的她愈差愈多。

假日，我沿着河边骑在跟她一起去滞洪池的那条路上。风吹过辽阔的河岸。阳光将茂盛的青草照得闪闪发光。我想起在那间昏暗狭窄的病房与她共度的最后一刻。能随手用运动饮料补充流失的水分，使我感到有点内疚。

重要活动结束后，第十集写的是关于志愿的故事。都到这个时期啦。

不去烦恼自己的志愿，而是在为其他人的志愿烦恼，实在很符合八幡的个性。

我高中的时候也没什么在为志愿烦恼。边缘人很闲，所以满常把时间拿去念书的。

平冢老师叫八幡好好面对现实。叫他思考上大学后的未来。我也到了要认真思考这些事的时期。

跟你在一起时，我真该更认真地面对现实。你再度住院后，病情明显相当严重。我却不肯正视它。明知时间所剩无几，我还是该好好面对你。即使会遭到拒绝。

八幡回应他人的委托，叶山回应他人的期待。他们在我眼中显得耀眼无比。尽管手段有所出入，他们都竭尽全力地在寻找跟其他人之间的妥协点。我没有那种经验。

明明是自己期望的边缘人生，有时却会觉得非常难受。

那种时候，我会想见你。

我在大学的食堂填志愿调查表。明年起必须加入研讨会。

现在是午餐时间，附近人很多。没有同伴的只有我一个人。

跟八幡和叶山要考虑志愿一样，于食堂内回荡的声音，每个都有大学毕业后该走的路。

他们每个人都有一路以来看过的书。

我抬头望向天花板，人声嘈杂，掀起巨浪。其中没有半个人是在跟我说话。

一○･五集是短篇集。满多轻松的故事。

看完六･五集时，我在为相模的未来担心，这次则换成材木座了。这家伙没问题吗……相模感觉还勉强有办法到外面上班，材木座呢？他在不同于八幡的另一种意义上缺乏社会化啊。

这集出现一个叫大众传播研究会的社团，我念的大学也有类似的团体。虽然与我无缘。我参加的是所谓的回家社，所以我有点担心求职会不会遇到困难。没空担心材木座了。

伊吕波在这方面似乎没问题。她一定很会做人。她跟八幡玩得很开心的样子。我想起了跟你一起去滞洪池的那一天。那是我人生中最美好的记忆。天空万里无云，眼前是一片美景，微风清爽宜人，你始终带着笑容。我大概会一直怀着这个回忆活下去吧。

八幡要为了学生会发行的免费情报志写专栏。现在回想起来，《果青》就是由他写的作文揭开序幕的故事。而我受到他的启发，开始写信给你。更进一步地说，是因为有《果青》我才有机会借你这部作品，和你聊了许多。很多人会说轻小说无益也无害，《果青》和八幡却改变了我的人生。总有一天，我想转生到那个世界向八幡道谢。虽然他八成会用「这家伙干么啊」的眼神看我。

八幡动不动就会感觉到「终点」。我也该在跟你相处时意识到终点的存在的。这样就能将更重要的事传达给你了吧。尽管结局终将到来，应该也会在那里留下些什么。

《果青》的最新一集出了，又过了一年。

我升上大三，加入了研讨会。在里面多少会跟身边的人讲点公事。聚餐则用打工当藉口推掉。

动画二期开播了。有种跟老朋友见面的感觉。宛如回忆中的她。我不断在脑内重播与她一同度过的短暂时间。

十一集是情人节回。

在策划做巧克力的活动时，八幡他们想起侍奉社的第一份工作。当时比滨同学来委托他们协助她烤饼干。

故事回归起点时，代表终点一定快到了。

叶山和三浦他们、伊吕波、阳乃小姐、玉绳、折本等之前出现过的角色通通登场。能将这些人召集到烹饪教室，是侍奉社的成果，是他们的终点站。

之后故事的中心大概会从社外人士，转为以侍奉社的三位成员为中心吧。

三人在水族馆约会完后，提出各自的委托。始终在为外人解决问题的三人，第一次面对彼此。

明显快走到结局了。

无论会是什么样的结果，我都想见证到最后。我不想跟你去世时一样，事后才从他人口中得知。我不想被故事排挤在外。

不过，这个故事结束后，我该何去何从？我能去往何方？完全无法想像。

虽然到处都在说人手不足、卖方市场，我找工作找得挺辛苦的。面试官没低头求我去他们公司上班，也没开出年薪一千万日圆的条件。结果，我拿到一家工作无聊，但看起来还算佛心的公司的内定。

之后我便关在图书馆乱掰毕业论文，好不容易顺利毕业。

成为社会新鲜人的我，开始在东京一个人生活。

这段期间，《果青》一直没出。

尽管没有学生时期那么频繁，我会去重看《果青》。每次都会想起她那句「不想看了」。

很多人不会把一个故事看到最后。再怎么受欢迎的作品，销量都会随集数递减。读者一个个弃坑。理由应该有很多种。说不定单纯是腻了。说不定超越了那个地步，成了黑粉。说不定是没钱。说不定死了。

他们不如追完整部作品的人吗？跟只看到一半的她比起来，我是更优秀的读者吗？

睽违两年的十二集出了。不知不觉，我已经踏出社会半年。

开头像要填补这段间隔似的，帮读者做了前情提要，但我仔细预习过了，所以衔接起来没有障碍。

小雪乃的委托（不如说「愿望」？）揭晓。至于她的梦想是否会成真，八幡和比滨同学一定会照她所说，见证到最后吧。

剧情以舞会为中心发展，大魔王——小雪乃妈妈终于登场。在她面前，连阳乃小姐都只是个小魔王。虽然阳乃小姐的目的好像只是捣乱，某种意义上来说比大魔王更难缠。

很多事情不能光由八幡他们做决定。家长的意见不容无视，校方不准的话舞会也绝对开不成。

即使如此，八幡他们仍在努力靠自己做决定。换成是我，八成会放弃。是什么东西让他们这么努力？是因为年轻气盛吗？如果将其归因为主角光环，可能又太武断了。

八幡说「就算上了大学，恐怕也不会遇见命运的邂逅或决定一生的梦想」。也许如此，也许并非如此。不是因为他们还年轻，而是这个故事尚未结束。

那我又如何？我觉得自己身在已经结束的故事中。

阳乃小姐直接跟八幡明说他们之间的关系叫「共依存」。我依存在你——更正确地说，是依存在你的死亡上。每天无精打采，不去交朋友，不好好吃饭，对世上的一切漠不关心，都是因为我将自己塑造成「失去心爱之人的男人」。有这个前提存在，我才能维持自己的样貌。《果青》是用来将我和你这个依存对象联系在一起的手段之一。自从你把书还给我后，我一直是这样自己一个人看，所以我不知道还能用什么方式阅读它。

我阅读《果青》的方式一定搞错了。早知如此就不该追着进度看。早知如此就不该渴望什么「自己的书」。

真想让一切重来。从你第一次在教室跟我搭话的那一天起。

一年的时间过去。

时间过得好快。我有了后辈，已经不算社会新鲜人了。

第十三集的书腰写着「故事迈入最终章——」。我犹豫着伸出手。

故事进入最终章，一开始的「比赛」被重新提起。

而提议举办那场「比赛」的平冢老师，即将离开总武高中。

故事是为了结束而开始。我明明是在知道这一点的前提下看起《果青》的，现在却害怕着故事迎接结局。

若能和你分享我的不安就好了。可是，我再也回不去有你在的时间。

八幡、小雪乃、比滨同学的时间也即将结束。他们三个肯定怀着同样的愿望。三人都想尊重彼此的做法，却渐行渐远。

他们再也回不去第一集刚开始时的关系，也回不去在侍奉社社办共度的时光。

完结的故事会去往何方？被黑暗吞没？不断在虚空中飘浮？重生为其他东西？

故事结束后，会留下什么呢？

日子没有过完的一天。

出社会第二年的我，不可能接到足以让公司、业界、世界产生变化的工作，一天、一星期、一个月在处理日常业务的过程中流逝而去，季节更迭。

完结篇第十四集当初预计在二○一八年三月发售，结果延期了好几次。

我并不会觉得迫不及待。我不太会有等待的感觉。时光流逝，代表我离跟你一起度过的时间愈来愈远。我不会想接近未来的存在。

发售日当天，我在下班后去了趟书店。整个轻小说区都在为第十四集做宣传。一名穿制服的少年从平台拿了一本，走向柜台。若他今年高二，第一集出的时候就是小二的三月。动画二期开播的时候也国一了。不晓得他得知这部作品的契机是什么。

他肯定不会像我这样看《果青》。我也没办法跟和八幡同年的他用同样的角度阅读。

我呆站在书架前面。无数个小雪乃在对我微笑。

这一刻终于来临。

那两个难搞的人，八幡和小雪乃对对方表明心意，竟然成了明眼人都看得出来的情侣。比滨同学想要三个人一直在一起的愿望也实现了。就我看来，诞生了小町×伊吕波这个尊到不行的配对非常赞，不过先不讲这个了。

跟随他们和她们一年来的脚步走的漫长旅途结束了。

原本还在担心《果青》完结后，我不知道会有什么反应，例如难过得泪流不止、被空虚感搞到什么事都不想做之类的果青完结后遗症，不过并没有。我知道八幡、小雪乃、比滨同学至今依旧身在总武高中的那间社办。没出三年级篇我也知道，所以没必要寂寞。

你会不会也在那里？说不定你在某处跟他们擦身而过了，说不定你们念的是同一所高中。虽然这样讲跟梦小说一样，完结的故事和去世的人一定会抵达同样的场所。

我在上一封信写到「真想让一切重来」。可是现在，我不想像这样感到后悔。八幡对小雪乃是这样想的——「这些话不可能让她明白。不明白也无妨。传达不到也无妨。我只是想告诉她」。就算我阅读《果青》的方式是错误的，我也能抬头挺胸地说，我想将自己对这部作品的感想传达给你、明知无法传达仍然不断写信，这么做是没错的。不能说这是错的。

八幡说要「结束我那故意搞错的青春」。以受到他人逼迫的形式揭开序幕的故事，最后也是因主角的决定而落下帷幕。

我也想做出决定。尽管非常微不足道，我相信这样可以报答《果青》和你的恩情。

沉浸在故事跟回忆中的我，总有一天也会被现实追上。

于是我抵达了这里。不如说回到了这里。

我下了公车，走在县道上。干燥的冷风吹过狭窄的道路。

她的家外观和六年前并无二异。线香的白烟在门口的卤素电暖器的加热下，散发出更加强烈的哀愁。

我不知道七周年忌在宗教方面有何意义，不过做个了断是很重要的。人类受不了没有分段、一直持续下去的故事。

有几个跟我同辈的人坐在佛坛前，但大多是不认识的。推测是亲戚和小学、国中的朋友。她念高中的时间实际上只有一年左右。

宇都宫美织现在染成比高中深的发色，妆却浓得跟夜店小姐一样。穿着吊带袜跪坐在地上的双腿，在屁股下面动来动去。

听说七周年忌经常只有家人参加，我是主动联络对方，请他们让我出席的。

我一直在逃避法事。我想独占她的死。她的死对我而言是唯一的「真物」，一切的基准。其他人怎么想与我何干。

然而，光这样无法使我的心情平静下来。死亡这种东西，存在只能藉由世人追悼死者的仪式平息的部分。就算不讲出来，也得靠某种行动与他人共同分担这份心情。

是《果青》推了我一把，让我来到这里。八幡做决定时，我觉得自己也必须采取行动。第一次写信给她，也是拜《果青》所赐。我总是把决定权交给故事。

法会结束后，我吃了盐原家叫的外送寿司，离开她家。

我站在大门口旁边的公车站等车，冷得缩着身体的宇都宫走了过来。她用指尖拎着手提包，一副太冷不想碰提把的样子。

「好久不见。」

「嗯。」

「朋友没跟你一起离开吗？」

「旁边那些不是我朋友。他们是真夏的国中同学，我是在补习班认识她的。」

她站到我旁边，打了个大哈欠。

「好想睡。」

「辛苦了。」

「因为我刚上完夜班。和尚念经的期间真的爆炸想睡。」

我心想，夜店小姐的工作也能叫夜班吗？

「你的工作是？」

「护理师。」

「咦？」

「我在红十字会，有需要就来吧。」

「原来是那啊。以前我长水痘的时候去过。」

她从我背后走过去，看公车时刻表。淡淡的甜美香气掠过鼻尖。

「我有点意外你会去当护理师……」

「真夏住院的时候，总是非常感谢护理师，所以我也想做那种能帮助别人的工作。」

在我将盐原的死视为「真物」、一个大洞的期间，宇都宫从她的死中得到了什么。将中断的故事连接起来。和只会哭哭啼啼的我正好相反。

她把用手指勾住的手提包当成钟摆晃了下。

「那个时候对不起喔。她叫你不要再去看她，你很受伤对不对？」

「没关系。」

我伸手搓了下鼻子。

「在那之后，她也有叫我别再来了。真夏当时瘦到不行，总是很不舒服的样子，还变得会迁怒在妈妈身上。」

「这个……嗯，或许吧。但我记忆中的盐原很温柔，一直都是面带笑容。」

「我也是。她真是个好孩子。」

她在高中这个大家都很幼稚，像八幡和小雪乃那样讲话只会拐弯抹角的年纪，预料到自己的死期，真的很可怜。

一辆大卡车从我们旁边经过，废气的臭味令我屏住呼吸。

宇都宫看向我。

「对了，《果青》完结了耶。」

「咦？」

出乎意料的词汇从她口中冒出，我吓了一跳。「你怎么知道？」

「我一直有在看。一开始是真夏借我的。」

「那是我的书。」

「不过你写的情书她就不肯给我看了。你每次都会附上呢。」

「呃，那不是情书啦。」

我把手插进外套的口袋。宇都宫微微扬起嘴角。

「最后果然是选小雪乃。我是结衣派的说。」

「噢……对结衣派的人来说，结局挺遗憾的……」

「看到八幡去结衣家做水果塔的那段时，我的感觉是『啊……』。太快营造出浪漫气氛了啦，还剩四百页左右耶。」

「要说的话我也挺紧张的。还有一些篇幅就告白成功，拜托不要之后来个大逆转啊。」

公车从车站的方向开来。空位很多，所以我们并肩坐在最后排的位子。

她从手提包里拿出纯白的手帕，捂住鼻子。细表带手表往手肘滑落一些。

我重新系紧领带。

「到站后要不要找个地方坐下来？我很久没跟人讨论《果青》了，想多跟你聊聊。」

「是可以。」

她看了手机一眼。

「那就来聊我去果青Fes时的事吧。」

「你有去参加呀？」

「一般来说都会去吧。可以看到江口拓也早见沙织东山奈央耶。渡航也在场。」

她噘起红润的嘴唇说：

「我不敢一个人去那种活动。」

「那天龙寺的竹林总该去过吧？」

「你去过喔？那是户部想跟海老名同学告白的地方吧？要我跑到京都有点困难。」

「一般来说都会去吧。那可是圣地。」

「我开始搞不清楚一般的定义了。」

我是个一般人。不是什么特异人士。不会有人羡慕我，我也无法影响其他人。

但我并不边缘。《果青》的读者全是我潜在的朋友。

追一部作品跟一个故事很像。

我也是一个小小的故事。

我们朝着「真物」迈进。

虽然没能拯救你的我讲这种话很奇怪，等我抵达那里时，还请救救我——我跟在迪士尼乐园向八幡求助的小雪乃一样，向她祈愿。

「你太嫩了。我看你得先从千叶的圣地开始跑起。」

我边滑手机边说。

停下来等红灯的巴士再度摇晃着驶向前方。我还想再写信给她。这次要写的是关于新故事的信。

车站进入视线范围内。我肯定又会自然而然走向那家书店。

即使不知道从那里开始的会是什么样的故事，我下定决心，不会再让自己被排除在外，也不会再让它中断。

完

1注	  指「高等学校毕业程度鉴定测验」。

** 果然，人多嘴杂。

作者：王雀孙

《九十九天后会死的满等的我被骑士团赶走一边过着慢活生活一边在迷宫里开无双击退反派圣女跟魔王》

「够了！你给我滚出这个国家！」

杀掉一只非常强的巨龙时，忽然有人对我口吐暴言——

「你的所经之处必定会有棘手的灾厄来袭！该死的死神，别再把更难缠的怪物引来我的国家！」

「呵，是吗……」

我惊讶得不禁失笑——听说人类直接面对令人惊讶的悲伤时，反而会惊讶得笑出来。看来百战百胜的我也不例外。

这个能够预测灾厄的破格罪孽<技能>，以及只是想救人的纯粹的正义感，竟然会害人产生这样的误会，我非常悲伤，忍不住笑出来——

「呵，明白。再会了，愿汝等幸福——」

就这样，我离开养育我长大的心爱的国家——

——离命运之夜，剩下九十九天。

「这什么东西。」

看完那篇文章，我诚实的感想就这五个字。还不小心连敬语都忘了用。这什么东西。盘踞在脑中的无数疑惑，反而统整成简单的结论。或者说这不是感想，而是化为言语的叹息。

「老师？那个，请问这是什么？」

过了一拍她还是没回答，因此我从印着粪作的那叠A4纸上抬起头。隔着桌子坐在我对面的，是神情自若的国文老师——平冢静。

「什么叫『这是什么』。比企谷，问问题的时候要讲清楚。」

「请问您给我看的是什么东西？」

我回应她的要求，正式提出明确的疑惑。

「小说。」

她正式回以明确的答案。

「小说……嗯，是没错，姑且算是。」

我将视线移回纸上。啪啦啪啦地从上面翻过几张。超常对别人嗤之以鼻的主角正经又奇妙的旅程，以摘要的形式呈现于纸上。「呵」这句台词出现的频率好高。这个主角的笑声种类好贫乏。而且敌人和伙伴的语气超做作。我都用舞台剧的语气在脑内播放。还有文言文跟白话文夹杂，看得我头都痛了。然后不要把破折号当成句点逗点用。罪<技能>孽<rt/>又是什么鬼。总之吐槽点多到不行。整体上来说——

「这什么东西。」

就是这五个字。

「要刊在文艺社社刊上的稿子。」

平冢老师终于给了一个有建设性的答案。

「尽管是篇拙文，用你宽大的心胸包容它吧。这是创作资历不到一年的一年级社员们的作品。」

「作品。」

日文真是心胸宽广的语言。

「为什么要给我看？」

「你跟同年代的人比起来，读书量算多的吧。你觉得如何？针对目前看到的内容发表感想就好。」

「喔。」

我也不是没心没肺的人，对方认真征求我的感想，多少会有点难以启齿。俗话说「别骂小孩，每个人都走过这条路」。既然我已经得知对方是新手这个基本资料，认真批评可能会被人觉得太幼稚。

「能看啦。」

我把开头的「根本不」省略掉。

「总之，我感觉得到他们想写出好作品的意志。」

不如说只感觉得到这个意志。总之想让书大卖的意志。为了冲销量将想得到的人气要素通通塞进去的意志。从那加了各种要素的无节操书名来看，这部作品充满作者迫切的愿望。大概是想反过来让人觉得「这个书名wwww」戳读者的笑点，但他们的意图表露无遗，反而达不到预期的效果，就只是个失败作。

「这回答挺模棱两可的。」

「没啊。我觉得能看啦。」

我再度省略「根本不」两个字。

「哦。」

平冢老师简短应了声，这声「哦」不是「这样啊」的意思，而是在问我「然后呢」。她要我给予更详细的评论。真的假的。这人今天好不知足。

「嗯，与其说意志，总之就是气势。作者的热情很惊人。有种『跟技术无关，这就是我的饶舌』的感觉，所以我决定投这位选手一票。」

我已经掰不出感想，便让昨晚碰巧看到的饶舌对决节目的评审附身在我身上，代替我作结。接下来Zeebra先生应该会帮忙把镜头交给怪物房。（注2）

「原来如此。还有呢？」

可是我们的静小姐十分缠人。没有篇幅这个概念。

「还有呢？」

我反射性回问，也是在委婉表示「没了啦」。

「真不像你。你还有其他意见吧？大可适度说明喔。」

「那，很无聊。」

平冢老师下达许可，我便恭敬不如从命，她话才刚讲完就立刻回答。

「很无聊，不如说超难看。完全不觉得之后的剧情会变精采，看完开头就能弃了。」

「原来如此。」

听完我诚实的感想，平冢老师反应十分平淡，彷佛早已预料到。

「那我问一下哪里无聊，做为参考。」

国文老师总是会想知道奇怪的事。我将那叠纸放回桌上。

「这个嘛，无聊的点在于太无聊了。」

就是无聊。除了无聊外没有办法形容。

不是让人怀疑自己眼睛有问题的夸张内容，字里行间也没有透露出作者强烈的风格。时间在阅读过程中白白流逝，虚无型的无聊。

我仔细地说明。

「这样啊。了不起，比企谷。」

「咦……？」

比企谷八幡鲜少得到称赞。直觉告诉我这是个陷阱。我被套话了。

「既然知道问题出在哪里，你应该能让这部作品变有趣。」

「不，这个理论有问题。」

如果这个理论说得通，网路上全是一流作家跟一流编辑了。我们是因为不用负责才能客观地讲出真理。来吧各位，今天也匿名狂批粪动画和粪轻小，以导正世界吧！

在我于心中玩起正义的网路义勇军游戏（我并没有真的干过这种事）时。

「你看一下。」

平冢老师拿起那叠纸，抽出最底下的那张递给我。

「可恶！这男人太强了！」

「我们几个等级超过二十，竟然连他的一根手指都碰不到！」

山贼们见识到我惊人的剑技，吓得两腿及声音都在颤抖——

「呵，真不好意思。我的等级——是满等。」

我举起连岩石都能劈开的大剑，用迅雷不及掩耳的速度一挥——

咻——！

——疾风呼啸而过，接着是刹那间的沉默。敌人一个个应声倒地。

不知为何，胜利过后总会有股空虚感——我转过身，准备离开静寂的战场。

「谢、谢谢您，圣骑士大人！」

惹人怜爱的声音从背后传来——是在这块无名的边境遭到山贼袭击的村姑。

「呵，圣骑士吗——」

然而，现在的我没资格被人用这个怀念的称号称呼，仅仅是——一介旅人。

「真是有趣的女人——回去时小心点啊。」

——离命运之夜，剩下二十四天。

破折号还是一样烦到不行。

还有那个女人有讲什么有趣的话吗？

还有从开头到这段剧情好像经过七十五天了，还在写这种日常剧情没问题吗？魔王登场了没？

「怎么样？」

「能看啦。」

她再度征求我的感想，我再度随口回答。

「我说的不是那个。」

平冢老师却摇摇头。

「倒数计时不是结束在『剩下二十四天』吗？不过，那是最后一页。」

「嗯，对啊。」

她说得没错，虽然我因为完全不好奇后续的关系，没有注意到。这里不存在故事的结局。有的只有「努力撰写中」，或是写到一半就弃坑。

不重要就是了。

「我想请你帮忙写后面的部分。」

「啥？」

平冢老师开了个荒谬的玩笑。她的表情完全不像在开玩笑，但那句话怎么听都是在开玩笑，所以肯定是开玩笑的。

「啥？啥？」

我问了三次「啥？」，打算问到平冢老师回答「开玩笑的啦」为止。

「比企谷，这里是哪里？」

「哪里……呃，侍奉社社办。」

虽然两位社员有事，今天只有我一个人。

「是啊。对吧。没错。」

听见我的回答，平冢老师满意地点头。

「所以，希望你想办法搞定这份没写完的原稿——这是文艺社的有志之士向侍奉社提出的委托。认真工作啊。完毕。」

「不不不不。」

我摇头摇到脖子都快断了。真希望我的头直接掉下来，击中平冢静的脸。

「您在说什么啊？我完全无法理解。叫我想办法搞定，咦咦，这什么随便的委托……不对，这是文艺社的作品吧？」

「嗯，文艺社成员的接龙小说。」

「接龙小说？」

由好几个人按照顺序接着写的那个接龙小说？

经她这么一说，我重新拿起原稿翻阅，尽管没有注明每位作者，每一段的文风……不如说文笔确实有差。大部分都是不成熟的练习等级，但其中也有几段能看的文章。

「发现了吗？没错，里面分成会写的人跟不会写的人。」

平冢老师抬起下巴，指了下我手中那叠办公室用纸。

「社团也是一个社会的缩影，有等级差距的话，各种摩擦也会随之而生。简单地说，现在社内的气氛似乎很沉重。」

「哦……认真写的人跟写好玩的人有点起冲突的意思。」

不意外，毕竟平均水准太那个……可是太自我感觉良好也很恐怖……对于认真型文艺社的同情，以及对于休闲型文艺社的共鸣同时涌现。双方的心情我都能理解。

不过，该怎么说呢。同好难得聚集在同一个地方，却把气氛搞得这么僵，都不知道那个社群是用来干么的了。人果然不该群聚。边缘人最强论的可信度又提高一级了……

「就是这样，原本打着要让社员团结的名义制定的接龙小说企划，如今似乎只是争执的源头。」

「那干脆中止企划不就行了？」

反正写出来应该也不会是多好看的作品。

「哪那么容易。中止企划的话，想继续写的人心里会有疙瘩。」

连这个都要再吵一次啊。真麻烦。边缘人果然是最强的。

「打个比方，由你以优秀讲师的身份参加，把这部作品的品质整个拉高，这个选项如何？」

平冢老师露出像在试探我的笑容。

「并不想。」

超级不想的。这人以为我是谁啊，我没那个能力也没那个神经。

「再说，非社员的外行人插手管这种事，只会害气氛变更差吧。」

说着，我脑中瞬间浮现一个想法。如果有个共通的敌人，能否提高社员的团结力？我吐出一口气，移动视线。茶具摆在原位。现在这间社办里，没有红茶的香气。

「这个选项麻烦作废。」

我斩钉截铁地回答。

「我想也是。」

平冢老师露出温和的笑容。

「用其他手段应该比较好。总之想点办法吧，拜托啰，侍奉社。」

「咦咦——」

讲得好像有很多手段可以选的样子……

「呃，是说，今天另外两个人没来，不能凭我的一己之见接下委托。」

「有什么关系？跟她们说这是平冢案件就好。」

「您一副这不是平冢案件的态度，这可是顾问对社员的职权骚扰喔？咦，在这个时代做这种事没问题吗？」

「那就交给你们了。」

我暗示她这样会违法，平冢嫌疑犯迅速离开社办。

独自留在社办的我，盯着平冢老师放在这边的那叠办公室用纸。

「唉……」

这么顺手就把麻烦事塞给我们处理。然而，既然她说这是社团活动——工作，那我也没办法。平冢老师近似道德绑架的行为把我训练得愈来愈社畜，无法违抗「因为这是工作」理论。工作真的是坏文明。

不过，幸好我和一位立志当小说家的人有着奇妙的缘分。那男人好像随时都在缺读者，而且他应该特别适合写这类型的小说。品质暂且不提。

回家后，我联络了材木座义辉。

《九十九天后会死的满等的我被骑士团赶走一边过着慢活生活一边在迷宫里开无双与反派圣女度过幸福快乐的生活～复活的暗黑四天王篇～》

同一时间，夜幕降临魔<Demonium>界<rt/>神<rt/>殿<rt/>。

异<Judgement>端<One>审<rt/>问<rt/>官<rt/>下到绽放鲜艳光芒的祭坛上。

「时机已然成熟……苏醒吧，同胞。」

回应他的声音，从黑暗中冒出的影子是泡沫。

「嘿嘿嘿，阔别千年的重力真让人受不了。」

燃烧的冷气。冻结的火焰。永恒的二律背反。

「嗯——好棒的黑<天气>暗<rt/>！欸欸！我可以去杀<玩>一下吗？」

满溢而出的魔<Mana>力<rt/>元<rt/>素<rt/>，是不知停止为何物的时间的奔流。

「呵呵呵……久等了，遥远故乡的末裔们啊。」

于街道上行走的不幸旅人，最后看见的景色是——

「呜、呜啊啊啊啊！你、你是什么人——！」

——伟大的英雄，真理的旅人。

「呵哈哈哈！吾乃独眼的魔龙！暗黑四天王之一，『于黑暗中爬行者』，支<Control>配<rt/>黑影及腐败的混迷的材木！」

那一天，永恒的终结降临世界。

——离命运之夜，剩下九天。

「这什么东西。」

看完那篇文章，雪之下雪乃开口就是这五个字。

我无视她像在责问我的视线，跟平冢老师一样假装听不懂。

「什么叫『这什么东西』。问问题的时候要讲清楚。」

「…………」

雪之下轻声叹息。

「那我重问一次。你给我看的是什么东西？」

「小说。」

「小说……嗯，是没错，姑且算是。」

这支支吾吾的说话方式好熟悉。

「这是某位立志当作家的高二男生提供的文章。尽管是篇拙文，依然是当事者倾注灵魂的作品。」

「作品。」

雪之下将视线移回稿纸上，眉间逐渐挤出细纹。

「这叫作品……是吗，日文真是心胸宽广的语言。」

我感到一阵焦躁。这女人不会把我拿来的原稿拿去作废吧……？

但我也很能体会雪之下的心情。昨晚阅读材木座给我的这篇小说时，我被那强烈的自我满足味呛得眉头紧皱。是说中二病都很爱把名词放在句尾耶。

顺带一提，雪之下才看完第一段。要是她知道后面还有九段都是出自材木座老师之手，不晓得会露出什么样的表情。

不管怎样，那是昨晚的我。读者･比企谷八幡。

现在的我是编辑･比企谷八幡。而且是相当缺乏专业意识的烂编辑。若我真的是编辑，就是那种会无意间伤到作家，在社群网站上疯狂爆料的类型。

而且，「想要做一本好书」的这种理想，也不存在于我心中。我会分得很清楚，作家是业者，读者是顾客，每天只会想着该如何让工作顺利进行。我想成为这样的编辑。不，也不能这么说，但我会扼杀自己的感情，以便轻轻松松地完成工作。材木座的小说我也会拼命护航。

这可是我难得违背良心向他低头，搬出各种好听话，又哄又骗才好不容易让他写出来的稿子。某种意义上等于是我的孩子。事已至此，作品本身的品质我就不管了。反而可以说孩子傻一点才可爱。我想守护这孩子，还有想快点搞定工作。

这件事本来是因我自己一个人而起的，雪之下雪乃的加入十分令人心安。考虑到她优秀的能力，可以说拿到了通往收工的特急券。

然而，雪之下有时会想把事情做到完美。至少这次的工作，她的完美主义是不必要的。根本不能吃的素材，再怎么努力调理都无法变成味噌。既然如此，干脆对品质睁一只眼闭一只眼，以拿出成果为目标即可。

由社外人士投稿到文艺社的社刊，藉此让这篇接龙小说完结。这样就不算支持中止派或继续派的任何一方。

至于品质，我完全不介意把它当成是因为收了社外人士的稿件的关系，才导致品质大幅下降。不如说我打算这样对外宣传。如此便能保住担心文艺社招牌被砸的实力派的面子。作品的平均品质下降，非实力派的人应该也不会觉得那么丢脸。当然不可能一切都这么顺利，不过这部分就请老实的仲介人平冢老师从中协调吧。她都说这是平冢案件了，这点小事一定会愿意帮忙。

以上就是针对这件委托的对策。

雪之下应该也已经知道了。

「你懂吧？品质并不重要喔？」

「话虽如此，若不维持在最低标准，会衍生出许多问题。」

呃，你说的也有道理……可是最低标准大概在哪个程度？太笼统了，我非常不安。

「那我先确认最基本的部分。」

雪之下整理好手中的原稿，然后翻开一页。材木座老师的缺席审判开始了。

「首先，这个叫独眼的魔兽的东西是什么？」

雪之下清澈的声音，现在听起来寒冷如冰。

严格说来，那应该不是魔兽，而是魔龙，不过老实说一点都不重要。没名字甚至也没差。反正就是只小怪。但我也没理由不回答。

「那家伙啊。他是暗黑四天王之一『于黑暗中爬行者』，支<Control>配<rt/>黑影及腐败的混迷的材木。」

「这样呀。那真是太好了。」

为什么呢？我只是把别人写的东西念出来而已，却觉得全身发热。或许语气该更缺乏起伏一点，不如说该营造出一种念得很不甘愿的感觉。我抓了下旁边的头发，盖住八成红得跟什么一样的耳朵。

「可是我想问的不是那个。」

既然你想问的不是那个，可不可以早点阻止我。为什么要让我连「混迷的材木」都清清楚楚地讲出来？她是S吗？

「那我换个问法。这个叫材木的角色，在写作上的功用是？」

功用啊，是什么呢……我咻咻咻地滑着（物理上的意思）材木座的原稿，重新确认。混迷的材木先生放话说「我要让世界被黑暗笼罩——」。

「好像是想让世界被黑暗笼罩的反派角色。本人是这样说的。」

「那是剧情上的功用吧。我想知道的是写作上的功用。」

「喔，那个啊。」

是哪个呢。看来雪之下老师是会想靠理论理解作剧法的人。她感觉就会去读《好莱坞式脚本术》。

「写这篇小说的男学生——勉强称呼他为作者吧——我想知道的是作者的目的。」

雪之下用拳头抵着雪白的下巴，陷入沉思。

「在故事进入尾声的这个阶段，出现了四个新角色。恐怕有着跟剧情结构相关的重要意图。」

「不，没有吧。毕竟是材木座。」

我不认为那家伙会去研究剧本结构论。他感觉就是那种会把没兴趣的作品的情报都上统整网站看过一遍，称之为研究的类型。还有，讲点题外话，他感觉就是那种会把乱逛宅店称之为市场调查的类型。

「暗黑四天王（笑）大概是那个。从他的灵感笔记本里随便拿来用的原创角色。毕竟是材木座。」

我忽然发现，我不知不觉放弃帮材木座老师护航了。算了。毕竟是材木座。

「那看来将它视为剧本中的杂质处理会比较好……」

雪之下导演彷佛在把剧本当成刀具研磨。暗黑四天王篇，默默迎接终结。

「话说回来，最重要的主角在做什么？」

「那个一辈子都在对人嗤之以鼻的男人，有做什么足以用『重要』形容的大事吗？」

说实话我根本还没看。

「不好说呢。如果是制裁恶人，救出被囚的女性的剧情，已经重复十次以上了，」

「你记得真清楚。」

「完成委托后，我有自信能在五秒内遗忘。」

尽管如此，雪之下还是看得很仔细的样子。好厉害，看那东西应该挺痛苦的。她是M吗？

「是说那个毫无计划性的接龙小说，竟然也有姑且称得上是剧情的东西，真令人惊讶。」

我更纳闷暗黑四天王篇到底是什么了。

「……比企谷同学，虽然我想不会有这种事。」

雪之下导演的声音变得更加冰冷。

「你应该有看过全文大纲吧？」

「唔咦？」

我哑口无言，不小心发出萌系角色的声音。

「…………」

导演的眼神愈来愈无奈。

「哦，原来有那种东西。我都不知道。」

「不存在却存在。」

「这什么哲学问题？脑筋急转弯？」

雪之下无视我的疑惑，取而代之的是从原稿中抽出一张纸递给我。我接过它，大略看了一遍。

「……原来如此，有跟没有一样。」

「嗯。」

打着全文大纲（暂定）的名号的那东西，是把那个尴尬冗长的书名直接拉长成三到四倍的字数写成的简陋故事梗概。

意即以形体来说确实存在，内容却等同于不存在。

「白看了。」

「是啊。」

这件事果然要尽快搞定。我重新下定决心。

《九十九天后会死的满等的我被骑士团赶走一边过着慢活生活一边在迷宫里开无双与反派圣女度过幸福快乐的生活～征服世界篇～》

基于谨慎的事前准备及收集情报，最终决战以我方压倒性的优势揭开序幕，成功杀死魔王。

理论上来说，四天王没道理比魔王强，所以四天王也很快就杀掉了。

剩下的敌人当然也杀了。

除此之外，现阶段所想得到的敌人也通通都杀了。例如之前遇过的敌人、之后应该会遇到的敌人、不知为何在独白预告过的敌人、埋了一堆自以为厉害的伏笔的敌人、仅仅是在开头有些过节，忘记回收伏笔的敌人、在剧情中盘遭到放置的敌人、在剧情终盘忽然出现的敌人。

另外，除了物理上的敌对生物，在其他领域可能会造成阻碍的敌人也杀掉了。例如讲好听一点叫复杂，讲难听一点叫乱七八糟的人际关系制造出的敌人、极其扭曲非现实的社会结构制造出的敌人、所有愚钝民众制造出的敌人。

而且，在精神方面会造成诸多问题，意即所谓的内因性的障碍也杀掉了。

结果，阻挡在我面前的敌人全被我杀得一干二净。

「胜利总是空虚的。」

达成打倒魔王这个目的后，我该做的只剩支配世界了吧。

为此有三个步骤要做，而那三个步骤又能再细分成三阶段。

我将依序说明。

——离命运之夜，剩下七天。

「这什么东西。」

看完那篇文章，由比滨结衣开口就是这五个字。

我无视她像在询问我的视线，再度假装听不懂。

「什么叫『这什么东西』。问问题的时候要讲清楚。」

「…………」

由比滨「嗯——」烦恼地皱眉。

「呃，就是，这个东西……是什么？」

「小说。」

「嗯、嗯。是啦，我大概看得出来……」

这支支吾吾的说话方式好熟悉。

「这是某位冷血的高二女性提供的小说。是部倾注灵魂的作品。我并没有要她写，然而无法否认的是，当事人拿出全力的成果，这次似乎不怎么理想呢……」

「作品。」

由比滨将视线移回稿纸上。垂下眉梢，表情带有淡淡的哀伤。

「啊，讲点题外话，最近我在电视上看过有人说『日文真是心胸宽广的语言～』。」

「呃根本不是题外话吧。」

前后文的关系可大了。

然而，我也不是不能理解由比滨的心情。

雪之下说什么「事关侍奉社的名誉」，展现莫名的坚持，花了一个晚上写出来的就是这东西。

吐槽点很多，一言以蔽之就是她太讨厌剧本中的多余之处，把她视为多余的部分尽数删除。残酷的是，魔王在开头就死了。四天王也顺便死了。不如说所有敌人都被屠杀殆尽。小雪乃是精神病患吗？

由比滨却坚强地握紧拳头，试图为如此具有特色的小说护航。

「嗯……不、不过，很符合小雪乃的个性啦！这种，没有多余之处的感觉。」

「是啊。她两三下就把疑似派不上用场的登场人物处理干净。」

其杀伤力被小林制药看上，拿去做成杀角色用的药品都不奇怪。

「可、可是她这样一改，故事节奏变得很轻快呢！一下就看完了！」

「是啊。快速杀光敌人，然后又用惊人的速度准备支配世界。」

征服世界所需的三步骤是什么啦。要是我在书店看到那种励志书，一定会毫不犹豫烧掉它。立刻烧掉。接续在后面的文字隐约可见雪之下小姐潜在的愿望，使我感到恐惧万分。

「呃，嗯。那个啦，或许是因为前面的剧情太粪，那家伙也看得很烦躁吧。我不知道啦。」

尽管称不上护航，我暂且下达结论。不对，更正。除了下达这样的结论做为妥协点外，我想不到以后该如何跟雪之下继续相处。

总而言之。

「那接下来交给你了。」

「咦？」

我把原稿塞给目瞪口呆的由比滨，掉头就走。回家后跟小町一起耍废。但愿这样的生活能永远持续下去。明天会更～开心对不对！哈姆太郎？（注3）

「等、等一下自闭男！咦，什么叫交给我了？」

结果是我在作梦。由比滨一把抓住理应已经回到家中的我的后颈，白日梦转瞬即逝。

「就是……我不是说了吗？这是接龙小说。现在轮到你写了。拜啦。」

我留下这句话，踏上归途。回家后下略。

「不不不，我做不到！我不看小说的！怎么可能写得出来啦我说真的！」

唔。本想模仿顺势将责任推给下属的垃圾上司，把工作塞给她，失败了吗？不过，要是她拒绝就糟了。我营造出「这样大家至今的努力都会白费……！」的气氛，试着拜托她。

「咦？啊，呃，哇——！知道了，知道了啦自闭男！我、我写就是了，不要把头贴在地上！」

顺带一提，「拜托」一词带有与「下跪」相近的言外之意。

「由比滨，你愿意写吗？」

「嗯、嗯。我试试看……怎么办，要不要找大家商量……」

她不安地自言自语，我实在有点愧疚。

这件事果然要尽快搞定。

我重新下定决心。

《九十九天后会死的满等的我被骑士团赶走一边过着慢活生活一边在迷宫里开无双与反派圣女度过幸福快乐的生活～乐园驱逐篇～》

「——你说你是打倒魔王的英雄？」

自称巴隆的宝石商人将柔软的嘴唇贴到我耳边，轻声呢喃。他的声音甜美诱人，宛如泡沫制成的弦乐器奏出的曲调，为我的背部带来一阵酥麻感。

我心想，真是个奇妙的男人。

外表看似放荡不羁，身上却戴着好几个耀眼的昂贵饰品。羽毛帽底下是一对目光平静、色彩静谧的眸子。

每当被那如同黑曜石的双眸注视，我都会产生所有的光芒都被他吸进内部的错觉。或者说不只光芒，我本身也包含在内。

「呜呼，真不可思议。在我眼中，你仅仅是个平凡的少年。」

「何、何出此言——！」

不知不觉间，他抬起我的下巴。骨节分明的手指沿着它抚摸。

宛如栖息在伊甸园的黑蛇，在肌肤上爬行，企图对禁果伸出毒牙。

「大英雄可爱的那一面，谁都看不见的重要部位——再让我看得清楚一点吧。」

巴隆的另一只手缠住我的五指，再怎么抓都无法挣脱。我是无力的。在这个男人面前，英雄之名于床单上逐渐凋零。

「——现在就让你解脱。」

柔软的突起物冒出一颗颗带有硬度的疙瘩，彷佛被他手指的动作引诱。淫靡的水声于身体内部响起。乐园之泉的门，大概会被那只节节分明的蛇撬开吧。

我再也回不去伊甸园了。

「啥？」

为什么回不去啊。

莫名其妙。

是说，真的莫名其妙。

我生气了。所以我揍他一顿回家了。然后睡觉。结束。

＃离命运之夜还有三天

＃总武高中文艺社

＃九十九天后会死的我

＃点赞的人我感兴趣的话就会去追踪

＃想跟喜欢英雄的人交朋友

＃海老名

＃三浦

＃我第一次写小说耶

＃比想像中好嘛

「这是什么东西啊。」

看完那篇文章，平冢老师开口第一句话从五个字增加成七个字。

我无视她像在询问我的视线，再度假装听不懂。

「什么叫『这是什么东西啊』。问问题的时候要……」

这时，一阵风吹来。平冢老师的拳头从我的脸颊旁边擦过，速度快到我的眼角余光勉强看得见残像。

「我再问一次。这是什么东西啊。」

好过分。她之前明明也用同样的手法跟我装傻。大人好卑鄙。

「这、这这是，您要的小说啊。这是由比滨写的份……」

「喂，比企谷……」

她的呼唤声，俨然是从地狱深处爬出的恶鬼。

「不用我说你应该也知道，对我说谎不会有好处喔。」

「是、是的，那个，一个人写对由比滨来说好像负担太重，所以，嗯，她向诸位友人寻求协助，写出来的就是那个……」

「结果写出这什么东西……？」

「……是、是什么东西呢？」

称之为暗锅太那个了。混沌唤来混沌的混沌小说在此爆诞。

想吐槽也会因为整篇都是吐槽点的关系，反而不知道该从何吐槽，处于无敌要塞状态。这究竟是什么东西？

「唉唷，不过这种类型的小说，说实话也有搞头吧？可以当成搞笑小说看。」

无论如何，我可不能让交出去的原稿被退稿。身为编辑，我必须像台机器一样假装没看见成品的拙劣之处，将它提出。那就是编辑的工作。

「说起来，前半段的文章是什么鬼？作者罹患了用太多常用词汇会死的病吗？……先不说这个了。更大的问题是，这个突然登场的宝石商人巴隆是谁？」

嗯，您说得对。由比滨——不，是海老名（大概）的文风，该怎么说呢，散发出强烈的耽美气息，该先从这边吐槽起。

「喔。就，如您所见，是个美男子角色吧？帅哥再多都不会有坏处，考虑到游戏化时的加成作用，走这个路线再正常不过。」

「竟然已经考虑到跨媒体展开？」

平冢老师为我远大的市场战略不寒而栗。

「……算了。我还有一半没吐槽。话说回来——」

平冢老师刻意避免实际念出来，指向纸上的文字。

她所指的是「柔软的突起物冒出一颗颗带有硬度的疙瘩～」、「乐园之泉的门，大概会被那只节节分明的蛇撬开～」等充满性暗示的字句。

「这种句子，你觉得我这个老师有办法纠正吗？」

「咦，什么东西？您在说什么？哎呀——我听不太懂耶。咦？平冢老师，您从这几句话当中解读出了什么意思？」

比企谷八幡，这时来了个漂亮的故作无知。通称「只有这个我有点无法护航」。八幡是乖宝宝，不懂色色的事。我说，那充满文艺气息的描述方式，我是真的看不懂她在写什么。

「从这边开始最夸张……」

她翻到下一页，接着指向另一段。

我再也回不去伊甸园了——耽美气息达到顶点后，紧接着是奇怪的文体。

每句话都短短的。开头还会加上＃字号……

「当这是IG喔！」

清澈嘹亮的吐槽，令我连自己编辑的身份都忘了，超想疯狂点头赞成。

这已经是会让人误认成刚出道的鬼才作家开发出过于崭新的行文方式的等级。只要随便掰一个类似「我试着用小说来呈现现代的社群网站」的理由，搞不好可以得个三岛奖（注4）。

卷卷头小姐三浦由美子所写的文章真惊人（这是「真低能」的委婉说法）。

总之，这个混沌程度连优秀的编辑都救不回来。

平冢老师不停翻页，无法收拾的一百天份的冒险故事，以大纲的形式展开。

看完的感想浓缩成短短一句话。

「……到底要怎么办？」

到底要怎么办。没怎么办啊。完蛋了。放弃吧。当编辑最重要的就是要学会放弃。反正就算出了本粪作，砸的也只有作家的招牌。哎呀～作家真辛苦～现在的我达到了这个境界。

「能配合这种无厘头的风格写出正常文章的人……很难找到吧……」

「咳咳！」

「唉，只差最后一段的说……就没有够资格写大结局的人才吗……」

「咳，咳咳！咳咳咳！」

不知为何，在我为此苦恼之时，坐在我正前方的可疑人物拼命咳嗽刷存在感。

「……咦，老师，您干么？」

她都表现得这么明显了，我也不能不问。这是在恐吓我主动关心她。

「没有啦，那个……看到她们自由自在地创作，我也有点想起过往的热情……」

「喔。」

平冢老师一反常态地扭动身躯。

「我也可以说是资深国文教师了。别看我这样，以前我在梦小说界可是被称为无声之静……」

「呃，可以不用讲这些没关系。」

现在在讨论的是「一直都是这种调调剧情一发不可收拾真伤脑筋」。

「是吗……」

哭哭。平冢老师沮丧地垂下头，我在她的肩膀处看见少女字体的拟态词。这个前文艺少女有时候满可爱的。

「可是，这样的话——」

抬起头时，平冢老师已经恢复成国文老师，或者说是侍奉社顾问。

「——比企谷，只能由你亲自操刀了吧。」

「我想也是……」

说实话，这个结局我早预料到了。

键盘被我敲得喀哒喀哒响。

不晓得我在房间的电脑前坐多久了。

答应平冢老师强人所难的要求，曾经委靡不振的心情，如今已被我抛到脑后。

全新的事物经由我的手诞生。

从其他人——连名字都不知道的其他人，连长相都不知道的其他人手中接过接力棒，将故事导向结局。

那个感觉对我来说意外舒畅。

手指以惊人的速度俐落地移动。文章跃于萤幕上。有什么东西正在逐渐成形。

——写作的喜悦。

难以言喻的情绪于心中往复，若硬要为其命名，就是这个了吧。

于是，我们既漫长又短暂的一百天的冒险，终于迎接结局。

我现在甚至会感到惋惜。

我依依不舍地将视线移回自己所写的文章上——

完

2注   Zeebra为日本的饶舌对决节目《Freestyle Dungeon》的主持人，该节目会邀请来宾担任让挑战者挑战的「怪物」，于怪物房待命。

3注   哈姆太郎的饲主小露在每话动画的结尾都会用「今天真开心呢。明天会更开心对不对，哈姆太郎！」作结。

4注   指日本的文学奖三岛由纪夫奖。

** 意外地，叶山隼人迷惘了很久。

作者：川岸殴鱼／插画：ななせめるち

星期一。放学后的教室。

昨天因为有练习赛的关系，足球社停止练习一天。

叶山隼人在喧嚣声中独自坐在自己的座位上看书。书名是《近代哲学入门：从存在主义、结构主义到后现代主义》。是他刚刚才趁午休时间去图书馆借来的书。

叶山隼人看了一会儿，却提不起干劲，将视线移向窗外。

空中飘着带有秋意的卷积云。

隼人看着白云，轻声叹息。

「隼人，你怎咧？干么那么感伤？」

跟他搭话的是户部翔。

是他在班上的朋友，和隼人一样是足球社社员。

「我只是在看书。」

「嗯——？看啥……哲学？哇塞——看这么深奥的书啊。」

「还好，入门书而已。内容就是把每位哲学家的思想简单整理起来。海德格、维根斯坦、德勒兹、伽塔利。」

「咦，啥东东⁉哇咧——虽然不知道他们是谁，大家的名字听起来都好强。打人感觉会很痛。」

「嗯、嗯……是啊。」

隼人判断继续跟户部解释也没意义，随便扯出一个笑容，结束话题。

户部想跟他聊的似乎也不是哲学。

「先不说那个叫什么德格的人了，隼人，没事吧？我看你一直一脸忧郁，想说是不是发生了什么事。」

「喔，嗯……没有啦。」

户部说得没错，隼人的心情一直好不起来。

借哲学书来看的原因也在于此。

而他忧郁的理由……

「该不会是那个吧？昨天的练习赛？难道你还放在心上？输了是很可惜没错，不过没办法啊。对手是县内四强，你对上的六号又是他们的队长，本来好像还是J联赛青年队的球员。」

「嗯，我有听说。好像是这样……」

「那有什么办法咧。想开一点啦。」

昨天星期日举办了和总武中央工业高中的练习赛。

结果是三比零。

王牌隼人被对手的队长——担任组织型后腰的高田压制住，无法射门。

比分和在球场上的表现都输得彻底。

队友们灰心丧志，十分不甘。

然而，拿出全力依然输了比赛是家常便饭。

隼人当然也不是第一次尝到败北的滋味。

尽管会不甘心，这在足球场上是稀松平常的景象……

隼人却一反常态，现在还是愁眉苦脸的。

「下礼拜还有跟市川南的练习赛要踢，把心情调整好啦。下次爽快地赢下一局吧。」

户部拍拍隼人的肩膀鼓励他，这个行为确实很符合他社团开心果的身份。

但隼人仍旧沉着一张脸。

——因为他烦恼的源头并非胜负。

「户部，我说……」

「怎么了？隼人。」

「那个六号……是叫高田对吧。」

「就跟你说没办法了。那家伙超强的。根本作弊。」

「他的身体能力和技术等级确实都很高，视野又广。体力也很好，比赛到了后半他的速度也丝毫未减。」

「真的，根本是怪物——吃什么东西长大才会变成那样啊。那家伙绝对有在吃蛋白粉。死都不想在正式比赛撞上他。」

「嗯，是没错，不过……」

「不过？不过什么？」

「那个怪物也只能止步于县内四强啊。」

「因为千叶还有船桥队嘛。」

「对，船桥是全国大赛的常客。连船桥队的选手都没几个能当上职业球员，顶多只有一两个。」

「这……对啊。」

「而当上职业球员的那一、两个人，也会在职业球员激烈的竞争中遭到吞噬，大多在数年后成为战力外名单。」

「你怎么了？尽是讲这些沉重的话题。」

隼人没有马上回答。

他陷入沉默，仔细整理思绪。

「……我在想，我的颠峰期搞不好就是现在。」

「咦——什么意思？」

「足球社的下任队长、在班上颇受欢迎的人，这就是我的颠峰期了吧。」

「啥啥啥我听不懂。」

「跟我刚才说的一样，以我的实力，要当上职业足球员还差得远。连在昨天的比赛上把我防死的高田都有困难。我的足球生涯大概会在高中告一段落。」

「说不定会在大学的社团继续踢。」

「那也只是踢好玩的。没有意义。」

「可是隼人，你也很会念书啊。」

虽说隼人的在校成绩不差，终究只是用来应付考试的。

仅仅是采用有效率的手段顾好背诵科目，提高文科的分数罢了。

他自己也很清楚，这跟真正的聪明不一样。

「不管是学业还是运动，我都只有一般水准，不是真正厉害的人。」

隼人自嘲地笑了。

「去普通的大学念书。去普通的企业上班。领普通的薪水，做普通忙的工作。在职场也普通受欢迎，下班后喝着高球跟后辈炫耀『我以前很抢手』的大叔。那就是将来的我。」

「怎么会——你会有更高的成就啦！」

「不，我没有值得拿来说嘴的可取之处。没有能和别人竞争的武器。」

「你都这么说了，那我怎么办？」

「呃，你没问题的吧……」

——因为别人大概没对你抱多大的期待。

隼人将讲到一半的话吞回去。

他在不论好坏的意义上备受期待，而他活着就是在回应那些期待。

所有人都认为隼人做得到。

家人的期待、教师的期待、朋友的期待。一路走来，隼人回应了所有的期待。

有时连不认识的女性的期待都会回应……

结果打造出如今的叶山隼人。

会念书、会运动，男性跟女性都喜欢他，活泼开朗的叶山隼人——

隼人自己变得无法相信那样子的叶山隼人的未来。

「咦——我没问题吗——没想到隼人对我评价那么高——」

户部对隼人那句话照单全收，悠哉地笑着。

这正是户部不会有问题的原因。

「总而言之，我觉得自己再这样下去不行。该怎么说呢，我需要本质上的自我风格。与他人的评价无关，超越胜负，类似核心理念的东西……」

「嗯——完全听不懂。所以你才在看那个斯坦先生的书？」

户部用「斯坦↗先生」这种语尾微微上扬的语调发声。

那是他叫当地的前不良少年学长的语调。

「……算是。想要拥有自我，哲学果然是必要的吧。」

「原来如此——既然你这么说，那就是了吧。虽然我一头雾水。斯坦↗先生讲的话应该也很有道理。」

很遗憾，跟户部聊这个极度不适合。

不只户部。大冈和大和八成也不行。

若要找能讨论这种话题的对象……

——顶多只有比企谷八幡吧。

隼人瞄向比企谷。

八幡不是会在放学后于教室久留的类型。

他已经收拾好东西，从座位上起身。

「那个，比企谷……」

隼人几乎是在下意识间叫住他。

「嗯？干么。」

比企谷懒洋洋地回头。

依然是那双死鱼眼。他瞥了隼人一眼，视线立刻落在桌上的《近代哲学入门》上。

然后又把视线移回隼人身上，表情几乎没有变化。

「没有……抱歉。没事。」

隼人忽然害臊起来。

比企谷一语不发。

然而……

——啊——这是那种遇到烦恼，突然看起哲学书刷存在感的模式。还不是看原典，而是入门书啊。

隼人却有种他在这样说的感觉。

不行。不能找比企谷商量。

比企谷是想事情犹豫不决的专家。

而隼人在这方面还是新手，经历差太多了。

「所以你找我干么？我要走啰？」

隼人发现自己叫住比企谷后，一句话都没说。

「噢，不好意思。没事。」

「嗯？莫名其妙。」

比企谷转身离开教室。

只留下令人不适得恰到好处的气氛。

「怎么了隼人？干么突然叫住他啊——我还以为你要拜比企鹅为师咧。」

户部可能是想改善尴尬的气氛，然而……

「不，我也不全是开玩笑。老实说，可以的话真想请他收我为徒。因为他是现实主义者，擅长某种生存策略。出社会后那种人会很有优势。有成就的出乎意料地都是那类型的人。我是这样觉得。」

「真的假的？是喔？」

户部把他的玩笑话当真，夸张地向后仰，表示惊讶。

隼人跟比企谷并没有特别熟。

但那有点豁达的气质，以及独特的思考方式。

再加上完全不向同侪压力屈服、我行我素的生活态度。

而且，他在遭受社会摧残前已经在高中被摧残到整个人快要磨损殆尽的地步，应该也不会再次受到现实的阻碍。

——有可能脱胎换骨的人，是比企谷。

隼人如此心想。

足球踢得不错，长得还算帅，成绩也称得上优异，以及不会破坏气氛的贴心之处和开朗的个性。

——我什么时候变得这么渺小的人……

隼人悔恨地握紧拳头。

去普通的大学念书。去普通的企业上班。过普通的生活。

自己会停留在这个程度吗……

想超越这个水准，需要突出的个性和突出的才能。

若能获得这些，拜比企谷为师根本不足为耻。

「拜师……说不定该认真考虑看看。不如说若我觉得自己必须这么做才能更上一层楼，立刻采取行动可以说比较符合我的个性。不对，从更积极的角度思考的话……或许该……」

隼人碎碎念着，反覆自问自答。

练习赛输掉后，烦躁的心情一直闷在隼人心中。如今他有种照进一束微光的感觉。

「隼人，你没事吧？怎么了？你在想什么？惨了惨了，你是不是斯坦↗先生看太多啦？」

户部不安的声音也传不进他耳中。

「抱歉，我今天先回去了。」

「咦——干么干么？隼人你好冷淡喔。」

「我想起来有事要做。」

隼人抛下户部，飒爽地从座位上站起来。

「什么事？你该不会真的要去拜师吧？去侍奉社跟比企鹅拜师之类的？不会吧。」

「真的对不起。明天见。」

隼人没有回头，对户部挥了下手，离开教室。

叶山隼人的决心已经无可动摇。

隔天，星期二早上。

待在教室的户部一大早就做出激烈的反应。

「咦——隼人，你怎么了？为什么在看轻小说⁉」

「奇怪吗？」

「当然啊。因为你不是会看轻小说的人嘛！对了，你昨天说过拜比企鹅为师也不错……」

「嗯，发生一点事，我决定拜材木座为师。」

「为啥！发生什么事才会变成那样？是说材木座是谁啊？」

「你不认识吗？他是比企谷的朋友。」

隼人对材木座也没什么印象。

不知为何在女仆咖啡厅大笑的邪恶宅男。

他对材木座只有这点程度的认知……

「我只知道有这个人，你为什么要当他的徒弟？」

「因为他拥有异于常人的某种特质。」

隼人不好意思拜比企谷为师，便去寻找类似的替代品，最后发现了他。就是这种感觉。

「他看起来确实异于常人。」

「不迎合周遭，确立稳固的自我风格。这一点很重要。」

隼人边说边轻快地翻阅书页。

右手……装备着黑色露指手套！

「手指从手套里面露出来了！超土的！土到爆！」

「这是师父给我的。好像是流派的证明。」

「不要啦，隼人。真的很恶。」

「不行。师父说，戴着它看轻小说时的专注度截然不同。」

「啊——是喔……那你在看怎样的轻小说？」

「现在还在开头部分……主角刚被卡车撞到。」

「交通事故的故事？」

「师父说，总之现在这种风格的轻小说似乎是最基础的。」

「哦——那很狂耶，在驾训班考驾照的时候让考生看或许不错。是说最近的轻小说都在被车撞耶。」

「对啊，目前就在被车撞。」

隼人再度用装备露指手套的右手，优雅地翻阅轻小说的书页。

某一天突然装备露指手套上学，戴着它看起轻小说……

理应会被嘲讽到不成人形……

但那个人是叶山隼人，因此没人敢随便嘲讽他。

说起来，连他的行为是奇特的玩笑抑或只是改变兴趣都无法判断。

正因为对象是隼人，其他人才没有勇气自己扛下这个责任去追根究柢。

班上的人远远监视着露指手套版的叶山隼人。

「……隼人怎么了？」

班上的女帝三浦优美子轻声询问……

「吾并无大碍……」

「吾、吾⁉」

连优美子都不禁语塞。

「怎么搞的？完了完了，隼人变成中二病了！」

「不，没事。我在职场见习活动的时候不是说过吗？我以后想去外商公司或大众传播公司。出版社当然也在我的目标之中。如果要在出版社的入社测验中获得胜利，果然必须要能展现对该出版社的作品的热情。而师父对作品的热情高人一等。所以我想从他身上学习，好让自己踏出新的一步。」

「听起来有道理，可是不知为何，我觉得结论错很大耶？隼人，第一步绝对不是往那个方向踏出吧！」

户部斩钉截铁地断言。

或许是自诩为隼人最好的朋友的责任感使然。

正因为其他人不方便在这个时机开口，才必须由自己说出来。

「我没你那么聪明，对放眼未来那种事也不太瞭解，不过就是因为这样，我反而看得出你给人的印象分数在直线下滑！」

户部直盯着隼人的眼睛，热情诉说。

连隼人都被他激动的语气压制住。

「……果然是这样吗？」

「轻小说也就算了，那个手套超有问题。换一个人戴，早就因为好感度过低当场暴毙。」

「这个……我隐约有感觉到。」

这是不是一时的鬼迷心窍？

虽说是要确立属于自己的风格，没必要戴这东西吧……

隼人也有这种感觉。

「把它脱掉啦，隼人。那个手套对人类来说还太早了。」

「是啊……」

隼人小心地慢慢拿下露指手套。

然后轻轻放在桌上。

宛如以前的偶像引退时把麦克风放在舞台上的行为。

与此同时，教室里的人明显松了口气。

班上的中心人物隼人脑袋出问题了。而现在，他们知道那只是暂时的迷惘。

「隼人果然在迷惘啊。」

「我确实很着急，处于混乱状态。我承认。输掉比赛的打击应该也占了一部分原因。」

隼人有点害臊地笑了。

户部见状，放心地吁出一口气。

「真的。我超紧张的，想说你变得怪怪的。」

「抱歉，我现在很不安。」

「没必要真的那么不安吧。你的未来肯定会一帆风顺。是超级简单模式吧。你烦恼过头了啦！」

出于放心，户部用一如往常的态度开起玩笑。

然而……

「……不，不对。」

「咦⁉」

户部期待的是谦虚地回以玩笑话的隼人。

他的期待却落空了。

「我的确是没什么兴趣却开始看轻小说，但这件事非常需要烦恼。我不能一直停留在原地。这个想法没错。这样下去，高中时期绝对就是我的颠峰。」

回答他的依然是沉重的话语。

「隼人，就跟你说了……」

「没关系，是我想太多也无所谓。就算是我想太多，拥有危机意识是很重要的。抱歉害你担心了。不过我没事，我一定会化危机为转机。」

「就是因为你讲这种话我才会担心啊。」

户部有点无奈地说。

「就叫你不用担心了。回座位吧，快要上课啰。」

隼人说完便从书包里拿出第一堂课要用到的世界史课本。

这个话题就此告一段落。

之后他像什么事都没发生似的，于学校度过平稳的一天。

上课，午休，下午的课程，最后是社团活动。

已经没人记得隼人失常的行为，各自踏上归途。

隔天，星期三。

户部一踏进教室，就立刻跟朋友兼班上的中心人物叶山隼人打招呼。

「隼人早啊！怎样？怎样？过得好吗！」

他期待着告别迷惘，恢复原样的隼人回以明快爽朗的招呼，可是……！

「ขอ ใบเสร็จ หน่อย ครับ<Koo Paisetto Nooi Kura>‼」

隼人说的话他完全听不懂！

「咦！隼人你说什么？」

「ขอ ใบเสร็จ หน่อย ครับ<Koo Paisetto Nooi Kura>‼」

隼人坐在座位上，对户部轻轻挥手，笑咪咪地说道。

「Koo？Paisetto？隼人坏掉了！昨天虽然也很恐怖，你现在根本故障了吧！陷入Koo Paisetto状态要怎么救啊。」

「喂喂，没礼貌。这是泰文啦，泰文。」

隼人拿起一本书给户部看。

那是给新手看的泰文会话书。

「咦——原来你讲的是泰文啊！」

「嗯，我昨天开始学的。」

但隼人的书上已经贴了好几十张便条纸，跟七彩的装饰一样。甚至有种用很久的感觉。

「隼人好厉害，突然讲起泰文。」

「不不不，就跟你说我只是新手了。」

隼人嘴上在谦虚，看起来却有点高兴。

「……所以刚才那句Koopai是什么意思？」

「请给我收据。」

「哇塞！你要收据啊？在便利商店买薄荷糖的收据行吗？」

户部急忙搜起裤子的口袋。

他从臀部后面的口袋拿出皱掉的收据，放到桌上。

「不用……谢谢你，那只是例句。」

「喔，这样啊，那就不用收据啰。是说是说是说！为什么是泰文？」

「我觉得未来是泰文的时代。」

隼人的语气充满自信。

「咦咦！是喔？」

这不是别人，而是隼人的看法，因此户部很想尽量表示同意，然而……

他实在无法理解，头上冒出一个个问号。

「户部，你听好，美国的霸权开始动摇，中国的势力愈变愈强。以后是中美两大强国互相竞争的时代。为此要先学好中文……但那个时代应该也很快就会过去。接下来恐怕是印度的时代。可是，那个时代也会过去。接着是非洲的时代……考虑到国家之间的力量平衡跟日本国内学习该国语言的人数，学泰文是最好的选择。我是这样判断的。」

隼人目前是高二生，即使他在大学毕业后立刻出社会，最快也要等五年。

做事时必须时常展望未来。

这个想法促使隼人跑去学泰文。

「我虽然不懂……隼人，你是不是想太多了？如果你对泰文有兴趣也就算了，想那么复杂有意义吗？」

「เสื้อ คุณ สวย จังเลย ครับ<Sua Kun Suai Cyanruui Kura>。」

「啥啥啥？『我要把有意见的人杀了』的意思？」

「不对！เสื้อ คุณ สวย จังเลย ครับ<Sua Kun Suai Cyanruui Kura>‼」

「听不懂啦！」

户部双手一摊，表示自己无法理解，反应激动到彷佛他才是外国人。

隼人也无奈地摊手，做出略有外国人风格的反应。

「我说的是『那件衣服真好看』。」

「隼人，这是制服耶！你也穿着同样的衣服啊——！」

「是没错……就说我在练习了。」

「这句话要用在什么场合啦。隼人，用泰文称赞别人衣服的机会不多喔。」

「不，现在你可能会这么觉得，但未来日本可能会因为人口减少的关系导致国力衰退。东南亚国家则必定会蓬勃发展。」

「是没错，可是用不着称赞人家的衣服吧。」

「可以拿来开启话题啊。不管是哪国人，有人称赞自己穿的衣服好看应该都不会反感……」

隼人难得露出沮丧的表情。

他也隐约察觉到自己有点意气用事。

「隼人，你昨天也很奇怪，今天则是真的有问题耶。到底怎么了？可以理解你想为未来做打算，可是你现在的定位超不稳定的。」

「会、会吗？」

「对啊。早上一进教室就看到你用神秘的语言说话，半句解释都没有，有点恐怖。」

「别人觉得我恐怖也没关系。因为这就是我要走的道路。」

「直觉告诉我，你误会了啦。你该走的不是那条路！」

「你怎么知道！我不希望我的颠峰期结束在高中时代。我需要出社会后还能继续使用的武器！เสื้อ คุณ สวย จังเลย ครับ<Sua Kun Suai Cyanruui Kura>‼」

「就叫你别夸我衣服了！我们明明穿一样！」

其实隼人想用泰文说更加帅气的台词，可惜他昨天晚上才开始学，根本没那个能耐。

「我……不希望自己将来要依附在高中的回忆上……」

「我懂，我懂啦，你先冷静一下。虽然我讲这个很奇怪，基础功比较重要。先认真上英文课就够了吧？」

「英文大家都在学，这样拉不开差距……」

「这种话等你能讲出一口流利的英文再说呗。」

「这……嗯……是啦。」

隼人难得被户部说服。

竟然会发生这种状况，可见他有多着急、多迷惘。

「欸，你从昨天开始就不太像你耶。」

「นี คือ หนังสือเดินทาง ของ ผม ครับ<Niikuu Nansuuduutaan Kon Pomu Kura>。」

隼人将视线从户部身上移开，看着自己的桌子说。

「这又是什么意思？」

「这是我的护照。」

「这是我刚才放在桌上的薄荷糖收据！」

「噢，那我知道。ระวัง ร ถกระบะ นะ<Rawan Rottogu Ra Ba Naa>。」

「啥？」

「请小心卡车。」

「怎么突然用卡车造句！你一直记着轻小说那件事嘛！哇咧——！隼人，你考虑清楚。真的太突然了！因为你从来没跟我们聊过泰国。」

「……噢，这个嘛……是啊。」

「如果你对泰国有兴趣，想去泰国之类的，那还没关系。这次再怎么说也太奇怪了。」

「说实话……我觉得你是对的。」

意气用事的隼人也不得不承认。

确实如此。

会讲泰文对未来有什么帮助，应该有许多种看法。

然而，大前提是对泰国没兴趣的人跑去学泰文，也拿不出多好的成绩。

「看，对吧？冷静点。放心。你就算不会泰文，将来也肯定是一片光明。」

「就算我不看轻小说也不讲泰文？」

「稳到不行。」

户部看着隼人的眼睛频频点头。

「这样啊。看来我又太着急了，忍不住往奇怪的方向想。」

隼人叹了口气。

「好了啦。这样真的很吓人。只不过是在比赛上被电过一次，你太放在心上了啦。」

户部似乎也放心了。

「嗯。说得对。ผม หลง ทาง ครับ<Pomu Ron Taan Kura>。」

隼人露出有点害臊的笑容。

「咦？啥？你说什么？」

「我迷路了。」

「真的，隼人！你在人生的道路上迷路超久的！」

两人因户部的吐槽相视而笑。

于是，隼人只学了一天的泰文。

本以为班上的中心人物叶山隼人的失常行为，会就此告一段落……

隔天，星期四放学后。

若是平常，户部会第一个跑去找隼人，在社团活动前跟他聊几句。

今天他却隔着一小段距离观察隼人。

大概是在警戒他有没有戴露指手套？有没有突然跑去学陌生的语言？有没有做其他神秘行为？

「隼人——去社团啰！今天也去挥洒青春的汗水呗。」

他仔细确认，判断没问题后，过度亲昵地勾住隼人的肩膀。

平常的隼人会抱怨着「喂喂喂，你有点烦喔」，推开黏到他肩上的户部……

「嗯，一起挥洒青春的汗水吧。」

他却用力回勾户部的肩膀。

两人勾肩搭背，令人忍不住怀疑他们是不是今天要从高中毕业。

「咦？隼人？」

「怎么了？今天也努力练球吧，户部。」

「喔，嗯。」

户部主动松开勾住隼人肩膀的手，大概是觉得不自在。

「干么？」

这次换成隼人勾住户部的肩膀。

「不不不，我才要问你干么。」

户部闪过他的手，用带有一丝恐惧的眼神凝视隼人。

「没有啦，我发现了。能点亮人生的不是宅度，也不是语言能力，是友情。」

「喔，原来……你还在迷惘啊。」

「这就是我迷惘过后得出的结论。文化运动会变。连国势都会随时间变迁。尽管如此，还是有东西不会改变。那就是我们的友情。」

叶山的永远是朋友宣言。

户部听了明显感到恐惧。

「……嗯、嗯。很高兴你这么说，但我有点难为情……不如说这句话好假掰……还有……」

户部忽然压低音量。

「嗯⁉」

「海老名一直在用很可怕的眼神看我们。」

隼人顺着他的视线看过去，确实看见了海老名姬菜。

她看似坐在自己的座位上看书，视线却飘向其他地方。

正在用热情如火的眼神观察隼人和户部。

「是在看我们没错。」

「唉唷，我之前不是说过吗？我有点喜欢海老名……就那种感觉……」

户部一面偷瞄海老名，一面跟他讲悄悄话。

「嗯。」

「所以我不希望被海老名当成搞BL的人，那个，我希望她把我当成一名异性看待，就是这样。」

「原来如此，可以理解。」

「你明白我的心情了？」

「那当然。我没打算阻碍你的恋情。所以……以后在教室里，我们就偷偷培养友谊好了。」

隼人像在跟他窃窃私语般，把嘴巴凑到他耳边，说出下半句话。

「哇咧——！隼人！这样更不行啦！」

「为什么？你不希望海老名用好奇的眼光看你吧？」

「偷偷摸摸更容易被她注意！我们在这边讲悄悄话，反而会严重刺激她！」

隼人瞄了海老名一眼……

她的镜框显得比平时还要红。

那股热度甚至让人觉得镜框彷佛是用滚烫的岩浆制成的。

「哦——这样啊。」

隼人对BL一窍不通。

同时也没有偏见。

也不觉得有必要请她戒掉兴趣。

「说实话，我不太懂那方面。不知道该怎么做。算了，我们就来燃烧青春吧。」

「呃，隼人，你真的怪怪的。」

「有吗？到头来，友情才是最重要的。这个结论这么奇怪？」

「结论本身没问题，但不太像你。我有点不喜欢那样的你。」

「是吗？我很喜欢愿意为我担心的你，觉得你比想像中更可靠。」

率先对隼人这句话做出反应的，是海老名。

她轻轻抖了一下。

当事人户部则因为隼人突然对自己说这种话，不知所措。

「呃，感谢你的称赞，不过……」

「เสื้อ คุณ สวย จังเลย ครับ<Sua Kun Suai Cyanruui Kura>‼」

「不用夸我衣服好看啦！」

他略显不耐地吐槽。

「我想说好不容易学会，不小心就说出来了。」

「结果，你只是因为一时迷惘才讲那种话吧。」

在户部眼中，隼人这几天的失常行为愈来愈混乱。

不是基于亲爱之情，而是一时迷惘导致叶山陷入错乱。

他八成这么认为。

「没这回事。我是经过审慎的思考才得出这个结论。结果最重要的是真正的友情。只要有能称之为真物的存在就够了。」

「啥？」

「去那里寻找吧。」

「哪里？」

「足球社社办和操场。透过足球培养一辈子都不会动摇的友情……来，今天也一起去吧！」

隼人紧握户部的手，用力拉扯。

海老名没有放过这一瞬间，身体一颤，彷佛是自己的手被握住。

似乎在偷偷享受。

然而，攻不过隼人——不如说单方面承受着他的友爱的户部……

「隼人，这样真的很恶！」

略为强硬地拍掉隼人的手。

「怎么了？」

「我说……我很高兴你喜欢我，可是这么黏人一点都不像你。」

「是、是吗……」

「这不是友情，比较像在依赖人……到头来，你是因为一直没有自信，觉得不安，才突然跑去依赖友情吧？我也不清楚啦。你有烦恼我可以听你说，但这样并不像你。」

从户部口中传出的，是比想像中更加严厉的话语。

——不过，他说得没错。

隼人自己也没意识到，这确实不是友情，仅仅是在依赖人。仅仅是在跟对方宣泄自己的不安。

「对不起。」

「不、不用道歉啦。我只是希望你恢复原状。」

「这样啊。嗯，你说得有道理，这样是不对的。」

——没想到会有被户部骂的一天。

看来黏在一起的友情路线也得暂时收回了。

——虽然这样对海老名不太好意思……

隼人偷看了海老名一眼。

海老名用课本挡住视线，兴奋得全身颤抖！

「暴娇……户部是暴娇。」

她嘟囔着隼人听不懂的词汇，颤抖不已。

这个展开似乎也戳到了她的萌点！

「总、总之，我会恢复正常的，抱歉跑来黏你。」

「不不不，你反省成这样也会把气氛搞得很尴尬。我觉得斯坦先生↗也会说这样做是错的。你先停一下吧。」

顺带一提，斯坦先生↗是语言学家，照理说不会对黏在一起的男生发表什么意见。

「是啊。要换条路走就得趁现在。」

隼人收回肤浅的友情路线。

他的迷惘期持续了很久。

这次想随便寻求友情的帮助，结果又搞错了。

隼人的迷惘依然看不见出口。

不知为何，只有海老名很享受这个状况。

隔天，星期五的午休时间。

「吃饭啰！啊——好饿喔。」

户部理所当然地拿着自己的便当跑到隼人的座位。

这是每天的例行公事，校园生活中最愉快的时间之一。

隼人的动作却很迟缓。

都下课了，他的手还在画东西。

「喂喂喂，隼人，吃饭了，吃饭呗。」

「嗯，等我画完这个。」

「嗯？你在干么？」

「噢，这个啊。这是手绘明信片。」

隼人得意地秀出一张明信片。

上面画着南瓜的图片，以温暖的笔触写着「感谢世人」。

「哇咧——！隼人，你烦恼过头，变成老爷爷了！」

「这几天我想了很多。到头来重要的果然是充实的老后生活。再怎么努力念书、埋头工作，老后不能度过健康愉快的生活就没意义了吧。我想寻找老了也能乐在其中的兴趣，开始画明信片跟种盆栽。尤其是盆栽，得花好几十年才种得好。」

「等等，隼人。我们还没出社会，你怎么已经在想退休后的生活？」

「我一直在想，就算高中过得不错，大学过得不好就没意义了。就算大学过得不错，出社会过得不好就没意义了……就算出社会过得不错……」

「老后过得不好就没意义了⁉」

「正确答案！」

隼人爽朗地竖起大拇指，眨了下眼。

「什么叫正确答案！你走得太快没人跟得上啦！烦恼过头整个人都变得好奇怪，这样戴露指手套还比较好！」

「怎么会！户部，一起度过理想的老后生活吧。一年四季我都会寄家庭菜园种的菜和明信片给你。」

「那我会有点高兴！」

户部边说边斜眼观察海老名的反应。

海老名的眼镜散发阴沉诡谲的光芒……

看来连老年版的隼人户部配，都在她的守备范围内。

真是可怕的高手。

「隼人，别想老后生活了，活在当下吧。」

「那当然。我只是想要一辈子的兴趣。跟之前不一样，不是鬼迷心窍。我的心态没那么老。」

「那就好。吃饭吧。」

「嗯。」

隼人露出清爽的笑容，拿出便当。

然后熟练地打开便当盖……

里面装着炒牛蒡、鹿尾菜、煮豆皮，还有一份葱和海带芽做的醋味噌拌菜。

「哇靠——！老爷爷的配菜！哇靠——！真的是老爷爷！哇靠——！根本是老爷爷吃的菜！」

看到那个菜色，户部放声哀号。

「怎么了？」

隼人因那激烈的反应面露疑惑。

户部却无视他，全力吐槽。

「便当的配菜老人味超重！食量大的高中男生便当里哪可能出现牛蒡和鹿尾菜！」

「是吗？昨天我点了想吃的菜，结果就变成这样。」

「你刚才还在那边否认，结果心态已经变成百分之百的老爷爷！这不是等等要踢足球的人吃的饭吧。」

户部用双手不停指向隼人的便当，像个正在跟裁判抗议他误判的足球选手。

隼人从昨天开始，就在不断思考老后生活。

该如何迎接人生的终点？

怎么做才能在死前觉得自己度过了美好的人生？

满脑子都在想这种事，自然会没食欲，导致他想吃清淡点的食物……

现在当成午餐尝过后……

「嗯……满足感好低……」

隼人老实承认。

对于肚子饿的高中生而言，午餐吃这样味道太淡了。

「对吧。没问题吗？能靠牛蒡撑过社团活动吗？」

「不知道……」

「来，吃点肉。我的汉堡排分你。」

看不下去的户部，将汉堡排分给隼人。

一口大小的汉堡排，放在牛蒡和醋味噌拌菜之间。

隼人毫不客气地夹起来送入口中。

「唔，好吃！跟醋味噌拌菜的冲击性截然不同。」

「对吧。这可是斯坦先生↗故乡的味道。」

正确地说，斯坦先生↗是奥地利人，所以有点不对。

但那不重要，比起牛蒡跟鹿尾菜，男高中生的身体果然更渴望汉堡排。

汉堡排的肉味渗透隼人的五脏六腑。

「啊啊，这果然是一时的迷惘。」

对男高中生的身体来说，汉堡排的诱惑力相当惊人。

其魅力足以凌驾任何思维。

「对吧！」

用不着户部说，隼人就收回了昨天的想法。

该如何生活、该以什么东西做为心灵的依归……隼人为此烦恼不已，因为太过烦恼的关系，思维跳跃到了老后生活。

不过，汉堡排的美味度一下就驱散了他的迷惘。

「身体很老实。全身上下都在为汉堡排感到喜悦。」

隼人微微颤抖。

海老名也在同时发起抖来。

对腐女子而言，绝对不会放过两人卿卿我我的瞬间。

「我说，隼人，果然还是多吃点吧。去福利社买个能填饱肚子的面包。」

「是啊。」

「你现在没精神对不对？我去帮你买。等我一下。」

「不好意思。谢了。」

「代价是请我一个面包。」

户部说这句话的时候，已经小跑步跑向福利社。

「嗯。谢谢你，户部。ขอ ใบเสร็จ หน่อย ครับ<Koo Paisetto Nooi Kura>‼」

「你要收据喔！哇咧，隼人居然想报公帐！」

叶山隼人在人生道路上迷途的一个礼拜过去了。

隔周星期一。

上课十五分钟前的教室。

叶山隼人已经坐在自己的座位上，无所事事，看着窗外发呆。

秋空万里无云。

「咦——隼人，你看起来挺有精神的嘛！」

「嗯，这还用说。如果有人一大早就无精打采，整间教室气氛都会变差。」

「呃，隼人，你上礼拜才把气氛搞差……」

户部稍微压低音量吐槽。

「对不起啦。那完全是我失常。现在没事了。」

「真的？」

「嗯。说实话，上礼拜的我太奇怪了！」

隼人露出腼腆的笑容。

这副模样无疑是平常那个阳光的叶山隼人。

「是平常的隼人耶——太好了。我真的超担心万一你一直是那个状态怎么办。所以？你怎么打起精神的？」

「噢，就是……讲白了点，是因为赢了。」

——没错。隼人赢了。

星期日和市南川的练习赛，他们以四比三获胜。

隼人踢进一球，助攻一球，表现十分亮眼。

结果，对上跟上礼拜输掉的中央工业实力相当，或者更强的市南川，他们来了个戏剧性的逆转胜。

「你的子弹远射真的超威的。」

「嗯，说实话，我也这么觉得。」

「看见那发射门，你的女性粉丝又会增加。」

「嗯，说实话，已经变多了。」

今天刚到学校，就有个一年级的女生在校门前等隼人，跟他要LINE。

「不愧是隼人。这么快就有人来搭讪！那当然会打起精神啰。」

「我不是因为这样打起精神的。」

「那是怎样？果然是胜利的滋味？」

「除了比赛赢了外，我挑战过了。我满意的是这一点。」

「喔，啊，这样啊。是喔——」

户部反射性点头，却无法理解隼人在满意什么。

可是，隼人现在并没有寻求户部的理解。

自己回答自己的问题，并且说服了自己。

这样就够了。

「人生颠峰一点都不重要。这种事死掉的瞬间再去想就行了。重要的是要想成为比今天更好的自己，告诉自己这里还不是顶点，挣扎着向上爬。我的顶点还在很遥远的地方。只要我这么想，就不会迎接颠峰期。昨天我的远射确实射中了。但重要的是我成功在那边射门的心情。」

隼人看起来有点激动，滔滔不绝。

还没消化完毕的户部，只是茫然地听着。

「呃——喔——这样啊。」

「没错。很简单。自己的辉煌时期能靠自己决定。打从一开始就没必要烦恼。」

「是啊……」

「老实说，昨天的比赛我也下意识觉得会输。结果我全心全意投入在比赛上，踢着踢着就……」

「哇咧——隼人，你一大早就这么兴奋？」

户部吓到了。

由于他太激动，其他学生也在不停偷看他。

比企谷阴沉不耐烦的视线也包含在内。

即使如此，隼人心情还是很好。

理由要多少有多少，不过单纯是因为赢了比赛，爽快多了。

隼人隐约察觉到那就是真相。

但他无法忍住不在单纯的人类身上添加装饰。

完

** 这是场不能输的婚活

作者：境田吉孝／插画：U35

俗话说，结婚是人生的坟墓。

结婚会有很多麻烦喔。不帮忙做家事也不帮忙带小孩的丈夫，待在家里也只会碍手碍脚喔。想要自己的时间喔。

社群网站往往反映出现代社会的人们内心的另一面，上面从来没少过这类型的话题。

所以，「结婚是人生的坟墓」这句话，大概并没有错。

不过，那是已婚者的论点。这个说法会不会只是事实的冰山一角？

真相虽然只有一个，同时也有许多个面相。

光是立场和固定观念不同，世界在观测者眼中就可能拥有各式各样的色彩及形状。

结婚是坟墓，但没结婚的人——未婚者又会有不同的见解。

我未来也想结婚。顺从「工作就输了」这个先人提倡的伟大论点，娶个漂亮优秀的老婆当家庭主夫。对未来的妻子说的求婚台词就决定是「每天早上都喝我煮的味噌汤吧……」。

闭上眼睛，幸福的婚姻鲜明地浮现脑海。

『八幡，这道味噌汤真好喝。谢谢你每天都为我做菜。』

『别客气，彩加。我才要跟你道歉，让你一个人工作养家……』

像这样……咦？为什么我自然而然把结婚对象想像成户冢？为什么我轻易跨越了名为法律及性别的障碍？

『真是的——八幡，我们不是说好别提这个了吗？我会生气喔？……啊，那我该去上班了。为了这孩子，得多赚一点钱才行。』

『嗯，路上小心。噢，对了，抱歉。今天有款新游戏发售，我可以买吗？』

咦？为什么户冢理所当然怀孕了？还有不给怀有身孕的户冢请产假的日本企业对于上班族女性是不是太严苛了？是说为什么我变成这种废物小白脸？

言归正传。总之「结婚是人生的坟墓」这句话，对于和结婚无缘的人来说，可信度并不高。

尤其是无时无刻都在盼望结婚的人。例如……

「唉……好想结婚……」

在周围还有其他人的教职员办公室内，平冢老师吐出不合时宜的呢喃，她应该无法对这句话产生共鸣吧。

结婚是人生的坟墓。

开完班会后又被叫过去说教，顺便被迫处理简单杂务的我，反射性望向平冢老师，竖起耳朵，不小心偷听到她悲痛的呢喃。

「结婚啊。年轻时我还以为时机到了自然会有对象……唉，人生好难……」

来人啊！拜托来个人把老师娶回家！否则我会忍不住娶走她！

我拼命抑制住差点随着呜咽声脱口而出的呐喊。不如说我都想去户政事务所拿结婚申请书请她跟我结婚了。不仅如此，可能还会把填好的结婚申请书拍照上传到社群网站上发文告诉大家「我今天和女友结婚了☆我们一定会过着幸福快乐的生活☆」然后因为这种无意义的晒恩爱行为搞到一堆人取消关注。

「那个，老师？」

我向那垂头丧气的背影搭话。

「请问，您还好吗？您看起来没什么精神。」

「嗯？喔……」平冢老师转头看过来，感觉有点苍白的脸，露出虚弱的笑容。「没有，我没事，比企谷。我没事……唉……」

她嘴上说着没事，口中却传出深深的叹息。

那悲壮的模样，使我想起数星期前的某一天。

没错，事情发生在由比滨的庆生派对结束后，离开KTV的路上。

我们看见了。不小心看见了。恐怕是在婚活派对上毫无斩获，跑来一个人唱KTV的平冢老师。以及。

『唉……好想结婚……』

留下这句过于悲伤的话语离开的萧瑟背影。

在那之后，平冢老师就有点无精打采。

连早上的班会和上课期间都经常叹气，平常那种热血少年漫的干劲也不知道跑哪去了。

『欸，自闭男。不晓得是不是我的错觉，平冢老师最近好像不太有精神？』

昨天放学后，由比滨在社办担心地说。

『别管她。老师一定也很烦恼。毕竟她正值适婚期。』

同样在场的雪之下如此表示，好可怕。那女人讲话有够直接，好可怕。恐怖。她大概早就舍弃人心了。若我是家臣，可能会觉得「王不懂人心……（注5）」因此背弃她的等级。真的假的，那家伙原来是骑士王喔。她一副会说「比企谷同学，你竟然是我的Master，我感到十分不快」立刻背叛我的样子。

先不说这个了，平冢老师最近低潮到会让人有点担心。想要安慰她，大概只能由我做好入赘到她家的觉悟拿结婚申请书给她，但我实在做不出这种事，到头来，以我的能力什么忙都帮不上。

我再度望向不知为何显得特别渺小的背影。

接着，细若蚊鸣的悲伤低语声，参杂在远方的蝉鸣中传来。

「唉……结婚。结婚啊。唉……」

——俗话说，结婚是人生的坟墓。

这是勇敢挑战这句话的一名女性——平冢静（未婚）奋战的故事。

过了一阵子，事情有所进展。

「欸，比企谷，假设……」

在教职员办公室处理完杂务后，老师说有事要去侍奉社，我们便一同走向社办。途中，她突然开启这个话题。

「这只是虚构的情况，与实际存在的人物、团体没有任何关联，假设啊。」

「怎么了？拼命强调是虚构的……」

她强调成这样，反而让人觉得百分之百是事实。现在是怎样？怎么开始播纪录片了？

「假设这里有一名妙龄女子。」

「喔，妙龄女子。」

「嗯。住在千叶，是高中教师。」

「呃，『假设』这个前提一下就飞到次元的另一端了。在千叶当老师，明显是指您……」

这时，一阵风吹过。平冢老师的铁拳划破离我的脸颊只有数公分的空间。

「……你说什么？」

「没、没有，没什么……」

「那就好。我也不希望拳头染血。产生鲁米诺反应就麻烦了。」

以会发生凶杀案为前提的思考模式，害我差点吓尿。是说你绝对是看柯南知道鲁米诺反应这个词的吧。拿藉由漫画得知的小知识出来秀的大人，有点那个喔……

「再说，你知不知道千叶县有多少妙龄女教师？你有证据证明这是在讲我吗？」

「…………」

是没证据啦，不过从前后文来看，明显是……算了，如果她无论如何都要拿这是假设性话题当前提，我也无所谓。

「那个，然后呢？那个虚构的女教师虚子老师怎么了？」

「嗯。她啊，怎么说呢，就是那个啦。基于年龄因素，她感觉到自己愈来愈想结婚。喔，可是她并没有因此着急喔？她也知道只要照常生活，应该就结得了婚。真的喔，只是因为她所处的环境太难找对象，变得太敏感了。」

「不是，您要花多少篇幅帮虚子解释啊。果然是在讲您自己吧……」

从途中开始就变成你自己的看法了。我可不能当没听见。

「喂，比企谷，千叶县想结婚的妙龄女教师不知道有多少。劝你别乱说话喔？」

「…………」

我说，关键字增加成这么多，符合条件的对象真的有限耶。

是没关系啦。

「顺带一提，关于她的外表，嗯，应该能说满漂亮的。身材也算好，类似散发妖艳女人味的女豹型。」

「我就说那明显是您自己……」

「！是、是吗！你果然也觉得我是那种类型吗！」

「喂，为什么只在对自己有利的部分乖乖承认，先否认一下吧！慎用『假设』这个设定啦！」

平冢老师很快就不打自招。

但这终究是假设性话题，老师继续述说。

事情发生在数星期前。她参加了某场婚活派对，犯下在途中被赶出去的失态之举。

详情我刻意不去过问。总觉得问了她会生气。

被赶出派对会场，心灵受到伤害的她，忽然想到一个主意。

「对了，去参加『宅婚』不知道怎么样。」

我解释一下，「宅婚」指的是限定御宅族参加的婚活派对。

虽说现在那种观念没那么严重，「宅」这个属性给人的负面印象……也就是所谓的非现充感、阴沉感依然深植于人们心中。

为那类型的人敞开大门，寻找理解自身兴趣的同好做为对象的婚活派对。那就是宅婚。

「她非常喜欢某些类型的漫画和动画，觉得在那样的场合上，一定能跟人聊得很开心。」

呣，她说的「某些类型的漫画和动画」，也就是平冢老师喜欢的作品，所以大概是指《超能奇兵》、《神剑闯江湖》这种热血少年漫。

「啊——不错啊。遇到喜欢那类作品的女性，男性御宅族八成会高兴地打开话匣子。有什么问题吗？」

「就是……」

平冢老师愁眉苦脸地解释起来。

在宅婚派对发生的那场悲剧。

『欸，你看？那边那个人打扮得那么正式，却是一个人耶（笑）。哇……（嘲笑）』

宅婚当天的平冢老师，被人暗中这么嘲讽。

理由很简单。前面那句嘲讽中也找得到提示。

「打扮得那么正式」，没错，平冢老师的败因就在于此。

派对当天，她怀着今天一定要找到对象的期待，拿出最大的努力盛装打扮，前往会场。

身穿大胆的漆黑色礼服，搭配色彩沉稳的短版外套，脖子戴着一条珍珠项炼。

硬要说的话，会场里走休闲风的女性较多，平冢老师应该是最耀眼的女性之一。

如今回想起来，那正是悲剧的开端。

为什么？答案很简单。平冢老师太不懂人称御宅族的男性的生态。不对，虽说通称为御宅族，在宅文化如此普遍的现代，御宅族分成许多类型。通称外向型，会打扮、擅长社交又高调的宅宅，应该也是存在的。

然而，去参加那一天的宅婚的男性，大多都不属于这类型。比较偏内向，聊喜欢的动画或漫画可以聊得很开心，却不瞭解时尚，交往经验也不丰富，讲难听一点就是偏阴沉的宅宅。而在他们眼中，平冢老师是什么样子？穿着超有干劲的礼服打扮得漂漂亮亮，相貌出众，身材也好的女性。跟自己一比，他们一定会这样想。

「那个人是很漂亮没错，但有点高不可攀，我实在不敢跟她搭话……」

不意外。换成是我也会因此却步。

于是，没有男人跟平冢老师搭讪，但她主动出击也得不到理想的回应，一个人悲伤地杵在会场正中央。

面对如此惨状，她听见从某处传来的女性轻笑声。

『哇好惨——穿那么漂亮却没人陪（笑）。好可怜，来个男人去跟她搭讪啦——』

『真的——她打扮得超认真的，笑死。「喂，你到底多想钓男人啊」的感觉？我不行——管她长得再好看，真的完全不行。不如说好耻喔。』

好耻喔……好耻喔……好耻喔……

隐隐约约的嘲笑声，伴随昭和动画风的特效传入耳中。

「……说实话，之后的事情她就不太记得了。等她回过神时，已经躺在家里的玄关。」

「玄关，是喝多醉啊……」

大人似乎是依赖酒精生存的生物。不过，也有酒精无法洗去的耻辱。

在那之后，那天发生的事就成了平冢老师的心灵创伤，每晚都在折磨她。

虽然很气那些人的挖苦，自己或许真的太拼了。

不对，说起来，因为在一般的婚活派对上遇不到对象就去参加宅婚，是否就是错误的抉择？「宅婚总该遇到对象了吧」这个企图，是否参杂着「宅婚的等级比一般的派对低吧，那我也行……」这种瞧不起宅宅的看法？穿上华丽的礼服时，是否想像过被捧得比在场所有女性高的自己，暗自窃笑？是否因为太害怕适婚期过了，沦为遭到这种报应是理所当然的可耻误会女？

「欸，比企谷，你怎么想？」

讲到这边，平冢老师带着有点空洞的眼神问我。

「尽管这只是假设，就你这样的年轻人看来，你觉得这种女性如何？」

「老师……」

您还在坚持这是假设情况啊，面对现实吧……

是说我哪知道。这种悲惨过头的婚活失败经验，我承受不住。为何我非得听班导讲这么沉重的话题？这种事不要找我，请投稿到发言小町（注6）那边。然后收到「婚活派对呀（笑）。辛苦你了（苦笑）。顺带一提，我老公年收有两千万日圆」这种欠扁的回应。

「喂，比企谷。别客气。告诉我你真实的想法。」看我沉默不语，平冢老师逼近我，都快哭出来了。「这种女性果然很耻吗？一辈子都无法结婚吗？你怎么看⁉」

「等等，你靠好近你靠好近！放、放心啦。那个人应该总有一天也能结婚的……」

「喂，你不是随便乱说的吧？你有种对天地神明发誓你说的是真心话吗？要是你敢说谎，这条审判小指炼<Judgement Chain>会勒爆你的心脏！（注7）」

「这个梗好老……」

你因为太拼命的关系，整个人都没救了。可是这么伤人的话我讲不出口。

的确，在那个叫宅婚的活动上犯下的失误，肯定对她造成极大的伤害。惨到我可以理解平冢老师最近为何这么颓丧。

可惜就算她跟我抱怨，区区一个未成年人也给不了任何安慰及建议。我完全不知道该说什么才好。

总之先随便讲点好听话，哄她开心吧。表面上。

「不、不用担心。老师那么漂亮，之后就会遇到好对象了。」

「之后就会遇到好对象？」

然而，这句好听话反而踩到她雷点的样子。平冢老师目露凶光，抓住我的下巴，用可怕的声音说：

「比企谷，那么，为何我一直等不到你说的『之后』？我哪里不好？」

「好恐怖好恐怖好恐怖！呃，硬要说的话就是这个吧！就是这种地方吧！」

一生气就会立刻动手，还有喜欢的都是热血动画、抽烟的动作有点大叔味……要一个个列举出来的话根本没完没了！

之后，空虚至极的对话又持续了一段时间。

「啊啊……好想结婚……！」

悲伤的呢喃忽然从平冢老师口中传出。或许，这句话被天上伟大的神明听见了。下一刻。

「——呣哈哈哈哈哈！你的愿望，我听见了‼」

啪唰！那名男子掀起厚重的大衣，从走廊的转角处出现。

背着光的矮胖身影手上戴着神秘的护腕，因本人散发出的热气而起雾的眼镜闪烁光芒。

不、不会有错，那是！……呃，那人是谁啊？我有点没印象。

「什么⁉材、材木座⁉你从哪里开始听的⁉」

平冢老师为他突如其来的登场大吃一惊，这句话让我想起来了。

喔，对，材木座同学。这情报太没用，害我的大脑下意识忘记。不如说我现在又快要忘记了。所以，你谁啊？

「呣哈哈，当然是从头听到尾。竟然没注意到我这满溢而出的庞大『气场』，看来我的光学迷彩<Suspend Mode>今天也状况绝佳。是吧，八幡？」

「闭嘴。才登场三秒就吵死了……你干么偷听？小心我告你妨碍隐私喔我认真的。」

「呼呼呼，八幡。何必这么客气，强敌<朋友>啊。遇到如此紧急的情况竟然不叫我一声，太见外了。」

谁要叫你。无论情况多紧急，就是不会叫你啦，是说不要这么顺地无视别人说的话。我都明显散发出「呃啊，来了个难搞的家伙……」的气息，材木座却得意地笑着宣言：

「无须担忧！既然我剑豪将军来了，尽管放一百万个心‼平冢老师‼」

「干、干么？材木座，你到底在说什么……」

困惑的平冢老师的疑惑也被他无视。材木座接着说：

「我材木座义辉，不是会对这种情况坐视不管的男人。八幡啊，我也来帮忙。放心，只要我和你携手合作，没有打不倒的敌人！呼哈哈哈哈哈‼」

「嗯，所以说……？」

你到底在讲什么鬼话？

……看到这边，我将视线从纸上抬起来。

怎么回事？总觉得被迫看了篇超恶心的文章，这到底是？啊，难道是垃圾？嗯是垃圾。垃圾就拿去丢吧，分类后拿去丢吧。

「喂——！慢着，八幡——‼」

我正准备将无限接近于垃圾的纸在真正意义上撕成碎片，写出这篇文章的人，也就是材木座宏亮的声音响彻萨莉亚。

「怎、怎么？你哪里不满意我的企划书？至少讲几句感想才符合礼节吧？」

「呃这就是我最诚实的感想了。我是个坐而言不如起而行的男人。我是个会做好垃圾分类救地球的男人。」

「嗯嘎嗯呜呜！」听见我的回答，垃圾制造者材木座发出恶心的怪声。「竟、竟然说我熬夜想出的必胜策略是垃圾……」

他不知道在碎碎念什么……这东西是必胜策略啊。

我再度望向他拿给我的垃圾——更正，名为必胜策略的「企划书」。浮现脑海的当然是昨天的对话。

『因战斗而粉碎的矜持，只得靠战斗夺回。八幡，你不这么认为吗？』突然出现的材木座，突然说出这种话。

他说的战斗，大概是指平冢老师在宅婚会场上犯下的各种失误。原来如此，确实有道理。

例如PTSD，俗称心灵创伤的症状，治疗法就是从面对造成心灵创伤的原因开始。也就是所谓的暴露疗法。

『呵。自古以来，在战斗中败北的主角重振旗鼓，最后获胜，方为王道。其中有着浪漫。海贼亦然，火影亦然。』

但材木座不可能想那么多，只是基于中二的想法才讲出这句话。

『总之这起事件，让我剑豪将军･材木座义辉负责吧！放心，万事都交给我处理！我不会害你们！呼哈哈哈哈哈‼』

于是，隔天放学后。材木座把我叫到最近的萨莉亚，我板着脸赴约，被他硬塞了那篇莫名其妙的怪文章看，到了现在。

我问他「所以这到底是什么东西？」。

「嗯哼？如你所见，是记载宅婚必胜策略的企划书<秘传书>啊？」

并没有。哪有这种一堆小细节的必胜法。是说，企划书是什么鬼？干么搞得那么正式。

「你问我为什么，我未来不是会靠写轻小说成为亿万富翁吗？」

「有这回事？我第一次听说那个计划耶？」

「而所谓的畅销轻小说家，讲白了点就是从宅宅身上捞钱的存在。蔓延世间的畅销作家，肯定只把自己的粉丝当成提款机。也就是说，唯有对宅宅的喜好及弱点瞭若指掌，能够让他们掏钱出来的人类，才能爬到畅销作家的地位。没错，像我这样！」

「好猛。你的思考模式直线往错误的方向狂奔。幸福回路差不多要烧断啰。」

有空妄想这些，不如快点把小说写完。还有，我觉得畅销轻小说家不会有那么过分的想法。我也不确定啦。

「讲白了点，去参加宅婚的男人喜欢的女性类型，对我来说一目了然！既然如此！」

既然如此，列出宅男喜欢的女性形象，带领平冢老师走向宅婚成功之路再简单不过。指导方针就是这篇「攻略宅男的一百零八条法则」。

「我将来会成为靠善于算计的企划力走红的男人。一不小心就先写成企划书了。唉呀，真害怕自己的市场能力……」

「可怕的是你惊人的妄想力吧。这也太惨不忍睹了。」

从途中开始明显是你的亲身经历。都能窥见这家伙平常的私生活了，好可悲。

「嗯哼。话虽如此，八幡啊，老实说，世上的宅宅的愿望，不会只有这种程度吧？资料来源是我。」

「呃，这个嘛……」

但我觉得宅男——不如说不受欢迎的男人的愿望，或许就是这种程度。资料来源是我。可是我完全不觉得这东西派得上用场。

不如说，平冢老师同意了吗？

记得平冢老师昨天是说「不，材木座。我很感谢你的提议，不过基于职业道德，教师可不能让学生帮忙找对象……」和「再说这不是我本人的经验，只是假设……」，直到最后都表示拒绝。

在我思考之时，手机震动起来。好像有简讯。我看看……？

From平冢to比企谷 主旨：询问进度

详细情形材木座同学跟我说过了。听说你也会帮忙打造我的形象，好让我下次宅婚能有收获？期待两位的表现。我的话，虽然不知道有没有效果，我打算跑一趟县内的结缘神社之类的能量景点，累积能吸引良缘的宇宙能量。其实千叶有许多知名景点——

看到这边，我默默收起手机。

「呣？怎么了八幡？不用回人家吗？」

「没啦，是垃圾简讯。说什么有个快死的大富翁要把遗产给我。」

那人生病了。

结婚、婚期都是会剥夺人类正常判断力的禁忌存在！婚活，万万碰不得！

「呣嗯，那就来修正企划书吧。我个人的意见是……」

于是，材木座with我制定的紧急企划「打造小静的全新形象」就此揭开序幕。咦？要with我吗？坚持要feat.比企谷八幡吗？

老实说，我不太想跟这件事扯上关系……

那么，平冢静培育计划就这样揭开序幕。

下下周六有场不错的宅婚派对，我们便决定以那天为重点执行计划。

活动第一天。

隔天星期六，傍晚材木座就把我叫出去，我心不甘情不愿地来到萨莉亚——

「——时机成熟，计划将进入最终阶段。准备好了吧，冬月（注8）？」

「太快了啦。哪有这么快就进入最终阶段的计划啦。」

那个垃圾企划书昨天才写好，今天计划就快完成了。这个碇司令动作有够快。跟靠一集三十分钟的动画就把故事讲完的OVA一样快。

「呣哈哈，这还用说！对轻小说家而言，生产速度就是命脉！听说能稳定提供稿子让出版社出书量达标的快手作家，就算他只写得出粪作，编辑也会重用。也就是说，我等于是当红作家！等于跟女声优结婚了！」

「你未免太乐观了吧竟然拿在网路上看到的超假业界情报当资料来源……」

乐观到我觉得他有在吃会刺激脑神经的药。希望他能在被警察先生带走前洗心革面。

「喔，所以？意思是那个吗？昨天那个跟垃圾一样的企划案已经写好了？」

「嗯，正是。毕竟是我这个神作家设计的形象，自然完美无缺。无奈我有可能无法理解外行人的感性。为了以防万一，想找你亲眼看过成品再告诉我感想。」

「喂，不要顺口把自己归类在不是外行人的那一区。」

你也是彻头彻尾的外行人吧……等一下，成品？

「咦，什么？意思是今天不只企划书，平冢老师也会亲自到场吗？到这里？」

「没<Exactly>错<rt/>！」材木座用欠扁到不行的卷舌音说话，点了下头。「尽管期待吧。然后看仔细了！在我的改造下脱胎换骨的那位圣女真正的身姿！」

喂喂喂，真的假的。才过一天就进行到这个阶段，你的工作效率根本是能干的制作人嘛。这家伙该不会真的是神P？

继天才･淳君♂、中田康贵（注9）后，拥有全新可能性的材木座……不，材木座P的眼镜反射阳光，闪耀异常睿智的光辉。

不用说，那当然只是我的误会。

十分钟后，现身于店内的平冢老师打扮成完全无法用一句话形容的羞耻模样。

一看到材木座，她就带着怒气冲冲＋有点泛泪这个互相冲突的表情迅速冲过来。

「喂、喂，材木座⁉」

咚！她用力拍桌，放声大吼。

「喂，材木座，这真的是『史上最强最赞的人气服装』吗⁉刚才路人看我的眼神像在看可怜人……比企谷⁉你也来了⁉」

「老师，您怎么穿成这样……」

我对瞪大眼睛的平冢老师这么说，本来就很红的脸立刻变得跟煮熟的章鱼一样红。也是啦。经由材木座之手形象大转变的平冢老师，身上的衣服就是如此羞耻。

「处男杀手服」。

各位记得之前在网路上流行过这样的衣服吗？接近这个意思。

纯白衬衫的领口系着鲜红色缎带，附肩带的马甲裙则是和上衣成对比的黑色。马甲使纤细的腰部变得更加显眼，凸显出撑起白衬衫的丰胸。包覆下半身的蓬蓬裙营造出强烈的梦幻感，底下是一双羚羊般的修长美腿。

清纯与性感的高度融合——材木座之前讲过这样的蠢话，不过确实形容得很好。

清纯却性感，性感却清纯，这奇迹的协调感带来的魅力，强烈刺激我的处男探测器。

另一方面，我也诚心认为都这个年纪了，穿成这样她不害臊吗？

「呃，虽然我有很多话想说……先请教一下，老师今年贵庚？」

「呜呃！」

平冢老师发出彷佛要吐血的呻吟声，跪到地上，然后用带着哭腔的声音说：

「别说，比企谷！别再说了……！」

「啊，可是比想像中OK喔。和年龄之间的反差反而营造出一种接近出局的安全上垒感……」

「比企谷，给我咬紧牙关！吃我这招！冲击的第一拳（注10）！」

——之后，材木座如是说道。

「这正是『对宅男用决战兵器･射杀无垢的铁处女』真正的力量！藉由让年长女性穿上梦幻又少女的服装，将她的圣女力提高到无限大！童贞会死。我也会死。」

不愧是材木座老师，还是一样逊。对你抱持期待的我真的太傻了……

可是偷偷说一下，我有点觉得穿成这样感到羞愧的年长女性也不错。

——别做奇怪的事了。要做就要按部就班、踏踏实实、打安全牌。

不用说，隔天平冢老师就提出严格的方针。

对材木座的企划案照单全收，出了个大糗的平冢老师，日后是这么追述那件往事的。

「我失去理智了……不知为何，我竟然觉得不会有问题……是熬了一整晚的夜的激昂情绪害我这么做的……」

不能让这样的悲剧重演。假如她穿成那副德行又去参加婚活派对，平冢老师肯定会自己选择死亡。

因此，「打造小静的全新形象」企划刚开始没几天就大幅转换方向。

我们开始寻找新路线。

「呣——那么，你有想到下一个计策吗，八幡？」

「我说，这是你该想的吧……」

我试着吐槽，但继续交给材木座处理，显然只会重蹈覆辙。

应该要找个新制作人制定计划。

那么，那位新制作人是谁呢？用不着解释。

就是我，人称346事务所第一名的稀世奇才･比企谷P。

如此这般，我想了企划案②出来。

「就我看来，想从衣服那种外观因素博得好感，一开始就是错的。」

隔天放学后。

我在熟悉的萨莉亚跟材木座和刚下班的平冢老师强调。

参加婚活……尤其是以宅男为对象的婚活时，最重要的并非包含相貌及服装在内的外貌部分，这是我的看法。

那么，在这种场合最重要的要素是什么？

「喂，比企谷，别吊人胃口。有主意就快说。」

平冢老师催促我讲结论，我隔了好一段时间才回答。

那是将异性放在手掌心上玩弄，赚取金钱的专家——例如夜店小姐或男公关应该要有的技能。

没错，也就是「接待力」。

——接待力。与其讲一长串话说明那个神秘词汇的意思，直接付诸行动应该会比较快。于是我提议举办一场模拟演习<角色扮演>。

「角色扮演？是那个吗？服务业偶尔会被要求做的……」

是的——我简短回答平冢老师的问题。

用字典的方式解释「角色扮演」一词，就是「每个人分别扮演自己的角色，体验特定的状况，藉此想出适当的应对方式的学习法」。

例如在餐厅打工的人，会透过即兴剧设想遇到客诉或奥客的情况，事先学习该如何应对。尽管意思有点出入，学校举办的防灾演习或许也可以说是角色扮演。

「总而言之，试一次就知道了。那我来扮演跟平冢老师搭话的宅男A，材木座你就……」

「呼呼呼，交给我。你的想法我很清楚……」

你派不上什么用场，可以闭上嘴巴去当掉在会场外面的小石头吗？我正准备接着说下去，材木座就擅自宣言：

「那么，我来当得知宿敌<那家伙>现身于会场，装成一般人潜入其中的抹杀者<Eraser>好了。别客气，咱俩这么熟了。无须道谢。」

「不，没有那种角色……」

谁啦，那个突然出现在对话中的宿敌<那家伙>。他特地跑到宅婚会场干么啦，那种人绝对不值得抹杀掉。

话说回来，你可不可以不要感应到人家不想理你，就硬插进话题？

如此这般，状况剧take1开演。

我们设计的情境是……用一副「知道这些很正常吧？」的态度跟人聊超冷门宅知识的宅男A。

「那个，那老师……不对，平冢小姐，您有喜欢看哪部动画吗？」

「喔、喔，这么快就开演啦。嗯。喜欢的动画，果然是超能奇兵吧……」

听见那个回答的瞬间，我饰演的宅男A的眼镜一闪。虽然我并没有戴眼镜，请各位靠想像力补足。

「哦，超能奇兵啊……不错啊，说到超能奇兵就不得不提至今仍被誉为传说的那一话，那一话的演出是由有名的西城先生负责，品质超高的。」

「嗯？」

「啊，西城先生还是《铬绿巫师》的导演，那部作品也满优秀的。平冢小姐喜欢西城作品的那些部分？」

「嗯？嗯？」

「咦？哎呀？平冢小姐，难道……」

难道您不认识西城导演？

话中带有这层言外之意的我，大概装出了非常真实的苦笑。糟糕，我那能靠表情迷住观众的演技太强了。这是会在威尼斯或坎城的影展博得满堂彩的等级。可能会有妖艳的好莱坞女演员大肆称赞我「阿八的演技非常Exciting又Emotional。是未来可期的Actor」。

先不说这个了，我起了兴致，继续扮演宅男A。

「啊，不好意思（笑）。站在消费者的角度看动画的人，对制作人员不会太瞭解吧（笑）。」

「…………」

其实我觉得那种鉴赏态度，比较能纯粹地享受看动画的乐趣（笑），反而很羡慕（笑）。像我在看动画前都会先去看制作人员名单，这几年来都是在拥有这些背景知识的情况下看动画（笑）。好啦，站在创作者的角度欣赏作品也——

我的即兴发挥停不下来，失控地疯狂自言自语（笑）。由于我实在太烦，材木座遮住眼睛，平冢老师则是——

「喂，小子，少得意忘形了……」

她一把掐住我的下巴，语带威吓地说。

「比企谷……看来你需要教育一下喔？就算你多少懂一些动画方面的知识，怎么能用这种态度跟老师说话。」

「不是，误会！我是在演戏啦！演戏！这不是我，只是在照实演出某种常见的宅男！」

「什么？常见的宅男……？」

平冢老师板起脸来，我拼命点头。

唉唷，这种人不是很常见吗？突然开启超冷门动画的话题，一脸「这点小事通常都会知道吧？」的人。对方一说不知道就会面有难色，彷佛在说「唉，所以说菜鸡就是这样……」的人。我演的就是那种御宅族。觉得看主题艰涩的动画或经典名作很了不起的类型。

这只是我个人的见解，那种人一定有收攻壳机动队的漫画，别人问「有什么推荐的动画吗？」时大多都会推枪神。反而看不起EVA，觉得自己很帅。

「噗呃！喂、喂，八幡。别说了。你的攻击对我很有效……」

「我没有要攻击你的意思……」

不过，材木座的确是那种会想在跟宅宅同好聊天时刷优越感的类型。想跟说「我喜欢看的漫画是航海王☆」的女生刷优越感，结果反而被更加强大的刷优越感怪物用「不过到阿拉巴斯坦篇为止的航海王确实是部优秀的漫画……」反击回去。

宅宅的争地位大战真恐怖。

「总之这种会想靠专业知识骑在别人头上的宅宅，在宅圈很多啦。」

「噢，知道了。那我该怎么做？」

平冢老师会有这样的疑问很正常。

「你该不会要我先吸收相应的知识再去参加宅婚，好跟那种人也能对话吧？」

「不，那样反而会有反效果。」

因为他们虽然摆出一张「咦？这么简单的事你都不知道？」的臭脸，心里其实在为自己懂得比对方多而暗爽。人类拥有「爽却面有难色」这种复杂诡异的精神活动，大概就是这个。

「想在跟这种人交流时也能取悦对方的话，你需要的是——」

——所谓的接待力。

接待力如字面上的意思，是接待对方的力量。

打个比方，去社群网站上搜夜店小姐抱怨用的帐号，应该能看见就算面对的是她们口中的「奥客」，工作时她们仍然笑咪咪的。若要用更普遍的说法，类似「忍耐力」一词，但意思有点出入。

不只御宅族，男人都很爱跟女性炫耀，有时甚至会害对方不耐烦。反过来说就是，他们本能渴望能得到女性的称赞。

我认为满足他们自尊心的能力就是接待力，是在婚活这种场合上所需的受欢迎要素。

而锻炼接待力所需的训练，正是角色扮演。

「例如像刚才那样突然有人跟您聊没看过的动画，就算您心里在不爽，也要装出『哇，○○先生懂得真多！我好尊敬你！』的样子。只要搬出这句话，我敢肯定大部分的时候都能顺利应付过去。」

「话虽如此，比企谷，有那么容易吗？这实在太刻意了吧？」

「放心啦。只要有接待力就稳了。可以结婚啰。可以让父母抱孙啰。」

这句话对平冢老师的效果似乎十分显着。

「结婚……抱孙……嗯、嗯，这样啊。既然你这么说，应该就是了吧。我试试看。」

如此这般，take2接着开演。

「汤浅的作品最关键的果然是前卫的影像呈现方式（笑）。或许对大多数的人来说不好理解，不过那个品味真的……好痛！喂，痛痛痛痛痛！投降投降！会痛会痛！」

「……噢，抱歉。我有点烦躁，又下意识使出了关节技。继续说吧。」

「那个，可以请您不要下意识那么精准地使出关节技吗……」

不如说我诚心希望您改掉会反射性使出关节技的习惯。好吧，是没关系啦。

……那么重来一遍，take3开演。

「还有，讲到现在的动画场景，不可或缺的是痛痛痛痛痛！就说了会痛！关节技会痛啦！我连论点都还没讲到！」

「噢，抱歉。我又下意识使出了关节技……」

take4以后的情况我就不多说了。反正不用解释应该也猜得到结局。

我的关节和平冢老师的压力达到容忍限度时。

「说起来，就算我成功跟需要那么高的忍耐力的对象结婚，之后的婚姻生活也不会顺利到哪去吧……」

我也不是完全不挑对象的喔——听见平冢老师这句话，我两手一拍，心想「啊——经她这么一说，确实如此……」，剩下我就不多说了。

因为我觉得浪费掉青春时光的自己有够可悲。

如此这般，我们两个又白忙了一场。

「真是，我对你太失望了，八幡。竟然满足于那种连计策都称不上的雕虫小技，可笑至极！果然只能靠我的企划案了吧？」

「啥？你的企划案只会给老师留下心灵创伤吧。我比你好七兆倍。」

「不不不，跟你比起来我比较好。」

「不不不，跟你比起来我比较好。」

——结论，半斤八两。

哎，在这边浪费时间装行也没意义。

在那之后，我们依然继续执行「打造小静的全新形象」企划，可是。

「……呣，说到令宅男深深着迷的神器，果然不能漏掉猫耳。」

「不，要是老师戴那种东西去参加宅婚，这次真的会嫁不掉。」

像这样。

「嗯哼。既然如此，也是可以选择巫女服或兔女郎装。你意下如何？」

「……………………（无视）」

或这样。

我和材木座连续好几天在萨莉亚碰面，议论纷纷，结果还是想不到好方法。

虽然讲这种话很不好意思，要我们这种完全没交往经验的男人想婚活的攻略法，打从一开始就是强人所难痴人说梦不可能的任务。

事到如今我们才快要想通这么简单的事。

就在这时，事态急转直下——

『……然而，病魔在不知不觉间向加藤先生（假名）伸出毒爪。』

这句话在电视上的医疗节目应该很常听见。

没错，意思是异变总会在本人尚未察觉的时候悄悄接近。等到发现时已经太迟了。

加藤先生（假名）英年早逝，而平冢老师也……

仔细回想起来，异变的征兆早就出现了。

忘记是什么时候，平冢老师传给我的简讯里有这么一句话。

记得是「为了祈祷婚活顺利，我打算跑一趟县内的结缘神社之类的能量景点，沾沾喜气」之类的。开始求神拜佛的人，通常不会有好下场。

所以，那句话一定就是征兆。

我们却坐视不管，才会演变成现在这种状况吧。异变源于一封简讯。

From 平冢to比企谷 主旨：询问进度

午安，比企谷同学。

市内的能量景点我大多都去过了，所以我今天鼓起勇气去找了占卜师。

到这边还没问题。问题在这之后。

他好像是拥有「超宇宙占星术师」这个头衔的知名占卜师，我非常好奇地征询了他的意见，他说我不能结婚是因为有大宇宙的意志在干涉——

「……………………………………………………………………」

无言。我一句话都说不出。

超宇宙占星术师是什么鬼。是兰花（注11）的盗版货喔——这么虚的吐槽我讲不出口。只能哑口无言。

从那一天起，我的手机就一直收到这种恐怖简讯。

From平冢to 比企谷 主旨：询问进度

午安，比企谷同学。今天我又去找了那位帮我占卜的老师。

身为教师的我叫人「老师」有点奇怪呢（笑）。不过，老师说的话非常有深度，我很尊敬他。

他说宇宙中存在科学技术还没办法观测到的未知能量，接触到这种能量的话，人类就能觉醒操纵隐藏在体内的运气的力量——

From 平冢to 比企谷 主旨：询问进度

午安，比企谷同学。今天我又去找老师了。

老师说妨碍我结婚的大宇宙的意志似乎非常强大，难以根治。但老师说他有个装着宇宙能量的圣光的壶，是从上一代的超宇宙占星术师手中继承来的，只要我把它买回家，或许会有帮助……

可是那个壶非常昂贵，老师说可以介绍值得信赖的金融机构给我，我却迟迟下不了决心——

惨了。惨了。代志大条了。这是怎样？《黑金丑岛君（注12）･女教师篇》吗？好恐怖。未知的宇宙能量是啥？好恐怖。

我搞不好错估了急于结婚的女性的精神压力。那个平冢老师竟然会变成这样。

当然，我也没冷血到会置之不理。

我判断必须制止平冢老师，某一天，我一大早就去跟她说那个占卜师有问题。

我问她，您没在《现在○午了！》（注13）上看到中○知子（注14）小姐的悲剧吗？

然而，平冢老师没把我的话听进去，甚至问我这种问题。

「比企谷，我问你。你觉得上帝为什么要赐给人两颗肾脏？」

「……………………………………………………………………」

不知道。不知道，但我认为不是为了让人拿去卖。

平冢老师已经走到我的声音无法传达的地方。

事已至此，我们只剩下一条路可走。无论如何都得让她在这周末的宅婚找到对象。然后守住平冢老师的肾脏。

「……期限还有三天。材木座，你懂吧？」

「收到！别担心，八幡。我不会失败第二次‼」

我们思考着。

该如何让宅婚成功，该如何带领平冢老师走向红毯的另一端。

我们思考、议论、决定、驳回、肯定、否定、改良、测试、失败、重新思考，拟定策略。

萨莉亚的关店时间到了，回家后我们还是熬夜思考下一个计策，隔天放学再拿出来检讨可行性。

由于我们严重睡眠不足，讨论时总是要强忍着睡意。

偶尔会拿饮料吧的橘子汁和哈密瓜汽水混在一起做成哈橘汁，笑到差点窒息，原因大概是思考力下降了。

议论，议论，哈橘汁，议论，哈橘汁。

本以为我们的议论永无止境。不过，世上不存在永恒的事物。

终结之时逐渐接近，最后——

「材木座，这样就完成了吗……？」

「嗯，这样就完成了……」

巧的是，那是宅婚前一天的事。在我们不知道去过几次的萨莉亚。

看着完成的企划书，我们不由得用力握手。

这样平冢老师一定也会清醒过来……

「好，出发吧八幡！这东西！这道光！是我！和你的！光芒<制作>……啊。对不起，太大声了对不对我会小心的。」

情绪亢奋到最高点的材木座喊出的帅气台词，搞得周围的客人及店员纷纷皱眉。

就这样，宅婚当天终于来临。

我们三个在做为会场的市内某处的出租大楼前碰面。

「那我走了……」

「老师，真的请您加油。」

「祝武运昌隆。」

我和材木座对走向出租大楼的平冢老师这么说。

平冢老师没有回头看我们，只是默默竖起大拇指。她的背影看不出昔日哀叹着「好想结婚……」的痕迹。

只是直盯着未来走向前方，这副模样撼动了我们的心。

『——这真的是你们得出的答案？』

昨晚，平冢老师看完我们写好的企划书，神情严肃地询问。我们用力点头。

『……是吗。那我也会相信你们。』

连续好几天为这件事烦恼的我们三个笑了出来，彷佛之前那些事从未发生过。

我们三个就是累到这个地步。大概是紧绷的神经放松下来，感情一口气爆发了。

没问题，一定会顺利。

我们看着平冢老师走进出租大楼，踏上归途。

我不经意地把手伸进口袋，把我们的建议整理在一起写成的企划书，揉成一团放在里面。

我默默打开它，又看了一遍。

上面写着这样的字句。

Q：这是在恶作剧吗？

A：不，这是平冢静･最终型态。

「……………………………………………………………………」

我再度将那张企划书揉成一团，扔进附近的垃圾桶。

嗯，垃圾分类很重要。要爱护地球喔。

先别管那个了，我无意间说出这句话。

「这、这这这这这、这不是我一个人的责任喔……」

这次学到的教训是，千万别相信熬夜三天的人得出的结论。

……之后。

「比企谷——‼材木座——‼你们做好觉悟了吧⁉」

不用说都知道气得前所未见的平冢老师制裁了我们，所以我就不多说了。

「唉……好想结婚……」

平冢老师的自言自语，参杂在远方的蝉鸣中，听起来十分悲伤。

完

5注   出自《Fate/stay night》中的台词「亚瑟王不懂人心」。

6注   日本读卖新闻经营的网路论坛。

7注  《猎人》中酷拉皮卡的能力。可插入对方的心脏，若对方违反约定，就会因为心脏被勒紧而亡。

8注  与下文的碇司令皆为《新世纪福音战士》中的角色。

9注  皆为日本音乐制作人。

10注  漫画《超能奇兵》的主角数马的招式。

11注   动画《超时空要塞Frontier》中的角色。个人角色歌为〈星间飞行〉。

12注  以高利贷为主题的日本漫画。

13注  指日本综艺节目《现在中午了！（ヒルナンデス！）》。

14注  日本艺人中岛知子据传遭占卜师洗脑过。

** 给十年后的八幡

作者：相乐总／插画：ももこ

接近末班车的山手线闷得要命。

年末时期就更不用说了。

嘴巴散发出的炸物味、廉价俗气的香水味、闷在厚衣服底下的汗水及疲劳的气味。有种这些讨厌的臭味跟弥漫于空中的酒精残渣混在一起，附着在老旧的皮制吊环及扶手上的感觉。

每当看见拿现在是忘年会的季节当藉口，边走边喝酒的人，我都会觉得他们真了不起。你们真的拿出了值得忘年的成绩吗？其实只做了会让人忘记的工作吧？

这只是从来没人邀他去参加尾牙的男人在胡说八道。不仅没忘记反而是被人忘记的那一方，请体谅一下我的心情。

「……都到这个年纪了，还是边缘人啊……」

我的身影映在深夜的车窗上，看起来憔悴不堪。

死鱼般的眼睛显得比平常凶狠许多，散发出一股腐臭味。

对于这混浊的空气最有贡献的，搞不好是映在玻璃窗上的这个三十岁的男人。

我缩着身子待在车厢最底部，尽量不接触到任何东西，听见稚嫩的欢呼声。

「欸欸，今年圣诞老人不知道会送我什么礼物！好期待喔！」

坐在座位上的小女孩牵着旁边的母亲的手，开心地笑着。身上穿的是以红色和绿色为主的可爱洋装。

对喔，圣诞节在这礼拜。

我都忘了。这是和边缘人无缘的节日。我甚至想告这个小孩骚扰边缘人，让她当众出糗。不过这么做的话当众出糗的会是我。

「圣诞节，圣诞节，好开心喔好开心！」

圣诞节，圣诞节，你好吵喔你好吵？

我把手伸进公事包，以隔绝无罪的笑声。

「啊……」

结果摸到不是耳机的东西。

是明信片。

通知我要办同学会的明信片。今天早上我在公寓的信箱发现的，不小心一直放在身上。

亏我把这个活动也忘得一干二净，结果因为一场意外又想了起来。大人有太多想忘记的事情。一人忘年会在等待着我。说起来，「忘记」这个行为就是自己一个人做的，无须他人介入，所以独自召开忘年会反而比较正确。

「唉……」

我叹了口气，看了一遍明信片上的文字。

『离我们从总武高中毕业，过了很长一段时间。我想大家应该也都找到不错的工作，建立幸福美满的家庭，迎接各种变化。要不要趁毕业十周年，久违地联络一下感情？』

多么正确无比的内容。

深信每个人都在向前迈进。

主办方大概是户部或他们那一挂的人。对于成群结党并不排斥，用十周年这个魔法词汇放大同伴意识。

没有他意。

因此虽然没有恶意，也没有善意。

通讯软件和社群网站的同学会消息一直被我放置，对方甚至特地打电话到老家问我现在的住所，寄明信片过来。

也不想想看我为何要无视。

离高中毕业过了十年。仔细一想，我还真是走到了很远的地方。

我对那个场所没有不好的回忆，甚至会怀念。

侍奉社和侍奉社的成员。闭上眼睛，他们的面容至今依然会浮现脑海。

那里对于我的高中生涯来说，是最神圣的圣域。

在充满错误的世界中，有着认真生活的人们，上演了一出绝对没有搞错的青春恋爱喜剧。

我觉得那是一则美丽的故事。虽然这样讲像在自卖自夸。

不过，正因如此——

「……蠢死了。」

我用尽最大的力气，揉烂同学会的明信片。

当时的他们她们。

我死都不想见。

童话故事已经画上句点。

美丽的青春恋爱喜剧的时代结束了。

我们已经生活在十年后的沉闷空气当中。

山手线的内圈，在从大冢站开往池袋站的途中会有一个急转弯。

生活在大都市东京内，一刻都不容大意。

毫无防备地站着的话，会被突如其来的离心力甩出去，急忙站稳脚步，换来隔壁的人的臭脸。这种事很常见。

在东京这座水泥丛林中，给别人添麻烦乃罪大恶极之事。这里可是难以生存的自然环境。唯有适应这个环境的人，能在荒芜的文明社会上生存。

「再睡几觉圣诞老人就要来了！叮叮当！叮叮当！圣诞节快来吧！」

我稳稳站在地上，承受着习以为常的离心力，下一瞬间，小女孩尖锐的声音再度刺进耳中。

转头一看，她的母亲正在打瞌睡，似乎没力气安抚小孩。

好危险。

我指的不是在这种时间搭电车的小孩。

小孩子在深夜外出的理由要多少有多少，例如因为父母要工作的关系，暂时找个地方把他寄放到晚上，或是不能在阳光底下走路的体质、他们过的不是日本时间而是格林威治标准时间等等。

这不重要。我对别人家的教育方针没兴趣。我们家是我们家，别人家是别人家。边缘人是胸襟跟甘地一样宽大的生物。坚守不杀生主义，一辈子被人无视的等级。可悲啊。

真正危险的不是小孩。

是周围的大人。

每当小女孩精力十足地唱起歌，都会传来不耐烦的咂舌声。

明显看得出，车厢里的人都在为打破东京丛林「不可以给别人添麻烦」这条不成文规定的小孩感到不耐。

这样下去，可能会发生什么突发状况。

比如说，可能会有某个危险人物跟小孩子抱怨他被不想看见的同学会通知搞得心情烦躁、圣诞节没安排所以不想听见这种歌。

……那个危险人物就是我，嗯。边缘人胸襟宽大是骗人的。有人就是因为无法跟其他人妥协，才会变成边缘人。

车内充满一触即发的气氛，宛如膨胀的气球。

那个小孩却完全没意识到，不停唱着歌——

「圣诞节，圣诞节，好开心喔好开心！」

「圣诞节，圣诞节，好开心喔好开心！」

——歌声突然被粗野的声音盖过。

幸好不是从我口中传出的。我还以为我太边缘，跟《化身博士》一样召唤了虚构的第二人格，超紧张的。（注15）

一名穿西装的男性硬是挤开其他人，走向那个小孩。

「唔、唔唔唔……」

他站在吓得瞪大眼睛的小女孩面前，长腿往两侧用力一踏。巨大身躯的体重全压在上面，导致老旧的皮革吊环发出如同老奶奶的呻吟声。

他接着转了半圈。

背对小孩，望向周围的大人。

「好了好了诸位，圣尼古拉的节日就快到了！愁眉苦脸地站在那边，对圣人未免太失礼。唱歌跳舞大声欢呼吧！跟我一起唱！圣诞节，好开心喔好开心！」

那人哈哈大笑，粗哑的声音响彻车厢。

看来他醉得很厉害。站都站不稳，讲话不合逻辑。大声喧哗的理由对他来说肯定一点都不重要。

不去触怒神明，神明就不会惩罚你。

在东京丛林中，除了不能给人添麻烦这条不成文规定外，还存在「千万不能跟看起来有问题的扯上关系」这条绝对的法则。

都市人都很虔诚。众人纷纷移开目光，不然就是移动到隔壁车厢，远离这个怪怪的神明。

而他则是——

「——嘿，小朋友。」

转头看着那个小孩，露出笑容。

「你声音这么好听，要好好珍惜啊。」

「好、好好珍惜？」

「随便唱给大家听，太浪费了吧。」

他没有说「你很吵」。是十分温柔的说法，跟其他人的威吓截然不同。

「……可是，圣诞节，很开心……」

紧张的小女孩肩膀慢慢放松，用稚气尚存的声音天真地笑着。

她的身姿被男人巨大的身躯遮住，大多数的人都看不见。

原来如此。

听见两人的对话，我自然而然想通了。

刚才的醉样是演出来的吧。他想让乘客对小孩的反感集中到自己身上，藉此改善车厢内紧张的气氛。

那聪明的做法——使我的内心躁动起来。

虽然他的外表、语气、行为举止都变了许多。

我知道这男人的名字。

「那你只唱给妈妈听如何？这样感觉起来就像只属于你们两个的特别的歌对吧。」

「好、好像有道理……！」

年幼的声音获得新的概念，语气整个轻快起来。

不久后，嘹亮的歌声音量渐渐转小。

坐在小女孩旁边的母亲终于醒来，频频低头道谢。

「不会不会。圣诞快乐。」

男人轻轻一笑，飒爽地点头致意。

电车正好抵达池袋站。

他若无其事地从打开的车门走到月台，我急忙追上去。

「那个，请等一下。」

我成功在下楼梯前叫住他。

「……有事吗？」

他对我投以怀疑的目光，害我有点却步。

光凭外表，他果然想不起来的样子。我也没什么自信就是了。

我们都老了。

「……你是材木座同学吧？」

他更加惊讶地眨眨眼睛，沉默降临。我受不了这尴尬的气氛，挥着手解释：

「那个，我不是可疑人士。我们高中时是朋友……」

「啊，不用了。」

他的大手立刻朝向我。不用了？什么东西不用？

我愣了一下，他用非常平静的声音接着说：

「就算你想玩朋友诈欺，我这人一个朋友都没有。请你去找别人。」

「……啊哈哈，我不会对朋友讲那种话啦……」

「不好意思，我没有钱。真的什么都拿不出来。放过我吧。」

他开始求饶。

对了，材木座同学好像本来就有这一面。他会在大声讲话的下一秒突然变正经，第一人称也会换。

看起来变了又没变，明明是很久以前的回忆，令人怀念的举动却重现于我心中。

也许正因为是他，我才会觉得在不想见面的当时的朋友中，他是唯一可以开口搭话的人。

我不知道。

说不定打从一开始，我就不该叫住他。

我克制住想扔下一句「我认错人了」转身就走的冲动，握紧拳头。

「你不记得啦。但我们真的是朋友。放学后我偶尔会和你一起玩，一起去KTV唱〈going going alone way!〉……那个，我还是网球社社长……」

不管几岁，自我介绍都好高难度。

我语无伦次地说出一个个可能可以让他想起我的关键字，他睁大眼睛。

发出怪声。

「难、难道你是——户冢彩加⁉」

「……太好了。嗯，对呀。」

我轻轻点头。

材木座同学说他要去转乘东武东上线。

他现在住在琦玉，常跑来这里玩，我就接受他的好意，让他带我去逛池袋西口的繁华街。

明天放假，晚回去也没关系。

聊着聊着，我们自然得知彼此都单身，也不用顾虑其他人。

「好久没见到你了。呣，上次见面莫非是成人式？」

「之后大家还一起去喝酒，庆祝大学毕业。」

「……没人约我耶？」

「咦⁉」

「原来大家一起去喝酒了，这样啊……」

「那、那个，呃，可能是我记错……啊！得点餐才行，点餐！」

我们踏进材木座同学常来的居酒屋，先点了生啤干杯，材木座同学把手撑在桌子上，托着腮凝视我。

「无论如何，五年的时光竟已匆匆飞逝。虽说士别三日什么的……你变得还真多。」

「啊哈哈……先不说这个了，材木座同学，原来你是会做那种事的人啊？」

我在自己的脸前面甩了下手，转换话题。

「哪种事？」

「刚才在电车上发生的那件事。你帮那孩子解围了不是吗？」

从高中时期开始，材木座同学的外表及行为就与众不同。

某种意义上来说，非常引人注目。

不过「引人注目」和「想引人注目」意思完全不同。

面对八幡那样温柔的人，他会敞开心胸，讲话变大声，但我看过好几次他在不认识的人面前乖得跟什么一样。

他应该非常不擅长面对车厢内不特定多数人的恶意才对。

「噢，你指那件事吗……没什么，小事一桩罢了。」

材木座同学将啤酒一饮而尽，吁出一口气。

然后用夸张的动作大大张开右手。

「于冥暗之时在外徘徊的孩童，都有自己的苦衷吧。」

「苦衷……例如因为家人晚下班的关系，被寄放在其他地方？」

「诚然。或者，那名孩童说不定晚上就会展开双翼，去吸血鬼学校上课。说不定是在太阳底下走路，肌肤就会燃烧的体质。说不定他过的不是日本时间，而是吸血鬼时间。」

……他现在迷的是吸血鬼吗？还是老样子呢。

我对他投以温暖的目光，材木座却不为所动。

「尽管无法理解所有的原因，我们至少可以陪在他身边。」

他用力将空酒杯放到桌上，发出今天最中气十足的声音。

「因为我们不惜粉身碎骨工作到这么晚，全是为了守护孩童能健康生活的社会！呼哈哈哈哈！」

看见他刻意装成高中时期的模样，我终于发现。

他大概——是在害羞。

就算会害羞，他依然阐述着人生的原则。

在电车里面，我明明也有过同样的念头，我却觉得我们的思考模式有着惊人的差距。不是，我指的不是中二病。

我从正面重新观察他。

比以前瘦一点，长高许多，相貌变成熟了。

「……材木座同学——」

「呣？」

「你变了很多呢。竟然做得出那么聪明的选择……」

我叹了口气。

「跟叶山同学一样。」

我是想称赞他的，材木座同学却「噗！」了一声。

他发出铿隆铿隆的咳嗽声，用力挥手。

「没有没有，没有没有。你才是。」

「我吗？」

「那个，就是……那个啦——感觉变得跟八幡很像？」

我也忍不住笑出来。

因为材木座同学压低了音量，彷佛在说很难听的坏话。

高中毕业后，我和八幡念的是不同所大学。

但我们并没有因此变疏远。理应会嫌这种事麻烦的他，有事没事就会联络我。

讯息内容大多是闲聊。比企谷家庭院的花开了、今天晚上月亮也很美、户冢真的很可爱……他是热恋期的男友吗？我是男生耶……

即使不在同一所学校，我们还是维持着一定程度的联系。

问题就出在这里。

女性原本是太阳——平冢雷鸟写过这句话。

我的话会这样写。

无论现在还是以前，比企谷八幡都是太阳。

本人八成会马上否认，搞不好会觉得恶心把我封锁，但在我眼中，他确实是太阳般的存在。

独自挂在天空中，能够凭一己之力绽放光芒的灼热恒星。

苛刻、孤独，却散发着令人安心的热度。

若能一直待在他身边，谁都会忍不住猜想自己是不是也能变成这样。

从高中的时候起，我就逐渐产生误会。

因为比企谷八幡对户冢彩加这个人太过亲切。

我一直认为自己是八幡特别的挚友——不小心以为自己也是特别的存在。

在辛苦考进的大学内，以及出社会后进入的公司，都试图用自己的方式真诚待人。

我曾经靠自我牺牲解决我加入的网球社的纠纷，也曾经看穿候选人的真意，解决校内选举发生的问题。牵扯到政治案件的重要活动，我也在被外人搞得一团乱的情况下让它顺利落幕。

我觉得，我下意识模仿了不停追求真物的八幡的人生态度。

可是——一切都是错的。

八幡是因为他是八幡，才有办法一直做八幡。

因为他拥有任何反感都能隔绝的强大、所有拒绝都能接受的弱小，以及将真正重要的人紧紧拥抱的温柔。

我没能成为八幡。

几乎在各个方面资质都不够。

就像夜晚冰冷的月亮，无法成为白天耀眼的太阳。

我仅仅是在八幡身边接受他的光而已。

在大学不停做白工，在公司被排挤，变成边缘人的数年后，我才意识到这件事。

「……户冢，你是不是太美化八幡了……？」

材木座同学用看待异形的眼神看着我。

我已经不记得我们点了几瓶啤酒。

我们都喝了不少，久违的重逢带来的些微紧张感及尴尬，都缓解得差不多了。

「那厮虽然是我剑豪将军义辉认同的男子汉，你竟会如此心醉于他，着实令我有些吃惊……我说，户冢。」

「嗯？」

「如果你有烦恼，我可以听你说。」

他是真心在为我担忧。

我苦笑着摇头。

「没有啦。只是被每天的生活搞得很累。」

「这完全是有心理疾病的人会说的话……咦，对了，你现在在做什么工作？」

「医药品批发。送药到各家药局。」

「呣喔？虽然不太能想像，是帮助人的职业啊。这样一想，挺符合你的个性。」

「啊哈哈，会吗……」

我耸耸肩膀。这工作很无聊。去我负责的调剂药局打招呼，讨好医生，一天就结束了。

不至于觉得自己在做没意义的事。可是，能取代我的人要多少有多少。

跟人生一样。

没有惨到令人绝望，却绝对无法成为唯一的那个人。

「你现在在做什么？」

我不想再聊自己的现况，便将话题转移到他身上，材木座同学得意地拍了下大腿。

「问得好。我在游戏公司上班！」

「哇，梦想成真了耶。」

我怀着今天最诚恳的心情鼓掌。

听说他一直想当创作人。长大后还能继续追寻高中时期的梦想的人，屈指可数。

「好厉害……你已经做出好几款游戏了吗？」

「呣？嗯，是有几款游戏工作人员表有我的名字……」

「好好喔，叫什么名字？」

说着，刚刚还在鼓掌的手自然垂了下来。

同为只是待在太阳身边的人，我实在忍不住不拿自己跟他比较。

以真物为目标，成功达成目标的他们。

连伪物都当不上，无所作为的我。

我们都变了很多。多到无法回头的地步。

「材木座同学真厉害……」

参杂叹息的声音轻轻落在地上。

在我寻找我的声音去往了何方前，眼前的他从椅子上起身。

要去洗手间吗？他喝醉了，一个人去很危险耶——我脑中冒出离正确答案差了十万八千里的推测，材木座同学一把抓住我的手。

「……户冢，走吧。」

「咦？」

「一起去吧！去我的公司！」

「咦咦咦咦咦⁉」

我被他强而有力的手从位子上拉起来。

「我现在在做悬疑推理风的文字游戏。」

我们坐上在池袋站的圆环等客人的计程车，材木座同学激动地说。

「随着剧情的进展，需要用到医疗关系的知识。你既然在批发医药品的公司上班，应该懂很多这一行的知识吧。我把你介绍给制作团队认识，能协助我们取材吗？」

「我的确常跟医疗人员打交道……可是跟专业人士起来，我根本没懂多少喔？」

「无妨。取材是次要目的，你本身才是最重要的。光是你愿意跟我一起做游戏就会有收获。」

「什么意思？」

「梦想到了几岁都能实现。我想跟疲于生活的你证明这一点！」

材木座深深坐进计程车的座位，意气轩昂地举起拳头。做游戏是你的梦想，不是我的梦想……

我说不出口。

因为老实说，我不小心被感动了。梦想无论何时都能实现。真是句名言。非常棒。喝醉有时会害人情绪不稳耶。

「……说得也是。我想看看你做的游戏。」

我轻轻点头，材木座同学愉悦地挺起胸膛。

「顺带一提，本作的卖点是精密的专业知识和新传奇作品的气氛兼具。女主角是吸血鬼，看得见直死之线，是贫乳又爱吃醋的妹妹铿隆铿隆！」

「噢，所以你才会这么执着于吸血鬼。专业意识真高。」

我想到他在电车大声呐喊的那一幕，低声说道，材木座同学默默流下泪水。喝醉有时会害人情绪不受控制耶。

「咦，你怎么了……？」

「我在感受没被说『所以你抄了哪部作品？』的喜悦。」

「我才不会对别人的作品讲这么难听的话。」

「……户冢，你是不是搞错崇拜对象了？」

材木座同学带着五味杂陈的表情摇头。

我不知道该怎么回答，将视线移向窗外流逝而去的景色。不管他本身有没有那个意愿，太阳总是会持续吸引别人，大概。

材木座同学的公司位于新宿站附近的办公街。

我没什么在玩游戏，所以听见名字也没概念，不过那家公司在游戏业好像颇有名气。材木座同学说的。

下车后，我拿出手机一看，早就过凌晨十二点了。

「虽然都到门口了才问这个很奇怪，现在这时间进得了公司吗？」

「放心，不会有问题。做游戏的人要练到吃饭睡觉都在公司解决，才称得上独当一面。现在是制作阶段的关键时期，公司里想必灯火通明吧。」

我顺着他的手指抬头看过去，高楼大厦中段，有一层楼整排的灯都是亮着的。

「我今天晚上也是久违地离开公司一趟，准备回家。」

「这一行也很辛苦呢……」

面向大马路的正门已经关上。

我们绕到大楼后面，员工用出入口低调地设置在用来掩人耳目的整齐篱笆的缝隙间。

刚刷卡解除电子锁，材木座同学巨大的身躯就灵活地跳起来。

「呣，糟糕！」

「糟糕？」

「会被发现！」

我从材木座同学身后探头偷看刚打开的门。

一名身穿羊毛大衣加休闲帽T的员工，正在从通往大楼内部的狭窄道路的另一端走来。

「不能被发现吗——痛痛痛，好痛，材木座同学，就算你推我推得这么用力，我也没办法躲进更里面啦……！」

他拼命推我的背，把我往后门旁边的高篱笆推。我一头栽进草丛，开口抱怨。

材木座同学却已经不在旁边。

「喔，材木座先生。这么晚了你在做什么？是说你酒味好重！」

「有点杂事要办……相模先生也辛苦了，这么晚还留在公司。」

他光速跑回后门，跟那个人打招呼。

从公司出来的，大概是有点地位的人。

看见鞠躬陪笑的材木座同学，我心不在焉地想——他真的变成社会人了。

「抱歉。」

和大人物聊了一会儿，目送对方离开后。

材木座同学回到篱笆处，对我深深低下头。

「仔细想想，就算是在会客室，这个时间让外人进公司不太好……我只得采取强硬的手段，以免被人抓到。」

「没关系啦，我不介意。」

我轻轻摇头。

「但我还是别进去打扰比较好吧。」

「呣！为何！」

「说不定会有其他人看见，即使没被发现，也可能给你带来许多不便。」

「呣嗯……」

材木座同学烦恼地沉吟，抬起视线看着我。虽然这一点都不重要，他好擅长由下往上看人。真想让八幡看看。他感觉就喜欢这种。

「……莫非你听见我跟方才那名男子的对话了？」

「一句话都没听见。我没兴趣偷听人说话啦。」

我垂下眉毛，腼腆一笑。

高中毕业后，我就故意不这么笑了。我讨厌自己幼稚的这部分。但现在为了让他放心，我刻意露出这种笑容。

「是吗……？」

然而，材木座看起来根本不相信。

八成是因为我突然拒绝去他的公司，而他认为理由在他跟那男人的对话中。

「没办法。事已至此，只得跟你坦承真相。」

材木座吞了好几口口水，下定决心，瞪大眼睛。

「其、其、其实！我的真实身份是……！」

「……不是游戏开发员对吧？」

「你果然听见了！」

材木座同学摆动四肢。虽然这一点都不重要，他闹脾气的方式好可爱。真想让八幡看看，他感觉就对这种没抵抗力。

「没有啦。刚刚那个人对你说了什么吗？」

我是真的没听见。

那个叫相模的人跟材木座同学聊了很久，我想说可能是在聊公事，就捂住了耳朵。

不过。

「我来不及捂住耳朵，刚开始那几句话有不小心听见。」

对方看到材木座同学这时间还在公司，为此感到惊讶。

可是做游戏的人要练到吃饭睡觉都在公司解决，才称得上独当一面。现在是制作阶段的关键时期，所以公司的灯也亮着——这是材木座同学自己说的。

综合两者，得出的答案只有一个。

也就是说，材木座同学没有参与制作那款游戏。

「那、那无法证明我不是游戏开发员！搞不好我参加的是其他团队！」

材木座同学一遇到突发状况就会忽然变得很可爱，太犯规了。也可能是我眼睛出问题。

我低头向惊慌失措的他道歉。

「……材木座同学，对不起。其实在计程车上的时候，我就觉得不太对劲。」

「你说什么⁉」

「因为车子是开往新宿的方向……」

我和材木座是在山手线内圈遇见的。

在从大冢开往池袋的车厢内，看见穿西装的他。

不过，若要从公司所在的新宿转乘东武东上线回池袋的话，要搭的是外圈。搭内圈这件事本身就很奇怪。

也就是说，材木座同学不是从这家公司下班的。

「你要是没讲得一副游戏开发员都窝在公司的样子，我就不会发现了。」

「讨厌讨厌，以理服人的户冢才不是户冢！讲什么山手线的内圈外圈，你还算千叶人吗！」

材木座同学变成小婴儿了。真想让八幡……不，还是不要吧……

「……对不起。」

我再次道歉。

开始自己一个人住后，我就变得对大都市东京的地理环境非常熟悉。

搭乘通往千叶地区的总武线的频率则大幅下降。

我们就是像这样吸收高中时期不知道的知识——等到回过神时，已经无法回到那个时候。

「我是业务员……」

材木座同学抱着啤酒瓶呻吟。

我们回到不夜城新宿的东口附近，走进刚才那家居酒屋的连锁店，再次沉溺于酒精的海洋中。

「我今天本来打算直接从客户那边回家。看到小孩就觉得他们都是游戏玩家，有种亲切感，才会忍不住跟她搭话。」

「……我觉得那也是很了不起的专业意识。」

「但我想做游戏！想做游戏让世上的俗人捧我！」

「真是坚定不移……」

我轻轻一笑。

材木座同学说他提出了好几次企划书，通通遭到驳回。

刚才那男人是开发部的大人物，他每天都在拜托对方提拔他，结果只会得到模棱两可的回答。

「那款以吸血鬼为主题的文字游戏做完后，肯定会是名作。虽然制作团队目前只有我和工读生……」

材木座同学没有骗我。确实有几款游戏的工作人员表有他的名字。

只不过是以行销人员和推销人员的身份。

「这样你还不满足吗？」

我将空杯子拿在手中转。

「广义上来说确实跟游戏有关，表现得好一点的话，说不定也能被人捧。」

「那样不行！」

材木座大声怒吼，趴到桌上。

「……那样就等于是放弃了。」

他接下来这句话说得非常小声。用一双大手抱着头，断断续续地咕哝道：

「我以前就说过要当游戏开发员，也讲过许多大话，也让人帮我收拾过烂摊子。我想让你……看到它开花结果。」

我想，他真的想展现成果的对象，大概不是我。

我们都在注视同一个人——同样的虚像。

「只要相信自己，贯彻到最后就能实现。我很久以前就知道了。」

「……材木座同学。」

「所以，我绝对要实现梦想……」

他的声音变得愈来愈微弱，消散在空中。

总觉得——像是被一成不变的生活搞到疲惫不堪的三十岁男人的声音。跟某人一样。

我们一定是离太阳太近了。

太过靠近他，所以至今依然将巨大的某物怀抱在自己的中心，绕着同样的地方打转。

就像环状线，就像山手线。

我们哪里都去不了。

我们就这样喝到意识不清为止。

高兴地聊着高中时代小小的回忆，尽是拿以前的蠢事出来分享。

「现在回想起来，侍奉社的女生还满可爱的……我真是太不懂得珍惜了……」

「你？不懂得？珍惜？」

「那里面的女生你喜欢哪一个？」

「好像毕业旅行睡前会聊的话题……」

「因为那个时候，你被捧成看起来就不会有性欲的王子嘛。可是男生通常多少会对女孩子有点意思。」

「秘密。」

我哈哈大笑。他眼中的世界和我眼中的世界不太一样，果然有点有趣。

「对了，之后好像要办同学会。」

「……我怎么不知道……？」

「咦，喔，嗯。啊，不过！搞不好明信片有寄到你老家？」

「是吗……没差，反正我不会去。」

「我想也是——」

「死都不想见到他们。」

「我懂。太懂了。」

「——真的吗？」

我们的表情瞬间转为严肃，在彼此眼中看见同样的颜色。

说谎，我和材木座同学都是。

为了立刻将其抹消，我们刻意把话题扯到往事上。

「所以是谁？」

「什么东西？」

「你喜欢的是谁？高难度的雪之下？还是安全点的由比滨？难道是爆冷门的一色？还是说该不会……」

「秘、密！」

「啊啊——我也好想上演青春恋爱喜剧！想要有人对我说想要我的人生！」

「呵呵，对呀——好想体验青春恋爱喜剧的滋味。」

材木座同学讲了好几遍同样的话，我也不厌其烦地附和。

或许我们这两个一丘之貉，就是在藉此互舔伤口。

踏出店门口时，朝阳已经升上天空好一段时间。

严冬的寒风从身上夺走酒精带来的热度。我们揉着睁不开的眼睛，拉紧大衣领口。

「……元帅想睡。」

「真的。」

「完全牺牲。」

「没错。」

假日的这个时间带，与车站相连的地下道还看不见几个人。我们进行着意义不明的对话，一起走在路上。

「——啊。」

材木座同学忽然停下脚步。

我顺着他的视线看过去，是一对母女。

母亲我不认识，不过小孩子我记得。

「昨天那个……」

是电车上的那孩子。她住在这附近吗？还是说，母亲有可能是上夜班的？

「……早上她也能出门呢。」

我喃喃说道，材木座同学皱起眉头。吸血鬼论被明确否定了。

没有啦，我当然一开始就没相信过。

我们过着平凡的人生。在这个世界中，没有传奇人物，也没有奇妙的纠纷——青春喜剧也一样，什么都体验不到。

「没办法啊。」

「没办法吗？」

「没办法，不过也只能继续活下去。」

「没办法，所以也只能继续活下去。」

我们面面相觑，露出无奈的笑容。

就在这时，那孩子跟母亲讲了几句话，啪哒啪哒地跑过来。

「——多的，给你！」

她将一小包东西塞给材木座，啪哒啪哒地跑回去。

踏着轻盈、纯粹、洁白无垢的脚步。

然后跟母亲一起不停鞠躬，消失在转角处。

看着两人离开后，我们的视线落在材木座同学手中的袋子上。

「这是……」

是一小包用红色和绿色缎带包装的饼干。不像现成品。可能是她努力做的。

有如精心准备的礼物。

「……圣诞节，好开心喔好开心！」

「你这人真单纯。」

材木座同学像在开玩笑似地唱起歌，我轻笑出声。

然而，事实上。

我有点羡慕他，所以我应该也很单纯吧。

我和材木座在刷票口道别。他要搭山手线去池袋，我则从新宿转乘小田急线。

「圣诞节，好开心喔好开心……吗？」

材木座同学和那孩子自创的圣诞歌，在耳边挥之不去。

我靠在月台的柱子上，闭上眼睛。

将自己关进暗黑的世界，却异常坐立不安。

「…………」

我将手伸进口袋里摸索，拿出手机。

凭藉滑手机的声音，按下一个个数字。是长久以来，我犹豫不决，最后还是没有播出去的号码。

完全是藉酒壮胆。虽然我搞不好只是在装醉。

电话响了几声后——

「……喂？」

传来了回应。

他好像还在睡。

冷淡又不耐烦——非常怀念的声音。

「嗨啰——是我。听得出来吗？」

「是户冢对吧？你声音都没变……根本是天使的清凉剂……」

「讨厌，八幡真是的。」

我忽然一阵鼻酸。

清了好几下喉咙，勉强掩饰过去。

「……嗯？怎么了？」

「没事，对不起喔，一大早就打给你。之后不是要办高中同学会吗？然后我就突然想到，不晓得你过得如何。」

「啥？我的户冢会不会太天使？」

「嘿嘿嘿嘿……」

久违的，稀松平常的，同学之间的对话。

仅此而已，为何发出轻快的声音这么费力？

既然注定得尝到这种滋味，早知道高中时期多跟他说话。更靠近八幡一点。

时间无法倒回。

苦闷的情绪盘踞在内心深处，即使如此，我还是不想挂电话。

「对喔，我们明明有传讯聊天，却不会聊太深入的话题，都不知道对方的近况。你现在在做什么？」

「嗯——我喝醉了。」

「听得出来。」

真拿他没辙——我笑了出来，一面让耳朵习惯八幡的呼吸声，一面发着呆心想。

八幡，跟你说喔。

我好喜欢你。

笨拙的部分、坚持会负起责任的部分、会掩饰这一点的部分。

我无可自拔地喜欢着你。

喜欢到欺骗自己死都不想见你。

「八幡不去参加同学会吗？」

「我怎么可能去。对了，下次一起出去玩吧。不带老婆。」

「啊哈哈……可以吗？」

「可以啊，预产期快到了。等小孩出生，过来看看吧。」

「……嗯，希望有那个机会。」

我会努力咽下苦涩的情绪，展露笑容。

在你面前，像以前那样。

所以——

「欸，八幡。」

「嗯？」

「圣诞快乐！给我礼物！」

「哦、哦？干么干么……你突然跟我撒娇害我措手不及差点死掉。送你我的遗产当圣诞礼物行吗？我现在去写遗书，等我一下。」

「呵呵呵，开玩笑的。我不会对有妇之夫提出这种任性的要求啦。」

「但我又没其他礼物。」

「我已经收到了。绝对不还给你。」

「啥……？喝醉的你可爱到无法无天耶？」

所以——在挂断电话前。

请让我抱紧你一如往昔的声音、太阳的热度。

拜托了，八幡。

完

15注  主角亨利･哲基尔博士喝了自己调制的药剂后，分裂出邪恶的第二人格海德博士。

** 川崎沙希与比企谷八幡跟纪念日有关的故事

作者：天津向／插画：うかみ

我在家里的客厅耍废陪小雪玩时，待在厨房的小町「啊！」了一声。

「怎么了小町？看见那种动作很快的黑色虫子了吗？」

「那个，看见那种虫子小町会叫得更大声。哥哥真的很邪恶。」

「我本来是想开个幽默的玩笑，没想到会被骂成这样。」

「比起幽默更接近阴沉。感觉得出开这个玩笑的人很阴沉。」

这个回应把我的个性摸得一清二楚，不愧是长年跟我生活在一起的妹妹。

「所以，你是被什么东西吓到？」

「不是吓到，是想起来了。」

小町走到客厅，指向挂在墙上的月历。

「母亲节快到了。」

「喔，对啊。怎么了吗？」

「小町忘记要买礼物。」

「喔，这样啊。那今年也拜托你了。」

比企谷家的母亲节，每年都是由小町挑礼物，然后我出比较多钱。我和小町合送一个礼物是惯例。

「嗯——」

小町沉吟着，走到我面前。

「小町觉得，哥哥和小町都不是小孩子了。」

「对啊。在某些国家，我们这年纪说是成年人都不奇怪。但我成年后还是想住在家里。」

「这是什么家里蹲发言……不是啦，小町是想说，礼物是不是分开送比较好。」

我看着提出这个建议的小町的眼睛。

「小町，不可能。我完全没有挑礼物的品味。品味差得吓死人。不是没有，而是负的。我挑礼物的品味烂到毁天灭地。」

「哥哥，亏你有脸讲到这个地步。」

「所以我才总是请你买礼物不是吗？例如时尚的东西，或是时尚的那个。」

「哥哥的品味差到讲不出名字耶。」

小町一下就看穿了。我因为自己脑中太缺乏时尚的词汇而感到无奈。

「我无法想像我送的礼物能让对方开心的未来。所以我不会自己去买礼物。证明完毕。」

说完，我抱住小雪，小町却马上把小雪从我手中抢走。

「哥哥，小町也知道你不会挑礼物。」

「你竟然知道⁉」

她直接往我心上刺了一刀，我有点恐惧。不对，这是我自己说的，所以应该没关系，可是我信赖的妹妹这么明确地对我表示肯定，害我忍不住心跳加速。

「不过，小町觉得送什么礼物并不重要，妈妈高兴的应该是『小孩为我选了这个礼物』才对。」

「呃，这说法会不会太精神论。」

「而且这样还能营造出反差呀。『那个八幡，对这种事一窍不通的八幡竟然为我买来这样的礼物。好高兴！』」

「会吗？」

「会啦。『品味是很差没错，可是好高兴！不对，正因为品味差才让人觉得真的是八幡为我挑的，好高兴！』」

「我在你眼中品味到底有多差⁉」

小町都把我说成这样了，难道我的品味比想像中还差？莫名的不安袭上心头。小町把脸凑向着急的我。

「所以这次，哥哥要自己买母亲节礼物！这样小町觉得分数比较高。」

小町讲完这句话露出的笑容，和必须独自帮人买礼物带来的倦怠感，导致我觉得怪怪的。

不懂我心情的小雪，悠哉地看着这边。

「嗯……毫无头绪。」

我在一家类似选货店的时尚店家内自言自语。

隔天，我趁放学后跑去逛「LaLaporTOKYO－BAY」这家店。我听小町的话来到购物中心，却想不到要买什么。

我用Google老师调查母亲节礼物，查到送花或时尚的小东西还不错，但我不知道该选哪一个。

是说选这种基本款的东西，反而会被骂没品味吧？思及此，我的思绪就打成死结，解都解不开。

怎么办咧。

「请问您在找什么呢？」

听见这句话，我抖了一下。店员来关心我了。

「啊，没关系，我自己看就好。」

我完全表现得像个社交障碍，倒着走出店门。

我轻轻做了个深呼吸。哎呀，话说回来，为何店员都那么爱亲昵地跟人搭话？也会有不想跟人说话的客人吧。有没有那类型的贴纸可以贴？像用来贴在车上的「车上有小婴儿」贴纸，「社交障碍在自己一个人逛街」之类的……不对，这样反而是贴那张贴纸的人会受到羞辱。

总之请不要跟我说话。那是事实。

「喂，你——」

这时，突然有人叫住我。我以为是店员追过来了，回头一看，一名头发黑中带蓝的高挑女性站在那里。

「你在这种地方干么？」

那粗鲁的语气，我好像在哪听过……呃，她是谁啊。我想想看——记得是叫川、川、川……

「你有在听我说话吗⁉」

「咦？喔，有啊。你问我在这里干么对吧。我来办一点杂事。」

这个年纪来买母亲节礼物有点难为情，因此我隐藏了目的。

「那你呢？」

「啊——我来买我妹京京的……」

「京京？」

「你记得吧。她也有送你巧克力。」

送我巧克力？我收到巧克力可是稀有事件，不可能忘记。呃，京京京京……

「啊！那个京京！」

想起来了。情人节送我巧克力的小女孩。那孩子是她妹，意思是这个人是……啊，川崎。川崎沙希。以有个讨厌鬼弟弟为人所知的川崎。

「京京怎么了吗？」

「嗯。她生日快到了，我来这边帮她买生日礼物。」

「哦。原来你也是。」

话一说出口我就意识到自己说错话了。川崎盯着我的脸。

「你也是来买生日礼物的？」

「是来买礼物的，但不是生日礼物。」

「嗯？什么意思？」

川崎面露疑惑，似乎听不懂我说的话。也对，正常人都会纳闷，总之得先换个话题。

「我来干么的不重要。你买好京京的礼物了吗？」

「我还在烦恼该买什么给她……对了！反正你很闲对不对？陪我一起选京京的礼物吧。」

「为什么！」

我像在吐槽似地表示抗议。川崎却一副不死心的样子。

「陪我一下又没关系。」

「不，川崎，我懂你的想法。可是啊，送礼的重点不在于送了什么礼物，对方高兴的是『你为她挑了这个礼物』吧。这样的话，由你亲自挑礼物买给人家应该比较好。」

我抄袭小町的说法，试图化解危机，川崎却对我投以冰冷至极的眼神。

「什么鬼？当然是送收到的人会开心的礼物最好。」

对吧，我也这么觉得。在同一个主题被人驳倒两次，是很罕见的经验呢。

「而且不知为何，京京不知为何很喜欢你。所以跟你一起挑礼物，说不定能让她更高兴。」

虽然我有点在意她讲了两次「不知为何」，现在可没空管那些。我是来买自己的东西，没空陪川崎挑妹妹的礼物。可是据实以报的话，她会知道我是来买母亲节礼物……我看还是早点陪她挑完，早点跟她说再见吧。

「总之你只要跟在我旁边就好。」

「好啦。既然你都这样求我了，我也不好拒绝。」

听见我这么说，川崎毫不掩饰地表现厌恶感。

「啥⁉我可没有求你。你只不过是一种调味料，好让我送出最棒的礼物给京京而已。」

「亏你有脸在本人面前讲出这种话。」

「因为我拜托得很不甘愿。全是为了京京。」

从这句话看得出川崎对妹妹的爱。这家伙真的也很喜欢妹妹，还有那个盯上小町的讨厌鬼弟弟。

「知道了啦。你真的是妹控。」

「才不是。京京是……等同于天使的存在。」

「这就叫妹控。你妹确实很可爱，我承认。但那是因为她有年龄优势。」

川崎一脸不解。我什么话都没说，坐到眼前的休息用长椅上。

「真正的可爱，要在失去那些优势时才会面临真正的考验。看能否在长大后——至少升上国中后依然维持可爱。」

「京京升上国中后当然也会很可爱。」

假如雪之下在场，她八成会说「原来你都用那种眼光看国中生。真的很恶心，拜托不要靠近我」，然而，她可是重度妹控川崎，她关心的只有「京京很可爱」。

「川崎，那只是假设。你当然会这么说，但那不是事实。」

「是没错，不过这是一定的。」

「世上没有一定。有的只有——」

我从口袋里拿出手机，打开一张照片给川崎看。

「长大后依旧可爱的小町这个天使。」

手机萤幕显示着身穿睡衣，在家里的沙发上耍废的小町。

「……这你妹嘛。」

「嗯，没错。写成妹妹念成天使。反过来说就是写成天使念成小町。」

「是什么东西反过来啦。」

川崎深深叹息。对吧对吧。看到如此可爱的小町，你也只能跪地投降了吧。水户黄门拿出的印盒里面好像也放了小町的照片，所以坏人才会俯首认罪。那声叹息绝对不是「这个死妹控在想什么」的意思吧。

「……是啦，小町——是叫这名字吗？的确很可爱。」

川崎边滑手机边说。

「对吧对吧。」

「不过，你只看过天使而已。」

「……什么意思？」

「意思是，你没看过率领天使的大天使。真可怜！」

「你在说什么啊川崎。大天使这种东西——」

川崎打断我说话，秀出手机萤幕给我看。萤幕上映着打扮成妖精，面带笑容的京京，大概是在演戏。

「怎么样？在这么可爱的孩子面前，也就是在大天使面前，你还站得稳吗？不，不行吧。那就是大天使京京叶的威力！」

她应该是因为是天使，才在名字后面加上跟拉法叶、米迦勒一样的「叶」（注16）。我觉得京京叶听起来怪怪的，川崎的气势却不允许我计较这种芝麻小事。

「这样就知道谁才是等级较高的天使了。」

川崎满意地准备把手机收进包包，就在这时。

「等级较高的天使啊……那么川崎，你知道吗？」

「什么？」

「世上还存在刻意扮成天使，监视大天使有没有把天使往错误的方向引导的极天使。」

「极……天使？」

川崎面露惊愕，我站起来把手机拿到她面前。

「没错！这又是极天使小町叶的模样！」

那是新年时盛装打扮的小町。

「这才是正义！这可爱的模样会净化世上所有的罪与罚！」

我一脸得意。呵呵呵。这样世界妹妹大战就落下帷幕了。我将手机放回口袋，伸手去拿放在长椅上的包包，一只手立刻放到我肩上，以惊人的力量拉得我转过身去。

「极天使上面还有主天使……」

「……不好意思，我们要关店了。」

经店员这么一说，我和川崎才猛然回神。看向手表，现在时间超过晚上八点。记得我是在六点左右来到这家购物中心的，然后马上就遇见川崎……我们为妹妹的可爱争论了将近两小时吗？

「……我和你都挺会说的。」

「是啊，连要买礼物都忘得一干二净。」

川崎有点愧疚。不过我也一样。基于对妹妹的爱，我们不小心进入一步都不肯退让的状态。从这一层意义上来说，我们是敌人也是同伴。想要立刻握紧她的手的神秘友谊存在于此。

「既然已经说好了，找一天再陪你买礼物吧。」

「不用啦，这样我过意不去。」

「没关系，我都答应了。」

然而，川崎还是不肯答应。嗯——尽管有些难为情，我们之间都透过妹妹萌生友情了，跟她坦承应该也没关系吧。

「还有，我刚才没跟你说，其实我今天是来买母亲节礼物的。可是我不知道买什么比较好。所以想请你帮妹妹买礼物的时候，顺便帮我挑我的礼物。这样就互不相欠了吧？」

「是吗？那就这么决定了。」

她总算同意。商量过后，我们决定周末要来这家购物中心雪耻。

「话说回来，早点跟我说你是来买母亲节礼物不就得了？」

「呃，很害羞耶。」

「送家人礼物哪有什么好害羞的。」

川崎讲得理所当然，这句话窜入心中，导致我心里痒痒的。

周末，我们约在「LaLaportTOKYO－BAY」北馆中央广场见面。时间是十一点五十分。我早了一点到。购物中心里面有很多人，非常热闹。

「妈妈——那个人的眼神好可怕。」

「不可以讲这种话。」

「是充满恨意的眼神。」

「是没错，可是不能这样讲人家。」

希望来自身后的对话不是在说我。不行，我快哭了。

我边想边看着手机，收到一则讯息。是川崎传来的简讯。

『你在哪？』

我环视周遭，看见一个同样在四处张望的马尾少女。

『找到你了。我过去就好，你别动。』

我回覆简讯，走向川崎。川崎也在途中看见我，轻轻举手。

川崎穿的是灰色连帽上衣和牛仔裤的简单搭配，我却觉得异常适合她，或许是因为我知道川崎这个人的个性。

「干么盯着我看？」

「没有啊，我觉得这身穿着很适合你。」

「啊？讲什么鬼话。」

川崎朝我瞪过来。不过她大概有点害羞，眼神没有平常那么锐利。

「别管我穿什么了……走吧。」

「嗯。要先从谁的礼物选起？」

「啊——先买你的就好。」

「是喔。那就这样。」

我和川崎看着购物中心的地图。

「仔细一看，这里果然很大。」

川崎有点惊讶。

「那当然。而且这个地方历史悠久，据说它是日本第一家LaLaport。」

我得意洋洋地卖弄知识。

「哦——好厉害。」

川崎好像是真心感到佩服，分享这个知识的我也很有成就感。

「既然有这么多家店，与其选定一家，到处乱逛看到喜欢的店就进去或许比较好。」

「你说得对。那就随便逛吧。」

我和川崎迈步而出。

大约走了三十分钟，我稍微停下脚步。

「怎么了？」

「休息一下。」

不愧是日本屈指可数的购物中心，这里大得要命，要仔细逛过一家又一家店相当累人。

「川崎，你会不会累？我看你脸色不太好。」

「嗯？嗯……我不累。」

她嘴上这么说，表情却有点忧郁。搞不好她其实身体不舒服，只是在意之前那件事（世界妹妹大战）才勉强赴约。可是就算我叫她不舒服就不要勉强，万一她进入备战状态呛我「啥？我又没有不舒服。我状况反而好到不行。不要自以为瞭解我好不好？要不要现在确认看看我有没有不舒服？」怎么办……至于川崎在我脑中的形象到底变成什么样子，就先不说了。

考虑到这一点，最好尽快挑完礼物。

「好，那走吧。」

「嗯。」

我们两个重新启程。过没多久看到一家叫「莉芙」的店。

「啊——这个不错吧？」

是家卖红茶茶叶的店。

「你妈喝红茶吗？」

「啊——好像喝又好像不喝。」

「是喝还是不喝啦。算了，我觉得它挺适合当母亲节礼物的。」

原来如此。我自己绝对想不到送这个。我和店员说了预算，请他帮我挑茶叶。

店员选的是什么玛黑兄弟经典罐装，我在他介绍到一半时化身成只会讲「哈哈哈」、「对啊」的机器人，勉强应付过去，买下那罐茶叶。

「谢谢光临——」

我看了彬彬有礼地对我们鞠躬的店员一眼，走出店门。

「谢啦，川崎。我一个人绝对想不到送这个。」

「希望你妈会开心。」

「好，那接下来去挑你妹的礼物。」

「……嗯。」

川崎仍然无精打采。她的语气明显异于平常，看来我非说不可了。

「……不舒服的话要不要回家？」

「咦？什么？」

突如其来的问题，令川崎有点慌张。

「我看你今天一直没精神，改天再说也行吧。放心，你都帮我挑礼物了，下次我当然也会陪你一起挑。我不会买好自己的礼物就爽约。」

「……我身体没有不舒服。」

「『身体没有』？」

「……找家店坐吧。」

川崎扔下这句话就径自走向前。

「喂，等一下。」

我一头雾水地跟上去。

我和川崎走了一小段路，进入南馆的咖啡厅。客人很多，不过双人座碰巧空着，我们不用等就有位子坐。

「久等了。这是两位的咖啡和柠檬茶。」

我往咖啡里面加了一堆砂糖。加多少才会变成MAX咖啡的甜度？望向川崎，她默默喝着柠檬茶。看来她很喜欢喝红茶，刚才选的礼物也是红茶。

「所以……你为什么没精神？」

面对我的问题，川崎微微垂下视线。

「京京念的幼稚园有养金鱼。」

「金鱼啊。我知道我知道，幼稚园会养金鱼。」

「京京很疼那只金鱼。」

「嗯，正常的。」

「那孩子非常温柔，很疼那只金鱼。」

川崎露出有点高兴的表情，却马上又转为悲伤。

「所以……死掉的时候会难过。」

听见川崎那句话，我大概猜到是什么情况了。原来如此，是这样啊。

「那只金鱼死了？」

「……嗯，对啊。」

她说金鱼是昨天死的。从幼稚园回来的京京心情低落，饭也吃不下。晚上睡觉时，她哭着问川崎「大家都会死掉，消失不见吗？」

「我没能好好告诉她……一想到京京这个时候也还在难过，我就觉得郁闷。」

「这是每个人都会碰到的阻碍。」

只要活在世上，总有一天必定会碰到这方面的烦恼。而如何将这个现象告诉烦恼的小孩，也是年长者必然遭遇的问题。

「我该怎么跟她说……」

看到川崎难得这么温驯，感觉得出她真的很疼妹妹。我自认我也一样疼小町，同为珍视妹妹之人，我想为她做些什么，却不知道该如何是好。

「对了。」

我忽然想到，小町以前也遇过类似的事。养在学校的乌龟死掉时，她亲眼目睹生命的消逝，为此害怕不已。记得那个时候……

「好像是买绘本给她看。」

「绘本？」

「嗯，小町也遇过同样的事，当时我爸妈买了绘本给她。『生命是会轮回的』、『还会再见面』之类的内容。」

「绘本啊。的确，绘本感觉就会写得连小孩都看得懂。」

她以手抵着下巴，叹了口气，显得莫名成熟。

这时，我想到一个主意。

「要不要送那类型的绘本当礼物？」

「礼物？」

「生日礼物。靠绘本学习生命意义的礼物。京京也会很高兴吧？」

川崎频频点头，赞成我的建议。

「你记得那本绘本的书名吗？」

「不记得了。那是满久以前的事，我想不太起来。」

「好，走吧。」

话刚说完，川崎就立刻拎着东西走出咖啡厅。

「等、等等，还没结帐耶。」

我急忙喝光咖啡，结完帐追上川崎。

川崎和我看过楼层地图后，前往北馆二楼的书店。购物中心里面的书店特别大间。我们找到绘本区，直接往那边走。

绘本区比想像中还大。

「这里吗？有满多本的。」

「看到书名，你想得起来送你妹的绘本是哪一本吗？」

「不知道。总之先逛过一遍吧。」

我们一本接一本检查起绘本的书名。我想说看到内容搞不好就想得起来，便把绘本拿起来翻阅。

可是，没看到小町当时看的绘本。

哪一本？到底是哪一本？快想起来。

「想得起来吗？」

川崎放轻语调询问，尽量避免给我带来压力。

「啊——不知道。没看到感觉像的书。」

「是吗？」

川崎只是简短应了声，我们又默默翻起绘本。

花了好一段时间翻完全部的绘本后，至少我记忆中的绘本并不存在于这家店。

「抱歉，川崎。」

「没关系，可能只是这家书店没有，你不必道歉。能看到这么多绘本的机会应该不常有，还满愉快的。」

这句话听起来像在安慰我，害我良心不安。我看过的书里面也有好几部以「生命」为主题的作品，大可从中挑一本，不过真的这样就行了吗？

我思考着。当时给小町看的绘本。记得她因为画技不太好的关系，笑过里面的画。

当时的记忆。小町专注地在客厅看那本绘本。

没错。她之所以那么专注，原因在于……主角是名为「小町」的少女。自己的境遇和同名少女一样，导致她深深为那部作品着迷。

思及此，我觉得不太对劲。

「未免太巧了吧？」

「怎么了？」

川崎盯着陷入沉思的我。

「我记得那本绘本的主角叫小町，内容是她养的宠物死掉了。可是这样未免和小町的境遇太相似，有这么刚好？」

果然是我捏造的往事吗？

「……说不定。」

川崎喃喃说道。

「说不定那本绘本根本不存在。」

「咦？」

我无法理解她的意思，面露疑惑。

「川崎，你在说什么啊。它不存在的话，我怎么会记得有那本绘本？」

「我不是那个意思，也许书店没有，但你们家有。」

听她这么说，我也恍然大悟。

「……原来如此。原创绘本吗？」

「对。可能是你爸妈为了安慰难过的女儿自己画的。」

经她这么一说，也能解释小町为何边看边笑画得很烂。爸妈应该不算擅长画画，搞不好他们画得很奇怪。

「如果结论是这样，那我更对不起你了。」

「为什么？」

「好不容易想到的礼物，结果市面上根本买不到。表示我们又回到起点了吧。不过你觉得送绘本没问题的话，我是有很多本想给京京看。」

我抽出好几本觉得不错的绘本，想递给川崎，川崎却伸手表示拒绝。

「没关系。我反而要感谢你告诉我正确答案。」

「正确答案？」

川崎看起来神清气爽。

我从她的表情推出一个可能性。

「难道你要——」

「嗯，没错。我要自己画绘本。」

「你在说什么啊，川崎。」

虽说我早已猜到这个答案，还是吓了一跳。

「你讲得那么简单，绘本可不好画喔。」

「这点小事我知道。但我想藉由自己的双手告诉京京。因为我昨天没能告诉她。」

略带忧郁的表情，明确传达出她的后悔。昨天那样回应妹妹的后悔。觉得自己很渺小的后悔。

那本绘本，是礼物也是赎罪吧。

「我认为那只是你自我满足的行为，这样好吗？」

我严肃地说。假如川崎只是想为自己赎罪，那就没意义了。

「……我觉得由我亲自告诉她是有意义的。」

川崎对我投以不安却锐利的目光。

「尽管很不甘心，你说得没错，这或许是我自我满足的行为。就算这样，我还是想用自己的话告诉京京。那样最能传达给她……我相信自己。」

「原来如此。不是自我满足，而是信赖的意思。瞭解。」

我将手中的绘本放回书架上，走向书店出口。

「等等。」

川崎的声音使我停下脚步。

「你觉得我的理由……很烂吗？」

转头一看，她带着有点怯懦的表情凝视我。我吐出一口气。

「不是啦。一楼不是有手创馆？得去那边买东西吧。用来画绘本的纸笔之类的。」

川崎愣了下，然后扬起嘴角。

「是啊。」

我们一同离开书店。

之后，我们买完东西便原地解散。

快考试了，她应该还得回家念书。这么忙还得画绘本，挺辛苦的，但我只有叫她加油，还有感谢她陪我选母亲节礼物。

回到家的时候，小町在客厅耍废。

「哥哥，你回来啦——咦，你拿着的是要给在家乖乖等哥哥回来的小町的土产吗——？」

「可惜不是。是母亲节礼物。」

「哦——哥哥终于踏出了第一步！这样离你独立还剩一万九千步。」

「那还很遥远呢。」

「哥哥买了什么？」

小町直盯着我手中的纸袋，大概是对我的礼物很好奇。

「红茶礼盒。没什么特别的。」

「喔——不像哥哥会买的礼物。是你自己挑的吗？」

「……不是，跟认识的人一起挑的。」

本以为小町会说「小町明明叫你自己选！」她却兴奋得两眼发光。

「咦？跟谁一起去的？雪乃姊姊？还是结衣姊姊？」

「都不是。」

「咦？那到底是谁⁉」

「川崎沙希。你也见过她吧。」

「啊——大志的姊姊。」

大志？听见不想听的名词，哥哥我心情不太好喔。

「她也想叫我陪她买东西，这一点我们利害一致。」

「这样啊。」

这时，我想起绘本那件事。对喔，直接问小町就能知道答案了吧？

「小町。」

「什么事？」

我做了一次深呼吸。

「……学校生活开心吗？」

「干么突然问这个？当然开心呀。因为是小町嘛。」

「这样啊。」

结果我还是决定不去问绘本的事。说不定是我和川崎推理错误。绘本不是爸妈亲手画的，只是那家书店没卖。

可是这样有什么不好？结论不是正确答案也无妨。既然如此，真相永远待在薛丁格的猫箱里就行了。

买完礼物的两天后。

我准备放学回家时，感觉到一股异常的杀气。回头望向教室后方，川崎把手靠在门上，招手叫我过去。

谁来看都会觉得她要把我叫去揍。川崎本来就因为气质的关系遭到误会了，为何连叫人都要选择容易引起误会的手段？我边想边走向川崎。

「川崎同学，请问你找我有什么事？」

「来一下。」

川崎抬起下巴指向走廊底端，快步朝那边走过去。川崎同学，我们班的人正在议论纷纷喔。为什么搞得像要教训我一样。

我跟着川崎走出校舍，移动到校舍后面。咦。真的要被揍了？大危机？

「川崎，我做错了什么吗？恐怕是你误会了。别揍脸，至少打身体就好。不对，身体也不要打。」

「你在说什么？」

「咦？你不是要揍我吗？」

「莫名其妙。拿去。」

川崎递给我一叠纸。拿起来一看，好像是绘本的草稿。

「你看一下。」

「是可以……不过别把我叫到这种地方啦。」

「那、那是因为！……要把这种东西给人看，很难为情。」

川崎看起来有点害臊，我在觉得她可爱的同时，脑中闪过「被当成戏剧性的不良少女就没问题吗」这个疑问，算了，本人不介意就没关系吧。

「总之我想听听你的感想。」

「好。」

我看起那篇草稿。

内容如下。

主角京华疼爱的金鱼梅莉死掉了。京华哭了出来。然后把金鱼埋进土里。每天她都想着梅莉看着那堆土，过没多久，一株新芽从那里冒出来，长成一棵树。京华在那棵树上感觉到金鱼梅莉的生命。树愈长愈高，冬天来临。京华为那棵树加上各种装饰，最后大喊：

「圣诞快乐！」

「怎、怎么样？」

川崎提心吊胆地询问。

「嗯，不错啊。」

「真的？」

草稿是手绘的，上面留有涂涂抹抹的痕迹，感觉得出制作过程中真的有考虑到妹妹的心情。

而且，从她脸上的黑眼圈来看，八成是熬夜想出来的。

「我想表达的意思，不知道能不能顺利传达给京京。」

「放心，一定可以。」

「太好了。」

川崎松了口气，整个人的感觉跟刚才会被误认成不良少女的她截然不同。虽然这说法很幼稚，我不禁觉得为他人付出的行为竟是如此可贵。

「剩下把图画好就完成了。」

「这样啊。加油。你妹一定也会很高兴。要在生日那天送给她对吧？」

「对。所以我等等要努力画完，回家准备庆生会。」

「原来如此。很多事要做耶，加油——」

我的话只讲到一半。

「等一下。你说什么？」

「咦？我等等要努力画完，回家准备庆生会。」

「喂！难道你妹的生日——」

「嗯，是今天。」

出乎意料的回答害我一阵晕眩。没想到是今天。望向时钟，已经四点四十分了。时间所剩无几。

「你的意思是，你等等要把这本绘本画完？」

「对。」

「不管你画得再快，至少也要花上三小时，不对，四小时喔。」

「可是京京的生日是今天……不在今天送给她就没意义了。」

话虽如此，做这么费时的事真的好吗？再说，这对看起来睡眠不足的川崎而言是颇大的负担吧。

而且这么晚才办庆生会，也会给京京造成负担吧？

「为什么非——」

为什么非今天不可？开口的瞬间，我想起川崎在购物中心说的那句话。

『一想到京京这个时候也还在难过，我就觉得郁闷。』

是吗？你不仅想为妹妹庆生，也想为妹妹排解内心的不安吗？是吗？是吧。

我搔了下头，望向川崎。

「你想在今天把礼物送出去对吧。」

「对。」

「……我知道了。但我不能让你一个人负责。」

我用手机搜寻「绘本 分工制」，将搜寻结果亮给川崎看。

「你看。」

「这本绘本……每页都是不同人画的？」

「嗯。最近的绘本也会像这样分工合作。重要的页数由你负责，我模仿你的画风画其他部分。这样时间应该能缩短成一半。」

「！那样确实能帮我一个大忙，可是我不能让你做这么多。」

「没关系啦。你让我重新体会到为家人着想的心有多重要，这点小事就让我帮忙吧。而且，你以为我是谁？」

我笑着把手放在胸膛。

「我可是侍奉社的比企谷八幡。」

「谢谢——拜拜——」

京华喜孜孜地挥着手，我在她的目送下离开川崎家。川崎走在我旁边。

「真的可以不用送我。你昨天没睡吧，在家好好休息啦。」

「一小段路而已，有什么关系。」

我们并肩而行。夜晚的街道一片静寂，脚步声听起来特别明显。

「庆生会办得很成功。」

「是啊。京京也很开心，太好了。」

我们和看到蛋糕，兴奋不已的京华一起唱生日快乐歌，为庆生会揭开序幕。然后享用川崎亲手做的大餐，再吃蛋糕当饭后甜点。京华吃得嘴巴旁边都是鲜奶油，川崎温柔地看着她，令我印象深刻。

「对了，母亲节礼物你送出去了吗？」

「还没。今天回家会送。」

「这样啊。不用说是我挑的。你一个人挑的，你妈一定会比较开心。」

「是吗……」

之后是一阵沉默。

「送我到这边就好。女生一个人走夜路也很危险。」

「……我想正式向你道谢。」

川崎停下脚步，对我微微鞠躬。

「谢谢。老实说，我没想到会花那么多时间。」

「别这样。而且我也有计算错误。」

我们虽然赶工把绘本画完了，由于我没把讨论人设的时间也算进去，花的时间比想像中还多。

不过亲眼看到京华高兴地阅读绘本，我深深觉得能在今天送给她真的太好了。京华一定也是诚心感到喜悦，因为她得到了世上仅有一本的绘本。

证据就是送我离开时，她还一只手抱着绘本。

「你把姊姊能做的事都做了吧？我觉得你很伟大。」

「那就好。因为大志和京京都是我重要的家人。」

我想到川崎之前还为了弟弟跑去打工。这家伙真的很努力，但她的行为举止太容易招人误解，很难得到正面评价。

是个笨拙的人。跟我同等级。

「你弟和你妹一定也很重视你。」

我把手放到川崎头上。动作跟摸小町头的时候一样自然，可是我马上就后悔了。糟糕。她八成会骂一连串「少瞧不起我」之类的话。搞砸啦——

我闭上眼睛，却没有被骂，时间静静流逝而去。我害怕地睁开眼，眼前是稍微低着头，脸颊泛红的川崎。

「那、那个——川崎同学？」

我一出声她便回过神来，甩开我的手。

「……我回去了！」

然后抛下这句话，朝她家的方向飞奔而出。我看着她的背影，不知道川崎刚刚的沉默是什么意思。

接着是结尾。

在那之后，我回家把礼物送给妈妈。

她很开心，问我是不是自己挑的。

这时，我想起在川崎家的庆生会上的对话。

「这是姊姊自己画的吗？」

「不是，是姊姊跟这个八幡哥哥一起画的。」

川崎这样回答。

我告诉妈妈，是我值得信赖的朋友帮我挑的。

妈妈非常高兴。

高兴我是和值得信赖的朋友一起挑的。

我觉得可以理解，又好像不能理解。

不过，看见收到礼物的对象喜欢那个礼物，心情果然会很好。

之后川崎传了封简讯来。

『对了，大志的生日也快到了，这次我一样想送绘本。』

我决定无视那封简讯。

完

16注  拉法叶、米迦勒的名字皆为el结尾。

** 然而，那句话的言外之意另有深意。

作者：渡航

——这是最后一次在这间社办看见樱花了吧。

我看着窗外的景色，没有将这句话说出口，只是默默心想。

四月已经进入下旬，薰风送暖的季节将近。

盛放的樱花如同雪花般纷纷散落，取而代之的是青翠的嫩叶探出脸来。尽管有几朵花还留在枝头，已经可以称之为叶樱了。

带着淡粉色的白色花瓣，彷佛要彰显曾经绽放过的事实及时间的流逝，被人扫起来堆在中庭一角，无处可去。

恍若残雪。然而，那句话的言外之意另有深意。

想到明年无法看到这幅景色就有点寂寞，我发现不知不觉间，待在这间社办对我来说成了十分理所当然的事。

新侍奉社刚上路的时候，我虽然会感到无所适从和异样感，随着日子一天天过去也习惯得差不多了。

身穿总武高中制服的我妹——比企谷小町哼着歌整理桌面的模样，也已经司空见惯。但我到现在还没看腻，我妹是不是太可爱了？甚至可以看一辈子。

不过就看不腻这一点来说，其他社员亦然。

雪之下雪乃以俐落的手势冲泡红茶，动作变得更加熟练，多了几分优雅。

「请用。」

她微笑着递出马克杯，给人的感觉比以前温柔，导致那抹微笑的破坏力也随之提升。可是偶尔也会有比以前恐怖的瞬间，某种意义上来说反而是正负相抵。

「啊，谢谢——！」

由比滨结衣接过红茶，语气比以前更有精神，灿烂的笑容变得更加耀眼。

「……我也带了一些过来。」

可是，她从书包旁边的纸袋偷偷拿出东西给雪之下的动作却透出一丝高雅的气质，散发不久前感觉不到的神秘感。

而坐在两人对面撑着颊看手机的人，是非社员却不知为何待在社办的一色伊吕波。

一如往常，却又有点不同。

每一天的变化太过细微，很容易忽略、忽视、无视其中的差异。想见证一切仅仅是永无止境的梦，即使如此，还是会忍不住想守望这段终将消逝的时间。

……是说，伊吕波真的跟以前一模一样耶！一点都没变。反而令人安心。你为什么在这啊？最近你是不是一直待在这？好吧，也不是不行。不过学生会和足球社那边没问题吗……

我既担心又怀疑地注视她，一色发现我在看她，往我这边瞥过来。

她在和我四目相交的同时扬起嘴角，微微歪头。微卷的亚麻色发丝瞬间往旁边垂落，挂在她嘴边。一色慢慢用手拨开头发，用嘴型问我「怎么了吗？」。

勾勒出平缓弧线的雪白喉咙、由下而上的视线，以及无声的呢喃。

像在讲悄悄话似的，害我觉得自己在做见不得人的事。分不清是罪恶感还是悖德感的感觉使我背脊发麻。

我以细微的动作摇头表示没什么，以驱散这种感觉。

看我没有说话，一色笑出声来，轻轻点头。

无声的交流导致那股酥麻感又快要窜上背脊，我抖了一下。

「比企谷同学。」

雪之下忽然叫我，吓得我抬头挺胸。

「咦，啊，是。」

我的语气异常拘谨，彷佛在问「请、请问您有何吩咐！」。

看见我这个反应，雪之下面露疑惑。她纳闷地眯起眼睛，眼神却逐渐转为柔和。像在说「真是个怪人……啊，你本来就很奇怪」似的，点了下头，擅自下达结论，将茶杯递给我。

「我泡了红茶。」

「喔、喔……谢谢。」

我恭敬地接过红茶，偷偷吁出一口气。眼角余光瞥见一色露出讨厌的奸笑。

为何……我什么事都没做错，为何这么累……

总之先喘口气再说。我拿起茶杯。

温度适中的红茶通过喉咙渗透体内，馥郁的香气扑鼻而来。嗯，心情好平静……

这间社办果然跟红茶的香味很搭……我悠哉地心想，闻到一股不同的香味。动了下鼻子，是清爽新鲜的甘甜香气。

这是什么……我搜索着香味的来源，最后抵达桌上。

放在纸盘上的是疑似苹果派的甜点。每当雪之下仔细地把派分切成一块又一块，就会散发出更浓的香味。

「哇，这是什么？自己做的吗？」

小町乐得拍手，兴奋不已。经她这么一说，那个派确实有点朴素，不太美观。但那样反而营造出强烈的手作感，给人温暖的印象。

雪之下微笑着为小町解答。

「嗯，好像是。」

「好像……？咦……」

有点神秘的说法令小町歪过头，我也跟着歪头。接着，微微倾斜的视线范围的边缘，有个人提心吊胆地稍稍举起手。那只手伸向头上的丸子。

「……算、算我做的啦。」

由比滨摸着丸子头，害羞地说道。我发出略带惊讶的声音，小町「哦……」好奇地眯细眼睛。一色则「是喔——」用对此毫无兴趣的语气极其随便地应声。

「总之，开动吧。」

雪之下面带平静的笑容，迅速摆好餐具，进入试吃阶段……

我们配着红茶，各自拿起叉子。

由比滨紧张地看着，最先发表感想的是一色。她边吃边感叹。

「满好吃的耶？」

「嗯，对呀……真的很好吃。」

雪之下接着点头赞同，闭上眼睛仔细品尝滋味。她点头的力道之重，彷佛连单纯的味觉以外的部分都在享受。

旁边有个同样在用力点头的人。

小町每吃一口就沉吟一声，端起盘子从各个角度观察它的外观。

「软趴趴的外表乍看之下有点丑，也感觉得出味道没有融合在一起，不过这也是手作甜点的乐趣……就算把刚烤好的香气和酥脆的派皮也考虑进去，还是有点太甜，不过……」

她大口吃着派，一面碎碎念发表高见，把派吃完后静静闭上眼睛。

社办鸦雀无声。

气氛莫名紧张，由比滨吞了口口水，等待小町继续说下去。

静谧的时间流逝而去，半点声音都没有。

只听得见一色鄙视地说「这家伙在讲什么鬼话……」。

一色刚说完，小町就突然睁开眼睛。

「对于喜欢吃甜食的人而言，这样的甜度反而刚刚好……！及格！及格！」

「万岁——！」

小町竖起大拇指，由比滨紧紧抱住她，两人接着击掌。雪之下见状，满足地微笑。

「由比滨同学，你真的有进步。这进步的幅度跟以前判若两人。」

「不过，我还是跟妈妈一起做的啦。嘿嘿嘿……」

由比滨害羞地梳着丸子头。

「所以，我想……味道应该没问题……」

她边说边偷看我。

原来如此，是跟比滨妈妈一起做的吗？那她就不会乱改食谱或加入崭新的调味料了吧。更重要的是，小町和雪之下都说好吃了。可以放心送入口中。

「我开动了……」

我拿起叉子，吃了一口派。

香酥的派皮瞬间在口中碎开，新鲜的桃子香气及浓郁的甜味紧接着扩散开来。

还以为是苹果派，实际一吃竟然是水蜜桃派。新鲜又惊讶的心情，导致诚实的感想脱口而出。

「……好吃。」

「真的吗⁉」

由比滨激动地回问。我又叉了一块水蜜桃派吃，以代替回答，点头给她看。

嗯，真的好吃。难怪雪之下会满意地点头，吃得心满意足。

光论味道和做为甜点的外观，恐怕比不过外面的店家。

然而，她至今以来的努力及过往的事件，让这块水蜜桃派变得美味好几十倍。

她之前可是连简单的饼干都做不好，无视食谱，加入一堆独创做法和配料呢……

这个水蜜桃派八成比饼干还难做。用桃子做的派不太常见，做的人应该也得费一番苦心。而那个不擅长烹饪的比滨同学竟然做出来了……

光想到就感动万分，吃水蜜桃派的手却停不下来，一口接一口。由比滨认真凝视着我。

或许是基于满足感吧，吃完那块派后我喝了口红茶，下意识咕哝道：

「虽然这样讲很奇怪，真的好吃……哎呀真的很厉害……」

「你夸得太过头了啦。」

由比滨狂拍我的肩膀以掩饰害羞。我被她拍得上半身晃来晃去，她的动作却突然停住。

「不过，太好了……我会再做的。」

这次她没有摸丸子头，而是把手放在胸前，低声说道。语气虽然充满稚气，她的微笑却显得比平常成熟许多，既甜美又苦涩，使我一阵晕眩。看来我因为散发淡淡酒香的兰姆酒而醉了。

虽然知道酒精早已挥发，我还是拿起茶杯，喝了口红茶醒酒。闭上眼睛让自己恢复镇定。

这时，黑暗中冒出一句呢喃。

「我要不要也来做呢……」

不晓得是因为红茶中的咖啡因使我恢复清醒，还是因为听见像在闹脾气的稚嫩声音，我猛然睁开双眼。转头一看，雪之下默默移开视线，噘着嘴巴，无所事事地拨弄黑色长发的发尾。

但那也只有一瞬间，她立刻抬头，露出跟平常一样从容不迫的笑容。

「茶点经常是由比滨同学帮忙准备的。下次让我来吧。」

「没关系没关系！我来做就好！总是让小雪乃泡红茶，我会不好意思啦。而且，看你们吃得开心，我也很高兴……我想做给大家吃。」

由比滨笑着梳理丸子头，雪之下拨掉垂在肩上的发丝。

「不，红茶泡起来并不费事，手作就该以手作回报。既然如此，我也用手作点心回礼才合理吧？」

「不用在意什么回礼呀。不如说，我也想好好回报小雪乃。」

雪之下和由比滨相视而笑。

哎呀，多么和平的气氛。女生互送手作点心真不错。好温馨的画面。

……然而，为何伊吕波带着讨厌的奸笑扯我袖子呢。你兴奋地拉着我的袖子，凑到我耳边讲悄悄话，我很困扰喔。

「学长，要不要我帮你翻译这段对话？」

「不需要。别小看我，我可是女生语检定三级。」

「那什么检定呀……」

我随口胡扯，一色用发自内心傻眼的眼神看着我。小町迅速加入对话。

「小町来负责说明！女生语检定是指女生特有的带有深意的话，也就是女生语的检定……嗯——类似英检。女生语检定三级的话，差不多能理解国三等级的女生语，好像啦。」

小町起初还讲得颇起劲的，结尾却随便到不行，大概是嫌麻烦。可是一色也打从一开始就没有认真听的意思，并未受到任何伤害。

「真没用的技能……是说学长和小米平时都在聊这些吗？你们感情真好。有点恶心就是了。」

「恶、恶心……小、小町觉得不恶心呀……小町只是在陪哥哥玩而已……」

时速一百六十公里的超直接嘲讽，令小町受到打击。哈哈哈，小町，你还得多加修行喔。伊吕波的恶心是那个啦，不是爱情的另一种表现或傲娇或掩饰害羞的方式，而是在真的觉得很恶的时候才会说。所以最好表现得更受打击一点，像我这样。

…………是喔——原来伊吕波觉得我很恶。虽然我早就知道了，还是有点受伤耶。

兄妹俩一同受到打击，一色又补了一刀。

「呃——陪学长玩不是正常人会做的事吧。再说，那东西要由谁负责检定……」

「当然是小町。」

「拿小米当标准喔——绝对派不上用场。」

「你说什么⁉小町很厉害！女子力很高！会讲女生语！哀砍斯必克女生语！」

「你连日文都讲不好了……所以学长对女生语的理解，是以小米为基准对吧——？」

一色歪头询问，我点头回答。

「嗯，对啊。」

「业死业死。」

小町用根本是日文发音的破英文附和。一色抱着胳膊陷入沉思。经过短暂的思考，她抬起脸来。

「……学长的性癖之所以那么扭曲，是小米害的吧？」

「怎么扯到性癖去了……并不扭曲好吗！很正常啊？」

总觉得她毫不掩饰地对我讲了颇失礼的话，我立即否认。可是，坐在我斜前方的小町好像想到了什么，垂下肩膀陷入消沉。

「呜呜……这个……小町可能无法否认……」

骗人的吧，我的性癖很扭曲吗？真的假的？

是说，这两个人都一副熟知我性癖的样子，害我有点害怕，不如说全身颤抖……有点兴奋呢。嗯——没错。我的性癖真的很扭曲。

在我自省的期间，雪之下和由比滨的女生语应酬仍在持续。

她们一个说「我来做」，一个说「我做就好啦」，互不相让。

这样下去，显然不会有结果。

不过一直进行无意义的争论也没意义。两人似乎也明白这一点，吁出一口气，纷纷端起茶杯喝红茶，回到起点。

「总之……来决定下次的茶点要由谁做吧。」

「嗯，要怎么决定呢？」

语毕，她们同时瞄向我。

咦，要由我决定吗……？

等一下。这个状况肠胃自不用说，对头皮也会带来相当大的负担喔～我最近才觉得头顶的发量是不是有点少。我快秃头啰我说真的。

但我可不能随便讲出敷衍的理由。

不管我的头皮会受到多少伤害，我的头会变得多秃都没关系。对我这个毛囊杀手来说，发旋乃身外之物。

我轻啜一口红茶，怀着「我们没有修罗场」（注17）的精神，将自己所想得到的说法通通祭出来，不是随口胡诌，而是全神贯注拼尽全力地唬弄过去。

「嗯——好吃。太好吃了。风在对我诉说……跟温度降到方便入口的红茶根本是绝配……对怕烫爱吃甜的人来说是最棒的组合……派和红茶携手谱出的乐章衬托出彼此的滋味，又互相调和……但愿人与人之间的关系也是如此……」

「又在胡扯了……」

一色彻底傻眼，露出鄙视的表情，我无视她凝望远方，装得感慨万分，紧盯着小町。

位于我视线前方的小町晃了下呆毛，马上做出反应。不愧是世界之妹！反应好快！很快喔小町！小町大口吃派，拿起红茶喝，然后放声大哭。

「怎么会有这种东西……怎么会……没吃过这么美味的红茶和派……比起来，伊吕波学姊根本不值一提……」（注18）

「啥？咦？啊？小米你说什么？」

一色狠狠瞪向跟京极万太郎一样感动得声音打颤、泪流满面的小町。其目光之锐利，彷佛在说「要不要老娘现在就把你筛成大小相同的米粒拿去电锅里煮啊」。实际上，听说大小相同的米粒煮成的饭比较好吃。美味大挑战无论何时都是正确的。我很清楚。

大概是被小町和一色演的闹剧搞到无言了，雪之下和由比滨瞬间全身无力。

「……那就一起做吧。」

「嗯！要不要找一天来我家？」

「好呀。什么时候方便？」

两人露出柔和的微笑，把椅子拉近对方，讨论起今后的计划。

嗯，多美的友情。

这样就告一段落了……吉宗如此心想。（注19）

我擅自觉得这起事件已经落幕，却有一个人看起来完全无法接受。

「……呣——我也很擅长做点心啊，我也会做菜啊。」

一色鼓起脸颊，双腿踢来踢去表示不满。事实上，她在情人节的时候的确顺利做出了巧克力，应该有一定的自信吧。说她根本不值一提未免太可怜。我才刚想着要帮她说话，小町又迅速插嘴。

「哎唷，料理是爱情的表现。只要有爱就Love is OK！反过来说，没爱就是垃圾啦，垃圾。不如说那根本不叫料理，只能叫饲料。」

「唉——出现了，精神论。感觉是学长会说的话，让人超火大……算了，你们两个那么像，这也没办法。」

「并不像。」

一色不满地吐了口气，小町也哼了声。

两人几乎在同一时间别过脸。

嗯——小町妹妹真顽固……是说照她这个说法，伊吕波不是无时无刻都在被我讲的话惹火吗？对不起喔？

一色无视于内心道歉的我，面露疑惑。

「对了，小米会做菜吗？」

「小町做的菜超级好吃喔。她平常就会做家事，还会帮忙做我的份。」

「咦，真的？」

她略显惊讶地回过头，小町并未因此得意忘形，只是表现出十分理所当然的态度，点点头。

「嗯，对啊。与其说做菜，小町挺擅长做哥哥的饲料。」

「没有爱啊……」

Love is over……虽然也曾悲戚，别再提起这个话题了（注20）。好，停停停。我告诉自己男儿有泪不轻弹，将视线从小町和一色身上移开。

眼前的雪之下和由比滨正在调整详细行程。

「我下个月开始要回公寓住，到时再做也行。」

「这样呀！那我每天都过去！」

「那、那个，每天有点……」

由比滨激动得探出身子，雪之下则往后拉开距离。不过，由比滨依然继续靠向前。

「因为我会担心嘛！」

「咦，担心？……咦？担、担心什么？」

看到由比滨面带微笑，雪之下显得不知所措。平常目光慧黠、炯炯有神的双眼，现在视线却在左右游移。

你的眼神未免太飘了吧……在我担心之时，有人从旁拽了下我的手臂。

我把身体靠过去，一色马上凑过来跟我讲悄悄话。

「学长，要不要我帮你翻译这段对话？」

「不，不用。不如说拜托不要好吗？」

就算她帮我翻译，以我的女生语能力也无法判断是否正确。女生语太深奥了。想钻研英文的话有英英字典可以看，差不多该出本女女字典了吧。女生语真的好难。

为了出国学习这门语言，看来我最好回家洗个澡睡一觉。吃晚餐的时候顺便请小町来个一对一教学吧。没错，就这么办。

好，回家……我准备站起来，一色却仍旧抓着我的袖子，所以我动弹不得……甩掉人家的手也不太好。才刚这么想。

她忽然放手，接着从制服外套的口袋拿出手机，深深叹息。表情莫名忧郁，令我有些在意。

「怎么了？」

一色只是摇头微笑，彷佛看开了什么。

「我该回去啰。」

「喔、喔。」

一色迅速起身。在我纳闷「这人到底来干么的……」之时，一色于离开前呼唤雪之下。

「啊，雪乃学姊。」

「什、什么事！」

被由比滨缠着的雪之下一副找到救星的态度光速回问。从来没看过如此敏捷的小雪乃……

「可以请你给我联合舞会的整份资料吗？」

「嗯、嗯，是可以……」

雪之下有点困惑，话只讲到一半，但下半句话不用问也知道。面对「你要拿来做什么」的言外之意，一色抢先回答。

「我想说如果以后也要办联合舞会，由学生会管理那些资料比较好。」

「说得也是。」

那场联合舞会表面上本来就是我们几个自愿办的。当然也有藉助包含一色在内的学生会成员的力量，不过主办方是我们几个自愿者和海滨综合的玉绳他们。原本只是仅此一次的企划，若要改成固定活动，最好给学生会管理。

「……是啊。那你先把这份资料拿去。」

雪之下想了一下，递出从柜子里拿出的资料夹。

「我这一、两天会整理好细部资料，可以吗？」

「啊，细部资料不急，看学姊什么时候方便。只要有个概要就行。」

「是吗？不过反正都要整理，我现在有空，会尽快弄完的。」

话才刚说完，雪之下就迅速整理好桌面，拿出文件放到桌上。挺直背脊，打起干劲的模样，看不出是不久前还被由比滨逼到手足无措的人。两者都很符合雪之下的形象，一样赞。嗯，赞……（这感想彷佛萌到不会讲话的宅宅）。

「我也来帮忙。」

由比滨也一手拿着计算机，俐落地区分文件。小町对立刻开始处理工作的两人投以感动的目光。

「喔喔，舞会……真不错……拿这种活动当工作，真有侍奉社的味道。」

一色听了微微弯下腰，把脸凑到我的肩头。

「学长害小米对侍奉社的印象崩坏了啦。」

「咦咦……是我害的吗……」

由于她突然靠那么近，我反射性身体后仰，清嗓子以掩饰过去，瞥向小町。

「小町，这种活动原本是学生会的工作喔。我们顶多算承包商或外包人员。」

打个比方，就是动画业界的「制作方」和「制作人」的差别——我本想举出一般人也容易理解的例子说明，却被一色的叹息声打断。

「我们也不是只会办活动啦……」

她的语气分不清是疲惫还无奈，不知道想到什么，以手抵着下巴想起事情。然后瞄了小町一眼，露出比平常更温柔的微笑，散发些许的大姊姊气质说：

「……有兴趣的话，小米要不要来学生会办公室看看？可以感受一下气氛。」

「小町不去。不用了。」

我妹却一秒回答，态度十分冷淡。她频频摇头，还顺便甩手表示拒绝。你刚才明明那么感兴趣……

「这家伙是怎样……小米真是个莫名其妙的人……」

「这部分有时超像自闭男的……」

一色一脸不悦，不只一色，由比滨也有点无言。甚至连我都有点无言。

「呃，可以去啊……你不是对学生会的活动有兴趣？」

「可是，小町还有侍奉社要顾……」

怎么办……小町轮流观察我、一色、由比滨、雪之下的脸色。她好像有点犹豫。雪之下停下正在写东西的手，用笔抵住脸颊微笑着说：

「这边由我们负责就好，你不用担心。有人来咨询烦恼的话我再通知你。」

「是、是吗？那、那就一下下……」

雪之下推了她一把，小町便雀跃地站起来。一色招手叫小町过去，把她推到走廊上，转头对我们说：

「那小米我就借走啰——☆」

她做作地举手敬礼，还抛了个媚☆眼，关上社办的门。

然而，在她离去前，门关上的瞬间，我好像看见一色露出奸笑。

小町跟一色前往学生会办公室后，过了一会儿。

很久没有只剩下我们三个人的侍奉社，弥漫红茶及水蜜桃派的香气，平静的时间缓缓流逝。

由比滨愉快地敲着计算机，她的哼歌声和雪之下写字的声音令人心旷神怡，与我整理文件时敲击桌面的声音形成和谐的合奏。

这时我的手机震动起来，产生了不协调音。

本以为是手机游戏的通知，看向手机，是小町传讯息给我。打开来一看，里面只有简短的一句话。

『救救小町……』

你放心！（咚！）（注21）

我顺从内心这股冲劲，一语不发地站起来。可能是因为太过突然，由比滨和雪之下吓了一跳，气氛顿时尴尬。

「怎、怎么了……」

由比滨战战兢兢地问，我随便回答了几句便冲向门口。拉开社办的门，侧身回过头。

「小町好像有点遇到危机。我去看看。」

她们错愕地眨了两、三下眼，立刻露出微笑。

「慢走。」

「慢走——！」

我听着身后的温暖送别词，赶往学生会办公室。

急得像要把四条原稿的死线扯断般，于走廊上奔跑。写不出半个字。

不久后，我抵达学生会办公室，急忙敲了几下门就用力打开。

要赶上……一定要赶上啊……

「小町！」

门发出响亮的声音开启，我看见小町坐在桌上的文件山后面。

她哭着在跟疑似文书作业的工作奋斗。浏海用发夹夹起来，额头上贴着退热贴，旁边还有一堆能量饮料，让人看了心痛不已。

「不是……这不是小町心目中的侍奉社……也不是学生会……不该是这样的……」

她像在下诅咒似地抱怨着，听见开门声，猛然抬头。一和我四目相交，无神的双眼就恢复光芒，同时泛起泪光。

「哥、哥哥……」

「什么嘛，你看起来很有精神啊。」

「哪里……看得出小町有精神……那双死鱼眼，有存在的必要吗？不需要了吧？」

她用超低的声音唾骂。

但我亲身经历过，工作真的忙不过来的时候，不会只有这个程度。真的在赶死线时会忽然大叫，用后脑勺狂撞墙壁，赶不上死线时则会自暴自弃跑去睡觉。真的赶不上死线时已经是无的境界。无。连两天没吃饭都不会发现的无。虚无。

跟那些比起来你还算有精神的啦！没问题没问题！累的时候看看比自己惨的人，打起干劲吧？

我正准备随便给几句建议再闪人，背后瞬间传来锁门的声音。

我惊讶地回过头，眼前是面带阴沉微笑的一色。

「呵呵呵，学长，就知道你会来……」

「一色……你要做什么……」

「只要把小米逼入绝境，她一定会跟你求救。这样学长一定会来……因为学长拒绝不了小米的请求！」

一色宛如在谴责犯人的侦探，指向我断言。

「你的请求我也拒绝不了啊。」

「是、是吗……这样呀……」

她卷着脸颊旁边的头发，彷佛不知道该把伸出来的手指往哪里摆，迅速移开目光，喃喃自语。刚才的气势消失殆尽，反覆咕哝着「是吗……」。然而，她突然静止不动。

接着用水汪汪的大眼注视我。

「……是吗？满常拒绝的吧？」

被发现啦。可是伊吕波每次都会使出各种手段，所以我嘴上在抱怨，最后还是会帮忙。她把我教的「有事相求的小女生很可爱」拿出来付诸实行，我只能举手投降。而这位学生正在威胁我，手上还握有妹质，无异于犯罪。

「用不着这么做，只要你跟我说，我会帮一些忙啦。虽然只是一些。」

「没有啦，我想说……打扰你也不太好，至少给你一个藉口。」

万一她之后又抓小町当妹质，我可应付不了，因此我稍微叮咛了她一句，一色却露出意味深长的微笑，把手放在脸颊上装可爱。谢谢你这么贴心喔……

算了。不管怎样，我不帮忙她就不会放走小町。

我拍了下小町的肩膀慰劳她。

「小町，你很努力了。去那边休息一下，看我工作吧。剩下交给我。」

「呜呜……麻烦了……剩下交给哥哥……」

我感慨地说，小町摇摇晃晃站起来，将位子让给我。我才刚觉得她看起来好累，小町就伸了个大懒腰，撕下退热贴，踏着小跳步走向一色自己带来的冰箱。

「哥哥，你要喝什么？这里有好多种饮料。」

「……都可以。」

没错，只要小町有精神就好……即使这出闹剧的剧本是小町写的，只要小町有精神就好……

我接过小町哼着歌拿给我的咖啡，大略看过堆在眼前的文件。

「所以，这是什么工作？」

「仔细检查今后的日程表和预计要办的活动。之前那场舞会把计划整个打乱了。」

一色边回答边坐到我旁边，拿出刚才从雪之下手中接过的舞会资料。

「哦……」

关于舞会那件事，我们也给他们添了许多麻烦，帮忙善后反而是应该做的，但我还是有点不明白。

「其他学生会成员呢？」

舞会是非正规活动，由我们筹办才合理，不过安排活动本来是学生会的工作。现在却看不见该做这些工作的人。

一色长叹一口气，指向学生会办公室的角落。

副会长带着祥和的笑容，幸福地坐在那里。还有一名将黑色长发绑成一束，垂在胸前的美少女。糟糕，我完全没注意到他们。

「之前那家咖啡厅虽然也不错，下次要不要去其他地方看看？我在新习志野发现一家超级澡堂，那里的岩盘浴好像很不错……」

「讨厌，牧人你动不动就在讲这个。就跟你说我会害羞啦。」

他们俩聊得有说有笑。喔，什么？三温暖？你们在聊三温暖吗？是那家对吧，新习志野的「汤～Neru」。那家不错喔，岩盘浴有三种。我的心情躁动起来，想跟他们一起聊三温暖，一色不悦的清嗓声却将我拉回现实世界。

「副会长和书记妹妹也有在工作，可是效率超级差……」

「原来如此……」

看来是因为那块空间太闪太幸福，我下意识避免去看那边。可是，他们好像也沉浸在两人世界中，没把我们放在眼里。别小看工作喔给我滚去做事我说真的。唉这里好歹是神圣的学生会办公室，会长也在场喔。最近的年轻人真的不知道道德两个字怎么写，人伦沦丧啊。不干了不干了解散！我说，真的别小看工作喔？去干活好吗？我如此心想，瞪着副会长，发现不太对劲。

「咦？书记妹妹？那人是书记妹妹吗？」

一色点头回答我的问题。

真的假的……我重新仔细观察副会长旁边的美少女。没绑辫子，也没戴眼镜，但经她这么一说确实有像。空耳时间（注22）到了。看来副会长培育了不起眼的女朋友。哇～好厉害。

一色无视佩服的我，碎碎念道：

「要交往也不是不行啦，但他们一发起花痴就派不上用场……还会害人不想待在学生会办公室……」

「我想也是。」

「对呀。真的是一发起花痴就派不上用场。」

「对啊。为什么说了两次？」

这很重要吗？感觉你这句话带有言外之意，我会很在意，所以请不要这样。

然而，刻意追究感觉会自找麻烦，于是我摊开文件，转移注意力。

好，专心工作专心工作！尽管因为亲友价的关系没薪水可领，既然已经答应，只能硬着头皮上了。友情不会要求回报。虽然我不确定我跟一色是不是朋友，至少我是她的学长。

我先对照整年的活动排程和个别案件，揪出有问题的地方。

粗略看过资料后，看得出学生会的工作好像通通时间不足、预算不足。也有几个无谓的活动和地雷案件。这种麻烦的案件只要有一个出问题，就会连带影响其他部分。

「……总之先把地雷案件找出来吧。」

「喔……咦？只是找出来而已？有意义吗？」

「嗯，光是把它们标记出来，就会轻松很多。」

话虽如此，小町跟一色都只是一脸纳闷。呵呵呵，你们社畜经验还不够喔。虽然我的社畜经验也是零。应该是零才对啊……算了，先跟她们简单说明一下。

「只要知道那个案件很雷，就能做好觉悟，或是彻底死心，心情会轻松许多吧。」

「什么问题都没解决……」

「嗯……精神状态也很重要没错啦……」

一色无奈地垂下肩膀，小町露出参杂困惑的笑容。不对，像这样帮案件分类，还能在实际工作时节省时间精力喔。本想随便乱讲，但我讲出来应该也不会有说服力。因为我总是在极限状态下工作……

然而，多亏我之前光速处理过好几件时间超赶的工作，训练出了找地雷案件的直觉。赶快来找吧～我，要成为踩地雷王！（注23）

我打起干劲，立刻发现一个。

「下个月有球技大赛……」

「每年都会办，必须先想好要比哪些项目呢。」

我烦恼地看着文件，一色从旁探出头。忽然接近的亚麻色发丝散发出一股花香，害我的身体反射性往后仰。一色则探出上半身拉近这段距离，指向文件角落的文字。

「这里有列出选项，每种都需要在各方面做调整～超麻烦的。」

一色抱怨了一连串，由于她一下拨头发一下把手放在我肩上，老实说，我半个字都听不进去。请不要碰我上臂！住手，制服互相摩擦会害我起鸡皮疙瘩！没有直接碰到反而更令人介意！

我将上半身往更后面的地方靠，把重心转移到小町的方向。啊啊，小町的味道让我平静下来了……所以，不管小町探头凑过来还是手碰到我，我都不会有任何感觉。小町也一副「这家伙好碍事」的态度把我推开。

「哦～还有这种活动呀。」

「举办时间在刚入学跟分班后，有部分也是要增进同学之间的情谊吧？」

「喔喔～」

一色对佩服得赞叹出声的小町，露出有点摆学姊架子的笑容。既然如此，我得摆出更大的学长架子。

「未必能增进情谊啦。搞不好会是高中生活最后一次参加的活动。」

她们对我投以「这家伙在说什么鬼话」的眼神。奇怪，我期待的是对前辈的尊敬啊……

我清了下喉咙，决定继续高谈阔论。

「那段时期还没建立稳固的人际关系，所以一旦出错，之后的学校生活会过得很痛苦。这样就得消去存在感，等待暑假来临。」

新学期是每个人都雀跃不已的新鲜期，因此会忍不住想引人注目。在自我介绍时虚张声势、想搞笑结果把气氛搞僵。像这样因为新鲜感的关系出错的话，别说打开夏天的大门，根本是挖掘通往夏天的隧道的等级。甚至严重到寻找再见的出口。

我随便扯了一堆，两人面色凝重地点头。

「的确……」

「有经验的人讲出来的话就是不一样……」

呵，还好啦。小学和国中都被疯狂排挤，导致我已经是被排挤名人了。不对，我不会止步于名人，我要立志独占七冠，首先以龙王的工作（注24）为目标。我得意洋洋，这次终于被当成前辈看待，她们的视线却不带丝毫敬意，甚至带有怜悯的意味。奇怪……「人生的前辈」原来不只有正面意义呢！人生好难！我面对文件，以摆脱两人的视线。

目前的选项有足球、篮球、垒球、排球、桌球、网球、橄榄球等等。大多都是我们学校有的社团。考虑到设备及道具，从里面选应该比较适合。

「……还没决定的话就网球吧。网球啦，网球。我想跟户冢一起打网球，还想跟他一起做其他事。」

「太公私不分了吧……」

「你没资格说……」

你也滥用职权办过活动吧……本来是出于善意的提醒，一色却一个字都没听进去，可能是耳朵被奈露莉割掉了（注25）。不仅如此，她还继续抱怨。

「不过真的有耶，每次办活动都想藉机和女生拉近距离的人。明明在那之前从来没说过话，不如说都在等别人跟他搭话，有点可悲，却只有庆功宴会拼命邀人去。他觉得大家吃过一次饭感情就会变好吗？」

「……别说了一色，那句话对我有效。」

我没实际经历过这种事，但我绝对属于那类型的人，因此精神受到很大的打击。

「那个，伊吕波学姊，够了……」

小町苦笑着抚摸我的背。大概是我太过可悲，一色也急忙用双手的手指按住嘴唇。她维持那个姿势歪头装可爱，彷佛在跟我道歉。我和小町看了纷纷露出笑容。拜其所赐，小町的语气也变柔和了。

「没关系，学姊知道就好。哥哥也知道自己是个超卒仔还会误以为有机可乘，企图冲一波的废物，所以请你以后不要太刺激他。」

「那个？为什么你又补了一刀？可以不要这样吗？哥哥不是濒死的敌人喔？」

被小町讲成废物的打击太大，害我脑中响起悬疑风的钢琴旋律，还附带受到打击的「当当！」声。

「哥哥，想打网球的话小町陪你打。之前大志约小町打网球，小町跟他说要约大家一起去！」

「……他只想约你一个人吧？」

一色的语气带着些许同情，我却没心思管这些。

那个混帐东西，光是加入有户冢在的网球社还不够，竟然拿网球当藉口对我妹出手，好大的狗胆。光是过着垃圾与天使的网球社人生（注26）就不可饶恕了。小心我折断你的手指，甚至连脖子我都折。

「好，我知道了。网球不行……再说人数太少，无法预测比赛时间。还有场地问题，不能同时举办多场比赛。」

「对呀……既然你知道就别提议了。」

我接收到一色鄙夷的目光。还不错。托她的福，我进入状态了。

「选大众一点的球类运动就行了吧。足球、篮球、排球、桌球这种运动大家也都熟悉，应该不会有人有意见。问题在于比<Regulation>赛<rt/>规<rt/>则<rt/>。」

「啊……这部分呀……」

一色不耐烦地叹气。

小町则点着头咕哝道「Regulation啊原来如此那什么东西」，看过来用眼神叫我快点说明。没问题，我的LIL SISTER，交给我吧。

「打个比方，如果足球社社员在球技大赛的足球比赛上开无双，会有种不公平的感觉吧。可是给他们加上奇怪的不利条件，又会有人有意见。所以主办方需要制定这方面的规则。」

小町点点头，一色烦恼地沉吟。

「不利条件，加了感觉会有人抗议耶～例如户部学长……」

「规则就全丢给社长会去想。自己订的规则总不会有意见吧。事实上，也不是凡事都能由学生会决定。」

可惜的是，只靠我们这些人，再怎么努力都没办法连小事都顾到。要是有人在那边吵「没加入社团却有加入俱乐部青年队的人怎么办」这种琐碎的细节，根本没完没了。想避免惹来抱怨的话，也可以改成不是以班级为单位参加，而是自由参加，但整理参赛者名单是件麻烦的工作。重点在于，这是以增进同学情谊为目的的学校活动，想改成自由参加应该有点难度。

谈着谈着，一色点了下头。

「我去找叶山学长商量看看。」

「嗯。不如说在把工作扔给我之前，先去跟叶山商量啦，虽然我觉得就算你去问他，他也只会回答『那是你的工作吧。我能做的事情有限』。」

「超不像的！咦，你在模仿叶山学长吗？咦，超不像的！」

我认为这超像叶山会说的话，一色的评价却不怎么好。不仅如此，还有种「你瞧不起人吗？」的恼羞成怒感。

我被她吓到，手自然而然伸向后颈抓头发。

「嘿——嘿——伊吕波～你怎么能这样～哇咧——」

「啊，这个就很像，超像的，好好笑。」

这反应明显参杂着嘲笑……

「……是、是吗？我觉得不像耶。你大概是对户部太没兴趣，对那家伙没印象吧？」

「不会啦！好像喔！哥哥，对自己更有信心一点！」

方向错误的护航从小町口中传出。

我忧郁地看着竖起大拇指的小町，旁边传来疲惫的叹息。转头一看，一色双臂环胸呻吟着。

「怎么了？」

「没有啦，我在想去足球社有点麻烦……」

「哦……发生了什么事吗？」

若是平常，她早就冲去找叶山了……我有点担心，就问了她一下，一色轻声叹息。

「……新加入的社员超烦的。一年级男生和女经理都一直来缠我。我不是学弟妹不喜欢的类型吗——？」

「啊——小町可以理解～学弟妹好像都满不擅长跟伊吕波学姊相处的。」

「讲反了啦。是我不擅长跟学弟妹相处。」

小町嘻嘻嘻地嘲笑她，一色扮了个鬼脸威吓她。讨厌啦，我学妹与妹妹的惨烈修罗场（注27）。

两人互瞪了一会儿，一色突然嗤之以鼻。

「话说回来，我觉得学弟妹也不会多喜欢小米。」

「呣，没礼貌！」

我点头附和愤慨的小町。

没错没错，小町很会照顾人的。川什么的同学的妹妹——京华也受过她的照顾，有可靠大姊姊的一面。我还没帮她说话，小町就挺起胸膛补充。

「小町对其他人没什么兴趣，所以是会把表面功夫做足的类型！」

「哈哈，这人好可怕。学长，这孩子有点可怕喔。」

一色指着小町跟我说，不用你说我也知道啦。小町有待人冷漠的部分。不在乎的话只要做表面功夫给别人看就行了，她却会展现冷漠的一面给一色看，真的很可怕。可怕到我想不到词汇可以形容。

我决定表现出认真工作的态度，以免被她们抓到我在暗自窃笑。

「球技大赛差不多就这样吧。其他的是……」

在我翻阅文件时，门外传来轻轻的敲门声。一色应声后，门无声地打开。

「一色同学，剩下的舞会资料整理完了。」

「这是给你们吃的。」

拿着资料夹的雪之下和拎着纸袋的由比滨，走进学生会办公室。

「明明不急却搞得像在催你一样真对不起。谢谢学姊特地拿过来！」

一色走到门前，鞠躬接过资料夹和纸袋。

「不会，我本来就在想之后要来统整资料，刚好趁这个机会处理。」

「对对对，而且我们也会担心小町。」

由比滨用力跟小町挥手，小町也挥手回应。这家伙完全忘记是她自己跟我求救的……

「不好意思把事情搞得这么大。谢谢两位的帮忙。」

一色笑着低下头，顺手握住门把。雪之下和由比滨见状，纷纷退后一步。

「嗯、嗯，那我先走了……」

「再见！」

离开前，两人往我这边看过来，我点头回应。她们同样点了下头，门慢慢关上。

「人家都特地带东西来给我们吃了，就边吃边继续工作吧。」

一色走回来开始分水蜜桃派，小町也迅速动手泡咖啡。

这、这样啊，不是先休息一下，而是继续工作吗……正常来说都会提议休息片刻不是吗……我望向旁边，一色正哼着歌翻阅文件。

「接下来是……学生大会吧～」

她吃着水蜜桃派翻开资料的瞬间，学生会办公室的门再度响起。

「嗯——！」

嘴里塞满水蜜桃派的一色，用含糊不清的声音回答。

门随之开启，理应已经离开的雪之下和由比滨从后面探出头。

「……那个，不介意的话，我们也来帮忙吧？」

雪之下客气地提议，由比滨在后面不停点头。

一色急忙配茶把派吞下去，站起来飞奔到两人面前低头鞠躬，惶恐至极。

「不不不！这怎么行不能让考生做这种事！」

奇怪，我也是考生耶……咦？你刚才是不是说了「这种事」？

我怀疑地看着一色，她刚好在双手合十，膜拜那两个人。

「不如说我想等有更难处理的工作时再拜托两位所以今天真的不用了。我说真的忙不过来的时候我会不客气地拜托你们的。」

我觉得你这说法也不太好，不过在一阵推托后，她们俩心不甘情不愿地让步了，门再度关上。

一色累得叹气，拭去额头的汗水，走回原本的座位，调整好坐垫后才轻轻坐下。

接着，这次门没有被敲响，而是突然打开。

「不好意思，一直来打扰你们。」

愧疚地从门后走出的当然是这两位，熟悉的雪之下雪乃小姐与由比滨结衣小姐。

「小町会晚归的话，钥匙由我拿去还吧。」

「要不要帮你把东西拿过来？」

一色站都站不起来，无力地仰望天花板。

「这个用LINE说不就行了……」

疲惫不堪的声音于空中回荡。接着，她狠狠瞪向我。似乎是在叫我想点办法。呃，跟我说也没用……

然而，我也很难在这种静不下来的状态下工作。可是为了这种杂务麻烦雪之下和由比滨，我又过意不去。既然如此，用最快的速度做完工作回去才是正确答案。

我清了两、三下嗓子，对雪之下和由比滨说：

「那个，我们会马上把工作做完回侍奉社……好吗？」

「是的！光速解决！」

小町精力十足地同意，站在门前的两人扬起嘴角。

「这样呀，等你们回来。」

「太晚的话再来接你们。」

她们分别露出温和的微笑与开朗的笑容。雪之下依依不舍地缓慢关上门。由比滨直到门彻底关上的前一刻都在挥手。

两人离开学生会办公室后，一色终于坐起身。

「所以说满脑子恋爱的人真的是……」

她大叹一口气，对角落投以严厉的视线。我跟着看过去，是副会长和书记。你们一直待在那喔……

看来他们也目击了整个过程，目瞪口呆，表情像是傻眼也像是困惑。讨厌，竟然被看到了，好害羞……

「那边那两个知道没？在其他人眼中你们就是那个样子。」

被点名的副会长跟书记抖了一下。

「……我、我不太明白你的意思。」

「我们会注意的……」

副会长还在装傻，书记倒是挺干脆地认错。我也不太明白她的意思，不过我会注意的。

好、好！打起精神，继续工作吧！对不对！副会长和书记好像也在反省了！别再责备他们啰！

我重新提起干劲，俐落地检查文件，伊吕波却还有点不高兴……

「不需要来那么多次吧。」

「叫她们不要来反而会更想来。这就是所谓的卡里古拉效应。」

尽管一色没有直接叫她们别来，郑重拒绝有时带有强烈的禁止之意。多少会有人理解成这个意思吧。

我讲出一知半解的知识，小町双手一拍。

「喔喔，那个！经哥哥这么一说，小町也听过……」

「小米，原来你知道呀。」

一色惊讶地回问，小町装出一本正经的态度回答：

「是的。看那本绘本就会想吃松饼的效应……」

「你说的是《古利和古拉》（注28）吧。它的确是本好绘本啦……」

什么嘛，还以为你真的知道。这家伙干么害人误会……我无奈地垂下肩膀，小町噘起嘴巴。

「那，那是什么效应？」

「简单地说，卡里古拉效应就是愈禁止就愈会想做的心理。警报器上面写着不准乱按，却会让人有点想按下去对不对？电影的宣传词用『千万不能看……』当标语吸引人去看，也是同样的道理。」

「哦～原来如此。」

小町点点头，露出「我懂了——」的表情。

一色却抱着胳膊独自沉思。不久后，她轻轻抚摸嘴唇，低声说道：

「是啦……愈禁止愈让人想做……愈是想要别人的东西，之类的？」

她有点俏皮地说。脸上的笑容明明很可爱，看起来却异常撩人，害我有点背脊发凉。

「不、不，有点不一样吧……」

我连忙移开目光，把注意力放在工作上。

「是吗——？」

眼角余光瞥见旁边的一色伊吕波在愉悦地呢喃。

急忙搞定文书工作，仔细调查有一堆事要讨论的年间活动，揪出地雷案件后，或许是因为那天实在太忙了，隔天整个悠哉到不行。

一如往常弥漫着红茶香气的社办内，是熟悉的景象。

只不过，之前常出现的一色却不在。也是啦，她不想待在学生会办公室的原因是副会长和书记，如今那两个人应该在认真工作，学生会大概也要忙起来了，说不定她这段期间都不会过来。

那家伙也变成一个优秀的学生会长了呢……

我像个坐在缘廊的老爷爷喝着红茶，这时社办的门忽然被人整个拉开。

「辛苦了——」

轻快甜美的声音传入耳中。不必特别往那边看都知道，一色伊吕波来了。

一色彷佛把这里当成自己家，大摇大摆地走进来，坐到快要变成她的固定位置的地方——我和小町之间的座位上。

「今天的点心是什么？」

「这间社办可不是咖啡厅……」

雪之下虽然感到为难，还是好好帮她送上一杯茶，由比滨则搜起书包。

「今天是买来的。」

「啊，这样呀。那正好。」

这句话令我们头上同时冒出问号。什么东西正好……我看了她一眼，一色将手中的纸袋放到桌上。

「我总是在吃雪乃学姊和结衣学姊的东西……」

她拿出一盒点心礼盒。费南雪、玛德莲、佛罗伦丁饼干，一打开可爱的包装袋，奶油的香气就扑鼻而来。

「这是我的回礼♪」

一色拿了纸盘子，把甜点摆得漂漂亮亮，推到桌子的正中央。

雪之下瞬间眯细眼睛，由比滨整张脸都僵住了。和笑咪咪的一色形成强烈对比。

「这样呀……谢谢你。」

「哦……好像很好吃。」

她们两个明明都在笑，语气却非常锐利、僵硬。

讨厌，怎么有股寒意……今年是冷夏吗？我觉得有点冷，假装什么事都不知道，往窗外看过去。

彷佛一切声音都消亡殆尽的漫长沉默，刺得耳朵好痛。

这时，超级缺乏紧张感的声音于这阵沉默中响起。

「哦～伊吕波学姊好会做点心耶。真的做得不错，小町有点惊讶。」

「还好啦……你的反应是不是比结衣学姊那时候还要平淡？」

一色挺起胸膛得意地说，却因为小町的反应太没诚意，有点不高兴。可是小町嘴上这么说，拿点心的手却没有停过。

嗯～她们感情真不错，好治愈。

我又像个坐在缘廊的老爷爷一样，看着小町和一色喝茶，这时一个纸盘送到我面前。

我瞄了旁边一眼，一色以无言的微笑要我发表感想。她都做得这么明显了，我可不能不吃。我说着「啊，那我开动了」，客气地点头致谢，拿起费南雪。

咬下去的瞬间，奶油香于口中迸发，还带来一阵扑鼻的芳醇甜味。口感湿润，连吞咽时都感觉得到它的柔软，和红茶也很搭。

「啊，好吃。」

难怪小町会称赞。不用刻意去夸，这个感想就脱口而出。一色听了，用手指掩住嘴角笑着说：

「我不是说过我擅长做料理吗？」

「我知道。」

之前我也看过一色做甜点，甚至亲自试吃过，所以我自认挺瞭解她的厨艺。

正因为这样，我才回答得那么简洁有力，一色看起来却不太满意，有点无奈地耸耸肩膀。

她从旁伸出手，紧紧抓住我的袖口，然后直接把我拉过去。在上半身歪向她的我耳边悄声说道：

「学长，要不要我帮你翻译刚才那句话？」

只有我听得见的淘气呢喃，轻咬了我的耳朵一下，接着立刻远离。只留下分不清是罪恶感还是悖德感，令人害臊的感觉。

我轻轻摇头，以驱散那种感觉。

「不，不必。」

反正再怎么推测她的言外之意，连推测出来的结果都另有深意。女生语就是这样。更何况对象还是一色伊吕波，现代最强小恶魔。我这个等级不可能敌得过她。

看见我除了苦笑以外做不出任何反应，只有一色一个人轻笑着扬起嘴角。

没错，只有一色一个人……

完

17注  恶搞自美国电影《我俩没有明天》。

18注  恶搞自漫画《美味大挑战》中京极万太郎吃到海原雄山的香鱼料理时所说的台词。

19注  时代剧《暴坊将军》中，总会以「吉宗如此心想」这句旁白作为每一集的结尾。

20注  欧阳菲菲《逝去的爱》的歌词。

21注  恶搞自《航海王》里鲁夫与娜美的对话。

22注  日本综艺节目《塔摩利俱乐部》的其中一个单元，介绍观众将各种外国歌曲的歌词听成日文的投稿，来宾常给予「这么说来确实有像」这个评价。

23注  恶搞自轻小说《我，要成为双马尾》。

24注  恶搞自以将棋为主题的轻小说《龙王的工作！》。「七冠」指的是职业棋士的七大头衔。

25注  恶搞自轻小说《割耳奈露莉》，作者石川博品所写的短篇也有收录于本书中。

26注  恶搞自轻小说《垃圾与天使的第二轮人生（クズと天使の二周目生活）》，作者天津向所写的短篇也有收录于本书中。

27注  恶搞自轻小说《我女友与青梅竹马的惨烈修罗场》。

28注  《古利和古拉（Guritogura）》为两只叫做古利和古拉的老鼠烤松饼的故事，日文与「卡里古拉（Karigyura）」音近。

** 后记

后记（石川博品）

「《果青》的读者是侍奉社的第十二位社员。够资格当短篇小说集里的短篇的主角」。虽然我用这个理由把责编骗过去，顺利过稿了，仔细一想，侍奉社有那么多人吗……

我还想了另一个版本，是「没能把《果青》看到最后就死掉的少女怨灵和灵能者联手袭击渡老师的果青豪宅」。从粉丝变成酸民的怨灵，将渡老师收集的艺术品、高级房车、大得莫名其妙的床全数摧毁！现实世界中不可能发生的秩序的颠倒及错乱——这才是故事拥有的力量吧。

我现在觉得自己毁掉了我那篇短篇的主旨。

九年是段非常漫长的时间。对于三、四年就会进入人生下一个阶段的年轻人而言，就更不用说了吧。正在看这本书的你与《果青》共度了多久的岁月，我无从得知，不过应该已经待在跟初次接触《果青》时不一样的地方了。我的话，九年前我每天都怀着「不想写了不想写了」的心情在写没希望出版的小说。现在则是「游戏好好玩～♥饭好好吃～♥我的侄女会荡秋千了～♥」的感觉，每天都过得很幸福～♥

人老了果然会变白痴。

但愿我所写的短篇能让您想起曾经所在的地方，以及在那边与您共度时光的人们。

后记（王雀孙）

我和渡航第一次见面是在十年前，他的出道作《あやかしがたり》完结的不久后。在那之后我们也陆续见过几次面，某一天，他跟平常一样用有点目中无人的态度（※他一直都是这样。现在也没变）对比他大一轮以上的我说：

「我正在写校园恋爱喜剧，因为同时在玩雀孙老师的游戏的关系，文风受到您很大的影响。」

我至今依然记得很清楚，他不知为何一脸困扰。然后带着困扰的表情接着说：

「咦，可以致敬您吗？」

这个年轻人会红——我受到震撼，拿他要把我奉为心灵的师父崇拜当条件，答应了这个要求。另外，由于是「心灵的」的关系，我不记得自己教过他什么。就是这样，各位果青的读者初次见面嗨啰，我是原作的心灵的师父王雀孙。有机会再见。

然后借这篇后记通知各位一下。为求方便起见，这篇短篇是以「王雀孙」的名义收录于书中，其实我受到许多作家朋友的帮助，是也有参加这本短篇小说集的相乐总先生、境田吉孝先生，以及原作渡航先生，真的谢谢你们啦。3Q～☆

最后是私讯。星野编辑长。这次真的非常感谢。

后记（川岸殴鱼）

大家好，我是跟渡航先生同期出道的那个内行人才听过的川岸殴鱼。

《果青》第一集是在二○一一年三月出版。因为东日本大地震的关系，物流作业一团混乱，《果青》却完全没受到影响，初版转眼间就卖完了，趁着这个势头再版又再版……

闭上眼睛，那就像昨天——或者说九年前发生的事一样，浮现脑海。

说到当时GAGAGA文库的老作家，就算书卖不好也能得到原谅，不如说几乎所有人的书都卖不好，因此销量不佳反而让大家产生了同伴意识，有种连带感。过着「没办法。毕竟我们家不是电击文库」的这种温水煮青蛙般的生活。

打破那个幻想的，是上○当麻——不对，是《果青》这部作品。

符合流行的主题、战略，更重要的是作品的品质。《果青》的刀刃破坏掉了装满温水的泡澡桶，将我们从温度舒适的温水拉回到寒风肆虐的现实世界。当时我是这样想的。「让我回去泡温水」。我可是因为一直泡在温水里，一件衣服都没穿喔。

各位也知道，从那一天起过了九年，《果青》做为GAGAGA文库的台柱，做为轻小说的台柱，长成了一棵大树。

如今《果青》完结了，我非常期待渡先生下次会破坏什么东西。我会翘首盼望那一天的到来……以全裸的姿态。

后记（境田吉孝）

初次见面。或是好久不见，我是境田吉孝。

我喜欢平冢老师，真心的。想跟她结婚……不对，那个，我以最自然的态度写起后记结果第二行就出现认真向平冢老师告白的句子真的很不好意思，可是平冢老师的外貌（人设）、性格（设定）、声音（CV）我全部超级喜欢。

说起来，像我这种默默无闻的作家能接下为《果青》写短篇的这个重责大任，起因在于渡老师用LINE轻描淡写地问了句「你要写短篇吗？」。

起初原本说好要用不同的角色当主角写两篇短篇，但我实在无法抑制对平冢老师的心意，便不抱期望地提出请求，结果编辑同意让我写平冢老师的故事。真的感激不尽。

我现在还在担心是否有写出能让同为平冢老师粉的各位读者满意的内容。真想成为那么棒的老师的学生。

若能让平冢老师粉的读者和不是平冢老师粉的读者都能看得开心，是我无上的幸福。谢谢大家。

后记（相乐总）

十几年前，有段时期我常看也常写喜欢的游戏的二次创作。

当时只要稍微对电脑有涉猎的人，都一定会玩过那类型的游戏，它的二次创作比原创小说还要多人看。我也沉浸在那种文化的谎言中。

在本篇没有太多戏分的角色们，也有各自的想法、各自的人生。如今回想起来，我应该是想尽可能靠近没有摊开在阳光下的那部分吧。

话说回来，关于《果然我的青春恋爱喜剧搞错了。》这部作品，我是每集都收了初版的单纯的粉丝。

接获短篇小说集的邀稿时，我的理解是「简单地说，跟二次创作一样」。

但我同时也在想，渡航这位奇才所写的正典以外的作品，会有人想看吗？

既然如此，我必须拿出全力满足各位读者。

我从冰箱里拿出未老的宝刀，把原作有写到的部分和没写到的部分放进同一个锅子里搅拌，洒上名为妄想的调味料，大火炖煮。

成品就是这一篇。

户冢好可爱喔户冢。我会给你幸福的。

后记（天津向）

初次见面。我是GAGAGA文库出版的《クズと天使の二周目生活》的作者天津向。平常还会做搞笑艺人的工作。

我本来就很喜欢果青，看得很开心，这次接获「要不要参加短篇小说集企划？」的邀约时真的感动到不行，一秒答应。不过仔细一想，还有哪些作家参加啊？问了作家阵容后胃就开始痛了。

不是吧，太豪华了吧。

但后悔也没用。我每天早上醒来都会想一千次「早知道不该答应」，可是接获邀约时我因为太兴奋的关系写了三篇企划书，而且还全部过稿了，已经无路可退。另外两篇是以「雪之下雪乃」和「平冢静」为主角，有兴趣可以看看。

请让我说一下写完的感想。我单纯地为角色原来这么会自己行动而感到惊讶。这篇的川崎沙希也比想像中还要有自己的意志，我很快就想好剧情了。创造出这么好写的角色的渡航老师真是怪物。

总之很开心。谢谢大家看到最后。

后记（渡航）

各位好，这是后记。

……后记会不会太多篇了？

我怎么觉得最近一直在写后记，各位过得怎么样呢？我今天也很有精神地在东京神田神保町的小学馆写后记。

我从来没在这么短的间隔内写这么多篇后记，说实话非常不知所措。

可是，写很多后记反过来说就是写了同样多的小说对吧。

再反过来说，为自己写了许多后记而惊讶，代表那人之前是不是太少写小说了？不对，没这回事。我有写。是真的。

再反过来说……不，再反过来说也没意义。请你不要再提起，不然会没完没了。（欧阳菲菲调）

讲出去的话有意义，没讲出去的话有意图，不过，每句话都有言外之意。讲到最后，这个故事大概就是那种感觉。无论是长篇短篇本篇还是短篇小说集。

〈然而，那句话的言外之意另有深意。〉就是这样诞生的。

本篇终于也告一段落，在这边写点有恋爱喜剧味道的东西吧——！毕竟是短篇小说集嘛——！我怀着这种轻松的心情，写得很愉快。

今后我依然会不时想起他们她们的青春恋爱喜剧，想像他们的未来，或回忆他们的过去，之后再将其化为文字。

会有这样的心情，也是因为这个短篇小说集企划很好玩！

大家也开心吗——！还有力气吗——！摇滚区——！二楼的观众——！会场的所有人——！谢谢——！最后面的观众我也看得很清楚喔——！

类似这种感觉，某种意义上来说，这个短篇小说集企划就像拿果青当成舞台的节庆，真的是如同祭典的日子。

老鸟新人前辈后辈大前辈、同期和战友、伙伴与劲敌、王牌四号跟深藏不露的高手、师父老师和命运的宿敌，总之是个all stars通通on parade，等同于睡前妄想的企划。遗憾的是因为时间等因素，有这次不能一起参加的创作者，嗯，就留待下次的机会吧？我个人对这个企划还抱持着许多梦想。

各位读者请务必把《果然我的青春恋爱喜剧搞错了。短篇小说集1 雪乃side》、《果然我的青春恋爱喜剧搞错了。短篇小说集2 ONPARADE》、《果然我的青春恋爱喜剧搞错了。短篇小说集3 结衣side》、《果然我的青春恋爱喜剧搞错了。短篇小说集4 ALLSTARS》都收齐，和我一起乐在其中。

以下是谢辞。

石川博品老师、王雀孙老师、川岸殴鱼老师、境田吉孝老师、相乐总老师、天津向老师。

我一定是全世界最感谢各位的人，所以我想拿出全力传达我的谢意。真的太谢谢了。每次看见各位的大作，我都在感谢遇到您们之前经历过的一切事情‼真的太棒了，总之我先下跪真心感谢再说。

うかみ老师、U35老师、エナミカツミ老师、えれっと老师、ななせめるち老师、ももこ老师。

每次看见您们的图，我都会心想「哦哦，这是剧场版对吧？不愧是allstars，作画太完美了……赞爆……」，跟以贝卡站姿站在摇滚席后方的男友一样。我不敢把脚对着各位睡觉（注29）所以我要一辈子维持贝卡站姿工作。现在我明白了，这份感情名为爱。真的非常感激。全心全意向各位致谢。

ponkan⑧神。

神为何是神？因为神是神。封面的伊吕波真的太神了，我只挤得出这句感想。如果是宗教盛行的时代，我可能会去当宗教家，踏上向世人传教的旅途。一直以来谢谢您！未来也请多多指教！

责编星野大人。

我们做到了！两个月连续出四本书！不愧是您！厉害喔！编辑长！请大家一定要去追踪他的推特！我对小学馆真的只有深深的感谢！谢谢！以后也要麻烦各位了！放心，下次一定能轻松搞定啦！呵哈哈！

GAGAGA编辑部的各位，以及同样提供诸多协助的各家出版社。

都是托各位的福，本企划才能成立。十分感谢各位向各作家、插画家邀稿，协助编纂本书。在此跟于百忙之中抽空参与本企划的您们致上深深的谢意。

以及各位读者。

完结后他们她们的生活依然能继续下去，都是多亏有您们的支持。我也会再努力一阵子。希望未来也能和各位一起享受果青的世界。所以请务必去看看动画！一起欣赏四月开播的「果青完」吧！详情请上官方网站确认！真的非常感激。今后也请多多指教！因为有你，才有果青的存在！

下次让我们在《果然我的青春恋爱喜剧搞错了。》的其他作品中见面吧！

三月某日 喝着MAX咖啡，独自召开短篇小说集庆功宴 渡航

29注  表示感谢之意的日本惯用语。