#+title: 非正文内容
#+HTML_LINK_HOME: /
#+html_link_up: ./index.html
#+setupfile: ../../../setup.setup
#+Author: web

* 萌娘百科的相关介绍
如果正文太描写不直观可以看下
** 主页
《我的青春恋爱物语果然有问题。》（日语：やはり俺の青春ラブコメはまちがっている。；
英文：My Youth Romantic Comedy Is Wrong, As I Expected 或 My Teen Romantic
Comedy SNAFU），+又称我的股市风云果然有问题、白色相簿4、我的白色相簿续作果然有问
题，+简称春物/果青（日语：俺ガイル），是由渡航创作的一部轻小说，并有动画、漫画、
游戏等衍生作品。
*** 原作简介
《我的青春恋爱物语果然有问题。》是日本轻小说家渡航创作、插画师ぽんかん⑧负责插画
的轻小说。2011年由小学馆出版，发行于GAGAGA文库。2015年于SUGOI JAPAN Award
2015“最想向海外介绍的日本流行文化”评选中，荣获轻小说部门首奖。2014-2016年连续
三年蝉联“这本轻小说真厉害！”榜首。(我大春物还能再战500年！) +2017年被加入特别
名单， 不再参与评选。+

2019年11月19日，本篇全14卷完结。至2021年4月20日，另有4卷“X.5”性质的番外篇。

2020年9月25日－2021年2月26日，全6卷的后日谈短篇小说《我的青春恋爱物语果然有问题。
新》随动画第3季BD捆绑发行。

2021年6月，渡航宣布将写作由比滨结衣IF线《我的青春恋爱物语果然有问题。结》。2021
年9月17日开始发售，至今已出2卷。
*** 剧情介绍
别扭的，没有朋友，没有女朋友，对着那些讴歌青春的同学吐槽着“讴歌青春的笨蛋们，都
给我爆炸吧！”的男主角的爱情物语，将来的梦想是成为“家庭主夫”。

这样的高中生比企谷八幡被生活指导老师的带到了学校第一美少女雪之下雪乃所属的“侍奉
部”，与美少女意想不到的相遇……怎么想都是恋爱故事的展开吧！？

但是雪乃却无论如何都无法认同八幡那扭曲的糟糕性格！

不断轮回着的充满问题的青春——我的青春，到底怎么了！？

+真正的现充即使是性格扭曲，晚入学，被孤立了很久很久，他也是能重新成为现充的。本
书就是讲述这一过程的全经过。+
*** 人物简介
【比企谷八幡】

男主角。侍奉部成员，总武高中2年F班。经常说出一些引人深思的言论，再加上《变态王子
与不笑猫》中的老师梗，在三次元被尊称为“大老师”。性情孤僻，对人际关系有着独特而
超脱年龄的见解，被由比滨称谓蹲家。思想看似非常成熟，自认非常了解人际关系的复杂和
险恶，认为人际交往基本上是互相欺骗。由于几乎不与人说话，在班上有着特殊的存在感，
但很少有人记清他的名字，常被叫成Hikitani(正确为Hikigaya)。小学时曾因抽签成为男班
长，和女班长相处得不错，误以为对方对自己抱有好感，结果表白被拒，相近事情发生不只
一次，使其受到了不小的伤害，往后对于女生一些不经意的举动都会在心中提醒自己不要再
被骗了。由于长期不受欢迎，确信“自己不可能遇到理想的女性”。 虽然没有对象(但是有
一个partner（伴侣）和三个喜欢他的人)，但志愿是做“家庭主夫”，本身貌似也有相当的
家务能力，有时也会说希望由妹妹照顾一辈子。按照长相来说，虽然也算是个帅哥，但一双
恶心残念的死鱼眼毁了整个脸，不过戴了眼镜之后基本能够抵消死鱼眼的效果。(最终用
「お前は望んでないかもしれないけど……、俺は关わり续けたいと、思ってる。义务じゃ
なくて、意志の问题だ。……だから、お前の人生歪める权利を俺にくれ」向雪乃踏出了那
一步。) (求婚…)(八幡你个大鲜葱，我拿你当信仰，你拿我当什么（哭)

【雪之下雪乃】

女主角之一。侍奉部部长，总武高中2年J班。十全十美的美少女，偏差值排名全校第一。由
于在各面方天赋都很好所以经常半途而废导致耐力很差。在学校中被女生嫉妒。虽然因为长
相在男生里受欢迎，但由于自己桀骜不驯的性格，所以没有朋友，因此独自创建侍奉部，经
常自己在那看书。大老师被迫加入时，曾对其恶语相向。两人 +打情骂俏+ 斗嘴频繁。拒绝
了大老师要求成为朋友的请求，自称为是他的熟人。被团子 +百合倾向+ 和比企谷小町喜欢，
与叶山隼人曾是同班同学，但由于种种原因与他存在距离。和大老师一样，看不惯人际关系
间的欺骗，但不同于大老师的消极处事，严格地以此律己，事事要求坦承。随故事发展逐渐
展现对大老师的好感，曾在游乐设施上要求大老师拯救她。从小总是追随著姐姐的影子，又
十分依赖大老师（在大老师和雪之下阳乃的讨论中认为两人是比恋爱关系更危险的“共依
存”关系），因此希望自己能够独立做主。非常喜欢猫，延伸至所有猫科动物，只要扯上猫
就会变得非常认真。(最终以「あなたの人生を、私にください」答复大老师。) (大老师求
婚成功！！！！)

【由比滨结衣】

女主角之一。侍奉部成员，总武高中2年F班，大老师的同班同学。由于发型，在三次元被称
为“团子”。样貌和身材都很出色，性格很温柔，但烹饪技能出奇的差，跟现充集团的关系
也很密切。善于观察别人的脸色，并以此来调节小团体的气氛，但在朋友交往中总是过于附
和别人，因此往往不能坦率地表达自己的想法，曾被雪之下雪乃严厉说教过，也因此决定加
入侍奉部。在加入侍奉部以后渐渐能够表达出自己的想法。对大老师有好感，但常常被大老
师拔旗。本身看似不聪明，常常需要大老师或是雪基百科解释英文或日文词汇，却是三人中
最先清楚了解彼此内心的纠结、想法及愿望。(最终对新侍奉部做出了「あたしの好きな人
にね、彼女みたいな感じの人がいるんだけど、それがあたしの一番大事な友达
で……。……でも、これからもずっと仲良くしたいの。どうしたらいいかな？」的委托。)
(白色相簿4名不虚传…)

【一色伊吕波】

总武高中1年C班，大老师的学妹。出场时担任足球部经理，后在大老师的扶植下，出任学生
会长。虽然表面上声称喜欢叶山，却经常跟大老师说一些意味不明的话学长，要负起责任
喔～。可爱的外表下隐藏着腹黑的内心世界，但貌似已经完全被大老师看透。特技是撒娇/
发嗲，以及向大老师发卡。故事后段有越来越常出现在侍奉部的趋势，与雪之下雪乃关系很
好。(最终以“有什么法律规定不能喜欢有女朋友的人？”劝解败犬团子。)

【户冢彩加】

总武高中2年F班，大老师的同班同学。秀吉属性的男性。因为长相和行为比女生还可爱，所
以经常让大老师性取向混乱。是少数跟大老师十分友好的人。总是向大老师寻求帮助，希望
自己也能帮助大老师。(人生有彩加就够了)(大老师真正的初恋www)

** 比企谷八幡
……

大老师虽然孤独，但内心无比自恋，经常会在心理描写自己是一个伟大的人。也会在心中吐
槽自己不会工作的各种原因。

主要原因还是：工作后的大老师：要是我这份工作干不好，我就要回家当靠富婆的小白脸了，
明明当时是我向她先表白的并说扭曲她人生的，现在干不好工作怎么行呢！！！！[fn:1]

大老师发呆的功力无与伦比。最高纪录可以发呆八小时。

大老师 +曾经+ 最期待的事情是和彩加小天使一起洗澡，在小说前6卷曾经在街上偶遇过彩
加于是就产生了每星期都要“偶遇”彩加一次的想法(，然而后来似乎因为有雪乃了因此不
这么想了吗？)。

大老师平常基本在家里蹲（也是团子取的绰号的来源之一）。不想外出的原因之一是不想遇
到旧识而产生尴尬。

大老师发明了集打球，接球，扔球为一体的单人棒球，由此可以看出大老师运动神经其实不
错。

出奇的是，死鱼眼“自爆”大老师其实是一个温柔的绅士，对有困难的人不会漠视，更甚在
帮助学妹的时候被再三误会。

大老师经常在学校和家中列出种姓阶级和金字塔阶级，无论是哪一种，他都会将自己列入最
低那一层。例如：“自家的阶级：卡玛库拉（猫）> (雪乃 >) 小町 > 妈妈 > 爸爸 > 我
（也就是大老师自己）”。

大老师喝咖啡喜欢加炼乳，最喜欢的MAX咖啡是炼乳调味，而且这一点从第一季OVA中也能发
现。

大老师的生日为8月8日(（世界爱猫日）)，跟同为妹控的老乡高坂京介同一天生日。

+大老师的后宫着火着了故事的一半，就是7卷书（一共14卷）。+

大老师在第一集（章）就说“爆炸吧现充”，然后在后续剧情不断自爆(谁是现充一目了然)。

*** if线
从第九卷起的的分支中，大老师与团子在一起了

*** 大老师的由来
大老师的“老师”出自《变态王子与不笑猫》第五卷第一节中的一句话：“小豆梓并不在意
这种氛围，这是因为她本来就已经习惯了吧，我想。真正的孤独是最强的，八幡老师的青春
恋爱喜剧指南书上是这么写的”。而“大”是当时第三四卷的翻译君为了区别平冢静老师和
八幡而加上去的，结果意外的贴切，经过一段时间，就这么定下了。

*** 大老师的“自爆”
所谓“自爆”，便是大老师通过自己来背黑锅的方式来成全他人，即通过不惜破坏自己的周
围关系来帮助他人的做法。原因是大老师自认为自己在学校地位低下，同时也不屑于现充之
间的虚假关系，于是常常“自爆”，但是在帮助海老名后发现这种方法会对在意自己的人产
生非常大的伤害。虽然通常不能解决问题，但用大老师的话来说，“能将问题消除”，“不
把问题当作问题，便不是问题”。+背黑锅我来，送死你去。+

也因为在第八卷中再次学生会选举所造成的一系列问题揽到自己身上独自承担导致与雪之下
雪乃的关系几近决裂，但是也触发自己了对“真物”的思考和探索，最终在第九卷中静老师
的启示下再次与雪乃和结衣和好。


应当指出的是，大老师的“自爆”需要具备包括但不限于以下条件：

1. 具备极强的人类观察能力，对人际关系、社会关系有深刻洞见——鹤见留美被孤立事件
   （起爆点不是大老师但思路类似）

2. 言辞犀利，一针见血，能够起到“杀人诛心”的效果——相模南天台事件

3. 看待问题的角度多样化，可以通过意想不到的方式“消除问题”——学生会选举事件
   （帮助一色有了当会长的意愿，“消除”了委托）

4. 自身的人际关系简单，自己受伤不会过度伤害到关注自己和自己关注的人——必要条件1，
   海老名告白事件（反例）（因此伤害了侍奉部三人组(，当时并没有意识到侍奉部众人是
   “自己想拯救的、不想伤害的人”)）

5. 具备即使牺牲自己也要构建一个“没有人受伤的世界”的坚定信念——必要条件2，车下
   救狗事件

大老师的“自爆”绝非是匹夫之勇，请广大三次元的兄弟们 +尤其是已经有女朋友的+ 理智
使用！！

** 雪之下雪乃
非常喜欢猫，但很害怕狗。很喜欢迪斯尼吉祥物熊猫潘先生，拥有迪斯尼年间通票，乘坐潘
先生的bamboo fight时需要全神贯注，甚至不准其它人出声。因为阳乃在小时候每次去游乐
场时都会戏弄她，所以很害怕过山车等机动游戏， +甚至认为坐过山车会致死+ ，乘坐时要
紧紧地拉着大老师的袖口,结果当场发表“一定要来拯救我哦。”之类的谜之宣言。 +简而
言之就是告白啦。+ (结果他们坐过山车的照片被团子看见。)

……

虽然头上的呆毛在动画第一季不是很醒目(与一缕普通头发类似，较难分辨) 但是一直都有，
但是第二季换了制作公司后有明显向比企谷家族的呆毛发展的态势。(别人夫妻脸，你们夫
妻毛……)
*** 剧中经历
与叶山小时候就认识（幼驯染），但似乎发生了什么而关系不好。雪乃被孤立后叶山以错误
的方式施以援手却导致事态恶化，最后年幼的雪之下请求他停止出手，不知如何是好的叶山
无奈接受……并在之后的多年里一直为自己当初没有贯彻到底而悔恨。

对姐姐有敌视心理，一直想要超过姐姐(，但貌似没有成功的记录)。阳乃曾经说雪乃是“讨
厌我却不想被我讨厌”。

由于在大老师面前弱点完全暴露“完美超人”形象于是荡然无存。 +但是不妨碍两人日常的
对喷（打情骂俏）+ 。

在车祸时认识大老师，但后者来到侍奉部时由于自己的罪恶感谎称不认识他（但文化祭后对
比企谷所说的微妙台词，也可解释为“当时不了解比企谷君，而现在了解了”）。（“知
る”有“认识”的意思，也有“了解”的意思）

后来逐渐喜欢上了大老师(（第9和第10卷扔了一大堆闪光弹，14卷达到最高潮）)，但大老
师及阳乃都认为是“更糟糕的某种东西（依赖共生）”，于小说第十二卷被阳乃点出，但后
来八幡在平冢静的指导下突破盲点，否定了阳乃的认识，两人迈向正确的关系。

在13卷中，雪之下雪乃选择独立面对的舞会(本质上是面对亲妈)问题始终得不到解决，最终
她仍是依赖大老师的弃子 +单挑岳母+ 方案艰难解决。在事后，大老师以自己的方案失败为
由宣称“比企谷八幡已经在与雪之下雪乃的赌约中失败了 +，你可要对比企谷八幡表白和负
责呀～+ 。然而出乎大老师意料的是。雪之下雪乃仍然有着自己是大老师“赝品”的自卑感，
据此得出自己不是大老师所期待的“真物”的结论， +此举使得大老师极度慌乱并一度想试
图改口+ ，最终做出了(扛着百万闪光弹拔flag和)让大老师“请你去实现由比滨同学的愿
望。”的抉择(正妻光环)。

14卷中二人最终认识到自己关于真物的答案——他们在相遇之后给对方的性格与人生都造成
了不可逆转的“扭曲”，相互之间的关系已经远不是阳乃所说的“共依存”能够概括的，相
互的感情也已经远不是用一个简简单单的词语或者是一句话就可以传达的，因而结成了互相
“扭曲”对方人生的关系。 +八幡：请给我扭曲你人生的权利 雪乃：请把你的人生，交给
我吧。（直接订婚？）+ (具体请往下看)

虽然已经和大老师是事实婚姻，不过一色和团子还是会经常来侍奉部试图攻略大老师，然而
自己看似对此没什么意见，实际上得知团子要和大老师说清楚时将本要发出去的命令句，但
顾及关系还是只发了“了解”。当团子借着看宣传册的机会贴在大老师身上时，雪乃立刻发
出了不满的呻吟（把大老师吓的背后发冷），并迅速把座位贴近大老师以宣誓主权。

(果然后面的软萌化是有原因的吗？)


【小说第五卷末尾各人以及大老师对于雪乃的认识】

(大老师转述他人对雪乃的看法，分别作了评价（这是得多了解她），然后对雪乃做了深情
告白，你告诉我怎么输？)

*** 【14卷第7章中决定性的情节转折】

(八幡老师：我能是一开口就告白的那种人吗？我都直接求婚的（雾）)

……

雪之下盯着没出息似地苦笑着的我，最终还是有些犹豫地开了口。

「总觉得…我应该是很麻烦的那种人。」

「我知道。」

「反正肯定会一直给你添很多麻烦……」

「才刚开始不是。」

「还很固执，也不讨人喜欢。」

「嗯，确实。」

「这点我倒是希望你否定的…」

「别闹…」

「继续依赖你…感觉我会变得越来越没用…」

「那我变得更废不就好了。大家都变废不就没有谁是废物了。」

「…就算这样——」

「没事。」

我出声打断还在继续搜寻辞藻字句的雪之下。

「不管有多麻烦都行。有多难搞都无所谓。不如说就是这样才好。」

「……说什么呢…听了完全高兴不起来。」

埋着头的雪之下还在继续轻敲我的胸口。

「疼疼疼…」

当然是完全不疼，不过出于礼仪还是要这么讲。雪之下闹别扭似的撅起嘴。

「还没说完吧？」

「你这人别扭过头真的让人不明所以，我也偶尔会觉得火大。当然这些我觉得都是说不来的
事，毕竟自己是也半斤八两…所以我大概是会一边抱怨一边陪你经历各种事情吧。」

话音刚落，这次她无言地敲了下我的胸口。心甘情愿地挨了这一下，我轻轻接过她纤悉的手。

说真的，能有别的话可说就好了。但我能说的只有这些。要是有什么更简单的话可以传达心
意就好了。要是更单纯的感情就好了。单单是爱慕或者思念什么的想必不会焦躁到这种程度
吧，也不会有“这定是今生唯一一次”的感想吧。

「作为歪曲你人生的报酬来说可能不够…反正，全都给你。不需要的话扔了也没关系。觉得
麻烦那忘了也无所谓。都是我率性而为，你不用回应我也可以。」

雪之下用鼻轻轻应了一声，点点头。

「我会认真回应的。」

接着，雪之下轻轻把额头靠在我的肩头。

「请把你的人生…托付给我。」

「……有点沉重。」

感想脱口而出，雪之下又抗议似地用额头轻轻撞了撞我的肩。

「没办法呀…我又想不到别的说法…」

她像猫一样用额头靠着我，被她紧紧抓住我的衣襟像是有只小猫在轻咬。

想必，千言万语也说不清道不尽的心意，通过彼此触碰的温度，确实地传递出来。


(然后就是雪乃党狂欢呼的时刻)

*** 【读者们等待九年的那一句】

出自14卷 第九章　 その青は、月日に色あせても変わらず青い （那片青蓝，纵然岁月褪
色也不会改变）

……

我露出有些厌烦的表情，雪之下却带着神妙的表情突然朝我走近一步。

「没有，最后还有句不得不说的。」

讲完这句开场白，雪之下稍稍清了清嗓子，视线从我脸上移开。

明明刚刚还那么拽的样子，此刻突然像嘴里打了结，接着又像要解开这个结似地，呼—吸—
呼—吸，胸前的一堆文件资料也被抱得更紧。

雪之下慢慢抬起已经垂到脚边的视线，美丽动人的双眼直直地注视着我。她声音低得像在讲
悄悄话，但清晰无误的字眼一个个从嘴边吐出。

「我喜欢你哦。比企谷君。」あなたが好きよ。比企ヶ谷くん。

毫无防备的突然袭击把我定在原地。雪之下害羞地浮现出腼腆的笑容，接着卷起手上的那堆
文件，啪地遮住自己染上淡红色的脸颊。像要偷看我有什么反应似的，有那么一瞬间，她悄
悄透过面前的文件瞥了我一眼。不过最后又像是受不了此刻的沉默，不紧不慢地朝身后退去。

接着，我要如何回应之类的也不打算等，逃也似地快步飞奔出去。

喂…真的假的。这家伙真的很难搞…

说完就跑那我不就没辙了吗。干嘛啊这是…搞得我也非得重新找个机会说点什么才行呗？这
种是真的难…真的麻烦。

——但是，虽说是麻烦得要死，也可爱得要死。


(全系列近千万字的篇幅里，用来表达男女之情的『好き』的唯一一次使用事例。而这句话
最终留给了虽然无比别扭却又无比直率的女主角，也正因如此，短短几个字在此处胜过某人
翻来覆去的千言万语，弥足珍贵。) (表达男女之情的『好き』在全系列中亦不常见，或者
说是被作者有意回避。但在14卷分别经由静老师、一色、结衣之口说出了数次，该说不愧是
最终卷吗…)

+于是在14卷里面大家连吃了四章高强度无间断的糖。+

*** 【咖啡厅调情片段】

大老师:“抱歉，久等了。”

雪乃:“没事，我也刚来不久，我这边上课时间推后了一点，你也是吗？”

大老师:“我上课时间倒是没变，就是课后了解学习环境和奖学金制度浪费了点时间。”

雪乃:“哦…”笑了起来

大老师:“怎么了？”

雪乃:“没什么，就感觉我们像是两个大学生在聊天。”

大老师:“是吗，哪里像了？”

雪乃:“这个嘛…只是我想象的而已…类似于下课后相约见面之类的，虽然各自上不同的课，
但下课后可以在食堂聊天之类的地方……差不多这样吧。”

大老师:“哦，这样啊…如果上同所大学，确实可以，虽然不太可能……”

雪乃:“都说了，只是想象而已……比企谷同学有时候太现实了吧。而且，还不一定呢，我
们肯定能考进同所学校的。”

大老师:“嗯…反正都一样啊，就算不上同一所大学，也能碰面啊。”

雪乃:“是啊，嗯。前提是你没落榜的话。”

大老师:“这可是我最担心的地方，能不能别这样吓我？”

雪乃:“瞧你这狼狈样，还好意思去问奖学金的事情。”

大老师:“毕竟那是我重要的赚钱手段。”

雪乃:“哦…你之前好像说过。你很缺钱吗？”

（雪乃把眉毛挤成八字形，用湿润的眼眸担忧的看着大老师(就差把钱包掏出来了)）

大老师:（咳嗽）“要是实在没钱了，可以找父母借，问题不大，最不济还可以去打工。”

雪乃:“工作是你最后的选项呢…”（按太阳穴）“要不要去我家打工？应该比普通的工作
要好呦！”

大老师:“哈哈哈，我才不要。”(想着岳母岳父怂了)

雪乃:“这样啊，我还觉得这时机刚好合适呢……”(所以真准备见岳父岳母？？？)

大老师:（害怕了，转移话题）“不过我一开始就没对奖学金抱有多大期望，无所谓啦。我
在乎的是学习环境，位置，设备之类的…”

雪乃:“要不换个补习学校？现在时间也刚刚好…”

大老师:“我也不是对那里有意见，只是想对比一下，至于老师的实力，要上课一年才能判
断，所以只能对比其他方面…”

雪乃:“其他方面…自习室的大小，资料的多少之类的？”

大老师:“也有吧，最好附近有好吃的店…”

雪乃:“补习学校也没想到有人会按照这个择校吧…”（开始嫌弃）

大老师:“（一堆歪理）”

雪乃:“虽然听起来有些荒唐，但是却很有说服力，真让人火大…我还真没考虑过这个。”

大老师:“对吧…”

雪乃:“那我们再去其他的补习学校再看看吧。”

大老师:“嗯？你要去吗？”

雪乃:“你不去吗？”

大老师:“不，我去…”（逐渐开始疑惑）

雪乃:（发现了大老师的疑惑后开始手忙脚乱）“我只是想…想和你上一个补习学校…”

大老师:（害羞了）“那个…上同一所也可以啊…但怎么说呢…最好还是考虑一下符不符合
自己喜好吧…”

雪乃:（开始大胆）“其实我早就想过了，要想维持学习动力，学习环境十分重要，比企谷
同学的这个建议十分中肯，所以我也要重视环境…”

大老师:“哦，这样啊…”

雪乃:（逐渐放开）“所以，关于环境……”（整理语言）“关于环境。当然是一起学习更
有动力……”(她A了上去！)

大老师:（差点丧失理性）“啊，我也想了很多，从结果来看，我们确实可以上同所学校，
应该可以，绝对可以…”

雪乃:“好……好的……就这么办……”

（过了一小会，两人聊了聊给新社长小町的礼物的事）

雪乃:（掏包）“对了，作为庆祝……这个给你……(这是技能前摇，她又A上去了！)”

（雪乃递出了包饼干）

雪乃:“作为庆祝，或者说纪念，但也不是什么重大节日，送太贵重的东西也不合适，于是
纠结了很久……”

大老师:“哦………”（完全什么都没反应过来）

雪乃:“这是……一个月的纪念礼物……虽然有点晚了……”

(什么一个月？确定关系？不对，是结婚吧，一定是结婚吧，如果不是我把民政局搬来可以
吗！)

大老师:“是这样啊…”（突然反应过来）“啊，我什么都没准备…”

雪乃:“你没错，是我擅自要送你礼物的。”(我也想要这样的女朋友…)

大老师:“这样啊，但不管怎么说…”

雪乃:“其实你不用在意的，好吧，那你就到时候补给我吧…”(她又开始了！这是一个脱胎
换骨的雪之下雪乃！)

大老师:（没反应过来）“到时候…啊…嗯…到时候……到时候……一个月的后面还有什么
纪念日，什么时候送比较合适？”

雪乃:“我也不知道呢，随便什么时候都行吧，但是如果非要追求仪式感的话…干脆一年纪
念日之类的？”

大老师:“一年…”（大老师已经不敢想象了）

雪乃:（以为大老师嫌短）“太短了…？那…那十年纪念日怎么样…？”（效果超群，大老
师已经失去理智了）

大老师:“十………”（出窍）

雪乃:“其实随便什么时候都行的，不用太在意啦…”(她终于想起害羞了)

大老师没敢回话，难为情似的抱着头，并表示这场景几十年都忘不掉。(理性还活着吗，喂？
理性？喂？)

——————

渡航执笔的雪乃side短篇中，(在姐姐的搞事攻势下)勉强告知雪父自己和某人交往的事情。
(于是雪父的面前出现了新的敌人。)

特典春物新篇的剧情中，雪乃在雪之下的家庭聚餐中因为比企谷面对雪母“你们在交往吗”
的提问避而不答而感到生气，但后来逼得比企谷在同学聚会上(主动承认恋人关系)并且(要
求与雪乃独处)，误会解除。

「如果你一直不回答(（我们的关系）)，我就会一直问下去的」

「......那，你就问一辈子吧。大概用一辈子的时间就能说出来了」

如果用一辈子的时间，我就能主动说出口。 如果用一辈子的时间，即使是一句话也不能传
达完的心意，也一定能够全部表达清楚。

「好，我会用一生的时间来问你的」

大概我会被她问一辈子吧。 所以，无论到什么时候，我与她的故事都不会结束。

** 由比滨结衣
喜欢用“Ya-hello”打招呼(雪乃险些被带跑偏)，是个外向积极的女孩，即使伤心沮丧时，
也能表露出笑容。

一直表现出天然呆，其实经常将心事深藏，天然呆某种程度上是为了融入现充团体所披上的
外衣。(东山大法好)

料理白痴，亲手做的饼干曾被大老师吐槽为：“根本是JOYFUL本田（日本的家庭用品连锁量
贩店）卖的木炭。”

擅长/爱好卡拉OK，成绩不错，体育爱好者。(当某些人说她蠢时，她总提起自己可是高分考
入总武高的哦)

还“擅长”给周围的人取绰号 +，虽然显然大部分人并不喜欢她给他们起的绰号+ (虽然心
里面很不爽，不过大老师和雪乃也渐渐接受了。)

*** 剧中经历
与大老师同去烟花大会时，(被雪之下阳乃抓奸)归程中表达自己心意的时候(被母亲的电话
打断)被大老师打断。

京都修学旅行中，在大老师于竹林自爆（抢在户部翔之前向海老名姬菜表白从而拯救现充集
团的内部关系）后，强颜欢笑(衣角杀)恳求大老师别再伤害自己和周围的人（动画版中有落
泪镜头）。

此后，在一色伊吕波的会长选举落败委托一事上，侍奉部陷入分裂的危机。为了保住侍奉部
的日常，决心参选学生会会长。但在大老师的计划下成功被止住。

在此后一色提出的圣诞活动委托中，被大老师“寻求真货”的宣言所 +忽悠+ 感动，和雪乃
相拥而泣。(人生苦短，百合吧少女。)

(从11卷封面以及第二季中相应段落，总感觉团子要放手了……然而这是一个错觉)

非常地喜欢雪乃，并希望雪乃能够依靠自己，是她的第一个朋友。

喜欢大老师，时不时对其插旗有所表示，(虽然多次被大老师拔旗。)

+天若有情天亦老，我为团子续一秒+

(渡航老贼丧天良，我与团子共存亡)

【由比滨结衣12卷的独白(团灭)】

眼泪停止住真的是太好了

……

明明眼泪停不住就好了呢。

(还不就是无法传达的爱恋。)

——————

在第14卷中，与大老师在回家路上谈话，对大老师问出了不可模棱两可回答的问题，也使得
大老师确定了这段关系的方向。

【由比滨结衣14卷间章中的泪水】

眼泪没能流出来。

我，我们，第一次真正的恋爱了。

(传达到了还是一枚败犬。)

——————

在十四卷第八章后的间章中，受到一色“再过三年酒后生米煮成熟饭”、“有法律规定不能
喜欢上有女朋友的人吗”、“不放弃是女孩子的特权”的怂恿之后，似乎还保留着“我能反
杀”的念想。

14卷最后决定回到侍奉部，正视三人之间关系，向新侍奉部提出了第一项请求“我喜欢的人
似乎有了女朋友一样的存在，我该怎么和他相处”。

在第14.5卷中，被一色和小町询问为什么不去参观补习学校后直言要等回头直接问大老师，
然后选和大老师一样的补习学校，被小町和一色吐槽是作弊(没想到，雪乃直接和大老师在
参观补习学校的时候把恋爱纪念日给过了，终究还是慢了一步)

(在后续的短篇集中貌似依然没有放弃对大老师的恋心，还在日常地插旗和被拔旗，并逐渐
真妃化。同时还表示要天天到雪乃的公寓来，因为她真的很担心。)

* Footnotes

[fn:1] 找不到出处。。。什么情况？

 
