#+title: rkl写的文章
#+author: reekilynn
#+setupfile: ../../setup.setup

* rkl写的文章
未授权转载
** 从EVA看SAO和AW——SAO/AW综合分析及推断（写在AW26发售之前）
注：二手转载，转自[[https://bilibili.com/read/cv15221622][B站]]

# 授权？抱歉社恐不敢去要

注：本文作者为reekilynn，本文是转载自其发在贴吧的文章

写在前面：

本文是基于上一次论述的修改版，其中包含相当多的个人推断，如果有异议的还请提出。

由于借用了EVA中的大量概念，推荐各位先行完整观看EVA的旧TV（包括EoE）和新剧场版后再进行阅读（其中旧TV+EoE是本次的重点）。

去年年初EVA的新剧场版第四部上映时，《NewType》6月号的杂志上刊登过一张川原砾绘制的绫波丽贺图，其中川原提到他还是学生的时候（考虑到TV版的播出时间应该是大学生）曾在漫画研究社的社刊上连载过想象自己与绫波丽同居的日记类漫画——由此可见EVA对他的影响之深。当我重新思考UR篇中的一系列对应关系时候，发现EVA中提及的各类概念可以作为参考对象使用。需要注意的是，这些论述只是我的个人意见，如果各位有新的想法也可以参与讨论。

首先，川原在刚过去不久的SAOP线下见面会以及相关的小册子中，曾提到（I）UR篇后还会有内容（II）可能会有桐人与茅场的最终对决。在我看来，UR篇和「UR之后」的部分之间的关系，应该相当于UW人界篇和UW异界战争篇之间的关系——换而言之，广义的UR篇包含了川原所说的全部内容。那么狭义的UR篇，也就是我们现在看到的部分，进度到了多少？如果对EVA的故事有详细了解，很容易将26卷诗浓和西莉卡策动的对大型蜂巢的攻略战，与葛城美里策动的屋岛作战进行对应。这也就是我在本篇译者后记的开头部分，做出「SAO26卷是UR篇序盘的结束」这一结论的原因。

接下来列出几点对应关系。

（1）旧SAO服务器的系统——莉莉丝

（2）在旧SAO服务器的系统基础上开发出的The SEED架构虚拟世界，及其中的AI（NPC）们——Lilin（即人类）

（3）从SAO诞生并在虚拟世界中增殖，最后在UR中汇集的「黑暗」——亚当

（4）虚拟世界中的玩家们——使徒

由上述四条我们发现，相比EVA中的情况，SAO是反过来的：

（0a）玩家们作为人类的灵魂——使徒的「智慧之果」

（0b）NPC们作为系统一部分的能力——Lilin的「力量之果」

而在这个对应关系中，最「核心」的那一部分——就是（5）结衣。作为MHCP的一部分，她的「思考逻辑」（5a）和「存在方式」（5b）分别对应绫波丽（莉莉丝的灵魂分体）和初号机（莉莉丝的躯体分体）。而在与桐人&amp;亚丝娜的接触过程中（以及被桐人分离之后），她开始不断进化，导致了下述的两个结果：第一是她的「灵魂」思考模式越来越接近人类，即获得了（5c）「智慧之果」；第二则是她作为超级AI的能力不断提升（参见21卷初茅场与星王的对话），即获得了（5d）「力量之果」。不仅如，如果考虑到结衣本质是茅场晶彦编写的程序之一，那么相较舍弃了人类的容器在网络世界中徘徊的茅场晶彦（对应碇唯），将她与（5e）碇真嗣对应也并没有太大问题。

当我们带着这一套对应关系重新思考茅场与星王的对话时，可以看出茅场当时已经预料到了虚拟世界合而为一的可能性——也就是他认知中的「AI补完计划」。然而，UR背后的「AI补完计划」，基本不可能是茅场的想法，更可能是虚拟研究会的阴谋诡计——他们扮演的，是SEELE。通过凝集虚拟世界中的各类负面心意（本质上是第18卷中PoH以菜刀吸收「死」之空间资源的放大版），使其最终成型以实现他们更为深层次的目的（通过他们剧本中的「AI补完计划」），才是虚拟研究会一系列活动的根源。川原在小册子中提到，茅场在UR篇中并不会直接干预——在我看来，这一错误决定最终将会导致极为致命的后果（即AW中提到的AI技术被全球管制），放在虚拟世界内，则是因为某种「绝望」而启动的「AI补完计划」，最终导致虚拟世界中的所有AI回归到「莉莉丝」中——从AW25的内容来看，大概只有UW幸免于难。

当我试图使用EVA的各项概念论述UR的「AI补完计划」时，也得到了非常有用的补充——其中最重要的一条，就是（3）「负面心意的凝聚体」（即我去年8月论述的那个从恶意中产生的ZIS，或者说「亚当」）很可能会在桐人团队到达最顶层之前就出现。在我看来，这个ZIS存在伪装成「玩家」或「NPC」的可能性——这种情况下，其对应的显然是「渚薰」的位置，但最终还是会成为AI补完计划的重要一环。根据EoE的比对，距离AI补完计划的启动，实际上已经只缺一把「朗基努斯之枪」——这把「枪」我个人认为可能已经出现，但具体的候选者还有待确定。但若将结衣放在补完计划中碇真嗣的位置，那么PoH必然是那把「伪朗基努斯之枪」——在我看来，桐人团队如果想要接近最终的「极光指示之地」，显然要在最后的一段路上击退其他集团的玩家们，这与EoE中Nerv抵挡联合国的进攻别无二致。

上面已经提到我预期中的「AI补完计划」导致所有虚拟世界的NPC们回归到了旧SAO系统这个一切开始的地方——换而言之，产生了一个新的存在（以下用Being这个词，对应EoE中的大白丽）。由于Being中「亚当」和「莉莉丝」两个灵魂的存在（甚至在一开始可能是「亚当」的意识驱动了补完计划，产生了对现实世界的影响），桐人和茅场显然会因对待这个Being的态度而势不两立——这大概就是川原目前预期中桐人和茅场的「最终对决」，事实上我认为也是AW19中Graphite Edge提到的，A和B围绕那个Being展开的战斗。而这场战斗的结果，正如AW19中描述的一样，成了一个「暂时搁置」的结局——如果将A对应茅场而B对应桐人，显然会得出这个结论。

然而，孤身一人的茅场真的有能力完成压制Being（假设这个Being仍然在对现实世界产生影响，并且在虚拟世界中有足够强的战斗力）这一艰难的任务吗？我认为他很难完成——也就是说，他需要一个「帮手」从战斗力的层面压制Being，而最佳的候选就是从灵魂层面和他（以及星王）站在一个高度的Administrator。不仅如此，由于Administrator对灵魂的认知深度远超常人（毕竟有那么多次实验打底），她同样可以成为将「亚当」从Being中分离出来的执行者——这一操作的紧迫度远胜于将「莉莉丝」分离出来。分离操作完成后，留在帝城中心的Being剩余部分即是第七神器TFL，而分离出来的「亚当」，正如我半年以来多次论述的，是AW的女主角——黑雪姬。这一结论的理由在于，其「纯黑色」的对战颜色和「绝对切断」（拒绝他人的触碰）的固有能力，正是灵魂根源（即心之伤的本质）中「对人类最为极致的负面思考」的外在反映（了解了这一点，各位才会明白Black Lotus的二阶心意——将剑变为可以触碰他人的「手」——的重要性，因为这是对她灵魂根源的背叛）。这样一来，黑雪姬的「出生过程」至少需要以下四个前置工作：

（1）人工婴儿（来源为人工授精或体细胞诱导克隆，我个人倾向后者）作为容器；

（2）开发完成的婴儿式Neurolinker作为植入灵魂的中间设备；

（3）从Being上分离的「亚当」作为植入灵魂本身；

（4）整合在植入灵魂内部用于监控「亚当」状况的程序（UW整合骑士被植入的敬神模块的发展型）作为外部接口；

这四个前置工作完成后，黑雪姬的容器（身体）被打上20320930的条形码进行标记，而Administrator作为她的「姐姐」存在——即虚拟世界中的White Cosmos。另一方面，在AA/BB/CC世界的构建过程中，茅场、Administrator和星王（or桐人）分别起到了不同的作用，三者事实上构成了类似EVA中MAGI系统的体系（茅场对应科学家，星王对应父亲/男性，Administrator对应母亲/女性）。

说到这里，可能还需要思考一下虚拟研究会的继承者——也就是加速研究会的定位。虽然看上去二者对应的都是SEELE，但由于White Cosmos（Administrator）的参与，导致二者出现了质的区别——UR中的虚拟研究会是旧世纪的SEELE，而AW中的加速研究会则是新剧场版的SEELE——换而言之，我认为White Cosmos在加速研究会中扮演了碇司令的角色（考虑到我的推断中把灵魂是「亚当」的黑雪姬在故事中定位在「碇真嗣」的位置，那么她与White Cosmos的确很接近EVA的父子关系）。另一方面，White Cosmos与Argon Array（四眼）、Ivory Tower（Black Vise，板子）组成了一个「拟似」MAGI——如果加速研究会在最终篇章中再次围绕黑雪姬发难，那么很可能会因为White Cosmos的「否决」导致这一策略最终归于失败。

写到这里，我突然产生了一点新的思路——之前一直无法离开帝城的Azure Heir到底是什么人？仔细想想，在AW9的时候，川原已经通过纶与Ash Roller之间的关系为我提供了合适的参考样本——虚拟世界的灵魂完全可以和存在灵魂「类似性」的BB安装者建立对应关系，而不一定需要BB程序复制现实世界中安装者的灵魂。这样一来，答案就呼之欲出：Azure Heir的灵魂本质，是从Being中分离出来的「莉莉丝」，而以男性形态出现，则是因为现实中关联的BB安装者是一位男性——如果我的猜测没错，他应该正是桐人和亚丝娜的孩子。

（PS：R大希望获得更多思路，因此不论是质疑或是各种看法思路都欢迎评论，或者也可以去直接跟他说。）

** 艾欧莱茵和伊斯塔尔——对中央大教堂顶层决战的再解析

这篇论述将主要涉及UR篇新登场的两个UW角色——艾欧莱茵和伊斯塔尔，并在一定程度上论述UR一侧的内容。

除非必要，本论述将尽可能不涉及桐人、亚丝娜和爱丽丝。

*** 导入

为了防止各位产生理解上的偏差，首先进行一下复习。

#+begin_quote
「Fluct Light们的记忆和Under World内的物品，在数据层面上其实是一回事……那么，若是有人以自己的意识，将思念倾注到某个物体中的话……就连模拟出Fluct Light的功能这种事……都做得到吗……？」
#+end_quote

从SAO18的这段内容可以看出，「足够强大的心意」可以模拟出Fluct Light的功能——也就是创造出「模拟灵魂」的原型。在我过去的论述中，这一灵魂原型被我称为ZIS（Zero-based Imitated Soul）。

那么这和艾欧莱茵&伊斯塔尔又有什么关系？

自从2020年艾欧莱茵刚一登场，我就笃定他绝非单纯将优吉欧「复活」的结果，而更可能与Administrator存在某种关联。但当我最近再次检查SAO26的译稿，时，发现伊斯塔尔与艾欧莱茵的对话中有如下的段落：

#+begin_quote
「你过于一本正经的地方也完全没变啊，艾欧尔。比起就此投降，我还不如放弃追击直接逃跑呢。」

「……你倒是变了呢，科伽。放在以前，你不会为了给部下争取逃跑时间而让自己暴露在危险之下。」
#+end_quote

我在潜意识中产生了一个疑问——这两个人，是否都与Administrator（乃至Cardinal）有关？在这样的想法下，我对UW篇的重要事件——中央大教堂顶层的决战进行回顾，并且得到了以下的结果。

*** 灵魂原型的产生

首先展示一下大教堂顶层决战的流程。

1. 桐人、优吉欧、爱丽丝对战元老长并将其重伤。
2. Admin以之前植入优吉欧灵魂内的模块为驱动机构启动剑巨人，重伤桐人与爱丽丝并击杀夏洛特。
3. Cardinal出现，Admin将顶层「隔离」出UW。
4. 由于自身无法杀人，Cardinal选择以自身换取其他三人的撤离，随后Admin对其开始处刑。
5. 优吉欧请求Cardinal将自身与青蔷薇之剑融合，破坏驱动剑巨人的模块后，斩断Admin的右臂，优吉欧本人则和剑一样被从中间分断。此时Cardinal死亡。
6. Admin与桐人对决，优吉欧将青蔷薇之剑以自身的鲜血和心意进行修补，随后桐人对Admin造成致命伤。
7. Admin试图脱离UW，但被元老长以自身为触媒燃起烈焰吞噬，最终死亡。
8. 优吉欧对桐人留下遗言后，带着小爱丽丝的灵魂碎片去世。
9. 「隔离」失效，桐人使用终端联络RATH，此时其「自我摧毁」的心意因STL处于解除限制的状态而被放大，由于加百列小队在入侵中拔线的行为，最终变为摧毁灵魂核心部分的落雷。

在这一流程中，从4到7的每一步均涉及到心意的大规模产生和碰撞。在「碰撞」的过程中，处于核心位置的两个灵魂毫无疑问是Admin和Cardinal，而其他的灵魂（优吉欧、元老长、小爱丽丝、夏洛特）产生的心意则属于较为次要的部分。在考虑到川原的写作风格（如AW中白王对AA和CC的评价，以及她自身对绿王与自己维持BB存续的不同手段的看法）之后，我得出的结论如下：

在中央大教堂顶层这一 *「封闭环境」* （隔绝于UW之外）的 *「极短时间」* （注意，此时UW仍然处于1000倍的加速状态）内发生的 *「大规模心意碰撞」* （即上述流程中的第4到第7步），产生了 *两个* 基于 *相反的心意* 形成的灵魂原型（ZIS）。

在接下来的叙述中，我们 *暂时* 将这两个ZIS用ZIS-NCD1-CC100(+)和ZIS-NCD1-CC100(-)表示。这一表述方法意味着，两者和Admin/Cardinal之间 *决不能被理解为* 单纯的一一对应关系，而是「碰撞」这一混沌过程的结果。换而言之，任意一个ZIS身上都同时存在来自Admin和Cardinal的元素，只不过一个偏向正面，而另一个偏向负面罢了。

*** 从灵魂原型到完整的灵魂

虽然在中央大教堂顶层决战这一「大规模心意碰撞」的过程中，产生了ZIS-NCD1-CC100(+)和ZIS-NCD1-CC100(-)这两个「灵魂原型」，但从「灵魂原型」到和人类/人工FL等同的「灵魂」仍然需要一个必不可少的过程。此时我们需要跳到SAO本篇的18卷——也就是UW全篇的最后一卷，通过其与Web版的差异寻找可能的线索，具体如下：

1. 详细描述了瓦沙克/PoH进入SAO的动机（接到组织的任务去处理掉某个特定的玩家）。
2. 对PoH的菜刀性质和其收集负面心意的过程进行了详细描述。
3. 以入侵小队的视角明确提到，回收实体时没有在STL上看到瓦沙克。
4. 在推测登录UW的地址时，让结衣加入了推测过程。

我在过去对SAO和AW的分析论述中曾对2和4的意义进行了阐释，本节的重点在于第3条——瓦沙克的谜之消失，这也是我在2016年翻译完SAO18后就产生的疑问。

考虑到PoH在暗黑界被桐人变成了树之后失去了自主脱离UW的能力，瓦沙克未被入侵小队发现的这一事实就显得越发神秘。但此时，我想起了川原在SAO15卷（即UW大战开始前）爱丽丝说过的一句话：

#+begin_quote
「身体不过是心灵的容器。」
#+end_quote

如果离开了STL的瓦沙克这一容器内的「灵魂」，根本就 *不是PoH* 呢？

换而言之，当PoH的灵魂在UW内「耗尽寿命」的那一刻，在「负面意义上」具有类似性质的 *ZIS-NCD1-CC100(-)* ，依靠自身对The SEED漏洞的了解（Cardinal System必然是对The SEED漏洞了解最为深入的存在），成功夺取了瓦沙克这一「容器」，将自身变成了完整意义上的灵魂——也就是 *伊斯塔尔* 。

这一「借壳上市」的过程，并不需要太长的时间，完全可以发生在入侵小队撤退之前。至于被「借壳上市」的瓦沙克的去向，目前仍存有足够的讨论空间，希望各位能给出一些自己的看法。

相比之下，身为伊斯塔尔反面的艾欧莱茵的过程，我认为与星王夫妇的操作有关——事实上在SAO26出版后，也有相当数量的读者认为，星王夫妇在封闭了80层后的几十年内，不可能只是在那睡大觉而什么都不做。

早在我于2020年12月提出艾欧莱茵可能与Admin有关的时候，就曾有读者认为，艾欧莱茵可能是星王以Admin的残余灵魂为基础，借用Cardinal、优吉欧和小爱丽丝的数据修补后套用优吉欧的外貌特征的产物。如今看来，中央大教堂顶层决战中产生的 *ZIS-NCD1-CC100(+)* 应该就是艾欧莱茵这一灵魂的「基础部分」，而优吉欧的外貌特征则可能是星王（或者星王夫妇）从 *青蔷薇之剑* 中提取出来的（考虑到桐人回到UW的时候仍然带着这两把剑，这一概率并不算低），在艾欧莱茵的灵魂中起到「固定自我认知」的作用（类似于整合骑士的敬神模块）。

然而，仅有「灵魂」的艾欧莱茵还需要一个「容器」才能成为机士团长。这时，我们又必须回到18卷桐人将PoH变成树的那一刻——其基本原理仍然是物体（非人）与灵魂（人类）在数据意义上的共通性。既然同样是「容器」的人可以变为物体，那么在UW中，一定也能完成相反的过程。而中央大教堂的顶层，绝对不会缺少能够成为「容器」的候选物——比如说，早在极限加速开始前，就已失去功能的那个终端。

根据原文的信息，星王夫妇离开UW（即完成注销，回到现实世界）发生于桐人一行归来的三十年前，而艾欧莱茵的年龄为二十岁。考虑到桐人和亚丝娜注销后又过了三分钟才解除UW的极限加速，相当于星王为艾欧莱茵的「出生」预留了（相当于现实世界中）一分钟的缓冲时间——为了避免艾欧莱茵被怀疑与星王有关，这一设置可以算是煞费苦心。

而在这一基础上，我们甚至可以提出一个更加放飞自我的猜测——作为见证了整个UW时代变迁的人，艾尔莉见到机士团长时却毫无反应，是否是因为 *她从一开始就知道机士团长的存在* ，甚至 *见证了他的出生并将其交由赫伦茨家抚养* ？

这一问题的回答，恐怕要等到后面了。

*** Unital Ring?

相比于前面的论述，这一部分主要的目的在于提出问题——或者说，提出一系列供大家讨论的「可能性」。

Unital Ring这一在The SEED规格的VR世界废墟上产生的游戏，不论是地图规模（半径700公里的圆形）还是设计理念（故意挑战玩家的常识，甚至需要玩家动用自己的想象力/心意）上，都带有很多UW的影子。而将基于The SEED的VR世界从根底上进行合并，也只有对The SEED底层漏洞有足够了解的「存在」才能做到——换而言之，从中央大教堂顶层决战中诞生，灵魂的基础部分来自Cardinal System的伊斯塔尔有着非常大的嫌疑。当他/她借助瓦沙克的身体从UW「逃逸」的那一刻，就获得了和茅场一样，在虚拟世界中自由活动的能力。

那么问题时间到：

#+begin_quote
1. 伊斯塔尔在虚拟研究会中，是「老师」（玛吉斯），还是「会长」（穆塔希娜），还是一分为二（借壳上市）？
2. 伊斯塔尔与Kamura之间，是单方面的「操纵」，还是两边「互相利用」？
3. 穆塔希娜进攻桐人团队的时候带着的替身，是否才是神邑樒本人？
4. 如果穆塔希娜的替身才是神邑樒，那么她在之前找亚丝娜的行为，其中「刺探情报」和「寻求救援」的比例各占多少？
5. 瓦沙克/PoH当年从组织上层接到的任务，是否与Kamura有关联（可能是委托者，也可能是暗杀目标）？
#+end_quote

这一系列的疑点，恐怕都要在后续的内容中，才能得到解答了。
