#+title: re0 怠惰if 从零开始私奔的异世界生活
#+setupfile: ./setup.setup

* 怠惰if 从零开始私奔的异世界生活

作者

長月達平

插画

来自网络

译者

不愿透露姓名的翻译组


制作信息

≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

作者：长月达平

插画：来自网络

译者：不愿透露姓名的翻译组

出资：逗你玩hey

制作与美工：蝎

≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

** 简介

分歧点:

昂是否会抛弃一切，选择与雷姆私奔。


————--

作者的话：

每年惯例的愚人节企划！ 并非本篇而是IF世界的故事！

本文为《Re：从零开始的异世界生活》分歧点后的内容，读者敬请注意。
此外，本故事发生在正篇内容截然不同的世界，角色之间的关系性也有巨大的变化，还望理解。
能在接受上述预警的基础上愉快阅读的人，请自由往下。

** 启程
——客车车厢内弥漫着沉闷凝重的气氛。

「————」

究其原因，并非是气氛紧张亦或是警戒着什么，不过是单纯的不融洽罢了。这股不融洽的感觉遍及全身，少女微微将身上的毯子裹得更紧了一些。拉车的不是地龙而是大型狮虎兽，安全措施一概没有。简陋的车厢晃得厉害，发出阵阵声响。尽管这样的环境说不上有多好，无奈自身的立场所迫，也只得忍忍了。

「————」

盘缠也有些吃紧。起初因罪恶感而犹豫了半天的手上的金币，为了生计也不得不用掉了。然而，只要资金短缺这一根本问题无法得到解决，即使解得了燃眉之急也无济于事。何况与之相比，还有更加棘手的问题。

那就是——「你的伴侣，噩梦缠身了呀汪」

狭小的车厢中，缩在角落里的少女被人冷不丁地说上这么一句。顺着视线看去，在一旁的是一个矮小的——不，无比娇小的人影。体格近似幼童，又或者更小。雪白的毛发中是一张可爱的小狗的脸——那是一只犬妖。

「我知道你在警惕我汪，我并没有恶意汪，只是有点好奇而已哦汪。」

「让您费心了。不过」

少女坐直了身子，同时也因对方的态度而卸下戒备。犬妖的话多半是出于好意。然而，就像是要让这份好意付之东流一般，少女的心「强硬」了起来。不强势起来的话就只会堕落下去，那才可怕。

「好像玻璃一样呢汪」

「玻璃吗？？？」

「玻璃虽然很硬，但也易碎汪。此时此刻你们的心，仿佛玻璃一样哦汪。」

的确，人心犹如玻璃。正如犬妖说的那句「你们」那样，少女并非独自一人。在她身旁，一位裹着毛毯靠坐着的黑发少年正酣睡着。少年挨着少女的肩，两人依偎取暖。而这位少年，正是车厢内气氛沉闷的原因所在。

「抱歉，对不起。是我太弱小了，所以，全部？？」

「————」

从做着噩梦的少年口中时不时会冒出一些惭愧之念。对于那好比是背负起了全世界罪恶一般的声音和泪水，其他乘客不知所措地僵在座位上。因而这只犬妖能上前向两人搭话实属勇气可嘉。

「看你们这身打扮？？是私奔还是别的什么呀汪？」

「别人的事情问得那么起劲？？」

「现在草木皆兵也是无可奈何汪。尽管如此，有些事情还是要去做的汪」

犬妖抱臂低下头，就像一团白色的毛球。白色毛团一副心知肚明的语气令少女略显焦躁起来。但她不能引起骚动，也不想这么做。见少女内心纠结，犬妖将手伸进戴着的帽中，并取出一样东西。随后在那东西上面唰唰地写了些什么，

「你拿着这个，上巴南街就行了汪。我朋友会照顾你们的汪」

「？？为什么要做这种事？」

犬妖的话语包含善意。递过来的纸条中写有地点和人名。刚刚添上去的是这只犬妖的名字吗？它这么做的目的不得而知。

「这不明摆着的嘛汪」

面对少女的疑问，犬妖笑着回道。

「只要有人遇到困难我就会出手相助。何况对象是两个孩子的话，作为大人的我就更应如此了汪。‘缘广良缘多'，这正是本汪信奉的卡拉拉奇流哦汪」

听了犬妖温暖的话语，少女将纸条紧紧攥在手里。随后她弯起膝盖，头侧靠在身旁少年的肩上，发出了啜泣般的声音。犬妖则用温柔的目光注视着少年和少女，轻抚他们的头。

** 第一章 『两个月』

1

\\

——卡拉拉奇城邦是西方的一个大国，与北部的古斯提科圣王国、南部的博拉奇亚帝国以及东部的鲁格尼卡王国并称为四大王国。但其建国历程同其他三国相比要来的独特得多。

卡拉拉奇城邦的历史远不及其他三国悠久。直到近几百年前西方还是个小国遍地，国与国之间群雄割据的危险地带。

而将这些小国家统合成一个整体的正是卡拉拉奇城邦。

把众小国的国名改为都城名，治理权交由各个都城的都城长旗下的议会。最终决定权则在都城长们一致选出的“大总领”手中。

这样的大背景下，扎根于卡拉拉奇人民心头的价值观，是与其他国家截然不同的。不仅是政治领域，卡拉拉奇在国民性乃至文化领域方面也有着自己的独到之处。

和风文化与和风穿着就是很好的例子。而说到最有特点的——

“对不住了啊蕾姆，事儿没成。咱尽力了，咱就是一……”

纯正的卡拉拉奇口音——即使是在文化特色浓郁的卡拉拉奇城邦，这样的口音也叫人十分好懂。而说话的是一个把脑袋贴着地板，磕头谢罪的家伙。

那是一位有着严重三白眼的黑发少年。此刻的他身着藏青色和服装束，正跪坐在铺有榻榻米的房间里，脸上写满了惭愧。

——菜月昴，这是他的名字。

从生硬的卡拉拉奇口音不难听出，他不是本地人。说到底，菜月昴并非这个世界的人。他从异世界被召唤而来，经历了各种各样的事，并最终来到了卡拉拉奇。——仅此而已。

坐在菜月昴对面的少女原谅了他。听完昴的谢罪之言，她莞尔一笑道：

“这语气一点儿都不像你呢，昴君。”

“啥？你说不像咱？”

“客气点讲，我挺讨厌这语气的。”

“这算哪门子客气咧？！啊，失礼了。我知道了，立马改。”

在这份笑容的“逼迫”下，菜月昴不情愿地收起自己蹩脚的卡拉拉奇口音。然而嘟起的嘴角与手指交叉所发出的声响似乎仍在悄悄抗议。

“我是说得不地道啦，可俗话说得好入乡随俗嘛。为了能尽早适应这里的生活，我也得努力啊”

“昴君是个了不起的人，有许多地方值得蕾姆学习。不过昴君的卡拉拉奇口音……该怎么说好呢，好比一个非本地人在恶搞卡拉拉奇口音一样，让人有股莫名的焦躁感。”

“就像是东京人操着一口夹生的关西腔令关西人听了火大的感觉吗？！”

“冬晶？观溪人？”

这番回答令菜月昴哑然叹息起来。而少女则不解地歪起脑袋，一头蓝发随之摆动。

少女的瞳色与齐肩的长发一样碧蓝。可爱温柔的气质与水色和服相得益彰，令人赏心悦目。


少女的名字叫蕾姆。准确来说是菜月·蕾姆才对。从刚才的对话来看，她与同样姓菜月的昴一定不会是兄妹亦或亲戚关系，多半有着其他联系。

“不过我觉得吧，事情搞砸和口音问题是两码事啊。前者只是我单纯能力不足……”

“事情搞砸了？能具体说说吗？”

“咕……呜呜呜，这个嘛。”

蕾姆一针见血地向昴发问，容不得他有半点狡辩之辞。昴绞尽脑汁地思考着该如何回答，口中含含糊糊起来。

见昴如此纠结，蕾姆柔和地笑了笑，

“有什么你就快说嘛。没事的，蕾姆我很清楚昴君有多么地废柴，所以就算昴君废柴到完全干不动力气活我也绝对不会生气的。”

“我就是如此废柴了啦！”

昴拗不过蕾姆，面对委婉的嘲讽他一下躺倒在地，随后转身侧卧，发泄似地扣起榻榻米来。

“我太天真了，天真到无可救药的地步。理所当然地以为这份活儿就像临时工一样，招的人多，干起来不会有什么难度……”

“喔，那实际是怎样的？”

“说到底！亚人在卡拉拉奇怎么也挺吃香的吧，居然让我这种弱鸡体质的人拼命干力气活！我想少搬几次每次多搬一点，没想到一次要搬三倍的量，身体怎么吃得消？！”

回想起上午所发生的不幸境遇，昴声嘶力竭道。

在异世界生活已不止一年的昴深感自己比以前坚强了不少，然而体质上的差距却难以填补。

顺带一提，今天的工作是运货。而混在亚人中，出不了多少力气，尴尬地红着脸浑水摸鱼的昴，看上去是如此滑稽。

“原来如此……那有什么问题吗？出什么岔子了？”

“返回途中我不小心把货给弄翻了……今天赚的钱全拿去充公了。”

“……没叫你赔偿已经算好的了。”

运货袋中装的是盐，少部分没撒掉，大部分盐同地上的沙子混在了一起无法回收。最终原定的安排只得中止，打道回府。

见昴说着说着脸上阴沉了下来，蕾姆小声叹了口气。

“事情进展得不太顺利呢，昴君。”

“被你这么一说更伤了……话说回来，蕾姆今天怎么了？这个时间还在家里，工作呢？”

“今天学堂放假，有一种感冒好像孩子们之间传播开了。我今早在你出门前不是告诉过你了嘛……
把别人的话当耳旁风可不行哦，昴君。”

“唔……”

面对蕾姆咄咄逼人的目光，昴惭愧地支支吾吾起来。

就像刚才昴所交代的力气活的失利那样，他没有一份正经的工作，确切地说，是有工作意愿但无法胜任它们。

相比昴的窘迫遭遇，蕾姆则要顺利得多。她找了一份在“学堂”手执教鞭管理孩子们的工作。

掌握了这个世界的基础知识、算术、礼仪等各项技能的蕾姆可是颇为抢手，工作机会从未少过。

两人日子过得清贫但也还凑合，毫不夸张地说，这全靠蕾姆一人维系。论贡献，和某人真是有着天壤之别。

昴本人对此也心知肚明，因而他十分焦急，对于这次失利的反省也格外深刻，充满自责感。

“可恶，又给你添麻烦了，蕾姆。”

“不是说好不许道歉的嘛，昴君。”

“那个，话是这么说，可正因为如此我才感到自己好没用啊。”

打着滚的昴盘坐了起来，不甘心地咬着嘴唇。

蕾姆大受欢迎，深受周围人喜爱这点，昴也感到很自豪。然而认同和依赖是两码事，何况当下——想要和蕾姆相互扶持生活下去的不是别人，正是昴自己。

就算这个想法是错误的，也完全没有理由依赖蕾姆，让她独自支撑起这个家。

“没事的，不要有那么大的压力。周围的人迟早会发现昴君的优秀之处的。现在只是还没找到适合昴君这样大度的人的工作罢了。所以尽管找吧，钱的话我来挣！”

“所以说，那样我不就成了吃软饭的了嘛！”

“诶，昴君？！”

对于蕾姆像是包养宣言一般的回答，昴奋起激辩。随后留下受到惊吓的蕾姆，独自一人跑出了屋子。

接着——

“——等着吧蕾姆！我一定会找到工作的！你得由我来养活！”

“嗯呢。记得要在晚饭前回来哦。”

“可恶！我绝对会挣钱养你的——！！”

昴眼含泪水，在蕾姆的挥手目送下冲出家门。

拖着一双草屐，消失在了卡拉拉奇的街道尽头。

谋职——纵使是在异世界，没有任何执照和工作经历的人要想找到一份工作也是极为困难的。

2

——这里是卡拉拉奇城邦的第二大城市“巴南”。

地处卡拉拉奇城邦以西方向的巴南市，其规模仅次于第一大城市“奇翁”，是昴和蕾姆这对菜月夫妇的现居地。

街道的样式仿照了卡拉拉奇和风文化的建筑风格修建而成，因此也有传闻称巴南是卡拉拉奇和风建筑风格的发祥地。但依昴看来，这样的和风建筑与异世界的格调总有些不太相称。

这样的街道，与其说是异世界的风格，不如说更像是——

““完全就是江户时代，或者往近了说，明治大正时代的既视感啊。”

昴口中所述的那一栋栋木质结构平房，如今正整齐罗列在眼前。而将店门敞开迎客也是这些和风建筑的一大亮点。

来往的行人脚穿鞋履，身着和服，却都是异世界的居民们。其中不乏以兽人为代表的亚人。它们不论毛发还是脸型都超出了昴的认知范围。

日本文化被强行塞入了异世界之中——这是昴对于卡拉拉奇风俗的印象，就连与关西腔酷似的卡拉拉奇口音也不例外。

“简直就是让幻想世界的人物进行cosplay的感觉啊。不过大家都很有资质，完全没有违和感就是了。”

说起来，幻想世界里有日本文化的影子本就是漫画或者游戏的惯用套路。只不过如今真见识到了那种场景，违和感比想象的要大。昴历经近一年时间才适应过来。

尽管如此，也难免会抱有疑问。

很难想象卡拉拉奇的文化是靠自身发展而来的。如今的卡拉拉奇文化得以广泛传播定是出自和昴有着相同故乡的人之手。

就是说，那个头戴铁盔的男人阿尔迪巴兰也是从异世界被——，

“不去多想了，还是想处理好眼前的问题吧。就算解开了这个世界的谜团，我也仍旧是个无业人员。啊，这种话由自己说出来真是逊爆了……”

至于这个世界的历史和昴以及与自己同乡的人三者之间究竟有何关联，还是等生活安定下来之后再做思考的好。

当务之急是找份工作，偏偏还得赶在晚饭前搞定。

“一到下午时间就过得飞快……！总之先去职业介绍所碰碰运气……”

“——哦呀，是昴啊。怎么一脸不快地上街呢？表情好吓人耶！”

“你这样对一脸认真的人说话很失礼啊……啊咧？”

一句不太友好的吐槽钻入了眉头紧皱着走在街上的昴耳中。他转过头去，只见说话的是身旁一位高个子的家伙，那是一张似曾相识的脸。

“这狗脸，这不是阿赫嘛！不要吓我啦！”

“别狗脸狗脸地叫我啊。我可是犬人族的狼人。”

听完昴的话，长着狗头，啊不，狼面的亚人张开大口笑道。只见这个大块头嘴里叼着烟斗，漆黑的毛发外裹着一身黑色和服。与一般的矮个儿犬人不同的是，这只自称是狼人的，高昴一个身头的家伙颇具信赖感。然而，一双眸子又细又长。比起狼，给人的印象更像是狐狸。

这个被叫作阿赫的狼人，全名叫赫鲁贝尔，既是昴和蕾姆所居住着的“长屋”的邻居，同时也是昴在巴南结识的第一熟人。

“不是还能叫我狐狸脸的嘛。昴真是一根筋呢。”

“别人的相貌可不能随便乱说嘛。何况我说的是事实。”

“我既不是地精也不是狐狸，是濒临灭绝的稀有种狼人呢。难道你觉得我身上没有背负着一族的骄傲吗？”

“既然要背负的话，那就再稍微上点心啊。”

一族的骄傲也得看是谁背负才行。假使是昴来背负的话，至少不会将濒临灭绝的狼人族的称呼转让给赫鲁贝尔。虽然受了他不少照顾，但这不代表会无条件信任对方。

“就不陪你唠嗑了，现在我正工作意愿满满着呢，可别给我添乱。”

“什么嘛，才刚见面就这么冷淡。就你这顽固的性格还是算了吧。再说了，昴这么想工作手头也没活儿吧，空有一腔热情而已啦。”

“我知道自己很顽固所以别说了行吗？！”

昴反驳地嚷道。赫鲁贝尔晃了晃嘴上的烟斗，随后吐了口烟。

“顽固点好，顽固点好。你可不能让家里的贤妻挑大梁啊。身为丈夫整天无所事事，还不知道把姿态放低点儿……蕾姆还真是可怜啊。”

“才没有无所事事！虽然很不甘心，但其他都说的没错！我确实尽给蕾姆添麻烦了。……真没面子。”

昴沮丧地垂下肩膀，赫鲁贝尔见状呵呵一笑。

“你当我是傻吗？还是说你是来鼓励我的？”

“你我都是无业人士，我想着来找你寻求慰藉什么的”

“才不要呢！之前差点成为情夫，这次又是慰藉的也太那啥了！”

昴连忙推开凑近的赫鲁贝尔，拼命想要撇清自己。

不过严格来说，赫鲁贝尔并非无业人士。这个不着边际的家伙是长屋的管理者——且不论他是否有在好好管理着，至少管理者的身份是千真万确的。

尽管见他成天不是睡懒觉就是梳理毛发，又或者是喝酒叼烟嘴的，然而并非没有工作。

“总而言之，阿赫对我来说也是个遥不可及的存在啊。”

“你这么说就太生分了。虽然我成天睡睡懒觉整整和服钱就能进账，可我是打心底里敬佩着想通过努力和汗水挣钱的昴哦？因为那样很棒不是吗？”

“闭嘴吧，你个工作宅！……上哪儿找工作好呢？当个管理员怎么样？”

“虽然不想打击你的积极性，我和那间长屋的主人是友人呢。因此是靠关系才……抱歉哈，昴。我是人生赢家呢。”

“可恶啊！！”

赫鲁贝尔的话着实无法作为参考却又让人嫉妒不已，昴按捺不住内心的愤怒骂声连连道。

到头来，在这个学历完全派不上用场的异世界，唯有靠人脉了。而即使抛去异世界人这一事实，人脉对于昴而言也是可遇不可求的。

无论是异世界还是在故乡都没有牢靠的人际关系——这就是菜月昴的真实写照。

“独自一人外加无业吗…… 貌似只能等死了啊。”

“你还有蕾姆陪啊，怎么会是独自一人呢！”

赫鲁贝尔张开大口仰天笑道。昴朝她瞥了一眼，无奈地叹了口气。

“你又不是不知道我的情况。今后我打算到处谋职去了。最好能有到手15万、包交通费，同时还交保险和养老金的职位。”

“我没什么工作经验，你刚才开的这些条件算高吗？”

“不过是按我故乡的标准认真算了笔账罢了。这样的条件保守估计，是我在这个世界工作所最起码要有的薪资待遇啊……”

当下迫在眉睫的，是不能仅由蕾姆养着自己。为此，不稳定的亦或是无法长久做下去的工作是不能列入考虑范围的。

昴的目标说到底不过是想寻求一份长期稳定的，能拿得出手的工作。

“所以我才跑到职业介绍所来了。”

在距离巴南大街一条街开外的地方有一家店铺正在营业。

这家被昴随口称为职业介绍所的店铺实际上叫作“中介所”。是一家专门向人推荐职位以及写推荐信的店铺。

尽管巴南还有其他几处中介所，昴却是这里的常客，与店长交情甚好——

“——额！是你啊废柴！”

昴刚一踏进店门便受到了如此“热烈”的欢迎。

“一上来嚷嚷什么呀，别给我起这种绰号，怪没面子的。”

“没面子的是我啊！你在搬运现场搞砸了不是？我可是被狠狠批了一顿啊，叫我以后不要再推荐像你这样无能的家伙了！”

“可恶，没想到现场的那个监督表面上叫我们回去路上当心点，背地里是这么说的……”

同昴进行着对话的是一只穿着围裙的雄蜥蜴人。虽然蜥蜴人在亚人中并不罕见，然而这只雄蜥蜴人因过于肥胖，乍眼看去更像是一只青蛙。

他名叫克莱茵·德纳夫，是这座城市公认的中介所店长。

能够得到公认的中介所并不多见，高质量的岗位推荐是它们能获此殊荣的原因。

然而，这位良心店长却露出一副嫌弃的神情打量着昴，

“搬运行李的差事到底要怎样才能搞砸啊？照这样下去，没有你能干的工作了。”

“不是这样的，因为我的工作量和别人的不一样，我过于在意这件事了所以发了呆……”

“每天的工资是固定的。你要是找周围的人帮帮忙，应该能省不少事才对。”

“那样做太不厚道了吧。不厚道的事还是不太好。”

“你怎么这么固执呢！也不想想我为了给你一份好差事找了半天……”

面对昴的狡辩，克莱茵颇有些无奈。随后，他将视线转向昴身后站着的那个人影。

“咦，这不是赫鲁贝尔嘛！好久不见好久不见！”

“嘛，素招呼就免了吧。我不过是来见证昴找工作的最终结果的。”

“最终结果什么的，比起这个……”

昴站起身，打量着克莱茵和赫鲁贝尔。随后他指向赫鲁贝尔，

“你认识这个游手好闲的家伙？”昴向克莱茵纳闷道。

“游手好闲！听起来多么美妙！我今后便作为‘永远的游手好闲者'生活下去了。有问题吗？没问题吧？”

“能对游手好闲如此情有独钟这点很有问题啊。”

附和着赫鲁贝尔的吐槽，昴等待着克莱茵的回答。只见他挽起粗大的双臂，呢喃道：

“废柴……啊不，昴先生是个大人物啊。老夫坚信这一点。”

“就不能说得再直接一点儿吗！”

“你看我说话语气都恭敬起来了不是？你把赫鲁贝尔当成什么人了……”

克莱茵的表情写满了惊恐与无奈，话到嘴边又咽了回去。昴抬了抬眉毛，对他的这一反常举动感到诧异。而克莱茵的视线飘忽不定，随后“啊”地一声，

“赫鲁贝尔是……是那个，永远的游手好闲者嘛。”

“这个外号刚才不是说过了嘛？”

“总而言之！这个话题就讨论到这里吧！别在意，我会给昴先生介绍好工作的啦，就像之前运货的工作那样子的。”

“这方面我倒是无所谓，我想找的是有晋升空间的工作。薪资待遇等等条件可以当面谈，必须是面向家里挑大梁的人的工作。”

“家里挑大梁什么的，老夫头一次被委托这种条件……”

克莱茵思考着昴提出的要求，眼睛快速地扫了遍店内。

虽说是城市公认的中介所，店铺本身却不十分宽敞。木质结构的平房内仅容得下几张桌椅，狭长的墙壁取代告示板，上面贴满了招人广告、寻人启事以及各种委托书。想要找工作的人便从这些信息中自行挑选，反之想要办事的话便委托克莱茵张贴告示。

“要是我接了击退恶龙的任务但不幸失败了的话，怕是会给你的牌子抹黑了啊。”

“不可能有人委托这种事的。要真出了这种事，我就第一时间逃离这个国家。”

“帝国那边倒是很乐意接那种活儿呢。一切顺利的话，说不定连王国的神龙也能击败呢。要真是那样的话，夺取国家也不在话下了……”

“嘿！克莱茵！你看这个！塞蕾丝缇雅的被窝探索，听起来很有趣！”

往烟斗里上完火的赫鲁贝尔的声音盖过了昴的发言。只见他拖着笨重的身躯来到墙壁前，看着昴从墙上取下来的委托书念道。

“我看看啊，征集大精灵塞蕾丝缇雅的被窝的探险队！一直以来不为人知的大精灵的处所，不仅能够探寻他的所在地，还招收探险队成员！待遇面谈，报酬视调查结果而定！这！这个……这感觉不咋地啊……”

“你一个人瞎嚷嚷什么呢！还有，这个还给我。”

见昴对这份征集内容死了心，克莱茵将告示拿了回去。他盯着告示看了会儿，随即发出了“啊”的一声。

“这个委托是我忘了撤下来了。征集在很久以前就截止了，不过一直不让撤下来所以只好挂着了。”

“探险已经结束了吗？”

“这个世上的笨蛋比你想的要多得多啊。”

克莱茵耸了耸肩说道。这个回答令昴心头一紧。

一旦和大精灵扯上关系无疑是自寻死路。一本正经接下这份委托的人是愚蠢的。——不过至少祈祷那些不要命的家伙们能死得痛快一点吧。

克莱茵见昴像是察觉到了这般神色异样，便拍了拍围裙说道：

“这种主动送死的差事还是不要干的好，我也明白昴先生现在的处境。虽然明白……可还是犹豫要不要交给你……！”

“也就是说，这份差事并不是主动送死吗？！”

“这要看情况了。话虽如此，昴先生毕竟是要为了家中可爱的妻子而工作的啊……！”

克莱茵掏出一份委托书。这是他认为目前最好的选择了。昴小心翼翼地接过委托书，用眼睛扫了起来。

“……在这位叫利夫坦·玛格洁的人手下当侍从吗？”

“没错，为期一个月的短工，也就是打打下手。昴先生，不赖吧。”

说着，克莱茵脱下围裙。与巨汉体型极不相称的这件可爱围裙所令人印象深刻的，是它上面绣着的花纹。

“就蜥蜴大叔穿着的围裙来说可真是恶趣味啊。”

“还不是你让我穿的！我家老婆看了可高兴了！”

“我只说了让你扣上扣子而已啦。那么，这件围裙和那份差事有什么关系？”

“你看看注意事项，里面不是写了工作场所女性居多嘛。有了这种技巧更受女性欢迎。”

“想多了！我在意的是注意事项里写的‘仅限年轻男性'这条。”

女性居多，仅限男性——完全搞不明白是什么性质的工作。

工作内容只是简洁地写着打下手、杂物活之类的，也没有特殊执照和力气大等相关的要求。

只要对地位不太抵触的话，其实就是当一个月男佣。

“……确实不错，有没有什么办法能避免续签合同呢？”

“那样的话一直干这份美差不也挺好的嘛？当下就先踏踏实实地积累资金，把身名宣传出去，等取得了足够的信任之后再跳槽呗。这点你也是知道的吧？”

“蕾姆她可是打一开始就被介绍去学堂工作了啊。”

“那是因为她讨人喜欢嘛。”

无法反驳，尤其是蕾姆讨人喜欢这点。昴的诡辩在社会上是派不上用场的。

“吃白饭的男人要在卡拉拉奇得到认可是天方夜谭。”

“所以我才跑来这里了不是？！”

为了寻找新工作跑来中介所，但因为前一份工作搞砸而备受冷遇。而遭受冷遇的原因不是工作热情不足，而是昴现在缺乏社会信用这一首要条件。

不管怎样，克莱茵也没有对昴网开一面。昴耷拉下肩膀，一副放弃了的样子。

“介绍信就拜托你了。请一定要下点功夫写啊。”

“知道知道，放心吧。利夫坦虽然是个猛商，为人倒也稳重。”

“……猛将？”

“是猛商。”

不理会昴的纠结，克莱茵继续写着介绍信，并将信纸谨慎地装入信封交到昴的手中。

“后天早上去见利夫坦，就说是我介绍来的”

“我知道了，一直都这么麻烦你”

“你小子就最后这句像话！真是的，这回可别搞砸了！”

昴将信揣在怀中，向回到店内的克莱茵挥手道别后与抽着烟嘴的赫鲁贝尔一同离开了中介所。

“话说回来……阿赫你还真是闲啊。”

“怎么了，突然说起这个？”

“就好像是一个无业人士慵懒地看着其他人找工作一样。难道不觉得很过分吗？”

“面对比自己境遇更惨的人难道不应该给予鼓励吗？我充当的是啦啦队呢。”

“那我获得的可不是什么鼓励和勇气，而是某种乌黑乌黑的玩意儿啊。”

昴回敬着赫鲁贝尔的玩笑话，随即哀叹一声。毕竟有工作的是赫鲁贝尔，而昴自己才是社会地位更低的那一方。

“不过找工作还真是费劲啊。你来到这儿之前都在干些什么呢？”

“——”

昴被赫鲁贝尔不经意的提问给问住了。

“这个嘛，”。昴立马调整好呼吸，耸了耸肩答道。

“和蕾姆一起东转转西转转呗。然后发现这儿不错。能租在长屋也多亏了阿赫，帮大忙了。”

“这事儿不用谢我，谢长老就好。人的缘分就是其生活方式的写照。能受到恩惠也是一种气量嘛。”

“……缘分什么的，有蕾姆才搞定的啦。”

这点是毋庸置疑的，昴心里如此想着回答道。他的心中百感交集。

总算是找到了一份差事，心中的一块大石头暂时是放下了。

“卡拉拉奇之旅呢……”

昴喃喃自语着，将在一旁叼着烟斗喋喋不休的赫鲁贝尔晾在一边。

3

“抱歉，蕾姆。俺尽力了……”

“——昴君？”

“啊，不闹了咳咳，不好意思啊。下一份工作也是短工。”

日暮时分，昴面对着在灶台旁做饭的蕾姆的背影跪在榻榻米上，掏出从中介所拿到的介绍信。蕾姆喊停了他蹩脚的卡拉拉奇口音，停下做饭的手接过介绍信。

“即使是短工也是一种收获哦。今后才是昴君出色表现的时候呢。蕾姆我能看见呢，届时昴君一定会为人们所崇敬，进而为你建造铜像的景象”

“不知道这个世界有没有眼科啊……”

对于蕾姆那略显夸张的看法，昴苦笑着回应道。忽然，蕾姆发出了“啊”地一声。

“这是份在利夫坦大人的麾下的工作呢。”

“的确是这样，蕾姆和那个叫利夫坦的人是朋友吗？”

“也不算是。在学堂的班上有个商人的孩子，或多或少听他提过猛商利夫坦大人的事。”

“你刚刚说猛商！难道不是勇猛的将军的意思吗？”

“呵呵呵，勇猛的将军……昴君你不要说笑啦。”

面对昴的疑问，蕾姆像是被戳到笑点般咯咯地咧开嘴。随后，“听好了哦。”，只见她竖起手指说道。

“哦哦，很有老师的风范。”

“不要打岔。所谓猛商，即是卡拉拉奇内对商人的一种称呼。对于优秀的商人，会予以‘大商'、‘豪商'和‘猛商'的称号，可谓是商人的名誉呢。”

“大商和豪商我能理解，猛商是什么意思啊？”

“在商业繁盛的卡拉拉奇，生意上的成功好比战场上立军功一般。利夫坦大人可是备受人们尊敬的哦。”

蕾姆说罢，目光在介绍信上来回扫寻着。望着神情不宁的蕾姆，昴皱着眉头道：“蕾姆？”

“你好像有什么心事，发生什么了吗？”

“那个，听说在利夫坦大人手下工作的多为女性……帅气的昴君要是在那样的工作环境下……”

“你想太多了啦！”

蕾姆一边继续着那夹杂着个人情绪的言论，一边将介绍信展展叠叠。昴见状多少也明白了蕾姆在担心些什么。

“好痛！”

“好痛呀！昴，昴君？”

面对因突如其来的击打而错愕的蕾姆，昴叹了口气。

“真是的，别想些有的没的啦。你把我想成什么人啦。”

“对不起，可是我还是会忍不住去想。不知道雇佣女性的利夫坦大人见了可爱的昴君会不会起什么色心……”

“啊咧？！你这话怎么和我原先想的不一样！”

听了蕾姆的偏执想法的昴吓了一跳，试图将话题引回正确的轨道上去。

“说到底可爱什么的，你看着我的眼睛，哪里可爱了？”

“昴君的目光炯炯有神，蕾姆已经按捺不住了。”

“在你眼里的我究竟是什么样子的啊？！”

蕾姆对于昴的评价有太多地方让人无法理解了。先不去想那些有的没的了，昴将手搭在蕾姆的肩膀上。

“没什么好担心的，我只要你就好了。即便面对的是遍地女性的职场也会如此的，懂了吗？”

“唔……知，知道了啦。昴君……”

听了昴的轻声细语，被轻抚着头的蕾姆红着脸答应道。昴就这么继续抚摸着，带着关爱与柔情。

蕾姆缓缓抬起头，湿润的眼眸相对着。两人近得能感受到彼此的呼吸——突然，锅声响起。

“哇！”“咿！”

锅盖掉落的声音打破了这片寂静，吓得蕾姆赶忙跑去了灶台。只见她给搭载了魔矿石的炉灶散热，盯着掉落的锅盖，心有余悸地捂着胸口。

她转过身去，视线正巧落在了因惊讶而僵直地站在那儿的昴。

“噗”“哈哈哈”

两人不约而同地笑了起来。

就这样欢愉了一阵，“那么接下来”，蕾姆拍了拍手说道。

“开饭吧。昴君来帮忙摆下桌子。”

“也只有那种短脚的桌子了吧。”

带着方才的余韵，二人着手准备起晚饭来。蕾姆待昴将搁在墙边的短脚食桌搬到屋中央后，将锅稳稳地摆在桌上。

锅内汤味四溢，里面盛着甘甜不烫口的蔬菜——今晚的主食是鸡肉汆锅。

“鸡肉汆锅啊，偶尔尝尝真不错呢。就着柑橘汁可是极品美味。”

“刚好分到了些蔬菜，顺便我也想吃点酸的东西。昴君吃酸的不要紧吧？”

“何止不要紧，我喜欢得不得了啊。倒是没想到蕾姆原来喜欢吃酸的呀？”

“也说不上喜欢，刚好想吃而已……”

蕾姆一脸不可置信般地用手指摸着下巴。而昴却一副理解的样子。而且，蕾姆将自己想吃的东西优先列为菜单并不是件坏事。

一直以来将昴放在首位思考事物的她，如今正渐渐蜕变着。

“好吃！今天做的饭菜也棒极了！”

“能有个如此可爱做饭还可口的妻子什么的……再这样夸下去我会害羞的。”

“不过这是事实嘛，是我的福分呐。”

来到这儿以后蕾姆的厨艺依旧那么高超。起初在厨具和食材方面确实费了不少劲，不过转眼在卡拉拉奇也已经生活一年多了，熟门熟路了不少。

做饭是得心应手了，有些事依旧还差那么点儿。

“唔，肚子好胀。撑得动不了了……”

“粗茶淡饭而已。蕾姆的膝上现在空着哦。”


“太好了，让我躺躺。”

“收到。这是昴君专用的特等席，请吧。”

昴转身一咕噜侧靠在蕾姆膝上。脑袋刚一贴在柔嫩的大腿上，幸福感便遍及全身。

就连装满了两人份食物的肠胃也仿佛置身于快乐之中。

“啊……蕾姆好厉害啊。”

“嗯。不过昴君也很出色哦。”

“才没有啦。”

“在蕾姆心目中就是很出色呢。而且是极为出色。”

与昴对自己的看法不同，蕾姆全心全意地信赖着他。

而昴并不确信自己是否值得她去信赖。因为“蕾姆很厉害”这一想法并无半点虚假，这是昴的心声，昴的感谢，同时也是昴的谢罪之言。

她或许也明白这点。——若是如此，他便更感到羞愧了。

“让胃休息下，然后我们去澡堂吧。当做是上班前的放松。”

“然而是后天上班哦？”

“我知道的啦。所以明天要让你好好休息休息。——不过，今夜另当别论。”

蕾姆贴在昴的耳边细语道。瘙痒的感觉令昴的耳根通红。

“蕾，蕾姆好厉害啊……”

“嗯。因为有你的爱”

听见昴支支吾吾的回话，蕾姆凑近身子应道。

不过昴并未察觉到的是，此时蕾姆的耳根也变得通红了。

4

两天后，昴持介绍信造访了利夫坦·玛格洁的住所。

“不愧是传闻中的玛格洁殿堂……好大啊。”

将介绍信给正门的看守过目后方才取得通行许可的昴感叹道。

位于巴南北部的这座房屋被称为“玛格洁殿堂”。平房式样的和风建筑风格与宽广的占地面积，令人不禁联想到古装片那样的大场面。

“来这儿上班要半个多小时，还会发给我工作服。”

多亏了有介绍信，昴这趟拜访顺风顺水。形式上的面试姑且还是要走一下的，女仆长见到昴后便予以通过了——具体是怎么通过的不得而知。

总之，昴正式成为了干杂务的新手成员之一，他怀揣着对新工作与新同事的紧张之情穿上工作服，踏上职场。

这座玛格洁殿堂如招募公告上所写的一样，女性多得惊人。

至少昴在这里还没有见到过除了看守以外的男性。看守也是无法踏入殿堂半步的，因为在室内工作的男性真的只有昴一人。女同事们多得数不过来，这里毫无疑问是个男女比例严重失调的工作场所。

然而蕾姆的担心是多余的。昴为人坦荡的同时，她们大多为已婚女性。

不过取而代之的问题却接连不断。

“昴君！这个能拜托你吗？”

“啊，昴君，这边这边，来帮帮忙。”

“呀！昴君真是个美男子！就是这样，就是这样！好帅！”

挑逗声——虽然这么说有些欠妥，这样的声音充斥着整座殿堂。那是与昴一同工作的女同事们的雀跃声。

昴到底是一名男性，因而他并不反感异性们的吹捧。但也仅仅是不反感。

“哦嚯嚯，这屁股不错嘛。”

“咿！！”

走着走着昴的屁股就被摸了——不对，是被猛烈地揉搓着，发出阵阵悲鸣。等他捂着屁股回头看去，那些人早已消失在了走廊的尽头。

一味受到性骚扰的昴颤悠悠地扶着走廊的墙面失声痛哭起来。

“这性骚扰真可怕……不愧是大阪大妈成群的地方……”

昴一边诅咒着自己误入魔境的不幸一边流着泪。

刚才揉了昴屁股的是大阪的大妈们——准确来说是卡拉拉奇大妈们。不过具体是谁干的尚不清楚。

在这座玛格洁殿堂内工作的全体女性都有嫌疑，肯定不止一次这么干过，说她们是惯犯都不为过。昴就像是被丢进饿虎群中的兔子一般可怜。

这里是中年妇女们独显威力的职场，与是否为人类还是亚人无关。

“雇主这是什么兴趣啊！钟爱熟女吗！”

“你的这句评价太主观，太片面了呢。”

听了昴的牢骚话，墙壁，不对，这一阴沉的声音是从昴背后的一个男子口中发出的。男子逐渐逼近，若不是看守的话，那么对方便是入侵者——

“谁，是谁！这个男性的声音！！”

“真是遗憾，符合条件的只有你了。现在能救你的也只有你自己了呢。”

“你说的没错！但是你一个看守来这里干什么……”

见昴没有反驳，声音的主人出来与他打了个照面。那是一名留着两髭和粗眉的，身材瘦弱的中年男性。只见他身着高级材质和服，全身散发出达官贵人般的气质，身份不言自明。

“难道，你就是利夫坦·玛格洁、大人？”

“正是。我就是你的雇主利夫坦·玛格洁，没什么好怕的。总算是忙完外边的事情，便过来见见新人长什么样而已。”

面对昴的疑问，利夫坦·玛格洁摸着胡须落落大方地点了点头。他丝毫没有追究刚才昴因不识自己身份而做出的无礼举动，果真为人宽厚。

因而昴借着这份宽厚斗胆开了口。

“叫您老爷，可以吗？属下有个问题，请问您喜欢熟女吗？”

“问得很直接嘛。不过你这是误会了。”

见昴不太相信，利夫坦·玛格洁无奈地耸了耸肩。随后他长叹一口气说道：

“女性大多细心开朗，举手投足间处若不惊。这份安心感是他物所无法替代的。女性的包容力随年龄的增长更显魅力，你难道不这么认为吗？”

“可我的屁股最近几天被摸了上百回又怎么解释呢？！”

“说明你有一对好屁股。”

“好过头了吧！”

“拍打起来有响声。我懂了，难怪你会有克莱茵给的介绍信。”

利夫坦趁昴不注意擅自对他的屁股进行了确认，至于昴有介绍信的真正原因却不予细问。

“不过嘛，从工作环境来看，老爷喜欢熟女这件事是没跑的了。”

“这可真是令人难过的误会。什么时候你才能解除误会真正理解我……不过到那时你是否还能留在这里，就让我拭目以待吧。”

“挺会故弄玄虚的嘛，凭什么这么说？”

“你觉得迄今为止来这儿干活的男性只有你一个吗？”

利夫坦用他那低沉得发颤的嗓音笑着说道。这外表加上这语调，昴的脑海中猛地浮现出一个地方恶官的形象。

“因为至今为止的那些男性全都因为被性骚扰而离开了吗……”

“性骚扰？没听说过的词呢，不过大致上猜得出意思。对于你的猜测，我不否认。”

简而言之，每过一段时间会需要有人来当牺牲品，而昴就是因此而入选的。

满是女性的工作环境里，对性骚扰没有抵抗力的男性想必一定会过得很艰苦。要是有男人的矜持的话，某种程度上会留下巨大的心理创伤。

“不过嘛，你和之前那些男性比起来似乎更……有毅力嘛。期待你的表现哦。”

“谢、谢谢您的夸奖……”

利夫坦拍了拍昴的肩膀，向走廊的另一端走去。昴目送着背影，面对雇主的古怪嗜好，他噘着嘴，心中多少有些惆怅。

人类，要变得伟大是否须以牺牲人性为代价呢？亦或是感性异于常人之人承认自身的异处并最终出人头地呢？

昴摸着自己刚才被利夫坦拍过的肩膀思考着，叹了口气。

“……对我有所期待不过是徒劳罢了。”

昴的呢喃就这么消逝在了木质地板上，无人知晓。

“昴酱！稍微过来一下——！”

“——好的！我现在就过来！”

听到远处传来叫喊声，昴迅速收拾起悲伤的心情跑了过去。

面对殿堂内的繁重劳务和女同事们，昴一刻不停地奔走着。

** 第二章 『三个月』

1

经过了和雇主的那一次事件之后，昴在宅邸的工作的日子倒也一天天相安无事地过去了。

而工作内容，也可以说是和之前的传闻相去甚远、十分顺利。听说在此之前宅邸雇佣的许多和昴是同一处境的男性们，往往都是还没过两天就叫苦不迭，然而昴却没有。

毕竟最首要的一点，也是因为雇佣昴时的条件是——只要是“年轻男性”就行。

弄清楚了被雇佣的理由，反而能让紧绷的神经放松下来、更专注地投入工作中去。所幸同事们有点过于粗暴的肢体接触也渐渐减少了，昴也没有再因此受伤了，这也多少保全了他的自尊心。

然而要说最幸运的就莫过于，正如克莱茵所预测的那样，昴相当受那些女前辈们的青睐。

「昴酱真是个勤劳的人呀。了不起了不起」

「不仅手脚灵巧心思缜密，还总能顾及到别人的情绪呢。和我家那孩子就是不一样呢」

「和他聊多久也不会觉得腻，还总是笑眯眯的就像个单纯的孩子一样哪」

诸如此类的，都是那些女前辈们在闲聊时常常挂在嘴边的。

为人和善总是挂着笑脸，很会开玩笑逗人开心，聪明好学不懂就问，任劳任怨做事积极。对昴的评价大抵都是相当好的。

从不会笨拙地死撑着面子、妄图掩饰自己的错误这一点也让她们相当欣赏。刚来那会儿让昴相当伤脑筋的性骚扰，也在熬过了最初的几天后锐减了。

「也就是说、或许大家都接纳了我成为他们的一份子了呢」

随着屁股被乱摸乱揉的次数锐减到十分之一的时候，昴如此感叹道。

编外人员、外来人往往就会受到那样的对待。然而，只要一旦被认可了、被接纳了，那样的事也就自然而然地消失了。之前的那些男性大抵都是没什么忍耐力才没能等到这一天吧。

「嘛，不过真要问起来是为什么要忍耐我也是有点迷……好，完成了」

缝上最后一针，昴把多余的线头用牙齿咬断。这下一来，呈现在眼前的就是纯手工做上装饰的一身衣服了——正是宅邸的制服。

昴为宅邸里佣人们人手一件的制服上一一缝上了花朵装饰，当然也没忘那些预备的制服。这是为了在今晚即将在宅邸召开的宴席上，能一眼就分清谁是客人谁是佣人的标记。

由于在卡拉拉奇的正装一般都是和服，没准儿就会把穿着和服来的客人们和佣人们给混淆了。因此也就需要一个巧妙而不伤大雅的方法了。

「毕竟在这儿，也不能让佣人们都穿上女仆装啊」

而缝上这些花饰，也是得到了女主人的同意后，昴主动担下责任的本职外的一项工作。尽管那些女同事们都体贴地对昴说道，「也不用劳你这么费心啦」，但他只是笑，「毕竟这是宴席对吧？看到大家都穿上这么可爱的制服，客人也好我也好都会更开心呢」

就这样，全员都愉快地接受了他的好意。

然而，那些穿上了带着可爱花饰制服的女前辈们又不仅仅满足于此了，像是抱着绝不能输给来宾的气概一样，纷纷精心做了发型化了妆，差点儿又引起了另一场混乱来。

而除此之外，在宴席上又发生了一件让昴吃惊不已的事儿——、

「——有吃惊是吗？昴君」

「……是啊，肯定会大吃一惊的吧」

「这样看来这次可是大获成功啦。呵呵呵，昴君穿上制服的样子也很帅气呢」

说这番话，让昴吃了一惊的便是身着一件藏青色打底、缀满了牵牛花一样的纹样的和服，头发上还插上了一支簪子作装饰的蕾姆。


蕾姆穿上这样一身华丽的衣装，惊艳到几乎要独占了全场所有的目光一般。然而，她却看也不看周围一眼，只是专注地等着昴的回答。

「啊---，太太太可爱了，我的新娘」

「哎呀呀……眼前的就是迎娶到了世界上最棒的新娘的幸运儿呢，好害羞啊」

「所言极是啊……不过，蕾姆为什么会在这里？」

看着蕾姆双手捂着绯红的小脸上半身扭啊扭的可爱模样，昴不禁脱口问道。听了这话，蕾姆说着「是这样的」一边抬起了和服的振袖

「其实呢，是蕾姆在寺子屋教的一个孩子的家长邀请蕾姆来的。一开始是想着婉拒的，但是说是利夫坦大人的宅邸就……顺便还借了一身和服呢」

「原来是为了来看我工作的样子啊。……那位，好心邀请了蕾姆的家长，是男性吗？」

「请放心吧，是女性呢。昴君你就是喜欢担心了啦」

邀请来宴席（也就等于派对），甚至还借了一身和服。可以说昴会生了警戒之心也是理所当然的吧。

看着昴这幅模样蕾姆不禁轻笑起来

「万一发生了什么事儿也别忘记蕾姆可是鬼哟。到时候一定会把对方的下腹部踢个粉碎的」

「一般来说蕾姆你从来都没有直接这么说自己是鬼的吧啊喂！？」

在这之前昴还从来没听过这么强有力的身份宣言。而把下腹部踢个粉碎……光是想想昴就有点腿发软。只见蕾姆正了正自己的发簪，

「因为绸缎庄有很多漂亮的和服，就爽快地借给了蕾姆一件。不过说是让蕾姆来穿也能起到宣传作用，所以蕾姆有点儿不太明白是什么意思……？」

「当然也就是字面意思啦。让美女穿着自家的衣服自然会博得一致好评啊」

而确凿的证据也就在于，哪怕周围人都知道了这是有夫之妇，他们眼神里的热度也没有降下来。能看到蕾姆穿和服的样子昴也很是享眼福，但身为丈夫，心里的不安也在加剧。

不过话虽如此，让昴觉得骄傲的是蕾姆完全没有一点儿动摇的心思。更何况她自己也说了，万一真有人不识相地对她出了手，可是有粉身碎骨之危的。

「不过惊喜倒的确是超惊喜的。我还有工作在身也没法太照顾到你，蕾姆自己好好放松享受一下吧。就论做饭的手艺我也是不逊色于蕾姆的哦」

「唔唔，不过蕾姆也不能认输。昴君的胃可是蕾姆的专属哦」

「呃呃，这话说得像是直接就要一把给揪去一样……」

「但是，总有点不可思议说不上来的感觉呢。蕾姆就在这样努力工作的昴君身边，静静地守望着。简直就像……」

「——」

说到那儿，蕾姆却突然停下了。她到底是想要说些什么呢。而眼下蕾姆只是「不不不」地摇着脑袋让人无从猜测。

「那蕾姆就随同邀请我的那位夫人一起了哦，蕾姆会偷偷找机会往昴君嘴里投食的哦，就期待着吧」

「这可是相当新颖的派对娱乐方式啊！？」

虽说本来也就不曾分散过注意，而现在蕾姆离开了，又多了一个更得专心致志的理由了。目送自己媳妇儿的身影消失在熙熙攘攘的来宾中，昴不无感慨地耸了耸肩。

也就是在那时，他突然察觉到身边站了个人——，

「——真是个不可多得的好媳妇儿啊，蕾姆酱她」

「哎呀呀哎呀呀，这就奇了怪了」

循着陌生的声音回过头去，昴立刻斜睨住了突然出现在身后的狼人——赫鲁贝尔。而对方正穿着和平日里别无二致的衣服一副和往常一样的态度，一个接一个的把盘子里的食物往嘴里扔。


「嗯---，真是绝品啊。免费的酒，免费的饭，你说这世上哪有比这更美味的享受了？」

「当然有了。是爱妻亲手做的饭菜嘛」

「哇！这恩爱秀的！再这样我酒也喝不下去了啊」

「不是啊，倒是阿赫你为什么会在这种地方！？」

昴一把拍掉赫鲁贝尔伸向酒瓶的手，声色俱厉地质问道。而面对气势汹汹的昴，赫鲁贝尔只是微微睁开了他那眯缝成一条线一般的眼睛，挤出了一个心虚的笑，

「也不看看我是什么人，门卫当然都是我的老相识了嘛。这可是阿昴你没法企及的人脉能力啊」

「这压根就是非法入侵吧！」

当然昴是很想追究当值门卫的责任的，但真要说起来赫鲁贝尔的面子到底有多大也的确是个谜。仔细回想一下，就连克莱茵对赫鲁贝尔的态度也是相当恭敬的。

「难不成阿赫你是微服私访咱们市井大众的殿下？」

「还殿下呢。看来你对古语也有点了解嘛。这不是卡拉拉奇一统之前对国王的称呼吗」

「是吗？其实我不知道啊」

也就是那么随口一说，却没想到这又是一个和原来的世界的交汇点，昴露出了一脸嫌麻烦的表情。而就在这时——

「——哎呀呀这可不是『永远的游手好闲者』氏嘛。你这家伙也大驾光临啦」

「哟，利夫啊，好久不见。本来你也没请我来，还真是不好意思了」

赫鲁贝尔手里的酒瓶不知何时已经高高举起，像是冲着前来打招呼的利夫坦的回敬。而见了他这大大咧咧的态度利夫坦却也只是落落大方地点了点头，昴这才反应过来立刻对着自己的雇主颔了首

「真是抱歉，老爷。我立刻就把这可疑人士给赶出去」

「哎哟哎哟，阿昴，你这就过分了啊」

「你这对工作的热情我倒是挺欣赏的，不过不用啦，小伙子。『永远的游手好闲者』氏能在这种场合露面也是挺难得的。反倒是我，要为了没有发请帖赔个礼了」

大大咧咧的赫鲁贝尔和绅士风度的利夫坦，这两人的关系在昴看来又是一个过于难解的谜。只是，要是说哪里有一个值得大大方方点出来的吐槽之处的话——

「莫非你这个游手好闲者的玩笑头衔还真给散布出去了？」

「悦纳自己中意的事物可不就是咱们卡拉拉奇的一大优点嘛。多亏了阿昴，我也有了平易近人的名号，还真是叫人开心哪」

「是，是吗……你什么时候转行当个贤者就再好不过了啊」

不过鉴于游手好闲者头衔前面还有个『永远』的称号，转行还是不大现实，但人总归是不能放弃希望的。

「对了，小伙子。这几天来，我都有在认真观察你……」

「啊，对不起。瞧我只顾着和客人说话去了……诶，这几天！？观察！？」

「我应该也说过吧，我对你还是很期待的。女主人也跟我报告说，你和迄今为止的男人们都不一样。说是你比起他们来说更有……对了，更有女子力」

「女子力！？」

「这也的确是个勾人好奇心的词啊。不过我听说是你把这个词诠释得更完美的」

这让人意外的评价和这顶猝不及防犹如现世报一般的名号让昴惊掉了下巴。自己的确是曾经对女前辈们提到了几次『女子力』这个词，但果然还是太小看了卡拉拉奇人接受新事物的能力。

即便如此，昴还是想不通这个词怎么会用到自己头上的。

「那么，老爷您又是怎么看这个女子力的评价的呢？」

「当然也不是说只欣赏你这一点，不过大体上，女主人和你其他的女性前辈们都是意见相同的」

「意见相同……」

「对了，我也听克莱茵说你好像很长一段时间都在求职」

听了这意想不到的一句话，昴楞楞地直眨眼。而对昴这样的反应，利夫坦扬起了粗粗的眉毛，伸过手来摸上了昴的胸——前的那朵花饰。

「做得真精致。做事儿还挺麻利的嘛。女主人她们也很高兴啊。就保持这个状态，接下来的实习期也好好加油吧。——我期待着最后一天能跟你有个愉快的交谈」

「——」

昴闻言深深地低下头去，利夫坦和赫鲁贝尔又寒暄了几句便回到了宴席大厅的中央。身为东道主，好好招待每一位来宾是他的义务所在。

而他百忙之中还拔冗来和昴聊了几句。而他话里的真意是——

「……阿赫啊，刚刚的话我可以理解为是对我大有期望吗？」

「如果那都是拐弯抹角的解雇预告的话，那我就再也不能相信这个世界的任何事物了」

如是回答着，赫鲁贝尔举起手里的酒瓶一饮而尽。而昴还沉浸在刚刚那冲击性的一幕里，都忘了提醒他这样的举动对于一个不速之客是很没礼貌的。

于是下一秒，昴从赫鲁贝尔手中一把夺过酒瓶、

「喔」

「尊敬的客人，您的酒像是喝完了呢。让我再为您取一杯来」

像是想要干脆把现场的气氛全给重整一下一般，昴逃也似的离开了。

一边忍耐着脸颊上火烧一般的温度，昴在心里默默下了决心，今晚要比任何人都要率先来为这个宴席尽职尽责。为了这一点，哪怕对方是不速之客也要招待得无微不至。

——这下一定也能给蕾姆带回好消息的，莫名的期待在昴的心里跳动着。

2

「——啊，昴君」

那是昴总算收拾好了宴席的残局，刚从正门出去想要急着赶回家的时候。

突如其来的一声招呼让昴有点儿惊讶地抬起了脸。下一秒他便看见了仍是宴席上的那一身和服装扮、正倚着宅邸大门的蕾姆。

「蕾姆？你不是已经和一同来的客人一起回去了吗？」

「蕾姆原来的确是那样打算的，但最后还是任性地拜托夫人先走，自己一个人留下来了。也约好了之后再去归还这身借来的和服和发簪」

「我倒不是担心那个……不，比起那个还是更担心你啊。都这么晚了，万一...」

「谢谢昴君。不过有门卫好心地陪着蕾姆，所以不用担心啦」

看着昴小跑过来，蕾姆握住了他的手，像是为了让他安心一般露出了一个甜甜的微笑。

听了这话回头一看，已经成了老相识的门卫正冲他比起大拇指笑得爽朗。昴连忙向他点头致谢，一边考虑着门卫擅自放了赫鲁贝尔进来这事儿还是向女主人保密的好。

「那就好，不过为什么蕾姆要在这儿等我呢？有什么急事儿吗？」

「也算不上什么急事儿啦。蕾姆只是想啊，难得今天打扮得和平常都不一样，真想和昴君一起走回家啊」

「——」

「毕竟也很少有机会能穿上这样的和服……不可以吗？」

「不是……」

昴用空着的那只手挠了挠脑袋，难为情地避开了蕾姆的视线。也就是这时候他才看见门卫正透过手指缝里看着两人呢。果然明天还是去打他的小报告好了。

刹住了脑子里这些乱七八糟的想法，昴仔细地回味了一下这叫人脸红心跳的滋味，这才说道。

「蕾姆能这样说我真的很高兴。不过都让你一个人说完了我可就挂不住了啊……我也想带着我的娇妻四处炫耀一番再回家。谢谢你」

「好。那就请让咱们整个城的人都知道，蕾姆是昴的专属吧」

「那范围也太大了吧！」

昴着实被蕾姆的想法吓了一跳，随即便冲着门卫挥了挥手，两人一起踏上了回家的路。

暮色深沉的巴南街道被那浮现在云朵后的月亮和星光照得亮堂堂的，此外家家户户门前挂着的灯笼也流转出一片片光彩。而那灯笼中发出光亮的并不是魔法石，而是蜡烛的火苗。

走在身边身着和服的美少女，和夜空中的微小光芒相映成辉的点着灯笼的街道——这给了昴一种自己不是身在异世界、而是迷失在了原来的那个世界的过往之中的错觉。

「——？昴君，怎么了？」

「想事情想得有点出神而已。虽然刚刚是说了想要向别人炫耀，但我想起来了，我果然还是那种独占欲类型的。我要在家一个人欣赏」

「这、这身和服是借来的东西，所以可不能淘气哦……？」

「可是，就摆弄那么一下下没问题的吧？」

「唔……要、要只是一下下的话……」

听了昴的淘气宣言，蕾姆羞红了一张小脸垂下头去。昴爱怜地凝望着蕾姆的侧脸，说了一句「不过说起来」作为开头

「蕾姆竟然会出现在派对上……应该说宴席吧。我还的确是吃了一惊呢。蕾姆现在也交到了能相互邀约着出去玩的好朋友了呢」

「可是蕾姆觉得，身为教师和临时监护人的立场上还是尽量避免这种关系为好。但是，的确是这样呢」

「是吗。那很棒嘛。看来咱们俩也总算是一点点地在这个城里安顿下来了呢」

一边这样回应着，昴脑海里浮现的是这一年来奔波辗转各地的不易。

就像前段时间找工作时和赫鲁贝尔也提及过的那样，直至两人在巴南定居下来，昴和蕾姆已经在卡拉拉奇搬了无数次家了。大抵也是因为一直没能找到合适的工作和住宅，而这次来到了巴南，总算是从这个难题里解脱出来了。

经过四处辗转期间认识的一个人的介绍，两人来到了巴南，得以认识了长屋管理人赫鲁贝尔，这才终于有地方可以安家了。蕾姆很快就找好了工作，而昴则苦于没有任何资格证而一度屡屡遭拒，但如今他离梦想中的正式上班族也就只差一步了，一切都在逐步走上正轨。

一帆风顺——总算熬到了用这个词来形容也不为过的阶段了不是吗。

「今天晚上过得真的是很充实呢。不仅这身和服被昴君夸了，还亲眼看到了近在咫尺的丈夫工作的模样，蕾姆可感触良多了呢」

「我夸的是蕾姆穿着和服的模样，可不仅仅是这件和服哦？而且呢，多亏了蕾姆找准时机来给丈夫补充能量，我现在也是一点儿也不饿了呢」

「因为那些菜都特别好吃，无论哪一样都想要昴君亲口尝一尝……」

「嗯，你能有这份心意我就很开心啦，我也就是爱你这一点」

其实在宴席开始前，昴也被女前辈们拉着莫名其妙地试吃了一堆菜，再加上蕾姆的投喂现在肚皮都已经快要撑破了。而现在唯一支撑着他的就是回到家之后的「淘气」约定。

「而且呢，这次总算也和昴君的那些同事们打了招呼，拜托了他们一定要多多关照昴君」

「明天肯定要被大家调笑了啊……」

「——？」

本来在那些前辈眼里就像是玩具一样的存在，再加上这次自己的新娘向她们打了招呼，她们不兴奋过头才怪。一想想明天上了班同事们的态度，昴就立刻有点害怕起来。

「——」

两人间没多大营养却饱含温馨感的对话突然就戛然而止了。然而，这沉默并不是来自不快，而是自然而然产生于两人间的。

哪怕是没有言语，也不会觉得尴尬。两人之间的确有着恰到好处的距离。哪怕是这样沉默着，对两人来说也不是什么问题。

——因此，整个世界不自然地安静下来，也绝不是因为两人没有再开口的缘故。

「昴君」

察觉到这违和感，与蕾姆叫出这样一声几乎是同时发生的。

蕾姆加重了手上的力道，于是她紧牵着的昴也随着她的站定而停下脚步。昴不由地稍稍屏住了呼吸，正要看向她——却犹豫了。

那是因为他已经知道了，蕾姆为何突然停止了脚步，又为什么叫了自己的名字。

「——」

就在两人的正前方，有一个小小的人影正伫立在夜色四合的街道上。

那个人影背对着月亮，整个身子都陷在阴影里模糊了轮廓。不过从那比昴要矮、比蕾姆稍微高那么一点点的身高和纤弱的体格来看，能推测出那是一个女子。

那一身像要融进黑暗里的纯黑装束，却在膝盖处大胆地截断，那双踏在地上雪白的长腿更显得对比分明。

两手空空而衣着暴露的年轻女人——就从这一点看，简直可以把她视为乞丐或者妓女了。虽说这样说也有点那什么，可在大都市，哪一种都不是什么稀奇的行当。居无定所无家可归只能游荡在街上的穷人，以及那在暗巷里掩人耳目地拉拢客人的卖身女，都是理所当然的存在。

——然而，让人打消了这种臆测的是伫立在那儿一动也不动的女人的目光。


背对着满天星光，脸庞深藏在阴影里，但那双眸子，却闪烁着烂漫的光。而此刻那束光正带着异样凄绝的敌意，直指向昴和蕾姆两人——、

「啊——」

领会了那敌意的一瞬间，昴立刻觉得手脚发凉。

「——」

动不了了。在这浓烈的敌意面前，昴的身体已经完全脱离了大脑的掌控。他瞪大眼，一时间忘却了呼吸，双膝竟也开始打颤。而后——

「——你，在干什么呢」

低沉的，空气的轰鸣变成了疾风袭了过来。

而意识到那只不过是声音、只不过是对方发出的一声疑问却花去了长到令人绝望的时间。这般与这个世界格格不入的存在，就以一个异物的身份伫立在眼前。

是个女人，却又不是。有着人的形体，却不是人。那是可怕至极的，敌人。

「——你，在干什么呢」

恐怖的敌人再一次吐出了这疾风，这言语。

那是质问，是恫吓，是攻击，却又是慈悲。是了，是慈悲。

要说为什么，如果对方有半分杀意，昴他们就早已灰飞烟灭了。而之所以没有，也正是因为对方对敌人的慈悲。除此之外，还有些什么理由。

除了慈悲和怜悯，敌人一定还有着容昴他们活了下来的理由。

「你、你是……」

昴完全没法出声。也正因此，这不是昴的，而且来自站在身旁的蕾姆的声音。她紧紧地握着昴的手，用力到他几乎要喊痛，而也正是这痛感让他清醒过来。疼痛，让昴又和这世界紧紧相连。蕾姆也用着同样的方式在稳定自己的心神。

「——」

两人都被面前的敌人给震慑住了。

而在这排山倒海的压迫感之中，也只有蕾姆在拼死抵抗着想要拼出一条活路。昴也拼命说服自己必须得那么做。然而，他的心灵却无动于衷。

或者说，是没有“动”的气概。在这样的强敌面前，昴做不到。

——因为，曾一度从敌人手里逃出来的昴，是不可能再选择去应战的。

「……去死吧」

他怕了。

就在他得出这个结论的瞬间，敌人突然给出了再也清楚明白不过的判决。

下一秒，那升腾而起的压迫感已经像是火烧火燎一般地爬上皮肤，敌意渐渐升华成了杀意。

风吹起来了。挟卷着这个季节独有的温吞的晚风，如同要温柔地抚慰上身体——

「——危险！！」

就在那眨眼间变得致命的风掠过之际，蕾姆一把抱住昴飞跳到一边避开了。那一刹那，两人原本的位置已经被削平了。就像是被猛兽的血盆大口吞噬了一般，整个空间都被削掉一块。

要是两人没能躲开，此刻也就没命了。这也毫无疑问，正是眼前这女人的杀意。

「咻——」

「去死」

看到一场恶战已经无可避免了，蕾姆试图使出攻防兼备的招式。然而，对方一出手却如同疾风一般迅猛。风的利爪接连不断地袭过来，蕾姆一时间只得专心躲闪。

「唔、啊——」

此时此刻和服反而成了帮倒忙的存在。那长至脚踝的裙裾看起来优雅，却束缚了行动力。就算再怎么可劲儿躲闪，总会有中招的一次。情势不断恶化。

「去死，去死，去死，去死，去死」

杀意愈发浓重，伴随着那最简短的两个字如同吟唱一样接连不断地迸发出来，堵住了退路。

抱着昴的蕾姆也没法跳得更高了。不过真要说起来，跳得越高也就越容易成为狙击目标。而蕾姆有意识地朝着人多的地方逃，也是怀疑女人对死也有畏惧心，想要尽量拖延时间——。

「——唔」

蕾姆拼命地转过头，为了这无比渺茫的一线生机负隅顽抗。

而被蕾姆抱在怀里，随着跳动的冲击力被甩得七荤八素昴也没法再动弹分毫。眼看着敌意变成杀意，杀意已经成了实际行动，这时候就连虚张声势的力气也尽数被磨灭了。

明明心里知道不能再束手就擒，不能再拒绝思考，不能再眼睁睁看着事态这样下去了。

「去死」

而女人却风轻云淡地连身形都没动过分毫，只是反复吟唱着死亡的篇章。

「去死」

风的利爪席卷了天空，席卷了大地，席卷了整条街道。

「去死」

就像猫在肆意玩弄无力反抗的老鼠一般，毫不夸张地说，两边的实力差距就是大到如此地步。

能够逆转局势的一招，起死回生的献策，逃出生天的一击——、

「——」

然而，对方却没有留下施展这一切的余地。哪怕一丁点儿。

——不想死。

如同锁链一般将昴的身心重新连接起来的，就是这如同咒语一般强烈的一个念头。

「去死」

「至少……」

承受着应接不暇带着疯狂杀意的疾风，蕾姆拼命从喉咙里挤出来这样一声。然而戛然而止的话语的后续，昴已经知道了。她是想说。

「至少——就算只有昴君……」


「——」

绝对不行，不能让她这样下去了。为了展示决心，昴往自己牢牢抓着蕾姆的和服的手上加入了微弱的力道。如今能使出的全力，都倾注到了手指上。

就算两人轻易地就被外力分离，唯独心是绝对没法剥离的。

「但是……」

蕾姆也从昴的挣扎中察觉到了他的意图。然而，很显然，比起被杀意束缚了自由的昴，蕾姆对事态的严重性把握得更为精准。

会被逼到绝路上。眼看着这一刻就要来临了。那飓风的利爪行将夺去手脚，舔舐肺腑，吞噬掉生命。

而在那一刻到来之前，哪怕是多一秒也好，也想让所爱之人的生命再延长一点儿——、

「去——」

「——那可不行呀，好了。一切到此为止」

就在即将要把决心付诸行动的前一秒，只听得疾风撞到钢板上一样唐突的一声响彻云霄。

此前一直所向披靡无从抗拒的喰击，也终于生了变化。而不仅仅止于那一击，正面迎上那接连不断的喰击，就连漆黑的夜幕都仿若要被这高亢刺耳的声音给划破了一般。

「——」

而随着这异变，不停地吟咏着死亡的女人也终于停下了动作。抱着昴的蕾姆也停下了脚步，眨巴着眼睛想要弄清楚到底发生了什么事。

突如其来占据了当事人们的眼帘的，是一条颀长的身着和服的身影，此刻和服的下摆正猎猎作响——身边缭绕着的是从烟袋里一刻不停冒出的烟，站在两者之间的，正是赫鲁贝尔。

「赫鲁、贝尔……？」

「是呀是呀，我就是你们的阿赫啦。你真是冒了个大险啊，阿昴。刚刚我要没赶到可就不妙了啊。看蕾姆酱也是一脸做好了觉悟的表情」

「为什么，你会在……」

「啊，我也知道你们肯定很想知道，不过这还是等之后再解释吧。要不然……」

昴对这从天而降的登场一时理解不来，声音都打着颤。而相比之下赫鲁贝尔的态度却和平日里完全别无二致。与其说这能让人更加放心，倒不如说这只能是反而加剧了异常事态带给人的恐惧。

而压根没有顾及到昴他们这样的感受，赫鲁贝尔缓缓转过身来朝着女人那边

「而且这对手还相当棘手的样子」

话虽如此，赫鲁贝尔却一点儿没流露出紧张的样子，只是朝着敌人不紧不慢地迈开了步子。看着他的背影，昴几乎就要喊出来这也太鲁莽了。

然而——

「就交给赫鲁贝尔大人吧」

「蕾姆？但是，那可是……那家伙、她……」

是相当可怕的敌人。是拥有着超乎常识的强大力量的存在。这样一个对手，只让赫鲁贝尔一个人去的话。

昴想说的是，至少，为了保一条退路也应该拿出百分之二百的决心去战斗啊。

「——『礼赞者』赫鲁贝尔」

「……诶？」

「在整个卡拉拉奇的都市国家，都被尊为最为强大的存在——那正是赫鲁贝尔大人」

听了蕾姆平静的宣告，昴哑口无言，整个人都僵住了。然后他立刻看向了正一步步缩短着和敌人间距离的那个背影，只是拼命地吸着气。

那是在宴席上，自己曾为他斟满了酒的人。他现在正以散步一般悠闲的步伐，朝着敌人走过去。

「这实在……」

「——傻丫头，你说你这样阿昴会怎么想吧。你这是要做什么啊」

简直就像是说出了昴的心声，赫鲁贝尔用一副自来熟的语气冲着面前的女人喊道。

而昴和蕾姆两人被他护在身后，赫鲁贝尔朝着那女人迎面而立的姿势就像在说「要想动这两个人先得踩着我过去」一般，但从他本人的表情上压根看不出来这气魄。

甚至就像平日里在长屋午睡时一样，赫鲁贝尔的态度一如既往地淡定又洒脱。

而要说到态度一如既往，女人也是一样。一直站在原地纹丝不动的女人对赫鲁贝尔的出现也没表现出多大反应，只是浑身都散发着对昴他们铺天盖地的敌意。

要是有多管闲事的挡了去路，那就一同粉碎掉——因此

「去死」

无形的杀意幻化成风，挟卷成一个球形横扫过整个空间——一记喰击冲着赫鲁贝尔直直招呼过去。那是让人毫无招架之力，毫不留情地将对手逼上绝路的致命一击。

而要想攻破这一招，就只有一个办法——把它截杀在半路上。

「——」

只见赫鲁贝尔把手伸进和服，以让人眼花缭乱的速度冲着对面扔出了什么东西。而那以普通人的眼睛根本跟不上的高速飞出去的东西在半空中和风的利爪迎面撞上了——于是这一击非但没有伤到赫鲁贝尔的一根汗毛，反而受了阻作用到了毫不相干的地方。

「别以为眼睛看不见的招数我就应付不来了。我的鼻子可是相当灵的」

「——」

「啊，但是可别误会啊？我可不是犬人而是狼人，这一点就很重要啦」

冲着第一次见面的陌生人就喊出这些叫人摸不着头脑的蠢话，女人当然是不可能反应过来的。但只见她缓缓地转过头来。

「哟，这家伙总算愿意看我一……」

「去死」

「——哈」

毫不留情的一记猛击再度被赫鲁贝尔用同样的招数给抵消了。然而，这一举动却成功使得女人杀意的矛头所指发生了变化，现在火力全都集中到赫鲁贝尔这边了。

「去死，去死，去死，去死，去死」

狂暴又毫无章法的杀意之风连珠炮一样袭过来，赫鲁贝尔双手齐上阵一口气把它们都截杀了。成功消灭第一波进攻，只听得赫鲁贝尔「好嘞」地一声轻巧地拉开身形

「看你对我这么感兴趣，那就如你所愿吧！」

「去——」

「哼哼。——你想让哪一个我去死呢？」

「——」

穿着草鞋的两只脚蹬在街道上，只见赫鲁贝尔的身形开始朝着左右大幅度晃起来。他脚下那敏捷又变幻无穷的步子一时间竟让人眼花缭乱。不一会儿，赫鲁贝尔的身子便起了诡异的突变——

「来呀来呀」「你喜欢哪一个我呀？」「我可愿意为爱奉献了呢」「我有点儿大男子主义就是了」

「——什么！？」

面对这难以置信的一幕，并非那女人，反倒是被护在身后的昴发出了惊愕的一声。

不过这也无可厚非。谁也没法一下子接受眼前这般光景——四个赫鲁贝尔站成一排、异口同声地冲着对面嚷嚷着。

「顺带一提，别以为这样一来我的力量就削弱成四分之一了啊。成了四个人，力量倒也增强了四倍呢」

「我实在太想要几个兄弟了，天天缠着*乞白赖才换来的哪」

「对不住了，我胡扯的」

「其实是从镜子里给拽出来的啦」

「对不住了，这也是胡扯的」

一边惬意地吸着烟袋一边抱着胳膊，四个赫鲁贝尔轮流叽叽喳喳地说着。

「——」

与其说增殖，倒不如说是分身。看到了这一幕，女人行云流水般的动作头一次呆滞起来。

这样一来，就算是连环击也未必能对付得了战斗力增加了四倍的赫鲁贝尔了。她那无形的攻击眼看着就要毫无用武之地了，反倒有可能要遭受惨痛的反击。

然而女人此刻残存的理性还能不能让她意识到这一点，却也是个未知数——

「去死」

「……我说你，除了那一句就不会说别的了？看起来你家里的情况相当复杂啊」

稍微一屈膝，女人纵身飞跳起来。那轻盈的身形在紧挨着的屋子的屋顶上翻飞着，赤裸的双足下碎裂的是一片片青瓦。她就那样居高临下地俯视着赫鲁贝尔他们，一双眸子里的精光丝毫未减，月亮衬在她的身后，整个人都散发着超乎寻常的凄绝之美。

昂首挺立在地上的四个赫鲁贝尔同融在月光的阴影里的黑衣女人怒目而视。

这一幕甚至让人觉得时间已经停止了流动——、

「——蕾姆！？」

打破了这胶着状态的不是他们俩的任何一个，而且一直在身后只能默默观战的昴。

抱着怀里突然精疲力尽像要昏过去的蕾姆，昴发出了惊慌失措的一声喊叫。赫鲁贝尔立刻回过头去。

趁着这混乱局势，女人的身形一晃就要消失在漆黑的夜空中——、

「呵——！」

然而，剩下来的三个赫鲁贝尔却不可能眼睁睁放她逃走。

三道袭击从三个不同的方向冲着女人逼近，其中两发都尽数被疾风给挡住了。然而，那绕过一个优美弧线的第三发却巧妙地钻了空子，赫鲁贝尔投掷出去的道具——忍者的飞镖直直冲着女人纤细的腰部刺了过去。

「——！」

女人负了伤，却只发出了一声微弱的呻吟便逃跑了。

「——」

调动了敏锐的听觉，赫鲁贝尔留意着女人消失掉的那个方向，仍是没有放下警戒。她也有可能是想要混进黑暗中，再来个出其不意的偷袭。然而过了一会儿，几乎已经可以断定醒悟到自己占下风的女人是真的鸣金收兵了。

赫鲁贝尔对这结果无不满意地哼哼着

「那好吧，暂且就一发收手好了。比起这个……」

「赫鲁贝尔！阿赫！蕾姆她！」

听了昴拼尽全力的呼喊，赫鲁贝尔总算是飞奔到了昴他们身边。

与此同时，他的三个分身突然如同幻影一般倏地消失不见，又变成了原来的一个。

然而，这会儿可没工夫去感叹这神乎其神的景象了，昴只是一个劲儿地呼唤着瘫软在自己怀里的蕾姆。

「她是不是中了那黑衣女的招儿了？」

「我检查过了！但是，她全身上下没有一处伤痕！就这样突然晕过去……」

的确是经历一场不小的骚动。然而，蕾姆并没有受伤却也是可以肯定的。昏过去也是一点儿前兆也没有的。女人刚飞身逃上屋顶那会儿，昴以为她肯定是要使出什么招数的。

然而，招数倒没有，反倒是蕾姆突然就倒下了。这是——、

「是被下了什么蛊吗……有点儿发烧。虽说听起来可能不大现实，但是也有可能是生病了」

「——！」

「你摆出那什么表情我也是理解不能啊。就由我来背她回长屋……」

「不，不用了，我来……我来背！我来带她回长屋……」

一把拦住作势要伸手的赫鲁贝尔，昴在心里痛斥着自己直打颤的双腿，一边抱起了蕾姆。而听了昴的话，也就那么一瞬间，赫鲁贝尔细长的眸子里闪过了一丝沉思。

然而，他立刻就道了一声「我知道了」又深深地点了点头，

「那好，就拜托阿昴把蕾姆酱带回长屋。我去请术师，咱们在你们的房间里集合。你记着要走灯火通明人又多的大路啊」

「好，有劳了！」

完全没有任何异议，昴抱着蕾姆猛地冲了出去。那拼死一搏的模样加上不断煎熬着内心的焦躁，使得他的双腿像是有源源不断的力量。看来他完全可以一口气跑到长屋。

望着那不断远去的背影，赫鲁贝尔深深地吸了一口手上的烟袋，

「不管怎样……不管怎样……嘛」

狼人缓缓地吐出口中的烟，为了去寻那术师，他开始在深夜的街道中飞奔起来。

3

——都是，我的错。

「呼、呼……」

——是我的错。我的错。我的错。我的错。我的错。

「——！」

——是我的错！！

「呼……！」

睁大了眼跑得上气不接下气，昴满脸通红地往长屋飞奔。

抱在怀里的蕾姆像是完全没有重量一样。明明抱了一个人肯定会影响跑步，但体内沸腾一般的血液犹如岩浆一般，那烧灼的感觉不允许昴停下来哪怕一秒。

「——」

用尽了全力一个劲儿往前跑。这种情况下哪怕是顾及到怀里人儿的感受想要降低颠簸的强度，也没法和速度两全。这时候怀里的蕾姆肯定不可能睡得安稳。然而，失去了意识的蕾姆却全无反应。这一点更加剧了昴内心的恐惧。

蛊或者病——赫鲁贝尔的这般猜测，让昴的心脏被名为不安的锁链五花大绑捆了个结结实实。

对于那突如其来从天而降的黑衣女的恐惧，此刻已经完全消失殆尽了。

与眼下相比，哪怕是承受了多大的敌意也好，完全暴露在杀意下无法招架也罢，这些都是小事儿，都是微不足道的事儿。

比起此时此刻，这个瞬间，怀里最最珍贵的少女还生死未卜之际——

「——该死！」

忍受着内心的焦灼，昴却不能直接走最短距离，他拼命飞奔过一条条人来人往的街道。从那女人出现的诡异的地方跑出两条街这样，眼前呈现的便又是平日里不能再正常的风景了，走在街上的行人们纷纷朝着昴这边投来了好奇的视线。

神色大变，抱着一个少女飞奔在人来人往的大道上的男人。这一路过来竟然没有被“正义感”满满的热心肠给拦住，也着实算个奇迹了。

然而，昴想要的并不是这样的奇迹。如果现在能让他碰上奇迹的话，他只有一个愿望。

「求你了，一定要让蕾姆……」

无论如何，一定要让蕾姆平安无事，这是他发自肺腑的请愿。

只要她还能再睁开眼，再一次呼唤着我的名字，再一次对我绽放出笑颜——他就再也别无他求了。

要是说在事发时无能为力束手无策的昴也拥有傻傻地祈求奇迹的权利，那么他只想要回他的蕾姆。只要这样，只要这样就足够了。

「——」

心中不断地向着上天苦苦地祈愿着，昴总算是抵达了长屋。他硬是用脚踹开横向开合的门，摸黑把蕾姆安放到房间里的榻榻米上。也顾不得擦一擦满头满脸的汗，刚开了灯就连忙铺好被子，再把蕾姆抱到上面。

「蕾姆，蕾姆……你答应我一声啊蕾姆……」

再怎么呼唤，蕾姆却只是痛苦地吸着气没有丝毫回应。昴一脸痛苦地伸出手，轻轻地帮她松开了和服的腰带、脱下了振袖。借来的这身和服已经东一块西一块地绽开了口子，插在头发上的发簪也不知丢去了哪里。

那个穿着一身华丽的和服浅笑盈盈的蕾姆，就如同一个虚幻的梦一般。

「蕾姆，求你了……」

打来了一桶水，昴用浸湿的毛巾仔细地擦着蕾姆的额头和脖颈。他可以感觉到从蕾姆额头传来的异常的温度。然而却无法分辨那究竟是低烧还是高烧。昴也还没从刚刚的一路狂奔与持续的精神紧张中缓过来，他自己的体温也就不正常。

现在昴只得翘首以盼赫鲁贝尔能带着术师尽快赶回来，哪怕是早一秒也好。

如今，昴依然什么也做不到。

「蕾姆……」

他只能紧紧握着裹在被子里的蕾姆的手，感受着少女纤细的指节，倾注了自己全心全意的祈愿。

你一定不能有事儿啊。求你了，睁开眼睛看看我好吗。只要你平安无事地醒过来，就像什么也没发生过一样再一次对我展露笑颜，再呼唤我的名字——

「——」

也不知这样在心里祈求了多久，当身后的门发出一声轻响之际，昴已然浑然忘我了。那是门被打开的声音。一定是赫鲁贝尔带着术师回来了。

昴满怀期待地转过头来，正要脱口而出「拜托您救救蕾姆」之际——

「——哈？搞什么嘛，瞧你那副凄惨的表情。我可是看不下去了啊？」

悠然自得地倚在门上，女人抱着双臂用一副满是侮蔑的语气说道。看清了来人的模样，昴的大脑在那一刻，完全冻结了。

那是一个身着纯白和服的女人。那纯白的没有一丝污垢的装束，前襟被拢到左前方，让人不禁联想到象征着死亡的寿衣。只是，那和服的下摆刚好在女人膝盖上方就被截断，毫不吝啬地展示出她纤长优美的双腿和那雪白的肌肤，一点儿也看不出死亡的阴影。

那一头铂金色的短发剪得参差不齐，那双狭长而锐利的瞳眸呈现出幽深的蓝色，加上那相当撩拨人的五官，造就了眼前这超凡脱俗的美丽容颜。

那是丝毫没有矫饰，正是源自于不协调而产生的别样的美。就好比野生动物们恣意地献出自己最美的一部分拼凑而成的，纯属偶然成就的美——并不拘泥于美的价值，只是忠实地将美再现出来的超自然的艺术品。

没有人不会为这超乎寻常的美屏住呼吸，甚至觉得不现实。然而看到这样的一个人，让昴浑身僵硬的却并非她的美丽。

虽说有点儿模糊了，但他仍然记得那张脸。那也是，存在于不久前的记忆中的——

「喂喂？我都纡尊降贵主动和你搭话了，你有在听吗？」

「你、你是……」

「什么嘛，这不是会说话吗。别这幅样子了成吗？一会儿无视我一会儿又故作惊讶。毕竟嘛」

听着昴几近颤抖的声音，女人先是瞪圆了眼，随即便把双手交叉到胸前，而后，从唇角勾起一抹淡薄的笑意——那是嗜血的猛兽一旦发现了猎物时便会露出的、近似恐吓的狰狞的笑。

「——要是在我亲自动手之前就让你们死翘翘了，岂不是坏了我『死神』的名声吗」

「——！」

就是这个女人——为了再度发起对这个曾一度要置自己于死地的攻击，昴猛地弹了起来。

他一把抓过放在蕾姆枕头边的水桶，不管不顾地狠命冲着女人砸过去。他当然没指望着这能给女人造成哪怕一丁点儿的伤害。只是，哪怕能牵制住她的行动也行。而事实上，看着飞过来的桶和四溅的水花，女人也的确一脸不快的神情躲到了一边。

「嘿，啊啊啊——！」

紧接着，昴像是要一把抱住女人的腰一般，弯下身试图飞扑过去。只要把她一把放倒在地、再跨坐到她身上就会有一线胜机。他要使上浑身的力气去把那纤细的脖子给拧断。也让她瞧瞧他的厉害。就凭着现在的决心和怒火一定能很轻松地——、

「——你也不能看我可爱就一把抱上来了吧？」

「啊——！？」

放低身形旨在攻下对方腰部的一声呐喊戛然而止。女人轻巧地一闪身，用右手一把拧住弯着身子的昴的后颈，顺势就一发力把他给按倒在地。面门一下子就磕在坚硬的地板上，昴的视野里几乎要蹦出火花来。那般纤细的手腕竟也能爆发出这么大的力气，昴的整张脸都要被压得不成人形了。

昴死命地咬紧牙关，想要通过一个鲤鱼打挺从这被扣在地上的劣势中解脱出来。那飞跃而起的脚踝瞄准了女人的头部，却被她另一只空着的手不耐烦地一把挥到一边。然而，只要分散掉她一点点注意力也就行了。昴一把拧转过身子，硬生生地扯开女人钳制住自己脖颈的手，跳了起来。

「唔哇，满身都是汗……我的手都被你弄脏了！？」

「谁管你、啊！！」

昴冲着正甩着右手皱着脸的女人再度袭了上去。目标仍然是执拗地锁定住了对方的下半身。总之，都站着的时候昴是没有任何希望能占到上风的。现在他只想把女人给推到长屋外面去，好让蕾姆远离这个危险，哪怕是一点点也好，就算只是一道门也好。

「——嘿，呀啊！」

这下昴的气势赢了，女人还来不及反应就被他抱住了腰。昴使出吃奶的力气扣住她的腰，顺势一把将她顶到门框上，成功地把两人一齐带到了屋外。紧接着正要立刻翻身跨坐到她身上扳回一局之际，

「给我适可而止！」

就在快要撞到地面之前，女人用膝盖猛地顶向昴的胸口，那优美而分明的腿部曲线就像是要嵌进去一般，巨大的冲击力贯穿了昴的身体。他不禁倒吸一口凉气，听见自己全身的骨头都在咯咯作响。就算他再怎么想给手腕加上力道，人体的构造却不允许他那样做。

厮缠在一起的两人终于分开了，但倒在地上的却只有昴一个人。

他下意识地抠着土地想要站起身，头却被女人光脚踩住，把他摁在地上动弹不得。

「唔、……！」

「你可不能站起来哦，哈腰虫。要不空气又得受污染。汗又要乱溅了呢」

昴举起手臂，一把钳住了女人纤细的脚脖子。使劲儿握紧。而对方却纹丝不动。女人从鼻子里发出一声不屑的哼哼，把轻轻抬起的脚又一次用力跺了下去。昴的脸马上就要变形了。两次。三次——、

「啊……」

「别碰我，变态。我可不是来和你做游戏的。知道了？你就给我老老实实睡觉去吧」

女人不放心似的又狠命跺下了一脚，昴彻底沉默了。看到昴瘫软在地上，身下绽放出血色的花朵来，女人满意地转过身准备再回到长屋里。

她说了，自己不是来找昴玩儿的。也就是说，她的目标并不是昴——、

「——你要干什么？」

「——」

面门被撞得一塌糊涂，鼻血流了满地，昴却仍旧死死地抓住女人的脚腕不肯松手。她雪白的肌肤粘上了泥土和血，煞是显眼。只见女人瞳孔里的温度骤然冷下来。

「给我放手」

女人的要求简明扼要。而此刻昴呼吸紊乱，说不出一句回答的话。

他只是顽固地用另一只手也伸向了女人的脚腕处，表明了自己的意思。

「我说……」

女人撩了一把自己的头发，用几近呆愣的眼神看向死也不肯松手的昴。而后，伴随着一声叹息，她用膝盖狠命撞向那满脸是血正斜睨着自己的男人。

「都说了让你放开了」

下颚承受了女人膝盖猛烈的痛击，力度大到大脑几乎都要在头盖骨里跳起舞来一般。不仅是脑震荡，昴觉得他的意识也即将消散了，他的血再次从鼻腔里喷出来飞溅到了女人的衣服上。

他彻底瘫倒在地。然而，那手却仍旧没有松开。就那样钳着女人的脚，绝对，不让她靠近长屋一步。

「会死的哟」

「咻……」

昴极其不情愿地左右摇了摇脑袋。疼痛，超乎寻常的疼痛，立刻从头部倾轧到四肢百骸。

已经被撞得面目全非的脸，持续受到暴击的身子，被膝盖狠狠顶了一记的下颚，被超出人类极限的暴击彻底打垮的全身，都在同一时刻奏起了疼痛和无能为力的大合唱。

「——」

濒临绝境的警报倏地敲响，在『死亡』这个威胁逼迫到眼前之际，巨大的恐惧让昴手脚发凉。视野不知是被血还是泪模糊了，颤抖不可抑制地愈发剧烈。

死亡，近在咫尺。而此刻，昴捉住不放的那女人就正是死的化身。是死神。

『死』是可怕的。叫人心生畏惧。昴十分惧怕『死』，比这世上任何一个人都要怕。

这时候乖乖听女人的话，向她求饶才是正确的。要是想要规避『死』，想要逃避『死』的话。

但是，但是，但是，阻止了昴那样做，毫不留情地推翻了这个想法，让他没法松开手的是——

「——你是阻挡不了我的，杂碎」

昴的努力终究只是徒劳，女人再次迈开了脚。她就那样拖着匍匐在地上的昴，就像在说自己压根没有把他的存在当回事儿一般，也没有去踹开他，就这样一路走向了长屋。跨过台阶，踩着榻榻米，一路直奔蕾姆的所在地。

「哈、啊——」

昴试图咬住榻榻米，想要硬生生地扯住女人。然而榻榻米一下就和地板分离了。他试图伸出脚，用腿弯勾住柱子，但哪怕用尽全力也一下子就被扯开了。昴拼命地想要抠住拖在自己身后的榻榻米来反抗。负隅顽抗。

「你这家伙还真是难缠。一点儿不干脆。你看你自己那副模样不觉得羞耻吗？」

「唔唔唔唔！ 唔唔唔唔！！」

「太丢人了！丢人丢人丢人！简直不堪入目！不像样子！你是傻子吗！？」

劈头盖脸的痛骂和如雨点般的拳脚落在身上，但即便如此昴还是像个倔强的小孩子一般顽强地摇着头。哪怕是流尽了最后一滴血，牙齿也被打落，手脚都被扯断，昴也要阻挡女人前进的脚步。

就连女人也为这死也不肯放手的态度焦躁地连连咋舌——、

「就算说是报应也太叫人烦心了吧！我只不过……」

那美丽的脸庞扭曲成一团，女人拖着昴总算是来到了被子旁。而后，她俯视着已经沉沉睡去的蕾姆，向她伸出手去。

要是那只手真的碰到了蕾姆，那这沉睡便会迎来最坏的一种结局。想及此昴不禁发出一声悲切的哀嚎——下一秒，女人的动作就停下了。

「——啊？」

女人一时僵在了要伸出手去的那个姿势，惊愕地张着嘴。下一秒她皱起了眉毛，凝神望着正痛苦地呼吸着的蕾姆。自上而下，仔仔细细地。

不知道女人究竟是怎么了，昴不由得咽了一口带血的吐沫。

「你，要做……」

「啊！哎呀呀！这算什么事啊！这可不行啊！我不能这样！」

「——！」

下一秒就只见女人突然爆发了，她胡乱地连连咋舌粗暴地踹着地上的榻榻米。然后一把甩开被自己的诡异行为吓得目瞪口呆的昴，纵身跳向房间另一头。

「糟……」

一时大意让那女人挣脱了，昴打心眼里后悔自己的失策。他立刻就要从榻榻米上站起来再次钳住女人。然而还没反应过来就被女人的光脚一下子踹上了面门。

「唔……」

「给我老实点儿。真是够了，臭男人还真是难缠啊」

女人猛的一记飞脚硬是把昴的呐喊堵在了喉咙里，下一秒她却呆呆地盯住了瘫倒在榻榻米上的昴。

而后她指着自己形状姣好的挺拔的鼻梁，

「你的脸变这么丑了耶。这还能治好吗？」

「——」

「人类就是不方便。你们一旦受了伤就得留疤啊」

没头没脑地说了这么一句话，女人便一脸嫌恶地来回看着昴和蕾姆。从女人的眸子也可以看出来，她的情绪还非常不安定。正因为知道这一点，所以必须得站起来制止女人。然而，身体却压根不听使唤——

「时间到了啊。嘛，算了」

「——」

昴感觉浑身都被钝重的无力感包裹了起来，而女人却压根没有再管他了。女人嘀咕了这样一句，而她的视线也不是朝着昴他们，而是朝着那大门已经快要摇摇欲坠的入口处。紧接着，女人也没再对昴他们出手，只是扔下了这样一句话就冲着外面——长屋外面消失不见了

「现在你就只能咒你自己的运气不好了。就瑟瑟发抖地给我忏悔去吧」

昴说不出一句能叫住她的话，也不知道她最后这句话究竟是什么意思。

他只得看着自己的鼻血又一次濡湿了榻榻米，目送着女人远去的背影。

一时间房间里静悄悄的，只能听到两个不同的痛苦的吸气声此起彼伏——蕾姆和昴的。

「——阿昴？情况还好吧？发生什么事儿了！？」

就在这样一片狼藉中，赫鲁贝尔终于姗姗来迟。

听得飞奔到眼前的狼人紧张的声音，昴只是艰难地动了动被血塞住的口鼻，喘息一般地说道

「……蕾姆、就、拜托你、了」

刚对着紧紧盯住自己的狼人说完了这句话，昴的意识就一下子消散了。

4

「这下就姑且算是处理好了。接下来要好好休养一段时间啊」

说着，年老的治愈术师将昴脸上最后一丝血迹也给擦得干干净净。

赫鲁贝尔给带回长屋的这位老人，是在整个巴南区也算得上数一数二的治愈术师。老术师一看到昴这已经半死不活的模样，就立刻麻利地为他实施了急救处理。

也多亏了他高明的医术，昴的满目疮痍的伤口多多少少都愈合了，那残留在鼻腔深处一下一下的钝痛也都减轻不少，咬咬牙也就能无视了。这样一来，至少就可以站起来走动自如了。

「阿昴怎么样了啊？还有救吗？还是快不行啦？」

「也就颚骨咬合的时候，还有全身上下的关节都痛得够呛，命总算是保住了。谢谢。……谢谢，只是……」

「等等等等？其实阿昴一心想要我们先救蕾姆酱的心情我也是明白的啊。只是，看到当时你的那副模样，再怎么也没法把你先晾在一边」

赫鲁贝尔无奈地耸耸肩，抢在还在支支吾吾的昴前头迅速发声，把他的不满都堵在了嗓子眼里。

赫鲁贝尔一回到长屋，就看到昴瘫倒在屋子正中央，流出的血都染红了身下整片榻榻米。他从牙缝里挤出那简直就跟遗言一样的一句话之后就立刻不省人事了。

而再往里面一点就是裹在被子里、沉沉睡去毫发无损的蕾姆。真要以紧迫性来判断的话，很遗憾，还是昴要更胜一筹。

然而即便如此，昴却仍旧希望蕾姆能够比自己更早获得救治——

「当然不是说蕾姆酱变成怎样都无所谓。可是，也不能眼睁睁看着阿昴这样下去啊。这是我和大夫两人公正地权衡了一番后的决定。之前算是欠了我一份人情吧？用这个来抵一下，就原谅我吧」

「要说人情……」

从让昴和蕾姆留宿长屋安居下来，到刚刚紧要关头把两人护在身后，再到现在救了两人的命——欠赫鲁贝尔的人情已经多得数不清了。更何况他还这么照顾自己的情绪，昴的脸皮还没厚到能让对方用这恩情来抵消“犯错”的程度。

「我知道了。比起这些，大夫，蕾姆就拜托您了」

「这里就交给我了。你们俩在这碍手碍脚的。到外面去」

昴郑重地低下头，而老术师只是冷淡地应了一声挥挥手。昴和赫鲁贝尔依言走向长屋外。半路上，牵扯伤口引发的阵阵痛楚使得昴打了趔趄险些摔倒，赫鲁贝尔连忙伸出自己颀长的胳膊扶住了他。

「哎呀呀。你可得小心点儿啊。阿昴，你这伤好也才两分钟而已。」

「也不用担心成这样啦。……不过，这次你真的帮了我们大忙了」

「平日里率直的阿昴这次也逞起强来了啊。不过，你说要谢我我还真过意不去。毕竟你们会在长屋里被偷袭，也是因为我一时大意了没有考虑周全」

两人好不容易来到长屋外那一张长椅上，并肩坐下来。赫鲁贝尔点上了烟袋，把吸进去的烟朝着夜空又吹了出来，如是说道。

「我没想到她竟然还会再趁虚而入。我还以为她吃了我那一记至少要好几天都没法动弹了呢」

「别说什么好几天了，这不还没到十分钟嘛就又见面了」

「说老实话，我看到阿昴浑身是血地倒在屋子里的时候着实吓得不轻。当时我就在想，让你一个人回来真是太失策了，先把当务之急做了再回来救你好了」

「要真是那样，我也就等不到你再回来了」

「嗯哼，我刚想着要去报仇的时候，阿昴就开口了不是吗？本来我还以为你的心跳已经停了呢。以为阿昴你已经回天乏术了」

「……啊啊，这样啊」

「——」

赫鲁贝尔的视线从夜空转回了昴的侧脸。虽然只是短短几句话，也能明明白白地听出来，现在昴的心思压根儿就不在这里。事实上，昴此刻的注意力并不在和赫鲁贝尔的聊天上，而是全倾注在了身后，在正在身后这间屋子里接受着治疗的蕾姆身上。

如果说是外伤的话，那根据自己的亲身体验昴是相当信任老术师的。然而蕾姆的情况却并不是外伤。是生病了，又或者——、

「我也粗略看了一下，我想那应该也不是蛊。可以说和那些咒术之类的完全不是一回事儿。你就不用担心这个了」

「可是你又怎么能下这样的断言呢？」

「你想想啊，我可是咒术的专家啊。我可以给你打包票」

「咒术，专家……？这种话果然还是听听就好了」

「你对我的真实身份就这么个态度啊啊喂。不管怎么说，你现在就当做省去多余的担心好了」

赫鲁贝尔的话的确是相当有冲击性的，但昴却无意再和他就这一点讨论下去。当然也不是说漠不关心，只是在这种关头，他也实在关心不过来。

如果赫鲁贝尔所言是真的，那么威胁到蕾姆性命的可能性就又减少了一个。姑且不说这一点能不能让人彻底安心，但好歹是让昴暂且松了一口气。

就这样，接下来的一段时间都随着赫鲁贝尔吐出的烟雾，被风卷着一起静悄悄地流逝而过——、

「——久等了」

「大夫！蕾姆，蕾姆她怎么样了！？」

「安静点，这大晚上的，还有一个在睡觉呢。——我有话和你说。进来吧」

只从门里探出了一张脸的老术师朝昴招着手，示意他进去。昴压制着自己焦躁的情绪，为这莫名有些叫人不安的氛围咽了口唾沫，迈开步子慢慢地走了进去。

房间里仍旧是和那女人一场恶斗后惨不忍睹的模样。但从睡在最里边的蕾姆身上的被子来看，就足以感受到老术师无声的关怀。——只有那床被子被重新铺了一下，好让蕾姆睡得更安稳。

「那边的那个阿呆，把你的烟袋的火给熄了。会影响这小姑娘的身子的」

「平时也没见你说过什么啊。……好好好，我知道啦」

被老术师狠狠地瞪了一眼，赫鲁贝尔立刻老老实实地掐了火。他依然坐在长椅上稳如泰山，昴则迫切地挪到了牵动着自己内心的蕾姆的枕边。老术师也坐到了昴的对面，「那么」随着一声沙哑的开场白，

「首先从好事儿开始吧。这姑娘之所以会不省人事，并不是因为受了伤，也不是害了病。跟咒术也没关系，这一点你也从刚刚那阿呆嘴里听说了是吧」

「……是啊」

「也就是，没有一点儿异常」

「哈？不，可是她……」

听了老术师的话，昴难以置信的瞪大了眼睛，几乎就要问出来你在胡说些什么了。

就算说是没有任何异常，但蕾姆突然就倒了下去，在睡梦里也还在痛苦地吸着气也是无可否认的事实。而现在也不知是不是治疗有了作用，她的呼吸变得安稳多了。

「大夫，蕾姆可是突然就晕倒了啊。看上去还挺痛苦的模样。请您再仔细看看吧！」

「看来不止是那边的那个，你这小子也是个阿呆啊。你这结论下得也太早了，先听我把话说完」

「您老就别总是阿呆阿呆地叫了……」

「闭嘴，阿呆。现在我要跟面前这阿呆说清楚了。刚刚那算是好事儿对吧……接下来我要说的，更是一件大好事儿」

「更好的事儿？」

蕾姆一切正常，在这样一句叫人难以信服的话之后，老术师又会说出什么样的话来呢。昴默不作声地等着，那模样就像在说，接下来的这句话会成为判断老术师到底靠不靠谱的重要标准了。

而老术师看着神情凝重的昴，故意停顿了一拍这才说道。

「——是有喜了」

「哈？」

唐突无比的一句话使得昴愣在当场，情不自禁地喊出声来。

——石游喜乐，昴完全不知道这个单词是什么意思。是人名吗，还是地名啊？不管怎么说，肯定是昴不知道的，这异世界的专有名词。而这又是什么意思呢？

（注:此处是因为大夫说的是日本的方言关西腔，昴并非关西人故一时没有反应过来）

「那个，也就是说只要有了石游喜乐这个东西，蕾姆就能得救了……是吗？」

「喂，浪荡子。你看看，这怕是个比你还要呆的阿呆啊」

看到昴一脸凝重穷追不舍地问着自己，老术师一时间也一脸呆愣，不知所措地挠了挠自己的脑袋。在一旁的赫鲁贝尔听了老术师打圆场一般的话，就立刻反应过来了，只见他「不是啊」地嘀咕了一句，也挠着脑袋说道

「大夫您的说法的确也不大妙不是吗？叫人混乱也不奇怪啊」

「什么混乱不混乱的啊！？求你了赶快告诉我吧！蕾姆她到底……」

「哎呀呀，阿昴。不是石游喜乐，有喜了。我也得恭喜你啦」

昴一脸茫然地重复着，不是『石游喜乐』，是『有喜了』。

所以这个词的意思就是——、

「你的小媳妇儿有了你的孩子。」

「有了……是，是说怀孕了吗！？」

听了老术师的解释，昴为这出乎意料的状况受了不小的冲击，瞠目结舌。

怀孕了，有喜了，恭喜了——这三个词不停地在脑海里飞速盘旋，把昴折腾得晕头转向。

见昴一时间还没从混乱状态里缓过神来，老术师一脸不悦地转头看向蕾姆

「不省人事这一点暂且倒不用担心。孕妇一下子消耗了太多体力，身子跟不上了才会昏睡过去的。让她好好睡上一觉也就没事儿了。不过叫一个孕妇就这样累倒了也太说不过去了吧」

「毕竟蕾姆酱那么要强，和一般的媳妇儿一对比可以说是天差地别。而且今晚也纯属突发情况。不过话虽如此，也不代表咱们就能彻底安心了啊」

赫鲁贝尔小声嘀咕着，解释了蕾姆为何会消耗掉那么多体力以致晕倒。

诚然，今天晚上发生的事是纯属意外。总不可能三不五时地就能遇到那样不分青红皂白就要动手的劲敌。只是，就算如今也不能说是成功击退了那女人，只能说是她自己也不知怎的就莫名其妙地主动偃旗息鼓了。到头来，还是不能妄下断论，说这事儿已经平息了。

「但是，她也并没有取了阿昴他们的性命，哪怕这对她而言轻而易举。这也是事实，是吧」

正如赫鲁贝尔所说，在他回来之前，女人要是真想动手的话，他们就已经死了不知道多少次了。

当时那女人浑身上下散发出了叫人不由颤抖的恨意，她却没有把它变成实际行动，反而硬是给压下来了。这也是事实。也正因此两人才捡回了一条命。然而她究竟是何用意，直到现在也无人知晓。

「——阿昴，你还好吧？」

「……诶，啊」

看昴呆呆地愣在一旁也不说话，赫鲁贝尔敲了敲他的肩膀，看向了他的眼。这下总算是把昴的意识给拉回现实世界了，他的眼有了聚焦、倏地对上了狼人的视线。

被这突如其来的一连串混乱和困惑的感觉彻底压倒，此刻昴的脑子已经成了一团浆糊。

他这幅样子看在旁人眼里也是一目了然，赫鲁贝尔和老术师互相看了一眼，点了点头。

「阿昴，今晚我们也就不打扰了。看样子刚刚那女人也不会再来了。估计你也有话想说，不过还是等明天吧。……大夫」

「让你的媳妇儿安安稳稳睡一觉就行。今晚你也得好好休息一下啊」

「好，那就这样」

赫鲁贝尔和老术师轮流叮嘱着，而昴却只是沉默着像个玩偶一样机械地点着头。那异常缓慢的动作连赫鲁贝尔也看不下去了，他一把捉住昴的脑袋，把他的脸扳向蕾姆那边。

「让蕾姆酱一醒过来就能看到你的脸可就是阿昴你自己的职责了。好吧？」

「——。知，知道了」

又被叮嘱了一番，昴的眼睛这才呆愣地定焦在了一点上。满意地看着他漆黑的瞳孔中映出了蕾姆睡熟的脸，赫鲁贝尔和老术师默默地站起身，出了房门。

就这么一晚上，已经给赫鲁贝尔他们添了数不清的麻烦了。真说起来这时候应该起身目送两人离开的，但昴此刻却连站起来的力气也没有，当然那两人也没有让他送的意思。

将倒在一边的门板重新装了回去，两位可以称之为恩人的访客静静地离去了。

被单独留下的昴默默伸出手去，握住了蕾姆横在被子里温暖的手。

混乱和困惑，直到现在还在不停啃噬着昴的内心。虽说术师和赫鲁贝尔都让他好好休息，但他实在也没厚脸皮到能睡着的地步，责任心也驱使着他不能这样做。

他要等到蕾姆睁开眼睛，等到亲眼确认了她是真的没事儿了之后。只有确认了她的无恙，昴停滞的思考才能真正再度启动。

「——蕾姆」

轻轻地唤了一声她的名字，昴久久地凝望着陷入梦乡的少女那安详的面庞。

整个屋子里，就只剩下了昴和蕾姆夫妻二人轻浅的鼻息。

5

那之后，或许已经过了好几个小时吧。

蕾姆睫毛微颤着睁开眼的时候，天都快要亮了。

「……昴、君？」

黑夜渐渐褪去了颜色，天空越来越白，微弱的光透过窗户打进屋子里来。在这暗黑与淡青交织出来的光影世界里，蕾姆那鲜亮的浅蓝色瞳孔映出了温柔的光。

「——嗯。早安，蕾姆」

蕾姆一声犹疑不定、像是还未完全清醒的声音把昴的意识拉回了现实中来。

这几个小时，昴只是一动不动地凝视着蕾姆的睡颜，他的意识被名为停滞的漩涡吞噬得一干二净。

兵荒马乱的一天里，从叫人手忙脚乱的宴席，到回家路上突如其来的死亡威胁，再到回到家后伤势惨重的一番恶斗，以及最后老术师的那句话。这一切的一切都停滞在了脑海里，昴无法思考。

他感到这一幕幕在脑海里挥之不去，但他又像是在刻意逃避这些拒绝去思考。不管是哪一种，他能做的只是把等待蕾姆睁开眼这件事当作免罪符，拒绝给出答案。

然而如今，过了这么久，这免罪符也已经失效了。不得不直面现实的时刻，已经到来了。

「蕾姆，嗯嗯……」

蕾姆扑闪扑闪地眨了眨睡意朦胧的眼睛，轻轻地晃了晃脑袋。很快她就意识到昴正握着自己的手，开心地绽放出一个甜甜的笑。

「怎么啦，昴君。这...在蕾姆睡觉的时候也要握着手……」

倏地，那如同花朵般明媚的微笑渐渐地僵住了，蕾姆的眼彻底睁开了。终于跨过了梦和现实的那道门槛，意识和思考能力都回归了，昨晚的记忆鲜明地复苏了。

蕾姆被昴紧紧握着的手猛地一发力，她慌忙支起上半身，

「昴、昴君，你受伤了吗！？蕾姆当时突然就晕了过去，然后...啊啊，怎么会这样……」

「冷静一下，蕾姆。我没事的。伤……现在也没事了」

踌躇了一小会儿，昴还是瞒下了在长屋里发生的二次灾难。

要是天再亮一点儿，整个房间里遍布着的、昴遭受的暴力袭击的痕迹就会暴露无遗了。然而现在，在这昏暗的光线下还看不出那些。眼下只要搪塞过去就好。

幸亏蕾姆也还没从混乱的思绪中彻底恢复过来，毫无保留地信了昴的话松了一口气。

「那就太好了。要是那之后昴君有个三长两短蕾姆也……」

「说来也叫人懊恼，全是多亏了阿赫……赫鲁贝尔。是他把那可疑的家伙给赶跑了的」

「是这样啊。是赫鲁贝尔大人啊。回头可得好好跟他道个谢呢」

昴也不知道蕾姆究竟还记得多少，眼下看来她像是还记得赫鲁贝尔在紧要关头现了身。甚至一直到她晕过去之前的事儿，她都还记得很清楚。

她突然抿了抿唇，这才又接着说道，

「所以说，蕾姆究竟是怎么了呢……」

「呃呃」

「赫鲁贝尔大人突然从天而降，所以蕾姆正准备集中意念想要上前帮一把的。这之前的事儿蕾姆都还记得。但是，不一会儿意识就模糊了……」

用空着的另一只手摸上了自己的额头——那是鬼角会现形的地方——蕾姆颦住了她细长的两道柳眉。自己竟会这般突然地晕厥过去——然而这背后的原因，却是她想不到的。

「蕾姆还是第一次那样突然地就晕了过去呢……实在是，对不起」

「啊，哪里用得着道歉啊。反倒是我，一直要蕾姆保护……在那种危急的时刻却毫无招架之力……真是，太难堪了啊」

「怎么会，没有的事……」

蕾姆那充满了歉意的表情让昴的胸口一痛。他连连摆头，自己把自己给臭骂了一顿。

行动上的无能为力和胆怯都已经暴露在蕾姆面前了，再要让她看到内心的怯懦可就真的说不过去了。而此刻昴只想着借着蕾姆的罪恶感来拖延一下宣告那件大事儿的时间。

既然现在已经确认了蕾姆的安然无恙，那么思考就必须继续前进到下一步了——非这样不可了。

「蕾姆，听我说。其实，我们请了大夫来给你做了检查。毕竟你之前突然就不省人事...」

「——是」

读懂了昴眼里坚定的决心，蕾姆也像是有点神情僵硬地点了点头。

已经让医生给你做了检查，他一脸凝重地表情如此说道。蕾姆之所以会紧张也无可厚非。然而，现在昴却无暇顾及她紧张的情绪了。

犹豫良久，吞吞吐吐好几次，昴舔了舔干燥的嘴唇。而看到昴这样的动作，蕾姆闭上了眼睛，

「昴君，就请直接说出来吧。无论是什么结果，蕾姆都能承受」

「……啊」

「哪怕剩下的时日已经无多了也罢，蕾姆只要和昴君在……」

「——你有了我们的孩子」

昴打断了她的话径自说道。

「诶？」

已经做好了被告知自己得了重病的蕾姆不由得目瞪口呆。

她立刻张开眼，楞楞地看着昴。见状昴冲她点了点头，也顾不上嘴唇的干渴了，抛却了踌躇和犹疑再次重复道，

「蕾姆的肚子里已经有了小宝宝。——有了我，和你的，孩子」

「————」

确定了自己并没有听错，蕾姆依旧杏目圆睁，缓缓地用另一只手摸上了自己的腹部。从外面看来，还并没有什么变化。没准儿是误诊呢。毕竟这太不现实了。

蕾姆的肚子里，孕育了一个新的生命。是两人的，结晶。

「有什么症状了没啊？比如有哪里觉得奇怪的」

「偶、偶尔会觉得、有点儿低烧……不过、蕾姆还以为只是有点劳累了。毕竟好不容易在一个城市定居下来了，还以为是精神一放松身体就……」

蕾姆结结巴巴地总算吐出了一个完整的句子。

显然蕾姆已经察觉出了自己偶尔会低烧，但她却隐瞒了这一点。当然昴也不是没法理解她的心情。生活总算是安定下来了。然而，蕾姆不想因为自己的身体状况又给昴徒增担忧。

要是昴的话，肯定也同样不想让蕾姆担心的吧。

「蕾姆怀上了孩子……小宝宝。昴君和蕾姆的……」

「大夫说也正是因为现在和以前不一样了，才会晕过去的。本就是比以往更容易觉得疲劳的身子，再加上遇到危险状况精神紧绷着，自然就消耗了太多体力」

「抱、抱歉……」

「哎呀呀，都说了用不着道歉了嘛。该道歉的一直以来都是我啊」

昴这次又让蕾姆铤而走险，做了她如今没法做的事。

而对她的身孕毫不知情也不能成为正当理由。全是因为自己偏偏能力不足，却非要任性地带着蕾姆远走高飞，给她徒添负担。

到头来不只是日常生活，甚至还叫她遇上了那般危险的状况，和以前一样。

「——」

一想及此，昴自己都没法原谅自己了。这个紧要关头却束手无策的自己。这个就连阻止敌人靠近蕾姆也办不到，到头来还是因为对方的心血来潮才捡回一条命的软弱的自己。

永远只会给蕾姆带来伤害的，菜月·昴——。

「昴君你……嗯嗯」

「怎么了？」

蕾姆的言辞之间明显带上了踌躇的意味。看穿了这一点的昴，尽可能用自己最温柔的声音问道，想要解除她内心的不安。

现在昴只想让蕾姆远远地避开那些会伤害到她的一切。他只有这一个愿望。

被昴温柔的声音安抚着，蕾姆怯怯地开了口。

「昴君，是，怎么想的呢？」

「是指什么怎么想的呢……」

「蕾姆现在有了、有了……昴君的孩子，昴君你」

『是不是后悔了呢』——恐怕蕾姆没说完的就是这样一句。

看到蕾姆没能说出口的怯生生的模样，想到自己竟会蠢到让她产生这种想法，昴就像被雷劈了似的猛地颤抖起来。

妈的。蠢过头了。此时此刻，对着面前这个得知了自己已经有了身孕、有了自己的孩子的少女，肯定还有许多其他话该说的不是吗。明明有的，却只是蠢到一味自责。

「我」


反射般地吐出了一个字，却又马上哽住了。蕾姆温润的眸子真挚地直直地盯住昴，等着他的回答。

就因为一时冲动说出了违心的话就叫人没法原谅了。就当着蕾姆的面，此刻更应该认认真真地，让自己已经冻结的思考再次复苏，扪心自问。

——再一次在心里告诉自己，蕾姆肚子里的新生命，正是菜月·昴的孩子。

这是第一次，认认真真地向着自己和蕾姆间降临的新生命，勾画出自己的感情。

那是——、

「是这样的吧。——我，我这种感觉、是高兴吗」

「————」

「我、和蕾姆两个人的孩子……小宝宝就要诞生了。一想到这个，我就……」


昴老实地说出了最初的、的确是最初的感动。

有惊讶，也有不安。但是，内心的那股暖流，却压倒性地超越了这两者。从内心深处喷涌而出的这股暖意，这就是菜月·昴命第一次体会到的最真挚的喜悦。

能和自己如此珍爱的少女共同拥有了爱情的结晶，昴他，不能更开心了。

「——蕾姆！」

「唔啊！？」

昴任由着内心这翻腾的激动情绪支配着，不由自主地一把抱住了蕾姆。

蕾姆却被他唐突的行为吓了一跳，感受着近在咫尺的昴的体温，楞楞地眨巴着眼。昴将嘴巴贴到蕾姆耳边，恨不得把自己整个心意都给融进声音里，


「谢谢你，蕾姆。——谢谢。谢谢你，蕾姆」

「昴、君……」

「我，我实在是太开心了。我和，咱们的孩子……我们终于有了自己的家」

「——啊」

之前的种种不安全都烟消云散了，昴凭着内心的那股冲动吐出的这番话，却字字句句都是真心实意的。

他和蕾姆有了孩子。在卡拉拉奇，原本只是形式上向周围人宣布是夫妻关系的两人——如今，却已经成为了真正的家人了。

「唔，呜呜」

被昴紧拥在怀里的蕾姆也轻轻抬起手臂，环上了他的后背。两人坐在被子上紧紧相拥，蕾姆漏出了一声呜咽一般的声音。

那一定是，她内心那不断膨胀开来的不安，被昴真挚的言语给刺破了，彻底安下心来的缘故。

「谢谢你，蕾姆」

「不，不……不用，不是这样的。明明是蕾姆该向昴君……」

「谢谢你，蕾姆」

就那样相拥着，昴对着怀里呜咽不止的蕾姆反复地道着谢。他每说一次，蕾姆就觉得自己的喉咙里像是哽住了一般，热乎乎的泪珠争先恐后地从眼眶滚落。

自然而然地，昴内心的暖流也伴随着悸动一起涌向了喉咙，涌向了眼底，扩散到了四肢百骸，他开始微微颤抖起来。

「啊、哈哈、哈哈哈……」

趁着那股悸动变成眼泪，变成再也压抑不住的哽咽之前，昴掩饰般地笑了起来。而这笑声也跟着颤抖得不成样子，到头来，什么也没能掩饰住。

此时此刻，夫妻两人只想尽情地分享这上天恩赐的新生命带来的无尽的喜悦。

纵使那些不得不去思考的事儿，那些不安也好危险也好仍旧未曾消失——

「昴君，谢谢你。——蕾姆最喜欢昴君了」

因为，昴的感谢，蕾姆的告白，这一切都是再真实不过的存在了。

2

“——不过，刚才的事情真令我吃惊，直到现在心脏还狂跳不止呢”

“那个时候”

“真的给您添了许多麻烦呢”

在迎来黎明的大宅的某个房间里，昴和蕾姆两人正低着头站在那里。站在他们对面的，是正接受着他们的道歉并客气点头的赫鲁贝尔。

他将手伸进自己的衣服里，一边挠着胸口一边环视着四周，最后将视线落在了有着人形凹陷处和裂痕的房间墙壁上。那是昨夜还没有的痕迹。

“啊咧，这是怎么做到的？”

“夫妇间诞生了新的生命，为了确认那一存在而采取行动的结果……大概”

“非常抱歉。蕾姆大概也是有些混乱，所以没有好好地控制力道”

用毛巾不停地擦着脸的昴和低下头反省着的蕾姆这么说道。

直截了当地说的话，墙壁的凹陷处是昴猛烈撞击留下的痕迹，而让昴做出这么猛烈撞击动作的人正是蕾姆。在向昴传达了怀孕了的事情后，两人互相分享着有了孩子的喜悦，不久后就成了这样。

“因为昨天一直在进行着冲击性的展开呢，我想确定孩子的事情并不是做梦，就拜托蕾姆稍微用力地拍一下我”

“唔（萎靡不振的样子）”

“……嘛，没能那样死掉真是太好了呢。我也稍微有点要升天了”

如此评价着这对稀有品种的夫妇的炫耀恋爱史，赫鲁贝尔将视线从墙壁的凹陷处移开了。随后，他眯缝着的眼睛稍微睁开了一些。

“关于修理墙壁的事姑且先放到一边……”

“放到一边？”

“损失不是很严重，先听听我要说的话吧”

在榻榻米上盘腿坐下的赫鲁贝尔，嘴里叼着上下摇晃的烟袋开口说道。

面对着引入话题的那个人，昴稍微恢复了一点昨夜的紧张感。这些一连让他过于激动的事情并不是梦，蕾姆那饱含爱情的一击已经证明了。

也就是说昨晚赫鲁贝尔的行动，全部都不是做梦。

“直截了当地说，作为大宅的管理人，“永远的游手好闲者”是我的伪装姿态”

像是验证着昴的想法一般，赫鲁贝尔光明正大地表明了自己的事情。从昨夜开始一直持续着的，早上最大的事件即是他所为。而此时，看上去有些无情的赫鲁贝尔所眯缝着的眼里也发出了认真的光芒——

“不，我们现在正处于投宿的状态中，所以也是会有些畏缩的呢”

“可是并没有必要畏缩的啊？我并没有做不好的事情，而是保护了你们呢”

在表明了有所隐瞒的基础之上，赫鲁贝尔依旧用平常的语调回应着昴。飘然洒脱，遵从自己节奏这样的性格似乎更像是他的本性。即使突然像是转换角色一般地伪装成威严的口气说话会令人很困惑，但也因此能事先顺从地接受了那一点。

总之，昴一边整理着正在反省的蕾姆身上的棉被一边说道

“阿赫现在正在告诉我们一个被揭露的急剧冲击性的事实呢……”

“非常对不起，赫鲁贝尔大人。那个，蕾姆没有很清楚地察觉到这一点。”

“唉——！真是令人羞耻！我是那么粗俗的羞耻家伙吗！真令人羞耻！”

半睁着眼的昴和略显窘迫而低下头的蕾姆，这两个人的回答令赫鲁贝尔抬头望向了天花板，张大嘴巴十分夸张地发出了“这可真是件难事啊”的叹息。

“等一下等一下，即便你这么回答并叹息着，我也听说阿赫可是个很有名的人呢？不，即使你多少察觉到周围的反应，也丝毫没有要隐藏自己名字的意思，在这样的情况下因为暴露了而感到困扰，是你自作自受吧？”

“蕾姆也是，很早以前就听说过“礼赞者”赫鲁贝尔大人的传说……因此，最初您作为大宅的管理人报上名字时，我就认为您在试探我们”

“啊，真的真的是从一开始就暴露了呢。你们看，这可真是难为情呢”

“很难为情的”

突然插入这么一句后，昴事到如今才意识到他正站在两人的蚊帐外。

移居的第一天就意外遇到了最强的卡拉拉奇，蕾姆甚至对昴都隐瞒了这件事，她的疲惫究竟到了多大的程度呢。这条街的平静日常中，究竟掩盖了蕾姆多大程度的奋斗呢，对于无意识中所发生的这些事，昴感到非常得可悲。

“明明说出来会比较好，蕾姆，为什么你要一个人背负这些”

“昴……”

蕾姆一直都是这样，一直都是相比于他人更愿意牺牲自己。即使像这样和昴两个人一同生活，也会为了昴而牺牲自己。

所以这次也是一样，在事实明了之前都会一个人承担着。

“对不起。因为我不明白赫鲁贝尔大人的本意，而且……”

“而且？”

“因为昴很不擅长说谎，我不想大大咧咧的说出赫鲁贝尔大人的身份，使得你表明了态度从而刺激到了赫鲁贝尔大人……”

“真是很没有实际信用呢！”

久违地被蕾姆毒舌后，昴拔高了音量说道。面对那样的昴，蕾姆慌乱地摇着双手，说出了“啊，不是这样的”的话。

“蕾姆相信着昴。那种信任之深即使用言语也无法表达。但是，相信你，和让你去做做不到的事，这是两回事”

“这样下去阿昴会越说越悲伤的，就到此为止可以吗？”

蕾姆将说不尽的亲密和信赖，以及现实性的意见全都毫不犹豫地告知了我。

实际上，蕾姆的担心是正确的。如果她把赫鲁贝尔的别名告诉了昴，昴是没有自信能继续保持相同态度的。

只是，必须要确定那样的担心是否具有说服力。

“我有一个疑问，阿赫真的是最强的卡拉拉奇吗？没有同姓同名的人，或是同胞弟弟什么的吗”

“关于那个……很抱歉，蕾姆也无法明确地断言。”

“被那么道歉的话，我可是会无立足之地呢”

面对一无所得的昴所指出的问题，蕾姆的道歉令赫鲁贝尔感到很受伤。

“说起来，阿昴对我是最强的家伙抱有疑问吧？呀，我可是最强的。还是说，你过于中意的不是真正的我，而是平时的我呢？”

“刚才所说的并不是想让你感到不舒服，而是更为理想性的话。我只是希望强大的家伙能有与强大家伙相符的风格”

“这种悖论性的话就是在说我的坏话！”

面对昴的强词夺理，赫鲁贝尔意外地拔高了声音喊道。但是，即使道理被歪曲，卡拉拉奇作为最强的国家——四大国之一，也依旧背负着最强之名。

当然，人们也期待有能与这最强相匹敌的人。在鲁格尼卡王国，那位被称为“剑圣”的莱因哈鲁特·范·阿斯特雷亚似乎就是一位具有压倒性实力的强者。

“……或许这很令人感伤呢”

“虽然我不明白阿昴的说法，但我从以前开始就接受了这种做法了。清楚地说的话，最强这一头衔是不会束缚我的……我也明白只要通过正面决胜负使自己变强并挺起胸膛的话，或许就能很自满了呢”

赫鲁贝尔巧妙地摆动着鼓起的烟袋，使其前端吐出了烟圈。对于赫鲁贝尔的态度，昴皱起了眉头，歪着脑袋询问道：“通过正面决胜负变强是指？”

“我，是从暗杀者开始成为战士的，针对敌人的弱点进行战斗是我的得意技能。啊，关于详细的战斗方式的解说可是组织机密，这可是关乎我家族的存亡呢。抱歉，除我之外家族的大部分人都已经死亡了”

“那种全灭玩笑我是不会轻易传出去的，还有，暗杀者是指……”

“啊，或许那是从外国人那里传过来的呢。要说到暗杀者的话，就是那个哦，这个，该怎么说才好呢？是那个哦。要对那部分进行说明的话可是很麻烦的工作哦”

“完全没有具体的内容呢……”

对于赫鲁贝尔这欠缺要点的说明，蕾姆只好作罢。没有顾及那两个人，昴的头脑中已经正确地将暗杀者当成了“忍”——也就是说，将其同“忍者”相连结了起来。

在和风中形成的日本式文化，用刀和筷子将其集结，令人佩服的忍者。多亏了这样，昴很容易理解，但也正因为如此，所以赫鲁贝尔表明的意思也有些变味。

许多部分因为带着玩笑而显得模棱两可，但它的根源却是真实的。

——但是，就算知道了暗杀者这种事，也不会就此结束。

“……”

“阿昴，你的脸色很不好呢，没事吧？”

“阿赫，你打算对我们做什么？”

脸部的肌肉因为戒备和紧张而变得僵硬，昴盘腿坐在那里向赫鲁贝尔追问道。旁边的蕾姆也感受到了这份紧张，她用力地抓着棉被。接下来的言行，将会决定赫鲁贝尔是敌是友。

然后，如果他成为敌人的话，需要照顾怀孕的蕾姆的昴是没有取胜希望的。

“假设，我在这个时候说出‘要收下你的性命——'这样的话，你会怎么做？”

“那个时候……”

“……”

“那个时候，我会用这段时间的交往、我和蕾姆是新婚、以及蕾姆怀孕了这些事情当作盾牌，拼命地乞求生命，诉说苦情……大概吧”

“哈”

伴随着认真的声音和表情，昴对于赫鲁贝尔的追问给予了回答。听到回答的赫鲁贝尔深吸了一口气，稍微睁开了眯缝着的眼睛，惊讶地看着他。

但是，和赫鲁贝尔一样听到了宣言的蕾姆，却是向昴微笑着。她朝坐在旁边的丈夫伸出了手，两只手交叠在一起，那正是信赖的证明。

看着那样团结的一对夫妇，赫鲁贝尔将拿着的烟袋换到了另一只手上。

然后——

“——呜哈哈哈哈！真、真不愧是阿昴啊！真是很恶心啊！用那样的表情，向我求情……噗哈哈哈哈！”

“笑过头了哦！！”

“那、那样的笑、我也想停下……啊，嘿，嘿，要、要笑死了……！这是阿昴的意图吗，真是神机妙算啊！”

“并没有事实根据，我只是认真地按照自己的风格回答的”

“我明白的我明白的”

在一阵傻瓜似的狂笑后，赫鲁贝尔伸手擦掉了因为笑过头而出现的眼泪。之后狼人看向了一脸不满的昴，说了句“抱歉”后扬起手来，

“哈——笑了笑了。笑成这样很抱歉呢？不过，可以安心了哦。假话无论到哪里都是假话。我如果真的要做你们所知道的困扰工作的话，就会改变名字而行动的哦”

“没、没错呢”

“而且，用自己的手了结了难得让自己给予帮助的对方，可是非常没有效率的事情哦。要真那样的话，昨天我就不会帮助你们的”

“……”

一想到昨天的袭击并回忆起那时的困境，昴的身体就开始不断地颤抖。

事实上，如果没有赫鲁贝尔在，昴的命就没了。蕾姆和她腹中的孩子也是如此。岂止这样，如果在不知道孩子的存在时就失去了他的话……

“说的有些迟了真的很抱歉，阿赫……赫鲁贝尔先生，昨天真的非常感谢。你是我们的救命恩人，你救了我和蕾姆，还有我们的孩子”

“蕾姆也要像您道谢。多亏了赫鲁贝尔大人，蕾姆和昴，那个，才没有失去这个孩子。真的非常感谢您”

“呜哇——真是认真啊。我很开心，就接受你们充满感激的道谢吧”

看着站在那里恭敬地低下头的昴和蕾姆，赫鲁贝尔心情很好地笑了笑。但是在那之后，他保持着笑容，将手里拿着的烟袋指向了昴，

“好了，我也接受了你们的道谢。所以，那种会让我奇痒无比的不舒服的说话方式就到此为止吧。如今被阿昴称为赫鲁贝尔先生什么的反而很羞耻呢。蕾姆酱也是，可以的话不要再称呼我赫鲁贝尔大人了，换成更亲切的说法我会很开心的呢”

“……啊啊，我知道了。谢谢，阿赫”

“我会做出前瞻性的妥善处理的，赫鲁贝尔大人”

“你的夫人真是顽固呢！”

面对到头来还是拘泥于敬称的蕾姆，赫鲁贝尔投降地举起了双手。并且，他将手里的烟袋点燃叼在了嘴里，吞吐着烟云。

看到升腾着的模糊烟雾，昴露出了有些阴沉的神情。

“阿赫。烟草对于孕妇的身体有不好的影响，今后我们是要禁烟的”

“啊——放心吧。我的这个烟袋和普通的不一样，并不是嗜好品。这是像药一样的东西，是暗杀者专用的”

“药，吗？”

“没错没错。如果不定期吸食的话是会死掉的哦。哈——那样的话就会全灭了——”

“所以说全灭玩笑……”

虽然这个借口听起来像是玩笑一般，却令昴改变了对于漂着的烟味的想法。虽然昴也不是很确定，但确实赫鲁贝尔吞吐出的烟味，更可以说是烟草味，确实和普通的烟味有所不同。不是烟味，而是药味——即便如此，想必对母体来说也是不好的吧。

“总之，请在蕾姆的面前适当控制一下。无论如何都想两者兼顾的话，为了我和蕾姆的孩子，我会毫不犹豫地帮助你全灭的”

“刚才明明还说我是你们的救命恩人呢！”

“救命恩人和吸烟者完全是两回事。快给我到窗边去”

赫鲁贝尔从榻榻米正中央被赶到了边上，他咒骂着向窗户外吞吐着云雾，然后眯缝着眼睛看向了保护着妻子和孩子的昴。

“嘛，孩子的事情是你们夫妇间的问题……关于昨天晚上的事情，可以再稍微谈一下吗？”

“嗯，我知道了”

“那样的话，我想先问一下昨晚的对手，那个女人，你有头绪吗？”

“……”

提及昨晚的话题，被问到杀手的线索的昴自己也说不清楚。

那位气场如刀刃的女子看着并不眼熟。不认识她也是事实。但是，这并不是说就没有遭受袭击的头绪。

女子很明显是来狙杀昴和蕾姆的，这和那些不幸被卷入的过路魔事件是不一样的。一次又一次，甚至都追杀到了大宅处。

被抱有如此强烈杀意的女子追杀的原因，能想到的可能性就只有一个——那也正是昴和蕾姆两人一起生活的理由。

“嘛……”

“嘛？”

昴表情僵硬地张开了嘴，打算把线索说出来。但是，那种曾经被遗忘的恐怖正在苏醒，打开了埋藏记忆的盖子，并不停地挠动着昴的心。

——不，遗忘什么的只是谎言罢了。这种事情一次都没有忘记过。

那种恐怖至今也在变成后悔的锁链束缚着莱月昴的灵魂。

“……”

想要继续说下去，但到了第二个字时却怎么也说不出口了。

看着昴那个样子，赫鲁贝尔焦急地用手拨弄着胡子。正在那时，

“……我认为昨晚的犯人，和昴是没有关系的”

“蕾姆？”

“我明白昴的心情以及你现在所想的事。在此基础之上，蕾姆认为并不是那样……没错，请让我来说吧”

因为没有想到两人的意见会不一致，昴惊讶地看着想要代替他发言的蕾姆。而蕾姆则是朝他点了点头，认真地看向赫鲁贝尔。

感受到迎面而来的视线，赫鲁贝尔微微地睁开了眼睛。

“这种担心阿昴的谎言，会令我困扰的哦？虽然由被称为“游手好闲者”的我来说很没有说服力，但现在可不是玩耍的时候。这可是攸关性命的呢”

“我并没有说谎。蕾姆……蕾姆是有着能识别出敌人的嗅觉的。而对于昨晚的对手我并没有那样的感觉。所以，我想我们和犯人是没有关系的”

“那样的嗅觉有多大的信用度呢？”

“现在蕾姆能和昴在一起，也是多亏了那样的嗅觉”

那样的话语根本毫无说服力。但是，那样的话语却有着强力的让人相信的感觉。正因如此，赫鲁贝尔有一瞬间的迟疑。

这时蕾姆拉住了昴的手腕，用力地将他抱在胸前。

“这就是，证据”

“阿昴和蕾姆酱，究竟是怎样的……真是令人困扰的邻居啊”

“……我可不想被隐藏了本性的阿赫这么说哦”

“不隐藏的话可是很奇怪的呢。不过，也并非如此。那样的话，我们就相互成为邻居间的志同道合者吧。好不容易成为了宅邸同伴，就保持良好的关系齐心协力吧”

赫鲁贝尔爽朗地笑了笑，向紧挨着的两人提出了协力的请求。那样的话语让昴深感惊讶，不由得和蕾姆对望着。两人都不明白赫鲁贝尔的本意。

被归属不明的敌人狙杀，在没有同伴的状况下却得到了卡拉拉最强者的帮助。虽然这是一个极具魅力的提案，但在达成之前还不明白赫鲁贝尔的意图。

在这里同昴和蕾姆并肩战斗，对于他来说又有什么好处呢？

“我不明白，为什么阿赫要成为我们的同伴，并为我们做到那种地步……”

“不用去考虑这么麻烦的事情哦，我只是被长老拜托要照顾你们，而且我们还是朋友。虽然卡拉拉奇流是在意得失，但如果失去朋友的话可是非常巨大的损失呢。我为了没有损失而帮助你们，不是很自然的事情吗？”

赫鲁贝尔用平常的语调这么说着，并做出了眨眼的动作。因为原本一双眼睛就是眯缝着的，所以并不知道他是否真的眨眼了。

无论何时都是这样缺乏真诚味的动作，正因如此才感觉不到赫鲁贝尔是假装的。赫鲁贝尔就是赫鲁贝尔，那种洒脱的性格无论到那都是一样。

因此，他的话语并不会让人认为是听起来舒服的谎言，而是真的能够去相信的。

“我明白了。你那样说的话真是帮了我们大忙了。那我们就拼死拜托你了哦，阿赫”

“没错没错，现在可是撒娇的时候撒娇的时候。反正当你们成为父母之后，在孩子面前就不能再说泄气话了。我想在变成那样之前，现在正是撒娇的好时期呢”

被这大度的回答所救，昴暂时感到了安心。当他好不容易放松了肩膀并朝赫鲁贝尔点了点头的时候，赫鲁贝尔却说出了“尽管如此”的话并继续道。

“没有犯人的线索可是很麻烦的呢”

“虽然是那样，但阿赫可以分身成一千个人以此来采取自动人海追踪战术，你看怎么样？”

“你还真是会撒娇啊……还有，我的分身术可是王牌，胡乱使用是不可以的。而且我也做不到分身成一千个人，四个人就已经很虚张声势了”

“那么，狼人的嗅觉呢？用那个来追踪犯人什么的不行吗”

“那个啊——可以试一下”

在分身战术被否决后，昴又献上了代替的方案。于是赫鲁贝尔就开始在昴的身上嗅了起来，用鼻子来回迅速地闻着。

“真是奇怪，那个孩子残留的味道已经没有了。像是想到了要从我的鼻子底下逃走一般，谨慎地消除了味道呢……光是这一点，就很技艺高超呢”

“看样子是对阿赫采取了对策呢”

这种时候，恐怕都会觉得是那位女子的周密计划吧。

赫鲁贝尔成为昴他们的同伴，这在昨晚还是不确定的情报。但是，女子却针对那不确定的要素做了完全的准备，并实行了袭击。

在夜晚的道路上屏退他人的夜袭，以及跟踪到大宅的奇袭——无论哪一种，特别是对于多少和她有所交谈的后一次的印象，同那种周密性似乎有什么地方不太一致。

“总而言之，只能看看现状了。我姑且问了问街上的同伴，但这似乎会成为牺牲无辜生命的举措呢。粗心大意地挑起斗争导致到处都是尸体的话，也是会很困扰的呢”

“这和屏退别人没有区别，能顺利的发现敌人吗？”

“那或许并不能有所期待呢。蕾姆也积极地行动一下会比较好”

“那样绝对不行”

对于蕾姆所提出的微小主张，昴强硬地驳回了。

虽然从外表还看不出有所变化，但蕾姆确实是怀孕了。这种勉强的事情绝对不能让她去做。要是可以的话，昴希望她能放弃寺子屋的工作，在家里静心地调养。

“……糟糕。工作要怎么办啊”

“蕾姆也必须要去寺子屋工作了”

察觉到已经逼近的工作时间，刚才沉浸在交谈中的昴和蕾姆都变得脸色惨白。

身为正式员工的蕾姆是理所当然要遵循的，而昴也正处于是否能够定下工作的紧要关头。对他们而言，擅自缺勤是毫无道理的，及时向上级汇报是成为社会员工的必要条件。

“啊---现在不是担心那些事的时候吧？”

“胡说八道，我可不想和不劳而获的阿赫一样呢。即使是敌人所在的这个时候也是要吃饭的，而吃饭是需要钱的，这可是每天都会让我困扰的事情呢”

反驳了呆怔的赫鲁贝尔后，昴又说了“而且”后继续道，

“这样不会后悔吗。明明是对方不对，却对我们这边进展不顺的生活放置不管，这可是很荒谬的。我可不想就这么屈服。”

“……”

面对敌人不讲道理的袭击这一危机，将其解决后面临的又是极为普通的日常。在经历了曲折的故事之后，昴他们更有必要活下去。

“而且，我们家的积蓄也不是很充裕”

“而且因为又要增加一个人，提前做好储蓄是很有必要的”

“这是什么威胁啊！？你们这对夫妇，真的很不讲道理啊”

被他们拿生活和新生命的盾牌要挟着，赫鲁贝尔露出了困扰的表情并陷入了沉思。两人有着很坚定的决心。看出了这点的赫鲁贝尔张开了大嘴，发出了一声长长的叹息。

“我想今明两天敌人暂时不会来挑衅的”

“那么想是因为？”

“那家伙，包含我的嗅觉在内都有相应的对策对吧？那样周密的布局，很难想象她会因为急于这件事而使得失败率上升，我是这么想的”

“蕾姆也认为很有道理”

对于竖起手指的赫鲁贝尔的猜测，蕾姆也表示赞同。昴也确实地接受了。

正因为敌人是头脑灵活的人，所以才会认为她不会做那种准备不足的事。虽然这种说法对于受到重创的对手来说不太合适，但确实该相信她那周到的手段。

相比于正确的做法，如果更遵从这种扭曲的信赖的话……

“从今天开始，我暂且陪在蕾姆酱的身边。那样的话阿昴也会放心，而且到了火之刻印的时候昨天的术师也会来的哦”

“……我明白了。我先去宅邸，和利夫坦先生及老板娘商量一下。寺子屋那边也是，要好好地传达“蕾姆需要辞退工作”的事情哦”

“……是。虽然感到很遗憾，但拜托你了”

蕾姆虽然看上去很沮丧，但她却点了点头，没有反对昴的提议。

关于昴的工作，在昴开诚布公地说出后，也只能等待利夫坦先生及老板娘的判断。但是，只有离升为正式职员的道路还很远这一点是不会错的，这一点令人十分沮丧。

不过，关于蕾姆的寺子屋工作，只要说出了怀孕的事情，就无法继续这份工作,
和敌人的存在毫无关系。只有这一点是确定的。

“可以的话，请让我继续做下去，昴”

“……看样子并没有好好地进行商量呢”

“没错”

工作和怀孕，这次轮到昴来支持怀抱着这两个烦恼的蕾姆了。虽然这成为了让她苦恼的理由，但今后不会再让比这更苦恼的事情来折磨蕾姆的心灵了。

“那么，虽然我会非常得牵肠挂肚……但我、也要、努力去工作……！”

“明明可以不用那么辛苦的”

“别说得那么轻松，不劳动的贵族。我可是，今后要支撑着全家的顶梁柱呢”

由自己说出来的话，总感觉是要重整那似乎丢失了的沉重感。

没错，就是那样。蕾姆的肚子里有着孩子。而昴，是即将要成为父亲的。

他将会成为守护莱月一家的顶梁柱。

——那对于昴来说，将会是一种承担着非常非常沉重的责任的自觉性。

“一路小心，昴。我会等你回来的哦”

“——啊，我走了”

浅浅微笑着的蕾姆，温柔地化解了昴的依依不舍和压力为他送行。感受到了这些的昴，深呼吸了一口气后离开了大宅。在即将关上门的时候，他最后一次回了头。

“阿赫，蕾姆的事情真的拜托了。如果发生了什么的话请代替我照顾好她”

“我可没有做替身的才能呢”

看到赫鲁贝尔作出的保证后，昴挥了挥手出发了。

寒冷的风吹来，升起的朝阳开始逐渐地照亮巴南的街道。

“真是耀眼啊”

感觉今天的朝阳比任何时候都耀眼什么的，一定是心理作用吧。

昴一边想着这些，一边朝着要尽义务的职场方向迈开了步伐。

2

——从昨晚开始一直持续的激动，以及那一连发生的事情都给昴带来了巨大的冲击。

在职场被暗示能升为正式职员，在晚归的道路上被未知的敌人威胁到了性命。回到家时被尾随而来的敌人杀了个半死，最后还明确地知道了蕾姆怀孕的事情。

老实说，似乎所有的大事件都挤到了一天。真是很想抱怨一下。

不过，正因为发生了那样大的事件，所以才注意到了几件幸运的事。

——首先第一件，就是蕾姆怀孕这样让人欣喜的事。这可是非常大的事情。

就如同很多男性一样，意想不到地知道了自己的配偶怀孕后所带来的冲击可是无法计算的。昴也是如此，在不断地惊讶中依旧表现出了自己无法理解的惊讶。

但是，当经历过一次这样的冲击后，昴的心中只剩下了纯粹的喜悦，以及对赐予了他孩子的蕾姆的感谢，而这些事同样也令昴自己感到十分开心。

孩子应该是在父母的怜爱、喜悦和祝福中所诞生的。

即使知道不是所有的孩子都是这样，昴也想相信这样的理想。这样一种令自己相信的教育方式，昴也或多或少地接受过。

所以，自己也想用这种方式去疼爱自己的孩子。被疼爱这种事情，是会令人感到十分开心的。

那些暂且不提，因为准备不足而感到不安这件事是另当别论的。

——然后第二件，就是两人切实感受到了周围的人的体贴。

说起来，在巴南安定下来的事情，也是多亏了在旅途中相遇的有缘人的指点。围绕着那样的事，两人和赫鲁贝尔相系，昨天捡回了条命以及今早的协力都是与之联系在一起的。

然后那种幸运，在向寺子屋的人员传达蕾姆请假时也切实地感受到了。

“——怀孕！真的吗！那真是要祝福你了啊！”

像这样被寺子屋的工作人员们所祝福，昴感到诚惶诚恐。

老实说，这可是与新加入人员切身相关的事情。虽然已经做好了被指责“新来的女教师，竟然有着这种缺乏职业精神并且蛮不讲理的私生活”的觉悟，但大家的反应还真是出乎意料。

那一日缺勤的工作将由其他老师来代行，并且上司也来参与了关于今后的事的商讨，除了感谢之外再无其他。在无形中知道了妻子在工作场所得到的评价，作为丈夫来说是很骄傲的。

就这样心情舒畅地离开后，昴朝着自己的工作地点走去。

必须要向身为雇主的利夫坦先生及身为上司的老板娘将事情交代一下，并商量下今后的打算。

当然，这是私事。所以昴打算找到机会再商量一下。

虽然是这么想的……

“……昴酱，你的夫人怀孕了吗？”

然而老板娘不知在哪听谁说的，这样一来昴的干劲全化作了泡影。蕾姆怀孕的事不知为何事先在宅邸中传开了，所以她一口气展开了询问攻势。

那之后的记忆不太清晰了，但最终似乎是被她说出的“昴酱也总算露出了孩子般的表情呢”这种模棱两可的结论所解放了。

随后，换成和利夫坦进行了谈话，

“关于你的事情我已经听说了。你的立场，真是相当不容易呢”

“哈，哈啊……对不起。我的生活给老爷您造成了困扰……”

“不，我并没有觉得困扰哦。新的生命，同样也是诞生的新顾客”

“人才队伍会壮大呢”

在茶室里向利夫坦如实地进行了说明后，相比于惊讶，昴对他容许的言行感到更为呆怔。

看到昴那样的反应后，利夫坦说了句“而且”后继续道

“昨晚的事情已经从赫鲁贝尔氏那里听说了。要是有什么不安的话，不管什么都可以找我商量。我会询问贵族太太们的”

“那真是……那个，帮了大忙。但是，为什么要做到那种程度？”

“因为会对我有益处的吧？说过的吧，我对你非常期待。我在你这里投资了名为期待的资产。为了能够回收它，尽其所能地帮助你是理所当然的”

职场上的理解和雇主的强力话语使得昴不由自主地眼睛一热。但是，那副样子被看见的话实在太过悲惨了，有些过于撒娇了。

“太太们也应该爽快地答应了你。这也是你和她们之间所培养出的信赖”

“……仅仅只过了两周左右而已”

“这可是十分有价值的两周。光是对你来说”

这种无所谓的语气，这次却令昴再也抑制不住地抬起了头。

在这一瞬间，玛格洁宅邸的人们对于昴来说就是大恩人的存在。

从恩人、邻居、职场的人们那里，受到了很多很多的照顾。

对于孩子所受到的恩惠昴也会计算着那样的祝福，并在激动的那一天将很多的幸运之事告知他。

——正因为如此，那位来历不明的女性的存在就会成为幸运下隐藏的阴影。

对于昴和蕾姆来说都是一个充满未知数的敌人。标志性的线索并不是“蕾姆所说的”。但是，那位美丽残忍的杀手一定会再次出现的吧。

即使有享誉卡拉拉奇最强者之名的赫鲁贝尔在，也存在着无法轻易放心的威胁。

所以，昴依仗着宅邸人们的厚意，提早下班，着急地走在回家的路上。所受到的恩情今后一定会回报。所以，只有现在需要撒娇一下。

紧迫的问题已经因为人缘而得到了解决。剩下的问题……虽然昴还没有想出妙计对付那位女性，但如果有熟悉这所城市的赫鲁贝尔和博识的蕾姆在的话，或许就能想出解决的办法了。

心中满怀着希望，昴沿着道路奔跑了起来……

“……独自一人出来什么的，真是个笨蛋呢。你是想要守护一对鸳鸯中的雌性吗”

……看到道路正中央出现的人后，确信了赫鲁贝尔的见解是存在问题的。

3

“什么啊，完全呆滞了呢。你能不能不要看我看得那么出神？”

那位女性在白天光明正大地现身在了昴的眼前。

地点是在街道上，是在从玛格洁宅邸去往大宅的归途中。因为周围的人都很体贴，所以正午刚过昴就可以早退了。因而现在正是太阳位置最高的正午时分……虽然这是理所当然的，但现在街道上人山人海，想要不引人注目是不太可能的。

实际上，这位女性异于常人的美貌是十分显眼的，这不论好坏都是不利于她的隐密行动的。如果想要进行和昨晚一样的狙击，却像现在这样不避开路人，这是不是出了什么差错呢。

或者说其实她并不讨厌引人注目，可能只是打算来挑衅一下。

“……”

昴压低了声音，看向了街上。来往的行人们谁都没有注意到这位站在道路中央为所欲为，且是个危险人物的女性。如果像昨晚……特别是第一次袭击时的气势的话，她的攻击将会令很多人卷入其中。众人所受到的伤害是预想不到的。

“真是失败啊……我已经确定你是一个谨慎的对手了”

屏退路人，并做好准备迎战敌人，最后追踪到其所逃到的地方。只要敌人慎重地这么做的话，就能秘密地达成我们的目的。昴他们一直先入为主地抱着这种观念。

结果却变成了这样。敌人拿街上的人作为人质，封锁了昴的行动。

“真是残酷却又头脑灵活的女人呢”

“哈啊？你这家伙突然就变得很失礼呢。一见面就说什么呢”

“周围都是人质，逃跑的话是不会饶恕你的。这就是你的狙杀方式吧？”

女子眯缝着眼睛，目光冰冷，身上依旧是同昨晚一样的白色装束。

这身打扮作为和服装扮来说并不罕见，但女子那不加任何渲染的纯白加上自身的美貌，使得这身打扮不同于平常，就如同世间之物诞生了难以想象的调和感。

她那副样子，光是沉默地伫立在那里，就令人觉得如同神所创作的画卷一般……要是昴不知道她那令人受尽折磨、痛苦不堪的施虐狂本性的话。

“嘛，算了。那就边走边说吧”

“什么？”

“这里很吵，反正我们的目的地是一样的。你也明白自己是没有能力拒绝的吧？”

女子努了努嘴，站到了昴的旁边盛气凌人地说道。因为她有周围的人质在手，虽然很不甘心，但也只能按照她说的去做。

只要有那句无法置若罔闻的话在的话。

“目的地一样……也就是说，什么。难道说，你这家伙”

“就是和你一对的那名雌性所在的家哦。现在那里有了一只多余的狗，会很麻烦的吧？所以我才需要你。只要饲主在的话套上项圈的狗就会十分安静的，不是吗？”

“不要说这种蠢话！眼睁睁地……我会眼睁睁地让自己领着你过去吗！谁会把你这样危险的女人带到蕾姆的……”

“……吵死了”

“……”

女子朝着强烈地拒绝了她的要求的昴，极不愉快地发出了一声警告。

声音中所包含的尖锐，令昴直接产生了喉咙被刀刃刺入的错觉，一时沉默不语。

全身的血液因为敏感于女子的敌意而逐渐变得冰冷起来。就像是昨晚暴露的丑态一般，即使膝盖逐渐坍塌也不奇怪，昴现在就感受着这样的压力。

但是……

“……带你去见蕾姆这种事，谁会去做啊”

“嘿唉。稍微有点佩服你了呢。我还以为你已经害怕得动弹不得了呢”

女子瞪圆了细长的眼睛，咬着嘴唇看向抵抗的昴这么说道。然后，她生气却又兴奋地指着面红耳赤的昴说道。

“不过，我是不会听的。而且，你们的判断是错误的哦”

“判断错误？”

“我并没有要杀你们的打算，虽然只是现在”

女子将指着昴的手张开，挥了挥手掌并耸了耸肩。这种泰然处之的神态，却是和昨晚将昴打趴下并想要杀死他的时候一模一样。

这位女子是能够笑着将昴折磨并杀害掉的。

“……怎样才能相信你说的那些话呢”

“只要我想做，就没有杀不掉的人。昨晚，只要想杀你的话是有很多时间能够杀掉你的。但是我却并没有这么做。所以，我并没有杀你的打算”

这作为证明来说真是十分简陋的道理。但是，它也是有着无法否定的分量的。

那样的话语是自负，是事实，也是只能称为自明之理的真实。

那名女子是敌人。她有着敌意和杀意。但是，女子没有夺去昴和蕾姆的生命就离开了，而且第二天又在街上露面，并直接表示出要前往两人的家里。

“你究竟在想什么，我真是完全摸不着头脑呢”

“想要我立刻就告诉你什么的，你难道是小婴儿吗？小婴儿应该是在你的妻子的肚子里吧？要成为父母的话，你也应该再稍微自立一点，好好地动下脑子会比较好吧？”

“你经过了一晚后洗心革面，为了谢罪因而带我去大宅，这样的？”

“哈，真好笑。没有打算杀掉你真是太好了呢”

女子嘲笑了一番后，背对着昴迈出了步伐。虽然她什么也没有说，但那飘荡着的白色头发却是无言地向昴施加了“跟过来”的压力。

即使在这里做出抵抗，女子的目标也是大宅，而且她也很有可能将街上的人当作人质。

“你为什么知道蕾姆怀孕了”

“只要看一下就会明白的吧？我和你这样迟钝的雄性是不一样的哦？”

“蕾姆也没有注意到哦”

“那么就改为，我和你们这样迟钝的雄性和雌性是不一样的哦？”

规规矩矩地改正后，女子哼着小调，带着昴继续在街上前进着。虽然这小调并不耳熟，旋律也是乱七八糟，但却夹杂着一种莫名的乡愁。

即便如此，昴对女子的警戒心却丝毫没有动摇，他一直在考虑着如何制造机会将事情告诉大宅里的两人。

但是，只是走了十五分钟就出现了夹带着离谱的话的戏剧性一幕……

“……我正想着阿昴回来得真是早呢”

站在大宅前吸着烟袋的赫鲁贝尔那么抱怨着。

他正好出来抽烟时，同昴和女子不期而遇了。赫鲁贝尔眯缝着眼睛望着两人，无法看出他此时的心情。

“知道妻子怀孕的第二天，就带着别的美女回家了，你身为男人就是这样的？”

“我知道自己很差劲，那么你又如何呢？”

“我承认从视觉上来说我是最坏的哦，不过，现在可不是能开玩笑的情况吧”

“嗯---”

赫鲁贝尔吸了口烟，从鼻子里吐了出来，似乎在沉思着什么。随后他慢慢地站了起来，掸了掸屁股上的灰尘，朝着女子看去。

虽然那名女子作为女性而言，身材十分高挑，但在身为亚人个子却很高大的赫鲁贝尔面前也是被俯视着的。不过，因为身高差而被俯视，她看上去也十分生气。

“不要因为你很高大就能得意忘形了哦？”

“真是新奇的攀谈方式啊。你可真是个美人，我也只有身高能赢你了啊”

“被狗夸奖而感到高兴的，只有同样身为狗的雌性哦”

这种令人无所适从的态度。虽然赫鲁贝尔面对女子的冷淡并不会气馁，但对昴来说，在这种险恶的情况下，他关心的只有和这毫无关系的蕾姆。

“阿赫，蕾姆呢？”

“在这种情况下你还真敢问啊。……在里面哦。刚才她还跟我说想要做家务，我可完全招架不住呢”

“真像蕾姆的风格”

实际上，即使说是怀孕，现在的阶段也还是怀孕初期，蕾姆那还不显眼的肚子就是证据。昴依靠仅有的体育保健知识进行推测，现在这个时候做家务应该不会成为重担。

要说会成为重担的话，旁边站着的女子所具备的那种可能性比蕾姆要大上一百倍。

“那么，实际上，那个孩子究竟是什么人？说话这么刻薄，是你的朋友吗？”

“不，你知道的吧。……是昨天袭击我们的女子哦”

“嗯嗯嗯？”

昴对赫鲁贝尔那慢条斯理的差劲察觉感到十分失望。本想着这种没有价值的对话能够争取到时间，但看样子却不是那样。

而且，在被昴指出后，赫鲁贝尔露出了奇妙的表情，

“她就是，昨天的那家伙？不，那是……”

“什么？你想说这是骗人的吗？想说我是做不到那种事的吗？别再让我觉得可笑了行吗？我昨天，可是把这家伙打趴在了房间各处，浑身都沾满了鲜血呢……等等！这么说来你这家伙，昨天汗淋淋的令我很难受的！你要怎么赔偿我啊！”

“我怎么会知道啊！那时我全身都变得摇摇晃晃的，所以你满足吧”

女子打断了赫鲁贝尔自顾自地说了起来，当她说得正兴奋时，突然想起来了昨晚发生的事情后就生气地沸腾了起来。听到她那随便迁怒于他人的荒唐话语，即便是现在，昴也丝毫不敢疏忽地拿自己的身体被打倒时的疼痛作为理由，想要让生气的女子镇定下来。

就那样，正当大宅前突然开始了骚动的时候。

“……我想听听你们所说的事情”

大宅的门被打开了，踏进眼下这种险恶情况的是一名有着天蓝色头发的少女——蕾姆。她处理好了家务活，正在解开束缚着的和服衣袖，并朝着昴微笑着。

“欢迎回来，昴。今天回来得很早呢。就那么，想和蕾姆见面吗？”

“……啊，没错。老实说，即使你离开片刻我也会感到很艰辛的”

“那，那是……嗯，那个，蕾姆也是。不行，我会害羞的”

“才不是害羞什么的呢！”

听到这对夫妇间天真无邪的对话，女子的不愉快又像先前那样以不同的形式炸裂了，她使劲地挠着自己的短发说道

“真是的，情况失常了啊……”

“失礼了。可以的话，请先到里面冷静一下吧？我已经沏好了茶，希望各位能好好享用一下”

“……”

那对于女子来说，大概是无论如何都想不到的话吧。

她露出了瞠目结舌的表情，而昴和赫鲁贝尔也相互对望了一眼。然后三人点了点头。看到他们的回应，蕾姆露出了温柔的笑容，说道：“肚子里的孩子不能受到惊吓，所以请让我们好好地谈一下吧”。而这样的话语诚然体现了“母亲是伟大的”。

4

“我是……啊，缇雅哦。总之先自报姓名一下”

在房间的榻榻米上稳稳当当地坐着的女子——缇雅，心情很差地报上了姓名。

在缇雅正对面坐着的是昴和蕾姆两人，赫鲁贝尔则是靠着墙站在房门附近。虽然现在这样的状况就像是在充满压迫感的面试会场上一般，但并不能明确地说房间里充满了紧张感。

实际上，即将开始的就是充满压迫感的面试一般的会谈——询问特地来到大宅狙击我们的缇雅，她的心中所想之事。

“难道说，犯人并不希望自己回到犯罪现场的吗”

她的自报姓名暂时也让大家的关系更进了一步。像是回应了这互相让步的妥协一般，蕾姆将茶端到了缇雅的面前，朝她点头行礼。

“我是蕾姆。旁边坐着的是昴，他是蕾姆的丈夫。墙边站着的是赫鲁贝尔大人，他是我们的邻居。请多多指教，缇雅大人”

“昴和赫鲁贝尔大人？”

“昴和赫鲁贝尔，请给我区分开来。比起这个，蕾姆，没有必要对这家伙用敬称。敌人……她看起来是敌人哦”

虽然蕾姆简直就像是对待客人一样，但缇雅可是应该明确地作为敌人区分开来的。面对着那么主张的昴，蕾姆却摇了摇头，

“不行。既然进行了招待，缇雅大人就是客人。而且，我们也苛待了寻求着交谈的对方。她看样子是有什么话想说，是这样的吧，缇雅大人”

“哼哼。和那里的雄性生物们不一样，身为雌性动物的你看起来比较强呢。你叫蕾姆是吧？好好记住，雄性和狗是不合格的哦”

蕾姆的礼貌待客方式似乎让缇雅的心情变好了，她心情舒畅地喝了口茶。可是却呛到了。

“好烫！好烫！这可是很烫的啊”

“啊，对不起。您没事吧？”

“真、真能干啊。我对这个大意了啊。你可真难对付啊”

“你明明是自残的吧。给我适可而止，话题完全没有进展啊”

面对着怕吃热食却反过来怨恨蕾姆的缇雅，蕾姆只是不断地道歉着，而昴则是抬手制止了蕾姆。

从刚才开始，大家似乎就看错了保留精力不断争论着的缇雅的本质。但是，昴却是绝对不会大意的。不知她何时会像昨晚一样露出獠牙加害他人，所以昴一直保持着警惕。

“一直绷紧着神经，你们这些雄性动物的这种无用的地盘意识还真是一个坏习惯呢。算了。就如你希望的那样，快点解决要办的事吧。我可并不清闲，反倒非常得忙碌呢。”

“要办的事……”

“所---以---说，我说过了并不是来这里杀你们的了吧。……不过要看你们的行为了”

在最后用冰冷的声音这么加上了一句后，缇雅放下了茶杯，用锐利的目光看向了对面。

然后——

“考虑到我这宝贵的慈悲心，我可能会对你一时产生歹念呢。所以，这被你逃掉的报应我也是可以接受的。但是作为交换，请老实地将光珠还给我”

没错，缇雅斩钉截铁地说出这些时，看着的并不是昴，而是——蕾姆。

“……”

首先，有一件事令昴感到困惑。那就是，缇雅的视线一直停留在蕾姆身上，对于就在蕾姆旁边的昴确实是目中无人的。另外一个困惑，就是昴对于缇雅所说的“光珠”完全没有头绪。看样子，似乎蕾姆也是如此。

“光珠？”

她歪着脑袋，露出了困惑的表情。但是，那样的回答并没有得到缇雅的回应。

“请注意你的回答。我不想听到除了‘是'以外的答案。每当听到了错误的回答时，我都会感觉身体里像是缺少了什么哦”

缇雅伸出了手，用雪白的手指指着对面的蕾姆，这么告知着。

虽然缇雅平静的声音听上去很冷静，但实际上那是骗人的。声音里所隐藏着的愤怒一直潜伏着，只有爆发的那一刻才能令人立刻意识到。

言出必行，缇雅根据回答直接将愤怒的矛头指向了蕾姆。当赫鲁贝尔的存在一旦失去了抑制力后，她就会开始进行不用言语的威压交涉……

“……等、等等”

“不会等的。不只是蕾姆，你也给我注意一下言行。只要你说错一句，和你一对的雌性生物就会少手指的哦”

“你真是个恶魔！不，恶魔也无所谓，给我听着。光珠究竟是什么啊？”

“真会装糊涂，就是被你们偷走的东西啊。虽然我不知道你们叫它什么，但那是我的光珠，我来着就是为了拿回它”

“那是什么啊……”

昴的回答令缇雅的情绪更加恶化了。但是，无论堆积了多大的愤怒，昴依旧没有给予缇雅她所期望的回答。

蕾姆当然是不知道的，而昴也确实对名为“光珠”的东西毫无头绪。

即使被说成是盗窃，这对于两人来说也是晴天霹雳的。那究竟是什么样的物品，对缇雅来说又是重要到了什么程度，即使她对于那东西十分热情洋溢，他们也是无法想象到的。

但是……

“我已经说过了，请注意你们的言论。你打破了这个规矩了呢”

“……”

一阵强风划过昴和蕾姆之间，二人背后的墙壁上出现了锋利的划痕。

像是经受过剑的攻击一般，大宅的墙壁上纵向刻下了利剑的划痕。那种锋利的程度非常可怕，如果不是墙壁，即便是人也会很容易地被砍成两半吧。

这与恐吓、警告是一样的。缇雅用实际行动，证明了下次自己是不会原谅两人这么说的。

“……”

站在后面看见这一切的赫鲁贝尔并没有动作。究竟是因为他看穿了这并没有打中的示威行为，还是因为他根本没有空隙动作呢。

不过，对于昴和蕾姆来说，这是不可小看的实力证明。在这基础之上，缇雅又向蕾姆质问了同一个问题。

即——

“……光珠究竟在哪里，快还给我”

“……非常抱歉。蕾姆的回答和昴是一样的”

“……”

“对于不知道的东西，我是无法回答的”

“是吗”

蕾姆坦率地看着缇雅，毅然地回答道。蕾姆的回答让缇雅闭上了眼，迅速地伸出了右手轻轻挥动着。

房间里的被子因为这次吹起的强风而被劈成了两半吹跑了。

“即使这样，也还是不能说吗？”

“不是不能说，而是我并不知道”

“真是顽固啊！”

看着即使变成了这样也依旧不肯屈从的蕾姆，缇雅的愤怒终于爆发了。

她站起身来，朝着房间两边迅速地伸出了两只手，下一个瞬间，令人惊恐的风在房间里狂乱地刮着，整个房间被镰鼬所切割着。缇雅正在不断地破坏，蹂躏着这里。

墙壁、被子、书架、榻榻米、以及矮脚饭桌，所有的一切都在被破坏着，并在房间里四处飞散。感受到强风留下的痕迹，昴停滞了呼吸变得有些僵硬。

但是，只要蕾姆不转移视线，昴也就不会因为胆怯而惊慌失措。

“咕唔……唔唔唔……”

终于，房间里没有了明显的可破坏对象，这使得缇雅开始低吼了起来。她将目光从蕾姆那里移向了昴，随后又移到了赫鲁贝尔身上。

“我、我要杀掉那条狗哦。即使那样你也不还给我吗？”

“是的，我无法还给你。”

“虽然现在说这话有点不合时，但你们对我是不是太差了点？”

万般无奈的缇雅的威胁，被蕾姆固执的意见所拒绝了。这样的话，即使缇雅残酷地杀了赫鲁贝尔，也不会达成她的期望。

“不过，我的心情稍微舒畅点了呢”

“阿昴，我正在哭泣哦”

“我知道的。稍微这样怎么了，与之比较起来，你会得到更多的回报哦”

“我可并不想拥护你那种想法呢”

朝正不满地闹着脾气的赫鲁贝尔斜视了一眼，昴发出了短促的叹息。他环视着房间，那里到处都是破坏的痕迹……但是，昴他们却毫发无伤。

只要看到这一切，就算是观察力再差的昴也能够理解了。

“你这家伙，真的没有要杀我们的想法呢”

缇雅带着充满愤怒和憎恶的目光，看向了得出那样的结论的昴。但是，无论带了多强的杀意，眼神也是无法杀死人的。

虽然房间里尽是缇雅的愤怒所留下的刻痕，但她的愤怒却不是杀意。就像她最开始所说的一样，“没有杀人的想法”。

威胁归根结底不过是威胁而已，而且她还避开了对我们造成的异常伤害。

“真是意外，昨天明明都把我打了个半死……”

“那个时候，我并不知道蕾姆怀孕了……”

“……那是理由吗”

“嗯唔”

缇雅刚一说完脸色就突然变得很难看，但即便她迅速地捂住了嘴，也为时已晚。

也就是说她……

“因为蕾姆和昴有了孩子，所以才不杀我们的吗……？”

“……盗窃光珠的罪确实是罪。但是，那个罪是你们所造成的哦。这和肚子里的小孩子是无关的。如果夺去了孩子的性命的话，是会违反被称为‘死神'的我的信条的”

“‘死神'……”

听了缇雅的追述后，昴瞥了一眼赫鲁贝尔。昨晚也是如此，虽然感觉到缇雅自称过“死神”，但被杀了半死时的记忆是模糊的。看到昴使的眼色，赫鲁贝尔微微摇了摇头，看样子他似乎也没有头绪。说到底不过是自称的外号……不过，这名字似乎与她的实力也太过般配了些。

“什么啊，你不会杀我们的。就连伤害也避开了呢。那样的话……”

“放手什么的，就算做了坏事如此厚颜无耻也要有个限度吧。我是绝对要拿回光珠的。既然小婴儿很碍事的话，我会一直等到他生下来的哦”

“真是有耐心啊，从一开始就……”

即使因为自身的信条而左右为难十分苦恼，缇雅也并没有打算让步到无法退让的界限。

看到缇雅的苦恼，昴不知道该怎么办地看向了蕾姆。蕾姆迎着昴的视线向他点了点头，继续保持着在那样狂乱的风中也没有零乱的正坐姿势说道，

“缇雅大人，就像我无数次回答的那样，蕾姆对于缇雅大人的光珠完全没有线索。再次重复一遍，盗窃它的人并不是蕾姆”

“蕾姆一直都和我在一起。她并没有那么多的空闲去做这种事，所以并不是蕾姆。你究竟为什么认为是我们拿的呢？你有什么证据吗”

“这不是由我决定的。——是鼻子哦”

“……”

缇雅指着自己的鼻子，堂堂正正地回答了昴的问题。对于那样的回答，昴皱起了眉头，心里像是被出乎意外的威力所震慑到了，一时说不出话来。

缇雅通过自己的鼻子找到了昴他们。当听到这个答案时，涌上众人心头的，果然是理所当然的恶寒和领悟。

缇雅通过嗅觉，探寻到了昴的所在之处而来到了这里……

“那副样子，看上去果然是毫无头绪呢。就算你再怎么庇护和你一对的雌性也是没用的哦。蕾姆的身上，可是有着强烈的小偷气味呢！”

“……”

缇雅得意洋洋的话语让昴一时说不出话来。

然后，他开始在头脑中慢慢地回味刚才所说的话。

“……是蕾姆？不是我？”

“哈啊？那是什么，你打算用哭泣的剧本来庇护她吗？很抱歉，我的鼻子是不会被蒙骗的。我的鼻子告诉我，蕾姆就是犯人哦！”

缇雅再次严肃地指着蕾姆，得意洋洋地断言道。

从刚才的反应中看穿了昴内疚的心情的她非常强硬。但是，那和缇雅所期待的内疚是完全不一样的。

因此，昴他们之间的气氛开始变得有些微妙。

“什、什么啊，你们这些家伙……那副样子，是在把我当成笨蛋吗？”

“虽然并没有把你当成笨蛋……”

“果然，应该是弄错了什么吧”

“才没有弄错呢！我的鼻子是绝对不会出错的！！等等你这只狗！既然你也有一张像狗一样的脸，就应该是明白的吧！？”

“为什么你认为我的想法会和你一样呢？你是我的妻子吗？”

“谁是你的妻子啊——！！”

雪白的脸顿时变得通红，缇雅捶胸顿足地怒吼着。那副样子已经没有了当初的威圧感，简直就像是一位下不来台的少女。

她拼命地粗喘着，挨个地怒瞪着昴他们。

“把偷来的东西还给我！竟然把我当成笨蛋，你们这些家伙，究竟有什么企图！？打算成为父母什么的，我会让你们后悔的哦！”

“请不要再那样做心理上的赌气了。比起那个，还是适可而止地承认了，这样如何？是你弄错了哦。我们谁都没有偷你的光珠”

“不---对---！绝对是蕾姆偷的哦！我是绝对不会弄错……”

“那样的话”

面对突然间变得缠人的缇雅，昴也感到了困扰。而打断了那与外表不相符的说着幼稚赌气话的缇雅的人，是蕾姆。

“缇雅大人认为蕾姆和昴偷了什么东西对吧”

像是在和听不进任何话的孩子说话一般，蕾姆温柔地和缇雅交谈着。而缇雅接受了她的话语，绷紧了脸转向她。

“我先说好，只有蕾姆哦。我可不知道这边的雄性有没有偷”

“蕾姆和昴无论做什么事或是去哪里，都是在一起的。对吧？”

“我、我知道的哦……”

缇雅恢复的状态再次受挫，她只能点了点头。而面对这样的缇雅，蕾姆说了句“好”并竖起了手指。

“我想拿回缇雅大人被盗窃的光珠。但是，蕾姆和大家并不知道光珠的事。如果您不相信的话……直到您信服之前，可以稍微再等待一段时间吗？”

“信服什么的……”

“如果缇雅大人的鼻子所确定的事情是真的话，说谎的人就是蕾姆我们。要是一直监视着我们的话，或许总有一天我们会露出破绽的。就是这样”

竖起的手指轻轻摇晃了几下，蕾姆说着“怎么样？”，并将选择权交给了缇雅。

虽然这是一个遥遥无期的提案，但对于昴来说，那简直就是应付小孩子的把戏。但是，缇雅听了那样的提案后，似乎很快就陷入了沉思，然后，

“……不是很有趣吗，可以哦，就这么办吧”

“认、认真的吗？”

“就像蕾姆所说的一样哦。因为总有一天你们肯定会露出破绽，所以我就等着吧”

缇雅挺起了丰满的胸部，堂堂正正地回答了昴的疑惑。即便如此，昴依旧很难相信她所作出的选择。看见昴那副表情时，她撒娇地说道。

“我可没有说谎。我对自己的鼻子可是很确信的。看，我可不存在会输的因素哦！如果是我弄错了的话，作为道歉把光珠送给你们也是可以的哦！”

“为了拿回光珠而遭到袭击，这真是一种没有止境的循环啊！”

不管怎么说，缇雅能将蕾姆的提案作为一个好主意接受的话，现在的局面就得到了突破。至少不用担心缇雅会伤害到蕾姆和昴了。

“不过，对于“我可没有说谎”这句话，你可要真的守信用啊”

“没关系的哦。蕾姆认为缇雅大人是真的没有说谎。……在寺子屋，蕾姆已经看过很多孩子的样子，所以是明白的”

“如果将那个作为证据的话，我有点烦恼是不是要同意呢”

但是，回过头来看的话，刚才说服缇雅的论调确实很像教师的口吻。也就是说，说服成功可以归功于蕾姆作为教师的才能。

“不愧是老师。真是厉害”

“嗯，这是当然的。但是，比起老师，在昴的面前我更想听到妻子的称呼”

“……没错呢。不愧是我的妻子。真的是最为可爱并值得我信赖的人啊”

“嗯，说得很好哦”

像是在调戏着改正了话语的昴一般，女教师蕾姆表扬了他。那样的微笑令昴不禁挠了挠头。真是败给了她呢，昴似乎是这么想的。

眼尖的缇雅察觉到了两人鬼鬼祟祟的交谈，便横起了眉毛。

“等等！你们在鬼鬼祟祟地干什么……难道说，是在讨论光珠的事情！？”

“即便假设我们是犯人，也不可能粗心大意到鬼鬼祟祟地在持有者面前交谈的程度吧。比起那个，你究竟要待到什么时候，如果得出结论的话……”

“你在说什么啊。我不是说过的嘛，在你们露出破绽之前我会一直监视着你们的。会一直待在这里的哦”

面对着缇雅理所当然般的说话音调，昴歪着脑袋问道，

“待在这里是……要到什么时候？”

“到你们露出破绽之前”

“……”

“即便这么说，三个人住在这个房间里实在有点吃不消呢。难道说，那边的狗也要住在这吗。那样的话不只是狭窄，房间里还会满是狗毛呢”

“你是要赖在这儿了吗！？”

出乎意料的致命威胁令昴发出了悲鸣。听到了那样的声音后，缇雅极为愉悦地动了动唇。

“啊啊，这悲鸣真是让人难耐……终于听到了，稍微感到有点满足呢”

“这可不是玩笑！谁会和你一起住啊！这里可是夫妇的家啊，给我好好考虑下！”

“……？蕾姆已经怀孕了不是吗？我住在这里有什么问题吗？”

“那是……那是？”

即使是被问道那样怎么了的昴，也一时无法给予答复。缇雅并没有什么嘲弄的意图，只是纯粹地说出了疑问罢了。

确实，如果不追求夫妇间性行为制造小孩之外的意思的话，缇雅的想法是正确的。

“但是，为了保证家庭的美满，夫妇二人的夜晚是很有必要的……”

“盯——”

“快住手！不要用那种眼神看我！就算你那样看我，我也是不会和你同居的！”

面对缇雅充满疑问的目光，昴说出了借口，却依旧没有令她屈从。而且除了夫妇的问题外，确实也同缇雅所说的那样，这个房间对于三个人来说实在太过狭窄了。

“我想，大概作为管理人及房东的阿赫也是不会允许的吧。你可是破坏房间，还把我打得浑身是血的罪魁祸首啊！”

租赁物品被这样的破坏掉后，几乎没有哪位房东还能豪迈地进行租金礼金的交涉。

听了抱着那样的期待的昴这么说后，赫鲁贝尔抱着胳膊点了点头。

“没错呢，正如阿昴所说的那样。首先要谈谈关于这个房间的赔偿呢”

“我可没有这么说！”

这可并不是希望房东说的话，面对昴这般的控诉，赫鲁贝尔并不打算听。站在一旁的缇雅转了转眼珠，指着自己说道，

“我来赔偿吗？这个房间的物品？”

“因为是缇雅大人破坏掉的，所以也是必须的……可以的话，作为受害者的蕾姆和昴的生活日用品也拜托了”

蕾姆看了看被狂风席卷过并散落在房间各处的物品的情况，向缇雅提出了这样的请求。

房间里的榻榻米和墙壁自不必说，就连书架和家具等物品也被风刃狠狠地蹂躏了。虽然有些餐具勉强逃脱了受害，但衣柜里的衣服以及壁橱里的被子大概情况很不妙。

在想方设法地得到了少量的收入后，准备好的生活用品却全被破坏了……稍微有些想哭。

“因为我会帮忙收拾房间，所以请把这里变成缇雅大人能够生活的地方。赫鲁贝尔大人，蕾姆和昴能否借住别的空房间……”

“啊---，可以哦。就如同你知道的那样，大宅里到处都是空房间。可以选你们喜欢的房间搬进去哦”

“您真是帮了我们大忙”

昴收拾着损坏的餐具，因为回忆被破坏而感到低落。而作为对那样的感伤满不在乎的现实主义者，蕾姆和赫鲁贝尔尽快地分好了房间，并确立了今后的方针。

这样顺利的进展，让一开始将主导权握在手中的缇雅渐渐失去了主导，她呆怔地看着一切，伸出手来摸了摸自己的脸颊。

“总感觉……你们可真是顽强呢”

“关于那个我也深有同感”

这个时候的昴，也是十分赞同这位美丽荒谬的杀手的话的。

5

“阿昴，可以和你谈一下吗？”

没错，昴正准备和向他招手的赫鲁贝尔一起到大宅外面时，缇雅正不情愿地跟着积极整理房间的蕾姆一起收拾着。

蕾姆将和服的裙带系了起来，完全沉浸在打扫屋子的快乐中。无论是谁，都无法阻止处于那种状态中的她的斯巴达式打扫。实际上，缇雅也无法应对蕾姆的魄力，只能不起劲地老实帮忙着打扫。

“那样看上去，即使稍微离开一下也没有关系呢”

看见主导权掌握在了蕾姆手中后，昴走出了屋子来到了大宅外面。现在太阳已经落山，天完全黑了下来。可以看见夜空中圆圆的月亮及闪闪发亮的星星。

抬头仰望那样的星空后，身上紫烟缭绕的赫鲁贝尔说了句“抱歉”，便开始了话题。

“谈话的时候，阿昴很心惊胆战的对吧？什么都做不了可是很难受的”

“这种道歉的话就不要……虽然想这么说，但我确实很心惊胆战。尤其是缇雅开始破坏房间的时候”

在谈话一开始就提及到了扫除房间的原因，这令昴不由得瑟瑟发抖起来。

在那样猛烈的风中，赫鲁贝尔毫无动作，只是观察着局势。而蕾姆之所以没有动，是因为她有着毅然的意志力。

那样的话，那时什么也没有做、只是沉默地观察着缇雅的胡作非为的赫鲁贝尔，他的意思又是什么呢。

“那位女子身上没有杀气，但是却有敌意。因此，她的暴行是不会伤害到任何人的，这点我很明白。……不过或许阿昴并不明白我这样做的道理呢”

“虽然不能理解，但也不是不明白。虽然我注意到的时候已经很迟了，但要是我事先能看到结果估计也会这么做。只是……”

“果然，只要一想到蕾姆的平安就想要阻止她呢，对吧？嗯，因为我也有过这种想法，所以还是应该和你道歉”

赫鲁贝尔放下了烟袋，说了句“抱歉”后再次深深地低下了头。

要按合乎道理来说的话，赫鲁贝尔并不需要向昴说这些。因为本来就是赫鲁贝尔出自好意地给予了两人帮助。站在没有被要求支付使他满意的报酬或是谢礼的立场上来说，只是想要指责他的判断的话，未免有点太过傲慢了。

“虽说如此，但下次就很难有这一句话了。危急的时候，我要是大意地动了一下使得自己擅自被风命中，这样也是可以的吧？”

“那种锐利度，即使手脚断了一两只术师也是可以接上的呢”

“要是一不小心连脖子都断掉了的话，可是会死的哦！”

是否会一命呜呼可是由被击中的地方所决定的。没有击中要害就是运气好。感受到要闯过离死亡一纸之隔的绝境的觉悟后，昴悄悄地往下抚摸着胸口，似乎松了一口气。

“阿昴能允许我这样做就太好了。昨天晚上我也没有赶上，使得房间变得破破烂烂的，这令我很沮丧呢”

“是那样的吗？”

“暂且不论卡拉拉奇最强的头衔什么的，我好歹也是暗杀者的一员啊。就这样被别人钻了空子什么的，真是一点都不有趣呢”

对于赫鲁贝尔的自负，昴托起了下巴，像是在问“是这样的吗”。

要说起忍者的话，他们扮演着多种多样的角色，像是潜入敌人内部打间谍战、暗杀及使用忍术……但是，忍者的特征果然还是站在古代的间谍一般的立场吧。如果反间谍失败的话，确实是很失态的。

“那样的情况下，不能拜托一下阿赫的部下吗？卡拉拉奇最强的忍者，应该指的就是暗杀者集团最强的头目吧？”

“暗杀集团可不是那种骚动不安的团体啊！找到除我之外的忍者可不是能草草决定的事。阿昴的想法是根据什么产生的啊？”

“暗杀者的故乡什么的，应该会有那种专门的教育机关吧？”

“如果是指因为种族原因而隐居在偏僻之地的村落的话，我是听说过的，但是我的狼人一族因为没有逃跑隐居而几乎全灭绝了……”

“灭绝什么的真是笑话！”

忍者如果成为了濒危物种的话，狼人也会成为同样濒危的物种。赫鲁贝尔就会是传闻已经灭绝的文化和种族间的混，也是代表正衰退着的种族的合适人选。

“也就是说，对于阿赫的忍者才能不能抱有过高的期待吗”

“虽然我不明白忍者是什么，但倘若抱有过高期待的话确实会令我困扰的哦。为什么从我刚才道歉开始，阿昴就开始提出别的提案了呢？”

“提案是说？”

“……那个叫作缇雅的女子，消失掉会比较好，你现在的提案和这不一样吧？”

那不过是用和平时一样的爽快语气所说的话语。但不知为何，这番话却令昴完全没有了动作。在缓缓地经过了五秒、十秒之后，

“阿赫？”

“那位女子没有杀意，现在也收起了敌意。就算是那样，她是危险的女子，这点是不会变的。如果现在毫无防备地向她暴露了弱点，就会什么都做不成地被收拾掉”

“那是……但是，正因为如此所以才”

虽然看不见赫鲁贝尔眯缝着的眼睛深处流露出的是怎样的情感，但是他的话语确实有一定的说服力。在这里斩断后顾之忧可能也是一种选择。

在探寻了蕾姆和缇雅表面上可以共存之后的现在也是如此。

“缇雅酱啊，是可以阻挡我用鼻子追寻的人。不只是昨天所说的，现在也是如此”

“现在也是？那是指可以消除气味的计策吗？”

“真是周到呢。我也没有听说过她自己所说的‘死神'这一外号，说不定原本是一个美人呢。因为被街上的人讨厌而有了谣言，但是，我却是不知道的。我不知道的事情，几乎没有人会知道”

针对赫鲁贝尔的嗅觉采取了完美的对策，到现在仍无法窥探到本性的谜之女子——缇雅，她所处的立场至今仍未改变。

不过，现在能做到的就只有能够和她交谈以及暂且拖延了决裂这两件事。而这些约定对于按照心情来行动的她来说，究竟又有多少效果呢。

“因此，趁现在什么都还没发生的时候是能够动手的。虽然有必要对蕾姆酱说谎，但对付那家伙的事就交给我吧”

赫鲁贝尔提出了冷酷的提案后，全身散发出了冰冷的气息和血腥味。

看到他那副样子，昴第一次理解了一件事：站在自己眼前的男人并不是一个善良的游玩者，而是被冠以卡拉拉奇最强者之名的暗杀者。

同时也明白了释放出如此冰冷威圧感的赫鲁贝尔的意图。

“……真是不好意思啊，阿赫。让我接受你那种恶人设定什么的……”

“……”
“不过，我觉得没有必要扮演恶人的哦。虽然我也并不是很放心……但蕾姆都对缇雅那么说了，那样的话，我也愿意试着去相信一下”

“你能相信那位女子吗？”

“我相信的并不是缇雅，而是说服了缇雅的我妻子的眼光。”

两人的背后，房间里的整理和扫除还在继续进行着。而略微能听见的声音，正是干劲十足的蕾姆和不情愿的缇雅的对话……那样看来，似乎进展得很顺利。

如果能够不用顾及杀与被杀的关系就能结束事情的话，昴想从那里找到希望。

“……阿昴的性格还真是很吃亏啊”

听了昴的回答后，赫鲁贝尔重新拿起了烟袋低语道。他全身所满溢出的寒气在那一瞬间消失殆尽。只要没有了这些的话，留在那里的就只是跟平时一样悠闲的狼人。

果然，刚才的态度是在表现对昴的担心——在昴说出了作为忍者行动，以此来排除危险的时候，为了减轻他的罪恶感，赫鲁贝尔所给予的关怀。

“即使你在怎么说我性格吃亏，现在的阿赫不也还是认输了吗”

“并不是这样。大概是因为我并不知道将你打个半死的对方是否洗心革面了，所以姑且原谅她——这种老好人的话我是不会说的”

“啊，这么说来”

被赫鲁贝尔这么一说，昴回忆起了被缇雅打成半死不活样子的事情。在理解了她的强大时，反过来却遗忘了她本身具备的暴力性。

正因为这个道理，赫鲁贝尔才担心着昴和蕾姆。

“难道说，你已经忘记了吗？你的身体现在不是还到处疼痛着吗？”

“别说了啊，我连疼痛都回想起来了……”

昴回忆起阵阵疼痛后，不停地晃动着手脚喊着“疼疼疼”，并露出了悲惨的表情。看到昴的那副样子后，这次换成赫鲁贝尔呆怔了一下，随后长长地叹了一口气。

“阿昴和蕾姆酱都这么说了的话，那就算了。我就先什么都不做吧。”

“真是令人感激不尽……话说，我是应该这么说呢还是该换成其它说法呢。嘛，不过确实受到你很多照顾”

“我可是施恩增加了的一方呢。真是很期待你给我回报的时候啊”

赫鲁贝尔笑着这么说道，他看上去并没有催收“恩情”的打算。然而昴听了之后却变得嘴角僵硬并低下了头，像是在说正是如此一般。

从来到巴南这条街以来，就一直承蒙了很多人的照顾，被很多人所拯救过。

“总有一天，我会把受到的所有恩情返还给你的哦”

“如果在那之前你就死掉的话，我会很困扰的，所以要努力地活下去哦！”

“那样的话，我会再次以尽可能前进的理由活下去的哦”

昴笑着回答了赫鲁贝尔的话后，挺直了身子。正巧那个时候，从房间里传来了呼喊两个人的声音。

“昴，请过来帮我挑选一下看上去还完好的衣物”

“你们这些家伙光是在那里开心，所以说雄性生物可是没有信用的哦。你们究竟想要在外面狩猎到何时”

受到蕾姆和缇雅的指名后，昴和赫鲁贝尔相互看了对方一眼，便分头行动了起来。

赫鲁贝尔放下了烟袋，而昴则是轻轻地活动着身体。

……大宅的喧闹日常就这么日夜交替着。

** 第三章 『六个月』

1

昴和蕾姆两人很快就办妥了搬家事宜。

这也多亏了之前两人迅速把未被殃及到的行李物件都转移到了隔壁房间。

新的房间分配也很顺当地就定下来了，原先昴他们住的房间被腾给了缇雅，而以这个房间为中轴，昴和赫鲁贝尔分别紧挨着其左右住下了。

尽管之前也有人提议干脆两两之间各自空出来一个房间——

但缇雅立刻就一脸狐疑地嚷嚷起来

“特地和左右邻居隔开一个房间住，简直就像摆明了告诉别人有什么见不得光的事一样不是嘛！”

于是只得作罢。

然而，或许也是厚度的缘故，隔着一堵墙隔壁房间的声音也听得真切。过了几晚之后、意识到这一点的缇雅这才涨红了脸叫悔不迭。

然而不管怎样，搬家事宜也顺利结束，和奇妙的邻居们的同居生活也就此拉开了序幕。

“挣不到钱可不行啊”

“大清早的，开口第一句话就说这些”

大家围坐在一起吃着早饭，缇雅一手拿着一根筷子突然蹦出了这么一句话来。

面前的圆桌在昨晚彻底成了两半，硬是把坏掉的板子给拼在一起这才有了这个救急用的临时餐桌。

而餐桌前却不知怎的混进了两个不请自来的编外人员——正是缇雅和赫鲁贝尔。两人厚着脸皮坐在那里稳如泰山，甚至仗着蕾姆人好又找她添了饭。

缇雅拿筷子的姿势过于笨拙，只见她满脸都沾着饭粒。

“听我说好吗？尽管我同意了在那种寒碜的屋子里住下，但一直那样破破烂烂的真的很讨厌啊、我不要了啦。所以啊我才和狗赫说了让他赶紧把屋子修好。结果呢”

“要是让我帮阿昴他们垫还说得过去，借给你门也没有。借钱是必须得建立在相互信任的基础上的。倒不如说正是借钱才导致了信赖关系的覆灭呢，你这脸皮是有多厚啊”

“哎呀，你看吧！喂，你怎么想 ”

“我注意力全在你脸上了根本就没听到你们在说什么啊、饭粒星人”

饭粒妆果然还是在时代前沿的路上走过头了，至少以昴的理解能力是看不懂的。

听了这话缇雅的脸立刻垮了下来。而蕾姆温柔地一粒粒帮她把饭粒从那张怏怏不乐的脸上取下来，点点头说道，“我知道了”。

“缇雅大人正在找工作是吧？这对我们来说也不算事不关己呀”

“啊，就在最近总是会听到这种扎心的话啊……”

“昴君离被正式雇用就差一步了。已经甩开缇雅大人很远了呢。这已经掰不回来了。是昴君赢了。”

“那就是那臭男人赢了吧，所以说你到底想表达什么啊”

如是声援着昴的蕾姆有点小得意地嗯哼了一声，缇雅见状立刻举起手来催着她继续说下去。

蕾姆回过神来先是作势轻咳了一声这才说道，“蕾姆有一个主意，或许可以去拜托中介吧。要是缇雅大人能通过自己擅长的工作来挣到钱的话就再好不过了呢。”

“也就是说，要找克莱茵的中介是最好的……吗。对了，你比较擅长些什么呢，又或者有什么证书之类的吗？”

“我的特技就是杀人哦。不过我现在没有杀意啊”

“哪儿能找叫你找到那种抱着打零工的心态就能做得来的杀手工作啊！”

缇雅抱着胳膊煞是得意地挺了挺自己壮观的胸，脸上还粘着几个残存的饭粒。

不过真要说，万一真按照她所说的给她找了杀手的工作，没准儿很快就要后悔昨天晚上做的判断了。

昴瞥了一眼对这个小城可谓了如指掌的赫鲁贝尔，投去无声的求助。

“嗯，说的也是。按规矩，招杀手的告示是不允许贴在中介那里的布告牌上的”

“就、就是嘛”

“那种事儿不得不在背地里干啊。也只有老相识才能互通有无啊”

“那是不愿暴露在阳光下的这个城市的黑暗面啊——！”

原来哪怕是公认的中介，竟也会悄悄在暗地里做这些勾当啊。昴觉得自己像是看穿了那个蜥蜴脸男人的所作所为、不禁有点儿厌倦起来了。

“不不不，开玩笑而已啦，玩笑。要是你当真了我反而就难办了啊”

“诶？玩笑？什么啊，原来这样，太好了。我还在想今后要拿什么表情面对那个穿着可爱围裙的蜥蜴脸呢”

“克莱茵那里是不会接手这种事的。那种有专门的私底下的中介管”

“我今后也只会去找正规中介的”

“不过啊，如果这次昴君能一举拿下这个工作的话，也就不用再劳烦克莱茵大人了呢，咱们就以这个为目标努力吧”

“喔喔，说得没错啊！”

听得蕾姆这么一说，昴才意识到自己已经在不断放低标准，都快以为自己要做一辈子家里蹲了。心里一边感谢着蕾姆的提醒，昴对这份宅邸的工作越来越有干劲了。

昨天也承蒙了一干相关人等的关照，从今天开始更要马力全开好好干了啊。

“这样一说，我现在可是干劲满满哪。好嘞，我这就出门了！”

“好的！”

“什么好的了啦！那我要怎么办啊！？”

昴和蕾姆两人情绪高涨，正手拉着手准备起身呢，只见缇雅立刻火山爆发了。

她用手一把抓起盘子里剩下的食物丢进嘴里大嚼特嚼，“就把我介绍给那个，也不知道你们说的是谁反正就是那个黑中介啦！呐，我是要去做杀手的！”

“你傻吧！谁会让你做那种见不得光的工作啊！阿赫你也说说她啊！”

“虽说我自己做的呢，也称得上见不得光的工作的代表之一……不过真要说，让她去杀人的确有点那什么，那要不就只能做那个了吧。去应聘别人的讨伐委托啦，当个赏金猎人什么的”

赫鲁贝尔打了个响指无不得意地说道。而缇雅只是微微地歪着头像在思考。但一旁的昴却为这份工作的浪漫色彩而眼睛发亮。

“赏金猎人！讨伐委托！这听起来酷毙了！”

“详细来说到底是一份什么样的工作呢？是缇雅大人能做的吗……？”

比起动不动就激动的昴来，蕾姆就显得要现实多了。她的视线停在缇雅周围被糟蹋得一片狼藉的餐桌上——很显然缇雅是不具备处理需要细心的工作的能力也不讲究礼仪什么的，而蕾姆担心的也正是这一点。

“嘛，大体的工作内容也就是去逮捕那些被通缉的恶党啦，偶尔也不过是去狠狠地教训他们一顿，然后就是碰到那些祸害人间的魔兽也得一并讨伐了之类的”

“也就是去猎杀喽。这可是我超擅长的啊！”

说着只见缇雅眼里闪过一道光。她双手撑在餐桌上一跃而起，兴冲冲地一把抓住正准备饭后抽一管的赫鲁贝尔的衣领。

“嗯嗯？”

“喂，就当回向导带我去吧。毕竟我连要猎杀什么都还不知道哪”

“喂喂等一下！阿昴啊！蕾姆酱！”

“一路走好啊”

“啊啊咧！”

反抗无效，被缇雅的蛮力给扯着，赫鲁贝尔挣扎的背影一会儿就消失不见了。

作为昴来说，他是没什么立场去阻止的，真要说起来他也没那个自信能阻止得了。

闹腾得不得了的邻居们走了，家里就只剩下夫妇俩也没外人了。

“唔唔……就这样把缇雅大人托付给赫鲁贝尔大人了，真的没问题吗？”

“嘛，是阿赫的话肯定没问题的吧。万一缇雅她想生事，除了阿赫也没人能制止她了。让阿赫跟在旁边也算是多少能管着她一点，这样不是更合理吗。”

“原来如此，这样一说还真有道理呢。而且如果不偶尔让赫鲁贝尔大人跟普通人一样在白天也出去走走的话，他肯定也会闷坏了吧”

蕾姆立刻领会过来，不动声色地带了点嘲弄的口气，为赫鲁贝尔打着气。

事实上，把缇雅全权委托给赫鲁贝尔已经成了既定常识了——就连赫鲁贝尔本人也认了命，而之前他不情不愿的态度也就跟例行花絮一般，可以说也就是为了追求形式美而已。

所幸，由于目前这边已经掌握了袭击者缇雅的一举一动，也就不用赫鲁贝尔再跟在昴和蕾姆身后当保镖了。两人也就不用为突如其来的偷袭担惊受怕、提心吊胆地工作了。

“接下来就剩我能不能被正式录用，还有蕾姆你的身孕了。”

“……目前看来，还是能正常工作一段时间的”

“毕竟这是你第一次生孩子，我不想大意。就我疏浅的知识来看，一直到孩子出生大概要十个月零十天吧”

据昴所知道的，从怀孕到出生大概要十个月左右——然而，现在也无从得知蕾姆是什么时候怀上的，也不知道现在有几个月了。从肚子还看不明显这一点，可以大致推测大概只有三个月这样。不过除此之外，也还是有其他问题的。

蕾姆是鬼族——即便看起来与常人无异，但实际上她是亚人一族。这样说来，人类怀孕和生产的经验，又到底能不能直接套用在她身上呢？更何况这次还是人类和鬼族的混血儿，实在是有太多不确定因素夹杂其中了。

“除了要请那位精通治疗术的术师来看一看，其他还有什么我能为你做的吗？”

“对不起。蕾姆也不是很清楚这方面的事。这种时候……”

“——”

“这、这种时候，要是能找到经验丰富的产婆就再好不过了呢”

蕾姆犹豫了一会儿，还是吞吞吐吐地说了出来。然而昴却没有对这异样的踌躇有任何反应，只是点了点头道，“说的也是”。

蕾姆最开始想要说、最终却还是没能说出口的话，昴是知道的。而绝口不提这件事，也是昴和蕾姆间共有的默契。

为了避免再深入从而触及到这件事，昴像要重新振作起来一般，开口说了句“好嘞”。

“那暂且在身子还不明显的时候就跟以前一样过吧。不过万一你哪儿有什么不舒服了一定要立刻跟我说啊。哪怕是发低热也要。你下次再瞒着我我就要发火了”

“蕾姆知道了。但是，要是昴生气了要怎么办呢？”

“那还用问吗。当然是把你给关进屋子里，由我来一直看着你。那期间的种种生活费只好找阿赫借了，到最后咱们一屁股债，等孩子生下来再拼命挣回来好了”

“那……实在是太可怕了。蕾姆真是服了昴君天马行空的脑洞了呢”

蕾姆一边咯咯笑着，一边又真的很害怕一般蹭到了昴身边。昴怜惜地搂住蕾姆纤细的肩膀，很长一段时间两人就这样沉默着相拥在一起。

转眼间就到了要各自出发去工作的时间了。

“那好，今天也要努力奋斗啊。就让我们默默祈祷阿赫和缇雅一切安好吧”

“默默祈祷，对吧。”

两人临走前又互换了一个心领神会的笑，走出自己的新卧室出发了。

——一直到那天的黄昏，两人才知道自己的祈祷完美地落了空。但却也是某种好的意义上的落空。

2

“这次逮捕那是干得相当漂亮啊，就连本大爷我也难得见一次”

缇雅抱着个鼓鼓囊囊装满了报酬的袋子进了门，得意洋洋地双手叉腰一脚踩在餐桌上。被蕾姆指出实在不成体统后又转眼变成了一只霜打的茄子。

而对缇雅的首次工作，赫鲁贝尔倒是毫不吝啬地给出了这个甚好的评价。

餐桌上已经摆上了晚餐，而那只塞着报酬的袋子被扔在一旁的榻榻米上。看着旁边正老老实实低着头听着蕾姆说教的缇雅，昴不禁怀疑起赫鲁贝尔的评价来。

“哎呀呀，虽然你怀疑的心情我也很能理解的”

“看到这一幕让人怎么也……嘛，要真是一切顺利那自是再好不过了。你说的那个，相当漂亮的逮捕是怎么个漂亮法啊？给我们详细说说”

“嗯，一开始我们就按计划好的，挑了个逮捕通缉令上一个小毛贼的活儿。但是呢，在途中咱们一下遇上好几个通缉犯……再怎么说我也不能只站在一边袖手旁观嘛，结果场面就闹大了，最后一番激战总算是擒来个大猎物哪”

听起来像是缇雅被带到克莱茵那里，在赫鲁贝尔的担保下小试身手，在店里的布告板上选了个合适的通缉犯，一步步锁定目标最终大获成功。

“那家伙本是个四处行窃的小无赖而已，咱们把他给堵进他自己的老巢，没想到那屋子里尽是些魔法石还引发了不小的骚动。结果那家伙走投无路狗急跳墙，竟想用魔法石自爆”

“这简直是恐怖分子啊！”

“然而呢，我们的缇雅酱上去就是一顿胖揍给他放倒，五花大绑捆了个结实。这下子那家伙就吓得不打自招了，说是自己还有个更危险的同伙在搞走私，在这整个城里都埋伏着他的党羽。三两下问出了他们的老家窝，咱们干脆连带着一起把他潜伏在城里的喽啰全都给一网打尽了，把他们的都市毁灭计划扼杀在了摇篮里哪”

“这种好莱坞超长大片一样的情节就今天这么一天就结束了！？”

没想到这竟然还牵扯到了整个城市的存亡大事，昴惊得嘴巴都合不拢了。

他们经历着生死关头那会儿，昴还一无所知，正在公司和女性同事们请教着孩子的教育问题，反被同事们笑道太猴急了。

“那，救了我们整个城的女英雄就因为把脚踩在了饭桌上被教训一通，变成了霜打的茄子啊”

“诚然如此啊”

赫鲁贝尔若有所思地深深点了点头。

两人一同望向缩成一团缇雅，她正接受着蕾姆涨红了脸关于礼仪重要性的谆谆教诲。蕾姆的说教并不是大吵大嚷类而是轻声细语却拷问良心的，应该更让人痛苦。

“所以说啊，礼节是很重要的。不仅是对一起用餐的人们的敬意，更是对那些端上桌的食物、对食材的敬意。明白了吗？”

“是是是，明白啦明白啦。小-的-明-白-啦”

“缇雅大人？”

“我，我不是说我明白了嘛……”

或许是即将成为母亲的缘故，即便是面对实际差距甚大的对手蕾姆也相当威严不留情面。被她的气势震慑住的缇雅畏畏缩缩地调整姿势，老老实实地端坐在餐桌前。

看着缇雅乖乖低头认错，蕾姆轻轻叹了一口气说道，“缇雅大人，给你”

“诶，这是……”

“看你用筷子吃很为难的样子，你要珍惜着用哦”

那是一把木质的勺子——把它递到面前的蕾姆笑得温柔，缇雅有点惊讶地睁大了眼，旋即又闭上了，

“还，还算伶俐嘛。好吧。我就勉为其难地用这个好了”

说着缇雅接过这柄作为礼物的勺子。脸上泛起一片绯红。

“虽说这不是驯化时的投食，但总觉得很像啊……”

“不过，按照这个形势来看，暂且算是阿昴赌赢了一局啊”

“不过呢，要是说打赌缇雅会不会惹出事儿来的话，赢的可是蕾姆哦。现在也是啊”

“啊啊，说的也是啊”

昴闻言咧开了嘴，赫鲁贝尔也爽朗地笑着赞同道。说教完毕的蕾姆看着笑得灿烂的两人，轻轻拍了拍手。

“那好，咱们快吃饭吧。今天是缇雅大人工作第一天，再加上赫鲁贝尔大人也跟着后面奔波，今天的饭会格外得香哦”

“说的倒是一点儿没错，我也有的吃吗？”

大家都听从蕾姆的指示围着餐桌坐下。虽说心里是有点担心有没有缇雅和赫鲁贝尔的份的，但看着两人一脸理所当然天经地义的样子昴也不好说什么。

大家齐声道了一句“我要开动了”（缇雅自然也被迫跟着），美食便很快带走了之前的违和感。今晚是蕾姆特制的以烤鱼为主的和风料理，让人不禁食指大动。

尤其是缇雅吃得好不豪爽，一脸满足的样子。

“行，行啊你，蕾姆。鱼肉鲜嫩爽口的口感，加上那故意烤至微微焦黄的部分独特的风味，简直叫人停不下来啊……！”

“谢谢你，缇雅大人。其实呢，要加上了这个白色的蔬菜丁一起吃味道更好哦”

“——！骗人的吧？味、味道竟然能这么清爽可口！？”

看着缇雅一惊一乍的样子，蕾姆也相当受用，愉快地给她投着食。看起来就像是在给一头奇珍异兽投着在它的生物圈里本不存在的食物，为它的反应愉悦不已的样子。

看这样子昨晚杀气腾腾的紧张气氛像是飞到了九霄云外般，昴也暂且松了一口气。

“吃了晚饭后肯定是泡澡啦，泡澡。今天也大赚了一笔，泡了澡出来喝杯小酒也不过分吧？”

“要是你不劝昴君和蕾姆喝的话，蕾姆倒是不会说什么的哦。缇雅大人也不行”

“还是别了比较保险吧……”

三人面面相觑，又一齐把视线投向缇雅。她正聚精会神地试图把碗里剩下的几颗饭粒给送到嘴里，好像根本没听到他们在说什么。

无论怎么看，她都是那种一旦醉了就不知道会做出什么不可预料的举动来的可怕少女。既然这样那就只能对不住赫鲁贝尔了，看来他今晚得一个人自斟自饮了。

毕竟昴是不怎么喜欢酒的，也不会主动去喝，蕾姆虽然作为鬼族却少见的不会喝酒，也难怪她一次也没陪赫鲁贝尔喝过酒。

“切，一个人多没意思”

看到一个两个都不愿意当自己的酒友，赫鲁贝尔惋惜地哼哼着，胡子也跟着他的动作发颤。正巧缇雅总算消灭光了饭粒，听到这声叹气便歪了头问道，“怎么了？”

“你们在说什么呢？我肚皮都撑圆啦，也想早点睡了”

“那可不行呀。奔波了一整天干成了这么个大任务，肯定出了一身汗吧。——所以，必须得先洗个澡哦”

“……要是随便冲一下的话，我又没说我不干”

“不是！咱们去浴场泡澡吧！”

蕾姆一把探身到兴致缺缺的缇雅面前，劲头十足地提议道。缇雅一时被蕾姆的气势震住了，向昴和赫鲁贝尔投去求助的眼神。然而，很遗憾——。

“——好主意”

“是呀是呀”

并没有一个人站在缇雅这边。

3

——这个世界的“浴场”倒是没有什么特殊之处，也就是字面意思上的大众澡堂。

宽敞的空间里是一个巨大号的浴池，里面的水被底下的魔法石发出的热量煮得刚刚好。正是因为加热道具特殊，也使得浴场成了极简主义风的产物。

这和原先世界太过相似，以至于昴一开始还为其存在惊讶不已。

“嘛，之前在漫画里也看到过，说是在古罗马时代就已经有了公共的洗浴设备了，相比之下这里有个浴场也算不上不可思议什么的啊”

更何况在卡拉拉奇的和风文化里就连忍者都出场了，所以现在看来光是泡澡的浴场和凉拌萝卜丝什么的也就无足大惊小怪了。

“要是再碰见个日本的象征性吉祥物什么的那可就更要大吃一惊啦”

“从刚刚开始你就一直在嘟嘟囔囔地说些什么呢？”

就在身旁不远处的忍者朝这边搭了话，他整个人都泡在浴池里，水淹到了他的脖子。那张精悍的脸上和身上一样挂满了水珠，头发也湿漉漉地贴在额上。

这样一来简直就像落汤鸡一样，也就只有体格和脸还是原来那个模样了。

“在异世界生活感到最大的问题，就是这不同种族间的差异导致统一文化习惯难以形成啊。甚至有时从这浴池里出来，全身都黏着不知道是谁掉的毛发”

“那不只得在旁边的冲洗处再冲一遍了嘛。还是说，阿昴想到了什么有趣的主意吗？”

“这个嘛。……或许可以沿着浴池的边缘挖上一条排水沟，用魔石的力量来控制水流轻轻冲上一圈。再设上一个能把那些毛发给拦住的网，这下流回来的就只是清水了”

“嗯嗯嗯？那啥，要不你下次画个图给我看看吧？没怎么懂啊”

昴一边回想着夏天的泳池一边认真地想出了这个提议，但显然舒服地仰面躺在浴池里、舒服地感叹了一声的赫鲁贝尔回答得相当敷衍。然而，这也不能怪他。

泡在这暖和又叫人舒服的浴池里，任谁都会变成这样，暂时失去思考能力退化成了动物。这跟昴刚感叹过的种族差异完全是两码事。

——叫人只想沉溺在这如母亲的子宫般温暖的浴池里。

“所以说啊，我是挺想忽视掉墙的那边传来的声音的”

“喂、你看啊！这里超棒的对吧！？这是什么地方啊，哎呀，初体验！”

“啊，阿昴，看来我做不到啊。瞧啊，那边那边”

昴正把手巾盖在脸上享受这温度，而耳熟的大喊大叫加之被旁边赫鲁贝尔敲了肩膀，他不得不作出回应。

拿下脸上的手巾，顺着赫鲁贝尔手指的方向看过去，那是一堵高墙——正是为了隔开男女浴池而设的。

不知为何，浴场总是要用一堵墙为男女浴池间架起了完美的通道——

“啊！看到了看到了！喂喂，那边的两个男人！没想到浴池是个能让人这么舒服的地方啊，太厉害了对不对？”

“————”

好像缇雅攀着墙壁爬上来、好不容易探进了这天花板和高墙的窄缝里，两人一抬头就和她四目相对。正天真烂漫地挥着小手的她应该是全裸的，所幸胸部以下好歹是被墙给遮住了。

即便如此，那湿漉漉的铂金色长发披散在她曲线优美的裸露着的脖颈上，垂到她雪白的肩膀上，显得极具女性魅力，老实说是相当诱惑的。而就是这样一个天上有地下无的大美女，却来了个突袭，男浴池里立刻起了骚动。

“呀啊啊啊！！”

男浴池里响彻着如同裂帛似的……当然实际上是要比那粗犷了好几倍的悲鸣。

只见有跌在地上滚成一团的，有飞窜进更衣室的，还有连忙跳进浴池的，一时间可谓鸡飞狗跳。而始作俑者缇雅在墙上俯视着下面乱成一团的景象，无辜地眨巴眨巴大眼睛。

“虽然不知道发生了什么事，但看着一群雄性生物四散而逃的样子还挺让人有快感的……”

“谁管你那恶趣味啊！快给我下去！”

“诶，可是明明这里看下去的风景这么好。啊，对了。我们这边的浴池和你们那个有什么不一样吗？能让我试一下吗？”

“是不是傻……！”

缇雅毫不犹豫身形灵活地一闪便要翻过墙来，众人立刻试图制止，但很悲哀的是浴池和那么高一堵墙之间的距离不是立刻就能解决的。

看来就只能任由缇雅胡作非为了，昴几乎要绝望了，众人也不约而同地咽了口唾沫。

就在那一瞬间。

“啊咧！？”

只听得一声尖锐又来势汹汹的摩擦声响彻两边浴池，下一秒缇雅的身影立刻就从墙上消失不见了。

然而，她并不是翻到了男浴池这边，而是消失在了女浴池那里。还没反应过来就听见隔壁响起重物落在水面上水花四处炸裂的声音，整个浴池都像是在跟着轰鸣，场面盛大。

“——诸位，很抱歉给您们添了这么大的麻烦。还请多多海涵，继续享受这怡人的温度吧”

就在水声的余音缭绕渐消之际，从女浴池那边传来了这样一个郑重又礼貌的声音。不必想也知道那是谁的。

“蕾姆？”

“昴君，很抱歉。我不过是在冲洗处洗了一会儿身子而已……不过，现在已经没事了”

“啊啊，幸亏反应及时。那既然没事了就再好不过了……”

看来是多亏了蕾姆才及时制止了这场灾难。昴满心想要表扬自己的妻子干得漂亮，但另一件事却更让他介怀。

那是——、

“刚刚我好像听到了那叫人怀念的锁链的声音啊……”

“那是护身用的”

“可是这里浴池，蕾姆应该也是没有穿衣服的……”

“那是护身用的”

听了蕾姆固执的回答，昴也没法再追问下去了。更何况中间隔着一堵这么高的墙，昴也没法去亲眼确认。于是这件事暂且就只能搁下，算是悬而未决了。

「真不愧是蕾姆酱啊」

只听得从头到尾淡定得如同事不关己的赫鲁贝尔用一副慵懒的口吻感叹着，他一手拨弄着飘在水里的托盘和酒，一边嘴里也不忘品着一口。蓬乱的头发下是已经带上了酒劲的大红脸。

经历了这么一场小骚动，泡完澡后终于是在浴场入口处和从女浴池出来的两个人汇合了。

恰巧在浴场的入口处有一个像聊天室一样的地方，却也是和更衣室隔开的，让前来洗浴的客人都能闲适地小憩一会儿。基本上会成为上了年纪的大爷大妈们的茶话室，也常常会有刚从浴池里出来的人在这儿放松片刻。

而就在这小房间的长椅上，正横七竖八地躺着一个看上去浑身都软绵绵的女人——

「好像她是第一次在浴场泡澡，兴奋过头到处撒欢不肯出来，结果现在说是头晕难受了」

「所以就擅自把我的专属特等席给占了啊。也罢，一眼就能看出来这是她第一次来啊」

昴小声嘀咕着，看着嘴里含混不清地嗯嗯啊啊着的缇雅正枕在蕾姆的腿上。她雪白的皮肤染上了一片一看就知道是泡澡泡过头导致的潮红，要是这会儿她能神志清醒亭亭玉立地站在那里，想必就成了一道极其勾魂的香艳风景了吧。

然而，她现在邋遢地瘫在那里缩成一团，男人们也就没了去怜香惜玉的心。

「就为了这家伙竟然连团扇都借来了？」

「要是在回去的路上倒下了，那好不容易洗干净的就又要变成小泥人了」

「即便是那样也比现在硬充美女弄巧成拙的好啊……算了，团扇给我。我来帮她扇。嗨呀，嗨呀嗨呀，嗨呀嗨呀嗨呀！」

「喔喔喔喔喔，好苏服～」

昴接过蕾姆手上的团扇，温柔的阵阵轻风转眼就变成了飓风。缇雅被扇得东倒西歪却一副相当心满意足的样子。

然而，很快昴的腕力就到了极限了。他缓缓改变风向，不一会儿风就弱下去了。

「喂喂，给我好好扇呀？」

「少来这套。蕾姆的膝枕可是我的啊，被你霸占着我都没计较了。你还真以为自己是公主呐」

「你吵死了……」

缇雅听了昴的抱怨，一脸不高兴地夺过团扇开始自己扇起来。就在那时，她的右手——上的东西吸引住了昴的视线。

「那是什么玩意儿。是祈愿手绳吗？」

「我也不知道是祈愿手绳还是什么的，是阿赫给我的。他叫我戴上的。是护身符？」

「是护身符啊。真有点没想到呢，赫鲁贝尔大人会给缇雅大人送礼物啊……」

「就是啊，怎么想也不可能是阿赫在追缇雅吧……」

缇雅听了气鼓鼓地嘟起嘴，手里还在猛摇着给自己送风，这副孩子气的模样和她成熟的外表形成了鲜明的对比。虽然也不知道赫鲁贝尔到底是何用意，但或许本来也就没什么特别的意思。再这样穷追不舍下去让她着凉了就不好了。

好不容易来泡个澡暖了身子，还是趁着这家伙还没感冒赶紧把事儿都解决了把她带回去的好。

「好了，接下来就是泡澡的最终仪式了。你也跟咱们一起吧」

「仪式……？」

「是啊，仪式。要是不做这一项的话，那就相当白来了一趟呢。」

昴和蕾姆夫妇俩不容分辨地对一脸惊奇的缇雅说道。缇雅正为他们强硬的口吻困惑不已，而下一秒出现在眼前的脸更让她惊讶万分。

走过来的是赫鲁贝尔——可是，他那一头头发此刻已经干了，高高地蓬在头顶上。和平日里见惯了的形象比起来判若两人。

「你你你是狗赫吗？」

「是是是，是我是我。你看，我带了这个过来。热了口味就差了」

「这、这玩意儿是……什么啊，是兽乳？」

「瞧你说的！」

赫鲁贝尔两手环抱着的，正是装在瓶子里的白色液体——缇雅的说法也不是不对，但要用更高雅更有风情的说法就是。

「入浴后来上一杯牛奶……这可是全世界都通用的仪式啊！」

毫不夸张地说，即便是加上「全」也可以这么断言。反正对昴来说，这是在两个世界都通用的极具形式美的仪式，说成超越世界界限的神谕也无妨。

不过要真严谨地说起来这也不是牛奶，比较理想的叫法是水果牛奶，但把它封进瓶子里冰镇的技术是存在的，就只需要让缇雅明白这一点就行。

「把栓子给拔了！手给叉到腰上！一口气咕咚咕咚喝光！」

昴劲头十足地解说着一连串流程，说罢自己带头立刻实践了这个仪式。

凉润润的牛奶从喉咙里灌下一直流到暖和的胃袋。这种爽快的感觉直直刺激着在水里泡热了的身体的最深处，这正是泡澡的奥义所在啊。

「嗯！」

蕾姆清脆地应了一声，跟着昴后面喝下了牛奶。身旁的赫鲁贝尔和其他刚出了浴的客人们也都一口气就把自己的牛奶喝干了。

「噗哈哈！啊，喂，看你脸上！胡子！变成胡子了！」

「这叫形式美！」

「得了吧！真土，土得掉渣！跟傻瓜一样！」

昴的嘴巴周围白了一圈，就像凭空长出来的白胡子一样。而这也正是完成了这个仪式的证明。

而赫鲁贝尔嘴部的构造使得他免受牛奶的侵害。蕾姆则是悄悄背过身去，轻轻地擦了擦嘴。

缇雅来回看着已经完成了仪式的三人，疑心重重地拔掉了瓶栓。然后把鼻子凑上去嗅了一下，便一手叉腰，咕咚咚地一饮而尽——

「——好喝！」

只见缇雅嘴边挂着一圈白胡子，眼睛发亮地嚷嚷道。

4

凉爽的晚风习习吹拂在回家的路上，穿着浴衣的四个人慢悠悠地向前走着。

“看来浴场也不是想象中的那么糟糕嘛。啊，不过我要先声明一下，我自己也挺意外的呢”

“又没人问你”

走在最前面的是脚步轻快的缇雅，赫鲁贝尔跟在她身后。像是这头一回的浴场体验甚是愉快，缇雅满脸高兴的样子还哼起了小曲儿。

听了半天，昴才发觉那听起来又像是跑调了，又像是故意标新立异的旋律和昨天听到的是一样的。不过这样说来，同一首歌也能唱成这样……

“那是什么歌啊？”

“嗯？也没正式的名字啦。非要说的话……”

缇雅把手指抵在唇上沉思了一阵。

然后——、

“就叫「杀戮之歌」吧！”

“难道就没有别的了吗！！”

听到缇雅嘴里蹦出来这过于张扬的词，昴不禁大声吐槽道。而缇雅只是咋了咋舌，不悦地抗议了一声“什么了啦”。

“昴君说得没错哦。难得是一首这么好听的歌儿呢。”

“又来了。反正你家男人说什么都是没错的对吧，蕾姆”

“是呀，没错啊。一般来说昴君说的总是对的呢。不过偶尔会失策一下下而已”

“我！我发现了，蕾姆在你面前就是苛刻不起来！”

也不知是不是被蕾姆话里无比的信赖感喂了狗粮，缇雅抱头鼠窜。见状蕾姆便接着缇雅的旋律哼了下去。

看来她只听过一次便能记住了大概，听了一会儿缇雅开口了

“……有点不对。不是那样，是哼哼~嗯哼哼~”

“嗯，蕾姆刚刚记不太清了。缇雅大人，请再唱一次吧”

“这种歌你也想听？真的想听吗？那好吧，真拿你没办法呀”

看到蕾姆向自己低了头请教，缇雅心情大好地继续哼了起来。要是不知道这是「杀戮之歌」的话，光是听着这纯粹的音色也足以让人入迷。

自然而然地，蕾姆和昴都安静下来，赫鲁贝尔也没有打破这宁静，默默地走在夜路上。

在这夜色笼罩下的静谧街道上，只有缇雅的吟唱在缓缓流淌。

夜空中挂着明亮的星星，大地上遥相呼应的是一盏盏光影朦胧的红灯笼。只截下这样一幕来看，那便是充满了幻想气息，如梦似幻的一刻——。

“昴君”

“嗯？”

沉浸在这样的氛围中，昴的反应不觉慢了一拍。

看出昴的心里所想，蕾姆浅浅一笑，脸上染上一片绯红。

“也没什么啦”

“没什么？”

“蕾姆刚刚在想啊，要是能一直守着这样的日子，迎来我们的宝宝就好了呢”

蕾姆此刻的笑容就像花儿缓缓绽放开来，她的手轻柔地抚上自己的腹部。她的话语和动作让昴的心里涌起一股别样的悸动，他却无从把它转化成言语，

“——”

他一言不发，有力又温柔地握上蕾姆的另一只手，两人感受着彼此的温度，走在回家的路上。

那便是这样的一个夜晚。

5

——日子一天天地缓缓流逝。就像潺潺的溪流一般、一刻不停地向前。

那是一段手忙脚乱，闹腾不已的日子。

自从那夜合住的屋子里来了那些奇妙的邻居后，昴所担忧的事大部分都并没有发生，却也因此，每一天都过得相当“丰富多彩”。

每天早晨，昴和蕾姆、再加上缇雅和赫鲁贝尔这四人组必定会围坐在同一张餐桌前，已经变成了例行公事。他们会聊着各自的行程，分享着上班前的这一段时光。

“要是没了我的话，那些恶党们可就无法无天啦。克莱茵也是这样说的”

“不愧是缇雅大人呢，已经变得这么可靠啦。蕾姆也很佩服呢。你看我还狠狠心为你多做了一道菜呢”

“就应该多做一道啊！不是什么狠狠心了啦，就应该给我加一道嘛！”

像是因为第一次小试牛刀就尝到了甜头，缇雅已经完全把自己定位成赏金猎人了。而实际上这也的确就像是她的天职一般，据说缇雅的逮捕率不是一般的高。

在克莱茵的中介处受理的任务都是都市公认的——也正因为如此，这工作对巴南这个城市的贡献率也是相当大的。缇雅的活跃也必将改善城市的治安。

“你们好歹也想想这个被迫和她一起行动的我的感受啊，我已经好几天没能在太阳公公露脸的时候睡上一个优雅的午觉了啊。再这样下去我的生物钟都要错乱了”

“这不也正是赫鲁贝尔大人一步步变得更像真人类了的证明吗？”

“蕾姆说的对。你就认了吧，老老实实跟在缇雅后面多跑跑，你前段时间总担心的肚子上的小赘肉也就能消下去了”

赫鲁贝尔一时间成为众矢之的，拉下一张脸没有再言语。蕾姆和昴夫妇俩又忙着去顺毛。而当事人却完全无视了旁边的硝烟，心情大好地一口气喝完了味噌汤，挥着碗嚷嚷着“再来一碗！”

到了中午，过了上班时间，昴也常常来往于玛格洁宅邸。

昴也顺利地得到了盼望已久的工作。这不仅仅是承蒙了利夫坦和老板娘对昴的厚爱，也可以说是昴对两人期望的报答。

只是，要说有什么是和原先预想的不一样的话——、

“——好，今天就先复习一下缝纫的基本功吧”

“知道啦，昴酱”

“不错不错！不过，现在好歹也是上课时间嘛。要喊我老师啊”

“好的好的，昴酱老师”

夫人依旧故意打着趣，昴不由得苦笑着耸了耸肩膀。

尽管昴已经被玛格洁宅邸正式雇佣了，但渐渐地他也不只是做那些杂务了，除了那之外现在他还在担任「习艺教室」的老师。

教室就开在宅邸里的一个小房间里，教授内容主要是昴很擅长的缝纫、刺绣之类的和制衣有关的“洋装课”。在和风文化已经占据一席之地的卡拉拉奇，从别国传入的服饰文化也颇具影响力，却迟迟难以实现本土化。因此，这个教室就是专门为了满足女性们对那些洋装的憧憬，由拥有专业知识技术的人来当老师时不时给予她们指导而开设的。

这里的学生大部分都是在这宅邸工作的女同事，再就是年龄相仿的悠闲太太们。偶尔还会有一两个难见的少女，为了以后能从事相关工作来学习缝纫基础，大概情况也就是这样了。

也可以说是异世界版本的文化教室的讲师，这便是昴的工作。

“我可是说过的对吧，我很期待你的女子力哦”

“嘛，我倒是没什么意见啦。不过啊，这也是主人的兴趣所在不是吗？”

“这可就是相当大的误解啦。我只是希望看见自己所钟爱的女性们也能多接触一点和风文化以外的新鲜文化嘛，只是为了满足这个小小的心愿而已。”

“何必要否认自己的熟女情结呢……”

同时，昴的授课也得到了一致好评。大家正商议着要把现在一周三节的授课增加到一周四节。而昴本人也想更充分地发挥在原先世界的知识，正好可以借助这种授课形式再把内容拓展得更为全面。

傍晚的时候，昴结束了在宅邸的工作，同夫人们还有已经混得相当熟了的门卫道了别，便朝家里——不、是朝着寺子屋去接蕾姆了。

自从发现蕾姆有了身孕，昴便把必须和蕾姆一起回家这件事当成了例行公事。毕竟不知道她回家路上会不会发生什么意外，等到真的发生了才知道那就已经迟了。

“说不定哪天就会因为一个荒唐的事不关己的理由，被一个根本不认识的人给突袭了呢”

“哈？这是几个意思，干嘛要看着我的脸说啊？你对我有意见啊，阿昴”

在沐浴在夕阳里的寺子屋门前，昴和缇雅好巧不巧地碰了面，刚一开口两人都颦起了眉毛。

作为丈夫，昴来接蕾姆是再理所当然不过的了。而缇雅也常常会不识趣地跑来寺子屋接蕾姆，使得夫妻两人的二人世界岌岌可危。

尽管这也算是缇雅和蕾姆已经玩得相当亲近了的证明，但这有时也实在是叫人为难。

“还有就是，阿昴什么的称呼也挺违和的”

“你还真麻烦啊，阿赫不也是那样叫你的，我跟着后面叫也没什么啊。更何况我原本就是来找蕾姆的嘛，你们不过是附带品而已”

缇雅撅起嘴像是威胁般地瞪了过来，昴也不甘示弱地不悦地撇了撇嘴。虽说这个称呼比之前那什么“雄性”之类的要好多了，但缇雅对自己旁若无人的态度倒是和一开始一样一点儿也没变。

“既然你这样，我就要去和蕾姆说让她给你少做一道菜”

“太、太卑鄙了吧你。你这铁石心肠的冷血动物……！”

即便如此，一旦抓住了缇雅的把柄，应付起来也就比之前不知道轻松了多少倍。

“昴君，缇雅大人，让你们久等了。……你们俩，不是在吵架吧？”

“怎么会”“那当然了”

更何况，两人一致认为，最具杀伤力的莫过于蕾姆微笑着的脸了。

到了晚上，赶得巧的话，不知道溜去哪儿了的赫鲁贝尔也会坐上餐桌，和一起回来的其他几个人共进晚餐。

一直在赚着赏金的缇雅像是对报酬本身没多大兴趣，除了第一次挣来的钱用来抵房子的修理费了，剩下的都尽数交给了蕾姆保管。

“所以说呢，大家的工作都很顺利的时候就稍微奢侈点。否则就朴素一点儿。”

“可钱不是问题啊，每天都吃豪华点不是更好？”

“要是那样的话，不仅大家会渐渐忘却了偶尔吃上一顿美餐的快乐和感激之情，而且更重要的是，还会伤了昴君作为家里顶梁柱的自尊心。这是贤惠妻子的关照呢”

“要是你不把这贤惠妻子的关照暴露在人前的话我还是挺欣慰的啊！”

俏皮地吐了吐舌头嫣然一笑的蕾姆实在是太可爱了就不计较了。再就是为了自己的自尊着想也就不计较了吧。

这事暂且放下，另一边缇雅正嗯嗯地点着头努力试图去理解蕾姆的意思。这两人的关系实际是挺不可思议的。尽管从外表看来缇雅显得成熟多了，但她内心简直就是个小孩子一样——不过那也是狼少女状态。而对这么个内外相去甚远的缇雅，蕾姆就像是母亲或者姐姐一样充满了慈爱之心。

在昴看来，要说是当作母亲的话，姑且也可以看作为肚子里的孩子提前做了演习。然而要是说看作姐姐的话，那就是如履薄冰般的复杂问题了。

“阿昴啊，怎么了？”

看着昴陷入了沉思，正自斟自饮的赫鲁贝尔歪了歪脑袋问道。而昴只是说了句没什么又摇了摇头，

“没事没事儿。我只是在想，明天能吃顿好的就好了啊”

“为此呢，赫鲁贝尔大人责任重大哦。基本上让我们和大餐失之交臂都是赫鲁贝尔大人呢”

“真的？早知道我哪怕是打着阿赫的屁股也要督促他好好工作呀！”

“你们这样对我，良心真的不会痛吗？”

众人你一句我一句地嚷嚷着，和早饭时的餐桌不同，晚饭时总是充满了欢声笑语。

晚饭后通常一行人会去浴场，由蕾姆来监督比之前稍微明白过来那么一点的缇雅，昴则带着赫鲁贝尔一起泡在浴池里享受，那之后就是出了浴的牛奶仪式。

走在回家的路上时总能听到缇雅的歌声。而就在最近蕾姆也加入其中成了二重奏，在动听的吟唱中的夜归也别有一番风情，昴很是享受其中。

就这样，充实的、又让人应接不暇的日子，缓缓地、缓缓地流逝。

6

“生孩子真是比想象中还要花时间哪”

缇雅两手抱在脑后，用悠闲的口吻如是说道。

缇雅和蕾姆、昴三人正并排走在从寺子屋回家的路上，对她而言夕阳下的大街小巷都已经成了再熟悉不过的风景了。此刻她的视线正锁定在走在一旁的蕾姆的腹部。

穿着和服的蕾姆正浅浅地笑着——她的腹部已经高高隆起，到了就连从远处也能一眼看出来的程度。

“粗略地来看，像是有六个月了……是吧？感觉也即将到了攻坚战阶段了啊”

“攻坚战！？也就是说才完成了一半而已！？诶诶，对动物来说肯定超不可思议的”

“谁是动物啊啊喂！正因为是人啊！所以才要慢慢地、好好地培育啊”

非要举出这样极端的例子来，昴赏了缇雅一记暴栗，只见她捂着脑门儿连连叫痛。而后她又把目光转回了蕾姆身上，

“挺着那么个大肚子，肯定很辛苦吧？又不能跑又不能跳的”

“的确是有点儿呢。毕竟大着肚子做很多事都不方便，绝对不能跑也不能跳，所以呢，这就交给缇雅大人啦”

“也真是没辙呢。不过啊，我可是超擅长又跑又跳的呢”

缇雅有点儿得意地接下了蕾姆的话茬儿，昴听着两人的对话也不禁莞尔。

蕾姆怀孕已经有六个月了——也就是说，他们同缇雅的邻居生活也快要满三个月了。一开始还叫人种种不安，而现在日子已经过得相当安稳了。

虽说和蕾姆身孕的安定期不同，但缇雅的性子也总算是安稳了不少。

“肚子里的小宝宝，到底是男还是女呢”

“是男孩儿也好，女孩儿也好，肯定都和昴君一样是个小淘气包呢。不过，因为宝宝总是会在蕾姆的肚子里不安分地乱动，所以蕾姆在想啊，有可能是个女孩儿呢”

“一般来说，不安分的往往是男孩儿不是吗？”

“——？是这样吗？”

根据蕾姆的自我判断，她好像觉得肚子里是个女孩儿。而听了她的判断依据，昴一脸惊讶。这倒也使得蕾姆疑惑地歪了歪脑袋，就连缇雅头上也冒出了问号。

或许在这个世界，人们普遍的观念是女孩子更加活泼淘气吧。

仔细一想也确是如此，好像在这个世界遇到的女性们大部分性格都是相当活跃的。——所以这时候就得划清思考方式了。

“嘛，第一个孩子是女孩儿多好啊。在我老家有句话叫「一姬二太郎」，意思就是头一胎是女孩儿，第二胎是男孩儿就再好不过啦”

“一姬二太郎？”

“姬呢就是指女孩子，太郎指男孩子。就是说啊，第一胎先生个女儿，第二胎生个儿子是最好的。好像是说因为女孩子晚上很少会闹夜”

育儿可是相当辛苦的一件事，这对于相关知识几乎为零的昴来说也是深深刻在脑海里的常识。当然，亲身体验是没有的，但这段时间他可没少听宅邸里那些女性同事们的抱怨——总而言之，以闹夜为首、照顾婴儿是特别辛苦的一件事儿。

“也就是说，一开始通过容易安抚的女儿来学习育儿入门经，到了第二个孩子的时候就能冷静下来自如地应对了。该说是古人的智慧吧，也可以说是从实际生活中得到的宝贵经验呢”

“原来如此。……那就是说，无论怎么样第一胎必须得生个女儿出来喽”

“就算肚子里是个男孩儿，也不要把刚刚这些奇怪的话放在心上啊，不要有压力，顺其自然就好”

昴苦笑着挠了挠脸。而在他身边的蕾姆却像是把这话刻进了心底里，

“就当是为了昴君，也一定要是个女孩儿、一定会是女孩儿的哟”

就像是在说给自己肚子里的孩子听一样。然而，据说胎儿的性别在受精的那一瞬间就已经决定了，蕾姆现在的举动也为时已晚。

“就算小家伙你是个男孩儿，也别管那么多，健健康康地来到我们的怀抱里吧。想要闹夜就尽管闹吧。毕竟先苦后甜的可能性也是很大的嘛”

“是呀。只要能健康地降临到这个世上……嗯，不管怎么样健健康康才是最重要的”

“就是就是，那才是头等大事哪。噢，动了动了”

昴的手抚上蕾姆的肚子温柔地冲小婴儿说着，没想到这么快便得到了回应。

这个崭新的小生命已经在蕾姆的体内辗转反侧迫不及待了一般。

果然，昴的直觉还是告诉他，这是一个男孩儿——、

“那现在就一心期待着宝宝的早日出生吧”

合理地考虑一番，果然还是事先知道了宝宝是男是女再来准备各项事宜要快得多。不仅是衣服，包括选什么样的玩具之类的也能定下一个方向。

真正有了自己的孩子之前昴也是这样想的，然而真到了如今这一步，他却不这么想了。

直到出生前都无法得知性别这一点，在昴的眼里也成了小婴儿为自己带来的祝福。

“不过，也就是说还剩六个月左右喽？唔唔，真的要好久啊”

“那肯定也就是一眨眼的事哦。缇雅大人讨厌那样吗？”

“也不是讨厌啦……只是这样一来，就一直也找不到关于光珠的丝毫头绪不是吗”

“——”

缇雅不满地嘟着嘴唇，斜睨着夕阳放言道。而听到这番话——或者说「光珠」这个词的一瞬间，昴的表情便僵住了，蕾姆也屏住了呼吸。

光珠，便是缇雅一路追寻而来的目标，也是如今这生活的一切的开端。

缇雅一口咬定那是蕾姆偷去的，然而蕾姆的身孕让她没能用强逼问出真相，于是双方便约定好了以直到孩子出生那天为期，暂且成为了和平相处的邻居。

可是，由于缇雅在最初的几天过后就完全没有再提及光珠这回事儿，也再没有表现出对蕾姆的怀疑，两人几乎已经把这件事儿给淡忘了。

然而即便是到现在，缇雅仍然记得，仍然在追寻，这让两人一时无法掩饰住惊讶之情。

“……不过就算这样，还剩六个月你也给我忍着吧。这是约定好了的”

“是是是，我知道了知道了。六个月，还有六个月啊……”

严谨地说，怀孕期间大概是十个月——既然现在已经是六个月了，那剩下的也只有四个月不到了。虽说知道这一点，但昴还是没有订正缇雅的说法。哪怕只有两个月也好，他也想让“那个”时刻来得更晚一点儿。

如今已经和初次见面时那般的刀锋相向不同了。缇雅她，现在已经成了两人无可替代的朋友了。

“别到时候你刚生下来，蕾姆就立刻又怀孕了，那我可就要犯难啦！”

缇雅望着蕾姆——不、是蕾姆肚子里的孩子这般念叨着。

只要蕾姆还怀着孩子，就绝对不会加害她。就像要把这自己定下的规矩一笑置之一样，缇雅的话里也带着宠溺的味道。要真是这样就好了，昴在心里想到。

“昴君……”

“别呀，蕾姆，就算你这样一副加油吧的表情看着我也……”

只见蕾姆的手用力握成了拳头，微微湿润的眼睛里投射出无比认真的光，昴不由地皱起了眉头。她的一张小脸红扑扑的，也不知是为了决心涨红了的还是夕阳染红的。

不管是哪一种，昴却迟迟未能回应蕾姆决心要生第二个孩子的弦外之音。当然了，昴也是相当赞成为孩子添个弟弟或是妹妹的，但家计问题也不容小觑。

更何况第一个孩子也本是没有计划就怀上了的，第二个孩子就更得慎重一点儿了、就是这样。

“当然，也不是没想过……通过这个方法让缇雅改变心意”

“只要一直到死亡将昴君和蕾姆分开之前，两人都不断地创造爱的结晶……”

“你这想法未免也太……啊喂！”

看到蕾姆还真的在一脸认真地盘算着这个恐怖的计划，昴赶紧一把抓住她的手上前一步引她下楼梯。蕾姆很自然地接受了昴的搀扶，先到了楼梯口的缇雅正站在原地等着两人。

被夕阳的余晖笼罩的回家的路，一如既往温柔静谧的时光。然而只有四个月了——或许四个月过后，这一切都将不复存在了，一想及此、眼前的光景也像是马上就会消失一样变得虚幻起来。

——眯缝着眼眺望向那遥远而炫目的夕阳，不知缘何，昴不禁为了这份虚幻而胸口阵阵刺痛透不过气来。

“哟。回来啦。今天也辛苦了一天啦”

刚一回到家，就见正靠在长椅上吧嗒吧嗒地抽着烟袋的赫鲁贝尔迎了上来。

这段时间，赫鲁贝尔也常常偷懒不再跟着缇雅一同出发去执行任务。以缇雅已经对大街小巷都熟悉了为借口，他又回归了“永远的游手好闲者”。

也就是说这是游手好闲的的迎接。理所当然地，三人的反应也都很冷淡。

“今天您也乐得清闲啊。在这里逛一逛那里遛一遛，明明是狗赫却压根没尽到看门狗的职责不是吗”

“软饭好吃吗？”

“呜哇，你们这一个个跟开了嘴炮似的好大的怒气啊。真过分啊。蕾姆酱，你也帮我说两句嘛”

“是啊。……只有辛勤工作了的人，吃饭时才会觉得特别香哦”

“虽然说话方式是委婉一点儿了，但本质意思还不是和阿昴一样，还是很扎心啊！”

吃了昴和缇雅的夺命连环攻击加之蕾姆的最后一击，赫鲁贝尔举起双手向后仰着连连投降。没过一会儿他又慢慢缩回了原样、

“我这段时间的确是没干什么事儿游手好闲的，但今天可是有一点点不一样哦”

“恐怕没人觉得你那一点点就足以改观你懒惰的形象了吧？”

“这种事就不要说出来了嘛。还有啊，我今天可是为了你四处奔波啊，你好歹也别直接无视了啊”

“为了我？”

听了赫鲁贝尔的话，缇雅一脸呆愣地指着自己。赫鲁贝尔神气十足地一扬下巴，他嘴里叼着的烟袋便指向了屋内——确切地说是缇雅的房门的入口处。

“快，阿昴，上去打开给她看看”

“别说得我跟你是同谋一样，我还什么都不知道呢……呃，哦？”

昴老大不情愿地听从指示上前打开了缇雅的房门。刚朝里面看了一眼，就瞪大了眼。房间里是——、

“哇。这，又是花儿又是点心的，还有和服呢。是礼物吗？”

蕾姆蹭到昴旁边瞄了一眼，便立刻双手合十捧在胸前，眼睛发亮地感叹出声。

正如蕾姆所言，缇雅的房间已经完全变了个模样。这间原本是蕾姆和昴夫妇俩住的屋子被缇雅大肆破坏后，也就随便修补了一下，放进了几个必要的家具，很是单调乏味。

然而现在，房间里点缀满了绚烂的花儿，榻榻米上堆着和服和点心盒子，五颜六色的礼物塞满了这块小地方。

“就阿赫的水准来看，这还真是一次罕见的完美礼物啊”

“哼哼哼~如何如何？这下对我刮目相看了吧？喂喂，不过我还是想说啊，其实这和我送的东西可不一样啊。这些都是咱们城里的街坊四邻送的哪”

昴刚发出一声佩服的感叹，赫鲁贝尔就立刻不打自招了。毕竟这的确不像是赫鲁贝尔的情商能做出来的举动，所以听他这么一说大家便立刻理解了，但同时也为这真相吃了一惊。

也就是说，整个巴南的居民，为这屋子的主人——也就是缇雅送出了这么一份礼物。

“之前你们不也听说了缇雅酱她的工作业绩相当好，逮捕率很是突出嘛？不过啊，缇雅酱可不仅仅是出色地完成了中介那里的任务，更是对居民们处处都相当关照哪”

“就是说不仅是任务，也有在做其他的工作？”

“说是工作，倒不如说是助人为乐那一类的呢。大概就是今天帮张跑个腿明天帮李做个事，每天都忙得团团转……然后她的付出就这样一点一滴地累积起来，以这种形式一下子都成了回报啦”

赫鲁贝尔抱着手臂向两人解释道，而之前对此一无所知的蕾姆和昴只得大眼瞪小眼。

这样想来，之前也有挺多让人意外的事的。在从寺子屋或者浴场回来的路上，也总能看见居民们十分热情地向缇雅打招呼。昴原本以为那只是因为她从中介那里接来的工作改善了城里的治安，现在想来也并不止是那样。

缇雅在昴他们尚不知情的时候，就一点点地同城里的人加深了情感交流。

“——”

然而缇雅本人却一时间没能像昴他们那样反应过来，只是呆呆地站在送给自己的五花十色的礼物前哑口无言。只见她涨红了脸，一根手指不停地拨弄着自己的头发，像是在表达自己困惑的心情一般。

一定是涌上心头的这滋味过于浓烈而陌生，一时间甚至招架不住了吧。

“不如今晚咱们就吃一顿大餐吧。这里也堆满了这么多食材”

“蕾姆……”

“这可是送给缇雅大人的一片心意啊，坏掉了就不好了。不过这么多蕾姆一个人有点吃力，能帮蕾姆一起吗？”

听了蕾姆的话，缇雅的眸子不由地闪了一闪。继而沉思了一会儿，缇雅还是没能憋出话来，只是用力对蕾姆点了点头。

得到了缇雅的首肯，蕾姆挽起了袖子——这场贺宴的准备就此开始了。

7

说是贺宴，但事实上究竟是祝贺什么这一点也不甚明了。

如果说非要为其加上一个意义的话——、

“——是为了庆祝缇雅大人已经成为了咱们城里的一员啊”

听蕾姆微笑着这样说，昴也就接受了。

庆祝成为城里的一员——对于昴和蕾姆来说，那是在得知了蕾姆有了身孕后，街坊四邻也都因此怀着满满的温情向两人伸出了援助之手。这便是已经被居民悦纳了的证明。

如今相同的事也发生在了缇雅身上，这真的，太好了。

“——”

大家围坐在餐桌前，桌上一字排开的碗啊碟子啊都空空如也。

虽说只有四个人参加，但贺宴还是贺宴。加之蕾姆热情高涨，接二连三地发动美食进攻，架势一点儿也不输给真正的贺宴。而这美味的进攻都尽数被缇雅正面拦截下来，加之昴和赫鲁贝尔的协助，完美剿灭一空。

于是现在大家都捧着自己撑圆了的肚皮，在饱腹感面前败下阵来开始睡意朦胧。

“刚吃完饭就睡觉会变成猪的。这样一来好不容易生了个美人胚子也就给你糟蹋啦”

“哟，阿昴，自己的夫人就在旁边你也真是敢说啊”

“我一直一来夸我家蕾姆都是比这要动听上几百倍的嘛。而且，我对缇雅可没什么不轨之心啊。缇雅她怎么说呢，嗯嗯。……大概就像妹妹一样吧”

虽然从外表上看还一时分不出谁更年长，但从平时的一举一动和常识感来说，也没有人会怀疑昴要比缇雅成熟得多吧。

所以听了昴的这番话，蕾姆和赫鲁贝尔都只是莞尔一笑没有反驳。

“不过啊，她现在这样睡着了还在哼唧可不仅仅是因为吃撑了啊。依我看她肯定又在偷偷地小口小口舔那玩意儿了”

“小口小口地舔……啊”

赫鲁贝尔憋着笑，指向了睡得东倒西歪的缇雅的屁股底下——一身白衣装束的裙角下藏着的是装在相当高级的酒瓶里的酒。

没准儿那也是来自居民的礼物之一吧。毕竟昴他们已经达成了共识，让缇雅喝酒是很危险的，平时一点儿也没让她沾过。

“有些东西你越是藏起来就越会勾起小孩子的好奇心。我就知道迟早会这样”

“……但是，阿赫你明明知道还睁一只眼闭一只眼，这也说不过去吧”

“我不是看她舔了几口就睡倒了嘛，实在是可爱啊。要是她因此发了酒疯我肯定也是会负责任的，但这不是没有嘛”

对赫鲁贝尔大大咧咧的态度，昴不由地沉下脸来。然而，看着缇雅那一脸安详的睡颜，也让人觉得对赫鲁贝尔发怒是没有必要的。

就算是喝醉了酒，现在的缇雅应该也不会像之前那样对昴暴力相向、哪怕夺去蕾姆的性命也在所不惜要抢回「光珠」了吧。——那副场景放在现在是没法想象的。

“不过，要说那个光珠啊”

“——！你知道什么了吗？”

“我也是常常到处跑着去打听过了啊。你们不会真以为我就是天天游手好闲的浪荡子吧”

打开了话头，赫鲁贝尔冲昴挤了挤眼，很显然那意思却和平常都不一样。见状昴不禁有些惊讶地扬了扬眉毛、

“啊啊，原来还真以为你只是在鬼混……现在我刮目相看啦”

“是，蕾姆也对您刮目相看了呢！不愧是赫鲁贝尔大人呢！”

“我还真是见不得你们小两口这样夫唱妇随啊”

赫鲁贝尔苦笑着挠了挠自己的脑袋。但紧接着他的口气又变弱了、

“让你们期待了真是不好意思。不过我上哪儿也没打听到关于光珠究竟是个什么，也不知道它在哪儿。现状还是没有任何变化，对不住啦”

“哈啊……”

“能别叹这么大一口气吗？更何况压根没打听到，不也是个相当有意思的情报吗？也就是从侧面说明了，就连那玩意儿到底是不是真的存在也相当可疑”

“也就是说，你怀疑这一切都是缇雅大人的一派胡言是吗？”

听了赫鲁贝尔的话，蕾姆的口气变得有点生硬，带着一点质问的意思。

虽然反应不及蕾姆那么大，但昴对这个假想也是挺反感的。

缇雅迫切地想要夺回那颗光珠的心情无疑是货真价实的。这一点就在刚刚回来的路上也是得到了确认的——再怎么想那也不可能是谎言或是伪装。

“只有本人固执地深信不疑，这种可能性也是存在的。阿昴也好蕾姆酱也好，你们应该知道的吧，缇雅酱她不是一般人”

“——”

然而，赫鲁贝尔不像被感性控制住而一口否决掉这个假想的两人，直截了当地向两人宣告道。

正因为是忍者才能保持这般冷静的头脑做出这客观分析的吗？还是说单纯地只是因为，昴和蕾姆出于对缇雅的好感一直以来都想刻意避开这事实呢。

“要是蕾姆酱的孩子出生了……”

赫鲁贝尔的口中第一次吐露出对所剩无几的时间的担忧。无可逃避的事实正一步步迫近。那是决断的时刻，也将是选择的时刻。

但拥有选择权的，是昴呢，还是蕾姆，抑或是缇雅呢。

“也没有必要现在就急着做出回答吧”

“确实如此。——但是总有一天，在那一刻到来之际，咱们不得不给出回答”

听了昴的话，赫鲁贝尔只是低下头，平静地说道。而昴对这番话无从辩驳，便没有再开口。此时蕾姆缓缓地站起身，

“要是缇雅大人着了凉就不好了”

“啊，我来”

昴跟着蕾姆后面走向壁橱，从里面扯出几块毛毯。这几天夜里明显变得寒凉起来了。不光是缇雅，昴更担心蕾姆一时没法适应。

“缇雅大人，酒蕾姆就拿到一边去了哦。被子就这样铺着可以吗？”

蕾姆走向睡眼朦胧的缇雅温柔地搭了话。而后将缇雅藏在裙摆下的酒瓶尽数回收，体贴地帮缇雅松了松衣带。

就在那时，蕾姆的手被雪白的指尖一把握住了。

“缇雅大人？”

这是一个再正常不过的举动了。而从中感觉到异样的，也只有看清了缇雅的睡颜的蕾姆一人。

把毛毯抱过来的昴也好，在窗边吞云吐雾的赫鲁贝尔也罢，他们都没有注意到的是

——一道泪痕，顺着缇雅的脸颊缓缓地、缓缓地蜿蜒而下。

“还，给我……”

虚弱如呻吟般的话语从缇雅薄薄的唇里吐出来。

那声音转眼便消失在空气中，蕾姆啊了一声把耳朵凑近前去——、

“——把我，还回来”

在那一瞬间，一道风袭过来。

“啊！？”

昴发出一声悲鸣，立刻将手里的毛毯展开来，稳稳地接住了被撞飞的蕾姆，但由于冲击力过大，昴一时没有稳住向后跌去，后背猛地砸在了料理台上。

那些烹饪刀具发出刺耳尖锐的响声纷纷翻落，锅里剩下的食物也打翻了。

“嘶，哈……”

到底发生了什么，昴吃痛地呻吟出声，拼命睁开眼。

映入眼帘的是，和就在几秒前是完全不同的面目全非的光景——餐桌和榻榻米被掀飞了，天花板上垂下的魔法石剧烈地闪烁着。房间中央那一片像是被野兽的爪子给生生剜出来的，而缇雅此刻就站在那里，一身白衣随风鼓动、猎猎作响，她的脸上尽是泪水。

风、和暴击。这一切都足以让人想起似曾相识的那个被袭击的夜晚。

“缇雅——！”

昴大吼一声。然而缇雅只是双手抱着头拼命地哭泣，这声音甚至没有抵达她耳边。她的眼底里满是迷茫和错乱，嘴里开始念念有词。

“我的手……我的脚……我的、身体……都在哪儿？都去了哪里啊？”

只见她的脚步极其不稳，整个人摇摇欲坠。然而即便如此，她的危险气息仍是一目了然的——、

“——！”

早就意识到这威胁的忍者自有忍者流的招数。

刚刚那道风袭，被赫鲁贝尔贴在天花板上给躲过去了。也不知道他这么大的个子是如何做到的。然而紧接着，赫鲁贝尔便飞身落下，借助自然的引力直直冲着缇雅的正上方使出猛烈的一击。

朝缇雅招呼来的是那双宽厚的手掌紧紧握起而成的斧一般的拳头。那是来势汹汹几可劈断一棵大树的猛烈攻击，若是尽数为纤弱的缇雅所受，很可能她的生命都会危在旦夕。然而只见流着泪的缇雅灵活地一翻身躲过去，转身就将断成几截的餐桌给踢过去，把飞身落下的赫鲁贝尔给挡到一边。

只见个子高大却身形灵活的赫鲁贝尔轻盈地在狭小的室内翻飞，完全没有把体格差距放在眼里的缇雅试图通过魔法战术来占上风，一时间两人激战在一起难舍难分。

这简直就是那一晚的再现，尽管地点不同但形势如出一辙。

缇雅接连使出不容小觑的喰击，而赫鲁贝尔灵巧地放出一个个结界全身而退。然而，这一来一往的冲击余波也使得房子添了一道又一道的伤痕、遭受了惨烈的破坏。

“这样下去可不行啊！阿昴他们会被压垮的！”

赫鲁贝尔意识到房子倒塌的严重性，大吼一声猛地一跺地板。只见地上残存着的榻榻米纷纷被巨大的冲击力弹飞上去，缇雅站在其中一个榻榻米的上面，为这意想不到的突袭一起带飞到了窗外。

榻榻米飞袭——尽管不知道原理是什么，这就是赫鲁贝尔使出的招数。

“——！”

终于反应过来的昴立刻唤起僵硬了的身子站了起来，蕾姆依旧蜷缩在他双臂间的毛毯里，就这样抱着她昴飞奔出了房子。

“蕾姆，你没事儿吧！？蕾姆！？”

皮肤一接触到室外冰冷的空气，昴这才意识到自己的全身已经被冷汗给浸湿了。他忍住这不适试图呼唤着怀中的蕾姆。

“昴、君……”

“蕾姆！”

伴随着痛苦的吸气声，蕾姆喊着他的名字。闻声昴咽下了所有话语，缓缓地展开了毛毯想要确认蕾姆的安好。

看上去是没有外伤的。看到蕾姆那么近距离地直接受了缇雅的风袭的那一瞬间，昴整个人如坠冰窖。若是运气不好蕾姆有可能就和那一块儿空间一起被撕裂了。然而幸运的是，蕾姆只是被冲击力给弹飞出去就幸免于难，这简直是奇迹——、

“缇雅、大人她……”

“别逞强了！缇雅……缇雅那边阿赫会帮我们想办法的！比起那个更要担心的是你自己吧！你的身子……”

“蕾姆，没事的……唔！？啊、啊啊！”

“蕾姆！？”

蕾姆想要挤出一个坚强的笑来，却突然痛苦地扭曲着脸蜷起身子。

昴惊恐地瞪大了眼，他的眸子里映出蕾姆用手按着自己的肚子一脸痛苦的样子。

这情景让他的心里不由自主地浮现出了最不好的预感。

“——！！”

猛地给了自己陷入混乱状态的脑袋一记拳头，昴再次连着毛毯把蕾姆抱起来。而在房子对面不远处赫鲁贝尔和缇雅还在刀锋相向。

可是，眼下可不能再让他们这样下去了。不是做这些的时候。

“缇雅！赫鲁贝尔！！住手！到此为止！！”

昴一路飞奔到那边，冲着正在激战的两人疯狂地怒吼道。听到声音，赫鲁贝尔仍旧没有放松警戒，而缇雅缓缓地望向了这边。

下一秒同样的光景映入了两人的眼帘，却不知他们心里是作何感想。

但，昴可以看到，就在那一瞬间缇雅眼神里的狂乱稍稍平息了，赫鲁贝尔则是完全脱离了战斗状态。

“诶……？”

缇雅像是彻底怔住了一般，发出一声困惑至极的声音，缓缓地转头看了看四周。

惨遭破坏的房屋，痛苦不堪的蕾姆，即将陷入疯狂的昴，还有和自己大打出手的赫鲁贝尔。

“诶……？”

缇雅像是完全没反应过来发生了什么一般，只是连续地重复着这个单调的音节。也顾不得缇雅如何了，赫鲁贝尔飞速奔跑到昴的身边、

“蕾姆酱她？”

“她正捂着肚子难受得不行！快！咱们立刻去找医生……”

“我带她去，这样快一点。阿昴你也赶快跟上来”

话音刚落，赫鲁贝尔就像是夺过来一般一把将蕾姆连着毛毯一起接过来，用难以置信轻盈的身形跃到半空中飞速穿过一片片街道，径直朝着之前关照有加的老术师那里去了。

望着赫鲁贝尔的身影迎着月亮渐行渐远，昴这才反应过来立刻追在后面。

“等，等等……”

然而一个颤抖的声音从背后叫住了他。一瞬间，昴停下脚步，回过身。

缇雅一个人孤零零地伫立在他身后，一只手拼命地伸向这边。尽管这么远的距离是不可能立刻就够到的，想要挽留的意思却表露无遗。

“我……”

“——”

“啊……”

缇雅说了一半便再也发不出声音，昴也不知该作何回应。

焦躁感占了上风。——不，或许也还掺杂着惶恐不安。现在没有停下脚步的时间。哪怕是早一秒也好，昴只想尽快飞奔到蕾姆身边。

这让人心焦的情绪让昴的脚再度动了起来，他扔下缇雅再次跑了起来。

“——”

昴总觉得缇雅沙哑的声音抵达了自己耳边，不知在诉说着什么。但他既没有停下脚步，也没有喊缇雅跟着一起过来。

是对她充满了愤怒吗。当然，是有的。

是对她充满了恐惧吗。当然，也是有的。

但是除此之外，必定还得对缇雅说些什么，昴抑制不住对此的恐惧，选择了逃避。

“小媳妇没事儿了。已经平稳下来了。……尽管母子俩一度很危险哪”

为及时送来医院的蕾姆进行了长达好几个小时的紧急处理后，老术师感叹道。

听着躺在床上的蕾姆呼吸渐趋平稳，昴总算是从心底里松了一口气，慌忙向老术师和赫鲁贝尔两人连连道谢。

直到蕾姆睁开眼，昴都一直在她身旁默默地守护着。

就算赫鲁贝尔回家看了一次又来告知缇雅已经不知去向了，就算老术师关切地让他休息一会儿，昴也不为所动，只是静静地等待着蕾姆睁开眼的那一刻。

“昴、君……？”

终于再次听到了苏醒过来的蕾姆的声音，昴泪流满面地把她抱进自己怀里。

直到确定了她是真的没事了，昴才终于恢复了往日的冷静，回到了日常生活的常轨来。

——自那以来，缇雅再也没回来过。

就这样，吵吵嚷嚷却又有趣的同奇妙邻居的同居生活也就迎来了落幕。

接下来的三个月过得飞快，如同眨眼间的事儿一般。

——眼看着，蕾姆的预产期就要到了。

** 第四章 『十个月』

1

「今天也多谢指点了。那么先告辞了，医师。」


「你就多留心点吧，因为不管什么时候生出来都不奇怪了啊。要是你又像之前那样被抬过来，老夫也不知道有没有闲工夫了呢。」

「是，我会铭记于心。」

「别说傻话了。」

蕾姆行了一礼，老术师仍然一副冷淡的态度，振臂一挥将他们赶走。

其礼数乍看之下敷衍了事，但相处的时间一长，便能理解这粗鲁的态度背后的真意。他只是说的话有点难听，但他的技术和对患者的关怀都是货真价实的。

正因如此昴才会放心，有意让蕾姆与这位治愈术师交心。

「话说回来，我真的好紧张。正如医师所说，到了这个地步不管什么时候生出来都不奇怪呢……」

「真是的，这可不行哦，昴君。如果一直都这么紧张的话，等到真来的那一天身体可撑不住。请保持适度的紧张和从容。」

「噢、噢噢。适度从容的态度对吧。」

看着紧张到同手同脚走路的昴，蕾姆用手捂着嘴嘻嘻地笑着。她的肚子已经大得无需辨别，马上要迎来临产月。

虽然有段时期母子二人都有生命危险，但能一起重新站起来，像现在这样欢笑着抚养肚子里的孩子实在喜人。

而这毫无疑问都要归功于蕾姆自身强大的精神，以及昴献身性的支持。

那晚以来，昴就比以往更加尽心尽力地从旁支持着蕾姆。同伴和熟人们纷纷称赞他很了不起，但事实却并非如此。

那一晚，那个瞬间所体味到的恐怖和混乱，一想到这些，这一切就都是理所当然。

可能会失去蕾姆和孩子的恐惧，仅仅是想象一下血液就仿佛要冻结。

「多亏了昴君，蕾姆想起了非常开心的往事。老公这么宠蕾姆，有点担心生下孩子之后能不能回到原来的生活呢。」

「现在的蕾姆可是有用肚子当摇篮哺育孩子这个重要的工作哦。在生下孩子之前，繁琐的工作全都交给我吧。你就像以往那样，如果有在意的事情不用自己解决，尽管严厉地指导我就好。」

「好滴——。」

蕾姆也应和着昴唱的戏，开着玩笑点点头。

正如蕾姆所要求的，临近妊娠后期的现在，家里所有的工作全都由昴代做。煮菜、洗衣服、扫地，都尽可能地交给了昴。

理所当然地，一开始虽然技术之差和知识的缺乏十分明显，也经历了很多次失败，但经过蕾姆悉心的指导，遇到困难时还去拜托了同伴和妇人们，总算挺了过来。

到了现在，昴总算是具备了蕾姆勉强认可的家庭主夫技能了。

「这一切都要归功于担任教师的优秀的蕾姆呢。」

「没有没有，昴君本身学东西就很快，手指也很灵巧所以教得很轻松呢。想必很适合做家里的工作吧。」

「因为只是没有什么机会，这样一说连我也觉得是这么回事了呢。」

对料理、洗衣、扫地这些家务适应性很高这点他也有所自觉，只是没什么机会罢了。

没想到，被卡拉拉奇主妇团体包围还能平安无事，还得到了支持。

「今晚该做什么呢？蕾姆，你想吃什么吗？」

「这个呢，我想吃酸东西。」

「来了个孕妇的超王道要求啊。真的会变得很想吃酸东西吗？」

「不，虽然刚怀孕那阵会有这种想法，但现在几乎没有了。所以那阵子经常偷偷地吃酸东西哦。」

「刚才坦白了冲击性的事实——！」

似乎喜欢吃腌制物和酸性水果的样子。不过，由于那段时间蕾姆还没有自觉到自己怀孕，似乎对此事一直很不解。

「我听说孕吐加剧的时候，就会变得很想吃酸东西呢。这样想来，蕾姆似乎没怎么孕吐过吧。」

「听你这么一说，好像真是。肯定是因为不想在昴君前露出软弱的一面，蕾姆强烈的心意在作祟吧。」

「钢铁般的精神力固然可靠，但没有变得为时已晚真是太好了啊……」

发现怀孕的契机，是请治愈术师来治疗突然失去意识的蕾姆之时。要是那个时候，没有失去意识而是强忍下去的话，说不定真的会直到肚子鼓起得不自然为止都无法发现。

「若是那样，可能会为了瞒着昴，做出各种各样的努力来遮掩腹部的膨胀，蕾姆有会这样做的自信哦。」

「而且我也有自信会粗心地一直被骗下去。我太没用了啊……」

想到这里，就觉得能在尚能挽救的阶段发现真的太好了。然后，在那产生了发现的契机的夜晚，所在场的是——

「————」

自然而然地，还没来得及避开，记忆不经意间就回到了那个夜晚。

想起这件事，昴的表情便力不从心地变得凝重。在巴南之街度过的三个月的回忆里，无论怎么寻找，都会有她的存在。

最为快乐，最为吵闹，至今也仍历历在目的那段时间里，总有缇雅的存在。

「缇雅大人……」

「还是行踪不明。克莱茵那里已经张贴了布告，阿赫也在帮忙寻找了，但还是没线索。」

听到蕾姆无精打采的低语，昴迅速答道，表明尽可能不要再谈及缇雅的话题了。但是，蕾姆却摇了摇头。

「昴君，是在生缇雅大人的气吗？」

「——那是，当然的吧。那个时候，也不想想你有多危险。你也是，肚子里的孩子也都命垂一线。但那家伙却做出了那样的事。」

「————」

「然而，那家伙不仅没道歉，甚而在骂她两句前就消失了。这样一来怎么可能不生她的气？」

——从那最后一夜以来，缇雅就从街坊某处消失了。

昴记忆中见缇雅的最后一面中，她被奔往治疗院的昴像小孩一样抛下，身影逐渐消失不见。

确认蕾姆平安无事而返回濒临崩塌的长屋时，周围早已没有缇雅的身影。之后经赫鲁贝尔的帮助，将街道找了个遍，结果还是没有她的行踪，就这样过了三个月。

缇雅，是去到了某个地方吗？那个奇妙的邻居，究竟在哪里——

就连发展到邻居以上的关系，都没有得到她的认可。

「如果能见到她，得到道歉的话，昴君能原谅她吗？」

「……蕾姆又是怎么想的呢？」

「蕾姆，肯定会原谅她的。因为蕾姆很喜欢缇雅大人。」

「————」

蕾姆这温柔的话语是理所当然的。她，是真心原谅了缇雅。

而蕾姆还说，理由就是喜欢她。

被这么一说，昴也无所辩驳。昴也应是抱有和蕾姆同样的情感才对，觉得缇雅惹人喜爱，把缇雅当作朋友看待。

然而，昴的心结却没有消失，仍然无法原谅缇雅。

明明心情和蕾姆一样，明明共有着同一份回忆，昴却无法原谅缇雅，这就是器量的差别吗？还是说，另有缘由呢——

「————」

说着这些话的时候，昴和蕾姆两人已经回到了家里。

现在，两人所住的不再是以前的长屋，而是承蒙利夫坦的厚意所得的一幢安置在近市区的独立房屋。因为那一晚的遇难，长屋彻底倒塌，因不再重建而成为了长屋旧址。

得知两人无家可归特意而来的便是利夫坦了。虽然就这样接受了他的人情实在不好意思，但孕妇的状况让昴也忘记了客气。

或许这也是利夫坦的关照，这里作为临时住处却出乎意料地舒适，和长屋里截然不同，还能关照到蕾姆的身体状况。

「不过，只有两人住的话感觉太过宽敞了呢。」

蕾姆慢慢在客厅内坐下，说道。实际上，和仅有隔板的单间屋子的长屋不一样，这个屋子无法全部使用。

即使算上客厅和寝室，还有各自的房间也用不完——

「应该是考虑到生下孩子以后孩子也能有一个房间吧。既然是利夫坦先生的话，可能连这种地方都考虑到了。」

「昴君看来很信赖利夫坦大人呢。」

「已经受了他这么多照顾了。事到如今也不会因为这点熟女的兴趣就减少信用吧。攒了很多还不完的恩情呢。」

「是的。蕾姆也是，受了寺子屋里的各位还有术师的医生的关照。还有，赫鲁贝尔大人也是……」

「阿赫，吗？」

昴把货物都放回壁橱，听到赫鲁贝尔的名字眉头紧锁。

从长屋倒塌，住所完全分开以来，和赫鲁贝尔见面的机会大大减少。三个月之前还是每天抬头不见低头见像家人一样的关系告终，现在的赫鲁贝尔似乎不再游手好闲，而是勤勉于忍者的本分。

「想必，是对蕾姆的事情感到了责任感吧。」

「那明明……不是赫鲁贝尔大人的错。」

「道理是这样的呢。然而缇雅的豹变……要说有什么契机的话，果然就是酒了吧。想必是因为坐视不管心情很沉重吧。」

尤其是赫鲁贝尔，如果出什么问题的话，甚至会开切腹这种玩笑。

而这一旦成为现实，他究竟会自责到什么地步，昴也无从得知。

说实话，赫鲁贝尔如果能再早点，在缇雅碰酒之前阻止她就好了，昴不是没有过这种迁怒的想法。虽然昴不是那种会把这种话说出来的小孩子了，但赫鲁贝尔会这样自己忏悔也没什么不可思议的。

因此，赫鲁贝尔在那一夜以后，就一直热心地追查缇雅的下落。

「……蕾姆，我准备出去买东西了，你有什么想要的吗？」

继续聊那个夜晚的话题的话心情就太郁闷了。蕾姆的心情失落下来对肚子里的小孩也不好。为了避免这点，昴强行转移了话题。

虽然蕾姆把这份心思看得一清二楚，但她还是摇了摇头。

「不，不用了。而且，就算每天都这么问，蕾姆也不是那种什么都想要的任性的人哦。」

「现在的蕾姆可是世界第一级别能对我撒娇的立场哦？」

「这样的话，我要你永远陪在我身边。」

「货物充足了之后可以考虑吧。」

昴对蕾姆可爱的撒娇露出苦笑，做完购物的准备后站起来，心里思索着，今晚的晚餐就按蕾姆的要求做一桌酸东西好了。

虽然蕾姆装作开玩笑的样子，但感觉那像是真的想吃才说的。

「那么，蕾姆，我出门了。要在家乖乖等我哦？」

「会和肚子里的孩子一起乖乖等你的。」

做完这些互动，昴便离家购物去了。目的地是市场街——但是，首先要去的并非食品店。而是，克莱茵的中介屋。

2

「很遗憾，缇雅酱的事情还没线索。抱歉。」

向着定期露面的昴，克莱茵说出已经成为惯例的回答并低下头。看到他这深感抱歉的态度，昴毫无办法地摇了摇头。

而这也早已完全成为惯例的反应了。

「大家都很担心她。虽然犯不着我说，但她也很受大家喜欢。」

「技术也很娴熟吧？虽然我至今还有点怀疑就是了。」

「首屈一指的。嘛，那么年轻的女孩以赚赏金为天职，这点不怎么想提就是了。总而言之，会继续搜索的。」

「拜托了。」

寻人启事贴在了墙上，昴也监制了这启事的人面画像，概括了相当多的缇雅的特征。即使如此，她那超乎常理的美貌是一张纸画不尽的。

事到如今，人们甚至怀疑缇雅是不是并非这个世上的存在了。

「但是，这和我这被拍扁的鼻子的痛楚绝对不是一回事。」

「被拍扁的鼻子？」

「没什么。我自言自语而已。」

昴对克莱茵挥了挥手，离开中介屋。他也以自己的方式，把缇雅视为家人一般担心着。昴愈发地扎心了。

仿佛这个世上，只有自己对缇雅抱有隔阂一般。

「哈，太蠢了。我还有闲工夫说这个吗……去买葱忘掉它吧。」

昴挥散这在心头挠痒的想法，在蔬菜店前买了一份很像葱的蔥。将其放进手提袋中，然后开始在脑海里编织起今晚的菜谱。

「因为一开始买的是葱，那就主打葱……不，毕竟葱是万能的选手，即使不以葱为中心，也完全能搭建成一个团体。」

多亏了蕾姆和妇人们的指导，昴习得的菜谱十分丰富。他在这些菜谱之中，要挑选出在商业街各家店里挑选的各种菜品中最适合的一种。

拧檬、土逗、白蔡、料理酒、鱼、蛋、米和酱油和缇雅、还有小麦粉——

「——缇雅？」

昴正在认真地斟酌着食材时，视野中一瞬间捕捉到的身影让他摒住了呼吸。刚怀疑是不是看错了而凝神细视的时候，那白色的头发消失在人山人海的另一头。

虽然只有一瞬间，但没错，那是缇雅的背影。

「缇雅！等等，你，等下啊——！」

一瞬间，昴抬高了声调，拼命地跑起来。

昴钻进人群的缝隙，紧紧追逐远去的背影。畅通无阻地，缇雅就像是毫无障碍一般前行，另一方面昴正撞开别人往前进。

即使如此，步行的人和奔跑的人之间的距离总是会缩短。忽然，缇雅的头在人流中消失，昴焦急地四处巡视——于是看到了消失在小巷中的礼服一角。

「缇雅——！」

昴一边在心里祈祷着没有看错，一边转向小巷那边冲过去。就这样，猛踢着坚硬的地面直冲进去，便看到一个在暗处的过道上站着的人影。

对女性来说略长的纤细而奢华的后背，在肩头处剪齐的精短的乳白色头发，毫无疑问都是她的东西。

「哈啊，哈啊……缇雅，你，真让我好找。为什么逃走了啊？」

「————」

缇雅没有回答昴的问题。不过，她也没有再跑掉的意思。明白了这点，昴调整好呼吸，同时把手上的行李放在地面上。

于是，昴走近在黑暗中伫立的缇雅，把手放在她的肩上。

「喂，我知道你很难面对我。虽然知道，但至少转过这边来啊。」

昴抓住黑色礼服的一肩，语气有些粗鲁，饱含了能见到她的欣喜，以及那一晚上纠纷的尴尬。

至少，她如果露出痛苦的表情的话，说不定能变得更坦率。

带着这样的念想，昴将她转过身——

「——去死。」

从正面，近在咫尺之处袭来一阵扬起杀意的风。

3

「阿昴！在吗！？」

「赫鲁贝尔大人！？」

家里的大门被猛地打开，这闯进家中的声音让蕾姆惊呼出来。仔细一看，冲进家里的是黑毛的狼人——赫鲁贝尔。

蕾姆一个月不见的面孔。然而，对方却以无法欢迎的气势，在家中扫视了一番。

「蕾姆酱，虽然很久不见了，但有急事。阿昴呢？」

「昴君现在，出去买晚饭的食物了。我想很快就该回来了……」

「咕噢噢，这不是最坏情况的错过了吗！不行不行，这样不行。」

赫鲁贝尔沙沙地挠着头，心情无法冷静下来，声音充满焦躁。蕾姆感觉到事情不简单，挺着硕大的肚子站起来。

「赫鲁贝尔大人，请问发生了什么事？如果和昴君有关的话请告诉我。」

「啊，勉强蕾姆酱是不行的。虽然我的说法可能不太好，但和阿昴有直接关联很不妙……不，那倒未必，吧？」

「赫鲁贝尔大人？」

「蕾姆酱，之前听说过一次吧？还记得吗？嗅到了阿昴可能被某人盯上的气息。」

赫鲁贝尔的问题让蕾姆瞪大了眼睛。虽然和正确的意思有所偏差，但大部分都是正确的认知。

昴被某人盯上的可能性——过去，在缇雅要加害于蕾姆他们的时候，蕾姆推测出了她的目的并将此事告诉了赫鲁贝尔。

包围着昴的瘴气——也就是，魔女的余香的可能性。

「是的，我说过。但是，和那个没有关系……事实上，缇雅大人的目标并不是昴君而是蕾姆，这一点也是误会了才对……」

「不，不是的。虽然没有误会，但也并非毫无关系。糟糕，我这说法不太好。没错，是误会。把它当成了『误会』。」

「误会？误会，是指什么……」

「犯人的真实身份，以及缇雅酱的真实身份。」

意料之外的答案让蕾姆屏住呼吸，赫鲁贝尔那总是眯成细线的眼睛大睁，里面藏着的黑色眼瞳中寄宿着极度的悔恨。

「我失算了。找不到借口，完全的失态。我把一切的一切都想错了。因为这个缘故，才酿成了这么麻烦的事态。」

「我，我不明白，赫鲁贝尔大人。请从头开始，详细地说一遍。」

「——开始是，大约一年前。契机是探索塞蕾丝缇雅的睡窝。」

赫鲁贝尔听从蕾姆的要求，诉说出来的内容又是一道晴天霹雳。

原来，她是被称为四大精灵的拥有强大力量的四个大精灵之一，在卡拉拉奇西端的『塞蕾丝缇雅的睡窝』这个地方所居住的存在。

只是，说到探索那个地方会成为某种契机的话——

「塞蕾丝缇雅的睡窝，是个只要有人接近就会吹起死亡之风的有名的地点。募集前去的调查队时，一开始也被笑话成不要命的无谋的挑战……」

「然后呢？」

「也不知道是奇迹还是啥的，只有一个人从那里生还而归。本来，只是能够生还就已经是捡回一条命了……」

赫鲁贝尔的话语没有结束的地方引人浮想联翩。

然后，赫鲁贝尔被焦躁感所驱使着，就像要确认前方的东西一样，那东西在脑海连为一体的瞬间，蕾姆恐惧地睁大了眼。

「——生还下来的女人，是憎恨魔女教而向塞蕾丝缇雅渴求力量的复仇者。」

4

——风吹了起来。

这恐怕是，能将昴的肉体轻松撕成碎片的尖锐的风。

亦或是被这风所切割，成为鲜红的肉片，这一切或许是对将她的背转过来的昴的惩罚。

一瞬间，想到了这些事情。

「——你，干嘛呆住了啊？蠢嘛你！？」

「呜哦！？」

领口被拎起来，连抵抗都来不及就被往后边扔去。就这样弹在地面上，姿势都没摆好就滚了一圈，再滚一圈，又滚了一圈。然后，因疼痛而皱着眉头从正面看去，把昴扔出去的人是——

「缇、缇雅、吗？」

「像我此等的美人，应该别无他者了。……呃，虽然还想再说下去，但看来似乎有点不妙了呢。」

保持稍微前倾的姿势，回过头来的缇雅——不管是粗野的语气，还是粗鲁对待昴的行径，毫无疑问都是她。

然后，说到缇雅的话中之意，看到眼前的光景很快就能明白。

「————」

把昴丢到后边的缇雅，是现在站在面前的缇雅。

同一副面孔，同一副姿态的两个缇雅，正针锋相对。长相一模一样的两人，只有她们的装束，除了一黑一白的礼服以外不再有区别。

一身黑的缇雅想要抹杀昴，而一身白的缇雅则保护着昴。

也就是说——

「黑缇雅是敌人，而白缇雅是友军——！」

「话虽然没错，但这种说法很让人不爽，啊！！」

白缇雅的声音盖过伏在地面上的昴的叫声，一口气冲出去。纤细的身体弹射出去，从正面往与自己相同面孔的对手猛扑过去。

白缇雅那野兽般的身体能力，使手臂毫不留情地往黑缇雅脸上狠狠挥打过去——那一刻，黑缇雅毫无理性的凶恶的美貌上刻上了笑容。

「——去死吧。」

「——！」

白缇雅猛地向上一跃，回避追打过来的刺击。但是，不可视的攻击朝白缇雅追来，在空中接连不断地袭击。白缇雅猛踢墙壁，以三角跳跃的要领往斜上方跳跃，逃跑，逃跑，一直逃跑。

「这家伙……！真烦人！」

虽然跳上了墙壁，卡拉拉奇的建筑物基本都很矮。很快到达小巷上方，白缇雅任由愤怒往地面上挥舞手臂。一瞬间，与黑缇雅的刺击同时发起的攻击已经压至眼前——但是，威力却有明显的差别，白缇雅这边更劣一筹。

就好像预定要发生一般，黑缇雅将其一瞬间击飞回避掉了。

「啊啊真是的！明明只是我，我却——！」

「——去死吧。」

面对怒伤心头的白缇雅，黑缇雅只是将暗怀杀意的言语说出来。

但是，其实力之差仅仅通过几回合的攻防就显现了出来。如果这样继续一对一的战斗，势必会对白缇雅不利。

昴明白自己只能陷入旁观的境地。因而——

「——看这边，假缇雅！」

「————」

昴沉重地站了起来，将墙角——在他被风卷走时放在一旁的手提包中滚落的东西投掷出去。

然而，最先划出抛物线扔出去的却是遗憾的葱。绿色细长的蔬菜毫无气势地回旋着，在到达黑缇雅之前就已经落地。

但是，这样就好。这样就够了。

并没有期待能打出什么伤害。因为并没有放入任何武器。只是，只要能构筑起疑似二打一的状况，只要能弥补白缇雅不足的部分的话——

「————」

「咕、唔……」

仅仅是被投以视线，昴的内心就紧张不已，缩成一团。

黑缇雅的双眸很空虚，看不到像是感情的感情，像是意志的意志。里面有的只是黑暗——只有将其体现出来的漆黑的杀意。

杀意，仅此而已。可怕的是，黑缇雅的内心只有，杀意。

因此，黑缇雅的行动即使单纯本身。仅仅做出为了杀戮而最合适的行动。而这一瞬间，她杀意的目标并非白缇雅，而是转向了昴。

「该死，的……！」

预感到死亡临近，昴挥着手腕抵抗着席卷全身的恐惧。只是，这终究也只是无谓的抵抗。对手中的壶没有施加太大的力气。最终果然没有打到黑缇雅，而是落在她跟前的地面上发出碎裂的声音。内含的东西全都倾倒出来。

——一瞬间，黑缇雅的面相发生了变化。

「——！？」

「什么？」

突然，黑缇雅睁开双眼，紧紧盯着落在眼皮底下的壶。躺在那里的是一个破碎的水壶——一个料理酒的瓶子，里面的东西全都洒在了地板上。

「只是，单纯的酒哦？」

「——」

对于昴呆然的声音，黑缇雅无暇应答。她绷紧了脸颊，手掌覆在脸上向后退，发出充满痛苦的呻吟声。

对着忌惮之物，黑缇雅就像胸口被撕裂了一般，对酒感到恐惧。

「——有破绽！！」

这时，白缇雅从建筑的房檐上急速下降，乘着惯性踢了过去。

黑缇雅毫无防备地正面吃了这记飞踢，猛地摔了一跟头向后飞去。滚了几圈，重重地撞在墙上，在小巷的地面上摊成大字。

「成功了吗！？」

「对！虽然不太清楚，但她突然放松了警惕算她好运到头了！接下来，我就亲手让她尝尝报应，呜诶！？」

昴的喝彩声，与白缇雅的胜利欢呼声叠起来。白缇雅刚准备就这样乘胜追击，但脚边的悲鸣戛然而止。

白缇雅对恰在自己脚后跟的酒瞪大了眼睛。

「~~~~！？什么！？这是啥！？呜诶，呜诶诶诶！！」

「连你也这样！？怎么回事啊！只不过是酒……」

白缇雅做出与黑缇雅一样，甚至在她之上的排斥反应。看到这不寻常的样子，昴理解到她们对酒的排斥反应不是喜恶感这么单纯的事。

但是，昴还没来得及深究，一个让他不敢相信自己眼睛的事态发生了。

「咕、呜呜呜……」

「啊啊？那家伙，脸型崩坏了……不，是变模糊了……？」

黑缇雅哼着呻吟，慢慢站起身——她那张脸，那张与白缇雅面容别无二致的脸逐渐崩坏，慢慢地剥落了。于是，藏在里面看着的是与缇雅完全不同的另一个人的脸。虽然冷峻的眼神很相似，但却有种特有的不和谐的黑暗。

她脸色煞白，发色从乳白色变化为茶色。体格也开始变小，就像是魔法被解除了一样的变化。

「你……！」

虽然这一切已经足够让人大吃一惊，但更为吃惊的事情让昴大睁眼睛。

——跪在地上的女人，头上伸出两根发光的凸起物。

「角……？这么说，你，是鬼吗？」

「——」

额头上伸出的两根角，让昴得出这个结论。与蕾姆相同，是鬼族的出身或者是后裔。听到这个结论，女人痛苦而又悔恨地，激烈地喘息。

「去死！去死！去死！」

昴被卷进这杀意的龙卷风而感到压迫，不由用手臂挡住了脸。但，女人没有去将杀意化为行动，而是张开手臂，发起大风。

小巷左右并排的建筑物，被女人两手发动的狂风卷入而被连根拔起，瓦解崩坏。房屋的柱子断掉了一半，所有房屋都被当场破坏，全都埋没在小巷中。

「可恶！喂，缇雅……啊啊，可恶！」

「呜呜……这个，这个，什么，是什么呀？要对我……唔呀。」

房屋倒塌的前一刻，昴呼唤着缇雅。但是，缇雅仍在被酒气吸引的冲击中无法自拔，昴无可奈何地抱起她纤细的身体，朝后方逃去。

「唔噢噢噢噢——！」

崩坏的巨响从后方压迫过来，而昴则全力地直线逃跑。于是穿过狭窄的小巷之后，崩塌立即到达了终端，小巷完全被埋没在废墟之中。

生成的大风和扬起的尘埃，这巨大的骚动引起外头的人们注意而纷纷赶来。他们很快也向倒在小巷入口的昴和缇雅伸出援手。

「那家伙是……」

借别人的手站起来后，昴回头看向崩塌毁灭了的小巷。除了昴和缇雅以外，没有看到跑出这个小巷的人影。但是，这次崩坏把那个女人卷了进去并就这样被压在底下，这种事不太可能吧。

让她逃掉了。让那个长着和缇雅一样的脸，和蕾姆一族的有角的迷之女人。

「究竟是何方神圣啊，那个女人……」

昴用袖子擦了擦被沙粒和汗水弄脏的脸，轻喘着气同时嘀咕着。这句话的答案，不可能由那个逃掉的女人自己带来。

反过来，要说能给昴带来答案的人——

「——可以对你有所期待吧？缇雅。」

「……我不知道。」

终于从酒的冲击中脱离出来的缇雅，板着脸不爽地答道。

听到这很像她的回答，昴不合时宜地露出安心的苦笑。

5

「——昴君！你没事太好了！」

「噢喲，好危险！」

刚刚回到家，冲出玄关的蕾姆就慌忙抱住了昴。虽说气势很足，但也不至于抱不住妻子。

话虽如此，这无疑是产期将至的孕妇有所收敛的爱情表现。

「蕾姆，你对我回家感到欣喜这点我很高兴，但每次回来都这样的话我的寿命会缩短的。稍微为肚子里的孩子考虑一下吧。」

「对、对不起。但是，我听说昴君很危险……」


「我很危险，谁说的？」

昴对怀中的蕾姆温柔地询问，但听到她的回答后却眉头紧锁。消息传的太快了。昴遭遇危险才过了仅仅一个小时，情报应该没传开才对。

其实，情况允许的话昴也想等冷静下来再慢慢解释。

「答案就是我，阿昴。」

「……你来了吗，阿赫。怪不得消息这么快。」

这份疑虑，在看到走廊深处出现的赫鲁贝尔的存在时就烟消云散。如果是忍者赫鲁贝尔的话，用某些特定的方法在街上布下眼线也不奇怪。根据情况，昴甚至会怀疑街区各个角落都潜藏着他的分身。

「不过，不要用消息灵通这点来让蕾姆不安了。因为是很重要的时期啊。」

「关于这点我很抱歉，不过这也在我预计之外哦。没想到阿昴正好在这个时间被袭击，既然知道你被袭击，还若无其事地不过来通知的话，蕾姆酱很可怜的吧？」

「昴君，请不要责怪赫鲁贝尔大人了。况且赫鲁贝尔大人也阻止了蕾姆飞奔出去呢……」

「就是就是。」

赫鲁贝尔听到蕾姆帮他说话得意洋洋。昴对他的态度深恶痛绝，但又久违地感到了像是他的作风，便错失了发怒的时机。

而且，现在不是该发怒的时候。因为有最棒的礼物要给蕾姆。

「真的发生了很多事，虽然我也很想先说清楚发生过什么……」

「嗯，请让我听听吧，真的很担心你。」

「但是，在那之前，有个想让你见的家伙。」

已经摆好姿势聆听的蕾姆，听到昴的话头上冒出一个问号。昴对她笑了笑，回头转向拉门的方向说道。

「你要藏到什么时候，进来吧。」

「————」

昴说完话后，一开始没有任何反应。但是，短暂地陷入沉默之后，或许是对方耐受不住这种紧张的气氛，心惊胆战地露出脸。从拉门背后偷偷摸摸露出头部窥视过来的是，三个月前不见了踪影的少女——

「——缇雅，大人？」

「好、好久不、见……」

「缇雅大人！」

「呀！好危险！！」

蕾姆发现对方是缇雅，感慨至深地跳了过去。缇雅因为这一飞扑而仰面朝天，慌慌张张地抱起这副身躯，不断重复。

就这样，缇雅将抱起的蕾姆慢慢地放在玄关上。

「很、很危、很危险的啊！你忘记自己是个孕妇了吗！？要是我躲过一边去可就不得了了哦！？」

「因为蕾姆相信，缇雅大人不会这样做的。」

「咕、咕呶呶，咕呶呶呶……」

缇雅看到蕾姆亲热的目光，悔恨地咬着嘴唇发出碎念。然后，她忽然像是放弃了似的叹了口气，看向身旁的蕾姆的肚子。

这个肚子比缇雅曾经见过的样子又膨胀了许多。

「……已经，很快就要生了呢。」

「是的。与缇雅大人的约定的期限就要来了呢。」

「————」

蕾姆的语气装作在开玩笑，实际上却看透缇雅眼中已经没有期限这回事了。实际上，这个见解是正确的。

对缇雅来说，杀死蕾姆这种事已经绝对不可能做到了吧。而且——

「蕾姆，关于这件事有话要说哦。」

「缇雅大人对蕾姆的话吗？」

「这是对蕾姆说的，也是对阿昴和阿赫说的。」

缇雅不只是对蕾姆，还对旁边的昴，以及走廊深处的赫鲁贝尔说道。她的表情很认真，神色有点不安地窥视着各位说道。

「我……我终于知道了有什么事是不得不去做的了。所以，我想把这件事，好好地跟你们说一下。」

6

将阵地转移到菜月家（临时）的起居室，四个人终于又久违地坐在了一张桌子前。

距离上一次全员齐聚一堂也过了大概三个月之久——只是，接下来即将开始的却并不是轻松愉快的用餐时间。

而是为了共同商议更加严肃的事儿而必须得召开会议的时间。

「我……」

正襟危坐、把双手规规矩矩地放在膝头的缇雅第一个开了口。她稍微犹豫了一会儿、像是不知道接下来该怎么继续。

「我是为了复……不不不，是为了拿回被偷走的光珠才找上你们的。你们都还记得对吧？」

「嗯嗯，当然记得了。毕竟第一次见面那一次，你可是让我吃尽了苦头呐」

「就是在夜路上突然袭击了蕾姆和昴君的那一次吧」

昴和蕾姆夫唱妇随地相继回答道。然而，这答案却半对半错。昴说的才是对的，蕾姆错了。

不过说回来昴原以为这回事儿已经再清楚不过、还没有这样直接地相互确认过——

「蕾姆，事实上那天晚上缇雅在路上倒是没有加害我们。缇雅干的好事儿是在那之后，她偷偷潜入了长屋里，把我给痛打一顿叫我差点儿就没见到第二天的太阳」

「诶？可是，这样说来……」

「是啊、那是我的第一个失误……我也真是啊，再马虎也要有个限度啊」

听了昴的话连连点头的不是一脸困惑的蕾姆，而是赫鲁贝尔。第一个察觉到事情的真相的，也正是和来袭者真正正面交了手的赫鲁贝尔。

——那天夜里，在回家的路上突袭昴他们的是黑缇雅，而自那天晚上之后，直到今天他们也再没有碰上过这个犯人了。

「为了方便，我们把她叫做黑缇雅吧，事实上，黑缇雅和缇雅长着极为相似的面孔。当然不仅仅是脸，包括身形姿态都是一个模子刻出来的。所以才叫咱们都弄混了。更何况缇雅本人也没否认过啊」

「可是那天晚上我胖揍了阿昴一顿也是事实嘛，再说了我也不知道竟然还有个长得跟我一模一样的女人啊」

听了昴的话，缇雅别开了视线、辩解般地回敬道。

不过自不必说，这也的确不是缇雅一个人的责任。要是当初能再深入谨慎一点儿和缇雅聊一聊，应该也就能立刻发现这不对劲儿了。

而之所以没能如此，也是因为他们一直把害怕使得和缇雅的关系恶化作为借口，来逃避和那天晚上的缇雅坦诚相对的缘故。

「这也不是阿昴的错。当时我本应该早点注意到『死神』这个名号的」

看着昴低着头沉思的侧脸，赫鲁贝尔叼着嘴里压根没点上火的烟袋嘟囔道。今天的赫鲁贝尔就像变了个人似的，他的耳朵软趴趴地折了下来、一副沮丧的模样。

「那个，『死神』也能成为线索吗？」

「何止是线索，那就是答案。——诚然，道上还从来没有过被叫做『死神』的人。但是，这正是因为已经有了一个最负盛名的『死神』，还没有人能敌过她的」

「最负盛名的『死神』……」

「——『最美丽的死神』」

赫鲁贝尔用一副诚惶诚恐的口吻叫出了这个名号。

闻言昴一时间还反应不过来，然而，蕾姆却猛地抬起头来瞠目结舌地看向了缇雅，甚至嘴唇都在颤抖。

「『最美丽的死神』，塞蕾丝缇雅……」

「塞蕾丝缇雅？塞蕾丝缇雅这名字、好像……」

好像在哪儿听过。刚要说出后半句，昴记忆里的那副画面突然无比鲜明地复苏了。那是在几个月之前，从中介克莱因嘴里听到的。

那是在别人给介绍了玛格洁宅邸的工作之前，昴凭着一腔意气自己找到的一个悬赏任务——那上面写着的就是「找到塞蕾丝缇雅的睡窝」。而且，这是一个向大精灵界发起挑战的任务书。

也就是说，在那里安家的大精灵的名字就是——

「大精灵、塞蕾丝缇雅」

「——这就是缇雅酱的本名啊」

昴的声音就像好不容易才从嗓子眼里给挤出来的一般，而赫鲁贝尔只是口吻淡淡地附和道。

然而眼下这个结论也未免太荒唐了。说起来，这要是真的，那这个假名也老套透了。原本应该这样打趣着一笑而过的，在场的却没有一个人笑得出来。

就连被昴指出来真实身份的缇雅也没有丝毫笑意，只是很怅然若失地叹了一口气

「我还是先说清楚吧。我正是你们口中所说的、塞蕾丝缇雅」

「缇雅大人……」

「不过，我并不是完整的塞蕾丝缇雅。我只是一半……不，还没到一半呢。我只不过是自己的一小部分罢了」

「这、这是什么意思？」

将手按在了自己的胸口，缇雅承认了自己大精灵的身份。然而，她接下来的解释却过于暧昧，昴不禁困惑地反问道。

而附和了一头雾水的昴的，却是蕾姆。

「这也正好是跟之前赫鲁贝尔大人说过的、有关搜查队的那事儿密切相连的对吧？」

「搜查队？也就是说接下那个任务书的？可是克莱茵说了啊，那次行动失败了」

「失败？哪有那回事儿啊？那群家伙岂止是偷偷摸进了我家，甚至还把我最最重要的……光珠给偷走了呢！」

缇雅的声音突然提了个八度，激动地一口否定了昴的话。

光珠，就是缇雅一口咬定是被蕾姆偷去的东西。也正因此，她才一直盯着蕾姆不放。

然而蕾姆本人却对此物毫不知情，甚至所谓光珠这种东西到底存在与否都叫人怀疑。而事到如今，这东西却真真正正地成了一切事情的重要线索。

「所以说到底，光珠究竟是个什么玩意儿啊？你一直要找的是什么东西呢？」

「光珠就是我力量的来源。是封印了我一直以来积蓄的力量的一块石头」

「石头？怎么……不对，你是精灵的话」

缇雅的说明并不怎么充分，但昴已经抓住了重点并在心里想出了个大概。对于像缇雅那样用玛那来造出肉身的精灵一族来说，为了让自身能在这个世界长久地留存下去所必要的石头——

「——是凭依之石吗！是精灵为了留存在世界上必须依赖的依附物！光珠就是指这个！」

终于想明白了，昴确信无疑地打了个响指叫出了声。

精灵要想变成拥有行动能力的实体，就必须得有玛那。而成了大精灵，玛那的量自然也就与日俱增，需要有储存着大量玛那的凭依物。而这凭依物，就正是缇雅口中的光珠了。

「那么重要的东西竟然被偷走了……所以，缇雅就是专程为夺回光珠而来啊」

「可是，又为什么会一口咬定说是蕾姆偷走的呢？蕾姆是真的对那所谓的光珠毫不知情。甚至从来都没有踏近缇雅大小姐的地盘附近哪怕一步……」

然而总算弄清了光珠是怎么一回事儿之后，蕾姆反而更加困惑了。但与正皱着眉百思不得其解的蕾姆不一样，昴是能够察觉到问题所在的。

他不禁想起了之前的那一次袭击中，黑缇雅的外表分崩离析、映入眼帘的却是另一个人。

正是因为如今光珠和缇雅的身份都水落石出了，这一直以来叫昴怎么也想不明白的一幕，眼下也大抵能推测出来一二了。

如果要说那隐藏在黑缇雅的外表之下、最终才现出原形的女人就是偷了缇雅光珠的犯人的话——

「——黑缇雅长着角。而且，那是鬼族的角」

「鬼族的角？那难不成……」

「怪不得当初缇雅满脸得意地说、是自己用鼻子嗅出蕾姆身份的呢。缇雅是把蕾姆的血……也就是鬼族的血，同其他的鬼给搞混了」

「就是这样啦……我竟然也会犯这样的错，也实在是叫人懊恼啊」

终于得知了真相，蕾姆不由得瞪大了双眼。

正是由于把缇雅卷入其中的这一连串事件，才使得她误打误撞地结识了昴和蕾姆两人。并且，这个误会在之后也一直都没有消除，这才招致了如今这种种误解。

不过这当然也不能全怪在缇雅的轻举妄动上。毕竟不是当事人，谁也没法体会到自己身体的一半以上都被人给夺去了究竟是一件多么叫人心焦的事儿。

「也就是说，只要把那个偷了塞蕾丝缇雅的凭依石……光珠的鬼族女人给捉住问题就解决了吧……不对，等一下？」

正要得出一个简单明了的结论，昴却突然困惑地歪了歪脑袋。这个推测的确是无比贴近真相的，却欠缺了最重要部分的解答。

就算面前这个缇雅是由于失误才袭击了昴他们的，那么那之前的黑缇雅，又究竟是为什么先行对昴他们下手了呢——

「没错儿，问题就在这儿。我这里倒是还有一句话想说呢？」

「在这种时候听你说出来这样的话，总觉得有一种不祥的预感啊」

「对不住阿昴你了，这的确不是什么叫人开心的话」

看着昴一脸不情愿的样子，赫鲁贝尔苦笑着挠了挠脑袋。

「我要说的也就是偷走了缇雅酱最重要的东西的那家伙。经过我这么久以来的暗中调查，大抵也算是知道了点真相」

「蕾姆刚刚也说了搜查队什么的，好像就是你偷偷和她说的吧？」

「蕾、蕾姆也是刚刚才听说的呢，并没有瞒着昴君什么啊。对蕾姆来说，赫鲁贝尔大人和昴君两人的重要性，根本无需衡量就能得出结论了啊！」

「这话听着莫名扎心啊。还是接着说吧，我就尽量简短点」

看起来接下来要说的话，就连到家后一直忍不住问东问西的蕾姆来说也是不知道的了。昴对赫鲁贝尔点了点头，说了一声「有劳」催促着下文。

「就是光珠嘛。据说那个偷去了光珠的家伙之所以想要找到大精灵的所在地，从一开始就不是奔着光珠去的，而是因为渴求大精灵的力量才参加了搜查队的」

「渴求大精灵的力量？这也只能说是太乱来了……是为什么呢」

「我猜，是复仇吧。——是为了向那些纵火烧毁了自己故乡的魔女教复仇」

「魔女教……！」

一直在竭力避免的这个忌讳的词语就这样突兀地被说了出来，昴不禁颤抖起来。

尽管没有直接的关系，但那个集团已然给昴留下了最糟糕的一段记忆。更何况，得知了黑缇雅也对魔女教抱着相当的仇恨，他心里的滋味儿更是复杂透顶。

为了讨伐魔女教才不惜盗取了光珠，想要借用大精灵的力量。而那女人要向魔女教复仇，又会怎么使用这颗光珠呢——

「——啊」

想到这儿，之前一直盘踞在心里的疑问的解答总算是浮出了水面。

犯人的目的是为了向魔女教复仇，而光珠不过是为了达成目的而需要的力量罢了。而如今拥有了这力量，犯人自然就会开始四处搜寻魔女教的下落，嗅出在巴南城里遗留着的魔女的踪迹。

所以说，对于那女人来说复仇的对象、也就是那天晚上她真正的目标是——

「——原来是我啊」

「复仇者是奔着阿昴，而缇雅酱是奔着蕾姆酱来的。正因为咱们此前一直没弄明白这一点，才会导致了这样那样的误解啊」

赫鲁贝尔一句话就做出了总结，昴心里的疑云也总算是都消散了。

狙击目标的混淆、与误把两个人当成了一个人，正是一切问题的根源所在，也是把事态弄得如此复杂，导致了云里雾里的状况出现的罪魁祸首。

「现在咱们是弄清楚了这乱麻一般的状况了。这下子就解释得通了」

掌握了再明显不过的事实，昴一边整理着思绪一边斟酌着措辞。

沦落成了犯人的女人、作为复仇对象的魔女教、昴的内心是对这件事怀着同情的。

「可是，犯人想要冲着我来就是个误会了。尽管，她对魔女教深恶痛绝的心情……我也懂。可是就算杀了我仇恨也没法儿消失。那样一来，缇雅的光珠也发挥不了价值」

「虽然你的说法有点儿那啥，但话糙理不糙。虽然这样做有点对不住那家伙了，不过我还是得好好教训她一顿把光珠夺回来。那之后，就顺其自然好了」

「就该那样做」

听了赫鲁贝尔的一席话，昴也连连点头表示赞同。

就算疑问全部都解决了，但结论是从一开始就不可能让步的。对昴而言，比起素不相识的复仇者的夙愿，还是蕾姆的安全和缇雅的焦灼心情更为重要。倒不如说，正是通过这一次把事情从头到尾都给理清了，才能毫无顾忌地着手去给这一切画上句号。

「只要把这件事儿解决了，就又能像以前一样大家一起……」

——等到一切都平息了，就再一起相聚餐桌上吧。

「——那是不可能的了」

明明应该继续下去的美好展望，却被突然站起身的缇雅给否定了。

缇雅的口气冰冷又固执、不容丝毫商榷的余地。这使得其他三人纷纷抬头向她看过去。

而缇雅只是抱住了胳膊，有意把目光给错开不去看他们其中的任何一个。

「抱歉。我做不到。一旦夺回了光珠，我就必须得回我的地盘了。我是不可能和你们一起生活的。这一点是铁板钉钉的」

「可是、为什么呢？蕾姆……不，如果说是缇雅大人还对之前的事儿过意不去的话，没关系的，蕾姆不会放在心上的！因为现在大家都已经知道了缇雅大人的难处了」

「不是啦，蕾姆。我呀，是和你们没法儿共存的存在啊」

缇雅已经顾不得正座不正座了，她朝着倾吐了心迹的蕾姆连连摇头。她的态度过于隐忍，不止是蕾姆、就连昴也不知道她究竟在想什么。

然而——

「咱们现在都察觉到了缇雅酱的真身是塞蕾丝缇雅了，可我还有一件怎么也想不明白的事儿。只要这一点解释不通，那整件事儿就牛头不对马嘴了」

赫鲁贝尔抱起他那粗壮的双臂，把一双狭长的眼睛眯缝得更厉害了。他那话里有话的口吻叫人很是不愉快，昴不由扬起了眉梢。

「你到底想说什么啊，赫鲁贝尔。别装腔作势了直接说吧」

「……塞蕾丝缇雅是『死神』，是杀人嗜血的大精灵。凡是闯入她的住处的人，格杀勿论。就是流传出来的有关她的轶事也全是事关杀戮的。既然如此，那咱们的缇雅酱又是什么样的呢？」

「那……那不过是添油加醋的谣传罢了、对吧？」

听了赫鲁贝尔的质疑，蕾姆一反常态、强硬地反驳道。就是昴，现在也是同蕾姆一样的心情。尽管如此——

「没错儿。不对劲的，是现在这个我啊」

「缇雅大人！」

「阿赫说得没错儿，我本就是只会杀戮的精灵……不，不是只会杀戮，而是我脑子里除了杀戮别无他物啊。只不过，被剥夺了几乎所有力量，我就成了现在这个残缺体，就连杀戮的意识也弃我而去了」

这么长时间以来，尽管缇雅常常语出惊人，但昴他们却从来没有当真过。不过结合她偶尔会展现出的极为凶残的一面来看，她大精灵的本性也的确可以窥见一斑。——而就连这一点，现在也只能是缇雅的奢求了。

「只要夺回了光珠，我就会再次变回那个满脑子只有杀戮的精灵。哪怕是蕾姆也好，阿昴也好，阿赫也好，整个城里的人们也好，我都会不分青红皂白地把你们杀掉的。所以我是不能和你们再一起待下去的。所以，这已经是最后一次、最后一次了啊」

「这实在……缇雅大人，难道……难道就没有别的办法吗？」

「————」

面对着不肯死心的蕾姆，缇雅只是一再地摇头。蕾姆的眼里泛出了泪光，转头看向昴和赫鲁贝尔。然而，看到蕾姆伤心的模样，昴却一句话也说不出来。赫鲁贝尔也闭上了双眼，用牙齿咯咯地咬着衔在嘴里的烟袋，像是在懊恼自己的无能为力。

谁也没法儿为缇雅做些什么，谁也做不到。就算缇雅主动放弃了光珠，但事实就是复仇者现在已经锁定了昴这个狙击目标。

并且——

「我是绝对要夺回光珠的。放弃之类的事儿，我是绝不会做的」

「……啊」

缇雅掷地有声地下了决心，只见蕾姆突然就像被抽走了全身的力气一般坐倒在地。仅仅用悲伤的眼神俯视了蕾姆一眼，缇雅就用力闭了闭眼睛。

而后，她走到蕾姆身边，把手轻轻地放在蕾姆已经高高隆起的腹部上

「——叫你久等啦，真是抱歉呀」

冒出这样温柔的一句话，她轻轻地抚摸了一会儿。除此之外她再也没有任何动作，只是重复了一会儿这毫无意义的举动——刚这样想着，蕾姆的表情突然变了。

「刚、刚刚……缇雅大小姐，你说了什么……？」

「已经到了期限了，蕾姆。我和你的约定，到此为止了……不过一切都是我误会了，或许本就不存在什么约定不约定的吧」

缇雅自嘲地小声说着，只见在她面前的蕾姆缓缓地、缓缓地俯下身。手紧紧地捂着刚刚被缇雅抚摸过腹部。看到她这副模样，昴脸色大变慌忙飞奔过去。

「蕾姆？蕾姆，你没事儿吧！？喂，缇雅，你对蕾姆做了什么！？」

「我只不过是抚摸了一会儿。真的啊。只不过是蕾姆心灵上的枷锁解下了，于是肚子里的孩子就意识到了，总算已经万事俱备了」

是不是和缇雅有关暂且还不知道，但昴现在也已经知道将会发生什么了。

往常的从容已经从蕾姆脸上消失了，她的呼吸也变得急促起来。从她的侧脸也能很明显地看出她此刻正在忍受着痛楚，见到她抱着自己高耸的腹部的模样——

「……阵痛已经开始了！」

「直到孩子降生的那一刻，我都不会对你们出手。这就是你和我的约定」

让昴惊慌失措的这一刻终于到来，而缇雅冲着蕾姆俯下身

「正因为有这样一个约定，你才为了我拼命地、拼命地忍了又忍，想要把这一刻延迟呢……妈妈也是孩子也是，你们都太固执了吧」

「缇雅、大人……」

蕾姆竭力想要拉住满脸温柔地微笑着、想要退到一边的缇雅，但腹部传来的疼痛让她伸出去的手终究只是捉到了一片虚空，就这样缇雅拉开了两人的距离。

轻盈地飞身跳到一旁的缇雅打开了推拉门，顺势纵身跳到了庭院里不再回头。

「缇雅！」

「这一切由我而起，也将由我来终结。——要是我失败了，阿赫，就拜托你了」

缇雅在庭院中央突然站定，转过身来嘴角挂着一抹浅笑如是说道。而听了这活像遗言一般的话，又被当事人指名道姓地要求收拾残局，赫鲁贝尔不由得歪了嘴角。

「哪儿有自己明知道胜算渺茫还非要去赴死的道理啊。连帮一把手也不愿意对我说出口，这是大精灵的矜持吗？」

「哪儿有那么夸张啊。——我可是很强的哦，我是不可能会输的」

缇雅爽朗地嫣然一笑，冲着赫鲁贝尔回敬道。

而后，缇雅最后的一眼就看向了昴，还有蕾姆。

「该怎么说呢，这话或许不怎么符合我的身份，嘛」

「缇雅大人……」

「那一天，那个，对不起。是我不好呢」

一边用手指不自在地搔着脸颊，缇雅一副难为情的模样向蕾姆道了歉。只不过是要把这样一句话说出口，她却表现得比说出自己真实身份那会儿更紧张。

而后，或许是看自己总算成功说出口了，缇雅一副轻松愉快的表情又加了一句。

「一定要生出健健康康的宝宝啊！要生好多哦」

话音刚落，缇雅的周身便卷起了一阵阵风。那不是疯狂凌厉的风，而是温柔地包裹住身在庭院中央的缇雅，将她带着升上空中的风。

根本就来不及制止。乘着风，只见缇雅的身影一眨眼便腾空而起。眼看着她就要渐行渐远，蕾姆伸出了手腕，拼命地喊了一声。

然而却传达不到。声音也好，手也好，都没能挽留住缇雅，她的身影朝着这被夜幕悄然笼罩的天空的另一头消失了。

「缇雅、大人……」

「缇雅——！！」

就像代替嗓子沙哑到没法儿出声的蕾姆一样，昴大声地呼喊着消失在天空那头的缇雅的名字。

然而，缇雅却没有回头。也没有停下。

她的身影就那样被风挟卷着，升得越来越高，最终看不到了。

「————」

那吹拂着庭院，屋子，以及昴他们的风悄然停了。这也表明缇雅已经完全彻底地远离了他们，这片区域已经在她的影响范围之外了。

「该死……！这蠢货！」

「昴、君……」

「我懂的！蕾姆，我理解你的心情。可是……」

想要把缇雅追回来。蕾姆的这心情，昴比谁都清楚。

然而，此刻有一件比什么都要重要的头等大事儿。必须得立刻，把蕾姆给送到诊所去。

「——啊，呜」

刚意识到这一点，昴就见蕾姆的脸上划过一丝剧痛带来的痛苦表情。她已经没法儿出声了，那不断侵袭着她的身躯的分娩的痛楚让她不停地喘息着。昴慌忙双手把蕾姆抱了起来。

「阿赫！拜托你了！」

「没问题，就交给我吧」

昴的话实在是太笼统了，但赫鲁贝尔一句话也没反驳立刻点了头，身形一晃就如同影子一般消失在了空气里。

把蕾姆送去诊所之前，必须得先告知老术师这回事儿。除此之外，昴想拜托赫鲁贝尔的事儿几乎数不过来。

「蕾姆，我这就送你去诊所。你就放心地把两条命一起托付给我吧」

「————」

见到怀里的蕾姆用力地点了点头，昴奔向门外。

夜幕即将降临，那淡青与橙红交织在一起的天空之下，昴抱着身怀六甲的妻子拼命地向前奔跑。

此时此刻、眼下、昴的脑袋里心里全都是蕾姆，他一刻不停地向着诊所的方向飞奔着。

——但同时，他自己心里也多多少少意识到了。这又是，另一种形式的逃跑了。

** 幕间 『忌日』

——发现了那个少女的一瞬间，涌上心头的是难以抑制的怒焰。

在复仇者踏上这条复仇之路之前，她住在『离群者』聚集的村落里。

鬼族可以说是一个稀有的种族了。虽说外界传言都是说为数不多的鬼族同胞会一起找一块地方作为他们的隐居地，在那里掩人耳目地繁衍生息。但她不是这样。刚生下来就只有母女二人相依为命，母亲亡故后她就只得一人茕茕孑立。

而就是这样的身世下，她历尽千辛万苦漂泊而至的地方，就是这『离群者』们聚集在一起而成的村落。

住在这里的往往是身不由己的亚人，犯下罪过而离开家乡的人，正派之人并不那么多。也正因此，充其量不过是背负着鬼族这个身份的她，也没有受到任何排斥，顺利地被大家悦纳成为了村里的一员，这才活了下来。

由于除了母亲之外还从来没有同其他人一起生活过，一开始那会儿，对她而言在村里的生活可谓是不知所措。所幸，尽管村子里的人绝不可能全都是良善之人，但家家都有一本难念的经，每个人都有各自的苦恼。此外，也没有故意对她冷眼相看的人。

日子就这样一天天过去，不知何时，她也交到了知己。同时，最初的为难和困惑都解决了，每天的作息安排也都渐渐固定下来，日子尽管平淡似水却安稳静好，她也打心眼里享受这样的时光。

她心里自以为是地断定，这便是所谓的幸福了。她从来没见过幸福的真实模样，所以也有可能是她一厢情愿的误解。但没关系，这就已经够了。

——而就是在她笃定地这般想着的时候，这一切都被血色的火焰给吞噬殆尽了。

已然再熟悉不过的村子陷入一片火海，被残酷的火舌席卷，顷刻间就灰飞烟灭。

平日里总是会热情打招呼的邻居、还刚开始学习如何种植庄稼的年轻人、曾为了自己的身世唏嘘不已的善良老人、昨天才刚刚说上第一句话的女孩子、最近格外喜欢找自己讲话的男人，而这些人、须臾之间都化作了灰烬。

她之所以能幸存下来，也只是因为运气好罢了。

可是，这真的能算作运气好吗。不正是因为运气最差了，才又一次落得这只剩一人苟延残喘的境地的吗？

她亮出了头上的角，解放了禁忌的力量。全身上下的魔力一瞬间沸腾，抱着势必要让那些放火烧了村子的一伙人斩尽杀绝的决心，她疯狂地发动了进攻。然而寡不敌众，这也成了以卵击石。

招架不住人多势众，她也被那群人的火焰给包围了。火舌舔舐着她的身体，带来阵阵剧痛和绝望，她不禁大喊出声，却立刻听到了尖锐刺耳的嘲笑，最后的自尊心也被击得粉碎。

「这倒是挺不赖的嘛。这小娘们的眼神倒是叫人欣赏啊」

尖利的声音贴着耳边响起。

那声音的主人站到她身旁，把不知名的可怖的玩意儿对着瘫倒在地的她释放出来。就在那时，她全身上下都起了排斥反应，不仅仅是肉体，甚至是灵魂。她发出支离破碎的惨叫，却没人会去在意。有什么东西从耳朵一气滑进了身体里。不紧不慢地，开始在她体内攻城略地。

「任务完成！来说说看，你喜欢我哪～里呢？」

奇怪，太奇怪了。一个疯女人的声音在耳朵里面嗡嗡作响，占据了整个大脑，久久不曾消失。

那声音一直没有停止，甚至她以为自己的脑袋要出问题了，就在这恐怖的苦苦煎熬中不知过了多久，就在那声音总算突兀地消失掉之际，她才发现，村落也好大火也好，还有那群家伙，一切都消失得无影无踪了。

尽管如此，她发誓要追寻到那群家伙的行踪，她的鼻子一刻也不曾放松。那被灌进她耳朵里的不明物，那贯穿了灵魂的猛烈冲击，也成了她嗅出仇人踪迹的线索。

「——我要，复仇」

看到眼前已然一片狼藉的村子，她在心里默默立了誓，成为了一个复仇者。

而成了复仇者，就要尽到复仇者的本分。为此，她需要足够强大的力量。

为了获得这力量，她不择手段，哪怕是拼上性命也在所不惜。同复仇者一样，那些几近疯狂的人们聚集到一起，偷偷潜入了大精灵的地盘。

——她渴求那能杀了那群仇敌的力量，那替天行道的力量，那斩尽杀绝的力量。

迎面袭来的风凌厉得宛如刀刃，同行者都一个个溅出团团血雾。而把他们的残骸当作盾牌，复仇者顽强地不断深入。一个盾牌没用了，就再换一具新的尸体顶上。她机械般地重复着这个动作。

不知何时，复仇者仿若听到自己耳边的风声俨然变得如同挽歌一般。

大精灵的家就在洞穴的最深处。不知为何，也就是从最深处呼啸而来的风，再加上洞窟这个大自然的造化，使得耳边奏起了一支像是在狠命剜心的哀歌。

复仇者为这风的歌声深深打动，像着了魔似的不停地向着更深处前进。

她渴望着力量。渴望着继续把风之歌听下去。这个洞窟里，有复仇者想要的一切。

终于跌跌撞撞地抵达了最深处之际，复仇者听到了这样一个声音。

「——我想要杀掉这世间的一切」

——她还记得自己当时是这样回答的，我也是。

2

「杀。杀。杀。杀。杀」

那不断灌入身体里的力量，没完没了地向复仇者教唆着这样的意念。

这原本是叫人心悸的，是对死亡的疯狂渴望、是杀意的奔涌，是毁灭的冲动——然而，这却正好同复仇者的心引起了共鸣，甚至在她听来，这就像歌声一般曼妙。

复仇者大喜过望，为了复仇开始纵情地施展起这力量来。

那些仇人一旦撞上了她嗅觉的网，她就会一个个地把他们给抹消掉，一个也不放过。就连碎肢残骸也绝不会留下。这帮家伙就连安葬在墓地的资格也没有，他们就该连一根头发也不剩下、彻彻底底地消失在这世界上。

就这样，复仇者不停地寻得目标，将其抹杀掉，不久后便来到了这个大城市。

夜色笼罩下，追赶着那强烈地刺激着嗅觉的『残香』飞驰过一条条街道，复仇者的脸上甚至浮现出了发狂一般狰狞的笑意。目标近了，更近了，就在不远处了。

这是迄今为止最大的目标。又或者说，这个才是复仇者真正的复仇对象——这该不会正是当时那冷冰冰的嘲笑声的主人吧？她的心剧烈地鼓动着。

乌黑的风吹起来了。但凡感受到一丁点儿这气息的人们都不由得心生恐惧退避三舍。更不必说这风的矛头所指的对象了。多想看到自己的仇人突然停下脚步、为这恐惧感吓破了胆的样子啊。复仇者的内心盈满了期待。

「————」

那个散发出浓烈残香、甚至叫她不禁扭曲了面容的仇敌总算出现在了她的面前。她的目光立刻扫向对方的脸，可惜的是这张脸她完全没有印象。不过也没关系。她要杀了对方的决心是不可能动摇的。

这样想着，复仇者把杀意全倾注在风中，正要给对方致命的一击——

「————」

她的视线突然停留在了就依偎在仇敌身旁的那个女人身上。

不知为何，复仇者一眼就看出来了，那是同自己流着相同的血的族人。

只见那女人就像要护住身旁的人一般站到了自己面前，那一瞬，复仇者不由得怔住了。很快回过神来，她立即被浓烈而漆黑的愤怒腐蚀了心神。

这女人在做什么呢。那个男人难道不是该遭天谴的仇敌吗。

本应同自己处于相同立场，流着相同的血，隶属同一种族的她，不对这男人复仇，反倒和他搅和在了一起。

「——你到底在做什么呢」

她怒不可遏地问出了声。

不是我要杀了你，而是质问。

然而，那女人并没有投向复仇者，反倒是选择了保护畏畏缩缩的仇敌。她的这般行动已经很明显地给出了答案。

这个把自己的邻居，村里的年轻人，善良的老人，初识的女孩儿。——甚至自己暗地里期许着、能拥有共同未来的那个男人都给残忍地杀害了的仇敌。

那女人要保护这样一个将自己的幸福轻易地付之一炬的仇敌吗。她流着和自己相同的血，却还能看起来很幸福似的爱着这个同鬼族不共戴天的男人。

那么——

「——去死」

——杀了这个女人，也是为了坚定自己的信念。

3

而现在，复仇者品尝了接连两次失败的滋味儿，终于等来了这第三次报仇的权利。

「该、死……」

从嘴里漏出一声痛苦的声音，被猛地撞在墙上继而瘫倒在地的，是身着白衣装束的女子。

她从牙缝里挤出来的声音听上去相当耳熟。当然了。这声音直到现在，也在一刻不停地在复仇者的意识里下达着嗜血的指令。这两个声音，是一模一样的。

声音，的确是一样的。但那女子的却显得太过脆弱。两者的意志相去甚远，没法儿相融。所以她才会本能地排斥。

这和复仇者所希冀的力量完全不是一回事儿。是异端，是脆弱过头的异端。

如若这个异端甘愿俯首称臣谋求融为一体倒也罢了，可这女子刚刚竟然叫嚣着让自己臣服于她。

「——去死」

因此，复仇者毫不留情地让她见识了自己的力量。复仇者要将她痛击到体无完肤，再将她生命的核心，也就是依附的载体给夺过来。

「啊、唔、啊啊……」

被自己一把抓住前襟给提了起来，女子发出了痛苦的呻吟。她挣扎着想要挣脱，复仇者却无动于衷。就这样，女子的身子渐渐化作了光粒，被复仇者给吸了过去。

原本，这女子的存在也是复仇者要汲取到自己体内的力量的一部分。现在复仇者终于能将这一度分裂出去的力量给制伏，将这力量完完全全地变成自己的东西了。

「——姆」

就在女子彻底消失的前一秒，她像是喊了一声不知是谁人的名字。然而，这一声呼唤却丝毫未曾传到复仇者的耳边，被那肆虐的风给裹挟着、消失在了空气里。

解决掉了碍事的人，力量也总算完整了。如今，再也没有什么欠缺的了。

「——去死」

接下来，就只要完成复仇的使命就行了。将复仇者的复仇，进行到底。用那个女人的死。

「——去死」

错的是那个女人。是那个包庇了本应向其复仇的仇敌的女人不对。

那全身散发着魔女残香的仇敌，和可憎的同胞。

无论是哪个，都要杀。无论是哪个，都该死。她要杀了他们，杀了他们，杀了他们。

只有杀戮，才是对那失去的一切最好的慰藉。只有以血，才能赎罪。

——这不是憎恨，而是使命。正因为这使命感在身，那个女人，必须得死！

** 第五章 『产月』

老术师看到被搬进治疗院的蕾姆，脸色摆得很难看。

「哪有间隔这么短的，这个状态是怎么搞的！」

「额，呜」

老术师把手放在蕾姆的腹部上，说疼痛间隔太短了。昴对此不明所以，于是老术师咂了咂舌。

「一般怀孕的疼痛间隔很长，间隔变短了就是生产的前兆呀。可你老婆的情况很奇怪，喂！去把婆婆叫过来！」

术师突然打断自己的说明，喊助手让他叫来产婆。之后术师慌忙地走出房间，紧张感充斥着整个房间。

「昴……君」

「蕾姆！蕾姆，没事……那肯定没事。可恶，啊，我就在这里呢」

昴一边握着蕾姆的手，一边对自己说不出像样的话感到生气。蕾姆紧紧地握着昴的手，紧到有些疼，但即使如此也丝毫不及蕾姆所感受的疼痛。

如果捏烂自己的手可以缓解的话，昴真心情愿地想这么做。

「不会做……这种事的，这可是……夫君的手……」

蕾姆看破了昴的内心，露出了淡淡的笑容。看着这明显的逞强，昴更加难受了。

应该是我来让蕾姆感到心安，可是为什么是蕾姆在照顾我。

「缇雅，大人……」

「——蕾姆，先不用想缇雅的事情，只用想自己的事情就行了。」

「……缇雅大人，说过这样的话吧，现在肚子里的小孩要生下来，是因为蕾姆心中的心结解开了。」

「的确……说过」

听完蕾姆断断续续的话，昴回想起缇雅临别前的言语。

蕾姆和缇雅之间约定的期限——孩子生下来之前，缇雅不会对蕾姆做出什么，安静地等待孩子的出生。

「约定……没有意义了，孩子……终于要生了……」

「虽然可能难以置信，这只是巧合。只是时间偶然重叠了，你不用担心。」

精神状态可能会影响孕情，可是在出产的时候还有影响是不太可能的。的确，蕾姆的产期是在老术师预期之后。

然而，不可能仅依靠念头抑制住要诞生的婴儿。

「当然、担心了。那是因为……蕾姆……」

「蕾姆什么？怎么了，说出来吧，今天你所有的话我都想听。」

「——蕾姆，很怕……孩子生下来。」

蕾姆握紧昴的手，眼中闪着泪光说道。

昴听到后咽了口气，蕾姆闭上了眼睛，泪珠缓缓流了下来。

「生下小孩，昴君能够开心，蕾姆也很开心。真的，真的很开心。可是，也很害怕，因为……」

「——」

「因为蕾姆，在自己小的时候，没能当一个好孩子。不能回应父母，还有村子里的人的期待……蕾姆，不是一个好孩子……」

泪水不断地流下来，昴没能拂去泪痕，被闪闪发光的泪珠夺去了视线。

没能做一个好孩子，这份后悔，令蕾姆心中充满了不安。

「这样子的蕾姆，有了小孩……心里完全没有底。女儿，还有妹妹！我都没能做好，母亲肯定也不行……」

「不想和缇雅大人分开真的是事实。如果没有期限的话，想在那间屋子一直待着……但是，不是这样的……」

蕾姆转过头，吐出了隐藏许久的心里话，如同在惩罚自己。

「蕾姆很害怕，成为母亲。害怕见到孩子。其实我一直都在担心，自己能不能成为一个合格的母亲！」

「——」

「每次蕾姆……都会让周围的人很失望。」

蕾姆呼吸逐渐加重，用另一只手拭去泪水，遮住眼睛。

蕾姆悲痛的哭诉如同尖刺般刺穿了昴的内心。这份哭诉太过突然、强烈而又悲伤。

「——」

昴咽下口水，拼命想下句话该怎么说。

不知道该说什么，很抱歉让你感到不安？对不起没能注意到你的悲伤？斥责她不能看低自己？都不对。

蕾姆一定是抱着会被自己失望、厌恶的觉悟说出了这些话，坦白地说出了一切。

对，蕾姆说过，自己总是让周围的人失望。这告白也一定是做好了这份打算。

以及，自己听完这个告白之后，是否真的失望了。

「蕾姆。」

「……」

非常短暂地，蕾姆颤动了一下，一定是非常害怕、非常不安，对昴将要说的话感到不安。

昴于是紧握着蕾姆的手，另一只手抚摸着她的头。

「你的感受，我也很清楚……真的，很清楚。」

「昴、君……」

昴的声音很温柔，蕾姆像是被惊到了，缓缓将手抬起。

「我啊……其实我更过分。我也没能做个好孩子，没脸见我的父亲、母亲。」

「——」

「我父母超级好，真的是世界第一的爸妈，彼此恩爱，对我也特别好。」

就像蕾姆刚才那样，昴也开始诉说自己的故事。

跟蕾姆一起生活了一年半，来到这个异世界生活了不到两年，过了这么长时间，昴这是第一次向别人诉说起自己的过去。

对昴来说，这与他最不愿提及的东西有关，对昴来说这是他最为美丽、遥远的回忆，即便是稍稍触碰都很害怕。

温柔、严格的双亲，给予了昴喜悦、悲伤、愤怒以及各种施舍，而昴却什么也回报不了，实在是太可耻了。

被那么好的父母所养育，然而还是成为不了一个好儿子，这样的菜月昴，如何才能为人父母。

「但是，我的这一面不能被你看到。是我……是我把你带到这里来的，你是、被我带来的。我必须用尽全力换取你的幸福，我必须这样……」

所以，将这种不安埋在心里，拼命等待这一天的到来。努力工作、努力支撑蕾姆、努力做个好丈夫。

坚信如果能够成为好丈夫的话，接下来就能成为一名好父亲。

「不过，问题不是这么简单，那也理所当然的，毕竟是要成为人父，用这种逻辑肯定行不通。所以，我现在也……」

之前没能注意到蕾姆的不安，开始在这个关键时刻如同忏悔一般吐露出了自己的心声。

昴和蕾姆都意识到了自己的不完全，因此都对自己能否成为即将诞生的婴儿的父母，能否承担养育的责任，而感到忧虑。

更有甚者，他们对表露出这个想法也感到担忧，不过——

「昴君……后悔，吗？」

听到昴的告白，蕾姆率先打破了沉默，昴抬起头，望着蕾姆湿润的眼睛。

淡蓝色的瞳孔看着昴，在绝望与悲痛之间摇摆，鼓起的腹部里有两人的小孩，阵痛已经开始，诞生已近在眼前。

这种情况下，进行着这样的告白——这个孩子，是两人所希望生下来的吗。

「——」

昴读懂了蕾姆眼神中的哭诉，擦干了眼泪。

是自己说的不够，后悔的不只是说得不够，行动力也太差，从眼前的问题逃脱，一直在逃向最轻松最不辛苦的地方，逃着逃着就来到了这里。

从父母那里逃离、从现实逃离、从异世界的洗礼逃离、从立下的誓言逃离、从重要的东西逃离、从对失去的恐惧逃离，最后来到了这里。

一系列的逃亡之后，是不是已经一无所有了？

「不对，蕾姆。我不后悔，我……我被救赎了」

「昴君……」

「我一直在逃避，什么东西都背弃掉，把你带走逃到这里……但是，我知道有小孩子的时候，我好高兴，那个时候，我被救赎了，我背后舍弃了太多，但在我面前得到的，就是蕾姆和我们的孩子」

不安是有的，没有虚言。无颜面对父母的昴，一直对能否成为人父感到不安。现在也是，那样的感情一直没有消失。这种感觉，可能永远都会残留在心里。

可是，昴也知道，世界上最称职的父母是什么样子。

「我是一个不好的孩子，没能好好地做他们的儿子。但是，我的父母是世界第一。我同时知道世界第一好的父母和世界第一坏的孩子。就是因为两个都知道，所以不管发生什么，我一定能爱我的孩子」

「——」

「我是个很烂的小孩，可我的父母亲依然爱着我。我知道，我一直知道这点——所以，我能爱自己的孩子，爱我的家」

脑海里泛起了二人的笑容——父母的笑容，昴露出了微笑。挺起胸膛，昴对最高模范的父母自豪至极。

被世界第一的父母，最模范的父母，养育了十七年啊。

「——」

对用笑容说出这些的昴，蕾姆说不出话来。湿润的眼眶瞪得很大，通红的面颊越发红，她的表情逐渐发生变化。

「——真是鬼上身了呢」

一个非常令人怀念的短语，蕾姆露出了与那时相同的笑容。

对这个笑容，昴在想自己是否能像当时一样、用同样的笑容答应了呢。

在这时——

「产婆来了，要准备生产了，你到外面去，祈祷吧」

老术师回到了房间，旁边有一名中年女性。昴想说时机也太好了，可老术师还是摆着平时的厌烦脸不知在想什么。

不管如何，到时间了，昴回过头看蕾姆，重新抓住她的手。

「蕾姆，我想说的都说了，要相信我」

「……蕾姆一直都相信你」

「啊啊，的确是这样」

助手在不断地搬进一些器具，产婆对此正在下指示，老术师用下巴对着外头，示意昴出去。

「不能在这看着吗」

「男的在这有什么用，产婆和助手都来了，我也只是以防万一在这里，但也跟装饰品没差多少」

产婆嗤之以鼻，在暗示只要没自己事就行。这种不和气的态度，现在觉得很可靠。

「医生，蕾姆就靠你了」

「跟产婆说去」

老术师挥一挥手，露出苦笑。之后，昴终于放开蕾姆的手。

「蕾姆，我等你——我的老婆，还有孩子都交给你了」

「好，交给昴君的蕾姆吧……缇雅小姐的事情」

「我知道」

对着蕾姆微笑着说出的话，昴点头回应，让她不要再说下去。看到这后，蕾姆满意地闭上了眼睛，呼吸声逐渐变成喘气声。

只属于蕾姆的战斗即将开始。

「丈夫请出去！」

被产婆呵斥，昴没有什么办法只能出去，在出去之前听到了蕾姆的哀嚎，她漫长的战斗要开始了。

昴也想在病房外面守望她的战斗——

「——阿昴」

昴到通道后，赫鲁贝尔找到了他。他通知了医院蕾姆要生，并帮忙打理了很多事务。

然后，也是昴和蕾姆以外唯一一个知晓情况的人。

「蕾姆酱呢？」

「现在正在生，他们说男的碍事就让我出来了……这种时候我总是没什么用」

「我也是呀。蕾姆的任务是蕾姆的，我们要把我们要做的做好……阿昴也知道吧？」

赫鲁贝尔苦笑着说，昴也点头回应。

从赫鲁贝尔的表情，或是从刚刚发生的事情都能看出发生了什么。

「窃取了缇雅的能力的家伙，会到这街里来杀我，缇雅她……」

「这个」

对昴的问题，赫鲁贝尔从袖子里拿出了一样东西。这东西是用黑色的丝编制而成，似乎本来是连成一个环围在手臂上用的。

「这个手带，不是赫鲁贝尔你交给缇雅的吗」

「这个手带是被称作黑结的一种咒具，制作方法虽然多种多样，但是一种两个为一对的道具，如果佩戴者发生了什么事情的话……」

赫鲁贝尔摇了摇黑结，这个结中途断开了。

「也就是说缇雅……」

「挑战之后被反杀了，胜算很小想必本人也知道，事后处理交给我之后就走了，真是个乱来的家伙」

将断开的黑结揣进怀里，他露出牙齿哈哈一笑。这笑容有些寂寞，可能这就是赫鲁贝尔在以自己的方式悼念缇雅吧

然后他拿出烟袋，点上火。

「我会做缇雅交代的事，阿昴——」

「我知道」

昴回答道，就像答应蕾姆那样打断赫鲁贝尔的话。

眼睛中燃烧着决意与觉悟，昴说道。

「——逃避到此为止了」

2

「那个小孩……敌人，就这么称呼吧。那敌人，据点在街的外头，虽然勉强碰过一次头，这家伙不得了，半吊子的实力去触碰只会增加尸体」

「碰头……是战斗的意思吗，赫鲁贝尔你跟他干了一架吗？」

「那我肯定不可能毫发无伤啊，不是我，是我的部下，用你的话说，就是雇了忍者集团」

「果然有忍者集团，你果然是头头，你之前不是说没有的吗！」

「忍者能透露自己的消息吗？嘛，这时候就算了吧」

赫鲁贝尔抵住紧咬不放的昴的额头，让他冷静下来。

的确，在这里问这个卡拉拉奇的忍者村在哪里没有益处，重要的是赫鲁贝尔所收集到的情报和解决方法。

「看起来与缇雅酱一模一样，不过穿的是黑色衣服很好辨认。使用拖延战术还能阻止一会，但是撑不了很久，怎么办？」

「阿赫有什么想法吗？」

「最简单的方法是——把阿昴绑到街外头，达成对方的目的」

赫鲁贝尔伸出指头，说出了最干脆也最确实的手段。在昴说出话之前，他自己收回手指。

「不过这不可能，不可能让朋友送死，也不能让蕾姆酱年纪轻轻当寡妇，生下来的孩子没有父亲也太可怜了。而且，也跟缇雅酱的约定相悖」

「还挺讲情义的嘛，作为一个游手好闲者」

「游玩都是要遵循规则的，作为『永远的游手好闲者』的话，更加是这样了」

赫鲁贝尔怂了耸肩，回答了昴的玩笑话。这段互动之后，昴绷紧的神经稍微松弛了下来，至少不需要当人肉贡品了。

「再进一步说吧——关于塞蕾丝缇雅，你知道多少？」

「大体就是在家里说的那样。四大精灵中的一只，杀人的精灵，被称为『杀人魔』或者是『最美丽的死神』，据点在卡拉拉奇的西部，会消灭闯入据点的探险者……然后是，有一个古老的歌谣吧」

「古老的、歌谣？」

「内容我也不知道，不过知道的人是知道的，好像是，什么来着……摇篮曲，那样的」

「风之歌？风之摇篮曲」

「啊，就是这个。阿昴，你知道的真多，而且还不是卡拉拉奇人」

「很正常吧，你以为我跟什么人一起工作啊」

赫鲁贝尔表露钦佩之情，昴回应道，内心里十分感谢在玛格洁宅邸一同工作的妇人，教会了昴这个准父亲家务事还有关于摇篮曲的事情，在这之中便有一首被称作风之摇篮曲。

那个摇篮曲讲述了古时候的人们击退某个巨大的怪兽。

「阿赫，你说过拖延战术吧，大概可以拖延多久？」

「……想要有牺牲的话就是半天，没有牺牲的话6个小时」

赫鲁贝尔犹豫了一瞬间，随即又盯着昴的眼睛说道。因为此时昴黑色的眼眸里流露着无比的决心。

考虑到风之摇篮曲，还有在此之前的敌人和缇雅的事情，有了一个想法。

这就是——

「——余下的一生，只能抱着全用来报恩的觉悟来求别人！」

3

挥动着手臂，卷起风，可以切开一切的杀戮之风。

「——去死」

一声令下，风云变换，紧张的攻防在毫厘之间，攻击吞噬着周围所有的空间。

一阵闪光过后，缠绕的风将钢铁弹开，投掷物从四面八方袭来。真烦人。风会弹开钢铁，增加攻速毫无意义。

「——去死」

向投来飞镖的人放出一阵风，没有打击感，这是以风作为武器的缺陷，放出的风如同獠牙一般席卷而去，有否击中只能通过肉眼观察。

但是，现在是夜晚，包围的敌人是擅长隐匿于黑暗的忍者。

「——去死」

如同被释放的风，不知道是否捕捉到了黑影，即使击中了也不会有哀嚎，死之前也不会吭声，可恨至极。

「杀掉杀掉杀掉杀掉杀掉杀掉！」

脑海中有声音，我知道，我也是相同的心情，想杀掉一切。

但在这之前，我必须杀掉该死的敌人。虽然鼻子能察觉那个的存在，能知道他在哪里，可是黑色的影子在妨碍着，可恶、可恶，我要杀掉他。

「——」

突然，黑色的影子聚集在一起，在观察发生了什么之时，周围散发的气息突然消失了，如同风一般。

撤退了，然而情况没有发生变化，突然撤退了。发生了什么？本能告诉自己要扑向魔女的气息，可是如果是陷阱的话，这么照做简直是愚昧透顶。

心中有两股不同的想法碰撞在一起。想要杀掉、必须要谨慎地杀掉。迟迟不能得出结论——

「——！」

下个瞬间，感觉到了无法忽视的恶臭。

睁开眼睛，顺着风向仔细分析这个臭味，即使拒绝也会漫入鼻腔的这股恶臭，毫无疑问是魔女的残香，可憎的瘴气——

闻到这突然变浓的味道，理性与本能在颤抖，脚底下的大地爆裂开来。

『杀掉！杀掉！杀掉！杀掉！杀掉！杀掉！杀掉！』

「——去死去死去死去死去死去死去死去死！」

脑海中的声音与自己的声音重叠，一跃而起追逐目标，跃入街道，踏碎瓦砾，翻越建筑，不断往里，终于——

「——虽然你的脸狰狞成这个样子」

四肢伏在地上，抬起头。面前是一位身着蓝色装束的男子，散发着刺鼻的、令人窒息的恶臭。

以前也见过这张脸，那个时候只能在恐惧中颤抖，任人宰割，现在却挑衅般地扬起嘴角。

「——笑起来挺可爱啊。仅次于我的老婆和孩子」

「——去死！！」

杀意朝那丑陋的笑容席卷而去，风径直袭向站立的男子，将其存在与恶臭从这世上抹除，本应该是如此的。

「不好意思，不会让你得逞的」

「——」

随着一声轻浮的声音，释放的风全都消散而去。从黑暗中释放的暗器将风逐一击破，毫发无伤的男子耸了耸肩，仿佛是自己的功劳一般。

「——去死啊！」

无法原谅，增加风量，任由自己的杀意膨胀，肆力挥去。

一瞬间爆风狂卷，大地崩塌成一个圆，然而那个男子已不在其中，那个妨碍的亚人也消失了。

向上看去，屋檐上亚人架着男子准备逃跑。

——怎会让你跑，杀掉，怎么会让你跑走，我要杀掉你。

「——去死！」

在黎明前的街道上，追着逃跑的恶臭与亚人，卷起风，乘上风，化为风——

「——！」

在风中，恶臭当中又混杂着其他的味道，这激起了神经，这是人的味道，还有很多，脚下是一个大规模建筑，男子和亚人跑进了其中。人的气息，这与之前的恶臭又是不同的恶臭。

进去之时，犹豫了许久，可是那个男的就在里面——

「——我可以死亡回」

「——！！」

在没能听清的话语之后，恶臭爆发性的浓烈了起来，本能狂躁地无法抑制，警戒心与理性已然荡然无存，向上猛地跃起，发现了正在庭中的亚人。

瞄准亚人与肩上的男子，发射出风，从四面八方吹起无法回避的攻击。

「别恨我，阿昴！」

知道无法躲避之后，在风刃完全闭锁之前亚人将男子从缝隙之间奋力抛出，男子逃过一劫，可亚人并非如此。

「——去死！」

将张开的五指并拢，残酷地将关在中间的亚人撕裂。亚人死了，在杀死一个人而喜悦的同时，仍然清楚还有事没有做。

将那个人五马分尸，抓住那个人的残骸放在那个女人面前，让那个投靠了该死的敌人，还生下孩子的女人知道什么是绝望。

这就是复仇，这就是报应。这就是血债血还。

——这是对如此侥幸的你的复仇！

「——去」

「就是现在！」

憎恶与欢喜交织在一起，在喊出「死」之前恶臭之源发出了叫唤。

「嘿——呀！」

在这瞬间，从所有方向上扔来了一样东西，在余光里瞥到的是类似于布一般的物质，无论如何，某种不详的东西被扔过来了。

「——」

开始思考，在我眼前有恶臭之源，在我眼前，可以杀掉，然而，优先杀掉他的话，就会中招，现在的话还来得及，唤起风，乘上去，可以令敌人的策略完全失效。

是的，不需要焦急，选择最有把握的选项，不需要中敌人的策略。

「杀掉杀掉杀掉杀掉杀掉杀掉」

抑制住脑海里的渴望，就能逃脱。

在这个瞬间遵从自己的意志。这样的话，这份渴望就能长久——

「——想要杀死。可是，不行」

「——！？」

「因为我，可不想被蕾姆讨厌」

与脑海中的声音相同，潜伏在自己心中的某人笑着说。

手脚如同冻僵一般，无法动弹，无法逃跑，无法杀人。

「去死————！」

「啊啊，这种叫声，真是爽」

在这个残暴的声音之后，无法躲避的某种东西命中了全身。这是湿的布，没有攻击力，却缠绕了好几圈。

不，这不是水。刺鼻的味道，这是——

「——！！——！！——！！」

头盖骨如同被敲碎一般的哀嚎，排斥反应搅拌着大脑，本应封印在容器里的东西暴走了，无法忍受一般，迸发而去。

「——」

头痛欲裂。如同从内部搅拌头盖骨，超越了想象的疼痛，从未尝到过，也从没有想象过，不想死、不想、不想、不想、不想！。

「——啊」

剥落了，构成身体的组成解体了，如同溶解一般，失去了力量。

身长缩小，发色发生了变化，丑陋得不如一个村姑，实力也下降得不如那个半吊子的鬼族。

然后，连复仇的能力也失去了，被杀意抛弃而去。

「我……」

「——饶恕我」

听见了明明已经被撕裂的亚人的声音，奋力拨开布，一个黑影进入了视线中。

刀光一闪而过，穿过了胸膛。

——这就是结局。

4

于宅邸的庭院之中俯视着倒下的少女。

茶色双马尾，配上一张虽显平凡，却又不失可爱的脸庞。不过她身上日晒痕迹严重，脸色差到奄奄一息的地步，将她的这份可爱浪费殆尽。

「她受的是致命伤，还被施了让她无法逃离的咒术。——这下就，真的结束了」

俯视着少女的昴身边，将衣物褪去、赤裸上身的赫鲁贝尔正站在那儿。他的话令昴眉头紧蹙，「咒术？」昴问道。

「之前也跟你说过的吧？我是咒术方面的专家……我是用咒术来决胜负的。我在手里剑中溶进了我的头发和指甲之类的东西，所以只要被武器擦到就会被诅咒」

「什么啊那是，超危险的啊，而且这种事可以说给我听吗？」

「没所谓啦没所谓啦。要是被人知道了的话，只要连同阿昴一起消灭掉就好」

「这相当有所谓吧」

赫鲁贝尔抱持着很轻松的态度，可昴却掩饰不住因他的杀人手腕而感到的战栗。

咒术，是被称为魔法的亚种的、这个世界的法术中的一种。昴过去也曾经挨过咒术，它是在夺取对方性命方面进行了特化的法术，不过与之相对地，咒术有着施术者必须与对象进行接触的规则。这就是咒术相当难以使用的原因，不过赫鲁贝尔通过混入了自己的一部分的武器解决了这个问题。

「最初遇到她的那一夜，我曾以一发手里剑刺中了她。那之后她的动作会变得迟缓就是咒术起效了。即便依靠大精灵的力量压制住了，也是没法阻止诅咒的进展的」

「然后，她就在临死之前跑来杀我了吗？」

「这或许就是她急于来杀你的理由吧。不过事实如何我就不清楚了」

耸了耸肩后，赫鲁贝尔从护腰中拿出烟袋叼在了嘴上。他似乎不准备插手接下来要发生的事。这是种温柔的同时，也是一种严苛。

做了个深呼吸后，昴望向了行将就木的少女。

「————」

是注意到他的气息了吗，少女慢慢撑起了眼脸。那是淡蓝色的眼瞳。这共通点愈发刺激了昴的罪恶感。不过，他却无法阻止。

「你……搞错了，才会盯上我的。我，和魔女教没有关系。不过我知道，就算我这么说也是没法阻止你的」

「————」

「我不会，请求你原谅我的。我很想那样说，但说了也毫无意义。你是不可能会不憎恨我的，所以你就恨我吧。不过，我希望你只恨我一个人」

蕾姆自不必说，昴希望她也不要去憎恨他和蕾姆将要出生的孩子、赫鲁贝尔以及其他帮助了他们的人。

考虑在这里抓住她、制定计划并付诸实现的是菜月昴。

她希望杀掉的、直到最后都憎恶不已的对象也是菜月昴。

「我的名字是菜月昴。这，就是你想要杀掉的人的名字」

「——---」

「抱歉，对不起。明明说了就算你不原谅我也无妨的……可我还是道了歉，抱歉」

这种心情在说话间涌了上来，抬高声音的同时，昴向她道了歉。

让将死的少女不留下遗憾，尽可能也不想听到她吐露憎恶的话语，能在这样的状态下夺去她的生命是理想的。

不过这样的愿望并没有实现，将死亡看在眼里的昴无法抑制地懦弱了起来。

「死」非常可怕。「死」是无药可救的。昴很清楚这一点。

正因为昴比这世上任何一个人都要了解「死」，他才会觉得少女如此可悲。

「我们的孩子快要出世了。蕾姆她为此拼尽了全力。我将要成为父亲了。所以，我们不可能去死。抱歉，所以，我只能把你杀掉了」

这就只是单方面的辩解。若是关系对立到会发展为彼此厮杀的关系，两方之间就已经没有彼此理解的余地了。

昴的话语无法起到任何作用，无论是慰藉少女，还是博得她的理解。

昴的这番话语，令少女痛苦地暂时止住了呼吸。

「我……」

「————」

「我……好恨，那个，女人」

如同吐出鲜血一般，如同从地狱窥伺着天堂一般，少女以充满憎恶的声音说道。

昴很快便注意到了，少女的这句话所指的是蕾姆。注意是注意到了，可矛盾也随之产生了。她应该是追着魔女残留下的香气过来的。所以昴诱骗她的作战才得以成立。她的憎恶应该全部倾泻到昴的身上才对。

「那个女人……拥有着、一切……我、想要的、一切」

「这是……」

「和那个人、在一起，获得幸福的……明明、应该是我」

少女的眼中流出了泪水。她的眼眸已经没有在注视着昴或是这世界上的任何风景了。

少女在望着的，肯定是某个其他的地方的——幸福到足以驱使少女进行复仇、并为之燃尽生命的风景吧。

直到最后都紧抓着不放的，恐怕是对流着和自己相同的血，身处的境遇却和自己有着天壤之别的蕾姆的憎恶与嫉妒——不对，应该说是羡慕吧。

「你的名字是？」

「————」

「你的名字，叫什么？」

昴蹲下来，将脸靠近了她后问道。旁边的赫鲁贝尔打算阻止，不过被昴用手制止了。这个少女已经没有余力对接近她的昴做些什么了。

现在这一瞬间，少女的命脉都几近断绝，对着她最后的生命灯火，昴侧耳倾听。

「——e　ze」

「蕾...泽」

听出了她以蚊蝇之声告知自己的名字后，昴如此念了出来。这名字是否正确，她所剩的时间已经不足以让昴去确认了。

光从少女的瞳孔中消失了。羡慕着蕾姆、诅咒着命运，少女在这里停止了呼吸。

「——蕾泽」

昴不会忘记她的名字。少女她，蕾泽她所说过的话昴也不会忘记。正是牺牲了蕾泽，昴才守护住了自己、自己的家人，以及这样的生活。

而名为蕾泽的少女真心企盼着的到底是什么，这件事昴也绝对不会告诉别人。身为她憎恶的对象，昴要把这些带进坟墓里。

绝不会让蕾姆以及将要出生的孩子知道这些的。

「……结束了」

「是啊。虽然实在算不上是以能让人心情舒畅的形式就是了」

对于昴这混杂着叹息的话语，赫鲁贝尔吞云吐雾的同时回答道。这次作战自始至终都依仗了他的帮助。这一点就令昴对赫鲁贝尔低下了头。

「感谢大家认可了我的任性和没有确切把握的作战。帮大忙了」

「最后做决定的是我，她也如阿昴计划的那样落入了圈套之中，所以我也没什么好抱怨的。而且久违的替身术也成功施展了，干得很不错啊」

曾说过「自己并不擅长」的替身术在最后派上了用场。

在帮助昴从少女的最大火力中脱身后，赫鲁贝尔的全身都暴露在了狂风之中。——不过他通过替身术让非常古典的原木来代替他承受了攻击。

看向周围后便会发现，这里原本是利夫坦的宅邸——为了确保准备陷阱所需的宽阔场地，昴他们将宅邸借了过来。还不止这些，人手和金钱也借到了。

就如同在证明这一点一般，利夫坦·玛格洁正站在宅邸的走廊里。捋着胡子的同时，他对昴深深地点了点头，接着

「平安无事地实现了计划比什么都重要啊」

「真的给老爷你添麻烦了……」

「『文化学校』才刚开始运作。我还需要你靠着那份女子力去引导为数众多的女性呢。这是必要的投资。因为我很喜欢投资嘛」

不仅让抿嘴笑着的利夫坦提供了场地，还将对于这次作战来说不可或缺的『酒』的筹措拜托给了他。靠着猛商利夫坦的名号，他如字面意思般从整个城镇中将酒聚集了起来，并将其运到了宅邸里。

「摇篮曲的启发、拿酒很没辙的缇雅。以及她对料理酒的过度反应」

这些都与塞蕾丝缇雅不擅长应付酒水的推理紧密联系在了一起。从古时起便拥有强大力量的存在沉溺酒水而被驱逐，这样的传闻不绝于耳。

摇篮曲的内容也与之相近。如若这个世界真的遍布着足以匹敌神话的存在，那么将那些神话的内容付诸实际也肯定不会有错。

而实际上，被蕾泽俘获了的塞蕾丝缇雅在被丢了吸收了大量酒水的毛毯、全身都被淋上了酒之后确实冒了出来。

靠着利夫坦的财力与知名度，以及宅邸里妇人们口中的传说取得了胜利。另外还有为了让缇雅被淋上酒做准备而借来的人手——

「——克莱茵的中介」

「对我说要讨伐缇雅酱的话，我当然会过来啦。除我之外，还有很多人喜欢着那个孩子，呢」

身上穿着的不是围裙而是铠甲，克莱茵环抱着手臂说道。他，以及除他之外的大量非正式雇佣者都为了讨伐缇雅而聚集了过来。

如果作战失败的话，情况就会变为与拥有大精灵之力的存在进行总力战了。尽管一开始以这样的理由拒绝了，还是有许多人为了缇雅赶了过来。

「而且就算有个万一，我觉得赫鲁贝尔也会有办法解决的吧」

「那算啥，对我抱有的期待也太重了吧」

对着搔着蜥蜴面孔上的鼻子的克莱茵，赫鲁贝尔一副「饶了我吧」的样子摇了摇头。那副样子使令人轻松一笑的气氛在周围扩散了开来。

心中很苦闷，也已经看透了结局。不过，除了少女以外的牺牲者并没有出现，这对昴所考虑出的作战来说已经是最好的结果了。这是没有任何损失便得以收场的，最妥当的结果。

所以，接下来——

「——还剩下，最后的陷阱了啊」

昴抬起了头，赫鲁贝尔则抖掉了烟管上的烟灰。利夫坦扑通一声坐在了走廊里，克莱茵等人重新抄起了放下来的武器。

一阵风缓缓吹进了这充斥着临战姿态，警戒与紧张感的宅邸庭院之中。

乳白色的秀发，纯白的装束，抵达非人领域、经由神之手创造出的美貌。同时拥有着与外貌不符的粗野一面和孩子气的部分，意外地亲近人，还很爱哭。

是在场的所有人都了解的，完全与大精灵之类头衔不相符的少女。

「————」

被麇集而来的气息所压制，昴竭力克制住了自己腿软的感觉。

必须要逃离，昴如此下定了决心。现在必须要从她——缇雅的身边逃开。

——而这就意味着，昴也要告别那段热闹而喧闹的、幸福的日子了。

5

这是很久以前，很久很久以前，在世界还没有冒出魔女啦、龙什么的之前的事。

那时候的我，一直都自由自在。不被任何人打扰，讴歌着自由。

唤起风，让火烧得更旺，卷起水流，刨开土地，我随心所欲地生活着。

大家都肯定着我，并将各种事拜托给了自由自在地生活着的我。我的心情很好，而大家也非常有礼貌，于是我便听取了大家的请求。

唤起风，让火烧得更旺，卷起水流，刨开土地，我实现了大家的请求。

然后大家便十分开心。大家纷纷夸赞着我。大家都露出了笑容。

所以我的心情便变得更好了，我听取了大家的请求。虽说偶尔也会因贪恋自由而不去听取人们的愿望，不过大多数情况下，只要我没在睡觉就会把力量借给大家。

这段时间里，每当有什么事要拜托我，大家便会带各种各样的东西给我。

蔬菜和动物的肉，闪闪发光的石头，鲜艳靓丽的衣服，大家拿来的都是这类似乎很有『价值』的东西。

我的肚子并不会饿，对石头也没有兴趣，我还有着不需要布头遮盖的毛皮，所以大家拿来的东西并没有令我感到高兴。

不过带东西给我的心意是令我很开心的，于是我也鼓足了干劲。

唤起风，让火烧得更旺，卷起水流，刨开土地，这些都是我喜欢的事。

做自己喜欢的事就能让大家高兴。所以，我不断重复做着这些事。

不过，在这一过程中，大家拜托我的事情中的奇怪请求也增加了。

为了让我实现愿望，大家一直以来都让我按自己的喜好行事。明明之前都让我随意对待风、火、水和土的，现在的他们却开始对我提出要求了。

我喜欢自由，我喜欢随心所欲地生活。

不过我同时也很喜欢被大家夸奖，被大家宠溺。

所以没有办法，我只能实现大家的愿望了。在大家指示的地方，按大家所说地唤起风，让火烧得更旺，卷起水流，刨开土地。

不断这样做之后，大家再度高兴了起来。我心情很好，就允许了这些事。

自那之后，我按照大家的要求来实现他们愿望的情况变得越来越多。

在这时，就在这时。就在我习惯了按照大家的吩咐行事的时候。

这次拜托给我的事，就真的很是奇怪了。

不需要风。不需要水。也不需要土。我们想要的是火，大家如此说道。

我讨厌那样。我想要从风开始。风之外的事也想要做。我是自由的。从很久以前开始，我的自由是以风为起点的。

我不愿让这一点被妨碍。我对大家说不要，拒绝了大家。

然后大家便一下子消失了。我，被孤身一人留了下来。

我自由了。终于可以像过去一样与他人毫无牵扯地自由生活了，我这样想着。不过，这样的自由令我感到了寂寞。大家消失不见之后，我感到很寂寞。

于是，我跑到了大家那里去。我对他们说，既然想要火的话我就给他们。

大家很开心。我照大家所说地为他们带去了火焰。

不过不只是火，我还悄悄地唤起了风。我想通过风来让火烧得更旺，而且只有风对我来说是必不可少的。风是我自由的象征。

没有水。没有土。只有风和火。一切都染上了一片赤红。

再次令大家开心之后，我被大家叫了过去，被大家盛情款待了。

不论是食物，舞蹈，还是礼物，我都没什么兴趣。不过大家想要招待我的那份心意感觉并不坏。而且那种不是水的水也很厉害。

喝下去后身体就会变热的水。有股奇怪的味道的水。那种水越喝就会越想喝。

我变得相当愉快，在大家的劝说下喝下了那种水。喝了好多好多之后我犯起了困，我第一次在不是自己巢穴的地方睡着了。

——醒来的时候，我的手脚都不见了，脑袋正要被斩落。

用来增强火焰的手去哪儿了？用来卷起水旋的尾巴去哪儿了？用来刨开土地的双脚去哪儿了？我的自由，到哪儿去了？

听到了我的声音后，大家带着惊恐的表情发出了怒吼。他们怒吼着。

可就算说我放火烧了他们的国家我也不明白。就算说我用风助长了火势我也不明白。就算对我怒吼着我没有用水和土来扑灭火焰我也不明白。

我的自由哪儿去了？我，为什么要被迁怒？

我告诉大家，希望大家把手脚还给我。可谁都没有听取我的请求。

相对地，我被泼上了那种有着奇怪气味的水。那种令我陷入睡眠的水。

他们在那种水上点了火。我的身体燃烧了起来。好热，好热，好热，我如此叫喊道。

大家都因此而开心。就像曾经对我所做的事感到开心那样，燃烧着的我令大家感到了愉快。

没了增强火焰的手。没了增强水势的尾巴。也没了刨开土地的脚。

——不过，我还有唤起风的脑袋。我还有嘴巴。我还有，牙齿。

把我的自由还给我。把我，还给我。——不要嘲笑我，我要杀了你们。

我的心被一片漆黑所浸染。我，要把除我之外的一切都斩杀殆尽。开心的大家，哭泣的大家，愤怒的大家，我统统都杀掉了。

就算把大家斩杀，斩杀，再斩杀，我想要杀戮的心情还是无法平复。

就算有开心的事，也想要杀掉。就算有悲伤的事，也想要杀掉。就算有生气的事，也想要杀掉。就算有在意的事，也想要杀掉。困了的话，也要杀掉。梦醒了的话，想要杀掉。风吹起来的话，想要杀掉。日落了的话，想要杀掉。

想要杀掉，想要杀掉，想要杀掉，想要杀掉，想要杀掉，想要杀掉，想要杀掉。

我想要杀掉一切。想要杀戮的心情就是我的全部。

我是自由的。所以我想要自由自在地把一切杀掉。统统杀掉。

我是自由的。被我杀掉的大家最后称我为「死神」。

我是自由的。在大家还会对我露出笑容的时候，曾说过我「很美」。

我，自由了。比任何人都要自由。所以，我是『最美的死神』。

——我，是『最美的死神』塞蕾丝缇雅。

——我，是自由的。我想杀掉任何东西。好想要杀掉。

6

菜月昴感受到了「死亡」。

他通过本能理解到，出现在面前的是引导着浓密「死亡」的存在。

「————」

菜月昴害怕得要命。害怕到无以复加的地步。大部分人应该都是如此吧。不过对菜月昴而言的「死亡」，和对于其他人而言的「死亡」有着不同的意义。

「死亡」应是终结，不过对菜月昴而言，「死亡」并不意味着结束。

——---而是地狱的起点。

「既然穿着这副白色装束，我可以认为你是我们认识的那个缇雅吗？」

在宅邸的庭院中央唤起风的同时，白色装束的少女落了地。她的外表和昴认识的那个缇雅无异。依旧是那副容姿，着装也是白色装束——不知为何，她在和蕾泽一体化时会显出一身黑色装束，所以分辨起来很简单就是了。

「现在的你是站在哪边的，要是能回答我一下的话我会很高兴的。而且我会根据你的回答……」

「根据我的回答来决定怎么做，你想这么说吧，阿昴」

「——---」

名字被她呼唤了。是听惯了的爱称。这种饱含亲近之情的称呼到底是——不，或许她是在以自己的方式、带着亲切感呼唤也说不定。

被以这样的爱称呼唤，昴眨了眨眼。

「怎么啦，一脸呆相。希望你不要因为我太可爱而看入迷了哦？」

「……我对妻子是一心一意的。如果下一个孩子是女儿的话，那就是一心两意」

「哼！真敢说！而且……大家都聚集到这儿了啊」

诙谐的回答令缇雅嘴角上扬，缇雅慢慢环视了一圈周围为了这场战斗而聚集于此的面孔。对她而言，这里应该也尽是些熟面孔吧。

他们是为了拯救自己而聚集到这里的，这一点缇雅应该也清楚。

「阿赫，还有其他人也是。大晚上跑过来真是辛苦呢。大人们还真是像笨蛋一样」

「被你这样说的话还真是沮丧啊。大人们偶尔也要像笨蛋一样熬夜的」

「嘿，那你们熬的夜……获得了什么成果吗？」

「不如说我们还比较想这样问你呢。缇雅酱，怎么样了？」

听到这问题后，缇雅伸展了一下双臂后轻轻地开合起了手掌。然后，在像猫一样「嗯～」地呻吟了一声的同时。

「……光珠被我拿回来了。我也，取回了我自己。『大精灵塞蕾丝缇雅至此完全复活！』这样的感觉哦」

「完全，复活，可是你……」

若是复原了的话，缇雅就会无法抑制住杀意了。我记得她以前曾这样说过。

不过即便面前的缇雅正在取回被夺走的力量，她也没有发生大家所担心着的暴走。她不还是以前那个稍显强势的少女嘛。

这样看来，缇雅所说的情况是不是就不会发生了呢。

「别这样啦，阿昴，别抱有些奇怪的期待」

不过缇雅带着严肃的表情摇了摇头，否定了昴这样的希望。昴不禁屏住了呼吸，而缇雅则很没辙似地叹了口气。

「立马就考虑些得意忘形的事情，还真是像男性会做的事呢。不过那是不行的。我说过的吧，能取回光珠都是托你们的福。这一点我很感激」

「既然如此……」

「嗯，谢谢你们——正因为很感激，我才想要杀掉你们」

「————」

让人背脊颤栗的浓厚杀意笼罩了整个宅邸后蔓延到了宅邸领地外，将半个城镇都包复住了。「死」的气息刺激着肌肤，到了让人感觉视野一瞬间被黑色迷雾所笼罩了的程度。

而这些都是面前伫立着的缇雅所释放出来的。

「这，就是我。这就是塞蕾丝缇雅，只为杀戮而生的大精灵」

「缇、缇雅……这，可是……」

「又要说了吗？又要，对我说那些了吗？」

被杀意所压倒，被恐惧扼住了喉咙，心脏跳动也因其紊乱，即便如此，昴还是试图要劝说她。似乎因此而感到烦躁，缇雅踢了踢地面。

缇雅要是行动起来的话，这就将变成一场总体战了。

不过这算不算得上是总体战都有待商榷。这不就只会变成单方面的虐杀吗。昴感受到的实力差就是如此悬殊。

「这种，奇怪的水……是叫，酒来着？我想起来了。我，很讨厌这个」

「————」

「我以前，曾经被灌下了这个，然后在睡着的时候被砍了头。手脚也被砍掉了。最后我被泼上了这个，被点了火……自那时起，我就一直都想杀戮了」

本来作为攻略底牌的酒，若是缇雅因为讨厌它而暴走的话，大家到底会遭受多么残酷的报复呢，缇雅正对昴等人诉说着对酒的怨恨。

不过，她的脸上却挂着笑容。她并没有生气。也没有憎恨。

就只是真心的笑容与杀意共存着罢了。

「我想把一切都杀戮殆尽。不论是笑容，气愤，哭泣，痛苦，开心，还是甜的，酸的，夜晚，早上，白天，孩子，大人，老人，婴儿，男人，女人，狗，猫，狼」

一切感情，一切感动，一切状况，一切时间，一切对象，一切存在，一切的一切对缇雅来说都和杀戮紧紧联系在一起。

「我想要杀戮。想要把一切都杀掉。我，就是这样的生物」

「既然如此……你，又打算怎么对待我们？」

「————」

对于昴挤出的问题，缇雅静静地释放出了杀意。她仅仅只是注视着昴。仅是这一动作便饱含了杀意。杀意的凝聚物，所有的结论都指向杀戮。

那副样子毫无虚假。缇雅她正准备杀掉昴等人。就算不能杀也要去杀。就算不想杀也会想杀。

「我……」

缇雅想要说什么。满溢着杀意的话语吐露了出来。

克莱茵摆好了架势，赫鲁贝尔将手伸进了怀里，昴静静地握起了拳头。

接着——

「——我」

7

——病房之中，浓重的热气与生命的冲动卷起了漩涡。

「快生了——！」

「呜、呜呜——！！」

咬紧牙关，用尽全力握住了支撑着自己的、床铺的栏杆。铁质的栏杆吱呀作响，留下了十分清晰的指痕。即便如此，疼痛也未能缓解，也没法装作感觉不到。

内脏快被挤破般的感觉和生不如死的疼痛捶打着她的意识。此般疼痛，蕾姆在人生当中都不曾体味过。

「咕，好痛——！」

——不，把持续时间也考虑在内后进行比较的话，这比至今为止品尝到的任何痛楚都要强烈。

即便把意识集中到额头上也没有要长出角来的感觉。这件事，蕾姆其实从得知怀孕的时候就已经很清楚了。作为鬼的蕾姆，在那一瞬间已经完全死掉了。

就仿佛将自己的全部生命力都灌注给腹中的孩子了一般。

「————」

至今为止给蕾姆带来痛苦的同时也为她带来了惠泽。

身为鬼族的一员，蕾姆也曾留下过十分痛苦的回忆，就如同向昴倾诉过的一样，自己并没有能够成为一个好孩子。对于父母来说，自己是个不成器的女儿。——而对于姐姐而言，自己直到最后都是个不孝的妹妹。

而相对地，自己也不曾想过自己蒙受的恩惠会如此之大。

每当被疼痛、苦闷，无力所折磨的时候，她便能切身体会到角的存在、鬼的血液与其强大的力量。

在失去了这些之后，自己才第一次意识到这些都是惠泽。

身为鬼族、被父母生下来，以及成为姐姐的妹妹。

和昴相遇、结合、怀上孩子，在她将孩子的诞下的一瞬间，她才第一次理解了这些。

蕾姆的父母，肯定也是这样将蕾姆——

「呜、啊啊！呜——！！」

疼痛的间隔变得越来越短，激烈的疼痛可说已经是连绵不绝地向她袭来了。意识渐行渐远，而每当这时便会被钝痛敲醒，这样的过程循环往复着。

就连竭力鼓励着自己的助产士的声音，蕾姆都渐渐听不到了。

「——！？你以为这里是哪儿！还有你这副打扮……」

「————」

奇妙而惊人的气息令蕾姆睁开了紧闭的双眼。眼眸被泪水所湿润，在模糊的视野里，拼命照看着蕾姆的助产士的身影，并不在。

助产士瘫倒在了病床的脚旁，而相对地，带着一脸认真的表情在旁边注视着蕾姆的人是——

「缇雅、大人……？」

「很抱歉在这种时候来打扰呢，蕾姆。还有，我之前曾说过是最后一次见你，但那是不对的。现在这次，才是真正的最后了」

在努力撑开的视野之中映照出的缇雅，露出了寂寞的微笑。

这是蕾姆也经常会看到的、缇雅的笑容——明明是这样，其中却有着漆黑的妄念在忽隐忽现。

杀意，是杀意。缇雅的笑容中包含着杀意。明明并不是装出来的笑容，却包含着杀意。

「这便是真正的我。所以，我果然是没法和你们呆在一起的。看到你努力的样子，我会想要杀掉你的」

「————」

缇雅的话语中蕴藏着谢意，真心与杀意，一下子就理解了这些。

缇雅的真心和性质，无论如何都没法相容。他们无论如何都没法和缇雅一起活下去。这就是她的话中之意。

「你，取回了自我呢……」

「……嗯，没错。这都是托阿昴，阿赫的福呢。好想杀掉」

害羞地摆弄着头发，缇雅脸颊泛红的同时将杀意挂在了嘴上。

友人的这副姿态，令蕾姆闭上了眼睛。一行泪水滑落了下来。

「缇雅大人，蕾姆要当上妈妈了」

「嗯，我知道」

「缇雅大人，蕾姆爱着昴君」

「嗯，这我也知道」

「缇雅大人……蕾姆，也好喜欢缇雅大人」

「————」

「所以，蕾姆，不能和缇雅大人呆在一起」

即便喜爱，也无法陪在身边。无法相容的性质化作了无法逾越的墙壁。

对于蕾姆来说，她有着比缇雅更优先的、需要去爱的对象。

「————」

将心情传达出去后，蕾姆第一次注意到了缇雅的姿态。穿着白色装束前来的缇雅，她的手臂抱着某人。那是个瘫软无力，没有了呼吸的少女。

是某人的亡骸，是少女的亡骸。这位少女是谁，蕾姆大致猜到了——

「这家伙，是被我带走的。这家伙，是由我杀掉的。她是我的另一半，是并不是我的我，因为想要在一起，因为爱着她，所以我杀了她」

「缇雅大人，您是来杀蕾姆的吗？」

「因为」

缇雅恢复了原来的姿态，就表示昴成功想到了办法。而这里并没有昴的身影，就只有怀抱着将一切斩杀殆尽的杀意的缇雅跑了回来。

从理论上来考虑的话，这真是令人绝望的状况。

单凭这绝望状况的证据，蕾姆就算不停悲叹、哭个没完、摇尾乞怜也没什么好奇怪的。

不过蕾姆并没有那样做，她也知道没有那样做的必要。

「因为」

缇雅再次停顿了下来。

乳白色的秀发摇曳着，通透的眼眸中映照出了蕾姆，缇雅嘴角上扬。

「——因为我爱着你们，所以不要把你们杀掉」

8

自宅邸一刻不停地跑了过来，昴在拂晓的同时抵达了医院。

「蕾、蕾姆，蕾姆怎么样了！？」

「她正努力奋战着呢。怎么啦你们，一脸傻相地靠了过来。你们在这儿只会妨碍我们。到等候室去吧。到外面等去！」

对于气喘吁吁地确认着妻子是否安好的昴，老手术师的态度着实冷淡。

话虽如此，这也是没办法的。昴和赫鲁贝尔的疏忽令他们成为了生产现场的闯入者。站在医院的负责人以及监护生产过程的立场上，这对他们的职业意识而言应该是相当忌讳的场面吧。

「不过话说回来，居然要花半天以上……光是生一个孩子就不是简单了事啊」

扑通一声坐到了等候室的椅子里，赫鲁贝尔长长地舒了口气。看到他摆出了休息的姿态，顺势一同跑了过来的克莱茵等人也纷纷坐了下来。基本在庭院里的所有面孔都跑了过来，医院里实在是容纳不下了。

结果超过半数人都跑到了建筑外面去，沿着路躺了下来，等待着婴儿的第一声啼哭。

昴当然是在建筑里，在等候室之中的。不过他却冷静不下来。

总之他能做的就是匆匆忙忙、焦躁不安地在走廊里踱步了。

「阿昴，你的心情我能理解，不过你还是再冷静一点为好吧？」

「……阿赫说的我都明白。不过，抱歉。即便清楚这样很丢人，我还是没法安静地呆着啊，不活动一下的话感觉都快没法呼吸了」

「也是啊。嘛，我也只是说说看而已。嘴上说着能理解你的心情，但这并不是我能理解的呢。你的烦恼是属于你的。我只是不忍看到你这样罢啦」

这话听上去有些不负责任，但他想尽力为昴排解一点紧张感的心意还是令昴很高兴。

不过赫鲁贝尔带给昴的安心感也仅花了数秒便耗尽了，昴再次开始在等候室里走来走去了。赫鲁贝尔露出了苦笑。

「这种时候，男人只能默默守护着了……就算有数次碰巧在场，也只会感到难耐吧」

叼着没有点火的烟管，赫鲁贝尔这次只说了这些便沉默了下来。

昴在内心赞同着他。这种时候，男人也只能保持沉默了。仰望天花板，以一种类似祈祷的心境全心全意地不断许着愿。

那是非常老套的愿望。不过被丢在这种状态中的话，任谁都会许同样的愿望吧。

「拜托了，神明大人佛祖大人我主耶稣耶和华穆罕默德安哥拉曼纽……」

不问善神恶神，就算呼唤恶魔之名也不在乎。

呼唤出自己知道的所有超常存在之名，昴祈祷着。

「——缇雅，拜托了」

而在最后，他向着既非神明亦非大精灵，而是自己友人的名字进行了祈祷。

希望——

「——请你保佑他们母子都能平安无事」

昴刚刚献上祈祷的话语，空气便如同被切割开来一般起了变化。

穿过病房大门，声音——啼哭声，婴儿的初啼声响彻了整个医院。

昴如同弹起来一般抬起了头，赫鲁贝尔也从椅子上站了起来。睡着的人们纷纷蹦起，翘首企盼着病房的门被打开的瞬间。

「名字，决定好了吗？」

对着伫立在那里、脑袋时而抬起时而低下的昴，赫鲁贝尔如此问道。

「是、是啊，决定好了。当然了。女孩子的话，就叫丝碧卡」

菜月昴的『昴』是星星的名字。是包含了父母祝愿的名字。以此为参考，昴发誓着要成为不为父母蒙羞的好父亲的同时，以星星的名字为孩子命了名。

病房的门，缓缓地打开了。在门的彼端，是蕾姆抱着婴儿的身姿——

「如果是男孩子的话——」

** 终章 『纪念日』

「利格鲁——」

被温柔的声音呼唤了名字。幼童慢慢地原地站了起来。

这是个有着淡蓝色秀发，以及与头发同色眼眸的孩子。年龄正值六岁，还是十分可爱的年纪——的同时，尖锐的目光中却带着对将来的担忧。

菜月·利格鲁，这是这个幼童的名字，他是与这个故事的尾声很相衬的主演。

「利格鲁，你在哪儿呢？差不多要到去寺子屋的时间喽」

「妈妈，我在这儿哦。我都已经准备好啦」

回应了从家里传出的声音后，一位摇曳着蓝色长发的女性走了出来。可爱而又美丽的女性望着站在庭院里的利格鲁露出了微笑。

「啊啦，今天准备做得还真快呢。真厉害真厉害」

「和爸爸不一样，我可不想给妈妈添麻烦」

「唔，不行哦，利格鲁。不能说爸爸的坏话哦。而且照顾爸爸是蕾姆的兴趣，所以没问题的。高兴得我都快生出第二个宝宝了……」

「这可算不上玩笑，所以希望你打住就是了！」

面对利格鲁的回答，女性——身为母亲的蕾姆轻声笑了起来。这样的她的肚子圆滚滚地隆起着，正在为利格鲁的弟弟或是妹妹的降生做着准备。

说实话，虽然对弟妹的降生抱有不安，对利格鲁来说却还是期待感要来得更为强烈。

肯定会是一个可爱的妹妹的。没错。要给妹妹投一票。

「所以说，就算生下来的是弟弟你也不能欺负他、要和他好好相处哦？」

「这个问题，我想只要妈妈你努力生个妹妹出来就能解决了」

「嘛，说什么呢。真是的，这孩子是像谁了呢……」

对于嘴硬的利格鲁，蕾姆如同在感慨着一般将手抵在了额前。

的确，利格鲁的擅长言谈在邻里之间也是出了名的。他的脑袋也灵光到让人无法相信是六岁儿童的程度，在这一带的孩子当中也是被敬佩着的存在。

不过，对于自己应有的状态很大程度取决于周围环境这一点，利格鲁是有自觉的。而大部分影响都是来自父亲以及父亲的工作的。

「能通过爸爸的提案请到产假和育儿假是很不错，但一旦暂停了工作，蕾姆就觉得好无聊……」

「肚子都这么大了，妈妈你还在说什么啊。做点家务不就好了」

蕾姆百无聊赖似地叹着气，不过利格鲁只觉得威风凛凛的妈妈很值得尊敬。

不是第一胎这点暂且不论，第二次怀孕还能这么冷静的产妇真的存在吗。可以的话真想到街上好好夸耀一番，不过这件事爸爸已经在做了，利格鲁只好忍了下来。

「生利格鲁的时候还挺费劲的呢。和那时一比较，就能冷静下来喽」

「生我的时候有那么费劲吗？」

「嗯，相当不得了呢。利格鲁你是横产儿，而妈妈也遇到了生命危险呢」

「有那么危险吗！？」

「很危险哦。危险到爸爸和赫鲁贝尔叔叔都快要死掉了呢」

「那两个人为什么会险些死掉啊！？」

「可不止他们俩哦。巴南城镇险些被全灭了呢」

「我到底是有多难产啊！？」

自己的出生与城镇的存亡息息相关，被如此告知的利格鲁惊讶不已。他根本无法想象当时的情况，不过妹妹被生下来的时候该不会也遭遇同样的难产吧。

「我能不能活着见到妹妹呢……」

如果有个万一，就用从赫鲁贝尔那儿学来的替身术来拿爸爸当替罪羊吧，利格鲁如此下定了决心。

在进行着这般对话的时候，钟楼的钟声响了起来。

「啊，不行。差不多真的要迟到了！」

「那可不行。来，把便当拿好。还有，爸爸他忘记带便当了，请你帮他送过去吧」

「我明白了……诶？」

接过两个便当盒后，两者之间的内容差异令利格鲁皱起了眉头。一边是儿童尺寸的，这他能理解。那是自己的便当。不过，另一边的奢华感是怎么回事。

「是误差哦」

「是吗！？」

「包含的爱意是没有差距的哦。居然担心这种事……利格鲁你还是个爱撒娇的孩子呢。这样可是会让妹妹吓一跳的哦」

「这种好像是我不好一样的说法，我没法接受啊！」

因母亲的话撅起了嘴后，利格鲁将两个便当盒收进了包里。

接着他对母亲挥了挥手，准备离开家了——

「——利格鲁」

母亲的声音令他停下来回过了头。母亲微笑着轻轻挥起了手。

「路上小心」

「我出发了！」

进行了这样的交流后，菜月·利格鲁奔向了寺子屋。

2

「今天也很精神呢，利格鲁」「利酱，早上好」「早啊，利格鲁」

「早上好！早上好！大家早上好！」

对着朝市区奔跑的利格鲁，打招呼的声音从街道各处抛了出来。这里对利格鲁而言是生他养他的街道，是非常习惯了的亲切环境。不过当他对寺子屋的同级生说出「这是当然的」之后对方很吃惊，所以自己似乎是有些特殊的。

「听说爸爸和妈妈以前好像相当胡来就是了……」

曾偷听大人们以开玩笑的感觉谈论过这些。爸爸和妈妈曾经与动摇巴南镇的大事件扯上过关系啦，又或者没扯上过啦之类。

说实话，利格鲁很怀疑这些传闻。那个除了在父亲面前外都小心谨慎的母亲会与那种大事扯上关系吗。不过骚动会以父亲为中心就没什么违和感了。

对着边考虑着这些边奔跑着的利格鲁——

「——哦，利格鲁。这边这边」

与打招呼不同的声音，这耳熟的声音令利格鲁驻足停下，他连忙转过了身去。接着便看到了紧贴着自己背后的黑色墙壁——不对是穿着黑衣服的人物站在那里。

「赫鲁贝尔叔叔！」

「哦～哦～，好久不见啦，利格鲁。有精神吗？修行没有旷掉吧？」

「没旷掉啦！话说，快点进行接下来的修行吧！叔叔你才是，一直都没在城镇里见到你，你在干嘛啊？」

脑袋被来回抚摸着，那粗狂的摸法令利格鲁笑了起来。

赫鲁贝尔是双亲的友人，对利格鲁来说就像是亲戚里的叔叔一般。

虽是这副打扮，工作却是忍者，总是在追寻着给卡拉拉奇都市国家埋下灾祸之种的那帮人。很像忍者这点是事实，他也有在悄悄进行修行。

「因为利格鲁很有才能呢。才能高到要是蕾姆酱同意的话，我都想让你当我的继承人的程度了」

「你说的继承人不会是『永远的游手好闲者』吧。不要啊。我将来还要养妈妈和妹妹，作为一家之主要一份体面的工作呢」

「这话好像在哪儿听过呢，只把父亲漏掉了这点也如出一辙」

「老爸他毕竟是男人，也到了该为自己擦屁股的年纪了。没关系的」

「啊哈哈哈哈！那是啥啊，阿昴也太丢人了吧」

利格鲁一副没辙的样子耸了耸肩后，赫鲁贝尔捂着脸爆笑了起来。那之后，赫鲁贝尔笑了好一会儿才停下

「呼、呼……总、总之我先去蕾姆酱那边露个脸。我会休息一段时间，所以可以的话想亲眼看到你的弟弟或是妹妹的出生呢」

「是妹妹」

「嗯？」

「生下来的，会是妹妹」

「哦、哦，是吗……」

被不可小觑的威压感所压制，赫鲁贝尔对利格鲁的话连连点头。接着他叼起了烟管，点上火后吞云吐雾了起来。

「你接下来要去寺子屋吧？路上小心点哦。回家之后可要好好锻炼啊」

「说好了！撒谎的话就吞千根针！」

「哦，好可怕好可怕。这种阿昴风格的说法真的很吓人啊」

「会从下面吞进去的！」

「还有那种操作！？」

因利格鲁的确认而发出悲鸣后，赫鲁贝尔一边笑着一边挥手和他道了别。

意外的再会令利格鲁雀跃，但相对地时间也变得非常紧迫了。这下子还有给老爸送便当的空闲吗。如果没送过去只会让老爸挨饿的话倒是无所谓，可不送过去的话妈妈会伤心的，他想要避免这种情况。真是进退两难。

所以，作为折中方案——

「——就悄悄地来，吧」

将意识集中在额头上，利格鲁高高跃起，猛地飞跃了道路。

3

高高跃至空中，沐浴在风中的感觉非常舒服。

额头上生着一根角，大气中的玛那聚拢其上，力量充盈全身。一旦进入这种状态，利格鲁便会被全能感所包围，有种无所不能的感觉。

不过若是让角长出来的话，母亲便会露出一副很寂寞的表情，所以他尽可能避免着这种情况。

当然，现在这样的紧急时刻就另当别论了。

「对不起、呢，只能让你生出一根角来……」

仅有过一次，母亲她曾边抚摸着装睡的利格鲁的脑袋边这样说过。

母亲她似乎觉得一根角不太够，可就算有五根、十根角，看上去也会很丑的吧。

额头的正中央长出一根角来，利格鲁觉得既平衡又帅气。

「嘛，不过我脸长得和爸爸实在太像了，所以根本不可能帅气就是了」

踩着不至于将瓦片弄破的步子，利格鲁的身体轻盈地飞跃于城镇之上。

父亲在叫做『巴南文化振兴会』
的地方工作，它位于城镇的东面，似乎在为各式各样的节日和活动做企划，以此来肩负起活跃整个城镇的责任之类的。

振兴会的前身好像是父亲曾经任职的『文化学校』 ，不过具体就不清楚了。

总之父亲的职场一年到头都很热闹，而被朋友问到的时候只能用『是推广用豆子砸鬼的仪式的工作哦』
来说明这一点则令利格鲁很沮丧。

话虽如此，家计是靠父亲赚到的钱来维持的，这一点也是事实。所以就算是站在儿子的立场上，自己也必须要去犒劳父亲，怀着这样的心情，利格鲁正在给父亲送便当的途中——

「——我说，那边的你」

「唔诶！？」

在空中轻松飞翔的时候被搭了话，利格鲁大吃了一惊。而看向出现在自己身旁的人物后，利格鲁不由地呆住了。

是个不得了的美人。乳白色的头发，纯白的装束，声音也带着威风凛凛的魄力。

「呜哇，你啊，我一眼就看出了你是谁的孩子呢。是不是很不妙？」

「诶……啊、哇呀！」

倏地靠近过来的美丽脸庞露出莞尔一笑，而惊慌不已的利格鲁则在空中失去了平衡。他的身体失去控制，就这样朝着地面摔了下去

「好险呢。办不到的话还是不要跳来跳去比较好哦」

「啊」

脖子被拽住、下落的过程被强行打断了。她就那样抓着利格鲁一口气急速下降——悄无声息地在人烟稀少的小巷里落了地。

「那，那个——」

着地后，女性保持着把利格鲁提在手上的状态和他面对面。身上一股好闻的香味飘来，而且还被初次见面的美人注视着，利格鲁心里也小鹿乱撞了。

面对这样的利格鲁，女性满足地舒了口气

「真开心呢。嗯，真是一副让人想把你杀掉的表情呢」

「怎么回事！？」

「哦哦，总觉得很像阿昴呢。那也当然的嘛。毕竟脸都长得这么像了」

傻傻地笑着，女性啪地一声松手将利格鲁解放了。着地后，利格鲁战战兢兢地抬头仰视着这位女性的同时，脑袋里也被浮现出的疑问弄得一筹莫展。

既然提到了长相，她就十有八九是父亲的熟人了吧。父亲的熟人里尽是些怪人，不过面前的女性却是个相当的美人。不，不过

「我说，因为我太可爱而对我一见钟情的话，我也会很困扰的就是了」

「不管你是何等的美人，我都已经有妹妹在了……」

「嘿，挺不错的嘛。有心有所属的女性……诶，妹妹！？业障会不会太深重了！？」

业障，是什么啊。就算对他说这种话，身为小孩子的他也理解不了。

「所谓业障，就是无法改变的生存方式的意思哦。你也会一点点理解的。比起这个」

「比起这个？」

「你啊，是利格鲁吧？阿昴和蕾姆的孩子。没错吧？」

「那个，如果你说阿昴指的是菜月昴的话，就没有错」

女性提到了父母的名字，尽管警惕，利格鲁还是点了点头。女性的态度非常亲切。另外，利格鲁的皮肤也有种轻微的刺痛感，不过这个还是先无视掉吧。

这种感觉，恐怕是那种只要利格鲁还在和这位少女进行接触就拿它束手无策的类型。

「——好惊讶。你呀，还真是有趣呢」

「这个算不算是姐姐你的业障呢？虽然不是很懂就是了」

「啊哈，被问倒了。挺能干的嘛。——你啊，可是成功地驱逐了妖怪的大英雄哦」

女性微笑着说出了妖魔驱逐之类的夸张词语。如果面前的她是妖怪的话，这个世上是有多和平啊。

「然后呢，作为奖励，就让我把这个送给驱逐了妖怪的大英雄吧」

「——？这是啥？」

女性递出的，是由白色丝线编织而成的、类似手镯的东西。对于利格鲁疑惑的反应，女性「呼呼呼」地坏笑了起来。

「这个啊，是我送你的一点小礼品哦。实际上我曾经说过要把光珠给你的，可那样就不妙了呢。所以呢，就把我特制的、不是黑的，而是白的绳结送给你」

「怎么回事？」

「万一你遇到什么危险的话，我会赶来帮你的。这就是为此而准备的道具。这可是很厉害的宝物哦，怎么样？」

就算她说会跑来帮我，面前这个纤弱的少女又能做到些什么呢。

心中产生了这样的感想，利格鲁连刚才她救了鬼化后险些跌落的自己的事都忘了。而且她虽然说了这是礼品。

「母亲跟我说过，不能收陌生人的东西……」

「哈啊！？……啊，你要拒绝我的施舍吗？杀、杀了你哦？」

「你这都是在威胁我了吧！」

利格鲁吐槽了眼泛泪光的同时说出危险话语的女性。

真是个会打乱别人节奏的人。明明看起来比自己要年长很多，却好像在和同级生对话一般。或者说彼此的距离很近——甚至有种在和姐姐对话般的感觉。

而且，利格鲁也清楚她并没有恶意。这一点只要看向她的眼睛便会传达过来。她以让人害羞的程度认真注视着利格鲁，不断组织着话语。

「因为啊，我爱着你呢。虽然很想杀掉你就是了」

「——因为我有妹妹……」

「这个刚才就说过了！说起来，那孩子应该还没生下来吧！」

被露出最棒的笑容的女性说了那种话，利格鲁一瞬之间有点入迷了，不过作为回敬，利格鲁拒绝了她。

是因此而更加生气了吗，女性又是跺脚又是挠头的。

「知道了，我知道了。我——知——道——啦！好啊，既然都说到这个份上了！其实我本来是打算干干脆脆地离开的，可我改变主意了！我要去找阿昴直接谈判！」

「找爸爸？倒是没所谓啦，不过我爸爸的性格可相当麻烦哦」

「我知道。你母亲也是呢。走喽，利格鲁」

只抛下了这句话，女性便快步走了起来。不过，那边和父亲的工作地点是反方向。

「是这边啦」

「我、我知道啊～？话说，你是不是太臭屁啦？你以为我和你的出生有着怎样的关系啊？城镇都要毁掉了哦？」

「讲真，我出生那天到底发生什么了啊！！」

这刚向母亲提过的问题所带来的既知感猛地将疑问抛向了利格鲁。听到他的问题，女性用手指抵在了自己

的嘴唇上，然后。

「这个就真是说来话～长了呢。至少到走到你父亲那儿为止是说不完的」

「那到我家来不就好了。妈妈绝对很欢迎你的」

「————」

利格鲁将手在头后面交抱着如此说道后，女性睁圆了眼睛。接着她抿嘴笑了起来。

「嗯，当然啦。毕竟你们家可是靠着我赚的钱买下的地产呢！」

「你，到底和我们家人是什么关系啊……说起来，我都还没问你的名字呢」

「我的名字？啊——是缇雅哦。关系嘛……我想想」

利格鲁被感觉和菜月家在各方面都有着千丝万缕联系的女性——缇雅戏弄着。不过对此没感到一丝抱歉的缇雅转过身来露出的笑容还是令利格鲁看入迷了。

面对着热闹的人群，缇雅露出了灿烂的笑容。

「——就像是，你的家人一样吧」

说完这句话后，两人慢慢地并肩朝着父亲的职场走去。

回过神来的时候，心情很好的少女正哼着小曲，那曲子利格鲁也曾听过。

「————」

那是从很久之前、自出生时起便不断能够听到的，母亲的摇篮曲。

母亲曾说过，这首曲子名叫『缇雅』。

——所以，既然她说是接近家人的存在，自己就接受了吧。

抬头仰望到的青空，随处可见的普通街道，平凡家庭安心生活的风景。

这份平凡却又无法取代的幸福在这世界一隅确确实实地延续着。

有失去之物，也有抛弃之物，会从某处逃离，也会有想忘也忘不掉的回忆。

即便如此，人们也会在怀抱着各种各样思念，在这不停前行的世界中生活下去。

——而那也是流离在异世界之人的、一种爱的结局。

【从零开始私奔的异世界生活】 完


** 后记

感谢大家陪伴至今。我是长月达平，同时也是鼠色猫。

随盘特典小说第四册，『从IF开始的异世界生活』，是购入了re0动画bd全卷的观众在进一步寄出各种应募券后才能入手的、不经历相当繁琐的步骤就无法获得的一册。

非常感谢花费了这么多精力也想要看到这本书的您。托各位的福，4册随盘特典小说得以顺利完成。谢谢您——

这本书若是放在小说本篇中的话是第六卷，放在动画里的话则是在『从零开始』的轮回前后产生分歧后的内容，是以昴和蕾姆离开王都、私奔到卡拉拉奇的if的故事。

以昴和蕾姆结合、以及那之后的展开为内容的书籍或web小说我也有在写，不过能有幸将其原封不动地写成满满一本书还是令我十分满足的。

内容方面我很想只把两人浓情蜜意的景象写下来，不过写作时各种各样的点子跃然纸上，然后就变成平时的re0那样的感觉了。

卡拉拉奇在本篇中有很多地方没法描写，于是值得一试的设定便纷纷冒了出来。

不管怎么说，这4册随盘特典小说……是我鼓足了相当的干劲所进行的尝试，而能得到成效最后真的是托了各位支持的福。

这篇后记是4月3日写下的。没错，就是正好在re0动画最早放映的一年后写下的。这还真是相当幸运呢。

拜此所赐，动画很受欢迎，书籍和web作品的认知度也越来越高，我也收到了许多的感想，真的是获取了作者一职的回报呢。

动画方面的工作至此就要告一段落了，不过书籍和web版接下来还有很长的路要走，所以还请各位尽请期待吧！

那么，请让我为随盘特典小说的封笔致以谢辞吧。

担当编辑i先生，我做到了。人类还真是意外地能干呢。虽然写下4册的难度相当大，我也曾对此感到不安，但还是真的很感谢您！

负责插画的大冢老师，作者说要写4册于是您也不得不画4册，真的辛苦您了。不过托您的福，我坚持到了最后！

另外，没有动画的话随盘特典小说就没法存在！动画制作相关的各位，谢谢你们给了我描写全新re0故事的机会，真的很感谢各位！

最后致全体读者与观众！谢谢大家对动画，对小说，对re0的支持！

从今以后也请大家继续支持我！还有，我好想写更多圆盘特典！
