#+title: re0 怠惰Ex
#+setupfile: ./setup.setup

* 怠惰Ex
** 第三章断章　『ナツキ・レム』

译者

帥哥魚住

\\

\\

1\\

——晴朗的天空之下，倾注而来的阳光让昴眯起了眼睛。

听见哭声。

是女孩子的哭声。那是已经，竭尽全力将声音融入气势中的哭声，小小的身体用尽全身的力量全力在哭泣。

看见那样将自己的感情与灵魂全部表达出来的姿态，小孩子为什麽总是这麽充满元气呢昴像个呆子一样的这麽想着。想到这里，昴对於自己那个毫无年轻气息的想法感到愕然。

「虽然以前总有自觉自己好像很老成的样子，不过意识到那是下意识情况的时候就屈服了。自己明明还处在活蹦乱跳的Yangumen的年纪的说」

「什麽活蹦乱跳。能客观的看一下你自己吗，喂」

明明就还是现役的，正在观察着自己空掌的昴迎头撞上从旁而来的骂声。再听惯了的骂声里叹了口气，昴慢慢地将目光转向那边。

在昴横侧的椅子上，坐着的是与昴视线高度处在一样的位置的少年。昴无言地注视着少年弯曲的嘴唇，「比起那个」少年继续说道，

「丝碧卡正劈哩劈哩的在哭着阿。我真的没办法处理阿」

「我已经不行啦。纯洁的心灵被你用一句话给无情的打碎变得破破烂烂的了。他已经回到幼童状态像丝碧卡一样在嚎啕大哭了呦。请原谅这么无能的我」

「在人来人往的大街上变成那种状态是要我怎么原谅你啦！?」

少年夸大的仰起身体元气满满的追究着正在孩子气的闹着别扭的昴。但、那个举动让在昴手中被抱着的小宝宝——被称为丝碧卡的少女再次吸了吸气，对两个男人「啊」的「呜」的二话不说，感情再次爆炸。

「哇——！！」

「呜喔！哭了！丝碧卡哭了！喂利格鲁，你小子快想办法解决啊，你是做哥哥的吧！」

「这句话从你嘴中说出来是要闹哪样阿这不太恰当吧！！」

在人来人往的街道上的一个角落中，两个男人一边抱着小宝宝焦躁的咕噜咕噜地转一边互相推卸责任。

大街上的行人们对于喧闹的三人投去了发生什么事的表情，然后观察了一下吧嗒吧嗒转圈的二人的情况只用了一句「什么嘛这不是每天都会发生的事吗」就一脸清爽的快速通过了。

结果，一个哭泣的小女孩与两个绕圈圈的男人形成的景色就这样持续了下去。令人欣慰的是，他们在名为骚乱罪的一张令人不愉快的厚纸来临前就先跑走了。

「明明有一位纯洁的女孩子将自己的感情与灵魂用哭声表达出来，但竟然没有任何人过来伸出援手……该死，这是什么见鬼的世界！人心都已经荒废到这种地步了吗！?」

「现在不是你感叹世界的时候啊！如果就这样让丝碧卡一直哭个不停的话，等等回来的时候该怎么办啊……」

「谁回来的时候怎么样？」

「废话，当然是……」

利格鲁，昴这么称呼的少年交叉着手臂，一边点头一边回头看。然后，他的脸瞬间哑然凝固，呆然的嘴巴发出喀擦喀擦的声音。顺着利格鲁的视线，昴将同样的人物也纳入视野「喔」的一下抬起了眉毛，

「买东西，结束了？」

「是的，并没有被堵住。……亲爱的你这边看起来非常不妙呢」

「是阿，丝碧卡超有精神的。照这个样子来看当她会走路的时候就能发育成将男性举在手中挥舞的类型了吧。恶女系之类的非常有前途，我就决定这么做了Da☆Ze!」ps:作者这里除了字面上发育成将男性举在手中挥舞的类型外也有可能是说发育成将男性玩弄于股掌之间的小恶魔类型，句尾那边我找不到词来形容所以就弄了个通俗易懂的，反正意思差不多

在闲聊的昴手中，丝碧卡睁开了哭肿的眼睛，发现站在正面的女性后张开了那像红叶一样的小手，并且伸直了手臂。虽然力量还不足但却努力伸出上半身的姿态，仿佛是在宣判因为被昴抱着的感觉太差所以想要交换似的让昴的男子心被寂寞给包围了。

「如果说，无视她的要求又让她哭了的话就会像木阿弥一样了。嘿咻，交给你了」

「确实收到了」

虽然语调稍微有些粗暴，但在将小宝宝抱过去的时候昴的动作非常的轻柔。仿佛在对待虚幻的宝物一般用指尖轻轻触碰，接过去的女性很小小的微笑了片刻。

并且，接过去的她好好地将丝碧卡抱在了胸前，轻轻地摇晃着身体，

「你看，那是没用的爸爸和哥哥。丝碧卡也要快快长大，不好好地斥责那两个人可不行呦」

「喂喂，不要趁她还不会说话的时候在她的内心刻上那些莫名其妙的东西啊？」

做出像笨蛋一样的动作和发言之后，想起想像中她把手夹到腰上怒气冲冲朝两人发怒中的自己的样子。利格鲁对于那被责备的光景总结了一句，

「阿勒，好像没有我想像中的那么坏嘛。倒不如过于幸福的未来让眼泪都啾啾的止不住了阿」

「我才不要呢。如果被妹妹发火的话，做为大哥的威信不就完全崩坏了嘛！」

「与我一起吧嗒吧嗒转圈的那个时间点开始威信什么的早就已经崩坏啦。我能看见，能看见呦……由于太过喜欢而娇纵妹妹，最后变成妻管严的你的未来阿」

「你自己不就是妻管严吗别给我加上奇怪的属性啊！我绝对不会变成那样的啦！」

对于手指做着复杂怪异动作而且故意吹着气的昴，完全气得青筋暴露的利格鲁激动地反驳。不过对于利格鲁那激烈的怒声而皱起眉头的并不是昴。

本来是微笑看着两人间互动，蓝色头发的女性。她用平静可是去非常清楚的声音叫着少年的名字「利格鲁」，

「从刚才开始就在外面不断逞口舌之利你以为这里是什么地方？真是令人看不下去」

「呜，可是阿……」

「妈妈讨厌找借口的孩子呦。而且，你刚才说错了一句话」

毫不留情地责备利格鲁，然后她微笑着将视线转向了在怀抱中一直安静待着的丝碧卡，

「妈妈才没有对爸爸妻管严什么的呢。因为爸爸无论什么时候，都是妈妈心目中的第一」

桃红色渲染了脸颊，说出了让整个大街上的人听到了都会害羞到哭的发言。

在堂堂地说出那个的母亲面前，利格鲁这次真正的举起双手清楚的做出投降的动作。

昴一边感受内心痒痒似的感觉一边笑着，看起来幸福地注视着家族情况的她悄悄地压住头发。

蕾姆如同天空一样美丽的青蓝色头发，被微风轻抚柔软地摇曳着。

名为卡拉拉基的地方城市的一个角落中——那是一个连是否能被称为公园都有疑问的广场，昴坐在被设置好的长椅上发着呆。

眼前的是将青蓝色的头发向后梳的利格鲁，与作为朋友的坏小子们组队一起向右向左的来回跳着。对父亲逞口舌之利的习惯虽然没有改过来，不过这点也是他可爱的地方……什么的才没这么想过。

「还有那个看起来一副要把别人杀掉的凶恶眼神到底要怎么办阿」

「不行的呢。因为有了那个凶恶的眼神他才是利格鲁。他看起来那么的快乐，无论怎么样都令人感到喜悦，不认识的人第一次看见他会以为他很不高兴一脸阴沉的正在设计别人的样子。因为是利格鲁呢」

「我听得见啊！妈妈后面的补充让我非常的受伤哟！?」

正沉迷于昴所传授的游戏『冰鬼』之中，被鬼抓到变成冰镇状态的利格鲁好像在呐喊些什么。昴向他适当的挥挥手，蕾姆也小心的在不影响到怀抱中睡着的丝碧卡的情况下向他挥了挥手。

噘起嘴巴，利格鲁因为不满而使得他的三白眼变的锐利。那个样子与残留在相册之中自己年幼时的模样相似的不得了。

「这么说来，那个家伙的未来会变成像我这样子已经是确定事项了阿。换作是我的话都会觉得不寒而栗阿……如果我被说二十年后会变成这样」

「做菜神手家务万能。变成勤快而尽责的男子汉大丈夫，也能够得到理想中的美丽媳妇……是不是这样的意义呢？」

「那是什么现充阿！爆炸吧混蛋东西。啊，好像是我！」

顺便问问，蕾姆线翻完后下一篇番外你们想看哪个？有想点播的话把章节名告诉我

对把手放在头上吐着舌头的昴蕾姆噗哧一声的笑了出来

蕾姆一边用手捂住嘴巴使笑声在喉咙中不断的鸣响着，一边斜视着昴的脸颊，

「完全否定不了的捧杀吧，蕾姆现在有些得意忘形了哟？」

「捧杀什么的，是现在的流行吗？是没有否定自卖自夸的话的意思吗？嘛，虽然蕾姆的话中没有能够否定的要素全部都是事实就是了」

倒不如说，对于蕾姆所说的事昴口中完全没有害羞或客气的意思，更多的赞美交错乱飞的话也会成为严重的事情。白天的公园是小孩子们争霸的场所，和家族同伴或邻居一起来的身姿也很多。一旦开始说起我们的恋爱故事的话，就会被刨根问底并且独占明天太太们在井边闲聊时的话题吧。

虽然不知道这是不是坏事阿，虽然是这么想不过周遭的人已经被荼毒的相当厉害，昴有意识地无视那件事情，温馨的时光逐渐浸染了昴的意识。

如果把眼睛闭起来将把身体托付给阳光的话，温暖的阳光会使身体产生好像快要浮起来的错觉。连续熬夜所带来的身体疲惫使得睡意将意识给冲走了，头变得非常沉重的在摇摇晃晃着。

「那个」

「如果觉得困了，请使用蕾姆的肩膀吧。因为手臂现在正被丝碧卡独占中」

如果试着张开一只眼睛，就会发现不知道什么时候靠近的蕾姆正用身体支撑着昴。二人间稍微存在一些坐高差。如果昴斜着头的话，就会变成头完全靠在她肩膀上的状态。

感觉到有点害羞，昴看着在她的手臂中健康地睡着的丝碧卡。遗传自父亲的黑发，遗传自母亲的可爱容貌。对于这个世界还什么都不知道，纯洁地度过每一天的可爱生命。

「姆姆，丝碧卡这小鬼。虽说是我的爱女，但却是占领我圣域的坏孩子啊。过一会要对她做口修口修的处罚才行」

「要独占蕾姆的胸口的话请等到夜晚的时候呢」

「现、现在因为还是白天的公园所以要小心一下发言啊！?」

对蕾姆的大胆发言昴有些激动的回转上半身。如果看见她的侧脸的话，就能看到说出这句话的本人颊通红的样子。真的不知道该怎么说呢，

「我的老婆，超可爱」

「因为每天，都被爱所包围着呢」

蕾姆也以爱的话语回应昴爱的话语，二人相视一笑。蕾姆是咪咪笑，昴则是带有拟声词的那种微笑。

对于那样互相凝视感觉到有些害羞，昴用手指挠了挠脸颊重新振作起来，说「那么，承蒙您的话」重新把头放上蕾姆的肩膀。

莎拉莎拉，被在风中摇曳的青蓝色柔发碰触脸颊异常地令人心情舒畅。昴就那样抽动着鼻子嗅起发丝的香味，一边将脸颊往蕾姆的肩膀摩擦。

「这样子好痒喔，亲爱的」

「啊，抱歉。不知道为什么这样用心情就会变得很好。看来我要和丝碧卡学习怎么冷静才行。慌张激动什么的就交给利格鲁吧。呜哇，希望利格鲁能自制一下---」

「我听得见啊笨蛋父亲！别擅自替我联想啊！」

「利格鲁。因为妹妹在睡觉，请你在多注意一下」

「这样的我不能接受啊！」ps:骚年你放弃吧23333

结冰的利格鲁大叫着不讲道理啊，不过家族中谁都没有理会他的呼喊。附带一提没有任何人想来救助被冻住的利格鲁。最后，他只能可怜的与鬼交换位置换他当鬼了。

性格和言行，在行动模式上利格鲁与自己相当相似，从周围的孩子们没有对他摆架子的这一点上来看是受了自己的恩惠吗昴这么想着。不过，将孩童时代的自己带入那个小团体来看的话，利格鲁的未来越想越令人觉得灰暗。

「我一定要确保丝碧卡不会变成那样才行。虽然利格鲁是那么的残念，不过，长得像妈妈的你未来是光明的。然后就只能祈祷以后你不会被像我这么没用的男人给捕获了」

「能代替你的人哪里都不存在。蕾姆的爱人在世界上只有你一个人」

可爱的妻子微微笑的说出了可靠的保证，然后沉默暂时降临到二人之间。

一阵柔软的风吹过了手臂，昴透过肌肤感受着蕾姆的体温整个人都快进入了无心的世界。

每天辛勤的劳动使得疲劳累积在了身体里。所以偶尔的家族福利时间，就是要讴歌幸福的日常。沐浴着晴朗的阳光，一边远远的看着儿子被朋友们玩弄，一边靠着抱住可爱女儿的妻子打盹。

——就是这样，这是多么甜蜜的幸福时间啊。

「昴君——」ps:本来我一般是直接翻昴，这里为了区分叫法的变换所以加个君

不经意间，被叫了名字的昴张开了闭上的眼睛。

将视线移向发出声音的位置，蕾姆的头微微的倾向了昴。她淡青色透明的瞳孔里照映出昴的身影，嘴唇微震仿佛有什么事要说一般。

「……那个叫法」

「————」

「真是久违了阿。最近一直被称作『亲爱的』或是『父亲』呢」

这两天太忙没时间更新，顺沿到礼拜六

张开了一只眼睛，昴放松嘴角，替代嘴唇打结的蕾姆继续说了下去。

她的那个态度让昴回想起了数年前，『刚刚逃跑的时候』她时常会变成这个样子。虽然她很尽力的不想让昴注意到吧，不过，在她想像之上昴也时常注意着她。

把眼睛闭起来，感受风的存在。

今天，提出想要像这样全家一起出来购物的是蕾姆。对于她的意图昴多少有些察觉到。说到原因的话，

「从那天开始，到今天为止已经过了八年」

「你注意到了呢……」

「那是，对于我……不，是对于我们的人生最大的转折点吧？与其说注意到，根本就是一直记着没有忘记阿。——根本不可能忘的了」

向命运屈服的日子。将一切全部抛弃，逃走的日子。

虽然想要将过去的一切全部都抛弃，不过就只有这一天怎么样都遗忘不了。

那天的决断和，蕾姆的爱——因为有了那个，昴才能像现在这样被他人所需要。

「昴……」

那个令人怀念的叫法，在两人逃到了卡拉拉基后就暂时没再使用了，她下意识地不使用那个称呼。也许是有想向周围的人表示我们是夫妻的意思，或是某一部份想要和过去有所区别而这样考虑的吧。

到了今天这种日子，那些话并不一定要说出口，蕾姆也不需要再对昴叙说那个理由。

用在那无法摆脱的过去里天天使用的称呼来呼唤昴，蕾姆的眼中泛起了复杂的感情旋涡，

「你会、后悔吗？」

「后悔？」

「是的。逃跑了的事情。死心了的事情。抛弃了一切的事情。蕾姆……」

「那是什么假设的选项阿，听了让人超生气的。带着利格鲁和丝碧卡一起回去吧！啊，果然利格鲁还是算了。丢在那边好了」

已经能看见对面的利格鲁凶恶的表情了，不过，昴以「现在，在说重要的事情」为由将儿子推落千寻之谷假装没有看到他的脸。重新转过身来面向蕾姆，「那个阿」将话题继续了下去，

「事到如今已经过去了八年，这样的话已经说了好几次几十次几百次所以不知道还有没有效果」

「嗯」　　ps:这里的はい我翻成嗯，总觉得用はい中文上看起来不搭

「在这个世界上最爱你的人是我。我的妻子只能是你，你的男人也只能是我。你就是属于我这样的男人，你可不是那种因为我的妥协就能到的便宜女人啊」

昴站了起来，用指尖很轻轻地弹了蕾姆的额头。把手贴到额头上，昴的脸靠近了有些惊讶的蕾姆，

「就如同那天的誓约所说的一样，我的身心全部都是属于你的东西。我会为你竭尽心力，为你献上所有，为了你努力生存在这个世上。——现在，也为了我们两人所生下的孩子们」

把嘴唇靠近她的鼻尖，夺去了眼角泛泪的她的嘴唇。

紧紧是双唇轻微碰触的轻吻，两人的呼吸及为靠近，即使昴的年龄增长了他的笑容依旧没有变化如同喜爱恶作剧的小僧一般

「那么，这样能够安心了吗？」

「……对不起。蕾姆一直都、非常的不安。可是，却变得越来越喜欢昴了。再也没有比这更幸福的时间了，更多更多的幸福向蕾姆聚集了过来。太幸福了，太喜欢了，所以我很不安」

双眸泛起了泪花，说完了幸福宣言的蕾姆微微的摇了摇头。摇了摇头，使自己的额头和昴的额头贴合在一起，互相交换彼此的余温，

「能像这样触碰亲爱的，好害怕不知道哪一天会失去你」

「放心吧。我不会离开你的，再也不会了。我会一直爱着你直到你不再爱我为止，到时候我就会尽量离你远远的」

「蕾姆不再爱昴什么的是不可能的事情——」

「那么，永远在一起吧。我爱你，蕾姆」

对于难以处理自己心中感情的蕾姆，昴再次吻上她的双唇。

双唇紧密的贴合在一起，固定了惊讶的蕾姆之后昴吻得更加深入。彼此间柔软的器官互相交合缠绕，舌尖上能感觉到两人炙热的唾液。

吻到了一个段落后两人分开双唇。轻轻地喘息着的蕾姆，稍稍的深呼吸了一下。昴对于那样的她立起手指说，「从一开始」

「妥协啦什么愚蠢事情从一开始就不应该说啦。那样说的话，你把他们当成什么啦？利格鲁和丝碧卡不是因为爱情而是在同情之下出生的孩子？丝碧卡是我和你充满计划性所诞生出的爱的结晶，利格鲁则是因为年轻时燃烧的爱情暴走所诞生的结果」

「……利格鲁出生的时候真的是非常不得了呢」

做出把手贴到腰上的姿势说教的昴，蕾姆以双唇微微笑的方式回应他。

回忆奔驰而出，她以充满爱的模样用指尖描绘出了过去的记忆

「我们转移到卡拉拉基之后终于找到了住的地方和工作，我们花了很多时间才将生活的基础慢慢地打理好呢」

「哦呀你看嘛，那是因为太年轻了所以耐力不足嘛」

「昴明明工作回来时应该会很累的，在睡觉之前却变得非常精神呢」

「呀，因为年轻所以体力很多嘛」

「明明就能申请变成正式员工的，却因为怀孕所以大部分时间都一直在一起。那时候蕾姆的脸色真的是铁青到发白呢」

「真的很不想承认，自己以年轻为理由所犯下的错误……」

面对蕾姆怒涛般的进攻方法，昴一边感慨地远目一边自言自语。面对自己过错的昴看向对面一脸苦涩想要说些什么的利格鲁，从读取他周遭的气氛来看他终于学会自制了。真是相当能干的儿子阿。

对于儿子的成长昴点了点头。在旁边的蕾姆也做出了一样的动作，看着一脸苦涩被冻在那里的儿子，「但是」蕾姆小小的吸口气继续说了下去，

「蕾姆在怀了利格鲁的时候，真的是非常的高兴」

「那个阿，我也是非常的高兴阿。最初听到时我直接喷出了鼻涕来还稍微漏了一点点尿，那时还想确定是不是梦而要求蕾姆把我打到流血哪」

或许是蕾姆也相当慌张的关系，结果她用了能将临时住处打到倾斜的威力将他打飞了出去撞到墙上。如果不是当下立刻做出了受身的动作，搞不好就死了也不奇怪。

那些回忆暂且不说，想起当时蕾姆一脸认真的向昴报告说她怀孕了的景象。那个时候，自己全身都被胸口涌出来的温暖给包围了。

可是，蕾姆对于昴的回答摇了摇头。不明白那个反应的意义昴疑惑的歪了歪头，她的微笑逐渐蒙上了一些阴影，

「蕾姆高兴的理由，一定与昴那个纯粹的理由不一样。蕾姆之所以高兴……是因为，这样子就不会失去昴而感到喜悦」

「……」

「利格鲁呢，是为了确保蕾姆与昴之间的形式而出生的纽带。虽然这个说法非常的坏，不过由于小宝宝的关系使得蕾姆与昴之间，产生了绝对不会被切断的联系。……那个令蕾姆感到非常的开心」

每天都感受到的不安，一直做为重压悬挂在她的身上。

将至今为止的人生中积累的东西全部舍弃，只有自己和昴两个人一起逃进了新天地里。在除了对方之外没有任何人能够依靠的每一天中，蕾姆难以忍受不知道什么时候会再次失去昴的恐怖。

她非常没有自信，觉得自己身上并没有能拿出来与昴相提并论的东西。

对于太过低估自己的蕾姆来说，与昴在一起生活所带来的极限的幸福时间和极限的恐怖时间相等持续抵销。

在那样的时间上打上了终止符的，是出现在二人之间的新生命。

「无法相信我吗？」

「不是的。蕾姆在这个世界上比谁都还要相信昴」

「不对啊。所以不是无法相信我……而是，无法相信自己吗？」

对昴否定的言词，蕾姆很小地吸了口气，然后点了点头头。

在她的心中昴的存在被不合适的放大。而与之对峙的自身的身影，她总是觉得格外娇小所以才感到不安吧。

——一直都在思考相同的问题，昴也抱持着和她同样的想法这件事她似乎一点都没注意到的样子。蕾姆总是认为自己是多余的存在，昴一直都觉得这个女孩子实在是想太多了。

不自觉笑了起来。昴的嘴角松动露出了洁白的牙齿，蕾姆没想到会被当成笨蛋所以脸颊不断的鼓了起来，

「呜呣——。蕾姆很笨。被笑了也没办法……」
ps:这里いいんです中文实在没办法清楚的表达出蕾姆卖萌的语气所以我干脆换成卖萌的状声词

「不是不是。我只是再次觉得。我和你在毅力这部分简直一模一样，果然我的老婆是世界上最可爱的」

对昴突然袭击而来的言词蕾姆一瞬间感到吃惊凝固了以后，突然间脸变得异常通红。观察着那个反应，拥有了果然自己非常的爱她这样的实感。

世界第一，最喜欢蕾姆这件事。爱着她。昴能大声的将它给喊出来。不如说，能做到这种事的人事实上相当稀少。他们在这附近也是相当有名的亲热夫妇。

「——利格鲁，丝碧卡」

「嗯？」

偶然间，蕾姆以充满了爱的语气呼唤着自己孩子们的名子。对着歪着头的昴蕾姆说「不是呢」，并使眼珠朝上凝视着昴，

「不管哪一个，都是星辰的名字呢。在昴之前所住的地方，习惯用星辰来称呼对方呢」

「虽然衣冠楚楚的。但我的父亲是脑子里基本都装了些很奇怪的写作常识读做残念知识的人类，不过，我觉得他将我的名字取作昴实在是非常好的判断。我非常的喜欢呦，这个名字。昴也是，星辰的名字」

记得是小学的时候吧，好像有个确认自己的名子来历什么的课题，昴就是在那时知道自己名字的来由。知道自己的名字是来是夜空中闪烁的星辰时，与平常不同高兴的蹦蹦跳跳。

从那以后，虽然爱好并不是什么拥有持续性质的东西，只有观看星辰突见这件事情持续了很长很长的一段时间然后变成习惯了。星星的名字大概都知道的话，在取名字的机会来临时就当然的会有很多可供选择的方案，

「名字取自星辰。网络的昵称也是星星的名字，报假名的时候大概也是会取和星辰有关的名子。也有这种意义阿，取个亮闪闪地名字！?」

「虽然不太清楚这是什么意思，不过我觉得用星辰的名子来取名是件非常美妙的事情。我们第三个孩子出生的时候，一定也要那样做」

「现在就开始讨论第三个孩子会不会太性急了点啊？丝碧卡，现在还是婴儿哟？」

「喂奶以外的时间我想如果托付给利格鲁应该是没问题的。要说为什么的话，利格鲁已经长大到会注意即将诞生的孩子了我是这么想的呢？」

「虽然在我的背后看起来有些不显眼，不过蕾姆对利格鲁也是锵锵的去啊！?」

Ps:就是说蕾姆也和昴一样偶尔会玩弄一下利格鲁，可怜的孩子

用平时处理儿子的方法苦笑，昴站起来拍拍屁股。在仰视的蕾姆面前昴把脊背向后仰，转了转腰部

「差不多啦，也想把买的东西放好我们回家吧。在外面众人的目光之下，也不能够尽情的打情骂俏」

「说的也是呢。现在蕾姆，也很久没有这种想要全力全开来调情的感觉的说」

「呃，在与鬼拼体力的场合上用现在的我的性欲能够支撑的住吗……」

提心吊胆地嘟哝，然后昴走到长椅前对坐在椅子上的蕾姆伸出手。蕾姆靠着那双手，慢慢的被拉了起来，在手臂中抱着的她发出了「哇」的一声。

她紧抱着丝碧卡，确实地充分享用那个温暖之后，

「好啦，回去吧。回到我们的家吧」

「是，亲爱的」

一只手拿着购物袋，用另一只手紧握着蕾姆伸出的手。走在前面的昴放缓了半步，形成与蕾姆牵着手贴近在一起行走的样子。

就这样到了广场的正中心，走到了到现在为止还是结冰状态的儿子身旁，

「喂，处在札幌雪祭中的儿子呦。因为看你玩一点进展都没有的冰鬼实在是太过无聊了，所以我和妈妈带着女儿回家了。你就住在朋友家吧」

「这么露骨地把我赶出家门！?话说回来，父母亲大白天的在公园正中央堂堂地接吻调情这件事是要闹哪样啊！?」

「啧啧，嫉妒啦。但抱歉阿，利格鲁。这个蕾姆，是我专用的」

「烦死啦！！」

昴鼻子膨胀的放声大笑，利格鲁的三白眼变得尖锐朝他大声怒吼。但越是那么做昴就会笑得越高兴，利格鲁一边大口的深呼吸一边摇头，

「冷静下来冷静下来阿，我。别被父亲的步调给拖着走。冷静下来，冷静---。好，冷静下来了。是说，你刚刚和妈妈在说什么？」

「啊？是在说你的名字是来自星辰的名字这种气氛的话题。你最初的名字候选其实是维迦，不过……」

「听起来超强的感觉！为什么最后不用了？」

「呀，听起来超强的对吧？因为很强所以会成长的很快，感觉叛逆期来的时候会很不好对付所以还是算了。总有一天你也会明白的，那种不想输给儿子的父亲的心情然后像我这样喃喃自语」

「对于才刚出生没几天的婴儿你就想到那么久远的未来去了！?」

对于昴冷澈的俏皮话，利格鲁气得跳了起来。但、

「啊ー，利格鲁动了呀！不能随便破坏冰鬼的规则啦！」

「啊！」

迄今为止都被认为刻意忽略利格鲁的鬼，在关键时刻弹劾了动了的利格鲁。面对喉咙堵塞再次凝固的利格鲁。昴拍拍他的肩膀，

「打破冰鬼规则的家伙是要受到逞罚的。在你笑到哭不出来之前鬼是不会停止对你挠痒痒的喔。——加油吧！」

「这可不是一脸真的吗的表情就能带过的事啊……喂，你们干什么啊！你们！给我等一下！别把这个男人的话当真啊！等，哇啊啊啊啊啊——！！」

利格鲁被一个接着一个出现的孩子们到处追赶。利格鲁逃了出去。可是，转眼间就被包围了。就那样被抓住四肢压上在地面上，空虚的抵抗也阻挡不了那一双双白色的手指向他的身体袭击而来，

「再见了儿子呦。你是个非常好的儿子，不过。你的父亲是个坏人啊」

「利格鲁。因为爸爸和妈妈有重要的事情要协商，所以你今天就住在朋友的家吧。还有，禁止使用角。衣服也不能弄破」

「喔，给我记着，你们这对薄情父母——！！」

被如同高山般的魔掌玩弄着身体，笑声以利格鲁为中心强制炸裂了开来。丝碧卡半睁着的眼睛看见哥哥的那样的丑态，昴和蕾姆听见了她那快乐的笑声。

将来相当有前途啊，昴这么感性地想着。一定，她的跃进会改变利格鲁在菜月家的立场并使它坚若磐石吧。
ps:咦？原来利格鲁的地位还能更低啊？

昴是如此的爱着他的爱子们，虽然他爱的表现方式稍微有点歪掉。就这样昴拉着蕾姆的手不断的开始向前走。

向与最最重要的家人们一起生活，充满安乐幸福地我的家。

「昴」

「嗯？」

被拉了拉手所以停住脚步，昴回头看了过去。

这个时候，一阵强烈的风刮过二人之间。让人不由自主地闭上双眼，直到风的声音停止之后才又慢慢地张开眼睛。

蕾姆青蓝色的长发被强风吹拂飞扬，在阳光的照耀下闪烁着美丽的光辉。

留起了长发的蕾姆。好像在与谁抗衡似的，现在的昴总觉得自己能够明白。而当联想到长头发的少女时，最先浮现在脑海里的，已经是在眼前的这个世界中对于自己最重要的女性。

青蓝色的秀发安静地飘动，手臂中抱着爱女的蕾姆对昴轻轻的微笑。

那是什么都无法比拟的，最能唤醒昴心中名为可爱的感情的挚爱的微笑。

「蕾姆现在，是世界上最——幸福的人了」

\\

《完》

** 怠惰Ex2『鬼与幸福都进家』
リゼロＥＸ　『鬼も幸福も』

译者

清欢2006

\\

\\

1

「怎，怎么会……这样，骗人的吧！?」

昴抱着头发出惊讶的声音。

眼中浮现出动摇，惊慌失措。昴的视线投在商店--市场左右展开的露天商铺中的一家上，

褐色皮肤的店员被昴夸张的反应吓得瞪大眼睛。（吓得眼睛瞪得想丸子一样大）

但是，被惊讶支配的昴没有注意到店员的态度。

嘴唇在颤抖，额头湿润浮现出汗珠也忘记去擦，非常痛苦的咽下一口唾沫。这样，停下脚步的昴。

「喂，怎么了突然停下来。不早点回去的话不会被咋整吗？」

走在前面带路的人，嘟着嘴走了回来。

手放在头后，尖锐的眼神中透漏着不满。但是，昴知道像是想要杀死对方的锐利的目光，并不是因为对对方的讨厌或恶意，这是与生俱来的。

要问为什么，昴自身就是体会过由这种眼神引来的无谓的中伤前辈。

「坚强的活下去……」

「怎么突然自怜起来了！啊，算了！不想听！知道就算听了也只会郁闷！别说！不要说啊！」

「被这么元气得激励着，我的心情也会向前看啊。真是的，你是拉动我的好家伙啊。天赋的才能。原来持有着加护啊！」

「真的不需要！老天爷是有分发这种加护的闲暇的话，就给我些更有意义的啊！」

冲昴说话的唾沫横飞的，三白眼的人——蓝色短发的少年仰天叹息道。昴对少年的过度反应多次点头，然后重新转向了一脸懵逼的露天商人。

然后，

「这个，多少钱？」

「啊？」

对回复的愣住了的声音，昴满脸喜悦地笑着。看到那露出牙齿的凶恶的笑容，露天商人的喉咙一瞬间「嗬咿」得抽搐了一下

看出内心是受了伤，在今天的相遇之前的都是些不值一提的事情。

昴咳嗽了一下，用手指着露天商铺摆放的「那个」，

「想要这个。给我。姑且，每袋三个」

「哎，啊~！谢谢惠顾！」

「等！等一下！突然间干什么……买些多余的东西回去的话，就不只是被怒视，是会被行使武力的吧！」

当理解了昴的要求，露天商人大气的答复的时候，少年抱紧身体脸色都变了。对拉着昴的衣摆，叫他重新考虑的少年。

昴拿开了他的手，弯下膝盖迎合他的视线说

「放心吧，买东西用的钱不在财政预算中。用的是我的私房钱，慢慢存起来的零花钱。我对零花钱的使用方法你也是知道的吧」

「啊啊，嗯……不喝酒、不抽烟也不赌博，除此之外的使用方法……都是花到女人身上呢」

「你，故意用招来误解的说法吗？想知道，性格恶劣乖张是和谁一样啊」

「大体上没错，是遗传基因啊。令人悲伤。」

冲像叹息一样摇着头的昴，少年竖起左手中指堂堂的宣言。昴抓住那竖起的中指，「啊」少年叫道，他的指关节发出了悲鸣。

这样进行互动的两个人在面前，孜孜不倦的进行着商品装袋作业的店员露出营业用亲切的笑容。

「关系真好啊，老爷。和那边的小子是亲子吗？」

「喂喂，在这种条件下才看出来……商人的眼光也真是不行啊！你怎么看，利格鲁（参宿七）」

「看到我的脸做出跟你有血缘关系的判断才是非常困难的吧！」

被关节技放倒的少年——利格鲁不服输的叫道。听到的昴也「嘛，也是呢」这样呆呆的答道。

在这期间，商品装好了袋子。昴对拿着三个小袋子出来的店员掏出了装着零花钱的名为钱包的东西，

「那么，多少万元」

「虽然不知道万元是什么，但每袋是铜币六十枚」

「那，银币三枚足够了——老哥，找零就不用了，收好。」

「唉~！这也太大度了！老爷，我就感激的收下了」

店员做出演戏般夸张的动作收下了给出的银币。对这场生意的氛围亲切的露出情不自禁的笑容的利格鲁、马上转动手腕露出怨恨的视线。

知道他关节技和找零都不需要的发言中抱有不满、

「好了。今天看到了足够令人怀念的东西。想象成和那感动相称的东西就好了。」
 
 赘沢するとバチが当たるぜ（没查到是什么意思，直译的话」太奢侈的话，蜜蜂会教训你）

「感动啊，怀念啊，在说些什么？」

站起来后，利格鲁继续不服的追问。

昴粗暴的摸着利格鲁的短短的头发，传来「哇」的叫声，

「稍微和老婆有关系，想起了故乡的风俗了」

昴露出邪恶的笑容说着。

-----

「所以，就买了预订外的东西吗？」

出来迎接的蓝色头发的女性，听了昴的说明后吐出来小小的叹息。

昴和利格鲁一起回到家进入屋子马上就来迎接的人物。可能由于干了洗刷的工作，白色的围裙上有擦拭过手的痕迹。

围裙上有昴因为无聊而缝上的贴花刺绣，就算是擦手也要避开那个地方，这让昴很是害羞。

「真是的，在笑什么。蕾姆无法理解」

看到昴不禁松开了嘴角的女性——长着蓝色长发的蕾姆生气了。她向昴旁边的利格鲁投去要降下惩罚的视线、

「利格鲁也是。爸爸不是经常就做出出奇怪的事情吗，你不好好去做是闹哪样啊」

「是。在反省了……不对，这很奇怪吧。冷静下来思考一下想来很奇怪吧！?为什么老爹的奔放，作为儿子的我会被迁怒啊？立场反了不是吗？」

「等下，利格鲁。深吸一口气，吐出来……对，慢慢的。这样试着做五次，闭上眼睛。一、二、三……对，怎么样。冷静下来了吗？冷静下来了啊。那么，再一次向妈妈道歉……」

「慢慢的深呼吸冷静下来再回来反省我也没有半点错啊！！」

与冷静正相反，满脸通红的利格鲁怒吼着走进了家。用敏捷的动作从蕾姆的侧面通过，

「利格鲁！」被蕾姆用愤怒的样子喊到名字也没停下脚步。这样出乎意料的，跑到了走廊的尽头，

「什么啊」

说着，停下了脚步，最后还是听了母亲的话估计内心还是好说话的。蕾姆叫住那样做的利格鲁的原因似乎明白了，用温和的表情松开嘴角，

「房间里有准备好的零食，洗过手再吃吧。还有，别忘了跟丝碧卡说『我回来了』哟」

「知道了。我开动了」

昴和蕾姆教育的结果，吃东西之前的「我开动了」是菜月家铁的规矩。怄气也好，反抗也好，尽管那样却遵守着的利格鲁的善良，夫妇二人用温暖的目光目送着。

作为最低限对的反抗，粗暴的关上门，利格鲁的身影在走廊下消失了，蕾姆重新转向昴的方向，

「刚才开始，就有点太过分了吧」

「嗯喵，作为母子间的交流，很好很好。利格鲁也是，那个绝对不是真心讨厌。那家伙，真的令人吃惊的程度和我小时候一摸一样。所以这种是明白的哟」

昴一边安慰着沮丧的垂头的蕾姆，一边把鞋脱在玄关走进家中。

先不管利格鲁（虽说这样，注意着不反过来悄悄地搭在墙壁上）回收行李，和理所当然的在旁边的蕾姆一起去往起居室。

购物袋放在桌子上，顺便一提露天商人卖得三个袋子像是能看到一样放着，蕾姆从袋口向里看，

「真是……什么奇特的东西东没有，只是普通的豆子呢」

「恩恩，是这样。什么啊，以为是什么羞羞的隐喻吗？我的老婆老实的在那种的方积极地呢」

「爱情用行动来表示，展示出来是不会踌躇的。而且，是害羞的事的话，就算是昴，也不想输」

「啊，我做过不知羞耻的模仿害羞又纯真naive的深闺男孩（ナイスガイ）之类的事吗」

用手抵住下巴，露出牙齿的昴，蕾姆一瞬间露出了看得入迷一般呆住的表情。之后她就这样脸颊发红，飞快地从昴那移开了视线，

「结，说是结婚纪念日买来大量的鲜花，又或是在蕾姆生日的时候和利格鲁两个人装饰了家，又或是丝碧卡降生的时候向镇里的人拜托（ダイミョーギョーレツ求大神解释）……昴太在自己以外的地方花钱了。」

「我为了让我的老婆、我的家人高兴而花钱。这是为了我以外的什么的意思吗？为了我幸福的生活而使用零花钱不是当然的吗？」

「————！」

歪着头昴的回复使蕾姆白色的脸颊因为羞涩而染得通红。过多的感情使眼中涌出泪水，抬起头的蕾姆突然抓住昴的袖子。

突然间的行为使昴发出「哇」的悲鸣体势崩坏。在昴的正面，就像等在那一样蕾姆踮起脚尖，

「————」

「……突然，怎么了？」

一瞬间，彼此的嘴唇相互重合，甜蜜的舌尖缠绕在一起而后分开。

对于蕾姆突然地爱的表现，昴心跳不止，表面上装作平静的样子。用舌头舔着说话的昴的嘴唇，总觉得露出妖艳的表情的蕾姆说「不是」，

「昴……好坏。那种事，突然说出来」

「那种事是，我说了什么」

「昴要更加好好打认识到，自己说的话和一举一动都给予蕾姆莫大的影响的事实、平常来说应该注意到的。——在家里再怎么（说话）去掉主要内容都没关系，如果在外面被这样说了不会很困扰吗？」

看着满脸通红说着可怜人的话的蕾姆，表面上保持平静的昴的那边理性像是被切断了那样。

扭扭捏捏地用手指顶着手指，侧开目光。吐息在慢慢的变热，应该不是因为昴的偏心吧。

但是，那两个人之间的羞羞的氛围——

「————哇，哇，哇~」

「呀！！丝碧卡哭了！谁！谁来！帮帮我！！」

从家的深处传来的，爱子与爱女两人的声音立刻破坏了氛围。

昴和蕾姆互相看了看对方的脸，不由自主的笑了出来。然后两个人，什么都没说，互相牵着手，走向骚动着的孩子们那边，

「这么说来，最后，为什么买了哪些豆子？昴的故乡的风俗是……」

「啊，没有说来着」

因挽着胳膊，靠在身上的蕾姆的体重感到高兴，昴一副没什么的样子，对妻子笑着说，

「——在我的故乡啊，有用豆子丢向恶鬼来驱鬼的风俗」

——说完之后，昴看到蕾姆的笑容像冻结了一样。

--------

「不就是这样的！真的完全！没有那个意思！」

「真过分呢~，丝碧卡。爸爸真是，一定是讨厌妈妈了。如果不是的话，为什么买来驱鬼习俗用的豆子……一定，在拐弯抹角的说。蕾姆的事，蕾姆的事」

「并不是那样的啊！我！在被问到蕾姆和利格鲁那边最重要的时候，一定会毫不犹豫的回答『蕾姆』的！」

「你这个，狗*爸爸！！」

家族四人的喧嚣吵闹地围着这个房间咕噜咕噜地转着圈。

在最前面作者圆周运动，怒气冲冲的蕾姆还在冲着还是婴儿的丝碧卡发着牢骚，昴追着她一边道歉，大体离开那个场所但是不薄情的利格鲁，现在正对着昴竖着眉毛发怒跟在最后面。

「我知道了，稍等一下！确实刚刚是我的说话方式不对。被问到蕾姆和利格鲁那边最重要的话，会好好地烦恼一会再选蕾姆的！」

「不是因为做出决断所用的时间而发怒！我被卷入夫妇吵架了啊！」

「利格鲁，爸爸什么的是用嘴说就好使得人吗。而且满脸怒气的生气的话，丝碧卡会哭的。请安静」

「不想被现在，这个屋里比谁都怒气冲冲的妈妈说！」

还在怒喊，被昴和蕾姆两个人同时做出把手指放在嘴唇上，「嘘」地告诫的利格鲁脱离了圆周运动。

剩下的两人，昴和蕾姆仿佛在相互追逐着背影一样，在中间体育坐（屁股放在地上，两手抱膝的一种坐姿）的利格鲁周围转来转去，

「驱鬼是比喻的表现手法。我老家就是这样……或者是所有的坏东西，疾病啊，贫困啊等不受欢迎的东西的总和叫做『鬼』。播撒豆子是驱逐哪些的仪式，并不是真的敌视鬼」

「好过分，真过分啊。昴，明明以前说过鬼什么的，非常喜欢鬼什么的说服了蕾姆……已经忘了那个时候的心情了吧」

「没有那回事！」

说完，昴停了下来回头看。没有想到圆周运动停了下来快步走着的蕾姆，一脸惊讶的撞进了昴的怀里。

昴用双手，像不想让她逃跑一样，抱住脸贴在胸膛上，呼吸急促的蕾姆。

「我忘记你的心情什么的，这种事情不可能有的吧。对我来说最重要的就是你了。你才是把这点忘了吧？」

「m，昴」

在热情的目光的注视下，昴看到面前蕾姆的眼睛湿润了。

距第一次相遇已经过去九年了，这期间成为母亲的蕾姆的身姿，也由娇弱孩子气升华成了一名女性的强大。

尽管如此，只有在昴的怀抱中的时候，会变回可爱，拼命的寻求昴的蕾姆。

蕾姆为那样的自己感到害羞而垂下了目光，因为甜蜜的感情而嘴唇颤抖，

「昴……啊，利格鲁。先照看一下丝碧卡」

「哎，啊，哦」

「——昴」

吧在自己与昴之间狭窄空隙中的丝碧卡交给利格鲁看管，蕾姆把空下来的双手和脸颊依偎在昴的胸前，

「在昴的（怀）中，现在蕾姆是世界上最重要的吗？」

「当然。我的一半是由蕾姆的爱，另一半是由蕾姆的思恋组成的，这样说也不过分哦」

「真是的，又把我当笨蛋……」

昴和蕾姆相互拥抱，彼此交换着爱慕。

看到那样的双亲和好的光景，利格鲁机智的捂上了腕中丝碧卡的耳朵，

「哪门子的喜剧啊~！！」

这样，用尽全力吐槽道。

--------

「说起来，节分吗……没听说过的风俗呢」

「嗯，这里是这样呢。原来的地方，用这边的日期来说不好表述，通常是二月三月左右……」

真确的日期是二月三日。

然而，这边的世界只有像是四季，一年大致三百六十天前后这几点是共通的，而叫法不同，生活了超过九年也没推敲出来。

模糊地认为，季节寒冷的现在是一月到三月的哪天当成是这样。

「因为只个原因，就想着过一下节分吧！不是为了驱鬼，而是想驱散被称作鬼的坏东西的总和，延续家族的幸福！」

「所以，就在四人中三人是鬼的家庭中说了……」

蕾姆苦笑着，突然伸出额头白色的角，开始鬼化。

就如蕾姆所说，鬼和人混血的利格鲁和丝碧卡同样继承了鬼的血，这两个人也好好地长着角。利格鲁可以按照自己的意愿显现，丝碧卡哭的时候短短的角会伸长。

房间中，围坐在一起开会的四人。果然，鬼们一副不起劲的样子，昴则是不満顔（注：不满颜是什么样的表情不是很清楚）。

打破这暂时的沉闷的是，

「话说」

「啊」

昴向正坐着的蕾姆伸出手，用指尖触碰白色的角。

角有着硬质的触感，其表面隐约感到温暖，触感光滑。而且，角本身也有感觉的样子，昴的手指移动的时候，

「啊，不……要，不可以，昴……孩子们，在看着……」

「舒服的样子没什么说服力啊……」

比起色色的样子，蕾姆展现出像是可爱的小动物的样子，身体靠了过来。抚摸着要确实软下来，坐在膝盖上的蕾姆的角，昴看向利格鲁，

「利格鲁怎么看？」

「现充夫妇爆炸吧以外的？不，虽然不清楚……老爸那个，为什么这么厉害。不知怎么就变成这么好的脸色了」

一边抱着丝碧卡，利格鲁一脸不悦的睥睨着昴。从儿子那得到答复的昴「嗯」地大幅度点头、

「单纯来说，鬼作为主角的风俗出来这个就想不到其他的了。而且刚刚说明不足，这个风俗

还有后续哦。驱逐坏东西的象征、鬼的时候，也有作为代替把幸福招入家中的一面哦。总之，就是从家里驱散坏东西，祈祷家庭平安的仪式」

拍着蜷在膝盖上的蕾姆的背，昴竖起空着的手指，

「对我来说没有比家人更重要的。并不会因为和鬼有关就无视缘分……再说了，就算是鬼也不全是坏家伙」

「……ってーと？（？）」

「正确的做法是，『鬼啊~，外面去~！福啊~，来我家~！』一边这样说，一边不停地洒豆子，最近，鬼啊福啊都到我家来的做法流行起来了」

「本末倒置了吧！区分好东西和坏东西的机会去哪了！」

「思考问题的方式变了吧。嗯，我不认为这是坏东西」

听了利格鲁的话昴苦笑着，用手指温柔的梳理着蕾姆的长发。背后微微传来震动的蕾姆，

令人恋爱的样子，是笑容升华了，

「因为是鬼就赶走，这太粗暴了。说不定，即使是鬼也能友好相处。和鬼工口的事情，结婚，组成家庭也能做到」

「……」

「总觉得，世界也能像这样改变就好了，这样想。我，越来越喜欢鬼了，现在老婆是鬼是最大的幸福。或许，人生是伴随着好事和坏事的这个教训的意义改变了。」

善与恶随着社会的变迁而改变，节分、对鬼的态度也改变了。

鬼是萌角色的出版物等，只不过是刚刚开始的国情，昴却也充分继承了那个民族性。而且，完全不想抵抗，因为——老婆好可爱。

「鬼啊~，来我家~！福也~，来我家~！」

「什么啊？」

「鬼在，福也在。哪个都想要的呼唤方式。我不管哪个，幸福也好鬼也好，都是幸福的象征。贪婪的两个都想要……，怎么样」

缩起肩膀看向昴，利格鲁想说什么似得嘴巴一张一合，结果什么也没说松开肩膀放弃了。

看到儿子的反应，昴笑了。一直在膝盖上任昴摆布的蕾姆也「呋呋呋」地微笑着，

「昴的那种思考方式，蕾姆最喜欢了。——来做吧，节分」

「噢，很有干劲嘛。那么，再没返回前我们开始吧。节分也，作为游戏知识推广吧。」

抱起抬起头的蕾姆，站起来的昴，只跟蕾姆交换了下视线。昴点点头，

「喂，冰鬼（注：一种游戏，见断章）推广的时候也是这样，总觉得阿拉拉奇好像令人熟悉，有这样的感觉。时常和我家乡的印象重合」

「时常说起呢。有那种感觉吗？」

「虽然以前开玩笑一样说过，尊重民意投票决定总理大臣……是最近的事。愚人节和圣诞节也有类似的活动」

「举办的各种祭典也是，因为商业繁盛的关系得以举办……之类的」

「也有这些的关系，但感觉不只是这样……嘛，现在就算了」

确实是不错的居住国。跟蕾姆两人移居过来已经九年了。

卡拉拉基没有，广阔的胸襟和人情味浓郁的国风的话，这些也很难流行起来吧。至今仍为习惯关西弁和卡拉拉基弁。

「喂，豆子拿来了。要开始就赶快吧」

「哦，很有眼色嘛，我的儿子。虽然因为立场原因想否定，但我内心也难以掩饰的砰砰跳起来了。利格鲁小盆友~！」

「妻子比起儿子更担心以下老爸的品行不是强多了吗？」

从起居室拿来豆子的利格鲁，粗暴地分给昴和蕾姆一人一袋，自己也留下了一袋。

昴向面面相觑，用眼神询问该怎么办才好的两人点了下头，把手插进袋子并抓起一把豆子。

「简单。就像刚才喊得那样，『鬼啊~，外面去！福啊~，来我家~』这样就行。不，用鬼和福都留下的版本。去那边」

「嗯，豆子……鬼碰上了没事吗？」

「以儿子的立场我看到那边妈妈的眼神有点恐怖！」

「嘛，虽然这样，不能来真的啊。摆出恶魔（鬼）的姿势，轻轻地」

确认完所有流程，现在起节分——开始了。

相互面对面，手里拿着豆子，

「喂！鬼啊~，来我家~！福也~，来我家~！」

「嗯……gu，鬼啊~，来我家~！福也~，来我家~！」

「鬼啊~，啊，丝碧卡哭起来了！在哭了！啊，等下，豆子等一下（再扔）！」

咕噜咕噜地，同刚才一样围着屋子转着圈，开始播撒豆子。

昴元气地，刚开始害羞的蕾姆渐渐忘记了羞涩一边笑着，而利格鲁则不知为什么抱着丝碧卡这个不利条件自己拼着命。

「喂！鬼啊~，来我家~！福也~，来我家~！」

鬼是亲人，幸福在家中，这就是菜月家的节分情形。

得到身为鬼的老婆，彼此间得到有鬼的血的孩子，就这样享受着节分的新形式。——

这是，多么幸福的事啊。

豆子在屋里，走廊里，家的各处飞散。

只有考虑到之后的扫除破坏了气氛——一边想着扫除的事，现在这个瞬间不享受快乐才是奇怪的呢。

笑着，笑着，一边笑着，一边抛洒豆子。

和可爱的鬼们一起，幸福感填满了胸膛，播撒豆子吧。

鬼和幸福，全部收入，盛大的欢笑着，相爱着。

「昴」

忽然，蕾姆的笑容出现在昴的旁边。

视线落在昴的身上靠在一起，蕾姆露出羞红脸发烫的笑容看向昴，

「今天，今后也能幸福的抱着蕾姆，一直在一起吗？」

这样说着，一边把飞入怀中的蕾姆被昴抱住，

「——说过了吧。和鬼一起创在未来，是我一直一直长久以来的梦想。」

现在这个瞬间的幸福，从现在开始一直不断的幸福，确实在这胸中感受到了，

昴将无限的爱拥入怀里，轻声细语。

------

「……真是的，随便使唤人」

「啊——」

「想吃吗？但是，不行哟。说是豆子要到一岁以后才能吃。丝碧卡才零岁，也没有牙没法吃的。我就代替你吃掉吧」

「呜——」

「相当不满的表情啊……你那个表情跟妈妈向爸爸撒娇的表情一样呢。

这个，当丝碧卡能来回走的时候考虑一下家里的金字塔，简直不堪设想」

「啊呜，吧——？」

「里边？说什么傻话，现在还没有回来哟。吧节分、撒豆什么的作为借口，一定还在里面嘿嘿嘿呢。鬼去外面，啥的。真的啊，那不就是把我赶出来，和妈妈干些见不得人的事情吗」

「啊呜！ 啊——，啊嗯——！」

「怎么了，你也想给老爸撑腰吗！无论是妈妈还是丝碧卡，老爸又发出让鬼喜欢的费洛蒙吗？真是难以置信」

「啊~?啊嗯，啊呜。呜——」

「哈？为什么像是安慰我一样摸我的脸？不是的，我才不喜欢老爸呢。我是鬼里例外中的例外。就算全世界的鬼都被老爸迷住，我也能继续断言，我是反老爸派！」

「啊——吧——」

「啊——，可恶！在做什么啊！好了，走了，丝碧卡。稍微到附近溜达溜达，就算是那两个人

也该亲热完了吧。先说好了，才不是因为想得周到让那两个人……才不是在辩解呢！」

「阿哦！阿哦！」

「啊——，可恶」

「——今天也是，好天气呐」

-----

下面是作者的话

2月3日是节分。

祝大家，一年一度的重要的日子，过得愉快。

偶尔和鬼一起度过一天，也不错呢。

《完》

** 怠惰Ex3『Fortune·Rhapsody』
リゼロＥＸ　『フォーチュンロール・ラプソディ』

译者

哈啦呵的菊花

\\

\\

1

回到家的利格鲁在起居室看到的景象，立即掉头逃掉了。

我想抛开一切都豁出去的心情强烈地沸腾着，不过，这是一件很可惜的事情，这是我无法逃避的命运。

「呜呒呜呒？」

「……」

「呜呒呜呒---呜，呜---呒呜呒呜」

「呜呒呜呒的在说什么东西啊！你这是打算进行什么仪式吗！回到家里看到自己父亲嘴里塞着个棒状物的儿子的心情你考虑过吗！」

站着，口中依然塞着东西的父亲——昴向利格鲁的飞唾怒吼，对着那样的儿子的反抗态度，昴怂了怂肩

「呜呒呜呒...」

「那个『呜呒呜呒』给我适可而止啊！」

「呼呒呀...真是的，真是一个不解风情的混蛋啊。小孩子的时间就是这种冷淡的性格，总有一天你会后悔的。在以后的日子必须好好认清自己的事。对大人来说，在意他人的目光，自由就会被各种各样的……」

「爸爸说的话我十分不能接受！就算到了今年！你什么时候都自由自在的！你是有什么时候都不会介意他人的眼光的能力吗！」

（PS:御年三十路？求大神解释）年龄接近三十应该冷静沉着，但至今还不知道这样的菜月昴。

和利格鲁的同龄的朋友们一样全力顽皮着的大人。这时的利格鲁感到很羞耻。想要他能像别人的父母那样，冷静下来。

嘛，如果可以冷静下来的话，这会让人怀疑他生病了的。

「那么，这次是想出了怎么样的奇祭啊。」

「喂、喂，儿子。你，难道是超能力者吗？掌握了读取我的内心的技能了吗？.才不是那样，为什么我的行动是『祭典』……」

「我希望这至少是个有意义的活动！如果自己的父亲是没有任何理由，就口中含着粗大的棒状物跑出来迎接的家伙，超恶心的！说到底，是怎么样的目的才搞成这样的……」

一边唠叨的说着，利格鲁一边刚才为止斯巴鲁嘴里叼着的神秘物体拿走。接着，那个意想不到的柔软性和弹性，让露出惊讶的表情的利格鲁马上思考起来那个玩意的原形。

「……紫菜卷？」

「对了，就是紫菜卷啦！一脸眼馋的脸哟。我明白了，想吃的也可以吃啦。幸好，那是试做品。用尽心力的正式品另外准备了，所以肚子饿的话就开动吧」

「即使肚子饿，也不会想吃父亲长时间含着的紫菜卷什么的啊……丝碧卡和妈妈的话还好。」

「你，明明还才八岁而已就到父亲的反抗期的时期，是不是太早了？我还是那个年纪的时候，对父亲的敬意……尊敬了吗？怎样来着？」

「你不知道吗！话说回来，这次是什么的奇祭呀！到底是什么啊！」

利格鲁没耐心的追究着，昴耸耸肩地笑着。

在起居室的桌子上，白色的碟子里有几个紫菜卷，斯巴鲁表示是自己的制做的它们。

「决定了！仅次于节分的豆子的约定——那就是，惠方卷的活动！」

※※　※　※　※　※　※　※　※　※　※　※　※

「惠方卷，是吗？那是什么样子的节日呢？」

买东西回来的蕾姆，抱着迷迷糊糊的丝碧卡对昴的话歪着头问道。蕾姆的长长的青发被丝碧卡小小的双手握着，那是柔和的解脱的一幕。菜月家四人聚集的起居室，在堆积了的紫菜卷盘子边围坐着。

「之前的说明，实际上关于节分的事还是记住的吧？撒豆子，将那一年的幸福招入家中，将灾难撵到家外的活动。」

「当然记得了。没想到昴君有蕾姆赶走的打算……蕾姆的心，非常非常的悲伤。这份悲伤，是那么简单也不会愈合的。请和我约会！」

对蕾姆白费力气假装沉着的行为，斯巴鲁苦笑着。媳妇可爱的孩子气的撒娇。将其接受是好丈夫的义务，是幸福的权利。

「那个我什么时候都热烈欢迎哦。那，明天就是休息日，明天就出发吧。这么说起来，街道的末端的神灵殿，进行了漂亮的改装了的样子呢。」

「是的。因为昴君的工作的缘故，原意接受缘结礼物而移步而来的客人也似乎多了起来。丈夫的工作成果出色，蕾姆的鼻子也跟着变得很高了呢」

「那么就这样，对我和蕾姆已经连接在一起的姻缘线更加地祈祷吧。两个人的约会。什么！?丝碧卡的话没问题。妹控的利格鲁会好好地努力帮我们照看的。」

「昴君……我很高兴。愉快的期待着呢」

「回答一下我的话好吗！?」

面对话题脱轨进入约会计划的拟定的父母，忍耐到了极限的利格鲁爆发了。

对于突然大声叫喊的利格鲁，昴也已经完全习惯了，蕾姆也什么反应都没有。岂止如此，丝碧卡迄今为止也已经习惯了，连迷迷糊糊的影响也没有。

也就是说，利格鲁的呼喊在空洞的回响着——这样的状态罢了。

「利格鲁，太过突然大声的叫出来。从年轻的时候就哇哇大叫着，成为大人的时候会有突然脑血管爆裂的可能性哦。」

「吵死了（无路塞）！忍耐也会憋炸的！那就让我呼喊吧！」

「利格鲁，爸爸什么的是用嘴巴说就好使的人吗？.而且，在外面也绝对不能用那种态度说话哦。总是生气的人，朋友也什么的、谁也不来和你来往哦。像是父亲那样，不是对人极好的人是不能忍受的哦。啊，不过，和昴君比是绝对赢不了的，不要失望哦」

「我对被这样安慰的事情很失望啊！我到底做错了什么！」

被父母两个人打倒了，利格鲁让身体抛出，倒在地板上，当作床来睡着。看着进入了完全赌气模式儿子的相视而笑，和抱着完全睡着的丝碧卡的蕾姆，昴咳了一声重新说道。

「嗯，因为利格鲁主动请求话题的轨道修正，有关惠方卷的故事。立春前一天的撒豆子，是为了呼唤幸福，远离灾难的仪式。另一方面，这惠方卷也是节分的纪念日的活动，不过，关注这活动的人稍微有点少。」

「在同一纪念日里，是另一种仪式吗？」

「就是这样子。我的家乡在西方和东方的意见分歧有很多。惠方卷和豆子也是这种感觉。东边的是豆子，西边的则是惠方卷。但是，我想，好的事多少都能加入多少，所以会有两者都举行的想法。」

「是的，不愧是昴君。对于好的地方没有踌躇，很棒呢！」

为了不吵醒的丝碧卡，轻轻的拍着手称赞昴的蕾姆。就那样蕾姆把手指顶着脸颊，「所以」微微倾头。

「撒豆子的时候豆子是必要的，那么，惠方卷则是这张海苔卷吗？」

「撒豆子的时候，其实已经稍微做了各种各样的准备了。在明年的同样的时候，为了得到豆子而进行了交涉，我也准备了鬼的面具或鬼的裤衩等，更加细致地准备。」

为了最大限度的享受节日的欢乐，菜月昴的无用的行动力是没有限度的。

对于在没有必要的事情上燃烧能量的昴，蕾姆一直凝视着，暂时把考虑抛出脑后的昴慌忙地摇动着头。

「不同的不同。这次是一方说的是惠方卷的故事。没错，就像蕾姆说的那样，此次代替豆准备了的是这边的海苔卷。我所说的惠方卷，就是这个这个紫菜卷的啊。蕾姆，看到这紫菜卷的样子有什么想法吗？」

「这样啊。感觉非常的黑非常地粗大。」

「再说一次」

「——？非常地黑非常粗大啊？」

「我的老婆是坦诚的可爱又不自觉色情呢……」

深情感动的咬住昴蕾姆不明所以的表情的脸。

但不管怎么说，孩子的情操教育不相符的话题到此为止，昴用手指指着向棉花一样的惠方卷。

「那个粗紫菜卷寿司卷。不凑巧，『咔啦啦』（カララギ不知道是不是拟声词，请大神出来打我脸）的感觉的惠方卷到也不是没有的，所以自己制作了。做法是看来是简了点。」

「微微酸的气味，是醋吗？」

「醋饭啊。跟米很合得来我很喜欢。这次、生鱼块配合寿司也试着挑战了。那些暂且不谈，做法简单。用紫菜把醋饭和卷起准备好的七种食材好好卷起来。以上！」

「用七种材料是有寓意吗？」

窥视着五颜六色的配料被拥挤的卷入了紫菜卷中的蕾姆素朴的疑问着。

「既然有注意到呢，不愧是我的老婆！是的，那里也是重点哦。惠方卷是喜气的食物。在我的老家，可是有约定着驱使喜气到来的神明的故事，那七个福神被称呼。七人的幸福的神明七福神。」

「哎呀，真是喜气的神明啊」

「是啊，是喜气的家伙啊」.那可喜的神中七人啊，把七种配料放在一起用紫菜包在一起的东西，称之为是惠方卷，是作为用来呼唤幸福的食物的风俗。这就是一个惠方卷的故事全貌！」

把一只脚放上桌子上，极力强调的昴，蕾姆又细微的鼓掌着。

至此，在那里默默地听了利格鲁抬起了头。利格鲁的与斯巴鲁一模一样的凶恶的眼神更加尖锐，向相互欢闹着的父母的父母瞪眼。

「也就是说，这样的规模巨大骚动的情况，结果只是单纯的吃紫菜卷的活动吗？「.那样的事是夸大的……」

「你这白痴混蛋！」

「痛，痛！脑门好痛啦！」

对自大的说话儿子的脑门被打了一下爱的鞭策，昴弯下身子苦闷的把利格鲁举起骑在肩膀上。

「为什么突然要骑在肩膀子上！?」

「因为想起来了所以这么做了。确实是你所说的，稍微比起撒豆来显得不起眼的点无法否定。还有，刚才的说全貌了，其实还有一小部分的几点没有说明，对不起！」

「载着我脑袋不要低下来啊！快住手！要掉下来了！」

将头上慌张的利格鲁的生杀大权夺过，握在手中。昴绕着桌子四周一圈圈走动。蕾姆用慈母的眼神慈母的目光眺望着那样的父子的相互接触，

「那，还没有说明的事情是什么？」

「最初，惠方卷的惠方到底是什么啊？这部分的说明不够啊。顺便说一下，惠方的惠和恩惠的写法一样。某一年，好象有着运气适合的方向，那一边朝着对方吃才是惠方卷的吃法。」

「原来如此啊。恩惠的方向真是有意思的想法啊

「追加情报，在啃其方卷卷的时候，也可以用无言食。虽然我认为没有必要在那里拼命守护，姑且。虽然也其他的带着笑容吃法等诸多说法……但笑容是必要的。常言笑脸迎福嘛，而且吃到好吃的东西的时候笑容是自然的啊「.

昴咧着嘴自论叙述，蕾姆也高兴地微笑着。

「昴君，吃蕾姆的饭的时候也会有很多笑容呢」

「可爱的饭是可爱的媳妇做的。有爱的家人在我家，没有不笑的理由啊。占有了这世上的幸福的感觉！」

「蕾姆也觉得，两个人都占了……不，是有人都是占又了。」

「蕾姆……」

「昴君……」

「别在脑袋载着人的状态下调情啊！妈妈也是！有点怀里还抱着丝碧卡的自重啊！」

对于在儿子和女儿紧挨着的状态，还在亲亲热热的父母，利格鲁容忍度破裂。

什么话也听不进去是菜月家的风格，所以没有办法。

斯巴鲁把利格鲁放下地，和抱着丝碧卡的蕾姆坐了下来，一脸不高兴的利格鲁不理会昴和蕾姆，挨着而坐。（PS:哎呀，利格鲁越来越蹭得累了~）

蕾姆握住昴的手，把体重放在他的肩上，

「说起来，惠方……是恩惠的方向，不过，那个是哪个方向？昴君明白吗？

「不懂，那个完全搞不懂的。每年，那是怎么决定的呢。用风水的方法来决定的吧，不过，那种知识不是很清楚。」

活用召唤前的知识，在卡拉拉基成为了出色的活动策划人而活跃着的昴，现买现卖的话题还说得过去，碰到话题扩展到不知道的知识就无法应对。

那么，惠方卷的准备在关键的地方不知道该怎么办呢，昴苦闷的歪着头，歪头的时候看到利格鲁和丝碧卡的昴敲了敲手。

「对了。今年的惠方，让丝碧卡决定吧」

「哈？让丝碧卡怎么决定呢？你再考虑考虑。丝碧卡还这么的娇小可爱，要是从现在开始因为父亲的缘故而被菜月家感染上了该怎么办啊，想着都可怜。丝碧卡的未来的负得起责任吗？」（PS:臭小子，你也姓菜月啊。）

「你把丝碧卡的事想得多阴湿黑暗啊。」

昴的想法利格鲁强烈反驳，昴对鲁那样的利格鲁一边选择用安抚话语说服，一边考虑进如说明。

总之，昴的想法是这样的。

「不然怎么办？对我家来说，幸福的象征是什么。当然是蕾姆的存在就是幸福的象征，是你本身的天性是被玩弄角色的特征是我只能认为是神明赐予的命运的机缘，不过……」

「慢着慢着慢着慢着，这有不能置若罔闻等等部分啊，喂！」

「请冷静，利格鲁。对于昴君来说蕾姆是幸福的象征的话，对蕾姆来说昴君也是幸福的象征。妈妈对于那样的事没有误会，不用担心也不要紧。」

「要是在这里问题的话，那就不用担心的那么多。」

堵住沉睡的丝碧卡的耳朵，一边用怒吼的声音向父母到达了全新的高度。从出生的时候起菜月家中长大的利格鲁的潜力，在短短的八年的人生中，他的才能朝着一个极点的方向上延伸着。

——没错，天性中深深植入的被玩弄的角色特点。

「不是一极化，而是两极分化。」

「什么独白啊？！把话说清楚！！」

「嘛，也就是说对于现在的我们来说、丝碧卡是最容易明白的全场一致的幸福形式么什么样的。所以，由丝碧卡来的决定我们的惠方的方向，那不是就好了吗？」

「可恶，父亲这话不是没有漏洞缺点也没有反驳的余地的完美的意见不是吗……啊！」

「你一旦扯上和丝碧卡有关的事就失去所有的判断力了呢」

也得到了懊恼的抓挠着青色头发的利格鲁同意，这次的惠方卷的全部项目明确决定了。

紫菜卷已经准备完毕，就还剩下决定惠方的方向了。

「让丝碧卡决定的确是不错啦，但要怎样决定？丝碧卡说话都还不清楚。」

「对了。……让丝碧卡睡着桌子上面，醒来的时候开始转向了的方向作为惠方不是很好吗？」

「睁开眼睛醒来时……」

「最初朝向的方向……」

周密商讨后得出的比较粗略的决定法，蕾姆和利格鲁面面相觑。然后两个人一起的向丝碧卡俯视，陷入了沉思。

「总之，丝碧卡醒来的时候……就是分出在家里中最喜欢的人是谁的胜负，昴君是这样想的吧？」

「……是那样、吗？」

在意想不到的情况深深的动摇了，不过，说不定就是那样。

丝碧卡醒来最初看对方——那就是，无防备的婴儿最初寻求庇护最可靠的对方的。

不光是确定惠方方向的方法，同时是分出谁能赢得丝碧卡的胜负！

「嗯，虽然很遗憾，但是肯定是我吧。为家里赚钱的我，也就是丝碧卡会有伟大的父亲让自己不愁衣食住幸福生活的意识吧。虽然还是小宝宝，但这个聪明的孩子一定会想着决定成为我的新娘。」（ps:小女孩对父亲撒娇的常用台词，虽然我是很想刷鬼父的）

「请等一下。虽然无论如何都会灌输给丝碧卡，昴君的厉害之处和动人之处，不过，那个和现在的话题不同。果然，丝碧卡是喝谁的奶，在谁的胸口中最安静地度过的呢，那孩子的话肯定是知道的。所以说，这里还是觉得蕾姆最重要的。」

「老爸老妈你们都退下。对丝碧卡来说，最可靠的人什么的除我以外不可能有吧。在这个人界外的魔境的家中，只有我为了保护丝碧卡全力奋斗着中。丝碧卡，喜欢，我，绝对！」

三者都一样，丝碧卡的爱谁也不退让。

非常壮烈的对峙发生，为了一个女孩的伸手全体互相牵制对方。刚才的和谐的气氛是什么。

「——呜——」

察觉到那样的紧张的空气了吧，利格鲁怀中的丝碧卡很难受。眼看就要醒来的那样的婴儿的反应，三人面面相觑，

「惠方卷退避！」

「被子防御！」

「丝碧卡防御！」

昴把桌子上的惠方卷斯拿开，蕾姆将坐垫放置在桌面，利格鲁在上面将丝碧卡放下。

就这样，三人点头互相，各自向房间的三个方向分散，观察着丝碧卡。坐垫上的角宿一摇头，眼睛细小的手擦动。可爱啊。天使呀。

「————」

全体屏气，注视着丝碧卡最初谁的人的经过。

不久婴儿睁开闭着的双眼，用薄薄的眼睛看四周。

「阿呀ー」（婴儿的叫声。）

「赢了啊啊啊啊啊啊啊！！」

向着伸出手的人是利格鲁，胜利者的利格鲁膝盖跪在地上冲天上的喝采。

被选中的利格鲁是欢喜咆哮，没被选择的斯巴鲁和蕾姆彼此隐藏不住沮丧的样子互相贴近。（蕾姆和昴：蓝瘦，香菇。）

「嗯，冷静考虑的话，在蕾姆的心里第一的稳定的位置无疑就是我，显而易见的胜负呢」

「虽然丝碧卡是有说想当昴君的妻子，但那个地方已经是蕾姆不可动摇的位置。早已明白的结果。」

「好好胜利的余韵里前去！在孩子的面前生々しい话すんな！」（ps:不懂什么意思。反正是对昴和蕾姆自我安慰的吐槽）

将丝碧卡抱起了的利格鲁，带着妹妹向父母责备。

对于总是那样的态度，两人笑着，然后昴向着丝碧卡所选择的利格鲁——儿子站在的方向窥视着，

「利格鲁站在了玄关的方法吗。最后，我们的惠方就在那里。各自把自己的惠方卷拿上在玄关集合。」

「好的，昴君。自己的惠方卷是哪个？蕾姆的惠方卷也准备了吗？」

「蕾姆的家伙是这个。为了这樱花色的心的形状耗费很多时间。失败的作品已经在我的肚子里了。」

比平膨胀硬和突出的肚子的昴。在那个肚子上蕾姆轻轻地伸出了手，爱抚着。

「为了蕾姆而努力的昴君，真棒……」

「好了好的，你看你看，玄关到了哦玄关。我的那份适当就好，话说丝碧卡的份要怎么办？丝碧卡，因为长出来的牙齿还很小，吃海苔之类卡住喉咙不是非常糟糕吗。那里考虑了吗？」

眺望白色盘子上的紫菜卷，年幼的丝碧卡吃这样的东西而探查的利格鲁。但是，好像没有成为被哥哥所娇生惯养的杰作的样子。

对于昴来说，这次准备的并不好。

「尝试着各种各样的努力，虽然想把海苔软化，但试做也不顺利。很可惜，丝碧卡的份由我和利格鲁两个人分吃，七福神是这么安排的吧。」

「这么大的紫菜卷，第二根怎么吃得下啊。你到底在期待什么啊。」

「啊，是吗。我明白了，好啊。你这样为了丝碧卡的幸福，稍微勉强下胃的程度的努力也不能的哥哥这样就好。我会加油的。反正你，顶多你说爱的丝碧卡的话说骗人的……」

「我明白了！我要吃了！不如说我吃定了！」

「别生气就长角伸长啊……」

因为丝碧卡被引用的缘故，利格鲁短角突额，利格鲁粗暴的抓住两根惠方卷走向玄关，斯巴鲁和蕾姆笑着追赶。

※※※※※※※※

「————」

「————」

「————」

「啊ー」

只是沉默，支配着那个场合。

对于吃惠方卷规则有各种各样的说法，其中也还是一般流行的条件是「吃惠方卷的时候就不能说了」.

虽然说是吸收了幸福的是惠方卷的目的，但是也不知道说什么是吸取了幸福进来的一种解释，总之就是那样的感觉的原因不是吗？

因此，三人坐在门口开始吃起了惠方卷，朝着门的方向眺望着无言的，只是一味的「喀嚓喀嚓」的把惠方卷吃了。

「菜月先生，打扰了是吗？」

端坐在玄关，然后对面的拉门突然打开。

这样很落落大方的卡拉拉基的风格啊，和以前乡下一样的和谐邻居交往是这一带的常态。

家里的钥匙很少锁，理所当然的，附近的人也打开了门。听到的声音是住在邻家的中年女性。

「传阅板在传来了。所以说想要看的话...」

手持传阅板的女性这么说，瞪大眼睛看着坐在门口含粗大的卷的一家的姿态。马上女性点了点头，传阅板轻轻地放在了鞋箱上。

「啊啦，你们好像很忙的样子。好好地确认下，这是旁边邻居吗？啊拉~丝碧卡酱，好可爱啊~」

挥手向着丝碧卡笑着的女性说着「那么」低头走出去家了。无言的对那样的女性的挥手点头送行，家中又只剩下四人了。

「现在的画面啊！！」

不能忍耐了的利格鲁，切咬着惠方卷如此怒吼道。

「邻居的大妈为什么理所当然的接受了现在的景象啊！在其他人的家里，我们怎么会有怎样的看法呀？！回来看到父亲含着粗大的卷动摇了的我，像傻瓜一样不是吗！我变得奇怪了哦！」

「哼呒。冷静一点，利格鲁。你的心情我理解，但也有这样的事嘛。感觉到底有什么错的时候，错的是世界还是自己呢？.但是，那种时候大部分是自己导致的不同……」

「不不不！不对！奇怪的不是我！疯狂的是这世界！」

吵嚷的利格鲁的身姿，丝碧卡高兴地嘎嘎地敲手。

看着哥哥的大动肝火，对于丝碧卡来说是最好的游戏道具吧。这个年龄就已经知道享受消遣利格鲁的方法，将来很有前途的女儿啊。

「因为你在说话的原因，我也中断了，惠方卷都被口水泡软了。差不多就要一次成功的。虽然还没有糨糊，但以这种状态但怎样做？」

「那也太奇怪了吧！说起来要吃两根的话，总是在我和父亲处理这种事情哦。妈妈呢？」

「你是傻瓜吗，不可能会让蕾姆勉强去吃的吧。大量的碳水化合物的大量的吃下去在蕾姆的身材崩坏的话要怎样做。即使是生了两个孩子也完全不会崩溃的奇迹的产物哦。我和你发福的话就不同了。」

「呼姆呼姆……吃完了。并且，如果被说那样的话害羞的。」

红红的脸颊的蕾姆，顺利完成了自己的份儿的定额。

擅长贯彻初衷的程度是惠方卷挑战成功率很高的原因，所以没有坚强忍耐而分心的昴和利格鲁是失败的。

并且，剩下的惠方卷，还有大和下各一根。

「这方恵卷就是最后的挑战。今天和之前的准备，所有的一切都不要白费了，期待你利格鲁。」

「呜……差不多，很辛苦了。给我记住了，臭老爸……啊」

「Good」

竖起大拇指，向着努力挑战最后的惠方卷利格鲁。其间，已经有自己的完成了使命的蕾姆帮昴擦着嘴，

「说起来，这次的活动和鬼是没有什么关系呢。撒豆的鬼和各种各样的地方有关系，没有关系的有点寂寞啊。」

「啊，不是没关系啊。紫菜卷上的配料是七福神的说法刚才的说明了啊。而且虽然说不上鬼，红色部分是红鬼，青部分是青鬼那样的感觉啊」

「有一个蓝的部分吗……？」

「那里你看，把这青色的蔬菜换上了……严肃了吧？」

听到青鬼认为是说自己？蕾姆不满的神情。虽说如此，把青色外观的食物放入紫菜卷的是因为就没有办法。

蕾姆眯眼眼睛苦笑着，昴把最后的惠方卷在手中转动。

「不是七福神而是鬼的场合，吃下鬼寓意退治鬼想法啊。在这样的场合，果然鬼是一个坏东西的想法。」

「昴君的故乡，有什么仇恨吗？」

「过去关于打倒鬼的各种各样的故事有很多，嘛，我没有那种想法。哭泣的红鬼是我最喜欢的故事了，老婆也是鬼。所以和豆子的时候和一起」

「一起？」

在不可思议表情的蕾姆面前，斯巴鲁敲了敲膝盖。

「是这样啊，一起。吃了鬼，对我来说是和幸福在一起。倒不如说是我的血和肉，再也不放开了吧？」

「我会被抓吗？」

「我会抓住你的吧」

蕾姆的看起来很高兴的样子，昴则是一脸下流的样子。

在这样的父母一旁的别处，旁边的利格鲁无声的终于吃完粗大的惠方卷了。

太好了，吃完了！我吃完了啊！看见没，我的努力！」

「对不起」

「坦率的道歉啊！我明白了，看到了我吃下去了吧！」

利格鲁抱起丝碧卡，蹲下揉搓着妹妹的脸颊。为了安慰那样伤心的哥哥的，丝碧卡「呯呯」的敲着他的肩膀。

「嗯，那么，最后一个大黑柱让你看清了」

「是的，请给我看一下帅气的地方。」

在蕾姆的支持下，昴最后的大物――――――――――――BIG惠方卷的胜负挑战。

最后的一只把剩了的材料全部卷入了，直截了当的话，七福神的七配料的规则也保护着的话，名为惠方卷的凶器啊。

「啊嗯」

张开大口，惠方卷一口咬住，昴的最后的大胜负挑战。

已经无数次挑战失败了，昴的肚子接近极限。胃快要撑裂，不残忍的死去也是可能的。但是，对于男人来说，父亲也是有战斗的时候。

「啊呜」

「——！?」

那样的昴的大决战，正面是蕾姆进入的补刀。

她轻轻地微笑着，吃着昴的惠方卷的反方向。规则上，斯巴鲁也不能责备那个。在蕾姆的预料中，与斯巴鲁一起吃了最后的惠方卷。

得到了蕾姆的帮助，昴好象得到了万军的援助一样一口气前进。

既然借助了蕾姆的力量，作为男方就要更加努力了。比蕾姆稍微多吃一点，减少她的负担，吃完惠方卷。

就这样两个人的饮食前进，两位间的惠方卷逐渐变短，不久之后两个人的脸就接近了，彼此的嘴唇。

「是的，咚！！」

在快要接触到的时候，惠方卷的正中间，利格鲁的手刀来了。

角伸展，解放鬼之力的利格鲁的手刀的意味着，将海藻和米做的惠方卷漂亮地切断的力量绰绰有余。

惠方卷切断成两半，被吓到的利格鲁和蕾姆两人的脸渐渐远去。（PS:一看就知道是FFF团的资深团员啊。）

就这样两个人，嘴里咬剩的惠方卷吞下，对利格鲁追问。

「喂，利格鲁！现在，是迎接美丽的最后一幕啊！」

「就是这样啊。昴和蕾姆的，重要的要事的共同工作。利格鲁对爸爸妈妈友好相处不满吗？」

「有啊！必要以上的面前的友好关系的事不服的！所以我打算把那个行为化作言词竭尽全力传达给你！传达吧，这想法！」

「可惜，被弹开了！」

「弹开吧弹开吧！」

利格鲁放飞的想法昴平手打落的动作。然后作为代替，蕾姆抓住利格鲁生长出的角。

「啊——嘿呀」的尖叫的利格鲁崩倒。

「吃东西的时候削过来，不记得有教育过那样的孩子。另外，完全没有因为差一点，就差一步而被打扰而生气哦。」

「这样的，人类所没有的特殊部位弱点，是战斗民族的约定吗。丝碧卡角长出来后，让重要的人以外的人触碰，是不行的哦。」

崩倒的利格鲁回收了的角，一旁昴对抱着的丝碧卡说着。女儿是听了昴那样的话眼睛眨了眨，使劲的点了点头。

为那种事而长角，即使是家人也真是够了。

「不愧是丝碧卡。我家的至宝一样，让我幸福的心情。」

比起惠方卷的效果，相当的有效，真是不可思议的东西。

昴在丝碧卡的额头吻了下，女儿交给旁边的蕾姆。作为代替，担起四肢无力而苦闷的儿子的肩膀，一边「啪啪」的敲着他的屁股，

「那么，剩下就是收拾一下厨房，和讨论明天的约会的事了」

「是这样啊。时间还很充足，不过，晚饭怎样做呢……」

「已经吃够了，肚子已经很饱了。」

一边苦笑一边朝着客厅走的昴，蕾姆微笑着在身旁。

那样的一天，又是另一种幸福的形式。

\\

《完》

** 怠惰Ex4『菜月·利格鲁』
リゼロＥＸ　『ナツキ・リゲル』

译者

哭云子

\\

\\

1

「今年也要庆祝蕾姆的生日和节分！来，尽全力的帮忙、来过这美好的日子吧！」

迎来2月2日的菜月家，埋下了骚动前兆的根源。

在这种时候，常说出（骚动）契机是一家子的经济来源菜月昴，这在这次也没有例外。

「家族成员、想大家一起合力促成美好的日子。当然，你会帮忙吧，利格鲁！」

这样说着将食指举着、牙齿闪着光芒提案的是昴。

对于决定姿势昴的提案，将脸转到一旁用与实际年龄不合的老成面貌、「哈...」的溢出叹息。

在深深的叹息的是承袭母亲美丽蓝色头发、将短发分齐、遗传至父亲死鱼眼刚满十岁的少年、菜月・利格鲁。

在桌子的对面算着数学功课的利格鲁对在等他回答、左右踏着步的昴很快的抬头看了昴一眼。

「老爸又疯了……」

「这样讲也太过了吧！把说出来的奇怪的话直接跳越变成发疯也太超过了唷！而且这次、我的提案才不是脑子变得奇怪了也不是跳痛喔，不如说是爱满溢喔！?」

「我害怕的就是因为溢出的爱太过盲目、要做出什么事都不知道啦。在这个家出生被养育了十年，就算是我也差不多也学习到了。」

用冷冷的眼神和声音说着、利格鲁用额将靠近来逼问他的昴的额压回去。然后少年用「说起来」继续接着他之前说的话说道。

「不管是老妈的生日还是节分，留给我的印象除了内心的阴影以外没别的了。到底要我对扔豆子啊、吃惠方卷的奇祭的习俗有什么期待阿……」

「不要说是奇祭阿。不，的确做的内容直接看的话是奇怪的事情，但是我不是有好好解释过了来源还有意义了吗。实际上因为那个的关系我们家没有发生不幸的事件真是万万岁了喔。」

「我那个时候遭到的许多的不幸是？」

「那才不是不幸是日常。还有，要体认一件事的时候、光是在意事物不好的一面的家伙是不会成功的，而且还会累积压力喔」

「不要说的好像是我的错！本来都是因为老爸的关系我才会成为被害者好吗！」

生气的骂道，利格鲁两手撑着桌子快速的站了起来。然后像窥视般的指着窗外的大街。 

家门前的街道上魔法路灯的支柱上贴着很多的传单，上面的标题写着『节分要来了！』和记载着活动的通知。

除了记载着日期和活动内容以外也有偷偷加上了负责人的名字――、

「那个奇祭，把镇上举办的规模扩大到不能理解的范围的不就是老爸吗？在负责人的地方也有写着名字……我在学校一直被说到快羞愧而死的程度的说。」

「嘛~这就是所谓在显示身为负责人员的我的拿手好戏吧！什么~可以不用客气的自傲喔！说『我的父亲是我们家的英雄喔』之类的！」

「假如说没有在活动的说明里写要拿豆子扔我的话我说不定会这样说阿！」

把家中墙壁上也贴着的一张传单撕下，利格鲁指着上面刊载的事项。

记载着节分的风俗・目的・内容的下方有2月3日要举行的活动内容，那里写着要装着鬼的装扮在镇里被追着跑的代表者的名字『菜月・利格鲁』。

「不要没有经过同意就把儿子卖了！你是鬼吗！」

「鬼是你、我的新娘喔。嘛，不能让蕾姆做那样的事嘛。所以这里应该是『将泪吞下的儿子牺牲自己』...」

「你是鬼吗！不对、是鬼阿你！」

「不要那么生气嘛。也没有那么多真的很认真的扔豆子的人、代表只虽说是你但也有其他当鬼的人喔。我也有好好的帮忙啊。」

对于完全没有道歉表情嘟起嘴的昴，利格鲁因再说也没用而脱力。

在最初这个活动的内容即将广为人之前也像这样谈了好几次了。再加上每次利格尔都讲输昴、就这样拖到了正式举办活动的日期的前一天。

现在也无法变更或中止了。就算是被硬塞的工作不好好做也是不行的。
――虽然是有一定程度的常识还有劳碌命体质在、名为菜月利格鲁的少年的生活方式也是非常辛苦的。

不管怎么说，

「活动是活动、你也会干脆的接受吧。但，现在，我想和你说的是别件事。」

「……是老妈的生日，对吧？」

「没错」

听了边弹响指的昴的话，利格鲁用鼻子哼了声将脸背对昴。

不知道是什么因果，气氛沉重的活动和身为利格鲁母亲的菜月蕾姆的生日只差了一天――盛大庆祝母亲的生日、隔天绝对见到地狱的行程。

「照这样的心情，老妈的生日我也没办法快快乐乐的庆祝啦……」

「确实是太过满的行程了，但是可以过两天快乐的日子也是幸福的事。多想点好事啊。Positive
Thinking!（乐观思考）」

「……照这样的心情，老妈的生日我也没办法快快乐乐的庆祝啦」

「咦？既视感！?」

不是既视感也不是恶搞。

现在的对话因为根本没有丝毫的动摇利格鲁的心，所以结果没有发生变化也是当然的。

「我知道你因为节分快到了在紧张。但是因为不能因为那样的理由而轻视一年只有一次蕾姆的生日。这样蕾姆会很寂寞吧？所以要好好转换心情，我相信你做的到。
」

「――。――――。――――――――。――――――――――――――――嗯」

想要转换好心情还是花了点时间。

只是这样继续说下去话题也不会前进，似乎不管怎么样也不会让昴受到打击、结果还是利格鲁要乖乖的听话。

「然后？是讲到老妈的生日礼物的事吧？」

「没错。其实与其说今年是人生的一个阶段、不如说是结婚十周年啊。虽然没有确切的结婚纪念日、但因为难得所以想和生日一起庆祝。恩所以，原因是想要（让蕾姆）比以前都还感到特别。」

「嘛、那不错啊？说实在的、虽然觉得老爸做什么老妈都会觉得开心，但这个提案的话我可以罕见的大方赞成。」

「对吧？所以接下来才是重头戏。」

浮现像坏小鬼一样的笑容、昴像是在劝诱利格鲁做坏事一样对他招手。那个姿势让利格鲁的嘴巴弯曲，让他充分尝到不好的预感。

但是，对于踌躇的利格鲁、昴不断的不断的对他招手。

结果，利格鲁没办法的叹气，将脸凑向昴。

「为了这次结婚十年的庆祝计划，其实我准备了特别的礼物。」

「……嗯、啊、OK」

「为了今天，我用了我偷偷一点一点存下来的私房钱买的。是很厉害的东西喔，听了会吓到吧――我准备了宝石。」

「――哎、宝石」

虽说昴说了吓到吧而做好心里准备，但因他说的真的是应该要吓到的内容所以让利格鲁双重惊吓。

虽说基本上昴在做事情时总是在多余的尝试下导致常招惹不必要的混乱，但由现在的样子来看这次并没有迹象。

「宝石吗……」

现在想想，利格鲁的母亲菜月·蕾姆是为不怎么带装饰品的女性。

并非是因为顾虑家计的关系、纯粹是因为蕾姆本人的气质吧。

在家族中是最耀眼的、利格鲁对身为自身母亲的蕾姆以女性来说拥有非常美丽的容貌这点常常感到自豪。

但他对母亲平时没有特别喜欢戴首饰、对于饰品啊华丽的衣服没关连也没关系的想法、有些不满也是事实。

虽然没有到清贫的程度、对装饰自己却毫不在意的母亲。

但对于迷恋母亲到不行的父亲、虽说很火大但昴送的东西可以很确定的母亲一定会收。

因此，父亲要送母亲宝石饰品的提案、利格鲁是立刻赞成的。

「这个提案我觉得超棒的。什么嘛、有的时候做还是会成功的嘛、老爸。」

「喔喔！对吧！我是想做就能成功的那种型的……嗯？不觉得奇怪吗？怎么觉得有种你那边才是父母的感觉？」

「不要在意那种事拉！重要的是要送给母亲的东西吧？」

「嗯、嗯嗯、也是呢。嗯，没错！重要的是要送给蕾姆的礼物！嗯~虽然想着没错、但你的大赞成让我更有这是正确解答的信心了呢」

互相用拳头敲击、昴和利格鲁两人向对方点了点头。

之后利格鲁开始在意起要送给母亲的宝石实物了。因为，父亲的感官（センス）由做儿子的来看也不是能拍胸保证没问题的。

「所以宝石呢？因为是老爸，很担心会不会拜托奇怪的工艺师傅做出什么恶趣味的东西来。」

「不要一下子就动摇对我的信任啊！……但是、这个话题重要的地方从现在才开始喔。用心听着、儿子阿」

「咦咦咦咦……」

看着再度将声音压低、摆出认真的表情昴，利格鲁哀鸣出声。

当昴用非常认真的表情、声音从吊儿郎当的声音变的正经无比的时候是重点。绝对会讲出非常不好的话――利格鲁这十年来和父亲相处培养的信赖感，这次也没有背叛他。

昴在一脸有不好预感的利格鲁的耳边小声的说道。

「――载着要送给蕾姆的宝石的商人的龙车因为遇到纠纷所以没到镇里来。好像说要折返的样子，没办法所以现在要自己去拿宝石。」

「……那样今天来的及吗？」

「当然、会全力冲刺的。――只是，老实说，有点不安。」

两指互抵着，昴的视线和声调都降了下来。

看着他的样子的利格鲁扶着额、

「如果那么不安的话、之后再去拿宝石不就行了吗？比起生日当天没有礼物、老爸不在才会让老妈伤心。」

「那我知道。那我是知道的但是……若是这个生日礼物不在时间内赶到的话就没有意义了，我是这样想的。」

「那样的……」

只是老爸的任性而已、想这样说的利格鲁将话吞了回去。

难为情的搔着头的昴微微苦笑、在苦笑中蕴含着用话语难以形容的感情，只用眼神似乎就要直接传达给利格鲁了。

那是从内心深处放着重要事物的地方传来的一种淡淡的、特别又重要的感情――父母亲之间无法用任何事物取代的羁绊。

「――――」

再用嘴问的话就是不解风情，利格鲁感受到了这个。

然后他马上叹息着和微微苦笑的昴一样搔头、

「所以老爸将事情毫无保留的跟我说了，是想要我做什么啦？」

「你会听我说吗？利格鲁？」

「把状况变成无法当成没听见就可以了事的人可真会说阿！在我被当成不会解读气氛的家伙之前快点说拉！」

「真是帮了大忙了！」

利格鲁用很勉强的态度接受后，昴觉得幸好因而松一口气的抓住利格鲁的手用力上下挥动。

接受了昴的动作，利格鲁皱起脸的同时，昴保持着笑容说道、

「我去目的地将宝石拿回来。虽然打算不管怎样都会在生日的期间回来，但希望你帮我对蕾姆隐藏一下我不在的里由。就算说错话也不要把生日礼物的事说出来喔。惊喜会消失的。」

「……如果生日老爸不在的话、我觉得那已经给人十分的“惊喜”了」

「就算是那样、也（不能说）。我马上出门。之后就交给你了！」

话都还没说完、昴擅自将所有的信赖交付于利格鲁后、像用飞的一样抓了行李冲出家门。

昴保持着像风一样的速度冲出门外后，非常着急的向城镇的入口奔去――恐怕是要坐已经准备好的地龙去那个宝石商人的所在地吧。

「真的回的来吗……？」

从说了勉勉强强的昴的样子来看、用预测的大概比起来的及、来不及的机率比较高吧！利格鲁以以往的经验来看都会猜中。

被托付的是、在生日当天深爱的丈夫不在身边会变成什么样子的菜月家的防卫战。想想每日倾注在丈夫身上的爱、母亲动摇的程度并不难想像。

「这、不就要下血雨了吗……？」

利格鲁战战兢兢的等待外出的母亲何时归来的同时，也祈祷着飞奔出门的父亲越快回家越好。

※　※　※　※　※　※　※　※　※　※　※　※　※

应该说是幸运还是什么、听了昴外出的蕾姆的反应，与利格鲁想像的最惨发展相较之下平静许多。

「就是因为那样、好像是因为工作上的问题还是什么的。嘛、看嘛，果然还是有人认为只有老爸靠得住的样子……那种人存在吗？好像存在吧？嗯、假设存在，感觉上似乎存在的样子因此才会像飞一样的冲出门呦」

「为何直接听昴说了的利格鲁会这么不安的样子呢？已经十岁了，做不到留在家里看家、好好传话可不行喔。真是的。」

迎接买完东西和与邻居的集会完了、回到家的蕾姆，利格鲁向上述一样说明昴冲出门去拿宝石的事。

虽然不能否定这是商讨不足的说明，但听了利格鲁说的话的蕾姆看起来并没有因此而讶异或是非常不开心。

相反的则是对于利格鲁微妙的细节说明方式不是很满意。这是母亲意外斯巴达的方针。实际上似乎只有对昴很放纵，这是外面的人并不知道的菜月家内情之一。

不管如何，

「话虽如此，昴君出门了阿……真是可惜。今天的午餐本来想全部都做昴君喜欢吃的东西的说。」

将购物袋拿起来，蕾姆露出有些寂寞的表情。在这途中利格鲁的内心因为看见母亲的表情燃起了不能让老妈伤心的使命感。

就算是被硬塞的工作也会拿出干劲的男人、利格鲁悲惨的习性。

「老爸喜欢的东西啊。那是有点可惜……咦，没记错的话昨天也说了同样的话对吧？总觉得昨天好像也都是一堆老爸喜欢吃的东西……」

「是的。明天也是、后天也是、前天也是、在之前也是，都是做了昴君喜欢吃的饭菜喔。」

「就算是在家里也太清爽的偏袒了吧！」

听到每日、每晚都要做昴喜欢吃的饭菜的发言，利格鲁反射性的提高了音量。

但是听了利格鲁的抗议的蕾姆，说着「不、不」边摇头。

「请安心。昴君喜欢的饭菜，也是利格鲁和丝碧卡喜欢的喔。蕾姆会做你们讨厌吃的饭菜吗？」

「那是……真的要说的话是没有啦，全家喜欢的菜色都差不多是奇迹吧？少说对食物的好恶，每个人应该都不同吧？」

「那是因为从利格鲁还是小婴儿的时候，蕾姆就一直在利格鲁耳边一直念昴君喜欢的食物给你听、直到你被洗脑到喜欢上为止。」

「那是骗人的吧！?」

「是的，是骗人的笑话。这种事，是不能相信的喔」

冲击性的事实让利格鲁瞪大眼睛，蕾姆吐吐舌笑着说道。

然后母亲抚上自己和利格鲁同样颜色的长发。

「虽然说了很多昴君喜欢吃的东西，但昴君说蕾姆做的菜都很好吃不用担心也没关系。」

「那样是、嗯、很好啦。但那样的话特地做的菜的价值不就没了吗……」

「没有那样的事喔。虽然昴君都说很美味，但真正吃到喜欢的食物时声音和脸部的动作都会变的不同。比平常都还要可爱呦，呵呵」

是要因为观察细微而笑呢？还是应该觉得有点可怕呢？不知道该表现出怎样感情的利格鲁对在幸福笑着的蕾姆投以暧昧的苦笑。

之后蕾姆将背负着的丝碧卡交给利格鲁，提着购物袋走进厨房。

「真是的，大哥这么辛苦，你还真是轻松呢ー」

「啊ー？」

「才不是“啊ー”喔、真是。……真可爱啊~丝碧卡！」

利格鲁抱着丝碧卡发挥着笨蛋哥哥的本性，摩擦瞪圆双眼的丝碧卡的脸颊。被哥哥溺爱着的丝碧卡就算还是一脸不知道发生什么事的表情，对爱情还是敏感的。

尽情的对一脸觉得很痒的丝碧卡投入爱后，兄妹俩一起向厨房移动。厨房里蕾姆还在整里刚刚买的物品的途中，她将购物袋打开，把食物、调味料等等移到柜子里放好。

「然后呢？利格鲁。爸爸有说什么时后回来吗？」

「啊~那个~……呃、似乎会稍微花点时间的事？虽然说会非常快赶回来、啦。哎、也是有很急的理由阿」

对于背对自己的蕾姆的询问、利格鲁对自己多说了一些不必要说的话感到后悔。

不管是否是要让蕾姆转移她在生日和昴的事情上的注意力、利格鲁对自己挖了坟的事实哑口无言。

虽然这是利格鲁完全没自觉、『完全无法说谎的诚实性格』的毛病，但他发现自己不适合阴谋诡计，利格鲁瞬间将自己的嘴捂住。

丝碧卡学着兄长的动作用小手将自己的嘴捂住。好可爱，但现在并不是看傻的时候。

「是嘛。说不定会花点时间……」

「――――」

「伤脑筋了。需要急急忙忙的理由、蕾姆也知道的说」

没有转身、就这样继续整理柜子的蕾姆的发言让利格鲁的紧张感更加上升。

音调虽然和平常一样，但现在受到的是会立刻倒下的打击也说不定。

利格鲁知道的蕾姆是位坚强的女性，但也有致命性的弱点，那个致命的弱点明显的都是有关菜月昴的部分。

首先，用现在这种方式说话的话、蕾姆说不定已经查觉到昴是因为生日的事才跑出去的了。原本蕾姆本来就是会用心思也能理解气氛的人和昴不同，利格鲁注意到骗她或是对她隐瞒事情基本上是没有意义的。

「啊ー、老妈、那个……」

越是这样想，想要隐藏事情的感觉的精力就会越来越少。虽然身为诚实的人但对于隐藏事情的意志却很弱。

「其实老爸阿、那个、虽然他出远门了、但是不要觉得很他不好喔」

「――？这是当然的啊。昴君是为了工作才出门的，不会怪昴君。因为是为了家族在工作啊。」

「但是看啊、应该说这次的情况和之前不同……不是吗？」

「……嗯、果然。利格鲁也在担心啊」

看着一脸紧张、在左右游移视线的利格鲁，蕾姆眯起眼睛。看到蕾姆的反应觉得隐藏事情被发现的利格鲁在内心对昴道歉。

没想到决定闭口不说的秘密差不多过了三十分就败北。

接受这个丢脸的事实后也因为不用对家族隐瞒事情，罪恶感消失，心情也变得很轻松。

果然不能保持这样不行。一点也不冷啊。

「没关系的、我知道的。蕾姆也有一点担心。但是、因为是昴的事所以不用担心也没问题喔。」

「关于那个信赖度、因为我和老妈之间有些温度差所以没办法马上点头啦……那样的话、嗯、太好了。」

「是。虽然蕾姆也不知道正确的做法、但也是打算照着昴君的指令去做。不如说，将这个场合交给我这件事就是昴君对我信赖的证明、不能不积极呢！」

「……嗯嗯？？」

举起两只手做胜利姿势的蕾姆。

那个动作像是母亲的习惯的样子，能感觉到有些孩子气的姿势，现在不知为何心中有越来越不安的感觉。

现在的对话，看似有连结但其实没有。

利格鲁扭过头，「可以等一下吗？」对蕾姆伸出手。

「现在在说什么事啊？」

「――？那当然是在说明天节分活动的准备。因为利格鲁有城里当逃鬼的代表者这个工作。那适合的服装……因为昴君说了所以蕾姆已经准备好了。但就是还想要确认一下就是了。」

「――混蛋、我果然没好事！！」

原本没合上的对话现在合上了、利格鲁抱着的罪恶感现在也没有了、领悟到以前没有告诉他的事实而发出叫声。

被哥哥好好的抱着的丝碧卡学着一脸烦恼的哥哥「啊呜~」开心的笑着。

――数分钟后，在镜子前面站着的是重生姿态的菜月利格鲁。

「果然，昴君的眼光绝对不会错的。蕾姆非常佩服。」

「呜吧~?」

在因为感慨而深深点头的蕾姆的胸口、被母亲抱的的丝碧卡双眼正闪闪发光。

这显示了站在她们面前的存在的再现度是多么的完美。

「――――」

在黄色的布料上绣有黑色闪电图案的竖条纹裤子。和上半身一样颜色的羽织、角下穿着一部分是卡拉拉基制造的木屐。

手拿着金属质感的装饰纸做的棍棒、嘴里装着从服装出租店借来的牙齿、再将平常有点乱的头发往上梳，这样从哪看都是完美的鬼的姿态。

对于身穿古典的鬼装扮的利格鲁、蕾姆非常的钦佩、满意又开心。丝碧卡也对哥哥看起来很有霸气的穿着给与称赞的眼光。

被两位家人看着作为鬼爆诞的利格鲁看向倒映在镜子里的自己。

「好惨啊、这个！」

「哎呀、再说什么呢。这不就是完全照着昴君的想像图做出来的嘛。蕾姆也不知不觉得自卖自夸了呢。」

「这是鬼吗？应该不是鬼而是把蛮族搞错了吧？老妈才是，身为现在稀有的少数鬼族，被当成这样的形象都不会不爽吗？」

「所有人认知的鬼是什么样的形象，对于蕾姆和昴的存在来说是不会被左右的喔。没问题的，话说回来真是令人怜爱的成果啊……尤其是、那双眼睛像鬼一样我觉得很好。」

「只有这个部分像而已啊！！」

从父母那得到的身体、被给与的父母亲夸奖利格鲁反而有种恼羞成怒的感觉。

那个反应似乎让蕾姆觉得很意外，但心底感到真正意外的是利格鲁这边。

丝碧卡看着哥哥激动的样子红着脸笑着翻滚、像铃铛一样的笑声在加中回荡着。

鬼的背心、鬼的裤子、鬼的金色棒子、鬼的眼神、简直是完美的成品。

「不、还没喔。最后请拿出角来。那样的话一定会很完美。」

「讲、讲的和自己没关系似的……」

「绝对没有那回事。是我的小孩的事。我是认真的、真挚的在思考。」

对于投以怀疑眼神的利格鲁，蕾姆用很认真的眼神看着他说道。

被那个态度压了下来，利格鲁稍微皱了下眉，没办法的将意识集中在额上。

继承了鬼的血源、利格鲁的角可是有好好存在着。

但是，本来应该两支的角只有一支，如果照蕾姆说的话应该是因为血缘薄弱的关系。老实说，那件事情不是突然想到的。

但――、

『从你出生只能有一只角、真是对不起。 』

在很久以前母亲曾经道歉过、这件事在利格鲁的记忆中鲜明的留了下来。

没办法忘记那个时候的，一脸很抱歉的母亲的脸和声音。

对利格鲁来说，角的多寡并不是太大的问题。不管是一只还两支，角就是角。拿出角的时候身体的动作会变得很轻盈的恩惠，只有这个他才觉得有得到好处。

『好的、谢谢您』

在利格鲁像这样回答蕾姆时、似乎很寂寞的母亲总是微微的苦笑。

那个时候的事情应该是无力的关系。但从那次以来，在母亲面前没有勇气提道角的事情、一次都没有触碰到角的话题。

母亲的角也只有一支的样子。那件事是否有什么辛苦的回忆？

「――――」

将这样的感伤先放到一边，利格鲁将意识集中呼换体内的鬼之血，他的额头白色的角的顶端开始慢慢的伸长。

额头像是有奔驰的闪电的锐利感，从那里注入的力量让全身放松、手脚都能感觉到力量的膨胀。在这时候胸口最深的部分有种甚至会使人疼痛的冲动，这是母亲说的斗争本能在利格鲁脑中强烈的换起他的本能。

奇妙的高涨感和可以与之匹敌的斗争本能在摆脱束缚，利格鲁站在原地。

镜内是和刚刚一样的姿态的自己和很明显的生出来的角。从镜内映出的样子，为了寻求认同、利格鲁转身面向背后的两人――、

「怎样……」

「噗……非、非常棒、棒喔、利格鲁……噗呵呵」

「把刚刚到现在的矛盾全丢给我了！?」

在回头的途中，就看到强忍着笑意的母亲的样子。

蕾姆的双颊泛红，看着一身古典鬼装扮的利格鲁终于忍耐不住跪在地上喷笑。

在数秒前还在想着角有几支的事情是怎么了。

就只是长出角来就能笑成这样，内心冲突的时间就只是徒劳而已。

利格鲁脱力的垂下肩膀，好不容易才站起身的蕾姆为了转换心情将眼角的眼泪擦掉、

「总、总而言之，我觉得非常好。昴君也一定会同意的、我想参加活动的大家一定也会非常开心。――（笑）」

「随便啦、我要让把我选当鬼的大家后悔。从出生到现在第一次，我要解放我体内沉睡的野蛮斗争本能――」

「当然利格鲁这边做出争吵的危险行为是不可以的喔。如果有暴力冲突蕾姆会秉持着责任镇压。知道了吗？」

「从出生到现在第一次，我要解放我体内沉睡的野蛮逃走本能――」

先不管说法如何、微妙的改变了一些的利格鲁表明了自己的想法。

看到蕾姆因为那个发言而满足的点头，利格鲁叹气。

「实际上，看着镜子的样子和不合适是能懂啦……这个、真的好吗？鬼给人的印象不会下降吗？」

「做为种族的鬼已经和毁灭了没什么两样了。现在不用担心谁会因此讲什么坏话喔。顺带一提活动的最高潮，利格鲁是设定为渴望鲜血的凶猛鬼族的首领。节分活动的期间若是没有击退的话、就开始虐杀城里的人将城里化成地狱般的画面……是像这样的展开呢。」

「果然就像看到的一样是蛮族嘛！鬼的存在必要完全没了！?」

「做为概念上的敌人身分是有效的。虽然是跟昴君现学现卖的就是了。」

就算说做为鬼的尊严是题外话、蕾姆也不太想要继续这个话题。

鬼族几乎是灭绝状态了，这是以一般常识来说会知道的事，利格鲁并没从蕾姆口中听到详细的经过。

现在想起来，父母两人刚认识的时候和过去的事也没什么听过。

「……嗯，听了也只是会扫兴而已吧。」

记得有时候、父母――昴和蕾姆两人有种奇妙的违和感。

那有时候是给他们看功课的时候、不限于奇祭，知道不知出处的知识、这样的场面有很多。

这样窥探着两人过去的碎片的时候、利格鲁尝到了不可思议的牙痒的滋味。不管怎么说，这是父母和在把无法藏起的教育痕迹试图藏起来的意思一样。

两人大概、在那里受到了正规的教育。

想要因为那个事实而骄傲的儿子的心情和、对想要隐藏那件事却有些徒劳无功的双亲的举动感到反感，两方有不同的心情。

有一天，是否能问出关于那个话题的事呢。

「但是那似乎不是现在啊……」

不管怎样先把没有当做结论，利格鲁将自身产生的疑问先抛在后头。

并未注意到那个内心想法、蕾姆说着「来吧」边拍着手、

「为了预备明天的活动先整理衣服吧。虽然不能给昴君确认很令人婉惜，但就当作当日的乐趣吧。」

「真的要穿着这个到处逃窜吗……」

「利格鲁以外当鬼的人也穿一样的服装，所以不会觉得丢脸喔。当然，真正的鬼只有利格鲁就是了。」

将背心从手腕脱下、短裤和木屐换下来，利格鲁对明天的事感到非常的不安。

为了激励那样的利格鲁，蕾姆温柔的抚着自己自傲亲爱的儿子的肩膀、

「没问题的。利格鲁是蕾姆和昴君自傲的儿子。」

「但是、就算不说老妈、我也是老爸的儿子啊……」

「那不如说是令人安心的要素。换句话说、利格鲁身体里流着的蕾姆的血会不会扯后腿让人担心的担心的……」

「这是不适当的评价对吧？」

喜欢昴、尊敬他尊敬的不得了是蕾姆的坏习惯。

并不是自卑，但少说给自己的评价也太微小了。

「虽然从我的嘴里说出来有没有说服力我是不知道，但我觉得我的体内留着母亲的血一点问题都没有喔。不如说，刚才也说过的老爸的血我比较担心呢。除了眼神以外似乎也有坏的地方遗传了。」

「眼神超棒的。」

「但是有的时候只是眼神对上而已女孩子就哭了……」

「那只是因为还不知道男孩子的好的年龄而已。」

那个顽固相信的姿态、不管怎么样变成自己的事就会变的极端脆弱。

事实上那个姿态和昴有些共通的感觉，但利格鲁几乎没在昴身上看到脆弱的部分所以不能拿来说。

不管怎么说，利格鲁的感慨先放到一边、

「为什么老妈会那么不安，老实说做为儿子的我一点都不清楚……但事只要我能证明的话、就可以了吧？」

「咦？」

「我在明天的活动、会好好的、完全没有任何问题、完美胜利的话……就知道我身为老爸和老妈的孩子、不用任何担心了吧？」

「――――」

「从以前就很在意了。所以我一直想证明看看。」

看像张大眼睛的母亲，利格鲁坦然的断言道。

证明、将菜月・昴做为丈夫爱着、给菜月・利格鲁和菜月・斯碧卡注入母亲的爱情、一直对自己没有信心的女性菜月・蕾姆。她、是这个世界上，利格鲁最值得尊敬的女性这件事。

「和老爸不相衬什么的烦恼、这样一点碎片、尘埃也好根本不需要。」

「利格鲁……」

「我的、我的母亲是世界第一什么的、希望你能相信。」

希望没有自信、似乎很幸福似的表现但却一直缩小自己的母亲能看到。

所以利格鲁希望自己的母亲，能更坦荡荡的过日子。

希望她能和爱父亲、儿子和女儿一样、爱着自己。

因为，昴和利格鲁还有斯碧卡也都爱着蕾姆。

「就算是老妈自己、我也不允许把我的老妈的事情当笨蛋。」

就像突然激动了起来一样顺势说了出来，利格鲁马上发现自己现在陷入窘境当中。

用这一点也不严谨的装扮，在这样的场面自己到底是说了什么啊。

将鬼的四角裤和背心脱下，现在是只有穿着内裤的半裸状态。

在这样的状态下认真的诉说着什么，根本和喜剧没两样。长年下来，就算是想说什么就说什么，应该也要找更好的时机才对。

「啊ー、呃、刚刚的是、那个ーー」

不是这样的、想这样订正，但却没有说出口。

「――――」

不经意的，利格鲁的头被两只手围了起来、唐突的被抱住。

头被柔软的触感包覆、利格鲁对于突如其来的事感到惊愕。

然后马上注意到自己被母亲抱在怀里。

炙热的、在脉动着的母亲的鼓动在这么近的地方听着、利格鲁理解的瞬间脸红了起来。

现在已经是对着母亲撒娇会感到害羞的年龄了。像这样被触碰的事已经不知道过了多少年、本能的因为非常害羞而有了拒绝反应。

但是――、

「……老妈？」

「――――」

抱着自己的手臂在颤抖，看着母亲无语的模样利格鲁停止了想离开的动作。

然后叫着抱住自己的母亲，他注意到了没有回答的蕾姆的样子。

「……呜、呼、呜」

听到的声音是呜噎声。

那不是利格鲁听惯了的可爱可爱妹妹的哭声。和那个虽然非常像但那是利格鲁没听过的别人的呜噎声。

那是谁的哭声马上了解了，利格鲁一下子煞白了脸。

说不定是不经意的说了什么伤到了她的话也说不定。

如果是因为感情的关系顺势说出来的话语而伤到的话，那会成为无法挽回的错误。

所以利格鲁非常努力的绞尽脑汁从混乱的脑袋中寻找该说什么话才好。

但是他马上理解了那个焦躁和冲突是不必要的。

「――――」

勉强摇着头、身材细小的蕾姆好好的抱着比自己还小的儿子。

在颤抖的双腕埋入的感情并非拒绝也并不是伤心、只是只是深深的爱情。

被触碰的利格鲁比谁都还能肯定的理解。

所以，反抱住在哭泣的母亲、利格鲁温柔的轻抚着她的背。

「请你不要哭了啦、老妈。――被老爸看到的话我会被杀掉。」

「……那样的、做不到」

「为什么？」

「因为明明这样开心、眼泪却停不下来」

出乎意料居然是爱哭鬼什么的、看着和自己在一起应该有十年的母亲的模样、利格鲁叹息。

被母亲背着、丝碧卡看着母亲和哥哥拥抱的样子、微微歪头。然后丝碧卡用她有如细小枫叶的手，学哥哥的动作、开始轻抚母亲的背。

像是在安抚轻轻的在哭泣的谁，慢慢的慢慢的。

――兄妹俩人，在因为太开心而哭泣的母亲背后不坚断的持续轻抚着。

※　※　※　※　※　※　※　※　※　※　※　※　※

――结果、跑去拿宝石的昴在利格鲁和丝碧卡两人还醒着的期间都没有回家。

「因为还有明天的事情、利格鲁早一点去睡吧。明天要早起所以太晚睡是不行的喔。」

竟然，似乎将刚刚哭泣的事情忘却了一样、重回平常样子的母亲的话语。

只是，这样子说道然后朝正要向枕头棉被走去的利格鲁头上亲吻的蕾姆的表情、似乎有哪跟昨天不一样。

结果、没有发生和生日有关的事，但这也有和昴的约定。就不要惹事，之后的事情就交给父亲了。

说起来已经没有再说出比今天说的话还羞耻的勇气了。

已经够将忍了十年都没说出口的话都说出口了。

「――――」

看像魔刻结晶，将要快要换日期剩下的时间用手指算了算。

在蕾姆生日的期间内，昴是否能实现回到家呢。说实在的，为了要给妻子爱的证明多少会做一些傻事是利格鲁了解的父亲的姿态。

所以是这样吧。就算剩下的时间真的没剩多少了、也不用担心昴是否赶不赶的上。

然后实际上――、

「――蕾姆、抱歉迟到了！我回来啰！」

昴像是要跌倒似的飞奔进家中、是在剩五分钟就要换日期的时候――正确来说就算祝福的时间只剩五分钟、也算是有好好的保护约定。

「昴君、欢迎回来。但是、那么吵是不行的喔。利格鲁和丝碧卡已经在睡觉了、如果把他们吵起来太可怜了。」

「啊ー、抱歉抱歉。因为我也太过亢奋了……」

从犒劳到责难的蕾姆的话、可以听到昴慌慌张张道歉的声音。

听着脱下鞋子走进家里的脚步声、利格鲁在被子里翻了个身。

在躺到棉被理的几分内，虽然有好几次重覆从睡着到醒来、但担心的事情也都收拾完了终于能好好睡觉的样子。

想到明天要做的事、不能不像母亲说的那样要早一点睡才行。一直到今早都还在忧郁到不行才对的明天的活动、现在却有种等不及的感觉。

那一定是因为、明天的活动和母亲有约定的关系――。

「蕾姆、虽然太晚了很抱歉，但实际上不是只有这样而已。今天说事工作不如说是因为有私事所以出门了。非常重要的事情。」

「私事、吗？有什么特别的事情吗？」

「有喔。虽然你可能觉得不太特别就是了。」

微微歪头、真心似乎想不到事什么事的母亲的模样在眼前浮现。不事只有太小看自己而已、也有轻视自己的坏习惯。这样说起来，说不定不用隐藏礼物的事也说不定。

因为蕾姆就是那样的对自己的事无所谓。

「虽然只剩两分钟，但收下吧。――生日礼物。」

「生日……啊」

听到昴正式的话语，微笑的蕾姆的声音到一半就断了。

终于理解是什么事的同时的加与减、似乎正在困惑要呈现哪种感情的样子。

「――――」

恐怕是母亲接过父亲给的东西，困惑着游移着视线。然后迫不及待的将合子打开的应该是昴吧。

随着箱子打开的声音，能知道蕾姆看到里面的东西后小小的吞了口气。

「这是……」

「石榴石……虽然不知道要怎么叫、就那个吧。偷偷的为了今天存了钱准备的。不、其实、让我紧张了一把呢。明明不这天送到就没有意义，结果龙车在途中折返了。」

「――――」

在说着辛苦过程的昴面前，蕾姆保持着无语的样子。

注意到蕾姆这样的反应、昴微微苦笑的粗鲁的抓了抓头。

「总想要送你什么实体的东西。十年、得到了一起过的时间。是生日、也有节分、再一次跟你说请多多指教很相配吧？」

「……蕾姆这样真的好吗」

「嗯？」

「蕾姆这么的幸福、真的好吗？」

听到的声音颤抖着、利格鲁翻了个身、偷偷的朝两人方向看去。

虽然是隔壁的房间但透过半打开的拉门可以看到对面的房里的样子。

「生日……完全忘记了。因为、那样的……没有被祝福的资格、一直都是这么想的」

「――――」

「蕾姆将同一天生日的姐姐大人放着、像这样……明明知道、那是多么过分的事」

「嗯、什么都说出来吧。我会好好听的。」

「――呜。这么的幸福真的好吗、一直、这样的想着」

呜噎声，虽然在几小时前也听过同样的声音，但比起之前的蕴藏罪恶感的色彩更加浓厚。

从母亲的嘴说出的听不惯的单字，对那个有点感到吃惊。姐姐大人、暗示着过去的发言，但是、让利格鲁惊讶的是，超越儿子的想像充满危险、父亲和母亲沉重过去的这件事。

「还记得罪恶感、那是没办法的事我知道。我也、一样。」

「……是的。」

「但是、我并不觉得那样所有的事情都是不好的。就算知道是将错就错、知道是逃跑了，逃走后得到的东西我也不想当成是坏的。」

「……是的」

被这是平常无法想像的、真正认真的昴的声音吓到了。

能感觉到好几次点头同意的蕾姆的声音也和一直可靠的母亲、一直超级偏袒父亲的母亲有什么地方不同。

在那里的是共同拥有重要的回忆和羁绊、只是男女的两人。

「不管是住在这个城市也好、利格鲁和丝碧卡也好、因为发生了各式各样的事情才有现在的我和你。希望有个东西能当作连结着幸福的证据。那就是这个宝石。」

「――――」

「要是、你要接受这个还觉得辛苦的话、我不会说希望你马上将这个戴在身上。就算是放在一旁也无所谓。但是、只有丢掉请饶了我吧。我觉得那是、不能做的事。」

轻诉着、看着一歩、一步朝自己走近的昴，蕾姆什么话也没说。

昴怯生生地伸出手时，蕾姆抱住他的手腕就这样靠到他的怀里。然后抱着蕾姆，昴温柔的抚着她的头。

抚着她的头一阵子、将脸埋进昴胸膛里的蕾姆小声的说道、

「今天，利格鲁说了。」

「嗯」

「蕾姆是……世界第一的母亲」

「啊啊。不知道吗？」

「……是的、我以前都不知道」

对利格鲁对蕾姆吐露的话语、昴像是没什么事那样的回答了。

对于那样简单的回答、蕾姆的脸小小的绽放了微笑。

眼泪从眼角溢出、从白皙的脸颊上滑落。

和眼泪一起、她胸口内纠结在一起的、幸福感和罪恶感互相冲突中所衍伸的、用言语说不出的感情似乎被洗清了。

「之前、曾经说了吧。蕾姆在利格鲁出生时松了一口气。」

「――――」

「和昴君之间有了绝对不会消失的连系、所以安心了。想着成为了家族所以松口气了。我是个讨厌的孩子」

「我哪会讨厌阿、很普通啊。讲我的妻子坏话，就算是我的妻子也不允许喔。」

「……呵呵。那个、真的利格鲁也说了一样的话喔。」

「哎？那个家伙、说了蕾姆是自己的老婆？那也太恋母情结了、有点恶心吧……」

「不是的。虽然利格鲁有说过丝碧卡是自己的新娘就是了。」

「那家伙是恋妹情节的范本啊」

虽然被说着对他来说的不名誉的对话、但利格鲁还是沉默着任由对话从身上流过。

就这样、交换着回忆的笑容、然后长长的吐了一口气的蕾姆从昴的胸口内侧向上看向他的脸。

「蕾姆觉得是自己任意的、一方面的爱着。因为一直没有自信，所以才会拼命的展示喜欢你这点。」

「真是超级笨蛋呢」

「是的、是超级笨蛋。――那个被利格鲁说了。」

觉得有些害羞的蕾姆笑着、深吸一口气。

然后蕾姆抚上昴的胸膛、手轻轻的压着他的身体向后退，在两人之间隔了一步的距离。

「昴君、谢谢你的生日礼物。――可以帮我戴上吗？」

「……可以吗？不用急也没关系喔？」

「不是的。是相反。蕾姆早就已经到了终点。所以，想要拿到那个奖励想要证明而已。」

「证明？」

「――蕾姆是被世界第一的丈夫、世界第一的儿子和世界第一的女儿围绕着的、世界第一幸福的女人这件事。」

坦荡荡的，一直没有自信的蕾姆用自信满满的声音和表情说了。

那个内容让昴愣了愣、马上微微一笑。

笑着挺胸的蕾姆。看着妻子那样表现出的态度昴满足的点点头、拿起她伸出的手掌上的宝石、那是被镶嵌在项链上的垂饰。

然后、

「爱着你喔、蕾姆」

「是的、蕾姆也爱着你。昴君」

项链围上了颈子、红色的宝石在蕾姆的胸前闪烁着温柔的光芒。

看着红色的宝石、两人互相微笑、之后慢慢的朝对方的脸靠近――、

「――真是的」

看到这边作罢、利格鲁翻了个身背对隔壁的房间。

这之后双亲恩爱的举动如果看到的话会削弱神经的、不识时务。

父亲和母亲和睦的、幸福的生活着。这样不是很好吗。

而且在这之后也都不会改变、是菜月家的日常。

「――――」

横躺着、利格鲁看向和他睡在同一个房间的丝碧卡的床。

被采取了翻身对策的、昴说的所谓的婴儿床上睡着的丝碧卡、像是读懂了气氛一般没有在夜里嚎哭、打扰两亲的幽会好好的睡着。

今天是母亲的生日、又或许是已经换了日期了吧。

就算是如此、明日或是今日的节分――有些型式不同的、鬼为主角的日子。

对母亲来说不管是昨天也好明日也好或是今日也好、都是主角的一日。

在眼前最重要的是――、

「在节分活动，我必须要证明我是世界第一的儿子这件事。」

想到要证明的难度、利格鲁在被子里叹息。

但是那和之前沉重郁闷、情绪低落受到打击时叹出的气不同。

――在明日晴朗的天空下、怎么演出最棒的鬼这件事、抱持着健康的想法睡去了。

\\

《完》

注：按时间顺序建议阅读完本篇后去看动画全卷BD特典蕾姆if：https://tieba.baidu.com/p/5147477115

** 怠惰Ex5『Fortune·Fish Head Tree』
リゼロＥＸ　『フォーチュン・フィッシュヘッドツリー』

译者

翻译：Iti-Tan

赞助

HenTaiPP、故意切线阻、寒冰牛仔、黑白熊、zmy240

\\

\\

1

更新停滞了真抱歉！一个月之内还是不行！

等12卷和光盘特典的蕾姆IF结束以后，大概，能开了吧！

这个先放一边，每年管理的「节气EX」更新了。

撒豆子和惠方卷，再加上这次新用的『柊鰯』，节气梗差不多要用完了。

本来是打算在去年的EX就把节气梗用完的。

但人生不如意事之八九……

因此，这次的事情是从本篇第三章52话开始分歧的。

2月3日更新的故事是完全独立的，所以请一边享受以前的剧情，也关注一下这次的故事。

更新，再稍等、稍等一会。抱歉。

-----

虽说每年都是——打从心里认同了这是每年惯例的自己感觉真是讨厌，而每年惯例的那一天今年也在逐渐走近。

「看到日历上的日期越来越近，感觉格外地可恨啊……」

带着叹息的语气说出这句话的人，是一位脸上带有与他年龄不相符的疲惫与达观的少年。

他蓝色的短发随风吹起，一双吊梢眼目光贯穿世界，身着卡拉拉基传统的和服。

他正是，在卡拉拉基都市国家，第二都市的巴南被人歌颂为『节气之王』的，菜月·源（1）

（1）ナツキ　リゲル：看昴的名字不是取自昴星团（Pleiades
简称M45）吗，于是想了想他儿子的名字音译也太奇怪了。于是查了一下是参宿七，看了一下发现有个“和名”，上面昴星团的和名就是すばる，也就是昴。于是看了看リゲル的和名是叫“源氏星”，于是按照语感取了第一个字源。

「太丢人了……！」

『节气之王』把短小的手臂抱在胸前，哀婉般地仰天长叹。

从几年前开始『节气』这种行为扎根这座都市，每年每年都会以不同的形式向源袭来。他在这这一连串的苦难下成长，不知不觉间这位少年被推上了『节气之王』的位置。

现在源只要走在巴南街上，不管是不是节气的日子都会偶尔有小孩跑过来洒他一身豆子。他们似乎不懂这个活动的意义。看在他们是孩子的份上不和他们计较，而看到这一幕的父亲也会放声大笑出来。

总之，『节气』这个惯例已经成为了巴南不可或缺的一部分，而这对源来说也是——姑且不论心情如何——对源来说也同样是无法缺少的一部分。

虽然有很大部分原因是因为提出这个事情的人是源的亲生父亲，但最大的要因还是在于家人——『节气』是一个和鬼有关系的节日。

而继承了母亲『鬼』的血脉的源以及最受疼爱的妹妹，和鬼可是永远脱不开关系了。

因此「节分」，在源的菜月昴家里是不可缺少的例行节日。

所以不管是撒豆子——源是被撒的那一边——还是必须要沉默着吃完巨卷的惠方卷，又或者是要扮成鬼的样子在大街上逃来逃去，他都能接受。

可是，可是，啊。

「父亲，梗也差不多用完了吧……」

「——喂！源！你要在哪里装深沉到什么时候啊！我可是相当依靠你的战力的啊！快过来！帮忙！！」

就在源无力地垂着双肩，像这样发着牢骚的时候。

远处传来了呼唤源的声音，而且听起来情况还相当紧急，源不情不愿地转过头去。

——摩格雷德大喷口的水边，半裸的父亲正在拼命挥舞着双手。

他浑身上下湿了个透，平时日天的黑发完全垂下，变成了一起洗澡时候看到的模样。父亲把没用的上衣脱掉，露出了有一定锻炼的上半身，再度喊道。

「有一大群要来了！长老说的是对的！过了这个村可没这个店了啊！源！快过来！」

「知道了！知道了啦！」

在这里还是见死不救以保其身比较好吧，不过源结果还是用力挠着自己的头，向父亲那边拿走了过去。

源淋着从万里无云的空中降下来的水花，来到了轰轰地喷水不停的摩格雷德大喷口前。

——今年的『节气』，有着不一样的滋味。

「不对，惹我厌烦这点还是和以前一样啊！」

「源！源先生！?快点！把角弄出来！抓住渔网！抓紧了别放手！」

「吵死了——！！」

源听着父亲那不知是认真的还是在耍人的指示，站在大喷口的深渊前，定睛凝视着卷起了水涡的睡眠，确实看到了无数的鱼影子。

「————」

源用力抓住渔网的一端。额头上一阵炽热，意识在瞬间的空白之后，随之而来的是过度的爽快感。

身体汲取大气中的魔力使得力量无限地增长，年方十一的菜月源矮小的身躯里，存在着与他的幼小并不相称的鬼神臂力。

「唔啊啊啊啊啊——！！」

源的纤细手臂发挥出超常的臂力，一口把渔网拉了起来。利用细铁丝制作成的渔网，支撑住了鬼的力量，成功完成了任务。

「干得好！源已经成了！我们也不能输啊！各位，站稳了，一口气拉上来——！！」

「一————二————三！！」

紧接吹响反击号角的源，父亲——不，不仅仅是他。

和他一起，巴南里的有志同志也一同跑到渔网前，和源同样发挥出各自的全力，拉起渔网。鱼影为了逃出渔网纷纷掉头散去，然而它们已经身陷恶魔的陷阱。是逃不掉的，也不可能放它们逃。

「你们……也老老实实，为了「时节」牺牲吧——！！」

他们，是同样因为「时节」而被迫遭受不意苦难的同志。

其他人、其他大人的感情是不知道。但是，至少。

——至少，我会发自内心，予以你们同情，然后带你们一同上路的！

「唔哦哦哦哦哦——！！」

咬紧牙关，拼尽全力征收它们的性命。

紧握渔网的掌心十分炽热。从额头上留下的水滴也不知是大喷口的水还是自己的汗。

只是，绝对不会放开这双手，仅此而已。

——为什么事情又会变成这样，这要追溯到几天之前。

※　※　※　※　※　※　※　※　※　※　※　※　※

「那么，请问「zhong ruo」又是怎样一种活动呢，昴君」

在这个消息被郑重发表后数分钟，一名女性从厨房回到了起居室——她有着蓝色的长发，面带美丽而温柔的表情。身着浴衣，胸前还抱着可爱的黑发婴儿，挤进空间本就不多的暖炉来到昴的身边。

自不必说，这位就是源的母亲，昴的妻子，菜月·蕾姆。

在厨房收拾好午饭以后，蕾姆在不吵醒人的情况下轻轻地抚摸着吃饱了以后就开始午睡的女儿——菜月·真珠（2）的小脑袋。

她听到了父子间的对话，似乎也是头一次听说昴口中『柊鰯』这种奇怪的节日。这种事情在基本上无话不谈的菜月夫妻之间很少会有。

（2）ナツキ　スピカ：这个北极星和上面的源同理，不太想音译，于是查了发现是青龙的角宿，而在日语里则被称为「真珠星」……于是虽然这个二择很不爽，所以虽然名字变成两个字感觉破坏了和谐性还是选择看起来比较像女性名字的这边。

「这个问题问得好，蕾姆。所谓『柊鰯』，就是继撒豆子和惠方卷之后，节分计划的第三弹。虽然不可否认这个计划和以往的比起来会有些平淡无奇，但是相对的，在这种利益之类的地方毫不含糊所以推荐有足够自信的人前来参加」

「原来如此，不愧是昴君。确实，撒豆子和惠方卷都是，对女性和老年人来说参加起来可以想象会觉得很麻烦。收拾豆子，吃巨卷都感觉不会很开心……真是目光独到」

「啊，是啊。这么一说确实是呢。……啊啊，是的呢。这一次的目的就是这个！」

「是！那么，『柊鰯』是什么？请问要让源被怎么样呢？」

「喂，感觉突然好想让妈妈感冒一下啊……！」

蕾姆把『节气』、『源』和『受害』画上了等号的这句话，让源抱着头悲叹起自身的不幸。不过，昴对蕾姆的话说着「啧啧啧」摇起了一根手指予以否定。

「蕾姆和源都太心急了。这次的活动对源是零伤害。『柊鰯』只是一项简单至极的工作而已。无须担心」

「是，这样啊。……好的，明白了」

「为什么看起来那么寂寞啊？呐，妈妈，妈妈？」

「开玩笑的。别这么认真，源」

看到立马从一脸的寂寞恢复成了平时表情的母亲，源什么也说不出口，一脸意味深长的表情。在母子间的交流后，昴拍着手喊道「好了好了，注意这边」。

「一言不合就歪楼可算是菜月家的坏习惯。以后改过来吧。那么，关键的『柊鰯』，这比撒豆子还要简单多了。只要用柊树的树枝插到烤沙丁鱼（3）鱼头里，然后挂在玄关上就行了。很轻松吧？」

（3）沙丁鱼：鰯就是沙丁鱼，也叫鰛。

「沙丁鱼？」

「柊树？」

相对于满脸得意进行说明的昴，蕾姆和源则是各自歪起了头。

昴说的「沙丁鱼」和「柊树」都是他们没听到过的单词。不过名字就是『柊鰯』，听起来确实是很直截了当。（4）

先不管自顾自给出了解释的源，昴双手抱胸同意道「我懂」。

（4）虽然翻译的时候用了两种写法。不过在日文里沙丁鱼的汉字写作「鰯」，发音是一样的。

「如果是以前的我，肯定会说『糟、糟了！在这里不管是柊树还是沙丁鱼，都不存在的啊！』这样傻到爆炸的话，这可不行。我也是会学习的。我早就知道这边不会有了。所以方便点说，柊树就是树，沙丁鱼就是鱼。也就是说，这是个把树枝插到烤鱼上的习俗！」

「把树枝，插烤鱼上……这是，用来做什么？」

「说实话我也不知道……这个习俗是我脑子里知识海洋的最角落里挖出来的东西，能想起这个豆知识连我自己都想夸我自己……」

「原来如此，节分时候的豆知识（5）……昴君，太棒了！」

「这个，可不是我故意的啊！」

（5）节分……前面也说过了其中之一就是撒豆子。于是……豆知识……好冷……

纯真无邪的蕾姆打出的助攻让昴身受重创，在一旁的源则是念出了声。

把树枝插在烤鱼上——确实，和以往的奇特活动比起来十分独具一格而又出类拔萃，却也并不需要过多的身体活动。的确，不会给源造成伤害。

「那么……」

「对此，源总觉得似乎少了些什么……」

「别个人加上奇怪的内心独白啊！才不是啊！虽然是觉得作为老爸的主意还真是和平，但这个和那个是两码事。用树枝插鱼，不是正好吗。就迅速地解决吧」

「哦哦，真积极。你也终于承认，『节气』是菜月家不可或缺的习俗了吗。……免许皆传了（为父已经没有什么可以教你的了）（6）」

（6）作为一个音游狗，我很想保留免许皆传这个字眼。毕竟「皆传」，不过考虑到可能一般人很难看懂，还是放上了一般的翻译。

「是是，可喜可贺可喜可贺。那么？要准备什么？」

「等、等一下。别看我这样，好歹也是『巴南文化振兴会』有头有脸的人物。从去年开始就煞费苦心做好了准备」

昴故作有远见地笑着。对此源感叹地发出了一声「诶---」。

『巴南文化振兴会』，是不知什么原因接受了昴提出的各项谜之活动，为了在卡拉拉基内扩张，进而有一天化作世界规模的组织而日日夜夜做着无意义的努力的一群人。

而振兴会不知道为什么还很为人所能接纳，有关人士的数量增长得比源想象的还要快，这让源感觉世界在崩溃，不过这又是另外一回事了。

总之，有『巴南文化振兴会』的协助，的确是没必要借助家里源和蕾姆他们这些少数精锐的力量了。不管做什么，准备和活动人手是最重要的。

去年整座城市撒豆子的活动，也是受到了周围人的广泛协助才得以举办的。

「所以，我从去年开始就虎视眈眈，拼命寻找和沙丁鱼柊树相似的鱼和树。虽说要找到完全相同的很难，但也要准备尽可能相似的以表诚意。万一效果改变，祝福变成了诅咒就麻烦了」

「这么说，听起来是找到鱼和树了？」

「正是。还就在身边……而且，很容易抓到」

于是，昴离开暖炉伸手摸向自己的腰际，缓缓抽出插在裤子上的东西，然后，在暖炉上展开。

那是地图。那是适度精细地描绘着卡拉拉基都市国家的地图，上面混着相当随意的手写记号，右下角有着『菜月·昴』的签名。

随后，昴指着地图正中的一点——，

「目标是摩格雷德大喷口，在这里我们要的鱼大量成群。而且，按照计划克拉格雷尔移动森林也会来到这个在这个时候来到这个喷出口。我们相信长老的情报，在这里埋伏好，然后将其一网打尽。——这就是，菜月家这次的任务」

「别理所当然的把我们也牵扯进去啊！！」

「啊！源，这样可不行！真珠要被吵醒……啊、啊——」

「唔哇哇哇哇——！！」

源对一脸骄傲的昴怒吼道，而蕾姆慌忙想要阻止他的时候一切已经迟了，被强行从睡梦中撬出来的真珠哭声传遍整个屋子。

——这就是『fish head tree作战』的前日谭。

※　※　※　※　※　※　※　※　※　※　※　※　※

——来谈谈摩格雷德大喷口吧。

虽然和星星之海，物见之台，乐园之端（1）没什么特别的关系，摩格雷德大喷口作为卡拉拉基都市国家的国土，是罕有的环境舒适的地方。

原本，卡拉拉基都市国家风土最为显着的特征就是遍布全国的沙漠地带，以及众多的虽不及沙漠却也自然环境欠佳的干燥地带——这么说来，和自然环境舒适的鲁古尼卡、波拉奇亚帝国不同，是个和万年冰雪覆盖的古斯提科王国在别的意义上环境险恶的国家。

（1）星の内海、物见の台、楽园の端：梅林的宝具语音。我不玩FGO，姑且查了一下有没有官方翻译……

因此，卡拉拉基在被统合为都市国家以前，各自的小国都在争夺肥沃的土地。虽说那种情况自从国家被一名英雄统一之后就没有发生，却也不意味着自然环境有什么戏剧性的改善。

贫瘠的土地仍旧贫瘠，就是肥沃的土地也没法说是很肥沃的环境，在这种情况下人们必须要摸索出某种生存之道。

既然没法依靠自然环境，最终卡拉拉基都市国家选择的生存之道，是推进全国的商业活动——贸易发达的卡拉拉基都市国家就此成型。

那么，事情回到摩格雷德大喷口上。

在这样的卡拉拉基都市国家里，之前也说过摩格雷德大喷口附近的地区环境堪称特殊，但具体要说哪里特殊，就是仅有这块地域，会定时有降雨。——而且，间隔绝不会发生变化。

光是这点，对卡拉拉基的国土来说就很是珍贵。

摩格雷德大喷口一眼看去像是一片宽广的湖泊。但是实际上它并不是湖泊，而是一个通往大地最深处，直穿最底部的巨大空穴，而填满这个洞穴的则是『大瀑布』。

而这个大瀑布会定时将水喷上天空，把雨水撒向数十千米，有时数百千米内的一圈地盘里。多亏这个，摩格雷德大喷口有着附近难以想象是在卡拉拉基境内的绿色生态，是国内的宝地。

第四都市「弗斯米」是离摩格雷德大喷口最近，最受其恩惠的都市。

而这次，昴率领着『巴南文化振兴会』在弗斯米都市长的支持下，开始挑战摩格雷德大喷口的『沙丁鱼抓捕任务』。

有传闻说这次协助的背后，是弗斯米见巴南近年因为活动的关系业绩步步高升，所以也想来分一杯羹。然而这件事不仅没有传入孩子的源耳中，也没有传入大人的昴耳中。只是大人物相互牵制的闹出的事情。

话说的有点多，不过这只是开头——是在摩格雷德大喷口奋斗的源下，『巴南文化振兴会』战斗的概要。

——也就是说，物语是从这里开始再度起步的。

※　※　※　※　※　※　※　※　※　※　※　※　※

「唔哦哦哦哦哦——！！」

渔网扔进摩格雷德大喷口，成功捕捉到大量的鱼影，鬼力全面开放的源全力叫吼道。

好漫长，这场战斗是如此的漫长。在抓住网以后，到现在感觉时间过得越发缓慢，源拼命地拉动着网无暇顾及其他。

以前，他和昴一起去钓过鱼。

不管是昴还是源都没有什么钓鱼的兴趣，源只是被突然想要做一些亲子间交流的昴恳求，迫不得已才带昴去在学校里传言甚广的钓坑的。

那个时候，不知道为什么最后演变成源和钓坑里的主人互相扯锯的状况，和前来抢夺钓饵的湖主进行了两个小时多的格斗。不能小看鱼。它们的生存本能，有时候会绽放出比身躯比自己大上数倍的源还要耀眼的光辉。

而这些被缠在渔网中的银色鱼儿也是同样——不对，单独一个再怎么说也不可能和湖主比，但数量差太多了。

无数的鱼影，数百，或是这数倍，甚至是超过这个数量的生命正在闪耀着，其惊人的力量让咬紧了牙关的鬼都没法拿到哪怕一步的优势。

「加油！加油，各位——！！」

「一二！一二！一二！」

就在拼命的源身后，昴和同行的振兴会的大人们也同样在拉着渔网的边沿。他们那不知道是认真的还是在搞笑的声音是让源大大走神的主要原因之一。

——话说，姿势没摆好。身体能再压低一点啊。啊啊，但是利金斯先生会腰痛所以不行。话说，我为什么要来啊。在家休息不好吗。

「总不能只让你们在这里耍帅啊」

「利、利金斯先生……！」

「嘿嘿，我这才正要发挥……唔啊啊啊啊！！我的老腰！！」

「利金斯先生————---！！」

利金斯刚露出深藏不露的微笑，改变了姿势，就脱离了战线。有一就有二，紧接着一个又一个大人被迫退出了战局。

理由基本都是败给了年龄。

振兴会的成员大半都是想要通过活动和更多年轻人接触，迫切希望能够加强地域间羁绊的老年人。

而即便要从中选出最年轻的，平均年龄都会将近六十。

这在当下搏命互争的战场上，就意味着半个死人。

「不行！撑不下去了！长老！快带着伤员离开！在这样下去会出现死人的！」

眼见局势险峻，昴做出了苦涩的决断出声吼道。

如果受伤的人就这么死掉了还好，若是还活着就必定会需要人来救援。要让伤员远离这里需要两个人。也就是说，一个人倒下了就会导致再减两个人，局势陷入负面的轮回，终于战线完全崩溃了。

事到如今，仍能正常抓住渔网的只有源、昴，再加上长老三个人而已。

「怎、怎么可能，这场战斗居然会演变成这样……对不住了，源。我的想法还是太天真了。还把长老也卷了进来……」

「没必要在意。都认识这么久了，知道迟早会有这一天的」

听到昴痛苦的低吟，被水湿透了白色毛皮可爱程度仍不见减的长老摇摇头——他是幼犬人查莫夫先生。

放出豪言壮语说要游历世界，制霸七个沙漠的查莫夫长老就是提供了这次会有目标鱼群经过的情报的人。

作为提供情报的人，他也承担起了其中的责任参加了打渔——，

「但是，遗憾的是……我，似乎，没法和你们一起，走到最后了……」

「等、长老？长老——！」

回过头呼唤着查莫夫的昴瞪大了眼。连带着源也转过了头去，从视野里消失不见的查莫夫让他震惊不已。

查莫夫身为幼犬人，身高不过五十厘米。这在摩格雷德大喷口的激战中，不过和挣扎的鱼群激起的波浪高度差不多——他，直到最后都陪着他们，中途到底差点被冲走了多少次。

在这个瞬间到来之前，没有让周围任何人注意到这份挣扎的顽强，正象征着从他外貌上看不出来的冷酷生活方式。

「已经、已经、不行了……」

长老——自从年幼的时候，就来过自己家里无数次，早已熟识。

看到查莫夫从战线上退下，源的身上突然失去了力气。额头的角不再发光，少年的身体化作正常的人类，变回了十一岁的男孩子。

在鱼群生命的光辉面前，这就相当于举起了白旗。

「——源，你已经做得很好了。退下吧」

「……老爸？」

正在源打算放手的时候，身后的昴对他说道。他的意识被昴的声线所感染，一瞬间，犹豫起是否该放手。

回过头，昴全身都已经湿透，即便如此，仍旧用网缠着自己的手臂，出于绝对不可能放手的状态。昴对源点点头。

「这是我的责任。所以，我会留到最后，你就回去吧。回去，然后把倒在那边的长老也带回去」

「但、但是……已经不行了！放弃吧！渔网之后再陪一个吧！」

「我才不是因为心疼渔网钱才不放手的啦。我说过了吧。这是我的责任。『巴南文化振兴会』的工作，或许你会觉得很不好意思，但这也是我的工作。——做父母的，怎么能在孩子的面前放弃工作啊」

「————」

昴的话让源说不出话。

这份意志很出色。出色到让人都没法出口质疑。

但是，没有胜算。在那一大群鱼面前就算想拉住也是没用的，连主力的源都不在了，昴一个人又能做的了什么。

不可能的。这场战斗，已经——。

「而且，你太小看人了」

「老爸……是说我小看了爸爸吗」

「我就算往好了看只是个废柴的大人所以无所谓。但是，你小看了的人说的不是我。……是蕾姆」

「妈妈？」

为什么，会在这里说出蕾姆的名字，这让源很是疑惑。

把至今为止的拉锯战看下来就能知道，这场以摩格雷德大喷口为舞台的打渔并没有蕾姆的参加。当然，这次是以全家旅行为名义来的弗斯米，但是，蕾姆和真珠并没有来危险的打渔这边，而是观光旅行一样地去『克拉格雷尔迁徙林』那边摘树枝了。

『蕾姆和真珠两个人会好好玩的，昴君和源注意别把膝盖擦去了哦』

相互祝福对方战斗顺利——虽说略微欠缺了些紧张感，但在那样的对话之后，很明显母亲和妹妹并不在这里。

因此源觉得昴不过是在用荒诞无稽的牢骚——。

「——不愧是是昴君呢，真了解蕾姆。好让人害羞」

「——！」

正打算说些什么劝昴放弃的源听到这个声音吓得一跳。不应该听得到的声音，不应该在这里的人，却悠悠然地在这里现身了。

蓝色的长发被简单地缠起，浴衣的袖子为了不碍事而被卷起，如此来到昴的身边伸手拉住渔网的女性——正是蕾姆。

她的登场让源哑口无言，昴随即开口一笑。

「抱歉，蕾姆。情况很危急」

「是。昴君只要一离开视线范围肯定会变成这样。这么一来，不能让昴君离开蕾姆视线的理由又多了一个」

「这份爱好沉重！但是，帮大忙了」

夫妻齐心协力抓住渔网，蕾姆咬紧牙关双手用力。仅仅如此，就十分干脆地把将要输给鱼的渔网给拉了回来。

但是，即便如此，劣势还是劣势。即便这时候再加上源，也没法改变这个劣势。本来这个战力差距打从根本上就不可能扭转。哪怕母亲奇迹般地加入战局——，

「源，抓住这根绳子，准备好」

「诶？」

「接下来，昴君和蕾姆……爸爸和妈妈要两个人撑住网，源注意不要错过时机。——这可是，让真珠看看自己哥哥帅气一面的好机会哦」

源一脸疑惑地按蕾姆说的，没有撑住渔网，而是抓住了和渔网相连的绳子，开始仔细环视起周围。

「现在正是体现男人的时候。这可不能输啊」

「等、长老……！」

「我也来了……！」

「利金斯先生！还有其他的各位！」

就仿佛要抹去担心双亲撑不住的这份不安一般，聚集而来的伙伴们再度一齐抓住了渔网，用气拉了起来。虽说只能算半个死人，但只要还有一半活着就有意义。现在正是时机。

「一二！一二！」

「一二！一二！」

源在口号声的干扰下拼命瞪大了眼。在大人们吵死人的声音里，突然有什么——对，仿佛听到了地震般的声音。

这或许是摩格雷德大喷口要喷水的预兆。——不对，并非如此。地震的声音并非从喷口内，而是从外面传来的。

那是——，

「克、克拉格雷尔迁徙林……！」

为了水源而迁徙的克拉格雷尔迁徙林——这片绿色，随着地震声，尘土飞扬地向这个方向行军过来。它们就这么打算从大喷口的旁边路过。

源慢了一拍地瞄准了其中最前方，行军在最前头的那棵大树。

「源，就是现在！」

母亲的喊声，无可置疑，源立马把绳子头上的绳环扔了过去。

绳环套住大树的粗大树枝，扯动起渔网。

——鱼群生命的光辉，在大自然的面前终将暗淡。

※　※　※　※　※　※　※　※　※　※　※　※　※

星之内海以下略。

克拉格雷尔迁徙林是在卡拉拉基都市国家的苛刻环境下，以摩格雷德大喷口的水源为中心产生的一种特殊神态——是对不扎根于地下的森林的称呼。

已经说明过摩格雷德大喷口喷出的水是这片地域的水源，但定期必定会喷出去的水，灌溉到的土地范围却不尽相同。

其中特别会受到风的影响，在季节风的影响下有些土地的降水量就变得稀少。人或是动物这样的生物还能看情况进行调整，但是傍水而生的植物却不行。而当然地，对于一旦水没有及时送到就会枯死的植物们来说，摩格雷德大喷口的水直接关系到它们的性命。

话虽如此，植物们却无从诉说，它们并没有嘴。因此适应环境的生存能力在此起效，树木们最终完成了进化。

「既然这片土地上水分不足，那移动到有水的地方去不就行了吗」。

而就这么诞生的迁徙林——最开始发现的人类为其取了『克拉格雷尔迁徙林』这个名字，这些富有活力的树木们，以摩格雷德大喷口水洒到的马高利亚高原为中心，一年到头，全年无休地不停地移动着。

也不只是是不是因为如此生命力旺盛的关系，迁徙林的树木作为木材品质很高，但是它们不会安札在一处不动所以采集起来也很困难，再加上若是挡在前面会被毫不留情地碾过去，所以它的伐木业以玩命出名。

迁徙林的这种特性，这次发挥出了正面的功用。

人力无法战胜的话，就借用大自然的力量。

「迁徙林前进的方向就是大喷口，所以似乎能够慢慢和昴君你们汇合的样子，一开始就说过了」

「如果蕾姆看到离开渔网的人在帐篷那消沉的模样，应该会注意到然后过来帮忙的……这就是我真正的作战计划」

「作战计划？哪里计划了？这不完全德式背摔扔给了妈妈吗！」

「说的真难听。嘛，总是结果还是爱的胜利吧」

「昴君……」

「刚才那句话有那么好吗！?妈妈太宠他了啊！」

打渔大丰收的一行人走上了回家的路。

在路上，一家落汤鸡正在讨论着这次的胜因，但源完全无法接受。

蕾姆的参战，以及让克拉格雷尔迁徙林来拉渔网的计划收效颇丰，把大喷口里的大量鱼群（昴将其明明为如鰯）拉了上来。

事实上在那之后，这次又是疾走的迁徙林把渔网连带着鱼也一起顺手牵羊了，为了追上迁徙林夺回渔网又是一场鏖战，这里就忍痛割爱跳过吧。

总之，平安拿到了鱼，柊树枝也利用从迁徙林中砍倒的一棵树确保了足够的量。

就这样，昴口中的『柊鰯』至此已经准备完成。

「这不是比撒豆子和惠方卷还要过分了吗。甚至还出了一趟远门，搞得这么累」

「啊啊，长老他们甚至都命悬一线了。不该做不习惯的事的」

「真是的，太吃苦头了莫。以后，绝对不干这种事了莫」

源叹息道，昴也苦笑着表示同意。

在两人视线的前方，查莫夫正在优先地咬着甜叶子。

幸好，在那样大负担的工作下没有人受伤，受害数为零。所有人都沉醉在这片空气中，腰痛也由蕾姆的治愈魔法痊愈了。

于是全员意气昂扬地凯旋，之后应该就是讨论鱼和木材的分配了——，

「那边就不归我管了。我们就一家人来分享一下这次旅行的辛劳吧」

「是的，这就是旅游的醍醐味呢」

「旅游的醍醐味是诉说旅途的艰难来着……？」

源对这微妙的常识感觉到了危机，正逗着最受宠的妹妹以作为对自己跨过了九死一生的奖励的他一脸不悦。

年方一岁的真珠最近开始会自己走路了很是活泼，而且在极少时候会叫源「哥哥（にーに（1））」简直天使。

（1）姑且给个读音感受一下，这个发音是（ni---ni）。

「叫得一声是哥哥，这可是我终生的宝物啊」

「你也真是妹控到没救了啊……」

「哎呀，在哥哥和妈妈之后才被叫的那什么好像在说些什么呢，真珠，败家犬的叫声听起来还真是愉悦啊。哈哈哈」

「咕呜呜……」

「请冷静下来，昴君。偶尔也需要让源体会一下优越感才行。而且，在蕾姆心里昴君是第一位」

「又这样宠他……」

蕾姆温柔地安慰着失落的昴。司空见惯的场景让源不满地鼓起了嘴。蕾姆见此轻笑出了声，

「哦，怎么了，蕾姆？」

「没，只是觉得，果然不管出门去哪里蕾姆和大家都是在一起的呢……这么一想，感觉有点开心，不自觉笑出来了」

「……这样啊这样啊。会产生这样的想法，那全家旅行看来是做对了。嘛，有点公司的福利旅行里带上家人的感觉就是了」

昴见蕾姆用手挡住唇边露出的幸福笑容也微笑了起来。见到他们的笑容，源也隐隐约约感觉自己似乎能够理解一点父亲的心思了。

新的祝贺方式『节气』，以及为了准备而出的远门。

当然，要举办『柊鰯』这样奇怪的活动肯定是需要一点程序没错。但只是鱼和树枝的话，应该用什么都能够代替才是。

但是，他却反而立了一个要出远门的计划——，

「文化振兴会能够着手新文化的推广很开心。弗斯米的大人物们学习到了巴南的做法很开心。而，我们因为能够全家出来旅行很开心。一石二鸟，皆大欢喜。虽然欢喜的不是二鸟是三鸟」

昴漫不经心地笑着，然而他主要的目的其实是最后的一部分，这点只要看到他平时和家人在一起时候的样子一目了然。

大概，前两个方面的原因其实也只是因为没法放任不管吧，这种没法随便拒绝别人委托的性格可真吃亏，源事不关己地这么想着。

「————」

蕾姆欣慰地望着昴的微笑。

母亲肯定早已看透了父亲的内心吧。所以才打从一开始就没有反对说要乱来的父亲，反而甘心乐意地陪着他一起。

「长老，长老，能问个事吗？」

在距离这场名为父母间交流的秀恩爱稍远处，源向正对着太阳晒干毛皮的查莫夫问道。查莫夫说着「莫？」回过头来，他可爱的圆眼睛望着源。

「怎么了莫？」

「这个季节，弗斯米有没有什么特产？」

「唔……」

查莫夫听到这个问题闭眼沉思了一会儿。随后，倏然证言望着昴那边，点点头。

「这个问题，昴也问了莫。毕竟是亲生的莫……」

「不，这种事情就算了」

「真不可爱莫。这个季节，在弗斯米的话……是有名的『白雪樱』盛开的季节莫」

只有位于受到摩格雷德大喷口滋润的土地上的弗斯米，才能栽培出这种非常娇贵的植物。

树木的叶子全部变成雪花般的白色花朵——源虽没有见过雪，但也能想象到肯定会很壮观。

也想象到了昴正是因此以『节气』为由，为了让『生日近在眼前的某人』看到这个风景，所以计划了这次家族旅行。

「说出来就太不懂风情了。要保密莫」

「我是不会说啦……但是，妈妈大概已经知道了」

「所以这么说了莫。你以后要找老婆也要找那样的才行莫」

「要把真珠养成和妈妈感觉有些抗拒啊……」

「莫你，就这么理所当然地要娶妹妹，疯得让人战栗啊」

查莫夫小小的身体颤抖着，望着源的目光露出了莫名的畏惧。对他的视线很是意外耸着肩的源，被真珠轻扯了一下脸蛋。妹妹真可爱。

「喂，源和真珠。过来一下。有话要说」

就在源他们话刚说完的时候，昴喊他们过去。查莫夫听此用下巴示意道。

「好了，快去吧。我也不会做出打扰家庭团聚这么不解风情的事莫」

「啊，谢谢，长老。那么，之后再见」

挥挥手，查莫夫露出惹人怜爱的笑容，摇着短尾巴，踩着娇小可爱的步子离去了。

见他离去，源也回到了双亲身边。只见脸颊赤红一如既往的蕾姆，和自信莫名爆棚一如既往的昴。

「咳。实际上呢，源。接下来，我像让蕾姆和你们看个东西」

这种装腔作势的语调，之后会说什么，可想而知。

「————」

昴在发表结果前顿了一下，源微微瞟了蕾姆一眼。

和孩子们面对面，双目放光的昴并没有留神身边妻子。微笑着的蕾姆注意到了源的目光，深处一根手指抵在唇边，给出了「嘘---」的暗号。

说出来就太可惜了，指出来就太可惜了，完全了解。

源无可奈何地耸了耸肩膀。真珠模仿他，也耸了耸肩膀。

「这次全家出来旅行，其实并不单单是为了钓鱼和与作（2），而是——」

（2）与作：歌名，最有名的是演歌歌手北岛三郎在1978年发售的版本，查了一下歌词，第一句就是“与作在砍树”

在这样的孩子们和妻子的包围下，还觉得自己事情藏得很好的小丑黑幕，光明正大地披露了这次家族旅行的最后一个计划。

※　※　※　※　※　※　※　※　※　※　※　※　※

——来谈谈克拉格雷尔迁徙林吧。

『白雪樱』的观赏会就不细说了。

只是，弗斯米漫山遍野的鲜花，实在是蔚为大观，总之就明说了他们对这片风景很是享受。

那么，关于作为家族旅行计划的一部分有着其必要性的新节气风俗『柊鰯』——，

「唔——，没想到会变成这样，就算是用我的眼睛看都能看出来啊」

「你的眼睛意外得瞎啊！少废话，老爸也快点动手！」

一大一下两道人影大喘着气在巴南的大街小巷里来回奔波——说白了，就是菜月家的男丁，昴和源两个人。

他们分别戴着一绿一红烫发一般的假发，身穿黄黑纵条纹的背心和短裤。手上拿着利用柔性材料制作，带有塞棉的突刺的法杖。古朴而又美丽的新时代鬼风。

若要问两人穿着这种一目了然的鬼装，到底在做什么——，

「能够试一下柊鰯是好……但没想到，居然会给街上招来猫鼠灾害啊！」

「想都知道肯定会这样吧！这样光明正大把食饵挂在那里，野猫肯定会扑过来的吧！」

源怒吼着，从另一个设置点上把挂在那里的烤鱼带树枝一起拔了下来，扔到了垃圾袋里。这样就二十了个，剩下的还有很多。

毕竟，把树枝和鱼挂在街上这种奇特活动可是在整个城镇里举办的。

「喂，源，别那么粗暴！这个，姑且是神圣的仪式，柊鰯可是一个感恩的节日啊。就算要处理，也要像这样，比如说好好找个地方埋起来，这样的感觉大概才行」

「好麻烦！话说别处理的那么随便啊！说到底……好痛！」

源对这种根本不讲道理的说法喊出了声，就在这时身后受到了连续的小攻击。回头去看发生了什么，之间脚下躺着小颗的豆子——是豆子。

而扔豆子的人则是面带笑容追过来的孩子们——。

「是、是捉人鬼！找到捉人鬼了！」

「糟糕！要被扔得满身是豆了！喂，那边的人！要怎么样才能从这里面……可恶！居然在吃惠方卷！」

源为了不被逼到思路，拼命寻找着逃脱的方法。正打算向路边的老人问路，却见他正在吃粗大的惠方卷。

那种状态下人根本不可能说话。只能看着他吃完惠方卷。

「类似事情，似乎在弗斯米那边也发生了，这个责任应该算哪边的？算我的吗？你怎么看，源？」

「只觉得好痛！现在，很痛啊！我没地方逃感觉很痛啊！会被撒豆子都怪你好痛好痛好痛！为什么只扔我啊！?」

好不容易稍微有点改观了，昴做事一直吃力不讨好。

被不停扔豆目带泪光的源，和身着鬼服的父亲一起在巴南的街道上奔跑着。

母亲和妹妹肯定正在家里向着惠方（1）吃着巨卷等他们回去。

到底能不能回收所有的『柊鰯』，平安回到家呢——。

（1）惠方：意思是吉利的方向，向着惠方吃卷所以才叫惠方卷。（具体方向和当年的天干有关系）。

「嘿嘿，源。你，跑步变快了嘛。我觉得好高心」

「吵死了——！！你倒是给我感冒啊——！！」

父子间的吵架声传遍天野。

这些都不过是卡拉拉基都市国家的角落里，日常风景的一个片段罢了。

\\

《完》

** 怠惰Ex6『Fortune·Setsubun Horo』
リゼロＥＸ　『フォーチュン・セツブンホロゥ』
\\

译者

L君

赞助

HenTaiPP、故意切线阻、寒冰牛仔、黑白熊、zmy240

\\

\\

1

（标题注：这里的フォーチュン为Fortune，有幸运，命运的意思，セツブン为节分，即立春，ホロゥ为霍洛，re0世界观内的鬼怪，出现于外传中的一篇，正文中有详注）

-----

好久不见的更新，很抱歉却是番外篇。

二月三日，节分惯例的EX.

这次的内容，Re0的动画BD特典小说『Re:从If开始的异世界生活』里登场的很多角色都登场了，不过即使是直接看我想也是能读的懂的吧。

那么，请尽情享受番外篇吧。

（本段来自长月达平）

-----

那么就闲言少叙，进入主题吧。——今年也是、节分的季节要来临了呢。

节分、那是被称作『节分之王』的菜月·利格鲁，一年中最为恐惧的一天了。

对于卡拉拉基都市国家的第二都市『巴南』而言，从数年前开始的那个活动，现在完全可以称得上是一种奇祭的文化了。

——遇到鬼的时候就撒豆子趋散，朝着吉祥的方位吃惠方卷。柊鰯的缘由也是出自这里。

虽然如此，但具体是谁说的就不得而知了，这就是卡拉拉基的新文化，节分的概要了。

「今年会被做些什么呢……」

从学校『寺子屋』回来的路上，利格鲁将双手交叉背在脑后，不禁对于近期即将要到来的不幸活动叹了口气。

扮成鬼怪的样子，为了免于被猎人们的豆子泼洒追击而在大街上跑来跑去。——利格鲁的主要任务虽然就是那样子的，但是说到底也是以当初想定的「撒豆」为标准所展开的情况罢了。

每年，根据利格鲁的父亲菜月·昴的提案，节分文化也是会不断向前进化的，所以被害的范畴早已不仅仅是局限于「撒豆」这种东西了。

一边看着幸运的方向，一边无言的吃着被称为惠方卷的大卷这一活动。

以及被称作柊鰯，将鱼头用树枝插入，再将其用来装饰玄关的这一活动。

身为活动策划人，以及『卡拉拉基文化振兴会』的代表的昴的发言是十分有说服力的，节分经过了几年时间之后，呈现出了魔改般的变化。

而且，由于这一方面的展出受到了不清不楚的情报所约束，再加上在人们之间的传言所导致的结果，让其内容逐渐地脱离了事物的本质。

结果而言，对于利格鲁来说，最后变成了自己在大街上以鬼怪的样子逃来逃去，受到豆子呀大卷啊，甚至鱼头的一并投掷攻击的活动了。

「不管是谁，完全没有理解节分的真正理念呢。而且，随意糟蹋食物。豆子的话也就算了，其他的东西掉到地上后还能吃的吗……！」

一边回想起节分时候的事情，利格鲁一边咬紧了牙根露出了愤怒的表情。

前面也说过了，利格鲁绝对不是不喜欢节分这个活动的。

当然也不是那种，每一次都受到伤害，然后还能说出喜欢这样的被虐体质。

不过，无论是多过分的活动，这都是利格鲁的父亲所策划的。只是这以事与愿违的形态发生的变化，才是最激怒利格鲁的地方。

大体上来说，以这种肆意妄为的方式来享受，对于体会活动的方法来说才是下策之中的下策。这种活动，应该考虑到人心以及传统才对。

——打心底里讨厌着，但又认真拘泥于节分是否能够很好进行着，菜月·利格鲁的纠结体质也是天生所具的。

虽然是些废话，但每当快临近节分到来的季节时，巴南街道上的每家每户都会开始储存豆子。结果，错误理解节分宗旨的小孩子们，从家里拿出豆子，用豆子偷袭利格鲁的事情也经常多发。

从寺子屋回家的路途中，只要发现利格鲁的孩子就会兴奋起来，出现用豆子投掷利格鲁的一幕。

不过——

「——哟，唔，嚯」

自己的肌肤能够感受到，所投来豆子的质量、数量以及轨迹，从而以最小的动作来将豆子全部回避。

投来的豆子要是一两粒的话，或许还不是让人意外的数量。

但是，此时，往利格鲁身上投掷的豆子可是五个孩子各自握在手中的——即便是小孩子的手，一次也能投掷个二十到三十枚左右。

也就是说，面对那差不多超过百粒的豆子雨，利格鲁看都没看就躲过了。

「太假了……」「就连看都没看……」「背，背后长眼睛了吗……？」

对孩子们发出的惊讶声，利格鲁耸了耸肩膀回过了头。

「真是天真呢，小屁孩们，回去练过再来吧，你们也不想想，每年我是如何身居死亡前线的呢？」

如此说完之后，利格鲁歪着脸笑着朝孩子们走去。

孩子们瞬间发出了颤抖，如同自己随意挑战『节分之王』而被诅咒了那般，发出悲鸣后，四散落荒而逃了。

「唔！要被杀了！」「那是什么眼神啊！」「节分之王是没血没泪的恶魔呀！」

「先不管你们说我的眼神！等下你们可是要给我好好向你们父母打听打听节分的真正规则，遵守规矩，正确地给我参加活动！下次我可是要捡豆子回击了啊！」

恐吓着快吓哭了的逃走的孩子们，利格鲁看着脚下的豆子叹息着。

节日马上就要到了，曲解活动的人增加的话可就麻烦了。不管到哪去都是这样。管中窥豹可见一斑，变成这样也无济于事。去学校是这样，只是稍微去买点东西，去散步啥的，自己都感觉时常身处危险之中。

不过，这也是玩笑话罢了，由于临近节日，街道中豆子四散的事态频发，但是在这时期，好像有被称作为『捡豆子』的这种短期的扫除工作。

这也是从自己的熟人『中介人』，叫做克莱茵的人物那边听的（注：BD特典中帮昴找差事的蜥蜴人）。听说还很赚钱，记忆中有很多人都对利格鲁表示过感谢。

不管怎么说，多亏了这个时期，利格鲁的感觉会变得十分清晰起来。

而且，要是可爱又乖巧的丝碧卡出来的话可不能让她遇到这种情况。简而言之就像是，濒临生命危机的一种进化了。

只要跟丝碧卡在一起的话，豆子或者其他这种概念的东西，即便是光速也有自信打不到自己。

「现如今，被当作豆子的这类东西都碰不到我丝毫了、吧」

「——在说什么啊，从大老远就听见这些稀奇古怪的话，跟阿昴一个德行啊」

「哦」

捡起了一粒豆子，不耐烦嘟哝着的利格鲁听到了那个声音之后，抬起了头。

是熟悉的声音。低沉，但又给人一种轻快印象的卡拉拉基口音——想到声音的主人的一瞬间，立马回过头的利格鲁露出了笑容。

「赫利贝尔叔叔！」

「噢——，看起来这么精神我就放心了，利格鲁，我刚刚看到了你那些动作了哦。看来在我不在的期间，还真是进步许多了呢」

一边如此说着，一边用自己的大手掌抚摸着跑过来的利格鲁的头的，是一位身穿长长的衣服，狗脸——不对，是狼脸的亚人。

非常少见的狼人种族的那个男人，用有着锐利牙齿的大嘴巴叼着一个金色的烟斗，双眼如同要眯成一条线一样看着利格鲁笑着。

他是父母的老朋友了，赫利贝尔对于利格鲁来说也是亲戚一般的关系。

「像利格鲁这种年纪，稍微不留神就一下子成长了呢。要是蕾姆酱同意的话，真想让你来继承我的家业呢」

「我之前也说过啦。我要做一些安定的工作，才能养起妈妈跟丝碧卡的，像叔叔那样四处溜达可是会不小心NG的」

「什么啊，说的还真是严厉呢。我只是随口这么一说罢了，利格鲁这么成熟的样子我还反倒有点困扰呢」

赫利贝尔说完就张开大嘴巴豪放地笑起来，利格鲁也露出了与他年龄相符的笑容笑着。

利格鲁也在这世界上跨越过许多障碍，即便他还有着孩子般的脸庞，也不得不在这世间的浪潮之中阔步前行。

「即便是背负父母期待于一身的孩子，也至少希望能让他安稳点成长啊……」

「还真是看的太远了呢。小孩子那么说可一点也不酷呢」

「那种事就不谈了啦！话说叔叔最近一段时间都去哪了呢？明明跟我约好要陪我练习的，却一直不在，让我甚至以为你横尸街头了呢」

「哈哈，还真是敢说啊。我要是死了的话，那对于这个国家来说可是件大事啊。这可是关乎濒临灭绝一族的命运啊，可是责任重大的立场啊」

「是是，这才是我的师傅呢」

「是呢。越来越让我觉得责任重大了啊」

两人融洽地说着话，看着露出笑容的赫利贝尔的利格鲁也缓缓地笑了。

在和谐相处的基础上，能如此与自己亲近的赫利贝尔也是自己很喜欢的人。

虽然是那样的态度，自称『永远的游手好闲者』，还有一副吊儿郎当的性格，但即便如此，工作方面是相当有能力的，偶尔跟他一起在街道上漫步的时候，可以看出许多人仰慕着他，这让利格鲁也十分开心。

虽然那个工作，对于现在的利格鲁来说到底要做什么还不得而知。

「作为忍者，为了守护国家而日夜跟危险的人战斗。而且还是濒临灭绝的狼人族的吧？太厉害了啊」

「嗯，但是利格鲁你现在，每天为了活着可必须要舍弃掉身为孩子的纯粹呢。虽然有点遗憾，但这就是这个世界的无常呢。」

将烟斗里的烟吐到了空中，赫利贝尔苦笑道。

「话说，教给你的变身有练习吗？要是腻了的话你也可以说说不满之处哦」

「那是肯定会腻的啊。要我做给你看看也是可以的哦？现在能够变的东西，也就是路上投来的柊鰯程度罢了。」

「那个鱼头，我也经常看见，果然是跟阿昴有关的呢」

今天，被扔了有点豪华的沙丁鱼的头，要让在家的妹妹看看，当作纪念带回了家。

从肩上的包里拿出之后，赫利贝尔明白地点了点头。

这个狼人，因为跟昴相处很久了，所以能够立马理解到。

「是叫巴南文化振兴会来着？偶尔会在其它的街上听到哦。貌似挺有名的样子，连我都觉得自豪呢」

「嘿嘿，嘛，虽然是那样子的父亲，但是这可是父亲的工作哦？被夸奖了之后当然就不会觉得不好了。啊，但是要是直接跟父亲说了他就要膨胀了！」

「小孩子的心还真是复杂呢」

赫利贝尔将手从和服的开口处伸到了里面，挠着自己的肚子发出了苦笑。

欣慰着他能够理解自己的态度，利格鲁向前迈了一步并继续说道。

「对了，这样子悠闲地谈话的话，是会暂时在这里呆一阵子的意思吧？」

「嗯，是那样的哦。稍微跟熟人打声招呼，到了晚上的时候再去你们家哦。跟阿昴和蕾姆酱问声好」

「叔叔」

「嗯？」

「丝碧卡呢？不给她带点什么吗？」

微笑着，利格鲁头向前倾斜着直接提问。

听到了他的那番话，不知道为何赫利贝尔仿佛是感受到了压力一般，脸都僵硬起来了。

「哦，嗷，也是呢。丝碧卡酱肯定，也在一脸可爱地等着呢」

「嗯嗯，我知道了，我会跟她说的哦！啊，但是怎么说呢。丝碧卡，什么都不用做就跟天使一样可爱的。让人在脑海里就能想象到她在很可爱地等待着，这或许也是，超越人们想象的一种可爱呢」

「这种地方，利格鲁不愧是蕾姆酱的儿子呢……」

利格鲁一边红着脸，一边陶醉地回想着在家等候的可爱妹妹的样子。看着眼前的这幅光景，不禁让赫利贝尔呆然的用手指挠了挠自己的脸。

「哈！可不能这样！必须要一刻不留地早点回到丝碧卡那边才行！叔叔！晚上再见！不要忘了给丝碧卡带特产哦！」

「啊。嗯，我知道了哦。会看着带点东西的……」

挥着自己的小手，利格鲁做完了自己应做的事情之后翻了个身，就这么用飞一般的脚步在街道上开始奔跑起来。

看着他那扬起尘土逐渐远去的背影，赫利贝尔吐着烟斗里面的烟。

「在妹妹还没出生前就是个妹控，生了之后却变得更加严重起来了啊，利格鲁」

如此苦笑地吐槽着。

※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※

利格鲁不管赫利贝尔的吐槽——假如真的听到了，行动也是不会有任何变化的——猛然穿过街道，在回家的路上飞奔。

「丝碧卡，丝碧卡，可爱的丝碧卡」

不断在嘴里重复着这一句话，利格鲁奔跑的速度仿佛快要超越风了。

仅仅是在脑海里描绘出可爱妹妹的样子，就能够让自己的身体内侧散发出无限的能量。这种力量，或许可以被称作「永久的丝碧卡发动引擎」吧。

这个世界，应该更加地注意到丝碧卡能够发挥出的无限可能性。

世界上的所有人应该在看到丝碧卡之后，争先恐后发起争夺以及发生各种各样的事情才对。

利格鲁一边陶醉在自己远大的妄想之中，一边将扔向自己的豆子弹落，朝着正在进行惠方卷的练习而正在吃着大卷的邻居挥了挥手，用柊插入了猫只会吃的鱼头部分，然后到达了家中。珍惜每分每秒，就这么就势冲进了玄关，一口气跑到屋里面。

「好了，我回来了！丝碧卡，哥哥（ni-ni）回来了哦！我现在立马洗下手就过来，你要可爱地等着哦！」

满面笑容的，利格鲁一边强忍着想要立马把丝碧卡抱起的冲动一边进行回家的问候。

之所以有洗手的习惯，是因为那是从小时候开始就做的义务。

单纯的估计是为了防止生病什么的吧。实际上也不知道是不是多亏如此，利格鲁一次也没感冒过。

虽然可能单纯是父母体质较好所遗传的，但是也还是要洗手，做好了这些事，才能跟丝碧卡接触——

「——你还真是，在家跟在外面完全不一样的态度呢？」

「欸？」

不过，迎接着径直冲到洗面台的利格鲁的，既不是妈妈也不是妹妹，却是不应该出现在这个家中的女性声音。

「————」

不禁吞了口气，利格鲁朝着洗面台回过了神，然后提高自己的警戒心朝着房间走去，将手放在了两边的拉门上，将其打开。

那边是——

「啊，哥哥（ni-ni）」

「欢迎回来，真是迟呢」

朝着门那边，房间里出现的场景让利格鲁愣住了。

在铺着榻榻米的房间里，正中央放着被炉，是寒冷时期菜月家必不可少的东西。

有一个将脚伸入被炉，将微笑地天使哄着抱在怀中的女人。

女人晃动着那不整齐的乳白色发丝，朝着利格鲁眨了眨眼，薄桃色的嘴唇微微一动，露出了极为动人的微笑。

「因为我太可爱了而一见钟情可是不行的哦？」

「——。才不会，无论怎样的美女在我面前，我心里也只有妹妹而已」

「你呢，喜欢妹妹是可以，但是太过头了的话可是会被当成笨蛋的哦，要注意点才行」

一瞬间呆住的意识，在听到了她讲出话之后自己才回过神来。突然清晰的意识，让自己不禁对这身穿白色和服的女人，有种难以言喻的复杂感情。

让人害怕的，端正外表的女人。

在这个时候，用端正这个词不知道是否贴切，要是以美丽来形容的话或许是更加准确的吧。她拥有的并非是人偶师所追求的那种美丽孕育而生的人造美，要说的话是能够让野生动物们遵从着本能簇拥而至，可谓是奇迹一般诞生的自然美才对。

野性的美貌，单纯来说的话是那样的，但这到底是如何的奇迹之上所成立的东西呢，这甚至让对于女性的兴趣尚且贫乏的利格鲁，都为之心里一颤。

原本，这应该是初次见面时候的想法。

但是对于利格鲁来说，跟这个女性并不是第一次说话了。

「缇雅！为什么会在这里！」

「哈？虽然没有什么别的理由。但是我只是在我所想的时候，呆在想呆的地方罢了。也不是因为受了谁的指使。啊，乖乖，你真是诚实又可爱呢，是吧丝碧卡——真想杀了你」

「别这样！这对情操教育可是不好的！」

对着丝碧卡投以怜惜的微笑，女性——缇雅却发出了十分具有杀意的语言。

突然说着毫无根据，却让人信以为真程度般的话语，利格鲁慌慌张张地将丝碧卡从她手中夺走，温柔着抚摸着她那一头黑发，确认着丝碧卡是否没事。

「没事吗，丝碧卡？没被做什么奇怪的事情吧？都怪哥哥回来的太晚……妈妈到底在干嘛啊！」

「蕾姆的话，把丝碧卡交给我以后就去买东西了哦。虽然我也想一块去的，这个，是叫被炉来着？一进去就不想出来了。我已经被这个东西俘虏了吗，人类有时候还真是活的精致呢」

因为丝碧卡被夺走而嘟起了嘴，可是缇雅也早已缩在了被炉之中，上半身则是趴在桌子上，发出「呜哇」的呻吟，眯着眼的她看起来很是幸福。

虽然年龄来说的话大概像是二十岁左右，但是属于怎么看其行为举止都不像是符合其年龄特征的类型。第一眼见到会让人觉得高冷的美貌，但却是意外与人亲近，这对于利格鲁来说是相当不擅长应付的类型。

——当然，也并不是讨厌。

「而且，看见你那么慵懒的样子，真是让人受不了呢……」

「哥哥（ni-ni），姐姐（ne-ne）」

「哦，是呢，丝碧卡。虽然把缇雅当成姐姐有点不明所以但是确实不能吵架啊，哥哥，要反省一下呢」

丝碧卡小小的手掌一张一合的，对着利格鲁的脸按来按去。可以感受到从妹妹发来的切实诉说后，利格鲁才暂且收敛了自己话语的长矛。

看着他们俩的举动，缇雅则是「是啊是啊」附和着。

「给我反省，反省。我被伤害了，所以想吃甜的东西了」

「不要得寸进尺了哦。再说喜欢照顾人的妈妈来说是不可能不准备点心的吧。点心跑哪去了」

「跑哪，当然是我的肚子里哦」

「那么，到了晚饭为止给我好好忍着」

在其他人家里目中无人的样子，利格鲁对于缇雅如此表现的跟暴君一样的举动说不出话来。

这个缇雅也是父母的老相识了。利格鲁也在几年前就认识她了，按照这些当事人们的说法，确切来说，是比起朋友更像家人一样的关系。

说真的，即便是这么说利格鲁也不能接受。

要说为什么的话——

「家人的话，肯定要一起住的啦。只有偶尔才露脸什么的，这难道不是亲戚，朋友之类的吗？」

「什么？你，是不是太久没见到我跟我拗气了？脸长的跟阿昴一模一样啊，真是可爱呢，让我想杀了你」

「不要说那么危险的话！」

如同是立下了不得不小心的约定一样，动不动就「杀了你」「杀了你」之类的。

言语，行动，都把她的外表给糟蹋了。

要不是那样的话，从她的外表来看的话——

「——？你，几天不见是不是长高了？」

「嗯噶」

立马从被炉里跳出来，她以能够碰触到对方呼吸的距离在利格鲁面前站着。身上散发着轻飘飘的香味，她却毫不在乎的伸出手，触碰利格鲁蓝色的短发。

慢慢的用纤细的手指抚摸着，利格鲁则是被封印住了一般一动不动。在那个期间，缇雅则是好好体会着利格鲁成长的样子。

「小孩子的成长还真是快呢。在不久之前还是个擦鼻涕的小屁孩，现在已经变成了这样子的程度了呢」

「……又是这种话啊，从我出生到现在，缇雅跟赫利贝尔叔叔总是那么说」

「因为这是真的啊。我跟阿赫都在看着哦……虽然我在最珍贵的时候不在」

「————」

这个时候缇雅眯起了双眼，投以仿佛看向远处的目光。

那个目光，让人感觉像是不是看着当前，而是看向过去一般，这让利格鲁有点不甘心。

那是对于利格鲁来说无法企及的地方。虽然也有去想象过，但是这样做让利格鲁有点不是很喜欢。

「本来，那一方面也不过是闲聊话罢了啊。再说我有没有出生什么的，巴南的街道要毁灭什么的，没有人会相信的吧」

「啊，那也是真的，当时的话地图可能都要改写了哦。不过，我还是忍不住想把你杀了啊」

「搞得像是你自己要把街道给毁灭了似的」

估计是说的太随意了，对于缇雅说的话，利格鲁无可奈何地耸了耸肩膀。缇雅看到了利格鲁的那一瞬间，如同是被刺中了要害一般张大了双眼。

「你的那种地方，还真是能够刺激我的嗜虐心呢。啊啊，尤其是看到你那困扰的样子，到底要让我有多满足呢。想杀了你。」

「我就是讨厌缇雅的那种地方。」

「——。但是，这个被讨厌的我送给你的东西，你倒是一直带着呢？」

说完，缇雅露出了笑容看着利格鲁的左手手腕。听了她的话之后立马说不出话来了，利格鲁微红着脸，转移着视线。

利格鲁手腕上佩戴着由白色野兽的毛编织而成的手环装饰品。

这是数年前初次碰到缇雅的时候，她给的东西。把这个交给他的时候，是这么说的。

「还记得吗？我把这个东西给你的时候对你说的话」

「啊！那，那是……那个，对于我来说已经有丝碧卡了」

「又是那样？你还真的是，真的跟阿昴一个德行呢」

被如此打趣，利格鲁听得咬牙切齿。在自己怀里的丝碧卡，则是天真无邪的看着哥哥和姐姐们大眼瞪小眼的样子。

在这里退缩的话作为一个男人就失格了。而且丝碧卡就在自己面前，可不能让她看到自己如此丢脸的样子。

下定决心之后，利格鲁对缇雅投以锐利的眼神。

然后——

「爱上我……」

「只要带着那个白色的绳结，碰到危险的时候我就会到来……」

同时张开了口，但是各自从嘴里蹦出的话语却是长短不一。

注意到这一点的利格鲁为时已晚了。

缇雅则是吃惊似的睁大了眼睛，然后慢慢的，露出了调戏般的表情，又变成如同要蚕食老鼠的肉食动物般的狰狞面貌。

「呐，刚刚说了上面？利格鲁啊，刚刚说了什么来着？」

「吵死了！没有！什么也没说！是你听错！那是父亲的阴谋罢了！」

「啊哈哈，没事的啦。我是爱着你的呢。虽然想把你杀了。」

「可恶！」

一边抱着丝碧卡，一边脸红着转身要从缇雅面前逃离，但是缇雅则是高速移动着阻扰着他，又迂回到了利格鲁的面前，对着他那红着的脸用指头戳着。

「啊呜，哥哥，姐姐。」

看着两个人的举动，丝碧卡露出了开心的微笑。

就这样，三个人如此的一幕，直到蕾姆买完东西回到家才结束。

※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※

「那么就重新为阿赫和缇雅的归来庆祝，干杯！」

「——干杯！」

到了晚上的时候，在菜月家的客厅里，围着被炉的大家共同发出声音干杯。

虽然是这样，但是举起的酒杯里放的并不是酒，而是茶水和果汁类的东西。由于各种事情的缘由，在这个桌子上是不能喝酒的。

这对于洗澡都要喝酒的赫利贝尔来说也不例外。

「哎呀，话说还真是巧呢，居然阿赫也回来了，正赶上缇雅时机刚好的时候」

「是那样的呢。多亏如此，才能这样子大家一起围在饭桌前。由于太开心了，都让蕾姆不知道该做点什么的地步了」

「啊，比起手艺啥的，还是有点不安的吧？」

「蕾姆可是一直为了昴君的家人们全力做饭的呢」

看着露出淡淡的微笑，眼睛出神的蕾姆，昴脸红着挠了挠头。

说实话，看着父母这般样子有点辣眼，但是对于利格鲁来说，从出生到现在这是司空见惯的场景了，事到如今也没什么了。

「叔叔，把盘子给我吧，我去帮你盛。」

「哦，还真贴心呢。那样的话，能多盛点肉给我吗？还有蔬菜啥的少放点」

「是是。但是，不好好吃蔬菜的话对身体不好的哦」

一边接受着赫利贝尔的要求，利格鲁一边熟练的用长长的筷子，将锅里面的食物取出放在容器里。

今天菜月家的饭桌上主要是以火锅为主，然后再加上蕾姆努力的制作的几个副菜。

「这么多人，再加上在被炉里，当然是要吃火锅的啦！」

「嗯，果然是昴君呢！让人佩服！」

这是决定做火锅之前的父母的对话。但也没有特别的意见，就这么随他们去吧。

而且，利格鲁也是喜欢吃火锅的。也可以不用吃自己不喜欢吃的蔬菜了。

「等下，利格鲁，你是不是在我的碗里放的蔬菜有点多啊？我也想跟阿赫一样吃很多肉。还有，我不是说不要放蔬菜的吗」

「说什么呢，吃蔬菜啊。光吃肉的话会变得肥嘟嘟可是不得了的啊。肉，蔬菜，蔬菜，蔬菜，肉，蔬菜，蔬菜，给我好好遵守吃肉的规则」

「我这不是没怎么吃到肉的吗！」

把高高迭起盛满蔬菜的盘子交了过去，缇雅不满地发出了悲鸣。但也还是很好的实行了盘子里的东西不回锅这一原则。

如此满足着这样规则的利格鲁，一个盘子接着一个盘子开始盛了起来。

「哎呀~能够遵守真是太好了，连我们自己看了都开心起来了。能够如此顺利地吃火锅真是让人开心啊。真是个双赢的关系呢。」

「不要说傻话了，我也是想要好好吃火锅的，不要老让我一个人盛了……」

「好的，真是可怜呢……好了，利格鲁，来吧，啊~」

对着分食工作过于集中，导致了自己的胃袋忘记填满的利格鲁，蕾姆伸出了筷子。

虽然有点让人害羞，但是在场的都是自家人。即便是觉得羞耻也罢，利格鲁乖乖地接受了蕾姆的喂食。

「喂喂，你让我的蕾姆做些什么事啊你这小子，好的，也来吃吃我的」

「哦，怎么回事，利格鲁，从刚刚开始都没吃多少，我来喂你吃吧」

「啊，那么我也要我也要。快，快吃这个。还有这个，快点给我吃！」

「姆噶姆噶！这种东西能吃的吗！」

以接受了蕾姆的喂食为契机，大人们都争抢着对着利格鲁的嘴巴运送食物。虽然昴和赫利贝尔有点开玩笑的样子，但是也还是有选择的给自己喂食所以还好，到了缇雅这边就是把自己盘子里讨厌的蔬菜全部塞到利格鲁的嘴里。

「不要开玩笑了！全部都是大人了给我好好的吃饭啊！在吃火锅的时候开玩笑什么的，给我更加崇拜火锅啊，畏惧火锅之力才行！」

「噢噢，感觉像是很隆重的奉行火锅主义呢，你那种立马就能得出结论的性格！作为父亲可是很骄傲的呢」

「烦死人了！我才不要被父亲表扬！」

大声吼叫着，利格鲁攻击着以昴为首开始的大人们，大人们则是笑着不当回事，这对利格鲁来说更为火大了。

果然，利格鲁的同伴只有丝碧卡了。

「然而，丝碧卡却被缇雅抢走了！」

「啊，好了好了，不要再闹别扭了，不要闹别扭了，那个呢，你可是丝碧卡最喜欢的哥哥呢，丝碧卡跟我也才见第二回罢了」

「是呢，利格鲁，平时都一直纠缠着独占丝碧卡，就今天先让给缇雅大人吧，相对的，你去摸赫利贝尔大人吧。」

「在蕾姆酱的心中，我现在是怎样的位置啊？」

从对人际关系的强弱具有露骨表现的蕾姆来看，对缇雅的关照比赫利贝尔要高的样子。

在人们眼里印象很好，也是在这附近有名的令人骄傲的美人母亲，这样的蕾姆会有如此亲昵的人也是相当少见的，所以即便是对缇雅有不满的利格鲁也不会说什么。

「嘛，就先这样吧、利格鲁。要是你的话，看不见可爱的丝碧卡的话不也是寻死腻活的。到时候缇雅也要好一阵子看不见丝碧卡了，你就体谅下」

「……这样子，能算的上是家人吗」

「嗯？」

「一起生活的话，不是才叫做家人吗？然而有时候在，有时候又不在，却要把这样的家伙当作家人，我觉得有点奇怪。」

在傍晚时候，利格鲁将对缇雅直接说过的话，再次跟昴说了。

就是突然的想要说出口，但是利格鲁又十分的讨厌这样。

不过，昴慢慢地抚摸着利格鲁的头。

「你所说的是有道理的，但是也并非是那样的。即便是没有经常在一起也是能够成为家人的，缇雅也有缇雅自己的事情。所以，才会这样有时在有时不在。但是，需要她的时候，她是绝对会在的」

「————」

「嘛，这还是个好感度很高的美人姐姐呢，她还会经常逗你玩这才是幸运的呢，你这家伙，也得了太多便宜了吧」

「说什么呢！?」

突然改变了语气，用着十分玩笑的语调如此说着的昴被利格鲁给咆哮了。将父亲放在自己头上的手拿掉，利格鲁就这样双手交叉抱住。

「再说，你说我得便宜什么的是认真的吗。明天就是节分了，我可是要遭遇很惨的事情了呢。早已经是郁闷的不得了了……必须要有丝碧卡才能睡得着啊！」

「为什么到了最后要按照你所要求的那样。丝碧卡的陪睡权是轮流的，今晚可是我啊。但是，我把她让给缇雅了。再怎么说你也是没有任何的陪睡权的哦」

「可恶！」

故意施展苦肉计换取同情，但是由于昴跟利格鲁相处的时间太长了。从他出生到现在，如此浅显的作战早已被昴一眼看破。

如此父子二人跟往日一样吵闹着。

「嗯？什么？明天吗，利格鲁会出什么事吗？」

听到了他们的吵闹，把手指给丝碧卡啃的缇雅歪了歪头。看着如此反应的缇雅，利格鲁犹豫着如何回答，然而蕾姆微笑着代替了他回了一句「是的」

「事实上，明天是节分了，是根据昴君的提案的一个节日，在那个时候，利格鲁要代表鬼族，以鬼的打扮在街道上躲避豆子的攻击跑来跑去的哦。」

「这是什么充满语病的介绍！」

「哇，怎么回事，听起来很开心的样子……」

「你也变得兴奋起来了吗！」

听到了蕾姆复杂的介绍之后，缇雅双眼发出了亮光。

缇雅可能会因为那危险的发言而对活动感兴趣，而且明显是对「撒豆子」的内容有兴趣，也正因为她有喜欢捉弄利格鲁的习惯，自己也说过自己有很强的嗜虐心，也就是说，这个节分——

「——不正是为我量身定做的节日吗」

「所以我才不想让你听见啊！是谁，是谁不小心把这个话题提出来的！是我吗！是我啊！真是不好意思！」

「你还真是一个人就能够瞎忙活的家伙呢……」

对着抱头受到巨大打击的利格鲁，缇雅用梦中少女一般的眼神看着他，看着利格鲁如此的自爆挠了挠头，昴则是「好的」点了点头。

「喂，给我好好听着，儿子哦。我很能够理解你的心情。的确由于节日的活动你会受到许多的打击，作为父母的我们也是不想见到的。」

「给我好好的品尝，说谎的滋味！」

「不要舔我啊。不要紧紧地咬住我啊！」

手上留下了儿子的牙印，昴对于满是不信任感的儿子感到了些许困扰。

「到底，是什么原因会让你变得如此癫狂起来了呢……」

「是亲人的行为啊！还有，街上人们的行为！」

「事先说在前头，在撒豆子的时候可是我跟你一起装扮成鬼的啊，走在外面被孩子们用豆子攻击可并不是只有你而已啊？」

「什么，也能够对阿昴扔豆子的吗？不行了，我快抑制不住我自己了……」

「缇雅大人，缇雅大人，我给你煮了好吃的肉了，好了，啊」

「啊」

中途，由于嗜虐心而变得难以忍受的缇雅也变得渐渐镇定下来了，自己的妻子华丽地救了场，昴轻咳了一声继续说着。

「总之，话不能说到一半，最重要的是现在要说的。也就是说，每年的节分你都遭受到了十分惨痛的遭遇，但是这次的节分活动，可是不一样的方向了！」

「又要增加多余的奇怪要素吗……」

「你这家伙，完全是不信赖父亲呢！但是，对于你的惊讶我也能够理解！」

那么说完之后，昴立马从被炉里脱开身，开始在房间角落里搜寻着自己放着的，工作用的鞋子，然后从那里面拿出了个卷起来的布。

「阿赫，帮忙拿下那边！把这个展开！」

「哦，这是什么，横幅？写着些什么呢？」

听到昴的请求后，赫利贝尔立马站起身拿住布头的一端，然后两个大人一口气把它摊开，用笔描绘出的文字就立马在利格鲁的视野里展开了。

那边写的东西是——

「节分鬼怪……？」

「为了让小孩子也能够读懂，刻意只用イ文字来写。实际上是写作『节分扮鬼』的。这也是我所策划的节分企划第四弹，是不是兴奋起来了呢？」

「是让人胆战心惊」

大体上，鬼怪这种东西给人都不是好印象。虽然也并不是熟知这一点，但是的确根据昴以前听过的传言——

「鬼怪，指的是霍洛吧？完全想不到好印象呢」（注：霍洛：出自短篇集2『Operation
KOKKURI』，https://tieba.baidu.com/p/4654462647）

「嘛，我也知道是这样的。即便是这样，鬼怪也还是观念上的东西呢。在当作节分的鬼的角色的时候……」

原本，节分的『鬼』与实际上的鬼族又有点不一样，鬼等于灾难，不幸这种印象已经根深蒂固，将鬼驱除的活动也是为了远离不幸的手段。

实际上拥有鬼族的血也会被人当作是鬼一样，是厄运的象征，这给人的印象也是十分的强烈的，即便是现如今在这街道上长居，也无法主张到其自身的市民权。

「虽然把驱除坏东西的一部分给省略掉了，但是只有鬼才是节分的主角！既然大家都是那样认为的，那么就姑且按照那么做吧」

「但是作为结果来看的话，每当节分要到来的时候，自己就会变得难以生存了」

「如此难以生存的话，对于在这世界上不得不生存下去的你来说，不是一件好事吗。尤其这种节分扮鬼的活动，才能把你给拯救」

「呵」

用着将信将疑的眼神，利格鲁看着昴。

看着那样子，话题似乎是无法很好的进行下去了，于是赫利贝尔点起了烟斗。

「嘛，嘛，虽然没有听到最后，但是对于节分来说我也只有道听途说的知识罢了，那个和霍洛到底有什么不同之处吗？」

「那个……嘛，这次鬼怪可是被允许能够变装的哦！」

「什么！?」

看着提高声音宣布如此的昴，利格鲁睁大了双眼。

变装，这是多么让人惊人的主张啊。要说为什么的话，迄今为止的节分，只能允许以黄色的布以及黑色条纹为主的装扮，还有红色的长棉坎肩，以及那以艳丽的绿色主张自我的假发。

「节分的鬼怪呢，要是穿了跟平时不一样的衣服的话，节分那天可能就会一整天找不到鬼就这么过去了」

「又要把鬼变成坏人吗！」

「所以呢，这次则是相反了呢。也就是说，在节分加入假面大会的要素。在街道上悄悄地通知，明天不管是男女老少，大家也都会按照计划好的来扮演。在那个时候你就混入人群之中，有种《寻找鬼怪的游戏》的那种感觉，怎么样，听起来是不是很刺激呢？」

「总觉得，节日有点变得越来越蠢了呢……」

昴露出了“不厉害吗？”的表情虽然让人很火大，但是利格鲁陷入了思考。

这也让人意外，感觉昴的意见也并不算得上是很坏。不如说，是蛮不错的。如果身穿显眼的衣服的话，肯定盯着利格鲁的人多。

可是，跟通常的鬼怪有所不同的打扮——不仅如此，对于菜月·利格鲁来说，只要以让人想不到的打扮，就能跟丝碧卡平安无事的上街游玩了。

「喂喂，怎么回事啊，爸爸。总算是父爱觉醒了吗」

「说得好像是我从未父爱觉醒过呢。我的父爱，早在两年前就已经完全绽放了呢」

「两年前，那不是从丝碧卡出生的时候才绽放吗！」

对于竖起大拇指，闪耀着自己牙齿的昴，利格鲁严厉地吐槽着。

不管如何，很少见，真的是太少见了——不对，对于节分来说是第一次，利格鲁第一次赞同父亲的意见。

「变装呢！好的，那么就明天开始，一定要成功呢！」

「就是这种气势！——虽然我想这么说，但是你太年轻了，利格鲁。明天准备好，在街道中你以普通的姿态，通过『魔法器』来拍摄宣传，也就是说不充分的变装可能会导致被攻击集团一下子看穿，那样的话、你·IS·DEAD」

「就不要做多余的事情了吧！?」

这不禁让自己后悔刚刚对父亲的策略那样刮目相看。

不过，对着这样的利格鲁，昴「切切切」地左右摆着手指。

「不要说些荒唐的话啊。这种一边倒的游戏才是，真正为了节分而考验你迄今为止所锻炼过的能力，不然怎么对得起那些撒豆子的人们呢。那边全力以赴，我们也全力以赴，这也是第一次这样，得有点运动精神才对的吧。really?」

「吵死人了！那么，怎么办才行的啊！到头来，跟普通的节分没啥两样啊！」

不如说，利格鲁的样子早已是众人皆知了，感觉会比去年还要惨。

被这样的绝望感所支配着，利格鲁预感到自己明天会被豆子给杀掉。

面对如此绝望的利格鲁——

「——不会的，利格鲁，不会变成那样的。这里就交给妈妈吧」

飒爽地站起身来，朝着利格鲁伸来援手的不是其他人，正是蕾姆。

她穿着淡蓝色的和服，挽起了自己的袖口，如同是下定决心一般，紧紧地握着拳头。

「昴君也说过了。那边全力的话，我们这边也全力以赴。就是这样。那么，就全力地面对对手就行了哦」

「可，可是，怎么办才好。妈妈，我，迄今为止不说假装，就连变装都没做过，肯定会被立马识破的，我就·IS·DEAD了啊……」

「真是傻瓜呢，利格鲁，这并不需要你一个人来面对」

「欸？」

微笑着的蕾姆朝着混乱的利格鲁点了点头。随即伸出了手，利格鲁的脸被母亲的双手触碰着。然后，与自己一样的淡蓝色瞳孔，正在跟自己眼神相对着。

「可以吗，利格鲁，这里就交给蕾姆了。昴君……你爸爸也在为利格鲁的事情拼命考虑着，那样的话，蕾姆身为妻子帮助他也是理所当然的事情」

「妈妈……」

听了妈妈说的话，不禁让利格鲁的胸中充满了温暖。

接着，利格鲁陷入了短暂的思考——

「——我知道了，我相信妈妈呢」

※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※

——相信蕾姆的利格鲁，把自己全身交给母亲也快近一个多小时了。

「怎么样。利格鲁，母亲这样子已经是竭尽全力了。」

说完之后，蕾姆用手擦拭着额头的汗水，然后又用力点着头。

将其全部接受，利格鲁正视着自己眼前的这幅姿态。在那面能够倒映全身的镜子中，倒映出的是『重获新生』的利格鲁。

「这是，我……？」（注：这里的“我”用的是a ta shi，女性自称时用的称谓）

镜子中出现的人，是跟利格鲁同龄的可爱少女。

以浓蓝色为基调的和服，再加上柔软又具有特征性的红色簪子。靓丽的蓝色头发被完美的扎了起来，让人误以为是哪儿的大小姐一样的装扮。

虽然眼神还是有点尖锐的样子，但是长长的睫毛以及些许的腮红，还有那有点害羞的表情，酝酿出了相当能够诱惑男人的魅力。

回过头。蕾姆点了点头。

回过头。赫利贝尔佩服地吐了口气。

回过头。看着那位少女的昴偷偷地笑了出来。

「就给这身打扮的你，起名为菜玥·琳梅尔吧」（注：这里的姓氏其实是na tsu
mi而不是na tsu ki）

「吵死了啊！！相信妈妈的我真是个笨蛋！！」

忍住笑声的昴的表情看着让人憎恨，利格鲁拼命地踏着地板。

当然，镜子里的可爱少女，正是通过蕾姆的手进行华丽变身的利格鲁。说实话，蕾姆的技术到了让人害怕的程度，简直就是完美的作品。

「在蕾姆的眼里这是很正常的。就利格鲁来说，是跟昴君一样拥有许多的可能性的……这也是我的力作」

「啊啊，真是可爱呢。明明长得眼神和我一样，生下来的时候还对这孩子的未来有许多不安的，幸好，总觉得以后即使是有这个眼睛也能够做点什么了……」

「怎么可能啊！这样子还有未来吗！?再说，妈妈刚刚说的，跟爸爸一样拥有的可能性是什么啊！爸爸也女装过吗！?」

「菜玥·修芭鲁……明天就请期待吧」（注：见外传「My fair bad
lady」，昴女装回，这里用的是同一个名字，https://tieba.baidu.com/p/4987171283，这里翻译略不同）

对于昴莫名其妙拥有自信的回答，利格鲁不禁跪了下去。

狼人赫利贝尔啪啪地拍了拍那样子的利格鲁的肩膀，然后从大大的嘴巴之中吐了口气。

「啊，或许你不会太开心，但是这不是挺好的吗，你看，要是将来继承了我以后，没准以这种打扮，对于潜入这种事也有帮助」

「这么奇怪的安慰还是不要了啊……不对，不要这样，叔叔，我可不能做这种事情啊」（注：这里还是a
ta shi下面也都是a ta shi看来是相当入戏）

「看来是相当艰难地前进着呢...」

这是自嘲又或者是固执吧，也或许是不习惯。

对于利格鲁这早早将自己的现实作为现实接受了的状况而苦笑着，赫利贝尔稍作思考般挠了挠头。

「如果那样做的话，为了明天的到来我教你下分身术吧？虽然不知道临阵磨枪能不能行，但是对于天赋很好的利格鲁来说，没准能分出一个人来」

「分身指的是，能够让赫利贝尔叔叔变成四个人的招数？」

「对对，可是能以手数四倍增加的能力哦，很强的。注意一点就是，分身数是根据手数增加的，要是受伤的话也是一起的，被咬的话，可是四倍的伤害」

「对于我来说，只能看到自己未来承受两倍豆子攻击的样子」

「就连声音都是假声了……」

要这样的话还不如干脆下定决心，演一个完美的女孩子，生存的可能性没准会更高一点。

要点就是让对方能够犹豫是否扔豆子，对于身为女孩子的菜玥·琳梅尔来说，让扔豆子的远离自己就行了。

「这就是让鬼也为之远离的，节分怪物……」

「这不就变成，要跟自己体内的血战斗的情况了吗」

「叔叔，我是不会输的」

「嗯嗯，是吗是吗，那就加油吧。我就喜欢你这样无论做啥都十分拼命的样子。」

让热血的利格鲁放弃思考，赫利贝尔想要抚摸他的头，但估计是怕弄乱他的发型，转而变成拍了拍他的肩膀。

他这担心弄乱自己发型的样子还真是不由的让利格鲁揪心。

「不好，从俺变成我的违和感要淡薄了……」「注：俺（おれ）是男子自称，我（あたし）女子自称」

「你这种容易受到影响的地方，说好也不好，说坏也不坏呢」

那到底是受谁的影响呢，利格鲁也不想去追究，只能伸出舌头，接受罢了。

不管如何，将菜月·利格鲁改变成菜玥·琳梅尔的作战，除去利格鲁自身的羞耻心之外，是的确有效果的吧。

剩下的问题就是——

「——嘻嘻嘻，要死了，要死了，我，你要把我，要把我杀了吗，到底这是什么啊，哈哈」

「你也笑过头了吧！就算是我也会很伤心的！」

「等下，不要再逗我笑了。啊，肚子好疼，肚子好疼……！」

在利格鲁完成之后，缇雅就变成了抱着肚子大笑的状态。虽然是毫无违和感的将其接受，但是也不希望自己被如此的嘲笑。

「……这样子，看起来真的很奇怪吗？我」

「完成度很高的，蕾姆可以自负的这么说。同时看了现在的利格鲁之后，甚至会让蕾姆有种错觉，自己到底做出了什么样的怪物……」

重新朝着镜子，摆出轻快的姿势，真的觉得很可爱。

看着利格鲁如此这般，蕾姆一边满足，一边又流了些冷汗。

与父母两人的反应不同，利格鲁在内心微笑着。

当然，不是因为自己真的喜欢女装，不如说，是因为完成度太高了，让自己也因为如此可爱而感到震惊，仅此而已。

如果他们的做法是真的打算将儿子置身于危险之地，那今后肯定会对父母所想的事情有所顾忌。

但绝对不是因为这样的机会不多了，而就这样享受女装的乐趣，威吓父母也不是为了发泄愤怒。

「呐，丝碧卡，明天我会加油的呢」

「啊~~唔？」

躲到被炉里面，在大家的脚间来回游玩的丝碧卡，这样回复了利格鲁的话。

由于因为自己的哥哥太过于可爱而完全认错了，丝碧卡睁大了双眼，咬着自己的手指。

这么说了一句话。

「——姐——姐？」

就这么一句话，让利格鲁陷入了身份危机，然后被击沉了。

※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※

——骚乱的晚餐结束之后，巴南的夜晚更深了。

明天就是节分了，这可谓是决战前夜了。

利格鲁属于要是第二天有什么要事就睡不着的类型，对于他来说，节分的前夜，紧张程度是特别的高。

除了节分以外，剩下的就是家人生日了，总而言之，都是让他心跳不止。

吃完晚饭之后，稍微跟爸爸晚酌的赫利贝尔也在之后回去了自己的房子。昴也为了明天的节分而去开最后的讨论会，跑到『卡拉拉基文化振兴会』去了，蕾姆陪他一起去了。

恐怕，也会拜托其他人「明天我的孩子就请多关照了」。是个周到，无微不至的妈妈。如此而已，利格鲁也很清楚自己受到过许多大人的保护。

如此那般说了许多关于节分的东西，但实际上则是为了利格鲁不受到过分的遭遇，以昴为首的大人们也有考虑这一点。

彻底地决定节日的参加要素，根据明天的『节分扮鬼』企划，讨论要是将利格鲁跟别人搞错的时候应该处以何种对策。

最坏的是，在利格鲁的背上贴上「这家伙是鬼」的纸张。

因此，夜晚的菜月家父母都不在，这时候利格鲁就变成了代理家长，为了守护身为可爱天使的丝碧卡而努力着。

「——还不睡觉吗？」

坐在了草坪一旁，利格鲁正看着悬挂在天空之上的蓝色月亮，突然有人跟他搭了句话。

回过头来，对方就毫不犹豫地坐在了利格鲁的身旁。温柔地毫无顾忌地触碰着他的肩膀，利格鲁发出了小小的叹息。

「我有点不明白，这不是到了人类孩子的睡眠时间吗？我明天可是很忙的哦？」

「话是这么说的，但是没关系。我的话，稍微有点睡眠不足的话反而能导致身体太过紧张而更好活动」

「但是，要是那样的话难得的变装不就毁于一旦了吗？是吧，菜月·琳梅尔酱」

被用调侃的口气说了，让利格鲁不禁一下子脸红了起来。

利格鲁把玩着手玉（注：为了女装而戴上的布袋，佩环之类物件），为了自己不被发现而把脸转了过去。可是，缇雅还是嘻嘻笑着，朝着利格鲁的脖子用鼻子靠近。

「哒，哇！」

「不要那么慌张啦……嗯，紧张时候的味道。而且还十分害羞，勉强的样子，你还真是不诚实的让人觉得可爱，可爱到让人想要杀了你的程度」

「……又这么说啊，真想杀的话，那你就杀了我吧」

反正又做不到——混入如此的想法，利格鲁叹了口气。然后，听了他那番话之后，缇雅张大了自己的瞳孔看着。

在那之后，她一瞬间咬紧了嘴唇低下了眼睛。

「是呢，想要杀，但是，我不能杀了你」

就这么，缇雅缓缓露出了微笑，说了句「因为」

「我，爱着你啊」

「————」

那是与缇雅初次相见时候所听到的话。那番话，让利格鲁的心很强烈地动摇着。

恐怕这是除了家人以外，第一次被说『爱着你』了吧。

而且，还是如此让人着迷的美女，无论如何也是不会想到的。

「————」

为了让自己的内心动摇这件事不被发现，利格鲁玩弄着自己的左手手腕，那用白色兽毛所编制的手环，这也是缇雅送的东西。

她说过，只要有这个的话，无论何时都会赶来帮助利格鲁。

「你一次也没用过那东西呢，你没有呼唤过我」

「……因为，总觉得，有点让人不好意思，寻求帮助什么的，只是因此而把你叫出来，这样子可不行」

「是吗？你的父亲阿昴可是，会立马向周围求助的人哦？」

「那是因为那是爸爸，而且妈妈也喜欢他那样所以没关系。但是，我又不是那样子的，我是因为母亲的血才和父亲不一样的。是不会把想要见到的人呼唤出来，而是自己去见她的哦」

「嚯哦」

特意鼓起勇气说出了那番话，可是缇雅的反应却让自己不是很满意。她露出从未见过的表情哼着鼻子，用手指玩弄着垂到肩膀上的乳白色秀发。

「真是个寒冷的夜晚呢，蕾姆跟阿昴，到底什么时候才能回来呢。」

「反正，是节分的前一天，会喝点酒的吧。估计还会花点时间呢」

「是那样的吗？那，为了不惹一身酒臭，我们还是先去睡觉吧」

大大地伸着懒腰，缇雅立马站起身来。

在菜月家的晚上，大家都是约定好在同一个房间里大家的被子并在一起睡觉的。即便是缇雅在这里过夜也是这样子的。

唯一的问题是，谁能够陪在丝碧卡身旁睡觉。但是这个导入了每日变动制度之后——

「今天是我跟丝碧卡一起睡觉的。很羡慕吧？」

「啊啊。很羡慕，但是明天就是节分了所以无所谓。」

「你这次回答的可真快呢，真的让人觉得恐怖呢你……」

因为不想要在丝碧卡的事情上说谎，而且也找不到说谎的理由。

对于如此不可思议摇着头的利格鲁，缇雅眯起了双眼。

「刚刚，我闻了就知道了，你在紧张，是在故作坚强的吧」

「……嘛，要说不是那样的话，可能会变成山一样多的谎言」

「无论是山也好河流也好，不要倔强了。来吧」

「——？」

缇雅站起身来，拉着利格鲁的手。纤细的手指，光滑肌肤的触感，比想象中还更加有力地把自己拉起来，自己也因此有点惊讶。

然后，面对如此惊讶的利格鲁，缇雅露出笑脸靠近着，差点能够碰到彼此鼻子的距离，十分近距离的微笑。

「为了让你获得勇气，这次就由我来帮忙吧，今天本来跟丝碧卡一起睡觉的权利在我，但是现在我把这个权力让给你。」

「哈，哈啊！?那样的话，那样的话，为什么啊」

「你跟我一起陪丝碧卡睡觉。我并不想把在丝碧卡身旁的权利让给你，但是你也太可怜了，看着你那可怜的脸庞，不禁让我心动，让我想杀你想的不得了了……」

「我知道了！请让我同意这个提案！」

露出陶醉的表情，扭扭捏捏红着脸的缇雅说出一番危险的话语，让利格鲁立马投降了。

接受了他的投降之后，缇雅「很好」的点着头。

「好了，要是决定好了的话就赶紧做准备吧。我也是，难得这么好的一天我也想要睡觉，给你唱首久违的摇篮曲吧」

「摇篮曲……」

「对，『杀人之歌』呢！」

「叫『缇雅』的吧！」

自己的母亲从以前就会经常给利格鲁唱摇篮曲，看来那个出处应该是缇雅那边，但是无论怎么说她都是个危险人物。

不过，虽然说她很危险，但是不得不承认利格鲁被她这一存在给救赎。

相遇的当初，利格鲁的心被淡淡地动摇着，若是那个心情从那时起一直不变的话，总有一天自己会追随她而去吧。

「利格鲁——？」

「我知道，马上就来！」

一边听着缇雅不可思议般的声音，利格鲁吹着夜风，试图将带着热气的脸颊以及耳朵冷却下来。

反正，钻入被窝里有可能又会变热起来，但是那个时候就钻进被子里去，没啥大碍的。

所以——

「——啊啊，可恶，安静点啊，我的心脏」

一边说着这样子不耐烦的话，利格鲁一边朝着可爱的丝碧卡，以及缇雅所等待着的被窝走去。

※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※

此外，虽然是多余的话，到了第二天，引进『节分扮鬼』的节分活动也是以大成功结束的。

根据菜月·昴的提案，在街道上宣传『节分扮鬼』。因此，在巴南的街道上混入了多数的化装人物，这次从外部开始，享受着节分的旅行者们也混入了其中，撒豆作为一大活动也很好地完成了。

结果，由于突然开展的『节分扮鬼』竞赛，而开始举行了化装者们的评选活动——

——在那表彰台之上，菜月家的总获胜者们，用《魔法器》以记录照片的形式保留了下来。

照片上的是可爱的少女以及看起来妖艳的美女，还有英姿飒爽穿着男装的丽人。

（注：这里的三人就是菜月家的三人，哪个是哪个就不用我说了吧，滑稽）

与那表彰台之上并排的三个人一起，巨大的狼人，以及抱着幼儿，露出笑脸的美女也被一起拍到了画面当中。

※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※

在twitter上，会公开这次登场的「缇雅」以及「赫利贝尔」两个人的角色设计图。

对此有兴趣的人，请务必浏览。

\\

《完》
