#+title: re0 忧郁if 从零开始奉献的异世界生活
#+setupfile: ./setup.setup

* 忧郁if 从零开始奉献的异世界生活

原文时间：2026.4.1

内容来源：web（ai翻译）、百度贴吧等

由于是web版文本没有分节，使用“神啊、佛啊……”作为分节标志

展示出来的正文为ai翻译版本，百度贴吧翻译版本因为更新未完故不采用，日文原文请访问本页面org原文件

** 简介

分歧点：

星辰篇佩特拉等人能否救昴于阿尔之中

【長月達平】：
惯例的愚人节、惯例的迟到！真是抱歉呢！
这次到底要写点什么让我纠结了很久、最后我想大概也算是盘了篇还不错的东西出来呢。
这次的故事虽然还是IF线、但和以往相比，算是别具风格的一篇吧。
那么敬请享受！让我们在篇尾再见！

** 1
——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会呼唤任何人的名字。

△▼△▼△▼△

——轰隆作响，仿佛要将身体割裂的冰冷寒风，包裹着整片绝冰河。

「————」

即使穿着厚实的防寒衣物，仍能感受到那穿透骨髓的空气的寒冷。他奋力撑开视野，那视野因白色的呼气而变得模糊，望向前方。

如果只是抵御寒冷，本可以穿得更多。但在这里，真正需要面对的敌人，并非呼啸的风雪。

而是更明确、更直接地将刀刃抵住自己性命的威胁。

「——害怕吗？」

忽然，听到这样询问的声音，他才意识到对方柔软的手的触感。

一直紧握着的左手感受到的温暖热量，无论身处何种绝境，都绝不会抛弃自己——那是充满信赖与亲爱之情的、最棒的搭档。

「不，除此之外，像保护欲啊、可爱啊、热情啊之类的，总之正面的感情要多少有多少……夸你的话根本不够用啊」

「哼哼，那是当然的啦。那些不够用的话，我倒是很想在时间允许的范围内尽可能多听一些……不过现在，似乎有些碍事的家伙在呢」

「是啊。——真是的，虽然早就料到了，但也饶了我吧」

赞同了可爱搭档的话，他耸了耸肩，视线却始终锁定前方——即便在互相调侃，他对那里存在的警戒也丝毫未减。

老实说，紧张也好，警戒也好，无论倾注多少，对这个对手来说都远远不够。

「到现在还拿你当衡量标准虽然有点问题……但比起你的恐怖程度，雷格鲁斯简直算得上可爱……不，他一点也不可爱。雷格鲁斯那种，顶多算个跳蚤」

「——这我就当作是您给予我的特别评价，收下了」

对方用顺风耳捕捉到他的牢骚，并且一丝不苟地回应，他对此眨了眨一只眼。

悠然自得的站姿，穿着华丽服饰、锻炼有素的高挑身躯，目光中透着贯彻强大意志的决心，以及略显晒黑的浅黑色肌肤。那肌肤上淡淡浮现的，是如同梵文般不可思议的纹样刺青。

一眼便知此人非同凡响——至少，环视当今整个世界，恐怕也无人能胜过他。

——人称『狂皇子』。

那便是他们如今在极寒风暴肆虐的绝冰河中，所面对的强敌。

「对峙，吗。……为什么，我们非得动手不可呢」

「这是在自问？ 若是疑问，那我必须质疑你提出疑问的态度。至于原因，我应该已经与阁下反复说过很多次了。在此基础上，我们决裂了。所以才会变成这样。——对我来说，这也并非本意」

「并非本意？ 这又是为何？」

「我对阁下，既无怨恨亦无憎恶。我与阁下不得不在此对峙的理由，与彼此的好恶或憎恨无关。只是——」

说到这里，『狂皇子』顿了一下，眯起眼睛，视线略微下移。由此，他看出对方的视线从自己身上，移到了身旁的搭档身上。

瞬间，一阵黏稠的、永不消逝的憎恶，从对方身上泄露出来。

那确实是『狂皇子』绝不会对与自己对峙的他流露的感情。与此同时，那也是那个男人与自己绝对无法相容的理由。

在毫不掩饰地倾泻着那份憎恶的同时，『狂皇子』宣告道：

「——围绕那份污秽，我与阁下，水火不容」

「首先，你把我超可爱的搭档称为污秽，这种审美观我完全无法理解。所以，我跟你做不成朋友」

「实在是，遗憾。正因遗憾，所以深感遗憾。但遗憾归遗憾，我也不会就此罢手」

『狂皇子』缓缓摇了摇头，仿佛在为说服失败而感到惋惜，叹了口气。然而，如果他那副样子算是真心想要说服的话，那价值观的鸿沟恐怕永远也无法填平吧。

「真是个完全无法沟通的家伙呢。……塞西尔斯都比他好说话些」

「拿他比的话，塞西也太可怜了。塞西那家伙，说话倒完全没问题……只是，谈话的结论会擅自按照塞西的喜好落地罢了。这就是强者的理论吧」

「但是，不能让他得逞呢。——你应该明白吧？」

「——嗯，不用你说我也知道。不过你说了我更有干劲就是了」

他重新握紧牵着的手，短暂地交换了一个眼神和笑容。

面对强敌，与搭档之间的团结感十分充足。——而他们之所以选择此地作为战场，并花时间进行长谈的理由，也在此刻不期而至。

那是视野边缘，瞬间闪烁了一下的绝冰棱镜——，

「「——E・M・M！！」」

瞬间，两人齐声咏唱发动，绝对防御魔法包裹住自己和搭档，通过将存在从这个世界偏移半步，使一切干涉无效化。

那毫不留情地试图击穿他们膝盖以下的白光，就这样穿过了他们因实体模糊而透过的身体，射向了另一侧。如果未能防住，并排站立的两人想必会一起被射穿双腿，陷入无法战斗的状态。

而那白光，同样也瞄准了『狂皇子』——但，

「——这是全力？ 还是说你想激怒我？ 若这是挑衅，后果可是要你承担的哦？ 让你承担后果的是我，承担后果的是你」

说着，『狂皇子』用竖起的两根手指夹住了白光，并将其接住。

光芒在男人的指尖缓缓失去光辉，最终显露出一根长长的针的本体，那针也随即碎裂、雾散。——那是以魔法构筑的针，以超高速射出的招式，被这样称呼。

「地狱狙击……也就是说」

「——又是你啊？ 真是不长记性呢。来多少次结果都一样啊」

「————」

突然，从上方传来的那个声音，让他不禁屏住了呼吸。

风，此刻仍在呼啸。尽管如此，这究竟是为何。为何在如此狂风中，那声音仍能清晰地传入耳膜。

莫非强者的理论，拥有连自然法则都能压服、使之服从的力量吗。

若果真如此，那声音能穿透暴风雪传来也是理所当然。

因为，那悠然现身于这绝冰河天空中的存在——她——

「——久违了，『忧郁魔女』。别来无恙？」

「别一副跟老朋友搭话的样子好吗？ 我既不是你的朋友，也不是什么亲近的熟人。我好不好什么的，根本无所谓吧」

「并非如此，并非如此。毕竟，眼下阁下与这位先生，正是我达成目的路上的坚实障碍。若恰逢贵体欠安之时，我定要趁机而为」

「哦，是吗？ 那如果我放出谣言说我状态极差，你会信以为真地眼巴巴跳进来吗？ 好厉害啊，去死吧你」

她在胸前啪啪地轻轻拍着手，悬浮在那寒冷的天空中，露出残酷的笑容。

「————」

那是个美丽的女人。

用缎带将长长的略带红色的茶发束起，身穿一件混杂了粉色、水色和金色等多种颜色的特殊纹样的礼服。

露出白皙纤细肩膀的装束，在这极寒地带简直难以置信地单薄，但对她来说，这似乎构不成任何障碍，她呼出的气息甚至都不会变白。

正如暴风雪的声音无法掩盖她唇间漏出的美妙音色一般，寒暑与天气的变幻无常，也无法阻止她做她想做的事，穿她想穿的打扮。

「——来了哦」

那声呼唤，将屏住呼吸、身体僵硬的他的意识拉了回来。

同样仰望着同一个对手，想必也抵达了同样心境的他，他的搭档却顾及他的心情，拼命压抑着即将溢出的情感。

他并不觉得这份体贴让自己感到难为情，或是过意不去。——只是，绝不能辜负这份好意，他深深地吸了一口气。

然后——，

「——终于又见到你了，■■■！」

「————」

他大声地，向着白雾迷蒙的风的另一侧的她，如此喊道。

不巧的是，她和『狂皇子』不同，他们这边可没有压制狂风的手段。

而且，好不容易积蓄到这一刻的声音，要是因为没传到对方那里就要重说一遍——那种逊毙了的事，他也绝对不想做。

究竟，他等待这一刻等了多久呢。

他究竟品味了多少无力感，又跨越了多少，才走到了这一步呢。

为了求得那一切努力的结果，他深吸一口气——菜月昴凝视着■■■。

凝视着，然后说道。

「我要把你夺回来，■■■。——命运大人，放马过来吧！！」

那是菜月昴踏上这片极寒之地之前所花费的漫长时光，那是他倾注了所有时间所得出的结果，也是他决定献上一切的日子的决算宣言。

** 2
——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会背负任何人的性命。

△▼△▼△▼△

——黑暗。黑暗。黑暗。在黑暗的深渊中，持续飘荡。

如同浅眠般模糊，如同永劫般不确定，如同泥泞般散漫。

仿佛一直处于一本书中，梦境与现实页码的交界之处——在那般模糊、不确定且散漫的、永无止境的黑暗中飘荡着。

究竟，这样过了多久呢。

究竟，还要这样过多久呢。

究竟，这不断延续的刹那，要延伸到何处呢。

这些理所当然的思考、疑问、命题，也被黑暗缓缓拉长、稀释。

被稀释的东西，薄得像一层纸，稍微用力一戳就会轻易破裂，接缝会消失，最终失去原本的形状。

想必，已经反复经历过无数次了。

将涣散的意识收集起来、拼凑起来、连接起来，却因为稍微用错了一点力，就轻易将其击碎，又变得七零八落、支离破碎。

既然如此，干脆放弃去维系那些已经破碎到数不清次数的东西不就好了。——然而，却做不到。

——黑暗。黑暗。黑暗。在黑暗的深渊中，持续飘荡。

如同浅眠般模糊，如同永劫般不确定，如同泥泞般散漫——然而，却绝非孤身一人的黑暗中，持续飘荡着。

并非孤身一人。也不会变得孤身一人。

那被拉长的刹那，那反复不断的失败，那持续飘荡的黑暗——是「并非孤身一人」这个理由，将它们留住，不允许它们消失。

自我的定义尚不完整，并非孤身一人的依据也被笼罩在黑色的迷雾中。即便如此，却无法将其抛弃、放手、放弃。

无法放弃。——因为，放弃与自己不相称。

所以——、

△▼△▼△▼△

「————」

视野豁然开朗，被抛向外界的瞬间，蜂拥而至的信息洪流在脑中掀起轩然大波，肉体剧烈地扭动挣扎。

「——！」

视野闪烁不定，红与黑的对比色交替蹂躏着世界。

伸展的手脚绷得笔直，无意识的制动器被解除，身体遭到过度使用——可怕的是，从指尖到根部，所有关节的肌肉依次开始痉挛。

疼痛，遍布身心每一个角落的疼痛，紧紧抓住他的身与心，不肯松开。

「烧焦了——！ 然后，稍等稍等稍等！？ 这、这不要紧吗！？ 简直就像被冲上岸的鱼一样的状态啊！？」

「闭嘴，露梅拉。无论你的外表如何超凡脱俗地可爱，朕也不记得允许过你在朕耳边吵闹。再说了，这不是理所当然的结果吗」

「理所当然！？ 阁下，您刚才说是理所当然？ 您早就知道会变成这样吗！？」

「朕的『阳剑』能焚烧想焚烧之物，斩断想斩断之物。不过，既然不是通过正规手段释放的，会产生些不便也是无可奈何的吧」

「……那话，您之前说过吗？」

「这点小事不说也该明白吧。你们这帮人全都比聪明却仍年幼的朕年长才对。难道说，你们都白活了？」

视觉、听觉、嗅觉、味觉、触觉——被五感捕捉到的所有信息的浊流吞噬，意识被迫遭受搅拌的头顶上方，回荡着这样的声音。

那些声音，也是全新的信息。即，汹涌浊流的一部分。

「糟了糟了糟了！ 要是就这么死了，多年的辛苦就全白费了！？ 我跑遍了各地，把脸皮都蹭到地上了，好不容易才走到这一步……哇，这让我怎么见人啊！」

「现在不是说这种话的时候啦！ 这种时候嘛……对了，用猛药！ 只要结果好，些许疼痛也会被冲淡，变得优雅！ 主人也一定会微笑着夸奖我们做得好的吧！」

「就是那个！ 你能做到吗，露梅拉小姐！」

「难说得很啊——！ 我可是燃烧得越旺火属性就越强呢！ 火焰能做的只有破坏，以及再生中的破坏部分哦！ 哦嚯嚯嚯嚯！」

「难道说刚才这纯粹是在浪费时间吗！？」

哇哇哇的，即使在洪水和浊流中也格外吵闹的信息，左冲右突。

感受着以自己为中心展开的对话轰轰烈烈地交错，在身心的疼痛之中，他缓缓地感知到正在逼近的威胁——一种窒息感。

「——唔」

胃壁痉挛，作为空气通道的管道因内部收缩而堵塞。

这是由肉体不自然的蠕动所引发的悲剧，但等待着它的结局，是谁也笑不出来的喜剧。本就因极度消耗而衰弱的身体，正因呼吸不全而机能受损。

然而，在混乱不堪的众多信息之中，却找不到解决之道。

「你们这样吵吵闹闹的，真的好吗？ 这家伙快要死了。对朕来说，既然是与朕素不相识的男人，死了也不痛不痒，但你们可不一样吧」

「不不不那确实是千真万确，不过我们也已经把资源压榨到极限了，实在没有余力啊！ 要不，先把他放回刚才那个球里怎么样？ 不行吧，果然不行！」

「自己就快速解决了啊。真是个有趣的男人。——嗯，也是啊。即便用朕的光辉，对这位濒死的小丑也无能为力……不过，这边可不一样」

「你想干什么？」

「蠢货，别用一副事不关己的表情说话，『云龙』。——那边的男人暂且不论，对这边这位可爱的姑娘，不是有办法吗」

无法应对，痛苦不断累积、累积、累积。

痛苦、疼痛、痉挛，将一切涂抹覆盖，那本应被拉长至永劫的刹那，披上了沉甸甸的终结。

就这样——、

「————」

——就这样，结束了吗？

「——昴！」

瞬间，另一个信息猛然击中了正逐渐被黑暗封闭的意识。然而，这次的信息，并非仅仅是延长痛苦与煎熬的东西。

是用痛苦覆盖痛苦，用煎熬覆盖煎熬，用信息覆盖信息，将其拭去的东西。

然后——、

「你不能死哦。你可不能死啊……！」

而那个信息、那份痛苦、那份煎熬，因为是熟悉而珍贵之物，所以——。

「——啊」

蠕动的胃壁，即将闭合的喉咙，打结的舌头，闪烁的视野，被刹那吞噬的意识，本应在黑暗彼方消散的生命——都停住了。

不要放手，什么都不要。不要放弃，一切。抓紧啊，抓紧这个世界。

不这样做不行，做不到可不行，只有这样才能——、

「呜、呃、唔」

「昴！」

令人不快的红与黑的光芒消失，逆光中映出一双含泪的眼睛。

有着蝴蝶状特征纹样的瞳孔，呼唤着自己名字的可爱声音，全力拉扯着即将四散的存在——那个小小的身体里，蕴藏着巨大的存在。

「呃、啊、这」

「——对，就是这样。是吧。没事的，我就在你身边哦」

身体各处都不听使唤，脆弱、麻木、破败不堪的心灵——即便如此，为了证明自我，为了告诉对方自己还记得，他编织着话语。

他会接受的。他如此相信着，如同闭上眼走过那座名为信赖的桥梁。

「无论发生什么，只要贝蒂和昴在一起，就一定能挺过去哦，昴」

他紧紧拥抱住那可靠而令人安心的话语，然后失去了意识。

——那是菜月昴重启脚步的第一天发生的事。

** 3
——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会回首昨日。

△▼△▼△▼△

薄薄的，睁开眼皮时，首先映入眼帘的是陌生的天花板。

「——呃啊」

他试图将所见直接说出，但干涸到极点的口腔和严重沙哑的喉咙，根本无法发出像样的声音，只能发出难听的呻吟。

活像一只被踩扁的青蛙临终前的哀鸣。

但是——、

「——醒了吗。真是个贪睡鬼，坏孩子呢」

对他而言，将这信息传达给在枕边等待他醒来的对象，已经足够了。

那只悄悄伸过来的小手，连带着刘海轻轻挠着他的额头，昴因痒痒而眯起眼睛望向那边，只见一个少女——碧翠丝——正柔和地弯着眼角，站在那里。

不变的姿态，不变的目光，不变的温暖——她就在那里。

毫无疑问，分毫不差，正是深深烙印在意识中的那个姿态——碧翠丝。

「呃、啊、这」

「对，就是贝蒂，没错。不用担心，可别乱来哦。现在的昴，心和身体的配线一团糟，正处于极其不自由的状态呢」

「哈、呜」

他并非想做什么乱来的事。

只是想坐起身，带着涌上心头的感情一把抱起碧翠丝，然后就这样冲出房间，在宽敞的地方两个人一起转圈圈而已。

但以现在昴的状态，这似乎也是奢望。——心和身体的配线，碧翠丝是这么比喻的。

「——唔」

实际上，昴的大脑似乎确实忘记了如何控制身体。

在无法转动的眼球边缘，勉强能映出碧翠丝的身影，所以才能捕捉到她，但别说手指了，连眼球都无法如他所愿地转动。

别说坐起身了，能勉强呼吸就已经算是奇迹了。

应该说，心脏没有忘记如何跳动，真是太好了。

「说来意外，这可一点也不好笑呢。在被关在那里面的时候，贝蒂倒是还好，但昴的生命活动几乎停止了哦。以至于身体都忘记了那些理所当然的事呢」

「——啊」

「那个空间……是用贝蒂也不知道的阴魔法编织而成的，非常离谱的东西。毫无疑问，是母亲大人插手制作的。那个男人为什么会习得母亲大人创造的禁术，谜团重重呢」

「——嗯」

「关于这个，贝蒂可没打算和昴讨论哦。无论昴怎么说，对贝蒂来说，母亲大人就是母亲大人，是无可替代的人。哼，就是这样」

昴笨拙地插入的，只是些气息微弱的附和。

然而，碧翠丝却能以超群的理解力与之对话，并且，在触摸着昴额头的同时，不满地鼓起脸颊，哼地一声别过脸去。

那种既充满爱意又带着不满、无法偏向任何一方的姿态，虽然可爱得过分——但，

「……这对话真的成立了吗？ 在我看来，完全就是碧翠丝小姐一个人在自顾自地喜忧参半啊？」

忽然响起的声音，既非昴也非碧翠丝，而是第三人。

视野中，碧翠丝「唔」了一声，将目光投向横躺着的昴的脚边，看来声音的主人站在那边。但不巧，昴没有看向那边的办法。

对于那个不在视野中的对象，碧翠丝仍鼓着腮帮子，

「别说这么失礼的话啊。总之，昴和贝蒂的羁绊是无限的……昴想说什么，贝蒂看一眼他的眼睛就全知道了」

「原来如此原来如此，这就是精灵使和契约精灵之间的默契吗？ 我身边倒是有不少与精灵相关的人，但那个领域对外行来说实在很难用感官理解啊」

「别人暂且不论，贝蒂和昴的关系是独一无二的。嘛，不过契约精灵大概都会这么想吧，所以随便装懂反而不妙哦」

「嗯嗯，多谢忠告。哎呀，差不多我也该打个招呼了吧」

如此说着，脚那边的对方似乎向碧翠丝征求了打招呼的许可。

被提出的碧翠丝轻叹一声，用那双大眼睛望向昴。是在问他是否可以让他打招呼，昴用心意点了点头。

「——嗯」

「没办法，就让你见识一下他的脸吧。感恩戴德吧，她这么说」

「那真是感激不尽啊！ 果然和传闻中一样嘴不饶人呢，真是的！」

说着，对方踩着地板，咚咚地靠近。

总觉得，语调有些耳熟——但那个声音本身却陌生。他只能以如同砧板上鲤鱼的姿态，迎接这样一位对象的接近。

碧翠丝缓缓退开，确保住的视野空间里，对方的头探了进来。

那是以绿色为基调的服装与宽大的帽子，以及带有癖性的灰色头发，长相中性的俊美男子的脸——是『不认识』的、温文尔雅的脸庞——，

「你好，初次见面，菜月昴先生。——我叫尼可拉·苏文。虽然有很多头衔，但说起来，商人的身份应该最容易理解吧」

眼角下垂的俊美男子——尼可拉·苏文，如此报上名号。

听到苏文这个耳熟的家名，昴瞪大了眼睛。然而，仿佛要加剧他的惊讶与混乱，对方继续说道。

「想必这突如其来的状况让您很吃惊吧，但在您身体尚无法自如活动的现在，恕我残酷，我要再告诉您一个更令人震惊的事实。——您被『逆贼』阿尔迪巴兰之手封印，直到今天，大约已经过去了四百年」

————。

——————。

——————。

「——。————。————啊？」

「四百年。您明白吗？ 您……不，您和碧翠丝小姐醒来的时候，已经是您所在时代的四百年后了。另外，这个也一并告诉您吧」

理解，完全跟不上。

并非信息量的问题，而是被信息的质所冲垮、吞噬的昴。在如此昴的面前，掀起惊人浊流的俊美男子——与熟识友人有相同特征的尼可拉继续说道。

那是——、

「——不管怎么说，您也让我们等得太久了，菜月先生」

跨越四百年，经由数条生命传递而来的，友人那无奈的斥责。

** 4
——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会哀悼任何人的死。

△▼△▼△▼△

「真是一段漫长而艰难的苦难历史。简直可以说是苏文家代代相传的重大事业。——将沉没于莫格瑞德大喷口最深处，将你们打捞出来这件事」

一边说着，一边用双手转着脱下的帽子的俊美男子——尼可拉，仿佛回想起至今为止的辛劳，深深地叹了口气。

他那谈论背负辛劳的姿态，以及仿佛在说「无可奈何」的语气氛围，都让人感受到尼可拉与友人——奥托·苏文之间的共通点，昴感到胸口一阵揪紧。

很像。越是试图否定，就越是空虚地相似。

但是，一旦承认这一点，就不得不接受现实。

菜月昴此刻所处的这个状况，并非梦境或幻觉，而是现实。

「尼可拉，我理解你想闹腾的心情，也对你感激不尽。不过，昴现在可不是刚病愈那么简单啊。实际上，光是看到你的脸、听到你的名字就已经昏过去了。可别乱来」

「不不，我明白啊？ 我明白，但我也算是等了很久、或者说忍耐了很久啊……打捞现场也好，初次见面也好，都被晾在一边，苏文家四百年的夙愿达成，到底什么时候才能让我有实感啊！」

「实感的话，贝蒂应该已经让你充分感受过了吧。还是说，你被『门渡』来回传送得还不够？」

「别说得好像是我求着您这么做的一样好吗！？」

瞪大眼睛叹息的尼可拉，那姿态简直就像是奥托的翻版。

不过，尼可拉比奥托看起来更年轻一些，身形也更纤细。头发也比奥托长，在背中央处束起，比起商人，更给人一种学者般的风貌。

细节的差异与共通点——尼可拉·苏文，毫无疑问，正如他自己所说——、

「是个一点就通的家伙呢。不愧是奥托的后代」

「真同情先祖大人和两位的交往呢。不过，也正是因为亲近才显得随意吧」

「——是啊。他是个好人，也是个出色的男人。甚至优秀到让子孙把昴和贝蒂挖出来，有点过头了呢」

那听起来，比起优秀，更像是执念深重的插曲。

确实，奥托并非只是偶然加入的成员，他以阵营中不可或缺的能干表现活跃，但真正让奥托成为奥托的，并非他的内政能力或『言灵的加护』，而是他天生的胆识、机智和毅力。

为了达成目的不惜一切努力的坚韧。——那正是奥托·苏文最大的武器，并且最终，他甚至利用子孙尼可拉等人，实现了目标。

真是个了不起的男人。——然而，却再也没有机会当面称赞他了。

再也无法交谈，无法相视而笑。

「——呜」

「昴……」

泪水毫不留情地涌上来，润湿了视野，察觉到昴呼吸一窒的碧翠丝，用手帕轻轻拭去那泪滴。

在碧翠丝温柔的安慰下，昴一边呜咽着，一边感到悲伤被轻轻拂去。

他承认了。不得不承认。

时间的残酷流逝，以及自己败北的结局。

「————」

缓缓地，将菜月昴四散的意识重新收集起来，苏醒前最后的记忆，是普雷阿迪斯监视塔内被『死者之书』书架环绕的一幕。——担忧着昴的心情的阿尔背叛了他，将他连同碧翠丝一起，用禁术封印了。

而自那以后，昴和碧翠丝一直被封印着，度过了四百年的时光，在如今的时代醒来。——那个时代的所有人，都已经不在了。

「——嗯」

忍不住的呜咽和泪水。

只是单纯地，为自己的不争气感到痛苦，想要死去。

丢人、凄惨、难看、想要死一样地逊毙了、笨蛋。

仅仅一次失足，就会发生无法挽回的事。他本应知晓。正是普莉希拉之死，让昴学到了这一点。

尽管如此，菜月昴还是失足了。

失足了，把一切都抛在身后，将义务和使命全部放弃，变成了现在这样。

「——！」

他想要死去。

那不仅仅是因为凄惨和无力感，而是从实际利益角度值得挑战的『死』。

现在，如果『死亡回归』的话，说不定能回去。回到四百年前。

然而——、

「————」

昴的身体无法动弹。连死，都无法靠自己实现。

即便如此，片刻不离地守护着昴的碧翠丝，也不可能允许昴选择『死』。

无法死去。无法死去。

连『死』，如今都从菜月昴的手中滑落。

「想哭的心情，我完全明白哦。尽情地，尽情地流泪吧，昴。无论流多少泪，贝蒂都会全部为你拭去的」

碧翠丝温柔的动作，拭去昴不断涌出的泪水。

既无法怀抱被泪水淹没的希望，却又同时品味着被碧翠丝的关怀所拯救的感觉，昴在希望与绝望的对比中，心灵变得一团糟。

如果，这漫无边际的未来，只有自己一个人被抛下的话，菜月昴的心无疑会破碎，除了腐朽之外别无他途吧。

但是，如果碧翠丝不在场的话，昴或许还能选择自尽。当然，无论怎样，在身体无法动弹的现在，那也不过是无法选择的可能罢了。

「————」

希望与绝望、生与死、过去与未来，正在蹂躏着菜月昴的灵魂。

毫无办法。无能为力。无论如何，都无可奈何。

在这走投无路的绝望中，唯有一点——、

「——啊」

唯有一点，在被蹂躏的灵魂中，有一个发热的疑问。

那是——、

「——呜、呃、呀」

「——我明白的」

颤抖的嘴唇编织出的不确定的声音，碧翠丝将其作为确实的声音接收了。

四百年的时光流逝，世界变迁，昴他们生活的世界中，许多人已经不在世上了。然而，这其中也有例外。

即使历经四百年岁月，生命仍未走到尽头的存在，其代表是——、

「尼可拉」

「嗯，是的。——爱蜜莉雅大人呢」

「————」

那心情，如同紧抓着一根细细的丝线、从天而降的蛛丝。

然而，当那个名字被若无其事地说出时，昴的心脏剧烈跳动到疼痛。他恨不得顺势起身，抓住尼可拉的胸口猛摇，却动弹不得，这让他更加焦急。

不过，他的气势似乎还是传达给了对方，尼可拉一边微微后仰，说了句「好可怕啊」，一边说：

「因为事先被问过，所以我已经告诉碧翠丝小姐了……那个，关于爱蜜莉雅大人呢」

「————」

「实际上，我们也不清楚」

「——啊？」

他怀着像被老虎钳夹住心脏般的感受等待，却等来了一个出乎意料的答案。

忍不住，用不灵活的喉咙发出了低沉的声音的昴，让慌张的尼可拉赶紧「不不不」地在脸前摆手，

「请、请不要生气。不是开玩笑或者卖关子，而是真的不清楚啊！ 关于爱蜜莉雅大人是否平安」

「……那个理由也一并说出来吧。不然的话，我们可无法接受呢」

「那个由碧翠丝小姐来说……这样也太残酷了吧。啊啊真是的，又不能交给露梅拉小姐或罗莎琳德阁下，这可真是一桩苦差事啊」

他使劲挠着自己的头，无可奈何地深深叹了口气。然后，他竖起一根手指，「听好了」，

「首先，为了避免误解，我先说明一下，爱蜜莉雅大人她还活着。这点毋庸置疑。只是，我们无法与她接触，所以不清楚她是否平安无事」

「……唔、呀」

「您一定觉得莫名其妙吧。我再解释得详细些。爱蜜莉雅大人现在，将位于统一帝国佛拉基亚与古斯提克圣王国边境的亚格萨德溪谷——将那条大溪谷整个冰封，切断了与外界的联系。而且」

「————」

「——为了将『逆贼』阿尔迪巴兰，连同自己一起封入那片绝冰之中」

难以置信的信息，被灌输进来，昴再次屏住呼吸。

如果眼皮的活动能更自如些，他大概会眨巴两三次眼睛吧。尼可拉揭示的事实，内容之冲击性，就是如此。

——爱蜜莉雅还活着。但是，在大溪谷中，与阿尔一起被冰封着。

「————」

原理，他明白。

与在水门都市普利斯特拉，将遭受『色欲』权能侵害的人们进行冷冻睡眠相同。爱蜜莉雅本人也曾说过，她曾将自己封印了百年以上。

她对自己和阿尔做了同样的事，将自己封闭在冰中。

其理由是——、

「是为了不让那个男人死去吧。而那也是……」

「呜、呃、我们」

「——为了不失去将昴和贝蒂夺回的方法，对吧」

昴得出了与碧翠丝相同的结论，他由衷地赞同她的这番话。

爱蜜莉雅将阿尔连同自己一起冰封的背景——只能认为是为了让阿尔活下去。而爱蜜莉雅这样做的理由，是因为她认为，只有封印了昴他们的阿尔，才知道解除封印的方法。

至少，如果阿尔死了，审问他的选项就将永远消失。

爱蜜莉雅为了阻止这种情况，采取了强硬手段。

「实际上，考虑到『逆贼』阿尔迪巴兰的所作所为，按当时的情况他是难逃一死的。不过，最终我们用了别的方法来解除二位的封印，所以并没有依赖阿尔迪巴兰的知识就是了」

「那……」

既然被救了，就无法指责尼可拉的选择让爱蜜莉雅的努力白费。但反过来说，既然昴他们已经被回收，爱蜜莉雅也没有理由继续将自己冰封，维持一个谁也无法插手的状况了。

那么，解放被冰封的爱蜜莉雅，也应该能做到。——虽然还不知道该如何与被一起冰封的阿尔交谈。

只是，如果阿尔的目的是将昴永远排除的话，那么他的目标也宣告失败，一个没有胜利者的结局，将在数百年后暴露出来。

即便如此，即便如此。即便如此，至少，如果能见到爱蜜莉雅的话——、

「——实际上，不仅如此呢。无法见到爱蜜莉雅大人，还有另一个理由」

「——！ 没听说过啊。贝蒂还以为，只要融化了那个冰，就能把爱蜜莉雅救出来了呢。你骗我吗！？」

「请您别说这么难听的话啊！ 我不是在骗您，只是，这会导致情况复杂化，所以说明起来比较困难……总之！ 爱蜜莉雅大人为了保护自己不让任何人触碰，将自己连同冰一起封印，但除了这是强力魔法之外，还有别的问题」

「那、嗯？」

「——『魔女』出现了」

「————」

出乎意料的单词，让昴和碧翠丝倒吸一口凉气。

在此刻，『魔女』——是魔女教，还是『嫉妒魔女』，无论哪个挡在面前，这都是何其漫长的问题。

然而，尼可拉接下来的话，进一步颠覆了昴他们的想象。

因为——、

「——『忧郁魔女』以爱蜜莉雅大人所在的绝冰河为据点，将所有试图靠近的人逐个击退。因此，谁也无法靠近」

那是在跨越了四百年的昴他们不知道的地方，新『魔女』的崛起。

** 5
——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会与任何人相拥。

△▼△▼△▼△

「——菜月昴大人！ 听说您醒来了，是真的吗！？」

「咳咳咳咳！」

房门被砰的一声粗暴地打开，吓了一跳，正在吃的粥呛进了昴的气管。

剧烈咳嗽的昴，以及正在他面前喂饭的碧翠丝，被喷出的粥糊了一脸，「呜哇——！」，她整个人都翻倒了。

转眼间，卧室就化作了尸横遍野（字面意义）的大惨剧。

「为、为、为、为什么偏偏要朝着贝蒂可爱的小脸咳嗽啊！ 饭粒全打在贝蒂脸上了哦！」

「啊、呃……因、因为，看着你……才咳的」

「唔……那、那就算了。来，让我看看你的脸。我来帮你擦擦嘴」

对于残留着咳嗽余韵的昴的辩解，擦完自己脸的碧翠丝，叹了口气，也来帮昴擦脸。然而，与她温柔的动作相反，她接下来的一句「那么」，声音却略带冰冷。

不过，那并非针对昴，而是针对造成这一切的元凶。

对于碧翠丝那可爱却带刺的声音，对方吓得肩头一颤。

「你这家伙，刚才倒是闹腾得很欢地闯进来了啊。探望病号的话，总该懂点礼貌吧」

「那、那个，碧翠丝大人……我、我绝无恶意啊！ 我只是，怀着如火般的热忱，一直祈祷二位平安无事……」

「既然如此，刚才差点就由你亲手为那份祈祷画上句号了哦。……既然知道你不是故意的，就别那么畏畏缩缩的了」

「哎呀！ 我，我可是比碧翠丝大人个子高得多呢！ 这个露梅拉，如同熊熊燃烧的火焰一般，长得又高又大了呢！」

「你情绪一高房间就会变热，为了昴，你最好克制一下」

「呜，好的……」

被这么说，垂头丧气地耷拉下肩膀的，是一位拥有亮丽卷曲的绯红色长发与眼眸，身着同色礼服的高挑美女。

身高比昴还高，大概有一米八以上吧。与身高相称的丰满体态，华丽而豪奢的装扮相得益彰，是一位容貌出众的美人。

这又是一位未曾谋面的女性登场，正被碧翠丝扶起上身、亲手喂饭的昴，眨了眨眼睛。

「呃、呃，那个？」

「哎呀！ 哎呀哎呀哎呀！ 您比尼可拉大人所说的要精神得多，我简直像燃起了熊熊烈火般感动不已！ 而且，您和碧翠丝大人也都完全没变……我由衷地感到喜悦！」

「露梅拉！ 好热……不对，应该说好烫啊！」

「哎呀！ 我竟然如此热情似火！」

那位美女大步流星地逼近，碧翠丝插入其间，用小小的身体将她推开。那位美女——被称为露梅拉的人物，在胸前合掌，为自己的气势和行动感到害羞般脸颊泛红，「哦嚯嚯」地干笑着掩饰。

对于她那气势汹汹的接近，昴确实感受到了热气的逼近。碧翠丝所言非虚——露梅拉明显是在感应周围玛那，散发热量。

而且，那还是与情感高涨相呼应的、无意识的强烈反应。从那个事实，以及她有些超脱尘世的气质，昴模糊地猜到了她的真实身份。

「精、灵……吗？」

「——？ 嗯，当然是，像要燃烧殆尽般肯定！ 当然，我可不是普通的精灵哦！ 我，已经是大精灵了！ 自那以后，经过了漫长的岁月，这个露梅拉也已经晋升为大精灵了哦！」

露梅拉如此说着，绽开笑容，将手放在自己丰满的胸前，显得非常自豪。

也就是说，是与碧翠丝相同的人形大精灵——听说精灵在成长时，可以选择自己的姿态，但会选择人形的似乎很少。因此，像这样碧翠丝和露梅拉，两位人形精灵齐聚一堂，是极为罕见的景象。

然而，对于露梅拉的言行，昴感到一种奇妙的违和感。

「说话、没、听过……」

露梅拉的措辞有些独特，或许只是单纯的语言选择比较奇怪。但她的态度中，不仅有为见到昴而感到高兴，还有为「重逢」感到喜悦的意味。

然而，昴对她却没有印象。本来，昴认识的精灵就没几个，根本无需寻找线索。

「————」

「啊，哎呀？ 哎呀哎呀哎呀？ 您怎么了，菜月昴大人……难道说，您并没有为与我重逢而感到如烟熏火燎般的高兴吗？」

「这也太被害妄想了。听说你成为了大精灵，昴只是太吃惊了而已。很快就会习惯的……昴？」

看到昴反应不佳，察觉到他的困惑，露梅拉变得不安起来。然而，安抚露梅拉那份不安的，居然是碧翠丝。

本应是昴绝对盟友的碧翠丝，不知为何，并没有注意到昴对露梅拉的存在没有印象，而是一副「理当知道」的表情。

为何会产生这样的误解，昴决定先解开误会，

「不、啊……」

「——是！」

「诶？」

就在他刚想说出「不」字、稍作停顿的瞬间，露梅拉突然大声回应。她啪地一下亮起脸庞的反应，让昴再次瞪大了眼睛。

不顾昴的惊讶，露梅拉松了口气，抚着自己的胸口，

「哈，我从心底里感到像要燃尽一般安心了。我还在担心，菜月昴大人是不是把我给忘了呢……不过，被您这样称呼，也真是久违了，我很高兴呢」

「名、字……」

被说是在叫她的名字，昴陷入了沉思。

然而，他很快就想到自己的话中何处让露梅拉产生了那种想法，并且也察觉到了那意味着什么，「啊」地倒吸一口气。

她确实，是以为自己在叫她的名字才做出反应的。

因为露梅拉——、

「不、是吗？」

「嗯，是的！ 毕竟，以这副姿态与您相见，还是第一次呢。——我，露梅拉·伊亚·尤克历乌斯，是为了完成主人那如同燃烧般炽热的特别使命，才前来寻找菜月昴大人与碧翠丝大人的！」

「————」

面对那激烈的、仿佛燃烧般的肯定，昴仔细地打量着她。

露梅拉·伊亚·尤克历乌斯——被称为伊亚，并对此予以肯定的她，确实拥有为与昴重逢而喜悦的资格。

与『最优骑士』由里乌斯·尤克历乌斯契约，支撑起他身为精灵骑士的实力与勇名的六位准精灵——不，现已晋升为精灵，并最终达到大精灵之境的存在。

在四百年前，当时还是准精灵的她，曾帮助过昴。那个伊亚，如今作为露梅拉，就这样出现在昴面前。——不对，并非如此。

她在回收昴和碧翠丝时，也提供了帮助。

「露梅拉是尼可拉的协助者吧。而且，她也出力将贝蒂他们从莫格瑞德大喷口拉了出来。这一切，也都是出于由里乌斯的指示吧」

「由里、乌斯……啊」

「是的！ 现在我们六位精灵公主，作为尤克历乌斯领的小领主治理领地。其实拉皮查、索约涅、多蕾娜、琪亚拉、希妮卡，她们也都如烧焦般期盼着与菜月昴大人的重逢，但这次无法前来，实在非常遗憾」

「是、吗」

如同熊熊燃烧的烈焰般积极向前的露梅拉。

她口中说出的诸多名字，大概都是随着由里乌斯的那些精灵们成为大精灵后，现在所用的名字吧。原本的名字似乎作为中间名，家名则冠以尤克历乌斯。

「……花了四百年，守住了与由里乌斯的约定呢。真是个重情义的家伙」

「哎呀！ 我们全员，都是燃烧般一心一意追随主人的。为了实现那位大人的愿望，四百年也是理所当然的！ 为此才与尼可拉大人合作……不不，刚才的发言，是如同火势熄灭般错误的说法」

「错、了？」

「正确的说法是，与历代苏文家的各位合作，才对哦。长年累月的积累结果，在这一代得以实现」

不将功绩独占为自己一人的功劳，不仅是因为露梅拉性格严谨，也是因为她与尼可拉建立了良好关系而达成的共识。

在其背后，有奥托和由里乌斯的存在，昴为此叹息。

「……真是个笨蛋」

与自己契约，长久侍奉自己的精灵们，在自己死后仍以不会消失的盟约束缚她们——这种选择，实在不像由里乌斯会做的，缺乏优雅。

而且，竟与在佛拉基亚帝国时激烈交锋的奥托合作来推进此事，简直不择手段。——不，恐怕这不仅仅是关于由里乌斯或奥托的事。

「大家……」

由于有直接关联的尼可拉和露梅拉存在，奥托和由里乌斯的行动结果更容易理解，但其他人也绝不可能与此无关。

他能明白。他确信。——大家，都是为了昴他们，拼尽了全力。

加菲尔。■■■。法兰黛莉卡。琉兹。梅莉。帕特拉修。罗兹瓦尔。柯林特。安妮罗洁。拉姆。丝碧卡。——雷姆。

为了将拯救昴他们的方法留给未来，而动用力量的的爱蜜莉雅。

除了她以外的阵营成员，不可能没有为了昴和碧翠丝而行动。突然失去昴他们的踪迹，大家都度过了怎样的时光，才走到了今天。

大家在自己的时代，是如何度过的，又是如何迎来终结的——。

「——！」

一切，原本都刚刚开始。

无论是好转的迹象，还是想要改善的志向，一切都刚刚开始。本应存在的未来已失，本应传递的希望也已错过，如今已什么都不明白。

「……露梅拉，你关于贝蒂的同伴们，知道多少？」

「非常抱歉。关于二位阵营的各位，我知道的并不多。在二位失踪之后，亚格萨德溪谷变成绝冰地带前后，实在发生了太多事情了……」

「——。真是没用的家伙」

「呜呜……我，明明已经成为了能与碧翠丝大人比肩的大精灵，但在历经了可与四大精灵媲美岁月的您面前，还是抬不起头来呢……」

当露梅拉无法给出昴所期望的答案时，碧翠丝特意冷淡地如此说道，让这位巨大的精灵公主消沉下去。

这是碧翠丝为了不让昴和露梅拉感到尴尬而给予的关怀。正因为明白这一点，昴愈发觉得自己是个扶不起的阿斗，实在可悲。

至少——、

「哪怕一天、也好……要尽快……」

必须用自己的手、自己的脚，在这个世界里行动起来，去确认一切。

现在的昴，连摆出一副了不起的样子去后悔的资格都没有。

** 6
——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会留下自己的名字。

△▼△▼△▼△

用碧翠丝的话来说，就是变得一团糟的心和身体的配线。——要将其正确地重新连接起来，似乎需要漫长而严酷的康复训练。

「这是长时间被关在那个空间里，只有灵魂状态存在，导致与肉体的连接被剥离的后遗症呢。被束缚在肉体容器中的人类，和贝蒂这样的精灵，情况是不同的」

「久违的，上位存在……讲话」

「贝蒂只是把和昴的差异用语言表达出来，以免昴过分自责罢了。被这样恶意揣测，贝蒂可要大受伤害了。哼，就是这样」

如此可爱地别过脸去的碧翠丝，与昴不同，没有表现出被阿尔的奥尔·沙玛克命中后的后遗症。听她说理由如上，虽然碧翠丝一人平安无事令人欣喜，但懊恼之情也确实更加强烈。

与身体和欧德直接连接的精灵不同，昴必须逐一确认灵魂与肉体的连接，在此基础上，让大脑重新回忆起如何操控连接好的身体。

如果配线弄错，比如想动手却动了脚，据说也可能发生这种驴唇不对马嘴的情况。

「康复、训练……吗……」

对于自己极度不自由的身体状况，昴用结结巴巴的声音如此嘟囔道。

昴自己自不必说，身边也从未有人陷入过这种状况，所以这纯粹是想象——但长期卧床不起的人如果进行康复训练，或许会经历与现在的昴相似的困难。

如果是这样，那诀窍大概也一样。——不要过于急躁，明确目标，一步一个脚印地朝着目标迈进。

而在朝着目标迈进这一点上，现今恐怕没有多少人比菜月昴拥有更强烈的动机了。

话虽如此——、

「——什么啊，朕本以为会比之前有所好转，没想到和上个月毫无变化啊。浪费朕的时间，可是不敬哦，不敬」

有声音如此严厉地评价着投身康复训练的昴的成果。

虽然意见严苛，但昴也无话可说。事实上，那个评价是正确的。客观来看，昴的努力远远谈不上有所成果。

面对无言以对的昴，做出评价的人物「哼」了一声鼻子，

「连反驳的志气都没有吗。真是个堕落的男人。至少，若不能以绝不认输的心志咬紧牙关，那些为你花费了时间的人，怕是难以瞑目吧」

「阁下，您说得太过分了」

「连龙都觉得可怜呢」

「哼，是周围的人太过体贴了。『能好好咀嚼食物真棒真棒。能咽下去就算很了不起了』。——你何不因自己的不争气而气恼得溺死在泪水中呢？」

「您这说得，也太过了……！」

再怎么也不至于被说到这份上吧——正如对方所愿，昴也生气了。

然而，即使听到他硬挤出的怒声，对方也只是若无其事地应付过去，实在是可恨至极。

「你是来捣乱的话就回去，罗莎琳德。昴正忙着康复训练呢。你那边应该也挺忙的吧，统一皇帝」

「朕正是忙里偷闲才来的，你就这般怠慢吗。露梅拉她们也是，你们这些精灵到底打算永远活在世界的秩序之外到何时？ 你们所居之地、所获之食，全都在朕的国土之内哦。碧翠丝，若非你的容貌是至上的可爱，朕早就砍了你的脑袋了」

「你说啊？ ……看你那样子，其实心里在意得工作都做不下去了吧」

「慎言，『金刚姬』。对朕缺乏敬意这点，你和『云龙』也一样。朕是那种欣赏美丽事物的艺术气质，可别因此得意忘形啊」

仿佛在说「可叹」般，将手覆在额头上，发出严厉与否难以判断的言论的人物，深深叹了口气。看到那副模样，面面相觑的是，夹着那位人物左右站立的银发犬人和长着黑色角的小个子少女两人——都是昴和碧翠丝认识的面孔。

那并非在这个时代结识的对象——、

「你们也真是辛苦呢。——阿拉基亚，玛德琳」

「无需龙的多余关照」

「比塞西尔斯强」

交替地，对说出体贴话语的碧翠丝做出回应的是，自四百年前就是旧识的佛拉基亚帝国『九神将』中的两人——阿拉基亚和玛德琳。

令人惊讶的是，在这个时代重逢的两人，外貌和立场都未曾改变，历经四百年岁月至今，仍作为佛拉基亚帝国的一员存在着。

而统率着她们的——、

「你们几个，胆子不小啊。你们把朕当成什么了？ 伟大之统一皇帝，朕可是罗莎琳德·佛拉基亚啊。竟敢无视朕，真是不敬哦，不敬」

如此说着，爆发着与年龄相符的不满的幼小少女——罗莎琳德·佛拉基亚，佛拉基亚帝国当代皇帝，阿贝尔与米蒂亚姆的后裔。

证据就是，她那不逊的言行和傲慢的态度，确是佛拉基亚皇族的风格，但金色的头发与蓝色的眼眸，以及与口吻形成对照的圆溜溜的眼睛——那可爱的容貌，明显带有昴所熟悉的奥科内尔兄妹的元素。

有一次，昴被奥尔巴特变小的时候，米蒂亚姆也同时变小了，那时候的米蒂亚姆和她很像。

「这样啊……就算嘴巴坏，只要可爱就够了……就像阿贝尔那样啊……」

「说的是以卓越治世闻名的文森特·佛拉基亚先帝吧。嘛，反正不如朕有才能的皇帝的事怎样都好。比起这个，无论朕怎么催『金刚姬』都不肯说，所以你来给朕讲讲『青色雷光』的故事吧」

「不说。不说」

「要说要说！ 朕要听『青色雷光』的传说！」

年幼的皇帝短腿乱蹬，吵闹地纠缠着。面对她的要求，阿拉基亚露出一副不能再不情愿的表情，玛德琳则是一脸无奈。

罗莎琳德来访已不止一两次了，昴也逐渐明白，这位年幼的皇帝似乎对塞西尔斯极为崇拜。然而，知道当时情况的阿拉基亚等人却守口如瓶，所以才会来找昴当替身。

当然，昴能讲述的『青色雷光』的故事要多少有多少。

「你一来，康复训练的计划就被打乱了，这可不是什么好事。阿拉基亚也是，别这么坏心眼，讲讲也无妨嘛。你不是和塞西尔斯共度了一生吗」

「完全，不对」

「不对吗？ 既然一起见证到了死亡，说是共度一生也没错吧，龙是这么想的。而且——」

「——。什么」

「因为是塞西尔斯拜托的，所以我帮了他们找人的忙」

被露出恶作剧般笑容的玛德琳如此说道，阿拉基亚的苦相达到了极限。

大概是觉得再说什么也没用了，阿拉基亚放弃了反驳，只是抿紧了嘴唇。但是，得知她帮忙寻找昴他们背后的原因，昴感到一种说不清道不明的情绪。

没想到那个塞西尔斯，会把自己离开后的舞台托付给他人。

「看来你们倒是留下了不少东西呢。朕之所以借出『阳剑』的火焰，也是因为佛拉基亚皇家流传下来的故事……是那个鬼族少女的恳求呢」

「————」

「没有朕的『阳剑』，你们就不可能重见天日。可千万别忘了这一点」

说着，罗莎琳德从空鞘中拔出『阳剑』握在手中。

看着这位年幼皇帝炫耀着那赤红刀身的姿态，昴苦笑着，却深深体会到了这个虽非第一次听说的话题。

佛拉基亚皇帝代代相传的『阳剑』佛拉基亚，其所拥有的强大力量，破坏了封印昴与碧翠丝的奥尔·沙玛克的黑球。

那是尼可拉和露梅拉寻求合作的结果，而罗莎琳德之所以答应这个请求，正是因为她先前的发言——那鬼族少女为了恳求佛拉基亚皇族援助拯救昴他们，并成功做出约定。

「——雷姆」

随着足迹一点点变得清晰，昴每次品味都会感到一种难以习惯的痛痒，以及随之而来的泪水的热度。

雷姆也在悲剧袭击昴他们之后，为了尽自己所能，前往佛拉基亚帝国，并与阿贝尔等人达成了协议。或许塞西尔斯考虑将未来托付给阿拉基亚，也是受了雷姆存在的影响。

实在太多太多的存在试图拯救昴他们，并且最终切实地抵达了那个能够拯救他们的未来。

所以——、

「我……」

「说起来，朕听说了。你们似乎打算，一旦能行动了，就要去挑战那片绝冰河。——说是要与『魔女』正面交锋？」

「——。是啊」

昴简短地点头，肯定了罗莎琳德的提问。

现在，昴通过康复训练恢复身体自由的目的，就是为了与被认为身处绝冰地带的爱蜜莉雅重逢。——虽然尼可拉和露梅拉表示这非常危险，希望等身体恢复后再详谈，但昴并不打算改变主意。

确实，事已至此，昴和碧翠丝不得不放弃很多东西。

但是，与那些因无法触及而不得不放弃的事物不同，爱蜜莉雅必定就在那里。这绝不会成为放弃的理由。

「虽是荆棘之路，但敢于踏上这条路的姿态倒也不坏。在这魔女教也已随王国的灭亡而消失、对『嫉妒魔女』的恐惧也几乎流于形式的时代，唯有『忧郁魔女』的存在仍让『魔女』这一称号带着畏惧……若她能消失，对朕而言也意义重大」

「————」

「唔，为何沉默不语。不敬哦，不敬」

「沉默也是理所当然的吧。你就不能稍微体谅一下贝蒂他们的心情吗。对贝蒂他们来说，那些载入史册的事件，也仿佛是最近才发生的事。更何况，王国……露格尼卡的灭亡，也实在难以接受啊」

「无法战胜接踵而至的苦难就会灭亡。无论是人、土地还是国家，道理都一样。露格尼卡也好，卡拉拉基也罢，都不过是历史书上悄然消失的名字罢了」

仿佛在说世间常态一般，统一皇帝——身为吞并了露格尼卡王国和卡拉拉基都市国家的佛拉基亚帝国之首的罗莎琳德，耸了耸肩。

老实说，难以置信的事件接踵而至，以至于对这件事本身，昴也无法确定自己是否已经完全感到震惊。坦白说，与四百年流逝、一切都被抛在身后的这个事实相比，没有任何事情能比这更动摇昴他们了。

话虽如此，对于一个直到前不久还在为争夺王国王座而全力投入王选的人来说，王国灭亡的消息，也绝非能够轻易接受。

「在时间的洪流中，有的事物会改变，有的事物不会改变。无论你从中看出何种价值，仅仅是随波逐流而后悔，是愚蠢的行为」

这或许是这位外表虽年幼，却与人类共同生活了超过四百年、持续注视着人类活动的古老龙人，给予的忠告或告诫吧。

即使是玛德琳、阿拉基亚，或是吞并三国、成为更庞大国家的佛拉基亚皇帝罗莎琳德，也无法阻止时间的流逝。

正因为如此，才要告诫他们不要唯唯诺诺地随波逐流——他如此认为。

无论如何——、

「——干吧」

「就是这个气势。贝蒂也会全力支持昴的」

时间宝贵。时间再多也不够。

无论多么珍惜，它都会像沙粒般从指缝间滑落，再也无法收回。所以，要在它还在手中的时候珍惜它。

正如不要在失去之后，才意识到自己有多么幸运。

** 7
——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会寻求安宁。

△▼△▼△▼△

——与焦急的心情和康复训练进展缓慢的焦躁相反，昴他们的日子舒缓而平淡，讽刺般地、平顺地流逝着。

「既然是碧翠丝小姐的希望，那么菜月先生身边的基本照料就交由您负责了。如果有什么需要，请随时吩咐。太大的房子也容易让人感到空旷，暂且就请随意使用这栋房子吧」

虽然对尼可拉如此大方地提供一栋房子感到惊讶，但现在的昴他们别无选择，只能接受他的好意。

不过，当昴告诉他一定会还清这笔人情时——、

「借贷一定要清算清楚。作为商人，这也是我认同的思维方式。不过，对于菜月先生你们，我并不太把这看作是借贷」

「那是、为什么」

「嗯。……或许是因为，长年来的辛苦终于有了回报，是因为菜月先生他们得救了，我是这么想的吧」

「————」

「我在苏文家算是个比较另类的人。兄弟亲戚们相对更稳重些，想法也更成熟，但我好像不太适合。人们常说，我要么成就大业，要么落魄而死。而结果，就是这样」

「这样……」

「我实现了苏文家四百年的夙愿。至少，这样一来，无论何时死去，我都能在落魄而死之前，做成了些什么——可以这样挺起胸膛。所以，无需回报。请你们度过一个能让我觉得‘帮上忙真好’的明天」

面对如此爽快说出口的尼可拉，说不觉得欠了大人情是不可能的。而且，这让他再次强烈地感受到——被称为苏文家另类的尼可拉，那无法隐藏的、如同奥托般的特质。

「打扰了，菜月昴大人！ 之后您身体感觉如何？ 这个露梅拉，可是如烈火般燃烧般牵挂着您呢！」

虽然不知道尤克历乌斯领的统治情况如何，但露梅拉经常来露脸，大概也是因为她与碧翠丝建立了友谊，总之她对他们非常关照。

她从伊亚时代起就一直受她照顾。其他姐妹虽然不方便来探望昴，但据说日常话题中也会提到。

「这也自然成为了我们回忆起主人的契机，我们也如同燃烧般度过着宝贵的时光。当然，没有一天不想念主人，但我们也正在品味着色彩与滋味都愈发浓厚的回忆呢」

「那、真是……复杂的心情啊……说起来，你们找到我们的时候，那时……」

「哎呀！ 哎呀哎呀！ 您想听吗？ 那可真是、真是，如同燃尽般的大事啊！ 毕竟，莫格瑞德大喷口的大洞，可是连接着这个世界的另一面，要寻找流入其中的东西，可费了好大一番功夫……」

「……能、找到……真不容易啊」

「当然，并非一次就成功了。历经四百年，我们收集了不足的技术和力量，大家齐心协力，才终于完成了这件事」

「————」

「所以，菜月昴大人，请您千万不要悲叹。未能将您送回主人生活的那个时代，我们也深感痛悔。但是……」

「嗯嗯。我知道，露梅拉。——谢谢你」

四百年——说起来只是一句话，但对于真正度过那段时光的人来说，却有着难以估量的重大意义。

碧翠丝在『禁书库』中度过的日子，讽刺的是也大约有四百年。——不用说，碧翠丝知道那段时光的分量。

四百年这个时间，终结了昴他们熟知的人们的生命，也终结了其后继者们的生命，即便如此仍遥不可及——这一点，她同样明白。

在无数连昴他们都不认识的人，为了拯救昴他们而奋斗的基础上，才有了如今的昴他们——这让他深切地感受到这一点。

「无聊的感伤。像朕这样立场的人，将希望寄托于你们这样杂乱的尘埃，既非始于此，亦非终于此」

明明没有商量任何事，罗莎琳德却凭着她天生的洞察力看穿了昴心中的烦恼与懊悔，仿佛嘲笑般地说道。

对于真挚的烦恼，这态度确实过分。然而，却无法生气——不仅是因为被她的外表所迷惑，更是因为她的真心并不像言语那般尖锐，她的行动与待人方式，清晰地传达给了昴。

「话说回来，你这家伙根本没什么进步嘛。到底什么时候，才能重现朕听闻的在剑奴孤岛上传为佳话的传说中的『斯巴鲁卡』呢？」

「那种事……怎么可能做到啊」

「安心吧。不用操心，朕也不打算让你去和吉尔提劳那种不懂玩笑的野兽交手。让『金刚姬』或『云龙』来吧。如何？」

「如何个头啊，笨蛋吗？」

「竟敢说朕是愚者？ 不敬哦，不敬啊」

罗莎琳德咯咯地笑着，展现出毫无防备的姿态。她以听古代传说为名义来到昴他们这里，看起来倒像是在放松休息。

罗莎琳德的优秀程度，除去年龄因素，恐怕也不输给阿贝尔——这一点不难察觉，但要治理比阿贝尔时代大了近三倍的统一帝国，想必需要巨大的辛劳。

昴无意依赖他人，但尼可拉和露梅拉并不催促昴，而罗莎琳德的严厉言辞，却有着鞭策的效果，让人挺直腰板。

不过——、

「失算。本以为你说了，她就不会再来问我了」

「但知道得越多，兴趣似乎就越浓厚呢。看阿拉基亚为难的表情也是阁下的趣味所在，看来你被耍得团团转呢」

「……玛德琳，你也帮帮我啊」

「想把龙也随心所欲，未免太得意忘形了吧，人类」

对于罗莎琳德的态度，实实在在吃了苦头的阿拉基亚，似乎并不欢迎昴以及助长这一切的玛德琳的态度。

老实说，即使过了四百年，阿拉基亚仍未完全消化死后的塞西尔斯的事，这或许是她自身的问题，但昴和玛德琳都乐得将其保留作为调侃的素材。

总而言之——、

「——昴，今天也辛苦了」

无论有无来客，一天的结束，必定是与亲爱碧翠丝一同度过。

面对内心焦躁的昴，碧翠丝或许处于更为煎熬的立场，但她却从未流露出那种表情。

他明白，那是碧翠丝的温柔。

但是——、

「是你想太多了。贝蒂只是清楚地知道，焦躁也得不到好结果而已。毕竟贝蒂也是八百岁的大人了呢」

「真、是个老、太太……」

「竟、竟敢如此口无遮拦！ 贝蒂虽然不会催你，但可会因为无礼而生气的！ 而且，如果昴气馁了，贝蒂可是会好好训斥你的」

「气馁、的话……」

「是啊。——除此之外，贝蒂是绝不会动手打昴的。在最初醒来的时候，我说过的话。你还记得吗？」

「————」

「无论发生什么，只要贝蒂和昴在一起，就一定能挺过去」

对，没错。她确实是这么说的。

而且，必须真正付诸行动——这正是昴的动力源泉。

日子一天天过去。平淡无奇。但绝不能漫不经心地接受这一切。

时间珍贵得令人惋惜，一天也好，一时也好，一秒也好，都不能浪费。

那就是——、

** 8
——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会哀叹失败。

△▼△▼△▼△

——那，横亘在菜月昴前进道路上的，是毫无特别之处、一成不变的一日中的一幕，换言之，便是毫无预兆的凶事。

「——吾思，故吾在。常思」

那个身材魁梧的男人，突然闯入了昴和碧翠丝的日常。

身着华丽的黑色服装，肩上披着白色外套。明亮的黄绿色头发被仔细地梳理整齐，与浅黑色的肌肤形成鲜明对比，使其存在感更加突出。

他那粗犷而端正的容貌中，宿有一种野性的高贵——这种矛盾的气质，将一种过目不忘的存在感，直接烙印在脑海中，是灵魂色彩浓烈之人。

正因如此，毫无疑问，他是初次见面。

与露梅拉那时不同，并非认识的人随时间流逝改变了容貌。那个不请自来的男人，突然出现在了晚餐的席上。

恰好那天，尼可拉、露梅拉以及阿拉基亚也聚在餐桌旁。

并非事先商量好的，在比平时更热闹的餐席上，昴也正想展示一下康复训练成果，就在此时。

「根据经验，愤怒这种情绪只会持续大约六秒。仅仅六秒。只要能熬过那六秒，便能避免愤怒这种原始情感的爆发及其最大化」

对于闯入家中的男人，昴目瞪口呆。然而，与昴不同，其他所有人瞬间变了脸色，踢开椅子站起来，进入戒备状态。

动作最快的是在场最强的——不，放眼全世界也是最高级别压制力的阿拉基亚。

在佛拉基亚的『大灾』中，因吸收了一部分四大精灵之一的『石块』姆斯佩尔，『噬灵者』阿拉基亚获得了超越常理的力量。

历经岁月，她将那份力量更进一步地化为己用，被称为『金刚姬』，作为当代皇帝罗莎琳德·佛拉基亚的心腹，毫无保留地发挥着力量。

「也就是说」

从阿拉基亚全身，数条闪闪发光的光带延伸而出，化为最高硬度的刀刃，无情地切割所触之物，在餐桌间狂暴地奔流。

十二条光带，它们瞄准的，是傲然站立的褐色大汉。那男人的左脸上，梵文风格的刺青淡淡发光——、

「——为了能让对方最大限度地体验到吾之愤怒，必须在六秒内了结一切」

瞬间，以男人为中心的狂乱光芒爆发，将本应切割他的光带正面横扫，并将其施术者阿拉基亚切成二十八块——那道斩光的余波呈爆炸性扩散，左右两侧的尼可拉和露梅拉也被轰飞了。

然后——、

「正好六秒」

面无表情地断言的男人，他双手不知何时握住了双剑——从握柄处延伸出光之刀刃的，两把奇特的剑。

那便是瞬间斩杀阿拉基亚，余波也秒杀了尼可拉和露梅拉——并且，由剑风波及，将昴也逼至濒死的剑舞的真面目。

「——啊」

仰面倒在地板上，沐浴着准备好的晚餐残骸，昴呻吟着。

没有疼痛。讽刺的是，尚未完全康复的昴的身体，不仅活动不便，连痛觉在内的五感配线也一团糟，袭向肉体的这场突发悲剧，也仿佛像隔着屏幕发生的事一样缺乏实感。

但是——、

「……你，到底是什么人」

「——。真令人惊讶。惊讶，且吃惊。竟然还活着吗」

即使袭向自己身体的疼痛如同他人之事，但为了庇护自己而张开双手站立的碧翠丝的坚强，却无法视而不见。

在冲击波袭来的瞬间，她迅速保护了自己和昴。碧翠丝一边懊悔自己未能顾及尼可拉等人，一边瞬间压下那份心情，锐利地瞪向凶手。

她眼中，有着明确的愤怒和一丝困惑。——困惑的理由，是。

「人类……？ 还是说，精灵……？」

「两者皆是，两者皆非。吾即吾。并且——」

「呃啊、快、快逃……！」

那如同吐血般的觉悟的呐喊，却因声音嘶哑，未能形成有效的牵制。只是，让碧翠丝那小小的身躯，背负了不相称的觉悟，鲁莽地发起挑战。

其结果，不言而喻，惨不忍睹。

「——精灵这种污秽，当除。六秒」

在那残酷的宣告之后，不到六秒，碧翠丝，以及菜月昴，便一同从这个世界上被消灭了。

相隔四百年，许多人连接起希望，最终被拖曳至遥远未来的精灵与契约者——作为二人的结局，实在是过于悲痛的落幕。

而这——、

×　　×　　×

「——吾思，故吾在。常思」

当意识恢复清晰的瞬间，菜月昴回到了晚餐时有闯入者的那个场景——这标志着他在四百年后，与『狂皇子』维格·阿德加尔德之间，那场绝望的、看不到胜算的泥沼攻防战的开始。

** 9
——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会寻求任何人的理解。

△▼△▼△▼△

——『狂皇子』维格·阿德加尔德。

那是与『剑圣』莱因哈鲁特·范·阿斯特雷亚、『青色雷光』塞西尔斯·赛格蒙特、『礼赞者』赫鲁贝尔并驾齐驱的四大国最强者之一。——那不过是昴他们生活的四百年前的情况，需要加上这个前提。

露格尼卡王国的『剑圣』、佛拉基亚帝国的『青色雷光』、卡拉拉基都市国家的『礼赞者』——与之对应的是古斯提克圣王国的『狂皇子』，但与其压倒性的知名度相比，其本人的信息却少得惊人。

作为圣王国皇族一员，却亲手杀害了与自己立场相同的十数名血亲，由数千军队耗费七天七夜才终于镇压并囚禁——这个逸闻广为人知——不如说，除此以外几乎没有流传出任何风声的存在。

也正因为那过于荒唐的传闻，甚至有人怀疑『狂皇子』本身是否存在，或许只是圣王国为了牵制他国最强者而演的一出戏。

然而，那怀疑终究只是怀疑。
『狂皇子』是真实存在的。其实力，也与传闻相符，是压倒性的强者，从同时了解与之并列的三位最强者的人的角度来看，也可以断言他足以与他们匹敌。

而与他们不同，只有『狂皇子』，在四百年后的今天仍然存活。

其机关在于——、

「——人类、和、精灵的……混血？」

「这就是所谓的公开秘密吧。据说他是世界上唯一的『精灵人』」

尼可拉那如同咬碎苦果般的话语，让昴不禁倒吸一口凉气。

人类与精灵的混血——对于这种存在竟然可能诞生感到惊讶，以及，那个『精灵人』竟然在追杀精灵，这个无法理解的事实。

诚然，世界上存在着像碧翠丝或露梅拉这样，拥有与人无异的外形的精灵。但是，由玛那构成身体的她们，其玛那体的根本原理就与人不同，似乎不可能生育后代。

然而——、

「事实上，他确实存在。作为公开宣称要消灭精灵——那些构成其自身根源一部分的存在——的世界最大灾害」

尼可拉的确定信息，让菜月昴意识到。

迄今为止，昴遭遇了各种各样的强敌，每次都陷入苦战。即便如此，真正不得不战斗的存在，除了魔女教那些脑子不正常的家伙，也就只有托德·方格、艾尔莎·葛兰西尔特等少数例外。

即使是托德或艾尔莎，昴有时也会觉得，或许依据方式和目的，也能并肩作战。——而眼前这个对手，他眼中没有那种可能。

昴所爱之人的许多，都与精灵的关系密不可分。——换言之，『狂皇子』维格·阿德加尔德，是绝对无法与菜月昴相容的存在。

一个要消灭精灵的存在，昴绝不可能与之并肩同行。

「——六秒」

何况，『狂皇子』挥舞的刀刃，为了杀死精灵，完全不介意波及周围。因此，昴又一次被杀。

一次，两次，十次，二十次。——计数，无情地累积着。

在这四百年后的时代，一次也未能尝试的『死亡回归』，能够发动，可说是万幸。即便它的重启点并非设定在四百年前——除去那份失意与沮丧，也堪称万幸。

只是，这留下了一个巨大的问题。

那就是——、

×　　×　　×

「——吾思，故吾在。常思」

在『狂皇子』的暴虐即将再次开始的瞬间，菜月昴回到了那个时间点——然而，此时的昴康复训练尚未完成，仍处于没有他人帮助就无法站立的状态。

「——六秒」

然后，什么也做不了的昴，他的世界再次被斩光撕裂。

△▼△▼△▼△

——在菜月昴所经历的『死亡回归』的螺旋中，『狂皇子』的这次强袭，也堪称是最糟糕级别的苦难。

若要类比，或许可与在魔都卡奥斯弗雷姆与奥尔巴特·邓克尔肯的捉迷藏，或是在剑奴岛金纽海布包括『斯巴鲁卡』在内的一系列事件相提并论。

然而，那时虽然身体缩小了，但手脚仍能自由活动，为了打破局面，也能亲自去尝试各种方法——与那时相比，现在的障碍简直如同天堂。

因为，即使在经历了数月的康复训练后，菜月昴的身体不自由状况也几乎没有改善，连独立行走都做不到。

在此基础上，对手还是昴迄今为止遇到的敌人中，与初代『剑圣』雷德·阿斯特雷亚一样拥有荒唐力量的家伙，生存的希望比针眼还要小。

因此，昴一直在死。

无法拯救阿拉基亚、尼可拉、露梅拉，甚至无法让碧翠丝逃走，反而因为自己不自由的身体阻碍了她们逃跑的路线，让她们不断死去，自己也一次次死去。

「真是个令人焦躁到极点、烦人的家伙！ 把我们视为眼中钉……因为你的缘故，尤克历乌斯领可是遭了大殃啊！」

理所当然，对于以灭绝精灵为目标的『狂皇子』而言，由六位大精灵统治的尤克历乌斯领，可以说是绝对不能存在的土地的前沿阵地。

或许之前也曾多次交锋，露梅拉对现身的『狂皇子』的感情，是恐惧与愤怒各占一半。

「那把剑，塞西尔斯想要。夺走它，在墓碑前折断」

据阿拉基亚观测，『狂皇子』双手所持的双剑，那寄宿着光之刀刃的，是与『龙剑』和『阳剑』齐名的世界著名魔剑——『咒剑』艾欧恩。

据说能吸取持有者的玛那，并发挥相应锋利度的『咒剑』，其剑风能够轻易突破被称为『金刚姬』的阿拉基亚的防御。

面对狂暴的斩击，现状的昴他们几乎没有防御手段。

「糟了糟了糟了！ 虽说大意了听起来像是我们的过错，但这难道不是无法预料的灾难吗！？ 毫无预兆地撞上世界最恐怖，事前准备根本来不及啊！」

在这场合中，继无法动弹的昴之后，毫无战斗力的尼可拉，面对突发遭遇战，脸色苍白地拼命叫喊。

看来和奥托不同，尼可拉这边似乎是个纯粹的商人，并没有在险境中也不动摇的胆量。不过，要求比奥托年幼的他做到那一步也过于残酷，只要不拖同伴后腿就已经很了不起了。

而最重要的是——、

「昴，由贝蒂来保护。——只有贝蒂了，不是吗」

无论被『狂皇子』的刀刃夺去多少次性命，碧翠丝总会挡在昴的命运终结之前，用那小小的身躯庇护他。

她那不变的奉献精神，每一次都让昴的心振奋起来——因此——、

「——六秒」

即使在不断重复的『死亡』螺旋中，昴的心也未曾屈服。

一旦屈服，就再也站不起来了。所以，屈服才是最可怕的。为了不发生那种事，昴——、

「好、好！ 就是现在！」

「——E・M・T！」

呼应昴拼死的表情，碧翠丝发动了E・M・T——绝对无效化魔法的领域展开，将围坐在餐桌旁的昴他们全部包裹其中。

在这个领域中，一切与玛那相关的效果都将被无效化。这同样适用于身为『噬灵者』的阿拉基亚和大精灵露梅拉。正因如此，如果仅此而已，那无异于资敌行为——但、

「——那是、魔剑吧！？」

『咒剑』艾欧恩的刀身散开，光芒扩散到E・M・T的领域内。

这正合意图，它切断了『狂皇子』所持魔剑的效果，成功地将此前数十次斩杀了昴他们的死因，首次阻挡在外。

「奇妙的魔法，产生奇妙的效果。出乎意料」

初次攻击被E・M・T妨碍，『狂皇子』第一次说出了攻击性以外的话语。紧接着，阿拉基亚的猛烈踢击，狠狠地砸在了『狂皇子』的侧脸上。

「去死」

身为『噬灵者』的阿拉基亚，其体内吸收的精灵之力被E・M・T封印。然而，即便如此，她的身体能力也是世界顶级。

全力踢击的威力如同炮弹，实际上，冲突声与扩散开的冲击波，蕴藏着能将锻炼过的战士头颅一击折断的火力。

不过——、

「不巧，吾没有回应阁下请求的理由，故而不应」

相对的『狂皇子』，也是与阿拉基亚同级或以上的怪物。
『狂皇子』用只握着剑柄的魔剑的手，轻松接住了阿拉基亚的踢击。男人与女人，手与足，攻与防——种种对比条件，都被他以力量强行压制。

然而，『狂皇子』的对手，并非只有阿拉基亚一人。

「还有我呢！」

高声呐喊，从后方用椅子猛击『狂皇子』的，是露梅拉。

早早放弃使用魔法的大精灵，趁着阿拉基亚吸引注意力的空档，绕到『狂皇子』背后，利用自己高挑的身材，毫不留情地挥下椅子。

随着碎裂声，木制椅子粉碎，后脑勺遭到无防备重击的『狂皇子』，身体前倾摇晃。有效果了——一丝期待涌上心头——、

「干扰了玛那的构成吗。了不起，了不起。但是——」

瞬间，从站稳脚跟的『狂皇子』体内，接连飞出的光刃，分别斩断了阿拉基亚的双臂和左腿，以及露梅拉的躯干。

「什……」

「——『适应的加护』」

目睹构成存在的玛那泄露、被击飞的阿拉基亚等人，昴倒吸一口凉气，『狂皇子』的目光转向了他。

瞬间，将昴他们判定为危险的『狂皇子』，在理应一切无效化的领域内发动了『咒剑』，其光刃呈袈裟斩状放出——、

「——E・M・M！」

刹那，碧翠丝切换魔法，在千钧一发之际将昴的性命从死亡边缘拉了回来。

「————」

作为无法动弹的代价，偏移了半步世界的昴他们，攻击不再能触及。但，也并非没有攻击手段。

「印、普罗！」

不可视的黑色魔手从昴的胸口显现，它逼近『狂皇子』的面门。打算用这一拳击中他的面部，趁其不备之际，再用碧翠丝的阴魔法轰击。

最坏的情况，即使昴因玛那耗尽而昏厥也无所谓。只要能将『狂皇子』，用阿尔·沙玛克送到异次元去。

「露骨的视线诱导。是陷阱？ 若不是陷阱，那便是幼稚」

面对那不可视的拳击，『狂皇子』只是轻轻歪头，便轻易躲过。

E・M・T已被应对，E・M・M的防御也无法持久。更重要的是，E・M・M能保护的只有昴他们，周围的同伴仍是毫无防备的状态。

阿拉基亚和露梅拉都需要立即治疗。当然，尼可拉也是——、

「————」

尼可拉，没有反应。

并非战斗人员的他，本应退到后方，以免妨碍昴和阿拉基亚他们。

「老实说，因为太过突然，我并没有把握这手准备能否奏效」

就在昴注意到的下一刻，退到墙边的尼可拉举起了右手。然后，他的手指用力弹响，奏出高亢的声音。

那动作，正是与尼可拉有着相同特征的先祖，在暗中布置什么时，喜欢用来作为触发开关的习惯性动作。

而那个习惯与缜密心思，似乎也完好地遗传给了子孙——、

「——可、可什么都没发生啊！？」

本应与昴抱有同样期待的碧翠丝，看到毫无变化，瞪大了眼睛。

莫非是哑火——焦躁感在昴的背上一掠而过。然而，弹响手指的尼可拉脸上并无悲壮之色。有的，只是孤注一掷的赌徒的目光。

面对他，手持『咒剑』的『狂皇子』眯起了眼睛——、

「——真奇怪。我应该说过，别动我的冰河才对吧？」

声音响起。——刹那，从四面八方涌来的无数白光，从外侧刺穿了尼可拉准备的安全屋，凶恶的光之乱舞蹂躏了室内。

「————」

不知道发生了什么，昴呆然地看着眼前的景象。

一瞬间，尼可拉提供的昴他们的临时住所崩塌，被光芒炸飞的遗址，化作了白茫茫的粉尘弥漫的惨状。

『狂皇子』的身影已不在近前，脑海一角认为是光之爆炸将其炸飞了。下意识扑进昴怀里的碧翠丝，也瞪大了那双大眼睛，带着惊讶的表情望向这边，「啊」地一声倒吸一口气。

「昴、昴，你的脚……」

「脚……？」

听到碧翠丝颤抖的声音，昴艰难地低头看向自己的身体。因为那话语中不祥的预感，他还以为至少会有一条腿被炸飞，但只要持续发动的E・M・M还在，无论何种灾厄都无法伤害他们。——相对的，存在产生偏移的昴他们的实体，被光所贯穿了。

「这、这是……」

在眨眼的昴的眼下，仿佛贯穿残像般刺入的光——那带着松散闪烁的，是一根长长的针。

长度从昴的肘部到指尖左右的针，由玛那构成的它，在完成使命的瞬间便松散碎裂，消失不见。——这，他有印象。

恐怕，他曾无数次被与此相同的光芒夺去性命。

但是，那本应是，无论多么希望也不再会发生的——、

「——是你吗」

那压抑了感情的低沉声音，震动着昴因惊愕而麻木的耳膜。

猛然望向那边，昴和碧翠丝看到的是——弥漫的烟尘对面，缓缓侵蚀视野的，是那可怕男人脸上散发着淡光的刺青。

身处光爆中心，『狂皇子』身上却连一道擦伤都看不到。

然而，在近百次『死亡回归』中都从未动摇过表情的『狂皇子』的侧脸上，昴第一次看到了戒备的神色。

而『狂皇子』那戒备的矛头，指向的是——、

「又在欺负弱者了？ 你不腻吗，『狂皇子』先生」

身着融合了数种色彩礼服的、美丽的『魔女』，站在那里。

「————」

『魔女』。没错，是『魔女』。

一眼望去，除了那个之外不可能是别的——菜月昴，不，所有有生命之物，都会因本能的警钟而被迫理解这一点。

看到山一样巨大的怪物，闻到嗜血野兽的腥臭气息，听到锁定目标的龙的咆哮——任何人都会本能地察觉到那是对生命的威胁。

同样的功能在说。——那东西，是『魔女』。

「令人不快，令人不快。将吾之行径如此矮小化，令人不快」

时钟方向上，十二点钟方向是『狂皇子』，三点钟方向是『魔女』——将两者分别纳入视野两端，昴无法抑制涌上的颤抖。

这或许正是当今世上最恐怖的存在之间的邂逅吧。

但，不仅如此，对于昴而言，还有更深的意义。

「……昴」

不对。现在呼唤昴的碧翠丝也同样。——昴他们，有更深的意义。

因为，出现在那里的美丽『魔女』——、

「——六秒，对吧？ 『狂皇子』先生的执着」

「————」

「那么——」

『魔女』轻轻歪了歪头，用那阴暗而湿润的目光，从唇间溢出美妙的声音。在她把话说完之前，『狂皇子』动了。

他与『魔女』之间的距离瞬间消失，『狂皇子』的刀刃正要左右横扫那纤细的脖颈——刹那，『狂皇子』的双剑被倾泻而下的光雨所阻挡。

光雨产生的冲击波与爆音，毫不留情地捕捉了处于战斗状态的『狂皇子』。『狂皇子』用双剑将其击散，防御、防御、防御。

然而，由此产生的片刻时间，对于与『魔女』为敌而言，却是致命的瞬间。

「我会给你百万倍。——『压缩痛苦』」

如此说着，『魔女』啪地打了个响指。——下一瞬间，操控双剑的『狂皇子』的动作失去了精准。在精确无比的剑舞中产生的破绽里，倾泻而下的光之风暴穿透防御，接二连三地刺入男人的身体。

而且，这还没完。光芒深深剜入『狂皇子』的身体，在其伤口最深处爆裂，将这位世界最强者的一角，从内部炸得粉碎。

「————」

面对那压倒性的力量冲突与瞬间的结局，他惊愕得说不出话来。

当光爆造成的视野压迫消散时，那里已不见『狂皇子』的片缕残骸。那位可怕的强者，被『魔女』一人瞬间屠戮。——不，并非一人。

「辛苦了，红蝎酱」

『魔女』发出慵懒的叹息，缓缓来到她身旁的，是比地龙还要巨大、披着赤红甲壳的巨型蝎子——魔兽。

被『魔女』带来的魔兽，那便是发挥出那压倒性光之压制力的正体。

而那个组合的背景是——、

「……喂，还要打吗？」

「——不，不甘心，虽不甘心，但吾认输。不甘心的是，吾败了」

「——！」

一股寒意窜上脊背，昴将意识转向声音的方向。光雨倾泻而下的爆心地，在距离约十米的地方，那里的雾气摇曳着——不，不对，摇曳的并非雾气，而是如同霞光般淡薄的人影。

存在被削弱到极限的『狂皇子』，如同雾气般站在那里。

「将肉体与玛那体切换……那、那怎么可能……」

「若论可能与不可能，吾之此身便是实证。虽令人恼火，但该说的并非不可能，而是不可解吧。令人恼火的是」

碧翠丝不由自主地低语，而『狂皇子』却仿佛在谈论别人的事一般，带着漠不关心——甚至夹杂着虚无感，如此回答。

碧翠丝随即沉默，存在稀薄的『狂皇子』望向『魔女』，

「若阁下在此，那绝冰河岂非空虚？」

「也许吧。但没用哦。我怎么可能毫无防备就离开呢？ 毕竟大家都比我笨嘛」

「————」

「谋划也是没用的。我和你们，能烦恼的时间可不一样哦。还是说——这次想要六千万秒？」

「阁下打算为此游戏付出何等代价？」

「谁知道呢？ 那跟你有关系吗？」

『狂皇子』与『魔女』之间，弥漫着剑拔弩张的紧张气氛。两人看似都在压抑情感，但彼此视对方为障碍这一点，却是显而易见的。

感受到那份战意的高涨，被称为红蝎的魔兽摩擦着双钳。双方的对峙持续了片刻——、

「——非自然的污秽，吾将亲手尽数消灭。记住，勿忘」

「那你不如先消灭自己？」

「那还为时过早，过早。——尚未到时」

那宣告，是对『魔女』说的，还是对与『魔女』所称的污秽相互依存的昴说的呢——『狂皇子』的存在逐渐淡薄，从现场消失。

不是假装消失，而是真的消失了。威胁已去。不过，留下了另一个威胁。

「留下那种人，真是受够了」

『魔女』为消失的『狂皇子』的存在轻轻叹息，耸了耸裸露的白皙纤细的肩膀。然后她轻抚身旁魔兽的甲壳，转过身来。

随着她的动作，束起的长长赤褐色头发和巨大的缎带随风摇曳。她就那样，『魔女』迈开脚步，走向昴和碧翠丝——却从他们身边走过，向后方走去。

他慌忙用目光追随着她的背影，这才注意到。在昴他们的身后，是伤痕累累的阿拉基亚和露梅拉，以及被她们护在身后的尼可拉。

在那场炸飞房屋的光爆中，三人竟都活着。看来是在E・M・T失效的瞬间，能够使用魔法的阿拉基亚她们设法应对了。

不过，并非毫发无伤。伤势最重的是——、

「对我的地盘动手的，是你吧？」

「——！ 您、您在说什么呢……？」

「哈，毫无意义的试探真让人累。听好了，魔纹因人而异，只要仔细调查，谁设下了什么陷阱，一清二楚。我有的是时间调查。所以，是你干的。那，这就是报应」

说着，『魔女』那白皙的手指，指向了瘫坐在地上、膝盖以下消失的尼可拉的左腿。

「————」

「很痛？ 那就别再做这种事了。被人随意利用，让人很不愉快」

她对着鲜血淋漓、满头大汗的尼可拉如此宣告，然后无视怒视着自己的阿拉基亚等人，抚了抚头发，转过身去。

她就那样，没有对尼可拉他们、也没有对昴他们说话，准备离开——昴不由自主地叫住了她。

为此，他呼唤的言语是——、

「——■■■」

——如此呼喊的话语，却不知为何无法顺利说出口。

「啊？」

「————」

明明发出了声音，却无法形成话语，昴怀疑起自己的喉咙。然而，并未感到异常。硬要说的话，仍是那个一直不灵活的、令人懊恼的喉咙。

他发出了声音。呼唤了『魔女』。呼唤了他本应知晓的『魔女』的名字。

「■■■……■■■！ 为什么……■■■！」

「……你」

回过头来的『魔女』，第一次正面凝视着昴。

她那淡蓝绿色的眼眸，朦胧地映出昴的影像。昴期待着其中能萌生正面的情感，等待着她的下文。

将那在喉咙深处难以成形的、焦躁的言语滚动着——、

「——为什么一副那么拼命的表情？ 真奇怪」

然而，『魔女』并未露出期待的反应，依然用那仿佛厌倦地眺望着世界的眼神，只留下那句话，便打算再次迈开步伐。

他不愿就那样让她远去。

「等、等等，■■■……！」

「昴！」

想要伸出的手伸不出去，想要移动的脚也动不了——两者都不充分的昴的身体，狼狈不堪地当场倒下。看到昴那可怜的模样，碧翠丝发出近乎悲鸣的声音，立刻蹲到他身旁。

「■■■……我……」

对于碧翠丝的支撑，他现在完全无暇顾及。

此刻，眼前这个即将远去的『魔女』才是优先。因为，如果在这里让她走了，如果再也见不到她了，那——

所以，哪怕一秒也好，他也要将眼前的『魔女』，将■■■——。

「喂，一秒就那么重要吗？」

忽然，昴拼命的模样似乎引起了她的兴趣，■■■蹲到了他眼前，俯视着他的脸。她将手肘撑在并拢的膝盖上，把小小的脸搁在上面，『魔女』微微歪了歪头，「那么」——

看到这一幕，碧翠丝脸色大变，

「住、住手啊！ ■■■……！」

「我会给你百万倍的。——『压缩痛苦』」

就在『魔女』如同歌唱般低语的下一瞬间，昴的意识被黑暗包裹。

但那最初让他不明所以的东西，昴后来花费了漫长的时间，慢慢解开了谜底。

因为——、

「——啊」

——百万秒的空白，由■■■之手，赐予了昴。

** 10
——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会为任何成功而喜悦。

△▼△▼△▼△

——『忧郁魔女』■■■·■■■。

那便是尼可拉为了击退突然出现的『狂皇子』维格·阿德加尔德而使用的王牌，也是所有人为了活下去而抓住的蛛丝。

「只付出一条腿的代价，已是万幸。幸好，现在比起昴先生的时代，魔道具也有所进步……义肢也并非那么不便」

以失去左膝以下部位为代价，拯救了昴他们的尼可拉，如此坚强地笑着说道。

当然，对于尚还年轻的他失去一条腿，无法像他所说的那样一笑置之。尼可拉以其周全与机智，换取了全员的生存，代价是自己的健全未来。

在深表感谢的同时，昴也必须确认一件事。

「那个、和‘狂皇子’交战的……」

「是的，正是『忧郁魔女』。如您所见，她是全方位散布危险的灾厄本身，但有一个基于客观事实可以信赖的特点」

「那是……」

「那位『魔女』不杀人。所以，报复也只是夺走我的一条腿。出于各种原因，曾对『忧郁魔女』的地盘出手的人不少，但没听说过有人直接死在她手里。虽然也有人因事后处理不当而死，但那已经属于自作自受的范畴了」

那并非依赖『魔女』的人品或性格，而是纯粹从客观数据中推导出的推测，并以此为依据，这很符合尼可拉的风格。

实际上，尼可拉的预测是正确的，『忧郁魔女』没有夺走任何人的性命。

被夺走的，只有尼可拉的腿，以及沐浴了『忧郁』权能的昴的两周——仅是昏迷不醒、意识未恢复的那段日子。

「告诉我，尼可拉。你是如何将■■■……『忧郁魔女』，呼唤到那个地方的？」

「之前也说过，『忧郁魔女』以亚格萨德绝冰河为领地。她基本不干涉外界事务，但一旦有人对她的领地出手，她就绝不容忍。她会锁定对方，必定报复」

「……也就是说，你故意对她的领地出手，以此来引诱『魔女』出来吗？」

「嗯，差不多就是这样。我准备了可以远程启动的术式，用它来骚扰她的领地。……话说，这招作为紧急应对措施，能卖钱吗？」

「你这商业头脑倒是令人佩服，但需要把『魔女』叫来才能解决的问题，恐怕不会经常发生吧」

「也是啊。那招说白了，也是用来对付『狂皇子』的」

尼可拉似乎想证明「跌倒了也要抓把土」这句格言，但看来他也觉得这样占不到便宜，便悻悻然地收回了提案书。

而他最后补充的一句话，强烈地吸引了昴的注意。

「你、知道……吗？ 那家伙会来」

「——。我料想总有一天会来吧。只是没想到会这么快就被发现，没能提前告知，是我的疏忽」

「疏忽……」

「您想必也明白，『狂皇子』……维格·阿德加尔德，是极度厌恶精灵的。可以说他对精灵怀有憎恨。他以抹杀古斯提克圣王国甚至被称为「慈母」的『灵兽』奥德格拉斯为开端，一直在屠杀世界各地的精灵」

「奥德格拉斯……和妮夏一样，是四大精灵啊。竟然杀了它……」

「不仅是『灵兽』哦。卡拉拉基的『路人魔』也被杀了，体内含有『石块』的阿拉基亚小姐也一直被盯上。身为大精灵的，露梅拉小姐的姐妹们——」

「诶？」

在列数『狂皇子』的暴行时，尼可拉不经意说出的内容，让昴和碧翠丝的眼睛猛然睁大。看到他们的反应，尼可拉捂住自己的嘴，意识到失言，闭上了眼睛。

然后，他接着说「对不起」，

「刚才的，能请你们当作没听到吗。我和露梅拉小姐约好了，不告诉昴先生你们」

「……这、怎么可能」

「照你这么说，贝蒂他们岂不是有义务知道吗。露梅拉的姐妹们……露梅拉以外的五人，难道说」

「——。她们都死于『狂皇子』之手。全部。她们是在做好觉悟的前提下，参与救出昴先生你们的」

「————」

本不欲言说，也不打算让昴他们听到——这是他们事先串通好的秘密。当然，那很可能与昴他们有关。

但具体来说，她们的生命是如何被使用的，这超出了他的想象。

「莫格瑞德大喷口……要在那片飘荡的里侧找到贝蒂他们，并非易事。那里就像个巨大的玛那蓄水池，要从其中拾起那么小的一颗黑球，需要时间、劳力和机会。而且……」

「————」

「而且，若大精灵做出那种事，只要张着天线，很快就会有人敏锐地察觉。为了不被干扰，只能制造混乱来掩人耳目」

「那、那个任务……难道」

「——对我们来说，那是理所当然的决定」

碧翠丝构建的推理，被当事人亲自证实了。

闯入昴和尼可拉谈话房间的露梅拉，她用红色的眼眸无奈地看着泄露秘密的尼可拉，

「尼可拉大人真是的，嘴也太不严了。我姐妹们最后的愿望，您也不肯听吗」

「……我无可辩驳」

「嘛，毕竟是从小看着长大的尼可拉大人呢。想说说我姐妹们的事迹，也是情有可原的」

露梅拉的手温柔地抚摸着低头沮丧的尼可拉的脑袋。那副模样，让人看出两人的关系正如所见，像年长女性与少年。

事实上，在昴他们不知道的地方，尼可拉和露梅拉的人生相互交织，为了迎来今天，经历了诸多波折。——其中，也包括露梅拉的姐妹们为了救助昴他们，不惜赌上性命的约定。

「为什么……」

他忍不住想要追问，为什么要做到那个地步。

作为被救助的一方，他知道自己这样想是不对的。但是，这太奇怪了。这绝对是错误的。为了拯救昴和碧翠丝，付出的代价过于沉重，不成比例。

尼可拉之前的奥托的子孙们，露梅拉她们掌管的尤克历乌斯领，更早以前，为了不让阿尔被杀而将自己与他一同冰封的爱蜜莉雅也是如此。

为了昴他们，牺牲了太多东西。仅仅是露梅拉的姐妹们，就有五人为之牺牲。不能因为她们是精灵就想当然地认为可以接受。

而且，费了那么多辛苦，奉献了时间和人生，即使这样将昴和碧翠丝救了出来——在那里，却已经——、

「大家……都不在了啊」

被抛到这样的世界，被留下来，他无法简单地感到喜悦。

为了对抗义务感和使命感、以及闭上眼睛就会涌上的无力感，昴拼命地进行着康复训练。——但是，在心底某处，他想着。

「毫无……意义」

即使能动了、能走了、能抓住了，又能怎样。

动？ 为了什么。
走？ 究竟走向何方。
抓住？ 在这空无一物的未来。

在这个，昴珍视的大多数人都已经无法相见、无法交谈的世界里。

「好想见……他们」

好想见大家。

好想现在就见到大家。好想和珍视的大家说说话。

如果连这都做不到，那得救又有什么意义。

「昴……」

任凭泪水滑落脸颊。

目睹这一切，听到那微弱呢喃的碧翠丝，脸上浮现出悲痛的表情，但随即又用那份悲伤被慈爱覆盖的表情，为他拭去泪水。

泪水拭去了，又流下，又拭去，又流下。

仿佛，就像昴他们得救这件事本身一样，拭去也是徒劳。

** 11
——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会否定任何人的梦想。

△▼△▼△▼△

——自那以后，他停止了康复训练。

将心和身体的配线重新连接，摆脱不自由，用自己的双脚踩踏大地。

在这个四百年后的世界，在这个已然抵达的明天的明天，作为今天活下去。

这种说教般的希望，在一切都被抛弃的绝望面前，是那样无力。

「昴，吃饭了。贝蒂来喂你」

碧翠丝在失去了自发行动气力的昴身边，忙前忙后、殷勤地照顾着他。

从以前开始，她就总想为昴尽力，但由于天性笨拙，常常不顺利。

但不知是使命感使然，还是因为无人可依赖的不便，讽刺的是，与康复训练毫无进展的昴不同，碧翠丝的护理能力日渐提高，开始能利落地照顾昴了。

早晚的饭菜，用热水擦拭身体的清洁。为无法活动的手脚肌肉进行伸展运动等等，这对碧翠丝娇小的身躯来说本是重体力劳动，她却毫无怨言。

不仅如此，她一丝不苟地完成每一项日常任务后，还会说：

「你做得很好。昴真了不起呢」

她会对这个什么也没做的废人，如此微笑。

如果这是对吃闲饭的人的讽刺或挖苦，昴的心或许还能得到救赎。然而理所当然，其中并不包含碧翠丝的恶意。

只是，碧翠丝对昴的担忧之情，反而让他的心更加腐烂。

「————」

夜晚——不，不仅限于夜晚，每当闭上眼，脑海中浮现的，不是一切都已面目全非的现在，而是被抛下的过去的光景。

那里，有昴珍视的一切。

珍贵的伙伴们，共同生活过的宅邸，相视而笑的回忆，绞尽脑汁的问题，发誓要跨越的未来——一切，都留在了那里。

能看到笑容。能听到笑声。能回忆起温暖。——然而，那些人和事，都已不在了。触不可及。无法交谈。无法欢笑。

——昴——仿佛能听到呼唤自己的声音。

各种各样的声音，各种各样的呼唤方式，各种各样的情感，在呼唤着菜月昴。每一个都深切地唤起回忆，菜月昴不断沉沦。

他想，就这样吧。——因为，此刻找不到站起来的理由。

「好想见……你们啊」

想必，为了确认，他应该站起来。

即使试图放弃，认为什么都不剩了，即使那些身影已不在触手可及之处——只有她，如今仍留在这个世界。

他应该以与爱蜜莉雅的重逢为希望，努力站起来。

为了拯救昴他们，而将自己封入永久冻土的爱蜜莉雅——他应该只为与她的重逢，拼命挣扎。应该是这样。道理他都懂。

但是——、

「如果」

如果连爱蜜莉雅，都不在冰层深处呢。

「如果」

如果那里，没有爱蜜莉雅呢。

如果一切，都是为了挽救昴和碧翠丝而牺牲的呢。

「如果」

如果，那是尼可拉他们为了给他活下去的理由而共谋的谎言呢。

如果，包括爱蜜莉雅在内，已经没有任何人留在这个世界上了呢。

「如果」

如果连那个理由都失去，如果确认了「没有」的事实，昴会怎样。

大家付出了所有能付出的代价，将昴带回这个已空无一人的大地——昴又将如何。

谁，都不在了。

爱蜜莉雅、雷姆、拉姆、奥托、加菲尔、■■■、法兰黛莉卡、丝碧卡、琉兹、梅莉、罗兹瓦尔、安妮罗洁、柯林特、莱因哈鲁特、菲鲁特、罗姆爷、安娜塔西亚、由里乌斯、库珥修、菲利克斯、威尔海姆、普莉希拉、阿尔、修尔特、阿贝尔、米蒂亚姆、弗洛普、坦扎、塞西尔斯、约尔娜、普雷阿迪斯战团、『修德拉克之民』——谁都不在了，谁都不在了，谁都不在了，谁都不在了，谁都不在了，谁都不在了，谁都不在了，谁都不在了，谁都不在了，谁都不在了，谁都不在了，谁都不在了——。

「没有……人」

没有。没有？ 没有。没有。没有？

那么——、

「——■■■呢？」

无法发出的名字，轻轻溢出。

试图唤醒想不起来的记忆。

扑簌、扑簌、扑簌——刚要抓住，便扑簌扑簌地崩塌，让人忍不住怀疑起自己心中产生的违和感。甚至开始怀疑，产生违和感这件事本身。

自己有什么理由产生违和感呢。■■■，又算什么呢。

「■■■……」

为何无法发出声音。这实在令人焦躁。

需要声音。为了留在记忆里，为了传达给别人。■■■、■■■、■■■啊。■■■！ ■■■！ ■■■——！！

「■■■……！」

想起来。留在脑海里。绝不让它散失。

就像醒来时会忘记所做的梦一样，大脑试图忘记■■■。如果大脑靠不住，那就刻在身体上——可就在指甲用力之前，■■■的轮廓便已模糊，忘记了想要描绘什么。

不自然、不讲理、不合理、不合常理、不仁慈、不合理。

为什么，昴无法记住■■■呢。

「——！」

他咬紧牙关，抵抗着想要忘记■■■的那种不自然。

试图将■、■、■等，将■■■的名字分割开来留在记忆中——但即便这样，当意识到那是■■■名字的一部分时，无论分开还是散开，结果都一样。

无法正确称呼■■■，是世界所规定的、不可违抗的规则。而像■■■这样，无法被正确认知名字的存在，会被世界遗忘。

就如同在亲眼见到■■■之前，连本该知晓并记得■■■的昴，也未曾意识到自己无法正确认知■■■一样。

想必，即使忘记了■■■，也会若无其事地，再次度过一个忘记了■■■的明天。

「开什么玩笑……」

都已经被夺走了多少东西了。

菜月昴，碧翠丝，为了走到今天，失去了多少东西。这边的心都已经快要崩溃了。满是裂痕，乱七八糟。

即便如此，还要忘记■■■，放手■■■，活下去吗。

「既然……你是这个意思的话……」

某个不知名的谁，在昴他们不在的时候定下了规则。理所当然地，这个规则在这个世界具有强制力。如果有异议，当时在场就好了，但因为做不到，规则就这样在不知不觉间缔结了。原来如此，明白了。好极了。

谁会遵守那种荒唐的规则啊，混蛋。

「■■■。■■■。■■■。■■■。■■■」

一秒，只要忘了思考■■■一秒，那一秒就会变成两秒，两秒变五秒，五秒变十秒——空白不断扩大，将■■■从脑海中驱逐出去。

这就是命运的手法，让你忘记，当作从未发生过。——既然如此，从今往后，菜月昴一秒也不会忘记■■■。

从现在起，直到死，他都会在脑海的角落里，持续铭刻着■■■。

将菜月昴内心的一部分，永远献给■■■。

确实，■■■存在过。

虽然被称为『忧郁魔女』，被世界上所有人视为灾祸，甚至被用作对抗世界最恐怖的『狂皇子』的王牌，成了如此离谱的存在——。

但■■■，确实在菜月昴和碧翠丝面前出现过。

「我会……再来的，■■■」

无数次屈服，无数次忘记，无数次放弃，无数次气馁。

无数次下定决心，无数次铭刻，无数次抬起头，无数次站起来。

即使如同笨蛋一样不长记性，即使步伐丑陋不堪，他还是会再来。

「——碧翠丝」

「————」

久违地动了动嘴唇。干裂粘连的嘴唇皮肤裂开，流出血来。疼痛，仍未感觉到。大脑和身体的配线，至今仍未重新连接。

但是，他还会再来。他决定会再来。这次，是真的，虽然花了很长时间。

「■■■还活着。一定，爱蜜莉雅也是。所以」

「————」

「所以，我会加油的。让你久等了，对不起」

反复下定决定和放弃，连自己都觉得缺乏说服力的决心。

尽管如此，他还是说了。不顾羞耻，不顾体面，他说了。

因为——、

「等你什么的，是理所当然的。——贝蒂，是昴的搭档啊」

因为他知道，他最棒的搭档，一定会这么说。

** 12
——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会推任何人的背。

△▼△▼△▼△

——一百二十六亿、二千二百七十八万、八百秒。

那是将四百年换算成秒数的结果。

因化身为『忧郁魔女』的■■■的权能，昴仅在短短一瞬间，便体会到了度过漫长无为时光的恐怖。

「一秒的一百万倍，就是一百万秒……」

粗略计算，是十一天半，这就是昴所体验的一百万秒。

换算成天数，让人觉得似乎不算什么大事，这让他很惊讶。明明那是如同在看不见尽头的黑暗隧道中行走般的体验。

而■■■所度过的四百年，大约是其一万二千倍。

「……那东西，的一万二千倍」

当然，那并非虚无的日子。

正因如此，『忧郁魔女』之名才会传遍世界，她所认识的人一个接一个地离世，最终连王国和都市国家都灭亡，走到了今天。

可以说，她切实地体验了一个动荡的时代。

「不过，我明白啊。那种事，根本不重要」

即使世界发生翻天覆地的大事件接连发生，如果那些事无法打动人心，那么无论发生什么，都与窗外的狂风无异。

只有将其视为己事，带着热度与实感去体会，各种体验才能成为自己人生的一部分。无法获得那种感觉的人生，空虚而等同于不存在。——那正是，人世间的炼狱。

■■■，就度过了那样的炼狱。没有梦想，没有希望，只是出于惯性。

漫长而虚无的时间，夺走了她身上那些闪亮的东西，塑造了作为『忧郁魔女』的■■■。若非如此，就无法解释她如今的存在方式。

然后——、

「——大家，是想让我去解决那一切吧」

如此说着，昴理了理自己亲手穿好的衣服的衣领，用力系紧了鞋带。

从能说话、能按自己的意愿活动双手、能站立行走，到将心和身体的配线重新连接起来，花费了难以估量的时间。

沉沦的时间之长，以及投入康复训练的时间。

即便如此，有着强烈目的和必须达成目标的昴所度过的时间，远比■■■所度过的四百年，要充满救赎得多。

那份给予昴的救赎，他也想传递给■■■。

「——菜月先生，准备好了吗？」

在昴感慨地眺望着自己长久居住的房间的背上，传来了已经听惯了的尼可拉的声音。

回过头，只见那个与初见时一样，温和而有些靠不住、却成就了大事的男人，正用已经彻底习惯的义肢堂堂正正地站在那里。

即使在昴沉沦的时候，他也一步一步地，推动着自己的人生向前迈进。

「准备好了。真的，什么事都受你照顾了。这份人情……」

「那个，我很久以前就说过不必了吧。在找到菜月先生和碧翠丝小姐的那一刻，我就已经得到了足够的回报。所以，什么借贷……」

「不，我要还。即使你拒绝，你爷爷的爷爷的爷爷……总之，我的朋友可不会允许欠债不还。而且，我明白了啊」

「明白了，是指？」

「那家伙，为什么要把‘把我和贝蒂子拉上来’这种离谱的遗训，一代代传下去啊」

那个具体理由，没有明文写下来，是他的疏漏，还是有其他原因。

他也有马虎的地方，所以前者的可能性不是没有。但，考虑到围绕那个目的的各种事象，或许是因为根本无法文字化。

即便如此，行动有时比语言更能清晰地传达意志。——奥托·苏文，通过子孙们作为媒介，托付给菜月昴的东西。

「——菜月先生，请救救■■■小姐」

「————」

「这样一来，各种齿轮就会咔嗒咔嗒地咬合在一起。当然，大家为了救我而努力的插曲也非常热血。但是，他们应该也想过，在大家都消失之后，出现的我可能会变成灵魂空洞的躯壳。然而……」

大家，没有那样做。

无论谁，都没有放弃将菜月昴拉上来。为什么？ 因为菜月昴有必须回来、必须去做的事。

他们自己无法拯救的■■■，必须由昴来拯救。

为了这个目的，那个时代的所有人，都给了昴一个巨大的人情。

想必，尤其是为了那个比任何人都付出了代价的■■■。

「即便如此，这也是个麻烦的机制……诅咒、系统、混蛋规则啊。谁都无法留下关于■■■的东西。无法记录。无法记忆，无法言说」

「但是，菜月先生记得。碧翠丝小姐也记得」

「那是当然的。毕竟，我们可是扭曲了一个女孩子的人生，把她变成了『魔女』这种离谱的存在啊。不承担责任可不行」

那正是，即使奉献上自己的人生，也无法与之相称的代价。

面对昴的觉悟与回答，尼可拉抚了抚下巴上蓄着的、与他并不相称的胡须，笑了。

就在这番交谈之后。

「菜月昴大人！ 这边的准备，如燃烧般万全吗！ 碧翠丝大人和我，都如灼热般绝！ 好！ 调！ 哦——！！」

「哎呀，吵死啦！ 再说了，贝蒂的状态凭什么由你来擅自说明啊！ 还有，你也该学会调节温度了吧！ 好热啊！」

随着哇哇的吵闹声飞进来的大小两个身影，昴和尼可拉对视一眼，随即忍不住笑了出来。

注意到室内的两人，露梅拉「哎呀」一声用手掩口，

「尼可拉大人！ 今天您状态不错呢？ 听说您最近不太出门呢」

「确实如此，不过，今天不来送行才是谎言吧。‘无法发现胜机的人，亦无法抓住商机’——这是凤仙语录。虽然现在早已过时了」

「好话就是好话呢。我那如燃烧般出色的主人，也珍视着他所侍奉之人留下的这样的话语呢」

凤仙语录虽已过时，但看着珍视着已过时的语录的两人间的对话，往昔的光景和身处其中的人们自然而然地浮现在脑海中。

但那怀旧而感伤的心情，现在必须封印起来。

「不过，露梅拉，你真的要跟我们一起来吗？ 毫无疑问，这会是一场艰难的战斗」

「哎呀哎呀哎呀，您这是在担心我吗，菜月昴大人？ 如果是这样的话，那我就更应该在场了。因为……」

「为姐妹们报仇吗？」

「不，不对。——如果是主人的话，他一定会在此与菜月昴大人并肩作战的。所以，我也要这么做」

「……可恶，那混蛋，现在倒先跑到一个我们没法直接抱怨或动手的地方去了」

「呵呵，这才是『最优』啊！」

她咚地一声拍了拍自己丰满的胸膛，比任何人都更加自豪地谈论着那个不在此处的男人。虽然露梅拉的姿态、性格、态度，一切的一切都与那个人不同，但昴却从她身上感受到了与她所崇敬的『最优骑士』同样的可靠感，这让他感到一种奇妙的滋味。

「实际上，有露梅拉在是如虎添翼。而且，无论怎样，一旦发生预料中的冲突，那个男人肯定会来插一脚的」

「那就干脆打成总决战，对大家都好。真是的，我们明明想专心完成被托付的重要任务，都怪我的贝蒂子太受欢迎了」

「不用担心，那个男人也好好地锁定着赢得了贝蒂的昴呢。被盯上可是很可怕的哦」

「那敢情好。既然我们一起被盯上，我就不用怀疑贝蒂子出轨了嘛！」

「呜哇！」——碧翠丝被不意间扛起，放在了肩头，惊讶地叫出声来。但很快，她将手放在昴的头上，对他身体恢复到了能被这样扛起的程度，感慨地叹了口气。

「————」

对于那落在头顶的吐息，昴没有多说什么。

感激之情无论说多少都不够，而且对碧翠丝，他不断地让她担心、给她添麻烦——感激的话语无论说多少都不够。

他真的让她等了太久太久，现在终于要开始了，从这里开始。

「什么啊，这么湿漉漉的。简直像要奔赴死地一样潮湿的空气。你们明白把朕的『九神将』借出来的意义吗？ 嗯，如何？」

当昴将碧翠丝扛在肩上，与尼可拉和露梅拉一同走出家门时，在那里等候的，是佛拉基亚帝国的统一皇帝阁下。

她特意离开王宫，亲自前来，昴「哦」地瞪大了眼睛，

「你在这里没问题吗？ 听说你很忙啊。好像是找到了那些企图颠覆帝国的家伙的据点什么的吧？」

「蠢货。既然已经查到那个地步，由朕来调度便不会有问题。过于重用固定的人选，反而可能使部下离心。文森特·佛拉基亚在这方面做得不够周到，据说经常需要皇妃来替他善后——这可是有记载的」

「真厉害啊。那家伙，在后世被记载为冷酷无情，还被记下了被米蒂亚姆小姐管得服服帖帖的。要是知道了，他眉间的皱纹恐怕都舒展不开了吧」

无论如何，他是否成为被尊敬的对象尚不可知，但如果能作为反面教材对自己的子孙统治有所帮助，那阿贝尔也能安息了吧。「哼」——他那张扑克脸，双臂环抱，一副若无其事的样子，仿佛就在眼前。

在这位谈论着先帝糗事的年轻皇帝左右，正是她刚才所说的、常被重用的两人——阿拉基亚和玛德琳。

以前，或许是出于让昴他们见见旧识的考虑，她们经常被派到昴他们那里，但这次的情况与以往不同。

「没想到，虽然是不抱希望地试试，居然真的能租借到『九神将』」

「当然，这对朕这边也有好处。若你能解决亚格萨德绝冰河的问题，便能打开通往古斯提克圣王国这条长年堵心的道路。『灵兽』已死，古斯提克圣教的影响力也已衰微，朕不能放任那个国家不管」

「这样一来，就能建立统一全球的超统一帝国佛拉基亚了吧」

「届时，朕便将作为完成世界统一的超皇帝名留青史。——若无那病，这本该是母君的荣耀，她运气真不好」

「……明明讨厌湿漉漉的话题，你倒自己提起来了」

「——哼，慎言。朕可不像母君那样，即便你可爱也不会心软」

不过，她终究没有惩罚他，这话说得毫无说服力。

无论是昴、碧翠丝，还是夹着皇帝本人的两位『九神将』，都看穿了这一点。

「能得到你们的协助，我真心感激，但我希望你们听从我的指示？ 我可不打算杀了■■■……『忧郁魔女』」

「听到了。鲁莽，愚蠢。但，会服从」

「是因为命令？」

「不。我也，不讨厌那个『魔女』」

言简意赅，用最美好的话语承诺协助的阿拉基亚。

昴向她回以笑容，然后看向另一人——玛德琳，

「玛德琳，拜托你的事呢？」

「你也真是，总是对龙提些无理要求。你真觉得会有用吗？」

「有没有用暂且不论，你要是不到场就不够精彩啊。这可是为了把■■■带回来的同学会。人越多越好」

「唉……虽然费了番功夫，但找到了」

「——！ 真的吗！ 太厉害了！」

听到玛德琳将手叉在腰上、深深叹气的回答，昴不禁跳了起来。

老实说，这件事比租借『九神将』更不抱希望。甚至可以说，一开始就不抱任何确信。因为与■■■有关，所以记录中也并未明确记载——那是在露格尼卡王国某地，罗兹瓦尔·L·梅札斯宅邸遗址中封印的禁书上记载的信息。

那是昴也认识的某个人的真实身份——在四百年后的现在，行踪不明的他的下落，昴委托玛德琳去搜寻。

他赌的是，同为龙人的她，或许能找到那一丝可能性。

「真是了不起啊。贝蒂待会儿会摸摸你的头作为奖励的」

「不需要！ 别把龙当小孩子！ 龙也好，你也好，都既不是孩子也不是什么别的东西！」

「是啊。八百岁的钻头萝莉和四百岁的角萝莉呢」

「那也是令人不快的说法……但或许听了也是白听」

「诶？」

「龙觉得，他已经没用了」

「————」

双臂环抱的玛德琳，眯起金色的眼眸，如此先说道。

将难以启齿的事也清楚地说出来，这是身为龙人的她的坚强，也是她在人类社会长期生活中所萌生的体贴的体现。

同时，被玛德琳评价为「没用的」对方，正处于何种绝望之中——昴能够想象。不——、

「那只有我们才懂。所以，我和贝蒂子会去的」

「我们去。昴和贝蒂，永远在一起」

「嗯」

被扛在肩上的碧翠丝与昴，互相碰拳。

看到这一幕，玛德琳耸了耸肩，没有再提出反对意见。

「————」

确认了这一点，昴深深地吸了一口气，又呼出。

将清冷澄澈的空气吸入肺中，微微冷却发热的身体，然后缓缓地，回头望向身后的伙伴们。

四百年，漫长的时光——将只是飘荡的昴和碧翠丝救出，并给予他们足够的时间，去全力完成必须完成之事的大家。

「尼可拉」

「嗯」

「露梅拉」

「在！」

「罗莎琳德」

「朕替她回答」

「阿拉基亚」

「嗯」

「玛德琳」

「听着呢」

「贝蒂子……碧翠丝」

「当然，在呢」

他依次看着大家的脸，依次听着大家的回答，依次将大家的可靠之处珍藏在心中，然后深深呼出一口气。

他留下了太多东西。与太多人分别了。

那是悔恨。是悲伤。至今仍感痛苦。但是，曾经变得空无一物的双手，并没有强大到能够一直保持空无一物。

「不对。我，从未真正孤独过」

只是昴在腐烂，自以为变得孤独了而已。

有碧翠丝在，有尼可拉他们在，爱蜜莉雅一定在等着他，而■■■，也在等着他去迎接。

「——走吧。为了让我们，成为我们自己」

** 13
——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会忘记■过的事。

△▼△▼△▼△

——然后，故事回到了开头的，那片绝冰地带的瞬间。

「我要把你夺回来，■■■。——命运大人，放马过来吧！！」

夹杂着吹来的寒风、以及不安地高涨的玛那波动，为了吹散那些不安因素，昴大声地、响亮地喊道。

然而，面对他强烈的感情，『忧郁魔女』的侧脸却纹丝不动。

于是，最初的告白轻易失败——、

「——六秒」

他用力踏在白色的大地上，瞬间缩短距离的『狂皇子』抡起双臂。他的手中握着两把『咒剑』，片刻之后释放的剑风，将同时斩断昴他们和■■■他们。

■■■或许有办法应对，但对于已经使用过E・M・M的昴他们来说，要防御住这一击却很困难。

因此——、

「——不巧，还请你们再多纠缠一会儿。请求」

瞬间，在大地上响起的雷鸣，化为正面袭来的雷暴，击中了『狂皇子』。

炸裂的光芒，向四面八方扩散着冲击波，连昴都能看到，冻结的大地呈放射状裂开、破碎。一瞬，他担心那会波及到自己脚下，但很快就判断那是多余的。

「因为，万能管家可不会犯那种疏漏啊」

「承蒙如此高度评价，倍感荣幸，昴大人。追加感谢。大恩」

「大恩什么的太夸张了。我才要感谢你来着。——柯林特先生」

如此说着的昴的视野中，映出一个纤细而柔韧的背影——那位有着秀丽面容、蓝色头发的男子，柯林特站在那里。

他是知晓四百年前往昔的人之一，也是在这个时代仍然存活的旧识。——并且，如今他那蓝色的头发上，长出了两根黑色的角——身为龙人。

他在四百年前销声匿迹，昴将希望寄托于同为龙人的玛德琳进行搜索，终于找到了他的下落——这最后一块拼图。

「我曾犯下巨大的过错。因过于渴望那份觉悟与未来，而未能察觉到对方愿付出巨大代价的真意。痛悔」

柯林特的嘴唇静静地编织出话语——那便是为何像他这样的人物，四百年来既未登上舞台中央，也未曾像尼可拉他们那样协助搜寻昴他们，而只是在失意中度过漫长时光的理由。

果然，在缺失的记忆中，仍残留着强烈的悔恨折磨着柯林特。从他那断断续续的证言中，昴看穿了柯林特所经历的绝望——它与■■■化身为『忧郁魔女』的现状，有着密切的关联。

或许，他曾想过死。

但是——、

「我愿将我的悔恨与哀悼，献给您。——这次，一定」

那寄宿着决意的金色眼眸，以及缠绕全身的迸发的紫电——这位将生命延续到这一时代的龙人，将为昴他们的愿望与祈祷贡献力量。

「……龙人啊。你等身负龙壳与龙晕的『龙』，广义上而言，与精灵同为拥有玛那体的存在。但吾并不视你等为直接敌人，不曾如此认为」

紫电一闪，正面承受了柯林特释放的缠绕着雷光的一击，『狂皇子』却只是用交叉的『咒剑』剑柄挡住，向后退了一大步。

他那超乎寻常的力量，甚至凌驾于拥有异常力量的龙人之上。——这并非源于对力量差距的确信吧。

『狂皇子』并非以那种易懂的算计或傲慢来看待对手。

这一点，对于以碧翠丝和露梅拉他们的安危为起点、经历了最糟糕的初次见面之后，多次与那凶刃交锋的昴来说，是再明白不过的事实。

仿佛是证明，『狂皇子』确认着手中『咒剑』的触感，面无表情地皱着眉头，无论对手是谁都一样，

「即便如此，也要战吗？」

「无需多言。至言」

「是吗。遗憾，深感遗憾。就请你们消失吧。遗憾地」

刹那，雷暴与光爆在大地上激烈碰撞，连声音都被吞噬的惊人爆压，从内部膨胀了整个战场上的绝冰河，改变了数百年未变的世界的形态。

那是数百年未遇的、动摇世界趋势的超凡战斗的开幕——、

「这样好吗？ 放着那边不管」

忽然，如此询问的是，在远处眺望着那场战斗的■■■。

她眯起那蓝绿色的眼眸，带着一副没什么兴趣的样子，向昴问起柯林特与『狂皇子』的战斗。

一瞬，对于她毫无防备的接近，昴差点被惊住——、

「没关系。这也是，计划的一部分」

「是吗？ 不过，那位龙人赢不了『狂皇子』先生吧？ 被干掉也只是时间问题哦」

「不愧是■■■，眼光真准。——不过，没关系。马上」

「——会有援军吗」

说时迟那时快，在冰上展开攻防的柯林特与『狂皇子』的战斗中，从四面八方猛然闯入的身影——全身包裹着升腾火焰的红发大精灵、从自身延伸出闪闪发光的金刚石光带这一矛盾武装的『金刚姬』、以及久违地将『云龙』的龙壳投入实战、实现自己×自己连携的『飞龙将』。

——这些当今世界最强级别的存在齐聚一堂，战斗进一步升温。

「……确实，有她们在，或许能多撑一会儿。不过，在场的全是『狂皇子』先生的目标吧？ 『狂皇子』先生是在战斗中会越来越强的类型，这岂不是作战失误吗？」

「————」

「……什么？ 我说了什么奇怪的话吗？」

「不……能从你嘴里听到‘目标’或者‘类型’这种词，我心里真是热热的」

面对■■■的见解，昴也说出了真心话。结果，虽然被她用看可疑人物的眼神盯着，但感慨之情是真切的。

但同时，■■■的战术评估是正确的。——本来，『狂皇子』不仅存在本身，连被赋予的才能也是超乎常理的怪物。

凭借『适应的加护』，他不仅能适应任何状况和环境，还凭借『孤独的加护』常态提升单独战斗能力，凭借『反复的加护』在战斗中让相同动作被加速磨炼，而本应只在临死时才发挥效力的『不屈的加护』，也因精灵人这一不死心脏的独一无二的bug而持续发动着。

这样，拥有复数加护，且加护之间产生协同效应爆发。——那正是『狂皇子』压倒性战斗力的真面目之一。

「莱因哈鲁特也够离谱的，塞西和赫鲁贝尔先生也是，但这家伙果然也是同级别的怪物啊」

「什么意思？ 也就是说，你知道赢不了？ 听着，想自杀的话请去别处。我住在这里，很忙的」

「不是自杀，我是来打赢的。确实，这样下去我们这边会输。但是」

「但是？」

「■■■，如果你肯帮忙的话，那就另当别论了」

与昴牵手的碧翠丝的发言，让■■■怀疑地皱起了眉头。

即使皱眉也丝毫不减其美貌的『魔女』，毫无感情地嘟囔道「真不明白」，

「为什么我要做那种事？ 我，是『忧郁魔女』。知道吗？ 没有人能支配我，也没有人能命令我。我就是这样的存在。还是说——」

■■■说到这里停顿了一下，投来一个令人脊背发凉的、妩媚的眼神。

那并非出于正面情感的行动，从像碧翠丝陪伴昴一样、陪伴在她身旁的红蝎就能看出来——红蝎正用那炯炯有神的复眼，仿佛要守护不容任何人侵犯的『忧郁魔女』免受一切灾厄。

「你，是被人拜托来保护■■■的吗？」

「……那是什么？」

「不，只是想象。记忆支离破碎，但如果是那样就好了，我这么想着」

「从刚才起……不，从一开始就完全听不懂你在说什么。你身边那位也一样，真是个奇怪的老人」

或许是不满、不愉快、不可解，各种情绪混杂在一起。

虽然依旧情绪低落，但话语中还是略带感情的一句话，对于现在的昴来说，却是一句犀利刺耳的话。

昴用与牵着碧翠丝相反的手，抚了抚自己已完全变白的头发，

「被当成奇怪的老头子还真是受打击啊。我还觉得自己心态挺年轻的，不行吗？ 胡子也学着……仰慕的威尔海姆先生那样打理了一下」

「从贝蒂的角度来看，任何昴都有男子气概……虽然很难说得让所有人都认同，但贝蒂认为昴充满了难以言喻的魅力」

「谢谢你这无法彻底夸完的夸奖！」

虽然这评价让人无法坦率地高兴，但其中没有谎言是毋庸置疑的。

若非如此，就不可能在这四十年里，为了完成必须完成的事而做准备的过程中，片刻不离地支持着他。

除了爱情之外找不到答案，也不需要寻找。

「爱情，吗。是啊，没错。努力的理由，就只有这个啊」

「你……」

「虽然很长，四十年。但是，那也不过是十二亿六千二百二十七万八千零八十秒。连■■■所度过的十分之一都不到。真的……真的很漫长啊」

『忧郁魔女』的权能。——与碧翠丝讨论后推测出的那种『压缩』之力，也无法抹消实际所经历的痛苦时间。

■■■活了四百年，而昴被自责与自罚所折磨、体验的地狱般的日子，简直是让人嗤之以鼻的岁月——那，消磨了■■■的心。

「为什么，要那样消耗自己，付出那么多代价，奉献那么多可能性，才走到今天这一步？」

「你在说……」

「为什么啊，■■■……■■■！」

「住口！ 别用那种听不清的名字叫我！」

不意间，『忧郁魔女』的表情崩溃，她大大地向后退了一步。就这样，反射性地抬起右手的■■■——那是准备打响指、发动权能的架势。

不夺走对方性命，只以经过的体感时间逼退对方——『忧郁魔女』那不杀生的权能——、

「你试试啊，『压缩』看看」

「——！ 别说得那么轻巧。你该不会以为你能承受得住吧？ 那是不可能的。能承受这个的，不是人类。四百年，太漫长了」

「我知道的」

「————」

「贝蒂知道。虽然■■■所度过的，和贝蒂所度过的四百年不同，但那份孤独，一定有相通之处」

碧翠丝也曾在『禁书库』中度过漫长的岁月。并且，她深知，那段看似永无止境的空虚日子，终有结束、迎来解放的一天。

「贝蒂希望■■■也能明白这一点。你有权利接受它。——不，我希望你能接受它」

「……为什么？」

犹豫着该将准备好的手指指向昴还是碧翠丝的『忧郁魔女』，显露出至今未见的感情，如此问道。

那个在舍弃一切的过程中，不得不连理由也一并抛弃的、悲伤的『魔女』——。

「因为，我们希望你幸福。我们大家都是这么想的」

「大家……？」

「我，菜月昴」

「贝蒂，碧翠丝」

「爱蜜莉雅」「法兰黛莉卡」「奥托」「加菲尔」「雷姆」「拉姆」「罗兹瓦尔」「琉兹」「梅莉」「丝碧卡」「安妮罗洁」「柯林特」「阿拉姆村的人们」「科斯茨尔的人们」「家人」「伙伴」「我们」「贝蒂们」「「大家」」

「——！」

■■■屏住了呼吸，脸颊紧绷。

其中，想必有许多名字是■■■未曾听过的。原因他知道。正如昴那样，■■■自身，如果仅有一秒不去想那些与自己相关的人，就会全部忘记。如此反复，一切都被磨灭了。

「老实说，当昴提出要在脑海的某个角落永远想着■■■的时候，贝蒂也觉得这太乱来了」

「是吗？ 这又不是什么大不了的事。只是把大脑的一部分，献给■■■而已」

「说得对」

他们互相点头，然后重新望向目光锐利的■■■。

对于她发出的「为什么」，昴他们给出了回答。

接下来——、

「你也回答我们吧。刚才的那个‘为什么’」

「刚才的……」

「为什么，■■■要成为『魔女』，即便被称为灾祸，即便要守护这个地方免受众人侵扰，也要跨越这四百年的空虚呢」

「————」

面对碧翠丝那深入浅出的提问，■■■屏住呼吸，说不出话来。

昴正面看着她，向前迈出一步。碧翠丝松开相握的手，用小手轻轻推了推昴的后背。

一步，又一步地向前。与一度后退的■■■之间的距离缩短了。

「——！」

就在昴与■■■之间，红蝎插了进来。

那姿态，仿佛是要以自己的牺牲来保护■■■，使其免受一切可能伤害她的灾厄。

但是——、

「一直以来，谢谢你替我们做了我们做不到的事」

「————」

如此说着，昴轻抚着它的甲壳，那高举的双钳便放了下来，红蝎以缓慢的动作，为昴让开了道路。

看到红蝎的举动，■■■露出了仿佛被背叛般的表情，瞪大了眼睛。——这是件光荣的事。如果红蝎在此退开会被她视为背叛，那么——、

「我这样做，对你来说，是有意义的啊」

「啊……」

站在触手可及的正面位置，昴让■■■的眼神动摇。美丽的、昴那模糊消失的、关于■■■的记忆——与在那里回忆中的她相比，眼前的她变得更加成熟，比起可爱，美貌更为突出。

礼服的挑选与穿着，发型的打理——即使不给任何人看，却仿佛一团时尚的集合体，这风格，实在很■■■。

即便过了四百年，她仍未改变那些部分，她就在那里。

那是——、

「是因为想见我们——想见我吧」

「——啊」

那微弱的气息，是令全世界畏惧的『忧郁魔女』，所能做出的最后的抵抗。

「————」

昴伸出手，将她纤细的身体拉近，拥入自己怀中。

■■■的身体微微一颤，仿佛在害怕。然而，带着热度的■■■，却并未推开只需轻轻一推便会轻易倒下的昴那老迈的身躯。

但她，也没有回抱。那不是她的拒绝——、

「那个，也献出去了」

她连与人相拥的权利也献了出去，■■■渴望了这个未来。

为什么。为何如此。那个答案，只能由菜月昴来强加给她。说是为了见到菜月昴，■■■才忍耐了四百年的空虚。

而那份空虚，那四百年的漫长空虚，此刻，即将终结。

「我，我，我……」

「没关系。既然你无法拥抱别人，那就由我来拥抱你」

「————」

「既然你无法呼唤名字，那就由我来呼唤你的名字。既然你无法在人前哭泣，那就这样把你的脸按在我胸口。既然你无法品尝喜欢的东西，那就为你创造无数新的喜欢之物。既然你无法握住任何人的手，那就由我来重叠我的手。既然你无法向任何人示弱，那就让我来夸赞你的坚强，夸赞四百年份」

自己能做的事，想做的事，未来，希望，可能性。
成为『忧郁魔女』的资格，从■■■身上夺走了太多东西。■■■为了获得、抓住那些可能性，甚至无法自己去渴望它。

但是——、

「没事的，■■■。昴啊，就是个会擅自为别人着想、擅自想象别人的心情、擅自想让人开心起来的天才呢」

「贝蒂子就是这样被攻陷的。■■■，你也成为他的猎物吧」

「——！」

昴轻轻抱起拥在怀中的身体，近距离看着惊讶的她的脸。她的眼中，虽有无尽情感翻涌，却没有泪水。

连在别人面前流泪的权利，也已不在她手中。她手中剩下的可能性、希望、未来，又有什么呢。

但至少，她并未献出脸颊泛红、湿润着眼眸、凝视着对方的资格。

「真不明白。你们，大家，都真不明白」

被一个普通人抓住的『忧郁魔女』，用颤抖的声音如此低语。

即使是能将任何灾厄、痛苦与艰辛，通过『压缩』化为刹那之事的『魔女』，也绝不想失去、绝不想放手这一瞬间——她仿佛祈祷般，嘴唇颤抖着。

「明明不明白……却……」

『忧郁魔女』，『魔女』，■■■，用湿润的眼眸微笑了。

仿佛在确认着，自己心中涌起的情感——那未曾放手的情感。

「——我，好像爱上你了。很奇怪吧」

「不？ 一点也不」
「奇怪吗」

她或许是做好了被拒绝的觉悟吧。

说出口的爱，被毫不犹豫地接受了，■■■瞪大了眼睛。那副毫无『魔女』风范的、如同普通村姑般的表情，让人忍不住笑了出来。

「说是村姑，未免也太漂亮了吧」

「……那句话，你好像对谁都这么说」

「就算说过，也只对那些漂亮得不像村姑的村姑说。据我所知，这种人可不多。就你一个」

「是吗。……那就好」

听到昴的回答，■■■像是闹别扭般别过脸去。看到她那份可爱，昴深深呼出一口气，

「那个，能放我下来吗？ 我的腰有点吃不消」

「怎么，你是说我重吗？」

「不是！ ■■■完全不重，简直轻如鸿毛！ 但、但是，我可是六十岁的老头子啊！ 虽然还没到老态龙钟，但客观来看也已经很老了！」

「唔……好吧」

得到同意后，他缓缓将■■■放下。随即，跑过来的碧翠丝，轻巧地代替她跳进了昴的怀中。

看到这一幕，■■■的眼神又变得严厉起来，

「她可以，我就不行？」

「■■■一看就知道了吧。我家贝蒂子是精灵，是真正的鸿毛」

「是鸿毛哦」

「真是默契……够了」

■■■从昴和碧翠丝身上别过脸去，缓缓迈开脚步。她抚了抚退到一旁的小红蝎的背，小声责备道「叛徒」。

然后，她瞥了一眼在这场对话中仍在持续进行着的传说级激战——那边，

「不知不觉间变得很危险了呢，你是想让我帮忙吗？」

「嗯。得让维格那家伙在这里老实一段时间。之后，也有很多事想借助你的力量……」

「你打算方便地利用我吗？ 是那种钓上鱼就不给饵的类型？」

「我是那种想尽可能每天都说‘我爱你’的类型」

「哦。……那，我就不抱期待了」

■■■挥了挥手，让红褐色的头发和巨大的缎带在背上摇曳，带着红蝎，走向战场。

看着那个熟悉的、刺激着记忆的缎带，昴眯起眼睛，

「——佩■■！」

「————」

「这片冰河深处，还有另一个我爱着的女孩子，待会儿能把挖她出来的事也帮我一把吗！？」

「去死吧，笨蛋！」

不知有几分真心，■■■如此说道，做了个鬼脸，奔向战场。

昴挠了挠头，叹了口气。怀中的碧翠丝用拳头戳了戳昴的心窝，

「就算想让她放松点，你这方式也太拙劣了」

「也许吧。我引以为傲的俏皮话，也被时代潮流淘汰了吗？」

「不清楚。不过……」

「——？」

「你和■■■说上话了。一切，都从这里开始。绝不能搞砸」

碧翠丝那蕴含着希望热度的言语，让昴屏住呼吸，点了点头。

对，没错。从这里开始，一切从这里开始。

昴他们，不过是终于站到了起跑线上。

跨越四百年，花费四十年，终于，站在了这个世界的起跑线上。

「贝蒂也去助阵吧。昴，准备好了吗？」

「当然！ 准备好让经过四十年磨练的、我们的团队合作和十二种原创魔法大显身手了！」

「大显身手吧！」

两人精神饱满地喊着，昴和碧翠丝也猛然冲向战场。

轰轰作响的缠绕着紫电的雷鸣震耳欲聋，如同世界末日般的火力烈焰狂暴肆虐，大地本身仿佛在咆哮的金刚石风暴横行肆虐，自由操控数百吨云层的『龙』之天罚倾泻而下——在这其中，地上最恐怖的怪物与带着魔兽的『忧郁魔女』激烈碰撞的战域。

一个抱着可爱小精灵的、年过六旬的老头子，冲了进去。

那无疑是赌上性命的挑战——、

「比起那四百年的空虚，赌上性命什么的，根本不足为惧啊——！！」

奔跑、奔跑、奔跑、不断奔跑。

不是为了将已经遗落的东西、已经放手的东西，再次抛弃。

被托付了。被传递了。被期待、被祈祷、被祝愿。

与确实在那里的所有人一起，在这无可替代的当下，奔跑。

即使，那并非所期望的理想未来——、

——菜月昴，将与心爱的伙伴们，在这个异世界，活下去。

△▼△▼△▼△

——神啊、佛啊、欧德·拉格纳大人。我发誓，此生绝不会忘记曾爱过。

** 『从零开始奉献的异世界生活』Fin

那么，这次是第九章IF！ 是从败北路线分支出来的！

具体发生了什么、导致了什么结果，因为分支要素太强所以无法给出详细设定，但内容大体上是，如果当时在场的人们做出了那样的选择，结果就会变成这样吧。

正如您所料，这是为了那个在第九章结尾不得不消失的"她"而写的故事，同时也是那些让"她"变成那样的人们的后日谈。

时间线上，涉及了一些本篇可能不会处理的角色，写起来也颇有趣味。虽然脑子里有个模糊的构想，但没想到展开后会变成这样。

总之，虽然让大家久等了，但今年也感谢各位！

托大家的福，Re:0的动画第四季也将从今年春天……不，大约在一周内就要开播了，也请大家多多支持那边！

那么，今后也请多多关照！ 尽情享受故事吧！！

** COMMENT 正文(百度贴吧版 未完成更新)

转自[[https://tieba.baidu.com/p/10771472059#][百度贴吧]]

译者：蝎蝎

————神明大人、佛祖大人、欧德·拉古纳大人。我发誓，此生绝不呼唤任何人的名字。

△▼△▼△▼△

————轰隆隆————

快要割裂身体般的凛冽寒风、正笼罩着整座冰川。

【————】

即便包裹着厚实的防寒衣物，仍能感受到那股透骨的寒意。他一边呼出白气，一边努力睁开被雾气朦胧的视野，看向前方

如果只需要对抗寒冷，那么再穿厚着也好。但此刻，真正的敌意并不止迎面呼啸的风雪。

而是更了当、将利刃架在我们喉咙上的威胁。

【——怕吗？】

忽地、听到这样的轻声闻讯、他意识到对方柔软手指的触感。

紧握左手传来的温度、是无论身处何等绝境、都绝不会抛弃自己的、信赖与爱的最佳拍档。

【不、还有保护欲、讨人喜爱、真情之类的啦，反正积极的情感要多少有多少——夸你的词儿都不够用了呢~】

【哼、那是当然啦。那些海量的夸赞、我倒是很想在时间允许的时候内听个够。。。不过现在、还有碍事的家伙在呢。」

【是啊——真是的，虽然早就知道了，但、真是饶了我吧。】

赞同着敲~~~可爱的拍档的话、耸耸肩、视线继续牢牢锁定前方——哪怕开着玩笑、也完全没有丝毫放松对那个存在的警惕。

嘛、老实说、无论精神多么紧绷、警戒、

对于这个家伙、都远远不够——

【虽然这样来当衡量标准有点那个啥……但相比起来，强欲司教雷古勒斯和你相比，都算是可爱……不，不是可爱。雷古勒斯大概是那种跳蚤一样的东西吧】

【——这，就当作是对我的特别评价，收下了】

对方敏锐的听感有察觉到他的嘀咕，一本正经地、眯着眼、回应道。

悠闲的站姿、华美的装束下、那副锻炼得棱角分明的高挑身材、

眼神流露着藐视、

略带雪灼后浅黑的肌肤、皮肤上淡淡浮现的、是类似梵文的神秘纹章。

外表就已知是绝非等闲之辈的男人，当然——实际也确实绝非等闲之辈。

——至少，这个世界，恐怕也无人能胜过他。

——人称——『狂皇子』

此刻，在这狂风肆虐的极寒冰河、这、就是他们所面对的强敌。

【对峙——吗？？——为什么，非得打一仗不可呢？】

【自问自答吗？ 既然是问句，那你就必须好好先问问你的疑问本身了呢。至于理由啊，我应该已经和你们反复说过很多遍了、在此基础上谈不来的话、才落到这般处境——对我来说，也并非我所意】

【并非所意？ 这又是为什么】

【我对你既无深仇也无大恨、导致你我必须这样对峙的理由、与你我彼此的好恶憎厌——无关、

只是——】

说到这里，狂皇子停顿了一下，眯着眼睛，视线微微下移。

他才明白，对方的视线是从自己身上，转移到了身旁的伙伴身上。

瞬间，铺天盖地的、紧伏天地的、永不消亡的恶意，从对方身上爆发了出来。

那确实是『狂皇子』在面对自己时才不会表露出得情感。同时，那也是这个男人与自己、和自己的伙伴之间，水火不容的理由。

『狂皇子』一边毫不掩饰地流露着那份憎恶，一边说道：

【——就是那份污秽，让我和你————水火不容】

【一开始、就说我超级可爱的伙伴是污秽、你这家伙的审美观我完全无法理解嘛、就因为这样、我才没法跟你做朋友】

【真可惜。但正因为如此、所以才真是太遗憾了。但是，我不会就此作罢】

『狂皇子』慢慢摇了摇头，叹息一声、仿佛在为劝说失败感到惋惜。不过，如果那算是真心的说服的话，那么价值观的鸿沟恐怕也是真的永远也无法抹平了。

【真是个没法沟通的家伙啊——相比之下，青色雷光塞西鲁斯可能还更容易沟通一些。】

【拿他跟塞西比，塞西就太可怜了。塞西明明挺好说话的吧——只是，聊着聊着最后会擅自按照塞西自己喜欢的方式来执行、这就是强者的逻辑吧】

【但是啊，那也不能让他就那么得逞哦——你应该明白的吧】

【——啊啊，不用你说我也明白。不过你说了就更棒了】

再次握紧牵着的手，相互交换一个眼神，会心一笑————

面对强敌，与同伴的羁绊已经足够了——而这时、将战场选定在此地、耗费大量时间对话的理由，也随之显现——

那是视野边缘，仅在一瞬间就闪耀开来的冰锥棱镜——

【——E・M・M！！】

一瞬、两人异口同声将咏唱发动——绝对防御魔法将他和伙伴包裹、通过将自身存在暂时从这个世界偏移、使得一切其他干预无效化。

穿过如同幻影般的两人身体、从大概膝盖下方射向对面的、是一道毫不留情击穿一切的毁灭白光。如果没有防护手段的话、并肩而立的两人恐怕会同时被射穿腿脚、陷入无法战斗的状态的吧。

而那道白光、瞄准、直击向【狂皇子】——

【——已经是全力了吗？ 还是想激怒我？ 如果是挑衅的话，那可要为此付出代价了呐！ 让你付出代价的是我、而真正付出代价的、是你】

【狂皇子】说着、用竖起的两根手指夹住了白光、控住

白光在他的指尖慢慢失去光辉、最终显露出本体——一根长长的针、那是由法力凝聚的针、以超高速射出、

随后针也碎成粉末，雾散而去——

【招式的名字。。。地狱狙击】

【——就这？ 真是不长记性呢。不管来多少次，结果都一样哦。】

【——】

忽然，从上方传出的声音，让他不由得屏住了呼吸。

狂风、此刻依在轰隆隆地吹着。那么、究竟是为什么呢？为什么在这样的震耳狂风之中、那个声音仍然能如此清晰地震动耳膜？

或许、强者的逻辑、拥有连自然法则都能压制、使其臣服的力量吧。

若是果真如此的话，那声音能撕裂暴风雪而传来、也是理所当然的了。

总之、淡然出现在这片冰河天空中的存在——是她——

【——好久不见啊，忧郁魔女。别来无恙？】

【别说得像认识我似的好吗？ 我既不是你的朋友，也不是能随便搭话的人。我到底好不好、对你来说、根本无所谓吧。】

【并非完全无所谓啊、并不是呢。毕竟眼下、你和这边的这位先生、正是我达成心愿前不可无视的障碍。若是趁你病、那就一定要你命】

【哦、是吗？ 那如果我放出假消息说我不在状态、你会信以为真、然后屁颠屁颠地直接杀过来吗？ 太好啦~去死吧】

她啪嗒啪嗒地在胸前轻轻拍拍手、漂浮在那寒冷天空中的女人、残酷地笑出声。

【——】

那真是个美人。

用缎带束起直腰的红褐色长发、身穿一件粉色、蓝色和金色等多种颜色混合的特殊纹样的连衣裙。

暴露白皙纤细肩膀的装束、在这极寒的领域、异样到难以置信、但对于连呼出的气都不会变成白色雾气的她来说、这似乎完全不是问题。

就像暴风的声音根本无法掩盖她美唇言出的优美音声一样、寒暑冷热、天气无常、都无法阻碍她想做的事、想穿的装扮。

【——要来了哦】

那声呼唤、将屏住呼吸、身体僵硬的、他的意识拉了回来。

注视着同一个对手、一定怀着同样心情的伙伴、她顾及着他的感受、拼命地抑制着快要溢出的感情。

他不会觉得这份体贴很窝囊、也不会感到歉意——只是觉得、决不能辜负这份好意、于是深深地吸了一口气————

然后——

【——终于又见面了、■■■！】

【——】

他大声、向白雾弥漫的狂风中、彼方的她、如此呼唤道。

不巧的是、与她或【狂皇子】不同、自己可没有能够压制风的本事呢。

而且、这种积攒了力气使出吃奶的劲儿吼出的几句话、要是因为对方没听到就再说一遍、这种逊爆了的事、他绝对不想干。

自己到底翘首以盼这一刻多久了呢？

自己到底咬碎了多少无力感、跨越了多少磨难、才走到了这一步呢？

为了求得这一切的硕果、他深吸一口气——菜月昴注视着■■■。

就这样注视着她、开口说道。

【我一定会夺回来、■■■——命运啊、放马过来吧！！】

那是在菜月昴踏上这片极寒之地前所经历的漫长时光——也是他花费如此漫长时光的理由、是他决定献上一切的后、决断的宣言。

△▼△▼△▼△

————神明大人、佛祖大人、欧德·拉古纳大人。我发誓、此生绝不会背负任何人的誓言。

△▼△▼△▼△

——黑暗。黑暗黑暗。黑暗黑暗黑暗。在无尽的黑暗深渊中、摇曳飘荡。

冰冷，寒楚

窒息，扑动

翻滚，气泡

深蓝，下沉

升腾，分离

波动，你的眼泪

消亡，我的呼喊

悬挂，倒立

冥冥，破裂

招致，死亡

沉默，我的苦痛

告别，爱的时代

如同小憩般恍惚、如同永劫般朦胧、如同泥泞般散漫。

如同在一本书中、始终停留在梦与现实之页的夹缝中、在那种模糊、不确定、散漫、永无止境的黑暗中飘荡。

到底、这样过了多久呢。

到底、还要这样多久呢。

到底、这不断延伸的刹那要延续到哪里呢。

就连这些理所当然会出现的思考、疑问、命题——黑暗也会将其慢慢延续、拉长......

被拉长的就像薄薄的纸片、只要稍微用力一戳就会轻易破碎、分裂、最终失去原本的样子。

一定、已经反复经历过无数次。

将涣散的意识拢起、拼凑、连接起来、然后用些许的力道就能轻易将其戳毁、再次变得七零八落。

干脆、已经破碎到星星般零落、不如就彻底放弃再将它们拼凑一起。

——可是，做不到。

——黑暗。黑暗黑暗。黑暗黑暗黑暗。在无尽的黑暗深渊中、摇曳飘荡。

如同小憩般恍惚、如同永劫般朦胧、如同泥泞般散漫。

——但是、在这而非孤独的黑暗中、我不断飘荡。

并非孤独。而是不会感到孤独。

被拉长的刹那、反复发生的败果、不断飘荡的黑暗、正因为“并非孤独”这个理由而将它们锁缚、不让它们消散。

就连自我的定义都不再完整、就连并非孤独的依据也笼罩在黑雾中、

即便如此、也无法放弃、无法放手、无法死心。

无法死心。——因为、死心不适合我。

正因此——

△▼△▼△▼△

【糟啦糟啦糟啦！ 要是他就这么死了、这么多年的努力岂不是全都白废啦！？ 东奔西跑、灰头土脸、好不容易才走到这一步……呜哇、没脸见任何人啦！】

【现在不是说这个的时候啦！ 这种时候呢……对、下猛药！ 只要结果好、多少折磨也会被掩盖而变得优雅！ 想必主人也会微笑着夸我干得漂亮吧、大概！】

【就这样！ 能做到吗、露梅拉小姐！】

【超级肯定不可能啦——！ 我嘛、可是猛烈燃烧的火属性呀！ 火能做的、不就光是破坏、破坏还好的那部分而已吗！ 啊啊啊啊！】

【莫非现在只是纯粹在浪费时间吗！？】

哇哇乱叫的信息、即使在洪水与浊流中也显得格外吵闹、在脑子里上窜下跳。

感觉到围绕自己而展开的对话、在猛烈地进行着、身心疼痛之余、死亡的威胁恐惧——又额外获得了名为呼吸困难的病症。

【——呕】

胃内痉挛、喉管因胃管收缩而堵塞。

这是肉体不自然的蠕动所引发的悲剧、等待在前方的是谁也无法笑出来的喜剧。本就因极度消耗而衰弱的身体、正因呼吸不全而逐渐丧失机能。

然而、在当下被无数信息扰乱的情况下、找不到解挽救的办法。

【你们几个啊——这样吵吵嚷嚷的就行了吗？ 这家伙、快死了哦。既然是朕素不相识的男人、死了朕倒是也不痛不痒、但你们不是这样想的吧。】

【不、但确实真的真的真的就是这样、我们也已经把资源压榨到极限了、根本没有余力了啊！ 要不、先把他塞回刚才那个球里怎么样？不行吧、是啊、这样不行的吧！】

【果断的自我了结了啊。真是个有趣的家伙。——嗯、说得也是。即便是朕的光辉、对一个快要死的小丑也起不来什么作用……没什么区别呢】

【你打算做什么？】

【蠢货、你那是什么好像事不关己的表情啊、【雲龍】——那个男人姑且不谈、但对这个好玩的家伙、应该是有办法的吧。】

无法应对、痛苦不断叠加、叠加、叠加。

痛苦、疼痛、痉挛、将一切涂抹殆尽、本应被永劫无限延长的刹那、此刻正蒙上一层沉甸甸的终结。

这样下去的话——

【————】

——就这样、结束了吗？

【——斯巴鲁！】

就正是要被黑暗掩埋意识的那一刻、同时又被另一个信息狠狠敲醒。但是这次的信息、并非只是让痛苦与疼痛延长而已。

而是用疼痛覆盖疼痛、用痛苦覆盖痛苦、用信息覆盖信息。

然后——

【不可以死哦——你不会要死了吧……！】

然后那条信息、那份痛苦、那份疼痛、是熟知的重要之物。

【——啊！】

蠕动的胃腔、快要封死的喉咙、打结的舌头、明灭的视野、快被刹那所吞没的意识、本该在黑暗尽头灰飞烟灭的性命、就此踩下了刹车。

不能放下、任何东西。不能抛弃、一切。

留在、这个世界。

必须这样做、不这样不行、只有这样——

【呕——呃——呕——】

【斯巴鲁！】

眼前明灭不定、碍眼的红黑交错的光芒就此消失、逆光下泪眼朦胧的面孔映入眼帘。

蝴蝶般形状的眼眸、用温怜的声音呼唤着名字、全力挽留着、将要消逝的小小存在。

【啊、这】

【——对、是的啊——是的、放心把、我就在你身边】

完全无法自由活动的身体、脆弱麻木破破烂烂的心、即便如此、为了证明自我、为了告诉对方自己还记得对方、而吐露心声——

对方会接纳。是的、如同闭眼走过名为信赖的桥梁。

【无论如何、有贝蒂在的话就一定能熬过去哦、斯巴鲁】

这句可靠又令人振奋的话、深深记住、就此、意识中断。

——那就是、菜月昴重新启航的初日情节。

△▼△▼△▼△

——神明大人、佛祖大人、欧德·拉古纳大人。我发誓、此生绝不会憾记昨日。

△▼△▼△▼△

最先映入眼帘的是陌生的天花板。

【——哦呕】

想要说出口、但干燥的不得了的口腔内部和糊成一团的喉咙却无法发出像样的声音、能发出的只有干哑的呻吟。

宛如被压扁的青蛙临终惨叫。

然而——

【——醒了吗。可真是个贪睡鬼、坏孩子呢】

枕边、等待着醒来的对方、这样来传达感情已经足够。

轻轻伸过来的小手连同刘海一起绕过额头、因这瘙痒而眯起眼睛、昴朝那方向看去、看到温柔弯弯细眉的少女——贝蒂、就在那儿。

不变的姿态、不变的目光、不变的温暖、她、就在那里。

毫无疑问、没有一丝一毫的差异、烙印在意识中模样的贝蒂。

【呃、啊】

【对、是贝蒂没错哦——不必担心、也不可以乱来哦。现在的昴、心脏连系身体的路线乱七八糟的、正处在混沌的状态。】

【呼、啊啊】

并没有试图去做乱来、或者说会被称为乱来的那种事。

只是想直起身、顺着涌上来的感情把贝蒂抱起来、就这样冲出房间、在宽敞的地方两个人一起轱辘轱辘地转圈而已。

但，现在的昴似乎连这都是奢望——心脏连系身体的路线乱七八糟的、贝蒂就是这样比喻的。

【——啊】

实际上、昴的大脑似乎真的已经忘记了该如何让身体动起来。

在无法转动的眼球边缘、勉强映出贝蒂的身影、但别说是手指、就连眼球也无法按照昴的意愿转动。

别说坐起身了，就连勉强呼吸这件事本身都觉得像是奇迹。

应该说，心脏没有忘记该如何跳动、已经值得庆幸。

【说起来不像玩笑、那段期间、姑且不论昴、贝蒂的生命活动几乎快要停止了啊。甚至到了身体都忘记所有事情的地步。】

【——啊】

【那个空间……是用贝蒂所不知道的邪恶魔法编织而成的——恐怖至极的东西。毫无疑问、有母亲大人的味道。为什么那个男人能够学会母亲大人所创造的禁术呢、谜团真是无穷无尽呢。】

【——呃】

【这个相关、可没打算和昴讨论哦。不管昴怎么说、对贝蒂来说母亲大人就是母亲大人、是不可替代的存在。哼，就是这样哦。】

昴只能用嘶哑声音、断断续续的附和。

然而、接受这些的贝蒂以绝佳的理解让昴信服、并且同时、抚摸着昴的额头、不满地鼓起脸颊、【哼】地扭过头去。

那副既偏向感性又偏向理性、结果根本无法偏袒任何一方的姿态、真是过分惹人怜爱——

【……那、真的承认了吗？在我看来、贝蒂只是一个人在自娱自乐而已啊。】

忽然传来的那个声音、既不是昴、也不是贝蒂、而是————

视野之中、贝蒂【唔】了一声、朝横躺着的昴的脚边看去——声音的主人似乎是在那边。但不巧的是、昴根本没有看得到的手段。

对着那视野外的家伙、贝蒂依然鼓着脸颊

【不要说失礼的话哦。再说了、昴和贝蒂的羁绊是无限大的……昴想说什么、贝蒂一看眼睛就全知道了哦。】

【原来如此原来如此、不愧是精灵使与契约精灵吗？我身边倒是挺多和精灵沾边的、但那种门外汉实在很难凭感觉理解呢。】

【别的另当别论，贝蒂和昴的关系是独一无二的哦。嘛、契约过的精灵应该都是这么想的、所以最好不要不懂装懂、那样对你没好处哦。】

【嗯，多谢建议。哦对了、差不多我也该打个招呼了呢。】

说着，盲区那边的对方似乎向贝蒂征求了打招呼的许可。

被请求的贝蒂轻轻叹了口气、用那双大眼睛凝视着昴。问是否可以让他打招呼、昴拼尽全力点了点头。

【——唔】

【真没办法、看在他的份上、要心怀感激的去打招呼哦！】

【那还真是谢谢你呢！腹黑的嘴果然是名不虚传啊、真是的。】

一边说着、一边噔噔地踏着地板、对方走近过来。

总觉得、是听过的那种口气——但对那声音本身却没有什么印象。只能以真·砧板上的鱼、这样的姿态迎接对方的靠近。

贝蒂慢慢抽身、在可视的空间内、猛地、对方的容颜挤进来、映入眼帘。

那是以绿色为基调的服装和大帽子、有些毛躁的灰发、带着中性感的面容的——【不认识】的温雅男子的脸——

【你好、初次见面、菜月·昴先生。——我的名字是尼古拉·苏文。虽然有很多头衔、但姑且、商人这个身份可能最合适吧。】

垂下眼角的温雅男子——尼古拉·苏文、如此自称。

面对报上苏文这个听着耳熟之姓、昴睁大了眼睛。然而、仿佛要加速这份惊讶与混乱一般、他并没有停下。

【听到这个姓您可能已经感到吃惊、但趁着身体还无法好好活动的现在、虽然很残酷、但我要再告诉您一个更令人震惊的事情吧。——您被【逆贼】阿尔德巴兰之手封印后、至今为止、大约已经过去了四百年了。】

　――――。

　――――――――。

　――――――――――――。

【――。――――。――――――哎？】

【是四百年。您明白吗？您……不、您和贝蒂酱醒来的时候、已经是您所在时代的四百年后了。罢了、他想说的也就这样告诉您吧。】

理解、完全跟不上。

不是信息的量、而是被质的洪流冲走、吞没。

在这样一个昴面前、言出巨浪的温雅男子——与熟知的友人有着相同特征的尼古拉继续说道。

——

【——无论如何、也让人等得太久了吧、菜月先生】

这是跨越了四百年、经由无数个生命传递而来的、友人那无奈的斥责。

△▼△▼△▼△

——神明大人、佛祖大人、欧德·拉古纳大人。我发誓、此生绝不会悼亡他逝。

△▼△▼△▼△

【真的是、极其——漫长的苦难历史啊。甚至可以说是、苏文家代代相传的大工程呢。——莫戈雷德大喷口、回收在那深处沉眠的你们的这份业务。】

一边说着、一边用双手叽里咕噜旋转着脱下帽子的温雅男子——尼古拉、仿佛回想起至今为止的所有辛劳、深深地叹了口气。

他所讲述的把背负的所有辛劳的姿态、以及仿佛在说“真没办法”般的口吻、让昴在尼古拉与友人——奥托·苏文之间终于产生了共鸣、心头一紧。

真像啊。越是反复不去承认、就越是觉得空虚般地、真像啊。

但是、一旦承认了这一点、就不得不接受下去。

接受如今菜月·昴所处的这个状况、并非梦境或幻觉、而是——现实。

【尼古拉、你兴奋的心情我明白、而且对你再怎么感谢也不为过哦。但是、昴可还不是大病初愈啊。实际上、他光是看到你的脸、听到你的名字就快晕过去了哦。禁止乱来哦。】

【不、我明白的？虽然我明白是明白、但我这边也是相当憋屈啊、或者说早已忍耐到极限啊……不管是打捞现场还是初次见面都不让我露面、苏文家四百年的悲愿就此实现、到底什么时候才能让我切实的感受到啊！】

【说到切实感受、贝蒂应该已经让你充分感受过了哦。莫非、你还觉得『穿越门』被甩来甩去得还不够吗？】

【能不能别说得好像是我求您这么做的一样啊！？】

瞪大双眼而叹息、尼古拉的举止、简直和奥托一模一样。

不过、比起奥托、尼古拉还要再稍微年轻一些、也觉得他更瘦弱。头发也比奥托长、在背部中央束起来的那副模样、与其说是商人、更给人一种学者的感觉。

细节之处的差异与相同——尼古拉·苏文、毫无疑问、正如他介绍的那样——

【是个一点就通的家伙呢。真不愧是、奥托的子孙呢。】

【先祖大人到底和二位有过怎样的交往啊、说实话我都想同情他了。嘛、是因为关系好到爆炸才会这样随意、大概就是这种感觉吧。】

【——是这样的哦。他是个好人、也是个出色的男人哦。正因如此、能让子孙把昴和贝蒂挖出来这种事、简直好到了过分的地步哦。】

那与其说是优秀、不如说、更像是一个执念深重的往事。

确实、奥托绝非只是半途加入的成员、他以阵营种不可或缺的表现活跃着、但真正让奥托成为奥托的、并非他的内政能力或【言灵加护】的力量、而是他与生俱来的胆识、机敏、以及毅力。

为了达成目的、不惜做出任何努力的坚韧——那正是奥托·苏文最大的武器、最终甚至动用了子孙尼古拉等人、才得以实现。

真是个、了不起的男人啊。——可是、连直接称赞他的机会、都已经没有了。

已经、连再交谈、再相视而笑、都做不到了、

【——呜】

【斯巴鲁……】

泪水毫不留情地涌了上来、润湿了视野、注意到昴急促呼吸的贝蒂、用手帕轻轻拭去那落下的泪珠。

被贝蒂此般温柔拭去悲伤的同时、昴还是哽咽了。

他承认了。或者说

不得不、承认了。

时间的残酷流逝、以及自己败北的这一结局。

【————】

慢慢地将七零八落的菜月昴的意识聚拢起来、醒来之前的最后记忆、是被【死者之书】的书架包围的普雷阿迪斯监视塔的那一幕——被担忧的阿尔背叛、被他亲手连贝蒂一起、用禁术封印的瞬间。

而从那以后、昴和贝蒂一直被封印着、度过了四百年的时光、在如今的时代醒来。——已经、那时候的任何人都不在了、在这个时代。

【——呜】

忍不住、不断涌出的呜咽与泪水。

只是纯粹地、为自己的不争气而感到想要死去。

窝囊、悲惨、难看、想死一样地逊、真是个蠢货啊。

仅仅一次失误、就会发生无法挽回的事。明明应该知道的。正因不是别人、而是普莉希拉的死、本应让昴学到了这一点。

尽管如此、菜月昴还是失误了。

失误了、将一切抛在身后、把义务和使命全都抛弃、到了现在。

【——呃】

好想、死去。

那并不仅仅是因为悲惨和无力、而是作为实用价值也值得尝试的【死】。

现在、如果发动【死亡回归】、或许能够回去。回到四百年前。

然而——

【————】

昴的身体无法动弹。就连死去、都无法靠自己做到。

退一步来说、片刻不离地守护着昴的贝蒂、也不可能允许昴渴望【死】的决定。

不能死。就是不能死。

就连【死】、如今对于菜月昴也是奢求。

【想哭的心情我很明白哦。尽情地、尽情地哭泣吧、斯巴鲁。无论你流多少泪、贝蒂都会全部给你擦干的哦。】

贝蒂温柔的动作、擦拭着昴不断溢出的泪水。

连在泪水中溺亡的希望都无法保有、但同时又体会着被贝蒂的关心所救赎的心情、昴在希望与绝望的对比下、内心变得一塌糊涂。

如果、只有自己被抛弃到这个荒唐的未来、菜月昴的心无疑会瞬间崩溃、除了腐朽之外别无他路吧。

但是、如果贝蒂不在这里、昴或许能够选择自杀。当然、无论如何如今身体无法动弹、那也只是无法选择的可能性罢了。

【————】

希望与绝望、生与死、过去与未来、凌辱着菜月昴的灵魂。

无可奈何。无能为力。什么都、做不到。

面对走投无路的绝望、然而、只有一点——

【——啊】

只有一点、被蹂躏的灵魂中、有一个燃烧的疑念。

那就是——

【——呃、啊】

【——我明白的哦】

颤抖的嘴唇编织出的不确定的声音、贝蒂将其作为确定的声音接收。

四百年的时光流逝、世界变迁、昴曾经生活的世界中存在的许多人、已经不在世界上的任何地方。但是、这其中也有例外。

即使四百年岁月流逝、其生命也绝不会终结的存在——其代表性的人物就是——

【尼古拉】

【嗯、是的。——艾米莉娅大人呢。】

【————】

那是一种仿佛要抓住最后一根稻草般的心情。

然而、那个名字被若无其事地说出口、昴的心脏强烈地跳动到疼痛的程度。恨不得就那样顺势起身、揪住尼古拉的领子摇晃——无法做到这一点真是令人焦急。

不过、或许是他的气势传达到了、尼古拉轻轻向后仰身说了句【好可怕啊】、同时、

【因为您提前问过了、所以我已经告诉贝阿朵莉斯酱了……那个、关于艾米莉娅大人呢】

【————】

【其实、我也不知道。】

【——啊？】

明明怀着仿佛心脏被老虎钳夹住般的心情、等待的结果却是这般令人泄气

不由得用无法自由活动的喉咙、发出低沉声音的昴、

对此尼古拉连忙【不不不】地在面前摆了摆手、

【请、请不要生气。我不是在开玩笑或者卖关子、我是真的不知道啊！艾米莉娅大人是否平安无恙这件事】

【……那个理由也说说看吧。不然的话、根本无法接受的哦。】

【就算这话从贝蒂酱口中说出……那样也太残酷了把。啊啊真是的、又不能交给露梅拉小姐或罗莎琳德阁下、真是抽到了下下签啊。】

尼古拉使劲挠了挠自己的头、叹了口气、仿佛在说“真没办法”。然后竖起一根手指——【听好了吗】

【首先、为了不让你误解、我先说一下、艾米莉娅大人还活着。这一点毫无疑问。只是、没有能够和她接触的手段、所以不知道她是否平安无事。】

【——呃、啊】

【您不明白意思吗。我再说得浅显一点。艾米莉娅大人现在、在统一帝国沃拉基亚与古斯提科圣王国的国境沿线的阿格萨德溪谷——她把那条大溪谷整个冻住了、切断了与外界的接触。而且】

【————】

【——连同【逆贼】阿尔德巴兰一起、她把自己也关在了那片冰障之中。】

难以置信的信息被一口气输入、昴再次屏住了呼吸。

如果眼皮能更自由地活动、他大概会反复眨眼两三回吧。尼古拉揭露的事实、就是如此带有冲击力的内容。

——艾米莉娅还活着。但是、在大溪谷、与阿尔一起处于被冰封的状态。

【————】

原因、能够理解。

在水门都市普利斯特拉、将遭受【色欲】权能侵害的人们进行冷冻沉眠同样的做法。艾米莉娅自己也、有着将自己冰封百年以上的过去。

她对自己和阿尔进行了同样的手段、封印在冰中。

其理由是——

【为了——不让那个男人死掉吧。而且那是——】

【呃、啊】

【——为了不失去、救回昴和贝蒂的方法呢。】

贝蒂得出与昴相同结论、昴由衷同意她的话。

艾米莉娅将阿尔连同自己一起冰封的背景——那只能认为是、为了不让阿尔死去。而艾米莉娅这样做的理由是、因为她认为、只有将把昴封印的阿尔、才有解开那个封印的方法。

至少、如果阿尔死了、知道那个方法的可能或许就将永远丢失。

艾米莉娅为了阻止这一点、采取了强硬手段。

【实际上、考虑到【逆贼】阿尔德巴兰所犯下的错事、在当时的情势下他也难逃死刑吧。嘛、最后由于还是用了别的方法才解开了菜月先生你们的封印、所以并没有依赖阿尔德巴兰的能力就是了】

【但——】

既然被救了、就无法对尼古拉的选择——艾米莉娅的努力变得毫无意义——这一点提出抱怨。不过、反过来说、在昴已经被救出的现在、艾米莉娅把自己冰封、维持不让任何人出手干涉状态的理由、应该也不复存在了。

那么、将冰封的艾米莉娅解放出来、也应该是可以做到的——虽然不知道、和被冰封的艾米莉娅一起被封住的阿尔、该跟他说些什么才好。

只是、如果阿尔的目的是将昴永远抹除、那么那个目标也已经失败、只会了结一个没有胜者的结局、跨越数百年的结局。

即便如此、即便如此。即便如此——至少、如果能再见到艾米莉娅的话——

【——其实、不止如此哦。无法见到艾米莉娅大人的原因还有其他】

【——哦、没听说过。贝蒂本来还以为、只要融化那块冰、就能把艾米莉娅放出来了呢。你是在骗我吗！？】

【请您别说得那么难听！我不是骗您、而是这个、怎么说呢、因为会导致情况复杂化、所以解释起来很困难……总之！艾米莉娅大人为了不让任何人出手、连同自己一起冰封了、但除了那是超强力魔法以外、还有一个问题。】

【什么、啊？】

【——是『魔女』】

【————】

出乎意料的词语、让昴和贝蒂倒吸一口凉气。

在这里、【魔女】——魔女教、或是【嫉妒魔女】、无论哪一个挡在面前、都是何等漫长的难题啊。

然而、尼古拉接下来的话语、进一步超越了昴他们的想象。

因为——

【——【忧郁魔女】、以艾米莉娅大人所在的冰河为根据地、把试图靠近的人一个接一个地消灭。所以、谁都无法出手。】

那正是、跨越了四百年时光的昴、他们所不知道的、【魔女】的崛起。

△▼△▼△▼△

——神明大人、佛祖大人、欧德·拉古纳大人。我发誓、此生绝不会与他人相拥。

△▼△▼△▼△

【菜月昴大人！听说您已经醒了！】

【咳噗、咳、咳】

被砰的一声猛然打开房门吓了一跳、正在吃的粥呛进昴的气管。

正面对面喂他吃饭的贝蒂被剧烈咳嗽的昴喷出的粥糊了一脸、【呜呀——！】地翻倒过去。

转瞬之间、市内便化为尸横遍野的惨烈战场。

【你、你、你、你为什么偏要朝着贝蒂可爱的脸咳啊！米粒全喷在贝蒂脸上了啊！】

【啊、咳……因为、咳、一直在、咳、看、着、你、啊——】

【唔……真没办法呢。来，把脸转过来。我给你擦擦嘴边。】

听到仍在呛咳的昴的解释、擦完自己脸的贝蒂叹了口气、也帮昴擦了擦脸。然而，与那温柔的动作相反，她紧接着要说的语气就略显冷淡。

不过那并非针对昴，而是朝着造成麻烦的那一位去的。

面对贝蒂那可爱却带刺的声音、对方吓得浑身一颤。

【你就这样大大咧咧的闯进来了呢、探望病后初愈的病人、总该有点礼数的吧。】

【那、那个、贝蒂大人……我完全没有恶意啊！我只是纯粹地、激情满满地祈祷二位平安无事……】

【是呢、差点就用你的手给那份祈祷画上句号了哦。……但是我觉得你并不是故意的，别那么搞得一团糟啦】

【哎呀！我明明比贝蒂大人个子高得多呢！我露梅拉、就像熊熊燃烧的火焰一般、茁壮成长呢！】

【你一提起热情、房间就会变热、为了斯巴鲁、你还是克制一点吧。】

【呜呜、好吧……】

被这么一说、垂头丧气地耷拉下肩膀的、是一位有着波浪般的亮眼绯红长发与眼眸、身穿同色连衣裙的高挑美女。

身高比昴还高、大概有1米8以上吧。与身高相称的丰满体态、与华丽奢华的装扮相得益彰、是一位极具傲人美貌的女性。

又是一位未曾见过的女性——登场、被扶起上半身坐在床上、正由贝蒂亲手喂饭的昴、瞪大了眼睛。

【哎？】

【哎呀！哎呀哎呀哎呀！比尼古拉大人说的还要精神得多、我就像激情燃烧样的感动啊！话说回来、您和贝蒂大人真的一点都没变……我从心底里感到高兴哦！】

【露梅拉！热——不对，已经是烫了吧！】

【哎呀哎呀！我可真是燃得滚烫呢！】

面对那位步步逼近的高挑美女、贝蒂用小小的身体将她挡了回去。那位美女——被叫做露梅拉的人物在胸前双手合十、脸颊泛红、【哦呵呵——】地笑着掩饰、为自己的气场和举动感到羞愧、

面对她那气势汹汹的靠近、昴确实感受到了热度袭来。贝蒂说的没错——露梅拉明显在感应周围的玛那，并散发出热量。

而且那还是随着情绪高涨而引发的、无意识的强烈热量。从这件事情、以及她有些超脱世俗的气场来看、昴隐约猜到了她的真实身份。

【精、灵、吗？】

【——？嗯、燃烧殆尽般地肯定哦！当然、我可不是普通的精灵呢。我可是大精灵哦！自那以后过了漫长的岁月、我露梅拉也终于达到了大精灵的境界呢！】

露梅拉颜开一笑、将手放在自己丰满的胸前、一副骄傲的样子。

也就是说、是与贝蒂相同的人形大精灵——据说精灵成长时、能够自己选择自己的形态、但选择人形的似乎极少。因此、像贝蒂和露梅拉这样两个人形精灵凑在一起、是非常罕见的景象。

然而、露梅拉的言行中、昴感到了一种奇怪的违和感。

【说、话、好、怪】

露梅拉的说话方式多少有些独特、或许只是措辞奇怪罢了。但她的态度细节中、不仅有见到昴的喜悦、还包含着一种重逢的喜悦。

然而昴对她并没有印象。本来、精灵相关的熟人几乎就没有，所以根本无需再动动脑。

** COMMENT 日文原文

转自[[https://ncode.syosetu.com/n2267be/771/]]

リゼロＥＸ　『ゼロカラササゲルイセカイセイカツ』
恒例のエイプリルフール、恒例の遅刻です！　すまなんだ！

色々今回も何をするか悩みましたが、悩んだ結果、いいものが出たと思います。

今回のお話もＩＦストーリーですが、これまでとまた違った毛色の作品かと。

ではでは、楽しんで！　あとがきでお会いしましょう！





　――神様、仏様、オド・ラグナ様。生涯、誰の名前も呼びかけないと誓います。







　　　　　　　　　　　　　　　　△▼△▼△▼△





　――轟々と、身を切るような冷たい風が、絶氷河全体を包み込んでいた。



「――――」



　厚手の防寒具を着込んでなお、貫くような空気の冷たさを味わいながら、白い息でけぶりそうになる視界を懸命に押し開き、前を見る。

　ただ寒さだけを相手にするなら、もっと着込む要素もいくらでもあっただろう。だが、ここで相手にすべき真の敵は、吹き付ける風や雪ではない。

　もっともっと明確に、こちらの命に対して刃を突き付けてくる脅威であるのだ。



「――怖いかしら？」



　ふと、そう尋ねる声を聞いて、相手の柔らかな手の感触を意識する。

　繋ぎっ放しの左手に感じる温かな熱は、どれほどの苦境に立たされようと、決して自分を見放すことのない、信頼と親愛しかない最高のパートナーだ。



「いや、他にも庇護心とか可愛げとか情熱とか、おおよそポジティブな気持ちはいくらでも詰め込めるからな……お前を褒め称える言葉が足りねぇぜ」



「ふふん、当然なのよ。その足りない言葉、時間が許す限りいくらでも聞いてあげたいのは山々だけど……今は、ちょっと邪魔者がいるかしら」



「だな。――ったく、わかっちゃいたが、勘弁してほしいぜ」



　可愛いパートナーの言葉に賛同し、肩をすくめながら視線は正面――軽口を叩き合いながらも、微塵も緩まない警戒を、そこにいる存在に注ぎ続ける。

　正直、緊張も警戒も、どれだけ注いだところで、十分なんて言えない相手だ。



「いまだに物差しとして機能するのはどうかと思うが……お前のヤバさと比べたら、レグルスなんて可愛い……いや、可愛くはねぇか。レグルスなんてノミみたいなもんだな」



「――それは、貴君からの特別な評価と受け取り、受け取っておこう」



　こちらのぼやきを地獄耳で拾い、律義に返答してくる相手に片目をつむる。

　ゆったりとした立ち姿、壮麗な装いに鍛え上げられた長躯、恐ろしく強い意志を貫徹する姿勢を示した眼光と、わずかに雪焼けしたような浅黒い肌。その肌に淡く浮かび上がったのは、梵字めいた不可思議な紋様のタトゥー。

　見るからに只者ではない風貌の男は、紛れもなく只者ではない。――少なくとも、今の世界の全土を見渡しても、彼に勝てるものは皆無だろう。



　――人呼んで『狂皇子』。

　それが今、極寒の暴風が渦巻く絶氷河で、自分たちが対峙する強敵である。



「対峙、か。……なんで、俺たちはやり合わなきゃならねぇんだろうな」



「自問か？　疑問だとしたら、疑問するその態度に疑問しなくてはならない。何故かについてなら、我輩は貴君らと散々言葉を交わしたはずだ。その上で決裂した。故にこうなっている。――我輩としても、不本意でならん」



「不本意？　そりゃまたどうして」



「我輩は、貴君に恨みも憎しみも抱いていない。我輩と貴君がこうして向き合わなければならぬ理由に、互いへの好悪や憎悪は無縁なのだ。ただ――」



　そう言って、一度言葉を区切った『狂皇子』が目を細め、視線をわずかに下げる。それにより、視線の向きが自分から、傍らのパートナーに移ったのがわかった。

　瞬間、どろりとした、粘性を帯びた消えることのない憎悪が、相手から漏れる。



　それは確かに、『狂皇子』が対峙する自分には決して向けない感情。その上で、絶対にあの男と、自分とが相容れない理由でもあった。

　その、隠さぬ憎悪を垂れ流しにしながら、『狂皇子』は告げる。



「――その汚穢を巡り、我輩と貴公とは相容れない」



「まず、俺の超可愛いパートナーを捕まえて、汚れ扱いするその美的センスが全く理解できねぇぜ。だから、お前とは友達になれねぇんだ」



「至極、残念だ。残念だから、残念でならない。残念ながら、手は引かないが」



　ゆるゆると首を横に振り、説得失敗を悔やむように『狂皇子』が嘆息する。しかし、あれで説得する気があったというなら、価値観の溝は永遠に埋まるまい。



「本当に会話にならん奴なのよ。……セシルスの方がまだ話せたかしら」



「比べたらセッシーが可哀想だよ。セッシーは別に全然話せた……ただちょっと、話の結論がセッシー好みに勝手に着地するだけだ。強者の理屈って感じ」



「でも、それを通させるわけにはいかないのよ。――わかってるはずかしら」



「――ああ、言われるまでもねぇ。言われた方が気合い入るけど」



　きゅっと、繋いだ手に力を込め直して、ちらと視線を向け合って笑みを交換。

　強敵との対決を前に、パートナーとの連帯感は十分。――そして、戦場をこの場所に選定し、長く対話に時間を割いた理由が、不意にくる。

　それは視界の端、刹那だけ光って感じられた絶氷のプリズム――、



「「――Ｅ・Ｍ・Ｍ！！」」



　瞬間、声を重ねた詠唱が発動し、絶対防御魔法が自分とパートナーとを包み、この世界から存在を半歩ずらすことであらゆる干渉を無力化する。

　その、実像のブレた自分たちの体を通り抜け、向こう側に突き抜けていったのは、容赦なく膝下をぶち抜いていこうとした白光だ。もし防いでいなければ、仲良く並んだ自分たちは揃って足を撃ち抜かれ、戦闘不能状態に陥ったはず。



　そしてそれは、同じように『狂皇子』をも狙っていたが――、



「――全力か？　それとも我輩を怒らせたいのか？　挑発というのであれば、その報いは受けてもらうが？　受けさせるのは我輩、受けるのは貴公だ」



　言った『狂皇子』が、立てた二本の指で白光を挟み、受け止めていた。

　光は男の指先でゆっくりとその光輝を失い、やがて一本の長い針の本体を晒すと、それも散り散りになって霧散していく。――魔法で構築した針を、超高速でぶっ放すそれは、こう呼ばれていた。



「ヘルズ・スナイプ……ってことは」



「――またあなたなんだ？　懲りないね。何回きたっておんなじなのに」



「――――」



　不意に、上空から降ってくるその声に、思わず息を詰めた。

　風は、今も轟々と吹き付けている。にも拘わらず、どうしてだろうか。何故、これほどの風の中にあっても、その声はしっかりとこの鼓膜を揺すぶるのか。

　あるいは強者の理屈とは、自然の法則さえもねじ伏せ、従わせる力を持つのか。

　仮にそれが事実なら、その声が吹雪を切り裂いて届くのも道理だ。

　なにせ、この絶氷河の空に悠然と現れた存在、彼女は――、



「――久しいな、『憂鬱の魔女』。息災かね？」



「知り合いみたいに話しかけてこないでくれる？　わたし、あなたの友達でも気安い知り合いでも何でもないし。わたしが元気かどうかなんてどうでもいいでしょ」



「そうでもなく、そうでもない。何しろ、目下、貴公とこちらの彼は、我輩の目的を達する上での確かな障害だ。体調不良の時節があるならばぜひつけ込みたい」



「へえ、そうなんだ？　じゃあ、わたしが絶不調って嘘の噂を流したら、それを信じてのこのこ飛び込んできてくれるの？　すごーい、死んじゃえ」



　ぱちぱちと、胸の前で小さく手を叩いて、その寒空に浮遊する女が残酷に笑う。



「――――」



　それは、美しい女だった。

　長く伸ばした赤みがかった茶髪をリボンでまとめ、桃色と水色と金色と、複数の色を混ぜ込んだ特殊な紋様の入ったドレスを纏っている。

　白く細い肩を露出したその装いは、極寒の絶氷地帯では信じられないほどの薄着だが、吐く息すら白くしない彼女にとって、それは何の障害にもならないらしい。

　吹雪の音が、その唇から漏れる美しい音色を遮ることができないのと同じように、暑さ寒さや天候の不順など、彼女のやりたいことを、したい格好を妨げることはできない。



「――きたのよ」



　息を呑み、身を硬くしたこちらの意識を、その呼びかけが引き戻した。

　同じ相手を見上げ、きっと同じ心境に辿り着いたはずのパートナーは、しかしこちらの気持ちに配慮して、溢れ出す感情を懸命に堪えてくれている。

　そう思いやられることを、情けないとも、申し訳ないとも思わない。――ただ、せっかくの厚意を無下にしてはならないと、大きく息を吸った。

　そして――、



「――ようやくまた会えたな、■■■！」



「――――」



　声を大にして、白くけぶった風の向こうにいる彼女に、そう呼びかける。

　生憎と、彼女や『狂皇子』と違い、こちとら風をねじ伏せる術なんて持たない。

　それに、溜めに溜めたこの瞬間の声を、相手に届かなかったからと言い直すなんて、そんなクソダサい真似も絶対にしたくない。



　いったい、どれだけこの瞬間を待ちわびただろう。

　どれほどの無力感を噛みしめ、踏み越えて、ここまでやってきただろう。



　その全部の結実を求め、息を吸い――ナツキ・スバルは、■■■を見つめる。

　見つめながら、言った。



「お前を取り戻すぜ、■■■。――運命様、上等だ！！」



　それは、ナツキ・スバルがこの極寒の地を踏むまでにかけた長い時間、それだけの時をかけた理由の結実であり、全てを捧げると決めた日々の決算たる宣言であった。





　　　　　　　　　　　　　　　　△▼△▼△▼△







　――神様、仏様、オド・ラグナ様。生涯、誰かの命を背負わないと誓います。







　　　　　　　　　　　　　　　　△▼△▼△▼△





　――暗い。暗い。暗い。暗い淵に、揺蕩い続けた。



　微睡みのように曖昧で、永劫のように不確かで、泥濘のように散漫で。

　一冊の本の中の、夢と現のページの境目にあり続けるような、そんな曖昧で不確かで散漫な、終わることのない暗闇を揺蕩っていた。



　いったい、どれほどこうしているだろう。

　いったい、あとどれだけこうしているのだろう。

　いったい、この延々と続く刹那はどこまで続くのだろう。



　そうした、あって当然の思考、疑問、命題さえも、暗闇は薄く引き伸ばしていく。

　引き伸ばされたそれはペラペラの薄紙みたいで、少し強く突くだけで簡単に破れ、繋ぎ目がわからなくなり、やがては元の形を逸してしまう。



　きっと、もう何度もそれを繰り返している。

　散逸する意識を掻き集め、寄せ集め、繋ぎ合わせて、ほんの些細な力の込め方で容易くそれを突き壊して、また散り散りの粉々にしてしまって。



　いっそ、数もわからなくなるくらい毀れてしまったモノなんて、繋ぎ止めようとするのをやめてしまえばいい。――なのに、それはできない。



　――暗い。暗い。暗い。暗い淵に、揺蕩い続けている。



　微睡みのように曖昧で、永劫のように不確かで、泥濘のように散漫で――でも、決して独りではない暗闇に、揺蕩い続けていた。



　独りではない。独りにはならない。

　引き伸ばされる刹那を、繰り返し続ける失敗を、揺蕩い続ける暗闇を、独りではないという理由が引き止めて、消えてなくなることを良しとしない。



　自己の定義も不完全で、独りではない根拠も黒い霧中に覆われているのに、それでも、投げ出したり、手放したり、諦めたりはできなくて。



　諦めるのは、できなくて。――諦めるのは、似合わないから。



　だから――、





　　　　　　　　　　　　　　　　△▼△▼△▼△





「――――」



　視界が開け、外の世界に放り出された瞬間、押し寄せてくる情報の洪水に頭の中が盛大に掻き乱され、肉体は激しく身悶えした。



「――ッ」



　チカチカと、視界が明滅し、赤と黒のコントラストが交互に世界を凌辱する。

　伸びた手足にはピンと力が入り、無意識のブレーキが外れた肉体への酷使が、恐ろしいことに指先から付け根に至るまで、全ての関節の筋肉を順番に攣らせた。

　痛み、心身の隅々にまでわたる痛み、それが、身も心も掴んで、放さない。



「焼き切れましたわー！！　からの、ちょちょちょ！？　これ、大丈夫ですかしら！？　陸に打ち上げられたお魚さんの状態ですかしらよ！？」



「黙るのじゃ、ルーメラ。如何にそなたの見てくれが常軌を逸して愛らしかろうと、余の耳元で喚くのを許した覚えはないぞ。そも、当然の結果じゃろう」



「当然！？　閣下、今当然って仰いました？　わかってたんですか、これが！？」



「余の『陽剣』は焼きたいものを焼き、斬りたいものを斬る。とはいえ、正規の手段を踏んでおらぬ出し方ゆえ、不都合が働くのも否めんじゃろう」



「……それ、前もって言ったっちゃ？」



「これしきのこと言わずともわかるじゃろう。貴様らは揃いも揃って、賢くもまだ幼き余より年長であるのじゃから。それとも雁首揃えて人生サボったか？」



　視覚、聴覚、嗅覚、味覚、触覚。五感がキャッチするあらゆる情報の濁流に呑まれ、意識の撹拌を余儀なくされる頭上、そんな声が飛び交っている。

　その声も、新たなる情報だ。すなわち、押し寄せる濁流の一端だ。



「マズいマズいマズい！　もしこのまま死なれたら、長年の苦労が水の泡ですよ！？　方々駆け回って散々地べたに頭を擦り付けて、ようやく漕ぎつけたのに……うわぁ、誰にも顔向けできなくなる！」



「言ってる場合じゃありませんですのよ！　こういう場合は……そう、荒療治！　多少の痛みも結果が伴えば紛れてエレガント！　きっと主様も、よくやったと微笑んでくださるはずですかしら！」



「それです！　やれるんですか、ルーメラさん！」



「ド無理ですかしらー！　わたくし、燃え盛るほどに火属性ですもの！　火炎にできることは破壊と再生の破壊の部分だけですかしらよ！　おほほほほ！」



「もしかして今これめちゃめちゃただの時間の無駄ですか！？」



　わあわあと、洪水と濁流の中にあっても飛び抜けてうるさい情報が右へ左へ。

　自分を挟んだやり取りが轟々と交わされているのを感じながら、心身の痛みに紛れ、ゆっくりと迫りくる脅威――息苦しさという情報を得る。



「――ぉ」



　胃壁が痙攣し、空気の通り道となっている管が内部の収縮で塞がりかけている。

　不自然な肉体の蠕動が引き起こした悲劇だが、その先に待つのは誰も笑えない喜劇。ただでさえ極度の消耗に衰弱した体が、呼吸不全によって機能を損ねつつある。

　なのに、それをどうにかする方法が、数多の情報に乱される今、見つからない。



「貴様ら、その調子で騒いでおってよいのか？　此奴、死にかけじゃぞ。余とは面識のない男ゆえ、死んだとて余に何の痛痒もないが、貴様らはそうではないじゃろう」



「いやそれは本当の本当にそうなんですけど、結構僕らも限界ギリギリまでリソースぶち込んだりしたので余裕ないわけですよ！　一回、さっきの球の中に戻すとかどうですかダメですかですよねはい！」



「高速で自己解決しよったな。楽しめる男じゃ。――ふむ、そうじゃな。余の光輝を以てしても、死にかけの道化にできることなぞないが……こちらは別じゃ」



「何するつもりっちゃ？」



「たわけ、何を他人事めいた顔をしておるのじゃ、『雲龍』。――そこな男はともかく、こっちの愛い娘にはできることがあるじゃろう」



　対処できないまま、苦しみが募り募り募っていく。

　その苦しみに、痛みに、痙攣に、何もかもが塗り潰され、永劫に引き伸ばされていたはずの刹那が、どっぷりとした終わりを被せにくる。

　このまま――、



「――――」



　――このまま、終わりか？



「――スバル！」



　瞬間、暗く閉ざされつつあった意識を、また別の情報が殴りつける。しかし、今度のそれは、ただ痛みと苦しみを長引かせるものではなかった。

　痛みを痛みで、苦しみを苦しみで、情報を情報で、拭い去るもので。

　そして――、



「死んじゃダメなのよ。死ぬんじゃないかしら……！」



　そしてその情報は、苦しみは、痛みは、よく知る大切なものだったから。



「――ぁ」



　蠕動する胃壁が、閉じかけた喉が、もつれる舌が、明滅する視界が、刹那に呑まれかけた意識が、暗い彼方に散り散りになるはずだった命が、留まる。



　手放すな、何も。放り出すな、全てを。しがみつけ、世界に。

　そうしなくちゃ、それができなくちゃ、そうすることでしか――、



「ぉ、え、お」



「スバル！」



　チカチカと、目障りな赤と黒の光が消えて、逆光に照らされた涙目が見えた。

　蝶を象った特徴的な紋様の瞳、名前を呼びかけてくれる愛おしい声、散らばりかける存在を全力で引き止めている、小さな体の大きな存在。



「えぁ、こ」



「――そう、そうなのよ。そうかしら。大丈夫なのよ、傍にいるかしら」



　どこもかしこも自由にならない体で、脆く痺れてボロボロになった心で、それでも自己を証明するために、それでも相手を覚えていると伝えるために、紡ぐ。

　受け取ってくれる。そう、信頼という架け橋を、目をつむって歩いて渡るように。



「何がどうなっていようと、ベティーたちなら乗り切れるのよ、スバル」



　その、頼もしく心強い言葉をしかと抱きしめて、意識が途切れる。





　――それが、ナツキ・スバルの歩みの再開、その初日の出来事だった。





　　　　　　　　　　　　　　　　△▼△▼△▼△







　――神様、仏様、オド・ラグナ様。生涯、昨日を思わないと誓います。







　　　　　　　　　　　　　　　　△▼△▼△▼△





　うっすらと、瞼が開いたとき、最初に飛び込んできたのは知らない天井だった。



「――ぉあ」



　見たまま、それを口にしようとするも、ガビガビに乾いた口内と、ハチャメチャに荒れた喉はまともな音を奏でてくれず、できたのは不細工に呻くことだけ。

　まるで、潰れた蛙の断末魔だ。

　だが――、



「――起きたかしら。ずいぶんとお寝坊さんで、悪い子なのよ」



　枕元で、その目覚めを待っていた相手にそれを伝えるには十分役立った。

　そっと伸びてくる小さな手に前髪ごと額をくすぐられ、こそばゆさに目を細めたスバルがそちらを見れば、柔らかく目尻を下げる少女――ベアトリスが、いる。



　変わらぬ姿、変わらぬ眼差し、変わらぬ温かみのある彼女が、そこに。

　間違いなく、一寸の違いもなく、意識に焼き付いたままの姿の、ベアトリスが。



「ぇあ、こ」



「そう、ベティーで間違いないかしら。心配いらないから、無茶しちゃダメなのよ。今のスバルは、心と体の配線がメチャメチャで、不自由この上なくなっているかしら」



「は、ぁう」



　無茶、と言われるほど無茶をしようとしたわけではない。

　ただ体を起こし、込み上げる感情のままにベアトリスを抱き上げ、そのまま部屋の外まで飛び出していき、だだっ広いところで二人でくるくる回りたかっただけだ。

　だが、今のスバルにはそれすら高望みの状況らしい。――心と体の配線と、そうベアトリスは喩えてくれたが。



「――ぉ」



　実際、スバルの脳が体の動かし方を忘れてしまったのは事実らしい。

　動かない眼球の端、かろうじてベアトリスを映せているから彼女を捉えられたが、手指どころか眼球さえ、スバルの望んだ通りに転がってくれない。

　体を起こすどころか、何とか呼吸できていることすら奇跡に思える。

　心臓が、鼓動の打ち方を忘れないでいてくれてよかった、というべきか。



「案外、笑い話にもならないのよ。あの中に閉じ込められている間、ベティーはともかく、スバルの生命活動はほとんど停止していたかしら。それこそ、体が当たり前のことを忘れてしまうくらい、だったのよ」



「――ぁ」



「あの空間……ベティーの知らない陰魔法で編まれた、とんでもない代物だったかしら。間違いなく、お母様の手が入ったものなのよ。どうしてあの男が、お母様の作った禁術を習得していたのか、謎は尽きないかしら」



「――ぃ」



「それについて、スバルと議論する気はないのよ。スバルがなんて言おうと、ベティーにとってお母様はお母様、かけがえのない方かしら。ぷい、なのよ」



　たどたどしく入るのは、掠れ息でしかないスバルの合いの手だ。

　しかし、それを受けるベアトリスは抜群の理解度で会話を成立させ、その上で、スバルの額に触れたまま、不満げに頬を膨らませてぷいと顔を背けた。

　その、愛情と不服のどちらか一方に偏れない姿が過剰に愛おしいが――、



「……それ、本当に会話成立してるんですか？　僕にはベアトリスちゃんが、一人で勝手に一喜一憂してるように見えるんですけど」



　ふと聞こえたその声は、スバルとベアトリスのどちらでもない第三者のものだ。

　視界の中、ベアトリスが「む」と横たわるスバルの足の方に目を向けたので、声の主はそっちに立っているらしい。が、生憎とスバルにはそっちを見る手段がない。

　その視界に入ってこない相手に、ベアトリスは頬を膨らませたまま、



「失礼なことを言うんじゃないかしら。大体、スバルとベティーの絆は無限大……スバルが何を言いたいかくらい、目を見ればベティーには筒抜けなのよ」



「なるほどなるほど、さすが精霊使いと契約精霊ってことなんですかね？　わりと周りに精霊の関係者はいる方なんですけど、そこって門外漢には感覚的にわかりづらくて」



「他はともかく、ベティーとスバルの関係は唯一無二かしら。ま、契約した精霊はみんなそう思ってるはずだから、下手に知った口は利かない方が身のためなのよ」



「ええ、アドバイスどうも。とと、そろそろ僕もご挨拶させてもらっていいですかね」



　そう言って、足の向こうの相手は挨拶の許しをベアトリスに求めたようだ。

　具申されたベアトリスは小さく吐息すると、その大きな瞳でスバルを見つめる。挨拶させてもいいか、と確かめる彼女に、スバルは気持ちで頷いた。



「――ぅ」



「仕方ないからツラを拝んでやる。感謝しろ、だそうかしら」



「そりゃまたありがたいですねえ！　口の減らなさは聞いてた通りだなぁ、まったく」



　言いながら、のしのしと床を踏みしめ、声の相手が近付いてくる。

　どことなく、聞いた覚えのある口調――だが、その声自体には聞き覚えがない。そんな相手の接近を、まさにまな板の上の鯉状態で迎えるしかない。

　ゆっくりとベアトリスが身を引くと、確保された視界のスペースに、ひょいと割り込んでくる相手の顔が見えた。



　それは、緑を基調とした服装と大きな帽子、癖のある灰色の髪に、中性的な雰囲気のある顔立ちをした『知らない』優男の顔で――、



「どうも、はじめまして、ナツキ・スバルさん。――僕の名前はニコラ・スーウェン。色んな肩書きがありますが、一応、商人が一番通りがいいかなと」



　目尻を下げた優男――ニコラ・スーウェンが、自らをそう名乗る。

　スーウェンと、そう耳馴染みのある家名を口にした相手に、スバルは目を見張った。しかし、その驚きと混乱に拍車をかけるように、彼は止まらない。



「いきなりのことで驚かれてると思いますが、碌に体の動かない今のうちに、酷ですがさらにショッキングなことを伝えておきますね。――あなたが、『逆賊』アルデバランの手で封じられてから今日まで、おおよそ四百年が過ぎています」



　――――。

　――――――――。

　――――――――――――。



「――。――――。――――――ぁ？」



「四百年です。わかりますか？　あなたが……いえ、あなたとベアトリスちゃんが目覚めたのは、あなたのいた時代の四百年後です。あと、これも伝えておきますね」



　理解が、まるで追いつかない。

　情報の量ではなく、質に押し流され、呑み込まれるスバル。そんなスバルの前で、とんでもない濁流を起こした優男――よく知る友人と、同じ特徴を持ったニコラが続ける。

　それは――、



「――いくら何でも、待たせすぎなんですよ、ナツキさん」



　四百年越しに、いくつもの命を間に挟んで届けられた、友人の呆れた叱責だった。





　　　　　　　　　　　　　　　　△▼△▼△▼△







　――神様、仏様、オド・ラグナ様。生涯、誰かの死を悼まないと誓います。







　　　　　　　　　　　　　　　　△▼△▼△▼△





「本当に、長い長い苦難の歴史でした。まさに、スーウェン家に代々受け継がれる大事業だったんです。――モゴレード大噴口、その奥底に沈んだあなたたちの回収は」



　言いながら、脱いだ帽子を両手でくるくると回している優男――ニコラが、それまでの苦労を思い返すみたいに深いため息をつく。

　その背負い込んだ苦労を語る姿や、仕方ないと言いたげな語り口の雰囲気に、ニコラと友人――オットー・スーウェンの共通項を感じ、スバルは胸が締め付けられた。

　似ている。否定を重ねようとすればするだけ空しくなるほど、似ている。



　だが、それを認めれば、受け入れなくてはならなくなる。

　今、ナツキ・スバルの置かれたこの状況が、夢や幻ではない、現実であるのだと。



「ニコラ、はしゃぐ気持ちはわかるし、お前には感謝してもし足りんのよ。でも、スバルは病み上がりどころの話じゃないかしら。実際、お前の顔を見て、名前を聞いただけでも気絶したくらいなのよ。無茶は禁物かしら」



「いや、わかりますよ？　わかりますけど、僕の方だってだいぶお預けというか、辛抱やる方無しというか……サルベージ現場でも初顔合わせでも引っ込めさせられて、スーウェン家四百年の悲願の達成は、いつになったら実感できるんですか！」



「実感なら、ベティーが十分させてやったはずなのよ。まだ、『扉渡り』であっちにこっちに飛ばされ足りないかしら？」



「まるで僕が望んでやってもらったみたいな言い方やめてくれませんかねえ！？」



　目をかっぴらいて嘆くニコラの姿は、まさにオットーの生き写しだ。

　が、オットーよりもニコラの方がまだわずかに若く、線の細さも感じられる。髪もオットーより長く、背中の真ん中あたりでまとめたそれは、商人というより、学者然とした風貌のそれに感じられた。

　細部の違いと共通点、ニコラ・スーウェンは紛れもなく、その自己申告通り――、



「打てば響く奴なのよ。さすが、オットーの子孫かしら」



「ご先祖様がお二人とどんな付き合いをしてたのか、正直同情したくなりますよ。まぁ、親しかったからこその気安さ、って感じですかね」



「――なのよ。いい人間だったし、優秀な男だったかしら。それこそ、子孫にスバルとベティーを掘り出させるなんて、やりすぎなくらいなのよ」



　それは優秀さというより、執念深さを象徴するようなエピソードに感じる。

　確かに、行きずりで加わったと思えないくらい、陣営に欠かせない有能ぶりで活躍したオットーだが、真にオットーをオットーたらしめていたのは、その内政力や『言霊の加護』の力ではなく、持ち前の度胸と機転、そして根性だった。



　目的を果たすためなら、どんな労力も惜しまない粘り強さ。――それがオットー・スーウェンの最大の武器であり、ついには子孫のニコラたちをも利用し、成し遂げた。



　本当に、すごい男だ。――なのに、それを直接称える機会は、もうない。

　もう、話すことも、笑い合うことも、できない。



「――ぅ」



「スバル……」



　じわりと、容赦なく込み上げた涙に視界を潤ませられ、息を詰めたスバルに気付いたベアトリスが、その雫をそっとハンカチで拭う。

　そうしたベアトリスの優しさに悲しみを拭われながら、スバルは嗚咽した。



　認めた。認めざる、を得なかった。

　時の残酷な流れと、自分たちの敗北という結末を。



「――――」



　ゆっくりと、散り散りになったナツキ・スバルの意識を掻き集めれば、目覚める前の最後の記憶は、『死者の書』の書架に囲まれたプレアデス監視塔の一幕。――その心を案じたアルに裏切られ、彼の手でベアトリスごと、禁術によって封じ込められた刹那だ。



　そしてあれ以降、スバルとベアトリスは封じられたまま、四百年もの時を過ごし、今の時代で目覚めた。――もう、あの頃の誰もいない、この時代に。



「――ぃ」



　こぼれる嗚咽と涙を、我慢できない。

　ただひたすらに、自分が不甲斐なくて、死んでしまいたかった。



　情けなくて、惨めで、みっともなくて、死にたいぐらいダサくて、馬鹿だ。

　たった一度のしくじりで、取り返しのつかないことは起こる。知っていたはずだ。他ならぬプリシラの死が、スバルにそれを学ばせたはずだった。



　それなのに、ナツキ・スバルはしくじった。

　しくじって、何もかもを置き去りに、義務も使命も全部放り出して、今に。



「――っ」



　死んで、しまいたかった。

　それは惨めさや無力感だけが理由ではない、実利として挑む価値のある『死』だ。

　今、『死に戻り』をすれば、戻れるかもしれない。四百年前に。

　しかし――、



「――――」



　スバルの体は動かない。死ぬことすら、自分ではできない。

　そうでなくても、片時も離れずにスバルを見守ってくれているベアトリスが、『死』を望むスバルの決断を許せるはずがない。



　死ねない。死ねないのだ。

『死』すら、今やナツキ・スバルの手を滑り落ちて。



「泣きたい気持ちはよくわかるかしら。たくさん、たくさん涙を流すのよ、スバル。どれだけ涙を流しても、ベティーが全部拭いてあげるかしら」



　ベアトリスの優しい手つきが、溢れ続けるスバルの涙を拭う。

　涙で溺れる希望すら抱けず、しかし、そのベアトリスの思いやりに救われる心地も同時に味わい、スバルは希望と絶望のコントラストで心がめちゃくちゃになった。



　もし、この途方もない未来に自分だけが投げ出されていたとしたら、間違いなくナツキ・スバルの心は壊れ、朽ちる以外になかっただろう。

　だが、この場にベアトリスがいなかったなら、スバルは自死を選べたかもしれない。無論、どうあれ体の動かない今、それは選びようのない可能性でしかなくて。



「――――」



　希望と絶望が、生と死が、過去と未来が、ナツキ・スバルの魂を凌辱する。

　どうにもならない。どうにもできない。どうも、なりようがない。

　そんな手詰まりの絶望に、しかし、一点だけ――、



「――ぁ」



　一点だけ、蹂躙される魂が、熱を帯びる疑念があった。

　それは――、



「――ぇい、いあ」



「――わかってるのよ」



　震える唇が紡いだ不確かな音を、ベアトリスは確かな音として受け取った。

　四百年の時が流れ、世界は移り変わり、スバルたちの生きた世界にいた多くの人々は、もう世界中どこにもいない。しかし、それにも一部の例外はいる。

　四百年の歳月が流れても、その命尽きることのない存在、その代表格は――、



「ニコラ」



「ええ、はい。――エミリア様ですね」



「――――」



　細い糸に、天から垂れ下がる蜘蛛の糸に、縋るような気持ちだった。

　なのに、平然とその名前が口にされ、スバルの心臓が痛むほどに強く跳ねる。その勢いのままに体を起こし、ニコラの胸倉を掴んで揺すぶれないのがもどかしい。

　だが、気迫だけは伝わったのか、ニコラは「怖いなぁ」とわずかに身を反らしつつ、



「先に聞かれていたので、ベアトリスちゃんにはもうお伝えしたんですが……その、エミリア様はですね」



「――――」



「実は、わかりません」



「――ぁ？」



　ギリギリと、心臓を万力で締められるような思いで待ったのに、その肩透かしだ。

　思わず、自由にならない喉でドスの利いた声を漏らしたスバルに、慌てたニコラが「いやいやいや」と顔の前で手を振って、



「お、怒らないでください。ふざけてるとかもったいぶってるとかじゃなくて、本気でわからないんですよ！　エミリア様がご無事かどうか」



「……その理由も話すかしら。じゃなきゃ、納得なんてできないのよ」



「それはベアトリスちゃんの口から……ってのは酷ですか。ああもう、ルーメラさんやロザリンド閣下には任せられませんし、貧乏くじだなぁ」



　わしわしと自分の頭を掻き毟り、仕方ないとニコラが大きく息を吐く。それから彼は、「いいですか」と指を一本立てると、



「まず、誤解のないように先にお伝えしますが、エミリア様はご存命です。それは間違いありません。ただ、接触する手段がなくて、ご無事かどうかがわからないんです」



「……い、ぃあ」



「意味がわかりませんよね。もう少し噛み砕きます。エミリア様は現在、統一帝国ヴォラキアと、グステコ聖王国との国境沿いにあるアグザッド渓谷――その大渓谷を氷漬けにして、周囲との接触を断たれています。それも」



「――――」



「――『逆賊』アルデバランを、自分ごとその絶氷に閉じ込めて、です」



　耳を疑うような情報、それを流し込まれ、スバルはまたも息を詰まらせる。

　瞼の動きがもっと自由であれば、二度三度と、白黒する目を瞬かせたところだ。そのぐらい、ニコラの明かした事実は衝撃的な内容だった。



　――エミリアは生きている。ただし、大渓谷で、アルと氷漬けの状態で。



「――――」



　原理は、わかる。

　水門都市プリステラで、『色欲』の権能の被害に遭った人々をコールドスリープさせたのと同じ。エミリア自身も、自らを百年以上閉じ込めた過去があると語っていた。

　それと同じことを、彼女は自分とアルに施し、氷に閉じこもったのだ。

　その理由は――、



「あの男を、死なせないためかしら。そしてそれは……」



「ぉえ、たちぉ」



「――スバルとベティーを取り戻す方法、それを失わないため、なのよ」



　スバルと同じ結論に辿り着いたベアトリス、その言葉に心から同意する。

　エミリアが、アルごと自分を氷漬けにした背景――それは、アルを死なせないためとしか考えられない。そしてエミリアがそうした理由は、スバルたちを封じたアルにしか、その封印を解く方法がないと、そう考えたからだ。

　少なくとも、アルの命が失われれば、それを聞き出す選択肢は永遠に失われる。

　エミリアはそれを阻止するために、強硬手段に出た。



「実際、『逆賊』アルデバランのしでかしたことを考えれば、当時の情勢でも処刑は免れなかったはずです。まぁ、最終的にナツキさんたちの封印を解くのには別の方法を使ったので、アルデバランの知識には頼らなかったわけですが」



「でぉ……」



　助けられた以上、エミリアの奮闘を無意味にするニコラの選択に文句は言えない。が、逆を言えば、スバルたちが回収された今、エミリアが自分を氷漬けにして、誰にも手出しさせない状況を維持し続ける理由もなくなったはずだ。

　ならば、氷漬けのエミリアを解放することも、できるはず。――そのエミリアと一緒に氷漬けにされたアルと、何を話せばいいのかはわからないが。



　ただ、アルの目的がスバルを永遠に排除することだったのだとしたら、その狙いも失敗し、勝者のいない結末が数百年越しに露呈するだけ。

　それでも、それでもだ。それでもせめて、エミリアと会えれば――、



「――実は、それだけじゃないんですよ。エミリア様と会えない理由は」



「――っ、聞いてないかしら。てっきり、その氷さえ溶かせば、エミリアを出してやれるってベティーは思っていたのよ。騙したかしら！？」



「人聞き悪いこと言わないでください！　騙したわけじゃなく、こう、状況の複雑化を招くので、説明が難しかったというか……とにかく！　誰にも手出しできないよう、自分ごと氷漬けにしたエミリア様ですが、それが強力な魔法って以外の問題があります」



「そ、えぁ？」



「――『魔女』です」



「――――」



　思いがけない単語に、スバルとベアトリスが息を呑んだ。

　ここで、『魔女』――魔女教か、あるいは『嫉妬の魔女』か、いずれかが立ちはだかってくるとは、どれだけ息の長い問題であるのか。

　しかし、ニコラの続けた言葉は、そんなスバルたちの想像をさらに裏切った。

　何故なら――、



「――『憂鬱の魔女』が、エミリア様のいる絶氷河を根城にしていて、近付こうとする相手を片っ端から襲ってくる。だから、誰も手出しできないんです」



　それは、四百年の時を跨いだスバルたちの、知らない『魔女』の台頭だったから。





　　　　　　　　　　　　　　　　△▼△▼△▼△







　――神様、仏様、オド・ラグナ様。生涯、誰とも抱き合わないと誓います。







　　　　　　　　　　　　　　　　△▼△▼△▼△





「――ナツキ・スバル様！　お目覚めになられたとお聞きしたですかしら！」



「げふがふごふっ」



　騒々しくバーンと開かれた扉に驚いて、食べていたお粥がスバルの気管に入った。

　激しくむせるスバル、その正面でご飯を食べさせてくれていたベアトリスが、吐き出されたお粥をこれでもかと顔面に喰らい、「うきゃーなのよ！」とひっくり返る。

　あわや一瞬で、寝室は死屍累々の大惨状と化していた。



「な、な、な、なんであえてベティーの可愛いお顔目掛けて咳き込むかしら！　米粒が全部、ベティーのお顔に当たったのよ！」



「ぁ、うい……おまえ、を、みてたか、ら」



「む……なら、仕方ないかしら。ほら、顔を見せるのよ。口の周りを拭くかしら」



　むせた余韻を残したスバルの言い訳に、自分の顔を拭き終えたベアトリスが、ため息まじりにこちらの顔も拭いてくれる。だが、その優しい手つきと裏腹に、「それで」と続けた声はやや冷たかった。

　ただしそれはスバルにではなく、今の原因を作った相手に向けたものだ。

　そのベアトリスの可愛いが棘のある声に、相手は盛大にビクッと肩を震わせる。



「お前、ずいぶんと賑やかに飛び込んできたもんなのよ。病み上がりの相手をお見舞いするなら、マナーってものがあるかしら」



「あ、あのう、ベアトリス様……わたくし、悪気なんて一切ありませんでございましてよ？　ただ一身に、燃えるようにお二人のご無事を祈り続けてですかしら……」



「だとしたら、危うくお前の手でその祈りの終止符を打つところだったのよ。……わざとなんて思ってないから、そう小さくなるんじゃないかしら」



「まあ！　わたくし、ベアトリス様より体は大きくてございますかしら。このルーメラ、燃え盛る炎の如く、大きく大きく育ってますですもの！」



「お前がテンション上げると部屋が暑くなるから、スバルのために自重するのよ」



「うう、はいですかしら……」



　そう言われ、しょんぼりと肩を落としたのは、明るく波打つ長い緋色の髪と瞳、それらと同じ色をしたドレスを纏った背の高い美女だ。

　背丈はスバルより大きく、百八十センチ以上あるだろうか。身の丈に見合った豊満な体つきと、派手で豪華な装いがマリアージュした、際立つ美貌の持ち主。

　これまた見覚えのない女性の登場に、ベッドに上体を起こされ、ベアトリスの手ずからご飯を食べさせてもらっていたスバルは、目をぱちくりさせた。



「ぇえ、と？」



「あら！　あらあらあらまあ！　ニコラ様からお聞きしていたより、ずっとずっとお元気そうでわたくし燃え広がるように感激ですかしら！　それにしても、ベアトリス様共々本当にお変わりなく……心よりお喜び申し上げますですのよ！」



「ルーメラ！　暑い……じゃなく、もはや熱いかしら！」



「あらまあ！　燃え滾るほどのわたくしとしたことが！」



　ずんずんと大股で詰め寄ってくる美女との間に割って入り、ベアトリスが小さな体で相手を押し返す。その美女――ルーメラと呼ばれた人物は胸の前で手を合わせ、自分の勢いや行動を恥じらうように頬を染め、「おほほ」と照れ隠しに笑った。

　その彼女の勢いのある接近に、スバルは確かな熱の接近を感じた。ベアトリスの言ったことは事実――ルーメラは明らかに、周囲のマナに感応し、熱を発している。

　それも、感情の昂りに呼応した、無意識で強烈なものだ。その事実と、どこか浮世離れした雰囲気から、スバルは彼女の正体を薄ぼんやりと察した。



「せぃれえ、か？」



「――？　ええ、焼き尽くすほどに肯定ですかしら！　もちろん、ただの精霊ではございませんですますのよ。わたくし、大精霊ですもの！　あれから長い長い年月が過ぎたですかしら、このルーメラも大精霊へと至りましてですわ！」



　そう破顔したルーメラが、自分の豊かな胸に手を当てて誇らしげにする。

　つまり、ベアトリスと同じ人型の大精霊――精霊は成長したとき、自分で自分の姿を選べると聞くが、それで人型を取るものはずっと少ないらしい。だから、こうしてベアトリスとルーメラ、人型の精霊が二人も揃うのは大変レアな光景だ。

　しかし、ルーメラの言動に、スバルは奇妙な引っかかりを覚えている。



「はなしぁ、みぇねぇ」



　少しばかり個性的な言葉遣いをするルーメラなので、ただ単に言葉のチョイスが変なだけかもしれない。が、彼女の態度の端々には、スバルと会えたことを喜んでいるだけではなく、そこに再会を喜んでいるニュアンスがあるのだ。

　だが、スバルには彼女の見覚えがない。そもそも、精霊にも知り合いなんてほとんどいないのだから、心当たりを探るまでもないのだが。



「――――」



「あ、あら？　あらあらあらま？　どうされたんですかしら、ナツキ・スバル様……もしや燻るほどに恐ろしいことに、わたくしとの再会を喜ばれておりませんですの？」



「さすがにそれは被害妄想が過ぎるのよ。お前が大精霊になったと聞いて、スバルもビックリしてるだけかしら。じきに慣れるのよ……スバル？」



　その反応の悪さに、スバルの困惑を感じ取ったルーメラが不安げにする。が、そのルーメラの不安をフォローしたのは、あろうことかベアトリスだった。

　スバルの絶対の味方であるはずのベアトリスは、どういうわけか、ルーメラの存在に心当たりのないスバルに気付かず、わかって当然の顔でいた。

　何故そんな行き違いが起きたのか、スバルはひとまず誤解を解こうとし、



「ぃあ……」



「――はいですかしら！」



「ぇ？」



　いや、と一言間を作ろうとした途端、いきなりルーメラが大声で返事をした。その、パッと顔を明るくした彼女の反応に、スバルはまたも目を丸くする。

　そんなスバルの驚きを余所に、ルーメラはホッと自分の胸を撫で下ろして、



「はぁ、心の底から燃え尽きるほどに安心しましたですかしら。ナツキ・スバル様は、わたくしのことをお忘れになられたのでございますかしらと……それにしても、そう呼ばれるのも久しぶりのことで、嬉しくございますですのよ」



「なま、ぇ……」



　名前を呼んだとそう言われ、スバルは考え込む。

　しかし、それからすぐに、スバルは自分の言葉の何がルーメラにそう思わせたのかに思い至り、そしてそれが意味するところも察して、「あ」と息を呑んだ。

　彼女は確かに、自分の名前を呼ばれたと思って反応したのだ。

　何故ならルーメラは――、



「いぁ、か？」



「ええ、そうですかしら！　この姿でお会いするのは初めてでございますですもの。――わたくし、ルーメラ・イア・ユークリウスは、主様からの燃え上がるほどの特命を果たすため、ナツキ・スバル様とベアトリス様をお探ししていましたですかしら！」



「――――」



　激しく、それこそ燃え上がるような肯定に、スバルはまじまじと彼女を見た。

　ルーメラ・イア・ユークリウス――イアと呼ばれ、それを肯定した彼女は、確かにスバルとの再会を喜ぶ資格を持った存在だ。



『最優の騎士』たるユリウス・ユークリウスと契約し、その精霊騎士としての実力と勇名を支えた六体の準精霊――否、精霊へ昇格し、ついには大精霊へ至った存在。

　四百年前当時、スバルもまだ準精霊だった彼女に助けられたことがあった。そのイアがこうして、ルーメラとしてスバルの前に姿を現した。――違う、そうではない。

　彼女はスバルとベアトリスを回収するのにも、その力を貸してくれたのだ。



「ルーメラは、ニコラの協力者かしら。それで、ベティーたちをモゴレード大噴口から引っ張り出すのに力を貸したのよ。それもこれも、ユリウスの指示で、かしら」



「ゆりぅす、が」



「ですかしら！　今はわたくしたち六人の精霊姫で、ユークリウス領を治める小領主をしておりますですの。本当はラピチャもソヨネもドレナもキアラもシニカも、みんな焼け焦げるくらいナツキ・スバル様との再会を心待ちにしていたのですけれど、ここにはこられなくてとても残念でございましたかしら」



「そ、か」



　轟々と、猛る炎のように前のめりなルーメラ。

　彼女が口にした数々の名前は、おそらくいずれもユリウスの連れていた精霊たちが、大精霊となった今、名乗っている名前なのだろう。元々の名前はミドルネームに、家名はユークリウスを名乗っていると、そういうわけらしい。



「……四百年かけて、ユリウスとの約束を守ったのよ。律儀なことかしら」



「まあ！　わたくしたち、全員燃え広がるほど主様一筋でございますですもの。あの御方のお望みを叶えるためなら、四百年も当然ですかしら！　そのためにニコラ様と協力して……いいえいいえ、今のは鎮火するほど誤った物言いでしたかしら」



「まちが、った？」



「正しくは、代々のスーウェン家の皆様と協力して、ですますのよ。長年の積み重ねが実を結び、今代でそれが叶いましたですかしら」



　功績を自分たちだけの手柄にしないのは、ルーメラが律儀な性格だからというだけでなく、ニコラとの良好な関係を築いているが故の認識だろう。

　その背景に、オットーとユリウスの存在があることに、スバルは嘆息する。



「……ばかやろう」



　自分と契約し、長く尽くしてくれた精霊たちを、自分の死後も消えない盟約で縛り付けるなんて真似、ユリウスらしからぬ優雅さに欠けた選択だ。

　しかもそれを、ヴォラキア帝国ではバチバチにやり合っていたオットーと協力して進めるなんて、手段を選んでいなさすぎる。――否、たぶんそれは、ユリウスやオットーに限った話では、きっとないのだ。



「みんな……」



　直接の繋がりがあるニコラやルーメラがいる分、その行動の結果がわかりやすいオットーとユリウスだが、彼ら以外の面々も、これと無関係のはずがない。

　わかる。確信できる。――みんな、スバルたちのために、必死になってくれたのが。



　ガーフィールが。■■■が。フレデリカが。リューズが。メィリィが。パトラッシュが。ロズワールが。クリンドが。アンネローゼが。ラムが。スピカが。――レムが。



　スバルたちを救う手立てを未来に残すため、その力を使ったエミリア。

　彼女を除いた陣営のみんなが、スバルとベアトリスのために動かなかったわけがない。突然失われたスバルたちを追い、みんながどんな時間を過ごし、今があるのか。

　みんなはいったい、自分たちの時代をどう過ごし、どう終わりを迎えたのか――。



「――っ」



　何もかも、これからだった。

　よくなっていくのも、よくしていこうと志すのも、全部これからだった。あったはずの未来が失われ、届くはずだった希望を取り逃がし、もう何もわからない。



「……ルーメラ、お前はどのくらい、ベティーの仲間のことを知っているのよ」



「申し訳ございませんですかしら。お二人の陣営の方々のことだと、あまり多くは知らないのでございますですのよ。お二人がいなくなられて、アグザッド渓谷が絶氷地帯になった前後は色々ありすぎてしまったですかしら」



「――。まったく、使えない奴かしら」



「うう……わたくし、今やベアトリス様とも肩を並べる大精霊でございますですのに、それでも四大に匹敵する歳月を経た方には頭が上がりませんですかしら……」



　打ちひしがれるスバル、その望んだ答えをルーメラが返せないとわかると、ベアトリスが殊更に冷たくそう言って、大きな精霊姫を凹ませる。

　それがスバルとルーメラ、二人を気まずくさせないためのベアトリスの気遣い。そうわかるものだから、ますますおんぶに抱っこの自分が情けない。

　せめて――、



「いちにちでも、はやく」



　自分の手で、足で、この世界を動き、確かめることができるようにならなければ。

　今のスバルには、偉そうに後悔する資格さえないのだから。





　　　　　　　　　　　　　　　　△▼△▼△▼△







　――神様、仏様、オド・ラグナ様。生涯、自分の名前を残さないと誓います。







　　　　　　　　　　　　　　　　△▼△▼△▼△





　ベアトリスが言うところの、メチャメチャになった心と体の配線。――それを真っ当に繋ぎ直すのには、長く過酷なリハビリが必要になるとのことだった。



「長いことあの空間で魂だけの状態にされて、肉体との接続が剥がされていた後遺症なのよ。肉の器に縛られたニンゲンと、ベティーのような精霊とはお話が違うかしら」



「ひさびさの、じょういそんざい、とーく」



「スバルが自分を過剰に責めないように、ベティーとの違いを言語化してあげただけなのよ。邪推されるなんて、ベティーは大いに傷付いたかしら。ぷい、なのよ」



　そう可愛らしく顔を背けるベアトリスには、スバルと違ってアルのオル・シャマクを喰らった後遺症が見られない。その理由は聞いての通りで、ベアトリスだけでも無事であることが喜ばしい一方、もどかしい思いが強まるのも事実。

　その体とオドとが直結した精霊と違い、スバルは魂と肉体との接続を一つ一つ確かめ、その上で接続した体の操作を脳に思い出させなくてはならない。

　もし仮に配線を間違えようものなら、手を動かそうとして足が動くなんて、そんなちぐはぐな事態も起こりかねないという話だ。



「りはびり、か……」



　不自由極まりない自分の体の調子に、スバルはたどたどしい声でそう呟く。

　スバル自身はもちろんのこと、身近にもそうした状況に陥ったものがいなかったため、あくまで想像でしかないが、長く寝たきりだった人間がリハビリをしようとすると、今のスバルと似たような苦労があるのかもしれない。

　だとしたら、きっとそのコツもおそらく同じ。――焦りすぎないことと、目標をしっかり持って、一歩一歩、それに向かって邁進すること、だ。

　そして、目的に邁進するという点において、今のナツキ・スバルほど強い動機を抱いている人間なんて、そうそういないと言えるだろう。

　とはいえ――、



「――なんじゃ、多少は前よりマシになったかと期待したというに、先月と変わっておらぬようじゃな。余の時間を無駄にするなど、不敬じゃぞ、不敬」



　そう、リハビリに挑むスバルの成果を厳しく評する声がある。

　手厳しい意見だが、スバルにはぐうの音も出ない。実際、その評価は正しい。客観的に見ても、スバルの努力は到底実を結んだとは言えない有様だ。

　その言い返せないでいるスバルに、評価を下した人物が「ふん」と鼻を鳴らし、



「言い返す気概もなさそうじゃ。見下げ果てた男じゃな。せめて、心持ちだけでも負けぬと歯を食い縛らねば、貴様に時を費やしたものたちが浮かばれんじゃろうに」



「閣下、言いすぎ」



「竜にも、哀れに見えてくるっちゃ」



「は、周りのものが気を遣って言わなすぎじゃ。ちゃんと食事が噛めて偉い偉い。飲み込めただけで大した奴じゃ。――不甲斐なさに自憤の涙で溺れ死んではどうじゃ？」



「さすがに、いいすぎ……っ」



　いくら何でもそこまで言われる覚えはないと、お望み通り、スバルも怒る。

　が、その絞り出した怒声を聞いても、相手は涼しい顔で受け流すのだから、全くもって憎たらしいと言わざるを得ない。



「邪魔しにきたなら帰るかしら、ロザリンド。スバルはリハビリで忙しいのよ。お前だって、それなりに忙しい立場のはずかしら、統一皇帝」



「その忙しい合間を縫って足を運んだ余を粗雑に扱うか。ルーメラたちもそうじゃが、貴様ら精霊はいつまで世界の秩序の外側にいるつもりでおるのじゃ？　貴様らが生きる地も得る糧も、全て余の国土のものじゃぞ。ベアトリス、貴様の見てくれが至上の愛らしさでなければ、首を刎ねておるところじゃ」



「言えば？　……気になって、仕事が手につかないって」



「口を慎むのじゃ、『金剛姫』。余への敬意が足らぬのは貴様と『雲龍』もじゃぞ。余が美なるものを愛でる芸術肌と思って、調子に乗りすぎじゃ」



　嘆かわしい、とばかりに額に手をやり、厳しいのかそうでないのか図りかねる発言を重ねる人物が大きなため息をつく。その様子に顔を見合わせたのは、問題の人物を左右から挟むように立った、銀髪の犬人と黒い角の生えた小柄な少女の二人――どちらも、スバルとベアトリスの知っている顔だ。

　それは、この時代で知り合った相手というわけではなく――、



「お前たちも、苦労が尽きないのよ。――アラキア、マデリン」



「竜に余計な配慮は不要っちゃ」



「セシルスより、マシ」



　交互に、気遣いの言葉を口にしたベアトリスに応じたのは、四百年前から旧知の間柄である、ヴォラキア帝国の『九神将』の二人――アラキアとマデリンだ。

　驚くべきことに、この時代で再会した二人は、その外見と立場を変えないまま、四百年が過ぎた今も、ヴォラキア帝国の一員として存在し続けていた。

　そして、その彼女たちを従えているのが――、



「貴様ら、いい度胸じゃな。余を誰と心得るのじゃ。偉大なる統一皇帝たる余、ロザリンド・ヴォラキアなんじゃぞ。そっちのけとは不敬じゃぞ、不敬」



　そう言って、年齢相応の不満を爆発させる幼い少女、ロザリンド・ヴォラキア――ヴォラキア帝国の今代の皇帝にして、アベルやミディアムの子孫。

　その証拠に、不遜な言動や態度の大きさはヴォラキア皇族のそれだが、金色の髪と青い瞳、口調と対照的な丸い目をした愛らしい容貌は、スバルのよく知るオコーネル兄妹の要素がずいぶん色濃く出ている。

　一度、オルバルトの手でスバルが小さくなったとき、同じタイミングでミディアムも小さくなっていたが、あのミディアムとよく似ていた。



「これじゃ、あべるみたいに、くちがわるくても、かわいいだけだな……」



「優れた治世で知られたヴィンセント・ヴォラキア先帝のことじゃな。まぁ、どうせ余より才能のない皇帝のことなどどうでもよいのじゃ。それよりも、いくらせがんでも『金剛姫』が話してくれぬから、『青き雷光』の話を聞かせるのじゃ」



「いい。しなくて」



「するのじゃするのじゃ！　『青き雷光』の伝説を聞くのじゃ！」



　バタバタと短い足をばたつかせ、まだ幼い皇帝がうるさくそうせがむ。その要望にアラキアはこれ以上ないくらいの渋面で、マデリンは呆れ顔だ。

　すでに、ロザリンドの訪問も片手を超える数迎えてきたのでスバルもわかってきたが、この幼帝、どうやらいたくセシルスに憧れているらしい。なのに、当時を知るはずのアラキアたちの口が重たいものだから、代わりをスバルに求めてくるのだ。

　無論、スバルの口から語れる『青き雷光』の話はいくらでもあるのだが。



「お前がくると、リハビリの予定が狂ってよくないかしら。アラキアも、意地悪しないで話してやればいいのよ。セシルスとは添い遂げたはずかしら」



「全然、違う」



「違うっちゃか？　死ぬところまで居合わせたんなら、添い遂げたって言っておかしなことはないって、竜は思うっちゃ。それに――」



「――。なに」



「セシルスに頼まれた通り、こいつら探しに手を貸したっちゃ」



　意地悪な笑みを浮かべたマデリンに言われ、アラキアの渋面が限界まで極まった。

　もはや何を言ってもと思ったのか、アラキアは反論を諦め、ただ唇を結ぶ。だが、彼女がスバルたちのために力を貸してくれた背景がわかって、何とも言えない気分だ。

　まさかあのセシルスが、自分が降りたあとの舞台のことを託すとは。



「存外、多くを残したようじゃぞ、貴様らは。余が『陽剣』の焔を貸したのも、ヴォラキア皇家に伝わった話……鬼の娘の訴えあってのことじゃ」



「――――」



「余の『陽剣』なくして、貴様らは日の目を見ることはありえぬのじゃったのじゃ。努々それを忘れるでないぞ」



　言いながら、掲げた手の中に、空の鞘から抜き取った『陽剣』を握るロザリンド。

　その赤々とした刀身を見せつけてくる幼帝の態度に苦笑しつつ、スバルは今日が初めてではないその話に、深く感じ入る。



　ヴォラキア皇帝に引き継がれる『陽剣』ヴォラキア、それが有した強力な力が、スバルとベアトリスを封じたオル・シャマクの黒球を破壊した。

　それはニコラやルーメラが協力を求めた結果であり、その求めにロザリンドが応じた理由こそが、先の彼女の発言――ヴォラキア皇族に、スバルたちの救済のための助力を願い、約束を取り付けた鬼の娘の存在だった。



「――れむ」



　少しずつ、明らかになっていく足跡に、スバルは何度味わっても慣れることのない痛痒と、それが引き連れてくる涙の熱を味わうことになる。

　レムもまた、スバルたちを襲った悲劇ののちに、自分のできることを果たそうと、ヴォラキア帝国にわたり、そこでアベルたちと話を付けた。あるいはセシルスがアラキアに未来を託そうと考えたのも、レムの存在の影響かもしれない。



　あまりにも、あまりにも多くのものがスバルたちを救おうとして、そうして実際に救い出す未来にまで辿り着いていた。

　だから――、



「おれは……」



「そう言えば、聞いたのじゃ。貴様ら、いずれ動けるようになった暁には、あの絶氷河に挑むそうじゃな。――『魔女』と、事を構えるつもりじゃとか」



「――。ああ」



　言葉少なに頷いて、スバルはロザリンドの問いかけを肯定する。

　今、スバルがリハビリによって体の自由を取り戻す目的、それは絶氷地帯にいるとされるエミリアとの再会だ。――ニコラやルーメラからは非常に危険であり、体が動くようになってから改めて話し合いたいとされているが、曲げる気はない。



　確かに、こうなったことでスバルとベアトリスは、多くを諦めざるを得ない。

　だが、決して届かないという理由で諦めなければならないものと違い、エミリアは必ずやそこにいるのだ。それは、諦める理由になんて、絶対にならない。



「茨の道じゃが、あえてそれを往く姿勢は悪くはないのじゃ。魔女教とやらも王国の滅亡と引き換えになくなり、『嫉妬の魔女』への恐れもほとんど形骸化した世にあって、今もなお『魔女』という肩書きに畏怖を纏わせるのは、『憂鬱の魔女』の存在ゆえ……それがなくなるなら、余にとっても意味のあることじゃ」



「――――」



「む、何ゆえに黙ったのじゃ。不敬じゃぞ、不敬」



「黙りたくもなるのよ。お前、もう少しベティーたちに気を遣うことを覚えるかしら。ベティーたちにとって、歴史書に載っているような出来事も、つい最近のことなのよ。ましてや、王国……ルグニカがなくなったのも、受け止め切れんかしら」



「押し寄せる苦難に打ち勝てなければ滅ぶ。それが人でも土地でも、国でも変わらんというだけの話じゃ。ルグニカもカララギも、もはや歴史書にひっそり消えた名じゃな」



　それが世の習いとばかりに、統一皇帝――ルグニカ王国とカララギ都市国家、それらを併呑したヴォラキア帝国のトップたるロザリンドが肩をすくめる。

　正直、信じ難い出来事があまりに多く打ち寄せるものだから、その事実に関しても、十分に驚き切れているかはわからない。はっきり言って、四百年が経過し、全てを置き去りにしてしまったという事実以上に、スバルたちを揺るがしたものはない。

　かといって、ほんの先頃まで、その王国の玉座を争う王選に全力投球していた身としては、その王国が滅んだという話も、容易くは呑み込めなかった。



「時の流れの中で、変わるものもある。変わらないものもあるっちゃ。どちらに価値を見出すにせよ、ただ流されて悔やむのは愚かなことっちゃ」



　それは、見た目こそ幼くとも、四百年以上の年月を人間と共に生き、その営みを見つめ続けてきた古き竜人の、助言か忠告だったのかもしれない。

　マデリンやアラキア、あるいは三国を呑み込んでさらなる巨大国家となったヴォラキアの皇帝であるロザリンドでさえも、時の流れを止めることはできない。

　だからこそ、ただ唯々諾々と流れに身を任せるなと、そう助言されたと、思う。

　いずれにせよ――、



「――やろぅ」



「その意気なのよ。ベティーも、全力でスバルをサポートするかしら」



　時間が惜しい。時間は、いくらあっても足りない。

　たとえどれほど惜しんでも、砂粒のように指の隙間をこぼれ落ちていくそれを、もう一度手の中に戻すことはできない。だから、手の中にあるうちに、なのだ。



　自分がどれほど恵まれているか、失ってから気付くことがないように、なのだ。





　　　　　　　　　　　　　　　　△▼△▼△▼△







　――神様、仏様、オド・ラグナ様。生涯、安らぎを求めないと誓います。







　　　　　　　　　　　　　　　　△▼△▼△▼△





　――逸る気持ちと、遅々として進まないリハビリの焦りと裏腹に、スバルたちの日々は緩やかに淡々と、皮肉にも大過なく流れていった。



「ベアトリスちゃんの希望ですので、ナツキさんの身の回りの世話は基本的にお任せします。何か必要なことがあれば、いつでも言いつけてください。あまり大きな家も持て余すでしょうから、ひとまずはこの家を必要なだけ使ってくれれば」



　と、そう言ってポンと家を一軒引き渡してくれたニコラには驚かされたが、現状のスバルたちには彼の厚意に甘える以外の選択肢がなかった。

　それでも、ちゃんと借りは返すと伝えると――、



「貸し借りの清算はきっちりと。それは僕も商人の端くれとして好ましい考え方ですよ。でも、ナツキさんたちへのこれは、貸しだとあまり思ってないんですよね」



「それは、どぅして」



「そうですね。……長年の苦労が実ったのは、ナツキさんたちが助かってくれたから、だと思っているのかもしれません」



「――――」



「僕は、スーウェン家の中だとわりと変わり者の方でしてね。兄弟や親類はもう少し落ち着きがあるというか、考え方が大人なんですが、どうも向いてない。大成するか野垂れ死にするかのどちらかだと言われてきました。で、これです」



「これ……」



「スーウェン家四百年の悲願を果たした。ひとまず、これでいつ死んだとしても、野垂れ死にする前に何かを為したと、そう胸を張れるでしょう。だから、お代は結構。僕が手伝えてよかったと、そう思える明日を過ごしてください」



　そう晴れ晴れと言ってのけたニコラに、大きな借りがあると思わないなんてどだい不可能な話だった。それに、改めて強く感じたものだ。――スーウェン家でも変わり種扱いされたというニコラの、隠し切れないオットー性というものを。



「お邪魔いたしましてですかしら、ナツキ・スバル様！　その後、お加減はいかがでございますですこと？　このルーメラ、燃え滾るほどに案じておりましたですかしら！」



　ユークリウス領の統治はどうなっているのか、わりと頻繁に顔を見せるルーメラは、ベアトリスとの友情を築いているのもあるだろうが、とてもよくしてくれている。

　彼女にも、イア時代から世話になりっ放しだ。彼女以外の姉妹たちは、さすがにスバルの見舞いに訪れることはないが、日々の話題には上がっているという。



「自然と、主様のことを思い出す機会にも繋がっていて、わたくしたちも燃え上がるほどに尊い時を重ねておりますですの。もちろん、主様のことを思わない日はないのでございますけど、色も味も濃い思い出を、堪能できていますかしら」



「それぁ、ふくざつなきぶんだ……そぅいえば、おれたちをみつけたときって」



「あら！　あらあらまあ！　お聞きになりたいですかしら？　もうもうそれはそれは、燃え尽きるほどの一大事でございましたことよ？　だって、モゴレード大噴口の大穴は、この世界の裏側まで繋がっていて、流れ込んだものを探すのに大変な苦労が……」



「……よくみつかった、な」



「もちろん、一度でうまくいったわけではございませんかしら。四百年がかりで、足りない技術も力も集めて、わたくしたちみんなでやり遂げたことでございましてですわ」



「――――」



「だから、ナツキ・スバル様、どうかどうか嘆き悲しまないでくださいですかしら。あなた様を、主様の生きた時代に取り戻せなかったこと、わたくしたちも痛恨でしたかしら。でも……」



「ぁぁ。わかってる、るーめら。――ぁりがとぅ」



　四百年と、言葉にすればたったの一言で済んでしまうそれは、実際にその時間を過ごしたものたちにとって、途方もなく大きな意味を持っている。

　ベアトリスが『禁書庫』で過ごした日々も、皮肉にも同じ四百年ほどだった。――言うまでもなく、ベアトリスはその時の重さを知っている。

　四百年という時間が、スバルたちのよく知る人たちの人生を終わらせ、その後に続くものたちの人生をまた終わらせ、それでもまだ届かないほどの長さだということも。

　数多の、スバルたちすら知らないものたちの、スバルたちを救うための奮闘の上に、今のスバルたちがあるのだと、そう思い知らされるほどに。



「くだらぬ感傷じゃ。余らのような立場のものが、貴様らの如き、雑多な塵芥に望みを託されるのは、今に始まったことでも、いずれ終わることでもないのじゃから」



　何かを相談したわけでもないのに、ロザリンドは持ち前の洞察力で、こちらの抱える悩みや懊悩を見抜いて、まるで小馬鹿にするみたいに嘲笑う。

　真剣な悩みに対して、あんまりな態度には違いない。なのに怒る気がしないのは、彼女の見てくれに絆されるのと、彼女の本心が言葉ほど尖ったものではないのだと、その行動と接し方が、如実にこちらに伝えてくるからだ。



「それにしても、進歩らしい進歩がないのじゃな、貴様は。いつになったら、剣奴孤島で語り草になったと聞く、伝説の『スパルカ』を再現してくれるのじゃ？」



「できてたまるか、ぁんなこと」



「安心するのじゃ。心配せずとも、余とてギルティラウのような冗談の通じぬケダモノとぶつけるつもりはない。『金剛姫』か『雲龍』にやらせる。どうじゃ？」



「どぅじゃもなにも、ばかじゃん？」



「余を捕まえて愚物じゃと？　不敬じゃな、不敬じゃぞ」



　くつくつと笑い、隙のある姿を見せていくロザリンドは、スバルたちの下に、かつての伝説の話を聞くという名分で、羽を伸ばしているようにも見えた。

　ロザリンドの優秀さ、それがおそらく、年齢分を差っ引けばアベルにも見劣りしないものなのは察しがつくが、アベルが統治していた時代よりも三倍近い大きさとなった統一帝国を仕切るには、並々ならない労苦があることだろう。

　甘えるつもりはないが、ニコラやルーメラがスバルを急かそうとしない分、ロザリンドの厳しい言いようには、尻を叩かれる効果もあって、背筋が正される。

　もっとも――、



「誤算。そっちが話せば、閣下はわたしにはもう聞いてこないと思った」



「なのに、知れば知るほど興味が増しているみたいっちゃ。アラキアが嫌がる顔を見るのも閣下の趣味っちゃから、振り回されてるようっちゃ」



「……マデリンも、助けてくれない」



「竜を意のままにしようなんて、図に乗るんじゃないっちゃ、ニンゲン」



　そのロザリンドの態度に、しっかりと割を食っているアラキアからすると、スバルや、それを助長するマデリンの姿勢は歓迎できたものではないらしい。

　正直、四百年経っても、死後のセシルスのことをしっかり消化できていないアラキア側の問題だとスバルは思うが、マデリン共々、からかい材料に残しておくのみだ。



　ともあれ――、



「――スバル、今日もお疲れ様だったかしら」



　来客のある日もない日も、その締めくくりは必ず、親愛なるベアトリスと迎える。

　焦れる気持ちを強く持つスバルと相対しながら、それ以上のもどかしさがあるかもしれない立場なのに、ベアトリスは決してそんな様子を見せない。

　それが、ベアトリスの優しさゆえなのだと、そう思うけれど。



「考えすぎなのよ。焦ってもいい結果は得られないって、ベティーはちゃんと知ってるだけかしら。これでも、八百歳の大人なのよ」



「ちょう、おとしより……」



「い、言うに事欠いてかしら！　急かしたりしないけど、無礼に怒りはするのよ！　それに、もしもスバルが挫けたら、ちゃんと叱るかしら」



「くじけ、たら」



「なのよ。――それ以外で、ベティーがスバルを引っ叩くことなんてないかしら。最初に目が覚めたとき、言ったのよ。覚えてるかしら？」



「――――」



「何がどうなっていようと、ベティーたちなら乗り切れるのよ、スバル」



　そう、そうだった。そう言ってくれたのだ。

　そして、それを本当にしなくてはならないと、それがスバルの原動力となる。



　日々は過ぎてゆく。大過なく。だがそれを、漫然と受け入れてはいけない。

　惜しむほどに時は貴重で、一日も、一時も、一秒だって、無駄にはできない。

　それが――、





　　　　　　　　　　　　　　　　△▼△▼△▼△







　――神様、仏様、オド・ラグナ様。生涯、失敗を嘆かないと誓います。







　　　　　　　　　　　　　　　　△▼△▼△▼△





　――それがナツキ・スバルの歩みに立ちはだかったのは、何の変哲もない、代わり映えしない一日の一端、つまり前触れのない凶事だった。



「――我輩は思い、思うのだ。常々思う」



　その大柄な男は、唐突にスバルとベアトリスの日常に割り込んできた。

　壮麗な黒い装いに、白いコートを肩から掛けた格好。明るい黄緑の髪は丁寧に撫で付けられ、浅黒い地肌とのコントラストがありあり存在を浮かび上がらせる。

　厳つくも整った容姿には、野性じみた気品という矛盾した気質が宿っていて、一目見れば忘れることのできない存在感を直接脳に刻み込んでくる、魂の色濃さがあった。



　それ故に、間違いなく初見の相手だ。

　ルーメラのときと違い、知った相手が時を経て異なる容姿に変化したわけではない。その招かれざる男は、突如として夕餉の席に現れていた。



　折しも、その日はニコラとルーメラ、それにアラキアが食卓に揃っていた。

　示し合わせたわけではなく、いつもより賑やかな食事の席に、スバルもリハビリの成果を見せたいと意気込んでいた矢先だった。



「経験上、怒りというものは六秒ほどしか持続しない。たったの六秒だ。その六秒をやり過ごせば、怒りの発露という原始的な感情の爆発、その最大化は免れる」



　家の中に踏み込んでくる男の存在に、スバルは呆気に取られる。しかし、そのスバルを余所に、それ以外の面々は一瞬で顔色を変え、警戒に椅子を蹴って立ち上がった。

　とりわけ早く動いたのは、この場で最大の――否、世界全土を見渡しても、最高クラスの制圧力を有したアラキアだった。



　ヴォラキアでの『大災』の最中、四大の一角である『石塊』ムスペルの一部を取り込んだことで、『精霊喰らい』アラキアは常軌を逸した力を手に入れた。

　時を経て、その力をさらに我が物とした彼女は『金剛姫』と呼ばれ、現代の皇帝であるロザリンド・ヴォラキアの懐刀として、遺憾なく力を発揮している。



「つまり、だ」



　そのアラキアの全身から、キラキラと煌めく光帯が幾本も伸び、触れたものを容赦なく切り裂く最高硬度の刃となって、食卓を荒々しく迸る。

　十二本の光帯、それが狙ったのは、堂々と立ち尽くす褐色の大男。その男の左の顔面を、梵字風のタトゥーが淡く光り――、



「――我輩の怒りを最大限相手に味わわせるためには、六秒以内にケリを付ける必要があるということだ」



　瞬間、男を中心に荒れ狂った光の暴発が、男を切り刻むはずだった光帯を真正面から薙ぎ払い、その繰り手であったアラキアを二十八の塊に分断――その斬光の余波が爆発的に広がり、左右にいたニコラとルーメラが消し飛んだ。

　そして――、



「六秒ちょうどだ」



　顔色一つ変えずに言い切る男、その両手にはいつの間にか双剣――持ち手の部分から先が光の刀身となった、奇妙な二振りの剣が握られている。

　それがアラキアを、その余波でニコラとルーメラを瞬殺――そして、巻き起こった剣風の巻き添えに、スバルをも瀕死に追いやった剣舞の正体だ。



「――ぁ」



　地べたに仰向けに倒れ、用意されていた夕餉の残骸を浴びたスバルが呻く。

　痛みはない。皮肉にも、リハビリの不完全なスバルの体は、ただ動かしづらいだけでなく、痛覚を含めた五感の配線もめちゃくちゃで、肉体を襲った突然の悲劇も、いっそ画面の向こうの出来事のように実感が得られなかった。

　だが――、



「……お前、何者なのよ」



「――。驚いたな。驚いて、驚いたぞ。生き残ったのか」



　自分の体を襲った痛みは他人事のように思えても、スバルを庇うように、その両手を広げて立ったベアトリスの健気さには無関心になれなかった。

　衝撃波が押し寄せる寸前、とっさに自分とスバルとを守ったベアトリス。彼女は、自分の手がニコラたちに及ばなかったことを悔やみつつ、それを一瞬で噛み殺し、下手人である男をキッと睨んだ。

　その瞳には、確かな怒りと、わずかな困惑がある。――困惑の理由、それは。



「人間……？　それとも、精霊かしら……？」



「どちらでもあり、どちらでもない。我輩は我輩だ。そして――」



「ぇあ、とりす……ッ」



　血を吐くような覚悟の絶叫は、掠れ声で大した牽制にもならなかった。ただ、ベアトリスの小さな体に、不相応な覚悟を固めさせ、無謀に挑ませただけだ。

　その結果は、言うまでもなく見るも無残なもので。



「――精霊という汚穢は消す。六秒だ」



　その残酷な宣告を最後に、六秒もたずしてベアトリスは、そしてナツキ・スバルは、まとめてこの世界から消滅させられる。

　四百年の時を隔て、多くのものが希望を繋いだ結果、はるか未来にサルベージされた精霊と契約者、その二人の最期としてあまりにも悲痛な決着。

　そしてそれは――、





　　　　　　　　　　　　　　　　×　　×　　×





「――我輩は思い、思うのだ。常々思う」



　意識が晴れた瞬間、夕餉に乱入者のあったその場に立ち返ったナツキ・スバルの、四百年後における戦い――『狂皇子』ヴェイグ・アドガルドとの、絶望的で、勝ち目の見えない泥沼の攻防戦の始まりを意味するのだった。





　　　　　　　　　　　　　　　　△▼△▼△▼△







　――神様、仏様、オド・ラグナ様。生涯、誰にも理解を求めないと誓います。







　　　　　　　　　　　　　　　　△▼△▼△▼△





　――『狂皇子』ヴェイグ・アドガルド。



　それは、『剣聖』ラインハルト・ヴァン・アストレアや、『青き雷光』セシルス・セグムント、『礼賛者』ハリベルと肩を並べた四大国最強存在の一人。――それはあくまで、スバルたちが過ごした四百年前の話、という但し書きが付く。



　ルグニカ王国の『剣聖』、ヴォラキア帝国の『青き雷光』、カララギ都市国家の『礼賛者』とくれば、グステコ聖王国の『狂皇子』とくるのがお約束だが、その圧倒的なネームバリューに対し、当人の情報は驚くほど少ない。

　聖王国、その王族の一員でありながら、自身と同じ立場の血族十数人をその手にかけ、数千の軍勢が七日七晩かけてようやく制圧、幽閉したというエピソードが有名――というより、それ以外に出回った風聞がないとすらされた存在。

　そのあまりに荒唐無稽な噂から、『狂皇子』の存在自体が、他国の最強を牽制するための聖王国のパフォーマンスではないかと疑われていたとも聞く。



　しかし、その疑惑は疑惑に過ぎなかった。

『狂皇子』は実在した。その実力も、噂に違わぬ圧倒的強者のものであり、肩を並べたとされる三人の最強をいずれも知る立場からも、彼らに匹敵すると断言できる。

　そして彼らと違い、『狂皇子』だけは、四百年後の現在にも生き延びていた。

　そのカラクリは――、



「――にんげんと、せいれいの、はーふ？」



「公然の秘密というヤツです。彼が、世界で唯一の『精霊人』だという話は」



　苦いものを噛み潰したようなニコラの言葉に、スバルは思わず息を呑む。

　人間と精霊のハーフ――そうした存在が誕生可能であるという点に驚いたのと、他ならぬその『精霊人』が、精霊を付け狙っているという理解できない事実に。



　確かに世界には、ベアトリスやルーメラのように、人と遜色のない姿かたちをした精霊が存在する。だが、体をマナで作られた彼女らのマナ体は、その仕組みの根本から人間と違うものであり、子どもを作ることなど不可能に思われた。

　しかし――、



「事実として、彼は存在しています。自分のルーツの一端を担っている、精霊を滅ぼし尽くすと公言してやまない、世界最大の災害として」



　そのニコラからの確定情報が、ナツキ・スバルに思い知らせる。

　これまで、あらゆる難敵とぶつかり、そのたびに悪戦苦闘を強いられてきたスバル。それでも、本当にやり合う以外になかった存在は、魔女教というネジの外れたものたちを除けば、トッド・ファングやエルザ・グランヒルテといった例外しかいなかった。

　そのトッドやエルザとすら、やり方と目的次第では共闘可能だったのではないか、とスバルは思うことがある。――その目が、この相手にはない。



　スバルの愛するものの多くは、精霊との関係が不可分だ。――すなわち、『狂皇子』ヴェイグ・アドガルドは、絶対にナツキ・スバルと相容れない。

　精霊を殺す存在と、スバルが並んで歩くことなど絶対にできないのだから。



「――六秒だ」



　何より、『狂皇子』の振るう刃は、精霊を殺すためであるなら周囲の巻き添えを一切厭わない。故に、スバルはまた殺される。



　一回、二回、十回、二十回。――カウントは、無情に重ねられていく。

　まだ、この四百年後の時代で一度も試せていなかった『死に戻り』、それが発動したことは僥倖と言えた。そのリスタート地点が、四百年前に設定されていなかった失意と落胆を抜きにしても、僥倖と言えた。

　ただ、それは大きな問題を残している。

　それは――、





　　　　　　　　　　　　　　　　×　　×　　×





「――我輩は思い、思うのだ。常々思う」



　また始まる、『狂皇子』による暴虐の寸前、そこに立ち返るナツキ・スバルは、いまだリハビリの不完全な、誰かの手を借りずに立つこともできない状況ということ。



「――六秒だ」



　そして、何もできないまま、無力なスバルの世界がまた斬光に切り裂かれた。





　　　　　　　　　　　　　　　　△▼△▼△▼△





　――ナツキ・スバルが味わった『死に戻り』の螺旋の中でも、この『狂皇子』の強襲は、およそ最悪に分類されるべき苦難だった。



　並べるならば、魔都カオスフレームでのオルバルト・ダンクルケンとの鬼ごっこか、あるいは剣奴孤島ギヌンハイブでの『スパルカ』含めた一連が匹敵するかもしれない。

　しかし、体が縮んでいたとはいえ、それでも手足が自由に動き、状況打破のためにあれこれと自分から確かめられたあれらの障害は、今と比べれば天国に思える。



　なにせ、数ヶ月のリハビリ生活を経た今も、ナツキ・スバルの体の不自由にはほとんど改善が見られず、自力での歩行もままならない状況なのだ。

　そこに、スバルがこれまで遭遇した敵の中で、初代『剣聖』であるレイド・アストレアくらい馬鹿げた力の持ち主が相手とあれば、生き残る目は針の穴よりなお小さい。



　故に、スバルは死に続けた。

　アラキアも、ニコラも、ルーメラも救えず、ベアトリスを逃がすことさえできずに、むしろ彼女らの逃げ道を不自由な体で塞ぐ形で、死なせ続け、死に続けた。



「本当に、焦げ付くくらい鬱陶しい方ですかしら！　わたくしたちを目の敵に……あなたのせいで、ユークリウス領は散々でございますことよ！」



　当然だが、六人の大精霊が治めるユークリウス領など、精霊の絶滅を目論む『狂皇子』からすれば、あってはならない土地の最先鋒だ。

　これまでにも幾度も衝突があったのか、現れた『狂皇子』に対するルーメラの感情は、怯えと怒りとが等分に混ぜ込まれたものだった。



「それ、セシルスが欲しがってた剣。奪って、墓標の前で折る」



『狂皇子』が両手に持った双剣、光の刀身を宿したそれが、『龍剣』や『陽剣』に並ぶ世界有数の魔剣――『呪剣』アイオーンであると、アラキアの観測が明らかにする。

　所有者のマナを吸い上げ、それに応じた切れ味を発揮するとされる『呪剣』の剣風は、『金剛姫』と呼ばれるアラキアの防御さえ容易く突破するものだ。

　荒れ狂うそれから身を守る術は、現状のスバルたちには多く取れない。



「マズいマズいマズい！　油断しましたって言うと僕らに落ち度があるみたいですがこれって予想できない災害すぎませんか！？　ここまで前触れなしに世界最恐と出くわすことになったら、備えだって全然間に合いませんよねえ！？」



　この場で、身動きのできないスバルに続いて戦闘力のないニコラが、突発的な会敵に顔面を蒼白にしながら必死に叫ぶ。

　どうやらオットーと違い、ニコラの方は本格的に商人らしい商人のようで、鉄火場にたじろがないほど度胸は据わっていないらしい。もっとも、オットーよりも年少の彼にそれを期待するのは酷な話だし、味方の邪魔をしないだけで十分偉い。

　そして何より――、



「スバルは、ベティーが守るのよ。――ベティーしか、もういないかしら」



　何度『狂皇子』の振るう刃に命を絶たれようと、必ずスバルの命運が尽きるその前に立ちふさがり、小さな体でスバルを庇うベアトリスがいる。

　その彼女の変わらぬ献身が、何度でもスバルの心を奮い立たせるから――、



「――六秒だ」



　繰り返される『死』の螺旋にも、スバルの心は折れ曲がらない。

　一度折れたら、もう立ち上がれない。だから、折れることこそが一番怖い。そうならないために、スバルは――、





「いいぇむてい！」

「――Ｅ・Ｍ・Ｔ！」



　決死のスバルの表情に呼応し、反応したベアトリスがＥ・Ｍ・Ｔを発動――絶対無効化魔法のフィールドが拡大、食卓を囲んだスバルたちを丸ごと包む。

　このフィールドの中では、マナと関連したあらゆる効果が無効化される。それは、『精霊喰らい』であるアラキアや、大精霊であるルーメラも同じ。それだけに、これだけで終わったら単なる利敵行為だが――、



「――まほぅけん、だろ！？」



『呪剣』アイオーンの刀身がほつれ、光がＥ・Ｍ・Ｔのフィールド内に拡散する。

　それは狙い違わず、『狂皇子』の有する魔剣の効果を断ち切り、これまで数十回にわたってスバルたちを切り刻んだ死因を初めて遠ざけるのに成功した。



「妙な魔法で、妙な効果だ。想定の外だな」



　Ｅ・Ｍ・Ｔに初撃を妨害され、『狂皇子』が初めて攻撃性以外の発言をする。その『狂皇子』の横っ面に、放たれたアラキアの蹴りが猛然とぶち込まれた。



「死んで」



『精霊喰らい』であるアラキアは、その内に取り込んだ精霊の力をＥ・Ｍ・Ｔによって封じられている。が、それを抜きにしても、彼女の身体能力は世界有数のものだ。

　渾身の蹴りの威力は砲弾じみたもので、実際、衝突音と広がった衝撃波は、鍛えた戦士の首をも一撃でへし折る火力を秘めていた。

　ただし――、



「生憎と、我輩が貴君の要請に応じる理由はなく、故に応じん」



　相対する『狂皇子』もまた、アラキアと同等かそれ以上の怪物だ。

『狂皇子』は柄部分だけの魔剣を握った手で、アラキアの蹴りを軽々受け止めている。男と女、手と足、攻と防、様々な対比の条件を、力ずくで押しのける。

　だがしかし、『狂皇子』の相手をするのは、アラキアだけではない。



「こちらもいますですかしら！」



　そう声高に叫びながら、『狂皇子』を後ろから椅子で殴りつけたのはルーメラだ。

　早々に魔法の使用を断念した大精霊は、アラキアが気を引く隙に『狂皇子』の背後に回り込むと、その長身からの容赦ない振り下ろしを叩き込んだ。

　破砕音を立てて木製の椅子が砕け、後頭部を無防備に殴られた『狂皇子』の姿勢が前のめりに揺らぐ。効いた、とわずかな期待が首をもたげ――、



「マナの構成に干渉したか。大したもので、大したものだ。だが――」



　瞬間、踏みとどまった『狂皇子』の体内から次々と飛び出した光刃が、アラキアの両腕を左足を、ルーメラの胴体を、それぞれ薙ぎ払い、斬り飛ばしていた。



「な……」



「――『適応の加護』」



　存在を構成するマナを漏出し、吹き飛ばされるアラキアたちを目の当たりにして、息を呑んだスバルに『狂皇子』の目が向く。

　即座に、スバルたちを危険とみなした『狂皇子』は、全てを無効化されるはずのフィールド内で『呪剣』を起動、その光刃が袈裟斬りに放たれ、



「――Ｅ・Ｍ・Ｍ！」



　刹那、ベアトリスによる魔法の切り替えが、寸前でスバルの命を死から遠ざけた。



「――――」



　動けなくなる代わりに、半歩ズレた世界のスバルたちに攻撃は届かなくなる。だが、攻撃する手段がないわけではない。



「ぃんぷろぉ！」



　不可視の黒い魔手がスバルの胸のうちから現れ、それが『狂皇子』の鼻面に迫る。その顔面を殴り抜いて、不意を打ったところにベアトリスの陰魔法を叩き込む。

　最悪、スバルがマナ不足で昏倒したとしても構わない。『狂皇子』を、アル・シャマクの別次元に飛ばすくらいのことを。



「露骨な視線誘導だ。罠か？　罠でないなら、未熟だ」



　その不可視の拳撃を、首を傾けるだけで『狂皇子』は容易く躱した。

　Ｅ・Ｍ・Ｔは対応され、Ｅ・Ｍ・Ｍの防御も長くはもたない。何より、Ｅ・Ｍ・Ｍで守れるのはスバルたちだけで、周りの仲間は無防備なままだ。

　アラキアもルーメラも、すぐにでも手当てがいる。当然、ニコラも――、



「――――」



　ニコラの、反応がない。

　戦闘要員ではない彼は、スバルやアラキアたちの邪魔にならないよう下がったはずで。



「正直、あんまり突然だったもので、この備えが使える確信はありませんでしたが」



　そうスバルが意識した直後、壁際に下がっていたニコラが右手を掲げる。そして、その指が強く弾かれ、高い音が奏でられた。

　それはニコラと同じ特徴を持った先祖が、抜け目なく何かを仕込んでいたとき、それを発動する切っ掛けとして好んでいた仕草だ。

　そしてその癖と抜け目のなさは、子孫にもしっかり受け継がれていたらしく――、



「――って、何にも起きやしないのよ！？」



　スバルと同じ期待を抱いたはずのベアトリスが、その変化のなさに目を剥く。

　あわや不発か、とスバルの背中を焦燥感が駆け上がるが、しかし、指を鳴らしたニコラの表情に悲愴さはない。あるのは、イチかバチかの賭けに出た勝負師の眼光。

　それを正面に、『呪剣』を手にした『狂皇子』は目を細め――、



「――おかしいな。わたし、氷河に手出ししないでって言ってあったはずだよね？」



　声がした。――刹那、四方八方から押し寄せた無数の白光が、ニコラの用意したセーフハウスを外側から刺し貫き、凶悪な光の乱舞が室内を蹂躙する。



「――――」



　何が、起きたのかわからずに、スバルは凝然と、目の前の光景に目を見張る。

　一瞬のうちに、ニコラに与えられたスバルたちの仮宿が崩壊、光によって消し飛ばされた跡地は、濛々と白い粉塵が立ち込める惨状と化していた。

　目前に迫った『狂皇子』の姿はなく、光の爆発が吹き飛ばしたと頭の片隅が思う。とっさにスバルの胸に飛びついていたベアトリスも、その大きな瞳を丸くしながら、突然の事態に驚いた顔でこちらを見やり、「ぁ」と息を呑む。



「す、スバル、足が……」



「あ、し？」



　震えるベアトリスの声に、スバルは苦労しながら自分の体を見下ろす。その言葉の嫌な予感から、足の一本でも吹き飛んでいる悪寒があったが、発動し続けていたＥ・Ｍ・Ｍの効果がある限り、どんな厄災もスバルたちを傷付けられない。――代わりに、存在のズレたスバルたちの実像を、光が、貫通していた。



「これ、って……」



　瞬きをするスバルの眼下、残像を貫くような形で突き立った光――ほつれるように帯びた煌めきの剥がれるそれは、一本の長い針だった。

　スバルの肘から指先まで程の長さの針、マナで形作られたそれは目的を果たした途端に散り散りにほどけ、消えてなくなる。――それに、見覚えがあった。

　たぶん、これと同じ光に、幾度も命を奪われたことがある。

　でも、それはもう、望んでも起こらないはずの――、



「――貴君か」



　呆気に取られるスバルの鼓膜を、感情を押し殺した低い声が揺すぶった。

　ハッと目を向けたスバルとベアトリス、濛々とした噴煙の向こう、じわりと視界を浸蝕したのは、恐るべき男の顔面に入った淡く光るタトゥーだ。

　あの光爆の中心にいながら、『狂皇子』には一筋の掠り傷すら見当たらなかった。

　しかし、これまで百に迫る『死に戻り』を繰り返した中で、一度もその表情を崩さなかった『狂皇子』の横顔に、スバルは初めて、警戒の色が宿るのを見た。

　そして、『狂皇子』の警戒の矛先が向いていたのは――、



「また弱いものイジメしてるの？　飽きないね、『狂皇子』さん」



　いくつもの色を織り込んだドレス姿の、美しい『魔女』がそこにいた。



「――――」



『魔女』。そう、『魔女』だ。

　一目で、それ以外の何者でもないと、ナツキ・スバルは――否、生きとし生ける全てのものが、本能の警鐘によってそれを理解させられる。



　山のように大きな怪物を見れば、血に飢えたケダモノの生臭い息を嗅げば、獲物を定めた龍の咆哮を聞けば、それが命を脅かす脅威だと誰もが本能的に察する。

　それと同じ機能が、言っている。――あれは『魔女』だと。



「心外で、心外だな。我輩の行いを、そうも矮小化されては心外だ」



　時計で十二時の方向に『狂皇子』、三時の方向に『魔女』――両者を視界の端と端にそれぞれ収めながら、スバルは込み上げてくる震えを堪えられない。

　あるいはこれは、今の世における最も恐ろしいものたちの邂逅なのだろう。



　だが、しかし、それ以上の、意味が、スバルには、ある。



「……スバル」



　違う。今、スバルを呼んだベアトリスにも。――スバルたちには、ある。

　何故なら、そこに現れた美しい『魔女』は――、



「――六秒だっけ？　『狂皇子』さんの拘りって」



「――――」



「じゃあね――」



　軽く小首を傾げ、暗く湿度の高い眼差しをした『魔女』の唇が美しい声音を紡ぐ。それが言い切られる前に、『狂皇子』が動いた。

『魔女』との間にあった距離が消滅し、『狂皇子』の刃がその細い首を左右から薙ぎ払わんと――刹那、『狂皇子』を双剣が、降り注ぐ光の雨に止められる。



　光の雨が生んだ衝撃波と爆音が、戦闘モードだった『狂皇子』を容赦なく捉える。それを『狂皇子』は双剣で打ち払い、身を守る、守る、守る。

　しかし、そこに生じた時間は、『魔女』を相手に痛恨の刹那だった。



「百万倍にしてあげる。――『コンプレス・アゴニー』」



　そう言って、『魔女』がパチンと指を鳴らした。――次の瞬間、双剣を操る『狂皇子』の動きが精彩を欠いた。正確無比の剣舞、そこに生じた乱れを縫い、降り注ぐ光の嵐が防御を掻い潜って、男の体に次々と突き刺さる。

　しかも、そこで終わらない。光は深々と『狂皇子』の体を抉り、その傷の最も深いところで爆裂、世界最強の一角を、内側からバラバラに吹き飛ばした。



「――――」



　その、圧倒的な力の衝突と、一瞬の結末に、唖然とさせられる。

　光爆による視界の圧迫が晴れたとき、そこには『狂皇子』の姿は破片もなかった。あの恐るべき実力者を、『魔女』は一人で瞬く間に屠った。――否、一人ではない。



「おつかれ、紅蠍ちゃん」



　アンニュイな吐息をこぼした『魔女』、その傍らにゆっくりと進み出てくるのは、地竜かそれ以上に大きな、赤々とした甲殻を纏った巨大なサソリ――魔獣だ。

『魔女』が引き連れた魔獣、それがあの圧倒的な光の制圧力を発揮した正体。

　そして、その組み合わせの背景には――、



「……ねえ、まだやる？」



「――いいや、口惜しく、口惜しいが、認めよう。口惜しいことに、我輩の負けだ」



「――っ」



　ゾッと、駆け上がる怖気に背筋をなぞられ、スバルは声の方に意識を向けた。光の雨が降り注いだ爆心地、そこから十メートルほど離れた地点、そこで靄が揺らめいて――否、違う、揺らめいているのは靄ではない、霞のように薄い、人の像。

　極限までその存在の薄らいだ、『狂皇子』が靄のようになってそこにいた。



「肉体と、マナ体を切り替えて……そんなの、不可能かしら……」



「可能か不可能を論じるなら、我輩のこの姿が論より証拠だ。腹立たしくも腹立たしいが、言うべきは不可能ではなく、不可解だろうな。腹立たしいことに」



　思わず、そう呟いたベアトリスに、『狂皇子』は自分の体のことなのに、まるで他人事のような無関心さ――あるいは、虚無感さえ交えてそう答えた。

　それきりベアトリスが口を閉ざすと、存在の希薄な『狂皇子』は『魔女』を見やり、



「貴君がこの場にいるなら、絶氷河は手薄か」



「かもね。でも無理だよ。わたしが何にも対策しないで離れるわけないでしょ？　みんな、わたしよりバカなんだから」



「――――」



「企んでもダーメ。わたしとあなたたちとじゃ、悩める時間が違うもん。それとも――今度は六千万秒にする？」



「そのお遊びに、貴君は何を支払う気だ？」



「さあ？　それ、あなたに関係ある？」



　じりじりと、『狂皇子』と『魔女』との間で静かな一触即発の気配が高まる。どちらも感情を抑制して見えるが、互いを邪魔だと感じているのは明白だ。

　その戦意の昂りを感じ取り、紅蠍と呼ばれた魔獣が両手の鋏を擦り合わせる。今しばらくの間、その睨み合いは続いたが――、



「――不自然な汚穢は、我輩の手で全て消し去る。覚えて、忘れるな」



「ならまず自分から消したら？」



「それはまだ早く、早い。――まだな」



　その宣告は『魔女』か、あるいは彼が言うところの汚穢と寄り添い合ったスバルに言ったものか、『狂皇子』の存在が薄れ、その場から掻き消える。

　消えたふり、ではなく消えた。脅威は去った。ただし、別の脅威を残して。



「あんな人だけ残って、もうやんなっちゃう」



　消えた『狂皇子』の存在に小さく吐息し、『魔女』が剥き出しになった白く細い肩をすくめる。それから彼女は傍らの魔獣の甲殻を撫でると、くるっと振り向いた。

　その動きに合わせ、長く伸びた赤みがかった明るい茶髪と、それをまとめた大きなリボンが風に揺れる。そのまま、『魔女』はスタスタと歩き出し、スバルとベアトリスの方へやってくると――その横を素通りし、後ろに向かった。

　慌ててその後ろ姿を目で追い、気付く。スバルたちの後ろに、ボロボロになったアラキアとルーメラ、そして二人に庇われるニコラの姿があったことに。



　あの、家を吹き飛ばした光爆にあって、三人とも生きていた。直前でＥ・Ｍ・Ｔが切れたことで、魔法を使えるようになったアラキアたちがうまくやったのだ。

　ただし、無傷ではなかった。とりわけ重傷なのは――、



「うちに何かしたのって、あなた？」



「――ッ。さあ、何のことでしょう……」



「はぁ、意味のない駆け引きって疲れちゃう。あのね、魔紋は人それぞれ固有だから、注意深く調べたら誰が何を仕掛けたかちゃんとわかるの。わたしには調べる時間がいくらでもある。だからやったのはあなた。それは、その報い」



　そう言った『魔女』の白い指が、地べたに足を投げ出したニコラ――その、膝から下をなくした左足を示していた。



「――――」



「痛い？　じゃあ、もうやめてよね。都合よく使われるの、不愉快だから」



　だくだくと血を流し、脂汗を浮かべたニコラにそう告げると、『魔女』は自分を睨んでいるアラキアたちを尻目に、その髪を撫で付けて背を向ける。

　そのままニコラたちに、スバルたちにも声をかけず、立ち去ろうとする『魔女』――それを思わず、スバルは呼び止めていた。

　そのために、呼びかける言葉は――、



「――■■■」



　と、そう呼んだはずの言葉が、何故かうまく言葉にならない。



「あ？」



「――――」



　発したはずの声が声にならなくて、スバルは自分の喉を疑った。だが、そこに異常は感じられない。強いて言うなら、ずっと不自由の続くもどかしい喉のまま。

　発音を、した。『魔女』を、呼んだ。――知っているはずの、『魔女』の名前を。



「■■■……■■■！　なんで……■■■！」



「……あなた」



　振り向く『魔女』が、初めて正面からスバルを見据えた。

　その薄い青緑の瞳が、ぼんやりとスバルを映して像を結ぶ。そこに、ポジティブな感情が芽生えることを期待して、スバルは続く言葉を待った。

　もどかしく、喉の奥でうまく形にならない、それを転がしながら――、



「――どうしてそんなに必死な顔？　変なの」



　しかし、『魔女』は期待した反応を見せることなく、世界を退屈そうに眺める眼はそのままに、それだけ言い残して歩みを再開しようとする。

　その、遠ざかろうとする背中を、そのままいかせたくなくて。



「ま、まて、■■■……がっ」



「スバル！」



　伸ばそうとした手は伸びず、動こうとした足は動かず、どちらも不十分になったスバルの体は、みっともなく無様にその場に倒れ込んだ。そのスバルの哀れな姿に、ベアトリスが悲鳴のような声を上げ、すぐ傍にしゃがみ込む。



「■■■……おれ、は」



　そのベアトリスの支えに、今は全く意識を割けない。

　今だけは、目の前の、この遠ざかろうとする『魔女』が優先だった。だって、ここで彼女をいかせてしまったら、もう会えなかったとしたら、それは。

　だから、たったの一秒でもいいから、目の前の『魔女』を、■■■を――。



「ねえ、そんなに一秒が大事？」



　ふと、そのスバルの必死さが興味を引いたのか、すぐ目の前に■■■がしゃがんで、こちらの顔を覗き込んでいた。畳んだ膝の上に肘を立て、そこに小さな顔を乗せた『魔女』は、「だったら」とわずかに首を傾げる。

　それを見たベアトリスが血相を変え、



「や、やめるかしら！　■■■……！」



「百万倍にしてあげる。――『コンプレス・アゴニー』」



　そう、『魔女』が歌うように口ずさんだ直後、スバルの意識が闇に包まれる。

　だが、最初はなんだかわからなかったそれを、スバルはゆっくり、時間をかけて紐解いていくことになった。

　なにせ――、



「――ぁ」



　――百万秒の空白が、■■■の手でスバルにもたらされたのだから。





　　　　　　　　　　　　　　　　△▼△▼△▼△







　――神様、仏様、オド・ラグナ様。生涯、何かの成功を喜ばないと誓います。







　　　　　　　　　　　　　　　　△▼△▼△▼△





　――『憂鬱の魔女』■■■・■■■。



　それが、突如として現れた『狂皇子』ヴェイグ・アドガルドを退けるための、ニコラが利用した切り札であり、全員が生き延びるために縋った蜘蛛の糸だった。



「足の一本で済んだのは僥倖でしたよ。幸い、今はナツキさんたちの時代よりも、魔具の方も進歩していますから……義足も、そこまで不便じゃありません」



　と、左足の膝下を代償に失い、スバルたちを救ったニコラがそう気丈に笑う。

　無論、まだ若い彼の足の欠損を、言葉通りに大丈夫などとは笑えない。ニコラはその周到さと機転、そして健常という未来と引き換えに、全員を救ったのだ。

　それに深く感謝すると同時に、スバルは確かめずにはおれない。



「あの、キョウオウジとやりあってたのが……」



「ええ、『憂鬱の魔女』です。あの通り、全方位に危険をばら撒く災いそのものなんですが、一個だけ、客観的事実から信用できることがあります」



「それは……」



「あの『魔女』は人殺しはしない。だから、報復も僕の足一本。色んな理由で、『憂鬱の魔女』の縄張りに手出しした人間がいますが、直接彼女の手にかかったって人の話は聞いたことがない。その後の対処をマズって死んだ人はいますが、そこまでいくと自己責任の範疇になってきますね」



　それは、『魔女』の人柄や性格を当てにしたものではなく、あくまで客観的なデータから導き出した推測と、それを根拠にするところがニコラらしい。

　実際、そのニコラの予測は的中し、『憂鬱の魔女』は誰の命も奪わなかった。

　奪われたのはニコラの足と、『憂鬱』の権能を浴びたスバルの二週間――昏倒したまま意識の戻らなかった、それだけの日数くらいのものだった。



「聞かせるかしら、ニコラ。どうやって、お前は■■■……『憂鬱の魔女』を、あの場に呼び出したのよ」



「前にもお話しましたが、『憂鬱の魔女』はアグザッド絶氷河を縄張りにしています。彼女は基本的に外の出来事に干渉してきませんが、縄張りに手出しされたときに限り、これを絶対に許しません。相手を特定して、必ず報復する」



「……つまり、あえて縄張りに手出しして、『魔女』を誘き出したのかしら？」



「まぁ、そういうことです。遠隔起動する術式を用意して、それで縄張りにちょっかいかける仕組みでした。……これ、緊急時の対処法として情報売れませんかね？」



「その商魂のたくましさには感心するけど、『魔女』にきてもらってまで何とかしなくちゃいけない状況なんて、そうそうないと思うかしら」



「ですよね。あれも、『狂皇子』対策ってのが本音でしたし」



　転んでもただでは起きない、という格言を実証したがったニコラだが、さすがに分が悪いと思ったのか、すごすごとその企画書を引っ込める。

　と、最後に付け加えた一言が、スバルの意識を強く引いた。



「わかってた、のか？　あのヤロウが、くるの」



「――。いずれ、あるかなと思っていました。こんなに早く嗅ぎつけられると思っていなかったので、お伝えしていなかったのは僕の手落ちです」



「ておち……」



「おわかりだと思いますが、『狂皇子』……ヴェイグ・アドガルドは、極度の精霊嫌いです。精霊を憎悪していると言っていい。彼はグステコ聖王国の慈母とさえ言われた『霊獣』オドグラスの抹殺を皮切りに、世界中の精霊を殺し尽くしている」



「オドグラス……にーちゃと同じ、四大なのよ。それを殺すなんて……」



「『霊獣』に限りませんよ。カララギの『通り魔』も殺され、『石塊』を内包するアラキアさんも狙われ続けています。大精霊である、ルーメラさんの姉妹も――」



「え？」



　その『狂皇子』の凶行が並べ立てられる中、不意にニコラが口走った内容に、スバルとベアトリスの目が大きく見開かれる。その反応に、ニコラが自分の口に手を当て、失言に気付いた顔で瞑目した。

　そのまま、彼は「すみません」と言葉を継ぐと、



「今の、聞かなかったことにしてくれませんか。ナツキさんたちには話さないって、ルーメラさんと約束していまして」



「……そんなの、むりだ」



「その言い方だと、ベティーたちには聞く義務があるかしら。ルーメラの姉妹……ルーメラ以外の五人は、まさか」



「――。『狂皇子』の手にかかり、すでに亡くなりました。全員、それを覚悟の上で、ナツキさんたちの救出に臨んだんです」



「――――」



　言わずにおこうと、それもスバルたちには聞かせまいと、そう口裏を合わせていた秘密だ。当然、それがスバルとベアトリスに関連したものである可能性は高かった。

　だが、具体的に彼女らの命がどう使われたのか、それは想像の外側で。



「モゴレード大噴口……あの裏側を漂泊するベティーたちを見つけるのは、簡単なことじゃないのよ。あれは莫大なマナ溜まりのようなもので、その中から小さな小さな黒球だけを拾い上げるには、時間も労力も、機会もいるかしら。そして……」



「――――」



「そして、大精霊がそんな真似をしていようものなら、アンテナを張っている奴ならすぐに目敏く気付くのよ。邪魔されないためには、目眩ましを置くしかないかしら」



「そ、そのやくめを、まさか」



「――わたくしたちにとって、それは当然の決断でしたかしら」



　組み立てられるベアトリスの推論、それが他ならぬ当事者によって裏付けられた。

　スバルたちとニコラとが話す部屋に乱入してきたルーメラ、彼女は秘密を明かしたニコラの方を、その赤い瞳でしょうがなさげに見て、



「ニコラ様ときたら、なんてお口の軽いことでございますですかしら。わたくしの姉妹たちの、最後の頼みも聞き届けてくださらないのでございますですことよ」



「……言い訳のしようもありません」



「まぁ、赤ん坊の頃から知っているニコラ様ですかしら。わたくしの姉妹たちの活躍を、どうしても話したいというのもやむなしでございますですのよ」



　落ち込んで俯いたニコラの頭を、ルーメラの手が優しく撫でる。その様子からは、二人の関係が見た目通り、年上の女性と少年とのそれに見える。

　実際、スバルたちの知らないところで、ニコラやルーメラの人生は交わり、今日という日を迎えるまでの紆余曲折があったのだ。――そこに、スバルたちを助けるため、ルーメラの姉妹たちが命を懸けるという、約束事も。



「どうして……」



　どうしてそこまでと、そう問い詰めずにはいられない。

　助けられた立場で、スバルがこんなことを思うのは悪いとわかっている。でも、こんなのはおかしい。間違っている。スバルとベアトリスを助けるために、費やされたものの大きさが、あまりに吊り合っていない。



　ニコラ以前のオットーの子孫たちや、ルーメラたちが預かっていたユークリウス領、古くはアルを殺させないために自分ごと彼を氷漬けにしたエミリアもそう。

　スバルたちのために、犠牲になったものが多すぎる。ルーメラの姉妹だけでも、そのために五人が犠牲になった。精霊ならいい、なんて都合よく考えられない。

　それに、そんなに苦労して、時間と人生を捧げて、そうまでしてスバルとベアトリスを救い出せたとしても、もうそこには――、



「みんな、いないのに」



　そんな世界に放り出されて、取り残されて、喜ぶなんて器用なことはできない。

　義務感や使命感、目をつむると押し寄せてくる無力感に抗いたくて、スバルは意味を見つけ出そうと、必死にリハビリに励んだ。――でも、心のどこかで思っていた。



「いみなんて、ない」



　動けるようになって、歩けるようになって、掴めるようになって、なんだ。



　動く？　何のために。

　歩く？　いったいどこを。

　掴む？　空っぽのこの未来で。



　もう、スバルの大事な人たちの多くと、会うことも話すこともできない、世界で。



「あいたい」



　みんなに、会いたかった。

　今すぐに、みんなに会いたかった。大事なみんなと、言葉を交わしたかった。



　それができないなら、助かった意味なんてなかった。



「スバル……」



　流れるに任せ、涙が頬を伝った。

　それを目の当たりにし、弱々しい呟きを聞いたベアトリスが、悲痛な表情で、しかしすぐにそれを覆い隠した慈しみの顔で、その涙を拭う。



　拭われても、拭われても、涙は流れた。

　まるで、スバルたちが助かったことと同じように、拭うことが無意味とばかりに。





　　　　　　　　　　　　　　　　△▼△▼△▼△







　――神様、仏様、オド・ラグナ様。生涯、誰かの夢を否定しないと誓います。







　　　　　　　　　　　　　　　　△▼△▼△▼△





　――あれ以来、リハビリはやめてしまった。



　心と体の配線、それを繋ぎ直し、不自由を脱却して、自らの足で大地を踏む。

　この四百年後の世界を、辿り着いてしまった明日の明日を、今日として生きる。



　そんなおためごかしの希望など、全てから見放された絶望の前には無力だった。



「スバル、ご飯かしら。ベティーが食べさせてあげるのよ」



　自発的に動く、という気力をなくしてしまったスバルの身の回りを、ベアトリスがちょこまかと甲斐甲斐しく世話をする。

　前々から、スバルのために尽くそうとしてくれる彼女だったが、生来の不器用さも相まってなかなかうまくいかないことが多かった。

　だが、使命感がそうさせるのか、甘え、頼る相手がいないことの不自由さが理由か、皮肉なことに、リハビリの成果の上がらなかったスバルと違い、ベアトリスの介護能力は日に日に向上し、テキパキとスバルを扱えるようになっていった。



　朝晩の食事に、お湯で体を拭く清拭。動かせない手足の筋肉を曲げ伸ばしさせるストレッチなど、ベアトリスの体躯では重労働のはずだが、文句の一つも言わない。

　それどころか、彼女はそうした一個一個の日課をきっちりこなすと、



「よく頑張ったかしら。偉いのよ、スバル」



　そう、何もしないだけの役立たずに、そう微笑みかけるのだ。

　これが、穀潰しに対する皮肉や嫌味であったなら、スバルの心もまだ救われる。そして当たり前だが、そこにベアトリスの悪意が含有されていることなどない。

　ただ、スバルを案じるベアトリスの想い、それがますます心を腐らせるのだ。



「――――」



　夜――否、夜に限らず、瞼を閉じて思い描くのは、何もかも変わり果ててしまった今の世界ではなく、置き去りにしてきてしまった過去の光景だ。



　そこには、スバルの大切なモノの全てがある。



　大切な仲間たちが、共に過ごした屋敷が、笑い合った思い出が、悩み尽くした問題が、乗り越えようと誓った未来が、全てがそこに残されてしまった。

　笑顔が、見える。笑い声が、聞こえる。温もりが、思い出せる。――それなのに、もう誰も、何もない。触れられない。話せない。笑えない。



　――スバル、と自分を呼ぶ声がする。



　色んな声が、たくさんの呼び方が、様々な感情が、ナツキ・スバルを呼んでいる。その一個一個を痛切に思い、ナツキ・スバルは沈んでいく。

　それでいいだろうと、思う。――立ち上がる理由が、今湧いてこない。



「あいたいよ」



　きっと、確かめるために立ち上がるべきなのだろう。

　もう誰も、何も残っていないと投げ出そうとしても、その姿かたちが手に届く位置になかったとしても、彼女だけは、今もこの世界に残っている。

　エミリアを、彼女との再会だけを希望に、立ち上がる努力をすべきなのだろう。



　スバルたちを救うために、自らを永久凍土に閉じ込めたエミリアと、その再会だけを求めて、懸命に足掻くべきなのだろう。なのだ。なのだとも。なのはわかっている。

　でも――、



「もし」



　エミリアさえも、氷の奥底に、本当にいるのだろうか。



「もし」



　そこに、エミリアがいなかったら。

　全て何もかも、スバルとベアトリスを生かすために、犠牲になっていたら。



「もし」



　生きる理由を与えるために、ニコラたちが共謀してついた嘘だったら。

　本当はエミリアも含めて、もう誰も、この世界に残ってなんていなかったら。



「もし」



　その理由まで失ったら、ないことを確かめてしまったら、スバルはどうなる。

　みんなが、ありとあらゆる犠牲を払ってまで、誰もいなくなってしまったこの大地に、取り戻してくれたスバルは、どうする。



　誰も、いない。



　エミリアも、レムも、ラムも、オットーも、ガーフィールも、■■■も、フレデリカも、スピカも、リューズも、メィリィも、ロズワールも、アンネローゼも、クリンドも、ラインハルトも、フェルトも、ロム爺も、アナスタシアも、ユリウスも、クルシュも、フェリスも、ヴィルヘルムも、プリシラも、アルも、シュルトも、アベルも、ミディアムも、フロップも、タンザも、セシルスも、ヨルナも、プレアデス戦団も、『シュドラクの民』も、誰も誰も誰も誰も誰も誰も誰も誰も誰も誰も誰も誰も誰も誰も誰もいないのに――。



「だれも」



　いない。いない？　いない。いない。いない？

　じゃあ――、



「――■■■は？」



　発音のできない、名前がこぼれる。

　思い出せない、記憶を蘇らせようとする。



　ポロポロ、ポロポロ、ポロポロと、掴みかけた端から、ポロポロと崩れ、自分の中に生じた違和感を疑いたくなる。違和感を抱いたことを、疑いたくなる。

　違和感を抱く理由なんて、あったっけ。■■■なんて、何が。



「■■■……」



　どうして、音にならないのか。それがあまりにもどかしい。

　必要だ、音が。記憶に留めておくために、誰かにそれを伝えるために。■■■、■■■、■■■だ。■■■！　■■■！　■■■――！！



「■■■……っ！」



　思い出せ。頭に留めろ。どこにも散り散りにさせるな。

　まるで、見ていた夢を寝起きに忘れるみたいに、脳が■■■を忘れようとする。脳が役に立たないなら、体に刻んでやろうかと思っても、爪に力を込める前に、■■■が輪郭を失い、何を描こうとしたのかを思い出せなくなる。



　不自然で、理不尽で、不条理で、不可解で、無慈悲で、不合理で。

　どうして、■■■を、スバルは覚えておけないのか。



「――ッ」



　歯噛みし、■■■を忘れようとする不自然に抗おうとする。

　■と■と■と、■■■の名前を分割して記憶に留めようとしても、それが■■■の名前のパーツだと認識した時点で、ばらそうと散りばめようと同じとみなされる。

　■■■を、正しく呼べないのは、世界に定められた逆らえないルールだ。そして、■■■のような、正しく名前を認識できないものは、世界から忘れられる。



　■■■を目にするまで、■■■を正しく認識できていないことを、■■■を知って、覚えているはずのスバルも気付けなかったように。

　きっと■■■を忘れても、素知らぬ顔で、また■■■を忘れた明日を生きる。



「ふざけんな……」



　ここまで、どれだけ失ってきたと思っているのか。

　ナツキ・スバルは、ベアトリスは、ここにくるのにどれだけ多くをなくしてきたか。こっちはもう、心がぶっ壊れかけてんだよ。ヒビだらけで、めちゃくちゃなんだ。

　なのにまだ、■■■を忘れて、■■■を手放して、生きろっていうのか。



「そっちが、そのきなら……」



　どこかの知らない誰かが、スバルたちがいない間にルールを定めた。その強制力が働いて当然の世界、異議を唱えたければその場にいればよかったのに、それができなかったから知らない間にルールが締結された。なるほど、わかった。大いに結構。



　誰が、そんな馬鹿げたルールに従うか、バーカ。



「■■■。■■■。■■■。■■■。■■■」



　一秒、ほんの一秒、■■■のことを考えることを忘れれば、その一秒を二秒に、二秒を五秒に、五秒を十秒にと拡大され、広がった空白が■■■を頭から追いやる。

　そうやって忘れさせ、なかったことにするのが運命の手口だ。――だったら、これから先、ナツキ・スバルは一秒だろうと■■■のことを忘れない。



　これから一生、死ぬまで頭の片隅に、■■■のことを刻み続ける。

　ナツキ・スバルの心の一部を永遠に、■■■のために捧げる。



　確かに、いたのだ、■■■は。

『憂鬱の魔女』などと呼ばれ、世界中のあらゆる人から災い扱いされて、世界最恐とされる『狂皇子』相手の切り札にされるくらい、とんでもない存在となっても。



　ナツキ・スバルとベアトリスの前に、■■■は、確かに現れたのだ。



「また、やるよ、■■■」



　何度も折れて、何度も忘れて、何度も投げ出して、何度もへこたれて。

　何度も決意して、何度も刻んで、何度も顔を上げて、何度も立ち上がって。



　馬鹿みたいに学びのない、不細工でみっともない歩き方でも、またやる。



「――ベアトリス」



「――――」



　久しぶりに唇を動かした。乾いて張り付いた唇の皮が裂けて、血が流れる。痛みは、まだない。脳と体の配線は、今もなお繋ぎ直されていない。

　でも、またやる。やると決めた。今度こそ、本当に、時間がかかったけど。



「■■■が、いきてる。きっと、えみりあも。だから」



「――――」



「だから、おれ、がんばるよ。またせてごめん」



　決意と諦めを繰り返して繰り返して、我ながら説得力のない決心。

　それでもしかし、言った。恥も外聞もなく、言った。

　だって――、



「待つのなんて、当たり前かしら。――ベティーは、スバルのパートナーなのよ」



　スバルの最高のパートナーは、そう言ってくれるとわかっていたから。





　　　　　　　　　　　　　　　　△▼△▼△▼△







　――神様、仏様、オド・ラグナ様。生涯、誰かの背中を押したりしないと誓います。







　　　　　　　　　　　　　　　　△▼△▼△▼△





　――百二十六億、二千二百七十八万、八百秒。



　それが、四百年を秒数に換算した結果だ。

『憂鬱の魔女』と化した■■■の権能で、スバルはほんのひと時、長い長い無為な時間を過ごすことの恐ろしさを味わった。



「一秒の百万倍は、百万秒……」



　ざっくりと計算して、十一日と半分、それがスバルの味わった百万秒だ。

　日数に直すと、それが大した時間でなかったように思われて、驚く。あんなにも終わりの見えない、真っ暗なトンネルの中を歩くような感覚だったのに。



　そして、■■■が過ごした四百年は、その百万秒のおおよそ一万二千倍だ。



「……あれを、一万二千倍」



　無論、何もない日々ではなかっただろう。

　それこそ、『憂鬱の魔女』の名が世界中に知れ渡り、自分でも知っている人たちが次々とこの世を去り、ついには王国や都市国家までも滅亡し、今に至った。

　まさに、激動の時代を体感したと、そう言っても過言ではない。



「でも、わかるよ。そんなの、関係ないって」



　たとえ、世界が書き換わるような大きな出来事が連発したとしても、それが心を動かすものでないなら、何が起きても窓の外の大風と変わらない。

　我が事と思い、熱と実感を伴い、そうした感覚が味わえてようよう、あらゆる体験というものは自分の人生の一部になる。それが得られない人生なんてものは、空疎で何も存在しないも同じ。――まさに、この世の地獄だ。



　その地獄を、■■■は過ごした。夢も、希望もなく、ただ惰性で。

　長い長い虚無的な時間が、彼女からそうしたキラキラしたものを奪い去り、『憂鬱の魔女』としての■■■を作り上げてしまった。

　そうでなくちゃ、今の彼女の在り方に説明がつかない。

　そして――、



「――俺に、それを何とかしろっていうんだろ、みんな」



　そう言って、スバルは自分の手で着替えた服の襟を正し、靴の紐を強く結んだ。

　口を利いて、自分の思う通りに手を動かし、立って歩けるようになるまで心と体の配線を繋ぎ直すのに、途方もない時間をかけてしまった。



　腐っていた時間の長さと、リハビリにかけた時間。

　それでも、強い目的と成し遂げなければならない目標があったスバルの過ごした時間は、■■■が過ごしただろう四百年より、はるかに救いのあるものだった。

　その、スバルが与えられた救いを、■■■にも届けたい。



「――ナツキさん、準備はできましたか？」



　用意万端、ずいぶんと長く過ごした部屋を感慨深く眺めるスバルの背に、すっかり耳に馴染んだニコラの声がかけられる。

　振り向けば、そこには出会ったときと同じ、柔和でどこか頼りない、しかし大きな仕事を成し遂げる男が、とっくに使いこなしている義足で堂々と立っている。

　スバルが腐っている間も、着々と自分の人生を前に進めていた彼が。



「できたよ。本当に、お前には何から何まで世話になりっ放しだ。この借りは……」



「それなら、だいぶ前にも結構ですと言ったでしょう。ナツキさんとベアトリスちゃんを拾い上げられた時点で、僕は十分救われたんです。ですから、貸し借りなんて……」



「いや、返すよ。お前が断っても、お前の爺さんの爺さんの爺さん……とにかく、俺のダチは借りを返さないなんて許さねぇ。っていうか、わかったんだよ」



「わかった、というと？」



「あいつが、なんで子々孫々にまでわたって、俺とベア子を引き上げろなんて無茶な言い伝えを残したのか、だ」



　その、具体的な理由を明文化しなかったのは、彼の手落ちか、それとも別の理由か。

　案外、抜けているところもあったから前者の可能性もなくはないが、ただ、その目的を取り巻く事象を考えれば、文字に起こすことさえできなかったのかもしれない。

　それでも、行動が言葉よりも明瞭に意思を伝えることは、ある。――オットー・スーウェンが、子孫たちを間に挟むことで、ナツキ・スバルに託したもの。



「――ナツキさんが、■■■ちゃんを救ってください、だ」



「――――」



「そうすると、色んな歯車がガチャガチャ噛み合うんだ。そりゃ、みんなが俺を助けようとしてくれたってエピソードも超熱いさ。だけど、自分たちがいなくなったあと、出てきた俺が魂の腑抜けた抜け殻になる可能性だって思いついたはずだ。でも……」



　みんな、そうしなかった。

　誰も彼もみんな、ナツキ・スバルを引き上げることを諦めなかった。何故なら、ナツキ・スバルには戻ってきて、やってもらわなければならないことがあったからだ。

　自分たちでは救えなかった■■■を、スバルは救わなくてはならない。



　そのために、あの時代を生きたみんなが、スバルに大きな貸しを作ったのだから。

　きっと、他でもない誰より、代償を捧げた■■■のために。



「それにしたって、厄介な仕組み……呪い、システム、クソルールだよ。誰も、■■■のことを残せない。記録できない。記憶を、語れない」



「でも、ナツキさんは覚えてる。ベアトリスちゃんも」



「そりゃ当然だよ。なにせ、一人の女の子の人生捻じ曲げて、『魔女』なんてとんでもないものにまでしちまったんだ。責任取らねぇと」



　それこそ、人生を捧げでもしなければ、釣り合いが取れないくらい。

　そのスバルの覚悟の答えに、ニコラがその顎に蓄えた似合わない髭を撫で、笑う。

　そんなやり取りを交わしていた直後だ。



「ナツキ・スバル様！　こちらの準備、燃え滾るほどに万端ですかしら！　ベアトリス様もわたくしも、灼熱の如く絶！　好！　調！　ですかしらー！！」



「ええい、騒ぎすぎかしら！　大体、ベティーの調子をどうしてお前が勝手に説明するのよ！　あと、いい加減に温度調整を覚えるかしら！　熱いのよ！」



　わあわあと、騒がしく飛び込んでくる大小二つの影に、スバルはニコラと顔を見合わせ、それから堪え切れずに笑みをこぼした。

　と、その室内の二人を目に留め、「あらまあ」とルーメラが口に手を当てて、



「ニコラ様！　今日は調子がよろしかったのでございますですの？　近頃は、あまり外に出られていないとお聞きしていたでございますですかしら」



「それには違いありませんけどね、今日、見送りにこないのは嘘でしょう。『勝機を見出せないものに商機は掴めない』、ホーシン語録です。今やすっかり廃れましたけどね」



「いい言葉はいい、ですかしら。わたくしの燃え盛るほど素晴らしい主様も、お仕えしていた方のそうした言葉を大事にしていたものでございますですもの」



　ホーシン語録が廃れ、しかし廃れたそれを大事にする二人のやり取りに、自然とかつての光景と、そこにいた人たちのことが脳裏に蘇る。

　だが、そのノスタルジックでセンチメンタルな気持ちは、今は封印だ。



「けど、ルーメラ、本当に俺たちとくるのか？　間違いなく、ヤバい戦いになるぞ」



「あらあらあらま、わたくしを案じてくださっているですかしら、ナツキ・スバル様。そうだとしたら、なおさらわたくしがいるべきでございますですわよ。だって……」



「姉妹の敵討ち、か？」



「いいえ、違いますですかしら。――主様なら、ここで必ずナツキ・スバル様と共に戦ったはずでございますですもの。だから、わたくしもそうするですかしら」



「……クソ、あの野郎、直接文句も手も出せねぇところに先にいきやがって」



「ふふふ、それが『最優』というものですかしら！」



　ドンと、その豊かな胸を叩いて、ここにはいない男のことを誰より誇る。そのルーメラに、姿かたちも性格も態度も何もかも違うのに、彼女が主と仰いでやまない『最優の騎士』と同じだけの頼もしさを感じるのは、不思議な心地だった。



「実際、ルーメラがいるのは追い風かしら。それに、どのみち予想される衝突が起こったら、絶対にあの男は横槍を入れてくるのよ」



「なら、総力戦にした方が全員にとっていい、か。ったく、俺たちは任された大事なお役目に集中したいってのに、俺のベア子がモテすぎるせいだな」



「心配しなくても、そのベティーを射止めたスバルのことも、あの男はちゃーんとロックオンしてるかしら。狙われるのはおそろなのよ」



「そりゃいい。揃って狙われるんなら、ベア子の浮気を疑わずに済むもん、な！」



「んきゃっ！」と、不意に担ぎ上げられ、肩車される形になったベアトリスが驚く。しかし、すぐにスバルの頭に手を置く彼女は、そうされるくらいスバルが体の調子を取り戻したことに、感慨深そうな吐息をこぼした。



「――――」



　その、頭頂部に当たる吐息についてスバルは触れない。

　感謝なんて、いくらしてもし足りないし、感謝の言葉はいくら尽くしても尽くし足りないくらい、ベアトリスにはたくさんの心配と迷惑をかけ続けた。

　本当に長いこと待たせてしまって、ようやくここから、ここからなのだ。



「なんじゃ、湿っぽい。まるで、死地に出向くような湿度の空気よな。そなたら、妾の『九神将』を貸し出す意味がわかっておるのか？　のう、どうじゃ？」



　ベアトリスを肩車したまま、ニコラとルーメラを伴ってスバルが家の外に出ると、そこで待ち構えていたのはヴォラキア帝国の統一皇帝閣下だった。

　王宮を離れ、わざわざ直接やってきたその姿に、スバルは「お」と目を丸くして、



「こんなとこにいていいのか？　だいぶ忙しいって聞いたぞ。なんかあれだろ？　こう、帝国転覆を狙ってた奴らの根城がわかったとか何とか」



「たわけ。そこまでわかった時点で、妾が差配すれば問題などあるはずないのじゃ。あまり決まったものたちばかり重用していると、かえって部下の心が離れる恐れもある。ヴィンセント・ヴォラキアはそうした点に行き届かず、よくよく皇妃にフォローされておったと、そう記録されておるほどじゃ」



「すげぇな。あいつ、後世に冷血だったことと、ミディアムさんの尻に敷かれてたことが残されてんだ。知ってたら眉間の皺が埋まらなそう」



　どうあれ、尊敬される対象かはともかく、自分の子孫たちの治世に反面教師としてでも役立っていたなら、アベルも浮かばれるだろう。「ふん」と、あの仏頂面で腕を組み、しらっとした顔をしているのが目に浮かんだ。

　そんな、先帝の恥を語った若き皇帝の左右には、今しがた彼女が語った、よく重用される二人――アラキアと、マデリンの姿がある。

　以前から、旧知の顔を見せてやろうという気遣いなのか、スバルたちのところに同行させられることの多かった二人だが、今回はこれまでとは事情が違う。



「まさか、ダメ元で頼んでみたものの、『九神将』をレンタルさせてもらえるとは」



「当然、妾らにとっても利があってのことよ。そなたがあのアグザッド絶氷河の問題を取り除ければ、長年の煩いだったグステコ聖王国への道が開ける。『霊獣』も死に、グステコ聖教の影響力も低い今、あの国をあのまま放置はできぬのじゃ」



「そうしたら、全世界を制圧した超統一帝国ヴォラキア誕生か」



「そこで、妾は世界統一を成し遂げた超皇帝として歴史に名を遺すわけじゃな。――病などなければ、それは母君の栄誉であったろうに、運のない」



「……湿っぽい話を嫌ったわりに、お前の方からしてきたかしら」



「――ふん、口を慎め。可愛いからといって、母君のように妾は甘くないのじゃ」



　なんて、結局罰しないのに言われても説得力がない。

　それはスバルもベアトリスも、皇帝当人を挟んだ二人の『九神将』にもバレバレで。



「協力してもらえるのは心底ありがたいけど、俺の指示に従ってもらうぜ？　■■■……『憂鬱の魔女』を殺したりするつもりはないから」



「聞いてる。無茶で馬鹿。でも、従う」



「命令だから？」



「違う。わたしも、あの『魔女』は嫌いじゃない」



　言葉少なに、最高の言葉で協力を約束してくれるアラキア。

　その答えに笑みを返し、スバルはもう一人、マデリンの方を見やり、



「マデリン、頼んであったことは？」



「お前も、竜相手に無茶ばかり言ってくれるっちゃ。本気で役立つと思ったっちゃか？」



「役立つかどうかはともかく、いてくれなきゃ締まらねぇとは思ってるよ。■■■を引き戻すための同窓会なんだ。面子は多けりゃ多いほどいい」



「はぁ……苦労したけど、見つけはしたっちゃ」



「――！　本当か！　すげぇ！」



　腰に手を当てて、大きくため息をついたマデリンの回答に思わず飛び跳ねる。

　正直、これに関しては『九神将』のレンタル以上のダメ元だった。それどころか、まず確信すらなかったことだ。■■■絡みであったのだろう。記録にもはっきりと明示されたわけではなかったそれは、ルグニカ王国のとある地――ロズワール・Ｌ・メイザースの屋敷の跡地、そこで封じられていた禁書に記された情報だった。



　それは、スバルも知るとある人物の正体――四百年後の今、居場所のわからない彼の足取り、その捜索をスバルはマデリンに託していた。

　同じ立場である彼女なら、見つけられるかもしれない一縷の可能性に賭けて。



「大したもんなのよ。ベティーがあとで頭を撫でてあげるかしら」



「いらないっちゃ！　竜を子ども扱いするんじゃないっちゃ！　竜もお前も、どっちも子どもでも何でもないっちゃ！」



「だな。八百歳のドリルロリと、四百歳の角ロリだ」



「それも不愉快な表現っちゃが……聞いても無駄かもしれないっちゃよ」



「え？」



「腑抜けて、使い物にならないと竜は思うっちゃ」



「――――」



　腕を組んだマデリンは、その金色の瞳を細めながらそう前置いた。

　言いづらいことでもはっきりと伝えるのは、竜人たる彼女の強さであり、気遣いの裏にあるのは人間社会で長く生きたことで芽生えた思いやりだ。

　同時に、使い物にならないとまでマデリンに言わせた相手、それがどれほどの絶望の中にいるか、スバルには察せられるものがあった。――否、



「俺たちにしか、それはわからねぇ。だから、俺とベア子がいくよ」



「いくのよ。スバルとベティーは、いつでも一緒かしら」



「おう」



　肩車されたベアトリスと、スバルがお互いの両手をグータッチ。

　それを目にしたマデリンは肩をすくめると、それ以上の反対意見を言わなかった。



「――――」



　それを確かめ、スバルは大きく息を吸い、吐く。

　しんと冷たく澄んだ空気を肺の中に取り込んで、熱を帯びた体をわずかに冷まし、ゆっくりと、背後にいる仲間たちを振り返った。



　四百年、長い長い時間、ただ揺蕩うだけだったスバルとベアトリスを助け出し、やらなければならないこと、それに全力を捧げるだけの猶予を与えてくれたみんな。



「ニコラ」



「はい」



「ルーメラ」



「ですかしら！」



「ロザリンド」



「代わりに返事してやるのじゃ」



「アラキア」



「ん」



「マデリン」



「聞いてるっちゃ」



「ベア子……ベアトリス」



「もちろん、いるのよ」



　順番にみんなの顔を見て、順番にみんなの返事を聞いて、順番にみんなの頼もしさを胸に蓄えて、スバルは大きく息を吐いた。



　たくさんのものを置いてきた。たくさんの人と別れてきた。

　それは悔しい。悲しい。今も辛い。でも、一度空っぽになってしまった手は、そのまま空っぽでいられるほど、強くなかった。



「違うな。俺、ずっと一人になんてなってなかった」



　ただスバルが腐って、一人になったような気になっていただけだ。

　ベアトリスがいて、ニコラたちがいて、きっとエミリアが待ってくれていて、そして、■■■が迎えにくるのを待たせているのだから。



「――いこう。俺たちが、俺たちであるために」





　　　　　　　　　　　　　　　　△▼△▼△▼△







　――神様、仏様、オド・ラグナ様。生涯、■したことを■れないと誓います。







　　　　　　　　　　　　　　　　△▼△▼△▼△





　――そして、物語は冒頭の、絶氷地帯の瞬間へと立ち返ってくる。



「お前を取り戻すぜ、■■■。――運命様、上等だ！！」



　吹き付ける冷たい風、不穏なまでに毒々しく高まるマナの波動、そうした不安要素を吹き飛ばす意味も込めて、大きく大きく、スバルは叫んだ。

　その強い感情を向けられ、しかし『憂鬱の魔女』の横顔は小揺るぎもしない。

　そうして、初手の告白があっさり失敗するのと――、



「――六秒だ」



　白く染まる大地を強く踏み、一瞬で間合いを詰めてくる『狂皇子』が両腕を振りかぶる。その腕には『呪剣』が二振り握られ、刹那ののちに放たれる剣風が、スバルたちと■■■たちとを、まとめて両断しにかかるだろう。

　■■■はどうとでもできても、すでにＥ・Ｍ・Ｍを使ったスバルたちにそれを防ぐのは難しい。

　故に――、



「――生憎と、もう少し手こずっていただきたく。要求」



　瞬間、地上で鳴り響く雷鳴が、真正面からの雷爆となって『狂皇子』を襲った。

　炸裂する光、それが八方に衝撃波を広げ、凍り付いた大地が放射状にひび割れ、砕けていくのがスバルの目にもわかる。一瞬、それが自分の足下に届く可能性を危惧するが、すぐにそんなものは不要だと判断した。



「だって、万能家令がそんな手落ちするわけねぇし」



「大変光栄な評価です、スバル様。それに重ねて感謝を。大恩」



「大恩なんて大げさだ。俺の方こそ、きてくれて感謝してます。――クリンドさん」



　そう言ったスバルの視界、そこに細くしなやかな背中を見せる、秀麗な面立ちをした青い髪の男――クリンドが立っている。

　四百年前のかつてを知る一人であり、この時代になお生き延びた旧知の人物。――そして今、その青髪をいただく頭から、二本の黒い角を生やした竜人。



　四百年前に行方をくらまし、同じ竜人であればと希望を託したマデリンの捜索で、ようやくその居場所を見つけることのできた、最後のピース。



「私は、大きな過ちを犯しました。その覚悟と未来を切望するあまり、大きな代償を支払おうとする真意に気付けなかった。痛恨」



　静かに、クリンドの唇から紡がれるのは、彼ほどの人物が四百年間、表舞台に立つこともなければ、ニコラたちのようにスバルたちの捜索に協力するでもなく、失意のままに長い時間を過ごすことになった理由。

　やはり欠け落ちたものの多い記憶の中、それでも残った強い後悔に苛まれたクリンド、その断片的な証言から、スバルは彼が味わった絶望――それが、■■■が『憂鬱の魔女』となってしまった今の状況に、密接に関わっていると看破した。



　あるいは彼も、死を覚悟したかもしれない。

　しかし――、



「我が後悔と哀惜を、あなたに捧ぐ。――今度こそ」



　決意を宿した金色の瞳、その全身に纏った迸るような紫電、この時代まで命を繋いだ竜人たる存在が、スバルたちの願いと祈りに力を貸す。



「……竜人か。竜殻や竜暈を纏った貴君ら『龍』は、広義の意味で精霊と同じマナ体の保有者だ。だが、我輩は貴君らを直接の敵とは思わず、思っていない」



　紫電一閃、クリンドの放った雷光を纏った一撃を正面から喰らい、しかし、『狂皇子』は交差した『呪剣』の柄でそれを受け、大きく下がるだけに留まった。

　その途方もない力量は、常外の力を有した竜人さえも凌駕する。――そうした、力の差の確信があってのことではないだろう。



　そういう、わかりやすい打算や驕りで、『狂皇子』は相手を見ない。

　それは、ベアトリスやルーメラたちの無事を巡り、最悪の初対面以降、何度も何度もその凶刃と衝突する機会のあったスバルには、明々白々な事実だった。



　その証明とばかりに、『狂皇子』は手の中の『呪剣』の感触を確かめながら、相手が誰であろうと変わらない無表情で眉を顰め、



「それでも、戦うのかね？」



「言うに及ばず。至言」



「そうか。残念で、残念だ。消えてもらう。残念なことに」



　刹那、雷爆と光爆とが地上でぶつかり合い、音さえ掻き消えた凄まじい爆圧が、戦場となった絶氷河を内から膨れ上がり、云百年そのままだった世界の形を変える。

　それは数百年ぶりの、世界の趨勢を揺るがすような超越的戦いの幕開け――、



「いいの？　あれ、放っておいて」



　ふと、そう尋ねてきたのは、遠目にその戦いを眺める■■■だ。

　彼女はその青緑の瞳をけだるげに細めながら、大した興味もなさそうな素振りで、スバルにクリンドと『狂皇子』との戦いのことを聞いてくる。

　一瞬、不用意な彼女の接近に、スバルは呆気に取られかけたが、



「大丈夫だ。これも全部、作戦通りだから」



「そうなの？　でも、あの竜人さんじゃ『狂皇子』さんに勝てないでしょ？　やられちゃうのも時間の問題だと思うけど」



「さすが、■■■はお目が高い。――けど、大丈夫だ。すぐに」



「――援軍がくるかしら」



　言うが早いか、氷上で攻防を繰り広げるクリンドと『狂皇子』、その戦いに、四方から猛然と乱入してくる影――全身を立ち上る炎で包んだ赤髪の大精霊と、その身から煌めく金剛石の光帯という矛盾した武装を伸ばした『金剛姫』、そして久々に『雲龍』の竜殻を実戦投入し、自分×自分という連携を実現する『飛竜将』。



　――それら、今の世界の最強クラスが揃い踏みし、戦いが一段も二段も加熱する。



「……確かに、あれならもうちょっとだけもつかも。だけど、あそこにいるのって全員『狂皇子』さんのターゲットっぽい人たちでしょ。『狂皇子』さん、戦ってる間にどんどん強くなるタイプだから、作戦ミスじゃない？」



「――――」



「……なに？　わたし、変なこと言ってる？」



「いや……お前の口から、ターゲットとかタイプとか、そういうのが聞けて、胸の奥がじんわりしたんだよ」



　■■■の見立てに対し、スバルも正直な気持ちを口にする。途端、不気味なものを見るような目をされたが、仕方ない。感慨深さは本物だ。

　ただ同時に、■■■の戦術評価は正しい。――そもそも、『狂皇子』は存在だけでなく、与えられた才能も埒外の化け物なのだ。



『適応の加護』で如何なる状況や環境にも適応するだけでなく、『孤独の加護』で単独戦闘の能力を恒常的に上昇し、『反復の加護』で戦いの中で同じ動作が加速度的に洗練され、本来なら死に際だけ効力を発揮する『不屈の加護』が、心臓の動かない精霊人であるというオンリーワンのバグによって常に発動し続けている。

　そうした、複数の加護の所有者にして、当たり加護が相乗するシナジー爆発。――それが『狂皇子』の、圧倒的な戦闘力の正体、その一端。



「ラインハルトも相当馬鹿だったし、セッシーとハリベルさんもまあ馬鹿だったけど、あいつもやっぱりおんなじレベルの馬鹿なんだよなぁ」



「なんなの？　じゃあ、勝てないってわかってるってこと？　あのね、自殺なら余所でしてほしいな。わたし、ここで暮らしてて、暇じゃないの」



「自殺じゃねぇよ、勝ちにきた。確かに、このままだったらこっちは負ける。でも」



「でも？」



「■■■、お前が力を貸すなら話は別なのよ」



　そう、スバルと手を繋いだベアトリスの発言に、■■■が怪訝そうに眉を顰めた。

　そうして眉を顰めても、欠片もその美貌の薄れない『魔女』は、「意味わかんない」と無感情に呟いて、



「どうしてわたしがそんなことするの？　わたし、『憂鬱の魔女』。知ってる？　誰もわたしを従えられないし、命令もできない。そういう存在なの。それとも――」



　そこで■■■が言葉を切り、ゾッとするほど艶めかしい流し目を送ってくる。

　それが、ポジティブな感情を理由にした動きでないことは、■■■の傍ら、スバルに寄り添うベアトリスの如く、その傍を離れない紅蠍を見ればわかる。

　紅蠍は、誰にも侵犯できないはずの『憂鬱の魔女』を、それでもあらゆる災いから守ろうとするかのように、その複眼を炯々と光らせていて。



「お前、誰かに、■■■を守ってってお願いされたのか？」



「……それ、なに？」



「いや、想像だよ。思い出はボロボロで、でもそうだったらいいなって思って」



「さっきから……ううん、最初からちっともあなたの言ってることわかんない。一緒にいる子もそうだけど、変なお爺さん」



　不満、不愉快、不可解、色々とないまぜになったのかもしれない。

　相変わらずローテンションながら、それでもわずかに感情の込められた一言は、しかし今のスバルにはグサリと刺さる手厳しいものだった。

　スバルは、ベアトリスと繋ぐのと反対の手で、すっかり白くなった自分の髪を撫で、



「変な爺さん扱いは凹むぜ。まだまだ気持ちは若いつもりなんだけど、ダメかな。髭もこう……憧れのヴィルヘルムさんリスペクトで整えてみたり」



「ベティー的には、どんなスバルも男前……一言で言い表すのと、万人に通用するとは言い難い魅力に満ちていると思ってるかしら」



「フォローし切れないフォローをありがとう！」



　何とも素直に喜べない評され方だが、そこに嘘がないのは疑いもしない。

　そうでなければ、こうしてやらなければならないことを成し遂げるまでの準備にかけた四十年――片時も離れず、支え続けることなんてできるはずがない。

　愛情以外の答えが見つからないし、見つける必要もなかった。



「愛情、か。そうだな、そうだよ。頑張る理由なんて、それしかねぇもんな」



「あなた……」



「長かったよ、四十年。でもさ、それですら十二億六千二百二十七万八千八十秒。■■■が過ごした時間の、十分の一でしかない。本当に……本当に、さ」



『憂鬱の魔女』の、その権能。――ベアトリスと検討し、推測されたその『圧縮』という力で以てしても、実際に味わったものとして過ぎる時間は潰し切れない。

　■■■が生きた四百年、スバルが自責と自罰に苛まれて味わった地獄の日々など、鼻で笑いたくなるような歳月、それが■■■の心をすり減らして。



「どうして、そこまで自分をすり減らして、ここまで何もかも代償に支払って、どこまでも可能性を捧げて、それでも今に辿り着いたんだ？」



「何を……」



「どうしてなんだ、■■■……■■■！」



「やめてよっ！　その、聞き取れない呼び方をしないで！」



　不意に『憂鬱の魔女』の表情が崩れ、彼女が大きく後ろに下がった。そのまま反射的に右手を構えた■■■、それは指を鳴らし、権能を発動する用意だ。

　相手の命を奪わないで、その経過する体感時間で相手を追い払う、『憂鬱の魔女』の、決して殺さない不殺の権能――、



「やれよ、『圧縮』してみろ」



「――っ、簡単に言わないで。まさか、耐えられるとか思ってるの？　そんなの無理だよ。これに耐えられるなんて、人間じゃないもん。四百年って、長いんだよ」



「知ってるのよ」



「――――」



「ベティーは知ってる。■■■が過ごしたのと、ベティーの過ごした四百年は違うものだけど、それでも、きっと同じところのある寂しさを、知ってるかしら」



　ベアトリスにも、『禁書庫』で過ごした途方もない歳月があった。そして、終わりがないとすら思われた空虚な日々、それが終わり、解放される日があることを知っている。



「それを、ベティーは■■■にもわかってほしいのよ。お前には、それを受け取る権利があるかしら。……違う、受け取ってほしいのよ」



「……どうして？」



　構えた指を、スバルとベアトリスのどちらに向けるか迷いながら、ずっと見せなかった感情を覗かせる『憂鬱の魔女』が、そう問いかけてくる。

　何もかもかなぐり捨てる過程で、理由さえ手放すしかなかった悲しい『魔女』が。



「お前に、幸せになってほしい。俺たちみんなが、そう思ってるからだ」



「みんな……？」



「俺が、ナツキ・スバルが」



「ベティーが、ベアトリスが」



「エミリアが」「フレデリカが」「オットーが」「ガーフィールが」「レムが」「ラムが」「ロズワールが」「リューズが」「メィリィが」「スピカが」「アンネローゼが」「クリンドが」「アーラム村の人たちが」「コスツールの人たちが」「家族が」「仲間が」「俺たちが」「ベティーたちが」「「みんなが」」



「――っ」



　息を詰まらせ、■■■が頬を強張らせる。

　どれ一つ、きっと■■■には聞き覚えのない名前だ。理由はわかる。スバルがそうだったように、■■■自身、自分に関わる多くの人のことを、たったの一秒、思わないだけで全部忘れてしまう。その繰り返しで、全部摩耗し切ってしまう。



「正直、スバルが頭のどこかで永遠に■■■のことを考えてればいいって言い出したときは、さすがに無茶だと思ったかしら」



「そうか？　大したことじゃないだろ。頭の一ヶ所、■■■のために捧げるくらい」



「なのよ」



　頷き合い、それから改めて、険しい目つきをした■■■を見つめる。

　彼女の発した、「どうして」にスバルたちは答えた。

　あとは――、



「お前も答えてくれ。さっきのどうしてに」



「さっきのって……」



「どうして、■■■は『魔女』になってまで、災いなんて言われてまで、大勢からこの場所を守り抜きながら、四百年の空疎を乗り越えたかしら」



「――――」



　ベアトリスの噛み砕いた問いに、■■■が息を呑み、何も言えなくなる。

　それを正面にしながら、スバルは一歩、前に出た。ベアトリスが繋いだ手を解いて、そうするスバルの背中を小さな手で柔らかく押す。

　一歩、一歩と前に出る。一度下がった■■■との距離が詰まる。



「――――ッッ」



　その、スバルと■■■との間に、紅蠍が割って入った。

　それはまるで、■■■を傷付けるあらゆる全ての災厄から、自分を犠牲にしてでも■■■を守ろうと、そう決意しているかのように。

　でも――、



「ずっと、俺たちができないでいたことを、ありがとな」



「――――」



　そう言って、その甲殻をスバルが撫でると、持ち上げられていた両手の鋏が下ろされ、のっそりとした動きで、紅蠍はスバルに道を譲った。

　その紅蠍の行動に、■■■が裏切られたみたいな顔で目を見開く。――光栄な話だ。ここで紅蠍がどいたのを裏切られたと感じるのなら、



「俺がこうすることは、お前にとってちゃんと意味があることなんだな」



「あ……」



　すぐ正面、手を伸ばせば触れられる位置に立ったスバルに、■■■の瞳が揺れる。美しい、スバルの掠れ、消えかけている■■■との思い出、そこにいる彼女よりも、目の前の彼女はぐっと大人になり、可憐さよりも美貌が際立っていた。

　ドレス選びと着こなし、髪のセットにしたって、誰にも見せないのにオシャレの塊みたいなセンスをしていて、実に■■■らしい。

　四百年経っても、そうした部分を変えず、変わらず、彼女はいた。

　それは――、



「俺たちに――俺に会いたかったからだろ」



「――ぁ」



　掠れた息が、世界中から恐れられる『憂鬱の魔女』にできた、最後の抵抗だった。



「――――」



　伸ばした手で、その細い体を引き寄せ、スバルは■■■を自分の胸に抱きしめる。

　びくりと、怯えるように■■■の体が震えた。しかし、熱を帯びた■■■は、押せば容易く砕け散るスバルの老体を、押しのけようとはしなかった。

　だが、抱き返してくることもしない。それは彼女の拒絶、ではなく――、



「それも、捧げてしまったのよ」



　誰かと、抱きしめ合う権利さえ捧げて、■■■はこの未来を切望した。

　何故か。何故だったのか。その答えは、ナツキ・スバルが押し付けるしかない。ナツキ・スバルに会いたくて、四百年間、■■■は空疎に耐えたのだと。

　そして、その空疎は今、四百年の長い空疎は今、終わるのだと。



「わたし、わたし、は……」



「いいよ。お前が誰かを抱きしめられないなら、俺が抱きしめればいいだけだ」



「――――」



「お前が名前を呼べないなら、俺がお前の名前を呼ぶ。お前が人前で泣けないなら、こうして顔を胸に押し付けさせてやる。お前が好きなものを食べられないなら、いくらでも新しく好きなものを作ってやる。お前が誰の手も握れないなら、俺が手を重ねてやる。お前が誰にも弱味を見せられないなら、俺はお前の強さを四百年分褒める」



　自分のできること、したいこと、未来、希望、可能性。

『憂鬱の魔女』になるための資格は、たくさんのものを■■■から奪い去った。■■■はその可能性を得るため、掴むため、自分でそれを望むこともできない。

　でも――、



「大丈夫かしら、■■■。スバルは、勝手に人のことを思いやって、勝手に人の気持ちを想像して、勝手に人を喜ばせようとする、天才なのよ」



「それでベア子も口説き落とした。■■■、お前もその餌食になれ」



「――っ」



　抱きしめた体を、スバルはそっと持ち上げ、驚く彼女の顔を間近に見た。その瞳には、込み上げる感情に反して涙は浮かんでいない。

　誰かの前で涙を流す権利をも、すでに彼女の手の中にはない。残されている、彼女の可能性は、希望は、未来は、何があるだろうか。

　ただ少なくとも、頬を赤くして、潤んだ瞳で、こちらを見る資格は捧げていない。



「意味わかんない。あなたたち、みんな、意味わかんない」



　震え声で、ただの人間に捕まってしまった『憂鬱の魔女』がそうこぼす。

　どんな災いも、痛みや辛さも、『圧縮』することで刹那のことにできる『魔女』が、この一瞬を決して、失いたくも手放したくもないと、そう祈るように、唇を震わせる。



「意味、わかんないのに……なのに」



『憂鬱の魔女』が、『魔女』が、■■■が、潤んだ瞳で微笑む。

　自分の中に湧き上がる情動、手放さずにいたそれを、確かめるみたいに。



「――わたし、あなたのこと、愛してるみたい。変だよね」



「いや？　ちっとも」

「かしら」



　拒まれる覚悟でいたのだろうか。

　口にした愛、それを一瞬の躊躇もなく受け止められて、■■■が目を丸くする。その『魔女』らしさなんて皆無の、ただの村娘みたいな顔に、笑みがこぼれた。



「さすがに村娘にしちゃ美人すぎるか」



「……それ、誰にでも言ってそう」



「言ってたとしても、村娘にしちゃ美人すぎる村娘にだけだ。あんまり該当者、多くないと思うぞ。俺の知る範囲だと一人だけだ」



「そう。……ならいいけど」



　スバルの答えを聞いて、■■■が拗ねたような態度で顔を背ける。そこに可愛げを見出しながら、スバルは大きく息を吐くと、



「あのさ、下ろしてもいい？　腰がちょっとヤバくて」



「まさか、わたしが重たいっていうの？」



「違くて！　全然■■■は重くないけど、綿毛みたいだけど！　でも、俺の方が六十の爺さんだから！　ヨボヨボではないけど、贔屓目に見てもヨボだから！」



「むう……わかりました」



　承諾を得たところで、ゆっくりとその場に■■■を下ろす。するとすかさず、駆け寄ってきたベアトリスが、ひょいとスバルの腕の中に代わりに収まった。

　それを見て、またしても■■■の目が厳しくなり、



「わたしはダメで、その子はいいの？」



「■■■は見たらわかるでしょ。うちのベア子は精霊で、真の綿毛だから」



「綿毛なのよ」



「息ピッタリ……もういいよ」



　そのスバルとベアトリスから顔を背け、ゆっくりと歩き出した■■■、彼女は脇にのいていた小紅蠍の背中を撫でると、「裏切り者」と小さく糾弾した。

　それから、このやり取りの最中も、なおも続いている伝説級の激戦――そちらの方にちらと目をやり、



「いつの間にかとっても危なくなってるけど、わたしに手伝ってほしいんだっけ？」



「ああ。ヴェイグの奴は、ここらで長いこと大人しくさせたい。そのあとも、お前の力を借りたいことがいっぱいあって……」



「便利に都合よく使う気なんだ？　釣った魚にエサはあげないタイプ？」



「俺はできるだけ毎日、愛してるって言いたいタイプ」



「そ。……なら、期待しないでおくね」



　ひらひらと手を振り、その背の赤茶色の髪と、大きなリボンを揺らしながら、■■■が紅蠍を伴い、戦場へ飛び込んでいこうとする。

　その、よく見慣れているように、記憶を刺激するリボンにスバルは目を細め、



「――ペ■■！」



「――――」



「ここの氷河の奥に、俺の愛してる子がもう一人いるんだけど、その子を掘り出すのもあとで手伝ってくれる！？」



「死んじゃえ、バーカっ」



　どこまで本気なのか、そう言い放った■■■が、あっかんべーして戦場へ。

　その様子に自分の頭を掻いて、スバルは息を吐く。と、その胸の中から、ベアトリスがスバルの鳩尾を拳でつついて、



「リラックスさせるにしても、下手くそすぎるかしら」



「だったかも。自慢の軽口も、時代の流れに取り残され気味かぁ？」



「わからんのよ。でも……」



「――？」



「■■■と話せた。全部、ここからかしら。台無しにはできんのよ」



　強く、希望という熱を持ったベアトリスの言葉に、スバルは息を詰め、頷く。

　そう、そうだ。ここから、全部ここからなのだ。



　ようやくスバルたちは、スタート地点に立ったに過ぎない。

　四百年の時を超えて、四十年かけて、やっと、今の世界のスタート地点に。



「ベティーたちも加勢するかしら。スバル、準備はいいのよ？」



「当然！　四十年かけて円熟した、俺たちのチームワークと、編み出した十二のオリジナル魔法が火を噴くぜ！」



「噴くかしら！」



　威勢のいい声を上げて、スバルとベアトリスも、猛然と戦場へ駆けていく。

　轟々と紫電纏った雷鳴が鳴り響き、世界の終わりじみた火力の炎が猛り狂い、大地そのものが荒ぶるような金剛石の大嵐が暴れ、数百トンもの雲を自在に落とす『龍』の天罰が降りしきる中、地上最恐の怪物と、魔獣を引き連れた『憂鬱の魔女』がぶつかる戦域。



　そこに、小さく可愛らしい精霊を抱いた、六十過ぎのジジイが駆け込む。

　それはそれこそ命懸けの挑戦に違いないのに――、



「あの四百年の空疎に比べたら、命を捧げるくらい、怖いもんかよ――！！」



　走り、走り、走り、走り続ける。

　残してきてしまったものを、手放してしなったものを、置き去りにするためじゃない。



　託された。渡された。期待され、祈られ、願われた。

　そこに確かにいたみんなと一緒に、このかけがえのない今を、走る。



　たとえ、いつか望んだ理想の未来ではなかったとしても――、





　――ナツキ・スバルは愛する仲間たちと、この異世界を、生きる。





　　　　　　　　　　　　　　　　△▼△▼△▼△







　――神様、仏様、オド・ラグナ様。生涯、愛したことを忘れないと誓います。







*** 『ゼロカラササゲルイセカイセイカツ』Fin





というわけで、今回は九章ＩＦ！　敗北ルートからの分岐です！

具体的に何がどうしてどうなった結果、かは分岐要素が強すぎて細かな設定は出せませんが、内容としては大きく、あの場にいたものたちの選択の結果はこうなっていくのではと。

お察しの通り、九章ラストで消えることになってしまった"彼女"のための物語であり、"彼女"をそうしてしまったものたちのアフターストーリーでもあります。

時間軸的に、本編では扱うことのないだろうキャラクターたちが扱われていて、なかなか書いてて面白みもありましたね。ぼんやり頭にあったけど、膨らむとこうなるかー的な。



ともあれ、お待たせしてしまいましたが、今年もありがとうございました！

おかげさまで、リゼロのアニメの方も四期がこの春から……っていうか、一週間以内に放送開始するので、そっちの方もぜひ、応援よろしくお願いします！

そんじゃまあ、今後もよろしく！　物語を楽しんでいけ！！
