#+title: Re:从零开始的异世界生活 外传 ex2 剑鬼恋歌
#+setupfile: ./setup.setup

* 外传 ex2 剑鬼恋歌

** 一幕

台版 转自 百度贴吧

图源&扫图：殉回仙梦

录入&校对：香草录入组（no3body、皓月星空、zhang960303、蕾姆酱、殉回仙梦、初音酱、极灬光）

1

——呛人的血腥味弥漫在战场上。

直到数个小时前都还是开阔盆地的战场，如今已处处火舌四起，树木被焚烧的声音与怒吼此起彼落。

空气中散发著树木与血肉烧焦的气味，以及足以湿透脚底的血泊腥臭，打乱人类的嗅觉。夕阳，火焰，脚底，世界被染成一片鲜红。

「呜、呃……！」

在这片鲜红世界中，一名拖著打颤双腿的青年双膝跪地。膝盖虽然泡在血泊中，但事到如今已经不会在意这种小事。

因为青年的身体老早被大量的鲜血给污染。

——真的是凄惨无比的样貌。

青年自己选择了挥剑之路，在无数个夜晚梦想有朝一日能名扬战场，从无名小卒一跃而为知名英雄，享受荣华富贵。

太天真了。不管是想法还是梦想，乃至于置身战场的角色，全都想得太美好了。

鲜血、伤口、疼痛、憎恨、刀剑枪炮和尸体，才是战场的法则。

初次上阵，就遇上了即使内战已持续数年，但惨烈程度却是王国内几乎前所未有的激战。

这次的战场指挥官是某个年轻贵族，因为想要建立功勋，所以就一股脑地冲进敌军里，结果败逃，导致战线整个崩溃。

交战双方顿时混杂在一起，形成混战。青年就在这时被魔法给炸到飞出去，丧失了意识。

多重的不幸偶然交叠，青年——格林·法先在战场上落单，于浓厚地飘荡著的「死亡」气息中拖著双脚。

「————」

恢复意识后，身体变得沈重，脚伤逐渐彰显存在，折磨著他。

——从头顶飞过来的火球，将格林与他眼前的地面一同炸开。

只受烧伤和脚伤的自己已算十分幸运，因为格林知道，除了自己以外的队员全都变成了焦炭，而且原本身旁的小队长是小队里头唯一的正骑士。

开战前才刚被他勉励过，自己也对他抱持著尊敬。

可是那个人的性命，如今却被战火轻而易举地烧毁。

「呃！呜呜呜！」

咬紧牙根，试图忘记那名骑士的临终样貌，但决定性的场景却烙印在眼底不断地重复播放，消耗格林的精神。跪下的格林手上还握著一把未曾好好挥过的剑。钢铁制的剑重得让人想扔弃，但身在战场使他不曾想过要放掉剑。即使明知道自己没法战斗亦然。

放下剑，就等于拋弃性命。而死亡不论何时都令人害怕。

「噫——！」

附近传来粗嗓哀嚎，格林一听，喉咙痉挛，当场逃离。

惨叫的发声者不知是敌是友，但格林甚至没力气去确认。

「呼！呼哈！」

现在遇到的东西看在眼中全都像敌人。不只是人，火焰、血泊和风声，对现在的格林来说都像要加害自己。

拖著疼痛的脚，冲进烟尘中。虽然视野极差，却反而让格林心中的混乱稍稍平息。而这消极的判断正确无误，成功躲过烟尘外头的敌兵目光，争取到些微的生存时间。

但是，这样的幸运并不长久。

「找到你啰，人类！」

「哇！哇啊！哇啊啊啊！」

一穿越烟尘，眼前就出现扛著类似大砍刀的敌人。

是亚人。有著结实肌肉和必须仰望的巨大身躯，以及质感宛如岩石的紫色肌肤。

亚人一看到受伤的格林，凶恶的面孔就露出嘲笑。格林从男子嗜虐的双目中，看出那是发现容易猎杀的猎物才会有的眼神。

在阴错阳差下与第一次的死亡擦肩而过，但幸运不会一直持续下去。既然如此，自己的性命在开战之后的哪一处终结不都没两样吗。

可是为什么偏偏要给自己些许茍延残喘的时间？

「——结束了！」

跪下的格林诅咒命运，大砍刀朝他的脑门直挥而下。

已经夺去许多性命的砍刀被黏附的血肉给染成殷红，看样子是没法死得轻松了。在极度茫漠的情况下，这样的感慨掠过格林的脑子。

这么愚蠢的想法，就是自己临终前的最后一瞬间了吗。

——就在这时。

「喝啊啊啊！」

气势十足的吆喝直逼而来，钢铁在眼前撞击出火花。

举起砍刀勉强防御住这一击的亚人边呻吟边后退，一道人影翩然降在格林与亚人之间。

近黑的咖啡色头发摇晃，身上的单薄皮铠溅有大量鲜血，手上样式精美的剑反射火焰的光芒。在惨烈的气氛中，只有那把剑的印象不可解地浮现出来，强烈烙印在格林的眼中。

可是那样的感伤，却在下一秒的交错就被立刻打碎。

「吁——！」

钢铁画出一道弧，银闪在战火中闪耀得更强烈。

伴随锐利吐气飞奔的剑刃，孕育出某种不合时宜的美感。

「啊？」

目瞪口呆的声音，不知是出自格林还是亚人之口。

银光一闪——精湛的斩击割断亚人的脖子，喷血的巨躯转眼间倒卧在地面。

「————」

俯视化为尸骸的亚人，人影用力挥剑甩去血浆。那把剑到底是有多锋利，上头几乎没有附著方才砍死的亚人的血。

「啊、哦……」

看到这一幕，终于自觉到捡回一命。格林立刻冒出想向那人开口的念头。道谢，没错，得跟对方道谢。

亚人是敌人。既然他砍了敌人，那他就是同个阵营的人。是自己的救命恩人。

「那、那个，你……」

格林颤抖的呼唤，招来人影的转头和狐疑的目光。

看到转过来的脸，格林讶异救命恩人比自己所料想的还要年轻许多。对方个子不高，恐怕是因为还在发育期，年纪大概小今年十八岁的格林两、三岁左右。大概才十五岁吧，还只是个少年。

但是，格林却不敢再继续呼唤。并非恐惧在持续、喉头在紧缩，战栗也早已停止。原因无他，出在少年的眼神。

「————」

空虚的目光。不过，那并非意味著少年的心中空无一物。

少年盯著格林的目光并不抱持著任何情感。是这层意义上的空虚。

006

察觉到这点，格林变得无法向少年表达感谢。少年盯著默不作声的格林半晌，但隔没多久就露出对本已兴趣缺缺的事物彻底失去关心的表情，迈开步伐。

「等……！」

虽然什么话都说不出口，但格林抗拒被留在一无所有的战场。

他拼命追著看都不看后头的少年，拒绝被他舍弃。一味地求生，就是现在的格林唯一的心愿。

穿过血洼和烟尘，死命地追著少年直到他脚步停下。

最后，在烟尘散开的地方，闻到呛人作呕的血腥味的同时，格林看到了。

「这、这是……」

那是堆积如山的大量亚人尸首。

全都是被砍杀而死的人，表情全都因痛苦、恐惧或愤怒而扭曲。察觉到他们是被谁给杀死的，格林忍不住颤抖。

「——什么啊。战争就只是这样而已喔。」

仰望天空的少年淡淡地这么说。

「嗯啊。」格林也跟著抬头看天空，发出沙哑微弱的声音。

——空中画出红和蓝的圆形光芒，是通报王国军胜利的信号。

「王国军获胜了……」

目睹毫无真实感的胜利宣告，格林虚弱地说。

小队瓦解，什么也没做只是在战场上转来转去，茍延残喘捡回一命——对只有丢人现眼可言的格林来说，到底是战胜了什么？

能够高声宣扬胜利的，一定只有少年这种人——

「没什么大不了的嘛。」

少年丝毫不察格林的感慨，不满地歪过了头。

2

格林得知少年名叫威尔海姆·托利亚斯，是在对他而言残酷非凡又没立下战功的初征几天后，论功行赏的那时候。

「那个砍掉敌方两名队长人头的士兵，有够年轻的。」

表彰仪式结束，士兵解散后，在王国士兵的营房里，同袍对格林这么说。

他是个把黯淡金发理成平头的男人，名叫托尔塔·威兹利。自格林从军以来，两人感情就不错，也是一同活著挺过初征的战友。

虽然他体格壮硕，却擅长使弓，本事足以发下「会彻底做到后方支援的职责」这样的豪语。事实上，虽是初征，但托尔塔完美地达成了任务。

「真的假的。仪式的时候我们排在最尾端，根本就看不见不是吗。」

「本来是这样啦，但我可是使弓高手喔？视力不好的话根本没法胜任弓手吧。既然是我亲眼所见就绝对不会有错。那个人与其说年轻，不如说还是个小毛头。」

被同袍奚落的托尔塔敲敲眉心，夸耀自己的过人视力。可是听到他的话而聚集起来的人，全都一副不相信的样子，还相视而笑。

会有这种反应也是难怪。托尔塔十九岁，包含十八岁的格林在内，是王国军里头最年少的士兵。要是比托尔塔还年轻，不就才十五、六岁——因内战而兵力不断耗损的现状下，是有可能让这样的孩子当士兵，可是无法想象这种年龄的小孩能够立下战功。

更何况其战果还是敌军队长的首级，就更不可能了。

「真是的，都没人相信啊。」

「欸，托尔塔。你有仔细看清楚那个你说的年轻士兵吗？」

「就说真的是年轻人咧！连格林你都怀疑我吗？我很受伤耶～。我用我这双鹰眼看得一清二楚！虽然不甘心，但那家伙年轻归年轻，本事真的一把罩呀。」

「不，我相信你……」

在周遭不信任的反应下，托尔塔露出闹别扭的神情，不过格林低垂眼帘静静地说。

低头的他脑海里掠过几天前在战场上看到的最后光景——被斩杀且堆积如山的亚人尸体，以及完成这座山的少年剑士。

那种仿佛有什么地方失衡了的氛围，确实存在于与年龄等一切无关的领域内。

一想到那光景，格林到了现在都还止不住战栗。

原本描绘自己在战场上的华丽活跃英姿，在初征之夜就被火给焚烧殆尽了。

还沐浴在燃烧梦想的火光下的，就只有那名少年。

——假如乱世真的会出英雄，那么那名少年可能就是。

「全体注意——！」

「——是！」

更衣室的门被粗暴打开，一道厉声从后头扔出命令。

格林遵从在军旅生活中培养出的习惯，立刻站得直挺挺的，踏响脚步，转身面向门口。不只格林，室内的所有人都这样。

对这规矩的行为满意点头的男子抚摸修剪整齐的胡须。

那张见惯的脸庞属于王国军的正骑士拉札克，年约三十前后，五官轮廓很深，一头绿色短发，平常就以在教导队格外严格而出名。对格林来说是熟面孔，毕竟刚进王国军的前几个礼拜就被他严格操练过。

「就算是平时也不能大意，要培养出敏锐的直觉。一定要时时做好准备。」

「是！谢谢指教！」

面对拉札克的训诫，小队长大声致谢，格林、托尔塔和其他人也跟著唱和。

这是某种约定俗成。初征前和初征后，对教导队的骑士印象会有一百八十度大转变。以前被操练到快吐而恨之入骨的对象，在初征后活著回来的现在只对他感激不尽。在场的所有人都痛切感受到他是为了什么而严格。

「很好。话说回来，平常休息的时候，你们根本不想见到骑士的脸吧。但不好意思，我手头上有必须要快点解决的要事。」

「请问是什么？我们队伍才刚重新编制，所以担心是否能回应您的期待。」

「不用这么拘谨。虽说你们才刚重新编制完打过照面，不过我想在你们队伍里头再加一个人。繁杂手续全都办好了，你们只要接纳就行。」

「这是没关系。请问是优秀的士兵吗？若是累赘的话还请恕我辞退。」

「放心吧。虽然比你们年轻一点，但本事了得。在前一场战役中明明是初征，却带回敌方队长的首级，因此在表彰仪式上还被唱名赏功呢。」

拉札克的回答，不只让格林，连周遭的其他士兵全都一起屏息。

因为跟方才的话题人物形象一致。敏锐察觉到气氛变化的拉札克点头道：

「看样子不需要我多做说明了。进来吧。这里就是你隶属的新队伍。」

一出声叫唤，更衣室的门再度开启，一人走了进来。

是有著茶褐色头发和锐利目光的少年。配给给士兵的制服穿在他身上歪七扭八的，不过他的样子跟可爱新兵等形容词无缘。不会看错的，他就是那名少年。

「他叫威尔海姆·托利亚斯。十五岁，剑术是自学的，不过前景看好。你们可要好好善待他。」

抬头挺胸，默默承受士兵视线的少年——威尔海姆。

介绍完少年，拉札克环视充斥紧张感的更衣室，然后满意点头。

让原本心情松弛的队员绷紧神经、重新做好觉悟，才是他的目的吧。

即使跨越了初征，但新兵就是新兵。在正骑士眼里还是雏鸟。

不过，那一天的邂逅造成的影响却远远超乎拉札克的意料，甚至撼动了王国。

只不过，在这当下，就连两名当事者都还一无所觉。

3

亲龙王国露格尼卡的内战、通称为「亚人战争」的开头，始于两年多前。

以「魔女」的出身为原点，亚人族被歧视了超过四百年。这在露格尼卡也不例外，人类与亚人族之间的关系降至冰点，彼此都谨记不要深入来往，维持著一股微妙的平衡。

而这危险的平衡会瓦解，源自于亚人族的商团与国境警备队的冲突。

商团要通过南方与佛拉基亚帝国之间的国境，却被怀疑涉嫌走私，但其实并没有确切的证据。唯一确定的，就是在激烈冲突下，商团被毁灭。与各地的亚人族有紧密来往的商团被人类歼灭，使得亚人族纷纷拿起武器蜂拥对抗王权，宛如泥沼般的内战于焉开始。

在那之后，徒耗国力的内战持续了两年，人民与士兵都已身心俱疲。

「唉呀，多亏有战争才当得了士兵。我可不是说我喜欢打仗喔，是觉得不愁吃穿这点帮了我大忙。」

一口喝光杯中物，手中杯子用力敲在桌上，嘴巴黏著酒沫的托尔塔笑道。

坐在微醺的他身旁的格林，边小口啜酒边点头。

「还好，这点我也跟你一样。要是没有内战，我根本不会想跑来从军。就算我志愿当兵也会被赶回去吧。」

「毕竟内战前虽然跟佛拉基亚有小争执，但大抵还称得上和平嘛。尽管魔兽时不时作乱……我跟你这种老百姓想要一夕致富的话，果然只能靠打仗了。唯有让武勇声名远播，才叫男子汉嘛。」

「让武勇声名远播吗……」

托尔塔轻松地要求再来一杯啤酒，格林则是缓缓重复他的话。

他那阴沈的侧脸，让托尔塔看不下去直摇头。

「都九死一生撑过初征了，你最近却老是一张苦瓜脸。差不多也该跟那种心情做个了断了吧？觉得很愧对死去的同伴？」

「才不是那样咧。虽然这样讲很薄情，但初征的心情我已经消化掉了。现在只是觉得没法做之前那样的美梦，所以觉得遗憾罢了。」

「美梦？」

「就刚刚托尔塔你说的梦想呀。让武勇声名远播，在战场华丽活跃成为英雄。我也曾经想象过那样璀璨的未来……」

手离开玻璃杯，格林低头看自己的手。

微微颤抖的右手，手掌和手腕都还留有白色的烧伤疤痕。那是初征留下的爪痕，深深地刻在格林的心灵和身体上，永远也不放过他。

「不单单是无法憧憬，我描绘的未来整个崩裂瓦解了。」

「那，就别干士兵了。既然觉得当不了英雄就放弃吧。」

「非常遗憾，就算接受现实，但还是要填饱肚子。不如说，看不见梦想后更能感觉到饥饿。所以说我不会不干，而是会踏实地做下去。」

紧握玻璃杯隐藏手的颤抖，格林对著托尔塔笑。看到他的笑容，瞪大眼睛的托尔塔用力抓头。

「……真是的，很逊耶。不过，很像你会下的决心。好呀，就这么做吧。当英雄的事就交给我。你就在我后头当英雄的帮手吧。」

「可是，你是弓箭手。我才是拿剑站在前面的人耶。」

「这边你应该要老实点头才对啦，不然我很丢脸耶。」

新的啤酒被送来，托尔塔握住杯子举向格林。察觉到他的意图，格林也举起杯子，两个容器碰撞，发出清脆声响。

格林来自王都近郊一座叫弗洛丽的村庄。虽是以街道和王都相连结的小村庄，却是颇有知名度的驿站村。只不过，他和村子重视传统的心态合不来，因此十五岁就离开故乡前往王都。

之后在商店和酒馆当打杂好几年，直到半年前因为内战扩大，急需有人志愿从军，听到消息的格林就奋不顾身地报名了。

——志愿从军的理由不是出自于爱国情操，而是希望成为英雄。原本他就是因为讨厌无聊的生活才离开村庄，因此这种理由就足够他主动加入王国军了。

在那里，他接受拉札克严格的指导操练，然后迎向初征，现在活著在酒馆里喝酒。

托尔塔的经历似乎也雷同。生为商人之家的次男，渴求自由与未来而志愿从军，然后在军队里遇见了格林。

「不过，知道现实的你，和还是决定要成为英雄的我，以初征这经验做出了抉择呀……那个新来的不知道又怎样喔。」

「——你说的新来的，是指威尔海姆吗？」

托尔塔突然提出了少年剑士这个新话题。察觉威尔海姆变成话题的瞬间，格林不希望被托尔塔发现自己心中萌生了微小犹豫。

原因无他，因为威尔海姆就是让格林放弃英雄之梦的人。

「我知道他那个年纪就本事了得，立下的功绩也不是骗人的，事实上，在练兵场操练时，若不是正骑士就无法招架他。」

「他好像不用做新兵要做的军训操练，说是没必要。不愧是拉札克教官认可的人才。老实说，听到他才十五岁的时候，我可是觉得毛骨悚然。」

这是真的。如今还没有完成的少年将来会变成什么样的人，这股不安掠过人心头。

英雄——若以剑斩杀所有来敌，引导王国走向胜利的话，不消多时少年就会被这么称呼吧。

但是，虽说是站在同一阵营，但格林忘不了他在战场上看著自己的眼神。那能说是有资格被授与「英雄」宝座的人吗？

他不会变成更让人害怕恐惧的东西吗？这份不安不曾消失过。

「说的对。确实叫人毛骨悚然。明明才十五，却那么不可爱。」

「……喂，话不是那样讲。」

「本来就是吧？不管邀请几次，那家伙都不跟大伙儿一块吃饭喝酒。有空就是一个劲地在挥剑，而且还从早到晚都不会腻。我看他最后一定会生病。不如说，他本来就有病！」

「有病……你的形容说不定蛮对的。」

托尔塔越说越过份，但格林忍不住同意。「对吧？」获得认同的托尔塔心情大好，格林的忧愁似乎丝毫没有传染给他。

「可是空闲的时间都耗在训练上的威尔海姆，和固定时间会来酒馆泡的我们，也不知道哪边才是对的。」

「不要这样讲嘛。人生当然是享受的那一方赢呀！不是说初代剑圣雷伊德不光只会使剑，也很享受酒和女人吗。英雄就该比任何人都还要享受人生！所以说，仿效他的我们也有英雄器量！」

托尔塔高呼歪理，周围喝醉的酒客也纷纷「对嘛对嘛！」地响应。店内的气氛顿时热闹起来，托尔塔灵活地站上椅子，高举酒杯。

「来吧，朋友们，战友们！为这酒馆即将诞生未来的英雄，干杯！」

「——干杯！」

在托尔塔起头领导下，男人们一齐撞击杯子，放声大笑。

听著酒液泼洒和杯子互撞的高亢声响，格林也拿起杯子碰撞托尔塔推到面前的酒杯，边笑边让自己融入气氛中。

不知为何，就是觉得那一天的酒意发挥得很慢。

4

在酒馆和托尔塔分头，迎著冰冷夜风的格林走向营房。

明天用不著值班，虽然对今晚打算喝到天亮的托尔塔过意不去，但格林实在没有心情享受饮酒。于是摇摇晃晃地走在月光下，冷却热烘烘的身子。

「今天是美丽的月牙……简直就像剑似的。」

该说职业病吗，感觉夜空中的月亮锋利度更甚美感，实在有欠风雅。总之在战争时期，人心也失去了闲情雅致。

没法像以前那样享受酒的美味，是格林跨越初征后的烦恼之一。

「托尔塔真勇敢。他可能真的是做英雄的料。」

每晚都跑去酒馆，跟素不相识的人们饮酒作乐的损友。

规劝他的同时，却又有著羡慕的心情。至少托尔塔在战场上想起初征时绝对不会呆若木鸡。

——另一方面，自己又是怎样？在下一次的战场可以做得让自己满意吗？

这样的不安时时折磨格林的心头。只要闭上眼睛就看到四处冒火的战场，只要睡著就梦到化成焦炭的同伴，就连现在都感受得到万籁俱寂中有临死前的哀嚎与恸哭。

「可是却没有打道回府的觉悟。不当兵的话就什么都不剩了，我是怕那样吧。」

挥别阻止自己的家人，舍弃故乡来到王都。对一成不变的日子感到厌烦而志愿从军，知道死亡的可怕后又想要逃离那段时间。

没有变，自己还是很弱小。怀抱著幼稚的梦想，以为有个地方会认同自己，于是就忘了要努力而在闹别扭。

这一定就是自己现在的生活态度。

「——？」

在回营房的途中，落入自我嫌恶的格林停下脚步。

因为听到声音。营房后方传来微弱的声响。

应该没有哪个白痴敢跑进王国军的营房里偷东西吧，不过现在是战争时期。亚人族搞不好偷偷潜入人类阵营里——觉得自己想太多，但又不能不去确认。

格林触碰带出门的剑的剑柄，蹑手蹑脚地绕到营房后方，悄悄地从建筑物阴影处探出头，确认是什么东西从刚刚就一直在制造声响。

然后，在夜晚的营房后方，看到正专心练剑的少年。

「……威尔海姆？」

踩著泥土，破风之剑化为银闪舞蹈。在月光中，上演一出澄澈得惊人之剑舞的少年，因有人出声而转过头来。被他锐利的目光洞射，格林屏息。

「啊……」

「什么啊，是格林啊。不要打扰我。」

少年扫兴地这么说，格林则是慢了半拍才畏畏缩缩地开口。

「你……你知道我的名字？」

「隶属同个小队，当然会知道吧。你不也知道我的名字吗。还是说，你觉得我是记不住名字的笨蛋？」

「我、我没那样想……只是，我以为你对别人没兴趣。」

「跟兴趣无关，有需要的我就会记住。同队的人的名字要是没记住的话，之后会很麻烦吧。不要让我讲无趣的话。」

虽然这分析正确无比，但没想到会被威尔海姆这么说，因此格林整个人楞住了。

像这样和威尔海姆正常对话，对格林来说是头一次。平常打招呼他不会理睬，因此只有在有必要传达基本事项的时候才会跟他说话。

老实说，之前格林从他身上感受不到人性，完全不觉得他跟自己一样是人类。

「原来你的思考逻辑也是像人类呢。」

「啊～？」

「呜哇，对不起！不是啦，不是那个意思……不，搞不好我没说错。」

想要重讲却又说不出个所以然。

狐疑地看向低头的格林后，威尔海姆的脸上立刻失去对他的兴趣，接著继续举起放下的剑，再度舞剑。

「训练结束后，你也一直这样挥剑吗？」

「对啦。还有不要跟我说话。会害我分心。」

「我们训练结束后，都去酒馆喝酒。我想托尔塔现在也还在喝。」

「是喔。难怪有酒臭味。还有不要跟我说话。」

冷淡回应的威尔海姆加快速度，专心练剑。他的剑舞快到肉眼都追不上，让格林靠著营房墙壁专注凝视。

「为什么你能这么热衷练剑？你都没有其他乐趣吗？」

「没打仗的话可能有吧。可是，现在有战争。与其喝酒抱女人，练剑比较能提高活下去的可能性。」

「那，你是为了想活下去才锻炼自己的？」

「不是。要我说的话，你们才让我觉得不可思议呢。为什么你们不练剑，而是把时间浪费在酒和女人身上？我说的有错吗？」

这段期间，格林发现一件恐怖的事：听不见威尔海姆的剑破风的声音。可能剑气锋利到连空气都没察觉自己被砍中了吧。

只有急促的呼吸，和鞋底摩擦地面的声响。陪衬剑舞的音色就只有这些。

「我不认为有错。可是，不是每个人都像你一样有剑术天分。把一切全都交给剑，会让人承受不下去，所以才会想把心灵寄托在酒和异性上。」

「无论何时，你们就只有借口讲得很棒呢。」

听起来不服输的话，惹来威尔海姆的强烈讽刺。

格林不知道为什么会有这段问答。可能就只是自己一直想要问威尔海姆吧。

问问那个在初征中做出尸骸山堆，还视那种惨状为理所当然、为剑而活的孩子。

「假如你一直是这种不理人的态度，到时在战场上会孤立无援喔。凭你一个人，能干什么？」

「只要挥一剑就能杀一人，挥两剑就是两人。就只是重复这样的行为而已。你说了那么多，在我看来就只是想保护自己而已。」

「还有，你的眼神让我想起来了。——格林，我们在战场上遇过吧。」

威尔海姆中止剑舞，看向站著不动的格林。

他的目光让格林喉咙一紧。——他想起来了。

「变得孤立无援是你的经验谈吧。可是，你知道吧？我在那个战场上也是一个人，而且还立下足以上台接受表扬的功绩，那才是一切吧。无聊透顶。」

「我、我……」

「装作开导人，其实不过是想隐藏自己想逃跑的心情。因为胆小所以想要同伴的话，那你找错人了。弱者就用弱者的方式团结在一起。还是说，你要证明我说的是错的？」

威尔海姆扯动脸颊，剑尖直指声音发颤的格林。

格林知道他在叫自己拔剑。要自己拔出配在腰际的剑，展现自己的气概给他看。可是。

「————」

「连剑都不敢拔吗，胆小鬼。」

低头的格林别说拔剑，连触碰剑柄和挺身面对他都办不到。

威尔海姆一脸失望地扔下那句话，就背对格林再度舞剑。

领悟到威尔海姆的思绪离开自己后，格林长吐一口气，鼓舞颤抖的双腿，像逃跑般离开营房后方。

进入营房，回到自己房间后，一头栽进狭小的床上。以棉被兜头盖住自己，浑身仿佛被淋了一盆冰水般打颤，用力咬牙压抑住情绪。

是气愤还是悲伤，根本分不出来。

只觉得弱小的自己丢人现眼。现在，极度羡慕那名少年的强大。

5

即使那天晚上有了那样的对谈，到了隔天，彼此表面又都恢复平常，继续执行自己的职务。

那或许是格林的特殊才能，只不过是坏的方面。

小队里的平常业务和训练，都跟之前一样会跟威尔海姆打照面。尽管如此，格林没有改变应对他的方式，威尔海姆的态度也一副早就忘了那天晚上的事的样子，就跟平常一样扰乱队上的团结，持续贯彻个人主义。

也因此，小队里头有著看得见和看不见的两枚炸弹。

而这炸弹是不是未爆弹，在格林他们的小队以及王国军与亚人族发生大规模冲突、战火再度燃起时，随之变得明朗。

——决战，在日落之后点燃火苗。

一开始在平原战斗的时候，王国军占有数量上的优势。活用这点一口气逼退反应迟缓的亚人联军，使得战线朝敌军阵营大幅推进。

被编入突击部队的格林他们，也乘著形式大好的气势，接二连三击败亚人。

「上次的混战是搞什么鬼呀。这次赢得可轻松啦！」

拉弓射倒一名敌人的托尔塔，边架起下一支箭矢边兴奋大喊。听到他的声音的格林在前方手持剑与盾牌，混在友军中突击。

王国军士气高昂。敌人节节败退、抵抗虚弱无力，王国军的胜利已近在眼前。身处在压倒性胜利的战场上，格林却无法随心所欲地使唤手脚。

「可恶，这样的话我到底是为了什么……！」

懊悔低喃的格林诅咒自己的脆弱心灵。

这样根本是被我军的奋战所救，自己连一名敌人都没打倒，只是一个劲地用盾牌防御敌人的攻击而已。虽然不能说未对同伴有所贡献，但这种说法无法构成安慰。

要说为什么的话——

「那、那家伙是怎样！？」

惊愕之声发自友军，任谁都被眼前的光景吸引住目光。

驰骋战场，以媲美风的迅速与锐利接二连三地砍掉亚人族的头颅。血花和手脚飞散，钢铁不断地制造断肉切骨的声音和临终惨叫。

「喔喔喔喔喝啊啊啊！」

谱出这一幕的，是急驰宛如箭矢的黑色少年使出的斩击。

他压低身形冲进敌阵，挥舞的剑刃砍杀、突刺亚人，将之变成肉块。敌我双方全都被他锐不可当的势头给惊讶到目瞪口呆。

「跟、跟著威……」

威尔海姆展现奋猛十足的样子，小队长却没法叫大家跟上。原本这是要乘势歼灭敌人的大好时机，可是不只小队长，所有人都认为：

——接近现在的威尔海姆的话，就算是友军也会被他杀死吧。

「队长！这一带已压制完毕！前进吧！」

在大家的目光都被威尔海姆的战斗样貌给吸引的时候，托尔塔充满气势地大喊。

听到的小队长这才回过神，并下达指令要全员朝威尔海姆开辟出的突破口前进。

「多亏威尔海姆那家伙干劲十足，这样子我们也能稍微沾点光分到些功劳了吧？」

在战场优势下，托尔塔狰狞地边笑边说。可是格林的心却无法为战况倒向我军这点感到热血沸腾，反而还觉得脖子后头一阵发寒。

「是说，都不觉得怪怪的吗？」

「蛤～？哪里怪。我们大家的声势正旺不是吗。」

「上次我军明明受到严重损害，为什么这次却突然这么顺利……」

「不是因为我们彻底反省了吗？应该说是上次干指挥官的贵族太无能吧。不就是因为他死了所以才换人带头吗？」

这番发言可是犯下了侮辱长官的罪状，但托尔塔依旧边说边拉弓朝敌人放箭。侧目看著他的格林架起盾牌，却始终没法拂去不安。

紧接著，眼前发出欢呼声。一名身躯格外壮硕的亚人被威尔海姆给砍倒。那应该是敌方队长，他又完成了可以上台接受表彰的战果。

「干得不错嘛，威尔海姆！」

在大家的包围中，只有托尔塔用平常的语气称赞威尔海姆。不过全身浴血的威尔海姆没有答腔，而是突然抬起头。

「……什么气味。」

「废话，身上淋到那么多血当然会臭啊。」

「不对，不是那样。小队长，我有不好的预感。敌人有所企图……」

威尔海姆转头，正在表达意见的时候，地面受到冲击而摇晃。

感觉视野在上下摆动，格林失去平衡倒在地上。周遭的士兵也都纷纷倒地，勉强站得住的就只有连同威尔海姆在内的几个人。

「刚、刚刚是……」

发生了什么事？但没有必要接著说下去。

比冲击力慢一步接近大家的，是突如其来的灼热之风。夹杂土石尘埃的热风扑面而来，眼睛和嘴巴首当其冲。边咳嗽边站起来的时候，怒吼开始交错纷飞。

「快走快走快走！是陷阱！是亚人族的陷阱！他们在地面设了魔法阵等我们上钩！我们会被包围歼灭的！」

「是巴尔加！巴尔加·克罗姆威尔！拿下那家伙的脑袋……不对，先撤退！！」

「有火！火烧过来了！我、我的脚啊——！等等、等我啊——！」

来自四面八方的声音都在告知我方突然陷入劣势。

热浪掀起的烟尘让视野变差，四周陷入恐慌的士兵们全都互相推挤，开始往后退，连格林都差点被撞飞。

「格林！」

格林快跌倒时被托尔塔抓住手，才免于倒地被踩踏的局面。只是军队陷入混乱的状况每分每秒都变得更严重，方才的战胜气氛早已荡然无存。

「陷、陷阱……我们被包围了？为什么突然就……！？」

「看不见周遭啊！可恶！小队长！现在该怎么办！」

在纷飞交错的怒吼中听到危险的只字片语，使得格林的恐惧加深，牙齿不住打颤。托尔塔也一脸可怕的表情，要求小队长下达下一个行动指令。

听到托尔塔的呼喊，双眼瞪得斗大的小队长抖著嘴唇说：

「撤、撤退！我们也撤退，跟其他队伍会合……！」

「不！不能那样！要前进！」

「——啥！？」

威尔海姆咬牙切齿地命令想跟其他队伍一样撤退的小队长。

他举起沾满血的剑，指向方才的行军方向。

「撤退的话就正中敌方下怀！为什么不懂啊！只有前方才有活路！」

「你才是为什么能这样讲！只是想杀敌的话就闭嘴！」

「敌人一开始就设了魔法阵陷阱！假装败退刻意引诱我们到此，就是为了一口气歼灭我们！那些中了陷阱就害怕的家伙惊慌失措地逃跑，根本是正中他们的下怀！」

他的反驳证明了他已经想到更深远的地步，小队长一时之间接不上话。满脸是血的威尔海姆逼近沈默不语的小队长，鬼气逼人地朝他破口大喊。

「要前进！只有前进才有活路！撤退也只会被包围！在包围网缩小巩固之前，我们要突破正面的包围杀出一条路！只能这样！」

「——呃！不、不行就是不行！撤退！就算前进也没有我方的人！在敌阵被孤立的话就跟被围剿没两样！」

虽然威尔海姆咄咄逼人，但小队长咬牙斥退他的意见。

听到答案，威尔海姆用力咬唇到嘴角淌血，同时退后。接著旋转手中的剑，背对整个小队。

「慢著，威尔海姆！不得擅自行动……」

「想逃请自便。只会逃逃逃，逃到最后只有死路一条。我要战斗。战斗到最后活下去。——才不跟你们这些胆小鬼同路。」

不听小队长的制止，威尔海姆愤恨地留下这段话。

他的话让小队成员全都说不出话来，只有格林莫名感慨。

一定是因为只有格林是第二次触及到威尔海姆的愤怒——

「威尔海姆！」

就算被呼喊也不停止，威尔海姆一鼓作气往前冲。

违抗小队长的命令，只身冲入敌阵——这毫无疑问是没得救的选择。

察觉到这点的瞬间，格林鞭策发抖的双腿，跑起来去追他。

「格林！怎么连你都……！」

「不能放著他！我去把威尔海姆带回来！要是他死了就麻烦了！他对王国军可是很重要的人！」

踏著泥土，撑起沈重的身体往前跑。虽然有手伸向格林意图制止，但感觉只是擦过，根本没碰到。

「格林！别死啊！你这个笨蛋！」

「才不会死咧！我可是胆小鬼啊！」

托尔塔豪迈的激励传达给奔跑的格林。

损友的叫喊带给他力气，让他也发出莫名所以的回应。格林顺从胸口的滚烫情感，追著威尔海姆的背后跑。

「————」

气喘吁吁，凝视弥漫的烟尘，踩过同为王国军的尸体，接著马上后悔。

怎么每次都这样！格林感到后悔莫及。不管怎么跑，每次都会后悔自己的选择。可是事到如今，只能撇去后悔拼命跑。

虽然有拿盾牌，但剑不知几时掉了。可能是在第一次的冲击波来袭的时候。没关系。论剑术，跑在前方的少年比自己高明十倍。

鲜血喷溅，哀嚎四起。

要在巨响交错纷飞的战场上找到跟丢的威尔海姆，其实很简单。

爬上山坡，跳过地表的裂缝，避开不知是敌方还是友方的尸体，格林追上了威尔海姆，同时也看到发著淡淡光芒的东西。格林不禁屏息。

仔细一看，眼前的地面微微发光。发光的线条呈现几何图形。

「该不会，这就是魔法阵……？」

毫无魔法天分的格林极少看过玛那光芒。

结晶灯这类一般人都能使用的魔石加工技术只在王都普及。个人要使用魔法，听说只有极少数拥有魔法天赋的天才才有办法。

人类这个种族在魔法才能上劣于亚人族，而王国军的劣势也源自于这次使用的魔法阵陷阱——从听来的片段情报，让格林推敲到这项事实。

因此魔法阵的柔和光芒，反而让格林的后颈感受到前所未有的恐惧。

「呜、唔……这种感觉是什么……好讨厌，快点消失啊……！」

为了擦去爬上来的恐惧，格林用手掌摩擦自己的后颈。

自初征以来就被胆怯附身的自己，身体好几次都像这样表达恐惧。讨厌这样的格林粗鲁地用脚践踏眼前的魔法阵。

顿时，眼前的光芒慢慢变弱，没多久就变成普通的涂鸦。

「搞什么？这样就消失了……」

「喂，格林。」

被人从后方叫唤，吓得格林心脏差点吐出来。回过头，后方是威尔海姆。身上的血色比方才还要浓厚的他，由上而下打量格林，然后牵起嘴角。

「你怎么会在这？小队不是要退向后方吗。」

「因、因为你擅自行动，所以我来阻止你！来，回去吧！一个人在这种地方，就算你本事再了得也……」

「多管闲事。……不过，你还有力气茍延残喘啊。不愧是胆小鬼。」

面对前来制止自己的格林，威尔海姆投以跟那一晚同样的嘲笑。格林忍不住闭上嘴巴。瞪著他脚下的威尔海姆则是皱眉。

「格林，这魔法阵是怎样？」

「……刚刚在发光，觉得有不好的预感就用脚弄掉了。这是陷阱吗？」

「嗯，是啊。曾经是陷阱。在准备发动的期间被你毁了。也就是说。」

威尔海姆的目光变得锐利，紧接著格林觉得脖子后方传来恐怖的寒气，因而瞪大双眼。

下一秒，红色光弹从右手边穿破尘埃，直直朝两人飞来。

「头低下！」

被撞开的格林当场跌坐在地，眼前的威尔海姆挥剑弹开直击而来的光弹，接著又猛然朝光弹射过来的方向挥砍。

纵向劈砍的剑划破飞砂走石，烟尘后方出现一名绿色肌肤的亚人。对方穿著一身长袍，只露出一颗吐著长舌头的头，外观看起来像爬虫类。

小个子亚人朝后跳，只有三根手指的双手再度朝威尔海姆发射光弹。但是从死角发动的奇袭都没能命中了，从正面施放更不可能管用。

威尔海姆翻个身，以最小的动作让光弹擦身而过，然后一口气接近亚人，直接切断躯干，再反手一刀割断脖子。

「威尔海姆！刚刚的亚人是……！」

「这家伙八成就是负责启动这个魔法阵的人。杀了他又毁掉魔法阵，这边的陷阱应该就不会发动了。就用这里做记号，一鼓作气冲到对面！」

踹开亚人的尸体，威尔海姆边甩去血浆边凝视前方。刚好跟小队的移动方向是反方向。格林从后方抓住他的肩膀。

「等一下！既然这个陷阱被毁了，那就可以叫大家回来啦！」

「白痴什么！大军回来又会启动其他陷阱。应该说，他们会在王国军撤退的中央处设下能够一网打尽的陷阱。就算回去了也救不了谁，只会徒增我跟你这两具尸体而已。别开玩笑了！」

抓住他的手被挥开，格林退后的同时喉咙被剑尖抵住。被剑气当成目标，使得全身被恐惧支配。

「想死那你就一个人回去！不想死的话，就挣扎求生吧！」

说完，威尔海姆一口气冲了出去，脚步毫不迟疑。

面对再度拉开距离的背影，格林被迫在短短的一瞬间做出选择。

回去的话，或许能和小队会合。但是，就算回去也有可能如威尔海姆所说，只是中亚人族的陷阱。可是小队那边有大量的王国军，人数的优势不会动摇。威尔海姆的想法也有可能出错，敌方搞不好是等在他前方。一直孤身往前冲，不是只会降低生存机率吗？自己都跟威尔海姆说了这么多，他却一意孤行，就算死了也只能说他是自作自受。

既然如此，选项就成了生死题。是想活下去，还是不想死。

格林他——

「——啊啊啊啊啊啊！！」

发出不明所以的吶喊后，格林朝前方冲刺。

不是朝托尔塔和其他同伴所在的后方，而是朝威尔海姆冲出去的前方。

没有什么理由和根据，就只是顺从本能而已。在这一瞬间，格林脑子里完全没有伙伴意识、使命感、爱国心和对王国的忠诚。

就只有思考要回去还是前进。哪一边比较可怕？格林靠著这个判断来选择自己的路。

跨过光芒消失的魔法阵，边发狂大喊边跑过战场。虽然是很醒目又无可奈何的愚蠢举动，但很幸运的，发疯在战场上一点都不稀奇。

没多久就穿越烟尘，路上奇迹似地都没遇到敌军，格林跑到了一座山丘上。

「嘶呀啊——！」

先是充满气魄的吶喊，接著面前的亚人被纵向一分为二。

甩去剑上的血，威尔海姆接二连三地砍死扑上来的亚人，同时被惊人的血量涂染，边发出僵硬的声音边累积死亡。

那僵硬的声音，和看起来像在笑的浴血表情，带给格林在战场上从未有过的最强烈恶寒，同时道出突然想到的字眼。

「鬼……」

鬼。没错，是鬼。在那边的是正在挥剑的鬼。在战场上砍杀敌人、笑得开怀的鬼。

享受挥剑杀戮的乐趣，像玩乐一样量产死亡的鬼。

——亦即，剑鬼。

「来啊！再来啊！尽管过来！放马过来！我会杀了你们，然后活下去！！」

剑鬼叫喊，每一次的银闪都夺去亚人族的性命。

面前是那样的惨状，格林慢慢转过头，俯瞰山丘下的光景。

在烟雾弥漫的战场上，只有魔法阵的淡淡光芒鲜明异常。

用上双手双脚的指头也数不清的魔法阵，在战场上注入超越人类智慧的力量，以破坏力粉碎愚蠢地被围困的王国军。

热风，地鸣，还有远方被烧红的天空中所回荡的遍野哀嚎——

「……这就是我做的选择的下场吗？」

背后是剑鬼制造的尸山血河。

眼底是被遗弃的同伴的惨叫与叫喊，听来像在诅咒生者。

不知何时格林跪地，双手掩面不停地啜泣。

「对、不起……对不起，对不起，对不起……！」

直至战斗结束，王国军吞下败战苦果并回收友军之前，格林带著哽咽的谢罪以及剑鬼的剑舞和大笑声，都没有中断过。

——撤退的小队以及托尔塔·威兹利都没有回来。

6

卡斯泽尔平原上的决战，初期王国军靠著优势乘胜追击，却中了亚人族的卑鄙陷阱导致前线军队几乎全灭。王国军后退时遭遇了使用魔法阵的包围攻击，全军因此受到极大损害而溃败——在绵长的内战中，王国吃了一场留下纪录的大败仗。

虽然未经确认，但据悉此次决战的亚人联军大参谋为巴尔加·克罗姆威尔。因此这次的损害被视为出自于这号狡猾人物的策略。

由于这场决战出现大量死伤者，因此很多的士兵尸体没能回收，于是由国王直接发表声明，表彰这些英灵的忠诚与爱国情操。

另外，有号人物在这场惨不忍睹的决战中贡献了出类拔萃的战果，因此名声响彻王国军与亚人联军。

那就是被称为剑鬼的威尔海姆·托利亚斯，年仅十五岁的剑术天才少年。

这是为王国内战「亚人战争」——拉开幕帘的第一步。

这场内战，终会成为名留历史的惨烈战争。

** 二幕

1

对威尔海姆·托利亚斯来说，世界的组成极为简单。

这世界绝大部分的事物，都可以用喜欢和讨厌来区分。

而目前眼前的状况对他而言，就是讨厌的事。

「不但在卡斯泽尔平原之役最早突破亚人包围网，还单独和一队亚人族交锋，最后还歼灭该队伍。包含队长在内的人头数有八十八个……哈哈！不愧是王牌呀！」

「说王牌不太妥，但您要表达的意思我十分同意。」

「那不就是赞同吗。不要一一挑语病啦，你这阴险的家伙。」

「因为这是我的职责。」

威尔海姆站得笔挺，而面前的两名男人正在交谈。

宛如具现豪迈爽快词汇的高头大马彪形大汉，和看似神经质的温文儒雅男子，两人都穿著骑士队制服，彰显出他们正骑士的身份。

今天早上，从治疗院出院回到营房，准备去做每日例行事项时被他们逮著，于是落得被人品头论足的下场。

正骑士找自己有何贵干？感到事有蹊跷的威尔海姆不得不警戒他们。而面对直接表露对长官的不信任的少年，两名男子反而越发兴致盎然。

「听说你在战场上很冲锋陷阵呀。在友军发现你之前，你已经抢占敌阵一角大打出手……据说把你带回来的人看到一座尸体山。」

「因为眼前状况过于凄惨加上剑术精湛无比，看到的人全都说『剑鬼现身』呢。」

「剑鬼！剑鬼啊！说得好！吹牛老子不讨厌！为了让名声更加响亮，以后也要尽情作乱喔。与其说是剑鬼，讲剑小鬼还差不多呢！」

听见温文儒雅男这么说，彪形大汉边笑边粗鲁地一把抓住威尔海姆的头。他不只块头大，连手掌也大，轻松就一把抓住威尔海姆整个脑袋。

「从刚刚就一直高高在上地打量别人，到底是想怎样！？」

挥开抓住头的手，威尔海姆轻盈往后跳，接著用危险的目光瞪视对方。彪形大汉甩甩被挥开的手，嘴角上扬。

「对正骑士还敢这样，胆子很大嘛。年轻人就该初生之犊不畏虎。」

「要说年轻的话，少爷也一样吧。虽然长相老成，但连内侧都老掉导致记错真实年龄，哪天就会后悔喔。」

「跟这小鬼比，每个人都是老头啦。纪录上是十五岁……听到没，皮波特！是你的一半！虽然年纪是你的一半，杀敌数量却是好几倍！你应该觉得可耻！」

「我是负责动头脑的嘛。少爷办不到的部分，全都是我在做。」

彪形大汉口沫四溅，温文儒雅男掏出白手帕擦拭自己的脸。他们的对话依旧把威尔海姆撇在一旁，耗尽了少年的耐心。

「如果没事我就先走了。我可不是闲著没事干。」

「你没空？你现在应该是待命中吧。要忙什么？」

「练剑。要是一天没做，就要花三天才能补回。明明挥一次就能斩杀敌人，却变成得挥三次，一点效率都没有。」

威尔海姆冷淡地丢下这句话就转身离开，想赶快去营房后头锻炼。

但是，身后的彪形大汉听到他的回答后却是哈哈大笑。

「听到了吗，皮波特！在那场战役结束后他足足躺了两天！昏倒的家伙一离开床铺就要去练剑，想把睡觉浪费的时间弥补回来！就为了练剑耶！」

「是，我有听到。我本来就觉得少爷很夸张了，但这一位却是超越少爷的大笨蛋呢。」

「你们两个是想一并被我打倒吗？」

管你是正骑士还谁，被人瞧不起到这种地步叫威尔海姆无法忍气吞声。

除此之外还有几天没练到剑的郁闷，使得他口气很不客气。

「很好，老子就是想听这种话。丢人现眼的正骑士们被稍微会点剑术的小鬼头给瞧不起，还让他大摇大摆地离开。这种话铁定会传遍骑士团的。」

但是，面对威尔海姆的瞪视，彪形大汉却是狰狞一笑。他身旁的温文儒雅男缓缓摇头，脸上的单边眼镜反射出不怀好意的光芒。

「虽说少爷叫人伤脑筋，但你也有错。尽管才这么大就剑术造诣了得……不过太得意忘形了。」

——强悍的战意与凛冽的剑气。

两名骑士的气氛骤变，威尔海姆忍不住用舌头湿润嘴唇。

「这才是你们打一开始的目的吧。」

「不要往坏的方面想。有了地位在很多方面都很麻烦。老子可不想在练兵场被人说是仗势欺人，所以放心。老子波尔德·卓格夫在兵戎交会之场是绝对不会做出可耻行径的。」

「就是这样，少爷是直来直往之人，请尽管放心。对了，抱歉没有及早告知。我是波尔德大人的监督者，名为皮波特·阿南西。请多指教。」

彪形大汉·波尔德和温文儒雅男·皮波特接连报上姓名，威尔海姆思索。

看不出他们的用意和想法，但至少知道当前的目的。

而且刚好不脱威尔海姆现在想做的事。

「马上撂倒你，我要回去练剑了。」

「那可不行。因为你搞不好又会躺回病床去！」

威尔海姆踏上石砌通道，前往练兵场。波尔德则是跟他并驾齐驱。

撞出激烈火花的两人身后，是慢慢跟在后头叹气的皮波特。

2

钢铁互相撞击，发出高亢声响，擦出的火花在视野角落闪耀出红光。

在连续的轻快声响下，威尔海姆往前踏出一步，上半身低到掠过地面，和落下来的战斧擦身而过后身形一钻，踩在斧柄上遏止对方下一个动作。

——停滞只有一瞬间，紧接著银光划过，剑尖直抵粗脖。

「——胜负已分。」

「……你这家伙真惊人。」

威尔海姆宣告胜利，被告知败北的波尔德低声沈吟。

威尔海姆额头冒汗，嘴巴弯成武人豪气干云的笑容，深深吐出一口热气，然后放下剑。

他使用的是剑刃未开锋的训练用剑，脚下劈进泥土里的是波尔德擅长使用的武器：又大又长、斧刃同样未开锋的斧枪。尽管两把都是使尽全力殴打的话还是会要人命的东西，但彼此都有能在武器碰到对方前停下来的技术，因此激战结束后无人受伤。

只不过，这个报告仍必须用「引人注目」这个字眼来形容。

「这样子，模拟战中七胜三败，是我赢了。没话说了吧你。」

「主动提出比试，结果却是这样，哪有什么好嘴硬的。哇哈哈！输了就是输了！好久没有输得这么痛快啦！心情好好呀！」

「什么跟什么……」

挑衅对方却得到大笑，搞得威尔海姆皱眉。波尔德拔起劈进地面的战斧扛在肩膀上，然后用力抓理成平头的深蓝色头发。

「你才是要更高兴一点。跟本大爷单挑还赢了。就算在正骑士中，老子也有自负战力可以匹敌近卫骑士。看样子不能说之前输给你的人是窝囊废了呢。」

「因为要是符合条件，那少爷也变窝囊废了。话说回来……原来如此，前途堪虑啊。这么强却才十五岁吗。」

站在练兵场一角观赏两人激战的皮波特走过来这么说。

这种评价早就听腻了，但他的话中却不像其他人那样饱含畏惧和惊叹。不管怎样，败家之犬的感想对威尔海姆而言都是废话。

「不能教训狂妄自大的小鬼头实在遗憾啊。这样的话，下次要再跟更上面的哭看看，派其他的刺客过来吗？」

「那样也不错，不过要拜托到老子这副身躯的话，至少要是神龙波尔卡尼卡这种等级的。要是因为无聊的事被叫出来，老子可会燃烧不完全啊。」

「在变成那样之前先进入主题吧。威尔海姆·托利亚斯。我们接触你的目的，并非假借比试之名动用私刑。不过，也多亏了少爷输多赢少，所以让人无法联想到私刑这一面就是了。」

「你这随从讲话很不留口德耶！哇哈哈哈！」

这对没理解讽刺的主仆让威尔海姆不爽皱眉。

「既然干架不是目的的话……」

「是的。方才不过是请你配合少爷的泄愤行径。那个先不说了，进入主题吧。——通告：威尔海姆·托利亚斯，你今后将隶属于这边这位波尔德·卓格夫大人所率领的卓格夫队，为他效力。」

皮波特这么说，威尔海姆眯起眼睛看向波尔德。

挺著健壮胸膛、扛著战斧的姿态全然就是蛮力型骑士——以前所属的小队已瓦解，威尔海姆对这决定没有意见，只是——

「我初征和第二战，每次上战场队伍就会全灭。你们搞不好也会在下一战死掉喔？」

他闭上一只眼这么问。话语不只傲慢，还侮辱了战死沙场的友军，可是波尔德却只是严肃点头。

「雷多纳斯台地和卡斯泽尔平原之役，这两起战役都有大量死伤。综观大局来看，雷多纳斯之役算是胜利，但卡斯泽尔是毫无疑问的惨败。伤亡人数是史无前例，甚至导致王国军被迫进行大规模的再编制。」

「你的小队也是，除了你和另一人全都阵亡。但不管怎么说你们幸存下来，这代表你们运气……不，是判断精准。」

早已传遍全国的败战内容，以及陷自身于被动的王国军。

被编进突击部队，进入敌军魔法阵效果范围内的队伍绝大部分都被歼灭。据说幸存者就只有做出跟威尔海姆相同判断并突破包围的人，以及在混乱之余逃离效果范围的人，还有真的运气好到身在魔法阵效果范围内却还活下来的人。

「然而，老子的卓格夫队身处最前线，却全员生还。」

「多亏了少爷的野性直觉。虽然看起来是这样的人，但在战场上却是可靠无比。因此，你的担心是多余的。」

自夸的波尔德，和补充不足之处的皮波特。听完，威尔海姆终于理解方才的迂回解说是对自己口出讽刺的回答。

「事先声明，老子当然不是因为运气好才活下来。而是突破敌人的包围，粉碎那些高高在上看人的家伙……」

「这点没什么好怀疑的……你们要说的就这些？」

视沈默为疑虑的波尔德高举斧枪，开始讲述自己在前一仗的威猛事迹时，被威尔海姆打断。

至少不用怀疑波尔德身为军人的实力。虽然战胜对方，但自来到王都之后，他是第一个能让自己身上沾到泥土的人。威尔海姆知道这个叫波尔德的男人是那种在实战更能发挥本领的人。

只不过，这点自己也一样。

「既然事情办完了，我要回去练剑了。只要在营房到卓格夫队露个脸就行了吧。」

「……原来如此，你已经看透了呢。是的，就抱著这样的认知也没关系。卓格夫队经过再编制后，加你和另一人就有二十人。明天晚上要和队员碰个面，请不要翘掉喔。」

「另一人是？」

「跟你同队的幸存者，格林·法先。既是同梯又了解你，对你而言应该也比较好办……虽说你好像不在意。」

威尔海姆立刻就转过身表达没兴趣，然后专注于练剑。看到他那样子，皮波特傻眼，同时死心叹气。

其实，听到早就知道的名字并没有激起威尔海姆一丝感慨，因为格林这名青年根本就没法引起他的兴趣。

窝囊废胆小鬼——格林对威尔海姆来说也是不喜欢的事物之一。

「————」

以失礼的态度结束与上司的对话后，威尔海姆就辛勤地锻炼自己。

波尔德和皮波特两人斜视他一眼后看向彼此。

「就跟传闻一样……不，比传闻更夸张，对剑术痴狂到极点！老子会输给小七岁的小孩，搞不好就是因为斧头还挥得不够多。」

「竟然有超越少爷、连睡眠时间都拿来练习的人才，世界真宽广。光在王都就这样了吗。希望接下来要去见的格林·法先是个普通人。」

波尔德总让人觉得有点失焦的感想，和怀有诸多不安的皮波特，以及对他们不屑一顾、专心一志练剑的威尔海姆。

就旁人来看，卓格夫队的这三人全都是十足的大怪人。

3

——威尔海姆被分到卓格夫队后几天。

第一天和队员打照面，威尔海姆还是跟以前一样冷漠。卓格夫队大部分都是波尔德从自己的领地带来的士兵，因此对波尔德不敬的威尔海姆在队友中风评非常差。不过——

「威尔海姆本事比老子了得！老子都没法教训他了，你们更没法教导这个狂妄小子何谓现实啦。很不痛快对吧！那就晨练啰！」

由于当事人的这句话，因此也就没人对他动用私刑。

其实从隔天开始，像是要做给卓格夫队看似的，连续好几天早晨训练时，威尔海姆和波尔德都在练兵场展开近似互相残杀的模拟战。

还有，跟威尔海姆同一天入队的格林，运用跟在以前的队伍里一样的处世法则，避免在新队伍内激起反感，似乎还变成了皮波特的跟班。

而且还比以前更加避免与威尔海姆打照面，有时候还会眼神涣散到让人以为他哪里不对劲，不过那也不足以勾起威尔海姆的兴趣。

之前的队伍把自己当疙瘩，现在的队伍则是过度干涉自己，但两者对威尔海姆来说都是厌烦的事物。

本来，不管锻炼还是任何事，他都喜欢一个人完成。

跟波尔德的模拟战也是，被挑战几次后就看穿了对方的呼吸与习惯，因此战绩方面自己压倒性胜利的次数变得越来越多，使得威尔海姆觉得跟同一个对手重复交锋根本毫无意义。

在战场上兵戎相见，对决只会有一次——不可能有第二次。

要是心里萌生「这是训练」这种天真想法，那关键时刻就不可能专注一致。保留实力进行锻炼，但面对对象时却很想真的砍下去。这种念头不是只有一、两次，还不如一个人锻炼，就不会这么绑手绑脚了。

「——我想上战场。」

并不是想砍人，也不是想夺取性命。就只是想练剑而已。

因为自己挥剑的本愿，就寄宿在赌上性命的战场、夺取他人性命的剑上。

就这样怀抱著郁郁寡欢的心情，在王都度过几个礼拜——剑鬼再度被给予踏上败战之地的机会，得以邂逅新的敌人。

4

——从王都前往卡斯泽尔，搭乘龙车约要八个钟头。

卓格夫队每十人一小队，分乘两辆龙车。以前后包夹的形式，中间夹著一辆护送要人的龙车——总计三辆龙车自王都出发。

「尽量开心吧！因为我们的勇猛获得肯定，因此被授与特殊任务。地点在卡斯泽尔平原！担任某个重要人物的护卫一同前往平原……这是很光荣的事！」

执行这次的任务时，波尔德兴奋地这么说。而皮波特边矫正单边眼镜的位置，边补充说明。

「好像是在魔法方面有非凡见识的专家。王国的要职一直以来都欠缺精通魔法的术师担任，所以在与擅长使用玛那的亚人战斗时才会惨败。前些日子的大败仗就是沈重的学费，强迫国家了解到这方面的认知不足会造成致命性的伤害。」

「说是想调查敌军用在包围歼灭战的魔法阵。虽然效果消失了，但还是想实地勘查看看。还以为魔法使者都是窝在屋子里的没骨气家伙，想不到比老子想得还要有气概。」

波尔德莫名感动地总结发言，不过难得威尔海姆也有同感。

不是靠钢铁而是仰赖玛那的人，不会知晓活著的充实感吧。

前往平原的三辆龙车——走前头的龙车搭载著波尔德和皮波特及另外八人，殿后的龙车则有威尔海姆和格林等十人。中间的护送用龙车里头除了坐著要人，还有非卓格夫队的正骑士陪同。

只是护卫一个人，这种战力未免太过夸张，但这也代表此次的作战备受重视。

话虽如此，对威尔海姆来说，不管是护卫对象还是作战的详细内容，这些一点都不重要。对他而言，重要的就只有战斗结束的平原上是否还有堪让自己举剑劈砍的对象。

不过很遗憾的，这次的任务恐怕难以满足这份期待。威尔海姆心想。

因此他毫无干劲，心情十分浮躁。

「喂，格林。你脸色很糟，没事吧？」

原本整个人靠在座位上靠冥想练剑的威尔海姆，被这话给拉回现实。看过去，被塞在狭小车厢内排排坐的队伍里，脸色铁青的格林正被身旁的队员摇晃肩膀。

惨白，格林的面颊只能这样形容。而且原因绝对不是晕车，因为地龙的「除风加持」还有在运作。

恐怕是精神方面的问题——而且还跟这次的目的地有关。

「我、我没事。只是觉得有点不舒服……马上就会好了……」

「难说喔。胆小这种病是没药医也没得救的。那么麻烦的病，靠你自己有办法好起来吗？那是只要活著就会一直跟著你的老毛病吧。」

「——呃。」

逞强的样子惹得威尔海姆烦躁，忍不住插嘴讽刺。

顿时，格林一脸不甘。平常温顺柔弱的表情转为愤怒得像要咬人一样，瞪著威尔海姆。

「你才是，很淡定呢。明知道接下来要去的地方是哪里。」

「少要求我的反应要跟你一样。弱不禁风到小便没人陪就没法撒尿的人就只有你。」

「那是我们的队伍死掉的地方！为此悲伤哪里有错了！」

「你根本不是在为他人的死而难过，只是抱著大腿觉得自己很可怜罢了。想到死去的队友，心想还好没变成他们那样，但又怕自己搞不好明天就走上一样的路。先讲清楚，要说认识的人死掉的数字，我跟你是差不多的。」

两人都固执己见，彼此的争论毫无交集。

心情焦躁不耐，使得威尔海姆今天对格林的态度特别看不顺眼。格林一副想要朝倚著爱剑的威尔海姆飞扑过去的样子。

「够了吧！威尔海姆你说得太过份了！」

但是，互相瞪视到最后，是被受不了他们吵架的队员怒吼给打断的。

原本坐在正对面的格林换了座位，威尔海姆这才沈浸在没有打扰的冥想中。在气氛尴尬的龙车里，感到沈闷的队员们只能焦急盼望尽快抵达目的地。

终于，当旭日东升的太阳到达天空正中央时，三辆龙车在没出大问题的情况下抵达目的地卡斯泽尔平原。

「老子知道这段时间的确是会坐到屁股痛，但你们的脸色还真差呢。」

下了龙车，在平原会合整队后，波尔德望著队员的脸表达不解。

前后两辆龙车在路上的气氛很明显的不同。殿后的龙车上，造成队员一脸疲惫的两名元凶因为列队的关系，虽然相邻，却用不著对上眼。

「老子不知道发生啥事，但我们的目的从这边才要正式开始，所以别让人看到你们疲惫的样子。给老子抬头挺胸——！接下来要招待客人！慎重点！」

在波尔德的厉声号令下，队员们忘了一秒前的状态，利落地整队和挺直脊梁。

看著他们踩踏地面，排成两排整齐队伍后，波尔德满意点头，朝身旁的皮波特使眼色。接到信号的皮波特打开护卫对象搭乘的龙车车门，让里头的人踩在卡斯泽尔平原的土地上。然后——

「真希望各位不要那么夸张。被这么多勇猛剽悍的男人一起注视，身为女人的我——会有点害怕的。」

用轻薄语气这么开玩笑的人缩了缩肩膀。

长至肩膀的蓝色秀发，宛如瓷器的白皙肌肤，长袍衣摆快要拖地，而朝前敞开的袍子下方以男性军装裹著颇具起伏的肉体。知道要前往何处，因此脸上只施以淡妆——但蛊惑他人的美貌依旧征服男人的目光。其中最具魅力的就是该人物的异色瞳：一黄一蓝，像是要把人吸进去的瞳孔。

没听说护卫对象是女性，因此队伍一片惊讶。

看到他们的反应，女性就像恶作剧成功的小孩一样灿烂微笑。

「我是罗兹瓦尔·J·梅札斯。目前担任王国境内稀少的宫廷魔导师……如各位所见，就是个弱女子。今天请多多指教～啰。」

见到娇媚一笑的女子——自称罗兹瓦尔的人，威尔海姆立刻决定了对待她的态度：把她归在不喜欢的类别里。

「是的——如外表所见，梅札斯女士是聪明的女性。以少爷为首的卓格夫队大多都是粗鄙之人，诸位还请留意别做出失礼之举。」

皮波特朝著不到大声嚷嚷，但表现出些微动摇的队员们如此叮咛。结果听到的罗兹瓦尔浅浅一笑，说：

「唉哟～说是这么说，但太绑手绑脚的话，连普通的实力都没法发挥了吧？隐瞒性别到现在才讲这种话，人家很过意不去，不过各位像平常一样就行了。梅札斯家除了有每一代当家都要继承『罗兹瓦尔』这个男性名字的特殊传统外，就只是支旁系贵族罢～了。」

「既然梅札斯女士这么说了。诸位，麻烦妥善应对。」

罗兹瓦尔这么要求，皮波特便重新下达指令。当然，这边说的「妥善应对」指的就是「给我展现顶级的绅士礼仪」的意思。叫人只能叹气。

在其他队员正经八百响应的时候，威尔海姆感觉到龙车内还有其他人。那个人估算对话结束，才从罗兹瓦尔身后翩然下车。

这位也是女性。身穿女性用轻铠，腰间佩著一把长剑。年龄超过十五，但不到二十，虽然长得标致，但眼中的严肃气息给人难以亲近的印象。

女剑士的美丽金色头发剪得短短的，还释放出带刺剑气。

007

「各～位，这一位是与我同行的专属护卫卡萝·雷玫迪斯小姐。是位剑术了得的女剑士，还请和她好好相处。」

「您的好意我心领了，梅札斯卿。反正只有今天会碰面……我找不到熟悉彼此的必要和理由。」

被介绍的卡萝跟罗兹瓦尔成反比，态度毫无从容。不知道是紧张还是亢奋，反正就是欠了几分沈著。

「……两个都是女的啊。」

「——喂，那边那个男的！」

听到一脸厌烦的威尔海姆的低喃，卡萝翘起眼尾。她一副像是要立刻拔剑的样子逼近威尔海姆。

「你，胆敢用性别侮辱我？粗心大意小心吃闷亏。」

「少在那边大呼小叫。明明是你自己最在意，才会有这种反应吧。而且我的工作是担任那边那个女人的护卫，用不著讨你欢心。」

「适、适可而止吧，威尔海姆！」

介入互瞪的两人之间，格林抖著声音制止威尔海姆。威尔海姆挑眉回应，格林气得大骂：

「我是不知道你在不爽什么，但龙车上的事就已经过头了，现在还跟协助者吵架……你不知道你给队长和副官添麻烦了吗！」，

听到格林的话，深感赞同的其他队员也瞪向威尔海姆。平常就态度欠佳，因此形势对威尔海姆完全不利。

「……抱歉喔。」

就算争论也辩不过，因此威尔海姆背过头，恶形恶状地道歉。对此格林抚摸胸膛，然后朝站在身后的卡萝低头致歉。

「非常对不起。我们会好好念他一顿的……」

「——请务必。我也不希望让王国子民流无谓的血。」

卡萝退下，原本一触即发的气氛总算收敛。接著卓格夫队重新整队，而嘻皮笑脸看著事态发展至此的波尔德挺起胸膛说：

「好！那么，接下来分三队。一队和梅札斯女史同行，在女史检查魔法阵的时候护卫女史。剩下的分两队，确保周边安全，提防洗劫尸体的不法之徒和亚人残党。在这边死掉可一点都不有趣喔！」

「那个～插个嘴可以——吗？」

罗兹瓦尔朝著干劲十足准备要编队的波尔德举手，说。

「我对你们的编队，只有一个任性要求。」

「您说任性要求吗？如果可以办到，倒是无所谓。」

「——刚刚那边那个少年，麻烦让他跟我同行。」

罗兹瓦尔笑了，手直指威尔海姆。

「那样子对我和对大家来说，一定都会是好～结果喔。」

这实在是让大家百思不得其解的要求。

5

对大家来说都是好结果。罗兹瓦尔用了这样的开场白，但她口中的「大家」似乎不包含自己。对此威尔海姆咂嘴。

既然是此次任务的重要人物罗兹瓦尔的要求，卓格夫队就没有不答应的选项。想当然耳，既然威尔海姆被挑选要跟罗兹瓦尔同行，那就顺便加上跟他处不来的格林。

罗兹瓦尔及其护卫卡萝，以及威尔海姆和格林，再加上两名队员，这六人就是探访平原上的魔法阵的中央队人员。其他两队分别由波尔德和皮波特带队，确保周围的安全。

「一脸期望落空的样子——呢。」

威尔海姆走在队伍前头充当先锋警戒，以此作为最低限度的抵抗，不过敏锐张开的警戒网没有捕捉到任何气息。顺带一提，对好不容易拿出干劲的威尔海姆来说，罗兹瓦尔一直开心地来搭话是最讨厌的事了。

「你——就那么想砍人吗？」

「不要把别人讲得像是人格有问题。我不是想砍人。只是想和有砍杀价值的对象互砍。若不是要和你同行，本来有这种可能性的。」

「你的答案，就足以说明你一只脚已经踏进人格有问题的行列了。而且就算警戒周遭真的有挥剑的机会，终究也只是开路而已……我不认为那样就能满足你。」

「不要讲得一副很懂我的样子。你这个来历不明的女人。」

「人很——老实呢。我不讨厌这样的男生喔。」

罗兹瓦尔手掩著嘴笑，威尔海姆则一直是张苦瓜脸。

周围没有异常，但目前也没有成果。卡斯泽尔平原的地形因之前的决战而改变；树木被砍倒，翠绿大地烧成焦黑，处处都有破损的武器和失去主人的铠甲，留下鲜明的战争爪痕。

「不觉得很凄惨吗？」

「不会。」

「这——样啊。你是那种人呢。」

「……你也是那种人啊。」

「唉——呀唉呀。被反将一军——了呢。」

不晓得罗兹瓦尔是否讨厌沈默，只要抓到空档就搭话。应付她也成了威尔海姆的不满火种。

不能轻忽大意的女人，这是威尔海姆对罗兹瓦尔的评价。从站姿来看就知道卡萝也是武艺精湛之人，但值得警戒的就只有深不可测的罗兹瓦尔。

虽然任务解说时说她是魔法专家，可是她这个人不可能就这么简单。

附带一提，对无礼的威尔海姆最反感的卡萝，始终由格林负责应付。察觉到只要放著这两人不管就会起争执的格林，一直跟卡萝对话，是因为他宁可把矛头锁定卡萝也不想对准威尔海姆。

看他们聊得很开的样子，威尔海姆也觉得轻松许多。

「所以说，今天的护卫其实不是由卡萝小姐担任啰？」

「是的。原本这个任务是由我侍奉的长官负责……不过因为有太多事要忙，才由我代理。也因此给梅札斯卿增添不便。」

「怎么会呢，卡萝小姐有哪里不好吗？」

「不是的。是因为我根本不及原本负责护卫的那位大人脚边。这次的代理安排，当事人一定是最难受的……」

卡萝的声音里头有忧虑，格林烦恼著该怎么接续话题。

话题要是能够尽量拉长就好了。只要威尔海姆不要扔出火星，自己就用不著跟他有所牵扯。

只不过有点在意是哪个人武艺高明到超越卡萝。其实有可能卡萝只是谦虚，才捧高那号人物——

「话说，你叫威尔海姆——是吧？」

「……嗯，对。」

「既然你刚刚夸下海口，那当然是本事了得——吧？」

「————」

「你不自夸吗？算～了，队长和副官马上就把最重要的职责交给你，光从这点来看就知道你备受信赖～呢。所以说，我很期待喔。」

不睬沈默的威尔海姆，罗兹瓦尔手负身后交握，踩著雀跃的脚步。她心情好到让人以为她会哼起歌来，不过她只是凝视周围。

「因为似乎快到目的地了呢。」

罗兹瓦尔才说完，一行人就来到山丘上。前方是往下的斜坡，凝神细看的话，上头有浅浅的几何图形。

被踩得支离破碎，一部份甚至被泥土掩埋，不过那就是决战当天威尔海姆也有看到的魔法阵的下场。

「好——啦，会让我看到怎样的工夫呢。」

看到魔法阵残骸的同时，罗兹瓦尔迅速滑下山坡。卡萝连忙紧随在后，格林也紧紧跟上。威尔海姆耸肩，和另外两名队员一同在山丘上警戒周围。

话虽如此，在威尔海姆的警戒下，丝毫没有生物的气息接近。波尔德他们要是离得远的话就完全不知道他们位置在哪，还真是无聊的时间。

「……原来如此。听到的时候就有想到会是这样，这果然是花了相当多的时间来设置的术式。不管是拟定战术的人还是执行的人，要是不精通魔法，可办不到～呢。这样看来，王国恐怕是岌岌可危。」

「是、是这样吗？这是那么危险的魔法……」

「这个单一魔法阵本身的危险性就不用说了，问题在于敌方阵营里头出类拔萃的魔法使者不只——一人。在整个战场铺设魔法阵，从构想来看就已经很反常了……但同样的手法，也就可以套用在其他地方——啰。」

「不会吧……！？」

格林对罗兹瓦尔的推测怕得要命。明明就只是猜测却吓成这样，这也算是一种才能吧。他实在是不适合当士兵。

可能恶寒没有消失吧，格林边摩娑脖子后方，边仔细地环顾周围，然后顺便朝威尔海姆那边叫喊。

「威尔海姆！有什么可疑的吗！？」

「哪有什么可疑的。是你自己要畏惧看不见的东西……」

随口回应拼命要求的格林，威尔海姆把视线撇向山丘下——破风箭矢贯穿大气，直直逼近蹲下来的罗兹瓦尔。

「——唔！」

判断仅在一瞬间，而且行动以秒计算。

威尔海姆以肉眼追不上的速度扔出腰部的爱剑。如疾风飞驰的剑刺进罗兹瓦尔脚边，剑腹代替她承受箭矢的攻击。

铿锵一声，箭矢弹开，在场所有人立刻警觉到有人偷袭。

但是为什么——明明威尔海姆有所警戒，却感受不到任何气息。

「敌人来袭！快防御！」

威尔海姆边叫边跳下山丘，拔起插进地面的爱剑做出防御，眼角余光扫到卡萝和格林也都架起自己的剑。叫慢了一拍才想下来的队员们留在上头，威尔海姆扫视四周。

——然后，看到了。

「……那是……」

山丘对面有个单膝跪地拉弓的人影。对方慢慢地把箭矢安在弓上，毫不犹豫地就朝这边放箭。

「——哼！」

砍断飞过来的箭矢，威尔海姆瞪著对方。身旁的格林却一脸不可置信地说：

「托、托尔塔……？」

他呼唤了面目全非，还朝战友拉弓射箭，曾是托尔塔·威兹利的东西。

——托尔塔的样子已经让人不忍卒睹。

脸颊有一半的肉脱落，骨头和眼球整个裸露出来，遍布全身的伤口溢出尸水和白蛆，腐肉只被破布和残破铠甲包裹。连握弓的手指都缺了好几根，看起来光是要维持人形都很勉强。

「尸体在动……？」

拔出长剑的卡萝面色铁青地仰望化为尸首的托尔塔。再加上诡异恶心的外表，完全超乎了常识。即便如此，卡萝跟身边面色已经超越苍白、随时都快晕倒的格林比起来，还算不错了。

「喂，魔法使者。……那也是一种魔法吗？」

「看到尸体会动——还这么冷静。那具尸首不是你认识的人吗？」

「跟死掉的家伙就是缘分已尽。所以我没有认识的尸体。」

「原来如此，很棒的意见。然后是你的问题……可以说是，也可以说不是。这不是魔法的——领域。——是咒术。」

罗兹瓦尔装模作样的答案让威尔海姆皱眉。但是，没有时间去追问。因为敌人不是只有托尔塔。

「————」

周围的地面隆起，会动的尸体伴随著破土声接二连三现身。有王国军士兵的尸体，也有亚人族的尸体，看样子这咒术不挑尸体的种族。

尸骸士兵——尸兵的状况都不算完好，但以破百的数量涌过来的话就是超乎想象的暴力了。威尔海姆咂嘴，改变位置，让罗兹瓦尔站在阵形中心，自己、卡萝和格林三人包围住她。

「唉——呀，想不到你意外贴心。还以为你会一个人冲锋陷阵咧。」

「我是很想，但要是让你死了就麻烦了。后面我照顾不到，你就祈祷那两个人派得上用场吧。」

「什么！？你、你这家伙竟然口出恶言……！」

「卡萝小姐！他们过来了！」

以格林的惨叫为信号，尸兵从四面八方一起扑过来。

正面逼近威尔海姆的是扛著大剑的大个子尸兵，还有手无寸铁也没脑袋，只有双手朝前伸长的尸兵。因为是尸体，也不知道要破坏到什么地步才能造成致命伤。然而……

「既然没有头还会动的话——」

银色闪光切断挥舞大剑的尸兵双臂，再反手一剑将身体分成上下两块，最后从胯下将摇摇欲坠的胴体纵向分为两半。威尔海姆边确认被分成六份散落开来的尸兵一动也不动，同时使出两记斜斩将手无寸铁的尸兵给分成四半，粉碎他再战的机会。

「比活著的时候多砍几刀就会死了。」

「真惊人的判断标准～呢。」

威尔海姆这么判断，身后的罗兹瓦尔苦笑。

瞥一眼背后，卡萝一口气打倒正面攻过来的三具尸兵，格林持盾支持掩护她，战线十分稳定。留在丘陵上的两人也是卓格夫队的勇士，携手合作对抗尸兵，轻易将之击倒。

尸兵的战斗力不高。不管生前是多么厉害的士兵，变成尸体的现在，战斗力全都在水准之下。其实根本不需使出实力。

「就只是脏了活人的剑。魔法使者，元凶在哪？」

「被信任的感觉不坏，但就——算是我也不知道喔。不过，能够操纵这等数量，应该不会太远吧。」

「这样啊。——那么。」

只要不移动，附近的尸体终究会被歼灭殆尽。只要没了尸体，就无法补充尸兵。但是，事情就这样落幕的话，让人咽不下这口气。

「————」

弹开尸兵的攻击，挥出斩击击倒他。威尔海姆仔细观察散发腐臭、滴著尸水的尸兵的动作后，发现：

有两具尸兵没有移动位置，就是站著不动——于是威尔海姆朝他们中间冲过去。

简直就像在保护什么，两具尸兵朝著冲锋陷阵的威尔海姆扑过去。但是，一招纵劈和踢技就让两具尸兵回归尸体，剑接著刺向他们所保护的空间——

「——唔呃！」

一瞬间，熊熊烈火在眼前烧起，威尔海姆立刻往后飞跃。

逼不得已之下以剑击砍破逼近而来的火焰，著地的威尔海姆面前的空间扭曲，一道娇小人影诞生，落在原本什么都没有的地方。

——目睹到那存在的瞬间，威尔海姆全身感到毛骨悚然。

「……进行得不顺利呢。」

细微的声音，来自于披著白袍的娇小少女。

长长的浅红色头发，脸蛋小巧玲珑，年约十岁左右的女孩。除去光脚和浑身上下仅披一件破烂袍子外，看起来就是个态度从容的普通少女。

正因如此，潜伏在少女皮下的是一只诡异怪物，这个事实叫人害怕。

之所以一眼就知道对方的异常，在于压倒性的阴森之气从女孩体内源源涌出。

「那怪物是怎么回事……！？」

「怪物……我果然是不完美的。离母亲还很远的失败品。」

威尔海姆脱口而出的话，惹来女孩蹙眉悲叹。然而，却有人对她的话产生剧烈反应。

「——母亲？可以不要开玩笑吗。像你这种让人看不下去的瑕疵品，就算只有一部份像老师，那种话我都说——不出口。」

往前踏出一步的罗兹瓦尔激动驳斥女孩的话。原本吊儿郎当又愉快的态度，转眼间就变成愤怒，怒目瞪著少女。

接收到罗兹瓦尔的愤怒，女孩困惑不已。

「伤脑筋。你是？」

「要消灭你的人。赌上我的一切，我说到做到。」

「越来越叫人伤脑筋。看样子，是认真的呢。」

相较于毫无感情的女孩，罗兹瓦尔的眼神越来越严厉。被瞪的女孩稍微看看周围，便以手比向尸兵。

「很幸运的，想要的东西已经回收了，没必要招惹麻烦。——容我先行告辞。之后的事，要·深·思·熟·虑。」

「哪能让你逃走——」

女孩一低头，身体就当场腾空浮起。不打算让她逃跑的威尔海姆冲过去，但却被周围的尸兵阻挡。

「少挡路……唔！？」

尸兵避开砍过来的剑后进入追击态势，使得威尔海姆微微一惊。好快。跟方才操纵的尸兵等级完全不同。

仔细一看，周围的尸兵动作全都变得顺畅流利。就算是威尔海姆也难以一击杀死他们，不过也不至于构成威胁。可是——

「呜、呜啊啊啊！」

「这些家伙突然……这些数量，顶不住的……！」

格林惨叫，光是掩护都来不及的卡萝可能也因为受伤了而导致动作变慢。再这样下去，除了威尔海姆以外的人早晚都会被尸海战术给击溃。

「尸兵数量越少，残存的个体就越强悍。恐怕在他们之中，有被称为司令塔的尸兵。只要打倒他，应该就能改变这状况吧。」

「怎么判断？」

「司令塔的动作应该不一样。要是能看出来的话……就好了。」

罗兹瓦尔提出突破现状的策略，但在混战之际要找出司令塔尸兵实在是困难至极。

既然如此，只好朝山丘上的两人求救了。才抬起头，迅猛的箭矢就贯穿丘陵上一名队员的膝盖，而且力道大到让他整个人都飞了出去。

办到这点的弓手，就是跟生前一样彻底做好支持角色的托尔塔。与大块头身材不相称的锐利目光，以及能够拉动长大弓矢的力气和精准度，使得他在小队中可说是出类拔萃。

再次见证那样的姿态，威尔海姆的直觉下了判断。

与生前一模一样的卓越技能——司令塔就是托尔塔·威兹利。

「我选了一个对你来说不好打倒的对手。因为我观察过你。」

仿佛要印证威尔海姆的结论，要离开的女孩淡淡地留下这段邪恶的话。

威尔海姆咬牙切齿。他清楚与托尔塔之间的尸兵数量，并用怒火剑刃拆解眼前的尸兵。

不够。自己冲过去的话，确实可以打倒托尔塔。但是这样一来就会离开岗位，这段期间剩下的三人就会被尸兵杀死。

若要撑住战线，还能打倒托尔塔的话——

「格林！你去干掉托尔塔！那家伙就是司令塔！」

眼下这战场地形就像个碗，一行人就置身在碗底，战力方面最派不上用场的人是格林。现状是冲著自己来的尸兵很多，因此就算少了格林也最不会影响战斗力。

听到威尔海姆这样怒喊，持盾的格林仰视托尔塔。但在看到借尸还魂的队友后，他不停摇头。

「我、我办不到啦。不可能的！」

「在你到他那之前，先让那女的掩护你！给我冲上去，砍断他的脖子！不过是没有护卫的弓手，只要靠近就杀得死！」

「这不是赢不赢得了的问题！你是要我杀死朋友吗！？」

格林一脸拼命，边承受敌人攻击边哭喊。

格林和托尔塔是好朋友，这点威尔海姆也知道。也知道在小队的其他同伴全灭之后，格林就没法再挥剑。可是他却——

「那又怎样！」

「那又怎样！？还能有怎样，就是那样啊！？我无法对朋友下手！我……我跟你不一样！我做不到！」

「他哪里像是你朋友了。你是哭到看不见前面了吗！？你朋友早就死了。在那边的是尸体。犹豫仿徨、不该出现在这的尸体！」

看到卡萝失去平衡，威尔海姆为了保护她们横扫尸兵。飞散的尸体碎片淋满全身，威尔海姆朝蹲下的格林背部一脚踹去，破口大喊。

「做不到做不到，你们每次都这样！就只会拼命找做不到的理由！有空在那边浪费口水，还不如动手去做！与其讲些无聊的屁话，用剑砍杀敌人还比较快解决事情！」

「————」

强塞霸道理论的威尔海姆，边咆哮边斩杀尸兵。

感受到身后的格林站起来。

他面朝下，喃喃自语。

「他可能是托尔塔。」

「那又怎样！」

「我怕挥剑怕得不得了。」

「那又怎样！」

「幸存下来，让我一直觉得很对不起他们！」

「那又怎样！」

「——我不想死！？」

背对背互相大叫后，格林把盾牌架在前方开始奔跑。卡萝连忙跟上掩护他，威尔海姆则是拼命肆虐好保护罗兹瓦尔。

冲上山坡，用盾牌挡去尸兵的突击，格林一口气逼近托尔塔。

对方拉满弓放箭。格林用盾牌扎实地承受看过无数次的箭击，然后挥动至今为止一次也没挥过的剑。

「我要活下去——」

008

战战兢兢的剑挥过去，砍断托尔塔的脖子。

至此，战况已定。

6

「这个——是最后一只了——！」

战斧以惊人威力敲烂尸兵，将之化为不成原形的肉块。接著波尔德边剥除飞散黏到铠甲上的肉片，边扛起斧枪长吐一口气。

「很～好！战斗结束！死掉的人答有！」

「不可能。而且很幸运的，全员都活著。」

波尔德吆喝，确认全体队员没事的皮波特这么回应。

尸兵来袭，将之击破的波尔德他们得以会合，是在格林打倒司令塔托尔塔导致其他尸兵弱化后的事。

展现迅猛活跃的威尔海姆和受伤的卡萝也都平安生还，被箭矢命中的队员也活著，卓格夫队奇迹似地在没有少人的情况下结束战斗。

「唉呀唉呀唉——呀，真是太棒了。多归了你们才能活下来呢。」

战斗结束告一个段落后，罗兹瓦尔称赞当场坐下来的队员们。这时，皮波特重新面向她，边矫正单边眼镜的位置边说：

「请问，梅札斯女史。这些尸兵到底是怎么一回事？」

「关于这点嘛——事态变得严重了。得尽早回王城报告发生最叫人担忧的事项——了呢。」

「最叫人担忧的事项吗……？」

听到这夸张的字眼，皮波特皱眉，罗兹瓦尔摇著蓝色的头发点头。听到的波尔德也走过来，双手抱胸道：

「言过其实。不过就是会动的尸体，又不是什么了不起的敌人。有什么好称得上危险的？」

「尸兵只是开始。问题在于策动尸体的元凶，以及张设魔法阵的术师。我认为这些恐怕都是同一人所为。」

不解状况的波尔德他们百思不得其解，抱著爱剑的威尔海姆则是皱眉看著一切。罗兹瓦尔那一副知道元凶是谁的嘴脸叫人火大。

但罗兹瓦尔不睬他的内心，而是指著魔法阵的痕迹说：

「不管是亚人联军所使用的特殊术式，还是操纵尸兵的咒术，全都是同一人的作为。名字……对方自称史芬克丝。据说是过去魔女的负面遗产。这样一讲，就懂她的威胁了吧。」

罗兹瓦尔的话，让包含威尔海姆在内的所有人都倒抽一口气。

魔女的残渣史芬克丝——王国军与亚人联军之战会转为又臭又长的内战，原因就在于有这可怕的怪物介入其中。

而据此而生、与魔女的渊源，将露格尼卡王国和卓格夫队，尤其是将威尔海姆卷进无可避免的庞大命运中。

威尔海姆·托利亚斯——是目前尚未与命运邂逅的一介剑鬼。

齿轮开始运转，是在他十八岁那年——距今三年后。

** 三幕

1

在卡斯泽尔平原的战场遗迹遭遇「魔女」并与之开战。

「魔女」加入亚人联军，带给露格尼卡王国大本营巨大冲击。

「该说事态严重——吗。自称是史芬克丝的人物操纵尸体，还能使用失传的大魔法。在卡斯泽尔的败仗，恐怕不会只发生一次。」

王国军上层人士、王国骑士队的知名士官与近卫骑士，以及王国屈指可数的上级贵族等齐聚在大会议场。在这庄严肃穆的场合，罗兹瓦尔·J·梅札斯女史气派堂堂地说出这段话。

在流畅的语调中，掺入她个人拉长语音的独特风格。但是无人针砭这点，听了这番话的大人物们也都不改严肃面容。

「史芬克丝吗。是有听说一部份的人怀疑她与魔女教有关……」

「就我所见，她与魔女教毫无瓜葛。魔女教的行动方针基本上是顺从己欲……若企图颠覆王国，很难想象会藉助亚人族之手。」

「虽然我认为，说穿了这正是『他们的作为，只有他们才懂』就是了。」

魔女教这字汇一出现，对忌讳之物所生的紧张气息便蔓延了整个会议场。

「魔女教」指的是信奉，并企图让数百年前差点毁灭世界的「嫉妒魔女」复活的团体——这是普罗大众对他们的认知。其实以现实面来说，他们的活动很难联想到与复活魔女有关，一般来说只把他们当成一群神经病。

比起激起同感，威尔海姆是压根儿对他们没兴趣。他很好奇为何自己现在会坐在会议场的末座。身旁的座位还坐著波尔德和皮波特，但身为正骑士的他们现身于此是再正当不过。经验不同。这个胆量，真想分给格林。

「……呜噗。」

一脸不耐烦的威尔海姆，旁边是身体不适到面色铁青的格林。他呼吸不顺到感觉一个弄不好就会把今天的早餐给吐出来。

这家伙怎么每次都一脸惨白啊。就在冒出这个感想的时候。

「——那么，请实际遭遇史芬克丝的卓格夫队报告。几位，请到这——边。」

「是！」

罗兹瓦尔指名，波尔德大喝响应然后站起来。另外三人慢一拍才站起，四人一起来到会议场的正中央。

「在下是卓格夫队的指挥官，波尔德·卓格夫！此次被传唤至大本营，实属光荣之至！」

「少爷，您招呼语搞错了啦。……咳嗯，鄙人是卓格夫队的副官，皮波特·阿南西。你们两位也报上姓名。」

皮波特在莫名大声的波尔德之后出声，接著朝威尔海姆他们使眼色。

「鄙、鄙人是卓格夫队士兵，格林·法先！」

「……同上，威尔海姆·托利亚斯。」

格林尖嗓报上姓名，威尔海姆则是有气无力跟著念。

皮波特皱眉，不过大本营的达官贵人们不在乎。比起他们的姓名，他们更在意报告的内容。

「据梅札斯女史所言，贵队曾和史芬克丝应战。尸兵、飞行魔法、卡斯泽尔的魔法阵跟那个人……你们怎么想？」

「是！在下虽和会动的尸体战斗过，但不曾见过那名魔女！」

「少爷，请安静。失礼了。我们队里曾跟那个人有过实际接触的，是这两位。威尔海姆、格林，报告。」

「素、素的！」

脸色更白的格林向前一步，威尔海姆心不甘情不愿地照做。接著，大本营便朝他们不断提出问题。话虽如此，内容与先前大同小异。主要就是为罗兹瓦尔的报告挂保证以及述说感想之类的。

「在形式上，姑且先当作对方是魔女吧。你对那魔女的印象是什么？」

这个问题不管是内容还是发问者的声音，氛围全都跟方才不同。

仔细看，举手发言的是名细长脸的温文男子，年龄约三十岁前后吧。温和的脸庞和细心整理的咖啡色头发，让他看起来就像名学者。在相貌全都雄壮威武的与会人员中，特别让人觉得是异类。

「印、印象吗！？这、这个嘛……就是诡异又恐怖……不！身为王国军士兵，绝不会胆怯……！」

朝著不打自招的格林微微颔首，温文男子眯著眼睛看向威尔海姆。

那透彻的眼神，使得威尔海姆在这场会议中头一次认真收敛表情。

外表看似文官，但却是招惹不起的对象。这种宛如被剑抵住喉咙的压迫感，是只有视这儿为战场的修罗才会释放的独特感觉。

「……你是谁？」

窃语四起，身旁的格林屏息看著威尔海姆。但是，威尔海姆所产生的动荡，却由举手的温文男子自行平息。

「嗯，这真是失礼了。我是麦克罗托夫·马克马洪。原本没资格出席这个会议，但因为推荐梅札斯女史分析魔法阵的人是我，所以才能得以像这样忝居末座。」

自称麦克罗托夫的温文男子说完后朝罗兹瓦尔使眼色。接受到的罗兹瓦尔刻意演了一出恭敬鞠躬的戏码。原来如此，两个都不是什么好人。

「——不管她叫魔女还什么，我不觉得她是人类。」

疑问冰释，威尔海姆边吐气边回答问题。

「只是披著人皮的怪物。就是饿肚子而杀红眼的魔兽出现在眼前，这种状态还有什么好商量的？不是杀了那魔女就是被她杀，就这样而已。」

威尔海姆杀气腾腾的回答，让会议场暂时沈默。

不过，即使承受威尔海姆的慑人视线，麦克罗托夫也只是微微点头。

「原来如此，可以作为参考。你可以退下了。」

他展现大人物的器量，结束对他们的提问。

2

「你真的是很不受教耶，为什么你每次都这样！？我寿命都缩短了！」

结束在会议场的职务，返回营房的途中，格林的怒气爆发。

任务一结束就立刻从卡斯泽尔平原来到王城，也没休息就进入会议场报告。现在总算是卸下工作，可以脱去身上拘谨的制服——就在这个节骨眼的时候。

脱去制服的格林，冲著脱去上衣擦身体的威尔海姆发脾气。

「面对那么多的重要人物，你干嘛那么坚持要做自己！皮波特先生明明事前就已经叮咛了那么多遍！你还那么不长眼！」

「你『那么』是要讲几次。还有少跟我装熟。」

格林讲得口沫横飞，威尔海姆只是态度冷淡继续更衣。他对格林的看法依旧没变，还是没用的胆小鬼。

唯有在卡斯泽尔平原遭遇战中，最后砍下过去战友头颅的气概，可以勉强认可。

「唉呀，用不著那么生气，格林！老子反而放心了。威尔海姆如果是有礼貌的笨蛋，那之前都被他无礼对待却还原谅他的老子立场何在！」

「该不该对少爷有礼貌姑且不论，威尔海姆的作为并没有不知礼数吧？」

同样在更衣室更衣的波尔德和皮波特加入对话。副官的话让波尔德不解，于是问他：「怎么讲？」

「威尔海姆的行为很明显地处处都有受过教育的迹象。他或许没有认真习礼，但日积月累下来就习惯成自然。」

「——呿！」

皮波特出乎意料的洞察力，让威尔海姆不悦咂嘴。

视那反应为肯定，格林和波尔德互看彼此一眼。

「受过教育？威尔海姆不是老百姓吗？」

「是有听说最近的商人流行让自己的孩子接受上流阶层的教育，是这种的吗？不管怎样，白白浪费学过的礼数叫人无法佩服。」

「少爷应该也接受过扎实的礼节教育，但别说态度了，连习惯都没有，真不知是怎么搞的。我从以前就觉得很不可思议。」

五十步笑百步的波尔德，和一脸惊讶的格林。斜眼看著他们的反应，但威尔海姆没有要为他们解答的意思。私领域方面的话题，自己可是一概不理。

「干嘛板著一张脸，这种事跟队上的同伴说——也无伤大雅吧？自己出身于地方贵族托利亚斯家，引以自豪的爱剑上头可是有露格尼卡国徽的正统宝剑喔。」

「——哼。」

自己的过去突然被人揭露，使得威尔海姆杀气腾腾地回过头。结果和背靠在更衣室门上嘻嘻笑的罗兹瓦尔对上眼。

她扇著手，若无其事地承受威尔海姆的视线。

「调查一下就马——上知道了。……虽说是边境贫穷贵族，但既然是跟露格尼卡有关连的贵族，当然就会有纪录。你不会以为——能够永远隐瞒吧？」

「与其闲到去挖别人的过去，不如把自己的工作做好吧。宫廷小丑是终于想到自己还有点用处了吗？」

「宫廷小丑……哈哈！不错喔。你啊，果然很有趣～呢。」

丝毫不睬威尔海姆的烦躁，罗兹瓦尔环视更衣室内的四人。

「史芬克丝的事在大本营中已经被列为最重要案件，地位等同于亚人联军代表利布雷·菲尔密和巴尔加·克罗姆威尔了——哟。感谢麦克罗托夫大人的支援。……我唯一不满的，就是那家伙被称为魔女。」

罗兹瓦尔耸了耸肩，还在最后透露不满。曾亲眼目睹她露骨表达厌恶的威尔海姆，想起卡斯泽尔平原的事。

「这么说来，你以前见过那个怪物吧？在卡斯泽尔的时候你好像有说想杀了她。」

「唉呀，你很在意我？呼嗯，虽然年龄有点差距……不过在爱面前那只是微不足道的小事。很幸运的，你长得很帅，我也不讨厌……开玩笑的啦。」

看到威尔海姆意欲拔剑，罗兹瓦尔中途举白旗投降。

「非常遗憾，我是不会说明我跟『那个』的关系的。不～过，我没法容忍『那个』的存在，所以尽管放心。杀了『那个』是你我共同的目标。假如你说什么都想知道的话……那就等我们关系变得更亲密一点——再说啰。」

「我只希望到此为止。」

「用不著害臊，况且也无法如你所愿。发生这次的事情后，我成了王国军的魔法对策负责人。只要内战和史芬克丝没有解决，我们就会很——常见面喔。」

罗兹瓦尔愉悦地朝苦著一张脸的威尔海姆这么说。

威尔海姆撇过头，波尔德和皮波特似乎早就知道，全都点头肯定。

「你们卓格夫队在这次事件中的功绩和实力获得肯定。今后除了会转战激战区，也会被派往各地的最前线吧。」

「哦哦，那真是求之不得！『剑鬼』威尔海姆也可以感到满足吧！」

「剑鬼……？」

听到会被派往激战区域，皮波特和格林叹气，但波尔德却非常开心，还拍了拍威尔海姆的肩膀。罗兹瓦尔则是对「剑鬼」这称号感到疑惑。

「军中给他取的煞气绰号啦。毕竟在初征和第二战都以好杀闻名。虽然老子也自称『刚战斧』来对抗，不过却传不开呢！」

「少爷的话，是被取『猛犬』这个绰号……不了，既然不是本人的意愿，就先不说了。毕竟这世上不可能事事顺心。」

「剑鬼……原来如此，剑鬼——啊。——真的很符合你呢。」

面对含笑的罗兹瓦尔，威尔海姆哼了一声别过脸。他对别人怎么称呼自己毫无兴趣。「剑鬼」这个称号也只是喊好听而已。

「那可不是随便的——称呼。正因为身在悲惨战火中，人心会盼望英雄出现。就像『剑圣』和『贤者』……呢。特别在这次的内战中，前代剑圣弗莱巴尔殿下还战死～了。」

「为了让友军撤退而殿后，最后壮烈牺牲。可说是军人的荣耀啊。」

威尔海姆对罗兹瓦尔的话漠不关心，波尔德代替他一脸沈痛地点头。

「剑圣」是代代侍奉露格尼卡王国的顶尖剑士称号。但是，有这头衔却还死掉，代表那个人的实力也没啥了不起的吧。

「我去练兵场。你们爱聊多久就多久。」

「什么，你接下来要去练兵场！？唉哟，实在是！等一下啦，威尔海姆！我也要去！」

「别跟来。」

威尔海姆快速换好衣服就步出更衣室，格林连忙抓住剑和盾牌跟上。在离开更衣室前就只有格林向大家点头行礼，彰显出两人的个性差别。

「威尔海姆和格林之间的隔阂感，从昨天开始改变了呢。」

「因为格林破除内心阴影了，表情也变得很棒呢。虽然剑术不怎么样，但使盾还略有心得。他接下来才要成长呢。」

「少爷不管对什么事都太过坚信人性本善。在您心目中根本没有不会成长的人类吧。」

「哇哈哈！人类就是缺点的集合体。既然如此，只要有一个长处就很够了吧！」

波尔德边笑边换上训练用的轻便服装，对此皮波特叹气。握住靠著墙壁的战斧后，波尔德重新面向罗兹瓦尔。

「劳梅札斯女史亲自跑一趟，却没能为您做些什么，真是不好意思。卓格夫队接下来全都要到练兵场，明天开始又会变得很忙碌。」

「我不在意——喔。你没改变我可是求之不得。而且刚刚也说过了，接下来有很长一段时间都会碰面。让我们永远打好关系吧。」

「……那真是太感激了。我也不希望搞砸与梅札斯女史之间的关系。」

皮波特说完，就跟大笑的波尔德一起走出了更衣室。在走廊和挥手的罗兹瓦尔道别，直到看不见她之后，波尔德才开口。

「怎么著，皮波特。才想说你都快三十了却都不曾传过绯闻，原来你喜欢梅札斯女史那类型的女人啊。不能小看你呢。」

「少爷——请不要太过相信梅札斯女史。」

「哦？」

波尔德本来是开玩笑，但压低声音的皮波特却投以别有含意的视线。接收到的波尔德抚摸懒得刮除的胡子。

「既然你都这样讲了，老子会注意的……有什么隐情吗？」

「她是个莫测高深的女性。不管是背后还是私底下都太完美无瑕了。总而言之，内战期间都会一直跟她打交道。……我们可要绷紧神经。」

「双面间谍吗，有意思。队上早已有剑鬼这颗炸弹了，队长可真难当呀！」

波尔德在营房走廊上大笑。感受到笑声引来周遭的讶异，皮波特也大声叹气，说：

「唉呀呀呀……我们真的专抽下下签呢。」

3

——露格尼卡王国东南区域有个不分昼夜都笼罩在浓雾当中的地方，叫夏姆洛克溪谷。

不限露格尼卡，雾在整个世界都被誉为不吉利的象征。地形只有陡峭岩区的溪谷，因此成了排斥生物的自然要害。

所以说，浓雾溪谷对见不得光的人来说，是绝佳的躲藏之处。

藏在悬崖底下，在雾气下几乎看不见、随便搭建的小屋，也是这些偷偷摸摸的歹徒的住处之一。

「——等一下，巴尔加！这到底是怎样！给人家说明清楚！」

毫无前兆就突然响彻浓雾的，是要求说明的激动人声。

要形容成裂帛又嫌太粗野的声音，满载著让人犹豫是否该指出这一点的愤怒。

「……不要那么大声。虽说外头的雾是可以吸收惨叫的邪雾，但你这音量大到别人听到都知道你是谁了。」

大声斥责后，是低沈的沙哑声回应。回应的人手贴耳朵，朝个性直来直往的对象诉说不满。但是，激动者的愤怒并没有因此收敛。

「你再怎么主张理性分析也没用啦，没用！假如是想对人家说教的话，那应该先解释你的所作所为吧！」

「解释什么？为何老朽非得解释自己的作为？老朽有做错什么吗？对吧，利布雷？什么都没做的你，有什么资格指责老朽！？」

「不要得意忘形了，未老先衰男！明明年纪比较小，拽什么拽！」

彼此的怒气都到达沸点，高个子和大块头的两人额头抵在一起，互相叫骂。瞪视彼此的眼中甚至带有杀意，这场对峙已经离爆发不远。但这时候——

「两个都吵死了。环境不够安静的话，会妨碍到实验。找你们来我的隐身处是要你们帮助我实验的。」

冷淡的女童之音——内容是在责备吵架的两人，但却不带一丝一毫的情感。

可是，女孩只是这么说，争吵的两人就老实各退一步。

「要是马上找碴吵架的话，就用不著谈团结了。好呀，这边就看在那孩子的份上让你。不过听清楚啰？这不代表人家接受了。」

说完还用鼻子一哼的，是个头高到天花板的人。

瘦弱无比的身躯被长袍包裹，黄色瞳孔闪耀著诡异光芒。探出的手脚和头部全都被绿色鳞片覆盖，衣摆底下还伸出又粗又长、像是爬虫类的尾巴。搭配长长的舌头，毫无疑问是亚人。

——名叫利布雷·菲尔密。其名声响亮，是亚人联军的代表人物之一。

「巴尔加，说明清楚。卡斯泽尔的魔法阵和之后的尸体家家酒是怎么一回事。」

「看结果不就知道了。叽叽喳喳像个娘们一样吵，臭蛇。」

骂脏话回应利布雷的，是硬把身子塞进尺寸不合的椅子内、看起来像个老头的大块头巨汉。他的身高目测就超过两公尺。

巨人族——除去体格外，外观几乎与人类无异的亚人族。

这个巨汉是巨人族的少数幸存者，而且在长寿的巨人族中还只算是年轻人。可是在亚人联军中，他所做出的贡献却比其他人还要突出。

他正是亚人联军的大参谋，集结原本只是乌合之众的亚人族，组织大规模联军朝王国高揭反旗的主使者——巴尔加·克罗姆威尔。

「对那个战果是有啥好挑剔的？哦，原来如此，老朽懂了。耗那么多功夫，人类的尸体却不够多是吧。这样啊。想杀更多就早说嘛！」

「人家才没讲那么乳臭未干的话呢！人家说的是杀过头了！本来这战争拖太久，大家都不想打了……现在那些人类被杀了那么多同伴，是绝对不可能会退缩了啦！这样下去只会两败俱伤！」

「不要误会了，利布雷。打从一开始就是两败俱伤啦！」

听了利布雷的大吼，巴尔加脚踹椅子站起来。两人再度互瞪。

「跟那些人类……老朽可不想跟任何一个臭人类一同活在世上。老朽要歼灭他们，把尸体全都给扔进大瀑布里！」

「所以才会说你是个小鬼！我们的数量跟人类完全没得比！就算之后你的战术全都奏效，让他们的死伤人数是我们的十倍……继续打下去，也会是我们先灭亡。这场战争就是这样！」

「那不然，你要对骄傲低头妥协，去对他们摇尾乞怜吗？你才是想清楚吧。你都没听见吗，我们的同胞被蹂躏践踏的叹息，被扔弃的同胞的声音。——老朽听得见。他们向老朽要求给人类报应。这才是亚人族的骄傲！」

「就跟你说为骄傲而死已经不流行了！观念是用来理解，不是囫囵吞枣的，笨蛋小鬼——！！要搞盛大的自杀场面就自己去，不要把其他人给卷进来！」

「——你们两个。」

声音冰冷无情，而且尖锐得像要戳破耳膜——一道白光闪过互瞪的两人的鼻头，光芒穿过的空间被惊人的锋利度给切断。

「我提议安静。假若不接受第二次的劝告，第三次我将会动用实力，将你们两个也加入我的尸兵行列中。」

身穿白袍，留著一头浅红长发的女孩——魔女史芬克丝这么警告。

楚楚可怜的女童竖起食指，歪著小脑袋询问两人的意见。

「可以吗？我两边都无所谓。两边我都会·仔·细·观·察。」

「跟这未老先衰男吵个架就要变成尸体，这可不好玩。」

「那是老朽的台词。」

互呛对方的利布雷和巴尔加这次拉开距离。而面对互相牵制的两人，放下手的史芬克丝轻叫了一声。

「啊。接续刚刚的对话，数量上的劣势可以用我的尸兵来弥补。」

「这倒是。尸兵就是为此而有，史芬克丝也是为此而来。虽然被爱担心的胆小蛇揶揄是『尸体家家酒』，但这个提议没得抱怨吧？」

「在伦理道德上抱怨可多了。玩弄死者的尸体，你都不会有罪恶感吗？人家是不期待可疑的魔女精神有多正常，但你不是吧。」

咧开嘴巴伸出长舌，双手抱胸的利布雷厌恶地瞪向史芬克丝。

可是，巴尔加却嗤之以鼻。

「用邪术侮辱邪魔歪道的尸体，有啥好在乎的。而且同胞们的尸体希望老朽给人类报应。如你所说，我们确实在种族上是弱势。既然如此，弱者就该以弱者的方式绞尽脑汁生出智慧——这世上没有弱者就该永远输下去的道理。」

「……人家会照自己的想法去做。可是，有件事要先说清楚。」

利布雷放弃跟他争辩，叹气后走向小屋出口。然后转过头，眯起黄色瞳孔，瞪著巴尔加。

「巴尔加，假如你继续走这条路，那迟早会通往地狱。」

「——几时？现在这个世界就是地狱了吧。」

叹气成了道别的招呼语。

利布雷离去，巴尔加顿时放松。这时，史芬克丝突然开口：

「既然会妨碍未来的计划，先收拾掉比较好吧？」

「不要多管闲事。利布雷只是意见跟老朽相左，但联合军需要他。老朽虽然被称为大参谋，但只能靠些小手段帮忙同胞。要打先锋扫除敌人、让我方士气保持在最高的话，就需要像他那样的英雄。」

「真不好办呢。要·深·思·熟·虑——然后，接下来要做什么？跟卡斯泽尔一样，铺设魔法阵吗？」

史芬克丝立刻舍弃加害利布雷的念头，将兴趣转移到下一个实验。偏颇的思维模式让巴尔加闭上眼睛，接著用粗壮双手摊开地图。

「在卡斯泽尔败战之因传开来之前，那招对人类还算有效；但联军目前也并未整合到可以马上动员的状态。下一仗越慢开打，就等于给人类越多时间想对策。以魔法阵进行包围歼灭的战术，已经不适用了。」

「那，要怎么做？」

「决定了。——就让他们轻易破坏魔法阵吧。」

巴尔加用邪恶的血腥笑容回应史芬克丝的问话。

见他如此，史芬克丝依旧面无表情，只是稍稍低垂眼帘。

「——要·仔·细·观·察。」

然后用小到没人听到的音量这么说。

4

——日子转眼间就过去。

忙乱的日子让人忘记时间，这点就连剑鬼威尔海姆也不例外。

如同大会议结束后的宣告，威尔海姆所属的卓格夫队之后不断前往王国各地的激战地区应战，时光就在最前线的战斗中流逝。

这段期间，王国军与亚人联军的内战情势是反反复覆——当王国军获得大规模的胜利，亚人联军就击溃复数战线来取得战略性的胜利。如此重复。

亚人联军的中心三人物，每个都逃过王国的追捕，因此王国始终没能摧毁亚人的士气。

回过神来，在王国军的时间拉长，在卓格夫队也待了两年。

卓格夫队也变得壮大，构成的成员也有相当的变化。初期就在队内的队员减到剩一半左右，而死去的队员会被加倍的人力增补回来，现在已经成了快百人的大家庭，也变成更能左右战局的活跃战力。

但，即使有这么大的变化，格林还在队伍中才是让威尔海姆觉得最不可思议的地方。两年前，第一次碰面时以为会马上死掉的人，不知不觉间也成了以勇猛著称，还是卓格夫队最元老的成员之一。

虽然使起剑来还是一样弱不禁风，却不得不认同他使盾和洞察危机的能力。能够对威尔海姆的第一击做出反应的，在队里就只有格林和波尔德了吧。

而且他还是一样，继续关照威尔海姆。即使被剑鬼无情对待却还是找他说话的格林，被人私底下定位为队里的第一勇士。

「嗨——哟，今天也是大为——活跃呢。」

「……别凑过来。」

「好冷淡～喔。美女亲自邀请，就算只有表面也该装个热情呀。」

在上次的卡斯泽尔平原任务之后，跟罗兹瓦尔打照面的机会就变多了。

不知亚人族何时又会在战场上使用魔法，身为魔法顾问的她当然也就不断巡视战地。因此，一定会碰到总是被派往最前线奋战的卓格夫队。

「对梅札斯女史是什么态度。你都不会觉得可耻吗？」

「唉呀，好了好了，卡萝小姐。威尔海姆就是这种人。就算挑他小毛病，他那个性也没法矫正过来。」

当然，被罗兹瓦尔的护卫卡萝瞪的机会也一样多。

像这种时候，爱出风头找卡萝聊天的格林就派上用场了。把严谨的她推给格林，威尔海姆就能快速沈浸在自己的世界中。

「威尔海姆都没变呢。但那也是他的强项就是了！」

「每次转战各地，听到剑鬼的传闻，我的寿命都要缩短了。下次我要是变得命在旦夕，就是威尔海姆害的。」

波尔德和皮波特站在不远处揶揄威尔海姆的态度也没变。改变的只有波尔德的战斧已经碰不到威尔海姆这点。

实力差距摆在眼前时，波尔德的男儿泪和大笑声不知为何接近烦人地深深烙印在记忆里，让威尔海姆觉得很讨厌。

那是眨眼间就过去的三年中发生的事。

在威尔海姆即将十八岁前，有许多事情都让他留下深刻印象。

——那是他到将来才会想起，无可替代的三年光阴。

5

在早晨的营房个人房，威尔海姆静静地睁开眼睛。

要是平常，只是一般士兵的威尔海姆根本没有权限使用个人房。但是他所立的战功让王国军给予他特别优待，这只是其中一项好处。

威尔海姆对奖赏无感，王国又不知该怎么对待剑鬼，只好出此下策。

「————」

连打呵欠伸懒腰都没有，就直接用冷水洗脸。洗去睡意残渣后，威尔海姆迅速换好制服。但在打理行头时，突然想到。

——今天莫名其妙就放假，所以用不著换上制服。

「……工作过头会过劳死，这可不好笑。」

放假一事是由波尔德亲自下达，再由皮波特叮咛再三，强制执行。

平常的假威尔海姆都会直接退回，然后继续锻炼或参与实战。因此这次的强制放假是用「队伍里最元老的队员剑鬼都不放假，害得其他队员也不敢放假」这种名目。

叹气的他嫌换回便服很麻烦，于是就穿著制服走出房间。

目的地是练兵场——本来是这样，但就是为了禁止他这么做才放他假。可是要是待在房间，最近越来越烦人的格林就会找上门来。

离开营房，前往还笼罩在晨间冷意中的城邑区。向大道上站岗的卫兵轻点个头，就一个人走在冷冷清清的王都中。

王都的活力，比起三年前与日俱减。威尔海姆是很喜欢这样，不过这也代表了内战陷入泥沼。战线扩大，以及明显增加的败战次数造成的影响——露格尼卡一步一步进入黑暗时代。

原本会帮忙防范来自他国侵略和瘟疫的「神龙」，可能判断内战是露格尼卡本身的问题，因此完全不理会王室的求救。

内战始终没有好转的征兆，人民只能勉强度过疲累的每一天。

——威尔海姆要去的地区，也是受到内战影响的地方。

穿过王都中间的平民街，就能看到开发到一半便被废弃的废墟群。听说内战结束的话就会再启作业，但确切时日还是个未知数。

就连威尔海姆也知道，如今这里已成了无业游民和宵小不法之徒的地盘，通称为贫民窟。

正是这种地方才能好好独处，因此他才会来这里。

「——滚。」

沿途放出剑气，驱赶窝藏在废墟中的鼠辈。接触到差距悬殊的杀气，待在这区块的人纷纷逃跑。

对此嗤之以鼻的威尔海姆，走向平常自己就在使用的广场。

位在贫民窟最深处的广场够宽敞和僻静，可以让他好好锻炼自己。在练兵场的话旁边的人会不自在，因此最近有空就是来这边锻炼。

原本威尔海姆锻炼自己就不需要其他人。跟同一个对手重复交手藉此锻炼，根本是在侮辱一招定胜负的实战。

因此对威尔海姆而言，要锻炼剑术，除了与自己战斗别无他法。

不是在讲什么「克己精神」这种文字游戏，而是真正与自己进行殊死战。

这就是最能让「剑鬼」威尔海姆心灵平静、埋头专注的锻炼时光。

「唉呀，对不起。」

穿越废墟群，抵达目的地广场的时候，突然听到有人这样说。

原本可以埋首于练剑的时间，因外来份子而远离。威尔海姆不悦咂嘴，不耐烦地瞪向声音源头。

——是有著一头美丽红色长发、侧脸漂亮到打动人心的少女。

充满光泽、宛如烈焰的红色长发，仿佛映照著皎洁无瑕的蓝天的一对眼睛，工整的美貌给予少女楚楚可怜和优美感，让威尔海姆错觉自己看到的不是人类。

但是，眨眼重新看仔细后，就发现对方只是一名村姑打扮，稍微比常人漂亮一点的少女。

少女坐在广场一角、废墟的部分建筑物上，盯著威尔海姆看。

004

「这么早就有人来这儿呢。在这个地方——」

「————」

少女微笑，威尔海姆的回礼却很简单。

就是毫不理睬，把锋利无比的剑气粗鲁地投向对方。

跟驱赶盘据在贫民窟的流浪汉一样。中了剑气的普通人都会怕到逃跑；就算是同行，也会察觉到威尔海姆的实力而迅速离去。

可是，这唯一的选项却不适用在少女身上。

「……怎么了吗？好恐怖的脸。」

少女歪头表示不解，面容就像是被微风拂面。

看到她那态度，领悟到剑气不管用的威尔海姆自讨没趣地背过脸。

剑气不管用——代表少女跟武术完全无关，是彻头彻尾的外行人。

对那些生活在与暴力无缘的世界的人来说，威尔海姆的剑气就只是威压。视对象而定，有人只觉得这股威压是因为威尔海姆在瞪人。

而这名少女就是这一类的人。

「女人，大清早跑到这种地方来干嘛？」

言外之意是她很碍事，不过伸懒腰的少女却丝毫不察。

「嗯——是很想把这句话原封不动还给你，不过那样讲有点太坏心了。毕竟你生著一张不喜欢人开玩笑的脸。」

「这一带很多不法份子。一个女人家闲逛很危险。」

「唉呀，你在担心我吗？」

「我也有可能是那些不法之徒喔。」

「用不著担心啦。你穿的是王城军队的制服，所以不是坏人，对吧？」

按照习惯穿上身又懒得换回便服，没想到直接穿著制服来会在这时让自己栽跟头。

平常的调调不管用还被回嘴。少女朝著他嘻嘻笑。

「我本来以为这里只有我知道，所以蛮讶异的。这是个好地方。虽然得走远一点，不过可以一个人独处。」

「对呀，像你就妨碍到别人独处了。」

「这点是彼此彼此，就不说了。跷班的不良士兵先生？」

「我可没跷班。」

「好啦好啦，我会帮你保～密的。啊，对了。」

少女不听信威尔海姆的反驳，径自指向自己坐著的废墟后头。

「你看——」

好像是有什么东西，但威尔海姆站著的位置看不见。见他眉头一皱，少女微笑，像小动物一样朝他招手。

「我不是特别想看……」

「没关系啦。过来过来。」

哄小孩一样的态度让威尔海姆脸颊痉挛，但还是无可奈何地来到少女身旁。踩上废墟的残缺建筑物上，看向少女指的地方——

「————」

看到在朝阳下一片鲜黄的花海，威尔海姆屏息。

「这区块不是很久之前就停止开发了吗？我想说不会有人来，就撒了种子。为了看结果才来这的。」

少女压低音量，像在对无言的威尔海姆坦白秘密。

被这意料之外的光景给震慑，但并非出自于感激。明明来过许多次，却看漏了与这里判若两个世界的光景，单纯是因为自己太糊涂了。

因而才看漏了只要稍微伸长身子、放宽眼界的话便能看到的世界——

「你喜欢花吗？」

少女问还是没开口的威尔海姆。

威尔海姆转向她，凝视露出柔和微笑的脸庞。

然后——

「不，我讨厌。」

威尔海姆见证了那抹微笑盛大地转化成不开心的表情。

6

「这阵子你假日很忙是吗，威尔海姆。去房间叫你找不到人，是上哪去砍人啦？」

「我才没很忙我也没去砍人。」

「是吗。虽非你的本愿，但和平的休假似乎有在持续呢。」

下了龙车，整顿军服的格林毫不客气地这么说。威尔海姆恼怒地皱起鼻子，斜眼看得到格林在笑，使得心情更加烦躁。

即使人数增加，威尔海姆在队伍里的待遇还是没变。只不过波尔德和格林经年累月习于应对威尔海姆，因此像这样被吐嘈的情况也增加了。

「————」

保持沈默的威尔海姆思考被格林当成话题的「假日」。

在那之后的几个礼拜，不知名的少女——先叫她花女好了，一直都和威尔海姆在他放得不情不愿的假日里相遇。

很不可思议的，不定期前往广场的威尔海姆不管几时前往，那个花女都像是理所当然地坐在花海前面。而她就这样坐在那儿，盯著威尔海姆练剑。那视线让人觉得很烦，但比起被对方赶跑还是来得好多了。

一开始，被她问对花海的感想时，威尔海姆不识趣的回答似乎惹恼了她。在宛如暴风雨的骂声中离去，使得他胸口留下满满的败北感。

可是，还有一件很不可思议的——

「你喜欢花吗？」

每次威尔海姆练完剑，她都会微笑这样问。

答案又不会因此改变，每次被问只让人觉得厌烦。

「不，我讨厌。」

而自己每次都用坏人脸回答，成了约定俗成之举。

「到了，南方战线！这里是目前交战最激烈的地区！似乎也已经确认利布雷·菲尔密和巴尔加·克罗姆威尔在此！假如要立下大功，除了今天没别的机会啦！」

声势逼人的吆喝声，将陷入沈思的意识拉回现实。

站在前头高举战斧、鼓舞部队士气的是有模有样的指挥官波尔德。率领的士兵人数增加，没法像以前那样随心所欲的他，意外地在部队运用上颇有一套，卓格夫队的战果也就益发扩大为世人所知。

「话虽如此，此次我们的任务不是突击敌方本营，而是看清各战地战况，适时增员，也就是打游击。因此麻烦千万不要做出争强好胜和专断独行的行动。」

虽然随著战果增加，身为副官的皮波特辛劳也跟著增加了。

——这次的战场，以露格尼卡南部的爱西亚湿地一带为中心。

内战在王国各地都掀起战火，但亚人联军抵抗最为激烈的地方就在南部。这回像是要证明这点似的，确切情报显示亚人联军的主要干部都集结在此，因此王国军组织大规模战力投入战线，卓格夫队也要跟著参战。

「这么庞大的攻势。搞不好内战会就这样结束……」

「还是一样乐观呢。我光是听到人类召集大批人马要闯到亚人主要干部所在的地区，就觉得可疑的气味臭到我鼻子要歪了。」

威尔海姆朝著满心期待的格林浇冷水，惹得他不开心。但是，他马上就了解威尔海姆话里的含意，摸著自己的脖子后方，问：

「该不会……是在讲卡斯泽尔平原的事吧？」

「那个时候，巴尔加·克罗姆威尔也在。要是有魔法阵，那魔女也会在吧。那些人好整以暇等在这里，王国却投入超越卡斯泽尔之役的人数。你想会发生什么事？」

格林吞咽口水的声音听起来格外大声。周围等待出阵命令的士兵们，个个都无一丝不安。在这高举战意鼓舞自己才是正确的。

不过，白白送死就跟字面意思一样，是毫无意义的行径。

「虽说，这种程度，上头也早就预料到了吧。」

「……咦？」

「当——然啰，就如你所说。刚刚格林的表情真是杰作——呢。」

格林做出愚蠢反应的同时，也听到再熟悉不过的女人声音。两人回过头，后头是即使身在战场也不改悠哉自得态度的罗兹瓦尔。她扬起罩在军服上的斗蓬，挺直背脊像在夸耀她那对美胸。

「当然，上级也看出史芬克丝在这战场上暗中活跃的可能性很高。因为至今为止的战役里，敌方企图使用魔法造成大规模伤害的野心屡次被击溃。拿手好戏被看穿，所以他们也差不多要按捺不住了。」

「已、已经不管在何处都会理所当然似地出现了呢，梅札斯女史。」

「害羞啦。而且看到我，就代表你的公主殿下也在——哟。」

罗兹瓦尔的笑容意有所指，她身后是正走过来的贴身护卫卡萝。还是一样，明明是女人，却装备骑士铠甲和长剑。这三年来有变化的，就只有稍微长长的金发，以及对格林的微笑有所不同。

「格林，还好在开战前见到你。今天会是一场激战，罗兹瓦尔大人这样吓我，害我很不安……」

「我、我才是很高兴见到面呢！一想到卡萝小姐在后方，没错，就是这样！我绝对不会让敌人通过我这面盾牌到后方的！」

「我可是比你强哟。被侮辱可是会不高兴的耶？」

「我、我我我我没那个意思！」

「开玩笑的。听你这么说，我很高兴喔。」

撇开威尔海姆他们，格林和卡萝开始了两人世界。

对此感到厌烦时，罗兹瓦尔用手肘顶了顶威尔海姆。

「心情怎样？欸，你现在心情怎样？朋友和女生感情这么好，而且还是在战场上卿卿我我，亲眼目睹的你心情怎样啊？」

「无聊透顶。还有不要擅自认定我跟那家伙是朋友。我才没有朋友呢。」

「唉——呀，真是寂寞的意见。那，要不跟我亲热吧？」

「小心我砍你。」

在话说完前，罗兹瓦尔就大幅退后到手碰不到的地方了。

明明是开战前的待机时间，每个人却都不让自己的精神集中在备战上。格林因为得到了卡萝给的护身符所以欢欣不已，完全不像平常那样长吁短叹。

「不管怎样，对付史芬克丝的事就交给我们吧。你就尽量砍杀眼前的敌人，尽情享乐就好。」

「务必让我那样。少做蠢事。」

「你是在担心我——吗？」

「我是指不要随便插手。」

冷淡的回应让罗兹瓦尔嘟起嘴唇，威尔海姆敲响爱剑的剑颚，想赶跑她。结果，在话题告一段落时。

「梅札斯女史在吗？指挥官有事想问她！」

「队、队长！这边，女史在这里。」

波尔德的巨大身躯分开士兵人海走过来。正在跟卡萝说话的格林连忙指向罗兹瓦尔，罗兹瓦尔则是挥手主张存在。波尔德点头，说：

「莱夫殿下！梅札斯女史在此！劳驾您了！」

「……用不著每个步骤都大喊，我听得见。你这样容易被人看做只有嗓门大，没有其他可取之处喔。」

一道阴沈男声回应波尔德的呼喊。以波尔德的巨大身躯为目标走过来的，是个眼神凶恶、年约三十左右的正骑士。

骑士在罗兹瓦尔面前站定，以流水般的动作对她行了一礼。

「我是莱夫·跋利耶尔南方子爵。负责担任这一边的战线指挥官。」

「唉呀？怎么我先前听到的指挥官是克莱曼卿呢？」

「克莱曼卿不久前于战场被流箭所伤，伤势恶化逝世。这么慢才通知您真的很抱歉。但目前以爵位和战功来看，我毫无疑问是指挥官。」

声音很平静，眼神也没有变化。但是，嗓音却让人觉得有点含混不清。

上司的新上司莱夫·跋利耶尔，给人的感觉不是什么好东西。威尔海姆视线撇离他，望向敌阵——

「那边的一般兵，立正站好！」

「……说我？」

「我不说第二次！」

莱夫直直走过来，接著就朝威尔海姆的脸挥拳。瞥见他这动作的瞬间，威尔海姆手伸向剑柄——然后硬生生停住。

于此同时，脸颊受到冲击。被打的威尔海姆上半身一晃。

「上司在场……更何况还是指挥官在场，士兵有全神贯注倾听的义务。可能被人称赞是勇猛部队所以就得意忘形了，但就算是剑鬼我也不会给予特殊待遇。」

「————」

「眼神透露出反抗的年轻人……是想在开战前重新学习规矩吗？」

威尔海姆吐掉口中的血，恶狠狠地瞪著莱夫。而莱夫的表情带著嗜虐，一副准备要教训人的样子。他的话意味著更进一步的体罚，而现场无人能阻止指挥官。

「到——此为止啰。现在可不是和小孩子玩——的时候吧？」

——除了不被王国军的规矩和阶级束缚的罗兹瓦尔·J·梅札斯。

莱夫再度举起的拳头被她从上按住。罗兹瓦尔朝莱夫微笑，结果莱夫不悦地鼻子喷气，转身背对威尔海姆。

「波尔德，要确实教育部下礼节。别让我做出要教育你的行为。南部战线可不是让小孩子玩沙的游乐场。」

「……是，万分抱歉。」

「梅札斯女史！开战前我想听你的意见。麻烦跟我过来。」

斥责完波尔德后，莱夫一脸兴致全无的表情呼喊罗兹瓦尔。「来——了。」罗兹瓦尔跟过去，带著担心到不住回头的卡萝离开现场。

直到看不见莱夫，现场的紧张气氛才总算解除。

「没、没事吧，威尔海姆？」

格林跑过去，看著被揍的脸颊边问。

「没什么大不了的。不过是被揍而已，有什么好担心的。」

「话可不是那么说。虽然你被揍，但你没杀掉指挥官这点才叫我惊讶。你是不是身体哪里不舒服？今天还是休息比较好……对不起对不起！」

威尔海姆抽剑抵著格林的脖子，强迫他闭嘴，接著收剑入鞘。波尔德则是一脸过意不去地点个头。

「抱歉，威尔海姆。让你抽到这么倒霉又不必要的下下签。」

「不用挤过来。用不著当一回事。没什么大不了的。不要让我重复一直说。」

这种郁闷的回应让威尔海姆挥挥手，用力以袖子擦拭被揍的地方。

「话说回来，刚刚的指挥官没问题吗？活脱脱就是士兵能想象到的最讨厌的上司。」

「莱夫·跋利耶尔殿下是个战功彪炳的杰出军人。个性有点难搞是事实……不过因为是战无不胜的指挥官，所以跟随的人也很多吧？」

格林对波尔德的回答只觉可疑，不过威尔海姆判断这番对莱夫·跋利耶尔的看法是正确的。

被揍的时候，莱夫的身体动作——确实是相当强悍的军人才会有的。那是经过严酷锻炼且去过许多惨烈战场还活著回来的人才会有的力量。

实战的实力或许和波尔德有得拼，格林的话就更不用说了。

「不好的传言不绝于耳，而且以做事不择手段闻名，但指挥方面可以信得过。在这次的大规模编队中，他具备被委任四军团其中之一的实力。总之，就放心吧！」

「是、是的，我知道了。……我先向卡萝小姐的护身符祈祷。」

波尔德大笑，恢复以往的态度。格林则是举起手中紧握的护身符虔诚祈祷。

瞥了一眼，好像是坠子——里头放了东西的项链坠子。

「女人送的礼物啊。格林意外地很有一手嘛。里头放了什么？」

「这个吗，据说是卡萝小姐侍奉的人送她的。里头是……花吧？是压花。鲜黄又楚楚可怜的样子，跟卡萝小姐好像……！」

刻意把坠子倾斜给波尔德看的格林大放闪光。此时，威尔海姆偶然看到里头的东西，结果微微吃了一惊。

那毫无疑问就是在贫民窟跟花女一起看过的黄色花朵。

「都要开战了，每个却都这副德性……」

全都在扰乱自己的集中力。敌方该不会用了什么计谋扰乱王国军内部吧？

威尔海姆压抑住一肚子火，试图集中精神——

「卓格夫队请集合。配置方面，要跟其他队会合讨论……你怎么了，威尔海姆？」

「没事啦！」

皮波特给予最后一击，从威尔海姆身上夺走集中精神的最后一丝时间。

「可恶，管你们发生什么事，我都不管了……！」

混在士兵们的行列里移动的同时，威尔海姆愤恨地望向天空。

夜晚结束，朝阳即将到来。开战是在早晨，剩不到几个小时。

莫被鸡毛蒜皮的事情扰乱心神，只要化为一把剑——那就是威尔海姆的宿愿。可是却没能断然实行，战火就烧到威尔海姆了。

——爱西亚湿地地带攻防战，牵动诸多命运的战端很快就要展开。

** 四幕

1

位在露格尼卡王国南部，面积广大的爱西亚湿地地带，座落在与南方的佛拉基亚帝国的国境附近，是非常危险的未开发之地。

王国的内战「亚人战争」自开战之后已持续了四年之久，战斗规模和紧张状态会高涨到前所未有的程度，正因为是在爱西亚开战。

「本来跟佛拉基亚间的小战役就多到数不清了，现在又还沿著国境集结这么多的战力……帝国一定也是紧张得不得了。」

远处的会战吶喊声响彻天空，无数踩踏造成地面震动。

以鞋底体验著战场的感觉，双手抱胸的正骑士被焦急给折磨。王国军与亚人联军的激烈冲突早已展开，一干人等却被命令待机。

「说后援部队是很好听啦……但其实只是抽中倒霉的下下签。」

「被旁边的人听到会衍生问题的，拉札克殿下。」

被部下劝慰却还大方点头的人是正骑士拉札克。曾经担任志愿兵教官的他，随著内战恶化而回到前线。由于人脉广又剑术强，所以现在得以率领一个队伍，但他也因此行动受限而颇感拘束。

特别是在只能旁观激烈战火，视线必须紧盯帝国的现在更是如此。

布署在爱西亚湿地地带的王国军分为四军团，其中的三个军团用于与亚人联军交战，剩下的军团就跟佛拉基亚帝国的精兵隔著国境对峙。

「……他们不会有所动作吧？」

「不会吧。要是配合亚人的行动攻击我们，就等于招惹神龙波尔卡尼卡。只要国土还在龙的庇护下，帝国就没法对王国出手。」

「这样的话，这对峙是在互相刺探啰……真的是下下签耶。」

跟部下做出同样结论的拉札克郁闷叹气。

战友们在搏命沙场，身在同个战场却被迫无所作为。拉札克是很为国家和朋友著想的骑士，因此这份心痛会不断地和他的骑士骄傲冲突。

「战友们，愿你们活著回来。要是没法幸存，至少要成全你们的骄傲。——可别输给这些忘记王国对他们有恩的无耻亚人族。」

部下们也怀著同样的心情，朝著压抑内心苦楚的拉札克点头。

拉札克是骑士中的骑士。他的想法表露出露格尼卡的常态：王国内的众多士兵都怀有高洁意志，以及对亚人的嫌恶与憎恨。

也因此，大部分的王国军都没有察觉到。

——这种毫无自觉就轻视亚人族的态度，正是亚人族不愿收起武器的最大理由。

2

一剑就将对手的手腕连同骨头劈断，再反手一挥砍断惨叫男子的颈项。

背部溅上喷出的鲜血，同时翻个身，钢剑就朝绕到背后、外貌像蜥蜴的亚人脸正中央刺过去。接著踹倒脑浆四溢、翻白眼的尸体就算结束。

「哦哦、喝啊啊！」

停下脚步的威尔海姆，旁边倒了一个被撞飞过来的亚人。撞他的人是持盾的格林。以盾牌承受敌人攻击再反击的格林，防御术可谓卓越超群。精通后之先的格林，跟擅长先之先的威尔海姆，战法可说是天壤之别。

撇除这样的感慨，贯穿亚人的心脏。接著格林便跑了过来。

「威尔海姆！你没事吧？」

「看就知道了。」

「也是啦。我只是问问而已。这一区应该收拾完了。队长他们也……」

格林回头望过去，刚好是被击飞到天空的敌兵四肢被斧头砍得七零八落的时候。锋利无比的可怕战斧是波尔德的吧。宛如野兽吶喊的战吼响彻周遭。

「似乎结束了。去会合吧。到下一个战场。」

「希望下一个地方有稍微带劲的对手。」

「我觉得现在这种的比较好。……我不想死。我想活著回去。」

并肩赶赴波尔德那里时，格林手探入胸口触碰坠子。斜瞄一眼，威尔海姆对已经跨越无数战场却都还是没变的格林感到不解。

嘴巴嚷著不想死，却还是冒著生命危险冲进战场。大喊想活著回去，却用盾牌击杀想要自己性命的敌兵。——这不是极度扭曲的心态吗。

「那么，你是因为想死才战斗的吗？」

「————」

「应该不是。你不想死。可是，也不是想杀人。不如说在我看来，你比任何人都想活下去。」

仿佛看透了威尔海姆的内心，格林这么说。

对此感到火大的威尔海姆，咂个嘴就加快脚步，打算把连忙想追上来的格林给扔在后头。

「先锋队长和他的管家公回来了吗！威尔海姆，敌人怎样？」

在前来会合的脸孔中发现威尔海姆的波尔德大喊。威尔海姆举起染血的剑指向战场。

「没什么难缠的。最好往更中心杀过去。打断多少残枝败叶也没意义。要砍就要瞄准树干。」

「格林你咧？有没有什么不好的预感？」

「我的话……没有。我讨厌激战区域，但我赞成接下来这样行动。」

皮波特把话题丢给格林，结果他也同意转战他处。听了意见，波尔德重新扛起斧枪点头道：

「好，就这样干吧！老子也觉得打树枝落叶打腻了。不管是要狩猎还是战斗，都要挑大的才叫战士啊！出发，卓格夫队！跟著老子冲！」

「请等一下，少爷！还是先听听本队指挥官的指示比较好吧？梅札斯女史应该也在。」

「说什么蠢话，皮波特。要是就这样大摇大摆地回去，跋利耶尔子爵又要大放厥词了。所以要突进取得战果，让他闭嘴！这样才可以尽我所能给他点颜色瞧瞧！」

「给他点颜色瞧瞧啊……真像是少爷会说的话，但有欠妥当。」

见波尔德抡起又大又长的战斧，皮波特斯文的脸上面露苦涩，沈默以对。副官这态度，惹得波尔德豪迈大笑。

「就跟之前一样，遵从老子的判断，皮波特！没什么，又没有损失！而且，那个指挥官在开战前揍了威尔海姆一拳，我们可得回敬他上乘好礼呢。」

开战前的事被波尔德拿出来说嘴，威尔海姆皱眉。

「等一下。少趁机取笑人。一开始我就说过这没什么大不了的。而且就算要先动手，也该是由我亲自下手。就我一个人。」

「然后，因为不可能让你一个人去，结果还是全体队员都要去。」

威尔海姆龇牙咧嘴，身旁的格林耸肩答腔。对他这讨人厌的态度破口大骂之前，波尔德和皮波特都笑了。前者是愉快地笑，后者是放弃坚持地笑。

「最近格林也变得很会耍嘴皮子了呢！怎么样，皮波特。还会不安吗？」

「……好吧，我知道了。有少爷，有威尔海姆又有格林才是卓格夫队。就上吧。」

「你也是其中的一份子呀。不要忘啰，皮波特。——好，那么出发吧，小子们！」

波尔德朝天空高举斧枪，其他队员也跟著举高武器唱和。就这样，以大块头为首奔驰的团队，只有在情感上跟不上他们的威尔海姆叹气。

自己只想在战场上互相厮杀夺命，并不期待更多。

「结果却专门招惹到一堆不必要的多余事……」

想要化为钢铁。想成为一把纯凈无污染的剑刃。

但现实与愿望相反，威尔海姆每天都在累积多余的事物。感到厌恶的同时，想要往部队前头跑的威尔海姆突然注意到。

在战场的角落，有一朵孤零零摇曳的红色花朵——原来在战火中，花也会绽放。

「蠢毙了。」

——为什么脑子里会掠过在贫民窟看到的花海呢？

3

——爱西亚湿地地带攻防战，跋利耶尔南方子爵大本营。

「在湿地地带北部又发现两处魔法阵！这样总计有八处！」

「画在地图上。位置要准确无误。」

冲进来的传令兵，于挂在墙壁上的地图留下红色记号。描绘爱西亚湿地地带的地图上，已经有四十个一样的红色记号。

战争开打后约六个小时，战场就不断传来发现魔法阵的报告。自从在卡斯泽尔平原吃了大败仗后，应对魔法阵就成了王国军的最优先事项。结果就是，自卡斯泽尔之役以后，亚人利用魔法阵所做的陷阱都没能达成亮眼的成果。

「再怎么说，这次的数量太超出常轨了。」

瞪著地图、俯瞰战场的莱夫面露险峻。

「果然是要像卡斯泽尔那次一样，进行包围歼灭战吧。」

「在应付方法都广传开来的现在吗？若亚人的大参谋无能到这种地步的话就要谢天谢地了，但假如不是的话，是不可能用这么再明显不过的手法的。」

「毕竟是亚人……有一半混到了野兽的血统不是吗？」

部下觉得没什么好奇怪的发言让莱夫动作停顿，接著用冰冷的目光瞪向部下。

「你说是因为混到了野兽的血统？那能作为轻视敌人的理由吗？假使遇上野兽就能轻松获胜的话，那你现在去猎一只白鲸回来看看呀？」

「是……啊，不……」

「无能又没想法的人就乖乖闭嘴。假如忘了脑袋怎么用，那留你在本营也没意义。——想去最前线活动身体吗？」

「真、真的是非常对不起！竟然自以为是地出嘴！」

朝著垂头丧气退出本营帐篷的部下冷笑后，莱夫再度面向地图。而身旁则是晃著蓝色头发身著军装的女子——罗兹瓦尔。

「说得真狠呢。他觉得是好的所以才讲出来吧。」

「善意的行为就一定会得到善意的回报吗？愚蠢。事物都会得到相对应的结果。既然轻率地给予劣评，那下场也会是一样。你有意见吗？」

「并——没有呀？因为我也很讨厌无能～之辈。」

见罗兹瓦尔摇头，可能是心理作用，莱夫愉快地鸣动喉头。

「绝佳判断。——我想听专家的意见。这次的魔法阵布阵，你怎么看？」

「完完全全地不自～然。不只数量，配置也很奇怪。依照这次布阵的法则来看，恐怕地图上的这里和这里，还有这一带都有密集的魔法阵。」

「我赞同。任谁一看都知道。这样的陷阱有价值吗？」

「明知是陷阱还是得破坏掉。有一种讨厌的感觉。……有件事我想确认看看，可以让我确认尚未发现魔法阵的这处地方吗？」

「有你的女骑士当护卫，我再派十个人陪同。千万别进入交战区域。」

在地图上，最接近本营的空白区域——依照布阵法则应该会有魔法阵。得到前往该处的许可后，朝著连目送都懒的莱夫优雅一鞠躬，罗兹瓦尔就步出帐棚。卡萝立刻靠过来。罗兹瓦尔朝著不安的女骑士微笑。

「我有事想确认。接下来要进入战场边缘。麻烦你护卫了。」

「这没问题……不过您又亲自涉足危险之处了。」

「还比不上你的——男朋友。跟最前线相比，接——下来要去的地方还算轻松呢。」

「格、格林才不是我男朋友！」

「我一个字都没提到格林·法先这号人物～呀。」

不打自招的卡萝红透了一本正经的脸庞。罗兹瓦尔看她这样，笑了起来，接著只用黄色的瞳孔凝视持续冒出黑烟和发出地鸣的战场，说：

「——史芬克丝，你在打什么鬼主意？」

4

决定深入战场中央的方针后，卓格夫队就像颗子弹一样勇猛突进。

势如破竹的他们接连粉碎挡住去路的亚人族。在绵密的合作攻击中，有疯狂肆虐的斧击以及精巧的盾术等不胜枚举的勇姿，但其中有个存在格外突出。

挥剑刮起风的可怕剑士——不，是「剑鬼」。

银色闪光断人手脚，突刺贯穿喉咙和心脏，毫无慈悲的剑技精准地葬送生命。接近他的敌人会被切割，就算拉开距离也会被瞬间接近然后被贯穿。

亚人族被精炼过的剑气震慑到无法动弹，使得战场上不断量产亚人之死亡。

「那、那是、什么啊……要跟那种东西战斗……」

有人战意萎缩，甚至丧失。在战斗前就知道压倒性的实力差距，接触后又会被无意义地屠戮。面对这现实而后退的年轻亚人，肩膀突然被某人碰触。

「——退下。挑战赢不了的对手只是有勇无谋。逃离这种敌人，人家不会嘲笑他胆小的。」

声音的主人顾虑害怕退缩的亚人，并往前走。

个头高到需要仰望，全身覆盖绿色鳞片，有著蛇头的亚人。手上的剑——中央是握把，两端是剑刃的双头剑。

「那边的剑士，请留步！依我所见，你是武艺高超之人。能否让人家直接担任你的对手呢？」

蛇人以高亢的嗓音呼叫，正在跳剑舞的影子停止动作。

威尔海姆放下染血之剑、紊乱吐气，喷发的剑气化为杀气刺向敌对者，光是用瞪的就让一群亚人浑身发抖。可是。

「真可爱的杀气。挺有模有样的嘛，小子。人家来陪·你·玩。」

对直射而来的杀气嗤之以鼻，高个子提起双头剑飞冲过去。于此同时，威尔海姆也蹬地回应。彼此的距离在一瞬间消弭。

旋转身子，使出纵向劈砍。电光火石的一击瞄准的是头部，却被从正下方伸过来的剑刃给弹开。尖锐撞击声和火花四散后，抽回被弹开的剑接著使出下一击——

「啊哈！这样子可是追不上人家的速度喔～！」

「吁——！」

身子往后仰，双头剑已来至眼前。下巴被削到，紧追而来的连击一口气冲破防线。

这把武器有著两把剑刃，集攻防于一体的斩击编织成杀戮舞蹈。

「——是利布雷·菲尔密！蛇人族！『毒蛇』！亚人联军的台柱之一！」

在千钧一发的连击交织出的攻防激战中，有人道出高个子的身份。亚人——利布雷在别人的介绍下加深笑意，夸耀似地从嘴巴伸出长长的舌头。

「才不是什么台柱呢。这种说法，听起来不就像是根粗壮的柱子？用那种说法形容人家这种纤细的女生，不会太过份了吗。」

「至少你说自己纤细这种话，是恶梦级的玩笑啦！」

「讨厌，嘴好贱。太狂妄了。——让人想吃了你。」

才说完，利布雷的表情就骤变。瞳孔变细，嘴巴也发出蛇类的吐信威吓声。而且，杀戮舞蹈的速度一口气上升许多。

「——威尔海姆！」

以肉眼追不上的速度刮起来自四面八方的凶猛剑刃暴风，让威尔海姆只能防守。

被穷追猛打之际有人叫自己的名字。是格林，还是波尔德？是谁都没差。不管是谁，都不准插手。这个战场，这个好敌手，都只属于自己。

「哈、哈哈……！」

「——你在笑吗？」

「哈哈哈！哈哈哈哈——！」

笑声蜂拥溢出。冲动停不下来。在胸腔内膨胀的，就是欢喜本身。

在欢喜的催促下，用剑身承受步步进逼的双头剑。架开一招，剑光朝尚未恢复平衡的利布雷冲过去。利布雷硬是倾斜身体避过这一击，紧接著威尔海姆就踢中他身体加以追击。

「呃呜……！？」

出乎意料的威力让利布雷弯腰，但往上顶的膝盖撞碎他下垂的脸。淌血蛇头尚未垂落，画出弧形的斩击就瞄准他的喉咙逼近。

「讨厌！挺有本事的嘛，毛头小子却还这么嚣张！」

斩击陷入左手，鳞片只承受攻击一瞬间，接著手腕就被切断了。但是，利布雷抓紧这瞬间的机会，压低身体一拳揍进威尔海姆的肚子里。

肋骨发出声响，内脏生痛。在这股威力下，威尔海姆的身体直接朝后飞出去。尽管在地面滚动分散冲击力，却还是没能完全卸除。混著血的胃液一口气从嘴里溢出。

「威尔海姆！可恶，我去助阵！」

「少、少说蠢话……！那家伙是、是我的……是我的猎物……！」

「——不，你错了。他是王国的猎物。也就是我们所有人的猎物。」

格林和波尔德站在呕血的威尔海姆前面，同时其他队员也散开来包围住利布雷，堵住他的去路。

「唉呀呀呀……围殴失去一只手的伤心女子，这样不会伤了骑士道吗？」

「我们就跟外表一样是群莽汉，欠缺讲起来好听的骑士道精神。」

「而且利布雷·菲尔密，我听说蛇人族就算断手断脚也会再生。」

「哦，真博学多闻。因为会累，所以我讨厌再生。」

站在包围网外头的皮波特说，利布雷则是举起失去手腕以下的左手回应。断得干凈的切断面蠕动，接著隆起的肉团形塑出左手。真是惊人的再生能力。

蛇目瞪视周围，四散的亚人们都被歼灭。利布雷难过地垂下眼帘，朝著逼近自己的卓格夫队敲手。

「贯彻实力主义，部队的能力也很够。那边的小子……是剑鬼吧。」

「喔！亚人军的大将也知道剑鬼吗！你发迹了耶！」

「请不要用大将这种毫无魅力的字眼。人家才不是那种人物呢。那种只有男人味的称号，只有巴尔加那笨蛋才喜欢啦。」

利布雷双手抱胸，长吐一口气，接著仰望天空。

「就算是人家，要一个人跟你们卓格夫队打也太吃力了。」

「那么，你的对手就只有我一人……！我要把你的头砍下来……！」

喘气的威尔海姆走向前，要求接续刚刚的舞蹈和剑舞。但是利布雷却朝他耸肩，接著高举双头剑——

「是很想陪你跳啦……但差不多到了开幕时间了。人家感到很抱歉。」

「你讲——」

讲些什么鬼话，但却没时间确认。

一开始感受到的是空气中的变化。原本笼罩战场、混和杀气与鲜血的沈闷空气，开始转为带有温热黏性。

——紧接著，手脚沈进「水」里。

「什么……呃！？这家伙做了什么！？」

「你们呀，太害怕魔法阵了。发现了一个就销毁一个……给预料到这点的人来说，不设个陷阱对不起自己嘛。」

「你说魔法阵……」

自从在卡斯泽尔平原大败之后，王国军在战场上就以破坏魔法阵为最优先事项。卓格夫队也是只要发现就彻底破坏魔法阵，在这次的战场上也已经毁掉一个了。

「魔法阵要输入魔力才能发挥效果。你们似乎太害怕那效果了，但其实打从一开始魔法阵就是在发动状态了喔。」

听了利布雷的话却还是不懂意思。感觉穿著战铠的身体像泡在水中一样，手脚沈重，连呼吸都很困难。不只威尔海姆这样，周围的我方人员全都如此。

然而，却只有利布雷丝毫不受影响。

「这些是蓄积魔力的魔法阵啦。然后全～部被你们破坏了。所以说，蓄积在里头的魔力就流了出来，通过藏起来的正牌魔法阵，接著好戏就上演啰。」

「为了什么要绕这么大一个圈……就算一开始有正牌魔法阵……」

「要是准备很明显的巨大魔法阵，你们就不会靠近了吧？先洒一点饵，才能钓到真正想要的……而且，战场可不只有这里。从今以后，你们就再也不敢随便碰魔法阵了。」

皮波特挤出声音发出疑问，利布雷从容不迫地回答，说出这次的战场状况，以及未来的战场情势，还有巴尔加·克罗姆威尔的策略。

利布雷仰望天空。跟著往上看的话，就会发现空中已经被染成紫红色。变色的天空覆盖整个战场，恐怕那就是魔法的效果范围。也就是说——

「要分辨人类与亚人，就是外观和身上流的血液。本以为不过如此而已，但光是如此，似乎也就足以把我们的世界割分得够开了。——从现在开始，我们将要扭转情势。」

5

「这个感觉是……！梅扎斯大人！」

「被摆了一道～呢。今天的战场……不——对，自卡斯泽尔之后的魔法阵都只是幌子，一切全是为了这个真正的魔法阵所做的——布局。」

卡萝难受到跪地，身旁的罗兹瓦尔皱著眉头瞪著魔法阵。

离开本营去调查魔法阵，魔法阵却在调查途中忽然发动，而且效果范围大到包含整个战场。

结果就是全身像浸泡在黏液中，呼吸和行动都有困难。

「呼吸……身体，好重……！」

喘气的卡萝满身大汗，莱夫派来的士兵也一样。看样子魔法阵造成的影响有个人差异，不过所有人全都跪在地上呻吟。

「如果这个魔法影响到整个战场……」

「不是如果，而是——正是如此。恐怕亚人不会受到影响。接下来就是让在陆地上的亚人屠杀在水中的人类。卡萝你赢得了吗？」

「我不想去想。既然这是魔法的效果，那梅札斯大人您可以解除吗……？」

「解读出魔法阵的术式是有可能阻止～啦——不过，正因如此。」

说到这儿，话语中断，罗兹瓦尔仰望紫红天空，眯起异色瞳双眸。这时，「那个」在她眼前翩然落下。

「——就知道你会来这里。」

「假如要说有谁可能阻止这个魔法，以至今的观察来看，道出的答案是你。这次劳心又劳力，要是魔法阵被毁了，我会很伤脑筋。」

说话毫无抑扬顿挫、身披白袍的少女翩然落地——是长袍里头蕴藏可怕阴森之气的魔女史芬克丝。

「你会在意我让我很——惊讶呢。害我差点吐出来。」

「拥有高度专门知识的人很重要。可以的话，很想让你帮忙把不完美的我变成完美……」

「老师有尝试过，但失败了。而你就是在过程中诞生的失败作品。——必须消灭。」

面对史芬克丝的邀请，罗兹瓦尔断然拒绝。听到答复的史芬克丝举起手，指著一名难受不已的士兵，然后——

「——刚刚就是你的回答？」

白光一闪——在眨眼间飙窜的光芒贯穿士兵的喉咙，使对方的头部蒸发。接著又一人、两人、五人。总计出现六具无头尸体。

「啊、啊啊……」

动弹不得，只能眼睁睁看著杀戮上演的卡萝愕然失声。

就算行动没有受阻，光芒的速度和威力也难以回避。凭本能就知道，假如对方的手指心血来潮稍微偏向自己的话，那就要跟这世界说再见了。

磨练的剑技还有高昂的斗志，在这怪物面前都毫无意义。

「我再问一次。你愿意帮忙把不完美的我变得完美吗？」

只是修饰用语，内容还是要挟。她就是要罗兹瓦尔的身或心之一屈服。

但是，罗兹瓦尔却对著指向自己的毁灭手指摇头。

「我应该说过。——我一定会杀了你。」

「真遗憾。」

淡淡应答后，史芬克丝的手指发出白色光芒。

光芒就在卡萝的眼前，直接瞄准罗兹瓦尔射了过去。

6

战场处处都有哀嚎和临终惨叫闯进威尔海姆的耳朵里。

「唔——！」

双膝用力到发抖，同时拼命呼吸，才勉强站起来。头好重，手脚酸软疲累。不管多么大口吸气，需要的氧气都无法充满肺部。

同样的现象也发生在波尔德他们身上，恐怕其他战场也一样。而且是只对王国军——只针对人类才有的效果。

「就算给予人类十倍的死伤也会输，这是人家的意见。而现在的状况是巴尔加的答案。给予你们一百倍、两百倍的死伤，你们也还是不会改变态度吧？」

「开玩笑！就算战到最后一兵一卒，我们也不会臣服于你们！」

利布雷摇晃双头剑，用战斧插地撑著身体的波尔德则是破口大骂。觉得他很吵的利布雷皱眉，以长舌头指向喘气的士兵们。

「有骄傲是好事，但非得互相伤害到灭掉其中一方才满意吗？所以人家才讨厌野蛮又下流的男人。讲话一点建设性都没有。」

「……你的意思是，想要进行有建设性的对话吗？」

打岔的是脸色苍白的皮波特。额头冒著汗水的他继续说：

「在这场战争的胜负中，你期望什么？」」

「那还用说。——安宁。不会被不分青红皂白杀害，不会被不可理喻践踏，我们亚人能够确实安稳地过著每一天。我们就是为此而开战的。」

「……跟巴尔加·克罗姆威尔的声明差很多呢。」

「是那个笨蛋讲话太极端了！……不过，让巴尔加变成那样子的是你们人类。人家也想朝那家伙的憎恨火焰投入理解。为此，你们人类就得败北和做出让步。」

虽然想法不同，但利布雷也期待亚人族获胜。他目光离开皮波特，双头剑朝向波尔德。

「砍杀不能动的骑士是最下流之举，但要是能挫折人类心灵的话，就让人家利用你们的威名吧。一旦歼灭卓格夫队，士气也会瓦解吧。」

「……你以为我们会就这样让你动手吗！」

「人家也很心痛呀。可是，人家是利布雷·菲尔密。就算有期望和不期望的事，都要将獠牙插进人类好彰显亚人族的怒意！波尔德·卓格夫，就请你死在这里了！」

说完，利布雷的修长身躯朝波尔德跳过去。在头上旋转的双头剑化为斩击风暴，盈满杀意意图切割大块头躯体。每个人都忍不住别过眼。

——而就在此时，剑鬼的一击从旁袭来。

「吁——啊啊啊！」

「你还能动……！？」

掌握身体能动的程度，威尔海姆以最小的动作破风斩击。利布雷立刻用双头剑弹开斩击，但剑鬼的穷追猛打还没放过蛇人。

一下瞄准落地的脚，一下瞄准后仰的脖子，一下瞄准闪避攻击的身躯，剑刃没有停歇。铿锵摩擦声和撞击火花四射，剑舞与杀戮舞蹈在战场上互咬不放。但是——

「虽然逞强但太钝——！太慢啦——！太虚弱了——！现在的你赢不了的！」

被压制住。这是当然。面对在陆地上互砍都平分秋色的对手，却只能用像在水中挣扎的动作应战。在这种状态下互相拼搏，根本不可能会赢。

即使如此，威尔海姆不允许自己不抵抗就倒地。

「为了同伴而送上门的姿态很伟大，不过到此为止了！」

「开什么玩笑！谁是为了他们——」

利布雷的叫喊，在威尔海姆的心中点燃一盏灯。可是，手的动作跟不上愤怒。宝剑被双头剑弹开，下一击逼近毫无设防的身体。要被一刀两断了，这样的确信让血液冻结。

接著是轻微冲击，和沐浴在热烫鲜血中。

「——啊啊，真的专门抽到下下签。」

「皮波特——！！」

波尔德仿佛呕血般的绝叫。在威尔海姆眼前被砍到倒地的是皮波特。他的身体从左肩被斜砍出深深一道伤口。

009

因为他挺身挡住利布雷的斩击，好保护威尔海姆。

「……别让威尔海姆死！不能让他死！」

仰躺倒下的皮波特，用至今未曾有过的大嗓门叫喊。其他队员听到后都奋起，逼使沈重的身体面对利布雷的双头剑。

根本不可能会赢。缓慢的动作被舞动的剑刃掌握，接二连三在战场开出血花。

「……住手。」

被皮波特庇护，即使如此还是因伤跪下的威尔海姆低诉。卓格夫队的队员，就在自己站不起来的时候一个一个倒下。

「住手啊——！」

喊出涌上来的激情。那是朝向利布雷，还是朝向不惜牺牲性命保护自己的队员们，连他自己都不知道。

这段期间，双头剑切割队员的声音依旧无情响起。尸体逐渐增加。

「你们都是好男人。……为什么会变成这样？」

「谁知道，为什么呢？我也不知道。……不管怎样，就是不能让威尔海姆死掉。因为那家伙，是露格尼卡王国的剑！」

丢掉剑、架起盾牌的格林正面防御住利布雷的斩击。精通承受敌方攻击的战术在此开花结果，格林奋战的时间比其他队员还要长。

但跟被一击毙命的队员相比，也只多撑了五招。

「——咳呃！」

盾牌赶不上，双头剑在格林的咽喉浅浅挖出了一道伤口。受到致命伤的格林翻白眼，盾牌脱手，整个人倒下。血沫在伤口膨胀，盾牌卫兵手脚痉挛。接著毫不留情的一击朝格林挥下——

「嘎啊啊啊啊啊——！」

被死亡逼疯的身体跃起，威尔海姆朝利布雷飞扑过去。意料外的反击让利布雷反应慢了半拍，两人纠缠在一起倒向地面，滚进坑洼。

两人轮流占据上方的位置，在滚进坑底之前都在互殴，边流血边发出野兽吶喊。剑鬼与蛇人就这样滚进最后的战场。

7

——朝罗兹瓦尔放出的白光，速度濒临肉眼能捕捉的极限。

因此卡萝无法完成自身的职责，只能束手无策、眼睁睁看著罗兹瓦尔蒸发。但放弃的心境马上转为惊愕。

「……吓我一跳。」

「我说过了吧？我是要杀了你的人。」

史芬克丝按住挨揍的腹部，头一次痛苦喘息。而成就这件事的人毫无疑问就是躲过白光，在一瞬间拉近距离挥拳的罗兹瓦尔。

她摇晃蓝色头发，做出微举双手的动作。

「魔法阵的影响因人而异……差异在玛那的循环性。也就是说，越有魔法使者资格的人，受到魔法阵的影响就越强。这样一来事情就简单了。越是资质低下的魔法使者，在魔法阵中也越能不受限地行动。」

「我听说你是魔法专家……」

「只是知识比大家丰富罢了。不过，没办法亲身——实践。这一代的罗兹瓦尔·J·梅札斯是个完全不会用魔法的天分低下之人。所以，才能杀了你。」

罗兹瓦尔边说边从怀中掏出拳套，戴在双手上。将拳头化为钢铁凶器，按照字面的意思杀死眼前的怪物。

「为了这一天，我自幼就锻炼体术。希望你能让我充分发挥。」

垫步快速，猛拳如风。迅猛使出直击的话连岩石都能粉碎的威力，顷刻间史芬克丝被逼得只能防守。

卡萝屏息，看著罗兹瓦尔使出的体术看到出神。武艺与架势完全无异于高手，已经抵达就连天才也要花二十年才能到达的领域。

自幼开始锻炼的那番话不是夸张，而是铁铮铮的事实。

承受威力足以劈断大树的一踢，史芬克丝轻盈的身体朝旁边飞出去。罗兹瓦尔脚蹬地追过去，拳头将魔女往下敲，让她呈大字形贴在地上。接著拳雨朝著稚嫩的脸孔粉碎头盖骨，使之陷入大地。但是——

「……超乎想象。是我观察不够。」

史芬克丝的身子眨眼间离开地表，飞至空中，擦拭嘴角。内脏受伤了吧，鲜血不断溢出嘴巴滴落。

仰望逃到空中的敌人，罗兹瓦尔愤恨地扭曲嘴角。

「你以为逃得了吗。」

「就这样待在你碰不到的地方，瞄准你攻击也是一种方案……」

「————」

「但我放弃。你八成也准备了击落我的办法。」

在罗兹瓦尔不放弃的眼神中看穿了什么，史芬克丝决定谨慎为妙。外表年幼的魔女往上飞，离罗兹瓦尔她们越来越远。

「梅札斯大人！那家伙，魔女逃跑了！」

「看就知道了。——要追是不可能了。还有，不要叫『那个东西』魔女。」

卡萝惋惜地说，不过罗兹瓦尔不睬。她卸下拳套，爽快地放弃追踪，接著走向魔力供给过多而在发光的魔法阵。

「复杂的术式与其说是为了追求魔法效果，不如说是为了令其难以解除而动了些小手脚吗。那东西对我的评价似乎——很高，但还是太小看我了。」

蹲在发光的魔法阵旁，罗兹瓦尔边玩弄土边这么说。然后，伸指进魔法阵，闭上一只眼睛。黄色瞳孔诡异闪动，下一秒——突然就听到像是玻璃碎裂的声响，罗兹瓦尔脚下的术式碎散。

魔法阵带来的效果消失，呼吸困难和手脚沈重的状况也跟著消失。红紫色的天空像是想起原本的颜色，卡萝在恢复夕照的世界中站起来。

「身体……！不对，梅札斯大人，刚刚魔法阵造成的损伤呢……！？」

「要影响战况，光只有五秒钟就很要命了。更何况持续了十分钟以上……好啦，会变怎样呢？」

「格林……」

将轻声呼唤心上人名字的卡萝留在视野一隅，罗兹瓦尔仰望恢复既有色彩的天空。

「果然，要在爱西亚消灭那个是不可能的啊。既然如此，决战会在——」

8

抵达坑底时，位在上方的是威尔海姆。

脸栽进过泥泞里，所以先吐掉口中的泥土，接著龇牙咧嘴咬断利布雷想要挣脱纠缠的手指，然后膝盖重击他腹部，再往后退开。

回过神时身体状况已恢复，于是重新握好爱剑指向利布雷。起身的蛇人也架著双头剑，两人面对面瞪著对方。

「魔法阵的效果已经断了呢。也不赖。斩杀不会动的对手不符人家的性格！」

「闭嘴，混账东西！王八蛋，竟然敢动他们……我饶不了你！」

「同伴被砍所以气炸了，原来剑鬼也有像人类的感情呢。」

利布雷的嘲笑，却让威尔海姆喉头一哽。

愤怒激情上涌到胸膛，感觉在血管里流动的不是血液而是岩浆。但是，这股愤怒的泉源来自何处，连威尔海姆也不知道，只能予以否定。

「不要乱讲话！我只是剑！就只是一把剑而已！才不会为了谁……！」

才不会为了谁生气或悲叹。美丽的钢铁，不需要那些感情就能完成。

正因如此，威尔海姆他——

「原来如此，不是不能懂呢。你现在，正在脱胎换骨的过程中。」

「——哼！」

「过来吧，小宝宝。人家教你——怎么发出呱呱落地声。」

威尔海姆踏地，果敢用力地砍过去。

为了迎击，亚人联军最强战士抡起双头剑。

9

「皮波特！皮波特，醒一醒！不要死，皮波特！！」

抱起气若游丝的皮波特，波尔德大叫。皮波特轻轻睁开眼睛，开始浑浊的瞳孔看到波尔德后，嘴角扬起微弱的笑容。

「少、爷……这样子、根本……不像您……」

「别说话！不对，继续说话吧！不要死！一旦失去意识就完蛋了！」

呼吸断断续续的皮波特抓住波尔德的颈部。他脸上血气尽失，伤口淌出的血流变少了。任谁一看都明白他受了致命伤。

不承认的，就只有在场的波尔德。

「少、爷老是……疏忽脚边……请要、留心……」

「弥补老子不足之处是你的职责吧！老子不许你放弃职责！」

周围的人都不再呼吸困难。但不只皮波特，绝大部分的人都已倒下。还有几个人有呼吸呢？在那之前，继续这样下去的话——

「少、爷……多、谢关照……了……」

「——皮波特？喂，皮波特！？不要讲蠢话！睁开眼睛啊！皮波特！」

吐出一口长气后，皮波特的身体失去力气。波尔德拍打他脸颊，用力撑开他眼皮。但是皮波特的身体文风不动，就像没了性命。

不，不是好像，而是真的没了性命。波尔德好歹知道这点。之前在战场上看过无数尸体，现在皮波特只是加入他们而已。

只是自己始终不愿意承认罢了。

「————」

「皮波特？」

皮波特的尸骸猛然震了一下。茫然的波尔德一脸不可置信地俯视皮波特。原本闭上的眼皮，现在缓缓张开。

然后，皮波特的双眼捕捉到了波尔德。

「皮波——呃！」

目睹奇迹的波尔德想要呼唤对方的名字，但皮波特的手指却陷入了他的脖子。脖子在剧痛和惊愕下后仰，皮波特的双手顺势直接绕上去，想要折断他的颈椎。

简直就像死去的皮波特要带波尔德一起上路似的。

「嘎、啊呜……！」

脖子被勒紧，波尔德的意识开始远离。皮波特发疯了？怎么可能。应该不只皮波特这样。到底发生什么事？视野一片白，就在这个当下。

「——！」

压在波尔德身上的身体，被持盾的格林给撞飞。两人几乎是交叠倒在地面上，但格林就这样站不起来了。反而是皮波特起身，发出如兽类的声音，双手朝失去意识的格林伸过去。

毫不留情的手指，挖开格林的要害夺去他性——本应如此。

「呜喔喔喔喔喔——！！」

波尔德的战斧带著豪风，从毫无防备的皮波特背后将他砍成两半。甲胄等物在这威力之前如同纸片。从正中央被剖成两半的皮波特倒卧在地，一动也不动。

是尸体。如今的皮波特，成了真正的尸体。

「————」

然后，扛著战斧的波尔德周遭被死去的卓格夫队员们包围。熟悉的脸庞失去生气，虚无的眼神紧盯著活人。波尔德大笑。

「哈、哈哈……哈哈哈！哈哈哈哈哈哈！」

被操纵的尸体。让尸体活动的恶魔花招——魔女史芬克丝的尸体游戏。

保全骄傲而死的战士，但魔女却玷污他们的死亡。当魔女的恶意寄宿在他们尸体上的时候，波尔德被迫理解到这点。

「魔女……！魔女、魔女魔女魔女魔女魔女魔女魔女————！！」

他发出灌注诅咒的叫喊，誓言要向不在现场的邪恶本尊复仇。

战斧呻吟，粉碎才刚死去的部下尸体。波尔德用斧击葬送逼近而来的尸兵，边敲击死亡边大笑。笑声持续不断。

笑著笑著，笑到最后，波尔德的哭喊声响在战场上回荡不绝。

10

剑舞和杀戮舞蹈交织成银色闪光。这一幕，终于要迎向最后结局。

在连血液都要为之冻结的精湛剑艺中，威尔海姆的速度更添锋利。像跳舞般操作双头剑的利布雷无法弹开所有攻击，身上开始累积伤口。

惊人的剑术能力，是超越想象的剑术才能，和自我锻炼到甚至连血泪感觉起来都像温暖所带来的恩赐。

对活了很久的利布雷来说，很难找到并驾齐驱者。但如今这等剑艺——而且还是如此年少的少年所有，实在值得惊叹和称赞。

想到他的未来就觉得打冷颤。不只剑技，他的人性面更让自己这么认为。

尚未完成。还不完满。不够成熟。还看不清自己的青春期少年。

——想要变成钢铁。想变成一把剑。少年这么吶喊。

以为这样命令自己，就能一直挥剑挥下去吧。他的斩击之重和锐利都不是半吊子的人可以抵达的领域。但是，以双头剑交锋的利布雷灵巧地带过利剑，同时感受到：灌注在剑刃里的激情热度并非无机质的钢铁。

是感情的热度。钢铁本身绝对不会发热。会被感情热度左右而让剑刃变得激烈的，除了人心别无其他。渴望成为剑的剑鬼，终究是人类。

「呵呵！」

「——有什么好笑的！」

激战中见利布雷笑，满脸是血的威尔海姆吼叫。

「没有啦……只是想到不管砍人还是被砍，木偶都不会因为对手而燃烧热情。果然还是要生存方式互相撞击，要会流血流泪的对手才能让人家燃烧热情呢～！」

是呱呱落地声。

火花的闪耀、互相敲击的轻快声响、践踏地面、发出的咆哮，全都是呱呱落地声。

每一击都是催生，斩击带有情感，剑击破口大喊放马过来。

既非钢铁，更非鬼魅。现在在这里的，就只是一名名叫威尔海姆的少年。剑刃交锋的对手是一介人类，而跟他面对面的自己是一个亚人，方是这场战争真正的本质。

勉强卸下上下连击，旋转身子的威尔海姆砍过来，斩击逼近脖子。利布雷抬起双头剑，承受斩击——接著双头剑剑刃碎裂，这一击就这样直接刺进脖子。

视野染成一片红。但是，威力衰退的钢剑无法穿破利布雷的鳞片。剑卡在脖子上，利布雷以没有碎裂的另一头剑身扫向威尔海姆。

种族差距，与生俱来的特质差异为战斗分出胜负。——内战的理由，就在这里。

「结局……不一样呢。我们没法理解彼此吗？觉得稍微了解了你一点，是人家的错觉吗？」

按住胸膛的伤口，持剑戳向仰躺倒地的威尔海姆。死亡迫近眼前，但少年充满杀意的眼神却不认输。

见到与高洁无缘的执著，利布雷的心被悲伤支配。

「你果然是人类，真真切切到令人家伤悲。同时，你们是威胁这点也没变。所以很遗憾，再见了。」

不能让你活下去。在战斗中拉出对手的人性却这样是搞什么东西！大概会被这样骂吧。但是，对一个人类有好感，和身为亚人的自豪，是两码子事。

利布雷·菲尔密的立场，让他不能以个人情感为优先。他知道，自己的一言一行全都会被亚人族仿效，因此——

「等一切都结束，人家会到你坟前供花。——供奉火红的热情之花。」

扬起双头剑，一面希望期望至少不要给剑鬼太多痛苦，利布雷带来死亡。

——白光从后头贯穿利布雷的胸膛，就是在那瞬间发生的。

11

以为死亡降临的那一瞬间，却没想到会目睹对方的性命在眼前燃烧。

「——咳呼！」

嘴巴吐出血和长舌头，颤抖的利布雷一脸惊愕地转头看向背后——看著突然出现在后头的魔女史芬克丝。发出白色光芒的手指正指向他。

「你……打算、干什么啦……」

「是。其实我遭遇出乎意料的打击，现在正在撤退。这段期间，我想要有实力的人保护我，因此就拿附近的你当候补人选。」

低头看到胸口开了一个洞，触碰不会流血的伤口，利布雷浅浅一笑。

「这样啊……可是人家看不出你有拜托的意思耶……」

「谈判的时间很宝贵，只好让你早点死掉当傀儡。请放心。我听巴尔加说过你的存在很有价值。因此就算你变成尸兵，我也会彻底做好防腐处理。要·深·思·熟·虑。」

「巴尔加…那个白痴。我早就…跟他说过…不可能驾驭得了……」

抓紧剑身受损的双头剑，利布雷与史芬克丝对峙。史芬克丝对他的态度感到不可思议，歪著头说：

「基于负伤和疲劳等其他问题，我判断你的抵抗毫无意义。」

「就算毫无意义，也不会坐等死亡到来。……人家可是亚人族的骄傲。——人家可是利布雷·菲尔密！不要瞧不起人家，臭女人——！！」

裸露牙齿，身体前倾冲出去。他的冲劲和速度充满了霸气，让人想不到他已经濒死。可是——

「本来不想弄太多伤，但没办法了。」

白光宛如迎击大炮，干脆地贯穿利布雷的胸部、膝盖和脖子。血液蒸发，身体被开了无数个硬币大小的洞后，利布雷倒卧在地。

「魔…女……你…做什么……」

「————」

「巴尔…加……之后…交给你……」

分不清是怨言还是遗言，总之利布雷的头部被白色闪光射穿，脑袋里头还顺势被搅拌一番。亚人族的最强战士就在此断送性命。

以剑交锋，即将分出胜负之际，上好敌手却在眼前被杀，威尔海姆气到叫不出声。

史芬克丝就在威尔海姆面前，用手掌触碰利布雷的尸骸。

「我会跟巴尔加说他是战死沙场，保全他的名誉。我有学到这种说法能讨人高兴。那么……？」

「站、站住……」

史芬克丝站起来，威尔海姆朝她射出杀意好制止她。但是面对敌意，少女表现得却像是轻风拂面。

「用不著觉得害怕，我不打算加害于你。快点离开这里，为下一次备战。要·做·足·准·备。」

「开什么玩笑……！你要、放过我？你打算干嘛？战斗……给我应战……！」

「——吓到我了。在这种状态还说那什么话。」

原本面无表情的史芬克丝，在听到威尔海姆的话后目瞪口呆。接著不住点头，兴致盎然地望著他。

「怎么看都是没法战斗的状态，即便如此却还渴求战斗。我不懂。是因为我的感情不完整吧。看样子，你似乎也是要·仔·细·观·察的对象。」

「观察……？」

「憎恨到痛苦的巴尔加，还有悲伤挥剑的利布雷都是观察对象。不过，身上的愤怒凌驾死亡的你，也是其中一人了。——我满心期待下次的观察。」

丢下这些话，史芬克丝就背过身。威尔海姆勉力撑起身体想要制止她，手脚却动弹不得。然而相较于无法动弹的威尔海姆，有人动了。

「……利布雷。」

眼神失去光彩，利布雷·菲尔密的尸体站了起来。成为表情虚无的尸兵后，利布雷丝毫不睬威尔海姆，而是跟著史芬克丝走。

就这样，修长身影与娇小女孩的身影，扔下威尔海姆从战场消失。

「……可恶！」

咬牙切齿到臼齿要碎裂的地步，诅咒没法动的自己的威尔海姆挤出这两个字。

瞪大眼睛，跪在漫天烟尘的战场角落，像咒杀一样满盈憎恨地这么说。

「给我记住……给我记住！你一定会后悔的。后悔让我活下来……我一定会让你后悔！可恶、可恶——！！」

呕血吶喊拉长尾音，剑鬼的败北为这一天的战场分出胜负。

直到被友军找到，甚至被带回军营，威尔海姆的悔恨都未结束。

大家都知道，唯有魔女的头颅落地，方是结束之时。

12

——爱西亚湿地地带攻防战，作为继卡斯泽尔之后吞下的第二大败仗，铭记在历史上。

虽然没像卡斯泽尔战役那样一面倒，但王国军的伤亡却将近卡斯泽尔的一倍，是内战开始以来人为伤亡最大的战役。

投入战役的王国军在短暂包覆全战场的魔法阵效果下，战力大幅下降。这段期间所受的伤亡占了整体的六成以上。

大本营沈重地接受这个结果，并将败战的责任归咎在解放双重魔法阵——也就是破坏最多魔法阵的阵营，莱夫·跋利耶尔南方子爵因此被当成战犯，进而被贬职。

莱夫对结果表达强烈抗议，要求大本营再度审议。但是，他本来就被怀疑谋杀前任指挥官克莱曼卿，众多部下又都举发子爵至今的残暴与蛮横不讲理，因此失去辩驳的立场。最后不但没能恢复名誉，连诉愿都被废弃。

以南方子爵为首的诸多武官被迫承担责任的期间，王国军内部因损耗了大部分的军队，不得不重新拆编。败战爪痕深深刻画在军队里，其中又以勇猛果敢为名的卓格夫队最为惨烈，生存者仅十一人。

波尔德·卓格夫、格林·法先和威尔海姆·托利亚斯的名字也名列其中。包含副官皮波特·阿南西在内，卓格夫队共有六十九名人员战死，而且每个人都化为尸兵，最后被波尔德杀死。

以此战役为契机，内战进入末期。往后的历史是这么陈述的。

这不单单是历史，参与战争的每个人，往后的生存方式都因此大受影响。

波尔德·卓格夫对魔女的恨意增加，倒向排斥亚人派。

格林·法先因伤及声带而无法发声，善良的女友因此难过不已。

而威尔海姆·托利亚斯自这天开始，他的剑道产生迷惘，决定要为自己的生活方式寻求答案。

——他追寻的答案一个人是找不到的。但是，得到解答的日子很快就逼近眼前。

** 五幕

1

——爱西亚湿地地带的大规模战斗结束后，过了一个多月。

这段期间，国内没有发生什么大战役，表面维持稳定。

但是，一旦观察过王国的内情，要是听到有人标榜这一个月很平稳，那可不是被嘲笑就能了事的。

加上爱西亚的损害，王国军伤亡人员超过四成以上，军队难以再做大规模编组，还要为战力大幅下降而烦恼。

而这类煽动的风声也并非与卓格夫队无缘。毕竟，以副官皮波特为首，包含元老队员在内，共近九成队员死亡，要重现濒临崩毁状态的队伍，基本上是不可能的。

以强焊闻名的卓格夫队，能够称为平安无事的生还者仅有威尔海姆和波尔德两人。但肉体姑且不论，两人的精神都受创了。

在那次战役所受的伤完全没有愈合，直到现在都还在溃烂生疼——

「总觉得，你咄咄逼人的感觉比之前更严重。」

看著默默埋头练剑的威尔海姆，少女突然这么说。

——地点在王都贫民窟一角，黄色花海旁边的大广场。

部队正在重组，威尔海姆现在尚未被发派，新的战场也尚未底定。每天活著就是在累积郁闷，因此在这边专注练剑成了他最近的例行公事。

如此一来，遇见在这里打发时间的少女的机会也增加了。在锻炼中被她说三道四早已习惯了。不过——

「——啧！」

「啊！你刚刚咂嘴了！」

虽然习惯，但不代表不会不耐烦。没有遮掩之意的咂嘴惹来少女不快。

「像这样明目张胆地咂嘴，感觉很讨厌。麻烦可以不要这样吗？」

「我要在哪练剑，在哪咂嘴，都是我的自由。就像你在这里无所事事浪费时间一样。」

「不要那样讲嘛。看花可以让心灵丰富……应该这样说吧？」

「真感谢你为浪费人生做了良好解释。」

彼此互呛后背过脸，已经成了默契。

休息时间到这里，结果还要被烦。虽然很愚蠢，但要是换地方感觉就像认输了，这又让人火大。结果，就是两人的邂逅次数持续累积。

「要我说的话，浪费时间的人是你吧。士兵真是闲差呢。我看你这阵子一直来这边玩。」

「……军队正在重组，暂时没地方去。做这种事也不是我的本意，反正我没有理由被你说是来玩的。」

「不是很开心地在那边咻咻挥剑吗？……只不过最近都不开心了。」

「——你懂什么！」

感觉被说中，为了帮自己找台阶下，所以口出恶言。

自己不是来玩的，但享受练剑的时光是事实。——不对，对自己来说，这段时间正是自己生命的充实之处。

而现在没法专注练剑也是被少女说中的事实。

『过来吧，小宝宝。人家教你——怎么发出呱呱落地声。』

——在爱西亚湿地地带，利布雷说过的话和双方的交手掠过脑海。

自己被逼到了几乎要被夺走性命的死路。

要是没有人来打岔的话，死的应该是威尔海姆。可是，战斗却被中断，那一天的对决就这样永远停留在那里。

「你～眉头又皱起来了！还这么年轻，等到皱纹不会消失，你就丢脸了。」

少女不知何时站在沈默的威尔海姆面前。威尔海姆对自己竟然一无所察感到吃惊，少女则是朝著他用手指拉高自己的眼角。

「眉头皱起来的话，眼神会像这～样变得很凶，还会让人觉得你浑身带刺……大家会怕你怕到不敢接近喔。」

「吵死了，跟你没关系吧。而且说我年轻，我已经……」

「十八岁。看起来跟我同年纪。对吧？」

少女指著他还眨眼，威尔海姆没法回嘴。她说对了。而自己脸皮又没厚到拘泥于无聊的小事，想将之蒙混过去的地步。

「喏，你看嘛。这点岁数眉心就有皱纹可是很丢脸的。反正都会生皱纹，不如用看花来做出笑纹吧？」

见他别过目光，给出最后解答的少女嫣然一笑。

接著像跳舞一样旋转，威尔海姆被她随风摇曳的美丽红发给吸引目光。然后，当红发消失在视野角落，取而代之的是黄色花海闯入眼帘。

已经不知是第几次，只要和少女邂逅就会被迫欣赏的花海。

所以，也已经习惯少女接下来露出的自豪面孔以及提问。

「——你喜欢花吗？」

到底是想要什么答案啊？而威尔海姆的答案也始终没变。

「不，我讨厌。」

他摇头这么回答。

2

「你又去城邑区啦。」

从贫民窟要回营房，就遇到用庞大身躯堵住入口的波尔德。

他抱著粗壮的手臂，用严厉的视线俯瞰自己。威尔海姆咂嘴。

「怎样，有什么好抱怨的？」

「当然，虽说军队正在重组，但亚人的野蛮行径不知会在何时何地发生。连军中的文职、杂勤人员，就算休假也要随时待命以备不时之需。这就是老子……」

难得滔滔不绝的长篇大论在中途中断，波尔德闭上眼睛后重新称呼自己。

「这是『我』跟你被要求要有的举止。」

「————」

他一个劲地主张正确的言论，让威尔海姆背脊发寒。

本来这番话不应该是由波尔德，而是由他的副官皮波特讲述才对。而被这么叮咛的波尔德就会拍著皮波特的肩膀反驳。

——波尔德·卓格夫在经历爱西亚湿地地带战役后，整个人变了。

外表没受什么醒目的伤，但他的内在产生变化，并强烈表现在态度上。

就像刚刚他停顿后的稳重表达，以及改用「我」而不是以「老子」称呼自己，处处都显示他发言时比以前更加注意自己的立场。简直就像死去的皮波特的幻影——灵魂在他耳边叮咛。

但是，最大的变化不是这个。只要跟他有点交情的人都知道。——当然，同队超过三年的威尔海姆也知道他有什么变化。

「你的剑术对现在的王国是不可或缺的。爱锻炼随你高兴，但至少要待在传唤下来便能立刻动身的地方。别忘了这点。我的要求就只有这个。」

说完，波尔德的脸上就只有带著严厉的苦闷情绪。从中看不出有转为笑容的征兆，而这正是他最大的变化——

「反正不管怎样，砍杀蛮族的事用不著我下指令，你也会做吧。」

对亚人深不见底的愤怒与憎恨——过去的波尔德绝对不会有的阴沈情感，迫使威尔海姆察觉到胸口有奇妙的隔阂。厌恶品尝到这股作恶的感受，威尔海姆相较以前变得更常避开波尔德。

「不久又会有大型战役。这是梅札斯女史说的。要做好觉悟。」

威尔海姆沈默，波尔德拍拍他的肩膀就离开营房门前。

不派使者而是亲自传达事情，这点总让人感觉还留有波尔德的直率，但威尔海姆立刻舍弃这份感伤。

在城邑遇到少女，在营房前又遇到波尔德，让威尔海姆心情很不爽。

进了建筑物，在回到自己房间的路上跟营房长擦肩而过。对方好像想说什么，但威尔海姆用视线让他闭上嘴巴，接著就快步回房间。

王国军的营房散布在王都各区块，威尔海姆被分配到的营房是供作上级士兵使用。对尚未成为骑士的士兵来说是最顶级待遇，而且能减少与他人接触的个人房生活也不赖。也因为这样，不请自来的客人让威尔海姆动怒。

「你一大早就出门啊。」

「……你为什么在这？」

「我表明身份，营房长就帮我开门了。我本来跟他说在楼下等就好。」

「多管闲事。」

想起在走廊错身而过的营房长可怜兮兮的表情，威尔海姆就忍不住咂嘴。

在房间等他回来的人是卡萝。脱去骑士装扮，穿上女性打扮的卡萝不像平常那样带刺。终究是庸浅的女人，威尔海姆心想。

当然，他不会犯下脱口而出惹人生气的愚昧之举。毕竟认识也很久了。

「仔细想想跟你认识超过三年了，但像这样好好说话还是头一次呢。」

「我可没打算好好说话。快点出去。」

「一点都没变耶你。还是有点变了……只是又变回原本的样子？以前你的眼神跟野狗和疯狗没什么两样。」

「你是特地跑来吵架的吗？放假还这样真辛苦。我奉陪。」

威尔海姆轻轻发出剑气，卡萝眉头一动，但马上叹气。

「我也知道你不欢迎我。事情结束了我马上就回去。」

「你除了来吵架还有其他事？」

「当然，是格林的事。我跟你之间没有其他共同话题了吧。」

听到格林这名字，威尔海姆一脸嫌恶。自从受伤之后，格林就被扔在治疗院。当然，威尔海姆从未去探望过。

这很正常。探病又没意义，而且自己跟他关系也没多好。

但是，卡萝却亲自到威尔海姆的房间——

「格林想见你。我是来告诉你这件事的。」

果然如威尔海姆所料。

格林和卡萝不知不觉间感情升温，后来成了情侣，这件事威尔海姆也有察觉。两个人要喜欢彼此是他们的事，但要来强迫推销温情，自己可敬谢不敏。

「当传令兵辛苦了。但是，我不打算照做。那叫白费力气。」

「你这人……」

「话又说回来，帮没法讲话的人传达意见，你还真灵巧啊。那家伙好歹会用笔写字吧……」

「——不要越说越过份，威尔海姆·托利亚斯！」

像是回敬他刚刚的行为，卡萝身上迸发出剑气。对此威尔海姆眯起眼睛，接著卡萝用力握紧手无寸铁的拳头。

「或许格林容许被你这样侮辱，但是，我不许你侮辱他！」

「感情很好嘛。但不要扯到我身上。」

彼此的危险视线交错，最后是卡萝先移开视线。威尔海姆才一哼，卡萝就缓缓摇头走向出口，然后说：

「或许白跑一趟，但我确实告诉你了。你好歹也回报一次战友吧。」

「我什么时候跟那家伙是朋友了……」

「格林认为你是他的战友。我以前也曾这么认为。」

撇下心虚的威尔海姆，卡萝迅速离开房间。门被用力关上后，威尔海姆不耐烦地躺在床上。

几度朝瞪视的天花板发出剑气，最后只有空虚盈满他胸膛。

3

那个地方充满腐臭和血腥味。

刺鼻的恶臭，让踏入小屋的巴尔加皱起脸。不过即使看起来老成的脸孔不悦地皱眉，他也绝对不会别过视线。

因为在这里的一切惨状，全都是自己的决定所造成的结果。所以他没想到要别开眼。

「……史芬克丝，进度怎么样了？」

没打招呼，就直接朝窝在屋子深处弓著背的小人影出声。长袍人影听到后站起来，用被血脏成黑褐色的袍子擦脸，然后回过头。

「过程要，仔·细·观·察……但不顺利。果然要重现缺损的关键部分术式，对只是母亲瑕疵品的我来说无法胜任。」

「明明是魔女却这么软弱……不，老朽只是在迁怒而已。」

看到巴尔加深深叹气，女孩——史芬克丝看向背后。

站在那儿的是浑身布满绿色鳞片的蛇人——曾经是利布雷·菲尔密的亚人。

「不忍卒睹啊。……太可怜了，利布雷。」

亚人族最强战士已经咽气，双眼失去生气。即便如此却还是站得直挺挺的，遵从魔女的命令挥剑。这是因为尸体受到能让死者活动的术式影响。

但只是单纯执行命令的尸兵，是无法完成利布雷的任务的。

「爱西亚的胜利使同胞热血沸腾，给予人类的损害也很大。明明这无疑是自这场战争开打以来，趁胜反击的绝佳机会……！」

「有你在就够了吧？还是说只要外貌还在，他的尸兵也能完成鼓舞我方士气的使命？」

「——不够。要站在同胞的前头，老朽的器量还不够。而且利布雷的领导者气势，内部空空如也的尸首根本不可能重现！」

瞪著变成尸兵的利布雷后，巴尔加用厚重手掌掩面。

爱西亚湿地地带作战战术进行得很顺利，给予王国莫大打击。本来应该乘著这股气势一口气压制敌人，却没想到利布雷会战死。虽然不甘心，但他的存在给亚人联军的影响远大过自己。

还好史芬克丝回收遗体，成功让他以尸兵的模式复活。但不管使用任何旁门左道的法术，都不可能让他恢复成原本的利布雷。

「就算复活，也没有灵魂。要重现『不死王的圣礼』真的好难。」

「少了利布雷继续打内战吗——没多少手段可以选了。」

「……但不是完全没得挑吧？」

史芬克丝眼睛微眯，巴尔加沈重点头。

当然，巴尔加有考虑到在战乱途中失去自己或利布雷的可能性。可以的话他希望是自己先走一步，但偏偏却反过来，或许这就是命运吧。

——用要是利布雷还活著，就绝对没法用的方法来打倒王国军。

「那家伙没法眼睁睁看著这世界化为地狱。……假如这个世界会变得比地狱还要悲惨，那家伙会用蛮力阻止老朽吧。」

「那么，在那个地狱里，你想要我做什么？」

「掀开地狱的盖子，用人类的惨叫和临终痛苦来慰祭同胞的灵魂。我命令你成为这条路的引路人。——用我憎恨的火焰，将整个王国化为灰烬吧！」

在内心深处猛烈燃烧、永远不会消失的愤怒之炎，将所有激情当作柴薪焚烧，最终将会烧尽一切吧。

这场憎恨大火绝不会熄灭。接下来要将这股确信化为真实。

「利布雷死了，老朽活著。既然如此，那就是这么回事了……！」

以无止尽的恨意为燃料，巴尔加的脑内开始建构可怕的盘算。这是在「亚人战争」当中，就真正的意义上成为「契机」之役的揭幕——

「——要·仔·细·观·察。」

也是决定「魔女」史芬克丝和众多人的因缘，并终结这一切的开端。

4

——亚人对王都进行恐怖攻击的情况，不断地零星发生。

「什么。你该不会是剑鬼……！」

「喝啊啊啊——！」

在王都外墙，威尔海姆朝著对包围王都的高耸城墙做些小手脚的团体吶喊。

少数的冲动犯行，单纯是凭著亚人优势而亢奋到控制不了自己而做的。

由于军队的编组迟迟没有进展，威尔海姆加入了王都警备队，之后就像这样多次斩杀这类不法之辈。

「我、我们的奋斗竟然以这种形式……我诅咒你，野兽……！」

受了致命伤，腹部被贯穿的最后一人吐出鲜血和仇恨。可是这类恨意威尔海姆早就听腻了。他转动剑锋，确实地送他赴黄泉。

「少吱吱叫了，白痴。既然怕死，好歹象样地挥剑啊。」

「……那么，就努力、用你自豪的剑……再过不久火舌会在国内……王都也没法躲过灭亡……」

「——？」

以诅咒而言，这段奇妙的发言未免有点太具体，总之对方还没说完就死了。

把死掉的亚人踹到一边后，其他卫兵终于跟收拾完亚人团体的威尔海姆会合。他们立刻就被眼前的惨状震撼。

「你、你、你是那个『剑鬼』威尔海姆……？」

卫兵是己方，但在道出那个别名后，连声音都变了。

不只敌人，也被己方的人畏惧。——这点威尔海姆也早就习惯了。

剑鬼的别名和威尔海姆的名字，现在都只是染血的恶名。

所以——

「我是特蕾希雅。听到了吗？要这样叫我喔。你是……」

「————」

「你是……」

「——？」

「够了！你真的不懂吗？我当然是在问你的名字啦！」

鼓著腮帮子跺地的少女——特蕾希雅发起脾气。

地点是老地方的广场，时间是威尔海姆练完剑后。不甘不愿配合招手的她眺望花海的时候，突然出现这个话题。

「不要老是叫『你』或『女人』，要叫我名字啦。」

面对这么表达不满的特蕾希雅，威尔海姆的答复是自己又不知道她名字。听到这话她瞪大眼珠。确实，都认识三个月了，却还不知道彼此的名字。

特蕾希雅接著轻咳一声，莫名正式地报上姓名，也就是一开头那句话。

「特蕾希雅……」

不自觉念念看，感觉很有她的风格。仿佛给人置身在向阳处的微笑，虽然很多话却也有可爱之处。情绪起伏剧烈这部分有点难搞，但特蕾希雅——确实比花女这个称呼还要好听。

「慢著！干嘛不说话？有没有在听人讲话啊？」

「……嗯啊，不错的名字呀？」

「咦，喔……是、是吗？算了，被你这样讲感觉也不赖……」

「我之前都在心里叫你花女咧。」

「咦咦咦咦咦……」

只是多补充一句，特蕾希雅的表情就整个大变。一下害羞一下愤怒、脸蛋红通通的她想要踩威尔海姆的脚，但都被闪过。

「够了！你这人真的很讨厌！还有，你到底有没有要回答？」

「——？」

「你那什么我在讲啥的表情！？我不是问了好多次你叫什么名字吗！」

特蕾希雅再度跺地，威尔海姆还想说她为何这么生气——他对这么思考的自己存疑。本来这话题只要回报自己的姓名就好，这样的响应才正确，而且也没有惹人嫌的道理。

——就算她对这个名字感到畏惧或嫌恶，那也没差。

「威尔海姆·托利亚斯。」

威尔海姆报出姓名，特蕾希雅楞了一下。

只要知道「剑鬼」这个别称在王国军中是怎么被传播的，那爱花的她也会感到排斥吧。一这么想，胸口就莫名喧嚣。但是——

「威尔海姆。嗯，威尔海姆。威尔海姆。威尔海姆。」

「……不要念那么多次。」

「呼嗯～是个好名字不是吗？你这个人的形象就很符合这名字。」

是要报刚刚的一箭之仇吗，特蕾希雅这么说的时候眼中带著淘气。对此威尔海姆沈默，不知该怎么处理内心的情绪。

「不过话说回来，还真好笑。」

「啊～？」

「因为，从第一次见面到现在都三个月了……现在才知道名字，很奇怪呀。」

特蕾希雅吐舌，害臊地笑。光是她这样的举动，威尔海姆就觉得刚刚的情绪烟消雾散。很不可思议的，感觉身体变轻盈了。

「不知道名字很正常吧。我跟你对彼此又没有兴趣，就只是各凭高兴跑来这儿，照自己的意思度过而已。」

「是吗？可是，我对你不是没有兴趣喔，也不是不了解你。像是威尔海姆，你讨厌花吧？」

「……嗯，对啊。而特蕾希雅，你喜欢花。」

「没错！你看，就算什么都不知道，但并不是不想去了解啊。」

特蕾希雅「哼哼～」骄傲地挺起胸膛，威尔海姆忍不住嘴角上扬。以他而言，这笑容难得纯粹，不是讽刺也不是挖苦。

「对了，威尔海姆。——你喜欢上花了吗？」

立刻摩擦脸颊好掩饰脸上的笑容时，突然被这样问。

每次都有的问答题。——只不过，今天的问题意图略有不同。

「不，我讨厌。」

即便如此，威尔海姆的答案还是没变。看花又没什么好处。

对他来说，重要的事绝对无法靠赏花得到。

「是喔。既然如此……」

不过，平常在这儿就理应结束的问答，今天却还没结束。特蕾希雅摇晃裙摆转向后方，不让威尔海姆看见自己的表情。

「你为什么要挥剑？」

「————」

这是她从未问过的问题。

从初相遇后的这三个月，两人之间必定有著剑舞和花海。可是至今特蕾希雅从未触及威尔海姆挥剑的理由。

交换名字后，她进一步地踏进威尔海姆的内在。

要是平常的威尔海姆，若对象不是特蕾希雅，这会是被他回避的问题——

「……因为我只有这个。」

但是，威尔海姆却在心境十分沈著的情况下，回答了她的问题。

关于剑的问答。为什么要挥剑？——答案在心中是再单纯不过。

只有这个。没错，威尔海姆比任何人都相信这点。

「————」

特蕾希雅只是沈默，没有任何只字片语。

就跟听了威尔海姆对花的问答后一样。

话多又心浮气躁的她总是重复提出的，答案不变的问答题——光凭如此，总觉得原本跟她之间的不确定关系就转趋稳定。

「————」

威尔海姆也没有不识趣地继续开口。

5

『没想到你会来。』

在床上坐起上半身的格林，睁大眼睛在纸上写字，拿给他看。

地点在王立治疗院格林的病房。不过，他的病房是同时容纳许多伤者的大房间。从床位的多寡就能窥见治疗院的繁忙。

「办完事后一时兴起。」

简短回应后，威尔海姆双手抱胸站在格林的病床旁。

跟特蕾希雅分开，双腿就奇迹似地跑来探望格林。跟字面意思一样，就只是一时兴起。没有排班，回去营房除了睡觉没事可干。就这样而已。

「还有啊，如果不过来，你的女人会很吵。」

『请不要那样说卡萝小姐。』

「……麻烦耶。不说总行了吧。」

自己讲一句，格林就要花时间用笔响应。他不挑纸也不润饰字句。直到一张纸被写满之前，两人就这样一应一答。

「————」

看威尔海姆焦急的样子，格林过意不去地笑，指指自己的喉咙。

喉咙上有白色伤疤，象征格林的发声器官严重受损。即使能发出类似呼吸的气声，却再也没办法发出能充作语言的声音。

『捡回一条命，运气很好呢。』

「……被那个利布雷砍到还活著，确实很幸运。」

『卡萝小姐呢？』

「你觉得我们的关系有好到会一块来吗？别开玩笑了。」

这次会一时兴起来探病，发生的机率足以与天崩地裂匹敌。而且要是关系形同水火的卡萝和他一块来，光想就让人倒抽一口气。只有那种情况绝对要避免。

「我没打算再来第二次。你可要跟她讲我有来喔。」

『知道了。我会说的。』

得到首肯后可以暂时安心。这样一来，就不用担心卡萝会紧迫盯人碎碎念。要不是如此，威尔海姆也不会刻意来探病。

『队长怎么样了？』

「简直就像皮波特附身，恶心死了。好好干呀。多杀一点亚人。最近专门讲这些。话是没以前多啦……但却觉得比以前吵。」

据说波尔德也有来探病过一次，但忙到马上就离开，王国军现在混乱到极点，连士官都被迫要应付各式杂事。波尔德也不例外。

「————」

格林突然停下手，看著远方。曾看过他这种表情。那是在王国军公墓里，目送战友时所流露的表情。

所以自然就知道他是在悼念在爱西亚丧命的卓格夫队同伴。

倚著窗边双手抱胸的威尔海姆也回想起在爱西亚的激战。之前就反刍过那场战役好多次，可是都忘不了没能决战到最后的利布雷以及中断决战的史芬克丝，每次想到都一肚子火。

不过，这次不一样。刚刚掠过威尔海姆脑内的，是那时候——

「……他们为什么要保护我？」

皮波特帮威尔海姆挨了一剑，因此殡命。而其他队员都遵从皮波特倒地时的吶喊，挺身对抗利布雷而被接连砍死。

格林也是。他也代替威尔海姆和利布雷战斗，最后留下永远都不会消失的伤痕，以及失去声音的永久后遗症。

——搞不懂。他们没一个有胜算。假如魔法阵的效果一直持续，威尔海姆也会命丧当场吧。所以实在搞不懂他们那样做有什么意义。

「挑战赢不了的对手，你也变成了这副德性。皮波特和其他人都死了，我也……」

要是没有史芬克丝插手的话，自己也会死。而威尔海姆一死，卓格夫队挺身而出的行为就全都会变成白白送死。要是变成那样的话——

「————」

「……你在笑吗？」

在低垂眼帘的威尔海姆面前，格林的反应有所变化。他抖著肩膀，震响沙哑的喉咙发出像咳嗽的声音，看起来是在笑。

出乎预料的意外反应让威尔海姆说不出话。于是格林拉近纸笔动手写字。

『抱歉笑了。我没想到你会有这种反应。』

「……那是我要说的话。我没想到你是会嘲笑他人生死的家伙。」

『我也是。没想到你会在意皮波特先生和队员们的生死。还有，居然会因为没被责备而不安。』

「——！？」

看著格林写到最后几个字，威尔海姆屏息。目睹令人难以置信的那段话，怒意立刻涌上心头，可是格林却摇头。

『没有人怪你，威尔海姆。我的伤，皮波特先生的死，我们都不怪你。队长应该也不认为你要为皮波特先生的死负责。』

这是事实。每次和波尔德打照面，都要听性情大变的他灌输思想。不过，他从未对自己抱怨或埋怨，也不曾追究过皮波特的死。

格林也不打算把失去声音的原因怪罪在威尔海姆身上。

当然，就算被人这样讲，自己也没理由自找罪受。没这必要才对。

『威尔海姆，你是我们卓格夫队的剑。只要你没输，我们就不算输。大家都这么相信，所以才会豁出性命。』

「——。少擅自认定。我的剑是我自己的，我不属于任何人。」

『是啊。这样就好。你那强悍激烈的生存方式只属于你自己。虽然是这样，但现在你已经不能只看自己了。』

「不知道你在讲什么。」

『你的生存方式是种理想，讲白点就是廉价肤浅。不过能这么活著的人就只有决定去实践、做出觉悟的人。我们办不到。』

格林写的字掺入感情，变得潦草：即使读得懂，但威尔海姆却不懂其中含义。

办不到，做不到。这些话是自己平常最讨厌的话。

而自己最讨厌的，就是讲出这些话的人的眼神。把放弃挂在嘴边、陈述怠惰的借口，却耍些小聪明的态度最叫人作恶。

「————」

然而，看著威尔海姆的格林，表情却跟那些人不同。

明明是用办不到、做不到当借口好放弃的家伙，可是看著自己的目光却不是死心与悔恨。

被他的目光直视，整个人就没法镇静下来。

『威尔海姆，我呢，非常憧憬你的强大。在卡斯泽尔平原遇见托尔塔的尸兵时，我深刻感受到跟你的差距，觉得你很厉害。队上的人也都是这样。远一点的人不知道，但只要靠近就知道你很厉害。』

「……不要擅自论断我。」

『对不起。可是，你也很自我。所以要论自我程度，我们是彼此彼此。我很期待。期待你能走得多远。』

——走得多远？挥舞剑、化成剑，这么一来究竟会抵达何处？

他终于知道格林眼中那叫人无法理解的感情是什么。那是期待与希望。

放弃，认同自己办不到，但对可以抵达高处的人投以欣羡。

『其实在没声音之前，我应该先跟你说的。结果现在才讲。』

「————」

『那时候多谢了。多亏了你，我现在才会在这儿。』

无声道谢的格林朝著威尔海姆一笑，然后鞠躬。

脸上浮现的表情，是只有亲密才办得到的，货真价实的笑容。

——那让威尔海姆感到十分难受。

6

「你喜欢上花了吗？」

「不，我讨厌。」

「你为什么要挥剑？」

「因为我只有这个。」

在互诉姓名和钦羡的表白后，接下来就是过著与之前无异的日子。

王国军还是一样没什么大动作。于是只能在没有编队的情况下担任王都的周边警卫，放假的时候就到广场跟特蕾希雅进行没意义的对话。

花的话题和挥剑的理由，不知何时，这些问答成了既定仪式。

威尔海姆的答案，还有特蕾希雅对此的反应，每次都没有改变。

本来是这样的——可是威尔海姆察觉，自己对这问答感到痛苦。

花的问答还没怎么样。自己对花朵的感情没有变。

但是被问到关于挥剑的事，心头就觉得紧缩。——每次都还会涌现焦躁。

在爱西亚皮波特的一呼，在治疗院格林说的话，他们投向自己的感情让胸口深处发疼。

「威尔海姆……干嘛一直盯著我看？」

「……没有，没事。」

「是吗？是说最好不要紧盯著女生的脸瞧，这样很失礼。」

「你看起来又不像被盯到不舒服。」

「咦？你、你这是什么意思……？」

「——？」

「为什么一脸不懂的样子！？刚刚的发展不应该是这样吧！」

在广场和特蕾希雅聊天的时候，发现自己就跟在练剑时一样沈著。

也注意到自己在练剑的时候，没法埋首专心。

原本只要挥剑就能满足，但现在和剑面对面时却觉得窒息。

自己简直就像——

「——总觉得，剑像在哭泣。」

「——！」

想不透，凭著习惯挥剑时，被特蕾希雅这么说。

一瞬间，感情像是沸腾了。威尔海姆转过头瞪向她。

「……怎、怎么了？」

「你！你懂我什么了！你哪懂我的剑……！」

心灵被逼至死路，威尔海姆忍不住迁怒，但马上就后悔这么说。可是话语一旦出口就覆水难收。特蕾希雅皱起眉，然后——

「威尔海姆……你说的对，我没资格论断你的剑。可是我看得出来，你现在挥剑挥得很痛苦。」

「不要讲得很懂的样子。我哪有痛苦……」

「既然那么痛苦又厌恶，不如别做了？」

「别做了……？」

从未想过的事让威尔海姆皱起脸。特蕾希雅点头道：

「对。既然厌恶，那继续也没意义。或许这样很没责任感，可是没有必要扼杀心灵勉强继续下去。还是说……」

说到这儿，特蕾希雅停顿了会，转身面向呆若木鸡的威尔海姆，歪著脑袋说：

「——你背负著必须挥剑挥到这种地步的意义？」

——不是问挥剑的理由，而是意义。

那是每次都会有的问答，只不过问题稍有更改。

挥剑的理由，是因为威尔海姆只有这个。

但是，挥剑的意义，指的是威尔海姆·托利亚斯这么做的意义。

「那种事，我不知道啦。」

「既然如此……」

「可是，我不允许自己拋下剑。」

威尔海姆说得强而有力，这次换特蕾希雅沈默了。

不允许自己拋下剑。没错，这无关威尔海姆这个人的意志，就是不允许而已。

「既然不允许……那就算会痛苦难过，你之后还是会继续挥剑啰？」

「对。——就算不知道，我还是会继续挥剑。我非得那样。」

就只有剑。除此之外，威尔海姆没有其他方法找得到答案。

威尔海姆像倚靠般紧握剑柄，对此特蕾希雅叹气。

「是吗。你有啊。——被迫活著的意义。」

「……被迫活著的意义？」

想都没想过的字眼，让威尔海姆受到冲击。

她知道皮波特和卓格夫队的牺牲，还有自己是被迫活著？

可是，她的双眼没有那种神色。清澈的蓝色双眼就只是凝视著威尔海姆。

「对。一定就是那个折磨著你，却又不让你放下剑。——我呢……」

「————」

特蕾希雅低垂眼帘，表情透著寂寞。

注意到她的表情变化，可是却没法立刻接著开口。

耳内深处，如今还持续回荡特蕾希雅的话。

「要是能找到就好了。找到你的理由。」

「……我的理由？」

根本不知道这番话是否与解决问题有关，毕竟这问题已在威尔海姆心中扎根。

你以为问题那么简单吗，少讲些无聊愚蠢的话。自己也是可以这样拒人于千里之外。

可是，威尔海姆却没这么做。

「这样啊。——既然我有的话，希望能找到呢。」

说完，他朝特蕾希雅点头。

被迫活著的意义，皮波特他们牺牲的理由，格林钦羡自己的答案——

或许，那会成为重新将威尔海姆打造为「钢铁」的契机也说不定。

「没问题。可以找到的。——假如是你的话。」

毫无根据，但特蕾希雅就是微笑著这么断言。

而威尔海姆不知为什么，也没心情去反驳。

仿佛被特蕾希雅的话所吸引，得到答案的机会降临。

对威尔海姆·托利亚斯而言，对剑鬼来说，无可避免的决战时刻。

——「亚人战争」的重头戏，露格尼卡王城血战的幕帘悄然升起。

** 六幕

1

——潜伏在王国各地的亚人族，同时掀起大规模战火。

还深受前次大败仗影响的王国军，面对亚人族风起云涌的武装暴动以及大量尸兵的进击，反应跟处置总是慢许多步。庞大的受害报告涌入，使得大本营陷入混乱、指挥系统崩溃，最后各地的防卫工作全权交由各地的负责人做判断定夺。

「这方面的事不断地零星传入，但详细状况却不明朗。要是有把我们配置到某处，至少可以减轻当地的损害吧。」

将卓格夫队聚集在值班室，全副武装的波尔德低声说。

聚集在这儿的，是取代死去队员的全新卓格夫队。已被王国军编组，只是尚未发布正式公告，不过波尔德先前就去打过招呼的人全都聚集在这里。

当然在这些人里头，少不了威尔海姆和出院的格林。

「格林！虽然没法出声，但身手可没退步吧！？这可是重头戏喔！」

「————」

在波尔德督促奋起的呼喊下，格林不发一语敲击盾牌作为响应。对他气势十足的态度满意点头，波尔德瞪向值班室外头。

「没多久，应该就会要求我们出动，前往附近的战场。本来是很想立刻冲出去，但考虑到伙伴变多，所以不能轻举妄动。」

波尔德长篇大论的期间，威尔海姆静静地提高战意。

在迫近的战斗气息中，剑鬼和内心翻滚的斗争心正面相对。届时于战场上、于割取性命的当下，就能削除在花海中产生的迷惘。

假如是在热血与性命激出火花、赌上灵魂战斗的战场上，就能毫无迷惘——

「不过，同时发动武装暴动还真是大胆的手段。应该是巴尔加·克罗姆威尔的策略吧。可是让亚人族统一步调联合进击，这招实在是很可怕。」

望向窗外等候通知的波尔德不经意地这么说。他抓抓自己的短发，厌恶地扭曲脸孔。

「不过，很遗憾，活动似乎没有波及到戒备森严的王都。虽然国内烽火连天，火舌却没能烧到重要的主堡。在最后关头掉以轻心，蛮族的智慧就是肤浅。」

虽说多少掺入了私情，但大抵来说威尔海姆也同意这意见。尽管王国各地都发生武装暴动，但就只有王都尚未传出任何受害报告。

尽管是不得已，但也住了好几年的王都市街。威尔海姆也不期望该处化为战场，那样会有很多人死伤。特蕾希雅和那片花海也不例外——

「——等等。」

太奇怪了，威尔海姆的直觉这么说。这并非基于自己担心特蕾希雅的心情。

哪里怪怪的。而不对劲藉由某个单字成形。

「……火舌？」

波尔德所说的这个单字，威尔海姆记得最近有听过。搜寻记忆、回想起符合的场景时，战栗窜上背脊。

——再过不久火舌会在国内寂起，王都也没法躲过灭亡。

说这句话的，是在王都周边进行破坏作业的一名亚人。当然，也可以视之为吹牛，但那是巴尔加·克罗姆威尔策划的阴谋。

王都里未曾发现过火苗，担任过王都警备队的威尔海姆很清楚。那群家伙放弃号召同伴，刻意将王都撇离目标。

——这不合理。王都不可能不是目标。

既然如此，这次同时发起的武装暴动，便是巴尔加·克罗姆威尔的——

「波尔德！外头的暴动是幌子！他们真正的目标是王都王城本身！」

「——什么？」

靠直觉连结到答案，威尔海姆靠近波尔德大声说。对他这番断定的发言，波尔德严肃的面容上浮现诧异神色。

心焦难耐。可是，这份确信如假包换。敌人一定会直捣我方要害。

「卡斯泽尔，爱西亚！想想让王国受到重创的战役！每一场都是设下显而易见的诱饵等王国上钩，这就是巴尔加·克罗姆威尔的策略！」

「……所以你的意思是，这次的暴动是声东击西，其实目标是主堡？」

「没错！你懂吧，波尔德！只要王都派兵去镇压暴动，亚人族再动用最大战力进攻兵力变单薄的王城，王国就会被攻陷！」

视事件和情况而定，这时的判断很可能左右亲龙王国露格尼卡的未来。

没有确切的证据。但是，威尔海姆相信自己的直觉。在战场上要是不相信直觉，就不能解释自己为何能活到今天。

「嗯……」

波尔德双手环抱进入思考模式，威尔海姆只能咬牙。

过去也曾这样。卡斯泽尔平原之役打到一半，小队长烦恼怎么应付第一次遇到的魔法阵的时候，威尔海姆建议为求生存只能前进，可是这意见却被驳回，结果整个小队只剩下威尔海姆和格林，其余全数阵亡。

这次根本就是那次的翻版。

假使波尔德驳回意见，那就算只有自己——

「————」

心浮气躁的时候，有人从后方拍了威尔海姆的肩膀一下。回过头，是格林。他朝威尔海姆点头，朝波尔德举手。

注意到他的举动，波尔德看著威尔海姆和格林，接著深深点头，嘴角露出久违的狰狞笑容。

「——有意思。让我们卓格夫队闷闷不乐地守在王都，对大本营来说反而是绝佳妙招呀。这可真是痛快！」

「哦！哦哦哦——！！」

发出吼叫声，波尔德用斧枪柄尾重击地板。值班室响起巨大的金属声，听到的卓格夫队队员一起大叫。

在一瞬间就点燃全员的战意。室内的空气为之震动，吞没威尔海姆。接著波尔德扛起战斧，朝著被气势拋下的威尔海姆露齿一笑。

「怎么啦，冲锋队长！这种表情跟你不搭喔。」

「——你相信我没来由的话？」

「最后做判断的是我。我没打算让人说三道四。而且啊，我的直觉也认同你的直觉。就当是给皮波特他们的饯别礼，粉碎亚人的计谋吧！」

被波尔德的拳头推了一把，幸好有格林撑住往后退的威尔海姆。不能说话的盾兵苦笑。知道他在问「怎么样？」的威尔海姆甩开他的手。

「好，出发！我们卓格夫队是王国之剑！所以有义务对企图谋反的蛮族们执行正义！有人有异议吗！有人否定吗！」

「没有！没有！并没有！」

队员们朝著高举战斧鼓舞战意的波尔德咆哮。然后，心情愉悦听著他们大声回复的波尔德转头面向威尔海姆。

「威尔海姆！剑鬼威尔海姆·托利亚斯！敌人的目标是——！」

「——！那还用说。敌人的目标是王城，露格尼卡王城！！」

被质问的威尔海姆放声回答，于是战斧举向远处的王城。

接著波尔德深吸一口气，用被称做「猛犬」的音量吠叫。

「敌人接近露格尼卡王城！走吧，出发，卓格夫队——！！」

2

面对以迅猛之势冲向王城的卓格夫队，负责王城警备的卫兵们都做好了赴死的觉悟。他们的神色看起来让人错以为是整群战鬼，卫兵们是真的以为要被攻陷了。

「站好，怎么回事！你们这样还能称做是保卫国家中枢的卫兵吗！」

一名正骑士怒骂个个发抖的卫兵。眼神凶狠的正骑士俯视冲向正门的卓格夫队，然后厌烦地咋舌。

「带头的不是那只愚昧野狗吗……！给我站住，波尔德·卓格夫！」

「那是莱夫·跋利耶尔殿下！？」

听到制止声而抬头的波尔德，看到站在卫兵中央的男人后瞪大眼珠。站在那儿的就是在爱西亚湿地地带战线遇到的正骑士莱夫·跋利耶尔。

凝视停下脚步的卓格夫队，莱夫挡在波尔德面前。

「战争时期搞什么鬼，波尔德！在王国有难期间你还带头作乱，就算被视作反叛份子也怨不得人！」

「在下为队上全都长得很可怕一事致歉。但是，我们并非来王城游乐。现下是分秒必争，事关王国存亡！」

「事关王国存亡……？」

两人在正门前互瞪。波尔德的豪气宣言，听得莱夫眉头深锁。而从战鬼团体走出来，与波尔德并肩而立的是威尔海姆。

看到剑气勃发的他，莱夫瞠目结舌，心情变得很差。

「又是你，剑鬼。」

「要怎么称呼是你的自由，但现在没时间一问一答了。敌人是冲著王城来的。」

「——意味著，暴动是调虎离山之计吗。但是你有铁证吗？」

他是个优秀人才。仅听了威尔海姆的简短断言，莱夫就立刻看穿亚人族的真正用意。可是，面对他要求证据的问题只能摇头以对。

「只是靠直觉啊。凭这理由就想冲进王城里，我佩服你们。——请速速离去，卓格夫队。王城的警备现在是我的职务。」

「巴尔加，利布雷，史芬克丝……全部一起上你挡得住吗？好大的自信。」

「……算上爱西亚那次，这是第二次了。不准顶撞上司！」

威尔海姆挑衅，莱夫咂嘴并朝他挥以铁拳。但是，威尔海姆只是头一偏就闪过在爱西亚湿地地带吃下的那一击。

「谁准你避开的……！」

「那时候你是指挥官，可今天不一样。既然没有被揍的理由，也就用不著被你挡在这儿。要挡路我就强行通过。」

剑锷与剑鞘撞击出声，中了剑气的周遭卫兵全都开始发抖。莱夫也是，头一次露出气势被盖过的表情。双方互相瞪视，气氛一触即发——就在这个当口。

「——好——哟，就由地位更高的我来下命令吧。卓格夫队正式加入王城警备的行列。」

拉长尾音的女子声音从王城发出。所有人看向城堡，便见两道人影走过来——著军服的女人罗兹瓦尔以及随侍在侧的卡萝。

「罗兹瓦尔·J·梅札斯……哼！」

「值此内战担任对魔特别顾问的我，和担任闲差的正门警备负责人……谁的命令比较优先，就用你最喜欢的阶级和地位来比较看看——吧？」

看到莱夫愤恨咬牙，罗兹瓦尔只是轻轻耸了耸肩。不过，她的话就跟蛇一样毫不留情，莱夫只能气愤地闭上嘴巴。

「什——么，又不是要你拋弃所有。今天有幸在场，说不定是挽回你的名誉的机会喔。凡事都要考虑。」

用称不上安慰的话斥退莱夫后，罗兹瓦尔看著威尔海姆。接著抚摸长至肩头的头发，嫣然微笑。

「你果然来～了。在卡斯泽尔选中你们……不对，选中你是正确的。」

「还是一样讲些让人摸不著头绪的话。不说这了，我们可以进去了吗？」

「讲些贴心话献个殷勤又不——会怎样。——当然，进来吧。」

本来就没打算多话，所以就跟平常一样冷漠响应。接著威尔海姆转头看向波尔德，被称做「猛犬」的他用力点头。

「好——！卓格夫队接下来就进王城！城内各处和主要场所全都由我们固守！分成十个班！班别就按照讲好的去分！」

以斧枪柄尾敲击地面，波尔德下达指示。卓格夫队立刻分成十个班，各班按照分配前往城内守备处。

「莱夫殿下就待在这里。城内由我们卓格夫队巡逻。务必别让亚人穿过正门。」

「——哼！那么理所当然的事用不著你提醒。连一只虫子我都不会放它过去。快点走开，一群野狗！」

斜瞄嘴硬的莱夫，威尔海姆一行人也冲进城内。而紧跟在后的罗兹瓦尔兴致盎然地闭上一只眼睛。

「都分班了，你还是单独行动——吗？」

「有管家公格林在。——虽然很烦。」

瞥了一眼后方，不出声的格林正被并肩走在一起的卡萝关心中。就算只有一方能说话，还是可以进行对话。对此威尔海姆轻声喷气。

「军队全都出去了啊。」

各班各自到城内就定位时，目睹冷清不已的通道和设施，威尔海姆低喃。

第一次进入露格尼卡王城内，是在被传唤至大本营会议的时候。可是那时候城堡里头人多到很夸张，现在却几乎感受不到人烟。

「因为在爱西亚损耗严重，使得上级士官全都被派遣至各地战线。而且这次的大规模暴动，陛下也亲自下令派兵前往受害情况大的区域。」

「那家伙……」

「不能轻视——国王的命令喔。——就算这点早被敌人料——中了也是。」

露格尼卡王室全都是老好人，个个都是不适合国政的装饰品。

虽是广为人知的传言，但似乎不是无中生有的胡说八道。

「那么，王城警备是空荡荡的啰？」

「就只留下了最低限度的近卫骑士，还有像莱夫殿下那种警备队吧？不打算明哲保身的陛下心胸十分——宽大，但身为国家主干，这样可能会——有点问题。现在为了王国安宁，陛下或许正在向龙祈祷吧？」

「最后还不是靠别人，就只有爱国情操能看——不对。」

讲到这里，威尔海姆的直觉又有反应。

既然亚人族是瞄准王城，那最终目标就是王国心脏，也就是国王本人。

而让亚人在王国全境暴动后，就能确实掌握留在城堡内的国王的所在位置——「亲龙王国」露格尼卡的国王在国家大难当头时一定会去的地方。

假如连这点都在巴尔加·克罗姆威尔的算计中的话——

「威尔海姆！我接下来去确保陛下的安危！往楼上……」

「波尔德！我去礼拜堂！有意见吗！？」

打断想往楼上跑的波尔德，威尔海姆丢出自己的意见。这种顺从己身直觉的态度和话语，让波尔德瞪大双眼，随后笑了起来。

「——不，没事！万一有什么事，也别忘了卓格夫队的气魄！」

「谁知道那种东西啦。」

「那就问格林。格林！不要放掉威尔海姆的缰绳喔！」

格林用力敲响盾牌回应，威尔海姆皱眉。波尔德扛起斧枪，祝彼此好运后就各自跑开了。

「你是干嘛？为什么一直跟著我们？」

跟波尔德分开，前往王城地底的礼拜堂的时候，威尔海姆这么问跟了过来还充满干劲的罗兹瓦尔。对此她闭上一只眼睛。

「我也有我的目的。我的目标会出现在哪边，碰运气——的成分很——大……而这时候，我决定相信让我一见钟情的男人的判断。」

罗兹瓦尔的戏言，听得格林和卡萝楞住了。不过当事人威尔海姆却一脸厌烦地咂嘴，像是要逃离她的视线般往前冲。

「死了我可不管。我可没温柔到战斗期间会考虑到后方。」

「……你会开口提醒，让我觉得你变～了呢。」

「谁变了。就算要变——」

也只是威尔海姆这个人逐渐精炼为不通人情的剑而已。

果然这才是自己从剑里找到的答案。

——脑里掠过特蕾希雅，不过威尔海姆咬牙挥别她的脸。

要是不这么告诉自己，就连自己都没法再继续相信下去。

简直就像为了背过眼不去看事实似的，威尔海姆笔直地往前跑。

3

——踏进谒见大厅时，波尔德的皮肤感受到空气变得浓密。

这种斗气刺人的感觉，绝对是与强者交锋时才会有的感受。没带部下，把他们派至其他地方是正确的。这个敌手恐怕只有自己承受得住。

「……威尔海姆那家伙，不管感谢他几次都不够呢。」

压倒性的斗气压力——最近频率锐减，但在练兵场与威尔海姆对峙时经常能品味到。对波尔德来说，是已经习惯的恐惧感。

让波尔德老实认同自己实力不如人的对手很少。并非他好强不服输。事实上，他的实力是高得罕见。

自幼就习武，活用优异的体格和才能走在骑士之路上。

在家世与才能的支持下，波尔德的人生可说是一帆风顺。和一个嘴巴啰唆、给人感觉像哥哥的随从一块儿走来，波尔德的步伐经常是顺风且迎向阳光。

而在波尔德这样的人生里添加新的色彩和掀起变化之风的人就是威尔海姆。自大又爱反抗的少年，让波尔德感到棘手的印象多到数不清。不过也因为承担了这样的辛劳，波尔德才拯救了威尔海姆。

从少年锐变为青年，他的剑芒之锋利，变成了对王国而言不可或缺之物。

皮波特也是因为明白这点，才会为了他献出生命。因为他看出威尔海姆的存在重要到左右王国和波尔德的未来。

而事实上，威尔海姆如今就决定了波尔德的生死。

「————」

边用深红血液为谒见大厅地板上的鲜红地毯染色，边挥舞双头剑的高个子转身面向波尔德。毫无生气的双眼，和腥臭又刺耳的呼吸声，完全没有一丝生者该有的存在感的蛇人利布雷·菲尔密。

可是，即便成为尸兵，依旧是亚人族最强战士，其斗气仍旧健在。

「史芬克丝不在吗。……但是，我要跟你算皮波特的仇。你这骯脏蛮族。」

故意口出秽言辱骂敌人，藉此鼓舞自己的战意。

不这样的话就会被扎人的斗气波浪给吞噬，让出先发制人的宝贵机会。这股阴森之气，这般差距，鲜明划分出身为战士的密度之差。

波尔德能够不屈服，是因为他已经品尝过几十遍这份败北感。

与威尔海姆·托利亚斯对峙，波尔德经常都是吃败仗的人。

「事到如今，早就不怕挑战必败之战了。——我上啰，利布雷·菲尔密！」

在头上旋转战斧，如野兽咆哮后波尔德用力踩踏地毯。巨大身躯宛如炮弹飞向前，抡著双头剑的蛇人立刻迎击。

激烈火花与钢铁互相摩擦，「猛犬」与「毒蛇」开始激战。

4

礼拜堂的大门前，倒著好几名失去首级的近卫兵尸体。

是人数少，但负责担任王城警备的近卫骑士。他们曾经奋战却落败了，地上的骑士剑和搏斗痕迹证明了这点。输家，亦即弱者，不配同情。这是威尔海姆的论调，但此时不知为何却有莫名感慨在心头萌芽。

或许是因为知道了这些亡骸是为了什么而战的缘故。

「————」

挥别感伤，威尔海姆手持爱剑敞开大门。门发出声响缓慢开启，清凉的风从礼拜堂吹进走廊。

建于王城地底的礼拜堂，是被皎洁的魔法灯照耀的庄严空间。左右两边并排著长椅，正面墙壁上雕刻著国徽神龙纹章。然后，在供人面朝雕刻祷告的祭坛上，站著两道人影。

「——在礼拜堂，王国的人会向龙祈祷。在帝国的话则向力量；在圣王国的话则向精灵，西方的都市国家就不知道了，但总是有让人祷告的对象吧。」

「那么，你们是来向谁祷告的？——亚人在礼拜堂，要向谁祷告，又祷告什么？」

「这个嘛，老朽的话，会是向同胞和祖先的灵魂祷告。至少老朽没有理由向其他事物祷告。」

沙哑的声音这么响应，两道人影——巨汉和娇小女童转身。

女童的身份已不用多说，早就知道的「魔女」史芬克丝。还有站在旁边的巨汉，他正是「亚人战争」的最大敌人，巨人族大参谋——

「巴尔加·克罗姆威尔。」

威尔海姆说，巨汉点头，可是却没法窥见他的脸。因为巨汉从头到脚裹著白布，都到这地步了却还隐瞒外表。

「正是。而你就是『剑鬼』啰。原来如此，无所畏惧的神情和异于常人的杀气……就算是对战斗一窍不通的老朽都知道。不愧是干掉利布雷的剑士。」

「干掉利布雷？」

想到爱西亚的决斗，只能用屈辱来形容。

扭曲事实的魔女丝毫不介意剑鬼的视线，而是凝视罗兹瓦尔。

「你会来这里，就代表……国王没有来这啰。」

「我个人没理由那么执著。不——过，如你所料令我非常不爽。我要否定你的一切，最后践踏你的性命。」

史芬克丝毫无感情地说，伸出双手装备拳套的罗兹瓦尔回答。罗兹瓦尔轻轻旋转手腕，用格外有模有样的动作摆出准备格斗的架势。

她身后的卡萝手持长剑，格林架盾，同样做好战斗准备。

「很有勇气。区区四人就打算当我们的对手。」

「你们才是，以这么少的人数杀进主堡。很遗憾，你的同伴嘴巴不牢靠，所以这个计谋已经泡汤了。——就在这结束吧。」

「……知道作战的应该是被严选过的人，却还是有快死的人脱口而出吗。不，我不恨同胞。能够潜入到这里，就流程来说已是完美。」

「能够溜进城内真的很厉害。卫兵们在搞什么。」

「从地下水脉走秘密通道……现在已经没人找得到了。虽然寿命短暂，但就是为此而生的洞窟。」

巴尔加用脚跟敲地板，正大光明坦承入侵路线。可能因为计谋被敌方看穿，所以对方的应对很得体。威尔海姆忍不住咂嘴。

「过去，在人类与龙缔结盟约之前……这块地在盖城堡的时候，亚人族也有帮忙建设。当时，谁也没想到人类与亚人的关系会变成这样吧，真是讽刺。正因为有那时，才能成就今天的报应。」

「很宝贵的意见。只不过，人选很糟。听说除了头脑战以外你根本派不上用场。所以实质的战斗力就只有旁边的魔女啰。」

「……确实，假若是原本的我，是那样没错。」

巴尔加压低音量，威尔海姆皱眉。这话启人疑窦。而看到他的反应，巴尔加从喉咙深处发出低沈笑声。

「要是达成目标，国王应该会在这儿。想要加害国王，除了打倒近卫兵以外别无他法。你认为老朽会没准备任何手段就前来挑战吗？」

「少绕圈子。」

「真无趣的人。……史芬克丝，启动术式。」

威尔海姆直截了当地说，巴尔加便命令身旁的史芬克丝。闻言，她仰望巨大身躯，微微歪头问：

「这样好吗？一旦开始就很难停止……不，是不可能停止。」

「没关系。原本为了报答同胞，老朽就没打算活著回去！」

巴尔加厉声说完，脱去披著的白衣。底下隐藏的是外貌凶猛的秃头老人。不过，巨人族特有的肌肉身材都还在，值得一提的是他的肉体仿佛像岩石，以及肌肤上的紫色纹路——发光的魔法阵。

「——在身上画魔法阵！？那什么术式！？」

「我应该说过。你们人类会向龙祈祷。既然如此，老身就是向同胞和祖灵祈祷！」

卡萝尖叫，巴尔加严肃回答。以老人的肉体为根基的术式启动，身上的纹路光芒增强，巴尔加从怀中掏出一个东西——小箱子。

「过去，巨人族曾为人所畏惧的证明！巨人始祖之骨啊！」

「只凭一片骨头，就算用上『不死王的圣礼』也无法重现尸兵。但是，假如是要供给血脉相传的子孙莫大玛那量的话，就另当别论了。」

「想用巴尔加·克罗姆威尔的肉体重现巨人始祖吗！」

「把亚人族的骄傲和坚持深深刻划在你们眼底，用你们的身体和灵魂去感受吧，臭人类——！！」

巴尔加吶喊，并将白色骨片朝自己的胸膛正中央戳进去。

接著，史芬克丝使用的「不死王的圣礼」效能，因巴尔加·克罗姆威尔肉体上的魔法阵而增幅，完成了可怕的计划——

「哦！哦哦！哦哦哦哦哦——！！」

如野兽吼叫的声音越来越大，发声源也逐渐变高。原因在于出声的巴尔加肺部变大，巨大的身躯倍增后又再倍增，整个人变成名符其实的巨人。

几秒后，术式发动的光芒收敛时，塞满礼拜堂里头的人是——

「这就是巨人族的始祖……？不就只是怪物吗……！」

仰望庞大身躯的卡萝说话时声音在颤抖，因为里头含著恐惧。但是，没有人因为这样责备她。

巴尔加的躯体直达礼拜堂天花板，身高至少超过十公尺。地底空间容纳不下他的身体，因此他是呈现弯腰半蹲的姿势。突然，巨人往前伸手。

看起来慢得恐怖的动作——但速度足够称之为暴力。

「——闪开！！」

威尔海姆立刻大喊，朝旁边一跳，躲过从正前方逼近的凶恶掌击。罗兹瓦尔也一样跳向旁边躲开，格林则是为了保护卡萝而冲到手掌前。

来不及做好准备的他，用盾牌承受足以匹敌巨兽冲刺的威力。不到一秒抗衡就被瓦解，整个人连同卡萝都飞到门后的走廊去。

「你们——」

「那个笨蛋用往后退抵销冲击了！没空理他们，过来啰！」

朝著关心他们的罗兹瓦尔叫喊，提醒她注意后，威尔海姆重新握好爱剑。剑鬼瞪著巨大化的巴尔加和飘在半空中的史芬克丝。

「魔女」丝毫不睬他的视线，「巨人」仰视开始崩塌的天花板。

「巴尔加，这边可以交给你吧？我·打·算·执·行下一个阶段。」

「随你高兴。——老朽，要为利布雷报仇。」

「那就这样。巴尔加，要·好·好·加·油。」

「……承蒙你照顾了。虽然你也许不懂这样的人情世故吧。」

自由的史芬克丝离去之际对巴尔加的话感到疑惑，不过还是什么也没说，就穿过天花板的洞穴，一下便消失不见了。

「史芬克丝……！」

「去追魔女。带上在走廊睡觉的那两人。」

魔女离开让罗兹瓦尔气愤不已，威尔海姆则是用剑指向走廊对她这么说。这话让她瞠目结舌，瞥视巴尔加的庞大身躯。

「你要一个人当巴尔加的对手？那——样不会太有勇无谋吗？」

「不能放著魔女不管。而且那家伙不擅长应付拳头和盾牌。以见招拆招为长的卡萝也一样，靠近她就砍。——这家伙是我的猎物。」

剑尖重新朝向巴尔加，威尔海姆释放出凶恶杀气。

「真帅气。骨头差点要酥了。要是能平安重逢的话我想给你个热吻。」

「不要说恶心巴拉的话，快走。」

「真的是很冷～淡耶。还是说，有心上人了？」

罗兹瓦尔不看状况，口气依旧轻佻。威尔海姆不屑地哼了一声。

一瞬间，脑内闪过红发少女，但他没说出口。

「祝你好运。」

「你也是，可别放过她啊。」

彼此杀气腾腾地要对方保重后，罗兹瓦尔就快速离开礼拜堂。在走廊跟那两人会合后，应该就会跑到楼上和史芬克丝交战。他们能否战胜魔女，就看他们的造化了。

那是某种信赖，只是威尔海姆没有自觉。

「我这可没心思去顾虑他人啊。」

「少骄傲，小子。像你这种家伙，哪能阻止老朽的悲愿——！」

巴尔加朝著压低身子持剑应对的威尔海姆怒吼，挥下巨腕。冲向威力超乎常轨的大手，剑鬼翘起嘴角。

强的话就办得到，弱的话就夭折。仅此而已。——跟意志的强弱哪有关系。」

5

踩地，使力抡起战斧从正上方敲下去。双头剑的一端承受敲击，发出摩擦声卸掉威力，但波尔德用超越极限的腕力强行突破。

斧击敲中蛇人的身体，鳞片和鲜血四散，利布雷整个人往后仰。

「喝——呀——！！」

波尔德咆哮，追击受伤却不吭声的敌人。沈重的斧头宛若伸长的手腕般挥动，以柄尾和斧刃使出连击。

面对这攻势，尸兵利布雷只用还存留于尸体内的战斗技术来防御。被他的闪躲和双头剑防御术给玩弄，最后失去平衡被斩击击飞。肩头和下腹都被挖出伤口喷血，但波尔德用力踏稳脚步。

强敌，毫无疑问是人生中遭遇的少数强敌。很难相信对方因变成尸兵，实力有所削弱。一想到敌人生前的实力之高就浑身颤抖，不知是因为恐惧还是战意高昂。

「喝啊——！热血沸腾！我热血沸腾啦，利布雷·菲尔密！」

其实，不管是何者，这个当下，战意就是真实。波尔德朝自己狂啸。

利布雷不具光彩的双眼看著即使染血还是奋起大喊的波尔德。蛇人对战士的吶喊毫无反应，只是用手掌旋转双头剑继续战斗。

利布雷·菲尔密的双头剑交织出必杀一击的杀戮舞蹈——

「唔哦哦哦哦哦——！！」

内心因斩击风暴而胆怯，但是后退的鞋底感受到楼下传来的震动。激战的余波都传到这里来了，战友的奋斗点燃了波尔德的斗志。

——自己老是疏忽脚边，皮波特死前不是这么说吗。

而现在脚下传来战友的奋斗，自己因此获得力量的现在，他会怎么说呢？

那还用说。

「你一定是笑著说：『我不是那个意思』吧，皮波特——！！」

杀戮舞蹈咆哮且逼近而来。波尔德振奋精神，扛起斧枪吶喊。

自己没有威尔海姆那样的技巧，没法像格林那样格挡，无法像卡萝那样灵巧，也没有罗兹瓦尔的见识。

因此，波尔德·卓格夫将一切赌在上天恩赐的肉体与才能上。

「——哦哦哦哦哦！」

010

宛如暴风的斩击切割身体，波尔德品尝到烧灼的痛楚与流血的滋味，于此同时高举的战斧伴随破坏性的威力，朝蛇人的正中央挥下。

冲击炸裂地面。然后，决斗分出胜负——

6

灼热的白光瞬间蒸发接触之物。释放死亡热线，在地板和墙壁留下锐利伤痕，自在散播死亡的人，是有女童外貌的稀世魔人。

史芬克丝穿过礼拜堂的天花板，逃到王城一楼的走廊。而脱离地底战斗，阻止她做出更邪恶之事的人，是穷追不舍的军服女子。

「你也真的很缠人。要·排·除。」

「是——吗？你快点倒下的话，我就能变回淑女啰。」

脚蹬石壁，以三角跳跃朝飘在走廊空中的史芬克丝挥拳。史芬克丝左闪右躲避开拳头，但罗兹瓦尔再次踢墙，长腿在空中画出美丽的弧形。——踢击直接命中魔女，一口气扯低她的所在高度。

「格林，配合我！」「——！」

而从走廊前后夹击的卡萝和格林朝魔女进攻。面对同时攻击，史芬克丝旋转身子，形成魔力盾来防御致命剑击。

「呜——！？」

想当然耳，这使她毫无防备吃下格林的盾击。来自身后的撞击让少女身体大幅后仰，飞向走廊尽头——大会厅。

「干得好！」

「——不，麻烦了。本来想在窄廊上把那家伙收拾掉的。」

卡萝对这结果大呼快哉，但感到失策的罗兹瓦尔却一脸不快。加上格林，三人追著飞出去的史芬克丝冲向大会厅。

——接著，朝三人倾注的热线将走廊出口烧成死白。

「要·注·意。不管是怎样的猎物，被逼到绝境也是有可能张牙舞爪的。」

大会厅有天花板挑高的设计，史芬克丝就待在那儿，以死亡热线欢迎他们。朝著无处可躲的地方，在绝佳时间点攻击。

魔女深信那是避无可避的必杀一击。但是——

「——？你到底用了什么机关？」

「没——呀，没什么——大不了的啦。」

从被热线烧灼而冒著白烟的走廊走出来的罗兹瓦尔一行人，个个毫发无伤。而史芬克丝的疑问，罗兹瓦尔用扔出原本披著的袍子来回答她。

「我的长袍是用能防御任何魔法一次的术式织成——的。」

「原来如此。用那个连同伴都一块保护了。准备得真周到，令我佩服。你真的很想杀我呢。」

「那是当然……不——过，这样的认知还太天真～了。」

一方在空中，一方在地面。虽然制空权被敌人掌握，却不减罗兹瓦尔的斗志。身旁被保护的卡萝，手持长剑摆出下段架势，同时往前进。

「劳烦您了，梅札斯大人。——可以稍微离开您的身旁一下吗？」

「嗯，自由发挥吧。差不多也该让她吓破胆了。」

虽是暂时的主从关系，但时间却长达三年。两人的互动令史芬克丝歪头不解。

「她跟你比起来能力不足……只是送死而已哟？」

「不准侮辱侍奉『剑圣』家族的当家雷玫迪斯的剑技，下流之辈。」

魔女的视线惹来痛骂。卡萝举起长剑，接著轻轻一跃腾空，直直砍向魔女。

面对这种不耍小把戏的勇往直前，魔女以发光的手指回敬。

「果然是送死……要·动·脑·袋。」

释放热线。人在空中又没翅膀的卡萝根本无法闪避。她立刻被热线贯穿，直接蒸发送命——但这一切都没发生。

「什么？」

「我应该说过。——不要小看雷玫迪斯！」

史芬克丝目瞪口呆，因为眼前的卡萝跳向旁边躲过了死亡热线。明明身在空中，却蹬著什么都没有的空间，而且还加速往上升。

然后划出半月形的斩击砍向毫无防备的魔女，左手的一半就这样被砍断。

「呜呃——！」

被切断的手飞出去，喷血的魔女身体往下坠。卡萝意图追击，但魔女用剩下的右手从旁发射热线。卡萝脚踢空中，勉强闪过热线。但是，魔女受的苦难还没结束。

「接招吧。——为了这一天，我这二十年来的努力！！」

等在坠下的史芬克丝正下方，罗兹瓦尔的拳头卷风上挥。

陷进年幼女童身体的拳击，透过拳套传达强烈的威力，骨头碎裂、内脏破裂的声响在大会厅里响起。

「——呃！！」

就算是史芬克丝，在这威力之前也无法若无其事。

在致命威力下吐出血块，可爱的容颜痛苦扭曲。不成声的声音被血和呕吐隐藏，飞出去的身体猛烈滚转到大会厅正中央。

少了左手而大量失血，又受到破坏性冲击而内脏全毁——一般人的话早在失血和剧痛下当场死亡，但对手是魔女的话就不能轻忽大意。

「在砸破脑袋，让心脏停止跳动前都绝不能松懈……哪。」

卡萝著地后紧盯著史芬克丝。罗兹瓦尔斥退她。但与其说是因为担心她危险，倒是因为个人理由优先的关系。史芬克丝的呼吸要由自己来中止。

罗兹瓦尔直接走向史芬克丝，准备给予致命一击——

「……吓到、我了。被破坏到这种地步……咳咳！超乎、我的预料。」

吐血撑起身体的史芬克丝这么说。咳血的魔女脸上血气尽失，已经是无法行动的状态，可却还是激起难以言喻的恐怖。

「幸好、被切断的是左手……」

要在她做什么之前接近她，砸烂她的头颅——但是，跟罗兹瓦尔的拳头相比，史芬克丝以右手扯掉身上袍子的速度比较快。布被撕破，裸露出的少女白皙肌肤画著紫色纹路，跟巴尔加身上的图案一样。

「——亚尔·吉瓦尔德！」

死亡热线——吉瓦尔德的最强魔法自她口中咏唱而成。

原本只从指尖发射的热线，现在从她的整片小手掌发出。从五根手指和手掌发出的热线，成了只要碰到就蒸发一切的死亡爪击。

「————」

整个大会厅斜向消失，死亡热线从正面逼近。即使是罗兹瓦尔也很难避开。她喉咙因吃了一惊而堵塞。

并非已有死亡的觉悟。在白色热波碰到之前，有道影子挡到面前。

「——！」

是无声无语的青年架著盾牌，从正前方承受住了热线。

011

7

在仿佛墙壁逼近的压迫感下，巴掌接二连三拍击礼拜堂地板，天花板因此震动崩落。

「巨人」的巴掌只是掠过，威力就大到身体整个要被风压带著走。不过，即使头发被暴风刮乱，威尔海姆还是挤到巨手旁用力砍下去。

「没用的，小子！那种不痛不痒的攻击，哪砍得动真正的巨人！！」

可是巨人的手硬度超越岩石和钢铁，轻松弹开剑鬼的一击。

在反作用力下无法保持姿势，这时另一只巨手从旁边挥过来。尝试利用那只手当立足点跳跃来闪避，但立足点的速度太快，导致身体整个失去平衡，产生致命空隙。

「牛皮吹很凶——用这招了结你！」

「呃啊——！？」

巴尔加像拍虫子一样，朝置身在空中的威尔海姆拍了下去。即使立刻防御，但在压倒性的打击力道前根本毫无意义。全身上下都受到撞击，威尔海姆撞向礼拜堂的地板，然后弹起来撞进长椅之中，被埋在坏掉的椅子碎屑里，就没再发出声响了。

「这么简单。接下来，就毁掉整座城堡……」

「少得意忘形。」

「姆～？」

威尔海姆飞出木片堆，朝著连疑惑声都变大的巨人冲过去。即使出血量惊人，剑鬼的双眼却在战意下灿烂生辉。

弯曲身子避开急匆匆挥过来的右手，再一跃躲过接下来的左手，然后顺著手冲到臂膀上，朝睁大的巨大眼球刺下去。

就算皮肤硬度胜过钢铁，人体要害的脆弱度也不会改变。眼球被轻易刺穿，玻璃体喷得威尔海姆满身，巴尔加惨叫。

「呜喔喔喔喔喔——！！」

手感叫人心满意足。站在肩膀上的剑鬼拔剑，耻笑痛到乱动的巴尔加。

被击中的身体全身发痛，一瞬间的轻忽大意就让肋骨和一部份内脏被破坏。要是松懈的话会被涌出的血块堵住喉咙，仿佛烧灼的痛楚让呼吸都变得没把握。

可是，这才对。这就是战场。

「哦哦哦哦啊啊啊啊！」

威尔海姆吶喊，瞄准巴尔加按著伤口的手指。剑劈进关节，但还是太硬。斩击不奏效，不过不构成败因和绝望。

收回被弹开的手，这次把剑戳进惨叫的嘴唇。割破肌肤、穿透进肉里，还有挖掘到牙齿的触感。口内被蹂躏使得巴尔加再度哀嚎，用力朝嘴前挥舞的手偶然直击威尔海姆，旋转的身体剧烈撞向地板再弹飞。

用拳头敲向地面，硬是止住旋转的势头。双腿发抖使力站起来，但起身的剑鬼对自己的惨状仅是咂嘴，然后瞪向巨人。

刺在嘴唇上的剑，距离掉落地面的威尔海姆太遥远。

「这就是战斗的痛……！老朽在耍小聪明的期间，让同胞们品尝到的就是这种痛吗！老朽是何等自以为是啊……！」

在咬牙的威尔海姆面前呻吟的巴尔加，手离开了伤口。接著，左眼的伤喷出红色蒸气，转眼间伤口就愈合。这段期间，巴尔加身体的纹路散发更强的光芒，「不死王的圣礼」发挥了可怕的效果。

「但是，在洗刷同胞的愤怒与屈辱之前，老朽绝不会输！不管你有多强，老朽都会让你知道你战胜不了亚人的骄傲——！！」

「有够啰唆……我说过了——意志的强弱跟胜败无关！」

威尔海姆语音方歇，咆哮的巴尔加以双手猛力打过来。

掀起强风的致命破坏力疯狂肆虐，为了夺回剑的威尔海姆果敢前进。对方是耐久力和再生力惊人的怪物，空手根本不可能跟他较劲。

巴尔加是战斗门外汉，不过就是凭蛮力攻过来而已。

没错，战斗无关意志。巴尔加把威尔海姆追到绝境，跟亚人族的志气与骄傲无关，单纯是因为「巨人」很强罢了。

「麻烦死了，你们每个都是！不要把多余的东西强加在我身上！」

只想成为一柄剑——这样的想法，却有多余的东西接二连三跑进来。

你的、他的，理由、意义、信念、骄傲、自豪。

战斗的理由有那么伟大吗？——挥剑的意义，是必要的吗？

『你喜欢上花了吗？』

不，我讨厌。非常讨厌。那对自己来说是多余的感情。

『你为什么要挥剑？』

我只有这个，因为我只需要这个，这理由就够充分了。

被钢铁之美吸引，憧憬钢铁的高洁，渴望成为剑本身。

「去死吧，人类！在王国灭亡的消息里再添一笔剑鬼的死亡吧！！」

「我的！一切！全都只属于自己！」

「你以外的人可不这么想！！你也跟老朽一样……！」

巨手和手指翻弄想靠近的威尔海姆。

陆续使出的威力敲碎地板，交错的语言射向剑鬼和巨人。

意气与意气、骄傲与骄傲的剧烈冲突。——并不是那样的冲突。走向战斗的面对面的双方，还有彼此的表达相去甚远。双方的目标也完全不同。

即便如此，只要有相争的两人，战斗就成立。

因此，能分出胜负的并不是看赌上什么，而是看力量强弱。

那是威尔海姆的理论，剑鬼深信自身强大的来源——正因如此，这场胜负已经底定。

因为相信自身和钢铁强大的剑鬼，这段期间凈是吸收杂质。

「咳、噗……！」

「——这次真的要结束了。」

没法全部躲开，正面受到拳击的威尔海姆跪坐在墙边。左臂被压烂，破皮的额头流出大量鲜血堵住视线。

而巨人朝著无法动弹的剑鬼，缓缓举起握紧的拳头。

威尔海姆默默地凝视上方的拳头。只要那个挥下来，自己的肉体就会被毫不留情地砸烂，转化为喷血肉块吧。

「死亡」就在眼前。至今给予众多人死亡的自己，终于也要死了。

剑也不在手边，找不到握著它继续挥舞的理由，就这样于此——

「结束了，剑鬼。不久你就能在地狱看到我和利布雷了——！！」

拳头落下。就这样，威尔海姆的命运被冲击给压个稀巴烂——

「——格林！！配合我！！」「——！！」

在即将完结的瞬间，听到女子声和男子的沙哑声，接著冲击波撼动礼拜堂。

8

——就在罗兹瓦尔要被热线消灭之前，格林冲到她前面。

「————」

根本不知道有没有胜算，也没自信可以幸存。胜算和自信都跟格林无缘，之前的人生不过都是厄运肆虐的结果。

因此在这瞬间，格林朝白光举盾的结果，也是他的「厄运」的赏赐。

「区区盾牌……」

热线是防御不了的攻击。切割王城大会厅，将波及到的近卫骑士尸体给蒸发。既然有贯穿铠甲的威力，那盾牌也会迎向同样的末路。

「格林——！」

承受白光的剎那，卡萝惨叫。平常严肃的她其实骨子里很温柔善良，只是用玻璃般的外壳保护脆弱的心。所以她个性看似坚硬，实则脆弱，让人想要支撑她。

而总是被人支撑的自己却在想这些事，未免太不自量力。

——就像现在，临战之前才刚被她的贴心所拯救。

「————」

沐浴在热线下，盾牌的握把变得高温烫手。手就像插进煮沸的锅子里头一样疼痛，但格林死都不放掉盾牌。

自己不会用剑，又失去了声音。正因如此，不能再放掉最后这面盾。

「我的亚尔·吉瓦尔德被——？」

前方释放魔法的魔女惊愕到声音发抖。从她的手掌发射出来的白光，被格林的盾牌给反射到大会厅的天花板。

除了烫，没有其他损伤。盾牌彻底断绝热线，救了格林和罗兹瓦尔。

盾牌的内侧刻有卡萝的老家——雷玫迪斯的家徽。是卡萝为了庆祝格林康复而亲手交给他的宝盾。而这礼物拯救了性命。

「——！」

手掌在高温下烧焦，痛得沙哑喉咙吼叫。被反射的热线破坏整个天花板，导致大会厅正上方的地板崩落。

大会厅的正上方——刚好是「猛犬」与「毒蛇」激战的谒见大厅。

「什、什么——！？」

在热线的破坏下没了脚下的地板，崩落的人影跌进大会厅。错愕出声的是满身伤的波尔德，他用战斧刺向墙壁稳住身躯。尽管跟著地板砸落地面，但最终免于受到致命伤。

「唔……！这里是大会厅……？到底怎么了？」

甩甩头，陷入混乱的波尔德视线游移。但是，他身旁掉落的影子虽然毫无防备地摔在地上，却还慢慢站起来，让人感觉不到有受伤。

被绿色鳞片覆盖的高个——无疑就是蛇人利布雷·菲尔密。

「这下子，形势逆转了。」

魔法被防御住，但却得到最强尸兵这个援军。魔女移动到站著不动的利布雷身旁，在他面前伸直右手，指向跪地的格林和备战状态的罗兹瓦尔。

「虽然你们有人数优势，但论质量是我有利。利布雷，要·仔·细·听·好。接下来你是主力，我来掩护——」

这么说著，她向尸兵下指令——但讲到一半就中断了。

原因是斩击。而且还是来自身旁、出乎意料的一击。

「——咦？」

指向罗兹瓦尔他们的右手从手肘处断掉，在空中旋转飞舞。以意想不到的形式失去双手，喷血的魔女看向利布雷。

挥舞双头剑的尸兵——利布雷·菲尔密瞥了魔女一眼后，手中武器掉落。原因出在他胸口被挖出又深又大的斧击伤口，而且是致命伤。

利布雷·菲尔密这具尸兵，已经败给波尔德·卓格夫。

「竟然、在结束之前……完成了、临终誓言……？」

痛苦不堪的史芬克丝语毕，利布雷的尸体就开始失去轮廓。逐渐崩解的颀长身体留下长袍，肉体变成灰烬残块。

亚人族最强战士，连死后都被利用的蛇人，其真正的死亡样貌。

「形势再度逆转了呢，史芬克丝。」

「唔……！」

看到尸兵死去，又失去使用魔法的双手，还被罗兹瓦尔残酷宣告。史芬克丝头一次失去从容，脸上浮现焦急。她动用仅存的手段——使用腾空魔法，从大会厅飞向走廊逃跑。

「——！不能让她逃了……！」

「事到如今，连逃跑的手段——都没了呢。——那个交给我来收拾。」

制止想要追上去的卡萝，罗兹瓦尔亲自去送魔女归西。直接冲向走廊的她在身影消失之前转过头来。

「跟你道声谢，格林·法先。要是没有你，我就没法完成我的夙愿。我向至今瞧不起你一事道歉。也要跟卡萝说声对不起。」

「————」

「用、用不著道歉！比起这件事，请快解决她！」

卡萝人在持盾撑到最后的格林身旁，被揶揄后红著脸大叫。罗兹瓦尔像平常一样，一脸悠哉地点头，接著脚蹬地面。

「楼下还有声响传来。先去帮威尔海姆，之后再会合吧。」

留下这句话，罗兹瓦尔就穿越走廊去追史芬克丝。而被留下的格林和卡萝面面相觑后，跑向波尔德。

「……利布雷和魔女都收拾掉啦。威尔海姆呢？」

「在礼拜堂，正跟因为术式效果而巨大化的巴尔加·克罗姆威尔交战。老实说，我很怀疑他需要我们的协助吗……」

回应波尔德的卡萝一脸复杂地说。

有所拘束的态度，不是因为抗拒帮忙威尔海姆，而是深知剑鬼的力量才会有的判断。只是，威尔海姆和卡萝真的就是处不来。

因为太过敌视，使得她判断失准。

「————」

「……哼，真嚣张。不过就因为这样，你也是卓格夫队的男子汉啊。」

格林无言地将手伸向跪著的波尔德。对此波尔德勇猛一笑，握住他的手拉起身体。然后扛起战斧，朝著目瞪口呆的卡萝点头。

「确实，威尔海姆——那个剑鬼用不著我们助阵。去了可能会被当成碍事。可是呢，用不著介意。就算会被说没必要去，那也是一种余兴——不过，假如他力有未逮的话。」

「力有未逮的话？」

「那就终于可以帮上他的忙了。——我们欠那家伙的可多得咧！」

说完，豪迈地拍拍卡萝的肩膀，波尔德就跑往礼拜堂。跟在后头的格林则是朝表情复杂的卡萝一笑。

然后——

9

「——格林！！配合我！！」「——！！」

面对敲下来的拳头，介入的人影从正下方施展攻击。

长剑前端钻进巨大手指的缝隙间，盾牌则是撞向手腕，然后是在这两者之后、划出弧形的斧枪强烈一击。

「哼唔唔唔唔唔唔——！！」

波尔德发出低吟，战斧敲在稍稍停下的指头根部。皮肤的硬度防御住斧头的切断能力，但无法连敲击力道都一并抵销。破坏声响近似树木倒塌声，拳头的中指和食指都从根部折向反方向。

「呃呜……！？」

手指被反折的痛苦让巴尔加惨叫。见拳头缩回去，波尔德笑了。接著狰狞露齿的大块头，在看到坐在墙边的威尔海姆后加深笑意。

「怎么啦怎么啦，威尔海姆！不像你喔！放弃了吗？你这样子，还算是名满天下的卓格夫队冲锋队长吗！」

「——！」

被笨蛋毫不客气地讲成这样，威尔海姆握紧撑在地板上的手。吐掉卡在喉咙深处的血块，攀著墙壁用力让自己站起来。

「少随便乱讲……而且，我又没拜托你们救我。」

「嘎哈哈哈！加上嘴硬就更少见了呢！没死是有价值的！真想让皮波特他们也听听看！」

「————」

波尔德无心的话，让威尔海姆失声。

他说的没错。威尔海姆又再一次被别人拯救，免于「死亡」。就跟皮波特和卓格夫队的同伴那时一样，被迫活下来。

威尔海姆没出声；取而代之的是巴尔加看了看波尔德他们之后，摇了摇头。

「援军……不，你们会出现在这，代表利布雷和史芬克丝走了吧。」

「利布雷·菲尔密化成灰，魔女史芬克丝由梅札斯大人收拾。亚人联军的主使者只剩下你了……巴尔加·克罗姆威尔。」

伸出长剑，卡萝宣告另两人战死。巴尔加闻言，用手掌盖住被血弄脏的脸，但只沈默几秒，喉咙就开始震动。

像是震动空气的声响连续发出，听起来是笑声。

「有什么好笑的！」

「你们人类，真的什么都不懂。明明彼此大开杀戒，却完全不懂我们的主张和意义！」

宛若爆炸声的叫喊震响礼拜堂，让人错以为是风的怒气撼动地底空气。巨脸充满愤怒，咬牙切齿的巴尔加张开双手。

「战争不会停止。就算利布雷和史芬克丝走了，就算你们在这杀了老朽……也绝对止不住亚人族的怒火！消除不了亚人族的憎恨！」

「————」

「就算今天的战斗以失败告终，有朝一日亚人族的怒火也会烧毁王国。只要你们没察觉到我们的、同胞的、祖灵的愤怒理由——！」

破口大骂又如此断言，巴尔加的震怒令卡萝和波尔德沈默。灌注在话语里头的激情，足以为他主张战争不会结束一事背书。

大量人员死伤，国家雕弊，即使如此战争却还是不结束。一想到这个可能，视野宽阔的波尔德他们才理解到这有多沈重。

但是，也有人不这么想。

「——少啰哩叭唆个没完，凈讲些有的没的。」

这样说死的，是全身喷发剑气的威尔海姆。

剑鬼粗鲁地擦拭脸上的血，边喘气边瞪著「巨人」。

「把一切都赌在现在、这瞬间吧。你死后的事！？这场战争会变怎样？那些事有什么意义。现在，在这，你要怎么做，决定了你的一切！」

「肤浅……不对，乳臭未干！你的视野太窄了！想法太天真了！自己的战斗就是一切？那你没参与的战争呢！这场战斗结束后呢！要怎么办！？」

「——往前冲，砍人。在结束之前，杀光一切。」

威尔海姆的答案简洁有力。

听到这么肤浅又不成熟的愚蠢答案，巴尔加·克罗姆威尔哑口无言。

没能立刻否定的理由不是因为震惊，而是因为对方是说真的。

威尔海姆·托利亚斯这番话，是他的真心话。

「没别的了。我不知道其他的方法。所以说，就是砍！」

原本就没有其他事是威尔海姆·托利亚斯能做的。

威尔海姆被迫活下去。被皮波特他们，这次是被波尔德他们强留在世上。

假如被要求活下去是有意义的话。假如有人期望威尔海姆做什么的话。

——就只有战斗，是威尔海姆可以回应的。

「……连交谈的价值都没有。跟你这人没必要说话。用不著多费唇舌。」

看著徒手却散发剑气的威尔海姆，巴尔加无力摇头。

事已至此，剑鬼与巨人、人类与亚人是完全决裂。彼此认为对方是无法互相理解的存在，一度停止的战斗再度开始。

威尔海姆的爱剑还插在巴尔加的嘴唇上。剑鬼必须躲过攻击夺回剑，方能开始作战。

「——你以为赢得了吗，人类！！」

「巨人」巴尔加·克罗姆威尔大吼。

「我对胜负没兴趣。——你会在这里被我杀死。」

「剑鬼」威尔海姆·托利亚斯回应。

——最终决战开始。

10

翻转身体，躲过手指。精疲力尽，浑身是伤，伤势和体力都早已濒临极限。然而肉体却比状态良好时还要灵敏。就像即将烧尽的蜡烛光芒最为强烈，舍弃性命以外的多余之物，精神力集中到顶点，就是这种感觉。

挥别迷惘。现在，拋弃所有看不见的重担后，威尔海姆感到身心轻盈。

「——哈哈。」

感觉真棒。太舒畅了。心灵从未这么深入地沈浸在战斗里。

在生死关头，世界仿佛只有自己和巴尔加。

闯进礼拜堂的波尔德和格林似乎没打算介入这场单挑。庆幸他们没那么不识趣，另一方面也了解他们是将战场交托在自己身上。

「————」

手指撞碎地板，从旁拍过来的巴掌就蹬墙跳跃来躲避。著地的瞬间压低身子急驰，丢下对方的连续敲击后接近对方。

拋弃无谓思考，沈浸在只属于自己的性命争夺战。

「跑来跑去、烦死人的渺小人类——！！」

面对在礼拜堂内穿梭害自己没法瞄准的威尔海姆，巴尔加烦躁地说。

虽然地下设施盖得很坚固，但已经被毁得毫无庄严感。重建会耗费不少功夫和时间吧。没被破坏到的就只有巴尔加背后、被雕刻在墙壁上的龙之国徽。

损害不只限于礼拜堂。在分头和史芬克丝与利布雷的尸兵战斗时，城内应该被破坏得很惨。虽说两边都有必须回敬之仇，但被人从旁抢夺心情会很差。可是，波尔德和格林都还活著。既然如此，也没差啦。

「你还有闲情逸致看别处……！」

「——只是在确认没这么做的必要。很吵耶你。」

面对气到声音发抖的巴尔加，威尔海姆丢掉心中最后的杂质。

因此现在，剑鬼完全觉醒了。

「就让我全数奉还吧——！」

背向并闪过灌注愤怒的里拳，剑鬼钻到巨人的胸前。巨人的另一只手想要捏死威尔海姆，但剑鬼却利用手指当立足点进而跳跃。终于，伸出的手抓住——插在巴尔加嘴唇上的剑，并横向劈开。

散播血花后落地的剑鬼，巴尔加边痛苦呻吟边用巴掌加以招呼。瞥了一眼瞄准自己膝盖的攻击，威尔海姆切换位置挥剑。

——纵向斩击掀掉巴尔加右手三片指甲。

每一片都有人头那么大。剑插进指甲和指头的缝隙，切破皮肤、剥掉指甲。火热的痛楚让巴尔加吭不了声，剑鬼冲向其后仰的身体。

目标是脖子以上的要害——都不是，是巴尔加的胸膛。

闪耀紫色光芒的纹路，其中光芒最耀眼的胸口处，埋藏著巨大化的原因——骨片。

「喝、呀啊啊啊啊啊——！！」

反手握剑，使尽浑身的力量砍下去。剑尖稍稍刺进巴尔加的锁骨内侧的肉里——下一秒，剑尖就碰到了骨片。

感受到坚硬触感后，威尔海姆一踢巴尔加的下巴，再顺势把体重压在剑柄上。利用杠杆原理施力，让勾著骨片的剑挖出一块肉。

012

「臭小子——！！」

巴尔加终于知道威尔海姆的目的，于是双手用力在胸前击掌。在被拍烂之前，剑鬼踢了他的腹部一脚，朝正上方一个后空翻，而剑像搅拌一样的动作就将骨片给挖了出来，强烈光芒笼罩整个礼拜堂。

「呃！呜喔喔喔！？」

始祖之骨被抢，巴尔加失去巨大化源头的肉体迅速失去力气。刻在身上的纹路还在发光，但注入的玛那量对原本的身体来说太过庞大，结果夹在肉体弱化和魔法阵强化的情况下，身体先承受不住。

「哦、哦哦哦……！」

身体处处都在喷血，巴尔加当场跪地。超过十公尺的庞大身躯发出声音轰然萎地、逐渐缩小。

「————」

巴尔加双眼流出血泪、微微呻吟的同时，瞪著面前的威尔海姆。握著剑的对方毫不大意，正面承受他的视线。

然后，巴尔加举起摸著伤口的手，拳头比向威尔海姆。

「……我的胜算，只剩下这瞬间。」

「——哦哦！」

没有丧失战意，最后的单挑宣言——对这要求，剑鬼予以回应。

「上啰，人类。」

「放马过来，亚人。」

彼此平静宣告，巨人和剑鬼的最后交错即将开始。

连吶喊的力气都倾注在手上，巴尔加将有大树一样粗的双手交握，一口气往下捶。使尽吃奶力量的一捶敲碎地板，让人觉得不只礼拜堂，连整座城堡都在摇晃。

但是，敲击的落点上却不见威尔海姆。

「吁——！！」

在千钧一发之际闪过敲击，威尔海姆钻进巴尔加的脚下。剑身气魄十足地挥洒，斩断巴尔加的小腿。剑身在猛烈的手感下陷入强度下降的肉体中，割肉断骨，然后再反手一刀刺进大腿。

「哦、哦哦哦哦——！！」

斩断腿，紧接著是腰，旋转身子戳进腹部，纵向旋转深深劈进胸膛，借著在空中旋转的力道砍向双肩，新生的割伤接二连三喷血。

疯狂肆虐的银色闪光切割巨人肉体，最后扫向脖子——一闪。

「给我听好了，人类。」

一个呼吸就使出无数剑击，然后落地。这时，巴尔加对他开口。

巨人任由脖子上的伤淌血，平静地朝背对背而立的剑鬼说。

「——别以为这样，就断得了亚人族的愤怒。」

跪在地上的大块头身体失去力气，头部就这么撞击地板。加上这次的撞击力道，礼拜堂里本已龟裂的地面崩塌。形成的洞穴通往王城地底更深处的黑暗，巴尔加的大块头身躯就这样被吞进黑暗中。

「……有多少都尽管过来。」

看著巴尔加摔落，站在大洞旁边的威尔海姆这么说。

浴血剑鬼的身后背著礼拜堂墙壁上的王国国徽——

「只要我的剑还在，就会挡住他们。我会一直砍，直到结局到来。」

那是剑鬼与巨人的对决，威尔海姆与巴尔加对彼此的宣言。

11

从怀中掏出的，是可以在掌心上滚动的铁球。连里头都是钢铁打造而成的铁球和外观相反，重量十分沈重，要是不小心掉到脚上有可能会砸碎脚趾骨。

当然，被这样的铁球命中，威力足以匹敌拳击。

「嘎、哈呜……！」

背部中央和下腹部各中一颗罗兹瓦尔丢出的铁球，威力大到让史芬克丝惨叫，无法继续飘浮而用力撞上墙壁，最后沿著墙壁滑落地面。这段期间，追击的铁球继续猛击魔女。骨头断裂，鲜血四溅。

「——放弃用飞的逃跑了——吗？」

罗兹瓦尔边在手中旋转铁球边缩短距离，同时问史芬克丝。

逃离大会厅，在王城内胡乱逃窜的她，因为失去双手而无法使用魔法，负伤流的血又成了让人追踪的线索，因此根本就逃不掉。

结果，被不断从远处悠哉扔掷铁球的罗兹瓦尔当成靶子。

「这个、铁球……是打下我、的方法……」

「很——棒的玩意吧？原本在准备虐杀你的工具，意外得到这个副产品。很遗憾，凭我纤细的手臂扔得不是很～好呢。——说了这么多，铁球也要用光了。逃脱剧差不多该落幕了。」

手中的铁球朝倒在走廊一头的魔女扔出，砸碎骨头。罗兹瓦尔一边俯视喘气的魔女，一边握拳准备让她断气。但是——

「你的个性、似乎……比巴尔加、还恶劣。……要·当·心。」

「哦～？由你给我忠告挺有意思的。要当心什么？」

「——脚不要被绊到了。」

史芬克丝不带感情地说完，就用头去摩擦走廊墙壁。沾到血的浅红色头发黏在墙壁上，惹得罗兹瓦尔皱眉，心想她在干什么的时候，忽然听到细微的声响。

走廊的隐藏机关启动，地板旋转，吞掉了史芬克丝。

「————」

看到她消失在地板下，罗兹瓦尔判断那是设置在王城各处的隐藏机关——城堡果然被亚人入侵了。

「但是，可争取不了多少时间。」

仔细调查史芬克丝消失的地点，罗兹瓦尔迅速看穿机关位置和操作方法。然后启动机关，自行坠入地底。

著地后，在黑暗中凝神细看。可以听见微弱的水流声，想必这里是在王城地底蔓延的地下水脉坑道。光源就只有嵌在墙壁上的矿石所发出的淡淡光芒。踩著湿滑的地面，罗兹瓦尔顺著血腥味追踪。

血腥味还很新鲜，可是途中突然变成别种臭味。对这变化感到不寻常而加快脚步，最后当她抵达时——

「那边那位，是梅札斯女史吗？」

被男人嘶哑的声音叫唤，罗兹瓦尔停下脚步。前方从暗处缓缓露脸的，是原本驻守在王城正门的莱夫·跋利耶尔。

「果然是你。你也是追亚人追到地底的样子。」

「看来莱夫殿下也一样……是——吗？」

正骑士确认来者是罗兹瓦尔后，就将手上提著的短铳挂回腰际。没见过的武器，恐怕是能发挥超常之力的魔法兵器「流星」。但是，罗兹瓦尔没有提及，而是观察他的身后。

「亚人族的主力史芬克丝逃进这里了。有看到吗？」

「魔女吗。放心吧。——刚刚已经被我收拾掉了。」

「————」

听莱夫这么断言，罗兹瓦尔屏息。看到她面颊微微一僵，莱夫阴沈的面容持续冒出卑鄙笑容。

「扫荡进入城堡的亚人，追击逃跑的家伙而进到这里。没想到王城地底有这样的地方……不过在路上，我遇到没有手的魔女。就二话不说烧了她了。」

「烧了她……尸体呢？」

「变成灰了。不知道是什么原理，不过，余烬里头留下这个。」

手伸进衣服，莱夫拿出一条项链。只是用粗绳穿过戒指好让戒指能挂在脖子上的简单项链——但是，对罗兹瓦尔而言意义重大。

「——那个，可以给我——吗？」

「什么？」

「或许有魔法方面的价值。其实那刺激了我的研究欲望。」

莱夫沈默半晌，思考罗兹瓦尔的要求。但是，他很快就叹气，把项链扔到罗兹瓦尔手上，然后说：

「给你是没关系。不过，你可要在论功行赏的时候帮我做证。我莱夫·跋利耶尔才是在水边阻止『魔女』史芬克丝逃跑并收拾她的功臣。」

「……嗯，知道了。这我欠你的，莱夫殿下。」

接过项链——用力握紧戒指，罗兹瓦尔只说了这句就转过身。

拿到这个，就用不著待在这了。一时大意就断送了让史芬克丝咽下最后一口气的机会，不过只要她死了就没什么好说了。一切都按照计划进行。

「老师，善后收拾结束了。——之后就是为了未来。」

怜爱地以手指抚摸戒指，罗兹瓦尔·J·梅札斯这么低喃。

在黑暗中，她那谁也无从得见的脸庞，正以安心至极的表情微笑。

——目送远去的罗兹瓦尔，莱夫·跋利耶尔轻声以鼻子喷气。

「搞不懂在想什么……可怕的女人。」

收下戒指后，罗兹瓦尔似乎就早早离开了地底。虽然是趁了自己的意，但却叫人耿耿于怀。看那样子，她打从一开始的目的就只有戒指。

「哼，算了。女狐狸的目的跟我无关。」

对莱夫来说，重要的就只有顺从野心，爬升自己的地位而已。

在前一场爱西亚湿地地带吃败仗之后，莱夫的立场就一直处在逆风状态。曾经贵为大军指挥官的他被流放到闲差，甚至还被检讨是否要降爵。

无法理解。在无能者和弱者充斥的世界里，为何有能力的自己要被贬低？

「我要取回失去的一切——不只！还要得到更多！」

只要能达成这目标，自己什么都会做。对王国的忠诚，就丢到一旁去吧。

莱夫王国只需要自己，莱夫的世界是只属于自己的。

「————」

转过身，在坑道深处扛起像破抹布般倒地的小身影。莱夫把失去双手的轻盈身体抱起来，从另一条路脱离地底。

这个背信弃义之举，只是莱夫·跋利耶尔绵长野心的起点。

12

——在露格尼卡王城发生少数亚人族精锐潜入偷袭事件。

就结果而言，虽然王室成员无人伤亡，但王城各处被破坏，而且还发现亚人族入侵用的地下水脉坑道等等，因此善后并不容易。

在此次事件中被认为功劳有目共睹的卓格夫队，自然也被要求参与善后处理。不过只有威尔海姆不同，他把大半的杂事都扔给格林，然后自己溜出城堡。

「谁理你们啊……」

大战之后一脸疲惫的他，解开绷带后就走向骚动平息的城邑区。

巴尔加这些主力被打倒，王国各地蜂拥而起的暴动似乎也结束了，王都暂时恢复平稳。一边对此感到莫名感慨，他前往老地方。

「————」

为什么要拖著疲惫的身体来到这里，自己也不甚清楚。

说起来，在发生这么大的动乱后的隔天，王都虽然恢复平稳，但有鉴于王城受害，因此很多店面都打烊，大道上还是一样没什么人。

只要是脑袋正常的人，都唯恐被卷入骚动而不敢出门吧。也就是说，单纯以今天的状况而言，窝在家里的人才叫正常。

假如在这种状况下还会像平常一样外出散步——

「那种人才叫反常……」

快步穿越荒废的贫民窟，威尔海姆忘了自己的伤势抵达广场。迎面吹来的风带了些许花香，强迫人意识到花海的存在。

而广场的正中央，站著红发少女。

「————」

看到她的背影，威尔海姆的双脚停了下来。

涌上心头的复杂感情，同时具有肯定和否定。一方面相信她会在，一方面又惊讶她竟然真的在这里，两种感觉交缠，充斥胸口。

同时还有忧郁——即将面对平常的互动，内心还是感到几分尴尬。

反正都确认她没事了，干脆就这样转身离去吧。就在这么想的时候。

「————」

察觉到气息的特蕾希雅转过头来，蓝色瞳孔微微瞪大，然后眯起。

接著她的嘴唇弯出弧度，浮现微笑。

「——威尔海姆。」

被她亲昵地呼唤名字，威尔海姆感到放心，但心跳加快。

完全忘记刚刚只想著要离开现场，心脏的鼓动因遇到特蕾希雅而欢喜，安心与温暖逐渐盈满胸膛。

「——啊。」

察觉到这股冲动是什么的瞬间，整颗心毫无预兆为之震颤。

那真的是突如其来、不经意、出乎意料的自觉。

——看到特蕾希雅微笑，威尔海姆知道自己感到安心。

守护住了她的微笑、她的安危和与她共处的时间，他获得了成就感。

挥剑杀死其他人，证明自己的剑术——用这以外的形式，得到更甚的喜悦。威尔海姆在背负花海的特蕾希雅身上看到的感情，让自己意识到这些。

理解的同时溢出的感情奔流，是威尔海姆很早以前就扔弃、忘记的潮流。被那股奔流吞噬，威尔海姆以掌掩面。

「————」

眼皮底下变热，鼻子深处刺痛，喉咙急速干渴，血液循环加快，脑袋变得沈重。灵魂晃动到差点当场跪下。

脑内顿时浮现的，是早被忘记的光芒。

不，不是忘记。对自己来说，那份光芒从未褪色，一直都清晰刻在心上。自己不知不觉忘记的并非光芒的美丽，而是自己被光芒吸引后想到了什么。

那是自己第一次握住剑，举起剑，比向天空时所产生的想法。

假如有这光芒，假如这光芒是真的，假如那道光芒能变成实物。

——假如有那力量，就能守护一切。当时就是这么想的。

头一次握住剑、什么也办不到的无力幼童，期望能够得到什么的那一天。

「威尔海姆……」

特蕾希雅呼唤以掌掩面、被激情打垮的威尔海姆。现在的自己，在她眼中是多么丢人现眼呢？

就特蕾希雅来说，一定不明白现在的状况。她只是像平常一样过日子，偶然露脸的家伙却突然在她面前感情溃堤。

好丢脸。好久没觉得丢脸过了。丢脸的感觉强烈到叫人哽咽。

好想立刻逃离现场。自己用不著在别人面前丢人现眼，其中又最不想让特蕾希雅看到。这真的是想象得到的最坏发展了。

可是脚却不动，心灵也没反应。简直就像灵魂期望如此似的。

「————」

在彼此的沈默间，时间一点一点过去。突然，威尔海姆觉得手背攀上了柔软发痒的触感。因为特蕾希雅小心翼翼地伸手触碰威尔海姆掩面的手。

被柔细的手指触碰，那股热度让威尔海姆屏息。

别人的体温有这么烫吗？从手指传来的热度，让威尔海姆以为自己成了被扔进炼炉的钢铁。

在炉中被火焰焚烧，钢铁被特蕾希雅的热度锤打，逐渐改变形状。

——事到如今才知道，原来自己一直在这边被锻造。

在广场和她见面，交谈，不做约定就分开。一直重复。

在这不著边际的时间里，一直锤打著名为「威尔海姆」的这把剑。

——不，不对。不是只有她，自己熬著活下去的每一天都是。

特蕾希雅、格林、波尔德、罗兹瓦尔、卡萝、皮波特，还有卓格夫队队员。以及巴尔加、利布雷、史芬克丝和被砍死的众多敌人。

至今和名为威尔海姆的钢铁交流的所有一切，都打造出威尔海姆这把剑。

这一点，到了现在这一刻，他才终于察觉。

「你喜欢上花了吗？」

这问题丢向一直沈默、自觉自己被持续敲打的威尔海姆。

约定俗成的问答，一定是希望威尔海姆有所变化。

而事实上，威尔海姆终于自觉到自己在改变。

「……不讨厌。」

道出这三个字时，心中毫无勉强或不安。

在战场上看到花的时候，平常经过花旁边的时候，眺望广场花海的时候。

心中一定有著异于以往的感情。

「你为什么要挥剑？」

特蕾希雅继续问。

这个问答题本来让威尔海姆觉得苦恼。

但现在他终于想起来了。第一次握住剑时那一刻的心情。

「因为我……只想得到这种保护的方法。」

剑就是力量。是最美丽、最锐利、最纯粹的尊贵力量。

但是如何使用力量，将提高的力量用在何处，端看使用的人。

威尔海姆忘记的初心，现在终于回想起来了。

回想起最初。回想起一开始最喜欢剑的时候的心情。

「————」

放下遮住脸的手，威尔海姆牵起特蕾希雅伸向自己的手。「啊。」她轻叫一下，不过没有挥开威尔海姆的手。

虽然称不上是交握，只是单方面接触，但彼此的热度清晰传达给对方。

「————」

两人什么都没说，就只是互相凝视。

一方面不知道要说什么，另一方面又知道没必要说什么。就跟同为剑士的对峙一样，语言是多余的。

「————」

特蕾希雅只是一直朝威尔海姆微笑。就跟她平常眺望花海时会有的柔和笑容一样。

顿时，心头一阵战栗，威尔海姆被冲动支配。

想将难以言喻的心情投注给眼前的少女，但他克制下来。

尽管如此，无法完全压抑的情感奔流，还是朝外流露了一些。

这一天，威尔海姆头一次让特蕾希雅看到自己打从心底微笑。

013

13

——动摇露格尼卡王国全境的亚人族武装暴动。

突然就开始的暴动，跟揭幕时一个样，突然变得沈静。原因在于武装暴动的主使者、代表亚人族的三名领袖死亡。

亚人族的最强战士利布雷·菲尔密，大参谋巴尔加·克罗姆威尔，还有「魔女」史芬克丝。这三人在暴动中被人类杀死，因此暴动以失败告终。

这样一来亚人联军就失去首领，内战终于出现歇息的征兆。每个人都这么想。

但是实际状况却颠覆这种想法。各地的亚人族反抗活动越演越烈，就如巴尔加死前所言，亚人族的怒火绝对不会消失。

而且，人类终于体认到。

被死去的三人所率领的亚人联军，至今为止还算是保持理性对抗人类。失去煞车的憎恨会换来多凄惨的事态，人类其实还没真正面对亚人族的愤怒。

王国内战「亚人战争」的末期，最终幕由此开始。

而这也是「剑鬼」与「剑圣」的邂逅与别离的故事。

** 七幕

1

这阵子，卓格夫队出现一个火热话题。

是跟队伍主干有关的大事，每名队员都能切身感受到极大变化——甚至可以说是骤变。

「——拉兹洛，退下。」

用剑接住斧击的威尔海姆命令队员。刚好是被叫到名字的队员被敌人猛攻逼到紧要关头的时候，察觉到队员有难的威尔海姆如风一般奔回来，边为他承担敌人攻势，边发出刚刚的话。

挡在上气不接下气的队员面前，顷刻之间便将敌人顶回去。手持斧头的兽人被剑鬼的气魄给压过，身体被横劈之后惨嚎倒地。当然，接下来就是追击对手给予致命一击的场面——

「我拉你。快点退到后方，傻子。」

但威尔海姆在把敌人顶回去后就没再穷追猛打，反而还搀扶受伤队员。难以想象细瘦的他竟然一拉就把身形比他壮硕的队员拉起来。被救的队员提心吊胆地道谢。

「对、对不起，副队长！」

「有空道歉的话，平常就多锻炼好让自己变得有用点。要是那么喜欢后头，那不管过多久，前线都会有个洞。」

嘴巴说著惹人嫌的话，但脚步又看得出运送伤者的贴心。其他队员也帮忙掩护后送行为。等伤者平安撤退，剑鬼又回到战场。

然后持剑一举扫除挡路的敌兵，开出一条路同时大喊。

「别像小鬼头打架，卓格夫队！看著前方，战斗！！」

不只对自己，还鼓舞周围的同伴，然后奔跑。

每当银色闪光乱舞都会有敌兵倒地，战场的士气以剑鬼为中心在提升。

「剑鬼」威尔海姆·托利亚斯的名字，如今雄赳赳气昂昂威震八方，甚至传出——他是王国军的希望、亚人联军的绝望。

「那个男人怎么会变这样……真恶心。」

「不要这么说嘛，卡萝姑娘。威尔海姆也有自己的想法呀。不过说真的，长年看著他的我也觉得他的变化有点恶心！」

以斧枪击溃面前的队伍、粉碎亚人的波尔德以豪迈大笑响应卡萝的意见。斜瞄他一眼，卡萝以长剑牵制攻过来的敌兵，同时继续动嘴巴。

「我可是知道他以前是怎样的人，那不是用心寒就能形容的。他一定是在策划什么才这样做……总有一天会露出马脚的。」

卡萝的眼神像在看可怕的东西，身旁的格林则是敲盾牌表达意见。平常温和的表情，现在却露出谴责。卡萝见了，缩了一下肩膀。

「对不起，格林。可是，我实在是不习惯……」

「如何看待那家伙现在的作为，队伍里头的意见也很分歧。不过，我跟格林还有其他队员的结论一样。虽然变动剧烈……但这变化不会不好。」

「……这我也知道啦。」

「唉哟，正所谓『钢铁会因为热度和槌子改变锋利度』，因为他是别扭的家伙嘛。搞不好有契机的话，他意外地会是变化得很快的那类型。假如那个契机是女人的话，就更有意思了。」

「呜……」

「怎么著，你那反应。是想到什么了吗？」

卡萝对自己的话有反应，使得波尔德好奇地盯著她看。对此卡萝不悦地撇过脸，端正的脸庞面露难色。

「就我来说……跟我本来的职务有关，顶多只能这样讲。请体谅。」

「所以说不是没关系啰。唉呀，知道了。我不会再多问了。」

「感激不尽。不过我真的还是不习惯……」

卡萝的视线尽头，威尔海姆再度保护同伴然后横扫敌人。在战斗时帮助队友还给予确实的建议，简直就像换了个人一样。

要是因此精神不集中导致战斗力低下的话，就能说他是多管闲事；可是威尔海姆的剑并没有因此变钝——不，剑气甚至比以前还强烈。

「————」

「好啦，我知道了，格林！不要大意，排除敌人吧！」

无言的格林表示不能输给威尔海姆，卡萝也赞同并加以配合。看著两人并肩加入前线作战，波尔德双肩扛著斧枪说：

「假如是态度上的变化，跟格林开始交往的卡萝姑娘也变了很多……只是她没自觉吧。真是的，大家都还是年轻人啊！」

大笑后往旁边看以征求同意，但习惯性看过去的位置却没有熟悉的面容。波尔德用手指搔了搔脸上的伤，然后扭动脖子，接著大喊：

「我说啊，你们！留些猎物给我！我要把蛮族一个一个消灭！」

经过王城一役，波尔德·卓格夫的内心疙瘩消失，斧枪术也益发精进。

为了发挥个中价值，他这个指挥官也亲自冲进战线正中央。

这就是掺杂了卓格夫队有所变化与不变之处的战场。

2

防卫战的派遣时间结束，卓格夫队回到睽违两个礼拜的王都。

昨天很晚才回到王都的队员，绝大部分都用睡觉度过第一天假期。但是，在这些人当中最骁勇奋战的威尔海姆，却大清早就起来离开营房。

在冷冽清澈的空气中，卫兵挺直脊梁朝腰挂爱剑的威尔海姆敬礼。威尔海姆举个手回应，就前往城邑区。

每次去贫民窟广场都没有特别指名日期或时间。因为彼此都不知道对方当日的安排，而且威尔海姆的假期也是不固定的。

因此抵达目的地时，对方是否会在端看运气。而今天——

「唉呀，威尔海姆。你今天有来呢。」

先抵达广场的特蕾希雅注意到威尔海姆而转身。红色长发迎风摇曳，威尔海姆看著微笑的她并皱眉。

原因在于她站著的位置。不知何故，她站在花海里头。

「在干什么呀，这女人……你一脸想这么说的样子呢。」

「谢谢你帮我说出我的想法。你在干什么呀，那边的女人。」

「唉呀呀，还重说一遍。那么，问题来了。我在做什么呢～？」

耍赖地说完，特蕾希雅在花海中抬起脚。光著脚的她拎起裙摆，露出白皙双腿。威尔海姆立刻别过眼。

「唉呀呀呀？对纯情青少年来说刺激太强烈了？」

「你这个野丫头也差不多一点，白痴。之前就说过这边的治安不好吧。那样浑身给人可趁之机，早晚会倒大楣。」

「哦，那不用担心。毕竟，这里老是会有个很强的剑士先生来巡逻，对吧？」

说完还眨眼，搞得威尔海姆吭不出声。感觉被玩弄在股掌间，青年边抓自己的咖啡色头发边走向少女。

「好啦，结果你到底在干嘛？你已经过了童心未泯光脚玩泥巴的年纪了吧。」

「很、很失礼耶你！而且童心未泯好歹是我这个年纪的特权。还有，我不是在玩泥巴！你全部都猜错啦！瞎眼了你！神经大条！」

「为什么我非得被你讲成这样不可啊。」

真的是感情很丰沛旺盛的女生。很爱笑，也很爱生气。

兴奋的声音，激动的声音，灿笑和生气的脸，真的是怎么看都看不腻。威尔海姆打从心底这么想。

连自己都觉得自己没药救了。

「正确答案是……我在洒新的花种子！」

「新的种子？」

看著她的侧脸看到入神时，性急的特蕾希雅主动公布答案。听了她的话，威尔海姆歪头表达不解，于是她伸手比向花海。

「没错，新的种子。季节也要变了，花海也到了准备换衣服的时候啦。虽然花枯了会很寂寞，但为了下一季，所以要培育新的花。」

「什么培育，我从来没看过你浇水还啥的。」

「是、是花儿们自己长得很快，但播种的人是我！而且这次我打算好好照料。可用不著给我浇冷水喔？」

那句吐槽，她不加倍奉还似乎就不甘愿。威尔海姆任她说教，不过她话锋一转，突然看著花海说：

「而且，要是这里没开花，就没借口过来了。」

「——！」

听到借口这两个字，威尔海姆忍不住屏息。

对持续在这幽会的两人来说，是深入这层默契的态度。

「————」

特蕾希雅会来这里，是为了欣赏花海。威尔海姆则是来这边练剑。只不过，如今这些目的已经丧失一半的机能。

特蕾希雅还好，但威尔海姆已经完全忘记当初来这的目的。当然，并不是练剑这件事变得不再重要，只是来这的理由变成了特蕾希雅。

而这件事，对两人来说理应都是心知肚明。但是彼此都没说出口，继续维持这种形式的幽会，一定是因为害怕这段关系产生变化吧。

即便到了假装自己没发现，但内心早已被千锤百炼到有所变化的如今也是。

「……对了，有件事我想向你报告。」

「报告？」

耐不住被凝视而背过脸的威尔海姆这么说。特蕾希雅歪起小脑袋好奇反问。脸颊感受著她的视线，威尔海姆点头。

「嗯。我的战功获得认可。——上头提到授勋的事，我成为骑士了。」

「————」

感觉得到特蕾希雅倒抽一口气。威尔海姆握拳，装作没看到她的反应。

得以被授勋为骑士的决定性功绩，在于成功阻止亚人攻下王城。再加上之后威尔海姆的处世态度有所变化，搭配波尔德等人的推荐，于是就出现授勋这话题。

以前的自己应该会拒绝，但现在威尔海姆却感激地接受。

自己的功劳被他人认可，还有接受这证明的自豪。要是糟蹋波尔德他们的贴心，自己会觉得愧对他们。

而且，有了骑士的身份，内心也开始有荣誉感。

「是吗？恭喜。离梦想更近一步了呢。」

「梦想？」

正因为内心产生这样的想法，所以听到特蕾希雅的回答感到意外又惊讶。

见威尔海姆目瞪口呆，她似乎觉得很好笑，手掩著嘴巴说：

「你是为了守护才握剑的吧？骑士都是为了守护某个人而生的。」

讲得一脸蛮不在乎的样子，却不知为何又笑得洋洋得意。

原来如此。威尔海姆接受了。同时把她的笑容烙印在眼底。

——为了让她的存在，也确实留在要守护的东西里头。

3

结束与特蕾希雅的约会后，中午时分威尔海姆前往商人街。

即使王国因长久内战而雕零，但不妨碍进出王国的商人的野心。王都里头就只剩下商人街还留有平常的活力，熟悉的餐馆也一样。

「老样子。」

在入口跟服务生点完单，威尔海姆就走向店内最里头的座位。结果发现自己要等的对象已经坐在那里喝酒了。

「大白天就喝酒啊。虽说没值班，还真有品味啊。」

一屁股坐在饮酒客人对面，劈头就说惹人厌的话。但是，对方只是以无声笑容响应，然后也打算帮他倒酒。

摇头拒绝后，服务生过来倒水。举杯要喝水时，面前的人举起酒杯要求击杯，威尔海姆皱眉，但还是照做了。

『想都没想到竟然会有跟你一道喝酒的一天。』

用第一口润喉后，流畅的文字便递到眼前。最近已经习惯了，不过不方便之处还是没变。威尔海姆用手指轻弹一下纸。

「我也是。不过，我不喝酒。谁会爱喝那种东西呀。」

『你这点还是没变耶。』

含笑的格林以简短句子回应，威尔海姆反省自己的心直口快。马上就讲惹人厌的难听话、摆出攻击性的姿态是自己的坏习惯。虽然想要改变，但长年培养出的个性不是说改就能轻易改掉的。

「————」

结果只好沈默，仰赖继续喝酒的格林的度量。一这么想，就察觉自己一直以来都被宠坏了。

下意识地触碰腰际的爱剑，熟悉的触感唤醒安全感。突然，格林把酒杯一放，用空著的手指向威尔海姆的胸口。

「——？哦，徽章啊。毕竟好歹也成了骑士嘛。」

格林的视线尽头，是别在威尔海姆左胸、以龙为意象的王国骑士徽章。受封为骑士后便会被给予嵌有龙珠的身份证明徽章。

「平民可以从一介士兵被授勋为骑士，似乎是史无前例……嘛，结果我的出身一曝光，这种评价也就跟著消失了啦。」

一时之间，威尔海姆成了平民模范和期待之星，但在知道他出身于露格尼卡贵族后，接受「剑鬼」这个称号的人就比感到惊讶的人还多了。明明家世出身对剑术的影响不多，但人类就是比较相信名声是靠趋炎附势得来的。

「虽说被封为骑士，但也没什么夸张的改变。你才是咧，如果跟卡萝共结连理的话就等于入了名门。那条路还比较快吧？」

被连连逼问会居于劣势，于是反过来攻对方痛处。结果，即使无法出声，格林整张脸照样红透了，似乎决定不答腔，所以嘴巴沾著酒杯不放。

能够从表情和动作大致了解格林的想法，也是其中一种变化。

比以前更留意周遭后，发现一件有趣的事。那就是除了语言，人类的想法还会透过其他方式表露在外。至今只用在战场和战斗上的观察力，现在也派上了用场。

『有跟老家的人说你成了骑士吗？』

「跟老家联络？不，没有。事到如今哪有那个脸……一方面是这样，再来就是授勋后马上联络很奇怪吧。至少等内战结束再说。」

因为授勋一事，因此上层有跟威尔海姆的原生家庭联络并确认关系。当然，留在老家的家人应该也知道这件事了，但正因如此才有必要划清界线。

受封为骑士，又不是什么可以夸耀的成果。要归乡的话就要有更确切的理由。

『例如，结婚后带老婆回乡探亲？』

「噗——！」

瞥到的文字内容让威尔海姆把喝的水喷了出来。突然讲什么奇怪的话啊！虽然这样瞪著他，但格林的脸上却掩不住笑意。

刚刚的回敬被原封不动地奉还了。忍不住有反应的自己实在很白痴。

『这阵子，你给人的感觉变了很多。是受了某人的影响吧，现在队上都在讨论这个。』

「……真要聊的话，也找点更有意义的话题吧。」

『虽然直接跟当事人说似乎也不太妥，但大家觉得很讶异。到底是怎样的女生呢？』

格林已经坚信威尔海姆改变的原因是女人。虽然不算错，但这边要是能肯定的话，也就不算对特蕾希雅本人有所蒙混了。

「白痴什么。那种蠢事……」

『如果接受骑士授勋是为了那女生，那最有可能的……不会是梅札斯女史吧？』

「别开玩笑了！就算朴利斯提拉沈进水里，我也不会跟那女的在一起！」

『用不著否认到这种地步吧。』

格林苦笑，不过威尔海姆是真的起了鸡皮疙瘩，希望他别再开玩笑。

顺带一提，朴利斯提拉是露格尼卡西部的大都市，紧邻一条大河，但得利于几百年前的水利设施，因此不曾闹过水灾，是个水路发达的城市。

「说起来，她最近都不上战场了。偶尔才会见到她。」

『搞不好那个偶尔是刻意来见你，很可爱不是吗。』

成功消灭「魔女」史芬克丝后，亚人联军与魔法相关的攻势就大幅弱化。因此，魔法顾问罗兹瓦尔上战场的机会也就随之骤减。

不过，即便如此她还是会来露脸给威尔海姆看，虽是偶尔，但却是不辞辛劳。

『卡萝小姐都跟女史在一起，因此她们上战场的机会减少，我很安心。即使知道她比我还强，但还是不希望她到现在的战场上。』

「是啊。」

点头同意格林的意见，心烦意乱的威尔海姆用力靠在椅背上。

——亚人联军的攻势在失去支柱巴尔加等人后也没有停歇。不仅如此，行为还比以前更激烈，朝向不顾一切的方向发展。

「少了作战参谋这个煞车，所以没人压得住他们。抱著牺牲的觉悟冲锋陷阵实在很愚蠢，但也因此死伤变得极为严重。」

『因为没有退路了吧。明明战况早就那么惨烈了。』

在王城的血战，可说是亚人联军主力竭尽全力的结果吧。

跨越那场赌局后，战火别说收敛，反而火力更甚。这实在是超乎预料——不，恐怕巴尔加早就预期到会有这种结果。应该说，那是他的期望。

「用自己的死，点燃亚人的怒火……想让战争变成两败俱伤吧。」

『就算如此，以数量来看还是对亚人不利。这种事巴尔加应该也知道。』

令人纳闷。格林不解，但威尔海姆能懂。

因为巴尔加·克罗姆威尔想要毁灭世界。他强迫推销自己的理论，想用不讲理劈开世界，留下会让局势大幅倾斜的伤痕。

假如巴尔加的目的是如此，那现下这状况正如他所愿。

『亚人族的怒火不会消失。不知道有没有方法可以停止战争。』

「我会杀到敌人灭亡。就算这样讲……但太不切实际。假如有可能的话，应该会是更极端的答案吧。」

『极端？』

「足以熄灭憎恨之炎、浇熄怒火的可能性。」

真是不著边际的话。假如有那种可能性，这场「亚人战争」就会成了大闹剧。

不过，真的需要那股力量。

——要打碎巴尔加留下的遗念以及亚人族的憎恨，就必须有个凌驾其上的压倒性存在。

「要是有的话……我想想，该叫什么好呢。」

「————」

威尔海姆喃喃自语，格林也沈默思索。接著他像是想到了什么似地，缓缓地在纸上写字，然后给威尔海姆看。

『英雄。』

格林只写了一个单字，威尔海姆看了点头。

——英雄。没错，就是英雄。

不是文字游戏，而是会被后世传颂的真正英雄。

被称为「剑鬼」的威尔海姆，和被盛赞为战鬼团体的卓格夫队，还有以勇猛无比为人所知的近卫骑士团。要有一个力量甚至超越他们的英雄。

就像过去曾让笼罩全世界的恐惧落幕的「剑圣」——

假如这场战争要迎向终点，恐怕只能巴望这种可能了吧。

4

「嗨——哟。回来得真～晚。」

「————」

返回兵营，一进自己房间，姿态优雅坐在床上的女人——罗兹瓦尔就出声迎接。

默默地瞪向那张毫无恶意的脸孔，反而使她更加愉悦地微笑。

「在练兵场挥汗，对异性发泄昂扬的火热……感觉怎样？」

「几乎都要习惯自己的房间被人闯空门了，感觉很讨厌。营房长在干什么，怎么那么没有管理员的自觉啊？」

「以前是提心吊胆地顾虑，现在则像亲人一样照料……不——是这样的感觉吗？」

「多管闲事……」

想起在营房入口擦身而过时，身材微胖的营房长对自己敬礼。自己和卓格夫队的人、其他卫兵以及营房长的关系都急遽改善，却也因此有不好的影响。

像是来访的客人直接进他寝室，害得他都没有休息时间。

「所以？刻意跑来有什么事？」

「女人半夜三更强忍害羞跑进心上人的房间，只会有一——个理由吧。请不要太粗鲁……好啦好啦，别生气别生气。」

瞪过来的视线开始带著剑气，罗兹瓦尔立刻消除营造的情色气息，接著不开心地吐气，用异色瞳凝视威尔海姆。

「人家都这样表达好意了，你还守得这——么紧。人家都丧失女人的自信了。」

「假如你的好意是真的，那我也会正经回应……不过不是的话就用不著客气。」

「——嗯。」

对此闭上一只眼睛的罗兹瓦尔陷入思索。斜瞄她一眼，威尔海姆开始准备擦汗。跟格林分开后，又到练兵场练剑流了满身汗。但他好歹有女性在场不方便更衣的顾虑。

「那么，就谈谈真正的好意吧。——可惜的是并非男女之情，而是作为一介友人的好意就是了。」

声音的气氛突然改变，威尔海姆回头。罗兹瓦尔姿势不变仰视著他，但态度却已丕变。那是在战地上勘查与史芬克丝相关的魔法阵时所表现出的真切态度。

——亦即，罗兹瓦尔是表明自己内心的状态。

「多亏你和你的朋友们，我才能达成我的目的。因此你可以把我接下来要说的话，当作是由衷感激。」

「……继续。」

「——内战的战火即将延烧到你的老家托利亚斯领。」

「什……！？」

以出乎意料的方式空降的字眼，让威尔海姆目瞪口呆。罗兹瓦尔就在惊愕不已的他面前交叠修长双腿，满脸认真地点头。

「我在各处都有认识的人，所以这方面的消息很灵通，又都是第一手。我想等消息传到你这儿的时候可能已经太迟，所以便亲自跑这一——趟了。」

「你为什么那么……而且，那边是……」

「当然，攻击托利亚斯领毫无战略价值。不论是对领主还是对王国军来说，听到这消息都是晴天霹雳。可——是，那种理论不适用于现在的亚人族。你懂吧？」

巴尔加留下的恨意，被那仇恨之火焚烧的亚人族已经顾不得那么多，也不知停损点。就算这样的行径毫无意义，也阻止不了内战之火的延烧。

「也有可能是为了报复杀了亚人族主将的你。——威尔海姆·托利亚斯。」

「——！」

只要做出伤害他人的行为，就会诞生报复的理由。内战的开头以及续战的理由都是如此，而且威尔海姆无从否认。

「有可能的话，找上头商量看看吧。波尔德殿下应该不会那么——坏心。虽说可能会花上一些时间。」

觉得事情办完的罗兹瓦尔站起来，穿过呆若木鸡的威尔海姆身旁，走向房间出口。

「……结果，你有何打算，是基于什么样的立场？」

威尔海姆立刻朝她的背影这么问。罗兹瓦尔停下脚步。

「不值一提。能让我有好感的人很稀少。正因如此，那些少数让我有好感的人要是能幸福就好了。——我是这么想的。」

头也不回，没让人看到表情的罗兹瓦尔这么断言。了解到这段话的重量，威尔海姆屏息。而她突然耸肩然后转过头，微微一笑。

「要怎么做，由你判断。不要让自己后悔喔。」

仅留下这句话，罗兹瓦尔·J·梅札斯就离开了房间。

呆立原地目送她，好半晌后威尔海姆才回过神来。然后急匆匆地抓起刚脱掉的上衣，冲出房间去找波尔德。

——廊上已经看不见罗兹瓦尔的身影。

5

『我先去确认事实关连。视状况而定，会召集队伍出动，先惦记这点。——不要太性急喔，威尔海姆。』

罗兹瓦尔亲自告知逼近托利亚斯领的动乱——听了威尔海姆的陈述，波尔德以异常认真的态度点头，说完这句话后就前往大本营。

目送背影离去，自己能做的只剩下等待报告。尽管痛恨自己的窝囊，但现在却有自制力可以忍受这份无可奈何的煎熬。

别在左胸上象征骑士身份的徽章，不容许自己像以前那样自作主张。这是自觉的证明。

『我重复一遍，不要性急。好不容易才被授勋，不要做出会被剥夺身份的举动，你已经是有地位的人，不再是无牵无挂的一介剑士。』

夕阳西沈，夜幕笼罩王都。站在大马路上，不断回想波尔德的话。

没法乖乖地等在自己房间，在这段只能等待的时间里，威尔海姆的双脚就像被邀请一样慢慢地走向贫民窟广场。

和特蕾希雅交谈，像平常一样分开后过了数小时。威尔海姆也是首度在一天之内前往那个地方两次。

「——威尔海姆？」

在已经变暗的广场里看到红发少女仍旧待在那儿，不禁惊讶。

跟大马路不同，要走小巷才能到的广场并没有人工照明。偏偏今天晚上又有云朵遮蔽，因此昏暗到连手边都看不清楚。

在这种地方，特蕾希雅应该也看不见花海了，但她却独自留在这里。

「……怎么了吗？好恐怖的脸。」

凝视愕然失声的威尔海姆，特蕾希雅眨眨蓝色双眸。

「都这么晚了，一个女人家在这种地方干什么？」

「这种说话方式简直……啊！」

口气不好地回应迟钝的特蕾希雅，结果她像是想到什么而击掌。

「嗯嗯……。——是很想把这句话原封不动还给你，不过那样讲有点太坏心了。毕竟你生著一张不喜欢人开玩笑的脸。」

「————」

不知她在演哪出，觉得奇怪的威尔海姆在探索原因的时候想到了答案，当然也知道了她的想法。

这段对话就跟两人第一次邂逅时一样。

「————」

老实说，现在的威尔海姆没有心情陪特蕾希雅玩这种小游戏。可是看到她等待自己有所反应的纯真目光，就让人冷静了下来。

自然而然地去回想邂逅当初，自己的恶行恶样。

「这一带很多不法份子，一个女人家闲逛很危险。」

「唉呀，你在担心我吗？」

「我也有可能是那些不法之徒喔。」

「用不著担心啦。因为你是王城的骑士先生，所以不是坏人，对吧？」

特蕾希雅指著他胸前的徽章，只修改当初对话最后的部分，然后微笑。对此苦笑的威尔海姆走到她身旁。

她的服装跟白天一模一样，坐著的位置也是。这样看来——

「你一直待在这？」

「……嗯。待得有点久了。」

说了很少见的话的她吐吐舌头，不过她讲的八成是谎言。

是不知道她跟自己分开后都在做什么，不过之前一定也是待在这里直到天黑。

「我不想重复一遍，但……都这么晚了，一个女人家闲逛很危险。」

「谢谢你担心我。不过，现在才讲太慢啦。而且我不是一个人，所以不用担心。会有人来接我的。」

「————」

「对方是女生，有松了一口气吗？」

「……我又没在怀疑那个。」

什么松一口气，想太多了。而且，来接人的是女性这点，并没有减少晚上走在路上的危险。

「放心啦。她是很强的女剑士，比我还强喔。」

「跟你比的话，绝大部分的剑士都很强吧。」

毕竟她是跟武力无缘的少女，怎能跟那些人比。话虽如此，威尔海姆和特蕾希雅相遇已经将近一年，这段期间若有人担任她的护卫，应该是身手了得吧。

护卫——既然身旁会有这种人，那特蕾希雅的身份也不难想象。

「你不回去，是因为不想待在家里吗？」

「怎、怎么突然就问了这么难以启齿的问题，你是这样的人吗？」

「工作习惯，所以讲话都一针见血。所以，答案呢？」

「……可以说是，也可以说不是。对不起，我很难回答。」

道歉的特蕾希雅目光凝视远方，掠过眼眸深处的感情脆弱无比，威尔海姆责备自己神经大条。

哪有女孩子毫无理由会晚上不回家在外头走动的。

「威尔海姆呢？」

因此，慢了半拍才察觉到她这么问的意图。

坐在花海前面的废建材上，抱著膝盖的特蕾希雅仰望威尔海姆。

「我可以问……关于你原生家庭和家人的事吗？」

「我家的事……」

「对。嗯——因为，不是没有关系……吧？」

看特蕾希雅笑得害臊，若是平常的话，自己可能会说些什么，但现在提到家人却让威尔海姆犹豫该说什么。

毕竟，自己的老家托利亚斯家可能遭遇危险。

「……我是不是问了不该问的事？」

看到威尔海姆欲言又止，特蕾希雅的表情顿时转为发愁。

太不成熟了，忍不住在心中这么咒骂自己。就算让特蕾希雅知道自己的现状，也只是给她增添不必要的负担。为什么自己不能维持平常的扑克脸呢？

威尔海姆懊恼地垂下脸。结果，面前的特蕾希雅站起来，然后双手伸向表情无精打采的威尔海姆。

「振作起来，你是男人吧！」

「——！？」

脸颊被她的手用力拍打，这招出其不意令威尔海姆目瞪口呆。才因干巴巴的冲击而瞪大眼睛，特蕾希雅便双手插腰挺起胸膛。

「我知道事情很复杂，但这样就垂头丧气的话太不像你了。你要像平常那样……毫无理由地威风凛凛才好。像个小孩子一样挥剑，毫无根据自信满满……这样才好。」

「————」

好过份的评价！没想到自己是被这样看待。威尔海姆先是傻眼，然后不高兴起来。

看到他不高兴，特蕾希雅这才觉得自己的发言不妥当。连忙说：「啊，不是啦，怎么说呢。」这样的变化让威尔海姆垂下肩膀。

然后叹气，紧接著露出笑容。不是苦笑，而是发自内心的笑容。

「你果然是个奇怪的女生。」

「什、什么？为什么这样讲？虽然感觉似乎前后不一，但我自认为说了很棒的话喔。」

「少自夸了。——不过，我不否认。」

回答完不服气的特蕾希雅后，威尔海姆再度深深吐气。

不是因为忧虑，而是吐出郁积在胸口中的所有感情。

「像个小孩子一样挥剑……是吗。」

拿著剑挥来挥去的小孩子，光想就觉得危险得不得了。这种表达方式很好笑。

但是，却没有错。威尔海姆就是挥剑的小孩子。内心还是小孩，就只有身体随著时间过去而长大，不知不觉便忘了那时候的事。

可是现在，他想起了还是个幼童的自己开始挥剑时，当时的志气。

「我送你到贫民窟的出口。在明亮的大马路上等人来接你吧。」

「……平常不这样今天却这样，可能反而会害她找不到我喔？」

「那不然，要留你一个人在黑暗中吗。我可不会这么做。」

「这倒是啦。那没办法，就当个能让男人表现的女生吧。喏。」

自信满满地说完，特蕾希雅伸出手。牵起她的手让她站起来后，两人不知为何就这样牵著手走向贫民窟出口。

威尔海姆感觉到对方的手指所传来的热度，让自己的心跳加速。

「我在这边等。在这的话，应该就不会找不到我了。」

走过好几条窄巷，到了大马路附近的街灯下后，特蕾希雅停下脚步。说老实话很想把她带到大马路上，但她可能不想让自己跟接送的人相遇吧。

「一个女人家站在晚上的巷子里，不要被误会是卖花女喔。」

「我看起来才不像咧。……而且一开始叫我花女的可是你。」

「意思就是脑袋只有花，又不是卖花女的意思。」

「那样子也很过份啦！」

被红著脸的特蕾希雅猛拍肩膀，威尔海姆松开握著的手拉开距离。手指还有点留恋温度，他凝视著拋去女人味的她。

然后，触碰左胸的徽章，向她道别。

「可要小心夜路喔，花女。」

「你才是，跷班也该适可而止，不良士兵。」

互相说对方坏话，却又马上笑出来。然后——

「拜啦，特蕾希雅。」

「下次见，威尔海姆。」

就这样，像平常那样告别后，威尔海姆背对特蕾希雅。

边感受被她目送边走向大马路，几度确认她远离之后，就拔下别在左胸的徽章。

身为骑士的证明，现在的自己被认可的证据，让自己可以抬头挺胸见特蕾希雅的功绩。

拥有这一切意义的物品，在威尔海姆的掌中闪动黯淡光芒。

——但却根本比不上幼时反射日光的宝剑光芒。

「那个大笨蛋——！！」

隔天，来到威尔海姆个人房的波尔德放声怒吼。

被他的拳头用力敲击的桌子碎裂开来，原本随意装饰著的勋章散落一地。这已经算是充分的问题行为了，但光这么做还没法平息波尔德的愤怒。

「————」

站在气到发狂的波尔德身旁、默不作声的格林伸向被破坏的桌子残骸，然后从里头捡起以龙为意象的徽章——骑士的证明。

放在桌上的徽章，还有跟徽章一起被留下的纸条，上头只有一句话。

『抱歉。』

简单又没有修饰，很像剑鬼会留下的、脑袋不好的内容。

脱去骑士证明，只带著爱剑的威尔海姆·托利亚斯离开王都。

那是脑袋不好的他——剑鬼的答案。

6

放弃骑士证明，对威尔海姆来说需要很大的决心。

徽章是自己这个人被王国这泱泱大国所认可的证据。原本被骂是个坏小孩的自己，终于获得毋庸置疑的肯定的证据。

敲开王国军的门户，一个劲地挥剑到今天。

在深信只要有剑就好的那些日子里，有很多人给了自己许多东西。

有些是敌人，有些是同伴。朋友，好对手，队员，上司，仇敌，还有——

「——特蕾希雅。」

能自觉到这些想法，都多亏了她。念著她的名字，威尔海姆触碰爱剑。

留下徽章，意味著远离至今在王都得到的一切。

并不是因为那些东西毫无价值。而是因为深信有价值，却因为背负著徽章而无法有所行动，所以才会在知道那是无可替换的情况下放手的。

依恋，愧疚，后悔，愤怒。感情就像浑浊的泥沼一样。

根本不可能维持单一又纯粹的生活方式。一心期望能够成为剑的日子简直就像骗人的。

只不过现在，并不觉得那是坏事。

「————」

等一切都解决完，也没法一脸若无其事地回归到原本的日常生活了吧。自己已经安于现状很久，到了会有美好梦想的程度。

不要犯什么大过然后消灭包围故乡的战火，卸除骑士名誉之事不被追究，牵起特蕾希雅的手向托利亚斯家族的人介绍她。真的是想得太美好的未来。

——这个对现实视而不见的梦想，在故乡被暴动给燃烧的光景下粉碎。

「哦！哦哦哦哦哦哦——！！」

回到面目全非的故乡，剑鬼挥舞爱剑，开始孤军奋战。

7

『哥哥你根本就不懂我的心情！』

大吵一架后离家出走，这种常见戏码就发生在五年前的托利亚斯家。

托利亚斯家是拥有露格尼卡王国北部一块小领地的没落贵族，过去贵为武士名门的荣耀变得稀薄，威尔海姆就是这个家庭中的三男。

上面的两个哥哥都具备了充分的继承人素质，因此威尔海姆跟继承家业无缘，度过了十分自由的幼年期。而在奔放的日子里，与领主工作无缘的少年被装饰在大厅的一把宝剑给吸引。

那是标榜托利亚斯家曾以武术之家享受荣誉的仅存物品。

回过神时，威尔海姆已经为剑著迷，每天从早到晚埋头锻炼。一开始微笑看著他这么做的家人，在他持续六年还如此之后已笑不出来。长兄对仿佛被附身般醉心练剑的幺弟说教的光景，成了司空见惯的事。

而反驳成了顶撞，演变成争吵，最后冲出口的就是开头那句话。

结果，离家出走到了王都的威尔海姆，成了王国军的「剑鬼」。

那是没法对特蕾希雅和其他人说出口、威尔海姆丢人现眼的人生起头。

——怀念的托利亚斯领，已经在亚人族的猛攻下被大火吞噬。

熟悉的景色一片火红，住了十几年的宅邸早已被烧毁。不知是否对来犯的敌人无法作出任何抵抗，处处徒留被蹂躏的痕迹。

这是当然。两个哥哥都是温厚老实人，作梦也没想过要战斗。他们是用战斗以外的方法来拼命守护家园。

正因如此，为了弥补哥哥不足的部分，自己才会埋首练剑。

明明现在的自己，应该有这样的力量。

「唔唔唔哦哦哦——！！」

剑风狂扫，亚人的血雾将托利亚斯领染得更加殷红。

践踏完人族微弱抵抗的亚人族，被一名剑鬼咬破侧腹，割掉仰首的脖子，斩断意图抵抗的手脚，贯穿发出憎恨声的喉咙。

身上溅满血花，扯破喉咙吶喊，不断挥舞挥过几亿遍的宝剑。

「是剑鬼——！是杀了巴尔加和利布雷的剑鬼！」

威尔海姆尽情施暴。察觉到他的身份后，亚人族一窝蜂拥上来。视野左右全都是亚人，宛如巨浪的恨意从正面袭来。

一开始的优势持续不了多久。原本因剑鬼出现而动摇的亚人联军，在发现敌人只有威尔海姆一人之后，就利用人海战术企图击溃他。

敌众我寡、势单力薄下，伤口不断增加。纵使十剑夺取十条性命，敌人也用百条性命来换取对他的一次伤害。自然而然的，孤立无援的威尔海姆陷入劣势。

「————」

四周被敌人包围，前后左右的杀意全都冲著自己来。

具有突破力的大块头不在，默默守护背后的盾兵也不在，更没有可以构筑战线的同伴。

一个人。过去战斗时曾以为自己一个人就够，但其实自己从未落单。直到现在他才痛切了解到这点。

「呃啊——！」

背后吃了一记。转身用突刺破坏掉偷袭的人的心脏。一停下脚步，针对自己的攻击就逼近，想要躲开，脚却扭到了。以不自然的姿势防御住攻击，导致全身骨头都在吱嘎作响。咬牙忍住，银色闪光狂舞，一群亚人被弹飞。

但是，难看不像样的破敌行进也就到此为止。身上除了惊人的溅血，还有自己的伤口流出的血，失血量即将超出极限。膝盖一软，当场倒卧在地。

「呼！呼！呼——唔——！」

呼吸急促，战意勃发，可是手脚却没法响应斗志。

被淹没在亲手杀死的敌人尸堆里，终于连爱剑都滑离威尔海姆的手中。在战场上松开剑， 是绝对不能犯的丑态。

剑鬼一旦放掉剑，就不再是鬼，只是个人——不，是连人都称不上的残骸。

最初的愿望让自己沈浸在剑中，甚至被称之为剑鬼，但连初心都忘记，什么也没想、就只是一路奔驰的男人，会有这样的末路或许也是理所当然。

结果，自己是为了什么而握剑，又留下了什么呢？

什么都没有。就只是空无一物的空虚肉块。

——真的什么都没有吗？

「剑鬼，可怕的高手……但你的命运在此结束了！」

大个子亚人站到旁边，准备朝半死不活的人类的脖子砍下去。

真正的「死亡」就在眼前，威尔海姆的心在感情下沸腾。

「————」

浮现脑海的无数影像，是与威尔海姆的人生交错的众人。

双亲，两名哥哥，领民，王国军战友，格林，波尔德，罗兹瓦尔，卡萝，最后是背对花海朝自己微笑的特蕾希雅。

下次见。道别时，她的脸和声音都烙印在眼皮、甚至灵魂上，没有离开。

——理应什么都没有的日子里萌生了光芒，和幼时所见的宝剑光芒相重叠。

祈愿成为剑，被众多邂逅给烧热，被堆叠的羁绊给锤打，最终成为了人。

不管是身为钢铁还是身为人的日子，都还有许多留恋以及遗恨。

「我……不想死……」

因此，当死亡真正降临，威尔海姆道出的是对活下去的执著。

夺去那么多的人命，原先是那样吶喊著自己临终时要利落干脆，但死亡真正降临的这瞬间，威尔海姆的心因畏惧死亡而战栗。

因为找到了活著的乐趣，如今，迎向终末的恐怖让他的心产生了裂痕。

「————」

但他那沙哑的最后遗言，被他砍死许多同伴的敌兵可不允许。

毫不留情挥下的大剑确实斩断剑鬼的性命——

——这时，迸发的斩击之美让自己这辈子永生不忘。

原本要给威尔海姆最后一击的大个子亚人，脖子被明快地割断。

伤口的断面太锐利平整，甚至没能意识到自己被砍。滚落的亚人头颅，表情也丝毫没有发现自己死了。

将死之际的威尔海姆，被头上发生的现象给夺去目光。

正因为目光整个被吸引，所以对之后发生的事也毫无反应，完全停止思考。

——剑风呼啸，无数银色闪光狂舞，亚人的性命被接连葬送。

有新的「人物」参战，错愕传遍亚人联军。但这不构成任何问题。为什么呢？因为知道「人物」的存在，跟剑光抵达几乎是同时发生。

亦即，亚人是透过死亡来得知有某个「人物」的存在。

「————」

剑舞，真的就像在跳舞，「人物」重复斩击，量产死亡。

淋漓尽致的剑击让威尔海姆以为是死神出现了。是准确收割对手性命，让当事人甚至不知道自己已死，美丽优雅的死神。

——死神绑在后脑勺的红发跃动，白色长剑就像手脚一样灵活。

「红发……？」

仿佛在保护跪趴在地的威尔海姆，死神将他周围的亚人砍光，了结性命。

每一道斩击，每当那身影掠过视野，就搅乱威尔海姆的心。

014

因为，现在在那边的人是——

「——威尔海姆！你这个大白痴！找到你了！」

听到粗野声音的同时，肩膀被粗暴地抓住，然后整个人被拉起。惊愕的视野里闯进波尔德和格林的脸孔。他们的身后还跟著卓格夫队，所有人都溅满血、样子惨不忍睹。

「本来想说就算是你也难逃一死！有没有学乖！你这个大白痴！笨蛋！」

「——！」

波尔德扯开嗓门痛骂，格林也嘴角扭曲像是想说什么。但是他们都没有追击满身疮痍的威尔海姆。找到重伤的威尔海姆后，他们立刻为了撤退做出确保退路的指示。不过——

「住、住手……现在哪能离开！我！不是躺著的时候！」

挥开抓住自己的手，想要踏进拓展开来的剑戟之宴。可是脚却在踏进之前停下来了，然后痛苦地咬牙切齿。

自己有自觉。身为剑士最基本的骄傲止住了他的脚步。

「————」

奔驰的银闪，美丽的剑闪，完成度超越所有人的一闪，那就是死神的剑技。

可以断言。为剑道而活、奉献许多时间给剑的威尔海姆可以断言。

——那样的剑之领域，自己这辈子永远都到不了。那是具备资格的人方能抵达的境界。

唯有真正为剑所爱之人，才能抵达以剑为名的钢铁顶峰。

「——！」

这次，身体确实被格林粗鲁地扛起。威尔海姆连抵抗的力气都没有，体力也耗尽，连意识都快要消失。

即使如此，只要是容许的情况下，只要心灵还能够承受，他想看那剑舞看到最后。

「——大人……！」

仔细一看，竟然连卡萝也在现场。仿佛像在看守死神的战场，她手贴胸膛，表露出担心强悍死神的态度。

傻住，愕然。卡萝的双眼到底在看什么？那个死神哪里看起来要人担心了？

——同为剑士的你，会不知道那剑技有多骇人吗？

只是一挥就让人看到同为剑士的等级落差，那个人物的存在高到让人绝望。

「那个、死神是……」

「死神？别说笑了，那是王国的王牌。是让我们望尘莫及，真正的王国之剑。——『剑圣』。」

远离战场，连意识都模糊不清，在昏厥前最后听到的单字。

「剑圣」。这本身就是赋予露格尼卡王国历史上的活传说的称号。

但是，那个称号根本就不适合她——

「————」

现在的威尔海姆不但无法传达这点，连要叫喊都没办法。

8

——托利亚斯领的战役在后来的露格尼卡史记上被大书一笔。

这场战役的舞台托利亚斯领本身并没有价值。其惨状仅被当作「亚人战争」中常见的悲剧之一。

这场战役跟其他悲剧只有一点不同。

它是当代「剑圣」华丽的初征战场。

当代「剑圣」在这场战役之前，从未出现在世人面前。因此有人质疑其存在，更有人怀疑「剑圣加持」是否光华不再。

可是，被世人担忧的「剑圣」实力，在这场战争中获得证明。

初征，仅仅一人，结束上千的亚人性命。这除了剑圣以外无人能办到。

「亚人战争」陷入泥沼迷雾状态，而能够将之结束的救世主终于登场。每个人都相信这种论调，每个人都高声赞美新的「剑圣」之名。

为了守护托利亚斯领，舍弃骑士身份回归一介剑士，孤军奋战打倒三百名亚人的「剑鬼」，他的名字和功绩都被悄悄埋没。

但是，「剑鬼」本人根本不在意那种事。

他不拘泥纪录和勋章。曾让他拘泥的理由他早已放手。

所以对威尔海姆·托利亚斯来说，重要的是——那个广场的花海。

战伤痊愈，终于可以到广场了。但那已是几个礼拜后的事。

一手拿著屡次在激战中被过度使用而残破变形的爱剑，走在习惯的路线上。漫步在这条路上时，威尔海姆的心头总是被各种情感给充塞。

有喜悦，有期待，有忧郁，有不安，有著急，有羡慕。

——而现在，充斥威尔海姆心中的感情跟以往的任何情绪都不同——

她应该在。直觉这样告知。威尔海姆相信自己的直觉。每次去广场幽会，她是否等在那里，自己都有信心能猜中。

但这股直觉是以何为要因而运作，现在去追究已毫无意义。

抵达广场，屏气凝神。用不著探寻，她的存在感就很强烈。

就在广场的既定位置，坐在每次坐著的废建材上，视线望著季节已过的花海。

不是用走近这种窝囊的方式，而是急驰且中途不出声地拔剑。剑在速度感中往下劈，迅雷不及掩耳的斩击会将她的头剖成两半，但是——

「真屈辱。」

「……是吗。」

真心话脱口而出，简短又有力。

威尔海姆的全力一击，被两根手指给夹住。

对方连头都没回。耗费在剑上的所有岁月，都被压倒性的剑术才能给否定。

「你一直在笑我吧？」

「————」

没有回答。明明沈默才最伤威尔海姆的心。

明明就连现在，都没法从那纤细柔弱的身体感受到一丝习武之人的气息。

「回答我啊，特蕾希雅……不对，『剑圣』特蕾希雅·范·阿斯特雷亚！！」

用力夺回剑，狂吼的威尔海姆再度砍过去。但是却被她以轻盈到连头发都没乱的动作避开。目光追随舞动的红发，紧接著脚被一绊，整个人随之倒地。

为人所惧的剑鬼威尔海姆连受身都来不及，实在凄惨无比。

被重复幽会，互相调侃对方，不为人知地加深羁绊的那名少女给绊倒在地。

俯视倒地的威尔海姆，特蕾希雅的蓝色双眸逐渐变得透彻。映照澄澈天空的蓝，慢慢转为不允许云朵存在的孤独蔚蓝。

「哦、哦哦哦哦哦——！」

像是要紧追远去的背影似的，威尔海姆跳起来再度开始攻击。

热心追击的剑击，精湛到让人忘了他曾满身是伤被逼到绝境。打倒巴尔加，与利布雷对峙，让剑鬼之名广为人知的无数战斗。现在的剑气却更胜上述过往。

被洗炼和研磨的剑技，连过往的自己都给爽快割舍。

在没有别人、仅有彼此的秘密之地，「剑鬼」倾吐自身所有的剑力。毫无疑问的，这是威尔海姆的人生中所展露的最顶级剑术。

但每一招，都被连剑都没拿的特蕾希雅像玩游戏一样轻易躲过。像在儿戏又像在跳舞，事实上，就是有这等差距横亘在两人之间。

无可奈何的墙壁，无计可施的差距，无法跨越的距离。足以被称之为隔阂。

彼此的隔阂清晰地挡在中间。

「我不会再来这里了。」

俯视被自己打倒的威尔海姆，特蕾希雅平静地宣告别离。

她的手上不知何时已握著威尔海姆的爱剑。剑鬼被剑圣夺去爱剑，还被剑柄而非剑刃难看地殴打，到了连一步都动不了的地步。

好远。还有好弱。碰不到。远远不够。

——所以才会让特蕾希雅有那种表情。

「露出那种表情……别给我用那种脸握剑啊……」

恬不知耻也该有个限度。也不想想是因为谁的无力，才让她露出那种表情的。

要是自己更强，更有剑术天分的话，就可以不让她有那种表情了。

「因为我是剑圣。我本来不了解握剑的理由，但后来了解了。」

那是特蕾希雅难解的、向威尔海姆寻求的「某种东西」的暗号。因为她想问却又无法老实问出口，心里有著这幽微的一部分。

「什么理由……！」

「为了守护某个人而挥剑。我认为那很不错。」

约定俗成的对话，不知不觉间已经没有必要确认的问答题。

——喜欢看花，找不到挥剑意义的「剑圣」。

给予特蕾希雅·范·阿斯特雷亚挥剑的理由，是威尔海姆的原罪。

正因为是比任何人都强大，剑技无人能及的她，故益发如此。

「你，给我等著。特蕾希雅……」

特蕾希雅说完要说的话就径自离去，威尔海姆只能朝她大喊。

手脚不能动，连脸都抬不起来。但是，以对特蕾希雅的心情和对自己的愤怒为原动力抬起下巴，拼命地用和她一样湛蓝的双眼盯著头也不回的背影看。

脚步没有停留，特蕾希雅的背影远去。声音将无法传达。在那之前——

「我会从你那抢走剑的。谁管你被给予的加持还职责。不要瞧不起挥剑——不准看轻剑刃、钢铁之美，剑圣……！」

背影远离，不久就看不到了。最后的痛骂有传到她那儿吗？

应该有。应该有传给她。

阐述钢铁如何为剑的剑鬼，对为剑所爱的剑圣作出的，悲哀凄惨的宣战布告。

——在那之后，两人再也没在那儿相遇。

「剑鬼」威尔海姆·托利亚斯在那之后就从王国军销声匿迹。

取代他的，是在王国军中以「剑圣」名闻遐迩的特蕾希雅·范·阿斯特雷亚。

一夫当关，万夫莫敌——仿佛体现这句话的她大为活跃，让原本以为没有终点的「亚人战争」形势逐渐一面倒。

用压倒性的力量，让巴尔加·克罗姆威尔所留下的憎恨火焰以及绝不会消失的战争循环臣服——就是这种英雄故事的其中一个答案。

「剑圣」的威名分别成了人族的希望、亚人族的绝望。

而时间流逝，战火被一扫而空的时候，这个故事也终于迎向结局。

「亚人战争」的终结，和剑鬼与剑圣的最后幽会——「剑鬼恋歌」将被传唱。

** 幕间

1

卡萝·雷玫迪斯第一次遇到特蕾希雅，是在十四岁的时候。

雷玫迪斯家代代都侍奉会诞生「剑圣」的阿斯特雷亚家。卡萝也是自懂事起就亲近剑，遵从家规磨练使命感和技术。

当「剑圣」弗莱巴尔·范·阿斯特雷亚的「剑圣加持」被下一任继任者承袭时，当时的卡萝就被赋予了随侍在对方身侧的职责。

执行职务的第一天，卡萝到现在都记得自己紧张到快晕倒。

这也难怪。除了她以外，雷玫迪斯家有许多优秀剑士。当然，卡萝的剑术跟同年代的人相比是很优秀，但如果单纯重视能够担任剑圣侍从的实力的话，应该还有其他适合的候补人选。

明明如此，不成熟的自己却还被选上，使得卡萝内心很混乱。

「你就是从今天开始要跟著我的女生？」

所以说，被引见的对象是年纪比自己小的少女时，说实在话她感到很扫兴。

「是、是的！我是雷玫迪斯家的卡萝·雷玫迪斯！虽然还是个不成熟的剑士，但为了特蕾希雅·阿斯特雷亚大人会不惜粉身碎骨……」

「……用不著那么紧张没关系啦。我可以叫你卡萝吗？」

面对紧张到浑身僵硬的卡萝，特蕾希雅为了让她安心而这么说，然后朝她微笑。

她的笑脸和态度让人安心，但反而让卡萝产生不信任感。因为不相信眼前这名少女就是当代「剑圣」，继承了被讴歌为传说的加持。

——这个女孩真的是剑术遥遥凌驾自己的高手吗？

钻研剑的时间也不算短，卡萝也有身为剑士的自负。每天接受锻炼的日子，让她没法不去怀疑「剑圣」的实力。

事实上，特蕾希雅不论是态度还是举止，都丝毫没有剑士和习武之人的色彩。

因此，即使被人告知她继承了最强的「剑圣加持」，自己也没法轻易点头同意。

「特蕾希雅大人，方便的话，能否露一手当作指导我的剑术呢？」

卡萝忆起当时的自己说出了万分的话。

尽管卡萝隐藏起自己的狐疑，但特蕾希雅一定看穿了自己真正的想法。她手贴嘴唇一脸思索，最后凝视卡萝，说：

「……对不起。这不太方便，所以没法配合。」

她爽快地婉拒卡萝的要求。

因为有这样的经历，因此卡萝对特蕾希雅的印象并不好。

当然，她不会因为这种理由而放弃职责。卡萝十分认真，特蕾希雅也从未抱怨过她工作的态度。

两人之间的距离产生变化——是因为发生某件事，改变了卡萝对特蕾希雅的看法。

那是在卡萝和特蕾希雅表面上维持良好主从关系约两个月后的事。

当时，特蕾希雅大多都待在家里过一整天，看起来欠缺身为「剑圣」的自觉。卡萝对此大为不满。而且每次要求她进行剑术指导都被拒绝。这样的互动或许也是累积不满的理由之一。

「特蕾希雅大人是否真的有剑圣资格，就来试她一试。」

如今回想起来，那真是愚昧的念头。可是那时候的卡萝却觉得是妙招。

——假如特蕾希雅大人在剑圣的素质上不够高，自己就得好好锻炼她才行。

要说这个错误的使命感推了卡萝一把也不为过。结果，卡萝决定佯装意外来测试特蕾希雅的剑术。没有打算要让她受伤，也没编织绵密的计划，就只是小小的测试而已。

然后，结果是——

「——卡萝！卡萝！没事吧？有、有没有……有没有受伤！？」

呈大字形躺在地毯上的卡萝听到特蕾希雅在拼命呼喊。

发生什么事了？感觉天旋地转，分不清楚上下。为了要测试特蕾希雅，所以佯装意外一口气接近她身后——接著意识就中断了。

「特蕾希雅…大人？」

「——啊！你、你要不要紧？没、没受伤吧？太好……太好了……」

看著傻楞楞的卡萝，特蕾希雅哽咽。担忧的声音没能再发出语言，以手掩面的特蕾希雅开始落泪。

明明做了坏事让她难过的人是卡萝才对。

「对不起……对不起，卡萝……！」

看到特蕾希雅抽泣，卡萝清楚意识到。

愚蠢的自己做出的轻率行动伤害了她。

卡萝知道特蕾希雅的「加持」，是在那之后的事。

前代剑圣弗莱巴尔是特蕾希雅的叔叔，有次卡萝有机会和他交谈，除了被嘱咐要好好照顾特蕾希雅之外，还从中得知特蕾希雅与生俱来的加持。

「特蕾希雅一出生就有『死神加持』。」

跟承继而来的「剑圣加持」不同，特蕾希雅与生俱来的「死神加持」能力，是只要被特蕾希雅弄出伤口，就绝对不会愈合痊愈的杀戮之能。

拥有两个加持，简直是被战斗所爱的特蕾希雅，让卡萝震颤。同时理解到把卡萝扔出去后哭哭啼啼的特蕾希雅，那泪水的意义。

「————」

察觉到自己做了无可挽回的轻率之举，卡萝十分后悔。

都走到特蕾希雅的房门前了，却因自省和悔悟而没法踏出一步。只确定自己做出了侍从不该有的行为，一定会被解除职务吧。

「上次真的很抱歉。或许你不能原谅我，可是我是真的觉得很抱歉。」

但那股确信，却在特蕾希雅一看到卡萝就低头认错的态度下粉碎。

明明该道歉的是自己，特蕾希雅却一脸灰心沮丧。她畏畏缩缩地以由下往上的视线，凝视呆立原地的卡萝。

接触到特蕾希雅的善良温柔，卡萝为自己感到羞耻。

羞耻愧疚后，卡萝变了。

「特蕾希雅大人，入浴的准备已经好了。一起过去吧。」

「卡萝……你是不是变温柔了？」

「哪里——还远远不及特蕾希雅大人。」

在那之后，卡萝就发自内心视特蕾希雅为主人。

她知道这个新的「剑圣」与被给予的能力相反，是位心地善良的少女。

——那就是改变卡萝·雷玫迪斯的原因。

在知道特蕾希雅的背景后，卡萝就成了善解她意的侍者。

身上拥有两个加持，只能认定她被战斗所爱——但是，特蕾希雅却是害怕伤害别人，喜爱花朵，善良温柔的少女。

一开始对她身为「剑圣」却连剑都不握的态度感到不满，可是在知道她的人品之后，卡萝认为这样就好。

为剑神所爱，但她选择了不握剑的生存方式。

不管是谁批判这样的特蕾希雅，自己都会站在她这边。那是为过去自己的愚行赎罪，以及为仰慕的特蕾希雅尽忠的方式。

要是心灵平稳的日子能就这样持续，特蕾希雅握剑的机会不会来临就好了。

可是这样的心愿却被悄悄违背。

——王国内战「亚人战争」的魔手，并不打算放过特蕾希雅。

2

「哥哥，对不起……哥哥……！」

「特蕾希雅大人——」

抱紧哭泣的特蕾希雅，卡萝拼命安慰心爱的主人，可是却又说不出什么温柔的话，只能憎恨不中用的自己。

——「剑圣」特蕾希雅的初征，对王国军而言是内战初期的败仗。

并不是特蕾希雅的力量不足，而是更根本的问题。

——特蕾希雅无法战斗。她甚至连剑都没法拿。

绑起红长发，穿上轻铠，佩上只有「剑圣」才能担负的龙剑雷伊德，拿起自己的长剑，肩负王国的期待于一身，特蕾希雅初次上战场。

准备如此周全，特蕾希雅却没法战斗。她无法去伤害人。

取而代之成了牺牲品的，是直到最后都在担心她的哥哥。他加入敢死队，保护无法动弹的特蕾希雅，最后壮烈战死。

而后，对因为不能作战而害死哥哥的特蕾希雅来说，剑成了诅咒。

「——对不起喔，卡萝。」

像这样护送一脸消沈的特蕾希雅，成了卡萝生活的一部份。

「剑圣」初征却不敢战斗的事让王国高层感到失望，他们对之后没法随军出战的特蕾希雅已不抱任何期待。

因此王国对徒具形式的剑圣的要求，都由卡萝代替特蕾希雅完成。

当然，卡萝没有自大到认为自己是特蕾希雅的替角。尽管如此，她却还是持续奉献，只希望能稍微让世俗对特蕾希雅的风评好转。

她知道，特蕾希雅若是能挥剑，绝对能制造高于自己十倍、甚至百倍的成果。

但是，希望那样的机会不会来临。卡萝这么祈求。

她由衷希望那名心地善良的少女不需要握剑——

内战开始过了多年，战乱始终没有平息的迹象，时间就这样过去。

这段期间内也发生过几次，厄运对无法作战的特蕾希雅穷追猛打。

特蕾希雅的二哥和弟弟接连战死，终于连前代剑圣弗莱巴尔也在内战中殡命。战火到处燃烧，烧灼特蕾希雅的心，把她逼到绝境。

「对不起……对不起……！」

晚上，特蕾希雅窝在自己房间里痛哭流涕的声音，卡萝听过好几遍。每次听闻哭声道歉，卡萝的内心便不禁为上苍的蛮横不讲理感到愤怒。

已经够了吧，还要多少次？为什么命运要将特蕾希雅逼到这种地步？

剑神的宠爱，不断地折磨温柔善良的少女。

谁都好，拜托救救她。卡萝发自内心祈求。

自己没办法，自己没有资格。就算被骂不要脸也无所谓，拜托那个人出现。

卡萝只能一直祈祷，希望那个人能够找到特蕾希雅。

3

——卡萝会发现特蕾希雅的细微变化，真的是很偶然的事。

内战开始已经五年，距离无法战斗的初征也已过了四年多。

这阵子，特蕾希雅不再窝在屋子里，常常一整天都在外度过。

话虽如此，她并非去到处闲逛。是卡萝劝她不要老是待在家里。原因很简单，却难以应付。

——随著内战越来越严重，唯恐「剑圣」立场雕零的阿斯特雷亚家的亲戚连日来亲自造访，想要说服特蕾希雅从军。内疚的特蕾希雅持续被他们的不负责任发言无情鞭笞。因此卡萝才劝特蕾希雅外出。

「请不要勉强自己。特蕾希雅大人只要顺从自己的内心就好。」

送怯生生的特蕾希雅出门时所说的话，是卡萝的肺腑之言。

特蕾希雅并不是逃避就会觉得轻松的个性，但卡萝还是希望避免让她累积苦恼。就算没法安稳度日，至少希望特蕾希雅能够过著没有波澜的时光。

离开宅邸的特蕾希雅，前往贫民窟的深处。虽然治安不好，却是能够一人度过的地方。她洒下的花种结出花苞，成为能带给她些许安宁的花海——本来是这样的。

「特蕾希雅大人……发生了什么事吗？」

晚上去广场接特蕾希雅的时候，平常忧愁的她那一天态度却改变了。很难得的，她轻轻笑著说：

「我遇到了万分失礼的剑。」

虽然这么说，但音调却很雀跃。卡萝不禁好奇。

不过再过不久，卡萝就知道了特蕾希雅话中的意思。

——在得知特蕾希雅在花海广场遇到的对象是威尔海姆之后。

谁都好，希望有人能救特蕾希雅。这么祈求的人确实是自己。

所以说，卡萝没有资格抱怨。但就算没有，还是想要问。

为什么是威尔海姆·托利亚斯？

在机缘巧合下，卡萝在特蕾希雅与威尔海姆相遇之前就认识了他。代替特蕾希雅出任务的卡萝，在战地上碰到过好几次的问题剑士。

威尔海姆的人性，跟善良的特蕾希雅在个性上应该合不来才对。

他不过就是披著人皮、渴望鲜血的野兽，知道怎么挥剑的生物。卡萝对剑鬼的评价就是如此。

跟厌恶伤害他人、畏惧自己强大力量的特蕾希雅刚好相反。

理应不相容的两人，却在那片花海莫名其妙地心意相通。

虽然对特蕾希雅感到抱歉，但卡萝不只一、两次偷看两人幽会。

每次监视都是做好有什么事就立刻冲出去杀人的觉悟，结果却都是大失所望——不，不能这么说。因为在花海的特蕾希雅笑得灿烂。

卡萝所认识的特蕾希雅，老早就没有微笑和笑容可言。

在即将迈入第五年的主从关系中，只有一开始的半年特蕾希雅是平稳度日。之后「亚人战争」就开始，接著初征，特蕾希雅的心碎裂而失去笑容。

——而特蕾希雅·范·阿斯特雷亚的真正表情就在那里。

既然特蕾希雅认可、相信他的话，那自己也要接受。卡萝不情不愿地这么想。

这阵子，卡萝也跟威尔海姆的战友格林熟稔起来，而他对威尔海姆的评价甚高，从而改变卡萝对剑鬼的印象。

不久，威尔海姆在内战立下大功，甚至被晋升为骑士。

那本来是「剑圣」特蕾希雅被要求的职责。引导「亚人战争」迈向终结的契机，这样的重责大任由「剑鬼」代替她完成了。

——特蕾希雅的眼光是对的。卡萝为这件事感叹。

之后，获得骑士地位的威尔海姆在思维和举止上都产生变化。

宛如负伤野兽的狰狞变得收敛，会注意周围，拼命完成自己被期许的责任。就像是保护骑士该有的风范。

这变化太过极端，但周围的人认同他的努力，卡萝也对他的变化乐见其成。尽管气愤，但只能认同。

「——威尔海姆。」

特蕾希雅与威尔海姆在广场的幽会，已不在话下。

在花海前等待威尔海姆，用愉快的面容和声音迎接他。看到特蕾希雅这样，应该没人不知道她对剑鬼怀有什么样的感情吧。

两人两情相悦、情投意合一事是毋庸置疑。

卡萝认为这样很好，所以由衷地祝福他们。不过，要说不嫉妒让特蕾希雅展露真正面容的威尔海姆是骗人的。卡萝表面上一直对他冷言冷语也是因为这样。

但是只要特蕾希雅幸福，那就都无所谓了。

特蕾希雅已经受了太多创伤。基于用不著受伤的理由，理应没有必要受到伤害的少女，却一直因被赋予不相称的命运而受伤。

所以说，希望她能幸福。希望她过得幸福。

只在那片花海展露的笑容，只对威尔海姆绽放的微笑，特蕾希雅·范·阿斯特雷亚是值得被爱的人，好想把这些传达给所有人知道。

而那个时刻不久将会来临。卡萝这么相信。

——但是，名为剑的诅咒却绝不放过特蕾希雅。

4

为了援救被战火吞噬的故乡，威尔海姆·托利亚斯孤身赶赴托利亚斯领。

从格林那儿知道事态时，理解到状况恶劣的卡萝犹豫著该下何种判断：到底该不该把这件事告诉特蕾希雅，心情在这两者之间摇摆不定。

告知了又能怎样。可是，不告诉她心上人奔赴绝望的战场的话，又等于背叛她。

犹豫迷惘后，卡萝向特蕾希雅坦承了一切。

——而那就是当代「剑圣」真正觉醒的时候。

「特蕾希雅大人……」

在被熊熊烈焰包围的托利亚斯领，挥舞长剑的特蕾希雅姿态美得悲壮不已。

挥出的剑闪，避开武器的步法，宛若舞蹈的剑舞，使众人知道她的高度。

一介剑士在「剑圣」的剑力下看到出神，只能感叹。

但是特蕾希雅的侍从卡萝·雷玫迪斯却觉得痛苦与悲伤。

保护身后浑身是血的威尔海姆，特蕾希雅屠杀不断扑过来的亚人族。以前跨越不了的障碍、犹豫到最后的尽头，是用呼啸的剑击来作答。

她十分清楚跨越犹豫的原因，以及跨越后的结果。

挥剑的特蕾希雅脸颊没有泪湿，但很明显地，她正在哭泣。

在心爱的男人面前，输给甚至害死了家人的宿命，跳著剑舞的特蕾希雅在流泪。

「特蕾希雅大人——」

到头来，自己总是让特蕾希雅哭泣。

跟第一次害她哭的那时候一样，什么都没改变。

得知特蕾希雅和威尔海姆别离，卡萝深切感受到自身的罪过。

5

——威尔海姆自王国军消失，特蕾希雅的名字取而代之。

无法战斗的初征一事被隐瞒，在托利亚斯领的战斗被当成剑圣的「初征」。在之后的战役里，剑圣响应、并完成了所有被期望的成果。

凭借无私的忠义效忠王国，挥剑的美丽剑圣受到大家的称赞，过去的传说再现使得王国热血沸腾，特蕾希雅·范·阿斯特雷亚逐渐被当成英雄。

而跟以前一样在身旁支持她的人是卡萝。

「一直以来谢谢你，卡萝。」

特蕾希雅浅浅一笑，这么说。

可是，那笑容却很虚幻，绝不是特蕾希雅原本的笑容。

能够让她露出真正笑容，让她绽放不输给鲜艳花朵的灿烂笑容的人不是自己，整个王国就只有一个人能办到。

然而——剑鬼那个男人，不知消失到哪去了。

留下无可奈何的焦躁，不久，战争也终于进入尾声。

绵长的王国内战，终于由特蕾希雅带来结束。

由她一人。

为剑神所爱，为王国尽忠，结束内乱，特蕾希雅成了英雄。

成为一名创造传说的英雄、未来会流芳后世的存在。

当事已至此，特蕾希雅已经不被容许以一名少女的方式生活。

不管是赏花，还是在心爱的男人面前微笑，都被拿剑的生活方式给盖过。

从今以后只能作为「剑圣」而活，以「剑圣」的身份死去，这让卡萝著急得要死。

谁都好，拜托救救特蕾希雅。过去自己曾这么祈愿。

而至今她仍这么希望，只不过不再有「谁都好」的念头。

能够拯救特蕾希雅的就只有一个人。所以卡萝只朝那个人祈求。

——愿望没有实现。祈祷没有传达。

什么都没变，特蕾希雅成为英雄的那天早晨——庆祝仪式即将到来。

** 落幕

1

——两年的岁月过去。

对许多人来说，这两年是从剑圣的初征开始算起。不过对少数的相关者而言，这个开始要从距离初征后的几个礼拜才开始算。

「剑鬼」失踪，以及代替他开始快速进攻的「剑圣」。

为剑神所爱的一名少女，引导王国走向千军万马也到不了的结局。

王国军耗费将近十年都无法平息的「亚人战争」终于结束，国内重现和平。

仅以战火余烬为原动力在反抗的亚人联军——连巴尔加·克罗姆威尔的复仇心愿，在能够斩除火种的剑圣之剑面前，也只能屈服。

——结果，举起的拳头找不到可以下拳的点。

亚人联军早就失去当初的主导者，是以继承他们的信念为由才持续抵抗。只不过持续的理由如今被剑圣斩断，就只是这样。

露格尼卡国王吉欧尼斯·露格尼卡和亚人联军代表克拉格雷尔面对面协商洽谈，为期九年的王国内战「亚人战争」就像泡影一样平静结束。

「您非常美丽，特蕾希雅大人。」

站在换上礼服的特蕾希雅·范·阿斯特雷亚面前，卡萝感动泛泪。

长达腰际的红发，映照澄澈天空的蓝眼，白里透红的肌肤。任谁都会看到著迷的美貌——那正是卡萝的主人应有的姿态。

「谢谢你，卡萝。你的礼服也跟你很相衬。」

浅浅一笑的特蕾希雅，夸奖同样精心打扮的卡萝的服装。感到受之有愧的同时，卡萝也感受到两人之间横亘著寂寥感。

——今天，要举办庆祝内战结束、以特蕾希雅为主角的纪念典礼。

终结没有尽头的内战，为人类与亚人的征战划上休止符的大功臣。「剑圣」特蕾希雅的存在享誉全世界，今天就是人类的希望第一次在民众面前露面的场合。

随著今天的到来，卡萝也是百感交集。

当然，她感到骄傲。身为侍从，能够待在特蕾希雅身旁是无上荣誉。

百姓称颂特蕾希雅，每个人都为了一睹她的风采而涌进首都。

这正是卡萝的主人真正被世界认同的证据。

然而，被妆点得美轮美奂的容颜，却只有空虚。

卡萝知道原因，所以内心才会感到复杂。

她知道特蕾希雅其实是为了什么、为了谁才战斗。

特蕾希雅为加持所苦的日子，以及挥别过往决定握剑的觉悟，以「剑圣」之姿立于心上人面前的决心，还有之后的别离所造成的心伤。

在那片花海安稳度过的样子，还有恋爱的她有多么可爱。

卡萝全都知道。所以说，才会痛心疾首。

「我真羡慕你，托利亚斯。」

深深占据重要主人的内心，连自己的男友都念念不忘的那个男人。

但他却不在场，这使得卡萝万分悲哀。

2

忍不住停下脚步，是因为她的存在感太过浓厚。

从休息室移动到典礼会场的时候，遇到一名久候多时的女子。她左右两边的眼睛颜色不同，还有著蓝色头发。

对方大步走向停下脚步的特蕾希雅面前，微笑道。

「传闻中结束内战的英雄……原来如此，美～得像幅画。只不过很遗憾，是不是少了——什么呢？」

「————」

「再——怎么说『剑圣』都是主角。应该要配把剑吧？」

讲话像小丑的女子递出一把剑——收在纯白剑鞘里的仪式用圣剑。

「你是……」

「现在没有互报姓名的必要。虽然是单方面，但我对你——知之甚详。因此，我推荐你拿去。」

「————」

「用不著担忧跟服装的搭配。这世上还有比那更重要的事。——而且呢，你不管做何种打扮，还是剑比较适合你吧？」

闭上一只眼睛，女子世故地这么说。

特蕾希雅犹豫片刻，最后接过女子递出的圣剑。

「这样就好。没什么，就是有点多管闲事——啰。」

事情才刚办完，女子就留下这句话立刻离开会场。特蕾希雅犹豫是否要叫住她，但最后只是看著她离去。

会场里头挤满了来自全国各地，只为亲眼目睹「剑圣」英姿的人们。因此不能为了自己的事给那么多人添麻烦。

「这是美德，却也是坏习惯。有时像他一样蛮干乱来也不错。」

明明没听到，却觉得听见那个女人这么说。特蕾希雅往前走。

走过长廊，看到会场。狂热蜂拥而上。

「竟然帮情敌推了一把。这样一来，我仿佛可以看到他厌恶的——表情了。」

总觉得好像听见了愉悦中带著懊悔的女人声音。

3

典礼顺利地按照每个人的期望平稳进行。

一开始，「剑圣」带著仪式用圣剑现身时掀起喧哗，但在看到特蕾希雅英姿焕发走进会场的姿态后，每个人都看著与剑同在的她看到入迷。

不单是国民，连国王也不例外。他甚至忘了呼吸，更忘记要颁发勋章给这名纤细娇躯里头蕴藏超人之力的少女。

举手投足无不充满魅力，随著典礼进行，每个人都这么想。

这样一名美少女，根本就和钢铁武器的粗鲁不合。不应该让她拿剑的。

那如梦似幻的侧脸诉诸本能，告诉大家她只想欣赏、培育花朵。特蕾希雅·范·阿斯特雷亚的风姿样貌，柔性得让人这么想。

「————」

特蕾希雅抬起头。

跪下，被国王亲手授予勋章后，少女再度站起，转过身去。

——仿佛要斩断会场的狂热般，一道黑色人影缓缓走来。

人们顺著特蕾希雅的视线看到那个人影后全都屏息。从头罩住身子的褐色上衣满是泥巴，骯脏的打扮增添寒酸。可能都没洗澡吧，皮肤上都是干掉的血跟泥土，整体的外观给人的感觉就是惹人生厌。

但是，大家没有开口说话，并不是因为这个原因。

而是因为他手上的出鞘之剑，和浓密到足以引发晕眩的阴森之气——不，是剑气。

担任会场警卫的士兵们个个紧张不已。但是，制止他们的人不是别人，正是特蕾希雅。人影笔直地朝自己前进，特蕾希雅也走过去。

不久，两人就在会场中央，只有典礼的主角才被允许登上的舞台上正面对峙。

「————」

美丽的白色圣剑被举起。寒酸冒有铁锈的钝剑摆开架式。

双方简直就像商量好一样，悄无声息地以剑刃交锋。

一开始，观众只觉得两人像是消失了。但是当耳朵听到钢铁互相撞击、咬合的声响后，目光就自然被战斗所吸引。

以常人的肉眼根本追不上的压倒性速度所展开的剑舞。

闪光乱舞，撞击的钢铁像在演奏，不知不觉间人们看到流泪。

眼睛看不见，连声音都听不清，只能被震慑。

然后，每个人都否定方才在仪式过程中所产生的感慨。

否定特蕾希雅·范·阿斯特雷亚跟剑不配的感慨。

在这场战斗中，人们看到钢铁之美，钢铁的尊贵，与钢铁依偎的光辉。

人与剑，原来可以给予他人美妙的感叹到如斯地步。

代替勉强用视力追随的观众，得以贴近这场战斗的人无不感到惊愕。

剑戟交错，短兵相接，变换立足点再互击，两人的剑术高明得可怖。

「剑圣」的实力有目共睹。他们也是参与了内战的人，曾亲眼拜见过那精湛的剑技。可是，与「剑圣」势均力敌的敌人，其已臻顶峰的剑力又叫什么？

剑圣命令卫兵退下，国王也命令他们看著就好。从命的他们只是默默看著，但心里觉得这样真的好吗。

敌人是什么人？是反对内战结束的亚人激进派吗？再加上人类也不是团结一致。不管哪一种，都有可能是不满内战结束的敌对人物。

是的话就得阻止。但是，那是肉身可以办到的事吗？

谁有办法介入顶级的剑技应酬。

而且，再加上……

看见毫不留情挥舞圣剑、斩击如风的「剑圣」的侧脸。

怎么说呢？要一语道破的话就是：谁能阻止那个恋爱的少女呢。

挥剑的「剑圣」双眼湿润，脸颊泛红，每一次过招都紧咬幸福。

舞动宛如摇曳火焰的红发，禁锢穹苍的蓝色双眼，美丽温柔的剑神宠儿因欢喜而愉悦。与外貌似鬼的剑士交战，对她而言仿佛像在度过这世上最灿烂的时光。她是由衷在享受这世界上最危险锋利的幽会——

「————」

然后，最了解「剑圣」的贴身侍从，还有认识「剑鬼」的人们个个战栗。想看到的人，想知道的事，全都在这瞬间获得解答。

挣扎著想成为剑、被称做鬼的男人，在尽头看到了什么？这个问题的集大成。

「————」

银闪划过，剑闪交叠，一闪极致，拋弃世界并合奏乐曲。

那些声响简直就是歌曲。

以顶级剑技和上好钢铁，以及无止尽高涨的感情所演奏出的交战之歌。观众全都成了俘虏，笨拙的两人在众目睽睽下高调谱写恋曲。

可是，就像不管多美妙的歌声都需要换气。结束来临，被期望能永远继续下去的战斗，终究要结束。

承受不住激烈的交战应酬，钢铁碎裂声在会场中如雷贯耳，褐色剑刃从中间折断，前端在天空旋转飞舞。

战斗结束，两名剑士的幽会划下结局。而「剑圣」手中的圣剑——

「是我…」

「————」

「是我赢了。」

圣剑落地出声，早一步下了舞台。剩下的就只有与之相对的鬼手中那仅存半截、徒具华丽装具的钝剑。

015

钝剑断折的剑身，抵住剑圣白皙的喉咙。在场的人都领悟到。

——剑圣输了。

那是被称做剑圣的超人，被拉下剑技顶峰的证明。

而每个人都慢一步察觉了，松手放开剑之后，得以身在当场的少女的模样。站在那儿的，仅仅只是一名恋爱中的美少女罢了。

「比我弱的你，已经没有持剑的理由了。」

面对剑圣，有谁这么说了。对这世上最强、立于剑技顶点的少女，有谁这么说了。

有资格的人，必须胜过剑神的宠爱。唯有那个人方能示爱。

——为了获得那个资格，究竟，他倾注了多少的钻研在其中啊。

「我要是不拿剑……有谁……」

「你挥剑的理由由我继承。你就当我挥剑的理由吧。」

——数百、数千、数万、数亿。剑士心中有无数纠葛和挫折吧。

只为了传达那一句话，只为了能够开口，而做了无数战斗。

笨拙至极的男子，拨去上衣的帽兜。

现出扑克脸的青年头发杂乱，脸被泥巴弄脏，眼神还很凶恶。

但是，眼中有藏不住的爱意。在那道视线中，特蕾希雅怜爱摇头。

「好过份的人。把别人的觉悟和决心全都糟蹋了。」

「那些被糟蹋的一切，全都由我继承。你就忘记自己曾握著剑，悠哉地……对了，种花吧。边种花，边在我后头安稳过日子就好。」

「在你的剑的守护下？」

「对。」

「你要保护我？」

「没错。」

毫无迷惘的断言，怀有就算挡路的是剑神也不会退让的觉悟。

仅凭己力，将一名少女从「剑圣」的位置拉下，让她恢复成心爱女性的觉悟。

手贴著抵著自己的剑腹，特蕾希雅往前一步。

从能互相接触的距离，接近到呼吸碰得到彼此的距离，两人相望。感情激动，双眸湿润，转眼溃堤，泪水沿著微笑滑落。

然后，流泪微笑的特蕾希雅道出两人幽会的例行问答题。

「你喜欢花吗？」

「变得不讨厌了。」

因为那片花海有你。因为我在那片花海与你相遇。

因为是你所爱的世界，包括你的美与你所希望的一切。

「你为什么要挥剑？」

「为了守护你。」

——而你对我来说，正是世界的起点。

慢慢地，彼此的脸靠近，距离缩短，最终消失。

寻求彼此的热情触感。

在极近距离下接触的吻，滚烫火热到足以使顽固的钢铁变形。

「你爱我吗？」

「知道就好。」

虽然嘴唇分离后的第一个问题，使青年害臊得无法回答就是了。

4

剑舞，幽会，两名男女亲热，结束。

著迷于剑舞，见证他们的幽会，远望他们的亲热时，卡萝哭了。

那是卡萝以为再也见不到、特蕾希雅真正的容颜。

看啊，大家快看啊！好想大声这么说。好想大叫，好想让大家知道！她是个心地善良的人。拿起剑来比谁都还强，可是却温柔善良。

希望大家知道她在心仪的男性面前只是一名楚楚可怜、爱笑的少女。

含泪的卡萝身旁，不知何时站著格林。

他也在仰望相拥的两人，像在看耀眼之物般眯起眼睛。

——格林的侧脸，突然令卡萝脑内的记忆复苏。

那是以前，和还可以说话的格林交谈的一幕。

因为某件事，那个男人成为话题，而自己像平常一样严厉批判他的时候。

「说起来，『剑鬼』这个别称对剑士来说也太不体面。剑士会被人看做是鬼，一定是生存方式有所扭曲！」

「哈哈……好不留情呢，卡萝小姐。虽然我不能否定。不过……」

「不过……？」

虽然一脸懦弱的笑，但格林却对卡萝的话有意见。

反问他的卡萝好奇接下来的话，格林则是在苦涩笑容中掺入自己百分百的信赖。

「一开始叫威尔海姆『剑鬼』的人，说不定就是我。在卡斯泽尔平原，看到虐杀亚人的威尔海姆后，对战争的惨状感到畏惧的我就那样称呼他。」

「那是没办法的事吧？虽说那家伙在战场上的行为是很相符……」

「是吧，他用厉鬼一样的表情在战斗。这点我也不觉得有错。」

对卡萝的肯定，格林抓抓脸，接著说：

「以鬼一般的形貌战斗的剑士，所以叫剑鬼——可是，现在我认为，那说不定是理所当然的呢。」

「你说，理所当然吗？」

「若是在认真挑战事物的时候，有不得不化身成鬼的情况下……那么威尔海姆看起来会像鬼，是因为他一个劲地全力投入吧？我不知道有谁能像他那样以鬼姿应战。我还没遇过有谁活得像他那样认真。」

声音平静，却又充满著迷。卡萝忍不住嫉妒威尔海姆。

哎，自己会讨厌那个男人，说不定就是这个原因。

「剑鬼……真不错的称呼呢。威尔海姆为剑认真，为了活下去而认真，所以才会被称作鬼。而那一定——」

5

「——剑鬼！！『剑鬼』威尔海姆·托利亚斯！！」

脸才背过寻求誓言的特蕾希雅，瞬时名字就被人叫得震天价响。远方传来久久未听闻的绰号，威尔海姆转身。

顿时，仿佛施加在会场里的魔法解除，群众和卫兵都回过神来。

「威尔海姆，你这个大白痴！」

「——！」

跑过来的卫兵当中有眼熟的大个子和青年，威尔海姆耸肩。

没有抵抗的意思。只是一想到之后的事，就觉得筋疲力尽。

干脆掳走特蕾希雅逃跑好了。甚至动了这种念头。

「奸～诈！」

不过，跟这念头相反，特蕾希雅抓著威尔海姆不放，鼓起腮帮子。爱笑，爱生气，爱闹别扭。是那个在花海中充满魅力的女孩子。

「有些事还是希望能听人亲口讲出来啦。」

「呃——」

她在央求方才的问答题后续。威尔海姆抓抓头。

把真正的心情讲出来，实在是很难为情的事。

都在这么多人面前接吻传递心情了，可能会被人骂事到如今还扭扭捏捏什么劲。

「————」

不过，因为她热烈央求，只好无可奈何地摇摇头。

威尔海姆夹著叹气回头望向特蕾希雅，脸凑近她耳边。特蕾希雅的脸颊红通通的，瞳孔因期待而发热。

楚楚可怜的样子让他屏气，涌到喉头的话语一下就消失不见了。

然后————

「等哪天有那个心情的时候。」

「剑鬼」头一次在紧要关头胆怯了。

6

——就这样，这个故事落幕了。

以王国内战「亚人战争」为契机，在战争中培育出来的羁绊与感情。

一名少年，憧憬剑之美、钢铁的高尚而备受煎熬地过著每一天。

转眼间少年成长为青年，邂逅了少女，因剑知晓了无止尽的爱。

这个故事，是希望化身成剑，生活方式激烈得被称之为鬼，然后成为一个了解活著的热情的人，最后在一名女子面前成为男人——这样的「剑鬼」的故事。

他让为剑神宠爱、超越人类领域而被称为「剑圣」的少女回归成一名恋爱少女。

只为此而歌唱，笨拙的剑之鬼恋曲。

任谁都迷醉、憧憬到胸膛发热的男女恋爱故事。

——「剑鬼恋歌」，人们这么称呼。

就只是这样的故事。

016

** 后记

嗨，大家好，我是长月达平。对某些人来说是鼠色猫，而对不知道的人来说就是本名那一方，平时承蒙各位关照了。

这次谢谢诸位阅读Re:Zero Ex2到这边。

尽管每次都会确认，我想应该是没有人会没看过本传就直接来看系列作的番外篇吧，不过能够获得长久喜爱真的让我很高兴。

包含这次的「剑鬼恋歌」在内，Re:Zero系列书籍已达十本！

虽然有一个月的落差，但几乎是在整整二年内便出版了十本。能够这么顺利不间断地出书，都要感谢大家的支持。今后也请多多指教。

那么，关于本书的内容，是以本传登场的人物作为主角的衍生作品。

Ex也出了第二集，上一集的故事撇除了本传男主角，而这一集也不例外，故事里头没有本传男主角登场。

故事内容在本传的四十年前左右，换言之对最喜欢过去篇的作者而言是垂涎三尺的题材，因此写得很愉快。担任Ex2主角的威尔海姆不用说，担任配角的男男女女都有在本传中登场或是出现名字，这样的出场安排若是能让读者喜欢，是我的荣幸。

——常言道：人本身就是历史。

这次身为主角的威尔海姆，会在四十年后的本传中成为怎样的角色呢，在过程中又会发生什么事呢。

像这样延长作者写的故事，光是想象，是不是就越来越爱上这故事了呢。

持续创作下，多亏大家的福，才得以让作品成为动画登上电视。

动画获得许多的人协助与用心，制作进行得很顺利。身为原作者，能帮的部分我都尽量帮忙，作者和制作群当然都希望能制作出让喜欢这个故事的读者们接受的动画作品。

关于动画的详细内容和情报请在官网查询，不过系列小说也有满满的情报，您留在手边真是太聪明了！

好啦，篇幅将尽，照惯例进入致谢时间。

责编I大人，感谢您每次都迅速通过作者乱来的提案。前一本（本传第七集封面）的老头封面还不够，还容许我让那个老头担任衍生作品的主角，真的是非常感激。多亏了您，我写了很棒的故事。

画插图的大冢老师，这次也谢谢您绘制的美丽插图。角色人数多又还是过去篇，所以有很多只会在本书出现的角色，内容复杂困难。然而您鬼上身的角色设计图画得之快之正确，实在精彩至极。今后也请多多指教。

设计师草野老师，每次都谢谢您的精美之作。如今从大冢老师那儿收到封面图后，已经有「这次的成品会怎么样呢！」这样期待的余裕了。您的卖力成果当真没有背叛用十本书建构的信赖关系，这次也多谢您了。

还有漫画版的マツセダイチ老师和枫月诚老师，给予我的故事各种色彩与形体，真的很谢谢两位。这次硬是要求要配合两位老师的漫画同时出版三本书（编按：此为日版时程），这么任性真的很抱歉。谢谢您们！

其他还有MF文库J编辑部、营销人员、校阅人员以及书店的工作人员，真的每次都承蒙诸位照顾了。

多亏诸位的帮忙，才能成书。

还有在最后，总是寄送温情讯息和加油信给我的读者们，实在非常感激您们。有您们才能出书到第十本，今后还请继续多多指教。

那么下一次，能在本传第八集相遇的话我会很高兴的。

2015年11月 长月达平《冷到手冻僵，于是装备无指手套中》017

「好啦，满是血腥又都是男人味的本传也结束了，从这边开始就是惯例的情报专区。好了啦，威尔海姆你别臭著一张脸，笑一个笑一个。一、二——」

「……根本没那个闲功夫聊天吧。该做的事没做会被你的随从踢屁股，这我可敬谢不敏。就快点开始吧。」

「真是的，一站在人前就马上害臊了……」

「你啊……！」

「好啦好啦，那开始发布情报啰～。首先，当然就是众所瞩目的动画情报。在本书的日版书腰有提到，不过为了那些没看就随手扔掉书腰的人，我们就来——好好讲一下。」

「播放时间是从2016年4月开始，也发布了跟确定制作动画时不一样的主设计视觉图。完成度还不错，有把故事内容表现出来。」

「又这样高高在上看人了……动画工作人员和配音员还有制作公司都公布中。详情请去官网确认喔，讲是这样讲，不过总感觉很没魄力耶？我讲得还好吗？」

「有点失礼但还在容许范围内吧。比起那个，情报不是只有动画。不要漫不经心的，花女。」

「哼，明明是不良士兵……呃、嗯～当然还有啰。像是在月刊Comic Alive和月刊BIG GANGAN连载的Re:Zero漫画也跟这本书同时发售。可以搭配这本书一起享用喔。」

「下一本是本传第八集，预定在三月发售，可别延迟了。」

「这样就结束了！来，喝茶吧。还是说，出去哪边逛逛？」

「跟你有什么……不，我说错了。走吧。」

「啊，真是的！用不著害臊呀。……不过就是这点可爱。」
