#+title: Re:从零开始的异世界生活 短篇
#+setupfile: ./setup.setup
* 短篇

** 艾米莉娅的博客练习用日记

网译版 转自 百度贴吧

扫图： 吃节操的南瓜菌（微博：爱理阿卡迪亚）

翻译： Chinyu°（微博：结城明日奈）

那个，虽然我非常手足无措，但是这样的可以吗？

各位，初次见面！我是圣卢格尼卡学院……诶？不能说学校的名字吗？

哇，对不起！那么，我是国内某大型学院的高中部的学生，也正在从事读者模特，我叫艾米莉娅。

被朋友劝说，所以用起了叫做博客？的东西，开始写这样的练习用日记一样的东西了。对于能不能写出读起来很有趣的东西，我感到非常不安，但是我想努力变得有意思一点的。请多指教。

从什么开始写比较好呢……啊，这是学校的朋友蕾姆酱一边教我一边写的。因为我是机械白痴，所以完全不会用手机，一直都是蕾姆酱教我的哦。为人可靠的蕾姆酱是我引以为傲的好朋友。

“艾米莉娅酱。请快点切入正题。正在阅读的大家要感到厌烦了。”

……被训斥了。

“现在可不是消沉的时候。你看，首先从早上开始讲起。”

好——的。我每天早上起床的时间是五点半。虽然七点半左右才从家里出发，但是因为我的头发很长，所以整理起来非常麻烦。还有，虽然说出来有点难为情，但是我怎么也没法从被窝里出来。

“银色的长发是遗传母亲的，编发的方式也经常变换呢。蕾姆是短发，所以有点羡慕。”

是吗。妈妈的头发也是银色的长发，我和她长得很像，所以私下很是骄傲呢。

早上起来之后梳理头发很麻烦，洗澡时也是洗得最费劲的，但是因为一直在留长，所以非常舍不得剪掉。周六的时候，因为下午放学之后有模特的工作，所以不会变换发型。

“艾米莉娅酱，睡觉的时候是穿睡衣派吧？”

嗯，是哦。我喜欢的睡衣是粉色的，上面有着小猫的图案哦。虽然家里也有养猫，但是和我家的帕克一模一样，非常可爱！

早上起床之后，就在梳妆台前梳理头发，之后换上校服。圣卢格尼卡……咳咳。我们学校的校服是水手服！夏季制服凉爽舒适，但是比起冬季制服少了几分轻飘飘的感觉。对于校服，我可能更喜欢冬季制服。

“我觉得，不如说是艾米莉娅酱比起夏天更喜欢冬天。虽然蕾姆也是更耐寒一点……但是艾米莉娅酱超越常人了呢。”

因为，夏天就算想抱帕克，也会被它躲开。冬天的话，就可以一起钻进被子里，帕克也不会不耐烦。

“艾米莉娅酱对猫的喜爱先放在一边，接下来是换好衣服，去学校上课了吧？”

嗯。啊，但是稍等一下。去学校之前，会在途中去一下面包店。周六会先去最近发现的装修精致的面包店买午餐，之后再去学校。

我推荐的是俱乐部三明治！是模仿这段时间在电视的特别节目中报道的食物，这是店员偷偷告诉我的。

（注：クラブハウスサンド，clubhouse sandwich，俱乐部三明治，一款北美传统三明治，配料有鸡蛋、鸡胸肉、火腿、西红柿、生菜等。）

“艾米莉娅酱在博客上进行宣传之后，客人们可能会蜂拥而至的。”

啊，那样我说不定也买不到了。是不是保密起来比较好呢？但是，如果面包店能变得有人气的话，我也会很高兴的……嗯，还是写上去吧。

“我觉得很不错。接着就来到学校了，之后就是。”

对。就是下午的工作！总算，做了点符合模特风格的事情了！

放学之后，中午就像早上买的面包一样。

虽然在休息的日子吃刚刚出炉的面包也不错，但是在忍耐到肚子饿瘪了之后再吃，就会变得非常好吃。啊，吃完之后要好好刷牙。

虽然被嘱咐要注意饮食，但是我对甜食的抵抗力很弱。一不小心就动摇了，所以一定要提高注意！

吃完午饭，从下午开始就要去模特事务所上班了。要迟到了？

（注：原文为“重役出勤”，指很长时间的迟到。常用于对那些迟到的人的讽刺。）

“呀。你来了，艾米莉娅。”

啊，前辈克鲁修小姐先到了事务所。身材苗条高挑，五官端正，非常帅气！

明明长着一头漂亮的绿色长发，但是像男人一样帅气，被她看着的话不知为何就会变得恍惚起来。

“那是在干什么？博客？诶。明明是机械白痴，真少见呢。”

被她笑话了。顺便一提，克鲁修小姐虽然是模特工作的前辈，但是也是学校的学姐。在学习和运动方面都相当有名气，克鲁修小姐被夸奖的时候，我也会偷偷地觉得自豪。我呢……那个，学习和运动都有点不擅长。

“作业还有不明白的地方就来问我吧。作为交换……”

在我垂头丧气的时候，克鲁修小姐投来了温柔的话语。在那之后，又露出了有些难以开口的表情，我也很快就明白了。

我知道了。又是想收集素材吧！我来帮忙！

“抱歉呢。看来只有在这一点上，无论如何我的欲望感知器都过强了。”

令人意外的是，克鲁修小姐非常喜欢玩游戏！但是却不怎么擅长，这一点也很可爱。其实，我虽然是机械白痴，但是只有游戏玩得还可以。最初就是和克鲁修小姐在休息时间一起狩猎，才变得亲密起来的哦。

“哈——，总算结束了。啊，是艾米莉娅酱。呀吼。”

我正和克鲁修小姐聊着天，这时候普莉希拉酱来了。普莉希拉酱和我同岁，开始模特工作也差不多是一个时候，是我的好朋友！是同期的樱花！

（注：原文为“同期の桜”，同期之樱，是日本的一首军歌，意指同一时期的战友。）

“普莉希拉酱你啊，一副漫不经心又疲惫不堪的样子。那样的话，憧憬普莉希拉酱的孩子们就要幻灭了哟？”

和那位普莉希拉酱一起出现的，是造型师菲利斯先生。是个非常可爱的人，衣着打扮也很出众……但是他其实是男的！不过，什么都可以跟他商量，是个十分值得信赖的大哥哥……嗯，果然还是像大姐姐一样的人。

“听我说，艾米莉娅酱。关于明天的衣服，小菲利太过分了。居然不让我穿可爱的衣服呢——”

“因为，普莉希拉酱的胸部有点大呢。明天是可爱风格的，就交给艾米莉娅酱了，普莉希拉酱是性感担当。怎么样？”

虽然菲利斯先生向我眨了眨眼睛……啊哈哈，这样回答就行了吧。

普莉希拉酱虽然和我同岁，但是那个，胸部非常大！大得厉害！啪嗒啪嗒地摸了摸自己的胸部，再看着普莉希拉酱，突然就变得沮丧起来。

“啊！不好了。今天被嘱咐了要早点回去。那么，我就先告辞了。艾米莉娅酱，明天见。”

在我陷入消沉的期间，普莉希拉酱就像龙卷风一样忙忙碌碌的。明明刚才的对话还没结束，她就拎起包，迅速地走了出去。

“普莉希拉酱真的很有精神呢。小菲利，也对她的年轻活力感到震惊。”

“菲利斯说这话还太早了哦。那么，我也还有事……菲利斯，不要捉弄艾米莉娅酱。”

“不会的喵。真是的，克鲁修酱也太不留情了喵。”

因为很久以前就认识了，所以克鲁修酱和菲利斯先生关系非常要好。

克鲁修小姐走了之后，就剩我和菲利斯先生了。今天的工作是对明天周日的摄影进行讨论，还要试衣服……。

“那么，去换衣服吧。哦呵呵，不会弄疼你的喵——♪”

虽然很信任他，但是被他那样笑着说话，稍微感觉有些不安。

明天一天都要进行模特的工作，所以从早上开始就很忙碌。整个上午都在摄影棚，下午似乎要去水族馆。因为普莉希拉酱也一起去，所以不会感到特别不安。

“虽然有点太过奔放了，但是咱可不会觉得不安呀。”

经纪人阿纳斯塔西娅小姐，一边说着明天的日程，一边笑了起来。

经纪人阿纳斯塔西娅小姐能力出众，在事务所似乎也是负责照顾充满潜力的女孩子。克鲁修小姐和普莉希拉酱这种还能够理解，但是让她来负责我简直就是天方夜谭。

“现实就是现实。把梦想变成现实也是咱的工作。今天也会把你当做试衣服的人偶，明天也要做好觉悟哦？”

被这样威胁了。

讨论结束之后，阿纳斯塔西娅小姐稍微绕了个远路，开车把我送回了家。外表可爱的阿纳斯塔西娅小姐，开着一辆非常狂野的跑车，这也让我吓了一跳。但是那辆车很适合她，我什么时候也能变成像阿纳斯塔西娅小姐一样成熟的女人呢——我如此想道。

被阿纳斯塔西娅小姐开车送回去，在天黑之前到了家。

因为最近白天变长了，所以可以长时间地看到晚霞，心情有些愉快。橙色的天空，不觉得看起来十分香甜可口吗？啊，似乎让谁目瞪口呆了！

“姐姐又在说奇怪的话了。”

在家门口被吓了一跳。遇见了在外面玩耍之后回到家的妹妹贝亚托丽丝！而且刚才的自言自语，似乎被她听到了，好害羞啊。

“没关系。令人失望的部分不会表现在照片中的，放心吧。”

呜——，真是不可爱！早熟的妹妹最近会像这样捉弄我。既然被她那样说了，我也不会给她好脸色看，也不会跟她一起洗澡了。

“太卑鄙了。姐姐，真狡猾！”

被她用一副快要哭出来的表情说到，我只好败下阵来。跟她和好，一起回到家里，直到晚饭前都和贝亚托丽丝表演时尚秀！给可爱的妹妹换衣服之后，稍微有点理解了菲利斯先生的心情。不对，是非常理解！

今天的晚饭是日式风味的。虽然有什么要细嚼慢咽啊、吃三十种食物的说法，但是全都交给妈妈有点不好意思。偶尔也会帮一些忙，每次戴上围裙收拾餐桌的时候，贝亚托丽丝也会挺直脊背来帮忙。

之后就是和贝亚托丽丝一起洗澡，换上睡衣在书桌边做作业。从事模特工作是以不落下学习为条件的。学习也要加把劲！

做完一半的时候，就输给睡意钻进被窝了。

不对。是因为明天不得不早起，并不是我输了。

啊，帕克来我房间了。真少见。明明夏天的时候很怕热，但是今天愿意和我一起睡了吗？好乖好乖，一起睡吧。

像这样，我的一天就过去了。明天开始也会继续努力写日记的……但是今天就到这里了。嗯，晚安。

《完》

** EX 从零开始过错的异世界生活

网译版 转自 百度贴吧

翻译：hhh0578

——占据了整个意识的，是以肉体为中心扩散开的剧烈【炽热】。

【咕、呜呜呜呜！好烫】

昴的脸面紧贴在坚固的地面上，他知道自己正趴伏在地。但是，能够助他站起身的手脚却一动不动。

就仿佛，自己不是自己，肉体的自由被完全剥夺。

但是，只有这份灼热正在永无休止地灼烧着昴，这可不是开玩笑的。

——好烫，好烫好烫好烫好烫好烫好烫好烫。

一张开嘴，比起惨叫首先涌出的是大量的鲜血。

在剧痛与苦楚的最后，又几乎溺死于自己涌出的鲜血中。昴正品尝着这个世界上最为极端的苦痛。

——自己，到底做错什么了。

想要从这份痛苦中解脱出去的愿望，在他的脑海里不断重复着这样的哭诉。

自己，到底做错了什么。

的确，自己的生活方式绝对说不上是值得褒扬。但是，也绝对不应该落得这种下场。不管是谁，都应该不敢说自己平日里的为人正直廉洁到可以傲视全人类。都应该有让自己不堪回首，让自己后悔不已，让自己不忍直视，让自己自我妥协的经历吧。

但却为什么，只有自己会遭到这种事情。

为什么，这份命运对其他所有的人类睁一只眼闭一只眼，却只向自己逼迫而来。

【啊啊，可恶……】

在汩汩泉涌的血液里，透出了这句低喃。

这是后悔，是对弱小的憎恨，是对命运的憎恶——，

——是对自己的，死心。

【————】

哪怕是受到了如此严重的创伤，遭受了如此的痛苦，经历了如此令人不仅求死的经历。

哪怕是被炽热灼烧全身，被剧痛真正意义上地斩过四肢，甚至生命遭受威胁。

只因为刻在自己脑海中，不断浮现的那位少女的身姿、微笑、和令人悲痛的死状。

【我】

如今，再一次，把决心说出了口。把觉悟说出了口。把留恋、后悔说出了口。

哪怕挑战无数次，垂死挣扎无数次，祈愿无数次，也要抓到那份遥不可及的未来。

【疼痛】和【炽热】都远去，败家犬就该像个败家犬，不要脸地吼下去。

【绝对】

挥舞的利刃，无情地迫近犹如风中残烛的濒死生命。

不过，这都已经入不了他的眼了。因为，他早就已经下定了决心。

——要，救你。

就在菜月·昴再一次心生这份愿望的瞬间，生命的灯火熄灭了。

※　※　※　※　※　※　※　※　※　※　※　※　※

——熟悉的光景再度出现眼前，让昴感受到了奇妙的安心感和无力感。

【平安回来了，是吗】

昴眺望着王都的人流，拾起一根树枝在地面写着【正】字，写爽了之后用一脚将其抹消叹了口气。

菜月·昴，是出生在太阳系第三个行星地球上的普通辍学高中三年级生。

运动衫配运动鞋，再加上手上拎着从便利店回家时候的塑料袋，看到这种随意的打扮，不管是谁都不会对产生怀疑吧。

但是，这个道理只在价值观相同，能够正确理解运动衫、运动鞋和便利店这种横读文字的意思的文化圈里才通用，

也就是说，这里真正想说的是——，

【——异世界召唤，比想象的要难受得多啊】

和马一样大的蜥蜴拉着马车，风尘仆仆地从眼前经过。

当然，这道风景在地球上是不可能看得到的。那么，如果要问刚才那个是不是对马进行了特殊的化妆，即主题公园里的演员之类的，这也让人难以苟同。

要说为何，蜥蜴并不仅仅有刚才那一头，大道上四处来来去去的都是，而且驱使这种蜥蜴的人们也有很多都是有这种特殊化妆的。

人型野兽——装作是兽人亚人这些种族的人类，光是在昴目光可及的范围内就有二三十人。当然，和昴同样的一般观光客也有很多，但因为那些人名为外貌的个性也过于暴力，导致让人难以意识到正常。

再说，继续这样逃避现实不可取。

这些兽人蜥蜴，不是演员也不是电影的特技。在这片文化圈里，这才是理所当然的当代流行，在这里昴才是异类而不是他们。

——主观上已经在这里度过了十几天的昴对此痛感地不能再深了。

【……走吧】

昴停下这种无益的思考，拍拍屁股站了起来。

拾到的树枝仍旧拿在他的右手，整个人飘飘忽忽地走向大道——不是外面人潮汹涌的大道，而是向着里面走了过去。

和人群摩肩接踵的外面不同，这条弄堂被夹在两栋高楼之间，人烟稀少。十分符合它小弄堂的氛围，只是隔了一条街就安静得恍若隔世。

说开了，就是在这里不管发生什么，惨叫也传不到外面的大路上。

因此，若是像昴这样一脸乡下人进城模样的人迷路到这个地方来，自然而然地就会有盯上他的恶人现身。

【哟，小哥。陪我们玩玩吧】

昴听到声音转过头去，只见三个人正堵在路前。

满足了小中大所有需求的列队，昴从他们身上感觉到了真正的调研能力。虽然不知道是调研什么的。 （/*原文只有research，一般就是市场调研了吧*/）

【——】

昴歪过头，望向和三人组反方向的道路。只见身后就是死胡同，要去大路只能让这三个人让路了。

那么，这三个人到底有没有让昴出去的意思呢——

【喂喂，一脸呆相是要怎么样】

【看他还不明白现在什么状况吧。告诉他一下也没什么不好的吧】

看到昴慢悠悠的动作，三人卑劣地笑着开始包围昴。在对方看来，昴浑身上下散发着外行人的气息吧。

正是个好猎物，他们见到这样的昴会蠢蠢欲动也无可厚非。

但是，这完全是他们看错了。

的确昴不是很会打架，也没有什么学过格斗技的隐藏设定。就是个外人，他们的判断没错。

但是，昴在他们的应对方式上，可以说是身经百战。

【——啊？】

昴对大意的大汉——被他起名为桶庆汉中的桶刺出了手。

昴的手中，握着刚才捡到的树枝，这根并不怎么锐利的树枝，刺入喉咙的柔软部分，突破了那道柔弱的抵抗刺了进去。

【喂？】

这一瞬间发生的事情让桶瞪大了眼，站在他两边的庆和汉也都当场僵住了。

这样桶就起不来了。然后，昴向还僵在原地的那两个人里身高适中的那位——庆伸出了空出的那只手，昴抓住他的头发和耳朵把他甩了出去。不给他抵抗的机会。一口气把他的脑袋撞到一旁的墙壁上。

一声实打实的撞击声，庆就这么靠着墙倒下，划出一道血痕。

与此同时，脖子上还插着树枝的桶跪倒了地上，翻着白眼倒下了。而且因为倒的姿势不好，向前面倒下，使得树枝插得更深了。

这样，就废了两个人了。剩下的一个人——。

【噫】

身材瘦小的男人——汉看到自己的两位同伴一瞬间就被打倒，脸色发青。

如果他就这么扔下两人向外面跑去，和昴比脚力的话或许还会出现一线生机。

但是，汉的目光落到倒下的两人身上，迟疑着是否要逃走。殊不知他们早就已经没救了，把这唯一的一秒机会浪费在了犹豫上。

蠢货。超蠢货。对于这种蠢货，就要为自己的选择付出代价。

【咕、嘎，啊啊……】

昴用手抓住他瘦弱的脖颈，用力把他摁到身后的墙上。小小的身体挣扎着，就这么被嵌到墙上拎了起来。昴的双手不断用力，绞紧。

汉被拎到和昴视线同等的高度，脖子被完全绞住的他拼命张开嘴喘着气想要呼吸。但是，呼吸道被全力堵住，又失去了身体自由的他是不可能得到救助的。

【算上这次，你知道，我一共遇到过你们几次了吗？】

【唔、这……】

【八十八次。所谓熟能生巧吗。可笑吧】

昴盯着那张渐渐变得赤黑，眼泪口水涕泗横流的脸说道。

但是，当然汉不可能有这份闲情。渐渐地，别说闲情就连抵抗都没了，昴把失去了抵抗的身体扔在了地上。

昴看着倒在地面上的三人，为了以防万一姑且重重踩了所有人的头。昴感受到运动鞋鞋跟下传来踩碎的感觉，这才放心了下来。

桶的脑袋比较大，需要要用力踩五次。只有这点不管来几次都很难把握。运气好的时候，一人踩一次就够了。

【勒脖子看来是个下策啊。……手感心情都不好，下次不这样了吧】

昴反省完之后从庆的身上搜刮出两把小刀。然后把三个人的尸体适当地拉倒路边，一脸淡然的离开了弄堂。

从进入小路，到遇到桶庆汉，其实都不过是短时间内发生的事情。虽然在处理桶庆汉的时候稍微费了点时间，但其实也才不过十几秒。

昴加快脚步穿过外面的打倒，前往目的地。

【————】

昴望着大道的模样，为自己赶上了时间而安心了下来。

这条大路被称为商业街，这里和其他地方也没什么两样，人来人往，证明了王都鲁古尼卡是个繁盛的地方。

光是站在这里，这份喧嚣都足以让人耳膜发疼。

不过，这份喧嚣，突然变成了不同意义上的骚闹。

【——等一下！真是的！等一下啊！！】

完美破开大道上这份喧嚣的声音，如银铃般让人听了耳朵怀孕。

这份声音中有着走投无路的焦急，但也没法隐藏说话人生性的温和儒雅，而这道声音的说话对象则是传过大道人流的某个娇小身影。

【嘿嘿】

一名金发的少女发出这样小猫般的笑，在人流的缝隙间来回穿梭。她的手中握着一个正在发光的东西，整个人散发着工作完成的氛围。

然后，一道淡蓝色的光辉——冰枪以少女为目标横穿大路飞了过去。

【——！！】

这道出乎意料的攻击让少女吃了一惊，连忙左蹦右跳地避开了冰枪。

在人数众多的大路上释放的魔法攻击使人群出现了些许混乱，王都的人们一齐让开了道路，满满地不想与之挂上关系的态度。

他们的动作整齐划一。在王都，发生骚动是常有的事——倒也不至于，只是差不多就是这么回事啦。

无论如何，穿过这片让开道路的人墙，就能看到自己朝思暮想的人。

【————】

在见到【她】的瞬间，昴就感觉自己的世界仿佛被完全冻结起来了一般。

风、人声、甚至时间都不在自己的感觉之下，所有的意识都被抽离这幅身躯。

银色的长发舞动，如宝石般的紫绀色眼瞳闪烁着坚强的意志，裹着她那皎洁纤细手脚的是就仿佛为妖精量身定做的神秘白色服装——。

她的目标，是在眼前东窜西跑的金发少女——菲露特。

菲露特抢走了她的东西，然后她正为了拿回那个东西奔走王都。从这里开始，通往的将是她避无可避的不幸命运。

但是，他不会让事情变成这样的。

绝对不会，让她被【死亡】的命运捉住。

【我，绝对会救你】

昴看着她远去的背影，第八十八次立下了誓言。

不知道已经打破了那么多次的誓言到底有什么说服力。

虽然不知道，但只要不放弃，只要继续斗争下去，只要继续心怀着救她的愿望——，

【等着我。——莎黛菈】

※　※　※　※　※　※　※　※　※　※　※　※　※

在死亡的时候能够让时光倒流的能力，【死亡回归】。

昴利用【死亡回归】的能力，已经让这个世界重来八十八次了。

挑战的次数即将破百，这一切都是为了将那位银发的少女——莎黛菈从命运的死胡同里救出来。

【都已经尝试了各种方法各种试错了……没法像桶庆汉那样解决啊】

这就是昴在这个命运最大的强敌——艾尔莎·古兰希尔特身上得出的结论。

委托菲露特盗走莎黛菈徽章的就是名为艾尔莎的漆黑女人。这个女人，是无数次将莎黛菈逼上死路的危险人物。

至今为止八十七次的挑战中，昴无数次奔走，为了解决艾尔莎以此来确保莎黛菈的安全。但在艾尔莎非人的战斗力面前屡战屡败，超过五十次被开膛破肚丢去性命。

喜好开膛的sadist艾尔莎并不是能够战斗获胜的对手。（/*sadist：性虐待者，俗称抖S*/）

如果她是和桶庆汉差不多的人的话，只要某种程度上让行为模式化，就能够找到一套必胜的方案。然而，强如艾尔莎，不管昴想要做什么，都只会在一瞬间脑袋落地。

虽然实际上不是掉的脑袋，而是好几次被眨眼间开膛破肚就是了。

昴不可能打得赢她。菲露特，罗姆爷，莎黛菈也是一样。

在得出这个结论后，昴选择的战斗方式是——，

【好棒！好棒！只是，再能多让我开心一会儿该多好！】

【咕啊啊啊——！！】

黑色的刀刃上下飞舞，卷起道道剑风，鲜血随之喷涌。

倒在大路上的人已经两手都数不过来了，浑身浴血的艾尔莎神情恍惚，看起来甚至感觉是正在连续不断地高潮。

身处如此凄惨的地狱的艾尔莎，越是浴血就越添一份娇媚。

听说过去有位通过沐浴处女的鲜血来保持青春的女性，被成作是吸血鬼，而此刻的艾尔莎的姿态正仿佛【吸血鬼】。

【……这也不行，吗】

昴藏身在屋顶上叹息着眯起了眼。

这里是贫民街的一角，周围被废墟包围显得格外寂寥，血腥的地狱以这片广场般的空间为舞台不断扩张。

与艾尔莎战斗的王都卫兵纷纷倒在了她的利刃下。

他们接到一位善意市民的通报，说是发现了危险人物艾尔莎·古兰希尔特，于是他们为了逮捕她而出动殒命——这份光景让这位善良市民内心沉痛不已。

【没想到，普通卫兵和艾尔莎的实力差距居然有这么大……】

这样的话就感觉就像是为了取悦艾尔莎而送上活祭品一样了。

昴期待的是守护王都的士兵能够有什么魔法般的力量强化肉体，然后和艾尔莎战个天昏地暗，可是看起来还是期望过高了。

果然，艾尔莎的实力在这个世界也是独树一帜。

昴对艾尔莎的愤怒越加难以抑制。但是，不管再怎么愤怒，仅凭昴的力量是无法阻止这位凶狠的女人的。

仅凭卫兵们拼运气的攻击，怎么都不觉得能够打到艾尔莎。

【再看下去也是白费功夫吗】

虽然有点对不起卫兵们的牺牲，但这次尝试就让它在这里结束吧。

并不是打算提醒他们逃路，只是他们在这里死了的话，昴最后也会失败死去，他们在重来的世界还会活过来的。

既然是为此而做出的牺牲，现在就先忍痛让他们去送死吧。如果有下次机会，一定不会对他们抱有任何期待的，就安安心心让他们守护王都和平去吧。

昴得出这个结论后，抽身离开了现场。

【——阿拉】

艾莎尔举着刀，停下了脚步，舌头抿过染血的红唇。

四溢的狂喜和杀意，是已经厌倦了虐杀卫兵的艾尔莎找到了新猎物的最大证据。于是，被选为艾尔莎可怜活祭的是——

【——到此为止了】

一瞬间，让昴产生了站在那里的是红色火焰的幻觉。

【————】

昴屏住呼吸，擦亮眼睛，再次望去，这才终于认识到站在那儿的并非火焰而是人。

那是一名青年，拥有赤炎般的红发，澄清蓝天般的碧瞳。

仔细看去，他那饱受锻炼的柔软身躯身着洁白服装，腰际挂着可怕的夸张大剑。

他的五官端正的犹如神迹，走在街上回头率百分之百。这是跨越了性别的美丽，这种富有包容性的美丽或许是出于青年沉着的站姿。

一眼，就让人从灵魂上感觉到了他是于世间万物不可一言而喻的存在——。

【骑士莱茵哈鲁特……！】

【你们退下。她……是【狩肠人】。已经牺牲太多人了。不想再让牺牲者出现了】

面对幸存卫兵们颤抖着的声音，青年——莱茵哈鲁特微微伏下目光说道。

这是他对如草芥般被屠戮的性命的怜悯，也是对造成这一切的艾尔莎这名杀戮者的义愤。

远远望着这一切的昴，对于莱茵哈鲁特这名青年的生性已经窥斑知豹。

这位男性正以何等正当的理由、正当的思考，以正当的精神，对此表现出着愤怒啊。

悲叹死亡，憎恶杀戮，后悔力所不及，然后以后悔孕育信念。

这就是，这位名为莱茵哈鲁特的青年——骑士的生存之道。

【莱茵哈鲁特·梵·阿斯特雷亚。是【剑圣】的家系呢。好棒，好棒啊！】

【这不过是我难以承受的过度评价呢。你，是【狩肠人】没错吧】

【是呢，正是。这可不好。怎么办呢。明明有着重要的工作，居然在这里和你见上面了】

艾尔莎神情恍惚着透露出炽热的呼吸，望着莱茵哈鲁特的湿润眼里充满热情。

另一方面，莱茵哈鲁特的表情则是十分严肃，碧蓝的双眸里充斥着使命感，玩心全无。

思想处在两个极端的两人面对面，得出的结论却是一样的。

相互厮杀，除此之外再无其他。

【本来说真的，我应该劝你投向的……】

【面如这个惨状，你还能对我说这种话？真温柔呢。不管是对我，还是对他们，这都温柔到让人觉得残酷呢】

【——不，我也和你是一样的想法。在这里予以你酌量，对他们的死而言必然算不上诚实。所以，我不会说希望你能投降】

对于愉悦地踢着倒在一旁的卫兵尸骸的艾尔莎说的话，莱茵哈鲁特缓缓地摇了摇头。

然后，他向一旁的卫兵伸出手，简短地说了【剑给我】字。

【务必，拜托了】

收到指示的卫兵递出剑，莱茵哈鲁特握着剑确认着手感。艾尔莎疑惑地皱起了眉头。

【不用腰上的剑吗？明明人家还听说传闻，想要体会一下龙剑的锋利的】

【不巧，这把剑有着能够看穿值得拔剑的对手的性质。虽然这个性质让人有点头疼，不过这把剑似乎并不中意你的样子。相对的，就用这边的剑来当你的对手吧】

【呼嗯】

看到莱茵哈鲁特没有使用腰间的剑，而是借了一把剑摆出了架势，艾尔莎叹了口气。

然而，这种让人认为她有所不满的态度也只在一瞬之间。这位女性当即切换了态度，与眼前这位青年的战斗及其血的预感让她一舔自己的红唇。

【【狩肠人】，艾尔莎·古兰希尔特】

【【剑圣】家系，莱茵哈鲁特·梵·阿斯特雷亚】

相互报上家名的两人化作疾风在广场中央碰撞。

胜负，只在这一击下就决出来了。

没有任何花哨的斩击产生光的螺旋，冲击波将贫民街的一角完全击垮。

被称为【剑圣】的男人的剑击，正是【力量】其本身。

昴瞪大着双眼，望着这道光景。

泪水滑落脸颊，膝盖颤抖着，却至始至终不知道原因何在——。

※　※　※　※　※　※　※　※　※　※　※　※　※

昴的计划，以不同于预料的发展方式，达成了打到艾尔莎这一最大的目的。

莱茵哈鲁特的参战出乎意料，不过自己的愿望达成就是万岁了。

多亏这个，莎黛菈被抢走徽章的事情也平安解决了。菲露特和罗姆爷没能和交易对象艾尔莎见上面的话，自己也就没必要非要自己从他们那里拿回莎黛菈的徽章了吧。而且，莎黛菈应该也不会一怒之下杀掉那两个人。

以盗品仓库为中心的故事，就这样在最少人物登场的情况下结束了。

这就是昴所希望的结果。

所以——

【——你，为什么要帮我？】

【你不相信我也没关系。不过如果说你愿意就这么在卫兵的重重包围下，甚至没法复仇的话，就这么砍了我逃走随你逃吧】

【————】

昴厌恶般地对背后靠着墙壁蹲坐在地上的艾尔莎说道。

她全身是血，黑色的服装也破烂不堪，白色的肌肤裸露在外。不过，由于肌肤上那些触目惊心的伤痕，就连让人感觉到羞耻的余地都没有。

而且，昴本来对艾尔莎就不抱有身体上的兴趣。

只是，想着能够利用一下她，就趁这个机会来了。

【卫兵正满眼充血地在找你。不过我给他们指了反方向的路，所以要注意到这边估计还要好久吧。伤势怎样？】

【好痛哇。好痛好痛，感觉要死了。呼呼，真棒】

【我是没法理解你的感性啊。不过你死了就麻烦了，我倒是想为你做点什么呢】

好不容易冒着危险让艾尔莎活下去了。

如果在这里被打倒，甚至说昴自己也成为了卫兵的搜索目标了的话，这次偶然进入的莎黛菈存活路线就泡汤了。

不过那个时候就那个时候再说吧，现在自己只是在结果出来之前不停投色子而已。

【能够，找到向贫民街东南边去的路吗？这么一来，我就能和妹妹汇合了。伤势也能让她处理，逃脱路线她也应该能够准备】

【妹妹！哈，居然说是姐妹，还真是精明啊，真无可救药】

自己又没有被信任，就算被信任了也只会觉得恶心，不过艾尔莎的话还是让昴找到了摆脱眼前难关的一线生机。

在逃走的时候他们早已来到了相当南边的地方。从这里要去艾尔莎说的地方并不需要多久。

昴用艾尔莎拿的圣金币之类的东西收买了贫民街的人，让他们妨碍卫兵的搜索，引导他们去不同的方向了。没有、问题。

【我想不通呢，你的目的】

【只是想让你欠个人情而已。总有一天，说不定就有用了】

【人情，么。这可真不可思议。——你，不是那么想要杀死我的吗】

艾尔莎搭在昴的肩膀上，对正在提供帮助的昴如是说道。艾尔莎仰着头望着昴，黑色的眼瞳近在眼前，仿佛在窥探昴内心深处的感情。

不过，根本不需要她这么刺探。昴眼中的回答正如她说的那样。

如果可以，昴真想立马就把艾尔莎杀死在这里。不过，如果就这么不考虑先后直接上，哪怕是濒死的艾尔莎昴都打不过，而且这种想法也太鼠目寸光了。

昴现在认为自己正处在一个十分偏激的游戏环境里。

考虑各种各样的方式，尝试各种各样的错误，以最佳选择为前提进行战斗。

想象成是将棋，这可不是容易到只要把棋盘上的所有旗子吃掉就能赢的游戏。

如果可以，化敌为友。如果有机会，甚至不惜改变自己的立场。

为此，哪怕对方是自己打从心底想要杀死的憎恶对象，也要利用。

【我啊，很想杀你。总有一天，要杀了你。但是，不是现在】

【这样】

昴对此根本不加隐瞒，就这么把自己的真是想法全盘托出了。

如果艾尔莎是慎重的那类人的话，必定会当场杀死昴以绝后患。但是，昴确信她不会这样。

这是至今为止的八十八次里——被艾尔莎杀死了八十次以上的昴才会有的，杀意的确信。

【真棒呢。你和我，因为憎恶聚在一起。总有一起，必定。一定，你会向我证明你说的话呢。这可真是真是，太棒了】

【————】

艾尔莎那染血的红唇露出微笑，就仿佛陷入爱恋的少女。

面对着这份笑容，昴打从心底，感觉这个女人是如此的恐怖。

※　※　※　※　※　※　※　※　※　※　※　※　※

【总有一天再会吧？】

【那再见了，哥哥。谢谢你帮助艾尔莎】

在把艾尔莎交给汇合的深蓝色头发少女之后，昴松了口气。

等在艾尔莎说的废墟屋子里的是一名十多岁的幼小少女。昴一开始因为她的年幼而吃了一惊，不过只见这位少女十分习惯地为艾尔莎治疗了伤势后迅速做好了逃脱王都的准备，立马就离开屋子了。

昴经历千辛万苦得到的报酬就是艾尔莎的联络方式。

这个报酬到底值不值得这次冒的险还不好说。

【这取决于我的行动了吗】

昴脱下沾染了血渍的运动衫绑在腰上走了起来。

去的地方是和贫民街相反的盗品仓库那边。艾尔莎没能去到那个地方，昴唯一关心的就是莎黛菈有没有顺利拿回徽章。

【————】

花了一点时间到达盗品仓库的昴对眼前的景象瞪大了双眼。

【这可真出乎意料】

让昴发出这声感叹的是已经化为冰晶的盗品仓库。

比起说是化为冰晶，更该说是仓库被封闭在了冰里。昴稍微向附近人打听了一下到底发生了什么。

【盗品仓库的看门大爷，和他的孙女被卫兵带走了。似乎是和可怕的魔法使为敌了的样子……真不想扯上关系】

【这个，孙女和大爷都没事吗？魔法使呢？】

【听说没有受伤，我对两边又都不熟。问够了吧】

或许是昴咄咄逼人的态度让男人感觉到了恶寒，他挥开了昴的手臂，快步消失在小路的黑暗里远去了。

昴望着他的背影反刍着他的话，安心了下来。

虽然不知道男人说的话有多少是真的，但就刚才的话听来至少没有死人就没错了。

菲露特和罗姆爷会被抓起来也是没办法，毕竟干的这个行当。也该暂时得吃几天牢饭反省一下自己的行为了。

而且，莎黛菈没事。昴知道自己遂愿帮助了她之后——。

【——那么。这之后，我该怎么办呢】

昴挠挠头，感觉自己失去了目标。

被召唤到异世界，拿到了【死亡回归】的能力，随后用它帮助了老好人的可爱银发半精灵。

为此，死了八十七次。

【糟了啊。还是再死一次，从艾尔莎那里问出为什么要偷莎黛菈的徽章比较好吗……？】

本来应该在背受伤的艾尔莎过去的时候问出来的，疏忽了。

不过，如果在那个时候问出来，让艾尔莎知道自己心情上是偏向莎黛菈的话，也不知道她会采取什么行动。

结果来说，现在昴和莎黛菈都还活着。如果，这个选择才是正确的话。

【如果可以，真想再多了解莎黛菈一点啊……】

莎黛菈是从哪里来的，是要去哪里，还能见到吗，都不知道。

为此不断重来倒也是一种方式。

不过要说除此以外的方法——，

【——你们，能够告诉我吗？】

在结冰的盗品仓库前，昴双手插在口袋里回头道。

明明，感觉不到人的气息。但是，却能看见昴的眼前站着无数的人影。

这是由一群面容平凡的男女老少构成的，毫无团体感的团队。

然而只有一点，能够说得上是统一的，那就是他们的双眸。

不管是谁，眼神都是死的。因为，都染上了疯狂，渴求着狂喜。

昴若是照镜子，倒映出的也一定是同样的眼神。

【————】

这份感伤让昴嘴角露笑，他抬起头。

月光皎洁得令人害怕，默默地俯视着冰冻的盗品仓库以及这群狂人。

在那之后过了近两个月，昴知道了莎黛菈的真实身份。

【王选！银发的半精灵！罗兹沃尔·L·梅瑟斯边境伯的推荐！不是莎黛菈，是艾米莉亚——！】

昴抓着在毫无进展，毫无报告的时候突如其来的详细情报，欣喜的拍着手。

这份意料之外的情报来源于在王都的告示下，张贴在全国上下的【王位选拔站】的公告。

一开始，昴对这张贴在看板上的公开情报嗤之以鼻，不过是一个国家的选举，然后他对这个告示目瞪口呆。

因为，在立候补的五名女性里——有一位，正是他苦苦追寻的少女。

【王选，王选吗……国王候补也就是说，身份高贵。难怪，举手投足之间都是高贵的气息。艾米莉亚，艾米莉亚吗】

知道了她的真名，让昴的内心像是生了翅膀一样轻松。

当初，昴立马就知道了她说得名字是假的。同时也知道了她——艾米莉亚，为什么要对昴报上莎黛菈这个假名。

因为，如果有银发的半精灵自称莎黛菈的话——，

【那当然，就会怀疑和这群人有关系然后原理她了。为了让我原理危险，特地用了苦肉计。一脸可爱的样貌，还真会做些可爱的思考啊】

一边寂寞地诉说着自己是半精灵，害怕自己会被疏远，又为他人考虑反而利用这一点，来让他人远离危险。

何等的惹人怜爱，惹人疼爱的孩子啊。感觉自己的胸口都绞痛了。

就在这时——，

【——菜月·昴！宠爱的信徒！你在这里吗！？】

【————】

尖锐得就仿佛是鸟儿被勒紧脖子发出的难听叫声想起，叫着昴的名字。

昴对这道声音皱起了脸，他把在王都撕下来的看板放在床上，不情不愿地打开门，走出个人房间。

房间外的空气很冷，是一片昏暗的空间。这片空间里回响的不仅仅是那难听的声音，还有慌张的靴子声。

然后，在昴靠在紧闭的房门上等了一会儿后，一位脸色苍白显得很不健康的男性摇摇晃晃地走过仅有微弱灯光的廊道出现在眼前。

这位男性见到昴，双眼瞪得眼珠子都要跳出来了。

【我在找你！为何、为何、为何在这种地方贪图怠惰！？我等！明明！必须勤勉地，遵从魔女的引导，回应这份爱才啊啊啊啊！】

【找茬就算了吧，培提先生。我只是遵从【福音】的指示而已，【福音】命令我在这里度过】

【为何！【福音】竟要你做这种事！？在这段时期，这个机会，这种状况下，为何让虔诚如你的信徒放任游玩，魔女到底在考虑什么，卑贱如我甚至！甚至！无法揣度吗】

烦人的怒吼，而且身体动来动去的也很烦。

在这位真正的狂人——培提尔其乌斯·罗马提空提的面前，昴好不容易才忍住叹气的冲动。

虽然昴对这位狂人并无好感，但他毫无疑问很有利用价值。

毕竟，被昴吸引过来的这个集团不管哪个都是只顾自己的自私主义集合体，而一般的教徒甚至有没有自我意识都惹人怀疑。

一般教徒的感情色彩稀薄或许是为了不在日常生活中暴露自己所以用什么方式对意识加以干涉了吧，这是昴自己的推测。

总之，这种考察不考察都无所谓。重要的是，拥有远超一般教徒权限的培提尔其乌斯来这里的目的。

这两个月，昴在被包括培提尔其乌斯在内的某个集团接纳头，姑且自由地生活了过来。

不过，生活上是没不自由，但是行动和精神上全都是不自由。

特别是在这里到处都能碰上狂人、狂信者之类的人，这让至始至终都抱有常识人性的昴只感觉到痛苦。

他现在住的地方，是山中某处的隐藏洞窟。

住起来意外的舒适，自己甚至还被单独配了一间房，但是距离人烟很远，坚硬的床铺和冰冷的四壁也让习惯现代生活的昴很是难受。

不过，他也没有好到能够在外面不暴露和他们之间的关系的演技。妥协一下住在这里，倒是有利于积攒一下这个世界的知识。

【那么，你找我这个过隐居生活的人有什么事？】

【你不知道吗？这个国家，此刻正要开办的愚昧活动！】

【国，从这个词来看……是说王选？】

【正是！王选！但是，问题不在这里！重要的不是王选，而是参加王选的那个存在！即，银发的半魔！】

【————】

或许是为了教导不谙世事的昴，培提尔其乌斯把王选的公告——也就是和昴装饰在房间里的那个一模一样的东西拿了出来。

那上面的当然是让昴望眼欲穿的可爱少女的脸。培提尔其乌斯用他那皮包骨的指头指着那个少女的脸。

【看！穿着！出身！正可谓，对魔女的冒渎！这对我们来说是不可忽视的存在！此刻，正是试炼之时！】

【试炼】

【正是！！】

培提尔其乌斯高声叫道，把公告的那张纸拍到洞窟的石壁上。然后，一拳砸倒艾米莉亚的画像上，血沫四溅。

喜好自残的狂人沉醉于疼痛与鲜血，亵渎着画在纸上艾米莉亚。

【善则拥！愆则除！是否拥有与魔女相应的器量，若是有则收入我等挥麾下！必须要，进行这个试炼！】

【所以，要我来帮忙？】

【诶诶，正是如此！虽然也向其他人说过了，但是实在难以想象那群不虔诚的家伙会予以回应！唯一，有可能的【愤怒】，现在又离王国十分遥远……因此！仅凭我们也必须去！】

培提尔其乌斯泪水滂沱而下，心怀着使命感，把染血的拳头不断压进自己的口中，啜饮着伤口。嘴边开裂，门牙刺入手背，这幅伤筋动骨的自残光景凄然得令人难以直视。

但是，昴告诉自己要用铁的意志撑过去，他装作淡然地说道。

【那么，只要一起去就好了吗？我还什么都不懂啊，司教大人】

【能够屈尊同行吗！啊！呜呼！这是何等何等何等何等何等等等等等等等等等……令人欣慰啊！】

【只是说一起去而已太夸张了】

这次的苦笑是真心的。

不过，培提尔其乌斯听到昴积极的回答，一次又一次以不惜把头摇下来的气势点着头，然后猛然态度一边双脚并拢，转过身去，

【立马，出发！我指示的【指头】已经在路上了……各自汇合，前往梅瑟斯领。届时，遵从【福音】的引导！】

【了解。……说起来，试炼是要做什么？】

【会感到疑问也是当然。这是要测试是否有与魔女相应的器量……即，测试容器到底有没有收容魔女灵魂的强度、质量、以及最重要的资格！】

对着这个毫不具体的说明，昴装作理解地点了点头。

虽然不知道详情。但是，和当时还不知道莎黛菈=艾米莉亚的烦闷时候比起来，已经要好很多了。

而且这次的事情，似乎又能让自己和艾米莉亚挂上关系了。

只是，为此——，

【——那么，那么那么！那么那么那么！走吧！去测试！若是此次的器可用，则让魔女再度将于此世！这是，我等数百年来，终于等到的补全所有席位的机会！】

【如果魔女莎黛菈降世的话，身为容器的人会……】

【会高贵地牺牲！但是，这是光荣！如果可以我都想与之交换！如果付出这个身躯能够让莎黛菈的满意的话，不管来几次，不管多痛苦都能忍受，只希望能够迎来再会之时！】

【是吗，会消失啊】

在狂乱着踏出步子的培提尔其乌斯身后，昴低声说道。

这声私语是如此的轻微，根本没能传到沉浸在自己的世界里，放声大笑的培提尔其乌斯耳中——。

【诶，是这样啊】

——狂人没能注意到，菜月·昴那十分阴邪的笑。

※　※　※　※　※　※　※　※　※　※　※　※　※

剑身，插进瘦削的身体里，拧动。

剑尖上传来的手感，有种将宝贵的性命撕扯殆尽的感觉。

对于这份空虚，他略微颤抖着叹出口气——，

【就算我说这么说或许你也不会信吧】

【为、何……】

【培提先生，在我讨厌的人里还算是好的啊】

因为惊愕而怒睁的双眼，正绝望地俯视着近在眼前的黑瞳。

然后就这么怀着无法释然的震惊，缓缓向后倒下了。昴拔出剑，用踩风箱的感觉重重一脚踩下，深呼吸一口气。

他的脚下，是倒在血泊中的培提尔其乌斯·罗马尼空提。

是被昴直接用手破坏了心脏，如今正在苟延残喘的培提尔其乌斯。

【努力筹备这一切到今天，辛苦你了。你假装是脑子有问题，结果考虑方式也太面面俱到了。说实话，真的让我头疼了好多次】

【你在、说……什么，啊……？】

【是在说我为了走到今天这一步究竟试错了多少次。哎呀，作战本身虽然也很强但底牌也是真的太强了啊。真的，让人叹息啊】

培提尔其乌斯硬是驱使着自己无法动弹的手脚在地面爬行。然而，他已经没有站起来反击的余力了。充其量就只是在为了远离死亡，向后挣扎而已。

哪怕就是什么也不做，培提尔其乌斯也命不久矣。

【最开始连【不可视之手】都看不到，都要急死了。【指头】的处理也一度是个困扰……现在，总觉得充满了成就感】

【咕，呜呜，呜呜呜……】

流淌的鲜血，正表明着培提尔其乌斯剩余的生命。

然而昴别说为他止血，他望着出血势头不止的培提尔其乌斯，以幕后黑手的感觉诉说着至今的计划。

操纵看不见的黑色手掌的【不可视之手】。

培提尔其乌斯的心腹，甚至是他备用肉体的【指头】。

然后，通过向备用肉体转移附身，从而续命的【凭依】。

他利用这些能力，将挂在嘴上的【勤勉】化作行动试图把艾米莉亚逼上绝路，昴为了阻止他真的是操碎了心。

为了做到这一点，实际上已经重试了超过400次了。

【所以，你毫无疑问是我在这个世界说过话最多的人啊。虽然只是我单方面的，但我甚至感觉到了友情一样的东西。一心向着目标，将自己拥有的手牌全部打出去战斗到最后，你这种努力的样子让我甚至都感动到了】

【你在，说……什么、什么、什么什么什么什么什么么么么么！！】

正在不断走上黄泉路的肉体，还有着能够最后类似愤怒的气力。培提尔其乌斯激将这份感情完全注入自身的存在，令濒死的身体坐了起来。

吐了口血——就如字面所说，吐出了满嘴的鲜血，他瞪大了赤红的双眼冲向昴。

【背信者！背叛了魔女宠爱的背叛者！不可饶恕，不可饶恕，不可饶恕啊啊！！】

培提尔其乌斯吼叫着，伸出满是鲜血的手臂。

这并不是为了发动【不可视之手】。能够被看得一清二楚的不可视的手臂没有任何意义。在这里，培提尔其乌斯能够赌的手段只有一个——。

邪精灵培提尔其乌斯·罗马尼空提，要夺取肉体需要满足一定条件。

对于拥有精灵术士资质的人类，要【凭依】上对方的肉体需要一定的步骤。

而，在场的人里满足要求的人只有一个——，

【你的、身体——！！】

昴面对意欲夺取他肉体的培提尔其乌斯，轻声叹了口气。

然后，慢慢地正面走上前去，一脚踹到了拼命的培提尔其乌斯身上。被昴全力一脚踹飞门牙的向后倒去的培提尔其乌斯惊愕不已。

他没能附身得到本应满足条件的肉体上去。

而给了他回答的不是昴的话语，而是其抬起的左手——昴指尖上那一点微弱的红色光辉正在说明着这一点。

那是被称为微精灵的存在。

它和拥有精灵术士素质的菜月·昴结订了契约，是个仅能照亮昏暗道路的可爱道具。

邪精灵培提尔其乌斯的【凭依】，只能够附身到尚未契约的精灵术士肉体上。

而不知昴为了看穿这一点，到底死了多少次。

【人生最长的三天啊。对你来说，或许其实只是短短的时间……】

【菜月·昴哦哦哦哦——！！】

【把艾米莉亚定为目标。——给我永远地后悔下去吧】

昴一脚踹到憎恨地吼叫着的培提尔其乌斯胸口，想着他仰面的脸部挥下了剑。剑击毫不留情地刺入培提尔其乌斯的头盖骨，把他的大脑连带着性命一起破坏了。

难听的临终惨叫安静了下来，昴靠在刺穿了培提尔其乌斯刺到地面的剑上，长长地叹了口气。

在实际经过很短，主观上却是如此漫长的时间之后，和培提尔其乌斯之间的战斗终于迎来了终结。

成就感和虚脱感一同袭来。

【啊啦？这边似乎也已经结束了呢】

就在昴沉湎在沉默中过了一会儿，一道声音传入他的耳中。

转过头去，只见一道巨大的黑影分开茂密的丛林——一头披有黑色体毛，拥有狮子的头部，长有凶恶四肢的凶兽迈着沉重的步子走了过来。

当然，这声显得有些慵懒的语调并非凶兽的声音。而是跨坐在它的背上，以不合年龄的娇媚眼神望着昴的少女。

【啊啊，解决了。多谢你的帮助，梅莉】

【道谢就算了哦。报酬都拿了，哥哥也关照过艾尔莎。但是这样好吗？这些人，不是哥哥的同伴吗？】

【哦是吗。如果最后他没打算杀我的话或许只是年龄差距有点大的朋友，但他还是打算杀我了啊。虽然很可惜但算不上是朋友了吧？】

昴用袖子擦擦沾到脸上的血，对少女——梅莉耸了耸肩。于是，听到昴的话，梅莉手指指着自己的下唇。

【嗯——。那么，因为我没打算杀哥哥，所以就是哥哥的朋友了？】

【从这个道理来看是的。我和你是朋友呢，梅莉】

【哇，太好了哇。这样，加上佩特拉她们就有很多朋友了呢】

梅莉握着自己的双手，在凶兽的悲伤欣喜地晃着身体。昴对她孩子气的态度一挑眉，听到她说有朋友而吃了一惊。

【欸，真意外。虽然这么说有点那个，但你是有朋友的啊】

【是的哦。不过，她们都已经被我杀掉了】

【————】

梅莉微微地笑着，毫无罪恶感地说道。

说是杀掉了，那也就是说是和工作有关系的人了吧。一时之间还以为梅莉也有孩子气的一面，结果还是伦理观扭曲的样子。

毕竟是那个艾尔莎的妹妹，这也不是什么怪事。

【不管怎么说，梅莉能够补上缺人手的地方真是帮大忙了。要不然，就我一个人要杀光到处潜伏的【指头】是不可能的啊】

【这倒是没什么。不过，不特地找我们也没关系的吧？拜托一下国家的骑士就好了吧】

【那样的话我的目的就有一部分没法实现了】

【目的？】

梅莉歪着头，尝试读出昴的想法。但是，昴也没有再多说的打算，随意地笑了笑。

【这里开始就是大人的事情了。像梅莉这样的小孩子不用知道】

【啊！就知道这样把人当小孩子！不管哥哥了，不管了不管了，不管了！】

梅莉生气地闹了起来，受到她愤怒的影响凶兽开始发出低沉的吼声。

一不小心在这里挑衅到凶兽了。好不容易经历千辛万苦杀死了培提尔其乌斯，可不想失败在这里。

必须要做点什么让梅莉心情好转才行，于是昴费尽心思，努力逗少女开心。

※　※　※　※　※　※　※　※　※　※　※　※　※

在王选开始之后过了好几天，鲁古尼卡王国的版块发生了巨大变化。

首先最大的变化，就是被视作王选最有力候补的克鲁修·卡鲁斯坦公爵的落败——不过，了解到这件事的只有昴而已。

要说为何，克鲁修这一人物已经不复存在于这个世界上了。【存在】过的事实被尽数泯灭，世界被改写成了她不存在的样子。

为此，王选变成打从一开始就只有四名候选人，支持卡鲁斯坦公爵的人们记忆也都遭到篡改，和其他不同的势力组到了一起。

【白鲸的雾还真可怕。居然能消除别人的记忆】

只是，为什么这只对昴无效还是个谜。但是，因为昴自己并不觉得有什么改变，所以在和别人说话的时候总会发生龃龉就很麻烦。

消失的克鲁修·卡鲁斯坦就别管了。

无谋地去挑战力所不能及的强敌导致身败名裂的人，是不会有东山再起的机会的。

在这个世界，能有这个机会的只有菜月·昴。

所以，自己注意别重蹈战败者的覆辙就好了。

除了这种对于昴以外的人毫无意义的变化外，还有别的变化。

那就是——，

【王选候补人，艾米莉亚。将常年让世界出于水深火热的邪恶之徒，魔女教大罪司教【怠惰】讨伐了……！】

这个通告让王国上下沸腾了，功绩甚至被传到了其他诸国。

这种让昴都感到意外的宣传效果，都归功于菜月·昴将不惜死亡四百次拿到的胜利完全让给了艾米莉亚——让给了支援艾米莉亚的可疑男性小丑。

说实话，自己当时还不知道这位边境伯对这场转让功绩的交涉会采取什么态度，甚至做好了和讨伐培提尔其乌斯同等的打算——，

【话好说的都让人觉得恶心啊】

边境伯，罗兹沃尔·L·梅瑟斯接受了昴的请求，当即允诺，然后立马将讨伐培提尔其乌斯的功劳当做是艾米莉亚的功绩发表了出去。

他的态度让昴疑神疑鬼，但昴也不会过多追究他的行为。

本来，艾米莉亚就因为一些无聊的原因在这个世界为人所轻蔑。他就是以这样的艾米莉亚的支援者为名号，作为她的后盾推荐她参加了王选的。

这或许只是单纯的性格乖僻，或者只是想赌一赌万一艾米莉亚登上了王座自己能够尝到最大甜头这种下贱的心态吧。

对于培提尔其乌斯被讨伐的报告，饿虎扑食般地就过来了就是证据。

【算了。随你吧，边境伯大人。只要你还是艾米莉亚的同伴，我也会是你的同伴的。艾米莉亚会和你期待的一样，成为王的】

为此，菜月·昴会把颠覆【死亡】的这份力量发挥到极限。

但若是，罗兹沃尔对艾米莉亚抱有什么不纯的希望，怀有什么不该有的想法，到时候——，

【不过是为了艾米莉亚而设的墓碑，再多一个而已】

在那之前，为了自己能够在艾米莉亚不知情的地方暗中行动，只能把表面的工作交给罗兹沃尔。

相对的，底下的事情就由昴来出谋划策。

为此——，

【难得都捡回来了。要是一点忙都帮不上的话可就麻烦了。【青】】

【————】

洞窟的深处，有一个制作简陋的铁格子牢狱。

在这片冰冷的空间里锁拷着一位样貌有些脏的人物。这位少女——一样的男性头上长着亚麻色的猫耳，窈窕的身体上穿着的是近卫骑士的白色服饰。

这是昴在培提尔其乌斯死了，以及白鲸暴动了之后四处奔走的时候发现而带回来的战利品。

只是，至今为止都还没有那个机会能够一览被称为【青】的治愈术才华。别说机会，他甚至都不治疗自己的伤口，只是盯着牢狱的地板，不停地低声哭泣般的喃喃着。

【……有谁，能告诉我。告诉我啊。我，是为什么……殿下呢？我，是为什么。有人在的。应该是存在的。如果不是这样的话，好奇怪……】

【不过，这可头疼了。看来要花点时间了啊】

昴挠挠头，取出自己怀里的资料。那是王选开始时候的通告纸，昴一直贴身不离地带在身上。

那张纸和昴知道的有所不同。本应是五名候选者在上面的，但现在人物像变成了四个人，人物介绍也减了。

随着克鲁修·卡鲁斯坦的消失，这边也出现了变化。

但是，昴还记得。虽然没放在眼里，但毕竟是看到望眼欲穿的程度了。克鲁修·卡鲁斯坦的骑士的名字，是菲利克斯·阿盖尔。

本应是眼前这位【青】之治愈术师。

【在我看来，被白鲸的雾消去以后，本来应该会给记忆造成没有违和感程度的影响的，但看这个样子】

【有谁，有谁能告诉我啊……殿下，殿下呢？殿下，是和谁一起……？】

【当失去的记忆重要到没法修补的时候，就会变成这样吗】

如果是能够对当事人的人格造成了巨大影响的存在，一旦消失，那个人当然就会难以维持自我。

因此，【青】就变成了这幅样子，像个坏掉的人偶一样不断说着重复的话。

如何治愈坏掉的心，很遗憾昴并不清楚。

能够让他保持自我的唯一存在，和昴之间并没有任何交集。哪怕要重来，回溯的时间也不是昴定的。

所以，他和她之间到底发生过什么事情，昴无从得知。

【就算是这样，毕竟是好不容易才找到的棋子。没关系的。我一定会把你内心的裂痕填上的】

【有谁，求求你了……告诉我。我，我为什么……】

对于昴的话，【青】没有给出任何反应。

虽然感觉这样下去也不是事儿，但昴已经做好觉悟，不骄不躁花上充分的时间来面对他了。

能够治愈伤势，失去倚靠的骑士，没有比这还要好用的棋子了。

所以，昴满怀真挚地，

【这次，绝对会找到不让你自杀的方法的】

断言道，不管几次，都绝对会正面接受他寻死的意志。

※　※　※　※　※　※　※　※　※　※　※　※　※

房屋的出入口被完全封锁了。

被从内侧被钉死，窗户也全都用木板封死。因为窗帘紧闭而显得一片漆黑的宅内状况，只要有还能察觉到异样的注意力都会觉得奇怪。

不过，当然这次就是因为确信不会被察觉到所以才设计的。

【——！】

猛烈的火势毫不留情地吞没了整栋建筑，将其烧毁。

在房屋四处出现的火苗不知休止，建筑物上下都在无法阻止火势，一切都在疯狂地化作灰烬。

被火焰吞没的豪宅里有的并不仅仅是被烤焦发黑的家产家具和装饰品。

在这栋屋子里经受了长期苦痛的女性们，也被卷入火焰失去了性命，变成了看不出原来是否为人的灰碳。

这过于凄惨的景象，说是作孽都不为过。

但是，又有谁能相信，这正是这些被烧死的女性们自身的愿望。

【开、开、开什么玩笑！！】

火舌的势头在风中进一步剧增，男性的骂声传遍宅邸。

在几乎被烧毁的这栋建筑中，这个声音嘶哑地让人觉得可怜。

这道声音还无法相信眼前的一切，还因为眼前发生的一切陷于狂乱，

【九十二号！一百十四号！一百二十三号也行！在哪里！？你们在哪里！？你们当我是什么人！？居然留下我，在这种情况下自顾自死去，你们这些女人到底要不负责任到什么地步！？】

白发的青年就仿佛是发脾气的孩童一般，失声叫道。他穿着白色的衣服，平凡的面容怒若罗刹，肆意叫唤着。

这在如今被快被烧毁的豪宅火焰中也堪称异常。

若是正常的人类，应该会为了逃离火势而拼尽全力。

然而，这位男性却完全不见如此。反而完全没有考虑自己的死，以某种超越了生死的伦理观在行动。

男人的脑子出问题了，也不是。

——不对，否定这一点也是不对的，男人只是有着某种确信。

自己，不会因为这场火灾而死去。

因此，男人怒吼的理由是出于于自己的死亡完全不同的原因。

非要说的话，是对引发这场意外火灾的自己妻子所抱有的无边怒火。

这份怒火，使他看不见眼前的局势，看不清自己的脚下——，

【不管是哪个，都在轻视我这宝贵的资产——】

【——希望，你能闭上那张听起来就让人难受的嘴啊】

【什】

愤怒男性的脸面，被一个穿破焰壁的靴底直接踹中。

这一脚来自于出乎意料的方向，着出乎意料的攻击让男性应接不暇，被轻松踹飞到走廊的另一侧。那边的墙壁因为炙烤变得过于脆弱，在男人的撞击下崩塌了。

男人摔了个大跟头仰躺在了地上，哑然地望着燃烧的天花板。

【怎、么了……】

【这个火焰，就是你那众多老婆们给你的绝缘信签名。说的通俗一点，用恐惧束缚起来的爱情已经结束了】

回答了呆若木鸡的男性的问题的，是和刚才踹他时候相同的声音。

男人弹起身体，越过撞碎的墙壁，正好见一位身着漆黑衣装的女性走了进来。

嫣然的微笑与黑色的麻花长辫是她的特征。

但是，最能说明她身份的，还是她右手上的弯刀——。

【贼人！你以为我是谁！？快为你做出的蠢事后……】

【悔】字出口的同时，男性就举起双手向女性发动了攻击。

然而，这个打算因为一道轻巧的冲击，和视野角落看到的自己被切断了的双臂而受挫。视线向下移去，只见自己的双臂已不复存在。

无法、理解。到底，发生了什么。

【不死之身？无敌？虽然不知道你是哪边，不过这个只要知道内幕就根本不成问题。现在的你，只是会惹人不快的虫而已呢】

【——！像你这样的，娼妇——】

【————】

被刺伤了尊严的男人忘记了自己失去的双臂，用污言秽语詈骂女性。然而，女性却不会等他说完。

她抬起纤长的脚，一脚向上踹中一屁股坐在地上的男性两腿之间。男人的身体因为其威力而浮了起来，而女性手中的刀刃不知何时开始描绘起死亡的纹路。

自双臂之后，其上的肩部亦被切断，再从脚底开始一点点向腿上剥削。脚尖，脚踝，小腿，膝盖，大腿，男人的身体喷着血不一会儿便化作凄惨的肉块。

【——你以为】

【都这样了，还打算说什么可正了不起】

对于他那变得越来越小的躯干，女性一直踢踹了出去，被木板钉死的窗户被装个粉碎，男人的身体带着火焰飞向宅邸外。

失去了手脚的男性随着破碎的窗户玻璃碎片一起，甚至无法受身直接摔在了地面上。幸好他所在的房屋只是二层，摔下来并没有造成致命伤。

不过，在失去了手脚的现在，光是大量失血就已经是个足够致命的问题了。

【怎么，能忍受这种蠢事。……我，我是这个世界，最完美的存在。不求过多，知足常乐，无欲无求，生活清贫……这样的，我，居然被你们这样缺陷的人类，肆意妄为……】

【平时就被骂的这么狠的话，那肯定是会想要提出离婚申请的呀】

【什！？】

在连靠自己翻身都很困难的男人面前，又有别人进入了他的视野。

他是谁呢，正是黑发黑瞳，披着黑色披风的少年——菜月·昴。

昴对这位目中无人到令人觉得悲哀的男性叹了口气。

【没想到，周围的人居然会协助我到这个程度啊，雷古尔斯先生】

【你，为什么在这里……不对，是你，计划的吗……？】

【还能有谁？】

昴耸耸肩，这才终于理解了状况的男人——雷古尔斯面对昴扭曲了面容。被昴的笑容俯视，雷古尔斯的眼里出现了暴怒的火焰。

【你这个、杀千刀的混蛋！你知道，自己都干了些什么吗！？我爱的妻子，妻子们啊！在我的面前，和屋子一起被烧掉了！你知道这行为有多么非人道，多么恶魔吗！？你这个杀人妻子的混蛋！】

【这种说辞可真是出乎我的意料，让我都惊讶的合不拢嘴了啊。……先说好，帮我出谋划策处理你的心脏的不是别人，正是你的妻子哦？】

【——怎么、可能】

对于昴挖着而说一脸无奈说出的话雷古尔斯哑口无言。

他这种打从心底表示意外的态度反而让昴感到难以理解。

雷古尔斯将众多的女性以妻子的名义关在屋子里，用反抗即死的暴力威胁她们过着自我满足的婚姻生活。

只是这样的话，还只是狠毒的后宫主，但这位大罪司教的行径之可不止于此。他，把自己的【心脏】交给妻子们，以此来让让自己肉体的时间静止从来实现不老不死和【无敌】的凶恶之人。

要杀死大罪司教【强欲】，只能在他的心脏回来的时候。

为此，必须要把他交付心脏的妻子们全部杀光，让他的心脏失去藏身之所。

在得知这个事实的时候，就算是昴都苦恼了好一阵子。

不过，解决了昴这份迷惘的，不是其他人正是被雷古尔斯囚禁的妻子——不对，女性们。

【她们，都觉得只要能报一箭之仇死不足惜啊。像你这么过分的骂法，我都不太听过啊】

【谁、信你……。我，我爱着妻子们！所以，她们也应该爱我！是这样吧！？要不然，就不对了吧！但是！为什么我，要因为那群不配当妻子的人，落得这幅模样！】

【……你是真心这么说的吧。还真恐怖啊，你们】

昴一副想要抽身而退的模样低声道，从现在还在不断谩骂转嫁责任的雷古尔斯身上错开了视线。

他视线望向的是从燃烧的屋子里跳下来，在中庭着地的黑影——艾尔莎。她轻轻拍落沾到身上的灰，随后注意到了昴的视线，

【啊啦，是在担心我吗？安心吧，没有一处受伤】

【才没担心你。比起这个，这是什么。我可没让你搞成这幅恶趣味的模样】

对于态度悠闲的艾尔莎，昴别着嘴，指着没有手脚的雷古尔斯说道。

至少在昴见到雷古尔斯的时候他还是有手有脚的，那把他变成这样的肯定就是艾尔莎。对于昴的指责她耸耸肩，

【因为让他留下手脚感觉会很烦……而且，还是帮那些人传个话比较好吧？】

【……这、倒是】

艾尔莎似乎也意外地会为人着想。

那些因为雷古尔斯而牺牲的女性们，究竟是抱着怎样的觉悟向雷古尔斯设下这个陷阱的。可不能让他在对此一无所知的情况下死去。

然后，既然这件事已经传达到了——，

【嘎，啊啊啊啊！】

艾尔莎将军刀刺进雷古尔斯的胸口，举起他那已经变轻许多的躯干。在这就仿佛烧烤串的状态下，雷古尔斯流着血挣扎着，充满了对生的渴望。

【一口气？】

【不……】

对于艾尔莎的询问，昴手抵着额头思考了会儿。

虽然不是艾尔莎，但昴也有一般人该有的同情心和义愤。而此刻这份感情，正在向他诉说要回报那些流着泪奔赴死亡的女性们的觉悟。

所以，昴对艾尔莎命令道。

【把他放到那边小火的地方。直到确认他被烧死了为止】

【好的，知道了】

对于昴残酷的只是，艾尔莎毫不苛责地答应了。

然后，她将还在说着狠话的雷古尔斯的身体扔到了燃烧的屋子旁只有一点小火的废弃木材的小山上。

【————】

身体被灼烧直到死亡的男性惨叫在夜空回响。

昴和艾尔莎一同面不改色地望着这一切。

【虫子的叫声听起来很舒心，反而还更好听啊】

在漫长的惨叫声结束之后，艾尔莎轻声说道。

昴对此也是同感。

※　※　※　※　※　※　※　※　※　※　※　※　※

——碎裂的玻璃杯声音，在昴听来是信赖散落的声音。

【这、是……】

【对不起喵。真的对不起喵。我也不想这么做的。真的，真的哦】

男人的声线因为震惊而颤抖着，他的手肘重重地靠在柜台上。然而，却仍无法支持住自己的身体，从椅子上滑了下去倒在了店的地板上。

在他倒下的时候，柜台上的玻璃杯和酒瓶子也一起被摔倒地面上，摔碎的酒水溅到了男性白色的制服上，让他身上染上了酒臭味。

他的手脚不听使唤，脸上渐渐失去血色。唇色发青，视野浑浊，男人不停地眨着眼，尝试远离近在眼前的死期。

昴坐在桌子旁俯视着这个男人拼命挣扎的模样。

这是一位面容优美的男性。纤细的高挑身材，在进入店里时候的举手投足，在和友人说话时候的遣词措句都充满了高贵的气息。正可谓骑士般的骑士。

【难怪被称作是【最优】啊，尤里乌斯·尤克里乌斯先生】

【你，这混蛋是……】

【但是，如果你知道自己现在的立场的话，还是再多关注一下周围比较好啊。你可是现在正处于风尖浪口的王选候补者的一位骑士呢。当然，要考虑会被盯上的不仅是主人，还有自己嘛。不过……】

昴对痛苦地喘着气的男人——尤里乌斯高声诉说着，随后站起来伸出了手。而伸向的是坐在倒下的尤里乌斯身旁的人。

昴轻轻搂过带有亚麻色猫耳，面容可爱身体骄奢的可人肩膀，抚摸着他的头。仅仅是如此，【青】就一脸陶然地喜上眉梢。

【菲、利斯……你……】

【要安慰伤心的人可是费了我好多工夫啊？没想到，居然要为别人的性命操心到这个地步。不过毕竟是值得的】

【你，到底，打算做什么……】

【这已经和你没关系了。安心吧。在我的计划里，只要你不在了，就不需要对你的主人加以危害了。不过如果要反抗的话就不好说了】

尤里乌斯的黄色双眸不断闪过疑惑与愤怒、悲伤与混乱、哀叹和疑念。

但是，这些高速转换的感情全都没有任何意义。

【被昔日的朋友叫出来，喝了一杯酒就变成这样。所谓信赖还真是一种甜蜜的毒药呢，【最优】先生。你沉溺其中，然后看错了局势】

【……啊，唔】

【做一些能够为之骄傲的事情还真轻松呢。活的那么轻松我好羡慕啊。虽然会死】

昴蹲下身子，王者意识朦胧的尤里乌斯的表情。尤里乌斯的眼里早已没有昴了。他并不会为了指示杀死自己的男人而拘泥。

他的双眸中唯一有的，只是对被利用的友人是否能够平安的担心，以及对不在场的主人的遗恨——，

【————】

【到死都是骑士啊。简直可恨得不行】

昴俯视这因为死亡而永远陷入沉默的这张脸，放言道。

唯一让他内心感到作呕的，就是完全没有必要在这里夺取【最优】骑士的性命这件事。

昴第一次做出了没有任何理由的杀人命令。

在让魔女教和大罪司教那群人死的时候，昴不会有任何心痛。但是，这次的杀人只是昴单纯出于难度选择了更加容易解决的那一边。

比起时时刻刻都有护卫包围的候补者阿纳斯塔西娅·霍星，还是利用一下不太被警戒，而且被自己用话语笼络导致依存自己的【青】更方便。

【昴大人，我干得不错吧？】

【做的好。抱歉让你做这么难受的事情】

在看到尤里乌斯死透之后，【青】在站起身的昴身旁细声问道。对于他的态度昴耸耸肩，再次抚摸了表情不安的他的头。

仅仅如此，就能让他情绪不安定的内心冷静下来的话，摸多久都可以。

【没关系的，只要能够帮上昴大人的忙就可以了。因为，这是为了造就殿下和昴大人所期望的未来不得不做的事情对吧？】

【啊啊，是啊。为了这个目的，不能让你的朋友活下去】

【是……】

【青】的脸上表情色彩变得稀薄，即便如此还是对朋友的死亡感到心如刀绞，他就仿佛要填补内心的空白一般，轻轻揪着昴的袖子。

就这样，店内漂了好一会浓厚的死亡气息后，

【——哦呀，看来还忙着吗？】

本应谁都进不来的入口被打开，一名美少年进入店内。

正想着被撞见了现场如果是无关人员就需要封口了，幸好，这名美少年并没有封口的必要。因为是有关系的人。

【和说好的时间一样啊】

【是啊。时间有限，商人的思考方式就是【时间就是金钱】】

【还敢自称商人，脸皮还真是厚啊。是【死之商人】吧】

【你这么说我也无话可说】

听到昴的话，身材瘦弱的男性挠了挠灰色的头发。

纤瘦的身体上穿着黑色的西装，还带着黑色的领带，一眼看去感觉就像是葬礼归来，但细细一看反倒是他的身上不断传来无法蒙混过去的死臭。

面部表情很是温柔眼神也很祥和，但视线的移动方式很明显正在警惕着昴他们，可以看出是经历过修罗场的人。

最关键的是，昴对他那浑浊的眼神很中意。那是没有任何生存价值，失去了生存意义，即便如此还是选择了活下去的行尸走肉的眼神。这个眼神，和自己身边的【青】性质相似。

【说起来……还没问过你名字吗】

【我没自报过名字，也没打算报上自己的名字。当然，这边也没打算问客人们的名字。这样才能让双方都安心】

【嘛，你说的倒是没错。又不是说能成为朋友】

【是啊。一旦发生什么立马就会变成敌人。和这种人称朋道友的结果就是这个下场吧？】

男性望着趴在地面的尤里乌斯的尸体和靠在昴身上的【青】揶揄道。对于他的讽刺昴无言以对，随后向店门口走去。

毒药和善后都已经和这个男人在私下商量好了。如果动用魔女教事情会变得很麻烦。昴现在，正一次又一次地走在危险的钢丝上。

【代我向拉塞尔问个好。有事再来找他。是右手吧？】

【那个人右手还在拉。我，只是个奴隶】

这种思考方式倒是干脆，对于男人这种现实的回答不管是在好的意义还是坏的意义上昴都很喜欢。同时也感觉很遗憾。

如果能够成为朋友，一定会很谈得来吧。

※　※　※　※　※　※　※　※　※　※　※　※　※

除去候补者，除去挡在面前的大罪司教，为此不停在幕后进行各种活动。

谜之集团，危险人物的巢窟，不仅如此还对内部的事情不会有过多干涉。

这个名为魔女教的集团，对昴来说实在太适合藏身了。

总有一天要根绝的藏身之处，因为是以此为前提对其进行利用，用完就丢也完全不会感觉到罪恶感。

大罪司教之间，也完全没有同伴意识。

昴一直虎视眈眈，思考着杀死他们的方法，然后尝试，如果有机会就着手准备。而若是失败，反正昴有能够让世界重来的力量。

而这种状况下，昴也不知不觉间，有了能够称得上是伙伴的人。

这不是魔女教中的任何一个人，昴也知道不该牵扯更多人进来。

【我和哥哥，不是早在一开始就在一起做事了吗？就这样继续，再多找点有趣的工作让我帮忙吧】

【我也没打算站在你这边，你现在也是想着一有机会就杀我。但就是这个，莫名让我觉得很舒服啊】

【只要有昴大人在，殿下的梦想一定会实现的。所以，我会一直跟随昴大人的。……但是，诶？殿下和昴大人，是什么时候在哪里认识的呢……】

【不过是肮脏工作的同事吧？说是伙伴真蠢。不管是我还是你，都是无颜面对家族的不孝之子啊。干脆，还是直接去死更加轻松吧】

【再一步，就差一步就能达成夙愿了。为此，我就是把灵魂卖给恶魔都无所谓。卖给你这个，恶魔呢】

——昴绝对并不会认为自己的所作所为值得褒扬。

即便是这样，不知何时也出现了一些赞同他行为的人。

或许，这就是所谓的救赎吧。

昴利用【死亡回归】的力量，尝试拯救艾米莉亚，为此而不停挣扎。

这场战斗只能自己一个人，不停战斗下去，自己曾经是这么想的。

说不定，不知从什么时候起，自己，不是一个人了。

※　※　※　※　※　※　※　※　※　※　※　※　※

王都四处都是火焰，昴感受着全身被碾碎的痛苦，仰头望着天空。

意识还很清醒。

剧烈的疼痛没有让昴失去意识反而让他清醒了。

到底发什么什么，为什么会在这里，全部都跃然眼前。

【————】

昴的怀里抱着不再动弹的梅莉的身体。

少女张开的眼中早已失去了光辉，正眺望着并不属于这个世界的景色。那副骄傲的态度，不合年龄的娇媚声音，每当被当成是孩子就会生气的模样，都无法再见到了。

——因为，昴【死亡回归】，回到的正是这个瞬间。

【死亡回归】虽然有改变过地点，却从未回到过比那还要之前的时间过。

【死亡回归】的地点变成了这里，回来的昴怀里仍旧抱着梅莉的尸体，既然如此，那么她的性命已经是救不回来了。

【————】

哪怕知道这不过是自己的心理安慰，昴仍旧轻轻为梅莉合上了眼睑。自己没有资格为死者送终。这双手，已经沾染了太多血污了。

【就算是、这样……】

不能只是因为看到了【死】，就放弃。

为了走到今天这一步，到底死了多少次了呢。早就成千上万，亵渎、踩碎了各种各样的人的生命，只为了实现自己的愿望，走到了这一步。

自己也有好几次因为【死亡】的痛苦而将近屈服。但每当这时，内心就会燃起火焰。

那是，最开始的炽热，是稍微触及到一些的指尖上传来的触感，就是这份触感让昴走到了今天。

就差一步，他的愿望就会触手可及。

在付出了众多牺牲之后，终于来到了这里。

然而——，

【——到此为止了】

凄惨的声音从昴的头上传来。

王都四处是火并不是比喻。然后，出现在斜坡上的那个身子闪耀的就仿佛要把这些疯狂的火焰全部吸收进去一般。

【莱茵哈鲁特·梵·阿斯特雷亚啊啊啊……】

【看来我没必要自我介绍了呢。我也没法控制住自己和你促膝长谈】

莱茵哈鲁特的碧蓝双眸笔直地望着蹲在他面前的昴。

他双眸中的光芒，和早之前见到的完全不同，充斥着激情。

哪怕是面对杀戮者的时候内心都未曾出现过一丝扰乱的男人，在面对昴的时候。

用充斥着难以言喻的浓厚激情——憎恨的眼神盯着昴。

【你也会憎恨人的啊，【剑圣】！】

【我也吓到了。没想到，自己的内心里居然会有这种感情】

【发现了新的自己吗。Happy birthday。生日快乐，莱茵哈鲁特】

【抱歉，今天不是我的生日。但是，会成为你的忌日】

这种说法让人感觉做作，但是由莱茵哈鲁特这样的美男来说就显得很有风范。

听到他的死刑宣言，昴笑了出来。

能够让他失去冷静，暴露出他心底的感情，明知这没有任何意义，自己却只有这点能够说得上是胜过他了。

【别惹我笑了，莱茵哈鲁特！【剑圣】！王国之剑！你，是守护鲁古尼卡王国的骑士吧！？你，哪里保护好这个国家了！？你说啊！】

【————】

昴伸开双手唾沫四溅地吼道。

两人在王城的正门前面对面，从这里可以看到王都的全景，四处都处在火焰之中——不对，不仅仅是王都。

现在，这道业火正在鲁古尼卡王国的全境内肆虐。

哪怕莱茵哈鲁特再强，是个再优秀的骑士，只靠他一个人又能做得到什么。什么也做不到。这就是结论。

【这就是，我送给你的礼物！为了杀死你，我准备好的陷阱！】

【为了、杀死我……？】

【你以为！我试图杀死你，试了多少次！？我以为，我到底挑战了你几次，几十次，几千次！】

【————】

对于昴意义不明的叫喊，莱茵哈鲁特的表情因为困惑而僵硬起来。

他不会知道。除了昴以外，绝对没人会知道。

昴为了杀死莱茵哈鲁特，早就尝试过各种各样的方式了。

他研究莱茵哈鲁特·梵·阿斯特雷亚这个男人，研究透彻，尝试所有能够想到的手段，使用各种策略，做了各种准备想要杀死他。

但是，不管采用什么手段，都会被莱茵哈鲁特尽数打回。就仿佛在说菜月·昴的小聪明，无法对他这个存在造成任何影响。

牺牲艾尔莎，牺牲梅莉，牺牲【青】，牺牲或许能成为朋友的那个男人，牺牲了自称共犯的小丑，牺牲了魔女教，牺牲了大罪司教，牺牲了各种各样不合法，非人道，邪道，即便如此，还是没能杀掉他。

所以，在失去了能够杀死莱茵哈鲁特性命的手段后，昴决定了。

【我，要把你从骑士层面上杀死。把【剑圣】这种夸张的招牌砸掉，用脚践踏，吐痰玷污掉！】

【就为了，这种事】

【就为了这种事！啊啊，是啊，就为了这种事啊！我就是为了这种事情，用光了我身边的人的命，来想要把你扯到地面上来啊】

昴让怀中的梅莉身体横躺地面，指着莱茵哈鲁特说道。

看到莱茵哈鲁特藏不住的动摇神色，感觉有点小得意。

【你是英雄，莱茵哈鲁特。我杀不死莱茵哈鲁特。但是，就算是我也能够杀死英雄。——这就是，杀死你的方式，莱茵哈鲁特！】

【————】

面对陷入沉默的莱茵哈鲁特，昴用卑贱的尖锐声音夸耀着自己的胜利。

殚尽竭虑，机关算尽，付出牺牲，血流遍地，重复【死亡】，这才终于。

在梅莉的保护下苟活了下来，这次终于，能够在这个状况下，和他对峙了。

付出了这么多牺牲，这才终于，和他站到了同一个舞台上。

【……为，为什么啊？】

突然，前一刻的威风尽数消失，透出了一声软弱的声音。

【为什么，你这么强啊？为什么，你强到，我必须要让他们全部死掉，才能触及的程度啊？】

昴的声音颤抖着，呜咽着。对此，莱茵哈鲁特表情僵住了。

他已经无法理解昴到底在想些什么了。这是当然的吧。因为连昴自己，都快要不明白自己了。

不知道自己为什么会哭。自己最后一次流眼泪，到底是什么时候。

想来，在来到这个世界的那一天，就是自己最后一次落泪的时候吧。

菜月·昴，在那天置身于这份火焰当中时候流下的眼泪，就是最后的泪水。

【如果我和你一样，该多好。和你一样，正直，有能够拯救一切的力量，该多好。我，好羡慕你啊。我，好恨你啊】

【你……】

随着泪水一起流出的话语，必定是菜月·昴心底真正的想法吧。

在王都最初重复的无数次循环里，在菜月·昴看到这位将自己从那个圆环中解放出来的男人，莱茵哈鲁特·梵·阿斯特雷亚的时候。

——那个时候，昴很羡慕莱茵哈鲁特。

一次又一次得被开膛破肚，一次又一次地经历了字面意义上的死，却还是无法对任何事情造成改变，内心渐渐枯竭，感觉就要死去，就在这时，就像是出于某种偶然一样，他就仿佛像只是踢开路边的小石子一样，轻松地将命运改写了。

这种强大，让昴憧憬，羡慕，嫉妒，憎恨。

【——我，想要变成你这样啊，莱茵哈鲁特】

【——我，没法理解你的心情】

对于昴发自真心的零散话语，莱茵哈鲁特当成是戏言予以了回答。

这是对的。莱茵哈鲁特，是英雄，你真的，至始至终都是正确的。

——是哪里错过了？菜月·昴，是在哪里做错了？

不知道。不对，是知道的。但是，谁都没法理解。

所以，正因如此。

菜月·昴，早就已经成为了无法他人所理解的狂人了。

【————】

莱茵哈鲁特眯起眼，微微弯腰。却没有伸手握剑。在他眼里看来，打倒昴根本不需要武器。

这是对的，这没错。昴这脆弱的身体，他只要一击就能将其灰飞烟灭。

那么至少，那么至少——

【——要放弃，会不会还太早了点？】

【你是——！】

就在莱茵哈鲁特冲上前来的瞬间，一道黑影从旁边横插进来。激烈的碰撞声响起，莱茵哈鲁特用手刀接下了黑影斩下的攻击。

怎么可能。为什么，攻势那么强的刀刃用手刀就能接下。向天空望去，只见刀刃发出一声脆响飞上去。怎么可能。为什么，是刀刃碎了。

【真的不是人呢，你】

在空中翻着身，最后四肢着地的人是浑身是血的艾尔莎。

昴以为她已经死了。为了造就这个状况她也成为了布局的一环，她自己也做好了在那里燃尽了生命之火的觉悟才对。

【似乎没能死成呢。不过看到这个状况，又想来死一次了呢】

【艾尔莎……】

【梅莉，是吗，已经死了啊。这妹妹真是没能遇到个好姐姐啊】

艾尔莎看到躺在地面的梅莉，表情有些寂寞地轻声道。

然而，她一瞬间就切换了情绪，和莱茵哈鲁特面对面，

【似乎还要加上杀妹之仇了，能陪我一起跳一支么？】

【你已经没武器了。而且，你不知道自己现在在保护的是什么人吗？】

【我不是很喜欢这种复杂的事情呢。我，只会做我想做的事情。身后的那个人，总是能让我做想做的事呢。所以，可是贵宾】

艾尔莎一舔红唇，用只有杀戮者才能理解的道理回答了莱茵哈鲁特的问题。

莱茵哈鲁特做好准备，面对艾尔莎摆出了架势。

【这回，想必是最后的机会了呢。我很开心呢。真的，太棒了】

【艾尔莎！我……！】

【永别了】

这很有她平时的风格，完全不给这边任何思考的时间就干脆地告别了。

下个瞬间，艾尔莎就仿佛俊敏的野生动物一样向莱茵哈鲁特跳了过去，英雄和杀戮者的剧烈战斗就此展开。

这是短短时间内就会结束的，艾尔莎·古兰纳西尔特最后的血腥盛宴。

【——可恶！】

还不能死在这里。

昴背对艾尔莎的战斗和梅莉的尸体，向坡下跑去。

身后远远地传来激战的余波。

燃烧的王都里建筑物一个接一个地坍塌，化作四处悲鸣的地狱。这是地狱，四处可听闻死的呼唤，子唤亲，亲唤子，男唤妻，女唤夫。

对，这就是昴制造的地狱。

制造出这个地狱，打碎莱茵哈鲁特的虚像，以此来达成目的。

然后——，

【你、你是……】

【————】

脚下被绊倒而差点倒地的昴的身体被身旁的巨大身体用嘴叼了起来，然后仍上了背部。昴总算是抓稳了身子，这才看到漆黑的体毛，以及猛然从正面赶过来的狮子的模样。

【你……明明梅莉，都已经死了……】

承载着昴，穿越火焰王都的是梅莉操纵的其中一头魔兽。

凶兽吉尔提拉，背着菜月·昴不停跑着。主人都已经没了，没必要在服从了，即便如此魔兽仍旧载着菜月·昴，直线——。

【拜托了，帮我找到她。一定在的，在哪里的……】

带着近乎祈祷的感情，昴希望吉尔提拉能够带来奇迹。

心里的这份感情是什么呢，是安心，还是放弃，在这份无法明辨的感情中，菜月·昴的意识几乎要断线。

但是，就在迎来真正的极限之前。

【——到此为止了哦】

冰桩一个接一个地刺入吉尔提拉的侧腹部。

魔兽发出一声惨叫，四肢纠缠着重重倒在了地上。昴随着魔兽的翻到，全身砸倒了石头路面上。

【咕，啊……怎么、了……】

昴忍痛睁开眼，确认周围发生了什么事。

只见，左半边身子插着无数冰桩的吉尔提拉站起身子，向着一道身缠淡蓝色光辉的人影冲了过去。

吉尔提拉挥起兽爪，发出吼叫。这或许是它作为梅莉最后一头使役魔兽的骄傲。

挥下的这一击，有着能够轻松将人撕碎的威力。

然而，在它的攻击触及之前，一支更大的冰枪刺了出来。

【————】

那支冰枪刺入吉尔提拉的血盆大口，贯穿咽喉刺入胸腔，随后从臀部传出刺穿魔兽的全身。

这反戈一击之后，空气中想起了开裂的声音，吉尔提拉全身笼罩上了一层白色的霜降，化作了冰晶的雕像。

昴在见证吉尔提拉的死期后，慢慢站了起来。

左手抬不起来，似乎是摔倒的时候骨折了。本应是让人哭喊出来的疼痛，大脑却完全没有收到感知。

因为，如果现在昴哭喊出来的话，一切就都白费了。

【——到此为止了哦，恶党】

两旁是王都燃烧的街道，两人之间是化作冰雕的魔兽。

燃烧着强烈的义愤和使命感的紫绀色眼瞳与充斥着难以压抑的喜悦的黑瞳视线交错。

宛若月光的银色长发，仿佛最高级紫水晶般的双眸。让昴心痒难耐的天人美貌，使人错认为是妖精歌声的银铃声音。

自己追求着，追求着，渴求着，爱得无以自拔的少女身影，就在那里。

【——艾米莉亚】

【你认识我？】

被叫出名字的艾米莉亚一挑眉头一副意外的表情，让昴不禁笑了出来。

和想的一样——不对，她就是一开始，和自己一同逛过王都的少女。

她现在还完全没有理解自己作为王选候补者，到底有多受到这个国家人民的注目。肯定还没正确地认识到自己，对自己抱有过低的评价。

在世间看来，她可是击败了魔女教【怠惰】、【强欲】、【暴食】、【愤怒】、【色欲】，根绝了长久以来让人们出于水深火热之中的邪恶的勇者。

而这个称号，就在今天，将成为完全体。

【有什么好奇怪的？】

【不是，对不起。怎么说呢，感觉，好高兴啊。你那个，那什么。完全没有变过，就感觉自己好像得到了回报】

【什么、意思？你和我在哪里……？】

听到昴的话，艾米莉亚拼命地回想着自己的记忆。

然而，在她的记忆里，完全不存在菜月·昴的身影。

那是当然的。因为，那简短的邂逅只存在于昴的心中。而就是那简短的邂逅，只凭借最后遗恨的誓言，菜月·昴走到了今天。

【你是……】

【莉亚，不行。不能认真听他说的话】

【——是帕克吗】

艾米莉亚正苦命想要从自己的记忆里找到一丝线索。而阻止了他的是突然出现在他肩头的小猫——这只精灵的样子，昴的记得一清二楚。

那一天早就成为了遥远的过去，但也因此，自己回想那天事情的时间比起重复那天的时间还要多。

而作为这份记忆的一部分，昴不可能忘记它。

【别随便叫我的名字。把事情搞得这么大，你到底打算怎么收场】

【会收场的。和我期望的一样。——反正，也没地方可逃】

【——？还真干脆啊？好可疑】

昴解开自己的运动衫，展开双手表示不做抵抗。

运动衫，对就是运动衫。这是一直封印至今的运动衫，现在正穿在身上。因为昴自认为要和艾米莉亚再会，穿这身最好。

自己一直等待着有一天能够穿着这身衣服站到她的面前。

【现在开始，我说的话，全都是脑子有问题的人说的妄言。听过就忘了吧】

【——诶？】

【现在，让王都烧起来的火是我放的。不仅仅是王都，全国上下都在这片火海里。没人能够阻止，这是这个国家，以及守护这个国家的骑士的失职】

对于不断诉说的昴，艾米莉亚感到很是困惑。帕克也迷惘着该不该阻止昴说下去，不过看到艾米莉亚的样子还是停止了攻击。

昴感谢她们的顾虑，继续说道。

【莱茵哈鲁特的【剑圣】名号就此扫地。本应守护亲龙王国鲁古尼卡的盟约，既然不知道灾祸是从哪里开始的龙也无从拯救。这我已经试过无数次了肯定没错。结果，不管是莱茵哈鲁特还是龙，都只是一个个体】

【烧了整个国家？你？你这是打算毁灭这个国家？】

【不对，不是的。因为，这是能够让你成为国王的，唯一的方法】

【————】

听到昴笑着说出的这句话，艾米莉亚瞪大了眼动摇了起来。

在她的心灵，昴刚才说的话完全意思不同。

妄言，反正都已经这么说了，就算意思传达不到也没关系。

只要结果好，昴就足矣。

【将国家逼向灭亡的终焉之火——撒下这份灾厄的本人，不是被莱茵哈鲁特，也不是被龙神，而是被你给讨伐。其他的王选候补者没人能做到在此之上的功绩。你，是打破这个世界四百年的停滞，拯救了这个世界的英雄！】

【这、怎么可能……你，在说什么！？快住手，完全不明所以！你到底在说什么，我不懂啊！！】

艾米莉亚抱着头，堵住自己的耳朵，不愿听取昴的话。她的眼中饱含泪水，顺着雪白的脸颊落下，昴见此感觉内心受到了甜蜜的冲击。

这是因为惹她哭泣而产生的罪恶，也是因为昴对于她的内心因为自己而产生了动摇感到了一种阴暗的快感。

【不明白也没关系。不明白也没关系的。之后的，你周围的人会擅自把你捧上王位。你，你只要在那里实现你的愿望就行了。我就只是为了这个，才烧了这个国家的。所有的一切，都是为了你】

【你骗人，骗人，骗人！因为，我……你，为什么，要为我……】

对于自己毫无印象的献身，对于自己毫不期待的奉献，艾米莉亚恸哭道。

她会伤心也没办法。她会不能理解也没办法。

昴，知道自己是错的。

昴，知道自己是不正确的。

昴，知道这是没法让艾米莉亚开心的。

但是，除此之外别无他法了。

实现艾米莉亚的愿望，让艾米莉亚成为王，将对艾米莉亚的感情化为实体。

明知如此，明知自己从一开始就错了，昴还是来到了这里。

所以，菜月·昴笑了。嗤笑了。哂笑了。

【——看着我，艾米莉亚。看着我，憎恨我，铭记我】

【你，是谁？你是哪里来的，是谁……？】

昴展开双手慢慢走上前去，艾米莉亚颤抖着说道。

对于这个问题，昴闭上了眼。

感觉，自己一直在等待着这一刻。

一直等着，能够在艾米莉亚的面前，回答这个问题——。

【——我的名字是菜月·昴】

【昴……】

她用沙哑的声音叫出了昴的名字，仅仅如此就让昴的内心百感交集。

想必，仅仅是如此，就足以让昴对至今的一切感到满足了。

所以他将这份感情放在心里，注意着不要让声音颤抖说出了接下来的话——，

【——魔女教大罪司教，【傲慢】担当，菜月昴·！】

【大罪司教……！】

昴用尽全身的力气踏着地面，全心全意地报上了自己的名号。

用尽全身的力气，菜月·昴开始了人生最后的奔跑。

付出了那么多的牺牲，把或许能成为是同伴的人们也都舍弃，被或许可以称之为羁绊的关系所拯救，终于在最后到达了自己心爱的少女面前——。

【是烧尽世界，动摇国家，杀死英雄，然后——】

【————】

【——被你杀死的男人】

昴感受到贯穿自己胸口的冲击，微微地笑道。

昴当场身体不支跪倒在了地面上。

甚至都没能够到艾米莉亚，就这么悲惨地，浑身脱力地倒在了石头地面上。

最终，昴张开身体仰躺在地面上，眼前是俯视着火红的王都的苍穹。

在赤色与青色之间的世界，菜月·昴迎来了终结。

【为什么？】

闭上眼，已经准备好迎来结束的昴，突然注意到了什么睁开了眼。

就在昴倒下的位置，艾米莉亚正站在旁边俯视着自己。泪水从她的眼中滑落，滴到了昴的脸颊上，令他睁开了眼。

【为什么？】

重复着，再一次问道。

这个【为什么】，到底是什么意思呢，昴思考着。

【为什么】，要做这种事。

【为什么】，只能这么做。

【为什么】，要为了被自己杀死来自己面前。

一定，这里面包含了各种【为什么】吧。

昴虽然想要对她所有的【为什么】给出回答，但留给昴的时间真的不多了。

所以，昴用尽最后一口气，回答道。

【——我爱你】

※　※　※　※　※　※　※　※　※　※　※　※　※

【死亡】，在接近。自己已经十分熟悉的，【死亡】。

每当【死亡】到来的时候，昴都会被带到某个漆黑而又寂寞的地方去。

这里真的、真的很寂寞，孤独一人让人无法待下去的地方。

每当【死亡】到来的时候，昴会从这里被送出去。

送到那个充满了血与苦痛，充满了泪水与恸哭，却又有着点点爱恋的世界去。

但是，已经，够了。

已经，满足了。

【————】

昴感觉在这个黑暗的世界里，有在这儿等自己归来的谁在窃窃私语。

是安慰，是鼓励，是确认，是告白。

为什么呢。明明对方也不是让昴朝思暮想的人。

自己思念的人在不是这里的某个地方，在自己所不在的某个地方，实现了愿望得到了回报。

自己为了付出了众多牺牲，最后把自己也献了出去。

所以，已经够了。就算自己得不到救赎。自己从一开始，就已经得到救赎了。

【————】

这一定是在呼唤吧。

温柔、慈爱，怜爱地，呼唤昴着名字。

所以，昴把自己的存在放到了【死亡】的螺旋之外，接受了那个远处的存在。

接受着，对这声【————】回答道。

【————】

————哪怕，你拒绝了我，我也不会忘记你。

【从零开始过错的异世界生活】 ~fin~

** 剑鬼恋歌 那之后的两人

*** 前篇

网译版 转自 百度贴吧

译者：QA君

——那是个沈浸于昏暗、干燥的空气中的地方。寂静又寒冷的空间。有的仅仅是拼命绞出最后一丝白光的结晶灯和用又冷又硬的石头打造的墙壁和床。四下流溢的寒风恰好是身体能够忍受的程度，让人不禁想到外面应该已经是冬季了。

[————]

已经过去了很久了吧、一直持续著与季节和时间无缘的生活。

仅仅把一切都消耗在一件事情上，那之外睡眠也好，饮食也好，都只是必要的最低限度的生活，过著如同野兽一般的每一天。

这样的生活的终点，现在已经到来了。

把时间全部花在这之上是有价值的。心里完全没有这样说的自信。

[……喂,你。那边的那个人。你有在听吗？]

[————]

[新人，你在听吗？还是说已经死了呢？喂！]

背靠著墙壁坐下来，突然耳边传来了这样的声音。

抬起头，看向声音传来的方位，黑暗中有一道铁栅栏，在道路另一侧的另一道铁栅栏深处，声音的主人正愉快地看著这里。

越过两道栅栏互相观察者的两人，也就是说两名监狱中的囚徒。

[终于看向这边了啊，明明是新人架子却不小嘛。……不对，应该说，正因为是新人，所以对世间还保有不切实际的幻想吗？嘛，怎样都好。常有的事。嗯？等一下，你，刚刚因为又脏又暗所以没有察觉到，莫非你其实很年轻？]

[……大概吧]

[怎么搞的？]

[之前就想说你还真是很能说了，你是一个人也能开心地说个不停的性格吗？]

对喋喋不休的声音，反射性地吐出讥讽的话语。这样糟糕的态度已经是自己长久以来的恶癖了吗。久违了的自觉和自省，混合在叹息中，吹动著自己的前发。

但是，面对著态度如此糟糕的自己，对面的人却自顾自地渐渐笑了起来。

[你真是我的知己啊，能说会笑，人称『六舌』的奥路菲，说的就是我哦？你也会进我所在的牢房，说明你也是气数已尽。释放也好，处刑也好…总之，待在这里直到了却尘缘之前无趣的时间，和我一起打发可好？]

[『六舌』?]

[世间送我的外号罢了。前不久的内战中，同时给予贵族街上六名又寂寞又纤弱的小姐心灵和肉体上的慰藉最后被抓了。之后，因为六个人描述的人都完全不一样，和不同的人交谈时视对象会有完全不同的谈吐和印象，所以被称为『六舌』。]

[原来是诈骗犯和流氓吗。和这样的人在王都的监狱里产生联系还真是令人笑不出来啊。]

对坦然，轻佻地笑著的男子的态度有些惊讶这样想著，不禁凝神看向铁栅栏另一侧的长发的美男子。皮肤白暂，手足纤细，看上去就和握剑的生活无缘，但是却有著一副可以在社交界大放光彩的容貌。

[仅仅是被联系在一起就笑不出来的话，你那边又如何呢？毕竟无论怎么说，会在地牢里产生关联的人都是彼此彼此，你又做了什么呢？嗯？]

[说的是啊，我做的是…]

戛然而止，我暂时对奥路菲的问题沈默了。

但是，回答很快就浮现出来。

[从自己不中意的混 蛋那里，夺回自己中意的女性罢了。]

[————]

[原来就这点事吗？还以为是做了什么了不起的事呢，这副口气。]

不以为然地摇著头，一直沈默著听著我把进入牢房的错综复杂的缘由吐露的奥路菲用手捂著嘴，很快忍耐不住大声笑了起来。

[哈哈，哇哈哈哈，什么嘛！喂，原来和我是同道中人啊！]

[混 蛋！你这个家伙，怎么能把欺骗了六名女性的你和我相提并论呢！我只中意一人。]

[我才没有说错呢！会被关到监狱塔来，那个不被你中意的混 蛋多半不是骑士就是贵族吧？……也有那个女性的地位特殊的可能。怎么样，我没说错吧？]

[……任你想象。]

我愤怒地对沈浸在想象中的奥路菲回答道，这家伙还在伏地大笑。

没有打算告知他实情。但是，客观地来看自己和奥路菲之间确实没有什么本质的差别。排除掉对女性的心意方面的区别的话，确实是一样的。

[不要这样嘛，我很感兴趣啊，小哥哥，狱中生活好像也暂时变得愉快起来了。]

[想要笑的话就随你喜欢地笑吧，但是你的期待似乎没什么机会得到响应了。]

[啊？]

对我的回复，奥路菲惊讶道。

但是，他的疑问的回答，早就从另一个方向——地牢的出入口，和地上世界联通的台阶方向传来了。

坚硬的靴子落在地面上的声音响起，走进地牢的是披甲的王城卫兵。

卫兵向坐在地牢中的我这边看来，眯起了头盔中的眼睛。

[出来！来接你了。]

用傲慢的口气说著，卫兵打开了地牢的栅栏。仿佛那句话重逾千金般地抬起了腰，在催促的视线下向外面走去。

[喂喂，还真是突然的分别啊。释放吗？有温柔的老相好在还真是让人羡慕啊！]

[谁知道呢。]

那是，至今为人传颂的，剑鬼和剑圣的，男孩和女孩的，相逢和离别的，恋爱故事。

动摇亲龙王国露格尼卡的，王国内战[亚人战争]。

在王国军和亚人联合的激战中

国土荒芜，百姓疲敝

人心渴望著和平到来的时代

如果说英雄是在战火中诞生的话

[剑鬼]威尔海姆·特利亚斯正是这样的人物

单人独剑，像野兽一样驰聘在战场的少年剑士

追求著自己的剑的极致的他的生活方式最终将战友和王国

以及一个少女，特蕾西亚卷入

铸就了留存在王国史上的伟业

这就是穿越四十年的时空，至今为人称颂的剑鬼的战斗。

对被卫兵带著走出牢房的我，奥路菲嫉妒似地撅起了嘴说。对那美男子的话苦笑以对，脑海中浮现起了前方的阶梯上等著我的温柔的老相好的样子。

而后青年——威尔海姆·特利阿斯闭上了一只眼睛

[如果等著的是生气的她的情况的话，说不定就不是释放而是处刑了呢]

这样说著走出了地牢。

2

[比起释放还是处刑更合你的心意吗？就算现在改变也还来得及哦？]

从地下走上地面，和凉风和阳光一起迎接威尔海姆的，是对方冷静中掺杂著怒气的发言。

片刻前还在其中的这片地牢，是邻接王都的被称为[监狱塔]的监狱的一部分。即便是在国内的罪犯之间，也以专门收容引起了重大事件的犯罪者而出名。相关人员无论是其中的囚犯也好，还是被委托管理这座塔的狱卒也好，都是令人畏惧的人物。

此刻在这样的一个地方，一位拥有不宜场合美貌的少女的存在正绽放出异彩，即便是混杂著异议和不满的表情，也拥有著使人倾倒的魅力。

垂至腰间如同火焰般的红发，仿佛容纳了整片澄清天空的碧蓝双眼，洁白的四肢纤长有力，均衡的身材是恰好位于健康美的极点。面容更是超出端正的评价之上，有著仿佛太阳一样明亮地绽放著的花容月貌。

特蕾西亚·范·阿斯特雷亚——这就是正怒上心头的秀丽少女的名字。

[威尔海姆？]

对严肃地看著自己的特蕾西亚，稍稍有一瞬间仿佛世间的声音被夺去的恍惚。察觉到自己的失神，威尔海姆很快举起手腕说。

[是我的错，不好意思。能先把这副手枷去掉吗？]

[……真是的，其实我是明白的但是，]

对敷衍了事的回答叹息一声，特蕾西亚对威尔海姆的手腕间的木枷挥起了手刀，随著她的指尖所至，拘束著威尔海姆的木枷被漂亮地一分为二。

随著木枷落在地上的声音，威尔海姆回转著两手确认著手指的灵活性，完成了之后。却注意到特蕾西亚正呆呆地注视著自己。

[怎么了吗？我身上有什么不对的吗？]

[什么也没有。不过……被不由分说地关进监狱塔，你才是怎么一副毫不惊讶的样子？]

[毕竟是破坏了国王主持的终战典礼，仅仅是留有一条性命就已经是意外的好了。]

[原来你还是有犯下了大错的自觉的啊……我还真是有点吃惊。]

对稍微苦笑著的特蕾西亚[差不多是这样吧]，威尔海姆肯定道。

无论怎么说，威尔海姆所引起的一系列事件，对露格尼卡王国来说是大事中的大事的大事件。就事情来说，引起国王震怒，甚至被称为国贼也是不奇怪的事。认识到这之中的温厚，没有吉奥斯·露格尼卡国王的宽大处理的话是不可能的。

威尔海姆的大图介绍：惰怠发作，略去50字。

[如果不是陛下亲自下令阻止的话，在那种场合被以无礼罪当场格杀也不奇怪哦？这件事，有在好好反省吗？]

[要用武力来讨伐能战胜[剑圣]的对手吗？明明好不容易结束了内战，让士兵白白送死的做法，即便是以不擅谋略闻名的王族也不会干的吧。]

[自信过剩！而且又是不敬罪的发言！你这个人完全得意忘形了！]

[而且，要以你我二人为对手的话，那个会场的兵力连战力不足都说不上呢！]

[居然还一副理所应当的样子认为我会站在威尔海姆你这边……]

在紧邻著王城的设施，再加上不远处就有卫兵的地方胆大妄为地说著。实际上，看著两人走远的卫兵听清了两人的对话后做出了目瞪口呆的表情，很快就装作什么都没听见的样子低下了头。真是明智的选择。

「什么事？现在我的脑袋里正十分混乱呢！而且也不知道是谁害的！」

「过来。」

「————」

对声音和表情都很慌乱的特蕾西亚，威尔海姆张开了双手这样说。虽然仅仅是这样简单粗暴的情感表达方式，却让特蕾西亚瞪大了眼睛说不出话来。

一度，也有过沈默和犹豫。但是，这期间威尔海姆依然张开著双手，对特蕾西亚的反应毫无犹疑地等待著。

很快的，对身边那个做出邀请的姿势的家伙，特蕾西亚无力地微笑说。

「……哈。原来是这样吗，果然我是败给你了呢。」

「那场决斗的胜负应该早就分出了。」

「不—是—啦！我说的完全不是这么回事。真是的……」

对于做出惊讶状的威尔海姆，特蕾西亚打从心底觉得“这个人没药救了”地叹了口气，然后向前走过去。跃入那个男性张开的双臂中，用额头摩蹭著他的头。

拥抱得到回应，威尔海姆拥抱著特蕾西亚如同火烧般的体温。纤细的身体仿佛用力地拥抱的话就会折断一样，明明如此，不用力地回应却不行，因为躯体的主人正用同样的力度紧抱著自己。

两人互相竭尽全力拥抱时，从男人的胸前抬起头的女性说

「欢迎回来，威尔海姆——让我等太久了啦。」

对这句话，拥抱著女性的男人低下头回答说。

「啊啊，特蕾西亚——让你久等真是抱歉了。」

肌肤相亲，从最近的地方看著注视著自己的特蕾西亚的笑容，威尔海姆脸上也不自觉地浮现了微笑。在最近的距离体会著对方的呼吸，体温和脉动。

只身一人的话无法达成的夙愿终于达成了，眼前这心爱的少女终于落入手中。用因为练剑而变得满是老茧的粗糙的手，威尔海姆温柔地抚摸著特蕾西亚的红发。

享受著毫无顾忌的幽会和肌肤相亲的拥抱的特蕾西亚眯起了眼睛，然后押向威尔海姆的胸膛，深吸了一口男子的气味。

「威尔海姆。」

「怎么了？」

「……好臭」

就久违了的重逢而言，用稍微有些不相称的声音和眼神说道。

3

亲龙王国露格尼卡长期以来持续的内战「亚人战争」终于结束了。

为持续八年的战乱拉下帷幕的仅仅是一名少女——「剑圣」特蕾西亚·范·阿斯特雷亚的功劳。以和传说中的「剑圣」称号相称的剑力，引导著王国军获得了胜利的她，理所当然地成为了王国中的知名人物，获得了与之相称的荣誉。

强大而美丽的当代「剑圣」仿佛是人们心中希望和理想的体现，在庆祝内战结束的王都典礼上，随著她的身影出现，国内的人们便汹涌而至。

page 574

事实上，典礼会场上特蕾西亚现身的一瞬间，全场观众就都被她的身影所吸引了。假设就这样典礼平安落幕的话，她也一定会毫不动摇地获得「剑圣」的评价，在未来永远被露格尼卡的人民以这个名号所称颂。

——但是，这说到底，不过是以什么事都没发生为前提假想的未来罢了。

「*****真的是什么都没考虑啊！有点羞耻吧！羞耻！」

开口第一句话就是唐突的怒吼，回声仿佛突破了屋顶后在晴朗的天空中回响不散。

真是尖锐，仿佛掺杂了锋利剑气的怒吼。并且是以大到吓人的音量说出的，实际上，即便是已经听习惯了的人在听到时身体也不自觉地僵住了。

但是在场同席的人中，却没有一个是那么好对付的人物。

「……不要突然吵吵闹闹的，烦死人了，究竟是什么意思啊？」

声音的余韵消散后，第一个发声的人正是这种棘手的人物的典型代表，那怒吼的直接对象，威尔海姆本人。但是他无动于衷的冷淡回答，只是加剧了对方的怒火，这次也是一样。

「『什么意思啊』是什么意思？混球，你应该还有别的话要说吧！」

桌子的一头，说出这话的人正身著长裙，面红耳赤地喘息著。那是个金发披肩，给人以强势的印象和傲慢的眼神为特征的女性。其楚楚可怜的外表即便说是贵族千金也会令人信服，看上去并不像是会这样情绪激动的人。

「卡罗尔，算啦，你的心意我很高兴不过，反正我也没有生气所以……」

「正是因为特蕾西亚小姐不会生气，所以作为代替，我才更加生气了！」

「嗯……」

试图劝说卡罗尔宽恕威尔海姆的特蕾西亚，对于自己的话起了反效果只能苦笑不止。虽然做出“你死心吧”的表情对威尔海姆吐了吐舌头，但是就这样放弃劝说也很困扰。因为很不巧的是，威尔海姆自身毫无让她——卡罗尔的怒火止息的方法。

因此，只能早早地让最终手段上场，让卡罗尔身边站著的青年帮忙擦屁股了。

「格林，你的女人啰里啰嗦的吵死人了，连好好对话都做不到了，像往常一样让她安静一会儿」

「————」

「别一脸微笑地看著了，这一点也不有趣。」

稍微有些强势地被胁迫著，青年老好人的脸上露出了微微的苦笑，稍稍敲了敲卡罗尔的肩摇了摇头。仅仅如此，之前还如同烈火一样狂怒著的卡罗尔的势头就弱了下来，脸色还很严厉的她喘息著说。

「……要记得感谢格林啊，威尔海姆。要是没有他和特蕾西亚小姐的话，我的说教可不会这点程度就算了。」

「嗯——。果然，难以习惯卡罗尔比起我先提起别的男人的名字什么的呢。不过，虽然寂寞但是也有点高兴呢。」

「特、特蕾西亚小姐又这样说！」

对这次并非是生气而是害羞得脸通红的卡罗尔，特蕾西亚恶作剧地笑了起来。两人宛如姐妹一样嬉闹著的热闹场景，令旁人也感到耳目一新。

「……干嘛」

『笑起来了呢。』

对察觉到侧脸的注视而随之到来的尖声询问，青年——格林·法恩赞将手中纸条上的字指给他看。因战伤而失去声音的格林，除了笔谈的方式无法向别人表达自己的想法。即便如此，如果仔细观察他的表情，大致也能理解他在想些什么。

比如他现在正调笑著威尔海姆。

「不过是笑笑而已，我也自然会啊，真是的，把别人当成什么人啊。」

「————」

对格林沈默和微笑的态度，威尔海姆用生气的表情回应。

被嘲笑也好，被发火也好，无声微笑著的格林确实看上去很幸福。本来抱有的反感都被这笑容击碎，吵架的力气也迅速萎靡了下去。

因为即便是威尔海姆，或多或少也还是有这样被人深深担忧著的自觉。

现在，四人所处的位置是王都露格尼卡贵族街的街道一角，特地为了「剑圣」而建造的房屋——也就是说，类似特蕾西亚在王都的私人别墅一样的建筑的大厅。

从监狱塔被放出来的威尔海姆，先被特蕾西亚带到房间里。然后，又被她强塞进浴室，按照她的指令，拧著鼻子把身上的恶臭彻底洗除干凈。洗完热水澡刚回到大厅——就迎来了一阵大声怒吼。

「——说到底，你们两个究竟为什么会在这里啊」

以激烈的责骂作为开头问候的严苛再会也告一段落了，威尔海姆在沙发前坐下，提出了一直以来的疑惑。

「这里是特蕾西亚的家吧？和你这家伙有什么关系啊」

对于正在绑起还没干透的头发的威尔海姆的疑问，格林和卡罗尔互相看了看，很快在威尔海姆的对面坐了下来，卡罗尔低声说

「……什么啊你这家伙，显然是来看望你出狱的吧。而且作为侍女，我到特蕾西亚小姐的住所来有什么奇怪的吗？」

「穿著礼服长裙来吗？我可没听说今晚要在这里开舞会啊」

「还不是因为你这家伙干了那样的蠢事，我们连换衣服的时间都来不及吗」

卷起蓝色洋裙的下摆，卡罗尔的怒火又爆发起来，看她旁边坐著的格林的服侍，也是王国军的正式礼装。也就是说，是从某个典礼的会场上没换衣服直接赶回来的吧。

明白了原因的威尔海姆这才明白为何先前他挖苦卡罗尔的时候，特蕾西亚做出「快停下」的口型。

「卡罗尔也好，格林也好，大家都是担心你所以才来看望你的哟。所以别再说这种满是厌烦口气的话了，不好好露出高兴的表情解除误会可不行。」

「说起来，你也是穿著洋裙呢，为什么换掉了之前的衣服呢？」

「诶？这是因为之前那件和你舞（yong）剑(bao)的时候弄脏了，走起来黏糊糊的很碍事，所以……不换的话更好吗？」

「仅仅是先前没见过你穿这件感到有些新奇罢了，说不上更喜欢哪一件。」

「这样啊……那，要是还有机会的话想不想看呢？」

「——？」

「为什么在这种对话上你的理解力就这么低下啊！?把人家的勇气还回来！」

对著一脸痴呆的威尔海姆，特蕾西亚含著泪说。不过，她很快就想起了身边还有旁人在的事情，「啊……」

「————」（气氛一度非常僵）

看著脸色通红的特蕾西亚和歪著头疑惑的威尔海姆，格林和卡罗尔一脸震惊的表情。现在的剑鬼和剑圣彼此亲密无间的样子，即使是与他们关系亲近的两人也是第一次见到，意外极了。

——如同正常人类的剑鬼和一脸少女表情的剑圣。

无论哪个，都和两人特立独行的名声不符，但却又是两人真实的姿态。

「————」

看到两人亲密的样子，最先超出极限的是卡罗尔。

她一副说不出话的样子，突然转身倚靠在格林的肩膀上。格林接受了情绪崩溃的恋人，温柔地抚摸著恋人的后背，渐渐微笑了起来。

「……卡罗尔好多年前就是和我关系最好的侍从了，在那个花园接我的和照顾著我的也一直是她。」

代替说不了话的卡罗尔，特蕾西亚向威尔海姆说明了自己和她之间的关系。了解了这点，威尔海姆露出一脸原来如此的表情，点了点头。

卡罗尔出现在这里的理由，还有她陪伴著作为「剑圣」第一次走上战场的特蕾西亚的理由，这下就全部说得通了。

——也包括卡罗尔多么地为特蕾西亚费心费力。

「还真是爱操心的人啊。」

「……那个，你是记得自己回来的路上又蹦又跳的样子还作出这样的发言的吗？」

「你在说什么呢，我不是很明白。」

把腰深深地沈入沙发，中断对话的威尔海姆对特蕾西亚耸了耸肩。对此，特蕾西亚「啊哼」地清了清嗓子，小声地对格林解释道。

「不好意思啊，这个人很害羞，所以不能好好地表达自己的感情……也有本来就笨嘴拙舌的缘故，不过并不是坏人。」

『没事，我明白的。』

「你这样说真的是帮大忙了。」

『我们都是好多年的朋友了，我可是亲眼看著他从野兽变成人类的嘛』

「你们在聊的是谁的事啊？不会是在说我吧？」

又是害羞又是野兽的，真是让人听到就会感到恶意的对话内容啊。当然，对这个追问，特蕾西亚和格林摆著一副一无所知的表情摇了摇头。看著两人一致的动作，威尔海姆不由得烦躁地咂了咂嘴。

看著态度恶劣，在沙发上盘腿坐著的威尔海姆，两人笑了起来。但是——

「——吶，威尔海姆。」

收起笑容，特蕾西亚突然端正了姿势正坐了起来。回头看向旁边坐著的威尔海姆，湛蓝色的眼睛里流露出认真的意味。从她的眼神中察觉到难以忽视的重压，威尔海姆也直起腰来。

面对坐了起来的威尔海姆，特蕾西亚稍微踌躇了一下，开口道

「虽然你可能不喜欢听……但是你今后究竟打算怎么办呢？」

「真是模糊的问题呢，所谓的打算是指？」

「大概是指所有事情的打算吧？你今后打算住在哪里，从事什么职业等等。这许许多多的事情不说清楚可不行。一起生活的话，就住在这栋房子里也不错。我的话，有国王的赏赐，所以生活也不会困苦……」

「——等一下」

对不断碎碎念的特蕾西亚竖起手掌，威尔海姆打断了她的话。急于得到结论的特蕾西亚的发言内容中引人注意的地方太多了。抱著数个疑问，威尔海姆深深皱起了眉头。

「啊，威尔海姆，你又皱眉了……明明都和你说过不要再这样了。」

「这个先稍后再说，还要更重要的话要谈。……刚刚的话，是什么意思？」

「刚刚的……？」

「就是一起生活的住所和工作什么的。我……」

说到一半，威尔海姆不祥的预感和眉头的皱纹越发加深。特蕾西亚看著他的表情，慎重地回复说。

「我？」

这是个非常笼统，缺乏指向性的提问。说著，特蕾西亚露出困惑的表情。

「————」

「直白的说的话就是……那个，失业……？」

「——失业」

对此无话可说，威尔海姆睁大眼睛看向特蕾西亚，而她则看向一旁。然后转头看向格林，他露出苦笑。最后，看向卡罗尔，被狠狠地瞪了一眼。

「当然是被开除了啊，你这个大**。」

她红著眼睛，泪水中混著怨气说了出来。

4

——自己因为任性的理由而脱离军队，就那样行踪不明成了逃兵。

理所当然的，这就是现在的王国军中威尔海姆·特雷亚斯档案上的记录，也是客观来看他履历的全部。

回想起来的话，自己刚刚受封为骑士就直接逃离军队，骑士身份应该是连同数枚勋章一起被剥夺了。

「也就是说，在仪式典礼的记录上，你完全就是个被收监的盗贼吗。更史无前例的是这个盗贼偷走的是「剑圣」的心……哇哈哈哈，还真是干得漂亮呢，大盗！」

「哇哈哈你个头……」

被这样傻笑著的巨汉欢迎之后，威尔海姆抱著头深深地叹了口气。

在王国军治所一间指挥官专用的办公室中。在只有用来接待来访者的椅子的朴素石屋内，得知威尔海姆的来访后，石屋的主人停下了手头的工作对他表示了欢迎。

但是，除了最初迎接时被嘲笑了，接待的过程完全谈不上有趣。即便如此，对于如今自己的身份和立场，确确实实有了详细的了解，这也算是一种收获吧。

「逃兵吗？难怪当初被关进监狱塔了。如果士兵的身份还在的话，我想应该是被带到惩戒所去吧。难怪被当作罪犯处置了。」

「话先说好，在典礼上干了这样的事就算没被当成逃兵，你还是会被关进监狱塔。而且我还听监狱塔的卫兵诉苦说，释放后你在别人眼前打情骂俏释放闪光弹」

「要以这个为理由再把我关到地牢里去吗？」

「虽然是不会这样，但是还是要懂得适可而止啊。总之，你要是再在人群眼前盛大地搞一次，现在也会再让你进去也说不定哦。是不是？特蕾西亚大小姐」

「诶？？是」

突然被问到，惊愕中有些害羞地，特蕾西亚微妙地回复道。对特蕾西亚回以充满野性的笑容，筋骨粗壮的巨汉——博尔多·谢鲁盖夫，既是这间石屋的主人，也是两年前时任威尔海姆所属的谢鲁盖夫队的指挥官的男人。也就是说，是当时威尔海姆的直属上司。当然，现在早已不是那种关系了。

「喂，别这么僵硬嘛，你也稍微放松点」

从博尔多的视线中把特蕾西亚挡在身后，威尔海姆这样对身后的她说。

「真是见到罕见的景象了。特蕾西亚小姐……「剑圣」会露出这样的表情还是第一次见到呢。」

「这么说你之前还见过她？」

「就算是你不在的两年间，谢鲁盖夫队也都是奋战在最前线的男儿啊，自然时常有和特蕾西亚一起并肩作战的机会，所以就会时常见到她。」

不在的两年。每次说到这个话题，威尔海姆除了沈默以对便别无他法。听了博尔多的话，只能以担忧的眼神看著她。

「本来是打算等到以后有机会时再和你提起的」

「那个……就是，之前对你的态度很恶劣，不好意思了……」

「关于这一点的话彼此彼此。现在想起来的话，当初说著什么要记得我的爱，真是无理取闹的话啊。不如说，你能有不一剑砍过来的自制力我就十分感谢了。」

「你们这两个家伙究竟是怎么凑到一块的呀…」

真是超出想象的不安定关系呢、不过博尔多也没有要订正特蕾西亚的话的意思。就这样，至少表面上两人能够欢笑著在一起，是如同奇迹一样的事情。

「格林和卡罗尔呢？」

「在特蕾西亚的宅邸里遇到过了。还是老样子，啰里啰嗦的女人和笑容也很烦人的男人」

「与其说是那两个人还和过去一样，不如说是你应该感谢两人周到的考虑吧

「啊？」

对预料外的发言，威尔海姆感到有些惊讶，但是博尔多没有回答。他挠著自己的短发，用一句「那么、」改变了话题。

「为什么特意要到治安所来看我呢？我可不会指望你仅仅是来见见旧相识，一起叙叙旧而已。老样子，直话直说吧。」

「那我说了——不，不好意思，现在还是让我以牙还牙吧。」

说到一半即止，同时习惯地咂了咂嘴。威尔海姆站直重新看向博尔多，然后稍稍向他低下了头

「博尔多，我有事想拜托你。之前是我得意忘形了，但是…」

「是想重新参军，对吧？」

「知道的话就早点说啊，我还…」

「丑话说在前头，重新参军可不会这么容易。」

「——」

对露出了决断的神情的威尔海姆，博尔多低沈地说。以「猛犬」的绰号知名的男人叉起了双臂，严肃地注视著威尔海姆。

「好好想想自己两年前，从军中辞行的做法吧。仅留下一封书信，就在内战最激烈的时刻逃亡了。…不管你有什么苦衷，客观来看就是这么回事。那副样子，谁又能简单地接受你的回归呢？」

「这个么…」

「不好意思，但是我也很生气，虽然很高兴你能平安无事地回来。也祝福你和特蕾西亚小姐未来能够幸福，但是现在的这个问题是不容私情的。一切如常。明白了吗？」

对于收敛笑容的博尔多义正言辞的话，威尔海姆无言以对。

两年前，就在威尔海姆行踪不明前后，王国军下达的开拔命令送抵兵营，关于这一点的记忆是难以忘怀的。虽说做出决定时已有了觉悟，但是一个人先行一步只能说是自私的觉悟。

出生的故乡受到战火的威胁，得知了这一点的威尔海姆拋下刚授勋的骑士身份，拋下军队离去了。但是，结果还是没能赶上，不仅故乡被付之一炬，连对前来救援的同伴一句感谢也没有，就这样消失了。

真是无情无义至极啊。还能像现在这样见到博尔多就已经是奇迹了。

「扰乱典礼的事也是。当然，吉奥斯陛下宽大处理的御旨比什么都大，但是你能够被放出来也是特蕾西亚哀求的缘故」

「特蕾西亚哀求？」

正为自己的鲁莽受到责骂的，低著头的威尔海姆突然听到博尔多提到特蕾西亚讶异道。与此同时，特蕾西亚露出了困扰的表情，用手指绕起了自己的红发。

「真的吗？」

「要说是真是假的话当然是真的但是…也不是那么值得在意的事情吧？」

「真是的，爱情可真伟大啊。听说是以吉奥斯陛下赐下的功勋作为代价，索取了你这家伙的特赦。你是不是应该说些什么啊？…」

「我只是做了我最想做的事情而已」

「这样啊。你这个幸运的家伙。」

对斜著眼的博尔多揶揄的说话方式，威尔海姆叹了口气。即便是威尔海姆，对于现在的谈话内容也没法感到平静。也就是说特蕾西亚是以终结「亚人战争」的功绩来换取威尔海姆从监狱塔中的释放的。

这也就意味著她在这两年间不得不天天参与她所不期望的战争。

「——漫长的内战也结束了，军队再编的方向性确定下来以后，招兵的频率也会重新回到正常的水平。你也借这个机会不要执著于军队，试试看生活在和平的年代如何？」

对沈默的威尔海姆，博尔多用沈稳的声音说道。对这意想不到的话语抬起头，威尔海姆慢慢摇了摇头。

「一直战斗的日子说不上是生活。身边又添了这样一位女性，过著平缓的一生也是不坏的选择吧。你不这样想吗？」

话说著，他转头看向自己桌上的一角。自然地跟随著那视线，威尔海姆才注意到在办公桌的角落放著一副碎掉的单片眼镜，这是博尔多以前的助手的遗物。

看著眼镜，也渐渐明白了说著去过平稳的生活的博尔多的真意。

「如果还活著的话，如果还能再相见的愿望能够满足的话，这样还不够满足吗？」

「——今天的事情就到此为止。打扰了呢，博尔多。」

听著尽量压抑得毫无感情，却反而让人察觉到内心的情绪的博尔多的声音，威尔海姆感觉无法忍耐地转过身去。

「啊、威尔海姆！真是的！博尔多阁下，抱歉。我也先告辞了。」

「我才是，没能好好招待非常抱歉。——威尔海姆」

露出慌乱的表情，低头道歉的特蕾西亚的声音和博尔多的声音交织著。在最后，对握著门把手的威尔海姆博尔多喊道。对听见了声音停下了脚步却没有转身的威尔海姆，博尔多说著「那个啊」继续道

「不管怎么说，欢迎回来。只有这一点是毫无虚假，真心实意的。*****家伙啊」

「好好学著忍耐吧。你所不足的东西就是自省和对周围人的关心。」

「知道了，博尔多队长殿下」

仅仅是一瞬间，两人仿佛回到了原来的关系一样互相挖苦著。下一刻，威尔海姆就离开了博尔多的办公室。硬石路上的脚步声渐渐远离，回想著今天的对话，威尔海姆不由地叹著气，这时，偷偷在旁边窥视著他的侧脸的特蕾西亚说

「那么，威尔海姆你现在打算怎么办呢？即便受到冷遇也还是要回军队吗？」

「正如你所说的，现在就先撤退吧。用正攻法的话，看来是没办法取回自己被剥夺的身份了。就算只是明白了这一点，也算是有所收获了吧。」

那个……要我这边联系下认识的人想想办法吗？」

「今后我都不会再让你为了我受罪了」

停下了脚步，威尔海姆用手指著特蕾西亚说。看著手指，特蕾西亚窘迫地「嗯」了一声。

「抱歉，仔细想想你这边才是多的是对我发火的理由」

「是、是这样吗？但是现在的话，我觉得是幸福的理由要比生气的理由更多更大……」

摆出思考的动作，特蕾西亚用放松的表情微笑道。看著双手举在胸前，仿佛抱持著某种珍贵的事物的她的样子，威尔海姆惊艳地喘了口气。

从她身上移开视线，眺望著窗外说

「……关于释放的事，不好意思啊。比我想象的更给你添麻烦呢。」

「行了啦，已经说过了不是吗？我只是为了做了我最想做的事情，按照国王陛下的话行事了而已。而且本来也没有其他的办法，实际上我也没有拒绝的权力。」

「但是，就算这样让你受累了，我却只是个无业人员」

「别这样失落了啦……好啦，我会好好照顾好你的生活的」

张开抱著丰满的胸部的手，特蕾西亚用更明亮的笑容激励著威尔海姆。但是，感受到她的温柔也多少更加伤害了他作为男性的矜持。尤其是现在在自己不走运的基础上，还要加上对过去的反省。

「别再宠著我了，老是这样说」

「啊，刚刚的那个可不是宠话哦，不论什么时候你身后都会有坚强的后盾……在呢」

对一下子就忘记前一句话的她弹了下额头，让她眼睛里充满了泪水，威尔海姆指了指窗外的景色，那是市区的街道中，她的宅邸所在的方向。

「只要有你在身边，就会占据我脑子里大半的空间做不好事了，请离我远点」

「真过分！这可是非常残酷的话哟！」

「你啰里啰嗦的样子有些烦人啊，晚上我就会回来了，你先回家吧——」

挥挥手，正想大步走开的威尔海姆，突然感到袖子被拉著而停下了脚步。回头一看，拉著衣袖的是特蕾西亚洁白的手指。她看见了回头的威尔海姆，「咦？」地对自己下意识的举动感到惊讶。

「这个是……那个……你要去做什么？」

「什么也不做哟——会好好回来的。约定好了。所以安心吧。」

「……真的会好好回来吧？不会像两年前那样一下子不在了？」

「你这个喜欢担心的性格真是……明白了，是我的错，抱歉」

握住抓著衣袖的手，威尔海姆拉著特蕾西亚入怀。一瞬间变得身体僵硬的特蕾西亚，很快就仿佛身体失去了力气一样依靠在他身上。过了一会儿，仿佛在安慰一样地温柔地拍著她的背，两人分开了。特蕾西亚脸上也不再有不安的表情。

「你先回去吧。很快就会像往常一样回来了。」

「嗯，会做了晚餐等你的。做些冷了也很好吃的好了。」

缺乏信任也是当然的事，威尔海姆用手指按了按特蕾西亚的额头，然后对用手遮住额头的她点了点头算是告别。一直到街道的拐角处为止，特蕾西亚的视线一直看著他的背影，为了彼此考虑，就没有挥手告别。

「即便是这样……还真是无情的家伙呢」

宅邸内卡罗尔对先前博尔多的正论毫不留情地批判道。

两年前，威尔海姆以自己的意志无视掉的数个人际关系，对如今回来的威尔海姆露出了獠牙。正可谓是所谓的因果业报吧。

然而不凑巧的是威尔海姆不是一个脆弱的人，不会因为这样就动摇自我。不如说在这世上的芸芸众生之中，各种各样的冥顽不灵集合而成了他。

无论是开始的两年前，还是作为结果的现在，无论谁都不能否定，也不会让任何人否定，自己这么做的意义。

「————」

重温自己的决意，威尔海姆思索著露出释然的表情。寻找著前行的方向，威尔海姆突然留意到了周围的风景。稍微驻足了一会，脚步便不自觉地，向那个方向走去。

——两年间，自己真正的意愿从未改变，现在也在那个地方。

5

走出城外，踏上卫兵们用石头铺出的道路。鞋底传来了熟悉的触感。虽然对于威尔海姆来说，也算不上走习惯了的道路。两年前，自己也曾经在这条路上进退两难而不喜欢这条路，而现在则是在另一种意义上果然还是不喜欢。

即便如此还是踏上这条路，是因为认为变得因为有这么做的意义和价值了的缘故。

「好久不见了呢——匹博特」

在正面刻著许多名字的石碑前驻足，威尔海姆念出了其中一个男人的名字。那既是谢鲁盖夫队的原副官，也是博尔多办公桌上那副破损的单片眼镜的原主，在内战最激烈的时刻殒命的战友的名字。

失去了直接和战友传达自己心情的机会，真的是一件令人从心底悔恨的事情。

石碑上也不仅刻著匹博特的名字，而是有著难以计数的数量。一两块石碑不足以刻满，因此才有了这一整片广阔的墓地——这里是保留战死者名字的军用公共墓地。

也是曾经不能体会死的意义的威尔海姆讨厌的地方。

「……不好意思啊，花也好，其他的也好，什么贡品都没带就来了。就大方地别计较了吧。」

也许是内战结束了的原因，墓地内有很多献上的花朵和贡品。在前往墓地的途中，也数次见到了面色沈痛的士兵。一个接著一个，仿佛所有人都来参拜了。向战斗中死去的人献上悼念，向无法回答的他们倾注话语。

「————」

如果没有能向死者献上的饯别物，并不能说是正确的做法。因此威尔海姆在墓碑前起身，静静地做出了习惯了的敬礼。王国军的敬礼。服装虽然只是平民的服装，被取走上交了的剑也没有佩戴在身旁，是只有形似，不正规的敬礼。

但是对围观者来说，是可以察觉到这个敬礼的动作的严格和完美的。被条例三令五申，被那个温柔的男人训到耳酸的程度的敬礼,不禁让人回忆起他的事情。威尔海姆向他献上毫不可耻的敬礼，与死者确实地饯别。

「————」

没有什么可说的话。也不觉得有说的必要。最初就不是觉得可以得到或者给予什么而来的。仅仅只是想向曾经一起共事的人们再次相见，觉得与他们不打声招呼无论如何都是不行的罢了。

仅仅只是这样而已。虽然如此，此刻吹来的风又是谁的思绪招来的呢。是久违了的匹博特，在说著些什么爱操心的话吗。

「——啊啦。这是这是，在难得的地方遇到了难得的人呢」

「你是……」

从墓碑前转过身，向来时的路走去的威尔海姆停下了脚步，和站在共同墓地的入口正饶有兴致地看著他的人对上了眼。

说话的是一位三十岁左右身材苗条的男性。看上去像是文官的打扮的人。基本上一直和身材健硕的武官们混在一起的威尔海姆很快认出了他是谁。

是在内战最激烈时，召集他到大本营会议时发过言的人物——

「名字确实是……麦库洛托夫」

「你还记得我真是比什么都好了，威尔海姆·特雷亚斯殿下。——你的事迹真是让人难以忘怀啊。」

这样说著的男性——王国宰相辅佐、麦库洛托夫·马库马洪正露出亲切的笑容，知性的眼眸中映照著威尔海姆的身影。

夕阳西下的时候，威尔海姆如约回到了家。也就是特蕾西亚的私邸。虽然这样说是回家多少有点语病不过——

「很好很好，好好地回来了呢。遵守了诺言了不起了不起」

这样说著出来的特蕾西亚心情好极了的样子。因此威尔海姆也就觉得没有特别纠正她的说法的必要。

接受了这样的特蕾西亚的欢迎，走进了餐厅的威尔海姆大吃了一惊。不能说是小的桌子上挤满了各色料理。色彩丰富的料理们各具独特的色香味，空空的胃袋仿佛把眼睛吸引在了上面一样。姑且认同特蕾西亚所说的的擅长料理不是夸夸其谈，然而却存在著一个问题。

「做这么多……真的吃得完吗？怎么看都不像是两人份啊」

「没关系的。过会儿卡罗尔他们也要来的所以，四个人的话就没关系了不是吗？而且我……不知道威尔海姆喜欢吃什么，所以就按照手边有的材料尽可能做了试试看，如果有这么多菜的话，应该也会有威尔海姆喜欢吃的了不是吗？」

「对于食物我没什么喜恶」

「真是白做了！」

变得气冲冲的特蕾西亚，将最后一道大碗的派放上餐桌，终于摆放完成。

不管怎么想就算是四个人也还是做得太多了，说不定特蕾西亚或者卡罗尔是大胃王吧。顺带一提，威尔海姆自负有识人的才能，格林毫无疑问是个胃口很小的男人才对。

「对于你很擅长料理倒是意外……说起来，为什么不让用人做呢？」

「向用人请教的事情倒是有过。——但是自己的事情，不喜欢任别人摆布。自己能做的事情就想自己做，所以这间屋子的事情也是请了最低限度的人来照看。而且，也没有在这里住多久啦」

用手指挠了挠洁白的脸颊，特蕾西亚若无其事地说著。

这间房屋是作为王国对身为【剑圣】的特蕾西亚的褒奖而赐予的，并非是内战终结的奖励，而是第一次上战场时就直接赐给她了。

也就是说，两年前这里应该就是她的宅邸了，在这里没怎么住过也就是说，战争中的生活的残酷，让跟随著军队行动的她一直持续著战斗吧。

由此可以看出特蕾西亚作为剑圣时是如何生活的。注意到这一点时的威尔海姆想到，绝对不能拋下她一个人不管。

——不应该让她第二次拿起剑了。

「……威尔海姆？」

「——」

睁大著眼睛的特蕾西亚，用脸摸了摸威尔海姆的手。指尖的肌肤十分柔滑。看向微微喘著气的她的嘴唇，桃红色的嘴唇带著高高的体温。就这样抱著她，涌上来的思绪都变得一片混乱，消散一空了。

「威、威尔海姆……不行。那个，你看，晚饭都要冷了……」

「你不是说做了冷了也很好吃的菜吗？」

「但，但是！果然趁热吃会更好吃，我想！」

被拉到怀里，变得手忙脚乱的特蕾西亚用奇妙的音调说著。用手摸著狼狈起来的她的红发，像是为了不弄坏那艳丽的长发一般温柔地抱著她。感受著深爱的男性的气味和心跳，特蕾西亚像是承受不了一样闭上了眼睛。

「——！果然不行！卡罗尔他们就快来了啦！」

这样说著，最终特蕾西亚的自制心击退了心烦意乱，从威尔海姆胸前挣脱出来，用和头发一样红的脸色喘息著说

「今天，不行。应该四个人一起愉快地进餐，交换两年间形形色色各种各样的有趣的话题才行，好吗？」

「即便是听了闲聊也不觉得有什么值得高兴的事啊」

被猎物逃掉，稍稍有点不高兴的威尔海姆对特蕾西亚摇了摇头。她则大声的说著「才没有这样的事呢」用红著的脸说。

「两年这样长的时间哟？发生了各种各样的事情，想法和情感有所改变也是当然的……」

「才没有这样」

「你这样说是很高兴，但是，但是你想，两年过去了……对了，刚好在典礼当天赶回王都什么的，还真是巧合呢」

「关于这个，当时你的事情整个国内都是你的传闻，怎么可能是偶然到的呢」

「这样啊！也是呢！」

糊弄的水平太差了，特蕾西亚的发言几乎可以说是支离破碎的级别了。对她的混乱苦笑以对，但是，威尔海姆在自己的心中转折道。

能在典礼当天回来赶上仪式并不是偶然。只是这之所以不是偶然另有他因。那就是——

「那两年，经常从罗兹瓦尔那里听说你的事情呢」

「……经常？」

「嗯。那两年在国内的各个地方流浪著，不知道从哪里知道我来和我接触的女人。嘛，除了托那家伙的福赶上了仪式以外，什么令人在意的事都没发生就分别了，没有感谢她是不是不义理的举动呢」

说著，威尔海姆的脑海里回想起了那个蓝发的女人——罗兹瓦尔·J·梅萨思——的样子。这个左右瞳色不同的女人，是内战初期就结识的五年以上的老相识了。尤其是，和威尔海姆相遇时她还总是非常多嘴，威尔海姆从心底警戒著这个心思难辨的女人。

威尔海姆失踪的两年间，只有她好几次地来拜访过，告诉他王国军和特蕾西亚的近况。每次，即便是辛辣地挖苦她也无动于衷。

实际上，要是没有她的情报，在重要的典礼之前回到王都的可能性也不是没有，但是，坦率地讲，是欠了她很多人情没错。

「女人，两年，经常……」

「……特蕾西亚？」

「威尔海姆，稍微把手，伸给我一下？」

「——？」

小声嘀咕著什么，突然特蕾西亚的脸上浮现出了笑容。对这个奇怪的态度，威尔海姆皱了皱眉，总之先如所说的那样伸出了手。特蕾西亚温柔地握住了手背——然后突然间，威尔海姆就感到天昏地转，重重地摔到了地板上。

「——唔、哇！」

「我心情稍微有点不好所以先回房间了，晚饭就你和卡罗尔他们三个人吃吧！」

「你这可不像是心情有点不好而已啊……」

「够了！」

连一点点订正的话也不允许，特蕾西亚留下尖锐的话语离开了餐厅。看著红发的身影逐渐走远，威尔海姆除了翻白眼别无他法。

「究竟怎么了……？」

「刚刚那是什么声音？……威尔海姆，你怎么坐在地上？」

不明白她突然发怒的原因，正发著呆的威尔海姆身后，听到了骚乱的卡罗尔赶来了。她身后格林也在。两人看著威尔海姆坐在地上的样子，露出了困惑的表情。

「特蕾西亚小姐怎么了？难道说，是亚人残党的复仇？……」

「等，等一下，不是这么夸张的事情。虽然不明白原因，那家伙突然发火给我来了个过肩摔……虽然被狠狠摔了一跤，但是我」

「现在是在意这些小事的场合吗？特蕾西亚小姐生气了可不是小事。做了什么，说了什么，怎么惹怒的！给我说！」

明白了是威尔海姆被摔出去，卡罗尔责骂著受了伤的威尔海姆。本来就急性子的卡罗尔，遇到和特蕾西亚有关的事情就越发如此了。连安慰著她的格林的手都甩开，用危险的眼神看著威尔海姆。

「把发生了什么详细地说出来！根据情况而定，最高可判处你死刑」

「冷静点。我只是，把自己先前两年的经历稍微聊了聊而已。在国内流浪的事情，和罗兹瓦尔几次碰面的事情，典礼当天……」

「和梅萨思大人？你、刚刚是提到了梅萨思大人的名讳吗？不对，说到底你们究竟是怎么取得联系的？」

「并不是我主动联系的。是对方来找我……」

「吵死人了，可恶的男人！稍微信任你一点，就把我当笨蛋欺骗啊！」

被毫无理由地中伤，威尔海姆闭口不言了。看到威尔海姆不配合的态度，卡罗尔飞退出餐厅，跑向特蕾西亚的寝室。

「特蕾西亚小姐！特蕾西亚小姐！您感觉还好吗？卡罗尔来陪你了！」

大声喊著跑过走廊，卡罗尔追上了特蕾西亚。看到了这一幕，威尔海姆只是继续坐在地上一言不发。

「——」

于是，对这样的威尔海姆，一样无言的格林伸出了手。握住他的手站了起来，轻轻拍了拍身上的灰尘，叹了口气。

「……什么嘛」

「——」

对无声地投来责备的眼光的格林，威尔海姆声音小了下去。但是这声音缺乏霸气的原因，也并不都是因为有谁在听。

「是我的错吗？」

『是你的错』

一开始就准备好的，递出的纸片上用大大的字写著。

「可恶」

夺过那张纸，生气地撕碎，手里拿著乱糟糟的纸团，威尔海姆回过头，看著餐桌叹了口气。

「桌上的就我们两个来吃了。……不许有异议啊」

「——」

回应威尔海姆的要求，格林敲了敲肩膀坐到了座位上。在他的对面，威尔海姆也坐了下来，开始挑拣自己的份。

还热著的菜每一个都很合威尔海姆的口味，让人欣喜，但是却感觉现在比起吃著冷掉的菜更让人感到寂寞。

*** 后篇

1

——结果，被惹怒的特蕾西亚一晚上都没露过脸。连解开昨晚的误会的机会都没有。

「哼，一开始是不是误会还是两说呢」

这样满腔怒火地说著，是正一起用早餐的卡罗尔。追上不高兴地回屋的特蕾西亚，听了她一晚上诉说的她，即便是伶俐的美貌也无法掩盖地敌视著威尔海姆。

虽然已经习惯了被她针对，但是现在的视线比之前还更尖锐。

「——」

「啊啊，格林，抱歉。本来，一起吃早饭是我提出的……」

『请不要在意』

无声地在席间劝说，卡罗尔的凶狠表情稍微缓和了。苦笑著拿出笔谈的纸。就这样三人就座了。

只是，无论等多久都等不到特蕾西亚，威尔海姆又开始叹气了。

「所以呢？聊了一晚，连劝她出门一步都做不到吗？」

「明明是你伤特蕾西亚小姐的心如此之深才对！这也好，那也好，都是因为你这个家伙的不检点引起的！稍微有点羞耻心吧！」

「你这家伙，还要提起吗？你这尖锐的口气是很让人怀念没错，但是不要得意忘形了」

还没开始吃饭，卡罗尔和威尔海姆就开始越过餐桌互相敌视著。

以不在场的特蕾西亚为中心，两人的关系可谓是非常复杂了，只是，两人确实都很重视特蕾西亚的事情。然而这个共同点，现在却成了两人之间矛盾的致命的导火索。

一触即发的剑气仿佛喷洒著火花，随时要把餐桌变成战争——就是这样的场面。

『到此为止』

两人之间插入了一张纸，纸片的两面写著相同的话语，让两人停止了可怕的对峙。无声的战士向战友和恋人投以严肃的目光，指了指餐桌。

那里放著的早餐是格林亲手做的，冒著的热气已经渐渐消散了。

「抱歉格林、让饭菜变凉了，我们开动吧……」

「——」

对于难得变得强硬的格林的主张，卡罗尔立刻变得温和了起来主动道歉，看了恋人的表情，格林温和地笑了。接下来看向了威尔海姆。

那和看向卡罗尔时相似的微笑，带有绝对无法违抗的决心。当然，威尔海姆也被气势压倒，没有了一定要分出现状是谁的错的打算。

「……抱歉了吶」

移开视线，威尔海姆用小到听不清的声音道了歉，让格林听到了满足的话语。

格林做的早餐，比起特蕾西亚当然是差了点，但是也是令人满意的一餐。早在王国军共事时，威尔海姆就很清楚他做饭的特长了。

「真是令人怀念的味道」

喝著咸味的鲜汤，威尔海姆下意识地呻吟道。听到了这个的格林稍微露出了惊讶的表情，很快拿出了一张纸，迅速地写道

『昨晚听说的，你要回王国军了吗？』

突然给出的书面的质问，是关于威尔海姆未来去向的内容。

尖锐的笔锋留下的飘逸字体，仿佛传递著格林本人的质问的口气一样。昨晚惹怒特蕾西亚后两人为了吃完都拼了命，结果几乎没有闲暇好好交流。

对和文字一样聚精会神地看著的格林，威尔海姆喝完汤说

「这件事我和博尔多说过了，结果却好像行不通。那家伙，一直说著些听上去了不得的话把我劝退了」

「不是听上去了不起而是本来就很了不起。谢鲁盖夫阁下在内战时也为你活动过，还被招到王国军司令部做检查。他作为平民，爵位之高已经是一个异例了。而且，爵位的升格也已经内定……」

「你还真是知道得清楚啊，格林要嫉妒了哦」

在听到意料不到的博尔多的晋升话题时，威尔海姆揶揄说。但是威尔海姆的揶揄，很快就被之后卡罗尔的话给击碎了。

「因为家业的关系，才对王国的内幕如此了解的。毕竟要是特蕾西亚大人从『剑圣』的职位上引退的话，会变成什么样之类的，必须了解清楚」

这是对授予特蕾西亚的『剑圣』称号，卡罗尔的个人见解。

「威尔海姆。我希望特蕾西亚大人以后能过上安稳地笑著的生活」

「——」

「你这混球的死活，说实在的我没有兴趣。但是，如果这和特蕾西亚大人的幸福相关的话就不一样了。——所以我可不希望你只是看上去能给特蕾西亚小姐幸福」

抖动著纤长的睫毛，卡罗尔认真地看著威尔海姆。那眼神和声音中的气概，一定是她每一天对特蕾西亚的珍视的结晶。

虽然为「剑神」所爱，然而心地善良的她在人间也不止被威尔海姆一个人挂念著呢。

「——啊啊。我也是、只有这一点是我无论如何也想达成的」

点著头的威尔海姆，觉得卡罗尔此刻看上去也没那么不顺眼地回答道。

2

充满紧张气氛的早餐结束后，格林和卡罗尔两人告辞离开了宅邸。

卡罗尔直到最后都在无数次地向威尔海姆念叨著特蕾西亚的事，格林则安慰著那样的她，留下『在军队等著你哦』的激励就走了。

「这家伙也好，那家伙也好，就不能直白地和我说吗」

送别两人，回屋的威尔海姆感到一阵虚脱感喃喃道。

「那个，我现在要出门了。会好好在晚上回来的所以别担心。……今天一起吃晚饭吧」

「——」

一言不发就出门会让人不安，于是威尔海姆解释说。

这样告别后，房间内传来一阵衣服摩擦的声音。把这个反应作为收到的讯息，威尔海姆出门了。

结果，在还没能见到特蕾西亚的脸的情况下，威尔海姆一个人走向了清晨的王都。

这样走在王都的街头也是长久没有的事情了，威尔海姆对街头气氛的变化惊讶极了。

两年前，『亚人战争』最激烈时的王都与现在相比，气氛完全不同。

并不是可见的实物有什么大不了的变化。街道本身还是那个样子，只是走在路上的行人的表情和心情的变化就有这么大的差别。连日照都变得更让人感到明亮温暖了。威尔海姆不由得眯起了眼睛。

内战时，王国内时常蔓延有不安和惶恐，如今阴霾散去，人心也重新变得安慰悠闲。——这应该是不错的变化吧。

而后，也正是为这个变化，特蕾西亚挥剑奋斗了两年。

「——」

作为『剑圣』度过的两年对于特蕾西亚来说，应该是痛苦和混乱的时光吧。但是，也正是因为有了这样的日子，才有由此诞生出来的和平。

理应赞美如今的光景才对，威尔海姆却抱著复杂的心情。

「——和宰相辅佐说好的一样呢，我是威尔海姆·特雷亚斯」

「嗯。听说过你。请向这来」

心中的情感如同旋涡一般，威尔海姆走进了王都的顶峰——格林尼卡王城，并向城门卫兵传达了自己来此的理由。

身披利甲的魁梧卫兵的带领下，威尔海姆静静地在走廊前进著。

王国军时代，几度走进过王城不过，这样一个人走进王城还没有过。时远时近，王城留给他这样的印象。

「宰相辅佐在这里等你」

领头的卫兵打断了他的回想，威尔海姆在目的地前和卫兵分别。从外侧敲响木门，等候房间里传来「请进」之后，威尔海姆打开了门。

迎接的房间内部，是和王国宰相辅佐头衔不符的朴素内饰，除了办公桌和接待用的沙发外，剩余的家具就只有书架之类的。

专注于实务的内部风格，确实和主人的气质很相称。

「欢迎光临，威尔海姆阁下，请过来吧」

「啊啊」

听了如太阳般温暖的知性声音，威尔海姆如言坐了下来。坐在对面的是身材细长的文官——麦库洛托夫·马库马洪，既是威尔海姆约定的对象，也是他回归王国军的关键。

「昨天没能好好详谈，特意让你来这里一趟不好意思了啊」

「……没事，昨天和今天都耽搁您的时间帮我，我这边才是，要感谢您」

「——嗯，原来如此。这还真是和从谢鲁盖夫卿那里听说的一样呢」

形式地交换社交辞令后，麦库洛托夫温和地笑著点了点头。对这个反应威尔海姆皱了皱眉，说著「哪里哪里」摇了摇头。

「我和你的见面，除去单向的，距今已经是4年以上事情了。回忆起那时的印象，对这变化还真是令人感慨」

「单向的见面……?」

「对此也没有必要感到惊讶吧。——内战终结的仪式上，这个国家四面八方的人都来了哦？自然所有人都认识你了。」

对正愉快地说著的马库洛托夫，威尔海姆感觉真是个糟糕的开头沈默著。

确实是让人无话可说的单向的见面，威尔海姆的名字和外貌，在当时的王都可是沸沸扬扬。

实际上即便是现在这个话题也还有相当的热度，虽然威尔海姆本人没有什么自觉，但是他和『剑圣』的关系可是非常令人瞩目，两人的故事甚至被编排为戏曲在各地传扬。

话说回来

「你拥有不下于『剑圣』的实力的事可是广为人知啊。也因此回归王国军的事，也能很简单达成。我向你保证」

「这、这样吗？但是，博尔多可不是这么说……」

「当然，谢鲁盖夫卿的考虑也是有道理的，事实上，你将被授予的骑士称号舍弃，出于私心逃离军队，对这些事情感到失望的人，现在也还反感著你」

「——」

「但是，这些问题都是时间可以解决的。重要的是你的实力对王国军很有帮助，而且你自己想回军队也是事实。」

摸著自己的下巴，麦库洛托夫思路清晰地讨论著威尔海姆的回归问题。对于王国宰相辅佐强而有力的肯定，威尔海姆也只能瞠目地听著。

文官和武官，即便两者之间的隔阂由来已久，想要无视宰相辅佐的意见也是做不到的。像一个士兵的回归这种小事，对他来说易如反掌。

「剑鬼」威尔海姆的军队复归，仿佛近在眼前了。只是——「——即便认可你回归王国军，但是要除名特蕾西亚阁下还是做不到的」

「——唔」

「对王国军来说，无论是『剑鬼』也好，『剑圣』也好，都是有用和重要的存在。没有放弃的理由。对于这一点，不容置疑。」

「那家伙……! 那家伙，不想再战斗了。」

「真心话可不是这么容易理解的哟」

到此，温和的气氛一扫而空，变得冷酷的麦库洛托夫一副吃定了威尔海姆的样子。宰相辅佐无情地眯起眼睛回复剑鬼说

「即便特蕾西亚殿下内心抗拒，她也不是个优柔寡断的人，况且她也做不到拒绝王国对她的邀请，恐怕，是这样。」

「——」

麦库洛托夫所推测的情形恐怕是事实，威尔海姆也只能闭口不谈。

如他所言，特蕾西亚是个心地善良的女人，即便内心不想再挥剑了，到了她不得不挥剑时，她也会咽下泪水握住剑柄。

威尔海姆很清楚这一点，但是即便如此，威尔海姆也不希望这样。

「要怎么做你们才能……」

「当然，说到底这只是我的一己之见，但是，王国军的领袖们也得出了一样的结论。这是无可动摇的。」

无情地，麦库洛托夫否定了威尔海姆的心愿。

威尔海姆回归军队的问题先不提，特蕾西亚想要隐退看来是怎样都不可能了。

「关于你回归军队的事我会好好操作的，无须担心。关于特蕾西亚殿下的事情么……嗯，应该好好聊聊」

「聊聊？」

「就算你一个人再怎么想，也无法简单地得到结论，容易误入歧途。这样的话就没人能阻止你了。因此心头有烦恼的时候就该和别人商谈」

这是劝解吗。对麦库洛托夫的话威尔海姆挑了挑眉毛。

看著年轻人的表情，麦库洛托夫闭上了眼睛，又像最初那样温和地笑了。

「也有除了你以外谁也做不到的事。——好好想想吧。」

3

和麦库洛托夫谈话结束，威尔海姆向王城外走去。

脑海中想著各种事的他，得出答案并不容易。本来就是不擅长思考，更喜欢用得意的剑术来解决问题的人。

托麦库洛托夫的福可以回军队——这算是好消息，但是随之而来的坏消息让人提不起劲。

「就算说让我好好聊聊……」

格林和卡罗尔，当然已经聊过了，博尔多和麦库洛托夫也。无声的匹博特也拜托过了。剩下的就只有特蕾西亚本人了。只是，如果和特蕾西亚商量的话，他很清楚她会怎么回答。

她一定会忍受著痛苦，脆弱地笑著点头答应王国的要求吧。

「那个**，要让别人明白自己的感受啊……」

在脑内责怪著自己想象出来的特蕾西亚，大概本人的反应也差不多吧。于是，威尔海姆怎么也不能和特蕾西亚聊起这件事。

一边感慨著自己人际关系狭窄的不便一边思索著探头看著天空

「只能拜托罗兹瓦尔了……也不知道她在哪里啊」

天空上浮现出的商谈候补一个个消失，威尔海姆露出了无可奈何的表情。

罗兹瓦尔·J·梅萨思要是在的话，应该能为现在的威尔海姆的烦恼给出有效的策略吧。只是，真心不想拜托她啊。

说到底，现在自己和特蕾西亚关系变得微妙的一个原因就是罗兹瓦尔。可不想和特蕾西亚把关系弄得更僵了。

只是，这样一来的话，真的是束手无策了。

「——等一下」

停下脚步，威尔海姆自言自语说。

极目远眺，威尔海姆看向视线边缘的一栋建筑物。一座位于王城旁，高高竖立的石塔、监狱塔。

昨天，威尔海姆才从中脱身的地方，确实有很会「侃侃而谈」的人在里面呢。

「那么，这就是你特意来见我的理由么？真是要让人哭出来了啊，小哥」

「别说废话了，时间可是很有限的啊」

踏入冰冷的地牢，看著铁栏杆里侧的男子，威尔海姆交叉起手臂说。愉快地呜咽著的，是长发的美男子。

同时玩弄著贵族小姐6人，以重恋罪（原文如此）被投入监狱的『六枚舌』奥路菲。

虽然只是短暂的狱友，威尔海姆还是来找他了。因为希望把这也好那也好各个视角可能收集到的解决方法都收集到。

「而且，你居然就是击败『剑圣』的『剑鬼』什么的，真是让人惊讶。难怪进了监狱塔还出的去呢。你好啊，偷心大盗！」

「小心我翻过铁栏杆把你砍了哦？想要早点被处刑吗？」

低下头，威尔海姆散发著些许剑气地威胁道。但是奥路菲耸了耸肩一副完全不怕的样子。看来至少关于他的传闻中胆大包天这一点是没错的。

毕竟是能同时说服六人的男人，要是这点自信都没有就麻烦了。

「话说回来，帮帮小哥的恋爱历程倒是轻而易举，不过这对我又有什么好处呢？我可不白干哦？」

「能回到军队的话，我也会重新成为骑士，这样的话就可以帮你说点好话，也许就能早点从这里出去了。」

「好吧，答应了！我要是排上用场的话，老大，什么都要为我说哦？」

「得意忘形的家伙……」

对没有恶意的奥路菲，威尔海姆苦笑著把现状介绍了一下。当然，纤细的情感部分大多省略掉了。应该说不愧是擅长说话的「六枚舌」吗，一问一答间就把事情的大致掌握了。

「事情的大概我已经知道了。也包括小哥你比我想象的还傻得多这一点。」

「我要砍了喔？」

「你这个什么都用剑解决的态度，就是这个」

就在威胁的前一刻，牢中的奥路菲用手指著威尔海姆说。从他的这个发言来看，还真是对威尔海姆的习惯了解得很啊。

「你自己也说过了不是吗？小哥你擅长的是剑，不如说你除了挥剑就没什么别的才能了。真是除了剑能解决的问题以外什么都做不到的残疾人啊」

「所以才说了我现在很困扰啊。要不是剑不能解决的话……」

「不对哟，小哥。为了重要的事物，即便是自己不擅长的事情也要去做的态度虽然很男人很帅气，但是却不理智啊。好好用用头脑明智地解决问题才对。听好了」

态度错了。奥路菲这样断言道，对威尔海姆点了点头。

然后，『六枚舌』向『剑鬼』展示了完全不同的另一种答案，那是——

「如果剑以外的手段解决不了的话，你就把它变成能用剑解决的问题好了。除此以外，还有什么别的胜算吗」

露出了不怀好意的笑容，奥路菲对威尔海姆眨了眨眼。

4

——夕阳西下时分回屋时，从餐厅传来了一阵食物的香味。循著气味，威尔海姆走向了餐厅，走进食堂打开的门，正在摆盘的红发身影映入了眼帘。

纤弱的肩膀，苗条的曲线，和左右摇摆的臀部，看著就很让人满足。

「——回来的话就好好说‘我回来了’。做错了事一样不发什么的，你又不是小孩子了，好好挺直身板」

「倒不是因为这个才不说话的」

「那又是为什么呢？在想怎么向我道歉吗？」

不回头的，特蕾西亚用更加闹别扭的口气说。呆呆地想著沈默的理由，好像也不是说得出口的内容。结果，对就这样无可奈何地沈默著的威尔海姆，特蕾西亚叹了口气说

「真是的，一点都不坦率……虽然知道威尔海姆就是这样的人」

「不好意思啊，说起来，你怎么回心转意了？」

「……晚餐，一起吃什么的不是你说的吗？哼」

发出可爱的鼻音，特蕾西亚弯下腰，把围裙挂在了椅子上。

餐座上的料理，今天刚刚好是两人份。看起来不像是有人要来的样子，这样做了饭等自己回来，让威尔海姆心中充满了疑问。

毕竟，他可不记得自己早上说过什么能修补两人间关系的话。

「早饭把威尔海姆一个人拋下了不是吗？那样做有点太残酷了也说不定……所以要是晚饭也这样的话也许太过分了」

「……火候有点过了」

「稍微过火点才好吃不是吗！又不是全烧焦了！而且我很擅长控制火候的才对！你还有什么不满吗！」

对于特蕾西亚咬牙切齿的表情，威尔海姆有点意外地皱了皱眉。因为事实上确实稍微有点过了火候，虽然也不是不能吃的程度。

仿佛从表情上读懂了他在想什么，特蕾西亚在正对的椅子上坐了下来。

「两年间一直在担心你吃什么。……莫非，是谁特意做给你吃的吗？那个，那个，那个人……」

「如果你想说是罗兹瓦尔的话你就想错了。都说过了，是那个人自己来找我的，我可从来没有欢迎过或者感谢过她。除了一次以外都没有」

「那个感谢是……?」

「告诉我典礼的时间那次。要不然的话也没那么巧遇到你。」

「这、这样吗……啊哈哈」

对正对著坐著的，把事情和盘而出的威尔海姆，特蕾西亚的脸又红了起来。在这样尬笑著的特蕾西亚面前，威尔海姆低下头看了看餐桌。

虽然料理的量比昨天大减，种类却没有减少。基本和前一天的一模一样。真是为特蕾西亚擅长的菜之多而惊讶。

「真是多才多艺啊」

「多才多艺什么的……是在赞美我吗？哼哼、一般般啦」

对笨拙的威尔海姆的话，特蕾西亚高兴地笑了起来。这是时隔了一整天，长久没见的她的笑容。

不自觉的，那个笑容让人感到安心，威尔海姆也感觉心情舒畅了。

「那么，开动吧。喜欢什么菜，一个个地都要把感想好好说给我听哦？」

「哪个都很好吃，这是我昨天的感想」

「今天可不能这么放过你。我会看著你好好吃的所以，让我看看你究竟喜欢吃什么吧，因为早就知道从你的嘴里得不到有什么参考价值的话了。」

看起来无论威尔海姆的评价多差，都只能进一步激发特蕾西亚料理魂的样子。以此为契机，她的怒火也消散了，无论是什么样的评价都能欣然接受。

就这样寻求著威尔海姆对每道菜的评价，晚餐时间就这样平和地过去了。

特蕾西亚的料理本领，昨天就见识过了。只是，比起昨天只是为了吃完而吃，今天能体会到更丰富的口感。

自然也就觉得今天的晚餐比昨天好吃多了。

「怎么样？今天比昨天更满足吗？」

「是这样。比起昨天，今天的更好吃」

「真的？太好啦！昨天是王国南部的料理，今天是北部的料理哦！说不定北部的菜更和你口味」

「谁知道呢。也许是因为和你一起吃吧」

「嗯哼，嗯哼。不要突然这样!……真是的」

只是不知不觉这样说说而已，特蕾西亚却过剩地反应了。看著喝著水缓解咳嗽的特蕾西亚，威尔海姆的脸色严肃了起来。

发现留意到这一点的特蕾西亚也正坐了起来，威尔海姆说到「我有话想和你说」

「好、好的，我听著……」

「实际上，是关于我回归军队的话题。稍微和上面的人聊了聊，好像可以平安地回去了。让你困扰和担心了真是不好意思」

「啊，是这个啊！什么嘛，太好了。说著出门了就出去了，我还很不安呢……」

「我是不会花心的，别让我总是说啊」

是多没有自信啊，特蕾西亚总是满是疑心的。

就威尔海姆来说的话，不如说是打从心底认为世界上没有比她更好的女人了。当然这样的想法，他是绝对不会说出来的。

「啊！当然啦，威尔海姆能回军队这件事我也很高兴哟。你的话，还是和格林还有博尔多阁下这样的朋友在一起工作时看上去更快乐」

「朋友……倒没有这么想过」

一句话来说就是战友，他们之间一直是这样紧密相连的关系。

先不提这个，特蕾西亚为自己回军队的事很高兴。剩下的问题就是特蕾西亚在军队中的立场了……

「特蕾西亚，实际上有重要的事要说」

「那、那是？」

「你很不安吶？不是你想的那样所以安心吧。明天一天我都要外出。会在和今天差不多的时间回来——但是你明天绝对不要来王城」

「——」

低声、用强硬的语气说道。听著这话特蕾西亚疑惑地睁著眼睛，用手遮著嘴，对话语迷惑道

「不要进城……为什么？」

「没有为什么。好好听我的话。不会让你后悔的。」

「我进不进城什么的，怎么会和后悔不后悔什么的扯上关系呀。你这样说才让我感到更不安呢」

对不足的说明感到不满，却没有要从威尔海姆那里追根究底的打算。两人无声地对视了一会之后，沈默的特蕾西亚对威尔海姆败下阵来。

她深深地叹了口气，说著「我明白了」无力地点了点头。

「虽然不能说理由，但是不要进城什么的，明天一天这样就好了对吗？」

「啊啊，是的。这就拜托你了。」

「这些都依你……不过我能问一个问题吗」

从椅子上起身开始收拾餐桌的特蕾西亚问道。向她转过头，特蕾西亚竖起一根手指说

「万一、打破了这个约定的话……你会讨厌我吗」

「只会真的很生气而已」

「这样啊，我明白了」

挥了挥手，特蕾西亚搬起盘子走向洗碗的地方。看著左右摇晃，心情不错的臀部，威尔海姆稍稍陷入了思考。

按今天的口气，要是特蕾西亚听说了什么，说不定会打破约定进城。

「嘛，算了，都已经说了别来什么的，应该不回来了吧」

这样理解了之后，威尔海姆搬起剩下的餐具，追上了特蕾西亚。

5

第二天，在早起的特蕾西亚的注视下，威尔海姆连续第三天走向了王城。

只是，今天的他的心情，和此前的完全不同。——不对，不如说前两天的他才是和之前完全不一样才对。

就这样，仿佛要把城门淹没的凶猛气势，才是他——威尔海姆·特雷亚斯身为『剑鬼』的实力和身为只身击败王国最强的男人的证明。

「——武运昌隆」

对走来的威尔海姆这样说的，是城门等著他的披甲卫兵。虽然微微颤抖著的士兵的脸隐藏在盔甲下，但是想必已经浑身僵硬，满头大汗了吧。

只是一眼，他就明白了今天的威尔海姆的强大。

那是将功绩卓著的当今『剑圣』击败，人称『剑鬼』，独步王国军的强大存在，是剑士实力的极限。

威尔海姆走向一个视野开阔的地方，映入他蓝色瞳孔中的，是充满了汗臭味的练兵场。

在四角为墙壁所包围的这个地方，顾名思义地站著许多士兵。

——要是加上王国军中的强者都在这里集合的情况的话，就更是如此了。

「来了吗？大**」

走向练兵场中间的一瞬间，迎接他的是‘**’的喝骂声。声音的主人正是有著茶碗粗细手臂，手持战斧的魁梧大汉——

「博尔多吗？不是已经从第一线退休不干了吗？」

「哈哈哈哈！说什么蠢话。我还是现役的将军呢。虽然稍微退休了一阵，但是你就以为我放弃了平时的练武吗？只有热衷武道这一点你我是一样的哟」

大声笑著，博尔多站在了威尔海姆正前方。威尔海姆的视线在他身上停留了一会儿，接下来看向四周的面孔。

都是些散发著干练凶猛的剑气的家伙。威尔海姆势单力孤地站在，看上去就像个弃子——那一圈人中，也有两个熟悉的身影。

「连你们两个也要掺一脚吗？稍微也有点自知之明啊」

哼了一声的威尔海姆说看著的，是金发的女骑士和持盾的战士——卡罗尔和格林两人。装备著自备的长剑和硬盾的两人，对这个挑衅抬起了头

「别太自恋了。这里集合的所有人可都是精锐。鲁莽地来挑战的结果，只会是你自取其辱而已。」

「我明白这里的家伙都很有一套。但是对于你在这里我很有疑问」

「你说什么——？」

『卡罗尔，冷静一点』

对于一下子就被挑衅到，面孔通红的恋人，格林制止道。然后他一脸老好人地看向威尔海姆，苦笑著拿出一张纸片

『我可不会手下留情哦』

「——尽管按你说的做吧」

笑著看著战斗开始的宣告，威尔海姆的笑容一下子狰狞了起来。

其他的人里，还有不少内战时代的老相识。也包括谢鲁盖夫时代的队友们在内，看著他们回旋交织的剑气就明白他们有多斗志高涨了。

「——看上去，全员都基本到齐了呢」

突然打破了练兵场剑拔弩张的气氛的，是一个稳健的男子的声音。

从上方传来的视线，是正在观众席俯视著练兵场的麦库洛托夫。穿著深红色的长袍的宰相辅佐，看著场下的战士们的姿态，深深地点了点头。

「真是壮观。而且气势也很惊人」

「我可不是来让你围观的，好好遵守约定啊」

对威吓著的威尔海姆，麦库洛托夫闭上眼睛笑了笑。然后他回过头，恭敬地说了一句「请到这里来」退到了一边。

看见他这样，练兵场内的众人都感到疑惑，紧接著，全员就都感到膝盖忍不住颤抖。要问为什么的话，因为那里出现的是——

「——很好很好。不用那么怕也可以。寡人只是来看看这次比试的结果而已」

这样说著，用浑厚的声音笑著的是身披华丽的外套和礼服的四十岁左右的男性——不对，不是这样表现就能描绘的身份。

这个男人，是整个练兵场，整个王城，整个王国中最身份显赫的人物。

「吉奥斯·露格尼卡陛下——」

「确实，如麦库洛托夫所言，真是壮观啊。这样精英汇聚一堂的景象，自从典礼之后，再也没有见过了。」

这样点著头的人——吉奥斯·露格尼卡,正是亲龙王国的现任国王，也是对于威尔海姆来说，在当下能帮上忙的关键人物。

吉奥斯看向跪下的群臣，在其中找到威尔海姆的身影后，抬起眉头

「哈哈哈，特雷亚斯哟，和只身来找寡人的昨天的态度真是完全不一样呢」

「……昨天真是非常失礼了。此外，对于陛下能赐予此次的机会，除了对陛下仁心的感谢以外无话可说」

「无妨。你所提出的挑战也有让我心动之处。此外，仪式上挑战『剑圣』时你的剑术十分精彩。即便只为了再看一次你的剑舞，举办今天的挑战就已经值得考虑」

摸著短短的金发，吉奥斯的红瞳中散发出小孩子一样的光芒。那态度，姿势，和思考方法，真难以让人相信是一国的王族。

但是，这正是露格尼卡的王族的特点。虽然王既没有处理内政的手腕，也没有令世人称赞的才能，却十分有人情味。这样的一族——

「想遍了可能说服军队的首脑同意的方案，除此以外别无他法了……没想到能得到国王陛下的认可，真是诚惶诚恐」

吉奥斯的一旁，摇著头的麦库洛托夫也想起了一开始的惊讶。

昨天，作为接受了麦库洛托夫忠告的结果，和奥路菲商谈之后，威尔海姆想到了一个能将特蕾西亚从王国军中除名的方法。

那方法，正是通过说服国王吉奥斯来实现的，也是让精兵集中在练兵场的目的——让他和他们决斗来证明。

「那么，来让我看看吧，特雷亚斯。将王国的精锐，自己一个人全部折服。如果能做到这一点——用自己的剑证明『剑圣』和王国军是必要的，那就满足你。」

这就是傻乎乎，不论到哪里都一把剑冲到底的威尔海姆所得出的解决方案。

但是这样傻傻地潜入国王卧室的阳台的威尔海姆的心愿，被见过『剑鬼』在仪式上剑舞的国王笑著认可了。

就这样，练兵场内集结了露格尼卡王国从内战终结典礼后就没有过的数量的精锐。

要将他们全部打倒，将『剑圣』的存在用『剑鬼』取代。

将特蕾西亚的剑和她身为『剑圣』的存在全部夺走，斩断干凈。

——证明她只要微笑著，像个爱花的普通女子那样生活著就足够了。

「——接著，特雷亚斯」

抬高声音，吉奥斯从麦库洛托夫手中接过剑，投向地面。将回旋著的剑接住，威尔海姆拔出圣剑，走向剑前的精锐们。

厚重，有著明亮锋芒的剑气包围了练兵场，战场已经构筑完成了。

「那么，开始了——寡人期待著『剑鬼恋歌』哟」

吉奥斯的话音刚落，威尔海姆就上前走去。

在那里迎击他的，是同样前进著的博尔多,将手中的武器和斗志一起递出。

「唔吼吼吼吼——」

像野兽一样咆哮著。威尔海姆的剑击冲入了人群的正中。

6

——并不是从一开始，就打算打破约定去王城的。

特蕾西亚就和往常的自己一样，又陷入了烦闷和懊恼。在意著威尔海姆的事情。非常在意。说实话的话，越是思索，越是在意。

保持著越来越膨胀的爱意，想著他正在自己的视线看不到的地方做著什么，就越来越被不安和害怕所支配得没有办法。

又要被丢一个人了吗？这样的担心经常困扰著特蕾西亚。

「大概在王城里吧……对吗？」

回想起昨晚的对话和今早的送别，威尔海姆应该在王城没错，不如说不在的话反而才让人惊讶。

所以，仅仅是想见面的话，只要现在去王城就行了，但是。

「但是，都已经说了别来了……但是但是，果然还是担心……？」

很快换好了衣服，但是却又在玄关迷惘了很久，但是最后的最后，还是踏出了脚步，特蕾西亚出门去了。

一小时不到的时间里，特蕾西亚就这样自言自语著，一直笨拙地烦恼著威尔海姆会不会回来。

但是——

「这样的话，就变成稍稍有些不够浪漫的结果了不是吗？」

「诶？」

疑惑著，特蕾西亚抬起了头，令她惊讶的是对方敢于和身为『剑圣』的她搭话的胆量和那声线的熟悉。

那是几天前，和威尔海姆再会的典礼的早上听到的声音——

「啊啦啦，几天不见了呢。你还过得好吗？」

「你是……你是，罗兹瓦尔·J·梅萨思小姐？」

「真令人惊讶呢，我应该没有告诉过你名字才对。我也不觉得他会对你详细介绍我的事情，你是怎么注意到我的身份的？」

「不知不觉……只是觉得你大概应该是这个样子，我这样想」

蓝色长发的异色瞳美女——罗兹瓦尔对这话点了点头，「原来如此啊」认同道。被黄色的眼睛盯著，特蕾西亚皱起了眉头。

「那么，来我家有什么事吗？威尔海姆的话不在家哦？」

「不要这么紧张也没关系哦？我早就被那个男人甩了哟？他可痴迷你了。没有质疑这一点的必要」

「我，我才没有怀疑呢。我，我也有被爱著的自信的。」

挺著胸的特蕾西亚回击道。很快又向罗兹瓦尔不好意思地道了歉，毕竟人家刚说自己被威尔海姆甩了。这样还说自己有被威尔海姆爱著的自信什么的，真是没仔细思考就说出来了。

「没事，不必介意。请珍视你的那份心情。只要有著这的话，总有一天会成为引发重大事件的力量的」

「……您是为说什么而来的呢？如果只是为了来祝福的话，我现在就为了你准备茶和点心」

「并不是这样，你和我应该都明白才对。我是……——嘛，为了最后的最后的一个请求而来」

这样说著，罗兹瓦尔仿佛从肩上卸下了什么重担一样笑著。

「——」

但是，她的笑容在特蕾西亚看来，既脆弱又寂寞。

怎么会这样的呢地想著，却完全不明白。

7

练兵场的斗气正四处狂奔著，剑戟交鸣的热浪仿佛要把空气烤焦一般。

「——」

一阵风一般，在浓密的剑压中四处奔走的威尔海姆，将敌人一个个击倒，将精锐追击到无法战斗。

仅仅一人的『剑鬼』，面对四十人以上的精锐集团的追击，即便是其中以勇猛知名的人物，也对沐浴著的锋锐剑气感到悚然，心中的兽性高涨不已。

真是玩笑般的约定啊。即便这样，也追求著证明。

只有达成万夫难挡的条件，王国才会愿意放弃手中的强大力量。

「哇啊啊啊——」

摆动身体，在被枪命中前的一瞬回避的同时实现突进格挡，利用冲击力将身体震退，同时实现打击和回避的过程，获得了一口喘息的空隙。

深呼一口气，将肺中的氧气送到全身，身体和手脚的力气就又回复了。还能够战斗。还能行。这点程度，远不及自己打败『剑圣』的战斗。

「吃我一招，大**——！」

「——」

看见威尔海姆游刃有余的姿态，从一旁斩击过来的是博尔多的战斧。劈开空气形成的风压先一步压迫过来，威尔海姆转身迎向斧击。

轻身掠过，躲开痛击，然后借此机会，威尔海姆一剑刺向空当大开的博尔多。只是、

「格林你这家伙！」

飞入的坚盾弹开剑击，威尔海姆对战友的妨碍骂道。

希望他能够认真以对也是不错的只是，看来格林也是认真地要和威尔海姆作战呢。

特蕾西亚的心情，威尔海姆的想法，在理解这一切的基础上还是刀剑相向，也正是明白了这些，才到场的。

「——」

思考仿佛闪电般游走著，四肢向习惯了的名为剑击的动作加力。

一瞬间将疾走的剑刃连挥3下，即便格林挡下了其中两击，第三下还是赶不及，被一击命中发出哀鸣倒了下去。

——还有一个人，还有一个人。

「——」

无视倒下的格林，威尔海姆握紧剑，看向博尔多。

四十多人的精锐终于除了『猛犬』博尔多·谢鲁盖夫以外全被打倒了。

「特雷亚斯……」

长剑折断，用剑柄撑著站起来的卡罗尔咬著牙念叨著。她的周围，其他倒下的精锐们也都注视著战斗的进行。

『剑鬼』的实力令人惊恐，他的剑力和想象的一样，连基本的战术都没有就击败了众人。

感到悔恨，本该如此的，但是卡罗尔同时却又感到欣慰和欣喜

「结果，你这个家伙啊……」

让特蕾西亚露出笑容的也好，实现特蕾西亚的愿望的也好。

为了特蕾西亚比任何人都更强的人，结果，能做到的还是只有威尔海姆啊。

——这个事实真是令人遗憾，虽然为此感到高兴也是没有办法的，不过果然还是不甘心。

「上了哟，威尔海姆！」

「——来吧，博尔多」

短短的交流，而攻防的时间则比这还要迅速，剎那间就分出了胜负。

高声怒吼著回转著斧枪的博尔多重重向下挥下，剑鬼险险躲过击碎大地的一击踏前一步，封住了博尔多的动作。

反击被封住了，博尔多勇猛地笑了笑，就被一道银色的闪光击穿了。

高高的冲击音响彻练兵场，巨汉被剑击轻轻地吹飞了。

被打飞在泥土和烟尘中四仰八叉地倒下的博尔多终于止住了翻滚的势头。伸出四肢的他仰望著天空，用手捂著脸说

「——啊啊，可恶！输了输了！完败呢，大**！啊啊，可恶啊……!」

聚集在城中的精锐，其中最后一人也只能向『剑鬼』投降了。

此即是『剑鬼』剑力的证明。

8

看著倒在地上的剑士、跪坐著不能行动的格林、瘫成一个大字大声笑著的博尔多和不甘心地低著头的卡罗尔，威尔海姆长长吐出了一口气。

非常凌乱的呼吸中带有淡薄的血腥味，虽然尽力避开了被直击，浑身还是有强烈的针刺感，战意和剑压的压迫也非同寻常，剑鬼身心俱疲地看向观众席。

「——」

看到胜负的吉奥斯，他的红瞳里饱含著激动地看著威尔海姆，得到国王的点头示意，剑鬼将手中的圣剑收了起来。

突破了获得战斗胜利的条件，获得了证明，然而——

「漂亮的战斗，特雷亚斯！你的剑力和想法，确实地传达……嗯？」

称赞著眼前的景象，话还没说的吉奥斯的表情突然阴沈了下来。

随著这个反应，威尔海姆转过了头，随著国王的视线看向背后。

那里，站在应该是特蕾西亚没错的身影，正张大著眼睛，喘著气。

练兵场的入口，正站著红发的女人——特蕾西亚·范·阿斯特雷亚。

「威尔海姆……」

叫著男性的名字，特蕾西亚向练兵场中央走去，眼中摇曳著困惑。

发生了什么，现在又是怎么回事，她什么都不明白。只是清楚正在发生什么不寻常的事，除此以外一无所知。

「这是，你在做什么……？威尔海姆」

「……特蕾西亚，当代『剑圣』哟，那边的男性为了你从王国军除名的要求，和寡人谈判过了。用剑将『剑圣』存在的必要剥夺，将你除名」

「——！他说的，是真的吗，威尔海姆？」

作为被责问的威尔海姆的代替，国王给出的解释让特蕾西亚睁大了眼睛，用颤抖的声音询问著。

要是可以的话，为了不让她感到内疚，是想瞒著她的，但是现场被她看到了的话，就做不到保密了。

「啊啊，没错。」

「所以就像这样，把大家……连卡罗尔都」

对点头的威尔海姆的回答，特蕾西亚从参战者中发现了自己的侍从惊讶地说。卡罗尔则一副做了坏事的小孩被抓的表情动摇著，低著头。

其他人也一副脸色难看的样子，感到没法在『剑圣』和『剑鬼』之间插嘴。

「——」

威尔海姆也感到难以预判特蕾西亚心情地闭口不言。

会生气吗，会被打吗（家暴.jpg）。看上去也不像是会举起双手庆贺的样子。对于自己重要的事情在自己不知道的情况下被片面地决定了，她到底如何作想难以得知。

因此，威尔海姆猜测特蕾西亚大概生气了吧。而且，这猜测其实基本上对了一半，实际上，她也确实生气了，只是

「——陛下。为什么要开这样恶意的玩笑？」

「——什么？」

双手叉腰，特蕾西亚怒视著上面的观众席。既不是是事先预测到她会生气的威尔海姆，也不是一同隐瞒的卡罗尔他们，而是观众席上的吉奥斯。

对这不敬的发言，但是心情变差了的吉奥斯，只是对特蕾西亚的剑幕苦笑了笑，用手摸了摸自己的金发。

「不是啊，那个，寡人也没有恶意的哟？只是，你的丈夫实在是太认真了，我就想著，要不要也参加一下玩玩啊什么的……」

「诶？陛下！还不是我的丈夫呢！你这么说，真是的！」

「……特蕾西亚？」

在微妙的对话展开的同时，威尔海姆叫著脸色通红的特蕾西亚的名字。她「吓！」地奇声回复了他，又变得慌乱起来。

脸色又变得比之前任何一次都更红了。

「不，不对哟。这个是，那个，没有把陛下的旨意好好传达的我的错，不过陛下也有问题……」

「简单明了的，从头开始说明吧」

「诶多、那个，嗯，威尔海姆想要把我变得不是『剑圣』什么的确实很高兴啦，真的很高兴。但是……那个问题，早就解决了。」

玩著手指，避开视线的特蕾西亚就这样做出了爆炸式的发言。

威尔海姆难以置信地瞪大了眼睛，当然，同样得知这件事情的练兵场众人也一个个精神叫喊了起来。发呆说不出话的人也很多。

对对此苦笑的特蕾西亚，威尔海姆无声地责备道。

「那，那个，威尔海姆……先生？」

「仔细地讲」

「……实际上，典礼之后和国王谈话时直接说过了。听了我，我和威尔海姆的事情，然后」

「内战也已经结束了。『剑圣』为王国已经尽了自己的义务。——分开相爱的男女实在不好什么的，接下来的事情怎么办之类的。」

中途接过话头，吉奥斯一脸糊弄的表情点著头。只有国王身后闭著眼睛的麦库洛托夫一人完全没有惊讶的样子。

于是威尔海姆注意到了。

——恐怕，从一开始，麦库洛托夫就是知道这件事情的没错了。

也就是说，一开始趁他一个人的时候来找他引出问题，只是为了看刚刚的热闹。

明白了事情的缘由，心头涌上一种干了蠢事的浓浓徒劳感。

「……哈」

「啊，威尔……吓！」

脱力的威尔海姆直接倒向地上，被特蕾西亚伸手接住。但是威尔海姆从那双手中用力地挣脱出来，反过来抱住她两人依偎在一起。

被威尔海姆抱著，特蕾西亚又翻起了白眼

「呜，又是汗臭味……威尔海姆真是的，老是带著这个味道」

「你的话则是带著花朵香甜的气味。典礼的时候就这么想了。」

「那是因为是你在花园遇到的我嘛」

可爱地笑著，特蕾西亚俯向威尔海姆怀抱深处。就这样抱著也不错但是

「啊啊，互相相爱真好呢，但是不要忘了我们还在呢，阿斯特雷亚」

「诶、啊、哇、是！您刚刚说了什么，陛下！」

想起还在大庭广众之下，特蕾西亚飞跳著站了起来。对慌乱著整理服装的特蕾西亚，吉奥斯露出了一丝苦笑挥了挥手。

「寡人，将你从『剑圣』的职位隐退下来的条件，还记得吗？」

「啊、呜……」

对国王的确认，特蕾西亚仿佛被戳到了痛处一样哀鸣道。

对先前也见过的她的反应，威尔海姆也直起了腰站了起来。

「怎么了？是很困难的事情说不出口吗？」

「诶多、那个，嗯…….」

「你要是觉得难的话我就来代你做。这点程度，放马过来就是了」

「真的吗？啊，稍微等一下。但是一个人实在太难了，不是两个人的话……」

重复著让人不得要领的发言，特蕾西亚红著脸支支吾吾的。周围的家伙们看见『剑圣』新奇的表情惊讶极了。

说到底，熟知身为剑士的她的他们会这样也是无可奈何的事情。只是，对于这令人怜爱的样子被别人看见，威尔海姆多少感到恼火。

于是，握住闭口不言的肩膀说

「好好说清楚！是什么？」

「——！陛、陛下说，如果我好好地做你的妻子的话，就让我辞去『剑圣』！」

「——」

满脸通红，眼眶含泪的特蕾西亚对紧贴著的威尔海姆说。

内容打击在鼓膜上，传入耳内，等到理解了之后——真是无话可说。

看上去特蕾西亚也一样，眼神中透漏出不安，一直盯著威尔海姆。

「这是，什么意思……」

「也就是说，陛下是这样想的——作为好的妻子，孩子的母亲的女性，一直握著不想握的剑满是牵挂什么的事情是办不到的。」

流畅地，坐在观众席的麦库洛托夫把隐退的条件好好解释了。

「好几次，打算在房间里和你说的但是……找不到合适的机会」

「看来确实是这样了，就算如此，还真是没有想到」

以婚姻作为条件，将特蕾西亚从军队除名什么的真是没想到。

原来如此，虽然早就听说露格尼卡王族确实爱做老好人，现在看来自己还是太天真了。

「——」

看著观众席上得意洋洋的国王，又转头看向身边的特蕾西亚。眼眶湿润的特蕾西亚，正颤抖著等著他的回复。

看上去还在害怕著自己被拒绝的样子。——真是傻

「——威尔海姆·阿斯特雷亚」

「……额？」

「特雷亚斯家已经不存在了。要改姓的话，就该这样改不是吗？」

对哑然的特蕾西亚，威尔海姆露出了浅浅的，晚霞一般的微笑。

对这微笑和话语，特蕾西亚的眼睛睁得更大了。

「接受了吗……?」

「不如说拒绝了的话才让人惊讶吧。你这家伙真是的……」

「因为！结婚什么的，也太突然了……」

「你是我唯一想娶的女人。只是早晚的事情而已」

对这玩笑般的话语，特蕾西亚张大了嘴，然后，大滴大滴的眼泪就开始沿著白暂的脸颊滑落。

对这反应叹了口气，威尔海姆又抱住了特蕾西亚。

「我能……做你的新娘花嫁吗？」

「本来你就是我的花女，只是稍微改变了一点而已。不用感到不安啊，笨蛋」

「这样啊……虽然有点牵强附会也不错呢」

埋头在威尔海姆怀中的特蕾西亚，红著脸笑著说。

因为看不见这样的（特蕾西亚的）表情，出乎意料的，威尔海姆一点也不觉得牵强附会。因为第一次见面时就被吸引住了所以，从一开始就没考虑过娶别人做新娘。

「——威尔海姆·范·阿斯特雷亚」

「什么？」

「要改姓的话，应该是威尔海姆·范·阿斯特雷亚才对哦。范这个姓是特意为了表彰剑圣家族的家系而赐予的姓氏……你的话，则是从我这里夺走剑的人」

——威尔海姆·范·阿斯特雷亚。

对特蕾西亚的话，威尔海姆小小哼了一声。

「也不坏」

——和你拥有一样的姓氏这件事。

把这样的一句追加埋在心底，『剑鬼』迎娶了不再是『剑圣』的女人，仅仅是爱惜地抱著她，温柔地抚摸著她绚丽的红发。

『完』