#+title: Re:从零开始的异世界生活 短篇集 2
#+setupfile: ./setup.setup
* 短篇集 2

** 『对E•M•T献上情歌』

台版 转自 轻之国度

图源：真妹控

录入：kid

1

──事情是发生在宅邸杂务告一段落的午后时光。

「──昴，可以拜托你帮我一件事吗？」

「嗯啊？」

突然传来的银铃般声音，让昴咬著烤甜点并回过头，有个一身白色装扮的美丽少女正从餐厅入口呼唤著昴。

拥有彷佛月光般闪亮的长长银发、如宝石般的紫蓝色眼眸以及超越人类领域的美貌──这位半妖精的名字就叫做爱蜜莉雅。

「啊，该不会是还在做事吧？我打扰到你了吗？」

「没啊，我正在休息。我觉得应该没有国家会把边吃点心边做事当成正式礼仪吧。」

昴将吃到一半的甜点吞进肚里，朝著一脸担心的少女投以笑容。爱蜜莉雅对这个回答松了一口气，她怀中抱著的珍奇物品让昴挑起眉头。

那是仍记忆犹新的异世界其中一种乐器……

「是流丽丽吧，我还以为已经放在宅邸仓库生灰尘了呢。」

另一名同样在房间休息的女仆装少女，则是对昴的反应如此补充说明。

这位少女留著一头短蓝发，并且身著颇为裸露的改造女仆装……她是昴的同僚，同时也是担任宅邸女仆长的超级女仆雷姆。

雷姆不只是家事方面全能，还一手包办宅第的所有事务。昴刚才吃的烤甜点也是雷姆亲手制作，目前她正与昴两人在工作休息时间享受著茶点。

「既然不是莉莉安娜忘记带走，那个布满灰尘的流丽丽是怎么回事？」

「就算是莉莉安娜也不会忘记重要的乐器吧……应该吧。」

「从那种犹豫的回答态度，就能看出对莉莉安娜的信赖程度了。」

「真是的，别这样消遣我啦。──就是上次莉莉安娜的事，让罗兹瓦尔心血来潮拿出来整修，还说念书想转换心情时可以请昴弹个一曲。」

「居然特别指名我，没想到罗兹亲还满会察言观色的嘛。」

昴战战兢兢地接下递出的流丽丽，然后轻轻地弹了一下琴弦。轻快音调随即传遍室内，看来整修做得相当万全。

流丽丽是木制弦乐器，形状接近原本世界的吉他。虽然尺寸较小，但能弹奏的音阶只要掌握诀窍并没有多大差异。

「昴，你也会演奏流丽丽吗？」

见到昴驾轻就熟地确认音色，让雷姆瞪大双眼。

「对啊，我会弹。基本上和家里的木吉他没什么差别，而且还受过莉莉安娜的小特训，如果是我老家的地方民谣大概都没问题。」

「木吉他？」

「就是原声吉他的简称。哎呀，就当成我老家那边才有的民族乐器吧。」

如此回应歪著头表示不解的雷姆后，昴回想起曾经对他做过猛烈特训的那名褐色肌肤少女。

莉莉安娜──是前阵子才在罗兹瓦尔宅邸作客的吟游诗人少女。不愧是以唱歌卖艺维生，她的歌喉与演奏技术可说是令人惊叹。不只是宅邸的女性成员，甚至连昴都暗中成为了她的忠实听众。

不过一反音乐方面的优越天赋，这位少女在人性面上可说是相当微妙。

总之，与莉莉安娜相关的事件也告了一个段落，宅邸又恢复了日常的生活。

过了几天后，目前爱蜜莉雅心中似乎尚未遗忘对音乐的憧憬与好奇心。从她会在休息时间要求昴献唱一曲，就能发现她已经完全陶醉其中。

「那么，昴也会演奏莉莉安娜小姐曾经唱过的歌曲吗？」

「演奏同样曲目很容易被拿来比较，所以我想尽量避免。还有就算会弹奏，要弹唱的难度可是高多了，主要是我的歌声问题。」

「不过昴还是很厉害，在宅邸工作完全无法派上用场的技术，真的是让雷姆难以想像！」

「嘿嘿，也没有那么厉害啦……咦？怎么感觉有点怪怪的？这应该不是称赞我吧？」

「──？」

面对毫无自觉的讽刺，双手合十对昴赞誉有加的雷姆露出不解神情。虽然模样看来很可爱，但反而更像是真实心声而深深刺进昴的心中。

不过，有两名少女正满怀期待，昴也想对她们展现出帅气一面。

「不然就『剑鬼恋歌』……这实在有点难，还是选七十年代的民歌组曲吧。」

「欸～～」

「没什么好欸的，这也是名曲。」

昴对听来不满的声音露出苦笑，便用手指开始拨著流丽丽弹出节奏。爱蜜莉雅与雷姆皆一同坐在沙发上，配合演奏开始轻轻地用手打著节拍。

「虽然音调比木吉他还阳光，不过这方面就请用想像力自行补充了。」

昴一边做著事前提醒，一边照著记忆中的乐谱拨动流丽丽的弦。

在消磨拒绝上学的无为时间中，菜月•昴厌恶自己停滞不前而学习了许多技术──练习吉他也是其中一环。

那段无益时光竟然能辗转让眼前两位美少女如此高兴，人生可真是难以捉摸。

「──」

七十年代的民歌反映了当时的时势与流行，多数是曲风稍显悲伤的歌曲。即使没有歌词，虚幻忧郁的气氛仍然会展现于曲调上。在仔细倾听歌曲的两名少女眼眸与表情中，能够明显感觉到浮现出忧郁与寂寞的神色。

此种反应让演奏的昴感到浑身不对劲，见到她们的表情让胸口有股苦闷感。于是……

「秘技！牙齿弹吉他……痛痛痛痛痛痛！」

「咦……昴！？糟糕！你怎么做出这么笨的事情呢！」

「昴！？怎么做出这种蠢事呢！」

「那也不用两个人说出一样的话吧……好痛！痛痛痛！」

昴想靠著表演在沉重曲调中炒热气氛，却被重新锁紧的坚硬琴弦弹到牙齿与齿龈。

说到用牙齿弹奏吉他的神技，这是只有一流吉他手才会的高超技巧，身为三流吉他手的昴当然不可能用得出来，最后只落得血流如注的悲惨下场。

「好好，请昴冷静下来，痛痛快点飞走～～」

「痛痛痛痛……不痛了！治好了！唉……刚才真是痛死我了，谢啦。」

雷姆将手抵在痛苦挣扎的昴面前，使出散发淡淡光芒的治疗魔法。

随著疼痛远去的感觉，被琴弦刮伤的伤口逐渐愈合，让昴表达感谢之意。昴的模样让爱蜜莉雅双手叉腰露出气冲冲的神情。

「害我以为突然发生什么事了，让我吓了好大一跳。真是的，别做出这种怪事让我担心嘛。」

「抱歉抱歉。哎呀，我自己弹下去之后才发现曲子选得不太好。这不是七十年代民歌的问题，是我选了没有符合气氛的曲子。」

昴认为既然要演奏，当然得选能让两位观众开心享受的曲子，民歌更应该用来拉近与心仪对象之间的距离。

「所以等有下次机会再弹刚才那首歌吧。要好好等著喔，爱蜜莉雅酱。」

「──？我不太清楚要等什么，不过好吧……这样就演奏完了吗？这些就是昴会弹的所有曲子吗？」

她那希望能再多演奏几首歌的言外之意，让昴顿时松了一口气。

先不论选曲，昴的演奏似乎有达到爱蜜莉雅期待中的水准。从雷姆没有插话这点，看来她也与爱蜜莉雅怀著同样意见。

虽然昴就算不受期待也会自行炒热气氛，但既然如此备受期待，昴也想尽可能地回应她们的期待。

「可是我只有练习七十年代的民歌而已啊！为什么我当时没有多练点HIP-HOP的歌呢……」

「昴，你正在烦恼吗？那么果然还是从莉莉安娜小姐的歌中挑一首吧。」

见到昴诅咒著过去的自己，雷姆举起手说出自己所认为的好提议。从这个难得的提案能够隐约见到雷姆的可爱企图，可说是非常惹人会心一笑。

出乎意料地，最为注意莉莉安娜歌曲的人就是雷姆。毕竟她对各地流传的诗曲与传承歌曲造诣颇深，所以她应该是假借提议的名义想让昴唱出口。

对昴来说，莉莉安娜的每首歌都是引人入胜。然而──

「我还没有厉害到能用听的就能把别人的歌抄下来，也没有能与莉莉安娜相提并论的实力。除了民歌以外的曲子……如果是『踩到猫儿』之类也没问题喔。」

「昴，那得好好道歉才行……」

「别露出那么难过的表情啦！这样我会很难过耶！是你误会了啦！不是我故意去踩猫啦！是曲名就叫这样！我之后会再去跟踩到的人说啦！」

这首传统的钢琴演奏曲，差点在说出曲名的时候就被打入冷宫了。

面对低头赔罪的昴，原先露出责怪眼神的爱蜜莉雅叹了一口气。接著她拍了一下手，悄悄以恶作剧般的眼神缓颊一笑。

「那么，你只要弹莉莉安娜的歌曲就让你一笔勾销。就算弹得差也不会笑你的，所以别紧张弹弹看吧。好吗？」

「昴，爱蜜莉雅大人说的没错。就算弹得多烂多难听或失败，雷姆都不会笑的。所以请放心尽管失败吧。不会有事的，雷姆会负责安慰哭成一团的昴。」

「不需要担心到这种程度吧！我不会哭啦！！」

居然被担心到只是稍微失误就会哭出来，昴只能毫无退路地垂下肩膀。

看来已经无法避免得把听过的旋律背出来，莉莉安娜本人曾经教过昴几首演奏过的歌曲，应该还不至于到完全无法弹奏的地步。

即使如此，昴的演奏技术只是拙劣的独门自学。那是他拿著父亲曾经用过的吉他并盯著乐谱，忍受著父亲在纸门另一侧偷偷窃笑的目光所练出的成果。

「要是真的很烂别笑我喔，我也不会哭的。」

如此做完事先声明后，昴重新举起流丽丽准备演奏。然后微微歪著头，以稍微装模作样的姿势朝爱蜜莉雅眨了眨眼。

「顺便问一下……有任何想点的歌吗？这位小姐？」

「啊……既然这样我觉得那首歌很不错！就是那个──」

见到昴接受要求演奏，爱蜜莉雅开心地阖起双手。接著她闭起眼睛，彷佛回想著歌曲般微微发出声音。

「啦、啦、啦啦啦～～」

爱蜜莉雅短短地将吐息乘著声音，从唇瓣中将犹如银铃的音色纺织成为歌声。

那以美妙声调纺织而成的魅惑曲调，让昴与雷姆皆不禁吞了一口凉气。

原先爱蜜莉雅的声音，便有牢牢吸引听者心灵并撼动魂魄的魔力。虽然每当说话时就会心跳加速是昴个人的因素，但除了昴以外的人应该也会感受到这股魔力。

声音透过鼓膜传进体内的血液，难以按捺的感情让灵魂不停跃动。在此种歌声面前，甚至令人有种连留在现场都是不识趣的感觉。

「────」

照理说她只是为了传达曲调而唱，但爱蜜莉雅兴致一来便停不下歌声。

昴与雷姆没有任何方式能够阻止她，只是默默地持续听著她以美妙音色演奏出名为歌声的魔法直到结束。

最后歌曲终于结束，唱完的爱蜜莉雅深深吐出一口气。

「……啊。」

这时，爱蜜莉雅才首度发现自己忘我地沉醉于歌声中。那白皙脸蛋害臊地染上红润，爱蜜莉雅慌张地看著昴等人。

「对、对不起……总觉得唱歌的时候唱得很舒服就……」

「……用看的就知道了，所以没事的。原来你很喜欢唱歌嘛。」

「我不知道，因为身边不常接触歌曲……不过……嗯，也许我很喜欢唱歌喔。」

爱蜜莉雅将手抵在嘴边，似乎有些害臊地如此点了点头。

听到她那宛如叹息般说出的「也许我很喜欢唱歌」，平时的昴肯定会想办法再问一次，但这时昴并没有如此思考。

在昴身旁悄悄拉著袖子的雷姆也不能算是毫无关系。

「昴……」

「我知道。」

雷姆那淡蓝色的双眸似乎欲言又止，昴看出其中带有的感情也跟著点了点头。

被叫出名字让他发出短短同意声，只靠这点话语便让两人顺利沟通……不，或许该说听到歌声的人应该都会有此种共通感受。

必须展开行动，这是昴在这个宅邸中学到最强大的武器。

被命运数度玩弄后，昴理解到选择与行动是改变这个不讲理世界的唯一方法……因此昴再度展开挑战。

对于目前仍然面露红润的爱蜜莉雅，昴先一度闭起眼睛。

「我说爱蜜莉雅酱……我不知道该怎么说才好。」

「咦？喔……」

爱蜜莉雅将手抵在自己的银发上，对慎选话语的昴歪著头表示不解。

她那望著昴的紫蓝色眼眸中，怀著与雷姆截然不同的信赖。此种感情让昴顿时揪紧心房，但他仍然将此种感伤按捺压回心中。

「爱蜜莉雅酱，你……」

「……刚才那像是小鸟临死惨叫声的声音是怎么回事？毛，我休息的时候你在搞什么把戏？」

话才说到一半便有人推开门，此种高傲语调将昴所作好的心理准备完全粉碎。

有位拥有粉红头发与淡红眼眸的少女走进房间──除了头发与眼眸颜色以及胸部尺寸以外，皆与雷姆如出一辙，她就是双胞胎的姊姊拉姆。

拉姆以看似不悦的眼神环视室内，依序看向呆站在原地的三人，然后闭起眼睛整整沉思五秒后──

「可以取消我刚才说过的话吗？难得拉姆会这么想呢。」

「大姊！虽然你一瞬间掌握状况是很厉害啦！不过气氛已经完全搞砸了啦！」

面对拉姆突然闯进现场并一针见血的发言，昴的喝斥声顿时响遍整个房间。

2

──拥有如天使般美声的爱蜜莉雅，竟然是个偏离常轨的超级音痴。

虽然整件事说起来单纯，但光是如此便让昴受到难以抹灭的震撼，甚至开始思考近年来是否碰过如此悲惨的情况。

并非只有昴对美声与音痴共存的事感到惊讶，雷姆也对亲眼面对的事实难掩落寞与悲伤。

对雷姆而言，爱蜜莉雅接近毁灭性的唱腔也是充满震撼。

没人能料想到爱蜜莉雅那宛如铃铛般的美妙声音，竟然能够演变成如此五音不全的结果。

「神啊，你对这孩子到底做了什么事？到底要多么残酷才肯罢休……！」

「拜托别说得那么难听啦！真是的！真的好丢脸喔！」

连那比一般人还长的耳朵都变得羞红不已，爱蜜莉雅将脸埋进沙发。

听到爱蜜莉雅五音不全的歌声，拉姆特地赶过来发出抱怨。一开始爱蜜莉雅还对拉姆的发言抱持疑问，但经过昴勉强找藉口并反覆解释，目前她也已经确实地认清事实。

正确掌握现实后，爱蜜莉雅正带著赌气表情蹲坐在沙发上。

「应、应该说是昴你们说得太夸张了……虽然我到目前为止几乎没有唱歌的机会，也没有人教过我唱歌的方法……不过差到这种程度还是有点奇怪，一定是大家想捉弄我开的玩笑对吧？我不会这么容易就被骗的。」

爱蜜莉雅抱著双腿饶舌地如此说著。她努力否定著难以相信的事实，态度就像是个孩童般不甘愿地抗拒著接受现实。

与爱蜜莉雅四目相对后，昴以诚挚口吻试图说服她。

「我能理解会怀疑并且不敢相信的心情。不过实际上不是这样的，我到目前为止有对你说过谎……唉，说实话好像说过满多次谎的，而且看到爱蜜莉雅酱被捉弄得面红耳赤模样，也让我常常想继续捉弄下去。」

「是这样吗！？我都不知道！我是什么时候被这样捉弄过？什么时候？」

「现在不是说这些的时候啦！别逃避问题！」

「唉唷……总觉得没办法释怀……」

昴一不小心说溜嘴赶紧用强硬语气掩饰，爱蜜莉雅似乎仍然相当不满，但昴彷佛排解此种不满般张开双手说道：

「这次是真的，我发誓没有半点假话。」

「昴……」

昴以诚挚语调与认真眼神，尽可能地将真心想表达的意思传达给她。

「──你是天神恶作剧下的牺牲者。」

「有夸张到这种程度吗！？」

「毕竟谁会相信竟然糟糕成这个样子！为什么爱蜜莉雅酱是个音痴呢！？明明那么可爱又有那么美的声音，唱歌唱成这样没有人会获得幸福的！要怪就怪天神吧！不然就要怪你爸妈放你变成这个样子！」

「欸欸欸欸……」

对于昴握紧拳头如此强调的模样，爱蜜莉雅的表情显得相当落寞。

或许是因为她没有自觉是个音痴，因此即使她对这件事颇为激动，但对她而言似乎仍然是事不关己的事。

没有理解到自己是个五音不全的音痴……据说这是矫正音感特别困难的「感受性音痴」，这与喉咙相关的「运动性音痴」不同，本人没有自觉可说极为难以矫正。

也就是说，要打倒这个难敌，除了本人之外还得要有家人帮忙。

「帕克！COME HERE！」

昴弹响指头，叫出爱蜜莉雅的家人作为这个问题的负责人。

虽然昴没有召唤精灵帕克的权力，不过身为契约者的爱蜜莉雅被昴的气势压迫下，便朝著自己胸前发光的绿色结晶石低声呼唤。接著……

「有求必应喵喵喵～～」

辉石散发出淡淡光粒，逐渐形成一只小猫形状的精灵。

随著此种傻呼呼声音现出身影的精灵────帕克落到爱蜜莉雅的左肩上，抱著长长的尾巴开始整理毛皮。

「怎么了？找我有什么事？我今天预定一整天都要休假呢。」

「你是在说什么很像繁忙业界人士的话啦？而且你不是都在石头里面听见刚才的话了吗？」

「我不是说今天休假吗？所以睡得很熟喔。」

「真的很像上班族老爸会过的假日耶……」

实际上班时间朝九晚五，这只可爱小猫已经无法停下成为上班族的生活方式了。先不论这只小猫怎么度过假日，昴先搭配些许肢体动作说明截至目前为止的来龙去脉。

听完昴的话后，帕克点了点头并看著爱蜜莉雅的侧脸。

「原来如此……莉雅有像昴说的那么音痴吗？」

「我是不想变成这个样子……我觉得是昴说得太夸张了，我还是能好好唱歌的。我没有随便胡闹喔。」

「如果是胡闹……是胡闹就好了……！」

面对爱蜜莉雅赌气的模样，昴单膝跪著并咬著嘴唇不断敲著地面。

来回看著两人的脸后，帕克便摸了摸自己的粉红色鼻子。

「总之得听过一次才能知道。莉雅，麻烦你了。」

「……真是的，不准笑出来喔。」

「我不会做这种事的，就算全世界的人都嘲笑你，只有我绝对不会笑你的。」

「耍帅到有点过头了吧。」

面对帕克颇为热血的回答，爱蜜莉雅吐出一口气并闭起眼睛。接著，她哼著节奏寻找开始唱歌的时机。

但在哼曲子时已经乱了节奏，不过她仍然毫不在意地开始唱歌。

经历过刚才那首歌，这次的歌声感觉比较随兴且放得开。爱蜜莉雅自己似乎也有感觉到，她唱完歌时的神情也显得相当舒畅。

「怎么样？」

爱蜜莉雅露出似乎唱得相当舒服的表情，并且颇有自信地对帕克如此问道。

这段话让帕克说著「嗯，说得也是」并用手洗著脸。

「我到目前为止对养育莉雅的方式很有自信，不只是把莉雅养育成全世界最可爱的女孩子，而且打从心底认为莉雅是个既聪明又乖巧的孩子。」

「嗯……是这样吗？感觉会让人有点害羞呢……」

突然被捧上天让爱蜜莉雅难掩害臊地微微一笑，不过帕克在这段称赞的话语最后补上「可是……」这一句。

「我从来没有像今天这么后悔自己没注意到这件事……」

「──咦？」

「对不起，莉雅……对于全世界最可爱的你，我没有成为全世界最优秀的父亲，只有这点我觉得真的很可惜。」

说完这句话后，帕克突然失去力气从爱蜜莉雅肩上滚落，昴赶紧伸出手接住这只从细肩上掉落的精灵。

在昴的掌心上，帕克气若游丝地转头仰望著昴。

「昴，对不起……都是我能力不足……」

「没关系！别再说了！帕克……这不是任何人的错！毕竟……毕竟连你都这么后悔了！那么我们的心情都是一样的！不是吗？」

「呵呵……光是能听到这句话就满足了──我突然觉得好想睡觉喔……」

光芒从那圆润的黑色眼眸中消失，帕克的身体失去力量。精灵的身体轮廓越来越模糊，并且化为光粒开始四散，昴则是拚命挤出声音呼喊想阻止他消失。

「别、别走啊！帕克！帕克～～！」

「谢谢你……陪我到这个时候……」

精灵在痛哭失声的昴掌中逐渐消失，而有个人正用斜眼瞥著他与精灵所发生的悲剧……

「我不想理你们了啦！昴和帕克都是笨蛋！笨蛋笨蛋笨蛋！」

爱蜜莉雅被捉弄到闹著别扭，从餐厅飞也似地冲了出去。

「──玩过头了。」

昴与帕克面面相觑并深深反省刚才演的那场蹩脚戏，然后赶紧冲出门追赶爱蜜莉雅。

3

「音痴的原因大致上能分成三种。就是『无法抓到音准』、『发不出声音』和『抓不到节奏』。只要一个个解决这些问题，理论上不论是哪种音痴都能完全根治。也就是说，爱蜜莉雅酱的音痴是可以治疗的缺陷！」

「你、你说什么喵～～！」

面对举起拳头如此强调的昴，帕克也发出老梗的惊讶回应声。

刚才昴提倡的理论其实是从电视学来的内容，虽然不知道有几分根据，但应该至少比没头没脑地随便治疗还好得多。

音准、喉咙与节奏──只要这些是音痴的主要原因，就能自然地缩小范围找到解决方法。

「首先，把爱蜜莉雅酱的问题简单易懂地整理一遍吧。从刚才听来的感想，爱蜜莉雅酱的音痴原因是出在音准和节奏上，毕竟不论音准至少能唱出声音，还有就是长相很可爱。」

「昴，话题歪掉了。」

「糟糕，不对啦。虽然长相确实是很可爱，不过声音的确有发出来。所以必须克服的问题就是音准和节奏。来！跟著我念一遍！」

「音准与节奏！」

帕克跟著昴的声音，两人对解决音痴问题的态度可说是相当积极。

但在两人的身旁……

「唔……」

爱蜜莉雅仍然坐在地面抱著双腿闹别扭，完全没有积极参加两人对话的意思。

虽然追上逃走的爱蜜莉雅，不过她闹别扭的程度可说是非比寻常。即使如此她的长长耳朵还是不停摆动，她那竖起耳朵听著话语的模样可说是既老实又可爱。

「既然能够享受莉莉安娜的歌，就表示爱蜜莉雅酱的耳朵能分辨出歌曲好坏。听歌没问题自己却唱不好的状况，说不定是自己会下意识地在脑中改变唱歌的方式，我们先来解决这个问题吧。」

「说起来好像很简单。要怎么样才能做到呢？」

「一般而言像是听正确曲调几百次，或是反覆哼歌直到掌握正确音准……其实对音痴有自觉是满简单的事，首先就……」

昴回应著帕克的疑问，并且准备开始爱蜜莉雅音痴矫正计划的第一阶段。

不过，就在昴准备拿出秘密武器的瞬间……

「──刚才我只是没说而已，你们还真是想做什么就做什么呢。」

突然有道听来很不高兴的声音插了进来，让昴无可奈何地摇了摇头。接著猛然将头转向将话题打断的那个人，朝著对方那冷冷表情刻意叹了一口气。

「真是的……难得大家都这么积极，别在那边只会泼冷水啦。你别只会看书，也要学会看气氛。」

「比起别人说出这种话，由你说出口感觉更让人火大呢。应该说你是真的听不懂意思吗？你为什么会要在贝蒂的禁书库做这些事？」

发出重重声响将书阖上后，房间深处坐在梯凳上的少女便不悦地啧了一声。

那位少女身穿有许多轻飘飘滚边的礼服并绑著一头长卷发，而且拥有一副宛如洋娃娃般的工整容貌。她是这间宅邸的一员，同时也是书库的图书管理员碧翠丝。

正如方才所见，她与昴可说是水火不容──虽然昴很想与她和好，但由于实在是个越捉弄越有趣的少女，因此昴总是烦恼著自己面对她总是会语带挑衅的行为。

「这也不能怪我吧？这间宅邸又没有防音设备齐全的音乐室，要是在其他房间唱歌让爱蜜莉雅酱的声音传出去怎么办？如果爱蜜莉雅酱是个音痴的事传开，就别提什么王选了。」

「我的歌有糟到这种程度吗！？」

被说成甚至会影响王选，就连爱蜜莉雅都无法保持毫无反应。

这番话语让碧翠丝将冷淡目光转向爱蜜莉雅。

「不管她将来会变成什么样子，都与贝蒂没有任何关系，而且这不构成在禁书库吵闹的理由吧。」

「碧翠子，是你应该很清楚吧？在普通房间声音会传出去，可是在这个禁书库就不需要担心。毕竟这是个与世隔绝的空间，所以不管上多少课都不会给人添麻烦啦！」

「可是这会给贝蒂添很多麻烦啊！」

碧翠丝跳下梯凳并抓著礼服裙襬，面红耳赤地如此怒骂。

碧翠丝怒气冲冲的反驳可说是相当合理，但要替爱蜜莉雅上课必须用到禁书库也是不争的事实，于是昴决定使用对碧翠丝的最后王牌。

「贝蒂……我们真的有这么碍事吗？你这么希望我们离开吗……？」

帕克带著圆润眼眸抱著尾巴，以无辜眼神朝著碧翠丝如此说道。

明明没有事前约好，但此种故意装成小猫的诉愿可说是相当完美的搭配。碧翠丝突然失去先前的气势，并且露出怯懦的表情。

「哥、哥哥没有半点错！可是禁书库……」

「嗯，我也知道贝蒂很重视这个房间。不过这件事也需要贝蒂的力量，所以拜托你帮帮我吧。」

「哥哥……」

在敬慕的兄长帕克的请求下，碧翠丝的决心大大摇摆不定。毕竟她原本就是个只会说说却不太会拒绝要求的少女，因此昴可说是胜券在握。

「看来赢了。」

「这、这也是没办法的事……好吧，既然是哥哥的要求就没办法拒绝了。」

碧翠丝没有发现昴面露邪恶表情的喃喃自语，以一如往常的样板反应并顺势接受要求，甚至让昴很担心她以后是否会被坏男人拐骗。

不过这样条件就准备齐全了。昴与帕克互相点了点头，帕克则是以身体冲向昴高举的手掌，与昴来了个超帅气的击掌。

顺利得到房间主人的同意后，昴决定开始爱蜜莉雅的课程。

「这或许是一条险峻难熬的道路，不过我们还是不畏困难地努力走下去吧！」

「喔～～！」

「我从头到尾都没有说过自己想改善音痴……不对，虽然说不定是真的有点不会唱歌，可是我从来没拜托过想改善这件事吧……」

不过此种燃起的干劲似乎完全忽视当事人的意见，就这样怀著各自的心情开始了课程。

4

「那么，接下来要正式开始上课了……爱蜜莉雅酱，你是要闹别扭闹到什么时候啦？这可是满重要的事喔。」

「因为只是唱歌唱得稍微小差而已，这样实在做得太过火了，我最讨厌昴和帕克了。」

「最近好久没听到小差这个词了，而且你为什么要这么顽固？」

「我才不知道呢。」

由于先前调侃过她，因此身为当事人的爱蜜莉雅似乎不太认真。

不只是音痴，这类问题必须要有当事人想改善的自觉，因此首先得要让爱蜜莉雅自己认真地面对这个问题。

「明明平常总是这么乖巧老实，为什么只对唱歌这件事这么顽固？」

「因为很丢脸嘛。昴和莉莉安娜唱歌都那么厉害，只有我不知道怎么唱又是音痴……我不想相信有这种事。」

「哎呀讨厌，这种抵抗方式真是太可爱啰。不过这样就头痛了……」

她那别过头的脸相当红润，爱蜜莉雅抵抗的气势也越来越弱，但见到这似乎还不足以成为最后的临门一脚，于是昴扭著头让脖子发出喀喀声。

「──要对音痴有自觉，最好的方法就是让你客观地自己听听歌声。原本只要能录音就能一次解决了，只可惜这里没有那么方便的工具。」

因此昴只好放弃倚靠文明利器，准备尝试最原始的方法。

「那是……水桶？」

见到昴手中所拿的道具，让爱蜜莉雅不禁瞪大双眼，映入眼帘的物品毫无疑问地就是金属制水桶。

「这就是这次的特别来宾水桶先生，这位特别讲师会告诉爱蜜莉雅酱自己有多音痴。这个水桶我已经洗干净了，你可以放心没有卫生问题上的疑虑。」

「要怎么用那个水桶？我可以进去看看吗？」

「现在不需要你强调想躲进狭窄处的猫咪特色啦，使用方法很简单──只要把这个盖在爱蜜莉雅酱头上，再请她唱歌就好。」

「……咦？」

「噗噗。」

昴斩钉截铁的发言让爱蜜莉雅相当惊讶，碧翠丝也忍不住噗哧一笑。

「呃……不好意思，我刚刚耳朵好像怪怪的。那个水桶要怎么使用？」

「要戴在头上唱歌，要让你成为一个水桶女主角。」

「昴！你这个笨蛋！亏我还这么认真听你说话！」

面对昴带著笑容递出水桶，爱蜜莉雅气冲冲地打算再度逃走，不过昴赶紧抓著爱蜜莉雅的手。

「先、先等一下！不是这样啦！我这次不是开玩笑的！只要戴上水桶唱歌，声音在里面回响就能让自己听到！我没有说谎喔！」

「这应该是平常爱说谎的报应吧，就像《荒地的合辛》里放水牛的小孩呢。」

「听起来怎么很像是放羊的小孩啊！真是个碍事的萝莉耶！你稍微闭嘴好吗！」

让从旁插嘴的碧翠丝闭上嘴巴后，昴赶紧向拋出怀疑目光的爱蜜莉雅如此解释。

被爱蜜莉雅如此严厉目光瞪著，这大概是自从被召唤首日以来，用她曾经使用的魔女假名称呼她后就没有出现过这种表情了。

面对区区水桶带来的惨剧，让昴尽可能地拚命表达诚意。

「只要听过自己的歌声，就能知道自己唱歌的程度！我没有说谎！你当成被骗戴起来唱唱看就知道了！」

「会说当成被骗就是想骗我吧！我不会再被骗了！」

「到底是谁害她变得那么多疑……」

「昨天你也说当成被骗，骗我试吃做坏的美乃滋！我想起昨天很生气的样子又更生气了！」

「可恶！原来是我！昨天的我真是个白痴！可是今天的我不一样！这都是为了你好！」

虽然感觉是要骗她去做坏事，但在昴凭著一股气势的强力劝说下，个性善良的爱蜜莉雅最后还是拗不过他的要求。

爱蜜莉雅看著交到手上的水桶，然后战战兢兢地举高到头上……

「……不会笑我吧？」

「不会不会，绝对不会笑的。」

「绝对绝对吗？」

「就算每个人都笑你，我也绝对不会笑你的。」

「那是在这种状况也能说的话吗？」

帕克在肩头上如此询问，昴则是一脸认真地装成没听见。一切都是为了让爱蜜莉雅戴上水桶，目前不论用多么帅气的话语都不足为惜。

或许是从这番强而有力的话语得到勇气，爱蜜莉雅带著下定决心的神情将水桶戴了起来。毫无装饰的水桶完全遮住爱蜜莉雅的脸──这也是水桶系女主角诞生的瞬间。

「该怎么说呢？明明已经知道会有这种事，不过看到爱蜜莉雅酱的模样还是有股心痛感。」

「莉雅，别担心。就算戴上水桶你还是全世界最可爱的。」

背负罪恶感的昴如此说著，帕克则是不论爱蜜莉雅任何模样都不忘表达亲情。

虽然昴对此种深深亲情有种被打败的感觉，不过似乎能感觉到被水桶遮著脸的爱蜜莉雅对这番称赞很高兴。

「噗噗。」

就连拿起书遮著脸的碧翠丝，都能发现她正压低声音忍著笑。

在众目睽睽之下，爱蜜莉雅仍然乖巧地转头朝向昴问道：

「只要这样开始唱歌就好了吗？总觉得位置好小喔……哇，声音好清楚喔。」

「毕竟很少有机会能客观地听到自己的声音，就照这样好好听自己唱首歌吧，如果需要也可以帮你伴奏喔。」

昴提议用流丽丽支援，但爱蜜莉雅摇了摇戴著水桶的头。虽然模样看起来相当诡异，不过昴认为爱蜜莉雅在水桶中肯定是带著凛凛的神情。

「没关系，一开始我自己试试看就好。」

「这样啊，如果你会担心要说出来喔，我也会尽量帮忙的。」

面对爱蜜莉雅的音痴，昴不知道自己身为三流吉他手的演奏技术能帮上什么忙，而戴著水桶的爱蜜莉雅则是对昴的话语收起下颚。

接著……

「啦、啦、啦啦啦～～」

在没有昴的支援下，爱蜜莉雅哼著节奏开始唱歌。

由于隔著水桶听来有些模糊，然而歌声并没有出现戏剧性的变化。如果猜想的没错，爱蜜莉雅应该也会听到自己五音不全的歌声。

「好糟糕呢。」

「嗯，真糟。」

「真是糟糕透顶了。」

帕克不禁发出叹息，昴也感同身受地表示同意。连对莉莉安娜音乐表示出宽容态度的碧翠丝，都不悦地皱起眉头。

音乐天分是不可抗力的因素，因此这点理应不该责怪爱蜜莉雅。然而……

「──啊……」

「喔？」

在昴等人听著可怜的歌声时，歌声突然在这时停了下来。

歌声在这道宛如沙哑的声音下中断，在三人满腹狐疑的视线注目下，爱蜜莉雅将戴著的水桶拿了起来。

她那被压著的银发倾泄而出，爱蜜莉雅则是从水桶脸告别。

接著──

「……请让我独处一下。」

这位自觉到音痴的少女如此说著，然后带著寂寞神情迈步离开禁书库。

「……不对！怎么能离开啊！今天怎么都是在逃避啊！」

一回过神后，昴便连忙追向爱蜜莉雅。

5

「既然爱蜜莉雅酱重新审视到自己的缺点，那我们开始让她再度成为一个美妙女孩的课程吧！首先是克服抓不到音准的问题！OK！？」

「O、OK……」

虽然爱蜜莉雅一度逃走，但当她带著泫然欲泣的神情被带回来后，便对昴的指导变得颇为顺从，看来她似乎对身为音痴的自觉感到很难受。

即使还没有到毫无精神的程度，不过她似乎燃起了对课程的干劲。

「要克服音准不全的方法，就是反覆听一首歌熟记音程。像刚才那样盖著水桶自行矫正是最好的，要随时哼歌也不错。」

「可是说到正确音程，莉莉安娜已经不在这里了……」

「这个世界上不是只有莉莉安娜能唱出正确音准，碧翠子应该也没问题吧？喂～～你稍微唱唱看吧。」

「啥！？为什么贝蒂得唱歌不可啊？」

碧翠丝对这个突如其来的提议提出反驳，昴则是「喂喂」地耸了耸肩。

「既然这边都变成上课会场了，你来帮忙也会比较快解决问题，不解决我们就会一直赖在这里喔。」

「唔唔……就算是这样，贝蒂也不想听你使唤。」

「好好，意思就是你只会像个评论家抱怨东抱怨西，结果是个什么都做不到的淑女是吧？OK，我知道了，你可以继续回角落看书了。」

「你说谁只会出一张嘴！别开玩笑了！好啊！贝蒂就做给你看看！」

碧翠丝一如往常地对昴的挑衅出现相同反应。对于她如此容易操控，虽然昴有点担心她的将来，不过目前这么好处理可说是省了不少事。

而这位好操控的少女向前迈出步伐，气冲冲地用手指著爱蜜莉雅。

「就让贝蒂好好教你──什么叫做音乐的精髓！」

「你也说得太夸张了吧。」

「好、好的！老师，还要请您多多指点……我会努力学习的。」

「超老实！」

面对自视甚高的碧翠丝如此宣言，反而让怀有危机意识的爱蜜莉雅备感信赖，希望她们能这样团结下去一起挑战音痴矫正课程。

「要培养节奏感，建议练习一边唱歌一边让身体做出固定节奏的动作，只用手打拍子或踏脚都没关系，我们和音准一起来练习看看吧。」

「那么莉雅，我们一起用手打节拍吧。来，喵、二、喵、二……」

「喵、二、喵、二……」

当昴用手打著节拍如此说明后，帕克也跟著模仿开始指导爱蜜莉雅。看到它用肉球拍著手没有发出拍手声，爱蜜莉雅也连忙跟上。

「喵、二……呀！」

「拿去吧，接下来要跟著唱，贝蒂会好好调教你到学会唱歌。」

碧翠丝将水桶盖在用手打著节拍的爱蜜莉雅头上，并且冷酷地如此说著。

在禁书库能够见到戴著水桶的少女、朝少女投以锐利目光的幼女、以及开朗地在周围飞舞的小猫──从旁看来可说是相当异常的景象。

「看起来就像是恶梦一样缺乏现实感……要是做这种梦，我肯定会去看心理医生。」

总之不论如何，理论上这个课程应该能让爱蜜莉雅的音痴获得改善。两个人与一只猫似乎相当专心上著课，于是昴决定先去解决另一个问题。

「抱歉，我先去方便一下。」

「什么方便？贝蒂完全听不懂你在说什么。」

「就是去上厕所啦。别让我说出来，这样很丢脸耶。」

让碧翠丝一脸无奈后，昴便将爱蜜莉雅等人留在禁书库走了出去。虽然离开时似乎见到爱蜜莉雅的侧脸面露担忧，不过因为戴著水桶而无法清楚见到。

昴走出禁书库后，便随即启动「机遇门」。那是能够将门连结到宅邸内任何一扇门的空间传送，出口则是设定为罗兹瓦尔办公室的旁边。

「那个萝莉直觉还真敏锐。」

她知道昴是将上厕所当成藉口想做某件事才会那么说，背地里对碧翠丝如此挖苦后，昴便敲了敲办公室的门。

「罗兹亲，是我。可以打扰一下吗？」

「──可以喔，我也差不多想问问你是什么情况呢。」

得到房间主人的许可后，昴大大方方地走进办公室。在宽敞的办公室中，能够见到打扮成小丑模样的宅邸主人坐在黑檀桌旁──他就是罗兹瓦尔‧L‧梅札斯。

身为昴的雇主，罗兹瓦尔以左右不同颜色的眼瞳紧盯著昴。

「你们是不是又牵连爱蜜莉雅在做什么有趣的事啊？」

「与其说是牵连，应该说这次的开端就是爱蜜莉雅。我想你应该有很多话想说，只有今天你就睁一只眼闭一只眼吧。」

「在这个王选即将开始的时候，你要我别去注意这些琐碎小事吗？」

虽然罗兹瓦尔的话一针见血，但他的表情似乎显得更加愉悦，他总是会张开双手等待昴会做出何种反驳。

这个有讨厌嗜好的主人让昴叹了一口气。

「这段时间看起来也许没什么用，不过休息也是很重要的事。尤其是最近这阵子，大家应该都有感觉到那孩子太逼紧自己了吧？」

在昴被召唤的第一天就碰到王都的徽章被偷窃骚动，之后宅邸闹出魔兽骚动，前阵子还接连发生莉莉安娜的事件。虽然爱蜜莉雅在每个事件都是当事人，但还不至于到面对核心直接解决问题。

就立场而言，她不能主动接近危险，但或许因此也让她深刻感觉到自己能力不足。

昴认为此种反作用力，与最近爱蜜莉雅太过紧凑的行程有所关联。

只要是为了别人，她会毫不犹豫地勉强自己。而此种个性的爱蜜莉雅会在短暂休息时间依靠昴，表示这或许也是信赖昴的证据，如果真是如此会让昴相当开心。

「这样用来说服我好像还不太够喔。」

「只要在练习唱歌的时候学会腹式呼吸，声音也会变得比较宏亮，这有利于演讲！克服音痴还能培养自信，表情也会变得越来越开朗！然后美丽歌声传遍世界后，爱蜜莉雅酱就能得到国王与歌姬的双重头衔……！」

「好好，我知道了，我同意让她这段时间稍微喘口气。」

面对昴接二连三的推销，罗兹瓦尔选择举白旗投降。话虽如此，他并非是被昴的说服打动，这或许是他考量到最近爱蜜莉雅态度的让步。

「话说一开始把流丽丽交给爱蜜莉雅酱的人就是你吧？我是不知道你已经掌握这件事到什么程度，不过这样正好如你所愿吧？」

「从我的立场而言，有很多事做起来都很麻烦呢。还得考虑到爱蜜莉雅大人的个性，如果她能老实接受休息的请求就好啰。你觉得她会听话吗？」

「不觉得，怎么看都是表面接受，然后会在看不到的地方更努力。」

她的此种模样可说是十分耀眼，因此昴认为自己才会想要支持著她。

不论罗兹瓦尔有何种企图，他也是处在支援爱蜜莉雅的立场。即使与真正意图有所差异，今天的事应该还是在他的料想之中。

「不过话说回来，爱蜜莉雅大人的歌声……真的有那么糟糕吗？」

「糟透了。明明声音那么美丽，反而在相反的意义上出现了奇迹。」

「你又来了，这应该也只是夸饰法而已吧？」

「这就像人人羡慕的高级食材，全部在铁板上面煎到变成焦炭一样。」

「那真是太浪费了。」

「嗯，真是浪费。」

只有这点是无法以体贴掩饰的残酷真相。

两人感同身受地互相点了点头后，昴便朝罗兹瓦尔举起手说了声「那先这样吧」。

「我差不多该回禁书库了，我只说自己出来上厕所，要是拖太久可是会被误以为是大号的。」

「关于这点已经过了十分钟，应该已经没办法洗刷掉疑虑了吧？总之爱蜜莉雅大人就麻烦你啰。」

「好喔，那就让她暂时身为爱蜜莉雅酱吧。」

「哎呀呀……哈哈哈，这形容的还真妙呢。」

此种昴特有的兜圈子方式，让罗兹瓦尔发出笑声。

互相更新彼此的共识后，昴便带著主人的许可离开办公室。

「好啦……就算我想回去，不知道碧翠子的房间有没有换位置了。」

总之昴先打开刚才与禁书库连结的隔壁房间门扉。如果是平常，照理说禁书库的位置已经更新，眼前应该是满满纸张的资料库──

「喔，真是太幸运啰。居然能直接进来。」

幸好「机遇门」还没有更新，让昴毫无困难地再度回到禁书库中。

「我回来啰。哎呀～～厕所真是大排长龙塞爆了……」

昴随便找了个藉口走进禁书库，见到爱蜜莉雅、碧翠丝与帕克三人与离去前同样站在深处……

「不要～～！饶了我！拜托只有这点绝对不要！」

「贝蒂已经忍不住了！你根本就是小看音乐！现在给我立刻戴著水桶到外面唱歌！你缺乏的就是危机意识！」

「贝蒂……我说贝蒂，让莉雅这么难过实在很可怜呢。别这样逼她嘛，音痴其实也是很可爱的。」

「哥哥就是太宠她了！这就是助长她的原因！」

碧翠丝气冲冲地卷起袖子，拚命拉著仍然戴著水桶的爱蜜莉雅腰部。戴著水桶的爱蜜莉雅则是紧紧抓著书柜，而帕克正在两人身旁盘旋并用手打著节拍。

「────」

只是稍微离开十分钟，这里到底是经历过多么惨烈的状况？

虽然昴大概能够想像，但要是如同想像，除了叹气还是只能叹气。

总之不论如何──

「这原本只是让爱蜜莉雅酱放松心情的游戏，不知道有没有让她好好放松……我只担心这样会不会本末倒置了。」

昴微妙地担心著与罗兹瓦尔刚许下的约定是否会立刻告吹，然后加进吵吵闹闹进行课程的三人之中。

6

「所以呢？爱蜜莉雅酱觉得这次特训有效果吗？有没有感觉唱得比较好？」

「包在我身上。经过帕克和碧翠丝这么密集的特训，我已经浴火重生了……说是浴火重生好像说过头了，总之已经变好很多啰。」

「喔喔……突然很有自信又没自信了……」

经历过严厉特训后，爱蜜莉雅带著改头换面的表情挺胸回答昴的问题。

脚下能够见到与她共同历战归来的水桶，那光滑表面宛如见证著学生即将展现成果的教师一般。

「不过，做那种练习真的能治好音痴吗？」

「如果那点程度的特训就能治好那个像恶梦一样的音痴，就不用那么辛苦了。」

「喂！那两个状况外的！别说闲话灭她锋头啦！结果很快就会出现了！」

昴将做著发声练习的爱蜜莉雅拋在一旁，先让旁边窃窃私语的两人闭上嘴巴。在禁书库正中央专心做著发声练习的爱蜜莉雅并没有听见两人的话，便将视线转往昴的方向。

「……嗯、嗯、嗯！好了！昴，接下来拜托你了！」

「包在我身上，爱蜜莉雅酱。还有不论发生什么事都不准哭喔。」

「结果最不相信她的人是你嘛！」

接到爱蜜莉雅的指示后，昴便轻轻举起流丽丽以轻快节奏拨动琴弦，那平缓的曲调就是被称为﹃剑鬼恋歌﹄的其中一节。

昴自认技术完全比不上莉莉安娜，然而──

「在爱蜜莉雅酱这么努力的时候，只有我躲在安全地带也满丢脸的。」

即便爱蜜莉雅出糗，昴认为自己演奏失误也能帮忙分担耻辱。从开始前便一直想著该怎么支援，正表示她的音痴是如此令人印象强烈。

因此，在展现出特训成果的瞬间就让期待──

「──啦、啦、啦啦啦。」

「────」

歌声搭上曲调，从爱蜜莉雅的双唇间纺织出如铃铛般的声音……原先瞬间准备好迎接悲剧的昴吞了一口气，帕克与碧翠丝也瞪大双眼。

因为歌声搭配曲调的时间、掌握曲调的方式、音准与节奏都是相当完美。

「────」

爱蜜莉雅闭起眼睛并随著心情晃动肩膀，将心情融入歌曲之中。

她依照练习抓著节奏，依照练习掌握音准，依照教导的内容唱出歌曲。

──那是由银铃般声调编织而出，并且带有掳获人心魔力的天使歌声。

「────」

爱蜜莉雅曾经说没有人教过她唱歌，实际上连唱歌基础都不知道的她，先前唱出的歌甚至可说是痛苦的代名词都不为过。

但爱蜜莉雅靠著既老实且纯粹的天性，为了克服自己的音痴认真练习，吸收力就像是海绵吸到水一般。

「──唔！」

昴差点陶醉地听著歌声，于是连忙集中精神在演奏上。

爱蜜莉雅的歌声中带有魔力，让昴的演奏一直无法跟上。但即使如此，昴还是尽可能地拨动琴弦紧追不舍避免被拋下。

「……谢谢各位。」

专心演奏的时间终于结束，爱蜜莉雅的行礼让昴顿时回过神。

唱完歌的爱蜜莉雅抬起脸，以不安眼神等待著昴等人的评价。毕竟爱蜜莉雅先前没有发现自己的音痴，所以应该也对刚才的歌声毫无自觉。

「果、果然还是很糟糕吗？说得也是，要是能这么简单治好就不会那么辛苦了……」

见到昴等人过于吃惊毫无动静的模样，她甚至想到最差的方向。

因此昴摇了摇头，将惊讶拋在脑后并冲到爱蜜莉雅面前。

「不不不！爱蜜莉雅酱好厉害！刚才那个临死前的惨叫声到哪去了！？」

「惨叫声是什么意思啦！？」

这个不曾听过的评语让爱蜜莉雅相当吃惊，不过又对昴的表情不解地歪著头。

「该不会……有好一点了吧？」

「这不是好一点而已！完美！真是超完美的！我就是想听这种歌声！」

「嗯嗯，莉雅真是唱得太好了，这样才是我全世界最可爱的莉雅。」

见到昴对内敛的爱蜜莉雅赞誉有加，飞来的帕克也搭著便车如此说道。面对落到自己肩头上的小猫与昴的话语，让爱蜜莉雅不禁瞪大双眼。

她的表情似乎仍然难以置信，不过──

「──就像哥哥说的，还算不错嘛。」

「碧翠丝……」

「不过这点程度别沾沾自喜，还需要更多练习，和那个除了唱歌以外没有任何长处的吟游诗人相比还差得远呢。」

虽然碧翠丝拿出莉莉安娜损著爱蜜莉雅，但还是称赞她的歌声，这番话让爱蜜莉雅带著总算有实感的神情用手摀著嘴。

「──好高兴，这样我也不再是五音不全，我已经克服音痴了。」

「没错！总觉得有种很强烈的成就感耶！明明只是音痴而已！」

「喂喂，她现在已经不是音痴，已经是过去的事了。这点可得说清楚才行喔。」

对于沉浸在感动气氛中泪眼汪汪的爱蜜莉雅，昴与帕克皆对她点了点头，爱蜜莉雅则是吐出一口热气，而三人的模样让碧翠丝不禁发出叹息。

「总而言之，这样事情应该就结束了，可以麻烦你们离开禁书库了吗？」

「喔喔，不好意思啰。不过这次也多亏了你帮忙，谢啦。」

「这只是为了哥哥才不得已这么做的，而且她唱歌还有要改的地方，就是一开始那个哼哼哼哼的部分。」

碧翠丝开始准备把人赶出禁书库，最后还指出爱蜜莉雅唱歌的修正点做为饯别。她哼出的歌在一瞬间让禁书库的气氛瞬间冻结。

昴、爱蜜莉雅与帕克皆绷紧神情回头看著碧翠丝。

「……怎、怎么回事？为什么露出那么奇怪的表情？」

「碧翠子，刚才那是什么？该不会是﹃剑鬼恋歌﹄的开头吧？」

「不然还会听成什么歌？除了﹃剑鬼恋歌﹄还会有哪首歌？」

碧翠丝大大方方且毫无疑虑地如此回答，那挺起平胸的态度让昴瞬间理解，于是他转过头看向身后的爱蜜莉雅。

「爱蜜莉雅酱。」

「嗯，没问题。我也知道昴想表达的意思。」

爱蜜莉雅对这道呼唤点了点头，这时昴与爱蜜莉雅已经是心有灵犀，只见爱蜜莉雅默默地捡起地上的水桶走向碧翠丝。

「……你那是想做什么？」

她朝著靠近的爱蜜莉雅拋出问题，不过回答的人不是爱蜜莉雅而是昴。

「那还用说──你从现在开始就是水桶女主角二号。」

昴指著爱蜜莉雅手中拿的水桶，义正严辞地如此断言。

──这位幼女先前曾经嚣张地说著音乐精髓之类的话，结果也是个不输给天使的音痴。

「原来你也是没有自觉的音痴啊！这间宅邸是怎么回事啊！而且你们这些没音感的家伙有可爱声音真是太浪费啦！你们前世是做了什么坏事啊！」

「贝蒂怎么可能会是音痴！诬赖也要有个限度！只因为我刚才对她严厉了一点就用这个来报复，未免太阴险了吧！」

「碧翠丝！别担心！多亏有水桶老师才让我唱歌进步，只要戴上去唱歌肯定会变好的！来，戴上去吧！戴上去之后……说不定会很可爱喔！」

「咿呀～～！唔呀～～！我绝对不戴水桶！」

由于贝蒂四处逃窜拒绝戴上水桶，于是三人便上演著到处追赶的戏码，而帕克则是浮在三人头上笑著洗脸。

「嗯～～这离音乐的精髓『对音乐乐在其中』可能还要一段时间呢。」

它装模作样地如此说著，将这个以流丽丽为开端的一天如此作结。

** 『RAM IS ORDER』

1

──这是个深邃不见尽头的森林之中。

在昏暗的视野中，脚下满溢著几乎会令人呛到的草与土壤味。

此种连数公尺前方都无法见到的黑暗，便是因为头上茂密生长的枝木将阳光遮蔽住的关系。昴则是在一片深绿中慎重地摸索并踩著土壤前进。

当黑暗让人不知所措后，甚至连时间经过都会变得暧昧模糊。

明明是从拂晓时就开始准备，然后在清晨走进森林，该不会在外面世界已经日落并夜幕低垂了吧？

「哎呀，不用担心这种事啦。你看，连我都还能像这样实体化嘛。」

疲劳累积也会徒增不安，不过每当昴感到退缩时，就会有道悠哉声音激励著昴的心灵。

昴对此种悠哉声音露出苦笑，然后抬起头看著头上说话的对象。

「老爸对准时下班还真是不遗余力，在用尽力气回家前，千万别忘记发射通知我位置的照明弹喔。」

「喂喂，我看起来会这么少根筋忘记这件事吗？别看我这样，莉雅可是仔细拜托过我，我会好好完成工作的。」

面对昴别有含意的笑容，飘在头上的小猫精灵帕克则是如此回答。

这位精灵以缩著身体的姿势摸著胡须，然后继续说著：

「不过话说回来，一直找不到呢。」

「呃……也是啦，差不多该是开始认真烦恼的倒数阶段了。」

「呵呵，真是爱逞强呢。不愧是个男孩子。」

被看穿只是虚张声势，让昴尴尬地吐出舌头。即便有帕克跟随，在昏暗森林前进还是无法让他撇除不安。

而会造成此种状况的原因，其实就是──

「拉姆那家伙……要是我死了可是会变成幽灵回来找她的。」

昴对一成不变的景象发出咋舌声，并且说出走散的同行者名字，也是前来森林的这个罕见三人组其中最后一名成员。

与那位态度高傲且自大的粉红色头发少女────拉姆会合，就是目前昴等人的当务之急。

「虽然死亡的灵魂会成为幻影只是迷信，不过大部分的情况下，幻影常会停留在死亡的场所喔。」

「那根本就是在说地缚灵吧？」

「要是在森林迷路变成幻影，之后又持续留在森林就好笑啰。」

「听起来真是超遗憾的耶！」

互相说著玩笑话与耍嘴皮子后，不安的情绪也稍微减缓。昴一边感谢著身旁精灵的体贴举动，一边将额头浮现的汗水擦掉看往前方。

在昏暗并充满寂静的森林中，让昴有种自己并非孤单一人的获救感。

因此昴心中想著。

──现在得赶紧找出那位在森林中孤单一人的少女。

2

事情发生在一天多前，得回溯到昴进入森林前的前一天下午。

「唉……还真和平……」

昴慵懒地让上半身趴在餐厅桌面，让自己放松心情休息。

他穿著以黑色为基础的管家服，即使说好听实在不能算是很适合他，但比起当初「被迫穿上」的印象已经稀薄许多，目前算是稍微变得有模有样。

至少他每天早上从镜子确认自己时是这么想的。

「今天昴好像很高兴呢，是不是碰到了什么好事？」

将银发绑成三股辫的爱蜜莉雅，在昴身旁的座位歪著头如此问道。她那美丽的银发每天都是不同发型，能让昴赏心悦目地观赏不同的可爱风格。

「如果要说好事，那就是今天的爱蜜莉雅酱还是这么可爱，爱蜜莉雅酱总是能给我很新鲜的喜悦，就像是上天恩赐的及时雨一样。」

「我有给人那么阴沉的感觉吗？」

「刚才那段话被当成梅雨了吗！？」

面对天然呆的爱蜜莉雅，搭讪用的甜言蜜语总是不太管用。或许该说昴就是知道这件事，才会毫不害臊地耍嘴皮子。

「这种不被放在眼中的感觉真是会让人上瘾……不对，我当然希望你能认真听我说，这就是难以解释的复杂男人心……！」

「又自己开始烦恼了，男孩子真难懂……啊，这种茶好好喝喔。」

将无法割舍感情而独自烦恼的昴拋在一旁，爱蜜莉雅拿起手边茶杯送往嘴边，对茶的味道微微一笑如此说道。

这是在罗兹瓦尔宅邸的下午茶会──中午过后像这样聚集在餐厅让身心休息，已经渐渐成为众人的习惯了。

仆人们的工作暂时告一段落，爱蜜莉雅也正好在用功途中穿插休息。有空的人会自然地前往餐厅，共同度过这段短暂的休息时间，这是自从昴来到这间宅邸后不知不觉养成的习惯。

当然了，由于是有空的人才会参加，因此几乎很少有宅邸全员到齐的机会。目前维持全勤的，顶多只有想见到爱蜜莉雅而把工作完成的昴，以及每天趁著这个时间休息的爱蜜莉雅而已。

要所有人参加茶会可说是相当困难，而今天也没有例外。

「雷姆和罗兹亲很忙也就算了，碧翠子还真不会配合。」

对那位没有什么工作却不露面的少女，昴不禁面露苦涩，爱蜜莉雅则是对昴的不满神情掩嘴微微一笑。

「昴和碧翠丝感情真的很好呢，平常总是会互相在意著彼此。」

「感情好听起来有点语病。虽然她会让人在意，不过应该用别的方式形容……大概就像有碎花枝卡在臼齿上的感觉吧？」

感觉是个让本人听到又会吵架的评语，让爱蜜莉雅不禁越听越高兴，而昴也对此种有气无力的样子面露苦笑。

就在他们享受著只有两人的茶会时……

「──你们聊得还满开心的嘛。」

突然有道声音传进餐厅打断两人，令人有种既冷酷且不懂变通的印象，那是伫立于餐厅入口双开式门扉前某位少女所发出的声音。

少女以贯彻毫无感情的眼神，斜眼看著昴皱著眉头的表情。

「亏拉姆这么辛苦地准备茶水，居然把拉姆拋下做出这么淫荡的事……那个毛没想到变得那么嚣张呢。」

「只是稍微与爱蜜莉雅聊得开心一点就被当成淫荡喔！？一开始是大姊你自己接受准备茶水的，错不在我身上吧？」

「我不想看到毛在拉姆工作的时候过这么爽。」

「只是单纯的暴君嘛……！」

昴对此种不讲理的话语翻著白眼，这位少女────拉姆以毫不留情的眼神冷冷哼了一声。

「拉姆只是以公平观点加上偏见，评论毛平常的工作态度而已。」

「难得有公平观点就别乱加偏见，用更中肯的观点评论我这个人嘛。」

「如果刚才的评论撇除偏见，那毛的茶点得配送到地板上了。」

「为什么撇除偏见会降低评价啊！？」

面对拉姆确实很有可能会这么做的眼神，昴难掩颤栗地表示愤慨。

拉姆将昴的不满视若无睹，将带来的烤甜点盘子排在桌面上。这段时间内昴将茶倒进杯中，替拉姆准备对面的座位。

对于两人准备茶会的模样，爱蜜莉雅不禁微微噗哧一笑。

「爱蜜莉雅酱，怎么露出那么可爱的表情？」

「因为你们虽然抱怨著对方，不过说出来的话总是很投缘，看著看著就让我觉得很有趣呢。」

「真是太可怕了。」

「别这么斩钉截铁回答啦！我会很受伤耶！」

面对由衷露出厌恶神情的拉姆，昴按著胸前并高声如此回答。

「不过爱蜜莉雅酱说的也有道理，毕竟我一开始在宅邸一起工作的对象就是大姊，每天还互相分担处理杂事，多少有点投缘也是很正常的事。没错吧？」

「真恶心。」

「可以麻烦看一下前后脉络再说话吗！？」

拉姆仍然是一副不容冒犯的模样，让昴甚至很想称赞自己不屈不挠的勇气。

总之不论如何，昴在罗兹瓦尔宅邸的立场大致就是此种状况。

被爱蜜莉雅置若罔闻、被碧翠丝找碴、被拉姆冷落、只有雷姆展现出过度亲密的态度，但他认为这已经是相当优渥的环境了。

「不过话说回来，拉姆烤的甜点还满新鲜的。平常都是看雷姆来做，没想到大姊还有除了蒸蕃薯以外的其他特长。」

「毛，梦话还是少说点。拉姆以前说过拿手料理只有蒸蕃薯，当然不可能知道烤甜点之类的做法。」

「你是要忙得无法出席茶会的妹妹做了什么事啊？」

对于她那是拜托妹妹的言外之意，让昴顿时闭口不语。一想起雷姆惋惜地表示无法参加茶会的模样，口中的烤甜点也是传来令人不舍的甜味。

「不过，这间宅邸的各种餐点真的都得靠雷姆。虽然没有像大姊这么将错就错，但我对料理这块实在也没得抱怨别人。」

毕竟昴在原本世界是个无与伦比的米虫，不只是翘课又不帮忙家事，只有裁缝与整床异常拿手的米虫界超新星。

由于还有此种内情，于是昴将视线转向爱蜜莉雅试图改变话题。结果享用著烤甜点的爱蜜莉雅只是掩著嘴说道：

「我？哼哼，昴可能以为我不会料理，其实我做得还不错喔。虽然帕克也有陪我，不过因为我之前一个人住满久的，所以大多数料理都是小菜一碟喔。」

「最近没什么人会说小菜一碟了吧……而且不知道该怎么说，明明这段话说得通，可是瞭解爱蜜莉雅酱之后总觉得就没什么可信度了。」

这都是拜爱蜜莉雅释放出看来很能干、却总是笨手笨脚的气场所致。

在宅邸共同度过数周的时光后，爱蜜莉雅的印象与初次见面时可说是截然不同。当初强烈的才女气息，也在平时能够瞥见的稚嫩与天然呆一面中几乎烟消云散。即便如此，她那既直率且温柔的个性仍然没有改变，甚至让昴能够断言这点才是最好的优点。

不过撇除这点不谈，她给人「形象崩坏美少女」的印象也是不争事实。前阵子还被发现是个音痴，让昴感觉似乎还有更多未爆弹。

对于昴的不安眼神，爱蜜莉雅似乎很不服气地鼓起脸颊。

「唔……表情看起来就是不相信我。哼，我知道了，既然怀疑就让我做菜给昴吃吃看吧，要做好大吃一惊的心理准备喔。」

「咦？明明没有拜托怎么埋下能吃到亲手料理的伏笔了？我会被毒死吗？」

见到对自己有利的局面反而会心生疑虑，这就是昴的可悲习性。

实际上自从来到这个世界后，他迟迟无法否定善恶事互相抵销的印象。由于大部分都是恶劣坏事先造访，因此只要一先发生好事就会令他相当担心。

这次不知道会发生什么坏事抵销这次好事，果然还是爱蜜莉雅的手艺糟糕透顶，一吃到料理的瞬间就会徘徊于生死关头吧？

「昴，你望著远处是不舒服吗？是肚子痛吗？」

「我、我没事……就算我的胃烧掉，我也会努力把爱蜜莉雅酱做的菜吃完，相信我。」

「昴才是该稍微相信我的话吧！？」

这个不正常的想像让爱蜜莉雅气得开始闹著别扭。如果是平常，照理说拉姆应该会刻不容缓地用毒舌继续追击──话语却迟迟没有传进耳中。

「咦？拉姆大姊？你怎么了？」

「────」

昴带著出乎意料的心情回头一看，只见拉姆正默默地盯著茶杯，然后彷佛确认般用嘴唇沾了一口茶并看向昴。

这道视线让昴背脊窜过一股寒意，她那总是锐利的目光显得更加犀利。

「呃……拉姆大姊，发生什么事了……？」

「毛，这种茶是从茶柜的什么地方拿出来的？」

「茶？喔……你是说茶叶啊！那是藏在茶柜深处的茶叶，我以为是很贵的茶叶才会偷偷拿出来……烫烫烫烫！？」

「呀啊啊！昴！？」

当昴报告著寻宝的成果，随即被找出的宝藏撒了满脸。

从头被热茶淋到的昴烫得四处打滚，爱蜜莉雅赶紧将水瓶的水倒在昴身上。面对昴被茶与水弄得浑身湿透倒在地上的惨况，爱蜜莉雅紧紧瞪著突然做出暴行的拉姆。

「拉姆！你怎么做出这种事呢！这样昴和衣服还有地板会弄脏吧！」

「拜托别只担心弄脏！也要担心我有没有烫伤喔！」

昴对爱蜜莉雅偏离主题的叱责发出呼唤，但拉姆没有对任何一方出现反应，此种模样让昴与爱蜜莉雅面面相觑。

「呃……发疯的拉姆大姊？到底是怎么……」

「看你……」

「拉姆？」

「看你做了什么好事，毛。」

拉姆压低的声音中含有愤怒，以及难以掩饰震惊的颤抖。

因此昴无法回答「是你先动手的吧！」这种话，只能与同样面露困惑的爱蜜莉雅再度面面相觑。

3

看来事情并没有擅自使用秘藏茶叶而被处罚那么简单。

秘藏茶叶──虽然此种认知并没有错，但问题是此种茶叶会被如此珍藏的理由。原因并非是味道、品质或价格其中之一，而是效用。

「那种茶有促进体内玛那循环的效用，对旧伤很有效果。」

「你说的旧伤就是……」

「就是角的事。」

「呃、喔……对喔，你还有角的伤……」

对于拉姆毫不掩饰的回答，反而让昴心生动摇。

拉姆与雷姆两姊妹都是生于亚人鬼族，虽然外表与人类没有差别，只有在感情激昂时具有会从额头长出白色角的特性，但拉姆似乎已经失去鬼族的角，甚至还自称是无角者。

昴并没有过问失去角的经过，他也知道这是个很敏感的话题，因此得知擅自使用的茶叶有治疗旧伤的药效时，让昴心中只有满满的罪恶感。

「那个茶叶要怎么样才能拿到？这次完全是我的错，可以等我出人头地再把这笔帐还清吗……」

「很可惜，没有那么容易找到对角旧伤有疗效的茶，那是拉姆将有药效材料调配成自己喜欢味道的特制品。」

「唔呃……真的假的……顺便问一下，没有那种茶大概会多难受？」

「没什么，接下来每个晚上都会没办法好好睡觉而已。」

「真的很对不起！」

由于情况比想像中严重，让昴除了弯腰赔罪以外别无他法。随意行事衍生出大问题，简直像是人类历史总是反覆上演的缩图。

想挽回也不是如此容易的事。

「那种独家配方的材料要去哪里才找得到？」

昴认为自己无法撇清责任，于是在地面正座如此主动问道。拉姆挽著双手俯视著昴并露出微笑。不知为何，此种微笑令昴不寒而栗。

「这样啊，意思是你想帮我收集材料吗？」

「毕竟这是我做出的错事……不过大姊，你的眼神会不会太可怕了？」

「别担心，不会花你太多时间的，材料全部都能在宅邸附近收集到。」

虽然拉姆面带微笑地说著「能收集到」，但不知为何感觉并非是昴想像中的采集植物，听起来还得与动物打交道，让昴希望这只是会错意而已。

结果，昴最后决定隔天出发收集特制茶叶的材料。

虽然事发突然，但拉姆的肉体每天都会增加负荷，因此赶紧解决并不会是什么坏事。幸好据说茶叶的材料能在宅邸周遭的山林间得到，因此等于是花上一整天的健行。

「如果可以的话，其实雷姆一起跟去应该是最好的……」

「这也是没办法的事。我和拉姆也就算了，要是雷姆放下一天工作，整间宅邸就会停止运作。这就是俗话说的适才适所，我就是适才，但不知道山上算不算适所就是了。」

在夜色尚未拂晓的清晨时分，有四个人影聚集在玄关大厅处。分别是准备出发前往山上的昴与拉姆，以及前来送行的爱蜜莉雅与雷姆四人。

如同前述般，爱蜜莉雅与雷姆有宅邸事务无法同行，因此雷姆从昨晚便没有放下担忧，连现在都是频频对拉姆提醒。

「姊姊，姊姊，在山里请记得注意昴，还有别让昴随便乱碰奇怪的叶子，可是会引起皮肤炎的。请注意踩到岩石区的青苔会滑倒，再来就是跌倒也不会哭的祈祷咒语……」

「我会忍住的啦！就算跌倒也不会哭！不用这么担心我啦！」

「好好，我知道。雷姆，要是毛哭出来我会在他膝盖上吐口水的。」

「别把在伤口上涂口水说的那么恶心啦！」

对于摆脱因为担忧而变得过度保护的雷姆，就连拉姆回应到后半段都显得有些敷衍。而在说话的两人身旁，爱蜜莉雅仍睡眼惺忪地用手掩著哈欠说道：

「我想有拉姆陪同应该不会有问题，不过千万别逞强或是做傻事喔。有结界应该就不会碰到魔兽，但要小心天气和虫子，被叮到可能会肿起来喔。」

「到时候爱蜜莉雅酱再替我温柔摸一摸就没事了。还有把帕克借来真的没问题吗？虽然这样真的会帮了我们不少忙。」

在如此说著的昴脖子上，能够见到平常爱蜜莉雅佩挂的项炼，发出光芒的绿色结晶就是精灵帕克的依附媒介。

这是爱蜜莉雅担心两人进入山林而让昴携带的保险措施。

「昨天晚上我已经拜托过它了，所以没有问题的。而且帕克就算留在宅邸也只会妨碍我念书，陪在昴身旁反而会比较令人放心。」

「那、那我就恭敬不如从命，稍微借一下这只家猫啰。」

昴带著苦笑用手指弹了一下项炼。在里面沉眠的精灵似乎会在起床时间擅自出现，所以昴很期待它能在山林中发挥力量。

「虽然我觉得不会发生事情，不过要是在山林出事，帕克会通知我，也能立刻知道出事的位置。我想雷姆应该也会火速赶过去，所以你们别担心。」

「在爬山时遇难呼叫搜救队会让我良心不安，我会注意别出事的。」

昴感谢著爱蜜莉雅的贴心举动，并且将穿习惯的运动鞋鞋尖敲了敲地面。他考虑到登山而换穿运动服，然后再背起准备装材料的背包，这样昴就做好了变身为背包客的准备。

「毛，准备好了吗？差不多该出发啰。」

「好好，一切都听大姊差遣。」

以平常的语气如此回答拉姆后，昴便最后转头看向爱蜜莉雅。

「那我出发了。虽然会给雷姆添麻烦，不过今天就麻烦你了。」

「好的，午饭已经装在背包里，路上请与姊姊一起享用。」

「我就实话实说啰，里面也有我亲手做的料理，猜猜看哪个是我做的吧。」

在似乎以为这是野餐的爱蜜莉雅，以及直到最后都带著担心神情的雷姆目送下，昴与拉姆便在朝雾中出发前往山林。

4

「说到茶的材料……到底需要些什么东西？」

由宅邸出发后，两人随即偏离平常通往阿拉姆村的道路走向山路，昴朝著走在前方的拉姆那小小背影如此问道。

面对这个问题，拉姆没有回过头并竖起四根手指。

「需要的材料总共有四种。首先是米莉吉雅花，虽然那是稀有的蓝色花朵，不过那在昴对爱蜜莉雅大人搭讪的花田里就有了。」

「你、你你你怎么会知道这件事！？」

「我很清楚位置，所以花可以摆到最后。第二个是在森林中，只会在特定种类树根生长的巴洛叶菇，要把这种菇干燥磨成粉状，顺带一提那是毒菇。」

「有毒喔！？吃下去没问题吗！？」

「没事的，反而还可以获得免疫力。接下来第三个比较麻烦，是只会长在波克阳树顶端的红色果实，需要那种果实的种子。」

「喔喔，感觉总算出现比较困难的正常材料了。」

「波克阳树是异常高耸的树木，而且除了种子以外的部分，带有用手摸到几乎会把手指融化掉的剧毒，这点你也得注意。」

「怎么又是毒啊！你是没吃毒就会死掉吗！？」

「毒和药只有一线之隔，药效过度也会变成毒的意思。我忘记说了，米莉吉雅花没有毒，不过是食虫花。」

「我和爱蜜莉雅酱的美丽回忆要被食虫花玷污了！」

或许该说，光是想到先前曾经享用大部分以这些素材做成的茶，就让昴不禁背脊发凉。虽然有对角有很好的疗效，但难道不会对普通人体造成危害吗？

「这方面不会有问题吧？」

「接下来只要用毛的身体花一整天的时间就能证明了。」

「唔喔～～！没想到居然被当成实验品了！」

「我是开玩笑的，药效喝下去马上就会出现，如果有害处，毛在晚上早就死了。」

「这一点都不算玩笑！真的没问题吗！？」

虽然昴张开嘴巴作势呕吐，但昨天喝下肚的茶早已消化，昴只好祈祷著自己的身体不会出事，然后将意识转回到材料的话题上。

「所以呢？最后一个是什么？虽然我完全没有好预感。」

「最后一个是……说得也是，在你见到实物前先保密吧，这是拉姆给毛的处罚。」

「还有比喝毒茶更重的处罚喔？」

「是毛擅自拿出来喝的，这也能算是对爱蜜莉雅大人下毒吧。」

对于这个回应挖苦的讽刺，让昴连个闷哼都发不出来并保持沉默。

先前举出各种毒药的拉姆选择隐瞒第四样材料，表示不是毫无意外性的普通材料，不然就是连说出口都会忌讳的恐怖材料。

要是只有这两种选择，昴也不想知道是什么材料，只能尽可能地祈祷是前者。

「不过像这样和你进入森林，让我想起上次来找雷姆的事。」

「就是毛丢脸地被狗咬，结果被罗兹瓦尔大人华丽地拯救的事吧。」

「那件丢脸的事对你来说确实是华丽回忆啦，不过今天应该不会碰到魔兽吧？我先说，我的装备只有道具袋和流星丸而已喔。」

流星丸是昴擅自取名的爱用菜刀，虽然已经有许多蔬菜成为刀下亡魂，但目前并没有在武器方面派上用场。

如果要以菜刀对付魔兽，夹著尾巴仓皇逃走或许是更好的选择。

「不用担心，没有人把毛当成战力，拉姆也不想之后被雷姆骂……真是的，为什么拉姆非得被骂不可？」

「呃……抱歉啦……对了！在森林的沃尔加姆应该已经被罗兹瓦尔全部消灭了吧？所以有需要戒备魔兽吗？」

「在森林的魔兽不是只有沃尔加姆，或许该说因为那一带被占据的地盘空了下来，现在应该有其他魔兽频繁抢夺地盘吧？虽然没有沃尔加姆这么危险的魔兽，毛碰到应该还是会变成一堆白骨。」

「不用你说，我也不想再与魔兽扯上关系了。哎呀，只要它们乖乖生活应该就不会碰面了吧。」

「这就难说了，总觉得毛的愿望没办法实现了。」

「为什么啦？」

「这是女人的直觉。」

明明只是随口说说，但不知为何「女人直觉」这几个字却如此具有说服力。

昴感觉到有些难以释怀，并且对脑中浮现的另一个疑问歪著头问道：

「我从以前就觉得很奇怪，魔兽与普通动物有什么不一样？」

「──从根本上就有决定性的差异喔。」

回答疑问的人并非是拉姆，这道熟悉声音是从昴胸前发光的项炼传来。由辉石溢散而出的光点形成小猫的形状并让精灵现身。

手掌尺寸的小猫帕克飘浮在昴面前，只见它伸直身体并开口说道：

「魔兽与动物的外观差距就是角。虽然有角的动物并不一定是魔兽，不过魔兽肯定会有角，这点还是记起来会比较好喔。」

「谢谢你的说明，不过你今天好像比平常还早起床喔。」

「毕竟莉雅已经拜托过我要好好做事了。如果你们不排斥省电模式，我应该能比平常陪你们更久，负责炒热气氛摆脱恐惧的任务就包在我身上吧。」

「爱蜜莉雅酱拜托你的工作绝对不是这个吧。」

帕克挺起胸膛并如此随口说说，然后这只小猫便直接降落到昴的肩膀上，晃著尾巴并将肉球抵在脸颊上。

「大精灵大人，很不好意思特地请您陪我们。」

「嗯～～不会啦，偶尔也想让莉雅在没有亲人的顾虑下好好放松心情呢。」

「我都不知道你是个这么体贴的绅士，而且没想到拉姆对帕克也是用敬语。」

「这是场面话而已。」

「我不讨厌这种既率直又勇敢讲实话的个性喔～～」

帕克对风格刁钻的拉姆展现宽容态度，昴则是对此苦笑以对。冷静下来仔细想想，昴认为这三个似乎很少如此碰面，或许是在宅邸完全没有出现过的组合。

「只希望我们三个别捅出什么篓子就好了……你应该听爱蜜莉雅酱说过今天的目的了吧？那就万事拜托啰。」

「嗯，别担心。如果下雨就毫不犹豫地把我举在头上挡雨吧。」

「感觉这用途真是超狭隘的，而且凭你这种大小肯定会被淋湿吧。」

想到将淋湿的猫放在头上的景象，就让昴不禁叹了一口气。

「话说拉姆，差不多越来越像踏进林间小路了，你有头绪哪里能找到目标的材料吗？」

「真是蠢问题呢，毛以为拉姆已经进来这座山几次找材料了？」

「从你平常的工作态度来看，我只是担心你会不会连这件事都是叫雷姆来做。顺便说一下，如果你知道位置就画一份连我也能看懂的地图……」

「先在脑中画一份属于自己的地图再来说吧。」

「意思就是靠经验吧，学姊我知道啰。」

不只是隐瞒其中一项材料、位置只能靠著拉姆的记忆、别说是战斗，连知识都无法派上用场──昴不禁开始怀疑她到底是为了什么把自己带出来。

「是搬东西兼炒热气氛吗……？」

「啊，如果要比炒热气氛我也不会输喔。呵呵，来看看谁比较厉害吧。」

先不论责任归属，帕克对烦恼著自己用途的昴悠哉地如此说著。由于语调听来实在太过悠哉，让昴忍不住歪过头压扁肩上的精灵。

「喵～～」

「喔，好舒服喔，就是这样。」

「喵喵喵～～」

碰到脸颊的感触相当舒服，让昴暂时一边听著帕克的哀号声，一边努力地走在不习惯的山路上。

「……唉。」

对于这对毫无紧张感的人与猫，拉姆的傻眼叹息声也没有被两人听见。

5

之后，冒失三人组的冒险碰到了无数难题。

举凡昴不小心碰到会让皮肤起疹子的植物、昴从岩石区的青苔不小心滑倒、昴要采收目标的毒菇时不小心被流星丸切到手、昴要爬上波克阳树时手一滑掉了下来等等，经历过这些惊人的壮阔冒险后，让昴不禁快要哭了出来。

要是没有雷姆的祈祷，说不定昴已经是既丢脸又痛得哭了出来。

「真不愧是雷姆，没想到居然能看得这么远事先提供建议……」

「居然能把雷姆的担忧全部化为现实，拉姆真是太失望了。为什么你能把别人提醒要注意的事这么准确地当成耳边风？」

「等等！这未免说得太难听了！应该说我没有把建议当成耳边风！我只是努力过却能力不够而已！别只是看结果也要评论过程啊！」

「结果才是一切。」

「好好，对不起啦。」

满身脏污的昴正在让帕克治疗擦伤，帕克能够使用治愈魔法也让他相当吃惊。

「教导莉雅精灵术的人可就是我喔，不过因为对治愈魔法的契合度不高，所以没办法像贝蒂一样治疗重伤，这点程度的小事我还能处理。」

「不好意思，明明有时间限制还让你浪费MP。」

「不会啊，反正我消失也是昴需要烦恼的事，这也算是自作自受。」

「我能感觉到你没有想勉强自己留下的意思了。」

膝盖与手肘的擦伤已经痊愈，昴则是举起手与空中飞舞的毛球击掌表示感谢。

拉姆斜眼看著两人的举动，她目前坐在似乎不足以称为溪流的小河边。虽然不能直接喝生水，但是个很适合休息的场所。

目前时间刚过中午，根据场所与饥饿程度，拉姆提议在此处享用午餐，昴则是顺从她的指示顺便治疗伤势。

「虽然路上碰到很多困难，不过总算顺利收集到材料了。不只是勉强采到毒菇和种子，也知道花生长的位置，没想到还满轻松的嘛。」

「我应该说过没有什么危险，路上是毛自己把困难度提高的。」

「唔唔……实在没办法回嘴……！」

到目前为止的各种失误，让昴无法反驳拉姆的挖苦。在清流中清洗肿起来的右手并将运动服的脏污拍掉后，才总算回到刚出发时的状态。

他也将采取毒菇时使用的流星丸放进河中清洗，正当他稍微喘了一口气时──

「难得有这个机会，也得把这条河川记下来才行。」

昴一边望著河流，一边从行李袋中拿出厚纸与看似蜡笔的道具，然后以轻快动作在厚纸上开始画著图。虽然只有单色蜡笔，但画出的图可说是颇为优异，昴也没有忘记在各处以日文留下注释。

「毛自从进入山里就一直在做这件事，是在玩什么游戏吗？」

「这不是玩游戏啦！这是更有价值的事！」

昴一边翻找著午餐的布包，一边朝窥视著手边的拉姆如此反驳，然后将刚画好的图抵在她面前。

「你看，这是我做的地图，人在开拓未开发秘境的时候都会制作地图。只要把哪里有什么东西记下来，之后就不需要烦恼了吧？」

「没想到毛的手还满灵活的，不过那张地图真的有用吗？就算茶叶材料用完，拉姆只要再出来采就好了，就算叫雷姆出来收集素材，雷姆应该也知道位置。」

对于拉姆对地图提出的疑问，昴只是带著苦笑卷起地图。确实如同她所说，对于已经熟悉材料位置的拉姆或许没有用处，不过……

「只是预防万一而已。」

「预防万一？」

「要是茶叶又用完，就会让拉姆不舒服地卧病在床，然后那时候要是雷姆又刚好出去办事不在宅邸，罗兹瓦尔又不知道跑去哪里。没有半个能够倚靠的人！万一变成这个样子的时候，只要有这个我也能出来收集材料。」

这确实只能当成万一中的万一，几乎没有任何方法能用时的手段。

「要是这张地图能当成安心与保险用就好了。」

如果没有用处也没关系，不过要是能够派上用场，到时候再来感谢当初有做地图的判断吧。

为了救命的道具，就是要在希望别派上用场的情况下制作。此种目的意识与理念的矛盾，不论在什么东西上都会出现。

「────」

对于昴的回答，拉姆带著有些复杂的神情默默不语，她那似乎有些惊讶的罕见表情让昴搔了搔头。

根据听的人不同，刚才那番话或许会令人有些害臊也说不定。

「总、总之只要有这张地图，就算我不小心遭山难感觉也能生还！大概就是这个意思！以人命最优先就得多少吃点苦！」

昴饶舌地如此说著试图掩饰，然后将卷起的地图塞回裤子后方的口袋。包含用日文写的部分在内，回到宅邸后看来有需要再整理过。虽然这是他首次制作地图，不过他认为自己应该画得不错。

此种不起眼的灵巧手艺与周到态度，也是菜月•昴没有自觉到的长处。

「好啦，赶快来吃饭吧。不快点吃饭我就要饿扁啦！」

「──说得也是。好吧，来用餐吧。」

昴拍了拍手让气氛回归正常后，拉姆点了点头表示同意。然后她打开装有午餐的布包，沉默不语思考一段时间。

「难得被毛的话打动心灵，那就给毛一个奖赏吧。」

「咦？你那句话是在埋什么伏笔？总觉得让人没有办法放下心，应该说只有不好的预感，我可以拒绝吗？」

「哎呀，感觉角的旧伤好像又在痛了，说不定还开始发烧了。」

「别把别人的良心当成人质！我知道了啦！尽量放马过来！要拿什么出来都没关系！」

「不是那么需要大声嚷嚷的事。难得有这个机会，就把大的布包给你吧。」

在畏畏缩缩的昴面前，拉姆将左手拿著的饭团布包显露了出来。大小约有孩童的拳头大，见到这个布包让昴不禁松了一口气。

「吓死我了，害我以为是什么事吓得要死，这点程度还算是能容许的尺寸，应该说这根本就是普通大小嘛。」

「没错，那你就收下吧。」

面对放心的昴，拉姆将藏在右手的王牌拿了出来。

见到约有孩童头部大小的布包，让昴对此种尺寸的存在感顿时哑口无言。

「顺带一题形状有点奇怪，这个肯定是爱蜜莉雅大人亲手做的。」

「我也大概知道啦！可恶！什么『我就实话实说啰，里面也有我亲手做的料理』嘛！她根本没有隐瞒的意思嘛！这么大颗是要怎么藏啦！」

脑中明明能够想像出她在雷姆身旁一起捏著饭团的模样，但实际上或许不是这样。如果是在雷姆陪同之下做出了这种饭团，一想到迟早会到来的爱蜜莉雅展现厨艺时间，便让昴感到不寒而栗。

昴怀著一丝希望看向帕克，但妖精只对他的视线摇了摇头。

「莉雅很可爱，光是这点就能容许一切了吧。」

「可恶，我能理解你的心情！」

见到帕克面露放弃地看著远处，昴也做好决定面对现实的心理准备。

总之不论如何，只是区区饭团应该不会因为制作者改变味道。为求保险昴先吃了一个雷姆做的饭团，仔细品尝过雷姆的心意后再挑战爱蜜莉雅的饭团。

「──好重。」

大腿上传来压倒性的质量，几乎颠覆昴心中对饭团的概念。

他屏著气息将手搭在布包上，然后正当他准备拜见内容物时──

「包装纸下面还有包装纸？」

当昴下定决心将包装纸打开，发现里面还有以包装纸做成的防御。那应该是包得太大，因此只用一张包装纸无法维持形状，藉著包裹许多层才能压抑此种巨大质量。

就像是用许多层结界封印具有强大力量的怪物一样。

「呃……这是什么比喻法啊。」

昴不禁对自己的想法感到傻眼，然后剥开包装纸确认内容物。迟迟无法见到本尊让昴有些焦急，然后一张张地剥开包装纸后──

「──啊。」

包含屏气凝神的拉姆与帕克在内，三个人皆异口同声发出这道声音。

在打开层层包装纸的瞬间，失去均衡的饭团突然从昴的大腿上滚落，菱菱角角的圆饭团就这样滚落地面。

「等等等等！」

昴连忙起身追赶滚落的饭团，就像是著名童话《饭团滚走了》一模一样的情况，重现度实在太高了。

就在饭团进入斜坡开始加速前，昴飞身一扑用指尖将布包勾著并松了一口气──但事情就发生在下个瞬间。

「喔？」

脚突然踩了个空，让昴的身体在空中游泳。低头一看便能发现脚下角度急遽倾斜，让昴脑中闪过「滑落」二字。

完全重现故事剧情的巧妙安排让昴扯开喉咙，不过当然是指坏的方面。

「毛──！」

「哒巴巴巴巴巴巴巴巴──！」

昴一边听著拉姆带有焦急感的叫声，一边抱著饭团倒栽葱地滚落斜坡。

他的脑中只能想著幸好地面长满树木且相当柔软……

6

──接著，故事回到开头昴与帕克两人的旅行。

「滚下来的瞬间我还以为自己会死掉……」

「我也是这么想的，不过幸好没死呢，和那个粉红色头发的女孩子也顺利沟通了。」

「幸好你会飞才帮了个大忙……你也可以带著我飞喔。」

「我想只有昴的头发会被扯掉吧。」

「为什么是抓头发飞啊！还有其他飞的方式吧！」

昴与帕克如此说著话，并且朝著与拉姆会合的目标继续前进。

由陡坡滚落之后，昴找到了下来确认生死的帕克后，然后靠著这位精灵往来两处与拉姆确认会合地点。虽然拉姆表示要从陡坡下来，不过滚了整条陡坡的昴表示太过危险而拒绝了这个提议。

「只要沿著陡坡前进应该就能会合了，我可是不会让你特地冒险的！」

「我会把你模仿得很像的事告诉她的。你想听她怎么回答吗？」

「哼！」

「哇，模仿得好像喔。」

模仿拉姆看扁昴的模样后，帕克佩服地拍了拍手。然后小猫看著一脸无奈的昴并歪头问道：

「话说回来，你吃过莉雅的饭团了吗？」

「毕竟布包里面没有事，而且与充满震撼感的外观不太一样，里面毫无问题地很好吃。就连咸味也是，一想到那是由爱蜜莉雅酱亲手调味就有种很特别的感觉……」

「下次我也一起参加捏饭团吧，不知道你有没有信心猜出来呢？」

「混了一堆毛的饭团不就是你做的吗？」

两人就这样说著废话，不过这也是帕克避免让昴担忧的贴心举动。

指示会合的方向，与拉姆分头行动约两小时后──虽然昴沿著陡坡持续前进，但森林的天色却越来越昏暗。

说不定是方针有误，此种不好的想像甚至在脑中越滚越糟。

「──昴，先停下来。」

累得长长吐出一口气后，肩上的帕克突然拉著昴的耳朵。

此种感触让昴屏住气息并绷紧手脚，有道令人不悦的声响突然掠过昴的鼓膜，那是生理上令人无法接受的威吓生物声。

而声音的来源正缓缓从草丛间出现在昴的面前。

那长满湿润鳞片的绿色身体，正从布满锐利牙齿的口中发出彷佛啜血般的威吓声，但最值得一提的莫过于那在黑暗中发光的两对赤红眼眸。

双头蛇──身体上有两个头的双头蛇正瞪著昴，那条蛇的头部还长有短短的白色角。

「……该不会是长得很像魔兽的蛇吧？」

「虽然这是个很有趣的解释，不过那是魔兽喔，而且还是颇为凶猛残暴又有毒素的双头蛇。」

「双头蛇……不过和我印象中的双头好像不太一样。」

眼前的魔兽并非是在身体延伸处分成两个头，而是更单纯地在头与尾巴长出头，的确没有违背双头这个名字的意思。

「与其说是双头蛇，这比较像是前后头蛇吧，这样大便是从哪里出来啊？」

「基本上魔兽会把吃进肚子的东西化为玛那吸收，所以是不会大便的。」

「真像是偶像的一群家伙，它们是想找食物链麻烦吗？」

虽然态度看来从容不迫，但其实昴对这只双头蛇是尽最大本能提高戒心。

魔兽的尺寸约有两公尺长，双方距离大约有十公尺。这点程度的距离，魔兽应该会一口气拉近。

「我还没问一下，今天的帕克大概能打到什么程度？」

「哼哼，那点程度的魔兽很轻松就能解决掉了。不过说到难处就是没有莉雅的辅助，收拾掉魔兽之后就没办法陪昴说话了。」

「命是没有东西能取代的。那就麻烦你了，大师。」

「真是拿你没办法，那只能回应你的期待了……咦？」

当他们说著话时，双头蛇的体色与眼神突然染上攻击色泽，魔兽瞬间扭动巨大身躯准备扑向昴──

「芙拉──！」

下个瞬间，袭来的风刃将双头蛇身体切成两半。

在惊讶的昴面前，双头蛇没有发出惨叫声便瞬间毙命。面对魔兽喷出青绿色血液的死状，昴转头看向帕克，但小猫只是摇了摇头。就在这个时候……

「拉姆的女性直觉果然猜中了呢。」

拉姆穿过先前魔兽出现的树丛，开口第一句话就是挖苦。距离数小时后的会合，看来就是由拿著法杖的她拯救昴脱困。

「呼……真是帮了大忙，拉姆。」

「在山里走路地图有派上用场吗？」

「重逢喜悦的短暂时间仍然不忘撒上名为毒舌的香料，大姊真是太帅气啰。」

拉姆对放心坐倒在地的昴嗤之以鼻，然后收起法杖靠近双头蛇的尸体。只见她仔细观察魔兽的尸体。

「喂……你在做什么？」

「这还用说，就是完成今天进入森林的目标。虽然正如预期，不过还是立了大功呢，毛。」

拉姆一边如此说著，一边从被切成两半的双头蛇身体──大约正好是前后头部的中心位置用小刀切开，从里面剥出某个看似白色结晶的物体。

「这是魔兽体内的纯粹玛那结晶，比想像中还大呢。」

「那就是第四样材料吗？毒蛇身体里的结晶比想像中还糟耶。」

面对满意地回收材料的拉姆，昴不禁对路上的不祥预感成真感到相当沮丧。难怪拉姆会闭口不谈，要是昴知道与魔兽有关也会更加提高戒备──

「啊！我知道会带我出来的真正原因了！你是想利用我容易吸引魔兽的体质来收集毒蛇结晶吧！」

「难得脑袋动得这么快呢。原本需要花好几天搜寻的魔兽，居然只花半天就能解决，这次得称赞毛总算派上用场了。」

「我说你啊……」

见到拉姆毫无反省之意的态度，就连昴也忍不住怒火中烧。

为了拯救雷姆，昴与拉姆先前曾经一起踏进魔兽潜伏的森林。拉姆当然也知道昴的体质与危险性，然而竟然把昴用来吸引魔兽与跨越结界，这几乎等于是拐骗的程度──

「不对，先等等喔。话说我是什么时候跨过结界的？」

昴发现前提条件不太对劲，于是转头看向帕克。虽然个性温吞，但再怎么说还是个精灵，这只小猫有可能没发现已经跨越过结界吗？

「嗯……被发现了吗？我说昴……」

「大精灵大人。」

帕克对昴的疑虑做出反应，不过拉姆突然出声打断。昴对这番对话感到有些不太对劲，然而拉姆仍然不理会地迈开步伐。

但是，她的脚步突然变得踉踉跄跄。

「喂，拉姆！」

昴随即拉著脚步踉跄的拉姆的手并扶著她差点倒下的身体，她那异常滚烫的身体让昴吓了一跳，仔细一看还能发现她的额头与后颈布满汗水。

「和沃尔加姆那次一样用光玛那了吗！喂，拉姆！」

「没什么大事……快放手。」

与其说是倔强，她的态度比较像是逞强。于是昴不由分说地像以前一样抱起拉姆，她的身体仍然相当轻盈，而且持续传来滚烫的感觉。

「真是下流。」

「别说话乖乖给我抱著就对了！喂，帕克！把那个材料也放进背包里！然后把我带到波克阳树那边！地图会派上用场……你应该知道怎么走吧！」

「看来歪主意被拆穿啰。好好，我知道了啦。」

昴抱著一脸懊恼的拉姆追著向前飞去的帕克，他不顾周遭地努力奔跑，脚与肩膀也被枝木划伤。

即使皮肤被划伤仍然持续奔跑，只要专心奔跑不论是谁都会这样。

因此，怀中拉姆的白皙肌肤当然也出现几条红色伤痕。

7

「也就是说，她一开始并没有利用昴当成诱饵的意思，她只是想在结界附近随便晃晃引诱出几只魔兽。结果昴自己追著饭团穿过结界，才会闹出这么大的事。」

如同早上所说，昴等人回到宅邸正好是用晚餐的时间。

然而见到三人仓皇归来的模样，当然无须赘述地无法开始享用温馨晚餐。

「在会合之前，她应该是努力用『千里眼』寻找昴的踪影。我想这就是她会这么累的原因，不过她绝对不会承认的。」

「那你为什么要帮拉姆？」

「毕竟莉雅已经拜托过我啰。说是拜托，其实只是要我在你们碰到危险的时候保护安全，算是莉雅拜托我的额外服务吧。哎呀，毕竟是莉雅的饭团才让你碰到危险，这点还要请你多多包涵啰。」

说完事实真相后，这位超过固定时间仍努力导航的精灵便消失踪影。

窗外已经是夜幕低垂，这位努力加班的精灵明天肯定会睡过头。虽然昴也很想立刻倒回床上，只可惜最靠近的床已经有人先呼呼大睡，看来这个愿望应该是无法达成了。

「不好好说她个两句，我实在没办法善罢甘休。」

昴如此说著，然后在床上沉眠的拉姆身旁搔了搔头。

昴将昏倒的拉姆带回来时，整间宅邸顿时闹得沸沸扬扬。尤其是雷姆特别慌张的模样，反而造成了爱蜜莉雅还比较可靠的稀有景象。

治疗过拉姆身体的擦伤后，替她擦拭干净身体并换好衣服躺在床上。昴则是一边接受盘问，一边掩饰著爱蜜莉雅饭团的事说明来龙去脉，并且将收集的材料交给雷姆，目前她应该正在制作先前用掉的那种茶叶。

虽然昴也被说过先去休息，不过他并没有回自己房间而是继续待著。至少到拉姆醒来为止，昴想将此种五味杂陈的情绪发泄在她身上。

接著──

「……真是下流。」

「……我先说清楚，我可是有先得到雷姆的同意。」

拉姆微微睁开眼睛，朝著伫立在床边的昴一开口就是这句话。昴先是对她一如往常的反应露出苦笑，然后拍了拍自己的胸膛。

「就像你看到的，我们已经顺利回到宅邸，收集的材料也交给雷姆了。顺带一提，我做的地图在回到宅邸的路上可是派上很多用场。这就是俗称的有备无患吧？」

实际上昴制作的简易地图确实是效果卓越。

让帕克带回到醒目的波克阳树后，从该处顺著地图几乎是一直线回到宅邸。要是没有地图，说不定就得在森林过夜了。

「哎呀，如果真得过夜就得靠著帕克通知等雷姆赶过来了……这次如果有让你学乖，记得要承认地图的效果，然后要相信自己的同伴，别随便把人当成诱饵。」

「……这样应该是最有效率的做法吧，你想怎么抱怨就尽量说吧。」

「不抱怨就是我的抱怨，这样对现在的大姊也比较有用。」

拉姆仍然将头躺在枕头上，微微绷紧脸颊以斜眼看著昴。她的反应让昴得意地露出窃笑，而且有种总算一吐怨气的舒服感受。

「我已经听帕克说过大致的来龙去脉了。虽然让我满火大的，不过我这次什么都不会说。」

「传闻中精灵总是充满义气不会随便泄密，看来认识那位大精灵之后就会颠覆这种概念，以后拉姆不会再相信那个传闻了。」

「这次可是受到他的放浪个性帮了不少忙，所以别说他太多坏话喔……我差不多该去叫雷姆了，得去告诉她你已经醒来的事。」

昴对抱怨著帕克的拉姆耸了耸肩，然后让自己站起身。

「等一下，毛。我有事情要拜托……不对，这是命令。」

「真是会让人没有干劲的修正语气方式。是想要我做什么事？」

「那个桌子的抽屉深处有个白色布包，用那个去泡茶吧，有拉姆和毛的两人份。」

顺著拉姆的指示打开抽屉后，发现有个白色布包收在抽屉深处。那是茶叶包，而里面装的就是──

「喂……这不是你的特制茶吗……」

「为求保险当然会留备用的，快去吧。」

那不由分说的魄力，让昴只能浑身无力地想著今天的辛劳到底是为了什么并前往餐厅，然后将水煮滚准备泡茶。仔细想想，宅邸的工作大部分都是由雷姆处理，但只有泡茶是由拉姆教导，而且拉姆对茶可说是相当讲究。

「拿去吧，大小姐我回来了，这是您点的蛇肝茶。」

「那不是蛇肝，制作的时候是用的狗肠。」

「两种都没什么差别啦。」

一反温和香气，使用的材料都是极为残忍。昴将茶倒进两人的茶杯后，便将其中一杯交给在床上撑起上半身的拉姆，然后昴也拿著杯子坐在椅子上。

杯中传来浓郁香气，此种香味实在很难想像是由毒菇粉末、毒树果实的种子、食虫花与魔兽体内结石做成的茶。

「虽然我是帮你泡好茶啦，不过一想起材料就完全不想喝了……应该说完全没有放叶子的茶叶到底是怎么回事？」

「煎过收集的材料之后，会再加进拉姆喜欢的茶叶调味。分类还算是茶类，别担心。」

如此说完后，拉姆毫不犹豫地将茶喝进口中，不得已昴也只好照做。

舌尖上传来热度与香味并从鼻腔溢出，浓郁的香味可说是相当容易入口，实在很难想像里面混有狗肠与各式各样的毒药。

「与其说是茶叶好，倒不如说是我的泡茶功力越来越强了吧？」

「别说傻话了，泡的方式实在是糟糕透顶。不只是味道变差不少，管理滚水温度的方式也是杂乱无章，或许该说倒茶的姿势完全不够到家。」

昴的自满被辛辣评语瞬间击溃，让昴只能面露尴尬地持续喝著茶。虽然很好入喉，但他那如孩童般的味蕾还是无法喜欢茶。

「唉……好想喝可乐喔，都没办法做些类似汽水的饮料吗……」

「没听说这种饮品呢，只要知道作法请雷姆做不就好了？」

「那和美乃滋一样不太确定找不找得到材料。不对，应该说比美乃滋更麻烦。」

为了重现遥远故乡回忆中的美乃滋味道，昴可说是历经艰辛，不只是需要新鲜鸡蛋、优良油类、醋、调味用的胡椒盐，还有不断尝试的毅力。

经过雷姆与拉姆反覆尝试后总算成功做出美乃滋，目前正收藏在罗兹瓦尔宅邸的厨房。对喜好美乃滋的昴而言，这可说是将美乃滋带进异世界的创举也不为过。

「不过我只是个单纯的美乃滋狂，想在异世界靠知识开无双还是遥不可及的梦想。」

「我只觉得你又在瞎扯了，不过能够感觉到毛对自己的愿望完全派不上用场。」

「我对自己的愿望毫无用处听起来还真传神，不过也没说错就是了。」

昴对拉姆的指摘苦笑以对。确实如她所说，这或许听来会让人颇为焦躁。

拉姆则是对昴的态度眯起眼睛，然后再度喝了一口自己的茶润润舌头与嘴唇。

「虽然我不清楚毛故乡的味道，但不知道茶的味道真是人生的大损失。」

「也不算不知道啦，是只有茶叶的味道。」

「没办法享受茶叶真是完完全全损失掉人生了。」

「茶是能代表整个人生喔！？」

在昴惊讶地发出叹息声之后，拉姆则是以淡红色的眼眸侧眼瞥著昴说著「没错」并且继续说道：

「看毛实在是太可怜了……你就用拉姆泡的茶好好学习吧。」

「────」

宣布自己要亲手泡茶后，拉姆静静地将杯子送往嘴边，而她的话语让昴莫名地想缓颊一笑。

昴不太清楚原因，或许该说今天还没有听到她的道歉。

不过他总觉得今天这样就可以了，因为这种距离感才是最舒服的。

这种麻烦的距离感既没有吵架争论、也没有赔罪和好或是做出类似的约定。

只要是这种关系，昴认为自己能够喝著不甚喜爱的茶期待著下次机会。

──而昴就在飘散的茶香中如此想著并度过了这天。

** 『OPERATION•KOKKURI』

1

大厅笼罩著一股紧张气氛，每个人都是屏气凝神地看著眼前的状况。

有三人正围绕著房间中央的圆桌互相对看──分别是额头流著汗水的昴、将白皙眉头皱起的碧翠丝、以及频频抖动竖起耳朵的帕克。

三人皆带著认真神情，在一旁观看状况的爱蜜莉雅与雷姆也流露出不安困惑神色，但昴目前并没有余力替她们排解担忧。

「碧翠子，你的脸色很难看喔。这么用力连鬼都会被你吓跑喔。」

「你还真敢说，到底是谁在用力？贝蒂根本没有半点理由需要生气，反而是你的鼻孔都胀起来啰。」

「哎呀，你们两个都冷静点啦，只是个游戏不要这么生气嘛。」

面对昴先发制人的挑衅，碧翠丝带著与稚嫩脸庞毫不搭调的粗鲁笑容如此回应，只有帕克是摸著胡须对互相对峙的两人一如往常地打圆场。

「哥哥说的一点都没错……不过就算是游戏，这也是一场对决，绝对不能输给区区人类。」

「真是的，贝蒂还真是爱逞强呢。昴，怎么样？你要不要展现成熟气度让她一次……」

「帕克。」

帕克以第三者的立场试图安抚两人，但昴突然打断它的话，并以严肃表情看著歪头不解的帕克继续说道：

「──如果你要说让步的话，你先把尾巴的力道放松吧。」

「────」

「做不到就表示你的立场和我们两个一样。没错吧？」

「昴也真是的，真让人头痛呢……」

对于昴低声说出的问题，帕克挽起短短双手叹了一口气。接著，这只呈现小猫姿态的精灵以圆润眼眸紧紧盯著昴。

「──看来我也得认真对付你们才行了。」

一股充满压迫感的风吹过身边，让昴差点仰起身体。但他还是拚命忍耐著风，以大胆笑容看著两名敌人。

「为什么会变成这样……」

在充满决心的气氛中，望著三人的爱蜜莉雅则是无奈地如此喃喃说著。

爱蜜莉雅将手抵在胸前，那紫蓝色的眼眸充满担忧，雷姆则是从身旁将手搭在爱蜜莉雅的细肩上，朝回过头的爱蜜莉雅摇了摇头。

「已经没办法阻止他们了，我们只能在这边静静看著他们。」

「为什么会这样……明明大家直到刚才为止都还是那么开心的……」

「因为他们都有不肯相让的坚持……」

对于发出悲叹的爱蜜莉雅，雷姆只能轻轻吐出一口气如此回答。这道声音让爱蜜莉雅瞪大双眼，雷姆则是望著三人点了点头。

「雷姆认为昴他们一定是有不能退让的坚持，所以有时候必须像那个样子产生冲突……应该是这个样子吧？」

「这就是他们三个会这样争执的理由吗？」

「雷姆是这么认为的。」

如此说完后，雷姆便带著认真神情注视著桌边的三人，而雷姆的模样也让爱蜜莉雅如祈祷般阖起双手并闭起眼睛。

只希望三人能够在不受伤的情况下解决这件事。

至于是向谁祈祷，说到现场能够祈祷的对象就只有──

「──求求您，钱仙大人。」

爱蜜莉雅呼唤著这个既遥远且不耳熟的精灵名称，静静地持续祈祷。

三人围绕面对面的圆桌桌面上有张白纸，纸上写著许多文字与数字，还有一枚硬币放在纸上。

三人将手指与尾巴放在硬币上，持续互相瞪著彼此。

还带著甚至连降临的神明都会感到困惑的认真神情与愿望──

──而事情的开端得追溯到这天的早餐时间。

2

「话说回来，你们这边对幽灵是怎么看的？」

昴突然对用过早餐的餐桌成员提出这个疑问。

宅邸的所有成员皆到齐，齐聚一堂谈话的用餐时间可说是过得相当有意义，像先前给雷姆整天休假的提议通常都是在这个时间提出来的。

今天也没有例外，昴提出的这个小小疑问吸引了众人的目光。

「雷姆雷姆，毛又开始说话了。」

「姊姊姊姊，这才是昴的特色。」

「什么特色，肯定只是会给人困扰的麻烦事。」

对于这段已经是耳熟能详的对话，碧翠丝则是跟在两姊妹后面发出叹息。

「看来你又～～想到什么有趣的玩意啰。」

一反女性们的反应，坐在上座的人似乎很愉快地拍了拍手。

那个人一脸小丑妆搭配奇特服装，再加上奇特发言与古怪个性，他就是万事皆带有与众不同感性的怪人罗兹瓦尔•L•梅札斯。

「每天昴都会带来新鲜话题，所以根本不会无聊呢。没有变化的日子会阻碍成长，我也从他身上学到停滞是最不应该的罪过。」

「是没那么夸张啦，不过以后也好好期待我的大幅度成长吧。」

两人互相说著不知该说是挖苦还是真心话的对话后，昴环视著餐厅内的成员开口说道：

「回到一开始的话题，我想问问关于幽灵的事。说实话我是不太相信，所以对夏天的灵异节目都是转台居多。」

能够断言的是，昴并不是会害怕灵异现象的人。

昴的个性出乎意料地注重现实，对于灵异现象一类总是采取否定态度。他认为没有实际体验过绝对不会相信，可说是非常符合时下年轻人的思考模式。

「因为被召唤到异世界，所以我相信有异世界。还有因为小时候在脏河旁边看过有个深绿色皮肤的大叔在洗盘子，所以我也相信有河童，那个绝对是河童没错。」

「呃……那个河童是什么？我不太懂那是什么意思……不对，应该说昴说的幽灵到底是什么？」

从小时候就没有人肯相信昴目睹河童的经验谈，在异世界果然也是无疾而终。

昴不禁失望地垂下肩膀，隔壁座位的爱蜜莉雅则是对昴投以不解神情，她将手指抵在自己的脸颊并可爱地微微歪著头。

「我从来没听过幽灵……是某种甜点吗？」

「想吃饭后甜点的意图实在太明显啦。不过你没听过幽灵吗？真的假的，这里没有灵魂之类的概念吗？」

「幽灵、河童、莲藕……又是只有昴才知道的字吗？」

「先姑且不说前面两个，最后一个肯定在便当看过。」

爱蜜莉雅对这个不熟悉的单词一脸困惑，由她的模样判断似乎真的是不知道，于是昴转头看向雷姆。

「雷姆知道幽灵吗？就是身体呈现半透明，然后穿著白色衣服与戴著三角巾在空中飞的东西。」

「不，很可惜雷姆没有看过……要是看到这种人还满可怕的。」

「我与雷姆有同感。在空中飞的怪人？哼，要是还没睡醒可不要怪我打你，毛。」

「我最近是有看过罗兹瓦尔在空中飞，这点你怎么说？」

「就是凡人无法做到才值得尊敬，毛也要记得怀著敬畏之意。」

对于拉姆毫不羞愧地将主人视为例外，昴只能一脸无奈地看著身为话题主角的罗兹瓦尔，而当事人则是对昴的视线耸了耸肩。

「用那么期待的眼神看著我也是没用的喔。好吧，下次我抱著你一起在空中飞，这样可以吗？」

「你根本没搞懂嘛，我的眼神像是表达这种意思吗！？」

「我是开玩笑的啦。而且说到幽灵或灵魂……这些在露格尼卡都是不常听到。就我所知，那好像是在卡拉拉基城邦之类的地方才会用的字喔。我也不太清楚详细情况，只是感觉好像听过很多次而已喔。」

「这样啊，原来是卡拉拉基的话。话说昴好像对奇怪的事很有研究，既然如此，这么瞭解卡拉拉基的事就不算奇怪了。」

对于罗兹瓦尔表示听过，爱蜜莉雅则是带著能够接受的表情点了点头。

虽然爱蜜莉雅的信赖很令人高兴，但相反地，她那似乎有些奇怪的接受态度令昴颇有疙瘩。但姑且不论这件事，昴对周遭缺乏反应的模样不禁狐疑地歪著头。

在原本的世界中，先不说相不相信幽灵，至少幽灵的概念算是众所皆知，祖灵之类的思考是从很古老以前便根深蒂固的概念。

死者与生者、牵绊与灵魂──感觉已经是与这类生死概念密不可分了。

「啊……该不会是有精灵的关系吧？仔细想想在晚上庭院见到的微精灵光芒也满像是幽灵的。」

「──？精灵就是幽灵吗？精灵不就是精灵吗？」

「不不，爱蜜莉雅大人。昴说的幽灵或灵魂应该是说『幻影』之类的事喔。」

「────」

瞬间，昴感觉到现场气氛彷佛发出冻结的声响。

罗兹瓦尔的发言让爱蜜莉雅带著微笑僵在原地，但浑身僵硬的人不只是她，不仅是雷姆与拉姆，就连摆出一副事不关己表情的碧翠丝也是一样。

她们的反应让昴瞪圆双眼，于是他直接朝罗兹瓦尔提出疑问。

「呃……那个幻影是什么？」

「简单说，就是死去的生命会将思念与遗憾留在生者的世界，并没有回到欧德拉格纳而留在常世中……大概就是这样吧。」

「嗯，那完全就是幽灵了。原来如此，在这里叫做幻影啊。」

罗兹瓦尔的说明完全符合，让昴满意地松了一口气。

但相较于自顾自理解的两名男性，女性们皆显得坐立难安。尤其是爱蜜莉雅面露苍白，她用发著抖的细细手指轻轻摸著昴的肩膀问道：

「昴、昴说的幽灵就是幻影吗……？」

「好像是，不过多亏说明才让我知道。虽然那也不是什么很重要的事就是了。」

「既然不重要为什么要提到幻影呢？真是太奇怪了，肯定是有什么原因……我知道了，原来是昴在宅邸看到幻影了吧？所以才会突然在意起幻影的事吧？讨厌，为什么要把那个字说出来呢？要是没发现就能在不知情的情况下生活了。昴好坏，真是个大笨蛋。昴真的好坏好坏，一定是因为自己怕幻影才会想拖我们下水吧──！」

「爱蜜莉雅酱的被害妄想还真夸张！！」

爱蜜莉雅越说越快，无法控制自己的感情用力摇著昴的肩膀。

昴被她的气势吓到，只能勉强对她投以温和笑容。

「没事啦！你放心！就算我要把人连累进来，爱蜜莉雅酱一定是最后，一开始的祭品绝对是碧翠子！」

「不懂这时候为什么会扯到贝蒂呢！」

「真的？真的是这样吗？一开始会找碧翠丝吗？」

「你是在趁乱胡说八道什么啊！你们两个是想被贝蒂揍扁吗！？」

「说得没错，雷姆也不能接受。既然昴要找也得先找雷姆，而不是先找碧翠丝大人！」

「为什么贝蒂得受到这种侮辱才行！真是气死我啦！」

爱蜜莉雅满头混乱地说出不可能出现的选择、总之吵到不行的碧翠丝、再加上雷姆还跳出来毛遂自荐，让这场谈话可说是热闹非凡。

在此种无法控制混乱的状况中，爱蜜莉雅则是泪眼汪汪地盯著昴。

「该不会昴很熟悉幻影吧？例如知道很多很恐怖的故事之类，就像星星一样多。」

「没那么夸张啦，我顶多只知道打破盘子留下遗憾的盘子店阿菊、被丈夫背叛含恨而终的阿岩、耳朵忘记抄写经书被切掉耳朵的无耳芳一等等……」

「啊哇哇～～啊哇哇哇～～～」

「我说昴啊，爱蜜莉雅大人已经快昏倒就别再说啰。」

爱蜜莉雅害怕的模样实在太过可爱，让昴忍不住越讲越起劲。被罗兹瓦尔如此提醒后，昴便带著苦笑，温柔地拍了拍爱蜜莉雅的肩膀。

「我是开玩笑的啦，我在这间宅邸没有看过幻影，我的人生只有碰过一次不可思议的体验……不过和幻影没有关系就是了。」

「可、可是昴……你刚才还有说什么河童或莲藕的……」

「河童是住在河边的不健康肤色大叔，莲藕是蔬菜喔。」

昴对自己的儿时回忆表示道歉，现在当然是爱蜜莉雅重要多了。

努力安抚总算有了成果，爱蜜莉雅的慌张情绪总算逐渐恢复平静。结果勉强冷静下来的爱蜜莉雅红著脸说道：

「那个……其实是昴稍微会错意了，我一点都不怕幻影，只是有一点点不太喜欢而已。」

「比一点点还要再严重一点？」

「比一点点还要再少一点！真是的！昴真是个爱捉弄人的笨蛋！」

虽然爱蜜莉雅气得鼓起脸颊，不过她的发言当然没有说服力，昴只好安抚著仍怒气未消的爱蜜莉雅并看向雷姆等人。

「话说你们两个的表情从刚才也很僵硬，该不会也是？」

「什么该不会，没有主词实在很难分辨呢。是毛自己不会问问题才浪费掉机会的，这个话题已经结束了。」

「这么明显的反应只会让人知道你不喜欢这个话题啦！」

口气比平常辛辣三成的拉姆对昴的追究啧了一声，雷姆则是悄悄地走到前方试图保护姊姊般朝昴摇了摇头。

「昴，不是这样的。姊姊不是害怕幻影，只是面对怎么攻击都无法击中的对手会很头痛而已……雷姆也是一样。」

「是交战拿手度的问题吗！？应该没必要以能否打倒为前提吧！？」

「毕竟保护各位努力奋战也是雷姆与姊姊的责任。不会有事的，要是幻影出现，即使赌上性命雷姆也会保护昴的。」

「只是举个例子，话题怎么变成这个样子？」

昴原本只是想轻松地闲聊几句，结果突然变成颇为沉重并必须赌上性命的话题。与观念上感到恐惧的爱蜜莉雅不同，雷姆等人对幻影害怕的感觉一点都不可爱。

「那碧翠子从刚才就带著苦涩表情也是害怕的关系吧？晚上敢自己去上厕所吗？」

「别再把贝蒂当成是乳臭未干的丫头了，应该说贝蒂怎么可能会怕那种暧昧模糊的东西呢。」

「那你为什么要这么生气？是牙齿卡了什么东西吗？」

「别找些奇怪藉口来惹贝蒂生气！……贝蒂会讨厌幻影，是因为那会玷污真正应该尊敬的象征。」

「真正应该尊敬的……呃，原来是这么回事。」

知道碧翠丝会如此烦燥的原因让昴点了点头。

「果然是因为精灵与幽灵的气氛很像，这样就能理解你会这么火大了。」

「幻影就连是否真正存在都不知道，却会贬低全体精灵的格调真是太让贝蒂生气了。」

碧翠丝露出自尊心受伤的神情并不悦地挽起双手。

昴先前也曾经想过，感觉有很多会把精灵与幻影认错的例子。或许该说既然有精灵也会有幽灵，不知道是否只有昴是如此认为的。

「──！那帕克也是幻影吗！？讨厌，亏我还这么相信它！」

「有人叫我就立刻出现喵喵喵喵！……咦？莉雅你怎么了？是谁害你露出那么难过的表情！我会替你骂骂他！」

「都是因为帕克！」

「可恶～～我这个笨蛋笨蛋！这样可以吗？」

爱蜜莉雅又再度开始慌张，与实体化的帕克开始演著搞笑短剧。

就连能独当一面的精灵使者爱蜜莉雅都是这样了，在一般民众之间到底有多少人能够分辨精灵与幻影的差异？不过也有可能是爱蜜莉雅极度胆小就是了。

「不过，没想到大家居然都对幻影这么棘手，虽然棘手的定义有点不太一样。」

「你说的幽灵和我们所知的幻影概念可能不太相同，至少我们印象中的幻影对生者并不友好。有在战场蠢动的尸体或是诅咒生者的邪念……像这样的实例非常多喔。」

「有活尸和诅咒啊……在这个有魔法的世界观怎么听都不像是开玩笑。」

实际上昴已经体验过关于咒术的事，罗兹瓦尔的例子让他不禁开始发抖，于是昴再度环视著面露不安的女性们。

十几分钟前的和乐早餐气氛已经消失无踪，都是因为昴轻率地提出关于幻影的话题，而让和乐气氛顿时烟消云散。

要是直接宣布解散感觉会留下遗憾，于是昴决定──

「──好！我有个提议！」

昴踢开椅子站起身并用手指著天花板，正当他的举动让众人皆瞪大双眼，昴则是将伸长的手腕转了几圈。

「我想大家可能有点误会了，我不是想吓大家才提到幻影的事，这点麻烦大家先搞清楚。」

「那刚才说的洗盘子阿菊、阿岩还有莲藕是……？」

「那些还有蔬菜的事麻烦都忘记吧，那些都是误会！只是假的故事啦！」

听到是假故事，让爱蜜莉雅顿时露出松了一口气的表情。虽然昴不知道这样究竟是好还是不好，但总之还是要善加利用她准备听话的态度。

「总而言之那只是假的故事……我不想只让大家感觉不舒服就让话题结束，应该说这样会让我变成单纯的讨人厌家伙！」

「这个评语会不会来得太晚了？这已经是幻影之类的话题无法挽回的事了。」

「我要把碧翠子充满偏见的认知完全洗刷掉……用我的降灵术！」

「降灵术？」

碧翠丝彷佛嘲笑般竖起拇指，爱蜜莉雅则是对高声宣言的昴歪著头表示不解。面对爱蜜莉雅无法理解这个单字的模样，昴则是咧嘴一笑。

「没错，就是降灵术！在我老家是写成降下灵魂！灵就是幽灵的灵！也就是说，降灵术是把幽灵叫出来的仪式！」

「──！？」

昴这个突如其来的提议让所有人皆脸色大变。

「能叫出幻影吗！？」

「爱蜜莉雅酱，任何事都有抄捷径或秘藏的方法。要不要当作被骗一次来挑战看看？」

「感觉我会被骗到最后呢？」

「这样真的没问题吗？不会很危险吗？」

雷姆往前逼近昴，代替困惑的爱蜜莉雅如此问道。

「幻影是邪恶的象征，这是一般民众的想法。虽然我也不想怀疑昴，不过要是有个万一……」

「哎呀，先等等啦，幻影与幽灵也不一定全都是恐怖的东西嘛。只要用降灵术叫出来看看，知道底细就能让恐惧感减半啦。」

「就算减半还是会很恐怖的！」

「雷姆，其实你也很害怕吧？」

虽然没有写在脸上，但其实说不定雷姆也挺害怕的。

雷姆靠到发抖的爱蜜莉雅身旁并扶著她的肩膀，但看起来像是藉著安慰填补自己的惧怕。

「呵呵，你偶尔也会说出有意义的事嘛。」

「没想到会在这种时候出现援军。碧翠子，你也赞成我说的吗？」

昴对出乎意料的赞成票感到相当惊讶，碧翠丝则是挽著双手不屑地哼了一声。

「趁著这次机会，贝蒂也有很多事想对幻影好好发泄一顿。如果你能用那个什么降灵术叫出幻影，那就叫出来让贝蒂好好教训一下吧。」

碧翠丝带著充满战意的神情，似乎想积极地挑战降灵术。总之不论如何，见到现场似乎没有人认真反对，最后昴将视线转向罗兹瓦尔。

现场是由罗兹瓦尔握有决定权，他对昴的视线豪迈地张开双手。

「好啊，想做就试试看吧。其实我也对能叫出幻影的降灵术很有兴趣，有机会也想看看呢。」

「就是这样才对嘛！真不愧是罗兹亲，这么好说话！」

得到好说话的主人同意后，昴得意地如此大声嚷嚷。

「既然这样就开始准备降灵术吧！没什么啦，要准备的东西没有那么难，只要有一张大白纸、羽毛笔和一枚硬币就好。」

「没想到那么便宜，真是让人怀疑。」

「简易通灵术就是以轻松为卖点，在我老家那边可是有阵子超级流行喔。」

「原来在昴的故乡都会玩弄幻影啊。没想到这么有勇气呢……」

昴对莫名佩服的爱蜜莉雅露出含糊笑容，并且省略说明详细内容，他认为说出降灵术流行的过程只会让爱蜜莉雅又再怕起来而已。

毕竟这个降灵术会稍微出现过度影响，还曾经在多数少年少女心中留下创伤，甚至还传闻过被禁止进行此种仪式。

而这个仪式在昴的故乡是如此称呼。

「那么，第一次罗兹瓦尔宅邸的『招钱仙』正式开始！」

3

──招钱仙是某段时期在日本曾经疯狂流行的某种降灵术。

由于影响力太过强烈，甚至有名到据说某些地区至今仍是明令禁止。

有人说钱仙的原文『KOKKURI』是源自于「狐狸」、「狗」、「狸猫」之类的名称，一般认为仪式只会叫出低等的动物灵魂。

虽然在昴的世代已经是过时的游戏，但仪式流程与准备的道具几乎已经是基本常识，表示这可说是如此广为人知。

「叫出来的钱仙不会说话，所以必须准备这些东西用来与钱仙沟通。」

「所以才要用纸和笔吗？是要与钱仙大人进行笔谈吗……？」

昴在桌面上摊开白纸，拿著铁球的雷姆则是战战兢兢地如此问道。

在宅邸很少会见到她如此全副武装。这也表示对雷姆而言，现在是超乎日常的备战状态，她已经准备好将叫出来的钱仙打个粉碎了。

「叫出来还揍飞对方会遭报应的……很可惜钱仙是看不到的，而且用笔的不是钱仙而是我，只要像这样写写写就对了。」

「字还真丑，能感觉到平常的课程都没有学进去。」

「大姊你很吵耶，只要看得懂就好了啦。」

如此回答因为提高戒备而说话比平时更加恶毒的拉姆后，昴不屈不挠地持续在白纸上写著字，依序地写下在这个世界等于是平假名的I文字。

「最后还要准备数字和『男』『女』的栏位，再来也不能忘记让钱仙出入的门。」

他仔细地写下0到9的数字和男女两字，最后则是准备好「是」与「否」的选择，在中间画下鸟居就准备完成了。

「爱蜜莉雅酱，借我钱吧。」

「好，不要乱花钱喔。」

「听起来像是小白脸拿钱耶。」

昴将帕克这番难听的话当成耳边风，把爱蜜莉雅递给他的硬币放在鸟居图案上，接著爱蜜莉雅与雷姆互相点了点头，三人便一同坐在座位上。

「在开始之前有几件事需要注意。首先是接下来三个人要把手放在硬币上，不过在结束之前手指都不能离开硬币，不然会有很严重的后果。」

「呃……好，我知道了。不能让手指离开硬币吧……那可以用冰冻结起来吗？」

「不是物理层面的放开手，而是精神层面的努力。还有钱仙是会替我们回答问题的幻影，有些时候会很啰唆。要是不照顺序来有可能会被骂，所以拜托要照我的指示来做。」

「会被骂……表示那个瞬间是个好机会，好像能知道昴期待雷姆做出什么样的事了。」

「我觉得你还是不懂，基本上是禁止攻击喔！？」

对于脸色苍白却带著认真神情的爱蜜莉雅，以及淡蓝色眼眸中怀著杀气的雷姆，昴不禁感到相当担忧。

但身旁能够见到碧翠丝充满敌意，还有攻击意识越来越强烈的拉姆。虽然罗兹瓦尔与帕克一如往常，但这样并没有办法成为担忧的心灵支柱。

或许该说只是玩个钱仙，应该没有需要那么认真的理由吧……

「对毫无意义的事燃起热情，男子汉的浪漫就是这样才麻烦啊……」

「别说那些傻话快点开始，快动手吧。」

被碧翠丝那揶揄的态度看扁后，昴重新打起精神并将手指伸向硬币，爱蜜莉雅与雷姆也跟在后头，三人的手指便重叠在该枚硬币上。

现场微微浮现出紧张感，仪式就在全员屏气凝神之下展开。

「──钱仙大人，钱仙大人，请快点下凡。如果在场的话请移到『是』的上面。」

昴以宛如念诵魔法般的气势说出这段固定台词。

这段话让爱蜜莉雅与雷姆加重手指力道，但硬币并没有任何变化，昴则是瞪著毫无动静的硬币并舔了舔干涩嘴唇再度说道：

「……钱仙大人，钱仙大人，请快点下凡。如果在场的话请移到『是』的上面。」

他再度说出召唤的话语，然而仍然没有任何变化。

此种结果让大厅的气氛自然地放松，参加仪式的爱蜜莉雅与雷姆也放心地松了一口气，背后还能听见扫兴的叹息声。由于先前备受期待的关系，此种结果应该会让碧翠丝相当不愉快……但就在昴如此想著的随后──

「──啊！」

爱蜜莉雅发出惊讶的叫声，雷姆哑口无言地瞪大双眼，连昴也是倒吞了一口凉气。

因为三人手指抵著的硬币正缓缓地移动到「是」的位置。

「那么，请回到鸟居的位置。」

受到两人如恳求般的视线，昴连忙回想起下一句指示。听到指示后，硬币从「是」回到鸟居的位置，让昴确定降灵术已经成功了。

与其说是幽灵作祟，但据说这是反映参加者潜意识的仪式，不过总算突破了最初的关卡，接下来就要看钱仙发挥本事了。

「很、很好……总算出现了。只要在这种状态下提出问题，钱仙都会回答大部分的问题。你们两个有什么想问的事吗？」

「先、先让昴示范给我们看看吧。」

「……是的，雷姆也觉得这样比较好。因为雷姆还没有见到幻影。」

爱蜜莉雅老实地表达恐惧，雷姆则是误以为这场仪式的目标是消灭幻影。由于两人放弃提问的权利，于是昴稍微思考过后问道：

「……钱仙大人，我想问问爱蜜莉雅酱是不是很怕幻影？」

「昴！？」

爱蜜莉雅发出责备声，但硬币早一步出现动静。硬币滑到「是」的文字上，将爱蜜莉雅显而易见的心情揭露。

「谢谢钱仙大人，请回到鸟居吧。」

昴对此种结果相当满意并发出回到定点的请求，硬币便滑回到鸟居的插图上，这就是钱仙的一连串流程。

「总之这就是钱仙的基本流程，再来只要避免失礼反覆进行对答就好……爱蜜莉雅酱，你那是什么眼神？」

「我、我一点都不怕，我觉得刚才的答案应该是错的。刚刚那一定是昴偷偷挪动手指，我不会被骗的。」

『否。』

「咿呀！？」

钱仙毫不留情地将爱蜜莉雅的可爱逞强完全粉碎，发出尖叫声的爱蜜莉雅反驳声越来越小，并且以细微声音说著「对不起……」如此道歉。

「──钱仙大人，今天的晚餐是要吃肉还是吃鱼呢？」

『肉。』

结果在旁边持续观望的雷姆，突然以惊人胆量朝著钱仙提出疑问。钱仙将硬币滑到文字栏位回答晚餐内容，雷姆道过谢后便将眼神转向昴等人。

「雷姆认为钱仙大人的回答值得相信，因为厨房的材料没有鱼，所以晚餐是吃肉类料理……而且这是只有雷姆才知道的事。」

「咦……这样不是很厉害吗？」

发现雷姆提问的意图后，爱蜜莉雅用空著的手掩著嘴表示吃惊，然后眨了眨那紫蓝色的眼眸紧紧盯著硬币。

「没想到钱仙大人这么厉害，吓了我一跳呢。」

『没有那么夸张。』

「很抱歉怀疑您，而且还这么有礼貌地与我们说话。」

『常有的事。』

「是这样吗？原来常有这种事啊……不过我觉得被误会是很令人难过的事，所以我还是得道歉才行，下次我也会注意的。」

『没关系啦。』

「钱仙是能这么轻松说话的对象吗！？」

面对反省的爱蜜莉雅，钱仙令人有种跌破眼镜的印象。

这段时间硬币仍然在纸上不停滑动，相较于温馨对话可说是颇为奇异的景象。

总之不论如何，爱蜜莉雅似乎对钱仙完全敞开心房，与先前害怕幻影的模样简直是判若两人。见到此种莫名温馨的异种文化交流，雷姆似乎也渐渐收起敌意。

「爱蜜莉雅大人，可以也让雷姆与钱仙大人说说话吗？」

「啊，对不起。钱仙大人，与雷姆说点话好吗？」

『好啊。』

「已经不是用『是』而用『好啊』回答了喔！」

在这场仪式中与其说是主宾，钱仙感觉还比较像是第四位参加者。

虽然与传闻中的印象有段差距，不过在异世界生活的钱仙都是这个样子吗？与日本钱仙的恶劣传闻实在差太多了。

「昴对雷姆每天做的餐点很满意吗？」

『感觉还不错。』

「昴对宅邸的工作有乐在其中吗？不觉得辛苦吗？」

『有种很舒服的疲劳感。』

「昴和姊姊有办法和好吗？」

『讨厌的反义词就是漠不关心。』

「那昴……」

「我说雷姆小姐，这些事不用经过钱仙，直接问我就能回答你啰。」

「不，因为直接问会让人很害羞……」

「这种形式算间接又一点都不间接啦！」

虽然不知道雷姆感到害羞的点，但钱仙也算是相当随兴，不过雷姆似乎已经满足好奇心，于是差不多也该告一个段落了。

「那么虽然有点可惜，也该请钱仙大人回去了…………钱仙大人，谢谢您大驾光临，还请您慢走。」

「谢谢您，要再来说说话喔。」

「希望您归途平安顺利。」

昴仍然拘泥于形式，爱蜜莉雅与雷姆则是夸张地送钱仙离开。当三人告别后，硬币便缓缓地滑向鸟居。接著先前笼罩整个大厅的莫名压迫感突然消失，让全员理解到钱仙已经离开现场了。

「大概就是这种感觉。怎么样？钱仙不是很可怕的幻影吧？」

「嗯，让我吓了一跳。明明看不到却真的在场，该不会是精灵……可是感觉又不太一样……」

「就我看来，现场也没有玛那干涉的现象。虽然很不可思议，不过感觉看到了降灵术的厉害之处呢。」

见到仪式结束后，先前保持沉默的罗兹瓦尔看似佩服地如此说著。被魔法的第一把交椅如此保证，让昴也对叫出钱仙与有荣焉。

「也不是精灵做的事喔。如果是精灵，我和莉雅不可能没有发现，贝蒂怎么看呢？」

「……贝蒂不承认有这种事，幻影本身就是亵渎精灵。」

「贝蒂？」

对于帕克的问题，碧翠丝以既平静却愤慨的声音如此回答。她将对这个答案瞪大双眼的帕克拋在后头，径自迈步走往圆桌的方向。

「双胞胎妹妹，把位置让给我，贝蒂要来揭穿这场骗局。」

「碧翠丝，你怎么能说这种话呢？这没有出老千喔。」

「最近没什么人会说出老千了吧……先不说这个，你是怀疑刚才的钱仙吗？那刚才的现象你怎么解释？」

「你闭嘴，还是说你怕被贝蒂拆穿真相？既然这样也不能怪贝蒂了。」

「……真让人火大。到时候可别哭丧著脸，电钻头萝莉。」

雷姆将位置让给碧翠丝，昴也再度坐回自己的位置上。见状，碧翠丝则是瞪著爱蜜莉雅说道：

「你也要和哥哥交换，站在钱仙那边的人实在不值得信任，看哥哥和贝蒂怎么华丽地揭穿这场骗局。」

「是要怎样才会怀疑是站在钱仙那边啊？而且帕克要怎么参加？」

「可以用尾巴吗？」

「呃……我知道了。好吧，用尾巴没关系。」

飞来的帕克浮在桌面上，伸出长长尾巴放在硬币上，昴与碧翠丝也做出同样动作。虽然看来有些滑稽，但三人也做好了仪式的准备。

「昴……」

「不会有事的，爱蜜莉雅酱。看我怎么保护钱仙大人……」

「嗯，我相信你。」

爱蜜莉雅将手放在胸前，以宛如祈祷的姿势朝昴点了点头。看到爱蜜莉雅的反应，昴轻轻地做了个深呼吸，然后将意识转向画在纸上的鸟居。

「……钱仙大人，钱仙大人。很抱歉一直找您过来，如果您在请移动到『是』的位置……喂喂，还真快啊。」

『叫太多次了。』

「也是啦，再怎么说都会生气吧。一回去又被叫过来肯定会生气的，真的很抱歉。」

从文章中能够感觉到极度不悦的感觉，让昴不禁卑躬屈膝地表示歉意。但相反地首度体验钱仙的两人微微地瞪大双眼。

「至少我是没有动喔。贝蒂呢？」

「……贝蒂还没有到那么不知耻的程度。好吧，就算真的在那里，看贝蒂怎么好好收拾你。」

『别让人笑掉大牙了。』

「碧翠子，被说成这样啰。」

「真是气死人了！」

总之，首战似乎是由钱仙方率先拿下。

不知是否被连续呼叫的怒气恢复平静，钱仙回答「尽量放马过来」并等待著问题。就连这段时间都是在纸上不停滑动，似乎完全没有静下来的意思。

「碧翠子，你可以问了，快去和钱仙好好打个一场吧。」

「可以告诉我怎么让你消失吗？」

「你怎么一开始就问这么没礼貌的问题啦！？能这样问的，只有明明没叫却出现在电脑上的海豚（注1： 日语版Microsoft Office求助栏位所使用的吉祥物动画。）而已啦！」

『该怎么回答呢～～』

「而且钱仙大人对碧翠子的态度超严苛的！」

对于理应是先展开攻击的碧翠丝，钱仙立刻回以迎头痛击，钱仙似乎也已经看出面红耳赤的碧翠丝拥有天生容易被玩弄的个性。

「那莉雅是怎么看我的呢？」

『很棘手的老爸。』『有时候像老妈。』

「呵呵呵，好有趣喔。那我是怎么看待莉雅的呢？」

『需要人照顾的可爱女儿。』『有时候像老妈。』

「两个人都会偶尔认为对方像老妈子吗？」

对于帕克颇具含意的笑容，爱蜜莉雅拚命地摇头否定。虽然此种亲子关系也令人摸不太懂，不过昴相当佩服钱仙的敏锐观察力。

「哼……既然这样，说说看哥哥是怎么看贝蒂的吧。」

『敬语。』

「静雨是什么意思？把贝蒂当成静雨吗……？」

『用敬语说话。』

「这家伙从刚才就只对贝蒂很严格耶！？」

不知究竟是心情差到极点，或是反而很喜欢她，感觉钱仙似乎对碧翠丝的态度特别有压力。之后也是巧妙地躲避碧翠丝的问题，让先前气焰高涨的少女可说是战意全失。

不论如何，既然能做到这种程度，碧翠丝应该也不会再怀疑钱仙的存在，就某种意义而言也算是达成目的了。既然如此也差不多该请钱仙离开──

「啊……昴，雷姆可以最后再问一个问题吗？」

「嗯？怎么了？雷姆也有想问的问题吗？」

雷姆举起手回答「是的」，让昴开始思考该怎么做。基本上能向钱仙提问的只有仪式参加者，这样钱仙不知道会不会生气。

『放马过来。』

「别说是生气，钱仙大人还超有男人味的。好吧，雷姆你问吧。」

「那么雷姆就不客气了……其实最近储藏的美乃滋好像会在晚上偷偷减少，原因究竟是为什么呢？」

就在雷姆不经意地提出这个问题的瞬间，先前钱仙寄宿并轻快地滑动的硬币突然停下动作。硬币停在鸟居图案上，在昴等人手指按压的状态下微微颤抖并毫无动静。

「────」

三人屏气凝神地互相对瞪，此种状况让爱蜜莉雅等人相当困惑。

──就这样，故事回到一开始的场景。

4

三人使出浑身解数地按著硬币，慎重地刺探著彼此的反应。

从指尖传来的冰冷感触，频频能够感觉到想朝著正确答案移动的气息，但这次并不能让硬币直接说出正确答案。

罗兹瓦尔宅邸储藏的美乃滋，是由极度喜爱美乃滋的昴在这个世界重现制作法，也是雷姆每天费尽心思做出的调味料。

虽然品质比不上原本世界，但在昴的饮食中可说是不可或缺的必需品。

而有鼠辈每个晚上都会偷吃美乃滋──老实说那个人就是昴。他偶尔会无法忍耐并潜入厨房偷吃美乃滋，但这件事当然不能说出口。

「碧翠子，你的肩膀会不会太用力了？帕克，你尾巴那团隆起的肌肉是怎么回事？」

「你才是表情那么僵硬，本来已经够难看的笑脸变得更邪恶，那个什么钱仙的肯定也是看不下去了。」

「你们两个，现在还有时间说清楚。别再说那些傻话，来说点更有建设性的事吧。例如要不要出去野餐呢？」

三人互相牵制彼此，但仍然没有放松按著硬币的力道。

昴用力压著硬币避免钱仙将真相公诸于世，但两人也是拚命妨碍著昴的动作，不然就会被当成犯人──

「啊……硬币开始……！」

在旁边观看的爱蜜莉雅发著抖注视著硬币，但硬币的速度相当缓慢，迟钝得彷佛会将下面垫的纸压破一般。而硬币正缓缓沿著「碧」「翠」「丝」的拼音移动──这当然是昴控制的动作。

在被揭穿之前先诬赖给别人，让整件事在暧昧模糊中落幕，只能这个样子了。

「喔喔？从这个样子看来犯人就是……？」

「别、别开玩笑了！你、你怎么不看仔细一点……！」

当昴一副事不关己地如此说著，反抗的碧翠丝手边突然发出鲜艳光芒。随后一阵风以少女为中心开始围绕，昴发现压在硬币上的力道越来越强烈。

「你……该不会……！」

「你们仔细看清楚！这个动作很明显就是那家伙的名字……！」

硬币如同碧翠丝所说改变轨道，并非是碧翠丝的名字，而是开始沿著昴的拼音开始移动。她肯定是为了这个使用某种魔法。

「碧、翠、昴？」

爱蜜莉雅照著拼音念出而感到相当困惑，但再这样下去会非常不妙，只要再指出最后一个拼音完成名字，就会让昴所做的坏事真相大白。

「不过就在这个时候，钱仙大人的灰色脑细胞突然灵活起来了！」

「这、这该不会是……！」

就在即将抵达昴的最后一个拼音前，昴勉强将硬币滑到别的拼音上，只要最后拼出碧翠丝三个字就算胜负揭晓了。

「碧、翠、昴、不、施？」

「钱仙大人！就这样直接抵达终点！」

「昴，我不会让你得逞的！这时候要对大意的你使出钱仙反击！」

「贝蒂也要帮哥哥的忙！两个人一起感情融洽地用出钱仙攻击！」

掌握到昴急于分出胜负的空档，帕克再度将硬币滑向「昴」的第一个拼音，碧翠丝也跟著助阵，将昴逼进被迫防御的窘境。

再这样下去会输──正当昴如此思考的瞬间。

『你们给我差不多一点。』

「──！？」

先前三人用蛮力压著的硬币突然高速旋转。不只是昴，连碧翠丝与帕克都被甩开桌旁。由三人腕力中解脱的硬币四处乱窜，指出彷佛斥责三人蔑视自己的文字。

『有个人对你们这么丑陋的举动很难过。』

「有、有人很难过……？」

『爱蜜莉雅。』

钱仙的回答让昴惊愕地回过头，只见伫立的爱蜜莉雅正以哀伤眼神看著三人，将手抵在胸前的她似乎正在祈祷。

钱仙似乎早已发现这件事，而且对互相推卸罪过的三人不忍卒睹。

『快想想』『那充满慈爱的心灵』『还有体贴他人的爱』

「钱、钱仙……你真是……」

『已经不需要我了』『接下来』『就是你们自己的故事了』

钱仙的贴心话语让昴无言以对，钱仙留下最后这些话并前往鸟居，还来不及阻止便能感觉到气氛突然一变。

「……钱仙大人好像回去了呢。」

在失去存在感的气氛中，雷姆说出这个每个人都理解到的事实。她摸著留在桌面上的纸，将手放在鸟居与硬币上。

「很抱歉，是雷姆说出不必要的事让钱仙大人生气了。」

「不、不是雷姆的错啦。应该说是我太随便提议要找钱仙出来，好像也给钱仙大人添麻烦了。」

虽然昴对太过亲民的钱仙吓了一跳，不过这也让他涌现出同等罪恶感。

因此，反省的方法就只有一个。

「雷姆，关于美乃滋的事……」

「是的，结果到后来还是无法得知犯人是谁呢……」

「不是啦……其实犯人是……」

被雷姆率真的眼眸正面看著，昴当场低下头。接著──

「我是犯人。」「是我做的喔。」「是贝蒂稍微动了歪脑筋。」

「咦？」

三人异口同声的自白让雷姆瞪大双眼，但最惊讶的当然就是昴等人，三人皆面面相觑且哑口无言地张大嘴巴。

见到此种模样，爱蜜莉雅最后则是拿起硬币。

「钱仙大人，钱仙大人，您该不会全部都知道了吧？」

接著，她带著淡淡微笑朝默默无语的硬币如此问道。

5

「……真是一场闹剧呢，罗兹瓦尔大人。」

离开美乃滋窃犯们道歉的大厅后，拉姆朝著走在前方的罗兹瓦尔如此说道，罗兹瓦尔则是抖著肩膀笑著回答：

「算是满有趣的把戏喔。昴真是个有趣的人，让生活不会无趣真是太好啰。」

「要是让毛太过得意，他又会做出很夸张的事。」

「那也是挺有趣的，如果我这么说，拉姆会不会生气呢？」

对于主人相当愉快的话语，拉姆没有反驳并微微叹了一口气。

拉姆原本就不打算反对罗兹瓦尔的意见，对主人的愿望尽全力奉献就是她的忠爱。因此──

「那枚硬币您是怎么挪动的呢？」

「那是应用风与地的魔法。先用风把玛那稀释掩饰，再用局部震动引诱硬币。碧翠丝和大精灵大人看来是发现了还刻意装成不知道呢。」

罗兹瓦尔那毫无反省之意的回答，让拉姆浮现出身为共犯的那两人。小猫看来似乎相当高兴，而少女则是满脸无奈地陪著这场闹剧。

「不过话虽如此，最后那段对话似乎有些奇怪，没想到碧翠丝小姐与大精灵大人会互相自掘坟墓呢。」

「因为他们没料想到会有这种结果，毕竟连我都不知道最后发生了什么事喔。」

「咦？」

「意思是不是整场游戏都由我操控，而且那时候没有玛那干涉，不知道昴到底叫出了甚么东西呢。」

罗兹瓦尔朝著被吓傻的拉姆眨了眨眼。不知道这究竟是他特有的开玩笑方式，还是真的对不可思议现象乐在其中，甚至连拉姆都无法看穿。

如果一切都只是罗兹瓦尔的夸饰就好了──但万一如果不是这样的话……

「今后在宅邸举行仪式……嗯，还是禁止他们玩那个钱仙游戏好了。」

拉姆深深地点了点头，并且清楚地如此下定决心。

就这样，流入异世界的「招钱仙」就像原先一样被视为禁忌，至少在罗兹瓦尔宅邸没有再度举行过这个仪式。

然而取而代之地，开始玩著呼唤「天使下凡」又是另一个故事了。

** 『图书馆员碧翠丝不甘愿的约定』

1

屏著气息打开门后，便开始确认走廊的左右方向。

少女竖起耳朵查探声响，附近并没有感觉到人的气息。于是少女说著「好」并轻轻握起拳头，踩著红色地毯开始向前奔跑。

虽然柔软地毯吸收脚步声，但不至于连少女的担忧一并消除。不只是脚步声，少女甚至连自己的呼吸都感觉是碍事的敌人。

遥远走廊的客房门扉并排直达转角，在长长通道各处能够见到摆设的装饰品。她对所有物体怀著戒心，正当她寻找某处躲藏时──

「──哇！」

「──唔！」

当她游移著目光寻找躲藏处时，有名少年的身影突然从正面壶的阴影处跳了出来。他将双手张在头部侧边并大大张开嘴巴，那是个垂著鼻涕的孩童。

少女随即咬紧牙根，将差点砸过去的玛那力量收了回去。差点就把眼前的少年打了出去，少女对自己的自制力与少年的好运不禁松了一口气。

接著……

「哼喝！」

「呜呀！」

取消使用玛那的手掌，朝摆鬼脸的少年侧脸甩了下去。见到少年发出短促惨叫声跌倒在地，少女便用手指拉著自己的长卷发。

「哼！这是吓到贝蒂的报应！别开玩笑了！」

「啊～～！找到了！」

「真的耶！在这里！榴卡被打倒了！」

「就算他被打倒，还有第二和第三个榴卡！」

「你输定了啦。」

在对方发出胜利宣言的瞬间，从走廊另一头出现的特遣队吵吵闹闹地赶了过来。这些声音让少女发出咋舌声并摸著附近的门扉，正当她反射地准备「穿越世界」时……

「──这点程度贝蒂不能就这样认输呢。」

少女抽回手，摇了摇头并跑往走廊的反方向。途中还踩过被甩巴掌少年的腹部，让他发出「咿啊」的丢脸叫声才转身离开。

「快上！把她抓住～～！」「冲啊！把她干掉！」「快冲！把她衣服脱掉～～！」

一边听著背后传来被踩踏少年同伴的声音，少女一边在脑中回想著宅邸的地图，接著朝追来的孩童们皱起眉头。

「绝对不会让你们得逞的。」

声音中怀有强烈决心，这位抓著裙襬的少女────碧翠丝则是全力奔驰。

2

「我说碧翠子啊，你一直窝在这里都不会搞坏身体吗？」

坐在地上的昴环视著塞满大量书本的书柜，并且提出这个疑问。

这个房间笼罩著一股古老庄严的气氛。

这个宽敞房间没有窗户，光源只有室内各处摆放的魔法灯，放在玻璃容器中的白色矿石发出灿烂光芒完成照明任务。

但光芒并无法照耀到摆满书柜房间的所有位置。

「一直窝在昏暗房间看书会让眼睛变差，这个房间没有窗户也不能通风，待在空气不好的房间也对肺部不好喔。」

「真是个唠唠叨叨的家伙呢，贝蒂想在哪里做什么都是贝蒂的自由……首先，禁书库的空气会用玛那自我清净，所以空气是很干净的。」

「真的假的，玛那会不会太厉害了。难怪这个房间待起来会这么舒服……不对，我之前就觉得很奇怪，明明这个房间只有碧翠子吐出的二氧化碳，不知道为什么会这么舒服。」

「虽然听不太懂，不过贝蒂至少知道这是很恶心的话！」

无法按捺此种毫无意义的废话，坐在梯凳上的碧翠丝不禁如此吼道。

少女红著脸，指著大大方方地待在房间的昴。

「你怎么每天每天都要来闹贝蒂啦！这里不是你用来打发时间的地方，是神圣不可侵犯的『禁书库』！」

「说是禁书库啦，能这么简单闯进来根本没有说服力吧。」

「贝蒂根本不希望你进来，是你自己随便乱闯进来的吧！」

对于蛮横闯进房间的昴，碧翠丝一如往常地发著飙。她直接跳下梯凳，在盘腿坐在地面的昴面前以唯我独尊的模样抬起下颚。

她那在头部侧面的奢华长卷发，宛如弹簧般弹跳的模样可说是相当引人注目。

「不管怎么用『机遇门』都能一副理所当然地找出来……能这么随意闯进禁书库的人，你是第一个。」

「我跳进来了，我又跳出去啰。」

「你是听到贝蒂哪句话觉得很好玩的！仔细听人说话啊！」

「唔喔！」

碧翠丝气得将看完的书丢了过来，昴赶紧将书接住，碧翠丝仍然红著脸以斗大眼眸看著昴。她的模样就像是不停吠叫的小狗，让昴微微地露出笑容。

「有什么好笑的……真是个不管做什么事都会让人生气的家伙。」

「抱歉抱歉，不过看完的书别随便乱丢，记得好好收回书柜啦。嫌麻烦整理，就会像这样整个地板都被书堆满了。」

「要对这间禁书库管理员贝蒂说教关于书的事，你还早了一百年呢。」

「我怎么总是看到那个管理员把书甩过来啊……」

虽然有身为图书管理员的自觉与尊严，但对书籍的管理似乎不太和善。

接过昴递出的书本，碧翠丝将书塞进身旁的书柜中。书柜排放的书背与书名也是杂乱无章，完全是随随便便处理工作。

「喂，你身为图书管理员的尊严摆到哪去了。这样随便收拾，想看续集的时候可是会后悔的，我以前就曾经有过双胞胎变成独自一个的经验喔。」

「虽然听起来是个颇有现实感的忠告，不过还是不需要你多管闲事，禁书库是无法用你常识衡量的先进场所。」

「是哪里先进啦？」

「只要把书放回书柜，就会自动回到事前规定的位置。」

「禁书库有够先进的！应该说超可怕耶！」

虽然对一副获胜表情的碧翠丝有些抱歉，但昴的感想是诡异更胜佩服，于是昴转头看向碧翠丝将书塞进的书柜。

「咦？真的假的？会自动把书放回去吗？虽然真的很方便，不过现场亲眼看到超诡异的。应该说这样就不需要管理员了吧？你是为了什么待在这的？」

「你是不会说除了贬低贝蒂以外的话吗……」

虽然只有这次是撇除玩笑的疑问，但碧翠丝似乎还是当成一如往常的耍嘴皮子。少女直接穿过昴身旁，从附近的书柜抽出书本。禁书库的书很多是既厚重且大本，她的模样看起来可说是相当危险。

即使如此，正当昴不经意地想伸出手帮忙时──

「不用你多管闲事。」

这个不可爱的反应让昴只能露出苦笑。

「好啦……那我差不多也该走了。」

碧翠丝坐在梯凳上，在大腿上打开书本进入读书模式。

只要进入此种状态，碧翠丝的反应就会突然变少，昴至少也知道看书时不应该打扰的礼仪，因此正好是撤退的好时机。

对于前往禁书库出口的昴，碧翠丝不发一语，昴突然回过头对一贯保持冷淡态度的少女问道：

「话说回来，碧翠子你有听说吗？从明天开始两天，罗兹瓦尔和拉姆会离开宅邸出门办事。」

「……我已经听说了，不过这与贝蒂没有任何关系吧。」

即使想闲聊几句，碧翠丝的反应仍然是极为冷淡。昴认为这种态度实在不太可取，于是歪著头继续问道：

「应该不算是没有任何关系吧，毕竟是一家之主与……呃，我想不到比较好形容他们之间关系的词，总之至少得去送行一下吧？罗兹亲说不定会高兴得跳起来喔。」

「贝蒂实在无法想像罗兹瓦尔跳起来的模样，而且已经说过很多次了，这与贝蒂没有任何关系──尤其是说什么出门小心之类的话。」

碧翠丝将视线落到书本上，然后不发一语。

禁书库顿时被沉默支配，昴错过了离开房间的时机，翻动书页的声响也停了下来，让室内充满著尴尬的气氛。

昴回想著自己说过的话，思考究竟该怎么接话。

他认为自己说出的话并没有想得这么深，不过他自认确实有些多管碧翠丝与罗兹瓦尔之间的关系。但即使如此──

『昴，出门要小心喔。』

「────」

脑中浮现的声音突然让昴有种揪紧心脏的感觉。

他尽可能地不让自己思考或回想，但这些声音仍然在头盖骨不停回荡。

在没有特别意识到离别时，由背后传来这道温柔体贴的声音。对于这道一如往常的声音，昴思考著自己究竟会怎么回答。

「──你明天还是去露个脸送行吧。」

「……唉。」

对于昴打破沉默的呢喃声，原先将视线落在书本上的碧翠丝叹了一口气。

少女没有抬高脸，只是上挑起目光瞪著昴。

「这已经是说第三次了，与贝蒂是毫无关系的事。」

「又不会让你少块肉，反正你也没有什么事只是窝在房间里面。既然这样，稍微露个脸也……」

「真是有够啰嗦的。」

面对不肯退让的昴，碧翠丝斩钉截铁地如此拒绝。

「原本贝蒂就是有待在这里的理由，不是只用『反正』就能妥协。如果你还是很坚持，那就用蛮力把贝蒂拖出去吧。」

「────」

「不过说实话，你在这个房间是没有方法赢过贝蒂的。」

碧翠丝的话语虽宁静，却能感觉到不可撼动的顽固情感。

那是平常对昴生气回嘴时没有展现出的深沉愤怒，一苏醒就有可能成为大火，发觉此事便让昴举白旗投降。

「好吧……是我不应该一直啰嗦的，晚安。」

老实地选择退让后，碧翠丝释放出的压力也随之消失。当昴直接离开房间，少女没有说出任何话。

「啧，真是个倔强的家伙。」

关起门扉的瞬间，能够莫名感觉到空间扭曲的感觉。昴试著再打开一次门，先前连接禁书库的门扉已经回到了连接空旷客房的任务。

碧翠丝的「机遇门」是能让禁书库连接宅邸内随意门扉的空间魔法，由于门扉选择权在碧翠丝身上，因此与她接触可说是极为困难。但不知为何，此种特性只对昴的直觉毫不管用。

「不过话说回来，碧翠子刚才那种态度到底是……」

「──咦？昴，你在这里做什么？」

正当最后那段话的不协调感让昴皱起眉头时，突然有道声音从旁传来，回过头便见到将银发绑起的爱蜜莉雅正好从楼梯间平台走了过来。

她走向杵在走廊上的昴，微微一笑歪著头如此问道。

「这里是往我的房间喔？刚才不是才打过睡前的招呼吗？」

「呃，我只是刚好路过而已。爱蜜莉雅酱，你刚洗完澡吗？好可爱喔。」

「好好。」

面对昴没头没脑的赞美，爱蜜莉雅以习惯的态度如此敷衍回应。

实际上带著苦笑的爱蜜莉雅脸颊与颈项发烫地泛著红润，长长银发也是显得相当湿润。与意中少女住在同个屋檐下，能见到此种模样可说是男人的无比幸福。

「昴，你看起来一副色眯眯的样子。怎么了吗？我有什么奇怪的地方吗？」

「不不，奇怪的人应该是我。爱蜜莉雅酱楚楚动人的模样总是让我疯狂……呃，又被左耳进右耳出了。不是啦，在这里碰面正好。」

「──？」

昴将玩笑话与耍嘴皮子撇在一边，将脸靠向带著满腹狐疑神情的爱蜜莉雅。有股很香的味道，但这并不是主要重点。

「虽然能像这样和爱蜜莉雅酱站著说话也很吸引人，不过我有件事想拜托。这种时间还能借帕克吗？」

「借帕克？」

手指抵著脸颊，爱蜜莉雅对突如其来的提议不禁瞪大双眼。

「这个时间他应该在睡觉了，叫一下应该还是会出来。不过找帕克有什么事呢……啊，我知道了，是自己一个人睡觉觉得很寂寞吧？」

「居然被当成这种人，我平常是不是做人太失败了？不是啦，其实我是想商量有关碧翠子的事，如果爱蜜莉雅酱能陪我聊聊就太好了。」

「碧翠丝的事吗？」

爱蜜莉雅的眼睛瞪得更加斗大，而昴则是朝她投以恶作剧般的笑容。

此种笑容就像是坏孩子即将把珍藏的恶作剧表演出来般。

「我只是想让那个家里蹲稍微瞧瞧而已。」

3

隔天，过了中午后昴才到禁书库露面。

坐在梯凳上的碧翠丝依然没有对昴表示欢迎。由于昨晚的事，她用书遮著脸并散发出更为难以相处的气氛。

「嗨，碧翠子，罗兹亲和拉姆都已经出发啰。都是因为你没有来送行，那家伙的小丑妆都要哭花哩。」

「既然这样贝蒂没去送行就更有意义了。──如果你只是想说这些废话，那还是快滚出去吧。」

碧翠丝宛如赶虫般挥了挥手，此种毫无商量余地的态度让昴搔了搔头，说著「好吧」然后点了点头。

「碧翠子，我们来说昨天的话题吧。可以吗？好，感谢你。」

「真是个擅自带动话题的自私鬼呢！可以别这么自我中心吗！」

「那就让我把任性发挥到最高极限吧。刚才又提到送行的事，如果不喜欢送人出门，那改成迎接回来怎么样？」

「哪有怎么样，没有任何讨论的余地，不想做的事就是拒绝。或许该说完全不懂你为什么这么坚持这件事。」

「没有为什么，因为这对你是很重要的事。」

面对碧翠丝的疑问，昴挽起双手不断点了点头。

从开始这番对话的昨晚以来，昴也同样反覆自问自答，而得到的结论有些难以化为话语说出口。

「虽然有点夸张，不过该说的话还是得说出口才行。要不然之后有可能会后悔的，你应该也有体验过『呃，那时候真是太失败了』之类的事吧？」

「……贝蒂没有碰过那种事。」

碧翠丝别开视线，消极地否定昴的话语。昴从少女的此种态度感觉到效果，于是继续展开追击。

「那是因为你一直窝在禁书库才会没有碰过那种事！真是个无药可救的家伙耶！」

「别用那种会让贝蒂很不高兴的用字遣词，你非得要贬低贝蒂的存在价值才高兴吗？」

「被戳到痛处生气，就是打从心底有自觉的证据。」

「贝蒂已经说过听不懂那些话的意思了，别让贝蒂说那么多次！」

被昴用手指著，碧翠丝露出厌烦神情。她将手指伸进自己的长卷发，并且宛如弹簧般让头发上下弹跳。

「贝蒂完全没听懂你想表达的事，赶快把想说的事说完滚出禁书库吧。」

「碧翠子，要不要和我打个赌？」

「打赌……？」

「没错，就是打赌。来做个小对决吧。」

这个突如其来的奇妙提议让碧翠丝带著无法理解的神情皱起眉头，她以满腹狐疑的视线频频看著昴并开口说著：

「打赌……你是突然在说什么鬼话，贝蒂没有任何理由需要接受吧。」

「凡事只用需不需要判断，以后可是会变成一个无趣的大人喔，不过像罗兹瓦尔那种不够稳重的大人也不太好就是了。」

「只有这点贝蒂有同感。」

两人对不在场的宅邸主人表示一致意见，不过先不论被用来激起共识的罗兹瓦尔，昴则是竖起手指说著「所以啰」。

「为了别成为无趣的大人，稍微和我打个赌玩个游戏吧。能把玩火当成玩笑话，可是我和像你这种小鬼头之间的特权喔。」

「……如果那个什么打赌赢了，对贝蒂会有什么好处？」

「还真是精打细算，你是对奖品有兴趣才想参加吗？」

眯起眼睛的碧翠丝没有回答，不过光是没有否定就是收获，于是昴朝著这位少女伸出右手。碧翠丝不禁露出满腹狐疑的神情，然而──

「只要有人呼叫就出来……」

「喵喵喵～～！」

随著昴的呼叫声，掌心传来跟著唱和的开朗声音并溢出光芒。光芒随即形成小猫的轮廓，在碧翠丝正面显现出并非手搭猫的猫精灵帕克。

小猫一边洗著脸，一边从那圆润黑眸带著恶作剧眼神看著两人。

「不只是莉雅拜托过我，我也有些想法所以会帮忙……不过没想到昴会这么虐待小猫呢。」

「毕竟实在太多连猫的手都想借的事，而且猫手在太多事都派得上用场喔。」

不论是在实力面还是友好层面，借助帕克之手的模式可说是频繁出现。虽然这次也是靠著帕克才能进行的策略，不过结果就像眼前所见到的──

「啊呼……今天的哥哥也是既可爱又毛茸茸的，真是太符合贝蒂理想中的模样了。」

果然如同想像般，用手掌接住现身帕克的碧翠丝显得娇柔体贴，昴则是对这位少女泛红著脸并以纯真眼眸盯著小猫的模样露出苦笑。

「实在很想说这已经样板到毫无变化可言了。不过要是你这次打赌获胜，就给你『一整天能尽量摸帕克』的权利，这已经经过本人与监护人同意了。」

「正确说来我才是莉雅的监护人，这点不要搞错喔。」

帕克直直地竖起尾巴如此强调重点，总之碧翠丝对昴的提议不断地点头如捣蒜。

「这、这不算是很差的提议呢，看来你至少还懂什么叫礼貌呢。」

「我很担心你将来会不会被坏男人骗走就是了。」

「听起来怎么像是多管闲事呢？」

「是你想太多了。那么，要是我获胜的话……就要把送行和迎接变成义务。不只是对罗兹瓦尔，对宅邸的所有人都是一样。」

昴提出的条件让碧翠丝顿时脸色一变。

她当然已经从先前话题想像到会有这种事，只见这位少女的眼眸中带有浓浓看傻眼的气息。

「我没有要你连去村落买东西都得照做，不过像这次至少得露脸出去送行和迎接进门。应该不需要摆出这么排斥的态度吧？」

「……贝蒂实在无法理解你这么坚持这件事的理由。」

碧翠丝紧盯著似乎在沉思的帕克，但很快便选择放弃挣扎，这位少女跳下梯凳落到地面并走到昴面前。

「那来听听打赌的内容吧。」

「意思是你输了就会接受条件吧？」

「只要不输就不会有事了，快点说出来吧。」

不知是否因为接受昴的提议很不愉快，碧翠丝不悦地嘟起嘴巴。趁著她改变心意前，昴只将头转向背后的门扉。

「规则很简单，那就是捉迷藏──不对，应该说是双重捉迷藏吧。」

「捉迷藏……是分成人和鬼两边，由鬼负责追人的游戏吗？」

「没错，就是那个。不过这次规则不太一样，你要在宅邸里担任逃走和追人两种身份。」

面对头上浮现出问号的碧翠丝，昴则是继续说明：

「也就是说，目前爱蜜莉雅酱正在宅邸里四处窜逃。你要追赶抓的人就是四处逃走的爱蜜莉雅酱，不过只是追赶逃走的爱蜜莉雅酱不太有趣……不不，如果是我肯定会觉得超有趣的。」

「昴，话题已经偏掉啰。」

「抱歉。然后追赶爱蜜莉雅酱的同时，你还得躲避准备抓你的人。只要你能抓到爱蜜莉雅酱就算获胜，反过来在抓到爱蜜莉雅酱之前被抓就算输──这就是双重捉迷藏。」

在帕克的些微修正下，昴将比赛的大略规则说明完毕。听完后碧翠丝皱起眉头，并且把玩著自己的长卷发。

「条件只有在宅邸里面吗？庭院和门外面怎么办？」

「庭院还没关系，不过门外禁止，还有也禁止使用『机遇门』和魔法。在捉迷藏用空间转移实在没人抓得到，用魔法也没办法保证不会受伤。」

「唔……这样对贝蒂实在太过不利了吧，没有魔法是要怎么抓到她？」

「那当然就要动脑了，例如躲在阴暗处或绕到前头。爱蜜莉雅酱也是同样条件，再来就要比心机才能决定胜负了！」

「如果你觉得这种说明能激起干劲，那你的脑袋真的有问题。」

碧翠丝虽显得有气无力，但似乎还是认真地思考著该如何赢得这场对决。

「机遇门」被封锁又无法使用魔法，代表碧翠丝与普通小女孩没有两样。即使条件相同，至少爱蜜莉雅的体能实在太过优异了。

不过要是比心机，爱蜜莉雅肯定是全宅邸最弱的人。原因就是她的个性太过老实，如果是以此种捉迷藏的规则，碧翠丝也有相当程度的胜算。

「好吧，那贝蒂就陪你玩玩吧──不过双胞胎的妹妹禁止参加。」

「被你发现啦。」

「这是当然的。就算是贝蒂，也不认为能在没有魔法的情况下赢过鬼族的体力，这点还是得先仔细拉起防线才行。」

揭穿昴的小聪明后，碧翠丝展现出破除策略的自傲神情。

只要昴拒绝这个条件，碧翠丝便不会接受这场对决。或许该说碧翠丝的指证并没有错，昴不得已只好放弃让雷姆参加。

「我等你出去数到一百就会开始追赶，帕克会留在禁书库，只要你一用『机遇门』偷鸡摸狗就会立刻穿帮。」

「别把人看得这么扁，贝蒂怎么可能做出那么不知羞耻的事。」

确认过彼此的条件后，碧翠丝将帕克递给昴，昴则是请接过手的小猫将赌注成立的事告诉爱蜜莉雅。

「──嗯，没问题。莉雅好像也是干劲十足，她已经在宅邸里开始跑跑藏藏了。」

帕克以一副打哈欠的模样通知万事俱备，昴随著这个回答朝碧翠丝招了招手，少女便裙襬纷飞地走到门扉前。

「赶快结束这件事，贝蒂要好好享受与哥哥的约会。」

不知道她想好了什么样的策略，只见碧翠丝充满自信地挥著手离开禁书库。目送她的背影离开后，昴发出声音开始念著数字。

「一、二、三、四、五……」

消除雷姆这张如字面所述的「鬼牌」后，碧翠丝似乎认为自己已经获胜了。

然而──只可惜碧翠丝还是太过老实，从她以为耍心机能赢过昴这点来看，昴认为她的耍心机程度弱得还是用倒数的比较快。

4

穿过「机遇门」的瞬间，碧翠丝确认自己正在餐厅前方。

转移的权利在碧翠丝身上，是她自己选择这里为出发点。为了执行作战计划，她认为从这里开始是最好的选择。

「好吧，那么就赶快把人找出来解决掉这件事吧。」

先前她那消极的态度早已不知去向，碧翠丝只要碰到对决的事就会相当认真。

她立刻开始在宅邸中寻找身为目标的爱蜜莉雅，不过她很快便发现附近有人的气息并抬起头，正好在通道尾端发现了蓝头发的少女。

那是原本身为强敌的女仆双胞胎妹妹雷姆。

「碧翠丝大人，看来您似乎接下这场对决了。」

「就像你看到的，不过贝蒂可不承认你参加。那个家伙的歪脑筋对贝蒂是没用的，他现在应该是歪主意落空感到很失望吧。」

「是的，真不愧是碧翠丝大人，您的慧眼似乎已经看穿昴曾经对雷姆下达指示了。」

雷姆带著一如往常的表情，以似乎含有些许失望的语气低下头。以前的她并不会如此轻易展现感情，而这是受到谁的影响也是无需赘言。

这件事让碧翠丝颇为不悦，于是她轻轻地发出冷哼声说道：

「既然学乖就别再帮那家伙了，那些都是毫无意义的事。」

「说得也是，要是碧翠丝大人能在这场赌注中获胜，雷姆也会仔细思考这件事。不过，昴果然是很厉害呢。」

「──？」

雷姆浮现微笑称赞著笨手笨脚导致计划被拆穿的昴，碧翠丝从她的态度中感觉到一股不协调感，正当她对此皱起眉头的时候……

「登登！」「登登登！」「登登登登！」

宅邸内突然传来这些喊叫声，背后还接连传来门扉连续打开的声音。

此种偷袭让碧翠丝抖了一下肩膀并回过头，只见有几个陌生的孩子从打开的门中滚了出来。

「那、那些家伙是……？」

「是住在附近阿拉姆村的孩子，他们与昴感情相当融洽，今天的事也是爽快地允诺协助，有此种号召力真不愧是昴呢。」

「不是说这些事的时候吧！应该说他为什么随便把村子的人带进宅邸……」

「在罗兹瓦尔大人出门前，昴已经获得大人同意了。由于不希望被闯进的房间已经上锁，也请碧翠丝大人留意本馆三楼、个人房间、更衣室以及宝物库是无法进出的。」

对于雷姆一派轻松地追加注意事项，碧翠丝不禁哑口无言。见到碧翠丝僵在原地，孩童们一起伸出手指著她。

「是昴说的那个女生！」「是家里蹲！」「礼服好可爱喔！」

打量过猎物后，孩童们便团结地朝碧翠丝冲了过来。在此种气势压迫下，碧翠丝只得慌张地拔腿跑向走廊的另一侧。

「顺带一提，那些孩子就是负责追捕碧翠丝大人的『鬼』，请努力逃走避免被抓到喔。」

在旁并肩奔跑的雷姆如此在耳边呢喃，让碧翠丝不禁面红耳赤。

「那家伙……比贝蒂所想的还要更会耍心机啊！」

他并没有提到追赶碧翠丝的「鬼」有多少，装成一副雷姆的事被看穿很不甘心，假装手里的牌被夺走，再将孩童们投入战局。

他对这么无聊的赌注究竟投入多少心力，实在让碧翠丝匪夷所思。

「快追上去！」「把她抓住！」「把她全身剥光！」

碧翠丝一边躲著吵吵闹闹追赶的孩童，一边持续对脑中得意洋洋的昴持续发著牢骚。

「贝蒂绝对不会原谅那个混帐！」

5

接下来，碧翠丝的「双重捉迷藏」可说是炽烈至极。

「啊！是碧翠丝！得快点逃走才行！」

「找到你了！绝对不会让你逃掉！」

虽然在宅邸西馆发现爱蜜莉雅并加以追赶，但步伐与速度之间的差距让碧翠丝立刻被拋下。不过她逃走的方式太过单纯，只要绕道应该就能抓到她……

「在那里！」「找到她了！」「是我老婆！」

「居然在这碰到那群小鬼！你们差不多也该放弃了吧！」

然而却被从旁出现的孩童们阻扰，碧翠丝转过身立刻逃跑，太过深入却被抓住就没有任何意义了。而且孩童们彷佛有耗不完的体力般，虽然脑筋有点笨，但纯以人数与活动力而言可说是充满威胁的强敌。

「而且问题还不只是这些小鬼呢……！」

逃走的爱蜜莉雅与碍事的孩童们，虽然他们的存在让碧翠丝颇为意外，但在捉迷藏上还是有太过单纯的缺点。目前最重要的问题还是──

「──最重要的那家伙还没有露过半次面。」

那就是提出这场赌注并身为鬼从禁书库出发的昴，碧翠丝目前还没有目击到那邪恶的模样。

就连碧翠丝也不觉得昴能像孩童那么容易甩开，光是比脚程就会输了，那异想天开的思考模式也丝毫不会输给那些孩童。

由于在说明规则时已经吃了闷亏，碧翠丝对昴的戒心可说是达到了前所未见的水准。

他要从什么地方出现都无妨，但相反地，也有种希望他千万别出现的想法。

当碧翠丝会如此思考时，感觉似乎已经在气势上输了一截，但目前发挥极限注意力的碧翠丝并没有发现这点。

「……喝！」

她一口气跳下楼梯并裙襬纷飞地著地，然后踩著地毯拔腿狂奔，沿著走廊由西馆回到本馆。就在这个时候……

「糟糕！」

正好从正面房间探出头的爱蜜莉雅发现碧翠丝并赶紧逃跑，碧翠丝紧跟著她那飞舞的银发，也跟著加速不让她逃走。

「不会再让你逃走了！乖乖就范吧！」

「不要！这个好好玩喔！我还想再多玩一下！我会努力逃走的！」

「就说你可以不用这么努力了！」

两人进行著此种少根筋的对话并继续奔跑。听到两人的声音，孩童们也从碧翠丝身后现出身影。

「找到了！」「来了！」「看到了！」「要赢了！」

「真是有够烦的！」

这些孩童完全不知道碧翠丝的想法，只是猛然地追了过来。

形成了爱蜜莉雅领头、碧翠丝在中央、最后则是孩童们的拉锯赛。

双重捉迷藏的缩图变为一列，爱蜜莉雅往下而非往上逃跑，她一口气从楼梯二楼跳到一楼，并非逃向东馆而是逃向宅邸正中央。

「把你逼进绝路了吧！」

碧翠丝只转头看往后方，背后的孩童们还有段遥远距离。在被追上前就能逮到眼前的兔子，接著猎人碧翠丝就能发出胜利的吼声。

「呃……呃……」

爱蜜莉雅张望四周思考著究竟该逃往何处，碧翠丝从她的表情发现有机可趁，于是决定一决胜负。

她已经在本馆中央设下陷阱，为了将爱蜜莉雅引导到该处──

「等等！绝对不会让你逃进餐厅！」

「──餐厅！」

真是太老实了……

说到爱蜜莉雅的败因，那就是她太过老实的个性。

一听到碧翠丝的叫声，爱蜜莉雅反射性地认为餐厅内还有活路，她如此单纯反而让设陷阱的碧翠丝感到有些担忧。

即使如此，对决还是对决，既然掉进陷阱也决定了兔子的末路。

「咦？这里是……」

打开餐厅的门并冲进房内的爱蜜莉雅发出脱线叫声，因为她冲进的餐厅正好是一开始「机遇门」连接的禁书库。

既然「机遇门」没有更新位置，那就表示餐厅的门仍然是连接著禁书库。禁书库不只是条死路，出乎意料的景象也会确实地让爱蜜莉雅停下脚步。

在熟悉的自己房间内，猎人要狩猎僵直的猎物可说是易如反掌。

「看来是贝蒂高了一招……应该说是高了十招才对！！」

确定胜利后，碧翠丝一个急转弯冲进餐厅──应该说是禁书库内，然后朝著惊讶地停下脚步的爱蜜莉雅背后伸出手。

「──欢迎光临！」

「什么！？」

从旁伸来的手腕将碧翠丝的身体轻松地一把抓住。

两侧腋下被抱住的她只能在空中摆动双脚，碧翠丝还不知道发生什么事而回过头，正好与带著恶魔般笑容的昴四目相对。

「比赛结束～～贝蒂很可惜，就像你看到的是昴赢啰。」

见到碧翠丝被抱起来，坐在梯凳上的帕克则是无情地宣布这件事。

在一旁的爱蜜莉雅微微露出苦笑，与追上的孩童们在房间前高举双手击掌，而碧翠丝只能哑口无言。

「我就说了，碧翠丝。」

昴重新抱好无言以对的碧翠丝，从正面与这位少女互相对看。

「──我说过是比心机了，你觉得玩心机能赢过我吗？」

他的笑容可说是令人相当火大，于是碧翠丝气得跳起来用膝盖顶进昴的心窝。

6

「我从一开始就猜想到你会用禁书库来设计爱蜜莉雅酱了，毕竟你有用『机遇门』找人麻烦的习惯。」

「唔唔唔……」

听完这段对决后的评语，碧翠丝不甘心地发出低吟声。昴对她那咬牙切齿的模样感到相当舒畅，并且摸著被狠狠踹了一脚的心窝。

──在这场双重捉迷藏中，昴的策略相当简单。

首先是关于「鬼」追赶碧翠丝的陷阱，先让碧翠丝发现雷姆的存在，趁著碧翠丝得意忘形时再叫孩童们增援出面追捕。

先用这个策略逼急碧翠丝，再用爱蜜莉雅当成诱饵的策略决定胜负。

「我已经把开始地点告诉爱蜜莉雅酱，请她在紧要关头逃进禁书库，然后躲在禁书库的我会负责抓住你，猎人即将得到猎物的瞬间才会出现真正的破绽。」

对于昴得意洋洋的战术论调，碧翠丝无法反驳。既然被昴完全玩弄在掌中，不论说什么都只是马后炮而已。

现在的她只能在平时坐的梯凳上抱著双腿并瞪著昴。

「不过真是太好笑了。刚才那是说什么来著？碧翠子高了一招……还是高了十招？可惜我可是高了十一招喔！」

「得意忘形也要有个限度吧！！」

「唔嘎哇吧！」

超过忍耐限度的挑衅让碧翠丝怒不可遏，被冲击波击飞的昴数度弹跳撞上墙壁，碧翠丝则是冷冷哼了一声。

「贝蒂承认你真的很会耍心机，不过可没有义务被你嘲笑，应该说贝蒂从一开始就不想接下这场赌注。都是你……」

「想把赌注一笔勾销，你会不会想得太美了？这样帕克也会很生气又难过，然后说著『没想到会把你教成这个样子』喔。」

「真是个讨人厌的家伙……」

想反悔的碧翠丝对昴的模仿发出咋舌声，不过昴对她那逞强的侧脸叹了一口气。

「唉，如果你怎么样都不想做，我也不是没想过解决的方法。」

「……你是哪根筋突然烧坏了？」

「我只是觉得这样很没气度而已，感觉是特地做好所有准备把你修理得很惨，而你也太容易被我玩弄在掌中，所以一个不小心就……」

「看来贝蒂的魔力还让你跳得不够呢。」

对于昴太过老实地说出自己的想法，碧翠丝似乎相当不满。

不过这确实是昴的心声，他当然也不觉得这场赌注有任何错。

「也有部分原因是我想逼你这么做。虽然我觉得就算不甘愿应该也会越做越顺手，不过硬逼你这么做好像也违反了初衷。」

「贝蒂一开始就问过了……你到底是为了什么要这么做？」

「嗯～～连我自己都不知道，不过今天这场对决好像也让我发现了某些事──那就是你居然能这么有精神四处活蹦乱跳耶。」

「唔……」

昴盘腿坐在地面，朝著鼓起脸颊的碧翠丝笑著如此说道。

「虽然对你来说可能不是很甘愿，不过我倒是挺开心的。爱蜜莉雅酱和村子里的那群小鬼头应该也玩得很开心，以双方妥协点来说还不算太差。」

「总觉得只有贝蒂是抽到下下签呢。」

「这两件事要分开谈，你就当作这是输掉的惩罚放弃挣扎吧。」

朝著闹别扭的碧翠丝如此说完后，昴站起身走向禁书库的门。

毕竟已经把整个宅邸玩透了，必须依照与罗兹瓦尔之间的约定，在他回来前得把宅邸恢复原状，不然就会有拉姆的恐怖处罚降临。

「碧翠子。」

在离开房间前，昴朝著碧翠丝回过头。

她没有发出回应声，但碧翠丝仍然以刺痛视线狠狠地瞪著昴。

「下次再一起玩吧。」

在做出肯定与否定的回应前，昴已经离开将门关上了。

「机遇门」起动将昴移动到宅邸的餐厅前方，爱蜜莉雅与雷姆两人正好站在眼前，昴则是带著一副放松的表情举起手。

「嗨，辛苦两位啰。」

「是，昴也辛苦了。」

「不好意思给雷姆添了这么多麻烦，还把照顾小鬼头的责任推给你。他们应该很吵又不听话吧？」

「没有这回事，大家都很听话。雷姆已经让他们带烤甜点当礼物带回村子，还说希望下次能再找他们来玩呢。」

「那些家伙对我和雷姆的态度差真多耶！？」

明明对昴是一副旁若无人的态度，但对雷姆似乎相当听话，看来下次得在每天做的收音机体操好好逼问这件事才行。

而且也得感谢他们前来帮忙的事。

「所以呢？有向碧翠丝说清楚了吗？她没有生气吗？」

当昴对孩童们的态度露出尴尬表情时，想知道结论的爱蜜莉雅歪著头如此问道。她的视线正注意著餐厅门扉另一侧的禁书库。

「总之她好像已经认输了……不过对赌注的结果还不太能接受，我也觉得赌注算是其次了。」

「是这样吗？那捉迷藏是为了什么？」

「那当然是为了玩，我是想教教那个不健康的家里蹲女孩与同年代小孩全力奔跑的快乐，关于这点我觉得应该满顺利的。」

昴揶揄地如此说著并眨了眨眼，爱蜜莉雅不禁露出有些惊讶的神情，不过很快便傻眼地吐出一口气并转为微笑。

「嗯，也是。碧翠丝应该也玩得很高兴才是，因为我也玩得很开心喔。」

「那真是太好了……好啦，那么该开始收拾善后了。」

昴对爱蜜莉雅的微笑看呆了，于是搔著脸颊试图掩饰害臊的情绪，结果雷姆突然悄悄拉了拉昴的袖子。

「收拾是很重要，不过先稍微休息一下吧。罗兹瓦尔大人与姊姊是明天晚上才会回来，还有很多时间喔。」

「没错，雷姆还替我们准备了烤甜点，先稍微喝个茶再来收拾吧。其实我也想找碧翠丝一起过来……」

「呃，我想应该会被拒绝……吧？」

「既然这样就把帕克带过去吧，这样应该就扯平了。」

由帕克接待或许稍微能抚平她的不悦，不过从爱蜜莉雅的提议中似乎很难感觉到有此种意图。

「那么昴，我们出发吧。」

「对啊对啊，我们一起去吧。」

「好好，毕竟我也不想太急躁没处理好被拉姆臭骂一顿。」

总觉得两人似乎显得颇为愉快，不知是否因为这天对两人而言过得很有意义。如果是这样，昴认为自己动歪脑筋就有价值了。

「如果你也能稍微这么想就好了。」

昴一边想著不在此处的那名少女，一边只在口中如此喃喃说著，然后缓缓打开弥漫著甜甜香味的餐厅大门。

7

约过了一整天后才收拾好捉迷藏的善后工作──差不多是宅邸主人预定回来的时间前一刻。

「那些臭小鬼……居然毫不留情地把宅邸弄得那么乱。」

「幸好没有任何物品损坏，因为已经事前把可能会被孩子们弄坏的物品集中保管了。」

「啊，两位都辛苦了！只能帮忙到途中真的对不起喔。」

转著手腕的昴与带著微笑的雷姆一同来到玄关大厅时，正好走下楼梯的爱蜜莉雅也与两人会合，三人就这样站在玄关大厅说著话。

「不过话说回来，能让爱蜜莉雅酱亲自出来迎接，罗兹亲还真是幸福。」

「是这样吗？不过昨天听完昴说的话后，我也觉得这果然是很重要的事。在这之前都没有特别注意过，我接下来会认真看待这件事的。」

「应、应该不是需要这么认真思考的事吧？别让自己想过头喔。」

昴对握紧拳头并颇为气宇轩昂的爱蜜莉雅回以苦笑，毕竟她的个性既老实又认真，因此小小的精神论便出现了绝佳效果。

就在三人一如往常地说著话时……

「────」

突然有道脚步声传进并肩站著的三人耳中，那是一道既细微且似乎显得有些犹豫的脚步声。发现来源后，三人皆瞪大双眼并分别露出笑容。

脚步声无声无响地靠到三人身旁，然后吐出一口彷佛放弃的叹息声。

三人并没有追问理由，只是接纳这位小小人影做为第四人。

「────」

没有人提起这道人影加入的事，但全员皆自然地理解到自己应该这么做。

时间静静地流逝，最后玄关门扉随著说话声一起敞开……

「──欢迎回来。」

有精神的三道声音与一道较为内敛的声音互相重叠，迎接著这座宅邸的主人归来。

** 『喜欢冷天气』

1

──那是一道既细微且缓慢变化的预兆。

「昴，早安。」

「呼啊啊……早安。我说雷姆，你不觉得今天有点冷吗？」

「说得也是呢。今天早上似乎有点冷，真不愧是昴，慧眼独具。」

「不不，天气冷大家都会发现吧？」

在早晨的罗兹瓦尔宅邸走廊碰到雷姆后，昴的早晨打招呼也是提到关于气温的话题。虽然还是清晨，但今早的气温可说是颇为寒冷，昴记得昨天一整天还有令人汗流浃背的暑气，竟然一晚就有如此夸张的气温差距。

此种寒冷气温也让昴将制服前方扣起，衬衫钮扣也是全部扣好直到颈部。

「先不说我，雷姆这种装扮已经不是冷不冷的问题了吧？女仆装没有得换吗？这样不会觉得很难受吗？」

「只要进入正式的冰季，雷姆当然会换上寒冷时期用的女仆装。不只是有厚布料还塞进棉花，所以穿起来很温暖的。」

雷姆带著微笑如此回应，她仍然穿著一如往常的改造女仆装。由于是大胆露出肩膀与双腿的设计，平常此种多处露出肌肤的养眼模样，目前也看来颇为寒冷。

附带一提，「冰季」似乎是称呼像冬天般寒冷的季节。反过来炎热的季节似乎称为「火季」，在这个世界也有类似四季的变化。

「不过现在这种气温，穿冰季制服应该会比较好吧？如果你不方便说，那我直接告诉罗兹亲吧。」

「雷姆很高兴昴如此担心，不过雷姆与姊姊都很习惯了，所以不会有事的。这不是需要劳烦罗兹瓦尔大人的事。」

雷姆对昴的体贴话语坚强地摇了摇头，虽然昴不太能接受这个答案，但还是接纳了这个意见。

「好吧，既然雷姆都这么说了……话说大姊呢？没有和你一起吗？」

「是的，姊姊今天早上说天气很冷不想下床，所以会睡晚一点。」

「就在你说了『雷姆和大姊都很习惯』之后就来这一招吗！？」

脑中浮现出拉姆仍然独自躲在被窝舒服赖著床的模样，让昴愤慨地想著总有一天要制裁这位沉溺在妹妹慈悲胸怀的姊姊。

「不能让她过得这么爽，不管是冷还是热，哪有住在宅邸的仆人还在休息的。雷姆，我们去把她叫起来吧。」

「不过姊姊每天处理繁忙事务一定很累，偶尔在天气冷的时候赖个床……」

「雷姆，走啰！」

「好的！既然昴都这么说了！」

心中的天秤瞬间倾倒，雷姆则是轻快地跟在迈开步伐的昴后头。

结果那天，昴最后只能被迫在拉姆被拖出棉被的怨恨与冷冽的风中处理工作。

2

──在饱受拉姆态度与寒风折磨后的隔天。

「呼啊啊……好冷又好困喔……咦？碧翠子？」

「唔呃呃……」

今天早上醒来的昴一来到走廊，罕见地遇到在无人走廊偷偷摸摸前进的礼服少女碧翠丝。

她那奢华的长卷发可说是太过具有特色，算是这间宅邸第二名不适合偷偷摸摸的人，第一名不用说当然就是这间宅邸的主人。

「这么早你在做什么？该不会又是熬夜到早上吧？常常熬夜可是会很难长高，总是在昏暗地方看书也会让视力变差喔。」

「真是多管闲事又让人火大的忠告，贝蒂的身高与视力和你没有任何关系……应该说贝蒂没时间陪你玩耍，赶快从贝蒂眼前消失吧。」

「好好。先不说这个，今天你不觉得超冷的吗？总觉得昨天也是很冷，不过今天又变得更冷了……」

「你根本不懂嘛！贝蒂不是说没空陪你玩了吗！」

昴一边对超越昨天的寒冷缩著头，一边靠向大声嚷嚷的碧翠丝面前。虽然少女明显地露出厌恶神情，但擤著鼻涕的昴并没有继续追究。

之所以会感觉到气氛紧绷，肯定是因为偶尔会吹来的刺骨寒风，窗外那微微阴沉的景色与随风摇荡的树叶，甚至像是表达著痛苦一般。

「季节转换很容易感冒，你自己记得注意保暖。」

「哼，贝蒂不需要担心这种事。贝蒂还没有软弱到需要你担心，秤秤自己有几两重吧。」

「说什么担心你，只是照顾你很麻烦而已。雷姆找不太到你的房间，特地替你做的粥凉掉实在太可怜了，感冒的时候至少乖一点嘛，真是个不可爱的萝莉。」

「贝蒂为什么要在这个假设的情况和结果下被念啊！」

在昴擅自想像下被如此指责，碧翠丝气得不停跺脚，不过少女随即鼓起脸颊，宛如赶虫子般朝著昴挥了挥手。

「总之贝蒂现在很忙，别去管冷不冷，你也好好拚命处理你自己的杂事吧。」

「说什么忙不忙的，你也只是窝在房间看书而已吧……对了。」

「……贝蒂已经要走啰。」

「你偶尔也来帮忙处理宅邸的事啦。动动身体不只能驱寒，也能减少运动不足而感冒的担忧，可是一石二鸟喔。听起来很不错吧！」

昴抓著准备转过身背对的碧翠丝肩膀，并且带著笑容如此提议，但碧翠丝面露不悦地回过头。

「……快放手，要说几次你才听得懂贝蒂很忙。」

「好好，我知道啦。我会向罗兹亲说给你工作份量的零用钱，像个小孩子至少帮忙拔草吧。」

「什么！？你以为贝蒂是因为这种理由赌气吗！而且听贝蒂说话啊！别开玩笑了！」

昴抱起气得面红耳赤的碧翠丝，将这位摆动四肢不停挣扎的少女带走。虽然碧翠丝拚命抵抗，但今天难得没有以魔法进行反击。

虽然这点令人匪夷所思，但缺少抵抗反而是好事。

「好～～！要开始跑啰！有精神地摆脱寒冷吧！」

「把贝蒂放下来之后，第一件事就是先揍扁你！」

怒气即将爆发的碧翠丝不停嚷嚷，昴则是沿著宅邸走廊有精神地开始跑步。

而那天宅邸也是持续传出碧翠丝高亢的怒骂声。

3

──接著，在戏弄碧翠丝后的隔天。

「咦唷？昴，你今天很早起来呢。」

「呃……喔，是罗兹亲啊……早、早安……是满早没错的啦……」

仆人的工作并没有较为正常的假日，今天昴也在早晨的走廊遇见宅邸主人罗兹瓦尔•L•梅札斯边境伯。

这位脸上平常总是画著小丑妆的诡异贵族，今天也是维持著一如往常的模样。

被他那左右分别呈现蓝与黄色的异色瞳看著，昴发著抖并发出晨间招呼声，并且转动僵硬的脖子与绷紧脸颊望著窗外。

对于昴的模样，罗兹瓦尔则是一脸费解地歪著头。

「看你今天早上好像状况不太好呢，是怎么啦？」

「当然是冷啊，还有什么！？」

被问到这个浅显易懂的问题，让昴吐出白色气息与激烈回应。

很冷，真的太冷了。昴在连鼻水都即将结冰的寒冷气温中跺著脚。

「这种气候再怎么说也太奇怪了吧！昨天还能用想太多解释，今天实在没办法再瞒混过去了吧！？连窗户都结冰了，吐出来的气也是纯白色的耶！」

昴指著结冻的窗缘如此说著。他身上已经裹了好几层毛巾，在睡觉用的运动服外面再穿上管家服，模样可说是彻底亵渎社交界。但即使穿成这样，寒气依然从布的缝隙间意图夺走昴的性命。

「这是怎么回事？这个季节的气候变化有这么剧烈吗？前两天根本是每天降十度的等级耶！天气冷得这么快，就连熊都会来不及冬眠直接冻死吧！」

「哎呀呀，怎么这么消极呢？这样可是不行的喔？要让自己的身心灵保持积极，不论气温怎么降低都要维持平常心……」

「穿著毛茸茸衣服与毛皮的家伙根本没有说服力啦！」

虽然罗兹瓦尔提出精神论，但他那已经做好抗寒措施的模样完全没有说服力，那铺满厚重毛皮的宽大防寒衣物甚至看似能抵挡极寒雪山的寒冷。

「再这样下去，这种防寒上的贫富差距很有可能会引来杀机……嘶嘶……」

「从你露出那么邪恶的眼神吸著鼻水来看，确实已经快到达极限了。到昨天为止还能睁一只眼闭一只眼，不过今天这样再怎么说就不太行啰。」

「你这种说法是对这种寒冷天气有头绪吗？既然这样快想办法解决吧，如果是魔兽『冬将军』之类的原因就麻烦尽早搞定吧，麻烦大师了。嘶嘶……」

面对罗兹瓦尔将手抵在下颚深思的模样，以小碎步跺脚的昴可说是心急如焚。垂下的鼻水与结冻的思考已经快到达极限了。甚至有可能出现把别人衣服剥下来的道德沦丧危机。

「昴，你该不会是很怕冷吧？」

「冬天抱怨冷、夏天抱怨热、春天抱怨困、秋天抱怨松茸太贵。我可是个标准的脆弱人类，嘶嘶……」

「我听不太懂松茸是什么，不过大概能理解你是个不太会忍耐的年轻人了。既然这样也是没办法的事，我们去对当事人说个几句吧。」

罗兹瓦尔翻动毛皮斗篷走在前头，昴也跟在他的后头。当两人踩著覆有长长毛皮的地毯前进时，昴对窗外白茫茫的景色皱起眉头。

「你很在意外面吗？」

「那是当然的，虽然我不是雪国出生所以不太清楚，不过这么冷的天气就算下雪也不奇怪吧。要是下雪的话，村里的田地要铲雪还挺让人担心的。」

在宅邸邻近的亚拉姆村，听说已经快到了田地收获的时间。

与村人感情融洽的昴，已经与孩子们约好收获时要过去帮忙。即使撇除约定，下雪也不是值得欢迎的天气。

「毕竟昴和村民……尤其是和那些孩子感情还不错嘛。」

「只是碰巧而已啦，我不太喜欢既任性又乱冲乱撞的小屁孩，不过既然是他们主动亲近就没办法啰……」

「好好，难怪昴会在地方上被叫做有名的『傲娇』喔。」

「嘶嘶～～！哎呀～～鼻子真是受不了！嘶嘶嘶嘶！鼻水流个不停啊！」

昴用吸鼻水的声音硬是将这番不利发言掩饰过去，罗兹瓦尔则是含笑带过，悄悄伸出手指划过起雾的窗户。

「总之你放心吧，这种寒冷天气应该不会传到村子，这种寒气应该只有笼罩宅邸附近而已。」

「是要我怎么放心啦！？这种不可思议的现象是怎么回事？到底是怎样才会变成这样啦！？」

「为了不让寒气扩散出去，已经有两个孩子去处理这件事了。其中一边昨天在被你逮到之前应该是偷偷摸摸的吧？」

「……你是说碧翠丝吗？」

罗兹瓦尔的话让昴回想起昨天碧翠丝鬼鬼祟祟的模样，原本还搞不清楚她一大早到底在做什么，原来是为了减轻寒气损害的行动。

如果罗兹瓦尔所言属实，那么碧翠丝特地前来帮忙的对象就是──

「这股寒流的原因是谁，应该不需要多说了吧？」

昴得到答案的同时，走在前方的罗兹瓦尔正好停下脚步。

在罗兹瓦尔宅邸的东馆最高层，眼前的房间对昴而言可说是很熟悉的场所，毕竟这是他每天都会为了拜访主人而来到的房间。

「爱蜜莉雅大人，一大早前来打扰相当抱歉。可以稍微借用一点时间吗？」

「……罗兹瓦尔！？呃……稍微等我一下！等一下喔！」

当罗兹瓦尔朝门内如此问话，房间内便传回慌慌张张的声音。

虽然那是一道隔著门都能听出彷佛银铃般的声音，但昴能够从中感觉到难掩惊讶与焦躁的情感，而且对于这个时间房间主人已经起床有种不协调感。

在同个屋檐下生活已经过了几个星期，她起床的情况并不能算是相当迅速。

「昴～～」

罗兹瓦尔叫著皱起眉头的昴并指著房门的门把，应该不会是要打开门的意思吧？虽然带著此种疑问，但昴还是将手伸向门把。

「好冰！？这是怎么回事！？爱蜜莉雅酱没事吧！？」

「咦！？昴也在吗！？」

「这不是在不在的问题了吧？应该有更需要先说的事吧！」

「需要先说的事……先说的事？早安？」

「还记得打招呼真是有礼貌……不对啦！真是的！我要开门啰！」

摸到的门把就像是碰到冰块般冰冷，连门把都冰冷到这种程度，表示室内有可能是处在更严酷的寒气中。

「我要进去啰！如果正在换衣服就先说感谢啦！」

「不是道歉吗！？」

昴说出同时带有担忧与下流的声音并将房门打开，房门传来一股彷佛与地面剥离的声响以及抗力，封锁在室内的寒风也突然满溢而出。

「不会吧！？超冷！这是怎么回事！？」

超乎想像的寒流让昴发出惨叫声，让昴朝室内投以惊讶目光。结果房间深处能够见到背对著床铺，并且伸出双手杵在原地的爱蜜莉雅。

她慌张地红著脸颊，拚命地遮著床铺避免被昴看见。

「爱蜜莉雅酱！这是怎么回事……」

「不、不能进来啦！没有经过主人同意就闯进房间很没礼貌……没错！这样是很没礼貌的事吧！快、快点出去重新再来一次！」

「爱蜜莉雅酱都这么说了，宅邸主人觉得呢？」

「允许进房喔。」

「罗兹瓦尔！」

以歪理反驳爱蜜莉雅的主张后，昴便踏进房内。

寒流的发生源肯定在房间深处，而从罗兹瓦尔的证词、碧翠丝的行动、以及爱蜜莉雅那宛如孩童隐瞒恶作剧般的态度判断，真相可说是欲盖弥彰。

「身为原因的帕克呢？身为怕冷代表的我要来抱怨个两句。」

「原因？原因是指什么？我完全……呃，是没有到完全啦，不过我还是听不懂呢。」

「──莉雅，没关系。反正差不多也没办法隐瞒了。」

面对爱蜜莉雅慌张地找著藉口却微妙地没有说谎，但无疑有他的骚动源头却无意抵抗。

这个声音让爱蜜莉雅皱起眉头，回过头看著床铺并将手叉腰。

「真是的！帕克真是笨蛋！只差一点就能隐瞒过去了……」

「不不，再掩饰几百年都不可能瞒过去的。」

「咦！？」

先不论认真感到惊讶的爱蜜莉雅，昴探出头窥视著他背后的床铺。在皱成一团的毛巾上能够发现身为寒流源头的猫精灵缩成一团。

「你那种动作还真像猫。」

「嗯……抱歉给你们添麻烦啰。」

昴的话让灰色毛球扭动身体，以圆润的黑色眼眸紧盯著昴，然后这只掌心尺寸的小猫帕克对爱蜜莉雅的落寞模样露出苦笑。

「别对莉雅和贝蒂生气，因为他们两个都是为了我著想。」

接著，他对爱女与情同妹妹的贴心举动如此补充说明。

4

「……发『魔』期？」

这个没有听过的单字，让昴皱起眉头并歪过头表示不解。

场所转移到罗兹瓦尔宅邸的餐厅，宅邸内的所有成员皆已到齐。包括赖床的拉姆与试图逃走的碧翠丝在内，所有人皆围绕著在桌面上的帕克。

大家已经有共识这几天寒流的原因就是帕克，当追究到究竟发生了什么事时，就出现了一开始「发魔期」的那个单字。

「发魔期是什么？不是发情期吗？」

「我又不是动物，不会有发情期啦。真是没礼貌呢。」

「从各种角度都很难回话耶。」

见到帕克以像是真猫的模样洗著脸，昴带著困惑神情转头环视周遭，雷姆则是对昴的视线举起手表示有话要说。

与昨天不同的是，今早雷姆总算改穿冰季用的女仆装。虽然大幅度减少露出肌肤的部位，但看她穿短裙露出双脚的模样感觉还是很冷。就算是跨越不同世界，昴还是无法理解女孩子在冬天穿裙子的心态。

「发魔期是部分具有强大魔力的象征，会在固定周期发生的现象。由于魔力强弱会依据各自的欧德──也就是受到魔力核心的资质影响，所以其实是很特定的情况才会出现。」

「那个欧德……又与玛那和门不一样吗？」

就昴所知，玛那是这个世界中的魔力根源。让玛那在体内外循环的器官就是门，而门的质量与身为魔法使者的资质有直接关联。

顺带一提，昴身为魔法使者的资质可说是相当平庸。而且由于先前过度使用门，因此已经被严厉叮嘱禁止使用魔法。

「从雷姆的话来看，欧德是比玛那和门更重要的部分吗？」

「──身为罗兹瓦尔大人的仆人，这么无知已经足以成为罪过了。」

面对昴对魔法一知半解的发言，拉姆刻意地叹了一口气，在雷姆身旁穿著更加厚重服装的拉姆眯起那淡红色的眼瞳。

「毛，连欧德都不知道，真是肤浅到让人怀疑你的常识。」

「虽然我觉得有可能是太冷的关系，不过大姊似乎比平常更辛辣了。」

那平常总是不留情面的口吻，在寒流中可说是更加毒辣。拉姆抱著妹妹的手腕取暖，吐著白色气息以视线逼迫著昴。

然而与雷姆不同的是，她那戴著可爱耳罩的模样可说是欠缺魄力。

「我从前两天就在想，大姊好像很怕冷喔。」

「怕不怕冷只是主观的问题，拉姆活著不会以那么狭隘的视野看待事物。别随便想说什么就说什么，真是有够蠢的，去死吧。」

「后半段有够随便又毒辣！」

「每次都是这样，只要放任你们说话总是不会有进展……」

对于不悦拉姆与即使寒冷仍不忘挑衅的昴，没有耐心的碧翠丝从旁打断话题，这位仍然穿著平常礼服的少女用手指著昴。

「真是拿你没办法，只好由贝蒂来说明了。欧德是生命的核心……不论精灵、人类还是魔兽，不论是什么样的生命都会有欧德这种魔力泉源。欧德就像是魔力的容器，也是从门吸收玛那后囤积的器官。」

「喔喔，是囤积玛那的容器啊。可以继续说下去啰。」

「真是让人火大的回话方式呢……总之优秀的欧德能累积多量玛那，可是不论什么样的容器都有容量极限，然后濒临极限的欧德会满溢出玛那……在那之前必须要释放出来。」

「在肚子爆炸之前先拉出来……所以就像便秘一样吗？」

「可以考虑一下用字遣词吗！」

面对自我解释的昴，结束说明的碧翠丝显得相当愤慨，但多亏她才让昴理解到这次骚动的来龙去脉。

「也就是说，这次寒流的原因就是帕克把累积的玛那释放出来吧。」

「……嗯，就是这样。不好意思没说出这件事。」

事情真相大白后，让爱蜜莉雅沮丧地垂下头。照顾家猫的责任在监护人身上，爱蜜莉雅的此种态度让昴用眼角余光瞥著身为战犯的帕克。

「真是个给别人添麻烦的解便秘方法耶……这个会定时出现吗？」

「大概是一年一次吧，与莉雅住在森林的时候会适度地释放出来，可是来到这里之后我就变乖很多，说不定是因为这样才出现的反作用力吧。嘿嘿。」

「嘿嘿你个头啦。」

昴对带著腼腆笑容的小猫露出傻眼表情，然后挽起双手继续说道：

「既然是必须释放出那个魔力，那我也没什么意见了。不过怎么会在这三天突然出现这么强的影响？应该还有其他方式可以用吧？」

「嗯，一开始我是有留意影响慢慢释放出来。不过因为囤积的玛那比平常还多，而且没有人说会冷，所以就变成『咦？感觉好像可以再放多一点？好，一定没问题的！没想到大家这么好说话呢！』这个样子了……」

「做事有够随便的！」

原本昴以为是无法控制的事，结果只是单纯的疏忽而已。

或许该说体感温度每天下降十度，每个人都会发现情况不对劲，一想到这种冷到心坎的寒气是帕克得意忘形造成的结果，就让昴的不满水涨船高。

「发魔期是像哥哥这种大精灵无法割舍的问题，你就看在哥哥毛茸茸的分上别抱怨了。嘶嘶……」

「你这家伙也在擤鼻涕嘛！应该说是你设下结界把寒气封锁避免这件事穿帮吧？说实话！」

「嘶～～贝蒂完全听不懂你在说什么呢。」

「居然鼻塞了！」

碧翠丝的鼻头显得红通通的，即使如此她仍然没有放弃替帕克说话。少女冥顽不灵的态度让昴闭口不语，取而代之地是爱蜜莉雅从旁说著「等等」打断话题。

「那个，这次的事我和帕克都已经仔细反省过了。不过帕克的发魔期应该快结束了……是这样没错吧？帕克？」

「嗯，同样程度只要再两天就可以了。」

「我们这边完全没做准备啦！要是照这样再冷下去，明天早上就会看到我和拉姆冻死的尸体了啦！」

明明身为当事人，帕克的态度却显得不太认真。看来帕克本身感觉不到寒冷，或许因为如此才让他显得事不关己。

「话说回来，帕克是精灵又有自备毛皮可能不需要在意，不过爱蜜莉雅酱穿那么少都不会冷吗？我想看看爱蜜莉雅酱穿得毛茸茸的模样。」

虽然最后那段话是心声，不过大部分都是认真担心爱蜜莉雅的发言，爱蜜莉雅在此种寒气中仍然穿著一如往常的单薄衣物。

面对昴的疑问，爱蜜莉雅似乎更加抱歉地垂下头。

「那个……我不是和帕克缔结契约吗，因此能够调节帕克魔法受到的影响，所以这股寒流也没有问题……」

爱蜜莉雅似乎越来越谴责自己，感觉她莫名地变得越来越无地自容。这次之所以爱蜜莉雅会呈现自责态度，自己没受到影响的罪恶感似乎也是原因之一。

不只是亲人成为骚动的原因，只有自己免于受害的良心苛责应该也让她很难过才是。

「给女儿添那么多困扰你都不觉得丢脸吗？来想点办法解决吧。」

「我当然觉得很难受，也希望能有别的方法解决就好。你有什么好主意吗？只要能大量消耗玛那就可以了。」

「不能随便找个地方乱放强力魔法吗？」

「也就是说，你要给我毁灭这个世界的许可证吗？」

「最好会给啦！」

「我是开玩笑的啦～～」

不是天崩地裂就是世界灭亡，虽然是开玩笑但还是十分空虚，而且感觉要是随便肯定绝对不会有好事，于是昴决定暂时避免太过轻率的言论。

「不过这么冷会对工作造成影响。实际上，拉姆在这三天的工作效率下降许多。」

「都躲在被窝当然会让效率降低。这个发魔期是只有精灵才会出现的问题吗？很强的魔法使者……罗兹亲和碧翠子呢？」

说到很强的魔法师，对两人而言应该也不算例外。成为话题目标的罗兹瓦尔耸了耸肩，碧翠丝则是让自己的长卷发上下弹跳。

「我是平常就会妥善调整自己的魔力，还有每天的日常行程，所以欧德都是维持在游刃有余的状态喔。」

「为什么日常行程会让拉姆……呃，还是算了，我不想再问下去了。」

当罗兹瓦尔拋了个媚眼，拉姆则是红著脸低下头。对于宅邸主人与女仆之间的不纯洁关系，近在身边的昴反而觉得太过写实而不想继续追究。

「贝蒂是靠著维持禁书库和『机遇门』妥善调整。对了，最近把某个很吵的人类揍飞也会用到。」

「好好，很可爱很可爱。」

昴将挑衅装成没听见，无视于这位鼓起脸颊的少女看向爱蜜莉雅与雷姆。

「那爱蜜莉雅酱你们呢？发情期……不对，应该说是没有发魔期吗？」

「只有很少数拥有很强资质的人会发生发魔期……」

「我也不太有身为魔法使者的资质，所以与发魔期无缘……啊，不过帕克对这件事经验很丰富，所以这次真的很对不起，我已经反省过了……」

「今天爱蜜莉雅酱的自虐梗还真多耶！」

她那既老实且认真的个性今天反而造成反效果，代替那个被女孩抱著而一脸事不关己的犯人，这时候看来只能由昴大展身手了。

「好吧，那就使出吃奶力气来好好摸索对策吧。总而言之，最近你使用感觉最好一次的魔法是在什么时候？」

「说到最近，应该是在王都与那个黑衣女孩交手的时候吧。毕竟打到玛那都用光了呢。」

「刚打起的精神都被消失的腹部伤痕抽干啦！」

被「掏肠者」击败的记忆，以及仅仅一个月前的旧伤传来阵阵痛楚。只是单纯为了散发魔力，是不可能找到那么强的对手来发散精力的。

「既然不行的话，那只有来森林迎接莉雅的罗兹瓦尔最适合了。说来惭愧，我记得那次也是大闹了一场呢。」

「哎呀，那次确实是相当刺激呢，那么大规模的魔法战可能是我人生中第一次碰到喔。」

「没事前预约就闯过来真是吓死人了，哈哈哈。」

「整整认真打了一昼夜呢。」

虽然两人一派轻松地如此说著，但事实上应该是一反气氛打得极为剧烈。说不定这两人确实如同话中所说，认真打起来就会让这个世界毁灭了。

「爱蜜莉雅酱，实际上状况到底怎么样？」

「后来听说那个地方的地图必须重新绘制才行……」

「好！确定不行啦！否决这个写做强敌念做『朋友』的作战！」

「吼唷～～」

「吼唷个头啦！别打个架就改变地形！给我向伊能忠敬道歉！」

「忠敬先生对不起！」

向步行完成绘制日本地图的伟人道歉后，昴烦恼著这个超乎想像的难题。如果可以的话，他原本想向经验丰富的爱蜜莉雅请教知识，然而……

「与帕克在森林的时候没有那么多会造成麻烦的人，没想过发魔期会是那么严重的问题。所以我也很头痛……」

「结果烦恼过后就是这几天的惨状。我能理解爱蜜莉雅酱想自己解决的心情，这种时候就是要向周遭的人……尤其是拜托我就好啦。」

昴并不讨厌受人请求，如果是爱蜜莉雅就更不用说了。再来就是雷姆或偶尔是拉姆，再加上碧翠丝、帕克或是萝兹瓦尔都没问题。而且还有村民与那些孩子──没想到出乎意料还满多的。

不管怎么说，在这个世界也增加了不少熟面孔，因此昴也想珍惜与这些人之间的羁绊。

「要是差点毁灭这个世界，要展开打倒大魔王帕克之旅也挺麻烦的……得想想能暂时度过难关的和平方法才行。说得也是……」

「──昴，你是不是又想到什么歪主意了？」

「真不愧是昴，雷姆真是太佩服了。」

「期待得太早了吧！」

昴对察觉意图的爱蜜莉雅与提早误会的雷姆露出苦笑，然后走到雾茫茫一片的餐厅窗户旁，接著用手掌擦了擦窗户并将目光转向宅邸中庭。

「这股寒流只限定在宅邸，都是多亏碧翠子的结界吧？」

「就是这样，要是让寒气离开建筑物，庭院树木和花坛会很可怜，所以用结界把寒气锁在适当的范围内。」

「居然有考虑到庭院，这还真是让我老实地感到佩服……顺便问一下关于结界的事，现在还能调整范围吗？可以的话我想拜托一件事。」

「当然不会没办法调整，不过你到底想做什么？」

「哼哼哼，当然是能既有趣又快乐度过发魔期的提议。」

昴将单手抵在窗户上，用另一只手弹响指头并指著天花板。当众人皆对他的动作瞠目结舌时，只有罗兹瓦尔隐隐笑著闭起单眼。

他的眼瞳中则是倒映著昴的身影。

「我不反对想做有趣的事喔。毕竟前几天的降灵术也是挺有趣的呢。所以你到底想在这间宅邸与大精灵的发魔期打什么主意？」

「策划企图写成企划，在我老家的北海道……虽然广义上算是老家，不过就是那个地方的庆典，让我们来好好浪费一下帕克多出来的玛那吧。」

昴的脑中浮现出只有在电视上看过的银白色世界庆典，那是在白色雪国才能举行的盛大庆典，而那个由来自祖先名字的庆典就是──

「第一届热热闹闹──罗兹瓦尔宅邸雪之庆典正式开始！」

「────」

昴摆出帅气神情并竖起拇指让牙齿发出亮光，他的宣言让所有人皆倒吞了一口气。

「热热闹闹的雪之庆典……」

听到这个庆典的名称，爱蜜莉雅在口中喃喃复诵并歪头表示不解。

接著──

「有需要用到……热热闹闹这几个字吗？」

──她只对这个部分采保持态度，接著便开始询问关于雪之庆典的概要。

5

经过如此这般后，企划案在一阵兵荒马乱中逐渐实现进行。

「好啦各位，第一届雪之庆典要开始啦！大家想去纽约吗～～！」

「喔、喔喔……？」

面对在众人面前展现亢奋情绪主持的昴，赞同的声音可说是稀稀疏疏。

虽然气势带不起来，但眺望眼前景象的昴并没有放在心上，而被昴找来的人们似乎也对庆典的气氛乐在其中。

目前昴眼前是成为一面雪景的罗兹瓦尔宅邸前庭，其中还有许多人……具体而言是阿拉姆村的大部分居民聚集在此。

虽然村民们皆对此种不合季节的寒风身穿收藏的防寒衣物，但表情与其说是对寒冷表达不满，莫名兴奋的情绪似乎较为显眼。

毕竟对于「庆典」这个名词，几乎没有人不会感到兴奋的。

「不过居然会想到雪之庆典，昴的创意总是会让我吃惊呢。」

从昴颈边围巾探出头的帕克如此喃喃说著，释放出多余玛那创造出白银世界的当事者，正望著祭典的参加者并摸著胡须。

「关于浪费资源这部分，可别小看活在丰衣足食年代的现代人。既然没办法隐瞒下去，不然就干脆办个庆典好好热闹一番吧。」

「我还没想过办庆典来热闹的方法呢，明明会冷到一直抱怨，可是对雪又不会有怨言，人类的想法还真是难以理解呢。」

「虽然像是天灾，不过人性就是会对下雪或台风之类的事感到兴奋。」

「嗯嗯，真是不可思议呢。」

即使听完昴的说明，帕克仍然是一副摸不著头绪的表情歪著头。

像他这种超乎常理的精灵或许无法理解，人类其实是种有时会想尝试不合理事物的生物。即使害怕大自然的威胁，但有时能够将此种心情转换为快乐，人类就是这么一种矛盾的生物。

「昴先生！麻烦继续说下去！」

「喔，对对！抱歉抱歉！」

村人如此叫著与帕克说著话的昴。顺带一提，帕克已经隐蔽身影避免被村民看见，所以外表看起来只像是昴正在自言自语。不过既然没有提及这件事，表示村民也已经相当清楚昴的个性。

「总而言之先来说明规则吧！也就是说，这间宅邸的前庭就是会场！这场雪之庆典的主旨就是使用在这里的雪或冰块，发挥各自的独特创意与创造力互相竞赛的艺术庆典！我已经准备好豪华的奖品，大家务必以得到冠军为目标！」

「喔喔～～！」

豪华奖品这几个字让身为参赛者的村民热血沸腾。毕竟是领主罗兹瓦尔办的活动，对奖品有所期待也是理所当然的事。

「那么，时间限制到火之刻结束为止！各位预备！START！」

「──？」

「啊，START就是开始的意思啦！开始开始！」

即使显得有些犹豫，但这场雪之庆典还是在昴的发号施令下揭开序幕。

村民们各自互相帮忙开始作业，但造雪像可说是需要高度注意力与灵活手艺，因此昴相当期待究竟会出现何种优秀作品。

「美景，真是美景啊。」

昴望著认真挑战制作雪像的人们，满足地从雪做的表演台跳了下来。

要做出评选的作品应该还需要几个小时。在这段时间内，昴迈步走向另一个尝试释放多余玛那的地方。

难得有这么多雪和冰，只是单纯用来办庆典热闹实在太浪费了。

「这边的作业情况怎么样？」

「喔，是昴先生啊。那边似乎办得盛况空前，这里状况也很顺利喔。」

当昴出声搭话，额头浮现汗水的村民青年团成员回过头如此回答，周遭还能够见到与他同样将冰块放上推车的团员们。

「不过话说回来，那边正在开心地玩雪，你们会不会觉得这里是个苦差事？」

「不会的，这也是为了村子好。而且听说今年的火季会特别热，我们反而感谢领主大人提出这个提议呢。」

这位剃平头的青年团长擦著汗如此回答，感觉不像是替昴等人找台阶下。昴对他的答案点了点头，对于幸好不是硬逼对方接下这个提议而松了一口气。

这位青年努力切著冰块，丝毫不理会正努力参加庆典的村民们。为了度过接下来的火季，他们都是自愿出来将冰块运进冰室。

冰块是暑期保存食粮与单纯去除暑气不可或缺的必需品，在这个还没有发展出制冰技术的世界，冰室可说是具有相当程度的重要性。

时常进出村子的昴，还记得曾经听人说过这段话。

「不过苦工就是苦工，其实原本我也得来帮忙的……」

「不不，昴先生已经很照顾我们了。再给您添麻烦会遭天谴的，而且还让我们看了这么棒的东西。」

「很棒的东西？是什么？」

对于没有头绪而歪著头的昴，青年团长将视线别开。沿著他的视线跟过去一看，便能见到雷姆与拉姆在前庭忙碌奔波的模样。两人负责担任雪之庆典的管理委员，冰季的女仆装依然是令人感到新鲜且可爱。

「光是能看到她们的模样就感激不尽了。昴先生，我说的没错吧？」

「……嗯，也许是这样没错。如果这样能让你们满足就好了。」

对于团长满足的话语，团员们也深深地点了点头。确认这是整体团员的共识后，昴与团长坚定地握了握手并理解他们的想法。

见证过他们的决心后，昴再度回到雪之庆典的会场。虽然就连昴都不太熟悉雪，不过只要四处给予适当建议……

「啊～～是昴耶！」「找到昴了！」「尝尝纯白色的恐惧吧！」

「喔喔！就算这么冷，你们还是很有精神嘛！」

当昴一回到会场，宛如脱缰野马般兴奋的孩童们冲了出来迎接昴。他们那热呼呼的身体冒出蒸气，并且淘气地四处嬉闹。

「哇哈哈～～！是雪耶！」「呀哈哈～～！是雪！」「噗哈哈～～！是雪！」

孩童们在雪堆上溜滑或躺卧翻滚，尽情地享受著白银色的世界。那深受白雪吸引的模样让昴回想起童心，但他并没有露出笑容，只是深深点了点头。

「不过他们总有一天会发现，其实自己才是被雪玩弄的一方……」

「啊，昴看起来好像没事做。快点过来看！这是我用雪做的喔！」

对于昴刻意耍帅的肤浅模样，走到他身旁的少女纯真地将他拉回现实，是村子中令昴最为期待的未来美少女佩特拉。

佩特拉的掌心上能够见到用雪做成的兔子。

「喔喔！是雪兔！原来这个世界也有做雪兔的文化吗！」

「嘿嘿……很可爱吧，有没有做得很棒？」

「很棒很棒！好，那么我再来做点改良，仔细看喔。」

「──？」

佩特拉微微歪著头表示不解，昴从附近捡来树叶与小石头装在少女制作的雪兔上，转眼间就完成了眼睛与耳朵。

一见到此种景象，佩特拉的神情顿时变得相当开心。

「哇啊～～！好厉害！昴好厉害喔！居然变成兔子了！」

「嘿嘿。我就说吧？看你这么开心也让我嗨起来啰！好，既然这样就来继续增加威力吧！不只是眼睛和耳朵，还要加上尾巴与翅膀，还有飞弹、变形合体性能、驾驶舱和履带……」

「啊……等、等一下……」

昴并没有将佩特拉的话听进耳中，径自将手上的雪兔胡乱改造一通。

数分钟后，雪兔已经失去一开始的模样，变成只为了伤人的武器「飞行强攻型重火力决战兵器YUKI-USAGI」。

理所当然地，此举让稚嫩少女相当不高兴。

「嗯……女人心海底针，女孩子的心情还真难捉摸……呸呸……」

昴将砸在脸上的雪球吐出来，目送著佩特拉逐渐远离的背影离去。看来此种点燃少年情怀的作品不太适合女孩子。

「比起超级机器人，佩特拉比较喜欢拟真机器人吗？」

「唔～～感觉两边好像都不太对呢。」

「不不，下结论还太早了。下次用拟真机器人的路线试试看吧。」

确定会再度被佩特拉砸雪球的未来后，昴在展场四处观赏著已经逐渐成形的雪像作品。虽然大多是首次制作而有些笨拙的雪像，不过仍然是众人齐心协力做成的优秀作品，让昴可说是难以评比高低。

「不过，感觉临摹的概念都比较偏向现实有点可惜。应该是没有吉祥物的概念吧，大多都是城堡和动物……喔？这个做得很不错嘛！」

「喔喔！谢谢昴先生称赞！这个沃尔加姆可是小人的自信作品呢！」

「这么冷就忘了之前曾经烦恼过的事啦！这实在很难笑出来耶！」

那是前阵子曾经让宅邸与村子濒临前所未见窘境的魔兽雪像，当时的恐惧与紧张仍然记忆犹新，浮现出鸡皮疙瘩的原因并不是只有寒冷。

「我也很喜欢重视震撼感的作品，对这种勇于尝试的心态也给予正面评价，不过倒是对审查员的心灵创伤思虑不周。所以我给七分！期待下次的作品！」

当昴评论过雪做的沃尔加姆后，身为制作人的男性带著苦笑回答「评分还真严格」，帕克则是对这段话用尾巴搔了搔昴的后颈。

「啊嗯，什么事？」

「关于雪之庆典的计分方法，是由昴和谁负责的？」

「是我和罗兹亲，还有蒙著脸的村长负责担任评审。要是被发现评审曝光，就有可能会出现贿赂或私下收买排名的家伙。在竞相展现艺术的庆典上，我坚决不允许这种操控排名的骯脏事出现。」

「有那么想得到豪华奖品的人吗？」

「有可能喔，毕竟那可是我精心挑选且世界唯一的豪华奖品喔。」

姑且不论金钱方面的价值，只有稀少度昴能够拍胸脯保证。得知奖品是昴自掏腰包后，帕克不禁露出佩服的惊讶表情。

「明明不是昴的问题，没想到昴居然会这么大方呢。」

「看爱蜜莉雅酱那么困扰，而且你不是也在烦恼这个问题吗？照常理说都要帮忙才对吧。」

毕竟没有付出多少劳力，而且昴本身也对庆典乐在其中，这点程度的互相扶持可说是易如反掌。昴对此并没有多加犹豫，要说人情债昴反而欠得还比较多。

「是喔……昴这点对我来说还满那个的耶。」

「你的代称词太多没办法让人听懂啦，那个是哪个啦……唔喔。」

回应帕克带著意有所指笑容说出的话后，昴突然停下脚步。发现昴停了下来，在正面作业的少女便开心地拍著手呼叫。

「啊！是昴呢！请看看！这是雷姆与姊姊共同合作的雪像！」

「雷姆和大姊不只是帮忙还有参加啊，真是出乎我的意料。」

带著灿烂表情的雷姆用手指著自己身旁的作品，身著更厚重衣物的拉姆则是在雪像旁将手挽在胸前，一见到昴便不屑地哼了一声。

「哎呀，毛，没想到你这么厚颜无耻地被我们的艺术气息吸引过来了呢。」

「那种感觉像飞蛾扑火的语气好像怪怪的，不过我还是来看看了。拉姆，你怎么会想参加这个冷得要命的庆典？原本看你好像连帮忙都不太愿意。」

「这已经获得罗兹瓦尔大人的许可，而且雷姆他们都在宅邸外玩雪，你的意思是只有拉姆会躲在被窝里贪睡吗？」

「还真是不必要的攻击意识，不过这段发言的意思应该是不想被排除在外吧？」

拉姆的不老实发言让昴垂头丧气，雷姆便悄悄走到姊姊面前，然后与冷得鼻头发红的姊姊牵起手。

「是雷姆硬邀姊姊出来的，虽然姊姊说玩雪很幼稚，可是雷姆就是无论如何都想和姊姊玩……」

「大姊，让妹妹不惜说到这种地步，你都不会有罪恶感吗？」

「有种能感觉到雷姆满满爱情的优越感，羡慕吧。」

要说赢已经豁出去的对手可说是相当困难，于是昴早早放弃突破拉姆的歪理，将视线转向姊妹合作的雪像。那个用白布盖著遮掩全貌的雪像约有人类等身大，由雷姆的灵巧手艺来看，或许会是相当优秀的力作。

「这是拉姆与雷姆结合两人力量、技术与姊妹爱的自信作品喔。」

「是的，在姊姊指示与雷姆的微薄之力下，这应该是最优秀的作品。」

「刚才好像隐约透露出大姊只在旁边看的真相嘛！……所以作品名称是？」

「是的，名字就是『伟大的昴瓦尔大人像』！」

「光听名字就觉得已经完蛋了！！」

不理会昴的呼喊，雷姆径自将盖在雪像上的布掀开，而露出的雪像呈现出一名男性的样貌。是个能够看出对细节部分颇为讲究的优秀作品。

细部做得相当精细，精密部位也有很高的完成度。单纯以雪像而言，具有技压全场作品的潜力，但最大的唯一缺点就是雪像没有彻底锁定临摹对象。

「姊姊想做罗兹瓦尔大人，雷姆想做昴，所以我们的意见出现分歧了。」

「这就是妥协后得到的结论。」

「感觉好像有让步又没让得很彻底！」

听完两姊妹的制作秘辛后，让昴犹豫著该如何评论眼前的雪像。虽然两姊妹一起创作的态度相当动人，但没想到成果竟然是这个颇具亵渎感的雪像。

协力作品『伟大的昴瓦尔大人像』猛然一看似乎是临摹罗兹瓦尔，但也能够看出昴的面容，此种难以描述的造型完全颠覆了观众的认知。

「哎呀呀～～？你们聚集在这里做什么呢？这是……」

当昴等人在昴瓦尔雪像前品头论足时，四处在展场评分的罗兹瓦尔前来会合。但一见到两人制作的雪像，难得能够见到罗兹瓦尔绷紧神情，嘴边那游刃有余的笑容也随之消失，并且游移著目光思考评语。

「啊……罗兹瓦尔大人，很抱歉让您见到丢脸之处，不过还请您观赏呕心沥血的作品。」

「这是姊姊与雷姆的协力作品。虽然是一家人，但仍然希望大人能给予不失偏颇的评语。」

见到评审齐聚在此，拉姆与雷姆一同表达希望能评断作品。虽然拉姆一如往常地带著充满自信的模样，不过连谨慎发言的雷姆都能莫名感觉到满满自信。

表示她们对这个雪像怀著高度期待，然而──

「那么，很可惜只有五分。」

「还有时间反悔喔～～」

「不会反悔了啦！就是这个分数！希望你们以后能继续钻研技术啦！」

「怎么可能……！？」

拉姆一脸愕然地看向罗兹瓦尔，但罗兹瓦尔也是摇了摇头举起右手。他只竖起四根指头，给的分数比昴还低。

顺带一提每个评审都有十分，总计三十分就是最高满分。

「虽然做得还不错啦。不过该怎么说呢……看了会让人有种毛骨悚然的感觉呢。」

「创意应该没有问题才对……果然是毛的成分太碍事了。」

「不可能是这样！是姊姊与雷姆的理想互相冲突才会搞砸的！一定只是因为时代还没跟上而已！」

听完罗兹瓦尔的短评后，拉姆与雷姆两姊妹开始讨论反省，不过如果那些话就是反省内容，总觉得下次还是会做出难以言喻的作品。

「该不会只有被当成临摹对象的我们觉得奇怪吧……」

「啊！找到昴了！我和碧翠丝也有偷偷参加喔，可以的话要不要来看雪像……哇，这是什么？好奇怪的雪像喔……」

「也是啦～～果然不是我们的问题嘛～～」

连正好出现的爱蜜莉雅都对『伟大的昴瓦尔大人像』表示抗拒。

表示这是全人类共通的看法，表示要追上那种艺术的时代是永远不会到来了。

总而言之，第一届雪之庆典就这样持续进行下去──最后是由佩特拉夺得优胜。

优胜作品就是总计获得二十八分的『飞行强攻型重火力决战兵器YUKI-USAGI』。

结果就是由这位坚强的少女趁乱夺下胜利。

6

「明明那么努力，只有九分怎么想都很奇怪……」

「这场活动对莉雅和贝蒂来说可能还太难了，该怎么说呢……你们两个的雪像都很难拉高艺术分数。」

在雪之庆典结束且已收拾完毕的前庭，爱蜜莉雅与帕克正在说著话。

爱蜜莉雅气呼呼地鼓著脸颊，似乎对自己眼前制作的帕克雪像很不服气。旁边还能见到碧翠丝制作的帕克，分数分别是九分与七分……由评分结果来看，希望各位能发现关于省略说明详细细节的原因。

雪像可说是太过前卫，几乎已经不是人类能够达到的领域。

「不过昴总是只对奇奇怪怪的事相当瞭解呢。如果不是在艾利欧尔大森林附近，是不可能办成雪之庆典的。」

「这是在很少看到雪的地方才能办成的庆典。如果住在没有心情玩雪的地区，绝对不会想到会办这种庆典的。」

「是这样吗……嗯，也许吧。」

爱蜜莉雅对帕克的话点了点头，四处绕著观赏留在夜晚展场的雪像。

多亏昴提议举办这场释放发魔期的雪之庆典，帕克的欧德也显得稳定许多。这几天以来的强烈寒流，到了明天应该也会减缓许多。

「不过如果这样，这些雪像明天一定也会融化的。明明有这么多雪像，真是太可惜了。」

「雪就是这样。没有能够永远留下形体的事物，就是这么单纯而已。」

爱蜜莉雅从帕克的发言中莫名察觉到些许不协调感，但她并没有特别说出口。只是途中停下环视雪像的脚步，抬头仰望著布满灿烂星斗的夜空。

在冷冽清澈的空气中，头上能够见到一望无际的漫天星空正俯视著这些雪像。

「不只是莉雅和贝蒂，宅邸的那两姊妹没有得到优胜也很可惜呢。」

「没办法，因为那个女孩子做的雪兔真的很棒。罗兹瓦尔和村长爷爷都是赞不绝口……连昴都是那么兴奋，没想到现在居然会这么安静呢。」

「对于这点我不予置评，不过倒是有点在意豪华奖品是什么呢～～」

「我也是，听说那是昴故乡的……我忘记叫什么了。玉米汤？好像就是这个名字。」

雪之庆典的优胜奖品是昴携带的神秘礼物，上面有著从未见过的字样与图案，还有摸起来奇特触感的袋子──里面似乎是装食物，不过感觉起来有些诡异。

顺带一提，同时间村里的佩特拉吃到奖品『玉米浓汤味饼干』，对此种天降美味可说是赞誉有加，不过这又是另一段故事了。

「这次的事如果一开始有向昴商量，说不定就不用像之前那么瞎操心了。」

「说得也是呢。不过再怎么说，我可不想把孩子教育成凡事靠别人。就算没办法解决，也要自己努力到找出方法为止。知道吗？」

「好～～我知道了。」

爱蜜莉雅嘻嘻地笑著如此回答，帕克则是说著「很好」并摸了摸胡须。之后两人经过一阵短暂沉默，爱蜜莉雅突然开口说道：

「帕克，还记得庆典最后昴说了什么话吗？」

「──明年发魔期的时候再来办雪之庆典吧。平常应该都会讨厌这种事，不过那孩子感觉又会搞出庆典的热闹气氛呢。」

「昴的那种个性……其实我觉得还满那个的。」

「对啊，我也觉得很那个呢。」

要是昴在现场，说不定又会对两人只用代称词自顾自说话闹著别扭。这是长时间相处并宛如家人般的关系才能如此沟通。

「明年啊……那么久的事，我不知道会变成什么样子呢。」

「莉雅想做什么都可以，我觉得如果能像他说的一样就好，到时候能不能真的做到又是另当别论了。」

「帕克反对办雪之庆典吗？」

「没有喔，其实我也玩得很开心，看莉雅也很乐在其中……不过如果直到明年都待在莉雅身边，我不知道昴还能不能那么幸福。」

「────」

帕克的话语让爱蜜莉雅静静地屏起气息。

爱蜜莉雅处在相当沉重的立场，无法随心所欲地做出轻率判断，一年后周遭环境应该也会有剧烈变化。

将昴那位善良的少年牵连进来，让爱蜜莉雅感到相当内疚。

「不论是腹部的伤或被魔兽咬伤，那孩子留下的伤势都是莉雅行动后造成的结果。虽然我觉得你应该不会忘记，不过还是得牢牢记住才行。」

「──嗯。」

帕克的声音听来虽一派轻松，但这番话语绝对不会是溺爱爱蜜莉雅。

爱蜜莉雅点了点头，帕克则是默默地洗著自己的脸，然后他望著爱蜜莉雅身旁的雪像说道：

「不过，如果明年雪之庆典能办成就好啰。」

「────」

「如果明年能够举办，表示我的玛那又能多到出现发魔期，庆典唱的歌也只有昴才会呢。」

要是明年能够顺利举行雪之庆典，表示爱蜜莉雅又平安地过了一年，也代表菜月•昴继续留在这间宅邸。

「嗯，说得也是──我也希望能这样。」

对于帕克出乎意料的话语，爱蜜莉雅频频点头并露出笑容。爱女的笑容让帕克满意地拨动胡须──并且将担忧藏回心中。

明年是否能再度举办雪之庆典？接下来的一年是否能保护顺利举办庆典的条件？

不论是爱蜜莉雅与昴平安无事，还有帕克自身的平安与其余原因──

短短数个月内出现了许多巨大变化，之后不知道又会有什么样的事。

「帕克？怎么了吗？」

面对帕克保持沉默的模样，爱蜜莉雅歪著头表示不解。而帕克随即一如往常地对爱蜜莉雅竖起耳朵。

「嗯，没事。我只是在想，从明天开始又要变热了。」

「这么说来好像是这样，说不定又会被昴和拉姆抱怨呢。」

爱蜜莉雅并没有发现帕克的担忧，只是一副理所当然地担心著即将到来的明日。

对于爱女老实率真的心情，帕克则是不发一语地持续摇著尾巴。

──只是保持著沉默，思考著到明年雪之庆典为止的一年究竟会发生什么样的事。

** 『酒精之乱』

1

罗兹瓦尔•L•梅札斯边境伯的宅邸中，有许多没有使用的设备。

这栋宅邸位居远离都市的山林间，在几乎能够媲美小城的宽敞占地中由三栋建筑物组成。

本馆具备餐厅、待客室与大浴池等等主要设备，宅邸居民与仆人的房间、访客用客房聚集于东馆，而西馆则是较多具有各种功能的多样设备。

而在其中，西馆使用频率较其他建筑物明显低了许多。虽然美其名是多功能，但正确说来是功能太过分散的设备较为实际。

包括不会办舞会的舞厅、聚集未装饰绘画与美术品的仓库、以及没有价值放进碧翠丝禁书库的书籍库等等，没有使用的设备实在太多了。

因此虽然西馆有排进轮值打扫的行程，但在日常生活是完全被遗忘的建筑物。在西馆最常进出的部分，是与本馆相连的走廊置物柜，由此也能窥得西馆的寂寥程度。

「所以像这样三天一次整个清扫过实在很没成就感，这方面大姊觉得呢？」

这时昴已经脱掉制服上衣并卷起袖子，用单手拿著撢子如此说道。

昴用手挥开飘散的尘埃并皱起眉头。不论怎么仔细清扫，在空中飞舞的尘埃都会无穷无尽出现，简直是让昴恨之入骨的敌人。

「真是的，这些灰尘到底是从哪里生出来又想飘去哪。大姊你觉得呢？」

「唉……别再说那些傻话，动手不要动口。不管毛怎么说，都得万全回应罗兹瓦尔大人的要求，这就是拉姆们的工作。」

「好好，我知道了啦。那只好乖乖努力……喂喂！」

说出那番冠冕堂皇的话并朝昴的屁股踹了一脚，昴则是对本人发出责难声。只见冷冷回应的拉姆正优雅地跷著脚坐在房间角落的木箱上。

她的手上当然没有拿著拖把与抹布，还用手掩著嘴巴打了个哈欠。

「我想说你难得没有任何抱怨声乖乖做事，结果居然是这样喔！我们两个的战力加起来只能算是半人份，要是变成四分之一就做不完事情了啦！」

「连自己的无能都不感到羞愧，表示这个人已经完蛋了……毛，你真是个没用的家伙。」

「可以看看现况再发言吗！？以客观角度来看是你还是我没用啊！？」

「只是打扫不使用的仓库，稍微偷懒也不会改变结果的。」

「刚才那个说要万全回应罗兹瓦尔大人要求的拉姆去哪了！？」

昴对那大言不惭反悔的模样翻著白眼，拉姆则是摆出一副事不关己的表情发出叹息。

罗兹瓦尔宅邸的各项杂事，是由身为仆人的昴、拉姆与雷姆姊妹三个人均等负责。但宅邸有八成机能是依靠雷姆才得以运转，昴与拉姆两人只负责剩下两成──为了解决这些事还是让昴每天伤透脑筋。

对于劳动力无法独当一面的两人，工作只有清扫整理西馆未使用的仓库，内容可说是简单明瞭到让人提不起干劲。

目前才刚开始打扫十分钟，昴与拉姆的士气已经完全降到最低点了。

清扫宅邸基本上是每天轮流清扫三馆，由于西馆三天前才清扫过，因此不算很脏乱也更加削弱想清扫的干劲。

「不过拉姆大姊说的也有道理。虽然有用撢子，不过感觉只是把灰尘挥起来，根本没有半点成就感……哈啾！」

昴以斜眼望著坐在木箱上跷班的拉姆，用撢子扫起的灰尘让他打了个喷嚏。聚集的灰尘瞬间扬起，撢子前端将隔壁柜子的物品勾倒，让昴不太甘愿地蹲下身将掉落地面的不知用途物品捡了起来。

「自己弄脏又自己整理，这份工作简直是越弄越糟……喔？」

在捡起物品的途中，昴突然发现地面有条难以发现的缝隙。他用手沿著地面确认过后，看来那是个地面下方的收纳柜木盖。

「拉姆，地上有个隐门，你知道里面有什么吗？」

「……我不知道。毛，别去乱动，说不定一打开的瞬间会有虫子飞出来。如果你坚持要开，等拉姆离开把门上锁再说。」

「为什么要上锁？而且已经来不及了。」

昴发现收纳柜的把手，一口气将地面的盖子掀了起来。虽然拉姆的话让他闪过不好想像，但好奇心还是赢过恐惧。

随后拉姆立刻跳下木箱并并冲到房间门旁，昴对她那准备逃走的俐落动作苦笑以对，战战兢兢地窥视著地板下方的收纳柜。

「──喔喔？」

然后吃惊地张大嘴巴与眼睛。

2

「……就是这样，这是在地下收纳柜找到的物品。」

恭敬地行了个礼后，昴毕恭毕敬地将眼前木箱沿著桌面推了出来。

在西馆仓库忘记当初目的进行探索后──发现了令人出乎意料的物品。

目前昴正自傲地对坐在办公桌的罗兹瓦尔报告这件事，一反那奇装异服与特立独行的说话口吻，身为领主的他在白天可说是相当忙于事务。

但当昴毫不忌讳地打断作业，别说是显得不开心，罗兹瓦尔反而像是很高兴地缓颊一笑。

「原来如此啊。话说在很久以前，我听说过在别馆的某处有个酒窖，没想到在西馆的地下……会找到这种东西呢。」

由摆在桌面上的木箱，从中能够见到看似昂贵的酒瓶与木屑一起收藏在内。

昴在仓库见到的地下收纳柜，就是保管无数这类酒瓶的隐藏地窖……简单说就是个小型的酒窖。

但比起酒窖这个名词，昴对罗兹瓦尔发言的其他部分狐疑地歪著头。

「嗯？你说别馆？可是这些酒是在这间宅邸的地下发现的呢？」

「喔，这很简单啊。这间宅邸只是用来作为爱蜜莉雅大人参加王选的据点。原本是我家的别馆，梅札斯家的本馆是位在更东边。哎呀，不过只要我在的地方就是梅札斯家的宅邸，区别起来也没什么差别就是啰。」

「这么大的房子居然是别馆，那本馆到底……算了，感觉问出来会很可怕还是算了。总而言之，既然你说没有头绪，表示那个地下酒窖不是罗兹亲的兴趣吧。」

「虽然现在是我当家，不过在那之前是我父亲和祖父的房子呢。地下的酒窖应该是祖父或祖母做的好事，曾经听说他们都很会喝酒喔。」

昴对嘴唇涂成紫色露出笑容的罗兹瓦尔皱起眉头。他说到自己祖父的事彷佛事不关己，罗兹瓦尔则是对昴的疑问闭起单边眼睛。

「因为我家代代都很短命，我没有见过祖父，连与父母度过的时间也不算太长呢。」

「呃……抱歉，我没有过问的意思……不过原来还有这种事啊。」

在忙于宅邸事务让昴差点忘记，这里毕竟还是个异世界，平均寿命的常识与昴原先世界应该有很大的差异。

例如长寿种族与存在魔法等等，与现代医学无法单纯拿来比较。

「……所以呢？我只是想报告这件事才拿过来，你祖父留下的收藏品要怎么处理？还有很多的量躺在地下酒窖喔。」

「嗯……说得也是呢。让那些酒放在地下室当成地基也挺浪费的──顺便问一下喔，昴你会喝酒吗？是不管多少都能豪饮？还是光是闻到酒味就会满脸通红说著『今晚不想回家……』之类的人呢？」

「原来这里也有据说会在联谊出现的发言啊……再来就是我没有积极喝过酒，喝酒还是等到二十岁以后吧。」

「二十岁？那还真是有耐心呢。」

面对罗兹瓦尔的问题，昴则是皱起眉头如此回答。

实际上昴并没有说谎，在原本世界未成年的昴并没有特别沾酒的理由。顺带一提，他也没有参加过联谊。

不论是酒、菸或是女人，菜月•昴至今皆是过著与前述三者毫无缘分的生活。

「哎呀呀，还真是令人意外呢。由昴的个性来看，我还以为绝对会对这种嗜好品出手呢。」

「虽然我大概能理解你怎么看我，不过很可惜并没有。呃……其实是有一次曾经拿老爸忘记熄灭的菸拿起来抽抽看啦……」

「然后呢？」

「一叼起菸的瞬间老爸就回来，还被狠狠揍了一顿。老妈也用『抽菸不会长高』的另一种方式把我骂了一顿……总之对那个有阴影就是了。」

如果交到坏朋友说不定会学会喝酒或抽菸，幸好别说是坏朋友，昴连好朋友也没交到，因此并没有接触这些东西的机会。

「就算想走歪路，或许该说连走歪路的方法都不知道……呵呵，真是太好笑啰。」

「不好意思打扰你回想往事，意思就是把这个当成给你的奖励也不会太开心吧。」

「应该是这样吧。其实之前曾经被某个块头很大的老头子请喝过酒，不过只有种喉咙、肚子和头都快要烧掉的感觉而已。还有就是……」

对于理所当然地想将酒当成礼物的罗兹瓦尔，昴指著箱子继续说道：

「这边在我这个岁数喝酒真的没问题吗？我刚才也说了，我是还没满二十岁的未成年人，没有监护人同意是不能逛色情网站的喔。」

「我听不太懂那是什么，不过感觉就算有监护人也不能偷看喔。先不说那个，在露格尼卡只要十五岁以上就OK啰。」

「喔喔，你用的还真顺口……」

正确地用出昴传来的「OK」后，罗兹瓦尔则是继续说道：

「而且啊，虽然王国法有规定，不过每块土地是以各自的领法为优先。也就是说，这一带的领法是由我决定想怎么做就怎么做喔。」

「哇～～真是滥用职权，只要用领法判我无罪……不对，我已经超过十五岁了，照理说在王国法也是无罪就是了。」

即使有法律保障，但仍然不会改变收到酒当礼物并非很高兴的事实。

这也是当然的，毕竟昴并不知道酒的味道或是有何优点。即使如此，拿去换钱似乎又对赠送作为奖赏的罗兹瓦尔不太好意思。

「不然绑个蝴蝶结放在房间角落当装饰好了……等二十岁后再隆重地打开当纪念，怀著那股感动继续迎向未来之类的。」

「真是个漫长的计划，在睡前、工作结束后、洗完澡或是用完餐的时候……又不用这么刻意寻找喝酒的机会，应该不是需要延后那么久的事吧。」

「听说硬逼不会喝的人喝酒叫做灌酒，小心这是有可能会吃上官司的。而且话是这么说，感觉罗兹亲也没什么在喝酒吧？」

「以前还算满常喝的，最近这几年突然减少很多。哎呀，不过在宴会上还是会好好喝几杯，我也知道自己的酒量大概到什么程度啦。」

罗兹瓦尔耸了耸肩如此回答。虽然他表达出不太喝酒的态度，但从模样来看飘散出一股压倒性的酒豪气息，实在无法想像他喝醉酒的模样。

「不过，我是有点在意自己酒量如何。」

在这之前昴对此没有任何兴趣，但当话题都在酒上打转后，他突然在意起自己的酒量极限。这就像是在测体能时测量握力时的感觉。

如此思考后，不只是对自己，昴甚至开始有些在意爱蜜莉雅与雷姆的酒量如何。

但要是没有契机，实在没有能够确认酒量的机会。

「对了！宴会！罗兹亲，你刚才也说过自己会在庆祝宴会上喝酒吧？」

「嗯？是啊，我是这么说过。在值得庆祝的宴席上，我也会喝到舒服醉倒的地步，毕竟我也是个人嘛。」

「也对啦！在那种宴席上也会不得已跟著喝个几杯嘛！」

「呵呵呵，真是的──把我灌醉想做什么事呢？」

「别说得那么难听，我的目标不是罗兹亲啦！！」

昴对带著意有所指眼神的罗兹瓦尔如此吐槽后，便拍了一下手露出邪恶表情──不，只是眼神比较邪恶而非坏人脸。

然而，那是昴突发奇想时的惯例神情，对于此种模样让罗兹瓦尔的双眼浮现出期待神色。

虽然不知道是否能够回应期待，但昴还是堂堂将计划说了出口。

「只要办了那个庆祝宴会，应该就能把地下的酒拿到酒宴上吧？」

「──原来如此。反正那是个有就像没有的酒窖，那边留下的酒要怎么使用，就给你某种程度的权限自由处理吧。不过话说回来……」

「话说回来？」

「你居然想趁著宴会看看爱蜜莉雅大人与雷姆衣衫不整的模样……没想到昴也会想出这么像个男人的企图呢。」

「我没有那个意思啦！别说那种会让我看起来那么下流的话啦！」

「不不不，其实我不讨厌你这个样子喔。」

「我就说不是了嘛！」

虽然昴原本完全没有这个意思，但就在稍微浮现出下流想法的情况开始策画宴会。

3

「就是这样。我想出了一场类似赏花的宴会，请各位踊跃参加！」

「赏花？」

一造访房间，爱蜜莉雅便对昴的突然发言歪著头表示不解。

今天爱蜜莉雅将银发绑成马尾，配合一身长长裙襬的装扮。虽然她将手指抵在樱花色的唇瓣上，但她似乎对这个突如其来的提议没有感到惊讶。

从此种反应能够看出，她已经习惯昴的突发奇想了。

「我没有听过什么赏花，不过感觉会很有趣呢。赏花……赏花啊……」

「没错。在我老家那边只要一度过冰季，就会有叫做樱花的粉红色花朵四处绽放。在那个时期的樱花树下热热闹闹地喝酒唱歌……那就是赏花！」

「咦？怎么感觉好像没看到什么花……」

「那就是赏花时绝对不能提出来的禁忌，总之那只是用来热闹一番的藉口啦。」

昴对她那揭露赏花本意的发言苦笑以对，然后将话题做出结论。

总而言之，发现酒窖获得奖赏的昴提议全宅邸成员一同赏花──应该说是藉著赏花的名义举办酒宴。

与其说是想要喝酒，昴比较想看看其他人喝过酒的反应。

尤其是爱蜜莉雅，很有可能会在喝酒后突然变得性感许多。要是真的变成这样，不就会增添她更加危险的魅力了吗？

「把酒和吃的东西带过来，把美丽的樱花当成佳肴享受，就是这次赏花最大的目的！绝对不会是我想看爱蜜莉雅酱酒后乱性的模样喔！」

「啊，我知道了。昴真是的，这样不行喔。」

「咦！？什么！？没想到我的计划会在这个时候就曝光！？怎么会！」

「小孩子是不能喝酒的，这样会没办法长高喔。」

「居然是跟我家老妈同样理由！？还有我已经不是会触犯王国法律的小孩子啰！今年已经要十八岁了！罗兹瓦尔也已经同意了！我可是个大人了，大人！」

「我觉得大人应该不会这样吵吵闹闹。不过原来昴已经十八岁了，真是让我意外……我还以为会更年轻呢。」

昴被似乎在某处听过的理由指责而大声嚷嚷，爱蜜莉雅则是对他微微露出苦笑。她多补充的那句话，正好指出了昴的长相并没有与岁数相符的稳重感。

「听说日本人在外国人眼中看起来比较稚嫩。顺便问一下我看起来像几岁？」

「十二……不对！十三岁！大概十三岁左右！」

「那不是比菲尔特还小嘛！还有后面重新修正没有什么差别啦！」

说起来这个判断与阿拉姆村的孩童没有太大差异。虽然昴反而想问问那些孩子在爱蜜莉雅眼中看起来像几岁，不过再问下去会没完没了。

「唉，真是累死人了。而且一直把我说得很幼稚，那爱蜜莉雅酱又怎么样？是很会喝酒吗？可以从菜单头喝到尾吗？」

「抱歉，我不太懂这是什么意思。」

虽然罗兹瓦尔给人一种酒豪的印象，但爱蜜莉雅的酒量完全无法想像。有可能是很会喝，不过也有不会喝酒的印象。

对于眯起眼睛刺探的昴，爱蜜莉雅只是支支吾吾地说著「这个嘛……」

「虽然我刚才说了那些话，不过我也没有喝过酒。啊，不过我已经是能喝酒的年纪了，不是十三岁喔。」

「这点我没有怀疑过，而且要是爱蜜莉雅酱只有十三岁，我就会犯罪了。」

「为什么昴会犯罪？」

「那是因为爱蜜莉雅酱可爱到会让人想犯罪……」

「而且说到酒，帕克也说不能喝喔。」

「明明有听见还故意视若无睹喔！？」

昴对于此种全新的置若罔闻法大表惊讶，但相较之下爱蜜莉雅没有任何反应，取而代之的是她颈边项炼有另一道声音打断对话。

「──这是当然的，酒是坏大人喝的饮料。莉雅永远都是我的可爱女儿，所以不需要去沾那种东西。」

随著这道过度保护的话语，由项炼溢出的光点形成小猫的形状。现出身影的小猫精灵坐在爱蜜莉雅肩上，用肉球不停按压著她的脸颊。

「我不允许把我家的孩子带坏，我会把莉雅面前出现的酒全部喝光。莉雅是不会随便送给你的喔，去去。」

「啊，你也想参加和喝酒啊。」

见到帕克不停挥著拳的模样，虽以爱蜜莉雅的监护人自居却似乎很想喝免费的酒，总之昴也对他似乎赞成赏花而松了一口气。

「既然帕克要参加，爱蜜莉雅酱应该也没问题吧？」

「咦？嗯，我没问题。虽然帕克说不能喝酒，不过我也很期待一边赏花一边吃好吃的东西。可是大家都能配合吗？」

「原本就是我和罗兹瓦尔一起计划这件事，所以罗兹瓦尔OK。只要罗兹亲可以拉姆就没问题，至于雷姆还得请她帮忙准备料理之类的事，所以得尽可能诚恳地拜托她。料理我也会帮忙准备。」

当初昴连蔬菜剥皮都是经历一番苦战，但多亏天生的小聪明，让他最近也能开始帮忙料理。与许多年来靠著蒸蕃薯而停滞成长的拉姆可说是截然不同，另外讲师的积极度也有差别。

「雷姆和昴一起做菜好像总是很开心呢。对了！那我也来帮忙做菜好吗？毕竟之前昴还怀疑我的厨艺嘛。」

「好像是有这么回事……不，那个疑虑还没洗刷干净就是了。」

「唔，昴还真坚持呢。之前那个饭团不是做得很好吃吗？」

「是只有味道而已，不过艺术分实在很难给高分呢。」

以前昴有事上山时，爱蜜莉雅曾经替他做了便当──虽然内容只是很简单的饭团。先不论形状，尺寸可说是异常庞大，光是将那个约有孩童头部大小的饭团吃完就得耗费许多体力。

不是味道而是拿捏方面的问题，这是昴对爱蜜莉雅厨艺的评价。

「哼，既然这么说我知道了。我要在赏花的料理上让昴吓一跳，之后再说道歉都来不及了。」

「之前我已经被吓了很大一跳了！不过还是满期待的喔。」

对于气呼呼的爱蜜莉雅，昴则是漫不经心地回以傻笑。想对昴回以颜色的爱蜜莉雅颇为不满，不过她的料理还是让昴期待得无法自拔。

「所以呢？赏花要选在什么时候！」

「想到的日子就是吉日！不过再怎么说今天实在还没准备好，不过要是打铁不趁热很快就会退烧，所以与大家说过之后应该是过几天吧。」

具体行程应该会配合宅邸最忙的罗兹瓦尔，在他没有离开宅邸的那晚就是举行赏花之日。

「既然名目上是赏花，那果然还是选在森林的花田最好吧？原本如果有樱花就更好了，不过时间与世界都不太一样啊。」

「看著很多花喝酒啊……嗯，感觉还真风雅呢，不过要在森林赏花会有点小麻烦喔。」

「小麻烦？」

对于烦恼著会场的昴，帕克竖起尾巴如此插嘴说道。这只小猫用手洗著脸，对于昴的疑问说了声「其实啊」并继续说著：

「离开宅邸贝蒂就不能参加了，那孩子的任务是不能离开这间宅邸喔。」

「呃……碧翠子吗？虽然我不太懂原因，不过稍微偷偷溜出来应该没关系吧？应该说连这间宅邸的负责人都同意了耶？」

「虽然我知道昴想表达的意思，不过贝蒂在禁书库并不是罗兹瓦尔的命令，所以那孩子是不能离开宅邸的。」

面对帕克颇为强硬的语气，昴也被说服保持沉默。

对昴而言，窝在禁书库的碧翠丝与昴之间有著难以言喻的关系，不过要将她排除在外出去赏花也让昴颇为内疚，这点是无庸置疑的。

毕竟那位少女总是不肯老实表达心情，要是她得知除了自己以外的人出去赏花，肯定会拖拖拉拉地窝在房间胡思乱想。

「呃……碧翠子真是有够麻烦的！……咦？我怎么记得她曾经到村子来帮我疗伤？那是怎么回事？」

「那是例外中的例外。是我去帮忙求情的，她听到的时候还很惊讶呢。」

因为那是极为紧急的状况，或许该说是碧翠丝佛心大发。不论如何，生死关头与游戏实在是天壤之别。

「如果碧翠丝无法参加，那赏花就要取消了……没错吧？」

面对没有好方法而保持沉默的昴，爱蜜莉雅也是看似惋惜地垂下视线。见到她那长长睫毛下的眼眸露出寂寞神情，让昴的内心燃起必须想办法解决的想法。

无法离开宅邸的碧翠丝、必须离开宅邸才能观赏的花田。原本赏花只是用来举办酒宴的目的，重点是准备能完成原先目标的场所……

「──好！不然这个样子吧！」

一想到起死回生的方法，便让昴重重地拍了一下手。

见到昴浮现灵感的模样，爱蜜莉雅的紫蓝色眼眸也跟著散发出期待眼神。

4

──如此这般，在计划的两天后很快就到了宴会当天。

获得爱蜜莉雅的同意后，便开始加紧准备宴会，不过大部分都是多亏了雷姆对昴的提议大展身手的功劳。

「毕竟不能让昴丢脸，雷姆也会使出浑身解数的。」

雷姆一边以可爱表情无法想像的速度切著鱼与肉，一边说出这番令人值得信赖的话语。

即便是昴临时起意让她增加工作，多亏雷姆没有半点厌恶神情地帮忙，宴会才能毫无延宕地持续进行准备。虽然昴与爱蜜莉雅也帮忙准备料理与会场，但为了两人名声，还是别说究竟帮了多少忙会比较好。

不论如何，在宴会即将开始前，昴将会场的准备事宜交给雷姆等人处理，他则是为了完成某个只有自己才能做到的事前往某处。

而那个地方就是──

「就是这样已经准备好了，只差你就全员到齐了。」

「……你还是一样，每次进来都说些莫名其妙的事呢。」

昴以准确至极的预感，找到了能在宅邸中自由移动的禁书库。

就连从前总是出现过度反应的碧翠丝，最近似乎已经放弃挣扎。虽然这让昴颇为得意，相反地也有种不太满足的感觉，不过今天昴决定先将此种感情摆到一旁。

碧翠丝坐在平常坐的梯凳上，昴装熟地拍了拍她的肩膀说道：

「你也太跟不上话题了，今天是宅邸成员准备赏花的日子。要是太早说可能又会被你念个不停，所以只有你是刻意留到今天当成惊喜！」

「你的话根本是前后矛盾吧！我是不知道什么赏花，不过贝蒂为什么非得参加那种胡闹的宴席……」

「你看，我就知道你会这么说，所以两次说服只要节省成一次。而且反正你都会不甘愿地参加，就让我们都省点功夫吧。」

「可以麻烦你别装成一副知道麻烦又可以这么说的表情吗！气死人了！真是气死贝蒂了！你是哪里懂贝蒂啊！应该说……」

碧翠丝甩开昴试图将她带出去的手，然后从梯凳上跳了下来，以那淡蓝色的眼眸瞪著昴继续说道：

「不管是赏花还是什么，贝蒂都没办法离开宅邸。你们自己想做什么就去做吧，贝蒂没办法去别的地方……」

「这可不行，要把你留在宅邸耍别扭去办宴会？那当然会没办法玩得尽兴，你还是为了我们牺牲吧，没有拒绝权。」

「你、你是哪有这种资格对贝蒂说这种话啦！？」

「啊～～啊～～听不见耶～～」

在发出怒骂声的碧翠丝面前，昴摀著耳朵故意装成没听见。他的态度让碧翠丝更加气得面红耳赤，昴则是对气冲冲的少女继续说著：

「我已经听帕克说过你有些麻烦事无法离开宅邸，所以我已经考虑过这个条件想好计划，为了这件事的准备也已经完成了，再来只剩你被我带出去就好。」

「────」

「说实话我能理解你的心情。不管是看起来多快乐的活动，实际要出门前也是会麻烦到会想死。不过最后试著出来之后，再怎么说还是会很快乐也是事实，所以我决定一开始要从背后硬推你一把。」

绷著脸的碧翠丝没有任何回应，不过宛如放弃般的叹息与浑身无力的姿势就是她的答案。昴微微一笑，拍了拍少女的肩膀将她带出禁书库。

两人就这样并肩穿过宅邸走廊，最后来到的地方就是──

「好好，快进去吧。我们两个是最后的参加者。」

「真是的，你到底在打什么主意……」

昴推著不太甘愿的碧翠丝背部，并且推开眼前的门。瞥见少女突然睁大那狐疑目光后，昴不禁会心一笑。

「那么，今天就是让宅邸成员培养感情的宴会……第一届罗兹瓦尔宅邸主办『观星』宴正式开始！」

昴跳到吃惊的碧翠丝面前，张开双手如此大声宣言。

这里是罗兹瓦尔宅邸西馆的最上层──也就是被遗忘的舞厅。

在这个久违地经过装饰的舞厅，由敞开阳台吹来的风已经先早一步在此享受舞蹈。在过于宽敞的房间一角能够见到摆放的料理，不过由于参加者人数而显得不算丰盛，但相反地品质与外观可说是相当精致。

「……啊，昴他们也来啰，而且也有带碧翠丝过来！」

发现昴等人出现，先在会场内的爱蜜莉雅发出叫声。这道声音让其他成员也跟著出现反应，只见雷姆用小跑步赶了过来。

「昴，辛苦了。碧翠丝大人果然还是交给昴最好，真不愧是宅邸碧翠丝大人的专属负责人。」

「哎呀，这样说我会害羞呢。不过身为碧翠子专家，我也觉得这点程度是应该的。」

「贝蒂从来没听过有那种负责人或是专家！真是有损名声！」

虽然碧翠丝对两人愉快的对答表示愤怒，不过昴与雷姆皆心平气和地装成没听到。此种对待让碧翠丝气得浑身发抖，但有个小小影子缓缓落到她的肩上。

见到毛球出现在自己的脸颊旁，碧翠丝的表情顿时豁然开朗。

「哥哥！」

「嗨，也欢迎贝蒂过来。我还在想贝蒂会不会闹别扭不想过来……真不愧是昴，这么瞭解该怎么说服贝蒂呢。」

「才、才没有这回事呢！最瞭解贝蒂的人永远都是哥哥！没错，就是这样，贝蒂绝对没有说谎。」

「哈哈，我很高兴喔。如果真的是这样就好了。」

对于帕克和缓的回答，不知为何碧翠丝突然瞬间绷紧脸颊。但昴并没有发现这番对话，只是倾听著雷姆的会场说明。

「料理的准备与配膳，已经与爱蜜莉雅大人和姊姊一起处理完毕了。由于昴也有帮忙准备材料，花费的工夫反而比平常还少呢。」

「这样啊，不过装饰会场之类是增加工作没错吧？这真的得说抱歉，下次我会补偿你的。」

「没问题的，只要今晚让我比平常更多看看昴的睡脸就可以了。」

「嗯……？你刚才是不是说了什么奇怪的话？睡脸？」

「不不，我没有说什么奇怪的话喔。」

虽然感觉是不能错过的发言，不过雷姆带著可爱的微笑瞒混过去。昴歪著头表示不解，然后走向阳台准备主持观星宴。

「昴，辛苦你啰。有好好把碧翠丝带过来，真是厉害呢。」

在夜风吹拂的阳台上，出来迎接的爱蜜莉雅笑著摸了摸昴的头。被白皙指尖抚摸的感触，让昴害臊地眯起眼睛。

「嗯～～有种想继续享受下去，又有种想强调我们是男女而不是小孩子的两难感。」

「──？我知道昴是男生，而我是女生喔？」

「意思就是，想把认为我是男生的意识中去除掉多余的部分……」

「毛。」

对于浮现下流想法的昴，与罗兹瓦尔并肩站在阳台边缘的拉姆紧瞪著昴如此说道。她的视线彷佛表达著「赶快开始吧」的意思，让昴不禁露出苦笑。

「昴，请用。」

「喔，谢啦。」

宛如抓准时间般，专心服侍的雷姆向昴递出银色托盘。托盘上放有装酒的酒杯，昴拿起一个酒杯并环视四周。

爱蜜莉雅、雷姆与罗兹瓦尔等人皆拿著酒杯，碧翠丝也是带著闹别扭的神情，在帕克身旁被迫拿著装有果汁的杯子。

「呃，今天感谢各位前来参加罗兹瓦尔宅邸『观星宴』，接下来是希望众人能团结一心并加深感情的宴会。首先由本人致上宴席时必定会提到的话题，那就是人生中有三个重要的袋子……」

「我说昴啊，你该不会要说很久吧？」

「不不，其实这是『胃袋、钱袋、带老妈与忍耐不是变成四个了吗』的搞笑梗啦……」

「毛。」

再度被锐利目光如此一瞪，昴只好无精打采地将主持棒交给主办人──也就是这间宅邸的代表罗兹瓦尔。

先前笑著在一旁观看的罗兹瓦尔则是轻轻拿起酒杯。

「致词太久只会让气氛变僵呢。所以我只说一件事──不论原因是什么，能像这样聚集起来就是同伴。之后应该也会有很多辛苦的事，让大家一起齐心协力克服万难，今天让我们对众星的加持干杯吧。」

「──干杯！」

在罗兹瓦尔这番令人出乎意料认真的致词后，所有人举起酒杯的声音也跟著响起。

酒杯的轻盈碰撞声此起彼落，酒宴便在和缓的气氛中揭开序幕。

5

接著，观星宴在既快乐且平稳的气氛下开始。

虽然名义上是庆祝的亲睦宴会，但具体上并没有要庆祝什么事，严格说来就是晚一步庆祝魔兽骚动顺利解决与伤患痊愈。

桌面上摆放的各种料理比平常更加丰盛，当然那并不是雷姆平时偷懒，而是今晚别有一番风味。

众人各自拿起餐点大饱口福，仰望星空并稍微品尝美酒。

虽然在齐放樱花树下赏花的计划没有实现，但从阳台一望无际的清澈夜空，仍然能见到不输给樱花的漫天灿烂星斗。

在凉爽澄澈的空气与万里无云的广阔天空下，可说是满足观星酒宴条件的绝佳场景。对于自己源自「昴宿星团」的名字，昴也意气风发地准备在宴会上展现出这个小知识。

然而──

「嗯～～？昴你怎么了？总觉得……啊哈，你的脸变得好奇怪喔。而且居然变成这么多个，好奸诈喔。昴一定是想把全部甜点都据为己有吧～～」

「说我的脸很奇怪有够伤人的，而且我没有变成很多个！真是的，爱蜜莉雅酱这样不行啦。居然那么大口喝酒……」

满脸通红并带著高兴笑容的爱蜜莉雅瘫软地靠了过来，她嘟起嘴如此告诫昴后，便将手中的酒杯一仰而尽。

琥珀色的液体流过樱花色的唇瓣，白皙喉咙微微发出吞咽声并吐出热气。

「唔嗯……酒好好喝喔。好奸诈喔，居然偷偷隐瞒到现在。大家都没避开我偷偷摸摸……偷偷摸摸偷偷摸摸做这种事对吧？嘻嘻嘻……」

「哎呀真是的，她未免太可爱了吧！」

爱蜜莉雅坐在阳台地面，替自己的酒杯倒著酒。从已经有几个空酒瓶来看，爱蜜莉雅的酒量可说是十分惊人。

但她只是没有醉倒，变成现在这种模样算是挺快的。

「虽然是如同猜想，模样也和想像中没有差别，不过爱蜜莉雅酱果然不会喝酒又酒品很差……」

根据先前与爱蜜莉雅相处的经验，昴认为她的酒量不是极好就是极坏，结果就像是眼前所见──幸好没有开始脱衣服或吐得满地，这种不会造成困扰的可爱酒疯算是不幸中的大幸。

不过要她别喝也不听劝，这点确实是挺麻烦的。

「最好还是硬逼她别再喝下去，然后唱个摇篮曲把她哄睡。不过……」

爱蜜莉雅带著性感神情靠了过来，不过昴有个无法阻止她的理由。原因单纯只是他无法动弹而已。

至于说到原因就是──

「──昴。」

「嗯，有什么事吗？雷姆？」

「我咬。」

「这样很痛，雷姆。」

昴盘腿坐在阳台上，雷姆则是将头躺在昴的大腿上。虽然与往常一样面无表情，但只有脸色红得令人担心。

雷姆将昴的大腿当成枕头，不过动作可说是既缓慢且没有任何要求。就连目前也只是突然想到咬了一下昴的大腿，并没有出现很差的酒疯。

但是否能不能算是酒疯都是个问题。虽然雷姆确定已经喝醉，不过并不像爱蜜莉雅，她并没有喝半口酒。

「就算不是因为空气与气氛，没想到居然只会因为酒味就变得昏昏沉沉。不过她在煮菜的时候用酒怎么办？也会有需要替罗兹亲倒红酒的时候吧？」

或许该说，她从这场观星宴开始时就已经在配酒了。面对昴的疑问，在大腿上的雷姆只转动头仰望著昴。

「请不要看扁雷姆，昴、昴、昴。」

「居然用比平常多三倍的次数叫我。呃，这是怎么回事？」

「平常总是会绷紧神经处理重要工作，可是今天的快乐宴会一个不小心就放松了，所以都是昴的错。」

虽然她的神情看来凛凛有神，但说话却是不合逻辑。

应该说她话说到一半，便将手绕过昴的腰部并将头抵在腹部，此种让昴心惊胆跳的撒娇方式表示她已经完全酒醉。昴对于她出乎意料的一面感到颇为吃惊，但还是不经意地摸了摸雷姆的头，雷姆则是喉头发出咕噜咕噜声表示高兴。

「是猫喔！应该是鬼才对吧……话说我认知中的鬼应该都是很会喝酒，该不会这方面的考证在异世界就不管用了吧？」

「我是不知道你在比什么，不过鬼族在种族之间的确是比较会喝酒，小时候拉姆也常常在大人的酒宴上比酒。」

当昴对鬼的酒量歪著头匪夷所思时，背后突然传来拉姆回答疑问的声音。

「你居然一副理所当然地说出未成年时代喝过酒。虽然我是没意思过问鬼族的规矩……不过拉姆你的表情和说话逻辑没有变耶。」

「这是当然的，锻炼方式不一样。」

昴回过头一看，便见到拉姆坐在舞厅内的椅子上优雅地喝著酒。明明身上穿著女仆装，但充满气质的模样就像是个女贵族。她那随时维持自信的态度，以及颇为落落大方的气质或许就是让昴如此思考的主因。

而宛如女贵族的拉姆眯著眼睛，看著雷姆搂著昴腰部的模样继续说著：

「雷姆好像也挺享受这场酒宴，看来很不错嘛。」

「这样叫享受……看起来是很享受没错啦，不过雷姆体验到的真的只有气氛而已。还没摸到酒就变成这个样子了，雷姆在鬼村子里的酒宴都没有变成这样过吗？」

「……拉姆和雷姆算是处在比较尴尬的立场，而且拉姆不太希望雷姆混在只有大人的宴席中。」

对于拉姆垂下目光的回答，昴犹豫著是否该继续问下去。前阵子才刚问过两姊妹关于角的事，对她们来说，故乡的话题应该算是禁忌。

居然会完全忘了这件事提到这个话题，昴希望这是因为酒而让判断变迟钝的关系。

──从旁或许很难看出来，其实昴也喝了相当程度的酒。

虽然酒醉让爱蜜莉雅与雷姆展现出全新魅力是好事，但只可惜昴也算是会喝酒的人。

他还没有到喝醉酒就不会看现场气氛的程度，也让他对自己的体质感到颇为傻眼。

「酒的味道本身还不算太差……不过这场宴席上我学到一件教训，那就是不能随便给女孩子喝酒。」

「感觉这个结论也太极端了。」

拉姆如此说著并将酒喝进口中，令人惊讶的是她身旁有无数空酒瓶，她的恐怖之处似乎都点到态度与体质这类与能力无缘的地方上了。

「拉姆如同想像是个酒豪，那其他人……帕克也满厉害的。」

昴将视线转往会场的方向，桌面上的帕克让他不禁瞪大双眼。

即使先前发下「绝对不会让莉雅喝酒」的豪语，帕克似乎已经完全忘记那番决心，目前正泡在装酒的容器中享受美酒澡。

正面能够见到罗兹瓦尔手持酒杯与帕克谈笑风生，也能瞥见精灵与宫廷魔术师之间的融洽感情。接著──

「啊，碧翠子那家伙在做什么？」

昴四处环视寻找著小小身影，结果在隔壁阳台发现少女的身影。碧翠丝靠在没有任何人的阳台栏杆旁，她那长卷发则是随风摇荡。

对于她那似乎沉浸在寂寞中的模样，昴不禁发出叹息。

「好吧，稍微去逗逗她吧。爱蜜莉雅酱，不好意思雷姆麻烦你了。」

「嗯～～？我知道啰～～好好，雷姆过来吧～～嘻嘻，好可爱喔～～」

昴小心翼翼地将绕过腰部的手腕解开，将目光呆滞的雷姆交给爱蜜莉雅。爱蜜莉雅接过毫不挣扎的雷姆，似乎很开心地紧紧抱著她，并且摸著雷姆的蓝色发丝。两位楚楚动人的少女就这样互相磨蹭著脸颊。

「……好想拍照留念。」

「拉姆会负责烙印在眼中的。」

对于依依不舍的昴，留在会场的拉姆坚定地朝他点了点头。于是昴托付给拉姆的记忆，便走向伫立在阳台处的碧翠丝。

碧翠丝静静地望著星空，昴则是在她身旁靠著栏杆笑著搭话。

「别一个人躲在边边嘛，你孤孤单单的模样实在让人看不下去了。」

「真是个没必要的中伤，不需要你多管闲事……而且当初说不给贝蒂喝酒的人就是你，不然你还要我做什么？」

「找你出来是一回事，毕竟你的外表年龄喝酒实在是不太能看吧？偷偷尝过酒的滋味后，我实在不敢想像你窝在禁书库喝酒的模样。」

这个宴会是为了让大家愉快度过时光，要是让这位幼女学坏就没有意义了，或许该说这种时候帕克才更应该跳出来阻止。

「结果那只猫居然泡在酒里面爽快豪饮，它是哪国来的土豪啊。」

「不准你说哥哥的坏话，而且哥哥的态度表示它是这么信任贝蒂，所以贝蒂根本不会感到寂寞……」

「哎呀，爱蜜莉雅酱与雷姆比刚才黏得更紧了……唔！」

「都来到这里还把贝蒂当成耳边风，真是个没礼貌的家伙呢！」

「呃……不、不是这样啦！只是爱蜜莉雅酱和雷姆的姿势对男生来说实在太有吸引力……我不是看傻眼喔，只是想拿台照相机……！」

「根本没有说服力和连贯性嘛！」

在另一侧的阳台，能够见到爱蜜莉雅抚摸著雷姆的身体，雷姆则是发出咕噜声向爱蜜莉雅撒娇，两人的模样已经亲密到了百合的程度。

「没办法在现场真是太可惜了……！」

「你说够了吧。哥哥也被罗兹瓦尔带走，今晚的贝蒂还是比较适合孤单一人在夜风中发抖。」

「抱歉抱歉，看到客人闹别扭的心碎模样也会让牛郎很难过，真是拿你没办法耶。」

对面露不满的碧翠丝回以笑容后，昴学她一屁股坐在栏杆上，但在坐稳前醉得摇摇晃晃差点摔了下去。

「哇喔喔！超、超危险的！差点就变成烂番茄了！」

「就算你卖命玩这种把戏也不好笑，就算你像只虫子被压扁死掉，应该也没什么有趣的吧。」

「我可没有责任需要招待你到赔上小命啦！刚才真的很危险耶！」

昴擦掉冷汗，一屁股稳稳坐在傻眼的碧翠丝身旁。虽然没有受到欢迎，但她也没有逃走的意思，这就代表碧翠丝已经同意了吧。

「好，既然这样我来说个美丽故事给你听吧。其实我原本是想在星空下耍帅，对爱蜜莉雅酱说出这个浪漫话题炒热气氛，结果酒力太强让我的计划都泡汤了。」

「怎么听起来像是聪明反被聪明误啊？」

「是啦！就是这样没错啦！不过先别管那件事，我是想说有关自己故乡星星的事，在那边星星可是有自己的名字和很多故事喔。」

对昴来说这可是相当正统的星空话题，他打算靠这个话题引起碧翠丝的兴趣与笑容。昴带著此种决心抬头仰望漫天星斗，结果不禁让他屏起气息。

其实每次昴抬头望著星空，都会顿时有种莫名困惑的感觉。

──毕竟头上的星斗，与昴所知的天体可说是截然不同。

不论是格外闪耀的北极星、附近的北斗七星、还有季节不同能够分别享受的夏季大三角与冬季大三角，以及猎户座和仙后座都不知道跑到哪去了。

讽刺的是，昴只要抬头仰望夜空就能立刻发现，这个世界的星群配置与昴所知道的世界截然不同。

「……你是已经忘光了吧，如果没事就快点去别的地方吧。」

「我没忘啦，只是因为太多有点犹豫……首先是那个，那个发出自我意识过度强烈光芒的星星就是北极星。基本上只要迷路就靠那个，那边大部分都是北方。」

「那边是南方，正好相反呢。」

「不然那就是南极星。」

「不然是什么意思！？听起来很像是随便唬人的呢！？」

昴确实只是随口说说，但他将这件事藏在大胆笑容内继续说道。这种场合只要退缩就输了，虽然不知道是在比什么，昴认为这一定是喝过酒的关系。

面对碧翠丝怀疑的眼神，昴则是指著南极星说道：

「从那个南极星为起点寻找其他星星，把视线稍微往下应该能看到五个排成M型的星星吧？那个就是仙后座。」

「贝蒂听不懂那个欸幕是什么，也看不出有什么形状。」

「不是用看的，要用感觉的。呃，如果不知道M是什么，那用锚的形状去思考也可以。关于仙后座的故事，就是喜欢炫耀的卡西欧佩亚皇后，因为太过炫耀自己女儿安朵美达的美色而招致众人反感。」

「……没想到天空的星星有这么像人类的故事呢。」

碧翠丝对昴的话感到相当傻眼，此种混有叹息的感想让昴缓颊一笑。

「对吧？在我老家那边星星是被当成神，可是每个神都是充满问题又很像人类！这才是最有趣的地方喔！」

「造神实在太夸张了。对于超越人类知识的象征，用这种解释实在是很自作主张。」

「虽然说成超自然象征的确很让人敬畏啦，不过看到类似条件的大精灵悠哉地泡在酒里，总觉得就没有半点说服力了。」

在昴的视线前方，能够见到罗兹瓦尔重新替帕克将喝光的酒杯重新添酒，说实话从此种胡闹的模样实在很难感觉到威严。

目睹同样景象后，就连碧翠丝也不禁露出尴尬神情回答：

「哥哥就很多层面而言都是超脱框架的大精灵，所以你别用大精灵的基准衡量哥哥的宽大胸怀，只有哥哥是特别不一样的。」

「辛苦你勉强找藉口解释。然后说到其他星星……好吧！既然这样不说别的，就来找『昴』吧！」

「……啥？」

对于弹响指头并露齿一笑的昴，碧翠丝投以哀怜的眼神，少女的此种态度让昴赶紧摇了摇头解释。

「等等等等！别用那么哀怜的眼神看我啦！不是你想的那样，虽然我的名字是叫『昴』，不过这原本是源自于星星的名字。『昴』是有很多星星聚集在一起的星团，我的意思是一起来找找看啦。」

「居然会把天上闪烁的星星当成名字，没想到你的双亲会做出这么残酷的事呢。」

「别兜圈子损我夸耀自己的名字啦！」

昴自己也并非是毫不在意，由于感觉快要碰触到此种自卑心，于是昴用轻佻的态度含糊带过并用手指著天空。

「你可能没什么兴趣，不过就当成某个酒鬼的玩笑话稍微陪我找找吧。」

「……贝蒂可没说没有半点兴趣。」

「────」

碧翠丝对充满干劲的昴如此喃喃说道。当昴对这句出乎意料的回答瞪大双眼，少女则是转过头别开视线，脸上还微微浮现出红润。

「怎么怎么啦！喂喂！真是个不老实的萝莉耶！真是拿你没办法！既然这样就继续来聊有趣的星空话题吧！」

「太大声了，真是个烦人的家伙。」

「好好！我知道这样很可爱啦！」

碧翠丝的态度让昴相当愉快，于是饶舌地继续说著话。仰望著不熟悉的星空，完全不同的星星故事也无止尽地涌出。

随著轻快的心情，昴总觉得脑袋也有种轻飘飘的感觉。

6

「──罗兹瓦尔。」

「哎呀？与昴偷偷约完会了吗？」

罗兹瓦尔晃动酒杯，对由阳台回来的碧翠丝笑著如此说道。这位小丑男的言行举止让碧翠丝不悦地皱起眉头。

「开玩笑可以只用你那身装扮就好吗？你的意思是贝蒂和那种家伙度过了快乐的时光？这一点都不好笑呢。」

「真是不老实，这种地方还是和以前没什么变呢。」

「这是当然的。除了哥哥以外，这里面没有人历练比我还深。不过话说回来……」

碧翠丝朝坐在罗兹瓦尔对面的拉姆瞥了一眼，罗兹瓦尔察觉这道视线的意图便收起下颚，拉姆则是无声无息地静静从座位起身。

拉姆将手中酒杯的酒一饮而尽，接著行了个礼走向阳台，阳台处能够见到昴、爱蜜莉雅与雷姆三人正融洽地呼呼大睡。

拉姆将事先准备好的毛毯各自盖在三人身上，对爱蜜莉雅小心翼翼、对雷姆充满慈爱、而对昴则是盖在脸上。

「不习惯喝酒的那群孩子还真是可爱呢，昴虽然看起来没事，不过也意外地差不多喝到极限啰。」

「就像是断线一样突然醉倒，步伐和说话方式也从一开始就怪怪的……模样与平常差很多，想不发现都很难呢。」

「不过你知道会醉倒还陪他说话，是因为你发现昴和平常不一样……是吗？」

「────」

「别用那么恐怖的眼神看我嘛，只是单纯开个玩笑喔。」

对于罗兹瓦尔意图捉弄的言外之意，碧翠丝疲累地长长叹出一口气。由于两人相识已久，这道叹息相对地显得既沉重且无力。

见到她那不符合稚嫩外观的动作，罗兹瓦尔则是无奈地耸了耸肩。

「今晚的宴会你不满意吗？」

「反过来问好了，你觉得贝蒂会满意吗？这么吵吵闹闹……对于不喜欢平稳生活被打断的贝蒂来说，这可是最让人生气的事。」

「是这样吗？看到最近的你实在没办法老实同意呢。你只是不得已接受名为安稳的寂静，原本的你应该是……」

「罗兹瓦尔。」

这道声音与冷淡目光打断罗兹瓦尔的话语，一股莫名尴尬的气氛顿时笼罩两人之间。但就在这个时候──

「贝蒂。」

「……哥哥。」

留在现场的第三者，也就是帕克仍然泡在酒杯中歪著头问道：

「贝蒂不太喜欢这次宴会吗？」

「……并不会，只要看到哥哥高兴，贝蒂就很幸福了。不过今天的哥哥酒臭味太重实在没办法抱紧呢。」

「喵～～」

酒杯中溅出飞沫，帕克则是沉进酒中。就这样直接将杯中的酒一饮而尽，然后再跳了出来将全身酒气吹散。

「怎么样？」

「还是有酒臭味。」

「那这样呢！」

听完碧翠丝的评分后，帕克的肉体连同胡须开始颤动并发光，转眼间再度形成小猫的肉体。这样就能将先前的影响完全恢复原状。

「不会宿醉真是方便的体质呢。」

「相对地吃下肚的酒和饭也会跟著消失，就这点来说，精灵的身体可是一点都不有趣呢。」

帕克对罗兹瓦尔简单明瞭的感想眨了眨眼，然后爬到碧翠丝的肩头上。碧翠丝先将脸颊悄悄凑到酒气消失的帕克身旁，接著便瞪著罗兹瓦尔。

「哎呀，表情这么可怕，你今天到底是怎么回事呢？」

「贝蒂只是想听听你真正的用意。今晚这场酒宴到底有什么意义？」

「就像干杯之前说的，需要让这里的所有人能团结一致面对接下来的问题──我决定要以这些成员达成长久以来的愿望。」

「────」

「你也做好心理准备吧。漫长契约完成的时候就快到了，至少我打从一开始就是这么想的喔。」

以认真语调如此说道后，罗兹瓦尔拿著手中的酒杯走向阳台。隔著琥珀色摇晃的世界，罗兹瓦尔的双眸中映照出睡在地面的少年等人。

碧翠丝知道他的长久心愿，对此种决定并没有表达肯定或否定。而放弃选择也是碧翠丝经过很长一段时间做出的抉择。

「……不论如何，我希望你的存在能够开花结果。这可是我众多谎言装饰的少数真正心声喔。」

「真是无趣的感伤。你是想同情我吗？」

「这叫做同理心。毕竟你和我可是这个世界上唯一的共犯呢。」

罗兹瓦尔如此说著，将新的酒杯摆在桌面上并倒进酒，然后小丑便将酒杯推到少女面前。

「这是？」

「这是你的份。被招待到酒宴却没喝半滴酒实在太可怜了，会责备你饮酒的孩子目前已经完全在睡梦中了。」

罗兹瓦尔带著邪恶笑容，闭起单边眼睛向碧翠丝如此献酒。这番话让碧翠丝朝酒杯伸出手，但就在此前瞬间吹起了一阵风。

这阵由阳台吹进并含有夜晚气息的风，让碧翠丝脑中闪过先前的对话。

「────」

接著，少女将碰触到的酒杯推了回去拒绝饮酒。

「还是别喝好了。」

「你是想做面子给昴吗？这还真是令人意外呢……」

「别误会了，贝蒂不喝不是因为听那个小鬼头说的话……是因为母亲大人曾经说过。」

碧翠丝的答案让罗兹瓦尔保持沉默，见到此种似乎效果卓越的反应，让碧翠丝带著彷佛事不关己的表情摸了摸帕克的背。

从前也曾有过这样的夜晚──夜空下，母亲曾对碧翠丝喝酒的举动没有摆出好脸色，另外似乎也有被出声喝止过。

因此在禁书库停滞不前的自己，没有资格违背那天母亲的告诫。

「就只是这样而已……那家伙说的理由和贝蒂没有任何关系。」

碧翠丝说著这个藉口，丝毫没有将酒杯送往口边。

酒宴的夜晚逐渐拂晓。

主办者尝到酒的味道、快乐与辛劳，而少女们展露出各自的酒品，这个酒宴之夜就这样缓缓迎接早晨。

而只有星空无言地俯视这段平稳的时光。

** 后记

各位好！我是鼠色猫！对不起！对大部分读者应该自称长月达平吧！

这次试著用相反的顺序自我介绍，两边都是本人的名字。有时候长月的签名会签错，而且鼠这个字总是会忘记怎么写而相当烦恼！

本次是短编集！其实本人在月刊COMIC ALIVE每个月连载《RE:ZERO》短篇小说，本集就是将短篇统整再度编辑的作品集。

多亏各位支持，短篇小说的连载也顺利来到第二年。这次只是将已刊载故事统整起来的简单工作！说实话当初的确是这么想的。

不过实际要编辑成书并回过头一看……自己两年前的文章真是不够成熟！写得又差劲！有很大幅度的改善空间！这些问题让本人深深吃了一惊。

结果最后结局也是全部文章修正，根本一点都不轻松！

但修改后文章变得更加洗炼，内容肯定也有变好，希望各位能享受罗兹瓦尔宅邸的和平时光。

另外说到罗兹瓦尔宅邸的故事，漫画版第二章的第三集与短篇集是同月开始贩售！第二章的故事也是渐入佳境，请各位观赏逐渐加速的故事剧情与充满魄力的画风！

还有就是，《RE:ZERO》世界还有许多漫画家精心绘制的漫画精选集也是同月贩售！其中也是有许多既和平又快乐的故事！

也请各位搭配漫画版尽情享受《RE:ZERO》的世界！

那么幕后秘辛也告了一个段落，接下来请容我进入惯例的致谢时间。

首先是责任编辑I先生，能够事先预测到动画化时期的出版作业会相当辛苦，因此先累积短篇小说的选择可说是相当令人佩服。只可惜因为作者太过热衷于修正文稿，导致作业流程并没有想像中轻松！

接著是负责插图的大冢老师，这次也是出现了许多既和平又安稳的场景！真是太厉害了！没有出现半次敌人！这是经过十二册后才发现的令人震惊事实！多亏大冢老师绘制的可爱角色，让本书可说是充满了视觉飨宴。谢谢老师！

另外还有MF文库J编辑部、负责漫画化的マツセダイチ老师、枫月诚老师、负责设计的草野老师、宣传部门、以及各家书店等等，这次也是受到了各方诸多照顾。

最后，则是对将此书阅读到最后的各位读者献上最高的感谢！

不论是小说、漫画或是动画，今后也请各位继续支持《RE:ZERO》！

那么，希望能在下集再度与各位相会！

（2016年5月，在动画拨放期间每周被剥夺睡眠之随笔）