#+title: Re:从零开始的异世界生活 外传 ex3 剑鬼恋谭
#+setupfile: ./setup.setup
* 外传 ex3 剑鬼恋谭

** 『剑鬼恋谭──之后的两人』

台版 转自 轻之国度

图源：真妹控

录入：kid

1

──那是个昏暗，又被干巴巴的空气给入侵的场所。

寂寞又寒冷的空间。

光照度已经低到不能再低的结晶灯，用白光照耀冰冷坚硬的石砌墙壁与地板。

流进地下的风冷得刺骨，令人想起现在是寒季。

「────」

已经有相当久都过著与季节和时间无缘的生活了。

将所有的心力全都投注在一件事上，连睡眠和进食都压缩在最低限度──那是与野兽无异的时光。

而这样的日子也结束了，自己现在才会在这里。

虽然不知道是否能挺著胸膛说耗费这么多的岁月是有意义的就是了。

「……喂，那边的。我在叫你啊。喂，有没有在听啊？」

「────」

「新来的──有听到吗？还是说已经死了？喂──」

背靠著墙壁坐著，漠然地发呆时，耳膜捕捉到了这些声音。

转动脖子，瞄向声音来源。昏暗的对面是铁栅栏，然后是通道，再过去又是铁栅栏，声音的主人就从那儿开心地看著这边。

隔著两道铁栅栏互看的两人──也就是他们两个都身陷囹圄。

「终于──看过来啦。明明是新来的架子却挺大的嘛～……不对不对，正因为是菜鸟，所以才会对世界破灭龟缩起来吧？唉呀～算了。这种人很常见。嗯嗯？等一下？因为骯脏又昏暗所以我刚刚没发现，但你看起来～还很年轻嘛？」

「……呢。」

「──？你说什么？」

「我说你很会讲话呢。一个人都可以讲得那么开心啊？」

面对对方的连珠炮话语，忍不住就反射性地回敬讽刺。这是自己的坏习惯。他在久违的自觉和自省下叹气，玩弄自己的浏海。

不过这种态度恶劣的反应，却只是让对方加深笑意。

「唉呀吾友啊，滔滔不绝和笑容泛滥，人称『六面三刀』欧尔菲的人就是我啦。住进我对面的牢房算你气数已尽。是会释放还是死刑呢……总之，在你跟这儿的缘份还没断之前，就先陪我杀时间吧。」

「『六面三刀』……？」

「一个臭名啦。内战时，我同时安慰六名芳心寂寞又胆小的贵族街千金，流连在她们之间，结果就被抓了。然后呢，因为我对她们说的话都不一样，大家就说我会见人说人话、见鬼说鬼话，就叫我『六面三刀』啰。」

「就是恋爱诈欺犯或人口贩子吧。就因为这样而被关在王城大牢里，真是荒谬至极。」

男子不以为意还轻浮大笑的态度，实在让人愕然。

心里这么想，然后凝神盯著暗处看，就在铁栅栏后方看到了长发美男子。肤白似雪、手足细长，看起来就是在社交界长袖善舞的人种。

冒出这感想的时候，自称欧尔菲的男子歪头看了过来。

「只是被关就叫笑话的话，那么你的笑话又怎么样呢？话是这么说，但既然会被关进城牢里，事情也不小条了吧。一定是做了什么惊天动地的大事，对吧？」

「是啊。我做了……」

讲到这儿，话语中断，他沉默半晌，思索了一下欧菲尔的话。

但是，答案立刻就出现了。

「就只是要把我的女人，从讨人厌的家伙手中抢回来而已。」

「────」

「本来我只这么打算，但事情就是闹大了。就变成这副德行啰。」

他没辙地摇头叹气，道出被抓进牢里的原因后长吐一口气。

结果，听到这番话的欧菲尔手掩嘴巴，忍俊不住地噗哧笑了出来。

「噗哈！噗哈哈哈！什么嘛，你。喂，那你的状况不就跟我一样了！」

「白痴啊你。不要把我跟一次劈腿六人的你相提并论。我只专情一人。」

「哪里不一样了！不都严重到被关进监狱塔吗。那个讨人厌的家伙不是骑士就是贵族……而且女方可能身份很特殊。没错吧？」

「……随你怎么想。」

不高兴地回答欧尔菲，结果放任想像膨胀的他继续拍腿大笑。

没打算把真相告诉对方。不过客观来说，自己跟欧尔菲的境遇确实没有太大的差别。都跟女人有关，如果只看这点的话那的确一样。

「唉呀～我欣赏你，小哥。看样子牢狱生活会暂时快乐一阵子了。」

「想笑就随你高兴笑多久吧。──不过，我可能没法回应你的期待了。」

「哦～？」

欧尔菲讶异反问。

不过答案很快就从别的方向──地牢的出入口、通往地面的楼梯那儿传来。

硬鞋底敲击地面，停在地牢前面的是身穿盔甲的王城卫士。卫士俯视坐在牢里的人，眯起头盔里头的双眼。

「出来。来接你的。」

卫士用傲慢的口气说完，就打开地牢的铁门。听了这话只好不情愿地站起来，在催促的视线下被带到牢笼外。

「哎哟～怎么那么快就要说再见啊。」

欧尔菲嘟起嘴唇，忌妒地朝被卫士带走的人说。

「被释放的话我会很寂寞的。你认识的人似乎蛮好心的，真叫人羡慕耶。」

「谁知道呢。」

苦笑回应美男子后，想像在楼上等著自己的「认识的好心人」。

然后青年──威尔海姆•托利亚斯闭上一只眼睛，说：

「看那个人的愤怒程度，搞不好我不是被释放，而是被处死喔。」

留下这段话后，威尔海姆就离开了地牢。

2

「处死比释放好，是吗？也行，现在改变主意也是可以的喔？」

走出地底来到地面的威尔海姆被凉风和日照迎接，而「认识的好心人」则用带著平静怒意的声音对他这么说。

方才关押威尔海姆的地牢，是邻接王城，被称为「监狱塔」的设施，只关押罪犯之中的重刑犯。跟如此知名的场所扯上关系的人，包含狱中的囚犯在内，负责管理这座塔的狱卒也都个个长得凶神恶煞样。

正因为是这样的地方，因此貌美如花的少女在此显得格外醒目。即便她的表情净是不服气和不满，却还是魅力十足到让人看得著迷。

宛如火焰的及腰长发，彷佛封闭了万里晴空的蓝色瞳孔。又白又细的手脚修长，匀称的体态位在被称为健康美的领域。五官除了端正外，还有著如花儿在阳光下绽放的开朗美貌。

特蕾希雅•范•阿斯特雷亚──就是怒上心头依旧美丽的人儿的名字。

「威尔海姆？」

即便特蕾希雅的眼神严厉，但威尔海姆一看到她，整个人瞬间就傻到忘了出声。只不过要是被察觉到会觉得很不高兴，因此威尔海姆立刻举起自己的双手。

然后摇晃铐在手腕上的手铐。

「知道了。是我不好。把这手铐拿掉吧。」

「……真是的。你真的明白吗？」

对敷衍了事的回答叹气的特蕾希雅，右手纵向挥了一下。顿时，她白皙的指头就将平滑的木制手铐给一分为二。

手铐发出声响掉落地面。威尔海姆旋转获得自由的手腕，确认手感。然后倏地察觉到特蕾希雅正在看著自己。

她眯起圆溜溜的双眼，嘟著嘴巴紧盯著威尔海姆看。

「怎么了？发生什么事了吗？」

「什么怎么了……明明都被不容分说地扔进监狱塔里了，你都不怕，或是气我们打算对你做什么吗？」

「毕竟破坏了国王主办的终战典礼。光是还有一条命就要谢主隆恩了。」

「你至少还知道自己做了很惊天动地的事嘛……。这反而有点让我吓到。」

特蕾希雅微微苦笑，说。威尔海姆肯定地回答：「还好啦。」

毕竟他所引起的骚动对露格尼卡王国来说是天字第一号大事件。如果不是以个性温厚闻名的吉欧尼斯•露格尼卡陛下给予宽大处置的话，威尔海姆就算被当成叛国贼来制裁也不奇怪。

「要不是陛下制止，失礼的你就算被当场格杀也不稀奇喔？你对这件事有好好反省吗？」

「命令士兵杀死战胜『剑圣』的人吗？内战好不容易结束却还让士兵白白送命，这种行为就算是毫不善战的王室也做不来吧。」

「你太过自信了！而且还犯下不敬之罪！你这人根本就得意忘形到极点！」

「还有要与我们为敌的话，会场的战斗力根本不够，所以是天时地利人和。」

「你竟然理所当然地认为我会站在你那边……」

人在紧邻王城的监禁罪犯设施里，而且身旁还有卫士，却还说出这种胆大包天的话。

其实在稍远处听著两人对话的卫士对谈话内容大表惊愕，但立刻又低下头装作没听见的样子。那是很聪明的判断。

撇开那虚弱的明哲保身之招不谈，特蕾希雅忙著让脸蛋一下红一下铁青。威尔海姆朝她走近一步，笔直地凝视她的双眼。

「……干、干嘛？」

「假如真的变成那样，我不会犹豫要选择哪一边。你也是这样吧。」

「──唔！你这个人，真的完全不懂别人的心情……！」

「──？我比任何人都懂你的心情。你怎么那么说？没事吧？」

「等一下！拜托打个岔停一下。被牵著鼻子走，失常到快死掉了我……！」

挥舞双手、脸红到耳根子的特蕾希雅背过脸。一下生气一下吃惊又一下害臊，真的是个表情千变万化的少女。

「────」

──不管看多久都不会腻。

分离的期间，描绘过无数次与特蕾希雅重逢的场景，但是现实中的状况全都和想像中的不符。

现在在眼前的特蕾希雅本人，比想像中的任何一个她都还要惹人怜爱。

「特蕾希雅。」

「干嘛！？我现在脑袋忙得要命！也不想想是谁害的……」

「过来。」

「────」

威尔海姆朝著声音和表情都慌张不已的特蕾希雅张开双手。

这么个不亲切的表现法，让特蕾希雅失声瞪大双眼。

沉默与犹豫诞生，持续半晌。

但是这段期间威尔海姆继续张著双手，等待特蕾希雅有所反应。

他那毫不做作又直接的态度，最后让特蕾希雅无力微笑道：

「……唉～。这样子，果然还是我输了嘛。」

「那场对决早就分出胜负啦。」

「才──不──是──那──个！我在讲另一件事啦！真是……」

威尔海姆面露不解，特蕾希雅则是看起来打从心底傻眼地叹气，接著走向前。她扑进男子的怀中，额头摩擦对方的脖子。

双方拥抱在一起。威尔海姆抱紧特蕾希雅，感受她像烧灼的体温。瘦小纤细的身体彷佛一用力抱就会断成两截，却又还紧紧抱著自己，让人受不了。

彼此都用力抱住对方，怀中的女子仰望男子说：

「欢迎你回来，威尔海姆。──你让我等太久了。」

这番话，让俯视女子的男子回答。

「嗯，特蕾希雅。──抱歉让你久等了。」

在极近距离下凝视特蕾希雅的微笑，威尔海姆也自然而然地浮现笑意。

──互相感受近在身旁的呼吸和体温与心跳。

这么点小事，对他们来说却等同是奇迹。

「────」

成就凡人无法达成的宿愿，终于亲手抱到心爱的少女。

一个劲地挥剑而变硬的手，温柔地抚摸特蕾希雅的红发。

用不著忌惮他人的幽会以及终于相触的拥抱，让特蕾希雅表情放松，然后脸贴著威尔海姆的胸膛，深吸一口他的体香。

「威尔海姆。」

「干嘛？」

「……你好臭。」

为久违的重逢划下句点的，是略微不悦的声音和眼神。

3

亲龙王国露格尼卡绵延长久的内战「亚人战争」终于结束。

长达九年的战乱，由一名少女──「剑圣」特蕾希雅•范•阿斯特雷亚拉下结局布幕。

拥有不辱没传说「剑圣」称号的战斗力，带领王国军走向胜利的她，名字被传遍国内，人们毫不吝惜地歌颂称赞她的功绩和荣耀。

强大美丽的现任「剑圣」，是众人的希望与理想的体现。在庆祝内战结束的典礼上，为了一睹剑圣尊荣的国民全都涌向王都。

事实上，当特蕾希雅现身在典礼会场时，所有观众全都目不转睛。

若是典礼就这样顺利落幕，她的「剑圣」地位将坚不可摧，永世在露格尼卡王国被传承吧。

──但是，那是在什么事都没发生的情况下。

「你到底在想什么！丢人现眼！知不知耻！」

开口第一句就是破口大骂，声音大到穿过屋子，响彻晴朗天空。

声音里灌注了宛如锐利突刺的剑气。其实若有人不习惯剑气，那么强大的声音是足以令人不自觉地缩起身子。

不过偏偏在场的每一个人，都不具备那么可爱的特质。

「……突然就那么大声，是怎样啦。」

怒吼的余韵消失时，最先开口说话的人就是不可爱人物的代表──也是被痛骂的当事人威尔海姆本人。

他的回答每每都淡然到事不关己，所以经常是更加惹怒对方。这次当然也不例外。

「什么怎样！你不觉得你该说的是其他的话吗！」

结果身穿礼服的人，被他的话给气到脸红脖子粗。

这名女性的及肩美丽金发和给人一点强悍印象的上吊眼很引人注目。楚楚动人的样貌就算自称是贵族千金也不会有人怀疑，但是这种情绪化的言行看起来才是她的个人风格。

能这么想，是因为威尔海姆跟她的交情很长。

卡萝•雷玫迪斯──威尔海姆在内战的任务中认识的女剑士。实力不差，但对威尔海姆来说印象比较深的是她很爱碎碎念。

两人之间的关系，有点像是把彼此视为眼中钉。

「卡萝，够了。你的心情我很高兴，但我没生气……」

「就是因为特蕾希雅大人不生气，我才替您生气！！」

「啊呜～」

特蕾希雅苦笑安慰，但别说哄过去了，反而还讲输她，结果回到原点。只好露出放弃的表情朝威尔海姆吐舌头。但若身为主子的她都放弃那可就伤脑筋了。

很遗憾地，威尔海姆没有方法可以制止卡萝发怒。因此他快速地使出最后手段──让站在卡萝身旁的青年帮忙擦屁股。

「格林，你的女人很吵，这样根本没法好好说话。快点像平常那样让她安静。」

「────」

「不用笑著看我。又没什么有趣的。」

稍微用力瞪了一眼，老好人青年就面露苦笑，轻拍卡萝的肩膀摇摇头。光是这样的举动，方才还气到七窍生烟的卡萝就降低气焰，一脸不高兴地叹气。

「……你要感谢格林，威尔海姆。要不是他和特蕾希雅大人，我的咎责、斥责和抱怨就不会是这种程度了。」

「嗯──果然还是不习惯卡萝不是先说我，而是先讲男人的名字。不过，虽然寂寞，但也很高兴呢。」

「特、特蕾希雅大人又讲这种话……」

这次卡萝不是因为生气，而是羞红了脸。特蕾希雅坏心地笑了。闹起来的两人就像姊妹一样亲密，实在是很新鲜的光景。

「……干嘛啦。」

『你在笑呢。』

投向侧脸的视线让威尔海姆尖起嗓子，青年──格林•法先把写在纸上的字拿给他看。

笔谈是在战场上失去声带的格林的沟通方法。不过就算没有纸笔，光看表情也大致能猜到他在想什么。

威尔海姆当然也看得出来他现在正在调侃自己。

「多少还是会笑的吧。你把人想成什么了。」

「────」

面对格林的沉默和微笑，威尔海姆不悦地回应。

若是嘲笑的话自然惹人生气，不过无声微笑的格林看起来似乎很幸福。本来该有的反感被他的笑容粉碎，连反击的力气都彻底萎缩。

要说为什么的话，因为自己被人担心到了会这么百感交集的地步。这点自觉威尔海姆还是有的。

现在四人所在的，是建在王都露格尼卡贵族街的「剑圣」宅邸──也就是特蕾希雅的私人宅邸，四人就在会客室内。

从监狱塔被释放的威尔海姆，被特蕾希雅带到这间宅邸，并不容分说地被推进浴室，还被吩咐要彻底洗去让人无法忍受的恶臭。用热水沐浴完后回到会客室，就直接接到方才被破口大骂的画面了。

「──说起来，你们两个为什么会在这里？」

从骂声开始的激烈重逢告一段落后，威尔海姆坐上沙发，歪头问出迟来的疑问。

「这里应该是特蕾希雅的宅邸吧。你们找她有事？」

威尔海姆把还没干的头发往上拨，听了问话的格林和卡萝则是面面相觑。接著坐在对面的卡萝立刻低声问道：

「……还为什么咧，当然是来见你的吧。而且我在特蕾希雅大人的宅邸里有什么问题吗？」

「穿著礼服来？我没听说今晚有舞会。」

「还不都是因为你做了那种事，才会害得人没时间换衣服！」

抓著蓝色礼服的裙襬，卡萝的情绪再度爆发。旁边苦笑的格林也身穿王国军的正式礼服。看样子，他们都是直接从典礼会场赶过来的。

因此即便威尔海姆并非刻意讲这种惹人嫌的话，但特蕾希雅还是忍不住责备。

「你喔。卡萝和格林全都是担心你才来的。不要老是讲那种让人生气的话，不好好表现出高兴的话，会让人误会喔。」

「这么说来，你本来也穿礼服的吧。为什么换掉了？」

「咦？因为跟你比剑的时候弄脏了，而且行动的时候轻飘飘的乱动很麻烦……我不要换掉比较好吗？」

「只是没看过你穿所以觉得很稀奇。其实穿哪种都一样。」

「是吗……那有机会的话还会想看吗？」

「──？」

「为什么你有时候就那么不懂看脸色啊！？把人家的勇气还来！」

威尔海姆像个木头人的反应，惹来特蕾希雅的泪眼抱怨。不过她立刻想起还有别人，所以难为情地羞红了脸。

格林和卡萝惊讶地看著他们。

「剑鬼」与「剑圣」刚刚的互动，对与他们感情好的两人来说都是无法想像、头一次见到的样貌。

──「剑鬼」简直就像个普通人，「剑圣」也同一名少女无异。

两个人的言行都远离了自身的称号，却又无疑是他们原本的样貌。

「──呜。」

深受感动而最先抵达临界点的人是卡萝。

她声音哽咽，脸靠上身旁的格林的肩膀。格林承受了情感溃堤的恋人，微笑又温柔地抚摸她的背。

「……卡萝从多年前开始就待在我身旁了。每次到花田来接我和担心我的人，都是她喔。」

特蕾希雅代替情感满溢的卡萝向威尔海姆解释两人的关系。听到后，威尔海姆也面露理解。

卡萝会在这里的原因，「剑圣」特蕾希雅出征时她会在身旁的理由，全都获得了解释。

──卡萝想必是万分担心特蕾希雅。

「真是好事之徒耶。」

「……你是知道这话会回敬到自己身上才讲的？」

「我不懂你在说什么。」

威尔海姆深深靠上沙发佯装不懂，特蕾希雅只能耸肩。接著她轻咳一声，朝格林轻轻点头。

「对不起喔。这个人很腼腆，所以没法好好表达自己的心情……偶尔话说得不够，但不是个坏人。」

『没事。我明白。』

「你肯这么说，我很感激。」

『毕竟多年来不是白白看著野兽变成人类的。』

「你们在讲什么？不会是在讲我吧？」

又是腼腆又是野兽的，听起来都是很难听的话。

当然，特蕾希雅和格林都装没事样摇头对付他的追问，威尔海姆忍不住咂嘴。

看著他不爽地拄著脸颊，特蕾希雅手掩嘴巴笑了。

就在特蕾希雅笑完之后──

「──那个，威尔海姆。」

她正经八百地呼唤威尔海姆，于是威尔海姆整个人转身面向她。特蕾希雅的蓝色双眸里带著认真。

无法忽视的压力，在那目光下威尔海姆也不禁挺直脊梁。

见他做好心理准备，特蕾希雅犹豫了一下后开口。

「这话很难以启齿……你今后打算怎样？」

「好莫名其妙的问题。什么打算怎样？」

「就是把视野放大来说吧？不管是住处还是工作，这些未来的事你都得面对。当然，住这间屋子是没问题的，我有俸禄所以生活上不虞匮乏……」

「──慢著。」

威尔海姆翻掌制止快嘴道出状况的特蕾希雅，打断她说话。

虽然特蕾希雅急著要讲到结论，但内容却有太多令人在意的地方。好几个疑问重叠在一起，使威尔海姆眉心挤出深深的皱纹。

「啊，威尔海姆，你又皱眉头了……都说过叫你别这样了。」

「这件事待会再说。我有更重要的事要问。……你刚刚说那些话，是什么意思？」

「刚刚的话……」

「就是住处和工作啊。我……」

说到这儿话语打住，不好的预感加深了威尔海姆严肃的表情。接著他凝视特蕾希雅，审慎地选字用词。

「我现在，是什么？」

非常模糊又欠缺具体性的问话。

面对这个问题，特蕾希雅一脸伤脑筋的样子。

「所以我才说难以启齿……该说你现在什么都不是吗。」

「────」

「讲白一点的话，就是……无业游民……？」

「──无业游民？」

这话让威尔海姆愕然，瞠目结舌盯著特蕾希雅，但她别过眼。看向格林，对方苦笑。接著就是卡萝含恨地瞪著自己。

「不然你还以为是什么。混帐大白痴……！」

双眼因泪水而红通通的她，愤恨地咒骂威尔海姆。

4

──因为私人因素脱离军队，目前下落不明的逃兵。

想当然也会是这样。这就是目前王国军的文件对威尔海姆•托利亚斯的记载，以客观的角度来审视他的一切作为。

如果后续有什么好追加的内容，就是他受封为骑士后没多久就脱离军队，因此骑士位阶和众多勋章都被全数剥夺，可说是骑士之耻。

「也就是说，闯进典礼会场找主角开打的行为，在纪录上跟强盗抢劫无异。不但史无前例，还偷走了『剑圣』的心……嘎哈哈哈！干得漂亮啊，你这个小偷！」

「笑屁啊……」

面对说完就哈哈大笑的大个子的欢迎法，威尔海姆抱头叹气。

地点是王国军办公区，且只给予将官使用的一间办公室。

这间石砌办公室相当简朴，除了办公桌就只有会客用的椅子和茶几。办公室的主人一知道来访者是威尔海姆，就停下手边的文件工作粗鲁地欢迎他。

只不过接待的一开头就是大笑，实在让人不觉得有趣。尽管如此，考量到自己的立场，这是理所当然的待遇。

「逃兵啊。那也难怪会被扔进监狱塔。不过既然有留下当过兵的纪录，应该要送我去惩戒室吧，怎么突然就把我当罪犯处理。」

「我先声明，干了那种天大的事，就算不是逃兵也会被塞进监狱塔的。监狱塔的卫士也有跟我抱怨，说是才刚出狱你就立刻放闪闪瞎他的眼睛。」

说完，浑身都是结实肌肉的男子露出充满野性的笑容。他正是办公室的主人，王国的少数精锐、率领卓格夫队的指挥官波尔德•卓格夫。

对威尔海姆来说，他是两年前的直属上司。即便是孑然一身的现在，两人之间的信赖也让威尔海姆第一个就找上他帮忙。

用皱脸咂嘴带过他的笑声，可看出他们之间的距离。

「想用那个理由把我再扔回地牢？」

「才不咧。不过，你要懂得分寸。但是话又说回来，在众目睽睽之下搞得那么盛大，现在才讲这种话可能也没用了。对吧，特蕾希雅小姐。」

「咦呀！」

话题突然落在自己身上，人也在现场的特蕾希雅发出混杂惊讶和羞耻的声音。

「呼哈！怎么了，特蕾希雅小姐。很可爱又惹人怜爱的叫声耶。」

「喂，别太超过，少闹她。你也冷静一点。」

挡住特蕾希雅免受低声沉笑的波尔德的视线所害，同时又朝身后的少女这么叮咛。

「好、好的。对不起。我有点紧张。」

他的话让特蕾希雅垂下头缩小身子，不过又调皮地吐舌。

看著他们的互动，这次轮到波尔德忘记发笑，睁大双眼。

「真惊人。我头一次看到特蕾希雅小姐……『剑圣』殿下的这种表情。」

「是说你跟这家伙之间有什么交集吗？」

「你不在的这两年里，卓格夫队仍经常在最前线冲锋陷阵。那意味著与特蕾希雅小姐齐头并进。想当然耳，也就有很多机会见到她。」

一提到自己不在的这两年，威尔海姆也只能默然。

不过波尔德打住这方面的话题，反而用难过的眼神看向特蕾希雅。

「不过，交谈机会不多就是了。」

「呃……那个时候，我的态度很差，实在很丢人现眼……」

「这点我们是彼此彼此。讲到当年，要亲近我是很难的。不如说应该要感谢您没有把剑对著我吧。」

「你们以前到底是有多针锋相对啊……」

他们以前的关系似乎紧张得超乎想像，波尔德和特蕾希雅都没有纠正自己的话。总之听他们的说法，就算只有表面，但能够像这样谈笑风生就已经是奇迹了。

「格林和卡萝小姐呢？」

「在特蕾希雅的宅邸见过面了。一个还是一样啰哩叭唆吵死人，另一个还是用笑脸烦人。」

「既然那两人看起来没变，你可要感谢他们的体贴嘿。」

「什么？」

这番意有所指的话让威尔海姆讶异，但波尔德没有回答他的疑问。他抓抓自己的蓝色短发后转换话题。

「是说，你为什么来？认识你这个人，我是不会期待你单纯只是来重温友谊的。就像平常那样单刀直入地说出来吧。」

「那还用说。──不，抱歉。这样太没礼貌了。」

为自己快嘴回呛的坏习惯咂嘴后，威尔海姆重新面向波尔德。接著隔著办公桌朝他鞠躬。

「波尔德，我想拜托你。我知道这样讲很自私……」

「想要回军队，是吧？」

「既然你知道那就好谈了。我……」

「我要先说清楚。很遗憾，没那么容易。」

「────」

面对把决心说出口的威尔海姆，波尔德以苦涩的声音回绝。以「猛犬」这个绰号闻名的男子抱起粗大的手臂，厉目看向威尔海姆。

自己不会被气势压倒，但给人压迫感的眼神中却不带威胁。

「想想你两年前脱离军队的方法吧。留下一张纸，而且还是在内战最激烈的时候逃军。……不管事实为何，以客观角度来看就是这样。这样的人，谁会乐见他回归？」

「这个……」

「抱歉啦，生你气的人我也有一份。你平安无事回来我很高兴，跟特蕾希雅小姐两情相悦的事我也由衷祝福。但是，这次的问题跟我个人情感是两码子事。军中任何事都要照规矩来，懂吗？」

笑意消失的波尔德所说的话再正确不过，威尔海姆根本无从辩驳。

威尔海姆当然没忘记两年前在个人判断下孤身前往战场，只在兵营留下表达要脱离军队的纸条一事。当时的他也做好了觉悟，只不过是自以为是又任性的觉悟。

故乡被战火威胁，于是威尔海姆舍弃刚受封的骑士身份，脱离军队前去援救出生地家乡。

然而却还是迟了一步。故乡被大火烧毁，自己也命悬一线。最后还对前来救援的同伴不告而别就销声匿迹。

无情无义到极点。其实现在能见到波尔德说上话，都要感谢他的不计较。

「闯入典礼大闹一场的事也一样。幸亏吉欧尼斯陛下是心胸宽大之人，不过你会被释放可是出于特蕾希雅小姐的请求。」

「特蕾希雅的请求……」

正在反省自己的有勇无谋时，波尔德提到了特蕾希雅。特蕾希雅一脸为难，用手指卷绕自己的红发。

「是真的吗？」

「真要说的话是真的啦……不过那不是什么大不了的事喔？」

「真是的，爱真伟大。我听说是将吉欧尼斯陛下此次赐予的功勋奖赏和权利全部拿来换取对你的特赦。该说你的心上人是无欲无求吗……」

「我很贪心的，只是只贪自己最想要的东西。」

「就是这样啰。你这个幸运儿。」

波尔德闭上一只眼睛调侃，威尔海姆痛苦呻吟。

即便是威尔海姆，对刚刚的话都忍不住大吃一惊。因为那意味著特蕾希雅将终结「亚人战争」的功勋奖赏全都拿来换成让威尔海姆离开牢狱的代价。

那相当于她献上了强迫自己投身于不期望的战斗中的两年岁月。

「──长久以来的内战告终，军队重组的方向性稳定之后，招兵买马的频率就会回到战前那样吧。你也别执著从军，趁这个机会好好享受和平时代如何？」

波尔德用格外沉稳的嗓音对著沉默的威尔海姆这么说。这话实在出乎意料，威尔海姆抬起头，只见波尔德缓缓摇头。

「只沉浸在战斗中不能算是活著。和你身旁的女性共结连理，慢慢地度过一生也是不赖的选择。你不觉得吗？」

他接著说了下去，视线则是投向手撑著的办公桌上。无意地顺著视线看过去的威尔海姆发现，办公桌的一角放著镜片龟裂的单边眼镜──是波尔德以前的随从的遗物。

看到那个，就了解了他劝自己好好过著平稳时光的真正用意。

「既然你幸存下来，活著而且还见到面了。……这样还不满意吗？」

「──今天我就先回去了。打扰你了，波尔德。」

波尔德努力让声音不带感情，反而让人窥见内心。那声音令人承受不住，威尔海姆背过身离去。

「啊，威尔海姆！真是的！波尔德大人，对不起。我也先告辞了。」

「我才是，没能帮上什么忙很过意不去。──威尔海姆。」

波尔德严肃地回应慌慌张张站起来的特蕾希雅，接著叫住手即将搭上门的威尔海姆。

然后朝著停下脚步但没有转过身的背影说：

「不管怎样，你回来得好。只有这句是我的肺腑之言。你这混帐王八蛋。」

「……我现在切身感受到自己有多混帐王八蛋了。」

「那就尽情感受吧。你欠缺的就是这份自省和对周遭的人的关心。」

「明白了，波尔德队长。」

彷佛回到以前的关系，挖苦完对方后，威尔海姆就离开了波尔德的办公室。

在石砌通道上踩出脚步声，回想方才的对话，威尔海姆叹气。走在他身旁的特蕾希雅冒出来盯著他的侧脸看。

「所以，你接下来要怎么办？从军没有下文还被赶出来。」

「就跟我刚刚说的，先离开。我现在知道从正面发动攻击无法挽回过去做过的事了。但即便只有这样都还算是有收获。」

「其实……可以由我来帮你交涉看看啦。」

「你再继续宠我的话只会让我更凄惨。」

威尔海姆停下脚步，手指向特蕾希雅。看著他的指头，特蕾希雅尴尬地低吟。

「呜……对不起我自作主张。……你生气了？」

「我倒觉得你气我的理由比较多呢。」

「是这样吗？不过，现在与其说生气，幸福的理由比较多又大……」

特蕾希雅思索，想著想著就露出傻气的微笑。手贴胸膛像在抱著重要东西的样子，令威尔海姆打心底惊讶，用鼻子喷气叹息。

接著视线离开她，望向窗外，说：

「……出狱那件事，很抱歉。给你添的麻烦超乎我的想像。」

「没关系啦。我说过了，我只是为了得到想要的东西，才去请求陛下的。反正那本来就是无处可用、有跟没有都一样的权利。」

「但是，让你做到这地步，我却还是个无业游民。」

「不用那么沮丧……别担心，生活方面有我罩著呢。」

挺起丰满胸部的特蕾希雅笑得更加开朗，勉励威尔海姆。可是她那样的女性温柔，有时会伤了男性的矜持。现在更是格外显著。

加上自己的不争气，威尔海姆彻底反省自己的莽撞。

「我一直跟你说不要宠我了吧。」

「啊！刚刚那不算宠，而是有万一的时候当你的后盾……好痛！」

弹了一下马上忘记自己原本怎么说的女人的额头后，朝著泪眼婆娑的她指向窗外。威尔海拇指的方向是特蕾希雅位在街区的私人宅邸。

「你在旁边的话，我半颗脑袋都会被你占据，害我考虑个事都没有进展。你先回去。」

「好过分！这样讲真的太过分了！」

「谁叫你一直动来动去，烦死了。我晚上会回去。你先回宅邸──」

威尔海姆甩甩手正想走开，却感觉衣襬被揪住而停下脚步。

回过头就跟捏著他上衣衣襬的特蕾希雅四目交接。她轮流看威尔海姆的脸和自己的手指，然后歪头说：

「奇怪？这个是……叫那个吧？」

「什么那个啦。──我答应你，我会回去的。所以放你一百二十个心。」

「……你真的会回来？不会又擅自不见两年吧？」

「搞什么，这么爱担心……我知道了。是我害的。我道歉。」

轻轻松开捏著衣襬的手指，威尔海姆将特蕾希雅抱入怀中。

一瞬间，特蕾希雅浑身一僵，但马上就全身放松委身于他。温柔抚摸她的背好半晌后才放掉她。而她的表情已经不再不安。

「回宅邸去吧。我马上就处理完杂事回去的。」

「嗯，我会做晚餐等你回来。我会做就算冷掉也能吃的食物。」

「我会赶在饭菜还没冷的时候回去的。」

深知自己不受信任，威尔海姆用手指推特蕾希雅的额头。朝著手摸额头的特蕾希雅点头后，这次才真的和她分开。

直到弯进通道的转角，特蕾希雅的视线都牢牢钉在背后，但为了彼此好，威尔海姆没有回头，以免依依不舍、没完没了。

「不过说真的……丢脸死了。」

在宅邸被卡萝说教，方才波尔德所说的言论，在在都沁入骨子里。

两年前，威尔海姆凭自身意志蔑视的诸多关系与累赘，如今全都朝著回来的他张牙舞爪。这可以说是自作自受的因果报应。

但很遗憾的，威尔海姆的内在并没有柔软到可以改变自己的信念。更何况他可是这个世界的芸芸众生中最为固执的人。

因此过去的两年以及得到报应的现在，他都不容任何人否定。

「────」

重下决心，威尔海姆收敛表情细细思考。

寻找著目的地的指标，目光不意驻留在外头的风景上。双脚自然而然地走向了那个地方。

──前往这两年来，真正没有改变的地方。

5

走到城外，踏上卫士交错来往的石板路。

两年前自己并不喜欢这条路，更遑论走在上头。现在也还是不喜欢，只是心态跟以前不一样。

即便如此还是走到这儿，是因为想法改变，认为有这么做的意义和价值。

「好久不见了。──皮波特。」

站在刻了许多名字的石碑面前，道出一个名字。

那是卓格夫队前副官的名字，也是波尔德桌上坏掉的单边眼镜的主人，更是内战时失去性命的战友。

──战友。没有机会直接对他传达这一点，威尔海姆到现在都还发自内心感到后悔。

刻在石碑上的名字不只有皮波特，还有难以计数的名字。战亡士兵的名字多到一块墓碑刻不完，因此在这不甚宽敞的墓地里有好几块战死者墓碑排列成行。──这里是只留下战死者名字的军队公墓。

过去因为在死亡中找不到意义，因此威尔海姆视此处为忌讳讨厌的地方。

「……抱歉，别说鲜花还供品了，我什么都没带。就宽宏大量原谅我吧。」

可能因为内战结束了吧，墓区里放了很多鲜花和供品。

在前往公墓的路上，几度跟表情阴郁的卫士擦身而过。扫墓的人接连而来，来悼念在战场殒命的同袍，对已经无法回应的他们说话。

「────」

因为没有带供品这类东西，因此也没法像其他人那样扫墓。所以威尔海姆就站在墓碑前面，静静地敬礼。熟悉又亲切的王国军行礼法，但穿著便服，而且连可以高举行礼的剑都没带，因此这个敬礼徒具形式又不好看。

可是他还是以完美的举止完成这个敬礼。若是有人看到的话，想必会赞叹吧。

总是啰唆著规矩，嘴巴酸不溜丢地灌输自己敬礼的作法。威尔海姆秉持著对那个温文儒雅的男子的敬意，做出不辱他教导的敬礼，作为对死者的饯别礼。

「────」

没有多说一个字。因为没有必要。

原本就不是期待能有所得才来到这里，只是陆续和怀念的面孔打过照面后，就觉得不来这里打招呼说不过去。

就只是这样而已。──然而会这样想，究竟是吹了什么风？

该说久别一见的皮波特，还是一样劳碌命地照顾他人吗？

「──唉呀。真没想到，会在这种地方遇到意想不到的人呢。」

「你是……」

背对墓碑，准备要回去的时候却停下脚步。因为和站在公墓入口，兴致盎然看著自己的人对上了眼。

是名年约三十五，身材瘦长的男子。从外表看起来像是文官，跟骨子里就是武人的威尔海姆不太可能熟识。不过威尔海姆立刻就想起他是谁。

是内战期间，召威尔海姆至大本营会议报告的人──

「名字是叫……喔对，麦克罗托夫。」

「你还记得的样子，真是太好了。威尔海姆•托利亚斯殿下。──我可不曾忘过你喔。」

这么说的男子──王国宰相辅佐麦克罗托夫•马克马洪露出亲切和蔼的笑容，理性的双眸映照著威尔海姆。

6

在一半的夕阳沉入西方天空之时，威尔海姆按照约定回家了。

说是回家，其实是回到特蕾希雅的宅邸。感觉用「回家」的字眼好像有语病。

「真乖，好好回来了。有遵守承诺的人很伟大喔。」

但因为出来迎接的特蕾希雅心情很好，所以也就觉得没必要订正了。

接受她的热情招呼，被带到餐厅的威尔海姆大吃一惊。因为不算很大的餐桌上塞满了形形色色的料理。

这些色彩缤纷的料理著实叫人佩服她的厨艺，但是──

「做这么多……吃得完吗？怎么看都不只两人份吧。」

「放心吧。待会卡萝他们也会过来，四个人吃就可以了吧？毕竟我不知道你喜欢吃什么……不过我想让你觉得美味，所以就有什么材料就做什么。这样一来，总会有你喜欢吃的吧？」

「我不挑食但也没有爱吃的。」

「那我亲自下厨不就没意义了！」

咬牙切齿的特蕾希雅把派放进大盘子后摆在桌上，这才算大功告成。

怎么想，这些量要说是四人份也太多了，但搞不好特蕾希雅或卡萝是个大胃王也说不定。顺带一提威尔海姆的食量跟普通人一样，格林反而有点小鸟胃。

「你擅长做料理这点让我很意外……应该说，怎么不是叫佣人做？」

「我可是有清楚听到你说了什么喔。──因为我不喜欢生活的大小事都交给别人处理。可以自己做的我都想自己做。所以说，照料这间宅邸的人，我也只要求最少的人数。反正我以前也不太来这里。」

用手指搔搔粉白脸颊的特蕾希雅表情不带虚假，如实以答。

这间宅邸应该是「剑圣」特蕾希雅被赐予的奖赏之一。跟结束内战而被给予的奖赏不同，这里听说是「初次出征」后被给予的。

也就是说，这间屋子从两年前开始就是特蕾希雅的。

但她却几乎没来使用过，当时她过的生活叫人难以想像。一定就是不断转战各地，战斗到没日没夜吧。

从这些事情的边边角角可以触及特蕾希雅担任「剑圣」时的日子。每次意识到这点威尔海姆就会想：不该放著她一个人。

──不可以再让她握住不想握的剑。

「……威尔海姆？」

特蕾希雅睁大双眼，威尔海姆伸手摸她的脸颊。

手指滑过柔软的肌肤，视线被倒吸一口气的嘴唇吸引。粉红色嘴唇和温热的体温，好想就这样抱紧，放任感情蹂躏它们。

「威、威尔海姆……不行。那个，就是，晚餐会冷掉……」

「你不是说会煮冷掉也能吃的食物？」

「可、可可可是！食物还是趁热吃比较好吧！？」

被搂过去而慌张失措的特蕾希雅口气变得很奇特。少女显得狼狈不堪，威尔海姆抚摸她的红发，小心抱住她，免得伤到她光泽亮丽的秀发。

在心爱的男子的体味和心跳下，特蕾希雅的双眼被热情融化，吐出灼热的呼吸──

「──唔！还是不行！卡萝他们马上就到了！」

但最后是特蕾希雅的自制力推却所有烦恼，同时推开威尔海姆的胸膛。迅速远离的少女红著脸整理头发和紊乱的呼吸。

「今天不行。因为我们要四个人快乐地一块共进晚餐。我们累积了好多话……没错，很多话！威尔海姆也有吧？像是这两年来怎么生活之类的？」

「我是觉得就算讲出来，听的人也不会觉得愉快啦。」

「才没那回事！」

被温香软玉逃掉的威尔海姆有点不高兴地回应，特蕾希雅则是用力摇头。

「两年是很长的时间喔。会发生很多事，心情有所改变也是很正常的……」

「我没有。」

「那样我是很高兴！可是都过了两年……对啊，像是你刚好在典礼当天回到王都，这不是很巧的事吗。」

「全国上上下下全都因为你而热烈庆祝，哪里巧合了……」

「是喔！这样啊──」

想要打哈哈带过但技巧太差，发言已经前后不连贯了。她混乱的样子让威尔海姆苦笑，不过又马上沉思。

在典礼当天回去是刚好赶上，并非巧合。不过之所以不是巧合，有更主要的原因。那就是──

「这两年来，我经常听罗兹瓦尔讲你的事。」

「……经常？」

「嗯。这两年我都在国内各处流浪，但不管走到哪里都会碰到那个女人。算了，多亏如此才能赶上终战典礼，要是不感谢她的话又要被说没良心了。」

说著说著，威尔海姆的脑中鲜明浮现出一名蓝色长发女人──罗兹瓦尔•J•梅札斯。

跟那个左右两只眼睛颜色不同的女子，在内战初期就结下孽缘。尤其对威尔海姆来说，她是每次见面就要戏弄自己、大意不得的对象。

威尔海姆失踪的这两年，就只有她会出现在自己面前，告知自己王国军和特蕾希雅的近况。而且每次都被辱骂驱赶，却还是不屈不挠地跑来找自己。

事实上，能够赶上典礼开始的时间，都要多亏了她的情报──

「你跟别的女人，在这两年间常常碰面……」

「……特蕾希雅？」

「威尔海姆，手可以借我一下吗？」

「──？」

才想说她在喃喃自语什么，突然又满脸笑容。这样的举止令威尔海姆皱眉不解，但还是乖乖伸出手。

接著，特蕾希雅轻轻握住他的手腕──下一秒威尔海姆便感觉天旋地转。

「──呜、喔！？」

「我情绪有点不太好，先回房间了。晚餐你就跟卡萝他们享用吧！」

「一般都说心情不好，不会说情绪不好……」

「随便啦！」

特蕾希雅理都不理一屁股跌坐在地的威尔海姆。她用力踩著脚步快速离开餐厅，威尔海姆只能望著她的红发瞪大眼睛。

「到、到底怎么了……？」

「刚刚的声音是！发生什么事……威尔海姆，你怎么会倒在地上？」

不知道特蕾希雅为何突然生气而傻住，这时听到声响的卡萝跑了进来。跟在她身后的格林讶异地看著瘫坐在地的威尔海姆，然后环视整间餐厅。

「特蕾希雅大人怎么了？该不会是亚人的残党跑来报复……」

「慢著，没那么夸张。我不是很清楚，但只是特蕾希雅突然生气然后把我摔向地板。……我竟然被摔倒了。」

「现在是为这种事受伤的时候吗！特蕾希雅大人生气可不是小事。你做了什么？说了什么？大人她为何生气！给我从实招来！」

被轻松摔倒而自觉败北的威尔海姆，紧接著被卡萝痛斥。卡萝本来就很没耐性，但一扯到特蕾希雅，这个特性就会更加明显。

格林靠近想要安抚她却被甩开，卡萝就这样指著威尔海姆说：

「到底发生什么事，给我钜细靡遗地说清楚！我听过之后再决定要判你死刑还是斩首！」

「冷静点。我只是稍微讲了一下这两年的事情。像是在国内流浪，罗兹瓦尔很常出现在我面前，还有终战典礼……」

「跟罗兹瓦尔大人！？你竟然提到罗兹瓦尔大人的名字！？不，你偷偷跟罗兹瓦尔大人见面几次了！？」

「又不是我联络她。是她自己跑来找我……」

「啰唆，你这个无耻的家伙！就算只有一点点，但稍微相信了你的我简直是白痴！」

毫无来由的中伤让威尔海姆忍不住闭上嘴巴。但卡萝看都不看他一眼，就直接冲出餐厅，跑向特蕾希雅的个人房。

「特蕾希雅大人！特蕾希雅大人！请您振作！卡萝就陪在您身边！」

她闹哄哄地奔过走廊，追在特蕾希雅之后离开餐厅。望著这一切发生，威尔海姆还是坐在地上不发一语。

「────」

而真正闷不吭声的格林，朝著他伸出手。

威尔海姆叹气，借助他的手站起来。

「……干嘛啦？」

「────」

不出声的格林用责备的眼神看过来，威尔海姆忍不住凶回去，但是任谁都听得出声音里头没有霸气。

「是我错了吗？」

『只有你有错。』

是一开始就准备好了吧，格林立刻拿出纸在上头大大写上这几个字。

「混帐。」

威尔海姆一把夺过那张纸，撕破泄愤，然后把手中的纸片揉成一团，接著回过头看著餐桌皱眉。

战力只有两人，敌方的数量却压倒性的多──面对桌上的满汉全席，只能硬著头皮上了。

「靠我跟你收拾了。……可不许有意见啊。」

「────」

听了威尔海姆的要求，格林垂下肩膀乖乖入座。坐在他对面的威尔海姆也搓著双手，准备挑战自己拿的份量。

整桌还温热的料理，每样都是为了取悦威尔海姆的舌头而聚集在此，然而现在吃起来却觉得比变冷的食物还要寂寞。

7

──结果，特蕾希雅不但没有回来用餐，误会也没有解开。

「哼。我很怀疑真的是误会吗。」

不悦地这么说的，是来吃早餐的卡萝。

跑去找气噗噗回房间的特蕾希雅，花了一整晚听取事情始末后，伶俐的美貌毫不隐藏对威尔海姆的敌意。

虽然平常讲话就带刺，但现在的视线锐利程度更甚以往。

「────」

「啊，格林，对不起。其实早餐应该是由我来准备的……」

『不用在意。』

格林给她看笔谈纸上的字后，卡萝这才卸下严肃表情。

放在餐桌上的早餐全都是由微微苦笑的格林做的。口味跟特蕾希雅做的相比略显逊色，不过以前在卓格夫队负责伙食的他手艺并不差。

至少比威尔海姆准备的还要高级许多。

『别看我这样，我老家可是旅社。』

意识到威尔海姆的视线，在纸上行笔的格林显得有点自豪。不管怎样，一伙人就围著格林做的早餐开始用餐。──少了特蕾希雅，只有三人。

「所以？花了一整个晚上都还没法把她拉出房间吗？」

「这就证明特蕾希雅大人的心灵受到很深的伤害。跟你有关的事，全都是因为你的不检点行为和态度导致的。不要脸。」

「挑衅过头啰，带刺女。少得意忘形了。」

在用餐之前，威尔海姆和卡萝就隔著桌子互瞪。

围绕著人不在现场的特蕾希雅，两人的关系十分复杂。不过他们都很重视特蕾希雅，但正因为这样，使得今天早上火药味十足。

一触即发的剑气激出火花，餐桌的气氛变成战场──

『到此为止。』

就在这时，两人中间被插进一张两面都写了相同文字的纸。无言的盾士轮流看了看战友和恋人，然后指著桌子。

停止无意义的行为，吃饭吧。这样的想法清晰地传达给两人。

「……对不起，脑子热了起来。来吃饭吧。」

面对格林罕见的强硬主张，卡萝迅速投降并道歉。接受恋人致歉的格林沉稳微笑，然后再度凝视威尔海姆。

「────」

虽然笑容跟对卡萝露出的微笑很像，但魄力却天差地远。当然，威尔海姆没有被压过去，不过他还不至于去争谁对谁错。

「……抱歉。」

别开视线，道歉的声音小到像是吐气。格林满意点头。

就这样，格林全面获胜。大家终于开始享用早餐。

「好怀念的味道。」

喝了一口咸汤，熟悉的味道让他忍不住咂嘴。

露宿野外的时候，远征结束回去的晚上，格林的咸汤总是吸引队上许多人品尝。用现有的食材做出美味食品，不愧是老家开旅社的。

看到威尔海姆因怀旧而表情缓和，格林眯起眼睛。接著他在新的纸上振笔疾书。

『昨晚没问你，你要回军队？』

递出来的纸上问题，是在问威尔海姆今后的安身之计。

字写得很快，文字的跃动感反映出格林的急躁心情。可能是他非常想问的问题吧。

昨晚惹恼了特蕾希雅，导致两人拼命地解决四人份的食物，根本没法从容地聊天。

面对格林兴致勃勃的面孔，威尔海姆喝光咸汤后，说：

「关于那件事，我跟波尔德讲过了，但结果是不欢而散。那家伙一直讲些自以为伟大的话。」

「不是自以为，是真的很伟大。卓格夫卿在内战有所贡献，所以有可能会被邀请加入王国军的大本营。以爵位来看可说是特例。为此有可能内定调升爵位……」

「你知道得可真详细。格林会嫉妒喔。」

一句话就同时揶揄格林和知道波尔德要升迁还洞察王国内情的卡萝。但是威尔海姆的讽刺，却被卡萝接下来的话给整个粉碎。

「因为家业的关系，所以才会详知王国内情。要是特蕾希雅大人离开『剑圣』之位，那我就不清楚会怎样了。」

特蕾希雅被给予的「剑圣」称号──卡萝对这个立场所拥有的见解。

虽是理所当然，但对威尔海姆而言可不能说事不关己。

「威尔海姆，我希望特蕾希雅大人能够和乐笑著过生活。」

「────」

「你要走哪条路，老实说我一点兴趣都没有。但是，若是关系到特蕾希雅大人的幸福的话，那就另当别论了。──所以说，不要做出半吊子的行为。」

修长睫毛颤抖，卡萝用认真的眼神直射威尔海姆。蕴含在双眼和声音里的气概，一定是她日日为特蕾希雅著想的结晶。

为「剑神」所爱的少女，天生就拥有自己不期望的力量。一直为她担忧著急的不是只有威尔海姆。

所以──

「──嗯。我也是，绝对不容许自己做出那种事。」

颔首的威尔海姆，也用不输卡萝气概的气魄这么回答。

8

结束充满紧迫感的早餐时光后，格林和卡萝便离开了宅邸。

卡萝直到最后都还在对威尔海姆叮咛特蕾希雅的事，格林边规劝她边留下勉励的话：『我在军中等你，无业游民先生。』

「每个都讲得很简单。」

目送两人离去，被留在屋子里的威尔海姆虚脱地喃喃自语。

问题堆积如山，而且都不是光靠挥剑就能解决的。而威尔海姆本来就不擅长解决这类问题。

说实话，他除了战斗别无其他才能。因此，现在可说是四处碰壁。

连窝在家里都有拒绝见到自己的女性──连要把心上人带出房间都没办法。

「特蕾希雅，我有留早餐。你要吃喔。」

敲门出声叫唤，但房间的主人没有回应。威尔海姆便将她的早餐留在茶几上，本来要就这样离开的──

「还有，我接下来要出门。我晚上就会回来，所以用不著担心。……今天一块吃晚餐吧。」

什么都不说就外出会让她不安，是反省这两年后所得出的结论之一。

怀抱著这样的想法如此传达出去后，可以听见房间里有微弱的衣物摩擦声。感受到这样的反应，威尔海姆判断刚刚的话有传达给对方，于是离开了宅邸。

结果，半天都没跟特蕾希雅打照面，就这样一个人走在早上的王都里。

好久没有带著这么沉稳的心情步行在王都内了，街头的气氛给人的感觉不一样，威尔海姆对此微微瞪大眼珠。

跟两年前「亚人战争」打得如火如荼的时候天差地远。

外观大致上没什么变，但来往行人的表情和心情变化都如实地呈现在气氛中。可能是心理作用吧，连阳光都感觉比较明亮温暖。

内战期间，王国内部总是弥漫著不安与不稳定。如今那份阴霾被扫除，人心又恢复了安定与平稳。──这是好的变化。

而这正是特蕾希雅持续挥剑两年的结果所造成的变化。

「────」

以「剑圣」身份度过的时光，痛苦与不讲理想必是接连不断吧。但即便有那样的时光，诞生出的和平并不减其价值。

应该要对这副光景感到自豪，还是该感到遗憾呢？威尔海姆不由得抱著这等复杂的心情。

「──我跟宰相辅佐有约。我是威尔海姆•托利亚斯。」

「是。我有听说。请往这走。」

感情在心中搅和在一起的同时，威尔海姆的脚走向王都最高处──露格尼卡王城，并告知在城门看守的卫士访问理由。

在强壮的卫士带领下，安静地走在城内的走廊。

还在军队时，有进过城堡好几次，但从来不曾像这样为了个人私事而进来。城堡给自己的印象就是缘份似深又浅的地方。

而最后一次进城，是在骑士授勋典礼的时候──

「宰相辅佐就在这里等你。」

卫士的话打断回想，威尔海姆在目的地前面和卫士分开。敲响漂亮的木门，里头立刻传来回应：「请进。」

房间里头的装潢，以王国宰相辅佐的头衔来说显得朴素。里头就只有办公用的书桌和接待用的沙发与茶几，再来就只剩下几座书架。

房间的陈设彰显主人倾全力在工作上，也如实反映出主人的气质。

「欢迎光临，威尔海姆殿下。请坐。」

「哦。」

在柔和语气的邀请下，威尔海姆正大光明地坐在待客用沙发上。

慢慢坐在对面的，是瘦个子文官麦克罗托夫。他正是跟威尔海姆约好碰面的人，也是掌握威尔海姆能否回到王国军的关键人物。

至少，威尔海姆是抱著这样的希望，才来见他的。

「因为昨天没能聊得更深入，才会劳烦你来这一趟，真是抱歉。」

「……不会。有劳你在不到一天的时间内腾出空来，我才要道谢。」

「──呼嗯，原来如此。确实就如卓格夫卿所言。」

打完形式上的招呼后，麦克罗托夫温和笑著点头。这反应让威尔海姆挑眉，结果对方摊开双手说：

「没什么。毕竟除却单方面的认识之外，我对你的印象就是四年以前的事了。回想起当时对你的看法，就对你的变化有颇深的感慨。」

「单方面的认识……？」

「关于这点没必要惊讶吧。在庆祝内战结束的典礼上，你可知道国内有多少人前来共襄盛举？现在大家都认识你了。」

麦克罗托夫开心地笑，威尔海姆则尴尬地陷入沉默。

那个「单方面的认识」实在无从辩解。虽是暂时的，但威尔海姆的长相和名字确实炒热了王都。

其实现阶段那股热度尚未冷却，只是威尔海姆本人没有自觉。

而且被他与「剑圣」的关系所吸引的多数人正在策划将他们两人的邂逅与恋情谱成「歌曲」，而他丝毫未觉。

这姑且不论──

「大众现在知道你有不输『剑圣』的实力。因此只要你有那个意思，要回王国军是轻而易举。我敢保证。」

「是、是这样吗？可是这跟波尔德说的差很多。」

「当然，卓格夫卿的意见也有他的道理在。以事实来说，你舍弃了受封的骑士称号，以个人为优先而脱离军队。对此感到失望和反感的人应该也不少吧。」

「────」

「但是，那些问题都可以靠时间解决。重要的是，你的剑术实力对王国军有益，而你本人也希望回到军队。」

麦克罗托夫手贴下巴，整齐地娓娓道出条理。听了宰相辅佐强而有力的断言，威尔海姆静静地端正坐姿。

文官与武官，两者之间有著不容置喙的鸿沟，即便如此还是无法忽视宰相辅佐的意见。毕竟要让一介士兵归队，对他来说相当容易。

「剑鬼」威尔海姆回到王国军的可能就在眼前，只不过──

「──就算认可你回到军队，也不可能撤消特蕾希雅大人的称号。」

「──唔。」

这么一句话，就让威尔海姆内心剧烈动摇。

见威尔海姆的反应，麦克罗托夫降低音调，说：

「对王国军而言，『剑鬼』和『剑圣』的战斗力都大有裨益，没有放手的理由。这一点，我想应该是没有反驳的余地吧？」

「可是，那家伙不期望上战场。」

「当事人的想法姑且不论。」

之前的温和气氛一扫而空，麦克罗托夫冷酷地说。面对「剑鬼」的叫喊，宰相辅佐面无表情地眯起眼睛。

「就算特蕾希雅殿下抗拒，但她并非失去力量。而且只要是王国的要求，我猜想她是不会拒绝的。」

听到麦克罗托夫用推论的形式所道出的确信，威尔海姆噤声。

如他所言，特蕾希雅是个心地善良的女子。纵使心底根本不想握剑，但一旦时代让她非握不可，她也会吞下眼泪拿起剑。

威尔海姆深知这点。但即便如此，还是不希望让她持剑。

「当然，这终究只是我的推论。不过王国军的将帅们也会做出同样结论吧。这点毋庸置疑。」

麦克罗托夫无情地否定威尔海姆心中的哀求。跟自己回到军队的事情不同，包围特蕾希雅的问题不见解决征兆。

见威尔海姆低头，麦克罗托夫轻声吐气。

「就先从你返回军队这件事开始著手吧。这点不用担心。不过，关于特蕾希雅殿下……嗯，建议你好好讨论商量看看。」

「讨论商量？」

「一个人再怎么苦思，也无法轻易得出结论。就算误入歧途，也无人可以制止。既然如此，就别独自烦恼，而是该借用别人的智慧。」

这算是建议吗？麦克罗托夫的话让威尔海姆皱眉。

望著年轻人的宰相辅佐闭上一只眼睛，展露一开始的沉稳微笑。

「有些事，只有你能办到。──仔细想想吧。」

9

在麦克罗托夫的帮助下，为威尔海姆返回王国军一事挂下成功保证。

然而从王城回贵族街的路上，他的心情依旧郁郁寡欢。

「────」

脑子里都是刚刚麦克罗托夫说过的话。结果只是思考的主题改变，无法用剑解决事态的无力感反而加重了。

就算失业的问题解决了，但最重要的特蕾希雅的问题却没能解决。

「就算叫我讨论商量……」

可以这样的人早就谈过一遍了。

格林和卡萝不用说，也拜托过波尔德和麦克罗托夫。也跟不会说话的皮波特说过话，现在还可以讨论的，顶多就剩特蕾希雅本人了吧。

但是找她商量的话，想也知道她会怎么回答。

只要国家向她求救，她一定会藏起自己的感受，微笑点头答应。

「那个笨蛋，都不懂别人的心情……」

在脑内的想像中被痛骂的特蕾希雅很可怜，不过这是十分真实的想像，所以就算要自己赌上性命也无所谓。因此，为了这件事，威尔海姆已经用光了可以商量的对象。

为自己的交友圈之狭隘感到悔恨，他边呻吟边仰望天空。

「再来就只有罗兹瓦尔了吗，虽然不想拜托对方……那家伙，人在哪呢？」

在蓝天里浮现的候补人选，让威尔海姆不悦地咂嘴。

罗兹瓦尔•J•梅札斯。若是那个博学又擅长突发奇想的怪人的话，应该就能提供有效的意见给烦恼中的威尔海姆吧。

只是威尔海姆有所矜持，不愿去拜托她。毕竟现在会跟特蕾希雅闹僵的原因之一也是她。就算是木头人威尔海姆，也明白去找她商量特蕾希雅的问题是个下下策。

像这样挑挑拣拣后，益发无计可施。

「凭我的脑袋有办法想出答案吗？我的事和特蕾希雅的事搞得我一个头两个大。要是至少能把问题统整为一……」

理想状况是威尔海姆归队和特蕾希雅退回称号。但如果可以铲除特蕾希雅往后握剑的机会的话，那就算没法回到军队也没关系。

自己不会错看重要的事物。只有这点可以完全信任现在的自己。

「有没有人呢，脑袋灵活又懂这种状况，擅长诡辩和见风转舵……」

寻求刚好可以配合自己需求的商量对象时，威尔海姆突然停下脚步。

在一瞬间闪过脑海的人，完美地符合以上的条件──脑袋灵活又了解状况，而且经营人际关系的手段出类拔萃。

「──同时骗过六个女人，所以被关在监狱塔的家伙。」

回过头，威尔海姆眯起蓝眼，看著王城旁边的石塔。监狱塔的威容正在俯视远去的威尔海姆。

「所以，想要建议的你刻意来见我吗。我感动到都要哭了，小哥。」

「少油嘴滑舌。时间有限。」

踩在地牢的冰冷地板上，威尔海姆隔著铁栅栏瞪著里头的男子。对此开心发笑的，是满脸胡渣的长发美男子──靠著自傲的舌头将六名贵族千金玩弄于股掌中，犯了恋情诈欺罪而被关进来的「六面三刀」欧尔菲。

仰赖当过数小时狱友的缘份，威尔海姆找上了他。连自己都觉得傻眼，但寻求观点角度异于相关人士的解决方案，是现下唯一的办法。

「不过吓到我了，没想到你就是那个打败『剑圣』的『剑鬼』。照道理来说你应该也被关在监狱塔里头的。哟～偷心小偷！」

「就算有铁栅栏我也照样有办法砍死你。要不要提早处刑呢？」

威尔海姆用剑气回应他的轻薄，但是欧尔菲却只是耸肩，丝毫没有害怕的样子。原来如此，他无疑是个胆识过人的家伙。

还是个能够同时和六名贵族千金小姐谈情说爱的人，若是没有厚脸皮的自信，那就不可能做出这种不经大脑的行为。

「话说回来，想帮助小哥你谈恋爱的人多得要命吧，我帮你有什么好处可以拿吗～？我可不做白工的喔？」

「只要我回到军队，授勋的骑士爵位也会恢复。那样一来受了你的恩惠的我就会为你说话。你离开这里重获自由的日子也就提早了。」

「好，这贼船我上了！我很帮得上忙的，老板。有什么需求尽管说。」

「现实的家伙……」

对方嘴脸转换之快速，令威尔海姆气焰消退，并开始向欧尔菲说明前因后果。

当然省去了细微的感情部份，不过对方不只嘴巴高明，也很擅长倾听，包含他在说话空档所提出的问题，威尔海姆几乎把事情赤裸裸地讲述殆尽。

「原～来～如～此呢。」

听完之后，「六面三刀」瞭然于心地点头。

「这段错综复杂的经过我都了解了。包括小哥比我想的还要蠢这件事在内。」

「砍死你喔。」

「就是你这种什么都想用剑解决的态度啦！」

只是轻轻威胁一下，欧尔菲就夸张地拍手。他的话让威尔海姆眨眼，接著欧尔菲将脸抵在铁栅栏上。

「你自己也说了吧？特殊技能就只有剑技，除了挥剑以外没有其他才能。也就是个没法用剑解决的话就充满缺陷的无用人类啦～」

「所以才伤脑筋啊。毕竟是用剑也使不上力的问题……」

「那就大错特错啰，小哥。为了重要的人，就算是自己不擅长的领域也想要做些什么的态度是很有男子气概啦，但却毫无理智。要多用脑袋，还有舌头，聪明合理地推动事情前进，懂吗？」

指责他态度不对的欧尔菲笑道，还朝他点头。

然后「六面三刀」对「剑鬼」的烦恼揭示出完全超乎想像的答案。

那就是──

「──既然只会挥剑，那就把问题改变成只要挥剑就能解决的形式就好啦。唯有这样，小哥才有胜算吧？」

他露出坏心的笑容，说完还朝威尔海姆眨眼。

10

──过了傍晚回到宅邸，就从餐厅闻到香喷喷的气味。

抽动鼻子嗅闻温和香气，像被引诱般往来源处走去。推开餐厅门进去，就看见正在把料理摆盘的红发少女的背影。

纤细的肩膀，细瘦的腰杆，左右摇摆的臀部，就算一直盯著看也不厌倦。

「──回来的话，要说『我回来了』吧。又不是闹脾气不说话的小孩子，该说的就该说出口。」

「我又不是因为闹脾气才不说话。」

「那不然你干嘛不说话？是在想要怎么道歉吗？」

头也不回的特蕾希雅，说的话很明显地在闹别扭。

我不说话是因为看你看呆了，但这话怎能说出口。到头来就只能沮丧地继续保持沉默。特蕾希雅傻眼地叹气。

「真是的，你很不老实耶。……虽然我知道你就是这样。」

「抱歉。不过，到底是吹什么风？」

「……说要一起吃晚餐的人是你吧，哼。」

鼻子喷气的特蕾希雅解开腰部的围裙，挂在椅子上。

今天餐桌上的料理是刚刚好的两人份。没有多余的碍事人物让人松一口气，但于此同时也对能这样共进晚餐一事感到怀疑。

早上自己讲的话，应该还不到重修旧好的程度──

「早餐是你做好放著给我吃的吧？那实在是太糟糕了……晚餐也要吃那种东西的话，我会受不了。」

「我不是有烤火加热吗。」

「那不是只有加热而已吧！？连中心都黑掉了！而且还只有材料的切片方式很高明，你是故意要惹我生气吗！」

特蕾希雅死咬著这点不放的反应，让威尔海姆颇感意外而皱眉。确实火力是有点搞错了，但应该还不至于不能吃才对。

读透了他的想法，特蕾希雅劝他坐下，并开口道：

「你这两年来的饮食状况让我担心。……该不会，都没人做给你吃吧？像是，你说的那个人……」

「如果你说的是罗兹瓦尔的话，那误会可大了。不要让我说好几遍。是那家伙自己跑来找我。我从来没有欢迎过她。最多只有感谢她一件事。」

「那件事是……」

「就是告诉我终战典礼的日子。不然的话，我就没法痛下决心去见你。」

「是、是这样啊。呃，那个，哦呵呵呵……」

面对面还若无其事地这么说死，让特蕾希雅面红耳赤。威尔海姆则是看向无力傻笑的她面前的料理。

餐桌上的食物份量输了昨晚许多，但是种类繁多，而且还没有重复。特蕾希雅的拿手好菜之多令人惊讶。

「你才艺真多。」

「才艺多算不上称赞吧？呵呵，不过算了。」

威尔海姆笨拙的称赞让特蕾希雅高兴微笑。睽违了将近一天的时间，终于又看到她原本的笑容。

那微笑令人不自觉感到安心，威尔海姆轻抚胸膛。

「来，吃饭吧。每一道都要给我感想，我好知道你喜欢吃什么。」

「每一道都好好吃。我昨天的感想就是这样。」

「今天这就行不通啰。因为我会观察你吃饭的样子。我会看穿你喜欢吃哪道菜。毕竟你的话根本没法当参考。」

自己的厨艺评价是有多低啊？威尔海姆端给她的早餐似乎点燃了她的料理魂，但假如以此为契机拉近距离，那么就算是残酷评价，自己也甘之如饴接受。

就这样被观察对每一盘食物的反应，晚餐时光平稳度过。

特蕾希雅的厨艺之高，在昨晚的时候就已充分体认到了。只是昨晚以扫光桌面为首要任务，所以很难说有充分品尝味道。

是因为这个缘故吗，今天的晚餐吃起来感觉比昨晚还要美味数倍。

「怎样？今天的满意度有胜过昨天吗？」

「有喔。跟昨天比起来，今天的更好吃。」

「真的吗？那就好。昨天我是做王国南部的料理，今天是北部的。想说那边的调味方法可能比较适合你的口味。」

「难说喔。搞不好是因为跟你吃才美味？」

「咳嗯！咳咳！讨厌，不要冷不防地出招……！」

明明就没特别说什么，正在喝水的特蕾希雅却过度反应呛到。对此威尔海姆浅笑，但马上又绷紧脸颊。

尽管晚餐时光很愉快，但一直把非说不可的事往后延真的很难熬。

留意到他的变化，拿餐巾擦嘴巴的特蕾希雅端正姿势。

「特蕾希雅，我有话要说。」

「好、好的。我在听……」

「其实，是关于我回军队的事。我稍微跟上层的人谈过，确定应该是可以顺利回去。不好意思，让你担心又给你添麻烦。」

「哦，那件事啊！什么啊，太好了。我本来很担心你会说要离开呢……」

「……没那回事。别让我说这么多遍。」

她对自己是多没信心啊？特蕾希雅的担忧直到现在都还没扫除。

以威尔海姆来说，真心话是没有比她更重要的人了。当然这是就算撕破嘴皮也不会说出口的话，所以也就没说出来。

「啊！你可以回军队我当然也很高兴。对你来说，能跟格林和波尔德先生这些朋友一块，工作起来也比较快乐吧。」

「朋友……我没这么想过。」

换成「战友」的话，比较符合彼此的关系吧。

不管怎样，特蕾希雅对威尔海姆能回军队一事感到开心。之后的问题是跟她本人有关的事──

「特蕾希雅，其实我还有重要的事没说。」

「是、是什么……」

「不要担心。不是你想的那样，所以放心吧。明天我会外出一整天，回来的时间八成跟今天差不多……不过你明天绝对不可以来王城。」

「────」

威尔海姆加强语气低沉叮咛，听得特蕾希雅瞪大眼珠。她手指贴唇，思索这些话。

「不能去王城……为什么？」

「没什么为什么。听我的话，我不想让你后悔。」

「我去不去王城，为何会跟我后不后悔扯上关系？你那样讲反而更让人不安。」

尽管被抗议说明得不够充分，但威尔海姆没打算要补充。两人就这样互瞪了好一阵子，最后是特蕾希雅败给彻底沉默的威尔海姆。

她深深吐一口气，认输地说：

「知道了。不能说理由，但就是不准我去王城。明天一整天都是，对吧？」

「对，就是这样。拜托了。」

「就算你拜托我……那我可以问一件事吗？」

站起身来，看来是要开始收拾桌面的特蕾希雅说。威尔海姆抬头看她，她竖起一根指头，问道：

「要是我不听你的吩咐……你会讨厌我吗？」

「我只会大动肝火。」

「好。我知道了。」

挥挥手后，特蕾希雅就把餐盘叠在一起拿到洗碗槽去了。看著开心地左摇右摆的臀部，威尔海姆稍微想了一下。

从方才的口气里，特蕾希雅是想问什么呢？实在不想去思考她不听劝告跑到王城去的状况。

「算了，都说别来了，那她就不会来了吧。」

说完点头，威尔海姆也叠起剩下的餐具，追著特蕾希雅去了。

11

隔天清晨，在特蕾希雅的目送下，威尔海姆连续三天前往王城。

只是他今天散发的气息，跟前两天完全不同。

──不，应该说之前那样才叫异常。

走进城门，散发惊人剑气的人──那正是让威尔海姆•托利亚斯之所以被称为「剑鬼」的本领，更是打败王国最强之人的铁铮铮证明。

「──祝你好运。」

迎接不吭声的威尔海姆的，是在城门等待的盔甲卫士。虽然表情被头盔隐藏，但他面颊僵硬，额头也不停冒汗。

只看了威尔海姆一眼，他就理解了。

被「剑圣」的华丽功绩给覆盖、遗忘的「剑鬼」──过去在王国军中独来独往的剑术奇才的实力，带来这个别称。

在卫士的视线中穿过城内的空地，走向那个地方。跃入敞开视野内的，是血肉交织的练兵场景观。

周围被高大墙壁环绕的空间里，充斥了许多士兵们的霸气与战意。这里每天都有王国军的骑士和卫士比划武艺，拼命提升战技到吐血的地步。

当然会有霸气，理所当然高涨的战意──尤其是聚集了王国军的知名强者，和以勇猛果敢闻名的战士之后，那程度更是翻倍增长。

「来了啊，大笨蛋。」

一踏进练兵场的中央，就沐浴在粗鲁的欢迎下。声音的主人是抱著粗如树干的双臂，帅气挺拔架著长大战斧的豪杰──

「波尔德啊。不是出人头地后就退出现场了吗？」

「嘎哈哈哈！说笑吧你。我打算做一辈子军人，哪有可能稍微出人头地就选择放下武器呢。只有这点我敢说跟你一样啦。」

大笑后，波尔德意气轩昂地瞪著站得直挺挺的威尔海姆。对此威尔海姆耸肩，接著把视线朝向站在豪杰周围的面孔。

每个都是散发出洗练澄澈剑气之人。包围威尔海姆的，在他看来全都是不能断言为弱鸡的战士们。在这些人当中有两个熟面孔。

「连你们都加入？不自量力也该有个程度。」

威尔海姆不屑地用鼻子喷气，面前是金发女骑士和持盾卫士──卡萝和格林。装备自傲的长剑以及宝盾的他们，缩起下颚接受挑衅。

「少自恋了。聚集在这里的全都是精锐。有勇无谋挑战我们，最后丢人现眼的，是你。」

「我知道在这里的人个个都很有本事。所以我才问你为何在这里呀。」

「你竟然敢──！」

『卡萝小姐，冷静点。』

中了挑衅而气到脸红脖子粗的卡萝被格林制止。格林接著用老好人的表情面向威尔海姆，微微苦笑。

『我不会放水的。』

「──变得敢讲这种话了呀。」

含笑的宣战公告，让威尔海姆狰狞一笑。

除了这三人，还看到几个内战时期的猛士。其中也有卓格夫队的同伴，每个人迸发的斗志席卷练兵场，连肌肤都感受得到。

「──看样子，全员都到齐了。」

而划破剑拔弩张气氛的，是沉稳得和练兵场不搭的嗓音。

抬头仰望，置身在能够俯瞰练兵场的观众席的是麦克罗托夫。身穿深蓝色长袍的宰相辅佐眯著眼睛望著底下的战士们，然后深深点头。

「多么壮观，气魄也十足，值得一看。」

「我可不是来演杂耍的。──你要遵守约定。」

底下的威尔海姆叮咛，麦克罗托夫闭上一只眼睛笑了。

接著他转身向后，恭敬行礼说：「请移驾至此。」

他的举动让练兵场的所有人都感到不解，但下一秒全都带著颤栗下跪。就连威尔海姆也不例外。为什么呢──

「──好了好了，别那么害怕。余只是要来见证这次战斗的结果。」

清澈的嗓音蕴含著笑意，响彻练兵场。

说话的人，是身穿豪华长袍外加闪闪发亮礼服的男子。现身在观众席上的男性约四十岁左右，身材略显圆润──不，不能用那样轻率的形容法。

要说为什么的话，因为不管是在这个练兵场，还是王城、王都，甚至在整个王国，他都是身份最尊贵的人──

「──吉欧尼斯•露格尼卡陛下。」

「确实如麦克罗托夫所说的十分壮观。要让这样的精兵齐聚一堂，仅限在重要时刻……也只有典礼之后的现在才办得到吧。」

表情温和点头的人，正是吉欧尼斯•露格尼卡──亲龙王国露格尼卡的现任国王，对威尔海姆来说是帮忙制造出这种状况的大功臣。

吉欧尼斯环视跪拜的臣民后，接著盯著威尔海姆说：

「哈哈，托利亚斯。怎么跟昨天直接找余面谈的时候不一样，态度差那么多。」

「……昨天小的万分失礼。陛下宽宏大量不计较，还给予此次的机会，除了感激，小的实在无以言表。」

「别在意。因为你的提议连余都被打动了。而且在典礼当时你与『剑圣』的剑技美不胜收。光是那场剑舞，就值得考虑这次的事。」

抚摸自己闪耀的金发，红色双眸闪著光芒的吉欧尼斯笑得就如稚子般直爽。他的态度、姿势、思考方式，在在都令人难以相信是王族。

但这确实是露格尼卡王族，亲龙王国血脉最尊贵的一族。

身为国王，他经营国政的手腕就算要讲恭维话也不值得称赞。可是那就是吸引他人追随的人性。这样的血统顶端人物──

「我是有建议去想一个让军方大本营能接纳的方法……但万万没想到你竟然先一步找上陛下。老实说我很惊讶。」

吉欧尼斯身旁的麦克罗托夫头一次露出混合惊讶和傻眼的表情。

──揉合昨天麦克罗托夫的忠告和欧尔菲的发想，为了剥夺特蕾希雅的「剑圣」称号，最后威尔海姆提出了惊天动地的提议。

而吉欧尼斯被说服，于是营造出这样的环境。聚集在练兵场的战士们──威尔海姆要一个人单挑他们。

「好了，让我看看吧，托利亚斯。──由你一人打倒王国军的所有精锐。只要办到这点，就能证明你的剑技凌驾『剑圣』之上，只身也能超越王国军的主力。用你的剑，说服王国军不需要『剑圣』吧！」

──这实在是很乱七八糟的结论。

用一把剑行遍天下的证明，就是钻研到最后的结论。

威尔海姆潜伏在国王寝室阳台并提出恳求，典礼时近距离看过「剑圣」与「剑鬼」幽会的国王笑著拍胸脯说交给他。

于是现在练兵场里聚集了原本来参加庆祝内战结束典礼、而且是亲龙王国露格尼卡最强的战士们。

把他们全部打倒，用「剑鬼」的剑力覆盖掉「剑圣」的存在。

扫除特蕾希雅持剑的理由，夺去她的「剑圣」称号凭据。

──证明她只是个喜欢微笑种花的普通女人。

「──接住，托利亚斯！」

吉欧尼斯扬声，将麦克罗托夫递出的剑往下拋。抓住旋转的剑后拔剑，威尔海姆将出鞘的圣剑前端指向众精兵。

剑尖闪耀著钝光，迸射的剑气包围练兵场，战场至此完成了。

「那么，开始吧。──余将成为亲眼见证『剑鬼恋歌』之人。」

国王在观众席道出成为开战信号的发言。

剎那间，威尔海姆踏步往前跑，冲向敌阵，一气呵成地使出斩击。

准备迎击的波尔德他们也跟著前进，毫不手软的斗志蜂拥而上。

「喝────啊────！！」

威尔海姆宛如野兽咆哮，剑击敲进人群的正中央。

12

──一开始，并没有打算要违背叮咛的。

特蕾希雅有她自己的一套深思熟虑法。她很在意威尔海姆，非常又十二万分地在意。老实说，越是思考越是喜欢他。

而这种喜爱的心情越是庞大，对于他在自己看不到的地方做些什么事的不安与担忧也就跟著膨胀，所以会害怕得不得了。

他是不是又会扔下自己离开呢？这份恐惧经常在折磨特蕾希雅。

「他应该……是在王城吧。」

从昨晚的对话和今天早上他离去的方向，再仔细回想谈话，就觉得他一定是去了城堡那儿。

所以说，假如只是要确认的话，现在过去王城那就行了。

「可是，他叫我不要过去。……可是可是，我又很担心！」

早就已经换装完毕，再来就是下定决心出门而已。但是却始终无法跨出最后一步，一直卡在门口动弹不得。

她已经一个人在这里低吟烦恼了将近一个小时。要是继续这样下去，可能在威尔海姆回来之前都还在犹豫不决，但──

「──那──样子，很容易造成不识趣的结果～哟。」

「咦？」

特蕾希雅惊讶出声，抬起头。虽说正在伤脑筋，但能够不让自己察觉到的人绝非泛泛之辈。

只是这次最让人惊讶的，在于对方的声音自己有印象。

那是几天前，跟威尔海姆重逢的典礼之仪的早上听到的。

「哟──呵，几天不见了。过得好不好──呀？」

背靠著打开的门朝自己微笑的，是蓝发女性。特蕾希雅见过她的异色瞳以及神秘美貌。

于此同时，烦恼的种子在心中抽芽开花。

「你……该不会是罗兹瓦尔小姐？」

「哎哟？我应该没跟你说过我的名字～呀。我不认为他会仔细介绍我，你怎么察觉到的？」

「内心油然而生……就是有这种感觉。是女人的直觉。」

「原来如此啊。」

接受特蕾希雅的答案，女子──罗兹瓦尔用舌头湿润薄唇，闭上一只眼睛。被她的黄色眼珠盯著看，特蕾希雅端正自己的姿态。

「请问，到我家有什么事吗？威尔海姆他不在喔。」

「用不著跟我较劲。我早就被他给甩了。他的心里就只有你，很专情呢。这点你不用担心。」

「我、我又没有怀疑。我有自信是被他爱著的。」

挺起胸膛顶回去，却又马上察觉失言而表情阴郁。

罗兹瓦尔说她被甩了。那在她面前骄傲地炫耀两人的关系不就是很没神经的行为吗。

「什么啊，不用在意我的。你那份心情很重要，记得要一──直放在心上。那迟早会变成联系到重要事情的关键。」

「……你来这里是想说什么？如果只是要来祝福的话，我是可以请你喝茶配点心啦。」

「当然不是为了那种事。你应该也明瞭。我……唉～呀，是来最后一次多管闲事的。」

说完，罗兹瓦尔耸肩，挤出滑稽的笑容。

「────」

不过，特蕾希雅却觉得她那微笑看起来很寂寞。

──但是却不知道为什么会那样想。

13

练兵场上斗气肆虐，剑戟化为猛烈热浪烧灼空气。

「──喝！」

化为一阵风，滑溜地穿过浓密剑压，威尔海姆的剑击接二连三敲向敌影，逐一将精锐逼至无法战斗的状态。

──只是面对仅仅一人的「剑鬼」，聚集的精锐人数就将近四十。

每一个都是以勇猛闻名的豪杰，每当他们的剑气直逼而来就让全身热血沸腾，感觉心中的兽性发出嘶吼。

要笑自己提出蠢条件的话就笑吧。但是，自己还是必须证明。

唯有达成万夫莫敌这条件，方能逼使王国放弃庞大力量。

「嘎啊啊啊──！！」

舞动身子，在千钧一发之际闪过枪尖，回以突刺。脚踢因冲击而后仰的身体然后横扫，藉由反作用力大幅后退，呼吸一下，让肺部膨胀。

氧气随著血液循环，使全身充满活力并让手脚灵活。还可以战斗。自己还可以。这种程度远远不及让人忘记「剑圣」的战果。

「防御看看啊，混帐东西──！」

「────」

瞄准看起来像趴在地面的威尔海姆，波尔德的战斧使出横劈。杀死风的打击逼近，威尔海姆配合斧击旋转身子。

被擦到，窜过一阵痛楚。但是对方出现空隙。威尔海姆持剑朝使出大招后的身体直直刺去，但是──

「格林！你这家伙！！」

介入其中的大盾反弹掉剑击，战友的妨碍让威尔海姆大叫。

既然希望认真打，这亦是理所当然的，他们也是全力以赴对抗威尔海姆。

特蕾希雅的心情，威尔海姆的想法，就算知悉两者也不会放水。正因为明白这点，才会和认真的他们对立。

「────」

思考宛如电击奔驰，手脚执行习惯无比的剑术。

眨眼间刀刃就朝格林挥去三次。格林用盾牌挡住两招，但第三招却来不及格挡而硬生生吃下，结果伴著沉声倒地。

──还有一个。还剩下一人。

「────」

斜瞄被击飞的格林，威尔海姆重新握剑，和波尔德对峙。

原本将近四十名的精锐，如今只剩下「猛犬」波尔德•卓格夫还屹立。

「托利亚斯……！」

按著手的卡萝只能咬牙切齿地看著最后的单挑光景。

长剑被打断的她已经脱离战线。周围许多跟她一样脱队的骑士们，全都屏气凝神等著分出胜负。

──面对「剑鬼」的恐怖实力、剑术与心情，他们无计可施败下阵来。

不甘心。打从心底不服气。

应该是如此，但卡萝发现自己也觉得放心和欢喜。

「结果，还是你啊……」

能让特蕾希雅绽放笑容，实现特蕾希雅愿望的人。

为了特蕾希雅而变得比任何人都还要强的人，终究只有威尔海姆。

──这事实令人遗憾却又喜不自禁，所以才不甘心。

「要上啰，威尔海姆！」

「──来呀，波尔德！」

对话简短，两人的攻防又比那更短，在剎那间决定了胜负。

用力喊出气魄，旋转斧枪的波尔德缩短距离，往下敲击。这粉碎大地的勇猛一击，被「剑鬼」闪过还踩上武器，导致动作被封住。

反击被阻，波尔德无畏地狞笑。银闪迸发，朝他穿过去。

高亢冲击声响彻练兵场，庞大身躯被剑击轻而易举地弹飞。

波尔德飞了出去，扬起烟尘在地面滚动。不久滚动停止，他手脚打直仰望天空，以掌掩面。

然后──

「──啊啊，可恶！输了输了！彻底输了，大笨蛋！啊啊，可恶透顶……！」

聚集在城堡里的精锐，撑到最后的那一人堂堂正正地表态自己输给「剑鬼」。

──至此，「剑鬼」的剑力获得了绝佳证明。

14

倒地的剑士，跪地无法动弹的格林，躺成大字形一直在大笑的波尔德，还有不甘心地垂头丧气的卡萝。望著他们，威尔海姆吐出一口长气。

紊乱的呼吸有血的味道，明明没被直击，全身却异样生疼。战意与剑压的负担非比寻常，在这场削弱身心的战斗结局中，「剑鬼」仰望观众席。

然后朝著见证完整场战斗的吉欧尼斯高举圣剑，像是献上胜利。

「呼嗯！战得漂亮，托利亚斯！你的剑力和心情，确实……嗯嗯？」

称赞底下的光景，快把话说完的吉欧尼斯表情有异。这反应让威尔海姆皱眉，顺著国王的视线往后看。

看到不该出现在那儿的人影后，威尔海姆瞪大双眼喘息。

「这是……在做什么，威尔海姆？」

练兵场的入口站著红发女子──特蕾希雅•范•阿斯特雷亚。

看到练兵场的惨状和大批倒地的战士后，她的蓝眼珠困惑动摇。虽然不明始末，但光看就知道这里发生了非比寻常的事。

「……阿斯特雷亚，现任『剑圣』啊。那边的男性直接找余谈判，要求让你脱离王国军。他说希望凭剑夺去你的『剑圣』称号，让你从军队除名。」

「吉欧尼斯陛下……！威尔海姆，这是真的吗？」

威尔海姆语塞，吉欧尼斯代替他说明。特蕾希雅一度对国王在场感到震惊，但马上就转向威尔海姆质问真伪。

可以的话不希望这件事让她感到内疚，希望能够一直保密。

「没错，是真的。」

「所以，你就把大家给……连卡萝都……」

威尔海姆点头，特蕾希雅发现参战者竟然有自己的随从而惊讶不已。

卡萝就像是做了坏事穿帮一样的表情，垂著颈项不敢抬头。其他人也都尴尬地远离「剑圣」与「剑鬼」的对谈。

威尔海姆也看不出特蕾希雅接下来的反应，因此无法有所动作。

是会生气，还是打过来呢？至少不会是额手称庆。她不是那种重要的事情在自己不知道的地方被处理掉还会开心的人。

因此，特蕾希雅大概会生气吧。威尔海姆这么预测。而这个推测猜中了一半。没错，特蕾希雅是生气了。只不过──

「──陛下，为什么允许他这样胡搞？」

「什么？」

特蕾希雅手插腰，朝著上方询问。她愤怒的矛头不是指向自作主张的威尔海姆，也不是跟著乱来的卡萝他们，而是坐在观众席上的吉欧尼斯。

这番容易被判断为不敬的发言，吉欧尼斯别说生气了，反而是朝著不悦的特蕾希雅苦笑，手摸自己的金发。

「唉呀～这个，余其实也觉得这样不太好喔？但是，你的丈夫太过认真，让余忍不住也跟著涉入其中……」

「陛、陛下！他还不是我的夫婿！怎么这样讲，真是的，讨厌！」

「……特蕾希雅？」

在奇妙的对话气氛中，威尔海姆呼唤面红耳赤的特蕾希雅。「呀！」她发出奇怪的声音，然后慌慌张张地转过身。

她的脸，比之前看过的都还要红。

「不、不是啦。关于这点，没有好好传达给陛下是我的错。不过陛下也有问题……」

「简单明白地从头说明吧。」

「呃，那个，咦？威尔海姆，你不想让我当『剑圣』，我非常高兴啦。真的很高兴。可是……这个问题，已经解决了。」

双手手指互戳，特蕾希雅结结巴巴地说出内容宛如炸弹的发言。

这话令威尔海姆惊愕，而练兵场里同样不明状况的人们也纷纷发出惊讶之声。有人讶异，有人愕然。

面对众多的反应，特蕾希雅苦笑。威尔海姆默默地靠近她。

「那、那个，威尔海姆……先生？」

「说清楚讲明白。」

「……其实，典礼之后跟陛下谈话时就说了。因、因为我跟你的对话好像被陛下听见了，所以──」

「内战也结束了，『剑圣』已为王国鞠躬尽瘁。──拆散相爱男女这种不风雅之事，谁做得出来呢。」

在说明途中吉欧尼斯不住点头。威尔海姆注意到就只有国王后方的麦克罗托夫丝毫不惊讶。

麦克罗托夫一定是打从一开始就了解整个状况。

「所以我说过了吧。要你好好讨论商量。」

面对威尔海姆抗议的视线，麦克罗托夫一派清凉地说。

接受这点的威尔海姆感到虚脱，对自找的徒劳无功感到颓丧。

「啊，威尔……呀啊！」

本来想要去支撑快瘫坐在地的他，却没想到手反而被抓住，拉了过去。特蕾希雅整个人飞扑进威尔海姆的胸膛，两人就这样跌坐在地。

被健壮的双臂拥抱，特蕾希雅讶异地睁大眼睛。

「呜～又是汗臭味。……威尔海姆你老是臭烘烘的。」

「你倒是甜得像花一样。典礼的时候我也这么想。」

「因为是你的花女呀。」

露出动人微笑的特蕾希雅，深深沉入威尔海姆的怀抱中。

虽然就这样一直抱著她也是一项乐趣──

「嗯～相爱是好事，但没有忘记吧，阿斯特雷亚。」

「咦，啊，哇，是的！请问是什么事，陛下！」

想起是在众目睽睽之下的特蕾希雅飞也似地跳起来，慌慌张张地端正姿态。吉欧尼斯微笑并挥手道：

「余对于你免除『剑圣』职责的条件，还记得吧？」

「啊、呜……」

面对国王的确认，特蕾希雅一脸被戳到痛处的样子。

那是从方才开始就屡屡见到的反应，威尔海姆也抬起沉重的腰杆和她并肩而立。

「怎么了？被要求了天大难题吗？」

「呃，这个嘛……」

「假如对你来说很困难的话就由我代劳。这点事包在我身上。」

「真的吗！？啊，等一下。可是，一个人很困难，非得两个人才行。」

特蕾希雅口齿不清，红著脸一下「啊～」一下「呜～」的。这段期间，周围的人全都对「剑圣」不曾展露过的面貌惊讶万分。

对于那些只认识她绷紧神经的剑士样貌的人们来说是很正常的反应。不过让大家欣赏她这么可爱的样子，不知为何让威尔海姆感到不痛快。

所以说，他一把抓住吞吞吐吐的特蕾希雅的肩膀。

「说清楚！是什么！」

「──！陛、陛下说只要我确实成为你的妻子就可以辞去『剑圣』的职位！」

「────」

脸颊红通通又泪汪汪的特蕾希雅输给他的气势，坦白以告。

内容撞击耳膜、流进脑子，最后终于理解──威尔海姆说不出话来。

仔细一看，特蕾希雅眼神不安地凝视自己。

「那是什么意思……」

「也就是说，陛下是这么想的。──让未来会成为贤妻良母的女性拿起不想拿的剑，这种事陛下做不来。」

在观众席的麦克罗托夫不客气地将条件简明扼要地说出来。

听了内容后，威尔海姆叹气。见状特蕾希雅摇头。

「在家的时候，我有好几次想跟你说……可是时机都不好。」

「因为吵架了。就算如此，没想到……」

以婚姻为条件就能让特蕾希雅从军队中除名，这点自己根本想像不到。

原来如此，露格尼卡王族以好人好事闻名，但这层认识还太浅了。

「──呵呵，就相当于代理人吧？」

「是的，正是如此。陛下慧眼识英雄。」

得意洋洋的国王，和身旁厚脸皮跟著点头的宰相辅佐。瞪过他们两人后，威尔海姆面向近在眼前的特蕾希雅。她眼眶泛红，静静地等待威尔海姆的答案。

害怕会被拒绝或疏远，眼神摇曳不安。──真是蠢毙了。

「──威尔海姆•阿斯特雷亚。」

「……咦？」

「托利亚斯家已经不在了。要自报姓名的话，就用你的姓氏吧？」

朝著愕然失声的特蕾希雅露出浅浅极淡的微笑。

他的微笑和话语，让特蕾希雅的双眼张得更开。

「你、你接受了……？」

「你以为会被拒绝才叫我傻眼。真是的，你啊……」

「因为！一下就说要结婚，太突兀了……！」

「除了你还有谁啊。早讲和晚讲没有关系啦。」

粗鲁地这么说，听得特蕾希雅张大嘴巴，但下一秒豆大泪珠就滚过白皙脸颊。

对这反应松一口气，威尔海姆将她整个人抱入怀中。

「我可以……当你的新娘吗？」

「就只是从花女改变一下身份而已。用不著担心啦，笨蛋。」

「这样子……曲解也不错耶。」

脸抵在胸口的特蕾希雅红了眼睛、鼻子和脸颊，笑著说。

凝视她的脸，意外地威尔海姆不觉得那是曲解。

因为自己从初相遇的时候就被她吸引了。至今从未想过要迎娶她以外的人为妻。

「……威尔海姆•范•阿斯特雷亚。」

「什么？」

怀中只对威尔海姆微笑的特蕾希雅继续说了下去。

「以后要自报姓名，就用『威尔海姆•范•阿斯特雷亚』这个名字吧。范是『剑圣』家族中赠送给有持剑立下功绩的人的名字。……而你夺走了我的剑，所以啰。」

──威尔海姆•范•阿斯特雷亚。

特蕾希雅的这番话，让威尔海姆轻声喷气。

「感觉不赖。」

──跟你使用同一个姓氏的感觉。

但是他没有补上这一句。「剑鬼」决定迎娶失去「剑圣」地位的女人为妻，仅是怜爱地将她紧紧抱在怀里，不断抚摸闪亮动人的红发。

《完》

** 『剑鬼恋谭──婚礼之日』

1

一踏进庭院，威尔海姆就迎上柔和的温风。

风送来了花朵的甜香和几片花瓣，掠过鼻腔，被晴天给吸了进去。

庭院反映出宅邸主人的趣旨，如今成了按照时节百花撩乱的花园。虽然开满了各式各样、大大小小的花朵，但保养和植栽方面可一点都不马虎，做得相当完美。

繁盛又美丽，骨子里很坚强的花──看著这些花朵，不意想起。

这个花园的主人现在也正在花园正中央欣赏繁花。她的生存方式比起在这里盛开的花朵，更像是真正的「花」。

「──特蕾希雅。」

和内心的感伤做区隔，威尔海姆朝著花园里的背影呼唤。

听到呼唤后，女子按著迎风飞舞的红发转过头来。她的蓝色眼睛映照出威尔海姆，嘴角做出可爱动人到令人忘记花朵存在的微笑。

「──威尔海姆。」

名字被呼唤，看微笑看呆的威尔海姆这才回过神。然后举起手好掩饰自己看到忘我的状况，粗声粗气地朝微笑的她说：

「哦。……我刚回来。」

「嗯。欢迎回家。」

威尔海姆的招呼很冷淡，但女子──特蕾希雅怜爱地眯起眼睛。光是这样的互动，就让威尔海姆的胸膛充满温暖。

可以的话，很想一直沉浸在这份温暖中──

「所以，了解状况了吗？」

但是这样的微薄心愿，却被微笑的特蕾希雅给打断。

「────」

「威尔海姆？」

一问威尔海姆就脸颊僵硬，特蕾希雅可没看漏这个变化。第二次呼喊名字时，声音里头有去不掉的不信任，不知何时微笑也消失了。

那眼神像是被人拿刀给捅了一下。威尔海姆叹气。

「……可能是白费功夫，但一开始我先声明。」

「……可能是白费功夫，但一开始我先听听。」

「别生气。」

「……要听过内容才知道。」

张设了防线但无效，一瞬间两人落入沉默。不过拖延结论跟自己的个性不合，于是威尔海姆下定决心后开口。

「我在跟上层说话的时候直接提出来申诉，说这次的安排太过蛮横了。」

「嗯，没错。非常不恰当。然后？」

「结果就是，巡察行程被加倍延长了。抱歉。」

「为什么会变那样！？」

听了愣住张开嘴，然后大步靠过来的特蕾希雅抓住威尔海姆的衣领摇晃。被细瘦的双臂晃来晃去的他一脸尴尬。

「所以我一开始就说别生气了……」

「这事听了一定会生气的吧！毕竟！毕竟……」

说到这儿语塞，特蕾希雅推开威尔海姆，然后瞪著往后退的他，泪湿蓝色双眼，同时叫喊：

「──三天后，就是我跟你的结婚典礼了耶！！」

特蕾希雅的大叫，吓跑了一众俯瞰花园的鸟儿。

在无数振翅声之中互看彼此的男女──是几经波折后结合，如今又身处在新的波澜之中的「剑圣」与「剑鬼」夫妇。

2

──绵延亘长的战争，历史将之纪录为「亚人战争」。

亲龙王国露格尼卡长达九年的内战，在一名担任「剑圣」的少女持剑挥舞下走向终点。

王国大肆宣扬这份功绩，想要将她立为英雄庆祝。而在那儿等著她的，是一名被称为「剑鬼」的青年的执著与剑力。

历经了峰回路转、曲折离奇的经过，「剑圣」恢复成一介女子，和「剑鬼」共结连理，过著幸福的日子。然后，人们祝福他们──

──但这世上可没有平顺到能这样三言两语就带过。

内战的英雄，生于「剑圣」家族，为王国尽心尽力的现任「剑圣」。

内战的逃兵，生于在内战时被灭族的没落贵族之家，毁了终战典礼的「剑鬼」。

一度舍弃授勋骑士名誉的威尔海姆立场岌岌可危，各种问题在两人的婚姻之路上化为障碍堵住前方。

但是那些障碍，两人还是靠著彼此的羁绊和周围的协助来一一化解。

然后，两人终于要迎接婚礼──威尔海姆和特蕾希雅要成为名实俱符的夫妻，并接受国人的祝福。

「可是！关键的新郎却要在婚礼上缺席，成何体统！！」

把在花园的怒意带进来，气得脸红脖子粗的特蕾希雅在宅邸地毯上跺脚。斜瞄一眼她那样子，威尔海姆无可奈何地叹气。

「啊！啊～！你刚刚的叹气，是觉得麻烦透顶对吧！这是我们的问题，威尔海姆你也要好好一起想！这可是大事耶！？」

「叹一个气就好像做了天大的坏事一样……而且我不觉得麻烦。只是觉得你嗓门很大。」

「你那样！就是没有认真理睬我的证据！真是的！信不过你！」

不管说什么都会惹出麻烦，威尔海姆也只好投降。现在的特蕾希雅就是个楚楚可怜的炸弹，不管戳哪里都免不了大爆炸。

「好不容易你也恢复骑士的身份，可以让那些说三道四的人接受了。为什么却突然要在结婚典礼前对卓格夫队下这个命令？明明还有很多人可以胜任这次的任务呀！」

一个劲地喷完火后，特蕾希雅终于回到一开始的问题来。

总算进入原本的主题，威尔海姆抱著双手说：

「我先说明。目前能在城内自由活动的小队不多。以灾后重建为名义，王国军被派遣至全国各地。留在王都又适合这次目的的面孔顶多只有我们……所以才落到我们头上来。」

「那种话，想也知道只是听起来好听的表面话！一定是有人从中作梗故意惹人嫌。……我猜，一定是父亲！」

「那样讲也太……我没法这么肯定地说。」

「看吧！你也这么想！」

拍打掌心、怒上心头的特蕾希雅鼓起腮帮子。

特蕾希雅的父亲──贝尔托•阿斯特雷亚是现任阿斯特雷亚当家，对威尔海姆来说就相当于丈人。确定要和特蕾希雅结婚后，当然也就去拜访了她的双亲。不过当时充满压迫感的会面令人难忘。

气势熊熊又压倒性的大量问题攻势，看穿威尔海姆的本性后又开始挑毛病并且严厉刁难──贝尔托不是坏人，只是过度保护特蕾希雅。

这次的事是想要妨碍两人婚事的贝尔托所策划──听到这种阴谋论，威尔海姆差点就要全盘相信。大概就到了这种程度。

「这时就用上代代出产『剑圣』的阿斯特雷亚家的威势，强行策动王国军高层听命行事……」

不惜做到这种地步也想破坏女儿的婚礼吗？真是让人匪夷所思。

可是威尔海姆的想法，却让特蕾希雅垂下睫毛。

「提姆兹哥哥和卡尔朗哥哥，还有我弟弟卡吉雷斯……在内战时，我的兄弟全都战死了。所以父亲才会这么担心他唯一的子女。」

「────」

「不过，没道理就因为这样妨碍女儿的幸福！要坚决应战！」

「坚、坚决应战的结果就是巡察行程被加倍喔。是对手太难对付了。」

「你明明奋勇战斗抢、抢走我，怎么对上父亲胆子就变小了？」

对「抢走」这个字眼感到害羞脸红，但特蕾希雅还是挑衅地瞪著威尔海姆。她的视线让「剑鬼」眉心皱起。

「认真抢走你，跟让岳父闭嘴是两码子事。要是砍倒岳父就能解决事情的话，那就简单了……」

「父亲的剑术是普通人水准……以我来看的话，甚至更低劣。叔叔……我父亲的弟弟是前一任『剑圣』，因此父亲很早就放弃练剑的道路……」

「这样一来，就算用剑打败他，他也不会认同我的吧。而且──」

说到这儿就打住，威尔海姆想像贝尔托这次运用谋略的真正用意。

在战争中失去家庭，私自脱离军队，甚至还一度舍弃骑士地位。因此威尔海姆根本不期望自己会被阿斯特雷亚家高举双手欢迎。

事实上，婚前去打招呼的经验给威尔海姆留下极度恶劣的印象，连许可都只是流于形式。这次推测贝尔托是在测试威尔海姆，看他是否配得上自己的女儿。

结婚典礼前的休假被取消，直接投诉的下场是工作的时间加倍，这真的让人难以忍受。

「──但是，既然都申请决斗了，那就必须接受。」

「决斗？」

「假如这是岳父搞的，那就等同是向我下战帖。不是靠比剑让我很不满，但战斗的方式百百种。没办法。」

讲白点就是，竞争的方式不是比剑，而是比谁对特蕾希雅比较深情。

想必对方是想表示：假如是真心想要抢走特蕾希雅，这点程度就加以排除吧。

──既然只要这种程度的试炼就足兹证明，那就如他所愿。

「我都把你从剑神手中夺走了。从令尊父亲身边抢走你这点程度，早已有所觉悟。」

「啊、呜……嗯，呃……」

被正面凝视说这种话，特蕾希雅完全忘了刚刚的愤怒，在混杂著喜悦的羞耻下红了脸。

接著害臊地垂下眼，支支吾吾后说：

「……我可以相信三天后，我真的会成为你的新娘吗？」

「你才是，与其担心我，不如先做好自己的心理准备。我先声明，除了我以外，不准让别人看到你毫无防备的红脸蛋。」

「毫无防备？」

是没有自觉吧，特蕾希雅愣住，歪过头来。

「────」

那模样激起怜惜之情，威尔海姆皱起脸。然后为了瞒过这份感觉，粗鲁地推少女的额头。

「呀啊！」

三天后要成为「剑鬼」新娘的「剑圣」，发出可爱的惨叫声往后仰。

3

──卓格夫队以在「亚人战争」中勇猛无比的活跃事迹而闻名，是由「猛犬」波尔德•卓格夫率领的王国军游击部队。

以猛将之姿穿越无数战场的波尔德，对威尔海姆来说是交情很久的长官，也是一名恩人。虽然打死他也不会说出口就是了。

包含卓格夫队在内的王国军，在内战结束的发展下进行大规模重组编制。卓格夫队也不例外，结果立下汗马功劳的部队长波尔德晋升，成为在军方大本营有一席之地的将官。

也因此卓格夫队的部队长位置就空了出来，而职务是按照序位来进行改组──

「──到底是哪里搞错了，怎么会是我当队长。」

王都露格尼卡的中心，露格尼卡王城城门前广场──站在整齐列队、人数超过百人的队伍前面，威尔海姆面有难色地喃喃自语。

『这是排名的结果，没办法啰。』

「这种排名太奇怪了吧。为什么是任命长期脱离队伍的我担任队长？我应该要从无名小卒开始证明自己的能耐啊。」

『若无其事地闯进典礼，强行娶「剑圣」为妻的男人的能耐？』

「吵死了。虽然是写字但还是很吵。」

朝著咂嘴的威尔海姆这么说的──不，是以纸笔这么传达的，是被委任为副队长但看起来很不搭的战友格林•法先。

他跟威尔海姆从内战初期就结下交情，即便是失去嗓音的现在都还是可以若无其事地互动，也因此被认为队长和副队长的沟通不会有问题。这点让威尔海姆很火大。

自己坐立难安，而他在旁边享受，这点也叫人一肚子火。

「唉呀，格林副队长的话也有道理，是真理。至少在这里的每个人都不会觉得你不适任队长。不管是武力方面，还是只身闯进典礼的胆量方面。」

「宰了你喔，康吾德。」

「哦哦，好可怕。」

笑著这么说的，是卓格夫队的老鸟士兵康吾德•梅拉浩。

在战斗上他并没有特别出色的才能，但是混战方面就连威尔海姆都对他刮目相看。不管是在战场还是平常生活，观察力卓越的人都是珍宝。

以他为首，卓格夫队有很多人入队超过两年，所以都认识威尔海姆。因此虽说是新队长，但在这么多熟面孔面前，威严起不了作用。一想到这些人里头甚至还有知道自己最不成熟时期的人，就更是摆不起架子。

「全都是眼熟的家伙，连旁边的都是熟面孔……根本就没新鲜感。」

这些老鸟成员，加上副队长格林和新队长威尔海姆──这就是新生的卓格夫队。虽然主要人物波尔德不在，但队伍的名称不变。

『这样一来，过去一块战斗的战友名字也不会消失。对吧？』

「都死了都还要被操啊。我可以听到皮波特在叹气啊。」

斜瞄一眼苦笑的格林，威尔海姆站到排排站的队员面前。

接下来卓格夫队将要离开王都，前往邻近城镇视察。目的在于提升于内战时恶化的治安，或是牵制趁著内战结束后的混乱企图为非作歹之辈。

跟内战时相比，这是一桩和平无事的任务──可是卓格夫队的队员们个个表情紧绷，眼神都燃烧著名为认真的火焰。

「巡察就算按照行程表来进行，几乎也要费时三天……不到队长和特蕾希雅大人的结婚典礼那天就回不来。老实说，突然被追加巡察业务时，我还以为上层在开玩笑咧。」

「本次的任务，关键在于能在鲁法斯街道缩短多少时间。全员都要谨慎注意，不要脱离了『除风加持』。」

「要是途中地龙累垮，虽然遗憾，但就舍弃掉吧。这次的任务不需要绊手绊脚的东西。──那样也是那位大人的希望吧。」

「嗯，对啊。就算我发生什么事，也绝对不要救我喔……！」

相邻的队员交头接耳，各自做好绵密的磋商和心理准备。见状，威尔海姆皱眉。为什么他们要这么认真呢？

自己当然必须赶上结婚典礼，但那终究是个人私事。归根究底来说和他们一点关系都没有──

「──看样子，这次的事大家都很在意。」

正在思考的威尔海姆，耳朵听见了熟悉的沙哑声音。回头一看，表情严肃的大个子从王城的方向走了过来。

蓝发平头，浑身肌肉的高大男子──波尔德•卓格夫。

「你好歹也该学会看看周围了吧。接下来你就是部队长，也即将为人夫，已经失去只要考虑自己就好的立场了。」

波尔德大笑又没礼貌地说，威尔海姆夸张耸肩。

「干嘛突然跑出来？不是说很忙吗？」

「嘎哈哈哈。当然忙。但是，新的卓格夫队的第一件工作，身为前任队长，要是不送你们一程的话就太没道义了。」

笑声刚毅十足，波尔德像殴打般拍威尔海姆的肩膀，然后压低声音对著在冲击下踉跄的「剑鬼」说：

「这次的事，觉得乱来的不是只有队员，我也持相同意见。『剑圣』和『剑鬼』的大喜之日，上头的人不可能不知道。事有蹊跷，当心点。」

「我还是一样，不习惯被你忠告呢。」

「换一个地方就换一个脑袋啦。我也变得会动脑了。……而且，你先前推荐的舌灿莲花的家伙意外地好用。动用关系硬是让他出狱是对的。」

「哦，欧尔菲啊。虽然是个恶质的恋爱诈欺男，不过好用就好。」

波尔德提到的是以前威尔海姆在监狱塔认识的诈欺犯，同时也是出主意帮忙解决特蕾希雅相关问题的人。

当时答应他会帮他争取特赦，后来也告知波尔德他能用，而不出所料，他是真的很派得上用场。

「有那么随机应变的家伙真是帮了大忙。搞不好迟早会弄一个做那家伙工作的团体也说不定。要是真那样，到时名字就取那家伙的绰号叫『六面三刀』。」

「那么，让那个以那张嘴自豪的家伙寻找之后，知道了什么？」

「详情还不清楚。但是，这次的事可以想成是某人不乐见你们的婚姻而做的手脚。你心里有底吗？」

「……想到我头痛啊。」

是我老婆的爸爸，但威尔海姆还没笨到说出口。不过依状况来看，疑虑是越来越往确定方向发展了。

波尔德对这答案皱眉，威尔海姆摇头说：

「不用在意。反正对方挑衅，我也做好必胜的觉悟。用不著担心。」

「这是输赢的问题吗？我是不太懂啦，但我懂了。」

不会拘泥于细节的决断力是波尔德的武器兼魅力。事实上他也立刻用「加油吧」来中断与威尔海姆的对话，改朝队员们吆喝鼓舞。

『真有队长的感觉呢。』

「是前队长，不过我也有同感。……唉呀呀，等波尔德闹完了就出发啰。」

推开含笑的格林递出的纸，威尔海姆仰望城门。

队伍的人数超过百人，要搭乘的龙车也将近二十辆。在门口列队排排站搞得城堡的卫士们也静不下来。等波尔德振奋完队员的精神，就赶紧出发吧。──就在威尔海姆这么想的时候。

「──威尔海姆！」

城门后方有人呼唤自己的名字，威尔海姆瞪大眼珠。仔细一看，刚好是一名女子小跑步喘气从坡下过来的时候。

「特蕾希雅？怎么到城堡来？」

「太好了！幸好你还没出发。」

不理惊讶的威尔海姆，特蕾希雅和城门的卫士点头后就进入广场。就在王城警备的枢纽城门被顺利突破的瞬间。

「……面子真广，但是守门的让退役的女人过来好吗？」

「守门士兵早就已经认得我了。不如说跟你比起来，我跟他们打照面的机会还比较多。」

特蕾希雅说完一眨眼，威尔海姆诧异地看著她。

要离开家门前就已经道别过了，也发誓三天后的婚礼一定会赶回来。为了避免依依不舍所以速速道别。可是她跑来的话，就功亏一篑了。

离别时越是花时间就越难以分开。这方面，或许是对于被这女人爱恋的自觉还不够吧。

「你看你，威尔海姆。眉心又皱起来了。都叫你别这样了。」

「……还不都你害的。」

「为什么是我害的？真叫人意外，不过算了。更重要的是……」

特蕾希雅把藏在身后的东西递给皱眉的威尔海姆。接过的东西，是用明亮的黄色包巾裹著的盒子──

「这是？」

「为了出远门的你而做的。就、就是叫爱、爱妻便当吧？」

「既然会害羞到结巴就不要说啊。」

朝著话讲到一半就脸红的特蕾希雅说完，威尔海姆掂掂包裹的重量。让人想像不到是急就章的重量感觉不赖，内心十分开心。

包裹的内容物不用说，她精心制作后还拿过来的用心著实叫人欢喜。

「那么，就是，是不是该说些什么？」

「说什么？」

「就～是～说，你看嘛，我特地做好拿来给你耶？是不是要机灵地道个谢？」

「机灵地道谢吗。──想到你，我会细嚼慢咽吃光的。」

「唔唔唔，心情好复杂……！」

虽然有思考一下，但看特蕾希雅的反应结果似乎是失败了。

不管怎样，自己确实很开心。而这点看来是有传达给她。威尔海姆的不机灵回答让特蕾希雅微微苦笑。

「算了，我本来就没太期待。没有关系啦。只要有收下便当我就很高兴了。」

「这样啊。那么，是什么让你突然带著爱妻便当赶来？」

「你怎么那么顺口地就把爱妻两个字讲出来啦……！」

不只表情，连脸色也千变万化。脸一下红一下青，待会又变白，忙不迭的特蕾希雅在这边轻咳了一下。

「咳嗯。因为，军队的饮食大多都很乏味吧？卓格夫队又都是男性，我猜行进期间你们也是随便吃，就稍微做点抵抗啰。」

「我们伙食有格林负责。而且我好歹也是会做料理的。」

「格林一个人做不来百人份吧。还有你那连肉里头都烤焦，而且青菜只是水煮过的东西，我才不承认是料理。」

「唔……」

「总而言之，我就是想做些什么。希望你能赶得上结婚典礼，也希望你能比较有精神，只要是办得到的我都会……就这样！没错。」

自觉到话题绕著自己的心情在打转，特蕾希雅中途撇离视线。所以她没看到威尔海姆的眼神变化。

「────」

有一瞬间，差点就要因为她看起来很可怜而忘我紧抱她了。不过硬是拼命地忍下来。

真危险。得看地点和场合。那样做可不是个好模范。以前未曾留意的障碍，如今都会责备威尔海姆的冲动行为。

该说是得救还是被妨碍呢，心情相当复杂就是了。

「果然变伟大后就没法轻松了……」

「是吗？你被大家认同，我很开心哟。」

「你是故意这样的吗？」

「──？」

愣住的特蕾希雅对自己的可爱毫无自觉，威尔海姆沮丧垂肩。接著「剑鬼」很慢才注意到周围的视线集中在两人身上。

波尔德的打气早已结束，队员们全都在看热闹。「剑鬼」与「剑圣」让人会心一笑的互动让人开心地起哄。

「……你们是怎样啦。」

「没有没有。只是觉得很可惜，但是也到了该出发的时候了。和尊夫人的甜蜜时光，烦请留到任务结束和婚礼之后。这是单身队员的肺腑之言。」

「什么尊夫人……讨厌……还太早了啦……！」

康吾德的诙谐让整个队伍发笑。被人取笑的威尔海姆不悦咂嘴，不过手贴在红脸颊上的特蕾希雅不能说不高兴就是了。

只是她接下来轻吐一口气，然后站到卓格夫队前面。

「那个，占用到你们出发前的时间真的很抱歉。没想到竟然要这样送各位一程，心里想说这样好吗。总觉得很过意不去。」

「────」

混合了害羞与罪恶感的笑容，让队员沉默。

其实在三个月前，特蕾希雅和卓格夫队是一同在内战奋战的战友。因为军队远征时她也同行，毕竟她是在最前线比任何人都果敢挥剑的「剑圣」。

这样的她留在王都，卓格夫队则是要出远门去巡察。这在内战时是不可能会有的光景，或许特蕾希雅也有很想跟去的冲动。

但是──

「呀嗯！」

「用不著道歉吧，笨蛋。这不是理所当然的吗。」

拍了她后脑杓一下的威尔海姆超越她，走到更前面。在特蕾希雅摸头抗议之前，「剑鬼」用力并拢双腿敲响鞋跟。

配合这道声响，卓格夫队的队员也都并腿立正，姿势整齐划一。

「──哇。」

「不管是战斗还是守护，都是骑士的任务。我应该说过了，特蕾希雅。你就待在我和这些家伙的后面玩花就好。那是百姓的任务。」

「是家庭主妇才对吧，队长。」

『我也这样讲。』

康吾德和格林再度插嘴，队伍哄堂大笑。

威尔海姆也苦笑，特蕾希雅则是圆睁双目。

「────」

仅仅一瞬间，蓝色眼眸就蓄积了快滚落的泪珠。但是她连忙用袖子擦去，然后露出一个如花绽放的笑容。

让「剑鬼」威尔海姆和身经百战的勇士们全都看呆的可爱笑脸。

然后她带著笑容，大幅鞠躬。

「谢谢。──我家的威尔海姆就麻烦各位多照料了！」

最后就用这句话作为出发前的总结。

4

「嘎哈哈哈！我家的威尔海姆，说得太棒了，特蕾希雅小姐。这是我听过最棒的送行话了。一想到那家伙不久后要被套项圈就觉得很感慨。」

「说套项圈太夸张了。而且他又不是那种能够轻易绑住和牵著走的人。被紧紧套牢的搞不好是我喔。」

「没有自觉也是一种罪。不这样的话哪能担任『剑鬼』的贤妻。」

目送卓格夫队出发后，留在广场上的特蕾希雅和波尔德做出了如上交谈。

这两人的关系也可以说是共同在内战打拼的战友。因为晋升而退出前线的波尔德，以及退役的特蕾希雅。──连在身份立场上都有颇多共同点。

「波尔德大人也是，送威尔海姆他们离开很寂寞喔？」

「寂寞这种形容太可爱了。是心痒难耐。……不，或许是因为再也没法随便跟他们到处跑，所以感到很寂寥。」

低头看没有拿斧枪的双手，语调微微变弱。但是他立刻又握紧双手。

「不过，只是战场换了地方，我还是我。有背负的东西，也有期待我往上爬的人。被人记在心里和被恳求是幸福的。就像特蕾希雅小姐对威尔海姆有期望那样。」

「这个……是的，我也这么想。」

肯定战友的话后，特蕾希雅瞥向威尔海姆他们离开的方向。看著她的侧脸，双手抱胸的波尔德切入主题。

「是说，在新的战场被特蕾希雅小姐拜托的事……关于强逼卓格夫队去巡察的人。」

「──对不起，勉强你了。因为现在我想不到还有谁可以拜托。」

「没关系。我的两个战友要结为连理，哪可能不当己事呢。……只是我很犹豫，真的要告诉你吗。」

抓抓自己的短发，波尔德面有难色。他的表情让特蕾希雅眯起眼睛，对他有口难言的原因有不好的预感。

「没关系。没事的。我不会怎样，所以请清清楚楚地告诉我。」

「清清楚楚，这样好吗？」

「拜托你了，要清清楚楚的。」

「……这次暗中搞鬼的，是阿斯特雷亚家。也就是令尊的指示。」

听了波尔德的苦涩发言，特蕾希雅闭上眼睛。

下一秒，庞大的剑气产生奔流，在城门站岗的卫士们全都寒毛直竖。其压迫感，就算是出生入死经验丰富的波尔德都做好一死的觉悟。

但是剑气的发生源头「剑圣」却急匆匆地收起外漏的剑气。

「对、对不起！不小心就！真的是不小心！没事没事！」

朝站岗的卫士们道歉后，特蕾希雅拍自己的额头以兹反省。发出可爱「啪」声的她跟「剑圣」给人的印象落差让波尔德苦笑。

「威尔海姆也是……特蕾希雅小姐早就料想到了？」

「嗯，是的。虽然不想去相信，但现在真的很希望你是在说谎。」

答案就跟预期的一样。确认真的是老家的父亲在对女儿的婚礼从中作梗后，特蕾希雅的心中、脑内和胸口都有风暴在肆虐。

不管怎样，现在确定敌人了。既然威尔海姆勇赴决斗──

「我也得去决斗才行……」

「特、特蕾希雅小姐？我想用不著我说，你拿起剑的话，威尔海姆会伤心喔？当然，我也会后悔。」

「啊，说是决斗，其实是商量啦？是措辞和心情上的问题。」

特蕾希雅切换心情、握紧拳头。波尔德勉强接受。

这次的调查，特蕾希雅拜托波尔德对威尔海姆保密。恐怕就是因为她打算自行和父亲算帐吧。

拜托不要闹大。波尔德恳切希望。

「假如需要见证人，我很乐意陪同前往……」

「不用啦。波尔德大人也很忙吧，哪能再麻烦你。而且，这是我跟威尔海姆的问题，我们夫妻……夫、夫妻！我们夫妻会一起解决的。没错。」

见她红著脸还这么振奋，波尔德也只能退下。

虽然还是担心，但特蕾希雅朝他深深低头，然后飒爽离开广场。

要去找亲生父亲贝尔托•阿斯特雷亚算帐。──从背影可以窥见她的觉悟。

「不管怎样，你们两个可都要平安无事啊，真是的。」

说著说著都觉得自己老了。波尔德往城堡迈步。

希望三天后的结婚典礼能顺利进行，现在只能这样祈祷──

5

这次卓格夫队的巡察任务，预计是以王都为中心绕巡街道。

被称为王国五大都市的各都市都已派遣王国军去帮忙复兴以及恢复治安，所以这次的主要视察对象为街道沿线上的小城镇。

本来这方面的任务派遣，不太可能会落到王国军的顶级精锐卓格夫队。不过这足兹证明这次的任务确实是在某人的巧思下方得运作。

『说是特蕾希雅大人的父亲动的手脚，会不会想太多？』

「因为你没见过他本人。要是亲眼见过，你就会说我的想法未必是笑话了。……虽然不是不能理解他过度保护女儿的理由啦。」

骑乘的地龙并驾而行，格林的意见惹来威尔海姆的嘴角下垂。战友对这回答苦笑，在纸上又写了些字。

在「除风加持」的庇佑下，坐在地龙背上不会受到风或摇晃的影响。尽管如此，能在龙背上流利书写依旧让威尔海姆暗中感到佩服。

『习惯了啦。』

「……我什么都没说吧。」

被他从表情判读到内心，让威尔海姆不高兴地皱眉。这反应令格林微眯眼睛，结果威尔海姆不爽地说。

「干嘛啦。一脸蠢样子。到时摔下地龙我可不管。」

『你的婚礼在三天后，让我深深感慨。你变得更出色了呢。』

格林看起来是真的很感慨，结果威尔海姆都没力气念他了。

跟格林的孽缘长达七年──对威尔海姆来说，等同于从军的时间。当然也包含自己搞失踪的那两年。跟波尔德和卓格夫队的老兵的交情架构出这段历史，不过威尔海姆若有所思。

「……说真的，遇到你的时候，我还以为你马上就会战死。」

『对吧。我自己也没想过能活过内战。到现在都还觉得是不是哪里搞错了，是用尽了一辈子的幸运才会在这里吧。』

「一辈子的幸运啊。」

幸或是不幸，这种认为人生被运气左右的想法，威尔海姆甚是讨厌。特别是在战场──铁屑火花激烈磨削生命力的生死关头更是如此。

在战场上的生死，端看当事人至今累积了多少经验，应该只被那左右才对。

以剑抗剑，以魔抗魔，以命抗命，必须是这样才对。

因此，若是以前的自己，会在这时狠狠痛斥格林。但是现在，自己稍微改变了想法。原因在于邂逅。

──遇见了让自己以为用尽一辈子幸运的女性。

『你变圆融了。』

「可恶。」

沉默的时候，眼前突然被递出这样的句子。因为内心再度被看穿，使得威尔海姆粗暴地把纸笔推回去。

「────」

对这反应感到满意的格林转移注意力。他拔出别在龙鞍上的短铁棒，朝自己的腿──绑在上头的钢板敲击，发出高亢声响。

钢板是代替哑掉的格林朝周围传达指令的道具。听到钢板的声音，跑在两人后方的康吾德追上来，骑在旁边。

「叫我们吗？」

『我想再次确认巡察的行程。因为这次的时间特别宝贵。』

「这点毋庸置疑。」

瞭然于心地点头，康吾德凝视威尔海姆。对此威尔海姆不做反应，「剑鬼」也是有学习的。

「可不能让特蕾希雅大人一个人寂寞地进会场。队员们全都将此铭记在心。出发前大人说的话，让我们更加振奋。」

「那就好。总而言之进入主题，主题。现在立刻。」

威尔海姆一瞪，康吾德就从怀里掏出地图摊开来。图上画了王都周围，行进路线用红线标明，目的地则是在上头作记号。

「首先，我们会走鲁法斯街道前往弗洛丽。从那继续朝西走，依序绕过谬尔格雷、波诺波、库拉姆林，最后回王都。必须强行军才能赶回去。」

「单看距离的话要两天……包含视察在内的话，三天可能不够。」

「为了避免那样的情况，路上就要全力奔驰。最差的情况就是舍弃慢的家伙。我们全员都做好了若是会拖累队长那不如一死的觉悟。」

「不要为了这种事而死啦……」

康吾德满脸认真，出发前队员们的谈话看来不是玩笑话。不管怎样，这次确实是要挑战将有限的时间压缩得更短。

「再来就是对各城镇的视察，若是能在最低限度完成的话，应该就来得及。」

「那样好吗？巡察的目的是要维持治安吧？若只是去到却不作为，那不就失去任务的意义了吗？」

「没有问题。毕竟这次巡察的目的地都在王都周边……要说的话，就是目前王国治安最好的城镇。所以说，抵达之后只要让他们晓得若是敢做坏事，可怕的『剑鬼』就会从王都飞奔过来就行了。」

『我们说的露个面，就是这个意思。』

接话做最后说明的格林点头要他别担心。

总觉得任务被放大解释了，不过确实只要有做到形式上的察访，那时间就会稍微充裕一点。将时间和任务放在天平上做妥协的结果就是这样。

「这也是我变圆融……不，只是变得会耍小聪明吧？」

『这也是为了特蕾希雅大人。』

「这样子说是逼我接受吧……」

嘴巴这样讲，但这次的任务可以有理的话，谁会想要用歪理走天下。

「照这速度，若是将巡察时间压缩到最短，那只要耗时两天半就能完成任务。若有半天的时间，回到王都后还有时间可以做结婚典礼的预演。对大家来说就是额手称庆了。」

「真那样的话就好了……」

是为了要消除不安吧，康吾德话讲得开朗轻松，但威尔海姆却没法那么爽快。他内心还是有莫名不安与担忧所形成的疙瘩。

队员们团结一心，要让威尔海姆赶上婚礼。虽然感激他们，但贝尔托的企图──有那么容易被破除吗？

『真不像你耶。果然还是很不安？』

「因为是和不拿剑的对手战斗，而我只能巡逻。」

『明白了。如果你那么不安，那我希望你能放心。第一个目的地弗洛丽几乎是通过就行。』

见威尔海姆面罩阴霾，格林这么写道然后递给他看。扫视过内容后，威尔海姆瞪大眼珠。

「──？你为什么那么肯定？」

『弗洛丽是我的家乡。居民我大致都认得。我会跟他们说这次的巡察要尽快结束。』

「嘿～我都不知道。原来你老家这么近啊。」

出人意料的声明让威尔海姆抬眉，格林心境复杂面露苦笑。

威尔海姆对这表情有印象。那是没有尽孝道的人才会有的容颜。跟兄长吵架后离家出走最后错过道歉机会的自己，也有同样的表情。

「俗话说得好，历史是人走出来的。我们也不能置身事外。」

「我们队伍是不孝团体吗。听到我们是王国军的精锐会让人傻眼呢。」

乘著康吾德的嘴皮子，威尔海姆仰仗他们的好意。心情稍微轻松多了。自己很幸运有这么一群好伙伴。──但这话就算撕裂嘴巴也说不出口。

『谢谢。总而言之，弗洛丽那边交给我。』

在格林强力请托的时候，街道尽头已经可以看见建筑物冒头。

是话题中的驿站村弗洛丽现身了。巡察的第一个关卡，能够按照格林预定的话术尽早脱身吗──

「──啊？」

正当这么想，看到村庄的样子后威尔海姆惊愕出声。而且卓格夫队全员都有同样的反应。

为什么呢？因为弗洛丽的入口高挂「欢迎！本村的英雄凯旋归来！」的布帘，而且居民也全都到入口处欢迎卓格夫队的到来。

远远地就能听见欢呼。知道一度舍弃故乡的少年如今在王国军是有头有脸的人物后，整个故乡的人与有荣焉一同大肆庆祝。

而那个少小离家老大回的放荡子是谁，已经不言自明。

「……喂，这样真的能够迅速说服他们吗？」

全员一致看向格林。身为队伍代表人物的威尔海姆这么问正大量冒汗的格林。

对这问题，格林用颤抖的手在纸上写道：

『我努力。』

他用摇晃的文字，做出跟方才强而有力的宣告完全相反的回答。

6

「真没想到！那个旅社的败家子竟然衣锦还乡了！」

『好久不见。对不起，我知道大家有很多话要说……』

「格林你好厉害呀！我后来马上就离开军队回老家了……」

『战场很可怕，也难怪啦。』

「格林啊。其实呢，我有一桩不错的婚事，你能不能跟对方聊聊呢？」

『对不起！我已经有正在交往的女性了……』

就这样，和家乡故旧聊过一轮后，卓格夫队总算能够离开弗洛丽村。

按照巡察的行程表，原本分给弗洛丽的时间预计是两个小时。

而这两个小时借助弗洛丽出身的格林，使得时间拉长到超过五个小时，最后总共用掉七小时后才成功脱身。

「我再也不会相信你的话了！」

在队伍前头催促地龙的威尔海姆怒声道。被「剑鬼」这样骂，格林这下也抬不起头来。

原本发下豪语结果却是惨败，也难怪会沮丧了。不如说他若是不好好反省这件事的话就太不像话了。

「队长，不要那么生气。离家出走的儿子荣归故里，家人会喧闹到这么久也是在所难免……」

「假如只有家人也就罢了，不只亲戚，连恩师、儿时玩伴全都跑来！甚至连其他镇上的远亲都来了……他们以为他们在办祭典啊！」

回顾长达七小时的盛大祭典，威尔海姆破口大骂。

其实乡里百姓对于格林出人头地的喜悦非比寻常。特别是他的至亲，一看到他回来就痛哭流涕。

『我父母似乎以为我死掉了。』

「毕竟初相遇时你身体弱不禁风，而且又音讯全无好几年，难怪会被这么以为。」

当时的格林不可能活得长久，这一点应该是大家都赞同的。靠著许多的侥幸偶然，格林现在才能这样跑在旁边。

以他的说法，可能就是幸运的恩赐吧。

「虽然时间被要命地拉长很多，但副队长的家人都很高兴，这是好事。以巡察旨在彰显军队存在感这方面，可以说是前所未有的大成功。」

『这次的事，』

「──不用，算了。就如康吾德说的。我们姑且完成了第一项任务。」

打断又想要道歉的格林，威尔海姆主张康吾德说得对。

老队员的意见，同为对亲人不孝的威尔海姆有切身之痛。

其他队员姑且不论，至少威尔海姆是没有可以联络的家人了。由于受到内战的战火影响，他的家人和故乡全都毁于一旦。

不管是离家出走还是音讯全无，全都是格林也做过的事。要说不一样的地方，就是威尔海姆再也没机会向家人道歉了。

在这层意义上，格林能够跟家人和亲戚重逢，应该要感到高兴。

「从现在开始挽回局面就好了。做为今天的反省，你以后要定期寄信回老家。」

「────」

「反正，下次你带卡萝回去的时候，全村会闹得更热闹吧？」

威尔海姆端出格林的女友的名字，要求以此来挽回他犯下的错。

格林的家人对他在军中获得副队长职务一事感动落泪。要是知道这样的他将会娶贵族之女为妻的话，无法想像他们会有多惊讶。

『多管闲事耶。』

因为失态而一脸消沉的格林，终于恢复了笑容。

回答的同时也恢复了精神，重新面对街道。──现状来看，原本可以缩短的行程被大幅拉长，但还在可以挽回的地步内。

「幸好，接下来要去的城镇都不是我们队员的故乡。」

「这样啊，那真是好消息。要是又被亲戚朋友团团包围，那我可受不了。」

『这个确定不是讽刺？』

「只是不想再重蹈弗洛丽的覆辙。你被害妄想症耶。」

撇开不能释怀的格林不谈，卓格夫队拼命地在鲁法斯街道上狂奔。

然后，平安抵达下一个目的地谬尔格雷。

这里就没有发生弗洛丽那种人海祭典骚动，巡察也在短时间内结束，得以在不被拖累脚步的情况下出发。

『幸好没什么事。就照这样冲吧。』

「争取到多少时间？」

『还是超时四个小时。』

「又没问你那个。」

话虽如此，有缩短超时的时间就是很确切的成果了。

照这个样子缩短行程的话，应该可以在婚礼几个小时前回到王都。

「这样一来……」

就不会惹怒特蕾希雅了。没错，威尔海姆抱著一线希望这么想。

──但是一抓住希望之线就断成了好几截，这也是理所当然的事实。

7

王都贵族街，是唯有在王国首都拥有特殊地位的人方能居住的区域。

庄严又豪华的建筑物，整齐干净的石板道，等距离设置的全新魔法灯照耀黑暗，往来龙车都是几乎不出声的一等一高级品。

受长期内战的影响而民生凋敝的王国──这样的说法却不适用在这个地方。贵族街依旧保留著有如另一个世界的气氛，拒绝外界的一切。

纠纷和吵闹全都被禁止──这就是贵族街的风格，这里有这里的潜规则。

有两名女子正高声踏步走在这贵族街的一角。一人飒爽地以肩膀破风前进，另一人则是呼唤对方。

「特、特蕾希雅大人！您、您真的要和贝尔托大人商量吗？」

「那还用说，卡萝。这次的事太过头了，就算是我也生气了。」

走在前头的特蕾希雅，对讶异地瞪大眼睛的同行人──金发碧眼给人敏锐印象的女性嘟起嘴唇。而走在后头的女性──卡萝一脸伤脑筋。

「还是说，卡萝你反对我？也反对我们的婚礼……？」

「请不要露出那么不安的表情！我怎么可能反对特蕾希雅大人的意愿！虽然我确实不喜欢您的结婚对象……」

「那，你果然还是反对啰……？」

「──唔！请不要欺负我，我会哭的！会嚎啕大哭丢人现眼的！」

「抱、抱歉，对不起。没事的，我相信你。」

眼见紧绷的美貌即将崩坏，特蕾希雅连忙安慰卡萝。

长期服侍她的随从平常是个坚决的人，但只要扯到特蕾希雅就会处处变得脆弱。最近则是在操烦她的男友格林的事，然后与特蕾希雅的联系又有威尔海姆来插手，总之感情方面很脆弱，还很喜欢可爱的东西──

「卡萝意外是个要人费心的女孩子呢。」

「您、您突然讲那什么话呀。我是特蕾希雅大人的首席随从兼保护者。不管是从今还是往后，都请您仰赖我。」

「嗯。你非常可靠喔。」

「是！」

特蕾希雅拍了拍她肩膀，卡萝眼泛光芒用力点头。「好！」然后干劲十足的她突然忖度。

「奇怪？怎么变成乖乖照特蕾希雅大人的话去做了……？」

「好啦，父亲和母亲应该就在这里。我要狠狠说一顿。」

毫不理会卡萝的疑问，特蕾希雅朝著贵族街里某一间豪宅──让远道前来王都的人们可以歇息的迎宾馆就在眼前。

为了参加隔天的婚礼，特蕾希雅的双亲──阿斯特雷亚家的当家贝尔托及其妻子媞舒雅应该都已抵达住进这里。

「一开始说不住在我跟威尔海姆家，反而说要借住迎宾馆的时候我就觉得奇怪了。一定就是不希望在使鬼把戏的事被我发现。」

「原来如此，顺便问一下，贝尔托大人是用什么说法拒绝住进宅邸呢？」

「说我和威尔海姆是夫妻，那边已经是我们组成的家了，不想因为双亲入住扰乱我们的生活……没什么，那个，我可不是被夫妻这种字眼给骗过去的喔？」

「……是，我明白。在下卡萝会站在特蕾希雅大人这边的。」

说完，卡萝温柔微笑。

跟内战结束后的庆祝典礼上，默默看著特蕾希雅准备去收取并不想要的荣耀时所露出的微笑一模一样。

也就是掩盖内心的笑容，而特蕾希雅没有勇气去确认她的真心。

「总而言之，上吧。──为了不让父亲再搅局。」

「这次的事，就算贝尔托大人认错也无济于事……」

「这次就算了。但是我要他答应我以后不会再这样。因为──」

走向迎宾馆的入口，特蕾希雅回头看向紧跟在后的卡萝。

然后用全盘信任的眼神清楚断言。

「──威尔海姆一定会赶上婚礼。因为他答应让我当他的新娘，所以说，用不著担心。」

说完，她就著这股气势，气宇轩昂地把手伸向迎宾馆的大门。

8

──而另一方面，被特蕾希雅寄予完全信赖的威尔海姆。

「────」

一片黑暗的空间。

这里完全被漆黑给支配，是没有一丝光芒的世界。

四面八方都没有光源，空气蕴含著苦涩的沙味和触感。鞋子底下感觉很硬却又湿滑。可以说是极为恶劣的环境。

在这样的黑暗中，不断地有高亢的金属声在回响。

钢铁互撞的声响在漆黑中反弹，渐渐地朝遥远深处消失。凝神细听，察觉到声音消失在远处后这才叹气。

「真深啊……」

对这毋庸置疑又清楚明白的结论，却无人出声附和。

但这也难怪。毕竟以现状来说，现场除了威尔海姆以外就只有两人。其中一人在「剑鬼」的怀中晕了过去，另一人则是──

「────」

被拍肩膀，威尔海姆回头。因为暗，所以看不见对方的脸。可是熟悉亲近的气息让他立刻知道对方是谁。是格林。而这是最糟糕的答案。

伸手不见五指和格林，用不著说明这两者的搭配有多惨吧。

对只能靠笔谈沟通的格林来说，黑暗是最大的天敌。看表情和动作多少可以了解他要表达的话，但在黑暗中连要这么做都没办法。

「──！」

「就算你那么拼命，我也不知道你想说什么啦……」

八成是对现状的恶劣感到悲观和慌张吧。

只听得见他沙哑的吐气和呻吟，反而是威尔海姆比较冷静。人类只要觉得别人比自己狼狈反而就会沉著下来。现在就是这样吧。

搞不好是因为不幸接二连三发生，反而逼使自己到达顿悟的境界。

「啊……」

威尔海姆边抓脸边看头顶。那里是被岩盘堵住的洞窟入口，可是太高了，根本碰不到。如果要仰赖格林钢板的回响的话，那就只能相信洞窟深处有别的出口，继续前进了，但──

「我大概会被特蕾希雅杀了吧……」

在赶上结婚典礼之前，要先怀疑自己能否平安回去吧。威尔海姆叹气。

离结婚典礼只剩半天──身在活埋自己的洞窟中，「剑鬼」踏出了第一步。

9

──面对面对峙的男子所释放的威严，让卡萝静静屏息。

那跟唯有一流剑士才会有的剑气十分类似，但是眼前的男子不擅使剑是众所皆知的事，这点卡萝也非常清楚。

因此，这一定是异于剑气的意志波动。

「──首先感谢您亲自移驾至王都。」

在浑身僵硬的卡萝身旁，她一辈子的主人特蕾希雅开启了对话开端。

她的眼神锐利无比，半吊子的人光是接触到这视线都有可能被压倒。可是现在的对象别说胆怯了，还正面承受目光，轻启唇瓣。

这是当然的。要说为什么的话，因为特蕾希雅的目光所指并非敌人──

「这招呼太隆重了，特蕾希雅。这里就只有我们家人。你可以轻松一点说话。」

「可是……」

「别让我重复说。这里就只有我们家人。我是你父亲，用不著那些表面话。」

朝特蕾希雅微笑这么说的，是个跟胡子很搭的壮年绅士。个子修长，红发丰盈，明亮的蓝色双眸──这些特征都跟特蕾希雅一样，毕竟他们是直系血亲。

男子名为贝尔托•阿斯特雷亚。是特蕾希雅的亲生父亲，也是历代「剑圣」辈出的阿斯特雷亚家现任当家，立于剑士家世顶点之人。

只不过与此头衔相反，当事人在剑术方面是一窍不通，这件事也相当有名。

「──卡萝。」

「……ㄗ、在！久疏问候，贝尔托大人。」

「招呼就免了。你怎么也这样。不管是特蕾希雅还是你，都用不著这么绷紧神经的。是做好了会发生什么事的准备，对吧？」

话题拋向自己，难掩紧张下，卡萝挺直脊梁。与贝尔托的距离感难以估算，使得她没法顺利与之对话。

这关系到卡萝的原生家庭和阿斯特雷亚家，不过那又是另一个问题了。

「父亲，请不要太欺负卡萝。这女孩个性很正经。」

「说什么欺负，太难听了。不过，事情似乎很顺利。你可能在为明天的事紧张，但其实用不著……」

「──父亲，我就是要来讲明天的事。」

打断贝尔托的话，特蕾希雅锐利地切入正题。卡萝也因此面颊一僵，贝尔托则是微微眯起眼睛。

「被明天婚礼的主角新娘说要谈明天的事，叫人紧张呢。」

为了缓解紧张感，贝尔托泛笑这么说。

从他的微笑，完全感受不到对明天一事的抱歉之意。这件事令卡萝颤栗。威尔海姆婚前巡察一事已经很明显与他有关，所以才吃惊。

完美地将谦虚穿在身上，来面对明显是来兴师问罪的女儿。

「按照传统，新娘是要来感谢双亲养育自己至今，以及对未来起誓吧。这些大多都在典礼前进行，不过又怕到时止不住哭泣，所以这样也不赖。」

「感谢是一定有的。不过今天来，不是为了那件事。」

「那就是要延后婚礼，还是中止？都明天的事了才说这种话，我可很难接受。这对当家来说太丢脸……没错，是耻辱。」

见特蕾希雅摇头否认，贝尔托触及最糟糕的可能性。口说婚礼可能中止的他用手掩面，像是在高呼可悲。

「我就想说怎会只有你和卡萝来，该不会是新郎逃跑了？还是说他病重或者有其他问题？当初见面时就已经大致调查过他的身家，莫非他还是有所隐瞒？不不不，应该是没有表现出来的个性或嗜好……或者特殊性癖好？」

「父亲！」

「冷静点，特蕾希雅。这没什么好丢脸的。彼此的感性对夫妻感情是很重要的。在正式结婚前发现不协调很值得庆幸。唉呀，婚礼告吹是很丢脸，但取而代之了解到更重要的事……」

「父•亲•大•人！」

贝尔托越讲越多、越说越快。特蕾希雅则是一个字一个字地叫他，就连贝尔托都吓到闭嘴瞪大眼睛。特蕾希雅视线朝上瞪著他。

「我明明什么都还没说……父亲似乎很希望丢人现眼。」

「希望丢人现眼？这话太奇怪了。我只是把你……」

「──父亲，您对威尔海姆做了什么吧？这点事我还知道的。」

特蕾希雅毫不留情地朝虚张声势的贝尔托施以言语剑击。女儿的视线和顶嘴，让他沉默半晌，然后──

「──假如我说是呢，你要怎样？」

贝尔托露出看起来就是幕后黑手的残酷浅笑。即便以「假如」来装饰，但丝毫不见他打算隐瞒微笑后头的真相。

特蕾希雅的怀疑是正确的。贝尔托的笑容和态度证明了这点。

「谢谢您至今以来的照顾。我要舍弃阿斯特雷亚这个姓氏。永别了。」

「咦！？等、等一下，特蕾希雅！爸爸不准你这么胡来！」

「不准胡来的是您吧！为什么父亲要动那种手脚！见面的时候也是，您到底看我的威尔海姆哪里不顺眼！」

单刀直入的特蕾希雅让贝尔托慌了手脚，面对后续的追究视线始终游移不定、张口结舌。方才所展现的威严整个荡然无存。

眼前就是个在背地里耍小手段，让人大翻白眼的小人。

「父亲您的作法太阴险了！假如不喜欢威尔海姆，那就直接当面说出来便是。他哪里不行，来，说呀！经历？家世？剑术？长相？经历方面他万分努力，老家原本也是贵族出身。剑术不用我说，脸也长得很帅吧！？」

「特、特蕾希雅大人，话题偏了……」

「才没有！威尔海姆很帅！卡萝也是这么认为的吧！？」

「我的格林才是最帅的！」

受到心直口快的特蕾希雅影响，卡萝不小心就说出了真心话，为此面红耳赤。特蕾希雅也手摀嘴巴，说：

「卡萝真的好可爱……」

「请、请别戏弄我，特蕾希雅大人……！」

「对啊，别开玩笑。爸爸惊讶过度，寿命都变短了。」

「我跟父亲您说的可不是玩笑话。我是真的要走人！」

「咦咦！？为什么！？」

「什么为什么，因为您妨碍我结婚啊！为什么不懂！」

被特蕾希雅怒吼，意志消沉的贝尔托把身子缩得更小。他那样子连卡萝都忍不住想要叹息，决定看到最后。

这对父女的互动，每次都是这样子。

贝尔托一开始都会表现得威严十足，然后被特蕾希雅充满感情的发言给粉碎。特别是最近，自从特蕾希雅要结婚的事成定局后，这种互动就从没少过。

对于频繁地听特蕾希雅抱怨的卡萝来说，这是早已知情的事实。

「还没见面就先擅自调查过去经历，又介入卓格夫队的人事安排不想让威尔海姆当队长，还有婚礼的日期不知道延期几次，让人都搞不清楚确切时间……做了那么多手脚把我对您的敬意也用尽了！不如说没有马上看出来的我反而像个笨蛋！」

「因为特蕾希雅大人很善良。不过，这次就连我也觉得不是很恰当。」

「什么！卡萝，怎么连你也讲这种话！」

主子扳著手指细数婚礼被妨碍的次数，使得卡萝也用轻蔑的目光看贝尔托。被这眼神刺到的贝尔托气得胡子都翘起来，指著卡萝喋喋不休。

「卡萝，雷玫迪斯家之女。你身上流的是代代侍奉阿斯特雷亚家的雷玫迪斯血统。这样的你竟然敢对阿斯特雷亚家当家的判断有意见！」

「您所言甚是，但在归属于雷梅迪斯之前，我是一介凡人卡萝。而且我效忠的不是阿斯特雷亚家，而是特蕾希雅大人──」

「咕唔唔……！」

被直接这样断言，贝尔托语塞。而斜瞄接不了话的父亲后，特蕾希雅对卡萝这番话是感激到双眼湿润。

「……假如我是男人的话，一定会娶卡萝为妻的。」

「荣幸之至。」

「慢、慢著！爸爸不准！就算对象是卡萝我也不会把特蕾希雅交出去的！」

「那只是假设，实际上根本不成立。……算了，比起这个，父亲。」

特蕾希雅眯起眼睛凝视慌乱到连玩笑话都当真的父亲。

「您刚刚说就算对象是卡萝吧？所以说您妨碍婚礼的原因不在威尔海姆身上，而是别的事？」

「呃呜！」

「刚刚贝尔托大人语塞了一下？」

贝尔托变得脸色苍白，双目泅游，身体发抖。他就是个不够谨慎、无法隐瞒事情的人。假如没扯到女儿的话，本来还比较正经。

这段期间特蕾希雅仍默默地继续瞪著他。贝尔托的想法已经很明显了，但是被妨碍结婚多次的特蕾希雅没打算轻饶他。再这样下去贝尔托会晕倒。

「──唉呀呀，怕成这样。亲爱的你也该放弃了。」

不过在他昏倒之前，第四个人现身在谈话室里。

听到声音，三人转头，接下来的反应都不同。贝尔托的脸变得更惨白，特蕾希雅鼓起脸颊，卡萝则是弯腰一鞠躬。

「媞舒雅大人，久疏问候。请原谅卡萝。」

「用不著那么死板。你就像我的女儿一样。」

朝著打招呼的卡萝笑著这么说的，是有著亚麻色长发的妙龄女子。其容貌跟她的真实年龄相较之下年轻得叫人讶异，且充满妖艳魅力。

女子名为媞舒雅•阿斯特雷亚，贝尔托之妻，特蕾希雅的──

「──母亲。」

「你也是，特蕾希雅。用不著鼓著腮帮子。难得我把你生得那么可爱，要是露出那种表情的话，会被威尔海姆先生嫌弃喔。」

「他才不会嫌弃我咧。……大概。」

「是吗。那很棒啊。──所以，亲爱的？」

特蕾希雅的母亲媞舒雅为女儿的痴情绽放笑容，接著视线朝向丈夫。目光流转让贝尔托的肩膀震了一下，然后慌慌张张地挥手。

「等、等一下，媞舒雅。这个是，那个，误会……对，是误会。」

「误会？要嫁女儿了很寂寞，所以就故意不断刁难未来的女婿，甚至还硬塞跟婚礼时程相冲突的任务，骯脏手段被女儿当面揭穿，闹到最后甚至要断绝亲子关系……我有误会吗？」

「呜哇啊……」

不愧是特蕾希雅的生母，媞舒雅的追究比女儿有过之而无不及，贝尔托也不辩解就直接当场下跪。是说奸计被人如此客观地陈述，让人不忍直视他的小心眼。

朝著被击溃的贝尔托叹气，媞舒雅转头看女儿。

「对不起喔，特蕾希雅。这个人不但心眼小，器量更是狭隘外加没脑袋，才会也给你们添麻烦。」

「那个，母亲……一般来说，做妻子的会稍微偏袒丈夫一点吧……？」

「可是这个人的作为，有哪一点可以让人为他说话吗？」

没有。这是贝尔托以外的三名女性的共同看法。

被妻女和等同女儿的人给责难，贝尔托的自尊粉碎殆尽。不过虽然受挫，但他还是抬起头。

「好、好呀，随你们高兴怎么说。但是，事实不会变的。只要那个青年赶不上婚礼，就会让阿斯特雷亚家颜面扫地。到时婚约就算是破局，特蕾希雅也就不用结婚了……！」

「为什么要做到这种地步……父亲是希望我嫁不出去吗？到底想怎么样？」

「那还不是该在此时此地说出口的话。」

「就算装模作样，理由还不是小家子气。反正就只是想把可爱的女儿永远留在身边，没肚量所以就做出妨碍之举。」

「媞舒雅！？你到底是站哪边的！？」

「唉呀呀呀，还用说。当然是特蕾希雅这边吧？」

「你说什么！？为什么！？你是我妻子耶！？」

「有谁规定妻子就理所当然地要以夫为尊？你未免想得太美了吧。」

媞舒雅的毒舌让贝尔托翻白眼，分不清他被击垮几次了，但这次确实再起不能。看这样子，他也知道妻子不可能说什么好话。

「想法和目的，都太浅薄了……」

「不过那正是这个人的可爱之处。」

傻眼的卡萝说，媞舒雅则是用恶作剧的目光望向丈夫。这对夫妻的关系叫人觉得不可思议，但其实是媞舒雅比较迷恋贝尔托。

虽然这件事连来往很久的卡萝都怀疑，不过这且先不提──

「对母亲您来说或许很可爱，但对我来说却是烦恼。因为父亲的愚蠢小心眼企图，让威尔海姆不知道遇到怎样的事……」

「刚刚也说过了吧，正因为他心眼小，所以也成不了大事。虽然有在路上安排一些拖延时间的陷阱……但全都是轻微到让人觉得不是要真心阻止婚事的事。换句话说，这次的事是他的最后挣扎。」

「最后的挣扎吗？」

媞舒雅轻触不安的特蕾希雅，温柔地说。卡萝不禁皱眉。

见她如此，媞舒雅垂下被长睫毛包围的双眼，说：

「没错，最后的挣扎。为了特蕾希雅的幸福，想要测试未来的女婿到最后。这是他身为这个家庭里唯一幸存的男性，想抬头挺胸喔。」

「啊……」

媞舒雅的话让特蕾希雅和卡萝瞪大眼睛。

阿斯特雷亚家最后的男性──对于在「亚人战争」中失去两位兄长和一个弟弟，如今全家只剩下自己是继承人的特蕾希雅来说，贝尔托既是家人也是父亲，而这次的事是他身为父亲最后的坚持。

「提姆兹哥哥，卡尔朗哥哥，卡吉雷斯……」

低垂眼帘的特蕾希雅呼唤的，是三名战死的亲兄弟的名字。卡萝觉得他们兄弟姊妹感情很好。至少他们全都很爱特蕾希雅。

道出亡故的兄弟名字后，特蕾希雅看向媞舒雅。

「要是哥哥们还活著……果然会反对我的婚事吗？」

「谁知道呢。假如那些孩子们没有像爸爸一样不懂是非的话，应该不会做出这样丢人现眼的事吧……不过，我认为他们会想去测试的。因为想知道威尔海姆先生是否真能让你幸福。」

「我早就已经很幸福了。」

「是要看他能否未来也让你永远幸福喔。」

特蕾希雅的低喃惹来微笑，接著媞舒雅靠近颓然倒地的贝尔托，把手放在不像样的丈夫的肩膀上。

「好了，你们应该还要为明天的婚礼做准备吧。特别是新娘，明天一整天可要打扮成人生中最美丽的样子。」

「可是母亲，父亲他……」

「这次是一家之主的最后挣扎，我不会再让他乱来了。而且这个人动的小手脚，你的新郎肯定可以跨越的，对吧？」

「当然，应该啦。……呃，母亲。」

反射性地回答母亲的挑衅后，特蕾希雅露出苦瓜脸。发现自己误上贼船时已经太迟了。

如此一来，特蕾希雅就失去了紧咬贝尔托的理由。

「不过父亲，您真的该好好反省！我这次是真的生气了！」

「我、我考虑考虑……知道了！我说知道了！我会反省！真的啦！」

耍嘴皮子结果引来剑气，贝尔托认真地宣告投降。见父亲这样，特蕾希雅从鼻子喷气，卡萝也有气无力地耸肩。

「总觉得好累……」

「不过，您很了不起。──我也很期待明天。」

卡萝带著微笑的回答，让特蕾希雅微微讶异抬眉。

「卡萝你也相信威尔海姆赶得上啊。有点意外……」

「因为有格林跟著……开玩笑的，不过我也相信喔。那个男的……威尔海姆一定会来接特蕾希雅大人。」

这么回答的卡萝，脑子忆起「剑圣」特蕾希雅恢复成一名女性的那一天。

当时，被威尔海姆拯救的不只是特蕾希雅。虽然不曾说出来，今后也绝对不会道出口，但是卡萝也是被他拯救的人。

那天「剑鬼」的爱意和战斗，如今仍烙印在眼底。

「所以说，特蕾希雅大人，去为明天做准备吧。媞舒雅大人说得对，明天的您将会是全世界最美的女人。请让我帮忙。」

「卡萝……」

「只不过要把特蕾希雅大人交给那个男的，就觉得一肚子火。」

「我也这么想。」

「父亲──！！」

卡萝用来掩饰害臊的话得到快速振作的贝尔托的肯定。对此特蕾希雅放声大叫，脸整个通红。

只不过红著的脸蛋与其说是愤怒，反而是因为期待明天的到来而闪耀生辉。

「……我等你。」

脸还是红通通的特蕾希雅朝著不在场的心上人这么低语。

在明天的婚礼上，心爱的他会破除贝尔托的所有诡计，亲自来迎接自己。特蕾希雅毫无疑问这么相信──

10

──而另一方面，当在王都的新娘口说全盘信赖的同时。

「……混帐，连空气都是泥土味。」

带著脏话吐掉口水的青年转头看向四周。

但是身在被厚重岩壁覆盖、光线又到不了的洞窟深处根本什么都看不到。只能瞎猜乱踩来确定踏脚处，抱著一丝希望跟著风走。

地点在王都东南方，城镇「库拉姆林」附近的柯鲁多罗山的山腰──以别称「土蛇巢穴」闻名的洞窟。是个危险的地方，就连当地人都不敢靠近的魔窟。

而半天后就要参加婚礼的新郎──威尔海姆却被关在这种地方，跟字面的意思一样陷入险境。

──时间回到事发前的几个小时。

靠著强大意志力在巡逻的卓格夫队，除去在弗洛丽被绊住脚步的状况，接下来的行程全都平顺地按照预定走。以风车闻名的谬尔格雷和以酿酒厂为人所知的波诺波都在短时间内就巡察完，毫无滞碍地抵达最后的目的地库拉姆林。

会在此滞留，是因为村民向卓格夫队报告：「村里好几个小孩下落不明。」

单纯夜游、迷路或恶作剧的可能性不是没有，但是一次好几个小孩失踪确实不寻常，因此查明这件事就成了为维持治安而巡察的卓格夫队的任务。

「队长，在这边花时间的话会……」

「赶不上婚礼。所以要我跟特蕾希雅说我丢下小孩以她为优先吗？到时不只是我，你们也全都会被她宰了。」

『是呢。我也会被卡萝小姐骂。』

这就是卓格夫队对多个小孩失踪事件的结论。

以婚礼为优先而轻视职责的话就本末倒置了──威尔海姆给的答案，队员们没人有异议。取而代之，之后队伍的行动相当迅速。

村里的搜索就交给居民，卓格夫队负责到附近的山林野地间搜索。就这样，追著在城镇后方的科鲁多罗山山脚下发现的脚印，然后找到了从山路的缺口滑落到洞窟的孩子们。

以当时的时间点来说，在库拉姆林逗留两个小时──虽然比预期时间长，但还来得及补救。

带著放心下到洞窟的威尔海姆，将四个小孩一次一人推到洞窟上方，正当心想要回到村庄结束巡察的时候。

──突然地震，洞窟入口崩塌。偏偏挑在这种时候。

四周微微晃动，接著土石开始崩落。随著摇晃变得剧烈，岩壁上的裂痕也伸长扩展，最后洞窟被土石埋没，原本的入口变成了一堵墙壁。

而在洞窟里的除了威尔海姆和最后一个准备要出到洞窟外的小孩以外，还有地震发生后立刻将怀中的孩子拋给同伴但自己摔下来的格林，就这三人。

──接下来的好几个小时，三人一直在黑暗中仿徨。

「我是觉得比挖掘入口还要好啦……但事到如今我开始觉得留在原地等待救援还比较好。」

在黑暗中绷紧神经，伸手不见五指的状况让威尔海姆这么说。顿时，洞窟内就响起高亢的金属声，像在责备他。

轻快的声响是无声格林的抗议。钢板就绑在他的左脚，靠著敲打来传达意思。威尔海姆从中感受到他强烈的「不要放弃」的意思。

多亏了他的神经质，两人原本不靠语言也能传达意思，但现在除了笔谈以外，格林的抱怨成了物理上的吵人。用不著他说自己也不打算放弃，以威尔海姆来说只想早点离开洞窟和金属噪音。

该说幸运吗，被找到的男童在洞窟崩塌时晕了过去，直到现在都还没清醒。格林负责背娇小的身体，威尔海姆负责警戒，走在前头朝洞窟深处探勘──放弃被土石塞住的入口，仰赖在洞窟内流动的风不断寻找其他出口。

「────」

时间一分一秒的过去。

洞窟里缺乏光源，探索的速度迟迟没有上升。内心越来越焦虑。

抵达库拉姆林时，已经是火之刻快要结束的时候了。现在，外头应该是太阳下山，气温开始下降了吧。灌进洞窟里的风也开始变冷，状况一点一点地恶化。

这样下去赶得上婚礼吗？令人绝望的状况加速焦躁的心情。

不过──

「喂，不要跑那么前面。地面不稳，要是突然坍塌，头下脚上栽下去的话，我可没自信可以救你。」

格林呼吸急促，脚步也很急。看起来比婚礼当事人威尔海姆还要著急。他这样的态度让威尔海姆疑惑。

格林和卓格夫队的队员们一样，都祝福自己跟特蕾希雅的婚姻，也明白他们都很希望尽快回王都。

「真不像你耶。安全第一和以性命为优先不是你的信条吗。再怎么说，这种状况下就算焦急……」

「──！」

想要安慰心急的战友而讲些自己都不习惯说出口的话，但格林却回头看自己。虽然脸溶于黑暗中看不见，但视线里有近似愤怒的感情。

八成是在说：『你怎么事不关己的样子？』吧。

这样下去会赶不上婚礼。明知如此，威尔海姆不但没有动摇，甚至没有做出任何焦躁的举动。当然，焦急是一定有的，但也仅此而已。

毕竟，木已成舟。

「就算赶不上婚礼，我们也已经确认彼此的心意了，这才是最重要的。只要没被拆散，我就没道理要乱了手脚。」

「────」

「而且，我可没打算毁约。娶她当我的老婆，还有一定会回去。我答应她两个都会做到。要是毁约，我就再也吃不到她煮的饭了。」

威尔海姆堂堂正正地朝感到悲壮的格林这么说。感觉带著幽默的发言让格林愣了一下。

接著立刻是格林的长声叹息──很像他会有的反应。

「────」

「不要露出那种眼神。就算看不见，就算没法写字，我大致上也知道你在想啥。而且闲聊瞎扯会浪费时间，对吧？」

严肃消失，格林的视线只剩下温和。挥别他的视线，威尔海姆继续探索洞窟。他的话八成让格林耸肩，重新──正准备要探索时，黑暗中响起虚弱的人声。

「……啊。」呻吟声是从格林那儿发出来的。是他背著的男童。原本一直昏睡的他扭动身子，慢慢地醒转过来。

「呃。呜……咦？」

「……醒来啦。算我拜托你，不要吵闹喔。」

清醒的声音透著内心的混乱。威尔海姆沉著冷静地跟醒过来的男童这么说。答应之后男童下到地面，在黑暗中边找他们边说：

「这、这里是……叔叔你们是？」

「叔叔啊……我们是王都的人，来找你的。这里是山里的洞窟，你跟其他小孩下落不明，所以村里的人都在找你们。到这边跟得上吗？」

「啊，我们掉进『土蛇巢穴』……那这个洞窟就是……」

威尔海姆的说明，让男童知道置身的黑暗真面目为何，并感到万分胆怯。

「你先冷静。这里确实是叫『土蛇巢穴』的洞窟。因为入口坍塌，所以我们正在找其他出口。……你们为什么会来这里？」

「……大人叫我们不准进来。」

「我想也是。因为我们要入山前也被叮咛过。」

「不过，最近村子里地震了好几次……我以前曾听爷爷说过，地震是住在山里的土蛇大人引发的。所以……」

威尔海姆察觉了声调压低的少年话中的真意。

「是要来杀土蛇吗。真勇敢。」

「才、才不是！我们是想说来供奉土蛇大人，请祂别再引发地震！」

威尔海姆做出的结论让男童慌张地大声起来，接著从自己的怀中摸索一下，然后把手中的东西扔向地面──顿时亮起白色光芒。

几个小时没见过光芒，强光令威尔海姆和格林呻吟。

「……原来你有带拉格麦特矿石啊。」

「因为要进洞窟，所以当然有啰。叔叔你们为什么没带啊？」

「────」

被孩童针砭准备不充分，威尔海姆和格林苦著脸面面相觑。但是多亏了男童，现在有了光源，这样一来探索应该会有很大的进展。

威尔海姆一伸出手，男童就不情不愿地将手中的矿石交了出去。威尔海姆边确认在手中发光的矿石触感边说：

「我了解你和其他小孩的决心，但是你们能力不足。下次要注意不要给其他人添麻烦，还有就是要提升自己的体能练习挥剑。」

「哦，嗯……知道了。对不起。」

被给予有点偏离目标的建议后，男童垂下头。之后仰赖光和风，找到风吹进来的洞口的话应该就能出去了。

虽然很怕到了外头得面对过了多少时间的事实──

「那个等到出去后再担心。不过我对于被土蛇这种迷信给摆弄感到很不服气。」

孩子们的行动出发点是为了村子好，就算一直怪罪他们也无济于事。要更积极、更有建设性的──不过威尔海姆的自言自语让男童睁大眼珠。

「哪里迷信了？土蛇大人是真的存在哟？」

「────」

男童愣愣地这么说，对此威尔海姆眯起眼睛。紧接著，身旁的格林摸著自己的后颈，用力敲响钢板。

金属声尖锐无比，这个信号是「提高警戒到顶点」。

格林洞察危机的能力甚至远远超过威尔海姆，因此他的反应代表有最大等级的危机降临，这点毋庸置疑。

「混帐，是什么──」

过来了？还没说完，「那个」就来了。

威尔海姆拔剑，把光源朝洞窟深处高举。顿时，有道黑影掠过矿石绽放的白光，用力蠕动并猛然摇动洞窟直逼而来。

「────！」

占据整个洞窟通道的庞大质量，是身躯远大于威尔海姆他们数倍的存在，一瞬间从有所戒备的三人身上夺走了现实感。

下一秒，扭动庞大身躯的影子便使出强烈一击──

「──啊！？」

毫不留情撞过来的破坏力，使得洞窟再度坍塌。

11

──被称作「土蛇」的玩意，就像身长超越十米的巨大蚯蚓。

为了适应洞窟里的生活，因此眼睛已经退化，蠕动的身躯也没有手脚。不过黑压压的额头上却长著扭曲的角，让人一眼就能看出它的丑恶出身。

头部长角的生物，就足以证明它是人类的公敌魔兽无误。

魔兽的行动准则，就是杀害一切的生命体──亦即对闯入自己狩猎场的这三人，魔兽最优先做的事就是施加毫无保留的破坏力。

「──唔！！」

往下敲的尾巴，格林立刻举盾挡住。

身为盾士的他，巧妙化解敌方攻击的技术出类拔萃。对手是魔兽，有著庞大差距的体重，即便如此他依旧勉强承受，并完全泄掉敌人的第一击。

「────」

全神贯注在盾牌上，将冲击力道往自己身边带。准头被带掉的攻击用力撞上坚硬岩壁，剧烈的摇晃撼动整条洞窟。

「喀、呼──！」

通道上的冲击摇晃脑袋，格林的嘴巴流出鲜血。虽然把攻击卸除，却没法完全抵销威力。他双手疼痛，两腿发软，没法再承受第二击。

但就算如此，还是制造出了剎那间的空隙。

「剑鬼」会活用那瞬间，格林比任何人都信赖他。因此──

「──干得好。」

用简短一声给予最大等级的称赞，银光在黑暗中不住迸发。

使出的斩击尽情肆虐，刺向动作停下来的土蛇身体。土蛇的表皮极富弹性，光滑的身躯也有强烈对抗爪子和刀刃的耐力。

可是，「剑鬼」的斩击在第一下被防住后，剑光就开始改变。剑击的角度、威力随著每一斩提升精准度，终于突破防护贯穿肉体──

「吼嘎嘎啊啊啊──！！」

魔兽咆啸，身上喷满血花的威尔海姆持续挥剑。

被他的剑击和强大气魄给镇压，魔兽的躯体边洒落鲜血边一口气往后退，发出在地面攀爬的声音，拉大跟威尔海姆之间的距离。

「格林，站起来！这边不适合战斗！要移动了！」

撑起跪地的格林的肩膀，把整个傻住的男童夹在腋下。虽然这两人都处在无法快速移动的状态，但在这里交战对己方太过不利。只好仰赖拉格麦特矿石的光芒，朝著洞窟深处再次移动。

但是在逃跑途中威尔海姆察觉：蜿蜒曲折的洞窟不是自然形成，而是由土蛇的身体走出来的通道。

「既然如此……！」

最恶劣的情况下，就是不管跑到哪里洞窟的宽度都不会变。要与土蛇一战，就非得需要能够跨越它巨大身躯的空间。

「照这样看来，一直逃只会让状况变得更差……」

战斗本能弹出来的答案，让威尔海姆当场停下脚步。把抱著的男童塞给格林，架起剑面向背后。

无声的格林抱好男童后，威尔海姆吼道：

「在这里我跟你都没法发挥本领！一起活下来是最好的！趁我应付这家伙的时候往更里头去！」

朝著想要留下来的格林大骂，用剑将手中的拉格麦特矿石剖成两半。即便变成两块，矿石的特性也不会消失。

将光芒变小的一半扔向格林后，威尔海姆把剩下的光源含在嘴巴上。

「好咧，快走──！」

格林手握光源，抱著男童往洞窟深处跑。远去的脚步声被逐渐从前方逼近、巨大身躯摩擦地面的声响给盖过。

衔在嘴巴的矿石白光，照出没有眼睛的怪物正张开血盆大口准备突击──

「呼唔唔唔啊啊啊──！」

鼓足劲，配合突击朝魔兽头部使出突刺。剑尖一瞬间被魔兽的体表给弹开，但迸发的剑气立刻修正目标，穿破肌肤让剑身戮进。

昏暗中看不清魔兽的体液颜色，但身体有一半被淋到的威尔海姆放声吠吼。不过，先发制人的突刺进度也只到此。魔兽的突击威力无法完全闪避，剑鬼的身体直接撞上庞大躯体，然后朝后方远远飞出去。

「咳哈！」

背部撞上岩壁，屏息的威尔海姆立刻朝旁边纵身一跃。紧接著魔兽就朝威尔海姆方才撞到的地方追击，墙壁被挖掉一大块。冲击力道导致牙齿咬住的矿石掉落。仔细一看，光芒就在扭动脖子的魔兽眼前。

「────」

回收光源──不，霎时做出了其他判断。

踏步，用剑尖挑起发光矿石，朝著腾空光源施以突刺。剑尖带著矿石，刀刃再度深深戳进魔兽的伤口。没有发声器官的魔兽剧烈扭动，在狭窄的洞窟通道里掀起冲击波和强风。

威尔海姆也在冲击下撞到墙壁好几次。额头破皮，裂开的嘴角流淌鲜血。但是目的达成了。

「这样一来，你的位置就一清二楚了。」

伤口被埋入拉格麦特矿石，导致魔兽头部发出白光。这样一来，在这个洞窟里，不管它躲在哪都绝对不会被看漏。

没有视觉的土蛇对此毫无所觉，又像平常狩猎时那样潜入黑暗，想从死角瞄准猎物进行狙击。但是──

「都看光光了，蠢货。」

难以相信那么庞大的身躯攻击时竟然毫无声响，不过威尔海姆在千钧一发之际闪过。纵使可以看穿它的攻击，但通道窄到难以回避。只能在接近到极限，在间不容发的时候闪过，然后重复这样的举动。

不时使出像是擦身而过的斩击，但都不构成致命伤。不管是要歼灭还是要击退，地形的限制使得自己无法灵活出招。至少──

「──！？格林吗！」

在战斗期间，突然从洞窟深处传来连续高亢声响。听起来像是自暴自弃乱敲一通，但那确实传达出明确的指令给威尔海姆。

「紧急集合」──不管在哪都要立刻集合的信号。

「────」

威尔海姆顺从钢板的指令，立刻赶往洞窟深处。

魔兽欢喜地追著奔驰的他，却没想到自己头部的光芒照亮了通道，因此其实它反而是在帮忙自己逃跑。

穿过蜿蜒的道路，跳过裂开的地面，不久终于看到黑暗通道的尽头──

「──格林！」

尽头处有光芒，站在那儿的格林张开双手在等自己。呼唤他的名字后，剎那间有疑问窜过脑袋。

寄托给他的男童不在。洞窟的尽头，格林叫自己过来的理由，以及眼神充满信赖的理由──

「────」

专心跑向格林，然后与他同时朝旁边跳。身后追著威尔海姆、直线前进的魔兽反应不及，一头撞上岩壁。

轰然巨响穿过洞窟，飞沙走石袭向跳开的两人，但是接著又发生超越刚刚的冲击。是承受撞击的墙壁崩塌所引起的。

坍塌再度发生，土石流进狭窄洞窟。可是最大的变化不是这个。崩塌的天花板，碎裂的岩壁，以及从后头照进来的刺眼光芒──

「──卓格夫队，总攻击！！」

像怒吼一样发出号令，下一秒武器就不断迎头痛击。真的是毫不留情地蹂躏撞穿洞窟墙壁、伸到外头去的土蛇头部──

「战斗结束。──确认队长和副队长平安无事！」

踩著在瞬间被撕开的魔兽尸首，往洞窟里头看的康吾德正盯著被土石埋住的威尔海姆和格林。

「──太慢啦。」

腰部以下都被埋没的威尔海姆，光是要这样说就已经竭尽全力。

12

──婚礼预计在火之刻准点开始。

约定的时间即将到来，会场已经被参加者坐满。来宾全都期待美丽「剑圣」的婚礼，王国政要也大多都有出席。

「我明明说过很多次，办个只有亲人参加的小婚礼就行了……」

「那肯定很难办到。因为全国都在关注特蕾希雅大人的婚礼。而且我也认为那样是理所当然的。」

听说了会场的盛况后，特蕾希雅这么喃喃自语，卡萝则是气势熊熊地这么说。

身为伴娘，卡萝也穿上华丽礼服打扮得宜。凛然样貌牵引出她的美丽魅力，但当事人却毫不在意。

对现在的她来说，最重要的就只有眼前的特蕾希雅。

「特蕾希雅大人，您真的很漂亮。让我很想掳走您逃跑。」

「如果是你的话那被掳走也不赖喔……不过这样一来，就得和追上来的威尔海姆决斗了。不要为了我打架！」

「现在的特蕾希雅大人，确实有挥剑抢夺的价值。」

卡萝带著玩笑的称赞，让特蕾希雅掩嘴笑。

面对身著白色新娘服的特蕾希雅，就算用尽赞美的话语都不够。现在的特蕾希雅就是楚楚动人又美丽到这种地步。就连同性别的卡萝视线也离不开她，还错以为自己口干舌燥。

艳丽的红色长发盘起，只是施以淡妆就大幅改变平常的印象。如果持剑的她是威风凛凛的英雄，那盈满爱意的她就是花之妖精。

帮忙穿衣和化妆的自己万分自豪。卡萝沉浸在这样的感慨里。

再来就只剩下让那个粗鲁的男人娶走美艳动人的特蕾希雅──光想就火大。

「不如真的掳人逃跑……」

「卡、卡萝？你没事吧？你刚刚的话好像有点认真……」

「请不用担心。是开玩笑的。……目前是。」

卡萝别开视线，在特蕾希雅的楚楚可怜视线下努力律己。而卡萝的苦恼，被粗暴打开休息室的门的声响盖过。

「特、特蕾希雅！威尔海姆还没回来吗？不快点的话典礼就要开始了！来宾里头有人长得很像国王陛下……。我是认为不是陛下，不对，比起那个，新娘礼服很适合你……呜喔喔喔喔！」

「父亲您很烦耶……」

慌慌张张进入休息室的是失去冷静的贝尔托。他忙不迭地轮流看向会场和休息室，连珠炮地吐出不固定的话题，最后又因为特蕾希雅的新娘样貌而痛哭流涕。

他这样子令特蕾希雅皱眉，不过看著父亲的眼神没有怒意，应该说只有十分沉稳和温柔的神色。

就如陷入混乱的贝尔托所说的，出去巡察的卓格夫队还没回来。已经超出预定时间半天以上却还迟迟未归，代表路上发生了问题。

其实那问题应该还包含了贝尔托的阴谋策划在内，所以他这样慌了手脚反而很不合常理。但──

「看吧。我就说了，不要多事，老老实实地等待女儿出嫁就行了。」

接在号泣的贝尔托后面现身的，是身穿礼服的媞舒雅。身为新娘母亲的她，眯起眼睛看著坐在椅子上穿著嫁裳的女儿。

一瞬间，有强烈情感掠过平常始终保持冷静的媞舒雅的双眸。那感情，卡萝看不出属于喜怒哀乐哪一种。但是──

「──很漂亮哟，特蕾希雅。提姆兹他们一定也会很高兴的。」

「是的。谢谢您，母亲。……还有也谢谢两位兄长和卡吉雷斯。还有父亲。」

面对母亲的称赞，特蕾希雅漾出唯美笑容，点头以对。感觉像顺便被加在感谢行列的贝尔托，也因为这句话而拿手帕擦拭溢出的泪水。

「对啊……你的哥哥们也在祝福你哟，特蕾希雅。」

「虽然父亲是想要说好话，但我还没原谅您喔。」

「咦咦咦咦！？典礼都要开始了耶！？现在有比这个更重要的问题吧！」

「也不想想是谁制造出这个问题的……」

「特蕾希雅大人，太激动的话头发和妆都会乱掉。贝尔托大人也是，请不要触怒特蕾希雅大人。请搞清楚状况。」

「怎么连卡萝都讲这种话！」

严厉叮咛没有好好反省的贝尔托后，卡萝接著观察特蕾希雅的样子。毕竟威尔海姆他们还没回来是事实。

假如他们没回来，那么婚礼将成为盛大闹剧，害得大批人颜面扫地。

「没事的。就算万一发生那种事……我也已经不需要任何人的许可。」

「特蕾希雅大人？」

「这跟父亲的阴谋无关。假如赶不上结婚典礼，大不了我跟威尔海姆一块到远方去结婚。我老早就是他的人了，他也是我的人。这点绝对不会变。所以我可以正大光明地面对大家。」

对王国来说，这是「剑圣」与一名骑士的婚礼。但是对当事人特蕾希雅而言，这只是一男一女的结合仪式──无人可以介入。

很感谢参加的来宾，也很高兴被大家祝福。

但就算如此──

「都没有威尔海姆回来的那一天让我开心。」

特蕾希雅的灿烂微笑，让卡萝忘了呼吸。这点贝尔托和媞舒雅也不例外。新娘的极品笑容，让他们都理解了。

特蕾希雅和威尔海姆早已结为连理。早在很久以前的那片花田里。

然后──

「──总觉得外面闹哄哄的。」

被什么吸引了注意力的媞舒雅转头看向休息室的门。接著门被敲响，一个大个子低头露脸。

是波尔德。充满肌肉的身体硬是塞进礼服里，看起来很不舒服的样子。

他向室内的每个人投以笑容，用力点头道：

「抱歉让各位等得不耐烦。他们终于回来了。」

没错，几乎是在典礼要开始的时候，传来了新郎回到王都的消息。

13

会场大门开启之前，特蕾希雅觉得自己的心脏快要跳出来了。

尽管在休息室等待关键时刻时可以保持平静，但真的到了进场时刻，沉著就立刻消失。从这部分来看，忍不住要笑自己也是个软弱的人类。

原因一定是出自在这扇门后方等待自己的新郎。只有他，能让特蕾希雅变成平凡的女人，而不是「剑圣」或是剑士。

「虽然他本人没这样的自觉吧。」

「特蕾希雅，时间到了。」

微笑著低语时，身旁的贝尔托静静地伸出手臂。

婚礼的经典桥段，就是新娘与父亲相偕一同进入会场。拖著新娘礼服的长裙襬，特蕾希雅伸手绕住贝尔托那只手。

因紧张而僵硬的温暖手臂，让特蕾希雅小声吐气。

「父亲，对不起至今给您添了很多麻烦。我会幸福的。」

「……唔。要是在这边哭了，阿斯特雷亚家会颜面尽失的。」

「所以我才要说呀。」

「你这孩子，真的是从小就最让人费心。」

这话简直像在报复，特蕾希雅憋住涌上的心情然后微笑。见状，贝尔托颔首，以父亲之手推开通往会场的门。

伴随光芒在眼前扩展开来的，是经过隆重装饰的王都圣堂。

特蕾希雅所走的花径，就如字面意思是由大量鲜花──而且还是由特蕾希雅和威尔海姆的邂逅处，用那片花田的无数黄色花朵来铺设的。

唯有知道两人幽会一事的人才能办到。恐怕是卡萝的杰作。察觉这让人感动的细节后，特蕾希雅抬头，凝视并排站在花径两旁的来宾。然后因为异样的光景而眨眼。

「────」

在衣冠楚楚、打扮奢华的来宾们旁边，还有堂堂正正入席的他们。

卓格夫全队都被泥土灰尘和汗水弄脏，甚至还穿著铠甲跟斗篷。破破烂烂的装扮外加睡眠不足的表情，但是全都出席，无一缺勤。

他们的样子绝不适合出席他人一生一次的结婚典礼。

事实上，是能以此为理由责备他们没礼貌，催促他们退场的。身旁的贝尔托很惊讶，斜瞄特蕾希雅以表达这点。

但是，特蕾希雅却只是一度闭上眼睛，深深感谢出席的他们。

「──谢谢。」

他们不成体统的样貌，却得到特蕾希雅的亲口道谢。

假如为了祝福这场婚礼，盛装打扮是一种体贴，那么为了赶上这场婚礼，不管多脏都还是赶过来了，这也是一种体贴。

而特蕾希雅明白几度共同奋战的他们的人品。被他们祝福，不管是身为「剑圣」还是女人，都是一份光荣之事。

接著踩上红色花径，接受来宾们的掌声和祝福，继续前进。拉著激动不已的贝尔托的手，苦笑都不知道谁才是新娘了。

通过卓格夫队面前，挺直背脊朝拍手的他们点头。他们所有人配合这动作整齐划一地敬礼。这一幕，深深地烙印在心底。

队伍边缘是并肩而立、正看著特蕾希雅的格林和卡萝。哪天立场交换的机会肯定很快就会来临。

届时自己会比任何人更祝福他们。特蕾希雅在心中用力发誓。

在两人身旁的波尔德，还有王国政要全都齐聚一堂。波尔德旁边是把帽兜往前拉到极限的人──连吉欧尼斯陛下都在，惊讶的同时忍不住苦笑。

对前来参加这场婚礼以及相关的人，全都献上由衷的感激。

然后──

「──威尔海姆。」

花径的终点，有一名青年站在祭坛上俯视特蕾希雅。

特蕾希雅呼唤他的名字，松开贝尔托的手。取而代之的，走下祭坛的青年牵起她的手，将新娘抱进自己怀里。

新娘从父亲手中被交给新郎。这一瞬间，这件事，让特蕾希雅闭上眼睛，大口吸进拥抱自己的青年的体味──

「──又是汗臭味。」

用这句话和笑容犒赏死命赶来的新郎。

14

在「土蛇巢穴」的攻防战，和婚礼当天的朝阳同时落幕。

「多亏了格林副队长的临机应变。洞窟深处确实有风吹进去，但是通道狭窄，大人过不去。不过却是孩童可以爬进去的宽度。他就让那孩子帮忙传话……」

「让队伍在外头埋伏，等魔兽撞穿山壁。真亏他知道我们会从那里出现。」

「队长看起来比想像中的还要拼，所以才整团出动来狩猎呢。」

以上，是救起被活埋一半的威尔海姆和格林的康吾德所说的话。

事情的始末就如他所说，靠著格林的机智和卓格夫队的总攻击歼灭了魔兽。不但确保了库拉姆林的安危，还找回、保护了孩子，在维持治安方面来说是莫大成功。

「再来就只剩下抱著操翻地龙的觉悟，把队长送回王都……婚礼会场。好啦，没空休息了。走吧！」

「虽说帮了大忙……不过你们为何要这么拼命？我跟特蕾希雅的婚礼对你们来说有那么重要吗？」

康吾德鬼气逼人的样子令威尔海姆忍不住道出疑问。

这话让跨在地龙身上的康吾德搔搔鼻头。

「说过很多遍了吧。不能让特蕾希雅大人孤零零地一个人站在会场上。那位大人……那位女性非得幸福不可。」

「────」

「队长……不，威尔海姆，你或许没有自觉。」

平常的随便语气消失，康吾德的侧面充满认真。身为老兵的他，言行恢复为对待过去的威尔海姆的样子，继续说了下去。

「不过呢，我们跟那女孩，和『剑圣』在内战中一块并肩作战了无数次。每次都被那把剑拯救，被她保护，也被给予勇气无数次。我们可以活到现在都是多亏了『剑圣』。这个可不是说谎或吹牛。」

手握操纵地龙的缰绳，康吾德直视前方。威尔海姆知道他的双眼掠过了对他自己的愤怒。

「那股强劲，『剑圣』的剑，压倒性的强大。所以说，在庆祝典礼那一天，看到你打败『剑圣』的时候，我很后悔。」

「后悔？」

「那女孩，『剑圣』其实就只是个女孩子。我们竟然都没察觉到这点。」

咬紧牙根的他一脸不快。威尔海姆斜瞄他，接著他又松弛紧绷的脸颊，无力苦笑。

「对你来说是天经地义的事，我们却一无所觉。压根儿没想过我们一直仰赖的强大代名词『剑圣』，其实也是有弱点的女孩子。」

「────」

「我们让一个女孩子持剑作战，这算什么骑士。算什么勇猛果敢的卓格夫队。所以说，你从她手中夺走剑这点，我们全都很感激。因为你让我们，让没资格自称骑士和男人的我们自觉到该做什么。」

康吾德就只说了这些，接著用双手用力拍自己的脸颊。干巴巴的声音响起，紧接著老鸟士兵就恢复成平常从容不迫的面容。

「这就是为什么要让队长给特蕾希雅大人幸福的原因。所以说要快上加快。就算连洗澡和换衣服的时间都没有。」

「为了别让她一个人，是吗。」

「正是如此。」

康吾德的笑容清爽不已，威尔海姆鼻子喷气，催促地龙加快速度。

就这样，卓格夫队一齐回到王都，还先略过报告直接赶赴会场──

「──又是汗臭味。」

见怀中的少女一脸不满，威尔海姆苦笑。

这次真的没法抗辩。因为巡察期间根本没时间睡觉和洗澡。不过原本是有预定婚礼前要从头洗到脚的，但最后还是来不及这么做。

再怎么说都有赶上婚礼，来宾里头也没人缺席。虽然没时间沐浴，但还是有脱下铠甲和护具换上新郎礼服。希望新娘能够满意。

只是，当然──

「我知道这样不好。」

「不会，没关系。这就是威尔海姆的气味，是你的一部分。」

「说汗臭味是我的风格，让我很想反驳耶。」

「又不是这种意思。笨蛋。」

相拥的两人交谈完，威尔海姆的视线转向前面的贝尔托。

八成就是硬塞巡察任务以及在路上安排一堆陷阱的人。一想到来到这里有多劳心劳力，就算抱怨个一句应该也不会遭天谴吧，但──

「贝尔托殿下。──您的女儿特蕾希雅，我接手了。」

威尔海姆的嘴唇没有吐出怨言。

说出必要的话，传达给必要的对象。闻言，贝尔托面颊僵硬，说：

「……要让她幸福喔。」

「我对天发誓。──只不过，幸福的程度会仅次于我。」

因为迎娶心爱少女的自己是最幸福的人，这点不能让步。

听到威尔海姆的宣言后，特蕾希雅红了脸，贝尔托则是瞪大双眼。不过新娘之父立刻行礼，站到身在观众席的妻子旁边。

就这样，留在花径上的就只剩下威尔海姆和特蕾希雅，婚礼的主角们。

威尔海姆虽然换上新郎装束，但也只有服装能看，整个人根本是蓬头垢面，绝对称不上是体面。

而另一方面，特蕾希雅身著以白色为基底的华丽新娘服，是这世上最美的新娘。

「对嫁裳的感想……等婚礼完再听你说。」

「老实说，我没自信可以说得出来。」

「假如说不出来，也可以用态度和行动来表示。」

「……那样子的话，可会变得非常不得了呢。」

「咦？」

早已习惯新娘对自身魅力一无所觉，新郎叹气。接著将她从胸膛解放，改用公主抱抱起来。

环抱住膝盖和腰部，抱著微微吃惊的她走上祭坛。心爱的少女纤细轻盈，不过却是这世上最值得宝贝的人儿。

「很丢脸耶，放我下来……！」

「不这样子让大家知道你是谁的人，我会不安。」

「那种事，从内战典礼那天开始就人尽皆知了！」

听了特蕾希雅红著脸说的话，威尔海姆却很狐疑。笨拙的藉口没有奏效。说到底，就只是威尔海姆想这么做而已。

只是想要炫耀这世界上最美丽动人的少女是自己的新娘罢了。

婚礼仪式开始进行。

新娘和新郎在祭坛上看著彼此，担任司仪的麦克罗托夫口述冗长的导言。一半的话都是左耳进右耳出的威尔海姆和特蕾希雅，互换彼此的爱与誓言──

「那么，虽然是第二次，但请在大家面前进行誓约之吻──」

麦克罗托夫故意加了一句俏皮话。威尔海姆朝特蕾希雅走近一步。

「威尔海姆，我爱你。」

「────」

「你呢？」

新娘带著戏弄的发问，让威尔海姆答不上话。

不过为了以态度和行为回应她的要求，便将嘴唇凑了过去。

那天的婚礼，就是后世咏唱的「剑鬼恋歌」的后日谈──

天气晴朗，正适合由闹哄哄又可爱的日子所谱出的「剑鬼恋谭」。

《完》

** 『剑鬼恋谭──聘可塔特的银华乱舞』

1

──带著强风的斩击低吟，「剑鬼」穿过生死缝隙，踢踹土壤。

视野角落是飞散的土块，「剑鬼」舞动身子使出剑击。朝对手的粗脖划过去的银光准确地瞄准要害，可是却被来自正下方的一击给弹开。

「────」

连咂嘴的时间都没有。

利用剑击被防御住的冲击，「剑鬼」顺势飞向空中。乍看之下逃向无处可逃的空中是愚蠢之举，但在这瞬间却是唯一活路──

「喳──！！」

转眼间，来自三方同时攻过来的刀刃毫不留情地削去肌肤，喷出血花。

但是却没有造成致命伤。加速运转的意志拋下痛楚，夹带血风的「剑鬼」在空中翻转身子，头下脚上朝眼底的大块头使出上劈。

剑尖入侵蓝黑色肩膀。太浅了，还不够砍掉一只手。咬紧牙根后，紧接著就被一记回礼侵袭。

「嘎──！」

有孩童头颅大小的巨大拳头，陷进硬是扭转的侧腹里。这一击的威力让肋骨哀号，身体直接朝旁边飞了出去。

用力撞击石墙，受身还不充分的情况下就掉落地面。额头被石板地割破，用舌头舔取流淌的热血后抬起头。对方没有追击，代表并非毫发无伤。

「────」

单膝跪地的「剑鬼」面前，是庞大到要仰望、傲然而立的身躯。巨大身躯凝视自己的手──殴打「剑鬼」结果手腕被砍断的左手。粗壮的手腕喷发血液，硕大的拳头掉在他脚边。

一望就知道是重伤。虽说「剑鬼」的伤也不算轻，但是跟失去手的对手相比就知道是谁占了优势。

──假如对方没有剩下三只左手的话。

「好久没有被敌人痛击了……这是难得的幸运。」

裸著蓝色上半身的巨汉深沉地说完，失去手的手腕膨胀，顿时伤口就停止出血。这是利用异于常轨的肌肉来收缩血管强行止血。这不是可不可能的问题，而是眼见为凭。

「……你是怪物吗？」

「别讲那么寂寞的话，劲敌。不管是吾还是汝，都要感谢这段缘份。」

「呸！……哼。那是想要抢走别人的女人的正当理由吗？还真好听。」

「打倒汝这样的强手，强抢美娇娘当奖励很正常。没什么好奇怪的。」

「简直是蛮族的道理。」

「是为剑而活的野兽真理。」

剑鬼吐出血块，巨汉──拥有八只手的斗神狰狞一笑。其威容释放出压倒性的霸气，不过「剑鬼」也毫不畏惧，与之相对峙。

那当然。可没有撤退的选项。为什么呢──

「────」

后方的石砌大桥入口处，有视线直刺自己背部。

这场超越人类认知的决斗，有大批的观众在看。背对的视线数量多到不用数，用肌肤就能感受到无数的感情漩涡。

但是，对「剑鬼」来说最重要的就只有一个。只要能够强烈感受到那一个就行。

「────」

反映出万里晴空的双眸，宛如烈焰的美丽长发迎风飘扬，专心一志又毫不怀疑，相信「剑鬼」一定获胜的视线。

只要那双眼还看著自己，「剑鬼」就不会输给任何人。

因此──

「随你高兴怎么说。反正会是我赢。──『八腕』库尔刚。」

「那吾就让美娇娘怀上吾的种，小孩就用汝的名字吧。──『剑鬼』威尔海姆。」

粗大健壮的七只手，架起刀身宽厚的大刀「鬼庖丁」。

全身剑气膨发，连「剑圣」也为之退让的高纯度剑技再度上身。

无止尽的狂乱，剧烈激情的斗气漩涡，「剑鬼」与「八腕」的一对一对决──

──史上赫赫有名的激战、死斗、性命交搏的「聘可塔特的银华乱舞」。

谱出这场战斗的开始和结局的，是一对年轻男女在「剑鬼恋谭」的其中一幕──

2

「──父亲是笨蛋！我不理您了！」

大清早就有美声响彻宅邸，在庭院树上歇息的小鸟们一齐振翅飞去。

受惊的拍翅声远去，世界又恢复片刻宁静。可是时间仅冻结了一瞬，融化时采取慌张行动的是个瘦长蓄胡的男性。

失去沉著的男性，用跟他外表不符的动作挥手道：

「等、等一下，特蕾希雅。要生气不嫌太早了吗？你先冷静一下子，慢慢考虑我的提议也不迟……」

「是父亲的想法太贸然又反常了吧！为什么这么重要的事连商量都没有就擅自决定！？我有说错吗！？」

「当然是因为我想给宝贝女儿一个惊喜啊。」

「哦～吓到我了。我吓了好大一跳。往很糟糕的方向！到了想要断绝父女关系！」

「咦！？为什么！？我这么为你著想耶！？」

男性反过来被吓到，跟他吵架的少女则是累到大声叹气。

有著美丽红发和蓝色双眼的漂亮少女，虽然无意打扮，但白色便服就已衬托出她的女性魅力。她双手环胸，像在强调意外丰满的胸部。

少女名为特蕾希雅•范•阿斯特雷亚──是这间宅邸的主人，也是眼前的贝尔托•阿斯特雷亚的亲生女儿。也就是说，这是父女吵架。

而这对父女吵架的光景其实并不罕见，不如说发生得相当频繁。而且只要是贝尔托去找特蕾希雅的话就几乎肯定会发生。

这次的情况是──

「是说，父亲您一个月来这里几次了！将近半个月都有跑来吧！您明白现在对我来说是什么时期吗！？新婚蜜月期耶！？」

「我当然知道！正因如此，为了避免两个年轻人擦枪走火，所以才要来盯紧你们踩煞车。这不叫为女儿著想要叫什么？」

「父亲您干脆去给地龙踹到受重伤好了！」

「什么！？那句是卡拉拉基的惯用语吧！？」

坐在沙发上望著父女吵架的威尔海姆叹息。这时，面前突然递出一个茶杯。看过去，端茶给自己的是有著亚麻色头发的高尚女性。见到她，威尔海姆也忍不住端正坐姿。

「抱歉每次都来叨扰喔，威尔海姆。我家那口子和女儿很爱吵。」

「还好啦……不，我已经习惯了。父亲大人的心情我也不是不懂。会担心女儿很正常……难免的。」

「用不著那么客气喔？我跟你已经是家人了。要是做爸爸的能够老实承认这点就好了呢。」

威尔海姆努力让谈吐有礼貌，女性则是对他这么说，露出微笑。从她的微笑里可以瞥见对威尔海姆来说最具魅力的女人的面容。

这是当然，因为这位女性正是特蕾希雅的亲生母亲媞舒雅•阿斯特雷亚。

早晨的阿斯特雷亚家──威尔海姆和特蕾希雅这对新婚夫妻所组成的家庭，目前正在接待妻子的父母贝尔托和媞舒雅。

而就如妻子的抱怨一样，接待他们几乎已经是惯例了。

「早安。……请问，今天早上是因为什么原因吵架？」

当休息室的争执还在持续，有其他人伴随著招呼语进来。面容反映出当事人正经八百的性格，闪耀的金发剪得和肩膀齐平，是看起来十分正派的女性。

是特蕾希雅的随从，跟威尔海姆也有交情的卡萝•雷玫迪斯。

她的家族世世代代侍奉阿斯特雷亚家，而她本人也已经很习惯主子父女吵架。这从她无视争执的两人，而是直接问媞舒雅就能窥知一二。

「早安，卡萝。是呢，好问题。顺便问一下，你觉得是为了什么呢？」

「大概是来访得太频繁，特蕾希雅大人终于受不了爆发了。」

「唉呀呀呀，正确答案。唉呀，毕竟他做事都一面倒，所以很好猜。」

「是……这样啊。」

见媞舒雅微笑肯定，卡萝面露遗憾。似乎是试著找出主子的亲生父亲贝尔托有什么优点但却找不出来，所以很灰心。因为那样而灰心未免太失礼了，只是威尔海姆没有说。

就这样，三人为了贝尔托的事，以叹息来代替晨间的招呼，而察觉到这边的特蕾希雅双眼发光，高声大喊。

「卡萝！你听我说！父亲又擅自作主让我伤脑筋啦！而且还不觉得自己有错……啊，早安。」

「早安，特蕾希雅大人。那个，特蕾希雅大人的心情我强烈地有共鸣，但是请不要太责备令尊，不然他很可怜。」

「就是说啊，特蕾希雅。你也稍微学学卡萝对我的尊敬。」

「呵呵，这个人啊，明明被同情了却丝毫没察觉……所以才可爱。」

特蕾希雅和卡萝的对话让贝尔托骄傲地挺起胸膛，就只有妻子是陶醉地看著他。眼前这光景让威尔海姆扶额。

奇妙的家庭关系。虽说自己现在也是个中的一份子，但在记忆中，自己在老家跟双亲和两个哥哥都没有这么令人疲累的关系。

这样看来，自己当年离家出走的原因实在很匪夷所思。

「觉得哥哥讲的话让我很火大这点，是毋庸置疑的。但……」

「是说，威尔海姆！你也说说父亲啊！他这样子很奇怪吧？不念念他不行……不念父亲就不知道！」

「那种事，就算我来讲也没什么意义吧？」

「假如你站在我这边帮忙，我会很高兴的！这样可以吧？」

陷进沉思时，特蕾希雅就来讨救兵。最后加的那一句话具备了多大的力量，这名少女根本没有自觉。

本能地了解对方的致命伤，该说不愧是前「剑圣」吗？

「──？干嘛贼兮兮地笑。好了啦，这边这边。帮忙我。」

「好，知道了。所以，今天早上是在吵什么？」

苦笑回应特蕾希雅的招手，询问不得要领的争执起因。

长达半个月叨扰新婚家庭，问题似乎并非这么单纯。

显然又是贝尔托提出什么无理难题──面对丈夫的问话，特蕾希雅面红耳赤。

「父亲啦，说我们蜜月旅行的时候也要跟去！很难以置信对吧？威尔海姆也帮忙我念他一顿！」

──原来如此。

真的是不识趣到极点了。威尔海姆仰头看向天花板。

3

「所以说，父亲。请您仔细说明。您的说法会决定我们的态度。」

「哈哈哈，那种说法还真是不得了的威胁呢，特蕾希雅。你这个想测试爸爸的孩子真叫人没辙。这样子更不能让你离开视线……」

「在您讲到主题之前，我对父亲的好感可是越来越低喔。」

「咦咦咦！？为什么！？我什么都还没说耶！？」

特蕾希雅的眼神犀利，贝尔托在心底仰天长嚎。干嘛那么惊讶？威尔海姆不解皱眉，但另外三名女性似乎都习惯了而一脸没事样。

不管怎样，继续下去的话只是重复原先的争执。尽管提不起劲，但无奈的威尔海姆介入两人之间说：

「冷静点，特蕾希雅。先听听父亲大人怎么说。父亲大人也请别再不小心刺激到特蕾希雅。这家伙很容易激动。」

「唔……好～知道了。既然威尔海姆这么说，那我听话。」

虽然噘著嘴不服气，但特蕾希雅还是勉强收起唇枪舌剑。看向为此而安心的贝尔托，他摸摸自己的胡须，嘴角下垂。

「威尔海姆你那什么态度，简直像是自己比较了解特蕾希雅。先声明，我可是跟特蕾希雅一起洗过澡的喔。」

「那都多久之前的事了！跟女婿争什么争啊，父亲！！」

「抱歉，我也有。」

「咕呃啊！」

「慢著！威尔海姆！？」

贝尔托跪地，羞红脸的特蕾希雅抓著威尔海姆的衣领把他推到房间角落，然后将他按在墙壁上，在羞耻、著急和爱情下泪眼婆娑地倾诉。

「你、你、你、你讲那什么话啦！我、我们根本就还没一起洗过澡吧！」

「抱歉。忍不住就跟他杠上了。」

「不要跟父亲较劲！跟父亲用同一个水准吵架的威尔海姆，我完全不想看到！」

她把自己的父亲讲得很过份，不过威尔海姆也持相同意见。

拥有共同敌人可以加深夫妻之间的羁绊，回到沙发前先张开双手轻搂一下特蕾希雅。接著两人就要往沙发上坐下去的时候──

「……卡萝，你为什么坐那边？」

不知为何，特蕾希雅和威尔海姆的对面本来只有贝尔托，但卡萝现在也加入坐在旁边。明明直到刚刚她都还随侍在特蕾希雅的后方。从她站的位置应该就表态了她支持谁。

面对特蕾希雅的问题，卡萝一脸认真地摇头。

「那个男的不讲道理，滥用夫妇之间的关系对特蕾希雅大人做了那种寡廉鲜耻的行为……」

「慢著！我、我可是已经和威尔海姆结婚啰？」

「是的。但是这并不代表他可以滥用丈夫的权利和特蕾希雅大人一块泡澡。」

「都是夫妻了耶！？」

卡萝用像在瞪弒亲仇人的眼神敌视威尔海姆。「就是说啊。」贝尔托也跟著起哄，两人缔结的守备关系看来十分稳固。

看样子对面也因为有共同敌人而强化了羁绊。真是给人找麻烦。

「万分抱歉，特蕾希雅大人。我也有说什么都不能退让的底线。为此就算不情愿，也还是跟贝尔托大人合作了。」

「就是说啊……咦！？不情愿！？」

「连、连卡萝都讲这种话，怎么办……」

「不管你们七嘴八舌什么，我都会跟特蕾希雅一起洗澡喔。」

「你这家伙──！」

真的生气了的卡萝飞扑过来，威尔海姆轻松闪过。斜瞄一眼实力差距显而易见的两人，满脸伤脑筋的特蕾希雅向旁观的媞舒雅寻求协助。

「母亲──……」

「唉呀呀呀，都嫁人了怎么还一脸可怜样。不过，确实有点令人同情呢。……亲爱的？」

「噫！我可没错哟！？」

抱头惨叫的贝尔托说出做坏事的人很常说的话。对此默默眯起眼睛的母亲，发抖的父亲，对特蕾希雅来说是司空见惯的样子。

而司空见惯的光景就顺著往常的走向，到达熟悉的结果。

「跟、跟去蜜月旅行，我也觉得太过头了……所以说，就算特蕾希雅不必那么生气，我也不会跟……」

「他这么说呢。虽然是个小心眼又不懂得看气氛的人，但不是坏人，顶多是个小恶棍中的小人物，成不了气候的。你们担心的事不会发生的。」

「母亲，稍微放点水吧……」

「要是放水让他尝到甜头，就对不起你跟威尔海姆了。所以说要欺负就要欺负得彻底。啊啊，好难受……」

表情看来艳丽无比的媞舒雅不断痛斥越是责备就缩得越小的贝尔托。每次特蕾希雅都会松一口气抚摸胸膛，同时又同情父亲那副模样。

蜜月旅行带父亲作陪，就算是想尽孝的特蕾希雅也无法接受。当然，以随从身份一块去的卡萝是另当别论。

「所以说，你们两个也好停止打闹了。」

「我根本没认真，是这个女的一直在烦。」

「唔！为什么我的力量不足……剑神啊，若是能听到我的请求，请现在就赐予我打倒这家伙的力量……！」

「在这里！？不要许那么恶质的愿望！住手啦，卡萝！」

抱住咬紧牙根悔恨的卡萝，特蕾希雅温柔地抚摸她的头。情深义重的随从感受到主子的心情，痛心疾首地收敛怒意。

「威尔海姆也是，不准再挑衅了。下一次就由我当你的对手。」

「……那样我没胜算的，还是算了。」

面对鼓著腮帮子抗议的特蕾希雅，威尔海姆早早举白旗投降。这下子终于为一大早就开始的蜜月旅行争执划下句点。

虽然觉得要是一开始贝尔托别无理取闹的话就没事了。

「不管怎样，这是第一次旅行。跟住在同一个屋檐下不同，是你们夫妻用另一种型态相处的机会。过程可别马虎敷衍，或是伤了特蕾希雅，知道吗？」

「知道。……领教了。」

「特蕾希雅，要是不开心随时都可以回家来……痛痛痛痛！」

「哦呵呵呵。那么，特蕾希雅，威尔海姆。好好享受蜜月旅行喔。」

贝尔托又要多话，媞舒雅拉扯丈夫的耳朵将他带离会客室。一个月就有半个月跑来新婚夫妻的住处闹，但又绝对不过夜，这方面勉强可以感受到贝尔托的良心。

「希望不是我想太多就好……」

「就别想太多。是说卡萝你怎么会来？今天休假吧？」

特蕾希雅问道，卡萝微微屏息。身为特蕾希雅的随从，其实她不太有「休假」这种概念。因此主子所说的「休假」对她来说，指的是可以与之共度安稳时光的对象的假期。

「今天队上放假。格林那家伙应该也窝在兵营。快去。」

「用、用不著你说！一开始我就打算这么做！」

「好好好，辛苦你了。快去快去，时间宝贵。今天是旅行前的最后休假，要连我们的份都一起陪他，快乐地过喔。」

「明、明白了……既然特蕾希雅大人说到这种地步的话。」

特蕾希雅微笑著送有点意气用事但其实很少女心的卡萝离开。直到最后卡萝都还想说什么，不过最终认知到对同样在恋爱的少女特蕾希雅讲什么都没有用，她才无精打采地离开。

「好像跟格林约好在商业街碰面。最近的卡萝万分可爱，有时候我都要吃格林的醋了。」

「因为那两个家伙个性都很麻烦。快点凑做堆不就得了。」

「那样的话，比起我和威尔海姆，她就会以格林为优先啰？那样子我会有点寂寞……」

威尔海姆咂嘴给的意见，让特蕾希雅浅浅一笑梳理自己的头发。

她当然懂威尔海姆的意见，只是那两人的关系有点复杂。卡萝出生的雷玫迪斯家虽然没有阿斯特雷亚家那么高贵，但也是王国贵族。身为该家族的长女卡萝，想和平民出身的格林结合并不是那么简单的事。

就算他们心意相通，但家世和血统却挡在中间。

「──要是格林当上骑士就好了。现在是卓格夫队的副队长，应该也不远了。」

「……嗯，是啊。」

察觉到特蕾希雅的担忧而这么回答的威尔海姆触碰她肩膀，然后搂过来让身体靠在自己肩膀上。感受到体温的特蕾希雅闭上眼睛。

自己能和威尔海姆结合完全是靠奇迹接连发生。要是有任何一个闪失就不会诞生现在的幸福──现在很想发自内心感谢这点。

满怀这样的怜惜后，特蕾希雅凝视威尔海姆。

然后──

「……对、对了，威尔海姆。」

「怎么了？」

「今天你也休假，对吧？今天一整天都没有行程。」

视线仿徨不定这么问的特蕾希雅令威尔海姆蹙眉。不明白她这么问的意图，于是就著这样的表情点头。

「对啊。那又怎么样？」

「……虽然才早上，但卡萝也不在了，那个……要、要不要我烧洗澡水？」

自觉面泛红潮的她鼓起勇气这么说。

拿她以「剑圣」之姿立于战场的样子来比较就太失礼了，不过感觉她现在比那时还要紧张，是因为这里也是认真决胜负之地吧。

「────」

接受这点，威尔海姆蓝色双眼睁大。看到他眼中自己的脸孔有多么不检点，似乎使特蕾希雅丢脸得要死。

虽然羞耻到好像快死掉了──

──这一天，对他们夫妇而言首度的经历又增加了一件。此事就先在此记下。

4

威尔海姆和特蕾希雅要去蜜月旅行，但现实层面却有种种考量和问题。

例如王国骑士团重新编组后，威尔海姆率领的卓格夫队业务繁重，也被众人期待能编入国王的直属部队。在国内外还浓厚残留内战影响的状况下，身为部队长的威尔海姆实在不宜离开王都。

其实被高层以此为理由要求旅行延期，实在很难拒绝。

但是──

「──不行，『剑圣』和『剑鬼』好不容易结为连理，现在要出门旅行，余等要是阻拦妨碍的话，连龙都会愤怒的吧。尽管去！」

原本的顾虑，在听说了事情始末的吉欧尼斯陛下一声令下后彻底粉碎。

国王还是一样直爽又情深义重，威尔海姆深深感谢他的解围。触及到他为王的器量，就会让人想要举剑为国奉献。

就这样，和大力赞同的吉欧尼斯陛下约好会带纪念品和讲述游记之后，威尔海姆成功安排了蜜月旅行。

丈夫的工作行程排好了，剩下的问题就是妻子那边。

原本特蕾希雅就有「剑圣加持」在身，但现在的她已经脱离王国军，成为一名贵族千金──还是为人妻子。要说这样的她会有什么问题的话，那就是「剑圣」压倒性的知名度。

「特蕾希雅大人要是被认出来，百姓的生活会大乱。那应该也不是您的本意。所以说，您要小心再小心。」

这是要跟特蕾希雅一块旅行，被久违的随从职责点燃干劲的卡萝的坚持。面对斗志昂扬的她，特蕾希雅有点被她的气势压倒了。

「那、那个，卡萝？你的呼吸有点急促喔？」

「能够自由打扮特蕾希雅大人，身为随从的我幸福到极点……。虽然结婚典礼时也有大显身手，但是我会用全副身心来疼爱特蕾希雅大人的！请做好觉悟！」

「唉～呀～」

卡萝的手意外地巧，专心地打扮特蕾希雅。这名女骑士明明很厌恶打扮自己，但在为特蕾希雅打扮时却会卯足全力。

最后成品是控制住特蕾希雅别具特征的魅力，同时将之升华成大幅提高娇滴滴感和高雅的魔性。

「只是把作品递到那男的面前是我最大的痛苦……」

「太夸张了……旅行期间别跟威尔海姆吵架喔？」

咬牙切齿的卡萝令特蕾希雅苦笑，接著看著镜中的自己感叹。

醒目的红发用宽檐白色帽子削弱印象，取而代之的是长裙襬连身洋装，以及施以精美刺绣的裙子很引人注目。

这样子只要不带著龙剑，就不会有人认为自己是「剑圣」。

「不愧是卡萝。嗯嗯，我非常满意。」

「那就好。那么，旅行的准备……」

「──在那之前，卡萝没打扮就太不公平了。」

「咦？」

特蕾希雅笑著转头，那笑容让卡萝全身一僵。

卡萝不住后退，特蕾希雅则是穿著千金大小姐的装扮将她逼向墙壁，然后张开双手不让她逃走。

「好啦，你也放弃抵抗乖乖做个女孩子！不可以只有我觉得害羞。」

「请、请饶了我，特蕾希雅大人！像我这样严肃的女生根本不用化妆……」

「你在说什么蠢话！好了，来吧来吧，看我的看我的！」

「唉、唉～呀～」

过了令人会心一笑的休息时间后，蜜月旅行终于成行。

5

蜜月旅行的时间，被豪迈地给了两个月。

听说这也是吉欧尼斯陛下的贴心，被礼遇到感谢之情越积越多，唯恐偿还不起。因此决定谢意日后一定要表达出来。

「即便如此，还是没法绕王国一圈呢……」

「反正去北部或东部也没什么好看的。这次就跳过吧。」

「可是，托利亚斯领在王国北部吧？」

「……这次就跳过。蜜月旅行去到那边只会徒增麻烦。」

想在途中去托利亚斯领──由于家族已经灭亡，所以得说是前托利亚斯领，但特蕾希雅还是想去威尔海姆的故乡。毕竟是丈夫的夫家祖先和家人的永眠之地，结婚前两人有去那儿扫墓，不过威尔海姆认为太常去死人也会嫌烦。

「知道了。那就照你说的……那要往西还是南，哪一边？」

「去西部的话就是水门都市，去南部的话就是地龙之都和商业都市吧。你挑喜欢的。」

「嗯、嗯～嗯嗯嗯……！」

选择权落在自己手上，烦恼到最后的结果，特蕾希雅张大双眼。

「──第一次的旅行，就去南部！」

搭龙车从王都出发的夫妻，决定一开始先去「弗朗达斯」。

弗朗达斯据传是地龙的起源地，位在海格拉拉高原上的都市栖息了许多种类的地龙。

在那儿出生的地龙不只在国内，连在国外都被视为宝物，因此那里以地龙产业而发达，也被列为露格尼卡五大都市之一。

「神龙波尔卡尼卡和初代剑圣雷伊德以及贤者夏乌拉缔结友谊，据说也是在弗朗达斯。」

「毕竟是地龙的诞生地，当时就有听说是神龙赐予的恩惠。虽然我觉得是唬烂。」

「可是，要是相信那是真的，不觉得就有种很兴奋的感觉吗？」

见特蕾希雅眼神闪耀光芒，威尔海姆憋住胸中的感慨，露出苦笑。

弗朗达斯以不辱没「地龙之都」名号的景致来迎接三人。

在宽广的都市中，不管去到哪当然都会有地龙，而且这个都市的一切机能的动力源都是仰赖地龙。

举个简单易懂的例子，像是旋转巨大滚轮的地龙动力。让地龙在滚轮里头跑，产生的动力就能用来引水至水道以及让吊桥升降。

「最近连在王都到处都可以看到使用魔矿石的魔法灯……」

「但这边反而看不到。不过这种滚轮在王都也没见过。」

「因为在王都，地龙的职责几乎都是交给货车或人来搬运。地龙的数量没有多到可以用来充当动力源的地步。而且王都的地形也不能说适合这种作法。这是这块土地才有的特色……干嘛？」

特蕾希雅和威尔海姆对话时，长舌的卡萝也接著说话然后面露不解。原因是威尔海姆的眼神。他耸肩说：

「没事。只是很讶异你竟然能做出这么聪慧的说明。你懂很多嘛。」

「被你直接称赞不带挖苦叫我不能释怀。……只是拾人牙慧罢了。」

「是格林吗？」

不想回答的卡萝皱眉，但这就是答案了。

一行人停留在弗朗达斯的时间约十天，这段日子三人都悠然度过。

话虽如此，享受的主要是特蕾希雅和卡萝，原本就没有欣赏风景这种感性的威尔海姆，基本上都是跟著她们而已。不过──

「──欸，威尔海姆！看啊！多漂亮的景色！」

跨坐在地龙上驰骋于高原上，特蕾希雅指著群山之间的落日笑道。

就算不会被景色吸引，但会被因美景而笑开怀的特蕾希雅吸引。同样骑著地龙在旁边的自己，只要能凝视她微笑的侧面就够了。

威尔海姆从中得到自己正在享受旅行的实感，表情放松。

只不过，对这趟旅行也有不满的地方。像是住宿的房间分配。

「是说，旅行期间订两间房是没问题啦，但怎么会是我一个人睡一间房，你们睡另一间房？这趟是我跟特蕾希雅的旅行耶。」

「你这家伙，跟特蕾希雅大人同房一定别有所图……」

「我先讲清楚，我们在宅邸的时候每天都同床共枕。你的担忧已经迟了太多步。」

「你这混帐──！」

「够了喔！禁止吵架！不──准──吵──架──！威尔海姆也不要挑衅卡萝！不然以后不跟你一起睡啰！」

类似的对谈不时发生。消耗了在弗朗达斯的行程，退房的三人下一个要去的都市是「聘可塔特」。然后在路上──

「顺便一提，阿斯特雷亚本家就在弗朗达斯附近……」

「是喔。」

「不知道母亲和父亲回到家了没……」

「是喔。」

进行完对话后相约禁止顺道去拜访。

就这样，撇离只要稍微绕远路就能到的阿斯特雷亚本家宅邸，龙车抵达以风光明媚闻名的都市聘可塔特──故事的舞台。

6

「聘可塔特」是露格尼卡的五大都市之一，是靠著与外国交易而繁荣的商业大都市。

都市划分为东西南北和中央五个区块，每个区块贩售的商品不同，而且有各自的规则。因此五个区块实质上都是不同的城镇，这个有别于其他土地的特色就是这儿的特征。

在这当中，中央区有多间适合给富裕阶层或是外地人居住的设施。而旅行中的威尔海姆一行人也按照惯例，在中央区投宿。但──

「──父亲是笨蛋！我不理您了！」

大清早就有高亢美声响彻旅社，在庭院树上歇息的小鸟们一齐振翅飞去。

受惊的拍翅声远去，世界又恢复片刻宁静。可是时间仅冻结了一瞬，融化时采取慌张行动的是个瘦长蓄胡的男性。

应该说，他就是贝尔托。

「等、等一下，特蕾希雅。用不著这么生气吧？在意想不到的地方遇到爸爸，惊讶完之后应该是要感动得扑进我胸膛……」

「为什么父亲老是这样！才想说这次您比较懂事了，我本来相信您了！背叛者……过份！过份过份过份！」

「咦咦咦咦！？怎么快要哭出来了！？」

在都市中央区被誉为最顶级的旅社「金狼酒杯」的入口，特蕾希雅和贝尔托又开始重复已经睽违半个月的争执。贝尔托被女儿的剑拔弩张吓得畏缩不已。扶著激动的主子的肩膀，卡萝冷酷地瞥向他。

「在女儿的蜜月旅行抢先卡位……贝尔托大人，小的实在没法为您说话。」

「怎么连卡萝都这种脸！？在旅行地点遇到家人，不是应该要温馨感动到忍不住落泪吗！？」

「并没有，才不会，根本不可能吧！母亲有允许吗？」

「不，媞舒雅很反对……不过，我想说她可能是在测试我……」

「是喔，是测试没错。我的忍耐力正在接受测试！被父亲您测试！」

看看缩得越来越小的贝尔托，这次媞舒雅似乎没跟他一块来。头一次看到他单独行动，不过正因为媞舒雅不在，所以反而让人紧张，因为不知道他会做出什么比之前更糟糕的事。

「冷静点，特蕾希雅。发火也无济于事。反正又不是连房间都一起。都见过面了，父亲大人也甘愿了吧。」

「咦……可是我也有在这订房……」

「──想必父亲大人也甘愿了吧。」

感觉到父亲还想黏著女儿，威尔海姆直接用剑气让贝尔托安静。

「剑圣」家族的大家长只撑了一眨眼，接著立刻铁青著脸点头。虽然这不是对丈人该有的态度，但是这种时候当然是袒护太太。

「唉……父亲，您是怎么跟母亲说才来这里的？」

「我跟媞舒雅说要去执行公务。这都市的西区商家通知我说要的东西来了，叫我过来拿……没错，这才是我真正的目的。」

「那么，你在进行真正目的的时候就顺便来妨碍我跟威尔海姆……」

「不管我说哪一个你都会生气吧！那不然要我怎么办嘛！道歉总可以了吧！」

嘴巴这样讲，但又因为面子问题所以没有真的道歉。

眼看这对父女即将再度争执，威尔海姆和卡萝互看彼此后点头。接著威尔海姆抓住特蕾希雅，卡萝抓住贝尔托分开两人。

「威、威、威尔海姆……」

「我懂。我知道，所以你先冷静。」

特蕾希雅难过到热泪盈眶，威尔海姆平静地跟她这么说，看著她的眼睛。

「我再说一遍，冷静下来。不要感情用事。」

「可是，这次真的太超过了……」

「假如憋不下去，那我代替你生气。你这张脸不能给我以外的人看到。流露感情的对象只要有我就够了。」

「不要自作主……啊呜。咦，那个，这个……」

在呼吸碰到彼此的距离下被这么说，前一秒还怒上心头的特蕾希雅气势急遽转弱。虽然依旧涨红著脸，但里头的成份不是愤怒。羞耻和害臊一口气增长势力。

见她这样，威尔海姆放心了，然后看向另一个麻烦人物。

「我要跟媞舒雅大人报告喔。」卡萝单凭这么一句话就轻松战胜贝尔托。虽然这样叫人觉得匪夷所思。

「那么，既然贝尔托大人也理解了，那事不宜迟，我立刻送……」

「慢著慢著慢著，卡萝！你未免太早赶我走了！我是有事才来这里。混进特蕾希雅的旅行中并不是我的目的！」

「父亲大人，请注意您说的话。否则我也没心情阻止特蕾希雅了。」

贝尔托一个不注意就暴露出野心，这样特蕾希雅爆发只会是时间上的问题。赶紧让丈人完成目的走人方是上策。

「……所以，父亲是想要什么吗？」

「总、总觉得这说法带刺……唔嗯，我想要的是──」

畏惧女儿狐疑的眼神，贝尔托摸自己的胡须，接著有点害羞地垂下眼帘。

「──媞舒雅的发饰。因为我们的结婚纪念日快到了。」

7

「父亲每年都一定会送新的发饰给母亲。而每当重大节日，母亲也必定会佩上当年的发饰……只有这点是我佩服父亲的地方。」

视线朝上瞥向威尔海姆，特蕾希雅轻轻一笑。

「希望威尔海姆你也学著点。」这个微笑的言外之意昭然若揭，不过另一个言外之意就是：「除此之外父亲做的事都很讨人厌。」

不管怎样，由于贝尔托的目的极为正当，所以也就没有制止他去收取礼物的理由。只是前往西区向熟识的商家领取货物罢了。就算是贝尔托，应该也不会再惹麻烦了。

「不过，为什么我们得陪他去呢？」

「没办法。希望特蕾希雅大人一块去，是贝尔托大人的要求。要是拒绝这小小的请求，导致旅行期间都被黏紧紧的话，那可够折腾人的。」

「你讲自己主子的家长可真不客气……」

并肩走在大马路上，卡萝的叹气惹来威尔海姆脸部抽筋。

威尔海姆会跟卡萝正经对话，在这趟旅程中可说是相当罕见。

之所以会变成这样，是因为走在前头的父女感情好到挽著手走在一起。顺带一提这并非贝尔托的要求，而是自然形成的结果。

「特蕾希雅那家伙，嘴巴念那么多，其实还是很亲近父亲大人嘛。」

「麻烦别用亲近这种像在说小动物的说法。基本上，他们的感情之好光看就知道了吧。特别是贝尔托大人，完全是把特蕾希雅大人捧在手掌心上疼。事实上也真的试图要把女儿捧在手上过。」

「但他的手还好好的。」

幸好特蕾希雅的「死神加持」没有起作用。要是因为那种事而害父亲的手废掉，那特蕾希雅一定会后悔一辈子。

抱著这样的感慨，威尔海姆眯起眼睛看著前面的父女。特蕾希雅对著只有声音严厉的贝尔托鼓起脸颊，但旋即又灿笑如花。

「……以『剑鬼』而言，真是松懈的表情呢。」

「我也有不需要当『剑鬼』的时候。实在想不到竟然能看到特蕾希雅和父亲大人正经对话。」

「这……或许吧。」

原本想紧咬不放的卡萝，难得今天赞同威尔海姆。

不管怎样，至少特蕾希雅和贝尔托的亲子关系修复了。──抑或者，打从一开始就没必要修复。

既然没必要盯著他们父女，威尔海姆也就适度地欣赏起都市的罕见风光。外观近似王都的商业街，但活力和热情却跟深受内战影响的王都有天壤之别。

马路两旁排满了商店和摊贩，吆喝叫卖的声音洋溢著生命力。长期作战导致兵疲马困的窘境，似乎跟这个都市无缘。

「好吵的街道。」

「跟你不合？不过，在特蕾希雅大人的守护下才能有这种样貌。」

威尔海姆简短的喃喃自语，卡萝却是正经八百地回应。她的答案没有虚假。要是「亚人战争」的魔爪有伸到这里来的话，那这份活力恐怕不复在。

「因为那家伙很爱自责。」

「对特蕾希雅大人来说，比起人民因为被拯救而献上的感谢，失去后的无言视线更是沉重。在旁边的我是心焦如焚……不过颠覆那一切的，果然是你。」

「────」

「我痛切地感受到这点。这趟旅行对我来说，就像是划清界线之旅。」

「划清界线？」

「……等旅行结束回到王都，你就知道了。」

卡萝看也不看他，带著平常的扑克脸这么说。就算想要探问，但卡萝却筑起铜墙铁壁，让人无法窥见她情感的内面。

回到王都就知道。虽然是个死板的人，但这句话可以相信。威尔海姆是这么想的。

就这样进行稀奇罕见的对话，一行人走了快一个小时。

「这里就是我说的店。」

贝尔托停下脚步的地方，是进入西区后马上就会看到的一家商店。听了他的话抬起头，威尔海姆眺望店面。

店铺相当大，贩售的商品从服装到食品应有尽有。据卡萝所说，在聘可塔特，从一间店所贩售的商品种类，就能够简单看出这间店的高低。按照这道理来看，这间店在这个都市里岂不是相当大的店面了吗。

「思文商会……」

「是充满干劲的商家。几年前直接找上我们本家洽商，之后每年送给媞舒雅的发饰，我都是找这里的老板商量。」

「虽然听过，但我是第一次来。谁叫父亲您每次都是一个人偷偷来。」

「礼物一个人就能挑。毕竟这是确认爱情的绝佳妙法。」

在特蕾希雅的嘲弄眼神下，贝尔托倒是毫不害臊堂堂正正地回答。听了这答案，特蕾希雅惊讶了一下，然后立刻垂下眼帘，似乎对自己的话感到羞耻。

毫不羞怯地把对妻子的爱转化成具体形式的态度十分帅气。感觉自己对贝尔托和媞舒雅的夫妻关系看法有点改变了。

「雅克托尔•思文在吗？我是跟他有约的贝尔托•阿斯特雷亚。」

不理女儿夫婿的视线，贝尔托朝站在店前的年轻店员这么说。「请稍候一下。」有熟客来访，店员快步走进店内。

「不好意思，威尔海姆。我接下来要挑选送妻子的礼物……可否请你和卡萝移驾。我可不是觉得难为情喔。」

在等店员回来时，贝尔托突然转过身这么说。这要求令威尔海姆抬眉，接著说：

「我是没差……但特蕾希雅留下来好吗？」

「我想跟女儿一块选发饰。稍微了解一下我的内心。」

明明方才说礼物都一个人选的，现在却说这种话。根本话都是他在讲。

「我可以！好、好啦，威尔海姆就跟卡萝出去蹓躂一下。这一定是最后一次跟我以外的女孩子散步的机会喔？」

「那种机会我从以前到以后都不需要。」

「够了，快点过来！特蕾希雅大人，贝尔托大人！那我们离开片刻。之后在这间店再见！」

燃起抗争心的威尔海姆被卡萝硬是拉走。虽然想要抵抗，但一看到特蕾希雅挥手苦笑就没了干劲。

没办法。既然是老婆的爸爸最后的任性，那就睁一只眼闭一只眼吧。

「……真的是最后的任性吗？」

「和贝尔托大人来往的经验告诉我，当他说这是他最后的请求……绝对不可以配合。这点要铭记在心。」

被传授了讨厌至极的训诫后，威尔海姆臭著脸和卡萝离开店家。

最后又回头看了一眼那对父女所在的店面。特蕾希雅在看不见他们之前，都不断在挥手。

──事后威尔海姆非常后悔自己当时离开那里。

8

──被卡萝扯著手，臭脸的威尔海姆消失在人群之中。

「特蕾希雅，你们一路旅途如何？」

彷佛看准这点，贝尔托盯著女儿的侧脸问。听了之后，特蕾希雅手贴自己的嘴唇，回答：

「非常快乐。就跟想像中……不，是超乎想像。」

「旅行超过一个月，就能看到平常生活里看不到的事。在宅邸可能觉得威尔海姆的举止没有问题，但在旅行期间就难说啰？像是偷瞄路上的女性，对店员没礼貌，或是对正在享受的你说『回家吧』这种不识趣让人伤脑筋的话……」

「没事的，父亲。」

「可是……」

「父亲。」

面对想死咬著这议题不放的贝尔托，特蕾希雅平静呼唤父亲。看著澄澈湛蓝彷佛湖面的瞳孔，贝尔托也知趣地闭上嘴巴。

虽然是万分不解人意，超级不会察言观色，更不懂得体察别人心情的父亲，但毕竟也是为人父母，立刻就明白女儿的心情。

「我在这趟旅程中，确实看到了许多他不同于平常的面貌。对其他女人眉目传情或是在没兴趣的地方摆一张臭脸的情况都没有，您用不著担心。他没法老实对人温柔……这点我想在今后改正他。」

特蕾希雅笑嘻嘻地扳著手指细数旅途发生的事，边回想边说：

「不过，认识到许多他平常不为人知的事后，我变得更喜欢他了。他很棒。因为是他，所以才好。」

「────」

「父亲，我在恋爱。我深爱威尔海姆。那个人的一切全都温暖我的胸口，让我无法自拔。──我很幸福。所以，」

话到此中断，她沉默并仔细凝视父亲，开口：

「──父亲，谢谢您一直担心我到现在。」

特蕾希雅微笑，满怀感激和亲昵告知了自己所能办到的顶级祝福。

听了爱女的回答，贝尔托屏息。接著手掩嘴巴说：

「我……只要你幸福，这样……这样就够了。」

「嗯。」

「你是我跟媞舒雅的孩子。是提姆兹、卡尔朗、卡吉雷斯的家人。我有责任让你幸福。而现在……」

「嗯。」

「这个任务，已经达成了吗……？」

「──是的。」

父亲声音颤抖，特蕾希雅带著爱回答。

扣下了最后的扳机，贝尔托感情溃堤。原本摀著嘴巴的手移到眼睛上，双眼开始流淌豆大泪珠。

在这么多人走动的街道上，一个中年男子嚎啕大哭的样子相当引人注目。但是特蕾希雅不引以为耻。她贴近父亲，轻轻递出手帕。

贝尔托接过手帕，用力擤鼻涕，接著直接把手帕还回去。特蕾希雅无可奈何地收下，想说之后再处理。

「既然你幸福，那就好了。在这趟旅行知道这件事就好。呜呜。」

「嗯，谢谢您，父亲。」

无视最后吸鼻涕的声音，特蕾希雅朝贝尔托深深鞠躬。

周围的人见贝尔托停止哭泣后就对他失去了兴趣。旁人看热闹的态度让特蕾希雅苦笑，然后转头看向店里──

「啊，抱歉让你久等了。你是老板吗？」

「咦？啊，是的，正是如此。那个，我就是这家店的代表雅克托尔•思文。以后还请您多关照。」

说完朝特蕾希雅低头的，是有著灰色头发、面容细长的人物。年纪略大于特蕾希雅吧。这把年纪就能自称是一家店的代表，著实令人惊讶。于此同时，也明白这个人就是和贝尔托有交情的商人。

「雅克托尔吗。抱歉让你看到丢人现眼的一面。」

「不会不会，哪里丢人现眼了。你们父女的重要对话让我也忍不住眼睛热起来了。……不如说过意不去的是我。」

「过意不去？」

青年──雅克托尔低头，从他的话中察觉到不对劲的特蕾希雅皱眉。

可是那个不对劲的答案立刻就主动出现了。

「──是要废话到几时。一群蠢货，少浪费余宝贵的时间。」

傲慢的声音从店里传来，特蕾希雅看了过去。店里的陈列架摆出的通道尽头，有一扇通往店面里头的门，而声音的主人就站在门前。

是个个子瘦高，容貌异样端正聪明的男子。年龄约三十岁，有著充满光泽的深紫色头发，以及一眼就能辨别其高贵身份的服装和仪表──只不过不是王国风格。

「史、史泰德大人！方才应该请您在里头稍候……」

「驽钝，愚昧。尔辈这种卑贱商人胆敢束缚余的行为。傲慢也该适可而止，否则就将汝唯一的长处──鉴定物品的双眼挖出来。」

被称为史泰德的男子，用冰冷锐利的目光刺穿雅克托尔。那冷冰冰的声音和视线，即便不是当事人的特蕾希雅也背脊打颤。

能够理解。史泰德的话绝无虚假，甚至不是威胁。──这男的只要不顺心，就真的会把对方的眼珠挖出来。

「……您似乎说了不太符合绅士礼节的话。到底有何贵干？」

代替被史泰德的视线给吓到发抖的雅克托尔说话的，是站到前头的贝尔托。方才丢人现眼的举止荡然无存。他的侧脸如今充满阿斯特雷亚家的当家、符合「剑圣」家族领头羊该有的霸气。

承受霸气的史泰德意外地挑眉。

「哦。还以为跟个女人一样哭天抢地的，没想到振作起来啦。」

「既然受到不正当的侮辱，就该用相应的态度回敬。若来此有什么事就速速告知。不然的话，可不是靠商量就能了事。」

「不能靠商量了事是吗。──这点余很满意。正如余所愿。」

「什么？」

对危险的对谈感到喜悦，这反应令贝尔托皱眉。结果，脸色惨白的雅克托尔吞口口水，说：

「贝尔托大人……史泰德大人说想要本店为您准备的物品。当然我已告知有买家所以拒绝，但他说想要直接跟您谈……」

「因此余才这样等待。因为知道汝会来所以才忍耐，却没想到汝竟然在店门口上演闹剧。还是让人看不下去的烂戏。」

「我说你……」

史泰德打断雅克托尔的说明，但冷笑的他所说的话惹得特蕾希雅一肚子火。被讲成那样，根本是全盘否定父女俩的心意相通。

这根本是瞧不起父亲的爱，蔑视贝尔托笨拙的疼爱，自己当然不能默不作声。

可是──

「……这是做什么？」

「按照露格尼卡王国的做法，申请决斗。帝国的少狼。」

史泰德眯起眼睛，白色手帕落在他脚边。那是贝尔托丢出去，撞到史泰德的胸膛后才掉落的。

做出这样的行为就如贝尔托所说──是正正当当地申请决斗。

「父亲……！」

这件事让特蕾希雅倒抽一口气，雅克托尔的脸逐渐变得铁青。但是，贝尔托的勇敢面容没有一丝动摇，而承受的史泰德也一样。

「做出无礼之举，可别想全身而退。」

「我可没打算退缩。你侮辱我女儿，甚至还想从旁夺取我要送给妻子的礼物。像你这种贼骨头，断不可原谅。」

「哈！真敢说。胆敢大言不惭！」

大声起来的史泰德表情升温。方才的冷酷神色消失，双眼在敌意下闪耀瞪著贝尔托。

「父、父亲！不可以！就算那样做……」

「不要阻止我，特蕾希雅。我好歹是王国贵族，也是阿斯特雷亚家的男人，更是一心向往挥剑的男儿。──最重要的是，我是丈夫，也是父亲。」

「──！」

没有退缩的选项，贝尔托挥开特蕾希雅的制止。父亲的决心与觉悟，令特蕾希雅没法再挤出一个字。

特蕾希雅只好奋力看向史泰德。从他的站姿，可以看出这个男的究竟有多厉害。拥有「剑圣加持」的特蕾希雅，也具备了一眼看穿对手力量的眼力。而看过去的答案是──

「──呃。」

「大胆。不准看过来，女人。无礼之徒的女儿一样也没礼貌。不过，汝用那万分无礼的双眼看穿了吧？余的高贵躯体可不是用来决斗的。」

「……什么意思？」

见特蕾希雅语塞，史泰德发出干笑，然后朝著表情诧异的贝尔托说：

「没什么。余体弱多病。别说提剑，连奔跑都有问题。靠著这副身躯决斗，一看就知道结果会凄惨无比。没错吧？」

「可能吧……」

特蕾希雅看到的答案，被史泰德本人娓娓道来。他的话没错。特蕾希雅看出史泰德的肉体承受不住剧烈运动。

那为什么这男的还接受决斗呢──

「──因此，接受挑衅和决斗的余，将会立代理人。这是看在汝之气魄上。」

代理人。史泰德一这么说，特蕾希雅就反射性回头。

「────」

后面有道直到刚刚都不在的人影。是个大块头。需要仰望的身躯将近有两米高，若不弯腰根本就进不了店面入口。全身用黑袍包覆的人影盈满让特蕾希雅感受到危机的霸气──

「──他正是余之代理人。虽是充当护卫而带在身旁的无赖，但这种时候就派得上用场。」

史泰德残酷又愉悦地朝颤栗的特蕾希雅这么说。

这是「剑圣」特蕾希雅•范•阿斯特雷亚与「八腕」库尔刚的邂逅。

──也是「聘可塔特的银华乱舞」所擦出的最初火花。

9

──目睹那名男子的瞬间，特蕾希雅的本能就在敲警铃。

就连目前仍有「剑圣加持」在身，受剑神擅自眷顾的特蕾希雅，都对那斗气感到颤栗。

厚重肌肉形成的铠甲被黑袍覆盖住。大块头的脸被袍子隐藏而看不见，但他最大的特征是手──而且还是常人不会有的八只粗壮手臂。

四双手悠哉地抱胸傲立的男子──一眼就能明瞭他是万中选一的豪杰。

「──不是说是单纯洽商，现在这是怎样，史泰德？」

「汝块头大到血液都送不到脑部呢，库尔刚。以为余是无事找事做？找麻烦的是那边的无礼之辈。好了，完成汝的护卫本分吧。」

「库尔刚……！？」

大块头的嗓音低沉到让人错以为山在说话，而史泰德却傲慢回应。他们的对话，让特蕾希雅叫出声。

大块头的斗气以及超过两只的手──如果是多手族的「库尔刚」，那肯定没错。

「你是佛拉基亚帝国的……『八腕』库尔刚！？」

「哦。不只看穿余的体质，还知道『八腕』这名字啊。真意外……不，有眼光是当然的吗。仔细一看外表也很出色。勾起余的兴趣了。」

「住手吧。这个姑娘不是会栽在汝手上的兔子。」

「……哼。祸血还敢自以为是给主人意见。」

开始对特蕾希雅有兴趣的史泰德被库尔刚打断。大块头掀起帽兜，裸露遮住的脸──蓝色肌肤和黑色瞳孔，压迫感十足的战鬼容貌。

然后盯著警戒有加的特蕾希雅说：

「我看汝身段廉洁，还具有超乎常人的武力。叫什么名字？」

「────」

一瞬间，特蕾希雅犹豫如何回答。

对方的身份很清楚。说到佛拉基亚帝国的「八腕」，是帝国最强战士的斗神称号。他的威名甚至传到露格尼卡王国，当然相对的，特蕾希雅──「剑圣」特蕾希雅•范•阿斯特雷亚的名号也是。

要是一个不慎报上名号，就成了「剑圣」与「八腕」的邂逅，而这会导致什么样的后果，特蕾希雅无从判断──

「──对小女投以这种眼神会让我很伤脑筋的。小女已经许配给他人。万万不得打她的念头。而且，这是我跟他之间的问题，身为代理人的你也不例外。」

在犹豫时介入并走向前的是贝尔托。他将爱女特蕾希雅藏在身后，意图完成挑起决斗的当事人应尽的责任。

接受这气魄，库尔刚重新看向贝尔托。

「……这份气概很棒。然而，汝不是吾之对手。」

「看过对方，还能够若无其事下战帖的人才叫剑士的骄傲吧？」

「──原来如此。是在下不识趣。原谅吾，王国的剑士。」

贝尔托的澄澈决心让库尔刚钦佩地低头。帝国最强战士向贝尔托谢罪，这幅光景令特蕾希雅忘了说话。

在这瞬间忘了置身的状况，单纯觉得父亲让自己很骄傲。

没有剑术才能，平常的言行也称不上勇猛，过度保护又不懂看气氛的个性惹自己火大无数次，但现在的父亲却闪闪发光，足以抵销那些缺点。

「取而代之的，虽然知道这样问很失礼，但请教大名？」

「……我名为贝尔托，『八腕』库尔刚啊。」

不说姓氏的贝尔托隐瞒了阿斯特雷亚──身为「剑圣」家族一事。没有打算重新报上名号，代表贝尔托和特蕾希雅的担忧一致。

「哼。」见父女如此，史泰德百无聊赖地鼻子喷气。

「真费工夫。血缘亲情……是余所不理解的道理。比起汝，让女儿持剑还更有道理。」

「────」

「还是说，是真心要让她弃剑从良？既然如此，就是汝疯了。允许如此的露格尼卡国王也是比传闻中还要愚昧的昏君。」

「史、史泰德大人！？这、这里可是王国都市聘可塔特喔！？」

贝尔托的高声主张惹来史泰德痛骂露格尼卡国王。对此惊慌失措的是被卷入这场纷争的雅克托尔。自己的店被当成决斗舞台使得他脸色惨白，还被史泰德嘲笑。

「呵哈哈。少用愚辈的标准去衡量阳剑之血，无礼之徒！不管脚下土地为何，阳光所及之处，余等就没理由畏惧。──好了，决斗吧。快点决斗！余的代理人『八腕』和代替『剑圣』、不自量力的家伙拼出个胜负！」

「──唔！你一开始就知道……」

兴致勃勃的史泰德，话中的恶意昭然若揭。

史泰德打从最初就知道特蕾希雅和贝尔托是阿斯特雷亚家的人──不，他根本就知道特蕾希雅是「剑圣」，所以才故意扯上关系的。

这无疑是帝国人史泰德居心不良的证据。

「你的目的是让两国关系恶化？既然如此，这场决斗……」

「撒手不干，是吗？那就是余全拿啰。自称是王国贵族恬不知耻的贝尔托，主动找余决斗却又怕到逃跑。跟他的女儿一块让家族名誉扫地。不错的形容吧。」

史泰德畅快淋漓地痛骂、贬损他人。

聪明的脸孔上带著残忍的他，让特蕾希雅激动到脑袋空白。父亲被瞧不起到这种程度，自己却只能哭著入睡吗。

但是，特蕾希雅的义愤填膺，也发生在贝尔托身上。

「特蕾希雅，我……」

「不行……！绝对不行，父亲。忍住，求求您。要不然会被杀的……」

比起家族和自己，贝尔托更重视特蕾希雅的名誉。特蕾希雅拉著父亲的衣袖，咬著粉红色嘴唇拼命摇头。

「──一旦战斗吾就不会放水。这是吾对敌手的敬意。」

俯视苦恼的父女，斗神沉重告知。

身为战士这种态度值得敬佩，但以现状来说却是把人给逼进死路的原因。假若以自尊受辱而接受挑战，那么「八腕」将会毫不留情地粉碎贝尔托。

在事情演变成那样之前，特蕾希雅想带著苦恼的父亲离开现场──

「连代替被贬损的父亲持剑的气概都没有吗。看样子，现任『剑圣』是个胆小鬼。假若不是，那么汝的丈夫一定长于在床上掳获女人吧。」

「──！」

下一秒，马路上响起坚硬声响。

是骨头敲击肌肉的声音，史泰德像反弹一样往后倒。击中男子苍白脸颊的是眼神熊熊燃烧愤慨的男子──贝尔托的拳头。

父亲被瞧不起，丈夫被讲难听话，特蕾希雅的忍耐也到达了极限。但是还没回过头，贝尔托就已经把史泰德揍飞出去了。

然后在瞠目结舌的女儿面前，对著史泰德大骂。

「──威尔海姆是阿斯特雷亚家的男儿。我不准你侮辱他！！」

「……作为升起决斗的狼烟，这样够了。」

嘴唇破皮流血的史泰德，仰望吼叫的贝尔托，说。

下一秒，爆发性膨胀的斗气出现在贝尔托的身旁。

「──不错。」

称赞他的觉悟，同时使出刚拳。

「帮我跟媞舒雅说抱歉。」

「慢──」

立刻伸手的特蕾希雅，听见父亲的声音沉稳地这么说。

10

威尔海姆听到出事而回来时，一切早已结束。

「────」

分开人墙硬是挤进通道里，只看到一片血泊。血量多到一眼就能看出有人伤重到处在生死关头。

就算环顾周围，也没见到在找的人影。原本在这家店前面分开，但心爱的女人和吵死人的岳父，全都不在这里。

「威尔海姆！在治疗院！特蕾希雅大人和贝尔托大人都在那……」

听到呼唤而回过头，表情严肃的卡萝跟店老板交谈听说事情始末后，两人便连忙赶往最近的治疗院。

然后，当他们喘著气抵达时，在候诊室的──

「──啊。」

特蕾希雅整个人呆呆地仰望赶来的两人。猛一看，她没有外伤。但相对的，她的浅粉红衣服上染著血。

大块的红褐色血渍，代表她曾抱著大量失血的某人。

「────」

见她那样，在出声前威尔海姆先抱紧她纤细的身子。顿时，原本要说话的特蕾希雅因强烈拥抱而倒抽一口气，然后溃堤。

她哽咽，泪水不断夺眶而出。

「父、父亲、父亲他……威尔海姆……！」

「别哭。没事了。……父亲大人呢？」

边摸她的头边问，特蕾希雅用颤抖的手指指向里头的诊间。

「我来吧。你先陪特蕾希雅大人。」

说完卡萝就朝诊间走了进去。目送她的背影，威尔海姆边安慰啜泣的特蕾希雅边问：

「发生什么事？我听说有骚动所以回去，只看到店前面都是血，你又哭成这样。虽然我也担心父亲大人，但是……」

「我、我没事……不过，在店里，跟帝国的人吵起来……不，不对。对方打从一开始，就是冲著我来……可是，父亲他……」

「冲著你来……？」

「父亲一直在忍耐。他知道对方的目的，所以知道不可以中挑衅……不管被讲多难听的话都忍住了，直到……对方讲你的坏话。」

「────」

「父亲说，你是阿斯特雷亚家的男儿……」

抓著胸口的特蕾希雅如此告知，威尔海姆失声。妻子的泪水逐渐湿了胸前。感觉有什么以此热度为燃料，开始发热烧起来。

在那个东西化为清晰具体的形式之前──

「──特蕾希雅大人，贝尔托大人的治疗已经结束了。我们去病房吧。」

「──！」

从诊疗室回来的卡萝说，特蕾希雅猛然抬起头，就这样踉跄走向病房。当威尔海姆也打算跟去时──

「威尔海姆，借一步说话。」

「──父亲大人还好吗？」

卡萝叫住他，威尔海姆先简短发问。卡萝边摸自己的金发边低声说：

「不好。这间治疗院的术师本领很高，托此之福，贝尔托大人挽回一命……但问题不在伤势，而在其他。」

「什么？」

「──门的耗损过大。这很不自然。恐怕是咒术的一种。」

声音是从身后传来，一名男子现身在候诊室。看起来比威尔海姆年长十岁，个子瘦长的人物。从他身穿白色术袍和姿态看来，是这个治疗院的术师。

「你是？」

「葛利奇。偶然在院里的术师。是说，我的事不重要。眼下最重要的是咒术……要是不能解开，患者就会没命。」

「那个咒术是啥？跟治愈术和魔法不一样吗？」

「是这些术法的亚种、赝品之类的玩意。不过不管是哪一种咒术杀伤力都很高，被施法者都会痛苦至死。是坏心眼家伙的拿手绝活。」

「────」

没听过「咒术」这个单字，却是贝尔托被宣告会「死亡」的原因。

静静消化自称叫葛利奇的术师的话，威尔海姆望向岳父躺著的房间。在那儿的他，生命如今仍在被侵蚀──

「──得找出干下这档事的帝国人。」

「终、终于、追到了……两、两位、脚程太快，根本追不上……！」

状况才刚说明结束，就有名上气不接下气的青年冲进候诊室。看过去，就是事件发生的商店主人──也就是清清楚楚看见特蕾希雅和贝尔托发生什么事的第三者。

「呼哈……我，有话要跟两位，不对，跟大家说……就是，咦咦！？」

「是哪个家伙干下这件事的？老老实实地吐出来。不准隐瞒。」

「慢著，威尔海姆。这样他说不出话来。你忘了斟酌力道。」

「麻烦冷静一下！我没有要包庇谁！我只是被要求来传话而已！我是来传话……请、请放我下来。」

被揪起衣领按在墙壁上的青年──雅克托尔终于被放开。

在威尔海姆和卡萝的包夹下，他胆怯地躲在葛利奇的背后，说：

「你们在找的史泰德大人，他们说明天早上会在西区的大桥上等候。说是带著折磨贝尔托大人的『朱色小指』……」

「那个『朱色小指』是！？」

「我、我不知道！我只被吩咐要这样传达……」

缩起来的雅克托尔似乎是真的没有更多情报了。玩味他的话，威尔海姆看向葛利奇。术师迎著视线点头。

「病患的玛那消耗剧烈。若不在白天以前解开咒术，就会有生命危险。」

「越早解开越好，就是这样吧。」

「──！这样哪能等到明天早上！我今天就要找到对方！走了，老板！跟我来！」

「咦咦！？我也要去！？」

不能悠哉浪费有限的时间，卡萝抓住雅克托尔飞奔到外头。她的耿直是项美德，但威尔海姆不期待她的成果。

对方是冲著「剑圣」而来，细心地使用咒术然后才指定时间和地点。这样的人躲起来的期间，要找到他简直难如登天。

「可以进去吗？」

「目前陪著病患的是你太太吧？我会跟负责的人说。你们今天想陪伴病患多久都可以。」

与嘶哑的声音和态度成相反，葛利奇充满人情味的判断令人赞同。接著虽然慢了一点，但威尔海姆走向门──贝尔托的病房。

保持洁白整洁的室内，里头是有四张床的大房间，但目前有三张床空著，只有贝尔托占据了一张床。

身穿病患服的贝尔托躺在床上，包著绷带的样子看起来令人心疼。特蕾希雅正握著他的手，凝视父亲的睡脸。

「像这样子，握著手……呼吸就比较稳定。父亲真是的，好像连露出痛苦的表情都觉得累了。毕竟他是个缺乏毅力的人。」

「……这样啊。」

威尔海姆静静地关上门。特蕾希雅没有看他，努力保持平常的语调这么说。她尽力佯装平静。

特蕾希雅是难过时也会逞强的女人，威尔海姆深知这点。

所以现在的她，一定十分痛苦。

「特蕾希雅，父亲大人发生了什么事？」

「……被施了奇怪的魔法。被那个帝国男人。」

「听说叫咒术。要是不解开，父亲大人就会有性命危险。而做出这种事的人在明天早上指定了会面地点。由我……」

「──我也要去。」

雅克托尔转达的条件，特蕾希雅豪气干云地回应了。可是那并非威尔海姆期望的答案。

他懂妻子的心情，但是对方锁定的人是「剑圣」，因此威尔海姆对于带她去这件事感到犹豫。

即便他知道这是把特蕾希雅和贝尔托放在天平上衡量的行为──

「──威尔海姆，听我说。」

「特蕾希雅。」

「我是曾为『剑圣』的女人。现在也仍是阿斯特雷亚家的女人。──阿斯特雷亚家的当家中了陷阱负伤倒地，我不能不去。」

这是身为王国贵族和王国剑士的骄傲与矜持。听特蕾希雅亲口这么说，威尔海姆屏息。

那并不是因为对她的荣耀或矜持所拥有的重量感到佩服。

而是因为，以这些为理由，想要积极贯彻自我的特蕾希雅泪眼婆娑，威尔海姆却觉得她从未这么美过。

而她就著美得让人看呆的双眸，说：

「你是阿斯特雷亚家的男儿，威尔海姆。──不是由其他人，是当家认证的。」

「……这样啊。」

「我跟你，是阿斯特雷亚家的儿女。──一起去吧。」

话语强而有力，威尔海姆仰视天花板。接著考虑了半晌，再慢慢地用手指拭去她那被泪水盈满的眼角。

「──说的也是。」

他只这么简短回答。

11

隔天一大早，威尔海姆和特蕾希雅就站在大桥上。

睡得不久，但状况不差。脸色糟的就只有半夜还在都市里东奔西跑，却依旧没得到任何成果，被自责和疲劳给折磨的卡萝吧。

「真的很对不起，特蕾希雅大人……」

「别道歉，没事的。威尔海姆会想办法，一切就交给他办。」

和道歉的卡萝抱在一起的特蕾希雅用毫无根据的话安慰她。这么简单就说这种话，让威尔海姆敲响配在腰部的剑柄叹息。

说来，现在还在蜜月旅行呢。非常遗憾，不管是威尔海姆还是卡萝都没有携带能和强敌死斗的剑。因此一开始，威尔海姆原先打算即便是粗制滥造品也行，至少要拿一把合用的单手剑去决斗，但──

「──小的知道您是阿斯特雷亚家的女婿威尔海姆殿下。还请收下。」

「……这是？」

这么说的人，是配合搜索寻找帝国人而跟著卡萝整晚到处跑的雅克托尔。出发前，他朝威尔海姆递出一个包裹。

收下的威尔海姆，对于沉甸甸的重量忍不住皱眉。包裹看得出来是包著长长的东西，但凭手感和重量就猜得到内容物。──这是一把剑。

问题在于出处。为何他要在这里把剑交给威尔海姆。

「我想您知道，这是一把剑。是锋利的名剑……想到接下来要发生的事，就觉得不能让您带次级品。」

「我是很感谢，但你没有理由偏袒我吧。」

「话不能这么说哟。贝尔托大人是我的大客户。这样的贵客在自己的店里和其他客人起纠纷……全都要怪我处理不当。」

「……他们是冲著特蕾希雅父女来的。你只是抽中下下签而已。」

「就算是，小的也有责任。而且，交给您这把剑并非为了赎罪。这原本就是您的剑。只是递交的时间有点提前。」

「什么？」

出人意料的话让威尔海姆吃了一惊，雅克托尔眉尾微微下垂。

「这是贝尔托大人订购，要赠送给女婿的礼物。跟送给夫人的发饰一样都是由大人亲自挑选的。──所以说，这是您的剑。是您持有才相应的剑，除了您以外无人能用的剑。」

「────」

「小的不知道自己有没有资格说这种话，但……祝您武运昌隆。」

在跟店家主人对话后，就有了这把剑。

手感熟悉得吓人，这都多亏了贝尔托的眼光吧。刀身长度、重量，全都像是量身订作般完美无缺。

因此这把武器没有任何可挑剔之处──再来要说有任何不安的地方的话，就只有──

「──先到了吗。本来就不该让余等候，这层顾虑是天经地义。汝们表现得还不错。」

傲慢的嗓音乘风而来，威尔海姆他们抬起头。在桥的对面出现的，是两名黑色装扮迎风飘逸的人影──一眼就知道是敌人。

面露冷笑、看起来就是贵族的男性，以及四对手臂抱在胸前的大块头──史泰德和库尔刚，帝国少狼和「八腕」一同现身。

「讨人厌的家伙。帝国贵族的恶心程度比传闻的还严重。」

「──。都没注意到呢。怎么有个多余配角。余可不记得有允许凡夫上这场舞台。胆敢旁若无人地待在此处，厚颜无耻至极。」

「我充分清楚跟你语言不通了。」

「够了，威尔海姆。我们不是来吵架的。」

被连续人身攻击，史泰德也忍不住残酷地眯起双眼。这时特蕾希雅介入。她用力瞪著史泰德。

「解开家父身上的咒术。」

「那不是咒术。谁叫那老头不只妨碍决斗还挑衅余，真是无可救药。对付无耻的王国人就该用……」

「──史泰德，够了。汝有时候话绕太远。」

「哼，不懂玩兴的无趣男人。汝们的目的，是这个吧？」

带开话题搪塞却被自己人给怪罪，笑意消失的史泰德举起右手。他张开的五根指头上全都戴著戒指，但其中小指头上的红色戒指正发出黯淡光芒。

是个看起来很诡异，色泽吸引人却又让人不舒服的宝石。

「这个叫『朱色小指』。自古以来就是咒具……在王国叫『流星』吧？就是其中一种。只要光芒不消失，你父亲的命就还在。当然，这也意味著痛苦拉得越长。」

「戒指交出来。我要粉碎那石头，解除那无聊的咒术。」

「笑话，凡夫。谁会乖乖交出去。首先，汝……」

挥手的姿势像在驱赶野狗的史泰德本来要打断威尔海姆的话，但彷佛是想盖过他的话似地，有东西飞进视野里。

那东西画出一道柔和的拋物线，撞击史泰德的胸膛后坠落地面。

是白色手帕──这种行为，在露格尼卡王国代表对方申请决斗。

「没时间了。──由我让事情变单纯。我要求跟你决斗。」

代替沉默的男人们支配现场的，是扔出手帕的特蕾希雅。她全身释放锐利剑气，眼神笔直瞪著史泰德。

站在那里的，不是盛装打扮的楚楚可怜少女。而是一把彻头彻尾被研磨犀利到让人心涨裂的冷剑──「剑圣」。

「终于让人拜见『剑圣』之姿了吗。说要决斗，还真是亲子同样野蛮呢。」

「不过，这正是你的盘算吧？找个理由，将我……『剑圣』拉到决斗的舞台上。虽然不知道你有什么企图……」

正面迎接特蕾希雅的剑气后，史泰德的冷笑开始带著些微热度。这个反应令特蕾希雅面颊僵硬，凝视史泰德身旁的库尔刚。

「……你早就做好稳赢的准备。证据就是带上了帝国最强战士。」

「────」

「我只问一件事。这场决斗的目的，是要让王国和帝国的关系恶化吗？如果是的话……」

「是的话，就怎样？」

「那就不搞决斗，只能强抢戒指了。」

「────」

终究不希望扩大成国家之间的问题。

听了特蕾希雅带著这番意思的话后，史泰德张大双眼。接著手掩嘴巴点头道：

「原来如此。不好惹的女人──就算决斗的结果是『剑圣』因遭遇不测而殒命。但是，那样的目的有何意义？王国有神龙庇佑。只要庇佑尚在，帝国不管怎么策划都没有意义……根本不过是亡国愿望吧？」

两手一摊，史泰德否定特蕾希雅的担忧。

其实他的话很正确。──正确来说，是奠基于被视为是正确的事实上。

「────」

探不出史泰德的态度，特蕾希雅表情严肃地抿起嘴唇。

亲龙王国露格尼卡过去与「神龙」缔结过盟约。盟约保障了王国的繁荣与平稳，当有试图扰乱的事物时──例如别国想要向王国发动战争的时候，据传龙会站在王国这边。

只是现今已经没有「神龙」于危难之中拯救王国的事迹。因为这几百年来，从未发生过需要履行盟约的事态过。

真的是「神龙」的盟约保护了王国吗？这方面的讨论也开始传开来。

话虽如此，当王国与帝国的关系恶化到无可挽回的地步时，只要「神龙」有履行盟约，帝国就无法免于毁灭。

若真变成那样，那史泰德的行径就真的只能称是「亡国愿望」了。

史泰德到底相不相信有盟约存在呢？他的目的是要导致王国与帝国的关系恶化吗？假若都不是，那他的目的究竟为何？

「──如汝所知，余的身体耐不住决斗。因此决斗是由代理人来处理，这汝知道吧？」

史泰德边说边捡起掉在脚边的手帕，收进怀里。──许诺决斗。看著他这么做的特蕾希雅深深点头。

「帝国最强战士『八腕』库尔刚。帝国无人能够超越他。」

「而符合这等级的存在，王国仅此一人──」

言外之意就是在说「剑圣」，史泰德露出冷笑。

那笑容让人一眼就知道他的目标之一就是特蕾希雅。不过特蕾希雅却挫了他那达成阴谋的成就感。

「非也。非常遗憾，我有件事要告诉你。──『剑圣』不会应战。」

「……什么？」

「我已是因故弃剑之身。基于跟你不同的理由，我也是无法战斗之身。──所以说，我也跟你一样推派了代理人。」

「推派代理人？开什么玩笑。有谁能够担任『剑圣』的代理人……」

语气开始粗鲁，表达不会配合她这胡言乱语的史泰德却中断了话语。不是基于自身意志，而是因为置身在近距离的剑气中。

近在身旁──两股剑气高涨，卷起涡流，大桥转眼就转变为战场。

「──感激不尽。好敌手。能够遇见汝，吾很高兴。」

「住口。妨碍别人蜜月旅行，别以为可以活著回去。」

喷发的剑气互相冲突，交谈起来的是威尔海姆和库尔刚。就连与武力无缘的史泰德都因被两人的强烈斗气波及而倒抽一口气。

然后──

「汝来阴的，『剑圣』。」

「先滥用决斗规则的人可是你。而且，我想解开父亲的咒术。为此采取确切的方法──推派出比我更强的人应战是天经地义的吧？」

特蕾希雅抬头挺胸、正大光明这么说，史泰德这才看向威尔海姆，重新审视他。见他剑气勃发，和「八腕」为敌也毫不退让互瞪彼此，史泰德这才终于了解。

站在此处的长发剑士，确实是足以让特蕾希雅托付剑的有实力人士。

「你是说王国里头有名称足以匹敌『剑圣』的剑士？」

「毕竟是王国丑闻，所以似乎瞒著外国。──『剑圣』在终战典礼上与可疑人物对决，最后输了。」

「那不是不值一哂的流言吗……！」

声音之所以混杂著愤怒，是因为自己不屑采纳的流言竟然是事实，并因此感到焦躁。对此心情大好的特蕾希雅轻轻牵起身旁的威尔海姆的手，展现出自己对他的信赖。

「────」

下一秒，大桥上出现轰然低沉巨响。特蕾希雅迟了一点才发现那是从库尔刚的喉咙发出来的，更慢了一点才发现那是笑声。

库尔刚肩膀抖动，低声大笑。然后斗神瞪大眼睛说：

「夺走『剑圣』手中的剑，并娶她为妻的剑之鬼──『剑鬼』名为？」

「──威尔海姆•范•阿斯特雷亚。」

「剑气里没有一丝混浊，很完美的见面礼。史泰德，这男的无疑是吾之劲敌。」

「少擅自决定。」

决斗代理人已经不理自己，使得史泰德苦著一张脸，接著望向靠在一起的威尔海姆和特蕾希雅两人，叹气道：

「既然不是『剑圣』为了保全自己而推派的人选的话就没话说。不管是哪一个要成为『八腕』剑上的锈，对余来说都一样。余已接受决斗，不容他人扭曲这话。」

「你们那边赢了的话，想要什么？」

「不用。因为余是被挑战的人。哦，不过呢……」

这时，史泰德停下话，眯著眼睛看著威尔海姆和特蕾希雅。接著拍打站在身旁的库尔刚的背。

「虽然余无所求，但这样无从慰劳决斗代理人。因此，这样吧。就用代为决斗的代理人的愿望，作为余的期望。」

史泰德这么说，把在决斗中获胜的赢家权利让给库尔刚。对于雇主的处置，库尔刚挪动一只粗手，指了过去。

指头尽头是特蕾希雅──

「──吾要那个美娇娘。」

「──咦？」

「……啊～？」

库尔刚的要求让特蕾希雅和威尔海姆同时出声。

「她的美貌、能力和胆量，全都舍弃掉就太可惜了。因此，威尔海姆。在吾用剑砍死汝之后，美娇娘就是吾的。没意见吧。」

「刚刚才说我们在蜜月，你们是都没长耳朵吗……？」

强抢新婚人妻的宣言，让威尔海姆额头暴出青筋。肆虐的剑气掺入了他对对方的怒意，但对此库尔刚反而是狰狞一笑。

库尔刚身旁的史泰德满意地点头，说：

「放弃吧。这就是蛮族人的精英。对于向女人强行播种好延续自己血脉一事毫无丁点犹豫。因此才会钦点汝作为给他的奖赏。怕的话可以转身离开喔？就像汝父亲那样。」

「──不，我接受。」

「特蕾希雅！」

特蕾希雅堂堂正正接受，反而是威尔海姆动摇了。这也难怪。她对这场决斗的态度大幅改变，甚至不惜将自己整个人拿来做决斗的奖品。

不过她对威尔海姆摇头，说：

「父亲的命在他们的掌控中。而且，怎能只有不能战斗的我待在安全处呢。我就算不作战也会负起责任。」

「可是，万一要是我……」

「唉呀。」

说时迟那时快，特蕾希雅把自己的手指贴在威尔海姆的嘴唇上让他安静，然后朝著因事出突然而双眼圆睁的丈夫微笑。

「──不会有万一的。因为这世上再也找不到比你还强的人了。」

「────」

「你会保护我吧？」

「……嗯，那当然。」

改口发誓后，威尔海姆用带著野性的笑容回答。

「剑鬼」只要贯彻自我就行。彻底做到身为剑士和男人的职责。

意图想要抢走妻子的大块头，以及阴谋使诈伤了岳父的家伙。他瞪向这两个敌人，龇牙咧嘴道：

「我接受。──被我砍死，赤手空拳下黄泉去吧。」

12

──听闻有人决斗，大桥涌入许多看热闹的人。

在这个时代，决斗是不容他人侵扰的神圣行为，犹如仪式。

但是决斗的同时，对毫无关联的第三者而言可说是一种娱乐。要是有遵循正确的规矩，那就连卫士都不得妨碍决斗。对于只能远望干戈搏斗的人来说，就等于是在欣赏毫无危险性的表演节目。

因此一听到有决斗，大桥上就塞满了许多瞎起哄的人，以及来欣赏决斗的凑热闹人士。

不过他们这种轻松的期待，却在大桥上看到对峙的双方后毁灭殆尽。

「────」

双方没有口述前因后果，光靠弥漫的剑气就让这些人乖乖闭上嘴巴。

分别站在大桥两头的「剑鬼」与「八腕」。大家全都被他们的对立气势给吞没，连要发出声音都没办法。

「──那是把好剑。虽然光辉劣于阳剑。」

「是阿斯特雷亚当家选的剑，当然是好剑。」

「那么，『剑圣』选的男人本事也不赖啰。不过实在看不出来能对『八腕』造成什么威胁。那么瘦的男人是能干什么。」

「……不是本来想让比他还瘦的女人战斗吗。」

在这种状况下，并非决斗当事人却还能唇枪舌战的就只有特蕾希雅和史泰德两人。远观决斗的他们跟不知情的外人站在一块，彼此互呛。

「────」

「八腕」超乎常人的能耐，痛切传达给有「剑圣加持」在身的特蕾希雅。在特蕾希雅至今所遭遇的对手中，他无疑是「第二强」的敌人。

因此，当然也就相信「第一强」的丈夫一定会胜出。

「──威尔海姆。」

不是祈祷也不是祈愿，就只是怜爱地呼唤这个名字。

特蕾希雅知道：这是身为妻子的自己所能做的最好的事了。

「────」

听到身后的人呼唤自己的名字，威尔海姆闭上眼睛。

风声，鸟鸣，桥下潺潺流水声，来看决斗凑热闹的人们的呼吸和心跳声，将注意力集中在夹杂于其中、心爱的女人的声音上。

这声呼唤并非质疑威尔海姆能否获胜，更不是不安。

就像早晨在同一张床上醒过来时所呼唤的第一声。像是准备餐点时看过来的微笑。又似一同独处时突然趁隙扯袖引自己注意。彷佛在小争执的期间，脸颊红通通的惹人怜爱。恰似睡前互吻彼此时一样。

──就只是被呼唤名字。光是想到这点，「剑鬼」就被打磨得越来越利。

「吾要道出羡慕与感谢。现在倾注降临在身上的祝福让吾雀跃。」

「祝福？感谢自己的死期？你这人真怪。」

睁开眼睛，在朝阳下的大桥正面──敌人就在那儿。

脱去罩住全身的袍子，裸露出纯为战斗而进化的异形样貌──高达两米的蓝色躯体，总共有八只手的怪物战士。而安放在异形身躯上的头部，简直就是量身打造的战鬼样貌。

「因为有八只手就叫『八腕』……多手族还真方便啊。」

「其实没有外表看起来这么便利。并没有因为手的数量增加，能做的事就跟著增加。最麻烦的地方，就是太过引人注意。」

「名人太过醒目会被盯上吗？」

「恰恰相反。──看过吾的样子后还攻过来的人少之又少。十分无趣。」

战士的守则就是为了战斗而活。这点倒是十分感同身受。

除了挥剑，当然也渴求力量。过去的威尔海姆也在「他人」身上追寻卓越剑技，只不过那已是过去式。如今自己追求挥剑理由的对象除却自己之外，也绝非「他人」。

「──没什么话好说的。时间也很宝贵。你就早早赴死吧。」

「享乐的时间就该好好享受。机会少的话就更是了。」

威尔海姆拔剑。「剑圣」家族当家所看上的宝剑，在斗争气息下闪著银色光辉。

库尔刚也同时策动四对手臂，拿出背著的四把大刀──厚重的切肉菜刀，彰显帝国最强战士的威武。

「这叫鬼庖丁。」

「我没问。」

「是要夺去你性命的武器。知道不会有损失。──你那把剑呢？」

「────」

思考了一下，但是马上视之为无趣问题。

「──阿斯特雷亚。」

说完后就立刻往前踏出步伐。

──银华乱舞的战火平静却又炽烈地开启。

13

这场决斗，以同为剑士之间的战斗而言，费时异样地长。

「────」

在势均力敌的战技下，交锋的次数以加速度增生。剑戟声响不绝于耳，鲜血飞散，大桥碎裂，踏响都市的脚步在水面产生波纹。

互相斩杀的柔与刚──不，说互相削切的轻与重比较适合。

威尔海姆在大桥上自由奔跑，为求一击必杀而使出锐利斩击。相较之下，库尔刚一直站在一开始的位置，挥舞刚剑迎战「剑鬼」。

虽然以轻与重来表示，但被称作「重」的库尔刚剑速不容小觑。常人所没有的八只手轮流挥舞四把大刀，动作像是暴风一样狂乱。若是衣角被掀起的剑风卷入，猎物瞬间就会化为碎屑。

之所以没有落得那样的下场，是因为威尔海姆的身法卓越。

「────」

假如只是无所作为地来回奔波，那体力迟早见底。速度一旦下降，就会避不开鬼庖丁的剑锋吧。但是威尔海姆的武器并非速度，而是在千钧一发之际穿越鬼庖丁攻势的胆量与步法。

不是以速度，而是以技术与胆量来扰敌，持续使出锐利斩击。

──可是，双方都没能使出决定胜负的攻击。

双方战术已定，并高度互相咬合，结果造就了这场长时间战斗。假若战技有些微差距，或是武器等级有别，就算不是如此，只要战斗方式一致，应该就能在一回合内决胜负。

但是战况没有演变成那样。决斗已经进行了上百回合。

「────」

锐利吐气，活用速度使出的一击被厚重刀刃承受，紧接著来自死角的劈斩就倾斜身子闪过。旋即银光迸发，却仅止于切破对手胸膛皮肤，还产生空隙，导致肩膀被乱拳给打到。

「咕……！」

身体被拳头给揍飞后，对手又接连补上横砍，威尔海姆靠跳跃躲过。而就在逃至空中的那剎那──寒颤窜过身子。

「──你以为躲得掉吗，『剑鬼』。」

库尔刚一只手抓住往上举的鬼庖丁的刀身，开始蓄力。原本就很粗的手臂肌肉膨胀，这是「八腕」要使出全力一击的前兆。

在空中无处可逃，回剑防御──不，那攻击是无法防御的。要是承受的话连肉体都不会有剩，将性命斩除得一干二净的必杀一击即将攻来。

因此，威尔海姆舍弃防御──

「──炸开来吧，『剑鬼』。」

必杀一击甩开声音，直接袭来──

──感觉在那瞬间，世界是鸦雀无声的。

「──威尔海姆！」

但其实并非如此。

高喊声，可爱的嗓音，震动心灵的声音，化为斗志、活力和战意。

舍弃防御，将剑打直，好迎击即将往下劈的攻击。──假如库尔刚在那瞬间使出的劈砍为雷击，那威尔海姆的突刺就是风牙。

──银光以大桥为中心，开花似地华丽炸裂开来。

冲击交错，血雾喷飞。被剧烈攻势碰到的威尔海姆飞了出去。全身骨头作响，被大剑剑腹打中的左半身发出哀号。肩膀到锁骨，肋骨到腰骨，分不出骨头从哪里断到哪里。

不过库尔刚付出的代价也不小。

「──厉害。」

库尔刚的庞大身躯发出像是呢喃的沉吟，单膝跪地。

斗神的位置依旧，不过脚却浸泡在自己的血泊中。大出血的原因来自右边的第三只手──在突刺下被连根斩断。

「奏效、了吗……」

判断无法躲开对方斩击的当下，威海姆以减轻伤害为优先，并且给予对手最大程度的痛击。利用突刺让劈砍的斩击偏离轨道，反过来利用对方踏步过来的姿势夺去他一只手。

如此一来，库尔刚不能使用的就有两只手和大刀一把了。他受的伤很深，没法轻易动弹。虽说威尔海姆也一样，但对方得凭一己之力站起，自己可不是。

身后的女子声音带给自己力量。就连现在力量都无限地从心头深处涌出。

就这样，战斗来到第二幕──正当这么想的时候。

「──到此为止吧。真是的，都不乖乖照著棋路走。」

「啥……！？」

惊愕声是来自看著决斗的某人──不，是大家一齐发出的。毕竟这种违反决斗流程的行径不可原谅。

拍打外套衣襬的史泰德，站在跪地的库尔刚身旁。这种介入决斗的行为，正是不可违反的禁忌之一。

「这可是决斗耶！？你是想怎样！」

「都半死不活的身体了还吠什么。在这边失去棋子的话会乱了之后的路。因此，这次就在这里拉下幕廉。决斗以余们输了告终。拿去。」

立剑试图起身的威尔海姆怒吼，史泰德嗤之以鼻。

然后他脱去小指头上的戒指，扔给特蕾希雅。被眼前的事惊讶到目瞪口呆的她反射性地接下。

她掌中是「朱色小指」──咒术的源头，被爽快地扔了过来。

「决斗算汝们赢，余们交出戒指离开。还有什么好说？」

「问题在贯彻道理的方式。你这王八蛋，到底把剑士……把战士当什么了！」

「在余眼中就是一枚棋子，战士不过就是能拓展疆土的道具罢了。此行也算是收获颇丰，因此余老实退下。什么呀，用不著担心。」

俯瞰愤怒不已的威尔海姆，史泰德朝他伸出右手。小指空荡荡的，但是其他四只指头却都还有戒指。

「──以后还可以用同样的作法来玩。玩兴可没结束。很期待吧？」

「混帐东西……！」

「开玩笑，耍汝的。尽管笑吧。因为不只右手，左手也有喔。」

说完，他亮出原本遮掩的左手，上头也戴满戒指。威尔海姆气到说不出话。看到他的反应，史泰德开心地将左手伸向脚下。

然后──

「被王国军牵扯进去很麻烦。因此，要开溜了。」

他说出这句话的同时光芒乍现，下一秒石砌大桥就突然融化了。──石材简直就像化为沙子一样消散，在大桥上的所有人全都掉进下方的河里。

「可恶、嘎啊……！」

吐出这话的威尔海姆在脚底立足点融化之前跑了起来，奔过接连化做沙的大桥，在一片哀号声中一鼓作气冲向特蕾希雅。特蕾希雅也朝跑过来的威尔海姆伸出手，帮助拼命的丈夫。

下一秒，抱住妻子纤细的身体，威尔海姆纵身一跃，逃离融解垮落的大桥，踩上还留有形体的都市地面，吐出一口气。

「威尔海姆！」

「我没事！比起我，戒指……」

「在、在这里。拜托了！」

特蕾希雅亮出手掌上的戒指，并轻轻扔向空中。视线追著轨道，威尔海姆手中的宝剑一闪──宝石毫无抵抗被斩为两半。

顿时，原本闪动的光芒一暗，彷佛被日照烧毁一样消失。

「这样一来，父亲就得救了吧？」

「要确认就只能回治疗院看看了。……但是……」

威尔海姆转动脖子望向崩塌的大桥。那里已经在开始营救坠河的看热闹观众，而乱成一团的现场里看不到库尔刚他们的身影。

他们不可能溺死，一定是逃脱了。要追上他们，逼他们吐出真正目的的机会，就只有现在了──

「不，我不想再跟他们扯上关系。先去、治疗、院……」

「威尔海姆！？没、没事吧？能动吗？」

「不用、担心。只是、血流得有点多，有点头晕罢了……」

「那才叫人担心吧！？够了，我来搬你！」

失血过多开始晕眩的威尔海姆，身体被特蕾希雅雄壮地抱起。感觉画面很难看的威尔海姆试图抵抗，却逃不出她的掌握。

「父亲也是我送去治疗院的。好了，抓紧我。……是说，抱著你跑步，跟我是『剑圣』无关喔？」

「……拜托不要摇晃。」

领悟到说什么都是枉然，威尔海姆放弃抵抗，委身给妻子。视此为信赖的特蕾希雅健步如飞，以无法想像是少女的速度穿过都市。

──在治疗院入口听卡萝转达贝尔托平安无事，因此哭了出来结果放手摔到威尔海姆，是几分钟后的事了。

14

「难得的蜜月旅行，真不想去相信发生了这种事……」

这么抱怨的是来看躺在病房床上的两人──照顾威尔海姆和贝尔托、鼓著红通通脸颊的特蕾希雅。

在决斗骚动后，身受重伤的威尔海姆立刻住院，演变成跟贝尔托同一个病房的局面。而说到一度被咒术侵蚀性命，被认为在鬼门关前游走的贝尔托──

「意思是，比起蜜月旅行还是以爸爸为优先……原来我对你来说是这么重要的存在。对此我很自豪，特蕾希雅。」

「父亲，假如不想被人用力按尚未痊愈的伤口的话，就别讲那种话。」

「咦咦咦咦咦！？为什么！？你不是很爱我吗！？」

「敬爱您跟有没有生您的气不能相提并论。欸，威尔海姆，跟父亲同病房真的不要紧吗？会不会难受到伤口裂开？」

原本左手抚须还莫名威风凛凛的贝尔托被痛斥。撇下因此垂头丧气的父亲，特蕾希雅担心地问。威尔海姆苦笑。

「没事的。面对父亲大人，只要习惯了就没那么难受。」

「想用那种话来博得我的好感是没有用的。因为我跟你为了争夺特蕾希雅，这辈子都注定要不断决斗。」

「我早就是威尔海姆的人了，是父亲您输了。」

特蕾希雅的爽快回答轰然击沉贝尔托。父女的互动照旧，不过特蕾希雅对此很满意。因为她看起来很开心，威尔海姆也觉得自己受了重伤、中断蜜月旅行也算有了价值。

「特蕾希雅大人，龙车差不多要到了。要前去迎接吗？」

「啊，嗯，就这么办。」

打开病房门的卡萝这么说。在她的呼唤下，特蕾希雅起身，拍拍裙襬走向门。

「龙车？是谁要过来？」

「那还用说。虽然很想在威尔海姆能动以后就出发，但是留下父亲实在让人不安。……所以说，就请母亲过来了。」

「咦咦咦咦咦咦！？叫媞舒雅来！？不要，好可怕！我一定会被凶的！」

「没错！一定会被凶！」

特蕾希雅毫不留情地朝著在床上扭动身体的贝尔托如此宣告。然后向著害怕的父亲叹气，接著目光温柔地望向威尔海姆。

「那我出门一下子。威尔海姆，待会见喔。」

「好。就先跟卡萝去蜜月旅行吧。」

「说、说什么蠢话！跟特蕾希雅大人蜜月旅行，这种事，那样子，嗯……」

感觉也不赖。「讨厌！」卡萝的这种反应惹来特蕾希雅害臊回应，接著就带著她离开了病房。少了闹哄哄的探病访客后，被留在病房的就只剩下威尔海姆和贝尔托。

「可别以为这样就赢了，威尔海姆。我可是帮特蕾希雅换过尿布的喔。」

「我也帮她换过衣服。」

「咕呃啊！」

被言语之刃切割的贝尔托整个人后仰倒下，然后就这样保持横躺，小声自言自语。

「唉……女儿被女婿抢走；蜜月旅行跟女儿会合的事又要被妻子骂；当成女儿的孩子瞧不起我，叫我要有所节制，我到底该去哪里才好……」

「父亲大人，别讲那么消沉的话。其实您的所有行为全都没法让人嘉许……」

「连女婿都落井下石……」

「不过，您为了家人挺身而出的样子十分勇猛，这是特蕾希雅说的。我跟敌人交手过，所以知道要面对他需要多大的勇气。」

脑子里浮现库尔刚的威容。他的斗气强大到连自己都紧张到颤抖，与他对峙的贝尔托根本是在自杀。

而让贝尔托做出这种有勇无谋行为的，就是骄傲与矜持。

「父亲大人比我还先跟他交战过。很伟大喔。」

「……可是却因为戒指的事给你和特蕾希雅添麻烦。你也受了伤，也因此打断了旅行。」

「会这样单纯是因为我能力不够。父亲大人用不著在意。而且……」

「而且？」

「听说父亲大人因为对方侮辱我而动怒。所以说……没关系了。」

两人之间出现一段沉默。双方八成都知道那并非害臊或尴尬。

因此，最后由贝尔托的噗哧一笑划破沉默。

「知道了。既然如此，那就这样吧。我跟你之间互不相欠了，可以吗？」

「……不，以贡献度来说的话我比较多。」

「可以吧？」

「……好吧。」

被重复这么问，威尔海姆只好吞下各种情感。接著视线突然瞥向贝尔托身旁的柜子，于是想起什么而敲手。

「虽然不知道母亲大人会对父亲大人说什么……但是有那个。」

「嗯？」

「只要送她庆祝结婚纪念日的发饰，场面就会稍微温和些吧？」

从柜子里取出来的，是在思文商会选购的发饰。

由于史泰德搅局而没时间选取的赠礼。后来由特蕾希雅和卡萝挑选，再托给威尔海姆转交给贝尔托。

「是特蕾希雅她们挑选的。所以说不定跟岳父每年的作法不合。」

「哦，她们啊。多么……虽然面对面说不出口，但她们都是我可爱的女儿。」

威尔海姆递出发饰，贝尔托又朝自己感动的方向解释事情。朝这样的他苦笑，将发饰交到他手上──

「父亲大人？」

「……不妙，糟糕。」

由于动作不自然，贝尔托手中的发饰落地。他转动身子想要拾取，最后在吐息的同时，才用左手捡起发饰。

不是用他的惯用手右手，而是左手。──右手似乎无法动弹。

「……好像是咒术的后遗症。」

贝尔托边看著不会动的右手，边对瞪大眼珠的威尔海姆这么说。

「其实本来是四肢要腐烂掉落的，是藉由将污染物集中在一处才将损害压抑在一只手上。那名术师很优秀。地方上原来有技术那么高明的术师，之后可要跟王都禀告推荐才行。」

「父亲大人牺牲了惯用手？可是，那样……」

「──我说过了，威尔海姆。我们之间互不相欠。你没必要负担这个重担。」

被他用左手拿发饰戳，威尔海姆只好闭嘴。这才了解方才贝尔托那番话的真正意思，羞耻心剧烈袭来。

贝尔托不让女儿和女婿负起自己右手有后遗症的责任。为此他还用恶作剧的态度强迫威尔海姆同意。

一无所觉的自己真是丢人现眼，同时怒意涌上心头。

逃掉的帝国人──对史泰德和「八腕」库尔刚的愤怒源源上涌。将来必定要洗刷这份耻辱。一定要赎罪。威尔海姆在内心发誓。

「这次的失败……」

「嗯？」

「这次的失败，我一定会负起责任的。岳父，我对您的手发誓。」

为了眼前的男人，威尔海姆意欲立下灌注强烈剑气的誓约。

但是贝尔托却笑道：

「……不用发那种誓。用不著啦。我不想让特蕾希雅担心。与其发这种誓，不如重复发誓要让特蕾希雅幸福。」

「什……」

被淡然地这么说，令威尔海姆说不上话。而贝尔托又朝著他一脸骄傲地补上一刀：

「要对特蕾希雅保密。这是男人之间的──家人之间的约定喔，威尔海姆。」

语毕，他边笑边和威尔海姆定下不可毁约的约定。

──之后，在贝尔托过世之前，都从未让女儿发现自己的惯用手出了问题。

因此后半辈子，每当威尔海姆被人问起值得尊敬的剑士时，他始终毫不犹豫地说出「贝尔托•阿斯特雷亚」这个名字。

于此同时，在聘可塔特被人称为「银华乱舞」的决斗一役后，威尔海姆后来再次遭遇了孽缘颇深的仇敌。

──「破灭愿望」史泰德•佛拉基亚，和「八腕」库尔刚。

他们与威尔海姆围绕著特蕾希雅，再度掀起将亲龙王国露格尼卡拉入混沌的战斗──「剑鬼战歌」将在那时开始。

《完》

** 『剑鬼恋谭──中场休息的情侣们』

1

──格林•法先到现在都还记得自己坠入情网的瞬间。

筋疲力尽的格林瘫倒在战场一隅。

一手拿著破剑，僵硬的手指不肯放手。手上还留著真确的触感──亲手割断原本是朋友的人的脖子。那个手感还鲜明地残留著。

「────」

这里是地狱。战场不论何时、不管去到哪里，都只会是地狱。

事到如今才后悔自己做了愚蠢决定。唯恐在穷乡僻壤继承家业后没没无闻活一辈子，所以选择离开故乡。

无聊的英雄愿望，和无法割舍、惨不忍睹的执著，结果造就了这个心境。

死后化为尸兵，眼神空荡荡的朋友托尔塔的脸烙印在眼底。不是怜悯友人的死，而是不想死，自己是抱著这种利己的感情挥剑。

这件事，让自己觉得双手逐渐被尸水和血给污染──

「──我对你另眼相看了。」

蹲伏的时候听到这声音，澄澈的声响摇晃心灵。

「────」

忍不住抬头。她就站在蹲坐在地的自己面前。

整齐的美丽金短发，表达直率感情、宛如宝石的碧蓝眼睛，威风八面的凛然姿态，自然地就在看到她的人心中留下严肃印象。

不是楚楚可怜，比较适合美丽这词汇的少女。她名叫──

「──卡萝、小姐。」

「嗯。我们都吃足了苦头。那个……格林。」

用沙哑的声音道出名字后，少女──卡萝嘴唇放松，浅浅一笑。顿时，严肃的印象柔和松弛，展露出符合年龄的少女面容。

卸除轻铠，放下爱用长剑的卡萝看起来跟娴熟女剑士天差地远。当然，要将之定义为日常一景非常勉强。战场遗迹刮起孕著血腥味的干风，卡萝本身也受了伤。

没错，卡萝应该是在战斗期间被敌人所伤。

「擦伤而已。武家出身的女儿，不会因为这种程度就大呼小叫的。」

「这样啊……」

「嗯，是的。还有……」

靠脸色读取内心并回答格林疑问的卡萝视线朝下。她一双碧眼盯著格林僵硬得紧握著剑不放的手。

剎那间，复杂感情掠过她的瞳孔，她当场蹲下。

然后──

「──你是第一次下手杀人吗？」

卡萝边问边触碰格林的右手。雪白纤指松开他僵掉的指头，格林知道自己的关节开始一点一点地在活动。

「那、那个……」

「用不著焦急没关系。慢慢来也无所谓。谁都会遇到这种事。更何况对象还是自己的朋友，就更糟糕了。」

「────」

发抖的话语被封住，格林难为情地低下头。

这次是自己第三次站在战场上了，而且终于第一次杀人。假如已死之人也能算在里头的话。

而且这三次来，每次格林都后悔自己上战场。

自己的性命受威胁，他人的性命被轻易摆布，在盈满呛人作呕血腥味的战场上，格林每次都有满满的后悔。

不该来这种地方的。每次都这样后悔──

「──这是十分有勇气的行为。」

卡萝笔直凝视紧咬牙根、懊悔不已的格林。

「咦……」

「你亲手用剑，让变得那样面目全非的朋友恢复永眠。虽说是下意识的行为，但发生的事不会改变。是了不起之事。」

卡萝像在说服般对著愕然的格林这么说。她的嗓音和内容都让格林屏息，回顾自己的作为。

──干得好。自己做了能够被人这么称赞的事吗？

「至少，你解放了死后受辱的友人，还推了在战场一同战斗的我和战友最后一把。……虽说那个无礼男子的活跃让人火大。」

彷佛又读出了默不作声的格林的内心，卡萝说道。

对此格林瞠目结舌，卡萝微微一笑。

「我不应该说看错你了比较好吧。」

「……没那回事。」

「是吗。那就好。……啊。」

卡萝安心地微微吐气。仔细看，刚好是原本困扰自己的手指脱离剑柄，僵硬紧握的手被松开的时候。

手自由了，剑被卡萝抢走。然后卡萝拿著剑，准备要站起来。

「──这是？」

「咦，那个，啊──」

相较于声音平静的卡萝，格林则是吓了一大跳。自己做出的事把自己吓到脑袋混乱了。──格林抓住卡萝的手，阻止她离去。

简直就像惋惜要离开的她，一把抓住方才接触过的手指。

「那个，被做这种事……」

「谢、谢谢你！」

「────」

「……只是想跟你道谢。」

在温暖即将脱离卡萝的表情的瞬间，千钧一发之际发出了声音。声音跑出来化为感谢之语，但很明显的是笨拙的藉口。

不过对于格林的这番话，卡萝圆睁双眼。

「……你真是奇怪的人耶，格林。」

垂下娥眉，卡萝朝著格林绽放笑颜。

──就是在那一瞬间，格林•法先被卡萝•雷玫迪斯掳获了心。

2

在那之后，置身战场的恐惧对格林来说并没有变得薄弱。

战场是地狱，这个认知也没有改变。没有不是地狱的战场，没有不畏惧的战斗，没有应该白白葬送的性命，还有无数死去的性命。

战场总是惹人嫌，格林从未觉得自己适合这里。周围的人也众口一致、毫不留情地说自己不适合。

格林也知道那是一种体贴。

不适合的人，无法克服恐惧的话，就无法在地狱持续抗战。要是格林开口说要退役，也不会有同伴挽留吧。

他们只会用安心的表情，目送格林回去故乡。

──除了威尔海姆•托利亚斯这个人以外。

「你还活著啊，胆小鬼。有空摆出死人脸的话，还不如快点消失。」

在战场大为活跃的「剑鬼」只要一看到难看挣扎的格林就会口出恶言。

他的话没有错。威尔海姆不是基于温柔或体贴，而是发自内心认为战场上不需要弱者，所以觉得格林碍事。

「我才不会消失咧！威尔海姆，你为什么每次……」

「我可没空跟你吵这个。──敌方增援来了。」

根本不听格林反驳，威尔海姆就提起染血的剑冲进敌阵。讶异他那如风的速度，格林抓抓头，喊：

「啊啊，可恶！慢著！等我啊，威尔海姆！」

追著背影冲进有无数敌人蠢动的战场，高举盾牌挥舞。

恐惧没有消失。自己不适合战斗。战场随时随地都是地狱。

尽管如此，格林也没有逃离战场。他没有逃跑，一直追著走在前头的战友的背影。──哪天没得追了，才是最恐怖的事。

「做出那种事，命有几条都不够的。」

卡萝来探访包扎伤口的格林，傻眼地这么说。

那是在「亚人战争」期间，卓格夫队和亚人联军发生小规模战斗后。在威尔海姆的奋战下战况一面倒，队上的伤者也不多，可以说是赢得漂亮。

而自己就是那为数不多的伤者之一，令格林大感丢脸。

「……看不下去了。借我。」

「啊，那个……不好意思。」

格林用非惯用手笨拙地包扎惯用手，结果被卡萝抢去了包扎主导权。她俐落地用绷带裹住格林右肩的撕裂伤。

从开始到结束仅仅几秒钟，突显出格林的笨手笨脚。

「这是习惯问题。用绷带包扎自己的惯用手，我也曾吃过这种苦头。」

「……我这么好懂吗？」

格林摸摸自己的脸，这么问道。听了之后卡萝有点愣住，然后点头：

「是的。怎么说呢。……很不可思议……对，很不可思议的，我就是觉得看得懂你在想什么。说不定……」

「说不定？」

格林探出身子，期待卡萝接下来要说的话。而面对这样的期待，卡萝微微歪头说：

「那么容易让人看出脸色，不适合战斗……」

「哦，是这样啊……」

格林虚脱，一屁股坐在地上。卡萝面露诧异。见她反应如此，格林苦笑道：

「没有啦。我很常被人说不适合打仗。我本身也有自觉。」

「那为什么你还要上战场？」

「为什么……呢。」

被问了这么理所当然的问题，格林蓦地看向远处。卡萝顺著他的视线转头望过去，然后──

「──是那男的，跟托利亚斯有关？」

格林的视线尽头，是总是在最前线挥剑却犹能生还，而且连个擦伤都没有的「剑鬼」。扑克脸少年看起来百般无聊，阖上双眼治愈疲惫。

卡萝的话语里微微带刺，格林苦笑。

「要是能说无关就好了，但八成有关。……虽然讲了这种话，但我不想被卡萝小姐讨厌。」

「────」

「我是不想被那个只有剑术可取的无赖给扔下。」

重新化做语言后，这种愚蠢动机就连自己都想笑。

威尔海姆的生存态度十分偏激，走在不依附任何人的孤傲道路上。那就是让他之所以为他，并将强韧实力化为主干的原因。

可是，格林被孤傲的他救了三次命。

「威尔海姆都没有感觉吧，也不觉得有借我人情。」

「既然如此……」

「可是，我不一样。我被他救了。」

恐惧无法克服，还是一样讨厌战斗，战场随时随地都是地狱。

但是在地狱战场救了格林的，是连当事人都没自觉的战友。

在宛如地狱的场所重复惹人厌的战斗，即便心灵被恐惧折磨，但唯有战友守护了自己的身后、隔壁和性命。

「单纯跟他道谢只会被他耻笑吧。他一定会说少拿那么无聊的藉口亲近他。所以说，我要让他了解。」

「了解什么？」

「有朝一日，因为有我……因为有战友而得救，我要让他那么想。」

就算诚心诚意地感谢，也无法真切传达给对方。既然如此，在自己的感谢打动对方的心之前，就等待机会吧。虎视眈眈地一直等待。

「等到他那么想的时候到来，我的感激应该也能传达给他了。到时，我就能说跟他互不相欠。──那是我持续战斗的理由之一。」

「────」

「啊……」

听到格林深藏不露的野心，卡萝惊讶到说不出话来。见到她的反应，格林垂下视线，为自己的坦白感到可耻。

怎么让人听这么卑微又婆婆妈妈的心愿。可是卡萝背叛了格林的后悔，几度颤抖嘴唇，最后说：

「……我又错看你一点了。」

「啊，咦，呜……那个，我才觉得抱歉，讲了这么丢脸的话。」

「不，完全不会。──你认为那男的会改变？」

原本要为羞耻的告白致歉，但讲到一半就中断。因为眼前的卡萝双眸绽放真挚的光芒，掳获了自己的心。

「────」

她静静地等待格林回答。

她似乎希望从格林身上得到不一样的答案。就像是紧抓一丝希望，又像是寻求支持。

顿时，初见面时的对话掠过格林脑内。──卡萝在侍奉某人，并代替主子参加内战。

该不会，她将自己对「某人」的心情重叠在这个问题上吧？

些微痛楚折磨胸口，不过格林抓住胸口，无视痛楚。

「是的，我认为会改变。不管是任何人事物，只要花时间都会改变，只要这么希望的话。」

「────」

「事实上，我凭这个信念，和威尔海姆比以前更能说上话啰？说不定哪天我们会一块去喝酒呢。」

刻意带著玩笑口吻对卡萝这么说。那不过是逞强和虚张声势。为什么这么做？因为看到了卡萝眼中的变化。

卡萝美丽的蓝眼原本充满不安，现在一扫而空。

她对重要的人怀有迷惘，而自己的话语帮忙去除了她的迷惘。──做那什么蠢事。格林知道战死的托尔塔在脑子里厌倦耸肩。

这根本是在袒护可能是情敌的对象。

「……会变的。只要花时间，只要希望的话，谁都会变。」

卡萝反刍格林勉励的话，声音逐渐恢复力气，最后加强呼吸，笔直凝视格林的眼睛。

「我也……」

「咦？」

「我也这么希望。要是你的愿望能达成，我也会很高兴的。」

脸颊泛红，眼中带著希望，卡萝这样告诉格林。

「────」

她的表情和眼神，让格林感觉自己的心跳前所未有的快速。于此同时又拼命地劝诫自己不要误会。

她指的一定是其他事。她原本就有倾心的对象。不过只是在战场上打过几次照面的自己，别对这么漂亮的女性有非分之想──

「唔……又来了。」

格林垂下快要红起来的脸，脑袋一团混乱时，卡萝突然这么低语。抬头一瞧，她正往后看，方才的表情已经转为严肃。而让她变成这样的答案很明显的是正在和威尔海姆对话的修长女子。

「梅札斯大人又跟那男的扯上关系……」

卡萝边说边拍大腿，站了起来。

带著敬称称呼的，是她目前保护的宫廷魔导师罗兹瓦尔•J•梅札斯。对方是个打扮奇特、言行也很怪异的人，会现身在经常转战激战区的卓格夫队里，通常都是要来调侃逗弄威尔海姆。

是个游走在灰色地带、问题又多的人，但多亏了她的鲁莽，在战地跟卡萝打照面的机会才比较多。因此格林心中是偷偷感谢对方的。

不管怎样，那两人凑在一起让卡萝心情大受影响──

「抱歉，格林。我得去工作了。」

「不、不会，哪里！我没事的。我已经充分享受了。」

「────」

格林回答得莫名其妙，让卡萝眯起眼睛。但也只有一瞬间，接著她望著格林身旁倚墙而立的大盾。

「你想学习盾牌的使用法吗？」

「……卡萝小姐？」

卡萝口气认真，所以格林也望著自己的盾牌反问。

「格林，假如你是真的要参加这场内战到最后……或者说，还要跟著托利亚斯或卓格夫卿的话，那你现在这样会很危险。」

「────」

「因此，如果你有这个意思，那我来教你盾牌的使用法。那个……怎么说呢。虽然我其实也还不是非常熟练就是了。」

「──！真的可以吗！？」

没有请求就突然出现的建议，让格林几乎是从地上弹了起来。这反应吓到卡萝，但她还是立刻点头。

「是的。那我们就都空出时间吧。如果在王都，应该是有休息时间的。」

「好、好的，非常感谢。请你多多指教！」

不停低头鞠躬，深深感谢卡萝。当然，格林并没有误会卡萝的想法。她终究是善良才这样建议。

即便如此，能跟心仪女性共度时光，以及想要实现改变战友的野心──能够让两边都有进展，他十分欢迎。

没错。格林握拳，开心不已的时候──

「另外，或许这是我多管闲事。」

「是？」

「──我侍奉的是女性。还请不要误会。」

就这样。说了这些，卡萝就转身走向威尔海姆他们那儿了。然后高声介入正在吵著什么的两人之间。

不过，远眺他们的格林，拼了命才理解刚刚被说了什么。

「不、不可以……误会了……」

其实早就误会了吧。唯有这股混乱继续困扰著脑袋。

──感觉自己这样的困惑，被脑中的托尔塔用讨厌的表情给嘲笑了。

3

莫大的感激，对未来的期待，以及些许的私心。暗藏了这些心情，两人的私下碰面就此开始。

表面上是为了让自己幸存而去学习盾牌的使用法，但老实说那段日子非常惨烈又严苛，说特训还比较适合。

「那边！」

「好痛！好痛好痛好痛！卡萝小姐，很痛！」

「在战场上可不是痛就了事了！就在刚刚，你的手脚全都没了喔！」

手持训练用木剑，朝著格林手脚一阵痛打的卡萝破口大骂。她脚边是盾牌脱手、痛到蹲下来的格林。

将长长的木剑如手脚般灵活操纵，卡萝用变换自如的剑术玩弄格林。肉眼追不上剑尖平滑的动作，被痛打了十几遍后身体到了极限。

「大致上变得不错了，但还是有很多多余动作。这样下去，哪天遇上强敌时会无法应付，只能等著被砍。」

说完，卡萝坐在格林身边。她轻吐一口气，擦去额头和脸颊的汗水，用舌头湿润嘴唇。

连这些举动都充满高雅，格林看卡萝的侧脸看得入迷。

卡萝像这样陪格林训练已经有一段时日。约在王都的练兵场见面，格林接受卡萝一对一特训好几个小时。

盾牌操作得不错，波尔德有这样夸奖自己。把话听进去的格林想要钻研盾术走出自己的路，但果然还是一堆毛病。在卡萝看来就是满满的空隙可钻，要是在实战的话，脑袋早就掉了千遍吧。

「我有观察，你在战场上的动作变得很棒喔。」

「啊～那说不定是多亏了脖子上的奇妙感觉。」

摸摸自己的后颈，格林对卡萝陈述自己的假设。

脖子的感觉──其实格林也不明原因，但那是感知危机的奇妙能力。在战场上遇到敌人或感受到敌人的气息，格林的脖子就会毛骨悚然。仰赖这个能力的话，盾牌比起剑术更能让自己活下去。

当然，要是没有卡萝提升自己的技术底蕴，那就会有很多碰不到的领域。

「总觉得心情很复杂。也就是说我的干劲远远比不过实战。」

「没、没那回事！只是，那个，怎么说呢，呃──……」

「只是玩笑话啦。请不用那么慌张。」

慌了手脚的格林让卡萝微笑，温柔地看著他。在视线中抱头的格林难为情地说：「这样啊……」

自己的心情八成早就被她看透了。尽管如此，她还是像这样按照约定来训练自己，是因为卡萝觉得这样也不坏，还是仅是守诚信呢？

若不是守诚信的女性，就不会陪自己到现在了。尽管格林明白这点。

「……真是敌不过卡萝小姐呢。」

「格林？你刚刚说什么？」

「呃～就是不管过多久都还是防不住卡萝小姐的剑，说不定是因为我的脸色被看光光的关系。」

不小心说出口的喃喃自语，格林用笑脸和藉口带过。接受这说法的卡萝理解吐气，说：

「原来如此。确实格林的表情从以前就很好看懂。说不定对我来说你就是很好懂的那种人。……我们可能很合得来。」

「咦！？」

「只是说说看而已。……你的脸真的很好懂。」

朝著惊讶的格林留下戏弄眼神，卡萝用力站起，然后朝仰望自己的他伸出手。

苦恼该不该握住手的格林，最后下定决心握住。

然后──

「──假如是你，我觉得不用听你说话也懂你在想什么呢。」

4

为了这句话，冲进病房的卡萝不断向格林道歉。

「对不起……！对不起，格林……我……！」

她靠著床，哽咽地向格林道歉。听见她悲痛的声音，格林开口想要阻止她哭泣，但是──

「────」

张开的嘴巴只透出沙哑吐气，无法纺织出具有意思的话。

──在爱西亚湿地地带的攻防战，是「亚人战争」中前所未见的大战。

身为卓格夫队一员参战的格林，遇上亚人联军的首领利布雷•菲尔密，整个队伍被卷进激烈混战。

利布雷使起双头剑来畅快淋漓，在战况快结束的时候挖开了格林的喉咙。一击就挖去了发声所需的器官，格林因此失去声音。甚至被治疗院的术师断言这辈子都没法说话了。

卡萝深信自己对他的伤有责任，因此非常悲伤。

只是一句玩笑话而引发这样的事态，让她懊悔万分。

「──格林？」

抽抽搭搭地哭，沙哑的声音呼唤自己的名字，但格林只是微笑。

卡萝就在眼前，像这样平安无事。他对这件事感到开心。

确实没法说话很难过。这辈子再也没法呼唤她的名字。即便如此，只要没在那个宛如地狱的地方失去她就够了。

──因为在那场战役失去了一名战友。是一向对自己照顾有加的恩人。

战场夺走了他。因为自己能力不足害同伴死去。正因如此──

「──啊。」

──你没事真是太好了。格林发自内心这么想。

这样的想法，擅长判读格林感情的卡萝立刻就看穿了。她慢慢撑起身子，用湿润的双眼凝视格林。

不管看多久都不会腻的漂亮脸蛋。哭湿的双眸凝视自己的理由，格林认为自己应该没有误会。用不著找藉口了。

不如说，他付诸了行动。格林拉近她的身体。

「──！」

顿时，卡萝一脸惊讶，却也毫无抵抗地倒进他胸膛。然后格林抬起她的脸，像啃咬一般占领她的唇瓣。

没有抵抗。

──我爱卡萝。假若嘴唇分离后，她能看穿这个表情就好了。

边这么想，格林边贪婪抱紧眼前的身体。

5

在那之后时光飞逝，格林和卡萝也遭遇了许多事。

决定「亚人战争」亚人方颓势的王城决战，以及成为威尔海姆脱离王国军的契机、「剑圣」初征，将内战导向终结的第二次卡斯泽尔攻防战决战。

然后是「剑鬼」捣乱终战纪念典礼，以及「剑圣」败北──

「──那个愚蠢男人！实在是！都过了两年还这么没药救！」

在终战纪念典礼上闯进来打败「剑圣」证明自己的强大后，「剑鬼」就被整个骑士团包围抓起来扔进了监狱塔。

看过其他人都办不到的愚蠢丰功伟业后，卡萝这么骂道。

怒上心头的恋人的话让格林苦笑。──自己也是抓捕那个旁若无人毁了典礼的「剑鬼」的其中一人。

一回来就听见女友这么辛辣的意见，嘴角忍不住上扬。

「格林？有什么好笑的吗？我说了什么奇怪的话吗？」

『不是好笑或奇怪，而是跟我预想的一样。』

「唔……也就是说，你早就看出我会这么生气啰？」

『你怎么想呢，老师？』

幽她一默的格林从怀中取出纸笔流畅笔谈。

失去声音超过两年，两人已经很习惯这样沟通了。当然卡萝看穿格林想法的能力仍然健在，因此在写完之前她就已经鼓起脸颊。

像这样子被看穿表情的时间也很长了。──可是她现在的样子自然无比，凌驾这两年来的感慨。

『威尔海姆回来，开心吗？』

「笨蛋……说那什么话！我心仪的对象就只有你……」

『对不起，我说得太少了。是特蕾希雅大人的事。』

「……你是故意的。」

格林立刻拿出写好的第二张纸，卡萝闹别扭瞪著他。

对女友可爱的脸蛋感到心满意足，格林也发现自己心安到叫人惊讶，于是用力咬紧发抖的牙齿。

──下落不明两年的威尔海姆回来了。

剑术还是跟以前一样──不，是磨练得更锐利，打败了参加典礼的「剑圣」，本领出色到足以囊括胜利的「剑鬼」回来了。

为了卡萝最关心的特蕾希雅，为了拯救她的心灵，为了带走她。

「总而言之！不可以这样子！要有人去好好骂那个做了蠢事的男人！这是我跟你的任务！」

『特蕾希雅大人呢？』

「特蕾希雅大人善良又温柔，我不觉得她会骂那男的。所以我有必要代理！」

强而有力的断言，里头包含的不是愿望，而是确切肯定。

卡萝会这样说死，是因为威尔海姆和特蕾希雅的关系就是那样吧。从头到尾都相信的格林，也是深爱卡萝到了这个地步。

之后还有很多想要跟威尔海姆讲的话。自己和卡萝利害关系一致。

「走吧，格林！特蕾希雅大人应该带那家伙到宅邸了……我要在那边，把累积两年的怒火全部砸向他！」

卡萝伸手，格林苦笑握住，然后制止想要就这样跑过去的她。

接著将顾虑她要参加典礼而没传达给她的想法写成文字。

『这件礼服很适合你。』

这句话让卡萝产生什么反应，就不详述了。

反正格林跟著脸红的卡萝离开典礼会场是不争的事实。

6

婚礼在圣堂举行，威尔海姆和特蕾希雅在众人面前接吻。

站在来宾行列里的卡萝望著一切进行而潸然泪下，格林搂住她的肩膀。

勉强让威尔海姆赶上婚礼的卓格夫队，全员外观都惨不忍睹，格林也不例外。连续穿三天的铠甲和制服可以说是不卫生至极。

可是即便身旁的恋人全身脏兮兮，卡萝也不在意。而身为新娘的特蕾希雅也一样。──她很自然骄傲地挺起胸膛。

缔结成为夫妻的誓约，接吻后的两人婚姻获得正式认可。连国王陛下都偷偷出席婚礼。已经没有人会对他们的关系有意见了。

虽说一开始就只有新娘的父亲强烈反对。

「啊啊……特蕾希雅大人好美……」

难掩欢喜与感动，新娘打扮的特蕾希雅掳获卡萝芳心。虽然有点吃醋，但今天是特殊场合，所以也就忍下了。

对卡萝来说，特蕾希雅有多重要是不言而喻的。

正因为两人情同姊妹，甚至同寝共食，因此对这天的感激也格外深刻吧。在这层意义上，格林也为威尔海姆的心愿实现一事感到放心。

只是没有像卡萝这么投入，定位没那么深而已。

「────」

誓言与接吻结束后，婚礼的重头戏也就结束了。

之后就是画蛇添足的后日谈，典礼慢慢地继续进行。由波尔德担任新郎的关系人代表上台致词，新娘的父亲贝尔托在讲述与女儿的回忆时还哭得不能自已而被带离，差不多就是这样。

而典礼最后，威尔海姆和特蕾希雅两人要相偕离开会场。接受与会者的鼓掌和祝福，两人步出圣堂──

「──卡萝！」

「咦！？」

吓一跳的卡萝，不自觉地就接住呈拋物线飞过来的花束。那是特蕾希雅手持的黄色花束，由新娘拋给与会者作为仪式的最后步骤。

而接到花束的人，据说就是下一位被幸福眷顾的人。这是相当知名的逸话──

「──啊。」

特蕾希雅调皮眨眼，察觉到她意图的卡萝面红耳赤。

顿时，留在圣堂的来宾们鼓掌的矛头，都从婚礼的主角威尔海姆和特蕾希雅转向卡萝。如雷的祝福倾注而下。

被这件事给吓到的卡萝搂住格林的手，结果祝福声变得更大了。

「格、格林，那个……」

该怎么办啊？不知如何应付的恋人，让格林闭上一只眼睛。看过去，特蕾希雅幸福地朝被众人鼓掌的两人微笑，威尔海姆也露出邪恶表情像是在报复。

──下次轮到你们被人看。感觉看透了对方的内心。

「────」

格林用左手抱住卡萝，右手抢去她手中的花束。然后将花束高举过头，展示给来宾们看。

顿时，被这行动吓到的与会者面面相觑，然后加大掌声。

接到花束的少女，其男友高举花束意味著什么，在场者无人看了还不知道。

特蕾希雅双手掩嘴，威尔海姆对这出其不意挑眉讶异。波尔德豪迈大笑，麦克罗托夫微笑眯起眼睛，吉欧尼斯陛下拍手的声音比任何人都大，当成女儿来疼的女孩要被抢走的恐惧让贝尔托痛哭流涕。

（插图）

然后，被抱住的卡萝缩著身子，红著脸蛋说──

「──格林是笨蛋。」

这声可爱呢喃，就只有格林听见。

7

「你做的事，真的是每次都吓我一跳。」

婚礼结束，夜晚降临的王都露格尼卡──位在平民街一角的一户人家，坐在床上的卡萝含恨地对著格林这么说。

这里是格林的寝室，建筑物是格林的房子。隶属于王国屈指可数的部队，名气响亮又被国王记住的卓格夫队，其副队长一职由格林担任。

因此他已经不用像一般士兵那样住在兵营，而是在城邑拥有房子，在波尔德的打点下最后住进这里。

很幸运地，因为备齐了大致的生活用品，所以住进去后还不曾遇过什么问题。像这样有了个人住处，也就比较容易邀请女友到自己家。

「以前我就觉得其他骑士和卫士的目光有点叫人在意。」

当然，两人并非公开频繁地见面，但女友容貌惹人注意的男人是很辛苦的。为了驱赶其他虫子靠近，格林迫不得已在私底下打了一场大暗斗。

没让卡萝知道这方面的辛劳，而且如今他已充分获得回报了。

「格林，辛苦了。……到这边。」

泡完澡，换好衣服后，卡萝拍拍床邀请格林坐到身旁。在脸颊泛红的她身边坐下，搂住她的细腰。

就这样，两人不需交谈，嘴唇便自然交叠。

──只有在两人独处的时候，格林几乎不拿笔。

只要看表情就够了。卡萝说的对，传达想法的方式不是只有语言，格林在心头深处咀嚼这份喜悦。

顿时，想起了身旁有人是以剑传达心情，忍不住噗哧一笑。

「……气氛都没了啦，格林。不是道歉就可以了事的。」

接吻途中被喷笑坏了气氛，卡萝很不高兴，也不接受格林道歉的表情，甚至撇过脸闹起脾气来。

「──嗯，不行。我不原谅你。」

手贴上背对自己的脸颊，嘴唇贴上另一边的脸颊。不放弃地勇敢挑战还在生气的公主殿下，朝耳朵和脖子落下亲吻之雨。

「啊，等一下，会痒……奸诈，太狡猾了！」

痒到扭动身子，绷紧的脸颊防御被瓦解。顿时，笑的冲动溢出，开始笑起来的卡萝宣布投降。格林将她抱进怀里。

「……明明是很健壮的胸膛，看起来却很单薄，真不可思议。」

抚摸胸膛的同时，卡萝发出带著甜蜜的声音。

平常威风凛凛，总是时时注意自己言行的她不会在人前表现出这般甜腻。这是连特蕾希雅都看不到的表情──只有在格林面前才会展露。

「────」

第一次的邂逅，是她维系了自己分崩离析的心灵。在那之后也没有嘲笑自己不知天高地厚的野心，而是支持自己。

惋惜自己失去声音，成为自己的女朋友。过了两年时光，见证她原谅自己的瞬间。──看著她最终接下花束，被人祝福。

「……要改名叫卡萝•法先，还太早了喔。」

察觉到俯视视线的意图，卡萝微笑著这么说。

由此看来，感觉连求婚的念头，似乎都会从脸上先被看穿。

为了不要让事情变成那样，得十分用心留意才行。为了可以献出自己的全部让心上人幸福。

那是在「剑鬼」与「剑圣」的华丽故事中的中场休息时间，相结合的两名男女的故事。

──这也是美丽的「剑鬼恋歌」与「剑鬼恋谭」的重要一幕。

《完》

** 后记

哟～大家好！我是长月达平，也是鼠色猫，总之是作者！

这次很感谢您购买「剑鬼恋谭」！秉持著努力与毅力，一路站著看到后记的您也很拼喔！

把站著看的时间拿来打工的话，应该就买得起这本书啰！？

好啦，如此这般所以这是后记，在正传的时候每次后记都会被拆成两栏排版，所以这种形式反而比较新鲜哩。

后记的字体小到作者的父亲没有放大镜就没法看的地步。作品的内容姑且不论，后记被亲人阅读让我莫名冒冷汗……

闲谈且先不提，来聊聊书中内容吧。

这次的「剑鬼恋谭」是汇整在月刊Comic Alive连载的Re：Zero短篇小说，重新架构添笔修正，苦恼自己以前文章怎么那么糟，反覆阅读后却感到很有意思……蕴含著这样的悲喜下化为实体本的书籍。

将作品中的配角写成主角的Ex系列也来到了第三集，包含短篇集在内，光番外篇就有六本，成了一个相当大的家庭。仔细想想Re：Zero系列出了二十二集，所以可以说是长篇小说也不为过了吧。

而作者我本人认为长篇小说的醍醐味之一，就在于在正传登场的角色过去篇。奇怪，这好像在「剑鬼恋歌」时也说过！？

不管怎样，喜欢的事就要多主张几遍。过去篇好赞！

因此，身为有许多值得大书特书的过去篇之重要人物，威尔海姆又再度被聚光灯给照耀。

在番外篇已经是第二次担任主角的威尔海姆，甚至已经内定为第三次的主角，简直是胜利组呢。虽说是番外篇，但因为是Re：Zero的主角，所以都会吃足苦头的！

话虽如此，这次的威尔海姆在历经求婚（大乱斗）之后，举办了（强行军）结婚典礼，然后去蜜月旅行（与最强敌人交战），本书就是充满了这些温馨的插曲。

实体书的正传方面是进入了网路第五章，再度轮到威尔海姆出场的时候，事先看过这本「剑鬼恋谭」的话，作者敢保证可以更享受第五章喔！

因此，若是有只追正传而没看番外篇的朋友的话，请务必要劝对方看过。基本上，作者写过的情报都不会吝惜地使用，因此全部都看过的人会更能乐在其中喔！

好啦，做完完美的番外篇广告后，就进入惯例的致谢吧！

责任编辑I大人，仔细想想「剑鬼恋歌」是感觉「就莫名写出来了所以寄给你」这样起了头的企划，而「剑鬼」系列能够持续出到第二集，实在是很不可思议。第三集的「剑鬼战歌」也请多多指教！

负责插画的大冢老师，虽然每次都会讲，但您的角色设计真是太棒了！连没有指定的角色都设计出来，插图的变化每次都乱赞一把。这次的库尔刚特别帅气！非常感谢您！

设计师草野老师，虽然本书封面是系列作有史以来最多人的一次，但您还是一如往常创造出鲜明的设计。真的很感激！

还有マツセ老师画的漫画第三章，目前刚好可以看到老威尔海姆的帅气活跃！谢谢您画出虽老却酷爆的威尔海姆！

其他还有MF文库J编辑部、行销人员、校阅人员以及书店的工作人员，承蒙诸位照顾了！每次真的都很感谢各位！

与OVA相关的动画工作人员，又要承蒙各位再度多关照，虽然书尾也有通知，不过「剑鬼」系列的漫画化开始启动，让我对相关人士有道不完的感谢。今后也请多多指教！

最后，要向每次都支持我的各位读者献上最大程度的感谢！

那么期待在下一次的故事里再相遇，掰啾！

2018年5月　《为了房间整建施工而筋疲力尽的一天的最后》