#+title: Re:从零开始的异世界生活 短篇集 3
#+setupfile: ./setup.setup
* 短篇集 3

** 『My fair bad lady』

台版 转自 轻之国度

图源：真妹控

录入：kid

1

「昴，你听说了吗？明天好像有个『流浪天才厨师』会来喔。」

「……为什么？」

对于露出期待目光的爱蜜莉雅，昴大大歪著头如此回问。

场所是罗兹瓦尔宅邸的中庭，时刻是尚未享用早餐的早晨。

在清新的晨间空气中来见与缔结契约微精灵对话的爱蜜莉雅，对昴而言也是每天必定完成的行程。

而在此种必定行程刚开始并差不多打完招呼后，爱蜜莉雅突然冒出了这句话。

不论是受晨曦照耀闪闪发光的银发、如宝石般圆润斗大的深紫色眼眸，此种爱蜜莉雅的美貌总是给人既清秀且坚毅的印象。但现在那既可爱且妩媚的动作，在在散发出与平常截然不同的魅力。

简单说来，就是明明很漂亮却又可爱，真是天使。

「──？昴，你有在听吗？」

「嗯，当然有。简直就是E（爱蜜莉雅酱）•M（真是）•T（天使）……呃……刚才说了什么？」

「真是的，你果然没在听！我是说有『流浪的天才厨师』会来宅邸。你不觉得很期待吗？」

她毫不掩饰兴奋难耐的情绪，那宛如银铃般的声色满怀著期待。

虽然此种可爱模样让人想一直看下去，但昴被爱蜜莉雅口中说出的「流浪天才厨师」这个名词引走注意力。

「流浪……天才厨师？那个头衔听起来很蠢的人是谁？」

「啊，不能这么说喔。虽然我自己也不是很清楚就是了……」

对于面带狐疑并皱起眉头的昴，爱蜜莉雅将手指抵在自己的嘴唇上。

「总之，好像是很会料理的人，听说做出来的料理有名到是『只要吃一口就会让身体不由自主，吃两口会心神无主，吃三口会让灵魂受到束缚』的程度喔。」

「那是对料理的传闻吗？不是诅咒吗？」

这种像是诗歌的风评内容太过空前绝后，感觉不太能够当成参考。

总而言之，撇除掉此种浮夸的风评，简单说就是要找那个名厨到宅邸举办类似餐会的活动。

没有传到姑且算是宅邸佣人的昴耳中，也是令人匪夷所思。

「唉，毕竟是罗兹亲，也很有可能是想来个惊喜。爱蜜莉雅酱是什么时候听到这个消息的？」

「刚刚才听到喔。」

「呃……那应该不会错了。」

身为宅邸主人的罗兹瓦尔•L•梅札斯，是个身穿奇特服装且化著小丑妆，将诡异行径散播至周遭的怪人。由于没头没脑的发言与提议已经是日常便饭，因此对于这次的事，昴也认为是其中一环而若无其事地接受这项事实。

「不管怎么样，希望别只是空有头衔啊。」

「说得也是呢！我好期待喔！虽然我不是很清楚，但听说对占卜我今后未来也有很重要的意义，让我有点紧张呢。」

「爱蜜莉雅酱的今后？」

见到昴点了点头，爱蜜莉雅一脸可爱的模样，显得相当兴奋，不过这番话让昴有些疙瘩。他无法得知究竟是哪里有问题，最后还是无法找出原因。

「──算了，总之我们来做收音机体操吧。做这个也比较有精神又好玩吧。」

「嗯，我知道了。那么把手伸到前面，开始做伸展操吧～～！」

已经完全溶入异世界晨间风俗的爱蜜莉雅，发出此种固定的吆喝声后，便开始做著收音机体操。

昴一边听著她那有精神且悦耳的声音，一边也开始专注做著晨间体操。

2

「昴，你听说了吗？明天有个『连龙都会发出低吟的终极厨师』迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世会来喔。」

「……什么？」

结束晨间收音机体操后，雷姆带著灿烂眼神对回归职位的昴如此说道。

平常在工作中总是以既冷静且迅速为原则的雷姆，现在正难掩兴奋地红著脸颊，让昴大大地吃了一惊。

「是的，『连龙都会发出低吟的终极厨师』迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世要来了！真的很厉害呢！」

「嗯，感觉好像真的很厉害。确定是厨师，不是冒险家之类的吗？」

「唔……昴，你在说什么呢？这是当然的，说到迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世，可说是名震天下的厨师。」

「这、这样啊……」

面对将脸突然靠了过来并发出紊乱鼻息声的雷姆，昴显得有些畏畏缩缩。

不知道是否很尊敬那位厨师，连平常总是站在昴这边全面支持的雷姆，这时甚至难掩不服气与不满地表现出怒气。

「呃……那就是明天会来的厨师对吧？我刚刚才听爱蜜莉雅酱说过，是很有名的人吗？」

「当然！是受到食物女神祝福，穷究世界上所有味觉的精髓，仍然持续追求未知的顶尖，甚至能让龙发出低吟的终极厨师！据说『只要吃一口就会让身体不由自主，吃两口会心神无主，吃三口会让灵魂受到束缚』这段传闻也是很有名喔。」

「那段歌颂的话不管听几次都很令人担心耶……没想到雷姆也满清楚的。」

「毕竟雷姆也有掌管炊事，能见到穷尽厨艺的人当然会既尊敬又憧憬，所以明天真的很令人期待呢。」

雷姆难得地频频展现出平时少见的兴奋难耐笑容。

这道极为灿烂的微笑，光是看到便让昴跟著缓颊一笑。但一想到这是某个陌生人的功劳，也让昴的男人内心感到不甚有趣。

在先前吟游诗人莉莉安娜的那件事中，雷姆出人意料的追星一面也在这时表露无遗。

「咦，昴，你怎么了呢？感觉好像不太开心……」

「没有啊，只是看雷姆和爱蜜莉雅酱对那个什么迪亚斯很陶醉，别管我了。还是躲在角落舔著盘子比较适合我啦。」

「哼哼，昂别说这种奇怪的话啦。啊，但是……」

对自卑地闹著别扭的昴投以笑容后，雷姆突然想起某件事般拍了一下手。

「先不说舔盘子这个玩笑话，迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世据说也是相当注重礼仪的人。即使厨艺至高无上，但对客人也会要求具有一定程度的良知。」

「呃……意思就是很难相处的名厨吧？这在哪个世界都是一样。总之我还是问一下，这是只要违反礼仪就会没办法吃到料理的意思吧？」

「不，是会被做成料理。」

「是『要求很多的餐厅』那种厨师！？」

听到会代替食材被做成餐点，让昴的背脊窜过一股凉意。然而见到雷姆随即噗哧一笑，便发现那是她特有的玩笑话而松了一口气。

「真是的，饶了我啦。我还以为真的有这种事耶。」

「对不起，因为昴老实的模样实在太可爱，就忍不住开了个小玩笑。可是不只是用餐，礼仪也是很重要的喔。像雷姆和昴这样的下人，不知道是否也会要求这种事呢。」

「哎呀，就算要求跟宫廷料理同等的礼仪，也只会让饭吃不出味道而已啦。」

将受过教育与没有受过教育的人摆在一起比较，实在会让人很受不了，不过前提是对方只招待受过教育的人……想到这里时，让昴心中顿时有些疙瘩。这些疙瘩到底代表什么？

「难得有这个机会，雷姆明天也想好好学习。昴，请仔细记起来今天雷姆的味道，明天肯定能品尝到脱胎换骨的雷姆。」

「这种说法好像是要吃雷姆一样，总觉得听起来有点下流……」

「昴真是的……居然说我这么可爱想吃我，这样我会很害羞的。」

「不，我根本没说吧！」

对微微红著脸颊的雷姆如此吐槽后，先前感觉到的不协调感也随之淡去。昴就这样不经意地摸了摸雷姆的头，与她再度开始处理晨间的工作。

不论如何，看来可以好好期待明天与之后的餐点了。

3

「毛，你听说了吗？明天有个『既好色又喜欢女人的传说厨师』迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世受邀来到宅邸，记得别做出失礼的举动。」

「……什么？」

在分配晨间工作的晨会结束后，与拉姆一起分配清扫宅邸时，听到这番话让昴深深地歪过头。

昴今天第三次歪著头回头一看，只见拉姆将双手挽在胸前，以颇为傲慢的模样叹了一口气并耸了耸肩。

「我是说明天有个『既好色又喜欢女人的传说厨师』迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世会来宅邸展现厨艺。虽然没办法同席的毛很可怜，不过记得别做出有损罗兹瓦尔大人名誉的举动。」

「不不不不，很多地方都先等一下！咦，你说谁要来？迪亚斯先生？」

「是迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世。虽然念起来很麻烦，不过听说要是不好好念出全名就会惹他生气。毛也是，记得要叫名字的时候绝对别念错。还有就是……」

「等等，真的先等等。」

途中打断如连珠炮般不停说著话的拉姆，昴将从爱蜜莉雅那里开始听到的「厨师情报」持续追加新页数。简单说来，这究竟是怎么回事？

「那个叫做迪亚斯•雷本卓的人，跟雷姆说的应该是同一个人吧？」

「我不知道雷姆是怎么说的，昨晚她有和我一起听罗兹瓦尔大人说这件事，所以应该是同一个人吧。然后呢？」

「和雷姆描述的印象，好像已经不是只有一点差别了耶？」

根据雷姆开心描述的语气，对方应该是个固执且对厨艺有所坚持的厨师，怎么样都不应该是个好色之徒。

「而且还不经意透露出我不能吃饭，这是什么意思？」

「我不是说了对方既好色又爱女人吗？精通各种美食且处在味觉顶点，迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世会挑选客人，而且还是很简单易懂地只限女性。真是个下流的人。」

「既然这样，罗兹瓦尔应该也没办法吃到餐点吧，这不是很奇怪吗？」

「哼！」

面对昴执意追问的问题，拉姆以毫不掩饰嘲笑的态度冷冷哼了一声。

「罗兹瓦尔大人是经过正式交涉赢得了席次。很可惜没有毛的位置，你就去舔别人的盘子好好满足自己吧。然后不准舔罗兹瓦尔大人的。爱蜜莉雅大人的你也死心吧，要是敢碰雷姆的盘子绝对不会放过你。如果你敢用舌头沾到我的盘子，会马上让你死个痛快……碧翠丝大人的盘子就随便你吧。」

「别把舔盘子当成前提！这是什么惩罚游戏啦！？」

既不能参加餐会，甚至还得体会舔碧翠丝用过的盘子的耻辱，这种结论任谁都会不由得发出抗议声。

「再怎么说这样都太残忍了吧！我要求改善待遇！我要直接上诉到罗兹亲那边！」

「很可惜，罗兹瓦尔大人已经前去迎接迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世了。明天晚餐时间才会回来……也就是开始作菜的时间之前，节哀顺变。」

「走头无路啦～～～～！」

昴当场跪倒在地，对自己的不幸仰望天花板长叹。

Eli, Eli, lema sabachthani──神啊！你为什么要舍弃昴啊！

「话说，为什么只有我这么晚听到这个消息啊！感觉有阴谋！」

「他是旅行各地的厨师，平常很难掌握行踪，这次也是很惊险才能找到他。不过一告诉他宅邸有四个美女顾客，他就马上答应了。」

「是个既好色又爱女人的厨师！」

对方答应邀请的理由实在太过明显，让昴首度认为那个称号很有说服力。

不用提爱蜜莉雅，拉姆与雷姆也是美少女。碧翠丝只要静静不说话并带著微笑，也是可爱得像是洋娃娃或是妖精。

「就算是这样……怎么能允许这种蛮横的行为……！」

「你认命吧，这本来就不是一介佣人能期待得到的幸运。应该说我们才是特例，全部都是多亏了罗兹瓦尔大人，你不觉得大人真的很棒吗？」

「我怎么能同意自己被排除在外！」

「你怎么这么啰嗦……而且这次除了用餐以外还有别的意义。」

拉姆对懊恼的昴继续鞭尸。她最后那段话因为太过小声，愤慨不平地拍著地面的昴并没有听见。

结果寻求慰藉也在途中被拋下，拉姆匆匆地回到工作岗位上，被留下的昴稍微懊悔一阵子后……

「至少给我爱蜜莉雅酱的盘子……不，我实在没办法做出那么大胆的举动……」

他就这样一边怀著此种低级的苦恼，一边开始处理晨间的工作。

4

「话说回来，你听说过了吗？明天『斩首厨师』迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆的继承人会过来这里。」

「等等等等等等！」

虽然这已经是今天第四次听见，但那充满震撼的前言让昴甚至忘了固定会回的话，而是忍不住如此放声回应。

难得带著得意神情提起这个话题的少女──碧翠丝似乎对这个反应颇为不满，只见她坐在梯凳上，冷冷「哼」了一声并瞪著昴。

「居然这么有胆敢打断贝蒂的话，还有别在这个房间吵吵闹闹的。不只是会扬起灰尘，重点是还会让书本变得不愉快。」

「我就不刻意追究那种好像自以为书本心情的神奇发言了。你刚才说了什么？要不要再说一次？」

「唉……我只是说明天『斩首厨师』迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆的继承人会来而已。」

「好，就是那里！那个超惊悚的外号是怎么回事啊！斩首！？我怎么没听说过啊！」

每当听到传闻，那个厨师的外号就会不停改变，不过在这之前都勉强维持在厨师的范畴内。但到这里突然加上了血腥的印象，就算昴再怎么宽宏大量也没办法装成没听见。

「说起来，外号只要有一个够帅气的就好了啦！有这么多反而只让威风感变得越来越薄弱而已！『流浪天才厨师』、『连龙都会发出低吟的终极厨师』、『既好色又喜欢女人的传说厨师』还有『斩首厨师』？从好色开始就已经很奇怪了吧，别把形容词全部混在一起啦！还有人像这样有这么多外号吗？有就说说看啊，我绝对要去好好教训那个人！」

「罗兹瓦尔不是好像有『亚人癖好』、『小丑贵族』、『首席宫廷魔导师』、『宫廷小丑』这些外号吗？」

「等他回来就去教训他！」

昴对身边居然有符合人选而感到相当愤慨，并且因话题中的外号不停抓著头。

面对昴天人交战的模样，碧翠丝则是无奈地叹了一口气。

「不知道你是在焦躁什么……反正肯定是很无聊的杂事吧。」

「哪是什么无聊的事啦。斩首真的很可怕，会被叫成『斩首厨师』至少就不是只砍了两三个脑袋而已吧，为什么这种人还能继续当厨师啊？」

「……喔，是这个意思啊。是你误会了吧？『斩首厨师』这个外号不是真的因为砍头来的。」

碧翠丝一脸傻眼的表情，她的发言让昴挑起眉头回问「是这样吗？」

「哎呀，说得也是。再怎么说只看人不顺眼就把头砍掉，实在不可能这么安稳地活著。什么嘛，只是个吓人的外号啊。」

「这是当然的吧。不过只要在餐会上被那个迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆的继承人看不顺眼，不知道为什么之后就会被迫离开立足处或职位而家道中落，所以才会被这么称呼。」

「是人事方面的『斩首厨师』！？」

与好色时同样，这个有说服力的内容让昴吓得浑身颤抖。

感觉越是偏颇的外号，越搞清楚根据反而更令人恐惧，不过昴仍然说服自己目前并没有太差劲的因素。

「等等喔……？」

当他准备接纳这个事实时，昴再度与不协调感正面冲突。

此种不协调感是来自早上与爱蜜莉雅相处的一幕，每当聊到那个厨师时，那个感觉便会微微探出头。昴到目前为止皆自然而然地忽视掉，但将至今的情报组合在一起后，便若隐若现地瞥见另一种全新的真相。

「会占卜爱蜜莉雅酱的未来、对礼仪很讲究、好色又爱女人、斩首厨师……」

这些令人不安且危险的关键字凑在一起，让昴几种颜色暧昧模糊的脑细胞开始活化，最后得到了一个结论。

──对方是个心狠手辣、残酷且怀著凶狠企图心的人。

「怎么可能有这种事……不过，如果是罗兹瓦尔的确有可能这么做。」

罗兹瓦尔•L•梅札斯在王选中身为爱蜜莉雅的最大后援，也可说是唯一的后盾。然而他也是王国贵族的其中一人，在位居边境伯的立场下──当然也被迫面临严酷的选择。

因此罗兹瓦尔应该也会寻求，与目标成为王的爱蜜莉雅同等的觉悟。

──而那肯定也是既温柔且纯真的爱蜜莉雅无法想到的方法。

「……得想点方法才行。」

爱蜜莉雅的笑容、动人的声音、以及手指碰触传来的温暖，正在昴的记忆中散发光芒。

不论是那道笑容、声音或是温度，一切都得彻底守护。

「只有我绝对会站在你这边。」

为了强烈照耀爱蜜莉雅所追求的目标，昴决定想持续成为她的支柱。

因为他已经收到了为此竭尽心力的报酬。

「喂……已经完全不听人说话了，我不管了。」

昴怀著决心重新握紧拳头，沉浸在内心世界的他已经完全忘了碧翠丝的存在，被忽略也让碧翠丝气得别过头。

在这个时候，双方没有将彼此的想法正确地传达出来，将这件事稍微导往了颇为复杂的方向。

──但这时的昴与碧翠丝当然无从得知。

5

「帕克，你知道吗？明天有个『让流浪的龙发出低吟的好色传说斩首厨师』会来到宅邸。」

「……是叫这个名字吗？」

今天第五次提到的这个话题，虽然流程与先前如出一辙，但有个决定性的差异──没错，就是先前身为倾听者的昴变成了说话者。

昴怀著高度戒备，在宅邸庭园对密谈的对象说出这个话题，而这只浮在空中并有著灰色毛皮的小猫精灵对昴的话语深深表示不解。

他是爱蜜莉雅的契约精灵，也是自称爱蜜莉雅监护人的帕克。

帕克歪著头，抱著几乎等同身体长度的尾巴并把玩著前端。

「我看莉雅好像很高兴，也知道会有厨师过来。不过我记得不是这么奇怪的外号，应该是更简单又可疑的外号吧……」

「没错！就像你说的，是不太正确！虽然原本有其他更多种外号，听起来实在太乱了，不过现在这不是重点啦。」

「嗯……我还是听不太懂。到底是怎么回事？」

「我只有叫你出来，当然是对爱蜜莉雅酱很重要的事。」

当昴压低声量切入正题，帕克的气氛也为之一变。虽然仍然维持著既悠哉且温和的模样，但这只小猫缓缓地升高到昴的视线高度后……

「只要是莉雅的事，我什么都会听。说来听听吧。」

「嗯。不过这不要让爱蜜莉雅酱听到，我不想让她多担心……而且这些事如果让她知道就完蛋了。」

「是喔？」

即使展现出不太能接受的态度，但帕克似乎还是打算将昴的话听到最后。昴一边怀著谢意，一边开始将明天的事──也就是将潜藏的阴谋揭露。

「关于明天的餐会……那是罗兹瓦尔设下的陷阱。」

「什么意思？」

「不是说里面有下毒之类的喔，只不过有个毒计。」

「听起来好饶舌喔。」

「很饶舌吧！呃……也就是说，罗兹瓦尔那家伙明天在餐会上想确认某些事──就是爱蜜莉雅酱的餐桌礼仪！」

昴总算找到时机说出整个计划全貌，帕克回问「礼仪？」对这番内容满腹狐疑。昴对这只小猫总是慢半拍理解的反应感到颇为焦躁，说著「你还听不懂吗？」并继续说明。

「今后爱蜜莉雅酱身为国王候选人，会在很多场合接受邀请用餐。例如舞会或是聚餐等等，就是想测试她能不能在这种场合做出相对应的举止。」

「──！意思是明天的餐会就是前哨战吗？」

「而且，那个『斩首厨师』会诅咒不懂礼仪客人的前途。只要曾经被那家伙批评，就会永远无法再抬起头，到目前为止也有许多人的前途受到诅咒，对世界前途渺茫而走上绝路……那就是罗兹瓦尔打的算盘。」

在禁书库发现这个阴谋时，昴一开始也是打从心底不肯相信。

但越想就越合理。也就是说，这是罗兹瓦尔对爱蜜莉雅王选之路所做的预演，也是考验。

这也代表了会根据结果，决定爱蜜莉雅是否参加王选──

「不过罗兹瓦尔会做这种事吗……不，如果是他就有可能……！」

「可能？不对喔，绝对是这样！他是想测试爱蜜莉雅！不过要是告诉她躲过了又怎么样，只会再被别的方法测试而已。」

「那要怎么办？莉雅很相信罗兹瓦尔，可是这样她太可怜了。」

帕克的猫耳无力地垂了下来，黑色眼眸在消沉的表情中难过地渐渐湿润，昴也能切身体会他的心情，于是彷佛鼓舞著他般重重地拍了拍自己的胸膛。

「所以我才会找你过来，为了让我们两个一起帮助爱蜜莉雅。」

「我和昴？要怎么做？」

「很简单，明天罗兹瓦尔他们会测试爱蜜莉雅的餐桌礼仪，爱蜜莉雅好像还不知道这件事……所以我们只要暗中支援她就好！」

对于宛如晴天霹雳般浑身僵硬的帕克，昴深深地点了点头。

罗兹瓦尔如恶魔般狡诈诡计，但这次昴与帕克皆已察觉，两人绝对是站在爱蜜莉雅这方，为了她勇敢面对困难。

「动手吧，帕克。我们两个要帮助爱蜜莉雅！」

「──嗯，没问题。我知道了，就赌赌看昴的这份心意吧。」

面对伸出手的昴，帕克犹豫了一瞬间后，便随即落到他的手掌上。

这并非是握手，但双方的意图在这时合而为一，既然这样就没有任何问题了。

「所以呢，明天要怎么做？」

「我已经想好几个妨碍的方法了，不过我们还要再往后多想几步。毕竟得根据状况暗中帮忙，这必须好好讨论清楚，你得做好今晚不能睡的心理准备。」

拥有同样目的，为了珍视的少女而竭尽所能的同伴。

昴与帕克带著在旁人眼中几乎同样的笑容，为了破坏邪恶企图，两人皆虎视眈眈地研磨著爪牙，准备迎接明日到来。

6

那天，拉姆从一大早便显得不太开心。

她当然没有不成熟到将情绪表现在脸上，因此举止仍然是一如往常地威风凛凛，表面上掩饰得十分完美──即使内心完全无法算是平静。

「毛那家伙，怎么会那么丢脸。」

只要一放松戒心，便会从双唇间焦躁地抱怨著那个总是吊儿郎当的佣人。

原本菜月昴身为宅邸佣人，必须与拉姆和雷姆一样，负责所有杂务──今天甚至得接待来宾，理论上应该要忙得不可开交。

但他却在这个重要的日子搞坏身体，从一大早便窝在房间没有出来。

「姊姊，昴也对不熟悉的工作累积了不少疲劳。雷姆会拚命工作，请让昴好好休息吧。」

面对拉姆的焦躁情绪，只有几乎等于是另外一半的雷姆发现这件事，并且替昴出声辩护。

然而，见到可爱妹妹增加负担，只让拉姆对受到雷姆宠溺的昴更加不愉快，拉姆心中对昴的评价已经等于是坠到谷底。

「毛已经没有活到明天的资格了。」

要是他敢嘻嘻哈哈地露脸，拉姆在心底决定绝对不会放过他。当她怀著此种怒气处理工作时──等待已久的客人总算来到了宅邸。

宅邸主人罗兹瓦尔将「既好色又爱女人的传说厨师」迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世带了回来。

「──很荣幸能接受招待喔。」

「────」

拉姆绷紧神情，迎接堂堂出现在宅邸玄关大厅的男子。

举凡圆润凸起的腹部、满是油光的脸、颜色稍淡的灰色短发等等，是个横竖体积皆相当庞大的肥男，正带著下流的笑容站在眼前。身旁还有个戴著头巾几乎遮住整张脸的帮佣，举止看起来十分大牌。

「会合花了一点时间呢，不好意思这么晚才回来。不过是个比传闻中更让人愉快的客人，记得别做出失礼的举动喔。」

并肩站在厨师身旁的罗兹瓦尔带著微笑表示欢迎。这是主人的命令，拉姆与一起迎接客人的雷姆深深弯下腰鞠了个躬。

「欢迎您大驾光临。」

「喔呵～～真是让人受不了啊～～」

面对异口同声如此说著的两人，对方发出油腻的声音并抖动著腹部、胸前与脸颊的肉。

「这么美丽又可爱，而且双胞胎更增添了许多魅力喔。真是的，边境伯大人的的眼光还真不错呢，嘿嘿嘿……」

「还真是多谢啦，很荣幸能得到您的夸奖。」

对于这名男子兴奋的话语，罗兹瓦尔都只是客套话回应。拉姆一边听著这番话，一边在脑中想像著将这位胖子的脸颊拉开、踹著腹部、像是踢绣球般让他在玄关大厅四处弹跳泄愤──不准用那么恶心的眼神看著雷姆。

「────」

「哎呀，这样不行。不好意思一开始就问这个问题，可以带我去厨房了吗？我也想赶快完成受邀来到这里的真正目的呢。」

正当拉姆以为这种下流的闲聊会持续下去时，男子背后的帮佣戳了戳背后，男子便绷紧神情拉回正题并询问著厨房的位置。

「好的，请往这边。由小的雷姆带两位过去。」

雷姆率先提出带路并引导著两人，虽然拉姆发现男子的视线盯著眼前雷姆的臀部，但见到随从彷佛像在替主人的无礼赔罪般频频低下头，只好勉强以脑内踢球忍了下来。

「──是不是让你们觉得不舒服啦？」

「……不，小的不敢。对罗兹瓦尔大人招待的贵宾，绝对不会有任何负面感情。」

「说真心话呢？」

「敢对可爱的雷姆投以下流的眼光，让我想把他眼珠挖出来捏烂。」

那猥亵的视线与下三滥语气令人起满鸡皮疙瘩。比起来，昴还好多了。

幸好他还有不争气的毅力与个性，不太常出现下流眼神这点也是令人赞赏。

「雷姆应该不会在意，我想爱蜜莉雅大人与碧翠丝大人原本就不会在意这种事，所以只要拉姆忍耐就可以了。」

「真是辛苦你啰。话说没有看到昴呢，他怎么了？」

「很抱歉，毛从早上就搞坏身体在房间休息。原本应该要把招待客人的事全部丢给毛……应该说是交给他。」

「哎呀，真是可惜，今晚的晚餐肯定会有改变价值观的特别滋味呢。」

罗兹瓦尔的声音听起来似乎十分惋惜，拉姆则是垂下视线。

「要叫毛晚上出来露脸吗？」

「我是不想勉强他啦。如果他能出席，不管他脸色多差都会欢迎他呢。好啦，一直在意昴也没什么用呢。」

柔软的肩膀被碰触，拉姆感觉到该处传来温度。罗兹瓦尔对微微红著脸颊的拉姆投以笑容，并闭起单边眼睛朝她拋了个媚眼。

「你也好好享受吧，这应该是很有价值的一餐喔。」

7

──而客人来访的模样，有对黑眼瞳从窗帘缝隙间仔细地窥视著所有过程。

「已经确认目标了。绝对没错，形象和传闻一模一样。」

「……也就是说，我们的推论没有错吧。」

少年朝暗处回过头，浮在空中的小猫将短短双手挽在胸前朝他点了点头。少年对这番话耸了耸肩表示同意，然后眯起那三角眼。

小猫察觉到气氛为之一转，便吐出一口气。

「真的要做吗？」

「嗯，不管做或不做我一定都会后悔，既然这样还不如做完之后再来后悔──我现在是这么想的。」

「……我似乎误会你了。我知道了，既然你都已经做好这种觉悟，只要是我能力所及的事都会帮忙，毕竟这也是为了我的爱女。」

「只要是为了她。」

在严肃的气氛中，两人静静地互相沟通点了点头。

确定目标并拥有共通目的后，心中已经是毫无犹豫。

「────」

少年将先前坐的椅子拉齐，重新调整呼吸俯视著眼前的道具。虽然并非是熟悉的道具，但也不是首度接触的陌生物品。

没想到以前锻炼出的技巧会在此处再度派上用场，人生果然很难预料什么东西会有用处。

微微怀著此种感触与更加强烈的觉悟，少年投身于战场之中。

8

经过数小时做好晚餐准备后，爱蜜莉雅与碧翠丝受邀来到餐厅。

这段时间宅邸的所有杂务皆落到拉姆身上，之所以会变成这样，是因为雷姆难得向拉姆撒娇地提出想参观迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世的工作方式。

既然雷姆都已经如此撒娇，拉姆也不可能不努力达成要求，于是她以比平常更加完美的方式完成剩余的所有工作。

「可恶的毛……」

当然这并非毫不辛苦，因此她将怒气转嫁到翘班的昴身上。

话虽如此，昴的身体状况到了晚餐时间仍然没有好转──

「亏他之前还那么期待，昴的运气真是不好呢……可不可以稍微留点东西给他呢？我可以去问问看吗？」

「这方面罗兹瓦尔大人应该有所考量，请爱蜜莉雅大人无须担心这些小事，只要尽情享受餐点即可。」

「嗯……我知道了，就这样做吧。谢谢。」

爱蜜莉雅对昴缺席感到相当可惜，并且带著微笑对拉姆的话语表示谢意。但爱蜜莉雅真正需要担心的并非他人，照理说应该是自己。

对于处在高贵立场的人而言，迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世的餐会也具有「相对应的意义」，爱蜜莉雅却没有发现。

「说到可惜，帕克也没有出来露脸。好像还在宅邸的某个地方，不过他不肯回到结晶石里面。拉姆，你有看到他吗？」

「很可惜没有，而且以大精灵的模样受邀来到餐会上可能有点困难。」

「果然有问题吗？平常都看他把毛皮整理得很干净呢……」

即使说是精灵，但以猫的模样来到餐桌上果然还是不太好吧。

如果是兽人，在露格尼卡王国肯定会牵扯到许多复杂的问题，这里还是老实地认为猫的模样会造成困扰吧。

「哼，那家伙还真可惜。应该是平常做的那些事受到报应了吧。」

接著来到餐厅的碧翠丝，也如此提到缺席的昴。

与爱蜜莉雅不同，她的发言中没有任何体贴关怀，但反而能明显看出在意著昴，在拉姆眼中甚至可说是令人莞尔。

「是的，碧翠丝大人或许会感到寂寞。」

「……给我等等，贝蒂不懂为什么会寂寞。给我回答得更详细一点，双胞胎的姊姊。喂！双胞胎的姊姊！」

「好好，碧翠丝大人。小的还得配膳，请乖乖地坐在位置上。」

安抚面红耳赤地发出怒骂声的碧翠丝后，她也同样坐在餐桌的位置上。

接著正好在这个时候，罗兹瓦尔与雷姆两人来到了餐厅。发现持续进行著准备的拉姆，雷姆急急忙忙地赶到身旁。

「姊姊，很抱歉将工作交给您处理。姊姊还忙得过来吗？」

「只是平常工作的延伸，而且很难得看到雷姆会任性提出请求。雷姆才是，有没有好好享受一下？」

「有的，请姊姊期待明天以后的雷姆！」

她似乎受益良多，见到平时总是乖巧的雷姆如此得意地回答，让拉姆忍不住疼爱地摸了摸她的头，妹妹也似乎很痒地眯起眼睛。

「既然之前在厨房的雷姆回来，表示差不多该上菜了吧？」

「是的，因为对方表示不需要帮忙配膳，还要雷姆与姊姊就座。姊姊，坐在我旁边吧。」

「呵呵，别这么兴奋，真是没礼貌呢。」

被迫不及待的雷姆拉著手，拉姆也弯腰坐在自己的位置上，能够见到身旁的雷姆难掩兴奋地望著餐厅入口。

「昴没办法享受到这顿餐点真是太可怜了。」

「……只要雷姆尽情告诉他感想就好了。」

「──好的！真不愧是姊姊，不知道这样能不能让昴开心呢？」

「他一定会痛哭流涕吧。」

但拉姆没有表示是欣喜或是悲伤所流下的泪水。

两姊妹的对话到这里暂时告一段落，同时餐厅的门扉敞开，身为今晚餐厅主角的究极厨师也随著现出身影。

「让各位久等了喔，各位有没有等很久了喔？」

男子晃著一身肥肉环视著餐厅，视野所及之处皆是曼妙的美少女，让他发出喘息声，满意地点了点头。

「没错，就是这样喔。边境伯大人说得一点都没错。那么，既然已经准备好也确认过了，差不多该是上菜的时候了喔。」

「好的，麻烦您了。」

尤其是被毫不客气的视线打量全身的爱蜜莉雅，仍然一副无所觉地浮现出悠哉笑容。

她天真地满心期待著美味的料理，让从旁侧眼观看的拉姆担心著这场餐会究竟会有什么样的结果。

然而──

「──本小姐也可以一起出席吗？」

却演变成甚至连拉姆都没想到的状况。

「────」

那是一道听来莫名清澈却有些沙哑的曼妙声音。

是个照理说不可能出现在此处的第三者，这个突如其来的人的出现，让全员吃了一惊，不禁将视线转向餐厅入口。只见有个身穿鲜明黑色礼服的人正站在视线前方。

一头艳丽的黑棕色长发，搭配一身包覆以女性而言算是高挑身材的漆黑礼服，以及化著稍浓口红的嘴唇、增添视线魅力的眼线与长长睫毛。肩上披著薄纱领巾，踩著高跟鞋前进的优雅姿态甚至散发出一股气质。

见到这名突然闯进晚餐的入侵者，众人皆怀疑著自己的眼睛并屏起气息。

面对此种景象，该名人物一副理所当然地微微歪著头露出微笑。

「怎么了呢？是本小姐呀。──是夏美•舒瓦兹唷。」

在众人无言的视线环视下，那个人若无其事地以高雅语气如此报上名号，以令人惊艳的完美动作完成了屈膝礼。

「──！」

从一开始的震惊中打起精神后，拉姆迟疑著该做出什么样的行动。总是倾向于速战速决的拉姆很少出现此种犹豫，这表示眼前的景象是多么超乎想像。

即使入侵者有股令人难以移开视线的吸引力，拉姆还是勉强将脸转向罗兹瓦尔。究竟身为现场负责人的主人会对这种状况做出何种判断──

「────这、这还真是抱歉呢，夏美小姐。来，请坐吧。不好意思，可以从现在再多一个客人吗？」

──餐会继续进行！！

罗兹瓦尔表示款待的模样，彻底地阐述出此种赤裸裸的事实。

那位带著奇特风格的贵妇微微一笑，扭腰摆臀地穿过那位胖男身边，擦身而过时还轻轻抚过胖男的下巴与颈项，模样充满了妖艳的魔力。

男子忍不住上下摆著头，就这样连忙离开餐厅准备上菜。

可悲的是，餐会的主角一瞬间由厨师转移到那位贵妇身上。

贵妇目送男子离开后，便以优雅步伐自然地坐在爱蜜莉雅旁边的位置。

「可以坐在这里吗？」

「好美的人喔……啊，请坐请坐，对不起。罗兹瓦尔真是的，有这位客人在都不说。」

爱蜜莉雅难掩惊讶神情，一副理所当然地与那位贵妇说著话。

拉姆朝她们两人以外的成员瞥了一眼，只见雷姆与碧翠丝的反应各有千秋──碧翠丝歪著嘴角带著难以言喻的表情。另一方面，雷姆微微红著脸，能够感觉到她似乎正在与莫名冲动天人交战。

至于唯一能够倚靠的罗兹瓦尔，则是弯著腰趴在桌面上。

「没想到……居然……会来这招……」

他拚命地忍耐著涌现的笑意，让拉姆放弃当场出声追究。

「我还以为他在搞什么鬼……毛真是太可怕了。」

贵妇夏美•舒瓦兹──也就是菜月昴的女装虽留有原先的影子，但几乎化为女性的模样完全骗过爱蜜莉雅，表示是如此完美得令人头皮发麻。

9

以完美女装获得爱蜜莉雅邻座的夏美•舒瓦兹──应该说是彻底装扮为架空女性的菜月昴，对于此种颇为顺利的感觉暗中露出邪恶表情。

『可是还不能大意喔，昴。』

──我知道，不会穿帮啦。

昴一边在化过妆的脸上带著微笑，一边对帕克直接传进意识的声音微微低下头。

这是藉著精神感应的超能力，简单说就是心灵感应。昴能够藉著此种能力与帕克零距离沟通，并且构筑出名为夏美•舒瓦兹的假象。

发现这场餐会中暗藏的阴谋后，昴配合事前得到的厨师情报，判断只有这个方法而下定决心扮女装。

幸好他并非是首次女装，因此很清楚详细流程。

──毕竟我可是在高中入学典礼上完美扮装，整整骗了所有人三天！

原因或许是对化妆出乎意料地擅长，以及「昴」这个男女皆可通用的名字。以前他曾经为此参加班上的女学生团体，差点就得以女学生的身份高歌学校生活了。

『总觉得不太想问最后有什么结果呢。』

──嗯，你问了只是把旧疮疤挖开，就别管这件事啦。

这番关心的心灵感应让昴低下头，重新确认自己的女装是否凌乱。

他以较浓眼影遮盖三角眼的锐利目光，用假睫毛与道具暂时画出完美的双眼皮，以化妆改变肤色并以鲜艳唇色产生对比，然后从服装储藏室借来黑棕色的长假发。遮盖男性体格的礼服也是同样从服装储藏室找来，这应该是从前体格较大的女仆曾在宅邸工作用的服装。

哪天要是实际见面，一定得对今天的事向对方道歉。

然而目前多亏如此，才得以完成夏美•舒瓦兹这名女性。

只要能打理好外表，对手脚灵活的昴而言，靠言行举止扮演出贵妇的模样可说是易如反掌。就连他自己都觉得扮演得比想像中更好。

但唯一昴无法靠自己解决的部分就是声带，以前扮女装最大的失败处，就是在第三天因为低沉声调彻底穿帮。

不过，昴这次活用上次失败的反省，靠著伙伴的协助克服了这个问题。

「好期待会有什么料理呢。爱蜜莉雅大人，您对礼仪有自信吗？」

「咦，我吗？呃……我还在学习，不过我得好好努力尽可能别丢脸。」

「喔呵呵，说得也是。可不能对餐点太过忘我了呢。」

贵妇夏美将手抵在嘴边露出微笑，大方地与爱蜜莉雅说著话。声音并非是低沉的男性声调，而是给人莫名中性印象的沙哑声。这并非是昴的个人技术，而是借助伙伴力量的部分──也就是帕克的声音。

帕克目前正躲在贵妇夏美披的领巾内，在胸前处偷偷代替昴回答。

简单说这就是双簧──由昴与帕克两人组成了夏美•舒瓦兹。

「──」

拉姆与碧翠丝持续对贵妇夏美的侧脸投以目光。

她们浅显易懂地皱著眉头，当然已经发现贵妇夏美的真面目就是昴。但这并非是女装的品质问题，而是没有其他人选可猜了。

另外，雷姆也以同样理由紧盯著贵妇夏美，但仍然是一如往常的慈母般眼神。虽然无法得知内心在想什么，但既然选择静观变化没有揭穿，就表示能暂时将她们视为同伴。

接著，说到这场作战中最需要警戒的「敌人」罗兹瓦尔──

「噗……呵呵……」

他似乎纯粹乐在其中，完全没有追究贵妇夏美真面目的意思，当初昴猜想「如果是罗兹瓦尔肯定不会放过这个乐子」可说是正中红心。

顺带一提，身为问题核心的爱蜜莉雅似乎真的没有察觉贵妇夏美的真实身份，感觉能一口气趁势瞒到餐会结束。

E（爱蜜莉雅酱）•M（真是）•T（天使）。爱蜜莉雅酱真是天使。

「──让各位久等了喔。」

厨师迪亚斯下略回到餐厅，仔细地将一盘盘料理配送到桌上。

当白色盘子上的银盖掀开时，盘子上能够见到看似白肉鱼经过调理的料理，浓郁的香气朝意识给予重重一击。

「这是炙烤莱特•罗伊鱼再淋上拉格蒂酱喔。」

严格说来，他说明的料理名没有半个字听得懂。

然而，表面稍经炙烤的白肉鱼缠绕著黄色与绿色的酱汁，滑进鼻腔的温暖香气直接一把紧紧抓住胃袋，让唾液大量分泌并传来一股晕眩感。

『喂喂！昴！』

──啊！好、好危险！

在开始狼吞虎咽的前一刻，帕克的声音让昴顿时回过神。

别说是女装，差点连社交地位都会一败涂地。转头看向旁边，只见爱蜜莉雅也对料理惊讶地瞪大双眼，其他成员或多或少也是同样的反应。

此种接近暴力的美味预感，搭配强迫遵从餐桌礼仪的名厨，可说是最麻烦的组合。

香气中具有让人性破壳而出并唤醒野生本能的力量。让昴──不，应该说是贵妇夏美将涌现的唾液吞回肚中，比任何人皆早一步拿起刀叉。

『没问题吧，昴？』

帕克用心电感应确认著昴的决心，昴则是咧起嘴角露出邪恶笑容点了点头。

──既然这样一不做二不休，看我比所有人都快解决这盘料理！

「哎呀，看起来还真美味，甚至让人舍不得吃呢。」

搭配嘴唇的动作，帕克扮演出贵妇夏美既高贵又积极的个性。

为了坚守且不输给此种精心扮演的态度，昴努力让自己维持镇定，将意识集中在眼前的料理上，以完美的餐桌礼仪开始享用白肉鱼。

他用叉子按著鱼身，用刀子切下一口尺寸的肉。由于火候控制得无可挑剔，光是叉子碰到的瞬间便让鱼肉崩解，与酱汁互相缠绕形成的视觉冲击蹂躏著脑部。只能屏起气息避免被此种美观击败，并且以心灵抵抗嗅觉传来的佳肴预感。

现在要是被吞噬就回不来了。

别说是为爱蜜莉雅指引道路，连昴都有可能会被料理迷失自我。

──要以钢铁般的自制力，以及对爱蜜莉雅的心意为武器，攻略这道料理。

重新下定决心并睁开眼睛后，昴将叉子上的一口肉缓缓送向嘴边。

「────」

顺序、姿态、举止、气质以及其他各种因素皆流畅得美不胜收──而此种努力与意志的成果，在料理接触舌尖的瞬间便随之崩毁。

昴以为自己的眼珠差点要掉下来了。

压倒性的味觉暴力透过舌头刺遍全身，不论是思考的脑、全身的血液、支撑肉体的肌肉、骨骼、细胞，让昴不成熟的决心与觉悟瞬间瓦解。

遭到蹂躏、凌辱与击溃，回过神时昴发现自己已经崩溃了。

「──怎么了喔？」

不知何时，贵妇夏美已经静静地从椅子起身，踩著高跟鞋来到迪亚斯（名字太长以下略）的面前，然后面对他那满腹狐疑的表情静静地吸了一口气并跪倒在地。

接著──

「──我完全低估手艺了，真的很对不起！」

他将额头抵在地面，以昴本身的声音表明全面降伏。

『真是输得太彻底了呢……』

躲在胸前的帕克用心电感应如此呢喃，但确实如同他所说彻底败北。

昴受到的冲击也传达给心电感应的帕克，失败感也是共同享有。

因此，昴将此种感动与失败感原封不动地朝迪亚斯（以下略）低头赔罪。

「这道料理真的很好吃。我原本想高雅地享用这道料理，可是完全没办法，我想不管是谁应该都是这样。我觉得遵守礼仪享用料理很合理，可是一边互相谈论对料理的感想，然后一边带著欢笑享用应该也很不错。这是我个人的想法啦！」

贵妇夏美完全无法看著对方的脸──不，应该说是昴拚命地说出自己的感想。

这既是藉口，也是败给阴谋之后的丧气话，然而这也是打从内心深处毫不吝惜的赞赏。表示这道料理蕴含著令人如此无法遵守礼仪的魅力。

面对这道没头没脑的称赞与丧气话，迪亚斯（以下略）顿时瞪大双眼。

这也是很理所当然的反应，至少得让被斩首的人只有自己就好──

「──哇哈哈哈哈哈！」

一道突如其来的笑声，让昴此种接近祈求的心情被完全颠覆。

昴随即抬起脸，发现有个人影在餐厅入口发出肆无忌惮的笑声。那是个既娇小且用头巾将整个头包住的人──

「哎呀哎呀，真是太让人惊讶了。没想到居然会有闻吾辈风评而来，却又找著『用餐时应有的态度』当成藉口想试图脱罪，再怎么耍小聪明也该有个限度。」

那个人一边说著，一边将包著头的头巾掀开露出脸。即使说话语气很老气，却是个声调高亢且带著不合稚嫩长相大胆笑容的少女。

原本以为这位少女是迪亚斯（以下略）的随从，她的突然闯入让昴顿时哑口无言。但那名少女望著昴的滑稽嘴脸，似乎很愉快地露出牙齿咧嘴一笑。

「很少有客人完全臣服于吾辈的料理，还出现那么干脆的反应。原来如此，边境伯也真是坏心眼，当初说吾辈也会很中意是这个意思啊。」

「我觉得他是个会说出老实感想的合适人选啦。不过依我个人来说，真正用意是另一边……总之这样也可以啦。」

对于少女呵呵大笑说出的话语，罗兹瓦尔带著苦笑表示同意。昴对他们的对话一头雾水，正当他歪著头思考「这是怎么回事？」时……

「关于师傅有很多传闻，不过全部都只是随便乱说的喔。师傅也不否定在旅程中被加油添醋的传闻，用绝佳美味玩弄那些彻底相信传闻的人，一直都是师傅的坏习惯喔。」

对于昴的疑问，那位迪亚斯（以下略）如此回答──不，从刚才那番发言判断，看来他并非是迪亚斯（以下略）。

「这么说来，真正的迪亚斯（以下略）是……」

「是吾辈。顺带一提，没有被好好叫出全名会不愉快的传闻不是假的，因此给吾辈好好记住，别忘记了。」

少女挺起胸膛并用力踩著地面。

「吾辈之名乃迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世！挑战传闻并见证人们与味觉纠葛的模样真是太有趣了！真是有趣！」

少女──真迪亚斯（以下略）发出此种豪迈笑声，让昴只能哑口无言地看著对方。

真迪亚斯（以下略）走向昴，伸出手让他站起身。回过神时，昴发现自己已经被完美的姿势引导回原本的位置就座。

「真是颇为像样的变装，这也是相当不错！既然如此，吾辈也得不服输地以拿手领域应战！罗德利格斯，过来帮忙！」

「好喔，师傅！」

很有男子气概地如此宣言后，真迪亚斯（以下略）便带著徒弟罗德利格斯冲出餐厅。

餐会持续进行，静待下道料理──照理说应该是这个样子，但过程可说是如同一阵风暴。

「那么，既然也顺利通过传说厨师的洗礼了，就开始继续用餐吧～～让我们为昴……应该说是夏美小姐的英勇牺牲干杯。」

以这句话为契机，罗兹瓦尔高举酒杯为昴的牺牲发出声援。

「干得不错，毛……不对，应该说是夏美•舒瓦兹小姐。」

「真是丢脸丢到家了，不过哥哥还是一样很帅气呢。」

「夏美小姐真是太棒了，雷姆觉得这样真的很美丽。下次请务必让雷姆帮忙化妆与换装。」

接在罗兹瓦尔后面，拉姆、碧翠丝与雷姆三人皆对昴的失败打分数，让昴如果有个洞实在很想钻进去把自己埋起来。

而对于怀著此种心情的昴，身旁的爱蜜莉雅拍了拍他的的肩膀。

「我不太懂是怎么回事，可以问个问题吗？」

「……请说。」

昴最为战战兢兢地等待著爱蜜莉雅的话语。接著，爱蜜莉雅竖起手指抵在脸颊上，并且可爱地微微歪著头。

「声音听起来很像昴，您是哪位？」

没错，在各种失败感中，最高级的挫败感毫不留情地倾泻而下。

『锵锵～～』

昴──不，应该说是在贵妇夏美的胸前，帕克带著松懈的笑容以心电感应做出结语。

10

「看来是个颇有收获的餐会呢。」

收拾完经商工具后，背著大包包的迪亚斯发出爽朗笑声。

在玄关大厅目送著她离开的罗兹瓦尔回以苦笑。

「很抱歉寒舍没有人可以出来送行，大家都被餐点迷得神魂颠倒了……让雷姆学到这么多真是帮了很多忙喔。」

「不论是谁，只要是想追求味觉极致之人皆相当欢迎。她的资质很不错，要好好珍惜。」

对于几乎将烹调过程望穿的那名少女，迪亚斯对雷姆相当中意。接著，见到身旁的徒弟罗德利格斯抬起头并带著难过表情，于是轻轻顶了顶他的肩膀。

「怎么，罗德利格斯。别对启程露出那么无趣的表情，好好抬起胸膛。」

「小的一直是这么想的喔，不用这样恶作剧，用平常的方式展现厨艺就好了喔。这样小的也不用摆出那种助长好色奇怪传闻的态度了喔。」

「不行！就是要用味觉粉碎那些尽信谣言、还摆出一副若无其事态度的家伙才有趣！而且只要你没改掉那个奇怪口音，那个好色传闻就不会消失！」

「口音是说什么喔？」

迪亚斯对毫无自觉口音的徒弟别过头，朝罗兹瓦尔举起手。

「那么，差不多该告辞了。这个世上还有许多吾辈追求的味觉，太多邀约实在是令人头疼啊！想好好捉弄一番的家伙总是多到数不清！」

「真是个对工作乐在其中的人呢～～」

「这是吾辈的兴趣，赌上生涯的兴趣──而且……」

迪亚斯打断话语，用手粗鲁地将包著头的头巾扯了下来。从下方显现出一头美丽金发，以及比普通人稍长的耳朵──

「是要让身为妖精族的吾辈，与那个半妖精女孩见面才是最重要的目的吧？」

「……说不定那孩子前进的道路能够弭平种族歧视。那样的话，你也不用隐瞒自己的身份，躲在徒弟后面持续旅行了。」

「哈，别做那种无聊的分析。宫廷小丑，吾辈是自己想这么做的，而且吾辈也没有打算四处散播支持那女孩的意思。」

迪亚斯闭起单边眼睛，露出牙齿咧嘴一笑后便再度戴起头巾，然后豪爽地转过身背对罗兹瓦尔并迈出步伐。

「话虽如此，和那个女装少年同样，那个女孩的直率感想也不错。所以有什么事再出声吧，只要有大展厨艺的要求，吾辈都不会拒绝。」

「我可以相信这算是良好的关系吗？」

「随便你。喔，对了。」

对持续纠缠的罗兹瓦尔表示服输后，迪亚斯竖起指头彷佛想交换条件。

「下次也想听听老实的意见，在那之前可别放掉那个半妖精女孩和女装少年。还有，下次有机会也要让那个少年扮女装。」

「如果这样可以的话，我很乐意。」

当成这是爽快允诺的证明，罗兹瓦尔趁著当事人不在场擅自答应女装的要求。

接著，迪亚斯带著罗德利格斯准备踏上下个旅程。

「一时之间还不知道会怎么样，总之这样就与迪亚斯•雷本卓•艾雷曼索•欧普连•法兹巴鲁姆六世做个人情了。」

虽然还有许多地方都有问题，但完成当初的目的，还是令罗兹瓦尔松了一口气。

今后还有很多令人肩膀酸痛的问题，不过今天并非是如此充满压力。

「不过话说回来……哎呀，那真是太优秀了。」

脑中浮现出昴完美扮成女性的装扮──也就是夏美•舒瓦兹的模样。

看来暂时不愁没有捉弄他的藉口了，可说是相当有意义的餐会。

不论是视觉或记忆，除了他以外的人应该也在味觉上充分获得享受的时光。

「噗……哈哈……啊哈哈哈……」

罗兹瓦尔一边怀著此种感想，一边忍不住发出笑声。

在没有任何人看见的场所，以不让任何人看见的表情毫不顾忌地放声大笑。

──罗兹瓦尔就这样独自持续笑著。

** 『佩特拉眼中的世界』

1

──对佩特拉•莱特而言，世界可说是十分狭小。

在梅札斯边境伯的领地，佩特拉诞生于小村落「阿拉姆」的莱特家。

佩特拉既没有天生受到加持，也不是诞生在富裕家庭。只是在极为平凡的村子、极为平凡的家庭、以一名极为平凡的村落女孩健全地成长。

阿拉姆村毫无值得特别书写之处，只是个随处可见的贫寒村落。

除了领主边境伯的宅邸座落于村子附近，没有任何特别著称的特色，顶多只有比起其他领地拥有较多见到领主的机会吧。

而此种珍贵的机会，要求仍年幼的少女理解，实在是很困难的事。

话说回来，身为领主的罗兹瓦尔•L•梅札斯这个人也是性格迥异，首先光是行径便与传闻中的贵族毫无相符之处。

喜欢顶著一脸类似童话中小丑的化妆，以及穿著特立独行服装的模样，让见到的人与其说是敬畏，倒不如说是困惑。

──如果领主大人不像样，会让身为领民的我们相当辛苦。

那是佩特拉从图画故事书，以及大人们的对话依稀留在脑中的观念。而身心稚嫩的佩特拉也发现了领主似乎并非是个具有正常人格的人。

实际上，领主以视察村落名义偶尔随兴造访时，态度总是很奇怪。

即使贵为领主却不卖弄权势，有时会对大人们捉弄开玩笑，或是说著莫名其妙的话让金发女仆伤脑筋，总是四处胡闹留下混乱便擅自离去。

佩特拉无法理解村长那些大人为何只是笑著带过，她曾经对领主正面抱怨过这件事。然而──

「哎呀呀，这还真是严格呢。不过能对我说出这件事，表示你是个有勇气的女孩，希望你别忘记这种勇气好好珍惜培养喔～～」

他只是将佩特拉的愤慨视若无睹，不知为何还似乎很高兴地摸了摸她的头才离开。

从那之后，佩特拉理解到即使告诉领主也是无济于事，于是放弃继续追究他特立独行的举止。

描述至此，将故事焦点由领主拉回到「佩特拉」这位女孩上。

如同前述，佩特拉至今的人生便是在毫无特色的村落中做为一位平凡女孩，若要借用领主曾经说过的话，也可以冠上「有勇气的少女」这个头衔。

而在村落中以一介女孩成长的佩特拉，在懂事的同时也自觉到一件事。

那就是萌生了「自己似乎比村落其他孩子还可爱一些」的自我意识。

事实上，佩特拉的容貌即使稚嫩，但确实可说是十分具有魅力。

斗大圆眼、樱色双唇、细长手脚搭配白皙肌肤、泛红的橙色头发既细腻且轻柔地随风摇曳。佩特拉此种既稚嫩且楚楚可怜的容貌，在村中甚至被誉为将来肯定会成为绝世美女。

像这种孩童的自我意识实在不能随便轻忽。

若要附带说明，那就是佩特拉不只是容貌，也比其他孩子还要来得更聪明一些，但这可归类于小聪明的范畴。

与生俱来的美丽容貌，让佩特拉认为这等同于是获得保佑或天赋异禀。

因此，巧妙地利用此种容貌活下去也是理所当然的事。

──例如稍微玩耍之际让物品损坏时。

──偷吃田里香甜的橙橘时。

──照顾家畜却偷偷翘班跑去与朋友玩耍时。

面对大人的怒气，佩特拉总是彻底善用自己的可爱容貌。

光是佩特拉泪眼汪汪地垂著头表示反省，大人便会无法继续强烈斥责。而只要她受到宽恕，当然也会无法再责骂其他孩子。

面对唯一能够跳脱此种藩篱、具有责骂立场的双亲，由于爱女总是在面前扮演著乖孩子的模样，而被蒙在鼓里，让她就这样顺顺利利地被养育成一个小恶魔。

──只要与佩特拉在一起，就能得到疼爱。

即便是孩子……或许该说正因为是孩子，才会毫不犹豫地因为此种好处而贴近佩特拉。村里的孩童自然地越来越常以佩特拉为中心聚集，结果更加助长了佩特拉的气焰。

被村内的男生拱上天、被村子的女孩子倚靠、被大人们疼爱，让佩特拉给予了自我意识花朵水分，并且持续日益壮大。

误以为世界是以她为中心运转，也是从这个时候开始的。

不论如何，包含此种误会在内，孩童本身仍然是相当可爱。

即使说是气焰增长，佩特拉的行为并没有超越恶作剧孩童的领域，呼朋引伴做出的行动也不过是小小村落中发生的事。

世界的中心佩特拉•莱特──当她发现自己如此误会，并且稍微得知世界的宽敞程度，是在萌生自我意识的数年后……也就是十岁的时候。

那天，阿拉姆村罕见地有位以绢织品经商的旅行商人造访。

据说那位商人是为了喜好奇装异服的领主而购买了几种珍奇布料回到村子，而回程途中在阿拉姆村摆摊开始贩卖。

「有西方卡拉拉基、南方佛拉基亚、还有王都露格尼卡流行的各种款式喔。」

见到商人随著这些推销话语摆出的商品，让佩特拉的世界顿时一变。

被色彩鲜艳的布料夺走目光，让少女瞬间陶醉于幻想之中。

回过神时，她已经用自己的可爱容貌将商人与双亲玩弄于股掌之间，并且得到几种布料，在自己房间毫不厌倦地持续盯著布料。

那成为任何物品都无法取代的宝物，并且让她诞生了一个梦想。

2

──岁月如梭，佩特拉就这样怀著梦想来到了十二岁。

到了这个年纪，不只是心灵，连身体也开始出现变化。

不仅仅是孩童特有的稚嫩，身为女性也开始渐渐准备绽放花朵。

即使含苞待放，自傲的楚楚动人模样仍然健在──或许该说随著自觉一同磨练，变得更加千锤百炼且灿烂耀眼。

而十二岁的佩特拉在村子仍然是孩童的中心，在大人眼中也是既聪明又活泼可爱，但她正在自己的房间不满地鼓著脸颊。

原因是佩特拉所怀抱的梦想。

在那天偶然感受到的震撼，于佩特拉心中随著岁月日益增长。即使从那过了两年，宝物仍然毫无褪色地珍惜保管。

接著，原先朦胧模糊的憧憬越来越具体，让佩特拉掌握了一个梦想。

──将来想前往王都从事制作服装的工作。

随意将漂亮的布料装饰，制作出既可爱又帅气的服装。那天被夺走目光后，对各种衣物的憧憬让佩特拉怀著此种梦想。

仔细想想，佩特拉会不太喜欢领主的理由，或许也是看不惯他的服装。他的服装穿著真是糟到极点，那是对服装的亵渎。

先不论对领主的愤怒，佩特拉会如此不满还有更深的原因。

那就是当她如此对梦想有所自觉，并且为了实现梦想而努力练习裁缝时，周遭却并非对她怀著肯定的态度。

尤其是周遭的孩童，他们的反应可说是令人惋惜。即使偶尔对他们提到未来的话题，却从来没有出现过期望中的答案。

榴卡只会流著鼻水回答说要与父亲同样继承樵夫的工作，米尔德只要想著困难的事就会肚子咕噜咕噜叫，岱因与凯因两兄弟只会吵著哪边要娶离开村子的佩特拉为妻。情同妹妹的梅伊纳虽然很令人疼爱，但只要说出要前往王都，就总是会开始哭哭啼啼。

到了这个地步，佩特拉品尝到孤独的滋味。

虽然周遭的孩子很倚赖佩特拉，但佩特拉却没有能够信赖的朋友；即使向大人说出这件事，也顶多会被笑称是做白日梦。

为什么会这样？可爱就是这么孤独。

对于凡事皆是以可爱解决的佩特拉而言，这是令她难以置信的现实；面对只靠可爱无法解决的状况，佩特拉首次尝到挫败的滋味。

结果，佩特拉只能将梦想与烦恼藏在心中，过著闷闷不乐的日子。

将来只要再长大一点，再变得更可爱一点应该就能解决了吧？

总之她将希望如此寄托在未来的自己身上。

某天，怀著此种烦恼的十二岁佩特拉再度体验到某个神秘的经验。

那是她与朋友们前往附近河岸钓沙蟹的途中，虽然不想弄脏衣服的佩特拉只在旁边观看，但与朋友一起玩耍仍然是相当快乐。即使对将来的事感到担忧，但这是另外一个问题──就在这个时候……

「嘿嘿！那边经过的小孩，你们知道这个村子地位最高的人在哪里吗！？」

有位黑发少年如此说著，以装熟的模样朝孩童们搭话。

他的眼神看来邪恶，长相也散漫毫无威严。明明是嘻皮笑脸，穿的服装却是颇为正派。

完全不符合他的个人风格。表情实在差衣服太多了。

但多亏此种不合适的装扮，佩特拉随即料想到对方的来历。

「啊，是领主大人宅邸新来的佣人吗？」

「嗯，没错！真不愧是佩特拉！真聪明！又是全村最可爱的！」

「……我有说过自己的名字吗？」

「唔呃！」

被佩特拉这么一瞪，那名拍著手显得很兴奋的少年顿时发出呻吟声。

明明是个陌生人，突然被叫出名字让佩特拉一口气提高戒心，其中也怀有被一开始叫声吓到的怨恨。他是在哪里知道自己名字的？

「呃……就是因为那个啦！就是村子里最可爱的美少女！说到阿拉姆村的佩特拉，连在罗兹瓦尔大人的宅邸都是声名大噪啦！知道吗？」

「咦……在领主大人的宅邸？怎么会……我好害羞喔……」

「当然当然！应该说这是必然的结果！哎呀，本人比传闻中还要可爱百倍呢，哈哈哈！」

见到佩特拉将手抵在脸颊并垂下头，先前手忙脚乱的少年明显地松了一口气。而佩特拉对这位少年相当害臊──应该说是装成害臊的模样偷偷观察著他的反应。

即使服装看起来像是宅邸的相关人士，但仍然不能随便相信。以前有个出入领主宅邸的男子，就常常紧盯著佩特拉等人，虽然长相帅气，服装也很合身，但视线总是让人坐立难安。

至于仔细观察后，能够发现那个人与这位少年身穿同样服装，让佩特拉对「同样服装竟然会因人产生这么大的差异」而感到颇为吃惊，并且告诉自己千万不能大意，就像可爱也代表著危险。

「我叫菜月昴！一气呵成的见习管家！是从昨天开始借住在罗兹瓦尔大人宅邸的劳苦人，大家要好好对待我喔！」

那名少年──昴没有察觉到佩特拉的疑虑，而是吵吵闹闹地自我介绍。

这份自我介绍没有成人的沉著稳重，各种言行举止丝毫没有遵照礼仪，有种看扁对方是孩童的感觉，缩短距离的方式可说是让人不舒服。

简单说来，对佩特拉而言，初次见到昴的印象简直是糟糕透顶。

但不知是否喜欢那种既不像大人也不像小孩的态度，一开始显得不知所措的榴卡与米尔德很快与他打成一片，而且玩得十分愉快。

既然这样，形同孩童代表的佩特拉也不得不接受他。

「……所以呢？村子地位最高的人，你找那个人有什么事？」

「哎呀～～因为有个女仆学姊要我把这个交给对方，总之就是跑腿啦！」

「喔……我知道了。那我带你去村长伯那边吧。」

她带领著背著榴卡、腰部还勾著米尔德与岱因而带著苦笑的昴，连恶作剧都不会生气这点也让佩特拉觉得很好捉弄。

顺带一提，虽然村子地位最高的人其实是米尔黛村长，但佩特拉故意将他带去见看起来比较像村长的拉斯福姆（村长伯）。

之后他应该会在宅邸被狠狠修理一顿，光想就觉得很有趣。

隔天，那个新加入宅邸的佣人在村子蔚为话题。

毕竟是个小村子，虽然不会出现大骚动，但只要有点小事便会立刻传遍村子。尤其是领主宅邸的人会频繁来到村子采买物品，因此接下来会时常见面的对象是什么人当然会成为话题。

「呃……还不太知道，不过感觉不是个坏人。」

被双亲询问后，佩特拉以普通回答如此敷衍了事。

由于昨天曾经帮带路，有许多人向曾经接触过昴的佩特拉确认传闻真相。虽然其他孩子也有被问到，但大人果然还是较为信赖佩特拉。

她对昴没有什么好印象，不过与其他孩子说出不同答案也不太好，要掌控可爱的印象也是颇为辛苦。佩特拉敷衍过接踵而来的问题并深深叹了一口气。

「……咦？有个没见过的孩子。」

穿过大人们包围并逃到村外的佩特拉瞪大双眼，因为眼前有个将淡褐色头发绑成发辫的少女──这也是她连续两天见到陌生人。

「你在这里一个人做什么？」

「啊……」

比起前几天的对象，佩特拉毫不犹豫地对少女搭话。少女对她的呼唤回过头，即使在佩特拉眼中看来也算是颇为──不，应该说是相当可爱。

虽然服装朴素，头发也没有装饰，但长相可说是具有潜力的极品，让佩特拉涌现出一股很想好好装饰她一番的欲望。

对于努力钻研自身可爱的佩特拉，对他人的可爱也是相当敏感。尤其特别讨厌浪费自身特质，因此对母亲与梅伊纳皆费了不少苦心。

对于这位少女，佩特拉也有种想将自己的可爱精神灌注其中的冲动。

「我叫梅莉，因为家人有点事，暂时寄住在这个村子。」

自称为梅莉的少女露出微笑，看来是个很乖巧的孩子。

虽然会立刻回答问题，但不太会主动说话。与梅伊纳的个性很像，这也让佩特拉涌现出身为姊姊拉她一把的心情。

「过来吧！我介绍大家给你认识，我是佩特拉，是你的朋友！」

将内向的梅莉带过去后，榴卡他们也立刻接纳了她。

孩童之间一旦混熟便很好说话，梅莉转眼间成为了佩特拉等人的同伴，那天在村子中四处游玩并加深感情。

「过来吧……这孩子好像是母的。」

「哇，好厉害好厉害！梅莉好像会跟动物说话！」

在玩耍的过程中，最让佩特拉等人开心的就是梅莉饲养的小狗。这只深褐色毛皮的小狗似乎是梅莉带来的，而且很不怕人。简直就像听得懂梅莉的话语般表演技艺的模样，让孩童们看得陶醉不已。

「梅莉，明天绝对也要一起玩喔！」

夕阳西下告别时，佩特拉握著梅莉的手并约好明天还要一起玩。梅莉害臊地点了点头，佩特拉则是满足地回到家中。

「今天啊，我交到了一个新朋友。看她一个人，我就找她一起玩了。」

佩特拉在晚餐餐桌上回顾这天的事并如此说道，双亲带著赞许的神情夸奖著她，这也是满足佩特拉自尊心的一个要因。

虽然梅莉也是个好孩子，不过是佩特拉对独自一人的她伸出援手。自己不只是可爱，而且还做出体贴的举动，这样肯定又朝王都更接近了一步。

佩特拉就这样怀著小小的盘算，并且舒服地坠入梦乡。

隔天，佩特拉一如往常地醒来，一如往常地出门玩耍。

在这个毫无变化的一天──她无法得知命运随时会伪装于日常生活之中。

「久等了～～今天要做什么？」

在日正当中的时刻，上午与榴卡等人约好见面后，接著在村外与梅莉会合。正当他们讨论著今天要做什么时──

「啊，是昴！」「咦，是昴耶！？」「好耶，昴来了！」

榴卡他们突然露出灿烂笑容并一起拔腿奔跑，只见不适合制服的昴站在他们前方。虽然他对孩童们的气势吓了一跳……

「唔喔喔！来吧，看我的厉害……噗哈！」

他张开双手试图接住孩童们，但完全无法挡下，榴卡、米尔德再加上岱因凯因两兄弟撞了上来，昴一群人无法抗拒地跌倒在地。

「真是的，大家别做这种蠢事啦！昴，你没事吧？」

「呃……没事没事，我太相信自己的力气了，好丢脸。」

对跌坐在地的昴如此问道，他带著苦笑搔了搔头。昴的模样让佩特拉不解地歪著头，虽然只有两天没见，但他与先前的印象可说是截然不同，那时候没有什么余裕，但模样看起来还是挺蠢的。

「昴，昨天发生了什么事？」

「咦，没、没没没什么啊！？我绝对没有在喜欢的女生大腿上大哭一顿，然后还流著鼻涕呼呼大睡喔！？」

「哼嗯……」

明明没问却被否定。总之他似乎不是在某个人腿上哭哭啼啼，然后还流著鼻水呼呼大睡，不过有可能很接近就是了。

「好吧，算了。」

比起前天的昴，现在的昴在佩特拉眼中看来顺眼许多。虽然不知道榴卡他们是怎么想的，但总觉得似乎能稍微好好善待他一番。

「所以呢，今天也是出来跑腿吗？」

「也有要跑腿的事，不过现在是自由时间。所以我稍微出来巡视一下村子……喂，别爬到背上！别把鼻水沾到我身上！我没说沾鼻屎就可以喔！？」

「呃……需要帮忙吗？」

「……麻烦了。」

昴的全身被榴卡等人紧紧抓著，拖著他们前进的模样让佩特拉有些同情。于是她一边陪著昴巡视村子，一边怀著难以言喻的心情四处向村子的大人介绍昴。

被称为村长伯的拉斯福姆、真正的村长米尔岱、统率领导村年轻人的马基西、以及偶尔会戴著面罩而不为人知的马基西等等。

就这样帮忙介绍昴给大家认识时……

「嗯……既然这样就得来试试那个了。包含出道仪式在内，干脆聚集村子的人来场演讲好像也不错。」

「演讲？」

「我会来个很夸张的打招呼，告诉大家希望接下来能好好相处啊。」

如此说完后，昴露出恶作剧孩童般的笑容。

见到此种天真无邪的笑容，让佩特拉首度对昴怀有好感。

3

「胜利～～！」

「──胜利！！」

对昴首度浮现的好感，就在莫名其妙的舞蹈中被抵销了。

那个牵连许多村人的「收音机体操」，让佩特拉正值青春期的心灵深深受到羞辱。然而榴卡等人又很喜欢这种体操，而且还连带影响到大人们，让被抵销的好感更加恶化，也让佩特拉更加讨厌昴。

说讨厌或许有些过头了。应该说是不擅长面对、不拿手、而且服装完全不适合长相。

「只有你懂我的心情了……」

摸了摸梅莉抱在胸前的小狗的头，佩特拉带著无力微笑，试图与小狗分享心情。

在舞蹈结束回家途中，她让偶遇的昴与小狗碰面，结果小狗居然咬了一下昴的手。由于众人都接纳了昴，对先前感到沮丧的佩特拉而言，感觉就像终于找到了同伴。

干脆拜托梅莉今晚让小狗和我一起睡觉──正当佩特拉如此对小狗投入感情时。

「啊──！」

不知道是凯因还是梅伊纳，也有可能是佩特拉自己发出的叫声。

小狗突然扭动身体挣脱出梅莉的手腕，就算众人急急忙忙地追赶，却怎么样都无法追上小狗。小狗就这样穿过村外的白色栅栏，直接冲进森林中。

「怎么办……」

小狗闯进的方向与平常玩耍的地方恰好相反──那是大人们时常强调绝对不能进入的森林。里面靠著魔石的力量设下结界，让危险的生物无法靠近，简单说就是个危险的森林。

要是年纪还小的小狗跑进去那种地方──

「佩特拉……」

孩子们担忧的目光集中在不知所措的佩特拉身上。

佩特拉是孩童们的中心人物，只要有事他们都会先倚赖佩特拉，而受到仰赖的佩特拉也有回应此种信赖的义务。

「梅、梅莉……！？」

即使受到倚赖，佩特拉却什么话都说不出口。梅莉则是代替佩特拉试图钻过白色栅栏，她紧张地绷紧神情，不过仍然直直盯著森林。

「得去接那个孩子才行……」

听见梅莉那有责任感的声音，让佩特拉有种彷佛天打雷劈的震撼。接著，明明像梅莉这种孩子都这么拚命，佩特拉感觉到停下脚步的自己实在很丢脸。

「────」

在森林与村子之间，结界用的魔石以固定间隔吊挂在树上。

佩特拉确认著魔石位置并在脑中描绘地图，然后记下相等间隔的结界，推算出能够安全寻找小狗的范围。

踏进危险森林后，即使被袭击也能逃进结界的位置──只要顺著这条路前进，就能进去寻找小狗。

「我要和梅莉一起进去森林，大家就……」

「没那么简单喔！」「佩特拉也要去吧？」「那里就是我死的地方！」

当佩特拉与梅莉牵起手，梅伊纳牵起另一只手，而梅伊纳的手牵著榴卡。所有人就这样牵起手，没有人表示害怕想要回头。

「……嗯，谢谢。」

平常佩特拉总是众人倚赖的对象，但在这个瞬间，佩特拉首次觉得能够倚靠大家。如果只有梅莉，也许就没办法鼓起勇气了。

不过──

「──大家牵著手很难走路，可以别这样吗？」

佩特拉依照脑中的地图，带领著大家走在森林中。

「────」

踩著枝叶在森林前进时，佩特拉感觉到几乎撕裂胸口的吵杂心跳声。随著接近黄昏，森林的视野越来越狭窄，要是搞错路或是看走眼该怎么办？不安与紧张让额头浮现出汗水。

进入森林约快过了一个小时，事到如今，佩特拉对准备不足感到相当懊悔。

用吸引小狗的诱饵──不行，说不定会有危险的动物跑来。用大声呼叫──那也很危险。不然去通知大人──就算怕被骂，这也是该做的事。将结晶灯带过来──在变暗前回头去拿来得及吗？

「────」

虽然之前有用捡的石头在树木上刻记号以免迷路，但这也只是求个心安。

朋友们的担忧表情变得越来越浓厚，只要其中一个人崩溃，就会一口气扩散到全体。那个人说不定就是自己。

脑中还记得结界的场所，不过要是被发现才逃走真的来得及吗？该不会自己做出了一个很不得了的决定吧？

担忧变得越来越强烈，佩特拉的眼瞳中开始浮现泪水。再做两到三次深呼吸，就该对大家说出得回去交给大人处理了。

接著──

「大家……差不多到这里就……」

「──说得也是，差不多该是时候了呢。」

「咦？」

正当佩特拉紧紧闭起眼睛，准备对众人说出「该回去了」的时候，突然传来一道声音。

明明是曾经听过的声音，其中却含有未曾听过的声调。当佩特拉不得其解地睁开眼睛，只见梅莉的脸就在正面相当接近的位置。

先前怯懦毫无自信的少女──现在表情却判若两人，带有成熟的妖艳感。

并非是可爱，而是令人不寒而栗的美貌。

「抱歉啰，大家。不过这就是我的工作喔。」

在微笑与传来声音后，佩特拉的意识被背后冒出的气息吸引。她连忙回过头一看，有条巨大的黑狗就在眼前发出低吼声。就算想立刻发出「快逃！」的叫声，却没有办法发出声音──意识也在这时中断。

4

──结果，佩特拉是在隔天的傍晚才恢复意识。

「佩特拉！你这孩子真是……总是让人担心！」

佩特拉在床上缓缓睁开眼睛，最先见到母亲满脸通红地紧紧抱著她。

发现母亲的声音，父亲也立刻冲进房间。就这样将互相拥抱的母亲与佩特拉一起搂著，然后一起发出哭泣声。

「是宅邸的人救了闯进森林的你们，尤其是昴大人那么辛苦，还把所有人都带回来了。」

对于不知发生什么事而瞪大双眼的佩特拉，双亲如此说道。

据说那只小狗就是栖息在森林的危险魔兽，佩特拉等人那时候差点就没命了。而拯救佩特拉等人脱离险境的，出乎意料地是昴和宅邸的女仆。

「话说回来……好像有这么一回事……」

听完这番话后，佩特拉开始追溯著朦胧的记忆。

那是一段令人窒息且浑身发烫的惨痛记忆。佩特拉躺在草原上，身旁能够见到榴卡与梅伊纳的身影，昴与某个人来到了那个地方。接著，对搭话的昴提到已经不在现场的梅莉──

「对、对了……梅莉呢？那孩子怎么了？」

「……昴大人把那个女孩子带回去了。担心她的家人很快就来接她回去，还说要向佩特拉打声招呼。」

「……这样啊。」

梅莉留下告别的话语，与家人一同离开了阿拉姆村，佩特拉莫名地能够理解到那是双亲撒的谎。

在发生某件事前，佩特拉还记得梅莉突然性情大变。如果那只小狗是魔兽，一开始将那只小狗带来的梅莉肯定也有某些内情。

即使如此，如果情况允许，她还想再与梅莉再说一次话──

「──佩特拉！你起来了吗！？」「佩特拉，你醒了吗！？」「快起来啦，佩特拉！」

彷佛不容许佩特拉沉浸在感伤中，同伴们吵吵闹闹地闯进家中。

比佩特拉更早醒来的榴卡他们，似乎同样与佩特拉听到同样说明，而且还老实地相信并对梅莉离开感到相当可惜。

「要不要去宅邸探望昴？」

平常总是没有己见的梅伊纳如此提议，榴卡等人对她的提议举双手赞成。佩特拉也同样赞成，不过只是觉得很少见到她此种反应。

「梅伊纳会说这种事还真少见。」

「因为如果没有昴，我可能已经看不到弟弟或妹妹了……」

佩特拉也知道梅伊纳的母亲已经怀孕，身为独生女的佩特拉既有些羡慕，也觉得得知自己将有弟妹的梅伊纳变得比较像姊姊了。

原来如此，这样难怪她会想对昴道谢。

「那大家一起去拜托宅邸的领主大人吧！」

就连佩特拉也对身为救命恩人的昴怀著感谢之意，虽然跳舞的事让好感度下降，不过这件事用来抵销也没关系。

接下来还是对他稍微温柔一点吧，毕竟自己已经是个懂事的孩子了。

「要探望毛？他应该还在睡觉……说得也是，反正被看到愚蠢睡相也是丢毛自己的脸。好吧，我带你们过去。」

虽然造访宅邸让人很紧张，但负责接待的粉红色头发女仆出乎意料地和善。即使表情与声调很冷淡，但佩特拉总觉得这并非是疏远他人，而是对任何人都是这种态度。

「不用对领主大人说这件事吗？」

「宅邸的杂事都是交给我处理。如果你们是要来给毛致命一击的杀手，那又是另一回事了……你们是杀手吗？」

「不会有这么可爱的杀手。」

「对吧？所以没关系。」

那位女仆没有否定关于可爱的事，而是带著一副若无其事的表情替佩特拉等人带路。就这样对首度造访的宅邸感到心惊胆跳，六个人被带到了某个豪华门扉的房间。

昴就是躺在这个房间里吗？明明已经傍晚了，真是个贪睡虫。

「要进去啰。」

女仆敲了敲门，确定没有回应后，便打开门扉。

在宽敞的房间深处有张颇大的床，见到有个黑发青年躺在上面，让佩特拉松了一口气走进房间中──

「昴，已经傍晚了喔？这种时候还在睡觉……」

──原先想带著笑容搭话，佩特拉的表情与声带却顿时冻结。

「────」

昴带著平稳睡脸静静地发出呼吸声，如果光看这种模样，也许会单纯以为他只是贪睡而已。

但沉眠的昴全身遍体鳞伤，包满绷带，而且到处都能见到白色伤痕。

──佩特拉理解到那一切都是野兽的咬痕。

「安静点别吵醒他，等你们满意再叫我吧。」

只留下这句话后，女仆便回到走廊上。听到女仆所说的话，榴卡等人担心地走到昴身边，佩特拉却没有动静。

她在原地无法移动半步，脑中同时一口气涌现出至今所发生的事。

「──啊。」

在森林遭逢危机的时候，佩特拉曾经拜托昴某件事。并非是某件事，而是希望昴能将不在现场的梅莉带回来。父亲曾经说过，昴将梅莉、孩子们以及佩特拉都带了回来，那时候受了一点小伤而有点辛苦──这种伤势到底哪里算是小伤了？

「啊……啊……」

都是我的错，全部都是佩特拉引起的。

不论是将梅莉拉拢成为同伴、疼爱梅莉带来的小狗、以及让小狗逃进森林都是。还有将大家带进不能进入的森林也是。明明回头就好却无法做出决定、即使已经意识朦胧却对昴做出无理要求，结果那个无理要求让昴受了无法痊愈的伤势。

一切的一切，都是佩特拉自以为是所招致的结果。

「在昴的绷带上写点东西吧……」「写吧写吧……」「这是来探望过的证明……」

将浑身僵硬的佩特拉拋在一旁，榴卡等人掀开棉被并盯上昴双脚的绷带。他们顾虑到昴，于是压低音量，将各自的心意写在绷带上。

接著，梅伊纳害臊地写下感谢的话语后……

「佩特拉？」

最后轮到佩特拉，拿著羽毛笔的梅伊纳歪著头表示不解。这时其他人才总算发现佩特拉的模样，但佩特拉并没有接下笔。

她的膝盖不停发抖，也没办法正眼看著昴。

「佩特拉？」「怎么啦～～？」「没事吧～～？」

见到佩特拉脸色不太对劲，榴卡等人皆不解地歪著头。受到他们注视，让佩特拉回想起在那座森林发生的事。在进入森林前，榴卡等人也是这样看著佩特拉，那时候佩特拉还能勉强挤出仅剩的勇气──

「──！」

──今天却无法这么做。

佩特拉将呜咽声吞回喉咙深处，摀著耳朵飞奔逃出房间。在走廊的女仆眯起眼睛看著飞奔而出的佩特拉，却没有追赶的意思，彷佛事前就知道佩特拉会直直冲向大门逃回村子似地。

实际上也是这样，佩特拉飞也似地逃回家里自己的房间，对双亲惊讶的询问声也是蹲著，怕得不停发抖。

这是不能容许的行为。直到这时，佩特拉才首度发现自己犯下的罪过。

「全部都是我的错……是我的错……！」

到了那天的深夜，佩特拉含著泪水向双亲表白。

她知道自己逃离宅邸后，榴卡等人曾经担心地前来造访，也知道双亲担心爱女而数度朝房间呼唤。

她将一切置若罔闻，假装没听到将自己关在房间里，但还是无法忍耐逐渐膨胀的罪恶感，最后佩特拉哭哭啼啼地冲进了双亲的寝室。

听完佩特拉的话，双亲一开始相当惊讶。

不论是梅莉、小狗、对昴的请求以及如此严重的伤势，佩特拉表示这一切都是她的错，啜泣地表示不知该如何是好。

「说得也是……佩特拉的确做错事了呢。」

让女儿窝在同个被窝中，母亲摸著她的头并如此说著。父亲也在身旁钻进被窝，佩特拉在父母陪伴下擤了擤鼻涕。

「做错事就得道歉，要带著真心努力道歉。」

「……可是就算道歉，他也不会原谅我。」

「你是希望得到原谅才道歉吗？还是想道歉才道歉？佩特拉是哪种？」

「────」

感觉这是个很难的选择，让佩特拉沉默不语。

道歉不就是为了请求原谅吗？至少到目前为止，佩特拉都将谢罪的话语当成此种道具。就算觉得做错事说出对不起，最后还是将此种话语视为让对方原谅的工具。

明明对方不会原谅，那么道歉还有任何意义吗？

「要好好去向昴大人道歉。如果只有自己一个人会害怕，那爸爸妈妈也可以陪你去，不过要佩特拉亲口说出道歉才行。」

「────」

整个头连同身体被抱住，额头被父亲搂在胸前磨蹭。仔细想想，自从懂事以来，这好像还是第一次对父母亲如此撒娇。

即使在双亲面前，佩特拉一路走来仍然是隐瞒著真心话。因此即使现在是真心希望两人帮助，希望向昴道歉时能够陪在身旁──

「──没关系，我自己一个人就能好好道歉。」

──佩特拉认为自己并没有撒娇的资格。

5

两天后，顺利醒来的昴前来村子造访。

「哎呀，真是糟透了。不过大家没事就好啦！」

昴竖起拇指如此说著。穿著并非是平时那套宅邸制服，而是不曾看过的灰色奇怪服装。不过比起特地显得笔挺的服装，这套服装反而还比较适合他，佩特拉颇为客观地如此判断。

「昴～～！」「打起精神了！」「昴站起来了！」「昴立于大地！」

「喔喔～～你们这些小鬼头看起来没事真是太好了，记得要感谢我喔。」

昴对大人们的感谢面露害臊，但对孩童们却是一如往常的态度，对自己的功劳自傲地四处炫耀。佩特拉与大人们皆依稀地能够感觉到，这是让周遭的人反而别太担心的举止。

发现这件事反而让佩特拉感到烦躁，明明昴对村子与佩特拉等人做出相当大的牺牲，为什么还要这么做？

「昴，来玩吧！」「来玩来玩！」「来钓沙蟹！」「要钓到大只的！」

另一方面，榴卡等人没有发现昴的顾虑，以一如往常的模样拉著昴。见到榴卡伸出手准备爬到他身上时──

「──榴卡！你在想什么！昴才刚痊愈而已！」

「哇啊啊啊！？」

佩特拉忍不住大声喝斥，榴卡吓得当场跌坐在地。众人对这道喊叫声一起回过头，发现佩特拉正在离人群有段距离的位置。

接著，昴也对独自站在远处的佩特拉举起手。

「喔～～佩特拉，你怎么自己一个人站在那边……」

「──！」

「咦，咦咦！？」

当他装亲密搭话的瞬间，让佩特拉转过身背对著他拔腿狂奔。虽然背后传来昴的惊讶叫声，佩特拉仍然没有停下步伐。

明明已经决定要道歉了，这样与在宅邸的时候根本没有两样。

「呼……呼……」

结果佩特拉直接逃到了村子另一头，她弯著膝盖做了几次深呼吸并环视四周，这里是村子外面──也是遇见梅莉和小狗的场所。

「全部……」

「──就是在这里让很多事一团乱的吧。」

这次真的不是夸饰，佩特拉吓得以为自己的心脏都要停了。

回过头一看，昴正站在佩特拉的稍后方。他夸张地喘著气，拖著蹒跚步伐靠在吊挂魔石的树干旁。

「可、可是啊……大病初愈就要全力跑步还挺累的……唉，这不是生病，受伤也能算是大病初愈吗……到底算不算啊……」

「为什么……」

「呼吸调整得还真快啊……不，应该只是我体力太差而已吧……」

昴带著苦笑在该处一屁股坐下，无法得知他的真正意图让佩特拉不知所措，昴则是朝佩特拉用手拍了拍自己身旁的地面。

「哎呀，总之过来坐著。佩特拉，我们稍微聊聊吧。」

「──嗯。」

被昴如此一催，佩特拉没有勇气拒绝。

当佩特拉一屁股坐在昴的身旁，便垂著头频频瞥视著他的侧脸。看起来不像是在生气，不过就算生气也是理所当然的。

「呃……我也不是很清楚，大家都说要来追赶佩特拉。感觉你好像有什么话想对我说？」

「──！是、是这样没错……」

看来这似乎是周遭的人为了让佩特拉道歉而营造出的状况。也就是说，是村子总动员帮忙佩特拉赎罪。不论是榴卡、米尔德、凯因与岱因、甚至连梅伊纳都试图让佩特拉道歉。

就算是昴，只要准备得如此周到，也能正大光明地责备佩特拉──

「你在说什么？该不会是从森林带你回来之前就受伤了吧！？那些狗有可能会毫不留情地乱咬人，如果让你留下伤痕……先说声抱歉！」

「啊……咦？」

「让女孩子留下伤痕是绝对不能出现的最坏情况。呃……如果要不留下伤痕，我记得好像要保持湿润之类的……」

昴脸色苍白，对佩特拉受伤明显地相当焦急。看到他努力地动脑想办法的模样，佩特拉顿时看傻了眼，而且开始怀疑这该不会是刻意煽动罪恶感的策略──但佩特拉很快发现他完全没有这个意思。

「────」

眼前这位少年完全没有想过是佩特拉做错事，反而认为自己害了佩特拉而不停反省。

此种误会与误解反倒让佩特拉感到怒火中烧。

「昴……」

「对了！佩特拉，让我看看伤痕……啊，不对，如果是在奇怪的地方好像不太好吧……」

「──昴！！」

「是是是是！怎么了！？」

昴被大声喊叫的佩特拉吓了一跳，回过头时才总算与佩特拉四目相对。见到大颗泪珠正在佩特拉的眼眸中打转，让他瞪大那罕见的黑色眼瞳。

激动的情绪让她很想大声喊叫，但现在并不应该任凭怒气出声。

「对……」

「对？」

「对不起……！」

支支吾吾地说完整句话后，泪水沿著脸颊流了下来。此种模样让昴变得更加惊慌失措，但佩特拉顺著失控情绪反覆说著道歉的话语。

「佩、佩特拉！？你为什么要道歉！？」

「对不起、对不起……！对不起……」

在手足无措的昴面前，佩特拉只是呜呜咽咽地持续道歉。

「──所以全部都是我的错。」

表白自己犯下的错后，佩特拉将视线盯著地面并紧紧握著手。

虽然泪水仍然不停涌出，但心情已经平稳到勉强能够说话。于是佩特拉就这样一点一滴地，以宛如对双亲说话的方式般向昴表明自己的过错。

不论是梅莉、小狗、拜托昴而害他受到重伤的事，佩特拉表示全部都是自己的错。

「────」

听完佩特拉表白过错后，昴带著五味杂陈的表情保持沉默。

只要一闭起眼睛，佩特拉眼中便会浮现出那天昴躺在床上的身影，他追赶著佩特拉来到这里的气喘吁吁模样也是记忆犹新。

而现实中昴就在身边，卷起袖子的手腕还有几道白色伤痕。那肯定会留下无法消除的伤痕，就像刚才昴担忧佩特拉的伤势一样。

「──我说啊，佩特拉。」

「……嗯。」

被昴叫出名字，佩特拉感觉到时刻总算来临而咬紧牙齿。

不知道他会说出什么话，也不知道他会怎么逼问。对于至今不论任何问题都会获得宽恕的佩特拉而言，甚至无法得知不受饶恕会有多么可怕。

因此当她抬起头，看见昴不知所措的苦笑时，佩特拉甚至忘了呼吸。

那并非是绝对无法容许对方的表情。

「我不觉得佩特拉有错……不对，既然你都道歉了……好像也不是这样。」

「呃……」

「嗯，应该要这么说吧。」

佩特拉对歪著头思考该如何回答的昴感到颇为惊讶，昴无视于惊讶擅自摆出接纳的神情后，便朝著佩特拉点了点头。

「──我原谅你。」

「────」

「哎呀，佩特拉做出很多错误选择是事实，我觉得不负责任说没有任何错也怪怪的。所以既然佩特拉都哭成这样好好反省了，考虑到要说什么最好……」

「────」

「我会原谅佩特拉。没事，我没有生气。佩特拉和梅伊纳没有留下伤痕就好。我和榴卡他们就不一样了，毕竟伤痕可是男人的勋章喔。」

如此说完后，昴便以毫无怒气的表情露出笑容。

这与先前佩特拉首度对昴怀著好感的表情，可说是如出一辙。

「──呜呜……」

体会到与当时截然不同的震撼，让佩特拉再度溃堤开始嚎啕大哭。

6

夜幕低垂后，佩特拉在自己房间的床上持续独自思考。

为什么昴没有生气？为什么自己会得到饶恕？

「我……」

并非是因为可爱，佩特拉已经充分理解到只靠可爱还是有无法解决的事，因此昴会原谅她的理由并非是这个。

天真、易如反掌、单纯──佩特拉回想起自己以可爱为武器，将大人与孩子们玩弄于股掌之间时朝对方做出的评语。

原因并非其中任何一种。可爱并非是武器，既然如此，佩特拉之所以会得到宽恕的原因是……

「……因为温柔。」

脑中浮现出温柔这个字的瞬间，便在佩特拉心中成为理解的最后一片拼图。

昴之所以会原谅佩特拉，绝对是因为他很温柔的缘故。昴为了拯救佩特拉等人进入森林，不只是相当拚命，即使受伤也没有任何抱怨，出来让担忧的村人们见面，以及摸著头安慰泣不成声的佩特拉，一切都是出自于温柔。

「啊──」

这时，佩特拉突然发现自己至今为止有个很严重的误会。

大人们会原谅佩特拉的恶作剧、容许偷吃与工作时偷溜出去，佩特拉以为理由是自己很可爱，但事实并非如此。

怎么会误以为是可爱？居然会有这么愚蠢的误会，那是因为大家很温柔才会容许这些事。

不论是仔细反省、认为自己有错的自觉、发誓不会再做出同样的事，大家会容许我想将整件事付诸流水，都是因为倚赖著众人的温柔。

佩特拉的人生总是仰赖著他人的温柔才得以成立。

直到现在，她才总算发现这件事。

多亏了到目前为止最令人感受深刻的温柔举动，才让佩特拉能够如此察觉。

「喔，佩特拉，你今天打扮得还满可爱的嘛。」

隔天，在村子广场见面的昴，带著微笑如此称赞佩特拉的穿著。

他完全没有提及昨天流泪的事，佩特拉认为这也是昴的贴心举动。她决定接受这番善意，因此佩特拉也没有提及昨天的泪水。

相反地，她轻轻抓著裙襬并当场以可爱动作转了一圈。

「嘿嘿……对吧？可爱吗，我今天可爱吗？」

「嗯，超可爱的。你那套衣服是在哪里买的？」

「呃……其实这不是买的，是我自己做的！」

「做的！？原来啊，原来是这样，说得也是。佩特拉还真厉害！」

面对昴交杂著理解、惊讶与接纳的反应，佩特拉顿时感到有些不解，不过还是对他的老实反应感到相当愉快，并且红著脸颊得意地挺起胸膛。

今天佩特拉的服装是既可爱且华丽的一件式套装──如同昴所说，这是佩特拉自己用布做成的服装。两年前让佩特拉怀著梦想的宝物，她用那些布料点点滴滴地制作成服装，在这天首度公开亮相。

「真不愧是佩特拉，有这种美感将来一定能开店。」

「……你是真的这么想吗？」

「嗯？」

直到刚才的兴奋心情，被昴的这句话突然冷却。

对于佩特拉这道没有精神的声音，昴也露出有些困惑的神情。不过佩特拉很害怕刚才那番话，她并非是首度在别人面前表示将来想从事制作服装的职业。

但这些话总是被当成玩笑话，没有人肯认真看待。

大人们只会笑著带过，朋友们也不肯相信──那就是佩特拉的梦想。

如果是昴会怎么想？此种想法在心中急速膨胀。

「我啊……将来我想到王都从事制作服装的工作。」

「────」

「这套服装也是为了这个梦想做的练习……虽然只有一套，不过我要继续练习。然后……」

佩特拉有些生涩却饶舌地阐述著自己的梦想。

并非是平常开玩笑的语气，而是将愿望寄托在希望能听听这件事的人身上。

听完佩特拉的梦想后，昴的回答是──

「真是个好梦想，如果是佩特拉，肯定能成为王都最强的裁缝师。」

「啊──」

平常总是会笑著答话的昴，这时并没有嘲笑佩特拉的梦想。

昴带著认真表情与语调，摸著担忧不安的佩特拉的头，替她的梦想声援。

──大家一笑置之的梦想，昴并没有嘲笑她。

「────」

这个人为什么会这么温柔呢？

佩特拉如此思考，那斗大眼眸映照出昴，脸颊下意识地变得越来越红润。

──只看著昴的此种表情，也是佩特拉至今以来最可爱的模样。

十二岁的佩特拉•莱特有个梦想。

那就是身为一流的服装师，在王都开间最高级的店──并非如此。

「我很喜欢做衣服，这点之后应该也不会改变……」

佩特拉一边望著完成的宝物，一边回想著开始怀抱梦想那天的事。

那天佩特拉被色彩鲜艳的纺织品夺走目光，并且怀著在王都展翅飞翔的梦想。但现在佩特拉得知了感动的真正意义。

那时候佩特拉并非是对美丽编织物感动，而是对自己小小世界中缺乏之物，以及完全未知事物的冲击，她是被如此浩大的世界所吸引。

那条道路肯定不是必须拘泥于服装，最重要的是佩特拉•莱特想尽可能扩展双眼所映照出的小小世界。

因为自己很可爱这个理由，佩特拉曾误以为自己就是世界的中心。

佩特拉到目前为止到底受到了多少人的温柔保护？当她得知了这件事时，佩特拉的世界再度受到不劣于缤纷编织物的冲击而遭摧毁。

因此──

「榴卡想继承爸爸的樵夫业，米尔德要让村子的酒馆重建？是要成为厨师吗？凯因与岱因……嗯，就算听了也没用吧，好啦好啦。」

聚集同伴们一如往常地聊起将来的话题时，岱因与凯因两兄弟又开始吵架，议题当然是谁能成为佩特拉的丈夫。

「佩特拉呢，果然还是想去王都吗？」

最近不知是否萌生即将成为姊姊的自觉，不像之前那么内向的梅伊纳向佩特拉如此询问，这个问题让佩特拉红著脸颊。

「呃……现在可能不太一样了。」

「是吗？那将来想做什么呢？」

佩特拉对如此回问的梅伊纳吐出舌头，那是令人不禁陶醉的可爱笑容。

「──将来我想嫁给一个温柔的丈夫呢。」

** 『雷姆极为平凡幸福的一天』

1

身为罗兹瓦尔宅邸的女仆长兼首席女仆，雷姆每天都得很早起床。

罗兹瓦尔宅邸由三栋建筑构成，雷姆在东栋个人房间中醒来时，仍然是空中留有浓浓夜色的清晨时分。

「────」

东方远处传来早晨的气息，让漆黑夜空微微混进一缕光芒。彷佛听见此种拂晓的脚步声般，躺在床上的少女静静地睁开眼睛。

娇小身躯搭配细瘦手脚、修齐的短发呈现明亮天蓝色，接近头发颜色的淡蓝圆眼十分可爱，留有稚嫩气息的五官也是楚楚动人。

不过说实话，本人对自己的过人容貌可说是毫无自觉。

「呼啊……」

她随著微微呵欠声撑起身体，身穿蓝色睡衣的雷姆从床上将脚落到地面。

她是完全不会赖床的人。雷姆挥除睡意并站起身，在房间正中央轻轻伸了个懒腰。接著再用手背将眼角浮现的泪水拭去，便将梦境中所残留的情感一同挥除。

「得先洗脸再换衣服……」

将该做的事说出口，这是雷姆开始工作前的小小习惯。

对于自觉到做事并非很有效率的雷姆而言，将事情订好优先顺序并整理行动，这是不可或缺的仪式。在不为人知的地方进行此种仪式，才能够勉强完成身为宅邸女仆长的职责，至少雷姆是这么想的。

「────」

她一边在脑中整理行程，一边单手拿著毛巾前往洗脸台开始洗脸。冰冷的水让迟缓思考绷紧神经，用柔软的毛巾擦过脸后，就是回到房间换衣服的时间。

让单薄的睡衣落到地面，只有穿内衣裤的少女柔软肌肤顿时表露无遗。

虽然比起十七岁的年龄雷姆看来更为娇小，但身体的凹凸有致仍然颇具女性魅力。尤其是这几个月以来，胸部的成长极为显著，这也是她烦恼的源头之一。

「唉……」

雷姆哀伤地叹了一口气，重新转头面对衣柜。在这个收纳衣物的空间中，有许多套制服一字排开──吊挂的皆是同样种类的女仆服。

雷姆毫不犹豫地选择其中一套，俐落地穿起熟悉的制服。

仔细想想，像这样穿著女仆装的生活也已经接近十年了。

十年──那是鬼族村落灭亡并与姊姊拉姆一起被罗兹瓦尔收留的时光。如同字面所述般，对雷姆而言已经是超过半生以上的漫长光阴。

这么长的时间，雷姆一直是穿著这套女仆装一路走来。她并没有对这件事怀著不满或疑问，而且认为接下来应该也不会有任何改变。然而──

「偶尔穿穿不一样的衣服会不会很奇怪呢……」

衣柜附设的镜子映照出自己的身影，雷姆仔细地检查著制服。将衣著打点整齐是女仆的基本礼仪，也是不让主人蒙羞的最低底限心态。这也是身为见习女仆时，被法兰黛莉卡指导过无数次的事。

雷姆当然遵从这些教诲，对这些礼节从来没有偷懒过。但这几个星期比平常更加认真检查，然而认真的地方与其说是注重「完美」，反而是「可爱」更加优先。

「……大概就这样吧。」

在镜子前转了几次圈后，雷姆让无法看见终点的准备划下休止符。

穿起颇为裸露的女仆装，最后再配上花朵发饰就完成了。她摆动著短短裙襬翩翩来到走廊，并且做了个深呼吸。

宅邸走廊满溢著清晨的冷冽空气，雷姆将空气尽情地吸入肺部，并且神清气爽地迈出步伐。她前往的方向是姊姊拉姆的房间──并非是这样。

「──早安。」

雷姆以细若蚊鸣的声音如此打声招呼后，便踏进了那个房间。

即使房间格局与雷姆的个人房间相同，内部摆设却受到主人个性左右。虽然私人物品还不算多，但总觉得其中有很符合他个人风格的物品，因此每当雷姆「日日夜夜」目睹时，便能感觉到胸中涌现出温暖的心情。

这并非是雷姆或拉姆的房间，而是佣人使用的某个房间。

目前在罗兹瓦尔宅邸工作的佣人，除了两姊妹以外只有另一个人。

也就是说，这里就是那位佣人的房间──

「──昴。」

在昏暗房间的深处，雷姆俯视著躺在床上的少年并叫出他的名字。然而这道声音也是细若游丝，不可能传到仍于梦乡中的少年耳中。

不过在进入房间前已经先打过招呼，也已经对沉眠的他出过声。

「所以昴没起来只是因为他贪睡而已。」

雷姆打著此种冠冕堂皇的藉口站在床边，紧紧盯著沉眠少年──菜月昴的睡脸，涌现的爱意让她的嘴角上扬露出笑容。

昴横躺在床上抱著棉被熟睡，他身上穿著黑色的运动服──这是雷姆将昴原本穿著的异国服装加以重现后的类似服装。见到他用来代替睡衣使用，让雷姆不禁感到心头一暖。

让她感到暖心的不只这个，那毫无防备的睡脸与平常梳高的浏海放下的模样，可说是既稚嫩又可爱。不论是出乎意料发出安稳鼻息声的双唇、抱著棉被的细长美丽手指、短短双脚、以及在枕头上流著口水的模样，都是相当可爱。

「昴好可爱……」

连她都对如此盲目感到有些傻眼，但自身的感性实在不容小觑，实际上就是有这种感觉也是无可奈何的事。

她的白皙脸颊泛出红润，雷姆默默地享受著昴的睡脸与睡相。她让全身神经集中到最高极限，下定决心绝对不漏掉昴发出的任何信号。

像这样接近愚蠢的夸张观察持续一阵子后……

「今、今天早上就到这里吧……再这样下去雷姆会撑不住的，得赶快离开才行……」

心脏越跳越快，感觉到自己不只是脸颊、甚至红到耳根，让雷姆勉强以强烈自制力将意识拉离昴的睡脸。她退了几步让少年完全脱离视野，才勉强找回自我。

「好危险……差点就迷失自我了。」

雷姆将手抵在额头上，对自己的自制心给予称赞。

虽然偷窥昴的睡相是雷姆「每天早上」的必经行程，但从来没有轻松解决过欲望与自制力的攻防战，总是千钧一发的对决。

──另外一提，光是输给前来偷窥睡相的冲动时，似乎就已经是顺从欲望了，这点本人似乎完全没有察觉。

「我真佩服自己今天早上能这么努力，昴真是个罪人呢……」

要是本人醒著，肯定会强烈主张自己是被诬陷的。

随著温热气息留下这句话后，雷姆匆匆地离开昴的房间。就这样完成晨间最初的行程后，接下来才是迈步前往拉姆的房间。

「──早安。」

进入姊姊的房间时，雷姆朝里面呼叫的声音依然是细如蚊鸣。

虽然熄灭灯光的房间有些昏暗，但比起昴的房间还是明亮许多。由于早晨逐渐接近，证明了雷姆在昴的房间浪费了相对应的时间。话虽如此，这段延迟并不会对业务造成障碍，雷姆已经算进偷窥睡脸的时间提早起床。

虽然这也表示睡眠时间会相对减少，但日常工作不只是体力，精神面的干劲也很重要。这只是雷姆试图补充干劲的行为，对象不只是昴的睡脸──

「──姊姊，今天也是很棒呢。」

对于拉姆仰躺在床上的安稳睡相，雷姆轻轻地投以微笑。

拉姆是雷姆的双胞胎姊姊，虽然在许多场合都被说是长相如出一辙，雷姆却完全没有相信过这些话。

那凛然的五官、满溢知性与强烈自信的淡红色眼眸、美艳且同时飘散出虚幻感的桃红色发丝、均衡完美的体态、纤细柔软的四肢──姊姊不论从什么地方观赏都是完美无缺，自己身为妹妹只有外表拥有不相衬的相似之处。

雷姆有属于自己的优点。因为有人这么说，雷姆才能对这件事不感到自卑地继续努力。然而──

「就算是这样，姊姊还是雷姆憧憬的目标。」

随时充满自信、不论何时总是既正确且坚强，这就是拉姆。

雷姆曾经对姊姊感到沉重压力，但由于对姊姊拥有更胜于此的骄傲，因此雷姆怀著敬爱与亲爱之情对熟睡的拉姆出声呼唤。

「姊姊、姊姊……早上了，请快点起来。」

虽然她那安稳熟睡的模样令人不舍，雷姆还是让身心灵皆化为「鬼」将拉姆摇醒。像这样在工作前将拉姆叫醒，也是雷姆每天的必备行程。拉姆对呼唤声微微睁开眼睛并发出「再五分钟……」的脆弱呢喃声，也是每天必定的反应。

如果情况允许，雷姆当然也想让拉姆尽情睡饱。

「不行喔，姊姊。要是不快点换好衣服做好准备，会没办法给见习的昴当成榜样。而且昴在魔兽那件事受的伤还没有痊愈，让他做太多工作实在很可怜……」

「……我不想看到雷姆比我更担心毛，所以我不起来。」

「姊姊，请别说这种话……不过要是姊姊休息，我就能和昴两个人一起工作了……我知道了，姊姊今天请好好休……」

「我还是起床好了。来吧，雷姆，快点帮我换衣服吧。」

拉姆爽快地收回先前所说的话，一股脑地撑起上半身并举起双手。雷姆对姊姊翻脸如翻书的模样瞪大双眼，然后幸福地露出微笑。

「姊姊，您太著急了。换衣服也是一样，得先梳理头发才行。尤其是今天头发睡得特别卷翘，昨天晚上很晚睡吗？」

「因为最近雷姆都不陪我一起睡，所以睡得很不舒服。」

「雷姆与姊姊一起睡觉已经是几年前的事了吧。」

雷姆沉浸在令人怀念的回忆中，拿出梳子开始替拉姆梳理头发。她那附有光泽的头发光滑柔顺，简直像是在手中舞蹈般，手触碰触传来的细致质感，照理说几乎与雷姆一模一样──让雷姆突然闪过一道想法。

「要不要来留长头发呢……」

雷姆之所以会将头发剪短，原因当然是想与拉姆同样发型。

不论是与姊姊同样发型、相同服装、人称如出一辙的长相，要是连特征都能类似，感觉就能更加接近姊姊。这么做才能支撑著雷姆的心灵。

不过，现在她认为也许能拋开这些幼稚的坚持。

「姊姊，要是雷姆把头发留长会不会很奇怪……？」

「……你是问我会不会觉得奇怪，还是问其他人会怎么看？两边的答案会不一样喔。」

「就是……昴会不会觉得我很奇怪……？」

当雷姆战战兢兢地说出担忧的原因，拉姆便露骨地深深叹了一口气。

「怎么突然这么说？是毛对你说了什么吗？」

「不，没有说什么。只是我梳著姊姊头发的时候突然想到……」

「……毕竟爱蜜莉雅大人是留著一头美丽长发嘛。」

原本想要掩饰真正意图却被一眼看穿，让雷姆只能回以苦笑，感觉到这道笑意让拉姆无奈地摇了摇头。

「雷姆要留长头发肯定会很可爱。不过就是肯定会很可爱，所以让我很想把毛大卸八块。」

「姊姊……」

面对声音与态度皆严肃许多的拉姆，雷姆同时感觉到喜悦与担忧。喜悦来自受到姊姊拉姆关心，担忧则是或许会让昴与拉姆感情不和。

「姊姊，您这么讨厌昴吗？」

「没那么讨厌，和配不上我可爱雷姆是两回事。」

对于拉姆如此斩钉截铁的回答，雷姆不禁瞪大双眼，但惊讶随即转变为带有笑意的感情。

也就是说，刚才拉姆的回答表示她并不讨厌昴。

「谢谢姊姊，雷姆也对有这种姊姊感到很骄傲。」

「这样啊……哎呀，这也是没办法的事。毕竟我就是让雷姆感到骄傲的姊姊嘛。」

虽然话题已经偏离原先主轴，但确认到姊妹之情的雷姆感到幸福洋溢。拉姆也不经意地愉快哼著歌──而她哼出的曲调也非比寻常地悦耳。

「────」

雷姆也顺著哼歌舒服地摆动梳子，温柔地梳理著姊姊的头发。

这也是每天早上必定反覆出现，拉姆与雷姆两姊妹加深羁绊的重要仪式。

2

在罗兹瓦尔宅邸的宽敞中庭，昴与爱蜜莉雅正愉快地谈笑风生。

雷姆远远地俯视著此种情景，嘴角也微微上扬。

「昴看起来很快乐的模样真可爱呢。」

雷姆对昴兴奋的模样感到相当满足，甚至流露出此种感想。

在早晨这个时间，是爱蜜莉雅在宅邸中庭与微精灵缔结契约──这是每日一度与精灵对话的时间，也是爱蜜莉雅来到这个宅邸一直持续的习惯，而昴出现在此也是来到宅邸后一直持续的习惯。

「──居然打扰与精灵之间的重要时光，真是个不知好歹的家伙。」

俯视著中庭的雷姆身旁突然传来一道声音。

原先雷姆将意识集中在庭院，对于没有发现来访者的气息稍微感到惊讶，然后对搭话的对象感到更为吃惊。

「碧翠丝大人。」

面对雷姆的呼唤，随即站在身旁的碧翠丝没有回应，只是将双手挽在胸前。

那是个拥有可爱外观的少女。淡亮色的长卷发配上多处使用波浪摺边的奢华礼服，五官也如同娃娃般工整，完全没有任何可挑剔之处。

以楚楚动人的意义而言，此种容貌无人能出其右。

「不，还是比不上姊姊呢。」

「……总觉得有种突然被侮辱的感觉呢。」

「没有的事。不论是什么人都无法比上姊姊，碧翠丝大人也有属于自己的优点，请别感到气馁。」

「是不是越说就越贬低贝蒂啊！」

原本是鼓励的意思，却让碧翠丝气得不停跺脚，雷姆则是弯下腰表示「非常抱歉」。原本并没有激怒她的意思，不知道究竟是什么地方让她听不顺耳。

「该不会因为肚子饿了吧？距离早餐还有一段时间……」

「怎么可能因为肚子饿就生气，别看扁贝蒂了！最近宅邸这些家伙的态度真是让人看不下去，这一定都是因为那个男的……！」

如此说完后，碧翠丝皱著眉头将视线转向中庭，视线前方仍然能够见到昴与爱蜜莉雅有说有笑。

「是那家伙影响你和你姊姊吗？真是让人气到不行呢。」

「影响……是的，昴真的很棒呢。」

「为什么讲到这里会微笑啊……现在贝蒂开始很后悔找你说话了。」

雷姆对昴的话题微微一笑，碧翠丝则是用手抵著额头发出叹息。不只是对她疲累的模样，雷姆对她的呢喃恢复一开始的惊讶感。

先不论碧翠丝的后悔模样，很少见到她会与雷姆闲聊，而且由碧翠丝主动搭话的次数更是单手就能数得出来。

「今天碧翠丝大人的事也得写在日记上才行呢。」

「喔？你居然会写日记，还真是一丝不苟呢。」

「是的，是最近想每天记录昴与姊姊的事才开始的。由于才到第六本，很丢脸的是文笔还不好……」

「第六本……？那个男的来到宅邸才一个月左右而已吧……」

不知为何碧翠丝露出战栗神情，雷姆对自己的不足之处感到相当丢脸。

虽然她有无数的事想写在日记上，但文才与时间不允许她这么做。不论是昴的美妙之处、拉姆的优点等等，想完全表现出可说是难如登天──

「即使这样还是要写出来，这是不是拉姆太过自以为是了呢？」

「我哪知道！你想写就随便你！……真是的，这点反而太过在意贝蒂了吧。」

「太过在意了吗？」

「我可不想再被卷进给你休假之类的麻烦事，所以只是在那之前随便看看情况而已。」

碧翠丝带著看似闹别扭的表情，同时发出不符合外表的深深叹气声。

回答内容让雷姆屏起气息并瞪大双眼，表示碧翠丝的发言是如此令人震惊。

碧翠丝口中所说的麻烦事，肯定是关于前阵子「雷姆的休假」。

那是昴担心雷姆的身体状况，向罗兹瓦尔提议临时给雷姆一个休息假日，那天的工作由宅邸的所有人帮忙代为处理。

说实话，雷姆对那个提议大为吃惊且惶恐，也担心是否能将工作交给众人，就结果而言，那段时光也让她深深体会到自己是多么受到眷顾。

从那之后，雷姆更加投注精力专心致志于工作，但看来不只是雷姆对那天的事挂在心上。

「该不会您是担心雷姆吧？」

「────」

「感谢碧翠丝大人，您有这份心意让雷姆十分开心。小人知道了，今后将会更加竭尽全力完成宅邸的事务！」

「我的意思就是叫你别这样！要你适当放松，别让自己太累！不然又会让事情变得很麻烦！」

面对雷姆充满决心的宣言，碧翠丝挥了挥手予以否定。这道反驳让雷姆沮丧地垂下头，碧翠丝则是用手指拉著她的直卷发。

「明明增加了佣人却比以前还累真是太奇怪了。虽然贝蒂也知道那家伙完全没有半点用，不过只要和你那个半瓶水的姊姊好好合作……」

「姊姊是很完美的，没有半点破绽。」

「……既然这样，那就趁著一丁点的破绽把那个男人塞进去好好利用吧。」

虽然雷姆想反驳「连一丁点的破绽都没有」，但还是将话语吞了回去。在这种时候重点并非是破绽的大小，而是碧翠丝想表达的想法。

只不过别说是想表达的想法，与以前的碧翠丝根本不可能出现这种关系。

「你在笑什么？」

「非常抱歉，不过雷姆相当开心。没想到碧翠丝大人会如此担心雷姆，以前从来没有出现这种事。」

「……这没什么，毕竟贝蒂总是很善解人意的。」

面对这位鼓起脸颊并别过头的少女，雷姆没有任何回应。

实际上也许真的是这样。碧翠丝原本就是既温柔又替雷姆著想，应该只是在这之前没有说出口而已。

「碧翠丝大人刚才说过，是因为昴对雷姆和姊姊产生影响……不过碧翠丝大人应该也是一样。」

「你这个讽刺还真伤人。」

「小的没有讽刺的意思……」

「如果是这样就更糟了。」

碧翠丝不悦地嗤之以鼻并转过身背对雷姆，然后将手搭在附近房间的门扉上。虽然那里是一间客房，但对于能够藉著「机遇门」连接禁书库与门的碧翠丝而言，这等于是通往个人房间的入口。

「碧翠丝大人，到了早餐时间会再亲访通知。」

对准备回到禁书库的小小背影如此传达后，碧翠丝默默地挥了挥手，少女的身影便消失在空间扭曲中，回到了不在此处的禁书库。

「我认为碧翠丝大人果然也改变了。」

即使知道消失的少女无法听见，雷姆仍然如此喃喃说著。

以前的碧翠丝连宅邸早餐都很少露面，却在这个月几乎每天出席，今天早上的邀约也没有拒绝。

「────」

看向窗外，能够见到昴与爱蜜莉雅两人正准备离开。

两个人应该是直接出发前往宅邸附近的阿拉姆村，带领村人举行已经成为惯例行程的收音机体操，早餐会等到两人回来宅邸后才开始。

「得赶紧准备才行。」

目送逐渐远去的两人身影离开后，雷姆快步前往厨房。

所有宅邸成员会在晨间餐会齐聚一堂，雷姆对此种已经成为常态的日常怀著满足感，快步地踩著走廊的地毯前进。

3

「哇，今天是雷姆替我泡茶啊。好久没有这样子了。」

迎接来到个人房间的雷姆后，爱蜜莉雅带著灿烂微笑如此说道。

长长银发搭配澄澈的深紫色眼瞳，连将姊姊拉姆视为至高无上的雷姆，都忍不住对这位少女拥有的美丽容貌看傻了眼。

时刻为阳日，约过了火之刻一半左右。午餐结束后，宅邸成员各自专心处理职责，现在正好是休息时间。

将烤甜点与茶水送来，提供爱蜜莉雅休憩时间也是佣人的职责，不过平常这个任务都会由昴率先接下。

「昴与姊姊今天一起到村子购物，因为品项有点多，所以来不及赶上休息时间。」

「这样啊，最近还真少见到他们一起出去，这阵子都是雷姆跟著其中一边出去比较多呢。」

「是的，今天是雷姆提出任性要求，拜托他们一起去的……因为我希望昴和姊姊能更和睦一些。」

如同晨间的对话般，昴与拉姆并非是感情不睦。或许该说光看对话相当投机，甚至可说是关系融洽。

不过两人都对自己不太老实，雷姆想要改善这点。

「所以雷姆刻意让自己的身心化为厉鬼。」

「这样啊，想让他们两个和好……嗯，这是好事。我也很赞成。」

爱蜜莉雅在胸前握起双手，露出灿烂的表情对雷姆表示赞同，不过她在摆出这个动作后又微微歪著头。

「可是，我以为昴和拉姆的感情一～直很好……就是啊，之前他们两个还和帕克，三个人一起到山上去采茶的材料。不是吗？」

「是的，多亏那件事让姊姊心中对昴的评价大幅提升。不过还需要再推一把，所以雷姆想主动做个推一把的机会。」

由于拜托两人购买的物品清单需要四处跑遍村子，所以会很花时间。只要这段时间能让两人解开误会，雷姆的幸福计划就更前进一步了。

不过这个幸福计划不只是拉姆，也需要爱蜜莉雅的协助──

「──？怎么了吗？」

「不，没什么。总之今天雷姆是负责侍奉各位。既没办法像姊姊冲泡美味茶水，也没办法像昴这样快乐地聊天，这点还请大人见谅。」

她隐瞒著内心面无表情地行了个礼，雷姆便推著推车进入爱蜜莉雅的房间。

比起雷姆等人的佣人房，爱蜜莉雅的个人房间大了一圈，而且格局较为接近罗兹瓦尔的办公室。房间深处有张黑檀桌，中央有较大的圆桌与待客用的座位，床铺则是摆放在隔壁房间。

而办公桌与待客用的圆桌上摆放了许多书本与资料。

「不好意思这么乱，我会马上整理干净。」

「劳烦您了。」

简单回应后，爱蜜莉雅开始收拾著圆桌上摊开的资料，雷姆也在她身后开始准备茶水。顺利将桌面净空后，便将冒著蒸气的茶杯放在桌上。

「咦，雷姆的份呢？你不喝吗？」

「不，雷姆单单只是仆人。怎么能与爱蜜莉雅大人一起……」

「不过拉姆和昴总是会陪我一起喝茶……」

「──那么，雷姆也恭敬不如从命了。」

虽然瞬间有些犹豫，但雷姆随即收回先前所说的话决定同席。

即使有些微妙地违反仆从守则，不过昴和拉姆都是这么做的。比起守则更应该重视关系，虽然这样会有些对不起曾经身为教师的法兰黛莉卡。

「下次有机会见面再道歉吧……」

雷姆一边对那位身为前辈而因为个人因素离开宅邸的女仆暗中道歉，一边准备著自己的茶水，接著听从爱蜜莉雅的话语一同享受喝茶时光。

「────」

双方互相拿著茶杯饮用，静静地享受茶的味道与香气。

这段时间两人没有类似对话的谈话，雷姆发现这件事而有些尴尬，也痛恨起自己的消极个性。

雷姆与生俱来就是个性内向，这点她早有自觉。就积极而言，别说是拉姆，甚至远远不及充满活力的昴。

另一方面，爱蜜莉雅应该也是对雷姆无法掌握距离感。此种沉默就是最好的证明，也让雷姆对营造出此种气氛的自己感到羞愧。

当初果然不该接受爱蜜莉雅的善意──

「……偶尔这样静静喝茶也不错呢。」

「────」

「昴平常总是会说很多话，拉姆也会对念书的事提出很多建议，不过与雷姆在一起会变得很沉静。」

爱蜜莉雅带著微微笑容如此说著，让雷姆吃了一惊。由爱蜜莉雅侧脸的表情完全窥视不出半点虚假，表示刚才那是她的真心话。

将沉默误以为是坏处，还认为自己处事不周而垂下头实在很丢人。

「……大人目前读书的状况进展得如何呢？」

「我希望这样还算可以，因为原本我的起跑点就比别人还慢，所以觉得自己得再认真点。」

雷姆将视线转向办公桌寻求话题，这个问题让爱蜜莉雅垂下眼角。

身为下任国王候补的王选候选人，需要爱蜜莉雅达成许多门槛。不只是身为国王的才能，还有支撑其地位的各式各样知识与教养等等。

目前爱蜜莉雅仍然处在学习的阶段，现在就算是奉承也很难说是及格。即使如此，王选即将在不久之后正式展开。

「在那之前我想让自己变得更能干一些。」

「小的能够理解这种心情。罗兹瓦尔大人收留雷姆与姊姊后，一开始也是努力埋头学习。」

在刚离开村子的那个时候，先不论拉姆，雷姆对外面世界可说是一无所知。

在宅邸学习的事，也并非全然是身为佣人的工作与准则。除了最低底线的阅读书写以外，不知道的事情全部都在这里学会。就连爱蜜莉雅努力认真的学习，对雷姆而言都是曾经学过的事。

「拉姆与雷姆一开始也是一直念书吗？」

「是的。尤其是雷姆的脑袋没有像姊姊那么灵光，所以学得很辛苦。」

「你们两个也是一样啊，看来果然没有捷径呢。我原本还有点著急……看来得脚踏实地慢慢前进了。」

「爱蜜莉雅大人也会著急吗？」

见到爱蜜莉雅越说越没自信的模样，雷姆感到相当意外而瞪大双眼。爱蜜莉雅则是对雷姆的反应彷佛表示「这不是当然的吗」而鼓起脸颊。

「其他候选人都很厉害，我光是身为半妖精就会被视为问题，如果没有王选，我就会一～直待在森林了。」

艾利欧尔大森林，据说那是爱蜜莉雅长大的森林。除此之外，雷姆并没有得知关于爱蜜莉雅的详细出身经历。

──仔细回想起来，雷姆到目前为止皆刻意避免深入接触爱蜜莉雅。

原因是雷姆排外且保守的想法。对雷姆而言最重要的，只有无可取代的姊姊，以及姊姊身边的世界。

不论如何，雷姆都对爱蜜莉雅没有任何兴趣。因此除了罗兹瓦尔命令的事以外，她并不会主动干涉或支援爱蜜莉雅的动向。

而她也认为既积极且努力的爱蜜莉雅不需要雷姆的协助。

雷姆与爱蜜莉雅各自维持著原本的模样，在最低底限的关系中过著彼此的生活才是最佳解答，双方就是维持著这种微薄的关系。

不过──

「爱蜜莉雅大人的歌喉实在很可惜呢。」

「咦咦！？讨厌啦，怎么突然提到这件事！？」

爱蜜莉雅的安稳神情顿时一变，雷姆的发言让她哭丧著脸如此高声回问。雷姆一边留意著此种表情变化，一边仍然带著事不关己的表情说著：

「而且手艺出乎意料地不够巧，也有点太过纯真容易被骗。然后还容易受到周遭影响……还曾经戴过水桶。」

「水桶是昴要我戴的！而且那根本不是必要的！」

「是的，大人说得没错……这一个月雷姆全都知道。」

就连之前没有深入关心的爱蜜莉雅，现在雷姆也知道这些事，还有很多除了刚才所说以外的事能说。

听到雷姆的呢喃声，先前闹著别扭的爱蜜莉雅「啊」地将手抵在嘴边，然后露出恶作剧般的微笑。

「那我也要来报复一下，雷姆其实是个既顽固又倔强，还有喜欢图画书与诗歌，对美乃滋不太喜欢。还有与昴感情很好！」

「真不愧是爱蜜莉雅大人，没有任何反驳的余地，尤其是最后那句完全能够接受。」

「嘻嘻，我说得没错吧。不过你怎么会突然说这些事？」

得意地挺起胸膛后，爱蜜莉雅满腹狐疑地微微歪著头，雷姆对爱蜜莉雅的疑问摇了摇头。

「不，没有什么重要的意思。小的只是想要确认看看，明明遇见爱蜜莉雅大人已经过了半年，但在这个月感觉比先前发生了许多事。」

「……嗯，说得也是。自从昴来了之后变得好忙，与拉姆和雷姆也多了很多话能说。」

「所以就是……那个……」

无法好好说明内心的想法，雷姆开始沉思寻找答案。此种模样映照在爱蜜莉雅的深紫色眼眸中，而她只是静静地等待著雷姆的回答。

此种态度让雷姆下定决心。说实话，以前雷姆对爱蜜莉雅的进退毫不关心，甚至即使没有照著罗兹瓦尔的计划行事也不要紧。

不过，现在却怀著与当时截然不同的心情。

「雷姆也替爱蜜莉雅大人声援。面对即将到来的王选，虽然雷姆的力量应该是相当微薄……但只要是能力所及之处必当竭尽所能。」

「────」

「认识了爱蜜莉雅大人后，雷姆是这么想的。刚才那番话，就类似我的想法根据，而且是雷姆所认识的爱蜜莉雅大人。」

「……不都是一些奇怪的印象吗？」

「那个……也许是这样呢。」

当雷姆对问题回以恶作剧般的笑容，爱蜜莉雅则是回答「真是的」并鼓起脸颊，然后随即噗哧一笑，两人就这样隔著圆桌互相投以笑容。

「谢谢，雷姆肯对我这么说让我很开心，这都是多亏了昴呢。」

「……是的，昴真的是个很棒的人。」

「对啊，昴真的是个好孩子呢。」

互相分享微妙地有些不同的见解后，雷姆与爱蜜莉雅皆拿起茶杯送往嘴边。

在日正当中的喝茶时间，虽然变成了与想像中有些差异的时间──

「雷姆，我刚好有件事想拜托你。可以吗？」

「是的，大人有何吩咐？」

「再帮我倒一杯茶吧，感觉我现在好想喝雷姆泡的茶喔。」

──对于爱蜜莉雅的愿望，雷姆则是以发自内心的亲爱之情开始准备茶水。

4

呼叫的铃声让雷姆赶到时，有个令人出乎意料的组合正在等待著她。

「您叫我吗？罗兹瓦尔大人……还有大精灵大人。」

夜晚的罗兹瓦尔宅邸最高楼观景台──能够见到坐在椅子上的罗兹瓦尔，以及在他前方圆桌上的帕克迎接著雷姆到来。

化上小丑妆的魔法师与呈现灰色小猫姿态的大精灵，虽然这间宅邸有复数超越人类常识的存在，但其中最为醒目的两人让雷姆感到戒慎恐惧。

「真的只要一叫马上就会过来呢。不过，你不用这么畏畏缩缩的，想缩到比我还小应该是很难啦。」

「很抱歉，小人没有任何技术能够完成大精灵大人的期待……」

「不用这么认真看待啦，雷姆。刚才那只是大精灵大人开玩笑而已。」

「对对，这是精灵开的玩笑，虽然连精灵都觉得不太好笑喔。」

帕克用颇长的尾巴卷著身体，一副悠哉的模样发出笑声。而帕克的脚下……也就是圆桌上能够见到倾注琥珀色液体的酒杯。

另一个成对酒杯正在罗兹瓦尔手上，既然两人会拿著成对酒杯就表示──

「我正在和大精灵大人小酌几杯稍微放松一下心情，难得昴发现了家族秘藏的酒窖。身为子孙得好好确认祖先的功劳才行，然后下酒菜刚好吃完啰。」

「要叫老板娘过来啦，所以就叫你过来啰。抱歉啦。」

「老板娘……那是卡拉拉基地区称呼能干女性的方式吧？」

「雷姆，我刚刚才说过，别把大精灵大人的话当真喔。」

受到主人反覆提醒，雷姆恭敬地行了个礼。虽然帕克发出「噗～噗～」的不满回应声，但罗兹瓦尔仍然对这位大精灵的态度摆出一副事不关己的表情。

总而言之，雷姆随即理解到自己被叫来的理由。

「小的知道了，立刻替两位准备餐点。另外还有其他吩咐吗？」

「没有啰，交给你全权处理。」

「我要吃美乃滋！美乃滋很棒！」

收到主要是帕克的要求后，雷姆快步前往厨房，并且开始在脑中思考应有的食材。下酒菜与美乃滋，最近后者已经是宅邸餐点必备的调味料了。

昴设计出的美乃滋，在宅邸成员中算是颇受好评。

虽然雷姆不太喜欢那种太酸的味道，但由于众人──尤其是昴特别喜欢，因此可说是不可或缺的重要调味料。除了他以外，爱蜜莉雅、帕克与碧翠丝也对美乃滋赞誉有加，因此也能积极地运用在其他新的料理上。

不过下酒菜并没有要求做得如此完美，雷姆从使用魔石低温保存的储藏库拿出鱼，迅速地将切下的鱼肉煎熟并淋上美乃滋。

「嗯～～真是撼动我本能的香味呢。」

雷姆拿著下酒菜回来后，帕克一边洗著脸一边如此说道。

即使帕克的外表是小猫，照理说实体是精灵，但动作和嗜好与猫可说是没有两样。雷姆对此种模样按捺著苦笑的心情，并且将盘子放在圆桌上。

「只要把盘子与酒杯放在桌上，雷姆等一下就会过来收拾。如果没有其他事，雷姆就先退下了……」

「辛苦你啰。说得也是，你今晚就直接休息吧……虽然我想这么说，不过还是稍微陪我们一下吧。」

「──？好的，遵命。那个……雷姆对酒……」

「我知道你不会喝酒啦，就连闻到味道都很危险，所以稍微站远一点吧。」

被罗兹瓦尔留在观景台，雷姆稍微绷紧神情如此回应。罗兹瓦尔对她的话微微一笑，将手中拿的酒杯放在雷姆对面的远处桌边。

身为鬼族说来很丢脸，雷姆对酒完全没有抵抗力。

鬼都是喜好酒的酒豪──虽然此种传闻相当有名，雷姆在村落时也见过大人们无数次喝得烂醉如泥的模样，不过与雷姆不同的是，拉姆是不论喝多少酒皆能泰然自若的真正酒豪，可说是货真价实的鬼族象征。

「你们两姊妹真是太极端啰。虽然喝多少都不会变脸的拉姆很让人吃惊，不过雷姆是另一种层面让人惊讶，料理用的酒应该不会有问题吧？」

「或许是料理中能够分辨那是必要物，以及精神专注的差距。小人在宴席上实在无法维持紧张感……」

「在之前举办宴会的时候，你和莉雅两个人就是喝得醉醺醺的。虽然那样还满可爱的，不过我是希望你们稍微节制一下会比较好啦。」

面对垂下头反省的雷姆，开始享用菜肴的帕克如此说著，胡须上还沾著美乃滋。

宴会指的是前阵子罗兹瓦尔宅邸举办的「观星宴」。隐藏于宅邸的酒窖被发现，便用酒窖中的酒办了一场宴席。

而雷姆在那个场合出现了难以言喻的丢脸丑态。

「那时让各位见到不堪入目的模样了……」

「只是满脸通红和莉雅抱在一起还算可爱喔。我和贝蒂就算想得到酒醉的经验都没办法……贝蒂应该不算吧，那孩子的境遇又和我不太一样。」

对于帕克感触良多的谈话，雷姆不知道该如何回应。

「困扰的时候就会露出困扰神情，我觉得这是好事喔。」

「────」

帕克对沉默的雷姆如此说著并点了点头。应该说当雷姆对他的话感到惊讶而将手抵在脸上时，帕克的注意力早已回到盘子上了。

「不只是开的玩笑，就连善变的性格也是很难掌握呢。别太过在意，适度保持距离感才是面对大精灵大人的诀窍喔。」

「听起来好像很难，不过小的会努力试试……话说罗兹瓦尔大人。」

被出乎意料回答揶揄一番的雷姆对罗兹瓦尔的建议点了点头，然后重新转头看著他。光是这个举动，便让敏锐的罗兹瓦尔察觉到雷姆的意图。

「让你待在这么酒气冲天的地方也很可怜呢，所以我们赶快进入正题吧……是关于昴身体的事。」

「昴的……小人洗耳恭听。」

「关于他的身体，在森林太过劳累，让门的状况超乎预期很不乐观。」

虽然还不算严肃到情况危急，但罗兹瓦尔还是以认真语调如此说著。

在宅邸周遭森林衍生出的魔兽骚动──昴在这场骚动中身心灵皆受到剧烈创伤，而且留下了不少后遗症。尤其是用来使用魔法的必要器官「门」受到剧烈磨损，之后还得继续观察情况。

「不只是我和拉姆，爱蜜莉雅大人、大精灵大人、甚至是碧翠丝对治愈魔法的契合度都不太好。唯一具有契合度的你也只能专门治疗外伤，内伤问题不是你擅长的领域。」

「尤其是他只会粗鲁地随便乱用，所以让人很头痛呢。」

虽然帕克一副事不关己地出声揶揄，但无法否定这点才是最麻烦的。总而言之，罗兹瓦尔的事前声明是其来有自，既然身边没有人能够治疗──

「要请内诊的专门医师替昴诊疗吗？」

「前阵子那件事，他让村子和宅邸避免受到波及的功劳不能忽视。既然这样我也有义务以最大限度予以回报，所以我和大精灵大人一起动了很多歪脑筋喔。」

罗兹瓦尔张开双手如此开著玩笑，不过雷姆对这番话中的诚挚语气松了一口气。

既然罗兹瓦尔会用这种方式说明，表示他已经找到了解决问题的方法，十年来持续侍奉著他的雷姆很清楚这点。

问题是什么样的解决方法，以及究竟与帕克有何种关联？

「既有功劳，又有难得的机会，我想安排王国最强的治愈术师帮他诊疗看看，所以刚才正在拜托大精灵大人帮忙准备礼物啦。」

「其实明明就不需要我的许可。先不说心情层面的事，那块土地的持有权不是在罗兹瓦尔手上吗？不只是我，只要莉雅觉得『同族』平安无事，应该就不会插嘴干涉了。」

「说是这么说，要是让大人心情不好又变大可就糟糕了。」

「我很少会这样啦～～真是的，你很会记仇耶～～」

虽然两人高兴地如此笑著说道，但雷姆很清楚这番对话的实际情况相当夸张。

为了王选，罗兹瓦尔前往森林迎接爱蜜莉雅，结果与反对的帕克产生激烈冲突，据说甚至还改变了地貌与地形。

不过雷姆将这些事视为小事，将注意力放在自己被分配到的职责上，那才是罗兹瓦尔将雷姆留下来的理由。

「虽然看你一副不用多说也充满干劲的表情，不过我还是清楚地下达命令吧。雷姆，你负责监视昴……不，应该说是负责看管昴，避免他做出勉强自己的举动。」

「也就是说，这是罗兹瓦尔大人赐给雷姆的正当名分吗？」

「你还真是会误解成适合自己的意思呢，不过我不讨厌这样喔。」

「雷姆每天已经尽可能别踩到昴的影子，还有吸到昴吐出的空气，这是要雷姆随时随地看守著昴吧。」

「你是这样束缚自己的啊，我都不知道呢。」

得知雷姆自发地在日常生活中设下许多限制，让帕克瞪大双眼。但这还没有什么好惊讶的，这些只是冰山一角。雷姆因为害怕自己无法控制而设下的限制，不论质量都并非只有这点程度。

「不过，现在还不到说出一切的时候……」

「嗯？」

「总而言之！小人听命，雷姆接下来会遵照罗兹瓦尔大人的命令跟踪昴。这是罗兹瓦尔大人的命令，是无可奈何的事。」

雷姆并没有面对满脸狐疑歪著头的帕克，而是对罗兹瓦尔挺直背脊敬礼。然后以流畅动作回到观景台入口，再流利地行了个屈膝礼。

「那么小人失礼了，祝罗兹瓦尔大人与大精灵大人有个好梦……」

以比平常更加诗意的语调打声招呼后，雷姆便豪爽地离开观景台。

罗兹瓦尔与帕克目送她迅速离开后，便互相看著彼此。接著，帕克以尾巴前端指著桌上罗兹瓦尔的酒杯。

「那孩子应该是在下风处吧。」

「……刚才那个实在不是我特别设计的喔。」

小丑与小猫将各自的酒杯送往嘴边，若无其事地再度开始晚上的饮酒。

5

「──我已经敲门了，打扰了。」

以彷佛抚摸的姿势敲了敲门后，雷姆便溜进了房间之中。

在这个已经熄灭灯光的房间中，一对淡蓝色的光点在昏暗中浮现出妖艳光芒──简单说来，那只是雷姆被酒意吞噬的双眸光芒。

「我有好好敲门喔。」

再度如此强调事先做好预防后，雷姆便蹑手蹑脚地前往房间深处。这里是「日日夜夜」频繁造访的场所，就连闭著眼睛都能抵达目的地。

不过由于闭著眼睛无法达到最重要的目的，她反而将眼睛瞪得斗大。

「昴好可爱……」

在瞪大双眼的视野中，黑发少年在床上熟睡的模样映入眼帘。雷姆突然松懈地露出散漫神情，并且浮现出与其说是微笑更像是冷笑的笑容。

深夜在个人房间就寝前，像这样享受昴的睡脸也是每天的固定行程。晨间与夜晚的昴各有不同的魅力，雷姆便是怀著此种对昴颇为叨扰的想法。

而平常总是摆荡于欲望与罪恶感之间的心灵，今天总算摆脱此种苦恼。毕竟今晚并非是因为雷姆的私人欲望，而是带有罗兹瓦尔命令的职责。

「大人命令我要在能碰到的距离看守，所以这也是没办法的事。」

雷姆一边微妙地扩大解释主人的命令，一边跪坐靠在床铺边。当视线与睡眠中的昴同等高度，便能感觉到双方的脸一口气拉近距离。

这已经是能感觉到气息的距离了。

「……昴，在雷姆面前这么没有防备真的没关系吗？」

对于这道彷佛耳语般的呢喃，昴没有任何回应。

他不知道雷姆已经闯进房间，持续沉眠的昴出乎意料地睡相颇为优雅。与醒著时的吵闹模样完全相反，甚至连鼻息声都是相当安静。闭起锐利三角眼的安稳睡脸也是符合年龄，或许该说看来似乎更为稚嫩。

「────」

雷姆不小心比平常看得更加陶醉，让她难为情地羞红脸颊。

明明想要严格控管自己，怎么会变成这么心浮气躁的魔鬼呢？

以前雷姆见到姊姊拉姆醉心地不惜为罗兹瓦尔奉献身心，实在无法感同身受地表示赞同。

此种差距的原因是出自于雷姆对罗兹瓦尔怀著尊敬之意，而拉姆对罗兹瓦尔怀著思慕之情，但雷姆并无法理解甚至演变成自卑感。

但这时候菜月昴突然出现，他的存在感在雷姆心中越来越强烈，甚至能够理解到拉姆思慕罗兹瓦尔同样的心情。

以及此种热情在真正意义上完全无法控制的事实。

「────」

雷姆跪在地面，将上半身靠在床铺上，然后盯著昴近在眼前的睡脸。

「明明是个男生，手指却那么细致美丽，睡脸也像是婴儿一样安稳。不把头发弄干睡觉可是会翘起来的。」

雷姆屈指说著昴令人在意的部分，但不论什么都不能算是缺点，这也是雷姆罹患发热症状的可怕之处。

「嘴唇……」

在毫无防备的睡脸中，她将视线集中在特别缺乏防备的某处上。

为了呼吸微微张开的嘴唇，就在只要稍微将脸靠近便能接触的距离。能够感觉到吐出的气息，这在平常已经是超过限制的状态了。

「──啊……」

但意识到那个限制的瞬间，雷姆的世界迅速地回到日常。

即使被酒意吞噬，但其实只有少量闻到酒味。当酒醉一醒，便变回了严格律己不能碰触思慕之人的少女。

「……雷姆怎么会这么笨呢。」

当带有酒气的思考恢复清醒，后悔与羞愧随即一涌而上。羞愧让脸颊变得相当滚烫，雷姆对自己丢脸的模样咬著牙齿撑起身体。

罗兹瓦尔的命令毕竟是在保持分寸距离感下的监视，与先前并没有什么差别。将这点扩大解释当成是正当理由，可说是相当傲慢不敬。

「这些都是昴不应该诱惑雷姆的错。」

雷姆对仍然沉睡且被冠上无辜罪名的昴投以微笑，她原本打算就这样直接撤退，明天再偷偷向昴赔罪今晚的事。

如此决定后，雷姆凭靠著最后一点玩心，用白皙手指轻轻地触摸昴的嘴唇──

「──啊！」

当手指触摸到嘴唇的瞬间，昴突然嘴馋地动著嘴唇将手指吸进口中，手指被既火热又粗糙的触感一舔，让雷姆思考陷入一阵空白的混乱状态。

这段吸吮并没有持续太久，雷姆的手指很快被放开。然而──

「────」

雷姆呆滞地紧盯著右手的食指，停在原地完全无法动弹。即使在昏暗房间中也能清楚看见，手指上沾染著发出妖艳光芒的黏稠唾液。

「……这样应该勉强能得到饶恕吧。」

用手帕或围裙擦拭的选项很快从脑中消失，雷姆心中对手指只有两个选择──做与放弃两种。

虽然雷姆面对昴时会设下各种限制，但这次实在完全没有料想到，也没有思考过应对的处置。既然如此只能立刻当成新的问题，然后开始思考并做出结论，不过这也是相当困难。

这很显然是千载难逢，要是放过这个机会就不会再有这奇迹般的一瞬间。

「可是……」

雷姆心中的善与恶剧烈碰撞并开始掀起战乱。

身为崇高鬼族的后裔，不能倚靠从天而降的幸运。不过现在这个地方有意识的只有雷姆，没有任何人看到。要是被拉姆知道会怎么想？这是对那个完美姊姊也能抬头挺胸说出口的行为吗？说实话，被舔手指瞬间的记忆突然消失也让她颇为扼腕。

两种意见在脑中爆散出火花，雷姆呼出的气息越来越紊乱急促，额头浮现出汗珠，并且紧张地绷紧全身不断烦恼挣扎，接著──

「我还是……没办法……」

额头长出白角几经烦恼后，雷姆将沾有唾液的手指按在围裙上擦掉。虽然瞬间涌现出一股空虚感，但她还是认为这样就好而视若无睹。

「是这样吧，昴──」

撑过这段痛苦的时光后，正当雷姆带著孱弱笑容看向昴的睡脸时，她的话语突然中断并惊讶地吞了一口气。

雷姆原先将双手撑著床铺并喘著气，突然有双手腕绕过她浑身僵硬的上半身，以男性的腕力硬是将她拉倒。

「呀──」

这个突如其来的举动让她脑中再度一片空白。

脸颊一口气变得滚烫不已，红著脸的雷姆理解到自己身处的状况。自己是被抱著仰躺在床铺上，粗鲁的动作让制服四处皱褶，感觉裙子似乎也被掀了起来──总之是很丢脸的模样。

「────唔！」

雷姆发现这件事实时，出乎意料壮硕的手腕更加紧紧将她搂住。整个身体被抱在胸前，让雷姆的心脏几乎快要爆炸地剧烈跳动。

这样到底该怎么做？善恶雷姆再度开始交锋。这并非是由雷姆，而是对方主动做出的动作──

「唔呀……」

一团乱的脑袋听见此种让人心神不安的梦话，让雷姆一口气浑身无力。

她转头环视四周，昴仍然是深深沉眠，也没有发现自己正紧紧抱著等身大的抱枕。

「说得也是，昴不是这种人。」

这道呢喃中含有放心与些许失落感，这并非是他怀著意识做出的行为，让雷姆感到五味杂陈，因此她决定用全身享受昴的体温与味道作为慰问。

接著──

「没办法。虽然雷姆有拚命抵抗，但昴没有清醒完全无法动弹，所以只能在昴醒来之前继续抵抗。」

只留下这番表面话，雷姆直接用鼻子与额头磨蹭著昴的胸前，幸福洋溢地品尝著此种感触。

──毕竟有正当理由，偶尔有这么一天也不错。

如此说服自己后，雷姆的意识也一点点地沉入梦乡。

隔天，睡过头的雷姆与昴感情融洽地维持著此种状态，被前来叫醒昴的拉姆发现，于是不由分说地将昴狠狠修理了一顿。

──对雷姆而言，这一切也是极为平凡且幸福的一天。

** 『卡拉拉基女孩遇见猫』

1

说到「荒地合辛」，可说是这个世界无人不知的传说人物。

合辛的传说起源于世界西部荒野中，得回溯至四百年前许多小国互相争夺霸权的时代。

在无法算是受到地利眷顾，而差点被埋没于他国阴影中的小国──「卡拉拉基」这个默默无名的贫穷国家就是合辛最初揭竿的地方。

传说中，合辛并非是个天生具有武勇的人。

传说中，合辛是个擅长与人对谈并熟知引导人心的稀世天才。

传说中，合辛与卡拉拉基的统治者缔结善缘，不只是暗中掌控指挥国家政策，还在转眼间与他国缔结友好关系。有时是谋略、有时是友谊、有时则是以商才拓展人脉。

当合辛在西国称霸，忽略小国暗中活跃的各国发现时为时已晚。

将不足为惧的大多数小国纳入旗下，合辛成为大型联合国领袖，没有任何人能够阻止他的鬼谋神算。

就这样，群雄割据的时代宣告结束，在「荒地合辛」之名下诞生了卡拉拉基城邦。

「呼……不管听几次，合辛的传说都是让人头皮发麻呢。」

听完这段故事，少女带著陶醉神情吐出热烈的感叹气息。

那是个既可爱且长相楚楚动人的少女。年龄约十一至十二岁，身高比同年代平均值略为娇小，但端丽的容貌却是远远超过同年代的平均值。

柔顺发质的紫色头发、充满好奇心的水蓝色圆眼、以及白皙细致的肌肤。如果有人问起是不是某个富裕家庭的千金小姐，此种外观肯定任谁都会接受。

然而，这位少女──安娜塔西亚并非是出自于显赫家庭。

「嗯，怎么啦？这样一直看人家的脸很没礼貌呢。」

安娜塔西亚突然以狐疑眼神打量著对方，其中没有温室花朵的可爱气氛，而能瞥见不合年龄的狡猾与戒心。

毕竟考虑到她的出身，有这种敏锐度才是正确的，男子则是张开大嘴露出牙齿哈哈大笑。

「没什么啦。只是想到那个在巷子捡到的脏丫头，居然会出现这么不错的表情而已。真是感动、感动哩。」

「又提到那么久以前的事。有没有人说过大叔很烦啊？」

「如果要这么说，同一个故事要人说好几遍的安娜还比较烦吧！要做好心理准备还会被我说好几年往事啊！」

面对闹别扭嘟起嘴巴的安娜塔西亚，有个坚硬的大手掌粗鲁地摸了摸她的头。安娜塔西亚并没有拒绝，但她仍然带著不服气的眼神及表情，让伸出手掌的人不禁苦笑以对。

这种不服输的个性很不错，他认为要不是这样，自己就没有待在这里的意义了。

「算了，反正老人家就会一直说同样的话，人家就忍耐一下吧。」

「喔，你还真敢说哩。到底是在哪里学到这种话的啊？」

「酒馆的老板娘和常客都是这么说的。之前没有从烂醉的大叔口中问出弱点，是人家离开那里之前的唯一遗憾喔。」

安娜塔西亚耍著嘴皮子并吐出舌头，挣脱摸著头的手并走向门扉，途中还稍微将发型与和服仔细打理整齐。

「休息时间结束啦，大叔要是一直打混，可是会被忠甸先生开除的喔。」

「那还真可怕，只靠安娜赚的钱实在不够养活我这么大只哩。」

「为什么人家要负责大叔的食衣住啊！」

「那还用说，当初不就是安娜把我买下来的吗？」

露出锐利犬齿咧嘴一笑后，他用粗壮手指摸了摸自己的脖子。该处有个既冰冷且粗犷的金属，那是从前奴隶时代所留下的项圈，以前做为刑具的项圈现在已经是约定的象征了。

见到这个彷佛回想起约定的动作，安娜塔西亚屏起气息并随即点了点头。

「……嗯，是这样没错啦。所以大叔在人家筹好军费之前可不能随便死在路边，要好好照顾自己啦！」

快嘴地如此回应后，安娜塔西亚吐著舌头冲出房间。男子一边听著匆忙远去的脚步声，一边微笑看向窗户。

窗外是一片阴天，而微微产生雾气的窗子映照出自己的身影。

房间窗户能够见到无法完全容纳倒影的巨大身躯，以及与安娜塔西亚截然不同的野兽面貌。焦褐色的体毛覆盖裸露而出的皮肤，毫不顾忌地显露出与人类不同的兽人威容。

里卡德•威尔金──拥有在犬人族中仍大放异彩的体格，目前是受雇于忠甸商会的保镳，也是身同安娜塔西亚的后盾兼监护人。

不过关于监护人的部分，安娜塔西亚肯定不会老实承认。

2

忠甸商会的根据地位于卡拉拉基城邦第二都市「巴那」。

卡拉拉基是由一到十区分十个大都市，每个都市皆在都市长与都市法的掌管下，以小国家运作组合成为某种联合国的形式。

而在都市巴那中，忠甸商会可说是中坚规模的组织，隶属于卡拉拉基少数的大型商会利格雷特商会旗下。

虽然没有限定经商品项，但主要是盛行交易品，因此许多出入巴那的交易商涉足忠甸商会已经是惯例了。

光是如此，当都市正门开启让商人一起进入时，商会前便会大排长龙，商会成员与仆人忙得昏头转向也是家常便饭。

「──安娜塔西亚，现金要用完了，马上把铜箱和银箱搬过来！」

「好喔！」

「不是只有那些！还有……」

「还有麻袋吧，知道啦！」

在接近吼叫的各种指示声下，安娜塔西亚用细瘦手腕将木箱拿了出去。里面装满了用来支付用的硬币。铜箱装有铜币、银箱则是装有银币，不论哪边对少女而言都是过于沉重，但还是不能让硬币洒满一地。

安娜塔西亚的立场实际上并非是担任商谈的商会员，而是负责辅佐并四处奔波的助手，此种职位通称为「打杂工」。

安娜塔西亚照著指示与诀窍，将沉重的钱币箱接连放在商会员脚下。

在忠甸商会的交易区，会有都市外造访的商人直接搭乘犬车──也就是由大犬莱卡拉的车当场进行交易。在这个空间中有许多长桌，由商会员与旅行商人隔著长桌会谈，然后用金钱换取交易品。

每个商会员负责的项目皆有不同，这天安娜塔西亚跟随的商会员是负责服饰与纺织物，交易的金额幅度相当庞大，鉴定的作业也是令人晕头转向。

「下一个！去把排队的客人分散，别让我多费工夫和时间！」

「合辛语录『时间就是金钱』！」

连观看商会员是否对这个回答点头的时间都不能浪费。

安娜塔西亚钻过长桌绕到队伍中，一边来回比对放在载货台上的商品与目录，一边将等待排队的队伍分散。现场还有许多队伍，除了安娜塔西亚以外还有几位打杂工少年，但每个的工作效率都比安娜塔西亚还低。

比自己年长之人的工作量，安娜塔西亚将之加倍完成了，但她并没有感到骄傲，即使被周遭的人嫉妒也没有放在眼中，因此这也是很理所当然的。

就这样将自己负责的等待队伍消化后，安娜塔西亚准备开始处理其它队列的工作，正当她转头环视四周时──

「──！那边那个人在做什么！」

在某个打杂工来不及整理的队伍中，有名男子对安娜塔西亚的怒骂声跳了起来。那个骨瘦如柴的人假装要拿目录，实际上是想对货物动手。

听见安娜塔西亚的叫声，那名陌生男子发现自己的偷窃行为曝光，于是立刻拔腿逃跑。他将试图阻止的打杂工推开，一口气冲出交易区。

「不会让你逃走的！」

「滚开，小鬼头！」

不过，安娜塔西亚早一步张开双手挡在即将冲出去的男子面前，男子口沫横飞地对这位打杂工的抵抗挥出拳头，就在即将被击中的瞬间前……

「你是以为逃得掉喔，吃这招啦！」

大约有男子手腕与拳头双倍粗壮的手挥了过来，将这名可怜男子高高打向空中，然后直接倒头栽倒卧在交易区地面。

呻吟声让安娜塔西亚战战兢兢地睁开闭起的眼睛，表情也随之一变。

「大叔！」

「安娜，亏你能发现哩。可是别勉强自己啰。要是因为这样受伤，可是最蠢的亏本方式。你应该很讨厌不合成本的事吧？」

将男子揍飞的里卡德呵呵大笑，朝飞扑过来的安娜塔西亚如此说著。接著，他拎起那名男子的后颈，直接将他拉到外面。

「喂，给我过来。居然有胆在我看管的地方闹事，做好断只手的心理准备吧。」

「……都是这臭小鬼多管闲事。」

无视于里卡德的恫吓，那名男子带著发狂的表情瞪著安娜塔西亚。见到对方彷佛快扑上来乱咬的模样，安娜塔西亚缓缓接近并赏了他一个耳光。

响起一道空气破裂的清脆声响，让男子与周遭顿时哑口无言。

「做这种傻事贬低自己的价值，然后还恼羞成怒真是糟透了。被小女孩正面赏耳光，你这个人还有什么价值。真是丢脸！」

面对幼小少女的辛辣话语，男子只能忍气吞声不发一语，里卡德则是眯著眼睛看著安娜塔西亚──不过整个交易区随即欢声雷动。

「说得好啊！」「真是太爽快啦！」「死小偷看到没啊！」

「谢谢各位！」

对周遭传来的欢呼声投以善意后，安娜塔西亚变回了平常的花漾少女。此种态度变化让周遭气氛更加沸腾，里卡德则是趁机将窃贼带到外头。

「原本是要把你的惯用手扭断，再丢出城镇的哩。」

里卡德绕到交易区后方，将男子丢到土堆上。在地面匍匐的男子被吓得脸色苍白，不过里卡德只是用手指卷著自己的胡须。

「──今天就饶了你吧。我再怎么修理你，都没办法比刚才那丫头的巴掌更有用。你应该也有点自觉吧，别再让我看到你啊。」

挥了挥手将他赶走后，男子便慌张地逃离里卡德面前。望著他的背影离开后，里卡德伸著懒腰并准备回到看守交易区的岗位上时……

「你觉得刚才那个窃贼真的会改过向善吗？」

「……怎么，原来是忠甸。你有看到啊？」

里卡德被如此一问而回过头，有个细眼的微胖男站在眼前。那名男子穿著高级的蓝色和服──就是这间商会的代表，忠甸•阿格利。

忠甸将和服衣襬拍了拍，将细眼转往男子逃跑的方向。

「窃贼要切断惯用手再赶出都市这个习惯……商会的保镳里卡德先生应该不会不知道吧？」

「因为安娜的关系让他偷窃未遂，而且刚才那件事让他吃了比断手更惨的教训，在我看来那边还可怕多了哩。」

「不是每个人有机会都会从歪路回头的。」

「这点程度我当然懂啦──我已经记得他的长相了，要是他下次在附近动歪脑筋，不只是惯用还是不惯用手都会直接扭断，这样可以了吧？」

当里卡德低声如此回应，忠甸稍作沉默后便表示同意。

「那就好，我只是担心『猎犬』里卡德是不是想袖手旁观而已。」

「别这样说啦，这样很丢脸哩。现在我不是商会饲养的戴项圈忠狗吗？汪汪。」

「那么，如果您是真心认为是我们养的狗就放心了……嗯，就当成这样吧。」

「这还真是话中带话哩……」

里卡德哼了一声并如此回应面带严肃的忠甸，忠甸对这个反应无奈地摇了摇头，然后开口继续说道，「话说回来……」

「……怎么了？」

「我有件麻烦事想找您商量，详情请到我的房间聊聊。」

对于忠甸令人不安的话题，里卡德也更加眉头深锁。

──因为根据经验，以这种方式开始的话题从来不会是「有点麻烦」而已。

3

「您知道最近巴那附近的商队频繁受到攻击的事吗？」

当里卡德被找到会长室而浑身不自在时，忠甸则是如此开口说道。

这个话题让里卡德皱起眉头回应「算是知道」，巴那附近商队受害的报告也有传进里卡德的顺风耳中。

「不过只是稍微听到传闻而已，都市外头的事已经不是商会保镳该处理的范畴了吧？应该说受害的都是外头的商人……不是我负责的范围吧。」

「虽然您说得没错，从外头来的商人是我们的重要经商对象，而且载来的货物之后也会成为我们的商品。要是被野外强盗掠夺，让旅行商远离巴那就会造成很严重的损失。」

「……所以该不会是要我想办法解决那些强盗还是盗贼吧？」

虽然里卡德有颇为显赫的经历，但如此备受期待也让他很头痛。

会以商队为目标的盗贼团，规模最少不会低于五十人，根据状况还有可能到百人规模，独自一人面对只是愚蠢至极的行为。

「既然对方这么多人，就算找我也是没用啦。这又不是一个人能解决的事。」

「嗯，关于这件事还请您放心。」

面对里卡德的此种疑虑，忠甸以老谋深算的虚伪表情笑著回答：

「巴那的都市议会也将这件事视为问题……所以从我们的商会为首，商业联盟也会出钱聚集人手。然后请里卡德先生率领那些人，找出那个闹事的盗贼团全部消灭，总之就是这么回事。」

「……这样也已经是很麻烦的问题哩。」

里卡德如此嘟哝，但他内心也很清楚自己渐渐没有退路了。

从卡拉拉基的建国过程，商人在都市中可说是有很强的发言权。

参与都市管理的议会相关人士，大部分是有力商人与商会领袖。忠甸也是其中一人，他会这么说表示议案应该早已提出，而且进行到只需要当事人里卡德点头同意的程度。

「要身为犬人的我带领乌合之众吗？真是的，你们到底在想啥啊。」

「有能之人才能得到发挥长才的合适立场，这是很理所当然的道理。」

忠甸脸不红气不喘地如此说著，接著在桌子上摊开地图。这是巴那周遭的地形示意图，能够见到复数商路上以红色印记做出标记。

「这是周边的商路与商队遭到袭击的场所。被袭击的商队没有任何幸存者，货物与运货犬也会被掠夺，以盗贼团来说做得相当彻底。」

「既然是在这么近的地方犯案，表示根据地应该也在这附近吧。」

里卡德一边望著地图，一边盯上袭击地点附近的树林与岩石区。既然是有相当规模的盗贼团潜伏，很有可能就是以这附近作为根据地。

当两人盯著地图如此讨论时──

「打扰了～～我把茶水端过来啰～～」

安娜塔西亚如此说著，手里捧著发出蒸气的托盘进入房间，然后将装有绿茶的茶杯放在里卡德与忠甸面前。

「怎么，安娜在负责端茶啊？打杂的工作怎么啦？」

「已经过了最忙的时间，他们说只要把茶端过来就可以休息了。话说回来，你们两个为什么在看地图？」

安娜塔西亚顺便将自己的茶一起拿了过来，她对绿茶吹著气并歪著头如此询问，里卡德对这个问题指著地图回答：

「这个红圈附近听说死了不少人，现在忠甸把难题丢给我要我解决啦。」

「咦，大叔吗？没问题吗？」

「喔，你还会担心我啊。」

里卡德似乎很高兴地咧著嘴，安娜塔西亚却摇了摇头表示否定。

「不是啦，找犯人是要用脑袋的工作，大叔真的有办法吗？」

「不需要担心，我拜托里卡德先生的事只是把找到的犯人头打烂。这样就是他的拿手领域了吧？」

「啊，这样就没问题了，人家也松了一口气。」

里卡德对一拍即合的两人发出叹息声，被此种彷佛狂风般的叹息一吹，安娜塔西亚气得大叫「大叔！」里卡德则是用手指指著她的脸。

「刚才不是在讨论玩的事，接下来是大人讨论事情，小丫头还是去外头追蝴蝶就好哩。」

「我才不会追蝴蝶那种没有半毛钱的东西。话说能不能也让人家听听看？要是什么都不知道说不定也会很危险喔。」

「城镇外面的盗贼，里面的打杂小妹就算不知道也不会危险吧。」

「哎呀，没关系啦。说不定这件事会一直麻烦里卡德先生，也让安娜塔西亚听听吧。」

不同于不情愿的里卡德，忠甸对安娜塔西亚的兴趣表示善意。原本他就对安娜塔西亚的未来充满期待，因此在这种时候就会展现出宽容的一面。

对于里卡德而言，他不太想让安娜塔西亚接触血腥的世界，这也是周遭嘲笑他过度保护安娜塔西亚的原因。

「喔～～什么嘛，城镇外面也是有很多麻烦事嘛。」

听完与里卡德同样的说明后，安娜塔西亚回以这个平淡的感想。对于这个如同完全不知道情况的孩童般回应，她会如此回答也是很正常的。

但一反里卡德在心中如此说服自己，安娜塔西亚突然说著「话说回来……」

「那些被攻击的人载了什么货物？」

「货物吗？根据报告，来到巴那之前是载著宝石与古董出发，也有魔石工艺品、魔矿石和武具之类的商队受害。」

「喔，这样啊──好奇怪喔。」

安娜塔西亚歪著头，只在口中如此喃喃说著。

「好啦，已经够了吧。忠甸也别一直把奇怪的事告诉这个丫头啦。」

里卡德也有发现这段呢喃声，但比起对话更优先于将她赶出房间。虽然安娜塔西亚仍然对这件事带著严肃神情，但忠甸也只好无奈地要她离开房间。

「真是的，怎样啦！大叔真坏心耶！」

安娜塔西亚吐出舌头，拿著喝到一半的茶杯被赶出房间。目送她离开后，里卡德关上门并耸了耸肩。

「真是过度保护安娜塔西亚呢。」

「你爱怎么说就怎么说。对啦，我就是过度保护，所以我不会让带来不良教育的家伙接近安娜在的这个城镇，我会马上解决掉这件事。」

里卡德不想再被调侃，于是龇牙咧嘴地瞪著地图。近距离笼罩在巨大身躯释放出的压迫感下，忠甸微微绷紧脸颊并吐出一口气。

「终于显露出『猎犬』的真面目啦。觉得可怕的同时，也开始庆幸您是站在我们这边了。」

4

──在忠甸商会那场对谈的几天后。

在巴那西方的某个酒馆中，有位少女正趴在柜台上，对店内的女店长不断发著牢骚。

「然后就把人家丢著不管了，还把我当成包袱，大叔真的很坏心耶。」

「原来是这样啊，难怪好几天没看见那张狗脸，是这么回事……所以安娜才会像这样在我这里大喝一顿啊。」

「对啊，人家好伤心喔。老板娘，快安慰我吧，然后我要再一杯牛奶。」

被称为安娜并要求再来一杯牛奶的少女，当然是各位熟知的安娜塔西亚。而开店前被安娜塔西亚缠上的老板娘，则是体贴温柔地做出应对。

对老板娘而言，安娜塔西亚是直到三个月前都在这家店工作的可爱员工。虽然没有到里卡德那么夸张，但老板娘也是相当疼爱安娜塔西亚。

因此，即使她在开店前造访也是不加追究，也不吝啬于听她抱怨发牢骚。

「不过真让人意外，我还以为你们两个的关系是里卡德单相思，没想到安娜也会对他离开感到寂寞啊。」

「毕竟大叔已经是我的东西了，是我预约他的项圈，所以不能让他离开我的视线范围。到底懂不懂啊，真是的。」

在里卡德的粗壮颈项，仍然戴著枷锁已损坏的项圈。

那是奴隶时代束缚著他行动的项圈，目前已经是没有任何功用的装饰。不过即使已经舍弃奴隶身份，里卡德仍然将那个项圈作为警惕戴在身上。

安娜塔西亚就是对那点相当不满意。

总有一天要用适合的价格买下里卡德，然后亲手把那个项圈拆下丢掉，这是安娜塔西亚众多梦想的其中之一。

「多亏大叔和老板娘，人家距离实现梦想又大大跨出了一步，所以人家得更努力点才行。」

「安娜的梦想？是什么样的梦想，我可以听听看吗？」

「人家的梦想就是变成像伟大的合辛一样！所以现在是为了这个梦想蓄积力量、知识和金钱的雌伏时间！」

见到少女激动地阐述梦想的模样，老板娘忍不住差点笑了出来。

有许多商人憧憬著「荒地合辛」的传说，只要是生为卡拉拉基的男性，几乎都会对他出人头地的故事怀抱著梦想。

但既然是身旁的少女怀著此种梦想，那又是另一回事了。

「真是的！连老板娘都笑我，这种反应和大叔一模一样！」

「抱歉抱歉，不过我觉得那不见得只会是梦想喔。实际上安娜也被大商会的忠甸先生带了过去……要是变成忠甸先生的太太，至少就会成为都市的高层分子了吧？」

「人家嫁给忠甸先生？这不可能啦，不可能不可能。」

少女呵呵呵地发出天真笑声，看来她似乎对自己的端丽容貌毫无自觉。就连现在安娜塔西亚也是十分可爱，总有一天肯定会成长为美丽女性。

到了那个时候，老板娘刚才的发言应该也不会是玩笑话了。

「我说安娜，现在你可能不会相信，不过你还是把我说的话好好记起来。安娜比普通女孩子还要可爱，所以可能会有些人打歪主意。要是一感觉到不对劲，要立刻找里卡德和忠甸先生商量喔。」

「呃……可是老板娘，怎么可能……」

「别问这么多，把话记起来就好。」

被带著认真表情如此告诫，安娜塔西亚回答「好啦～～」并对老板娘的话点了点头。她察觉到接下来可能会继续说教，于是将续杯的牛奶一口气喝光。

「谢谢招待。人家今天还有工作，要先回去啰。」

将牛奶费用的三枚铜币放在柜台后，安娜塔西亚跳下柜台旁的座位。虽然老板娘瞬间露出惋惜的表情，不过随即对前往店外的小小背影挥了挥手。

「安娜，下次休假记得要再来哩。」

最后老板娘难得用卡拉拉基腔告别，安娜塔西亚则是离开酒馆。

「嗯～～还有一点时间……大叔也不在这里，要怎么办呢？」

安娜塔西亚在店外伸了个懒腰，还有空闲时间的她开始思考该做什么。

今天是休假日，也是每周一天的完全假期。虽然对老板娘说还有工作，不过其实没有任何行程。即使如此，跑去交易区帮忙很显然只会被人白眼。

「要是被说成摆出一副得意模样也很麻烦……好吧，干脆去买东西边走边吃吧。」

安娜塔西亚挺起平坦胸部，迈步走向行人众多的拥挤街道。像这样带著自己的钱包边走边吃，也是她不为人知的兴趣。

在暗巷生活的那个时候，摊贩贩售的食物可说是饥饿的敌人。由于现在已经能够好好享受味道，因此也让她认为自己算是很有福气。

「嗯……」

像这样一边吃著买来的甜点一边前进时，她突然感觉到一道视线。

安娜塔西亚朝视线传来的方向瞥了一眼，正好某个与紧盯著她手的脏兮兮少年四目相对。她很快想像到对方的身份，那是在都市暗处贫民窟生活的「鬣狗」。

没有家也没有食物，只能拚命翻找垃圾堆寻找每天粮食的人皆称为「鬣狗」，据说那是从合辛时代就流传至今的称呼。

而安娜塔西亚以前也曾经是「鬣狗」，无法得知自己是否有明天的处境绝非他人之事，对少年的视线也是感触良多。然而──

「──真蠢。」

安娜塔西亚将剩下的甜点一口气吃进口中，故意将空容器现给少年观看。被她如此恐吓，少年慌慌张张地逃回小巷中，可说是毫无霸气。

就像是期待著施舍，态度宛如开口等待喂食的雏鸟，这是最让安娜塔西亚感到不舒服的地方──实际上她自己就是受到施舍才得到现在的立场。

就是知道这件事，安娜塔西亚心中有种作茧自缚的痛楚。

自己还有里卡德陪在身边，可是里卡德说不定──

「啊～～！？」

思考事情的空档被人趁虚而入，有个人从背后伸手摸进她的怀中。虽然她立刻挥开，但还是太晚了。能够见到有个从安娜塔西亚怀中摸走钱包的小小背影，蹦蹦跳跳地冲进巷弄中。钱包被偷走了──而且没想到会这么简单。

是被偷的人自己太蠢，曾经身为「鬣狗」的安娜塔西亚也很清楚此种想法。如果是平常也许会无可奈何地选择放弃，但这时她完全没有此种想法。

「站住！」

安娜塔西亚追著逃走的人影，也跟著冲进暗巷中。虽然已经很久没有在巷弄中的崎岖地面奔跑，但毕竟是懂事以来便四处跑跳数年的场所，身体还记得在这里奔跑的方法。

安娜塔西亚立刻追上对方，用脚步声与声音引诱对方，就这样直接将对方逼进死巷子后，发现完全掉入圈套的人影则是懊恼地回头看著安娜塔西亚。

「好了，快把钱包还给我。要比经验你是比不上人家的。」

「什、什么经验啊……像你这种穿著漂亮衣服的家伙……！」

就算说以前是同样立场，对方也不会相信，而且也没有特地说出口的必要。

安娜塔西亚逼近那位瞪著她的少年「鬣狗」，准备将钱包拿回来。不论是营养状态还是在商会学习的防身术，要拿回钱包可说是易如反掌。然而──

「──没错，像你这种小鬼头别装成一副很懂的模样。」

「──！？」

身后传来一道男性声音，让安娜塔西亚连忙回过头。

但一道坚硬锐利的冲击更为迅速地击中头部，让她当场倒在地面。手脚无法使力，意识也随即开始远去。

「嘿，干得不错啊。拿去吧，拿著钱包快滚！」

这道谈话声让安娜塔西亚依稀察觉到自己掉入圈套，这是某个人设下的陷阱，那道粗鲁的声音感觉似乎在那里听过。

──感觉才刚在交易区听过这名男子宛如诅咒般的声音。

5

另一方面──这时里卡德率领的佣兵团也在击退盗贼这件事碰到瓶颈。

虽然在地图上标记的地点，也就是都市周边的树林发现了强盗，但规模并不足以袭击之前所说的商队。数十名强盗一见到里卡德等人便溃散四处逃逸，今后应该也不会再从事不正经的勾当了。

然而，除此之外没有任何成果，也丝毫没有掌握到商队袭击犯的任何踪影。

「在森林发现的洞穴也是扑了个空，不过从那么窄的入口原本就没什么好期待了……」

扑空的报告接连传来，在地图上打叉的里卡德也显得闷闷不乐。

虽然临时组成的佣兵团默契不足，但他认为是自己没有尽力才无法拿出应有成果。即使如此，整件事的扑朔迷离也是令人相当在意。

「也有可能已经改变根据地了吧？和我们出来讨伐盗贼的时间点也太巧合了……」

负责管理都市的议会也并非是团结一致，不能保证没有希望现任议员失势而帮助盗贼的人。要是如此，状况会持续变得复杂许多。

不过，里卡德总觉得还有别种谋略牵涉这件事。

「里卡德，这些是要从巴那出发的商队，还是姑且见见他们一面吧。」

「好喔。」

在扎营处的帐篷中，副队长如此呼叫著低吟的里卡德。从帷幕来到外面时，能够见到拉著十数台犬车的商队正在黄昏街道上成群结队前进。

其中有许多壮硕的护卫，可说是相当程度规模的大型商队。

「这种时候还要出远门啊，你们还真忙哩。」

「要是被天候影响会错失商机，我们可不想被天上的合辛耻笑啊。」

「嗯，也是啦……不过亏你们带了那么多壮汉护卫啊。」

「听说最近这里的治安不太好，和小哥你们也不是毫无关系吧？」

率领商队的壮硕男子用夸张动作耸了耸肩，里卡德并没有回答男子的话语，而是走向商队的犬车并翻开盖著载货台的布。

载货台上放著铁制牢笼，其中放置著商品──也就是复数的人类。

「……是奴隶贩子啊。」

「小哥看不顺眼吗？那个项圈原本也是奴隶的证明吧？」

男子指著里卡德的颈部，见到宝珠脱落的洞孔便如此说道。是否有宝珠便能够分辨戴著项圈的奴隶身份，里卡德的情况就是身为解放奴隶的证明。

「奴隶商也是很正式的商业手段。只要有遵守条约，我也没资格说话。」

对有著委靡眼神的奴隶们冷冷哼了一声后，里卡德便离开犬车，然后对商队代表说声「可以走啦。」

「不好意思把你们留下来，路上我们也会注意情况，不过你们还是自己小心哩。要是被传闻中的强盗袭击，别说是全身家当，连小命可能都会不保喔。」

「还真恐怖哩，我会尽量注意啦。」

男子假装害怕地笑著回应后，便驱车让商队出发。里卡德也离开犬车车队，命令佣兵们目送开始移动的集团离开。

「──狼先生，你的表情还真帅气呢。」

接著，在犬车队列最后方殿后的护卫男性，突然用黏答答的语调对里卡德如此说道。

那是个身材壮硕的男子。比超过两公尺高的里卡德更高，虽然体格幅度没有里卡德宽广，但满是刀伤的战场经验似乎毫不逊色。

而且男子身体最醒目的，就是由肩膀延伸而出的四只手──表示对方是个多腕族。

「居然不是在帝国，难得会在卡拉拉基见到多腕族。」

「呵呵，是啊。大部分多腕族都是流浪到佛拉基亚，不过我的祖先有卡拉拉基的血脉，所以我是继承那个血脉的末裔。」

男子瞪大双眼展现出四只手分别握著的板斧，然后带著阴沉笑容如此说著。虽然里卡德不太喜欢他的笑法，但对他的装扮更为看不顺眼。

强者的姿态与只保护要害的轻装皮甲，头上还披著毛皮。里卡德就是无法容许那种毛皮的装饰感，那很明显就是──

「你很在意吗？会很在意吧？呵呵，说得也是，毕竟这可是与你同族的狼人族毛皮。要把杀害对象的毛皮漂漂亮亮地割下来，可是很辛苦的呢。」

「你好像误会什么了，我只是单纯的犬人……是可勃鲁特族的。只是不小心饭吃太多养太大只而已。」

「呵呵呵！我知道啦，你们狼人族因为已经濒临灭亡，所以被教导成要这么说。为了存留血脉必须整族都撒谎，比起灭亡的鬼族还要优秀不少嘛，是不是啊？」

男子挑衅地歪下腰探头如此说著，里卡德并没有被激怒，而是仍然将双手挽在胸前，用下巴指了指逐渐远去的犬车尾端。

「你要被留下啰，不是护卫吗？别在那边卖弄色相好好工作吧。」

「……真可惜。哎呀，真是太可惜了。呵呵……可惜可惜。」

用黏腻语气如此说完后，男子将四根板斧重新背回背上。然后以大眼由上到下打量著里卡德，接著……

「我叫迪德利。如果在哪里见面，想再多聊聊这个毛皮的事呢。」

「这样啊，迪德利。我倒是不想再见到你了，因为下次见面我可能会想把你的脑袋砍下来啊。」

「呵呵呵呵呵！」

似乎很满意里卡德的回答般，迪德利不停点头如捣蒜。之后他以轻快的步伐追赶犬车，追上集团并老实地离开。

直到最后毫不松懈地目送对方离开后，里卡德则是转动脖子让骨头发出清脆声响。

「真是一群诡异的家伙。」

「奴隶贩子大概都是那个样子吧……还有个没办法这么简单区别的狠角色。他说自己叫迪德利，你们知道吗？」

「我不知道，也许有人知道他是谁。总之还是问问看吧。」

「虽然和讨伐盗贼没有关系……算是个人兴趣吧，那种自以为是的蠢货对小孩教育也不好，没工作的时候看到再做掉他好哩。」

当里卡德愤愤不平地如此呢喃，身旁的副队长不禁瞪大双眼，然后便噗哧一笑。

「你是在笑什么？」

「我只是觉得你变了。最近在佣兵那边很有名喔，说那个『猎犬』被一个名不见经传的小丫头迷得神魂颠倒。」

「你们这些家伙……真是闲到没话可说了喔。」

用手肘顶了一下副队长后，里卡德便发出脚步声走回帐篷。

他打算重新清查出盗贼的巢穴，要是没有拿出这点成果，就算是被忠甸冷嘲热讽都不奇怪。

「而且安娜也是，把她丢著不管可是会闹别扭的哩。」

将这句话说出口的当下，他回想起刚才被副队长笑的事而感到有些怅然。

也难怪这个样子会被当成传闻，虽然被迷得神魂颠倒是误会，但他承认自己随时注意著她。所以更应该要──

「如果能平安无事，让她和平过活才是最好的哩。」

在钻过帐篷入口前，里卡德望著夕阳西下的方向如此喃喃说著。

夜色与夕阳混合的天空呈现淡紫色，与里卡德脑中所想那位少女的发色同样，是相当美丽的颜色。

6

──而里卡德的愿望扑了个空，安娜塔西亚目前正面临著人生中最危险的困境。

「嗯～～嗯～～！」

嘴巴被紧紧塞住，手脚也被彻底捆绑，甚至连撑起身体都无法如愿，简直是有如范本的监禁状态。

安娜塔西亚认为情况实在很不妙，于是拚命扭动身躯并发出声音。

一醒过来后，她随即发现自己情况有异。她只用一瞬间判断情况，脑中仍然鲜明地记得失去意识前的事。以被监禁的人而言，这点安娜塔西亚可说是异常冷静，但能否找到突破困境的方法又是另一回事了。

──在失去意识前，她回想起动手殴打她的人。

那是数天前在交易区曾经进行偷窃的男子声音。那个人被安娜塔西亚看穿手脚，然后被里卡德修理了一顿，之后带著怨恨的脸颊还被甩了一巴掌，获得满堂喝采的景象仍然记忆犹新──是对方记恨才会尝到这种苦头吗？

「偶就说踏输太框聪了哈……」（我就说大叔太宽容了啦……）

对于窃贼严格惩罚，这就是卡拉拉基的风格。依照此种原则，那名男子当然得受到折断惯用手的惩罚。即使如此他仍然执意对安娜塔西亚复仇，此种怨念可说是很值得敬佩，很想叫他把这种热情用在别的地方。

「────」

将责任推给里卡德后，安娜塔西亚总算恢复冷静。

总之这样继续吵闹也是于事无补。房间中没有见到窗户，感觉声音也无法传到外面，或许该说不可能选吵闹声会传出去的地方做为监禁场所。

从声音回响的感觉来看，房间并不算宽敞，躺著的地面也是坚硬冰冷的岩石地──并非是铺设石材，而是直接将小屋盖在岩石区，地面感觉没有经过整地，就各种意义而言可说是相当随便。

──把我抓来的那个男人，到底有什么目的？

稍微观察过房间后，安娜塔西亚开始推想对方的目的。

如果是那个窃贼，动机应该是复仇，问题是复仇的内容。毕竟不惜做到这种程度，不可能只是吓吓人就放过她。如果是思虑短浅的人，也有可能会选择折磨后再杀害。

「应开是配卖票汤图隶吧……」（应该是被卖掉当奴隶吧……）

卖给奴隶贩子，这应该是最有可能的选择。

不只是巴那，原本在卡拉拉基城邦从事贩卖奴隶并不罕见。人手是能够作为劳动力的珍贵资产，举凡佣仆或修整街道等等有著各种需求。

安娜塔西亚在贫民窟时，也曾经许多次差点被奴隶商人逮住。即使在巴那的都市法律中，完全毫无保障贫民窟「鬣狗」的奴隶化，因此不对衣衫整齐的孩童出手，也已经是奴隶商人之间的不成文规定。

「真是高砸啦……」（真是搞砸啦……）

既然都已经被抓，也没什么藉口好说了。

毕竟忠甸商会能够保证安娜塔西亚的身份，应该说还有里卡德在。要是被卖给奴隶商人的事传到他耳中，里卡德肯定会对犯下此举的男人痛下毒手。

这并非是自夸，而是客观的事实──不过其中多少有些自以为是。

「我是说真的啦！这是高级货，你们只要看到就知道了！」

正好在安娜塔西亚如此做出结论时，能够微微听见有人的声音逐渐接近。

有名男子以沙哑嗓音粗鲁地说著话，并且进入昏暗的房间。安娜塔西亚还记得那张脸与声音，果然就是先前那名窃贼。

在那名男子后头又有两人走进房间，不论哪边都是身材魁梧，比起那个身形消瘦的男子简直是是枯树枝与大树干的差别。

「咱们不是怀疑你，只是被逼急的人总是会失手啊。」

「别、别开玩笑了啦，我怎么可能会做那种不要命的事。你、你们看……就是她……」

被其中一位壮汉如此吓唬，让那名窃贼顿时惊慌失措。见到他用颤抖的手指指了过来，安娜塔西亚立刻装成昏倒的模样。

安娜塔西亚感觉到对方缓缓窥视的气息，接著……

「什么嘛，真的是高级货哩。这个小美女以后长大可是会变成大美人，这简直是大奖中的大奖啊。」

「呜……」

躺在地上的头被抓了起来，硬是被拉起上半身让安娜塔西亚发出呻吟声。但男子并没有发现安娜塔西亚醒著，就这样持续转动头，粗暴地品头论足。

从对话内容来看，这名男子就是奴隶贩子。被说成是高级货，让脑中回想起酒馆老板娘曾经说过的话，当初把那番话当成耳边风看来是错的。

如果可以的话，希望能有机会能再见到她当面道歉。

「那、那么……交涉就算成立了，是吧？」

「当初是说带土产想加入咱们的商会吧？说得也是，既然有这么上等的货色，对咱们来说也是帮了大忙啦。」

「那么！」

「不过哩，前提是这丫头不是被其他地方绑著的野狗。」

「咦……」

传来彷佛松了一口气的声音后，发出重重撞在墙壁上的暴力声响，然后随即听见闷哼与四处打滚的声音，让安娜塔西亚理解到是那名窃贼遭到痛殴。

这就是外行人擅自跨越奴隶商不成文规定的惩罚。

「啊啊！啊啊啊！痛……好痛啊啊啊！唔呕！」

「别在那边大声嚷嚷，睡觉的小朋友都被你吓醒哩。」

奴隶贩子放开安娜塔西亚并传来回过头的气息，她微微眯著眼确认状况，只见贩子正俯视著倒卧在地面的窃贼，用脚跟踩著腹部让他接连发出惨叫声。

「听懂了没？咱们奴隶贩子也是有规矩哩，是勉强走在都市法律边缘才能干这行，不懂规矩的家伙是要怎么在咱们手下做事啊？知道了没啊？」

「咳噗……对、对不起……」

连安娜塔西亚都能听到体重压迫骨头的声响，窃贼吐著血并拚命求饶，奴隶贩子则是蹲下身体将脸靠向他。

「这样学到了吧？这不是好事嘛，接下来会在实地好好教会你该怎么做，别担心啊。」

「谢、谢谢……」

窃贼发现自己获得饶恕而准备道谢时，却被迫打断话语。

一道「铿锵」的金属声响与窃贼「咦？」的疑问声互相重叠。窃贼用颤抖的手指摸著自己的脖子，冰冷坚硬的感触让他露出绝望神情。

「为什么……我要戴上奴隶项圈……？」

「刚才不是说要实地教你吗？学会奴隶规矩的最快方法就是成为奴隶。看你好像没什么毅力，不过还年轻，只要运气好就能活下来哩。」

「这跟当初说的不一样噗！」

侧脸被狠狠踢了一脚，让窃贼翻著白眼昏了过去。确认过他昏倒后，奴隶贩子继续将他戴上手铐，然后将他丢在地面。

「真是的，外行人就是这点才麻烦。呃……对啦，有这么上等的货色还真是走运哩。反正违反规则的人也变成奴隶，这样就没有人吃亏啦。」

「对变成奴隶的他们两个是吃了不少亏呢。」

面对奴隶贩子的感想，先前持续保持沉默的另一人以黏腻语调如此回应。奴隶贩子对这个回答只是歪著头发出「啊～～」的声音，并且将视线转向安娜塔西亚。接著……

「不好意思啦，咱不把奴隶当成人看。这是商品，和肉或鱼是一样的哩。」

语毕，奴隶贩子带著一起同行的壮汉离开小屋，门扉外再度传来上锁的声音，气息则是逐渐远去。

在回归黑暗与无声的小屋中，安娜塔西亚将先前憋著的气息一口气吐了出来。心脏跳得很快，全身都是冷汗，而且希望对方没发现就好了。

「不购画搓回来……」（不过话说回来……）

居然会被很像奴隶商的人看上了。

虽然连那个窃贼也被当成商品，但安娜塔西亚并不觉得一吐怨气。

毕竟报应来得早晚，对安娜塔西亚没有任何意义。

──经过几小时后，安娜塔西亚凭感觉判断已经到了夜晚。

这段时间她一直被迫躺在冰冷地板上，虽然安娜塔西亚好几度被想翻身的冲动折磨，但每次都得忍耐下来。毕竟……

「为什么我会碰到这种事……可恶、可恶……」

因为恢复意识的窃贼无法接受现实，不断哭哭啼啼地自言自语。

要是发现安娜塔西亚醒著，肯定会将她骂得狗血淋头，因此为了避免不必要的杂音，只好继续忍耐不让自己翻身。

不过话说回来，对坚硬地面躺起来不舒服感到不满，以前的自己从来没想像过这种事。安娜塔西亚不认为这是现在生活太过安逸而变得脆弱，现在并没有任何不好的地方，甚至还让她感到有些自傲。

只要过著像人类的生活，当然会无法忍受非人道的对待。每个人都不应该乖乖地待在底层，梦想就是要既遥远又伟大。

「喂，其实你已经醒过来了吧，是不是啊？」

不知是否总算唠叨完，窃贼爬往安娜塔西亚的方向。从他恨之入骨的语调，很显然是要对安娜塔西亚痛下毒手。

原本奴隶贩子似乎不觉得他会蠢到这种程度，但安娜塔西亚却不是这么想，那名男子用手拉著塞进她嘴巴的布并粗鲁地扯了下来。

「……起来了啦，从刚才就吵死人了。」

「你、你你你根本就醒著嘛！你、你这家伙居然敢……」

「先说清楚，劝你现在最好别对我动手喔。你应该也很清楚我现在有多少价值吧？要是动手，你真的会被那个奴隶贩子处理掉喔。」

「唔……唔唔……」

听到处理这几个字，让窃贼收起至今为止的激愤。回想起被拳打脚踢的痛楚，让男子顿时哑口无言地抱著头。

「这里是什么地方？」

「────」

「什么嘛，没有半点有用的情报吗？」

「────」

不行，这样根本没完没了。

对毫无气力可言的男子说什么都没用，于是安娜塔西亚缓缓撑起身体。她一边转动因为躺在令人难以入睡的地面而导致僵硬的身体，一边勉强爬向小屋的门扉。

「没用的。」

无视于窃贼的消极发言，安娜塔西亚勉强靠著墙壁站起身，然后开始撬弄著看似门扉的把手，但丝毫没有开启的迹象。既然这样就只能摩擦地面将手腕的绳子松开，正当她如此思考的时候……

「偷偷摸摸……嗯～～感觉里面好像有人在？」

「──！？」

在开始挣扎前，从门扉另一侧传来这道声音。虽然声音听起来毫不遮掩又漫不经心，但光是如此就能判断与奴隶贩子毫无关系。

「有！就在里面，我抓到了！」

「喔～～有人耶！好厉害，就像黑塔洛说的一样！我知道了！」

如此说完后，门外的气息稍微远去。虽然安娜塔西亚对此种举动感到不解，但随即察觉到理由而连忙倒卧在门扉旁，随后……

「喝呀～～！咪咪咚锵！」

随著这道吆喝声，伴随著青白色光芒的身体冲撞由外将小屋门扉撞飞往内侧，绞链弹飞的木门发出剧烈声响在小屋内四处碰撞。

「好～～成功～～！咪咪好厉害！哼～～！哼～～！」

「────」

这个过于粗鲁的举动让人哑口无言，但无视于安娜塔西亚的这个感想，站在没有门扉入口处的人影似乎很开心地反覆小跳步。

那是个相当娇小的人影，身高只有在同年代中已经算是娇小的安娜塔西亚的一半左右。在月光照耀下的容貌甚至不是人类，模样与猫没有两样，说到能用双脚步行的猫脸种族，就只有猫人而已。

「喔～～被绑得好紧喔，稍微等我一下喔～～！」

猫人少女毫无恶意地笑著如此说完后，便将被绑著无法动弹安娜塔西亚解开束缚。只见她亮出锐利爪子，轻而易举地将四肢的束缚切断。

「呃……谢谢你？」

「嗯！道谢很重要喔，懂得道谢就是很懂事！咪咪也常提醒黑塔洛和堤比别忘记这件事喔！真是个乖孩子呢～～乖乖～～」

「别、别这样啦，好痒喔。话说回来，你是谁？」

橙色毛皮的猫女毫不客气地摸著安娜塔西亚的头，安娜塔西亚让她离开眼前并如此提问，她则是眨著大眼回答：

「呵呵～～问得好～～呃……咪咪是义谁喔！义谁！」

「义谁……？」

对于她双手叉腰得意地说出这个单字，安娜塔西亚完全没有听过。这是她的名字吗？不对，咪咪那个自称又是什么意思？

「姊姊，不是义谁是义贼啦。」

不过，安娜塔西亚的疑问却从别的方向获得解答。从少女所在的小屋入口传来较为成熟的声音，接著新露面的人果然还是个娇小猫人，即使考虑到种族差异，长相还是与少女如出一辙。

「不好意思让您搞糊涂了。我是黑塔洛，这位是咪咪姊姊，目前总之请跟著我们走吧。」

弟弟──黑塔洛低下头鞠了个躬，与咪咪呈现截然不同的理性态度。咪咪仍然是一副得意自满的模样在黑塔洛身旁挺著胸膛。

虽然两人并没有表明身份，但能够理解到并无恶意，既然如此……

「合辛语录『果敢决断是最强之剑』！好吧，我跟你们一起走。」

──女人要靠胆量，男人要靠殷勤。

虽然突如其来的闯入者和义贼宣言让人吓了一跳，不过安娜塔西亚选择相信他们。在短短人生中培养出来的看人眼光，判断两人并非坏人也占了很大因素。

「来，那个哥哥也一起走吧。」

不只是有意逃跑的安娜塔西亚，黑塔洛连窃贼都想一起带走，但窃贼却对咪咪等人投以怯懦眼神。

「别、别说傻话了！跟你们逃走……要是被发现会被杀掉的！我、我还不想死……绝对不能死……！」

「怎么会……」

「没用的，怎么说都他都不会听进去……只有决定走出自己人生的人，才有办法正面笔直前进。」

阻止执意将窃贼带走的黑塔洛后，安娜塔西亚前往小屋外头。即使如此黑塔洛还是犹豫到最后一刻，咪咪也同样拍了拍他的肩膀。

「嗯～～别太难过啦！不过这也是没办法的事，我们能救的就只有伸出手想获救的人喔～～」

出乎意料地，咪咪与安娜塔西亚做出同样判断，准备牵著迷惘的弟弟离开。在姊姊话语的催促下，黑塔洛总后总算放弃带走窃贼。

「这里是都市的哪里？」

「是边缘的垃圾山，那群奴隶贩子总是会用这个地方。」

「是我们查出这个地方喔！是伸张正义的时间了！」

垃圾山只是俗称，处分掩埋土砂与废弃材料的场所都是如此称呼。毕竟是人类不会长留或接近的地方，因此很适合作为奴隶贩子的躲藏处。

安娜塔西亚抬头望著月亮并轻轻吐出一口气，开始寻找回到城镇的路。

从这就算要到有人的贫民窟也有段距离，虽然安娜塔西亚对脚程颇有自信，但实在无法比拟咪咪等人。就算大声呼救，应该也只会惊动奴隶贩子。就这样静静地逃走，应该才是明智选择──

「这样不行喔，这样恶作剧偷偷跑出去是不对的喔！」

但可惜愿望落空，这道声音从正上方传来。

「──唔！」

安娜塔西亚随即停下脚步，眼前有个壮汉发出沉重声响著地，而对方的异常姿态让让安娜塔西亚屏起气息。

壮汉将兽皮披在头上，是个肩膀长出四只手腕的多腕族。

那名男子瞪大眼睛，声音就是先前在小屋听到的黏稠声音，也是先前站在奴隶贩子后方的另一名男子。

「都要成为奴隶了，这么有精神真是太好了，不过太有精神就不太好啰。稍微让脑袋冷静一下吧？」

「噫……」

当男子如此说著并将脸靠了过来，让安娜塔西亚差点发出尖叫声。

严格来说并非是男性，而是因为见到男子手中所拿的异物。

「啊，这个吗？吓到你了对不起喔，可是这家伙不是眼睁睁看著看著你们跑掉吗？居然放著同室的奴隶逃掉，这家伙真的是完全不懂规矩呢。」

男子一边笑著，一边将手中拿著的东西──也就是窃贼的头开始摇摇晃晃。窃贼带著惊恐神情被切下的头，似乎到死前都不知道自己会死的理由。

男子直接将窃贼仍然滴著血的头粗鲁地丢掉，然后用沾满血的手缓缓伸向安娜塔西亚──

「先发制人～～！！」

「喔唷？」

在安娜塔西亚被抓住之前，咪咪朝男子使出发光的踢击，男子用下方左腕轻松接下这击，再用上方左腕抓著咪咪的身体。

「唔唔！？咦，会不会太多手了？好厉害喔！」

「没错，就是很厉害。不好意思喔，有比较多手的那边就会比较强，这也是很正常的吧。」

「放开姊姊！」

相较于即使被抓住仍然一派轻松的咪咪，黑塔洛迅速地绕到男子背后。

然而，男子就像背后长了眼睛般，甚至连这个动作都是轻松躲过。无处可逃的黑塔洛也无法逃过男子的两只右手。

「好厉害！好厉害喔！」

「唔～～！抱歉，姊姊对不起……」

咪咪不停扭动挣扎，黑塔洛深刻地感觉到实力差距。男子用四只手将两人抓著，朝安娜塔西亚投以愉悦的眼神。

彷佛正在说著「现在没手说不定就能逃走喔」似地。

「会相信那种傻话的，只有刚才死掉的那种人而已吧。」

「是啊，有时候太聪明也是很残酷的喔。这次拿一个蠢货换到两个看起来很好用的猫人，算是很值得啰。」

男子露出黏腻的笑容，安娜塔西亚感觉到奴隶贩子从后方接近的气息，这次再被抓住肯定就会被当成商品。

因此在嘴巴被塞住前……

「只有一点你们要记住。」

「嗯嗯？」

「要是对我出手，可是会有很可怕的狼来找你们──我也不是那么好惹的。」

对于安娜塔西亚的宣战，男子则是发出「呵呵呵！」笑声并看似很高兴地颤抖著肩膀。

「好喔，这样太棒啰──那我就好好期待吧。」

男子不把这当成单纯的不服输，也表示接下这场对决。

──绝对不做在开始前就注定会输的对决。

即使被奴隶贩子粗鲁地抓著肩膀，嘴巴被塞住并被拖了回去，安娜塔西亚的眼眸中并没有失去斗志。

7

在「荒地合辛」的传说中，有段故事是无血开城。

据说合辛单枪匹马进入敌人的城塞中，只靠著三寸不烂之舌便让城主归顺，让坚固的城门开启迎接同伴进城。

至于进入城塞的方式有各种传闻。

有堂堂从正面敲著城门、有躲在运送的货物中潜入、也有装成尸体趁人不备。

但即使进城的方式众说纷纭，最后都是共通的结局。

──合辛兵不血刃便解放城池，拯救了小国卡拉拉基并开始缔造传说。

之后合辛以此为立足点，踏进了互相争霸的国家间争斗，接著创造出卡拉拉基城邦诞生的历史。

回想起此种轶闻，让安娜塔西亚感叹著传说的英雄果然是与众不同。

居然单身闯入敌阵，到底要有多少勇气与胜算才敢这么做？合辛并不擅长武艺，最有名的是除了口舌以外没有任何武器，这点与自己可说是一模一样。

不同处应该就是合辛不曾失手，让自己的脖子被套上奴隶用的项圈吧？

「────」

既冰冷又坚硬的项圈感触，让安娜塔西亚感叹著自己与英雄的器度差距。

虽然没有余力能够开玩笑说著「与里卡德一样」，但这个项圈让安娜塔西亚带来一定程度的安心感，因为这让她知道对方是个正派的奴隶商。

奴隶商也有分成正派与反派，项圈就是其中最大的差异。

从是否有奴隶用的项圈就能大略区分，这个项圈是被称为「流星」的其中一种，能够藉著项圈上的宝珠与持有者的门互相联系。因此只要持有者发出意念，便能给予奴隶痛苦作为惩罚，多数奴隶商人皆是以此管理维持奴隶。

要是没有项圈，奴隶商只能以暴力管教奴隶。由于这种方式无可避免会伤害到奴隶，因此越正当的奴隶商越会重视奴隶。

所以有没有项圈就是奴隶商是否具有良知的证据──至少不需要担心会被夺走性命。这就是安娜塔西亚浮现安心感的原因，也是让她能够持续思考的精神支柱。

「嗯～～嗯嗯～～！」

接著，支撑安娜塔西亚的精神支柱另外还有一个……不，应该说是两个。

那就是与安娜塔西亚被关在同个小屋、并被戴上项圈的两个小猫人。

「嗯嗯～～！嗯嗯嗯～～！」

彷佛体力无穷无尽般，咪咪已经连续挣扎几个小时试图挣脱拘束。黑塔洛则是静静地躺在身旁，但他也并非已经放弃希望。

「────」

沉默并不是悲观，而是因为努力思考著突破现况的方法。他与安娜塔西亚同样带著等待机会的眼神，其中没有任何妥协或放弃。

黑塔洛虎视眈眈，咪咪则是充满精神地不放弃任何希望。

既然如此，安娜塔西亚也有希望，就是那个既雄壮又全身毛的希望。

「得抢盼法告促大叔……」（得想办法告诉大叔……）

必须将自己身处的困境告诉里卡德才行。

这就是安娜塔西亚能够开启这个奴隶商城塞的方法。

「──喔？」

当三人就这样拚命寻找著脱逃的方法时，奴隶商再度出现在他们面前。

「刚才听迪德利说了，听说用那个蠢货就赚到了两个猫人啊。」

有个体格魁梧的壮汉打开门，环视著房间内部并冷冷哼了一声。

昨晚也曾经见过这名壮汉，应该就是奴隶商的头目。虽然昨天没有正面见到面，但今天能够一起见到发出锵锵声的装饰品与整套服装。

头目带著几名护卫，其中也包含了那名四只手的男子。他发现安娜塔西亚的视线后，便露出阴险的笑容挥了挥手。

头目带著三名护卫与一位狂战士，以检点商品而言可说是颇大阵仗。

「没什么，因为听说你们昨天晚上想偷偷溜走。俺是很怕出事的，多亏你才让这票干得还算不错哩……喂。」

头目仔细地替安娜塔西亚回答疑问，然后用下巴一指，护卫便将安娜塔西亚锁在墙壁上的锁链解开，这当然不是准备放了她。

「把货物重新装箱，在巴那的生意也该换个地方了。」

头目粗鲁地拉著安娜塔西亚的锁链，兜圈子地告诉她要被出货的事。她就这样被带出房间，即将被带上外面停靠的犬车载货台。

但就在途中……

「唔嘎嘎～～！」

「喔哇！等等！」

同样被带出小屋而胡乱挣扎的咪咪将护卫的手挥开，这只小猫一跳扑向头目。会锁定集团首领或许并非作战策略而是本能，但这个选择本身相当正确，头目顿时绷紧神情。

「我就说不能恶作剧啰。」

不过咪咪的反击在途中便受挫，四只手的壮汉介入两人之间，用两只手将咪咪揍了出去。少女的身体重重撞向地面，完全无法采取安全落地的姿势而弹起。

「呀啊！唔……」

「喂，迪德利！你打太过火了！这样要是受伤不就糟糕啦！」

见到咪咪趴在地面，头目拍了拍壮汉的背部。那位被称为迪德利的壮汉，对这番话耸了耸常人双倍宽的肩膀并向后退下。

「不好意思啦，小鬼头。可是不能再这样啰，我们也不想特地伤害商品。只要你们乖乖的就不会亏待你们啦。」

「喔～～我不会被骗的～～你这个坏蛋！」

当头目蹲低用恶心的细语声如此说著，咪咪也不灰心地回嘴，被殴打的冲击让塞著嘴巴的器具松脱，言论恢复自由的咪咪完全发挥出不服输的个性。

「做坏事会碰到悲惨下场！就算咪咪我们被抓住，黑塔洛和堤比还是会挡在你们面前的！」

「这丫头被揍还这么有精神……看来很值得调教一下。」

「什……喵嘎～～！」

话说到一半，咪咪突然竖起全身的毛发出尖叫声。这名少女瞪大双眼并发出悲鸣，原因是奴隶用的项圈，身为头目的男子命令项圈折磨咪咪。

「──唔！」

见到姊姊被折磨的模样，弟弟黑塔洛也彷佛承受著同样的痛苦般皱起眉头，接著咪咪瘫软地浑身无力后，头目便重新塞住她的嘴并站起身。

「居然会直接让她逃出来，你这个蠢货。要是再这样随随便便的，要不要也让你们戴上首饰玩玩看啊？这样漏光的气应该也会灌回来吧。」

「对、对不起，绝对不会再犯了！──唔！」

失手的护卫侧脸被甩了一巴掌，被殴打的男子将咪咪重新扶好，先前默默看著一连串发展的安娜塔西亚，自觉到被难以对付的家伙抓住了。

既有规律又有高度归属意识，也有很强的实力，是很棘手的对象。

「哎呀，想逃走也只会像刚才一样被修理得很不舒服而已。既然学到了……好啦，那我们出发吧，最好跟故乡好好道别哩。」

对于头目有些揶揄的话语，安娜塔西亚稍微环视四周，不论怎么环视都只能看到废弃材料。简直就是标准的垃圾山，完全没有浮现出任何感慨。

「看表情已经告别得差不多了吧，那咱们走吧……嗯？喂喂……」

头目推著俯视下方的安娜塔西亚背后，试图将她推上龙车，但安娜塔西亚被这么一推便失去平衡倒了下去。

「怎么，我没有拍那么大力吧。这样不行喔～～要坚强活著啊～～」

护卫将向前扑倒的安娜塔西亚拉了起来，被拉起身的安娜塔西亚摇了摇头，从他们的视野中将握著的手藏了起来。

正当她就这样带著若无其事的表情，准备迈步走向犬车时──

「……」

一股寒意让安娜塔西亚抬起头，迪德利瞪著大眼从正面低头瞪著起身的安娜塔西亚。

被他的眼瞳这么一瞪，安娜塔西亚的背脊窜过一道冰凉的感觉，被看见的战栗感让嵌著项圈的肌肤害怕得不停发麻。

会像咪咪一样被项圈惩罚──

「──呵呵呵呵。」

但这个预感被迪德利咧起嘴角的低沉笑声否定。

他并没有追究安娜塔西亚的行动，而是像其他护卫一样回到戒备四周的工作。虽然安娜塔西亚对此举感到哑口无言，但还是被推著背后一步步走向犬车载货台。

在犬车的载货台中分隔成几个区块，设计成无法由外侧见到内侧，那应该是区隔符合奴隶贩卖规定和违法奴隶的设计。当然安娜塔西亚他们是违反规定的奴隶，要是被发现肯定不会草草了事。

「────」

与小屋不同的是，犬车载货台上有窗户。由于设计的关系，载货区十分狭窄，只有安娜塔西亚等人的空间几乎可说是「装箱」的状态。

「你们要在里面乖乖待著啊，虐待儿童可是会让人心痛的。」

头目指著自己的脖子，摆出用项圈威胁的姿势后便将帆布盖在载货台。在奴隶商人的身影消失前，最后还能瞥见迪德利的笑容。

有种彷佛一切都被看穿的惊悚感，是个无法看透到底带著何种想法的男人。

「姊姊、姊姊……」

「唔喵～～」

在封闭的箱子中，黑塔洛担心著昏倒的咪咪。虽然咪咪还没有恢复意识，但没有性命危险，项圈的效力就是这么回事。不过比起这件事──

「你可一书话了……？」（你可以说话了……？）

塞著黑塔洛嘴巴的器具已经松脱，正当安娜塔西亚对此歪著头感到不解时，黑塔洛发现她的疑问而露出自己的锐利门牙，并且将牙齿磨出声音。

「我们的牙齿比人类还要坚固。姊姊也是，如果醒著请告诉我……呃……」

黑塔洛之所以会犹豫，或许是因为想像到咪咪嘴巴恢复自由时又会开始躁动，能够预见她大声嚷嚷后又被项圈电晕的模样。

不只是手脚被夺走自由，脖子上还有项圈。黑塔洛的课题应该也是想办法处理这些问题，但这些安娜塔西亚已经有各种突破的方法。

「首先……噗哈，我们得先来交换情报。」

「──要怎么做？」

见到安娜塔西亚将手绕过头并拿下塞口器具，黑塔洛相当惊讶，安娜塔西亚则是将仍然被枷锁铐著的手掌张开，上面有个在上犬车前跌倒而偷偷捡来的铁片。

「我觉得故意跌倒应该有被看到，那时候还吓出一身冷汗。不过……」

不知道迪德利刻意放过她的真正意图为何，不过他的临时起意倒是帮了不少忙。

虽然条件很严苛，但已经万事具备。不论是咪咪等人、自己、由载货台上能够见到的外头景色、奴隶商的头目与穿著、记忆中鲜明的都市周边地图、以及里卡德──

──只要能将所有条件串联起来，应该就能「解放城塞」。

「所以我想问你……你脸颊上的伤会不会痛？」

面对安娜塔西亚的问题，黑塔洛顿时绷紧神情。

此种反应让安娜塔西亚感觉到确切手感，于是露出既可爱又狡猾的微笑。

8

「里卡德，到处打听后才知道，那个迪德利好像是个很难缠的家伙。」

副队长回到帐篷后，对盯著地图的里卡德如此报告。里卡德坐在不符合巨大身躯的小椅子上，对这个报告带著烦躁表情咬牙切齿。

「只要看到那个『覆皮者』一眼，这种事不管是谁都会知道啦。」

「喂喂，『覆皮者』形容得还真夸张，不过听起来好像还不错。那家伙实际上会把杀掉的对手剥皮，听说很恶名昭彰。」

「我怎么只觉得那是单纯的变态而已啊……」

回想起那个四只手的变态，里卡德似乎很厌恶地皱起鼻头。

如果只是披著兽皮也就算了，那家伙是披著杀害亚人剥下的皮，而且那种搜集品不会只有一两件，应该会有搭配心情与天气换穿的无数收藏。

「出身好像是更北边的地方，不过因为名气当红，所以到这里来出差。现在是刚才那间……我记得好像是叫拉兹克鲁商会吧？现在是与那间商会缔结独占契约。」

「说什么名气当红，那家伙哪有那么可爱，不过没想到会有人那么清楚他的来历。」

「据说好像是在酒馆打过一架，只有单边耳朵被扯掉，算是运气还不错的。」

副队长耸了耸肩如此回答。里卡德也有同样感想，只是耳朵被扯掉算是很幸运了。

由迪德利身上散发出的血腥味，不是普通佣兵能够应付的程度，光是一只手就能扭断杀害人，既然有四只手也能明显看出差距。

「你的表情还真严肃，『猎犬』。就算那么杀气腾腾，与我们的工作也没有关系吧？」

「我知道啦。可恶，我稍微出去走走。」

里卡德仍然怀著焦躁情绪，留下副队长走出帐篷。他从扎营地抬头望著夜晚天空，用没事做的手指把弄著自己的项圈。

目前仍然无法掌握目标的盗贼团行踪，让他对自己衰退的嗅觉难掩落寞，而且满是疙瘩的心情被看不顺眼的家伙刺激就更不用说了。

剥下同族毛皮并披在头上的男人──迪德利，当他从正面称呼里卡德为「狼先生」的时候，只能感觉到一股挥之不去的恶意。不盲目相信将里卡德的自称，除了迪德利以外，将他称为狼的人就只有安娜塔西亚──

「怎么了，胡须在颤抖……嗯？」

里卡德摸了摸胡须，感觉到一股不安而抬起眉头。从稍远处的方向似乎传来争吵的声音，于是他迈步走了过去。

「我说啊，小鬼头。这里很危险，赶快回去城镇吧。」

「我就说有话要找负责人说了，希望能放我通行。」

粗鲁的语气与颇为聪慧的稚嫩声音互相重叠，仔细一看便能发现草原上看守的佣兵，与某个小小的猫人少年正在争执。

「你们在吵什么？一个大男人和小孩子计较真丢脸。」

「啊，里卡德队长……没有啦，这小鬼怎么说都不肯听话乖乖回去……」

见到里卡德介入，卫兵不停低下头频频道歉。里卡德哼了一声并看向少年，那是个表情看起来颇聪明的小猫人。

「小鬼头，我是这里的代表。怎么了？有话可以说来听听。」

「您就是负责人吗？」

衣衫褴褛的少年对里卡德的态度瞪大双眼，然后随即低下头行了个礼，并且当场跪下垂著头说道：

「有事想拜托您，请救救我的姊姊与哥哥。」

「你的哥哥与姊姊？这是怎么回事？」

「是奴隶商人。他们被奴隶商人抓住……希望您能救他们出来。」

「……喔，是这样啊。那还真可怜。」

面对少年的请求，里卡德感到有些怜悯地搔了搔头。

他的哥哥姊姊应该是猫人，不过年幼的猫人姊弟是奴隶商人的绝佳猎物。而从少年的破烂衣衫来看应该是贫民窟的「鬣狗」，捕捉他们的奴隶商人并没有违反巴那都市法，所以前来拜托里卡德算是找错人了。

如果不是在工作中或许还能帮忙，里卡德佛心地如此想著。然而……

「请看看这个。」

少年打断里卡德拒绝的话语，将自己身上的破烂衣服脱了下来。见到他那不堪入目的胸部到腹部，让里卡德微微发出低吟声。

──肌肤上有红黑色的淤血，而这些内出血形成了一幅图画。

仔细一看能够发现这张图是地图的形状，里卡德理解到那是直到刚才为止一直盯著的巴那周边地图。

「小鬼头，你这个伤……不对，这个地图是怎么回事？」

「有人正在伤害我姊姊或哥哥的身体，是因为加持……『三分加持』的力量会把我们三个人的伤势和疲劳分摊……这些伤就是这样来的。」

「用伤来画地图……还真是勇敢。原来如此，用这种方式表示自己的位置……等等。」

被奴隶商人抓住的姊弟，在身体刻上伤痕报告位置。虽然这种想法相当令人惊叹，即使如此仍不足以打动里卡德。但想到这里时，里卡德不禁皱起眉头──这个地图不只是如此而已。

「这张地图……」

都市巴那的周边地图，虽然这与里卡德拥有的地图一样，不过就是太过相似了。在少年身体上的地图，能够见到里卡德等人追捕的盗贼团袭击商队地点，甚至连预测的潜伏地点都做了记号。

若是没有看过里卡德持有的地图，是不可能画出这张地图的。而目前与里卡德地图的差异点，就是在巴那附近的扎营处──也就是目前佣兵团的所在地做了记号，以及沿著都市延伸而出的街道也刻有记号。

「从这里沿著街道，还有盗贼犯案的场所……把这些地方连起来……」

「里卡德先生？……咦？哇啊！」

凝视著少年身上的地图思考一段时间后，卫兵朝里卡德如此搭话。而里卡德一把抓住卫兵的肩膀咧嘴露出牙齿大声喊道：

「现在马上把带队的都叫到帐篷来！这些小鬼立下大战功啦！」

9

那位少年自称为堤比，在所有人面前露出刻在自己身体上的红黑色地图。里卡德支撑著站在桌上的少年肩膀，向佣兵们指著血构成的地图。

「所有人听好了没？这个小鬼头肚子的地图，是有人在他被抓的兄姊身上刻的。看起来好像很诡异，不过从这个地图上能看出一件事。」

「就是小鬼头兄姊被抓的奴隶商所在处吧？是很厉害啦，可是我们……」

副队长支支吾吾地表示与他们没有关系，但这也是所有人的共识。

对奴隶贩卖的好恶毫无关系，这个佣兵团的目的是讨伐盗贼团。即使同情堤比的境遇，但还是不能违背当初的目的，然而里卡德对佣兵们说著「不对」并摇了摇头。

「重点是这个地图有很多记号的地方，有商队被袭击的场所，也有我们扑空的盗贼据点。你们不觉得奇怪吗？」

「那的确是让人无法理解……不过那有什么意义吗？」

「听好啰，商队的袭击地点和我们扑空的潜伏场所附近是打叉，然后现在正在移动的奴隶商人是打圈……你们知道画这张地图的人要表达什么了吧？」

「──喂喂，里卡德。你的意思该不会是……」

理解到里卡德凶暴笑容代表的含意，副队长不禁瞪大双眼，佣兵团内似乎还有很多人没有找到答案，里卡德则是用能让所有人听见的声音说道：

「我们找的目标不是盗贼，是做盗贼勾当的奴隶商人……不对，是装成行商商队袭击其他商会的『强盗商会』。」

到处寻找潜伏的盗贼团会扑空也是理所当然的，因为根本没有盗贼团，而是装成旅行商人、袭击经过对象的武装集团。

将犬车与货物丝毫不剩地全部夺走，再将人员做为奴隶，将收获与奴隶直接卖到其他都市，在国家境内四处进行商业手段就是「强盗商会」的作风。

「然后那个『强盗商会』……离开巴那之后，这时候在街道的这附近四处乱晃，考虑到犬车运送行李的速度，只有一个候补。」

「──是拉兹克鲁商会吗！」

那团人数小时前才曾经通过扎营地造成话题，让副队长不禁发出咋舌声。虽然他焦急地认为这样会让对方逃走，但里卡德却摇了摇头。

「别那么慌张，我不是说过了吗？这张地图会持续告诉我们那些家伙前进的方向，不久之后那些家伙会为了露宿停下脚步。」

只要知道场所，接下来就是「猎犬」大显身手的时候了。

「把帐篷收起来！现在立刻朝拉兹克鲁……不对！是出发追赶『强盗商会』！」

副队长发出指挥，顿时打起精神的佣兵团同时四处散开。目送众人离开后，里卡德用力地拍了拍撑到最后完成任务的堤比的肩膀。

「小鬼头，亏你这么努力撑到最后，真是太伟大啰。」

「只要是为了姊姊和哥哥，这是……当然的……」

如此回答后，堤比浑身瘫软地倒了下来。他那随即获得搀扶的小小身体既滚烫且呼吸紊乱。这也是很理所当然的，毕竟这种伤势应该伴随著非比寻常的疼痛。既然是互相分担，实际上堤比兄姊所承受的痛楚或许也是难以言喻。

因此更得倾注全力才行。

「安娜，你的传言已经确实传过来啦。」

里卡德抱起堤比，叫出不在现场的少女名字。

能够正确地描绘出只瞥过一眼的地图，将盗贼团与奴隶商人连结起来，并且将对方的扎营处传达给「大叔」──就是那位立下丰硕战果的少女。

「得顺利把她找出来，然后好好问她为什么会被那种奴隶贩子抓住才行啊……！」

原先应该留在都市的少女为何会身陷此种危机？

里卡德完全没有料想到，就是先前自己放过那名男子所种下的因。

10

──「猎犬」率领的佣兵团，在深夜与拉兹克鲁「强盗商会」展开激烈冲突。

在沿著连结都市街道的某个无人废村中，从事正当买卖的商队会在途中在此落脚，是个经常被用来让大犬与商队扎营地用来休息的场所。

在这个从前曾为农村的扎营地，能够四处见到当时留下的废弃民宅。以扎营地而言，有屋顶的房舍可说是十分充满吸引力。

也因为如此，从事不法勾当的「强盗商会」轻松愉快地使用这个地方，让「猎犬」率领的佣兵团极为愤怒。

「────」

「猎犬」与佣兵团四十名恶煞，将夜幕低垂的废弃村落团团包围。

能够见到扎营地燃起看守的火光，以及酒气冲天的卑鄙谈话声，系著的犬车上刻有证明目标商会的商会章，因此绝对不会有错。

刻在堤比身上的地图相当完美，「猎犬」在作战前将那名少年留在帐篷中，脑中一边反刍著他恳求的话语，一边指示副队长将小队配置于村落各处。

取得确认后，副队长朝「猎犬」点了点头，「猎犬」便随著信号仰天长啸。

「吼喔喔喔喔喔～～！」

他发出了彷佛能传到无垠夜空的圆月般的野兽嘶吼。

下个瞬间，「猎犬」的四肢冲向自己该有的所在处──战斗也随之开始。

「唔喔喔喔～～！」

「吵死啦，蠢货！」

对于发狂冲过来的男子，里卡德用大砍刀给予一记致命回击。

厚重铁块砸在男子头上，头盖骨就像是水果般爆开。见到鲜血与脑浆四溢倒地的尸体，后续跟上的男性们皆哑口无言。

「噫……」

「别停下来啊，蠢蛋！」

被四处飞散的同伴尸体吓得停下脚步与思考，简直是三流以下的水准。

将其中一人的身体砍成两半后，再将另一名男子的头打断，接著用力将第三人的身体踢到墙壁上，朝喘息的男子头顶部用刀柄底部直接敲碎。

伪装成正常商会，在路上袭击其他商队反覆进行掠夺的「强盗商会」。当自己成为被掠夺的一方时，这个头衔顿时显得毫无用武之地。

「里卡德，你那边怎么样！」

当里卡德踹著尸体时，挥著沾血剑身的副队长赶了过来。当他一见到「猎犬」大闹一番后的惨状，便将手抵在额头上发出叹息。

「虽然我不担心，不过还是杀过头了。你是打算把全部人杀光吗？」

「对这种家伙要留什么情面？我甚至想把所有人的手脚全部砍断，再丢进煮滚的热油里面哩。」

「我能理解你的心情，不过也想想之后的事吧。还得对议会说明情况，把所有人杀光不是全员道歉就能了事的。」

「怎样，要我切腹道歉就道歉嘛！可是这也得等到把所有事都解决再说，要是没找到安娜和小鬼头的兄姊都免谈啦！」

面对担心都市议会想法的副队长，怒发冲冠的里卡德如此吼道。

是靠著安娜塔西亚的机智与堤比姊弟的协助，才能查出「强盗商会」的真实面貌，连那么幼小的孩子都那么勉强自己，因此有回报的义务。

对于里卡德的回答，副队长露出更加悲叹的表情仰头看著天空。

「啊～～可恶！就是这样我才不想和你一队，其他家伙也被你感化了，不知道还有多少人能留下来作证……」

「那我至少别打头吧，没死的留给你就可以了吧？比起这件事……」

「我知道，是『覆皮者』那家伙吧。」

「覆皮者」迪德利，那个多腕族肯定是这个「强盗商会」的主力。

偷袭与小把戏肯定没有用处，他已经不是能用这些方式处理的层级了。

「只有那家伙得由我处理才行，别让其他人对他出手。」

「这样只会增加无谓的牺牲而已，这件事差不多也该……」

若是发现迪德利的所在处，已经事先告诉佣兵们要用笛声通知；只要里卡德能将迪德利击杀，这场战斗便能以数量取胜。

因此里卡德竖起耳朵，等待著笛声传来。然而──

「喂～～～～！狼先生～～～～！快点出来吧～～！」

一道既黏腻且阴险的声音，不顾废弃村落的血腥气氛开朗地如此传来。

11

在「猎犬」的袭击下，拉兹克鲁商会瞬间受到毁灭性的打击。

喝得烂醉或倒头大睡的成员被佣兵轻松杀害，人员一口气被削减三分之一，但能够在此种先发制人下逃过劫数之人，才是「强盗商会」的核心成员。但对里卡德而言，或许该说那些人肯定也只是区区喽啰。

然而，这是以里卡德的身手为前提。

「混帐！这些家伙居然把咱们看得那么扁……！」

身旁的亲信反将佣兵击杀，拉兹克鲁则是在尸体前方气得咬牙切齿。

有五名佣兵闯入废弃村落看来最豪华的房舍，这里是拉兹克鲁的休息处，这五名佣兵已经被亲信的剑技砍倒化为尸体。但从村子传来的交战声与惨叫声判断，很显然并非是只有这五人失控随意攻击。

「不是脑袋烧坏的盗贼会干的事……是在街道的那群废物。」

巴那都市议会为了处理商队受害而组织佣兵团，这件事也已经传到拉兹克鲁耳中。这让他决定不在巴那继续犯案，打算甩掉持续进行无谓搜索的佣兵团前往别处，但不知道是什么地方被查出线索──

「头目，其他家伙该怎么办？」

「不是还有迪德利吗？就算咱们啥都不用做，他也会把那些不知好歹的家伙收拾掉，比起这个得先确认一件事。」

多腕族狂战士的名号让亲信顿时闭口不语，那个狂战士目前肯定是狂喜地在战场上奔驰，并且四处砍下脑袋吧。

比起这件事，现在得先查清楚这场骚动的原因。毕竟在一如往常的工作中出现了反常的变化，表示肯定有部分「不同于以往」的原因。

拉兹克鲁一边确认著嵌在手腕上的手环与奴隶项圈宝珠连结的感触，一边带著亲信前往「商品」的安置处。接著……

「那丫头是在这个箱子吧。」

他来到目标的箱子前方后，便命令亲信将门打开。当门一打开，一股血腥臭味迎面而来，让拉兹克鲁不知发生何事而皱起眉头。

「唔──」

在箱子深处传来某个人倒吞一口气的气息，拉兹克鲁走进里面并在昏暗处定睛一看，然后对合乎想像的景象收起下颚。

「原来如此，是这些小鬼有某种加持吧……干得还不错嘛。」

猫人少女的腹部沾满鲜血，猫人少年也受到几乎同等的伤势，拉兹克鲁对试图保护两人的少女坦率地感到佩服。

这种容貌搭配器量，在至今曾经经手的「商品」中可说是特别突出的高级品。

「手脚被绑住亏你还能做这些事，这些伤……是从废物堆捡了玻璃过来吗？」

「看你好像还很有余力，可怕的野狼不是已经过来接我了吗？」

「应该正在和我养的疯狗对打吧……话说回来，这次损失可是赔大了哩。」

面对逞强的少女，拉兹克鲁露出左手的手环。只要想像就能让戴著项圈的奴隶受到剧烈疼痛，这已经拿猫人少女实践过了。

想像到那种疼痛，就连少女都不禁绷紧神情。见到她的模样，拉兹克鲁则是从怀中掏出一把变形短剑，那是拉兹克鲁爱用的拷问器具之一。

当然他并不打算伤害少女降低商品价值，这把短剑是打算对身后的猫人使用。

「听好啰，小姐。你干的好事不一定要由本人承担责任，这次的事就让你好好学学吧。」

拉兹克鲁用下巴一指，亲信便伸出手将少女压制住，然后直接打算在少女面前随意虐待猫人让她好好反省。只要迪德利把周遭的佣兵清扫干净，这场骚动也就告了一个段落。

「干下这些事的责任啊……」

「嗯？」

拉兹克鲁已经将意识转到收拾后续，当少女细微的声音传到耳中而回过头，便见到少女正紧紧瞪著他。

她那浅蓝色的眼眸彷佛有将人吸进去的力量──

「既然这样……你自己做的事就自己负责吧！」

少女以强烈语调如此说道。

瞬间，眼前的猫人突然有精神地跳了起来并咧嘴一笑。

「这个世上不容许邪恶蔓延！」

猫人如此喊著，脚底则是直接强劲地打在拉兹克鲁脸上。

12

──在这一秒钟内，箱子中的状况产生了巨大变化。

「────」

安娜塔西亚的叫声让咪咪突然跳了起来，以浑身是血的凄惨模样一脚踢飞拉兹克鲁，在这个剎那间拉兹克鲁应该已经用手环惩罚咪咪了。

透过门释放出惩罚的意念，让咪咪的小小身体抖了一下，但这道力量并不足以阻止咪咪维护正义，毕竟「惩罚」是由黑塔洛一手接下。

咪咪三姊弟的「三分加持」是能让疼痛之类的感觉互相分配。虽然比率平常是均等分配，不过也能刻意倾向某一方。像是描绘地图的时候，或是姊姊受到「惩罚」的时候，能够将所有痛苦由其中一人全部承担。

「因为我没有像姊姊那么强……所以只能这么做了。」

黑塔洛如此说著，他接受安娜塔西亚将地图刻在身上的提议时，正气凛然的神情可说是相当耀眼。就连现在受到出血与疼痛折磨，他还是接下姊姊所受的「惩罚」彻底保护姊姊。

「喔～～！嘿呀～～！」

感受到弟弟的心意，四处活蹦乱跳的咪咪拥有比想像中更强大的战斗力。

趁著亲信对拉兹克鲁倒地而不知所措的瞬间，咪咪用短脚将两名亲信其中一方踢飞，将对方重重撞在墙壁上予以击溃。

毕竟是拉兹克鲁直接带在身旁的护卫，实力绝对不算弱，但小猫人的激昂情绪也让战斗力随著大幅提升。

「喝！」

见到同伴被击倒，另一名亲信回过神拔出腰间的刀剑。被称为武士刀的单边刀刃剑光一闪，施展出令人畏惧的锐利斩击，然而咪咪俐落地钻过这道攻击……

「哎呀呀～～！」

她用尾巴将对方打得向后仰倒，再朝腹部使出一记强烈的头槌，接著用短短手脚朝踉踉跄跄的敌人喉头一阵猛打，最后再把对方摔晕倒在地上。

「看到了没～～！咪咪完全胜利～～！」

将亲信与拉兹克鲁一同击倒，让咪咪当场得意地发出胜利宣言。

亲眼见到她的活跃表现，安娜塔西亚顿时瞪大双眼。原本只打算争取时间，没想到她居然能将对方全部击倒。

「总之这样就解决啦！」

即使对出乎意料的战果感到惊讶，安娜塔西亚还是从倒地的拉兹克鲁身上将手环抢了过来。

就算要逃离这个地方，有手脚枷锁的情况下还是很难成功。与其逃离不如先确保现场的安全，再等待可怕的野狼赶来才是最佳解答。

「喔～～项圈拿下来了！黑塔洛的也拿下来了！」

「很好！果然就像我想的一样，能用这个把项圈拆下来。再来就是……」

手环就是钥匙，安娜塔西亚将三人脖子上的项圈拆了下来，然后再将项圈分别铐在拉兹克鲁与两名亲信身上。

「可恶……做这种事别以为我会轻易放过你们……噫呀！」

恢复意识发现自己被套上项圈，拉兹克鲁以低沉语调如此威胁。不过安娜塔西亚用手环给予「惩罚」夺走他的意识。由于很难控制，不只是拉兹克鲁，连倒在地上的亲信也被连带受到惩罚，总之这样就确保现场安全了。

「再来就要靠大叔了……别辜负我的期待喔……」

在咪咪替黑塔洛开始治疗伤势时，安娜塔西亚摸著手环如此静静呢喃，持续祈祷著下一个打开箱子的人会是熟悉面孔。

「呀啊啊！」

「啊，糟糕了。」

一不小心误启手环，被惩罚的拉兹克鲁惨叫声顿时传遍整个箱子。

13

被强烈的自我呼喊吸引过去后，只见眼前一片血海。

「啊哈，狼先生你来啦。」

狂战士兴奋地发出喘息声朝里卡德投以目光，脚下四散著大量尸体，模样甚至残酷到没有保留原形。

不过就连无法判断生前模样的尸体堆，也能清楚地看出一件事。

「那边、那边还有那个都不是我们的人，是你们那边的同伴吧？」

「咦，是这样吗？因为在眼前晃来晃去很烦，所以就直接干掉他们啰。这种事不是很常见吗？」

「一点都不常见，别把我跟你混为一谈，蠢货。」

「覆皮者」迪德利故意装傻回答并举起沾满鲜血的板斧，他用四只手的其中一只手调整披著毛皮位置，并且朝里卡德瞪圆眼睛。

「果然是这样呢，那丫头说的狼就是你。」

「……让安娜随便胡搞的人就是你吧。与其说是疯狂，看来只是个单纯的蠢货。结果被逼到接近全灭，要这么拚命引人笑也该有个限度哩。」

「是吗？对我来说，只要能跟狼先生好好玩一场就好啰。」

原来如此，完全是符合狂战士的理由。

不考虑人格只看能力雇用迪德利，是负责人的误判──由于很少见到出现如此彻底的破绽，要让人同情或许还比较困难。

「里卡德……」

被同行的副队长这么一叫，里卡德用大砍刀指著别的战场说道：

「这家伙我会负责压制住，其他家伙应该不会输吧。」

「对面应该也能说同样的话吧。」

「少啰嗦，赶快滚去别的地方，然后祈祷我会获胜。」

粗鲁地将担心的副队长赶走后，里卡德单独面对迪德利。见到迪德利静静等待副队长离开，里卡德颇为意外地挑起眉头。

「怎么，比想像中还乖嘛。我还以为是条疯狗，没想到调教得还满好的。」

「在大餐面前这么没礼貌，让难得的滋味变差不是很浪费吗？依我迪德利的个性，就是要把食物留在最美味的状态品尝喔。」

「是喔，我是不会把赌命对决当成好不好吃的基准啦……你应该没有对安娜做什么蠢事吧？」

「有做会让你比较生气吗？」

「有就把你塞进煮滚油锅里啦，蠢货。」

双方耍嘴皮子成为开战的导火线，里卡德一个箭步冲进迪德利的怀中，迪德利以四把板斧迎击，分别以不同轨道砸向巨大身躯。

里卡德压低姿势先躲过板斧缠著风的一击，再用大砍刀弹开后续的两把板斧，在最后一击抵达前使出一记前踢将「覆皮者」踢了出去。

「吼啊啊啊！」

随著吼叫声，大砍刀的一击挥向后仰的迪德利头部。

这道甚至能将巨大岩石劈成两半的钢铁一击，迪德利用举到头上的两把板斧挡下。钢铁互相咬合爆出火花，正当两人就这样较劲力气时，多腕族的另外两只手施展出攻击，里卡德随即用胸甲将左右逼近的板斧架开。

胸骨传来痛楚，冲击甚至传到内部的内脏。里卡德吐出涌上的血块，利用迪德利挤压的力道向后大大一跳并开始咳嗽。

「咳～～呸呸！混帐，还厉害的嘛！」

「狼先生才是让人佩服呢，那差不多该认真打啰。」

见到里卡德口吐血痰与怒骂，迪德利以黏腻的满面笑容如此回答。随后，巨大身躯逐渐模糊从视野中消失，四只手的异形就这样消失在夜色中。

「那么大的身体还可以做到这种事啊！」

迪德利出乎意料的隐形，里卡德以粗鲁语气如此说著并凝神盯著黑暗处。

没想到那么强调自我的模样，能够如此完美地溶入黑暗中。视野内已经没有狂战士的身影，浓密的血腥味也不让嗅觉掌握到足迹。

如果他是为了这个特地将现场化为一片血海，战术思维可说是出人意料地细腻。

「唔──」

里卡德瞬间配合破风声挥起大砍刀，清脆声响与弹回趁势而来的三道冲击触感传回手中，要有里卡德的技术才能一次将三把巨大板斧挡住。

但四发攻击之中能有其一命中，也代表著迪德利的战术技高一筹。

「唔呃……」

板斧的一击刺进左肩，将类似硬针的体毛与结实肌肉切开，喷出的鲜血让里卡德喉咙深处爆发出疼痛与怒气。

「唔哈～～！只靠一把板斧没办法把你砍死呢！」

狂战士愉快地如此喊叫，并且以令人吃惊的轻快动作向后方一个空翻回到夜色中，甚至无法听见踩踏草地的声音，此种潜进夜色的功力连野兽都自叹不如。

这种模样简直像是一场恶梦。

将杀害对象的皮披在身上，以四只手带来死亡的恶梦化身，可说是令人留下深刻印象。

「怎么样？怎么样怎么样？有没有好好享受我的舞蹈啊？」

踩踏地面的短促脚步声，与黏腻声音传来的方向并没有一致。

声音与脚步声各自独立的奇特步法、用隐形对付视线、声音扰乱听觉、以血腥味干扰嗅觉，里卡德没有任何手段能够追踪那潜伏于黑暗中的巨大身躯。

远离、接近、环绕、跳跃、左右、上下，自由自在接连施展出的板斧杀招，让里卡德受到的伤势逐渐加重。

即使靠著一击瞬间释放出的杀气，极限也只能弹开三道攻击，被剩余一道攻击削过身体并被砍下头颅也只是时间问题。

「混帐！够了，我要杀掉你把这场舞打断！」

发出这道不像是身处困境的怒吼声，里卡德扛起砍刀大大向后一跳。「猎犬」就这样背对著废弃房舍，直直地盯著正面并架起武器。

只要背对墙壁，就能将对方进攻的方向限定在正面与侧面。面对迪德利无法猜透「什么时候」或是「从何处」进攻，这样至少可以封锁进攻的方向。

面对里卡德此种战术判断，狂战士愉快地发出喊叫声。

「呵呵呵呵呵！对啊！就是要这样！可是啊！」

「──唔！」

下个瞬间，迪德利的身影出现在里卡德正面，然而位置是在双方攻击距离的远处──迪德利的目标并非是肉搏战。

丢出的板斧描绘出拋物线，成为死亡圆盘逼近里卡德。

对于无法掌握隐形而选择苦肉计的敌人，板斧投掷就是必杀的杀招──若是要对付四个方向而来的同时攻击，真的得要有四只手才有办法应付。

「杀掉你之后，我会再让那个女生看看你的毛皮。不知道她会出现什么样的表情呢？」

「────」

迪德利带著阴险笑容，说著杀死里卡德后的恶心展望。他的模样与说话内容让里卡德理智断线并张开口。

──为了制服敌方的杀招，里卡德也同样使出杀手锏。

「喝啊～～～～！！」

里卡德张开咧牙大口，朝著正面放出毁灭的咆哮声。

空气为之撼动，地面受到声音震动而掀起。逼近的板斧被冲击波吞没弹飞，音波直接击中迪德利并将巨大身躯染上鲜血。

「咦……啊？」

这道超乎预期的一击，让迪德利满脸是血地歪著头。

「喔啊啊啊啊！！」

里卡德一气呵成地冲了过去，毫不留情地挥下扛在肩上的砍刀。

这一击刺在狂战士的粗厚颈项上，将披著的毛皮连同迪德利的巨大身躯豪爽地击飞，然后绽放出血花。

「喔啊──」

肉与骨头被砸烂的声音互相重叠，被击飞的狂战士坠落到地面。

「真不愧是……真是太让人陶醉啰……」

迪德利折断的头露出笑容如此喃喃说著，最后便随著嘻笑的气息回归沉静。

──这就是在都市巴那蔓延的邪恶「强盗商会」的最后下场。

14

事变的隔天，在忠甸商会的商会长室中见到了里卡德等人的身影。

坐在沙发上啜饮著绿茶的里卡德报告完工作后，便松了一口气。

「就是这样，已经把做坏事的家伙全部解决掉啦。安娜也已经找回来了，我们这边的损失……没什么大不了的。」

「好像是这样，听说好像有很多意外同时发生……」

听完来龙去脉后，坐在里卡德对面的忠甸深深地点了点头。听到他似乎难以启齿的回答，里卡德便说著「怎么」并皱起鼻头。

「话说得不清不楚。怎样？是对我有意见吗……」

「当然有意见！都是因为大叔，你知道害我吃了多少苦头吗？减薪啦，减薪！忠甸先生要严格一点！」

「唔嗯……安娜，我不是道过歉了吗……」

面对在身旁大声嚷嚷的安娜塔西亚，里卡德露出尴尬的神情。忠甸也是傻眼地耸了耸肩，看来这次他已经老实反省过了。

多亏安娜塔西亚的机智，才能顺利歼灭「强盗商会」。

但以这件事为首，里卡德听完安娜塔西亚被奴隶商人抓走的过程后，目前完全没有办法在她眼前抬起头。

没想到当初佛心大开会招致那种后果，这次安娜塔西亚的困境都是里卡德种下的因。

「话是这么说，不过都是多亏安娜才能击溃拉兹克鲁商会……」

「反省！」

「是，真的很抱歉！会尽量不再犯同样的错……」

见到安娜塔西亚气冲冲的模样，里卡德垂下耳朵出声赔罪，两人的对答让忠甸忍不住噗哧一笑。

「你们还真是……不不，我知道了。这次当成是安娜塔西亚的大功一件吧。关于里卡德先生，就是功劳与失败互相抵销吧。」

「忠甸先生真是太宽松了，这样大叔可是会得意忘形喔。」

「那部分就请安娜塔西亚帮忙严格管教吧。」

「呃……嗯，好吧。我会好好管教大叔的！」

表情像是从忠甸身上获得免责权般，安娜塔西亚朝里卡德瞥了一眼。

虽然她的眼神让人担心接下来的发展，但同时也是「解放城塞」时的眼神，里卡德认为自己果然没有看走眼而感到相当自豪。

「不过话说回来，安娜塔西亚，亏你能把奴隶商和野盗联想在一起。你是在哪里发现这件事的，是有人不小心说漏嘴吗？」

「呃……没什么啦，那些人不是有个头头吗？我曾经看过他身上戴著那些发出锵锵声的发光装饰品。」

「曾经看过装饰品？」

「我在打杂的时候曾经看过，然后那个经商的客人说曾经被大叔提到的盗贼袭击。既然这样……我就在想大叔找不到盗贼团的原因应该就是这个，因为野外盗贼想把赃物卖掉应该很困难，这样不是很奇怪吗？」

「────」

面对安娜塔西亚似乎认为自己很幸运的说词，忠甸不禁吞了一口凉气。

里卡德也在身旁对此种跳跃性思考哑口无言，而且最恐怖的是这种思考不只是找出了正确答案，而且还想到方法将答案传达给里卡德。

「一起被抓的咪咪他们……啊，就是那几个猫人姊弟。我看到姊姊被打的时候，发现不知道为什么连弟弟的脸颊都一起红肿，所以我想他们应该有加持之类互相联系，结果他们就说还有另一个弟弟在外面了。」

「……是为了让另一个人的身体浮现出地图，才会把一起行动的猫人用受伤的方式画成地图吗？」

「幸好我有稍微瞄到地图，这样才能好好画出地图。」

只是瞥过一眼的地图，能够如此精准地描绘出地图，对安娜塔西亚并非是难事。从运送的犬车窗户看向天空，再从太阳的位置与高度，还有车轮的旋转次数测量移动距离与位置，甚至还能补足伤痕地图上的情报。

当锁定夜晚扎营地为潜伏场所时，去除掉迪德利这个不确定因素，几乎已经能够确定是佣兵团获胜，而一切的最大功臣就是安娜塔西亚。

「不过啊，亏你在被关的犬车里面能做这种事……」

「就算是在载货车里面，受阳光照射的墙壁也会变热，而且从中午的钟声响过之后，我就一直在算时间。只要这样不就能清楚知道地图位置了吗？」

「喔、喔喔……是这样啊……」

里卡德心虚地点了点头，的确如果单看这些事或许不是什么大事。

但能用秒数计算时间、用太阳位置与阳光角度确认方位、拟定逃脱计划、将记忆中的地图鲜明地刻在人体上等等，照常理而言是不可能同时进行，她竟然只靠自己一个人全部处理。

「真是的……你真的比想像中还令人惊艳呢。」

「──？」

安娜塔西亚天真无邪地歪著头，忠甸则是相当满意。当初看上这位少女的才能，从酒馆招牌服务生引进商会的人就是他。对于此种投资能够回本的工作效率，以及确信自己看人目光没有出差错，会为之一笑也是很理所当然的反应。

然而，里卡德也担心著忠甸的期待是否会很危险。

因此他发出比平常更响亮的声音，粗鲁地搓了搓安娜塔西亚的头。

「唉，的确是比想像中还夸张啦。没想到安娜会在我过去拯救之前，就把对方的头头打扁，还把他当成奴隶，真是吓坏我啦！」

「那、那又不能怪我！因为我觉得外面很危险，至少得确保里面的安全……而且奴隶商人有那种下场只是自作自受……唉唷！头发被弄乱了啦！」

当里卡德前去迎接时，安娜塔西亚将奴隶用的项圈嵌在敌方头目身上，漂亮地将被虐待过的事反将一军，没有任何复仇比奴隶商人被嵌上奴隶项圈还要更有趣了。

「之前约好要把我的项圈交给你处理，看来好像还是太心急哩。」

「别说傻话了，就算是口头上的约定也要誓死遵守。大叔真是的，怎么会说这种话呢！」

安娜塔西亚面红耳赤地如此怒骂，里卡德则是咧牙一笑。

虽然刚才省略报告，不过当安娜塔西亚见到里卡德前来迎接时，嚎啕大哭地扑过来一事，还是保密比较好。

对于两人说话的模样，忠甸早已是哑口无言。既然话题焦点已经脱离安娜塔西亚的功劳，差不多也该是让话题告一段落的时候了。

「话说回来，那三个帮忙抓人的猫人三姊弟……到哪里去了？」

最后忠甸提到在话题中出现却不见踪影的功臣，里卡德与安娜塔西亚皆对此露出尴尬的神情。

「这我也不是很清楚哩。我是确定最大的那个大姊，用治愈魔法把两个弟弟的伤势治好了啦……」

「然后说什么『正义是不求回报的啦～～！』就不知道跑到哪去了……」

「……那是怎么回事？」

忠甸提出的疑问，同时也是里卡德与安娜塔西亚所怀著的疑问。

三姊弟对「强盗商会」做出莫大贡献，没有要求任何谢礼或是道谢，姊姊便抱著两位弟弟豪爽地消失在晨曦中……不，由于是一起回到城镇入口，应该还在巴那的某个地方。

「正义的一方……那些小鬼真的知道这句话的意思吗？」

「他们一定很清楚啦，毕竟人家也是被正义和勇气所救的……而且我觉得一定会在某个地方再见面。」

毕竟是那么吵吵闹闹的三姊弟，只要寻找应该就能轻易找到，不过安娜塔西亚想说的应该不是这个意思。

里卡德将手挽在胸前，对微微露出开朗微笑的安娜塔西亚只回答「是啊。」

看完这个反应后，安娜塔西亚直直伸了个懒腰，接著……

「那么，昨天也多赚了一天休假，我要回去工作啰。」

「等、等等啊！才过没几天哪有那种精神……」

「人家只是躺著而已嘛。大叔如果也是商会的保镳，就得好好认真工作！别再像这次一样发呆犯蠢啰！」

里卡德手腕的毛被小小少女一拉，然后被屁股一顶地赶出房间。

报告完之后，他原本想好好喝顿酒并睡个懒觉。这个小小愿望似乎完全无法传到充满精神的少女耳中。

「这次的大失败应该也让大叔的价格降低不少吧？这样离我买下大叔的日子也不远啰！」

少女带著灿烂笑容，毫不掩饰地说出购买人口的梦想。

少女的笑容让里卡德顿时浑身无力，只能毫无威严地发出叹息声。

由于这并不会让他感到反感，因此被说成冲昏头也是理所当然的。

里卡德怀著此种感慨搔了搔头，便跟在安娜塔西亚后方迈步离开。

** 『阳光，照耀水面』

1

某个午后，那是由突如其来的一句话开始的。

「──阿尔，妾身感到很无趣，来做点有趣的事吧。」

「喂喂，我说公主啊。那可是连暴君都会吓一跳的开场白，没有一点轻重缓急连我都跟不上这种节奏啦。你刚才说什么？」

「妾身很无聊，快找些有趣的事，不然就把你的头砍下来。」

「咦！？这样根本不用怀疑是不是暴君吧？」

以低沉的声音如此喊道后，男子便举起双手仰头望著天空。

如此背靠观景台铁栅栏并仰望壮阔蓝天，能够见到云以颇快速度随风流动，正当他呆滞地想著「明天天气也许会变差」的下个瞬间──仰起的下颚突然被重重一推。

「喔！哇！呀啊～～！」

毫无支撑的身体以铁栅栏为支点转了半圈，身体差点被甩了出去。右手突然抓到某个东西，于是拚命地攀附著此种既柔软又滑嫩的感触。

「好、好危险！我刚才完全是在生死关头徘徊吧……」

「很可惜，现在你的危机还没解除……不，应该说现在才危险喔。」

「咦？」

男子俯视著观景台正下方的庭院并松了一口气时，这句话让他发出脱线回应并将视线拉回上方。在隔著铁栅栏的另一侧有只白皙手腕突然将他抓住──能够见到那只手的主人正露出残暴的微笑。

橙色头发配上大胆露出美艳肌肤，那是个身穿红色礼服的少女。她轻轻地用被抓著的左腕支撑男子，然后朝男子伸出如同白身鱼般的手指。

「公、公主！？公主，拜托再多点慈悲胸怀！」

「即使只有几秒钟，不过能摸到妾身如玉般的肌肤，你就感到光荣安心下去吧。」

「呀啊～～！」

随著这道无情宣言，少女将右手手指弹出。虽然这个动作只是俗称的弹额头，但速度与威力却是超乎常理，身体便随著高亢声响被冲击力道弹了出去。

身体飞向正后方，就这样被飘浮感笼罩上下颠倒──然后一头栽进水中沉了下去。

「刚、刚刚刚才！～阿尔先生好像掉到池子里去了！」

「喔，舒尔特你来得正好。妾身正好想喝红茶，快点去准备吧。这可是你的工作，别让妾身等太久。」

「遵、遵命！这是当然的，不过阿尔先生也是很令人担心！」

男子咕嘟咕嘟地吐著泡泡，沉进还算颇深的水底。远处能够听见少年听似困扰的声音，以及少女将此做为佳肴高声笑著的笑声。

──我在做什么啊。

阿尔一边如此想著，一边踩著水底用力浮上水面。

2

这里是亲龙王国露格尼卡西南部，由莱夫•跋利耶尔男爵统治的跋利耶尔男爵领地。

身为领主的莱夫，是个施加暴政而被领民厌恶至极的人物。不只是将重税与过度劳动视为义务，跋利耶尔领地有段时期甚至被称为王国的流放地。

然而，跋利耶尔领地的恶评在这几个月消声匿迹，甚至据称是近年来领民与领主关系最为良好的时期。

这都是因为莱夫娶了一个年轻聪慧的美丽女性为妻，才会改变本性全心全力为领民付出──不论领地的哪个人都知道当然不可能是这样。

并非是领主的本性出现变化，而是领主整个人。也就是说，先前负责掌管领地的莱夫病倒后，是多亏了他妻子负责代管的本领才有此种结果。

代替卧病在床的莱夫，领地的命运落在这位美丽女领主手中。她的治理手腕可说是有如天神下凡，领民的心皆被她夺走。

一反只会压榨的前任领主，这位女领主采取亲近领民的治世方针。那稀世的高贵美貌，再加上频频视察领地的平易近人态度，让跋利耶尔领地的居民皆拜倒在她的石榴裙之下。

「太阳公主」就是领民们对这位慈悲胸怀女性的高度评价。

「……要是知道太阳公主会把随从踢到池里差点溺死，不知道那些领民会怎么想喔。」

「别说那种很难听的话。或许该说死无对证……像你这种几乎算是可疑分子的混混，和美丽的妾身相比，你觉得领民会相信哪边？」

「刚才那段话真是糟糕透顶，这点我可以肯定！」

阿尔盘腿坐在宅邸庭园的池子旁，竖起拇指斩钉截铁地如此说道。

不只是衣服摔进池子湿透，连内裤都是湿答答的。阿尔一边将脱下的草鞋晒著太阳，一边上半身打赤膊努力地扭干上衣。

他用下巴夹著布料并用右手用力扭转，因为阿尔并没有该有的左手，所以这种姿势很辛苦也是理所当然的。

「阿尔先生，我来帮忙扭干吧。请包在我身上！」

看不下去阿尔辛苦的模样，仍然年幼的少年如此出声说道。约十岁的稚嫩可爱长相配上小小管家服，努力想装成熟的模样实在令人莞尔。

然而，此种令人莞尔的模样也是──

「别去帮他，舒尔特。洗衣服的工作让你手指变粗就不好了，要是抱起来不舒服，妾身会马上把你踢出陪睡的行列。」

「哇、哇哇哇！普莉希拉大人，这样突然抱著我会吓一跳……！」

被从后面这么一抱，那位少年──舒尔特面红耳赤地显得畏畏缩缩。奇特的是，见到这种害臊的搂抱姿势，先前令人莞尔的印象顿时一变，反而有种莫名的悖德气氛。

「阿尔，怎么用那种蠢样傻傻看著妾身？」

橙色少女如此说著，仍然搂著舒尔特露出大胆微笑。

模样简直就像是太阳──让见到的人几乎会灼烧双眼，她就是拥有如此美貌的人物。随阳光闪耀的橙色发丝、熊熊燃烧的热焰眼眸、蛊惑人心的魔鬼般魅力、以及毫不掩饰地展露而出的嫣然肢体，不论男女见到心灵都会被随即掳获。

这位少女拥有此种连红艳礼服都无法比拟的强烈印象，她就是代替丈夫掌管领地的太阳公主普莉希拉•跋利耶尔。

面对普莉希拉彷佛毒蛇般的眼神，阿尔宛如掩饰叹息般摇了摇头。

「呃……没有啦，我只是重新确认御姊配正太还是很不错而已，感谢两位招待。」

「又说那些让人听不懂的话，那也是你老家的大瀑布语吗？」

「对啊，还有头盔到处都是水实在很难看到前面，大概就是这样吧。」

阿尔随便找个藉口，用手朝著头敲出锵锵声。声音是源自于头盔的接缝处，也是平常总是戴在头上的黑色铁盔。

见到阿尔的此种动作，仍然被普莉希拉抱著的舒尔特瞪大双眼。

「头盔！阿尔先生的头盔这样会生锈的，要是没有头盔，阿尔先生会变成无头人！这样很恐怖，要立刻晾干才行！」

「舒尔特，你的误会是还满可爱的。不过我不是从脖子以上都是铁制品，所以不会变成无头人喔，还有就是这个头盔不用担心生锈。」

「咦，不会生锈吗？而且还有头……有点可惜。」

「我实在不能理解舒尔特觉得可惜的点在哪啊。」

对莫名感到寂寞的舒尔特回以苦笑后，阿尔便拍了拍头盔轻轻将水拍出。

「这个头盔是特制的，而且还是有点历史渊源的东西喔。」

「喔？那还真是第一次听到，那是在哪偷来的？」

「为什么一开始就当成是用偷的啦！多相信我一点嘛！」

「靠你那点出息怎么可能买到那种高级货，是从哪里偷来的？」

「是以前待的剑奴斗技场啦！不过不是用偷的喔！是从那里逃出来的时候，有个好心老兄送给我的。好像是在斗技场装饰的头盔，我想应该是还不错的东西啦。」

当说出剑奴这个单字时，舒尔特的侧脸瞬间闪过难受神色。但即使听到同样单字，普莉希拉仍然面不改色的态度让阿尔有些欣慰。

「记得你原本是佛拉基亚的剑奴，既然这样，你的出身地应该就是剑奴孤岛基奴海布一带，那个头盔应该是从前剑奴王相传的复制品吧。」

「对博学多闻的人实在没办法隐瞒事情耶！对啦，我就是一直被迫在剑奴孤岛工作，左手也是在那边断掉的，这个头盔就是当成退休金啦。」

来历被接连爆料，让阿尔半闹别扭地如此挖苦。总之先不论出处，仍然无法改变这是个特制头盔的事实，因此没有必要拿下晾干。

「所以就算你带著充满兴趣的表情也是没用的喔，舒尔特小弟弟。」

「啊……那个，我没有特别在意！男人是不需要靠脸的！」

「这一点都不算帮腔啦！还会让人受到不必要的创伤！」

发现自己说的话根本不算安慰，让舒尔特沮丧地垂下肩膀。普莉希拉则是一边摸著那少年的头，一边朝阿尔拋了个白眼。

「你们在说什么，虽然男人的价值不能全靠脸，但长相也是判断的基准之一。舒尔特，别忘记你是因为长相可爱才会受到妾身爱戴，要尽量避免让自己成长，还有也不允许长出无谓的毛。」

「至少命令在还能勉强做到的范围嘛，公主。」

「我、我会努力的……！」

「你看，舒尔特就是这么老实才会相信啦。」

对于舒尔特握紧拳头如此宣言的模样，阿尔投以怜悯的目光。但为了普莉希拉努力奉献就像是舒尔特的生存意义，干涉或许也只是多管闲事。

普莉希拉用随兴发言决定随从努力的方向后，便从双胸间掏出扇子，虽然不论何时总是既大胆又能一饱眼福的私密处，但她只是用扇子遮著嘴边说道：

「嗯，难得排遣的无趣感又回来了。阿尔，差不多该进行下个活动了。看你掉到水里已经很满意了，接下来……说得也是，干脆在火堆上跳舞吧？」

「喔～～还不错耶，我刚好想把衣服烤干……怎么可能，白痴喔！」

「为什么明明接受又会突然恢复正常？刚才那是怎么回事？」

「那是先装傻再吐槽啦。别让我继续说明下去，这样会让人很沮丧的。」

当阿尔对尴尬气氛感到无地自容时，普莉希拉突然变得越来越不高兴。虽然她就像是猫一样阴晴不定，但比起猫更加残酷就是这位主人最难伺候的地方。

就算想尽可能让她开心，但阿尔也是不知所措地歪头思索。

「你这家伙，身为取悦妾身的丑角，要随时记住自己最低底限的职责。向舒尔特多学学吧，只要是妾身说出口的话，要有不论如何都要完成的心态。」

「这真是太强人所难啦。」

「没这回事。舒尔特，说点能排遣无趣的事吧，现在立刻。」

「咦！？啊……好的，我会努力……呃……那个……」

代替无法做到的阿尔，被普莉希拉宛如暴君相向的舒尔特开始努力思考。再怎么说这样还是会良心不安，正当阿尔试图开口阻止的时候……

「啊，我想起一件事了！是刚才女侍们聊到的事！」

舒尔特顿时露出开朗神情，然后举起手开始说道：

「听说在领地南方的某个村子，最近好像出现了很多人口失踪的事件！村子附近有个森林，好像只要接近那边的泉水就会回不来了！听说好像被称为『拉德利马的恶梦』！呜呜……好可怕喔！」

「你是怎样？刚才说我是个无头人，舒尔特小弟弟喜欢鬼故事吗？」

发现少年出乎意料的兴趣，阿尔带著苦笑从头盔缝隙间将水拍出来，金属接缝间发出撞击声，阿尔则是发出「我说公主啊……」并回过头一看。

「南方村落、『拉德利马的恶梦』、会让人失踪的泉水……」

见到普莉希拉若有所思的模样，阿尔顿时有种不祥的预感。

而那个预感在阿尔实际展开行动前便化为现实。

「有趣。」

普莉希拉如此说著并阖起扇子，将扇子前端指著阿尔与舒尔特两人。

「看来这应该能打发点时间，就由妾身亲手解决那个事件吧！」

她信心满满地打算插手那件麻烦事，并且露出宛如太阳的灿烂笑容。

3

在跋利耶尔男爵领地南方的村落拉德利马，是个随处可见的平凡小村落。

离王国的主要街道太过遥远，因此几乎没有未来的发展性，只是领地内各处四散的农村之一，作为特产的花也只是稍微有名。村民们过著期望中缺乏变化的日子，因此这天拉德利马对鲜少出现的异常变化引起一阵骚动。

「呃……我就说得要变装再过来了。」

「别说那种蠢话，为什么妾身得靠变装掩人耳目？妾身没有半点需要感到羞愧的理由，你就和那群凡夫俗子把这份威严尽量烙印在眼中吧。」

「不是羞愧，是尽量不要显眼的问题……不过事到如今也来不及啦。」

阿尔一边用手指搔著后颈，一边对周遭传来的视线发出叹息声。拉德利马居民正注视著突如其来的闯入者，这也是无可奈何的反应。

毕竟连搭乘来到这个村子的龙车，都是装饰各种金银珠宝的土豪风格。

一眼就能看出光鲜华丽的黄金龙车，再加上有个绝世美少女下车，村民当然会对发生什么事而感到一头雾水。

另外如同阿尔想像般，村人的惊讶眼神大部分是朝向龙车与普莉希拉，但也有不少视线是朝向奇装异服的单手铁盔男，只是他没有发现而已。

这对主仆在显眼这点上可说是十分相似，不论如何……

「调查的基本应该是要踏实收集情报，不过啊……」

「踏实收集情报不适合妾身，快点去那个发生问题的泉水那边吧。」

「我就知道你会这么说！舒尔特，你可以应付公主吗？」

主人非常讨厌踏实或点滴累积之类的字，完全没有想遵守调查铁则的意思，阿尔决定将坐立难安的普莉希拉交给随行的舒尔特处理。

不过舒尔特没有任何反应。回过头一看，只见那位少年管家正带著认真神情，专心地看著大本的书。

「舒尔特小弟弟？」

「啊呜！对、对不起，我太专心了！」

「先把怠忽职守的事留到后面再说，那本书是什么？」

「是普莉希拉大人赐给我的书！因为怕普莉希拉大人会无聊，如果先把故事记起来可能会派上用场……所以大人要我认真读到能够背起来的程度。」

对于才刚学会读写的舒尔特，这个重大考验让他焦头烂额。虽然普莉希拉的反覆无常和随心所欲一直都是稀松平常的事，但舒尔特被这样搞得晕头转向也是很可怜。

「公主，你又对舒尔特灌输了什么奇怪观念啊。这样很可怜吧。」

「知识能够帮助人生，舒尔特还有很多要学的事。别用你的狭隘观念随便衡量，不过妾身不否认他既拚命又泪眼汪汪的模样很惹人怜爱呢。」

普莉希拉用扇子遮著嘴边，用眼角余光侧眼瞥著专心的舒尔特。要摸透她深谋远虑的心思可说是相当困难，包含她是否有想过这些事在内。

「就算舒尔特能坚强活下去好了，村子那些人的不安情绪也差不多到极限了。差不多该对他们说明情况了吧？」

「然后顺便踏实收集情报吗？好吧，在舒尔特看完书之前，妾身就特别陪你走走吧。」

对于阿尔战战兢兢提出的建议，普莉希拉出乎意料地老实点头允诺。在普莉希拉改变心意前，阿尔对远方围观的民众招了招手。

「不好意思吓到你们啦，我们不是什么可疑人士。虽然看起来好像很可疑，不过就把我们当成调查队吧。最近在这个村子附近不是发生了某些事件吗？我们就是来调查那个的啦。」

见到阿尔指著自己只有三人的小队说明目的后，村民们皆面面相觑。

说实话完全没有说服力。不论是可疑的发言、妇孺加上铁盔男的调查队，实在太多可疑的地方，阿尔已经做好了收集情报会四处碰壁的心理准备。

然而──

「那边的女性……或许有点失礼，那位该不是会是太阳公主殿下吧？」

「喔？」

有位接近壮年的男性战战兢兢地走向前如此问道。混有白发的短发男性就像是代表村人的意见般，将视线朝向阿尔身旁的普莉希拉。

受到此种目光，普莉希拉只是微微发出「哼」的嗤鼻声。

「妾身从来没有如此自称过，但领内的凡夫俗子如此尊称妾身也是事实。只要见到此种有如日轮般的高贵美貌，会如此称呼也是理所当然的事。」

「──喔喔，果然没错！」

对于这番斩钉截铁的自我意识过剩发言，男子露出炯炯目光。而男子的惊讶与感动也传达到其他村民身上，让他们如出一辙地当场跪地。

「太、太阳公主殿下居然亲自来访！虽然泉水的事已经向周遭的村子商量过了……」

「就是辗转传到了妾身耳中，才会像这样亲自直接前来。应该不会说这件事已经结束，让妾身白跑一趟吧？」

「当、当然不敢！」

普莉希拉一瞬间掌握全村的意见，并且满足地望著跪下的村民们，然后回过头朝著杵在原地的阿尔说道：

「阿尔，你还在做什么？不起眼的调查是你的工作吧。妾身已经像这样展现出威严了，你就趁著这段时间迅速完成自己的职责吧。」

「是没什么问题啦……总觉得不太能接受就是啰。」

与普莉希拉一起行动时，有时候会认为颇为认真的自己是不是做错事，也许是因为不曾看过她失败吧。

「那当然，毕竟这个世界就是为了妾身量身打造的。」

说完这句固定的台词后，普莉希拉用高亢笑声将阿尔推了一把。

之后多亏既顺从且配合的村民，情报收集得相当顺利。

「在村子旁边有个森林，里面有座泉水，然后这两个月内前往泉水的人接连行踪不明。一开始是村子的人，后来是去找的人，再来就是经过的人。后来是……」

「奇怪的传闻传开之后，每隔几天就会有人靠近泉水行踪不明──真是有够奇特诡异的。」

将村民处听来的情报简略整理后，普莉希拉对内容眯起眼睛。虽然普莉希拉的意见听来似乎颇感无趣，但阿尔也是抱持同样意见。

感觉就是救人反而身陷困境的走向。

「村子派出很多次搜救队，结果好像都是毫无成果。听说森林里面会起雾，回过神的时候就会变成独自一个人。虽然有人勉强逃回来，不过也有人没有回来，就这样变成连续失踪的事件了。」

「如果只是这样，不可能会连续出现受害者，应该不会只有村民会蠢到进入危险的森林。外面的人是被什么引诱了？」

这个精辟见解让阿尔对普莉希拉吹了个口哨，但并没有吹出声音。在干涩吐息声让她感到不悦前，阿尔便「咳哼」地清了清喉咙。

「这才是最妙的，听说那个泉水在传开的时候被加进了奇怪的传闻。接近泉水会被雾气吞没，然后只要穿过雾气……好像就能见到死去的人。」

「──喔，见到死去的人啊？」

「也有传闻说那边是连接死后的世界，不管是哪种听起来都很胡扯，不过没想到一直有人被骗。虽然现在只有十几个人受害，但说不定会变成更严重的事。」

如果不能早点解决万恶根源的传闻来源，或许会演变成国家层级展开行动的局面。这样就算能解决问题，普莉希拉身为领主的能力也会受到质疑。

身为即将参加王选的候选人，得尽可能避免这种事发生。考虑到此种层面，当初让舒尔特找来这个传闻可说是正确决定，多亏他才能动手解决这件事。

「公主，要怎么办？要随便组个调查队解决问题也是一种方法啦……」

「当然是直接进入森林，现场确认那个泉水。如果是能解决的问题，就由妾身亲手解决。这样没有异议吧？」

「真的假的？公主要进入森林？说不定会有虫子出现喔？」

「蠢货，那怎么能当成抽手的理由。而且凭妾身的威严，连虫子都不敢接近。」

普莉希拉斩钉截铁地说著这段不一定算是胡诌的话语，似乎充满干劲地想进入森林。

她绝对不是因为「想尽早解决问题」这种正面理由，不过阿尔认为这次她算是颇为积极地面对这个问题，而且反常地采取协助的态度。

但阿尔的惊讶程度，远远不及听完普莉希拉的方针后赶来的村民。

没想到代理领主普莉希拉想直接闯进森林，对他们而言可说是等同天地翻转的惊人之举，于是慌慌张张地试图阻止她。

「太、太阳公主殿下怎么能做那么危险的事！要是殿下无论如何都要踏进森林，请让我们也一起同行，动员村子的所有人进行协助……」

「等等等等！我能理解你们担忧的心情，不过要动员所有村人！？别说傻话了，带那么多人过去只会动弹不得而已啦！」

阿尔连忙对激动的村长如此说著，但看来这并非是他狂妄自大，村民们皆带著认真想跟随普莉希拉的表情，村长则是握紧拳头用颤抖声调说著：

「前任领主统治的时代简直是地狱，对现在代替领主掌管领地的太阳公主殿下，恩情实在是难以言表，至少请让我们当成肉盾！」

「嗯嗯，心态很不错。以你们这些凡夫俗子来说算是挺优秀了，今后也别忘了为妾身尽忠的节操。」

「现在是说这种话的时候吗！？」

普莉希拉看起来很开心，但就算带著一堆无法成为战力的人也是毫无用武之地。

阿尔想尽办法，试图用各种话语推辞村民们的协助。

「很感谢你们有这种心意啦，不过带那么多肉盾也没有意义。希望你们在这里乖乖等著好消息，太阳公主也是这么想的。」

「你还真是会曲解成合乎自己的意思呢。」

「太阳公主希望你们领民平安无事就好！遵命～～！太阳公主万岁！」

「万、万岁～～！」

当阿尔豁出去高喊万岁，村民们也跟著发出喊叫声。虽然再怎么强硬也要有个限度，但至少应该已经阻止村民们献身的举动了。

再来只要在他们恢复正常前赶紧离开就好。

「我们走吧，公主。人生是有限的，不过有无限的可能性，朝著充满希望的明天Let’s Go吧。」

「唔，列兹够吗？那也是新的大瀑布语吧，妾身挺喜欢这句话的。」

阿尔轻轻牵起普莉希拉的手，她也没有发怒而乖乖随著离开，仍然与书本搏斗并带著快爆炸表情的舒尔特则是跟在后头。

「那就赶快解决这件事吧。走，列兹够。」

普莉希拉高兴地说出刚学到的字并让龙车出发。

而村民们欢呼著万岁，目送载著三人的黄金龙车离开。

4

在泉水所在的森林中，飘散著一股彷佛拒绝人进入的独特气氛。

不知道是因为泉水所发生的问题所致，还是这座森林独特的先天特质，不论如何能够确定森林中似乎有某种邪恶正在蔓延。

「唉，不过我们还是不管气氛直接踏进来了。」

阿尔一边踩著地面的草，一边紧盯著茂密生长的树木并淡淡地如此呢喃。

从拉德利马出发数十分后，一行人来到目的地的森林。他们已经四处踩著草开始调查，由于当然无法搭乘龙车进入，因此内部调查只能倚靠徒步。

由走在前头的阿尔用武器青龙刀砍倒草木开出一条路，用草鞋踩平地面再让后续两人跟上的行军方式，但话虽如此……

「舒尔特和车夫一起留在龙车上会比较好吧？」

阿尔只转过头对后面两人──踩著高跟鞋毫不犹豫前进的普莉希拉，以及拉著她的手并战战兢兢跟随的舒尔特如此说道。

虽然舒尔特对这番话感到有些歉疚，但普莉希拉反而瞪著阿尔回答：

「蠢货，要是把舒尔特留在车上，带他过来还有什么意义吗？妾身能理解你想在暗处两人相处，真是太用下半身思考了。」

「我的提议才没有那么邪恶！是更纯粹的上半身思考！」

「没、没问题的！我会尽量不给普莉希拉大人与阿尔先生造成困扰……啊，要跌倒了！唔！我撑过来了！」

「嗯，舒尔特很勇敢，值得嘉许。」

与提议遭到否定的阿尔相反，舒尔特只是差点跌倒就被普莉希拉称赞而露出开心表情。这一点都不让人羡慕，也许吧。May be。

比起这件事，缓慢的行军与紧张感对阿尔来说才是大问题。明明对泉水引起的骚动没有什么兴趣，这种慢吞吞的动作反而会累积压力。

「干脆把森林和泉水一把火烧掉，这样应该比较快吧？」

「阿尔，你的愚蠢发言比平常还多。首先，用这种手段解决事情，这与认输没有两样。」

「是输或赢的问题喔？」

「不论任何事，只要自己认为是这样就会是这样。而且你就是没有发现这件事才会一直输，败者总是在战斗前习惯怀著丧家犬的想法。」

普莉希拉严厉地如此断言，然后挽起双手继续说著：

「应该说妾身也喜欢火，能把东西烧尽也会感到兴奋。不过只因为人会接近泉水这个理由把森林烧掉，这个用火的理由实在是卑贱至极，实在是蠢到极点了。」

「我实在无法理解公主坚持的点在哪……不过这样我知道了，就继续前进吧。」

早早认为反抗没有任何意义后，阿尔专心继续用青龙刀开路。毕竟是没有路的路程，这种密林也难怪会有很多人失踪，但反而会让人怀疑遇难是否与泉水毫无关联。

这座森林不算太大，也没有特别需要进入的理由。毕竟连开出道路的前提都没有达成，这也是理所当然的事。

「被森林的泉水引诱啊……听起来还真老套。」

在劈开森林的阿尔背后，普莉希拉以掩饰无趣的声调如此说著。阿尔一边听著这番话，一边说著「也是啦」如此表示同意。

「一开始失踪的人，好像说过在森林看到有美丽的光四处跃动，然后被引诱就摇摇晃晃走进森林……现在是想见到死者的人被接连吞没。」

「想见到死者……听起来越来越老套了。」

普莉希拉的话语让阿尔感到有些诧异。无趣、愤怒、不服气、开心、喜悦，虽然普莉希拉的阴晴难定很难捉摸，但刚才的呢喃与这些感情截然不同。

感觉比较接近羡慕与嫉妒的情感。

「……公主没有想见到已经死掉的人吗？」

「没有，最近妾身身边死掉的人顶多只有心爱丈夫而已。」

「还没死啦，对外宣称疗养中。」

「连大小解都得靠人，和死掉没什么两样了。」

普莉希拉这种难掩厌恶的态度，没有出现直到刚才的奇妙征兆，阿尔视若无睹地耸了耸肩后，便看向持续保持沉默的舒尔特。

刚才的话题说不定会让仍年幼的他难以接受。果然如同想像般，舒尔特彷佛回想起话题中提到的人物并面露铁青。

「老爷他……应该是个坏人吧？」

「有句至理名言是『正义的相反侧是另一种正义』。不过说难听点，莱夫老爷子实在不能算是正义，完完全全是个坏人，虽然我们也不能算是正义啦。」

身为普莉希拉的夫婿，原本的跋利耶尔领主莱夫•跋利耶尔，曾经企图将普莉希拉当成傀儡掌握王国实权，结果计划被阿尔与舒尔特摧毁，精神也崩溃成为废人。

「有很多人会因为那样高兴，这也证明了公主很受欢迎，虽然这样挺悲哀的。」

「可是……我还是希望老爷的灵魂能至少获得安息。」

「就说他没死了啦……」

虽然阿尔想继续说下去，但舒尔特带著认真表情用双手遮著脸的模样让他打断话语。至少有个人能认真地悼念莱夫，希望他来世能变得更正常一点。

「真是的，别再说了。对那种老不修祈祷只是浪费时间而已。」

然而，阿尔决定不继续追究的此种祈愿，似乎让普莉希拉不是很中意。只见她不悦地挑起眉头，对抓著手腕舒尔特的头晃了晃。

「如果有时间在意那些小事，还不如赶快把刚才那本书背熟。」

「咦？遵、遵命……小的会努力背熟！呃……一开始是……」

「别欺负纯真的小孩子啦……」

虽然阿尔对这种幼稚的态度颇有微词，不过舒尔特已经放弃祈祷，开始继续背诵。阿尔只好在心底合掌替莱夫默哀，然后用刀将眼前某根较粗的树枝劈断。

「话说阿尔，你对见到死者这件事好像还满否定的。」

「当然不可能会有这种事。人只要死掉就结束了，不可能见到死人，也别想再见到面。那只会招来不幸而已，公主应该也是怀著同样意见吧？」

树木之间的间隔相当狭窄，阿尔先将树枝劈出裂痕再用脚踹。只靠一击无法劈断树枝，第二发也是传来坚硬触感。

「就算结论类似，妾身和你走来的过程不一样。不能见到死者这点确实没错。」

「────」

第三道攻击让树木发出低沉声响倒地，阿尔用小腿将树木抬起并踢到一旁开出道路──

「还是说……你有不想见到的死者？」

这道撼动鼓膜的话语让阿尔咬著牙齿，脚太过用力将树木一脚踹飞。杂乱倒地的树木摇晃著枝叶，阿尔则是深深吐出一口气。

这名少女真的是毫不留情地践踏著他人的心灵。

「我说公主啊，对我说那么严肃的话题也是……」

阿尔硬是让自己的心脏恢复冷静，装成一副若无其事的飘飘然态度回过头。不过这番话并没有传到普莉希拉耳中，连舒尔特也是。

「────」

开始起雾了，阿尔也在不知何时变成独自一人。

5

阿尔环视四周，不知何时视野被白色雾气覆盖，变成连森林都无法看清楚的世界。没有感觉到原本应该在身旁的两人气息，阿尔用青龙刀敲了敲自己的肩膀。

「真的假的，跟传闻一模一样啊。」

原本阿尔对村人几乎等于是流言的证词半信半疑，现在却成为了现实。

只要进入有泉水的森林就会被雾气包围，被剩下只有自己一个人。虽然有人勉强逃脱雾气回到村子，但运气不好就会被拉进泉水──

「然后就能见到死人吗？很可惜这一点都不让人高兴啊。」

因人而异，也许有人会想冒著失踪的风险，不过对阿尔来说，与死者重逢只会感到恶心而已。

「比起这件事，如果能趁著这场雾不小心吃到公主的豆腐还比较令人高兴哩。」

阿尔将色欲更优先于神秘景象，伸出青龙刀往雾中搅动。刀尖没有碰到任何东西，完全感觉不到先前如此密集的树木，可说是很不自然。

依照遇难时的准则，最好的方法是尽可能不要乱动。不过阿尔的两位同行者，感觉分别会以不照规矩与无知为由违背这个准则。

「也不能不去找吧……真是饶了我吧。」

面对此种被迫主动的状况，阿尔只好叹了一口气慢慢踏进雾中。

雾被视为不吉的象征，在这个世界似乎是各处共通的概念。这片雾虽然与原本被视为凶兆的雾气不同，但仍然无法拭去诡异的气氛。

阿尔拨开甚至有触摸感触的浓雾，竖起耳朵寻找会合的线索。他犹豫著是否该主动出声呼喊，原因是来自直觉。总觉得有种不好的预感，至于那种预感──

「──是谁？」

雾气前方传来呼吸声，阿尔怀著戒心停下脚步。他人的低沉呼吸声传到头盔内侧并撼动鼓膜，不像是普莉希拉或舒尔特的声音。

很显然是男性的声音，带来的人里面没有符合的人选，让阿尔越来越紧张地摆出备战架势。

「────」

微微的脚步声在正面传来，毫不迷惘地逐渐接近。

该不会真的是死者出现在这里──

「──找到你了，你这个叛徒。」

「────」

在浑身战栗的阿尔面前，有位体格壮硕的老龄男子穿过雾气现出身影，那位白发老人穿著剪裁高级的衣物并带著充满野心的混浊眼神。

阿尔曾经看过这个人，男子朝阿尔投以满是憎恨的目光。

「是你这家伙……」

「就说他还没死啦！！」

在吐出愤怒前，阿尔已经一刀斜向将老人劈成两半。

「────」

还来不及对此种暴行做出反应，老人硬生生地吃下这击，然后老人往后倒下的身体如同字面所述般烟消云散，化在雾气中消失得无影无踪。

见到此种景象，阿尔气喘吁吁地扛起青龙刀，刀刃上没有沾染半点血迹。

「果然只是唬人的嘛！至少把死人带过来啊！死人！」

才刚提过而且是活著的老人出现，让阿尔对此种随便至极的超常现象表露无遗地发泄怒气，不管再怎么说这个发展也太即兴了。

或许不是参考阿尔的意见，但在假莱夫消失后，发出怒骂声的他的四周，取而代之地浮现出许多人影。

有全身盔甲的壮汉、握著长长刀剑的黑衣男、拳头与刀刃化为一体的半裸矮男，另外还有许多阿尔曾经看过的人，让他忍不住叹了一口气。

「要剑奴同伴大集合是没关系啦，这是怎样？你们是在我不知道的时候挂掉了吗？」

「────」

没有任何回应，取而代之地黑衣男横举著武器冲了过来。

阿尔冲进对方怀中，压低身体躲过银色闪光。这是挑战过几千几万次的一击，身体完全记得对方会怎么行动。接在首度攻击后的膝盖搭配剑击，趁著对方失去平衡后再用刀刺穿身体。

盔甲壮汉习惯在使出大招前举起手腕，矮男只要拚死往前突击就会怕受伤拉开距离，这些都没有改变，或许该说劣化许多。

「重现度有够低的啊～～！」

横扫过举起手腕的壮汉身体后，趁著厌恶接近的矮男退后时将青龙刀丢向他，致命伤并非喷出鲜血而是雾气，这些虚假的老面孔也消失无踪。

接下来出现的并非是剑奴，不过仍然是熟面孔，于是阿尔带著感谢之意挥出刀。

「感谢你饯别的头盔啦！！」

这次是逃出斗技场时将头盔作为饯别的门卫，将对方的头砍下并目送下流笑容化在雾气后，阿尔确认击退了第二波攻势。

「真是有够不痛快的……应该说我逃走的时候所有人还活著吧。啊，只有加吉特是被我杀掉的。」

和重现的过程一模一样，当时应该已经刺穿身体杀掉他了。既然这样，这也能算是与死者重逢吧。

「有够诡异的……应该说不能选人就没什么好说了。」

只是随便找有关系的死者过来，对想见面的人也只会感到困惑，或许该说连还没死的人都会出现，这个前提条件早就已经不成立了。

「不过倒是有照顺序符合传闻，照这样下去就换我要到死后的世界了吗？」

能够料想到失踪者的名单上也许会加进阿尔的名字。条件或许是在这片雾气中被杀害，或是会出现其他异常状况。

「在说这些的时候，第三波要来啦……」

阿尔不耐烦地举起刀，视野中能见到雾气正异常蠢动。雾气无声地开始旋转接连构成形状，缓缓地当场形成新的个体。

现在不管是谁出现都不值得惊讶了──原本阿尔是这么想的，然而……

「────」

由白色雾气构成诞生的个体，却是呈现几乎埋没视野的漆黑。

暗色覆盖的细瘦肢体，旋转的雾气突然被膨胀的漆黑影子吞噬并失去原形，世界也转眼间被涂成截然不同的模样。

──眼前重现的是绝对不能存在的禁忌。

「啊……」

阿尔发出嘶哑的吐息声，感觉到自己正处在前所未见的战栗感中。

他已经发现这片雾气不问生死，是将与对方曾经有关系的人重现在眼前，不过现在实在太反常了，这个根本是犯规。

重现这个已经是超越生死并亵渎所有万物。

「啊、啊啊啊啊啊啊啊～～！！」

一股愤怒涌上心头，让阿尔激动地发出喊叫声。

得靠著这道喊叫声的气势蹬地冲向前，用尽所有力量将眼前的黑影劈散，必须这么做才行。

然而，带有气魄的怒吼却变得沙哑，应该踏出的脚不停颤抖，理应挥出的刀由放开的手指滑落地面。

不能动、没有动静、无法移动，因为真的没办法动。

已经尝试过几千、几万、几亿次都不行了──现在当然不可能成功。

「────」

牙齿发出喀喀的颤抖声，阿尔的双脚随时都有可能跪倒在地。

而在阿尔面前，黑影缓缓地前进。被黑影覆盖的人影穿著同为暗色的礼服，礼服裙襬随著黑影摇晃，细瘦手腕则是直直举起。

能够见到每根纤细的手指，以静静、温柔、彷佛疼爱的动作逐渐接近直挺挺站著的阿尔颈部。

只要被碰到就能解脱，一切都能获得解脱。所以──

「────」

突如其来的恐惧让阿尔吓得跌坐在地，但下意识的浑身僵硬将恐惧感剥除，让他勉强后退，试图拉开距离。

「别、别过来……我……我……！」

「────」

声音断断续续无法形成喊叫声，黑影完全不在意阿尔的抗拒，仍然缩短拉开的距离走了过来试图碰触。

正当阿尔就这样即将发出绝望的惨叫声时──

「咦？」

下个瞬间，黑影的胸口由背后突然被闪耀红光的宝剑贯穿。

阿尔对此种景象看傻了眼，随后发出一道光芒。红与白色的光芒交互膨胀，由雾气构成的影子瞬间燃起火焰，全身毫无遗漏地被火焰包覆。

「──真是无趣，区区幻觉终究只有这点程度。」

雾气被红光蒸发，另一侧传来听似无趣的少女声音。站在阿尔与火焰另一侧的人，就是单手握著深红色宝剑的普莉希拉。

就在阿尔面前，宝剑之力将雾气形成的黑影燃烧殆尽。

「可、恶……」

「────」

「你做什么啦。居然在我面前……啊噗哩唔！」

「吵死了，别把对莫名其妙的怒气发泄在妾身身上，你这个凡夫俗子。」

对于咬牙切齿气得发抖的阿尔，普莉希拉毫不留情地用剑揍了下去。这发攻击让阿尔翻了一圈，冲击力道也让他瞪大双眼。

「啊……嘎……公、公主……唔喔！好烫！呀啊啊啊！火、火啊！」

「这是没礼貌的教训，你就被阳剑的火焰稍微烧秃头好好反省吧。」

受到普莉希拉无情的处罚，阿尔的铁盔一部分烧了起来。他拚命在地面翻滚试图灭火，总算把火灭掉后便落魄地瘫倒在地。

普莉希拉俯视著阿尔，将阳剑刺在地面并发出冷哼声。

「就是越多纠葛才越容易著这种魔，假惺惺地说自己没兴趣结果变成这副德性，实在是丢人又滑稽啊。」

「公、公主……是真的公主吗？应该不是假的吧？」

「你是想被像平常一样被踩，再用快感回想起来吗？」

「重现度好高！是真的公主！」

抬起头望著残酷地歪著头的美貌，阿尔对自己回到恢复正常的世界而松了一口气。

虽然刚才重现的事还余悸犹存，阿尔告诉自己刚才消失在雾气中的只是假货，没有任何问题，应该是没有问题才对。

现在还是先对双方能够平安会合感到开心就好。

「公主没有碰到任何事吗？」

「这点程度的低等魔物怎么可能迷惑妾身？你在这里别乱动，雾气马上就会消散，舒尔特会把雾气驱散。」

「舒尔特？为什么？」

「已经告诉他解法了，只要舒尔特不是个肤浅的蠢货就没问题。」

普莉希拉指著不在现场的少年管家，毫不犹豫地如此断定。阿尔感到颇为困惑，但他的困惑并非是由这段话，而是由结果迎刃而解。

「────」

只能以「歪斜扭曲」这四个字形容般，阿尔的视野明确地开始大大扭曲变形。

在扭曲的世界中只有景色歪斜变形，将双手挽在胸前的普莉希拉仍然维持原状。她与阿尔平安无事地留在原地，只有世界大幅扭曲歪斜破坏，接著雾气被杂乱地撕裂成四分五裂──

「真的假的……」

在一眨眼间，先前大量弥漫的雾气突然消失得干干净净，阿尔等人的身影在森林中──而且已经移动到泉水旁的草丛上。

在哑口无言的阿尔眼前，有一汪并非很宽敞的泉水。澄澈的泉水上有无数水草漂浮，还能四处见到花瓣随风摇曳。

接著，在泉水正中央，有个泡在水中直达腰际的少年举起双手。

「舒尔特！？你在做什么！？」

「舒尔特把依附在泉水的幻象驱除了，那会产生雾气将迷路的人蛊惑心灵再沉进泉水中，就是那么丑陋的魔物。」

对惊讶的阿尔如此说完后，普莉希拉不悦地瞪著泉水。发现两人的存在，舒尔特顿时露出开朗神情朝向两人。

「普、普莉希拉大人！阿尔先生！我有好好找出来了，水镜就像普莉希拉大人说的沉在水底！」

「就像公主说的……」

「和大人赏赐的童话书写得一模一样！」

舒尔特划著水走了过来，这番话让阿尔想起书的事而哑口无言。让舒尔特念到背起来为止，就连在森林里都让他持续默背的那本书，内容就是──

「泉水或是湖之类的水边都不会缺少这种故事，总之水流聚集之地容易累积玛那，自然也偶尔会引起这种现象。」

「上面也有写著避免被水边的水妖或幻影迷惑的秘密！」

「那是让孩童听闻的有趣奇特童话。」

普莉希拉若无其事地闭起单边眼睛，阿尔却迟迟无法挥除震撼感。表示普莉希拉在听到传闻片段时，就已经察觉到泉水的真相了。

「普莉希拉大人，这是水镜。打破之后雾气就消失了。」

舒尔特从泉水跳了出来，仍然浑身湿润地冲到普莉希拉面前。少年将先前拿在手中微微呈现白色透明的结晶递出，那应该就是水镜吧。

「做得好，值得嘉许。」

「谢谢大人！小的很高兴能派上用场！」

普拉希拉接过水镜并收起下颚，舒尔特则是带著满面笑容。阿尔从后面望著两人如此说著话，带著尴尬的心情搔了搔后颈。

「所以这样就解决了吗？这个事件是累积的玛那在作怪？」

「──无能的人也许会这么擅自认定就回去了吧。」

从这番尖酸的发言中感觉到杀气，让阿尔与舒尔特皆瞪大双眼。随后，普莉希拉手中的水镜突然开始燃烧，透明的玛那结晶被火焰焚烧。接著──

『吱吱吱──』

水镜突然改变形状，从普莉希拉的手中飞了起来。四根翅膀、小小青蓝色身躯与瞪圆复眼──那是人类身躯与虫类翅膀头部混合的异形。

异形发出尖锐惨叫声，试图逃离这个地方。

然而──

「──邪恶精灵，妾身会这么容易让你逃走吗？」

舞动的阳剑前端将小小异形的翅膀斩断，将身体刺穿钉在地面上。就像是昆虫标本般被留在地面，异形摆动手脚拚命地挣扎。

『吱吱吱──』

「别在那边吱吱叫。配上那个丑陋的外观，光是存在就让人想吐。」

普莉希拉不悦地扭动剑身，让异形更加痛苦地发出叫声。见到此种景象，舒尔特吓得跌坐在地，阿尔则是深深地倒吞一口气。

「公主，那家伙……是精灵吗？」

「就像你看到的，应该是伪装成自然诞生的水镜想骗过我们吧。想用这种小聪明轻视妾身，真是罪该万死。」

「就是俗称的邪精灵吧。我还是第一次看到哩……」

被普莉希拉的阳剑刺穿，精灵拚命地喘息──阿尔则是对邪精灵皱起眉头。

邪精灵也是精灵的一种，严格来说并没有差别，只是会对人类与动物抱持恶意而让此种称呼传开。原本精灵就是依存玛那的超自然生命体，不会受到物质世界的善恶束缚。

不过只有在很稀有的情况下，会出现像此种对人类怀著明显恶意的精灵，这些对人类有害并等同于魔兽的精灵就会被称为邪精灵。

「以水镜的力量吸引人类，沉到泉水中再将欧德吸取殆尽。应该就是用这种方式累积力量，简直就像是食虫花一样的习性。」

反反覆覆此种行为，失踪的人或许就是在这里遭到邪精灵杀害。

想见到死者而将一丝希望托付于此的人们，如果能在雾气中见到想见的人才死去倒还好，但要是扑了个空还被啃食杀害的话──

「普莉希拉大人，这个邪精灵……要怎么办才好？」

「当然是处分掉，在妾身的领地进行此种暴行，不论死多少次都罪不足惜。不过妾身还是慈悲为怀──罪该万死只要一次就结束了。」

对于发出痛苦呻吟的邪精灵，仍然年幼的舒尔特怀著些许同情，但此种同情被普莉希拉坚决斩断。

但不知是否从舒尔特的态度见到希望，邪精灵停下挣扎的手，抬起头让舒尔特能够见到，彷佛拚命地发出某种诉求般开始鸣叫。模样简直就像求助，恳求只要能得救不惜做任何事似地。

「唔──」

此种模样让舒尔特噤声并泪眼汪汪，对他那失声投来的目光，普莉希拉的鲜红眼瞳没有半点迷惘。

接著，在她与少年产生不必要的争执前，阿尔插嘴说道：

「就算那家伙表示只是临时起意，不会再犯第二次，还说之后会洗心革面也是一样。」

「阿尔先生……？」

「你应该也有在村子听到，最初的牺牲者是被森林摇曳的光芒引诱。表示这家伙从一开始就是打算把人类当成目标。」

邪精灵就是邪精灵，不可能会突然性情扭曲。那些家伙的恶意没有任何理由，对人类就是单纯的敌人，因此不需要任何同情或留情。

「就慢慢燃烧殆尽，藉此用来安抚妾身领民的灵魂吧。」

阿尔的话语让舒尔特保持沉默后，普莉希拉便如此宣言并将阳剑灌注力量。

随著她的意思，阳剑刀身开始发出赤红色的光芒。接著，熊熊燃烧的火焰沿著剑尖，将邪精灵的小小身体逐渐烧焦。

邪精灵发出尖锐的惨叫声，但声音渐渐被火焰吞噬缓缓淡去──然后突然断绝再也听不见声音。

而这就是连续失踪事件「拉德利马的恶梦」的结局。

6

「听说从那汪泉水底部接连发现失踪者的骨头，虽然几乎都已经变成骨头了，不过好像还是能从装饰品区别。」

泉水的事件解决数天后，阿尔将刚听说的消息传达给普莉希拉。

场所是跋利耶尔宅邸二楼的观景台，在办公之余的茶会时间，普莉希拉正喝著舒尔特冲泡的红茶，对阿尔突然现身的报告皱起眉头。

「那汪泉水？你在说什么事？」

「就是之前那个邪精灵相关事件的后续报导啦！看公主好像是真的忘记，让我差点吓死了哩！」

「泉水、邪精灵……喔，你是说拉德利马的事啊。别把妾身已经没兴趣的事挖出来重提，还以为是什么大事。」

「我的错？是我的错吗？好好，抱歉啦～～！」

向已经失去兴趣并面露不悦的普莉希拉道歉后，阿尔坐在她的对面。一阵暖风拂过观景台上，温暖的阳光让他频频浮现睡意。

面对阿尔此种懒散的模样，普莉希拉将杯子放回桌面并发出嗤鼻声。

「说起来，你这家伙那天一副丢脸的模样，还真敢再提起那件事。先说清楚，你那天的表现可是比舒尔特还差劲。」

「我完全不能否定，所以别再说啦！明明都已经忘记了，还记得我的样子喔！」

被水镜的幻影束缚并扯后腿的事，实在很难淡忘，回想起当天的事，在头盔内侧红著脸的阿尔指著重新泡著茶的舒尔特说道：

「为什么水镜的陷阱对公主和舒尔特没有用啊？公主的超脱世俗规格我是能接受啦，舒尔特不就只是普通的正太吗！」

「啊，是的。就是个普通的正太……」

「这没有什么好害臊的，因为正太也不是称赞的话。」

对露出害臊笑容的舒尔特随意搓了搓他的头后，阿尔将脸靠向这位少年。对于阿尔询问突破幻觉秘诀的态度，舒尔特只是面露尴尬地垂下头。

「我没有做什么特别的事，或许该说幻觉是……？」

「问题是在这边吗！？」

「这不是什么难事，因为舒尔特没有需要逞强隐瞒或想见到的死者，水镜幻觉的前提条件就和你不一样了。」

普莉希拉从纠缠的阿尔手中将舒尔特抢了回来，将这位少年夹在自己双胸前。阿尔一边看著此种令人羡煞的景象，一边对普莉希拉所说的话在头盔中眯起眼睛。

──之所以不会被幻觉困住，是因为舒尔特心中没有会被束缚的回忆。

身为孤儿的舒尔特在差点死掉前被收留，没有与家人的回忆，也没有被普莉希拉收留前的幸福记忆，所以幻觉对他没有产生效果。

如果是这样，没有被那道雾气束缚到底是幸运还是不幸？

「至少我不觉得是幸运啦……」

在雾中反覆出现的邂逅，原先应该是生者与死者互相交会的时间，对阿尔而言并非是期望中的重逢，而且毕竟都只是假象。

「────」

阿尔用头盔隐藏著表情，看著拥抱舒尔特并露出满意表情的普莉希拉。

用阳剑将黑影贯穿后，普莉希拉并没有逼问阿尔在雾气中见到了什么景象，她应该也毫不在异自己究竟烧掉了什么东西。

即使知道这并非是她设身处地替阿尔著想，只是单纯想这么做的结果，阿尔还是对此感到有种既舒畅且解脱的感觉。

「阿尔，怎么这样盯著妾身？舒尔特的位置不会让给你的。」

「我是很羡慕啦，不过我的眼神不是那个意思！话说回来……公主在那片雾气中没有看到任何东西吗？」

「很可惜，最近妾身身边的死者顶多只有心爱丈夫而已。」

「就说他还没死啦！虽然没死，我也在雾里碰到他了啦！」

即使在不想见到的死者中，莱夫还是最感到尴尬的对象。

这个表白让普莉希拉微微一笑，舒尔特则是露出惊讶表情。就这样笑了一段时间后，普莉希拉微微歪著头问道：

「话说阿尔，村子的报告是从哪听来的？」

「嗯，是刚才提到的村子派使者过来。要我把刚才那些事告诉公主再打声招呼……对对，还有花送到门口。」

「──！你这个大蠢货，怎么不早点说！」

「哇呀！普、普莉希拉大人！」

阿尔最后一段报告让普莉希拉露出灿烂目光，她用公主抱将舒尔特抱了起来，就这样充满气势地冲出观景台。见到普莉希拉以猛烈速度冲了出去，阿尔慢了好几拍才连忙跟在后头。

就这样，阿尔直到宅邸门口的大片花束前才总算追上两人。

「嗯嗯！真是既壮观、优雅又楚楚可怜！拉德利马的居民真是值得赞许！」

普莉希拉双手叉腰，开心地对花束──也就是随著报告送来宅邸的高级鲜红色花朵展露灿烂笑容。

普莉希拉的此种反应，只有见到奢华黄金龙车、各种珍奇艺术品、以及疼爱舒尔特时才会露出类似表情。简单说就是相当开心。

「这些花是这么高级的东西吗？」

「哼，无知还真是悲哀。这是只有在露格尼卡王国部分区域才会生长的花朵，也是只有在拉德利马之泉才会绽放的『红花』。」

「没听过……咦？嗯嗯？你刚才说只有那个泉水的森林才会绽放？」

「只有在这个时期，甚至可说是那个穷酸村子唯一存在的价值。」

普莉希拉挽著双手撑起丰满胸部，彷佛确定这个答案般不断点著头。

对她处之泰然的侧脸，阿尔理解到她会颇为积极解决这个事件的理由，仔细回想她当初也曾经强烈反对将整片森林烧掉。

她那极为灿烂的笑容，解释了她的所有行动。

「话说公主，你一开始就是看上这些花才会帮助那个村子吧？」

「别说傻话，拉德利马可是妾身的领地。怎么可能只看上花才施舍慈悲──但不否定是会立刻行动的理由。」

普莉希拉毫无隐瞒或羞愧之意，大大方方地走向花束。

要是得知她的真正意图，将普莉希拉赞叹为慈悲女神的村民肯定会很吃惊。告诉他们也没有任何意义，没有人知道能让更多人得到幸福。

「实际上也是公主救了村子，虽然是以自己的欲望为优先。」

因为想看到大朵鲜花而展开的行动拯救村子，就结果而言还接连获得领民的支持，恰好证明了普莉希拉所说「世界是为了她量身打造」的话。

「普莉希拉大人，请问花要送到哪里呢？」

「妾身的房间，还有装饰整个宅邸。趁著花朵性命犹存，尽可能用美丽取悦妾身的眼睛吧。别忘记照料让花枯萎了。」

「遵命！小的会努力照料！」

遵从普莉希拉的指示，舒尔特拔腿开始收集整个宅邸的花瓶。目送这位少年管家四处奔走后，普莉希拉发现阿尔还留在原地。

「阿尔，你在做什么？有时间杵在那边还不去帮舒尔特，要记得这里的每片花瓣都有你性命的双倍价值。」

「……这实在说得太过头了吧，公主。」

她的心情可说是相当愉悦，口无遮拦也是搭配得恰到好处，这番犀利言词让阿尔无奈地微微苦笑。

接著，这位红衣少女背对著红色花束。在被残酷且慈悲为怀的主人踢屁股前，阿尔连忙加入准备运送花束的行列。

** 后记

各位好！也许是这个月第二次见到各位的长月达平！同时也是鼠色猫！如果这里是初次见面，希望能有第二次向各位打招呼的机会。

那么，或许有人会对这些话不得其解。请容本人在此说明，那就是Re：Zero短篇集3与本篇15将会同时贩售！（注：此为日文版之贩售状况。）

也就是说，这次也是写了两篇后记。说不定会与本篇同时购买的读者连续见面两次，所以在此全盘说明。

这集就像是简介所述，是「主角不会死亡！」的罕见内容，因此也能让「本篇因为不敢看到主角死亡，不过短篇没有这些剧情，所以可以轻松看」的读者充分享受。不对，感觉这种读者一开始就不会碰Re：Zero，但毕竟还是有无限的可能性嘛！

总而言之，这次也是面临惊滔骇浪的两集同时连载。上次在短篇集后记应该也有提到，这集收录的内容是月刊Comic Alive样本杂志挑选出来的短篇故事。

因此我原本以为已经有原稿会比较轻松，结果实在很想把以年为单位的旧稿重新改编！可是又没时间！不，还是改编好了！

就是这个样子，这次也是整篇经过改编，以作业量来说和平常没有两样！

话虽如此，故事也有经过同等改良，希望各位能充分享受包含内容与文笔修正的短篇集。

话说回来，最近因为本篇的关系，后记的篇幅也相对较少，因此几乎没有空间能够报告近况。不过这次后记有三页！所以能报告近况了！

其实在作者近况的部分也有稍微提到，在推出这集之前曾经到兵库一趟。目的是观光……当然不是。没错，其实是去做健康检查。

相信聪明的各位读者都知道，作家这种职业非常容易疏忽健康。虽然还是有个人差距而无法一概论定，但至少本人所知大概都是这个样子，当然包含本人在内也是这样。

不过为了继续进行优良的写作，维持健康也是不可或缺──因此念头一转便进行了这趟「健康检查假期」，本人为了参加这次活动前往了兵库！

接著，在兵库主题公园「太阳公园」尽全力享受并四处拍照，然后意气风发地踏上归途！还是自己家最棒了！健康检查的结果？请期待明年！

而凭著这股心情与气势完成了这本短篇集！这是牺牲健康写出来的作品，大家应该会充分享受吧！

那么，对各位的心灵健康给予莫名不安后，请容本人进入惯例的致谢时间。

首先是I责辑，虽然同时连载两集并不是做不到，但不只是本人，连相关人士应该都是忙到快死掉了，下次还是先累积量表之后再这么做吧！总之这次也辛苦您了！谢谢！

接著，这次插图是向不同老师道谢！负责Re：Zero第二章漫画版的枫月诚老师，居然会负责这次短篇集的插画！

包含漫画版也有出现的夏美•舒瓦兹，以及在第二章没有出场机会的王选候选人，能够见到枫月老师的笔触很令人高兴！真的非常感谢！

设计仍然一如往常地完全交给草野老师，这次是分别由不同老师负责插画的豪华阵容，感谢您将本书完成！

另外还有MF文库J编辑部的各位、负责漫画化的マツセ老师、以及在这个位置致谢相当有新鲜感的大冢真一郎老师、宣传人员与各家书店，感谢各方的照顾！

只靠长月孤军奋斗不可能完成两集同时连载。多亏各界相关人士，才让本人能乐在其中。

最后当然是多亏了阅读本作的各位读者，一直总是非常感谢各位支持。

小说、漫画、决定制作新作插曲的动画等等，Re：Zero还有很多企画正在进行！

接下来也务必请各位多多指教！

（2017年11月，想到今年即将结束而涌现出恐惧感）