#+title: Re:从零开始的异世界生活 外传 ex5 绯色姬谭
#+setupfile: ./setup.setup
* 外传 ex5 绯色姬谭

** 『红莲残影』

台版 转自 天使动漫论坛

天使动漫录入组

图源：真妹控

录入：kid

1

林间洒落的温暖阳光照在额头上，让意识缓缓地恢复清醒。

「嗯、嗯嗯……」

细瘦喉咙发出尚未变声的较高声调。

这种无法感觉出男女差异的中性声音，搭配声音主人的甜美容貌，甚至伴随着莫名悖德的魅力。

某个惹人怜爱的年幼少年喃喃发出这道声音，在床上扭动着身体。

睡卷的桃红色头发，以及乳白色的光滑肌肤。年龄看起来约十岁左右，那令人误以为是天使的清纯天真模样，确实与声音的印象毫无差异。

少年名为舒尔特──有段时间因为与生俱来的贫穷差点饿死，但靠着极为幸运的际遇捡回一条命。

「呼啊……」

舒尔特在白色床单上撑起身体，打着哈欠，揉了揉眼睛。

进行这一连串动作的少年的深红眼眸像是嵌进红宝石般，让容貌更显魅力。就某种意义而言，舒尔特的容貌可说是纯粹自然的极致。

然而，这种客观评价与他本身的感想往往有所歧异。

「唔……还是这么瘦弱啊……」

揉完惺忪双眼，当清醒的意识跟上现实后，舒尔特捏了捏自己的手臂，不悦地鼓起红润脸颊。

不满的原因相当单纯，便是不论如何锻炼都没有变得结实的手脚，以及让各种锻炼成果化为乌有的自己的身体。

明明昨晚也有彻底练习挥动木剑才上床就寝，舒尔特的手臂仍然柔软弹嫩，然而还是有微微抽痛的感觉，这才是最让他感到不堪的原因。

严格说来，舒尔特感觉到的抽痛名为肌肉酸痛，也证明了少年的纯真愿望正踏实地逐步前进。不过──

「阿尔大人说过，身体会痛就是不舒服的证据……得休息到这种抽痛感消失才行。」

舒尔特反刍着训练时向阿尔寻求的建议。若是听从阿尔的话，依照计划来算，大约会是一天练习空挥再休息五天。

──理所当然地，这样要出现锻炼成果只能说是痴人说梦，而舒尔特当然不可能知道其中含有阿尔的算计。

然而，阿尔的计划并非完全来自他的幼稚心态。

「──起来啦？舒尔特。」

「啊……」

听见这道声音的瞬间，舒尔特弹起身体，在床上改变方向。房间深处有个人影映入舒尔特回过头的眼帘。

那个人坐在奢华的椅子上，优雅地翘起长腿。那窈窕婀娜的肢体被单薄睡衣包覆，深红眼瞳正阅读着放在腿上的书。

光是这副模样便彷佛至高无上的绘画，实际上，她的一切在舒尔特眼中都是如此闪耀动人。

「──早安，普莉希拉大人。」

「嗯，舒尔特，你今天早上还是这么可爱。昨晚抱起来的感触也值得嘉许。」

「谢、谢谢您夸奖……」

见舒尔特带着陶醉表情回应，眼前的女性──普莉希拉落落大方地点了点头。对舒尔特而言，这段夸奖的话语有种不知道该高兴还是害羞的复杂心情。

即使知道自己的职责是在普莉希拉身边打杂与陪睡，但如果情况允许，他想以更确切的方式地回报这份深厚恩情。

这既是舒尔特无庸置疑的真心话，同时也是愿望。

「盯～～」

「怎么了？今天早上格外仔细地盯着妾身，有什么事？」

「没、没什么……普莉希拉大人今天依然是全世界最美丽的女性！能陪在普莉希拉大人身边真是太幸福了！可是……」

「可是什么？」

「明明很想替普莉希拉大人尽心尽力，我还是没有能力完成这个愿望。如果能像阿尔大人一样用力挥剑就好了……」

舒尔特一边说，一边重新对自己的细瘦手腕涌现出无力感。

就算没有到普莉希拉的骑士阿尔，或是私兵团「赤备队」的程度也没关系，至少希望有力量能替普莉希拉分担即将面临的其中一项艰辛苦难。

「要是有个万一，我会成为普莉希拉大人的挡箭牌……啊，可是我身体很小。如果普莉希拉大人能把我举起来当成盾牌……啊呜呜！」

「别说蠢话，只有妾身能决定要怎么使用持有物。居然敢指使妾身，你是什么时候变得这么嚣张了？」

普莉希拉如此说着，不知何时站起身，使劲地搓了搓舒尔特的头。被普莉希拉的手掌摆弄，舒尔特头晕目眩地辩解：「我、我不是这个意思……」

「呜呜……要是不能成为挡箭牌，我要怎么样才能帮上普莉希拉大人的忙呢？啊，紧紧抓着普莉希拉大人当成铠甲……」

「不是要不要成为装备的问题。舒尔特，妾身不是希望你身为剑或盾，顶多只要像现在一样当成抱枕就好。」

「抱枕……吗……」

普莉希拉毫不留情的回应，让舒尔特沮丧地垂下肩膀。

虽然他早已知道，但被救命恩人告知自己不被当成战力还是相当难受。这一切都是柔软的手臂，或是骨瘦如柴的细瘦双脚的错。

「──嗯。」

望着似乎痛恨着自己身体的舒尔特，普莉希拉彷佛夸耀着丰满胸部般将手挽在胸前，吐出一口气。

「舒尔特，要是你不甘愿只能成为抱枕，与其挥剑，不如多看书吧。这样比较能帮上妾身的忙。」

「……看书吗？看书就能成为普莉希拉大人的挡箭牌吗！」

「不可能，别自大了。」

「的确是太自大了……」

舒尔特随即反省着听到解决方法便乱投医的自以为是举动。普莉希拉对舒尔特这番模样眯起眼睛，用手大略指了一下房间内部。

这里是普莉希拉的寝室，但除了大床铺以外，书架上还收藏着供她阅读的书籍。在普莉希拉的跋利耶尔宅邸中也有大规模书库，藏书量可说是王国数一数二。

普莉希拉的前夫莱普，似乎原先也是很会收藏书籍的人。自从普莉希拉掌握宅邸实权后，收购的书籍数量更是与日俱增。

这实在无法单纯以「饱读诗书」一句话解释，而是篡夺知识。

「──知识有时候比剑与盾更能保护性命。」

「咦？」

「这是很久以前被称为智者的人留下的话。妾身也大致有同感，但要抵达真理还差一步。」

「那是……呃……」

普莉希拉的话语太过复杂，让舒尔特越来越无法跟上。然而，面对舒尔特的困惑，普莉希拉没有想配合对方步调的意思。

无论何时，普莉希拉总是以自己的速度迈步前进。由于想持续瞻仰她那豪爽的背影，因此被普莉希拉吸引的人必须随时维持着奔跑的速度。

毕竟要是不拔腿狂奔，就无法追上从不停下脚步的她。

「────」

「──智慧可是万能的杖。不像剑与盾，智慧能在必要以外的地方派上用场。剑与盾能对土壤施肥吗？能替人疗伤吗？能孕育生命吗？都做不到，只有智慧能在所有事上成为派上用场的杖。虽然妾身靠着自己的力量前行，但不代表不会跌倒。」

「要、要是跌倒会很痛吧……」

「没错。跌倒会痛，会受伤，也会流血。不过……」

「──啊！只要有杖就不会跌倒了！」

理解普莉希拉表达的意思，舒尔特迅速举起手如此回答。听到这句话，普莉希拉满意地缓颊一笑，再度摸了摸舒尔特的头。

这次并非是使劲搓头，而是以温柔疼爱的动作。

「所以你勤勉向学吧。不是成为剑、盾或是抱枕，而是想成为杖的话。」

「遵、遵命……！啊，可是我看不懂字……」

「去找阿尔学习吧，那家伙应该也闲得没事可做。而且别看他那副模样，他应该很会教导别人，不然就把他剩下的那只手砍断。」

「真是重责大任！为了阿尔大人，我会好好努力的！」

想到阿尔失去双手的辛苦生活，舒尔特挺直背脊发出回应。普莉希拉对他的模样点了点头，突然有本书映入舒尔特的眼帘。

那是先前放在普莉希拉座椅上的书。对舒尔特而言，深红色装订与金色装饰似曾相识。

每晚担任抱枕陪睡的舒尔特知道，那是普莉希拉一大早清醒时，肯定会每天过目的中意书籍。

「普莉希拉大人，那是什么样的书呢？」

「──那本啊？那不是用来阅读的书。说的也是，比较像是备忘录吧。就算给你看，也不会有任何乐趣。」

「备忘录吗？」

听到这个陌生的字眼，舒尔特不解地歪着头。他的模样让普莉希拉拿起那本书，用手指滑过书本的装订处。

「就算你看懂了，也不会学到任何知识。或许该说，要对书籍寻求知识也得看内容本身……不过，为故事感到雀跃也是读书的喜悦之一。」

「──？可是，我是为了成为普莉希拉大人的杖……」

「对妾身来说，读书也并非单纯为了学习──嗯。」

语毕，普莉希拉便再度坐在椅子上。然后在腿上打开书本，过目着书本的内容。

「兴致来了。舒尔特，妾身稍微念点内容给你听听吧。」

「普莉希拉大人吗？哇，好期待喔！」

「哼，反应这么老实，真是个可爱的家伙。好吧……那么……」

望着舒尔特在床上正襟危坐的模样，普莉希拉开始轻声说了起来。面对这个出乎意料的难得机会，舒尔特充满兴趣地竖耳倾听。

彷佛优雅的歌声般，普莉希拉的声音滑进舒尔特的鼓膜。

而从她口中说出的故事前言，也不免流于俗套──

「很久很久以前，有个既美丽又楚楚动人的女孩。」

2

──那是个身穿奢华礼服，而且美丽又楚楚动人的少女。

「────」

仍带有稚嫩感的年幼少女，晃着如鲜血般深红的礼服裙摆，挺直背脊前进。那细长的红色眼眸、如陶瓷般透亮的白皙肌肤以及端整的容貌，在在皆散发出能料想到少女未来魔性魅力的光芒。

周围有六名侍从随侍在侧，少女大方地迈出步伐，踩着红毯前进。穿过敞开的大门后，豪华的餐厅与九名侍从迎接着她的到来。

来到铺设白色桌巾的长桌中心处后，一位侍从迅速拉出椅子，为了少女开始准备餐点。载着餐具类的推车推了过来，在少女面前配送餐点。宽敞餐厅只有少女一人使用，配置的其他人员仅仅只是处在供她用餐的立场。

「今天有什么行程？」

在准备餐点的当下，少女向身旁侍从询问今天一整天的预定行程。侍从恭恭敬敬地行了个礼后……

「用餐结束后，今天会在寝室修习课程。还有，文森大人表示想共进午餐。」

「修习课程啊……真是笼统的预定行程，不过兄长要来真是个好消息，他应该是想来洗刷先前输了沙特兰兹棋的耻辱吧。」

对于静静回答的侍从，少女以高傲语气如此回应，点了点头。侍从并没有追究少女的态度，只是维持鞠躬的姿势退后一步，回到其他侍从的队列中。

少女对这种贯彻始终的态度闭起单边眼睛，说了声「好吧」便转回正面。这时，餐点已完成配膳，第一道是冒出蒸气的汤品。

「那么，恕小的失礼。」

「嗯。」

完成配膳便开始用餐──当然没有这么单纯。

一位侍从走上前，对少女如此搭话，然后轻轻地拿起汤匙捞了一口汤，并非朝着少女，而是送往自己嘴边。

只要到了某种程度的高贵立场，就需要有人在用餐前负责试毒。

或许已经是司空见惯的景象，少女对侍从试毒没有任何反应。侍从便靠着这一匙确认味道，与是否被下毒。

基本上，提供给少女的所有餐点都会经过试毒，因此完成的料理很少会以刚出炉的形式送到少女面前。

当然她完全能够理解这是必要措施，然而──

「真是无趣。」

少女动着嘴唇说出这句话，但没有任何人听见。

无视少女这句呢喃，侍从结束试毒的工作。少女总算能够开始啜饮凉掉的汤，美丽的脸蛋浮现慵懒神色。

「────」

她舀起一口汤送往口中，然后立刻紧接着下一口，由衷表现出想早点结束这场单调用餐的心情。总之只要遵守用餐时的礼仪，在场成员没有人会对匆匆用餐指指点点。

──而且，用餐速度与礼仪规矩已经不是重点了。

「──唔？」

少女突然自唇间发出奇特的声音。

少女的手放开汤匙，发出碰撞声，直接转为抓起桌巾，用力拉扯，桌面的器皿与餐具类变得一片凌乱。

「呃啊……唔……」

少女用另一只手抓着喉咙，发出呻吟。她大大睁开深红双眼──不，眼瞳已经并非是原本的深红色，而是被以外的血红色染红。

少女流着血泪，口鼻也开始渗出血，这种逸脱常轨的景象让周遭侍从一片哗然，但还是只能从旁观望。

除了茫然若失的侍从以外，只有一个人出现截然不同的反应。那个人──先前负责试毒的侍从与少女同样，从脸部各处流出血来。

「成、功了……」

脸部流出血的试毒侍从在极度痛苦中浮现笑容，然后直接双膝一软倒卧在地，甚至没用手去支撑，这种倒地姿势证明她已经瞬间死亡。

即使与少女服下相同毒药，撑到让少女认为无害，见证过结果才倒地丧命，可说是完成了身为刺客的职责。

而这种赌上性命的执念顺利收到成果。

「呃……啊……」

少女撞倒椅子，横躺在地，直到最后手脚仍然为了求生不停颤抖，不久后终于不再抖动，餐厅恢复一片死寂。

「────」

两名死者──刺客与目标双双丧命，让整个餐厅的时间为之静止。不只是死亡的两人，侍从们也不敢随便乱动。

只要发出声音让时间再度开始流动，一切都会变成自己的责任。这种既奇妙又不明确的主观意识束缚着他们的行动。

就在这时──

「──怎么，与刺客一起死了啊。」

「────」

少女出现在餐厅入口，望着倒地的两具尸体，扫兴地如此说着。

面对现身说出这段发言的少女，餐厅内的成员皆难掩惊讶神色。这也是理所当然的，因为少女的长相与先前中毒暴毙的主人如出一辙──不对。

「────」

少女将手挽在胸前，望着倒地的少女。面貌确实有些部位与死亡少女神似，但观察细微部分便能发现差异。

如果说已故少女是有名艺术家的杰作，俯视她的少女便是连艺术家或人类都无法抵达之境界的美丽结晶。

瞠目结舌的侍从们理解到美貌的真正可怕之处。

「──普莉丝卡大人。」

站在遗体旁的一名侍从说出这个字眼。少女──普莉丝卡闻言便回过头，微微歪着头。

如同太阳般灿烂的橙色头发，以及彷佛嵌进红宝石般的细长眼眸，只要像这样在本尊面前便能一眼看出──她从出身便与凡俗世人截然不同。

「您、您没事真是太好了……」

「哼，连老套都没办法形容这句话。说起来，妾身怎么可能被这种拙劣手法杀掉。要准备能相对派上用场的替身也不便宜呢。」

普莉丝卡瞪着低下头的侍从，走到倒地的少女身旁。

替身──这是准备与重要人士容貌相似的替代者，并且由其代为处理危险的事。这个手法在算尽权谋术数的暗斗中并不罕见，替身本人也很清楚这必须赌上性命。

即使如此，也不会希望替身在痛苦中死去。既然是选择长相与自己具有共通点的替身，普莉丝卡心中也并非很安稳。

「也就是说，有人想看到妾身死去的模样吧。」

「────」

这位十一、二岁的少女望着遗体如此低语，让侍从们开始颤抖。见到少女既妖艳又凶恶的稚嫩侧脸与深红眼眸，有谁会嘲笑侍从们的反应胆小呢？

「侍从长，过来。」

「遵、遵命……」

被普莉丝卡招了招手，侍从代表走向前。瞪着比自己大了二十岁以上、紧张明显浮现在脸与肩膀上的对象，普莉丝卡只是「嗯」地闭起单边眼睛。

接着，她再度招手要侍从把耳朵靠过来。

「记得今天宅邸的人都是你挑的吧。」

「……是的，遇刺的责任都在小人身上。」

「蠢货，你以为是为了什么才会把这个职责交给你？」

「是为什么呢？」

或许以为会受到严厉斥责，侍从对这个出乎意料的问题瞪大双眼。侍从的困惑态度让普莉丝卡露出笑容。

以这个年纪的少女而言，浮现的笑容实在太过残忍且嗜虐成性。

带着这种彷佛甚至能蛊惑人心的笑容，普莉丝卡继续说：

「──只要让无能的人担任侍从长，那群蠢蛋就会闹得沸沸扬扬，以为这是能杀死妾身的好机会吧？再不把那些家伙一网打尽实在很麻烦嘛。」

「────」

就在普莉丝卡说完这句话的瞬间。

「──！」

在困惑的侍从长周围，侍从皆从怀中抽出同样的武装──挥舞短剑。

深红眼眸捕捉到这番景象，普莉丝卡随即做出决定。她一把抓起眼前侍从长胸口的衣领，让对方的身体挡在短剑挥舞的路径上。

锐利短剑挖开肉，让侍从长发出惨叫声。但短剑上似乎也涂有速效性的毒药，侍从长的惨叫声随即中断，翻着白眼倒卧在地。

普莉丝卡趁机纵身一跃，落在摆放餐点的桌面上，从自己脚下抽起白色桌巾丢向迎面扑来的侍从──不，应该说是刺客们的头上。

「────」

面对盖下的桌巾，刺客们靠着默契瞬间将桌巾切碎，但只要能瞬间阻挡视野，就已经达到普莉丝卡的目的了。

「啊──」

普莉丝卡用脚踢出餐刀，刺穿最前头的刺客喉咙的薄薄皮肤，然后补上一脚将刀身刺进更深处。

男子喉咙被刺穿受到致命伤，用颤抖的手举起短剑。但普莉丝卡冲进对方怀中，抓起对方手腕，将短剑刺进别的刺客胸前。涂上剧毒的短剑光是擦伤便能让意识陷入昏迷，要是刺中心脏附近肯定会直接毙命。

「对个小丫头在磨蹭什么！」

「觉得很棘手吗？区区尘芥毕竟只有这点程度。」

面对对方无法彻底攻陷而耐不住性子的喊叫，普莉丝卡甩动附近的椅子击飞对手的短剑。短剑发出声音在地面滑动，刺客紧追着短剑的眼球被手指一插，失去视力倒在地面，随后便被毫不留情踩断脖子。

即使势单力薄，普莉丝卡依然以压倒性的走位将大人玩弄于股掌之间。即使如此，还是难以颠覆数量劣势，空间逐渐被重整旗鼓的对手占据。

手边只有桌巾与餐具，没有像样武器也是劣势的主要原因之一。

然而──

「妾身也对亲自动手感到越来越腻了。」

从普莉丝卡身上丝毫感觉不到这种气氛，只是朝敌人投以无趣的视线，红色眼瞳让刺客们皆绷紧身体。

只要一起发动攻击，前仆后继总会有人的短剑能够击中。只要涂毒刀刃掠过身体便有可能夺走对方性命，就算对方是普莉丝卡也一样。

因此，刺客们不惜性命的战法相当正确。

只不过──

「──！」

「你们这些家伙真是一群蠢货。既然已经料想到会遭受袭击，你们以为妾身怎么还会单刀赴会？」

对于准备同时扑来的刺客，普莉丝卡的冰冷声音如毒药般渗入体内。

不知道刺客们是否有时间在脑中思考这段话的真正含意。

从被火焰吞没且无法成声便被烧死的模样实在无法判别。

「────」

试图狙杀普莉丝卡的刺客共十四名同时开始燃烧。

途中被普莉丝卡反杀的刺客也不例外，面对熊熊绿色火焰燃烧生命的梦幻景象，普莉丝卡拍了一下手。

「喔，真是不错的表演。火焰的美丽还是无法撼动，就算是用蠢货的生命作为薪材亦然──值得嘉许。」

「……荣幸之至。」

普莉丝卡望着燃烧的刺客发出称赞，有道声音如此回应。有个小小人影挡在先前试图袭击的刺客与普莉丝卡之间。

「────」

外观年龄与普莉丝卡相差无几，是个十几岁左右的年幼少女。头部长着犬人特有的兽耳，手中拿着像是从杂木林捡来的粗陋树枝。

缺乏凹凸的年幼白皙肌肤只用最低底限的薄布遮盖，模样看来莫名引人犯罪，在银色短发中只有一撮浏海呈现红色也极具特色。

她望着燃烧的刺客们，以仍然欠缺感情的眼眸回头看着普莉丝卡。

接着──

「处分完毕。您没事吧……唔嗝……」

「喂，你刚才是对妾身嗳气吗？」

「嗳气……不是，这是打嗝。」

「蠢货，这就是嗳气。」

少女缓缓地摇了摇头，普莉丝卡用手掌轻轻推了一下她的头，少女便以毫无抑扬顿挫的声音喃喃回应「好痛」。

（插图007）

接着，少女摸了摸自己头上的犬耳。

「普莉丝卡、大人……怎么样？」

「真是个笼统的问题。就像刚才说的值得嘉许，妾身毫发无伤，而且处分掉那些家伙的华丽表现也很有看头。」

「……全部都是多亏了精灵。」

少女腼腆一笑，将先前摸着耳朵的手放了下来。接着，少女掌心微微浮现出淡淡光芒。

在以玛那为媒介显现的精灵中，这种没有实体的光芒是力量与意识稀薄而被称为微精灵的种类，也有能够与人类互相沟通并缔结契约提供力量的精灵。

这位少女也是如此向精灵借助力量的其中一人。

然而，少女并非是与精灵缔结契约──

「──啊嗯。」

少女毫不犹豫地将掌心的微精灵放进口中，开始咀嚼。

见到这幅景象，普莉丝卡眯起深红眼眸，愉快地咧嘴一笑。

「不管看几次，还是觉得『吞食精灵』的用餐方式很特别。」

「唔嗝……」

见少女再度打嗝，普莉丝卡将手挽在胸前，耸了耸肩。

──「吞食精灵」是这个少女的特殊能力。并非是与精灵缔结契约，而是吞食精灵获得力量，也是篡夺者的特殊能力。

理所当然地，吞食精灵并夺取力量并非是每个人都能做到的事。这是极为罕见的资质，因此普莉丝卡也相当重视。

「──亚拉基亚，亏你有遵守妾身的吩咐。」

「……因为普莉丝卡大人这么说了。」

普莉丝卡说出少女──亚拉基亚的名字，踩着成为余烬的刺客们的遗骸，迈步走向唯一没有化成灰的遗体旁边。

代替普莉丝卡倒卧在地的少女，面带痛苦地命丧黄泉。普莉丝卡蹲在少女身旁，让她闭起眼睛，并用手指调整表情。

「就算只有一次，还是让对方成功认错人，这种死法实在是不忍卒睹。」

「那个孩子是谁……？」

「替妾身派上用场，光是这样就有曾经活着的价值了。妾身会让她回到家人身边，支付相对应的代价，这就是犒赏她代替妾身的报酬。」

向亚拉基亚如此回答后，普莉丝卡站起身，她的侧脸已经不再在意代替她丧命的那位少女了。

接着，普莉丝卡的视线从少女转向室内，望着天花板，喃喃说道：

「那么，收尾交给兄长处理吧。」

3

「所以，站在迎接客人的立场还碰到那种惨状，我妹妹还是一样残忍啊。」

访客指着餐厅的惨状，愉快地咧嘴一笑。

这位黑发青年浮现出嗜虐成性的笑容，细长的黑色眼瞳并非单纯美丽，而是富有智慧，拥有彷佛能看透这个世界深渊的妖艳光芒。

年龄大约二十岁左右，但言行与风格丝毫与乳臭未干搭不上边，那直挺挺的站姿具有从政者让他人跪拜服从的天生素质。

青年名为文森•亚伯克斯──是神圣佛拉基亚帝国贵族的一员，也是普莉丝卡•班奈狄克同父异母的兄长。

文森带着十几名随从造访普莉丝卡的宅邸。在仅仅一小时前将侍从全数杀害的普莉丝卡，与唯一生还的亚拉基亚迎接着他的到来，听完整件事的来龙去脉后，最初的感想就是开头的那句话。

对于才刚差点遭到暗杀的妹妹，这种话实在无法算是相当合适。然而──

「哪里残忍了，有虫子飞过不是拍掉、打掉就是烧掉。这么理所当然的事，妾身没有任何理由需要受到责备，应该说……」

「别嚣张到以为有资格责备妾身……你是想这么说吧？」

「就连兄长也不例外。」

即使被预先猜到发言内容，普莉丝卡仍然毫不在意。对于妹妹这种态度，文森闭起单边眼睛，并将翘起的修长双脚换边，看向普莉丝卡身旁的少女。

不仅是面无表情与感情，而且还是没有教养地呆站在原地。对于很挑剔身边装饰品的普莉丝卡而言，怎么看都是未经琢磨。

然而，文森对于妹妹不会做出无谓举动的判断能力给予高度评价，用绿色火焰将刺客烧尽也证明了她的实力。

「好吧，就不继续追问了。所以你知道这次刺客是谁派来的吗？」

「完全没有。明明手段漏洞百出，但避免延烧到源头的措施倒是相当彻底。虽然怒火中烧，还是没办法继续追查。妾身才想问兄长有头绪吗？」

「很可惜，我们完全不缺被狙杀的理由。」

被如此回问，文森浮现冷酷的笑容回答。或许因为原本普莉丝卡没有怀着过多期待，因此对这个答案并未感到沮丧，只是短短地回了一声「这样啊」。

──地点是在普莉丝卡宅邸没有受到损害的某间待客室。

餐厅仍然是一片狼借，普莉丝卡便直接迎接来访的兄长。实际上，即使听闻在妹妹宅邸有许多人丧命的事实，兄长依然丝毫面不改色。不只是普莉丝卡，文森也对这种状况驾轻就熟。

从儿少时期以来，遇刺之类已经是稀松平常。在众多同父异母的兄弟姊妹中，普莉丝卡对文森的这种胆量给予赞赏。

受到小七岁的妹妹如此评价，文森并未感到特别高兴或是有其他感想。

总而言之──

「关于宅邸我会派人处理，要是因为无关紧要的理由失去难得活下来的妹妹，对我来说也是会感到寂寞的。」

「寂寞这个理由还真是好听。不过既然是敬爱兄长的心意，妾身就心怀感激地接受吧。」

「真是不可爱。」

「加上敬爱这两个字，已经是妾身极力展现爱情的表达方式了。」

普莉丝卡举起唯一能够作为招待证明的亲手冲泡的红茶茶杯，如此夸下豪语。

听到这番话，文森对只出一张嘴的爱情表现回以苦笑，啜着递出的红茶，短短叹了一口气。

互相挖苦并试探彼此，这就是这对兄妹每次说话时必定上演的戏码。

看起来甚至像是互相厌恶的互动，但其实普莉丝卡与文森出乎意料地赏识着彼此。

会毫不犹豫地喝下递出的茶水也是最好的证据。

「──阁下！阁下！已经巡视完附近了！」

突然有道声音打断两兄妹的沉静时光。

待客室门扉由外头打开，有个个头矮小的少年大方地现出身影。与普莉丝卡、亚拉基亚差不多岁数，是个将蓝色头发绑在头部后方的细瘦少年。

虽然端整的中性容貌几乎会让人误以为是少女，但言行举止皆充满少年风格，误认性别的因素极为稀少。

少年兴奋地赶了过来后，便趴在文森坐的沙发椅背上，从文森肩头后方探出脸。

「哎呀，阁下真是会使唤人，而且工作都很无趣。我是不在意被使唤来使唤去啦，不过还是得适才适所吧。」

「少啰嗦，应该说不准对饲主说教，真是欠缺身为忠犬的自觉。」

「忠犬也是有自己的原则，要有舞台才能展现出自己的才艺。不是吗？我要站在能彻底发挥风格的合适舞台，毕竟人生有限嘛。」

对于少年扯东扯西地坚持己见的对答，文森发出叹息。接着，嘟着嘴的少年看到眼前的普莉丝卡便「啊」地张开口。

「哎呀呀，真是美丽的小姐，有对曼妙动人的眼眸。那如同红宝石般的眼瞳，映照出来的我应该是相当帅气吧。您认为呢？」

「兄长，要把小丑留在身边是兄长的自由，不过这么吵很受不了，实在不合妾身的兴趣。」

「小丑？哪里有小丑之类的人……？」

普莉丝卡将脸颊撑在扶手上，如此评论主动积极的少年。但少年本人似乎没有听懂，他闲不住地张望着室内。

「小丑、小丑、小丑……没看到呢。咦？该不会是把小狗认错了吧？如果是说小狗，正在小姐身旁打盹喔。」

「……小狗？说我吗？」

对于突如其来的话题，亚拉基亚歪头指着自己。

「对啊。不然还有谁？小狗垂下来的耳朵很可爱喔，不过就算是想引人注目，还是穿得太暴露了吧？太明显可是会吓到对方喔？」

「暴露……小狗……」

面对少年连珠炮般的耍嘴皮子，亚拉基亚朝普莉丝卡瞥了一眼。察觉到视线的意图，普莉丝卡点了点头。

「兄长。」

「嗯？」

「还是找个代替的小丑吧。」

普莉丝卡说完这句话后，亚拉基亚的身影瞬间从身旁消失无踪。

转眼间，她出现在待客室的天花板。亚拉基亚上下颠倒地踩着该处，冲向紧邻文森身旁的少年头顶。

「汪汪！」

亚拉基亚举起的手发出蓝色光芒，带着火焰准备将少年烧尽──

「真是沉不住气，不过我不讨厌这种反应，反而很喜欢喔。」

──不知何时，少年拔出的刀刃挡住亚拉基亚的手掌，完全挡下偷袭。

少年手中握着西方大国称为刀的武器，是卡拉拉基城邦特产的刀剑。少年灵活地运用刀刃，轻易地挡下亚拉基亚的杀招。不仅如此，少年拔出的另一把刀刃还抵在亚拉基亚颈项上。

「────」

要是少年挥动刀刃，亚拉基亚已经人头落地──少年甚至释放出令人如此确信的锐利剑气。而更令人惊讶的是，少年竟然能像鞘中刀刃般彻底隐瞒此种剑气。

「当他对战场抛弃的武器品头论足的时候，是我收留了他。」

「毕竟想要的武器不是那么好下手嘛。原本我想在战场上打响名号，再靠着俸禄买把不错的刀，结果就被阁下看上了。」

少年轻松地将刀刃从亚拉基亚颈边挪开，将两把刀分别收回腰间的鞘中。

「啊，要再攻击我也没关系。下次我不抵挡，闪开给你看看吧？这样说不定能更展现出我的帅气模样……啊，痛痛痛痛痛！？」

「住手，别太得意忘形了。我还不打算与普莉丝卡为敌，下次再说吧。」

文森拉着废话很多的少年的耳朵，让他闭嘴，然后毫不留情地拉着耳朵将他推到前方。

「报上名号，先让对方认识绝对不会吃亏。」

「好吧，请多指教。我是瑟希鲁斯•塞格姆多──是文森•亚伯克斯大人的心腹，总有一天会得到帝国最强的名号轰动各地，成为这个世界的主演要角。」

「────」

听到他光明正大如此报上名号，普莉丝卡首度微微睁大双眼，然后张开桃色双唇「唉」地叹出一口气。

「真是个夸下豪语的家伙，而且没有半点虚伪，真是无可救药。」

「哎呀，毕竟我没有理由说谎。对了，普莉丝卡大人……我应该没说错名字吧？普莉丝卡大人手下的那只小狗也很有潜力，虽然面对我就相形失色了。」

「……我讨厌他。」

少年咯咯地发出天真无邪的笑声，被瑟希鲁斯摆了一道的亚拉基亚气得鼓起脸颊。普莉丝卡朝亚拉基亚招了招手，摸了摸这位趴在腿上的少女的头。

接着，她就这样摸着少女的头……

「话说兄长，您刚才是说『还』不打算与妾身为敌吧？」

「听得还真仔细──没错，我是有说。」

「兄长也会与妾身一样仔细挑选话语，表示会特地这么说的意图相当明显……也就是这个意思吧？」

「真是好说话的妹妹。」

面对普莉丝卡的追问，文森似乎很愉快地咧嘴一笑。无法理解两兄妹话中的意义，亚拉基亚与瑟希鲁斯皆歪着头表示不解。

但不同于消极的亚拉基亚，瑟希鲁斯毫不犹豫地问出「这是什么意思？」。

「从气氛感觉只有两位理解是怎么回事，与今天的访问有关系吗？」

「发现了吗……不对，你应该是靠直觉吧。当然有关系，我们的感情还没有好到容许对方没事来往各自的宅邸。」

文森回应着瑟希鲁斯的问题并站起身，身高比这群青少年还修长的他，直直俯视着位于正面的妹妹普莉丝卡。

被那对黑色眼眸盯着，普莉丝卡也以红色眼眸回望着他──

「要开始了吗？」

「嗯，要开始选帝之仪了──普莉丝卡，你也做好前往帝都的准备。」

文森先暂时打断话语，然后继续说──

「父皇──皇帝要驾崩了。」

4

──神圣佛拉基亚帝国是完全支配世界地图南方部分的大帝国。

支配领地──也就是国土面积是世界顶尖，即使与并肩称为四大国的其他三国比较，占领面积仍然远超各国。

受到温暖气候与肥沃大地的恩惠，神圣佛拉基亚帝国或许可说是四国中最适合生活的环境──但这只是自然环境方面。

在丰硕大地生活的人类，当然能够强大茁壮。

依循此种大地的传统，佛拉基亚帝国内基本上已被敬强欺弱的价值观渗透，即使经过漫长的历史累积仍没有改变──不，应该说是随着历史累积而逐渐加深，帝国民众皆被这种不成文规定束缚。

而代表帝国的佛拉基亚皇帝，以及身为血亲的皇族，正是体现出这种样貌的最佳典范。

「就这样手足齐聚一堂，没想到还挺壮观的。」

普莉丝卡环视着大厅，确认每个人的长相，说出这个感想。对于普莉丝卡的感想，文森只回了一句「说的也是」。

同父异母的兄长将酒杯送往嘴边。以他为首，现场普莉丝卡与文森的兄弟姊妹可说是两手手指都数不完。

普莉丝卡的兄弟姊妹，男女总计有六十六人──如果只局限在目前还活着的，人数便会一口气减到三十一人。

「────」

兄弟有十八人，姊妹则有十三人。再加上普莉丝卡总共有三十二人，都是现任皇帝德莱森•佛拉基亚的亲生子女。

佛拉基亚帝国是许多种族互相混合的大熔炉。皇帝并不会挑选人种，向各地权贵迎娶妻妾，并生出许多孩子。这代皇帝子嗣总共有六十七人──因此被揶揄为性无能的少子皇帝。

考量到历代皇帝有一两百个子嗣是理所当然，会被如此揶揄也是无可奈何的事。

「不过站在儿孙这边就没有那么轻松了。不只有六十个兄弟姊妹，长相和名字也各自不同──要是明君能生出贤子就不会这么辛苦了。」

身为六十七人其中之一，普莉丝卡说出这个简单扼要的感想。

有些兄弟姊妹根本没有见过，就算有部分血缘又怎么样？这完全不构成相爱或是手下留情的理由。

文森所说的利害关系一致，才是独一无二的联系。

「哎呀？普莉丝卡～怎么看你一脸无聊的样子啊？」

「────」

「哎呀，这么久没见面，都不打声招呼吗？姊姊我好难过喔。」

普莉丝卡朝伴着这道娇滴滴的声音一起现身的某位少女投以冷淡目光。

这位少女留着与普莉丝卡同样极具特色的橙色头发，以及美艳垂眼。年龄大约比普莉丝卡大四到五岁，拥有凹凸有致的女性曼妙身材。

她也是普莉丝卡的其中一名姊妹，名为──

「滚开，拉米亚。听到你的嗲声嗲气就浑身不舒服。对妾身来说，你的声音比涂毒短剑还具有威胁性。」

「态度这么冷淡，还说得这么难听。为什么文森哥哥会喜欢像你这种丫头啊？哥哥，为什么啊？」

「我很欣赏她那种嚣张态度。」

面对普莉丝卡别说是冷淡、甚至具有杀气的回应，名为拉米亚的少女并没有退让，甚至毫不隐瞒敌意地露出嫣然微笑。

拉米亚从以前就会找普莉丝卡麻烦，如果只是想引起注意的可爱举动也就算了，她却是出自纯粹的敌意而展开行动。

证据就是拉米亚带着假惺惺的微笑开口：

「对了，话说你在宅邸被侍从袭击了？好可怕喔，连在宅邸都没办法放松心情，怎么这么可怜啊。」

「你这只母狗，真会睁眼说瞎话。」

把照理说不会那么容易走漏的事刻意说出口，或许是为了展现无法查出源头是她的自信。真是个狡猾的女人，普莉丝卡紧紧瞪着拉米亚。

接收到普莉丝卡的视线，拉米亚高兴地缓颊一笑。

「普莉丝卡，表情真棒。什么都不知道的可怜孩子。」

拉米亚用手抵着嘴边，出声嘲笑普莉丝卡。接着，彷佛对普莉丝卡失去兴趣般，拉米亚改为贴到文森身边。

「不过话说回来，为什么今天不是在水晶宫，而是在别馆集合呢？听说父皇的身体状况不好，不觉得很奇怪吗？」

「当然有别的意义吧。水晶宫是帝都的象征，因此不能受到破坏，所以才会选择不论怎样都没关系的别馆吧。」

「你的意思是──」

瞬间眯起眼的拉米亚正打算进一步质问文森。

然而，状况比起这段话更早出现变化。

「────」

门扉随着静谧声响敞开，大厅中众人的视线皆集中到该处。从缓缓敞开的大门，有个接近老年的白发男性穿过门现身。

手腕与脖子骨瘦如柴，皮肤也像是病人般苍白，但只有深红双眸散发出灿烂光芒。整副身体散发的并非生命力，而是霸气。

「──皇帝德莱森•佛拉基亚。」

见到这名男性的身影，普莉丝卡短短叫出他的名字。

没错，他正是神圣佛拉基亚帝国的现任皇帝，也是现场三十二名皇族的亲生父亲，德莱森•佛拉基亚。

「────」

见到德莱森步行前进，聚集的子嗣们皆跪下各自表示敬意。

先前的闲聊声彻底消失，在寂静笼罩的室内只有德莱森的鞋声不停回荡。接着，皇帝在大厅最深处模仿王座的椅子上坐了下来。

德莱森深深吐出一口气，视线朝大厅望了一眼后──

「──多亏你们前来……朕原本想如此嘉许。」

「────」

「不过能见到几个没对朕下跪的人啊。」

面对德莱森的话语，已经跪下的子嗣们惊讶地抬起脸。当他们慌张地回过头，视线前方能够见到以普莉丝卡为首的几个人没有下跪。

其中有文森与拉米亚的身影，除此之外还有稀稀疏疏约不到十个人，然而──

「你们这是什么意思？父皇……皇帝陛下亲临现场，胆敢放肆！」

「放肆？别笑死人了。如果真的是佛拉基亚皇族，妾身和你到底哪边正确就不用多说了吧？只会遵从形式的无能废物。」

「什……！？」

普莉丝卡毫不留情地反驳放声喝斥的兄长。既然有高达六十名以上的兄弟姊妹，与年长兄姊的年龄差距甚至有可能接近亲子。

面对小二十岁的普莉丝卡的回应，那名兄长面红耳赤地发出颤抖的声音。

「普莉丝卡……你、你对兄长是什么态度……」

「兄长？对喔，还有这么回事。不好意思，兄弟姊妹数量这么多，实在没几个有需要特地记起长相与名字的价值，原来你也是兄长啊。」

「──！」

兄长无法承受此种侮辱，气得满脸通红地站起身，感觉很有可能会直接扑向年少的妹妹。然而……

「──住手。」

「唔……可是，父皇……」

「对朕不敬？如果那只是做做表面，连愚蠢都无法形容。朕没有对不在朕面前跪下究责的意思──应该说，这样才好。」

皇帝这么说，阻止兄妹的争执，但内容并没有偏袒兄长，而是容许普莉丝卡的行为。

证据便是德莱森交握瘦骨嶙峋的手，望着普莉丝卡。

「──普莉丝卡，你为何不对朕下跪？」

「那还用说，当然是因为不值得妾身跪下。父皇，您真是老了。实在无法想像是立于崇尚强大教义的帝国人民顶点。」

「喀哈……」

被年仅十几的女儿如此一说，皇帝并没有愤慨激昂，而是发出笑声。

接着，他那深红眼瞳朝普莉丝卡以外没有下跪的成员瞥了一眼。

「────」

没有人否定普莉丝卡的话语。

多多少少都是持相同意见──不认同目前皇帝有需要下跪的价值。

「这样才是佛拉基亚皇族与朕的子孙。」

「父皇……！」

「隆梅尔，你刚才说了放肆吧。放肆有什么样的价值──要不要试试看？」

「试试看……？」

对于皇帝的话语，被称为隆梅尔的男子皱起眉头。就在下个瞬间，皇帝将手举到空中，用力挥动手腕。

随后，隆梅尔眼前的空间开始扭曲，突然出现了一把剑柄。

「────」

隆梅尔瞪大双眼，除了他以外的成员也吞了一口气。

出现的剑柄正是如此美丽，光是想像剑柄前方的刀身与剑鞘装饰会是多么华丽，便不禁发出吞咽声。

「──『阳剑』佛拉基亚。」

「这就是佛拉基亚皇族代代相传的宝剑……」

德莱森说出的话，令隆梅尔以宛如发烧的神情如此呢喃。他因为敬畏与兴奋绷紧表情，遵从父皇的话语发出吞咽声，走向前去。

「陛下……能、能承蒙如此重责大任，真是荣幸之至……」

隆梅尔欣喜若狂地浑身颤抖，德莱森并没有回应他的话。在周遭视线不由分说地涌现的期待感中，隆梅尔下定决心，朝空中纳在鞘里的宝剑剑柄伸出手。

──冠上帝国之名的「阳剑」，是从远古建国时代便存在的宝剑。

如同其名为佛拉基亚，只允许佛拉基亚帝国的皇帝驾驭，连普莉丝卡也是第一次见到实物。

还有「只允许皇帝驾驭」这段话代表的真正意义。

「──咦？」

当隆梅尔握着阳剑剑柄，试图从空间中拔出来时，突然发出哑口无言的声音。

这也是理所当然的事。因为以为他能拔出阳剑美丽刀身的瞬间，他握着剑的手冒出火焰，烈火瞬间将他的身体吞噬。

「──！」

被惊人烈焰吞噬，隆梅尔发出无法成声的惨叫。但喉咙与肺部一开始就被烧尽，因此根本无法成声，甚至连惨叫声都发不出来。

对皇帝下跪的成员代替隆梅尔发出拼死尖叫，但这丝毫无法弥补问题。不给予任何能够痛苦的空档，燃烧的隆梅尔倒在地毯上，烧成无法判别是仰躺还是趴卧的焦黑尸体。

仅仅过了数秒，这就是隆梅尔这名皇族被烧尽的时间。

「哎呀，有焦臭味。」

当有些人对人体烧焦的味道作呕时，拉米亚皱起眉头说出的感想可说是浅显易懂。前阵子才将侍从烧尽的普莉丝卡，也是虽吃惊却没有厌恶感。

她吃惊的原因并非是隆梅尔死亡，而是构成死因的阳剑筛选机制。

「没想到是除了皇帝以外不允许触摸的魔剑。」

在一片震惊的兄弟姊妹中，只有十人左右冷静地接受隆梅尔的真正死因。当然，身为其中一人的文森也喃喃说出与普莉丝卡相同的结论。

「父、父皇！这究竟是怎么回事……」

「──安静。」

对于见到兄弟突然丧命而惊恐的喊叫声，德莱森只喊了一声让众人住嘴。

老皇帝朝大厅望了一眼，以透彻的视线睥睨着子嗣。在多数人被深红眼眸散发的凶光震慑时，普莉丝卡突然发现。

「什、什么……？」

同样发现的另一人以没出息的声音如此说着。

眼前浮现的扭曲空间冒出红色剑柄，在普莉丝卡眼前──不，文森与拉米亚眼前也有出现。

说来奇妙，「阳剑」佛拉基亚的剑柄──从空间中出现在减少一人的三十一名佛拉基亚皇族面前。

「接下来开始『选帝之仪』。」

面对超乎想像的现实景象，德莱森以充满活力的声调说出这句话。

朽木、老皇帝、不值得下跪的盛世余烬。与先前普莉丝卡看透的此种印象截然不同，眼前德莱森的存在感宛如烈焰般令人目瞪口呆。

接着──

「『阳剑』会挑选主人，被剑选上是成为皇帝的首要资格。」

「────」

「好了，拔出形同宝剑的命运吧──这是你们无法逃离的宿命。」

皇帝──不，先皇德莱森•佛拉基亚如此说着，站起身来，他的头上也同样出现宝剑剑柄。

德莱森紧紧地握住剑柄──全身瞬间被火焰笼罩。

「────」

这就是「阳剑」已舍弃前任皇帝，并且寻求下任皇帝作为持有者的证据。

德莱森•佛拉基亚驾崩，佛拉基亚帝国的皇帝宝座无人在位。这便是由先任皇帝驾崩开始，代代传承的决定下任皇帝之仪式。

也代表着「选帝之仪」即将开始。

「──普莉丝卡。」

当所有人的目光皆聚集在父皇燃烧的景象时，文森朝普莉丝卡叫了一声。

或许先前预言前任皇帝驾崩的兄长已经知道会发生这种事，但无论如何都不重要了。

普莉丝卡将视线转向声音来源，红色眼眸与兄长的黑色眼瞳互相交错，两兄妹便相互理解了。

接着，普莉丝卡毫不犹豫地将手伸向自己眼前的剑──

「──这个世界就是为了妾身量身打造的。」

──宝剑被拔了出来。

决定下任佛拉基亚帝国皇帝的「选帝之仪」正式展开。

代表拥有皇帝血脉的兄弟姊妹，将揭开毫不留情地互相残杀的序幕。

5

──佛拉基亚皇帝，德莱森•佛拉基亚驾崩。

这件事与「选帝之仪」出乎意料地在帝国内静静流传。

德莱森被烈焰吞噬，并在子嗣面前烧死──虽然晚年的他不能算是适任的佛拉基亚皇帝，但即使如此，最后仍然展现出令人惊叹的矜持。

随着皇帝驾崩，帝国王位将会出现一定程度的空缺期间。然而，已经习惯历代皇帝更迭的帝国子民，对皇帝驾崩与王位空缺并没有太过惊讶。

惋惜伟大皇帝过世并献上默哀后，帝国子民的注意力便会转移到下任争夺帝位，也就是「选帝之仪」的胜负上。他们会在谈笑中提及皇帝子嗣的名称，以及由谁就任下任皇帝宝座，讨论得沸沸扬扬。

接着，在燃烧驾崩的皇帝面前，下任皇帝需要面对的第一道关卡──也就是挑战过握取「阳剑」资格的人，便是帝国子民瞩目的「选帝之仪」参加者。

但话说回来──

「──只有十一个人拔出阳剑留了下来。不知道该说是只有十一人，还是多达十一人，实在很难回答。」

普莉丝卡将手肘靠在扶手上拄着颊，随着吐出的气息如此呢喃。

随着「选帝之仪」揭幕，争夺下任皇帝宝座的争战早已开始进行，普莉丝卡当然也是拔出阳剑并获得「选帝之仪」参加权的其中一人。

在皇帝被烧死时，扣除已经化为焦尸的愚蠢兄长，剩下的候补人选──也就是普莉丝卡的兄弟姊妹原本还有三十人，但包含挑战阳剑与没有挑战的人在内，最后有资格的人减少到只剩十一人。

换言之，除了普莉丝卡以外的十名兄弟姊妹，都是争夺帝位的敌人。

「说是敌人真是笑掉大牙，竟然是要直到昨天为止甚至没有意识到存在的兄弟姊妹互相残杀。」

普莉丝卡展现出极端姿态，以手指轻轻撑着自己美丽的下腭。

有十一人拥有资格，除此之外不是害怕被剑烧死而没有拔剑，就是错估器量被剑烧死的愚者，胆小鬼与死人并不值得戒备。

因此，明确的敌人只有除了自己以外的十个人──其中当然也有文森•亚伯克斯。目前他是兄弟姊妹中最具有威胁性，也是最难排除的障碍，这可说是所有参加者的共识。

也因为如此──

「──居然会想结盟啊。」

「哎呀？有这么奇怪吗？在这种状况下，互相合作不是很自然的想法吗？对不按牌理出牌的普莉丝卡来说，也许不会出现这种想法啦。」

拉米亚•戈德温如此说着，那如同毒花般的涂红嘴唇露出笑容。

就连普莉丝卡的同父异母姊姊拉米亚，也是拔出阳剑的十一名候补之一。对普莉丝卡而言，她也是这个世界上最厌恶的人之一。

这种接近厌恶的情感，应该和拉米亚面对普莉丝卡时抱持的东西同质。

从前这对同父异母的姊妹便相互嫌恶，累积了许多甚至有可能演变成厮杀的剑拔弩张关系。

毕竟两人是如此交恶，在「选帝之仪」开始后，见拉米亚随即主动造访宅邸并提出这个建议，让普莉丝卡眯起深红眼瞳。

趁着她思索时，拉米亚坐在沙发上，环视着空荡荡的待客室说道：

「不过话说回来，这宅邸还真荒凉。连仆从的数量也不够……你明明喜欢搞得花枝招展，在这种地方小气看起来反而会更寒酸喔。」

「很可惜，才刚把没用的仆人全部清理干净。虽然是被某个心狠手辣的女人诓骗的蠢货，也没有那么容易找到替代品。」

「喔，心狠手辣的女人啊。那还真是辛苦呢。」

拉米亚露出虚情假意的笑容，望着自己的指甲，说出完全无心的同情话语。

考量到她在先皇驾崩场合的牵制举动，佣人们的叛乱很显然与拉米亚有关，但普莉丝卡这时并没有追究那件事。

既然没有证据，拉米亚肯定已经仔细准备好借口脱罪。这次光是能让她白费功夫准备就好，而且最重要的是──

「────」

「──怎么啦？普莉丝卡？」

「没什么，只是不论有没有佣人，应该都不可能侍奉好你这个娇娇女吧。」

「哎呀，我被讨厌了，不过我也知道是彼此彼此啦。」

拉米亚与普莉丝卡难掩厌恶地互相对望。

谈论侍奉之类的事简直是毫无意义。应该说，就算提供茶水也不会拿起来喝，如果是至亲招待的茶水更不用说，毕竟这可是佛拉基亚皇族之间的礼仪规矩。

除非是两者之间有相当程度的信任关系，或是未朝对方展现敌意的场合，才会不遵循此种礼仪规矩。

这两者都不是普莉丝卡与拉米亚之间会出现的相处模式。

就是处在互相血洗的关系，拉米亚的提议才有考量的价值。

「所以你觉得怎么样？要考虑看看姊姊的提议吗？」

「说的也是，至少可以夸奖是很超乎常理的想法──没想到会一开始就想与妾身结盟，原本以为你根本不可能做出这种事。」

「你的意思是以为我总算得到名分，可以毫不留情地修理你吗？普莉丝卡真会挑衅，我怎么可能不经大脑做出这种事呢？」

拉米亚露出冷酷微笑，与普莉丝卡同样用手撑着脸颊。模仿对方的动作，这是在对谈中引起对方共鸣的手法。

并非出自理论，拉米亚是以本能体会到这件事。

这对普莉丝卡当然没有用处，但她仍然维持同样姿势说：

「我当然不是没想过一开始就先击溃普莉丝卡，不过我还是有用脑袋思考，用这个既漂亮又形状美丽的头。」

「────」

「要是感情用事把你击溃……然后呢？后来会怎么样？做出这种不顾后果的举动实在很愚蠢，就像那时候没有挑战阳剑的那些孩子一样。对了，那些挑战后被烧死的孩子更愚蠢就是了。」

对于拉米亚揶揄死者，而且还是有血缘关系的兄弟姊妹，普莉丝卡闭起单边眼睛。

这并非愤怒，只是因为持有同样意见而感到不悦。

──到目前为止，拉米亚的意见与普莉丝卡完全一致。

虽然很不愉快，但她对于临阵脱逃与被阳剑烧死的人也怀有同样想法，以及在「选帝之仪」开始的同时，考量先解决掉最碍眼的姊妹这点也是。

与其说是不合拍的姊妹，原因当然是判断拉米亚是危险的敌人，而且是需要尽可能提早排除的竞争对手。

然而，还有比起拉米亚更需要戒备的敌人。那就是──

「──就是我们敬爱的哥哥文森•亚伯克斯。」

「……真是让人不愉快的女人。」

「我就当成是称赞吧。」

说中普莉丝卡的心声，拉米亚浮现出得意的笑容。见到拉米亚眼瞳深处隐含的杀意，普莉丝卡感到有些畅快。

至少在这场对话中──这对互相厌恶彼此的姊妹，看来不是只有普莉丝卡正在忍耐无法立刻开始杀戮的屈辱。

「为了对抗文森哥哥，除了与其他人联手以外没有别的方法。既然要联手，选择没用的废物也是于事无补，以毒攻毒就用最强的猛药──这应该是我们两个的共识吧。」

「所以你才会来提议结盟，这个卑鄙谋略确实很有你的风格。」

「说卑鄙好难听喔，请说我狡猾好吗。」

「原来如此，狡猾啊。很适合你这只女狐狸，妾身也没有意见。」

拉米亚发出如铃铛碰撞般的高亢笑声。在她那游刃有余的态度背后，能够感觉到她绝对不屈居劣势的自信。

她确定旗下的「修剪部队」不会让普莉丝卡有机可趁。

──在佛拉基亚皇族各自持有的私兵团中，拉米亚个人持有的战力「修剪部队」可说是以特别强大着称。

当然，并非是大部队已经将普莉丝卡宅邸团团包围，而是部队本身的存在便能达到吓阻效果──即使现在能像这样不受他人干涉两人独处，或是这里是普莉丝卡的宅邸，姊妹立场仍然绝非对等。

拉米亚只是看起来毫无防备，但能够确定她绝对不是「毫无防备」。

「────」

与拉米亚的战力对比，除了弱小班奈狄克家的不可靠私兵，普莉丝卡的战力只有亚拉基亚一人。

就这层面而言，这个结盟提议极为不对等，与普莉丝卡结盟对拉米亚几乎没有任何好处。面对正面冲突没有胜算的普莉丝卡，拉米亚或许能够满足让她屈服于自己的虐待心态。

「──普莉丝卡，我对你有很高的评价。我对班奈狄克家没有半点兴趣，兴趣只在你一个人身上。」

「────」

「所以我想在成为敌人前，先行拉拢你成为同伴。反正最后还是得互相残杀，因此在那之前……」

「要保护妾身避免折断手吗？真是狂妄的想法。」

「可是就算不愿意，你有拒绝的选择权吗？」

拉米亚如此说着并张开双手，晃着不符合十六岁年龄的丰满胸部，直直盯着普莉丝卡。

「我为了这天已经事先准备好了。考量到历代佛拉基亚皇帝驾崩的岁数，我觉得差不多该是时候了～虽然比想像中还要早了几年，但还在误差范围内……要是与哪个事先以备不测的人正面冲突，我也不觉得会输。只不过……」

「只不过？」

「你和文森哥哥不一样。文森哥哥不论在谁眼中都是明显威胁，不过普莉丝卡，你是看不出来的威胁。」

「────」

「我知道你很危险。可是危险到什么程度？怎么危险？等到伸出手被咬才知道是毒已经来不及了。所以……」

「想把妾身放在身边好好观察吗？」

「要在姊姊腿上也没关系喔？」

拉米亚将裙内翘起的脚换边，妖艳地抚摸着自己的大腿。这位少女带着淡淡微笑，熟知自己的美貌是蛊惑他人的武器。

只要能碰触她的肢体，多数男人不会对偏离正轨的行为感到犹豫，而拉米亚•戈德温便是具备着此种魅惑人心的魔性。

这种美色对身为姊妹且心怀厌恶的普莉丝卡没有效果，但有别于美色诱惑，拉米亚的提议具有无法立刻拒绝的价值。

因此，见到普莉丝卡无法当机立断，拉米亚满意地点了点头。

「没想到有机会对你说出这个提议──不需要现在立刻决定，我会等你的好消息喔。」

拉米亚对无法随即拒绝的反应绽放笑容，然后缓缓站起身。

她怡然自得地直接转过身背对普莉丝卡，毫无防备的模样简直像是期待着能被当场挥砍──不，她的态度更加强调普莉丝卡不会，且不能受到挑衅。

「对了，下次我会来问答案……你应该知道会是什么时候吧？」

「就像刚才说的，会等到修剪结束吧？」

「呵呵，回答得真棒。」

拉米亚仍然维持背对姿势，那令人憎恨的美丽面容滑过门扉另一侧，待客室的门扉便应声关上。

「──真是只母狐狸。」

普莉丝卡没有走到房间外目送她离开，而是望着她离开的背影如此呢喃。

反正她只会把这儿当成自家，不需要带路自己离开。在外面待命的「修剪部队」迎接她后，整个帝国便没有人能阻止她继续前进。

「……公主，这样好吗？」

拉米亚离开后，有道声音在只剩普莉丝卡一人的房间内响起，银发少女亚拉基亚从普莉丝卡的影子中冒了出来。

她是普莉丝卡的随扈，也可说是她持有的唯一战力。接见拉米亚时，她在影子中陪同出席。应该说在这种状况下，拉米亚几乎没有任何展开攻势的可能性，这种戒备除了保险也没有其他意义。

拉米亚应该也有发现亚拉基亚的存在。

「不好也不坏，现在就算出手也不会有收获，虽然是满让人火大的。」

「……至少能拿到她的头啊？」

「想想要拿多少代价来换这颗头。要是妾身没有事前吩咐，你应该已经把那家伙的头砍下来了吧。」

「……我讨厌她，看不起普莉丝卡大人。」

亚拉基亚像是不懂事的孩子说出这些话。见到她眯起的眼中透露出敌意，普莉丝卡愉快地用手撑着脸颊。

毕竟是个忠于自身感情的女孩，仰慕普莉丝卡的态度就像宠物一般，这种可爱模样也是普莉丝卡将亚拉基亚留在身旁的理由之一。

相反地，脑筋有些迟钝算是美中不足之处。然而──

「与妾身或是兄长相比也是强人所难。应该说，你会遵守妾身的吩咐。只要能好好遵守这点，就这样继续成长茁壮下去吧。」

「──嗯？好，我知道了。」

从回应声听来感觉她没有听懂，但还是努力想要听懂。普莉丝卡认为这样就可以了，而且……

「她是个会动歪脑筋耍小手段的女人，暂时故意装成照她的意思行动吧。亚拉基亚，你也不要轻举妄动。」

「────」

「亚拉基亚，回答呢？」

对没有回应声感到不解，普莉丝卡皱起那美丽的眉头。面对这个问题，亚拉基亚摸着自己仅仅只有一撮红色的浏海，回答道：

「……大人对我这么没用很生气吗？」

「没用？」

「……因为我输给文森大人那个蓝头发的随从。」

「──喔，你说那件事啊。」

听到亚拉基亚担忧地这么说，普莉丝卡回想起前几天──陪同文森前来宅邸的那名少年剑士，以及亚拉基亚败在他剑下的事。

基本上，亚拉基亚不会执着于普莉丝卡以外的事。这种个性来自于「吞食精灵」的特殊能力与战斗力，自信心受到年龄相近的少年威胁，让她感到十分害怕，担心是否会因为无法派上用场而被抛弃。

然而──

「蠢货。」

「好痛。」

沮丧地垂下的额头被普莉丝卡的手指弹了一下，亚拉基亚顿时泪眼汪汪。普莉丝卡对她这样的表情感到怜爱，然后再度说了声「蠢货」。

「妾身还没有愚蠢或疯狂到会把不能用的工具放在手边。亚拉基亚，掂掂自己的斤两，别擅自贬低妾身的工具。」

「……连我自己也是吗？」

「你以为你是属于自己的东西吗？」

「────」

这句话让亚拉基亚瞪大双眼，连忙左右摇了摇头。稍长的兽耳也跟着摇晃，简直就像很有精神地摇着尾巴似地。

实际上尾巴也是剧烈摇晃，看来已经调整好心情了。

「话说，普莉丝卡大人……修剪是什么？」

「修剪就是为了花树成长修掉不必要的枝叶，简单说是为了正常执行『选帝之仪』的杂事。妾身是不想插手管这些杂事，不过呢……」

「不过？」

「拉米亚应该会带头处理这些事──毕竟是个低俗卑劣的女人。」

6

──「选帝之仪」是佛拉基亚帝国皇帝更迭时必定举行的仪式，内幕则是血亲之间的残酷厮杀。

如同先前所叙述的，佛拉基亚皇帝向帝国领土各地权贵迎娶妻妾并生出许多孩子，再从拥有皇帝血脉的多数子嗣中选出下任皇帝。

「选帝之仪」是从皇帝驾崩为开端，由拥有成为下任皇帝资格的人互相血洗到剩下最后一人的继承战──也就是说，皇帝必定得杀害与自己有相同血缘的兄弟姊妹才能继承帝位。

──帝国子民须剽悍强大。

这是传遍整个佛拉基亚帝国的教诲，也是帝国子民的基础思维。

佛拉基亚皇帝与皇族必须身先示范此种铁血纪律，而这也是「选帝之仪」无法避免流血的仪式本质。

「──就算是这样，持续从几百年前延续到现在的旧习实在是没有创意。观念也得与时俱进，凡事都得适应现况才行。」

巴罗伊•费兹如此说着，将酒杯内的葡萄酒送往口中。

巴罗伊二十七岁，在先帝德莱森的子嗣中年龄恰好位于中间。超过六十名的兄弟姊妹中，最年长的是四十岁，最年少则是十岁──但这些血脉相连的兄弟姊妹关系绝对不能算是融洽。

既然生为佛拉基亚皇族，必须随时将总有一天会举行的「选帝之仪」放在脑海中，因此兄弟姊妹之间很少会培养出良好感情。

亲近会涌现感情，带着感情就会无法对终将残杀的对象冷酷无情。

因此手足们害怕这点，互相疏远厌恶，憎恨着彼此。

「这也是很刻板的观念──拉米亚，你也是这么想的吧？」

巴罗伊回过头，看向前来访问的妹妹──拥有美丽红色眼眸的拉米亚。

对于这声呼唤，拉米亚露出淡淡微笑。

「是呀，真佩服巴罗伊哥哥的想法。到底是什么时候开始这么想的呢？」

「当然花了不少时间。毕竟这个可恨仪式本身持续了这么多年。要是空手触摸生锈的锁链，有可能必须切断握着锁链的手。」

表示事前需要经过万全准备。

巴罗伊看着似乎佩服地点着头的拉米亚，紧紧地握着自己的手。在德莱森被烧死的现场，他并未同样握住阳剑的剑柄。

巴罗伊的立场是在那个场合拒绝参加「选帝之仪」。

另外还有九人与巴罗伊同样拒绝阳剑，失去资格──除了这些人以外皆挑战阳剑，有十一人生还，有十人失败被阳剑烧死。

包含一开始被烧死的隆梅尔在内，那天失去了十一名兄弟姊妹的性命，老实说他想尽可能减少不必要的牺牲。

「所以我才会来找拉米亚缔结密约。」

「──当我得到帝位后，包含巴罗伊哥哥在内，让拒绝『选帝之仪』的兄弟姊妹得到庇护。」

「嗯，没错。为了这件事，我已经说服另外九个人了。」

拉米亚喃喃说出的话语让巴罗伊点了点头。

包含巴罗伊在内可说是落第的十名兄弟姊妹，从「选帝之仪」开始前便决定放弃资格。结果最后没有成功说服的兄弟们挑战阳剑并被烈焰夺走性命，但这应该不会是无谓的抵抗。

毕竟成功阻止了十人原本应该会被阳剑烧死的命运。

如同前面所述，原则上佛拉基亚皇族的手足间感情不算融洽，但巴罗伊亲自身为例外展开行动。他与其余兄弟姊妹积极交流，营造出能够替对方解决烦恼或是商量问题的关系。

──一切都是为了「选帝之仪」。

「不过为什么会选上我呢？虽然说这种话有点奇怪，我在兄弟姊妹之间还算是小丫头吧？」

「那还用说。拉米亚，因为我刚才的想法就是你给我的灵感。」

「我吗？」

「没错，所以我觉得如果是你，应该能沟通。是你还小的时候，问过有没有不让兄弟姊妹互相伤害的方法。」

当年轻的巴罗伊还在摸索是否有方法的时期，年幼妹妹这句如虚幻梦想般的呢喃，令他简直如同受到天启一般。

后来巴罗伊拼命思考奔走，才走到了今天这一步。

「虽然『选帝之仪』照着计划进行，但你获得胜利的结果仍然不会被撼动。以我为首的十名手足会协助你，只要这样就能……」

「──也能赢过文森哥哥。对吧？」

「嗯，没错。」

听到文森这个名字，巴罗伊感觉到喉咙干渴，点了点头。

对巴罗伊而言，文森•亚伯克斯也是具有血缘关系的同父异母弟弟。然而，他实在太过优秀杰出，不论好坏都很难实际感觉到他是兄弟。

不只是文韬武略，文森还有极为清晰且深谋远虑的思绪，靠着己身的才能与实力，重整位居佛拉基亚贵族最底层好一段时间的亚伯克斯家，拉抬到上级伯爵的地位。

没意外的话，文森是最接近皇帝宝座的人。就这层意义而言，巴罗伊应该找文森商量这件事，然而──

「无法期待文森对兄弟手下留情。」

「而且对只靠自己的力量就能取胜的对手，很难提出交涉吧？」

「拉米亚真的很聪明。」

「嘻嘻，我没有生气喔。因为是看上我是紧接在文森哥哥后面有机会的人对吧？感觉不差喔。」

听到拉米亚的自负、自尊心以及喃喃说出的真心话，巴罗伊不禁露出苦笑。

实际上确实是如此。除了文森以外，获胜机率最高的应该就是拉米亚。

当然除了这两人以外，另外九名候补也相当优秀，但巴罗伊认为拉米亚最有可能与文森抗衡。

──虽然还有另外一个在意的妹妹，不过她与文森也是同样特质。

「就算年幼，却充分具有身为佛拉基亚皇族的资质……」

要是「选帝之仪」能晚五年举行，那位妹妹应该也能在竞争帝位的舞台整装待发，但现实并没有如此顺利。

正因如此，巴罗伊才会朝拉米亚提出合作的提议。

「对了，巴罗伊哥哥，我想聊聊以后的事喔。」

「──嗯？不好意思，我在想事情。你要聊以后的事吗？的确很重要。」

九名兄弟姊妹已经被迫放弃争夺帝位的资格，也需要对他们转达以后的动向。

目前巴罗伊还没有对其他九人表明与谁联手。

这个谋略很有可能会破坏「选帝之仪」这个佛拉基亚帝最重视的仪式。不知道会从什么地方泄漏出情报，必须慎重行事。

话虽如此，辛苦得到回报的日子也越来越近──应该能完成当初的约定。

「虽然说是为了帮助兄弟姊妹，不好意思要你挑战阳剑。要是在那个时候……」

「连我都被烧死就麻烦了呢。」

「真的是这样。不对，这不是开玩笑的。」

巴罗伊摇了摇头，对差点露出苦笑的自己如此告诫。他再度将葡萄酒倒进空酒杯，打算滋润先前便感到干渴的喉咙。

或许因为完成重责大任的成就感，喝酒的速度还算满快的。就算到了现在都还想逃避骨肉手足互相厮杀的现实吗？

他发出「咕噜咕噜」的声音将酒咽下喉咙──

「话说回来，巴罗伊哥哥。我稍微在想一件事……」

「嗯？什么事？」

「我想，人类要发挥出比身体更强大的力量，应该需要愤怒与拼死挣扎吧。」

「愤怒与拼死挣扎……？」

巴罗伊不懂妹妹为什么突然说出这番话，于是坐在沙发上看向拉米亚。拉米亚仍然维持原本的姿势，竖起两根细细手指点头说「对对，没错」。

「巴罗伊兄长聚集的九个人……毕竟是这种状况，大家肯定会拼命互相合作对吧？不过，里面也是会有害怕的人吧？」

「……毕竟是不擅长斗争的一群人。」

「不过要是没办法团结，就无法完成我们的目的，所以需要能淡忘这种胆怯的强烈愤怒。举例来说……」

「举例、来说……？」

感觉拉米亚令人酥麻的声音似乎越来越远。

巴罗伊感觉到脑袋沉重，世界变得越来越稀薄，脑袋昏昏沉沉地前后摇晃，而且口一直很渴。他不满足地倒着酒，酒从杯中满溢而出。

接着酒杯倾倒，红紫色液体在地毯上逐渐扩散──

「──像是举例来说，大家信任的温柔哥哥被卑鄙陷阱陷害，失去性命。」

听不见拉米亚的声音。

喉咙好渴、好渴、好想喝酒──想喝拉米亚带来的酒。

「────」

好想喝酒──

7

拉米亚俯视着倒在被酒浸染的地毯上的巴罗伊。

这位兄长已经停止呼吸，没有半点动静。

拉米亚突然将伸出的指尖抽了回来，拿起自己的酒杯，把没有喝过半口的液体倒在地面的巴罗伊身上。

──结果兄长还是毫无动静。

「哎呀，真让人吃惊……没想到真的没做任何准备。」

原本直到最后都没有舍弃巴罗伊装死的可能性，结果连这种戒备都变得毫无意义，巴罗伊便是在如此毫无戒心的情况下突然失去性命。

拉米亚将空酒杯丢向地面，眯起红色眼眸望着兄长的遗骸。

「花了这么多年准备让自己白白送死，真是个愚蠢的哥哥。」

不知道他误会了什么，拉米亚是真的无法掌握巴罗伊的想法。

他说是拉米亚给了他启发，但从拉米亚的角度而言，只是装成纯真妹妹从背后推了他一把，而且还是推向对自己有利的方向。

结果没想到能把竞争对手减少了十人。

「反正是触碰阳剑也会被烧死的十个人就是了。」

只不过，她无法理解巴罗伊只因为有血缘关系就想提供协助的思维，或许该说，想拯救他人这种傲慢想法，是有力量的人才能容许进行的游戏。

当他想对强者阿谀奉承并寻求温情的时候，巴罗伊就已经舍弃了实现自己愿望的最佳方法。

「所以你才会这样死掉啊，巴罗伊哥哥。」

（插图008）

──帝国子民须剽悍强大。

这是佛拉基亚帝国的不成文规定，也是认同强者有权虐待弱者的铁血纪律。在这种纪律面前，即使身为佛拉基亚皇族，弱者还是只能被强者吞噬。

而弱者被吞噬后的「死亡」，只能被强者的理论自由利用。

「──阁下，已经顺利镇压完毕了。」

从俯视着死者的拉米亚背后，传来一道男性的沙哑声音。

拉米亚身为被招待到巴罗伊宅邸的客人，待客室出现的这个人并非是宅邸成员，而是与拉米亚有关的人。

这名老龄男性白发苍苍，嵌着理智眼瞳的脸上布满深深的岁月痕迹。他将拉米亚称呼为阁下，这是佛拉基亚帝国最高级的尊称，而这个人便是拉米亚•戈德温阵营的作战参谋──

「──贝尔斯特兹，辛苦你了。那里应该没问题吧？」

「毫无窒碍。一切如同阁下指示，巴罗伊大人只有在宅邸配置最低限度的人员。」

「喔……这样啊……虽然是有血缘的兄妹，实在是没什么好替他辩护的了。」

「────」

名为贝尔斯特兹的老人，恭敬地低下头不发一语。

有能的人不会随便开口说话。虽然拉米亚厌恶老人，但原因是出自于很多老人庸碌无能。如果是有能老人，存在并没有任何问题。

毕竟老人总是会立刻开口说话，原本拉米亚认为让老人闭嘴绝对不会是坏事。然而……

「就这点来说，还是得佩服父皇这么干脆选择赴死，要是死前还丢脸难看，就连全盛时期的功绩也很容易蒙上阴影，实在是不想变成这种后果呢。」

不论年轻时多么强盛，年老会让人变得庸碌。因此对于演变到这种地步前替换顶点的帝位承袭制度，拉米亚深表赞同。

当自己老后，知识与美貌跟着衰退前，希望也能如此让生命闭幕。

「不过我是打算尽可能延长啦。」

「──那么，之后是否也依照计划继续行事呢？」

「嗯，就那么做吧。」

贝尔斯特兹并没有陪拉米亚谈心，而是询问接下来工作的许可。拉米亚没有追究，朝着他点了点头，闭起单边眼睛。

巴罗伊倒下后，被他说服的愚蠢兄弟姊妹们顿时群龙无首。

既然已经没有参加「选帝之仪」的资格，走投无路的他们只能对新领袖──也就是对拉米亚言听计从。

「毕竟是巴罗伊哥哥聚集的狐群狗党，应该都是一群没脑袋的家伙。只要让他们听到哥哥的死讯，应该就能轻易将他们收服了吧。」

与错估自身力量挑战阳剑而被烧死的手足同样愚蠢。

这是拉米亚对巴罗伊的真实见解，不过这种愚蠢替拉米亚带来了有利的结果。就这层面而言，这条命确实具有价值。

「我说巴罗伊哥哥，其实我不讨厌哥哥啦。」

在离开房间前，拉米亚回过头看着兄长的遗体，对面部朝下的巴罗伊这么说。

当然没有回应，拉米亚也没有特别希望他回答。

这并非是忏悔或道歉，只是单纯的报告。

「只是哥哥最容易被小妹妹的话感化，容易操控而已。」

报告这是从小便开始准备的布局其中之一。

只朝死者抛出这句悼念的话语后，拉米亚将残局交给低头的参谋收拾，悠然自得地离开房间。当她穿过门并搭上龙车时，甚至已经忘了兄长的长相。

接着──

「那么，要开始修剪了──好期待接下来的事喔，普莉丝卡。」

拉米亚嫣然一笑，注意力已经转移到下个对象上了。

8

──换言之，「选帝之仪」便是帝国内部引发的内战。

毕竟是佛拉基亚皇族凭借己身战力与权谋术数争夺下任皇帝宝座，因此惯例上整个国土都是一决雌雄的战场。

理所当然地，内战期间与其他国家的关系会变得更为紧张。

既然无法避免国内混乱并损失国力，这也是理所当然的结果。

数十年前，邻国露格尼卡发生大规模内战时，也是同样戒备着以佛拉基亚为首的其他国家侵略。就和当时的状况一样。

而这绝对不会是唯一的原因，但以「选帝之仪」为开端的内战基本上都会很快结束──毕竟不能让皇帝宝座空着整整一年。

或许因为这种思维，「选帝之仪」再怎么长都会在一年之内分出胜负。

也就是说，这代表着──

「──现在可以说是『选帝之仪』的高潮。」

普莉丝卡望着完成的包围网，将红色扇子抵着自己的嘴唇，如此喃喃说道。

在山丘摆出的阵型中，班奈狄克家拥有的私兵团在普莉丝卡周边严阵以待。这些士兵穿戴着由普莉丝卡喜好的红色统一制作的铠甲，但缺乏训练与实战经验，要称为精锐还是不太可靠，只有士气仍然相当高昂。

「庸俗只要乖乖听从妾身的指示就好。亚拉基亚，你在吧？」

「……嗯，我在旁边。」

听到普莉丝卡的呼唤，亚拉基亚从赤备队私兵之间现出身影。见到少女突然出现，完全没有察觉到气息的私兵团顿时阵脚大乱。

普莉丝卡举起手制止惊慌的众人，看往现出身影的亚拉基亚。

她的服装与平常同样暴露，手中拿着细树枝维持备战状态。虽然装备比起全身铠甲的私兵们令人无法放心，但亚拉基亚是有合理原因才会采用此种装扮。

虽然以前曾经被陪同文森的少年剑士揶揄，不过，亚拉基亚是为了最大限度发挥出「吞食精灵」的特殊能力，才会露出大部分肌肤。

据她所说，微精灵喜好与自然融合，会远离人类经手的物体。

因此亚拉基亚暴露出肌肤，以接近裸体的穿着将微精灵吸引到具有「吞食精灵」之特殊能力的自己身旁作为粮食。

一切都是亚拉基亚为了最大限度发挥出自己的能力。既然有需要暴露出肌肤，普莉丝卡认为要怎么裸露都没问题。

「会说这样丑陋的人真是匪夷所思。」

「──公主？这是什么意思？」

「是说你很美丽，值得妾身鉴赏的程度。」

「……谢、谢谢？」

突然被称赞容貌，亚拉基亚一副无法释怀的模样歪着头，普莉丝卡也不打算继续谈论这个话题。

毕竟不是能一直闲聊的场合。

「阁下！有事禀告！」

传令兵如此说着，来到普莉丝卡的所在处。

传令兵摇晃着一身红色铠甲，穿过私兵之间，跪在普莉丝卡面前献上书简。亚拉基亚收下书简，解开绳结递给普莉丝卡。

浏览过收下的书简后，普莉丝卡发出「哼」的嗤鼻声。

「是谁要你拿过来的？」

「是戈德温家的参谋，贝尔斯特兹•彭达冯伯爵！」

「贝尔斯特兹……那个老骨头啊。」

将浮现出的长相与名字互相对照后，普莉丝卡闭起单边眼睛。

基本上普莉丝卡不会记得不屑一顾的人。既然会留在普莉丝卡的记忆中，表示贝尔斯特兹是值得牢记的对手。

拉米亚喜好心狠手辣的谋略，虽然她本人对恶魔般的谋略也有资质，但支持她发挥这种才能的人也带来不少影响，贝尔斯特兹便是其中一人。

是灌溉拉米亚这朵毒花并使其盛开的园丁之一。

「公主，信上写什么？」

「不是很重要的事。接下来开始攻城后，妾身负责殿后。」

「殿后……」

「就是在后面观看战况。」

普莉丝卡说出书简内容后，亚拉基亚的表情缓缓出现变化。一开始是不解地皱起眉头，接着是瞪大眼睛，最后则是不悦地鼓起脸颊。

「……公主，我们是不是被看扁了？」

「应该是有想让妾身丢脸的企图吧。那只母狐狸在找碴方面不会留情，但没有鲁莽到会错失胜机。」

「所以呢？」

「实际上应该是认为不需要借助妾身之力便能获胜，或许该说从布阵就能让人联想到了。」

普莉丝卡如此安抚着气呼呼的亚拉基亚，朝着四周轻轻抬起下巴。随着她的动作，亚拉基亚的视线被引导到许多军旗的方向。

与普莉丝卡阵地同样，复数阵地配备着私兵团──是响应拉米亚•戈德温号召聚集而来的另外六名参加者混编部队。

不知道是像普莉丝卡一样提议合作，也有可能是其他条件，总之拉米亚向其他四名兄弟谈妥并策动这次的计划。

而计划内容就是──

「──文森•亚伯克斯包围网。」

亚伯克斯家拥有的城堡位于远处森林围绕的区域。

身为包围网其中一员，普莉丝卡从矗立的断崖俯视着被混编部队包围的城堡，眯着眼睛望着最具威胁性的兄长濒临穷途末路。

这是最合理的策略。

只要能将最接近下任皇帝宝座的文森早日踢下盘面，不惜与即将真正断绝关系的兄弟姊妹联手。

连普莉丝卡都处在参与计划其中一人的立场。

双方具有压倒性的战力差距。虽然普遍认为攻城战中，进攻方需要防守方的三倍兵力，但就单纯兵力差距有五倍以上。

训练程度低落的普莉丝卡私兵团能维持高腾士气也是理所当然的事。只要知道自身处在压倒性有利的情况，便没有任何害怕怯懦的理由。

虽然令人不满，拉米亚的计划在形成包围网这层面没有半点破绽。

再来就是──

「──要看兄长怎么在那只母狐狸做出的狩猎场中抵抗了。」

9

──拉米亚•戈德温是个非凡天才。

这是加入戈德温家「修剪部队」士兵们的信仰。

「修剪部队」身穿统一款式的铠甲，双手拿着大剪刀，可怕程度在佛拉基亚帝国广为人知。

拉米亚威名远播的时期，要追溯回七年前年仅九岁的时候。

当时戈德温家旗下的中级伯爵引发叛乱，约有一半领地被夺走而受到沉重打击。

在尊崇强者的佛拉基亚，反骨的狼性也会比向猪宣示忠诚更受欢迎。因此没有外人想营救苦于镇压叛乱的戈德温家。

颠覆戈德温家的劣势并一口气镇压叛乱的人，便是拉米亚•戈德温。

她让准备两败俱伤的当家以生病为由隐居后，便取而代之掌握家中实权，活用智谋使中级伯爵兵败如山倒，甚至揭发出唆使中级伯爵叛乱的幕后黑手，处以在帝国广为流传的极刑。

当初为了镇压叛乱编制的「修剪部队」，后来成为了戈德温家的王牌。

所有成员身着看不见脸部的装备，携带着凶残大剪刀，毫不留情地将敌人剪碎。这种破坏人类尊严与战士矜持的残酷举动，以及对敌人凄惨的报复行为瞬间传遍整个帝国，让拉米亚•戈德温声名大噪。

要让拥有正常思维的部队彻底成为无血无泪的冷酷士兵，便需要接近支配的崇拜与信仰。

这位少女做到了，因此「毒姬」拉米亚•戈德温被尊崇为天才。

跟随「毒姬」并替她实现梦想，便是「修剪部队」的夙愿──

「────」

虽然这是半放弃思考并被命运论囚禁的思考模式，但实际上不这样思考便无法维护自己的精神──正常的心态是无法维持「修剪部队」的。

将失去理智且逸脱常轨的行动视为正义，并付诸实行。

这毫无疑问是在上位者的资质与特质。

因此──

「──杀掉文森•亚伯克斯！为了拉米亚大人！」

「──为了拉米亚大人！！」

「修剪部队」异口同声地发出咆哮，一口气朝敌阵发动猛攻。

搭配「修剪部队」冲锋，混编部队也朝亚伯克斯城堡冲刺。

踏步声踩出轰然巨响，在大地彷佛摇晃的错觉中，亚伯克斯私兵团没有任何动静。虽然固守自身城池是常规战术，但以这种战力差距而言可说是下下策。

或许固守城池并非是决心奋战到底，而是放弃与绝望迫使他们做出这样的选择。

既然如此，这种绝望也只会成为让「修剪部队」的冲锋变得更强的原因之一。

「──受死吧！！」

率先冲锋的首群士兵随着咆哮声冲进敌阵──

「──哎呀，各位真是有气概呢。我不讨厌，反而很喜欢这样喔。」

瞬间，带头的士兵误以为有道强风刮过身边。

「某种物体」以超越眼睛能够掌握的极限，甚至会误认为风的压倒性速度从正面冲了过来。

然而，被风刮过的结果却明确得无从误认。

「──啊。」

视野突然昏眩地开始摇晃，「修剪部队」多数士兵停下脚步，抛下大剪刀，用手撑着自己摇晃的头，但还是没有办法。

因为，支撑头部的脖子已经被俐落地一刀斩断。

「────」

头部没能受到支撑，嘴唇发出无法成声的声音。

被砍断头的集团还没倒下，便被穿过的后续部队撞倒、踢倒、踩踏，脑袋就这样与身体直接分家。

当后续部队发现前头集团被砍倒时已经来不及了。

「战场上除了直觉、判断能力、剑术，在各种层面上最重要的还是速度。我在这方面还满有自信的，各位反应会不会太慢了啊？」

银色刀光令死亡蔓延，与惊恐传遍周围的速度没有太大差异。

发现时已经被斩杀，当部队彻底理解到有个可怕剑客闯进来时，被斩下的脑袋已经无法用十位数计算了。

「哎呀哎呀，厉害！不愧是阁下！很清楚只要赐给我期望的刀，在战场上就会发挥出加倍的战果啊！」

蓝发少年如此说着，将刀身的血挥掉，快活地笑着。

这位优雅美少年身穿亮桃色的和服与草履，腰间佩戴着两把刀──散发出浓厚的剑气，一眼便能看出他是带来多数死亡的死神。

「修剪部队」笼罩在战栗中，一起将大剪刀朝向少年。

「别大意！包围他，确实阻断退路！」

「哎呀，重整态势的速度很不错，真棒。我也觉得好不容易等到的表现场面，对手如果和稻草捆没两样就没有看头了。毕竟负责被打败的角色鼓不起干劲，主角的活跃表现也会显得黯淡无光嘛！」

「脑袋有问题的小鬼……！你是文森•亚伯克斯的……」

「说我脑袋有问题真难听，所以我回答后者的问题吧。答案是肯定没错，正是如此！」

少年环视着包围自己的「修剪部队」，大大扭了扭头，并举起刀。那不合实战的姿势并非是为了战斗，而是为了表现自己。

而实际上，少年用草履用力蹬着地面，朗朗地放声喊道：

「我是瑟希鲁斯•塞格姆多！是文森•亚伯克斯阁下的心腹，总有一天会被誉为佛拉基亚头号剑士！然后成为这个世界的主演要角！我要砍倒你们，把帝位呈上给阁下作为祝福！」

「────」

「咦？照预定来说，这时候应该是要拍手喝采……不用害羞喔？」

少年歪过头，绑在身后的头发跟着摇晃。

然而，名为瑟希鲁斯的少年并没有迎来期望中的拍手声，反而是被看扁的「修剪部队」爆发出怒气。

见到勇猛士兵将大剪刀敲出残酷声响冲了过来，瑟希鲁斯用手指搔了搔额头。

「在对方报出名号前，自己先报上名号果然不太好吗？」

他一面想着脱线的解决方式，挥舞着刀迎战大剪刀。

10

「──戈德温家的精锐部队与亚伯克斯方开始交锋了！」

战事终于展开，从下方传来撼动空气的呐喊声。

以极为没品的拉米亚家私兵团「修剪部队」为首，文森包围网确实地逼近亚伯克斯家的城堡，预计持续推进战线。

但即使如此──

「原本应该会早早突破的前线居然会瓦解，都是靠着那个剑士的力量吗？」

普莉丝卡发出声响阖起扇子，用深红眼睛仔细观察着最前线的战况。

原本遥远的战场只能看到豆粒大的人，普莉丝卡眼中映照出某个人发挥出压倒性的剑技，以惊人剑术压制战线。

那是文森在「选帝之仪」开始前特地前来展示的秘密武器。原本只知道他比亚拉基亚还强，没想到……

「──这样看下来真是横扫千军。」

如同字面叙述般以一挡千，只靠一个人抵挡如此浩荡军势，真是难以置信的战果。

面对文森固守城池，拉米亚准备了五倍的兵力。但兵力差距的理论只能套用在士兵对等比较的情况，如果有人能够以一挡千──以单独一人便能发挥出千名士兵的战果，便完全无法以理论评断。

「……摩拳擦掌。」

「亚拉基亚，你这么在意他吗？」

与普莉丝卡看着同样目标，被迫待命的亚拉基亚咧起嘴。她回答普莉丝卡的问题：

「嗯，没错。我可以这样说吗？」

「虽然想说可以，但还是不行。继续待在妾身身边，也许在这个战场没办法与那个剑士再度交手。不过……」

「……不过？」

「──妾身还是需要你的力量。」

普莉丝卡斩钉截铁地这么说，亚拉基亚原先不满的表情顿时改变。她眨了眨眼睛后，先前的笑容便切换成战士神情。

普莉丝卡满意地点了点头，命令附近的士兵编组小队。

从目前进行激战的两军人数来看，这只是微乎其微不影响战况的误差程度。普莉丝卡带着这支小队，从阵地做好出阵的准备。

接着──

『普莉丝卡，你要去哪里？』

「────」

突然传来的声音，让普莉丝卡闭起单边眼睛。

周遭士兵没有发现普莉丝卡的反应，对传来的声音也毫无反应。毕竟他们并没有听见这道声音，而是直接传进普莉丝卡的意识中。

这是名为念话的单方面传达讯息，能够做到的知己只有一个人。

──是与普莉丝卡处在同样立场，也是参与这个战场的「选帝之仪」资格者。

『真是没礼貌，帕拉迪欧。谁准你直接对妾身说话？』

『──没想到对妹妹说话还要有人准许。』

虽然要习惯念话需要掌握诀窍，但普莉丝卡随即朝对方如此回应，能够感觉到发话方有些惊慌。

目标应该是突然发出念话，借着让对方惊慌，在精神层面取得优势吧。

『做法真是卑鄙，擅长戏法和小把戏的魔眼族只能做到这种程度吗？』

『……拉米亚应该是命令你殿后，别轻举妄动。』

『听话的人偶还真乖，不然要妾身换上你的衣服也没问题──不过妾身原本就不打算任那只母狐狸摆布。』

『……你想在这种状况下叛变吗？』

『哈，别引人发噱了。妾身是要去补上漏洞。』

声音源头──帕拉迪欧的困惑随着念话传了过来。

在心中对话的念话很难隐瞒心情，这是很明确的缺点。只要精神越脆弱，便会借着念话变得越发明显，帕拉迪欧也不例外。

或许该说，帕拉迪欧对普莉丝卡的侮辱与嘲弄也毫不隐瞒地传了过来。

『听不懂刚才那番话的家伙，妾身没有解释的意思，想报告就去吧。』

『居然不把兄长当成一回事。普莉丝卡，我不喜欢你如此不敬。』

『别担心，刚才那番失言让妾身决定要亲手把你的头砍下来了。』

普莉丝卡露出残酷笑容，带着不屑情绪单方面打断念话。即使帕拉迪欧的特殊能力是直接闯进对方的意识中，但他并没有展开反击。

对于这种懦弱态度，普莉丝卡心中暗自嘲笑着「真是个胆小鬼」。

魔眼族是魔眼寄宿于体内，并借此获得特殊能力──虽然本身是很稀有的才能，但配上那种个性只能说是暴殄天物。

「……公主？」

「没什么，只是好好教训了一顿以为是监工的告密者。准备好了吗？」

亚拉基亚对这句确认点了点头，普莉丝卡眯起深红眼眸，并打开原先阖起的扇子。扇子的破风声听来格外响亮，让少数人的目光聚集在普莉丝卡身上。

在这些视线注视下，普莉丝卡朝着战场──大军激烈厮杀的最前线完全无关的方向指了过去。

接着──

「──接下来要讨伐文森•亚伯克斯，你们只要跟着妾身就好。」

11

「──阁下，请注意脚边湿滑。」

身材细瘦修长的黑衣青年──奇夏•哥尔特如此提醒着对方注意脚边，在前方引领着身旁走着的美青年，一同穿过苍郁茂密生长的树林缝隙间。

在壮硕精锐的围绕下，奇夏走在最靠近主人的身旁，心中对抽到下下签感到十分悔恨。

原本奇夏并非帝国贵族，或出身于侍奉亚伯克斯家的家系。

身为平凡帝国居民的他，恰巧帮助了皇子在路旁无法动弹的龙车，才会偶然成为了文森的随从。

为了让车轮卡在沟缝中的龙车脱困，奇夏展现出的数学知识让这位奇特的佛拉基亚皇族感到相当中意，因此便被当场收编。

后来即使对此感到不适任，奇夏还是跟在文森身旁。

而他最无法习惯的莫过于这种战场──不，是称为「选帝之仪」的帝位继承战争，不知道过了多少个扪心自问「自己为什么会在这里」的夜晚。

即使如此，没有其他人能够担负起这种重责大任。不只是对做出详细指示感到很麻烦，也有主人信任的问题。虽然瑟希鲁斯在取得信任方面较有天分，但要那只笨狗严格遵守作战内容实在是不可能的事。

结果奇夏理解到，还是亲自执行想到的计划才是最好的做法。

「奇夏，表情怎么这么严肃？平常不是很健康的脸色看来更差了。」

「……是的，正是如此。刚才正在感叹着自己的境遇。」

「喔？为什么要感叹？」

「当然是因为我对赌命进行的计划没有兴趣。还有不只是献策，甚至还要陪同，更不像我会做的事。」

奇夏无奈地摸着自己仔细梳理服贴的黑发，夸张地发出叹息声。

虽然奇夏的声调像是低声咳嗽，但奇特的是不会很难听清楚。虽然现在也是小声地进行对话，听到这个回答，主人便愉快地发出笑声。

如果能推着对方的头回答「现在不是笑的时候」，不知道会有多么爽快。对极为理性的奇夏而言，对方地位高到当然不能做出这种事。

──远处能够听见战场短兵相接与怒吼的声音。

在掠夺与防卫之间，性命为了彼此的主义与主张激烈碰撞并消逝。而位于中心处的人物，毫无疑问地是在奇夏身旁的文森•亚伯克斯。

「选帝之仪」开始后，文森被评为是最接近帝位的候选人。理所当然地，早已料想到会成为其他候选人锁定的目标，确实是相当猛烈的包围网。

受到这种猛烈攻击，这在事前计划中是最为危险的立场。

然而──

「这毕竟在我们料想的范围内，表示状况进展在我们掌控中……」

「──原来如此，兄长也是找到不错的棋子，值得嘉许。」

「────」

有道如火焰般的声音撼动鼓膜，从前进路径打断奇夏呢喃般的话语。

瞬间确实感觉到思考被烧尽，才会有种误以为是火焰的错觉。这位少女的声音便是如此压倒性强势，满溢着吞没一切并燃烧殆尽的自信。

奇夏对眼前景象吞了一口气并绷紧神情，视线前方有群人从黑暗中现出身影。那是个身旁带着银发少女，背后还有全身红色盔甲士兵跟随的深红色公主──

「──普莉丝卡•班奈狄克。」

名为普莉丝卡的少女堂堂现踪，令奇夏感到喉咙干渴。虽然呢喃中忘了敬称，但普莉丝卡并没有追究──不，应该说是不放在眼中。

她跳过惊讶的奇夏，紧盯着站在他身旁的文森。

接着，这对染血的兄妹互相对望，缓颊一笑。

「真亏你能来到这里，普莉丝卡。近来是否安好？」

「那当然，兄长。要是兄长能在这里人头落地，肯定会更加神清气爽吧。」

两兄妹朝彼此露出微笑。代表这对互相认同的兄妹之间无法再度重修旧好，也代表这是散发出鲜血气味的重逢。

12

──「选帝之仪」开始三个月后，帝国内战早已迎来高潮。

拥有继承下任佛拉基亚皇帝宝座资格的候补聚集起来，展开包围网狙杀号称头号继承人的文森•亚伯克斯。

这场内战投入英勇名号不分轩轾的私兵团，让亚伯克斯上级伯爵的领地染上鲜血，战场上蔓延着死亡与破坏的味道。

四处传来的怒吼与凄惨叫声，如实地反映出这场流血内战有多么悲惨残酷。只要是拥有正常思维的人，应该都会对此种惨状别开视线，受到沉重的心灵创伤──但只有极少数人并非如此。

为了成为下任佛拉基亚皇帝，佛拉基亚皇族拥有身为从政者的志向。

身为矛与盾侍奉佛拉基亚皇族的忠臣们。

或者是顺着无可救药的己身特质，只为了自身欲望而展现力量的逸脱常轨之人。

像这样在某种意义上受到天选的人们，对自己身旁出现的惨状，以及性命散发出耀眼光芒消逝的景象没有任何情感。

要有这种超乎常人的精神特质，才能抵达常人无法抵达的领域。

──这便是超越者的资质，也是拥有支配者基准资格的一群人。

在深邃森林中，男女背对着彼此阵势堂堂对峙。这对拥有同样血缘的亲兄妹也不例外──不，或许该说这两人才是最为显著的例子。

这个瞬间，两人的意识中只有彼此。他们很清楚自己的存在会左右多数人命运，并决定帝国未来，而且贯彻此种态度。

他们早已看透这条路的尽头，便是佛拉基亚帝国的未来──

「──呵。」

兄妹互相对峙，文森与普莉丝卡的重逢可说是迅雷般猛烈。

在深绿的景色中打过照面后，两兄妹不约而同地伸出手。下个瞬间，两者手中皆握着发出赤红光辉的美丽宝剑。

──据说世界存在着十把拥有无比力量的魔剑。

「阳剑」便是其中之一。是除了具有资格以外的人触碰，便会连魂魄都被烧尽的魔剑。据说阳剑由代代佛拉基亚皇帝继承，但只有在「选帝之仪」时会依照符合资格的人数出现相对数量，理由仍然不得而知。

然而，如果说到阳剑的光辉是否会因此黯淡，答案当然是不可能。

「────」

两把阳剑如同太阳般，将昏暗森林的黑暗耀眼地照亮。

普莉丝卡与文森，两者分别拿着阳剑踩着轻快步伐前进，以彷佛舞蹈般的流丽动作展开交锋，迸射出红白色的光芒，笼罩森林。

这是两种火焰互相交缠、提升热量的美丽景象。

互相吞噬的火焰似乎会将触碰或靠近的人烧尽，地上理应不会存在的复数魔剑互相斩击，简直像是虚幻的现实一般。

两人的随从们来不及反应，被热浪灼烧皮肤才总算理解状况。

──主人已经赌上自己的生存开始厮杀了。

「──怎么会有这么丢脸的事！现在不是发呆的时候！」

灼烧皮肤的热风扩散，笼罩其中的奇夏回过神来并咒骂着自己的失态。他将手伸进怀中掏出一把铁扇，试着协助主人。

然而，当奇夏准备飞奔而出时，身体并非是往前，而是往侧面一跳。刹那间，奇夏原先所待的位置与理应踏进的空间，同时被「削」了过去。

看着彷佛连野兽都会被撕成碎片的凌厉一击，奇夏眯起细长眼眸，瞪着使出刚才那一击的源头。

「……不会让你妨碍公主。」

在持续进行灼热交锋的两兄妹背后，毫不吝惜地露出褐色肌肤的年幼犬人族少女──亚拉基亚与奇夏正面对峙。

她手中握着毫无奇特之处的树枝，那悠哉站着的模样看起来破绽百出，但对峙的奇夏绷紧神情，并吞了一口气。

因为他理解到对方是与瑟希鲁斯同类的「猛兽」。

「我个人不太适合劳动身体……你是普莉丝卡大人的心腹吧。」

「──？我是亚拉基亚，要替公主而战。」

对于奇夏的问题，亚拉基亚的回答十分简略。但正因如此，能够从中感觉到绝对无法撼动的信念，让奇夏深深吐出一口气。

他知道靠着问答制造惊慌或是话语交涉，都是毫无意义的举动。

那么，继续说话也没有任何益处。在举起铁扇的奇夏后方，文森的士兵们也同样各自举起武器。

「我和后面的士兵都是为了宣示效忠而战，很可惜，我无法诉诸决斗这种没有效率的手段。请您见谅。」

「呃……？」

「简单说来，就是要用人数优势直接突破战线。」

面对奇夏这道斩钉截铁的号令，士兵们同时发出吼叫声向前冲刺。

亚拉基亚对此举瞪大双眼。她以眼角余光瞥着背后交战的两人──看似很愉快地挥舞阳剑的普莉丝卡与迎战的文森，然后往前迈出步伐，不让两人受到阻碍。

「我听不懂太难的话，不过这是为了公主，去死吧。」

13

涌上的士兵们脸上皆带着视死如归的凌厉神情。

「────」

剑与枪是实现他们钢铁般意志的唯一手段，将这些武器刺进亚拉基亚的皮肤、穿过肌肉、击碎骨头并凌辱性命，战争便是为此而生的仪式。

互相夺取性命──亚拉基亚也遵循着此种规则。

「啊嗯……」

随着这道脱线的声音，亚拉基亚将精灵放进自己口中。

正好受到普莉丝卡与文森的战斗触发，周遭的火之微精灵开始聚集而来，亚拉基亚将其中一只吸收，并化为自己的力量。

这是「吞食精灵」篡夺力量的特殊本领──

「──汪汪。」

亚拉基亚压低身体，全身被淡蓝色的火焰围绕。以烈火而言实在过于美丽，缠绕着火焰的印象更为强烈。在士兵们对这种充满神秘的模样浮现出迷惘的刹那，她同时从后方用力一蹬。

如同一阵风般，亚拉基亚的身体穿过冲来的最前列士兵。

躲过攻击并被穿过的男子们回过头，准备追击钻进队列中央的亚拉基亚，结果突然发现──全身已经被蓝色火焰吞没。

「唔、嘎啊啊啊啊啊～～！！」

被从头顶到脚底被灼烧，士兵们发出痛苦的惨叫声。

与甚至看起来身穿火焰羽衣的亚拉基亚不同，吞没士兵们的蓝色火焰却没那么简单。不论在地面打滚或是用土覆盖，无法消灭的火焰仍然缠绕在身上，直到性命消逝、肉体化为灰烬为止。

「别怕！」

然而，文森的私兵也绝非泛泛之辈。当他们判断燃烧的同伴已经无法获救，便随即将意识切换到攻击亚拉基亚上。

但令人难过的是──经过统率的人数优势仍然无法对抗更强大的暴力。

大部分战争都是由数量决定胜负。考量到每个人没有太大差异，两个人会强过一个人，一百个人会强过十个人，这已经是无庸置疑的战术理论。当然拟定策略颠覆此种战力差距，也是战术家一展长才之处。

「……真是有够麻烦的。」

先前命令士兵攻击的奇夏，将另一只手放在握着铁扇的手上。

他也是善尽职责利用此种战术屠杀敌人的其中一人。正因为被看重这样的能力，才会连在这种状况下都能随侍在文森身旁。

思考谋略掌握状况并歼灭敌人，靠着战术完成这目标，便是他的职责。

背负这种职责，并俯瞰过多数战场的他才能理解──世界上有践踏这番理论，并且不将人数放在眼中的超越者。

仅仅数个月前，加入文森阵营的少年便属于这类人，而眼前肆无忌惮的亚拉基亚也是这类存在的其中一人。

「呃啊！」「唔呃！？」「呃啊啊啊～～！」

精锐士兵们接连发出惨叫，悉数倒卧在地。

有些是全身被灼烧、有些是脸部被挖开、有些是手脚被打碎、有些是被撕成碎片，倒在地上无法再站起来。

亚拉基亚像是野兽般四肢着地，虽然她的武器只有一根树枝，但光是树枝便将士兵们的刀剑击碎，并且彻底夺走矜持与性命，直到现在仍持续进行。

「不能再继续下去了……」

不能再随意失去兵力，奇夏只好做出苦涩决定，往前迈出步伐。

面对毫不畏惧人数差距的超越者，让喽啰发动攻势只是浪费生命。身为管理将兵性命的立场，没办法继续进行这种愚蠢行为。

「各位退后，这里由我来对付她吧。」

奇夏朝士兵们如此喊话后，亚拉基亚突然停止动作。她仍然像是狗般坐在地面，抬头盯着这位高挑青年，不解地歪着头。

接着，青年朝宛如动物般的亚拉基亚叹了一口气。

「我是文森•亚伯克斯大人的参谋奇夏•哥尔特。」

「──普莉丝卡公主的狗，亚拉基亚。」

彼此报上名号后，「选帝之仪」资格者的心腹便展开激烈交锋。

但双方只有一度剧烈冲突，而且瞬间分出胜负。

亚拉基亚从举起铁扇的奇夏下方沿着地面展开袭击。配合这道由低空发动的攻击，奇夏瞄准少女头部，挥下握着的铁扇。

在混有一搓红发的银发会被直接命中、染上黑色鲜血的前一刻，亚拉基亚张开大口将光吞噬──刹那间，少女身影从视野中消失。

奇夏目瞪口呆，让身体在地面滑动的亚拉基亚踢起光脚，奇夏的修长身体被冲击力道踢得飞向空中，然后追击如字面所述般刺了过来。

这击从背部贯穿到腹部，亚拉基亚的树枝穿过身体，将身体牢牢固定在地面。

「咳、啊……！」

奇夏吐出大量鲜血，被树枝贯穿的他无法倒地。面对奇夏这副惨状，亚拉基亚往后跳开，「嗯」地竖起双手手指并回过头。

当她准备向主人报告收拾掉强敌的事时──

「公主──」

下个瞬间，从头上灌注的红色光芒连同森林将亚拉基亚等人吞没。

14

──对拉米亚•戈德温而言，那年的园游会是很难忘的回忆。

每年当亲生父亲皇帝德莱森•佛拉基亚迎接生日时，便会举办园游会。

在为时七天的园游会上，佛拉基亚皇族兄弟会不由分说地被迫见面。当然，由于还有「选帝之仪」，因此会尽可能错开行程，不让皇族之间碰面。

即使如此，毕竟有多达六十名以上的兄弟姊妹，根本不可能全部错开躲过。

「────」

在那年园游会，当时九岁的拉米亚向父皇打完招呼后，便开始找起理应是同一天参加的文森。

以立场而言，多数佛拉基亚皇族精神层面偏向早熟。由于处在不尽早孵化便会被打破蛋壳的立场，成长缓慢的人只会丧命。

因此拉米亚没有半点普通九岁幼女的可爱之处，而是个聪明伶俐的女孩。

从这时开始，她已经培养出观察周遭的眼光，而且喜欢有能力的人。不论是寻找文森的身影，或是与聪明帅气的他说话，都是最令拉米亚雀跃的事。

她打发掉与弟妹们装熟的巴罗伊，在宽敞水晶宫举办的园游会会场中，总算找到文森的身影，赶到他面前──

「──普莉丝卡•班奈狄克，这就是妾身的名字。」

「────」

在文森身旁，她遇见了某个身穿深红色礼服的女孩。

而拉米亚•戈德温为了处理引发叛乱的中级伯爵，采用强硬手段，逼迫无能当家隐居，是从那之后过了三个月的事。

「──魔石炮确认弹着，等弹着点烟雾散去后会确认战果。」

「把魔晶石打完没关系，一定要确实得到成果，报告要适时、正确地回报。」

对恭敬地行礼回应「遵命」的贝尔斯特兹如此命令后，拉米亚用手撑着脸颊，望着森林被烧成荒野的惨状，眯起眼睛。

拉米亚•戈德温与许多兄弟姊妹结盟，完成了文森包围网。

之所以会连不共戴天的普莉丝卡都加入联盟，原因并非是需要能确实收拾文森的战力。

而是确定普莉丝卡本人才是能杀死文森的毒药。

「普莉丝卡，我说过很看好你了。因为文森哥哥后面第二麻烦的就是你……毕竟你的想法最接近哥哥，所以我认为你一定能找出文森哥哥喔。」

文森应该也有料想到自己是「选帝之仪」中的头号猎杀目标。

当然，他想必也算到了会被成群结盟的兄弟姊妹包围，毕竟战场也会在亚伯克斯家领地，所以逃走的准备亦不可或缺。

丢脸的是，要看穿文森贯彻逃跑的策略对拉米亚来说太过困难。不过自己做不到的事，拉米亚认为只要交给做得到的人去处理即可。

因此她做出了这个决定。

『文森与普莉丝卡位在相同地点，肯定会被炮击波及。』

协助的帕拉迪欧传来这道念话，让拉米亚确定自己的策略奏效。

拥有魔眼族血脉的帕拉迪欧，能够借着魔眼的特殊能力，持续追踪特定对象的所在处。这件事没对其他兄弟姊妹公开，但前提条件是需要对象的身体部分组织，当初并没有得到文森的身体组织。然而──

「我会特地直接过去找你，你也不觉得这只是单纯牵制吧？」

从「选帝之仪」开始之前，就已事前准备好利用帕拉迪欧魔眼的策略了。

目标文森是个慎重的男人，但如果是为了狙杀文森，就算没有直接锁定他，只要瞄准确定能抵达他身边的人就可以了。

那个人就是普莉丝卡。拉米亚会亲自造访提议结盟，邀请她加入文森包围网，也是为了让这个策略成功的事前安排。

──为此，拉米亚对杀死普莉丝卡一事忍耐了七年以上。

「普莉丝卡，我的心情总算舒服多啰。」

拉米亚将手抵在丰满的胸部上，回想起同父异母妹妹令人厌恶的表情。

只要能确定文森与普莉丝卡脱队，再靠着「修剪部队」虐杀文森的士兵，借此牵制其他兄弟姊妹。要是能解决最麻烦的强敌与不安因素，其他兄弟姊妹都不会是拉米亚•戈德温的对手。

『拉米亚，只要这场战事结束……』

『嗯，我知道。到时候要我的头发还是指甲都可以给你，随时想杀我都没问题喔。』

只要杀掉文森，与帕拉迪欧的同盟关系也会解除。

之后拉米亚虽然会依照合约内容转交部分身体组织，但就算是能在掌握关键的情报战中拥有压倒性优势的魔眼，一旦使用者资质驽钝，也是暴殄天物。

可惜的是，帕拉迪欧单靠自己不可能赢过拉米亚。如果他想像文森包围网一样，为了击倒拉米亚而向其他兄弟姊妹寻求协助也毫无意义。因为多数有能力的参加者已经被拉米亚掌握弱点，不会有人想对他提供协助。

只有文森与普莉丝卡两人有可能赢过拉米亚──是帕拉迪欧自己局限了可能性。

愚蠢的帕拉迪欧没有发现这件事，他与被妹妹操控使唤、白白送死的巴罗伊没有两样──不。

「他以为自己还有机会获胜，这就比巴罗伊哥哥更愚蠢了。」

「──阁下，烟雾要散去了。」

被蒙蒙白烟吞没的森林，正是被由于威力太过强大而被忌讳使用的十架魔石炮同时轰炸的结果。

虽然魔石炮的威力会根据发射的魔石大小与纯度改变，但从这将战场一角完全破坏的威力与规模来看，能够想见拉米亚有多么看重这次攻击。

不只是破格准备了最高纯度的魔晶石，除了帝都禄普加纳水晶宫配置的魔晶石炮以外，在帝国没有其他能够发挥出这等火力的武器。

激烈炮击甚至让魔石炮无法承受炮击威力而损坏。面对这番破坏，就算是佛拉基亚皇族，当然也无法避免被炸得灰飞烟灭。

因此众人深信这是必胜一击。然而──

「──怎么可能。」

侦察兵用望远镜窥视着远处，其中一人惊愕地发出这声呢喃，想必是肉眼理应无法看见的战果映照在那名男子眼中了吧。

然而，即使不是很详细的结果，拉米亚也看出这是异常状况。

──受到魔石炮的炮击，森林地带理应被烧成一片白皙。然而其中只有一部分完全避免受到伤害，仍然保持着毫发无伤的状态。

而造成这种超越常识之结果的源头是──

「──弹着点有人影！是银发犬人族……是普莉丝卡•班奈狄克的心腹！」

听到侦察兵震惊的喊叫，拉米亚瞪大双眼。她回想起普莉丝卡的心腹爱将，就是那个不爱说话且缺乏表情变化的混血丫头──

「不错嘛，普莉丝卡……！」

拉米亚站起身，前往侦察兵身旁抢走望远镜。接着，她见到普莉丝卡的心腹仰躺在爆炸处中央，吐出烟雾。

不知道是用什么方法，那个混血丫头完全挡下拉米亚准备的魔石炮。

那个犬人族少女生死不明，倒在地面，没有任何动静。但那并不是重点，重要的是爆炸中心处的受害规模，这点程度没办法杀死普莉丝卡与文森。

策略第一阶段以失败告终──但拉米亚还有两道攻势。

「没想到会用到巴罗伊哥哥留下的保险措施。」

这是放弃挑战皇帝宝座权利，自愿成为败者的哥哥留下的策略。

利用与巴罗伊同样放弃资格的九名兄弟姊妹作为手牌，同时攻陷受到损害的文森与普莉丝卡──

「调动伏兵。就算没有霸气，那群家伙还是能当成肉盾……」

「──阁下！」

正当拉米亚放下望远镜，准备做出下一个指示时，突然有道锐利声音打断了她。

随后，拉米亚反射地朝闪过视野边缘的黑影挥出手。她手中握着的阳剑烧尽空气，也将瞄准她柔嫩肌肤的箭矢燃烧殆尽。

但即使挡下第一道攻击，锁定拉米亚的攻击接连倾注而下。反应慢了一步的士兵们保护着自己，拉米亚则是思考着被包围的情况。

「为什么我的本营会被找出来？该不会是──」

从自问自答中察觉到端倪，拉米亚从士兵缝隙间窥视着攻击的敌人。朝火中窥伺后，拉米亚确定预感完全命中。

原本拉米亚想利用从巴罗伊手下抢来的丧失资格的兄弟姊妹们，作为文森包围网的伏兵，结果竟然朝拉米亚展开攻击──那些不可能违抗拉米亚的胆小鬼，竟然同时举旗叛变。

在这种关键时刻，难道是萌生了亲自掌握皇帝宝座的野心吗──不，他们没有这种当机立断的能力，表示答案只有一个。

「──文森•亚伯克斯。」

对于敌人暗中实现以包围反制包围的智谋，拉米亚不禁咬紧牙根。描绘出这番状况的男人，文森的帅气容貌令人憎恨地浮现在脑海中。

是反间计，被誉为「毒姬」的拉米亚竟然将毒收进怀中。

到底是从什么时候开始──想到这里时，拉米亚聪明伶俐的脑袋突然发现了某种可能性。

「……该不会是先与巴罗伊哥哥联手了吧？」

照理说巴罗伊应该只是个白白送死的输家，想到他聚集的兄弟姊妹可能直接成为文森反击的鸣镝，便让拉米亚不寒而栗。

被巴罗伊算计的可能性，还有文森比她准备得更加周到的执拗之处。

或许连拉米亚发射魔石炮都在计算之中，流程便是让她失去魔石炮后，再趁着破绽完成拉米亚包围网──但这个策略只有一个难处。

那就是为了防止拉米亚的魔石炮，绝对不能缺少那个混血的犬人族少女。

为了完成文森的计划，普莉丝卡的心腹则不可欠缺，从这件事实推导出的答案相当单纯明快──

「──普莉丝卡，原来你们联手了啊。」

普莉丝卡与文森进行密约，这是成立拉米亚包围网绝对必须的条件。

整理出这个前提条件时，被算计的拉米亚受到越来越猛烈的攻势。

「阁下！这里交给我们，请与『修剪部队』会合，赶紧撤退！」

负责指挥士兵的贝尔斯特兹，建议被敌方摆了一道的拉米亚撤退。

瞬间，拉米亚差点意气用事地拒绝这个提议，然而贝尔斯特兹的判断相当准确。留在现场只会送命，让她随即恢复冷静。

「贝尔斯特兹，这里交给你了，就算死也要撑下去。」

「遵命，阁下请务必平安无事。」

简短告别后，拉米亚从化为战场的本营撤退。

她只带着亲卫队精锐士兵，无视与背叛的兄弟姊妹们展开剧烈交锋的贝尔斯特兹，拉米亚脑内开始策画脱离这种状况，以及之后该如何重整旗鼓的方针。

但她订立的每项作战计划都──

「──面对被感情束缚的对手，只能用更强大的感情使其屈服。例如羡慕与嫉妒，如果是最单纯明快的手段，应该就是恐惧吧。」

「────」

拉米亚脑中的计划应声崩毁。

将她考量的作战计划悉数破坏的原凶不是别人，便是悠哉地站在眼前的人影──文森的心腹怀刀，也是真正的「杀人魔」。

「嗨，你好，这么晚赶来真是不好意思。虽然我尽量快了，要配合这把初次出场的刀还是有点麻烦，不过我已经差不多抓到感觉，应该不会再出现丢脸模样了。」

握着一把刀且满身是血的少年，如此说着，露出微笑。

不知道他一个人到底杀了多少人，全身被喷溅的血染成鲜红色，罕见的和服甚至重新染成看不出原本颜色的深黑色。

然而，那位少年的异常之处并不在浴满喷溅鲜血的姿态上。

他不在意身上沾满血，那总是难以捉摸的言行举止，伴随着令人联想到「死亡」的压倒性气魄，这才是最为异常的特质。

「……阁下。」

以低声呼叫着拉米亚，身穿「修剪部队」铠甲的士兵向前挺身而出。

他们把拉米亚藏在身后，选择成为阻挡少年接近的盾牌，而且确信自己肯定会「死亡」。

「嗯嗯，原来如此。是带着赴死的决心保护主君吧，真是令人赞赏的完美态度！我不讨厌这种悲壮感，反而很喜欢喔。」

「──不会让你这种怪物碰到阁下！！」

面对急速冲来的少年，「修剪部队」拿着大剪刀展开迎击。在双方剧烈交锋的瞬间，传来的并非是凶残刀刃切开肉质，而是俐落挥砍迸出的残响。

拉米亚清楚得知士兵接连被斩杀，只能跨越「修剪部队」的尸骸，持续逃往少年刀刃不可及、无法追上的场所。

接着，在拉米亚逃离的路线前方──

「别担心，拉米亚──妾身会亲手葬送你的性命。」

手持阳剑的普莉丝卡•班奈狄克，正在等待拉米亚•戈德温到来。

15

「──普莉丝卡•班奈狄克，这就是妾身的名字。」

在园游会首度见面的妹妹，那幼小身体满溢着桀敖不驯的气息，如此报上名号。

当时五岁的普莉丝卡首度参加园游会，在先前找得那么辛苦的文森介绍下，拉米亚备感震惊，甚至连后面兄长的话语都没有听进耳中。

拉米亚•戈德温本能地理解到──她就是生涯中最大的天敌。

「没错，我是拉米亚•戈德温，是你的温柔姊姊喔。」

拉米亚以微笑掩饰并如此回答，普莉丝卡一眼便看出了她的本性。

在姊妹初次见面的那天开始，两人便互相敌视。

「────」

由于文森没有松懈戒备，拉米亚才没有当场将普莉丝卡掐死。看来连天资聪颖的兄长都一眼看出两姊妹话不投机。

虽然今后拉米亚打算定期派人刺杀普莉丝卡，但除了找碴以外应该不会有其他效果。

而且既然有普莉丝卡存在，也不可能拉拢文森，表示那对兄妹只会对拉米亚的称帝之路造成阻碍。

原先怀着的犹豫消失无踪，既然这样就只能展开行动了。

「唉，巴罗伊哥哥……为什么没办法兄弟姊妹一起向父皇庆祝呢？」

「拉米亚……我也觉得很可惜，只是我们实在没办法……」

「实在没办法好好相处？那是很让人难过的事呢。」

「────」

下定决心后，拉米亚随即开始布局。

她在各处埋下各种种子，替萌芽的种子浇水，并培养可能性。从各式各样灿烂绽放的花朵中，仔细挑选哪朵能培养成毒花。

「没错，就是这样。就像拉米亚说的，只要能让兄弟姊妹不要互相伤害……」

将妹妹演得纯真无邪的话语信以为真，拉米亚瞥视着似乎相当感动的兄长。

就像这样，拉米亚巩固着自己称霸帝位的道路，并筑起未来。

接着──

「把你培育成用来杀害文森哥哥的毒花……我这七年来积极做了不少布局呢。」

在逃亡路线的前方，被挡下的拉米亚以毫无感情的声调如此呢喃。

正面等待着拉米亚的普莉丝卡没带任何士兵，与让分身带着护卫刻意显眼地逃跑的拉米亚一样。

这里只有拉米亚与普莉丝卡两人。

拉米亚不是个不明事理到会对此感到侮辱的女人。

「真是个不可爱的孩子。」

拉米亚用手轻轻整理着凌乱的头发，望着将手挽在胸前，站在面前的妹妹。那毫不掩饰残酷之色的炽热深红眼眸，与在园游会见面时如出一辙。

这是拉米亚与普莉丝卡认同彼此为天敌时的眼神。

「你家那只小狗是怎么挡住炮击的？如果没有她，你和哥哥照理说都会一起被炸死了呢。」

「你消息那么灵通，应该知道亚拉基亚有『吞食精灵』的特殊能力吧。她的力量依存于吞食精灵的力量，这样答案就很清楚了吧。」

「──是吸收了能挡下那阵炮击的强大精灵吗？不会那么轻易就出现那么强大的精灵吧……」

拉米亚话还没说完便闭起嘴巴，接着压低视线盯着地面，彷佛能够理解般点了点头。

「知道会被包围，文森哥哥还选在这个地方固守城池的原因……以为有坚固城池本身就是错的吧。」

「舍弃城池一开始就包含在兄长的计划之中，表示兄长选择这个地方的理由不是城堡，而是这块土地本身。」

「正确来说，是这个地方沉眠的精灵吧？」

普莉丝卡没有否定拉米亚的补充说明。从妹妹这种态度，拉米亚察觉到了自己被引诱到这个地方的理由，以及魔石炮攻击失败的原因。

「──『石块』穆斯贝。」

「就是那片神域，还有被誉为四大之一的精灵。」

普莉丝卡对拉米亚说出的词语点了点头。

「石块」穆斯贝──是这个世界最有名的四精灵其中之一的名号。

被称为四大精灵，并拥有强大力量的大精灵其中之一，据说在佛拉基亚帝国的国土上随意流浪。如果能够吞食那个强大大精灵的力量，应该也有可能从拉米亚准备的魔石炮炮击下保护主人。

「可是，吸收四大精灵的力量，对那只小狗而言没问题吗？」

「毕竟只有吸收一部分……但就算是这样，如果不到亚拉基亚这种程度，肯定已经被撑死了，不过世上不存在走运得不需要牺牲的胜利。」

「──你们有考虑大精灵被咬之后大闹的情况吗？」

拉米亚如此询问断定心腹赌上性命是必要牺牲的普莉丝卡。

已经理解他们利用大精灵力量的手法，但别说是相互沟通，「石块」理应是无法指定或限制行动的超常存在。

就算只有一部分，被亚拉基亚吞食也无法保证不会开始大闹。

「更不用说你们是怎么让『石块』留在这里的？文森哥哥真是的，连人类以外都能用谋略操控吗……」

「很多地方都是兄长的谋略没错，但重点不是做法，而是出现结果这点。」

「──嗯，是呀。」

普莉丝卡举起手握住阳剑，表示已经得到结论，不打算继续说下去。拉米亚也配合着她，从空中拔出自己的阳剑，摆出架式。

不会阻碍彼此拔出剑，这个毫无戒备的举动不能算是信任，这种公认的事不会称为信任，但两姊妹很清楚必须这么做。

还有必须亲手分出胜负的事也是──

「普莉丝卡，我从第一次见面的时候就很讨厌你。」

「别担心，你是妾身记得名字的人当中最令人痛恨的人。」

这对姊妹只要见面，便会互相投以憎恨与敌意。

即使这是生涯中最后的机会，这种关系还是没有任何改变。

「────」

双方冲向前互相交锋，红白光线与热量将世界逐渐吞没。

周遭景色变得模糊不清，世界只剩下自己与普莉丝卡存在。果然，还是应该在初次见面的园游会就杀掉这个妹妹的──拉米亚如此嗤笑着。

──在仍然没有改变彼此认知的情况下，这对姊妹的关系宣告终结。

16

「这个时候，普莉丝卡和拉米亚应该分出胜负了吧。」

文森这么说，俯视着半生不死的亚拉基亚。

亚拉基亚靠在大树上，将脚伸直，耗尽体力的模样看来十分疲惫。

这也是理所当然的，毕竟她抵销了有可能会消灭整支部队的魔石炮大破坏，为此决定将四大精灵的力量吸收进小小的体内。

反作用力当然相当强烈，是甚至做好了魂飞魄散的心理准备的牺牲奉献。

因此文森的策略才得以成功，亚拉基亚的贡献难以估计。

「做得漂亮。普莉丝卡有这么好的部下，这点我也表示认同。」

「……这是、为了公主。」

「我想也是，这点我没有怀疑过。」

文森很少对这种值得钦佩的忠心耿耿赞誉有加。

侍奉皇族的臣子多少都会具备与她同等，甚至是更为强烈的忠诚心。

不知道文森暗中与普莉丝卡联手，而被利用当成欺敌诱饵的私兵也是一样。

「虽然感觉奇夏会有怨言就是了。」

在如此呢喃的文森视线前方，不只是被亚拉基亚刺穿、还被卷入魔石炮与四大精灵力量抵销中央处的奇夏正在接受紧急治疗。

肉体内外皆受到重创，能不能获救都很难说。

他是有能的参谋，也是将来能够肩负起重要立场的忠臣。为了让策略成功而需要他的三寸不烂之舌，甚至连他都成为谋略的一部分，配置于盘面。

然而，文森确定有这么做的价值。

「就像拉米亚很看得起我和普莉丝卡，我也对她有同样评价。虽然『选帝之仪』才刚开始，这样有看头的候补差不多都解决掉了。」

野心与能力皆十足优秀，有可能获得帝位因而需要戒备的候补，在文森眼中顶多只有拉米亚与普莉丝卡。

可惜的是，其他手足不是文森的对手──只不过，在与抢夺帝位不同的层面上，有个兄长让文森颇为吃惊。

「没想到连我都会误判巴罗伊兄长。」

在「选帝之仪」开幕后，巴罗伊•费兹便以被拉米亚修剪的形式离世。

他厌烦兄弟姊妹互相残杀的血之仪式，计划让「选帝之仪」夺走的性命控制在最小限度，而且采用连文森都不禁吃惊的手段。

「用拒绝参加仪式并对我投降的手足们的首级当作交换条件，保证自己领地与手足们的领民性命安全，真是个不得了的策士。」

要是他计划成功，为了减少十个候补，只要砍掉十个首级。如果兄弟姊妹各自举兵，失去的性命应该也会等比增加。

文森绝对不会放过兄弟姊妹，这是反过来利用这个正确认知的策略。

──突破拉米亚包围作战的重要关键有两个。

能用四大精灵之力抵销魔石炮的亚拉基亚，以及拉米亚没有掌握到的反间计──也就是巴罗伊暗中留给文森的手足们的私兵。

即使那是与死者缔结的密约，实际上只要能够获得战功，文森便不会选择违反这项密约。

赏罚分明，这是文森身为佛拉基亚皇族必须遵守的规范。

手足们在巴罗伊唆使下放弃资格，为了生存，应该会拼死战斗让联手的文森获得胜利，而且无从得知两人暗中缔结的密约。

巴罗伊这个披着好人外皮的策士，肯定没有将接下来的真相告诉手足。

甚至连自己的「死亡」都编进计划中，这种为了达成目标的态度十分令人赞赏。

表示巴罗伊•费兹也是合乎佛拉基亚皇族风范的其中一人。

「────」

对于文森这番抒发，奄奄一息的亚拉基亚没有回答。

他原本就是忠实遵从普莉丝卡命令的忠狗，不需要拥有自己的意见或思考的脑袋，是个与背叛或野心毫无缘分的方便丫头。但或许该说，普莉丝卡重用她肯定不会只出于方便这个原因。

在普莉丝卡与亚拉基亚之间，拥有并非单纯主仆的真正羁绊。

只要是为了普莉丝卡，亚拉基亚会不惜抛弃一切──她本人与普莉丝卡的想像力，还没有丰富到能够联想出这代表何种含意。

「你叫亚拉基亚吧。」

「──嗯？没错。」

被叫出名字的亚拉基亚满腹狐疑，文森走到她的正前方，朝眼神如同不亲近人的小动物的少女闭起单边眼睛。

接着──

「有句话要先对你说清楚，我……不对。」

文森在这时打断话语，并微微摇了摇头，然后他不改黑色眼眸透露的神色，重新改口：

「……是余有话要对你说。」

17

──自文森•亚伯克斯包围网后过了两个月。

「普莉丝卡，你这家伙……！」

「──闭嘴，愚昧无知的家伙。与你交谈没有任何价值。」

长发男子表情显得激动不已，从空中拔出阳剑。然而，描绘出半圆形的深红色斩击却被上方传来的冲击压垮，魔剑被强硬地从男子手中弹开。

一道剑闪划过手无寸铁的男子瞪大的双眼，这比起他挥剑的轨迹更加美丽且残酷──而这也是男子最后的死期。

斩击俐落地将男子头身份离，带来确切的死亡，分开的头与身体瞬间同时燃起火光，赤红烈焰将尸体化为灰烬。

这就是佛拉基亚皇族之一帕拉迪欧•曼内斯库的最后一幕。

「毕竟只是凡夫，这即是你的极限了吧。」

面对躲在自己城堡内迎接毁灭的愚蠢兄长，普莉丝卡如此评论。

与拉米亚联手并煞费苦心扰乱「选帝之仪」的蝙蝠，普莉丝卡依照约定，亲手将他的头砍了下来。虽然被杀害的一方不可能会高兴，但普莉丝卡并不想管帕拉迪欧有何种内情。

又一个通往王座的障碍被排除，事实就是如此单纯。

「公主……」

「亚拉基亚啊。这里解决了，其他地方怎么样？」

「没问题，结束了。」

普莉丝卡将阳剑收回空中，亚拉基亚出现在回过头的普莉丝卡前方。

在帕拉迪欧的据点中，亚拉基亚为了扫荡各处配置的士兵四处奔波，但她裸露的肌肤没有受到任何创伤。

即使帕拉迪欧身为魔眼族的特殊能力相当杰出，但阵营中缺乏能够活用这种能力的智将，也没有能够支持他的忠臣。

结果帕拉迪欧的首级被普莉丝卡拿下，手脚也被亚拉基亚扯断。

「如果只有这点程度，反而是拉米亚让妾身愉快许多，没想到妾身也会有怀念那个恶劣女人的一天。」

「────」

「怎么了？亚拉基亚？难得看你出现这种沉思的表情。」

堂堂坐在杀害的手足的宝座上，普莉丝卡窥伺着保持沉默的亚拉基亚。对于这番话，亚拉基亚只是「啊……」地眨了眨眼。

「……公主快要跟文森大人交手了吗？」

「兄长啊──应该是吧。先不论是否很快，应该是无法避免分出高下吧。」

得知亚拉基亚担忧着文森的存在，普莉丝卡眯起眼睛。

文森•亚伯克斯是「选帝之仪」的头号劲敌──自从普莉丝卡主动提供协助突破文森包围网后，他的阵容日益茁壮，并且将其他身为候补的兄弟姊妹接连消灭。

正因为知道会有这种结果，拉米亚才会趁早与其他人联手发动攻击，试图剿灭文森──在包围网失败后，其他候补应该也要对多少受到打击的文森持续展开同样攻势。

然而，他们错过这些机会，让文森获得了疗伤与报复的机会。

「这种愚蠢的报应，带来的肯定是灭亡。」

不论如何，只要能在「选帝之仪」中获胜，接下来便是佛拉基亚皇帝的宝座与义务，而他们只是不足以身负起这个重责大任罢了。

既然已经缺少拉米亚与中庸的帕拉迪欧，再来就只剩下──

「──不愧是普莉丝卡大人，真是慧眼独具，让小人深感佩服。」

在这对主仆如此交谈时，有另一个人影发出鞋声现出身影。用手撑着脸颊的普莉丝卡将深红色视线转了过去，对方便恭敬地垂下头。

出现的是某个白发青年。瞬间，普莉丝卡眯起单边眼睛追溯着记忆，随即从记忆与眼前青年互相对照出姓名，模样却与记忆中有部分差异。

在普莉丝卡的记忆中，这位青年理应是黑发。

「若您是对小人怀有疑问，很抱歉这种模样让您受惊了。由于前阵子生死旁徨之际，似乎让身体失去了颜色。」

「原来如此。虽然说来奇妙，妾身就不追究此种迷惑妾身的奇特样貌了，是奇夏•哥尔特吧。」

「您能记得小人，真是荣幸之至。」

在前阵子战斗中见到的青年──奇夏这么说，恭敬地低下头。

假装与文森互相交锋后便赶往拉米亚那里去了，因此普莉丝卡并不清楚，听说他与亚拉基亚交手，并受到濒临死亡的重伤。

「这次奉阁下之命携带礼物前来拜访，虽然似乎有点言之过早，倘若大人肯收下，便是吾等荣幸。」

「把对手的首级砍下后，再派遣使者穿越敌营，确实很有兄长的风格。所以是带了什么礼物过来？」

「──是庆贺的美酒。」

奇夏这么说，献上一瓶据称是至高无上的美酒。

虽然普莉丝卡只有十二岁，但她已经尝过酒的滋味。即使对尝过各种极品美味的她而言，那仍然是难以得手的美酒。

然而──

「──亚拉基亚，打碎那瓶酒。」

随着这句话，奇夏手中的美酒容器被打得碎裂四散。发出尖锐声响碎裂的酒洒落地面，奇夏见状，眯起那如爬虫类般的眼睛。

「这可是几乎能让权贵倾家荡产的名酒……」

「妾身很清楚，如果不是在『选帝之仪』期间或许会收下。但在这种机会赠送礼物，兄长应该也是以被打碎为前提才送过来的吧。」

「所言甚是。」

奇夏一副若无其事且毫无落寞之意地点了点头。

只要是佛拉基亚皇族之间赠送的礼品，肯定会隐含着某种意图。对见惯了毒杀谋略的帝国皇族而言，不可能将他人赠送的礼物直接送进口中。

见到这种打从一开始便十分清楚的应对方式，文森的年轻爱将露出与体色同样彷佛失去感情般的静谧眼神。

「回去告诉兄长，有看头的对手都已经处理完毕，妾身与兄长决战的时刻越来越近，两边应该不会想回到以前那种相处模式了吧。」

「恕小人失礼，普莉丝卡大人认为有可能赢过吾主吗？」

「当然──毕竟这个世界就是为了妾身量身打造的。」

面对阐述己身哲学的普莉丝卡，奇夏敬佩地当场行了个礼。普莉丝卡从行礼别开视线，挥了挥手表示已无话可说。

她打算让奇夏回到文森身旁转达准备进行决战的事。

然而──

「──既然世界是为了大人量身打造，您对接下来有什么看法？」

「什么？」

听到这个耐人寻味的问题，让普莉丝卡朝奇夏投以狐疑目光，接着吃惊地瞪大双眼──因为有个人影跪在视线前方的地面上。

「────」

亚拉基亚跪倒在地，将脸靠向弄脏地面的美酒。她颤抖地将舌头伸向缓缓扩散的酒，发出声响开始啜饮。

「亚拉基亚，你在做什么？身为妾身的随从居然做出这种卑贱举动……」

「公主……对不起……」

在对这种行为瞠目结舌的普莉丝卡面前，亚拉基亚回过头，泪眼汪汪地如此说着。

见到同乳母的姊妹首度展现出悲叹的模样，连普莉丝卡都不禁倒吞了一口气。但她的惊讶不仅于此，因为亚拉基亚浑身无力地倒卧在地。

「……啊……呼……唔呃……」

倒地的亚拉基亚发出呻吟，四肢抽搐，翻着白眼，明显表达出她的肉体正受到致命伤害。

「────」

见到这幅景象，普莉丝卡眼中瞬间冷酷地开始进行计算。面对濒临死亡的亚拉基亚，无数选择在她那聪慧的脑中转瞬即逝。

如果是普通凡人，肯定会在犹豫下一手的时候让亚拉基亚丧命。但普莉丝卡并非凡人，早已看穿这点的文森也非比寻常。

正因如此，这对最为接近的兄妹只能迎来彼此残杀的结局。

「──愚蠢的家伙。」

普莉丝卡在倒地全身抽搐的亚拉基亚身旁，如此呢喃。她抱起亚拉基亚，毫不犹豫地将嘴唇抵在她的唇瓣上，开始吸出亚拉基亚啜饮的毒酒。

就像从伤口吸毒般，将亚拉基亚啜饮的毒酒向外吐出。但这是连强韧的亚拉基亚都会倒地的剧毒──光是接触到黏膜，普通人便会无法维持神智。

「唔……」

普莉丝卡当然也亲身体验到剧毒的效力，但即使被剧毒侵蚀身体，普莉丝卡仍然没有放弃从亚拉基亚体内吸出毒素向外吐出的动作。

「真是可怕的两位。」

奇夏望着这番景象，从口中喃喃说出由衷涌现的赞赏。

不论是对强忍着些许剧毒、却仍然执意替亚拉基亚排除毒素的普莉丝卡，或是知道只有这个方法才能让工于心计的她喝下毒药的文森。

对奇夏而言，双方都是难以捉摸心思的杰出人士。

「……兄长是怎么说服亚拉基亚的？」

亚拉基亚停止抽搐，虽然仍然失去意识，但已经脱离险境。完成救治的普莉丝卡擦了擦自己的嘴唇，压抑着颤抖声调，向奇夏如此问道。

奇夏望着这令人惊叹的胆量，歪着头反问：

「大人应该很清楚吧？阁下认为普莉丝卡大人肯定能准确看出端倪。」

「哼……所以才会把这个重责大任交给你吧。」

「很抱歉辜负了大人一番好意。」

普莉丝卡缓缓站起身，再度回到宝座上，奇夏对她那平稳的步伐感到无以言表。但她将身体靠在椅背上的垂危模样，表示毒素正确实地侵蚀着她的性命，让奇夏不由得松了一口气。

接着，即使知道接下来的话只是多余，奇夏还是忍不住继续说：

「普莉丝卡大人。」

「怎么？」

（插图009）

「要是小人没有侍奉文森阁下，主君应该就会是普莉丝卡大人了，实在是相当令人惋惜。」

「哼……」

在摇了摇头的奇夏面前，普莉丝卡彷佛吐出气息般露出笑容。然后，她看着倒在地面的亚拉基亚，放缓那血色嘴唇，微微一笑。

「不需要像你这种不可爱的小丑。想在妾身手下做事，至少外表得楚楚动人……你这凡夫。」

直到最后的最后，她仍然维持着自身风格发着牢骚，长长地吐出一口气。

气息就这样停了下来──这便是普莉丝卡•班奈狄克临终前的最后一刻。

18

「──楚楚可怜的公主就这样掉进敌人的陷阱中，轻易地失去了性命。之后公主的兄长获得胜利成为皇帝，据说让帝国继续维持着荣景。」

「听、听起来让人好紧张喔，那还有什么后续吗？」

「怎么可能还有后续。刚才不是说过了吗？这个故事的主角公主已经死了，不可能会有后续发展。」

「咦咦咦！？怎、怎么这样啦！」

少年皱起可爱的眉头，气呼呼地表达不满。对于少年的罕见反应，阐述着故事的美丽公主──不，是普莉希拉不解地歪着头。

她那美丽的橙色发丝从白皙平缓的香肩垂落，她在丰满的双胸前挽起双手，对气头上的舒尔特出声斥责。

「舒尔特，没想到你已经大胆到敢挑剔妾身的故事。是哪边让你觉得不满意？说来给妾身听听。」

「遵命！刚才那个故事的公主太可怜了！明明公主已经那么努力了，结果居然被养的狗狗和哥哥欺骗……不知道该怎么说才好了！」

舒尔特面红耳赤地如此抗议，让普莉希拉眯起眼睛。

虽然对舒尔特述说的故事经过些许修饰，但基本上还是依照「事实」阐述。因此身为熟知公主的人，舒尔特认为公主很可怜的反应让普莉希拉匪夷所思。

但即便如此──

「不论你有什么想法，公主就是已经死去，故事也画下句点。结局不会有任何改变，这是阐述故事必定得遵守的规矩。」

「唔……这样实在太难过了，有种很不甘心的感觉。」

「那又怎么样？表达不满、闷闷不乐，然后虚度光阴吗？」

要是舒尔特真的这么做，普莉希拉对他的评价会大幅改变。一时兴起让他听完故事后的感想，将会大幅左右舒尔特的未来。

舒尔特不知道事情的严重性，只是将细瘦双手挽在胸前，发出「嗯……」的低吟声不停烦恼。普莉希拉并没有特别催促，静静地等待着他的回答。

接着，舒尔特解开双手，望着普莉希拉。

「既然这样……小的会继续把故事写下去。」

「──什么？」

听见舒尔特出乎意料的回答，普莉希拉挑起眉头。见到普莉希拉的反应，舒尔特紧紧握起小小拳头。

「普莉希拉大人说过故事就这样结束了，不过只要小的想出后续发展，让公主不要这么可怜就可以了！」

「────」

舒尔特以拙劣的遣词，试图编撰出理应结束的故事后续发展。见到舒尔特这番拼命的模样，普莉希拉微微屏起气息。

接着，普莉希拉先是闭起眼睛。

「没想到是编造出结束的故事。那么之后要怎么继续下去？舒尔特，如果是你，会给死掉的公主怎么样的未来？」

「这个嘛……首先是公主虽然喝了毒酒，但其实并没有死！只是陷入沉眠，还会再醒过来！」

「喔？为什么会醒过来？那是剧毒，而且还是能让一个人瞬间毙命的剧毒喔。」

「可是公主和养的小狗各分了一半！所以才能醒过来！」

因为分摊了一人份的致死毒药量，所以公主和养的狗幸运逃过一劫。虽然这个理由很像是孩童的算数，但普莉希拉并没有否定舒尔特用这个理论去联想。

普莉希拉只是摸着舒尔特的桃红色头发，缓颊一笑。

「普莉希拉大人？」

「舒尔特，真是个会想着奇怪事情的小家伙。将结束的故事改写成自己喜好的模样，这可是践踏故事作者的傲慢举动喔。」

「呃呜……不能这样吗？」

「为什么这么问？没有什么好不能的。把不能接受的故事扭曲成自己喜好的模样，这没有什么错，妾身是对这个答案感到佩服。」

如果只是不服气地忍气吞声，即使是疼爱的书僮，普莉希拉肯定也会毫不留情地认为自己看走眼，但舒尔特顺利地合乎普莉希拉的期待。

「让妾身听听，你能接受的可怜公主的后续发展吧。」

「──！遵、遵命！首先公主并没有被毒死！然后被很善良的人救了回来……」

得到普莉希拉允许，舒尔特带着灿烂目光说起故事后续发展。普莉希拉撑着脸颊望着少年的兴奋模样，轻轻地抚摸着书本的封面。

这本书是阐述这个故事的契机。不知道这个故事有何种价值，根据每个人的眼光不同，也有可能没有任何价值。

或许该说，这在旁人眼中只是文字莫名其妙随意排列的书籍。

然而──

「普莉希拉大人？您有在听吗？」

「当然，你以为妾身是什么人。」

语毕，普莉希拉摸了摸舒尔特的头，然后眯起眼睛。

脑中回想着曾经被这只手摸过，并且同样眯起眼睛的另一张脸──

19

『──普莉丝卡是赢不过余的。她除了自己以外有很多弱点，因此与余交手肯定会死，那是无法避免的结局。』

『不过，余也不想看到挚爱的妹妹死去，所以为了奖赏这次的功绩，特别赐给你一个机会──能拯救普莉丝卡的机会。』

『那个方法就是──』

「────」

「你醒了啊。」

在床上睁开眼睛，望着天花板时，脸旁突然有道声音传来。朝旁边瞥了一眼，便能见到有个由上到下都被染成白色、外观奇特的男子。

记得这名男子叫做──

「全身白的……」

「奇夏•哥尔特。我认为至少要努力想出名字吧。」

奇夏面不改色地自报名号，顺便加上抗议，躺在床上的少女──亚拉基亚并没有将抗议听进耳中，随着些许不协调感用手摸着自己的左眼。

虽然起床时睡眼惺忪是很常见的事，但现在亚拉基亚模糊的视野有微妙差异。简单说，左眼视力接近于零。

「算是用来交换性命的代价吧。就像我这样全身变白一样，双方能保住性命真是太好了。」

亚拉基亚摸着眼睑时，奇夏如此平淡地说明状况。听到自己失去左眼，亚拉基亚心中并没有特别惊讶，毕竟原本就是很有可能失去性命的交易，能活着反而比较令人吃惊。

而自己活了下来，等同于文森的计划已经成功，不然毒素不可能没让亚拉基亚完全丧命。

「公主呢……？」

「普莉丝卡大人吗──不幸过世了。」

「──！」

然而，即使这番说明与刚才一样平淡，亚拉基亚并没有漏听这句话。

亚拉基亚瞪大剩下的右眼，从床上跳起来，将手伸向身旁的奇夏，准备折断他那细瘦苍白的脖子──

「──嗯，刚大病初愈不能做这种事喔。冷静点，小狗狗。」

「嘎啊……」

随着这句轻佻的话语，亚拉基亚的额头被重重一击而瘫倒在地。亚拉基亚不知道发生什么事，眨了眨眼，有抹奸笑映入视野角落。

将蓝发绑在身后的少年前倾身体，窥视着倒地的亚拉基亚。得知对方身份的瞬间，平时缺乏感情起伏的亚拉基亚心中顿时激动不已。

「奸笑脸……」

「哈哈哈，我知道看到我的脸会很高兴，但不需要这样自己表白嘛。看到我会忍不住缓颊一笑也是没办法的事！」

「────」

亚拉基亚瞪着在剩余的右方视野中扶着额头的少年，见到她带有杀气的视线，奇夏缓缓摇了摇头。

「我替他口出狂言，还有我自己不好懂的回答表示赔罪。重新再说一次好了，普莉丝卡大人已经过世，但您的公主还活着。」

「意思是……」

「阁下有遵守约定──既然您已经成为普莉丝卡大人的毒药，便不会违背当初的诺言。只不过……」

「没办法再见到公主……」

「──正是如此。」

瞥着静静点了点头的奇夏，亚拉基亚按着左眼，屏起气息。

──文森会遵守诺言。如果奇夏所言属实，普莉丝卡已经死了，却又活着，她的「选帝之仪」便在亚拉基亚背叛下宣告落幕。

「公主……」

她应该会恨我吧，亚拉基亚回想起长久以来持续凝视的美貌。

憎恨遵从文森的意图成为普莉丝卡的毒药，而且不相信她会胜利，自作主张地避免她「死亡」的亚拉基亚。

亚拉基亚并非是对文森的话语着了魔，说到普莉丝卡无法胜过文森之处，并不是实力或智谋，而是心灵的差距。

普莉丝卡慈悲为怀，太温柔了。──因此无法赢过冰冷残酷的文森。

「呜……呜呜……」

「哎呀，哭了起来呢。奇夏，这只小狗狗要怎么办？听阁下说她无处可去了。」

「据说进退要尊重本人的意思，你前阵子毁灭『修剪部队』的恶行才是都传开了。」

亚拉基亚手捂着脸，微微发出呜咽声。脚边能够听见少年与奇夏的对话。亚拉基亚毫不在意两人，只是哭泣着，同时开始祈祷。

即使身为吞食精灵、没有对象能够祈祷的蛮族少女，亚拉基亚还是向天祈祷。

（插图010）

祈祷那位亚拉基亚醉心的公主总是挂在嘴边的话语能够成真。

世界就是──

20

「──为了妾身量身打造的。」

少女如此喃喃说着，轻轻按着自己随风飘逸的橙色秀发。

美丽少女伫立在草原上，眼前有个坐落在树荫处的小小墓地，墓碑上刻着「普莉丝卡•班奈狄克」之名。

少女眯起深红眼眸，望着这位败战而死的佛拉基亚皇族墓志铭。

「公主，现在您的身体还不能这样吹风。」

少女背后传来这道声音。出声的是某个自然地身着高贵装扮的老妇人，身后带着几名侍从，能够看出她的立场与外表印象没有差别。

这位老妇人表达敬意的少女，处在更为尊贵的立场。

「公主，请务必好好听话……」

「──别再用公主这种愚蠢的称呼，普莉丝卡•班奈狄克已经沉眠在墓中。明明是你的孙女，称呼妾身公主很奇怪吧。」

「────」

面对这个以高傲态度回应的「孙女」，老妇人恭敬地垂下头。少女从背后感觉到这个举动，「哼」地重新望着墓碑。

原本参加「选帝之仪」的佛拉基亚皇族不会立墓。

由于「选帝之仪」的习俗，不仅对败者不会给予任何同情，而且很少有遗骸不会化成灰烬，还能残留下来。

因此这个普莉丝卡•班奈狄克刻有墓志铭的墓碑算是例外。

包含少女遗体葬在这个墓地中的事。

「虽然是与妾身十分相似的女孩……没想到会连续两次派上用场。」

少女回想起「选帝之仪」开始前，为了引诱出送来的刺客而牺牲的分身──那位完成保护公主职责，同样的发色少女。

她的遗体经过仔细修整，连同奖赏一起送回家族身边。但即使已经成为遗体，她似乎仍然被指派了职务，不得安息。

不只是生前，连死后都得伪装成「普莉丝卡•班奈狄克」。

「……真是辛苦你了。」

少女如此说完，便将手中的红色扇子发出声响打开。她用这把从可恨的姊姊手中抢来的扇子对自己搧着风，迈步走向在后面等候的老妇人。

接着──

「公主……」

「不是公主，别让妾身一直提醒这件事，拥有这个名号的公主已经凄惨死去。可怜的是，受到了未抹除忠臣忧虑的报应，目前在这里的是……哼，又是什么人呢。」

面对歪头思索的少女，老妇人闭起眼睛停了一拍后，回答：

「──普莉希拉。」

「说的也是。」

大方地点了点头后，少女发出声响阖起扇子。虽然没办法像那个姊姊一样将扇子夹在丰满双胸之间，但不久以后应该就能做到同样的事了。

她还活着──活着就还有未来。既然如此……

「继续活下去吧。毕竟──」

少女仰头看向天空，在几乎令人憎恨的苍穹远方，能够见到赤红燃烧的太阳。只要伸出手试图掌握，「阳剑」的热度便会留在掌中。

确认过这股热度后，少女──不，普莉希拉笑着说道。

「──世界就是为了妾身量身打造的。」

《完》

** 『赫炎剑狼』

1

──对所有人而言，与自己性命无关的杀戮便是娱乐。

虽然认为这是很极端的意见，但从目前自己身处的状况来看，却有无法一笑置之的说服力。

在头顶倾泻而下的欢呼声中，从坚硬地面向后翻滚。即使这种难堪的逃脱模样让欢呼声变成咒骂，但顾不得这么多了。

「我也是在赌命啊……！」

将痰与怒骂声一起吐出，右手握着与身体同宽的剑朝向正面作为牵制，于是试图进行追击的对手便停下光脚。

血色苍白的秃头男垂着双手，阴沉地发出嗤笑声。

罕见的是，秃头男并没有拿着武器。然而这位摇晃身体男子的双手，某种层面上带有比剑或枪更为凶恶的武器。

──有种技术名为「毒手」。

那是持续将人类的手浸泡在毒药中，在不会丧命的程度下持续累积毒素的暗杀技术。毒素会留在持续浸泡的手指或指甲中，成为光是掠过身体便能杀害对手的武器。

男子染成红紫色的手，正重现出毒手的样貌。

「应该不是暗杀高官显贵失败的忍者吧。」

从毒手与毫无迷惘的杀气，开始推断对方的来历。

忍者是让身体经过极限锻炼与超乎常理改造的刺客。虽然是否实际存在令人起疑，但基本上在传闻中都自然地视其为存在。

忍者多数是受到权贵雇用，身为权谋术数中互相暗杀的尖兵。虽然不知道原因为何，但在这里出现应该是受到囚禁吧。

毕竟这个地方就是──

「──让剑奴互相对战的恶心场所，剑奴孤岛『基奴海布』。」

写成剑之奴隶，念作「剑奴」──

这就是互相战斗两人的身份，也是每天有许多流血碎骨、失去性命的低等贱民之总称。

而在剑奴孤岛反覆举行互相杀戮的活动，也是观战的心态扭曲的群众──帝国居民满足血肉饥渴的绝佳场所。对于贯彻残酷信条的神圣佛拉基亚帝国而言，这里是不可或缺的娱乐之处。

「就算是这样，我们随心所欲被玩弄一点都不有趣啊。」

单手握着沉重刀剑，口中如此喃喃自语，缓缓站起身。原本应该是长时间挥舞会颇为疲累的重型刀剑，可惜只能用右手努力奋战。

毕竟已经失去了原本能用来辅助右手的左手。

「────」

独臂男子的凌乱长发绑在后脑勺，以能够称为凶恶的眼神瞪着对方，借此尽可能进行牵制，并深深叹了一口气。

其实并非是最近，而是满久以前便失去了胳膊。原本以为自己已经习惯了这种不平衡的感觉，但像今天面对这种需要耗尽心神的对手，也很常会感到负荷沉重。

「大概就是这样，我尽量不想拖太久。怎么样？看起来像忍者的大哥，要不要和我串通好来场没收比赛？」

「……没收比赛？」

「喔？你有兴趣吗？」

听到这个提议，毒手男子严肃地皱起眉头。从这种反应感觉到对方有兴趣，单手男便抓准机会积极地继续说：

「很简单，只要我这样继续逃跑，然后大哥攻击也打不到。拖久之后，观众与主办者会越来越着急，然后我猜会把突破僵局用的魔兽之类放进来。到时候敌人不是我们两个，应该就会变成魔兽了。」

「……合作打倒魔兽撑过今天，意思是这样吧？」

「对对，就是这样。什么嘛，大哥真好说话……唔哇！？」

正当以为对方脑袋很灵光而露出笑容时，毒手男突然将锐利指甲挥了过来。千钧一发地仰起身体躲过这击并再度翻滚后，单手男拉开距离盯着对方。

秃头男投以鄙视眼神，实际上还用不屑语气说着「无聊」。

「合作对付魔兽？为什么非得特地选危险的路？如果是单手男和魔兽，不管是谁都会选前者，我也一样。」

「不不，我是能懂你的想法啦。可是我们都是人类……」

「而且这里可以展现我锻炼过的技巧，哪能忍受这么充足的准备被阻碍。」

「呃……原来是以杀人为天职，价值观完全不同，难怪没办法沟通啊。」

虽然想搔头，但只要一放下牵制的手腕，对方肯定会发出致命攻击。于是仅仅只叹了一口气，这时对方的毒手突然开始摇晃。

直觉到对方准备展开攻势──不，应该说是已经知道了。

对方会刺出右边毒手，只要躲过就会假装挥出左手，然后踢出不是毒手的毒脚给予对手致命一击，真是大费周章。

然而，这种已经被掀底的手法不需要吃惊。

「──！」

躲过刺来的右边毒手，用眼角余光盯着移动的左手，以刀身配合对方旋转踢来的脚。被刀身吸入的膝盖被砍断，喷出漆黑鲜血，些许鲜血喷溅到身上，脑中想着「血液里面至少也该混进毒素吧」──

「运气……不对，要怪就怪这颗星吧。」

语毕，无法相信自己败北的男子首级便高高飞向空中。

2

「今天获胜也是很惊险啊。」

「哎呀，我也觉得如果能用不危险的方式获胜当然是最好啦。可是对一个年过三十的单手大叔来说，这种俗气的获胜方式已经是极限了。」

离开欢声雷动的竞技场后，回到剑奴用的通道时，有个人出来迎接。

是这个竞技场配属的看守之一。负责管理参加竞技赛事的剑奴，在剑奴中也有人亲昵地称为「奴隶商」。

不论如何，在大多对剑奴采取粗暴态度的看守中，眼前这个名为欧兰的看守，算是较为罕见对剑奴保持友好态度的人。

虽然对为人和善的他是否能担任看守存疑，但至少他既然在这里工作了几年，表示已经适应这种生活，与他相处也算是过了颇长一段时间。

多亏如此，与其说是看守与剑奴，双方的距离感比较接近朋友。

「拿去吧。」

单手男将沾满鲜血的武器交给欧兰。由于在赛事以外的时候禁止剑奴携带武器，还有必须在竞技场外面上手铐的义务。

不过对只剩单手的人上手铐，如同字面所述般徒具形式。

「好，手铐固定好了……不过话说回来，还好今天你也赢了。这种话由我来说好像很奇怪，不过你的对手风评很差。有两个看守被他抓着手死了，虽然听说只是意外……」

「使用毒手的人闹出意外，就跟自己用武器把头砍掉的失误差不多吧。」

「对吧？不过听说因为很少见过这种事，所以就不追究责任了。真是的，在这里剑奴和看守的命都不值钱，虽然不是只有这里就是了。」

欧兰带着苦笑这么碎念，他确实不适合看守这个职位。或许该说他并非不适合看守一职，而是不适合待在剑奴孤岛与整个佛拉基亚帝国。

不惜性命的竞争心态、绝对不容撼动的信念──这在帝国已经是推崇已久、根深蒂固的价值观，只会视博爱精神与慈悲为怀如敝屣。

具有正常伦理观念的人很难存活，这就是神圣佛拉基亚帝国。

「唉，至少比变成像我们这种剑奴好多了吧！」

「真的是笑不出来啊……对了，你获胜会很高兴的原因，当然不只对方风评很差，还有因为你是个不错的家伙。」

「喂喂，小心点啊。要是对我太好，搞不好会进攻略我的路线喔。」

「路线？」

「别在意，话说我们差不多该走了吧。」

欧兰对这个没听过的单字歪头表示不解，单手男拍了拍他的肩膀催促他移动。

毕竟站着说话有点尴尬，而且这里是连接竞技场的通道。出场参加下一场死斗的剑奴当然也会通过这里──

「──哎呀？我还以为是谁在这里闲晃，这不是阿尔小弟弟吗？」

「呃……」

确实如同猜想般撞见下个剑奴，让单手男发出响亮的咋舌声。

见到这个反应的瞬间，对方发出如铃铛般的「哎呀呀」回应声，左右晃着那修长身躯，愉快地靠了过来。

「呃这么大声真的很不领情呢。我们应该是朋友吧？」

「饶了我吧。要是到处宣传和你是朋友，麻烦事只会越来越多，你偶尔也去交点能站着聊天的朋友怎么样？」

「呵呵呵，阿尔小弟弟果然很有趣呢。」

这位将黑发剪短的高挑女性嫣然缓颊一笑，超过两公尺的身高在这个世界也算十分罕见，就真正意义而言是高挑身材。

彷佛夸示天赋的体格与凹凸有致的女性体态般，她穿着紧贴肌肤的服装，配上深邃五官，令人有种看似美术品的印象。

然而，她的双手比起这些特征更具特色。照理说她的手应该会拥有符合身躯的长度，但左右手都没有手肘以下的部位。

她背负着比单手更加夸张的缺陷，但这种不完全的姿态反而能增添风采。不像骂声连连的暖场演出，拥有能掳获全场观众的风采。

她就是剑奴孤岛「基奴海布」的首席表演者──

「──荷奈特，我很感谢你，可是稍微想想彼此的立场吧。像我这种小角色，在你身边一下就被吹跑了。」

「别说这么让人寂寞的话嘛，你可是我最好的朋友喔。」

「最好的朋友啊……只是因为其他家伙都被杀掉，才会让排名提高吧？」

「唔呵呵呵……」

毕竟是人员频繁替换的剑奴生活，排名变动也相当剧烈。并未否定这点，就是这个女人──荷奈特不会让人生厌的特色。

不仅是只要看过一次便难以忘记的容貌，言行举止也有掌握他人内心的毒性。简直像是蜂毒般，要是连续相处几次肯定会没命。

比起这种剧毒，刚才交手的男性毒手根本不足为惧。

「荷奈特大人，差不多该……」

「嗯，我知道，麻烦你了。」

称身为剑奴的她为「大人」的，没想到居然是管理剑奴的男看守。

荷奈特身边的欧兰同事跪在地面，将代替手腕的双脚枷锁解开，模样简直与臣下侍奉女王没有两样。

──这种让他人侍奉的天生特质，也是荷奈特被称为「剑奴女帝」的原因。

「你还是过得这么优雅啊……喔，好可怕喔。」

如此揶揄完全不像剑奴的荷奈特后，便被看守男瞪了一眼。被她彻底迷倒的看守只要被她下令，肯定会毫不犹豫地加害对方。

只不过──

「别想做傻事。好了，把我的『手』拿过来吧。」

「遵命。」

被荷奈特制止，看守弯下腰，并抬了抬下腭。接着，从通道深处出现用头巾遮着脸的狱卒，将放在推车上的两把大剑送了过来。

大剑约有大人身高的长度，但握把部分呈现奇特形状。这也是理所当然，因为这两把大剑是没有手腕的荷奈特专用武器──

「嘿咻。」

荷奈特发出这道妖艳的声音，将断掉的双腕朝向大剑，然后以手腕前端对准、伸进大剑握把的空洞处，发出坚硬声响加以固定。

她以手腕用力一举，便轻松地将看起来有一百公斤以上的大剑举了起来。

同时驾驭两把连常人都难以举起的大剑，没有人能够模仿她的战斗风格──这也是剑奴孤岛最强女王的真本领。

「阿尔小弟弟，难得有这个机会，看看我战斗的过程吧。今天的胜利不给别人，就献给你啰。」

「真是谢谢你这么鸡婆喔。」

再度感觉到看守憎恨的目光，阿尔仍然耍着嘴皮子如此回答。荷奈特甚至对这句话也露出微笑，便穿过他身旁走向竞技场。

一段时间后，现场欢声雷动，是整个会场见到她出现而沸腾的最好证明。

「好啦，那我回去地下睡觉了。」

「你……你这家伙居然把荷奈特大人说过的话……！」

「呃……我刚才也对本人说过不会看了吧。她不是有笑吗？那就是答案了。知道吗？」

近距离瞪着咄咄逼人的看守，见到对方被自己压过，便转身离开。

毕竟刚结束赌上性命的生死之战，看来自己也是难掩激动。

对方也有见到荷奈特笑着放过阿尔的景象，继续找碴也是于事无补，只能不甘心地保持沉默。

「哎呀，真是紧张死了。她的气氛感觉就不像是个剑奴嘛。」

穿过闭嘴的看守身旁，走向竞技场的反方向，与欧兰并肩前进。自从荷奈特出现后，他就像是完全掩盖气息般躲了起来，这也是正确的选择。

不论好坏，避免遇见荷奈特是最好的选择。让她产生兴趣与否都麻烦至极，这也是这个孤岛的规则。

「不过话说回来，阿尔迪巴兰，她还真喜欢你。」

「……饶了我吧，欧兰大哥。而且我不是说过吗？」

对于面无恶意地搭话的欧兰，单手男──阿尔迪巴兰朝他闭起单边眼睛。

「叫我阿尔就好，我不是很喜欢全名。」

3

──剑奴孤岛「基奴海布」。

那是位于神圣佛拉基亚帝国西部，周围被湖泊围绕而被称为「绝水孤岛」的场所。

进出岛屿仅仅只能使用一条桥，而且还是平时无法通行的可动式吊桥。出入均会经过严格管制，将岛内外隔绝的理由相当单纯明瞭──便是避免关在岛上的剑奴逃脱的措施。

写作剑之奴隶的剑奴如同字面所述般，是容许拿剑的奴隶名称。

然而，只有在座落于岛屿中央的竞技场进行生死对决时才能拿剑，而这种对决是提供给岛外前来之观众的娱乐活动。

简单说来，这个岛便是让奴隶互相残杀作为表演活动的恶心场所。

多数剑奴不是罪犯，就是无法偿还借款、被迫卖身的借贷人，也有走投无路的不幸家伙会极为罕见地被抓到这里。

但不论是何种境遇，只要沦落为剑奴，就只有同样下场。

──只能在生死对决中获胜，杀害对手延续性命。

「──阿尔先生，偶一直在想啊，这样下去真的好吗？」

在剑奴孤岛的地下，有个让剑奴生活的居住区。

即使说是居住区，丝毫没有修整成适合居住、或是备妥生活用品之类的贴心安排，只是单纯把剑奴丢在这个空间之中。

剑奴们在地下各自占据地盘，被带到竞技场进行生死对决之前只能虚度光阴，阿尔也不例外。

正当他感谢着今天也能平安回到睡床，准备躺平时──

「咦？阿尔先生？你有在听吗？阿尔先生～～」

「────」

阿尔对这道娘娘腔的男性声音皱起眉头，在坚硬地面上翻过身，背对着对方，表明自己不想说话。

然而，对方无视阿尔的态度，发出「喂喂」的声音摇晃着他的肩膀。

「唉唷，听我说啦。我在说很重要的事耶。」

「没兴趣，我才想说可以考量一下我的心情吗？我刚打完一场，很累很想睡，现在只有睡觉能好好享受了。」

「又在说这种话，除了睡觉以外还有别的乐子吧，毕竟阿尔先生那么受欢迎。」

对方笑着持续纠缠，抬起下腭指了指远方能够见到的人影。是一群穿着煽情服装的女人，立场也算是剑奴的岛上娼妓。

她们几乎不曾作为剑奴被叫到竞技场进行生死决斗，但取而代之的职责，便是成为岛上剑奴发泄不满的管道。

阿尔从来没有自大到会觉得自己受那群女性欢迎，然而──

「唔呃……」

「哇啊啊！阿尔先生！刚才那会不会太没礼貌啊！是很美丽的女性们喔！？职业不分贵贱吧！」

「……不不，我不是歧视职业，只是精神上没办法接受。」

被突然如此责备，阿尔按捺着涌现的呕吐感，脸颊一歪。

敷衍地对女性们挥了挥手后，她们带着微笑回挥着手，为了寻找工作对象各自散去。

根据对象不同，这群女性很常被玩坏，也很少会受到温柔对待。但她们在这种环境下还是积极地活着，怎么还能粗暴地对待她们？

「明明不擅长面对女性，却对女性怀着敬意，也能理解阿尔先生为什么会受到爱戴了。」

「我只是没有选择权，不然像我这种落魄大叔根本没人会想看啦。」

「嗯……好卑微，不过偶也喜欢阿尔先生这种地方就是了。」

语毕，眼前相貌堂堂的帅气男子朝阿尔如此笑着说道。对于男子亲昵的态度，阿尔面露苦涩地叹了一口气。

这名将灰色头发留长的帅气青年名为乌比克，是大约在五年前被带到基奴海布的剑奴之一。

虽然是个身材细瘦的高挑美男子，但并非拥有优秀实力，或许该说他对战斗一窍不通，要是被丢进竞技场，肯定会转眼间遭到蹂躏。

他在这五年内活下来的原因，与先前那群女性相同。

虽然荷奈特算是例外中的例外，在剑奴中也有不少实力优秀的女性。因此待遇与男性剑奴没有两样，也有职责为满足这些女性的人。

乌比克便是靠着这点活到现在的其中一人。

「话说阿尔先生，关于刚才那件事的后续……」

「我就说没兴趣陪你聊那件事了，听人说话好吗？」

「哎呀哎呀，别这样说嘛。毕竟可是『剑奴女帝』直接邀约喔。」

「让我更没兴趣听了。」

话题提到这个暂时不想见面与听闻的名字，让阿尔眉头深锁，这种反应让乌比克笑了。

「对荷奈特小姐摆出这种态度……阿尔先生是勇者无惧吗？」

「说什么傻话。刚才你也看到了吧？我就是普通地怕女人，所以我也怕荷奈特，QED。」

「丘益滴……？又是阿尔先生那边的方言吗？听不懂是什么意思啦。」

对于阿尔口中说出的陌生字眼，乌比克歪着头表示不解。

话虽如此，阿尔不打算特地解释。乌比克很熟悉阿尔此种态度，因此也没有继续追究的意思。

但就算没有追究话题，还是坚持想继续聊天。

「总之听偶说嘛。不然偶下次被荷奈特小姐叫过去的时候，肯定会被榨干的。这样也会让阿尔先生很有罪恶感吧？」

「有够麻烦……听完之后可以不要打扰我的睡眠时间吗？可以的话姑且听你说说吧。」

「哈哈，阿尔先生果然很善良，不擅长面对女性真的很可惜。」

「少啰嗦。」

让乌比克不再耍嘴皮子后，阿尔催促他继续说下去。

接着，乌比克总算切入正题。而内容就是──

「其实最近这里的竞技场要举办活动，而且还是有很多帝国权贵会来访的大规模活动。」

「喔？不知道已经几年没办过了，怎么又突然想到要办活动？」

「因为佛拉基亚皇帝驾崩，新任皇帝刚上任的关系，简单说就是皇位候补已经全部死光了。」

「全部死光怎么还会有下任皇帝……喔，是最后剩下的候补成为皇帝，才会说是候补全部死光吧。」

以理解能力填补乌比克没说清楚的部分后，阿尔静静地闭起单边眼睛。

就连在这座孤岛，都听说过神圣佛拉基亚帝国皇帝驾崩，以及举行「选帝之仪」选出下任皇帝的事。

既然如此，也能理解这里为何会举行活动庆祝帝国新陈代谢。

「其他家伙可能还不习惯，不过这里偶尔也会有季节性的活动……虽然对我们来说都不会是什么好事啦。」

「真不愧是在剑奴孤岛待了十年的选手，经验就是老道，让偶好尊敬喔。」

「回想起自己的足迹都会浑身不舒服，别再说了。」

对称赞挖苦各半的乌比克回以咋舌，阿尔回想起以前的例子。

以往剑奴孤岛趁着帝国庆祝所举办的活动，大多数都是把剑奴丢进与平常不太相同的「死斗」中。例如改变平常一对一的生死决斗规则，根据场合也出现过组成十人队伍，与特地为了活动抓来的巨大魔兽对抗。

「四年前对付那个像山一样的魔兽大概是最累的……要是没有荷奈特就会全部死光，那只魔兽的角现在还挂在大厅装饰。」

「那已经被流传成传说之战了。听说除了阿尔先生和荷奈特小姐以外，当时所有剑奴都死掉了。」

「那也是我被荷奈特盯上的原因。」

原本只被当成是不足挂齿的小喽啰，不小心从地狱活着回来，让她对阿尔产生兴趣。现在只要擦身而过就会被缠上，可说是增添不好回忆的头号麻烦人物。

但四年前那场激战也是多亏了她才能活下来，所以不能算是完全没有欠下人情。

「就算是这样，不喜欢的东西就是不喜欢。所以荷奈特说了什么？」

「不不，不是什么很难的事。只是这个活动与平常不一样，会有平时不会出现的嘉宾来访。也就是说……」

「────」

「──把帝国的上级伯爵之类当成人质，说不定有可能要求释放。」

乌比克压低声量说出这句话，让阿尔闭起眼睛。

原因除了话题内容本身──

「你们真的是很不死心，这种计划是要说几次啦。」

因听了好几次这种难以实现的梦话而涌现出的疲劳感才是主因。

剑奴孤岛解放计划──不只是乌比克，这也是岛上多数剑奴的梦想。

只要待在这个岛上，剑奴便会持续被迫处于无法预测明日未来的立场，希望获得解放也是理所当然。

话虽如此──

「这种梦想别说是几百个人，甚至有几千个人想过吧。可是没有半个人成功逃出去，你知不知道这是多有勇无谋的计划啊？」

「偶知道啊，可是……当初是缺乏周详计划与执行能力之类才会失败，简单说就是注定失败才会失败。」

「也是有这种看法啦……」

虽然他说得冠冕堂皇，但那才是理论上每个人曾经梦想过的理想论调。

总而言之，这个意见并没有强烈到足以让阿尔忽视抗拒感。

「应该说，我不觉得荷奈特会认真参加这个计划。那个女帝喜欢住在这里，她是很喜欢战斗的狂战士。」

在这里能够过着身为剑奴例外的无拘无束生活，又能满足自己的欲望。

找不到荷奈特需要放弃这种待遇的理由，表示荷奈特要求转告这个提议的前提本身就相当诡异。

「我没说错吧？你现在赶快道歉，我可以原谅你。」

「啊哈哈哈哈……哎呀，果然还是不行吗？看荷奈特小姐好像很中意阿尔先生，偶以为只要先说服阿尔先生就没问题了……好痛！」

「我只有说可以原谅你，但没有说绝对。」

拳头打在毫无悔意的乌比克头上，阿尔将泪眼汪汪的他拨开。

光是听完这些话浪费的时间就亏大了。总而言之，把最近会在剑奴孤岛举办大型活动这件事记起来或许会比较好。

身为过去被各式各样的活动凌虐，而且体会过无数次类似「死亡」体验的人。

「所以才得努力逃出这种困境……」

「快给我滚开！下次就不会手下留情了！」

朝迟迟不肯放弃的乌比克挥出拳头，才总算赶跑这个瘟神。

虽然刚才那么说，他应该也不觉得解放计划能够成功──到头来那对剑奴来说还是遥远梦想，是绝对不可能实现的愿望。

而且，阿尔已经花了太多时间怀抱这个梦想。

──甚至认为既然已经在剑奴孤岛身为剑奴活了超过十年，不可能再得到除了这里以外的生活方式。

4

室内笼罩着紧迫干涩的紧张感，让老练管家挺直背脊到几乎发出倾轧声的程度。

对老管家而言，这份侍奉他人的工作是天职。在彭德尔顿家连续侍奉长达五十年，从现任主人的双亲时代便持续工作至今。

主人给予了诸多恩情，即便没有恩情，仍有陪着主人成长的亲爱之情。简而言之，便是希望主人能够得到幸福。

然而──

「──嗯。」

拿起管家送来的红茶茶杯，用形状美丽的鼻子享受着茶香。

蒸煮茶叶的时间与水温等等，这些基础条件应该都已经达成。即便规矩之多令人吃惊，但实际上，茶香与味道也会产生剧烈变化。

是否具有源自丰富知识的审美观，已是在这间宅邸工作的基本命题，为的便是能够提供更多奉献与对主人展现敬意。

若是说到会有何种抗拒，顶多只有对持有审美观的人会有意见吧。

「──夫人，味道如何？」

「香气算是及格，再来就是味道吧。那么……」

管家弯腰侍奉的对象，是在这间宅邸仅次于主人的人物，也就是长年给予恩情的主人──裘拉•彭德尔顿的伴侣。

「────」

樱色唇瓣抵在茶杯上，那品尝着红茶的侧脸让管家眯起眼睛。

对久久没有天赐良缘的主人而言，这是相当晚的初次结婚。光这件事便值得感到高兴，即使对方是年仅十二岁的少女。

双方有年龄差距的婚姻在贵族之间并非罕见。为了加强家族之间的凝聚力，贵族之间时常会互相联姻，但即将五十岁的主人迎娶十二岁的夫人，对相处已久的管家而言仍然是相当令人吃惊的事。

而且与这位夫人结婚不会有半点利益。

即使如此，主人裘拉的善良心肠仍然无需赘述。在帝国贵族之间很难找到这样品格高尚的人，身为管家，为此种主人鞠躬尽瘁也是理所当然。

这位少女肯定会对新环境感到诸多困惑，因此必须竭尽全力支持──管家如此暗自下定决心，将主人的年幼夫人迎接至宅邸。

当见到夫人的真面目时，管家的静谧决心便随之化为灰烬。

新夫人确实只有十二岁，年幼的她无依无靠地来到宅邸。

但她的美貌令人夺目，灵魂甚至比火焰更加炽热燃烧。

──普莉希拉•彭德尔顿。

这便是裘拉•彭德尔顿的妻子，也是宛如支配者般君临这间宅邸的鲜明少女之名。

「还不差。」

少女的白皙喉咙发出吞咽声，以彷佛直达脑髓的美妙声音如此说着。

管家慢了半拍，才察觉到这是对咽下红茶的感想。原因出在少女那若无其事的侧脸，她那美貌让管家看傻了眼而静止不动。

接着，时间开始转动，理解到这是称赞话语的瞬间，全身便开始颤抖。

明明少女只活了甚至不到管家四分之一的岁数，这声称赞却让他浑身热血沸腾，一股酥麻的感觉紧紧掌握住灵魂。

对已老的他而言，管家这个职业是天职。

既然如此，管家服侍眼前这位与生俱来身为支配者的少女，不也是理所当然的事吗？

──毕竟服侍便是等同于受到支配。

「退下，妾身有事对夫君说。」

「遵命。」

管家行了个礼，遵从命令向后退下。

在离开房间时，不知道夫人是否能再喝一口杯中的红茶呢？那个年幼支配者是否能再回应刚才工作的功劳呢？

渴求地怀着这样的愿望，老管家静静地离开房间。

「……大家都被你迷得神魂颠倒啊，普莉希拉。」

管家离开房间后，只剩两人的客厅微微传来这道孱弱沙哑的声音。

声音来源来自房间深处，姑且算是坐在上座的某位初老男性。那开始斑白的头发感觉不到霸气，这名男性就是宅邸主人裘拉•彭德尔顿。

既是神圣佛拉基亚帝国的中级伯爵，也是幸运继承了颇高地位与家世的男人。

而裘拉投以怯懦目光的对象，正是在明亮橙色头发上戴着镶嵌宝石的发饰，而且拥有如血般鲜红眼瞳的美少女普莉希拉。

虽然这对夫妇年龄差距甚远，但说话方式却像是稍微拉开了心灵距离。面对丈夫战战兢兢的态度，普莉希拉发出「哼」的嗤鼻声。

「别畏畏缩缩还用那种沙哑声音说话，你的声音和风根本没办法区别。还是刚才妾身听错了，其实那是风声吗？」

「不、不是……没那回事，是我说的话……只是看佣人们好像对你敞开了心房，我只是想说这件事。」

「哼，哪壶不开提哪壶。说敞开心房真是没看人眼光。」

对于普莉希拉这番话，裘拉「咦？」地瞪大双眼。看着丈夫这种傻呼呼的反应，普莉希拉说着「听好了」，闭起单眼。

「他们不是对妾身敞开心房，只是遵从而已。他们原本是除了侍奉他人以外没有任何存活方式的人，因此当妾身展示出道路，就会很高兴地摇着尾巴。」

「原、原来如此……？」

「或许该说，率领着那些乖巧的凡庸，真亏你能制得住那群人。」

「制得住……？不好意思，我听不太懂你的意思……」

「────」

裘拉仍然含糊回应，普莉希拉单眼传来的视线变得更加锐利。但即使对这种炽热的视线感到怯懦，裘拉的态度依旧没有改变。

「──让人更无法理解了。简单来说，你缺乏身为人必须具备的欲求与冲动。虽然也不是没有这种人，但是……」

「但、但是……？」

「如果真是如此，无法理解你迎娶妾身为妻的理由。」

对于裘拉支支吾吾的回应，普莉希拉仍然带着锐利视线如此补充。

裘拉的个性说好听是善良，说难听便是缺乏风骨与冒险心态的胆小鬼。只要能一路走得顺遂，就绝对不会选择未经开拓的道路。

虽然不有趣却很踏实，这在尊崇轰轰烈烈人生的佛拉基亚帝国可说是十分罕见。

被看轻为懦弱，或许就是到了这个岁数仍然单身的理由吧。

不冒险或豪赌，这应该就是裘拉•彭德尔顿的信条。

而裘拉迎娶普莉希拉为妻的举动，与这种信条可说是恰好相反。

这已经不是豪赌之类的问题。

毕竟──

「妾身应该已经对你表明过真实身份──妾身就是在『选帝之仪』传闻已丧命的皇女普莉丝卡•班奈狄克。」

普莉丝卡•班奈狄克──那是在争夺佛拉基亚帝国皇帝宝座的「选帝之仪」中败北，据闻已经死亡的皇女姓名。

然而普莉丝卡并没有死亡，而是诈死，现在仍然活着。

不是使用本名，而是改称为先前那位见习礼仪的少女名号，后来随夫改姓为普莉希拉•彭德尔顿。

这是经过各方人士努力，努力挣扎着让少女活下来的结果──但普莉希拉嫁给裘拉时，并没有对他隐瞒这件事。

当然，如果知道这件事还拒绝，普莉希拉肯定不会留他活口。就这层意义而言，普莉希拉的告白对裘拉除了灾难以外别无益处。

然而，即使得知内情，裘拉没有拒绝与普莉希拉结婚。

原因究竟为何？甚至连能让老管家在短时间内心服侍奉的普莉希拉，都无法看穿裘拉有何意图。

「────」

听到这番话，裘拉稍微瞪大双眼，然后微微缓颊一笑。

反应就像不懂问题答案的幼小孩子般令人莞尔。

「就算是夫君，也无权用这种眼神侮辱妾身。」

「抱、抱歉……虽然很意外，但我也懂了。之前的你是个能理所当然地看透所有事物的幼小贤者，所以……」

「所以？」

「也有符合岁数的特色呢。」

从现在普莉希拉的心情来看，这种说话方式也是十分豪赌。

让她甚至差点开始检讨「干脆把他的头砍下来」的选项。

「别、别担心，我没有想过利用你或是把你交出去，这些都是毫不虚假的真心话。」

「……算了，打从一开始你有什么企图都没关系──毕竟这个世界就是为了妾身量身打造的。」

「────」

这是不知该称为天运还是宿命的普莉希拉独门哲学。

说出这句话的瞬间，裘拉的表情再度出现柔和的变化。不过普莉希拉还来不及追究──

「──老爷，非常抱歉。」

刚才离开房间的管家，随着敲门声再度回到客厅。

虽然打断夫妇相处的时间很不识相，但这不像是资历老练的管家会做出的行为。而从他接下来的报告便清楚地能够看出理由。

「德拉克洛伊上级伯爵的使者来访。」

「德拉克洛伊伯爵的使者？没听说这件事啊……普、普莉希拉！？」

裘拉对管家的报告皱起眉头，普莉希拉突然快步走出房间让他吓了一跳。但普莉希拉并没有因为丈夫的声音停下脚步，而是迈步走向门口大厅。

接着，当普莉希拉在宅邸门口现身时……

「喔？怎么出现了这么可爱的小姐呢？」

某个陌生青年对普莉希拉的模样挑起眉头。

这位看似十七、八岁的年轻青年搂着细长布包，浮现出和善笑容，朝普莉希拉挥了挥手。

「是彭德尔顿伯爵的女儿吗？请问你爸爸在不在家……」

「白痴！巴尔！彭德尔顿伯爵没有小孩！别自己预设立场！」

青年的后脑勺被身旁的矮小男子重重敲了一下。

随着清脆声响，让青年发出「好痛！？」的惨叫。

「怎么突然打我啦！迈尔斯大哥！就算里面空空没料，你也知道打破会很惨吧！」

「少啰嗦！既然知道没东西，就好好装满再来！别把你出的包连累到我身上！」

「出包！？什么是出包？我刚刚搞砸什么……」

「彭德尔顿伯爵最近才刚迎娶年轻夫人！用你那个草包脑袋好好想想，在没有女儿的彭德尔顿伯爵宅邸出现年轻女孩……」

「呃……原来如此。」

总算理解似地点了点头，青年用手摸着自己梳理整齐的栗色头发，身旁的矮小男子说着「总算听懂了啊……」，看似疲累地垂下肩膀。

「真是会找麻烦……巴尔，要不是从小时候就混到现在的孽缘，我早就把你这个没头没脑的家伙丢着不管了。」

「哎呀，在迈尔斯大哥面前真的是抬不起头啊。可是大哥这么说，你自己不也是稍微搞砸了吗？」

「什么？我哪有……唔呃……」

话题告了一个段落后，矮小男子看着两人争论的起源，浑身僵硬。

原因不疑有他，身为争论源头的普莉希拉望着两人没有插嘴，发现视线聚焦在自己身上后便耸了耸香肩。

「怎么？不用顾虑妾身，继续说。很少见到小丑互骂，还满尽兴的，快点继续吧。」

「唔喔喔……被乳臭未干的小丫头完全玩弄在股掌之间……！」

「这样不行喔，大哥。说话越来越难听了，总之先道歉吧？」

「唔唔唔……」

大小二人组似乎对普莉希拉的话语浑身颤抖。虽然没有特别想捉弄两人的意思，但放弃这种不管说什么都很有效果的丑角实在很可惜。

「普、普莉希拉，他们是我的客人，可以不要太捉弄他们吗？」

「唔，赶过来了啊。」

在普莉希拉思考接下来要说的话时，裘拉从后面赶了过来。一见到与普莉希拉对峙的二人组，便发出「嗯」的声音微微挑起眉头。

「听说是德拉克洛伊伯爵的使者……原来是你啊，迈尔斯小弟。」

「彭德尔顿伯爵……！好久不见！」

裘拉说出其中一人的名字，似乎认识矮小男子迈尔斯。他当场单膝跪地，身旁青年也连忙效仿这位情同兄长的动作。

此种态度很显然不习惯身为使者，裘拉见状便开口询问：

「他是谁？没看过他呢。是新人吗？」

「是的，他是我的儿时玩伴，有幸能向德拉克洛伊伯爵引荐。他有『操纵飞龙』的非凡才能……喂，向伯爵打声招呼。」

「好好，我来打声招呼。」

在迈尔斯催促下，单膝跪地的青年抬起脸看着裘拉。瞥着被他那率直眼神压迫的夫君，普莉希拉对他浑身涌现出的霸气眯起眼睛。

隐瞒在年轻的轻佻态度下，这名青年可说是相当杰出的人才。

无视于普莉希拉的评价，青年将手抵在自己胸前。

「请让我自我介绍，我是巴尔罗伊•特梅格里夫。迈尔斯大哥从小时候就很照顾我，现在也是一样。」

「原来如此，毕竟迈尔斯小弟很会照顾人。『操纵飞龙』意思是……」

「是，收养了一头还算满冒失的家伙啊。」

与紧张毫无缘分的青年──巴尔罗伊原先带着天真无邪的笑容，但只有最后补充那句话时，笑容突然改变了。

变成不知该说是桀骜不驯，还是充满自信的笑容。

「『操纵飞龙』……是让不亲近人类的飞龙服从，也是部分家族流传的秘术吧。」

「对对，亏你知道这件事。明明年纪小还这么勤奋学习……痛痛痛痛！」

「我说你啊！至少！多学点东西！」

（插图011）

迈尔斯捏着随即放软姿态的巴尔罗伊屁股，气冲冲地这么说。面对两人的对话内容，裘拉说着「哎呀，不会不会」并挥了挥手。

「不用这么吹毛求疵。是我没有向你们介绍，她是普莉希拉•彭德尔顿……是我的妻子。」

「接近五十岁的男人，只是介绍妻子不需要这么害羞，大方一点。能迎娶妾身已经是地上最幸运的男人了。」

对于裘拉似乎只能以「战战兢兢」来形容的介绍，普莉希拉发出冷哼。于是裘拉对这种语气回以苦笑，巴尔罗伊与迈尔斯皆目瞪口呆。

「哎呀哎呀……刚才稍微聊个几句的时候也有想过。彭德尔顿伯爵，夫人个性真是剽悍啊。」

「多亏这样，完全被她压得说不出话啊。」

「蠢货，这样才更应该感到光荣。还有别用剽悍这种狭隘字眼形容妾身，凡夫俗子──不，凡夫俗子这个字眼不适合你们。」

「呃……可以把这句话当成夸奖吗？」

面对普莉希拉打量般的视线，巴尔罗伊一脸疑惑地看向裘拉。但裘拉也无法控制新婚妻子，这位中级伯爵只能面露尴尬地回以陪笑。

而先前保持沉默的迈尔斯对这种状况似乎耐不住性子，于是率先发难。

「呃……咳哼……彭德尔顿伯爵，我们带着主子捎来的信，可以把信交给您了吗？」

「嗯、嗯嗯……不好意思，是瑟莉娜写的信啊。不知道内容是写什么？」

「应该是剑奴孤岛的事吧。」

「剑奴孤岛……说的也是，还有那件事。」

裘拉收下封蜡的信件，准备过目内容时吐出一口气。虽然反应像是听到不太喜欢的字眼，然而──

「剑奴孤岛……『基奴海布』啊。这么说来，妾身还没有亲自去过一趟。」

「喔？夫人也有兴趣吗？哎呀，其实我也想去那边看看，所以对这次的活动很有兴趣喔。」

「嗯，应该是你家主子想招待妾身的不肖夫君去剑奴孤岛吧。」

「嗯嗯，是这样没错……咦？迈尔斯大哥，你怎么了？」

普莉希拉很快理解了对方来访的真正目的，巴尔罗伊轻浮地点着头表示同意。听到小弟与普莉希拉说的内容，迈尔斯便面露苦涩地说「那我们是为了什么还要送信啊……」。

看来这位小弟似乎让他感到颇为棘手，但这也是无可奈何的事。

「要是倒进不合容器的水量肯定会溢出，如果不想让内容物洒出来，只能随时把嘴巴抵在容器边。就算是这样，总有一天还是会满溢而出。」

「……我会铭记在心。」

看来他的脑袋还不算迟钝，从他不会把普莉希拉的话语当成丫头在胡言乱语，也能看出迈尔斯受到巴尔罗伊仰慕的理由。

接着就是──

「虽然很感谢德拉克洛伊伯爵邀约，但目前寒舍也是不太稳定的状况。所以……」

「──别管那家伙说的话，妾身接受去剑奴孤岛的招待。」

「普、普莉希拉！？」

裘拉摺起信件，原本想郑重拒绝的话语却被普莉希拉打断。裘拉难得显露出强烈感情，将脸靠向普莉希拉耳边。

「普莉希拉，剑奴孤岛有很多人进出。说不定会有认识你的人……」

「只因为这个理由拒绝吗？那妾身告诉你接受这场招待的理由吧。」

「理由？是、是什么……」

「很简单──就是妾身对剑奴孤岛有兴趣。」

裘拉惊愕地瞪大眼睛。

那就是普莉希拉的骨干思想，也是妻子对丈夫的可爱请求。但以目前身处的环境而言，用「可爱」形容实在有些太过特殊。

总而言之──

「────」

「彭德尔顿伯爵，您意下如何？主子不会急着要求答覆，您可以仔细考虑看看……」

普莉希拉的话语令裘拉浑身僵硬，迈尔斯见状便出言相救。但裘拉面对他的担忧只是摇了摇头，回答：

「不，不需要等待回答……请转告德拉克洛伊伯爵会接受招待。」

「喔喔，那真是太好了。主子肯定会很高兴啊。」

听到裘拉虽苦恼仍然如此回答，巴尔罗伊由衷地感到高兴。另一方面，迈尔斯朝裘拉投以五味杂陈的目光，但没有对这个判断插嘴。

相反地，他只是深深弯下腰，说「瞭解了」，接受回应。

「那么，详细日期会依照信件所述。如果需要，也能将回应带过来……」

「不用，只要你们脑袋不是空空如也，就不可能会忘记妾身的回应。把这件事回去告诉你们主子就好。」

「哈哈大哥，被念了耶。真是完全无法回嘴呢。」

「吵死了！」

结果迈尔斯无法保持身为使者的体面直到最后，怒骂声顿时传遍整间宅邸。

5

两头飞龙大大张开双翼飞向空中。

飞龙在龙种中算是较为暴躁，甚至是据称凶猛特质接近魔兽的狞猛种族。与亲近人的地龙或是虽粗暴但仍可驯服的水龙相比，对待难度有根本上的差异。

让飞龙顺从的技术称为「操纵飞龙」，传说是自古以来只有佛拉基亚帝国极少数人能够学会的独门秘术。

而巴尔罗伊与迈尔斯是学会这种珍贵的「操纵飞龙」技巧的人才，也是帝国内据说不到百人的飞龙骑师。

「这么说来，妾身没有印象搭乘过翼龙。」

「普、普莉希拉，你该不会说想乘坐飞龙吧……」

「哼，不用那么慌张。妾身也不认为那是能轻松做到的事，还有，依靠本能存活的野兽，不可能完整地理解妾身的品味。」

「这样啊……没事，我放心了。」

目送着使者们飞离宅邸，普莉希拉瞥视着裘拉松了一口气的侧脸。

他仍然稀松平常地展现出懦弱印象，是个没有任何可看之处的凡庸男人，但他又刻意做出危险的抉择。

决定带着普莉希拉前往剑奴孤岛。

「嗯？怎么了吗？」

「──越来越看不透你这个男人的意图。嗯，或许该说就是这种男人，才能满足身为妾身伴侣的最低标准。」

想到裘拉无法捉摸的内心，普莉希拉如此喃喃说着。

如果只是单纯看上普莉希拉的美貌，想一逞兽欲，肯定连初夜都无法活过。另一方面，要利用普莉希拉的真实身份也太过危险。也就是说，她是个完全不适合打歪主意或设计谋略的炸弹。

结果感觉还是无法看穿他的心思──

「算了，比起现在没什么兴趣的夫君，还是剑奴孤岛比较能引起妾身的兴趣。」

「对、对夫君没什么兴趣让我很受伤啊……」

「如果不想受伤，就引起妾身的注意力吧。至少比起还没见到的新活动，现在的你是无法引起妾身注意的。」

被普莉希拉毫不留情地泼了一头冷水，裘拉沮丧地垂下肩膀。但不知是否韧性十足，即使落寞，他仍然继续说：

「话说回来，虽然刚才被你牵着鼻子走……你是认真要去基奴海布吗？」

「当然，德拉克洛伊应该是上级伯爵吧。要是答应邀约又反悔，对方认为受到侮辱、发动战争也不是什么奇怪的事。刚嫁来的家室灭亡也会让妾身感到心痛，这是不得已的决定。」

裘拉似乎显得更加无奈，但这时普莉希拉已经不将他放在眼中。

她的深红眼眸盯着飞龙离去的远方天空──理应在那个方向，让她那尚未膨胀的胸口感到雀跃不已的剑奴孤岛。

到时会有什么样的未来正在等待，就连普莉希拉都无法看透。

然而──

「结果如何都无所谓──毕竟这个世界就是为了妾身量身打造的。」

6

「──唔啊！」

感觉到一股类似恐惧的寒意，躺在地面睡觉的阿尔弹了起来。

他不知所以然地张望着四周，却没有见到任何人或物体。

「喂喂！阿尔！你刚才在干什么啊！是在玩吗？」

「嘎哈哈哈！想表演在上面就够了吧！」

见到阿尔的糗态，喝着酒的剑奴们发出嬉闹声。

既然有娼妓，也能大致调来酒或食物，这就是孤岛地下的环境。阿尔瞪着喝得醉醺醺、吵吵闹闹的那群人，用力抓了抓自己的黑发。

「喂，阿尔？阿尔小弟弟？你在生气吗？」

「别学荷奈特，会让我以为在做恶梦。」

朝语带捉弄的剑奴不屑地如此回应，阿尔缓缓地站起身。被酒鬼缠上实在是无法放松，于是他摇摇晃晃地旁徨寻找能独处的场所。

如果随便找个地方，被荷奈特或乌比克找上就麻烦了。一想到这里，便对「这个岛上只有欧兰能让自己心平气和」的事实由衷感到沮丧。

找着找着，阿尔离开令人窒息的地下空间，出外去吹夜风。

「────」

设置在岛屿外墙的巡逻用狭窄立足地，与开放给剑奴使用的地下直接相连。由于除了吊桥以外没有能从孤岛离开的手段，对出入内外的戒备相当松散。

不过，也许会有计划游过这片超大湖泊的人──

「在水生魔兽到处出没的湖泊，做出这种白痴举动只会丢掉小命。」

因此，一反剑奴孤岛漏洞百出的戒备体制，到目前为止没有出现任何逃狱者，在这种环境下，希望能获得释放简直愚蠢至极。

回想起白天乌比克提起的白日梦，阿尔烦躁地发出咋舌声。

平常应该会将这种胡言乱语当成耳边风，今天却格外在意。

「别在醒着的时候做白日梦嘛，真是蠢到不行。」

再度愤恨地如此呢喃后，抬头仰望的空中能够见到缺了一半的月亮。

半月看来显得特别明亮，但阿尔的注意力并非放在月亮上，而是朝着夜空中装饰般撒落的漫天星斗。

阿尔瞪着无数星辰，咬紧嘴唇。

「──一切都是星星的错。」

──这是个剑奴孤岛庆祝活动逐渐接近的夜晚。

7

──彷佛将「炽烈」拟人化的个性。

这便是普莉希拉对瑟莉娜•德拉克洛伊上级伯爵的第一印象。

以女性而言算是身材高挑，修长手脚经过相当程度的锻炼。即使如此，从中感觉不到粗俗的印象，由于体态凹凸有致，无法单纯用勇猛形容这位女性。

或许该说是美丽的猛兽。

一头锈红色的微卷发丝从背后放下，瑟莉娜并非身穿礼服，而是披着如商船船员般的宽大外套。虽然感觉会被暗中数落不像贵族，但在佛拉基亚帝国只要有实力，任何举止都能横行无阻。

那么，甚至被称为「灼热公」的瑟莉娜•德拉克洛伊，又有什么样的人敢对她指指点点？

「好久不见，彭德尔顿伯爵。近来可好？」

瑟莉娜如此说着，露出笑容，在她那工整面貌的左侧有条纵断脸部的旧伤。

那条白色大型刀伤，是被夺走家族领导权的父亲对她刻下的伤痕。由于在争夺家族领导权时直接将父亲活活烧死，因此被称为「灼热公」。

「嗯、嗯嗯……我很好，瑟莉娜，看你过得不错真是太好了。」

面对女杰态度轻松的招呼，裘拉浮现出孱弱笑容如此回答。普莉希拉的「最爱」夫君的懦弱态度一如往常，与害怕爵位差距应该是毫无关系。

上级伯爵与中级伯爵、男人与女人、强势与懦弱──两人在各种特质呈现对比，明明年纪相差二十岁以上，两人似乎是朋友关系。

不过说到年龄差距，普莉希拉与裘拉也没资格说别人。

毕竟是五十岁男人与十二岁女孩结为连理，瑟莉娜肯定也大感意外吧。

「那位就是传闻中的夫人啊。听闻彭德尔顿伯爵迎娶到颇为年轻的女孩，原本以为那就是长期单身的缘由。没想到……」

瑟莉娜瞥了裘拉身旁的普莉希拉一眼，打量着大方站在畏畏缩缩的裘拉身旁的普莉希拉。

「哎呀，传闻实在是不可靠。迈尔斯他们的报告很准确。」

「喔？那两个人的报告啊？他们对妾身如何美言？」

「他们说过有不合年龄的器量，还有想挫挫那股锐气。」

「──喔？」

对没有打招呼便开口搭话的普莉希拉，瑟莉娜只是耸了耸肩如此回答。

听到她的回答，普莉希拉眯起深红色眼眸，看向瑟莉娜身后待命的两人──先前身为使者，曾经露过面的巴尔罗伊与迈尔斯。

这道视线让迈尔斯耸了耸肩，巴尔罗伊带着和缓笑容回挥着手。

（插图012）

「哪边才是狠角色，不用多说了吧。」

「别这么说。虽然迈尔斯那副模样，看人眼光还是满准的，他们两个都是我珍贵的部下。不好意思，就算看上眼也不能让给你。」

「不需要。只有美丽到合乎妾身眼光，或是不会感到无趣的丑角才有资格待在妾身身旁，这两个条件夫君都没有达成就是了。」

「咦咦！？为、为什么这时候会扯到我？」

裘拉瞪大双眼。他破嗓的回应声让普莉希拉表示「大方接受吧」，并发出冷哼将细瘦手挽在胸前。

现在普莉希拉与裘拉夫妇离开熟悉的家，接受瑟莉娜•德拉克洛伊上级伯爵的招待，来到帝国西部地区。

目的是为了出席由剑奴孤岛「基奴海布」举办，祝贺佛拉基亚帝国新皇帝诞生的庆典。

「严格说来，选帝与剑奴孤岛没有任何关联，显然只是想拿新皇帝诞生当借口招揽观众。」

「夫人说话真是不留情面。是不喜欢这种活动吗？」

「不，对皇帝表示忠诚没有什么意义，妾身也不会心胸狭窄到责备草民沉迷这种娱乐活动，而且最重要的是……」

「最重要的是？」

「妾身喜欢观赏赌上性命的对决。」

普莉希拉从怀中抽出扇子，遮着嘴如此回答。结果瑟莉娜微微瞪大眼睛，然后「哈」地发出彷佛吐息般的笑声。

「不错！彭德尔顿伯爵，找到了不错的夫人啊！感觉和我很合得来，年龄还不能喝酒真是太可惜了。」

「别说了，我头好痛……普莉希拉，你应该不会做出这么轻率的举动吧……」

「蠢货，区区小酒妾身当然尝过，你以为妾身是何许人等？」

「普莉希拉！？」

普莉希拉的回答让裘拉大吃一惊，瑟莉娜显得更加愉快了。

双方结束会面后，瑟莉娜脸颊上的白色伤痕随着笑容皱起。

「不好。感觉越聊越尽兴，留到路途上再好好享受吧。」

「麻烦手下留情了……话说回来，记得基奴海布只有一座吊桥吧。考量到庆祝活动，感觉会很壅塞吧。」

「别担心，既然邀请了两位，就不会让你们无聊。」

瑟莉娜如此回答后，便在歪着头的裘拉面前弹响指头。以此作为信号，瑟莉娜身后待命的迈尔斯与巴尔罗伊展开行动。

「────」

两人将手抵在嘴边，高声吹响指哨。

而受到指哨声的呼唤──

「这是……！」

「飞龙啊。」

在一动也不动地睁大双眼的裘拉身旁，普莉希拉盯着从空中降落的身影。

两头飞龙张开巨大双翼，扬起强风缓缓降落。如果只是飞龙本身，前几天巴尔罗伊等人访问时也已经展露过了。

但这次值得惊讶的点，是因为两头飞龙下方还吊着一艘船。

以粗锁链固定并由飞龙吊挂的船名为「飞龙船」，即使是在有人能操控飞龙的佛拉基亚国内，这也是很少见到的交通工具。

「应该很少会有搭乘这种飞船的经验。好了，虽然有点晚，这是我送给两位成婚的礼物。」

飞龙船在背后飘浮，瑟莉娜得意地笑着如此说道。

裘拉对她那落落大方的态度哑口无言，相反地，普莉希拉绽放笑容，这确实可说是适合作为庆贺成婚的礼物。

「很好，值得赞许。德拉克洛伊上级伯爵，妾身很中意这个礼物。」

「──哎呀，彭德尔顿伯爵真的是娶到了很不错的妻子。」

面对毫不畏惧地回应的普莉希拉，瑟莉娜用手指摸着自己脸颊的伤痕，如此呢喃。

8

「阿尔先生，你听说了吗？好像有飞龙船来了喔，飞龙船。」

乌比克莫名兴奋地这么说着的同时，阿尔正用手撑着墙壁，做着伸展脚部肌腱的暖身运动。

阿尔处在艰辛的剑奴立场，今天还是有需要赌上性命的工作。

即使是在全国沸沸扬扬地庆贺新皇帝诞生的时候也一样。

「应该说因为庆祝的关系，岛上活动也是盛况空前啊。」

「糟糕了啦，飞龙船是一辈子都不知道能不能见到一次的稀奇东西，要是没看到就亏大了，偶真是有够不走运的。阿尔先生，阿尔先生你有没有在听啦！」

「吵死了！没看到我在暖身嘛！」

乌比克在转动腰部的阿尔身旁转来转去，马上挨了一顿骂。

虽然对感叹被命运放弃的他不好意思，但要阿尔来说，乌比克不用参加生死对决已经是相当幸运了。

每天面临性命危机，直到抽到「死亡」这支下下签前会持续被迫参加表演活动，这就是剑奴生与死的生活样貌。

虽然潦倒来到剑奴孤岛，但光是不用被这种体制牵连，乌比克应该就已经是个很幸运的男人了。

「──可是被虐待践踏的立场还是没变，偶从来都不觉得自己比阿尔先生还好。」

「……你是想把男妓和我们剑奴摆在一起比较吗？」

乌比克收起和善笑容沉重地这么说，阿尔也跟着放低声调。

这句反问相当尖锐，看场合甚至有可能失去友好对话的机会，但乌比克只是带着苦笑回答「真是不留情面耶」，抓了抓头。

「到头来，意思是只要偶不会挥剑，就没办法成为阿尔先生的朋友了吗？那一辈子都只会是陌生人了吗？」

「别偷偷暗示一辈子都不会挥剑啦。就算你现在靠着人脉和长相勉强能混过去，以后就不一定了，好好思考十年或二十年后的事吧。」

「阿尔先生才是，难道要在这里再住十年吗？与其说是很会忍耐，这样才是没有看清自己的立场吧？」

虽然被这样说不是很高兴，但乌比克说的没错。

要在这个剑奴孤岛撑过十年、二十年实在很荒谬，在那之前肯定会在某天丢掉小命。

或许是一年后、下个星期，也有可能是今天。

「所以要在那之前想好办法啊，阿尔先生。」

「────」

「与其在这里坐着等死，不如对抗命运吧。偶觉得阿尔先生答应帮忙，肯定会是如虎添翼喔。」

不知道是从阿尔眯起的黑色眼瞳中看出了什么，乌比克以热情语调如此邀约。

乌比克再度开始高谈毫无根据与限度的革命论点──别停下来，或是拿起武器对抗暴政等等，如此煽动应该会让心情很舒畅吧。然而……

「我没兴趣，也不是值得我拼死拼活去大干一场的事。」

「阿尔先生……那你为什么还要在战斗中获胜？阿尔先生获胜就代表有人会输掉送命，偶觉得这样还满矛盾的。」

「才不矛盾咧──只是我没有理由死掉而已。」

见到乌比克难得──不，应该说是首度坚持己见，阿尔冷淡地如此回应。看乌比克的表情似乎还有话要说，然而从集会场深处已能够见到有人前来迎接。

是负责阿尔的看守欧兰，他会露脸表示时间到了。

「我走啦。不知道还能不能回来，你可以先吃饭没关系。」

「偶相信阿尔先生会回来的。」

「那是女主角才会说的话吧，虽然有女生对我说出这种话也满麻烦的。」

即便如此，进入乌比克的攻略路线也是麻烦事，还是随便打发掉他吧。

就这样，在乌比克与面熟的剑奴目送下，阿尔被欧兰带到竞技场。

途中解开了徒具形式的手铐，并且握起自己的爱剑后──

「今天也别死了喔，阿尔迪巴兰。」

「……记性不好是你唯一的缺点呢。」

又被叫出不想听到的名字，阿尔带着苦笑踏进竞技场。

头顶顿时传来观众扭曲的狂热呼喊声，虽然感到讽刺，阿尔还是戏谑地行了个礼，担负起取悦观众的职责。

虽然不可能喜欢那些观众，但让观众站在自己这边总是会有些好处，这是阿尔在十年剑奴生活中学到的处世之道之一。

「不过话说回来，今天真是盛况空前……就算是做一样的事，没想到庆祝新皇帝诞生的活动这么不容小觑。」

即使内容与平常没有差别，还是有比平常更多的脱缰观众前来观看基奴海布的剑奴活动。

既然如此就尽量让他们着迷，让他们成为能够活下来的助力吧。

「欢迎观众席的各位、VIP室的各位高官权贵、还有从屋顶观赏比赛的观众，手上请准备好厚手帕。」

阿尔一边挖苦地如此呢喃，将扛在肩膀上的青龙刀缓缓举起。

从正对面通道有个秃头壮汉现出身影，两手握着大弯刀走进竞技场。全身布满显眼的刀伤，证明了他也是身为剑奴经历过许多次对决。

当天自己会与谁对战，要到竞技场见面时才会知道。

老实说，不知道什么时候会对上那个「剑奴女帝」荷奈特，阿尔对今天还没有收到死亡宣告这件事松了一口气──

「总之两边运气都满差的，不是谁有错──要怪就去怪星星吧。」

9

秃头被砍断，血肉横飞地在空中飞舞。

瞬间，俯视着剑奴生死对决的观众发出今天最热烈的欢呼。对这场激烈对决──不，是嘲笑败者，并对胜利者混着侮辱与称赞。

「哎呀，打得还满激烈的。之前听说是『生死对决』，没想到真的是毫不儿戏互相屠杀，把这当成表演也是满厉害的。」

「真是充满恶意的兴趣，完全无法理解对此乐在其中的人在想什么。」

瑟莉娜的属下巴尔罗伊与迈尔斯一边看着生死对决，一边如此交换感想。

巴尔罗伊自己似乎也是使用长柄武器，而迈尔斯自称对动武一窍不通。对于剑奴们的战斗，双方的意见也可说是相当极端。

说好听点，就是情同兄弟的两人彼此各自缺乏的特色。

「怎么样？普莉希拉，看得还满意吗？你的夫君倒是脸色苍白啊。」

「不差，空无一物的人赌上一切争斗的模样令人尽兴……不过刚才那个丑男的战法很无趣。」

「刚才……喔，是说那个单手的。」

瑟莉娜摸着自己脸上的伤疤，浮现出彷佛散发鲜血气味的笑容。

普莉希拉话题中提到的人，便是直到方才犹让观众情绪沸腾的生死决斗获胜者──那个以颇为丑陋的模样获得胜利的黑发单手男。

虽然将对面的壮汉玩弄于股掌之间，最后顺利斩下首级获得胜利，但此种俗气模样与华丽仍然相去甚远。

面对剑奴之间的战斗，当然不可能要求追求极致技术的高水准战斗。然而──

「感觉不到对性命的执着，不知道到底是为了什么而战。」

普莉希拉将手挽在胸前，如此评论这位不甚帅气的剑奴。

被囚禁于剑奴孤岛的多数剑奴，事实上都是被迫参加不希望的战斗。但即使在这样的环境中，应该还是会有想战胜、活下来的理由。

不论是与某人重逢、或是寻求低俗的名誉都没关系，只要想尽可能活下来，都是赌上性命的诉求。

然而，这个人却异常到没有这些情感。甚至不执着于自己的性命，只像是处理眼前的事情般赢得生存，这种模样实在是──

「──真是一点都不优雅。」

「唔呕……」

当普莉希拉简单地做出这个结论后，身旁的裘拉同时传来反胃声。

朝身旁瞥了一眼，只见脸色苍白的裘拉从竞技场别开视线，脖子与额头被大量汗水浸湿。

先前早已十分清楚，这个男人不适合观看血腥舞台的战斗。

虽然顺着普莉希拉的愿望，以受到瑟莉娜招待为由来到此处，光是要这个男人做到这点就已经濒临极限了。

「真是不适合当佛拉基亚贵族的男人。」

「抱、抱歉……我以为自己还能再多撑一下……唔……」

「正好妾身也想出去吹吹风，过来吧。」

语毕，普莉希拉便拉着面色铁青的裘拉的手，让他站了起来。

替普莉希拉等人准备的观赏席，位于能俯瞰整个竞技场的高处，但还是会有鲜血、油脂与性命的味道飘上来，只要裘拉处在这些气息中应该就不可能放松心情。

「用外面那条通道吧。巴尔罗伊，跟着两位去吧。」

「咦咦？我吗？我还想从生死决斗中学点东西……好痛！」

「不准违抗伯爵的命令！在让我丢面子之前快去！也别对彭德尔顿伯爵和夫人做出没礼貌的事！」

「好啦。」

在瑟莉娜与迈尔斯的命令下，巴尔罗伊不甘愿地接受指示。带着手持布捆长柄武器的他，普莉希拉与裘拉一同离开观赏席。

一行人前往被狂热气氛笼罩的竞技场外头，来到能够俯视围绕剑奴孤岛「基奴海布」湖泊的瞭望台，蕴含水气的冷风便迎接着普莉希拉等人到来。

此时早已日落，取而代之的是赤红月亮飘浮在空中。幽暗湖面倒映着赤红月色，天空与湖面的双月彷佛睥睨着世界一般。

「唉……不好意思让你费心了，普莉希拉。也不好意思让巴尔罗伊小弟陪着过来，你明明还满享受观赏生死对决的。」

「喔，不会啦，请别在意。我个人的见解是虽然能学到东西，但要说乐在其中又是另一回事了。」

「是……这样吗？」

「就是这样。反正不管怎么样，也没理由让彭德尔顿伯爵一直待到心情变糟。」

明明还没有随侍多久，巴尔罗伊的发言可说是口无遮拦。

虽然普莉希拉没有很在意，但裘拉似乎很在意他是否会说出必须惩罚的失言。普莉希拉朝他那甚至犹豫是否该动用贵族权力的模样瞥了一眼，便转头望着湖面。

「────」

没有想像中令人惊艳，这是普莉希拉对剑奴孤岛的感想。

当初原本很有兴趣想知道是什么样子，但见过实景后也跟着变淡许多，却也不像裘拉对鲜血或生死对决涌现厌恶感。

「不如说，这点反而会让妾身热血沸腾。」

好说歹说，普莉希拉仍然是佛拉基亚贵族──虽然血脉的话题无法一概而论，但拥有浓厚佛拉基亚血统的她会有这种想法也是理所当然。

纵使普莉希拉不相信血脉中寄宿着人格，但至少普莉希拉本身不会对互相赌命的人别开视线。

只是在虫笼中安排好的厮杀，不会让她感到血脉贲张而已。

「不过话说回来，夫人这么年轻却这么有胆量。连迈尔斯大哥都带着那么严肃的表情，夫人看到头被砍掉居然能面不改色。」

普莉希拉站在栏杆前方俯视着湖面，巴尔罗伊从旁窥视着她，而且还是背靠着栏杆、抬起双脚的不敬姿势。

但普莉希拉没有责备他的态度，只是反问「你想表达什么？」。

「是要像街坊姑娘一样情绪震荡起伏，悼念死亡的失败者才算可爱吗？」

「不不不，我不是这个意思。特地来到这个岛上，每当看到有人死掉就哭出来，反而更麻烦吧。而且……」

「而且？」

「德拉克洛伊伯爵也是，我很喜欢强悍的女性喔。」

他说出比姿势更加不敬的话语，普莉希拉仍然对此保持沉默。

她已经看穿巴尔罗伊的言行举止没有恶意，也判断要是在这里扼杀他将来的器量会很可惜，还有──他现在担负着保护两人的职责。

虽然巴尔罗伊的态度很像真的放松心情，但普莉希拉知道他的视线偶尔会毫不松懈地巡视四周。在见过许多高手的普莉希拉眼中，虽年轻的他身手也能排进前段班。

只要没有犯下大错继续成长，肯定会成为帝国内知名的武人。

「────」

瑟莉娜派巴尔罗伊护卫普莉希拉等人，考量到招待普莉希拉与裘拉来到岛上的立场，希望两人安全也是理所当然的安排。

目前普莉希拉对瑟莉娜并没有坏印象，她甚至对可能会被其他贵族看轻的裘拉同等看待，包含这点在内，没有任何敌对的理由。

因此普莉希拉也想过接受她的好意，然而──

「──真奇怪。」

「哪里奇怪？」

普莉希拉皱起美丽眉头如此低喃，让巴尔罗伊闭起单边眼睛。与其说是回答他的问题，普莉希拉比较像是延续呢喃声般继续说：

「吊桥是什么时候拉起来的？」

10

──看来自己把事情想得太过乐观了。

「────」

远处通道另一侧传来回荡的欢呼，阿尔听着背后传来这些声音，冷静地思考着自己目前身处的状况。

短短几分钟前，才刚面临赌上性命的生死对决。

拿着两把大弯刀的壮汉也是颇具实力，难得花了两位数的挑战次数才拿下胜利。身心灵经过剧烈消耗赢得生存后，虽然还不到意气风发的程度，当阿尔放松力道回到内侧后──

「乌比克，这是在开什么玩笑？」

「开玩笑？阿尔先生，偶从来没开过玩笑，偶不是一直说了吗──说需要变革。」

美男乌比克如此说着，仍然朝阿尔投以散漫笑容。

然而，看守欧兰倒卧在他脚下的血泊中，能够明显看出生命泉源从深深被挖开的颈项彻底流出。

一眼便能看出乌比克杀了欧兰，剑奴杀了看守。

「杀死看守是最糟糕的禁忌，这已经不是问题，而是严重违规了。」

「从状况看来是这样，不是剑奴也会被视为重罪犯。一个不小心还有可能被丢进惩罚对决……像是与荷奈特小姐对决之类的。哈哈，那肯定会死吧。」

「就说那不是能嘻嘻哈哈的事了！」

面对乌比克搞不清楚状况的态度，阿尔的焦躁感瞬间爆发。

他架起青龙刀，瞪着手持染上欧兰鲜血的粗劣短剑的乌比克。

刀身宽厚的刀剑与似乎是暗藏的粗制滥造短刀，一旦互相交锋很显然无法抗衡。或许该说──

「凭你不可能赢过我，你有蠢到连这点都不知道吗？」

「不，偶当然知道。偶没有自大到认为自己能够赢过阿尔先生，看守也是让他松懈到不行才能刺到他的脖子。」

乌比克一边说着，一边将短剑丢到地上，举起沾满鲜血的双手。他表现出无意挣扎的模样，阿尔无法看出他的真正意图，皱起眉头。

「虽然阿尔先生拒绝了很多次，但要偶说几次都没关系。请帮帮偶们，只要阿尔先生提供协助，革命肯定能顺利进行。」

「不可能，别在这种浮在水中的岛上做梦。不管我和你怎么说，其他人都不会听进去的。」

「不会的，只要是偶和阿尔先生……」

「你很烦。」

乌比克仍然用尽言词坚持邀请，阿尔决定让他闭嘴。

虽然对乌比克不好意思，不过革命是不可能实现的梦想。阿尔不打算听他疯言疯语，一起踏上这艘肯定会沉没的泥船。

于是阿尔一个箭步往前，毫不留情地将青龙刀挥向乌比克。

「我不打算杀你，先把你一只手砍掉，变得像我一样，再对其他看守──」

「是打算把偶交出去吗？偶才不要──真是太可惜了，阿尔先生。」

乌比克垂下眉头，朝阿尔投以由衷感到同情的目光。刀刃彷佛挥开那道视线般横扫出去，然后停了下来──不，是主动停止。

更正确地说，是被挡了下来。

「什……」

斜向挥出的青龙刀被途中闯进的大剑弹开，虽然阿尔想称赞自己没有把剑放开，但眼前的现实让这种游刃有余的心态顿时烟消云散。

「喂喂喂，这是在开什么玩笑啊。」

感觉到手传来酸麻感，重新握紧青龙刀的阿尔吞了一口气。眼前保护乌比克、挡在前头的人，是个带有可怕压迫感的高挑身影。

既美丽又带着残虐武装，在「剑奴孤岛」最为凶残的剑奴──

「──荷奈特。」

「哎呀呀，露出这么可怕的表情，阿尔小弟弟真的是很冷淡呢。」

扭动着甚至需要抬头仰望的修长双脚与身躯，黑发女荷奈特俯视着阿尔，露出愉快笑容。失去手肘的双手前方已经装着爱用大剑，成为简直可说是人类武器的完整型态。

即使身为剑奴，却以魔性与霸气迷倒众生，支配基奴海布的「剑奴女帝」荷奈特──她保护乌比克具有很重要的意义。

「简单说，你站在乌比克那边，赞成革命吗？真是个完全摸不透的家伙。」

「哎呀，是这样吗？阿尔小弟弟以为我是个既保守又无趣的女人吗？让我好难过喔。」

「我是从来没有『你是个无趣女人』这种不要命的感想，不过说得也是。就算是这样，我以为你对这座岛上的生活很满足，真是出乎我的意料。」

让其他剑奴刮目相看，甚至让看守臣服于她，原本以为荷奈特会想继续维持这种类似岛屿主人的立场──身为喜好战斗，不知败北的剑奴孤岛绝对女王。

在这个岛屿应有样貌的祝福下，她应该是最适合这里的存在。

而她居然会与乌比克联手，参加「革命」这个荒谬的漫天大梦──

「或许该说，身为首席保守派的我完全搞不懂。你为什么不惜抛弃安定生活，要陪那个自以为是革命先驱的家伙？真的是脑袋有问题吗？」

「哎呀，嘴巴好坏喔。可是啊，我很喜欢阿尔小弟弟这种地方喔。还有啊……冷淡的阿尔小弟弟总算能回应我的期待了。」

「我回应你的期待？」

体会到强烈战意灼烧眉头的错觉，荷奈特的说词令阿尔闭起单边眼睛。

就算说是回应期待，还是没有头绪。

面对阿尔这样的反应，荷奈特发出「唔呵呵呵」的低笑。

「──与其让阿尔小弟弟成为同伴，成为敌人比较有趣喔。」

「──！」

随后，不下一百公斤的两把超沉重大剑破风袭向阿尔。

荷奈特的臂力非比寻常，连阿尔都没办法抱起来的两把大剑，彷佛小树枝之类的物体般由她轻松挥动。

（插图013）

在绝对不算是宽敞的通道挥舞这种武器，几乎没有空隙能够躲避。阿尔只能缩起身体避免被波及，然后往后大大一跳──

「哎呀，这样不行喔。」

胸口被荷奈特一个箭步往前刺出的大剑刺穿，心脏、内脏与腹部内侧被毫不留情地翻搅，弹了出去。

两把大剑的前端刺进体内，还来不及喘息便被左右拉开，阿尔的身体被漂亮地──不，是被肮脏地分成两半，内脏瞬间四处喷溅洒落。

难以避免的「死亡」将阿尔吞噬──

「哎呀，这样不行喔。」

面对荷奈特一个箭步往前刺出的大剑，阿尔刹那间摆动身体勉强躲过。听着荷奈特出乎意料地发出「哎呀」的声音，他凭直觉朝因翻过身而绕到背后的对手挥出青龙刀。

荷奈特用巨大身躯难以置信的速度蹲下身，让这记反击通过头顶。

下个瞬间，往上弹起的锐利脚跟将阿尔由下往上踢起，双脚离开地面的身体无法躲避，被正上方落下的大剑直接劈成左右两半──

「哎呀，这样不行喔。」

面对荷奈特一个箭步往前刺出的大剑，阿尔用青龙刀由斜下方交锋，强硬地架开刀刃。听着荷奈特出乎意料地发出「哎呀」的声音，阿尔伴随怒吼，朝对手作为轴心的脚挥出斩击。

荷奈特轻松地跳跃躲过这记反击，但她人在空中便是绝佳的大好机会──阿尔立刻转过身，背对着她跑往通道深处。

「唔喔喔喔喔──！！」

虽然这是首度与荷奈特交手，但「剑奴女帝」果然并非浪得虚名。

凭阿尔的三脚猫功夫，双方实力很显然已经差距到就算挑战一百次也只会被杀死一百次的程度。如字面所述般切身体会到这点后，阿尔决定逃离战场。

或许该说，他原本就不会坚持绝对要战胜对方。以阿尔的论点来说，活下来的那方才算胜利。也就是说──

「只要冲到竞技场，让观众站在我这边……」

「阿尔先生，偶不想对你失望，只要稍微想一下就能知道了吧？」

然而，当阿尔准备逃进竞技场时，背后观看着战斗的乌比克这么说。

不想听他说话，但他的声音还是钻进鼓膜。

「让荷奈特小姐站在偶这边的时候，就已经安排好了，最后就只剩你肯不肯点头答应而已。」

这句不想多做思索的话语，阿尔瞬间理解了个中含意。

因为在脑袋理解前，答案已经映入了阿尔的视野中。

「────」

勉强穿过眼前竞技场的门扉后，状况已经彻底改变。

先前对竞技场举行的生死对决发出欢呼，事不关己地享受赌命战斗的观众间的狂热气氛已经消失，取而代之地则是紧张与恐惧感支配了整个会场。

这也理所当然──因为拿着武器起义的剑奴们在观众席排开，束缚起表情抽搐的观众们，加以控制。

或许也有人挺身抵抗，但都被毫不留情地杀鸡儆猴，在剑奴刀下成为凄惨尸体。

对这番景象看傻了眼，阿尔才总算理解。

「该不会是认真的吧……」

占领「剑奴孤岛」与帝国抗战──这个漫天大梦要付诸实行了。

11

在庆祝活动这段期间，剑奴孤岛与陆地会有人潮频繁来往。

因此唯一连系岛屿与陆地的吊桥会维持放下的状态，见到事前听闻理应是如此的吊桥拉了起来，让普莉希拉起了疑心。

接着，她带着裘拉与巴尔罗伊连忙赶回瑟莉娜身旁。然而──

「──看来完全被夫人料中啦。」

在俯瞰着会场的普莉希拉身旁，见到同样景象的巴尔罗伊如此低喃。

原先以为是发生了什么不容忽视的事，没想到回来一看便见到整个会场陷入混乱。而这种浑沌并非是观赏生死决斗的狂热气氛──

「这、这是……剑奴们跑到竞技场外面了……？」

裘拉慢了半拍才掌握状况，但说出的话语准确地形容出现场状况。

如同脸色苍白的裘拉所说，剑奴们从彼此交锋的竞技战场逃出，上到观众席，将武器抵在浑然无所觉的观众身上。

这并非是表演或游戏，从违抗的愚蠢家伙已经倒卧在血泊中便一目瞭然。简单说这是──

「──是剑奴谋反啊。」

「瑟莉娜•德拉克洛伊上级伯爵在哪里！！」

普莉希拉的呢喃，让裘拉发出「咦」的傻呼呼疑问。但在回应他的疑问之前，有道粗犷声音先响彻了整个竞技场。

有群看似鲁莽暴徒的男性，在贵族用的观众席旁若无人地大摇大摆走着，他们的目的似乎是招待普莉希拉等人的瑟莉娜。

对方应该不会猴急到一发现她就格杀勿论，然而──

「别躲了！快点出来！不然把所有人杀掉都要把你揪出来！」

订正刚才说的。原本以为对方不会那么猴急，但看来比想像中更沉不住气。

不觉得对方有那个脑袋会暂缓执行这些威胁话语。普莉希拉眯起眼睛，思考该怎么采取行动。

「普、普莉希拉……躲、躲在我后面……」

不知道是怎么看待普莉希拉表情的变化，裘拉勉强挤出所剩无几的男子气概站在少女前方。

对于丈夫出乎意料的态度，普莉希拉微微挑起眉头。巴尔罗伊同样也得知自己的主人身处困境，但仍然对裘拉的男子气概佩服地发出「喔」的声音。

然而，见到裘拉的动作，对方也发现回到此处的三人。

「嗯啊？喂，你们几个，在那边也没用。以为这样就能逃走……」

「──妾身就是你们要找的瑟莉娜•德拉克洛伊。」

「什么！？」「唔嘿？」

怒骂声被普莉希拉的凛冽声音打断，内容让陪同的两人目瞪口呆。

普莉希拉的声音在充满紧迫感的空间中回荡，自然地吸引暴徒与被囚禁的观众们的目光──其中也有瑟莉娜•德拉克洛伊本人的视线。

她微微瞪大双眼，似乎无法揣测普莉希拉的真正意图。

这也是理所当然，瑟莉娜本身并非泛泛之辈，然而──

「还是远远不及妾身。」

「──小妹妹，你就是德拉克洛伊上级伯爵啊。」

面对念念有词的普莉希拉，身穿黑衣的男子突然出现在前方。

头发右半边留长并剃掉左半边的奇特发型，腰间配戴着刀身向后弯起的弯刀，看起来颇具实力。

男子朝普莉希拉投以极度不信任的眼神，由上到下频频打量。

「听说德拉克洛伊上级伯爵是被称为『灼热公』的女中豪杰，怎么看都不像是你这种丫头做得到的事……」

「那是见到妾身如火焰般红发的俗称。妾身对凡夫俗子如何称呼没有兴趣，用你自己的眼睛看清楚吧。」

「────」

「你看起来又是怎么样？妾身是谎称上级伯爵的鼠辈吗？还是自称佛拉基亚帝国贵族之名，想得到『灼热公』俗称的女人吗？」

普莉希拉抬起下腭，正面瞪着有身高差距的对方。

先前应该误以为对方是个吹弹可破的丫头，男子顿时绷紧神情，或许是因为见到普莉希拉的表情没有半点胆怯或示弱的缘故。

如果这名男子也是剑奴，肯定在这个岛上跨越过许多相对应的生死关头。

由男子眼中看来，普莉希拉的胆量已经脱离常轨。

因此──

「不好意思，上级伯爵。麻烦你陪我们一起过来，我们的首领想要见你。」

男子善尽低俗人民该有的礼仪，承认普莉希拉为上级伯爵。

接着，他朝附近的同伴使了个眼色，准备将普莉希拉带去某处，普莉希拉也没有反抗的意思。

「等、等等！要把她带走的话，就连我一起！」

然而，裘拉又在这个时候发挥出不必要的男子气概。

不知是否没有看见畏畏缩缩无法加入话题的他，男子露出首度发现他的表情。

「父亲有陪你过来吗？我怎么没听说这件事……」

「我不是她的父亲，是她的丈夫。」

「丈夫……？」

男子的眼神越来越怀疑，来回比对着普莉希拉与裘拉。

与其说是两人的年龄差距，他视为问题的点是两人散发的霸气。然而，要是裘拉在这里被杀害，对普莉希拉而言也会造成很多问题。

「这是事实。他是妾身的夫君，应该说父亲已经在妾身眼前被活活烧死。除了发色以外，妾身被称为『灼热公』的原因应该也经很足够了。」

「原来如此。但如果照你这样说来，你的丈夫是……」

「把他一起带走，不然他哭哭啼啼会很棘手，与妾身一起就不会吵吵闹闹。要是把他杀死，妾身跟着夫君寻短，你们也会很麻烦吧？」

普莉希拉当然没有柔弱到会跟着夫君一起寻短。

然而，男子们已经对普莉希拉带有确实很像帝国贵族的先入为主观念。

而且还发生了让男子们失去冷静的状况。

「喂，那是荷奈特吗？」

众人目光皆集中在普莉希拉身上，先前陷入不快寂静中的竞技场传来这道声音。某个暴徒俯视着下方的竞技场，对其中景象发出惊讶叫声。

随着声音将视线转过去，只见该处正展开一场理应中断的生死对决。

正确来说那不是剑奴孤岛的活动，而是突然发生的真正生死决斗──

「──与其说是生死决斗，双方实力差距比较像是处刑吧。」

两名剑奴在竞技场展开死斗，一方身高超过两公尺，用失去的双腕化为大剑展现出压倒性的剑技。一眼便能看出这个曾经让场上血流成河并堆起尸山的剑奴，肯定就是对方心怀畏惧称呼的荷奈特。

另一方面，对峙的单手剑士遗憾地没有任何可看之处。力量也远远不及荷奈特，就连现在也是──不，即将受到致命一击。

「────」

单手剑士正鲜血四溢，被重重地打了出去。

身体在竞技场地面不停翻滚，直接滚到会场边缘为了清理战斗后血迹与尸体的地洞旁。接着，荷奈特追了上去，并用长腿朝他踹了一脚，将对方活生生地踢进洞中。

「那家伙拒绝了荷奈特的邀约啊，真是个蠢蛋。」

见到一面倒的战况，配戴弯刀的男子傻眼地如此呢喃。

对他而言，被荷奈特斩杀的剑奴应该也是熟人。虽然不知道对普莉希拉是否有益处，但看来是在这种状况拒绝与他们联手的愚蠢家伙。

「如果想贯彻自己的意志，就需要相对应的力量。就这个层面来说，刚才那家伙死掉也是理所当然。好了，你们是为了露出那种愚蠢表情才杵在这边吗？」

「……真是个口无遮拦的上级伯爵。你以为我们不会对你做任何事吗？所以才会用那么狂妄的语气说话。」

「──你是认真说出这些话吗？」

「喔──」

「用那种以为妾身不会出手的态度，你的意思是这样吗？」

不知道从普莉希拉的眼神中见到什么，男子将接下来的话语吞回肚中。

接着，他随即抬了抬下巴，与同伴一起准备将普莉希拉与裘拉带走。

「我……」

「再怎么样都不可能连你都说是妾身的夫君。就算你跟过来也不会有用，等到能派上用场之前，乖乖躲起来吧。」

普莉希拉如此劝阻差点追上来的巴尔罗伊。

即便巴尔罗伊很有实力，现场剑奴至少超过百人以上。考量到寡不敌众，在此时逞强明显没有任何价值。

但他仍然是既青涩又横冲直撞。

「虽然夫人这么说，我还是有不能退让的……嘎喔！？」

「──闭嘴！蠢蛋！」

巴尔罗伊解开长柄武器的布包准备拿出武器，后脑勺被不知何时偷偷接近的迈尔斯用酒瓶击中。发出沉重声响后，巴尔罗伊被毫不留情打得翻白眼趴倒在地，迈尔斯则是踹了他一脚。

「就是有这种家伙，才会让我们所有人都被当成傻子！真会找麻烦啊！是不是啊！？」

「你是……」

「没关系、没关系，我不会反抗你们。你们要找上级伯爵吧？赶快把那个丫头和丈夫带走吧，我们会在这里乖乖等着。」

迈尔斯丢掉酒瓶，展现出完全投降的态度，让男子们面面相觑。

然而，或许因为随即感觉到理睬这名男子有点蠢，于是确认过巴尔罗伊真的昏倒后，便继续将普莉希拉等人带走。

「──抱歉。」

在即将离开观众席的前一刻，能够瞥见瑟莉娜的嘴唇如此低喃。

普莉希拉没有做出任何回应，以豪爽步伐跟着走在前头的男子身后。

「普莉……瑟莉娜，你打算怎么做？」

「至少还有这点程度的脑袋啊。没什么，如果在那时候没有报上名号，连他们说的首领都见不到，只能置身事外。不论事情最后如何解决，这样会很扫兴。」

「扫兴……」

听到普莉希拉的回答，压低声量的裘拉顿时哑口无言。

不知道他是想要哪种万能的答案，但普莉希拉的逻辑依然不容改变。

虽然不清楚对方想对瑟莉娜做什么，但要是留在观众席就会无法掌握状况进展，这与畏缩在舞台边缘没有两样。

「妾身不希望以这种方式解决。」

「────」

「别担心，不管出现什么样的状况都没关系，毕竟这个世界就是为了妾身量身打造的。」

普莉希拉堂堂说出独门哲学，让裘拉瞠目结舌地沮丧垂下肩膀。

虽然这反应让普莉希拉颇为不悦，但没有时间能多加追究。

「把人带过来了。」

离开观众席走了一段时间后，两人被带到颇为森严的门扉封锁的房间。

普莉希拉在脑中描绘着岛屿地图，这个房间应该是位于剑奴孤岛最高处的房间──猜测应该是岛主的房间。

这样想来，也能想像到在这个满是剑奴的岛屿上，只有这个房间摆放着不合环境的摆饰品与高级地毯的理由了。

以及某具像猪一般脑满肠肥的男性尸体真实身份为何。

「他、他是……」

「应该是这里的岛主……也就是掌管安排剑奴孤岛活动的男人。毕竟是先前被当成表演的剑奴们揭竿起义，就算蠢到一定程度，也能知道谁会最先被抓来血祭吧。」

而且明明招致了相应程度以上的怨恨，缺乏危机意识才会招来这种结果。

也有可能是对方的智谋超过岛主的危机意识，然而──

「──哎呀哎呀，初次见面，上级伯爵。不好意思用这种方式迎接您，其实偶很想用干干净净的房间招待你。」

在如此思索的普莉希拉面前，有个表情傻呼呼的人跨过岛主尸体走了过来，那是个给人细瘦印象的帅气男子。

与看来粗俗的暴徒们截然不同，面貌与剑奴孤岛格格不入，但普莉希拉一眼便看出他是主导这场起义的首脑。

「你就是这场宴会的主导者啊。」

「宴会？喔，说成宴会真不错。偶很喜欢热闹，所以我也不讨厌这个岛屿，虽然有些难以忍耐的事就是了。」

帅男如此笑着，朝脚下尸体投以带有侮辱的目光。

光靠如此，便能察觉到这个帅气男子如何不用挥动钢铁武器，而是靠着自己作为武器在这个岛上存活下来，岛主会丧命可说是理所当然的结果。

「那你们还有什么期望？特地把妾身……上级伯爵绑来这里，应该有对未来的展望吧。」

「真不愧是身经百战……虽然看起来不像那么有年纪，不过这样就好说话了。『灼热公』瑟莉娜•德拉克洛伊……你是帝国首屈一指的贵族。」

「蠢货，没有地方能找到替代妾身的人，拿其他凡夫俗子来比较甚至是不敬之罪。」

「瑟莉……！」

裘拉发出支吾声，拼命地摇了摇头。

对这难以理解的声援皱起眉头，普莉希拉仍然装成瑟莉娜继续对话，从刚才的前言能够大致猜出对方的目的。

也就是说，对方想用上级伯爵作为人质──

「要与帝国做什么交涉？」

「这很单纯──让这座剑奴孤岛独立，并释放所有剑奴。偶想离开这座水中孤岛啊，德拉克洛伊上级伯爵。」

帅男发出阴沉的嗤笑声，堂堂宣布与帝国为敌。

12

──「剑奴孤岛」被剑奴占据，多数观众被扣押成为人质。

以瑟莉娜•德拉克洛伊上级伯爵为首，其中包括不少帝国贵族，叛乱分子以这些贵族作为人质，要求解放岛屿。

这个报告送到帝国中枢，对刚诞生新皇帝的帝国带来剧烈动荡，令其陷入混乱──当然没有。

「立刻组织讨伐队派过去，没有与那些家伙交涉的余地。」

这是新皇帝文森•佛拉基亚下达的敕命。

皇帝的指示具有绝对优先权，于是随即开始组织派遣到剑奴孤岛的讨伐队。岛上剑奴数量大约五百人──但歼灭叛乱势力的讨伐队是两千名遴选而来的精兵。

即使剑奴们身怀武艺每天战斗，还是无法胜过数量暴力，而且皇帝还下达「歼灭敌人」的敕命。

也就是说，两千名精兵没有拯救人质的名分，而是得到了单纯用数量对寡兵进行压倒性虐杀的许可证。

「──话虽如此，放弃德拉克洛伊也只会徒增麻烦而已。」

「那阁下是说谎吗……？」

「别胡说，你这个不要命的丫头。那不是说谎，而是图个方便。只是先把话说清楚，之后还是会稳当地解决掉这件事，这不是开玩笑的。」

白发老人抓了抓自己的脖子，以毫不掩饰感到麻烦的气氛如此回答。

这位老人身材矮小，弯着腰，并非是长命的亚人，而是超过九十岁的纯粹超高龄老人，但相反地甚至可以用矍铄形容。

然而，要是知道这个皱眉蹙额、眉毛长到无法看见眼睛的老人是佛拉基亚帝国最为知名的「九神将」之一，不论是谁肯定会怀疑自己是否听错了。

九神将便是借着展现出优秀武勇，才能获得只有九个名额的一将宝座。这位白发苍苍的老人──奥尔巴特•丹克肯也是其中之一。

而与奥尔巴特说话的人，是裸露出褐色肌肤的年轻少女。面对用眼罩遮盖左眼的她，奥尔巴特眯起浓密眉毛下的眼睛。

「丫头，记得你是叫……」

「──亚拉基亚，我说过好几次名字了。」

「喔喔，对对。亚拉基啊，亚拉基，这次绝对记起来哩。」

奥尔巴特弹响指头，漏出像是病人般的呼吸声如此笑着。听到他的回答，亚拉基亚发出叹息，半眯着眼望向远处的剑奴孤岛。

目前亚拉基亚、奥尔巴特与派遣的少数帝国兵正驻守在基奴海布附近，从对岸窥伺着岛屿的状况。

「如果能闯进去可能会比较快，可是吊桥没有放下来啊。」

「不能搭船之类吗……？」

「船啊，之前也有想过，可是你看那个啊，岛屿附近的湖中有很多水生魔兽到处晃来晃去。以前为了不让那些剑奴逃走，放了一堆魔兽进去，结果那些家伙在湖里互吃到没办法处理。所以没有吊桥，咱们和那些家伙都不能进出。丫头，你不觉得很糟糕吗？」

奥尔巴特持续发出像是咳嗽般的笑声，如此整理着目前的状况。

被这么一说，亚拉基亚也将视线转向湖泊。在夜晚的湖中，能够见到鱼影正在蠢动。虽然说是鱼影，正确说来并不是鱼，而是水生魔兽。

与地上相比，多数生物在水中的战斗能力会降低。就某种意义而言，水生魔兽或许比陆生魔兽更为棘手，奥尔巴特会笑着回答无计可施也是理所当然。

所以──

「我去。」

「喂喂，只是稍微会游泳不行喔？在抵达岛屿之前就会被咻地扯下去喔？看到年轻丫头跳进去自杀，来日不多的老人家可是会爆气的哩。」

「没问题……只要变成水就可以了。」

「喔？」

奥尔巴特摆动蓬松眉毛，露出惊讶神色。在他面前，亚拉基亚解开只有最低限度遮盖身体的布，让身体全裸。

接着，她蹲在水边，将手轻轻伸进湖面。

「啊嗯。」

──她捞起水精灵的小小微精灵放进口中，与之同化。

具有「吞食精灵」特殊能力的亚拉基亚，能够吸收空气中的精灵化为自己的力量。虽然只有在消化精灵的时间内能够使用吸收的力量，但由于只要仔细观察便能在各处发现精灵，因此不曾陷入缺乏燃料的窘境。

亚拉基亚靠着这种能力吸收水精灵，让自己获得精灵的特性，然后再度看向奥尔巴特。

「只要把吊桥放下就能进去吗？」

「对对，可以可以。应该说连丫头都这么努力了，咱要是懦弱说办不到，可是会被阁下掐死哩，快去吧。」

奥尔巴特挥了挥手，敷衍地送亚拉基亚离开。但她没有放在心上，点了点头便跳进湖面，接着以能够媲美水生魔兽的速度向前游去。

吸收水精灵的力量，与湖水半同化的亚拉基亚不会被魔兽发现。魔兽身旁也有大量的水，不会有魔兽特地咬附近的水。

因此亚拉基亚只靠自己，轻易穿越了剑奴孤岛完成以来没有任何人能通过的湖泊──而且是不花十分钟便悠哉地抵达岛屿。

「──？」

当她顺畅地持续游着时，突然发现某件事而放缓速度。

在水中的亚拉基亚发现岛屿与岸边之间有个漂浮的小浮岛，这个浮岛小到甚至令人犹豫是否该称作岛，只是岩石漂浮在水面而已。

或许是因为与水精灵同化，比较容易察觉到漂浮在湖面的异物，才会让亚拉基亚的意识察觉到该物体。

感觉到飘散的鲜血气味，亚拉基亚转换方向前往浮岛，然后沿着些微的鲜血流动爬上浮岛。在岩石互相堆叠的狭窄空间中，发现了向内延伸的血迹。

而沿着血迹抵达尽头后──

「……喂喂，现在是什么状况？终于缺血到开始做梦了吗？」

「────」

「在这种状况下还能看到裸体银发女孩……我未免太造孽了吧……」

在眯起眼睛的亚拉基亚眼前，有个失去单手的男人被埋在岩石缝隙间。

湿润黑发与胸前看来很严重的伤势，很显然刚才那是他流出的血。要是没有进行急救，不久后肯定会死亡，这名男子不知道是不是岛上的相关人员。

亚拉基亚稍做思索，她接到的命令是夺回岛上的帝国贵族，因此必须放下吊桥迎接奥尔巴特入岛。

要完成这个目标，得尽量获得岛上知识才会更顺利。

「你不想死吗？」

「────」

「如果不想死的话……嗯，我能救你……相反地你要告诉我。」

这个交换条件是模仿以前侍奉的主人──不，就算到了现在，心中仍然遵从那位主人的手法，亚拉基亚对濒死男子提出这个交易。

然而，听到亚拉基亚人生中首度提出的交易，男子发出低沉笑声。

「事到如今我还会怕死吗？那种话要在我死几亿次之前先说啊。」

单手男愤恨地吐着血，以彷佛咒骂的声音这么说。

13

──剑奴孤岛「基奴海布」的剑奴同时起义，要求解放孤岛。

在庆祝佛拉基亚帝国新任皇帝即位的庆祝活动日，剑奴们将聚集在基奴海布的多数观众作为人质，向帝国要求解开束缚的枷锁。

貌似主导这场武装叛乱的帅男说明这就是目的，假扮瑟莉娜•德拉克洛伊的少女──普莉希拉•彭德尔顿眯起深红眼眸。

虽然是年仅十二岁的少女，但眼神内寄宿的理智与冷酷光芒，令她在假扮受帝国重视的上级伯爵立场时具有充分的说服力。

实际上，现场所有人皆相信她的谎言，对她的立场深信不疑。

要是穿帮，普莉希拉与陪同的丈夫裘拉当然也会没命──

「──让剑奴孤岛独立啊，很像是畏畏缩缩住在狭窄岛屿上的鼠辈会做的梦。一点都不感到意外或有趣，简直是浪费时间。」

「等……」

普莉希拉发出冷哼，平淡地这么说，裘拉顿时脸色苍白。

全副武装包围周遭的剑奴当然露出不悦表情，唯一只有站在普莉希拉正面的帅男出现不同反应。

帅男从喉咙发出「呵呵」的愉快笑声。

「没想到您会说出这么不留情的话。虽然偶不会生气……但其他人看起来不是很高兴喔。」

「不会用自己脑袋思考的无能家伙，对妾身的话怎么想都无所谓。反正应该只是被好听话拉拢，随随便便就加入你的愚蠢东西吧。」

「喔，这还真是……偶刚刚有说什么奇怪的话吗？」

「当然──在这座狭窄岛屿里面，你看起来算是还会动脑，不过要独立或是解放剑奴，很容易就能想像到这是不可能实现的梦想吧。」

帅男耸了耸肩，对普莉希拉的指摘不动声色。然而，跟随帅男的暴徒们反而对这句话出现反应。

「喂，那是什么意思？只要把这个贵族当成人质，帝都那些家伙肯定会……」

「以为这样就会倾听你们的诉求吗？如果你们也活在佛拉基亚帝国，应该知道『帝国子民须剽悍强大』那个愚蠢的训示吧──贪生怕死替你们开路前往帝都的上级伯爵算剽悍强大吗？挟持人质想让交涉处在优势的你们算是剽悍强大吗？」

「────」

「帝都的对应方式很容易看穿，只要寻求解放的要求传到帝都，皇帝便会立刻派兵过来歼灭敌人，再来便是皇帝直属的『九神将』上场的机会了吧。」

听到九神将这个名词，暴徒们与裘拉分别绷紧神情。

九神将是皇帝直属的部下，也是帝国最强的九人──在剑奴孤岛成天战斗的剑奴们，对自己的实力应该也算有自信，但九神将是完全不同次元。

在这个世界仅有一小部分获得天赋英才的人，与普通人可说是具有绝望般的力量差距。

九神将正是体现出这种差距──只靠地位与家室无法获得，而且是强大力量的名誉代称。

听到会派九神将过来，剑奴之间顿时一阵哗然。刚才将普莉希拉等人带到此处的男子，发出「开什么玩笑！」的叫声逼近帅男。

「乌比克！刚才那些话是真的吗！？我们都没听说！」

「哎呀，加吉特先生，冷静点。偶完全不会用剑，你靠这么近很可怕耶。」

「现在是消遣我的时候吗！啊！？」

被用力抓起胸前衣领，帅男乌比克如此安抚着配戴弯刀的男子。

「上级伯爵的意图很明显，她是想让我们惊慌，然后让我们乖乖投降。可是偶啊……不不，是我们不会这么容易上当。执着和贪念不就是我们的卖点吗？」

「──啧。」

对于乌比克的反问，男子发出咋舌声放开抓着胸前衣领的手。除了他以外的剑奴，也是面露苦涩地压抑着愤怒神色。

虽然这句话在普莉希拉听来相当愚蠢，但他们也已经无法退让。

目前木已成舟，事到如今就算弄错前提，当然还是不可能全面投降，这群人已经没有任何退路了。

正因如此才无法理解。

「普莉……瑟莉娜，他是有什么打算？」

「喔？没想到夫君的脑袋除了被恐惧支配以外，还有别的用途，真是令人吃惊。」

「别、别开我玩笑了，这是很重要的事……对于帝都的判断，我和你有同样意见。帝都不可能派人救援……或是认同基奴海布独立。」

裘拉语带颤抖地指出剑奴们计划前提条件的漏洞。

一边听着丈夫压低声量这么说，普莉希拉一边眯起深红眼眸，以沉默催促他继续说下去。

「我再怎么说也是帝国的中级伯爵，我很清楚帝都的作风。就算更替的皇帝再怎么慈悲为怀……」

「帝国到目前为止的建国原则不可能容许这种懦弱态度，因此这场武装叛乱只会以被歼灭的结局落幕。」

「……我不觉得他不知道这点。」

裘拉战战兢兢地将视线转向煽动剑奴暴徒的乌比克。

而普莉希拉也与裘拉的见解怀有同感。既然乌比克有脑袋思考又能看清局势，在实行这种计划之前应该就已知道无法成功。

即使如此，他还是能言善道地唬弄着剑奴们，营造出这种状况并加以实行。

而他的真正意图是──

「──解放剑奴孤岛只是欺瞒，那家伙应该还有其他目的。」

既不想让他如此顺利完成计划，随着状况随波逐流也很不服气。

原本普莉希拉就不可能「对他人言听计从」──不论对方是谁，只有自己能够决定自己的生活方式。

因此普莉希拉窥伺着四周，静静等待时刻来临。

等待着肯定会造访的机会，绝不错过，毕竟──

「──这个世界就是为了妾身量身打造的。」

14

「……这样应该就没问题了，不会死掉。」

「嗯……谢啦……好痛！」

正当准备道谢时，用布包紧的伤口被拍了一下，让他发出惨叫。

由于对方用生涩的危险动作进行急救，男子被碰到许多次伤口而痛得泪眼汪汪。但说来讽刺，毕竟是失去意识就有可能直接死去的状况，至少这个动作还能用来醒脑。

总之不论如何，男子──阿尔看向替他包扎伤势的少女。

「……虽然现在才说这种话有点奇怪，真是个不懂害臊的小姐。可爱女孩子全裸出现在面前，在我人生中很少有这么碰巧能大饱眼福的机会啊。」

「──？我有哪里很奇怪吗？」

在搔着脸颊的阿尔正面，歪着头的褐色肌肤少女目前裸着身体。虽然没有多余赘肉的美丽裸体表露无遗，但个性似乎完全不懂羞愧。

少女年龄约十二、三岁，感觉是会理所当然具有这方面情绪的年龄。然而……

「唉，这方面会因出生与生长环境而有完全不同的观念吧。还有我喜欢波霸翘臀的前凸后翘身材也派上用场，幸好两边都捡回一条小命啊。」

「是你捡回小命……我没有差别。应该是吧？」

「别自己怀疑自己说出口的话啦……不过居然会在死前出现银发美少女，未免太恐怖了吧。」

有别于寒意的某种因素让身体打了个冷颤，阿尔勉强挤出落魄笑容。被他这么一说，在治疗途中自称亚拉基亚的少女摸着自己的头发。

湿润发丝从发尖滴下水滴，她眯起赤红色眼眸，说：

「银色头发很奇怪吗？公主说过很漂亮。」

「嗯？不是啦，是在说我自己的事，也是我自己的问题。与小姐没有关系，只是银发让我有不好的回忆，会回想起以前是个没用的垃圾。」

「──？」

即使听到阿尔自虐的回答，亚拉基亚还是不解地歪着头。不知道为什么要让救命恩人听这些话，让阿尔更加面露苦笑。

他深深叹了一口气，虽然这样并不可能把心中的芥蒂吐出来。

「没什么啦，只是我以前没有帮到很重要的对象而已。」

「啊……那种感觉我也懂，因为我也没有帮到公主。」

亚拉基亚沮丧地垂下头，轻轻地摸着自己的左眼。

就连在治疗途中，也很在意左眼的眼罩。她的眼瞳呈现明亮的赤红色，然而隐藏的左眼似乎已经失明。

那只失明的左眼，或许就是连系她后悔记忆的关键。

「……真是的，我总是会说些多余的话。」

说出了不必要的事，让阿尔对她感到歉意。自己的无力感连累到有前途的年轻人，这是身为中年大叔最差劲的行为。

在那座岛屿虚度的无为光阴，确实很适合此种自虐。

「抱歉抱歉，刚才说了奇怪的事。说要你忘记好像很不负责任，先别管这件事吧。小姐，你是有事才会从这么危险的湖泊游过来吧？」

「……嗯，没错。这座岛屿被占领了吧？」

「……好像是，我也没有很清楚状况就是了。」

虽然这种不确定的语气对她很抱歉，但当时状况也没办法冷静下来观察周遭，毕竟是突然演变成与剑奴孤岛最强女帝生死对决的局面。

勉强没有受到致命伤，真的已经是奇迹了。

这也是在千钧一发的生死瞬间，勉强苟活下来才能掌握到的奇迹。

「在我差点挂掉的时候，岛上已经被荷奈特与乌比克说服的那群家伙占领了吧……小姐，你的任务是什么？」

「把吊桥放下来，没有吊桥没办法让军队进入岛内。」

「──那可能满难的。」

「唔……」

听到少女的目的，阿尔很快摇了摇头，让少女气得嘟起嘴巴。虽然这是适合年龄的可爱反应，只可惜她的目的没有那么简单就能达成。

在连接孤岛与陆地的吊桥拉起来的这段期间，帝都本队无法登陆。也就是说，吊桥本身便是占据孤岛的剑奴们的生命线。

他们当然也理解这点。

既然如此──

「会把最强的手牌放在那边。说到这个岛上最强的手牌，就是叫作『剑奴女帝』荷奈特的怪物。」

「剑奴的女帝……很强吗？」

「把我打得半死不活的就是那个女人。」

「──？很强吗？」

阿尔指着自己这么说，而亚拉基亚的疑问并没有得到解答。在她眼中看来，这是她对阿尔实力存疑的证据。毕竟只有单手又被打得半死不活，且亚拉基亚应该也有相当程度的实力，被她这么想也无法否定。

不过，荷奈特的实力是货真价实。不只是在剑奴孤岛所向无敌，就连帝国的强者应该也没多少人能与她抗衡。

眼前的亚拉基亚应该比阿尔还要强得多，即使如此还是一样。

「如果小姐你是活得很积极正向就算了……那个放下吊桥的计划可以花好几年吗？」

「……不行，我还有其他要做的事。」

「唉，我想也是啦……」

亚拉基亚摇了摇头，给出理所当然的回应。

听到这个回答，阿尔带着苦笑靠着墙壁站起身。虽然脑袋受到出血的影响仍然昏昏沉沉的，但只要提起精神，感觉还能勉强活动。

见阿尔撑起身体，亚拉基亚眨了眨她那双大眼睛。

「你要做什么？」

「没什么。小姐不是要去岛上吗？为了放下吊桥，需要有熟悉岛内的人帮忙，所以才会救了我。不是吗？」

「……啊。」

「你忘了喔！……呃，太大声吐槽，又开始头晕了。」

不知是否个性容易将注意力放在眼前的事情上，亚拉基亚的态度让阿尔回以苦笑。

说实话，回到充满敌人的岛上这种危险的自杀行为，不管有几条命都不够用，但如果亚拉基亚要上岛就不一样了。

她是救命恩人──即使阿尔的性命只有像沙粒般微小的价值，她还是恩人。

「我不想成为忘恩负义的家伙，所以我会带你到岛上。只不过……」

「──嗯，帮了大忙，战斗交给我处理。」

遇见敌人就夹着尾巴逃走，阿尔将这句话吞回肚里。听见实际上有尾巴的亚拉基亚如此充满决心，态度懦弱的阿尔没什么资格对她说出这种话。

如此决定后，阿尔钻出浮岛的岩石缝隙间，来到外头，瞪着那座可恨的孤岛。

在那座剑奴孤岛上，有群胆大包天的剑奴将众多观众挟为人质，对帝国宣战──

「──虽然决定要回去，可是要怎么去啊。」

阿尔歪着头将耳朵深处的水倒出来，脸颊抽搐地露出尴尬神情。

必须放下吊桥才能登岛的理由──是因为围绕剑奴孤岛的湖泊有大量水生魔兽栖息，必须越过这片湖泊才能登岛。

为了报答恩人，首先必须跨越这道最初的关卡。

15

「喂，刚才那些话到底有哪些是真的？」

「────」

这声窃窃私语令坐在奢华的椅子上渡过无趣时间的普莉希拉闭起单边眼睛。

朝普莉希拉搭话的人，是将半边头发剃掉，留着奇特发型的男子──乌比克将这名使用弯刀的剑奴称为加吉特。

在貌似信奉实力主义的剑奴孤岛，他看来具有一定程度的发言权，应该也有不错的实力，能在这个场合自认为代表便是最好的证据。

或许该说，只有正式代表乌比克不在场的时候才能擅自行动，这种勇敢的态度看来也只是虚张声势罢了。

「别默不吭声啊，贵族大小姐。你知道自己的立场吗？啊？」

「别在那边大声嚷嚷，或许该说你有立场要妾身掂掂斤两吗？你们这群凡俗才是连立足点都分不清楚吧。」

「你说什么？」

「对首领的话语唯唯诺诺，不用自己的脑袋思考。既然连脑袋都没用，装在上面的眼睛、耳朵与鼻子应该也没什么可靠之处。捂着这些感官被牵着手走路，这就是你们现在的立场。不是吗？」

即使被对手威吓，普莉希拉的态度丝毫没有改变。

身旁的裘拉显得焦急不安，即使被骂了一顿的加吉特毫不掩饰不悦神情，但没有贸然动手。

他们剑奴也从占据孤岛的瞬间渐渐恢复了冷静，虽然一头热地发起叛乱，或许也开始对将来益发感到担忧。

因此，他们试图向现场最接近帝国的普莉希拉──不，是向德拉克洛伊伯爵寻求锦囊妙计。

「帝都接下来的举动就像刚才妾身表明的。九神将……会派几个过来要看皇帝，但只要派遣『将』过来，肯定会立刻解决这场毫无理智可言的骚动。」

「……还真敢说，以为我们这边有多少人啊。」

「──与人数无关，这点你应该也很清楚。」

「──！」

不论如何虚张声势，只要是活在帝国并勤练武艺之人，皆能切身体验到与顶端的遥远距离。

连加吉特与其他剑奴，也不认为能与身为活传说的九神将对等抗衡，冷静思考便能发现这点。

「明明知道，你们为什么还要做这种事……」

见剑奴们脸色大变，裘拉喃喃发出不算怜悯也不是同情的话语。听到这句话，加吉特等人便无力地发出叹息。

像他这种弱者，不可能理解这群拥有不上不下力量的男人们有何种心情。

像他这种天生具有地位权力的人，不可能知道这群活在闭塞孤岛的人们有多么绝望。

这点普莉希拉也一样。即使能用想像推断，但还是无法理解，也不可能想要理解。因此──

「你们能走的路只有两条。一条是继续顺着煽动者的花言巧语，作为九神将不放在眼中的喽啰凄惨地丢掉性命。或是……」

「或是……？」

「──反抗宿命，自己赢得存活的机会。」

剑奴们咕噜地咽下唾液，将意识集中在普莉希拉的话语上。

依照现状而言，剑奴们眼前的道路只会通往死路。自行断绝退路并失去前进以外的选择，这个判断只能说是愚蠢。

然而，要是因为无法突破死路而选择放弃，才会失去「死亡」以外的结局。

「────」

「好好用你们没动过的脑袋思考吧，这是你们自己的宿命。」

见他们试图挤出缺乏的智慧，普莉希拉耸了耸细肩。

正当加吉特的眉头增加一条皱纹时，突然有道声音呼叫着他，是回到房间的乌比克。

「德拉克洛伊上级伯爵，方便到观景台一趟吗？可以清楚见到对岸喔。」

「真是无趣的邀约，不过至少比在这里更好吧──你待在这里，要是被做出不必要的揣测就麻烦了。」

「咦！？」

普莉希拉答应帅男的邀约站起身，裘拉对她命令留下的话语露出吃惊表情，但普莉希拉并没有予以理会。

毕竟是自己主动担任这种危险身份，普莉希拉认为得由自己好好完成这个职责。

在留下的裘拉担忧的眼神目送下，普莉希拉跟着走在前头的乌比克，在竞技场的观景台吹着夜风。

吊桥与数小时前同样拉起，将基奴海布与外部隔绝。

但也有与记忆中景色不同的部分，那就是──

「帝国兵好像在对岸布阵了，能见到各处燃起灯火。」

如同用手遮着眼睛上方的乌比克所说，远方陆地能够见到复数火光。可以察觉这是听闻乌比克等人率领剑奴发起叛乱的要求，帝国兵正在散开包围整座湖泊布阵。

战士们备战的兴奋感也微微混在风中飘散而来。

「刚才看您与加吉特他们聊了很久，他们实在很不敢随便轻举妄动吧。偶懂偶懂，毕竟光是煽动他们起义就花了五年的时间呢。」

「别把你这个凡夫俗子的诈术与妾身的伟大之处相提并论，真是不敬。」

「说诈术好难听喔……不过居然对凡夫俗子说出不敬这个字眼啊。」

乌比克发出「咯咯」的愉快笑声，趴在观景台的栏杆上。

他的模样颇缺乏防备，虽然有负责监视的剑奴站在稍远处，但不可能会比普莉希拉更快做出反应。

正如他自己所说，乌比克的举止不像是战士，因此对普莉希拉而言，要取下这个帅气男子的性命易如反掌。

但即使如此──

「做这种事没有任何意义。事到如今把偶的头拿下，这场暴动也不会停止，因为偶只是稍微从背后推了一把喔。」

「哼，从背后推了一把啊。是推了谁的背后一把？」

「──我只是对稍微有感觉的人随便游说而已喔。」

语毕，乌比克露出轻佻笑容，轻轻抓起自己的衣摆。

乌比克掀起奴隶穿的粗陋囚犯服装下摆，展露出自己微微浮现肋骨的身体。这个举动让普莉希拉皱起眉头，但能理解到他并非是想让对方见到自己的裸体，而是其中的一部分。

同时也得知了乌比克为何能煽动这场暴动的答案。

──因为在乌比克的胸口中心处，有个闭着眼睛的第三只眼。

「是魔眼族啊。」

「正确答案。毕竟已经没剩下多少人，很稀奇对吧？偶是少数存活下来的族人喔。」

乌比克将掀起的衣摆放下，轻轻举起双手摆出吓唬的动作。普莉希拉对这个举动毫无反应，只是静静地用手腕搂着自己的手肘。

──即使在亚人族之中，魔眼族算是较为突出且拥有罕见特殊能力的种族。

他们会在身体某处拥有第三只眼，透过该魔眼显现出各式各样的特殊能力。那是类似加持的特性，换言之也能说魔眼族是「必定能出现某种加持」的种族。

加持与魔法具有不同力量，魔眼族打从出生就能够确实获得类似的能力。对于想随意操控此种力量的人而言，可说是垂涎欲滴的宝物。因此过去在佛拉基亚帝国，甚至曾经数度发生围困魔眼族的战争。

而被当成宝物抢夺的魔眼族，在这些战争中人数大量减少──

「现在几乎等于是被灭亡，据说血脉已经稀少到与鬼族差不多了。」

「真是聪明伶俐……没错，偶就是那个稀有种族的族人，虽然被岛主看上与魔眼没有关系就是了。」

「是男妓啊。」

「说来惭愧。」

乌比克用手指搔了搔脸颊，首度由衷说出听似真心话的话语。

但听完乌比克过去承受的耻辱，普莉希拉只是「哼」地发出嗤鼻声。

「有什么好丢脸的。」

「咦？」

「用尽己身力量赢得居所，此乃生物之常理。更不用说，不诉诸武力便能起身而立，这也是靠着智慧得到的结果，甚至可说这并非野兽，而是人类的证明。」

以獠牙互相冲撞夺取胜利，或许能成为强者的证明。而用智慧代替獠牙，则不是强者，而是智者的象征。

不代表哪边较为优秀，两边都有适合的场所。

「……原来如此，真是宽宏大器。」

「蠢货，那是当然的。你以为妾身是何许人等？」

「真是个很难回答的问题。」

面对堂堂挺起胸膛的普莉希拉，乌比克回以苦笑。从他说话的语气，普莉希拉能够猜想到他接下来会说出什么话。

或许该说，如果是乌比克主导这种状况，而且一开始就将目标锁定瑟莉娜•德拉克洛伊上级伯爵，会发现也是理所当然的事。

「──小姐，你不是瑟莉娜•德拉克洛伊上级伯爵吧？」

「这么理所当然的事还用说吗？你和带领的那群凡夫俗子一样都没脑袋吗？」

「别说是装傻，没想到连装都不想装了……」

听到普莉希拉毫无歉意的答案，乌比克垂下肩膀。

另一方面，说到普莉希拉，即使被乌比克看穿谎言也没有任何改变。她原本就不觉得那是能一直通用的谎话。

于是乌比克将看守的剑奴支开，避免两人的对话被周遭听见，能晓得他不打算让剑奴们知道普莉希拉的真实身份。

就某种意义而言，这是乌比克主动让步。虽然他看穿普莉希拉的真实身份，却不打算告诉同伴，相反地──

「偶现在不希望小姐出来碍事啊。」

「无法理解。对你来说，这场叛乱很显然只会被毫无意义地镇压。就算没有吊桥，对岸见到的军势迟早会找到能渡过湖泊的方法，只是时间早晚的问题。」

「偶就是想要那段时间啊。」

「──原来是这么回事。」

乌比克眯起眼睛，静静地说出自己的目标。

刹那间，普莉希拉从先前怀着的疑虑中，总算找出能够接受的回答。为何早已知道会被镇压，乌比克还煽动这场叛乱的原因。

以及他究竟是为了什么必须争取时间。

而从普莉希拉的呢喃中，他也发现自己的企图被看穿而眨了眨眼。

「真令人惊讶。只靠那点线索就看穿偶的目标了吗？而且很奇怪的是，偶不会怀疑你说出的话，你就是具有这种奇特的说服力。」

「──妾身不想管你能不能理解。不过你要怎么做？既然计划已经被妾身看穿，你打算怎么处理？」

「真伤脑筋，偶以为自己还能占上风呢。」

乌比克带着苦笑抓了抓头，普莉希拉隔着衣服注视着他胸口的魔眼。

如果他是使用魔眼族的特殊能力煽动武装叛乱，魔眼应该是拥有能感应他人精神之类的麻烦能力。

然而，乌比克说「不是」，摇了摇头。

「偶的魔眼没有那么方便的能力，怎么想都不可能对你有用。所以把你灭口应该是最好的选择，不过……」

「────」

「有股疑虑让偶不敢这么做。所以……」

语毕，乌比克弹响指头呼叫负责看守的剑奴。有个全身穿着甲胄的高大男子，与上半身赤裸的矮小男子走了过来。

「把她和丈夫带到别的房间，记得要慎重对待两位。」

「说什么慎重，在这里别想要有那么高级的待遇好吗。」

「哎呀，她毕竟是我们的最后王牌嘛。」

如此回应声音彷佛虫鸣般刺耳的矮小男人后，乌比克看向普莉希拉。

他仍然带着无法看出何种感情的深邃眼神。

「还要麻烦你陪我们一阵子了，而且，九神将会粉碎一切之类的想法也许有点太傲慢了呢。」

「喔？你有能让皇帝折损『将领』的策略吗？」

「是的，既然是面对皇帝……我们就只能派出『女帝』了。」

普莉希拉挑起眉头，将乌比克提起的「女帝」这个字眼留在脑海中。

在这个满是剑奴的孤岛中，既然会有被称为「女帝」的人，倘若不是相当滑稽的丑角，便有可能是──

「──有可能是会危害到皇帝宝座的强者。」

16

咕噜噜、咕噜噜，景色正以极快速度被冲往后方。

严格来说这并非正确的形容方式，视野中的东西并没有优雅到能称为景色，实际上被水流冲刷的并非景色，而是自己。

只是阿尔这名独臂中年男子，被水流高速冲刷横渡过湖泊而已。

「噗哈！？」

在水中的高速移动被突然停止中断，但完全无法减低速度的阿尔吐出水，身体在坚硬的地面不停滚动。

然后直接仰躺在冰冷地面上，用力将氧气吸进肺部。

「噗哈、噗哈……我、我还以为会死掉……！」

阿尔拼命呼吸，回想着刚才就两种层面而言生不如死的局面。

刚才那种心情的第一个原因，当然是在无法呼吸的水中；第二个原因便是与水中游泳的魔兽数度目光交会。

魔兽将水中当成庭院般自由自在优游着，如同文字所述般居住的世界完全不同，原本阿尔能漂流到那座浮岛也是连续出现奇迹才有的结果。

──光是思考在水中被魔兽利牙撕裂的次数，就已经是蠢到极点的举动了。

「到了。」

「……嗯，看就知道了。还有这个拿去，把身体包起来。」

亚拉基亚慢了阿尔一步从水中上岸，对于仍然毫不羞耻地赤裸着身体的她，阿尔皱起眉头，将自己破破烂烂的上衣丢给她。

即使衣服已经呈现被血与水沾湿且四处破损的惨况，但至少比起带着全裸少女还要好得多。亚拉基亚也尊重阿尔的意思，将布撕成两半，包起自己的胸部与下腹，脱离危险状况。

就这样，解决了道德面的问题后，阿尔歪着头问道：

「几个小时又重返故乡……不过感觉满诡异的。」

仰望着静悄悄的剑奴孤岛，阿尔面带苦涩地如此呢喃。

目前阿尔与亚拉基亚登陆的位置，是岛屿下方的废弃场──将岛屿中的垃圾与废弃物品等等丢进湖泊，用来喂食魔兽的简易立足地。

虽然直接与湖泊连接，但这里没有安排戒备帝国兵登陆的看守，考量到水生魔兽这个天然屏障，也是理所当然的举动。

「不可能料想到有人这么不怕死从这里登陆吧。」

「这里是用来做什么的？」

「是岛上丢垃圾之类的场所，像是腐烂食物、人类的排泄物、还有变成脏东西的人。」

「变成脏东西的人？」

「就是尸体。魔兽会扫去吃掉，听起来很环保吧？」

听了阿尔的解释，亚拉基亚露出由衷感到厌恶的表情。

姑且不论她的感想，阿尔认为这是很合理的环境。毕竟只要持续举办剑奴之间的生死决斗作为表演活动，岛上便会持续出现尸体。

既然整座岛屿都是用来举办活动的竞技场，便不可能整理出用来埋葬尸体的土地，更别说这种环境就算有墓地，也不会有人前来吊唁。

既然如此，把尸体当成粮食交给魔兽处理算是最快速的方法。

「唉，观众里面也是有爱管事的恶心家伙会把尸体买走就是了。」

「要尸体做什么……？」

「剑奴不是只有像我这种丑男，偶尔也会出现长得不错的家伙，也会有美女流落到这里。就算该死的时候还是要死……要是死状还算完整，还是有人会想要尸体。」

也有不少稀奇种族的亚人成为剑奴，像这种时候，听说有收藏家会想把稀有种族的尸体作成标本。

因为如此这般，除了死后被凌辱的可怜死者以外，大部分死者都会被丢进湖中，进入食物链成为可悲魔兽的养分。

「死掉之后，哪种处理法比较好就不好说了。」

至少阿尔认为，自己死后，被玩弄尸体或是成为魔兽食物都没有太大差别。死了就是死了，不会再留下任何东西。

没有留下任何尸骸才是正确的自然定律。

「──嗯？小姐，怎么一直盯着我的脸？」

当阿尔在心中如此想着时，亚拉基亚将视线投向他的侧脸，就这样用单边失明的眼神朝阿尔看了一段时间后……

「……我觉得还不差。」

「啊？什么不差？」

「你的脸？没有到丑男的程度。」

听见这出乎意料的帮腔，阿尔顿时不知该如何回应。

不只是对亚拉基亚有这种判断基准感到吃惊，考量到阿尔的心情出声安慰也令人惊讶。也或者是并非前述两种原因，她只是单纯地将想到的话说出口，但这样还是很令人惊讶。

阿尔不太喜欢自己的脸，或许该说是厌恶，甚至到了如果能遮起来就想永远遮住的程度。

「──哪里能移动吊桥？」

然而，在阿尔烦恼是否该道谢时，亚拉基亚已经继续推进话题。

阿尔无可奈何地打断思考，说「在那里」，抬起下巴指着头上。

「有看到吊桥前面那座高塔吗？那个就是控制吊桥起降的控制塔。只要能进去，放下吊桥就不算难事。」

「────」

亚拉基亚抬头看往阿尔指的方向，眯起眼睛望着控制塔。

只要亚拉基亚从控制塔放下吊桥，配置在对岸的帝国兵就会蜂拥而入，这场武装叛乱会被镇压，宣告终结。

被乌比克煽动进行有勇无谋挑战的剑奴，应该也会壮志未酬身先死。

「这样就会像四年前一样，一口气失去很多熟人吧……等等喔？应该不会连我一起被处理掉吧？」

「没问题……我会说明。应该不会忘记，一定。」

「喂！你那种不确定的语气很难让人放心啊！还有……」

阿尔在这时打断话语，咧嘴一笑，让亚拉基亚顿时摸不着头绪。

虽然很难对她启齿，毕竟没办法保证亚拉基亚能顺利与本队会合。

或许该说，如果她要前往控制塔放下吊桥，对上在该处严阵以待的「剑奴女帝」荷奈特──胜算几乎可说是趋近于零。

「────」

即使凭阿尔的实力没有立场说嘴，但荷奈特的实力在剑奴孤岛号称最强──阿尔甚至想过也许能匹敌帝国最强战力的「九神将」。

要是乌比克他们的计划想要有胜算，必须要有能与派遣来镇压孤岛的九神将交战并击退的战力。

为了逼迫佛拉基亚帝国上谈判桌，剑奴方也必须拥有足以避免被对方的蛮横暴力压垮的力量。

荷奈特的存在，肯定是乌比克等人计划的「支柱」。

只要如此思考──

「我实在不觉得小姐你能赢过荷奈特。」

亚拉基亚肯定比阿尔还强，但荷奈特是即便集结一百个阿尔都无法获胜的怪物，亚拉基亚也无法获胜。

不如干脆回头，将似乎在对岸的九神将找过来，就像刚才让阿尔被水流蹂躏渡河的方法。

「……那很难。如果是短距离还没问题，可是……」

「唉，要十到十五分钟完全不换气是不切实际啦……可是要赢过荷奈特，我也觉得不合乎现实喔？」

「我在想，既然没办法获胜的话……那就不交手。」

「什么？」

在吃惊的阿尔面前，亚拉基亚从空中抓起某种物体。她抓的是微微散发光芒的微精灵──她毫不犹豫地将没有实体的微精灵放进自己口中，开始咀嚼。

「────」

──她向阿尔说明自己的特殊能力是「吞食精灵」。

吞食在空气中飘浮的无数精灵们，将特殊能力吸收并据为己有，亚拉基亚似乎就是用这种力量与水之微精灵同化渡过湖泊。

她夸下与水同化的豪语，实际上游泳的速度确实不是人类能够比拟，体验过被化为水的她包覆并高速游泳的阿尔也能接受这种说词。

为了渡过湖泊，亚拉基亚吸收了水之微精灵。那如果是从控制塔放下吊桥，她要吸收的精灵就是──

「──风之微精灵。」

「喂喂，真的假的……」

亚拉基亚如此喃喃说着，身体在阿尔面前缓缓与风同化。而与风同化──代表会化为没有实体且无法目视的存在。

只要定睛观察，还是能见到亚拉基亚的身影，但那是要意识到有人在眼前才能勉强看出来。

「可以任意变身还方便……我也从今天开始吃精灵过活吧。」

「不太推荐……因为自己会消失。」

「呃……原来是会无法维持自我之类的类型啊。」

为了「吞噬精灵」与精灵同化，需要绝对无法撼动的坚强自我，似乎需要这类的才能。

原来如此，阿尔认为从这点比较的话，完全不适合自己。

因为阿尔完全没有坚强的「自我」。

「说了那么多，要是荷奈特不在控制塔就好笑了。」

先前把荷奈特形容得那么强，如果这个话题焦点不在控制塔未免太扫兴了。

这样对亚拉基亚完成任务当然会轻松许多。

然而，亚拉基亚并没有对阿尔耍的嘴皮子回以笑容──不，亚拉基亚成为半透明、抹除存在感，望着控制塔，这么说道：

「──不，我想她在那里。」

17

就这样，阿尔怀着疑心与戒心，与亚拉基亚再度回到岛内。

目标是控制塔──或许该说，阿尔只是顺道与亚拉基亚同行。虽然想回报救命之恩，但只要在某处充分回报恩情后，阿尔会斩钉截铁地与亚拉基亚分道扬镳。

就现状而言，告诉她放下吊桥的方法、在岛屿内带路、然后把衣服交给她避免被叫成变态女，光是这几点感觉就已经加了不少分数，需要回报的恩情应该也所剩无几了。

「噗……」

阿尔眼前的短发男从脖子喷出血，毫无挣扎余地倒了下去。

刚才说过话的对手突然受到致命伤倒地，身旁男子顿时大吃一惊。阿尔的职责并非是将吃惊的原因告诉他，对心灵创伤进行咨询。

而是从吃惊男子的腰际夺走小刀，从后方搂着戳进对方胸口，刺进心脏旋转，再拔了出来。

两名看守便无声无息地手牵手在五秒内丧命。

「看不见真的是太犯规了啦……」

「……你也比想像中还强，明明只有一只手而已。」

用尸体的衣服擦拭沾血小刀后，半透明的亚拉基亚如此称赞发出叹息的阿尔。虽然这个感想有点老实过头，但阿尔还是决定虚心接受。

总而言之，感觉浑身是血的男子们衣服已经不能穿了，目前还是需要以半裸中年大叔的身份继续潜行任务。

「不过话说回来，这座岛屿还真的被占领了啊……」

「你以为是谎话吗？」

「我希望是一场梦啦。」

阿尔对这里并没有感情，也没有朋友在──不，只有看守欧兰是阿尔的朋友，因此只有他丧命让阿尔由衷感到悲伤。

但也只有如此。即使在剑奴孤岛住了长达十年，对阿尔来说，回忆顶多只有死去的欧兰，除此之外并没有其他留恋之处。

之所以希望是一场梦，只是因为包含欧兰在内的环境剧烈变化而已。

「是要我怎么做啊……」

在这件事解决后，剑奴孤岛肯定多少会出现变化。既然无法避免不想改变的事与其他事出现变化，那又为了什么留在这里？

或许该说，阿尔在这里待了长达十年，又到底是为了完成什么？

「……什么都没做到，也不打算做什么。」

只是像随风摇荡的草叶，或是浮在水面的叶片般飘摇的日子。

最后会有什么样的结局正在等待，甚至连想像的力气都没有──

「──那里。」

在解决掉看守的阿尔身旁，亚拉基亚突然这么说。

阿尔对她的呼唤屏起气息，朝亚拉基亚望着的同样方向看了过去。该处能够见到被石板地面、天然与人工围绕的控制塔，而其脚下便是──

──能够见到有个巨大的站立背影正背对着两人。

「──！」

就在这个瞬间，阿尔体会到彷佛被抓着心脏的感觉，随即躲在墙壁后方。他只有从通道露出脸一瞬间，别说是成为半透明的亚拉基亚，背对的对方应该连阿尔的身影都没有看见。

但要是对方那时候转过来会怎么样？

「呼……呼……」

用手抵着感到疼痛的胸口，阿尔意识到自己的呼吸突然变得越来越急促。

明明已经跨越并体验过无数次如字面所述的「死线」，但难以逃避的死亡恐惧仍然支配着阿尔全身。

他不是害怕痛苦或绝望这类尝过无数次的情绪。

如果终将结束，要他挑战几百几千次都没问题，但要是永远不会结束该怎么办？

阿尔──阿尔迪巴兰知道这个世界上存在绝对无法获胜的敌人，以及永远无法跨越的高墙。

──那个「剑奴女帝」就是其中之一。

「……哈。」

一想到这里，阿尔对自己的固执成见吐出气息，加以嘲笑。

为什么要擅自认定是绝对无法获胜的敌人，或是永远无法跨越的高墙？其实阿尔没有理由需要与她交手。

正如先前对亚拉基亚说的，目前的贡献应该已经很够回报她的恩情，该是夹着尾巴逃走的时候了。

要是她又发现阿尔，肯定会再度展开追杀。

在被她的毒牙袭击前，必须尽早离开这里。

「小姐……不好意思，我只能陪你到这里了……」

「────」

「一次……不对，是已经差点被她杀了几百次，我实在没办法再跟她交手了。」

阿尔做好被骂忘恩负义的心理准备，向亚拉基亚宣布脱离战线。

要是这时候亚拉基亚气得发动袭击，总比与那个怪物再度展开生死决斗还好。那个怪物是无法跨越的高墙，不过面对她的亚拉基亚肯定能发现获胜的机会。

「──嗯，知道了，谢谢。」

然而，无视于紧张的阿尔，亚拉基亚一派轻松地这么说。

这个平淡反应让阿尔眨了眨眼，但亚拉基亚的态度没有任何改变。她自然地接受了阿尔的畏缩，不打算将他列入用来达成目标的战力。

但这也代表她不想放过那个怪物──

「……我这样说是为你好，小姐也放弃比较好。你也看得出来吧？」

「……应该很强。」

「不是应该，而是真的。至少在我人生见过的生物之中，那家伙大概是第三或第四强。」

「那第一和第二呢？」

「实在不想再去回想了。」

每个怪物都有让心脏结冻般的类似触感，这点倒是没变。

光是想像要挑战，便会回想起像是部分脑袋坏死般的感觉。因为就是不可能赢，不管挑战几次、几百次、几万次都没办法。

因为知道这个世界上有无法跨越的高墙。

「小姐──」

「──掰掰。」

然而，中年男子充满教训语气的诉求，仍然无法阻止这位未来有望少女的有勇无谋。

将阻止的呼叫声当成耳边风，亚拉基亚的半透明身影混在风中，如同字面叙述般以如风的速度冲向控制塔。趁着高挑剑斗士背对这边，似乎望着湖面的意识空档试图闯入──

「──哎呀？真是一阵怪风呢。」

只有活在常理之外的超越者，才能阻止这种举动。

不知道是从风的变化中察觉到什么，超越者荷奈特一回过头，便烦躁地挥出嵌在双手上的大剑。虽然只是随意挥动，但从直直冲来的亚拉基亚正面砍了过去。

要是毫无防备受到这击，亚拉基亚的身体应该已经被分成上下两半。不过少女迅速察觉到接近的死亡，瞬间浮起躲过这击。

──然而，「死亡」舞蹈并没有结束。

「哎呀，哎呀呀，哎呀呀呀。」

「～～！」

浑身散发出彷佛哼着歌般的杀气，荷奈特的死亡之舞狂乱袭卷而来。

与风同化后，亚拉基亚的速度与动作变得超乎常理，荷奈特双手的大剑仍然毫不留情，带着压倒性的杀气持续紧逼。

亚拉基亚拼死地试图逃离「死亡」螺旋，虽然从状况能够清楚感觉到她努力奋斗，但对峙的荷奈特尚未离开玩耍的领域。

──不，对她而言，战斗只是游戏。杀戮是兴趣，虐杀是最喜欢做的事。

因此将亚拉基亚逼上绝路的攻防，只是荷奈特寻求快乐的仪式。

「我就说了嘛……」

嘲笑亚拉基亚有勇无谋的话语还没说完。

明明是显而易见的结果，阿尔却选择不强硬地阻止亚拉基亚。

当然就算用蛮力，也很有可能无法阻止那位少女。但这是只有一次选择的人才会出现这种结论，无法套用在阿尔身上。

只要想阻止就能阻止，却没有阻止。

阿尔已经没有扭曲他人想法的气概了。

因此，他目送着少女挑战早知会送命的战场，以知晓内情的旁观者角度，望着少女在不久的将来将会倒在血泊中的死态。

「────」

内心深处天人交战，感觉有股似乎将心脏压垮的沉重压迫感。

如果这表现的是被迫面对无法忍耐之事物的压力，为什么自己会在这里停下脚步，看着不忍卒睹的景象呢？

并非是「想见证自己选择后的结果」这类帅气理由，自己不是个能如此冠冕堂皇的伟大人物。

只是靠着粗劣武器勉强躲开致命伤，满目疮痍且内心受挫，毫无梦想的中年男子。

明明完全没有挑战的理由、获胜的主因、以及为何抵抗的动机。

然而，阿尔还是──

「啊呜……」

「──哎呀呀。」

无法完全躲开挥出的大剑，鲜血在夜空中四处飞散。

解除与风的同化，半裸少女当场向后仰倒在石制地面上，剑奴孤岛的女帝俯视着染血少女，露出嫣然笑容。

「真是可爱的小妹妹呢。没在这里看过你，你是怎么跑进来的啊？」

「────」

荷奈特微微歪着头如此提问，少女没有回答。被纯粹带着强烈敌意的赤红单眼盯着，荷奈特更加愉快地歪起嘴角。

滴下的血将少女美丽的银发染红，变色的褐色肌肤更加深了她的暴戾之气。

为了享受她接下来会有何种举动，荷奈特高高举起大剑──

「──到此为止了。」

在她用力挥下高举的大剑前一刻，这道声音打断了荷奈特的兴致。

然而，当视线见到发出声音的人时，对此的不满顿时烟消云散。

「哎呀、哎呀呀、哎呀呀呀。」

荷奈特瞪大眼睛，对背对着月色的人影真实身份雀跃不已。

与自己同样缺少部分肢体、与自己同样的罕见黑发、与自己同样从持续从绝境中存活至今的男人──

「──阿尔迪巴兰。」

「别叫我那个名字啦……现在感觉已经不是普通想死了。」

不屑地如此自嘲后，阿尔将短剑指向荷奈特。

比起平常使用的约有身体宽的阔刃刀剑，这是更加粗劣且短距离的武器。先前在竞技场只能彻底逃走并勉强躲过致命伤的男人，再度朝荷奈特展开挑战。

「真是意外呢，阿尔小弟弟以前有这么热血吗？」

「我没有那个意思，只是让美少女年纪轻轻早死很可惜，银发被血染红比想像中还恶心。还有……」

「还有什么？」

对于荷奈特甜甜的疑问，阿尔愤恨地皱起脸颊，露出阴沉笑容。

一股香甜寒意窜过背脊，让荷奈特也回以笑容。

两人就这样互相笑着，阿尔开口说道：

「星星……不，今天要怪就怪我心情不好吧。」

18

「差不多该是毒素要出现效果的时候了。」

「啊？」

听见坐在椅子上的普莉希拉突然这么说，半裸矮小男子顿时目瞪口呆。

在观景台与乌比克密谈后，普莉希拉被带到与裘拉不同的房间，负责看守的两人其中一人就是这个半裸男。

另一个全身穿着甲胄的高大男子沉默寡言，但仍然将注意力朝向普莉希拉，双方似乎都同样对普莉希拉的呢喃声存疑。

因此，普莉希拉竖起纤细手指，好让两人能够看见。

「不是很复杂的事。毒只是用来比喻，为了让资质驽钝的你们能听懂，实际上不是真的有毒，虽然那也是能侵蚀并夺走生命就是了。」

「……越来越听不懂了，可是听得出来你是看不起我们啊。」

在这个豪华程度无法与岛主房间比拟的房间中，被派任无趣看守工作的矮小男子站起身，亮出双手短剑瞪着普莉希拉。

从他那卑鄙的表情来看，能够明显得知他因普莉希拉的发言感到不悦，而且试图对她发泄不满。

然而──

「如果是要威胁妾身，一切都已经太迟了。」

「啊？你以为这种话还能说到什么时候……」

「──哎呀，我觉得她应该会说到死为止喔。」

打断恫吓的声音传来，让矮小男子吓得回过头，动作却被长枪刺出的一击打断，矮小男子被刺穿脸部的长枪一击毙命，当场倒地。

同时传来甲胄互相摩擦的刺耳声响，高大男子也同样倒在红地毯上。动手的人是发型奇特且使用弯刀──是那个名为加吉特的男人。

而与同样砍倒剑奴的加吉特一起赶来的人──

「竟敢让妾身等这么久。」

「不不不，我这样已经算是赶很快了。不只是被迈尔斯大哥打头，上级伯爵还要我静静等待时机……」

「不需要借口，在毒素完全发作前赶来这点就好好称赞你吧。」

普莉希拉一边说着，一边如此褒奖沮丧地垂下肩膀的巴尔罗伊，接着将视线转向加吉特。

身为普莉希拉洒下的毒其中一环，加吉特擦拭着斩杀同伴的弯刀上的血迹，对普莉希拉的视线微微发出咋舌声。

为了掌握自己的命运，看来他决定反抗这个状况。既然加吉特已经展开行动，裘拉房间的剑奴应该也已经下定决心了。

「不过，也有可能与妾身心爱的夫君一起陪葬就是了。」

「你可以不要说得这么恐怖吗？上级伯爵也吩咐要保护彭德尔顿中级伯爵……」

「那你好好努力吧。」

冷酷地抛下这句话后，普莉希拉便拍了拍礼服裙摆，当场站起身。

这场闹剧越来越缺乏乐趣，既然现在已经大致看穿首谋乌比克的企图，便不会再有多少排遣无趣的空间了。

既然如此，普莉希拉•彭德尔顿能做的事只有一件──

「──这个粗劣舞台的闭幕，至少由妾身来增添些许风采吧。」

19

──背负着湛蓝的明月，在吊桥控制塔前与强敌互相对峙。

「────」

连阿尔都不禁对这种颇为戏剧化的景象发出自嘲。

单手剑士与浑身是血倒在身旁的少女，简直像是英雄故事或宏伟叙事诗的一幕般，但前提是两者都要能顺利脱离险境。

要是无法如愿，便会沦落为点缀故事的常见悲剧。

如果在场的人不是自己，而是更有实力与天赋的勇士，肯定会是更为经典的画面。

「这也有可能是经典场景，只不过是地狱般的景象就是了。」

阿尔面露苦涩地强忍着后悔，将右手举着的短剑前端朝向正面。明明连拿着爱用的青龙刀都会屈居劣势，只有粗陋短剑真不知有多么不可靠。

阿尔很快开始感到后悔，荷奈特望着他这模样，嫣然一笑。

「──心情不好啊。」

反刍着先前阿尔的大放阙词，「剑奴女帝」发出如揶揄般的嗤笑。

荷奈特将双手手腕以下缺失的部分装上大剑，两公尺以上的修长身材甚至像是三个人并排在一起──让阿尔再度认为真是夸张的轮廓。

真正的强者是一眼就能看出没有胜算。

由这点而言，荷奈特合乎最初的条件。原本欠缺肢体会以为是明显劣势，但荷奈特顺利地将其升华为强项。

「唔呵、唔呵呵、唔呵呵呵。」

无视阿尔的感慨，荷奈特彷佛搂着双手的大剑般发出笑声。

即使被旧识刀锋相对，她的模样看来既悠哉且愉快。

「有那么好笑吗？」

「阿尔小弟弟应该也知道，我一直很想和你相杀吧。」

「虽然不想知道，不过是知道没错。我们也已经相杀过了吧？我不是被你打得七零八落吗？还被踢进尸体用的洞穴吧？」

「可是啊，你现在在这里，不就是这么回事吗？」

「是怎么回事啦……」

只可惜，阿尔无法理解战斗狂的思维。

虽然在剑奴孤岛待了十年，但阿尔从来没有享受过战斗。如果是厌烦地持续战斗，至少一次沉溺在胜利的美酒中也不会有人怪罪。

但阿尔还是没办法，他并没有夺走他人性命还能感到高兴的强韧精神。

以后肯定也是这样。所以──

「我和你永远不会互相理解吧，荷奈特。」

「不用互相理解啊，阿尔小弟弟。只要我能打得高兴就好了喔。」

简直是女帝，荷奈特这种单方面的价值观，甚至爽快到很有帝国风格。

当然，前提是自己并未成为这种价值观的牺牲者。

「丑……男……」

「在那边乖乖看着吧，小姐。还有你刚才说过我没有那么丑的意见，我可是满当真的喔。」

「────」

亚拉基亚以难掩痛楚的表情紧盯着阿尔。

虽然她的单眼缺乏感情，但显而易见地正在表达阿尔处于劣势的诉求。

「压倒性劣势，这点我自己最清楚啊。」

但不需要她多说，阿尔开始数起自己挑战这场愚蠢战斗的胜算。

「那我要上啰，阿尔小弟弟，别那么简单死掉喔。」

荷奈特随着甜美声音轻快地挥出双手大剑，桥上刮起风暴疯狂袭卷。阿尔随即蹲下身，举起短剑试图抵抗强风──

「──！」

身体连同试图抵挡的短剑一起被扫了出去，阿尔轻易地失去性命。

20

「──引起这场骚动的目的，应该就是皇帝的首级吧。」

「喔喔喔，没想到会出现这么跳跃的答案啊。」

普莉希拉拉着礼服裙摆，跨过倒在通道上的剑奴尸体。刚才用枪刺穿剑奴心脏的巴尔罗伊，对她的话语顿时目瞪口呆。

普莉希拉毫不犹豫地向前持续挺进，替她开路四处奔走的青年却没有任何怨言，用沾血的枪尖指着四周说：

「岛上剑奴发起武装叛变，对帝国表示希望获得解放的诉求……实际上也是这样，如果是这种剧本我还能相信，可是从这种情况要怎么拿下皇帝的人头？皇帝应该不会亲自过来解放人质吧？」

「就是你说的那个可能性，皇帝不可能做出危及自己性命的决定，除非那是取得对方首级的必要手段……」

「不不，就算是这样也太过头了吧。」

普莉希拉如此堂堂说着，巴尔罗伊用手抠着脸颊回以苦笑。

这位大胆少女的发言十分具有说服力，要是放空脑袋，感觉就会顺势点头接受她所说的话。

即使如此，她那彷佛近距离认识皇帝的语气还是太过大胆了。

「夫人的看法会不会太跳跃了？顶多拉出皇帝直属的九神将就已经是极限了吧，实际上对岸也只有九神将过来的样子……」

「看来你还是会转动不太灵光的脑袋，那就多想想看吧──要是派出九神将，岛屿会怎么样？」

「呃……武装叛变会失败，剑奴也会被全数镇压吧。」

巴尔罗伊毫不怀疑地如此断定，陪同的剑奴加吉特面露苦涩，但这也是事实。

身为武人顶点的九神将，资质与其他国家的选拔标准截然不同。

与家室或人格毫无相关，只尊崇「强大」便是佛拉基亚的风格。

因此剑奴会一个不留地被制伏，这也是清楚至极的结局。

「没错，既然是清楚至极的结局，那首领为什么要策画这场会被击溃的叛乱？」

「呃……？会派九神将过来，剑奴绝对会被歼灭的话……」

「绝对会被歼灭──但九神将肯定会暂时离开皇帝身旁。」

「────」

听到普莉希拉重复强调，巴尔罗伊瞪大眼睛。

他忍不住咽下口水，开始咀嚼这番话的意思，然后说着「不不」并摇了摇头。

「我是能理解啦，可是只有一两个九神将离开身边，保护皇帝的阵容还是无懈可击吧？九神将就是有九个才叫九神将，可是……」

「那如果除了剑奴孤岛以外，也发生了必须派遣九神将的骚动，又会怎么样？」

「该不会……」

与这里不同的周到计划互相配合。

面对这种可能性，巴尔罗伊无法用「怎么可能」从脑中予以否定。

实际上，巴尔罗伊等人被封锁在剑奴孤岛，与外界的情报也跟着断绝，即使其他场所与这座岛屿同样产生骚动也无从得知。

但帝都就无法同日而语了，要是出现同样类型的骚动，便会投入镇压所需的战力──也就是皇帝直属的九神将。

「皇帝与亲信不会如此掉以轻心，不可能让所有九神将都离开身旁。但人数还是会减少，相对地也会出现绝佳机会。」

「……意思是岛上剑奴和这场骚动完全都是弃子吧。」

听完普莉希拉的推敲，巴尔罗伊惊恐地舔了舔干燥的嘴唇。

对方不顾损害的计划也十分值得赞赏，为了达成目的，策画出容许众多牺牲的阴谋，实在是做得相当漂亮。

但对普莉希拉能够看穿这个策略的洞察力，有股更加难以掩饰的彻骨寒意。

在这个少女的深红眼眸中，这个世界究竟是什么样子？

但唯一能够确定的，便是这位少女不可能甘于「裘拉•彭德尔顿中级伯爵的嫩妻」这点程度的地位。

「……开什么玩笑。」

然而，不同于能够接受这推论的巴尔罗伊，被当成弃子的当事人加吉特就没有这么好说话了。

他的嘴唇愤怒地不停颤抖，眼瞳中燃烧着熊熊怒气。

「皇帝的脑袋？那和我们无关！我们只是……」

「只是想从死巷中逃出来吗？就是这么随处可见的动机，才会被轻易利用──你们多动点脑袋吧。」

「──你、你这家伙！」

加吉特拔出弯刀，将刀刃举向说话毫不留情的普莉希拉。

突然演变成一触即发的紧张气氛，巴尔罗伊对两人招着手，耸了耸肩。

「别这样啦，老兄。你发泄怒气的对象不是夫人，就算做这种事也没有意义吧？」

「闭嘴！没有意义？这样说的话，不管我们做什么都没用吧！如果只是解放岛屿就算了，还扯到暗杀皇帝？这样我们会成为共犯！」

「呃……那只是夫人的推测，又不代表真的会这样……」

「住嘴，耍枪的。你应该也知道那只是安慰的话……那个丫头刚才说的话说服我了。」

面对加吉特皱起眉头的诉求，巴尔罗伊无法做出任何回答。

在巴尔罗伊心中，也与加吉特同样接纳了普莉希拉的意见。她这番话具有说服力，敌方目标肯定是皇帝的首级。

这样即使加吉特等人不知道内情，还是会成为暗杀皇帝计划的共犯。

当然，就算事情顺利结束，还是难逃死罪。

「────」

巴尔罗伊同情着加吉特的立场，闭起单边眼睛开始思索。

只要巴尔罗伊拿出真本事，就算从原地还是能靠一枪攻击加吉特的脑部或胸口。只要瞬间贯穿要害，便能毫不痛苦地夺走他的性命。

但靠加吉特的力量，有可能会避开致命伤，并对普莉希拉造成危害，得尽可能避免普莉希拉受伤的情况。

虽然还有主人瑟莉娜的命令，不过巴尔罗伊自身的判断也是如此。

绝对不能在这里失去普莉希拉。

「──你还在磨蹭什么？巴尔罗伊•特梅格里夫？」

然而，出声呼唤逡巡的巴尔罗伊的人不是别人，便是普莉希拉。

即使被弯刀指着脖子，她仍然朝巴尔罗伊投以无所畏惧、若无其事的表情──不，是平常那道如火焰般的眼神，继续说道：

「这个世界是为了妾身量身打造的。」

「────」

「所以你的决定不会危害到妾身，千万别忘了这点。」

普莉希拉以平淡语调表明自己是世界中心。

这番斩钉截铁的发言，让巴尔罗伊与加吉特皆倒吞了一口气──随后。

「喝啊～～～～！！」

「嘎唔！？」

随着这道充满气势的沙哑吼叫，从旁丢来的瓦砾直接击中加吉特的侧头部。

冲击力道让加吉特发出闷哼，从该处冲出的人影这回以手中拿着的瓦砾，毫不留情地由上往下朝剑奴头部砸了下去。

加吉特不支倒地，掉落在通道的弯刀碰撞出清脆声响。

「哼！居然敢对上级伯爵刀刃相向，真是个大逆不道的家伙！」

「迈、迈尔斯大哥？」

将加吉特击倒并如此夸耀的男子──迈尔斯的出现让巴尔罗伊吃了一惊。

原本应该在观众席护卫瑟莉娜的他突然出现，当然会让人感到吃惊，但迈尔斯只是瞪着惊讶的小弟。

「你这个大蠢蛋！在这里拖拖拉拉做什么！要是你犹豫的时候，让彭德尔顿伯爵夫人受伤该怎么办啊！蠢货！」

「又是蠢蛋又是蠢货的……没那么严重吧，迈尔斯大哥……」

被迈尔斯口沫横飞地臭骂了一顿，巴尔罗伊沮丧地垂下肩膀。

但多亏这位大哥介入，先前揪紧心中的那股闭塞感顿时消失，对加吉特态度犹豫不决的阴霾也总算一扫而空。

「即便有器度，还是要有能封口的盖子，不过你倒是找了个颇为俗气的盖子啊。」

见到巴尔罗伊放下心的模样，普莉希拉眯起眼睛如此呢喃。

途中会合的迈尔斯似乎听不懂这是什么意思，但巴尔罗伊能够理解。确实如此，大哥从以前就会替他弥补不足的部分。

「毕竟我脑袋不是很灵光，所以很多事都只能靠迈尔斯大哥了。」

「怎么怎么，你们在说什么？不对，现在那不重要！夫人您没事吧！上级伯爵也很担心您啊！」

盖过巴尔罗伊的话语，将加吉特绑起来后，迈尔斯确认着普莉希拉的安危。

发出呻吟声的加吉特似乎没有丧命，只是让他延后做出决定。巴尔罗伊感谢着迈尔斯的行动，点了点头说「那当然」。

「夫人没有半点皮肉伤，完全照着上级伯爵的指示喔。」

「吵死了！没有人问你啦！看你杵在敌人面前的样子，这句话还有什么说服力啊！是我迈尔斯在危急时刻救了夫人……」

「少啰嗦，别像发情的猫吵吵闹闹的。妾身没有受伤──出发了。」

让邀功的巴尔罗伊与迈尔斯闭嘴后，普莉希拉迅速地转过身。

跟在直接迈出步伐的她身后，但巴尔罗伊发现她前进的方向，并非是裘拉被囚禁的岛主房间。

「呃……夫人？就算往那边去，彭德尔顿伯爵不在那个方向喔？」

「蠢货，妾身心爱的夫君之后再说。即使对方的真正目的是暗杀皇帝，目前的困境还是在岛屿内部，首要之急是镇压这场骚动。」

「咦？敌人的目标是暗杀皇帝？那、那是怎么回事！？什么意思！？」

无视于迈尔斯慢一步得到情报的惊讶反应，巴尔罗伊则说「那要怎么做？」，向普莉希拉寻求下一步的指示。

既然不是拯救裘拉，而是以结束剑奴孤岛骚动为目的展开行动，她究竟要去什么地方？

那个地方就是──

「刚才那个剑奴已经清楚展现出来了──要让那些剑奴知道自己的立场。」

21

在剑奴孤岛「基奴海布」中，会利用剑奴举行各式各样的表演活动。

最简单的活动，便是让剑奴单挑进行生死对决。

有时候会是团队战的形式，也有举行过三对三或五对五的团队生死对决。

根据场合不同，还会将魔兽带进岛上，举行面对巨大魔兽的讨伐战等等，只要是为了满足观众对血肉饥渴的欲望，不论什么事都做得出来。

只要能滋润对暴力的渴望，剑奴孤岛容许各种「战斗」。

但即使是在这座剑奴孤岛上，要将这种场景称为「战斗」，应该也会有所忌讳。

毕竟──

「──别那么简单就死掉喔。」

随着这句话施展出的狂风，阿尔不论过了多久都无法攻略。

如风暴般疯狂挥舞的斩击，从上下左右毫不留情地压榨世界，简直是破坏的象征。不论是向后跳开、用短剑接下、往旁边往前往斜向、不管往哪跳跃都会死。

头被打碎、身体被切断、脚被砍断、手腕折断、内脏四处飞散──即使尝试了无数次，仍然无法避免性命被凌辱的未来。

这是虐杀，发生的景象只能以凄惨形容。

来到剑奴孤岛的观众中，也许会有光是见到小虫被辗碎便会感到喜悦的稀客，但大多数人只会对这种结果感到失望。

如果只是想见到人死去，来到剑奴孤岛的掌权者在自己领地随便动手即可。

他们想看的是互相夺取性命，以及将决斗视为生计的战士们的极限对决。

就这层意义而言，眼前景象了除了期待落空以外，别无其他形容方式。

或许该说，对自己被击碎后的景象会有何种想法，对阿尔而言可谓毫无关系。

「多纳！！」

数到刚好二十次左右的时候，阿尔豁出去施展魔法。

没有锁定目标就念出这段咒语后，桥上地面掀起露出，岩石块的前端刺向荷奈特，让大剑的目标偏离阿尔。

拼命冲进瞬间产生的空隙，阿尔勉强躲过第一道攻击。

拉开距离，跨越过最初的死线后，正当阿尔放心地松了一口气──

「──噗。」

才刚准备松口气，头部便被挥下的一击打碎。

「──别那么简单死掉喔。」

「多纳！！」

一开始便彷佛照着刚才的发展般使用魔法，配合岩石块碎裂的动作往后跳开，然后喘了一口气立刻跳往旁边。

呼啸一击打在地面上，有股整座石桥都在剧烈摇晃的错觉。荷奈特直接将大剑抵在地面，扭动身躯将刀身划破地面，挥向阿尔。

跳过这道粉碎一击，阿尔的刺击抵达荷奈特面前，但这道浑身解数的攻击，却被挥开虫子般的动作轻易扫开──

「就是这样！阿尔小弟弟果然很厉害嘛！」

「是这样吗？我只是照字面意思拼死应战，其实心底觉得这样做根本不划算喔。」

虽然对出声喝采的荷奈特不好意思，只可惜阿尔与她看到的世界完全不同。

对她而言，阿尔或许是能在危急状况中发挥超常应对能力的高手，但只要战斗越是拉长，阿尔总是会对自己的评价越发沮丧。

每次像这样见到强者的时候都会如此思考──自己没办法像她们一样。

并非是只有单手或是年龄的问题，而是身为生物素养层面的更根本差距。

正如「老虎为什么会很强？因为是老虎」这句名言所述。

强者之所以会强，因为生来就是强者。

弱者之所以会弱，因为生来就是弱者。

没有除此之外的原因。

因此──

「还不够！让我更尽情享受吧！」

荷奈特愉快地挥动大剑。面对这个强者，阿尔这个弱者只能不断被蹂躏践踏数十次、数百次、甚至是数千次。

22

亚拉基亚紧紧盯着凶残的大剑士与单手剑士交战。

开始战斗只经过短短数十秒──但两者之间的各种攻防可说是犀利无比，让性命垂危的少女不由得盯着猛瞧。

「────」

先前带着亚拉基亚来到此处的男子，正在与大剑士荷奈特交锋。

由于荷奈特称呼他为阿尔小弟弟，所以名字应该就是阿尔吧。

虽然阿尔面对荷奈特勉强存活下来，在亚拉基亚眼中却是难以置信地连续出现奇迹。

说来惋惜，阿尔的实力由亚拉基亚看来，顶多只有二流程度。

毕竟是在剑奴孤岛过活的剑奴，应该是跨越过无数次赌上性命的战斗，但即使几经生死关头，还是无法期望能有更强大的实力。

这就是阿尔这名男子实力的极限，与称为「剑奴女帝」的荷奈特之间，有难以弥补的实力、才能与力量差距。

只要有心，就连亚拉基亚都不需要几秒便能制伏阿尔。

但现实又如何？

「好厉害……」

并非是对阿尔的实力提高了评价。

但阿尔在千钧一发之际勉强架开或躲开荷奈特的剑击，再以拙劣动作进行反击的模样，彻底颠覆了亚拉基亚对他的评价。

照理说他已经死了，那点程度的实力面对荷奈特连两秒都撑不过去。

可是，阿尔却活了数十秒，甚至试着反击。

不同于偷偷摸摸抹除身影想偷袭荷奈特却失败的亚拉基亚，他从正面堂堂正正挑战，持续战斗。

──而且他挑战荷奈特的原因，是为了保护亚拉基亚。

「──！」

亚拉基亚咬紧牙根，开始对自己的手脚使力。

比起锋利程度，大剑的一击对少女带来彷佛被敲碎的破坏，应该已经有几根骨头折断，内脏或许也受到相当程度的损伤。

虽然有用吸收的水精灵力量进行治疗，但无法立刻痊愈。

而且──

「我瞄～」

荷奈特刻意说出这句话，仍然注意着亚拉基亚的方向。

即使与阿尔交手，荷奈特还是紧盯着亚拉基亚的动向。要是亚拉基亚想趁机冲进控制塔，肯定会立刻进行阻碍。

不甘心的是，亚拉基亚不像阿尔有办法躲过攻击。要是被一刀击杀，便会让阿尔失去挺身而出的意义。

既然如此，亚拉基亚还有什么能做的事？

就连面对最珍贵的主人，亚拉基亚都无法做出任何回报──

「公主……」

亚拉基亚垂下头，唇瓣喃喃念出那彷佛另一半身体般重要的对象之名。

从出生以来便在身边，却无法再待在对方身旁的那个人。

那位少女态度高傲，总是露出如同支配整个世界般的目光，对亚拉基亚而言她就等同于支配者──

『──听着，在剑奴孤岛四散的所有闲杂人等。』

瞬间，有道极为高傲的呼叫声响彻剑奴孤岛的天空。

突如其来的声音让亚拉基亚吃了一惊，阿尔与荷奈特也停下战斗，露出不解神情，但亚拉基亚的吃惊程度远远高过两人。

他们是对突然传来声音感到惊讶，但亚拉基亚并非如此。

因为她曾经听过这突然传来的声音。

『这场武装叛变没有未来，首领的目标是皇帝首级。解放岛上剑奴不过只是表面话，你们这些无首的悲哀士兵只是被煽动怂恿罢了。』

『等待着你们这群愚者的只有死亡，但现任皇帝并非毫无慈悲之心。只要你们展现出相对应的态度，便会好好裁量关于你们的处置，尽可能转动你们那空荡荡的脑袋吧。』

『来吧，无首士兵。如果想取回脑袋，就只有现在了。』

无视哑口无言的亚拉基亚，这道桀敖不驯的声音将想说的话彻底说完。

那是由孤岛各处设置的金属传声管传来的声音，不只是亚拉基亚等人所在的桥上，应该还传遍了岛屿各处。

震惊的亚拉基亚没有余力深思刚才那段话的内容。

但阿尔与荷奈特并非如此。

「……不知道是哪个家伙，看来是想彻底扭转局势。」

「好像是呢。刚才那段话肯定会让胆小的家伙改变念头，明明说不定还有可能让计划继续进行下去呢。」

「哈，说什么鬼话，你也不觉得会进行得那么顺利吧。」

「唔呵呵呵呵。」

荷奈特抱着大剑开口笑着，在金属挤压声中扭动身体。阿尔带着愤恨眼神盯着她，继续开口：

「我说啊，虽然在这里过着安定生活听来也是满蠢的，不过你会放弃这种生活参加乌比克的计划，应该不是以暗杀皇帝为目的吧？」

「当然不是啊，我对皇帝那种天上人没有兴趣。如果实力很强是想找他过过招，可是原因不是这个喔。」

「嗯，看来是这样。也就是说，你的目标是货真价实的比试……意思是占领岛屿之后，想与派遣过来的九神将交手吧，真是个脑袋有病的家伙。」

阿尔不屑地如此说着，荷奈特仍然不改笑容。

既然没有否定，表示阿尔的见解确实没错──荷奈特的目的是与九神将对战，只要把吊桥放下来就能实现这个愿望。

「那把吊桥放下来不就好了？」

「对啊，可是像这样与阿尔小弟弟交手也是很甜美的诱惑。还有很多剑奴我没交手过，所以……」

「呃……等等，有种不想继续听下去的预感……」

「等我把岛上的人全部杀掉，没有能交手的对象再放下吊桥喔。」

「就说我不想听了嘛……」

荷奈特的冒渎想法，让阿尔由衷感到厌恶地撇起嘴。

将剑奴孤岛的人全部杀光，杀害包含剑奴、相关人士与访客在内的所有人，将遗憾一扫而空后再与九神将展开激战──简直是壮阔无比的拉人陪葬计划。

「你应该不会认为自己是世界最强吧？就我所知，世界最强的生物目前正在露格尼卡背着书包喔。」

（插图014）

「我不会误以为自己是世界最强啦。嗯嗯，应该会是这样，我会在战斗中用尽全力死掉吧。」

「────」

「可是这样就好，我的愿望就是在战斗中华丽死去──我要赌上家族的名号，痛快大干一场再死掉喔。」

说出对自己死亡的展望后，荷奈特好战地舔了舔嘴唇。

荷奈特表示出自己已经做好绝对不会退让的决心，听到这个狂战士的答案，阿尔眯起黑色眼瞳，用手中不可靠的短剑刀尖搔了搔自己的颈项。

接着──

「怎么每个家伙都这么会从死亡中找出特殊价值，真是有够蠢的。」

「────」

「死亡不是救赎也不是宝物，只会很痛又难受而已。为什么连这都不懂？」

阿尔带着冷淡目光与表情，打从心底对荷奈特感到轻蔑。

阿尔的黑色眼瞳深处蕴含强烈感情，充满让见者心底发寒的凶气，彷佛没有任何人窥探过的深渊沉眠于其中。

甚至连常保游刃有余态度，并且斩钉截铁地表示自己赌上生死的目的不值得一提的荷奈特，都犹豫着是否该回嘴。

「……我也要一起战斗。」

「喂喂，小姐。我觉得你不要太勉强自己比较好，继续躺着休息吧。」

「不能这样。」

趁着对话的空档，亚拉基亚缓缓用四肢撑着地面站起身。

先前被割开的肩头与骨头碎裂的伤势已经愈合，恢复到即使动作也不会再度碎裂掉落的程度。虽然还不到万全状态，但也不能让阿尔孤军奋战。

要是让自己失误而连累的人死去，这样才会没脸面对公主。

「──公主。」

从传声管传来的，是对亚拉基亚而言最重要的少女发出的声音。

那是她没有任何改变的证据。别说是将世界纳入掌中，甚至是深信不疑地将世界踩在脚下，身为这个世界的支配者的高傲声音。

听见那道声音，亚拉基亚心中的灵魂开始熊熊燃烧──有种再度被支配的感觉。

「我还是公主的所有物……！」

实际感觉到这点，对亚拉基亚而言是比一切都更值得高兴的事。

就这样，见亚拉基亚的单眼发出炯炯目光，阿尔似乎也决定不再泼她冷水。

他重新握好短剑，朝向正面，与亚拉基亚两人前后包夹荷奈特──

「那就让你如愿打输吧，荷奈特──没有人能赢过我的。」

23

普莉希拉握着传声管将声音传遍岛屿后，便将脸从传声器拉开。

听见先前基奴海布武装叛变的真正目的──是为了暗杀皇帝铺路，让岛屿各处顿时传出开始骚动的气息。

正如普莉希拉的目标，剑奴们似乎开始产生对立。

「相信武装叛变会成功的家伙，与多少还会动点脑袋的人会产生歧异，表示会成为两个目标相异的武装集团。既然已经习惯被迫进行夺命的生死决斗，先发制人较为有利这点也不必多提。」

「……看来是这样啊。」

先前仔细竖耳聆听的巴尔罗伊，比普莉希拉更加正确地以声音掌握了岛屿的状况。

他运用优秀五感，说着「嗯嗯」并点了点头。

「就像夫人的见解，很多地方好像已经开始出现争端。照这样看来，感觉放着不管他们自己就会全灭了……」

「哪有那么简单，那些家伙又不是虫子或鱼。如果人数一口气减少，很快就会察觉情况不对劲，希望在那之前顺利解决啊……」

「也不会那么顺利。只要有相对会动脑的家伙留下来，就会开始思考接下来的对策，大概会是将有力权贵当成人质，以不靠首领的形式展开新一轮谈判吧。」

「喔……」在如此表示理解的迈尔斯身旁，巴尔罗伊疑惑地歪着头。

巴尔罗伊的脑袋不太灵光，搭配缺乏武力但会耍小聪明的迈尔斯。确实如同瑟莉娜的见解，他们似乎是处在能互补的良好关系。

对于相对重视外观的普莉希拉，虽然迈尔斯无法触动琴弦，但只招揽巴尔罗伊肯定也不会有好结果。

为了心爱的夫君，只要能与上级伯爵维持良好关系也是不错的选择。

「迈尔斯大哥，感觉有种被秤斤两的感觉耶。」

「别说出口啊，白痴……不过明明是个丫头却很有威严，而且既高贵又骄矜自满，好想被她凌虐喔。」

这两个情同兄弟的男人互相把脸凑近，似乎正在窃窃私语，但这番悄悄话在普莉希拉与众不同的听力下彻底露馅。即使迈尔斯的嗜好颇为冒犯，但普莉希拉认为只是心中想想便不算罪过。

毕竟男人对普莉希拉产生情欲并难以自拔，是很理所当然的反应。

「────」

接受着两人的视线，打头阵的普莉希拉继续沿着通道前进。

途中只要有人阻挡前进，便会由巴尔罗伊悉数排除。甚至连剑奴孤岛的历战勇士，在他的高超枪法下丝毫不足挂齿。

接着，普莉希拉毫不费力地来到目的地的房间──

「──滚开，凡夫俗子。妾身来要回夫君了。」

「啥！？」

普莉希拉大方地踹破岛主房间的门扉，她的出现让房内男性们皆大吃一惊。

其中最为吃惊的，莫过于坐在中央椅子上的裘拉。见到被带走的普莉希拉出现，他高声喊出：「普莉希拉！？」

这番忘记曾经做过伪证证明她是瑟莉娜的发言，让普莉希拉微微发出咋舌声。

「居然五十岁左右就开始痴呆，夫君还真是令人头疼。」

普莉希拉一边如此呢喃，一边拿起门扉旁的花瓶丢进室内。花瓶不偏不倚地击中裘拉坐的椅背，让他迅速地翻了过去。

裘拉的身影瞬间从室内男性们视野中消失，趁着这个空档──

「──去吧，巴尔罗伊。」

「好好，悉听尊便。」

被叫出名字如此下令，巴尔罗伊如同闪光般冲进房间。

见有人闯入，慢了半拍才对普莉希拉做出反应的剑奴们一起拔出武器，室内的六人同时展开行动准备迎战巴尔罗伊。

但还是太迟了──瞬间，长枪描绘出巨大的半圆形。

「不只是突刺，横扫也是长枪的绝活。是不是误判了啊？」

巴尔罗伊闭起单边眼睛后，被划开腹部的三名剑奴内脏四处飞散，然后直接往前倒卧在自己腹部喷出的肠子上。

「吁～～！！」

跨越过倒地的三名尸体，活着的两名剑奴试图对巴尔罗伊展开反击。

两人分别是将拳头打上钢钉的拳斗士，以及手握两把飞斧的兽人。虽然两人攻击范围都比长枪短得多，但只要被冲进怀中，便是适合小幅度活动的两人占有优势。

实际上他们也是冲进巴尔罗伊怀中，试图发挥出短程兵器的真正价值。

「以为枪手只会用枪，思考模式会不会太狭隘了啊。」

刹那间，挥出的左拳直接击中拳斗士的脸部，冲击力道将拳斗士的意识与门牙击飞。原来是巴尔罗伊将长枪换回右手，用空着的左手殴打男子。

被殴打而失去意识的男子身体，直接飞向兽人挥出的飞斧轨道上。

男子的后脑勺发出坚硬声响碎裂，失去的意识永远无法找到归处。但兽人仍然毫不在意地继续朝手腕使力，试图连同拳斗士的头一起击溃巴尔罗伊的细瘦身驱。

虽然亚人特有的豪迈力量确实很有看头，然而──

「就算是这样，还是我比较快。」

巴尔罗伊放开右手的长枪，如同箭矢般刺出贯手。竖起的两根手指刺进兽人脸部，指尖贯穿眼球，夺走对方视力。

兽人发出惨叫，仰起头的动作极为缺乏防备。

巴尔罗伊用脚跳起，左手接住长枪，用枪尾划开对方喉咙。兽人血沫横飞地往后倒地，浑身抽搐，甚至无法发出临死惨叫。

这样房间内的六人已经有五人丧命，至于最后一人──

「别动！一动就把这个男的──」

那名男子并非锁定巴尔罗伊，而是冲向倒地的裘拉。

虽然这个剑奴的判断相当确实，但他最多只有将短剑抵在裘拉的颈项上。

「──动手！盖乌斯！」

「────嘶嘶！」

站在普莉希拉身后入口处的迈尔斯如此喊叫，瞬间房间的天花板碎裂，从该处伸出的翼龙头咬住压制裘拉男子的头。

男子无法抵抗地直接从天花板被拖到外面，然后传来惨叫声。

接着，从天花板大洞流出大量鲜血，淋在正下方的裘拉身上。

「噗啊！？血……是血！？普莉希拉，我已经……」

「蠢货，不是你的血，是那个凡夫俗子的血。」

见到浑身是血差点昏倒的裘拉，普莉希拉傻眼地发出嗤鼻声。朝上方瞥了一眼，正好与从天花板窥视内侧的翼龙视线交会。

曾经见过这头翼龙，那是飞龙船接送普莉希拉等人到剑奴孤岛的其中一头翼龙。由于是迈尔斯发出命令，表示应该是他的爱龙吧。

「做得漂亮。不过……」

「这里就是所有人了吗？那个首领呢？」

环视整个房间，察看过尸体的脸，没见到那个身为首领的帅男乌比克。

在眯起深红眼眸的普莉希拉身旁，将长枪扛在肩上的巴尔罗伊也寻找着同样的敌人。但乌比克似乎已经离开现场──不，不只是离开岛主房间。

「也有可能是从岛屿逃出去了。」

「不过吊桥还是没放下，应该没有逃出去的方法吧。」

「虽然不是很容易达成的手法，还是有使用传送的可能性。那是能瞬间跳跃到远处的魔法，在帝都的皇帝之间也有隐藏类似的机关。」

「哇，感觉光是知道就会被杀掉的情报。」

多亏深植于心的教育，两人没有回问为何普莉希拉知道这件事。

对巴尔罗伊与迈尔斯的评价改观后，普莉希拉从房间观景台望着外面，让自己听着乘风而来的剑戟交锋声响。

「普莉希拉？呃……在这里待太久感觉会很危险……」

「大势已定，再来只剩剑奴们决定自己的立足之地，放下吊桥的方法随便找都有──现在听着这阵风实在是心情舒畅。」

让裘拉这个杂音闭嘴后，普莉希拉轻轻闭起眼睛。

从基奴海布各处传来的交锋声，代表企图碎裂瓦解的脚步声。其中格外响亮的声响，是由拉起的吊桥前方传来。

混在强风与巨响之间，夹杂着类似小老鼠拼死顽强抵抗的细微声响。

然而──

「──俗话说穷鼠具毒，被吃掉的究竟会是哪边呢？」

24

由于亚拉基亚参战，面对荷奈特的战况大幅改变。

不只是自己，还必须留意亚拉基亚是否会死亡，频频爆出火花的思考让阿尔脑中即将爆裂。

「最好是有办法和不熟悉习惯的人搭配啦！」

「配合我……」

「我没有那么厉害啦！」

亚拉基亚带着吞食精灵的力量，发挥出特殊能力。

或许该说，「吞食精灵」这种体质实在太过特殊，因此从来没有做过搭配的模拟训练。

虽然四肢着地还会利用牙齿的战法很像野兽，但由尚未成熟的美少女亚拉基亚做出这种举动，有种极为诱人犯罪的猥亵感。

而对手是欠缺双腕的美女，也更加深了此种印象。

「如果是从远处观看，你们两个这种组合真想让我录起来啊……」

「哎呀，这样称赞真是我的荣幸喔。」

剑舞随着微笑袭卷而来，面对这只要被稍微擦过便会连接上死亡的连段起手式，经过十几次再战才总算找出躲避的方式。

在被冲击力道弹开的手腕前方，短剑已经紧紧绑在手上，避免脱手。就算不可靠，武器还是武器。失去这把武器的时候，也就是失去另一只手的时候。

「──唔！多纳！」

因弹开的冲击力道而仰起身，阿尔念出咒语，从地面刺出岩石块。

荷奈特毫不惊险地应对从死角处刺出的攻击，但似乎对战斗中穿插的小技巧感到颇为厌烦。

「这样有点头痛呢。」

发出不屑嗤笑声后，荷奈特将双腕大剑刺进石制地面。直接躲过亚拉基亚全身带着火焰的冲撞，女帝当场将手腕用力旋转──地面便随着崩塌。

立足点顿时变得极度不稳定，阿尔与亚拉基亚两人皆被崩塌卷入。

两人发出短促的惨叫，从吊桥前方落到岛屿最深处，阿尔的身体无计可施地持续坠落，亚拉基亚踩着墙壁跳了过去，接住他的身体并维持姿势平衡。

「嘎啊！得、得救了……」

「没事，不过还没得救，接下来还有得打。」

在掉落的最深处，阿尔与亚拉基亚定睛看着沙尘的另一侧，只见荷奈特劈开笼罩现场的烟雾，怡然自得地现出身影。

她将两把大剑互相摩擦出刺耳声响，笑着说：

「这样就能在更宽敞的地方交手了。阿尔小弟弟，得再努力点才行喔。」

「……只要用小招攻击脚边，你有六成左右的机率会打坏地面。」

「──你说什么？」

听不懂阿尔这句话的意思，荷奈特的笑容顿时僵硬，但阿尔仍然对带着尴尬表情的「剑奴女帝」继续开口。

「只要把地面打坏，小姐会有百分之百的机率会拯救掉下来的我，真是个重义气的家伙──要是在开始剑舞的时候合作展开突击，头就会被打烂。观察情况会被切碎，就算想逃走也会没办法跟小姐好好搭配，死掉的机率大概有七成多。」

「────」

「尝试次数总共七百一十三次，今晚我就被你杀了七百一十三次。」

「────」

「不对，算进一开始竞技场的战斗，是七百九十二次。」

荷奈特保持沉默，静静地听着阿尔语调平淡的说明。

她没有插嘴或觉得很蠢而笑出来，让阿尔感到十分佩服，因为荷奈特知道这并非是威胁或随口妄想。

既然如此──

「──你也看得到纠缠着我的死神吗？」

「……看不到，而且我也听不懂你在说什么，因为我至今还没有杀到阿尔小弟弟半次喔。可是──」

荷奈特打断话语，眼瞳中满溢出杀气与情欲。

「我居然能杀了阿尔小弟弟大概八百次，真是像梦一样。」

荷奈特如此说着，兴奋得面红耳赤，微微采取前倾姿势。

这是荷奈特准备开始绝对致命剑舞的前一阶段。虽然使用剑舞会有各式各样的过程，但目前所有结局都是死亡。

因此不能让她施展剑舞。为了防止她这么做──

「好了，废话该结束啰。阿尔小弟弟，举起武器吧。」

「我不是在说废话。」

「──？」

「──我做的所有事，全部都是有必要地在争取时间。」

听到阿尔说的话，荷奈特狐疑地皱起眉头──效果也跟着出现。

荷奈特发出「啊……？」的沙哑声音，当场跪倒在地，眼睛开始充血变红，呼吸明显变得越来越急促。

然而，越是快速深呼吸，荷奈特的性命便会被加速侵蚀。

俯视着不知发生什么事、眼睛布满血丝，一头雾水的「剑奴女帝」，阿尔实际感觉到让别人跪下并没有半点喜悦感。

即使怀着这种实际感触，为了回报四年前魔兽战受到帮助的恩情，阿尔开始解释原因。

「──是毒。」

「……毒？」

荷奈特以痛苦的表情，对阿尔的话语惊愕地瞪大眼睛。

「这是我以前在漫画中学到的知识……听说能最有效杀人的武器就是毒。」

「毒……？你……是在哪里……？」

「是在这里找来的──就是这个尸体放置场。」

阿尔转过头，对荷奈特表明这个岛屿最深处就是尸体放置场。

先前也对亚拉基亚说过，在造访剑奴孤岛的特殊癖好观众中，有些人会想购买壮烈牺牲的剑奴尸体。举凡特殊出身、华丽外观、或是以密传技法肢解等等，理由可说是五花八门。

而在为了这些原因保管的尸体中，有阿尔想要寻找的尸体。

那就是──

「就是之前和我在生死决斗中被我杀死，使用毒手的那个落魄忍者。直到最后尸体还是充满毒素，我拜托那个小姐把尸体烧掉了。」

「呃──」

「……再用风把毒烟吹过去，然后你就把那些空气吸进去了。」

脸部浮现出血管、瞪大双眼，荷奈特的上半身倒落地面。身体不停颤动的「剑奴女帝」，简直像是在对阿尔与亚拉基亚求饶般。

在这之前让许多人跪倒的「剑奴女帝」，此时立场彷佛完全颠倒。

「毒有效真是让我松了一口气，还有把你引诱到这里的正上方也是。虽然经过很多次的尝试和失败，能奏效真是太好了。」

「等等、啦……这样……对我用毒、真是卑鄙……」

「啊？说卑鄙是在开玩笑吗？在剑奴孤岛活下来不分正道还是邪道，还是说你连这点都不知道吗？『新来的』？」

面对流着血泪咒骂阿尔卑鄙的荷奈特，阿尔不屑地冷冷抛出这句话。

即使身处剑奴孤岛，用实力华丽地制伏一切的荷奈特似乎有所误会──在这里并非强者，而是获胜的人才是胜利者。

不论是燃烧施放毒烟，还是两人包围，只要获胜就是胜利。

「要是放毒没效，我原本以为会更棘手。那就只能把整座岛屿毁掉，或是在吊桥杀了你，能获胜的方法不到十个，而且不知道哪个对你有用。」

「唔──」

视野被血泪沾染模糊，荷奈特对如此低喃的阿尔感到恐惧。

没有尝试过的复数胜利方式，她很清楚这些都所言属实。假设就算没有用毒，阿尔还是有能杀死荷奈特的手段。

荷奈特期望的赌命战斗，不可能带着游玩的心态实现。

在选择与阿尔生死决斗的时间点，就已经失去了这种可能性。

「────」

反刍着这个事实，荷奈特在痛苦中自己找出了理解的方式。

获胜活下来的人才是强者，遵循佛拉基亚流的原则承认自己败北。因此，最后她爬向阿尔。

「阿尔、小弟弟……杀了、我……」

希望由他亲手结束性命，「剑奴女帝」恳求着能够得到适合的死法。面对荷奈特的诉求，阿尔闭起单边眼睛。

接着──

「至少要我杀了你？呃……我是能理解你的心情啦……」

「啊──」

「不知道靠近会不会被你在最后摆一道，我还是在这里等你死掉吧。」

阿尔用嘴巴卸下绑着右手短剑的破布，与荷奈特保持距离。

荷奈特像毛虫般使出最后力气爬行前进，希望阿尔能了结她的性命，却被后退拒绝，让她再度感到绝望。

希望获得相符的最后结局，却无法实现的「剑奴女帝」──看着她先前充满自信的表情染上绝望，阿尔用恢复自由的手抓了抓头。

他一边抓着头，一边对这位不听劝的知己投以怜悯眼神──

「所以我才说了，荷奈特──和我交手不会有任何乐趣。」

25

──在放下吊桥，从对岸涌入援军的时间点，战况就已经分出胜负了。

或许该说，在少女靠着传声管暴露出敌人计划的时候，便可说是大势底定。

既然如此，包含九神将在内的援军工作只剩下剿灭残党。

而实际上，处理的过程也毫无滞碍──

「亚拉基啊，老爷子咱不能接受这种来历不明的年长男人，和你的岁数实在差太多了，反正最后肯定会没办法照顾直接杀掉哩。」

「……你在说什么？」

「嘎哈哈哈！是老头子特有的老顽固啦！不好笑吗？不好笑啊，说的也是啦，老头子说出这种话实在是很不得体啊，真是失敬失敬。」

白发的矮小老人──奥尔巴特•丹克肯说完便开始哈哈大笑。

这位被誉为九神将之「参」的老人的态度，似乎令亚拉基亚感到颇为困惑，但被拉到这位老人面前的阿尔更是摸不着头绪。

由于身心灵都累积了不可小觑的疲累感，老实说他很想直接倒地呼呼大睡。

但如同字面所述，他打死都不能在奥尔巴特面前说出口。毕竟──

「所以是你放下吊桥的吧，真是帮了大忙哩。毕竟要是没有早点解决，咱就会被阁下宰掉了。」

虽然老人展现出莫名滑稽的言行举止，但实力比先前经过那么多次尝试与失败才勉强突破的荷奈特还要更强，阿尔的本能正拼命地如此表达。

在阿尔的人生碰过的人之中，荷奈特肯定是第三或是第四强，但这个排名很快就出现了变动。

「世界真是宽广啊……我还是只要在这个岛上就够了。」

「喂喂，真是没有欲望啊。明明没有年轻到哪里去，在咱眼里大概都是很年轻啦。从这种观点来看，年轻人还是要有点梦想啊。」

「……如果是梦，我已经做过美梦了。」

如此回答奥尔巴特不负责任的鼓励，阿尔看向老人身旁的亚拉基亚，然后朝少女的头伸出手，摸了摸她那沾满尘埃的银发。

亚拉基亚仍然带着不解的表情，接受了阿尔的手掌。

「保护银发美少女的性命──这是我必须付出整个人生去做的事。」

「喂喂，小子你是认真的啊。亚拉基可不会给你，这个梦太夸张啦。」

（插图015）

「不，亲情和异性爱情不一样啦。只有银发我绝对不行。」

阿尔抽回摸着头的手，对奥尔巴特误以为是爱情的发言表示否定。

无视于两人的互动，亚拉基亚望着奥尔巴特的侧脸，开口问道：

「那个……这个丑男要怎么处理？」

「没有恶意的辱骂好伤我的心……！」

「呃……不会怎么办吧？想要奖赏可以用咱的权限直接给他，如果想从这里出去，他的功劳已经很足够哩。」

被斜眼这么一问，阿尔感到有些不舒服，但还是对奥尔巴特点了点头。

这把年纪不是白活的，这位人生经验丰富的老人已经看穿阿尔心中的想法。

「嗯，我什么都不要，我不打算从这里出去。硬要说的话，如果这座岛屿能别消失是最好了。」

「这点应该不用担心哩。帝国不会缺少恶人，这次也出现很多罪犯，减少的量很快就会补上啦。嘎哈哈哈哈！」

奥尔巴特又再度放声大笑，用力拍了拍阿尔的肩膀。

然后他直接转过身，亚拉基亚也准备跟在他身后离开。目送着她那小小背影，原本阿尔准备出声告别。然而……

「──谢谢。」

亚拉基亚停下脚步，只回过头说出这句话。

听到这句道谢，阿尔耸了耸肩。

「You are welcome.」

「……听不懂你在说什么。」

「这个回应真是一百分满分。你看，冷到鸡皮疙瘩都快掉满地了……要好好地活久一点啊。」

亚拉基亚皱起眉，点了点头，才跟在奥尔巴特的身后离开。

目送她离开后，阿尔尽情伸了个懒腰。

剑奴孤岛的骚动总算落幕，包含荷奈特在内的许多熟人皆已身亡。

但听说主犯乌比克行踪不明，而且事情不单单只限于基奴海布，据说是牵连整个帝国暗杀皇帝的其中一个步骤，也是很令人吃惊。

不过皇帝的项上人头并没有落地，于是阿尔姑且认定乌比克已经变成鱼饵，这是没资格介入他人命运的愚蠢败逃垃圾的宿命。

「啊……可是我可能也改变亚拉基亚小姐的命运了。」

最后活下来的亚拉基亚可能会与某人结为连理、生下小孩，只要能靠着繁衍后代建立起全新命脉，说不定世界会迎来巨大变革。

这或许可说是阿尔对世界留下的另一个爪痕。

「要是说出这件事，不知道又会被老师骂成什么样子……」

阿尔抓着头，准备回到剑奴孤岛的深处。

就算没有其他人，或是没有任何人期望，这里就是阿尔的容身之所，能够容许阿尔存在，受忌讳之人们的乐园。

「……无首士兵啊。」

阿尔脑中突然回想起少女隔着传声管传来的话语。

无首士兵是指不假思索参加武装叛变的剑奴们之蔑称，但阿尔也是类似的立场。居然要那群愚者找回自己的脑袋。

「没想到有那么残酷的女人。」

让对方见到真相，不代表能拯救活在虚伪中的人。

这番毫无体贴、呈现血色的宣言，令阿尔舔了舔干渴的嘴唇。

希望自己的人生至少不要与那个高傲声音的主人产生交集。

26

「这次邀约还满有趣的，妾身代替夫君道谢。」

普莉希拉在彭德尔顿宅邸的待客室迎接客人，将茶杯送往嘴边，维持桀骜不驯的态度这么说。

听到这句话，坐在她正面的女豪杰瑟莉娜•德拉克洛伊便缓颊一笑。

「毕竟是我邀请两位，听到您这么说也让我释怀许多。话说夫人，没看到尊夫的身影，敢问中级伯爵人在何处？」

「从那件事之后就卧床躺了好几天，看来是太过刺激了。真是个软弱的家伙。」

「要是迈尔斯他们所言属实，中级伯爵会有那种反应也是无可奈何，总之，两位平安无事真是太好了。」

这种一反「灼热公」著名激进风格的老实态度，让普莉希拉静静眯起眼睛。

如同普莉希拉的预测，不仅「剑奴孤岛」，帝国全土似乎同时出现武装起义与大规模叛乱。但不只是悉数被派遣的九神将迅速镇压，理应是主要目标的帝都并没有出现任何纷乱。

结果仍然无法厘清敌方的真正目标，首领乌比克也从基奴海布消失无踪，让这次事件留下索然无味的不悦感。

「明明才刚继位，皇帝还是一刻都不得闲。或许该说是甘愿背负这些辛劳，能不能顺利跨越这些障碍，值得一看。」

「……甚至连对皇帝阁下都用这种语气，看来夫人确实是个大人物。还有……」

「还有什么？」

「不，这次欠了夫人一个人情，毕竟先前让您碰到了那些危险的情况。」

瑟莉娜耸了耸结实的肩膀，提到普莉希拉在剑奴孤岛顶替自己身份的事。

就客观角度而言，普莉希拉假冒瑟莉娜的名号，看来像是挺身而出保护她不受突如其来的灾难波及。但实际上的原因并非如此正向积极，身为当事者的两人也相当清楚。

她应该也有收到巴尔罗伊与迈尔斯两名同行随从的报告。先不论巴尔罗伊，迈尔斯肯定是将普莉希拉的行动毫不隐瞒地全部呈报。

对于普莉希拉拿出不仅限于替身的成果，瑟莉娜给予高度评价──这不过是类似确认此事的仪式。

「我不喜欢欠别人人情，很想尽量早点偿还。有什么想要的东西吗？只可惜我的部下不能给你……」

「别让妾身说太多次。如果妾身想得到他们，不会特地经过你许可，那些部下肯定会主动投靠妾身。」

「这样啊，那还真是可怕……那么，这份人情只能先欠着了啊。」

「目前暂时是这样吧。」

瑟莉娜看向普莉希拉，那左半边有白色纵向刀伤的脸颊露出笑容。对于这道视线，普莉希拉也闭起自己的左眼直直回看着她。

虽然有年龄差距，但同样身为男性们为之颤抖的女豪杰，仍是心有灵犀。

因此，直觉敏锐的瑟莉娜甚至认为，普莉希拉会在那个时候出面顶替，目的正是为了留下这份人情。

这点是否属实，普莉希拉并没有直接表明。

不过──

「──总有一天会要回这份人情，好好期待那个时候到来吧。」

「真是的，这个人情债还真是沉重啊。」

对于这位少女虽年幼却妖艳的话语，「灼热公」发出咯咯笑声，吐出一口气。

27

「──拿去吧，阿尔迪巴兰。」

「就说别叫我那个名字了。」

徒具形式的手铐解开后，阿尔收下取而代之递来的青龙刀，如此回应。

虽然这是固定形式的对话，但对阿尔如此搭话的对象，并非是剑奴孤岛中难得能敞开心胸的人物，而是惹人厌的看守代替死去的他跟着阿尔。

直到现在都还是会怀念死去的欧兰，说不定会挑战荷奈特，也是出自于怨恨与想报仇的情绪。

「最好是啦……暗杀皇帝失败，剑奴孤岛也只是替换剑奴照常运作，结果世界在巨大洪流中还是一片祥和啊。」

不论是乌比克的煽动、荷奈特的疯狂举动、剑奴们的愿望、亚拉基亚的忠诚、奥尔巴特的狡狯、欧兰的死亡等等，一切都是诸行无常。

即使有再多蝼蚁哭喊，仍无法停止或改变河川流动。

回想着剑奴孤岛的骚动，让阿尔切身体验到这感想。他迈步走向笼罩着观众狂热气氛的竞技场。

今天生死决斗的对手从对面通道缓缓现身，阿尔顿时瞪大双眼。

「是加吉特啊。原来你还活着，我完全以为你已经死了。」

「我也以为你死了，不过由于某种原因活了下来……今天我和你其中一个会死，也是命运使然吧。」

将头发剃掉半边的弯刀剑士，原本听说他率先参加武装叛乱，看来是在某处获得恩赦才活了下来。

而在生死对决中与他如此碰面，总之只能说是世事无常。

「那就别怨恨彼此吧，加吉特。」

「……也是。结果我们到死为止还是剑奴，荷奈特会死，我们也会死。」

「────」

在举起弯刀的加吉特面前，最后那段话让阿尔举起青龙刀做为回应。

每个人都会死、大家都会死，这点绝对无法避免──除了阿尔以外。

「至少目前是这样。」

观众的热烈气氛逐渐高涨，随着铜锣的声响宣告战斗开始。

看着加吉特压低身体冲了过来，阿尔往前跨出步伐。

在头被砍掉之前砍掉对方的头，与平常没有差别。

只不过──

「──要怪就怪星星吧。」

《完》

** 『绯色别离』

1

──自从首度受人搓合与少女成婚的那天开始，日子转眼间流逝而去。

「真是个穷酸的男人。」

「咦、咦咦……！？」

受到某个老交情的地方贵族女性下级伯爵的强烈邀请，裘拉被安排与她的孙女相亲。

对即将五十岁的裘拉•彭德尔顿而言，与婚姻可说是几乎毫无缘分，感觉就像是与自己毫不相关的世界。虽然他当然有身为贵族继承家室的义务感，但他认真思考过只要收养子继承即可。

因此出面参加相亲，再怎么说只是避免对方丢脸。

或许该说，先前已经听说孙女的年龄只有十二岁，与裘拉的年龄差距甚至超越了父女的程度，不想特地让这位将来有前途的少女遭逢不幸。

如果对方有需要，应该也能提供生活援助与介绍出嫁对象。但当裘拉参加相亲后，这种想法便被彻底摧毁了。

「妾身名为普莉希拉──原先是名为普莉丝卡•班奈狄克的佛拉基亚皇族。」

「咦咦！？」

被这位风格不像年纪十二岁的少女震慑，裘拉原先准备的拒绝话语完全无法说出口。当话题继续进行下去，对方突然丢出了震撼弹。

裘拉再怎么落魄还是佛拉基亚贵族，他很快想到普莉丝卡•班奈狄克这个名字。

他理解到这是毫无虚假的事实，以及那位老交情的女性究竟希望裘拉担任什么样的角色。

因此，对方期望裘拉能身为保护幼小少女的庇护人──

「──蠢货，妾身怎么可能要你担任这种角色。」

「咦咦？那为什么要找我……」

「那还用说──听说你家的书库有珍贵古书沉眠。」

并非是对裘拉的为人处事，而是毫不羞愧地表示对持有物品有兴趣，展现出对自身困境毫不在乎的压倒性自我与存在风格。

而裘拉迎娶了这位态度如火焰般的少女──普莉希拉为妻。

到了快五十岁才娶妻原本是很丢脸的事，但这也是裘拉首度体验到如此焦急地希望得到某个人。

2

身为帝国贵族，裘拉•彭德尔顿是个毫无可看之处的凡庸男人。

适者生存、弱肉强食、富国强兵──在普遍存有这类思想的佛拉基亚帝国，只有真挚算是优点的这个男人没有任何地位。

总而言之，裘拉是个不适合身为帝国贵族的男人。

本人也有自觉不适合帝国环境，因此裘拉至今不曾与周遭兴风作浪，甘愿过着在阴暗处的低调生活。

完全无缘挑战足以改变人生的赌注，自己的任务是将家室继承到下一代。由于这种懦弱的思考模式，让他直到这个岁数仍无良缘，也是讽刺。

──但正因为是单身，也有因此诞生的奇迹。

「──只是这样一直盯着妾身，很愉快吗？」

紧盯少女的视线突然被这么指出来，让裘拉瞪大双眼。

面对眼前正在读书的少女──妻子普莉希拉，裘拉毫无自觉地甚至忘了呼吸，对她看傻了眼。

得知这项事实，让裘拉用手指拨弄着自己的浏海。

「不、不好意思，我只是不小心看傻了眼。」

「哼，这样啊。这也是没办法的事，人之所以会陶醉地望着绘画与宝石，是因为里面寄宿着不须理由的真正美丽。真正美丽之物会魅惑他人，是妾身就更不用说了。」

少女发出冷哼声，优雅地将翘起的脚换边，说话语气可谓何等傲慢。但实际上她就是如此美丽，让人不会浮现出想否定她这些话的意思。

「────」

就连在对话时，她那深红眼眸仍丝毫瞥都不瞥裘拉一眼。她翻着大腿上书籍的书页，贪心地咀嚼着看到中间的故事。

仔细想想，见到这个女孩时总是在阅读书籍。

她那满溢智慧的来源，肯定是来自至今阅读过的大量书籍。也就是说，读书对她而言是积蓄知识、为了展翅飞向更高处，也是升华她存在的必要行为。

换言之，自己可以说是见证着她逐渐完美的过程。

陶醉于美丽的事物不需要理由，这便是人类的本质。没错，如果她刚才说的那些话都是事实，这就是裘拉迎娶她为妻且目不转睛的理由。

对她言听计从，或是想听她任性的要求，或许全都是因为这样。

因此──

「普莉希拉，虽然时间不长，但与你渡过的时光很幸福。」

「────」

「我是个胆小的男人，在这之前是渐渐耗损自己与生俱来的幸运活到现在，就像是用小汤匙一样，一点一点地慎重捞起。可是……」

裘拉在此时语塞。

并非是因为还没想到后面的话语，或是一如往常没有自信地支支吾吾之类的消极原因。

理由很简单。

「────」

──因为普莉希拉的眼眸不是看着书，而是看着裘拉。

那如同红玉般美丽的红色眼瞳，正直直盯着裘拉。即使她不发一语，见到那催促着自己继续说下去的视线，让裘拉的喉咙发出吞咽声。

虽然说起来很蠢，但裘拉这时才首度实际感觉到。

自己如此渺小的存在，首度在眼前这位少女──普莉希拉的人生中被分配到登场角色，得到台词。

（插图016）

因此──

「──裘拉•彭德尔顿伯爵！我们要以叛乱国家罪的嫌疑拘捕你！」

即使从屋外传来这锐利的呼喊，他还是对毫不动摇的自己感到自豪。

3

裘拉•彭德尔顿中级伯爵的宅邸，被身穿黄金铠甲的士兵团团包围。

这些从头到脚皆以金色盔甲包覆的士兵，是即使在神圣佛拉基亚帝国中仍有特别立场的「九神将」其中一位的部下。

这些金色士兵分别带着剑、枪、斧、弓之类的武装，展现出强大的团结力──不，其实这是错误的认知。

这群身穿金色铠甲的士兵没有半点配合或团结的意思。不只是擅长武器有所不同，个性也千差万别，要将这群人和平地予以统整简直是不可能的事。

因此，说到有什么特质能够统率这群人，并非是团结一心之类的无形精神，而是更加明确且带有具体性的象征──就是力量。

以纯粹力量统率聚集这群人，这是帝国唯一不变的绝对真理。

「拉尔冯一将，人员配置完毕。」

「嗯，知道了，退下吧。」

收到身旁部下的报告，脸上有伤的壮年男性面色凝重地点了点头。巨大身躯覆盖着魁梧肌肉作为铠甲，外面还穿着黄金铠甲的全副武装。

别说是从头到脚尖，连流着的每一滴血都像是由「战士」的矜持形成，实际上也能感觉到他对这种印象感到荣誉。

哥兹•拉尔冯──这是壮年男子的名字，身为佛拉基亚帝国军人最高位阶的一将，也是位于此种立场的帝国最强阶级其中一人。

以哥兹为首，包围宅邸的这群人笼罩着肃杀气氛。这也是理所当然，因为他们的目的是前来拘捕对帝国犯下叛乱罪的人。视情况预期到可能会发生战斗，可说是因此才会派遣他们前来。

但要是演变成冲突，比起彭德尔顿中级伯爵的私兵，最需要戒备的是他藏匿的目标人物──

「────」

瞬间浮现的担忧让哥兹眯起眼睛，他随即摇了摇头，将推测赶出脑外。

接着，哥兹挺直巨大身躯的背脊，从自己周围部下的队列中走向前，大大吸了一口气。

「──裘拉•彭德尔顿伯爵！我们要以叛乱国家罪的嫌疑拘捕你！」

随着这声大喊，身穿黄金铠甲的士兵们将宅邸正面大门撞破。

嫌疑已经调查属实，不会有任何给予辩解机会的宽容举动。必须迅速拘提当事人，接下来会由适合审问的人负责。

「既然这样！」

并非经由他人，哥兹有自信能完成这个被赋予的责任。

黄金士兵们冲进宅邸后，剧烈交锋声响顿时四处回荡。看来彭德尔顿伯爵也已经在宅邸内暗藏伏兵，战事就此揭开序幕。

「我不打算花太多时间。」

哥兹短短抛出这句话，拿起立在自己身旁的武器。那是具有双手握持的长柄，前端附有巨大圆形铁球，被称为锤矛的武装。

哥兹轻松地扛起将近一百公斤重的武器，巨大身躯一口气飞越过士兵头顶，接着豪爽地挥出锤矛，将阻挡的敌人全部横扫了出去。

「退下！我们是奉陛下敕命行事！要是还有意抵抗，你们也会与裘拉•彭德尔顿伯爵同样视为反贼！」

「────」

他以几乎能够撼动空气的巨大声量，威吓举着武器的中级伯爵士兵。从裘拉的风评来看，他不认为其中会有武艺高强的心腹。

当然，面对身为一将的哥兹•拉尔冯，也不觉得对方会有能够充满气概堂堂挥舞武器的人。

然而──

「──没想到会由拉尔冯一将亲自出马，真头痛。」

穿过正面大门的大厅处，在连接大厅与二楼的大型阶梯上方，有个细瘦人影发出鞋声现出身影，哥兹抬头一望，皱起粗犷眉头。

那是个熟悉的面孔──因为出现在眼前的不是别人，正是他在寻找的人物。

「彭德尔顿伯爵，您主动现身了啊。」

「别看我这样，我好歹还是帝国贵族。交给部下们处理，在后方瑟瑟发抖等待结果，传出去也不好听吧……虽然有可能只是会换个地方发抖就是了。」

这个如此说着话并带着尴尬苦笑的人，正是裘拉•彭德尔顿本人。见到裘拉像这样出现在前线，让哥兹有种颇为出乎意料的印象。

就哥兹所知，裘拉理应是个优柔寡断且不好争端的懦弱人物。竟然会像这样亲自出现在战场上──

「您是改变心意了吗？虽然很想问问让您如此转变的原因……」

「被九神将其中一员这样威胁，让我很想全部说出来。我是个软弱的人……所以得随时逼迫激励自己出面面对。」

裘拉咬着嘴唇，以颤抖的声音如此回应。一名随从的士兵单膝跪在他身旁，恭敬地举着剑，裘拉拿起剑，并缓缓将剑拔出鞘。

裘拉•彭德尔顿是个剑术高手──从来没听过这类传闻。

一看就是个外行人。别说是虚有其表，连模样都装不出来。

「既然您还是选择拿起武器，就别怪我心狠手辣了。」

「那、那也没关系。自从选了这条路，我就知道会有这种结果……也已经与妻子道别过了。」

「……原来如此，那么看来无须多言。」

见到裘拉如此斩钉截铁地断言，笔直望了过来，哥兹深深点了点头。重新用力握紧锤矛后，他发出鼓舞周围士兵歼灭敌人的吼声。

「佛拉基亚帝国九神将之一，哥兹•拉尔冯！奉陛下敕命，前来拔除企图由内撕裂帝国的灾厄根源！」

「为了吾妻，就让我裘拉•彭德尔顿中级伯爵螳臂挡车吧。」

4

「──那道粗喉大嗓，是哥兹•拉尔冯来了啊。为了捉拿妾身一个人，还真是大阵仗，虽然这也是理所当然的。」

这位露出淡淡微笑夸下豪语的少女──普莉希拉正在森林中豪爽地奔驰。

她抓着红色礼服的裙摆，那毫不畏惧恶劣地形狂奔的模样，十分接近在大自然中理所当然地存活的野人。

但扣除掉这身动作，构成她的所有华丽显眼要素都与野人恰好相反，因此有种类似奇迹般的错觉。

「────」

背后被她抛下的宅邸中，夫君与部下们正在激烈交战，裘拉在最后一刻对普莉希拉展露的微笑顿时掠过脑海。

「──真是苦了夫君。」

他是个没有特别可看之处的男人。

既不符合佛拉基亚帝国的信念，无论是身为帝国贵族，或身为男人也都充满缺陷──但在最后的瞬间，他确实是普莉希拉的夫君。

为了妻子着想，他牺牲自己，争取退路与时间。普莉希拉不会做出对他的功劳与努力一笑置之这种没品的举动，也不会让其他人看轻这种行为。

怀着这样的感慨，普莉希拉飞也似地穿过森林──

「──到此为止，公主。」

「────」

突然传来这道声音，让穿梭在森林中的普莉希拉停下脚步。

普莉希拉的深红眼瞳直接看往头上，视线前方的大树上有人影降落到普莉希拉眼前。

那是个只以薄布缠绕身体，暴露出大部分肌肤的少女。

年龄与普莉希拉相差无几，大约十来岁左右。虽然看来健康，但身体还没有成熟到凹凸有致的煽情程度，搭配惺忪的红色眼瞳、覆盖左眼的花纹眼罩、只有一搓红色的银发、以及犬人特有的犬耳，可说是颇具特色的人物。

少女手中握着似乎刚采下的鲜嫩树枝，以红色的单边眼睛看着眼前的普莉希拉，颤抖着嘴唇说：

「……普莉丝卡大人。」

她如此称呼普莉希拉。

「────」

被叫出这个早已舍弃的旧名字，普莉希拉静静吐出一口气。

虽然没有经过很长时光，但还是过了一段时间。即便如此，这位熟悉少女的脸庞、眼瞳颜色与言行举止却没有任何改变，甚至到了不自然的程度。

即使主人理应改变了，她那仍朝普莉希拉投以倚靠的目光便是最好证据。

「不过话说回来，在这种局面竟然是你挡在妾身面前，说来真是讽刺。」

「公主……我是……」

「背叛妾身投靠兄长，最后还像这样得到能亲手缢死妾身的机会。还有什么想辩解的吗？」

「不、不是的！我不是，这个意思……！」

受到普莉希拉冷酷的指责，这位缺乏感情的少女表情大大扭曲。

她露出泫然欲泣的表情，以颤抖的声音说：

「公主……那时候和现在，我都是为了公主……」

「────」

「就连今天也是……我对文森大人主动提议……」

「蠢货，现在不能用这个称呼。兄长已经是佛拉基亚皇帝，如果你也是帝国士兵的一员，就要分清楚轻重。或许该说──」

普莉希拉这时中断话语，将双手挽在胸前，以她那细长的眼眸紧盯着对手，双唇露出挑衅的笑容。

「就真正的意义而言，兄长还没有得到能自称佛拉基亚皇帝的资格。」

「啊……」

「普莉丝卡•班奈狄克已死，参加『选帝之仪』的佛拉基亚皇族已经全被消灭，只剩兄长……妾身的存在会颠覆这个前提。」

要是这件事公诸于世，会成为佛拉基亚帝国创立以来的丑闻。

──这将是理应体现「帝国子民须剽悍强大」信念的皇族，违反弱肉强食定律的证明。

如同文字所述，普莉希拉的存在将会成为撼动帝国的震撼弹。

「普莉丝卡、大人……」

「嗯，这部分也要订正，现在妾身是普莉希拉。考量到夫君最后的牺牲奉献，现在是普莉希拉•彭德尔顿。千万别搞错了，亚拉基亚。」

「普莉、希拉……？」

「这只是类似文字游戏。不论身在何处或发生什么事，妾身都不会有任何改变，对兄长而言应该是很头痛的火种吧。」

普莉希拉闭起单边眼睛，朝眼前名为亚拉基亚的少女发出冷哼。面对普莉希拉的话语，亚拉基亚绷紧那小小肩膀。

「不管是普莉丝卡还是普莉希拉……公主就是公主，跟我一起来吧。文森大人……陛下肯定会听我解释，所以……」

「……不懂你的想法。事到如今才要回去？回去又能怎么样？兄长不会容许妾身存在，如果还是坚持要妾身回去帝都……」

「如果坚持的话？」

「就会将之视为夺走妾身性命的宣言。」

「啊──」

普莉希拉平淡地说出的这句话，令亚拉基亚面露惊愕。

见到同乳母的姊妹这副模样，便能知道文森没有对她说明命令的详细内容，而普莉希拉几乎能够推测出文森的想法。

会在这种状况下，将亚拉基亚派到普莉希拉面前。目的便是──

「兄长会派你过来，算是兄长表现亲爱之情的特有方式。」

「咦……？」

「嗯，就是亲爱之情。兄长还是很爱妾身，妾身也对兄长还有相应的情感，但这件事与妾身的立场不可同日而语──兄长这次绝对必须杀掉妾身，所以……」

「──唔！？」

普莉希拉说到一半突然压低声调，让亚拉基亚瞪大眼睛，她那娇小的身躯直接向后大大纵身一跳。理由相当简单明瞭，便是深红色的挥砍。

这道横向的美丽凶猛斩击，从亚拉基亚颈项先前的所在处准确地划过，头差点就被灼烧砍落地面。

这道挥砍来自不知何时出现在普莉希拉手中的深红宝剑──

「阳剑『佛拉基亚』──」

「要是有两个人能用这把宝剑，对兄长肯定也会有很多问题吧。虽然兄长应该不需要充满霉臭味的权威象征，但没有的话没办法让贝尔斯特兹那群人信服。」

「公主，把剑收起来。这样会……」

「你现在还想劝妾身投降吗？既然这样，妾身也只能靠这道光芒拓展出自己的道路。好了，亚拉基亚，你打算怎么做？」

普莉希拉举着从空中拔出的「阳剑」，确认亚拉基亚的决心。

对手脚尚未发育完全的少女而言，这把宝剑实在太过巨大勇猛，但普莉希拉充满能够自在驾驭它的自信，实际上应该也有能力化为现实。

与普莉希拉对峙的短暂时间，对亚拉基亚而言似乎十分漫长。几经思索后──

「──去吧，公主。」

语毕，亚拉基亚缓缓放下紧紧握着的树枝。见到这番举动，普莉希拉状似出乎意料地闭起单边眼睛。

「喔？你这样应该是违反皇帝敕命吧？」

「可是文森大人……陛下是派我过来。」

「────」

推测着文森命令背后的真正含意，亚拉基亚做出决定。

那或许只是将命令解释成对自己有利的方向，但原先只会忠实听从命令的亚拉基亚确实出现了变化。

见证着这种变化，普莉希拉将握着的阳剑纳回空中，令其消失。

「……我的公主还是公主，可是既然普莉丝卡大人已经死去……这是最后一次，拜托别再做出显眼举动，像是在剑奴孤岛进行广播之类……」

「那也是妾身对兄长展现亲爱之情的特别方式。多亏解决了剑奴孤岛的问题，才能回到帝都进行防守吧。」

到头来，普莉希拉被找出藏身处也只是时间早短的问题。

普莉希拉很不适合低调过着隐世生活，与裘拉度过的时光只是单纯绕路──虽然出乎意料地过得还不算太差。

至少她对于自称普莉希拉•彭德尔顿不会感到抗拒。

「亚拉基亚，辛苦你了──记得想好下次遇到妾身要怀着什么心态。」

「……我不想再遇到公主了。」

「但天底下不会有这么顺利的事，至少妾身是这么认为的。」

普莉希拉只说出这句话便眯起眼睛，同时从森林的另一侧──普莉希拉先前逃走的宅邸方向传来轰隆巨响。

那儿肯定已经以某种方式分出胜负，亚拉基亚的意识瞬间转了过去，便随即转回正面。

然而──

「──公主。」

重新回过头时，普莉希拉的身影已经不在眼前。亚拉基亚的视线四处旁徨游移，但对方并不是个大意到会被发现的人。

她是与亚拉基亚同乳母的姊妹，也是与佛拉基亚皇帝血脉相通的兄妹──

「求求你了……」

切身希望她能尽量到不知名的远处过完自己的人生。

忘记帝国的严苛继承权争夺战，到遥远的地方，以一名少女的身份活下去。

但亚拉基亚知道现实总是无法如愿。

「──绝对不可能。」

普莉丝卡•班奈狄克不可能承认这种生活方式。

总有一天肯定会像今天这样再度见面，到时候，自己面对普莉丝卡或普莉希拉，又会怎么做？

她说了，要自己想好得怀着何种心态。然而──

「……普莉丝卡公主，你这个笨蛋。」

至少她目前只能如此呢喃。

5

──裘拉•彭德尔顿中级伯爵策画的国家反叛计划以失败告终。

身为首谋的中级伯爵被帝国一将哥兹•拉尔冯讨伐，可说是成为了新任皇帝文森•佛拉基亚最初统治的基础。

中级伯爵没有血亲，代代相传的彭德尔顿家就此绝后。在仅仅两个月前，与中级伯爵缔结姻亲关系的年幼妻子自杀，也确定了这件事。

年幼夫人对丈夫的行为感到愧疚而选择自杀──这是后来成为佛拉基亚帝国九神将其中一人的亚拉基亚的证词。

因此没有任何逃亡者。这个剑狼之国没有任何隐忧，也保护了皇帝的盛世。

──然而，日轮仍然会毫无阴霾地持续照耀着大地。

《完》

** 后记

懦弱必须死！没有任何慈悲！各位好！我是长月达平！同时也是鼠色猫！

开头那句话是佛拉基亚帝国的国家口号，本篇故事也是类似这样的内容。一整集佛拉基亚帝国篇，不知道各位有什么感想呢？

这次Ex是王选候选人普莉希拉的过去故事，也是介绍正在进行中的本篇故事第七章「神圣佛拉基亚帝国」这个舞台。

由于国家风格流传着颇为激进的常识，在Re：Zero的世界中应该算是「最不想去的国家」第一名都不为过，至少作者本人完全不想去。

但相较于激进的一面，在竞争意识下培育的佛拉基亚帝国，强盛程度甚至胜过露格尼卡王国。推测国民满意度也是非常高，表示与现任皇帝文森•佛拉基亚的治世广受好评也有关系。

至于现在佛拉基亚变成什么样子，会从Re：Zero本篇第26集开始的第七章开始描述，有兴趣的读者请务必购买阅读。

今后也是会以这种形式，在Ex或短篇集描写菜月昴视点无从阐述的往事或视点，倘若各位不只本篇，也能补充这两个系列的作品，肯定能更加享受Re：Zero的世界！

说着说着篇幅将尽，那么将开始惯例的致谢时间。

首先是I责任编辑，这次也是煞费苦心地思考Ex要插进哪些故事，「以本篇进度只能选这里了！」最后很感谢您如此做出决定，第七章也会继续冲刺。

接着是插画大冢老师，明明也有在这次过往篇就会死掉的角色，竟然一口气设计了九个角色，真的是万分感谢。换了国家也会改变服装款式，风格彻底转变，让本人相当乐在其中！以后的第七章也要继续麻烦您了！

再来是负责设计的草野老师，这次感谢您设计出许多角色齐聚一堂的完美封面。每个角色背后都有一段故事，总是能满足期望真的是帮了大忙。

在月刊Comic Alive负责第四章漫画的花鸡ハルノ老师与相川有老师，将非常困难的章节以浅显易懂的方式再度编排，非常感谢两位。

另外还有MF文库J编辑部的各位、校正人员、各书店的负责人员、宣传部门以及各方人士，这些日子以来承蒙各位照顾。

最重要的是，不仅本篇，甚至还热衷于购买外传的各位读者，在此由衷献上最高谢意，一直以来相当感谢各位。

那么，希望能在描写佛拉基亚帝国的本篇故事中与各位再度相会！

2021年8月《在雷雨交杂的吵杂夜晚中一边吃着冰》