#+title: Re:从零开始的异世界生活 短篇集 7
#+setupfile: ./setup.setup
* 短篇集 7

** 『Lugunican Papers』

台版 转自 天使动漫论坛

天使动漫录入组

图源：真妹控

录入：kid

1

「修堤！修堤！修堤•梅根！！」

一名男子大声叫喊，冲过走廊。

声音高亢，脚步声豪迈，旁人对这些声响只是面面相觑地说：「又开始了。」接着就立刻失去兴趣。

就是日常会发生的理所当然光景，甚至不被拿来当闲嗑牙的话题。

对这些反应不屑一顾的男子，抵达他目标所在的房间。接着以彷佛要撞破墙壁的气势敞开房门──

「──修堤•梅根！你在这吗！」

「唔噎！？咦啊、有有有有、我在我在、我在啦！修堤•梅根还活在这里！」

房门敞开的室内，有一个块头娇小的少年被男子的声音吓到跳起来。

他头上戴着盖住整个头的大圆帽，额前浏海长得藏住了双眼。身上松垮垮的工作服和坚固的旧皮鞋，一看就知道都穿了很久。

这是基于个人的美学或不迎合世间流行的独特展现──皆非如此。原因在于兴趣和财产，尤其是时间极度缺乏。这点从他连自己家都不回，睡在资料杂乱堆积如山的工作室里来看，也十分明显。

少年──修堤•梅根用袖子擦去嘴角的口水，慌慌张张地面向来者。

「摩、摩、摩、摩根总编辑！？请问您为什么会在这里！？」

「没错，正是如此！我是这家『亲龙报文』的总编辑摩根•法兰兹！然后修堤，你到底是我的部下、记者还是手足，哪一个！？」

「当然都是！部下记者手足都是！」

「说得好！但是！你终究只是脚小趾！老是提交这种报导，只会危害到其他趾头，根本成不了大事！」

有着鹰勾鼻的脸孔气得通红，修堤的上司摩根•法兰兹总编辑是「亲龙报文」──露格尼卡王国国内发行的报纸总编，也是个不知妥协为何物的可怕工作狂。

不只身形，声音和态度也很庞大的总编辑，不肯放过王国内发生的任何怪事，日复一日垂涎其变化，完全就是个纯粹的新闻成瘾者。

而这位新闻成瘾的编辑，特地亲自跑来找小小记者修堤，原因只有一个。那就是看过了他写的报导。

「因为这样而特地……谢谢！能获得您的称赞是我的光荣！」

「从刚刚的脉络来看，我是在称赞你吗！？看看我的脸！鹰勾鼻的七成……不，八成都变红了吧。这是我发怒的讯号！」

「总编辑！是十成都是红色的！」

「那就是我被这篇报导，气到比我自以为的还要更生气！」

红光满面的摩根边吼边把手上的纸捆扔向修堤。撞在胸膛上掉到地面的，是修堤熬夜写出来的访谈报导。

那可说是血泪的结晶，却被这样对待。也就是说──

「难道说，要重写！？」

「白痴！是不予采用！再给我倒出一点欲望来！首先，王都的地底出现大量大老鼠，这种内容谁看了会有雀跃的感觉啊！？看到一半还以为会有什么令人惊讶的发展，结果收尾的话语也是糟糕至极！给我说出来听听！」

「──后续发展，请用您的双眼亲自确认吧！」

「闭嘴！不准诱导好奇心旺盛的读者到危险的地底探险！应该要直接联络卫兵去铲除鼠患吧！要是有读者因为挑战大老鼠导致死亡或是生病的话，你要用什么来赔！」

「所以问题出在那种情况下的责任归属吗！？」

「白痴！问题在于购买和阅读『亲龙报文』的人会变少！」

摩根指着捡起地上报纸的修堤鼻梁，破口大骂。

这种话只有新闻成瘾者的价值观才说得出来，但修堤就是喜欢对方这种想法。若要问为什么，在于修堤本身也是新闻成瘾者之一。

因此，这次的报导也是自己挺着胸膛肉搏冲撞出的采访成果就是了。

「以贫民窟为主进行访谈，并仔细观察在王都地底大量繁殖的大老鼠群体的生态，可说是我的倾力之作！您却不予采用！？请问为什么！？」

「这还用问！给我挺直背脊！收下腭！──『亲龙报文』的宗旨是！」

「──唯有打动心灵的报导，才能刊登！」

「这就是一切！」

在肃然立正的修堤面前，摩根口沫横飞地主张。脸上溅了大量口水的修堤，不甘心地咬牙切齿。

其实在采访期间，他也不是没有问自己，这样真的好吗。

「可是，一旦开始却半途而废，心血就白费了……！」

「你这种不轻易放弃的心情我很买帐，但是这次却用到坏的方向去了。讲到往坏的方向发挥，就跟这篇报导的插图给人的印象一样！」

「咦咦！？连插画也不合格吗！？不是画得很棒吗？」

「就是太过用心了！栩栩如生到简直要跳出画面……那群大老鼠！」

他从修堤手中抢过报导，翻到话题中的插画，用力拍打。

映入眼帘的是大批老鼠──写实到令人觉得魄力十足。画功精美逼真，甚至让看的人隐隐觉得闻到老鼠的臭味。

话说回来，因为真的在地底遇到了大老鼠群，当时的记忆与恐惧透过画面让视觉和嗅觉复苏，修堤不禁整个人瘫软。

「呜、呕恶恶恶恶……！」

「不要看自己的报导反而吐了！不过，看了你报导的大批读者也会有相同反应的，懂吗？画这插画的是露露拉拉吧！她人呢！」

「她、她的话，在那边……」

忍住呕吐感，修堤勉强举起手，指向房间角落。

「嗯？」顺着他的指头，摩根凝神看去。结果在堆积如山的资料山脉中，看到了蠢动的身影──专心在挥动画笔的少女。

「哦哦哦哦！？在那里吗，露露拉拉！？」

「……在。」

「你在这种肮脏的房间做什么！？……话说回来，好臭！臭死了！你该不会从地底回来后都没洗澡吧！？呕恶、呕恶恶恶！」

捏着鹰勾鼻的摩根与呕吐感奋战。而少女──露露拉拉只是瞥了他一眼，不发一语。与动都没动的表情不同，她的手继续在腿上的画本上工作。

这是负责绘制「亲龙报文」报导插画的她的职责。

话虽如此──

「既然是可以在画中表现一切的她，那不管多异想天开的事，在她笔下都会充满说服力……根本是暴殄天物！都不觉得浪费吗，修堤！」

「咦！呃，这个嘛，那个……」

「──不准嘻皮笑脸，修堤•梅根！」

话题矛头突然转向，吃惊的修堤忍不住露出讨好的笑容。不过摩根见状后不只鹰勾鼻，连脸都气得通红，然后逼近他。

「我们必须创作出能触动读者感情的作品。而要是不能老实面对自己的感情，又怎能完成这职责呢？对吧！」

「呜……」

「修堤，你到底是为了什么进入『亲龙报文』的！？是为了追着老鼠尾巴跑，让王都的阅报读者皱眉头吗？是吗？」

「并、并不是！」

摩根带着怜悯问道，修堤强力否认。

他甚至忘了被气势压倒一事，瞪着身高有四十公分差距的上司。脑袋火热到像烧起来，原本的憨厚笑容也消失，取而代之的是道出真心。

没错，若要问自己为什么加入「亲龙报文」的话──

「我也想要写出打动人心……可以改变世界的报导！我不是为了折磨怕老鼠的人才当记者的！」

「那你在做什么！浪费露露拉拉的宝贵时间与才能，躺在资料山堆中打盹就能办到吗？」

「这是……这样的话，既然如此……」

被上司讲到无话可说，咬紧牙根的修堤看向废寝忘食埋首作画的搭档。让露露拉拉做了不相衬的工作这件事，被上司说对了。

而最重要的是，修堤本身也觉得，自己做的大老鼠报导并未符合这份热情。

「──」

感受着这股激情沸腾，修堤屏住呼吸。

视野角落，贴在工作房墙壁上的一张报导映入眼帘。那不是修堤写的报导，但却像是纪念莫大奖项般贴在墙上。

如果要问为什么，在于那篇报导的内容，正是修堤所认为的「可以改变世界的报导」的范例。

而要说修堤发自内心渴望想写的报导的话，那就是──

「──王选。」

「什么？」

听到他的低语，摩根一边的眉毛抖了一下。修堤没有错过摩根的声音产生的变化。

为了打动总是最先看到报导的总编辑、「第一位读者」的心。

「王选……我要采访王选候选人！撼动亲龙王国的大事王选，所有国民最关心的候选人，我要亲耳听见她们的说法，亲眼拜见她们的面貌！」

「──」

「如、如何？」

顺着气势选出题材，但摩根的反应却是默不作声，让修堤感到不安。

可能会被骂这是什么有勇无谋的选择，但最后这份不安被沉默思考了半晌的摩根的大笑声给粉碎。

修堤诧异地睁大眼睛，摩根则是用巨大手掌一把抓住他肩膀。

「很好！很好，修堤！就是这个！」

「哇啊啊！肩膀──！」

肩膀被抓到痛的修堤惨叫，但摩根不理睬，反而双眼发亮。

「国民最关心的大事，就是王选！自从宣布开始后已经过了好几个月，虽然一开始蔚为话题，但现在已经逐渐退烧。此时经由我们之手，再度将民众的兴趣导向王选……不赖！不赖呀！」

「谢、谢谢称赞！」

「闭嘴，白痴！你什么都还没干！高兴个屁！」

「是、是的！我这个白痴！」

才刚被捧起就立刻被摔下，修堤的情绪被牵引摆荡。而口沫横飞的摩根竖起食指比向修堤。

「很好！既然决定了就赶快，修堤！不要被其他人抢先！立刻去采访王选候选人，想办法写成报导吧！老鼠的报导我这边会帮你先拿掉！」

说完这些话，摩根就一把抓起大老鼠报导，冲出房间了。掀起的风不但卷起室内的资料文件，还摇动修堤的长浏海。

但是在暴风雨离去的室内，修堤满怀热血，握紧拳头。

虽然只是顺势脱口而出，不过胸口的这份热情是货真价实。

「上吧，做番大事业！我要改变世界！露露拉拉，你也会忙起来喔！」

「……嗯。」

「咦？我？」

鼻子朝天喷气、意气风发时，不知何时站到身旁的露露拉拉撕下画本的一张纸递给他。

──上头画着情绪亢奋到流鼻血的修堤。

「唉，这种事好歹用嘴巴讲吧！！」

修堤把布塞进鼻子里，小心翼翼地折起画纸，收进口袋内。接着拉出被文件埋起来的采访工具，准备外出进行采访。

「大老鼠之后是王选候选人……两边都是不能走普通方法采访的对象，都只能亲自走一趟才能成功采访！走吧，露露拉拉！」

「……小心。」

「什么路上小心，你也要去喔！？」

露露拉拉缩起身子，一副要窝在屋内的模样。修堤背起她，连同她的画具一并抱起，以奇怪的样貌离开了「亲龙报文」总公司。

「……懒。」

「别发懒啊！想想看，候选人个个都是美女，你的创作欲望一定也会泉涌而出！还会盛大喷发的！」

死命唤起有气无力的搭档的斗志，修堤的冒险开始了。

尽管搭档的脚步沉重、意兴阑珊，但修堤的双眼闪耀生辉。今天十分适合开始动笔，写下足以推动世界的报导。

「看到了，露露拉拉……蓝天在祝福我们的前途！」

「……是阴天。」

「用心眼去看啦！」

2

「亲龙报文」在露格尼卡王国，算是小有名气的报纸。

报纸上要传达给读者的，是发生在露格尼卡国内、可以带动喜怒哀乐情绪的事件──可以用来妆点平静生活的好事，或是谁在某个地方失去性命这种难过悲伤的事，种类非常多。

但是，要说能刺激怎样的情绪的话，「亲龙报文」有着绝对不会退让的原则。那就是──

「唯有打动心灵的报导，才能刊登！这是我们公司的宗旨呀，露露拉拉。」

「……噗噜噜噜。」

「不要用水发出这种声音，听我讲话好吗！？还有，我知道这是你的习惯，可是待会在采访的时候绝对不可以这样喔，懂吗！？」

修堤高举拳头、斗志昂扬，面前的露露拉拉脸上却毫无干劲。

离开总公司的两人，正在王都的一间餐厅里磋商采访计划。不过拟定计划和说明都是修堤的工作，露露拉拉只会在旁边帮腔。

「接下来，我们将要去拜访参加王选的候选人。露露拉拉，就算是你，也应该知道王选吧？」

「……亡藓？」

「一脸不知道的样子！真可怕！明明投身新闻业，却对世间一切毫不关心，这种态度叫人害怕！还开始画下我害怕的脸的这种反应也很可怕！」

露露拉拉迅速地在画本上画出脸色苍白的修堤。

（插图007）

如方才所说，露露拉拉是靠绘制报纸上的报导画作维生的「报纸绘师」。其画工是天才等级，但是个对画画以外的任何事物都不在乎的怪人。

因此对修堤来说，巧妙引导长期合伙的麻烦搭档有其必要性。

「我要跟你这位重要的搭档，讲述一下接下来要采访的对象。不过终究是为了整理我的思绪而做的说明，你就这样想就好了。」

「……好。」

总之搭档附和了，于是修堤轻声咳嗽，接着朝她开始说明王选与参与者。

「首先是王选，是距今约半年前，由王城宣告决定下任国王的仪式。三年后，要从被选中的五名候选人之中选出国王……因此为了成为国王，目前五人都在互相竞争。」

国王及其后代全都因不明疾病而逝世，可说是露格尼卡王国近年来动摇国本的重大灾厄之一。

结果，王国就在没有统治者的情况下，由贤人会代为治理国家，但是这样的状态无法长久。因此为了解决这状况，就有了──

「──王位选拔战，简称王选。王选候选人有五位：库珥修•卡尔斯腾公爵、安娜塔西亚•合辛商会会长、普莉希拉•跋利耶尔男爵夫人、菲鲁特大人与爱蜜莉雅大人。」

「……也太多？」

「不，倒是不多啦。……毕竟在决战之前，候选人的人数有可能会减少。」

露露拉拉歪头，似乎不懂修堤这话的意思。

在这场决定下届国王的争战中，假如只有候选人拥有必要的资质，那么包含暗杀在内的手段，各种明争暗斗都可以想像得出来。

「如果只有普普通通的觉悟，候选人是不敢报名王选的。被选上的五位候选人，一定全都做了不小的心理准备。」

既然是要争夺空缺的王位，那么这些人想必都极具野心吧。

「而且全都是女性……这种情况下，该称她们为女杰吧。被称为『战乙女』的库珥修大人，在卡拉拉基都市国家发迹致富的安娜塔西亚大人……菲鲁特大人听说掌控着贫民窟，最重要的是还能够使唤『剑圣』。」

「……剑圣是，『骑士中的骑士』？」

「没错……话说回来，之前你有画过骑士莱因哈鲁特呢。」

露露拉拉的反应，让修堤想起以前她画过的一张画。

不过那次不是采访，只是偶然遇到放假在王都散步的「剑圣」，而对方爽快地答应露露拉拉想画他的要求。

事实上露露拉拉也奋笔疾书，完成一张精美画作。

那张画也成了修堤放在工作室里的精心收藏。

先不说这件事了──

「既然能让那位骑士莱因哈鲁特宣示效忠，那菲鲁特大人想必是了不起的人物。然后是……」

「……是？」

「爱蜜莉雅、大人……」

只是要念出下一位候选人的名字，修堤就觉得全身颤栗。

面部血气尽失，双肩直发抖的样子，让露露拉拉面露不解。要是知道原因的话，想必她也会跟着害怕的。

王选候选人之一爱蜜莉雅──拥有银发和蓝紫双眼的半妖精，特征与过去把世界逼到毁灭边缘的「嫉妒魔女」一样。

据说具备宛如魔性容貌的她，身边有一只身上散发的冷气可以冻结世间万物的凶猛精灵。另外，虽然尚未确认，但有人指出她不仅是导致王国北部领土化为永冻土的始作俑者，还会因为好玩就降下暴风雪破坏当地人民生活，并乐在其中。

当然，她并非「嫉妒魔女」本人。──但却是危险到让人谣传「嫉妒魔女」重现的人物。

──在自己之前，也曾有其他记者想要写出相同题材的报导吧。

但之所以都没能达成，最大的原因就出在这位「爱蜜莉雅」身上。

既然标榜要采访王选候选人，那当然就要访谈过五人，企划才算成立。可是，没有人敢去采访爱蜜莉雅。

修堤也认为，本次采访最大的障碍，就是对爱蜜莉雅的恐惧。

「──」

但是，看到修堤害怕的样子后，露露拉拉就挥笔在画本上作画。

画出现状并不能成为力量，完全不担心自己这点也让人难掩惊讶，不过却成了让修堤回神的契机。

「要改变、世界……」

想起自己对摩根总编辑发下的豪语，修堤咬紧牙根。

不能让那句话变成谎言。要咬紧的不只牙根，还有自己的梦想。

「现在不是害怕的时候。我要做，露露拉拉。我会做好我的工作！」

「……另一个人，是？」

「唔噎？啊，对喔，对了对了，还有一个人。」

才刚下定决心，露露拉拉就递给他刚画好的图。看着画中脸色苍白的自己，修堤苦笑，接着慎重地将图画纸收进包包。

「最后一人，就是跋利耶尔男爵夫人普莉希拉大人，婚姻反覆遭逢不幸到被人称为『染血新娘』。她年轻貌美，结婚数次，但每次丈夫都先她一步死去……是个充满悲剧的女性。」

「……悲剧。」

「在其领地内的评价很高，似乎还被仰慕到被尊称为『太阳公主』。一定是个会积极露出笑容面对身旁的人，给予温暖魅力的人物吧。」

从收集到的评语来判断，修堤个人最想支持这位个人境遇很差的普莉希拉•跋利耶尔。

尽管接连死了丈夫，却不对天降的不讲理低头，反而还发光发热。

这一定可以说是能感动众人的英雄传或发迹故事吧。

「哎哟哟，不可以不可以。说到底，我们必须对候选人一视平等。不然的话，对第一个接受采访的对象很失礼。」

「……第一个？」

「──库珥修•卡尔斯腾公爵。」

说完，有预感将会是个正式采访的修堤忍不住抖擞了一下。

既是王国重要人物，且被认为是目前王选里头最有希望登上王位的候选人。

「老实说，如果扣掉心情上的问题，我认为这是最难应付的敌人。首先，根本就不觉得对方会接受采访邀约。」

毕竟是有爵位，地位又是王国首屈一指的特殊人物。

以平民观点出发，目的是让大众乐意阅读，这种报业的采访要求被拒于门外是再正常不过。虽然如果被拒绝，自己打算申请采访几十次、几百次，直到对方输给自己的毅力勉为其难答应，但──

「……厉害人物？」

「怎么说呢……库珥修大人武力高强不输男性，并以此闻名，而且还逼迫尚未到退休年龄的父亲退位，自己坐上当家位置。可说是个野心勃勃的人。」

不然的话，就无法胜任被称为「战乙女」这头衔的女公爵之职了。

会接受这次的采访，想必也是出于她个人的盘算吧。修堤被利用了。──但，自己可没打算乖乖被利用就了事。

「就算对手是身经百战、贵族中的贵族……我也不会被撂倒的。」

首先要把第一个参选的候选人库珥修•卡尔斯腾不为人知的面貌，公诸于世。

就算第一个访谈也可能是自己最后一次的采访，修堤•梅根也会战斗到最后。──他做好这悲壮的觉悟。

3

但是，以结果来说，这悲壮觉悟以杞人忧天告终。

库珥修•卡尔斯腾公爵接受「亲龙报文」的采访，目的不在于敌视进来的报章业者，更不是要给业界一个下马威。

不但不是，反而──

「这样啊。修堤先生和露露拉拉小姐在『亲龙报文』工作两年了……两位还这么年轻，工作态度却这么可敬呢。」

「哪、哪里，您言重了！这没什么大不了的啦，啊哈哈哈……」

没想到会被称赞的修堤面红耳赤，把帽子压得更低。

「哪儿的话，您太谦虚了。」看着修堤并手掩嘴巴微笑的，是气质文雅，高尚的举止与她惊人相应的绿发美女。

她泰然自若的一举一动都让人看呆，不过发现自己被现场的──不，是被对方的气场给吞没的修堤，内心慌张，心想得做些什么才行。

修堤和露露拉拉被迎入位在王都贵族街的卡尔斯腾家别墅。被带到宽敞无比的接待室，屁股坐在柔软舒适的沙发上，忍不住就露出一脸憨样。

面前的美女可说是天女也不为过，恍惚心境彷佛是梦境成真。

没错，天女。这种形容再适合她不过。丰盈的绿色长发流泄在背后，充满女人味的起伏肢体包裹在设计高雅的礼服中，她──库珥修•卡尔斯腾公爵的美，足以深深烙印在修堤脑中。

「唔～～」

「请问，您身旁的露露拉拉小姐不要紧吧？」

「能、能承蒙您担忧，实属光荣备至。不过，她平常就是这样子，还请睁一只眼闭一只眼……！」

库珥修歪头担心地问，这让修堤无法保持平常心。不过，根本比不上身旁呼吸急促振笔疾书的露露拉拉。

露露拉拉本来就是个忠实于自己的感受的人。说得白话点，就是当她发现好题材时便无人能够制止。修堤也没打算阻止。

毕竟，这个时候的露露拉拉产出的画作，张张都是杰作。

「……请。」

「啊，我可以收下吗？这是……我吗？」

露露拉拉畏畏缩缩递出画，接过的库珥修看了睁大眼睛。

那是已经熟悉露露拉拉画作的修堤，都认为堪称完美的佳作。真实描绘出眼前所见的露露拉拉，毫不浪费地发挥了自身画功。

「真想挂在我房间做装饰……」

忍不住就脱口道出真实的感想。

「咦？」当然，一听到他的低喃，库珥修忍不住反问。必须粉饰这句话，修堤连忙想要开口……

「──嗯，嗯，能懂能懂。画得这么漂亮，连菲莉酱都想要装饰在房间里了喵。」

「对吧，就是这样！……既然懂，那就没问题了吧！？」

欲望被肯定而忍不住赞成的修堤语毕，感到惊愕。结果道出恶魔语言的当事人「喵呼呼」的笑，然后坐到库珥修旁边。

就这样加入现场的人物，也是个外表好看得可怕的人物。

假如适合库珥修的形容词是「美丽」，那这号人物适合的正是「楚楚可怜」。动作和视线全都有着洗练的可爱，令人离不开目光。

但是不要小看这边，自己可是写报导的记者。这位少女──不，是看起来像少女的人物，自己老早就调查过是谁了。

「您、您是骑士菲利克斯•阿盖尔殿下，对吧？」

「是没错，可是菲莉酱讨厌那种称呼。要叫的话，就叫人家『菲莉丝』喵。也欢迎直接叫菲莉酱哟。」

「啊呜、这个……菲莉丝殿下，容我这样称呼您。」

「喵呼呼，真～可～爱～」

手指贴唇嫣然微笑的菲利克斯──不，菲莉丝。差点被他那带着恶作剧的表情与举止给蛊惑，不过他可是货真价实的男性。

王选候选人库珥修•卡尔斯腾，及其首席骑士菲莉丝。

面前有着主从关系的两人，正是这次的采访对象。

「菲莉丝，不要太欺负这两位记者了。」

「好～对不起喵，库珥修大人。不过，画得真的很棒喵。……库珥修大人，您就这么仔细地展现自己给这孩子看吗？」

「被你这么一说，总觉得好像做了丢脸的事，让人在意……不过没有。一定是这位小姐的观察力过人吧。」

谴责菲莉丝的态度，库珥修同时用琥珀色双眼看向露露拉拉。

顿时，被那双瞳孔的美给吸引的露露拉拉，开始着手画第二张画。不可以输给她，于是修堤小声咳嗽清嗓。

「那、那么，既然尊贵的王选候选人库珥修大人，和您的首席骑士菲莉丝殿下都到了，可以开始进行访谈了吗？」

「可以。此次两位刻意前来采访我，我很荣幸。虽然不知能否回应期待，但还请多多关照。」

修堤的发问用字遣词尽可能审慎，库珥修则是端庄行礼。

美女讲话也这么美丽有品，修堤佩服的同时，超越佩服的惶恐袭向全身，使他发出「哦呜呼」的奇怪声音。

「真是，库珥修大人客气到吓到客人啦～。摆点架子吧。」

「摆架子……很难呢。意思是要自然就好吗？」

「嗯～有点不一样喵～不过就当那样也不错喵。记者先生，要是不稳重一点的话，这边会很伤脑筋喵。」

（插图008）

「明、明白了……」

库珥修和修堤两人，都被菲莉丝讲到只能点头。

看样子，在场最有实权的人是菲莉丝。另外，最自由的露露拉拉，似乎决定第二张画要连同主仆一并画入。

「请问，作为王选候选人呼声最高的库珥修大人，自王选开始已经过了几个月，能否让我们知道您现在的感触或感受是什么呢？」

「应对再自然一些也没关系喔？」

「这、这已经是我目前的全力了……」

库珥修表现得贤淑端庄。修堤之所以招架不住，当然一方面是她的美貌，但还有她的言行举止跟先前收集的情报有龃龉这点。

她是被称为「战乙女」的习武之人，甚至逼迫父亲退位的野心女公爵。然而这样的评价与眼前的美女并不一致。跟传闻一样的就只有美丽的外貌而已。

而在内心发生冲突的修堤面前，库珥修的视线略微下垂。

「呼声最高，这评语实在太过高估了。至少，现在的我还有许多要学习的事，没资格坐上国王的位置。」

「库珥修大人！？」

「咦咦！？您这话是，咦咦！？难道，您打算退出王选吗！？」

听到库珥修「没自信」、「自己没资格」这样的自我评价，修堤不禁怀疑起自己的耳朵。菲莉丝也大为震惊。

才刚采访第一位王选候选人就已经出现出人意料之事。在王选最占优势的候选人库珥修•卡尔斯腾向记者坦白自己的内心──

「──不，请不要误会。」

不过，库珥修凛然地打住记者和下属的混乱。而修堤也为对方一发声，自己内心立刻心如止水一般平静感到讶异。

这代表自己被面前女性所散发的气质给魅惑到整颗心都受她牵引，忍不住倒抽一口气。

「我还有许多不足，仍在学习中……若要论胜过其他候选人之处，顶多只有家世吧。但是光凭这点终究不能彻底胜任国王这职责。因此，才要继续努力。」

「努力……」

「不成熟的此身，必须拥有担起国王这重责大任的器量。若还是不足，就须拜借身边最亲近的随从和臣下之力。」

「──。库珥修、大人。」

微笑这么说的库珥修，轻轻把手放在身旁的菲莉丝肩头上。感受到触感的菲莉丝面露感激，湿了眼眶，回望着主人。

这么优美的主从关系，让修堤也忍不住眼角一热。

「……我认为这种想法很棒。那、那么，改变一下话题，能否让我询问打倒白鲸那件事呢？这个丰功伟业，据说是和其他王选候选人合作才办到的。」

「嗯，关于这件事……」

「──说到这个喵，少不了杀死白鲸的最大功臣！那位鼎鼎大名的威尔海姆•范•阿斯特雷亚就在我们这里喵！」

眼神闪耀光芒的菲莉丝放声盖过库珥修的回答。虽然被这气势给吓到了，但那确实也是修堤想问的人。

「没错，我也想访问本人！那在『剑鬼恋歌』当中描述的两位主角，与白鲸有匪浅的渊源……」

「正是如此！你们等一下！人家马上带威廉爷过来──！」

说完，菲莉丝就跳过茶几冲到房间外去了。能够直接访问那位「剑鬼」，修堤也忍不住紧张起来。

「呵呵。」见状，库珥修笑出声来。

「啊，不是的，那个，对不起！我知道这次主要是来采访库珥修大人的！」

「没关系，我不在意。访问我的随从和臣子，就跟访问我是一样的。而且我认为，威尔海姆的故事必须广为流传。」

「您、您能这么说真是太感激了……啊，那么，还有一个问题。」

厚脸皮地享受对方的恩赐，同时他询问库珥修。

刚好菲莉丝不在，能够直接询问库珥修的意见。王选开始后已过数个月，这段期间发生了许多令王国混乱的事──

「目前，库珥修大人最关注哪个阵营？」

「这个嘛……」

听到这问题，库珥修有一瞬间中断了话语。不过，思索和犹豫也就只有一瞬间，她心中似乎立刻给出了答案。

不过，明明是在讲劲敌，她却始终保持微笑。

然后──

「──我认为爱蜜莉雅大人的阵营，是最应该关注的吧。」

她这么回答。

4

「奇怪……跟之前的评论完全不同，访谈过程从头到尾都很和睦……」

结束采访，离开卡尔斯腾家别墅时，修堤疲惫地这么说。

疲惫的原因不是出在身体，而是精神方面的消耗。当初的不安虽是杞人忧天，然而提心吊胆的惶恐之处还是比想像中要多。

不过虽然身心俱疲，却得到了相应的收获，这点还是不错的。

「只是没想到，威尔海姆殿下的故事会拖得这么久……」

面对想要知道白鲸讨伐战故事的修堤，得到主子许可的威尔海姆滔滔不绝。不过讲的话大部分都是他妻子──生前败给白鲸而殒命的前任「剑圣」跟他之间的爱情故事，在这点上实属意外。

「唔～～」

回到平民区，修堤在广场的喷水池旁小憩，身旁的露露拉拉则是迅猛舞动画笔，亢奋到脸都红了，气势高昂到都快用光新买的画本了。

看样子，库珥修和菲莉丝的存在，给予了她相当不错的影响。

「不过，我懂。……果然亲自的所见所闻，跟传闻完全不同。」

沉迷剑术、胜过男人的野心女公爵──以这么极端的评语来分析库珥修的话，照理来说，她应该会是个能力符合家世，却以鼻子看人的高傲贵族。

但实际上，库珥修的姿态柔软，时时意识到自己的不足之处却又不减上进心，是能够为对方着想的理想人物。

「假如要选的话，我希望是那位大人当国王……」

「……私心？」

「咦啊！？不、不是不是，完全不是！记者要公平！报导要平等！」

自言自语被听到还被反问，修堤连忙否认。不过露露拉拉无视他的慌张，毫不在意地继续埋首作画。

对此修堤只能叹气，重新戴好帽子。

「总而言之，来归结采访的内容吧。从库珥修大人盛传于世的风评而生的误解……消弭这种传闻与现实之间的鸿沟，也是我们的责任。」

「……嗯。」

用手指搓着人中的修堤这样主张，露露拉拉则把画递给他。「哦。」接过来一看，修堤讶异抬眉。

不愧是露露拉拉。这个天才报纸绘师，画出了想让读者看的东西。

──是美丽的主从相依偎，牵着手的画面。

「嗯，这张画得好。真有你的，露露拉拉！」

「……两个漂亮女生在一起，你看得很开心？」

「我没用那种眼光去看，再说菲莉丝殿下可是男性喔！？」

被她那彷佛看穿什么的目光凝视，记者魂被扭曲的修堤感到无法释怀，不过对于采访内容和这张出色的画作没有任何不满。──可是，目前才采访了一个人。

「接下来还要继续花心思呢……特别是下一个采访对象，也是不容小觑。」

「……不腻吗？」

「不要觉得厌烦！是真的啦！……毕竟，下一个采访对象不是本国人，而是来自国外的候选人。」

「……国外。」听了修堤这样讲，露露拉拉才一副第一次听说的表情。照理而言之前有说明过，所以她应该不是第一次听过，总之就先算了。

毕竟，这次一定也要让露露拉拉有危机意识。

「下一位采访对象安娜塔西亚•合辛大人，是在卡拉拉基都市国家拥有庞大力量的合辛商会的会长。在卡拉拉基可说是呼风唤雨……这样的人特地跨国跑来争夺露格尼卡王国的王位……有没有闻到什么？」

「……我洗过澡了。」

「不是说你身上的气味！是说，假如你身上有味道，那在库珥修大人那边就万分失礼了！」

说到底，打从一开始就不该问嗅觉可能因颜料而失灵的露露拉拉这种话。对可疑之事的嗅觉，是修堤应该磨练的感官。

这就是搭档之间的分工合作，修堤负责的职责。

「在这之前，要说来自外国的干涉的话，都是南方的佛拉基亚帝国。事实上，在王选开始之前，也有传出贤人会的代表私底下与帝国订定不可侵犯条约。」

一直在提防的南方帝国，是任何人都会想到的威胁。因此特地跑来这里成为王选候选人的安娜塔西亚，搞不好是来自西方的刺客、预料之外的威胁。

然后是──

「声明支持安娜塔西亚大人的，是『最优秀骑士』由里乌斯•尤克历乌斯。从他身上也传来了可疑的气味。」

「……那个人，也没洗澡？」

「被称为『最优秀』的人都没洗澡的话，会让人大失所望吧！就算他表里不一，我也希望他会洗澡！」

当然，最好他是表里一致的人。

但是，身为在骑士团内备受信任、前途无量的可造之材，是基于什么目的想把在国外有庞大实力的人推上王位，却无人知晓。

尤克历乌斯家代代都是骑士，在露格尼卡王国从未有家族被轻视过的纪录。既然如此，可以想到的可能性就是──

「骑士由里乌斯是个野心大到无可救药的人，或是卖国贼……」

「……两个。」

「是的话会很让人讨厌的，希望是其中一个就好。……不管怎样，都是在策划什么吧。就用这次的采访来抓住线索。」

用力握拳，修堤下了新的决定。

透过亲身采访库珥修，现在他心中的自信与类似崭新使命感的东西已然觉醒。那就是：详述王选的真相。

世人对库珥修的风评，跟她真实的为人有极大落差，不在话下。从这来看，就算想决定下任国王，也难以制定准则。

既然如此，就由「亲龙报文」来拟定难以动摇的准则吧。

「──不，不是由『亲龙报文』，而是我们。」

「……好大的口气。」

「正是如此！我们已经跑起来了。所以说，在抵达某处之前只能继续跑。给它用力做下去。所以……」

修堤从采访用包包拿出新的画本，交给露露拉拉。她立刻用力呼吸、双眼发亮地收下。

露露拉拉干劲十足，修堤也觉得使命感满满。

乘着这股气势──

「──这跟安娜塔西亚大人有何企图、隐瞒着怎样的计划没有关系。我不会被那些动听的甜言蜜语所骗，誓要问出她的真心话！」

5

「伦家的目的？想也知道是得到露格尼卡王国呗？」

「呜噎耶啊！？」

听到双手支在桌上托着脸颊的女性这么说，修堤目瞪口呆。

对方是个气质沉稳又和蔼的女性。促狭的表情令人联想到高贵的品种猫，搭配刚刚的话，正面击碎修堤的决心。

抱着必死决心要揭发对手肚子里藏的葫芦膏药，结果居然被满脸笑容给肯定。

「怎么怎么？这么夸张的反应。岂不是会让人开心咩。」

「安娜塔西亚大人，戏弄人请适可而止。方才的发言有些不妥。」

「唉呀呀，被念咧。伦家的骑士大人很一板正经滴。」

说完吐舌头的，是可以套用「楚楚可怜」这说法的女性──大商会合辛商会的年轻会长安娜塔西亚•合辛本人。

长长的浅紫波浪发，即便身在温暖的阳光中依然穿着毛茸茸的毛皮大衣。个头不高，外表给人弱不禁风的印象，但浅葱色眼珠透露着强烈的反骨心，让人忍不住就被她的棘手人性给吸引。

使人无法移开目光的魅力，一方面是因为她那楚楚可怜的容貌。安娜塔西亚的美貌也不逊于库珥修，但修堤对于她中选为候选人的原因抱持着疑问。

总不可能用容貌作为筛选条件吧。

「嗯？怎么咧，盯着伦家的脸在想事情？有什么想知道的尽管问呗。」

「不是啦，因为安娜塔西亚大人和库珥修大人都很美，所以不知道怎么反应。」

「唉呀呀。」

安娜塔西亚手掩嘴巴、睁大眼睛。「呜啊。」这样的反应让修堤再次诅咒自己老是管不好嘴巴的坏习惯。

但是听了他自认失言的话后，安娜塔西亚却笑了，还朝坐在旁边的人点头。

「原来如此，我也持相同意见。安娜塔西亚大人不仅拥有优异的知性与商业才干，也是拥有极大女性魅力的人物。」

「那么正经八百地回答，会让好不容易缓和场子的记者先生的体贴给白费咧。喏？」

「嗯……那真是抱歉。我应该要推敲到才对。」

「咦！？啊，那个，我、我这边才是觉得让人搞不清楚，真的很抱歉！哈哈哈……」

顺着对话走向被访谈对象道歉，修堤边摸帽子边苦笑带过。

除此之外，自己究竟还能做什么？──在面对第二对王选候选人主从：安娜塔西亚，和她的骑士由里乌斯•尤克历乌斯的这个当下。

──王选候选人的采访行程，进展比当初料想的还要顺利。

被神秘面纱给包覆的候选人，一定会讨厌这种采访。但彷佛在嘲笑修堤这种先入为主的想法，采访的申请都被爽快答应了。

当然，此外还有三个人。之后跟她们的接洽很有可能遇到难关。

「现在，必须尽可能活用这份幸运……！」

幸运的是，以商谈为目的来到王都的安娜塔西亚答应采访，并且也让首席骑士由里乌斯同席。这对修堤来说可是额手称庆的状态。

另外，在两人面前急促呼吸，对着画本猛画的露露拉拉，一定也跟自己有相同看法。

「不过话说回来，在这么开放的地方采访……真的可以吗？」

「嗯～是很想在伦家的店里接待你们，可是那样子记者先生会紧张呗？要是被认为伦家威胁你写些对伦家有利的报导的话，那可就讨厌咧。」

微笑的安娜塔西亚，边说边看向王都的街道。

眼前是人来人往的街景，一行人位在面向大马路的咖啡厅露天座位。会在这么多人的地方进行访谈，是安娜塔西亚的要求。

这么做要表达的是，她并未强迫修堤写出不想写的报导。

刻意在会被许多人看到的地方接受采访，是坚持走在正途上的库珥修所不具备的另一种强大。从这儿可以感受到安娜塔西亚不好对付，以及为人有多么精明。

「可是，刚刚说的『得到王国』，这种说法的真正用意是……」

「伦家的真心话。并未有所隐瞒，在其他候选人和贤人会面前也都说过哟？……还有，要是问一些激进的问题，那孩子会看过来吗？」

「那孩子……啊，是说露露拉拉吗！？」

安娜塔西亚的视线尽头，是没礼貌地把脚放在椅子上的露露拉拉，无视访谈进行、一个劲地挥动画笔。

话虽如此，这是露露拉拉的最佳工作姿势。

「其实这个样子是露露拉拉最能发挥工作效能的状态……假如不会造成您的不快，那请让她维持这样……」

「伦家很不快。」

「露露拉拉！马上跟我一起道歉！快道歉……脖子好硬！！」

「──要是人家这么说了，你会怎样咧？本来想接着这么说滴，可是你接话速度快到伦家来不及插嘴。」

修堤立刻抓住露露拉拉的头想要让她低头认错，却被非比寻常的力道给阻挡而失败。看到他这么焦急，安娜塔西亚苦笑。

不管怎样──

「不过，她的专注力真了不得。修堤殿下，我知道她在工作，但能否让我稍微拜见一下呢？其实舍弟也会画画。」

「令弟……啊，只要不跟她说话，露露拉拉不会在意的。」

「果然是因为说话的话，会扰乱她的专注力吧？」

「不，是跟她说话她也不会答理，只是自讨没趣。」

虽说在工作上是必要的，可是若不只几个小时，被连续无视几天的话，内心也是会很难受的。

「了解了。」可能将修堤的答覆视为露露拉拉的敬业态度吧，由里乌斯说完就绕到露露拉拉身后，不发一语开始参观她工作的样子。

是纯粹的好奇心吗？还是担心主子安娜塔西亚有可能被人贬低，所以才进行牵制呢？「原来如此……」说不定他不时发出的赞叹之声，也都是为了让自己大意的演技。

「想像力很丰富的孩子捏。不如转行当作家比较好呗？」

「您说什么呢。我是记者，把所见所闻如实传达出去就是我的工作。哪适合当那种把天马行空的想像写出来的作家。」

「是咩？算咧，既然你本人这么说，那就这样呗。」

别有含意的回答，让修堤感觉举手投足都被玩弄。这样下去会中她的圈套，看来访谈不能慢慢来了。

从这点来看，说要「得到王国」，也是为了玩弄修堤才这样讲的吧。

「怎么着，以为是谎言？但不是咧。」

「咦……」

「好不容易鼓起勇气申请采访的呗？然而伦家却说谎或是讲表面话带过的话，这样对记者先生的气魄太失礼咧。」

「──」

双手在脸的前面交握，盯着自己看的安娜塔西亚令修堤屏息。

还是一样被掌控了局面。但是，不会觉得对方谎话连篇。能够让人这么想，这件事本身对修堤来说有着惊讶与感动。

库珥修说自己尚未成熟，还在累积知识的道路上，深深打动了修堤。而安娜塔西亚给了跟她截然不同的，让修堤目睹了某种庞然大物的感动。

不管是基于个人还是记者的立场，都想听她多说一点。这就是她的魅力。

「那、那么，今天还请赤裸裸地回答问题……！」

「讲赤裸裸，有点害羞咧？还有，机会难得，希望能写一篇好报导……这样的话，伦家也稍微下点功夫呗。」

「稍微下功夫，是吗？具体来说是……」

做些什么呢？但后面的话被中途打断了。

因为听到再清楚不过的高亢鞋跟声响。──有时，存在感这东西也会延伸至该人的脚步声，这是修堤第一次认知到这点。

不过这份感慨在见到脚步声的主人后，立刻消失无踪。

「──竟然叫妾身过来，挺得意忘形的嘛，母狐狸。」

难以形容的热度烙印耳膜，修堤不禁觉得喉头一紧。

现身于大街，看着店内一行人的美女，双唇吐出的声音洋溢着捕获听众心灵的魔力，事实上，修堤就被捕获了。

整个人僵住的样子，让美女皱起娥眉。

「怎么着，小童。一直瞄着妾身的脸看，太无礼了吧。」

「呜噎呜！？对、对不起……！我没那个意思……」

「要看就正大光明地看。凡人会被妾身的美貌给魅惑是极其正常的。」

说完用手中的扇子示意自己的，是有着血红瞳色的华丽女子。

耀眼的橙色头发以宝石装饰，丰满美丽的身材以血色礼服包裹，其美貌堪称暴力。这容貌的特征，以及散发的支配者气息──让大脑停止运转的气味，一并告诉修堤这位美女的身份。

那就是──

「偶介绍一下，记者先生。──她是跟伦家同为王选候选人的公主。」

安娜塔西亚讲得轻松自在，而修堤光是要在心里回答「我知道」都很吃力。

「──」

就这样，心灵发出声响，干渴到龟裂。在这样的错觉当中，就只有专注动笔的露露拉拉画个不停的声响。

──唯独当下，他打从心底羡慕能够沉浸在自己世界里头的露露拉拉。

6

「这、这次真是黄道吉日，该怎么跟聚集到这儿的各位道谢让我想破了头、眼花撩乱了，对……！」

拼命挤出来的招呼语，后半段混杂了修堤的真心话，不过只出这点小差错已经算不错了。

就连「亲龙报文」干部、身经百战的摩根总编辑，被放在这种状况的话都没法不紧张。更何况修堤还只是个菜鸟记者。

当然，他是以不把这点当作借口的心态拟定了这个计划──

「──记者先生，反应真不赖咧。公主小姐不这么想咩？」

「妾身承认小童是有可爱之处，但跟你意见相同真是让人不快。」

「唉，真冷淡。虽然早有料到会是这种态度。」

说完，安娜塔西亚手掩嘴巴轻笑，结果坐在对面的美女貌似不服气地眯起眼睛，鼻子轻声喷气后晃动丰满胸脯。

面对两者之间的对峙，修堤感觉自己的心理准备正在瓦解碎裂。

这也难怪。与安娜塔西亚对峙的美女，名字是普莉希拉•跋利耶尔──竞争露格尼卡王位、众所周知的候选人之一。

也就是说，现场有两位王选候选人正面交锋。

而且──

「没、没跟我商量，就突然带来这种惊吓……」

「抱歉，是安娜塔西亚大人出其不意的计策，不过变得像是攻其不备了。只能向修堤殿下和露露拉拉表达歉意。」

「被骑士由里乌斯道歉，也太惶恐了……！对吧，露露拉拉。露露拉拉？」

由里乌斯代替主人致歉，修堤马上回以真心话。

心脏剧烈的跳动令人难受，想说至少把这份痛楚分摊给搭档。但是露露拉拉没有说话，而是撕下画纸给予回应。

上头画着的，是口吐白沫、脸色苍白的修堤。

「你似乎很享受，这真是再好不过了！」

「瞎咪瞎咪？哇，很棒捏。这个可以给伦家当作今天的纪念吗？」

「请、请收下……假如您不嫌弃我那丢人现眼的表情的话。」

得到出乎意料的高评价，于是修堤就把画献给了安娜塔西亚。

自己慌乱的表情留在安娜塔西亚手边，心情感觉很奇妙，不过露露拉拉的画作被人赏识，身为搭档也感到自豪。

不管怎样──

「是那个吧？要开始所谓的共同访谈。唉呀～一群记者堵麦采访跟公主绝对合不来，不是那样子我就放心了。」

笑着耸肩的，是坐在普莉希拉后面、外观奇特的男性。

虽然已经听取介绍，但跟安娜塔西亚和普莉希拉的美貌不同，给人深刻印象的理由来自于外观特征，然而不是由里乌斯的那种俊美。

用漆黑头盔藏住脸，穿着就跟山贼没两样的人物，名叫阿尔。就跟侍奉安娜塔西亚的由里乌斯一样，是普莉希拉的骑士──不过这对主仆都否认这点。

「我是公主的小丑喔。我从以前就讨厌所谓的骑士。哎哟，我这可不是在说『最优秀』先生的坏话喔？这只是在讲概念而已。」

「我也不认为被挑衅了。只是很遗憾，我喜欢骑士。这一点，也跟阿尔殿下说的一样，是指概念方面。」

彼此都待在主人后方，由里乌斯和阿尔开始唇枪舌战。

在修堤看来，两个主人给人针锋相对火花四射的印象，不过这两人就不是了。

「得救了……要是两名骑士也吵架，那我的心脏会撑不住的……！」

老实说，虽然状况等同被安娜塔西亚给设计了，但这或许是对方给的最小程度的体贴。

「──采访王选候选人时，尝试看看跟先前不一样的方法，就这样理解吧。」

撇开修堤的内心小剧场，双手环胸的普莉希拉平静打响地第一炮。

用这姿势彰显自身胸部的她，轮流看过在场的人一遍。修堤、露露拉拉、阿尔、由里乌斯，最后是安娜塔西亚。

「不过，这个组合叫人不明白。母狐狸，为何妾身要跟你共同采访？」

「嗯～问得好。确实，找其他两人也是可以。菲鲁特小姐和爱蜜莉雅小姐应该是不会拒绝这个提议的。不过……」

「──」

「偶认为，公主小姐最能理解伦家提议的意图，对呗。」

竖起食指贴在嘴唇上，安娜塔西亚嫣然一笑。听了这答案，普莉希拉沉思半晌；这段期间，修堤试图松弛紧张得僵硬的脸颊。

──将这个逆境转变成好机会吧，修堤•梅根。

「──算了。有些人否定耍小聪明、走邪路的作法，但妾身跟那些固执己见之辈不同。算是与母狐狸的计谋相应吧。」

「哦哦，厉害。公主折服了，那边的商会长小姐很行喔～」

普莉希拉减缓追究力道后，阿尔吹口哨称赞安娜塔西亚。「过奖咧。」安娜塔西亚这样回应，由里乌斯则是手贴自己胸膛。

「得到您的承诺，容在下献上谢意。那么，修堤殿下。虽然跟预定的有些落差，不过能否继续采访呢？」

「咦？啊，好！好的，请交给我！一开始因为吓到和紧张，所以腿跟腰都软了，但是在这边退缩的话记者魂会腐烂炸开的！请各位多多指教！」

「好咧好咧，多指教。」

「拼命是小童的美德。就奖励你吧。」

得到两个阵营的承诺后，修堤也终于重振心灵摆出采访架式。

心境到达这阶段，马上就浮现出该问的问题。首先是对较慢来的普莉希拉，询问先前问过安娜塔西亚的问题。

「那么，先请教普莉希拉大人。这个问题稍早也已经询问过安娜塔西亚大人，请问您是为了什么而打算成为国王的呢？」

「哦～母狐狸回答什么？」

「伦家的答案跟在城堡里的时候一样。除非公主小姐忘记咧。」

「假如是服从你自身的欲望，那么那番大话就不会改变。」

安娜塔西亚摆手道，普莉希拉则是从胸口拔出扇子摊开。

从普莉希拉的回答可以得知，安娜塔西亚在王城内所主张的参加理由──得到露格尼卡王国是事实。

不是在怀疑，但再怎么说这种贪欲也太庞大了，让人闭不起张开的嘴巴。

「安娜塔西亚大人的宏大想法着实叫人惊讶，那么普莉希拉大人的理由是？每位王选候选人是基于何种理念而参与王选，也是国民想知道的事。」

自从宣布王选开始后，决定下一任国王的战争早已开启。

可是包含修堤在内的众多王国人民，都不知道参加的候选人的心态和为人，乃至于打算引导王国的未来走向何方。

情报很容易产生变化，不只形状会改变，连颜色和气味都会被涂抹。

为了采访而接触到的王选候选人已有三位──每位的人品都跟民间风评不同，修堤对自己轻信传闻感到羞耻。

普莉希拉才不是什么悲剧霉运缠身的虚弱少女。

而是带着令人联想到烈火与鲜血的赤红，具备刚烈脾气以及魔性美貌的超规格人类。

这样的她所描绘的王国未来，究竟会是──

「──什么都不做。」

「咦？」

怎样的答案呢？严正以待的修堤听到后傻眼。

忍不住停止思考的脑子里头，反覆播放普莉希拉的答覆。

「什、什么都不做？什么都不做是指……」

「想成跟字面意思一样便行。妾身没特别打算对王国或草民做些什么。因为这世间万物，打从一开始就是妾身的。」

「──」

「没有必要刻意去扰乱自然的安排。当然，是需要整理吧，也可以说是修剪。然而，世界原本的样貌就很美。──这个世界对妾身而言，本来就是量身打造的。因此只要妾身坐上王位，繁荣自然也会随之而来。」

拄着脸颊淡淡陈述的答案，渲染了修堤的脑袋。

多么夸张的谬论，就算被一笑置之也理所当然的玩笑话。若要问为什么，因为这种傲慢的想法，是连位居王国顶点之人都不会有的想法。

可是，让人觉得是玩笑的这番话，听在修堤耳中却不觉得是玩笑。

没法一笑置之，不是因为普莉希拉很可怕。而是因为修堤的灵魂接受了她所说的话并非虚假妄言。

「还是一样，公主小姐的道理真可怕。……假如那是真的，那伦家以外的人，都没理由违抗公主小姐咧。」

「对吧。其他家伙的愿望，用不着登上王位也能实现。但是，就你的贪婪没有妥协的余地。──因此，你是妾身的敌人。」

「唉呀，评价这么高，好荣幸。伦家也认为公主小姐是敌人捏。」

虽然一脸和蔼，但安娜塔西亚的回击也相当锋利。

同为王选候选人，出其不意地策划了同时接受采访，因此原本以为两人的关系还算和睦，但眼前的展开却抛弃了这种期待。

「不过，正因如此，才有切入的价值……！」

刚刚普莉希拉的发言，为了避免表达方法有误，必须刻意挑字选词。但是，这终究只是正确与否的问题，不必对事实加油添醋。

王选候选人的发言，只要毫不保留地传达出其真义即可。

「对于其他候选人，请问两位抱持着怎样的看法？」

「依现状来看，最被期待的是库珥修小姐呗？以立场来说也是坚不可摧，但是她的方针能获得多少支持是个问题咧。」

「来自贫民窟的小姑娘，说话倒是豪言壮语。但那个不过只是无限放大志向，看不见自己脚下的愚者顶点。要是继续那样子愚昧下去，毫无可看之处。」

面对提问，安娜塔西亚和普莉希拉陈述意见。

没有插嘴对方的话，在于彼此的意见没有可以置喙的余地吧。两个脑筋运转速度极快的人所作的答覆，修堤拼命地写在脑子里头。

前面是库珥修，刚刚的是针对菲鲁特。那还有──

「──请问对第五人，爱蜜莉雅大人的看法是？」

「「──不值一谈。」」

想要深刻切入的问题，却被极端的几个字给驳回。

简短话语强大到让修堤倒抽一口气，张口结舌继续追问。

「这、这是基于怎样的想法而得出的答案？」

「根本用不着说。说穿了，爱蜜莉雅小姐会被原本的出身给绊住脚步呗。银发又蓝紫瞳孔，还是个半妖精……不该有的特征全都有咧。」

「连过问当事人的资质都没必要。无论本质如何，多数草民都愚昧无知。只会凭想看的东西与想听的话来判断。」

她们说的话虽然有差异，不过核心是一样的。

最后一名王选候选人爱蜜莉雅，置身的状况严峻，甚至已经到了没人关心她理念的地步。

而且不只是别人，连修堤本身也有这种想法。

「可是听说爱蜜莉雅大人也跟安娜塔西亚大人以及库珥修大人一样，对于消灭三大魔兽之一的白鲸以及大罪司教做出了贡献……」

「那个严格来说不是爱蜜莉雅小姐本人做滴，是她的骑士的功劳。而且『嫉妒魔女』的伤口可没浅到可以这样就擦掉咧。呐，由里乌斯？」

「说来伤心。」

接过话题的由里乌斯，垂下长睫毛然后摇头。

「不清楚听到消灭白鲸与大罪司教的人，内心有多震撼。但就如安娜塔西亚大人所言，无法有过多期待吧。」

「真是让人遗憾啊。都做到这样了还没法受到好评，都不知道是为了什么而挑战了。是为了输才去做的吧？」

「阿尔殿下，那种说法……」

「不妥吗？那样讲才是表面话吧。讲白一点，我跟你说的有差很多吗？公主她们的意见也一样吧？」

由里乌斯的眉心挤出皱纹，阿尔则是像在扮演坏人。他用单手──右手的手指去摸头盔的接缝，发出卡铿卡铿的声响。

干巴巴的声响，感觉就像是把横亘在爱蜜莉雅面前不会改变的现实摊开来看，修堤也莫名感到郁闷。

可是──

「所有的事物自有其独特的成败条件。不过，那东西的胜利条件就是那东西本身。不是外部可以推测并轻易决定的事态。」

「公主？」

「那个半魔在王选中就是个不值一提的敌对候选人，这点毋庸置疑。但与那个相关的所有人全都蠢到不了解这点吗？妾身可不这么想。」

随从阿尔的意见，被主子普莉希拉给覆写。

被讲成这样，阿尔也不禁歪头。

「喂喂。我没想到会被人背刺耶。公主不是意见跟我一样吗？」

「就算过程一样，结论也不同。那个半魔的心态，也可以说是一样的。」

「那公主是说，那女孩没有想要当国王啰？意思是设定了其他目标吗？」

「不然的话，道理就说不通了。不过──」

阿尔的口气带了些许热度，且好像带着拼命的感情。

修堤对此感到诧异，却无暇插嘴。不过这是修堤的情况。──可以匹敌普莉希拉的大器者没有让她这么好过。

「──必须加上『维持现状的话』这个前提呗。」

「哼。」

安娜塔西亚这样接话，普莉希拉眯起眼睛从鼻子喷气。

目睹了无法断言是错看的一幕，似乎意味着她们意见一致。这代表两人对爱蜜莉雅的认知是一样的。

「有意思，不觉得很期待咩？一开始就注定大败的比赛，爱蜜莉雅小姐却还是打算挑战。她有颠覆败战状态的手段──不觉得她好像在这样讲咩？」

「假若只是为了凑数才参战的，那根本没有价值入妾身的眼。如果想证明自己有价值，就主动映入妾身眼里吧。」

微笑与嘲弄，两人相反的反应令修堤产生莫名的感慨。

因为不知为何，他觉得安娜塔西亚和普莉希拉她们对话题中的对象，寄予的感情都接近期待。

「呿！感觉像被当成踏脚石。真要说的话，如果不是心情上的，而是真的被公主踩还比较像样啊。」

「阿尔殿下，我们都在记者面前。身为骑士，建议发言时要谨慎。」

「多谢忠告。不过，我说过了吧？我不是骑士，也没有想要去当。」

「遗憾。我是发自内心说的。」

由里乌斯闭上眼睛答腔，阿尔弄响头盔接缝故作滑稽。但这举动的背后看不见方才的拼命。

抑或那也是修堤看错了，只不过是错觉呢──

「感谢诸位宝贵的发言。再来……请问两位怎么看待最后的敌对候选人，也就是眼前的对手呢……！」

「……勇气可嘉喔，记者先生。」

明知不会收到什么像样回答还是问了出口，惹来阿尔发自真心的感叹。由里乌斯也忍不住对这问题苦笑，不过没有不问的选项吧。

因为当事人就在眼前。这正是没有任何忖度，问出彼此真心话的绝佳机会。

事实上，安娜塔西亚和普莉希拉肯定也想过会被这么问吧。

她们两人互看对方，同时开了口。

接着──

「──一脚踢开咧。」

「──亲手摘除。」

双方互相交换了也能视为最佳赞赏的敌意。

7

「寿、寿、寿、寿命缩短了……」

「……辛苦了。」

露露拉拉慰劳瘫软在椅子上、面如土色的修堤。

在椅子上抱着膝盖的她，难得关心起修堤。她也稍微理解到了修堤是花了多大的心力才终于完成采访的吧。

事实上，这场奇迹般的访谈，也表现在露露拉拉洋溢奔放的创作欲望中。

以各种角度画出安娜塔西亚和普莉希拉的画作，在获得摩根总编辑肯定这点上，可说是有史以来数量最多的一次。在这当中也有几张是随从由里乌斯和阿尔的画，以取材纪录来说，这工作态度完全无可挑剔。

「只是，数量偏向某些人……虽然现在才讲，但露露拉拉也很看脸呢。」

「……这是误会。」

「两个王选候选人和骑士由里乌斯的张数，跟阿尔殿下的比起来一点说服力都没有！说起来，阿尔殿下就只画了一张！」

「……只画打动心灵的东西。这话修堤也说过。」

面对修堤的追究，露露拉拉拿出「亲龙报文」的宗旨来规避。被这样一讲，修堤也不好太强硬。

虽然只有一张，但证明了阿尔也有打动露露拉拉心灵的一瞬间。

「……因为有认真的感觉，就画了。」

「阿尔殿下认真……是呢，说的也是。这确实是认真的样子。」

露露拉拉笔下的阿尔，是跟普莉希拉意见相左的那一刻。

正好是问到对其他候选人──爱蜜莉雅的意见时，阿尔当时的回答也让修堤觉得耿耿于怀。

「──。等这次的采访结束，下次去深入了解王选候选人的骑士说不定也不错喔。爱蜜莉雅大人的骑士，我也非常有兴趣呢。」

「……下一个比较重要。」

画完一个题材后，露露拉拉的重心就会快速转移到下一个题材。这现实的态度让修堤苦笑。

「果然，露露拉拉是外貌协会。是不是很迷恋下一位采访对象呀？」

「……下个采访对象是？」

「明明就知道，少装傻了！……不对，假如露露拉拉迷恋的是骑士的话，那可能是真的忘记了！？」

「……只是没在听。」

「这样啊……怎么可能！光是没在听就是问题了！」

挥洒手中的笔，在采访内容的新鲜度下降之前先归纳统整起来，同时感叹可靠的搭档有着不可靠的记忆力。

但是，虽然形式意想不到，不过同时完成了普莉希拉的访谈，如此一来，采访过的王选候选人就有三个了。剩下两个人，而下一个要采访的对象是──

「──菲鲁特大人。她也有着特殊经历，只是那特色被爱蜜莉雅大人的情报给盖过了。」

「……特色！」

「跟绘画的颜色无关，意思是独特！……其实菲鲁特大人，是在王都的贫民窟长大的孤儿。──也就是说跟我们一样喔，露露拉拉。」

盯着把画本放在大腿上的露露拉拉的眼睛，修堤这么说。

修堤和露露拉拉现在的身份是「亲龙报文」的记者以及报纸绘师，但原本都是被双亲抛弃、在贫民窟挖垃圾挣钱的孤儿。

大部分的孤儿都无法脱离那个环境，不是开始做坏事，就是被坏人利用而失去性命。幸运的是，两人都没变成那样。

反而是各自的才能和热情被认可，争取到了现在的职业。

菲鲁特可以说也一样。──只是她的现状，高度超乎想像。

「除此之外，菲鲁特大人也流传着不知真伪的传闻。关于那些也是我想问的……不过最受注目的是她的骑士啊！」

「……剑圣！」

「没错！『剑圣』莱因哈鲁特•范•阿斯特雷亚！……他担任首席骑士辅佐菲鲁特大人，这样的声明带来的影响极大。」

不只「亲龙报文」的读者，对绝大多数的民众来说，生活在王城的王选候选人根本就是远在天边的存在。即使是国王仍健在的时期，人民也是这样看待王室成员。

因此，要说庶民会在意的知名人士，就会是经常听到名字的人了。在这方面，当代「剑圣」莱因哈鲁特所具有的影响力，堪称王国第一吧。

连王都居民对「剑圣」的关注程度，都超越了国王。而没机会看到王室成员，甚至也没机会瞻仰王城的外部居民，对两者的关注度的差距就更大了。

「当然，菲鲁特大人为了在王选中获胜，应该也会尽量利用骑士莱因哈鲁特的影响力。『剑圣』的威望就足以吸引众多目光……所以！」

「……所以？」

「我们不能输给他的威望，要看清菲鲁特大人真正的器量！」

修堤握拳道出的决心，不知道露露拉拉有理解多少，她的表情还是没有干劲，动作悠哉地打开画本。

到目前为止运气很好，采访都进行得很顺利，可是很难说后头都会按照计划走，毕竟前面都只是结果不错。所以说，从这边要开始挽回局面。

不管「剑圣」有多耀眼迷人，修堤那有如钢铁的记者魂也不会发抖──

8

「──欢迎来到阿斯特雷亚领。我诚挚欢迎两位记者。」

出来迎接修堤他们的，是宛如火炎的青年。

红发就像燃烧一样耀眼，双眼像是把湛蓝天空给封在瞳孔内，出乎意料的是个美青年。虽然以前露露拉拉就画过一张他的画，自己当时也看到着迷；不过如今画中的当事人笑脸迎人、亲自出来接待前来采访的两人。

「骑士中的骑士」的接待──只不过打扮没有骑士样。

「请、请问是骑士……莱因哈鲁特吗？」

「是的，正是我本人。有劳两位刻意从王都前来，辛苦了。」

忘了紧张，惊讶到结巴的修堤问道，青年──莱因哈鲁特点头。

他脱去了标榜禁卫军和骑士身份的制服，改穿白衬衫黑长裤这种城镇风格的便服。脖子上挂着毛巾，微笑以对的他，也没将「剑圣」的代名词「龙剑」挂在腰上。仔细看，是斜靠在身旁。

这简直就是他放掉了「剑圣」身份的证明。

证据就是，在迎接两人到来之前，他一直都在──

「……整、整理庭院？」

「嗯，对啊。我刚好在整理宅邸的庭院和花圃。今天早上，花苞终于绽放了呢……」

「……漂亮。」

露露拉拉歪头问道，莱因哈鲁特则用手示意花圃这样回答。他答得自豪，身后的花圃也确实很漂亮。

竞相绽放的有红色与白色的花，以及另外一种花瓣是黄色的花朵。吸睛的是颜色丰富多彩的花圃，不过被细心保养的庭院树木，在外行人眼中看来也能知道园艺师的手艺高超。

不愧是「剑圣」，修剪树木的技术也是一把罩──

「不对不对不对！忍不住佩服，但一般都是交给下人打理吧！？『剑圣』竟然拈花修树！」

「……对剑圣有意见？」

「我才不会做出那种不要命的行为，也做不到啦！」

看到「剑圣」被用在无聊小事上，修堤大惊失色提出抗议。结果露露拉拉马上就不站他这边，于是他连忙改口。

两人的互动令莱因哈鲁特轻笑，接着脱去工作手套，说：

「原来如此，『剑圣』不适合修整庭院吗。那你认为应该怎么做？」

「这个嘛，因为骑士莱因哈鲁特在王国内是无人不知无人不晓的名人，因此一般来说应该是巡逻各地，靠自己的颜面和名声得到有力贵族的支持……！」

「──好像是这样喔，菲鲁特大人。」

被莱因哈鲁特本人问有效利用他本人的方法，修堤讲出当下想到的方案。但马上就被对方后面说的话给吓到。

「哦耶？」修堤不禁发出愚蠢的声音，然后顺着莱因哈鲁特别具深意的视线看过去。──视线的尽头是站在修堤和露露拉拉后方的人物。

在附近的城镇接到两人后，带着他们来到阿斯特雷亚宅邸的跑腿少女。承蒙这份好意，一路天南地北地聊到宅邸。

少女的特征是在耀眼金发上别上黑色蝴蝶结，有着意志坚强的红色瞳孔，以及从嘴角探头的虎牙。而莱因哈鲁特刚刚称她为──

「啊、噫、呜、唉、喔……？」

「哦～哦～整个人陷入混乱了。哈哈！看啊，这家伙的脸！」

修堤嘴巴一开一合，惊恐得张大眼睛时，少女指着他忍不住笑出声来。露露拉拉也顺着她的动作看向搭档。

「……有趣。」

「哪里！一点都不有趣好吗！？」

露露拉拉毫无同情心的发言，让修堤高声反呛。少女对此笑到眼角泛泪，这时莱因哈鲁特叹气。

「菲鲁特大人，恶作剧也差不多该打住了。做过头的话会被修堤殿下和露露拉拉小姐给讨厌的。」

「知道啦～知道啦～。真是的，才想说好像稍微懂一点人话了，结果啰哩叭唆这点还是没变嘛。」

「已经变得比较有弹性啰。所以才没有阻止您去接客人。」

「你派了弗拉姆和葛拉西斯来监视吧。他们还太嫩了。」

少女朝着微微苦笑的莱因哈鲁特吐舌头并这样回应。──不，称对方为少女这种逃避现实的方式已经不管用。她是能够随意使唤莱因哈鲁特，还应当被尊敬的人。

毕竟她的名字已经听了好几次，绝对不可能听错──

「──能够拜见您是我们的光荣，菲鲁特大人！」

「嘿！感谢这种会让耳朵痒的招呼喔～」

想办法扼杀惊讶后打招呼，但菲鲁特却是边掏耳朵边这样回答。

乍看之下只是个城镇女孩的她，正是第四位王选候选人。

又是开头就挫败，可是跟同时采访两人比起来，这点程度──

「……给你。」

「露露拉拉！？」

紧张到停止呼吸时，身旁的露露拉拉突然递出一张画纸给菲鲁特。「嗄～？」菲鲁特挑起眉毛接过，看向上头的画。

接着──

「噗哈！啊哈哈！你看这个，莱因哈鲁特！」

「这是……呼。」

在爆笑的菲鲁特呼唤下，从后面看了画作的莱因哈鲁特喉咙发出低鸣。

这对主仆的反应，让修堤嘴巴一张一合。

「连骑士莱因哈鲁特都……露露拉拉！？你到底给了什么！？」

「哇哈哈哈哈哈！」

菲鲁特大笑，莱因哈鲁特则是没法完全憋住笑。

视线在他们和露露拉拉身上徘徊，最后是莱因哈鲁特略带笑意把那张画给修堤看，而纸上画的人正是修堤本人。

是他睁大双眼张着嘴巴，整个人傻住看着菲鲁特的蠢样子。

「……是杰作。」

「真的，感谢每次的关照！」

露露拉拉自豪地举起画笔，修堤自暴自弃地朝她这样大喊。

9

「重新感谢两位在今天安排时间与我们会面……」

「一脸不服气的样子。算啦，看在刚刚让我捧腹大笑的份上，就不在意了。」

「感•激•不•尽……」

被带到阿斯特雷亚宅邸的会客室接受款待的修堤，回答变得很简略。

这是因为方才所发生的事，所以让他觉得菲鲁特很棘手。当然，面对王选候选人都会紧张，不过跟前面三人相比，这次的压迫感很薄弱。

「──？干嘛？」

「没、没有。没事。」

「那样子直盯着人家的脸看，哪可能没事啊。」

菲鲁特身子前倾，仔细观察修堤的表情。一面因她的眼神而脸颊僵硬，修堤感到有些沮丧。

以王位为目标的王选候选人，至少都要有异于一般人的王者风范──他认为，立于国家顶点的资质，这点是不可或缺的。

例如菲鲁特假扮佣人来接修堤他们，假如另外三人也做同样的事，是没办法完全骗过修堤和露露拉拉的吧。

因为她们有着藏不住的王者气质。

──很遗憾，从菲鲁特身上就感受不到这点。

想想她的来历，要磨练那资质的机会等同于无。虽说这也是没办法的事，只是不得不感到遗憾。

她还没做好跟前面三人分庭抗礼、争夺王位的准备。

既然如此，现阶段菲鲁特和爱蜜莉雅几乎是笃定落选，在争夺王位的就是库珥修、安娜塔西亚和普莉希拉她们。

包含这一刻，对最后两人的采访就成了无关痛痒的行程。

「──要结束对我的评估，会不会还太早了？」

「咦？」

「哎哟，看就知道了吧。你很明显一脸沮丧啊。」

嘟起嘴唇、眼神变锐利的菲鲁特，令修堤感到畏缩。

让采访对象道出内心话可是记者的任务，可是表现出这样明显的态度、损及自身的信用，这就说不过去了。

「──呃。」

道歉的话差点就脱口而出，可是却停了下来。

事到如今粉饰态度也没意义。还不如顺着对方开启的话题走。

「请问您看人的目光，是在贫民窟生活时培养出来的吗？」

「哦？突然就问了个很难开口的问题嘛。不过，我喜欢会露出这种眼神的家伙。」

「过奖了。」

「是要问贫民窟的生活让我变强了吗？嗯，是那样没错。」

明明过去被人毫不客气地探问，菲鲁特却不生气。不仅如此，还欣赏修堤的厚脸皮。

翘着二郎腿，一手支在腿上托着脸颊，菲鲁特看向窗外。──在远处的天空下，遥远的地方是她出生长大的王都。

红色瞳孔透露的复杂情感，看得出是思乡情怀。修堤低头问道：

「……您是在怀念王都，怀念贫民窟吗？」

「嗄？没有喔？贫民窟的事我才不想回想起来咧。我又不喜欢～」

「啊咧～！？」

「未免太容易被气氛牵着走了吧你。就算离开了也完全不会想念的啦。离开了才清爽痛快，贫民窟就是这种地方啦。──你们不也一样？」

粗鲁抓头的菲鲁特撇嘴这么说。「是没错。」原本听了这话而这样回答的修堤，下一秒就倒抽一口气。

「您刚刚的说法，像是知道我跟露露拉拉来自贫民窟……」

「早看穿了，这又没什么大不了的。在贫民窟讨生活养成了判断人的习惯，这可是你说的。毕竟原本我的工作就是从蠢蛋的怀里拿一点钱。」

「那个，我跟露露拉拉算是记者……」

「所以才老实跟你们讲啊。假如撒个谎或随便说说应付了事就可以，那我一开始根本不会接受采访。随你们高兴怎么写就好啦。」

菲鲁特正大光明坦白过去犯下的罪行，修堤感到扫兴。

这个事实无疑会在菲鲁特的王选事业上造成坏影响。不过同为贫民窟出身的修堤，没想过要袒护她的犯罪行为。

因为有必要，为了生存只好做坏事。那原本也是修堤跟露露拉拉的未来，而现在菲鲁特也已金盆洗手。

只要是事实，就连万不得已的事都加以曝光，这样还能以这份工作为傲吗──

「我会先写下事实。要不要写进报导里，就留待之后决定……奇怪？我的笔呢……」

「这个吗？用的家伙还挺不赖的嘛。可以卖个高价喔？」

「您不是金盆洗手了吗！？」

讪笑的菲鲁特不知何时偷走了修堤的爱笔，还拿在手上摇晃，朝他炫耀。对这高明的手法是该佩服还是傻眼呢？

「──菲鲁特大人，修堤殿下觉得很困扰喔。」

打开会客室大门的莱因哈鲁特走了进来。

他手端银托盘，送来了冒着热气的茶杯，然后在主人与来客之间分配杯子。

「不会刻意隐瞒是菲鲁特大人的美德，但我认为没有必要刻意暴露缺点加以宣扬。来，请归还笔。」

「呿！又在说教。大致上，我啊……」

「这是罗姆殿下和艾佐的指示。」

「唔……！」

后面补充的那句话产生效果，菲鲁特的表情失去从容。接着她不甘心地把修堤的笔交给莱因哈鲁特。

对此苦笑的骑士，转头把笔还给记者修堤。

「请收下。还有这热茶，请务必品尝。虽然我还在学习……」

「哪、哪里哪里，太意外了！『剑圣』泡的茶！这是多么宝贵的机会，好。真想端回家看着茶蒸发！」

「……白痴吗？」

「是缓和气氛的玩笑啦！」

回呛露露拉拉的话，修堤这下终于恢复正常。果然大声讲话可以稳定精神。

话虽如此，也不能毫无节制地一直大叫。所以他轻咳一声，说：

「没等骑士莱因哈鲁特抵达就擅自开始谈话，实在是失礼了。」

「哦，用不着担心。因为内容我都听得一清二楚。」

「这样啊。那就放心……咦？在这里的对话？在厨房听得见？」

「啊～够了够了。要是把这家伙的每一句话都当真，那不管过多久话题都不会有进展，采访永远不会结束啦。今天很忙，人家之后也是有事的。」

莱因哈鲁特那句话让人意犹未尽，不过既然菲鲁特都说之后有安排其他事了，那就不能讲太久。必须知道菲鲁特对王选的干劲有多少。

交谈过后，在修堤看来，她根本不够格。不过她本人表示「自己放弃得太快了」，那么，她眼中的未来有什么呢？

「──菲鲁特大人当上国王后，打算做什么呢？」

「把这个国家看不见的规则，全部破坏。」

「……什么？」

对方回得毫不拖泥带水，修堤听了则是停下在笔记本上写字的动作。──刚刚菲鲁特宣告要破坏什么？

「这个国家，看不见的规则……是吗？」

「那些被认为理所当然的不讲理观念，我看过、听过、讲过，还是觉得不爽的东西，全部都是。贫民窟也是，没一个我喜欢的。」

「──」

「自然而然就会这样做、变成这样、这样去想，成为一股天经地义的风气。贫民窟的匮乏生活会乏味是当然的。可是，只因生在上流阶层就永远是胜利组，生在下层的人就永远是输家，这点我很不爽～」

在消化完话中意思之前，菲鲁特又继续讲述自己的意见。修堤一点一点消化的同时，还试图去逼近对方的真心。

如果只看字面意思，就是个在贫民窟出生长大的孤儿，嫉妒生在环境好的人，口吐内心的憎恨与黑暗面而已。

可是，菲鲁特的双眼和声音里，却蕴藏着更宏大、有重量的坚强意志。

「反正，你也对我没抱多大的期待吧？」

「──！」

「嘿！讲表面话只会让说出口的话变得廉价。不会随意隐瞒带过，在我看来是不错的判断。事实上，几乎是没有人期待我啦～。这也难怪。人家就只是在贫民窟长大的小女生，跟其他候选人完全没得比嘛～」

讲到这儿，菲鲁特打住，然后摇头。

「不对，还是比半魔大姊姊好多了，不过那是另一个层面。没有人期待我。──既然如此，也就没啥好失去了。」

「这就是您要挑战看不见的规则的理由吗？」

「一个人会去揍人，就是因为想让惹火自己的家伙流鼻血。不管怎样，反正我会第一个揍过去。机会难得，我都拿到免罪符了。会不会有人接在我后面出拳，不试试看怎么知道呢～」

粗鲁又乱来的巷弄礼仪，走这套的菲鲁特这样下结论。

这种主张荒谬绝伦又缺乏具体事例，但同为贫民窟出身的修堤却能痛切理解。假如露露拉拉有在听的话，应该也能明白。

于此同时，修堤看出了菲鲁特的可能性。

采访前觉得没胜算而对她感到失望与沮丧──还是老样子，从她身上感受不到王者风范。

但是，若要问这个无依无靠、缺乏力量的少女是否毫无可取之处，答案是否定的。

──菲鲁特具备了挑战者的决心，以及试图改变普世规则的革新者意志。

跟那些具备气度、生来就绽放光彩的才干者不同，菲鲁特的气度仍在培养形塑中。

说不定，即使王选分出胜负了，她的气度都还没定型。但是假如她的器量完成了，得以接触到众人目光的话──

「──看不见的东西会被破坏的日子即将到来。不觉得会有这种期待吗？」

「骑士、莱因哈鲁特……」

修堤所得到的结论，被莱因哈鲁特抢先说出口。

一看过去，他正用蓝色眼眸望着修堤与露露拉拉，接着凝视自己面前的菲鲁特。

「事实上，菲鲁特大人目前也仍在进行各种尝试。例如，我也是菲鲁特大人想破坏的东西之一。」

「……破坏剑圣？」

「没那么狂妄好吗～。莱因哈鲁特，少说奇怪的话啦～」

「可是，菲鲁特大人第一个想破坏的东西是我，可以的话，我不想隐瞒这件事，而是希望能广为人知。」

「可怕！知不知道自己在说什么啊你。」

微笑的莱因哈鲁特视线温柔，菲鲁特回应他的声音则十分凶狠。

看到这边，觉得两人培育出了万分奇妙的主从关系。之前访问过的王选候选人和骑士之间的关系虽然有细微差异，不过共同点都是关系良好。

可是菲鲁特和莱因哈鲁特之间，却有着无法说是良好关系的鸿沟。没到险恶或合不来，但就是有种身在强风中的紧张感。

「修堤殿下，其实我会打理庭院和照料花圃，也是因为遵守菲鲁特大人的嘱咐喔。」

「是、是这样吗？」

「是的。菲鲁特大人说，就试着去种种花吧。不巧的是，我有『园艺加持』，所以不至于到从错误中学习改进这么艰难……」

说到这儿，莱因哈鲁特停了下来，低头看自己的手掌。

原本戴着手套在打理庭院的手。为了接待客人而清洗干净的手现在没有任何脏污，可是在他眼中似乎还清晰留着做过园艺的手感。

虽然修堤觉得，那只是让「剑圣」莱因哈鲁特大材小用。

「其实，我觉得我本人的心情有转变。说不定世界的变革，都是从这种小事开始累积起来的。」

「夸张的家伙。……稍微称赞花园好看，就马上得意忘形了。」

「因为很高兴呀。毕竟是菲鲁特大人赐予我的赞美。」

菲鲁特拄着脸颊低语，莱因哈鲁特则毫不踌躇这样回答。

这句话让听着他们对话的修堤很惊讶，这点菲鲁特也不例外。她苦着一张脸，恶狠狠地瞪着修堤，彷佛是在懊悔表情被他看见似的。

「瞪我也没用啊！」

「混帐，真的有意义吗，这个采访。假如只是要让我心里不舒服的话，就算付出与回报不成比例，也该有个限度吧。」

「请不用担心，『亲龙报文』的发行数量在王都也是首屈一指。我认为罗姆殿下和艾佐的战略没有错。」

「喂！绝对不准把这笨蛋刚刚讲的话写进去喔！」

露出锐利的虎牙，菲鲁特直呼莱因哈鲁特为笨蛋。

要「剑圣」修剪庭院，让他泡茶招待来宾，最后还叫他笨蛋，菲鲁特到底把莱因哈鲁特当成什么了啊？

「菲鲁特大人认为，骑士莱因哈鲁特是……」

「啊～？睡傻了吗，说什么梦话～。──这家伙是莱因哈鲁特。」

「──啊。」

「不多也不少，就这样。明明就不听人话，抱怨倒是很多。对我来说就是头痛根源啦。」

双手抱胸，菲鲁特从鼻子用力吐气。听了这答案，后方的莱因哈鲁特什么也没回答，就只是眼神微微放松。

撇开莱因哈鲁特的反应，修堤省视自己，这才意识到：自己也是被菲鲁特口中的「看不见的规则」毒害的人。

在王国蔓延的身份差距，有形的有贵族街和贫民窟，无形的有贵族与平民和贫民，由此而生的偏见与先入为主的观念，自己应该瞭然于心才对。

但是随着采访王选候选人的次数增加，修堤越来越痛切感受到，自己绝对不是那种聪明又博学的人。

最后是被同样出身贫民窟的菲鲁特给点醒。

──修堤和众人对「剑圣」莱因哈鲁特•范•阿斯特雷亚的幻想，也是菲鲁特不喜欢并打算破坏的东西之一。

「菲鲁特大人，对于王选的结局有什么看法？」

「──」

眯起红色瞳孔，菲鲁特凝视发问的修堤。

修堤正襟危坐，正面承受视线。访谈到这边，一开始对菲鲁特的失望已然消失，剩下的只有莫名的期待。

究竟这个贫民窟出身的孤儿，会带来什么样的未来？这点不得不让人期待。

说不定，这就是莱因哈鲁特选择菲鲁特的决定性关键。

「哦，其他人都很了不起啦。一开始在城堡见到面的时候我什么都不知道，所以不晓得她们是怎样的家伙……」

对于在贫民窟出生长大的她来说，接受正式教育是在表明要参加王选，并决定在阿斯特雷亚家生活之后才开始。

修堤也有印象。一开始她连读书都不会，连应该要知道的事情都不知道，因此不先填补这断层的话，就无法站在相同的舞台上。

菲鲁特感到气恼不甘，却还是不死心持续战斗。

「目前的话，占优势的绝对是公爵，再来就是商人吧。虽然有参加猎杀鲸鱼，半魔大姊姊那边还是欲振乏力吧。那个红色女人我就不知道了……」

「──」

「不管拿我跟谁比，对方都是好评拔得头筹。前途一片黑，能不能在这三年弥补差距，就是我的胜利条件。」

正确掌握自己的现状，并给予客观明确的分析，让修堤佩服不已。

掌握战况，也是她没有扔下比赛的证据，更是为了求胜而决定用尽手段的证明。

不过前途可说是多灾多难。这点毋庸置疑，而且她也有自觉。

「请问您已经决定好如何应战了吗？」

「目前，就算模仿其他人也不会赢。我要做只有我能做到的事。因此……」

「因此？」

「总之呢，先从说服黑社会的人开始，这已经在进行了。之后的事，也会跟那些干部开会决定。」

「跟预想的完全不一样耶！？」

菲鲁特笑得天不怕地不怕，给予出乎意料的回答，修堤听了忍不住大叫。

「哇哈哈哈。」这样的反应让菲鲁特开心不已，站在她后面的莱因哈鲁特则是手贴额头。不过想要掩住脸的反而是修堤。

王选候选人之一跟黑社会有牵扯，根本是等着被淘汰。

「这个独家新闻重大到好像没人会相信……！」

就算内容给摩根总编辑看过，也会被认为是捏造的报导吧。毕竟没有人会想到，候选人竟公开这个秘密。

「──」

就在修堤抱头的时候，身旁的露露拉拉默默地画画。

她的画兴没有离开莱因哈鲁特──本来以为是这样，但关于菲鲁特的画作也在不断累积。她也总算意识到自己是报纸绘师，就该把所有采访对象全都画下来这个铁则了吧。

但很遗憾，并非如此。单纯只是菲鲁特的态度符合露露拉拉的目光罢了。就像修堤改变对菲鲁特的认知，露露拉拉似乎也是这样。她画在纸上的事实，以及画作的精美程度，可以说证明了菲鲁特大器的一面。

还有就是──

「然后？除了我为什么参加王选，参加后打算做什么……还有其他想问的吗？」

「……我也有问过其他人，请问菲鲁特大人对于其他王选候选人有什么印象？」

「其他人吗。刚刚也说过了吧。都是了不起的家伙。」

菲鲁特冷静地做出不容小觑的自我分析。

只要针对每一位候选人细问，恐怕都能听到有听取价值的评论。虽然当下并不在场，但应该是有为她献策的优秀参谋吧。

可以的话，很想也访问菲鲁特阵营的其他人。

不过沉思的菲鲁特抓抓脸，说：

「我想想，虽然不是什么了不起的看法，不过公爵是个棘手的对手吧。在城堡看到我的时候，就只有她没有低估我。明明她已经是最有力的人选了，真是大意不得呢～。唉呀，虽然她评估我的理由似乎不是只有这点啦。」

「原来如此，库珥修大人……那么，请问安娜塔西亚大人和普莉希拉大人呢？」

「商人……安娜塔西亚的眼力了得。上次欠了她人情，看那家伙会怎么开口讨吧。不过，那笔人情债值那个价。我相信那方面的交易不会刺激到她的贪婪。再来是那个红色女人……」

说到这儿停顿了一下，接着菲鲁特皱起鼻子，看起来打心底感到厌恶。

「不是好坏的问题，是一定要揍扁她。」

「个人色彩相当强烈的感想耶！……毕竟普莉希拉大人的性格就是这么刚烈呢。」

「嘿！讲得可真好听。再来是──」

吐舌头后，菲鲁特稍微慢了一下，才评论最后一人──爱蜜莉雅。

花了一点时间才得出答案。不过，跟评价普莉希拉时不一样，里头没什么敌意。甚至没有针对半妖精的恶意，更像是表达不同的印象。

是什么呢？修堤期盼到身子往前凑，菲鲁特笑说：

「半魔大姊姊是那个。自己去亲眼看看吧。比起其他任何家伙，更能让你明白『传言不可信』这件事吧。」

「是、是在故作姿态吗……！？」

「嗯，我不讨厌喔～。因为我也欠那个大姊姊人情。」

双手在后脑勺交握，菲鲁特把对爱蜜莉雅的评价藏在心里。至少，跟她有关的发言少得可怜，都放在心底没有说出来。

菲鲁特建议自己直接去见她，这让修堤感到紧张。

打从拟定这个计划开始，在心情上最大的难关就是爱蜜莉雅阵营──终于剩下她还没采访，其他的候选人都已访谈完了。

然后──

「……画好了。」

露露拉拉边说边又撕下一张画纸。

「给我看、给我看～」菲鲁特开心地接过她递出的画作。是因为先前修堤的糗画让她尝到了甜头吧。

这次又会提供怎样的笑料呢？菲鲁特满心期待，双眼发亮──

「呿。」

（插图009）

「这是……」

菲鲁特皱眉，从后方看画的莱因哈鲁特睁大眼睛，接着笑了。

到底是画了什么？修堤也偷偷看过去，这才了解他们的反应何来。

画纸上是往后靠坐在沙发上的菲鲁特，以及后方表情柔和的莱因哈鲁特──这对别扭的主仆，透露出主仆味道的一刻。

10

──从想法和气势起头，采访王选候选人的行程。

给予修堤身心莫大负担却又有所进展的采访，终于走到最后的结尾。

最后要挑战的是最后一位王选候选人，也是本次企划中最大的障碍。

被唤作「嫉妒魔女」、差点毁灭世界的最可怕的灾厄──容貌被传说简直是「嫉妒魔女」再世的爱蜜莉雅，据说是个行径邪恶、走享乐主义的魔女。

当然，先入为主和民间情报不准，修堤已经透过至今的访谈有十二万分的感受了。即便如此，最难跨越的心理障碍还是「嫉妒魔女」的传闻。

连对画画以外的事漠不关心的露露拉拉，听到「嫉妒魔女」的名字都会发抖，那渗透进王国人民──不，是全世界人类的恐惧，是深入骨髓的。

因此，即便在王选里头背负着压倒性不利状态却还是决定挑战的她，究竟是基于什么想法和目的，以露格尼卡的王位为目标呢？

为了探听这点，修堤和露露拉拉两人前往梅札斯领地──

「──我的名字是菜月•昴！速度媲美疾风迅雷，不屈不挠的接待人员！」

右手食指朝天高举、左手插在腰部的少年这么大喊。

被一头黑短发又眼神凶恶的人物迎接，修堤感到傻眼，不知道这是哪来款待客人的习俗。

也因此，他慢了一步才意识到眼前少年报上的姓名的意义。──明明那是活在这个时代的报纸记者绝对不会听错的名字。

「──」

愕然失声的修堤，人在共乘龙车的停靠站。

这里是露格尼卡王国的五大都市之一，「工业都市」克斯泽尔。目的地罗兹瓦尔•L•梅札斯边境伯的宅邸就位在这个大都市的附近，因此行程预定是以此为中继站前往宅邸，在那边采访爱蜜莉雅。

但开头就以意想不到的形式受挫。修堤忍不住──

「请问，您说您是菜月•昴殿下吗？」

「呃？啊，没错没错，我就是菜月•昴本人。是两位要来采访的爱蜜莉雅酱……不，爱蜜莉雅大人的骑士……」

「果然！就是协助打败白鲸和『怠惰』的人吧！？」

「唔喔唔！？」

修堤忍不住身子前倾，少年──昴吓得往后仰。但是修堤还是兴奋到鼻孔撑大，步步逼近。

「关于您的传言，我一直很感兴趣！请问，可以请您谈谈那些事吗！？」

「可、可以。当然，我们这边就是为了这件事才来的，不过这次比起我，最重要的是爱蜜莉雅酱……」

「听说您跨越阵营之间的障碍要求协助，并且成功歼灭大敌！能够办到这点的信赖与谈判能力是在哪……啊好痛！」

呼吸急促地缩短距离，顺着好奇心勇猛往前的修堤后脑勺被敲了一下。一看过去，是挥动画本打人的露露拉拉。

她垂下眼角，展示用来打人的画本。

「明知会痛还用边角打我！？」

「……兴奋过头。伤脑筋。」

露露拉拉难得斥责人。对此傻眼到眨眼的修堤想到她是在讲自己刚刚的行为，连忙转向前面。果然，昴站在那儿，一脸苦笑。

顿时，感觉一团火瞬间从脖子烧上来，脸颊好烫。

「万、万分失礼……！我完全！我完全失去理性了！」

「哦～没事没事。虽然真的被气势压倒，不过反过来感受到你的干劲了。」

「您、您愿意原谅我？真、真的非常感谢！骑士菜月……」

鞠躬低头道歉的修堤，对昴宽宏大量的话感动不已。于是重新弯腰，正要握住对方的手的时候──

「──你，立刻远离昴！！」

「等等──！？」

旁边传来厉声和看不见的冲击波，被打中的修堤身体轻盈地在天空飞舞。被这光景吓到的昴转过头，看到一道娇小人影。

「真是的，真是大意不得。昴真的是没有贝蒂的话，有几条命都不够用耶。」

「碧、碧翠子，你……」

「哼哼～。看样子，是惊讶和感谢到说不出话来了。既然嘴巴笨拙，那至少用行动和态度来表达对贝蒂的心情。」

边说边朝慌张失措的昴伸出双手的，是身穿礼服的女童。昴伸出颤抖的手，朝长发烫成大波浪卷的她──捏住她红润的脸颊。

「呼呀！？干、干什么啦，昴！对、对刚刚救了你的贝蒂做这种事，是不可原谅的！」

「大笨蛋！我的性命确实就跟松软棉花一样不可靠，可是这次你操之过急啦！他们是来采访的工作人员！」

「……啊啦啦啦？是喔。」

脸颊继续被捏着的女童，凝视飞到昴后方的修堤。

无计可施顺着力道飞出去的他，撞进篱笆，只留下脚给露露拉拉拉扯。昴接着也连忙跑过去帮忙。

「没、没事吧，修堤先生！抱歉！我的碧翠子误会可大了！」

「没、没事，我没事……一头撞进某个东西里，是『亲龙报文』记者经常会发生的事……」

「这也太离谱了！总而言之……嘿咻！」

昴代替没力气的露露拉拉，把修堤的身体从篱笆丛拔出来。本来长到遮住眼睛的浏海夹满树叶，整个人都沾满了叶子。

「来，碧翠子，为你的操之过急道歉。说对不起。」

「可、可是，谁叫这个小不点做了让人误会的事。他也有错……」

「不准说这种不懂事的话！」

昴就在修堤面前教训起坚持己见的女童。不过女童反而更加顽固，还背过脸，于是修堤出面打圆场。

「好了，没关系没关系。用不着放在心上！看，我没事。」

「不，她一定要道歉！这也是教育的一环！来，碧翠子！」

「唔咕咕咕咕……贝蒂绝对不道歉……！」

头被按住的女童，拼命抵抗说什么也要她道歉的昴。这像是亲子般的互动令人微笑，不过修堤有种被抛在一旁的感觉。

犹豫要不要出手，不知所措的时候──

「──菜月先生、碧翠丝酱，你们在客人面前干什么呀？」

略显傻眼的柔和嗓音，制止了现场胶着的空气。

「哦！」不断一进一退攻防战的昴跟女童，一听到这声音便转过头，表情跟着转变。──站在视线尽头的，是一头灰色头发、身穿绿色服装的青年。

气质沉稳的他一登场，就让叫做碧翠丝的女童垂下眼帘。

「呜咕，不是啦。发生了不得已的事态……」

「那件事，就是你们放着满身叶子的客人不管的理由吗？」

「你这男人讲话真不留情耶！噗哼！」

被直接点出问题的碧翠丝闹起别扭，把脸撇向一边。轻拍抚摸她脑袋的昴，也是一脸尴尬。这本事让修堤感到佩服。

青年一现身，昴跟碧翠丝全都变得温顺乖巧。

「真抱歉，给两位添麻烦了。我会好好说说他们的。」

「呃，那个，谢谢、您？请问，您是？」

「敝人叫奥托•思文。算是后面这两人的……亲属。」

耸耸肩，表情交杂着自负与不得已的青年──奥托，他身后的昴与碧翠丝正感情融洽地闹别扭说：「什么嘛──」

但是，袭向修堤的震惊，并未让那两人察觉。

「奥、奥托•思文殿下，是吗？」

「──？嗯，是的……」

「噫噫噫！？真、真的很对不起！」

奥托不解，修堤却慌张地当场下跪。而且还拉身旁杵着发呆的露露拉拉的袖子，要她一起跪地。

「露露拉拉！露露拉拉，跪下！要是惹他不高兴，我们的脑袋会被咬掉的！」

「我才不会咬人咧！是说外头都是怎么谣传的啊！？」

「在、在故乡聘可塔特威胁有权势的人而被发布通缉，歼灭占据了基聂布山的山贼，还焚烧边境伯的宅邸要胁加薪的武斗派内政官大人……！」

「虽然嘴长在别人身上，可是这种说法不会太过分了吗！」

奥托忍不住拔高音量，却没有否认这些评价。也就是说，他对这些事有头绪。在看到本人之前，修堤还以为这也是个不能轻信的情报。

但是，他完美封杀打败白鲸与「怠惰」的菜月•昴，将他驯服得服服贴贴，这点是毫无疑问的。

「只、只求您饶我们一命……」

「喂喂，奥托。你该不会……」

「我才不会对他们怎样咧！？是说，不要连菜月先生都趁机恶搞，请赶快帮忙解开误会啊！这样子会没法收拾的！」

中间挟着缩起身子浑身发抖的修堤，昴跟奥托吵了起来。看着他们三个这样子，碧翠丝叹息，注意到蹲下来的露露拉拉的手。

在地上屈膝的露露拉拉，正以猛烈的速度挥动画笔。察觉到作画对象是自己，碧翠丝撩起自己的头发。

「要充分画出贝蒂的美喔。」

「……不会遗漏任何一处。」

对露露拉拉的回答很满意的碧翠丝点头。

11

──虽然开头发生了失误的小插曲。

「容我重新欢迎两位的到来。感谢大驾光临。」

离开龙车停靠站，再次献上迎接招待语的昴伸出手。

惶恐地回握他的手，修堤对昴的随和感到惊讶不已。写下新历史的英雄，他本人跟民间的壮阔评语相去甚远。

他总是跟碧翠丝手牵手。修堤也搞不清楚这两人的关系。

「没有啦，听到有人申请采访，奇蒙子就整个亢奋起来。毕竟选举的首要战术就是形象营造……宣传可是分出胜负的关键。」

「奇蒙子……形象营造……？」

「哦，菜月先生偶尔会即兴造词。就当做是菜月语便行。虽说他本人坚持是他家乡的语言……」

「还好啦，基本上意思都是代表心情或想法。左耳进右耳出就行了。」

边笑边回答的昴，其欢迎的心态就跟表现出来的态度一样，相当积极面对这次的采访。关于这点，内政官奥托似乎也持相同意见，丝毫感受不到众人对修堤和露露拉拉的敌意。

「不过，没想到迎接阵容这么豪华……而且来的都是重要人物。」

「其实爱蜜莉雅酱本人很想亲自前来，但她突然登场的话怕会吓到两位，所以阵营的大家姑且劝退了她。」

「本、本人本来要亲自前来！？」

对修堤来说，光是王选候选人的首席骑士昴亲自来迎接就已经很震惊了，但听到还有更夸张的可能性后，实在无法不惊讶。

「啊，果然会吓到。虽然爱蜜莉雅酱一点都不可怕。」

「但是人类这种生物，就是会屈服于权威和身份。这方面的观念，昴跟爱蜜莉雅都还不够喔。」

「关于这点我也有相同看法。希望可以透过这次的事有所学习。」

奥托叹气，指搓眉心，哀怨地这么说。

尽管武斗派内政官的说法也是，不过昴和碧翠丝的言行确实值得注目。因为是阵营相关人士，所以要说理所当然也是理所当然，但──

「请问从您们三位的角度来看，爱蜜莉雅大人是怎么样的人呢？」

这个问题在某种意义上十分虚情假意。在带领之下，作为抵达宅邸前的随口闲聊抛出的这问题，太过切入核心了。

「──」

最后，沉默的三人会给予多严肃的回覆呢？修堤屏息。

「──嗯，就是天使。可爱又拼命，但再怎么客气地说都是天使。」

「呜耶？」

可是才思索刹那，昴就立刻从口中给出这样的答案。

「昴……记者小鬼头觉得很傻眼啦。不是那个意思吧。」

「哎哟，我还以为就是那个意思咧。那不然，碧翠子你会怎么回答？」

「这还用说。爱蜜莉雅是个乐观到没药救的大蠢蛋。」

「碧翠子心中的爱蜜莉雅酱，形象会不会太低了？」

拉着昴袖子的碧翠丝给出的意见，也不符合世人对爱蜜莉雅的评价。对于这点感到困惑时，奥托以食指轻搔脸颊，道：

「哦～我明白修堤先生这问题的重点是什么。大概就是有没有掌握到一般世俗对爱蜜莉雅大人有怎样的评价吧。」

「噫！请不要生气！」

「我没在生气好吗！？总而言之！先入为主的印象大多都是骗人的。这次刚好是个让大家理解到这点的机会。」

虽然没有昴那么积极，奥托对本次的采访同样抱有期待。听了这话，昴也点头。

「说的也是。也希望能让世人认识真正的爱蜜莉雅酱，所以必须策划提升形象这一类的计划。就是这样，拜托你写一篇好报导啰，修堤先生。」

「我、我终究只是记录下亲眼所见、亲耳所闻的事。就算被武斗派内政官殿下威胁，也绝对不会……」

「我不会威胁人好吗！呜呜……王选结束之际，我的形象到底会变怎样啊～？」

「想了也没用的事，想破头也没用喔。」

感到世间无常的奥托，被碧翠丝晓以世间无常的大义。

在一旁看着这样的互动，修堤从三人身上感受到一些事。就是这三人都对爱蜜莉雅有好感，也为她的境遇抱不平。

身为银发蓝紫双眼的半妖精，就因为这样，世人便不讲理地加以排斥。三人对此很反感。

他们的愤怒，如果是正当的话──

「真正的……爱蜜莉雅大人吗？」

传言和实际情况不符，在本次的计划中没有什么比这点让修堤更痛切有感了。

库珥修、安娜塔西亚、普莉希拉，连菲鲁特给人的印象都产生了剧烈的变化。那么，同样的状况发生在爱蜜莉雅身上，也是可以接受的。

一这么想，不安与期待就越是澎湃──

「真想快点见到本人呢。」

「……明明很怕。」

修堤握拳的喃喃自语，只有认识他很久的露露拉拉听到。这样低语的自己，在她眼中是什么样子呢？

既然她已经开始挥动画笔，那这样的自己一定有勾起她的兴趣。

就这样，在众人的带领下，修堤和露露拉拉前往有爱蜜莉雅等待的边境伯宅邸。不过就在路上。

「──哦～？你们～来得正是时候！」

才想说怎么突然有粗里粗气的声音，一道人影便气势凶猛地从草丛里冲了出来。

是个一头金发、露出锐利牙齿，感觉很凶猛的人物。因为出现得突然，所以修堤圆睁双眼，倒抽一口气。

「咦？呜哇啊，有山贼！」

「这下事情可大条了……这个世界完蛋了……」

「咦咦！？出现在大城市附近的干道上！？」

丢着被状况撇下的修堤不管，昴跟碧翠丝面色铁青抱在一起，当场瘫坐在地。

看到他们这样，金发山贼愉悦地从鼻子喷气。

「嘿！看样子似乎搞不清楚状况呀。不想讨皮肉痛的话，就乖乖把东西交出来～」

「噫噫噫，只求、只求饶我们一命啊……」

俯瞰浑身发抖的一行人，山贼残虐舔舌。顿时把露露拉拉护在身后的修堤，转头看向奥托讨救兵。

就在这时。

「──到此为止了，恶棍。」

银铃嗓音突然响起，气氛整个被掌控。

不知发生什么事的修堤目瞪口呆，山贼则是「啊～？」不悦地转头。接着是草丛摇晃的沙沙声响，然后出现一名新人物。

银色头发闪闪发光，蓝紫瞳孔就像宝石一样，只要看过一次就不会忘记的美少女──她的样子，让修堤忍不住忘记呼吸。

集所有人视线于一身，少女直指山贼。

「我不会再容许你继续为非作歹。快离开昴他们。」

「哼！嘴巴很会讲嘛。你，是哪来的东东……啊！难道说！」

「没错，正是那个难道说。我是……我是……」

「──？」

挺身站在摆开架式的山贼面前，威风八百的少女气势忽地急速萎缩。她皱起细眉，维持指着山贼的姿势，一动也不动。

然后，偷偷地凑近昴。

「……昴、昴，下一句台词是什么？」

「……这边是『露格尼卡王国的下任国王候选人，爱蜜莉雅！』啦，爱蜜莉雅酱。」

「……啊，对喔。嗯，我知道了。呃──」

跟坐在地上的昴交头接耳后，少女恢复精神回到原本的位置，轻咳一下，接着继续。

「我是露格尼卡王国的下任国王候选人，爱蜜莉雅。──我要代替月亮惩罚你！」

「咕、咕啊啊啊～！糟糕，对手是王选候选人爱蜜莉雅大人，根本不可能赢啊！」

听到少女的台词，做出畏惧样子的山贼当场趴下。见状，少女深深颔首，然后盯着傻住的修堤他们。

「这样事情就告一段落了。各位，有没有受伤？」

微笑这么说的少女──不，假如方才报上的名号属实，就用不着怀疑她的身份了。毕竟从那明显的外观特征，也能看出她是谁。

「您、您是爱蜜莉雅大人吗？」

「──！嗯，是的。我只是非～常偶然经过……」

挺起胸膛，少女──爱蜜莉雅这样回答。可是话才刚说完，她就按住肚子蹲下，呜呜呻吟。

「爱蜜莉雅酱！？」顿时，昴慌张地冲到她身旁。

「怎么突然不舒服，没事吧！？」

「呜、嗯，我没事。只是撒谎后，肚子马上就抽痛……」

「这……一定是因为让你做了不适合的事。昴，已经……」

「白痴，不能放弃！好不容易做到这里，就该做到最后……」

围住爱蜜莉雅的昴跟碧翠丝慌张失措。因为完全看穿这是一场戏，修堤反而认真烦恼起该做出什么反应才好。

但是，假如要给修堤一个最佳解答的话──

「──不是耶，这场闹剧未免拖得太久了吧！！」

无法忍耐而这样大叫的是奥托•思文。

他吓到在场所有人，接着大步走向昴。

「菜月先生！这个战术不是已经驳回了吗！？为什么还硬是执行！」

「舍弃这个方案很可惜耶！就在我们被流氓混混纠缠的时候，被飒爽经过的爱蜜莉雅酱拯救！完全重现我跟爱蜜莉雅酱邂逅的场景！」

「那个，昴。我不记得有这样救过你……」

「当事人爱蜜莉雅大人不都这样讲了吗！可以麻烦你别再说梦话了吗？」

「跟爱蜜莉雅酱的邂逅确实就像作梦一样，可是那不是梦哟！？」

奥托揪起昴的衣领摇晃，爱蜜莉雅从旁插嘴。

修堤被撇在一旁的状态仍在持续，不过他已经知道一件事。那就是方才从三人口中听到的爱蜜莉雅的形象。

「你们两个，不要吵架！奥托，这也是昴拼命想出来的方案，你不要对他那么凶！」

奥托继续前后摇晃昴，在旁边的爱蜜莉雅于是大声起来。从那张拼命的侧脸来看，根本不觉得跟冷酷无情的「魔女」沾得上一丁点边。

就只是被眼前的事情给摆布，随处可见的普通少女。

「哟～碧翠丝……这个，莫非是失败了～？」

「还用得着问。说到底，让爱蜜莉雅撒谎本身就是个乱来计划。结果计划一塌糊涂。」

「呿！所谓的『精炼过头的嘎周鲁聂』啊～」

抬起低垂的头，抓抓头上金发的山贼──不，扮演山贼的少年这么说。他旁边的碧翠丝叹气，短短的双手抱胸。

「请问，您们都是同个阵营的人……对吧？」

「事到如今隐瞒也没用了吧～。本大爷～是『最强之盾』嘉飞尔•霆杰尔。可不是什么山贼，给俺记住了。」

咬响锐利牙齿的少年──嘉飞尔正大光明报上名号。

饰演小混混的演技惊人，不过他身上的霸气更是非凡，就连修堤也因为没搞错对他的印象而暂时放心。

不管怎样，这些都是该阵营所策划的、壮烈的形象营造计划──

「……闹剧，停止。」

「嘘──！安静，露露拉拉！我也想讲，可是都忍住了！」

露露拉拉直率的评语让修堤提心吊胆，回头瞥望一眼。结果他们的争执似乎恰好告一段落。

正是衣服乱掉的昴被扔在地上，爱蜜莉雅借他躺大腿的时候。眼角余光内的奥托边乔正帽子的位置，边朝修堤低头。

「不好意思，让两位看到难看的一面。关于这点……」

「不会！没有，我们什么也没看见！……毕竟要这样讲多少是有点勉强，还想着必须做出一点反应才行呢……」

「是吧。让你感到困惑，我也只能说对不起就是了。」

不知道是今天第几次了，奥托指揉眉心，大声叹气。

尽管相处的时间短暂，却足以令修堤察觉到奥托在这个阵营的位置。以他为主，带着各种勇武风格的传闻，或许也是在他对同伴大声规劝的期间传开来的。

「可是发布通缉令，还有歼灭山贼是事实呀……！」

「奥托兄啊～首领跟爱蜜莉雅大人都有在反省了。所以就别再紧咬不放了吧？」

「随便乱讲……说起来，嘉飞尔你配合演出，待会也要说你一顿。」

「嘎喔，打草惊蛇……！」

嘉飞尔露齿，一脸懊悔自己失言的表情。果然对这个阵营来说，奥托的立场就是监督官，或是顾问之类的。

就在修堤坚定这个印象的时候，如今印象仍尚未稳固的人──

「那个，对不起害你陷入混乱。大家都没有恶意……」

「咦、啊，好的。那个，其实，我懂，感觉上。」

「真的吗？太好了。我松了一口非～常大的气呢。」

爱蜜莉雅微笑并抚摸胸膛，看起来终于放下了心。

想要直接跟本人见面说话──几分钟前才有这样的想法。而当事人真的来到面前后，修堤的心可以说被大幅搅动。

冻结故乡的森林，依着心情在梅札斯领降下大雪，在现代复活的「魔女」──有着这些传闻的当事人，是怎样的人？

「就跟说过的一样吧。……是个没药救的蠢蛋。」

来到修堤身旁的碧翠丝嘟起嘴唇这么说。

按照刚刚的意见，跟先前的人物评价相比，少了好几根筋的地方甚至变得更多了，不过修堤对此没有任何异议。

「──？」

明明被当成话题中心，爱蜜莉雅却歪头貌似不解。

尤其置身在她所散发的悠闲气氛中，这种感觉就更加强烈了。

12

「客人，请不要误会。关于那场闹剧，拉姆有制止他们别做。因此，那是爱蜜莉雅大人和昴的独断行为。」

以十分冷静的口气再三推托的，是端红茶过来的女仆。

在干道上演的闹剧结束后，修堤和露露拉拉再次被带往爱蜜莉雅住的宅邸。而这位粉红色头发的女仆，为被带到会客室的两人送来热茶。

开头那番话就是随便打过招呼的女仆丢给修堤他们的话。

对方身上有不像区区一介女仆该有的威严，因此修堤也不敢随便回应什么。露露拉拉的画笔没有停歇，继续画着女仆。这也算是对方并不单纯是宅邸佣人的证明吧。

「非、非常犀利的女仆小姐呢……因为爱蜜莉雅大人那个样子，两相比较之下，女仆小姐还比较像魔女呢。」

「……好了。」

「啊，画好了？还是一样这么快呢。……好惊人的魄力。」

露露拉拉画出已经离开会客室的女仆。容貌端庄不用说，连难以用文字表达的压迫感都清楚明瞭地撷取下来。虽然用作报纸插画的可能性低，但却是应当保留下来的一张力作。

就这样，修堤和露露拉拉享受着被款待的片刻时。

「抱歉让你们久等了。因为等昴换好衣服才过来。」

爱蜜莉雅边说边走进会客室。她身后跟着换过衣服的昴，以及牵着昴的手的碧翠丝。

王选候选人，跟首席骑士并肩而立的理想组合。

「可是，碧翠丝大人……」

「呣，贝蒂跟昴是一心同体的关系喔。我们的缘份，是特别到任谁都切不断的。」

「确实如此。撇开玩笑不提，要是跟碧翠子分开太远，我会炸开而死。啊，这段麻烦剪掉不写。因为这姑且算是……我的弱点。」

「剪、剪掉不写……意思是不要说吧。我知道了。」

碧翠丝爬到坐在沙发上的昴的大腿上头，坐在一旁的爱蜜莉雅对此没有任何置喙，代表两人平常的相处模式就是这样。

修堤心想，如果他们平常就这样，那也不需要说什么。尽管昴的口气轻佻，但听得出他没有说谎或是在开玩笑。

接受这点，场子也备好了。修堤重新向他们低头致意。

「再次为各位愿意接受采访表达感激。其他的王选候选人，我们都已经访谈过了……」

「嗯，有听说。所以我们是最后一组啰？」

「是的。采访的顺序没有任何用意，希望不会造成误会──」

本来要说明采访计划的经过，但说到这儿却打住了。

因为被眼前的光景给吸引了心神。

「──首先，谢谢你们特地来问我。能够跟想正经问事情的人说上话，我也很高兴。还请多多指教。」

「──」

说完，坐在对面的爱蜜莉雅也深深低头致意。

连身边的昴，别说劝谏爱蜜莉雅了，反而是跟着一起低头。

其他王选候选人都是比较积极，基于好意接受采访的。但是带着感谢低头致意，这还是头一遭。

与其说这证明了爱蜜莉雅阵营的规矩或礼仪较佳，不如说是清楚展示出他们置身的状况之恶劣，以及世人先入为主的观念有多深。

也就是说，能够接受正经的采访，对爱蜜莉雅来说是个例外。

「爱蜜莉雅大人……」

「是，什么事？」

「爱蜜莉雅大人，为什么会参与王选呢？」

回过神来，修堤已经脱口这么问了。

对刚刚尽完礼仪后才接受采访的爱蜜莉雅而言，这也许是个直率到失礼的问题。

修堤这个提问的意图，不用想也很清楚。──有着半妖精身份的爱蜜莉雅，所处的状况相当恶劣。

虽然说是王选候选人，但任谁看来都觉得败相浓厚。连现在要接受这么年轻又没有什么实际成绩的黄毛小子的采访，都必须要低头表达感谢。

几乎没有胜算，可是为什么还要挑战？

修堤的问题里头，这种意图应该显而易见。

但是──

「──一开始，我没有想得很深入。」

然而回答的爱蜜莉雅不仅没有生气，嘴唇甚至还漾出微笑。

在屏息的修堤面前，她手贴自己胸膛，像在回想刚刚说的「一开始」而眯起蓝紫双眸。

「我原本在森林生活，有一天，罗兹瓦尔来接我。那时我才第一次听说了王选的事，以及国家失去所有国王继承人的事……一开始，我不知道自己能否胜任那么伟大的职务，单纯是基于自私的理由才接受的。」

「请问自私的理由是？」

「跟家人有关。所以完全不是为了王国或旁人。」

稍微吐舌后，爱蜜莉雅害臊地回答。如此直接的回答，在听者听来，肯定会给她的王选之路带来坏影响吧。

明明可以挑剔她的理由多不胜数，甚至多到已经没有挑剔的机会了。

然而，那是肤浅者的看法，从她刚刚的说法可以推测出还有后续。

「也就是说，您现在的想法不同了？」

「嗯。……不只旁边的昴跟碧翠丝，拉姆、奥托、嘉飞尔、法兰黛莉卡、佩特拉酱和琉兹小姐，还有罗兹瓦尔也是，都对这样的我抱有期待，因为有这些人愿意推着不可靠的我前进。」

回答的同时，爱蜜莉雅贴在胸前的手指碰触了挂在脖子上的结晶石。修堤这才初次注意到这东西的存在。

她怜爱有加地抚摸龟裂、失去光芒的结晶石。

「大家都对我很好，所以我用我的方式做了很多功课，我知道我的立场危险到让修堤你们很担心。但是……」

「──」

「但是，我不想拿这当作放弃的理由。我是怎么出生、怎么长大、怎么思考的，我想努力让大家看清楚。」

「──」

「我想让我，和我以外的某些人，想做什么，或想成为什么人的时候，不会被人阻挠。我现在，是这么想的。」

蓝紫双眼笔直地凝视修堤，坚定地这么说。

爱蜜莉雅用不甚流畅的句子诉说了决心。修堤睁大眼睛，于此同时，对自己心中的偏见感到可耻。

想要尽可能公平、不带先入为主的观念来接触她。即使内心这么想，可还是无法跳脱僵固的思维。

既是半妖精，又有着银发和蓝紫瞳孔的爱蜜莉雅，至今应该体验到了超乎自己想像的偏见、先入为主、令人难以置信的障碍才对。可是她却不会过度悲叹这些遭遇，甚至还加以咬碎。

咬碎、咀嚼后，作为自己抬起头的理由。──除了自己以外，也有尝到相同痛苦、受到没道理批判的人。她想成为那些人的同伴，挺身应战。

要把人嵌进某个框架来鄙视，这种条件要多少就有多少。

甚至不必是外貌特征跟过去差点毁灭世界的「嫉妒魔女」一模一样这么夸张的理由。只要生长在有事故的土地上，亲人是罪犯，或单纯出身贫穷，就很容易被烙上「弱者」的印记。

而人类对于「弱者」，可是惊世骇俗地残酷。

明明在贫民窟长大的修堤，对这种事是再清楚不过了。

「那么，爱蜜莉雅大人的意思是这样吗？要拯救我们？」

这是作为「弱者」的代表，由修堤提出的狡猾问题。

在前一刻还表现出一副跟挑战王选的爱蜜莉雅毫无瓜葛的外人嘴脸，但在她高举救赎大旗后却第一个跑过去投靠，这是多么无耻的行径。

要是爱蜜莉雅正面肯定的话，会变怎样呢？

不管如何，这个场合下的答案，修堤都无从得知。原因在于──

「可以成为某人的助力的话，我想帮忙。但是，拯救某人这种大事，我没法承诺，也认为不可以说出口。」

「──」

「如果某样东西有两个人想要，要是那东西是可以分开来给的，那就还好；可如果不是的话，就只能有一方得到吧？没法两边都帮到。」

「那么，我们要怎么做才能被拯救呢？」

「这个嘛……绝对不是提供帮助。可是，我认为，想要却不能说出口，或没法参与这场竞争是很奇怪的。所以，我不会让那种事发生。」

「──」

「嗯，没错。我一定是想要留下可能性。任何人都能得到公平机会的可能性。」

面对修堤像寻求救命绳索的问话，爱蜜莉雅似在确认般点头。

这是她一度在心中整理过后，吐露出的话语。她没有要撤回说出的话，而是用直接的答案回覆修堤的提问。

听完，修堤静静地改写对爱蜜莉雅的印象。然后，点头的爱蜜莉雅身旁──

「爱、爱蜜莉雅酱变得好棒……」

「讨厌！昴！不要用贝蒂的领子擦眼泪啦！」

「笨蛋，我擦的不是眼泪啦。是鼻水……哇喔！？」

「感觉更恶心了！！」

感动到拿碧翠丝的礼服擦眼角和鼻子的昴，吃了碧翠丝的头锤。

首席骑士及其跟班糟蹋了气氛，不过正好。听完爱蜜莉雅的话后，现在也想听听首席骑士的说法。

「菜月•昴殿下，请问您为何要担任爱蜜莉雅大人的首席骑士？您也是受爱蜜莉雅大人的理念所感召的吗？」

「我？……要说契机的话，是别有企图。」

「别、别有企图……？」

竖起大拇指的昴毫不愧疚地这样回答。出人意料的答案让修堤圆睁眼珠，碧翠丝也摇头叹气。

但是她却没有要订正昴的话，或是要他闭嘴。

「虽然只是在巷子里瞥到了一眼，不过我就是在那样的状况下对她一见钟情了。之后为了帮上她的忙而一股脑地奔波，不知不觉就……」

「就爬上了现在的位置？可、可是，昴殿下打败了白鲸和『怠惰』吧？」

「那也是为了对喜欢的女生耍帅的一环啦。」

用手指搔脸的昴笑得很腼腆。不觉得他在说谎，也不像是开玩笑。也就是说，昴之所以成为首席骑士，并累积了几件名留青史的功勋，原动力全都来自于对爱蜜莉雅的恋慕之心──

「您没有被爱蜜莉雅大人的外表给吓到吗？」

「有啊，可爱到被吓到呢。就算到了现在，好比早上的时候，如果没有做好心理准备，看到她的话还是会被吓到。」

「真是的，你又这样乱开玩笑了。」

爱蜜莉雅边说边伸出手，轻拉昴的耳朵。面对苦笑着「好痛好痛」喊疼的骑士，微微羞红脸颊的爱蜜莉雅说：

「刚刚的恶劣玩笑，还请不要写进报导。因为昴马上就会得意忘形。」

「以牵制情敌这意义来说，我认为写出来比较好……啊，不过这次的目的是提升爱蜜莉雅酱的形象，所以跟我晒恩爱的话不好吧？」

（插图010）

「没有晒恩爱。还有，我不记得有救过昴……」

「关于这件事，要是细说的话，我的心脏会被折磨……」

被捏耳朵的昴如此辩驳，爱蜜莉雅嘟起嘴唇表达不满。昴腿上的碧翠丝一脸厌烦地看着他们的互动。

跟被吓傻的气氛不同，修堤内心受到冲击。于此同时，因心焦而用力握紧拳头。

幸好自己有在现场听到爱蜜莉雅表达想法。这么想的同时，也冒出另一个想法。

──为什么，在场的是自己呢？

「──」

爱蜜莉雅认真表达自己的想法，她的话确实打动了修堤的心。不夸张，他可以点头认同那是很棒的决心、想法和觉悟。

但是这终究是直接跟爱蜜莉雅交谈，亲身感受她的声音和眼神后才有的冲击。

要将相同的东西带给「亲龙报文」的读者，绝非易事。

而且原因不是出在爱蜜莉雅，而是修堤能力不足。

假如修堤的文采优秀到能够把所见所闻完全传达给阅报读者的话，就用不着这么苦恼了。

但是很遗憾的，现在的修堤没有这样的能力。假如要说谁写得出来，以前还在跑新闻的摩根总编辑或许有可能。

自己的能力不足，无法完整传达正确情报。这可以说是记者最害怕的事了吧。而且严重到危及记者生涯。

既然如此，修堤•梅根可以做什么呢？

自觉能力不足，即便如此，「亲龙报文」的记者接触到必须传达出去的真实后，要如何──

「──啊。」

在不为人知的情况下被迫站在人生分岔路口的修堤，看向自己身旁专注画画的露露拉拉。

她还是一样没在搭理采访，继续画报导插画。这是她处理工作的方式，修堤也不期待从她身上得到任何掩护或安慰。

露露拉拉就只是专心地观察眼前的光景，然后不断挥动画笔。

瞄了那鲜明描绘的报导插图后，修堤屏息。

然后冲动地从露露拉拉的腿上抢过画本。

「……！」

「抱歉，露露拉拉！让我看看！」

露露拉拉大受打击，简直就像自己的另一半被人突然抢走。她气到一口咬过去，修堤边按住她额头，边翻阅采访开始后──不，跟昴等人在停靠站相遇后所绘制的十几张画作。

看着每一张画，修堤低喃：「哦，果然。」

「这个，爱蜜莉雅大人的表情。」

拿起其中一张，修堤表情柔和地点头。

接着他看向如今依然伸长手想抢回自己工作道具的露露拉拉，从正面抱紧她。

「……呜噫。」

「露露拉拉，谢谢你、谢谢你！多亏了你！多亏了你我看见了光明！果然没有你的话，我根本是个没用的废物！」

修堤感谢惊讶地睁大眼睛，整个人僵住的露露拉拉。

多亏了她，自己看到了突破口。诅咒自己能力不足这点依旧，但真的想要感谢上苍给了自己露露拉拉这样的搭档。

修堤•梅根身为记者该做什么，现在他终于知道了。

「爱蜜莉雅大人，昴殿下！请教两位……不，不只两位，请让我采访每个人！」

「我们？不是要问王选的事吗？」

面对转过头来干劲十足这样说的修堤，爱蜜莉雅歪头不解。昴跟大腿上的碧翠丝也一样歪头，这令人微笑的模样让修堤忍住笑意，用力点头说：「是的！」

已经知道爱蜜莉雅主张的理想与信念。

因此，接下来，为了让自己以外的人都能理解到这点──

「──请先让我喜欢上大家！」

13

「──修堤！修堤！修堤•梅根在吗！！」

大嗓门和豪迈鞋跟声，粗鲁地打开工作室的门。

顿时，房内的文件随风飞起，浸泡在里头的修堤弹起身。弹起身来，环顾四周，看到站在入口的鹰勾鼻身影后大吃一惊。

「呜哇啊，摩根总编辑！在！我在我在我在！修堤•梅根在这里，我在这儿，我醒着！」

「没错，我是『亲龙报文』总编辑摩根•法兰兹总编辑！还有你这个白痴！醒着是当然的！上班的钟声早就响过了！现在可是工作时间！」

「呜噎耶，对不起！」

因为身高差巨大，被正上方的嗓门骂得狗血淋头的修堤连同头上的帽子一起抱紧。在慌乱中驱散睡意，试图整理今天该做的工作──

「奇怪？对不起！我今天应该出去采访是吗！？」

「白痴！你今天放假！完成大案子后的休假。为什么还跑来公司？」

摩根将某样东西塞给已经吓到翻白眼的修堤。东西用力抵在鼻梁上，往后仰的他，终于看清楚这是什么了。

「这、这、这、这是……」

「当然是『亲龙报文』！还有，更准确来说是报导！上头刊载了什么？」

「我写的王选报导！！」

立刻抢过摩根手上的「亲龙报文」──刊登了自己写的报导的报纸，修堤双眼发光，屏住呼吸，整个人腿软。

「动作很多嘛，修堤•梅根！」

「因、因、因、因为……我、我的、我的报导……」

「笨蛋，哪能这样就腿软！我们『亲龙报文』的宗旨是！」

「──！唯有打动心灵的报导，才能刊登！」

连鹰勾鼻都变红的摩根问道，修堤反射性地回答。附带立刻当场起身立正站好。

这样的反应，让摩根边摸鹰勾鼻，边满意点头。

「──是篇好报导。」

「啊……」

「触及每位王选候选人的主张，并着眼于至今无人深入探索的人品，这样的内容令人耳目一新。虽然对于想要深入了解王选动向的人来说还不够……」

说到这儿，他停顿了一会儿，然后用力拍打站得直挺挺的修堤的肩膀。

「但就算是那样的读者，也为最后一句话感到震撼了吧！欲知王选候选人更多的情报，请期待下次采访！……也就是说，你要继续啰？」

「是、是的，我是这么打算的！不过，当然是要得到总编辑的许可……呜呀！」

「白痴！说什么软弱的话！谁可以妨碍你这尝试呢！」

激动的摩根力道过大，修堤不只肩膀，整个人都被打飞出去，就这样刺在文件山里头。然而摩根却瞥都不瞥一眼。

「很好，修堤，就要这么贪婪地咬住！事实上，王选候选人也都礼貌地捎来谢函。以后，访问她们的工作就交给你啰！」

「感、感激不尽……可是，总编辑，这方面的采访……」

「呣……也是，我懂。就交给你和露露拉拉吧！」

重新订正刚刚的话后，摩根像敲墙壁般把报导贴在办公室墙上。接着再次看了一遍报导，然后视线投向房间角落。

「很棒的新闻插图。果然捡你们回来是对的！」

留下这句话，摩根总编辑就大步离开了。

宛如暴风雨一般，会让人感叹，他的人品确实拥有与统辖旗下记者相应的分量。

「唉呀呀，真是敌不过总编……啊，露露拉拉，谢谢你。」

「……没什么。」

露露拉拉费了一番苦战，才把埋在文件山里的修堤拉出来。然后两人爬下山，并肩仰望贴在墙壁上的报导。

──访谈过五名王选候选人，修堤归纳统整所见所闻后写下报导文章，并从露露拉拉的画作中严选出数张刊登。

柔和微笑的库珥修，并肩而立的安娜塔西亚与普莉希拉，让「剑圣」听话的菲鲁特，每张都是热情洋溢的佳作，但其中修堤最喜欢的是──

「……听说反应热烈。」

「哦，是吗。嗯，这样啊。那真是太好了。」

身旁的露露拉拉的话，让修堤自豪地笑了。

受到最热烈回响的画──是爱蜜莉雅与昴，和阵营中的人们聚在一块的团体画。

大家都笑得和蔼，传达出沉稳气氛的画作──修堤不清楚画的价值，却可以断言这是一幅无价的名画。

这一张画，就是这么棒。

「……为何是这张？」

「因为我的能力不足啰。」

「──？」

「我的笔力，无法完整表达出爱蜜莉雅大人的觉悟与决心。读报的观众要接受，心魔太多了。」

先入为主的观念和偏见，这些在爱蜜莉雅的人生中造成诸多妨碍的因素不单对她本人，甚至也会对记述她的文章带来恶劣影响。

可悲的是，修堤的文章没有拂去这些坏影响的能力。

因此，修堤想过。──要怎么做，才能驱散那些妨碍因素？

「那场闹剧真的很过份。不过，我也因此放松了。」

「……闹剧。」

「那么认真地演出，之后还认真地……爱蜜莉雅大人跟『嫉妒魔女』完全是不同人，这个就是我想到的出发点。」

「──」

修堤原本也对爱蜜莉雅有偏见，认为她就是类似「嫉妒魔女」的存在。而一开始打碎这个偏见的，就是在干道上上演的别扭闹剧。

阵营商量的结果，原本的计划是要抹去记者对爱蜜莉雅先入为主的想法，结果却成了演得很烂的闹剧──然而那很重要。

他们认真无比地去进行那种计划。而其中，关键的爱蜜莉雅的本质，正是必须给大多与王选无关的人民知道的事实。

追求公平的她，并非要求大家全面接受、肯定自己的主张。

先入为主和偏见，也是有发挥功用的时候。就跟让人做出错误判断一样，不让人迷失判断，也是有其价值的。

所以，不需要全面袒护爱蜜莉雅。修堤记者的答案就只是诉求公平，认为她的主张有一听的价值，如此而已。

因此，先要让大家知道爱蜜莉雅跟「嫉妒魔女」是不同人。

「所以说，这次的报导主要是让大家知道各个候选人的目标及人品。当然，在之后的后续采访中，会更深入剖析。」

「……之后，要做的事？」

「是喔。一直去见适合被画的那些人，露露拉拉不也会很高兴吗？」

修堤耸肩说，露露拉拉面无表情沉默不语。从那难以看出感情的侧脸读取出里头确实拥有热情后，修堤笑了。

两人扶持相伴很久。──从贫民窟开始，累计超过十年。

要是没有露露拉拉，修堤根本当不了「亲龙报文」的记者吧，会过着更加贫穷的生活，或是老早就死掉了。

用一点都不特别的白色石头，在墙壁上画出大幅画作的露露拉拉──被那幅画的魄力给吸引，认为不能让她在这边走完人生，这种使命感就是驱动修堤的原动力。

说不定，那热情就跟以爱恋为理由而奔波的昴相近。

像这样实际成为记者后，世界上有太多东西都在修堤的背后点火，逼使他东奔西跑。

因此──

「还没呢，未来也一起努力吧，露露拉拉。」

「……没辄。」

「没错，拿我没辄啰。要是少了你，我依然只会是个实习记者。」

修堤边调整帽子的位置，边朝垂下肩膀的露露拉拉笑。

没错，接下来才要开始。

幸运的是，后续的追踪采访因为这次的报导造成的回响极佳，因此也容易跟当事人申请。特别是从爱蜜莉雅阵营那边，获得了很棒的回覆。

首席骑士昴相当看重「亲龙报文」的价值。

关于他，在这次爱蜜莉雅的相关报导中也非常活跃。他足以在历史上留名的诸多功勋也是，不过其中最受关注的是──

「不过，还真没想到会造成这么热烈的回响呢，『幼女使者』。」

「……不生气吗，神奇。」

「我、我想他不会生气吧？」

报导中对于王选候选人的首席骑士，全都给予了与耀眼功劳值得匹配的头衔。因此也想为昴准备符合的称呼，苦思之后，最后给出这个答案。

这道出了昴与碧翠丝的关系──没有她的协助，就无法完成骑士的职务。昴如此断言也占了很大的理由。

于是修堤就为他命名「幼女使者」，结果得到惊人回响。

恐怕从今以后，菜月•昴跟「幼女使者」这个名号，将会是切也切不断的关系。

「怎、怎么办，要是因为这个原因而拒绝采访的话……」

「……事到如今，太迟了。」

「不，话是这么说没错！但现在我不想把这工作让给别人……」

越是冷静思考，越觉得自己挖洞给自己跳，使得整个人血气尽失。看到他开始脸色铁青烦恼的样子，露露拉拉拿起画笔。

然后又用平常的调子，开始描绘修堤的惊慌失措。

「露露拉拉又这样子……原本你就是个只画自己有兴趣的东西的人，为什么却画了好几张我呢！？」

「……为什么咧？」

「不知道啦！拿了好几张自己的画，心情很复杂耶！？」

对方不解外加随兴的态度，让修堤尖起嗓子。

连这段期间，她的画笔都没停歇。

说到底，开头的问题也没解决。

「啊啊，怎么办啦……果然还是带个礼品致歉比较好吧？可要是对方没生气的话就等于自找麻烦……呜哇啊，未来好可怕！」

「……活该。」

「露露拉拉，不是没你的事喔！？」

露露拉拉挥挥手，修堤看了哀号惨叫。

而两人身后堆积如山的文件，都是修堤写过但未经整理的采访内容，这些文件山如今正开始慢慢倾斜。

将来不单露格尼卡王国，势必连邻国都会被牵扯进来、引发纠纷的王选，身为第一位勇敢采访这些核心人物的记者，修堤和露露拉拉的名字将会流传很长一段时间。但──

「哇啊啊──！？」

「……啾呜。」

被崩塌的文件山给活埋，在公司内遇难的两个活宝，目前距离成名还非常遥远，那又是另外一个故事了──。

虽是闲谈，但刊登这篇报导的「亲龙报文」的销售量创下史上第一的纪录，更让众多王国人民引颈期盼下一篇对王选候选人的专题报导。

《完》

** 『Sword Identity』

1

「──开始评鉴。」

沉重肃穆的宣言，响彻整个议场。

声音不大，却具备劈开紧绷空气的力道，严厉敲击齐聚一堂的人的耳膜。这也难怪。

原因无他。声音的主人就是一国之君，遵守弱肉强食法则的帝国之首──神圣佛拉基亚帝国第七十七任皇帝，文森•佛拉基亚本人。

乌溜溜的黑发和凛然的细长双眼，纤细的身体包裹在没有过度华丽装饰的衣着内。黑色瞳孔寄宿着理性光芒，思虑遍及广大帝国的各个角落，因此这名美青年被誉为足智多谋的贤帝。

在这位皇帝的统治下，佛拉基亚帝国迎来建国以来难得的平稳时代。

在他坐上皇帝宝座之后的七年间，是争战不曾根绝的佛拉基亚帝国史上最安宁的日子。百姓对此津津乐道。

但是，为政者的优异手腕，与个性的温和程度不成比例。──这一任的皇帝也跟历代皇帝一样冷酷无情。

这件事众所周知，从议场的气氛就能察觉。

「──」

为了评鉴而聚集到议场的众「将」，以各种形式表达强国佛拉基亚的「武勇」。他们的表情严肃，认真无比，使人无法放松。

众「将」都知道。──不只他人，何况在皇帝面前，只要展现出懦弱的举止，就等同要了自己的性命。

因此，聚集在此、二将以下的「将」们，个个脸上都爬满紧张。

「──虽然有点仓促，不过今天的议题多如山高。」

在充斥着杀气腾腾的紧张感的议会中，紧接在文森之后发言的沙哑声音，给人从容不迫的印象。

宽敞的议会会场中央摆放着长桌，皇帝居于上位，按照惯例，座位越靠近皇帝，就是地位越高的人。

而说话从容的人物，就坐在皇帝的右边──以奇夏•哥尔特驰名，有着白发和粉白皮肤，全身都穿着白色装束的魔人，地位正是皇帝的左右手。

以优秀和胆大的才智谋略为皇帝的治世做出贡献的奇夏，是深受文森信赖的参谋，同时也是佛拉基亚帝国武官顶点「九神将」之一。

佛拉基亚帝国所施行的「将」制度，其最高地位就是一将，而被赐予一将位置的只有九人，奇夏即为其中之一。当然，评鉴上也有传唤其他的「将」，但──

「首先是第一个议题……一将的召集可说是史上最困难，令人困扰的一次。」

事态严重到奇夏拿来当第一个议题。

在帝国最被尊崇的文森，周围的空位格外引人注目。这是帝国一将──「九神将」出席率差的证据。

「这是怎么回事！必须成为将兵们表率的我们却这样，叫我们面对众『将』的时候面子往哪摆！」

「我，严守时间。这是当然。」

一边气急败坏，另一边机械性地表明遗憾。他们分别是填补除了奇夏以外的空位的两名一将──哥兹•拉尔冯和莫古洛•哈葛内。

千锤百炼的军人哥兹，以及出身特殊、被称为钢人的莫古洛，都对皇帝极为忠诚，跟奇夏一样认为出席评鉴是理所当然的义务。

但现实是，参加今天评鉴的一将，仅有三人。

「指挥远征军的葛路比就算了，奥尔巴特翁在搞什么！」

「奥尔巴特翁有交付会缺席的文件。……不过，从一开始就省略掉那两位，看来哥兹一将似乎完全理解了。」

「瑟希鲁斯和亚拉基亚。期待，只会，失望。」

哥兹大骂不在场的同僚，奇夏指出他话中的毛病后苦笑，莫古洛以明智合理的见解予以肯定。

在崇敬强者的佛拉基亚帝国，要获选为「九神将」的条件很简单，只要是勇武兼具的高强实力者就行。为此，跟他国相比，帝国军拥有无伦比的战力，不过越上位者就越不遵照繁文缛节。

像是哥兹完全不期待会出席的前两名──瑟希鲁斯•塞格姆多和亚拉基亚，各自位居「九神将」第一和第二，就是个中翘楚。

不管怎样──

「这些人到底将陛下刻意拨冗召开的评鉴都当成什么了……！」

「──还是一样，就会叽叽喳喳吵闹。」

「陛下……！」

哥兹气到脸红脖子粗时，坐在上位的美青年──文森出言责备。皇帝眯起细长眼睛，望着不在场的「九神将」的座位。

「说起来，根本就不期待这些会出席。即便是沙特兰兹盘，每一种棋子也都有自己移动的法则吧。无视这些随便乱动的话，盘面将会无视棋手的意图而失控。最重要的──」

「──若是要求礼仪品行，陛下就不会恢复九神将制度了。在下是这么解读的。」

「哼。」话说到一半就被人接过去讲，文森轻声喷气。

胆敢打断皇帝的话，做出这种不敬行为的，是坐在文森隔壁──跟坐右边的奇夏相反，坐在左边位置的是一头整齐灰发的高龄男子。

在武官就是讲实力的帝国里，文官出身，且地位仅次于皇帝的要职就是「宰相」，也就是文官的顶点──贝尔斯特兹•彭达冯。

细如闭合的双目深处在进行着各种策略与计算，这位帝国贤人在话中透漏的不满，针对的是对文森忠心耿耿的哥兹。

「宰相，怎能打断陛下的话……」

「万分抱歉。但是，陛下政务繁忙。可以的话，迅速地推进评定会议也是忠臣的职务，这是在下的愚昧想法。」

「您这话的意思是我们妨碍了陛下吗！」

「哥兹一将，不要太激动。陛下的目光变得冷淡，这一看便知。」

「唔……！」

哥兹紧咬贝尔斯特兹抢话的行为，却被老练宰相轻易闪过。

非常遗憾，在唇枪舌战上，两人的等级不同。哥兹虽是身经百战、深受将兵信任的军人，但要发挥真本领果然得在战场上。

而且以何处为战场，端看当事人的气质──真要说的话，奇夏也是比起舞矛冲锋，更适合在战场上动头脑。

「瑟希鲁斯他们，事到如今，没有意义。」

「嗯，正如莫古洛殿下所说。『壹』和『贰』两位的缺席早已计算在内……比起这个，更该进入评定会议的主题。」

「……无妨。奇夏，开始吧。」

最后，被辩倒的哥兹没能挽回颜面，评定会议就开始了。

奇夏吐气，斜瞄几乎要把自己穿着的黄金铠甲的臂甲给握碎的哥兹一眼，同时进入主题。

「那么开始了。」每次评定会议开始之前，都要这样浪费精神。

──这也是现在的神圣佛拉基亚帝国首脑阵营的态度。

2

──「政变」这词汇，频繁地在佛拉基亚帝国史书上登场。

如前所述，以弱肉强食为真理的佛拉基亚，推崇靠力量获取渴望想要的东西。以此获得将兵等地位，或是抢夺心上人，抑或是争夺累积的财富，可以举的例子多不胜数。

当然，既然允许所有靠武力掠夺的行径，那已然是无法地带。

现在的皇帝，以贤帝闻名的文森•佛拉基亚在整个帝国推行法律，彻底强调和规范力量的使用和展示方式，并进行土地均分。

结果就是，无分强者弱者，多数帝国人民都受到其恩惠，每个人都不容易死亡，形塑出容易生存的时代。

不过要是以为造就太平盛世的文森是慈悲为怀的皇帝，那可就大错特错。

『──纵使国旗上高揭剑狼，但狼也有优劣之分。没有个体差异，群体就无法成立。然而，砍掉威胁到群体的恶性个体杀鸡儆猴，还是有其必要。』

这正是文森的方针，也是改变帝国型态的目的。

巧妙引导棋盘走向自己所想的布局，就是文森的执政法。为此，不惜扭曲、践踏帝国礼仪或古老传统。

以某种意义来说，最没有佛拉基亚皇帝风范的他，又最有佛拉基亚皇帝风范。

这是在文森就任皇帝后的七年──佛拉基亚帝国迎来建国之后的首次平稳时代。因此，也跟「政变」这词汇无缘。

文森•佛拉基亚的统治开始后，遇到足以被称之为「政变」的事态，除去继承皇位后，便仅有一次。

那就是──

「──必须填补上九神将的空缺。」

评定会议顺利进行，在消化掉几个议案时，奇夏触及这个话题。

顿时，议场的气氛急速冷却紧绷。

哥兹的眉心就像在岩石上刻下皱纹，连看不出表情的莫古洛散发的氛围都有变化。二将以下没有座位的「将」也都紧张兮兮，没有任何反应的除了奇夏外，就只有文森和贝尔斯特兹两人。

──武官的顶点「九神将」空缺，是绝不能发生的状况。

强大，是「九神将」唯一被要求的条件，意味着身居此位之人不得败北。而之所以会出现空缺，原因除了败死，别无其他。

而且原本排名「玖」的人物，不单单仅因败死才空出位置。

「要不是巴尔罗伊那家伙做出蠢事……」

哥兹抱起粗臂，表情苦涩地说。没人接他的话是因为没人打算纠正，并且大家藏在心中的想法都一样。

──巴尔罗伊•特梅格里夫。他正是原本居于「玖」的一将，更是在佛拉基亚帝国发动最新「政变」的主要人物之一。

牵连邻国使者的谋反，目标是文森的性命。这是文森的治世开始以来最严重的政变。结果是文森遭受濒死重伤，主谋和执行犯巴尔罗伊被处刑，政变告终。

这是大约两个月前的事，在那之后，「九神将」就一直空着一个席次。

既然文森已经身体无恙，可以继续执政，那就不能一直让一将的席次空缺。所以才会有这个提议。

「也为了警告其他三国，是该稍微考虑了。」

在鸦雀无声的议场中，奇夏抛砖引玉。

所有人的目光焦点，当然就是文森。承受视线的同时，文森正经地瞥了那空位一眼。

原本巴尔罗伊•特梅格里夫一派轻松坐着的空位。

「陛下。」

「无妨。余可没空闲关心死人。尽快推出人选。」

「遵命。感激陛下的批准。」

黑瞳眯起的瞬间，是文森的饯别。

接到指示的奇夏行礼，感谢皇帝的判断。接着转向不高兴地抱着手的哥兹。

「哥兹一将意下如何？是否有符合您目光的『将』呢？」

「嗯，这个嘛……假如是长于军略的人选，是有几个备案；但要说可以就任九神将之位的话，就是卡夫马•依鲁鲁库斯二将了吧。」

「卡夫马二将是吗。」

与众「将」有广泛交流的哥兹，端出的名字当然也是奇夏知道的人物。

卡夫马•依鲁鲁库斯不仅是年纪轻轻就爬上二将之位的奇才，身份更是连境内有各式各样种族的佛拉基亚帝国都少见的「虫笼族」。

虫笼族会在体内饲养被称为「虫」的寄生体，自幼开始操纵，战斗时就能借用虫的能力，是一种很特殊的技术。

但若要说有什么问题──

「卡夫马一族，跟巴尔罗伊，共谋。」

「如莫古洛一将所言，卡夫马二将因该事而在闭门反省吧？」

先前提及的巴尔罗伊发动的谋反，在参与策划的人当中也有虫笼族，而且还是卡夫马出身的部族。尽管他本人与谋反无关，但因为许多族人参战，所以他也被连坐拘留。

「要说他能补上九神将的空位，实在是不得不存疑呢。」

「所以这正是他挽回信誉的机会啊！他本人也对族人参与谋反一事感到有责任！这样下去他有可能会自裁。」

「唔嗯……」

「陛下！臣知僭越，但请容臣谏言！卡夫马•依鲁鲁库斯对陛下忠心耿耿，是个失去会惋惜的人才！请陛下给予宽容判断！」

踢开椅子站起来的哥兹，手撑桌面，身子前倾直言极谏。

其他人这么做可能会让人控诉态度不敬至极，但哥兹•拉尔冯眼中和心头点亮的只有忠义与义愤填膺。

「陛下！」

「不要大叫，凡夫。你的音量本来就大得莫名。用不着往前弯，声音也早就不限议场，响遍城内了。」

因此，除了音量大以外，文森也没多加责备。

对这谴责，哥兹大声谢罪。

「万分抱歉！但是！请您重新考虑！欠缺的九神将席次，忠诚笃厚之『将』的未来，这两个问题都能够一举解决！」

「──。奇夏。」

「是。容小的表达意见。我认为哥兹一将的提议不错。」

文森征求意见，奇夏边摸自己的尖下巴，边这么回应。

尽管故乡的同胞做了坏事，但卡夫马•依鲁鲁库斯的武勇功勋，奇夏也是知道的。哥兹说得对，失去优秀的「将」对帝国来说是伤害。

更何况，帝国已经失去了巴尔罗伊•特梅克里夫。

因先前的事而跟露格尼卡王国签订了休战条约，为期三年，但以后的事没人说得准。

无论何时，帝国都不可能容许国力被削弱。

「我想卡夫马二将本人也有自己的想法，但被荐举为九神将还拒绝的人，放眼整个帝国应该找不到吧。」

「呵。不愧是不情不愿坐上位置的人，说起来的说服力就是不一样。」

「……见笑了。因为小的早已放弃。」

耸肩应对皇帝的挖苦，奇夏平静自嘲。

假如卡夫马没有打算成为一将的志向还被荐举，那实在令人感到非常同情。同类增加了，奇夏会很高兴吧。

奇夏本人就认为，被赋予「九神将」这种沉重职位是一种负担。他觉得比起武官，自己更适合担任文官。

不管怎样，既然奇夏持肯定态度，文森的担忧也获得解决。接下来荐举卡夫马的话题应该也就到此为止了。

但是──

「──陛下，在下也有想要推荐的人才。」

「你说什么！？」

这话在议场空气中掀起剧烈震荡。发言的人是贝尔斯特兹。

眼睛眯得像条线，不让人窥见内心的帝国宰相所说的话，对哥兹来说简直就像是杀出个程咬金，因此哥兹怒视对方。

「你是打算怎样，宰相！身为文官的你，竟然对武官而且还是一将的任命插嘴！」

「尽管惶恐，但还是要说，在下的职位是宰相……负有为了使帝国更加美好而努力，为此粉身碎骨在所不惜的义务。因此，请容在下斗胆提出意见。」

「真是大胆的发言。就当作你有与发言同等的觉悟吧。」

怒上心头的哥兹，面对贝尔斯特兹冷静的应对也平静地高涨敌意。那是肉食野兽面对猎物的集中力，「狮子骑士」哥兹•拉尔冯斗争心的显现。

就这样，还以为议场的空气将无可避免地一触即发时──

「住口，凡夫。你愤怒的声音又更吵了。」

为这场互动喊停的不是他人，正是文森。一声令下，哥兹也只能忍气吞声，文森则是看向贝尔斯特兹。

「贝尔斯特兹，你说你有想要推荐的人选？说来听听。」

「陛下！请再考虑……」

「余说过住口了吧。」

被重复要求闭嘴的哥兹涨红着脸，乖乖沉默。

经过这段插曲后，贝尔斯特兹点头道。

「感谢陛下宽大的判断，容在下献上敬意。」

「闭嘴。你也别让我再说第三次。快说。」

「遵命。在下想推荐的人物，名叫玛德琳•恩夏尔德。」

被催促的贝尔斯特兹抓住机会道出名字，文森听了微微皱眉。那是他难得的惊讶，虽然对其他人来说是十分微小的反应。

现场的奇夏、哥兹和出席的众多「将」们，全都面露诧异。

原因在于──

「我，没听过。宰相，那是谁？」

众人所抱持的疑问，由话很少的莫古洛代为问了出口。

发言机会少，讲话又断断续续的他，对评定会议的理解力绝不低下。他可以冷静地俯瞰状况后再开口，是一将少有的智者。

而面对莫古洛这理所当然的问题，贝尔斯特兹抚摸蓄在鼻下的胡须，道：

「会惊讶也是在所难免。玛德琳•恩夏尔德……她并非帝国军。没有从军经验，也没有率领军团立下功劳过。」

「这样子……根本上了不台面。」

「──不成体统！！」

荐举者明言大家不可能听过，奇夏接受这个事实，而被文森命令安静的哥兹则是忍不住骂出声。

但只有这次无人责备哥兹。议场内所有的「将」，包含一将在内，全都对贝尔斯特兹的想法感到疑惑。

没有从军经验，也没有率团立下汗马功劳，也就是说，是个没有建立过成果的人才。──谁会去理睬这种推荐啊。

「这是在愚弄我们帝国军的名誉吗！」

「岂敢。在下应该说过，身为帝国宰相，就应思考国家未来并给予意见。那话绝无虚假。」

「你哪张嘴敢说这种话……」

「慢着。」

额冒青筋、情绪即将爆发的哥兹，再度被文森制止。

肘靠椅子扶手、拄着脸颊的文森，以测试的目光看向贝尔斯特兹。在这视线注视下，宰相毫不胆怯地呼唤主君。

「陛下，容臣重申，在下绝无任何企图，或是有任何轻视九神将的意思。在下确信，玛德琳•恩夏尔德绝对是符合陛下想法的人才。」

「少随便开口就说什么确信。那东西会什么？」

「──操纵飞龙。」

「──」

顿时，这答案让议场的气氛整个冻结。

多不要命的发言，出言者却近在身旁，连奇夏也忍不住倒抽一口气。

使唤凶猛飞龙的「操飞龙」技术，是佛拉基亚特有的技术。要运用这技术使飞龙服从，必须要有才能和长久的钻研，方能成为飞龙骑手。这种人才极少，所以被视为珍宝。──但是，问题不在那儿。

问题在于，发动谋反的巴尔罗伊•特梅克里夫，也是飞龙骑手。

由死掉的巴尔罗伊留下的位置，竟然又推荐同为飞龙骑手的人选。

先不论有无意图，这样的荐举只能想做是挑衅行为。众「将」愕然失声，连文森都接不上话也是正常的。

到底在想什么？哥兹的怒火即将喷发。

但是──

「因为是你，余不认为会推举一个飞龙骑手来代替原本的飞龙骑手。」

「正是，谢陛下慧眼。当然，在下也认为，一介飞龙骑手──尽管这是贵重的技能，但光是这样仍不足以胜任九神将之位。而且──」

「什么事？」

「容臣订正一件事。──在下没有说过玛德琳•恩夏尔德是飞龙骑手。在下说的是，她会操纵飞龙。」

这样回答完皇帝的疑问后，宰相满是皱纹的脸庞浮现看不见真意的笑容。

两者之间鼓胀的紧绷感，是每次评定会议的必经过程。心怀鬼胎的贝尔斯特兹是不能大意的对手，但他还是坐上了宰相位置，足见其多有才干。

──只要有能力就拔擢运用，借此构成想要的棋局。

自身武勇并不出类拔萃的文森之所以能治理剑狼之国佛拉基亚帝国，用的就是这个宗旨。

因此，这次文森也了无遗憾地施展自己的手腕。

「──传卡夫马•依鲁鲁库斯，和玛德琳•恩夏尔德两人。」

「……这没问题，但真的好吗？」

「无妨。卡夫马的力量早已有所掌握。既然如此，也必须看清玛德琳。要是不合余的目光，就意味贝尔斯特兹老糊涂了。余可没慈悲到为老而无用之辈准备席次。懂吗？」

「臣明白，陛下。」

被无情目光注视，贝尔斯特兹却不显畏惧，反而行礼。

并不是期待文森的慈悲，或是看轻对方。是对自己的眼光有绝对的自信吗？无论如何──

「操纵飞龙……那又怎样！卡夫马也会操纵虫啊！」

「哥兹，那个，不重要。我，认为。」

「用不着仰赖飞龙，虫也可以运送陛下！不是吗，莫古洛！」

「没错。只是，我，讨厌虫。」

贝尔斯特兹的意见被采纳，莫古洛要烦躁不耐的哥兹冷静。

瞥了他们一眼，奇夏在心中替换政务的优先顺序，并思索后续事项。

「先前谋反的事终于告一段落，但还是要考量未来呢。」

有预感将要辛劳起来的奇夏敲敲肩膀，姑且先接受了当前讨论出的结论。

之后要跟哥兹打声招呼，还必须探寻贝尔斯特兹的想法等等。要是期待文森会处理这些事，以认识他很久的忠臣来说，未免太虚假了。

毕竟，文森已经十二万分地在履行自己的职责了。

「……唯有强者可自由挥洒自我的帝国，却强迫位居顶点的『皇帝』不能自由，怎么想都觉得讽刺。」

而且这也是他求仁得仁的立场，所以才会觉得棘手。

要是认真抗拒的话，逃跑的方法要多少都有。事实上，自己对真的逃离了不自由的鸟笼的人心里有数──

「──啊～啊，大家都集合了呀。偶真是～太失礼了。」

就在评定会议要收尾前，议场入口被打开，同时有人这样说。

轻轻摇晃留有紧迫感的气氛，踩进议会的身穿蓝色长袍的温文尔雅男子。把帽兜拉到看不清眼睛的他，跟聚集众武官的议场十分不协调。

「──是『观星者』殿下啊。究竟有什么事，让您亲自跑这一趟？」

「没～事没事。没想到你们正在进行评定会议。唉呀，承蒙陛下好意把偶摆在水晶宫，但是任何派系都讨厌偶呢。」

嘻皮笑脸、不受欢迎的男子──「观星者」态度轻薄地回答。「这样啊。」面对这没法有效应付的态度，奇夏也只能若无其事地这样回应。

──所谓的「观星者」既不是帝国武官的「将」，也不是贝尔斯特兹那样的文官。是文武百官中的异类，也是水晶宫当中立场独一无二的人。

包含奇夏在内，在场所有人都不欢迎他，但──

「可不记得有叫你，丑角。」

这样称呼他却又没打算疏远，基于皇帝这样的态度，才允许他留在水晶宫。

丝毫不介意周遭的警戒与厌恶眼神，「观星者」的注意力只投向文森。对此皇帝嗤之以鼻，轻轻挥手道：

（插图011）

「正在开评定会议。没你出场的份。快点消失。」

「当～然，偶啊～自认了解自己的立场喔。因为陛下慈悲才得以留下，所～以说，不完成职责可说不过去。」

「──」

听了这不要命的抗辩，文森眉头略为上扬。同时，奇夏和其他「将」也全都一僵。

──没有人对这位「观星者」有好感，也不信任他。

但是如果是「观星者」带来的预言，那就另当别论了。

「没看出巴尔罗伊要造反的你，如今想说你看到了什么？这次要是不能说出有益的东西，你脑袋和身体就要分家了。」

「请不要讲那么可怕的话嘛。偶啊～就跟外表一样，跟碎木片一样弱不禁风哟～。被这样威胁，会害怕到说不出话的。」

「够了，少耍嘴皮子！陛下要你回答！就快点回答！！」

被文森威胁，又被哥兹破口大骂的「观星者」隔着帽兜抓抓头后，苦笑道。

「哎哟喂呀，看样子，偶啊～很不受欢迎呢。因～此呢，偶会按照吩咐回答，不过陛下，若是有任何烦恼，好像马～上都能解开烦忧耶。」

「──。什么意思？」

「意思是，如果在比较某些优劣的话，大好时机将会降临。每次都讲得这么含糊实在～诚惶诚恐，但是偶啊，可以说的顶多只有这样……」

「这样啊。莫古洛，把手变尖。」

「明白。」

面对歪过头去的「观星者」这番发言，文森点头后这样命令莫古洛。

莫古洛按照指示，举起又长又大的手，接着宛如矿石平滑的手逐渐变形，变得越来越像长枪枪头一样尖锐。

奇夏也知道，莫古洛变成那样的手锋利得宛如刀剑。连石墙都可以轻易切开的手，就算十个「观星者」的脖子也能一口气削下。

「陛下！？莫非～偶要被处刑了！？」

「蠢货，哪有可能。──先从手指开始。」

「拷问出来的情报没有价值，这不是陛下的想法吗！？」

「像你这种不讲关键的家伙，重要的在于先让你肯开口，等你说完后再仔细审查内容就好了。不是吗？」

文森残酷又合理的判断，让「观星者」忍不住后退，直到撞上墙壁。而身高超过三公尺的莫古洛，不断逼近「观星者」。

在这样的压迫感下，「观星者」左顾右盼，期待救援。

「呼嗯，可不能让血弄脏议场呢。来人，去拿垫布来！」

然而，以将拷问当成既定事项的哥兹为首，无人有意伸出援手。想当然耳，奇夏也是。他没有忤逆文森、站在「观星者」这边的理由。

就这样，在「观星者」的指头即将变得比一般人短少的时候──

「──会议中打扰，万分失礼！但有必须报告的事！」

没错，在「观星者」之后，是传令兵冲进议会会场，中止了即将发生的血腥事态。

3

眼前有白色和黄色的蝴蝶在飞舞。

「──」

呆呆地看着以不规则的动作拍打翅膀的蝴蝶，同时思索这两只蝴蝶有什么关系。

不深思熟虑，直觉思考的话，是家人吧。可是颜色一白一黄的蝴蝶，有什么血缘关系呢？就像人类的头发颜色一样，也是各自继承了来自双亲的特征吗？

「可是，蝴蝶基本上都是品种相同的才会交尾。」

若是人类和亚人，因为语言相通且外型相似，如果双方萌生爱意的话，也是有诞下子嗣的例子。不过很不可思议的，没印象蝴蝶之间会跟不同品种交配。

就像鸟也只会跟同一种类的鸟交配，不会跟不同品种的鸟生下小孩。

「奇怪……可是猫跟狗就不是这样……是我想太多了吗？」

突然产生疑问而歪头思索，但不管想多久都得不出答案，于是干脆抛弃了这难题。只是想是没用的。那么这两只蝴蝶如果不是家人，而是宿敌的话又如何？

一安上这样的设定，以不规则动作替换彼此位置的蝶舞，看起来就变得像是寸步不让的赌命攻防。真是不可思议。也对蝴蝶所用的战技兴致盎然。

「这么说来，虫笼族的人好像可以跟自己的虫沟通，不知道有没有人养蝴蝶呢。有的话，我的烦恼就可以畅快解决了。」

基本上，虫笼族养在体内的虫以攻击性的居多，但假如有不是杀人，而是使用杀虫武术的蝴蝶的话，不也可以被列在强者的框架内吗？

干脆再拉近距离观察，说不定就能看见什么──

──刹那间，头上倒下鲜红火焰，转眼间烧光花海。

「──」

方才的田野光景消逝无踪，被火舌舔过的花草化为灰烬。

原本以蓝、绿、黄等柔和色调彩绘的世界，都被红色全部吞没覆盖，化为宛如地狱的惨状。

不只花草，以蝴蝶为首的各种昆虫与生物，都在一瞬间成灰了吧。

而做出这种事的人是──

「还是一样，打招呼很粗鲁呢。」

望着被烧掉的花海，蓝发青年耸肩。他的视线尽头是站在燃烧的花田正中央、不把灼热火焰当一回事的半裸少女。

大量裸露咖啡色肌肤的装扮，下垂的犬耳和银色头发，以眼罩盖住左眼都是吸睛的特征。美丽的少女正是烧毁花海的元凶。

站在火中的半裸少女，名字是──

「──阿妮亚。」

「……不对，是亚拉基亚。不要让我说那么多遍。」

被唤作「阿妮亚」就立刻面露不悦的少女──亚拉基亚反驳。

面对答案，被回嘴的青年摇摇头。

「没有啦。不好意思，应该是很小的时候就有的绰号吧？事到如今就算要订正，也已经习惯嘴巴怎么动了。」

「我从很久、很久以前，就一直在说了……！」

「好啦好啦，我知道啦。所以我也很久以前就一直在说啦。──阿妮亚要是赢过我，就会仔细重说一遍的。然而～」

「然而？」

「然而你却一直没赢过我，这不是阿妮亚的错吗？讲得像是我的错，那我也只能说对不起我太强啰？」

闭上一只眼睛，他露出一个充满恶作剧意图的微笑。亚拉基亚的表情被怒意渲染，细瘦的身体溢出连大气都畏惧的战意。

见状，青年张开原本抱在胸前的双手。

「唉呀呀。好啦，这里很危险，快走开。」

「……蝴蝶？」

张开的掌心飞起了一对白色与黄色的蝴蝶。

在亚拉基亚跟着火焰冲过来的时候，立刻用手包覆，加以保护的那一对蝴蝶。要是见死不救，它们现在就会跟花草一起被烧成灰了吧。

「难得的一对一决斗，却被人从旁干涉而糟蹋，搞得兴致全无。如果认为我对你们有恩的话，那一定要回来跟我报告是谁赢了喔……」

两只蝴蝶的对决，以及触发这场战斗的起因。那些一定是听了会很快乐的故事。青年的兴趣与好奇无穷无尽。

可是似乎很难听到后续了。青年切开逼近的火球后叹气。

「阿妮亚真的是从小就缺乏情感呢。」

「我本来就不叫阿妮亚。」

「真敢说呢。甚至可以引以为傲也没关系喔？」

展示切开灼热火球的刀身，同时对亚拉基亚笑。青年的笑容和说的话让亚拉基亚微微皱眉，他因对方的洞察力之差露出更深的笑容。

明明都已经说过无数次了吧。

「毕竟这是身为这个世界的主角、红牌演员的我──瑟希鲁斯•塞格姆多直接为你取的绰号。你可以大声说出来，自夸自己叫做阿妮亚喔！」

「瑟希鲁斯，我要杀了你。」

「哈哈哈哈！你又在说办不到的事了！」

对单方面的杀意一笑置之，面对以凶猛气势倾泻而来的破坏奔流，青年──瑟希鲁斯•塞格姆多毫不畏惧，猛然蹬地冲过去。

一边，是仰仗挂在腰部的两把刀切割破坏的不正常剑客。

一边，是能自由操纵大自然、扭曲世界原有形貌，超脱常人的美女。

──他们，就是佛拉基亚帝国「九神将」的「壹」和「贰」。

4

「唉呀～阿妮亚，你变强了耶！看，我的和服到处都有焦痕！这个要从卡拉拉基寄过来，可要费一番功夫耶！」

「哈吁、哈吁……」

「所以说，又要跟平常一样麻烦你善后啦！自己弄破烧掉的东西就自己修好，不准有意见喔！」

「……瑟希鲁斯，去死。」

在烧毁的原野上呈大字形躺下的亚拉基亚口吐诅咒之语，但被诅咒的当事人却一副浑然不知的嘴脸。

都充分领会过想必比诅咒更有效果的敌意与杀意了，却依旧处之泰然，因此诅咒的话语根本就不算什么。

「说起来，『去死』啦、『下地狱』啦这种低级台词，建议不要说比较好。这样会降低自己扮演的角色的价值，很容易沦为无趣配角喔。」

「……又在、讲些、听不懂的话。」

「我是不觉得有那么难懂啦。大人物本来就只会讲有份量的话。小人物就只会讲小家子气的话。世界万物都是这样运行的，所以反过来说，可以讲出帅气话的人就是帅气的人！」

瑟希鲁斯竖起手指阐述自身哲学。盘腿坐在亚拉基亚旁边的他，衣服处处都被黑灰弄脏，但人却没有醒目的外伤。

周遭附近简直就像被魔石炮地毯式轰炸过，一片荒芜。看到的人根本不会相信他刚刚人就在爆炸区的正中央跑来跑去。

「我啊，要是拿出真本事的话，连雨都躲得开喔。」

「……再怎么快，都办不到。」

「我～说～啊！要不要办到是看我自己来决定。认为办不到的事就做不到。以为做不到的时候，就连云都斩不了。」

微弱的反驳被十倍奉还，瑟希鲁斯坐着拔出腰际的刀。

连声音都被抛下、宛如闪电的动作，从刀刃放出的剑压飞向天空，将两人头上厚重的云朵给砍成两半。

目睹这光景，亚拉基亚的红色单眼不禁动摇。

「──云切。」

「还好啦，就只是亮出来吓吓人的招式。不过，如果一直哇哇叫说碰不到云然后这样那样的，那就永远碰不到云啰。」

「──」

「所以，阿妮亚也别说什么要杀我还是去死的，专注在自己的目的上比较好喔。──你有目标吧？」

他观察躺在身旁的脸蛋；犹如抗拒他的视线般，亚拉基亚背过脸。结果因为更想看清楚而换角度观察，最后对方干脆趴在地上，把脸藏起来。

与其跟瑟希鲁斯对看，宁可选择与土地接吻，这极端的态度叫人傻眼却也微笑。

──从旁看来，这是只会给别人造成麻烦的「九神将」成员的冲突。

瑟希鲁斯和亚拉基亚之间频繁发生冲突，但目的简单明瞭，就是排序。「九神将」的数字越小代表越强，身为「贰」的亚拉基亚上头是瑟希鲁斯──也就是说，亚拉基亚想要「壹」的位置。

据说获得那位置，就能完成她想要完成的悲愿。

「我会帮阿妮亚加油，希望你愿望实现。不过我不会放水的。」

「……我果然、讨厌你。」

「唉呀～很常被这样讲。不过我没那么讨厌我自己，不如说是喜欢。」

瑟希鲁斯边说边脱下披着的和服外套，轻轻盖在躺着的亚拉基亚身上。

被她讨厌是早就知道的事，但战斗中实在没法去顾虑衣着方面。原本的轻薄衣衫就已经不知道该把视线往哪摆，要是不遮住的话，旁人就太可怜了。

「难得是个美人胚子，阿妮亚却毫无体贴可言呢。要是起了怪念头的人们反而遭受你的报复，同为男人实在看不下去！」

「……在说什么，听不懂。」

「听不懂也是问题所在。被牵挂的主人给抛弃，没人教导任何礼仪是不行的吧？我来教你吧。汪汪、汪汪。」

「──」

把外套拉到肩膀上披着，撑起上半身的亚拉基亚恶狠狠地瞪着他。

好心被狗咬，瑟希鲁斯只好举双手投降。话虽如此，被打不赢的对手同情有多难受，他不知道，但也不是无法想像。

「唉呀，不过被『剑圣』殿下安慰会很难受之类的……？一般来说，被喜欢的人温柔以待会高兴，应该不会觉得不甘心呀？」

「我讨厌你，瑟希鲁斯。」

「嗯～真顽固耶。好！这事还是直接丢给奇夏吧！」

伤脑筋的时候就拜托奇夏，是瑟希鲁斯烦恼时解决问题的方法。他全盘信赖老相识，决定把事情交给对方处理。

「好啦，这样子的话就带阿妮亚……奇怪？这么说来，今天城里是不是有什么事啊？」

想要打铁趁热到奇夏那边，却有些微挂意而歪头思索。结果在答案出来之前，先被解答那方给呼唤了。

「瑟、瑟希鲁斯一将！亚拉基亚一将！两位还平安吧！」

「嗯？哦，这边这边！我们都没事喔～」

瑟希鲁斯转过头招手，就看到赶过来的帝国士兵。

提心吊胆踩进被火燎原的一带的，是个年纪轻轻的青年。他畏畏缩缩地环视周围，茫然地问：

「这是……究、究竟发生什么事？两位遇袭吗……？」

「用不着太在意没关系。这一区是阿妮亚的私有地，只是选了个乏人问津、没人打理的地方作为我们争执的地点罢了。」

「──」

瑟希鲁斯对吓到的士兵如此说明，亚拉基亚不满地低着头，但没说什么。

看起来像是天崩地裂的惨状，却是每次亚拉基亚找瑟希鲁斯麻烦时都会有的损害。瑟希鲁斯姑且不论，亚拉基亚的战斗方式本身就是在猛烈地破坏大自然。

由于损害太过，总是波及周围，因此亚拉基亚被禁止在战场以外的地方使用能力。唯一例外的地方，就是在她拥有的私人土地上。

「因为是陛下亲自下达的命令，阿妮亚也只能勉强遵守啰。连我都被要求住在于私有地上临时搭建的小屋，我完全就是被牵拖下水的嘛。」

「原来如此……咦！？临时搭建的小屋！？」

「嗯，对啊对啊。你看，那一带，看到了没？就是那个。」

帝国士兵大吃一惊，瑟希鲁斯指了个有点远的地方给他看。森林附近有条河经过，旁边则挖了一个洞凑合着盖了间小屋，那就是瑟希鲁斯的住处。

另外，有个建筑章法相似的小屋位在同一条河的上游，那是亚拉基亚的住处。因此位于「九神将」顶点的两个人，都各自住在简陋的屋子里。

「为、为什么帝国最强的两个人，会住在那种地方……？」

「为了搜集古今中外的名刀宝剑，我所有俸禄全都花在上头。阿妮亚的话就只是不讲究而已。」

「……请问两位是一起生活吗？」

「不是……」

犹豫可不可以问，但最后输给好奇心的士兵问道。结果亚拉基亚比瑟希鲁斯还快否定这疑问。

事实上，两人是住在同一块土地上，但并没有一起生活。

「这也是陛下的命令啰。说什么我要是在不对的地方生活，阿妮亚脾气一来就会把那边整个毁掉吧？既然如此，倒不如一直待在阿妮亚伸手就能碰到的地方，这样危险的就只有我了……」

「对不起、对不起！我理解力太低，完全不懂意思！」

「哈哈哈，陛下检定太低的话就会这样啰。我是认为，这在陛下心中八成有着不限于字面的意思，但我没详细问，所以不清楚。」

士兵面露困惑，瑟希鲁斯开朗地拍拍他肩膀，还向道歉的他笑开怀。

老实说，不管知不知道都能被原谅。只是对瑟希鲁斯而言，这样的生活已经持续好几年，事到如今也没啥好在意了。

「……所以，有什么事？」

极度困惑的士兵开始眼睛打转时，亚拉基亚问起对方来访的原因。

「对了！」士兵听到这问题，彷佛被拯救般恢复生气。

然后──

「瑟希鲁斯•塞格姆多一将、亚拉基亚一将，陛下紧急召集两位！请以最快的速度前往帝都水晶宫！」

「水晶宫……啊！这么说来，今天有评定会议喔？因为每次去参加都在打瞌睡，所以最近都不叫我去了呀。」

「我也是……」

「虽然不是很想听到这样的实情，但这次不同！」

对两人的回应左耳进右耳出，立正站好的士兵表情紧绷。见他如此焦躁，瑟希鲁斯在焦臭预感下用舌头湿润嘴唇。

亚拉基亚也感受到相同预感了吧，瑟希鲁斯朝着她的侧脸笑。

「不久前巴尔罗伊先生才刚干了坏事，怎么突然又有别的事了呢。佛拉基亚该不会要开始战乱了吧？」

「……只有『选帝之仪』，就够了。」

「嗯，阿妮亚讲的我也懂，但我觉得手脚还伸展得不够呢。这股郁闷之前是由『剑圣』殿下帮我清除……哦哦，抱歉。」

一将之间的对话一开始，一个小兵根本无从插嘴。

瑟希鲁斯为打断传话一事道歉，士兵摇头道：

「不会。现在事态需要两位的力量。」

「哦哦～发生什么事？」

「就是……」

说到这儿，停下来吞了口口水后，士兵才继续。

开场白说到需要瑟希鲁斯和亚拉基亚两人力量的事态，就是──

「──『九神将』之『柒』夜鸣•魅时雨一将发起叛变！」

5

──神圣佛拉基亚帝国「九神将」夜鸣•魅时雨有个坏习惯。

有力量的人会被提拔、就任高位，是佛拉基亚的传统。

当代皇帝文森•佛拉基亚恢复九神将制度是其象征，但选定的条件只有强大的话，想当然耳便无法保证人格品行。

所谓的强者，正是不会讨好他人、不会顾及弱者，因此方为强者。

若是顺着这种思维，那强者的极致「九神将」如果具备协调性和伦理观念的话，就说不通了。当然，并非只有任性可以被原谅。

──他们都肩负着唯有他们才能达成的职责。

以完成其职责为前提，「九神将」才被允许拥有超越尺度的自由。

而理所当然的，要是被判定不适合享有这份特权，便会以更强大的力量使其屈服。

这便是强者的道理，剑狼之国佛拉基亚帝国的传统。

──在理解这点后，把故事回到前一节。

神圣佛拉基亚帝国「九神将」之一的夜鸣•魅时雨。

位居佛拉基亚帝国的强者顶点，拥有无与伦比的力量以及相符合的特权，这位魔都支配者有个难以评价的坏习惯。

那就是──

「──『九神将』之『柒』夜鸣•魅时雨一将发起叛变！」

冲进正在开评定会议的议会场后，传令兵气喘吁吁地厉声控诉。听到的刹那，整个议场鸦雀无声。

耳膜是接收到了这资讯，但让大脑理解需要时间。

之后，情报由大脑咀嚼，慢了一下，在场的人才各自有所反应。

参与评定会议的「将」大多都睁大双眼、面容紧张，而在议场中央有被安排座位的人们，反应每个都跟凡将不同。

有人皱眉，有人沉思，有的纹风不动。而在他们当中反应最剧烈的人，举起被黄金臂甲包住的手。

「开什么玩笑，那只母狐狸！！」

他顺从怒意把手往下挥，又长又大的桌子顿时粉碎。

这一击的威力刮起风，强大冲击波掀动与会者的头发和衣服。放任愤怒使出的挥击蕴藏了能一击杀害大型魔兽的威力，令人想起被人畏惧地尊称为「狮子骑士」的哥兹•拉尔冯有多强。

当然──

「你的愚蠢，就不能只停留在那张吵人的嘴巴里吗，凡夫。」

长桌被粉碎后，被掀起的风给摇晃黑发的皇帝目光十分冰冷。

接触到文森的视线后，乱发脾气的哥兹脸上血气倒流。原本听了报告后染成红色的脖子和脸都失去色彩，壮躯还当场跪地。

「陛下！臣万分失礼！任何惩罚均甘之如饴……」

「蠢货。哪有空惩罚你。明明身为『将』，却蠢到看不清这种状况吗？还是说，是在问余有多蠢？」

「不敢！陛下所言皆为实情！」

趴跪在上的哥兹，打从心底为自己的失态感到可耻。

无论好坏，他的特征就是情绪起伏大，也因此影响到自身的力量与指挥大军的能力。或者，这该说是坏习惯吧。

若被问罪，为了改正这点，哥兹想必愿意粉身碎骨吧。但是那样带有风险，就是「九神将」中可以根据状况发挥最强大力量的男人，有可能会堕为凡将。

因此，文森只是瞥了跪地的他一眼，就没有多加斥责。取而代之──

「这就是你预言的东西吗，『观星者』？」

「恐怕是。……只～是，不早点告诉您的话，预言也就没什么意义了。这是偶的个人想法啦。」

话题离开哥兹，转到用斗篷隐藏面部的「观星者」。听到他的回答后，文森看不出感情的脸哼了一声。

养在帝都水晶宫的「观星者」带来的预言，刚好和造反的报告一致。把这跟评定会议提到的事情叠加的话，也就看得清该做的事了。

──身为佛拉基亚帝国的首脑、皇帝该做的事。

「贝尔斯特兹。」

靠着扶手拄着脸的文森呼唤，细瘦老人安静回应：「在。」文森的黑瞳转向恭敬垂手的宰相贝尔斯特兹。

「你方才提到的名字是？」

「──是玛德琳•恩夏尔德，陛下。」

「那玩意儿，传唤的话有参加的意愿吗？」

皇帝试探的问题，让宰相脸上的皱纹加深。

只不过在老宰相回答之前，先有人呼唤文森。「陛下。」是坐在贝尔斯特兹对面的参谋奇夏。

奇夏粉白的面容也看不出感情，文森瞄了他一下。

「这样真的好吗？」

「无妨。反正不合期待，糟老头和丑角都要掉人头而已。」

「……小的理解了。」

接受文森的回答，奇夏老实退下。当事人「观星者」歪过头似乎想说些什么，但文森没搭理他。

「听见了吗，贝尔斯特兹。余的意思很明确。对你也照办。」

「臣当然明白，陛下。从一开始，为了让帝国未来更加美好，臣便做好不惜粉身碎骨的觉悟。──还有什么好畏惧的呢。」

「──」

面对真挚到让人觉得扫兴的回答，文森也没说什么。

就这样，文森的视线移向跪地大块头的头顶。哥兹目前仍下跪叩首，所以只看得见对方的头顶。

不管怎样──

「凡夫，你推荐的东西，能立刻行动吧。」

「──！当然！那个现在被拘留在领地内……只要陛下允许，在这瞬间就能立刻动身！」

「别胡说做不到的事。──就配合军队布阵吧。」

「遵命！」

开出的条件跟对贝尔斯特兹的一样，这让叩首大声回应的哥兹造成地鸣。

奇夏也接受，帝国首脑阵营的行动已定。

「镇压夜鸣•魅时雨的叛乱。根据卡夫马•依鲁鲁库斯和玛德琳•恩夏尔德的表现，来决定九神将之『玖』的继任者吧。」

「陛下，下次不是『柒』会空出来？」

收到文森号令后，提出疑问的是莫古洛。

听见钢人的死板声音，室内的众「将」看起来也都持相同意见。当然，造反的夜鸣要是被处刑，她被给予的「柒」的地位当然也就会被剥夺。

「届时有可能卡夫马二将及玛德琳殿下会一并跻身九神将之列。当然，在本次战斗中，包含小的在内，也有可能空出其他九神将之位。」

「可以的话，想避免那种可怕的事态。但是，莫古洛殿下的担忧言之过早。是否要剥夺夜鸣殿下的地位端看陛下，对吧？」

接在奇夏的话之后，贝尔斯特兹的视线洞穿文森。

细到让人以为他根本闭着眼睛的老人目光带着试探，皇帝闭上一只眼睛。对其他人而言，可能从这反应中撷取不到任何讯息，不过──

「余并不慈悲深怀，也不宽宏大量。然而，只要那个有尽到自己的职责，就不会剥夺给予的地位。说到底──」

在这边停顿了一下，文森先环视议场的众人，然后才继续。

「盘面上的棋子若不遵照余的意志，那就不在此限。──而这点，在场的你们也一样，搞清楚这点。」

这就是文森•佛拉基亚为这次的评定会议收场的话。

6

──「极彩色」夜鸣•魅时雨谋反。

帝国一将造反的新闻，在帝国内转眼间就传开了。其叛乱源头位在国土东南部的大都市──魔都卡欧斯弗莱姆。

原本帝国各个都市的首长就都拥有私人士兵，采行自治管理。

话虽如此，联系各都市的干道及要冲都有帝国军驻扎的军营，为了维护国土在四大国之中最为广大的帝国治安，强悍的士兵们日夜都目光炯炯。

因此，本次造反的最初火种，就发生在国土防卫最前线的士兵驻扎的军营里头──

「──军营里似乎有三百人起算的士兵，但无一幸免全遭杀害。夜鸣一将的恶评早有所闻，不过这次应该是最后了吧。」

「哦～」

在大众食堂的热闹氛围中，男子提不起劲地附和坐在同一桌的同事所说的话。

这也难怪。男子的视线聚焦于手边的盘子上、散发香草气味烤得恰到好处的厚肉块。唾腺早已麻痹，胃袋在高唱空城计。

正如宣传标语所说的「可以豪迈啃肉」一样，这肉是难得一见的美食。不过若以喜好来说，希望是能不要烤得那么刚好，留一些红肉带血的区块是最理想的。让粗鲁的搭档去点餐是错的。他在心头发誓下次绝对不会再犯这种错误。

不管怎样──

「喂，你那什么有气无力的回答啊。这是帝国最重大的事。不要一副事不关己的态度。」

才在自省的时候，面前探出身子的搭档──右眼戴着眼罩的贾马尔不开心地说。青年则是旋转手中的叉子，耸了耸肩。

「才没有。我没认为事不关己喔。只是现在在用餐吧？明明是你带我来这家评价很高的店，放着美食不管，未免太过失礼了喔。」

「混帐东西。肉随时都吃得到，可是身为帝国军人，能就近展现志气的机会有多少？你也认真想一想吧。」

「认真啊。你那张脸真的很不适合认真耶。」

「你说啥～！？」

忍不住就说出真实想法，结果贾马尔气到脸红脖子粗。

跟粗鲁的外表和言行相反，对帝国忠心耿耿是贾马尔有趣的地方。虽说是弱小的下级伯爵，但好歹是帝国贵族的末端，对此颇有自觉吧。

不过，贾马尔没打算坐等继承原生家庭欧瑞黎家的当家之位，满脑子只想着要凭本事立下汗马功劳来取得成就。

讲好听点，就是个不靠老家力量的老实人。讲难听点，就是个把生来就有的特权扔到水沟里的大笨蛋。而青年的意见偏向后者。

只不过──

「我是在称赞耶。别看我这样，我也是有脑袋的，当然会去捧迟早要成为我大舅子的人。」

「称赞～？你话里头根本感觉不到敬意……」

「我又不是那种会公然表示尊敬或景仰的人。要是办得到的话，就能轻松让卡楚雅相信我了。」

「哦～有可能喔。不是我要说，那家伙真的很顽固。」

贾马尔抱起手肘，点头表示理解。青年耸肩。虽说只是随便讲讲，但用在贾马尔身上，效果十分显著。

自己不打算跟他交恶。──要是见不到卡楚雅可就伤脑筋了。

与这个粗鲁男子有血缘关系的少女──卡楚雅•欧瑞黎对青年来说，是独一无二、绝对不想失去的人。

「好啦。卡楚雅的事先不说，继续夜鸣一将的话题吧。」

「那个可以边吃肉边聊吗？」

「你这个贪吃鬼。又不会花多久时间，听好了。」

香喷喷的肉摆在眼前却不能啃，青年垂下嘴角看着贾马尔。

虽然面露不满，但对方似乎认为这才叫认真，于是心满意足地竖起手指开始娓娓道来。

「注意啰？虽然这个也是听来的，不过为了镇压夜鸣一将的叛乱而出动的军队……似乎成了决定下任九神将的试验。」

「那是怎样？不久前少了一个九神将我是知道啦，但那又是怎么跟这次的事扯上关系的？」

「九神将的位置总不能永远空在那儿吧，也刚好突然有叛变。因此能够快速平息这场叛变的人，就可以补上那位置。如何！？」

「什么如何，我不觉得怎样啊。」

话语中挟带过度热情的贾马尔听了这回答后沮丧地说：「什么嘛！」他坐回椅子上一脸不满的样子，让青年歪头不解。

「就算你说的是事实，那又跟我们有何关系？该不会是想要立下大功劳，好被提拔为九神将吧？」

「哈，就是你说的那样！」

「我也有想过你是个大白痴，可是没想到笨到这种地步……」

看着贾马尔露齿一笑，竖起拇指比着自己后，青年惊愕不已。

身为一名帝国士兵，「九神将」的地位多有魅力，自己也能理解。贾马尔除了身为下级伯爵，又有着帝国士兵的自豪，所以使得这憧憬加速成长。

但是憧憬或理想，堪称是距离现实最遥远的东西。这是青年的想法。

「我说啊，贾马尔……你和我都只是一般士兵。虽然是上等兵，但依然是离『将』很遥远的兵卒。」

「所以才要在这边一举成名……」

「那种好事，不会降临在我们身上的啦。首先，你自信满满说的『镇压叛乱的目的是为了选出下一个九神将』，这事也很可疑。你听谁说的？」

贾马尔的人面意外广，所以早就听过他讲些真假不明的传闻很多次了。

只不过，至今大多都是被假消息给耍得团团转，因此让青年没法轻易相信他。老实说，这次也是打从一开始就认定这一定也是骗人的消息。

连不擅察言观色的贾马尔，都对青年狐疑的眼神感到不悦。

「不要一直挑毛病。也不要一直问东问西的。这话是我从夜鸣一将屠杀的军营中逃出来的家伙那儿听来的。」

「──不是说军营里头的人全被杀光，却有人逃出来？」

「啊！」反刍被问的话，失言的贾马尔这才抱头意识到哪里有问题。

追究对方有多蠢这件事先留待后头，青年稍加思索。假若情报的出处是事实，那单纯把这件事当成戏言就太可惜了。

「既然是从军营里逃出来，也就是说，该事件的当事人……假如是有事要报告，那对方就跟上头的人有联系啰。如果是从那边听到的话……」

「喂，怎样啦。才嫌我唠叨……」

「──贾马尔，你说的话，搞不好意外地不是笑话喔？」

因自己失态而摆出一副苦瓜脸的贾马尔，听到这话倒抽一口气。

不过，他的表情立刻变得神采奕奕。

「你到底想到什么啦？快点跟我说，陶德。」

「哎哟，等一下。不要那么着急啦。慢慢地静下来，收集情报吧。反正我们也被点名要参战了，死了可就不好玩了。」

这样回答性急的贾马尔后，青年──陶德•方克狰狞一笑。

他一面笑着，咬上终于可以品尝的肉块。

肉早已冷却，但锐利的牙齿毫不留情地把肉块撕扯开来。

7

被蹂躏过的军营惨状，完全符合单方面被虐杀的报告。

实际到达现场，踩在有许多士兵死亡的土地上后，哥兹•拉尔冯厚实的胸膛便被非物理的痛楚给折磨。

士兵的遗体已经全数运出，但营地内处处都留有战斗过的痕迹，遭到破坏的武器防具上都有擦不完的血痕，述说着这里曾经有过的激战。

「混帐，夜鸣•魅时雨……！」

一想到这些士兵们不甘心地死去，哥兹就义愤填膺。

做出这种大逆不道之举的，是跟自己同为「九神将」的一将。夜鸣•魅时雨到底要到什么时候，才会发自内心向皇帝陛下效忠？

哥兹是千锤百炼的帝国士兵，在九神将制度恢复时被指名为最初九人的其中一员，直到现在都还继续待在这位置上。他不觉得自己的实力有比其他「九神将」优秀，但却有着对文森的忠诚不输任何人的自负。

在哥兹看来，数次对文森发起叛乱的夜鸣根本难以理解。

每次镇压叛乱和造反，她的性命和地位都因为文森的温情而获得保障，不过引发这次的事件实在是不敬之极。

「这次的谋反，一定要割断夜鸣一将的首级。」

「──哎哟～那有点困难耶。看嘛，哥兹先生擅长的武器是锤矛吧？可以打烂头，但不适合砍头哟。」

严肃的面容上浮现险峻表情的哥兹，身后传来朝干劲泼冷水的声音。回头一看，便看到穿着草鞋踩在军营屋顶上、身穿和服的青年。

他的蓝色长发在干巴巴的风中摇晃，翩然地站到哥兹旁边。

「夜鸣小姐还是老样子，搞事起来毫不客气呢。听说留在军营里的人全都被她一个人给干掉了……」

「根据逃跑的士兵的报告来看是这样。夜鸣一将一个人灭了整个军营。」

「哈哈，不如说，若是夜鸣小姐的话，一个人战斗还比较厉害吧。在这边遇到她的人也真可怜，还得跟他们说声暖场辛苦了！」

心情大好的青年──瑟希鲁斯说。哥兹对他投以责难的目光。那眼神诉说对方太不尊敬死者，接收到视线的瑟希鲁斯挑眉。

「唉呀，莫非不合哥兹先生的意吗？」

「那当然。竟然把死去的士兵当成暖场……他们有他们的足迹和人生。以你的话来说，就是他们有自己的舞台。」

「哎哟，那真是失礼了。不过，只有一件事我要订正，哥兹先生。」

「──？」

「确实，每个人都是自己故事中的主角……是也有这样的章节，但要我来说的话，那些都是逃避。不可能。这个世界，只有名为这个世界的唯一舞台……而在那上头闪闪发亮的主角，舞台上的红牌演员，就只有一个。」

瑟希鲁斯抬头仰望比较高的哥兹，正大光明地主张自己的道理。俯视话语中的热情和积极非凡的态度，哥兹松开相当于一个孩童脑袋大小的拳头。

「……这就是你想讲的话吗？」

「对，就是这样！你懂呢！」

对方拍了一下自己胸膛，笑得轻松自在。哥兹叹气。

那是瑟希鲁斯的哲学，对任何人都不让步的绝对信条──无论是哥兹还是佛拉基亚帝国的任何人，都无法笑他在痴人说梦。

──因为，在崇拜强者的佛拉基亚帝国，位居最强顶点的人就是瑟希鲁斯。

遵从帝国高举的铁血定律，假如要耻笑他的道理并加以否认，就必须比他更强。然而，帝国里没有这样的人。

因此，无人可以否定瑟希鲁斯的哲学。

「──又在讲这个。瑟希鲁斯，你真的是白痴。」

才刚做出结论，痛骂瑟希鲁斯的哲学很愚蠢的例外现身了。

这个例外刮起风，翩然降落在军营屋顶上。夹带肉眼看不见的风飞行的，是银色短发随风摇曳的犬人少女，亚拉基亚。

沐浴在从空中现身的亚拉基亚的风中，瑟希鲁斯歪过头。

「很慢耶，阿妮亚。明明是同时起跑的，怎么落后我一圈啊？」

「……又没明确决定哪边是目的地。」

「被通知的时候是那样没错啦，可是军营里头这个金光闪闪的哥兹先生就像目标一样，阿妮亚也是朝这边飞过来的吧？那么，先到哥兹先生这边的我赢了，这样说也没问题吧？」

「瑟希鲁斯，去死。」

「都变没法回嘴时的惯用句了。哎呀，真想知道输家的滋味呢～开玩笑的！」

被亚拉基亚斜眼瞪视，但瑟希鲁斯不改滑稽态度。

哥兹觉得这种孩子气的互动实在不能让其他将领士兵看到，对此很头痛。原本这两人就欠缺身为「九神将」的自觉了，凑在一起的时候，这种情况便会更加显著。

话很少、对职务很认真的亚拉基亚，一扯到瑟希鲁斯就会欠缺冷静。

「亚拉基亚一将，连你都用瑟希鲁斯那种标准说话的话就伤脑筋了。要对自己担任相当于陛下手脚的九神将一职更有自觉。」

「……对不起。」

「奇怪奇怪奇怪！？哥兹先生，莫非你认为阿妮亚比我还通人话！？这样我有意见，我很受伤耶！阿妮亚也是脑袋有问题的人！煎蛋的时候她每次都只煎一面耶！」

「两面都要煎的话就自己弄。」

给予忠告也是徒劳，亚拉基亚的情绪依旧被瑟希鲁斯轻佻的话语给摆布。侧目旁边这样的互动，哥兹重新从屋顶眺望远处──看向闪耀生辉的魔都。

远到在地平线上闪闪发亮的，就是魔都卡欧斯弗莱姆的红琉璃城。

那是用名为红琉璃的特殊魔晶石建造，被誉为跟帝都水晶宫并列的美丽城堡。只不过，城堡内住着叫做夜鸣•魅时雨的奸臣。

「这样一想，那个亮晶晶的东西看起来就像血的颜色呢。」

「好啦好啦，漂亮的东西就是漂亮，没必要刻意说破……所以要怎样？这次我跟阿妮亚好像都要听哥兹先生的指挥喔。」

「我不认为用道理可以束缚你们。战斗开始之后，就交由你们各自判断。」

「不愧是哥兹先生！就是那么懂事～！」

被给予打游击战的使命，双眼发亮的瑟希鲁斯高呼快哉。

（插图012）

帝国之「将」被要求的资质，就是个人战力和团体的指挥能力。哥兹在两边都有一定程度的水准，但瑟希鲁斯的资质完全偏向个人战力。亚拉基亚同样也偏向个人战力，而奇夏就相反，是拥有非凡指挥能力的人才。

准备好和彼此相应的战场，使其能力发挥到最大程度，就是用兵的极致。这是哥兹靠实战锻炼出来的哲学，也是自己受到好评的部分──哥兹是这么分析自己的。

事实上，有瑟希鲁斯和亚拉基亚在，就算对手有千军万马也敌不过。可是，如果对方有「九神将」的话，这个道理就不管用了。

「更何况，对手是夜鸣•魅时雨……而且还是在那个母狐狸的都市。没有做好万全准备的话，被害范围只会扩大。」

「夜鸣•魅时雨……我没见过。怎样的人？」

「嗯……也是。毕竟夜鸣一将没有出席过评定会议。」

抱着粗臂的哥兹低喃，玩弄左眼眼罩的亚拉基亚问道。听到她说没见过对方，哥兹感到讶异，此时瑟希鲁斯举手。

「来！既然都提到了，那我要说，最近我跟阿妮亚都没被叫去评定会议喔！说是不在的话事情进展得比较顺利，我听奇夏说，这是陛下讲的！」

「这点无法否定，但就我们而言也是感到无可奈何。」

评定会议里，「九神将」的出席率之低，才刚被讨论过。

不过本来就没人期待瑟希鲁斯、亚拉基亚和夜鸣他们出席，因此出席者最多六人。现在少了「玖」，所以是五人。

前些日子的评定会议中，连这五人都凑不齐，不过──

「夜鸣一将是统治魔都的女狐人。以吃人的态度和举止欠缺对陛下的敬意引人侧目。以我个人来说觉得她不适任『九神将』，更没有好感。」

「是个大美女，很有魅力，所以适合当个舞台演员。哦哦，还有，在先前的造反中我有两次动了杀意，可是她怎么杀都杀不死。」

「──！连瑟希鲁斯都杀不死？」

听了补充后，亚拉基亚瞪大眼睛，感到惊愕。

亚拉基亚想要「壹」的位置而不断挑战瑟希鲁斯，这件事很有名。哥兹也曾刚好待在他们死斗的场合。每次都被对手敷衍的她听到有帝国无双的瑟希鲁斯杀不死的人，当然是不可能听过就算。

「瑟希鲁斯，对美女敌人，手下留情……？」

「哎哟哟，这可不能当耳边风呢！不管对手是谁，我都不会刻意放水的啦！说到底，如果用对方是美女这个理由而不拿出真本事，那对上阿妮亚，条件不也一样了吗！」

「────」

「怎么说呢，夜鸣小姐的强大很独特。这方面，我想她比较接近奥尔巴特先生。唉～因为奥尔巴特先生也是不知道在强什么嘛！」

瑟希鲁斯提起夜鸣的强劲，亚拉基亚的表情很复杂。

不过不好说明这点，哥兹也有同感。他也不明白夜鸣的强大实力何来。连「九神将」之间都不明白彼此的实力底细，也是帝国的风格。

「跟老爷爷一样……越来越搞不懂了。结果，是怎么个强大？」

「别责备瑟希鲁斯，亚拉基亚一将。我也是觉得夜鸣一将的强大很难说明的人。不过硬要说的话……」

「硬要说的话？」

亚拉基亚歪头求解，哥兹思索了一下。

但最后只想得到一个答案，于是他脱口而出。

「就如绰号『极彩色』，是不时便会有鲜艳变化的强大吧。」

「……听不懂。」

「就是说嘛！」

不知是歪头的亚拉基亚还是哥兹的说明好笑，总之听了说明后，瑟希鲁斯大笑。

他那态度惹来亚拉基亚的视线针刺，还真是会触怒她啊。虽然偏离了主题，但哥兹对瑟希鲁斯感到佩服。

开战前都还是老样子的他们，这种态度应该是令人觉得很可靠才对。但──

「──也是为了陛下，我们必须完成使命。」

「这倒是。」

「没有异议。」

此次出兵是为了镇压叛变，为此而派出的军队指挥官为哥兹。哥兹道出决心，瑟希鲁斯和亚拉基亚都毫不犹豫地这样回应。假如内心不动摇与他们的强大有直接关联，那么予以肯定就是帝国的风范。

「不过话说回来，哥兹先生好辛苦喔。不只我跟阿妮亚，还得指挥集合起来的士兵，再加上监督巴尔罗伊先生的位置之争。」

「……既然知道的话，麻烦你也自重。」

「哈哈哈，开玩笑！人都有适合和不适合的事。嘴上一直说讨厌，奇夏还是一直陪着陛下，就是因为他适合呀。」

瑟希鲁斯随兴挥手道，哥兹沉重叹气。

瑟希鲁斯说的没错，这次除了要镇压叛乱外，哥兹还得监督争夺「九神将」席位之争的两名候补人选──卡夫马•依鲁鲁库斯和玛德琳•恩夏尔德。

推荐卡夫马的正是哥兹，但既然被赋予这个责任，就要尽可能公平看待事物。

话虽如此──

「两者都太慢到了。……先不说不认识的那位，卡夫马二将理应不会这样。」

应该早已被命令出征的两人都没有露脸，哥兹对此感到不解。

还没见过贝尔斯特兹推荐的玛德琳，但跟卡夫马已经是至交。虫笼族出身的年轻人责任心强，跟文森说的不惜自裁谢罪的觉悟也不是夸大其词。光是这样，就希望给他一个机会挽回声誉。

这时──

「──一将！卡夫马•依鲁鲁库斯二将抵达！」

「来了吗！」

「是的！在军营地底……咦！？瑟希鲁斯一将和亚拉基亚一将，两位几时到的！？」

双脚并拢发出声响，报告现状的士兵看到瑟希鲁斯他们后瞪大眼睛。因为这两人没有做抵达现场的报告，而是直接跑到屋顶上，因此小兵有这种反应也是难怪。

不管怎样，忍不住大声的哥兹安抚他。

「别在意。那么传话下去，要卡夫马二将上来。我要跟他讨论攻打魔都的事。」

「……这恐怕有困难。」

「什么？」

哥兹已经想到作战会议去的心情，因部下出乎意料的答覆而栽跟头。他带着｢发生什么事｣的含意睁大眼睛，士兵被他的眼神吓得嘴巴直发抖，说：

「卡夫马二将虽然抵达，但目前处在特殊状态……想请一将前往判断。」

「特殊状态？连你们都没法判断的状况？」

「是的……」收到不得要领的回答，部下以一脸伤透脑筋的样子点头。很想对这懦弱的样子说个几句，但卡夫马现在的状态叫人挂意。

而且──

「虽然跟你们讨论的事没关系，不过你叫一将，是在叫哥兹先生还是我？又或者是阿妮亚，根本就搞不清楚呢。毕竟你看，我们全都是一将嘛。」

「你有做过像是一将会做的事？」

「有啦！我有赌上佛拉基亚帝国的威信，跟王国最强的『剑圣』单挑！」

「听说输得很惨。」

「在王国再战的时候就平手啦！」

看到瑟希鲁斯被亚拉基亚的话激到跺地嘟嘴，就觉得把消解部下们的不安的任务交给他们，也太过残酷了。

不巧的是，瑟希鲁斯擅自闯进王国这件事，包含在该处引发的事件在内，全都是不得泄漏的机密事项。

而部下不小心听到而大吃一惊，之后得好好封住他嘴巴。

提醒自己不要忘记这件事的同时，哥兹对部下说：

「知道了。去卡夫马二将那儿。带路吧。」

8

「哈哈～这可真是。唉呀唉呀，原来如此原来如此。」

手扶细腭，瑟希鲁斯不住眺望眼前的异物。

从后方看去的亚拉基亚，犹豫要不要攻击他满是空隙的背部。

文森有说过，自己随便什么时候都可以攻击瑟希鲁斯，然而如今是作战当中，应该要自重吧。再说了，要是在这边打起来的话，先不说瑟希鲁斯，哥兹和其他士兵会觉得很困扰吧。

亚拉基亚并不讨厌块头大又长得可怕的哥兹。

因为他总是会担心这儿担心那儿，还会照料自己，万一有什么不好还会提醒自己要注意。由于亚拉基亚对于一般人的常识很生疏，所以他的体贴帮了很大的忙。

因此，即便看到了攻击瑟希鲁斯的绝佳机会，都还是忍下来了。

「哎哟，不攻过来吗，阿妮亚？我刚刚故意全身都露出破绽，但是被你察觉了？」

「去死。」

不是对讨厌的话，而是对说出讨厌话的瑟希鲁斯反射性地回呛。被他苦笑带过，亚拉基亚感到颇不痛快。

「不过，虽然我没见过他，但真是相当奇特的人呢。你说他叫卡夫马先生吗？」

「……确实，虽然人多少都有不同之处，不过没有遇过这种样子的。」

「啊，果然是这样啊。太好了～。因为没想过有比莫古洛更偏离人类的人加入，所以我架式都摆好了呢。」

不甩亚拉基亚的心境，瑟希鲁斯和哥兹两人朝着面前──在被运到军营地下室的异物前交谈。

哥兹眉心深锁，不擅长推测他人心情的亚拉基亚读不出他的心。但是心情复杂这点，她的意见跟瑟希鲁斯相同。

要跟这个叫做「卡夫马」的物体好好相处，实在很难。

毕竟这个──

「──简直就像是虫蛹呢。」

瑟希鲁斯浅笑道出感想，直率地表达出他对这个的印象。

蛹──昆虫成长阶段的变态过程之一，羽化之前的状态。这个被咖啡色圆壳包覆、一动也不动的玩意儿就堂堂镇坐在地下室里。

就算听到这便是卡夫马•依鲁鲁库斯，实在不知道要怎么跟他交流。

「这个，为什么会变成这样？」

「是、是这样的！卡夫马二将闭门反省期间……在体内放入了新的虫……」

「新的、虫……」

负责搬运蛹的士兵慌慌张张地这样回答亚拉基亚的提问。听了还是不懂的亚拉基亚，只好看向哥兹寻求说明。

在她单眼的注视下，哥兹手扶额头说：

「是这样啊。虫笼族在出生后，据说就会将该族相传被称为『虫』的寄生体放入体内。与该虫共存，有时借用其力量，就是虫笼族的特性……」

「可是，放了新的。」

「呼嗯，有听过。在他们族人中优秀的个体，会再纳入新的虫，好提升能力。也就是说，卡夫马二将……」

「追求新的力量，结果变成了等待羽化的蛹。」

哥兹眯眼望着蛹如此推测，瑟希鲁斯抢先讲出结论。

连对世间没兴趣的亚拉基亚，都有听说几个月前的政变与虫笼族有关。尽管卡夫马没有涉入叛乱，却因为被族人牵连，所以受到连坐处罚。

在关禁闭的期间把新的虫放入体内，用意是──

「委屈生气，所以想大闹一番？」

「啊哈哈哈哈哈！哪有可能是这样，他又不是阿妮亚！」

「──」

「人会懊悔而想要力量的理由很简单明瞭，就是为了奋发再起。杀死无力的自己，成为不同的自己，然后挑战下一个死域。除此之外，还有其他理由吗？」

还有其他理由吧。亚拉基亚这么想，但也觉得瑟希鲁斯说的话是有道理的。

因为，自己也有过想要力量的时候。──不，即便现在都还是想要。

发现自己的力量不足以守护重要的人时，亚拉基亚的人生迎来了很大的转机。当时的无力感强烈到对现在都还有影响。

假如同样的东西，也袭向卡夫马•依鲁鲁库斯的话。

「是为了让自己变强。」

「话虽如此，也不知道要多久才会羽化。哥兹先生，抓得到时间吗？」

「──。不知道。不过不能等他太久，我只能这么说。」

苦着脸的哥兹沉重回答。

推荐卡夫马为「九神将」的他，应该很期待卡夫马在这次的仗中大放异彩。可是若对方继续窝在蛹里，就不可能实现。

话虽如此，哥兹可不会同意因此延迟开战。

「原来如此、原来如此……那么，就快快解决吧。」

「瑟希鲁斯？」

亚拉基亚对哥兹遗憾的表情感到同情时，旁边的瑟希鲁斯静静拔出刀。

他架着看起来微微透蓝的刀，刀尖指向卡夫马的蛹。锋利的剑气缓缓释出，里头没有任何玩笑或天真的气息。

「瑟希鲁斯，你到底想干嘛？」

「硬要说的话，便是质问卡夫马先生的觉悟吧。既然不能等太久，就只能证明啰。──证明他有多认真。」

回应神情严肃的哥兹后，瑟希鲁斯的蓝眼睛因剑气而湿润。

澄澈剑气高涨，亚拉基亚感受到躲在大气中的微精灵在胆怯。──以「食精灵者」来看，那单纯就是恐惧。

会吃精灵的自己被精灵畏惧，这点她早就知道了。可是精灵们会害怕瑟希鲁斯的剑气，代表瑟希鲁斯让没有实体的它们联想到死亡。

而这点，躲在蛹壳中的虫笼族也一样──

「──吁。」

简短吐气，瑟希鲁斯的手头发出剑击声响。

只是轻轻转动手腕就放出的剑闪，跟做给亚拉基亚看的「云切」都是技艺的一种。但能够取笑这是卖艺的人可少之又少。

顶多只有亚拉基亚那胆量超乎常人的主子，和文森而已了吧。

其余之辈，应该会错以为自己的身体被斩成两半了。

因此──

「──哈哈，确实有喔。」

这是对瑟希鲁斯的剑气产生的防卫本能吧。

瑟希鲁斯轻笑，歪过头。飞出来擦过脸颊的，是从龟裂的蛹溢出、彷佛深绿色荆棘的物质。原本毫无反应的蛹进行反击，瑟希鲁斯灵巧地用刀对应那东西，然后转头对哥兹说：

「已经没事了。既然会对我的剑气有反应，那只剩下时间的问题。壳可以剥吗？」

「……这样啊。看来，确实如此。」

哥兹只愣了一下，接着轻触伸出的荆棘后，接受建议。

他一用力握住藤蔓，藤蔓便裂了开来，一口气碎裂。看样子，这个绿色玩意如外观般有着植物般的弹性，却也蕴含了宛如结冻的硬度。

「这样一来……不，剥开的过程中或许还是会有荆棘跑出来。剥除工作就由我来。你们负责回收剥下的壳。」

说完，哥兹就开始俐落剥壳，其他士兵们也重新面向蛹。

旁观着这副光景，瑟希鲁斯把刀收回刀鞘，开心地转身。那雀跃的气息叫人厌恶，亚拉基亚的视线因此严厉起来。

「哎哟，心情不好吗，阿妮亚？」

「瑟希鲁斯心情好，我就心情不好。」

「这什么奇怪的连动啊。自己的心情不该托付给我或主人，我觉得这样才健康喔。」

「──哼！」

对方说了自己不想听的话，亚拉基亚的眼神开始带着怒火。但瑟希鲁斯只是轻轻挥手掸掉热度，就接着说了下去。

「不过呢，昆虫的羽化真是不可思议的现象。毕竟蝴蝶的幼虫和成虫，姿态外型完全不一样。为了活下去，使用的能力也不同，感觉像是这样呢。」

「……吃叶子，和吸花蜜。」

「没错没错，吃的东西也不同！根本就是不同生物嘛。蛹也是，在独立羽化之前要是剥开壳的话，里头就是软烂黏糊的东西，吓死人……」

就在瑟希鲁斯说到这儿的时候。

身后卡夫马的蛹那儿传来哥兹的粗野嗓音，以及士兵们骚动的声音。看来是剥壳的过程中发生了意料之外的事。

该不会，刚好跟现在讲到的话题有关吧。

「瑟希鲁斯。」

「我以为没问题，但还是太性急了吗？」

以一副没有危机意识的样子歪过头，瑟希鲁斯抓抓脸。那随便的态度让亚拉基亚叹气，同时把处理蛹的工作扔给哥兹。

取而代之，她用单眼紧盯瑟希鲁斯的脸。

「──？干嘛？」

「这次的任务，会决定下一次的九神将。」

「哦，好像是呢。因为是递补巴尔罗伊先生的位置，希望是可以沟通的人。卡夫马先生要是也能平安登上舞台的话就好了……」

「──我要让你，好好念对我的名字。」

「哎哟。」

亚拉基亚平静地告知决心，瑟希鲁斯圆睁双眼。

接着原本惊讶的表情转为满意微笑，并回视亚拉基亚。

「你的意思是，要在这场战斗中做出连我都会吃惊的战果啰？」

「瑟希鲁斯都杀不了夜鸣。那么，我来。」

「要杀掉夜鸣小姐啊。原来如此、原来如此……我懂了！」

亚拉基亚点头，瑟希鲁斯站到她前面，脸上堆满笑容。接着他快速地握住她的手，粗鲁地上下挥动。

「好耶，请杀掉夜鸣小姐看看。如果用赢过我这个条件，那阿妮亚永远都没办法达成，所以这次这样刚好！」

「──」

「唉呀呀，怎么了？皱眉头就不好看啰。因为你比我弱，所以至少要维持可爱美女的样子会比较好喔。」

「放开。」

瑟希鲁斯的话已经突破惹人厌的程度，亚拉基亚甩开他的手，咬牙切齿。

她暗暗下定决心，要让他那张从容的脸孔变成哭丧脸。

这不是为了抢走瑟希鲁斯的「壹」之位置，也不是为了一直在心底维持热度、自己对主人的想念。

但是对亚拉基亚而言，这是为了持续强大自立所需的仪式。

「哎哟喂呀，一说到阿妮亚又马上生气了。……不管怎样，这样的挑战我很欢迎喔。有能够挑战我的对手，我可比『剑圣』殿下还幸运。」

不睬亚拉基亚的怒火，双手抱住后脑勺的瑟希鲁斯这么说。

明明身在地下室，蓝色眼眸却像是透过天花板看到了外头的天空。对亚拉基亚来说，那是这一天最让人火大的东西。

不论何时都不把亚拉基亚放在眼里、一副绝对强者之姿的瑟希鲁斯•塞格姆多。他那样子，最是让人火大。

9

──就这样，在帝国军集结在最靠近魔都的军营的同一时分。

「不过，真没想到会有稀客上门呢。」

带着慵懒妖艳的声音，盈满、支配了天守阁。

铺着木头地板的大厅，坐在最深处上位的就是城堡主人，掌控着魔都卡欧斯弗莱姆的天上美姬。身穿华丽斑斓的和服，头上插着众多发饰，用各种装饰品来妆点自己的狐人──夜鸣•魅时雨。

目前在佛拉基亚帝国里，立场最危险的女人，但她的态度却没有丝毫紧张不安。

对侍奉她的所有人来说，表现得泰山崩于前而色不改，就是他们的心灵寄托。即便被整个帝国视为眼中钉，举手投足仍旧没有一丝动摇。

这正是数度起兵造反的美姬的态度。

但是──

「就算是奴家，也没想过会用这种形式迎接客人。」

「这是对龙的发问，给的答案吗？」

夜鸣把长柄烟管送到嘴边，吐出烟雾。而强硬的声音这样回应她。

出声者是坐在下座的娇小身影。夜鸣俯视这个稚嫩的小个子，要说对方看起来就像个迷路的小孩也不奇怪。

然而这个迷路的小孩，却不是一个人造访红琉璃城。

「──」

好几个黄色瞳孔，毫不客气地睥睨着天守阁内。

眼睛的主人以凶猛闻名，不管对手是人类还是魔兽都会毫不留情地袭击。而彷佛要证明这事不是乱讲瞎掰的──

「──貚纱，不要动。」

「遵、命……」

夜鸣的湛蓝双眼瞥过去的天守阁阳台，正上演着异样光景。

小小的头上长着两只大角的鹿人女孩──眼眶蓄满泪水的她，头正被收起双翅的巨大飞龙含在嘴里。

只要飞龙一个不高兴闭上嘴巴，女孩的头颅就会像鸡蛋一样破裂。

而且，除了含着女孩脑袋的一只外，还有许多只飞龙。每只都把红琉璃城的屋顶和阳台当成让翅膀休息的踏脚地，拿魔都居民为人质来牵制夜鸣。

不肯亲人，驯服方法也极为有限的飞龙，现在却乖乖听从坐在夜鸣面前、双眼炯炯有神的少女──

「你是……」

「──玛德琳•恩夏尔德。」

「──」

「快快听龙的话去做比较好。因为大家可不像龙一样温柔。」

说完，少女──玛德琳•恩夏尔德的金色瞳孔紧盯夜鸣。

端坐得体的她，头部长着异于鹿人与鬼族的黑角。

──理应早就消失，被当成古代生物的种族。

──头上长着龙角的龙人少女，正在劝夜鸣投降。

10

──位在魔都卡欧斯弗莱姆中央的「红琉璃城」，被异样的气氛给包覆。

「────」

在城堡最顶楼，天守阁最深处，慵懒地看着来访者的美女夜鸣•魅时雨。

她是魔都支配者，佛拉基亚帝国武官顶点的「九神将」之一──不过，目前陷入称号被剥夺的危机。但是君临魔都的她即使置身在立足点动摇的状况，那美丽的容貌仍没有一丝阴霾。

这也难怪。

要是贯彻自己的信念，结果却是后悔，根本就不可能担任帝国军的一将。只不过，夜鸣的态度跟那软弱的想法无缘。

超然目睹发生的一切，走在用愤怒铺设的道路上，就是夜鸣的处事哲学。

而且即便四面八方被狰狞的敌意给包围，这点也没有改变。

「──回答龙。用心回答。」

以指头玩弄金色烟管的夜鸣不吭声，可爱的嗓音就开始逼问。

声音的主人即是夜鸣前方，端坐在木头地板上的娇小少女。坐在支配天守阁的敌意中心，明亮的蓝色头发中长着两只黑角，金色瞳孔紧盯着夜鸣。

不过，要是以为这名少女只是普通小孩的话，那要不是看不见状况的蠢蛋，就是感受不到威胁、彻头彻尾的和平主义者。

很遗憾，夜鸣两者都不是，因此不会错估少女的危险性。

更何况──

「……夜鸣、大人。」

天守阁阳台上，随从貚纱命悬一线，就更不可能误判了。

嘴巴含着貚纱头部借此恐吓自己的，是喉咙发出低吟的巨大飞龙。以不亲人而知名的天空霸者，掌握着貚纱的生杀大权。

再加上，把天守阁当成栖木的狰狞飞龙不只一只。无数飞龙把天守阁的屋顶和阳台当成让翅膀休息的踏脚台，金黄色的眼睛直看着夜鸣。

以跟身在中心的少女一样的金色瞳孔──

「你，叫什么名字？」

「──？龙的名字吗？玛德琳•恩夏尔德。好好记住。」

「玛德琳•恩夏尔德……十分时髦的名字呢。」

「──」

给出名字的少女眯起和飞龙一样的金色瞳孔。在夜鸣眼中看来，跟龙种这些脾气暴躁的生物特有的目光极为相似。

当然，对方可是以貚纱为人质，还带来无数飞龙进行恐吓谈判的人。要说她倾向避免与人起争执，是谁都不会信的吧。

不管怎样──

「只身一人……这样说好像有语病。不过，你是奉陛下的命令来奴家这儿的吧？」

「陛下……是指地面上最伟大的人？」

「──。大致上就是那个意思。」

「是的话，那没错。……不对吗？直接跟龙说的和陛下是不同人。是个长满胡须的糟老头。」

「长满胡须……」

玛德琳意外有规矩地回答，夜鸣皱起娥眉思索。是把这个反应看成犹豫了吧，玛德琳的视线稍微变得尖锐了一点。

「龙回答了问题。你也快点决定态度。」

「这可真是热情的邀请。有时会有技巧高明的『操飞龙』。在奴家的记忆里，从未有人能让飞龙如此顺从。您是怎么驯服这么多龙的？」

「──这是侮辱吗？」

顿时，玛德琳瞳孔变细，宽敞天守阁的空气瞬间冷却。

在全年气候都很温暖的佛拉基亚，几乎没有机会感到寒冷。若要说有，那就跟气温无关，而是生命响起警铃，是与强者对峙时才会有的本能感受。

「龙，没有服从谁。别把龙的慈悲，当成是忠诚。」

「……明白了。不愧是龙人，跟奴家在标准上就不同。」

「──快回答，石头城堡的主人。」

玛德琳用不容分说的目光，强迫夜鸣做出决定。

这是没打算继续陪她闲聊的意思。至此，夜鸣把烟管抽离嘴巴，目光再度转向阳台上的貚纱。

性命被飞龙利牙把持的她，黑溜溜的眼睛与夜鸣视线交错──

「──貚纱。」

「……在。」

「你，能爱奴家吗？」

被问了跟状况八竿子打不着的问题，貚纱目瞪口呆。

不过夜鸣的声音里头不带玩笑和恶作剧，这点貚纱好歹分得出来。女孩睁大的眼睛透着微弱光芒，接着她点头。

见状，夜鸣静静微笑──

「请两手空空地回去吧。──这里是奴家的城堡。」

「──龙生气了。」

夜鸣的话充满挑衅，玛德琳站起来，朝飞龙挥手。

下达的指令很简单，就是闭上嘴巴。

巨大飞龙阖上嘴，其咬合力将貚纱的头像鸡蛋一样咬碎。清脆声响后，女孩的头部轻易裂开──并没有。

「──吼吼！」

下腭使力，打算咬碎貚纱的飞龙低声吼叫。每一颗都彷佛尖刀的牙齿怎样也无法贯穿貚纱柔软的肌肤，甚至还开始龟裂。

目睹这不可能的景象，玛德琳惊愕不已。

「你做了什么！？」

「──。多可爱的说法呀。」

玛德琳立刻表达惊讶，却因夜鸣的话而屏息。然而面对这意想不到的状况，龙人可不会只做出愣在原地这种愚蠢的可爱反应。

「──哼。」

屏气的玛德琳把手伸向背在身后的包包，白色手指解开包包的扣环，抓住把手，然后转动手腕。──接着，武器便发出声响伸展开来。

是有着和缓曲线的投掷用武器，又叫做「飞翼刃」。一旦扔出使其高速旋转的话，就能在空中划出弧形然后飞回来，是一种狩猎道具。

不过玛德琳手上拿的，大小却跟她娇小的身材差不多大。

「喝──！！」

她抓住飞翼刃的握把，使出横扫一击。

不是投掷，宛如刀剑横扫的一闪伴随惊人的冲击波，化为暴风肆虐红琉璃城的天守阁，直接袭向一直坐在上座的夜鸣。

但是──

「您是真的什么都不知道，就前来奴家的城堡了呢。」

连木头地板都被掀起，玛德琳这一击足以撕破血肉，却在继续待在和式椅上、一动也不动的夜鸣面前硬生生被挡下。

原因不明，总之飞翼刃的猛击没有碰到夜鸣。旋转的利刃像是被看不见的墙壁给阻挡，因而避开夜鸣，转而撕开她身后的墙壁，穿破天守阁。

这状况让玛德琳目瞪口呆，紧接着飞龙的咆哮传进她耳里。──不，才不是咆哮这种勇猛的叫声，而是飞龙的哀号。

转过头，映入眼帘的是在阳台那儿举起手的貚纱。鹿人女孩面露惊愕，手上握着拔下来的利牙。

捕食者和猎物的立场颠倒过来，飞龙因为被女孩拔牙而痛苦惨叫。

这个既成事实和貚纱的反应都很奇怪，令玛德琳忘记呼吸──

「在奴家面前还看向别处，未免太冷淡了。」

「──唔！？」

接着，夜鸣穿着的木屐屐齿，笔直刺向玛德琳的侧脸。

在强烈冲击下被踢飞，玛德琳整个人往后飞出去。就这样在地板上弹跳，以猛烈的速度撞上墙壁，半个身子埋在墙里。

毫无防备吃了一踢的玛德琳，不知道自己的攻击被防御的机制。但是踢飞她的夜鸣也因反作用力出人意料而眯起眼睛。

外表看起来个头跟貚纱没差多少的玛德琳，却让夜鸣的脚承受极大的撞击力，比踢飞一个必须抬头仰望的大个头男子还要沉。

简直就像是那小小的身躯里，塞满了不寻常的质量。

「真的、生气了……！」

脱离墙壁的玛德琳气到声音发抖。吐槽她说话口气发生变化的时机已然错过。

而且既然开始了，双方就没有放水的选项。

「──」

夜鸣叼起烟管，玛德琳让瘦小身躯吸饱空气。

烟雾与空气，各自用不同的东西膨胀肺部，两人视线交错的刹那间──

──强大的冲击波，从红琉璃城的天守阁内部炸开。

11

「这次因为自己的不小心给各位添麻烦，真的非常抱歉！」

说完，青年以像要用额头摩擦面前桌板的气势──不，会议室真的响起了撞击声。青年深深低头折腰，为自己的失态道歉。

那是咖啡色皮肤和绿色头发，目光强硬、表情剽悍的人物。到他谢罪这边的过程姑且不论，能够平安无事地看着彼此，一行人还是感到放心。

毕竟──

（插图013）

「从蛹里跑出黏糊糊的东西时我紧张死了！要是就那样没有变硬的话还能当同事吗，光想我就不安得无以复加呢！」

开朗大笑、回顾刚刚发生的事，瑟希鲁斯道出没啥礼貌的感想。

事实上，要怎么处理蛹，在军营里引发了一阵骚动。要是哥兹等人害死了前途似锦的帝国之「将」的话，就等于是做了背弃皇帝的无耻行为。

幸运的是，尽管溢出黏性液体，但蛹里面的青年还维持着原形。

「那么，确认一下。你是卡夫马•依鲁鲁库斯先生吗？」

「是！我是卡夫马•依鲁鲁库斯二将！族人对皇帝陛下不忠，虽然我被放过一马，但最后还差点失去挽回颜面的机会……我为自己感到羞耻！」

「呜哇啊，好一板一眼的人。我可能不太擅长跟这种人打交道。阿妮亚你咧？」

「去死。」

大声为自己的过失谢罪的青年──卡夫马•依鲁鲁库斯的态度，让瑟希鲁斯征求旁边的亚拉基亚的感想。因此，她如他所愿，给予回应。

撇开得到一如往常的答案而嘟起嘴巴的瑟希鲁斯不谈，哥兹发出粗野呐喊：「好了！」他踩过会议室地板，大手拍打卡夫马肩膀。

「抬起头，卡夫马二将！『虫笼族』的习俗我不清楚，但是你放了新的虫吧？既然是你，想必这也是为了洗刷一族的污名吧。」

「哥兹一将，可是我……」

「你的这股自觉和对皇帝陛下的忠肝义胆，都用不着怀疑。不只我，瑟希鲁斯和亚拉基亚一将也都认同，对吧？」

安慰自责不已的卡夫马，哥兹转头要亚拉基亚他们同意自己。

但是亚拉基亚却没法好好回应。跟卡夫马才第一次见面，根本没有准备好哥兹想要的答案。即便如此，还是必须说些什么才行。

「──」

「哎哟喂呀，不擅言词这点还是没好耶。看这样子，没有我跟奇夏的话，阿妮亚你要怎么办喔？辛苦的都是旁边的人，真令人同情。」

斜瞄了一时之间找不到话说的亚拉基亚一眼，瑟希鲁斯笑得傲慢，接着又满不在乎地拍手。

「很好，很棒，没有问题！就跟哥兹先生说的一样，卡夫马先生的努力很了不起。就算被下令去做我也办不到。竟然把虫放进自己身体里面！」

「……这是在侮辱我们『虫笼族』吗？」

「怎么会！？我是非常正面地夸奖你呀！」

卡夫马皱眉探问瑟希鲁斯这么说的真正用意。接触到疑惑眼神的瑟希鲁斯举起双手，厌恶摇头。

「还请不要误会。强化自己的方法因人而异，也有分适合和不适合的流派。我是自学的剑客，而既然『虫笼族』的方法是与虫共存，那以这个方向去努力是没有错的。我认为锻炼的方法不分贵贱。」

「这……对不起。我的看法太过主观了。」

「这是无可奈何的。因为瑟希鲁斯每次都用这种像是吃人的说法。」

「同感。」

「怪了怪了怪了？我明明在讲正经话，怎么都没人帮我说话？」

被哥兹和亚拉基亚背刺，瑟希鲁斯一脸意外。但是以亚拉基亚的角度来看，被认为会为他说话这点才叫人意外。

亚拉基亚替瑟希鲁斯说话，是绝对不可能发生的事。

就算是在酣战之际，假如瑟希鲁斯毫无防备地背对自己──

「会毫不犹豫地宰了我。唉呀，就算有那种机会，办不到的话就只是纸上谈兵。就像剥不下的龙皮交易一样。」

「你话太多了。」

「那就加点油，试着让我闭嘴如何？」

看到他挑衅的微笑，亚拉基亚憋住烦躁，别过视线。眼角余光瞄到的瑟希鲁斯，边把手放进袖子里，边摇动肩膀。

搞得亚拉基亚越来越不爽。

「好了。嗯。」

看对话告一段落后，哥兹轻咳一声好转变话题。

他碰触自己满是伤疤的严肃脸庞，低头直盯着卡夫马看。在他的注视下，卡夫马立正站好，脸上带着紧张。

「请问有何吩咐，哥兹一将？」

「你知道自己为什么被叫来东部前线吗？」

「──。在蛹里面的时候，有微微听到。」

「就算变成黏答答的液体，也还是得听见啊。」

手贴嘴巴，瑟希鲁斯对亚拉基亚讲悄悄话。对方无视他这举动，只是看着事情发展。

抱起粗臂的哥兹听了卡夫马的回答，沉重点头。

「呼嗯。既然有听到，那就好说了。此次远征以镇压叛乱为目的，目标是以卡欧斯弗莱姆为据点的夜鸣•魅时雨。然后，会根据在那边的活跃程度……」

「决定目前悬缺的『玖』的继任者。」

「没错。我已经向陛下推荐你。」

挺起罩着黄金铠甲的胸膛，哥兹替卡夫马感到骄傲。

现任「九神将」亲自推荐，假如想要「玖」的位置的话，一定是渴望到迫不及待吧。

但是听了这话的卡夫马表情并没有变开朗，亚拉基亚歪头不解。

「你不想当？」

「──。不，我可以肯定地说不是那样。只是，我对自己是否与那地位相应，内心存疑。」

「自己是否相应……」

「我族的同胞对陛下造反，这是怎么也偿还不了的事实。这样一来，我怎么还好意思追求相当于皇帝陛下心腹『九神将』的地位呢。」

「……明明想要，却放弃？」

无法理解卡夫马的想法，亚拉基亚忍不住插嘴。

因为疑惑表现在声音里头了吗？被如此询问的卡夫马像是被责备似地脸颊一僵。可是，对于没有「放弃」这个选项的亚拉基亚来说，是真的不明白他在犹豫什么。

有想要的东西，为此需要地位，而且也有机会去获得地位。

既然如此，就没有道理不去挑战。要是挑战了却犹不能及的话──

「那时就只能死了。」

「……当然，我不怕死。假使由我填补上『九神将』的空位，亚拉基亚一将对此没有异议吗？」

「……不就只是，由能当上的人当上吗？」

被询问意见，亚拉基亚老实说出真心话。

其实，不管卡夫马有没有当上「玖」，跟亚拉基亚都没什么关系。当然，假如是看准亚拉基亚的地位，想要抢夺瑟希鲁斯的位置的话就另当别论。

「现在的阵容虽然维持了很长一段时间，但『九神将』也有换人过。……只是没想到，巴尔罗伊会离开。」

「因为巴尔罗伊先生是个好人嘛。他陪我说话聊天的时候几乎不会露出讨厌的表情，好人不长命是真的耶。」

「巴尔罗伊可是企图暗杀陛下。称不上好人吧。」

「或许以哥兹先生的角度来看是这样啦。」

手在后脑勺交握，瑟希鲁斯苦笑回应口气不好的哥兹。

原本的「玖」巴尔罗伊•特梅格里夫──企图推翻文森，最后壮烈死亡，不过亚拉基亚也不讨厌他。

虽然是个多话的男人，但会根据对方体贴地改变应对方式。跟话少的亚拉基亚会保持适当的距离，老实说，跟他讲话很轻松。

因为平常都在对付一个完全不会顾虑己方心情的男人，就更加觉得难能可贵。

因此，听到巴尔罗伊谋反丧命的消息时，着实大吃一惊。

「没想到巴尔罗伊先生是被王国骑士杀死的。要是能先砍掉由里乌斯先生的脑袋的话，巴尔罗伊先生也比较能安息吧。」

「王国骑士的脑袋吗？这未必是你的真心话吧。」

「正是正是。就算砍掉由里乌斯先生的脑袋，巴尔罗伊先生也不会高兴啦。──但如果是『剑圣』殿下的脑袋的话，可能就另当别论啰。」

顿时，亚拉基亚、哥兹和卡夫马三人因本能而反射性地僵直身体。

原因出在凝视虚空的瑟希鲁斯，浑身散发出清澈剑气。

佛拉基亚最强的剑客，朝着在虚空想像的某人所发出的剑气余波──

「──」

讨厌瑟希鲁斯去想远在他国的对手时的那张侧脸。

亚拉基亚对瑟希鲁斯和那个「剑圣」抱持着莫名的愤慨。明明要杀死瑟希鲁斯、抢走「壹」的位置的人，是自己才对。

那种彷佛周围的人都入不了他眼的举止，真的叫人火大。

无论如何──

「卡夫马二将，你觉得担子沉重，我能理解。但是所谓的机会，并不会顾及我们的状况。就是这么一回事。」

「……我很明白，哥兹一将。请问其他的候补者是？」

「──。跟你一样立于候补的人选，是由宰相贝尔斯特兹推荐的。」

抱起粗手的哥兹沉重回答。卡夫马面露疑虑。不是武官，而是由文官宰相推荐，想必叫他很在意吧。

「我们已经错过会合的预定时间大半。陛下对展示出能力的人很宽容，但我可不像陛下那么宅心仁厚。为了尽早除去陛下的烦忧，必须投注心血。」

「好啦好啦，只要做出成果就不会抱怨，不就是佛拉基亚的风气吗？只是没守时，这种缺点等到回顾的时候就会觉得很可爱啦。」

「那么，被比较的双方如果都做出成果，可以获得好评的就是守时的那一方啰。」

「哥兹先生真的很擅长比喻耶。」

讲到另一个候补者就心情不好的哥兹，讲话尖锐到让瑟希鲁斯投降。

别人的地位进退，他本来不打算认真讨论的吧。早早放弃拥护的瑟希鲁斯盯着会议室的窗户看，放弃表达更多意见。

见状，亚拉基亚重新看向卡夫马。

「所以，要怎么办？」

「──。怎么办是指？」

「你要当九神将吗？还是不当？」

虽然不是瑟希鲁斯，但亚拉基亚也对卡夫马的晋升毫无兴趣。

但既然作战指挥官是哥兹，那卡夫马的选择便会影响到哥兹的想法吧。所以只能要他快点做出决定。

明明有想要的东西，却做出妥协。尽管自己对这种想法丝毫不赞同──

「反正随你高兴。」

「──唉。阿妮亚、阿妮亚，可以过来一下吗？」

「……不可以。」

亚拉基亚催促卡夫马赶快下定决心，得不到教训的瑟希鲁斯此时呼唤她。

想要置之不理，但又知道他是个对方没反应的话，就会一直叫到对方有反应的人。因此百般无奈之下，只好看向瑟希鲁斯。

结果当事人一手支在桌上拄着脸颊，另一只手指向窗外。

「天上来了一群飞龙，但那是不可以砍的吧？」

如此这般，他用温吞的态度若无其事地传达出事态有异。

12

「────」

「哇～满是杀气。这么多的飞龙，就算是梅佐雷亚也不常见吧。」

「闭嘴，然后去死。」

来自四面八方的金色狰狞眼神围成一圈，置身在漩涡内的两人，对话却还跟平常一样。

其他手拿武器、远望状况的士兵们全都紧张兮兮。

只要是帝国人，知道飞龙有多凶暴的机会要多少有多少。有时还会发生所谓的飞龙灾害，像是一整个村落被进入繁殖期的飞龙毁掉之类的。

而这样的飞龙突然以超过三十只的群体出现，也难怪他们会这么警戒了。

「冷静！那不是敌人！是我方的人！」

高声大喊的哥兹推开士兵，走到前头。

以军营中庭为中心，飞龙群正大光明地将瞭望台和外墙当成栖木。粗暴的空气支配现场，一名少女站在飞龙群正中央。

从一头飞龙背上慢慢降到地面的少女，她就是──

「──玛德琳•恩夏尔德对吧。你的事我听说了。」

「……龙的事？」

「龙的……？」

一瞬间不懂对方的答覆在说什么，哥兹皱眉。

回应他的少女个头不到哥兹身高的一半，外表也是年幼且楚楚可怜的样子。但是仰望哥兹的眼神却未有丝毫胆怯。

就只感觉得到，她在判定名为哥兹的「生物」有几两重。

另一方面，哥兹也同样在评估少女。──她的本质根本不是外表那样的年幼少女，这从她驯服大量飞龙就能确定。

但她也不是毫无道理就为飞龙所爱的少女。证据在──

「该不会，那双角……莫非你是龙人？」

「……没错。」

「竟然有残存者……！」

从头部的两根黑角联想到的事实被对方肯定，哥兹很是惊讶。不过这份惊讶，在后面歪头的两个「九神将」却无法理解。

跟哥兹有相同惊讶的，反而是环视飞龙群的卡夫马。

「哥兹一将，竟说她是龙人……是真的吗？」

「至少，当事人是这么说的。……据说是已经灭绝的种族，不过听说龙人可以跟地龙、水龙还有飞龙互相沟通。」

「跟飞龙沟通……实在叫人难以置信。」

「不然，眼前这个景象要怎么说明？」

哥兹用下巴示意飞龙，反问语塞的卡夫马。

在军营收起翅膀休息的飞龙们，也压抑着狰狞本性，老实待机。即便运用「操飞龙」来驯服飞龙，一个人顶多也只能和一头飞龙沟通。也就是说，玛德琳能率领这么多飞龙的方法，无法用「操飞龙」来说明。

那么自然地，少女──不，玛德琳•恩夏尔德的身份，就是解答。

「贝尔斯特兹宰相是从哪里找到这个姑娘的……」

舌头道出颤栗，哥兹为贝尔斯特兹深不见底的人脉网愤恨咬牙。

就如前些天的评定会议上贝尔斯特兹所说的，玛德琳没有从军纪录和可以担保其家世的人。但若说是看出了她在民间的才能，却又令人难以置信。

所谓的龙人，就是这么特别的存在。既然如此，到底是从哪里获取了孵化的卵──

「──呃，哥兹一将！」

就在哥兹这样思考的瞬间，状况开始有变。

身旁的卡夫马睁大眼睛，朝前举起手。被纹有虫笼族独特刺青的手针对的玛德琳，从背后的包包拔出飞翼刃。

以少女的身材来说大到过头的飞翼刃，锐利刀刃就抵在哥兹的粗脖上。

就这样，玛德琳用颜色与哥兹铠甲相同的双眼仰望他。

「不准侮辱龙。你那眼神，就是对龙的侮辱。」

「──」

是从哥兹方才的眉目表情洞察到其内心吧，声音饱含怒意。

心高气傲的龙人，绝不容许被侮辱或轻视。为了一雪侮辱甚至不惜性命。这种态度就是导致这种族灭亡的原因。

不过，在灭亡之前，龙人已经把超过十个种族给逼到灭亡了。况且既然还有玛德琳在，那龙人应该称不上是灭绝。

不过，其存亡端看玛德琳在场的行动。

「……别做蠢事。我自己也还没习惯到可以手下留情的地步。」

卡夫马平静警告，玛德琳稍微瞄了一下自己的脖子。

爬在少女白皙颈项上的，是从卡夫马手上伸出的绿色荆棘。在还是蛹的状态时就已经施放过的荆棘藤蔓，如今正绕在玛德琳脖子上。

这个荆棘似乎就是卡夫马变成蛹之后摄取到的新虫之力。只不过就如他说的，发抖的荆棘离完美驾驭还远得很。

「──吼吼！」

再加上自己的公主被威胁，使得飞龙们开始群起吵闹。

包围军营的飞龙活跃起来，发出凶猛叫喊，原本被哥兹要求冷静的士兵们又开始紧张，个个都准备要拔出武器，气氛一触即发。

这样下去别说攻下魔都，根本会先上演同室操戈。

在演变成那样之前，必须收拾场面。就在哥兹这么想的时候。

「好了好了，各位，冷静下来。──哥兹先生都在伤脑筋啰。」

说完，穿着草鞋踏进众人眼帘的人影，一句话就吞噬营内的气氛。

悠然而立的和服青年瑟希鲁斯，样子就跟先前一样没有变化。真要说起来，只有一处不同，那就是他把手放到了刀柄上。

──光是这样，瑟希鲁斯•塞格姆多就支配了整个军营的气氛。

「──！」

这名剑客的步伐，让玛德琳睁大双眼。

比起直接威胁自己性命的荆棘、污蔑龙人骄傲的哥兹，只是悠哉走路的瑟希鲁斯更吸引她的目光，令她一动也不动。

而且，感受到延伸出去的荆棘在胆怯的卡夫马，还有突然停止喊叫、缩起翅膀的飞龙群也一样。

虫笼族的年轻英雄、龙人残存者、狰狞的天空霸者，在天灾面前全都明哲保身，只能祈祷性命被保佑。──而瑟希鲁斯就是那个天灾。

被称为「蓝色闪电」、会走路的天灾，就是名为瑟希鲁斯•塞格姆多的剑客。

「你、你是、啥恰……！」

「啥恰？你刚刚说『啥恰』？那是龙人的方言吗？」

「你这种存在，太奇怪了！！」

发出活像哀号的大叫，玛德琳大幅后退。让荆棘离开她脖子，把虫收回体内的卡夫马也屏息看着瑟希鲁斯。

这两人──不，被整个军营的人盯着看，瑟希鲁斯歪头不解。

「嗯～受众人注目我是不讨厌啦，可是这跟我期望的方向有点不同耶？」

「你的不满之后我再私下问你。幸好，脑袋似乎冷却下来了。」

拍拍看起来不怎么服气的瑟希鲁斯肩膀慰劳他后，哥兹看向瞳孔变细的玛德琳。她全身都在警戒瑟希鲁斯，同时对哥兹的注视有所反应。

「我的目光若是失礼的话，那我跟你道歉，玛德琳•恩夏尔德。」

「……别让这个怪物，接近龙。」

「知道了。」

瞪着瑟希鲁斯的玛德琳如此要求，哥兹可是求之不得，点了点头。

瑟希鲁斯总是制造问题，但这次他的存在往好的方向发挥了作用。在战场以外的地方也能派上用场，在哥兹看来是很稀有的体验。

「不过，因为瑟希鲁斯在场而使得状况变复杂的情况也不在少数……」

「慢着慢着！既然都夸奖了，就夸奖到最后嘛，哥兹先生！不好好夸奖的话，我也会闹别扭喔！不可以太严厉，绝对不可以……对吧，阿妮亚！？」

「光是存在就麻烦……」

瑟希鲁斯一开口，马上就糟蹋掉方才帮上忙的功劳，结果被亚拉基亚拉住领子强迫退下。感谢亚拉基亚的贴心，哥兹手插腰看向玛德琳。

为了表示自己已经实现所说的话，他用下巴示意周围。

「那么，请叫飞龙们静下来。营里的士兵们都放下武器了。彼此都是同一边的，就别再起多余的冲突。你懂吧？」

「──。懂。」

点头后，玛德琳朝周围的飞龙使眼色。

不是出声，也不是打什么信号，仅靠眼神便能沟通。

极为自然地就办到这点，令哥兹不得不承认她就是真正的龙人。面对哥兹的视线，玛德琳眯起眼睛。

「干嘛。看着龙的眼睛，无礼。」

「失敬了。这么说来，都还没打招呼。我是哥兹•拉尔冯，奉皇帝陛下命令，以这个军营为据点，攻下魔都的指挥官。」

「……龙是玛德琳•恩夏尔德。」

「嗯，我知道。其他的人……之后再跟你介绍吧。」

亚拉基亚难得帮忙把问题儿童带远，没必要刻意让瑟希鲁斯的存在感回归，让玛德琳反感。

眼见玛德琳不时瞥向瑟希鲁斯，于是哥兹改变位置，挡住她的视线。

「所以，你为什么迟到？所谓的军队，目的就是众多将领士兵要成为一个生物，集体行动。要是有扰乱步伐的人，身体就无法产生应有的机能。」

「────」

「要是让手脚、尾巴和翅膀擅自动作，就会很伤脑筋。懂吗？」

哥兹说明的时候用玛德琳的身体来比喻──龙人的特征除了头上的黑角，还有长在背后的小翅膀。

尽量留意让说明简单易懂，这种小心思是哥兹的常识，也是在帝国军队里头培养的。尽管这并非一切，但至少哥兹是这么想的。不过，既然可以使唤整群飞龙，那哥兹认为，玛德琳也应该理解团体行动的重要性。

事实上，听了哥兹的说明后，玛德琳轻轻点头。

「嗯。知道就好。那么，我再问一次。你到底是怎么了？假如只是迷路的话……」

「──龙，刚刚在魔都。」

「……什么？」

假如是因为不熟悉路况，才花了一点时间会合的话，那就算了。

可是得到的回答却背叛预料，哥兹以为自己听错了，但仰望他的玛德琳又重复一遍同样的回答。

「龙，刚刚在魔都。──那个女的，说要传话。」

「────」

有一刻，哥兹犹豫该不该斥责玛德琳。

但是这边该优先做的不是矫正玛德琳的常识，以及追究她无视作战行动，独断专行。而是审核她所带回的情报。

她一说「那个女的」，哥兹马上就猜到是谁。

因此──

「说来听听。那个母狐狸到底要你传达什么？」

「──逃离军营的，士兵们。」

「────」

「逃离军营的士兵，在彻底夺走他们的性命之前，她没打算收手。」

玛德琳淡淡陈述要转达的话，哥兹听了眯起眼睛、手扶嘴角。让手掌感受自己的胡须，同时静静地思考。

「军营的士兵……莫非是，哥兹一将！」

「我知道。──虽然我一直疑惑她是基于何种目的而开始造反的。」

听了相同报告的卡夫马声音急促起来，哥兹低沉回应。

屠杀整个军营的士兵，扰乱皇帝文森治世的夜鸣•魅时雨。她是想到什么而开始造反，又是因着什么而决定造反？

这些问题的部分解答，偏偏是从玛德琳口中传来的。

「──在攻进魔都之前，我们必须先请示陛下。」

没错，怀着苦闷的心境，哥兹瞪着屹立在远方的魔都。

13

「──要杀光逃离军营的士兵，是吗。」

「没有讨论的价值，不得不这么说呢。这种要求，根本不能说是要求了。」

听到魔都最前线的军营传回来的情报后，帝都水晶宫也静谧地产生动摇。

在缺乏华丽感的办公室内，靠在办公桌上的文森，目光自镜子里头哥兹的严肃面容上移开，内心思索。

取而代之面对镜子、朝哥兹出声的是也在场的奇夏•哥尔特。

担任皇帝参谋、浑身无一处不白的男子，用手抚摸自己的尖下巴。

「尊崇强者是帝国习俗……话虽如此，要是误以为自己所有的任性都能实现的话可就伤脑筋了。首先，以这道理来说……」

『那我的愿望全部都没实现很奇怪耶！』

「────」

「哥兹，让那个愚者闭嘴。会妨碍讨论。」

文森代替沉默的奇夏，朝镜子那头发出指令。『遵命。』先是得到沉重回应，接着，轻薄的声音便逐渐远去。

「对话镜」是要与远处联络不可或缺的「流星」，但唯一的缺点就是好不容易跑远的大笨蛋也能像这样交谈。

无论如何──

「──把夜鸣一将的要求视为戏言一笑置之，会不会太早了呢？」

「哦～虽说是你推荐的人带回来的情报，但你可真执着呢。」

「这种情况比起是由谁带回来的，出处更重要吧。当然，身为推荐者，不能说没有私心就是。」

「哼。比起带回来，说是被要求带回来比较恰当吧。」

鼻子喷气的文森厉目看去，贝尔斯特兹垂下满是皱纹的脸。

水晶宫的办公室里有宰相、参谋和皇帝共三人。用来审查透过对话镜收到的情报，指示攻打魔都的军队下一个方针，这样的阵容可说十分充分了。

议题当然就是透过玛德琳•恩夏尔德传话的夜鸣•魅时雨的真正意图。

「我认为，很难将这视作单纯是在搅乱军心。说起来，要是玛德琳殿下没有擅自行动的话，根本就没有机会传达那句话。」

「谁知道呢。所谓的战争，在开始的时候也要想到让它结束的方法。虽然在下见识浅薄，但造反不也一样吗？换言之……」

「打从一开始，就预定了一个结束战争的妥协点，是吗。」

三人凑在一块儿，推敲夜鸣提出明确要求的真正用意。

当然，经常会有「未经多想就恣意妄为」这种最糟糕的答案，但是文森看不出那种可能性。即使「九神将」是只看武力来挑选，然而每个人都有各自的想法，以及为了实现心愿的计划。

例外的只有「壹」瑟希鲁斯•塞格姆多。

要说哪里有问题的话──

「──为什么，拘泥在军营士兵的性命上？」

这次叛乱的决定性起头源于军营的士兵，同时也被指定为结束的条件。不过，对方并非为了挑衅文森或帝都，才挑选了他们当祭品。

一定有非他们不可的理由。目前会议倾向这样推测。

「向西方挥军的葛路比•格姆雷特呢？」

「当地有暴动的火种。目前的状况无法调动。」

「缺席评定会议的奥尔巴特•丹克肯呢？」

「说在家乡处理流行病。虽然在下也已一把年纪，但较在下年长二十的他，工作表现却比在下出色。或许不太能对他做出无理要求吧。」

「军营是距离魔都最近的据点，在夜鸣•魅时雨统治的卡欧斯弗莱姆旁边啊。」

「嗯。连在帝国都算少数的亚人和族群都喜欢移居过去的边境之地。因此那边若发生像是问题的事件，都只会是夜鸣殿下引起的，可说是异常之地。」

「死亡的军营士兵有三百，下落不明者有十多位。」

「听说现场凄惨到让人想要背过脸。每一个人全都被仔细地断头。──陛下？」

冷静地抓住可以推进思绪的情报，文森难得陷入沉思。

不过，就算说是长时间思考，也不过才不到十几秒的时间。只是对皇帝那任何事都能在瞬间导出最妥善方案的脑袋来说，十几秒的思索极其罕见。

然后──

「──龙人的残存者，真亏你找得到。」

出其不意的话题突然抛来，但贝尔斯特兹的表情没有动摇。

白发老人摇头道：

「哪里哪里。发掘和采用难得人才，是使帝国繁盛不可欠缺的要素。在下也是透过向陛下推荐这种人才，才能放心觉得多少完成了宰相的部分职责。」

「哼，讲些诡诈的话。但是这次帮了余的忙。」

「谨遵旨意。」

表露忠诚到虚情假意的地步，贝尔斯特兹当场深深弯腰。看着他这一连串举措，文森呼唤自己的左右手：「奇夏。」

「在。什么事，陛下？」

「前往当地。余的期望，你早已明白了吧。」

「这可说是过奖了。若您能更明确下令，就能让小的不用怀抱多余烦忧。」

「你若想天真就顺你的意。准备折磨心头吧。」

陈述未被采纳，希望被拒绝的奇夏夸张地以手掩面。当然，文森不会因为这样就推翻意见，皇帝对左右手的沮丧不屑一顾。

相反的，是注意力重新转向对话镜。

「就跟听到的一样，你们该做的事没变。攻下魔都，让夜鸣•魅时雨知道自己做过头了。」

『是！知道了！……还有，陛下。』

「什么事？」

在对话镜另一头气势十足回话的哥兹，态度变得谨慎。文森对此蹙眉，哥兹则是挺着厚实胸膛道。

『臣知无礼，但请给予时间。卡夫马•依鲁鲁库斯二将想请陛下直接赐言。』

「卡夫马•依鲁鲁库斯啊。无妨。到镜子前面来。」

『是，马上来！同时……』

『来了来了来了！陛下陛下！听我讲一件事就好！』

哥兹离开，接着露脸的却是原本被斥退的瑟希鲁斯。

错估与对话镜的距离，直接在镜面显示大脸的佛拉基亚最强剑客无视距离感，直接对皇帝出言不逊。

「假如有人能割断你的脖子，余早就以不敬为理由处分掉你了。」

『又在讲无法做到的事了！唉，就是啊，我想说再过不久就会直接跟夜鸣小姐杠上，所以想问您有没有话要我转达的？』

「────」

『看嘛，夜鸣小姐不是一直在引起陛下的关注吗！搞不好是这辈子最后的机会，要是有一句话可以让她没有后顾之忧跟我认真打，那我会很高兴的。』

跟一般人的顾虑天差地远，瑟希鲁斯用不同次元的理由想要皇帝赐言。跟方才恭敬有礼的哥兹之间的落差，让文森忍不住失笑。

当然，只是嘴角失守的样子，没有让任何人看到──

「是有要告诉她的话。你就用心当好传话的角色吧。」

『好的好的，放心交给我！感觉确实就像是皇帝陛下的传令官呢，真是奢侈加三级。』

「别误会了。还有，完成后立刻回到你原本的工作。你是──」

『──陛下的白刃。当然，我了解。』

平常察言观色的程度令人绝望的男子，只有在这种时候才懂得看脸色，实在不懂他脑子怎么运作的。就算要追根究底，很遗憾地，文森得做的事太多了。

沐浴在参谋与宰相的视线中，文森肃静审慎用词。

宣告的话语十分直接，最重要的是意图很明确，充满对叛乱者的蔑视──

「就把余的话跟刀刃一并传达吧。这正是余的武器应有的意义。」

14

──决战的导火线被点燃，闪电穿过化为战场的城镇。

许多亚人混居，被揶揄为混沌都市的魔都卡欧斯弗莱姆。

杂乱无章的建筑物林立，随心所欲添加踏脚处和扩建建筑物的市容，完美地符合了「混沌」之名。

就算对都市景观没有一丝兴趣，也仍暂时被那份不整齐给吸引了目光。话虽如此，注意力也因为跑在正下方的影子吵闹而撑不久。

「唉呀～果然跑第一的感觉就是爽！难得可以跟『九神将』互砍，这机会怎能错过！啊，跟阿妮亚的互打不算！」

「去死。」

草鞋鞋底蹬着地面，猛然破风的瑟希鲁斯的碎嘴融入都市中。勉强追上他的速度，亚拉基亚皱起娥眉这样回答。

对话听起来十分悠闲，但这段期间发生在这两位帝国最强战力周围的事，已远远超出常规，非常足以验证两人身负的评价了。

「哎哟，诸位配角，对不起。重头戏在后头，所以得在过场收拾掉你们！」

没错，带着常人无法理解的理论，使出的斩击横过天空。

只要一眨眼就追不上的闪电，接连啃食挡路的人影，每个人别说接触了，连残光都追不上，血风就散落一地。

而运气好没站在闪电行进路线上的人也──

「碍事。」

跟着简洁的话语一同倾注的火球，从一头开始烧起被漏砍的人。

做出这事的人，是在自己腿部发火，不需要像鸟或飞龙那样鼓动翅膀便能飞行的「食精灵者」。

瑟希鲁斯和亚拉基亚这两名「九神将」所向披靡，以惊人速度踏破魔都街道。不过──

「难得可以和夜鸣小姐再战，却要带着阿妮亚，我不能接受啦～！」

「那是我的台词。」

「哥兹先生根本不信任我们嘛。要是因此出了差错，夜鸣小姐跑去另一边的话，那我都不知道自己来这儿干嘛了啦，讨厌！」

在没有合作意图的拌嘴下，配合瑟希鲁斯的亚拉基亚叹气。

亚拉基亚之所以与瑟希鲁斯同行，是按照指挥官哥兹的吩咐。老实说，亚拉基亚的脑子里根本没有战术这概念，所以除了个人感受以外，没法提出其他抗辩。

不管怎样，既然这是为了胜利，那也好勉为其难地接下监视瑟希鲁斯这个职务。理想的话，就是赢下一场会让瑟希鲁斯懊悔的胜利，那样最好。

虽然为了实现这个目标，最快的方法是以失败告终──

「──看起来闹得相当兴奋呀。」

穿过都市正门后，正大光明奔驰在大马路上的瑟希鲁斯停下脚步。

出声的人，就是傲立在大马路的正中央、盯着这边看的和服妖媚女子。──一看就知道是强敌。亚拉基亚这么判断。

「那是……」

「嗯，就是她喔，阿妮亚。──你好你好！好久不见，夜鸣小姐！」

双腿化成火焰的亚拉基亚选择在空中调整姿势。抛下飘在空中的她，往前走的瑟希鲁斯朝着女子──夜鸣•魅时雨用力挥手。

面对他气势磅礡的问候，夜鸣摇晃手中的烟管。

「还是一样是个大嗓门呢。又送您过来，代表您十分得陛下赏识喔。」

「陛下赏识我？没有没有，没那回事没那回事。那一位不是用赏识不赏识这种尺度来看人。所以才会一年到头都板着脸孔！是劳碌命的代表！」

手指按着自己眉心的瑟希鲁斯，想到什么就讲。夜鸣眯起眼睛看他。

在亚拉基亚听来就是没有价值的胡言乱语，但夜鸣一脸认真地接受了，接着瞥向亚拉基亚。

目光简直就像在征求亚拉基亚的意见，令当事人有点困扰。

「第一次见到您呢。知道奴家是谁吗？」

「听说过。亚拉基亚。以后请多指教。」

「冷漠却又有好好打过招呼。真是有礼貌啊。」

振臂后卷起和服袖子，夜鸣当场弯腿行礼。他人有礼问候便回以周到款待，接着她问道：

「所以，那个先露脸的龙人姑娘，有把话传给您们吗？」

「传话……」

「哦哦，有喔有喔，有听到喔！玛德琳小姐说的话嘛。哥兹先生有好好跟陛下说了！」

瑟希鲁斯拍自己胸膛，大声回答夜鸣的问题。闻言，夜鸣颤动眉毛，视线里掠过微弱的感情热度。

在亚拉基亚的眼中，看起来像是微弱的期待。

既然如此，夜鸣会很沮丧吧。

要说为什么的话──

「陛下的回答是？」

「要军营里每个士兵的命嘛。咳嗯。──不值得考虑。愚蠢愿望的报偿，就用自己的血来偿还。好像是这样。学得像吗？」

瑟希鲁斯先咳嗽一下，然后模仿皇帝文森说话。真是不知恐惧为何的人，而且学得完全不像。他有要模仿对方的意思吗？

亚拉基亚因此赏他白眼，而希望落空的夜鸣轻声吐气。

「那么，奴家的答案很简单明瞭……用血偿还就行了吧？奴家疼爱的东西流的血，就要以千倍的血偿还。」

「哎哟，反而生气了。阿妮亚，是我的错吗？」

「整体来说，是陛下和瑟希鲁斯的错。」

品尝到空气似乎发热沸腾的感觉，亚拉基亚握紧手上的细长树枝。

静谧的战意高涨，见夜鸣缓缓摇头，瑟希鲁斯故作轻松地放话，同时拔出青白刀身。

「服了你了。算啦，本来就打算要跟你打，这下也省得费工夫！那么，我们来当你的对手，夜鸣小姐！──『蓝色闪电』，瑟希鲁斯•塞格姆多。」

「──『食精灵者』，亚拉基亚。」

往前弯腰的瑟希鲁斯，和增强腿部火势的亚拉基亚。

正面迎战两人的战意，夜鸣却没有丝毫怯意，还笑道：

「──『极彩色』夜鸣•魅时雨。这就隆重招待两位。」

15

从都市中央传来的剑戟声响之猛烈，让哥兹知道战斗已经正式开打。

夜鸣果然到正门这边了。她做出这个判断没什么好讶异的。当然，就算她是来这边，自己也会作为一名「九神将」全力迎击。

「瑟希鲁斯和亚拉基亚一将，似乎跟夜鸣•魅时雨打起来了。」

「呣，真的吗？为什么肯定……」

「仔细听就知道了吧。可以听见武器撞击的声音。」

哥兹说，跑在旁边的卡夫马目瞪口呆，接着把手贴在耳后，按照哥兹说的仔细倾听。

「您听得见？在这场乱战当中。」

「声音也各有各的特征。别看我这样，我可挺喜欢乐器的。」

这个嗜好经常被人说不适合，但哥兹喜欢音乐。不管是听还是演奏都喜欢。会结识妻子，也是因演奏会产生契机。

音乐丰富了哥兹的人生。因此在战场上，声音也会帮助哥兹。

生来就具有超越旁人的听觉，是哥兹为数不多的宝物。

「但是，这个城市比原先听说的还危险啊。」

「是的，我也有同感。」

说话的同时，以哥兹和卡夫马领头的帝国军进入魔都。而卡欧斯弗莱姆迎接从后门挥军的他们，城市以奇形怪状的构造来迷惑入侵者。

创作者八成没有要阻扰他们的意图吧。就只是靠着杂乱繁多的想法，以及当天的心情而拼接出来的市容。

而在这种充满混沌的市容生活的人，也是符合混沌的居民。

「哦哦哦哦──！！」

边吼边冲过来的，是连正经武装都没有的魔都居民。

身上没有任何护甲之类的东西，只有气势和士气不输正规军。这些人不是有勇无谋，而是靠确切的力量在支撑──

「──夜鸣一将所施展的秘术。」

「术式详细不明，但魔都居民每个都拥有非比寻常的力量。所以──」

说到这儿话音打住，哥兹用下巴示意的地方，经过武装的一队士兵正在接受居民们来自正面的突击。──不，是试图接受。

「呜哇啊啊啊啊──！？」

下一秒，一只眼睛点燃红色火焰的魔都居民，撞飞五名架着大盾的士兵。而后头的士兵也都阻挡不了男子继续冲刺。

这样的光景，在进攻都市的各处上演。

「那就是，魔都难攻不破的原因……！」

「嗯，没错。虽然多少有个人差异，但你就当作卡欧斯弗莱姆的居民每个都有十个士兵的力气。因此，才会需要我跟卡夫马二将你的力量。」

「──」

用力咬牙的卡夫马，胆颤地抚摸自己有刺青的手。这举动看起来莫名不安，于是哥兹问道：「你害怕吗？」

听到这问话，卡夫马猛然抬起头。

「我不怕！」

「既然如此，你为何要向陛下那样说？说自己不适任九神将。」

「那是……」

说不下去的卡夫马，正经八百的面孔满是苦涩。

开战前透过对话镜直接跟文森对话的卡夫马，拒绝了哥兹推荐的「九神将」荐举案。

当然，身为推荐者难免觉得没面子，可是哥兹跟卡夫马寻求的不是谢罪，这点卡夫马也知道。

想要的不是道歉，而是自己为什么会做出这种决定。

「是为了陛下……可以说是为了佛拉基亚帝国。在重要时刻却无法正常运作的『将』，难以回应陛下的期望。」

「──。那么，没打算爬更高啰？」

「不，这只是因为现在的我没那个价值。」

凛然眼神宿着光彩，卡夫马凝视着哥兹的脸后才这么说。

辞退爬升到「九神将」的光荣荐举，让哥兹•拉尔冯颜面扫地的二将卡夫马•依鲁鲁库斯，决心走在正确的道路上。

不加以认同的话，被赋予一将地位的哥兹就真的面上无光了。

「卡夫马二将，你为何而战？」

「──为了神圣佛拉基亚帝国，和统治帝国的皇帝陛下！绝无二心！」

「呼哈哈哈哈！」听了他堂堂正正的宣言，哥兹大笑后，说：

「那么，就抬头挺胸吧，卡夫马二将。──唯有建立自己和旁人都认同的功勋，推荐你当『玖』的我才挂得住面子！」

「是！一定会！」

这么回答的卡夫马，背上长出透明翅膀，带着他的细长身子飞向高空。

斜瞄一眼，哥兹也举起自己的拿手武器──黄金锤矛，正大光明地加入战场。他疯狂肆虐，为了彰显皇帝陛下的威光，演奏出极大声量。

再来就是──

「──陛下，请随意。无论结果如何，只要是陛下的想法，我等将兵唯有赌上性命服从。」

16

彷佛烧灼般的战斗气味，令玛德琳•恩夏尔德抽动鼻子。

遥望就看得见的魔都正在开启战端，大量鲜血流失，性命空虚散落。

但这没什么稀奇的。性命不管在哪都会失去，血液不管在哪都会流淌。即使是玛德琳留守的军营也一样。

「────」

营地内飘荡着极为浓厚的血腥味。

似乎遭受强烈攻击，营中的建筑物本身也呈现半毁状态。集结起来的士兵们已出征，只留下最低程度的兵员数量，恐怕是放弃这个建筑物了吧。

索性宣泄一下情绪，把这里夷平算了。虽然曾经冒出这样的念头。

「不要做蠢事。龙，是更骄傲的物种。」

这样戒惕自己，让浮动的情绪平息下来。

放任感情施暴，咬人啃人都是不可以的。那不是坏事，但是听说那样在人类的世界里会不受欢迎。

没打算要讨好人类，只是被数量多的他们疏远会很麻烦。

而且──

「……竟然有那种人类，根本没听说。」

这样低语的玛德琳，脑子里浮现腰部挂着刀的蓝发男子。

难以捉摸的态度和笑容不止的人物，但玛德琳只凭一眼就知道了对方是个异于常轨的怪物。那个轻薄态度，一定也是拟态。

这是龙人末裔玛德琳本来不会品尝到的负面情感。

龙，必须总是强大又豪气万千，君临在所有生物的顶点。可是，却被那个人类的气势给压过了。

「是因为，龙还太小。」

低头看自己的手，玛德琳的低语中掺杂着不甘。

要是可以发挥龙人原本的力量，根本没必要畏惧区区一个人类。可是，玛德琳还年幼，身为龙人还不够成熟。都怪这样，才会玷污种族的名誉。

为了洗刷这份屈辱，总有一天必须跟那个用刀男对峙──

「──哦哦～原来如此。确实是一眼就能看出。背后甚至还有长翅膀，小的看了也感动得无以复加。」

「呀呜！」

思考时靠着墙壁的玛德琳吓到肩头耸起。表情变得凶狠，是因为从后面出声的家伙让自己发出不愉快的声音。

而且对方还没礼貌地摸自己的翅膀，于是玛德琳恶狠狠地瞪向个子比自己高的男子。

「好大的胆子，胆敢评价龙的翅膀？区区人类少得意忘形。」

「这可真是，小的做了万分失礼之举，在此向您谢罪。小的庸俗的好奇心似乎稍稍冒出了头。」

点头后鞠躬，这样回答玛德琳的是给人一片白印象的男子。

不如说，对方是浑身上下只有白色的异样人物。头发是白的，脸也是白的，衣服和鞋子也全都是白的，简直就像是刻意舍弃自己的「色彩」。

那个穿金闪闪铠甲的男子是有说一眼就能认出对方。原来如此，确实是一眼就能认出的外貌。他毫无疑问就是自己在营里等待会合的人物。

「──」

她眯起眼睛，男子一派平淡的态度让玛德琳感到焦躁。

又是个面对自己却面不改色的大胆狂徒。那个住在闪亮石头城堡的女主人，在这个军营里遇到的金黄铠甲男，森林臭味男和裸女全都一个样。

就算去掉那个异常的用刀男，无趣的人还是很多。

也是有龙会称这种人为勇者吧。可是玛德琳没那么老成。她相信龙是应该被敬畏、恐惧的存在。

因此──

「你，跪下。」

「……跪下，真是奇怪的话。小的为何要那么做？」

「少啰唆，跪下。敢不听龙说的话？」

玛德琳指着裸露泥土的地面，强硬下命令。

男子犹豫了一下，接着顺从地当场单膝跪地。如此一来终于可以俯视对方，玛德琳抱起双手摆起架子。

「不要用高高在上的态度跟龙说话。你也好，其他的家伙也好，都不懂龙的伟大。」

「──。顺便请问一下，您说的其他的人是？」

「原本在这个地方的家伙。金闪闪铠甲男，裸女，还有用刀男。」

「都是跃然于眼前的面孔，但得由小的负责擦他们的屁股，还真是会让人痛恨起命运啊。──不过……」

「──？」

男子讲到这煞有其事地中断，令玛德琳皱眉。接着，男子维持跪地姿势，抬头看向玛德琳，白色的脸孔中，映照出唯一有颜色的黄色瞳孔。

「不知为何，四处替人擦屁股好像成了小的的工作。关于您的愤怒该如何回应，小的在思考这个问题。」

「──」

没错，这个直瞅着自己眼睛瞧的男子，并没有连心灵都跟着下跪臣服。玛德琳领悟到在物理层面上俯视对方毫无意义。

跟龙不一样，人类都是骗子。──即便不是真心服从，还是可以若无其事地跟对方下跪。

「……够了。站起来。」

「哦～已经气消了吗？」

「知道让你跪着也没意义了。以后再教你们龙的伟大之处。」

「如果您愿意这样，小的会非常感激。唉呀，太慢自我介绍了。」

得到玛德琳的许可，站起来的男子拍拍膝盖，重新鞠躬。连这举动都让人不悦，不过表达出礼仪的态度，让龙的矜持抗拒咬他。

诡异一笑，男子边俯视玛德琳，边报上姓名。

「小的名叫奇夏•哥尔特。受聪明又桀骜不逊的皇帝陛下命令，亲自远赴战争前线。今后还请您多多指教。」

「知道了。龙不自我介绍。」

「要是不认识彼此的话就伤脑筋了，不过小的已经听说过了，玛德琳殿下。──那么，该从哪里开始好呢？似乎没剩下太多时间的样子。」

东张西望的白色男子──奇夏佯装不知地这么问。

听了这话，玛德琳抽动鼻子，然后指指自己的鼻子。这是玛德琳刻意远离战场留在这儿的理由。

因此──

「让龙的鼻子派上用场吧。就借此告诉你，龙的水准跟你们有差。」

露出锐利牙齿的同时，玛德琳凭恃龙人的矜持如此断言。

17

『她说在铲除军营士兵之前都不会收手。虽然我跟瑟希鲁斯说要以血偿还，但你知道该做什么吧。』

尔后就被命令飞到当地，可以说这是信赖的证明吗？抑或是该怨叹自己无法违抗的权力者施加不当压力？真是难以判断。

就算想找人商量这件事，偏偏又爬到了没有上级可以商量的地位。因着这个自己不期望的地位，心情有多苦闷难受啊。

不管怎样，自己被赐予这个地位，就有相对应的责任，必须完成必要的工作。

至少，这是名叫奇夏•哥尔特这个人类的职业道德。

「话虽如此，情况有些难堪呢。」

「──？你对龙说什么？」

「没，只是自言自语。还请别在意小的。」

耸耸削瘦肩膀，奇夏这样回答。「这样啊。」玛德琳冷淡回应。接着她把手贴在地面上，鼻子嗅闻，再度开始追踪气味。

这么热心工作的态度，真希望让众多「九神将」也学习学习。但是，在不明所以的外人看来，这句话简直再糟糕不过了吧。奇夏心想。毕竟让外表年幼的玛德琳趴地闻气味，然后自己跟在满地爬的少女后头。怎么看都很奇怪。

龙人自尊心强，对于玷污骄傲者绝不留情。

虽然第一印象就跟这个传闻一样，但事情发展到这边后就一口气转变了。

被人状似稀奇地看待角跟翅膀，玛德琳对此大动肝火；然而被人看到在地上爬的样子，龙人的矜持却似乎没有受伤。

这方面，可以说龙人与人类的感性有差别吧。多亏如此，只要奇夏对眼前的画面传出去有多难听这点睁只眼闭只眼，这个搜索活动可以说就能毫无滞碍地进行。

「要是葛路比在，那个不好的名声也能被忘掉吧……陛下真的是坏透了。虽然不觉得是为此才策划远征的。」

「九神将」之一的鬣犬人葛路比•格姆雷特的嗅觉，在同为兽人系的亚人当中也格外突出。只要碰上他的鼻子，就算从帝国一头逃到另一头都会被追上，这种不好笑的笑话可是在帝国境内传播不已。

而且奇夏知道，这事意外地不能以玩笑来解决。

「毕竟就算小的跟陛下调换，没有投入十成功力就会被看穿。」

有战事之际，自己必须担任文森的替身，因此从奇夏的角度来看，能够骗过葛路比的嗅觉就成了决定性的指标。

不愧是除了奇夏和瑟希鲁斯这些一开始就指定的棋子以外，文森最先指名要加入「九神将」的人才。

能否代理葛路比的任务，奇夏是有点怀疑玛德琳的。单纯只因为龙人稀少，是没法胜任「九神将」的职责的。

──现在，奇夏和玛德琳两人在追踪的，是遭受夜鸣•魅时雨的袭击而陷入毁灭状态的军营幸存者。

只不过，他们在找的不是报告军营毁灭的局外人，而是真的逃离惨状苟活下去，却下落不明的十几人──从地狱生还的人们。

「报告说军营全灭，多达三百名士兵被屠杀。可是……」

军事用语的「全灭」，跟一般人用的「全灭」之间有认知上的差异。

在军队中所谓的「全灭」，指的是无法继续战斗的状态。其定义在各国都不同，以佛拉基亚帝国而言是一百人以内死掉九十人的话，就可以说是全灭。

也就是说──

「有十个人活了下来。你，和地上最伟大的男人都这么想。」

抽动鼻子，顺着气味走的玛德琳把奇夏最后想的话说了出来。对此，奇夏以指头扶着下腭，说：

「是呢～。考量到军营的惨状和下手的人是夜鸣一将，猜想人数会更少，不过就是有人幸存吧。而且……」

「而且？」

「夜鸣一将意外有着在最后关键松手的习惯。毕竟，她要玛德琳殿下传话就把您赶跑了。」

「才、才不是被赶跑恰！」

「恰？」

玛德琳大吃一惊，用字遣词出现的变化让奇夏歪头不解。但玛德琳马上就粉饰好表情，露出口中锐利的牙齿。

「反正不要做多余的事恰。……不要做多余的事。做那种事就像是偷看龙的鳞片内侧，只会缩短自己的寿命。」

「这样子啊，您的忠告我会谨记在心。……小的充分理解您的忠告的意思了，另外，可以问点问题吗？」

「────」

玛德琳撇头重新看向前方，再度四肢趴地进行搜索。没有出言拒绝自己的要求算是好事，奇夏又开始思索。

由贝尔斯特兹荐举为「九神将」的玛德琳•恩夏尔德，配合身为龙人的特异点来看，不清楚她是怎么跟贝尔斯特兹有交流的。

说到底──

「玛德琳殿下是因为什么原因而接受此次的任务呢？」

「……听了糟老头的请求。说如果接受这任务，就会站在龙这边。」

「站在您那边是吗。贝尔斯特兹宰相说的？」

「他叫那名字？如果是地上第二伟大的男人，就是了。」

假如皇帝是地上最伟大的男人，那帝国宰相被称为第二伟大的男人，至少在佛拉基亚帝国不能说是错的。

在军务上权力与宰相相提并论的「九神将」之「壹」瑟希鲁斯，简直就是白白浪费权势的代表。

更何况，没人会认为瑟希鲁斯是帝国第二伟大的人物。

『咦咦？我很伟大？请别乱讲啦，奇夏。你认为我会拘泥伟大不伟大那种头衔吗？会接下一将这位置是因为只要强大就能为所欲为，而且伟大的人根本不适合当主角，比较像是被人砍的角色！』

本人会如何回答，脑子里可以清晰描绘。

这十年来的交情，让画面重现得超出必要所需，让人退避三舍。

「不过，就跟糟老头说的一样。」

并未注意奇夏内心的煎熬，玛德琳突然这么说。

对此奇夏挑眉，玛德琳继续看着前面，抽动鼻子说：

「龙的血脉很稀少。他说，在地上遇到的家伙，全都会把龙当珍禽异兽吧。又说那些人会问一堆问题，可是不能生气咬别人的头。」

「原来如此。小的也想避免被咬头呢。」

「你也还有事要问龙吗？」

「呼嗯，这个嘛。」

玛德琳表明自己有贝尔斯特兹的指点和来自他的忠告，所以没打算再回应更多质疑，要求奇夏划清界线。

奇夏也没有被文森特别命令要试探她。

因此，这边就算放弃发问的机会也没什么大碍。

但是──

「嗯，还是有想问的。小的这人就是担心成性，为了替小小的心脏带来安宁，所以认为知识越多越好。」

「就会卖弄小聪明。少拿无聊的问题烦龙。」

「这是当然。──您的出身、受过的教育、家人组成、信念、爱看的书、战斗方法、龙人的生态、龙人的故乡、喜欢的东西、讨厌的东西、正义、厌恶、一天进食的次数、睡眠时间、喜欢的食物、惯用手、惯用眼、昼行性还是夜行性，还有其他很多问题。」

「────」

「可是，在这当中，若要选最想问的问题的话……」

奇夏罗列出想知道的情报，停下脚步的玛德琳一脸像在看有问题的人。虽然这点很令人遗憾，不过他也认为这是很正常的反应，于是接着说了下去。

凝视过来的金色瞳孔露出嫌恶，奇夏朝着她问道──

「──您的名字，是谁帮您取的呢？」

「……咦？」

「您的名字。玛德琳•恩夏尔德，您这个名字。」

可能完全在料想之外吧，玛德琳的双眼充满困惑和惊愕。

反应就跟外表一样稚嫩。贝尔斯特兹刻意让她讨厌周围，并保持她年幼无知的状态，是用来预防露出马脚的机制吧。

其实，奇夏也不认为可以得到难能可贵的情报。

不过──

「据说已经灭亡的龙人，相传都是跟龙一起生活。听说也是有龙能够理解语言。所以小的斗胆猜测，玛德琳殿下的名字也是龙取的……」

「──不是。」

「哦。」

「龙的名字，是龙的家人给的。」

小手贴着自己胸膛，玛德琳回答得像在告知秘密。

说这话时轻声细语，像在对待易碎品一般纤细。奇夏眯起眼睛，很快相信她没有说谎。打从一开始，她可能就不会说谎。

谎言是弱者的武器，是用来对付强者、看不见的爪牙。

强者的爪牙肉眼可见。身为龙人的末裔，她完全没理由说谎。

「──」

反过来想，玛德琳的名字姑且不论，要是调查「恩夏尔德」这个姓氏的话，或许会有什么收获吧。这么冷静思考的自己实在很讨厌。

只是，玛德琳口中的「家人」，对她而言是真的无可取代的吧。从声音和表情就能洞悉。

关于这一点，人类和龙人之间倒是没有差异。──不。

「──所以，龙来到了地上。」

接着讲出口的话，虽然平静，却有着闲人绝对无法涉入的冰冷温度。

听到这儿，奇夏重新做出人类与龙人没有不同这样的结论。

不管流着怎样的血、过着怎样的生活，「复仇者」的态度都一样。

──玛德琳眼中擦不去的憎恨，令奇夏理解到这点。

「……到了。」

就在奇夏做出结论时，趴在地上的玛德琳站了起来。她拍拍手拨掉泥土，用下巴示意通往深山的山路入口。

大致看看周遭，就知道这是远离人烟、生活很不方便的土地。

「在营中闻到的人类，跟血的气味混在一起。要找的人就在这儿。」

「呼嗯，原来如此。不过，躲在山里实在很麻烦。小的对自己的腿跟腰可没自信。」

「那种事，龙才不管。不然，要放弃？」

「没有没有。只是，荒废的土地和树林，看起来就像是不被人需要的山……要是玛德琳殿下能把在找的人从里头熏出来，小的会非常感激。」

「──熏出来。」

既然要找的人躲在山里，就只能搜山了吧。

遗憾的是，这次除了玛德琳以外，没有人可以帮奇夏。想要感叹劳动环境有多严苛，可是大量人手都被分去攻打魔都了，所以也不好说什么。

既然如此，也只能拼命运用脑袋，拟出最佳方案了。

唯一的协助者玛德琳五感优异，找出了他在找的人躲藏的地点。再来要是能利用她有的优点把人从森林熏出来的话，事情就能快速获得解决。

而对于奇夏这样的要求──

「──龙的作法，有点粗鲁喔？」

金色双眼闪闪发亮，看向奇夏的少女嘴唇弯成弧形。

顿时，彷佛受到少女的笑容邀请，空中传来鼓动偌大翅膀的声音，而且数量还不少。奇夏看到了比传闻中更夸张的光景。

超过三十只的飞龙，翩翩落在玛德琳周围。

「龙的狩猎很凶猛。之后可别抱怨。」

抚摸站在旁边的一头飞龙的头，玛德琳提醒奇夏。接受龙人这样的牵制，奇夏也点头说好。

接着他走到玛德琳旁边，重新面向森林。

「军营的士兵掌握多少尚不确定，不过逃离夜鸣一将追杀躲进森林里的人，不能说没有关系。所以……」

「──？」

说到这儿打住，奇夏闭上眼睛，然后深吸一口气──

「──躲在山里的帝国军！！假如您也有身为一匹剑狼的骄傲，就出来给个解释吧！！」

「──」

奇夏的声音大到撼动空气，甚至传到山的另一头。

这不是出于慈悲或宽容，而是必要的仪式。给予辩解的机会，是让士兵们可以为自己的名誉做辩护。

应该准备这种机会吗？奇夏心中的天平没有倒向任何一方。不过，当时军营里发生了什么事，而那件事跟夜鸣造反有关吗？奇夏心中已经有个猜测。

要是那个猜测中了的话，奇夏便认为没必要对他们慈悲。

「玛德琳殿下，只要等一刻就好。要是这样还没有动作，待会的处理就要拜托您了。」

听着自己的声音在山中回响，奇夏坐到附近的树荫下。望着他这样，玛德琳平静吐气。

「人类有够爱磨蹭的。……龙只问一件事。」

「是什么呢？」

「……你说的一刻，是什么？」

皱眉的玛德琳问道。其他飞龙也跟着歪头面露困惑。

亲眼目睹少女统领飞龙的能力，另一方面觉得贝尔斯特兹保持她无知到无情的地步，奇夏搓揉自己眉心。

一刻。是可以教玛德琳这个，要花的时间恐怕不到一刻。

然后当一刻刚过，飞龙群就会进攻卑鄙小人躲藏的山林。他们将会在那儿品尝到飞龙的凶猛和龙人的可怕吧。

──还会领悟到，对于扭曲骄傲的人，铁血定律是毫不留情的。

18

婀娜摆动手臂，纤白手指搔抓空气。

洗练得宛如舞蹈的动作，却引发了如梦似幻、非比寻常的现象。

「起舞吧。」

──马路就像生物一样弹跳，建筑物卸除桎梏后慌张地往旁边滑动。

「歌唱吧。」

──整个都市装设的踏脚台全都失去支撑，往下掉落，从名为自由落体的不自由规则中获得解放，自在地在空中来回飞舞。

「打碎吧。」

──砖造建筑物、色彩丰富的玻璃艺品，最后连种植的树木花草，全都扭曲原本的存在方式，随心所欲地肆虐起来。

在宽敞的大马路正中央手持烟管翩然起舞的夜鸣，周围的街景变化外型，建筑物和踏脚地飞向空中，树木花草像士兵一样傲立挡路。

「这是……」

「唉呀～还是一样不知道你在做什么，很恶心！不过，同时又让人移不开目光！这种综合艺术真是太棒了！」

目睹诡异光景，亚拉基亚大吃一惊。但是看到旁边的瑟希鲁斯跟平常一样，便立刻舍弃惊愕。

「极彩色」夜鸣•魅时雨，是个不可小觑的实力派，这点已经非常清楚。

「而且，奇怪的技巧，老爷爷也有。」

举看过的人当例子，亚拉基亚封杀自己的惊讶。

斜眼看到亚拉基亚恢复后，瑟希鲁斯往前踏出一步──消失不见。

「──！」

而消失的瑟希鲁斯下一次出现时已在夜鸣眼前，以雷速拔出的刀子穿越漂浮起来的各种障碍，直抵她细瘦脖子，打算将之一刀两断。

但是──

「唉呀，还是一样。脖子守得很严密呢。」

「您才是，还是一样的方法呢。取不下奴家的首级这点，不是应该已经从以前的交手经验中学习到了吗？」

「不，上次的我跟这次的我不一样。别说一天了，每一秒都在成长正是主角的特权。不如说，每次登上舞台，男人味都会上升！」

「歪理讲不完的人呢。」

脖子被瑟希鲁斯的刀砍，夜鸣的脖子别说还连接着身体和脑袋了，甚至连一层皮都没掉。斩击的成果只留下微微的红色印子。

以前瑟希鲁斯就有说怎么杀都杀不死。──原来真的是字面上的意思。

「吁。」

接着，夜鸣用烟管弹开刀，旋转身体朝瑟希鲁斯使出肘击。

瑟希鲁斯瞬间往下缩躲过，但无数砖瓦──解体后的民宅零件如箭矢般追击残影，接连打向他。

没命中目标的物体在地面上打出大洞，惨状宛如炮弹风暴洗地。像这样直飞过来的砖瓦等物体，不过只是开端罢了。

「哎哟，相当华丽的发展呢！」

「难得有招待帝国最强人物的机会，奴家也不会放水的。」

原本装在都市各处的无数踏脚台，朝着往头上看的瑟希鲁斯降落。

每一个重量都不少，庞大质量只为压烂瑟希鲁斯一人，都市不厌其烦改变形状，直往他坠落──

「哒哒哒哒哒哒哒哒──！！」

面对宛如暴雨倾泻的巨大攻击，瑟希鲁斯不是采取慎重态度，反而大胆加速闪避。

踏脚台每次撞击都让地面摇晃，闪电踩过乱成一片的踏脚台，快速穿梭。就在瑟希鲁斯豁出性命挑战跑酷的时候──

「还有我。」

挥动手中的树枝，亚拉基亚用体内感受摄取的微精灵最后的热度。

「食精灵者」的能力，是靠燃烧摄取的精灵的性命来获得发挥。为了与夜鸣一战而事先摄取的微精灵，将在这里解放它们最后的光彩。

为了一举攻下被讴歌为难攻不落的魔都，以及它的女主人。

──刹那间冒出的火焰，以亚拉基亚为中心延伸至数百公尺。

「──这是……」

身体被满出来的火炎热量和扩散的势头给烧到，夜鸣惊讶抬眉。

一般来说，火是慢慢延烧，逐步扩大燃烧范围，可是亚拉基亚的火焰不走那种慢调子烧法。

摄取火之微精灵，运用蓄积起来的力量，让可以感知的大气范围内的微精灵一同发火，一口气烧光殆尽。

迅速扩大火焰和使出庞大火力，而且亚拉基亚本身也化为火焰攻击敌人。

这是她摄取火之微精灵的时候的战斗方式──

「虽然没有小看她这个姑娘……」

「我擅长，烧东西。」

在轰然烈焰中，夜鸣被照得红通通的眼眸里带着警戒。沐浴在她的眼神中，制造爆炎的亚拉基亚感受不到手感。

城市或物体，所有一切都在燃烧，可是灼热却碰不到夜鸣。

就像瑟希鲁斯的刀刃切不断她脖子，反而被雪白肌肤弹开一样，火焰也──

「阿妮亚！等一下！我也快要被烤熟了喔！？」

「……顺便。」

「啊啊够了听不懂人讲话！我要干啰！」

同样被火焰缠绕、奔驰中的瑟希鲁斯刀刃呻吟，一口气把面前的建筑物一刀两断。他跳到断面上，拔腿狂奔，逃离燃烧地面的火焰，抵达都市上空。

就这样纵身飞进踏脚地和建材暴风雨当中，斩击如闪电喷发。

──顿时，所有物体都被切割，失去作用。

此时，化成火焰的亚拉基亚也攻向夜鸣，使出大火力踢击。

「──！」

划出弧形的火焰拉长了亚拉基亚的腿长，像舔拭般扫过都市。被擦过的建筑物和行道树，路径上的一切全被燃烧扫踢烧毁，将魔都变为地狱。

但是──

「没有人？」

身在烧毁的魔都中，亚拉基亚却感受不到有任何牺牲者。

甚至连周围的微精灵，都感受不到类似的性命增减。在这一带，亚拉基亚的攻击范围内，除了夜鸣以外还真的没有其他人。

这也意味着，都市居民全盘信任夜鸣，让她一个人去对抗来自正面的敌人。除此之外没有其他可能。

「早就知道各位会从正面进攻。那么，把后门交给孩子们应付是人之常情。──只是一、两个『九神将』，由奴家一人就能压制。」

「好大的自信。」

「这是奴家的骨气。您的眼神，动摇了喔。」

穿破炎幕，以突出的厚底鞋鞋跟贯穿没有实体的亚拉基亚的胸膛。飘动的和服衣摆斜向砍断火焰，反手一击就把亚拉基亚纵向切成两半。

当然，物理攻击对同化成火焰的亚拉基亚完全不管用。就算拿剑劈砍、刺穿火焰，也杀不死火焰。然而──

「我，动摇？」

「够强的人，就会去做想做的事，这是佛拉基亚风格……而您，看起来似乎不快乐。不如说……」

「──」

「您像是对『自己为什么在这里』感到迷惘。」

夜鸣踏地剖开道路，往上挥出的手掌打消亚拉基亚的颜面。分散的火焰聚回来，被打掉的头部也立刻恢复原状。

可是话语比拳头更有力，带给亚拉基亚胸膛针刺般的痛楚。

夜鸣那番话彷佛看穿她内心，令她的心也跟着动摇──

「请不要这样啊，夜鸣小姐。因为阿妮亚是个马上往心里去的人。」

这时，瑟希鲁斯的声音介入其中，滑过来的他用草鞋轻轻贴在夜鸣胸前。「喝。」接着他膝盖使力，夜鸣的身子就被轻松往上推，被猛烈地踢向天空。

随后，追着她跳跃起来的瑟希鲁斯的无双斩击杀向夜鸣。

剑击毫不留情，夜鸣全身的要害都暴露在危险中。

「您真是学不乖呢。」

「呜哇，这样都还不行！还以为你铁定有『地灵加持』之类的，本来想说让你离开地面再杀就管用了。」

「──。您有学习的意思，着实令奴家惊讶。」

「当然，边找胜算边将敌人逼上绝路才叫醍醐味。什么都没想就投身战斗，我又不是阿妮亚。」

瑟希鲁斯的雷速斩击低吼，夜鸣无法阻止，只能以胸部承受。可是她丰满的胸部拒绝刀刃的锋利，回敬的一击被瑟希鲁斯用刀鞘防御住了。

承受反手拳的刀鞘嘎吱作响，瑟希鲁斯的身体迅速划破红色天空。

「瑟希鲁斯！」

目光追随飞远的瑟希鲁斯，亚拉基亚立刻转头看向夜鸣，但脖子却被伸过来的手抓住。夜鸣脚踢空气回到她面前了。

她用纤纤玉指掐住亚拉基亚的细喉──握住理应没有实体的喉咙。

「啊咕……」

「因为动摇了吧。影像模糊，变成了可以抓住的实体。──您，是为何而战？」

「────」

「奴家是为了爱。您是出于何种理由，烧掉整座都市呢？」

假如拥有的东西直接关系到强劲的话，那夜鸣强大的保证就在这儿。

感觉似乎被这样质问，亚拉基亚的嘴巴一张一合，同时眼皮底下冒出远昔的幻影──自己最重视的存在。

不论何时，不管在哪里，亚拉基亚核心当中的存在都未曾改变。──可是，亚拉基亚这样烧毁都市，能够说是为了她吗？

「──都说了，请不要让阿妮亚想事情了，夜鸣小姐。」

横切斩击闪过眼前，扫掉抓住亚拉基亚脖子的手。

她的手跟脖子一样砍不断，但发出的钝重声音带给夜鸣的手痛楚，趁她力气放松的时候把亚拉基亚抢走。被抱住腰往后退的亚拉基亚看过去，发现救了自己的是表情轻松到可恨的瑟希鲁斯。

抱住同化成火焰的亚拉基亚，意味着拥抱火焰，他却不改若无其事的表情。

「──。对奴家来说，最不能了解的就是您这种贵客。」

「嘿～我有那么难懂吗？陛下和奇夏都觉得我很难应付，所以都简单应付我，我对此倒是蛮有自信的耶。」

「您的手正在被烧，不痛吗？」

肉被烤熟的声音和气味，源自于和服底下的手正在被燃烧，可是瑟希鲁斯的微笑没有任何变化。连夜鸣的提问，他都表现得泰然自若。

「嗯～这时候比起痛到慌慌张张，笑得目中无人比较帅吧？」

「──」

皮跟肉被火焚烧，热度甚至传到骨头。散发着烤肉味的瑟希鲁斯没有羞耻，也没有畏惧，而是顺着自己的哲学如此主张。

他就这样绽放笑意，轻抚怀中亚拉基亚的头。

「还有，麻烦不要灌输阿妮亚多余的事。什么战斗理由还是意义的，我是不否定认为这些东西很重要的人啦……」

「可是强者不需要那种东西，您是这么想的吗？」

「不是不是，我的强大跟别人的强大性质不同。不想让阿妮亚去想那些事，是因为想事情的阿妮亚弱得甚至让人觉得遗憾。」

「──！」

被直接了当这么说，亚拉基亚立刻就想反驳。

但是她却出不了声。理由恐怕在于夜鸣与都市居民之间的关系──只身一人挡住前线的夜鸣，以及信任她并团结一致，保护她保护不到的地方的居民。如此坚强稳固的关系，令她好生羡慕。

过去，自己跟主人之间也有过的信赖关系，要说自己不会去想是骗人的。

可是──

「阿妮亚，我不会要你别思考，可是要看时间和场合。把自己当成主角还是配角，端看你怎么做。」

「……意思，不懂。」

「就是要你现在化为一把刀就好。或者，阿妮亚心中的主人希望你死在这里？」

「──」

手臂发出炙肉声，但瑟希鲁斯还是笑着这么问。

不爽他这表情，想说要不要干脆就这样把他的手烧焦，但算了。虽然很生气，然而亚拉基亚真正的主人不期望这样。

而且，真的做了会被瑟希鲁斯笑：「我就知道你会这样！」自己可敬谢不敏。

「阿妮亚，摄取的微精灵呢？」

「……一百二十四。」

「好。那就杀夜鸣小姐一百二十四次。──这是我们，从九神将上面数来前两名的人，被要求存在的理由。」

直接给予战斗的理由后，瑟希鲁斯把刀收回刀鞘。「嘿。」接着他扶起亚拉基亚的身子，手穿进烧焦的袖子里，摆出要当观众的态度。

看着瑟希鲁斯这一连串的动作，夜鸣嘴叼烟管。

「原先还以为您只是擅长杀人……」

「啥？」

「您也擅长不用刀就让人活过来，同叫奴家吃惊。」

吐出烟雾的夜鸣眯起眼睛说，瑟希鲁斯抬眉。接着，帝国最强男人弓起腰大笑。

「哈哈哈！我终究只是一介剑客。才不会让人复活这种技俩咧。要说阿妮亚会苏醒，只是因为我跟她是老交情了吧。还有……」

「还有？」

「认真的阿妮亚很强的喔。偶尔会让我胆寒呢！」

用毫无恶意的表情这样宣告的瑟希鲁斯真的很讨厌。要是烤焦的不是他的手而是脸的话，该有多好。

可是，自己不会这么做。虽然不这么做，但若问她有没有什么想说的话──

「瑟希鲁斯。」

「我在我在。」

「──去死。」

「就是没法老实说谢谢呢。」

果然还是希望他死掉。这么想的同时，亚拉基亚全身都绽放耀眼光芒。

不考虑后头的事，把所有摄取到体内的微精灵全部活性化──见状，夜鸣缓缓摇头。

「你，也是为了爱而战呢。」

「……大概，完全不是！」

瞄了一下瑟希鲁斯时被这样讲，亚拉基亚大吼，冲上前去。

下一秒，魔都卡欧斯弗莱姆攻防战中，最大等级的破坏与光芒笼罩了战场。

然后──

19

吃了一记前踢而飞出去的身体，硬生生撞上墙壁。伴随哀号一同倒下的男子，脑袋被往下踏的鞋底给踩在地面。

门牙撞地而脱落，男子吐血惨叫。听着他哀号，踩着他的眼罩男歪头，不屑地说：「有够没劲。」

地点是帝国军宿舍的其中一个房间，互殴的是两名基本装备都是红色的帝国士兵。

话虽如此，这场架根本是单方面施虐。并非是出其不意或奇袭。彼此都手持武器，同时开始劈砍对手，接着瞬间一面倒。剑力差距非常明显。

一般兵和上等兵里头，恐怕都没人敌得过他。──这就是叫做贾马尔的男子的实力。

「要是脑袋再好一点的话，就会平步青云地晋升为『将』了吧。」

「吵死了，陶德！这边就乖乖夸奖老子的实力就好！」

「我是在夸奖你的实力啊，你的剑术没人会怀疑啦。好啦。」

耸肩带过不满的抱怨，被贾马尔呼唤的陶德走向前。他看着被打趴在地、头还被踩着的可怜男子。

（插图014）

不过这个男的是不是真的可怜，还得看他之后的应答表现。

「你、你们……同样是正规军，竟然做出这种事……」

「喂喂，先动手的可是你吧？在我看来，贾马尔只是反击。因此被打得落花流水的你真是令人同情……不过，看来我们问的问题对你很不利，可以这样想吗？」

「──！」

「哦，可别想逃喔。要是敢开玩笑，就让你跟我一样喔？」

俯视脸色铁青的男子，贾马尔用手指敲敲自己右眼上的眼罩。这很明显是恐吓，但效果却很显著。事实上，如果是贾马尔的话，有可能真的会这么做。

男子的气势越来越萎缩，陶德满意点头。

「帮了大忙。那么，继续刚刚的问题。──你，是夜鸣一将消灭的军营的生还者吧？为什么夜鸣一将要杀你们？」

「她、她脑子有问题！传言你们也知道的吧！那个女的之前也……呀！」

「她可是一将，放尊重点。这里是酒馆，我们是知心好友吧？」

贾马尔挥动手中的长剑，耳朵被削掉一部分的男子惨叫。贾马尔嘴边也很常挂着下流没品的发言，但却又莫名坚持上下关系，这样的性质显得很奇妙。

有鉴于此，男子的发言会比刚刚更加谨慎吧。

「脑子有问题，这我当然知道。不过呢，虽然这只是我个人的主张，可不管看起来多不正常的家伙，都有那种人自己的一套道理在。即使旁人看起来没有意义的行为，在那种人的心里就是讲得通的。懂吗？」

「啊、啊……」

「也就是说，我推测这次夜鸣一将的暴行，也有身为一将的她的道理在。因此，她会一个一个杀光军营里的士兵，我怀疑是出自于怨恨。」

不单单是赶尽杀绝，而是彻彻底底地赶尽杀绝，从动机看来一定是根深蒂固。

开始调查后便得知，夜鸣似乎要求交出逃离军营的士兵。皇帝加以拒绝，结果就发展成了在魔都进行武力冲突。

但是──

「那、那种事，知道了，又怎样……」

「啊～？这种事用不着你关心……」

「唉，等一下，贾马尔。讲出来没有关系的。──视情况而定，我认为有可能阻止这场战争。」

手在胸前合十，制止贾马尔的陶德朝男子笑。

胸口和耳朵都在跟疼痛奋斗的男子，边喘气，边用求救的目光仰望陶德。

「假如开端是怨恨的话，那道歉的方法也会改变。没有什么比不知道在对什么道歉的谢罪更能触怒对方了。而且只有你得救的方法，我们或许也不是不能提供给你。」

「怎、怎么、做……？」

「不难。只要知道事情始末，由我们跟上面的军官报告。在我们介入内部纠纷进行调解的时候，对你搞失踪的事睁只眼闭只眼啰。」

听了陶德的提议后，男子屏气，用试探的眼神看过去。虽然对方早已疑心生暗鬼，但陶德还真的没有比话中更多的企图了。

他终究不在乎这男子的生死或下场。他有兴趣的只在眼前夜鸣•魅时雨造反的原因，还有阻止的手段及确保情报。

准确来说，是要用这情报来做出功劳，以获得好评。

为此，才会刻意挑战危险，找出军营的幸存者，把闲杂人等支开，直接把当事人带到宿舍问话。要是这人派不上用场的话可就伤脑筋了。

「……一开始，只是排遣无聊而已。」

陶德的诚意传出去了吗，男子像是死了心，开始慢慢讲述。

这就是此次骚动的开端，搞得夜鸣屠杀军营士兵，还要求幸存者在内所有相关人员都要拿命来偿的理由。

听完的内容，大致就跟陶德想的一样。

果然，夜鸣•魅时雨谋反的原因在于怨恨和愤怒。

「这、这就是全部了。怎么样，能接受吗？」

讲到一半口气开始变得粗鲁，语调激动说完的男子询问陶德。在他的注视下，陶德抚摸自己下巴点头道。

「嗯，是啊，我能接受。若说事情是这样的话，那军官应该也会听才对。」

「那么……！」

「不过，运气有点不好啊，我说你。」

陶德附加的那句话，令男子目瞪口呆。

是不懂这话是什么意思吧。正因男子的观察力差，所以得用自己的性命支付代价。应该要更早察觉才对。

察觉也在陶德身旁听男子说话的贾马尔，朝对方露出了打从心底蔑视他的眼神。

「明明有想过可能会变这样，失败啊失败。」

陶德耸耸肩，然后站起，男子被切断的头部在他脚边滚动。没什么。就只是贾马尔挥刀，一口气割断了男子的脖子而已。

「人渣。根本称不上是荣誉的帝国军。」

「你的自我评价如何，我才不想管咧。」

陶德转动脖子，伸个懒腰。

这家伙就跟刚刚说的一样很不走运。在贾马尔脚下失言是如此，被陶德他们掌握到位置这件事也是如此。

而明明还有其他锁定了位置的逃亡士兵，但男子站在最好引诱出来的立场上也是。

不过──

「剩下的两人，也不能说是运气好呢。」

「嗯，我要把他们大卸八块。」

「慢着慢着，不要为了发泄你的心情就杀了他们啊。要好好抓起来交给军官，变成我们的功劳。」

听到这建议，贾马尔用整张脸主张自己的不悦。用手推开那张烦人的脸，陶德对未来的大舅子这么莽撞只能叹气。

自己会去挑战平常不做的危险事，全都是为了建立功劳，好回到帝都。一切都是为了回到等在那边的心爱女人身旁，才有的付出。

为此甚至──

「──我会照顾好难以应付的大舅子的。相对地，照顾完以后，拜托要用你的胸口好好慰劳我喔。」

20

「──这次的事，源自于军营士兵凌辱、杀害鹿人姑娘，甚至还玷污其尸首。杀死了受魔都庇护的兽人，魔都女主人当然会勃然大怒。看样子，一切都在预想之外。」

挺直背脊，朝着在办公室处理文件公事的黑发美青年──皇帝文森•佛拉基亚报告，刚回来的奇夏等待答覆。

不是等待慰劳自己的话语。是实务性的，针对往后发展的现实指令。

在奇夏面前停下翻阅文件的动作，文森视线抬也不抬，就说：

「那就是要杀光正好人在军营里的士兵的原因吗。──谁说溜了嘴？」

「四散逃亡的士兵有三人，跟会合的部队士兵透露了内情。掌握了情况的上等兵就把他们抓了起来，向上呈报。一名死亡，另外两名幸存者已被关押。」

「把关押的两人，送到魔都的夜鸣•魅时雨那儿。」

文森毫不犹豫就定下逃亡士兵的末路，奇夏默默遵从。

这次夜鸣的叛乱导火线，就是那些人。要是他们的惨死，能稍微慰借在这场战争中所流的鲜血就好了。

这么杀气腾腾的想法，连奇夏自己都讨厌。自己本来应该是个温厚又文静的人。

没有理睬他的内心纠葛，文森边看文件，边继续下命令。

「还有，找出任命军营的『将』的人，及其所有亲属。处置随后发布。」

「小的明白。另外，陛下，俘虏逃亡士兵的上等兵……」

「应该要给奖励吧。就给那些想要的奖励吧。」

「有想过您会这么说，所以就直接问了。当然，不是以这张脸就是了。」

听到这边，文森头一次把视线移到奇夏身上。

既然注意力有被吸引正好，奇夏在脑中描绘之前面对面的两名士兵。一个是气质粗野的眼罩男，一个是给人老好人印象的温和男性。

顺着少之又少的情报找到逃亡士兵，判断他们的堕落应该报告给高层，于是采取适切的作法，这点非常值得评价。当然，也想给予相对应的报偿。但──

「──帝国人民须剽悍强大。」

「……什么？」

「其中一名上等兵，在被问到想要什么奖赏的时候，跟小的这么说。说自己不过是遵从佛拉基亚帝国的理念。」

而且这么说的人，是看起来就很有野心的粗野男，所以更让人啧啧称奇。

该名上等兵是真心服从帝国的铁血定律，憎恨做出违背此一原则行径的弱卒。甚至一口咬定说，不要用他们的血换来的奖赏。

当然，他身旁的搭档听到这番话，一副像是要晕倒的样子就是了。

「帝国人民须剽悍强大，是吗。」

只要是佛拉基亚帝国的臣民，任谁都一定会知道的剑狼道理。

这句话重新入了耳，说出口，文森微微眯起眼睛。存在于黑瞳深处，皇帝陛下那所有深远的想法，就连奇夏都无法完全看透。

说不定，最接近这本质──这番无从言表之理的，是不靠理论思考、跟责任感或地位这种束缚完全无缘的剑客。

总之，这次事件的起因已经做了一定程度的安排，并获得解决。若论还有什么其他应当报告的事，奇夏击掌道。

「对了对了，跟小的同行的玛德琳•恩夏尔德，实力和能力都无可挑剔，可说具备『将』的器量。然而没有从军经验，后盾是贝尔斯特兹宰相是麻烦之处，这是小的的担忧。」

「既然哥兹推荐的卡夫马•依鲁鲁库斯辞退，就没必要把有能力和气概的东西搁置在一旁。就算有那个插手也一样。」

「……小的认为没有必要刻意服毒。」

「为此才有你、『九神将』，和余。」

说着说着，文森视线再度回到桌面，继续翻阅文件。

态度表达出他不打算继续对话，奇夏对于文森的顽固，和一开始就大胆地把手放进还有余烬的灰中，只能叹息。

在长年的来往中，早已知道他就是这样的人。但──

「──最晚，也只有两年了。」

「陛下。」

在离开前，文森静谧的话绊住了奇夏的脚。可是文森没有回应他的呼唤，继续埋首于工作中。

只是自言自语，还是对奇夏发问？

不管是何者，都没法再引出更多话。──知道这点的自己，明明知道却什么也做不到的自己，极其可恨。

自己到底是为了什么而在这里的呢？忍不住自问自答。

「……小的一点都不像自己了。真是让人感到厌恶。」

阐述心头话，佛拉基亚皇帝的宝刀──不，刀另有其人。因此自己不是刀，就只是心腹罢了。自认如此的奇夏离开了办公室。

「──」

从走廊窗户看出去的天空湛蓝得令人生恨，简直就像没注意到在老天雄伟的眼皮子底下，死去了多少生命。

「真是的……」

──身为剑狼的一员，实在无法不对此感到极度憎恨。

21

「啊！阿妮亚，你蛋又只煎单面了！」

「……想煎双面就自己来。」

在粗制滥造的小屋里，亚拉基亚瞪着对餐桌上的食物有意见的瑟希鲁斯。

放在粗糙桌上的食物有两人份，各自被盛放在颜色不同的餐具上。为了区分彼此的物品，餐具架上放了好几个颜色不同的餐具。

要是有个闪失不小心用到瑟希鲁斯的餐具，自己绝对敬谢不敏。话虽如此，因为他都不洗碗，所以也没法完全避免不去接触。

更何况，今天要把接触限制在最低程度都很难。

要说为什么的话──

「啊～」

「──」

「阿妮亚，来，我嘴巴开开啰。啊～」

被这样催促的亚拉基亚烦躁地抓住对方的叉子，朝他盘子里的煎蛋插下去，接着活像喂食雏鸟般把食物塞进他嘴里。力道猛到最好能折断他门牙，但他却轻松地用牙齿夹住煎蛋，享用起来。

既然这么灵活，进食根本用不着帮手吧，他这只是故意惹人嫌。

因为亚拉基亚烧了瑟希鲁斯的手，所以在伤痊愈之前都要被他找麻烦。

要不是因为一起生活，所以被命令照顾他的话──

「哈呼哈呼……嗯，好吃。撇除只煎单面这点的话，阿妮亚的厨艺很了不起喔。知道是以年为单位在进步的我可以保证。」

「奇夏的话还可以，瑟希鲁斯的保证……？」

「啊！不相信我的表情！我可是有评鉴的眼光喔，阿妮亚。不然的话，就没办法看清古刀和名剑了。当然也有看人的眼光。」

「……骗人。」

「唉～」手吊着没办法动，于是瑟希鲁斯左右摇摆身体来表达不满。

亚拉基亚不理他，想要快速结束用餐兼拷问，于是接二连三将刚做好的热腾腾料理送进他嘴巴。而他每次都能巧妙处理，真叫人不爽。

就连这种杀气腾腾的早餐时光也是──

「不过，这次夜鸣小姐的叛乱也以失败告终呢。唉呀，说到底，她到底有多认真，连陛下都很怀疑。」

「……死掉的鹿人，是原因。」

「嗯，没错没错。卡欧斯弗莱姆是有麻烦的人们最终寻求庇护的地方，所以要是半开玩笑插手的话，当然会得到相对应的回礼。就像把手伸进巢穴会失去手指一样，这种事想都不用想也能知道吧。」

咧嘴大笑的瑟希鲁斯悠哉地总评这次的叛乱。不过听了以后，亚拉基亚垂下眼帘，瑟希鲁斯挑眉。

「哎哟？怎么啦，阿妮亚？有什么在意的地方吗？」

「夜鸣，很强。」

「是啊。唉呀～这次也还是不知道那机关是什么呢。本来想说总算可以砍断她的头了，结果还是失败了。」

「那个奇怪的能力，也是。」

会接连改变形状的都市，还有夜鸣那不知坏损为何的压倒性顽强。那些当然也很异常，但动摇亚拉基亚心房的，是她的态度。

虽然气恼，可是在战斗中，自己确实就如瑟希鲁斯所说的，都是抛弃杂念放手一战。然而就算结束了，内心的动摇──那个问题并没有解决。

为了什么而战？被这样问，亚拉基亚突然想到。

「瑟希鲁斯，为什么战斗？」

「────」

「……干嘛，那张脸？」

为了面对自己的问题，亚拉基亚这样发问，没想到瑟希鲁斯却露出奇怪表情。好半晌后，才意识到那是他惊讶的表情。

维持那张惊讶的怪脸，瑟希鲁斯摇头道。

「没有没有。阿妮亚竟然会想要了解我而这么问，真的太让我意外，大吃了一惊。这难道不是你从小到大的头一遭吗？」

「──。用不着问，你也会自己一直讲。」

「是呢。我对食物的喜好、信念什么的，身为红牌演员的心态什么的，要多少都可以让你问到饱，偏偏却是问为了什么战斗啊。哈哈哈。」

「回答不出来？」

「不，回答得出来喔。──因为我的志向是追求天剑。」

瑟希鲁斯平静回答，眼神中带着静谧。跟他平常给人吵闹程度是一般人两、三倍的印象有天壤之别。

有时候，瑟希鲁斯•塞格姆多这个人会展现这种表情。

难以捉摸，简直就像闪电一样没有实体，无法以肉眼追上的性质。

这是从亚拉基亚这辈子的主人，或这个国家的皇帝文森身上可以感受到的，异于常人者特有的气质。

就像彰显出站的位置不同，看到的东西也不同似的。亚拉基亚有这样的感觉。

「瑟希鲁斯。」

「是？」

「去死。」

「为什么！？我刚刚老实回答问题耶，你怎么可以忘恩负义！」

闹哄哄的瑟希鲁斯让那股气氛烟消云散。亚拉基亚吐气。

之后发现自己稍稍安心了，亚拉基亚皱起脸。

亚拉基亚心爱的主人，和本质上与之并立的皇帝。是因为不用把他们跟瑟希鲁斯看作同一个次元的人，所以才感到安心吗？

这无疑也是一个相当令人生气的案件。

「不过，阿妮亚这个绰号，好像还会再继续叫上一阵子呢。」

「──。马上，会让你撤回。」

「这么说的期间，已经过了七年啰。哈哈。」

笑得轻佻的瑟希鲁斯又「啊～」地张开嘴巴。这次亚拉基亚板着脸，把没有去骨的烤鱼直接放进他嘴里。

用牙齿和舌头灵巧地分开骨头和鱼肉，帝国最强的剑狼笑了。

──位在剑狼群顶端的存在，一面想着远大的天剑，吃着钓上来烤好、放在餐桌上的鱼，开心地露出了笑容。

《完》

** 『绯色联盟』

1

「──好。那么，开战吧。」

高举手上的扇子，犹如鲜血般赤红的美女正大光明地宣告。

身旁听到这番宣告的人不是吃惊就是困惑，还有一部分人表露出狂热，反应各异，但有个共通点。

就是有反应的人，每个都很年幼。

「──」

听到美女通透美声的，全都是十来岁的男童女童。

年龄多少有点差距，然而全都很年幼。再加上，这些孩童并不是精通战斗的人，而是都来自于城镇的普通人。

虽然不能说与战争无缘，不过小孩不可能主动站上战场。对着这些孩童宣告「战争」开始，甚至还推了人一把的暴行。

这种行为就算是玩笑也太恶质了。遗憾的是，堂堂正正宣告的当事人完全没有在开玩笑，还是个要是有人敢在背后指指点点，就直接连同手腕一起砍掉的暴君。

不管怎样──

「──开始战争吧。双方，都做好准备吧。」

重复宣告的美女──普莉希拉•跋利耶尔十分愉悦。没打算让她撤回这番话，不是因为惋惜自己只剩下一只手喔。从后方看着一切的铁头盔随从这么想。

2

──时间回溯到普莉希拉做出开战宣言的几个小时前。

「普莉希拉大人！不好了！我已经应付不来了！」

小孩的大声叫喊，响彻整栋豪宅。

不是因为嗓门特别大，只是刚好为了让房子透气，所以侍女们把所有门和窗户都打开而已。

听起来像是被逼到绝路，可是猜到大叫的人是谁后，侍女们都漾出微笑，回去继续忙自己的工作。

因此，听到声音后抓抓脖子、抬起腰杆的就只有一人。

「唉呀呀，舒尔特酱今天也一样很有精神呢。」

从原本靠着的沙发站起来，不情不愿这么说的是黑色铁头盔男。

跟以漆黑钢铁罩住的头部相比，脖子以下的部位防御力显著降低。脚下甚至踩着改造过的草鞋，毫不一致的印象肯定会深深烙印在记忆里。

不过，跟这奇特的外貌相反，了解他所扮演的角色详情的人很少。具体来说，连他自己也没法掌握自己的地位是什么。

「虽然都被公主叫成丑角，但会不会给薪水啊？」

他知道自己的主子支付给下人的薪水相当丰厚。她不是那种小气的性格，会得到侍女们的喜爱，也是因为她会给认真工作的人慷慨的报偿。

话虽如此，每个月的薪水并不是汇进银行户头，所以应该是在某个地方交付现金才对。──只是自己根本没印象有收到过。

「我物欲低，说想要零用钱就可以拿到，所以都没仔细想过。该不会我现在，是个没有像样的工作经验和存款的糟糕大叔吧……？」

被不经意的自我分析搞得心情消沉，男子毫不犹豫地走向某一个房间。

想想刚刚大叫的人和叫喊的内容，那目的地就只有一个。随后，果不其然，这个直觉没有失误。

「我试着努力，可是大家都不听我的话！这样下去，普莉希拉大人的、普莉希拉大人的手段会因为我……！」

「呼嗯，妾身的手段会？」

「被、被众人怀疑！我没法忍受这点……」

偷偷往房内窥看，便看到了垂头丧气的小个头背影。

悔恨地握紧小拳头，惹人怜爱、浑身发抖的粉红色翘发男孩，万分适合穿五分裤的知名管家──舒尔特。

稚气全开的模样，小心翼翼、努力活下去的样子，任谁一看都会忍不住想要温柔疼爱他。豪宅的侍女们也都无一例外地爱着他，这不单单是年龄的原因，还出自舒尔特本人的性格。

不过，侍女们不能如此明目张胆地表现出对舒尔特的疼爱。并非因为现在还在工作时段，而是有更根本的理由。

那就是──

「每个动作都很可爱的家伙呀。在用那矮小的身躯担心妾身吗？」

是因为这么说完便眯起红色瞳孔的豪宅之主普莉希拉，万分宠爱他的缘故。

坐在金碧辉煌的椅子上，倚着扶手、拄着脸颊的普莉希拉腿上放着看到一半的书，正在倾听舒尔特令人感动的诉说。

意外地很爱看书的普莉希拉，自由的时间大多都消耗在读书上。

跟书互相接触的时间是她的圣域，要是有人胆敢打扰，就等着吃一顿尖锐无情的挞伐，状况糟糕的话，甚至可能会触发炸弹，变成断头台上的露珠。

但只有舒尔特是个例外，能够入侵那个圣域。

「不，意外地，女仆小姐们好像也或多或少都会被放过耶？这样一来，不如说有特殊待遇的，只有会被骂的我了。」

「搞什么，想说怎么听到恶心的声音，是你啊，阿尔。」

「哎呀，糟糕。」

从走廊偷看房间里头的时候被发现了，男子──阿尔鞠躬哈腰。

（插图015）

本来没打算被发现，但普莉希拉的麻烦之处就在于其宽容跟股价一样会大幅变动。可以的话，希望是碰到她心情好的时候。

幸运的是，普莉希拉没有提起偷听的事，而是抬起下巴问道：

「你该不会也要用世界末日的表情，跟妾身报告什么吧？」

「这怎么可能呢，公主。就算没这个头盔，你觉得我会像舒尔特酱那样随时都露出很拼命的嘴脸吗？」

「就算会，那张丑脸也让妾身的心纹风不动。」

「咦！普莉希拉大人有看过阿尔大人的脸吗！？」

「──」

普莉希拉和阿尔对话的一部分，激起舒尔特的强烈反应。

「啊！」顺着好奇心发言，但马上用双手捂住嘴巴，努力反省自己怎么这么沉不住气。

「我真的是很没用……！好像变成只会发出悦耳声音的虫子了……」

「蠢蛋。虫子是可以放在妾身屋子里的东西吗。不想被踩烂的话，赶紧羽化成舒尔特便行。」

「我会成长的……！」

「匆匆忙忙的样子很可爱呢，真是的。」

大步走过去，阿尔从后面把手放在舒尔特垂下的脑袋上。不仅不讨厌被这样做，反而显得有点开心，这稚子有够狡猾。

啃食周围的人的好感，殷切盼望肥美丰满的未来。

「那，舒尔特酱今天的哀叹是什么？公主又出不讲理的难题了？」

「『又』是什么意思？说起来，妾身何时给舒尔特出不讲理的难题了？舒尔特会这样哀叹，大部分的情况都是『谢尔夫』吧。」

「Self，自作自受。确实啦。」

抖动漂亮的眉毛，普莉希拉讲英文单字的可爱样子让阿尔苦笑。

接着他面向舒尔特，歪头道：

「怎么啦？舒尔特酱慌了手脚是家常便饭，可是公主的手段被怀疑可就大条了。可以讲给我们听吗？」

「那是，这个……」

「──记得你今天早上，跟侍女一起去街上。」

「──噗通！说中了！」

按住自己的小胸膛，舒尔特做出被说中心事的反应。

因为第一次看到有人说「噗通！」，所以惊讶之余也很感动。「街上啊。」阿尔看向窗户外。

普莉希拉在这边说的「街上」，指的是最接近豪宅的库尔弗纳。

在跋利耶尔宅邸附近的库尔弗纳城镇，想当然耳是跋利耶尔领地最受普莉希拉影响的土地，也可说是欣欣向荣的城镇。

正确来说，是普莉希拉「令其繁荣」。

「莱夫老爷爷当领主的时候，那里可是惨不忍睹呢。」

普莉希拉的亡夫，前任领主莱夫•跋利耶尔男爵的专横跋扈，从旁人来看也太过极端，领民更是苦不堪言。

此时飒爽现身的，是广施善政拯救他们的莱夫的「爱妻」普莉希拉。

现在回想起来，要是有人主张莱夫旁若无人的过分行径是为了拉抬后继的普莉希拉的人气的话，大家可能都会相信。

只不过对于精神崩溃、几乎都躺在床上，跟死没两样的莱夫来说，那种评价根本连听的价值都没有吧。

「舒尔特，你在库尔弗纳做了什么？」

「我……我太无能为力了……！」

自行扛着对瘦小肩膀来说过重的行李，舒尔特面对普莉希拉的问题紧咬嘴唇，结结巴巴地回答。

那是今天早上他跟侍女出门采买时发生的事，简单来说──

「……也就是说，一对兄妹因为公主的事吵起来，你上前仲裁，却失败了？」

「是、的……」

阿尔总结，舒尔特轻轻点头，湿润的双眼充满不甘心。

低头看着他，心想该怎么办的阿尔，用手指拨弄头盔的接缝，让它卡铿作响。

──根据舒尔特所说，事情是这样子的。

跟侍女一同前往库尔弗纳的舒尔特，途中遇到在马路上吵架的两个小孩。想说只是起口角的话就放着不管吧，但这两人──似乎是兄妹，吵架的原因却是普莉希拉。

「哥哥说了普莉希拉大人的坏话，而妹妹泪汪汪地反驳。可是吵到一半的时候，妹妹被推开……」

「于是就忍不住介入了。可是，看到舒尔特酱也不怕，那个哥哥胆量可真大。」

「──？」

当事人面露不解，不过在外用不着自我介绍，大家也都知道他是普莉希拉的随从。

在跋利耶尔领地是知名人士，在库尔弗纳恐怕也没人不知道他吧。连面对着舒尔特都还继续骂普莉希拉，可见得对方勇气过人。

在这个世道，八成是个脖子会被割断死掉的勇者。

「当然，公主再怎么样也不至于做出那种暴行……」

「──出发，去库尔弗纳。」

「喂，等一下等一下！冷静点，公主！这样不行吧！」

岂止话刚说完，根本是还没讲完对她少到可怜的信任之前，对方就起了身，阿尔连忙安抚平息普莉希拉的愤怒。

虽然领民高声批评领主确实是很愚蠢的事。

「再怎么说，就只是小孩子嘛？那对兄妹跟舒尔特酱年纪也没差多少，对吧？」

「是的！哥哥只比我大一点而已。」

「看吧！这样就要砍他的头未免也太……」

「蠢货。」

气势如虹阻止普莉希拉的阿尔，咽喉被对方的扇子尖端抵住。

顿时，声音被封住，紧接着火热感从外部炙烧咽喉，阿尔发出惨叫，整个人翻倒。

「呜呀啊！好烫！好烫好烫烫！做、做过头了吧！？」

「哪有什么做过头。不能正确汲取主人的意图，那放你这种丑角在身边的理由也消失了。不得据此立场傲慢懒散。」

「懒散是指……」

「你能随侍在妾身旁边，别以为是理所当然。」

「唔咕！」

按住被烫伤的喉咙，阿尔在普莉希拉冰冷灼热的视线下呻吟。

普莉希拉摊开刚刚烫他喉咙的扇子，遮住自己的嘴角。

「妾身可没打算做出你担忧的粗浅举止。不过，舒尔特可是哭着说能力不足了，要是不有所行动，有损做主子的颜面。」

「……真心话呢？」

「排遣无聊，还有，这样痛骂妾身倒是令人产生了兴趣。」

「我就知道……」

多么有普莉希拉风格的回答。阿尔对此垂头丧气，接着环顾周围。

「奇怪？话说回来，舒尔特酱跑哪去了──」

「阿尔大人！请用──！」

「咳吧！？」

寻找不见人影的舒尔特的瞬间，正后方传来当事人的声音。一回过头，大量的水就朝阿尔的脸倒下。

仔细一看，气喘吁吁的舒尔特拿着走廊上的装饰花瓶。先仔细地把花都拿了出来，然后用里头的水给阿尔洗澡。

滴答滴答。头盔处处都有挟着植物特有气味的水珠滴落。阿尔对舒尔特突然做出这种过分的事感到惊讶，于是问道：

「唉～请问……？为什么？」

「因、因为阿尔大人烫伤，我想说要赶快冷却伤口……」

「原来如此～」

听了答案，阿尔点点头，扭动脖子发出声响后，抬头看向普莉希拉。

「我去洗一下头盔和擦干，可以给点时间吗？」

就这样，请主子延迟出发。

3

「因此，妾身就这样直接出面了。」

「──」

普莉希拉威风凛凛地宣告。看到在她面前整个人僵住的人，阿尔发自内心感到同情。不过，除了同情以外，他也不能做什么就是了。

他既没有阻止她的力量，而且打从一开始也就不打算阻止。

「敢对公主有意见，怎么会做出这种不要命的行为。」

首先，普莉希拉会听随从阿尔的意见，是非常罕见的事。

事实上也是，清洗被花瓶的水弄湿的头盔，仔细擦干后回到房间的阿尔，发现根本没人等自己。听到普莉希拉和舒尔特早就离开宅邸，才连忙追上去。

而这个时间点，普莉希拉已经站在出门的目的面前──

「啊、呜……」

被红色视线凝视，惴惴不安、眼神游移不定的是一位年约十三、四岁的少年。

暗红色头发和雀斑脸孔，可以说是没有醒目特征的普通男生。面对领主突然来访，想必整个人怕得要命吧。

而且自己就是来访的原因，就更不用说了。

「太阳公主……！哇啊，是真正的太阳公主耶！」

而在面色铁青的少年旁边，手掩嘴角雀跃不已、难掩兴奋的，是绑着红色辫子，年约十岁左右的女孩。

根据舒尔特在宅邸所说的话，这两人恐怕就是那对问题兄妹──讲普莉希拉讲到吵起来的兄妹。

「而且说公主坏话的，是哥哥……」

拥护普莉希拉的妹妹挺身面对讲领主坏话的哥哥，然后舒尔特加入，却还是输给了哥哥。

假使立场颠倒过来，是年长的哥哥安慰不懂世间道理的妹妹这样的形式，那倒也不会有什么问题吧。但偏偏不是这样，所以才微妙。

而说到微妙，少年的年龄也很微妙。别看普莉希拉这样，她对小孩子意外地宽容，不过，少年的年纪可以挤进那个宽容范围内吗？阿尔觉得这就很难说了。

要是有什么差池的话──

「要是会让随意斩了领民这种谣言传开，不如现在由我冒险出面阻止？虽说若想说服公主的话，会被打到骨折啦。」

事实上，恐怕不只是骨折而已，说脑袋会搬家甚至比较恰当。

无论如何，他维持着有什么万一随时都可以冲过去介入的姿势，提高警戒，踏进刚过午后就有可能一触即发的现场。

结果注意到阿尔的舒尔特高声大喊：

「啊！阿尔大人！您追上来啦！那个，头盔不要紧吧？有没有生锈或坏掉……」

「哦哦，没事没事，不用担心喔。唉呀，假如真的坏掉的话，到时就用舒尔特酱的存款买一个适合我的新头盔送我吧。」

「新头盔……可是，说不定帽子比较好！戴起来比较时髦，而且也可以看见阿尔大人的脸！」

「完全不隐藏旺盛的好奇心也是舒尔特酱的可爱之处呢。……是说，公主那边怎么样了？已经让小孩子哭出来了吧？」

舒尔特对阿尔的长相兴致勃勃，阿尔轻松带过，并把话题转向普莉希拉。听到他的话，美丽残酷的美女斥责道：

「蠢货。妾身有可能做出那种事吗？现在正在告知此行用意。」

「说是用意，要怎么表达？」

「听闻他痛骂妾身，所以来问他说了怎样的谩骂。」

「那真是节哀顺变……」

背地里讲人坏话被当事人知道就已经很尴尬了，还被当事人直接上门质问，怎是一句尴尬就能表达的情况。更何况，对方还是自己住的地方的领主，现在一定是吓得魂飞魄散了。

「太阳公主！我哥哥很过分！说太阳公主的坏话……请骂他！跟他说不可以这样！」

但妹妹却不知道哥哥现在的心境。不了解事态严重性的女孩直接向普莉希拉告状。

普莉希拉接受了的话，少年很有可能不是挨顿骂就能了事的，可是要女童了解这点实在是强人所难。

「呼嗯，由妾身亲口斥责吗。实在是很有意思的提案。舒尔特怎么想？」

「呜……这都是因为没法好好回嘴的我不好。所以，要是由普莉希拉大人回嘴，该说是很奇怪吗……」

「表达得不干不脆。不能好好讲吗？」

「我、我想让普莉希拉大人看看我努力的样子！」

在普莉希拉面前挺起胸膛表达决心的舒尔特红了脸，重新面向少年。「哦哦。」他的模样，让跟普莉希拉并肩看着他的阿尔十分感动。

不可以把这件事交给普莉希拉处理。尽管切入的角度跟阿尔完全不同，但舒尔特也产生了相同看法。他抬头看向比自己高的少年。

「大哥哥，你为什么要跟妹妹讲那么坏心的话！普莉希拉大人非常漂亮又可爱！头脑也很聪明……哪里奇怪了！」

「这、这个……」

「对啊！哥哥每次都这样，每当我称赞普莉希拉大人，不管我讲什么都只会反驳『才不是那样』！你仔细看嘛！那么漂亮！」

乘着舒尔特的气势，女童也朝哥哥赞美普莉希拉的美貌。

被两名幼童夸奖美貌、承受少年紧张视线的普莉希拉一动也不动，毫不吝惜地将自己那番绝不动摇的火焰美貌暴露于公众视野中。

不过，少年看着她的视线里头掺杂的感情，跟之前听到的不一样，感觉是有点复杂的情绪。

讲白一点，他的紧张不单是针对领主，还因为面前有个让人眼睛承受不住的大美女。

「这样看来，似乎不是因为讨厌公主呢……是那个吧。我就是不称赞大家都说是美女的人，这样才显得我是个硬派。青春期特有的逞强。」

「你的比喻听不懂，不过妾身大概找到原因了。──阿尔，你有兄弟姊妹吗？」

「我？我独生子兼长男。」

「那么，跟你说了也不会懂。」

被干脆地抛了这句话，阿尔不禁一副苦瓜脸。不过这表情被头盔隐藏着，所以没被任何人看到。

「少苦着一张脸。阴沉都传到空气里了。」

「好可怕！」

应该没人看得见的表情却被看破，阿尔感到畏惧。普莉希拉不睬他，走上前去。

被舒尔特和妹妹追逼得几乎都让人感到可怜的少年，又意识到了压倒性美貌和权力的存在而萎缩。

但是──

「你们兄妹，都是红头发呢。」

「咦……」

「妹妹的是亮红色，哥哥是暗红色，不过构造是一样的吧。」

普莉希拉伸手，用手指梳理少年的红发。这让少年目瞪口呆，女孩则是大声回应。

「对啊！因为红头发的小孩很少，所以我说『跟太阳公主一样，很高兴』。结果哥哥连这个都要生气……」

「只是红发少见就被周围的人另眼相看。因为这种小事被人找麻烦也不是一次两次了。你们呢？」

「您指被人讲坏话吗？有。可是，这个时候……」

顺着普莉希拉的问话，女孩回想不好的遭遇，看向哥哥。

这视线的意思很清楚了，就跟普莉希拉举的例子一样，被人以红头发为理由找碴的时候，每次都是由女孩的哥哥来出面反驳吧。

只不过那种事，在普莉希拉•跋利耶尔这位红发的「太阳公主」出现后，就没再发生了。

「──。哦～原来是这样啊。」

虽然比普莉希拉慢很多，但阿尔也意识到兄妹吵架的原因了。

也就是呢，哥哥对普莉希拉反感的理由是嫉妒。

「原本因为红发而被取笑欺负的时候，保护妹妹的都是自己。可是公主登场后，立场就瞬间转变了……」

感觉做哥哥的自信和矜持被整个抢走，所以妹妹一称赞普莉希拉，就忍不住反唇相讥。而且时间点又不凑巧，当时舒尔特正好经过，无法当作没听到，于是事情就闹大了。

「统整起来的话，真相自然就清楚了。不是谁的错，硬要说的话就是运气……不，是星星的错吧。」

「呣呣呣，看这样子，阿尔大人好像知道了什么！？」

理解后阿尔不住点头的反应，令舒尔特用小小身躯拼命回应。他跳着跑向阿尔，拉着他的衣摆仰望他。

「四十五度角看人很狡猾喔。」

「──？为什么？有事隐瞒才狡猾！也请告诉我！我也很在意阿尔大人的长相！」

「不要在这边追加希望啦。说起来也没什么大不了的，就只是……」

刚好进入青春期的兄妹吵架，阿尔试图以此做个总结。

实际上，对话要是再拖得更长的话，只会让为妹妹着想的少年感到害羞，这样他未免太可怜了。而普莉希拉非比寻常的美貌与异样的气质，也使得人们开始聚集起来。

被原本的兄妹吵架气氛给吸引的年幼孩童很多，但骚动没必要地扩大后导致更多人聚集，情况变得难以应付。

这正是靠阿尔的方式收拾问题的大好时机。

──就在这个时候。

「──好。那么，开战吧。」

突然一记宣告烧毁了整个对话流程，支配现场。

忽然听到开战宣告，理所当然的，除了宣告者──普莉希拉以外的所有人都愣住了。就连阿尔和舒尔特也不例外。

不过，突然被当成战争当事人的兄妹，惊讶程度更甚吧。

脸色惨白的哥哥如今更是瞪大眼睛，妹妹则是对这番超出她理解的话频频发出「咦？咦？」的声音。

虽然无关，不过兄妹慌张失措的模样是一个样。

而不等其他人的反应，普莉希拉便哗啦张开手中的扇子，向听到自己声音的所有人下令。

宛如难以抗拒的火焰吞噬一切，将所有事物都染红，就是普莉希拉的做法。

这是你应该挥洒自我的对手和场面吗？阿尔非常疑惑，却没有插嘴。

因为──

「──开始战争吧。双方，都做好准备吧。」

如此宣告的普莉希拉的微笑，美得阻绝一切从旁干涉。

4

「我先确认一下，为什么要玩模拟战争？」

「蠢货。什么模拟，少用你的一己之见平凡看待。让不同意见进行对抗，若其中涉及武力的话，就可以称之为战斗了。」

「哪来的涉及武力……」

「按照舒尔特所说，是哥哥先出手的。」

俯瞰正在准备「战争」的庭院，普莉希拉直接阻断随侍在后的阿尔的疑问。

以兄妹吵架这种小事为开端的骚动，透过意想不到的形式被带进跋利耶尔宅邸。

是真的照字面意思被「带进」来了。

「──」

骚动中心的兄妹，跟他们的朋友──相识的男孩女孩全都被聚集起来，用龙车送到跋利耶尔宅邸。然后，被不熟悉的领主豪宅内的景观与氛围给震撼的孩童们，正在有条不紊地接受「战争」的教育。

当然，不是拿真枪实盾开打的战争──

「看到是木剑和泥巴球的时候，我松了一口气。毕竟公主真的有可能让他们拿真的刀剑上场。」

「拿那种连使用都不会的道具是没法发挥本领的。如果那些是战士的话也就算了，可他们是连士兵教育都没受过的身份。」

「稍微训练过就能让他们拿武器上战场的发言，感觉会炎上，好可怕。」

「为什么会突然烧起来？搞不懂意思。」

听了阿尔的干话而皱起娥眉的普莉希拉质问「炎上」的意思。

对此耸肩带过的阿尔，看向地面乖乖照着安排在做「战争」准备的孩子们。

好歹是「战争」，因此一群人被分成两派阵营。

也就是作为中枢的哥哥与妹妹，分别是东军和西军的首领。两边人数各十五人，集结起来的都是兄妹的朋友，只是哥哥那边的平均年龄较高，男女比例方面也是哥哥那边男生比较多，以一般眼光来看，会认为哥哥那边胜券在握。

当然，妹妹那边也不是完全没有男生。然而──

「我会加油的！大家一起齐心合力，证明普莉希拉大人的伟大～！」

斗志高昂的舒尔特就是其中一人，所以应该很难赢取胜利吧。

原本舒尔特的发育就比同龄小孩慢，再加上普莉希拉的刻意引导，使得他许多行为都无法表现得正常得体。以战力来说根本是极度不合格。

他的奋斗精神让人会心一笑，却又令人痛心。

不过另一方面，很难认为普莉希拉没掌握这种状况。

「怎么着，又是一张无趣的嘴脸。」

「就说了，不要透视头盔里面啦。我是什么嘴脸公主应该不知道才对吧。」

「要是未曾见过，或许如此吧。但不是那样吧？」

「──！」

听到他的不满抱怨，普莉希拉轻触自己嘴唇。

视线被这举动和粉色嘴唇诱导，阿尔想起了以前被看到素颜时的事而噤声。

那是不可抗力。但是，普莉希拉和阿尔在角色上不同。不管怎样虚张声势，被人握住弱点的心情是无人可以颠覆的。

「──你问了妾身，为什么是战争，是吧？」

就在以为对话被迫结束的时候。

看都不看不发一语的阿尔，坐在椅子上的普莉希拉拄着脸颊这么说。对此，阿尔闭上一只眼睛，她则是盯着底下的孩童们。

「既然彼此没有退让的意思，就算是亲手足也有必须动干戈的时候。决心被质疑的情况，是不会被体内的血统浓淡所左右的。」

「……不是不能懂，但这决心非得现在去质疑吗？兴奋起来的妹妹姑且不论，哥哥那边没想到事情会变这么大条吧。」

「应该说过了，先使用武力的是哥哥。」

意见被跟前面一样的道理驳斥，阿尔万般无奈地抓抓脖子。

兄妹吵架的原因，和哥哥不得不这么做的心情都已经明白了。但是，出手推人确实不对。这就是所谓的报应吧。

「不过，『战争』开打后，哥哥赢的话，不是反倒出乎意料了？」

「哥哥赢的话，确实如此吧。但是，士气站在妹妹这边。再加上──」

「再加上？」

「妹妹那边，有妾身指点。」

附加的情报在阿尔心中，是足以颠覆原先评估的震撼弹。

老实说，阿尔不知道普莉希拉是否通晓会战的战术。虽然不知道，但他期待普莉希拉没有做不到的事，也是不争的事实。

而且神奇的是，这个大无畏的绯色公主，被所有事物所爱。

这正是──

「──这个世界，就是为了妾身量身打造的。」

她这样标榜的哲学，简直就像世界团结起来帮助她似的。

「……公主莫非有兄弟手足？」

迎着为了普莉希拉而刮起的风，阿尔突然产生这样的疑问。

这是连阿尔本身都没想到会脱口而出的话，说完才意识到这可能会触怒普莉希拉，内心因此慌乱不已。

但是普莉希拉没有搭理他的内心波澜，眯起眼睛道：

「真唐突。为何这么想？」

「没有，真的就是天降泉涌的印象？一开始会察觉到兄妹吵架的原因也是这样，还有就是，呃……」

「不要在这边停顿。想惹妾身不高兴吗？」

「……因为你对搞砸的哥哥很严格？」

毕竟是脱口说出莫名涌现的念头，因此在心中没法顺利化作语言。但是刻意讲出来后，就想到了让自己挂意的理由。

仔细想想，一开始会说要前往库尔弗纳，不是因为有人在背地讲她坏话，或是舒尔特能力不足，而是听到兄妹吵架的内容时才做出这决定。这事越想越合理，不是吗？

最重要的是──

「──」

听了阿尔的推测后，普莉希拉难得默不作声。

她也有这种因为心事被人说中而沉默的可爱之处吗？惊讶之余，阿尔身体前倾，想要拜见她的表情。

结果，下腭被伸过来的扇子尖端戳中。

「好烫好烫烫烫！？」

普莉希拉再度施以灼热制裁，焚烧阿尔的好奇心。

「啊咕！嘎呃、啊！好烫！干嘛啦，公主！？」

「不得抱着无礼想法窥探妾身的脸。对妾身的美貌产生情欲是男儿本色，但希冀更多，就要支付相对应的代价。」

「因为这样就要把喉咙烧成焦炭未免太不讲理……啊啊，可恶！」

遭遇辛辣应对，导致连优越感也被烧焦，阿尔边摸喉咙边沮丧退下。

接着普莉希拉轻声吐气，说：

「手足的话，曾经很多。有哥哥弟弟，也有姊姊妹妹。」

「……嘿～好难想像。」

先前提出的问题收到答覆，阿尔歪头思索普莉希拉的家人组成。而他的回应让普莉希拉反问。

「呼嗯。为何很难想像？」

「虽然是我先问有没有手足的，但我不觉得公主是会在拍家族照片的时候乖乖听话的类型，而且那种身为姊姊或妹妹的感觉也很低。听到你说你两者兼具，脑子里就产生了bug、lag和error之类的。」

「一口气说这么多，是大瀑布对面讲的『跳楼大拍卖』吗？」

含笑之后，普莉希拉活用一知半解的词汇，但阿尔没有迟钝到没察觉出她这番话里头蕴藏的几许乡愁。

乡愁，没错，乡愁。普莉希拉也会怀念什么东西，这件事真的让人很吃惊。

也很在意她用过去式表达自己曾有很多兄弟姊妹这件事。

「普莉希拉大人！准备万全了！」

阿尔跟普莉希拉的对话告一段落的同时，在庭院里的舒尔特大喊。

看过去，装备了「战争」用武装的孩子们分站庭院左右两边，斗志高昂，急着要证明自身的武勇。

妹妹的阵营本来就士气很高，连一开始没干劲的哥哥阵营在即将开战之际，热度也都提升上来了。

「这下子，要大乱啰。」

「正因如此，才有点火的价值。」

阿尔的语调意外兴奋，普莉希拉也站起来这样回答。观察她的侧脸，尽管只有一瞬间，但掠过她眼眸的情感掳获阿尔的心，然而在解读出那意味着什么之前，普莉希拉就把扇子朝前比出──

「双方，竭尽死力对决。既然坚持意志互不相让，证明自己正确的方法，便唯有取胜。──那么，开始吧。」

「──上啊──！！」

接受绯色公主的高声号令，孩童们高亢的呐喊响彻天空。

以跋利耶尔宅邸为舞台的「战争」开始，兄弟姊妹开始对决。

看着这光景，阿尔终于掌握住先前内心疙瘩的答案了。

普莉希拉的侧脸所透露出的微小东西，是期待。

──能否看到自己想看的东西，里头有着这样的期待。

5

「今天大吵大闹的，到底是在干什么？」

带着酒气的脸庞红通通的，摸着没在打理的胡渣下巴，男子歪头问道。

发色亮红如火的高个子，脱去轻铠，只着一件衬衫，透露出锻炼有素的身材，跟平常自暴自弃的态度给人截然不同的印象。

不过，说不定当事人并不期望给人这种印象。

──入夜的跋利耶尔宅邸，阿尔在白天也待过的阳台仰望夜空时，并非跟普莉希拉、也不是跟舒尔特，而是跟这男的度过雀跃不起来的片刻。

并不是特别在这儿碰头。只是偶然度过平静夜晚的时间和地点重叠，彼此互不相让也不退避罢了。

有时，像这样在没有人的阳台沉思，对男人来说是必要的时光。

「唉，像我们这种年纪的男人，有很多复杂的事啦。」

「什么？」

「没有，在讲我自己。不管过多久，男人都还是青春期啦。」

男子皱眉看过来，阿尔缓缓摇头回答。

年龄越大，相应的烦恼就会增加，不过若谈到自己的话，根本的本质却没有太大变化。结果，就是到死之前都还持续在问同一件事吧。

──自己到底是什么人？这种像是青春期会有的烦恼。

「……算了。所以，没有要回答吗？」

「哦，是公主心血来潮啦。不过若要问那个是什么的话，我也有没办法完全掌握的部分就是了。」

「太阳公主的首席骑士，可真悠哉呀。」

「饶了我吧。从以前就说了吧？我不是当骑士的料啦。」

「──」

骑士。就算是开玩笑，阿尔也讨厌被这样揶揄。

甚至对骑士这个职业有偏见，认为每个骑士都不是什么好东西。对自己和普莉希拉来说，都没打算要用那种东西来装饰彼此的关系。

说起来，骑士云云的话题，不只阿尔，对方也很讨厌吧。

毕竟──

「因为是『骑士中的骑士』莱因哈鲁特•范•阿斯特雷亚殿下的父亲。」

「呿！」

被这样讲的中年男子──海因格•阿斯特雷亚不悦咂嘴。

满面愁容、放任胡渣乱长、简朴的穿着在在都削弱了仔细看很端正的容貌，加上红色头发，就跟王国的知名人士「剑圣」特征一样。

他们是亲生父子，所以自然长得像。──当然，父子关系复杂也不在话下。

不然，就不会发生父亲跟儿子服侍的主子分属不同阵营这种事了。

「──」

安静下来后直接拿起酒瓶对嘴喝的海因格，目前是普莉希拉挑战王选的阵营成员之一。话虽如此，他被期待的职责是什么，是连阿尔都没法预测的东西。

这可是普莉希拉的意图。很难认为其中没有任何意义。

「我既没有能忖度的器量，也没有这种想法。」

「话虽如此，那种调调，旁人会很伤脑筋吧。要是普莉希拉大小姐认真想要那王位的话，就会诞生一个人没人能理解的国王……」

「跟那没关系。──不管做什么，我都会让公主获胜的。」

靠着阳台扶手，轻轻抚摸今天普莉希拉倚过的部位，阿尔道出这份决心。

听到阿尔果断地这么说，海因格微微睁大眼睛。

「真意外。还以为阿尔殿下对王选的结局没兴趣。」

「喂喂，说得太过分了吧。我可是每天都在为此烦恼喔。」

「……是吗，那我换个说法。我认为，自己没必要去参与王选的过程。普莉希拉大小姐一个人就能包办一切。」

「哦。」

海因格充满刺探的推测，令阿尔微微吃了一惊。

是因为他说出了自己完全没想过的事？并非如此。自己是对海因格竟然拥有看清周围的眼光一事感到惊讶。

──不，想到普莉希拉今天连续两次看穿头盔内的表情，说不定是阿尔其实并非自己所预想的是张扑克脸。

「唉呀，就是因为有部分自觉，所以才像这样戴头盔的哟？」

明明很干脆地选择罩上头盔，但还是藏不住所有溢出的情绪。或许自己应该成为一名演员，而不是居无定所的流浪汉。

「唉呀呀，连这都保持沉默吗。真是个爱隐藏秘密的人呢。」

「这个一看就知道了吧。我可是一开始就把脸藏起来呀。哎哟，就算我的秘密解开了，也没什么特别有趣的情报。硬要说的话……」

「硬要说的话？」

「我认为，我跟你算是同类人喔。」

只靠口耳相传的情报，就能得知海因格身负的复杂经历。

拥有被称为「剑鬼」的伟大父亲，以及被誉为史上最高杰作的「剑圣」儿子。夹在他们之间的三明治世代，被郁闷和立场给折磨的可悲男人。

值得强烈同情。──害怕伟大至亲的心情，自己非常能够理解。

「……你，懂我的什么了？」

「我就知道你会这样讲！」

皱起鼻子后，海因格厌恶地这么说。不被理解也不想被理解，碰到这拒人于千里之外的态度，阿尔笑得轻快。

接着背靠扶手，抬头仰望夜空明月。

「在我看来，今天的『战争』是公主的确认作业啦。」

「──『战争』？」

「就是你所说的大吵大闹啦。让意见互不相让的双方召集同伴，分成两个阵营，诉诸武力来决定谁是正确的……就是『战争』吧？」

「他妈的无聊至极……」

是醉意加深了吧，海因格讲话开始带脏字。他喝醉的情况是喝得越醉就离严肃和真诚越遥远，在旁边看着觉得很有趣。

阿尔不喝酒，所以不知道自己喝醉了会怎样，不过他人喝醉的丑态足够抑制他想喝酒的欲望了。

无论如何，阿尔判断普莉希拉对「战争」的态度是一种确认作业。

「公主有想看到的东西。所以就利用那对兄妹的吵架确认看看，这是我的推测。」

「想看的东西是……」

「很遗憾，公主不肯说明，我也不知道是什么。说起来，我的推测也有可能从一开始就是错的。」

「没用的东西。就算会断另一只手也要问到啊。」

「你喝醉了真的就净会造口业耶！？双手健全的人大概不明白吧，我这只手可是比有两只手的家伙还重要！」

根据情况，他那话有可能会导致两人起冲突，但海因格没有道歉。

不是因为他觉得别人怎样都无所谓，毋宁说正好相反吧。就因觉得自己怎样都无所谓，自暴自弃才得以成立。

事实上，要是别人因为自己的谩骂而要求决斗的话，海因格一定会喜孜孜地接受。只不过──

「一旦知道你是『剑圣』的父亲，对手就会立刻收起剑吧。」

「……呿！」

听到阿尔这句话，海因格移开视线，再次咂嘴。

不管话题怎么绕，平静夜晚的阳台上总是回到同一个议题。──到头来，自己是什么人，任谁都没法逃离这个课题。

「……刚刚讲到想看的东西。」

「嗯？」

傻傻地望着夜空，思绪跑到各个具有名字的星座上时，阿尔被带着酒味的声音给拉回地面。

看过去，略带迷蒙的蓝色眼睛盯着酒瓶中残存的酒滴，海因格说：

「阿尔殿下也有吗？想看的东西……」

「我很讶异你对我有兴趣。还以为你只对家人有兴趣呢。」

「──哼！」

话才刚讲完，面颊扭曲的海因格就把酒瓶扔向阿尔。

「哎哟。」阿尔倾斜脖子，躲开旋转飞过来的东西。瓶子飞越扶手后往庭院坠落，一秒后发出撞击地面的碎裂声。

然后海因格看都不看就背过身子要离开阳台，宛如想逃离触怒了他逆鳞的阿尔似的──

「──我也有喔。」

阿尔只朝那离去的背影这么说。

顿时，海因格停下脚步，没有回头，继续倾听。如此老实期待令阿尔苦笑，但却没打算说更多了。

「我也有想看的东西。像是公主洗澡的样子。」

「呿！」

「这是今天咂嘴咂得最大声的一次！」

故意搪塞掩饰带过的阿尔，得到了至今最大的咂嘴声。

6

「那对兄妹和好如初，真是太好了。」

「呼嗯，舒尔特是这么想的吗？」

「是的！不愧是普莉希拉大人！我很自豪！」

舒尔特满脸喜色，反应天真，没有一丝怀疑。面对如此坦率的纯真，普莉希拉闭上一只眼睛，从敞开的睡衣前襟拔出扇子。

接着她用扇子前端抬起舒尔特的下巴，让圆睁眼珠的男孩看向旁边。这么一来，右脸颊上的红色印子便看得一清二楚。

这是今天的「战争」留下的痕迹，所谓的荣誉负伤。

「把战伤称作名誉，在妾身看来只是过失的证明。」

「普莉希拉大人？」

「脸颊会痛吗？」

「还有一点麻麻的，不过没事！这也全都是为了胜利而有的战术……！」

用力握紧小拳头，舒尔特发挥不厌牺牲的精神。

除了脸颊上的红印子，舒尔特身上处处都有在「战争」受的伤。跌倒擦破膝盖、背被打到瘀青，恐怕其他地方也还有吧。

受伤就会痛，会想哭。事实上，舒尔特也哭过了。

可是──

「这次的事，是妾身起的头。你恨妾身吗？」

「──？我恨普莉希拉大人？完全不可能啊！」

「──」

「不如说，幸好有为普莉希拉大人战斗！在那边站着发抖没法动，我认为比痛还可怕……」

舒尔特低下头，称赞自己的少许勇气。这反省可说颇有他的风格，另一方面，他的态度也跟身体的伤一样令人痛心。

而令人开心又痛苦的是，舒尔特这样并不显得特别奇怪。

而是任何人都可能发生的一种「热病」。

「──」

结束白天的「战争」，沐浴完的普莉希拉坐在床上。换上睡衣的舒尔特会在卧室，是因为抱着他入睡是每天的习惯。

娇小可爱的男孩，对普莉希拉来说是无可取代的抱枕。

只不过舒尔特本人并不满足于只是个抱枕。今天的「战争」就证明了这点。普莉希拉心想。

──被称为「战争」的兄妹吵架，如自己预料得到解决。

也就是说，普莉希拉提点的妹妹阵营获胜，舒尔特也可以说有稍微做出了贡献：在死得壮烈以令对手困惑这个层面上。

「我以为练习的成果会显现出来，但太天真了……不管哪边都是敌人，结果就被痛揍了一顿。」

讲先锋是比较好听，但以舒尔特的情况而言，更确切的说法是他头一个牺牲。

无论如何，打头阵的舒尔特第一个被挂掉，妹妹阵营的士气因此岌岌可危；相反地，哥哥阵营士气大增。就这样，妹妹阵营的抵抗徒劳无功，被一口气站上优势的哥哥阵营给逼到绝境──

「果然，哥哥就是哥哥呢。」

就如微笑的舒尔特所言，哥哥就败在他身为哥哥。

「战争」到最后，妹妹阵营的人都倒下了，可是来到敌方首领妹妹面前时，只要撂倒妹妹就胜券在握的哥哥却犹豫不决。

普莉希拉的指点就在这一刻发挥作用，而且「战争」因此分出胜负。

「胜利条件在于打败敌方首领……既然如此，就算剩下一个人，只要解决掉敌方首领就算获胜。胜算就只在最后那一刻。」

这一点，那个妹妹可说有仔细听进普莉希拉的话，并鼓起勇气执行。

普莉希拉提点的内容很简单明瞭──「哥哥最后要杀你的时候会犹豫，你就乘机刺哥哥。」就这样而已。

而且就如普莉希拉判断的一样，胜负就是以那种形式尘埃落定。

只不过──

「最后，哥哥阻挡自己的阵营成员，保护了刺向自己的妹妹，真的很棒呢。就跟普莉希拉大人说的一样，他们和好了！」

其实最后的状况没有如天真无邪的舒尔特所开心的那样。

身为首领的哥哥被妹妹的策略打倒，导致以为赢定了的哥哥阵营残存者不肯认输，结果把怒气转向妹妹，但挡下他们的即是哥哥。──原本，就是因为兄妹感情好才会发生这次的事。

哥哥不希望妹妹被当成坏人，被大家责备而害怕的妹妹也对保护自己的哥哥再次拾起尊敬与亲情。这就是结论。

「──」

即使看到结论，普莉希拉的内心依然有着些许乌云。

虽然过程中的一切并未全部如自己预料，但结尾大致按照自己的想像发展。即便如此，普莉希拉心中的结论原本也是二择一。

也就是自己的提点有成功，或是没有。

推测命中，妹妹趁哥哥犹豫而行刺并取得胜利。──不，妹妹得到的不是胜利，应该说是确信吧。

这是哥哥无私爱着妹妹的证据。

虽然是模拟，但那是「战争」。人的死亡是假的，受的伤也很轻的「战争」。

只要有那个意思，普莉希拉是可以召开一场真正关系到生死存亡的战争，像今天一样诱导许多人狂奔勇赴战场。

煽动那些像舒尔特一样天真无知、以信仰为力量的人民。

自己有那能力与责任、地位与美貌。普莉希拉对此有自觉，而今天的结果可以说是补强了这点。

然而内心挥之不去的乌云却在降雨，是为什么呢──

「……果然，没有看错。」

「呣？」

沉思时，身旁的舒尔特突然发言，且语气消沉。

每次都很开朗的他难得有这种反应，普莉希拉把注意力移到他身上。结果，他用双手揉自己的脸颊。

「普莉希拉大人，您很寂寞的样子。」

「很寂寞？妾身？」

「在我看来是这样。……您看着那对兄妹的时候，眼神有点难过。」

视线往下滑，舒尔特的低语透露着担心。说不定这个稚子认为自己没法好好平息兄妹吵架才会害普莉希拉心烦意乱，所以为此责备自己。

不过，是舒尔特想太多了。在那之前──

「──呼哈。」

「普、普莉希拉大人！？」

手轻贴在嘴边，却还是吐出没法完全压抑的急促呼吸。这是连普莉希拉自己都出乎预期的笑声，也是舒尔特带来的真情流露。

说中普莉希拉心头不肯放晴的乌云真面目，是舒尔特的功劳。

「妾身很寂寞难过，真是、真是……」

「哇、哇、哇……果、果然很奇怪！？是我误会了……」

「不会，虽然用字遣词有些不对，但还是要夸奖你。」

舒尔特惊慌失措，普莉希拉用扇子抵住他额头阻止他动摇，并带着微笑慰劳年幼的随从。

这话让舒尔特先是睁大眼珠，接着安心地抚摸胸膛。

愚昧无知，却也因此纯洁无垢的他，或许用那双没有阴霾的绯色瞳孔看穿了普莉希拉──灼热又持续燃烧的绯色公主的内心。

「舒尔特，你对妾身的感慨，不得向任何人提起。」

「普莉希拉大人好像很寂寞这件事？」

「好像很寂寞这件事，妾身绝不会承认……但被传出谣言也很麻烦。因此命令你闭口不提。──眼里封着赫炎的，妾身的勤务兵。」

眨眨红色眼睛，舒尔特慢了一拍才点头道：「遵命。」

听到这答案，普莉希拉将手放在自己丰满的胸部上，感受原本卡在那儿的乌云正在逐渐消散。

让人多少感到有点可恨的是，舒尔特的看法有一半是对的，一半是错的。

互相为彼此着想的兄妹之间的「战争」，其结局带来的东西，一方面正如普莉希拉所想；而另一方面，却又不是她期待的东西。

兄妹之间的感情、想法和爱这些东西，皆是会在各种因素面前失去光芒、温暖和明亮，逐渐蒙上暗影的事物。假如没办法这样断言的话──

「──不足的是妾身，还是兄长？」

怀中的幼童发出稳定鼻息。戳着他脸颊，朝着心头散去的乌云碎片问出这问题。

想当然耳，不会有答案。询问的机会，早在很久以前就已经失去了。可是──她有预感，心中的疑问，将在不远之后获得解答。

要是能一直被遗忘、被疏远的话，那样也不错。

可是，既然那股预感从这胸膛内的灼热开始复苏，那么答案一定会被带到自己身边吧。

要说为什么的话──

「──这个世界对妾身而言，本来就是量身打造的。」

《完》

（插图016）

** 后记

《Re：从零开始的异世界生活短篇集》第七集！感谢陪伴！我是作者长月达平＆鼠色猫！

成为久违短篇集的本书，是否有让您看得开心？最近因为忙于推进正传，所以冷落了短篇集许久。

当然，虽然是由番外篇收录进来的短篇集构成了本书，但作者可没因为是番外篇就放水松懈，内容依然倾注了全力和热情。

在正传一直遇到悲惨遭遇的昴，能够不靠死亡和死了重新再死来推进故事，可是很宝贵的！唉呀，虽然在这次的短篇集里，昴的戏份并不多，因此也没法活用他这优势呢！

那么，大家是否有发现，这次收录进短篇集的内容，是为了让各位能更加享受在正传第七章节进入的佛拉基亚帝国篇，才以这些故事组成吗？

第一则故事〈Lugunican Papers〉是将所有王选候选人放在聚光灯下的故事，第二则〈Sword Identity〉和第三则〈绯色联盟〉的焦点各自放在佛拉基亚帝国和普莉希拉阵营上。

活用短篇集和Ex的优点，填补护城河的作战……！西诺比真卑劣！我想大家如果能在不自觉的情况下搭上这想法，或许就能更加畅游在Re：ZERO中！

当然，除了让读者更加享受正传外，本书内容都是可以让人享受的好故事，可以看见许多角色不同的面貌并让您满意的话，没有什么能够比这个更能让作者开心的事了！

〈Lugunican Papers〉触及了至今不太接触、从外部窥伺王选候补者的故事。想也知道，绝大多数的人都不是候选人身边的人，所以这些人对她们的印象，以及让知道其为人的读者享受这中间的落差，就是作者想要达成的目的！

〈Sword Identity〉是以最近作者心中狂热度很高的帝国为舞台的故事。在正传中以敌人姿态登场的角色们，他们与她们各自的故事、想法与理想。看着这些互相碰撞后再接着阅读正传，我想应该能享受到两边总共两倍的内容才对！

〈绯色联盟〉是描写普莉希拉阵营中意外感情好的一面。不限于这篇故事，普莉希拉是个写起来非常快乐的角色，若能知道在各位读者的心中对她的印象是什么的话，我会很开心的。

那么，在聊到每则故事的时候，篇幅也来到了极限，接下来便进入惯例的答谢。

责编I大人，同时进行本书和正传第三十集，这次也多谢您的帮忙。为了避免作业流程重叠的进度安排，让我幸运捡回一命！

福きつね老师，感谢您绘制这次精美的诸多插图！气势磅礡的封面图搭配多张可爱插图，让我大饱眼福！

设计师草野老师，要一口气进行与正传同时发行的本书，真是辛苦了！两本书排在一起都毫不逊色，真的是很了不起！这次也让我看得非常开心。

在月刊Comic Alive有花鸡老师＆相川老师连载的第四章漫画。若想彻底享受Re：ZERO的话，那不只短篇集，也务必要看过漫画喔！

然后是MF文库J编辑部的各位、校对人员、各书店以及行销人员和许多人的齐心合力，才能完成这次的发行。每次都很感谢您们！

再来是不只正传，连短篇集都追的热情读者，容我灌注地球上所有的爱向您们致谢！

随着短篇集的集数增加，我也写了许多插曲，不过还是有很多想写也写不完的故事。若您往后能继续陪伴正传和本系列的话，是我的荣幸！

那么这一集也将在此道别！下次期待在某处的后记相遇！再会！还有谢谢！

2022年5月《对于下次要写什么心头满怀期待与干劲》