#+title: Re:从零开始的异世界生活 第四十一卷
#+setupfile: ./setup.setup

* 第四十一卷
** 序章 『魔女的梦呓』

「——我也跟你一样，是个不成材的女儿。」

『魔女』垂下那双长睫毛镶边的眼眸，说出这句话，让阿尔德巴朗不知道该说什么才好，只能沉默不语。

阿尔德巴朗总是与『魔女』相约在这片草原见面，这个不存在于世上的地方，是『魔女』创造出来的幻想城堡，也就是异空间。

就算询问原理，她也一定会用「就像在打瞌睡的梦一样」来敷衍过去，这片草原——今天难得迎来了夜晚。

「真是稀奇。」

阿尔德巴朗在布满星星的黑色天空俯视下，感叹地吐了口气。

基本上，草原的时间带固定在白天。因为这个地方是创造主『魔女』的心象风景，所以与真正的时间概念无缘。因此，草原总是明亮且晴朗。

本人明明只需要白色与黑色两种颜色，但没想到她意外地是个心情总是很好，内心经常露出晴朗天空的人。

正因为曾经有过这样的疑惑，所以阿尔德巴兰对于自己被迎接到了夜晚的草原感到惊讶。更何况，那位『魔女』还在山丘上打瞌睡。

「————」

『魔女』上半身趴在白色的桌子上，发出安静的呼吸声。

阿尔德巴兰原本想询问关于这片陌生的夜景，但注意到她睡着了之后，便屏住呼吸，仔细观察『魔女』的睡脸。

他最初的感想是，原来『魔女』也会睡觉啊。

虽然这可能是理所当然的，但『魔女』的生态就是如此神秘。因为她是能够随心所欲创造出异空间的存在，所以就算她不睡觉也不会让人惊讶。实际上，在今天之前，他从未见过她的睡脸。

「真是美到让人火大……」

虽然早就知道了，但她即使在睡觉，也拥有异常出众的美貌。

虽然那双蕴含着超群的知性与好奇心的细长眼睛闭着，但那仿佛神花费了大量时间进行微调的端正五官，以及仿佛在说世界不需要其他颜色而准备的美丽白色长发，还有白皙的肌肤——真的让人火大。

「仔细想想，这可是难得的机会，赶紧拿笔过来在她脸上涂鸦——」

「——唔」

「——！」

就在他想着这些不正经的事情时，『魔女』的薄唇发出了声音，阿尔德巴兰僵住了。

明明什么都还没做，却感觉自己像是恶作剧被发现的小孩子。但是，阿尔德巴兰的僵硬在下一瞬间达到了最大值。

——因为他看到了在打瞌睡的『魔女』的眼中，渗出了些许泪珠。

「老师——」

「——嗯」

阿尔德巴兰下意识地触碰了睡着的『魔女』的肩膀，摇晃她的身体。呼唤和肩膀的触感让『魔女』的喉咙微微发出声音，缓缓地睁开了闭上的眼睛。

那双黑瞳像是在确认什么一样眨了几次眼，然后映出了眼前的阿尔德巴兰。

「……阿尔德巴兰？」

「啊，嗯，是我，老师。真不像你啊，居然在这种地方打瞌睡」

「————」

在隐藏着动摇的阿尔德巴兰面前，『魔女』静静地起身。纤细的手指抵着自己的下巴，刚睡醒的『魔女』为了整理状况而沉默地思考着。

然后——

「——是梦啊」

她的低语中带着遗憾的语气。

『魔女』喃喃自语，用指尖拭去眼角的泪水，赶走睡眠的余韵。那不经意的动作，让阿尔德巴兰感到奇妙的寂寥。

然后，他不禁问了出来。

「居然做梦哭出来，真像小孩子啊——你做了什么梦？」

「————」

阿尔德巴兰因为尴尬而沉默，非常后悔自己问了这个问题。

说实话，他想象中的发展是『魔女』会讲述关于梦的渊博知识，或是因为自己对『魔女』的梦感兴趣而被捉弄，一如往常的发展。

但是，『魔女』没有用一如往常的发展回答阿尔德巴兰的问题。

取而代之，她给出的回答是开头的那句话。

『——我也是和你一样不成器的女儿哦。』

「————」

阿尔德巴兰再次反刍『魔女』的话，在沉默中混乱到了极点。

那到底是什么意思？可以深入询问吗？平时明明只要不阻止就会说个不停，为什么偏偏今天这么淑女？

——就算问了，确认了，『魔女』也不会受伤吗？

「……真是的，到底谁才是小孩子啊。」

「咦……」

「我是说你缩成那样，简直就像小孩子一样。不用担心，我可不是会被你伤害的可爱存在——我可是邪恶的魔女哦？」

『魔女』闭上一只眼睛，抛了个媚眼，说出招牌台词。从中可以窥见平时的她所具有的稚气，阿尔德巴兰长舒了一口气。

不知为何，他真的觉得自己差点就要死了。

「可恶，居然被老师你害得体会到这种感觉……」

「真奇怪。就我所知，老师应该是敬称才对，但我完全感受不到敬意。我只是因为被看到少女的睡脸，稍微掩饰一下害羞而已。」

「你的做法太恶劣了！」

差点造成心理阴影了，阿尔德巴兰如此抗议，但『魔女』却对他的控诉置若罔闻，心情愉快地用手指敲了敲桌子。

突然，装着茶的茶杯出现了，也有阿尔德巴兰的份。

「来，别生气了。既然机会难得，要不要我端点心出来？」

「不用了。在这里吃东西也不会饱，回到那边的时候，饥肠辘辘的身体和心满意足的精神会让饱足中枢产生混乱。」

「听你这么说，我更想让你吃了。」

「性格恶劣！」

阿尔德巴兰对毫不掩饰邪恶的『魔女』怒吼，用手托着下巴。然后，他偷看『魔女』愉快的样子，确认她脸上没有泪痕。

「————」

泪珠消失了。尽管如此，阿尔德巴兰的胸口仍然残留着无法消除的疙瘩。

『魔女』说那是开玩笑，但恐怕不是玩笑，而是事实——即使美丽又聪明的她，也会诅咒自己，想要流泪。

到底对谁而言，『魔女』是不完美的存在呢？

「嗯？」

「——没什么，贪睡的老师。」

阿尔德巴兰对歪着头表示疑惑的『魔女』咒骂，然后喝了一口茶。

大概错过了机会。同样的问题，还有机会再问吗？就算有机会再问，阿尔德巴兰想知道答案吗？

如果想知道，是因为想要同情或共鸣吗？

或者——

「——即使是假的星空，也是相当壮观的景色吧？」

是想让她那与星空同样漆黑，看起来比星空更加耀眼的黑瞳转向自己吗？

与『魔女』同样不完美的阿尔德巴兰，不知道答案。

** 第一章 『人类的天敌』

1

——「死亡回归」。

以性命为代价回溯时间，获得重新度过一度度过的时间的资格。

在受到那个恐怖的「嫉妒魔女」干涉下，为了除去面对的一切苦恼和障碍而耗费性命，菜月・昴重复了无数次的「死亡回归」。

而且，次数不是两三次这么简单。

光是自己知道的，就有十次以上的「死亡」袭击菜月・昴。

没有一次是轻松的死法。

没有一次是不伴随丧失感的结束。

没有一次是觉得这样就好而放弃生命的最后。

没有一次，菜月・昴想过要放弃生命。

即使如此，菜月・昴还是失去性命，持续「死亡回归」。

不讲理、不合理、绝望，夺走了菜月・昴的性命。但是，不管是哪一次的不讲理、不合理、绝望，只要想回避就不是办不到。

然而，为什么菜月・昴就是无法回避「死亡」呢？

那是因为——

「——因为很温柔。」

因为不希望失去任何人。

因为祈祷着，不想失去任何人。

因为讨厌，不想让任何人消失。

因为菜月・昴，无法认为有任何人死了也无所谓。

所以，菜月・昴才会失去性命，持续「死亡回归」。

所有的障碍、恶意、敌人、魔兽、大罪司教，都阻挡在性命之前。那些事物一次又一次地杀害菜月・昴，给予「死亡」，粉碎灵魂。

但是，我知道——我都知道。

确实有许多敌人、难以跨越的障碍、无法避免的灾祸，无情地夺走菜月・昴的性命。那是事实，无庸置疑。

但是，我知道。比任何人都深切地感受到。

比起敌人、灾祸、不讲理。

比起命运这种无形的恶意，杀死菜月・昴的——

——不是别的，正是持续依赖菜月・昴温柔的某人。

2

『我觉得，你不用那么钻牛角尖啦。』

「……就算昴那样说，我也完全无法释怀。」

在奔驰的龙车驾驶台上，佩特拉握着缰绳，瞥了一眼在自己身旁撑着脸颊的「菜月・昴」，然后忧愁地叹气。

现在在佩特拉身旁的「昴」不是真正的昴。

要说的话，是佩特拉的脑袋擅自让她看到的幻想——想象中的昴。证据就是他有点半透明，而且跟佩特拉记忆中的最新昴相比，感觉他的脸庞还留有稚气。

大概是因为佩特拉体验的「死者之书」，是距今一年半前的过去——佩特拉刚成为女仆，那段惊涛骇浪的几天。

「我跟昴都发生了很多事……」

想到在那之后流逝的时间，不管好坏，彼此当然都有成长。

单纯就身高和头发长度来说，佩特拉也有所成长，身为女仆、身为女性，她自负有显著的进步。另一方面，昴也跟碧翠丝感情融洽，跟奥托和加菲尔吵吵闹闹，然后跟爱蜜莉雅两人三脚地描绘出成长曲线，逐渐实现凛然精悍的男性形象。

因此，当时的『昴』看起来比现在要稍微年幼一些也是没办法的事。

——但是，即便如此也很帅气。

就算比现在要缺少男性气概和精悍，但可爱和讨人喜欢也是犯规的吧。

「不行不行……现在不是想这些的时候吧，我」

佩特拉用手扶着额头，缓缓地摇着头，责备着自己的内心。

没问题，能够好好地自制。毕竟，佩特拉像这样在脑海中想象着昴，让他说出自己想听的话，摆出自己喜欢的姿势，这也不是第一次了。

恋爱的绘画故事和恋爱的诗歌，想象着各种各样的场景，把自己和昴作为登场人物配置在其中，脸和胸口都变得火热，这已经是身经百战了。

把这些当作预演的话，现在眼前的想象中的昴，只是比那些更有真实感，更生动，更真实而已。

『这已经超越了想象，不是靠自制心就能解决的等级了吧？』

「没关系，这是我的心态问题。比起这个，不要偷窥我的脑海」

『别强人所难啊！就算你说不要偷窥，我可是在佩特拉的脑海里啊！？』

「————」

被瞪大眼睛的「昴」这么回话，佩特拉不禁屏息。看到她的反应，「昴」似乎反省自己说得太过火，用手指搔搔自己的脸颊。

那担心对方而变得柔和的眼神，还有处处都像昴的笨拙反应，让佩特拉重新觉得他很可爱。

——菜月・昴的「死者之书」，侵蚀了佩特拉・雷蒂的「心」。

佩特拉如此分析发生在自己身上的事。

原本是「死者之书」爱读者的艾莎・卡德纳，曾说过阅读这本书会对精神造成很大的负担，而这也为佩特拉带来超乎觉悟的冲击。

不过，佩特拉从昴的「死者之书」品尝到的冲击，有可能跟艾莎所畏惧的完全是两回事。

「……『死亡回归』，还有大瀑布的另一头。」

菜月・昴所背负的，远远超出佩特拉的想象。

昴离开故乡，独自一人是抱着怎样的心情与佩特拉他们相遇，是抱着怎样的心情拯救佩特拉他们，是抱着怎样的觉悟为佩特拉他们而战，这一切——不，佩特拉所知道的，只不过是极少的一部分。

因为，背负着如此悲剧命运的昴，在佩特拉所读的「死者之书」的记录之后，竟然一次都没有使用过那个权能，这实在是难以置信。

昴在那之后，一定也无数次地体验过灵魂被剥离，心灵被撕扯，生命被践踏的感觉，忍耐，忍耐，忍耐，直到今天。

「————」

艾莎所担心的，无法挽回的心灵瑕疵确实被刻上了。

大概，恐怕，不用说，自己的心已经受到了重创，精神的平衡已经崩溃得无影无踪，处于危险的状态，佩特拉俯瞰着自己这么想。

明明死了却没死的心上人。和那个幻想中的心上人交谈，他的言语让自己在这种情况下也能一喜一忧。这已经完全是一种心病了。

「但是，没关系。」

恋爱是盲目的，爱是热病。佩特拉・雷蒂被爱意侵蚀，活到了今天。

只要知道自己是异常的，就能控制住自己——佩特拉不会这么想。就像不管主张自己有多强的判断力，都不能在喝了酒之后开车一样。

佩特拉和昴都没有驾照，也没有酒后驾车的记忆，但是一样。

「车，酒后驾车，红灯绿灯，过马路……」

突然，被脑海中浮现的单词牵引，就像塞在衣柜里的不合季节的衣服满溢出来一样，知识接二连三地掉落。

那些全部都是佩特拉知道的单词，不知道的单词，在理解与不理解的界线上来来去去，是全新的老朋友。

如果不仔细地仔细地挑选，等注意到的时候，佩特拉就会穿上男装，拿着罪恶鞭走路吧。

『话说，我的主要武器是鞭子吗？太尖锐了吧？而且好像和碧翠丝很亲密，跟不上世代的差距……』

「顺带一提，老爷被大家惩罚，嘉飞先生也反省自己中二病，奥托先生没睡着，爱蜜莉雅姐姐非常努力。」

『原来如此，罗兹瓦尔是一切的幕后黑手……咦？为什么那家伙被原谅了？』

「那是昴和爱蜜莉雅姐姐的结论……」

另外，佩特拉现在还是无法原谅罗兹瓦尔，虽然没有反对昴和爱蜜莉雅的处置，但也没有赞同。当然，以在帝国的行动为首，罗兹瓦尔帮了他们很多次，不过这是两回事，佩特拉打算一辈子都不原谅他。

但是，现在，有比罗兹瓦尔更无法原谅的「某人」——

『——佩特拉。』

「……就算你这么说，我也没办法。」

平静温柔的音色，认真的眼神，要逃离「昴」的组合技，也就是强行让人忘记呼吸和心脏跳动，只能像孩子一样别过眼。

佩特拉无视自己内心深处，从持续跳动的不知羞耻的心脏发出的诉求，将意识朝向正面，朝向看起来无边无际的沙海。

「——」

——现在，佩特拉她们的龙车离开了普雷阿迪斯监视塔，为了横穿奥古利亚沙丘而笔直地暴走着。

在这片沙海的彼方，有一个必须追上的背影。

对方使用了「神龙」的翅膀，以比拥有「除风加持」的地龙还要快的机动力，一口气飞越了沙海。想要追上他绝非易事。

而且，佩特拉她们不得不赶路的理由，还有其他。

『——「嫉妒魔女」。』

和陷入沉思的佩特拉共享意识的「昴」，说出了赶路的理由。

不顾一切地让龙车行驶了几个小时——尽管已经和普雷阿迪斯监视塔拉开了相当的距离，但那股压力依然没有放过佩特拉她们。

那是为了给阅读了《死者之书》，踏入禁忌领域的佩特拉施以惩罚，而不断向她伸出手的，本应被封印在祠堂中的可怕的「魔女」。那片侵蚀、破坏世界的黑影大海啸，现在被仅仅一名英雄所阻挡。

——「剑圣」莱因哈鲁特・范・阿斯特雷亚。

他孤军奋战，将「嫉妒魔女」的暴威压制在塔的另一侧，以一线之隔防止世界崩坏，维持着抗衡。但是，现在也依然有仿佛要天翻地覆的轰鸣和激震，以及远雷般的闪光断断续续地发生，宛如默示录的号角被吹响，不分昼夜地持续鸣响。

这种抗衡究竟能持续到什么时候，佩特拉和谁都不知道。

要说知道的，就只有一件事——

『莱因哈鲁特要是被干掉的话，一切就都完了。』

「嗯。莱因哈鲁特……先生要是不在了，『魔女』就会追上我。在那之前，无法预测会出现多少损害。」

『毕竟她看起来不像是会规规矩矩地让路给周围的人的类型。』

对于「昴」的玩笑话，佩特拉想象了在满员电车里把座位让给老人的亲切的「嫉妒魔女」，但实在笑不出来。

实际上，如果要将损害抑制到最小限度的话，不管莱因哈鲁特的胜败如何，佩特拉都应该留在普雷阿迪斯监视塔，甘愿接受「魔女」的封口。

但是，佩特拉要是有一瞬间考虑了那种事的话——

『——那绝对不行。死也要拒绝。』

「——」

被『昴』当面这么说，佩特拉的反驳被封住了。

从以前开始，她就有自觉昴很重视自己。当然，还有爱蜜莉雅和碧翠丝，雷姆也是。和她们相比，自己并没有自大到认为自己有特别待遇，但还是可以确信——自己被放在菜月・昴心中，用来放重要物品的架子上。

但是，直到今天她才知道，这个开玩笑挺起胸膛的昴所说的「死也要」，究竟有多么沉重。

菜月・昴真的是「死也要」守护重要之物的人。

「——嗯，我很清楚。我也不想死……阿尔先生有准备什么可以阻止『魔女』的手段吧？」

『嗯，那家伙也不是笨蛋，不知道世界会被破坏到什么地步。在那之前，他一定会准备好对策。』

「嗯，一定会。」

『绝对会。』

『昴』握紧拳头，用力断言，佩特拉也点头回应。

追上离开塔的阿尔，让他坦白阻止『魔女』的策略。虽然整理必要的步骤后让人感到头晕目眩，但『昴』的话是多么可靠啊——但是很悲哀的是，和刚才一样的话不仅适用于『昴』，也适用于佩特拉。

和佩特拉共享意识的『昴』，佩特拉的想法和不安都暴露无遗。

然后，和『昴』共享意识的佩特拉，『昴』的想法也暴露无遗。

「……如果，阿尔先生想要终结世界的话。」

佩特拉和『昴』相互确认的绝对，就无法成立了。

最坏的情况，阿尔可能没有准备阻止『嫉妒魔女』的方法，任由世界毁灭，打算带着自己死去的心一起上路。

阿尔失去了敬爱的主人普莉希拉・跋利耶尔——或者不是敬爱，而是抱有更浓烈的爱情的对象，就算憎恨世界也不奇怪。

但是，无法不抱有一缕希望也是事实。

「我和梅莉，还有格菲她们，大家都活着。」

阿尔甚至得到了『神龙』波克肯尼卡，他有权利决定塔内佩特拉等人的生杀予夺。而他没有夺走她们的性命，行使了不夺走她们性命的权利。

相信这是残留在阿尔心中的一丝希望，是想太多了吗？

「……或许不是想太多，但这样不像我。」

『唔。』

佩特拉用手指抵着嘴唇喃喃自语，旁边的『昴』刻意耸肩。瞥了他一眼，『昴』露出笨拙的谄媚笑容朝她挥手，佩特拉眯起眼睛。

不知道『昴』对佩特拉现在的想法有多少影响。

『死者之书』的影响，对佩特拉来说，不可能只有看到想象中的昴这种额外效果。

「得小心才行……」

佩特拉很喜欢昴，但并不想成为昴。而且，也不该成为像昴那样，对每个人都很温柔的人。

佩特拉憧憬温柔的人，也一直想变得温柔，但像昴和爱蜜莉娅这样的人，只要有昴和爱蜜莉娅在就好了。

佩特拉想成为不会把温柔的人们的温柔当做理所当然的人。

为此，她不能太过融入菜月・昴的心情。

「——佩特拉，差不多该换人了」

正当她这么想的时候，龙车的小窗被打开，后脑勺传来了声音。

说话的人是在客车里休息的梅莉。对于提出换班的她，佩特拉摇了摇头。

「我没事，梅莉你去休息吧。你不仅把我睡着时的我搬到了这里，还帮我赶走了魔兽」

「我可没像搬着牙哥哥和老师小姐的芙拉姆那么辛苦。而且，因为“剑圣”小姐和“魔女”的争吵，魔兽们似乎也没空管我们」

梅莉耸了耸肩，她的表情上刻着浓厚的疲劳感，一眼就能看出她在客车里休息时也没能放松心情。实际上，在能感受到远处“魔女”存在的状况下，她一直处于被蛇盯上的青蛙状态，能平静地休息才奇怪。

而且梅莉的责任感意外地强，所以她应该更难放松。

「芙拉姆呢？还在睡吗？」

「是啊，还没醒呢。不过我想仰赖小芙拉姆的加护，所以这么做是对的哦。」

『这孩子……梅莉待在这里的违和感也超强烈啊……』

梅莉忧郁的回答，和「昴」对她的存在感到战栗的感想重叠。佩特拉不理会后者的反应，意识起话题中提到的芙拉姆的存在，以及她的加护。

芙拉姆拥有的「念话的加护」，是每天能和双胞胎姐妹通话一次的加护。虽然只能单向通话，但这种和距离无关的通讯手段，目前处于就算拿任何东西交换都不足惜的重要地位。

而加护的条件「每天一次」的判定，似乎和睡眠时间有密切关系，因此越是紧急的状况，越需要让她睡着。

只不过，芙拉姆为此采取的行动超乎佩特拉的想象。

「没想到她竟然会突然勒住自己的脖子昏过去……」

「因为在意『剑圣』小姐，所以没办法正常休息吧。不过，能因此下定决心这点，很有『剑圣』小姐相关人士的感觉呢。明明比我或佩特拉还小，却是个和普通相去甚远的女孩呢。」

「我想她才不想被梅莉这么说哦。」

『你没资格说啦。』

佩特拉和「昴」的吐槽重叠，让梅莉不满地嘟起嘴。

虽然她只听得见佩特拉的声音，但像这样刻意进行不合时宜的日常对话，是为了让彼此忽视「魔女」带来的压力。

或许该归功于这样甩开不安，专心一志地持续奔驰吧。

「——！」

突然响起的尖锐嘶鸣声，是比佩特拉、梅莉和芙兰姆都更拼命持续出力的存在——帕特拉修发出的。

鉴于在普雷阿迪斯监视塔发生的事，和佩特拉她们共享紧急性的帕特拉修发出的嘶鸣声，代表目的地——沙海的尽头已近在眼前。

接着便看见离沙海最近的城镇，以及米露拉的身影。

「佩特拉！」

「嗯，我知道！」

回应梅莉的呼唤，佩特拉握紧缰绳，身体前倾。

只有一瞬间在意后方的帕特拉修已经将意识转回前方，开始为至今为止不眠不休的归途进行最后冲刺。

『我爱你，帕特拉修。』

没有实体的想象昴，将无法传达的感谢和爱的言灵赠予帕特拉修。

看着无法触碰的手抚摸地龙的脖子，佩特拉小小的脑袋里，展开了抵达米卢拉后需要的路线图。

在路线图的终点，作为最终目的的当然是阻止阿尔背叛菜月・昴的行动——不，是在那之后。

为了到达那里——

「——」

龙车猛然穿过城镇入口的门，冲进米卢拉。佩特拉以此判断自己已经穿过奥古利亚沙丘，大大地张开嘴巴。

不管要做什么，佩特拉她们都必须先借助某人的力量——他无法进入奥古利亚沙丘，所以在这里目送佩特拉她们。

所以反过来说——

「——既然回来了就帮个忙吧！你有听到吧，克林德哥哥！」

没错，为了寻求能将拉开的距离归零的王牌，佩特拉高声呼喊。

3

「——呃。」

瞥见视野角落的小小身影，菲鲁特用力皱起眉头。

那造型、颜色、光泽都让人产生生理上的厌恶，虽然从懂事开始就和那群家伙在贫民窟同床共枕，却丝毫没有同伴意识和亲近感。

菲鲁特甚至为了御寒而抱着大老鼠睡觉，却连一只蝼蛄都不想当朋友。

简直就是人类天敌的可怕存在。

「真的耶，蝼蛄不管到哪都有……」

蝼蛄以脱离常轨的生命力确保生存区域。虽然大多在不卫生的地方看到，但那并非绝对条件。

实际上，菲鲁特这时候在视野角落看到蝼蛄的地方，是管理完善、维护周到的建筑物中——王都露格尼卡的贵族街宅邸。

奢华而奢侈，放置着许多菲鲁特无法理解价值的绘画和装饰品的这个地方，即使失去了宅邸的主人，也依然保持着那份华美。

「喂，你的那个线，不是能伸到很远的地方吗。不能用那个把索达驱除掉吗？」

「哈～那个啊，菲鲁特大人。我使用的钢丝术，是百年单位内都没有使用者的超稀有技能哦？那个技能加上『咒具师』格鲁比・加姆雷特制作的钢丝专用戒指，才能发挥八重的厉害女忍者本领。抓住这样的我，居然要我驱除索达虫吗？」

「太长了，我听不进去。结果，到底是什么？」

「我不想让爱用的线被脏东西弄脏，所以不要～」

八重・天膳这么说着，把戴着戒指的双手藏在背后，把脸转过去。菲鲁特「知道了知道了」，漫不经心地回答。她瞥了一眼刚才的影子，右，左，好像跟丢了。这让她感到不快。

「就算我看不见，也不代表从这世上消失……别说消失，那些家伙偶尔还会朝人的脸飞过来。」

「我懂。要是那样，就只能做好死亡的觉悟了～」

「虽然想说不会啦，但要做好觉悟。」

心境上与其说是觉悟，不如说是放弃或绝望比较贴切。

不管怎样，看到索达虫的影子，菲鲁特和八重意外地产生共识，同时重新眺望宅邸——王都的跋利耶尔别邸的内部装潢。

露格尼卡贵族有一部分的人在王都以外的地方生活，会在王都的贵族街拥有滞留用的别邸。菲鲁特第一次被莱因哈鲁特绑架监禁的阿斯特雷亚宅邸也是如此，这栋宅邸——普莉希拉・跋利耶尔建造的宅邸，也是基于相同目的建造的。

「那位公主大人，就算自己不在家，应该也会要求好好整理，结果却有索达虫在乱窜，真是不像样。还是说，主人一死，女仆就立刻失去干劲了？」

「哦，就算是挑衅，最好还是别在阿尔大人面前说那种话哦～？听起来很像坏心眼的人，而且说夫人坏话，我也不太好受～？」

「哦？你是叫我别惹火头盔小子？」

「不不不，阿尔大人不会生气，但一定会受伤。我不太喜欢那样。」

八重稍微压低声音，最后歪头。顿时，菲鲁特的脖子感到些许紧张，用生命感受到看不见的丝线。

原本犹豫是否要对索达虫使用的钢丝，又缠绕在菲鲁特的脖子上。

「就算危害我，头盔小子也不会生气吧？」

「或许吧。不过，让菲鲁特大人畅所欲言，对身为排除万难、万能女仆的我来说，也是个问题。」

「『主』这个称呼真奇怪。你和头盔小子的关系不是主从吧？不过，我知道从安全范围高高在上地指手画脚很逊啦。」

边回答边举起双手，菲鲁特向八重表示没有抵抗的意思。看着她这副模样，八重耸肩收回钢丝。

即使如此，只要菲鲁特有任何可疑举动，八重就会毫不留情地射出钢丝，砍断一根手指，必要的话砍断一只手或一只脚来表明自己的意思——从速度和精准度来看，挑衅她是有价值的。

「虽然早就知道了，但不是我能应付的对手……」

现状，跋利耶尔别馆只有菲鲁特和八重两人。

如果菲鲁特能瞒过八重，或是独自打倒八重，就能逃离被囚禁的公主状态，牵制菲鲁特阵营的行动。

「真是的，被当成公主对待，别开玩笑了。」

客观审视自己的立场，菲鲁特吐舌抱怨。

——现在，菲鲁特处于被头盔男阿尔德巴兰一伙囚禁的立场。

到目前为止，菲鲁特阵营和阿尔德巴兰一伙的战绩是两战两败——阿尔德巴兰漂亮地躲过莱因哈鲁特和罗姆爷，菲鲁特手牌中最强的两张。

不仅如此，连菲鲁特都被抓住，可以说是完败。

但是，菲鲁特的个性可没有可爱到会因为连战连败而露出肚子。就像刚刚确认八重的本领一样，只要一有机会就会睁大眼睛。

「不服输这点不愧是王选候补者，随从精神的高贵性令人着迷，不过请不要想些乱来的事哦～？像粗暴的人或是亨克尔大人，就算用线绑起来或是砍飞，我也不会心痛，但我可不喜欢对可爱的女性这么做。」

「是哦，那你也记住这点。我也不喜欢可爱、可怜、很适合你之类的话，被说的次数我可记得一清二楚。」

「咿～好可怕。顺便问一下，数这些是要做什么？」

「等到可以反击的时候，我会用那个次数踢你的屁股。」

顺带一提，菲鲁特已经决定要踢八重的屁股三次。阿尔德巴兰和「神龙」、亨克尔也都有各自的次数。

菲鲁特会确实清算人情债，恩情和怨恨没有区别。

「龙的，更何况是『神龙』的屁股，很少有机会可以踢吧。这么一想，就算被当成人质也挺好笑的吧？」

「真坚强呢～精神力太强，连八重都吓到了。就算不是这样，八重也怕被搭讪，所以不想让菲鲁特大人和波尔大人接近。」

「所以说，让莱因哈鲁特的老爸照顾『神龙』，就我来说是相当不好的兴趣。」

「亨克尔大人想要『龙血』想要到两只手都伸出来了。希望他不要急着下手，不小心砍到波尔大人。」

八重手指抵着嘴唇，露出恶作剧的微笑，但内容一点都不可爱。

实际上，对八重来说，就算刚刚的想象成真——也就是，鲁莽行事的亨克尔被「神龙」杀死，也不会有什么问题。包含对算是同伴的亨克尔的态度，果然是坏心眼的分配。

当然，「神龙」太过显眼，不能让他靠近王都，既然不想让他和迷惑人心的菲鲁特待在一起，那分配不均也是无可奈何。

「菲鲁特大人不是倾国美女，而是倾龙美少女。」

「踢屁股的次数增加了哦……说真的，那个老爸想要的『龙血』，是从那个呆头呆脑的『神龙』身上采集的吗？」

「谁知道？啊～不过就算不行，到时候回收保管在城堡某处的古老『龙血』，阿尔大人也打算遵守约定。因此，沉睡的亨克尔大人的夫人应该会醒来。菲鲁特大人无法接受那个做法吧？」

「是啊，老实说，我不喜欢那个做法。」

关于这点，菲鲁特也直接对找借口的亨克尔说。

菲鲁特不喜欢那个做法。但是，当事人思考、行动、决定的事，被局外人不分青红皂白地否定，这样也不合理。

所以菲鲁特就算想让莱因哈鲁特的母亲醒来，也想走跟亨克尔不同的路，抵达山顶。

「——？干嘛啦。」

突然，懒散地坐在会客室沙发上的菲鲁特，察觉到八重频频打量自己的视线而皱眉。

看到菲鲁特的反应，八重摇头说「没有啦～」。

「只是觉得意外。没想到菲鲁特大人竟然想让亨克尔大人的夫人……也就是『剑圣』大人的母亲大人醒来。」

「……那家伙啊，在我们所有人一起吃饭的时候，都会坐在我旁边哦。」

「——？」

乍听之下毫无关联的这番话，让八重露出讶异的表情。菲鲁特不理会八重的反应，继续说下去。

「芙拉姆和格拉西丝……是宅邸工作的双胞胎女仆，她们两人准备完餐点后，会通知所有人。」

在菲鲁特阵营用餐时，除了坐在上座的菲鲁特外，其他人都是听到芙拉姆她们的呼唤后，先到的人先坐。

而坐在上座的菲鲁特旁边，几乎都是莱因哈鲁特。

然后——

「吃饭的时候，那家伙的脸是我看得最清楚的。那张脸好看一点，饭也会变得更好吃啊。」

「……美少女订正。菲鲁特大人是帅哥呢～」

「虽然不懂你在说什么，但我要增加踢你屁股的次数。」

「咦～为什么啊～！」

八重不满地嘟起嘴，菲鲁特别过脸，没有继续回答。

虽然习惯当人质这种事很不名誉，但在这种状态下保持精神从容的诀窍，就是不要把所有事都滔滔不绝地说出来。

就这样，当菲鲁特让钓到的鱼焦急时——

「好啦好啦，如果惹你不高兴的话，那我道歉。总之，请用。」

八重边说边递出银色托盘，上面放着夹有烤面包的轻食三明治，菲鲁特的肚子咕噜叫。

八重听到声音轻笑。

「哎呀呀～？连这种地方都有饿虫吗？」

「那些家伙到处都有，连我的肚子里也有……喂，别让我想象恶心的画面啦，快点给我。」

菲鲁特瞪着语带调侃的八重，从她手中抢过银色托盘。咬了一口飘着微温香气的三明治，味道不会太浓也不会太淡，感觉刚刚好。八重和菲鲁特四目相交，露出笑容竖起拇指。

「怎么样，三明治。这可是八重唯一擅长的料理哦～」

「好吃……不过，唯一擅长的话就另当别论了。你姑且是女仆吧？还是说女仆是骗人的，其实是杀手之类的？」

「嗯～虽然暗杀也是忍者的主要工作之一，但我真的是女仆哦。只是比起做菜，我更擅长收拾而已。啊，擅长的料理只有夹烧是骗人的。我也擅长重包。」

「结果不都是在面包里夹料吗？」

顺带一提，菲鲁特对重包的印象是夹的料以蔬菜为主。实际上，她并不清楚夹烧和重包的细微差异。

不管怎样，被抓住的人质也有饭吃，这让她安心了。看样子，不必怀疑阿尔德巴兰的话都是谎言。

不过，这样一来，不在场的阿尔德巴兰的行动就成问题了。

和菲鲁特等人分头行动的阿尔德巴兰，他的目的地是——

「——那个头盔混蛋，真的打算带大罪司教出去吗？」

如果要谈相信，那项宣言——解放被囚禁在王都监狱塔的「暴食」大罪司教，也得相信。

现在，露格尼卡王国正拘禁着「愤怒」和「暴食」两名大罪司教。

菲鲁特也在普利斯提拉直接和大罪司教接触，深深感受到他们的威胁性和非人道。这世上竟然有这种无可救药的家伙。

「我在普利斯提拉和『暴食』……被抓住的家伙的哥哥或弟弟，还有他的妹妹见过面。而且移送『愤怒』时也和莱因哈鲁特一起行动。由我来说的话，那个头盔混蛋根本疯了。」

「是那样没错～不管什么事，大业都不是在正常情况下能成就的。阿尔大人到目前为止所做的事，不都是脱离常轨的作为吗？」

「不是数量的问题，而是跨越的次元不同吧。而且利用『魔女』是为了绊住莱因哈鲁特，这还可以理解。可是大罪司教呢？特地把那种人带出来，是想让他们做什么？」

「当然，那也是为了达成阿尔大人的目的吧～」

「具体的事连我也不知道。」

八重双手背在身后，微笑不回答菲鲁特的话。

不过，答案在预料之中。虽然不知道八重服从阿尔德巴兰的真正用意，但不管发生多么冲击的事，她都强烈地感受到八重不打算和阿尔德巴兰分道扬镳的意志和执着。

所以，接下来不是等待答案，而是由菲鲁特来探询。

「……『暴食』那家伙，会没礼貌地乱吃人的『名字』和『记忆』。」

就像『记忆』被吃掉的库珥修，还有『名字』被吃掉、据说是安娜塔西亚骑士的尤里乌斯。还有，听说在爱蜜莉雅阵营，正在寻找让昴觉醒的方法的少女——说不定，最后的少女和菲鲁特他们所知道的「睡美人」并非毫无关系。

不管怎样——

「——有想让他吃的东西，除此之外，不可能有其他方法把『暴食』的混账叫出来。」

即使被囚禁、被强迫不自由，菲鲁特的灵魂依旧拒绝屈服。

那一定是和莱因哈鲁特一样，将阿尔德巴兰逼到绝境的可靠罗姆爷教她的，菲鲁特的人生哲学——「坚强地活下去」。

「啊咕。」

豪迈地用夹烧填饱肚子，菲鲁特努力实现人生哲学。

只要不放弃思考，不停下脚步，就会有伸手触及的余地。为了那个瞬间，她用舌头舔掉沾在嘴角的夹烧酱汁。

在她身旁——

「……哇，真的是蟑螂。才请管理员休假几天，真～讨厌～」

八重似乎看到和菲鲁特方才看到的同一只，又或者是不同只，她厌恶地皱眉，吐露这样的牢骚。

4

——那里是狭窄、昏暗、令人窒息的地方。

「——」

独居房这样的形容都还太温和，感觉不出将人关在这里头还能活下去的意图。不过，用残酷或冷酷来概括的话就太暴力了。

毕竟被关在这里的，是在全世界引发无数悲剧的稀世亵渎者。恶名昭彰的存在，被逮捕的方式当然也和一般人大不相同。

连进食、排泄、呼吸、心跳都不需要的「黑色棺材」，是连这世上最令人畏惧的「魔女」都能封印，将存在从世界隔离的无情牢笼。

因此，被关在牢笼里的亵渎者，当然不会被赋予尊重生命的准备。

然后——

「——抱歉啊。我好像也累积了不少怨气，没能控制好力道。」

在冰冷的地板上踩出脚步声，背靠着狭窄房间的墙壁。头盔的后脑勺撞上墙壁，铁与石壁碰撞的声音，让冰冷的石室空气刺耳地摇晃。

那个试图调整微乱呼吸的男人——阿尔德巴兰的脚下，有个无力地趴倒在地，奄奄一息的人影。

那就是从王国获得这个类似单人牢房的石室的亵渎者。

方才被阿尔德巴兰完封，沦落到趴在地上舔地板的难堪败犬——魔女教大罪司教「暴食」负责人，罗伊・阿尔法德本人。

「————」

深吸一口气，用力吐出。

阿尔德巴兰用勉强的深呼吸调整紊乱的心肺机能，环视实际上只过了一分钟，却变得相当凌乱的石室，耸了耸肩。

墙壁龟裂，地板碎裂，这个疏于维护的狭窄房间，被破坏得连立足之地都没有。虽然只有像正常咖啡店的厕所那么大，但真亏他们能在这里大打出手。

不过，这并不是他们想打才打起来的。

「……我明明才刚说过，只要乖乖跟我走就不会取你性命。就算要造反，一般也会再等一下机会吧。」

「——哈哈，大叔，你这话真有趣。」

听到阿尔德巴兰语带叹息的话语，呈大字形躺在地上的罗伊不快地嗤笑。

罗伊维持趴着的姿势，以锐利的眼神看向墙边的阿尔德巴兰，用长长的舌头下流地舔了舔嘴唇。

「你的意思是，要总是饥渴到不行的我们学会忍耐吗？那根本就是虐待了吧。」

「很不巧，我没有义务养育你这种坏小孩。虽然听说昭和时代除了家人以外，邻居也会帮忙管教，但这里是露格尼卡，年号也不是昭和……不过，都把你打成这样了，说是虐待的话我也无法否定。」

阿尔德巴兰用手敲响头盔的金属部分，罗伊心情很好地「哈哈」笑。

被彻底折断双手双脚还接受管教，却还能摆出这种态度，真的是个恶心的小鬼。至少在体罚盛行的昭和时代，也不会允许这种程度的管教。

话虽如此，罗伊・阿尔法德在是恶心小鬼之前更是大罪司教，这点程度的风险回避还在容许范围内。

「虽然一开始就不觉得事情会顺利进行。」

阿尔德巴兰这么说完，将计数结束在六千二百二十二。

已经不需要说明的数字，是阿尔德巴兰管教反抗的罗伊・阿尔法德所需的挑战次数。要是连折断的骨头和牙齿数量都算进去，数字会轻松变成好几倍吧。管教坏小孩就是这么费工夫。

「没想到，会陷入跟莱因哈鲁特类似的试误学习……」

罗伊・阿尔法德是名副其实的「恶食」，其「暴食」权能是将吃掉的对手的技术和性能重现的「蚀」——因此，罗伊等同于在自己体内储备了无数的战士，会立刻舍弃不管用的战法，马上拿出新的战法。

罗伊是战术、战法、战技和魔技的百货公司，能够自由自在地出招，有时还会将不管用的A战法和B战法组合起来，到达连过去被吃掉的被害者都没能抵达的招式极致，是践踏原创者钻研成果的亵渎者。

而那种亵渎的战斗方式，跟配合对手的战术和状况，长出适当的加护来即时应对的莱因哈鲁特有相似之处。

幸好，阿尔德巴兰有跟莱因哈鲁特战斗的十三万以上的经验值，因此面对同样超乎规格的罗伊，也成功在四位数的挑战中取胜。

「话虽如此，你是在塔战之后被抓住的。之后都没好好治疗的话，那也算是奋战过了。」

「咦？大叔，你该不会是在安慰我们吧？我们还是第一次体验到，自己的所作所为从头到尾都被完封。不过，如果真的想安慰我们，最好的方法就是……」

「暴饮暴食会影响隔天。我可是逐渐难以消化油腻食物的大叔世代。光是脑袋里浮现成语，胃袋就缩起来了。」

「哈哈，真冷淡。」

罗伊用满是尖牙的嘴巴嗤笑，用骨碌碌的眼睛看着阿尔德巴兰。

视线的色彩是兴趣、食欲、好奇心、食欲、嗜虐心和食欲，总之是让阿尔德巴兰背脊发凉的全餐。超越手脚被折断的痛楚的饥饿感，让罗伊变成这样，但那实在是扭曲至极的存在方式。

阿尔德巴兰不想同情那种存在方式。

因为和过去为世界带来混沌与破灭的「魔女」们一样，被魔女因子选中的大罪主教也是与生俱来就偏离正常轨道的可恨异端。

「——啧。」

顺着话题想起「魔女」，感到心中有疙瘩的阿尔德巴兰咂嘴。

「魔女」和大罪主教是同流合污的——那么自己又如何呢？和那些旁若无人地占据世界核心的异物们一样，还是比他们更严重的BUG。

「……想要我说明状况吗？」

「嘿，要说明吗？什么什么，折断手脚之后同情起小孩子了？不过也是呢，如果是正常的大人，不可能会若无其事地折断这么幼小的孩子的手脚。不过呢，外表看起来这样却戴着头盔的大叔，是不是正常的大人还有讨论的余地。」

「真能说啊……这里是离你被抓住的普雷阿迪斯监视塔很远的露格尼卡王都。你的另一半——」

「——啊，死了吧？」

「————」

「这点小事，我们也很清楚。家人之间的联系，比大叔想的还要强韧……抱歉抱歉，骗你的。只是因为感受不到莱伊的魔女因子才这么想。而且……」

「而且？」

「虽然从外面完全看不出来，但被绑住的人多少可以感觉到外面。明明被封印得那么紧，大家却都吓得要死，真没出息。」

罗伊露出嗜虐的笑容，舔着舌头，若无其事地说出另一半的死。那轻薄的态度让阿尔德巴兰不禁感到扫兴。

虽然他能若无其事地接受相当于半身的莱伊・巴登凯托斯的死，但被那个「黑色棺材」——奥尔・纱幕施加了同系统的封印，却还能保有自我，感受外面的世界，这个证言让阿尔德巴兰大吃一惊。

罗伊没有理会阿尔德巴兰的惊讶，「嘿咻」一声翻过身，仰躺着将阿尔德巴兰倒映在视野中。

「啊，呼吸好困难。这样好多了……所以？大叔，我记得在我们的『记忆』中，你是王选的相关人士之一吧。竟然会像这样解放我们这些大罪主教，重要的公主大人会对你有不好的评价——」

「你这家伙，不只战斗方式，连思考方式都吸收了各种各样的东西吧？如果不想被当成只是凑齐了道具却什么都做不到的无能，就在我问你之前先思考一下。」

「哇，踩到地雷了。我是不是太多嘴了？没关系啦，没关系，没关系，没关系啦，没关系的，没关系啦！我不会再问下去了。你是不是因为宝贝的公主大人死了，所以自暴自弃了……呃！」

「是哦。你愿意这样就太好了。感谢你的体贴。」

罗伊脸上浮现邪恶的笑容，但骨折的肩膀被用力一踩，表情立刻扭曲。阿尔德巴兰用脚跟仔细地踩踏折断的骨头，然后把脚放下。

对方是大罪主教。虽然早就知道，但就事情无法按照计划进行的观点来说，可以说是最难缠的对手。虽然早就料到封印一解开就会被反咬一口，但这种料中了当然也不会高兴。

大罪主教这种人，要不是计划需要，真想直接把他们关进棺材，丢进大瀑布里。

不过——

「……！竟然这么需要我们。真是难为你了，大叔。」

「你这小子真会耍嘴皮子。真想叫你爸妈教你讲话客气点。」

「生父？养父？前者的话，生下我们的时候就带着妹妹一起死了，后者的话肯定跟大叔你合不来吧。」

「不管哪个，我都知道你不是什么好东西——没办法了。」

虽然奇迹般地能够对话，但问答之间没有任何收获。空虚的多嘴是大罪主教的特征，这点「暴食」也名副其实。

涌上心头的只有不快感与厌恶感，别说待起来不舒服，连活在世上都感到难受。

「————」

罗伊仰躺着，处于砧板上的鱼状态。阿尔德巴兰走到他身旁，蹲下。

罗伊与俯视自己的阿尔德巴兰隔着头盔四目相对，他上下颠倒，折断的骨头被踩踏的痛楚也只有一下子，他好奇地转动眼睛。

「怎么了怎么了？大叔，接下来要对我做什么？要拷问不听话的小孩吗？可是啊，我们早就习惯这种痛了。」

「放心吧。我也跟你一样，不相信用痛楚就能让对方听话。如果心情超越痛楚，就没办法让对方屈服。所以——」

「所以？」

「我束缚你的不是痛楚，也不是感情——是约定。」

阿尔德巴兰一边说，一边将拇指伸进头盔的下颚部分，咬破指尖。他将随着尖锐的痛楚浮现的血滴沾在手指上，然后将手指指向罗伊。

然后，他将沾着血的指尖按在倒卧在地的亵渎者的肌肤上。

「别做无谓的抵抗。虽然我被训练到就算闭着眼睛也能画……但这是第一次实际测试效果。」

「竟然用血在小孩子的肌肤上涂鸦，这种恶趣味连我们大罪主教都自叹不如。不惜做出这种反常的举动，到底想让我们做什么？破坏国家吗？」

「我没那个打算，而且那种事只要我想做就能自己做。我之所以特地放了你这个可恨的小鬼，是因为有件事只有你才能做。」

「只有我们才能做？」

罗伊一边被沾着血的手指抚摸身体，一边忍耐着痒意，露出牙齿嗤笑。

那下流的眼神、语气与散发的气息，都在催促阿尔德巴兰说出没有说出口的部分。

虽然顺着对方的意很令人不爽，但阿尔德巴兰还是回答了。

阿尔德巴兰释放罗伊・阿尔法德的理由是——

「——我有个想让你用权能吞噬的对象。你可别拒绝哦。」

「嗯？也是啦。毕竟都释放我们了，也只有这个理由了吧。」

罗伊躺在地上歪着头，听到阿尔德巴兰的要求后，他歪着脸笑了。

阿尔德巴兰不知道那笑容是肯定还是否定。而且，不管答案是什么，都与罗伊的意志无关。

为了让罗伊接受，阿尔德巴兰将手段记在罗伊・阿尔法德的肉体上，刻在灵魂里。

用阿尔德巴兰的血画出的图案是——

「——誓约的咒印。而且还是偏执到彻底的类型。这是大叔自己想出来的吗？还是从脑袋有问题的咒术师那里学来的？」

「是学来的。虽然那个人脑袋有问题，但不是咒术师。是魔法师。在这个世界上，毫无疑问是历代最厉害的魔法师。性格姑且不论。」

「誓约的条件是？」

「未经我的许可就吞噬别人的话，就燃烧灵魂而死。」

阿尔德巴兰简洁地告知，然后不看罗伊的脸，直接将他的身体扛在肩上。

『恶食』是恣意妄为、到处乱吃的亵渎者，不过身体很轻。毕竟他是潜入罗伊被关押的监狱塔，身体轻盈是再好不过。

虽然已经让所有看守都昏倒了，但回程还是谨慎为上。

「之后和八重与菲鲁特小妹妹会合——」

为了在王都行动，命令八重监视菲鲁特，在跋利耶尔别邸待命。那栋宅邸原本是莱普・跋利耶尔建造的，因为普莉希拉的干预，大幅变更了预定，才变成现在的模样。

结果到处都残留着普莉希拉喜欢的风格痕迹，虽说有其必要，但阿尔德巴兰也不想久留。

所以想尽早接走八重她们，和分头行动的「阿尔德巴兰」会合。

「话说回来，我刚刚也说过了。」

阿尔德巴兰如此心想时，被扛着的罗伊突然开口。阿尔德巴兰瞥了他一眼，手脚无力的罗伊正看着地板。

顺着他的视线看去，阿尔德巴兰皱起眉头。

那里——

「在大叔把我们拿出来之前，被那个黑色的东西固定住的时候，虽然很模糊，但我们还是能感觉到外面的情况。可是，这里完全和外面隔绝了。在那种状态下，别说会面了，别说老鼠了，连一只虫都进不来。可是啊」

「——啊？」

「居然有只蟑螂，真是稀奇啊」

罗伊粘稠的话语，和映入阿尔德巴兰视野的那只小虫子一致。

「————」

在冰冷的地板上爬行，有着令人毛骨悚然的外形的虫子，是这个世界所有人都厌恶的蟑螂。因为蟑螂到处都有，所以就算出现在监狱塔里也没什么奇怪的——阿尔德巴兰不这么认为。

「——糟了！」

内心涌起的焦躁，让阿尔德巴兰顾不上自己正扛着手脚折断的罗伊，急忙冲出单人牢房，冲出监狱塔。

必须尽快逃出去，不然阿尔德巴兰的潜入已经暴露——

「——到此为止了」

踏出监狱塔的瞬间，那个声音敲打着阿尔德巴兰的鼓膜。

与此同时，他感受到气温骤降，甚至令皮肤发麻，头盔外侧也因为与塔内的温度差而发出嘎吱嘎吱的声音。周围飘舞着白色的雪花，不合时宜的寒流到来，比起想象到农作物受害的农民，阿尔德巴兰的精神更加动摇。

那是曾经听过的银铃般的声音。

监狱塔周围是一片广阔的庭院，她踩着薄薄的积雪，飒爽地走来，银色的长发在雪景中闪耀。

那美丽的紫绀色瞳孔中，总是寄宿着温和的光芒——但是，现在并非如此。紫绀色的瞳孔中，燃烧着熊熊烈火，让人无法看错。

那毫无疑问，是她的愤怒——

「——把昴和碧翠丝还给我。」

平静而堂堂正正地表明自己的意志，那是只有某种王者才被允许的风格。

伫立在那里的她，美丽、华丽、高贵，甚至让人一瞬间产生了那样的错觉。

「————」

阿尔德巴兰吐出白色的气息，呆立在原地。站在雪上的『冰结魔女』——爱蜜莉娅，竖起形状姣好的眉毛，对阿尔德巴兰说道：

「我现在非常生气，就算对手是阿尔，我也不会手下留情。」

** 第二章 『爱蜜莉雅大怒』

1

「我现在非常生气，就算对手是阿尔也不会手下留情。」

说完，将监狱塔周边化为雪景的「冰结魔女」眼神严厉。

那双蓝紫色瞳孔里燃烧的怒火，让阿尔德巴兰的喉咙深处感到干渴。

在帝国里，他看过好几次她拼命伸长修长手脚，美丽脸蛋带着认真战斗的模样。但是，那认真的神情总是带着符合她个性的坚强与体贴，不曾被激情所占据。

所以，这是第一次。

「——」

第一次看到爱蜜莉雅的眼中只有愤怒，而且是用力瞪着某人。

更何况，那股怒气是冲着自己来的瞬间，他根本连想都没——

「……想过，这样想太自私了。」

夺取「神龙」波克肯尼卡的龙壳，为了绊住「剑圣」莱因哈鲁特而操控「嫉妒魔女」的世界之敌——在那之前，光是封印菜月・昴，就算不是世界规模，阿尔德巴兰的敌人也很多。

爱蜜莉雅是其中的代表。这场对峙，是必然的决断所付出的代价。

「咦咦咦，好奇怪哦——？大叔，你好像惹她生气了耶。你知道吗？那个大姐姐一生气就很难搞哦。」

「闭嘴。」

「哦哦，好可怕好可怕。」

被阿尔德巴兰扛在肩上，动弹不得的罗伊揶揄地嗤笑。

罗伊被抓住的经过，是在普雷阿迪斯监视塔与菜月・昴他们的战斗——爱蜜莉雅当然也在场，所以他会认识她也很正常。

在那之前，罗伊在普利斯提拉也吃了许多人的「名字」和「记忆」，就算其中有认识爱蜜莉雅的人也不奇怪。

所以现在，该重视的不是罗伊的轻佻话语——

「——哟，竟然在这种地方遇到，真是奇遇啊，小——」

为了选择最初的一句话，阿尔德巴兰煞费苦心地开口。

但是，辛苦选择的第一句话，很遗憾地没有意义。

因为——

「——」

阿尔德巴兰观察对方的态度，话才说到一半，爱蜜莉雅就往前倾，脚下的薄雪爆发，蹬地的她银发美丽地飞舞。

在白雪妆点的视野中，飞舞的银发闪耀，紧接着——

「嘿呀！！」

——毫不留情，冰之手甲的拳头击穿了阿尔德巴兰的心窝。

2

——时间，稍微回溯到心窝被击中之前。

「昴他们……！？」

「是啊，我这边的人联络我，说塔里的人全都被干掉了。」

没错，自水门都市普利斯提拉以来的重逢，菲鲁特却没时间叙旧，而是告知爱蜜莉雅惊人的消息。

地点在王都贵族街的王侯馆——这是王国所有的宅邸，只有王室血亲和受命的高阶贵族才能住宿，是滞留王都的爱蜜莉雅的临时住所。

频繁造访王都的贵族，大多在贵族街有别邸，但能用魔法当天来回自己宅邸的罗兹瓦尔，在王都并没有这样的宅邸，因此王选候补者之一的爱蜜莉雅被分配到王侯馆。

造访王侯馆的菲鲁特，其实爱蜜莉雅也很高兴能与她重逢。

可是，爱蜜莉雅造访王都的目的——是为了向王城报告普莉希拉・跋利耶尔在佛拉基亚帝国殒命的事实。

爱蜜莉雅带回的报告，不仅对王选造成巨大影响，更让认识普莉希拉、爱着普莉希拉的许多人感到悲伤，这让她非常心痛。即使像这样与菲鲁特重逢，也不可能毫无忧虑。

更何况菲鲁特带来的消息，对爱蜜莉雅来说是沉重的追击。

「阿尔……」

为什么，爱蜜莉雅说不出这种没神经的话。

现在，阿尔会做出什么事，不可能与普莉希拉的死无关。失去重要存在的阿尔憔悴到让人看不下去，所以爱蜜莉雅他们才会听昴的诉说，送他们前往普雷阿迪斯监视塔。

相信在那里，阿尔会为了重新振作——不对，至少，会得到向前看的契机。

然而——

「——菲鲁特大人，可以再详细说明一下吗？」

在低着头紧握拳头的爱蜜莉雅身旁，一起到王都的奥托向菲鲁特搭话。

与不愿相信这个消息而心慌意乱的爱蜜莉娅形成鲜明对比，奥托注视着菲鲁特的侧脸十分平静，声音也很冷静。但是，爱蜜莉娅知道——奥托就是用这种态度来表达自己最愤怒的时候。

奥托的愤怒方式是爱蜜莉娅阵营的大家都知道的，菲鲁特似乎感受到了他那平静的压迫感，她抱着胳膊说：

「是啊，听说哥哥和精灵小不点被头盔混蛋抓住了。虽然不知道用的是什么方法，但似乎没有杀掉他们的打算」

「没有杀意？……塔里的其他人呢？」

「联系我的菲拉姆没事。梅莉和爱蜜莉娅姐姐的女仆也平安无事。但是，我们的老师和那个叫加菲尔的家伙被干得很惨。不过，好像也没有要他们的命」

「——是吗。谢谢你」

「不用谢。只是知道你在，不告诉你的话，我会觉得不舒服」

不卖关子直接告知后，菲鲁特看向爱蜜莉雅。她继续用带着热度的视线，看着还没松开拳头的爱蜜莉雅。

「我们的方针已经决定了，就是用莱因哈鲁特一口气回到领地。和罗姆爷商量过后，要做的事堆积如山。」

「领地是指阿斯特雷亚领吧？那里离奥古利亚沙丘很近，我们也跟菲鲁特一起——」

「——不，还是不要吧，爱蜜莉雅大人。」

「咦？」

爱蜜莉雅因为急躁而往前倾，却被奥托冷静的声音制止。

不明白制止的意义，爱蜜莉雅感到困惑。因为，现在昴他们正面临危机，必须尽快赶回塔里才行。

「该不会是因为我们增加，莱因哈鲁特会很辛苦？这个……那个，虽然现在要变轻很多很困难，不过我会努力……！」

「就算爱蜜莉雅姐姐和佐多虫哥哥增加，那家伙的负担也不会有什么改变啦。不过，不是因为那样哦？」

「菲鲁特大人的仆人认知先不管……是的。」

菲鲁特和奥托互相点头，爱蜜莉娅的头上满是问号。

但是，爱蜜莉娅并不怀疑，菲鲁特和奥托两人已经想好了，这是最好的办法。

「……我知道了。菲鲁特，小心点。也跟莱因哈鲁特说一声。还有，阿尔的事」

「兜帽混蛋的事，我没法跟你保证。抱歉」

「——不。你能跟我说没法保证，我很高兴」

菲鲁特粗鲁但诚实的回答，让爱蜜莉娅缓缓摇头，然后带着祈祷她平安的心情，从正面轻轻抱住她。

「————」

再会的时间很短，交谈的内容也完全不令人高兴。尽管如此，能看到菲鲁特平安无事的样子，毫无疑问是件令人高兴的事。

「爱蜜莉娅姐姐」

被抱住的菲鲁特露出奇怪的表情，挠了挠头。

「等这些全部结束之后，再聊吧」

「嗯」

「来聊聊那位公主的事吧。不光是我和姐姐，安娜塔西娅姐姐，可以的话库珥修姐姐也一起」

「……嗯。我觉得，那样非常好。」

菲鲁特用粗鲁的口吻说道，爱蜜莉娅微笑着，将她送出王侯馆。

之后，菲鲁特他们将由莱因哈鲁特带去阿斯特雷亚领，在那里有很多很多不得不做的事。

「昴……」

暴风雨般的菲鲁特离开后，爱蜜莉娅因涌上心头的烦闷而低语。

听说被送到普雷阿迪斯监视塔的大家遭遇了不幸，现在她紧握的拳头也迟迟无法松开——其中，爱蜜莉娅最担心的，是自己的骑士昴。

昴一直，一直一个人努力着，非常辛苦。

在帝国也为了雷姆和丝碧卡而一直绷紧神经，和埃布尔一起战斗，时而变小时而变大，即便如此也没能帮到普莉希拉。

为了折磨那样的自己，让帝国的许多朋友殴打自己，实在让人看不下去。而昴为了阿尔考虑的体贴，却被背叛了——

「……我。」

沸腾的，内心深处点亮的奇妙感觉，让爱蜜莉娅察觉到自己内心的热度。

和悲伤、心痛有点不同，那是爱蜜莉娅很少会有的感情，正因如此才让她非常困惑。

像这样，胸口、眼底、内心深处，像这样沸腾的感觉，自从那时候——在普利斯提拉和雷格鲁斯对峙以来就没体会过了。

对于希尔菲她们，用非常自私的理由束缚新娘内心的雷格鲁斯，爱蜜莉娅是真的真的生气了。

和那时候一样，或者是在那之上的愤怒，现在让爱蜜莉娅的胸口发热。

「爱蜜莉娅大人，您愿意听我说真是太好了。」

「奥托……」

自觉到自己心中有无法完全压抑的巨大激情，爱蜜莉娅直觉理解到表情平静的奥托也和自己一样。

那是当然的，奥托也是和爱蜜莉娅她们一样担心昴他们而来到帝国的人，这种事，虽然不是完全——

「嘿！」

「啪！」发出响亮的声音，爱蜜莉娅用双手拍打自己的脸颊。因为太过突然，奥托惊讶地叫道：「咦，爱蜜莉娅大人？」

爱蜜莉娅一边觉得不好意思，一边把手从发烫的脸颊上放下，

「刚刚，脑子里一片混乱，没法好好说话。不过，这样就没事了！……虽然没事是骗人的，不过能好好说话了」

「……是吗。那我也——」

「呀」

像是模仿点头的爱蜜莉娅一样，奥托也啪地拍了拍自己的脸颊。因为太过用力，发出的声音大到爱蜜莉娅以为他要流鼻血了。

不过，奥托没有流鼻血，只是脸颊变得和爱蜜莉娅一样红，

「——我来说明没有和菲鲁特大人同行的理由。我们一起去也没有意义……是为了以防万一」

「……继续说」

爱蜜莉娅没有打断双手贴着脸颊的奥托的说明。

虽然有疑问，虽然有想说的话。不过，先听对方把话说完。爱蜜莉娅所想的事，奥托也准备好了答案。

「莱因哈鲁特先生站在前线的话，以武力为基准送多少人过去都没有意义。菲鲁特大人应该也知道这点。即使如此还是回到领地是因为——」

「——那就是，以防万一？」

「是的。请试着想想。菜月小姐她们姑且不论，如果攻击了塔里和菲鲁特大人有关的人，莱因哈鲁特先生出现是自明之理。尽管如此，阿尔先生……那个男人还是下定决心了」

爱蜜莉娅终于明白了奥托想说的事。

莱因哈鲁特非常强。大概，在爱蜜莉娅所知的人中——不对，包括不知道的人在内，世界上最强大的就是莱因哈鲁特。帕克也这么说过，所以不会有错。

明知道要和莱因哈鲁特战斗，阿尔却什么准备都没有，这很奇怪。所以，阿尔肯定做了准备，莱因哈鲁特说不定也有危险。

「小菲鲁特是因为担心莱因哈鲁特才回去准备的吧。……但是，那我们呢？如果要准备的话，和小菲鲁特她们一起……」

「我们是莱因哈鲁特先生之后，菲鲁特大人她们的准备」

「——这样啊。明知道莱因哈鲁特会来，为此做了准备的话，为了那个准备而做准备的话……那个」

「就是这样。当然，如果要准备的准备的准备的准备的话就没完没了了。那个男人会做出暴行的理由，是因为在帝国发生的事……我不认为他有时间去策划，或是花时间准备。因为，他能用的时间应该和我们一样。」

「……嗯，说得也是。」

多亏了奥托仔细的说明，爱蜜莉娅的理解也追上了奥托他们。对他的深思熟虑感到佩服的同时，爱蜜莉娅也对奥托将阿尔称作「那个男人」一事，产生了非常沉痛的感情。

奥托的同伴意识非常强烈，一定是爱蜜莉娅他们之中最强烈的。虽然这点非常可靠，但同时也让他被迫做出非常痛苦的割舍。

话虽如此——

「……我也不知道该怎么想才好，阿尔。」

有理由，不可能没有。但是，即使有理由，有些事还是无法原谅。

昴很令人担心，碧翠丝没事吧？听说加菲尔受伤了，佩特拉和梅莉肯定也充满了不安。昴最喜欢的帕特拉修，说不定也在哭泣——胸口深处，有股灼热在燃烧。

「——是我的失态。」

在心中燃起火焰的爱蜜莉娅面前，奥托突然低语道。

因为完全不知道他话中的意思，爱蜜莉娅不由得瞪大了眼睛，说不出话来。奥托用放在自己脸颊上的手捂住了脸，凝视着天花板。因为比自己个子高的他这么做，爱蜜莉娅看不到他的脸。

但是，她知道他的声音在颤抖，而且那不仅仅是出于单纯的愤怒。

「我一直觉得菜月先生太过投入了。我勉强自己去理解，他是为了已故的普莉希拉留下的东西而行动，这样可以让他分散注意力，得到救赎。我试图让自己相信，只要和他分开的碧翠丝在他身边就没问题了。我也认为佩特拉会坚强地照顾和帮助他」

「奥托……」

「最重要的是，我把一切都交给了加菲尔。把我们所有人都必须做的事情，交给了那个直率、诚实、细腻的加菲尔」

「奥托！」

就在他的声音真正开始崩溃的瞬间，爱蜜莉娅抓住了奥托的双臂，让他把手和脸放下来，从正面看着他。然后，她看到了。

——奥托那双略带蓝色的眼睛，第一次被泪水润湿。

「可恶……为什么我总是考虑得不够周全呢……」

「────」

「够不着的手，赶不上的脚，不够的部分只能用头脑来弥补。明明知道这一点，却在关键时刻总是——」

「——」

爱蜜莉娅不想再听到奥托用快要哭出来的声音责备自己。

所以爱蜜莉娅抓住他的手臂，把他的头抱在自己的胸前。就这样抱着他的头，强行让他闭嘴。奥托似乎对爱蜜莉娅的行动感到非常惊讶，他一言不发地僵住了。

趁这个机会——

「不要这样贬低自己！奥托很努力了！我们大家都明白。正因为明白，所以想好好听奥托的话！」

「爱蜜莉娅，大人……」

「我知道！就算我说了这些话，奥托也明白吧？但是，我只会说我的话，只能说出我的想法，所以至少要带着我的心情说出来。所以——」

「────」

「什么都还没有结束。我们，还能够非常努力地继续下去！」

爱蜜莉娅紧紧地抱着奥托的头，坚定地如此说道。那像是在说给自己听一样，但同时也是相信着的话语。

不是别人，正是爱蜜莉娅的骑士菜月・昴无数次地让她相信。

爱蜜莉娅和昴一起积累起来的，最值得骄傲的信赖。

「我们，是非常非常地不放弃的！」

不擅长放弃。已经不行了，抱着头蹲下，逃走。正因为自己做不到这些，所以只能不放弃地继续努力。

是爱蜜莉娅的诉求传达给他了吗。突然，奥托一直僵硬的身体放松了下来，然后，

「……请松开手。会被菜月先生杀掉的」

「不，谁也不会死的！我们就是为了这个……」

「我知道了！我知道了啦！求你了请放开我！」

面对胡乱挣扎的奥托，爱蜜莉娅不情愿地松开了手。真的恢复精神了吗，爱蜜莉娅盯着奥托看，奥托一边用手帕擦着额头的汗一边叹气。

那是非常非常深的叹息。

「虽然不是那种场合，但我回想起来了。」

「回想起来？回想起什么？」

「——我帮助菜月先生和爱蜜莉雅大人的理由。」

用手帕擦掉眼角的泪痕，奥托用平静的表情这么说。那和刚刚非常生气的表情不同，是下定决心的勇敢表情。

「对方绑架了菜月先生和碧翠丝妹妹，应该有这么做的理由。绑架的目的通常是对相关人士的威胁，或是对本人……」

「对我们，或是对昴有事吧。」

「是的，如果真的和『神龙』有关，那这就是王国整体的问题。我们就在王都完成应尽的职责吧。」

「——嗯，就这么办，得快点行动。」

听着奥托诉说的未来展望，爱蜜莉雅拼命忍住冲动。

「——」

那是迟来的，想要现在立刻奔向昴他们身边的冲动。莱因哈鲁特在，菲鲁特也在，奥托所想的这些理由，都被想要冲出去的强烈心情给推翻。

想要触碰，想要凝视，想要听到声音。

当你受伤想要低头的时候，我想在你身边。

「——昴。」

爱蜜莉娅还不知道，这种焦灼的，和愤怒不同的感情叫什么名字。

3

「嘿呀！！」

笔直地飞奔过去，不听对方解释就对阿尔的心窝处使出浑身一击——这全部都是送爱蜜莉娅过来的奥托的指示。

『请忍住想听对方解释和说明的心情。这些全部，等对方亮出底牌后再听也不迟。』

推着爱蜜莉娅后背的奥托，用尽全力使用自己的『言灵之加护』找到阿尔他们，原本就白皙的脸色变得像病人一样苍白。

不想让他乱来。但是，该乱来的时候也只能乱来。爱蜜莉娅的生存方式，也不允许她去阻止这种乱来。

所以，为了尽早结束这种乱来，爱蜜莉娅努力着。

「这样——」

怎么样，正想这么说的爱蜜莉娅，对冰冻的拳头的触感感到违和。

明明是用拳头打在阿尔裸露的身体上，反弹回来的却是打在坚硬墙壁上的反作用力——

「突然就来啊……！」

阿尔用挤出来似的声音说道，他的身体被石铠覆盖，保护着。

明明是奥托说的先发制人，却失败了。但是，现在不是为此而沮丧的时候。一次没打中的话，就再挑战两次三次。

「连话都不听我说，真是寂寞啊」

「那是！阿尔你才——嗯呣」

「嗯呣？」

「说好不提的——！」

被石铠挡住拳头，向后弹开的阿尔正想说些什么，爱蜜莉娅却中途强行闭上嘴，用双手做出的冰槌横扫过去。

独臂的阿尔把娇小的对手扛在右肩上。爱蜜莉娅一边想着利用他行动不便这点很狡猾，一边故意从阿尔的左侧打过去。

全力挥出的一击，打中的话会非常痛。不仅如此。

「切！」

爱蜜莉娅狡猾的一击，被阿尔用左臂——用魔法做出的石制手臂挡住了。但是，挡下攻击的阿尔却咂了咂嘴，立刻破坏了好不容易做出来的左臂。

因为冰槌击中的部分开始冻结，连阿尔的身体都快要被冻住了。

『如果无视感情问题，为了救出菜月小姐他们，我们必须活捉那个男人。就这点来说，爱蜜莉娅大人的战斗方式很合适。话虽如此——』

「——我保证不会像昴那样乱来！」

爱蜜莉娅把出发前和奥托的约定铭记于心，制作出冰之双剑，踏出一步。

——爱蜜莉娅的冰结品牌・技艺新增了新功能，那就是冰之武器碰到对手后会将其冻结，夺走其身体的自由和武器的自由。

因为这个功能，比起制作普通的武器，使用玛娜的量会稍微多一些，但只要不是大量战斗，对爱蜜莉娅来说还在误差范围内。

不夺走对方的性命，而是阻止其行动——这就是爱蜜莉娅所期望的“冰结魔女”的战斗方式。

「啊哈哈！大叔，你是不是有点不利啊？」

「闭嘴！」

阿尔扔掉快要冻结的假手，对扛着的对手怒吼道。

阿尔不惜做到这个地步也要扛着的对象，正是被关在监狱塔里的罗伊・阿尔法德，爱蜜莉娅亲眼确认了这一点，咬紧了嘴唇。

罗伊是爱蜜莉娅她们和安娜塔西娅她们合作努力抓到的大罪司教。

尤里乌斯为此付出了特别多的努力，而爱蜜莉娅对尤里乌斯没有夺走罗伊性命的判断，以及安娜塔西娅允许他这么做的勇气，都抱有很高的好感。

「可是，你们两个却让我失望了……！」

为了阻止他们，爱蜜莉娅要在这里阻止阿尔。不管阿尔有什么愿望和祈祷，都不能让罗伊逃走。

「我可没有理由要听从你的想法」

就在爱蜜莉娅鼓起干劲后，阿尔的脚下突然隆起，整个人被打上了天空。他用土魔法制造出立足点，一口气跳到了高处。

他大概是打算就这样和爱蜜莉娅拉开距离，逃离这里吧。爱蜜莉娅一时反应不及，就算伸出冰块也够不着头顶上的阿尔和罗伊。

但是——

「——冰柱线」

「咕哦！？」

爱蜜莉娅在监狱塔周围布下的冰雾结界，不允许他们逃走。

白雾弥漫的天空中传来惨叫，阿尔的头撞到了冰的天花板，逃亡剧以失败告终。他被完全覆盖周围的冰的天盖挡住，头朝下掉了下来，爱蜜莉娅追上他，用冰之双剑使出浑身一击——

「——！？」

被坚硬的触感弹开，爱蜜莉娅倒吸一口气。

如果和刚才一样，只是阿尔用假手接住的话，她也不会这么惊讶。阿尔确实做了新的手臂，但做的不光是这个——阿尔做出来的是岩石义手和石制双剑。

「大地品牌・技艺，差不多是这样吧！」

「模仿……！」

「想出这个的是菜月・昴吧？那我也有使用的权利吧？」

在瞪大眼睛的爱蜜莉娅面前，阿尔利用冰和石双剑的碰撞产生的反作用力旋转，和爱蜜莉娅拉开很大的距离，再次落在雪地上。

在阿尔周围的地面上，石剑发出声音一个接一个地生长出来——他打算用土魔法，做出和爱蜜莉娅的冰品牌・技艺一样的事情。

「这是我和昴两个人，非常努力练习的魔法！」

「我知道别人在卿卿我我时，有人插进来会被认为是被地龙踢死的家伙。我姑且说一下，我不是为了煽动你，而是迫不得已。」

爱蜜莉娅不知道该相信他到什么程度，阿尔一边说着一边用石制义手拔出旁边的剑。爱蜜莉娅狠狠地瞪了他一眼，然后她注意到了——罗伊的身影不在阿尔的肩膀上。

「——！那孩子呢……！？」

「啊，刚才趁乱让他逃了……如果这么说的话会很帅吧，但我没有那个余裕。只是因为碍事所以放开了他。你看那里」

爱蜜莉娅的肩膀抖了一下，阿尔耸了耸肩，用下巴指了指刚才隆起的土柱。罗伊被倒吊在土柱的正中间。

罗伊的身体被土做成的被子盖住，行动被封住了。他和爱蜜莉娅对上视线，然后嗤笑起来。

「加油啊，姐姐。如果姐姐赢不了的话，我们就只能听那个大叔的话了。咦？但是，如果姐姐赢了的话，我们不就又得回监狱塔了吗？哈哈，那不管谁赢都一样啊」

「……如果能起来反省的话，就起来反省一下吧」

「哇哦，好棒的回答。我本来就很喜欢你，现在更喜欢了……好痛」

「别废话了」

罗伊用湿润的眼睛看向爱蜜莉娅，然后被小石头砸中了脑袋，皱起了眉头。那是阿尔不高兴地踢出的小石头。

「阿尔，对不能动的人做这种事，非常不好」

「谢谢你的说教。但是，从他至今为止做过的坏事来看，那只是微罪吧？」

「就算做了大坏事，也不能对小坏事视而不见」

爱蜜莉娅一边训斥着理直气壮的阿尔，一边思考着罗伊的处置。

罗伊被魔法固定住了，虽然封印被解开很危险，但总之他没有逃走，爱蜜莉娅松了一口气。她原本就觉得只是把他固定住是无法让他反省的，所以对罗伊在监狱塔的待遇还有考虑的余地。

如果能创造出罗伊不会逃跑的环境，让他在清醒的状态下好好反省自己的所作所为，这就是爱蜜莉娅的理想。

但是——

「这些都得等这里的事情全部结束之后再说」

「真是果断啊。话说回来，你已经愿意和我说话了吗？」

「啊！……从现在开始。从现在开始，我完全，一丁点都不会和你说话」

「真冷淡啊。我可是觉得和小姑娘你好好谈谈的话，就能互相理解——呜哦！」

爱蜜莉娅向还想继续说下去的阿尔发射冰锥，表明了不想再和他说话的意思。

阿尔向旁边一跳躲开了冰锥，爱蜜莉娅绕到他的侧面，刺出了闪耀着蓝白色光芒的冰矛——瞬间，冰矛的尖端被岩石剑挡下，冰矛和岩石剑同时碎裂。

爱蜜莉娅立刻造出下一把冰刺突剑，阿尔也从地面拔出下一把岩石剑，两人的剑剧就此开幕，武器碎裂后又重新造出，造出后又再次碎裂的战斗连锁不断。

「不错，不错啊，不错呢，不错嘛，不错哦，不错嘛，不错吧，正因为觉得不错！暴饮！暴食！」

在爱蜜莉娅和阿尔的激烈冰岩剑剧之中，传来了罗伊的喝彩声。

爱蜜莉娅一边把罗伊的声音从意识中赶出去，一边对自己的攻击感到焦躁，明明觉得绝对能打中，却总是被阿尔惊险地躲开。

好像打中了又好像没打中。总感觉，就像在踢水面一样没有实感。

最重要的是——

「虽然不是在夸你，但你这招还真不错——真是羡慕你们相亲相爱啊」

「——」

阿尔那过分的说法——让爱蜜莉娅勃然大怒。

一定要除掉那个邪智暴虐之王——想起昴之前说过的生气时的固定句型，爱蜜莉雅勃然大怒。

不想听到阿尔用那种说法来描述自己和昴的关系。

而且更让爱蜜莉雅生气的是，那并非阿尔真心的想法，而是为了惹她生气才说的。

还有——

「之前我就在想了，阿尔和我说话的时候，为什么看起来很寂寞？」

「——你不是说不和我说话吗……」

「不要只在对自己有利的时候才拿出来讲！还有，另一个！」

爱蜜莉雅大声斥喝，同时用力挥下高举的冰之大剑，阿尔将岩石剑架在头上挡住——这时有人抓住阿尔的双脚和腰部。

阿尔倒抽一口气，抓住他身体的是冰之手臂的主人——冰之士兵。

爱蜜莉雅信赖的，长得像昴的冰之士兵，让阿尔咬牙切齿地说：「糟透了……！」

这时，爱蜜莉雅抬起穿着冰靴的脚——

「——和我说话的时候，要好好看着我！！」

这次使出浑身解数的踢击，打穿了岩石的防御，击中了阿尔。

4

「————」

八重微微皱眉的反应，菲鲁特没有看漏。

这并非菲鲁特眼尖，也不是八重反应过度，而是菲鲁特为了「那一刻」，一直绷紧神经。

菲鲁特并非确信——即使如此，她还是期待「那一刻」到来。

在这种束手无策的状况下，再丢脸也不过是误差。既然如此，干脆豁出去，抓住所有能抓住的希望才是上策。

其中之一，就是自己和八重的对话，或许会被微不足道的「某物」听到。菲鲁特想起之前「被迫觉悟死亡」时的事，因此期待。

「安静。」

八重睁开平常眯起的一只眼睛，静静地靠近房门。

不容分说的言词压力，具有说服力，让菲鲁特相信只要自己轻举妄动，脖子上的线就会惩罚自己的粗心大意。

因此，八重留下无法动弹的菲鲁特，将手伸向门——

「——！」

——刹那间，无声贯穿门扉的锐利剑尖，毫不留情地逼近八重的喉咙。

「——」

菲鲁特倒抽一口气，八重雪白的喉咙在她的视野中被剑贯穿——没有。剑尖在即将划开八重喉咙的前一刻停了下来。不是对方停手，而是八重用线缠住剑尖，勉强挡下攻击。

九死一生，千钧一发。但是，八重的危机并未就此结束——挡住的剑与另一把剑同时挥出，门被砍倒，剑光狂乱。

「唔！」

面对迎面而来的剑风，八重用力往后跳，同时挥舞丝线。

一边是剑，一边是线，尽管如此，两种武器的冲突，却在室内奏响钢铁与钢铁碰撞的火花般清脆声响，剑光灼烧旁观的菲鲁特的双眼。

八重巧妙地运用双手，射出占满视野的丝线，撕裂房间奢华的内部装潢。但是，对手也用双手的剑表演压倒性的剑舞，从正面斩断闪耀银线的威猛，强行横扫想缠住自己剑的丝线——瞬间，两者之间的距离消失了。

「喝啊啊！！」

「——唔！」

踢出的前踢，从正面踢中八重的细腰。八重立刻扭身，一边旋转半圈一边飞出去，脚踩墙壁着地，手按住腹部。

然后，八重直直盯着做出这件事的闯入者。

「……突然踢女士的肚子，真是毫不留情的客人呢～」

「——有必要吗？对忍者你手下留情。」

「那不是歧视忍者吗？那不是绅士该做的事哦？」

「很不巧，我不记得自己有做过值得绅士这个评价的事。不管到哪，只会挥剑的我只能是剑士。」

这么说完，从双手的剑上甩开丝线，蓝色的平静眼神看向八重的人物——对于他的自我评价，菲鲁特小声地吐嘈「别说蠢话了」。

确实，不知道他是不是绅士。但是，他不只评价为剑士。那个男人，菲鲁特也知道，许多人不允许他只被这么评价。

要说为什么，自称一介剑士的那名男子，曾经以剑尖触及剑术顶点，拥有夺取胜利的剑力。亦即「剑鬼」——

「——威尔海姆・托利亚斯。听说王国陷入穷途末路的窘境，所以前来尽微薄之力。」

听着对方报上名号，菲鲁特一边退到房间角落，一边叹气。

面对意想不到的援军，她的心情十分复杂——

「……佐塔虫小哥，真的不择手段耶……爱蜜莉雅姐姐那边的家伙到底怎么了？」

她半是傻眼半是佩服地嘟囔。

5

强烈的剑气充斥室内，肌肤真的起了鸡皮疙瘩。

虽然内心锻炼到不会被大部分的事态影响，但在预料之外和意料之外接连发生的情况下，这种局面应该算是例外的变故吧。

「——威尔海姆・托利亚斯。」

在口中重复对方报上的名字，八重・天膳静静地加强警戒。

虽然只交手过一次，但第一招是对方的踢击，八重处于劣势。

尽管往后跳抵销冲击，但那一踢的伤害还是残留在八重纤细的身躯。要是没往后跳，威力大到腹部可能会被踢出一个鞋型的洞。毫不留情地踢向妇孺，所以正如本人自称，称不上是绅士。

这个老剑士的称号，早在四十年前就准备好了。

也就是——

「——『剑鬼』先生登场了，能见到名人真是感激不尽～为亡妻报仇的故事，简直就是王国之剑的荣誉呢～」

「————」

「哎呀？不过我听说在那之后，您和夫人意外重逢了！在水门都市发生的事想必让您很痛苦吧？我深感同情，呜呜呜。」

「————」

八重用手指揉着眼角，一边假哭一边观察对方的一举一动。

面对八重的红色视线，老剑士——威尔海姆凛然挺立，没有一丝动摇，将凛冽的剑气传到双手持握的两把剑上，然后盯着八重。

那双蓝色眼眸的平静，让刻意不客气地践踏对方心灵、试图让对方动摇的举动以失败告终，同时也让八重深深体会到自己只是在扮演性格恶劣的女人。

「……根据我听到的印象，还以为您会更激情呢～」

看样子，那也是不正确的印象。

虽然情报来源是亨克尔，但连本应是她亲生父亲的情报都难以相信，那到底还能期待他什么？干脆别让亨克尔监视「龙」，让他监视菲鲁特就好了。

然后，如果亨克尔让菲鲁特逃走，就能同时成立收拾她的名目，以及切割亨克尔的名目。

八重会这么想的理由是——

「除了里长老爷爷以外，应该没人能察觉到我的隐身才对——菲鲁特大人，您该不会做了什么坏事吧？」

「那也太强词夺理了吧。我根本拿你没办法，这点你自己最清楚吧。」

「————」

「除了和你说话以外，我什么都没做。那就是现在的我全心全意做的事。」

声音中带着些许自愤，退到房间角落的菲鲁特如此回应。

她不是能做出愤怒演技的聪明人。如果她有连声音颤抖都能调整的精湛演技，那骗人骗到这种地步的本事就值得称赞了。

因此八重轻轻拉扯挂在菲鲁特脖子上的钢丝，让她意识到钢丝。

「请不要考虑逃跑哦？我可不想让菲鲁特大人的可爱脑袋和身体哭着分开。」

「再追加一次踢屁股。还有，我可没资格说这种话。」

「什么？」

「现在的你，没空东张西望吧。」

菲鲁特吐舌头，可爱到不可爱。但是，用不着提醒，八重的警戒一刻也没从威尔海姆身上移开——站在和先前相同位置的威尔海姆，因为八重的钢丝术而无法决定如何出招。这也是当然的。

——忍术大半都是专门针对对手的弱点。

因此，和为了战斗而存在的战士的战斗技术不同，为了杀戮而存在的忍术被称为术技。八重的钢丝术就是最典型的例子。

愈是身经百战的战士，愈会在战斗方式上慎重行事。趁这段期间，像蜘蛛网一样布下十重、二十重的陷阱，就是忍者的本领——

「——四手。」

「——？什么？」

威尔海姆的嘴唇突然吐出单词，无法理解的八重皱起眉头。

对于八重的疑问，威尔海姆没有回答——但是，他给出了答案。微微眯起眼睛，发出的锐利剑气将八重全身切裂。

「——」

来了，这么想的瞬间，八重弹开似地动了。

遵从忍者的本能，双手五指毫不犹豫地动员，不是压制而是杀戮的钢丝斩击打向「剑鬼」，用丝线进行压杀。

——阿尔下达的不杀指示，只要结果上遵守就行了。

抱着杀意发动攻击，即使如此对手还活着就谢天谢地。但是，不抱杀意的攻击，对这个对手不管用。

因此从四面八方，再分割成十六方三十二方，更加细分的钢丝形成无处可逃的死条牢笼，对此，威尔海姆让双手的刀刃闪烁——

「哦哦哦哦——！！」

挥舞的双剑卷起的剑风，将涌来的杀戮钢线如字面所述一蹴而散。

剑速过快，剑与钢丝的冲突声一次响起，产生的剑火让八重产生眼睛被灼伤的错觉。压倒性的剑压挡下初击，但是钢丝术没有中断。

从戒指中生出的钢丝被赋予了足够的空间，接下来是更加细分的攻击——刹那间，房间的『地板』在八重眼前被斩起。

——被切开，被踩住边缘而抬起的房间地板。大小堪比奢华床铺的『地板』，从八重的视野中遮住了威尔海姆。

「————」

咚，强烈的踏步，那块『地板』被踢向八重。

在逃亡空间有限的室内没有逃走的空隙，八重改变左手操纵的钢丝角度，应对冲过来的『地板』，不是斩断而是捆住，弹开，反弹回去。

被踢飞的反作用力直接被利用的『地板』，以比去程更快的速度和危险性在回程上猛然撞向途中的『剑鬼』。

那是——

「哈？」

尖锐的突刺声响起，八重看到被射到空中的『地板』而瞠目。

势头加速，威力随着重量倍增。『剑鬼』将剑尖分毫不差地对准『地板』的中心，将那股反叛的威力在空中完全抵消。

那正是，不属于人类所能达成领域的神技。

八重也是被捧为超乎常人领域的神童，和威尔海姆共度许多时光的人，所以她知道——即使年老，『剑鬼』的剑技依然停留在神技的领域。

「三招。」

在屏息的八重视野中，停留在空中的『地板』另一侧，威尔海姆如此低喃。

被宽度不长，长度很长的『地板』挡住，八重看不见威尔海姆的身影。可是，钢丝的优势在于能够攻击看不见的位置。

让钢丝绕过『地板』，将另一侧的『剑鬼』赶往左右其中一边。

不管他往哪边逃，那边都已经布下钢丝——

——随后，剑尖贯穿空中的『地板』，逼近八重的鼻尖。

「————」

钢铁敲击钢铁的声音响起，剑以强弓般的速度射出。剑刺在『地板』上，威尔海姆敲击剑柄尾端，让剑贯穿『地板』。

与其说是出乎意料，不如说是超乎规格的飞箭射来，八重放弃用钢丝捕捉剑，稍微错开轨道，倾斜细颈避开致命伤。剑尖通过脖子旁边，刺在背对墙壁的八重身旁。

躲开了。而且，八重在这一刹那也没有将视线从『剑鬼』身上移开。

所以她立刻就察觉到自己的失策。

剑深深地刺在八重的脖子右侧——将她的退路限定在左边。

然后——

「喝啊啊啊啊——！！」

以『地板』为立足点跳起，蹬着天花板加速的『剑鬼』的斩击落了下来。

直劈而下的剑刃一直线地瞄准八重的性命，深深地砍入了她的左肩。

6

威尔海姆・范・阿斯特雷亚——不，威尔海姆・特利斯会出现在这天的王都，是为了寻找让主人库珥修・卡尔斯腾痊愈的方法。

在与魔女教的战斗中，库珥修被『色欲』大罪司教注入了侵蚀身心的邪毒，这几个月来，她一直徘徊在地狱之中。

就连王国第一的治愈术师，拥有『青』之称号的菲利斯，也无法除去她的痛苦。而最近，终于出现了曙光。

库珥修的病状并没有戏剧性的改善。只是，出现了或许能开拓出可能性的手段——通往普雷阿迪斯监视塔的道路已经打通了，她收到了这样的报告。

只要借助露格尼卡王国三英杰之一，被誉为全知全能的「贤者」夏乌拉的智慧，或许就能知道如何从邪毒中拯救库珥修。——菲莉丝抱着一线希望，威尔海姆无法劝阻她。

去年，库珥修被魔女教夺走「记忆」，个性与以前大不相同，菲莉丝一直尽心尽力地支持她。菲莉丝本身应该也为了与长年相处的库珥修重新建立关系，而感到许多苦恼与困惑。

这样的日子持续了将近一年，两人之间终于建立起信赖关系——虽然与以前不同，但即使不同也无可动摇，缔结了这样的羁绊。

——却被「色欲」大罪司教卡佩拉・埃梅拉达・露格尼卡破坏殆尽。

之后库珥修的痛苦如前述，陪伴在她身边的菲莉丝也令人不忍卒睹。

所以，当听说以普雷阿迪斯监视塔为目标的昴一行人抵达塔并获得成果时，威尔海姆他们除了佩服，还被更深切的希望灼烧。

虽然昴他们没有直接带回来这个消息让人觉得奇怪，但其他阵营的动向是无法介入的。只不过，他们想要尽快得到塔的情报。

因此威尔海姆他们坐立不安，为了直接向王都申诉，希望前往普雷阿迪斯监视塔，而动身前往王都。

然后，在被叫到王侯馆的一个房间，被告知有话要说时——

「——有事想让您知道，还有想请您协助的事。」

爱蜜莉娅阵营的青年内政官，告诉了他们可能会动摇王国根基的灾祸的来龙去脉，以及威尔海姆挥剑的理由，也就是两个名字。

「噜啊啊啊啊——！！」

踢向天花板，从正上方朝红毛少女——高超的忍者砍去。

极细的丝状凶器实在是过于多彩，其威胁以不规则的轨迹散布开来。从各种角度瞄准性命的忍者术技，战斗拖得越长，大意的概率就越高，因此威尔海姆选择了短期决战。

以毫厘之差超越剑力，紧咬不放的斩击从她的左肩侵入，就这样一口气从右腋拔出，以袈裟斩将性命一刀两断——本应如此。

「——」

刹那间，少女咬紧牙关，身体沉入地板——不，并不是沉入。

地板被丝线切开，散落一地。失去立足点的少女身体就这样先行坠入地下，威尔海姆也紧追在后。

「————」

威尔海姆迅速伸出手，从墙壁上拔出封住少女动作的剑，确保双剑。

虽然没有砍飞少女的左臂，但肯定受了重伤。不能误判进攻的时机，让对手逃走更是万万不可。

忍者一旦从视野消失，就会变得比看得见时还要麻烦五倍、十倍。

也就是说——

「「——在这里解决。」」

威尔海姆和少女的声音重叠，他们并没有事先商量好。

在坠落的黑暗地洞中，威尔海姆看到反射光线的丝线瞬间闪耀——那是宛如蜘蛛网般布满地洞的致命丝线。

7

八重背朝下坠落，用钢丝绑住自己的左肩止血。

虽然刀刃深深地侵入了少女柔嫩的肌肤，但生命之花并没有散落，所以勉强算是安全过关。同时，八重也对『剑鬼』的剑力之强感到惊叹。

最初用来防御八重钢丝的一招，踢飞斩断的『地板』的第二招，阻止八重弹回的『地板』的第三招，以及以贯穿地板的剑为诱饵，冲入八重怀中的第四招——正如他一开始所宣言的，八重差点就被这四招杀死了。

「尽是些讨厌的老人……！」

最亲近的个性最差的『恶辣翁』，在平原上让阿尔吃尽苦头的巨人族老人，以及一把年纪却达到剑术顶峰的『剑鬼』——八重脑海中浮现的老人，全都是些不知圆滑处世为何物的人。

说到底，生命之火随时熄灭都不奇怪，这就是世界的常理。尽管如此，能在这样的世界中长生，就表示这些老人在生命的筛选中胜出。

『所以老太婆才可怕啊。要是以为老人很弱很脆弱，就会在自己变成老太婆之前先一步进坟墓。不过，活了很久的忍者是例外中的例外，老朽说这话好像也不太对劲？』

八重回想起在严酷的环境中生存下来的里长的高笑声，脸颊不禁抽搐。

忍者们的精髓就是瞒过对手的眼睛，迷惑对手的心，封住对手的行动，夺走对手的性命。八重在迷惑对手心神的技巧上也是个优等生，但她也知道自己在这方面比不过里长。

八重的个性没有里长那么扭曲，她也不认为自己能活到那么老。实际上，她就曾差点被阿尔杀死。

她不认为那种幸运会一直持续下去——心地善良的怪物一时兴起，根本就是奇迹。

「————」

威尔海姆拔出墙上的剑，追着八重跳入洞中。

看来他似乎有和忍者实战的经验，他的动作充满自信。八重猜想，他恐怕对过去派遣忍者过来的佛拉基亚帝国，以及当时没有杀死威尔海姆的前辈忍者们怀恨在心。

八重将这些想法压缩成一口气吐出，然后在心中切换开关——在地下这种黑暗的环境中，她的视野变得比白天还要明亮，而且更加宽广。

这是适应黑暗的训练成果，她操作眼球周围的血流，改变视觉，是一种肉体操作。

在从黑色变成灰色的视野中，浮现出白色『剑鬼』的身影，八重张开双手，表示终于将对手引入了自己的领域——

「「——在这里解决你」」

双方同时说出意料之外的话语，但彼此脸上都没有笑容和惊讶。

双方都决定要杀死对方。既然精神攻击已经没有意义，那就放弃所有心惑之术技，为了取走对方的性命，竭尽血色的诚心诚意。

这里就是八重为此而准备的『红樱』的杀戮领域。

——在跋利耶尔别邸地下挖出的空洞，并非是将建筑物改造成自己喜欢的普莉希拉的提案，而是原本的主人莱普・跋利耶尔留下的礼物。

据说普莉希拉的亡夫有着病态的不信任和猜疑心，他在王都建造的别邸自不必说，连在自己领地的宅邸和隐居处都准备了以防万一的措施。

这个地下空洞也是其中一项措施，原本是和通往外面的避难路线相连，但八重认为可能会成为敌人入侵的路线，于是将通道破坏，只留下了大洞。

八重和莱普素不相识，对于他强行娶普莉希拉这样年轻美丽的妻子，还把妻子当作傀儡企图掌握国政，八重只有厌恶感，但对莱普想要防备各种灾难的态度产生共鸣，于是心怀感激地利用了。

重新利用大洞，布满钢丝，改造成只有八重能自由使用的处刑场，这就是「红樱」杀戮战场的真面目——为了在紧急时刻随时都能帮助阿尔，潜入王都，带着为了监视而带来的菲鲁特进入那个房间，也是为了在万一的时候能发挥这个功能。

因此——

「——接下来，脚不放水。」

八重边说边弯下膝盖，从脚上脱下鞋子，伸展被黑色内衣包裹的脚尖——左右脚的五指张开，从嵌在手指上的戒指射出钢丝。

正如字面意思，不放水，脚不放水，手脚合起来二十根手指巧妙地操纵，八重・天膳登峰造极的杀戮术技在黑暗中跋扈——

「————」

这边和那边，彼此都希望短期决战。

八重一边落下，一边用膝盖勾住一根绷紧的钢丝，切断落下的势头，反转身体，在如同大井一样的圆筒形空洞中，利用钢丝的张力跳跃，开始狩猎。

八重利用如同杂技演员一样的轻盈，如同被风吹起的花瓣一样舞动。

轻飘飘，轻飘飘，衣摆，红发，修长的手脚，都在舞动。

八重那流丽的舞蹈，伴随着将看入迷的人引向死亡的银丝，舞动的她的周围，被舞蹈所吸引的人的血花绽放——因此，是「红樱」。

吸收倒下的尸体流出的血，盛开的，美丽而残酷的红樱。

「——」

被与那个异名相称的猛威攻击，委身于自由落体的威尔海姆全身沐浴在钢丝中，在做工精良的衣服下，老剑士的血肉在空中飞散。

被一边落下一边挥舞的双剑的剑风煽动着头发，八重对「剑鬼」的眼力感到吃惊。

剑和钢丝不同，只能到达挥舞刀刃的手臂的范围。因此，在这个准备好的处刑台上，威尔海姆只能一味防守。

理所当然，被重力束缚，行动受限的威尔海姆，和依靠钢丝自由自在在黑暗中来回的八重，两者之间绝对无法靠近。

保持剑击绝对无法触及的中距离，单方面用钢丝攻击。在跳完一支舞之前，在「剑鬼」到达地面恢复自由之前。

八重的手臂缓缓抬起——血喷出。

八重纤细的脚在墙壁和空中滑行——血喷出。

八重扭动细长的身躯，背部向后仰到极限——血喷出。

八重的舞蹈越是接近完成，沐浴在无法完全防御的钢丝攻击中的「剑鬼」就越是染血。

他的脚、身体、肩膀、脖子、脸颊、额头，被锐利的钢丝划出伤口，流着血的「剑鬼」逐渐被引向死亡。

但是——

「——讨厌的眼神。」

寄宿着可怕而澄澈的剑气的目光，完全没有被战意污染。

「————」

除了八重挥舞的双手双脚的钢丝，还有已经布满地下的钢丝。

不用说，光是分心应付八重，不小心碰到绷紧的钢丝就会失去四肢，碰到脖子或身体就会失去性命。

对威尔海姆来说，这个大洞就和不经思考就跳进去的魔兽的下颚一样。肉被牙齿削掉，血被舌头吸吮，最后落入胃中，生命被溶解——他没有露出那种眼神，而是对抗绝望与鲁莽。

「可是，能做的事不多吧？」

就算没有那种眼神，八重也不会小看「剑鬼」。

八重早就舍弃亨克尔对威尔海姆的评价，用自己的眼睛确认在生死交锋中的「剑鬼」——因此，她对束手无策往下坠落的「剑鬼」，警戒着两种攻击。

一种是蹬墙，和将八重打落地下时一样的剑击。

另一种是在地上展现过，朝八重的性命投掷剑的招式。

这两个选择，是任凭身体自由落体的「剑鬼」唯一能做的反击。而「剑鬼」会选择哪一个，答案在眨眼间就揭晓。

「——咻。」

伸长的黑色脚尖画圆，在威尔海姆的脸颊上留下三条伤痕后，「剑鬼」朝正下方挥舞双剑弹开钢丝，强健的脚部律动，鞋底踩在墙壁上。

微微弯曲的膝盖，积蓄了足够的脚力，「剑鬼」在空中疾驰——在那之前，从举起的双臂中投出两把剑，朝八重的性命迸发。

两条银光在空中奔驰，八重用舞蹈的一连串动作回避朝自己迫近的剑。

以遍布的钢丝为立足点空翻，让剑刃从胯下和后背擦过，平安无事。然后，用双脚的钢丝招呼在剑之后飞来的「剑鬼」。

放开剑，没有手段应对钢丝的威尔海姆扭动身体，护住头部，以最小的伤害穿过钢丝的网眼。但是，八重已经不在他突进的路线上，用钢丝弹开逃走，赤手空拳的「剑鬼」的手够不着她。

这样就成功防住了警戒的两招——要安心还太早。

「——哦哦哦！」

扑空的威尔海姆大吼，伸出手。那里插着刚才投出的双剑，抓住两把剑的威尔海姆蹬墙，再次飞起。

追赶逃到斜上方的八重，威尔海姆以弹速朝上方前进——然后直接踢飞他飞过的墙壁，朝对面的墙壁飞去。又踢墙，再飞去。不断重复这个动作，追上边舞动边上升的八重。

「开什么玩笑……！」

面对用蛮力追上来的威尔海姆，八重的喉咙深处因惊愕而颤抖。

踢墙，用三角跳的要领上升。这个动作本身八重也做得到，没什么好惊讶的。该惊讶的是，威尔海姆重复这个动作的场所，是八重布下无数钢丝的地方。

随便乱飞的话，当然会背负撞上钢丝而四分五裂的风险。

但是，威尔海姆不害怕。为什么？——因为他掌握过一次坠落通过的空间，知道那里有钢丝，所以飞起来的时候不会撞到。

那是异常卓越的战斗直觉和观察力，以及毫不犹豫地将性命赌在自己亲眼确认过的事物上的决断力，两者并存的可怕战技。

面对翩翩起舞，果敢冲进银丝风暴的「剑鬼」，八重无奈地将手伸向王牌——

「——呜、呀。」

八重用丝线弹起，高高跃起，以倒立的姿势伸出双手双脚，二十根手指射出的钢丝缠上事先布下的钢丝，将四肢拉近。

八重巧妙的钢丝术，利用钢丝的缠绕方式和周围的物体，可以在森林的战斗中一次捆住一百个以上的人。而八重现在正用着全身的骨头和肌肉，将钢丝一口气拉紧。

「——嘿呀！」

刹那间，银色的钢丝在地下空洞的昏暗中不规则地狂暴肆虐。

用线切开香肠肉的机关，利用绷紧的钢丝断裂的张力，八重自己也无法预测轨道和数量，仿佛要将整个空间撕裂的斩丝击。

再加上——

「——能干的女仆会多花点心思！」

八重将无数的丝击压杀的空间置于眼下，将双手的戒指拉到嘴边，亲吻——随后，从戒指伸出的丝线被火焰点燃，一拍后，爆炸火焰升起。

狂暴的丝击加上烧尽一切的灼热业火——八重翻开两张王牌，毫不留情的忍者术技，将「剑鬼」的身影包覆在红色的光芒中，烧焦。

「果然——」

没能贯彻不杀的信念，八重对战斗的结果感到遗憾。

但是，战斗开始的瞬间她就明白了。对方不是不杀就能战胜的对手。只有抱着杀意战斗，才能选择对方是生是死。

所以——

「请对亨克尔大人保密——」

「——不必。他也应该知道我来了。」

刹那间，突破爆炎飞出的『剑鬼』的斩光，擦过空中的八重。

「——呜。」

被锋利的剑闪砍中身体，无法卸除威力的八重以不同于舞蹈的形式喷着血旋转，瞪大双眼，呻吟着发生了什么。

发生的事情显而易见。敌人从钢丝的风暴和追加的爆炎中活了下来。问题是，他是怎么做到的。

最后的威尔海姆从正上方飞来。和之前的三角跳跃不同轨道，要在洞穴中实现那种跳跃，只能和八重一样——把钢丝当成踏脚处。

「你是怎么，把我的线……」

「我看过很多次了——你的线是锋利得可怕的武器，但只要用特定的角度和施力，就能不斩断而直接绑住。」

威尔海姆的回答，是看穿八重钢丝特性的正确答案。

奇怪的是，他居然能在战斗中短时间内看穿这点，而且毫不犹豫地将性命赌在没有确证的事情上。

再加上无法理解的是——

「那火呢？」

「砍了。」

听到这极为简洁，无可奈何的回答，八重傻眼地叹了口气。

大概不是在说谎吧。他的回答就是如此堂堂正正。接受这个回答的同时，八重的脑海一角突然想起一句话。

那是八重曾经认为派不上用场，而丢到远方去的话——

『——老爸很强。强得不得了。你和阿尔德巴兰那家伙应该也很强，但我还是觉得老爸比较可怕。这就是所谓的「剑鬼」。』

虽然亨克尔的个性别扭，但他的评价是正确的。

虽然无法认同他比阿尔强或可怕，但至少比八重还要恐怖。

——这时候，承认这点的八重・天膳有个误算。

那就是亨克尔的意见，情报的可信度只有一半。

威尔海姆的本领，比八重调查过的白鲸战、讨伐「怠惰」战，以及水门都市防卫战时还要高超。

虽然八重无从得知，但此时的威尔海姆・托利亚斯的剑力，已经逐渐逼近现役时代的最高峰——战胜『剑圣』的那个时代了。

因此，跋利耶尔别邸中『红樱』与『剑鬼』的战斗——

「——喝啊啊啊！！」

以剑闪阻止了舞蹈的完成，将红色樱花的本体染上鲜血的『剑鬼』获得了胜利。

** 第三章 「幼子的话语」

1

双剑划出十字，对敌人造成决定胜负的剑伤。

威尔海姆全身上下都是不浅的伤口，鲜血直流，但他对自己的剑闪——不成熟的剑技却难掩焦躁。

「——太弱了。」

从咬紧的牙关深处吐出的，是对衰老的自己的失望与愤怒。

随着年龄增长，老迈的自己是多么不中用，令人想掩面叹息。

如果是诗人或艺术家，岁月会直接化为知识和技术，巧妙的言词和画笔会让他们达到年轻时无法企及的高峰。

可是，剑士没有那种东西——衰老无法成为养分。

实际感受到衰老的岁月，是无法辩解的劣化，力量、技巧和速度都跟最巅峰的时候无法相比。

这点令他焦躁——只能说是焦躁。

同样的焦躁，至今为止已经品尝过好几次。

身为王国近卫骑士团团长，决定从最前线退下时也是。

妻子被白鲸夺走，为了报仇而耗费了十四年，却只能用衰老的剑去挑战最重要的仇敌，被迫意识到自己的衰老时也是。

而现在，威尔海姆心中焦躁难耐的感觉，毫无疑问是至今为止的人生中品尝过的所有焦躁感中最大的——在「亚人战争」中，他第一次知道特蕾西亚是「剑圣」，意识到自己远远不及她时，感受到的焦躁感。

太弱了。实在是太弱了——弱到该死。

在名为强大的真理世界中，弱小是不可饶恕的罪。

在这个世界中，借口是行不通的。只有强与弱，仅此而已。

才能、怠惰、疾病、衰老，在站上竞争强弱的擂台时，都没有意义。

这是当然的。剑不会选择使用者——钢只会回应。

那么，使用者不被允许找借口，是理所当然的——不，这个世界中，也有选择使用者的「剑」。

而那把「剑」的主人，正是站在无法找借口的世界顶点之人。

——而那个存在，正是无法用衰老作为借口的威尔海姆・特里亚斯，无论如何都必须亲手战胜的对手。

「————」

威尔海姆的自我评价暂且不论，这场战斗中，他发挥出了这几十年来最接近全盛期的剑技，而可怕的忍者则被打落到了地面上。

在与威尔海姆交手过的忍者中，她毫无疑问是最强的。

虽然无法想象少女为了达到这个高度，究竟积累了多少修炼，但胜负的世界中没有努力奖——这就是剑最为残酷的地方。

即使比任何人都要爱剑，剑是否会回应自己，也与爱情的深浅和大小没有任何关系。

不如说，爱得越深，爱得越多，当知道自己的爱没有得到回报时，内心就会产生裂痕，然后崩溃到无法挽回的地步。

而一旦崩溃，就再也无法恢复原状了。

「————」

威尔海姆将这份感伤放在脑海的角落，即使胜负已分，他也没有放松警惕。

他看到坠落的少女身体没有被切碎，而是被一根残留的丝线吊在空中。血液从倒吊的少女身体中滴落，但那纤细的身体并没有被一分为二——这就是『剑鬼』警戒的理由。

在赌上性命的战斗中，双方都没有手下留情的余地。

威尔海姆没有因为对方年轻、性别、情况，而对挥下的剑有任何斟酌。

毫无疑问，他挥剑时是打算斩断对方的性命。尽管如此，少女的身体却没有被一分为二，这证明了少女用某种方法避开了致命伤，而不仅仅是威尔海姆的剑技不成熟。

恐怕是——

「——丝线吗？」

少女使用了手脚所有的手指，在地下事先布下了银丝。

这种需要稀世才能和呕心沥血的修炼才能掌握的术技结晶，既可以成为撕裂对手的利刃，也可以成为封锁敌人动作的锁链，甚至可以紧紧缠绕在身体上，起到防御剑击的铠甲作用。

在最后一闪的时候，少女做出了保护头部和心脏的动作，威尔海姆用尽全力横扫了她空荡荡的身体，但那其实是她刹那间的诱导。

对于在瞬间的判断中留下一线生机的少女，只能说她做得漂亮。另一方面，威尔海姆对于自己被她的策略所骗，再次感到羞愧。

话虽如此，威尔海姆也希望少女能活下来。可以的话，希望能活捉敌人，这是己方的共同见解。

「——呜。」

被吊在空中的少女，纤细的喉咙发出微弱的呻吟。

威尔海姆将剑插在墙上，缩短距离准备回收少女。或许是察觉到他的气息，少女的眼皮颤动，红色瞳孔静静地映照出威尔海姆。

少女恢复意识，让威尔海姆的警戒更加强烈。不过，从剑击的手感可以确定她不可能反击。

挥剑五十年，赌上性命的战场和夺走的性命数也数不清。

流下的血和斩杀的生命重量不容置疑，告诉威尔海姆对方的剑伤有多深。

「————」

因此，不管少女用视线暗示自己有多少王牌来牵制，威尔海姆都看穿那是她迫不得已的虚张声势，没有停止接近她。

「虽然我这边也不清楚详细情况，但为了你自己好，还是别再做无谓的抵抗了。阿尔阁下很快就会被我们抓住的」

威尔海姆看穿了少女的虚张声势，牵制着她，不让她继续抵抗。

威尔海姆也听说了，少女是和普莉希拉・跋利耶尔的骑士——阿尔共谋的其中一人。普莉希拉在佛拉基亚帝国殒命的悲剧，以及阿尔因此而犯下凶行的推测，他都听说了。

阿尔失去所爱之人的痛苦，威尔海姆感同身受。

他能理解那种身体被撕裂，内心被撕碎，灵魂被无尽的无力感灼烧的感觉——而且，如果再这样下去，菲利斯也会品尝到同样的痛苦。

「……必须尽快救出她」

对威尔海姆来说，库珥修・卡尔斯腾和菲利斯——菲利克斯・阿盖尔这两人，毫无疑问是他的大恩人，是无可替代的存在。

虽然讨伐白鲸一事是利害一致的结果，但库珥修原本是王选的最有力候补，她没有理由率先讨伐危险的『雾之魔兽』。

昴预测到了白鲸到来的时间，特蕾西亚的战友库乌德们为了替她报仇而聚集起来，还有帮助他们的『铁之』，都对他有莫大的恩情。

但是，对威尔海姆来说最大的恩人，果然还是库珥修和菲利斯两人。

正因如此，他不能让委身于负面激情的阿尔破坏这个世界。虽然同情他，但这份同情绝对无法胜过大恩。

——必须挫败阿尔的企图。

这和阻止那些支持他的企图，无论出于何种理由都要协助阿尔的人们是同义的——无论其中有什么人。

这个忍者少女也是必须从他的企图中排除的齿轮之一——

「……太差劲了。」

她无力地勉强维持着生命，用微弱的呼吸说出这句话。

被吊在空中的少女似乎领悟到视线的虚张声势对威尔海姆不管用，毫不掩饰地对自己感到失望。

那是——

「不仅没能派上用场，还扯了后腿。」

如果不是被吊在空中，她或许会流下眼泪，这是发自内心的悔悟。

如果这份悔悟，只是因为与威尔海姆的战斗胜负已定，威尔海姆或许会解除最后的警戒。

但是，不对。少女低语后，有声音响起——从头上的洞穴外。

咚加斯顿，有什么沉重的东西倒地的声音。

接着——

「——呜、呃！」

听到的惨叫，是留在头上的房间的菲鲁特发出的。察觉到的瞬间，威尔海姆以刺在墙上的剑为支撑，再度蹬墙跳起。

重复三角跳，跳出洞穴外的威尔海姆，当场瞪大眼睛。

「～～！」

双脚乱踢，浮在空中的菲鲁特拼命用手指抓脖子。

脖子被线吊着。但是，操纵线的少女应该没有余力才对——威尔海姆看到房间角落，一部分墙壁倒下，理解到那是刚才声音的真面目，也是吊起菲鲁特脖子的机关。

机关很简单。在菲鲁特的脖子上绑线，事先斜向挖空的墙壁随着时间经过倒下，拉扯的线将她吊在空中，是时限式的陷阱。——这样一来，不论胜负，与少女的生死无关，菲鲁特都会被吊起来。

「现在立刻——」

威尔海姆拿着剑冲向菲鲁特，准备救她。

线虽然强韧，但没有操纵者的话强度就不及剑击。要救出菲鲁特很简单，而且，设下陷阱的少女也逃不了。

原本她会设下时限式陷阱，是为了在与威尔海姆的战斗拖长时，自己主动分散他的注意力，趁机逃跑。

然而，陷阱发动前胜负已分，少女受了无法逃跑的重伤。

陷阱没有给她偷袭的空隙，也没有逃跑的余裕。要说的话，菲鲁特是被连累的倒霉鬼——威尔海姆这么想。

这时候，威尔海姆的思考很自然，没有人能责备他。

毕竟，这个时间点上，除了王国颠覆危机的元凶一伙人，没有人正确掌握菲鲁特被吊起来的意义。

只不过——

『岂止没派上用场，还扯了后腿。』

吊在半空中的少女悔悟的话语，要是有时间推敲其真意，或许会是不同的结果。少女的悔恨并非败北本身，而是在那之后。

她悔恨的不是败北，而是之后的「保险」。

「——逃。」

威尔海姆的剑击即将斩断线的前一刻，被吊起来的菲鲁特拼命地吐出沙哑的气息，拼命地诉说某件事。

那不是「救我」——而是「快逃」。

「————」

威尔海姆的眼睛确实捕捉到那句话后——「龙」的巨腕便贯穿跋利耶尔别邸的墙壁，毫不留情地从侧面痛殴威尔海姆。

2

——潜入王都露格尼卡，解放被囚禁在监狱塔的「暴食」大罪司教。

表明这个岂止荒唐无稽，只会让人觉得脑袋有问题的方针后，阿尔德巴兰便独自迅速潜入都市，这让亨克尔感到五味杂陈。

阿尔德巴兰的目的，其根本之处并没有和亨克尔共享。

看来跟随他的八重所获得的情报量也和他差不多，但是和亨克尔为了回报而协助阿尔德巴兰不同，八重之所以参与这个计划，似乎是因为对阿尔德巴兰的扭曲执着。

「扭曲的执着吗……真亏她能厚颜无耻地说出这种话。」

八重对阿尔德巴兰抱持的，既非爱也非憎恶的不可解感情。亨克尔用自己心中的标准衡量并如此评价，让他感到非常寒冷地自嘲。

说到底，什么才是直率，什么才是扭曲，到底要以什么为标准来衡量呢？

如果能将八重的执着评价为扭曲，那么自己的执着又如何呢？亨克尔为了寻求让沉睡的妻子苏醒的方法，最后成为国贼之一的执着。

「——！」

混杂着自责与自嘲的自问自答，让亨克尔感到头痛欲裂，他用手指按压太阳穴，试图掩盖疼痛。

如果是平常，这种没有答案的迷雾般的疼痛，酒是最好的特效药。虽然酒无法治愈疼痛，但能让人暂时忘记，麻痹。

即使知道这样不健康，亨克尔也只有在酒带来的酩酊感中，才能正常地睁开眼睛。

但是现在，他无法为了寻求掩盖疼痛的酩酊感而喝酒——因为，那个时刻或许终于到来了。

他追求了近二十年，渴望到灵魂都快要碎裂的夙愿，或许终于要实现了。

「——卢安娜。」

闭上的眼睑内侧，嘴唇编织出心爱女人的名字，她的身影随之浮现。

从相遇时起就未曾改变，年轻、可爱又惹人怜爱的妻子，从她开始沉睡的年龄起就一直未曾改变。并非回忆没有更新，而是她的睡脸真的无视了所有岁月，一直保持着从前的样子。

他想再次看到她的眼睑睁开。想将她的嘴唇编织出声音，与惹人怜爱的容貌相反，一秒都静不下来，活泼的她深深烙印在自己的眼中。

如果能实现，亨克尔就不再对自己的人生抱有任何期望——

「我……」

『——啊～老爸，你又在想那些负面的事了吧？你给人的感觉就是这样哦？』

突然，正下方传来的声音让亨克尔屏住了呼吸。对着用手指按压太阳穴的亨克尔说话的，正是张开翅膀的“神龙”。

与那庄严而强大的存在感相反，说话轻浮至极的“神龙”，明明看不到坐在自己背上的亨克尔的表情，却敏锐地察觉到了他的心思。

面对“神龙”那算不上关心的提问，亨克尔不知如何回答。

这也是当然的——对亨克尔来说，像这样和“神龙”两人独处，简直就像好东西被吊在鼻子前面的飞龙和水龙一样。

为了让沉睡不醒的卢安娜・阿斯特雷亚醒来，亨克尔摸索了各种手段，无论是魔法还是咒术，无论是“米提亚”还是魔造具都尝试过。而这些希望都被断绝的亨克尔，最后的希望就是“龙血”。

只要有能够驱除各种病魔，为干涸的大地带来丰收的至宝，就能让卢安娜醒来——而那个至宝，就在亨克尔只要拔剑就能触及的位置，脉动着，主张着自己的存在。

不过——

「……别管我。别来管我。」

『别这么不爽嘛。我明白你父亲着急的心情，也知道和我在一起很辛苦。所以，我可是有好好考虑过，让令尊不会太急躁哦？』

「考虑？你该不会要说这就是你的考虑吧？」

『我就是这个意思，难道不行吗？』

『神龙』毫无恶意地歪着头说道。他所指的，是亨克尔他们现在的位置——也就是在大地遥远的上方，云层之上。

亨克尔坐在『神龙』的背上，身处高高的天空之上。『神龙』似乎在操纵风，所以没有摇晃或强风，除了鳞片的硬度之外，环境相当舒适。但是，『神龙』所说的考虑，应该不是指这个舒适感。

万一亨克尔拔剑，『神龙』会维持在无法得救的高度。

『就算你挖出我的心脏，得到我的心血，要是我们一起摔死就没意义了。所以，就算只有我们两个，令尊在这里也不能对我出手。怎么样？这个主意还不错吧？』

「别自己说啊。首先，这既不是关心也不是算计。你的计划也可能失败，我可能不顾后果地拔剑……」

『不，那不可能。你父亲是个正经人』

「什……」

『正经的人会好好考虑恐惧。我至今为止见过各种各样的疯子，但你父亲不会变成他们那样』

面对『神龙』肆无忌惮的神谕，亨克尔嘴巴一张一合，一时无法反驳。他的耳朵最先变红，是因为愤怒还是羞耻呢？

如果是前者，那他没有不顾后果地破口大骂，就证明了『神龙』的判断是正确的。

如果是后者，那他被责备后心里有数，也证明了『神龙』的判断是正确的。

也就是说，当他的耳朵变红时，亨克尔就已经输了。

「你说我正经……」

亨克尔加大了手指的力道，对『神龙』的评价发出嘶哑的声音。

正经这个词用来形容现在的亨克尔，实在是太讽刺了。『神龙』是瞎了吗？正经的人怎么会变成自私自利的国贼呢？

亨克尔既不正经也不正派。他不是那种可以用市井百姓普遍拥有的善良来证明的人。

「所以普莉希拉小姐去世的时候，我接受了阿尔德巴兰的邀请。」

介入佛拉基亚帝国的国难，殒命的普莉希拉・跋利耶尔。

亨克尔的立场让他无法说出自己曾向她宣誓效忠。自己和她的关系，只是利害一致的共斗关系——就连这点，如今也无法得知普莉希拉从亨克尔身上看出了多少利用价值。

只不过，虽然亨克尔没有向普莉希拉宣誓效忠，但他毫不怀疑她拥有得到王座，作为王国新领导者引导国民的王者资质。

优秀的才能和洞察先机的聪明才智，以及美丽的容貌，都是作为女王的出色资质。

普莉希拉有成为亲龙王国露格尼卡女王的资格——而当她实现这个目标时，亨克尔应该会从她那里得到「龙血」作为奖赏。

这个希望，随着普莉希拉的性命一起在那个帝国消散了。

打从心底感到遗憾。——没能得到「龙血」自不必说，普莉希拉统治露格尼卡王国的未来没能实现也让他遗憾。

然后，阿尔德巴兰向失去希望，一蹶不振的亨克尔伸出了手。

只要协助自己，就能得到「龙血」，作为代价要与世界为敌。——对亨克尔来说，这是过于甜美的提议。

近在眼前，本应可以得到的希望却失去了，这很痛苦——而且，只差一步希望之灯就会熄灭，这对亨克尔来说是第二次了。

因为自己愚蠢的失败而错失机会的第一次，那股烧灼全身的无力感难以忘怀。

正因如此，亨克尔这次才肤浅地抓住可能性。

这种人很正经？「神龙」的指摘根本是大错特错。

『又不高兴地缩进壳里了啊。虽然我这么说很奇怪，但中年男人的别扭性格可没人会喜欢哦？』

「……那种事，事到如今还用得着说吗？」

『真是别扭啊……唉，因为真的是回力镖，所以我不再多说了。』

就连耸肩的动作，「神龙」的庞大身躯都显得夸张。

那令人毛骨悚然的像人类一样的动作，让亨克尔发现了自己和阿尔德巴兰的共同点，他无视了因为无法理解而加剧的头痛。

不被任何人所爱。这是亨克尔所期望的。

自己从来没有被爱过，亨克尔还没有蠢到会说出这种自暴自弃的话。亨克尔是被爱着生下来的，而且爱着这样的亨克尔的人也不在少数。

不仅没能回报那些爱，还背叛了他们，亨克尔在雾中前行。

家人也好，为数不多的朋友也好，有机会并肩作战的对手也好，亨克尔・阿斯特雷亚一个接一个地牺牲了他们，亨克尔・阿斯特雷亚在前行。在前行。

『——说起来，我们俩独处的机会也不多，我有件事想向你父亲确认一下』

「你就不能安静地等着吗？」

『我是无法忍受沉默的类型。可能是因为我总是喋喋不休吧』

虽然对「神龙」的生态一无所知，但对方并没有说太多，亨克尔也不想知道。不管怎样，对方都是在事情结束后为了心血而死的对象。没有必要特意给自己增加罪恶感的理由。

而且，虽然对方是在关心自己，但话题的走向发生了变化，这倒是值得庆幸。

如果能聊些别的，或许能稍微缓解一下头痛。

「那么，恕我冒昧，『神龙』大人想问我什么？」

『啊，不是什么大不了的事。你父亲不是特别结实吗？我想知道他为什么这么结实』

「————」

『咦？我做了什么吗？』

听到『神龙』装傻的话，亨克尔咬牙切齿。

头痛加剧，证明了亨克尔之前的计划落空了——虽然期待对方改变话题，但证明了对方并没有改变话题。

「————」

亨克尔沉默不语，低头看着自己的手掌，叹了口气。

『神龙』的问题是关于亨克尔的身体。当然，是关于自己的身体。亨克尔知道自己身体的异常，也知道原因——这是亨克尔犯下的众多罪行中，罪孽最深重的惩罚。

卢安娜・阿斯特雷亚的沉睡——包括亨克尔在内，阿斯特雷亚家的分裂毫无疑问始于这件事，但决定性的事件是十五年前发生的事。

特蕾西亚・范・阿斯特雷亚在白鲸讨伐战中出阵，以及在战斗中『剑圣』的加护转移所导致的『剑圣』交替剧，还有特蕾西亚的死。——而这一切的契机，就是王弟佛鲁德・露格尼卡的女儿绑架事件。

在那起事件的夜晚，亨克尔犯下了不可饶恕的背叛，以及让背叛变得毫无意义的最糟糕的失败。——而天罚，就是亨克尔现在的惨状。

「我有什么理由要特地告诉你……」

『哦，你这么说吗？那我如果不告诉你，而直接去向另一个我告状，说你父亲不合作，威胁他违背约定的话呢？』

「你……！」

『开玩笑的，开玩笑。不想说的事情，我和你父亲都有成千上百个吧。』

「……上百个也太多了吧。」

『神龙』的玩笑听起来一点也不轻松，亨克尔只能虚弱地回答。

虽然他说成千上百个，但亨克尔所背负的东西一只手就数得完。而那一只手数得完的数量，就足以让他崩溃。

尽管如此，他还是把裂开的东西拼凑起来，拖着紧绷的东西，想着再一下、再一下，终于——

『————』

「——？怎，怎么了？发生什么事了？」

亨克尔感觉到空气的微小变化，向『神龙』搭话。一瞬间，他犹豫着要不要像平时一样叫它波克肯尼卡，最后还是选择了最保险的叫法。

但是，『神龙』无视亨克尔的犹豫，看向了下方——云层之下的王都。

然后——

『——抓紧了，老爹！』

「呜噢！？」

瞬间，亨克尔被从正上方吹来的暴风压住，像下跪一样趴倒在『神龙』的背上。他连因为突如其来的冲击而屏住呼吸的时间都没有，『神龙』就带着趴在背上的亨克尔，一口气从王都的天空上冲了下去。

在阿尔德巴兰攻略监狱塔的期间，他一直藏在云层之上，现在全都白费了——也就是说，现在产生了这么做的必要。

「呜，啊，啊，啊啊啊啊……」

脑袋转不过来，无法呼吸，也看不见周围。

亨克尔只是因为强烈的压迫感而发出分不清是惨叫还是呻吟的声音。『神龙』载着这样的亨克尔，以令人难以置信的速度到达了目的地——刹那间，狂暴的龙挥舞前臂，伴随着强烈的破坏声，建筑物的墙壁被击穿。

没有任何说明的暴举，不知道目标是什么的破坏声搅乱了亨克尔的脑。

当然，被『神龙』一击这种不得了的悲剧袭击的建筑物被破坏得惨不忍睹，里面的东西也被龙爪撕裂——

『——真的假的！』

那是，实行无情破坏的『神龙』纯粹的惊愕之声。

『神龙』瞪大黄金双眸，视线投向自己手臂挥舞的建筑物——被金色装饰得近乎低俗的豪华宅邸的房间。它窥视被毫不留情的攻击打飞屋顶和墙壁的房间，对结果感到震惊。

那是当然的吧——比这世上几乎所有刀剑都要锐利强韧的『神龙』的龙爪，被切断、剥落，化为粒子。

而做到这件事的，是谁呢——

「——父亲，大人。」

在半毁的建筑物中，将双剑交叉成十字，刚刚接下『神龙』龙爪的存在。

——『剑鬼』威尔海姆・范・阿斯特雷亚，就在那里。

3

「——感谢。」

一边意识化解龙爪，勉强卸除冲击的双臂的麻痹，威尔海姆一边向告知威胁接近的菲鲁特道谢。

脖子被丝线缠住，悬在半空中的菲鲁特——在性命危在旦夕的状况下，她没有向威尔海姆求助，而是命令他做好准备。

因此才能在千钧一发之际，来得及采取防御姿势。

『不，一般来说，就算来得及也挡不住吧！』

威尔海姆的感慨，让站在宅邸外的巨躯发出粗鲁的声音——那恐怖又神秘的存在感，是许多人光看到就会跪拜的绝对强者。

——「神龙」波克肯尼卡的威容，从外头窥视着宅邸内部。

「咳、咳……我也赞同那条『龙』的意见。我叫你逃走，不是叫你干掉它……咳。」

痛苦咳嗽的菲鲁特，竟然也赞同波克肯尼卡的意见。

方才趁乱从悬空状态解放的菲鲁特——不，威尔海姆的眼睛，正确地捕捉到发生的事。

菲鲁特没有借助威尔海姆之手，而是偶然得救。

「没想到，您竟然救了菲鲁特大人？」

『立场上我不好说YES或NO，不过要是现在说YES，菲鲁特妹妹也会正式成为我们国贼团队的同伴吧？』

「才不是同伴。不过，飞过来救我倒是没错……」

声音中还留有被吊在半空中的余韵，菲鲁特摸着自己的脖子回答。波克肯尼卡也没有否定。看来「龙」是用某种方法察觉到菲鲁特的困境，飞过来救她。

也就是说，那个忍者少女是看准这点，才用丝线缠住菲鲁特的脖子。

话虽如此——

「对本人来说很苦涩吧。毕竟，来到这边就代表……」

『无法帮助那边的我。』

「嗯——话说回来，你的说话方式变了很多呢。和四十年前瞥见你的时候简直判若两人……不，判若两龙。」

『有句话说士别三日当刮目相看。四十年可是很长的岁月。夏天会让女孩子变魔法哦，老爷爷。』

「原来如此。」

虽然点头，但威尔海姆无法接受波克肯尼卡的变化。不过，现在没有追究其变化的余地。

比起这个，还有更优先的事。——闯入的波克肯尼卡并非单独一人。龙的背上似乎载着某人。那个人之所以一直保持沉默，隐藏气息，不是为了给威尔海姆出其不意——

「——在我面前，连露脸都不敢吗，亨克尔。」

「——」

威尔海姆的呼唤，让对方的胆怯透过空气传达过来。

就算低下头，压低声音，努力隐藏自己的存在也是徒劳。威尔海姆已经知道，帮助与王国为敌的国贼阿尔的党羽中，有亨克尔在。

阿尔的所作所为，足以让王国陷入存亡的危机。

在如此危机的状况下，身为前近卫骑士团长的威尔海姆不可能不挥剑。就算撇开这些事情不谈，威尔海姆之所以会下定决心率先握剑，理由就在于亨克尔的存在。

「我猜，你大概是被说只要帮忙，就会通融『龙血』给你吧。你打算用那个让自己的妻子……卢安娜苏醒。如果是这样，你太肤浅了。」

保管在王城的「龙血」，确实寄宿着绝大的力量。

只要有那个王国至宝的力量，或许就能让原因不明持续沉睡的卢安娜・阿斯特雷亚苏醒。

但是——

「阿尔阁下……不，成为逆贼的阿尔那个男人，会遵守约定吗？他背叛了自己侍奉的主人普莉希拉・跋利耶尔大人留下的东西，甚至欺骗了关心自己的人，企图引发事端。为什么，他会只实现你的愿望？」

『不是，我也知道你会怀疑哦？但是，那也太片面了——』

「露格尼卡的尊贵之龙啊，现在我并没有在和你说话。」

『唔……』威尔海姆用态度表示波克肯尼卡不在他的眼中，波克肯尼卡沉默了。威尔海姆继续对沉默的另一侧，躲在龙背上的对象说。

「怎么了，什么都说不出口吗？是被说中了，还是根本没想过？是啊，你从以前开始，遇到讨厌的事就转头、塞住耳朵，只会逃避。所以到了现在，除了对自己有利的事以外，其他都不看——」

「——吵死了吵死了吵死了！」

「——」

「随心所欲……随心所欲地胡说八道……！我为了卢安娜做了什么，老爸你有什么资格说我！！」

随着这声呕血般的怒吼，波克肯尼卡背上的身影站了起来。

那张熟悉的脸和熟悉的声音，颤抖的手指指着自己，威尔海姆深深叹气。那是带着无奈、失望，以及些许安心的叹息。

安心的理由有很多。被说得这么难听，他还有没有抬起头来的斗争心？和国贼联手却藏身不出，他有没有做出这种卑鄙的行为？

不过，总括来说——

「……终于肯露脸了。」

「呜……」

「然后呢？除了大声嚷嚷之外，没有其他反驳吗？你和那个男人联手的理由，和我想的一样吗？如果是的话，为什么你会觉得那家伙会实现你的愿望？你的心愿被磨耗殆尽，所以看不清现实了吗？」

「我……」

面对威尔海姆的质问，龙背上的身影——亨克尔低下头。

方才的怒气不知道消失到哪去了，他明显消沉。而亨克尔在威尔海姆面前畏缩，也不是第一次了。

从很久、很久以前就是这样——从发誓成为骑士，威尔海姆将爱剑「阿斯特雷亚」托付给他的时候开始，一直都是这样。

「大叔的目标是『龙血』，目的是叫醒睡着的女人，这点不会错。」

代替沉默的亨克尔回答威尔海姆疑问的人是菲鲁特。

她放下摸着脖子的手，当场站起来。明明是比在场任何人都无力的存在，却用让人感受不到这点的表情说：

「这是大叔亲口告诉我的。至于他和头盔男做了什么约定，我也没问那么多……不过感觉他没说谎。」

「——」

「不过，这只是我的感觉，没有任何保证。」

「——不，感谢您代替不肖子回答。还有，让您参与这种事，实在很抱歉。」

「后面那句道歉就免了。大叔也说过，那只是做法和我不一样，不是好或坏的问题。」

尽管被卷进来，自己也遭逢不幸，菲鲁特的回答却没有愤怒。

那堂堂正正的模样，让威尔海姆确信她有王者器量。毫无疑问，菲鲁特和库珥修一样，都是龙历石选中的五人之一——明明是这样，带来龙历石的「神龙」却像这样阻挡在王国的危难前。

「你像这样降临地面，毫不留情挥舞爪子的模样，想必很多人已经看到了。亲龙王国的地盘动摇，你有自觉吗？」

『嗯，我打从心底觉得抱歉。不过啊，就算亲龙王国变回狮子王国，也比世界毁灭要好得多。』

「你的叛意十足，我认为足以构成世界毁灭的理由。」

至少，露格尼卡王国会剧烈动荡是无庸置疑的。

那股动荡，可能会让王国岌岌可危的地盘出现裂痕，产生的地裂会毫不留情地吞噬许多事物。假如，阿尔和波克肯尼卡的行动，是为了对抗连地裂都能超越的某种事物——

「那不是只靠几个人就能决定的事。更何况，连自己脚下都看不见的不成熟者也是那几个人之一，实在难以理解。」

『这是来自崇高神龙的灵验托宣哦？』

「那么，就像过去那样，现在这个时候，拯救痛苦喘息的众多人民吧。在那之后，再和更多人一起拯救世界就好。如果办不到的话——」

『办不到的话？』

「——只能认为你和我那愚蠢的儿子一样，被甜言蜜语操控了。」

说完，威尔海姆重新握好双剑，与「神龙」波克肯尼卡对峙。

初击的麻痹感从手上消失。但是，如果只有一回合是那样的话，只要交手三回合剑就会被夺走。要完全躲开，或是化解，都得更加提高警觉。

『唉呀呀……菲鲁特小姑娘，别动哦。我可没自信能手下留情。』

「差不多，我也不打算听你那套说法了。自从罗姆爷彻底骗了我之后，我就一直很不爽。」

「那么，现在暂时要麻烦您忍耐了。」

『没错没错。』

「不要只在对待我的时候才这么要好！」

菲鲁特怒吼，交互瞪着威尔海姆和波克肯尼卡，吐出舌头。

威尔海姆将对菲鲁特的注意力降到最低，将注意力集中在波克肯尼卡的一举一动上。对方也是前来救援忍者少女的立场。其身影已经被许多人目击，随着时间经过，骚动会扩大，行动会变得困难——所以，这里也要短期决战。

『再怎么说，我好歹也是传说之龙哦？寻找交战以外的路不是比较聪明吗？』

「很不巧，我正好在想必须超越传说。虽然很抱歉，但请陪我一战。」

面对波克肯尼卡的牵制，威尔海姆毫不畏惧地回应。听到这个回答，许久没有说话的亨克尔屏住呼吸，脸颊僵硬。

「老爸，难道……」

嘴唇颤抖，呆愣的蓝色瞳孔映照出威尔海姆。面对儿子有所察觉的眼神，威尔海姆静静地闭上眼睛。

在波克肯尼卡面前，这举动实在太过无谋且毫无防备。但是，彼此的战意中确实有股信赖，相信对方不会趁隙攻击。

委身于那份信赖，威尔海姆闭上的眼睑里，闪过遥远往日的后悔。

——阴天的墓园，空无一物的墓碑。沉浸在悲伤中的众多出席者，以及国王陛下赞扬为使命殉身之人的存在方式的话语。没有出席葬礼的儿子，以及没有力气带他出席葬礼的憔悴的自己。

然后——

『——没关系的，祖父大人。祖母大人去世的时候，她还不是『剑圣』。所以，『剑圣』并没有输』

『因为，『剑圣』是不能输的。父亲大人是这么说的』

『所以，不必叹息，阿斯特雷亚家会平安无事的，祖父大人』

「——只是，幼童的话语」

拔出『龙剑』的资格，与加护一同继承的幼童，毫无恶意的话语。

威尔海姆详细地回想起那天的后悔，睁开眼睛，看向龙——正如自己所说，是与传说同名，曾经拯救过王国的『神龙』。

在王国存亡的危机，人心惶惶的状况下，明知自己不谨慎。

但是，如同拯救王国，拯救世界一般，威尔海姆有必须用剑完成的重要使命——只有用剑才能完成的重要使命。

威尔海姆不知道其他方法——让『剑圣』恢复成人的方法。

因此，他要让这把剑发挥出与过去相同——不，是比过去更强的剑力，挑战龙。

为了战胜在那之后等待着他的，改写传说的传说。

「——『剑鬼』威尔海姆・特里亚斯」

『——『神龙』波克肯尼卡』

在报上名号的同时，双方动了起来——剑光与龙爪，将声音远远地甩在了身后。

4

——这正是，传说中描述的战斗的一节。

「————」

『剑鬼』的双剑舞动，迎击的『神龙』的龙爪卷起暴风。

龙是所有生命的最上位，作为顶点生物而生，其中拥有突出力量的『神龙』，其爪，其牙，其鳞，都是应该被称为天然神器的物品。

每当蕴含着绝大力量的神器挥动，风就会发出临死前的惨叫，天空会被扭曲，世界会带有热量，命运会被编织。

不管是爪还是牙，只要被直接击中一次，战斗就不可能继续下去。

『————』

『剑鬼』有一个方法，能让龙无法完全发挥出那可怕的神器。

『神龙』与『剑鬼』相见的原因，是拥有与『狮子王』系谱相同特征的少女的危机。在战斗开始的宅邸一室，那位少女没有压住被深处刮起的风吹动的头发，而是目不转睛地注视着战斗。

何等胆量，何等勇气，那挺直背脊的模样，正适合拥有王器——『剑鬼』将那位少女护在身后，站在『神龙』引发的破坏会波及她的位置。

这样一来，对少女寄予非比寻常的关心，害怕她失去光辉的『神龙』就无法发挥力量，『剑鬼』逼近的死亡脚步声也会远离，能够稍微缓和敌我之间作为生物的绝对差距。

因此——

「————」

『剑鬼』离开将少女护在身后的位置，主动拉近与死域的距离。

他将自己的身体暴露在狂暴的破坏与扫灭的风暴中，将双手紧握的两把钢当作救命绳，投身于一旦踏错就会丧命的终焉绝壁。

利用战场的优势，将对手的感情当作弱点，能够逐渐接近胜利。

但是，那太不识趣了。在谈论识不识趣之前，那是无礼至极又无利无益的行为。

以技术而非剑力弥补不足，偷取胜利，那种胜利在此时此刻有什么价值？

『————』

——『剑鬼』也是在战场中生存的男人。

为了生存的战斗，只有胜利者与生者能够讲述的历史，无法成为借口的败北与战死，这些事情只有沾满灵魂的血渍重量能够证明。

但是，现在这个时刻不同——不，从今以后，『剑鬼』握着剑，以那把钢与某人对峙的所有战斗中，夺取的胜利都没有意义。

以剑力制伏最必须战胜的对手。

在那个过程之中，『剑鬼』没有时间绕远路。如果要让只能衰老的这副身躯与过去相同，成为钢，就只能让灵魂持续浸泡在灼热之中。

「————」

剑风呼啸，龙爪被剥下、砍飞，在空中飞舞。

太狭窄了。不管是挥剑，还是『神龙』要完全使用尾巴与牙齿，这个战域都太狭窄了。

『剑鬼』的脚跟爆炸，剑光超越风加速，刺进『神龙』的胸口，空间爆炸。一次、两次，突刺与剑击连续，爆炸的光芒连锁。

龙鳞的硬度，受到个体保有的玛那总量大幅左右。

愈是强大且长命的龙，愈是健壮且强韧，如果是最上位的『神龙』的龙鳞，硬度甚至超越金刚石。

『————』

面对那金刚石般的龙鳞，『剑鬼』毫不留情地挥舞着钢，敲击，斩断，刺穿，反复进行着攻击。即便如此，他手中的钢依然健在——『剑鬼』为了达成目的而新准备的双剑『托里亚斯』，是与因缘颇深的『阿斯特雷亚』的名剑出自同一剑工的杰作。

剑柄与手相合，重量与肉体融为一体，剑光与金刚石相击，却不见缺损——

「————」

面对『剑鬼』的猛攻，『神龙』也不是省油的灯，不会一直被压着打。

即便其内心并非原本的『神龙』，但只要毫不犹豫地发挥出地上最强的龙壳的性能，『神龙』就能轻易地实现天崩地裂级别的威势。

这毫无疑问是『神龙』从奥德・拉古纳那里得到的，能够随心所欲地改变世界形态，将理想的结果覆盖到现实，使其成为现实的权利。

『————』

咆哮撕裂天空，龙爪撕裂大地。

龙鳞将『剑鬼』的全力攻击弹回了上百次，其全身释放出的龙气将王都的空气染成『神龙』的颜色，死域覆盖了天地。

尾巴挥舞，从正面击中年迈的『剑鬼』——不，『剑鬼』用剑刺中尾巴躲开，一口气冲上去逼近喉咙。

咆哮迎击，释放的光芒被正面斩断，银光贯穿龙鳞。冲击与清脆的声音，斩光被弹开，刹那间重整旗鼓，『剑鬼』与『神龙』的冲突不断持续。

不断不断不断，彼此向世界发出血之咆哮，持续着——

「————」

展开的翅膀化为刀刃，『神龙』卷起的风之剑岚撕裂王都。

『剑鬼』穿过风，拖着血带，配合其轨迹，描绘出死域的尾巴终于捕捉到了老体。响起破坏的声音，『剑鬼』的身体猛然向后飞去。

是直击——不，『剑鬼』判断无法躲开，配合尾巴的旋转，指尖、脚踝、膝盖、股关节、腰部、肋骨、肩膀、脖子、头顶脱力，将致命的冲击从全身排出，飞去，飞去，飞去——撞进了街道。

一栋、两栋、三栋，『剑鬼』刺剑入地，穿过建筑物，抬起头。战意丝毫没有动摇。这时，『神龙』的气息化为白光逼近。

『————』

剑光一闪，『剑鬼』用剑闪斩断气息的前端，将身体钻进产生的些微空隙，逃过被光烧灼的命运，飞舞至空中。

『神龙』在那里拍打翅膀，龙颚毫不留情地咬向『剑鬼』。

以超越龙爪的强度与锐利为傲的龙牙，打算咬碎『剑鬼』的肉体。『剑鬼』将双手的剑尖对准龙牙，作为不让龙颚阖起的支撑棒。假如将剑尖朝向上颚与下颚，阖起的龙颚就会咬碎性命吧。

不让他那么做的，是拒绝『死亡』的嗅觉——不对，是掌握胜利的贪欲延续了性命。

『神龙』用没有阖起的龙颚捕捉『剑鬼』，放弃用龙牙夺命，发出强烈的舌击，口中空间爆炸从正面打向『剑鬼』的全身。

「————」

『剑鬼』的左右耳朵喷出鲜血，被震破的鼓膜与深处的三半规管摇晃着。

『剑鬼』咬紧牙根，站稳脚步。伸长的龙舌打向他，『剑鬼』的身体被抛到龙颚外——毫无防备地飞向王都的高空。

『————』

在被龙颚捕捉的途中，『剑鬼』被振翅的『神龙』带到空中，被无计可施的自由落体的风蹂躏，一口气、一口气地朝向如果胆子小，光是往下看就会失去意识的高度直直落下。

如果就这样落下，就算是『剑鬼』也不可能平安无事。那是生活在地面上的人类，与被允许以巨大身躯支配天空的龙之间的决定性——

然而，就连在那个决定性的状况下，『神龙』也没有放过『剑鬼』。

「————」

龙大大地鼓起肺部，准备吐息。如果朝正下方的王都释放，将会造成莫大的损害，不杀的尝试将会被打破——不对，正下方的贵族街已经远离人群。

事先将这里设定为战场的某人，让有可能被卷入的人们全部避难，构筑了『剑鬼』与『神龙』的决战场。

『神龙』带着对那手法的佩服与感谢，发出咆哮。

『————』

释放的吐息比刚才更大更热，化为灼热逼近『剑鬼』。

没有翅膀，也没有抵抗重力的方法，『剑鬼』连从正面捕捉那道光都做不到，只能被蒸发——瞬间，『剑鬼』在空中转身，从立足点的方向飞驰而来。

「————」

那是『剑鬼』在飞上天空前，用身体撞穿的其中一栋建筑物，高耸的时限塔在坠落途中倒下，成为扭转身躯的『剑鬼』的立足点。『剑鬼』弯下膝盖，站在塔的侧面，拉紧双剑仰望天空——『剑鬼』与『神龙』的视线隔着吐息交错，刹那间，美丽的剑闪与漩涡状的光正面冲突。

『————』

水面破裂，宛如薄玻璃破裂的声响连锁响起，白光从内侧被切开。

那是『神龙』的吐息。它拥有吞噬冲突的许多事物，剥开其表层，剥下深远之物，使其赤裸裸地暴露在外的威力与权利。尽管如此，『剑鬼』却无视那些被推到眼前的事物，放任它们恣意妄为，剑击切开了光。

——真正纯粹，没有邪物介入余地的剑闪，将一切美丽地切开。

「————」

被切开的吐息呈放射状扩散至地面，将王都的贵族街压平。

成为爆炸中心的塔载着「剑鬼」，以及受到「神龙」保护的红色豪宅，只有这两栋建筑物免于直接被害，除此之外都见识到龙绝大的力量。

被白光余波熏黑的「剑鬼」从崩塌的塔上跳下，拍动翅膀的「神龙」从天空发出敌意，视线在天空与地面交错。

然后——

『————』

「————」

不仅没有用尽，反而涌出的剑气，与压制一切的龙压再度冲突，王都露格尼卡所有活着的生物，无机物有机物全都颤抖起来。

5

『你喜欢花吗？』

在白茫茫的世界里，可以听到背对黄色花田的爱女发问。

世界因龙气而扭曲，威尔海姆将身体挤进涌来的致死之风，挥动双手扛着的剑光，心中有无数思绪在奔驰。

『喜欢上花了吗？』

那是心爱的女人。一眼就被吸引，愚蠢的男人将那股不明所以的感情盖住。

即使如此，关系依旧没有断绝，威尔海姆依赖那个环境，害怕深入，沉浸在非常非常胆小缓慢的时间中，轻视了时间。

『为了保护某人而挥剑，我觉得那样很好。』

被火焰包围的故乡，救了差点丧命的威尔海姆的美丽剑光。

给予不期望挥剑，却被剑所爱的女人挥剑理由的事实，威尔海姆用足以让灵魂焦灼的否定来否定，无数的愤怒充斥着威尔海姆。

对弱小的愤怒，对隐瞒的愤怒，对不成熟的自己的愤怒，愤怒、愤怒、愤怒——

将所有的愤怒斩断、压制，为了将所有的激情寄宿在剑身而献身，威尔海姆终于站在她面前，得到与她交剑的资格。

然后，从可恨的剑神身边夺回心爱的女人，将她占为己有。

『你爱我吗？』

——不，是占为己有，还是被占为己有？正确答案不得而知。

只是，很幸福。很幸运。能够得到的最大祝福，从与特蕾西亚相遇的瞬间开始，直到失去她为止，都持续满足着威尔海姆。

——特蕾西亚的「死」，毫无疑问是一场悲剧。

连道别的话都没好好说，该传达的话也没传达，威尔海姆被叹息与恸哭支配，在失意中看漏了许多事物，犯下过错。

但是，与特蕾西亚度过的日子，对威尔海姆来说很幸福。

那段幸福的时光，真的可以被断定为在两人最后一天以悲剧告终的瞬间，就完全褪色，化为乌有了吗？

就算暂时失去了颜色，真的可以不去期望它再次变得鲜艳吗？

——答案，绝对是否定的。

为了不让特蕾西亚的「死」，她的「生」以悲剧告终，威尔海姆追上了仇人。

然后，如果为了特蕾西亚挥剑，能让那段日子取回颜色的话，威尔海姆便无法停止挣扎，期望同样褪色的光景再次恢复色彩。

狂风大作，凶暴的「神龙」发出咆哮。

威尔海姆将剑尖刺入将世界染成一片白色的「龙」的愤怒中，斩开，视野变得开阔，他看见了在前方吐着血，应该斩杀的后悔。

——阴沉的天空，空荡荡的墓碑，止不住的呜咽与惋惜，祈祷安息的话语。

在为了被爱的她而聚集的众多泪人儿的中心，威尔海姆想不起自己说了什么，传达了什么，选择了什么话语，让特蕾西亚的存在方式深深地刻在他们心中。

他想起的是后悔。威尔海姆强烈、巨大、无法抹去的后悔。

不懂事的幼童，没能和父母在一起的幼童，为了安慰自己而选择的话语，自己却拒绝了，没能接受。

那一瞬间的褪色的天空，大地，人们的表情，自己和幼童——

『——没事的，祖父大人。祖母大人去世的时候，她还不是“剑圣”。所以，“剑圣”并没有输』

「……别说了」

『因为，“剑圣”是不能输的。父亲大人是这么说的』

「求你了，别说了」

『所以，您不必叹息，阿斯特雷亚家会安泰的，祖父大人』

「现在，这里……别再说了」

无力的拒绝的话语，不断重复。

幼童的安慰的话语，不断重复。

然后——

『我是下一任“剑圣”——在祖母大人去世之前，我被授予了这个称号』

「——别再说了！你到底想让我说什么！别让我开口说，都是因为你特蕾西亚……你的祖母才会死！！」

『————』

「别让我……开口……」

褪色的光景中，其他的一切都被抹消，只剩下自己和幼童。威尔海姆将剑刺向那个瞬间，不成熟又愚蠢的自己，然后往前迈进。

没有说出口的话，无法传达给对方。即使心意相通，应该说出口的千言万语、万言万语也无法传达给对方。

同样地，说出口的话，无论以何种形式都会传达给对方。

从中汲取什么，端看接受的一方。

但是，对尚未完成的容器注入超过容许量的水，无法完全接受而溢出，却把过错推给容器，这是多么愚蠢的行为。

褪色的世界，那天的幼童——莱因哈鲁特的脸，想不起来。

那是因为不小心说出不该说的话后，就无法正视他的脸。不是想不起来，而是因为没看到所以不知道。

然后，听到说出口的话的人，不只一个。

『……听说你在母亲的葬礼上责备那孩子。可是，却想见莱因哈鲁特？连该说什么不该说什么都分不清楚的父亲，有资格向那孩子道歉吗？』

『那孩子，是我和卢安娜的孩子……。什么害死了母亲，什么夺走了加护！那都是搞错了！我……我会证明给你看！』

『不是父亲，是我——我，必须去做。』

一旦说出口的话，就无法收回。

威尔海姆对莱因哈鲁特的谩骂瞬间传开，连没出席葬礼的亨克尔都听说了，因此失去了谢罪和辩解的机会。

同时，祖父对孙子的愚蠢斥责也传到家人以外的人耳中，比起丑闻，「剑圣的加护」的继承事实传得更广。

亨克尔绝不让威尔海姆和莱因哈鲁特见面。

莱因哈鲁特照亨克尔说的避开威尔海姆，断绝交流。

威尔海姆被亨克尔和莱因哈鲁特疏远，独自埋头于复仇。

错位的三人关系，在水门都市与特蕾西亚的尸兵交战后再度结缘，然后再次产生决定性的龟裂——如果这是最后，那悲剧就结束了。

但是，威尔海姆选择不让特蕾西亚的『死』、『生』、『人生』以悲剧告终，因此他对于让这段关系以悲剧收场也持反对意见。

然后，对于难以抗拒的命运，除了用剑来唱出异议之外，他不知道其他方法。

——莱因哈鲁特是『剑圣』。

只要他继续背负着不可动摇的使命，莱因哈鲁特和『剑圣』之间的想法就无法交集，让褪色的光景重新染上色彩的机会就不会到来。

所以，威尔海姆・范・阿斯特雷亚——不，从『剑圣』手中夺走剑之人，『剑鬼』威尔海姆・托利亚斯，必须让剑光染上鲜血。

6

——重新来过。那正是传说中描述的战斗的一节。

『剑鬼』和『神龙』的战斗，虽然孕育着各种各样的因素，但还是形成了一进一退的攻防，锻炼出来的钢铁剑技和与生俱来的顶点生物之力相互抗衡。

王都，成为战场的贵族街一带化为平地，崩塌的建筑物和被破坏的道路，诉说着在凡人无法到达的领域中，两者冲突的激烈程度。

身体的大小、立足点的有无、决定胜负的相互较量，剑光和龙气相互抗衡。

人类和龙的战斗，是即使在现今世界，也不知是否能再看到百年一次的贵重死斗，但令人惊讶的是，对「剑鬼」来说这是第二次和龙的战斗。

只能说是他期望踏入这世上最危险的战场，以及掌管命运的伟大存在持续为「剑鬼」准备相称的敌人，这是他的宿业。

从前提条件来说，这场战斗对「剑鬼」压倒性不利。

「剑鬼」的剑击无法贯穿「神龙」强韧的龙鳞，另一方面「神龙」的龙爪和龙牙，只要擦过就能轻易将「剑鬼」的性命从肉体上剥离。虽然「剑鬼」用尽全力持续闪躲，但迟早会到达极限——理论上是这样。

但是，任谁都没想过，浑身是血、满身煤灰、背部烧焦挥剑的「剑鬼」，精疲力尽被「神龙」的爪子抓到的模样。

「剑鬼」鬼气逼人的样貌，光是沐浴在那股浓密的剑气中，就会产生被刀刃架在脖子上的错觉，曾经一度击败「剑圣」的全盛期剑力，否定了理所当然的现实，让观看的人抱持着超乎常识的希望和期待。

——「剑圣」是露格尼卡王国的剑，是希望的承担者。

当那个希望被「剑鬼」击退时，人们应该会绝望地仰望天空。

因为「剑圣」败北了，所以会变成那样是理所当然的。但是，现实却不同。

「剑圣」败北，放下剑时，没有人悲叹，而是祝福。因为新的希望萌芽——打倒「剑圣」的「剑鬼」，寄宿了新的期待。

「剑鬼」只是追求强大，除了像手中的钢一样磨练自己以外，什么都不会。

那个「剑鬼」率直、不向任何人让路的态度，让许多人抬起头，怀抱希望，期待崭新的明天。

现在，这个瞬间，无法想象与「神龙」对峙的「剑鬼」败北的未来，也是同样的道理——「剑鬼」的存在方式，让人看见希望。

只要在剑开辟的前方有期望的景色，就会让人觉得不可能无法触及。

因此，「剑鬼」与「神龙」的战斗陷入胶着，找不到决定性一击的两者，始终在赌上性命的炽烈战斗中，看清对方的长处。

——所以，传说之战的落幕，「剑鬼」与「神龙」无法准备。

「————」

『————』

在化为战场的街道中心，「剑鬼」与「神龙」的视线交错，沉默以对。但是，虽然双方都沉默不语，沉默的性质却不同。

一边是忍耐，一边是惊愕。虽然都是沉默，但后续发展却不同。

「咕」

微弱的呻吟，伴随着大量鲜血，从「剑鬼」口中溢出。

但是，「剑鬼」依然紧握双剑，没有止住溢出的鲜血，而是俯视自己的身体——他看见染血的剑尖从腹部刺出。

从背后侵入的剑刃贯穿「剑鬼」的身体，鲜血流出。那把剑「剑鬼」非常熟悉——当然，因为那是自己曾经爱过的剑。

那把剑的名字是「阿斯特雷亚」，而现在的持有者是——

「——亨克尔」

被涌出的血泡所覆盖，他不确定自己的低语是否变成了声音。

但是，贯穿自己的剑的震动，以及其中包含的意图传达了过来。如果回头，身体可能会被切断，「剑鬼」咬紧牙关，站稳脚步。

背后，那个人用双手握紧刺穿「剑鬼」的剑柄——

「……用你的做法，是无法夺回卢安娜的」

「————」

「你……不是父亲。是我——是我必须做的事」

他挤出的声音，带着撕心裂肺的呜咽。

「————」

被贯穿的「剑鬼」听着他的声音，长叹了一口气，回想起往事。

在训练中，如果弄哭儿子，妻子就会唠叨个不停，所以儿子总是忍着眼泪，央求自己继续训练。

回想起来，从那时起，只要儿子一哭，自己就毫无胜算。

——这就是传说中，人与龙的巅峰对决中，被人从旁插手的结局。

** 第四章 『十成的工作』

1

——天地剧烈震动，至极之力相互冲突，正可谓新编织的传说一节。

超越人智的『剑鬼』与『神龙』之战，开始后仅仅一次眨眼——仅仅那刹那，亨克尔便从龙背上摔落，被踢出了传说。

「————」

从云上降落时，『神龙』用风压住了他，但与『剑鬼』的攻防一开始，龙便失去了那份顾虑——不，那份从容，亨克尔被迫自助。而亨克尔的努力没有结果，很快就被从舞台上摔落。

他无法只是紧紧抓住，觉得自己在地上翻滚很悲惨、很丢脸、很可怜——亨克尔现在甚至不允许自己有那种奢侈的自罚。

「————」

在跋利耶尔别邸开始的战斗已经远去，舞台扩大到贵族街，人与龙的超常攻防伴随着白日梦般的非现实光景持续着——亨克尔无法将目光从那里移开。

「————」

心情上想别开目光。不只是别开目光，还想转身逃走。如果不能如愿，就想抱着头蹲下，捂住耳朵拒绝一切。

但是，做不到。做不到那种事——威尔海姆・范・阿斯特雷亚在挥剑，亨克尔・阿斯特雷亚怎么可能将目光从那里移开。

「————」

年迈的“剑鬼”全身跃动，挑战比自己大几十倍的“神龙”巨体，回避好几次致命的死线，无数剑击削去龙鳞。

他的踏步，跳跃，剑闪，格挡，姿势维持，体重移动，视线诱导，招式的应用，障碍物的利用，将一切活用，增加剑力的剑士究极形态——毫无疑问，与龙交锋的威尔海姆，是亨克尔所知的最强剑士。

哪怕一瞬间，也无法将目光从那个“剑鬼”的妙技上移开。

「————」

屏住呼吸，忘记眨眼，甚至觉得心脏的跳动都是一种妨碍，被剑闪所魅惑。

那不是剑舞那种高雅而洗练的东西。无论从什么角度都要斩向对手性命的“剑鬼”的生存方式，更加粗俗，是类似野兽本能的激情。

那份激情成为业，业升华成招式，成为与“神龙”交锋的传说。

「————」

——与“神龙”交锋的威尔海姆的身影，让亨克尔窥见无数的战场。

在水门都市，与年轻时的特蕾西亚・范・阿斯特雷亚交锋的身影。

在利法乌斯平原，与妻子的仇敌白鲸这个强大敌人交战的身影。

与支配商业都市天空的三头“邪龙”交锋，斩下其长颈的身影。

同样在商业都市，与帝国最强“八臂”库鲁刚激烈冲突，名留青史的身影。

在露格尼卡王城，从曾为“剑圣”的特蕾西亚・范・阿斯特雷亚手中夺剑的身影。

在“亚人战争”中斩杀众多敌人，被称为“剑鬼”而沾满鲜血的身影。

亨克尔从现在的威尔海姆身上，窥见了除此之外在无数的战场上，以剑引导胜利的最强剑士的身影。

同时，他理解了——这样下去，“神龙”会败北。

「不行。」

亨克尔挤出声音，跪在地上的他站了起来。

他用手确认腰间的剑的存在，被那份确信所驱使。

“神龙”会输。因为，对手是决定要取胜的“剑鬼”。

「不行，不行。」

很遗憾，亨克尔的眼睛看不到“剑鬼”和“神龙”的实力上限。

就像在地上的人无法确认云上的光景一样，即使那里展开了远超想象的景色，亨克尔也无法亲眼目睹。

所以，他只能用拙劣的想象力去描绘——然后，在亨克尔・阿斯特雷亚贫乏的想象力的世界里，「神龙」败给了「剑鬼」的剑。

——作为前提，这场战斗是「神龙」压倒性地有利。

即使在亨克尔看来，「剑鬼」的剑也无法伤到「神龙」的龙鳞，不管攻击多少次都无法给予决定性的一击。

相对的，「神龙」的攻击每一击都是致命的，爪子和牙齿只要再深几毫米掠过，「剑鬼」就会无情地被夺去性命，曝尸荒野吧。

亨克尔也明白这个前提——尽管如此，他还是坚信「剑鬼」会赢。

这并不是道理。

没有人能用道理和道理战胜「剑圣」。也就是说，曾经战胜过「剑圣」的「剑鬼」的强大，是位于道理和道理的另一侧。

因为「剑鬼」拥有将剑尖伸向另一侧的强大——

「——不行。」

亨克尔无法接受这个无法颠覆的最坏想象。

如果在这里战胜了「神龙」，「剑鬼」下次挑战的就是「剑圣」。然后，就像打败了上一代的「剑圣」一样，「剑鬼」也会战胜这一代的「剑圣」——莱因哈鲁特。

那是不行的。只有那个，绝对不行。

虽然要实现那场战斗，以阿尔德巴兰不知如何利用的「嫉妒魔女」为首，还有许多障碍，但就算排除那些要素，也不行。

「不行……」

不行。不行。不行，因为不行，所以绝对不行。为什么不行，不用说明那个不行，总之就是不行。不行就是不行，只有不行。不行。因为不行。不行的是，不行。不行就是不行，不行。

「剑鬼」的那把澄澈的剑，无法拯救卢安娜・阿斯特雷亚。

因为救不了，所以——

「——亨克尔。」

正面，是呆立不动的「剑鬼」的背影。

隔着背影的模糊声音，被血泡阻隔，几乎像是溺水的声音，亨克尔没有听错，那是呼唤自己名字的声音。

明白这点后，亨克尔用全身的自制力抑制双臂的颤抖，握紧剑柄。

「……用你的做法，是无法夺回卢安娜的」

亨克尔的额头被倒塌的建筑物碎片砸中，流着血。

他被爆炸般的冲击波多次吹飞，被倒塌的柱子压在下面。

被剑闪切开的龙息余波烧伤了半身，拖着血肉和骨头被烧焦的痛苦，他依然在走着。

全身被尘土和鲜血弄得脏得不能再脏，走着，走着，走着——亨克尔站在威尔海姆的背后。

——站在那里，拔出「阿斯特雷亚」，从背后刺穿亲生父亲。

「————」

透过贯穿的剑，亨克尔感觉到威尔海姆想要回头。为了阻止他，亨克尔在手上用力，让他意识到自己受了重伤，阻止他回头。

现在，亨克尔无法看到威尔海姆的脸。如果看到自己的身影映在那双眼睛里，无论现在还是过去，亨克尔都会变得什么都说不出来。所以不能让他回头。绝对不能。

不能让他回头，不能让他开口。

如果让「剑鬼」说他要完成，就会被剑撬开。

被撬开的未来，或许会将乌云全部斩除，露出长久以来被封闭的晴空——但是，那里没有卢安娜的身影。

「剑鬼」的剑，无法让卢安娜醒来。

而如果没有她，亨克尔——亨克尔他们，就无法得救。

「你……不是父亲。是我——是我，必须做的事」

从喉咙里挤出的，是带着呜咽的微弱声音，亨克尔想诅咒自己。

咬紧牙关，废物。声音里带着力量，胆小鬼。有时间低头吗，懦夫。

这双手，这把剑，被父亲的血染红，牙齿颤抖，眼睛深处发热，内脏全部蠕动，无法完全抑制想要把一切都倾泻出来的冲动，没用的饭桶。

吹嘘自己做好了觉悟，什么时候才能完全骗过自己，漏尿的家伙。

「——大笨蛋」

亨克尔用无尽的恶骂让自己振作起来。

亨克尔的耳朵里，传来了不是自己的，但只能同意的斥责。

没有被血呛到的声音，亨克尔绷紧了脸，随后瞪大了眼睛——他和自己一直试图不让他转过来的威尔海姆对上了视线。

「——啊」

看向手边，剑还在同一个位置。然而威尔海姆却转了过来，是因为他扭动身体，强行拔出了贯穿身体的剑。

理所当然，拔出剑的伤口会流血。强行拔出，伤口会扩大。

但是，「剑鬼」拔出了剑。因为不拔出的话，就无法转过身来。

「……亨克尔」

威尔海姆再次叫了因为这暴举而哑口无言的亨克尔。

威尔海姆喉咙一动，咽下涌上来的血，不让声音变得模糊。但是，和八重与「神龙」连续战斗而全身负伤，又受到亨克尔的重创，他的身体已经失血到致命的程度。

不出所料，失去了贯穿身体的剑的支撑，威尔海姆跪倒在地。

「父，父亲……」

亨克尔立刻伸出手想要支撑住他倒下的身体。但是，亨克尔伸出的手反而被抓住，出乎意料地被拉了过去。

亨克尔因为威尔海姆那不像是濒死之人拥有的力量而绷紧了脸，威尔海姆用绝不失去力量的眼神看着他。

「你差不多该醒醒了……」

「————」

这句诉说，让亨克尔那即将萎缩的心中燃起了昏暗的热量。

他想说不要做梦吗？想说让卢安娜醒来是痴人说梦吗？还是说，他觉得就算卢安娜醒来，她也不会高兴——就算他不说，亨克尔也知道卢安娜不可能会高兴。

亨克尔至今为止所做的一切，卢安娜都不会肯定。

她会轻蔑他，会对他感到厌烦，会将爱情反转为憎恶，亨克尔的名字会作为这世上最可憎的男人，不可避免地刻在卢安娜心中。

但是，这样就好。

愤怒也好，憎恶也好，轻蔑也好。只要卢安娜从沉睡中醒来，用那双蓝色的眼睛看着世界，用那张嘴讴歌生命，这样就好。

他不会做那种对自己有利的梦。

亨克尔会活在这个如同噩梦，却又不是噩梦的现实中，然后死去。

为此——

「——不对」

伴随着昏暗的决心，亨克尔的头痛再次复发，但是威尔海姆却制止了他。

亨克尔屏住呼吸，看着威尔海姆，想知道他要说什么。威尔海姆依然没有从不成器的儿子身上移开视线，动了动沾满血的嘴唇。

亨克尔见过那表情。那是过去不好的记忆——特蕾西亚，母亲告诉他白鲸之战后没有回来时的悲痛表情。无法怪罪于任何人的叹息与愤怒灼烧着自己，同时履行家长职责的表情。

「醒醒吧，亨克尔……你……」

那是就亨克尔所知，「剑鬼」威尔海姆最脆弱时的表情——

「你，不管招惹谁的憎恨，莱因哈鲁特都不会放弃『剑圣』的宝座……！」

——和那时一样，说出最伤亨克尔心的话。

2

「——和我说话的时候，好好看着我！！」

被强烈踢击命中的瞬间，阿尔德巴兰的脑内警铃大作。警铃响起的原因是那记踢击，以及围绕着踢击的各种要素。

首先，踢击的威力大得惊人，造成的伤害也非同小可。而将自己踢飞的对手的腿长到让人怀疑「从这里到那里全都是腿吗！？」这点也令人吃惊。被踢中的冰靴的鞋尖刺穿了碎裂的石制护胸，冰块开始在胸骨嘎吱作响的胸膛上凝结，这可说是最大的危机。

不过，警铃大作的最大理由，果然还是因为从她口中听到了无法辩解的真相。

——好好看着我。还有在那之前，和我说话的时候看起来很寂寞。

「——」

老实说，她能察觉阿尔德巴兰内心复杂的感情，这点令他感到惊讶。

虽然他并没有自以为能够巧妙地隐藏，但他擅自认为她对这种微妙之处很迟钝。不过仔细想想，她只是不擅长与人互相投以恶意，对来自他人的恶意却相当敏感——因为她是银发的半妖精，生在这个世界上，这也是理所当然的。

「学费可真贵啊……」

痛苦地吐出话语的阿尔德巴兰的腹部，冰块开始侵蚀，而在那下面，有个冰制的男人正紧紧抓着它，那男人的外表和它憎恨的对手一模一样。

冰男妨碍了它的行动，阿尔德巴兰用魔法做出的石制左臂抓住冰男的头，毫不留情地将其拧了下来。它听到了制作者的悲鸣，没有头的冰男的身体凄惨地碎裂，化为冰屑。

相似的不只是外表，连容易死去这点都一模一样。

「来，接住！」

「呀！真是的，好过分！」

和碎裂的身体不同，被拧下来的头想要咬住它，所以它把冰男的头扔向打算追击的她——爱蜜莉娅。爱蜜莉娅像在玩躲避球一样，用身体正面接住了那颗头。阿尔德巴兰瞥了她一眼，看向自己的腹部。

被踢到的地方的冻结范围正在扩大，这样下去全身都会被冻住——

「那样的话就完蛋了呢，大叔。你知道该怎么做吧？」

被倒吊在土柱上，眺望着阿尔德巴兰和爱蜜莉娅攻防的观众——罗伊・阿尔法德用令人不快的坏笑，暗示阿尔德巴兰冰的应对方法。

它不需要大罪主教的建议。阿尔德巴兰咬紧牙关，用剑尖刺入自己开始冻结的腹肌。剧痛和出血，它用石盖强行堵住切腹前的伤口，回避了被冻住的坏结局。

因疼痛而变得通红的视野，鼓膜上响起了罗伊打心底感到愉快的笑声，「啊哈哈！就是这样！」

「——，这么痛苦的忍耐方式」

「喂喂，你都逼我二选一了，还说这种话。如果不想痛的话就老老实实被冻住。你也要有小姑娘的攻击就是这样的自觉」

「——。是啊。我也这么想。但是，阿尔你可别误会了」

「误会？」

「你不能用和肚子一样的方法，忍住全身的痛苦吧？」

这句宣言表明了爱蜜莉娅要将刚才腹部受到的一击，打入它全身。

就像在证明这句话一样，爱蜜莉娅那张美丽的脸庞因痛苦而皱起，表情变得严肃，开始吹起冷风的监狱塔周围开始出现白雾。飞舞的白色雪花包围了战场，阿尔德巴兰从爱蜜莉娅冰冷的手指感受到了她的认真。

「虽然我想说你生气的表情也很可爱，但老实说很可怕啊。而且……」

在轻浮地开着玩笑的阿尔德巴兰眼前，空气发出挤压声，被爱蜜莉娅抱在胸前的冰男头部开始复原。仿佛在说「这是新脸」，不，是「这是新身体」，冰男在几秒内完全复活，当场伸展身体展现自己还健在。

那无意义的挑衅活动力，忠实重现了原版，实在很烦人。

「……连细节都做得这么恶心，真是了不起。」

「跟拉姆的称赞方式一样呢，宅邸的大家也都说非常像。」

「嘿——不过，只有本人一脸厌恶吧？」

「你怎么知道？」

「当然知道，因为那是最不想看到的脸。」

回答单纯的疑问，爱蜜莉娅瞪大眼睛，眼角因愤怒而上吊。可能是以为被愚弄了，但阿尔德巴兰的意见毫无忌惮。

首先，用冰块制作某人，应该要选更可靠、更强大的外表——例如，以加菲尔为范本就好，偏偏是菜月・昴。

多亏如此，阿尔德巴兰破坏那个冰男时，毫无任何抗拒感。

「既然是军队，就该以最可靠的家伙为范本吧。」

「——？所以才以昴为范本啊？」

「……是吗？早知道就不问了。」

在头盔里吐舌头，阿尔德巴罗的心情就像吃了黄莲一样。

被踢飞的伤害自不必说，对阿尔德巴罗来说，像这样和爱蜜莉娅面对面说话的精神伤害更难受。

阿尔德巴罗的权能，维持『领域』需要精神的安定。然而爱蜜莉娅却能轻易动摇阿尔德巴罗的心，是个反常角色。

「混蛋。」

说实话，会在这里遇到爱蜜莉娅是意料之外。

从佛拉基亚回国后，阿尔德巴罗就按照自己的方便控制了普雷阿迪斯监视塔的成员。当然，他也掌握了爱蜜莉娅她们前往王都的事，但阿尔德巴罗打算在那之上迅速回收罗伊，避开波澜安全地离开王都——没想到会被佐达虫给阴了。

「……霉运的开始，是菲鲁特小姐吧。」

为了在环境最恶劣的奥古利亚沙丘迎击莱因哈鲁特，阿尔德巴罗故意让在塔里的菲拉姆使用加护，让她把自己的背叛告诉她的妹妹。

结果，虽然成功把莱因哈鲁特引到沙丘，但之后却招来菲鲁特他们的埋伏，陷入苦战。——不仅如此，菲鲁特似乎没有把情报只在自己人之间完结。

留在普雷阿迪斯监视塔的同伴受伤，本应守护王国的「神龙」与自己为敌，面对这种紧急事态，她还能冷静判断。阿尔德巴罗认为这也是那个巴尔加・克罗姆威尔的建议，但阿尔德巴罗摇头否定。

菲鲁特被普莉希拉认定为敌人。她的王器值得称赞。

不管怎样，菲鲁特在紧迫的事态中选择最佳方案，从她那得到情报的爱蜜莉亚也没有浪费。

结果就是，从监狱塔逃脱被阻止，与爱蜜莉亚对峙的最糟「现在」。

「————」

正面，爱蜜莉亚双手戴着冰手套，旁边是摆出剑道蹲踞姿势的烦人冰男，两人一起用锐利的眼神看向阿尔德巴罗。

从那双蓝紫色的瞳孔中，可以强烈感受到阿尔德巴罗不管做什么都不会输的气魄，但就算没有这种气魄，阿尔德巴罗能做的事也不多。

虽然模仿她的冰系魔法，用土系魔法造出石剑来对抗，但武器的质量却是天壤之别。这类武器的精巧程度与耐久力成正比，所以完成度的差距直接反映在武器的性能上。熟练度和熟练度的差距也体现在武器的制作速度上，与能即时制作出最适合武器的爱蜜莉娅不同，阿尔德巴兰是事先制作好武器再到处摆放的风格。再加上品味的问题，阿尔德巴兰就算拼尽全力，也无法用土块造出可靠的军队。

不仅如此，阿尔德巴兰别说伤害爱蜜莉娅了，就连让她受伤都会受到良心的谴责——这已经是自己与生俱来的致命缺陷了。再加上爱蜜莉娅那专精于活捉的战斗方式，与阿尔德巴兰的权能相性极差。

因此，如今排除了计划最大的障碍菜月・菜月和莱因哈鲁特，爱蜜莉娅对阿尔德巴兰来说就是天敌——除了一个人之外，是最糟糕的「敌人」。

「不管怎么说。」

不管怎么整理状况，都找不到一个好材料，让人想哭，但哭诉连发却从未打破过死胡同。

如果无法靠自己的力量给对方决定性的一击，那就只能依靠外部的其他力量了。就在他准备打出王牌的时候。

——他看到『龙』贯穿云层，急速降落到贵族街。

「真的假的？」

看到那东西从视野中穿过，阿尔德巴兰不禁喃喃自语。

刚才，从白雾弥漫的天空中，一道蓝白色的光线划过地面，那是阿尔德巴兰准备作为王牌的『阿尔德巴兰』。恐怕，它的目的地是贵族街——八重她们在别墅待命的地方，从那势头来看，十有八九是去救援的。

也就是说，八重无法应付的存在，被送到了跋利耶尔的别墅。

既然『阿尔德巴兰』已经介入，八重的生死概率各占一半。无法随意更新矩阵的阿尔德巴兰，除了担心同伴的安危之外，还面临了另一个问题——『阿尔德巴兰』无法帮助陷入危机的阿尔德巴兰。

「真的假的……」

阿尔德巴兰用同一句话，深切感受到状况比刚才更加恶化。

虽然可以使用权能重新来过，抢先一步把『阿尔德巴兰』叫过来。但是，那样的话没有援军的八重就会败给未知的敌人。

八重和菲鲁特，对阿尔德巴兰的目的来说都不是不可或缺的。

虽然不是不可或缺的——

「可恶！」

放弃咽下口中毒药的机会，阿尔德巴兰骂道。

对于用雪支配整个场地的爱蜜莉娅，用『阿尔德巴兰』的龙气把寒流全部吹飞，然后脱离战场，这是王牌的计划A。

既然这个不能用了，那就只能尽快实行计划B。然后要实行计划B，就必须尽快想出计划B。

在这期间——

「看到了吗，小姑娘！这样下去的话，我的伙伴会在王都大闹——」

「我被说过，那边的担心不是我的责任！」

爱蜜莉娅果敢地冲向想要延长思考时间的阿尔德巴兰。

『阿尔德巴兰』——『神龙』的来袭，爱蜜莉娅一边感受着墙壁对面的情况，一边相信同伴无视了它，她的胆量超乎寻常。虽然这是她信任制定作战的对手的证明，但也不是说做就能做到的。

而且，这也是对付阿尔德巴兰的最好办法，所以阿尔德巴兰也无计可施。

「嘿呀！嘿！嘿！嘿呀！」

爱蜜莉娅像是突然想起来一样，按照当初的方针，放弃对话，发动了怒涛般的连续攻击。

她用戴着冰手套的拳头连续打出无数拳，把临时造出来的岩石盾牌从正面打碎。在碎片飞散中，她用岩石义手接住冰枪的枪尖，然后扔掉被冻住的冰枪，向后跳去。——这时，绕到她身后的冰男用铁山靠撞了过来。

「呃，啊——！」

阿尔德巴兰挨了这招依样画葫芦的八极拳奥义，被撞飞了出去。而在她被撞飞的方向上，爱蜜莉娅把冰枪变成了冰锤，用力挥舞着。

纤细的手臂被拉紧，然后释放出威力难以置信的全力挥击。

充满气势的冰冷一击把空气殴杀，阿尔德巴兰也明白自己躲不掉，就在她放弃的瞬间，她用土防具覆盖住自己的身体——然后被巨大的威力直接击中。

「——」

阿尔德巴兰连惨叫都发不出来，就这样飞到了空中。

虽然只是临时造出来的土衣，防御力也只比用纸挡子弹好一点，但至少能防止被冰侵蚀。

视野在旋转，也不知道自己飞到了哪里，最后被某种坚硬的冲击接住，然后摔到了地上。

「呜呀，好痛。真是穷途末路了呢，大叔」

手撑在开始积雪的地上，头上传来了观战者愉快的声音。看来阿尔德巴兰是撞上了罗伊被钉住的土柱才停下来的。

飞了十几米远。全身都痛，连骂人的力气都没有了。

「可恶……」

对阿尔德巴兰来说，他不希望再花更多时间。

爱蜜莉娅的战斗方式是让周围的气温不断下降，时间拖得越久，负面效果就会像雪一样越积越多，而且说不定敌人还会在磨磨蹭蹭的时候增援。

对手的数量越多，攻略的难度就会呈指数级上升，这一点在和菲鲁特她们的战斗中已经痛感过了——而且其中说不定会有『天敌』。

「虽然被雪遮住了看不清楚，不过街上那边好像也变得很不得了了呢。要不要试着努力喊出声音，求救看看？大叔」

「吵死了。你给我闭嘴，就这样——」

罗伊特意去触碰阿尔德巴兰的逆鳞。

阿尔德巴兰怒火中烧，想要为了揍他那张笑嘻嘻的脸而死一次——在那可恨的对面，阿尔德巴兰看到了B计划的光明。

「如果那家伙是我……」

在远方，被白色雾霭笼罩的天空的另一端，大气摇晃的感觉，那是『阿尔德巴兰』正在展开激战的证明。

能和『阿尔德巴兰』上演死斗的候补，在阿尔德巴兰所知的范围内并不多，不过那边只能相信『龙』的胜利，交给它了。

而且，相信的不只是『龙』的胜利——

「——B计划」

相信的是，知道无法帮助阿尔德巴兰的『阿尔德巴兰』，会为没有商量过的未知的B计划打下基础。

为了实现那个未确认的B计划——

「罗伊！不想死的话就帮我！」

「——！阿尔！！」

听到阿尔德巴兰的声音，爱蜜莉娅瞪大眼睛尖声叫道。

声音中蕴含着难以置信的音调，阿尔德巴兰对此感到惊讶，明明自己已经把罗伊带出监狱塔了——不对，早在菜月・昴设陷阱的时候，自己的股价就已经跌到谷底了，没想到还有下跌的余地。

「不过，有必要的话，我也会借助大罪司教的力量。在帝国，菜月・昴应该也做过同样的事吧？有什么不对？」

「你明明知道不是这个问题！」

「是啊，我是知道才这么说的。你可以讨厌我。」

早就习惯被爱蜜莉娅讨厌了——骗人的。

其实，在被讨厌之前，自己根本就没被放在眼里。

「你这——！」

阿尔德巴兰的回答，让悲伤又愤怒的爱蜜莉娅在空中生成冰柱。

除了肉搏战，爱蜜莉娅也能像魔法使者那样使用冰，她让生成的冰柱像地毯式轰炸一样朝阿尔德巴兰和罗伊倾注而下。

总之，爱蜜莉娅想表达的是，她想尽快阻止阿尔德巴兰他们的恶行，但阿尔德巴兰用魔法掀开雪地，像翻榻榻米一样接住爱蜜莉娅的焦急攻击，化解了攻势。

「就算你说要我们帮忙……」

穿透而来的冲击让大地摇晃，这个临时建造的土制避难所也撑不了多久。

阿尔德巴兰分神维持避难所，而罗伊明明身处同样的困境，却完全不关心避难所的情况，不满地弯起嘴唇。

「就像你看到的，我们的手脚都被折断了，还被禁止进食。那你说我们还能做什么？还是说……你愿意允许我们吃掉那位姐姐？」

「才不要。我不会让你吃，也不会让你暴动。」

「那我们还能做什么——」

「当然有——吐出来。」

阿尔德巴兰低声说道，与他背后的土塔中倒吊着的罗伊对上视线，向「暴食」提出了除了吃和暴动之外的第三个选项。

罗伊听到这个提议瞪大了眼睛，然后立刻咧嘴一笑。

「叔叔，你到底对我们有多了解？该不会真的是我们的亲生父亲吧？」

「要是我养了像你们这样的小鬼，那我可没脸活下去了。」

阿尔德巴兰用咒印束缚住罗伊，强迫他听从自己的命令。虽然阿尔德巴兰的态度表明了他不打算和罗伊建立友好关系，但罗伊却舔着嘴唇表示欢迎。

罗伊・阿尔法德是“暴食”中“恶食”的持有者。无论是什么样的怪东西都会吃进肚子里的大胃王，究竟会如何评价阿尔德巴兰呢？——反正肯定不会是什么正经的回答，不过现在也没有时间去问了。

「——住手！」

瞬间，土制避难所被强大的冰之回旋镖击破——和帝国的玛德琳・艾沙尔特使用的飞翼刃一模一样的东西被扔了进来，爱蜜莉娅从被击破的冰的缝隙中冲了进来。

阿尔德巴兰用大了一圈的岩石义手妨碍爱蜜莉娅的前进。他用像棒球手套一样的手掌从上方覆盖，柔软而确实地阻挡了道路。

但是——

「——是诱饵吗！」

冰男用手撑着岩石手套，用前手翻的技巧飞越了阿尔德巴兰的妨碍。

爱蜜莉娅把自己作为诱饵，让冰男先冲了进来。一般来说，自己和人造物的诱饵角色应该反过来才对，不过阿尔德巴兰还是完全上当了。

冰男越过阿尔德巴兰的头顶，接近土柱。阿尔德巴兰从左右两边生出岩石碎片，打算夹击冰男，将他四分五裂——

「比刚才还硬！」

冰男似乎提高了冰密度，坚固的冰男新身体弹开了碎片。

冰男就这样无视阿尔德巴兰的妨碍，向被钉在柱子上的罗伊伸出手，逼近他，不让他做任何事——刹那间，他的头和身体分开了。

「什么！？」

爱蜜莉娅看到冰剑切开岩石手套，冰男的头从缝隙中飞出，不禁大叫。

她不知道坚固的冰男身体被什么破坏了——那是阿尔德巴兰右手无名指上的戒指，从那里伸出的钢丝。

在冰雾中闪耀的银色丝线贯穿了冰男的防御力，砍下了他的头。这是在与菲鲁特他们的战斗中学会的，一根手指的钢丝术。

艺术能拯救自己。就在体现这句话之后——

「——反正，这是最有趣的吧。」

充满阴暗愉悦的声音响起，阿尔德巴兰——不，世界发出了悲鸣。

3

——瞬间，袭击阿尔德巴兰的是灵魂的呕吐感。

「呕。」

它自认为知道原理，也想象过会发生什么。

但是，实际发生后，理解与想象都派不上任何用场。

那不是对肉体或精神，而是对无法触碰的『记忆』的攻击。

「呕。」

有一种似曾相识的现象，明明是第一次看到，却感觉不是第一次。此时阿尔德巴兰——不，所有受到这个影响的人所品尝到的，是比似曾相识还要浓烈数万倍，无法忽视的『反刍』。

证据就是——

「——啊。」

爱蜜莉娅发出嘶哑的声音，冰之标枪从她手中掉落。原本准备投掷的标枪无力地掉落，在碰到地面之前就无法保持形状，变回了玛娜。

她瞪大的紫绀色眼睛剧烈地动摇，无意识地当场跪下。阿尔德巴兰看着她的样子，咬紧牙关，向后跳去。

「呕。」

虽然感觉很恶心，但还不至于跪下。

『反刍』的影响因人而异。这是当然的。每个人对回忆的投入程度都不同。阿尔德巴兰和爱蜜莉娅对『记忆』的投入方式不同。

虽然很可恨，但罗伊的选择很正确。他选择了对爱蜜莉娅影响很大，但对阿尔德巴兰影响不大的『记忆』。

所以——

「呕。」

阿尔德巴兰忍耐着呕吐感，将手伸向天空。

王都的天空被冰雾染成白色，无法看到天空的全貌。但是，阿尔德巴兰相信『阿尔德巴兰』已经在为B计划做准备了。

只要做好准备，阿尔德巴兰就能启动它。

「呕。」

——这是在奥古利亚沙丘与莱因哈鲁特战斗时得到的战斗经验的成果。

在那场战斗中，阿尔德巴兰和『阿尔德巴兰』作为拥有相同自我的人类，共享了本应像指纹一样固有的魔纹，行使魔法——阿尔德巴兰借用『阿尔德巴兰』的玛娜，发动了魔法。

这次的B计划正好相反——『阿尔德巴兰』准备了等待启动的术式，阿尔德巴兰则负责将玛娜注入其中，代替他按下开关。

正因为是同一自我，才能想到同样的事情，发动不存在的B计划——

「——呕。」

发动之后，阿尔德巴兰看到了『阿尔德巴兰』准备的B计划的全貌，发出了和之前不同，但和罗伊的『反刍』相连的呻吟。

B计划的全貌是——

「不行……」

感受到强烈的玛娜奔流，跪在地上的爱蜜莉娅嘴唇颤抖。

她没有站起来，但抬起脸的紫绀色瞳孔捕捉到了浮现在王都天空中的百米级巨大岩块。

那块岩块的规模，简直就像从某处拔出了一座小山一样。

虽然阿尔德巴兰没有见过，但如果亲眼看到传说中的白鲸，或许就能体会到被天空中的强大存在所压倒的感觉。

不管怎样，『阿尔德巴兰』让岩块浮在空中的目的很明显——

「呕。」

下一瞬间，天空响起了破裂的声音，看到天空异变的每个人都明白，那是岩块上出现的无数龟裂所导致的。

小山般的岩块，被分成十几二十个岩弹，就这样朝地面——

「不行……！！」

预见到结果的爱蜜莉娅，鞭策着颤抖的膝盖站了起来。

她应该明白。就算碎裂了，直径十米以上的岩块一旦落到地上，街道就会受到巨大的损害，出现大量的受害者。

而且，为了阻止这件事，只有能够阻止的人去阻止。

「别看我这样，我可是打算不出现死者呢。所以啊。」

「——阿尔！」

「我相信，一个都不会让它们落到街道上。」

阿尔德巴兰单方面且自顾自地提出请求，无视了爱蜜莉娅激动的高亢声音，为了确保罗伊而跑向土柱。

冰男为了妨碍他，再次只剩头部滚了过来，但阿尔德巴兰毫不留情地踩碎了他，将磔刑的大罪司教从柱子上剥了下来。

「真是个坏男人呢，大叔。」

阿尔德巴兰没有回答罗伊多余的话，将他娇小的身体扛在肩上，跑了起来。

他没有回头看向直到刚才还在互相攻击的爱蜜莉娅，一溜烟地跑走了。

「阿尔！不行！不要逃……阿尔！！」

虽然听到了爱蜜莉娅悲痛的诉求，但没有攻击阻止他。这是当然的。她的力量现在正为了救人而全力使用着。

如果她能在这里不顾一切地追阿尔德巴兰，她会活得更轻松。她的人性一定会拯救爱蜜莉娅和阿尔德巴兰。

但是，爱蜜莉娅为了救人而使用了魔法，因此让阿尔德巴兰逃走了。

「不要走！把昴和碧翠丝还给我——！」

仿佛在呼应她激动的情绪，天空冻结的声音听起来格外响亮。

阿尔德巴兰一边听着那悲鸣般的声音，一边以隆起的地面为立足点，翻越监狱塔的围墙，从白色的战场中飞奔而出，不停地奔跑，不停地奔跑。

「那个姐姐在哭哦。」

如果他没有指出，他就能无视，但应该唾弃的大罪司教却特意指了出来。

阿尔德巴兰一边被哭声撕裂着心，一边不停地奔跑。现在他只希望在汇合地点能和共犯们聚在一起，不停地奔跑。

坠落在王都的岩块被接二连三产生的冰塔所阻挡，城市受害的情况被阻止了。

无论是引发这种情况的罪魁祸首，还是阻止这种情况的功臣，谁都没有感到高兴。

只是——

「——啊，多谢款待！」

只有舔着舌头，享受着悲喜交加的「恶食」在嗤笑着。

4

伴随着仿佛要撕裂天空的轰鸣声和视觉效果，巨大的岩块坠落。

龟裂，碎裂，化为一片片十米到二十米的空中土石流，给王都带来了天崩地裂的绝望感。

倾泻而下的岩弹袭击地面，估计最少也会造成千人到万人的伤亡。

能造成如此大量屠杀的，以现代的杀伤率来说，只有在佛拉基亚帝国争夺帝位时斩杀众多士兵的「蓝色雷光」塞西尔斯・赛格蒙特，以及每次暴动都会造成以都市为单位的牺牲者的「强欲」大罪司教，还有以勤勉创造出魔女教受害者五成以上的「怠惰」大罪司教。

不过——

「如果不局限于现代，以前应该有很多吧。」

阿尔德巴兰从城墙上眺望着，充满疲惫的声音中透露出无奈。

B计划——被逼入绝境，用卑劣手段制造逃跑机会的阿尔德巴兰，为了亲眼看到自己砸下的岩块结果，勉强留在王都。

当然，既然都特地用了卑劣的手段，阿尔德巴兰应该要赶紧夹着尾巴逃走，无视惨叫连连的王都。

但是，阿尔德巴兰没有这么做——他必须负起责任，见证到最后。

「——不愧是……」

阿尔德巴兰在头盔底下眯起黑瞳，发出嘶哑的称赞。

伴随着岩块坠落的声音与演出，不相上下的华丽光芒出现，从地面升起的美丽冰塔将倾注而下的岩弹全部挡了下来。

那与冰冷的外表相反，是充满温暖慈爱的救赎之手。那冰塔的蓝白色光辉，仿佛也表现出施术者深深的悲伤。

「大叔，你这样想会不会太有诗意了？」

被扛在肩上的罗伊如此嘲笑眺望着那幅光景的阿尔德巴兰。

虽然罗伊的手脚被折断而无法行动，但他用背肌灵巧地撑起上半身，越过阿尔德巴兰的肩膀观赏袭击王都的天地异变。

简直就像在享受VIP的特等席待遇。看他这副要是手脚能动的话说不定会吵着要爆米花的愉快模样，实在让人受不了。明明什么都没做，也没办法做，却能用那张嘴大放厥词。

「你才是，对我的心情描写过度投入，变得很诗意哦。虽然我不是很清楚，但比起『暴食』的你，那种品味更适合自以为是『美食家』的已死的另一半吧？」

「哈哈，拿死去的家人当话题攻击，你是不是没教养啊？实际上，对吃下去的东西品头论足的不是我们，而是莱伊哦。真是不可思议。反正我们和你们，吃下去的东西最后都会到达『灵魂的胃袋』啊。」

「不愧是小偷，不，是偷吃贼。」

「别把我们当成小偷啦。我们只是想吃得比饱足再多一点点……只是这种程度的可爱美食家而已。」

真是爱顶嘴。从『暴食』的权能性能来看，『恶食』那丰富的词汇和强辩能力，别说大罪司教，放眼世界也是屈指可数。

虽然他那副孩童的外表和表露出腐烂本性的说话方式很容易让人上当，但他肩上扛着的存在是吞噬了无数知识和经验的集合知怪物，不能忘记对他保持警惕。

正因如此，他才放弃用语言说服，选择用暴力和咒印强行让他服从。

「……总之，事情办完了。走了。」

「已经没必要帮助漏掉岩石的大姐姐了呢。大叔，你是不是经常被人说成是怪人或者变态？」

「谢谢您对我这两天的总评。」

罗伊没有说明就猜中了阿尔德巴兰留在这里的理由，最后还加上了多余的话。阿尔德巴兰敷衍地回应他，再次看向王都。

多亏了爱蜜莉娅，王都的受害被控制在了最低限度——看到贵族街的一角完全被夷平，阿尔德巴兰急忙从城墙上跳了下去。

5

——通过与巴尔加・克罗姆威尔的战斗，阿尔德巴兰改变了自己对无敌的权能的认知，认识到还有难敌能与自己匹敌。

现在，他仍然确信没有人能战胜自己。

但是，他告诫自己，为了巩固这份确信，不能对权能掉以轻心，不能放弃思考。

因此，他潜入王都进行『暴食』越狱作战时，没有轻易地重置，而是每一次的阿尔德巴兰都认真地，像把牙膏管挤到最后一滴那样，拼命地挑战，最后终于在六千七百二十四次的时候成功了。

——虽然每个人对这个数字是多是少的看法不同，但阿尔德巴兰基本上认为无论多少次都是『适当』的。

无论次数多寡，每一次都是为了跨越障碍而必须进行的挑战。

虽然也有极少的几次是为了让内心深呼吸而无谓地消费，但这种内心的换气也是必要的。

所以，无论次数多少，只要能得到期望的成果，阿尔德巴兰就会坚持说这六千七百二十四次是『最佳』的尝试次数。

「——哟，臭头盔混蛋。」

事先约定的汇合地点——离王都有段距离的这个地方，是已经荒废很久的采石场，非常适合想要避人耳目的坏蛋们作为集会场。

在采石场，背靠在快要崩塌的石壁上迎接阿尔德巴兰的，是发出辛辣称呼，因愤怒和敌意而让赤红眼睛闪闪发光的菲鲁特。

她弯曲着露出尖锐虎牙的嘴唇，双手抱胸，毫不掩饰对阿尔德巴兰的轻蔑。称呼也从『头盔混蛋』降格为『混蛋头盔混蛋』。

菲鲁特抬起纤细的下巴，示意远处的王都的方向，

「那种大岩石，要不是爱蜜莉娅姐姐阻止了，你知道死了多少人吗？你那不让人死的方针怎么了？每次受挫就改变决定吗？真是逊爆了」

「……是啊。我也因为菲鲁特小姑娘没事而松了口气」

「啊？」

「开玩笑的。不然就是随口说说，或者冷场的笑话」

阿尔德巴兰无力地回应着话中带刺的菲鲁特。可能是觉得阿尔德巴兰的态度不诚实，菲鲁特向前探出身子想要咬上去，这时，肩膀上的罗伊开口道，

「虽然想说继续保持下去，不过如果要责备大叔的话，我们已经做好准备了。既然要吃，要不要试试不同的调味料？」

「谁管你啊……你就是被抓住的『暴食』吗？我之前遇到的是大哥？还是弟弟？不管哪个，都是一副让人火大的相似脸。」

「啊，你也知道我们吗？不过，那也是当然的。路伊也跟我说了哦？说莱伊因为菲鲁特而食物中毒。」

「你是指你拿我的名字找碴的时候吗？真是活该。」

菲鲁特的毒舌越来越犀利，听说她曾经和普利斯提拉一起遇到过「暴食」——莱伊・巴登凯托斯。

当时，虽然罗伊揶揄了她死去的兄弟，但和面对阿尔德巴兰时一样，罗伊只是「哈哈」地愉快笑着。

「顺带一提，我们也不知道我们之中谁才是长男。我们有时候想当长男，有时候想当次男，所以才会这样。」

「别扯些莫名其妙的歪理。兄弟姐妹的上下关系不是靠心情决定的吧。要让还是不让，趁还没缺损之前选一个。」

「哈哈！大叔和小妹妹都以为面对被讨厌的大罪司教，说什么都可以吧？没关系没关系，这就是大家的共同见解吧？」

「喂，臭头盔混蛋，我可没打算和你开心聊天。快点闭上你那锯齿嘴，回答我的问题。」

「虽然我也同意这家伙很吵，不过问答就先暂停。在那之前……」

阿尔德巴兰打断菲鲁特的要求，东张西望地环视四周。察觉到他的视线在采石场游移，菲鲁特咂嘴后用下巴示意。

采石场深处，勉强没被破坏的简陋小屋吸引了阿尔德巴兰的视线——

「——阿尔大人。」

「————」

正好，八重从小屋现身，与阿尔德巴兰四目相接。

八重身上带着微温的香气，恐怕是在小屋准备了食物。由于消耗相当剧烈，这份体贴令人感激。

虽然令人感激——

「从你的样子来看，你被狠狠修理了一顿吧？」

阿尔德巴兰一眼就看出她与平时飘忽不定的她不同。

带有瓦斯语风格的特制女仆装到处都是破洞，即使在战场上也不忘保养的红发也乱糟糟的。最重要的是，她的表情。

该说是严肃吗？缺乏稚气的氛围最损害她的风格。

证据就是，八重注视着呆立的阿尔德巴兰，将手放在自己的胸前。

「……太好了。」

她用微弱的呢喃声吐露安心。

「————」

那声音中蕴含着出乎意料的感情色彩，阿尔德巴兰虽然有些扫兴，但绝不会提及此事，「喂喂」地耸了耸肩。

「这不像万能女仆八重小姐会有的态度啊。竟然连支援我都没办法，你和什么惊喜嘉宾在调情吗？」

「——什么调情，说得真难听呢，阿尔大人。如您所知，八重酱的心完全被阿尔大人支配了。」

八重一瞬就消除了回答时的犹豫，回答时的态度也恢复了平时的样子。她轻轻抚摸着自己的胸口，继续说道：

「不过不过，和男士度过热情的时光也是事实呢～。来宅邸的是威尔海姆・范・阿斯特雷亚……不，是威尔海姆・特里亚斯大人」

「是『剑鬼』爷爷啊。那确实……」

面对意料之外的刺客，八重也吓了一跳吧。不过，他很难说是最糟糕的敌人。

当然，威尔海姆毫无疑问是王国首屈一指的强者，但只要是剑士，就比魔法使更容易对付八重。而且，跋利耶尔别邸布满了她的陷阱，可以说是万全的「红樱」狩猎场。

但是，从结果来看，既然「阿尔德巴兰」赶去救援，就说明「剑鬼」的锋利程度更胜八重一筹。而且从她的表情来看，她甚至没有遗憾地输掉，而是彻底地输了。

又或者，他锋利的理由是——

「在那里垂头丧气的老爸也脱不了干系吧？」

阿尔德巴兰看向小屋旁被丢弃的劈柴台的树墩，红发男子——亨克尔正抱着单膝低着头。

亨克尔无力地垂着头，沾满全身的血迹也没有擦拭。从这里看过去，也看不出来那是他的血还是敌人的血。

「发生了什么？」

「……我意识朦胧，没有亲眼看到」

「但是？」

「亨克尔大人说，他击败了『剑鬼』大人」

「————」

八重没有确凿的证据，阿尔德巴兰闻言倒吸一口凉气，再次看向亨克尔。

当然，阿尔德巴兰也知道亨克尔和威尔海姆的关系。也就是说，这是父子对决，而且是儿子击败了父亲。

他也知道亨克尔作为剑士有着致命的缺点——

「夹在儿子和父亲之间，真是辛苦啊，老爸」

阿斯特雷亚家的恩怨，阿尔德巴兰并不知道其中的核心。

他只知道，「剑圣的加护」和「剑圣」的头衔，让亲子三代之间产生了绝对无法融合的矛盾。

而这次的事件，让这个矛盾变得更加明确。

「————」

莱因哈鲁特和威尔海姆，这几天亨克尔和这两人都完全处于敌对立场，阿尔德巴兰他们没有资格担心他的心情。

他们是为利用而将亨克尔卷入的一方，就算问「没事吧？」也只是装模作样。所以阿尔德巴兰说「然后」，将视线移回八重身上。

「那个老爷爷呢？既然你说讨伐成功，老爸的血是回溅的……」

『——姑且做了最低限度的处理。因为不能久留，所以真的是最低限度。』

「呜哦！？」

突然的声音让阿尔德巴兰肩膀一震，他慌张地看向周围。但是，声音的主人「阿尔德巴兰」却不见踪影。那么大的「神龙」龙壳，应该不是会看漏的尺寸——就在这么想的时候。

『抱歉抱歉，先解除光学迷彩。』

话才刚说完，原本空无一物的空间——龙的巨躯出现在菲鲁特靠着的石壁上，下巴靠在石壁上，身体无力地靠着。看到那仿佛模糊的空气逐渐染上颜色的登场方式，阿尔德巴兰惊讶地瞪大眼睛。

「光学迷彩，是用光的折射透明化吗？还能做到这种事啊。」

『不过，要一边行动一边进行实时修正还是有点勉强。但是，如果只是要静止不动的话，正如你所见，这个巨大的身体带来的劣势就会消失得差不多了』

「是啊。能够透明化的『龙』，感觉挺厉害的」

虽然只要结合阳魔法和风魔法，就可以实现改变光线折射的魔法，但是要一直展开的话，不仅魔力消耗太大，而且还需要能够一直和周围景色同化的才能。佛拉基亚的『九神将』中似乎就有擅长这种魔法的天才，据说在『大灾』中复活了。

阿尔德巴兰也记得，自己在帝都的时候，曾经多次被看不见的狙击瞄准性命。

总之，除了那一部分的天才之外，这个魔法很难实用化。

实际上，阿尔德巴兰也很难在实战中使用这个魔法，所以才在王都让其躲在云里，在上空待机。

「既然你能够做到这一点……看来是经历了一场激战啊」

『和你那边不相上下。说实话，要不是有你老爸的背刺，我可能就要输了』

「背刺吗……」

阿尔德巴兰缓缓地摇了摇头，处理着两个惊讶。

一边是，让『阿尔德巴兰』想象败北的『剑鬼』的恐怖。虽说积累的软件不同，硬件的规格毫无疑问是『神龙』的，却在和八重的连战中达到那个领域，真是不得了的怪物。

然后，另一边当然就是，亨克尔对那场战斗的搅局方式——

「不是正面战胜就能解决的简单事情，但是用背刺决胜负的话，你父亲的精神会变得乱七八糟吧。」

「嘛，我觉得那是毫无疑问的哦～结果，从逃到这里开始到现在，一次都没有和我们说过话。」

「是吗……」

亨克尔的重症程度和想象中一样，得到八重的肯定，阿尔德巴兰长叹一口气，重新环视在场的众人。

因败北而沮丧的八重，被『剑鬼』的气势压倒的『阿尔德巴兰』。因为刺杀父亲的冲击而蹲下的亨克尔，毫不隐藏对这边的敌意的菲鲁特。然后，肩膀上心情愉快的罗伊，以及一直走在卑鄙者道路上的凶恶反派阿尔德巴兰。

不仅成员不怎么样，而且相当狼狈。

「——即便如此，全员都活着。」

在采石场碰面的成员，所有人都活了下来，阿尔德巴兰松了一口气，静静地解除『领域』，重新展开新的矩阵。

重新开始的地点被更新，这样王都发生的事情就成为这个世界的既定历史。

也就是说，从她紫绀色的眼瞳中流下的泪水，已经无法挽回了。

「但是，这样就好。在决定背叛一切的时候，就没有只对某个人例外这种便宜行事的事情了。」

不妥协。也不允许内心动摇。一旦动摇，一切都会白费。

为了得出结论，让这副身体，这颗心所感受到的所有痛苦都有意义，阿尔德巴兰他们不能失败，也不能停下脚步。

「八重，如果你准备了饭的话，就给我吧。我肚子饿了。」

「因为没能从宅邸里带出食物，所以从路过的商店里偷来了。我有记录从哪家店拿了什么，之后就拜托你支付了。」

「真会精打细算啊……我知道了。还有这个。」

「绑起来，吊起来就行了吗？那我已经做好了。」

八重刚这么回答，阿尔德巴兰的肩膀就突然变轻了。仔细一看，原本扛在肩上的罗伊被钢丝吊了起来，像蓑衣虫一样挂在采石场的石壁上。

对于一路上被迫听他们两人没完没了地闲聊的阿尔德巴兰来说，这实在是大快人心。

「怎么了怎么了，又是这种待遇？算了，至少比倒吊要好」

「你就暂时保持这样吧。等我决定好怎么管教你之后，再帮你治好手脚。但是」

「别忘了咒印，对吧？那有什么关系？虽然我们绝对不会说我们没有图谋，但暂时会老实点，好好鉴定一下的」

「鉴定，是吗？」

「是因为莱伊死了吗？虽然我完全不打算继承『美食家』，但开始对盘子上之前发生的事情产生了一点兴趣！」

罗伊的双手双脚被绑住，以虾一样的姿势被吊着，摇晃着身体。阿尔德巴兰对他的诡异态度耸了耸肩，和『阿尔德巴兰』交换了一下眼神。

拥有相同自我的他收起巨大的下颚，保证不会移开视线。

「对了，B计划帮了大忙。多亏了那个，我们才能逃出来」

『啊啊，奥里金是那边的吗。我这边是想的“B计划”。嘛，想法的着陆点一样就好』

「奥里金？」

『“另一个我”这种称呼方式也差不多该乱了吧？所以，用奥里金来表示元祖怎么样。我这边就叫直系怎么样？』

「元祖和直系，好像家系拉面啊」

对于“阿尔德巴兰”的提案，阿尔德巴兰只是说了句「考虑一下」就随便应付过去了。然后终于，他转向了被搁置的怒气冲冲的菲鲁特。

菲鲁特保持着双臂抱胸的姿势，双眸中燃烧着不变的怒火——

「真亏你能知道接住那块大岩石的是爱蜜莉雅酱啊」

「啊？你是在小瞧我吗？那种蠢事，除了爱蜜莉雅姐姐以外没人会干吧」

「这种说法，感觉像是在说小瞧人的是哪边啊……不过实际上就是这样。我就是算上爱蜜莉雅酱会接住一切才把岩石扔下来的」

「……你这家伙，看来不踢你屁股是不行了」

为了逃跑而用卑劣的手段，正确理解阿尔德巴兰的意图，菲鲁特的嘴唇更加扭曲地如此恐吓。阿尔德巴兰感受到，这种充满平民气息的威胁，是她表达愤怒的最大限度，但同时也抱有别的感慨。

阿尔德巴兰的做法，以及完全中计的爱蜜莉雅。让「暴食」越狱这件事本身，也是菲鲁特会生气的要素。

但是，菲鲁特的愤怒满溢的方式，感觉还有其他理由——

「……父亲和『剑鬼』爷爷的事，不是菲鲁特的错吧。」

「我才不觉得是自己的错咧。毫无疑问，是你的……你们和莱因哈鲁特父亲和祖父的错。不过，就算这样我还是很火大，一想到知道这件事的那笨蛋会露出什么表情，我就更火大了。」

「——」

「在那家伙成为我的骑士时，和那家伙有关的事，不管是什么都跟我有关，这样才合理。给我记住，你这混账铁罐。」

「……记什么？」

「就算你认为那是你自己的责任，但那位公主殿下不可能和你一样。你所做的事，只是在鞭尸。」

菲鲁特的目光和舌锋，是至今为止最毒的，侵蚀着阿尔德巴兰。

骑士和主人的关系，就算其中一方死去也不会消失。阿尔德巴兰的恶名，也会变成普莉希拉・跋利耶尔的恶名。

重新被指出这点，品尝到新鲜的苦涩和痛楚。但是——

「公主已经不在了，连尸体都没留下。」

「——！不是那样……！」

「对我来说，生命就是那样。」

菲鲁特的愤怒，被干渴的回答给堵住。

死后的名声和恶名，对死者来说没有任何意义。一切都得活着才有意义。对死者的评价一喜一忧，都是活下来的人的感伤。

「自己和对方都活着的时候，要尽全力去做。我能说的只有这些。」

「——混账铁罐，你到底是什么人？」

「……我是追随星。」

「追随……？」

「在夜空中最闪耀的星星的失败品。」

说完，阿尔德巴兰背对菲鲁特，放弃对话。就这样，阿尔德巴兰走向劈柴台，走到亨克尔的身边。

「————」

低着头的亨克尔没有抬头，也没有看向阿尔德巴兰。但是，他应该还有意识。呼吸和紧绷的全身都感受得到这边的气息。

很容易想象他现在的心情。阿尔德巴兰稍微烦恼了一下该说什么。

「我会遵守约定。事情结束后，『龙血』一定会是你的。」

「——！」

现在亨克尔需要的不是安慰也不是谢罪，而是约定的约定。

听到阿尔德巴兰这么说，亨克尔倒抽一口气，接着伸出手抓住阿尔德巴兰的上衣下摆，强行拉了过来。阿尔德巴兰立刻单膝跪地，冰冷的刀刃抵住他的脖子，与近在眼前的亨克尔四目相对。

脸上也溅到父亲鲜血的亨克尔，蓝色的眼睛布满血丝。

「绝对……！」

「————」

「绝对要遵守约定。无论如何都要拿到『龙血』……还有『嫉妒魔女』……！」

「我知道。我不打算终结世界。『暴食』就是为此而存在的。」

阿尔德巴兰感受着脖子上的尖锐疼痛，冷静地回答。同时他轻轻抬起手，让对亨克尔的暴行有所反应的八重退下。

就这样，阿尔德巴兰和亨克尔在极近距离互相瞪视了一阵子。

「可恶！」

亨克尔骂了一声，推开阿尔德巴兰。阿尔德巴兰勉强撑起差点跌坐在地上的身体，往前一看，亨克尔又低下头，回到刚才的封闭状态。

看到他的样子，阿尔德巴兰用手指拨弄头盔的金属零件，轻轻叹了口气。

总之，现在掌握了所有人的状态。

虽然无法否认在进入王都前后，所有人都有所消耗，但没有人脱队，而且成功回收了罗伊，所以希望这些事可以互相抵销。

老实说，虽然知道自己不适合做这种事，但还是得好好掌舵才行。

「总之，这里应该可以暂时休息。吃完八重做的饭，稍微休息一下再继续移动。王都的混乱也还在持续——」

阿尔德巴兰用手指弹出声响代替拍手，吸引众人的注意。

从一开始就跟昴一起行动的八重和亨克尔，几乎三天不眠不休地持续行军。为了让他们休息，他打算花点时间。

——如果不是大岩石从上空投下，打断了阿尔德巴兰的话。

「什——」

才刚觉得薄云遮住了影子，阿尔德巴兰就被超重量击溃。

只是，感觉好像听到远处有虫子的振翅声。

6

——奥托・苏文暴怒。

他下定决心，一定要除掉那个邪智暴虐之王——之前昴开玩笑时曾说过，生气时的固定台词掠过脑海，奥托就是如此暴怒。

愤怒的起因和矛头，已经不需要说明。

化为大罪人的阿尔——阿尔德巴兰做了不可原谅的事。他背叛了关心、担心他身心的人们，还以逼近上百的气势打破王国制定的法律。

但是，最让奥托生气的是，他和奥托的亲人敌对。

奥托自觉自己是和平主义者。

基本上他讨厌争斗，信条是能避开的麻烦就避开。实际上，作为旅行商人和芙拉姆轻装旅行的那段时间，除了被卷入不得不参与的事件以外，他几乎不会主动插手纠纷，也不会选择粗暴的解决方法。

但是，自从他加入爱蜜莉雅阵营，成为内政官之后，情况就变了。

虽然他不认同昴把自己称为武斗派内政官，但和平主义和以温和的方式解决事情——这样的方针，在现在的立场上已经不是最优先的了。

和轻装旅行商人的时代相比，针对自己的恶意的性质和尖锐程度都不可同日而语，如果一直采取消极的对应方式，就无法保护好自己想要保护的东西。

另一方面，被王选候补者之一重用的自觉，也作为警惕而无法放手，他也在这样约束着自己。

作为阵营的内政官，奥托的立场也涉及梅札斯领地的运营，他拥有着过去自己无法想象的地位和头衔的力量。为了不沉溺其中，搞错自己的位置，奥托每天都在自我警惕。

而奥托的警惕，在自己人被动手的瞬间就轻易地解除了。

「谁都有自己的苦衷。但是，对于不打算坐下来谈判，也不准备谈判的对手，我不会手下留情」

如果希望别人怜悯，那就怜悯；如果希望别人施舍，那就施舍。

以爱蜜莉娅为首的阵营的成员们都有这样的关怀和温柔。所以，奥托也最大限度地尊重了大家的善良之心。

如果对方还是践踏，利用这份善良，那就没办法了。

如果希望别人施恩，那就施恩；如果希望别人支持，那就支持。

然后，如果对方希望敌对，那这边也尽情地敌对。

「多亏了爱蜜莉娅大人，街道没有受到损害。贵族街的避难诱导也事前完成了。王都的骑士团很能干啊」

奥托一边整理着发生的事情的受害状况，一边握紧拳头。

因为需要分心把握事态和确认进展，所以无法愤慨。只是，内心深处有种羞愧的感觉——对于自己丢人的丑态。

事态开始动起来，最初沉重的打击打在脑袋上，奥托狼狈地诉说自己的无力，结果被爱蜜莉雅安慰。简直完全相反，不该发生那种事的。奥托的立场应该是要除去爱蜜莉雅的不安。

然而现实却是奥托哭丧着脸被爱蜜莉雅安慰，被应该支持的对象的话给拉起脸，最后还被拍背。

虽然对爱蜜莉雅开玩笑说会被昴杀掉，但奥托的真心话是想勒死自己。

不过，死人永远没有挽回的机会，所以奥托没有做出勒自己脖子的愚蠢行为，而是全心全意地动脑。

幸好，哭丧着脸让脑袋稍微清醒了——虽然脑袋里头依旧雷鸣大作，但闪电的光芒可以用来凝视黑暗深处。

回想起来，以前和弗乌尔两人在雷雨中赶路的时候，货台曾经被落雷打中，结果把货物全都烧光了。

奥托感叹自己运气不好，爱龙却说『少爷和我都没受伤，应该要高兴才对』，这个意见很正确。

在闪电不断的雷雨中前进，要有被落雷击中的觉悟——那时候，能不能不被雷电烧死，全看当事人的运气。

尽可能地削减运气这个要素，让敌人在雷雨中前进。

这就是激怒的奥托・阿斯，不择手段的战斗方式的本质——为此，他可以毫不犹豫地打出被骂无情的牌。

其表现就是——

「比莱因哈鲁特先生更强的武力，比菲鲁特大人更强的战力，滞留在王都的我们无法准备。说起来，当事情轮到我们出场的时候，武力和数量就无法成为阻止他们的绝对指标。」

不知道用了什么方法，阿尔德巴兰躲过「剑圣」莱因哈鲁特，带着「神龙」波克肯尼卡，击退菲鲁特等人的战力抵达王都。

面对阿尔德巴兰难以理解的执行力，刚从佛拉基亚帝国回来，和同伴分头行动的奥托等人没有对抗的手段。

因此，指示爱蜜莉娅活捉敌人，还有向正好来到王都的威尔海姆他们搭话，都不是为了决定性的一击。

当然，如果爱蜜莉娅和威尔海姆他们能赢的话，那是最好的，但奥托预想那是不可能的。而且，现在的奥托他们没有比投入手头最大战力更有效的攻击手段。

——莱因哈鲁特・范・阿斯特雷亚的强大，还有菲鲁特的参谋的战略性智谋，奥托・苏文都没有。他也没有高估自己，认为自己有和他们竞争的才能。

奥托不期待自己能做到能力以上的任务——自己能做到的，顶多就是发挥出自己能力的十成。

发挥十成，奥托・苏文能做到的是——

「——王都西边，被放弃的采石场。」

听到和振翅声一同传来的报告，奥托眯起眼睛在地图上做记号。手上拿着染血的手帕，一边按着鼻子，一边轻敲开始朦胧的脑袋。

加护的过热——昴这样称呼过度使用加护的疲惫，想起加菲尔听到这不可思议的词汇时眼神发亮，嘴角不禁上扬。

「过热，非常好。就算头裂开我也不会停手……」

流着鼻血这么说完，奥托朝聚集在周围的振翅声——沙虫弹指，指示它们继续监视目标和采取下一个行动。

沙虫的个性好，个体意识薄弱。

以群体为单位共享方针的它们，只要说服一只就能发挥说服整个群体的效果。而且沙虫对于请求的回报，几乎都是「安居」。

奥托要利用内政官的地位确保回报，相对的，沙虫要遵从会危及个体性命的指示，完成人类办不到的乱来工作。

——像是跟在逃亡的「神龙」后面锁定会合地点，或是用十万以上的群体之力将大岩石砸到对方头上，还有回收被囚禁的菲鲁特留下的信息，诸如此类。

「……莫戈雷德大喷口。」

这是被阿尔德巴兰一伙人当作人质带走的菲鲁特，相信能传到这边而留下的信息，是从被破坏的跋利耶尔别邸回收的。从她能躲过监视，把信息托付给沙虫来看，菲鲁特也相当有胆量。

信息上只简单地记载了卡拉拉基都市国家的某个地名，恐怕是阿尔德巴兰他们的下一个目标，或者是目的地吧。如果他们以那里为目标行动的话，就请他们尽情地行动吧——只不过，奥托不会移开视线。

无论他们去哪里，无论他们如何隐藏，奥托都会以耳鸣和流血为代价，继续监视阿尔德巴兰他们的举手投足。

「请不要以为还能睡得着——现在全世界都是你们的敌人」

自己没有胜利的力量。能做的，只有持续削弱对手的力量。

这就是奥托・苏文，与“剑圣”和“大参谋”不同，作为爱蜜莉亚阵营的内政官，将自己力量发挥到极致的战斗方式。

** 第五章 『名为佩特拉・雷蒂的少女』

1

——在阿尔德巴兰一伙人被强敌追得喘不过气来的时候，王国里还有两个地方正在进行不输给他们、同样激烈的战斗。

一个是『剑圣』的战斗。她正在阻止『嫉妒魔女』从被封印的祠堂中显现一部分，吞没奥古利亚沙丘，防止世界灭亡。

『嫉妒魔女』和『剑圣』，如果她们的对手不是彼此，双方都拥有瞬间分出胜负的实力，但因为彼此是对手，所以战况陷入胶着，一直无法分出胜负。

正如字面所述，这场战斗会持续七天七夜吧——以世界的崩坏为代价。

而另一个战斗，与阿尔德巴兰一伙人和『剑圣』不同，虽然没有伴随物理上的冲突，却有大幅影响其他两场战斗趋势的余地。

也就是以佩特拉・雷蒂为关键，追逐『后追之星』的人们的奋斗。

——关于克林特这个男人，佩特拉知道的实在不多。

他站在我们这一边，这点不会有错。

他侍奉的主人安妮罗洁・米洛德，是位聪明伶俐的少女，她不介意自己年幼和罗兹瓦尔亲戚的瑕疵，是爱蜜莉雅阵营的强力支援者之一，而且在佩特拉看来，她毫无疑问是被爱蜜莉雅所魅惑的人。

献身支持安妮罗洁，被信赖为万能总管的柯林特，佩特拉以女仆身份开始工作时，也曾受他教导礼仪和礼节。

不只是佩特拉，法兰黛莉卡和拉姆这些梅札斯家的相关人士，几乎所有人都受过柯林特的熏陶，学习佣人的基础。

因此，柯林特可以说是梅札斯家佣人的始祖，原本佩特拉应该要将他视为老师或师父。

不过，订正佩特拉这种认知的不是别人，正是他本人。

「教导什么的，我可没打算接受那种夸张的职责。误解。我不过是将先人传下来的东西传承下去。只是刚好长时间待在这个立场，所以机会比较多。坚决拒绝。」

柯林特的这种想法，可以评为谦虚或内敛。

但是佩特拉却隐约能感受到，这正是几乎不表露感情的柯林特的真心话。

『到头来，那个男人还是太小看自己了。因为对自己的评价低，所以对自己的工作表现也认为不值得夸奖……太瞧不起人了！』

这是只有在评价柯林特时，法兰黛莉卡才会格外严厉的评论。佩特拉认为，法兰黛莉卡的见解绝对正确，比这世上任何人都要出色，但佩特拉却只有一部分赞同，一部分持不同意见。

柯林特的态度乍一看确实像是对自己的评价很低。但另一方面，柯林特在用自己的言行影响他人时，却不会表现出犹豫和踌躇。

如果真的对自己的评价很低，应该会更加犹豫和踌躇才对。

柯林特的处世之道中，没有这种凡庸的犹豫——和佩特拉一样。

「只要我想做，就没有什么做不到的。」

大多数的人听到这句话，或许会认为这是骄傲而嗤之以鼻，但佩特拉想珍惜的不是大多数的人，而是身边的人，所以无所谓。而佩特拉相信，身边的人们也相信着佩特拉的自信和可能性。

佩特拉知道自己是可能性的集合体，也拥有让可能性开花结果的才能。

她知道自己的外表可爱，也拥有足以走上自己所期望的道路的才能，以及相信自己的才能并持续努力的毅力，是被上天赐予了两样甚至三样才能的存在。

作为拥有天赋之才的人，佩特拉认为柯林特的处世之道并非是对自己评价低，而是评价高。

柯林特知道自己拥有优秀的能力，但并不以此为傲。所以乍一看，他的人品谦虚而内敛。

「但是，我非常讨厌他。」

——关于柯林特这个男人，佩特拉知道的并不多。

但是，对于了解不多的柯林特，佩特拉却无法发自内心地喜欢他。

这与对任何人都温柔慈祥的法兰黛莉卡，唯独对柯林特表现出特别的态度和表情，以及佩特拉察觉到那是出于怎样的感情有关。当然，也与柯林特和罗兹瓦尔有很长时间的交情，看起来关系很好的事有关。

但是，最大的理由，和法兰黛莉卡或罗兹瓦尔的关系不同，是从柯林特本人的生存方式衍生出来的——他那仿佛已经离开舞台的生存方式，与佩特拉的主义完全相反，这是最大的理由。

「——既然回来了就帮帮我！你听得到吧，柯林特哥哥！」

在离沙丘最近的城镇，米卢拉的入口大门，佩特拉驾着龙车通过，高声呼唤着认识的男人。

从普雷阿迪斯监视塔开始，帕特拉修在沙海上奔驰了一昼夜，多亏如此，佩特拉她们的归途是最快的路线，最短的时间。尽管如此，还是远远落后于借助了『神龙』之翼的阿尔。

为了追上那远去的背影，必须借助他的力量。

「柯林特哥哥！」

拉起缰绳停下龙车，佩特拉在城镇正中央的广场再度高声呼喊。

对于佩特拉拼命的诉求，寻求的男人没有回应。但是，声音绝对传达到了，佩特拉如此相信，环视周围。

『什么？镇上一个人也没有？』

和佩特拉眺望同样的景色，想象中的『昴』如此说道。

正如『昴』所说，明明还是大白天，广场上却一个人影都没有——不，不止广场。整个镇上都感觉不到人的气息。

米卢拉给人的印象是萧条的驿站小镇，但即便如此，应该也有不下一两百人的居民生活在这里。一个人都没有的话就太奇怪了。

「……难道说，大家被头盔大叔给消灭了？」

『你这话也太吓人了！你又不是艾尔莎！』

「梅莉，别说吓人的话——昴也是，梅莉已经不会做那种事了。这是教育的成果。」

前半句是对梅莉说的，后半句是对『昴』说的。

确实，一瞬间梅莉所说的最坏的剧本从脑海中闪过，但这种可能性从无人的小镇却没有被破坏这一点可以否定。如果阿尔和波克肯尼卡一起大闹的话，镇上应该会呈现出更加无法挽回的惨状。

这个小镇的样子，与其说是那种荒芜的惨状——

「像是连夜逃跑了。」

『像是连夜逃跑』

佩特拉和『昴』的感想出乎意料地重合了。

因为『昴』是佩特拉脑中的居民，所以要说理所当然的话，这结果确实理所当然，但对恋爱中的少女来说，和心上人想法一致还是有点开心。

而且，能够变得积极的理由还有其他。

「——虽然有些语病，但大致上是那样没错。慧眼。」

这么说着，一个男人从空无一人的小镇广场中走了出来。

那是在荒凉的小镇风景中，散发出异彩的洗练氛围的人物。那不可思议的存在感，就像在纯白的画纸上滴落一滴深蓝色的颜料一样，让人感受到一种不加修饰的强烈。

就算这里不是寂寥的驿站小镇，而是人山人海的王都的喧嚣中，或是咚咚咚地发射着夏日风情的烟花的拥挤的烟花会场，也一定不会看漏那个男人的存在吧，他就是拥有着这种天生的气质。

『等一下。我现在正火速地在佩特拉的知识中搜寻』

「——克林特哥哥」

『啊——被抢先了！』

当时『昴』还没有见过对方，被对方打断对话后显得很不甘心，而佩特拉从驾驶台上跳了下来，直直地看向对方。

看向万能管家，也是掌握着改变局面关键的人物——柯林特。

「——米卢拉的情况也好，那片沙海的荒芜景象也好，看来放弃回去是正确的选择。侥幸。」

柯林特用手调整了一下左眼的单片眼镜，眯起眼睛看向空荡荡的小镇，以及佩特拉她们背后——颜色浑浊的天空，以及造成这种现象的原因。

然后——

「我们来谈谈吧，佩特拉。看来我们有必要尽快这么做。」

2

「——原来如此。深思熟虑。」

听完大致的说明后，柯林特用手指抵住自己纤细的下巴，闭上一只眼睛。

拥有锐利美貌的他思考的样子本身就像一幅画一样庄严，但很不巧的是佩特拉没有余力看入迷，而且她对美的感性方向也不同。

如果只是想看美形的话，看镜子或者看爱蜜莉娅才是最享受的。

「加菲尔和艾莎的情况如何？确认。」

「牙之兄和老师应该都不用担心性命问题。不过，牙之兄明明应该很结实，却迟迟没有醒来，这点倒是让人担心……」

「嗯，我想，加菲尔先生应该是保护了艾莎先生。」

佩特拉接过梅莉回答的后半部分，想着躺在龙车里的两人。

以结实为卖点的加菲尔，会受到和身为小人族且是魔法师的艾莎同等的伤害，恐怕是因为在受到『神龙』攻击时，加菲尔站在前面保护了艾莎——如果不是这样，艾莎的伤势应该会更严重。

『所以，加菲尔正面承受了龙的一击吗？……我还没完全接受这家伙是会如此奋不顾身的人，以及十四岁就是中二的事实。』

「加菲尔先生姑且已经十五岁了。顺带一提，我也快要十四岁了。」

『时间过得真快。难怪佩特拉会从美少女变成美女。』

「————」

再者，这终究只是佩特拉脑中的“昴”，并非是真正的昴的发言，这一点必须铭记于心。不过，即便是真正的昴，也会说出这种话，而且我也有印象。

虽然知道这不是客套话而是真心话，但除了爱蜜莉娅以外的人也能轻易说出这种话，这让我在各种意义上感到烦恼。

不管怎么说——

「虽然我也担心加夫先生和艾莎先生，但最担心的还是阿尔先生。柯林特哥哥也是因为同样的心情才等在这里的吧？」

「同样的心情，这么说有点不太对。我留在这里的理由，是因为在目送佩特拉她们的时候，我感到有些许违和感。怀疑。」

「些许违和感？」

「嗯。其实我已经告诉过昴大人和碧翠丝大人了。回顾。」

对于佩特拉和梅莉不知道的事情，柯林特忧郁地垂下眼帘。实际上，告诉她们的那两个人都死在了阿尔的手下，所以柯林特应该相当自责吧。

对于他的尴尬，连不认识柯林特的“昴”也感到同情，

『不，越听越觉得是我和碧翠丝的错。因为，克林德先生不是有好好地报告、联络、商量吗？而我们却没有这么做不是吗？结果就是这个，真是无可奈何……』

「昴和碧翠丝酱没有错。昴你闭嘴。」

『我的反省文竟然没有我的意志！』

昴仿佛碰到了不讲理的事情般叹息，但即使是昴自己，佩特拉也不会允许他随意贬低自己。更何况，刚才的说法还把碧翠丝也卷了进来。碧翠丝可爱又坚强，所以没有罪。

只要问了，无论是什么人，她都会毫不犹豫地做出让对方颤抖的偏袒判决。这就是佩特拉・雷蒂的法庭规则，也是佩特拉法官的裁定。

「然后呢？总管在意的是什么事？」

「当时，我也没办法具体指出。能力不足。只是，现在情况已经发展到这个地步，我回想起来……对状况的设定，有疑虑的余地。担忧。」

在梅莉的催促下，克林德依旧低着头，将自己的心象化为言语。

柯林特在意的“状况的设定”，似乎是指在米卢拉目送佩特拉他们离开时，队伍的编制。

「虽然不到不自然的程度。但也是听了说明就能理解的人员。接受。——但是，感觉为了组成这个队伍，必须费劲地通过两三个道理才能成立。意图。」

「意图……」

对于柯林特的说明，佩特拉在口中反复咀嚼着那个单词。

说实话，柯林特含糊其辞避免明言的事实——选择普雷阿迪斯监视塔同行成员的失误，作为自责的理由一直折磨着佩特拉的头脑。

如果和昴他们一起去的不是佩特拉，而是爱蜜莉雅或拉姆、奥托的话，事情就不会变成这样了吧。如果当初按照预定，由法兰黛莉卡代替佩特拉的话，说不定就能防止阿尔的暴行了。

突破奥古利亚沙丘不能缺少梅莉，作为护卫，阵营中最可靠的战力是加菲尔，这两个人是必须的同行人员。

只有佩特拉。只有佩特拉是可替换的成员。

「————」

应该更加强硬地主张才对。主张推迟前往监视塔的时间，或者主张全员一起行动。

当然，从佛拉基亚回来后，应该尽快报告在那个国家发生的事情，而且也不能疏忽对失去依靠的修尔特的心理护理。正是因为觉得需要做出这些正确的判断，所以才会组成现在的成员。

但是，佩特拉没有自信，自己没有掺杂进主观的愿望。

和长时间分离的昴，片刻也不想离开他的想法，以及想为他派上用场的利己功名心。在爱蜜莉娅和雷姆不在的地方，佩特拉是不是希望自己的力量和存在能够支持昴呢？

所以，佩特拉甚至没有注意到，柯林特所察觉到的违和感——

『——佩特拉，不管怎么说，你都考虑太多了』

佩特拉紧紧抓住自己裙摆的手，被『昴』那无法触碰的手重叠，耳边传来温柔的声音。

但是，佩特拉无法坦率地接受昴的话。

『虽然由我来说有点那个，但想和我在一起，这种别有用心的想法也不是没有。不过，那不是坏事。而且就算有那种想法，也只有一点点，百分之一而已。剩下的百分之九十九是佩特拉的温柔，这点我很清楚。』

「讨厌……那也是我自己让脑中的昴说的……」

『被你这么说，我不就什么都说不出口了！？这是禁止卡吧！』

想和自己在一起，这种话自己说出口很害羞，但看到脸颊微微泛红的「昴」这么说，佩特拉长吐一口气。

真的，讨厌被那份体贴轻易束缚的自己。大概，佩特拉不是廉价的女人，而是昴的话太有力量了。

『而且，佩特拉痛苦这件事，有可能不是佩特拉的错，我是这么想的。』

「那是……和阿尔先生太强有关吗？」

『唉，我没看过阿尔实际拿剑战斗的样子，所以可能会说错……不过我知道莱因哈鲁特。』

就算阿尔的实力是未知数，但佩特拉知道这个世界的顶点——莱因哈鲁特的实力。

加菲尔和艾莎都是佩特拉无法企及的高手，既然能打倒那两人，一般都会认为阿尔比他们更强吧。

可是，不管阿尔再怎么强，都敌不过莱因哈鲁特。

『在赃物库第一次看到他时，因为不太了解这边世界的常识，所以才那样……但那家伙就算以这边世界的基准来看，也是个十足的怪物啊。』

「嗯，可是阿尔先生也把莱因哈鲁特先生给怎么样了。因为芙兰姆用加护叫来了莱因哈鲁特先生，这点不会错……」

『至少他没被莱因哈鲁特秒杀。这点是我们的共同见解吧？』

「这件事跟我们两个的组合有什么关系吗？」

『或许有。总觉得光靠很强这理由，很多事都无法解释。』

听了「昴」说出的疑点，佩特拉也慎重思考起来。

确实，莱因哈鲁特是对手的话，不管多强都是五十步笑百步。在力量的强弱大小上，没有人能躲过莱因哈鲁特达成目的。

也就是说，阿尔有达成目的的，除了强大以外的执行力。

『老实说，对阿尔而言，运气好的状况持续太久。』

「不过，运气总是好的人，除了运气以外还有其他理由。」

『就是那样。』

虽然没掌握到核心，但佩特拉认为这部分有掌握的价值。

像这样寻找其他可能性，无处可去的自责念头多少缓和了。说不定这才是昴的真正用意。

「佩特拉酱？你在发呆，没事吧？」

「——对不起，梅莉，我没事。还有，柯林特哥哥。」

「什么事？确认。」

「柯林特哥哥感受到的不对劲，我想没有错。虽然不知道理由，但是不知道那个不对劲的话，谁也阻止不了阿尔先生。」

「——」

「只有我们，只有我们能阻止阿尔先生——要阻止他，然后夺回昴和碧翠丝酱。」

佩特拉手贴着胸口，对柯林特如此强烈诉说。

双手抱胸的「昴」用复杂的表情凝视佩特拉。佩特拉毫不动摇地承受「昴」的视线，相信自己心中的结论，相信到底。

——佩特拉读了《死者之书》。

最糟的情况，昴和碧翠丝有可能被阿尔杀害。有菜月・昴的《死者之书》，一般都会这么想。

「可是，我的昴不普通。」

忍不住说出「我的」，但这是事实。不普通的地方，是事实。

菜月・昴有「死亡回归」这种非常痛苦、难受，而且只有温柔的人才能正确使用的力量。佩特拉推测，昴至今为止的死亡经验，或许就是自己看到的那本。

因为——

「在我看到的书之后，昴真的连一次都没死过吗？」

『——』

面对佩特拉的疑问，「昴」用虚幻的表情不发一语。他也知道。

昴至今为止所建立的辉煌功绩，原本以为是经历了许多苦难才得到的结果，但当佩特拉知道那是比自己想象中还要残酷的地狱套餐时，她不仅没有对昴失望，反而被他的献身精神所感动。

然后同时，她注意到了——昴因为普莉希拉的死而受到的内心创伤有多深。

昴受到了很深的伤害，深到任何人都无法想象。正因如此，他才会责备自己，背负一切，为了阿尔愿意做任何事。然而阿尔却背叛了昴的这份心意，背叛了这份无人能模仿的献身决心。

「佩特拉酱，大哥哥和碧翠丝酱……」

「还活着，绝对。」

「……是啊，他们两个，特别是大哥哥很顽强呢。」

梅莉用微弱的声音低语，轻轻把头靠在佩特拉的肩膀上。

不坦率的梅莉，也打从心底担心昴和碧翠丝。能让周围的人这么想，是昴至今为止所累积的足迹的结果。

『碧翠丝也好梅莉也好，我不知道的我到底做了什么啊。』

明明是自己的事却不知道自己做了什么，『昴』傻眼地嘀咕。看到『昴』的样子，佩特拉放松嘴角，重新面向柯林特。

已经传达了自己的意思，佩特拉用眼神如此诉说，柯林特叹气。

「只有你们能做，是吗？说得真有气势。不过，那股气魄值得一看。佩服。」

「————」

「在『魔女』于世界尽头那样行动的当下，我就已经半放弃，认为事情无可挽回了。反省。但是，既然你们燃起那股斗志——」

「等等，柯林特哥哥。」

柯林特开始回应佩特拉的意志，却被佩特拉中途打断。

那并不是因为话题会变长，或是担心离题——以柯林特的说法，就是无法明确说出口的在意之处。但是，正因为柯林特后悔自己没注意到那个在意之处，佩特拉才无法忽视那个在意之处。

佩特拉在意的是，柯林特的说法。

「我说的是我们。那个我们，也包含柯林特哥哥哦。请不要说得好像事不关己。」

「那是……犹豫。」

「虽然现在是这种时候，但我还是要说。柯林特哥哥，你从以前开始就一直摆出一副自己不属于我们圈子的表情，和我们在一起。我讨厌这样。」

如果他是在退一步的位置，作为大人，作为被需要的人，和佩特拉她们爱蜜莉雅阵营接触的话，那还能理解。

但是，柯林特不一样。他对任何人都一样。

对柯林特仰慕的主人安妮罗洁，对和柯林特像损友一样相处的罗兹瓦尔，对不让柯林特从自己的人生中离开的法兰黛莉卡，都一样。

「这种生活方式，在爱蜜莉雅姐姐的理想王国里是不被允许的。」

「————」

「这可不是别人的事。只要活着，和谁见面说话看到脸的话，不管好事坏事都会不由分说地发生。只有一点点，只挑好的部分，这种狡猾是做不到的，也不能做。」

「佩特拉酱……」

「如果一直这样下去，总有一天重要的东西都会被你抛弃的」

感受着袖子被梅莉碰到的存在，佩特拉喘着粗气，坚定地说道。

中途开始，连自己都不知道自己想说的话有没有好好说出来，想传达的事情有没有好好传达出去。一定是受到《死者之书》昴的影响。

『喂喂，那也是刚刚说的狡猾的一环吧？』

垂下眉毛的「昴」这么说，现在就先无视他，对柯林特——

「重要的东西，全都背对着我，是吗……痛感。」

听到柯林特这么低喃，佩特拉微微倒抽一口气。

那是因为柯林特低喃的声音里，蕴含着非常沉痛的感情，让胸口感到痛楚。不过，更让佩特拉倒抽一口气的是柯林特的表情。

柯林特很少表露出感情。不管是笑容、愤怒还是悲伤，佩特拉都想不到，总之柯林特就是用面无表情来表现那些。

那样的柯林特的表情，出现了变化——那是哀切。

沉痛的声音和哀切的表情。这两者重叠的话，人会用虚幻来形容。

这时，柯林特的表情是虚幻又哀切，怀念过去的表情。

「已经，是乡愁了。」

「柯林特哥哥……」

「佩特拉，我早就已经背对过这一切了。自嘲」

听到他这么说，佩特拉想起了自己刚才的发言，感到羞耻。

自己好像很懂一样，自以为是地说着刚刚才开始理解的感情。明明柯林特早就已经知道那种感觉，还表现得像现在这样。

但是，即使感到羞耻，佩特拉还是想说。

「即使如此……」

「——是的，即使如此。感叹」

「诶？」

「我曾经一度放弃了所有。就算那导致我变得空虚是事实，但在我之后走过的道路上，也有得到的东西，积累的东西。自省。——佩特拉，和你们的关系也是其中之一。天启」

说完，柯林特闭上眼睛，仰望天空。

云朵被撕成碎片，天空仿佛勉强将世界末日推到了另一边，他在那里看到了什么？

「为什么我没有被命令，却因为微小的违和感而留在这里呢？那是因为，我也难以忍受就这样走过去吧。冰解」

「……那个，柯林特哥哥，那是」

「也就是说，佩特拉酱说的没错，对不起？」

「梅莉酱！」

『唔哦哦，梅莉前辈，说得好啊』

梅莉代替困惑的佩特拉，清楚地问出了难以启齿的问题。

佩特拉对此感到惊讶，而“昴”则佩服地喊出了“前辈”这个称呼，即使没有记忆，梅莉和“昴”之间也有不可思议的共同点。

不过，被单刀直入地问到的柯林特，「呵」地轻轻一笑，

「我为缺乏当事人的意识，让你感到不安而道歉。陈谢。在此之上，佩特拉，我要感谢你。大恩。——我也想积极地协助。提唱」

柯林特说完，恭敬地行了一礼，佩特拉的眼睛闪闪发光。

然而，梅莉却像给佩特拉的感激泼冷水一样，继续说道：

「其实管家先生并没有打算妨碍我们，或者不协助我们吧？是佩特拉酱想太多了吧？」

「或，或许是这样没错……」

「不，梅莉，你错了。订正。有当事人的意识，就意味着我会率先提出解决的方案。和旁观者有很大的不同。别人」

『说别人也太过分了吧！』

「也就是说，可以期待到这种程度，对吧？那么！就用柯林特哥哥的不可思议力量，把我们送到大家那里……」

佩特拉向前探出身子，鼓足干劲想要使用柯林特的力量。

实际上，佩特拉在这种状况下最期待的，就是柯林特的『转移』之力。

柯林特的瞬间移动，是追上带着『神龙』不知道去哪里的阿尔所不可或缺的力量。

虽然不知道阿尔的目的地，但带着那么显眼的『神龙』。只要爱蜜莉娅和拉姆她们，老实说虽然讨厌但有罗兹瓦尔的协助的话，一定能找到阿尔，追上他。

佩特拉干劲十足地这么想着，但是——

「很遗憾，我的移动术不是可以无限制使用的。不如说，从限制的意义上来说，是相当不灵活的力量。遗憾。」

「柯林特哥哥是骗子！叛徒！」

『让我们期待，没有那种事！柯林特哥哥的空欢喜！』

「说，说得太过分了，佩特拉酱。我想管家先生也没有恶意。」

看到的光明突然被云遮住，佩特拉和『昴』一起生气。虽然只有一半的怒气传达给柯林特和梅莉，但让他们空欢喜一场是事实。

说起来，虽然不知道原理，但要是不能使用期待的『转移』，就只能让帅哥积极地跟着了。

「那个正确来说不是『转移』，而是空间和时间的『压缩』。说明。本来，应该移动的距离和必要的时间『压缩』。但是，因为可能对世界的存在方式造成很大的影响，所以需要奥德・拉古纳的放水。方便。」

『奥德・拉古纳？那是什么？』

「玛那之类的根源，用昴的知识来说，就是没有意识的神明……大概。」

柯林特突然说出的单词，佩特拉一边向歪着头的『昴』说明，一边也不确定自己的理解是否正确。

佩特拉拜罗兹瓦尔为师，站在学习魔法的立场，虽然也听过关于奥德・拉古纳的讲解，但是否真的理解就微妙了。罗兹瓦尔也说过，很难说他完全理解奥德・拉古纳。

只是，奥德・拉古纳是无比巨大的力量集合体，从某种意义上来说，是与『剑圣』、『神龙』、『嫉妒魔女』这些拥有力量的存在处于不同位置的某种东西。

「那个，如果不能骗过奥德・拉古纳的话，会怎么样？」

「不清楚。不清楚这个事实很可怕。震撼。」

柯林特缓缓地摇头，回答梅莉的问题。

从他的回答中感觉不到敷衍或岔开话题的意思。也就是说，看起来无所不知的柯林特，和罗兹瓦尔有着相同的见解。

但是，如果是这样的话——

「柯林特哥哥，你至今为止做过几次了吧？按照刚才的话，就是骗过了奥德・拉古纳……该怎么做才好？」

「佩特拉……」

「因为有那个方法，柯林特哥哥才能使用力量。需要什么？比如说……使用魔法需要玛那。让精灵服从需要契约。那么，让奥德・拉古纳做些什么也需要代价吗？」

「——你这孩子，真的让我很惊讶。脱帽。」

柯林特的反应，证明了佩特拉的推测是正确的。

也就是说，通过向奥德・拉古纳献上代价，就能得到使用柯林特那超乎寻常的力量的许可。按照柯林特的说法，就是睁一只眼闭一只眼。

『也就是贿赂和私下交易吗？……真是超俗气的，明明是神明大人』

对于一脸不悦地嘀咕着的『昴』，佩特拉也完全同意。但是另一方面，比起什么也不做就给予施舍的神明大人，佩特拉觉得要求代价的神明大人更值得信任。

最重要的是，佩特拉“死心塌地”地知道，这个世界并没有简单到不付出代价就能得到想要的东西。

所以——

「告诉我需要什么，柯林特哥哥。不管是什么，我都会准备的。这是为了昴和碧翠丝，为了大家」

「哎呀，佩特拉真是奇怪。你刚才不是说“我们”吗，而不是“我”」

「——抱歉抱歉。但是，谢谢你」

梅莉抱着下定决心的佩特拉的手臂，佩特拉向她微笑。

回想起来，佩特拉完全没想过自己能和梅莉发展成这样的关系。当梅莉被囚禁在宅邸的牢房时，佩特拉之所以经常去见她，是因为她被梅莉的真情打动，打算让她不再成为危险的存在。

她从未想过梅莉会像这样陪伴着独自下定决心的佩特拉。

而这一切，都是佩特拉从他那里得到的。

「——可能性。回答。」

在佩特拉和梅莉面前，柯林特停顿了一下，然后如此说道。

他之所以停顿了一下，并不是因为犹豫着是否要将残酷的事实告诉少女们，而是为了将佩特拉她们视为面对同一个问题的同伴，点燃坦白的觉悟。

「对世界，对奥德・拉古纳可能造成的影响，可能性，以此作为代价。这就是我所拥有的『忧郁』魔女因子的权能，其使用的条件——坦白。」

3

「——可能性，作为代价。」

佩特拉在口中确认着被告知的内容，皱起形状优美的眉毛。

可能性，这是为了使用柯林特所拥有的不可思议力量『转移』，必须交换的东西。比方说庞大的玛那，或是稀有的魔晶石，她原本想象的是这种简单易懂的代价——

『代价是可能性，什么鬼啊』

和佩特拉抱有同样的疑问，『昴』利用自己没有实体的优势，在空中转来转去，全力表达柯林特的说明不足。

当然，只有佩特拉能看到他可爱的抗议。

『话说这个人，说了“忧郁”的魔女因子？说了吧？魔女因子就是那个吧，艾姬多娜说过的，听起来就很不妙的关键词之一！』

「……我对那个『强欲魔女』没什么好印象，不知道能相信她到什么程度」

『不，嘛，那家伙就像你看到的那样，是容易产生误解的类型。虽然我也没有完全信任她，但只要想到这是她社交能力低下的表现，看法多少会有些改变吧。毫无疑问她是个坏人。坏人』

「是啊。用我的手帕……没什么」

『昴』将注意力放在代价以外的部分，声音颤抖着。佩特拉垂下眼帘。

在《死者之书》中看到的绝望景象，以及为了结束这一切，『魔女』所准备的，昴所选择的方法，对佩特拉来说是绝对不想说出口的。虽然不想直视，但也不能移开视线，这正是麻烦之处。

不管怎么说——

「魔女因子，也就是说，管家先生也是大罪司教吗？」

在某种意义上，天然呆且不懂察言观色的梅莉，切入了这个难以启齿的内容。

在阅读《死者之书》之前的佩特拉，对这个单词没有印象，但梅莉似乎有机会在某处得知了魔女因子。魔女因子和『魔女』——进一步来说，和大罪司教的关系，佩特拉也觉得必须问清楚。

『如果这位克林德先生和培提尔其乌斯一样是大罪司教的话，刚才为止的和谐对话能相信到什么程度呢……』

「原谅了曾是『暴食』大罪司教的丝碧卡的昴，有资格说这种话吗？」

『你在说什么啊！？我怎么可能原谅让雷姆遭遇那种事的「暴食」啊！？』

「……你还是暂时看看我最近的记忆比较好」

虽然和碧翠丝的关系也是如此，但佩特拉所看到的『死者之书』中，昴的时序和现在的昴在知识和关系性上有着很大的偏差。回想起来，昴有时会说艾姬多娜的坏话，所以可以推测在佩特拉不知道的范围内，昴和艾姬多娜之间发生过很多事。

毫无疑问，那是个坏女人，佩特拉的直觉是正确的。——在脑内会议的旁边，佩特拉和梅莉一起警惕地看着柯林特。

虽然相信柯林特不是坏人，也知道丝碧卡这个大罪司教的前例，但像爱蜜莉亚那样毫无保留地相信对方又是另一回事了。爱蜜莉亚的纯朴既可爱又有魅力，希望她能继续成长下去。

「梅莉的怀疑是理所当然的，但我不是大罪司教。否定。说到底，『忧郁』的魔女因子是例外的东西。范围外。就算适合这个因子，也不会成为『魔女』或大罪司教。排除在外」

「例外的，魔女因子……」

「以前的持有者……适合『忧郁』的魔女因子的人，自称『忧郁魔人』。自称……不，是被称作。那个人并不拘泥于称呼方式，只是觉得这样称呼比较合适，他的妻子才这么称呼他。爱称」

「魔人……」

『不是魔女而是魔人吗！我懂。我还担心要是你说是魔男该怎么办呢』

『昴』似乎很中意这个称呼，他弹了弹手指表示佩服。另一方面，佩特拉嘴里嘟囔着这个词，同时看向柯林特。

「那么，柯林特哥哥也是『忧郁魔人』吗？」

「不。否定。我没有适合『忧郁』的魔女因子。因此，要引出『忧郁』的权能需要代价。不适。本来，适合魔女因子的人行使权能不需要代价。这是奥德・拉古纳认可的，改写世界的权利。官方说法」

「改写世界的权利啊。虽然经常听到，但奥德・拉古纳也真是的，真希望他能再挑挑人选再给啊」

『我同意梅莉』

梅莉不满地嘟起嘴，『昴』用无法触碰的手抚摸着她的头，佩特拉则用手指抵着嘴唇，整理着至今为止的对话。

柯林特既不是大罪司教，也不是『魔人』，我想相信他。

然后，魔女因子带来的特殊力量是权能。适合者可以随意使用，而不适合者使用则需要代价，我也接受了这个规则。

然后，柯林特的权能不是『转移』而是『压缩』，使用需要代价的话。

「比如说，柯林特哥哥持有的魔女因子如果由其他人……由我来使用的话，就算不支付代价也能随意『转移』吗？」

『佩特拉！那绝对是糟糕的家伙，所以别这么做！』

「为什么？昴也明白吧？昴的『死亡回归』，绝对是柯林特哥哥所说的特别的力量……权能哦。」

『那是……』

因为有头绪，『昴』苦着脸沉默下来。

在与艾姬多娜的茶会上，昴被指出体内有魔女因子。当时认为是之前打倒的『怠惰』大罪司教的，但只要想象『嫉妒魔女』执着于昴的理由，就是自明之理——菜月・昴也是『魔人』。

「那么，我就算变成『魔女』也无所谓。和昴在一起的话，就没什么好怕的。」

『……说不定是我太武断了。我的『死亡回归』和权能没有关系，是那个，还没有露面的，异世界故事里经常出现的神明的赠礼』

「昴虽然经常隐瞒事情，但很不擅长说谎呢」

所以，为了不露出马脚而隐瞒事情，避免交谈吧。

如果能和这么温柔的人在一起，就算是世界的敌人也不可怕。

「——很遗憾，这个方法不能采用。否决」

但是，佩特拉的决心被没能成为『魔人』的男人否决了。

「——为，为什么」

「首先，佩特拉不可能适合『忧郁』的魔女因子。还有，『虚饰』的因子是缺号……不，应该说是番外。这些是为唯一一个适合者——勇者和圣女调律的。特制。其他人是不适合的。而且」

「……而且？」

「就连适合的人，也无法逃脱精神的堕落。羞愧」

柯林特垂下眼帘，抿紧嘴唇。从他的反应来看，佩特拉感觉他认识那两个适合者——勇者和圣女。更进一步来说，『忧郁』的魔女因子唯一适合者，陷入精神堕落的『忧郁魔人』，正是那个勇者。

然后，如果柯林特拥有那个『魔人』的魔女因子，那么勇者已经——

「好啦好啦，我知道你们在谈很重要的事，但是佩特拉酱危险的决心也不行，所以回到正题吧？」

「危、危险……」

「很危险啊。就算佩特拉酱被魔女因子看上，我也绝对反对。不可以跟那种东西交好。」

没有恶意，知道那是打从心底担心佩特拉的话。但是，很讽刺。

『——』

垂下眉梢，用说是复杂又太过温柔的表情凝视梅莉的『昴』。

在『圣域』和罗兹瓦尔宅邸发生的事件，以及在那场混乱中被逮捕，梅莉跟那件事——在『死者之书』看到的佩特拉和法兰黛莉卡之死有关。

佩特拉和梅莉的关系，没有以单纯的『死亡』受害者和加害者结束，正是多亏了昴的『死亡回归』。

所以佩特拉无论如何都会觉得，力量也是有其用处的——

「……嗯，我知道了」

「是吗。真是个好孩子」

听到佩特拉的回答，梅莉明显松了口气。佩特拉握住她的手，点了点头。

不管怎么说，如果『忧郁』的魔女因子不适合佩特拉，就无法采取代替柯林特成为因子持有者，无视代价的作战。

如果昴是『魔人』，佩特拉就是『魔女』，这只是单纯被吸引的场景，没有好处的话就应该废案。

「梅莉说得对，回到正题吧。复刻。不管怎么说，根据我说明的经过，需要支付代价。而代价就是，对世界造成的影响。可能性」

「——请再详细一点」

「比如说，有一个咏唱就能生火的魔法。其便利性自不必说，这个魔法开辟了许多未来。有望。烹饪，医疗，雕金，锻造，战争……不胜枚举。庞大。这就是影响力，可能性。然后——」

「……如果把那个魔法作为代价，因为那个魔法而产生的所有可能性都会消失？」

「相对的，世界会留下本来应该使用的可能性。只有那个余地，那个空白，才能行使不适合的『忧郁』的权能。完毕」

听到这个总结，佩特拉理解了柯林特已经完成了必要的说明。

她明白了。——简单来说，就是资源的问题。奥德・拉古纳管理着用于世界运行的资源，而其是有限的。

本来已经用尽的资源，通过支付代价来留下剩余，然后偷偷使用那些剩余，这就是使用柯林特的权能的条件。

聪明又可爱的佩特拉明白了这一点，又注意到了另一件事。

「……我们去帝国的时候，柯林特哥哥使用了很多权能吧。那个代价呢？」

「——是老爷。保密」

「……真是讨厌」

对于这个不想知道的答案，佩特拉的眼中充满了愤怒和憎恶。

在那个状况下，阵营的所有人为了帮助昴他们而全力以赴。碧翠丝相信能与昴再会而持续沉睡，奥托不惜扭曲自己的主义去拜托老家。爱蜜莉雅拼命展示方针，当然佩特拉也尽了自己所能。

明明如此，付出最大代价的却是不愿说出这个事实的罗兹瓦尔，这对佩特拉来说是无比的屈辱。

『怎么说呢，是赎罪的心情吗？像是对「圣域」和宅邸的事感到抱歉之类的。』

「我认为不是那么好懂的心情，所以才讨厌老爷……！」

『嗯——佩特拉的愤怒，非常合理。』

『昴』举起双手，理解佩特拉即将喷火的愤怒。

对罗兹瓦尔的不满累积至今。然后，罗兹瓦尔满足柯林特的权能使用条件，也是适当的人才，这点佩特拉也认同。

「如果是老爷，魔法和魔造具，能作为代价的东西有很多。」

当然，不是说有很多所以不管付出多少都无所谓。

虽然不知道奥德・拉古纳是否会把感情的多寡纳入评价，但只要不放手，就是能对世界造成影响的“可能性”。无论是什么，佩特拉都不认为没有感情的东西能推动世界。

——“可能性”需要热情和感情。

用不包含这些的代价换取简单的救赎，这种投机取巧的想法，不可能取回真正重要的东西。

所以佩特拉——

「——我愿意献出任何东西哦。」

可能是和佩特拉有了同样的想法，梅莉静静地提议。听到这句话，『昴』惊讶地眨了眨眼，梅莉则继续说道：

「因为我能活着，追根究柢也是多亏了哥哥你们的放水。虽然不是想报恩，但这样不是很简单明了吗？」

『佩特拉，阻止这孩子……梅莉！我不知道她和现在的我之间发生过什么，但我不是为了这个才救她的！』

「嗯，是啊。」

虽然『昴』脸色大变，但佩特拉却轻易地接受了。

昴帮助梅莉并不是因为想让她勉强自己，或是让她在某处报恩，他肯定只是单纯想帮助她。

昴应该不会让梅莉做出封闭可能性的事。

「梅莉不行。梅莉能给出的东西中最有价值的就是操纵魔兽的加护，但要是没有了那个，梅莉就毫无价值了」

「哎呀！佩特拉真是的，好过分」

「抱歉，说毫无价值是说过头了。梅莉就只是个可爱的女孩子」

说实话，昴和爱蜜莉娅她们应该会说那样也没关系。但是，梅莉自己却无法接受自己只是个可爱的女孩子。

佩特拉对此深有体会——可爱的女孩子并不能像周围的人所想的那样，只是个可爱的女孩子。

「——佩特拉大人，梅莉大人」

这时，突然传来了一个声音，佩特拉她们猛地回头看向龙车。在那里，从龙车的货架上跳下来，朝这边跑来的少女——菲拉姆的身影。

在奥古利亚沙丘移动途中，自发性失去意识的她醒来了。芙拉姆失去意识的经过，和她的加护有关——

「芙拉姆，你醒了真是太好了。身体还好吗？」

「没事。比起这个，『念话的加护』的使用条件已经满足了。能和妹妹……格拉西丝取得联络。我想也能和菲鲁特大人和拉珍斯大人他们沟通。」

芙拉姆只确认了佩特拉的安危，迅速传达加护的状况。

明明一醒来，就会想和莱因哈鲁特与「嫉妒魔女」的冲突有关的人取得联系，却忍住没这么做，对此佩特拉只有感谢。

毫无疑问，收到芙拉姆联络的菲鲁特阵营，也会知道阿尔的暴行，为了解决问题而行动。

『莱因哈鲁特无法行动，能仰赖菲鲁特和罗姆爷到什么程度还是未知数……』

「——不，不能拘泥于只靠我们自己做。」

『佩特拉……』

「这已经不是我们的问题，而是王国所有人的问题了。」

阿尔失控，菜月・昴和碧翠丝被掳走——事态已经不是这种微观的问题，而是该认为陷入了「剑圣」和「神龙」、「嫉妒魔女」混战，国家规模、世界规模的状况。

因此，最了解状况的佩特拉他们不该吝于提供情报。

「菲拉姆，马上去问菲鲁特大人他们的所在地。只要有我柯林特哥哥在，只要知道地点就能会合。」

「——明白了。」

听了佩特拉整理好顺序的指示，菲拉姆看了柯林特一眼，忍住想问清楚详情的心情，立刻答应。

「佩特拉？」梅莉拉了拉她的袖子。

「还没谈好给总管的报酬哦。」

「——不，那方面我已经决定了。」

「咦咦？」

梅莉对这答案瞪大双眼。佩特拉温柔地松开她抓着袖子的手指，迅速靠近柯林特，斜眼看向「昴」。

即使知道他目不转睛盯着佩特拉的行动，是自己一厢情愿的幻影。

「稍微塞住耳朵。」

听到佩特拉的请求，「昴」停顿了一下，然后老实地照做。然后「昴」塞住耳朵，佩特拉踮起脚尖，直接把嘴凑到柯林特的耳边，悄悄地对他耳语。

那是——

「——这个，能作为报酬吗？」

佩特拉放下脚跟，压低声音询问，柯林特凝然地瞪大眼睛。佩特拉歪着头，做出自己都觉得超级可爱的动作，看到她的样子，柯林特叹了口气。

他深深地长叹一声，摘下单片眼镜，用真实的面貌重新注视佩特拉。

「可能吧。概算。但是，佩特拉，那是——」

「太好了。」

「————」

「虽然我早就知道了——我有能推动世界的『可能性』」

佩特拉堂堂正正地挺起胸膛，不让柯林特再说下去。

只让柯林特听到的问题，得到了答案。对于那个答案，佩特拉得意洋洋——柯林特是柯林特。虽然他的评价不一定和欧德・拉格纳一致，但至少，柯林特认可了那个「可能性」的价值。

「我会付出代价的，柯林特哥哥。我们，要拯救世界……不对，世界什么的其实无所谓。我只是想拯救重要的人们」

「——我明白了，佩特拉。在所有我认识的少女中，你是最勇敢的少女。佩服」

深深地行了一礼，柯林特就像对安妮罗洁和罗兹瓦尔那样，或者说就像对真正觉得出色的人那样，如此说道。

对此佩特拉回以微笑，然后注意到梅莉注视着自己的视线。看到她圆圆的眼睛里带着些许不安，佩特拉轻轻将她抱到怀里。

「虽然我不懂，但佩特拉酱一定是个大笨蛋」

「呵呵，好过分。我头脑聪明，又可爱又帅气哦」

佩特拉这样回应了说话难听的梅莉，然后越过怀中的梅莉的肩膀，看向无所事事地站着的「昴」。

「昴」终于把手从耳朵上放了下来，看着那不管怎么看都可爱得不得了的脸，佩特拉更新了自己史上最高的可爱度，说道。

「昴，最喜欢你了」

** 第六章 『引力』

1

柯林特的「转移」——本人说是「压缩」，佩特拉已经一个月没体验，梅莉则是几天没体验过了。

「第一次或许会吓到，但不用怕哦。」

佩特拉基于经验者的立场，给没体验过的菲拉姆建议。

这是担心若不先说明接下来会发生的事，可能会让她陷入恐慌。不过对此，菲拉姆却摇头回答：

「不，您不必担心，大部分的事都比不上少爷惊人。」

『那家伙连自己人都把他当惊吓箱哦？到底有多夸张啊？』

听了这过于坚强的答案，「昴」也傻眼地回应。

不过佩特拉透过「死者之书」共享的记忆中，也看过莱因哈鲁特一剑劈飞建筑物，踹飞梅莉的姐姐，因此能理解芙兰姆彻底习惯超乎常理事物的态度。

「就算芙兰姆妹妹没问题，希望睡着的医生先生不会晕过去呢。毕竟小红蝎第一次被管家先生传送时，可是慌得不得了哦。」

「说起来，转移的时候好像会晕车呢。在佛拉基亚的时候，小丝碧卡的『转移』好像也有人能接受，有人不能接受」

梅莉耸了耸肩，她头发里蠕动着的小红蝎模仿主人的动作，也耸了耸钳子。

佩特拉的疑问让梅莉想起了留在帝国的丝碧卡的『转移』——那是因为体质的原因吗？不管强弱，不行的人就是不行。佩特拉是没问题的，但加菲尔不行，他当时还蜷缩着闹别扭。

对于佩特拉的疑问，柯林特竖起手指说：

「是的。思考。虽然尝试的次数和人数都不多，但目前为止没有人身体不适。放心。严格来说，『忧郁』的权能不是『转移』，而是将本应花费的时间和距离『压缩』的结果。省略」

「不管听多少次都听不懂啊」

『也就是说，就像游戏中的快速旅行一样。不，快速旅行也有时间流逝的游戏……可恶！应该有更好的例子！』

「不用担心会晕车，而且是能创造出我们现在最想要的时间的力量。只要知道这些，现在就足够了」

对于歪着头的梅莉和追求自己解释的『昴』，佩特拉如此下结论。

虽然好像理解了『昴』的说法，但现在没有时间去思考这些。如果时间允许的话，她想好好确认流入的记忆和知识，成为对昴无所不知的自己——

「柯林特哥哥，可以拜托你吗？」

别说满足这个愿望了，现在连抱有这个愿望的时间都没有，佩特拉催促着柯林特。

「嗯，我会适时出手」柯林特点头回答，单片眼镜的镜片闪闪发光。考虑到接下来要发生的现象，他轻松可靠的态度令人安心。

「那个」佩特拉正感到佩服，梅莉拉了拉她的袖子。

「佩特拉酱，关于刚才说的代价」

「——没关系，柯林特哥哥已经保证了」

「不是的……虽然我自己也不知道为什么，但如果佩特拉酱必须承受损失的话，我不要」

梅莉似乎对自己的感情感到不知所措，佩特拉听到她的话后眨了眨眼。

朋友直率的担心，以及柯林特所提出的代价的评价——此时，佩特拉心中来来去去的感情，复杂而丰富到了极点。

然后，佩特拉对梅莉微笑，

「谢谢你，梅莉酱。不过，我真的没事的」

「……你要是骗我的话，我会很伤心的」

梅莉思考到最后挤出的威胁，其笨拙让佩特拉微笑着点了点头。

佩特拉小心翼翼地将被松开的袖子抱在胸前，然后寻找着『昴』的身影。虽然她不会丢下幻影的他不管，但这是心情的问题。

当她找到那半透明的背影时，『昴』正远远地眺望着沙海。

『如果我能再振作一点，就不会让那家伙受苦了』

东方的天空——空气发出悲鸣，天空的颜色令人鼻酸。在大地、世界被削去的声音轰鸣的战域，『剑圣』和『嫉妒魔女』的战斗仍在继续。

那是决定世界趋势的激烈战斗。然而，『昴』却在担心朋友，后悔自己的无力。对于『昴』这种无法置身事外的生存方式，刚刚才被尊重了隐瞒之事的佩特拉，内心被悲伤刺穿。

极端来说，他存在于佩特拉的脑中，应该无法隐瞒任何事，只要他有那个意思，就能将佩特拉塞住耳朵的情报全盘托出。

可是，想象中的昴没有那么做——那是出于『昴』的良知和体贴，还是自己想让他听话的意志呢？自我意识、爱意和记忆混杂在一起的佩特拉无法判别。

不过，不管哪一种都无所谓，佩特拉是这么想的。

就算是体贴，就算那是佩特拉期望的结果，『昴』的生存方式，都是佩特拉・雷蒂眼中的菜月・昴的参考。

所以——

「克林德哥哥，麻烦你了。」

「——遵命。……赞赏。」

佩特拉怀着对『昴』的爱，向克林德打暗号。

佩特拉和梅莉，还有菲拉姆。加上拉龙车的帕特拉修，以及意识不明的加菲尔和艾莎，总共五人一龙——再加上『昴』和小红蝎，追加一只一具，一行人在柯林特的帮助下开始行动。

为此，佩特拉提议的『代价』被献给了奥德・拉格纳——

「————」

瞬间，世界如字面意思，眨眼间切换，『压缩』完成。

闭上眼睛，睁开时景色为之一变。舌头和皮肤感受到的空气味道，以及嗅觉接触到的世界气味都截然不同，佩特拉切实感受到权能被使用了。

「————」

一瞬间，佩特拉闭上眼睛，思考自己开始奔跑的事实。

但是，一秒的祈祷将感伤放在架子上，意识转向眼前的事。从现在开始，佩特拉他们没有时间浪费在原地踏步上。

没错，佩特拉重新振作精神——

「哇啊啊啊！？怎、怎么了怎么了！？龙车突然冲出去了！？」

「莱、莱因哈鲁特吗！？这种胡闹的举动，只有那家伙做得到吧！」

「我还在做梦吗？托托！托托！借我柔软的膝盖！」

「啊啊，吵死了！你们在吵什么……从，从哪冒出来的！？」

佩特拉的干劲被泼了冷水，从『压缩』的目的地传来了吵闹又不冷静的盛大欢迎。

『啊咧！？罗姆爷爷就算了，加斯顿拉珍斯汉巴里！？是加斯顿拉珍斯汉巴里！为什么他们也在一起！？Why！？』

另外，最先对这盛大欢迎做出反应的『昴』，也因为这预料之外的惊讶而大声叫了出来，最后补充一下。

2

「佩特拉酱！梅莉！你们两个没事吧！？」

「——」

『爱蜜莉娅碳……！』

看到脸色大变，冲到佩特拉她们身边的爱蜜莉娅，佩特拉感受到自己心中甜蜜的感情爆发性地扩散开来。

胸中充满了温暖又甜蜜到令人麻痹的感情，脑中溢出了赞美她的美貌和可爱的华丽词藻。这份感激不仅赞美了她的容貌，还赞美了她的举止和说话方式，最后连脚步声都赞美了。

「好露骨……」

佩特拉被这明显又强烈的情感大浪所吞没，脑袋晕乎乎的。

至今为止，因『死者之书』的影响而产生的最大变化毫无疑问是想象昴的存在，但这次的爱蜜莉娅冲击足以与之匹敌。

直白地说，爱蜜莉娅泽的过度摄取可能会危及生命——

「我到底在说什么蠢话……！」

意识突然被拉走了一半，佩特拉强行抓住自己快要消失的衣领，勉强停留在现实之中。

虽然早就知道了，但对爱蜜莉娅的爱实在是溢出太多了。

虽然这件事本身也让她感到焦躁和嫉妒，但更重要的是，佩特拉明明也很高兴能和爱蜜莉娅再会，但自己对爱蜜莉娅的重视却被挤到一边，这令佩特拉感到很不满。

所以佩特拉忍住自己想对发现她们，带着美丽到令人惊讶的容颜，眼中含泪跑过来的爱蜜莉娅使用Ｅ・Ｍ・Ｔ的心情，张开双臂。

然后——

「爱蜜莉娅姐姐大人……！」

「姐姐大人！？」

舌头突然打滑，在感动的再会之际吓到了爱蜜莉娅。

差点就叫出「爱蜜莉娅碳」，虽然想立马修正轨道，但还是失败了。真是的，这完全不是佩特拉会犯的错误。

不管怎么说——

「但是，太好了……你们两个都来见我了」

「嗯。爱蜜莉娅姐姐大人也平安无事，真是太好了」

被感动至极的爱蜜莉娅抱紧，佩特拉也抱紧她，如此回答道。

在佩特拉的另一边，同样被抱紧的梅莉则说着「喘不过气了……」，做出了不坦率的反应，战战兢兢地把手绕到爱蜜莉娅的背上。

『唔哦——！看到平安无事的爱蜜莉娅碳，我真是松了一口气！咦？稍微离开一会就变得可爱了？成长空间很大？』

从各种角度眺望着拥抱佩特拉和梅莉的爱蜜莉娅，浮在空中的“昴”很是感激。太兴奋了。不过，这也是没办法的事。

毕竟，在《死者之书》的时间点上，『昴』最后所知道的爱蜜莉娅，是在『圣域』里变得非常虚弱的她。当时，佩特拉和爱蜜莉娅还没有像现在这么要好，所以没能帮上她的忙。连佩特拉都对此感到后悔，那么近距离地体会过那种滋味的『昴』，心中的悔恨就更不用说了。

『啊啊！不好了，佩特拉！快看！爱蜜莉娅碳精神满满地走着呢！』

「是啊。她正用那双长腿走着呢。太好了」

『太好了……！真的太好了……！』

因此，佩特拉也犹豫着要不要对感动得颤抖的『昴』泼冷水。一边对『昴』感激的样子做出适度的回应，佩特拉一边暗自松了口气。

她松口气的理由之一——是看到爱蜜莉娅后，自己没有感到害怕。

「在《死者之书》里看到的，最后的景色……」

沉入影子的『圣域』，被无法逃脱的执着所捕获，抓住『魔女』准备的像是恶作剧一样的手段，对自己的性命下手的菜月・昴。

在那个最后的瞬间，昴＝佩特拉看到了——可怕的『嫉妒魔女』，和自己最喜欢的人有着同样的脸。

「————」

想要深入思考那个理由，就像把手伸向雾霭一样，无论如何都无法好好地思考。即便如此，鲜明地烙印在心中的感情还是无法剥落。

所以，她害怕与爱蜜莉娅再会。——不对。正确来说，是害怕自己可能无法像以前一样看待爱蜜莉娅。

「但是，没有变成那样真是太好了……虽然在不同意义上，让我心跳加速了」

「诶？佩特拉酱，怎么了？」

「没什么。能和爱蜜莉娅姐姐再会，我很开心」

佩特拉隐瞒了内心的纠葛，发自内心地为与爱蜜莉娅再会而感到高兴。爱蜜莉娅对此瞪大了眼睛，但还是微笑着，小红蝎代替主人在不坦率的梅莉头上高兴地敲响了钳子。

就在这时——

「——想说怎么这么热闹，小姑娘，你来了啊」

这时，一个低沉沙哑的声音插了进来，爱蜜莉娅发出“啊”的一声惊呼。

爱蜜莉娅冲进来时打开的房间入口，一个高大的人影站在那里敲了敲门，往里面看。那个人影是——

「菲鲁特的爷爷！」

看到老人罗姆爷穿过入口，爱蜜莉娅眨了眨眼。听到爱蜜莉娅的声音，罗姆爷摸摸自己的秃头苦笑。

「照你的说法，好像真的有血缘关系……周围的人都叫我罗姆爷，像这样好好说话还是第一次。」

「呃，对啊。在王选开始那天的城堡里没能说上话，徽章被菲鲁特偷走的时候，也没办法冷静下来好好说话……」

「……不用那么在意我，我明白情况的。」

回应罗姆爷的招呼，爱蜜莉娅担心怀中的梅莉，当事人梅莉则是以一半厌烦一半担心的态度回答。

刚刚两人的对话，是爱蜜莉娅和罗姆爷的接触点——以前，菲鲁特从爱蜜莉娅手中偷走参加王选资格的徽章时，梅莉的姐姐艾尔莎也有参与，梅莉在意的就是这件事。

这么一想，这三人的缘分意外地奇妙。加上「昴」的话，就是四人的奇妙缘分。要是连莱因哈鲁特都算进去，那可就没完没了。

「小姑娘……以现在的立场，这样称呼也不太好。可以叫你爱蜜莉雅吗？」

「嗯，可以。请多指教，罗姆爷。」

『哦哦……这两人好好地自我介绍，感觉是历史性的瞬间呢。』

「太夸张了。」

看着握手致意的爱蜜莉雅和罗姆爷，『昴』说历史性的瞬间这种大话，让人觉得好笑。

确实有点感慨，但那种说法简直像是目击到十年以上没有交流的两人重逢一样。

就这样，『昴』的感激先摆到后面——

「菲鲁特的事我也听说了，罗姆爷你们也很辛苦吧？」

「嗯，是啊，这方面的事想先磨合一下。佩特拉。」

「是啊，我想柯林特哥哥还要再过一阵子才会回来，这边可以先开始……因为要跟时间赛跑。」

最后佩特拉补充，爱蜜莉雅和罗姆爷同时深深点头。

没错，跟时间赛跑。为此，佩特拉他们甚至不惜使用犯规手段。

——现在，佩特拉他们齐聚一堂的地方，是王都露格尼卡的王侯馆。

爱蜜莉娅阵营的成员各自分散行动，虽然爱蜜莉娅的所在地很明确，但要说以谁为中心聚集的话，除了爱蜜莉娅以外别无他人。

佩特拉这么想着，用柯林特的“压缩”和罗姆爷他们汇合后，火速飞到了王都——

「王都的荒废程度连老朽都感到吃惊。」

「我也好久没来王都了，之前来的时候街道上没有这么破烂，也没有那种奇怪的物体」

罗姆爷抱着粗壮的手臂说道，眺望窗外的梅莉也跟着说道。

和有经验的两人不同，佩特拉是第一次来王都。幸好，刚才想起的赃物仓库在王都的贫民街，佩特拉靠着记忆，也能够比较出王都健在时和现在的王都。

确实，记忆中的王都没有那么多华丽的冰塔，贵族街的气派房屋也没有那么凌乱。

「虽然老朽讨厌贵族街，但没想到贵族街会变成那样。根据听到的消息，那里的人已经避难了，真是不得了啊」

「梅莉也说了，那些冰塔是爱蜜莉娅姐姐弄的？」

「啊，那个，是的，我弄的，但我是有理由的！因为大家很危险，我完全没有余力去控制……！」

从勉强没事的王侯馆向外望去，王都的街道发生了巨大的变化，被指出这一点的爱蜜莉娅慌慌张张地想要解释。

佩特拉一边觉得她慌张的样子很可爱，一边和罗姆爷一起，将发生的事情一件一件地梳理清楚——

「——那么，果然是阿尔先生」

「……是的。因为我没能阻止阿尔，所以街道也变得乱七八糟了」

「这不是爱蜜莉娅姐姐的错。那些冰塔也是，如果爱蜜莉娅姐姐没有做的话，王都的人们就麻烦了……所以，E・M・G（爱蜜莉娅碳・真的是・守护天使）」

「嗯，佩特拉，谢谢……诶？你刚才说什么？」

对于自责的爱蜜莉娅，佩特拉用力地摇头否定她的责任。

听到袭击王都露格尼卡的大灾害也和阿尔与波克肯尼卡有关，佩特拉反而觉得自己有责任。说到底，如果在以阿尔的恶作剧为出发点的普雷阿迪斯监视塔那里阻止了他的话，就不会发生这些事了。

「要这么说的话就没完没了了。大家都有点被那个头盔先生给骗了。错的是头盔先生和他的同伴吧？」

「是啊。为了弥补不足之处而反省是好事，但后悔自己的能力不足是没用的。这就是所谓老年人的经验之谈」

「——嗯，我觉得你们两个说得对。做坏事的是阿尔，他必须为此负责。我们没有时间在这里唉声叹气了！」

听了梅莉和罗姆爷的话，爱蜜莉娅绷紧了脸，重新振作起来。看到爱蜜莉娅的反应，佩特拉轻轻叹了口气，然后用力地鼓起肚子。

大家说得对，假装反省的软弱是坏习惯。路，永远只在前方。

『阿尔应该也是这么想的吧……不然他也不会做出让大罪司教越狱这种越界的行为。那家伙到底在想什么啊？』

阿尔察觉到佩特拉的心情，因他在王都的暴行而皱起眉头。

实际上，唆使波克肯尼卡，给王都带来巨大伤害也是不得了的恐怖行为，但知道他真正的目的——帮助「暴食」越狱后，这些事就显得微不足道了。

对佩特拉他们来说，「暴食」大罪司教是因缘匪浅的对手，没想到他竟然逃走了。

「那家伙干的好事随便列举一下，就让人觉得快昏倒了。攻击王选候补的相关人士，绑架一名骑士，让王国的守护者『神龙』波克肯尼卡倒戈，利用『嫉妒魔女』封住『剑圣』的行动。不仅如此，还以一名王选候补者为人质潜入王都，导致贵族街半毁，让被囚禁的大罪司教越狱。」

『这很不妙吧？要判几年？』

「感觉会被判死刑一百次……」

重新审视阿尔——不，阿尔一伙的罪状之多和严重性，实在非比寻常。

看起来简直像是要将这世上所有坏事都做一遍的气势，但佩特拉认为那并非自暴自弃，而是基于计划。

没错，阿尔有计划。他只是在为计划的实施而进行必要的准备，而这些准备碰巧都是些世纪大犯罪。

「没有大罪司教就无法实施的计划，还是从头开始重新考虑比较好吧？」

「毕竟还有『嫉妒魔女』，完全没法辩解呢……」

说到底，佩特拉也没必要替他辩解。

从《死者之书》给人的印象来看，昴似乎也把阿尔当作同乡——不讨厌的对象，但阿尔的所作所为已经远远超出了可以原谅的范围。

关于这点，可以说是在场所有人的——不，包括不在场的人在内，所有相关者的共同见解。

「现在，我让克林特哥哥去叫法兰黛莉卡姐姐她们了。爱蜜莉娅姐姐，奥托先生呢？」

「——啊！呃，那个，奥托他，现在，那个，很忙」

「看你的反应我就明白了。他又在乱来了吧」

「呜呜……是的，就是这样。没能阻止他，对不起」

爱蜜莉娅垂下眼帘，一副觉得自己很没用的样子。但是，爱蜜莉娅并没有错。要说有错的话，那就是奥托了，不过这次的事件他也没有错。

奥托在阵营中本来就经常乱来，佩特拉和法兰黛莉卡也经常叫他休息，但这次的事件并不适用于这个注意。

实际上，操纵“言灵加护”的奥托，在这种情况下非常可靠。

「用虫子和鸟进行侦察和谍报吗？虽然这个加护能想到很多坏事……但相应的，背负的辛苦也会变多吧」

「哎呀，完全正确。毕竟帽子哥哥看上去就很辛苦呢」

「我活了这么久，也没听说过什么“言灵加护”。这么有用处的加护却完全不为人所知，也就是说，被授予这个加护的加护者没有一个活得很长吧」

梅莉嘻嘻笑着，佩特拉也对罗姆爷黑暗的推测表示赞同。

事实上，佩特拉在帝国也目击过奥托因为过度使用加护而流鼻血的场景。虽然那也是战时的必要情况，但“言灵加护”的滥用对身体有害。

「虽然昴他们的事情也是，但奥托哥哥特别为加菲尔的事情钻牛角尖……他好像非常有干劲，想着绝对要为他做点什么」

「如果加菲尔哥醒着的话，他大概会因为奥托哥被他拜托了什么却没做到而消沉吧。毕竟他们俩很像」

「佩特拉酱模仿得真像，吓了我一跳」

先不管惊讶的爱蜜莉娅和梅莉的反应，因为这种理由而乱来的奥托和加菲尔很容易想象。持续昏睡状态的加菲尔现在在治疗院，为了让他醒来后不会责备自己，需要多加注意。而另一边的奥托——

「如果和他在一起的芙露芙能好好安抚奥托哥就好了」

佩特拉这样嘟囔着，担心着不在场的奥托的身心。

不管和什么虫子或动物交涉，听取收集到的情报的都是奥托自己。

因此，奥托正独自追踪阿尔一伙——准确地说，是和他长年的搭档爱龙芙露芙，一人和一头一起行动。

『奥托吗……我担心他在关键时刻会出错，不知道能依赖他到什么程度』

「如果听到这句话，感觉能看到奥托哥至今为止最生气的表情」

实际上，这次事件中最让人害怕的就是奥托的反应。等到一切顺利解决后，佩特拉也必须做好和昴一起被他训斥的觉悟。

为此，所有人都必须平安无事地看到事态的解决。如果柯林特把拉姆带过来，借助她的『千里眼』之力，应该也能分担奥托的负担。

想到这里，佩特拉突然想起一件事。

「对了，爱蜜莉娅姐姐，我有件事想问你。」

「嗯？什么事，佩特拉？」

「爱蜜莉娅姐姐可能没有头绪，其实来到这里的途中，我和梅莉突然感到很不舒服……」

那是发生在芙兰姆通过和姐妹格拉西丝的『念话的加护』确定了座标，和罗姆爷他们汇合后，讨论接下来要去王都的时候——佩特拉突然全身起鸡皮疙瘩，一股仿佛内心被搅动的冲击袭来。

由于太过恐怖，佩特拉还以为那是『死者之书』的副作用，或是莱因哈鲁特战败，『嫉妒魔女』即将来到自己身边的前兆，但因为梅莉也感受到了同样的感觉，所以她得出的结论是两者都不是。

「但是，现在是这种状况吧？虽然小芙拉姆和罗姆爷爷他们没事，但我和梅莉，还有柯林特哥哥都有感受到。所以我想这可能和阿尔先生有关……爱蜜莉娅姐姐？」

感受到恐怖的梅莉和柯林特，两人讨论后也没得出结论的异变。

共享这可能很危险的情报，佩特拉看到爱蜜莉娅的反应后中断了。因为爱蜜莉娅睁大美丽的眼睛，明显心里有底。

「……那个非常恶心的感觉，大概是『暴食』大罪司教干的。」

『……你说「暴食」？』

「呜欸，好讨厌的感觉。」

眼下最可恨的大罪司教的存在让『昴』皱起眉头，梅莉吐出舌头。佩特拉也紧紧按住自己的胸口，倾听爱蜜莉娅接下来的话。

「我也不清楚到底发生了什么。但是，阿尔让『暴食』……让罗伊做了什么，然后我也突然感觉很不舒服，就在头晕目眩的时候……」

「阿尔先生和『暴食』两个人就逃走了」

「嗯，是的」

爱蜜莉娅无力地点头，肩膀也垂了下来。

听到爱蜜莉娅的回答，佩特拉瞥了一眼罗姆爷，菲鲁特阵营的贤者老人一边用大手摸着自己的头一边说：

「佩特拉和梅莉她们在说的时候，我还以为是不得要领的话，但既然连爱蜜莉娅都这样了，而且还是和『暴食』有关，那可就不是什么好预感了」

「共通点是……大家都是爱蜜莉娅姐姐的同伴？」

「要是牙哥哥醒着，帽子哥哥在这里老老实实等着，昴哥哥没被抓住的话，事情就简单了」

『包括现在轴的我在内，时机不好的三笨蛋……』

虽然佩特拉猜到了和阿尔有关，但没想到会和『暴食』扯上关系，对于身份不明的攻击的不安材料，严重程度是天差地别——稍微有点后悔把丝碧卡留在帝国了。

虽说丝碧卡也经历了一番波折，但她也是『暴食』大罪司教之一——

「不行不行，这种想法。又不是老爷。」

能做到什么，做不到什么，派得上用场，派不上用场。

要是开始用这种观点来判断人的价值，就会一口气变成罗兹瓦尔。洞察力可以尽量磨练，但要是开始渴求人性的话就要小心了。

「关于那个『暴食』的所作所为，除了留意之外也没别的办法了。然后，根据你们那边的内政官所说，他们的目的地是……」

「——卡拉拉基的莫格雷德大喷口。」

罗姆爷试图将偏离结论的话题拉回正轨，爱蜜莉娅接过他的话。

那是阿尔一伙的最终目的地，而得知这个情报的经过是——

「被他们带走的菲鲁特留下的，然后由你们的亲人传达的，是吗？老朽虽然对菲鲁特百分之百信任，但你们呢？」

「奥托吗？别说百分，是百万信任。」

「爱蜜莉娅姐姐，刚刚说的不是数字，而是百分率。不过，很帅气。」

爱蜜莉娅的回答没有被百分率的概念所束缚，但还是好好地回答了罗姆爷的问题，佩特拉对此感到骄傲和欣慰。

『……不只是可爱，还变得超强了呢，爱蜜莉娅碳』

『昴』用看着耀眼之物的眼神注视着爱蜜莉娅。

『昴』在『圣域』的问题解决到一半时就被拉了上来，没能好好地感受到爱蜜莉娅的强大是如何培养出来的，对此他感到很着急。

好想告诉她——现在的爱蜜莉娅，是和昴一起同甘共苦才变强的。

「不对，因为有碧翠丝在所以是三人四脚……如果这个道理说得通的话，那我也想加入，而且如果不把格菲也加进来的话，她会闹别扭的。梅莉酱觉得呢？」

「突然在说什么啊？突然说出像昴哥哥一样的话，好可怕」

『确实像是我会说的话，但梅莉的理解度也太高了吧？』

带着些许感慨，『昴』对佩特拉和梅莉的对话露出苦笑。

不管怎么说，罗姆爷似乎也接受了爱蜜莉娅的回答，于是阿尔他们最终目的地是莫格雷德大喷口的事情也分享给了大家。

说实话，虽然不知道那个地方有什么——

「只要知道地点的话，借助柯林特先生的力量应该就能抢先到达了」

「——是的。罗姆爷爷，加斯顿加斯顿加斯顿他们呢？」

「除了重伤者以外，其他人应该都按照指示进入附近的城镇了。联络员格拉西丝也在这里。那个叫柯林特的小子的力量，还是不要多用为好，对吧？」

罗姆爷耸了耸宽阔的肩膀，对没有详细说明的柯林特的权能表示理解。

通过佩特拉提出的“代价”，柯林特的“压缩”权能的使用限制被解除了，但根据移动的次数和人数，还是有可能无法支付。首先以最少的人数做好准备，等到看清情况后再投入最大人数。

而这些准备，也多亏了奥托的乱来才得以看到光明。

接下来，只要在到达最终目的地之前，阿尔他们打算以什么样的布阵进行，情报越多越好。

然后——

「——为此的手段，已经在我们手中了。好机会」

听到期待已久的声音，佩特拉她们一齐转过身去。集众人的视线于一身，行了一礼的正是刚刚提到的柯林特。

面对这仿佛在等待时机的绝妙时机，爱蜜莉娅「柯林特先生！」地叫了一声，表情一下子明朗起来。

「谢谢你把佩特拉她们送过来。多亏了你，我们才能像这样见面」

「无需道谢。回到米卢拉是我自己的判断，能回应你们的期待是佩特拉激励的结果。比起这个，我为回来晚了而道歉。陈谢」

「虽然我觉得也不算晚，但发生了什么吗？柯林特哥哥」

佩特拉歪着头，看着缓缓摇头道歉的柯林特。

确实，考虑到『压缩』的超规格性能，柯林特在王侯馆的汇合感觉花了点时间。但是，去迎接对方的时候应该也有必要说明情况，佩特拉不觉得需要为此道歉。

这是能干的人才会有的完美主义的表现吗？佩特拉这么想着，看向柯林特，而柯林特开口道「不。否定」

「关于迟到的理由，比起用语言说明，直接让你们感受一下才是最快，最能帮助你们理解的方法。感受一下。」

『直接』

「感受一下？」

作为迟到的解释，这番话的措辞很不自然，『昴』和佩特拉都歪着头。

爱蜜莉娅和梅莉也抱有同样的疑问，某种意义上，处于最客观位置的罗姆爷双手抱胸，一副兴致盎然地观望事态发展的样子。

就这样，在众人的观望中，柯林特退到房间入口的旁边。

「哈。让你们久等了。」

威风凛凛，大摇大摆地走进房间的，是那副旁若无人的举止也十分合适的桃发女仆——大家都知道的，我们的拉姆。

和柯林特同行汇合的她，穿着久违的女仆装，同样身为女仆的佩特拉也感慨颇深地觉得很久没看到她穿制服了。

但是——

「拉姆，你来了……」

迎接身穿女仆装的拉姆，爱蜜莉娅笑着想要跑过去，但话说到一半就停住了。她停下脚步，本想握住拉姆的手，却放在了自己的额头上。

「呃」

爱蜜莉娅发出困惑的声音。

面对这突然的状况，佩特拉本应担心她的身体状况，但却做不到。因为佩特拉和梅莉也和爱蜜莉娅一样，被一种无法理解的感觉折磨着。

「这个，是——」

看到拉姆的瞬间，涌上心头的无法理解的，无法用语言表达的巨大动摇。

这种难以言喻的神秘感觉，佩特拉觉得和刚才话题中提到的『暴食』带来的恶心感很接近。但是，那时的恶心感中能感受到强烈的恶意，而此时的感觉却感受不到。

这不是那种感觉，而是另一种，更强更强的引力——看到身穿女仆装的拉姆，强烈地被某种东西吸引的感觉。

而那个引力的答案，从拉姆的身后立刻出现了。

那是——

「——很抱歉，汇合晚了，爱蜜莉娅大人」

这样说着，站在拉姆旁边的是，和她一样身穿女仆装，以流畅的动作行屈膝礼的蓝发女仆。

当然，那是她认识的人。但是，在佩特拉所知的范围内，她应该没有穿着那件女仆装，也没有能做出完美礼仪的状态——不对，也不是那样。

再一次，再一次，再一次，重新认识。

不对，没错，不对。她没有女仆的知识和礼仪，这根本是天大的误会。因为在这个世界，她比任何人都还要早，给还是村姑的佩特拉，给菜月・昴带来女仆的正确印象。

佩特拉・雷蒂借由引力想起这件事。

被锁链敲击的声音敲打耳膜，集周围瞠目结舌的视线于一身，她点头。

站在那里的少女，她是——

「为了那个人……为了夺回昴，雷姆愿尽棉薄之力。」

没错，罗兹瓦尔宅邸的万能女仆始祖，负责嘴上不饶人的雷姆，用浅蓝色瞳孔直视前方，手拿附带锁链的铁球，做出宣言。

3

——雷姆回到罗兹瓦尔宅邸的时候，雷姆完全没有「回到」的实感。

「雷姆，看得见吗？那就是拉姆和雷姆工作的罗兹瓦尔大人的宅邸哦。」

「我们的职场……」

从龙车车窗看出去的景色，拉姆指着阳光普照的风光明媚景色这么说，雷姆眨了眨浅蓝色的瞳孔，睫毛颤抖。

乘坐公共龙车前往工业都市科斯达鲁，然后坐上在那里准备好的接送龙车，过了一会儿——映入眼帘的却是陌生的“家”。

在佛拉基亚的帝都和卡秋娅一起居住的贝尔斯提兹的宅邸，比那还要豪华的宅邸和门扉，是只要看过一次就无法忘记的雅致建筑。

然而——

「怎么样？」

「……对不起，姐姐」

雷姆缓缓地摇了摇头，为无法回应姐姐期待的不中用而道歉。

在来到这里的路上，雷姆和因为各种目的而分开行动的昴和爱蜜莉雅他们分别，和拉姆两人一起踏上返回宅邸的归途。在这期间也看到了各种各样的东西，虽然期待着记忆受到刺激，但没有收获——就连自己重要的宅邸也不例外。

「是吗。不过也没办法。因为，拉姆和雷姆在现在的宅邸工作已经是很久以前的事了，对雷姆来说印象深刻的宅邸不是这里」

「诶！？」

「顺带一提，之前的宅邸被暴躁的奥托烧掉了，所以已经不在了。如果没烧掉的话，我倒是考虑过绕过去看看」

「奥托先生……明明看起来不像那种人」

被追加的情报搞得晕头转向，雷姆对拉姆说的奥托情报更加困惑。

身为阵营内政官的奥托，给人的印象是态度柔和的人，是昴的朋友也是不可或缺的伙伴，佩特拉和法兰黛莉卡都说他完全不睡觉。然后再加上他因为心情不好就放火烧房子的情报，让人对他的性格感到迷惘。

「那个人也是，爱蜜莉雅小姐的同伴都是那种人吗？加菲尔和罗兹瓦尔先生也是……」

「是罗兹瓦尔大人。」

「……罗兹瓦尔大人也是。」

「好孩子。不过，把那三人和罗兹瓦尔大人相提并论就是坏孩子咯，雷姆。罗兹瓦尔大人聪明又有能力，是这世界最优秀的魔法使者。相较之下那三人，三人加起来才勉强一人……不，是半人吧。」

「三人加起来半人……」

在脑中让奥托、加菲尔和昴三人坐在肩膀上，雷姆让用魔法飞起来的罗兹瓦尔坐在三人旁边。就算这样并排，雷姆也不知道他们之间有多大差距，不过拉姆说的话应该没错。

对于记忆没有恢复头绪的雷姆来说，对双胞胎姐姐拉姆的无条件信赖和思慕是毋庸置疑的真心——因为这是将过去和现在的雷姆联系起来的，确切的缘。

「……这种想法，会被普莉希拉小姐骂呢。」

胸中产生的苦涩想法，让雷姆想起如火焰般的绯色女性的眼神。

在短暂的时间内，对雷姆的思考方式和前进方式造成巨大影响的她，绝对不会认同拘泥于过去，想要依赖过去的态度。同样的，雷姆委身于名为信赖感的蜜糖，对拉姆阿谀奉承，她也不会喜欢这样的雷姆吧。

雷姆不想被普莉希拉讨厌，也不想做出丢脸的生存方式。

所以，她斥责快要变得消极的心，拍打脸颊抬起头。

「可是姐姐大人，根据刚刚的话，就算回到那栋宅邸，也没有什么恢复我记忆的线索吧？」

「呵呵，理解得很快呢。有聪明的妹妹，拉姆也很骄傲。」

「不，没有……没有到被姐姐大人那样夸奖的程度……」

「不过，雷姆以为在这里的拉姆是谁的姐姐？雷姆的姐姐拉姆，会那么粗心大意吗？」

拉姆将手放在自己胸前，用充满自信的表情如此断言。

拉姆的态度，让雷姆觉得自己的担心被她看穿而感到害羞，然后突然在意起拉姆自信的来源。

「既然不是为了回宅邸，那么……是为了人？」

拉姆对猜中的雷姆微笑，几乎同时龙车也停了下来。

久违地感受到被「防风的加护」隔绝的摇晃，雷姆吃了一惊，拉姆在她面前飒爽起身，朝她伸出手。

「来，到了，走吧。」

「——是，姐姐大人。」

握住拉姆的手，雷姆按住因些微紧张而跳动的胸口，走下龙车。

拉姆向送两人到这里的车夫搭话，雷姆则是走到龙车前方，隔着眼前的铁栅栏，将宅邸和美丽的前院纳入视野。

「这里就是……」

雷姆眯起浅蓝色的瞳孔，映在眼中的宅邸果然没有印象。

尽管如此，还是看得出建筑物、花坛、树篱和宅邸的每个角落都有确实管理，自然而然挺直背脊。

不管有没有记忆，今后雷姆若要在这间宅邸生活，立场应该会跟拉姆和法兰黛莉卡一样，成为佣人。

『不，雷姆只要每天健健康康、悠哉地活着就好。』

一瞬间，脑中的昴说出那种话的身影浮现，雷姆强行驱赶想要过度宠溺自己的幻影。

昴确实有可能会说那种话，可是现在的他没那个心情。

因为失去普莉希拉，昴的心灵受到雷姆无法比拟的创伤，为了安慰他，现在他——

「——哦？哦哦、哦哦哦、哦哦哦哦！」

突然听到的低吟声吓到雷姆，她「呀」地往后退。

仔细一看，声音来自栅栏的对面，也就是宅邸的占地内——那里有个用小手抓着栅栏，目瞪口呆的小女孩。

可爱的五官，留长的粉红色头发，看起来十一、二岁的娇小身躯穿着黑色连身裙，圆滚滚的眼睛瞪得大大的盯着雷姆。

雷姆看过那个少女——在帝国的惨状中。

「你、你是……引发『大灾』的『魔女』！」

「唉呀，琉兹大人，感谢您前来迎接。」

「大灾」的罪魁祸首浑身颤抖，指着自己。

突然与不该再会的灾厄重逢，雷姆惊愕不已，拉姆从旁探出头，向她搭话。看到拉姆自然的态度，雷姆「咦？」地转头看她，「魔女」也像被电到一样瞪向姐姐。

「拉姆！你回来啦，回来是回来了……但你也太随便了吧！」

「……拉姆要像葛菈法和法兰黛莉卡那样，抱起琉兹大人吗？」

「妾身不是那个意思！比起那个，那女孩是……」

「姐姐大人，这位是……」

企图毁灭帝国的「魔女」，名字叫斯芬克斯。

可是，拉姆却用别的名字——琉兹称呼眼前的少女。琉兹的视线再度看向自己，雷姆困惑地凝视拉姆。

看到两人的反应，拉姆轻轻把手放在雷姆肩上。

「报上名来。」

「——」

连最低限度的说明都没有，但拉姆平静的声音，却不可思议地让雷姆激动的心平静下来。混乱自然地平息，雷姆转头看向琉兹。

然后调整呼吸，直视对方的眼睛。

「——雷姆，你是琉兹小姐，对吧？」

「……是、吗？是呢，嗯，没错，我是琉兹，雷姆。」

报上名字，询问名字的雷姆，琉兹一瞬间眼神飘远，柔和地点头。

从那个反应和拉姆的态度，还有在罗兹瓦尔宅邸的腹地内，雷姆终于确信眼前的少女和帝国的「魔女」是不同人。

「就算是这样，也太像了……」

「是啊，这世界有三个和自己长得很像的人，虽然是这种俗说，但琉兹大人的状况是接近十倍，也就是说，俗气也是十倍。」

「在老人家感动的场面，你在说什么啊。」

雷姆提及外表的混淆，拉姆如此回答，琉兹斥责她。

从对话中可以知道，两人的关系相当轻松，从琉兹的态度来看，她也是和以前的雷姆关系很深的人物吧。

「对不起，可是，我什么也不记得。」

「没什么没什么，不用道歉，我是——」

「——妹妹，和拉姆有着同样的发色吧。」

「确，确实……！诶，可是姐姐大人的妹妹也就是说」

拉姆打断琉兹的话，说出冲击性的事实。被吓到的雷姆来回看着拉姆和琉兹，从发色上感受到确信的说服力。

可是，拉姆和雷姆是双胞胎，那么必然的，雷姆和琉兹的关系就是——

「我的，妹妹……？」

「别这样，拉姆！你，是那个吧！罗兹亲和阿斯亲的坏影响！」

「把那两人相提并论？就算是琉兹大人也不能原谅。」

「你有资格说吗！」

琉兹可爱的脸蛋竖起眉毛，拉姆对她吐舌头。看到拉姆的反应，雷姆终于想到刚刚是开玩笑。回想起来，到这里的路上，拉姆也经常发挥淘气的一面，让雷姆感到困扰，也得到救赎。

对因为一些小事就容易消沉的雷姆来说，拉姆充满自信和幽默的态度，简直就是阳光的温暖。

「我觉得姐姐大人很出色，包括淘气的一面。」

「从鸟文传达的内容来看，你们重逢后还没过多久，竟然这么亲近……」

「什么驯服，说得真难听。拉姆只是尽了诚意和爱而已。」

「话虽如此，你却不像平常的你，太兴奋了。拉姆，一直沉睡的妹妹醒来，能像这样一起生活，老身明白你很高兴，不过……」

「——琉兹大人少得意忘形了。」

「你的害羞攻击性太强，老身也就算了，希望你对加小子手下留情。那么……」

拉姆微微皱眉。姐姐被驳倒的稀奇光景让雷姆感到佩服，靠在铁门上的琉兹离开栅栏。

「一直隔着门说话也很奇怪。老身也想和平安回来的孙女们拥抱，分享喜悦。」

「孙女……？」

「琉兹大人使出浑身解数的笑话，笑一个吧。」

「和你的姐妹笑话没差多少，代表老身就是这么重视你们！」

琉兹大声说道，雷姆尽管困惑，嘴角还是扬起。不是因为拉姆叫她笑，而是琉兹的体贴让她自然微笑。

不过，外表比雷姆她们还年幼的琉兹把自己当成孙女，就算有体贴成分，还是让人想歪头。

「虽然碧翠丝也是这样，但小孩子是不是都有想装大人的倾向……？」

「是啊。碧翠丝大人坐在巴鲁斯腿上的时候，才是她真正的模样。」

「她那么可爱，我懂。」

丝碧卡也是，小孩子就应该像个小孩子，天真烂漫地笑着才是最棒的。碧翠丝也是，琉兹也是，如果她们不装大人，用符合年龄的方式笑的话，会有多么可爱啊。

沉浸在如此感慨中的雷姆，因为接下来发生的事，一瞬间停止了思考。

「那么，大家开门吧。」

琉兹才刚说完，宅邸的铁门就开始缓缓打开。

这件事本身没什么问题。有问题的是开门的方式。

「「————」」

门闩被卸下，门朝内侧打开——而推动门的，是听从琉兹的指示的几个人。她们的发型和装饰品各不相同，但所有人都和琉兹有着相同的容貌。

也就是说，她们都是和『魔女』斯芬克斯有着相同容貌的少女——

「——！！」

这已经超出雷姆的容许范围，她高声尖叫。

4

「我还以为您在尖叫什么呢，原来是因为这个啊。第一次看到琉兹大人和姐妹们碧姬大人她们，会吃惊也是理所当然的」

「你能这么说，我稍微有点被拯救了……」

金发女仆表示理解，雷姆则以羞愧的心情低下了头。

在门前和琉兹打招呼，然后是之后的惊愕事件——和琉兹有着相同容貌的十名以上的少女登场，雷姆慌慌张张的样子让她感到羞耻。

「姐姐明明告诉过我，和琉兹大人有着相同容貌的人有三人的十倍，我还以为是开玩笑……」

「拉姆那种说法，雷姆会这么想也是没办法的吧。不觉得是开玩笑的人才叫盲目，我觉得这样才对」

「虽然您说得轻描淡写，但琉兹大人您也该反省一下自己吧？如果以您那可爱的外表，以无法忽视的频率引发问题的话，我差不多也该出手了」

「你、你这话好吓人……」

被女仆静静地瞪着，琉兹缩起身子反省。看到她这个样子，雷姆也终于放松了嘴唇，挺直了蜷缩的背。

没想到在进入宅邸前会那样手忙脚乱，不过像这样被带进屋内，就不能一直畏畏缩缩了。

话说回来——

「因为我的吵闹，给大家添麻烦了。呃……」

「——我是希尔菲・艾尔玛特。以前是柯尼亚斯，不过离婚了。这次在各位不在的期间，负责管理宅邸。」

「宅邸。那么，希尔菲小姐也是我和姐姐的同事咯？」

雷姆向静静鞠躬行礼的女仆——希尔菲如此询问。

虽然是理所当然，不过在罗兹瓦尔宅邸工作的她们，很有可能都是雷姆认识的人。因为自己睡着的关系，想必给她们添了不少麻烦。

「不会。」不过，雷姆的担忧被希尔菲摇头否定。

「我是新人，没有和雷姆大人一起工作过。而且我不是被边境伯爵雇用，而是米洛德大人雇用的。更进一步来说……」

「更进一步？」

「我的主人只有我，而且我心中的主人只有爱蜜莉雅大人。」

被希尔菲蕴含强烈意志的眼神压倒，雷姆不禁后仰。

希尔菲对爱蜜莉娅有着非同寻常的忠诚心。这一点从她带我们参观宅邸时，玄关大厅和走廊，以及现在所在的接待室的完美维护情况中也能窥见一二。

这正是她把爱蜜莉娅奉为主人，发自内心地为她服务的工作态度。

「希尔菲小姐和爱蜜莉娅小姐认识很久了吗？」

「不，我们相遇才几个月。而且，直接在一起的时间非常短。」

「尽管如此，你还是这么为她着想？」

「一个人在自己心中所占的比重，比起一起度过的时间长短，不是更取决于那个人为自己做了什么吗？」

「这……」听到这出乎意料的回答，雷姆惊讶地低下了头。

这时，雷姆的脑海中闪过丝碧卡和卡秋娅等重要之人的身影。

但是，雷姆和她们一起度过的时间，即使加上没有记忆的雷姆从零开始积累的关系，也绝对算不上长。

尽管如此，雷姆还是强烈地认为她们是无可替代的存在。

希尔菲说得没错。——虽然认同，但昴的脸却清晰地浮现在脑海里，雷姆抿紧嘴唇。

「雷姆大人？」

「她很困惑吧。希尔菲，雷姆的情况应该跟你说过了。」

「是呢，非常抱歉，是我思虑不周。」

「不，这不需要道歉——只是，这是我的情况。」

听到雷姆的回答，琉兹和希尔菲面面相觑。虽然对替自己着想的两人感到过意不去，但雷姆并不打算说出现在的纠葛。

正如她所说的，这终究是雷姆自己的烦恼，是她的问题。

「——忧愁的脸蛋呢，雷姆，是被希尔菲欺负了吗？」

「——」

突然有人呼唤自己，雷姆抬起头看向会客室的入口。站在那里的人，是带她们来会客室的途中，说有事暂时分开的拉姆。

晚一步会合的拉姆，她的模样让雷姆瞪大眼睛，屏息凝气——因为现身的拉姆，穿着不熟悉的女仆装站在那里。

「姐姐，那身打扮是……」

「说过好几次了吧？拉姆是宅邸的，罗兹瓦尔大人的女仆哟。」

拉姆潇洒地抚摸桃色头发，如此回答，雷姆不禁看呆了。琉兹和雷姆一样看着拉姆，「哦」地吐气。

「也好久没看到拉姆这身打扮了。」

「是呀，拉姆也穿了很长一段时间的旅行装，感觉很新鲜。」

「太新鲜了，制服穿得歪七扭八，可以帮忙调整吗？」

「是吗？那就拜托了。」

琉兹不理会瞠目结舌的雷姆，感慨万千，希尔菲则是默默地开始帮忙拉姆整理仪容。在希尔菲的帮忙下，拉姆一边整理制服，一边对看着自己的雷姆眨了单眼。

「这就是拉姆和雷姆在宅邸工作时的女仆装。」

「……我觉得很棒，可是。」

「可是？」

「跟希尔菲小姐的制服相比，肌肤的裸露度是不是有点高？到底有什么差别……该不会跟那个人有关吧？」

比较拉姆和希尔菲的女仆装，雷姆抱着自己的肩膀抱持怀疑。

确实是很可爱的服装，但不明白这么明显的差异是基于什么意图。回想起来，昴在帝国也经常提及雷姆的服装，说这样穿会更可爱，那样穿会更有魅力，说来说去都让雷姆心情复杂。

「拉姆大人，您似乎对别人的服装格外拘泥，连在这里也……？」

「……总觉得，好像产生了什么误会，拉姆大人？」

「是啊，拉姆是觉得昴在雷姆心中的评价跌落谷底也无所谓，但功劳被抢走就不好玩了。」

「功劳？」

「嗯，这套女仆装是拉姆亲自提案改造的。全都是……因为拉姆想穿更方便行动的制服？应该是这样吧？」

「为什么突然失去自信了？」

「无法理解。」对于话题最后的部分，拉姆一反常态地失去自信，琉兹歪头不解。听到琉兹的指摘，拉姆喃喃地说：

「无法接受自己的意见，真不愉快。拉姆提案改造制服的理由，应该不是像刚刚那样随口胡诌的。」

「明、明明是自己的意见却这么说！？」

「感觉是被强迫穿上的……虽然跟巴鲁斯有同样的想法很不爽，不过想让雷姆穿可爱制服，这样比较能接受。」

「原来如此，确实，可以接受。」

拉姆对自己的想法如此推理，不知为何希尔菲也赞同。从对话的走向来看，希尔菲也有想让特定的人穿可爱衣服的欲求吧。

实际上，在与雷姆有关的记忆从许多人身上消失的世界里，拉姆感受到的异样感，其真面目和答案大概永远都不会被知晓。

「既然如此，拉姆就相信自己想相信的事物，不用顾虑任何人。」

「……姐姐大人，你一定跟普莉希拉小姐很谈得来。」

雷姆的交友关系狭隘，不过就高傲坚强的女性这点来说，普莉希拉和拉姆都有令人憧憬的共通点。普莉希拉若健在，两人一定可以透过雷姆成为好朋友，又或者像天敌一样互相冲突。

不管怎样，因为女仆装而怀疑昴似乎是搞错了。

「不过，全都是那个人平常就做些混淆视听的事害的。」

「如果是阿昴的话，被骂得这么惨还真可怜。」

「琉兹女士，你没有看到他说着莫名其妙的话然后穿女装的样子，所以才会说出这种话。」

「什么！阿斯小弟在帝国也穿女装吗！真是学不乖的孩子。」

「女装？明明都有爱蜜莉雅大人了？他到底在想什么。根据他的回答……」

从琉兹的反应来看，可以确定昴真的是女装的惯犯。雷姆决定要和对这件事感到不快的希尔菲合作，再次逼问他。

在她们交谈的旁边，希尔菲帮拉姆整理好仪容。拉姆当场转了一圈，裙摆飘扬，头发飒爽地往上拨。

「辛苦了。你做得很好，希尔菲。」

「……承蒙您的夸奖，我感到很光荣。」

「这是拉姆的称赞，你就坦率接受吧。不只如此，拉姆稍微巡视了一下，宅邸的管理也很周到。」

「因为我在无可救药的老爷底下，过着屈从的日子。要是地板上掉了一粒灰尘，我们这些妻子就会被狠狠教训。光是回想起来就火大，不过最近他得到报应了。」

希尔菲将拉姆的制服整理得整整齐齐，不过从她的言行举止中，可以感受到以前的职场——不，是环境非常糟糕，雷姆也感到非常同情。

这时，变成完美女仆的拉姆，将茶杯轻轻放在雷姆面前。

「来，被琉兹大人和希尔菲逼问，喉咙很渴吧。」

「只是端一杯茶出来，就把我们说得像坏人一样。」

「哈！」

拉姆对嘟起嘴的琉兹嗤之以鼻，也为她和希尔菲准备茶水。

拉姆似乎将配膳台搬到走廊，她俐落地泡好两人的茶，同时以视线催促雷姆先喝。雷姆遵照指示，享受茶香后将茶杯凑到嘴边——然后忍不住睁大眼睛。

「好喝……」

「对吧。泡茶是拉姆身为女仆唯一的特技。」

「干脆豁出去的坦荡态度，真是令人着迷……实际上，没有机会喝到这么好喝的茶，所以也没什么好挑剔的。」

「法兰黛莉卡也常说，只有泡茶是她赢不了拉姆，总是很开心的样子。」

面对夸耀胜利的拉姆，希尔菲和琉兹也承认败北，喝起茶来。

雷姆享受着穿过鼻腔的香气和舌头上的味道，点头同意两人的话，同时注意到拉姆柔和的眼神中带着慈爱和些许期待。

「——啊。」

拉姆没有明说，不过她一定对这杯茶的味道抱有期待。

如此美味的茶，除了拉姆以外没人泡得出来，不难想象失去记忆前的雷姆也品尝过。实际上，这杯感动到连泪腺都湿润的茶，仿佛渗透到雷姆身体的每个角落。

可是，这并没有刺激雷姆的记忆，带来期望的结果。

「真的非常、非常美味，可是——」

雷姆将喝完的茶杯放在桌上，垂下眼帘含糊其辞。不过，看到雷姆的样子，拉姆微笑着说「笨蛋」。

「只是泡茶而已，可爱的雷姆没必要道歉。」

「说不定是拉姆大人的目光太锐利，才害我忍不住道歉。我以前的老爷是个喜怒无常的人，不过只要先道歉，他就会心情大好。」

「……可以帮拉姆和希尔菲再泡一杯茶吗？老朽觉得这女孩可怜得不得了。」

「为什么您会这么想？别说可怜了，我可是享受着前所未有的自由呢。」

希尔菲微微皱眉，对琉兹悲伤的眼神表示意外。而拉姆则回应琉兹的要求，开始为希尔菲准备第二杯茶。

雷姆望着拉姆的背影，再次下定了决心。

「……我想回应那些对我好的人」。

5

离开接待室后，雷姆随心所欲地在宅邸里四处走动。

每当停下脚步，跟在后面的拉姆就会说「那里是巴鲁斯的头被肥料浇到的花坛哦」、「这根柱子有加夫咬过的痕迹呢。之后要骂它了」、「哎呀，爱蜜莉娅大人和碧翠丝大人画在地上的大精灵大人的肖像画，原来还留着呢」，讲述着那里的回忆，让雷姆没有时间感到不安。

只是，与拉姆的陪伴和体贴相反，雷姆一直没能遇到能推自己一把的感觉。

「啊，又看到和琉兹大人很像的孩子们……」

「是皮可它们呢。它们被赶出『圣域』，正在从头学习各种事情哦。」

「……我和那些孩子，还有希尔菲小姐她们的境遇很相似呢」

和格外老成的琉兹不同，少女们看起来天真无邪，与外表相符——以被称为皮可的孩子为首，她们在广阔的罗兹瓦尔宅邸各处都能看到，她们穿着和希尔菲同样的制服，到处奔走帮忙女仆们。

那副样子看起来非常坚强的少女们，似乎与生俱来就背负着与人类不同的宿命，现在从那里解放出来，正在以不同的方式生活。

另一方面，虽然有很多女仆的女性们美丽和气质引人注目，但根据听到的话，她们和希尔菲一样，都是身处恶劣环境的女性，似乎都是多亏了爱蜜莉雅才能脱离那里。

琉兹的姐妹们，还有女仆的女性们，她们的生活方式被命运玩弄，被命运摆布，就这点来说和雷姆的立场相同，她是这么想的。

可是，对于雷姆的想法，拉姆说了句「是呢」后继续说道：

「不管有没有记忆，如果决定要开始走上新的道路，大部分的情况都只能从头开始重新积累。雷姆并没有什么特别的。」

「姐姐大人……」

「不对，说错了。雷姆很特别哦。对拉姆来说，是过于可爱的存在。」

被这么重新说了一次，雷姆因为感受到的爱意太大而害羞地转过头。

当然，雷姆对拉姆也有强烈的亲近感，以及从内心满溢而出的爱意，但雷姆的爱意是一，拉姆给予的却是十或百，所以无法平静。

抱着这种焦躁感，雷姆和拉姆继续在罗兹瓦尔宅邸里绕。

然后终于——

「——这里就是雷姆的房间。」

拉姆的手打开门，她用手指示的房间，雷姆踏入其中。

在绕过的宅邸中，与会客室、餐厅、大澡堂、秘密特训场、谈话室、庭园和露台等地方相比，跟客房没什么两样的这里没什么特别之处。

因为宅邸很大，所以给予一介佣人的雷姆的房间也相当气派，但特别之处就只有这点。

「——」

大床铺、收纳诗集和图画故事书的书架，书桌整理得很干净，上头摆着插有鲜花的花瓶。

「有一次，没注意到这点而整理了私人物品，结果巴鲁斯把东西全都拿出来，说雷姆是这样整理的，全都放回去了。」

「那个人……」

站在书架前的雷姆，听到拉姆传达昴的努力。

基本上，拉姆对昴的辛辣发言很显眼，雷姆也点头同意很多地方，不过刚刚补充的话只有真挚，雷姆的内心也沉稳下来。

抽出诗集，翻阅页面。写在上面的诗篇都是没看过的，不过以前的雷姆喜欢、喜欢过的诗文应该都写在上面吧。总觉得有很多歌咏爱和恋的诗，以前自己的兴趣让她感到滑稽和羞耻。

「我睡了一年以上呢。」

把诗集放回书架后，雷姆轻轻抚摸床铺，眯起眼睛。

代替陷入沉眠无法醒来的雷姆，拉姆、法兰黛莉卡和佩特拉她们应该有整理宅邸，每天照顾躺在床上的雷姆。现在床铺的枕头和床单都保持清洁，可以窥见她们细心的工作态度。

床铺旁边，地板有微微日晒的痕迹，那是长时间放椅子的证据。造访沉眠雷姆的人，在这里跟她说话的光景浮现在脑海。

那一定是拉姆、爱蜜莉雅她们，还有——

「——」

拉姆也默默坐在坐在床边的雷姆身旁。面对拉姆浅红色的温柔眼神，雷姆闭上眼睛，摇了摇头。

没有被问到，可是，拉姆应该很想问。

这间宅邸的一切、这个房间的一切，都没有刺激雷姆记忆的东西。

这里有的是许多的亲爱，能够感受到亲爱的事物，全都是让什么都不记得的雷姆，知道自己曾经很幸福的东西。

强烈地、强烈地，让人眼眶泛泪地深深感受到。

正因为如此——

「……姐姐，我很在意那个，那是什么？」

阳光从树叶间洒落，温柔的空气和体贴蔓延的房间角落，放在那里的神秘物体——附有锁链的带刺铁球的异样感引人注目。

听到雷姆的疑问，拉姆「啊啊」一声，像是察觉到什么似地吐气。

「那是晨星槌。」

「……晨星、槌？」

「对，巴鲁斯开始那样叫，不知不觉间就固定下来了……那也是雷姆很珍惜的东西哦。」

「那个我吗！？」

听到和至今为止的回忆天差地远的发言，雷姆的视线在拉姆和带刺铁球——晨星锤之间来回移动。

移动之后，雷姆差点就接受这是拉姆的玩笑话。

「拉姆也明白你怀疑的心情。不过，看到巴鲁斯准备专用的布和油，每天都在擦拭那个，拉姆觉得以无聊的玩笑话来说，准备得也太久了。」

「可、可是，那个人的话，感觉会做这种无聊的事吧？」

「是啊，拉姆不否定。」

似乎是已经讨论过很多次，拉姆对雷姆的反驳回答得很无奈。看到拉姆的样子，雷姆从床上起身，走向晨星锤。

「不懂意义何在……」

靠近一看，为了避免铁球的刺伤到地板，还准备了手工制的铁球放置处，可以感受到细心的考量。放在相同位置的布和油的容器，也证实了昴每天擦拭的发言。

不过，就算这样，还是不知道这代表什么。

「反正这也是那个人的恶作剧——」

和女装的时候一样，只是昴的恶作剧，只是在反映昴的喜好，只是某种恶劣的玩笑。

雷姆这么想着，弯下腰，用手指触碰铁球——就在这个瞬间。

「——咦？」

突然，雷姆的视野扭曲，不由得一屁股坐在地上。虽然姿势很不雅观，但雷姆没有余裕去在意这种事。

「唔……」

即使坐在地上，晕眩也没有结束，视野天旋地转。

明明自己就在这里，却分不清地板和天花板，世界的黑白反转，眼睛看到的、耳朵听到的、鼻子闻到的、空气的味道、肌肤的触感，五感全都混在一起，空气看得见、声音有香味、气味可以触摸、颜色有味道、可以听见。

「——啊、呜。」

可以感觉到的一切全都混合在一起，搅拌，雷姆的过去、现在和未来全都混在一起。

山间的村落、被剑贯穿的狼旗、嘎吱作响的轮椅车轮声、覆盖天空的飞龙群、在夜空飞行的可怕白鲸、在火焰照耀下飞舞的断角，还有拼命诉说的少年、愤怒的少年、流泪的少年、微笑的少年——

「————」

不久，仿佛要重塑整个世界的冲击，像泡沫破裂一样突然炸开。

「————」

视觉、听觉、嗅觉、味觉、触觉，每一种感官都看得见听得见闻得到尝得到摸得到，以正确的形式告诉自己生命的所在。

雷姆感受着那烙印般的强烈刺激，以及接受刺激后，血液在自己身体的每个角落循环的脉动，眨了一次、两次、三次眼睛。

她不知道到底发生了什么事。

只是——

「我……雷姆，我……」

她坐在地上，用颤抖的手摸着自己的脸颊，确认自己的存在。

指尖触碰到的触感没有消失。她害怕那虚幻、不可靠、像沙子做的城堡一样崩塌的感觉，不敢再往指尖施力。

如果再贪心一点，感觉一切都会消失——

「————」

雷姆被无法抗拒的不安与恐惧所笼罩，从背后传来温暖的触感。

她倒抽一口气，僵硬得无法回头。被从背后伸过来的手臂抱住，雷姆原本只顾着自己的脑袋和心灵，得到了转向其他事物的契机。

然后最先面对的，就是从身后抱住自己的存在——

「姐——」

「——等等。」

「————」

「还不要转过来。现在，拉姆是人生第一次，对自己感到失望。」

正要出声、正要转头，这些全都被对方制止，雷姆全身僵硬。

拉姆不让她看到脸，抱住她的手和发出的声音都在颤抖。那实在与雷姆所知的拉姆形象相差甚远。

不管何时，拉姆都凛然勇壮、堂堂正正，只让雷姆看到那样的身影。

在帝国重逢的时候是这样，回到罗兹瓦尔宅邸前的两人之旅也是，一开始在宅邸工作，角刚折断负担很重的时候也是，为了保护愚蠢的雷姆，在被烧毁的村庄里与魔女教徒大打出手的时候也是。

映在雷姆眼中的拉姆，总是很帅气——

「对不起，雷姆，拉姆觉得自己很没用。」

「姐姐……你在说什么……」

「竟然……」

「————」

「竟然忘了这么惹人怜爱、这么重要的雷姆，活到今天，拉姆是多无情的姐姐啊。」

因为拥有过于庞大的爱情，拉姆的声音充满懊悔，雷姆听了瞪大双眼。然后，雷姆甩开所有制止，转身面向抱住自己的拉姆。

「——」

湿润的淡红色瞳孔微微睁大，拉姆惊讶地看着自己——雷姆人生中最常、最长注视的脸庞，令她胸口发热。

她可以确信，自己是多么幸福的人，被多么惹人怜爱的人围绕。

「姐姐大人，你才不是无情的人。雷姆才要说对不起，一直、一直让姐姐大人担心，是不孝的妹妹。」

「雷姆。」

「全部，雷姆都知道。姐姐大人为了我多么费心，牺牲了多少事物，直到今天都陪伴着我。还有……」

「雷姆……」

「只知道接受，软弱又没用的雷姆，今后必须做的事。」

「——」

雷姆从正面凝视拉姆的脸，用手指拭去滑过脸颊的泪水，朝她微笑。然后伸出的手将姐姐的头拉近，抱在胸前。

姐妹俩坐在地板上，轻轻靠在一起，互相怜惜——不，一直都是拉姆这么做，雷姆却做不到。

「姐姐，最喜欢你了。」

嘴唇凑近抱着的耳边，雷姆将满溢而出的情感传达给拉姆。感受着温热的泪水濡湿胸口，雷姆继续抱着无声流泪的拉姆。

终于，打从心底接受真正意义上的重逢，雷姆将过去和现在的自己，以及所有的一切都传达给拉姆。

直到心满意足，直到尽情享受，现在只想和拉姆一起度过。

就这样，确实取回姐妹之间没有填补的时间，雷姆有非做不可的事——必须传达感谢和爱的对象太多了。

特别是，最先浮现在脑海的，是眼神凶恶的黑发少年——

「——昴。」

为了传达爱，必须站起来。

自己是被多么幸福的理由所救——雷姆这么想。

6

「——」

凛然又壮丽，挺直背脊站着的女仆装少女，让佩特拉倒抽一口气。

佩特拉睁大眼睛，僵硬的身体无法动弹。不只是佩特拉，梅莉和爱蜜莉娅也一样，看到出现的她后，都失去了言语。

在这样的强制沉默中，最先开口的是——

『——雷姆。』

没有实体的想象昴，和佩特拉看着同样的对象，呆呆地站着。

他茫然的声音除了佩特拉以外没人听到，很悲哀的是，被视线集中注视的少女，也没有和半透明的他视线相交。佩特拉没有余裕去帮助谁都没注意到的“昴”。

不过，可以保证“昴”的呼唤是正确的——站在那里的是，毫无疑问是可爱的少女雷姆。

「——啊。」

瞬间，佩特拉的脑海中闪过一道电光，蒙上一层雾的意识野逐渐清晰。

吸引她的引力，其原因就在眼前，被无意识地推到脑海角落，盖上忘却的布幔，名为回忆的画作再次在意识的回廊展示。

就这样展示出来的所有色彩鲜艳的画，都让她受到火花四散的冲击。

——佩特拉以佩特拉的身份，和她接触的时间并不多。

少女是罗兹瓦尔宅邸的女仆，偶尔会来村子买东西。几乎没有交集，也没说过话，但自从昴在村子露脸后，她的表情就变得丰富，而且她是佩特拉她们的救命恩人——让她们生命陷入危机的，是操纵魔兽的梅莉，这也算是因果报应。话说回来，梅莉和她的姐姐，也太常觊觎自己人以外的性命了。

不管怎样，佩特拉和她的交集就是这么薄弱。

之后，她随着王选开始，同时成为「暴食」大罪司教的受害者，为了填补空缺而被雇用的佩特拉，以女仆的身份加入爱蜜莉雅阵营。

也就是说，没有她的悲剧，就没有现在的自己，这件事本身让佩特拉的心境变得很复杂——

「雷姆……是雷姆吗？」

翻开盖住的牌，像是要重新确认图案和写在上面的内容，佩特拉心中对她的不解逐渐被理解取代。

在她身旁，眨着眼睛的爱蜜莉雅用生硬的声音呼唤她。

爱蜜莉娅向前走了一步，像是在犹豫接下来该说什么一样，嘴唇一张一合，

「不，对不起，我说的很奇怪吧。雷姆就是雷姆，这点我之前就很清楚……但是，我想说的不是这个」

「没关系的，爱蜜莉娅大人。冷静下来，慢慢说就好。雷姆也知道这是突然发生的事」

「——嗯，谢谢。虽然有很多话想说，但是」

「但是？」

「……这身打扮，非常适合你。非常有雷姆的感觉」

爱蜜莉娅把手放在胸前，紫色的眼瞳湿润，对雷姆微笑。听到爱蜜莉娅的话，雷姆轻轻挑眉，然后点了点头。

她自豪地挺起穿着女仆装的胸膛，

「因为这是姐姐为了适合雷姆而制作的制服」

听到雷姆的回答，拉姆双手抱胸，满意地点点头。

「……这，突然之间是怎么了」

在爱蜜莉娅和雷姆的旁边，梅莉皱着眉头嘟囔。

从她的头发里探出头的小红蝎，像是担心主人的反应一样，钳子咔嚓咔嚓响，梅莉闭上一只眼，把手放在自己的额头上，

「一看到拉姆姐姐的妹妹，我就想起了那个人把乌尔加姆连同它的族群一起碾碎的事。这可不是工作失败的原因……」

「那你就该感谢雷姆。多亏雷姆让工作失败，除了巴鲁斯以外没有出现其他受害者，你才能在这里。」

「心情好复杂，很难感谢她……」

拉姆抱着自己的手肘指出问题，梅莉露出厌恶的表情吐舌头。

虽然说法不好，但拉姆指出的问题也是真理。事实上，曾经是敌人的梅莉之所以能被爱蜜莉娅阵营接受，是因为她的行为让阵营受到的损害控制在最小限度——讽刺的是，拉姆指出除了昴以外没有出现其他受害者，从「死亡回归」的观点来看也是正确的。

「正如你所感受到的，一看到雷姆，以前认识她的人就会想起她的记忆。再生。我和琉兹大人都无法抑制动摇。结果，导致我们晚一步会合。告白。」

「克林德的反应很贫乏，一点都不有趣，不过琉兹大人慌乱的样子很夸张，真是大饱眼福。这是在场者的特权。」

「原来如此，值得一看吗。确实，看到了罕见的东西呢。我懂了」

「——哈」

围绕在雷姆身边的人们，她们的『记忆』复活了。——不，从至今为止的『暴食』的权能的条件来看，应该说是『名字』复活了。

面对触及这个事实的柯林特意味深长的眼神，拉姆明显不满地哼了一声。这份不满，或许和拉姆微微泛红的眼角有什么关系。

但是，佩特拉没有提及这件事——不是出于武士的同情，而是无法提及。

「——佩特拉小姐？」

突然，沐浴在大家目光中的雷姆，看着沉默的佩特拉，瞪大了眼睛。她的反应让爱蜜莉娅她们也转过头来，被佩特拉的样子吓了一跳。

她们的反应也是理所当然的。因为至今为止一言不发的佩特拉，那圆圆的眼睛里正滂沱地流着泪水，拼命地按住快要抽泣的喉咙。

「佩特拉酱！？不好，哭得那么厉害——」

「——」

在哭脸被发现的瞬间，佩特拉的脚蹬了一下地板。

佩特拉躲开被她的眼泪吓到，想要抱过来的爱蜜莉娅的手，躲开想要碰她袖子的梅莉，穿过被状况吓到的罗姆爷的胯下，以敏捷的动作，从正面——扑进了瞪大眼睛的雷姆的怀里。

「雷姆——！」

「呀！」

被没有躲开的雷姆抱在怀里，佩特拉紧紧地抱住她纤细的身体。雷姆一边回抱着紧紧抱着自己，难以分开的佩特拉，一边眨巴着眼睛。

「雷姆……雷姆，雷姆……」

在雷姆的怀里，佩特拉一边流着泪，一边做出绝对不能在人前做的行为，吸着鼻子，仍然没有分开。

就这样，雷姆一边支撑着大哭的佩特拉，一边求助般地看向周围，

「那个，雷姆和佩特拉小姐，只是我想不起来，其实关系好到会为我哭成这样吗……？」

她掩饰不住困惑的神色，继续温柔地抚摸着佩特拉的头。

7

「对不起，给你添了很大的麻烦……」

「没有，雷姆才是，你为我哭成那样，我真的很开心，就像姐姐为我哭那样……啊」

佩特拉一次又一次地低头道歉，为自己的丑态谢罪。雷姆想要安慰佩特拉，却说出了不妙的话，她僵着脸看向拉姆。

拉姆用温柔的微笑回应雷姆的眼神，说道：「没关系」

「拉姆终究是个在感动的再会场面中无法保持平静的没用姐姐，被雷姆说成是爱哭鬼也没办法」

「我，我没有那个意思！姐姐是爱哭鬼是误解！而且，姐姐为我哭我很开心！」

「是啊，拉姆。因为，你终于想起了雷姆。就算因此哭出来，也没有人会认为拉姆是爱哭鬼。打起精神来！」

「雷姆，爱蜜莉娅大人……呜呜呜」

爱蜜莉娅也跟着雷姆一起安慰拉姆，拉姆用手遮住眼睛背过脸。两人看到她的样子更加担心，但佩特拉觉得这出闹剧有点过头了。

当然，这是让拉姆高兴到感动落泪的事态。

「……拉姆姐姐，我知道你很开心，但不能太捉弄她们两个」

「诶！？」

「捉弄……？」

佩特拉努力让自己的声音平静下来，提醒拉姆。爱蜜莉娅和雷姆听到后瞪大了眼睛。骗了她们两个的坏拉姆停止假哭，耸了耸肩。

「是啊。因为记忆顺利恢复了，所以忍不住想看看雷姆的各种表情，就捉弄了她。能原谅坏姐姐吗？」

「姐姐……真是的，真拿你没办法。只有这次哦？」

「嗯，谢谢。爱蜜莉娅大人也同意吗？」

「真是的，雷姆都原谅你了，我怎么能一直生气呢。真是的」

「好厉害。完全没有谦让，只是撒个娇就过去了」

尽管拉姆的态度完全没有反省的意思，但雷姆和爱蜜莉娅还是轻易原谅了拉姆的蛮横。看到这一幕的梅莉呆呆地嘟囔着。佩特拉也对梅莉的反应深有同感。虽然很像拉姆的态度，但有点太得意忘形了。

「我也想为雷姆……为雷姆姐姐大人开个庆功宴，但现在是非常时期，拉姆姐姐也请自重」

「自重，是吗。虽然乍一看是个很正经的意见，但佩特拉你又如何呢？」

「——？什么意思？如果是说刚才的事，我也反省过了」

「我并不是在责备你慌乱的行为。我在意的是别的事——从刚才开始，你就在雷姆和爱蜜莉娅大人之间很自然地待着」

「诶？」听到拉姆闭上一只眼睛指出的问题，佩特拉瞪大了眼睛。然后她看了看自己的左右，分别看了看爱蜜莉娅和雷姆的侧脸。

三人现在以佩特拉为中心，横着坐在沙发上。佩特拉分别抱着两人的手臂，紧紧地抱着不放。

「咦？」

「咦什么咦啊。你抱住雷姆姐姐大人之后，就非常自然地把她们拉到你身边了。连爱蜜莉娅姐姐大人也一起」

「对，对不起。我对她们两人的爱好像溢出来了……」

「唉」梅莉继续无奈地说道，佩特拉听了之后反省了自己。但是，她的借口和拉姆刚才撒娇时的借口完全一样，所以拉姆对她笑了。

「没关系的，佩特拉小姐。雷姆也想把之前空白的部分一个一个地好好填上」

「雷姆姐姐大人……」

「而且，雷姆一直觉得和在村子里生活的佩特拉小姐她们关系不太好，所以能被这么重视，我很开心」

被佩特拉抱着胳膊，雷姆的脸颊微微泛红，害羞地说道。

在雷姆的自我意识中，和佩特拉她们的交往是在王选开始之前——昴被带到宅邸的一个月是高峰，以前只是擦肩而过的交情。

所以，害羞的雷姆的认知并没有错。佩特拉对雷姆抱有如此巨大的感情，与其说是佩特拉自己的感情，不如说是受到了『昴』的影响。

但是，即便如此，佩特拉还是这么想。

「微笑着害羞的雷姆姐姐大人，好尊贵……」

「佩特拉酱，你的耳朵好红。没事吧？」

「啊，不是的。我不是出轨……爱蜜莉娅姐姐大人是第一位」

「诶？啊，是啊。我是阵营里最伟大的人，要好好相处才行」

佩特拉夹在焦急和幸福之间，说出了多余的话，但爱蜜莉娅却像天使或者女神，又或者说是像误会系主人公一样，无视了佩特拉的话。

对此，佩特拉隔着胸口抑制住自己心脏的跳动，一边说着「我最喜欢的是昴吧……」一边站了起来。

如果就这样被爱蜜莉娅和雷姆夹在中间的话，感觉自己的心会变得四分五裂。

『佩特拉，你真了不起！能忍住真是太好了！』

「昴，你给我做好之后被我挖苦的觉悟。你这个花心大萝卜」

『对于不能触碰爱蜜莉娅碳和雷姆的我来说，这太不讲理了！』

佩特拉勉强斩断了自己依依不舍的留恋，将心中的愤怒转向了想象中的昴。佩特拉看着单手拿着手帕擦拭眼泪，为了表达对恢复记忆的雷姆的感情爆发而在接待室里转圈跳舞的『昴』，叹了口气。

然后——

「我知道因为雷姆的事情而吵吵闹闹的，但希望你们能先冷静下来——我们来谈谈那个人的事情吧」

「————」

雷姆用平静的声音开口说道，房间里的气氛明显地紧张了起来。

虽然还不到放松的程度，但与紧迫的状况相反，现场气氛开始热络起来，而成为契机的雷姆本人则将之抹去。非常了不起，很了不起。

「拉姆和雷姆，从克林德先生那边听说了吗？」

「大致上，而且也看到了王都的惨状。没想到会变成这么严重……巴鲁斯搞砸了呢。」

「拉姆姐姐大人，那种说法……」

「对不起，拉姆重说一遍——拉姆我们全都搞砸了呢。」

「——」

拉姆的见解很沉重，重重地回响在全员的胸中。

方才在拉姆和雷姆会合前也确认过了，阿尔的行动造成的损害之大，让人不忍目睹。

「话虽如此，过度自责也得不到什么。事态的责任终究在引发的当事人身上，这是老朽等人的结论。」

「拉姆我们是这么想的，不过，事情没有这么单纯，不是吗？」

「……真是不能小看的女孩，刚刚的恶作剧算什么啊。」

罗姆爷这么说完后摸摸自己的秃头，对拉姆的追究露出苦涩的表情。看到两人互相理解的互动，雷姆歪着头说：

「不单纯是指责任所在吗？」

「嗯，对。详细情况罗姆爷想说，就交给他了。」

「把麻烦事丢给我……算了。那女孩说得对，先不论我们的想法，现状对我们和你们来说都不好。」

被拉姆托付说明工作的罗姆爷，用粗手指指向自己和爱蜜莉雅。凝视粗大的指尖，爱蜜莉雅眨了眨蓝紫色的瞳孔。

「我们当然不好，罗姆爷你们……菲鲁特也一样吗？」

「我们家艾莎也在塔里。在正式的国家调查团派遣过来之前，艾莎被赋予管理塔的责任，但却没能完成。莱因哈鲁特和头盔男都没能阻止『神龙』，让王都受害。」

「可是，多亏爱蜜莉雅姐姐，大石头才没有掉到街上吧？这样还要被骂吗？」

「如果把丢出去的石头打碎就能讨好大家，莱因哈鲁特就能一直重复同样的事。梅莉，这种事不能只看结果，过程也得公平评价。」

罗姆爷缓缓摇着巨大的脑袋，一脸为难，梅莉见状嘟起了嘴。

梅莉无法接受，她这种态度的背后，隐藏着对爱蜜莉娅完成的重要任务没有得到正确评价的不满。爱蜜莉娅明白这一点，所以她微笑着对梅莉说“谢谢”，然后把脸扭向一边，让嘟着嘴的少女更加生气。

「老夫先说说我们必须要做的最低限度的事情。首先，我们必须亲手阻止头盔男……阻止那个自称阿尔德巴兰的男人。不能交给其他人和王国。只有做到了这一点，才能挽回失分，然后讨论之后的事情。」

「为什么必须由我们来做？当然，我们努力是理所当然的，但如果能在阿尔做坏事之前阻止他的话……」

「你还不明白啊，爱蜜莉娅。这已经不是阿尔德巴兰一个人的问题了。他有『神龙』跟着。这是动摇王选基础的重大事件……要想颠覆它，只能由龙之巫女，由王选候选人将『神龙』拉回来。如果做不到这一点……」

「——王选本身就会变成没有发生过的事情？」

爱蜜莉娅说出决定性的可能性，罗姆爷表情严肃地点头。听到这里，佩特拉也慢了一拍才追上危机感。

说起来，露格尼卡王国决定下任国王的王选，是以与龙的盟约，以及维持盟约所必须的龙历石预言为基础。要说的话，就是仰仗「神龙」波克肯尼卡强大之力的仪式，没有「神龙」王选就无法成立。

「因此，一定要有。让迷惑『神龙』的阿尔德巴兰，不是由其他人而是由王选候选人亲手阻止的结局。」

那是让这桩大事有个了结，让王选继续进行下去的大前提。

菲鲁特阵营的智者，长年看着世界的巨人之言，具有其他人无法反驳的说服力。

必须防止世界被阿尔亲手破坏。但是，只要世界没有被破坏，之后不管发生什么事都无所谓，事情不是这样。

战斗结束后，那里——

「必须好好地，留下可以让昴回来的地方。」

「雷姆……」

听到罗姆爷的话，爱蜜莉娅凝视着喃喃自语的雷姆。雷姆的浅蓝色瞳孔里充满了使命感，回应爱蜜莉娅的视线说：「因为，就是这样吧？」

「那个人，对我就是这样。宅邸里雷姆的房间，和以前一模一样……因为昴强烈地思念着，所以雷姆才能想起忘记的事。多亏了昴每天帮我磨的晨星锤……！」

没错，雷姆拿着锁链铁球——晨星锤，用力地诉说。被锁链锵锵的勇猛声音和雷姆的气势压倒，爱蜜莉娅歪着头。

「……多亏了晨星锤？」

「是的。你可能会很惊讶，但就是碰到这个晨星锤的瞬间。之前的记忆一下子苏醒……原本以为是那个人的偏执，但那是误会……有很多事，想向他道歉。」

雷姆像在为自己感到羞耻般地垂下眼帘，开始诉说记忆复苏的经过。雷姆热烈的诉说，让爱蜜莉娅翻白眼，手忙脚乱，感到困扰。

大概，是时机的问题。——阿尔从监狱塔里带出来的『暴食』，它做了什么，恐怕和雷姆的『记忆』和『名字』的复活有关。然后，那是在雷姆在宅邸里碰到晨星锤的同时发生的。

所以雷姆，才会认为是晨星锤唤醒了自己。

「那个，雷姆，冷静下来听我说……」

「请放心，爱蜜莉娅大人。雷姆一定会用这晨星锤，成为取回昴的力量。之后，关于帝国的事和今后的事，有很多话想说……」

雷姆握紧拳头，用力地说道，爱蜜莉娅继续露出困扰的表情。在旁边，梅莉看向拉姆，问道「不阻止吗？」

「没办法。只有这个，连拉姆也预想不到。——没想到，每天磨晨星锤的昴的胡话，真的派上用场了。」

「……在这之中，我最接近常识人，真的觉得不太好啊。」

连那个拉姆，都对晨星锤的力量过于相信的状况，梅莉感叹道。

不管怎样，关于『暴食』的事，包括推测的范围在内，有必要和雷姆她们共享。佩特拉觉得这件事交给爱蜜莉娅就好，她用余光看着爱蜜莉娅和雷姆的梦中演出，重新看向罗姆爷。

然后——

「虽然柯林特哥哥还没把老爷他们带回来……但没时间了。我们和罗姆爷爷你们是合作关系，对吧？」

「——嗯，没错。继续王选是我们全体的意愿。」

「那么，请告诉我。罗姆爷爷在阿尔先生身上注意到的事。」

在平原汇合，一起飞到王都的罗姆爷。因为柯林特的『压缩』，他选择和顿珍汉加斯顿他们分头行动，和爱蜜莉娅她们一起战斗，然后在一次冲突中掌握了阿尔的重大情报，他以此为前提。

到目前为止的谈话，爱蜜莉娅阵营和菲鲁特阵营已经是一条绳上的蚂蚱。佩特拉觉得差不多该互相敞开心扉了，她向罗姆爷提出要求。

面对佩特拉的要求，罗姆爷拍了拍自己的秃头，

「这件事，是相当不合常理的非常识内容。老朽隐瞒不是因为装模作样，而是信赖性的问题。」

「没问题的，我信任罗姆爷。我可是认真到罗姆爷要是知道的话，一定会吓一跳。」

「……你也是个十分奇怪的女孩呢，佩特拉。」

是觉得佩特拉在说客套话吗？罗姆爷垂下眉毛，无奈地嘟哝。

但是，佩特拉没有说谎。佩特拉信任罗姆爷，因为他很重视被阿尔他们当成人质的菲鲁特，知道他拥有为了菲鲁特可以毫不犹豫舍弃性命的父性。

所以，罗姆爷在意的信赖门槛，打从一开始就已经通过了。

不知道佩特拉这些隐情的罗姆爷，现在也很在意爱蜜莉雅和雷姆在互相磨合彼此的认知。

「这件事之后也会传达给爱蜜莉雅她们……阿尔德巴兰那家伙，恐怕使用了被称为权能的犯规招数。」

『——权能。』

罗姆爷慎重选择的词汇，让「昴」比佩特拉先有反应。

停止空中回旋的「昴」表情僵硬，目不转睛地盯着罗姆爷的脸。想象中的昴会有这种反应也是当然的，因为刚刚才从克林德口中听到，佩特拉和「昴」都对权能这个单词有不好的印象。

那是「怠惰」大罪司教，沉眠在坟墓的「强欲魔女」说过的单词。

干涉这个世界的存续方式，颠覆概念，随心所欲地替换法则的强大力量，显现。

罗姆爷判断阿尔使用了那个的理由是——

「——那家伙，似乎可以回到过去。不过时间好像不长。」

8

——结果，自己非做不可的事是什么？

从小时候就一直持续的「命题」，在被阿尔德巴兰一伙人带走的现在，也毫不客气地纠缠菲鲁特。

「真是的，烦死人了。」

烦躁地抓头，菲鲁特吐出累积在肚子里的愤恨。

无力感和放弃，菲鲁特知道这些感情对生存没有帮助。明明如此，这些家伙却既不能润喉也不能填饱肚子，却用尽各种手段涌上，想把人的身体填满，妨碍人活下去。

「——呿！」

咂了嘴，菲鲁特咬下拿到的晚餐肉干，用力咬碎。对过于强烈的咸味感到不满，对自己变得奢侈而傻眼。

才被拆散短短两天半，已经怀念起和芙兰姆、格拉西丝一起吃的饭。

偶尔出现在餐桌上的艾莎和拉珍斯他们那些重口味的男子汉料理也比携带粮食好得多。虽然让莱因哈鲁特下厨的话，芙兰姆她们会生气地说「适才适所」，不让莱因哈鲁特做，但偷偷让他做点心的话，手艺其实不差。

遗憾的是，菲鲁特和罗姆爷的料理手艺惨不忍睹，亏他们能在这座赃物库里待了将近十年，没因为食物中毒而死。或许菲鲁特的成长比同年代的人缓慢，原因就出在这里。

姑且不论阵营的料理情况——

「我不会做菜啦。那我到底会什么？」

用舌头舔掉指尖沾到的盐巴碎片，眯起红色眼睛，菲鲁特的思考回到最初的「命题」。

——现在，阿尔德巴兰一伙人不断转移据点，努力恢复阿尔德巴兰和「神龙」在王都的消耗。当初菲鲁特以为逃离王都的阿尔德巴兰等人会直接前往目的地莫格雷德大喷口，但看来并非只要抵达当地就好，似乎在选择时机。

只不过，等待时机的休息绝不能说顺利——无情的追踪者，奥托・苏文的执拗妨碍。

「不只和虫子说话，那加护太可怕了……应该说，可怕不是加护，而是佐达虫小哥是可怕的人吧。」

奥托虽然一脸悠哉，但本性似乎是必须特别注意的人物。

极端来说，任何加护都只是一种道具。就算持有再好的剑，如果没有挥舞的腕力、学习使用方法的机会和意愿，以及在关键时刻挥舞的勇气，剑就只是华丽的装饰品。

奥托有腕力、机会、意愿和勇气——然后，菲鲁特也必须以不持剑的方式证明自己也有这些。

「那个小哥的方针就是削弱……想些下流的事。」

似乎借由「言灵的加护」让虫、鸟、鱼成为同伴的奥托，让阿尔德巴兰一伙人连片刻的安宁都没有，被迫随时应对。

虫的振翅声、野兽的嚎叫、污水和食物的污染，这些弱点多不胜数，连睡眠时间都无法确保，因此被迫同行的菲鲁特也感到头痛。

但是，这种程度的连累对菲鲁特来说是可爱的被害，也已经做好心理准备。可以的话，菲鲁特也想利用与敌人同行的立场，毫不留情地协助奥托的作战。

「光是成为『神龙』的抑制力，就有意义了吧……」

但是光是这样还不够，这是在王都的「神龙」与「剑鬼」的战斗中明白的。

即使菲鲁特的存在削弱了「神龙」一成的力量，剩下的九成也足以发挥灾害级的力量，这才是「神龙」波克肯尼卡的真本事——考虑到之后曾经败北的罗姆爷有可能再次挑战阿尔德巴兰等人，光是现在这样还不够。

眼下，这是被囚禁的菲鲁特应该抵抗的「命题」。

「不对，还有一个。」

菲鲁特如此低喃，看向从自己的立场来看的另一个「命题」。

「————」

正面，隔着发出啪叽啪叽声的营火，有个与菲鲁特相对的男人——不，正确来说不能说是相对。毕竟对方低着头，连看都不看她一眼。

将入鞘的剑抱在胸前，宛如死去般安静蹲着，全身散发出阴郁气息的红发男子——亨克尔。

在岩场自然形成的洞穴入口，菲鲁特与亨克尔两人独处，等待确认周围安全与排除妨碍的众人，一起度过阴郁的时间。

亨克尔姑且是负责监视菲鲁特，但以看着对方的频率来说，根本分不清谁才是被监视的一方。别说晚餐的肉干，连水都不喝，彻底拒绝外界的举动，全力持续刺激菲鲁特的神经。

菲鲁特断言自己没有好坏的基准来判断亨克尔的举动。那不是谎言，也不会改变意见——但有好恶的基准。

至少，明明活着却像霍洛一样，被她判定为最讨厌的类型。

「喂，不吃的话，那个肉干给我。」

「————」

「你有听到吧？别无视我……啊，哦哦。」

一开始就不想吵架，所以菲鲁特用肉干当话题的开端，结果却被扔过来的肉干给堵住嘴。慌张地接住肉干，但亨克尔看都不看这边。

突然，觉得张开拳头的自己很蠢，菲鲁特再度喊道。

「为什么要在那时候插手？」

单刀直入，菲鲁特堂堂正正地切入亨克尔蹲坐的原因。

「————」

亨克尔保持沉默，但是，既然会扔肉干过来，就代表没有完全拒绝外界。以此为前提，菲鲁特轻轻哼了一声。

「你老爹……真难说出口。莱因哈鲁特的祖父和『神龙』打架，我不是战士，所以不清楚那场架哪边占优势。不过，你应该站在『神龙』那边吧？」

「————」

「你插手的话，就代表『神龙』很不妙。虽然那也很夸张，但有奇怪的地方。——你的目的是『龙血』的话，祖父快赢的时候应该是绝佳的机会。」

「————」

「龙死了的话，说不定就能拿到血，但你却妨碍了。为什么？」

趁着对方没有反驳，菲鲁特毫不客气地说道。

正如她所说，从亨克尔的目的来看，插手「神龙」和「剑鬼」的战斗极其不自然。虽然也怀疑动机是来自对父亲的强烈恨意，但亨克尔在和「神龙」飞走前，拜托龙治疗被自己刺伤的威尔海姆。

也就是说，亨克尔不希望「神龙」或「剑鬼」在那场战斗中死去。

「太不协调了。你到底在想——」

——什么？正要继续说下去的瞬间，菲鲁特被瞬间推倒在坚硬的地面上，拔出的刀刃抵在她的脖子上。

「你太多话了，小鬼。」

亨克尔充血的蓝色双眸近在眼前。菲鲁特被他吐出的血腥味呛到，皱起眉头。在这期间，亨克尔依然恫吓菲鲁特，刀刃滑过她的脖子。

「不想吃苦头的话，就给我闭上嘴——呃啊！？」

趁着恫吓的空隙，菲鲁特毫不犹豫地挥出拳头，打中亨克尔的鼻梁。

「呜、啊？」比起疼痛，被殴打的惊讶更让亨克尔翻白眼。菲鲁特趁势踢向他的胸口，俯视着跌坐在地的亨克尔。

「事到如今，我怎么可能怕你。」

说完，菲鲁特捡起亨克尔掉在身旁的剑。亨克尔瞬间身体僵硬，但菲鲁特叹口气，将剑扔给他。亨克尔立刻接住剑，瞪大眼睛，菲鲁特对此耸了耸肩。

他应该很疑惑菲鲁特为何要还剑，但对菲鲁特来说，这是理所当然的判断。

就算菲鲁特在这里大闹也赢不了亨克尔，万一亨克尔不小心砍了菲鲁特，八重肯定会非常高兴。说起来，让菲鲁特和亨克尔两人独处，八重的目的就很明显了。

八重想趁机舍弃菲鲁特和亨克尔两人。为了不让她得逞，这时候大闹不是上策——就算不讲道理，菲鲁特也知道自己不是来揍亨克尔的。

「那莱因哈鲁特的职责又是什么？」

「——唔。」

一听到莱因哈鲁特的名字，亨克尔又夸张地抖了一下。

比自己年长一倍以上的男人，被菲鲁特的言行吓得发抖，实在是很丢人。但是菲鲁特想知道他丢人的理由。

即使那会为菲鲁特带来非常苦涩的滋味。

「跟刚刚一样，什么都不用回答。我自顾自地说，自顾自地听。」

拍了拍被推倒时弄脏的衣摆，菲鲁特不等对方回答，仰望天空。从岩场缝隙间窥见的夜空，有几颗不合时宜的明亮星星闪耀。

瞪着那讽刺的美丽天空，菲鲁特开口：「实际上——」

「我被『神龙』和祖父吵架的事吸引，是因为刚刚的话。明明想要『龙血』，你做的事却很矛盾。然后，看起来很矛盾的还有另一个——『暴食』。」

「——」

「那家伙性格恶劣，是个嘴上不饶人的混蛋，这点先无视。就算不考虑这点，大罪司教这种人渣，根本没人会欢迎……但是讨厌那家伙的理由，比起我，你更有理由吧？」

沉默不语，什么也不回答的亨克尔，被这么一问屏住呼吸。就算不用言语回答，从反应就能轻易看穿的亨克尔，让菲鲁特眯起眼睛。

从监狱塔被释放，阿尔德巴兰为了计划而同行的罗伊・阿尔法德——虽然产生许多悲剧的大罪司教被讨厌、憎恨的理由不胜枚举，但亨克尔应该有更明确、绝对的敌意理由。

因为莱因哈鲁特的母亲，也是亨克尔的妻子——持续沉睡的卢安娜・阿斯特雷亚的被害，跟「暴食」的被害者有显著的相似之处。

「虽然只说过一次，但我很清楚你的……莱因哈鲁特家的状况。大叔的妻子沉睡了十年以上，找不到叫醒她的方法。唉，只要有了『龙血』就能解决……但你打算怎么算这笔账？」

「——」

「让你的妻子沉睡十年以上的混账，你打算怎么算这笔账？」

经过库珥修・卡尔斯腾公爵袭击事件和水门都市普利斯提拉攻防战，「暴食」权能的被害被厘清，「睡美人」——周围的人不知道其存在，被发现时处于不会醒来的沉睡状态，与所有联系都被切断的悲剧存在。发现她们无一例外都是魔女教的被害者。

当然，亨克尔应该也听过。尽管如此，亨克尔却对可能是妻子沉睡原因的「暴食」，至今从未表现出兴趣。

——因为得到「龙血」，让妻子醒来是第一要务？

——亲手刺杀父亲，被父亲的血溅到的冲击让他无暇顾及？

又或者是——

「如果他真的没把那家伙放在眼里，那又是为什么？」

「等、等等……你在……」

「不用回答。我说过了，我自顾自地说，自顾自地听。」

握剑的手颤抖，亨克尔用土色的脸看着菲鲁特。阿斯特雷亚家的蓝色瞳孔和自己的红色瞳孔视线相交，菲鲁特确信了。

亨克尔的瞳孔深处，有非常不可靠，但却不会消失的余火——那大概和罗姆爷看着菲鲁特时，寄宿在瞳孔中的热情是同一种。

自暴自弃、自我中心、任性妄为、不知天高地厚又没有主见，看起来是无可救药的男人——亨克尔・阿斯特雷亚。在那最深处，若能窥见些许热情，而那热情又常在那男人行动的一端，那么。

「你没去找『暴食』，是因为你知道你老婆睡着的原因和『暴食』无关。因为知道搞错对象，所以剑也指向错误的方向。不过……」

——卢安娜・阿斯特雷亚的「睡美人」被害状况，和其他的「睡美人」有决定性的不同。

和其他被断绝与世界所有联系的「睡美人」不同，卢安娜的事莱因哈鲁特、亨克尔和所有相关人士都记得，为她的沉眠感到惋惜。

也就是说，不一样。卢安娜・阿斯特雷亚不是「暴食」的被害者。然后，亨克尔知道这个事实，却没告诉任何人。

为什么？因为不能被知道——让卢安娜睡着的原因。

那个原因就是——

「——莱因哈鲁特。」

「——」

——凝然睁开的双眸、失去声音的表情、失去生气的吐息，这些都比话语更能说明答案，菲鲁特的确认得到后援。

自己必须做的事——知晓，就是菲鲁特现在的「命题」。

面对那个「命题」，觉悟和确信引导出的，是苦涩至极的真相，那就是——

「——让莱因哈鲁特的母亲睡着的，是莱因哈鲁特那家伙吗？」

《完》

** 后 记

势如破竹地更新的第九章，41集！由长月达平＆鼠色猫献给各位！

漫长的帝国篇结束，舞台回到王国，许多久违的角色登场，如同上次提到的，第九章的主题是「疾风怒涛」，希望各位读者能感受到与主题相符的剧情发展！

受到上集最后使出的「禁招」影响的佩特拉、带着一群胡闹的伙伴勇往直前的阿尔德巴兰、突破障碍却逐渐遍体鳞伤的阿尔德巴兰一行人，以及唯一一直乐在其中的罗伊・阿尔法德，这一集也充满了精彩之处！我刻意不在后记提到她！

这次的故事，果然少不了从动画第三季得到的灵感！动画本身的质量当然不用说，各位观众的反应与感想更是我的动力，灵魂因此燃烧，让我自认写出了好作品！令人高兴的是，也发表了动画第四季的制作与26年播出的消息，我会将这股热情投注在第九章的未来，以及之后的章节，还请各位继续支持！

那么，接下来是已经看惯的超短后记，按照惯例进入谢词环节！

I责编，我在写作期间得了两次感冒，截稿日又碰上活动高峰期，您对自顾不暇的作者的照顾，我感激不尽！这次也谢谢您了！

大冢老师，虽然每次都是这样，但这次我尤其受到大冢老师的画力和作画速度的帮助！您甚至把后记的篇幅都让给了我，真是感激不尽！能看到久违登场的角色们的新形象，这一卷也成为了我珍藏的一本！

草野老师，这次插画中登场的角色很多，是您大展身手的机会，这次您的工作成果也很出色！谢谢您！

花鸡老师＆相川老师的第四章漫画版，以及高濑若弥老师的第五章漫画版，两位都用强烈的绘画力量提高了故事的强度，让我也经常鼓起干劲，不能输给她们！今后也请继续关照！

MF文库J编辑部的各位，校对，各书店的负责人，业务，这次也承蒙大家的照顾了！今后也请各位助我一臂之力！

最后，我要感谢一路陪伴我走到这里的各位读者！本作能获得原作、漫画化、动画化等众多幸福，都是多亏了各位的支持！今后也请各位多多关照故事、角色和作者！

那么，我们就在第42卷再会吧！『疾风怒涛！』的故事会如何发展，敬请各位拭目以待！谢谢大家！

2025年5月《第四季动画也令人期待！今后也请多多关照！》

Re：从零开始的异世界生活 41

长月达平

ＭＦ文库Ｊ

2025年6月25日　发行

ver.001

©Tappei Nagatsuki 2025

本电子书是下述作品修改后制成的

ＭＦ文库Ｊ『Re：从零开始的异世界生活 41』

2025年6月25日　初版发行

发 行　株式会社KADOKAWA

●　关于本书的咨询请发送至以下地址：

KADOKAWA　BOOKS　咨询室

（请注明「MF文库J」负责人收）

●　关于作者、插画师、封面、刊头彩页、卷末插画的咨询请发送至以下地址：

Sneaker文库咨询室

●　关于漫画版的咨询请发送至以下地址：

Sneaker文库咨询室

轻小说/动漫/漫画/游戏 总链接

https://link3.cc/acg123


