#+title: Re:从零开始的异世界生活 第四十二卷
#+setupfile: ./setup.setup

* 第四十二卷
** 序幕 『魔女的祝福』

１

「──谁也无法、战胜我创造的你哦」

如此低语的『魔女』微笑，在阿尔德巴兰眼中映出血色。

如同依偎、如同怜爱、如同哀叹如同倾诉如同渗透如同奢望，在吐息可及的距离，『魔女』凝视着阿尔德巴兰。

那张白皙的面容，那双漆黑的眼瞳，阿尔德巴兰觉得真美啊。──大概，在阿尔德巴兰的认知里，她的美丽堪称数一数二。

──银色与紫绀的组合，和纯白与漆黑的组合。

这对实质只知晓狭小世界的阿尔德巴兰而言，正是世间最美的色彩搭配，是至高无上的顶峰。

２

持续挑战多次的外壳破碎时，其手感之空虚令人吃惊。

「────」

哐啷一声，黑色球体落在茶会的桌面上。目睹着它骨碌碌滚动，阿尔德巴兰茫然地睁大了双眼。

成功案例已目睹多次，甚至亲身体验过几次，但距离自己成功施展还遥遥无期，总有种在永无止境地挥棒击打看不见的球的感觉。

当然，这既是她的嘱咐。虽然早有心理准备迟早会来——

「真要成功的时候，居然这么简单吗……」

阿尔德巴兰一边嘟囔着毫不掩饰的真心话，一边拾起在桌上滚动的黑球，掌心把玩着那既不冰冷也不炙热的神奇触感。

虽外观朴素，这黑球却是阴魔法的极致——不，是偏离正道、穷尽邪路的禁术『奥尔・纱幕』。通过将效果对象限定于魔女因子，从而将效力提升至极限的世界唯一对抗『魔女』的王牌。

这正是阿尔德巴兰被要求必须掌握、并为此努力至今的超魔法。

『——打扰你沉浸其中真不好意思，但该稍微关注下我了吧』

「呜哇啊!?」

突如其来的声音让阿尔德巴兰大吃一惊，黑球从手中飞脱。只见那黑球抗议着『喂喂喂！』，顺着草原的斜坡滚落下去。

「啊ー，糟糕了。别在意」

『这说话方式完全不像不在意的样子吧。喂，快点捡起来捡起来』

「好啦好啦」地应和着，阿尔德巴兰追向滚走的黑球。幸运的是，草原的草高在低处都很整齐，不用担心看丢球。

「话虽如此，滚得比想象中远……难不成，老师变成球的样子反而动作更灵活吗？就保持这样？」

『别说这么可怕的话。虽然是自己开发的禁术，但对魔女因子的特效效果太好，真的没法靠自己出来。要是你真的鬼迷心窍想把我关起来，我可没有抵抗的手段』

「把老师就这样，嗯」

『哎呀？为什么用有点可行的感觉嘟囔了啊？好可怕好可怕。那是为了逼我妥协的玩笑对吧？』

明明是连感情都不明白的『魔女』，却擅长装出害怕的演技，有点让人火大。

そんな感想を余所に、アルデバランはようよう势いの止まった黒球を见つけ、ひょいとそれを拾い上げると、またしても手の中で転がした。──一瞬だけ、このまま『魔女』を闭じ込めておくのも、なんて気持ちがむくむくと芽生える。

『──阿尔德巴兰？』

但是，那种一时的鬼迷心窍，随着『魔女』的一声呼唤便轻易消散了。

取而代之残留在内心深处的，是终于滚滚涌上的实感，以及随之而来的不安。这是长期以来被灌输的观念的总决算，有着那份临阵的颤抖。

「如果老师从这里出去的话……」

『──？　怎么了？』

「大概、准备得差不多了吧？我的权能、还有必要的魔法、另外……」

『你的成长。是呢。——那时机、临近了』

阿尔德巴兰的心情不知是被理解还是未被理解，『魔女』的声线始终平淡。

因为她时不时会流露出孩子气的一面，或是展现出奇怪的幽默感，所以容易让人产生误解。她是『魔女』，和阿尔德巴兰只是因某个目的而相连的关系。

明明绝不可能心意相通，也不可能被珍视。

『你稍微有点误会了呢』

「咦？」

突然，在正要下定决心前被出乎意料地打断，漏出了傻乎乎的声音。在阿尔德巴兰的手中，被赋予破坏意图的黑球如闪电般龟裂。

理应唯有术者之手，或至少需权能乃至『龙剑』方可破坏之物就此碎裂──

「────」

下一秒，阿尔德巴兰仰望着从黑球中被解放的『魔女』。

『魔女』以压倒的姿势凝视着仰卧在草原上的阿尔德巴兰。被近在咫尺的『魔女』的黑瞳所震慑，阿尔德巴兰语塞。

对着沉默不语的阿尔德巴兰，『魔女』继续说道。

「不必不安。我已为你备齐所需知识，而你也将我布置的课题悉数完成。且未曾理会其他『魔女』的闲言碎语呢」

「老师，我……」

「无需多言」

颤抖的嘴唇被手指轻按住，让阿尔德巴兰沉默的『魔女』神情骤变。那薄唇弯成半月形，『魔女』露出了前所未有的微笑。

那是足以掠夺阿尔德巴兰的视线、夺走他的呼吸、俘获他的心灵般的，血色的微笑。

本应只拥有黑白两色的『魔女』所展现的，鲜血的色彩──

「──谁都无法战胜我创造的你哦」

那句话滑入鼓膜，渗透进阿尔德巴兰的大脑，烙印在灵魂之上。

不要忘记、不要忘记、不要忘记，如此刻入阿尔德巴兰体内的那句话，正是对于直至今日仍持续追逐星辰的阿尔德巴兰，来自『魔女』的祝福。

『魔女』从不说错话。──因此，那便是真实。

「……谁都无法战胜我」

「啊啊，正是如此。希望你能证明这一点。想必，不会有人愿意称颂你吧……但我发誓，唯有我会由衷祝福达成目标的你」

那道誓约，对阿尔德巴兰而言，正是无法抗拒的『魔女』的诱惑。

在这个世界上，阿尔德巴兰只希望两个人认可自己的存在。既然其中一人已无法期望，便只能向剩下的一人祈愿。

「我会赢的，老师。──为了我能继续作为我而存在」

「────」

阿尔德巴兰如『魔女』所料地在心中点燃火焰，如此回答道。

听到那个答案的『魔女』，维持着微笑，漆黑眼眸中却流转着截然不同的感情。那究竟是源于『魔女』怎样的伤痛，阿尔德巴兰无从知晓。

只是，相信着『魔女』的话语、教诲与祝福。

眼前，是白与黑的美丽『魔女』。闭上双眼，是银白与紫绀的美丽『魔女』。

追逐着那炫目、可憎闪烁的星辰，阿尔德巴兰持续等待着那个时刻。

终于，这份等待将得到回报。他如此坚信。仿佛要将那份献给坚毅的阿尔德巴兰的祝福化作实体，『魔女』的嘴唇，落在了阿尔德巴兰的额头上。

感受着那唇瓣的触感，『尾随星』一边体会着『魔女』那近乎哀求的愿望，一边低语。

「──我必定，会将你杀死」

** 第一章 『最后的底线』

１

「──昴大人与碧翠丝大人，落入了名为阿尔德巴兰的人物手中。痛恨。目前，正以爱蜜莉娅大人为中心，推进针对该人物的应对策略。报告完毕」

そう、『忧郁』の権能を用いて飞んできたクリンドの报告を受け、ロズワールは起こった出来事の理性的な受け入れと、感情的な受け入れの难易度の落差に戸惑った。

场所是露格尼卡王国南方的跋利耶尔领──死去的普莉希拉・跋利耶尔曾居住过的跋利耶尔宅邸。罗兹瓦尔之所以会在从亡夫莱普・跋利耶尔那里继承下来、再次失去主人的宅邸里，是以帮忙各种手续和善后为名目，跟随了曾是普莉希拉仆从的修尔特。

从佛拉基亚帝国归还，向仆人们报告了主人不会回来这一事实的修尔特，虽然尚且年幼，但可以说出色地完成了任务。对于他那份坚强的工作态度，以及有不少仆人流下了眼泪这件事，罗兹瓦尔感到了一丝惊讶。

普莉希拉是个性格苛刻、给人以生人勿近印象的人。由于在领地经营上取得了超出相应的成果，领地居民对她抱有好意是可以理解的。但是，本以为取而代之的是会被自家人恐惧，可看来似乎也并非如此。

对修尔特的印象，在前往跋利耶尔领的途中也发生了很大的改变。

看来普莉希拉让修尔特接受了正规教育，加上他本性就想报答恩人，所以比起同龄人对事物的理解能力要出众得多。

照这个势头的话，和修尔特同行的罗兹瓦尔的目标，或许会比预想中更顺利地进行。——就在柯林特带来开头那份报告的时候。

「────」

阿尔的暴行，那就是对关心他的昴他们的背叛。

老实说，对于将伤心的阿尔带去普雷阿迪斯监视塔的昴的提案，罗兹瓦尔完全不欢迎。

仅仅是把被抛到佛拉基亚帝国的昴带回来就花了那么多时间。──虽然雷姆也同样被抛了过去，但罗兹瓦尔并不喜欢欺骗自己。罗兹瓦尔的目的就是带回昴，雷姆的安危是次要的。

无论、雷姆回来这件事对阵营全员来说都是值得高兴的，但并不能因此认为所花费的时间是无价的。必须立刻行动起来，为了挽回为王选准备的对策的延误。——昴提出前往普雷阿迪斯监视塔的商量，正是在他这么想的时候。

现在最应该优先的是什么。罗兹瓦尔本想从这个角度说服昴，但昴的意见顽固不屈，最终，昴的商量被通过了。

即便如此，也并非全无好处。——修尔特。

「拜托了，拜托您照顾阿尔大人了……」

虽是孩童，但作为普莉希拉的随从力求贤明的修尔特，担心因普莉希拉之死而沮丧不已的阿尔，为了阿尔而深深地低下了他那带点卷翘的桃色头发。

——而要赢得这位修尔特的好感，这次昴的提案非常有用。

让修尔特产生好感，让爱蜜莉娅阵营卖个人情，这对于如何处理即将空缺的跋利耶尔领地这一王选战略来说，是一个巨大的优势。

王选开始后，成为王座角逐者的爱蜜莉娅与普莉希拉，二人在竞争中互相认可，成为了心意相通的挚友。随着普莉希拉的离世，继承她遗志的爱蜜莉娅开始扶持引导其庇护下的跋利耶尔领民众——而要促成这个剧情，深受普莉希拉宠爱的修尔特是不可或缺的角色。

毕竟也从爱蜜莉娅那里得到了'等王选结束后想和普莉希拉成为朋友'的承诺，稍加润色应该算是常见创作手法。

正因如此，罗兹瓦尔才同意昴等人前往普雷阿迪斯监视塔，并独自造访跋利耶尔领而未与爱蜜莉娅同行——然而，这是失策。

「昴大人他们……那、加菲呢？加菲怎么样了？他明明是为了保护昴大人才跟着去的呀」

「遗憾。加菲尔败于阿尔德巴兰的计策身负重伤。昏迷。虽想仰仗'地灵加护'的效果，但负伤地点在奥古利亚沙丘……受瘴气弥漫之地影响。效果受限。微弱」

「加菲……」

在沉思的罗兹瓦尔身旁，同往跋利耶尔领的法兰黛莉卡从柯林特处得知了曾担任昴等人护卫的加菲尔之事，用手掩住了嘴角。

那侧脸上浮现的，并非对未能完成被赋予职责的加菲尔的失望或沮丧，而是对性命无虞的安心、以及对弟弟内心忧虑的浓重担忧。

罗兹瓦尔也同样对加菲尔的存活感到宽慰，然而──

「……真让人想不通啊─。本来嘛，阿尔殿下的实力应该远不及加菲尔。当然，加菲尔心里还留有不少破绽，要说他是被针对精神弱点、钻了空子倒也很有可能就是喽─」

「……若是小加菲的话，那倒是最有可能的情况了。那孩子，还太天真了」

「温柔并非该受指责之事。纵然是为了律己，也无须刻意选用严苛之辞。指正」

「你这男人，偏偏这种时候就……」

面对柯林特的关怀，法兰黛莉卡神情复杂地磨了磨牙。

这两个人的交往，也是从法兰黛莉卡离开『圣域』、开始在罗兹瓦尔那里工作的十多年前就开始的，但一旦产生的隔阂却难以弥合。

当初、法兰黛莉卡把柯林特当作兄长般仰慕，无论什么事都追在他后面喊着「兄长大人兄长大人」，但自从法兰黛莉卡开始长高后，两人的关系就彻底改变了。

那是以什么为契机的事情呢、知道情况的罗兹瓦尔对柯林特表示了理解、但突然被疏远的法兰黛莉卡并不接受。就因为这样、她才会像对待蛇蝎一样一直讨厌着他、真是让人无话可说呢。

总而言之──、

「柯林特、从你的那种态度来推测，单纯地无法责备加菲尔的理由貌似是存在的吧。……发生了什么，事情呢？」

「────」

「柯林特？」

对于罗兹瓦尔的询问，柯林特罕见地没有立刻回答。

那分不清是犹豫还是踌躇的片刻停顿的理由，在接下来的回答中立刻明白了。

「──『神龙』波克肯尼卡的龙壳竟会服从阿尔德巴兰。为此，『剑圣』莱因哈鲁特・范・阿斯特雷亚大人已前往镇压。急报」

「──『神龙』波克肯尼卡居然服从阿尔德巴兰？而且还派出了『剑圣』大人？　不过，这样一来......」

「难道连莱因哈鲁特都被阿尔殿下镇压了吗？」

「确切而言，称之为'封印'更为恰当。订正」

「怎么会......」

「随之而来的是王都频发的各种问题。因此，爱蜜莉娅大人希望即刻借助老爷的力量。进言」

听闻柯林特这番话，罗兹瓦尔手托下巴陷入沉思。

法兰黛莉卡瞪大翠绿双眸愕然失色，尚无法消化这汹涌而至的情报——她的心境与罗兹瓦尔大致相通。不同于她的是，即便置身于理应溺毙的信息洪流中，罗兹瓦尔仍保有选择权。

换言之，现在不正是该履行与昴的约定之时吗？」

「────」

在昴正式接受骑士叙勋之前、『圣域』相关事态平息之际、罗兹瓦尔向昴表明了自己的想法和立场。

ナツキ・スバルが全てを拾い続けると誓ったのなら、この先、彼の手から何かを取りこぼすことがあれば、ロズワールは容赦なく彼にやり直させるための手を打つと。" -> "如果菜月·昴发誓要持续捡起所有一切的话，那从今往后，万一他手中漏掉了什么东西，罗兹瓦尔就会毫不留情地采取措施让他重来。

那是他不想失去的重要之物，也是罗兹瓦尔主观上对世界的舍弃。

「普莉希拉大人这边，虽然很难判断……」

是否要将普莉希拉纳入昴所说的『全部』之中，着实让人烦恼。

だが、最终的な政敌であるプリシラの死は、王选に参加するエミリアにとっての追い风になると判断し、ロズワールはその死を契约の外のものと判断した。──さらに言えば、伝え闻く限りのプリシラの死を、覆すべきではないとも思った。" -> "但是，罗兹瓦尔判断最终政敌普莉希拉之死对参与王选的爱蜜莉娅有利，认为她的死亡不属于契约范畴。──更进一步说，他觉得根据传闻所知的普莉希拉之死，不应被推翻。

普莉希拉・跋利耶尔的死，是普莉希拉・跋利耶尔选择的结果。

除非那是罗兹瓦尔目标中不可或缺的人才，否则罗兹瓦尔不会否定那个人应该受到尊重的选择。

──但昴现在的状况光是听起来就令人难受。

根据柯林特的话来看，似乎还没有出现明显的死伤者，但考虑到阿尔所处的状况，那也只是时间问题。既然迟早会变成那样，在被逼到这种地步的时候，就应该让昴重新来过了吧。

如果需要有人推一把的话，罗兹瓦尔就会来做那个推手。

但是──，

「──碧翠丝」

对于据说和昴一起被捕的碧翠丝，罗兹瓦尔怀着一缕希望。

那并非因为碧翠丝是精通阴属性的大精灵，也并非因为她是世界最强的魔法使『强欲魔女』艾姬多娜所创造的至高存在，甚至也不是因为她作为昴的契约精灵，会怀着强烈的感情与觉悟去保护他。

这对罗兹瓦尔来说是相当不可思议且难以消化的感情，但本就毫无根据。

在于罗兹瓦尔想要相信碧翠丝，在于他不由自主地这样想。

「──边境伯大人，请您务必下令是也」

发出这声音的，既非法兰黛莉卡，也非柯林特。

在宅邸的会客室里，为了推进关于跋利耶尔领地未来的讨论，同席在场的修尔特如此插话道。

『忧郁』的权能──通过『压缩』进行瞬间移动而现身的柯林特，以及他之后的报告让修尔特屡次发出「哎」「啊呜」等惊讶的声音，但现在，对罗兹瓦尔如此放言的幼童脸上，柔弱的神色已然消失──不，是被掩盖了。

人们将那掩盖了的、无法触及的妆容，称为勇气或觉悟。

「在下替阿尔大人犯下的过错赔罪。此外，还请诸位莫要让阿尔大人再涉险境」

「修尔特大人……」

「在下无妨。为了普莉希拉大人，宅邸的各位也会相助……恳请诸位成全！」

注视着深深低头的修尔特，法兰黛莉卡转而望向罗兹瓦尔。

她的眼眸中，充满了希望修尔特的愿望能够被应允的祈愿，以及至少想要成为他力量的倾诉──，

「最大程度遵循修尔特君的意愿的话……法兰黛莉卡，就不能把你留在这里了。既然阿尔大人带着『神龙』的话，呐」

「把在下……？老爷、这是怎么……」

「那是……」

「──关于那件事、由我代替她来应对。举手」

『神龙』与自己的关联性令法兰黛莉卡困惑不已、但比起罗兹瓦尔回答这个疑问、柯林特的进言更快一步。

「您要、代替在下？不、说到底、到底是代行什么……」

「时间宝贵。请你连同老爷的份一起、为修尔特大人尽力。奋励。……是蕴藏着珍贵可能性、难得的人才。希望」

「～～、请不要用您邪恶的性癖来窥视修尔特大人！」

涨红脸的法兰黛莉卡、从柯林特的视线中护住修尔特、如此咬牙切齿道。

但是、在那段对话旁、罗兹瓦尔对柯林特的提案瞪大了眼睛。他主动行动的宣言、有着表面上听起来更深的意义。

毕竟、无论被怎样劝说、柯林特本应是不会做出那个决断的。」

「再也无法袖手旁观了 被过于耀眼的灵魂光辉踢醒了后背。真是羡慕」

对着难以掩饰惊讶的罗兹瓦尔 柯林特微微松缓嘴唇 如此说道。

就连柯林特那温和的笑容　对罗兹瓦尔而言也只是增添了惊讶的要素。

２

「──让莱因哈鲁特的母亲长眠的 是莱因哈鲁特那混蛋吗」

对于自己竟一反常态地犹豫着是否该说出口　菲鲁特感到一阵苦涩。

这并非因为事情与莱因哈鲁特有关。不　某种意义上确实如此。

从相识之初起 菲鲁特就总是被莱因哈鲁特打乱步调 一旦事情与他相关 就常常无法做出符合自己风格的判断和决断。

这既有总是被他用武力干扰决策结果的影响 更进一步说 最初相遇时被他看到哭脸的经历也占了很大比重。──但大概 最主要的原因还是莱因哈鲁特擅自放弃了太多东西。

这使得菲鲁特犹豫是否该全盘接受莱因哈鲁特。同时　这大概也是莱因哈鲁特未曾将真心托付给菲鲁特的缘由吧。

菲鲁特心中来自贫民窟生长的处世哲学『坚强生存』乃是至理名言。

无论出身何处无论自己是谁唯有那份精神无论遭遇什么都能坚信其存活着。依照那份处世哲学来看莱因哈鲁特并未坚强生存。

无论是作为狮子还是作为龙抑或作为人，莱因哈鲁特都是半吊子的存在。

若是方才菲鲁特察觉到的事实正是造成此状况的部分缘由──

「──嗯呀，那样的话就说不通了啊」

然而，菲鲁特对自己刚刚想到的假设按下了暂停键。

带着某种确信，菲鲁特认定莱因哈鲁特与持续沉睡的母亲──卢安娜・阿斯特雷亚这位『睡美人』有关联，但倘若莱因哈鲁特知晓这一事实，那他至今的言行就实在说不通了。

当然，也不能排除莱因哈鲁特向菲鲁特隐瞒了这一事实，把自己与母亲沉睡原因有关的事情若无其事地隐藏起来的可能性。

「才怪呢。那个笨手笨脚的家伙怎么可能做出那么灵巧的事啊」

大概、除了菲鲁特以外，还会有其他人这样评价莱因哈鲁特吧。

等等，若是向抱有理想或梦想的『剑圣』提出忠告似乎会是这样，但这样一来反而意外地，在菲鲁特阵营中将莱因哈鲁特当作废物对待已成常态。

从小一起长大的菲菈姆和格拉西丝姐妹，总是亲昵地撒娇戏弄着莱因哈鲁特让他困扰，而毫无敬意的野狗般的加斯顿、拉珍斯、汉巴里三人，也对莱因哈鲁特进行着有理有据的咒骂诽谤。

负责阿斯特雷亚领内政的艾莎，经常追问莱因哈鲁特「至今你是怎么……」，而似乎对『剣圣』没啥好感的罗姆爷等人，则从一开始就对莱因哈鲁特态度冷淡。

そしてもちろん、この世で最もラインハルトをこき下ろし、悪口を并べ、理想とされる最高の骑士なんて称号に泥を涂りたくってきたのはこのフェルトである。" -> "当然毫无疑问，这世上最会贬低莱因哈鲁特、编排他坏话、往理想中最高骑士这种称号上拼命抹黑的，正是这个菲鲁特。

来自那个阵营伙伴们的各种言行，莱因哈鲁特都承受了下来。

一边承受着，他如何动作。──笑了出来。

那实在是显得很开心地，笑着。

仅在那一瞬间，他仿佛并没有放弃任何事物。

「就算你小子藏真心藏得再好，假货也挤不出那种笑法啊」

──莱因哈鲁特并不知道卢安娜沉睡的原因在于自己。

这就是菲鲁特的结论。与那些对莱因哈鲁特过度期待的家伙们不同，这是只有把莱因哈鲁特也看作寻常存在的人才能得出的答案。

因此，除了菲鲁特以外，能用这种方式看待莱因哈鲁特的，只有阵营内部的人员、与莱因哈鲁特亲近的友人骑士们，然后──

「──老娘觉得你小子藏不住事儿，这脸面上还得再加条理由，因为你是老娘养大的崽啊」

在如是说着搔头的菲鲁特眼前，单膝跪地的亨克尔紧握长剑，淌着鼻血的面庞一片惨白，嘴巴正一张一合地动着。

──在岩地的野营地，菲鲁特与亨克尔隔着篝火相对而立。

对直截了当干涉家庭私事的菲鲁特，亨克尔一度试图威胁。将剑抵来的对手鼻梁被狠狠揍了一拳，形势逆转，一边观察着那位亨克尔的脸色一边组织起来的，就是刚才所说的《睡美人》真相。

「────」

沉默不语的亨克尔，握剑的手过于用力，手指已经变得惨白。

导致他这样的既非愤怒亦非悲伤亦非恐惧，这点正从动摇的亨克尔青色眼眸中鲜明地传达给菲鲁特。

若要用一个词来形容那种感情，绝望最为贴切。

虽是得知了不该被知晓之事，却难以避免难以逃脱，不可饶恕的绝望。深深铭刻的这份绝望，正将亨克尔的心逼入绝境。

那过于惨痛的模样，甚至让菲鲁特产生错觉——亨克尔的生命该不会就要被绝望扼杀了吧。

但是，恐怕，亨克尔没那么容易死掉。

若是能被那份绝望夺去性命就此结束，他早就该变成那样了。

「──啊、咕、呜、不要、呜」

亨克尔嘴唇颤抖，持续漏出不成声的声音。

菲鲁特眯起红眸看着亨克尔的反应，仰望着从岩缝间俯视他们的星空，思索着眼前男子与莱因哈鲁特的关系。

──决定参加王选后，菲鲁特让莱因哈鲁特成为了自己的骑士。

对菲鲁特而言，莱因哈鲁特既是世界最强的骑士『剑圣』，同时也是让她与罗姆爷骨肉分离的元凶。更是个硬要给抗拒的菲鲁特灌输教养、套上礼服和高跟鞋的可恨家伙。

在那个前提下，菲鲁特虽然并没有特意向莱因哈鲁特追根究底地问这问那，但有些传闻还是不可避免地传入了耳中。

就是关于莱因哈鲁特在阿斯特雷亚家受到的待遇，以及世人对这件事的看法。

特に话として多いのは、先代の『剣圣』テレシア・ヴァン・アストレアの死にまつわる様々な噂と、『剣圣の加护』を継承したラインンハルトが正式に『剣圣』として认められた原因──彼が八歳のときに起こった、三国の奸雄が仕组んだ王国侵犯を阻止した事変。それから、骑士団に入団する前后まであった、父であるハインケル・アストレアの言いなりであったという拭い切れない汚点、といったところだ。

关于那些事情，莱因哈鲁特从未主动提起过半句，菲鲁特也一直没有深入追问过他，但如今只觉得违和感愈来愈强烈。

最大的原因，就是莱因哈鲁特对亨克尔言听计从。

如果那是事实的话，亨克尔的苦战又算什么呢。

菲鲁特虽然没有调查过莱因哈鲁特的事情，但为了掌握关系到阿斯特雷亚家当家权限的情况，所以调查过亨克尔的事。

尽管名声相当差，许多记录都显示亨克尔作为骑士和父亲都不合格，但他利用阿斯特雷亚家族的名义强行推进的事，全都是为了获得让持续沉睡的卢安娜苏醒的手段。

虽说不上本人清贫，但从数字上得来的印象是，他与贵族式的奢侈无缘，生活各方面都精打细算，把钱全都花在唤醒妻子上了。

但是──

「要是真能让莱因哈鲁特言听计从，怎么着都行了吧ー」

无论是名声还是武力，王国内都没有胜过莱因哈鲁特的人。

对此，莱因哈鲁特本人绝不会为自己使用它，并且有着以此约束自己为佳的风范，但若是传闻中的亨克尔的话就不会这样了。

如果亨克尔是如传闻中那般的人物，那么即使是莱因哈鲁特的声誉也好武力也罢，无论什么都能利用起来，本可以完全省略掉特意亲自赶赴当地、直接与对方交涉、若谈崩了就用剑技强行贯彻道理这般胡来的连锁行为的。

非但如此，为何还执意不让莱因哈鲁特插手，非要靠自己的力量让持续沉睡的妻子醒来。

倘若妻子重于一切，那么无论在天秤另一端放上什么都不会使其倾斜。——除非对侧托盘上放着同等沉重之物。

如果菲鲁特的猜想正确——

「你这家伙……你所谓的重视方式，也扭曲过头了啊」

「——！」

瞬间，原本瑟缩的亨克尔咬紧臼齿，眼中迸出厉光。

迟了一拍才膨胀的剑气掀起劲风，菲鲁特只见寒光一闪，待冰凉的剑尖抵上自己脖颈，才意识到亨克尔已然拔剑出鞘。

「少在那边……絮絮叨叨地说些多余的话」

「喂，先说好……」

「别动！」

面对双目赤红、嘴角泛沫的亨克尔的怒斥，菲鲁特用牙齿内侧咬住脸颊肉，懊悔自己逼人太甚的失策。

与刚才挨打时的直白威胁不同，此刻亨克尔的气势中蕴含着明确的杀意──那并非源自憎恶或愤怒，而是某种防卫本能。

「这是咱家内部的问题。岂容外人肆意插手。更何况像你这样一无所知的小鬼，岂能让你再插手──」

「──再插手？难道还有后续？」

「──啧，闭嘴！」

菲鲁特从亨克尔的只言片语中察觉到端倪，忍不住插话。就在她以为对方脸色会再度剧变的瞬间，亨克尔猛然爆发了。

剑尖轻巧后撤，陡然加速前刺，去势远超后撤幅度──仅在刹那。

「拜托别刺激大叔了啊」

倏然闯入的人影挥动手中石剑──石龙刀，毫不留情地砸中屈膝的亨克尔太阳穴。随着「嘎呜!?」的痛哼，翻着白眼的亨克尔瘫倒在地，而阿尔德巴兰正俯视着他咂嘴摇头。

危急关头插手的阿尔德巴兰，对于他的登场菲鲁特不屑地哼了一声。

「你这混蛋，居然一直看到我差点就要动真格玩完的地步」

「不过你这个小妮子，不也隐约察觉到我在盯着免得你不小心被杀掉，才和大叔聊起来的吗。这招可真不可爱」

「老娘我最讨厌被人说什么可爱了」

菲鲁特「呸」地吐出舌头，丝毫没有向阿尔德巴兰道谢的意思。

只是确认了倒下的亨克尔并没有死，叹了口气。——从亨克尔最后的话来看，莱因哈鲁特似乎还藏着什么。

这位众人公认的『剑圣』，似乎又是让母亲长眠的缘由，再加上让亨克尔变成那样也要隐藏的某些事情——

「差不多吧，坚持不到他主动坦白就什么都不问，也变得有点不负责任了呢」

「这还真是，了不起的表态。你清楚现状吗？」

「照你的说法，你并没打算加害于咱，等目的全达成了，还想让王选重新启动是吧？咱倒是盼着你输，不过眼下无论输赢，咱之后该做的事儿都一个样」

「真叫人无言以对」

菲鲁特对着飘飘然挥着右手的阿尔德巴兰又哼了一声，走近昏厥的亨克尔，试图将出鞘的剑收回剑鞘。但亨克尔即便失去意识也不肯松手放剑，菲鲁特只好将就着用剑鞘凑合，勉强纳剑入鞘。

「嘁」

就在剑将入鞘的刹那，刻着『阿斯特雷亚』之铭的剑锋寒光，在菲鲁特眼中显得格外冷酷无情，令她火冒三丈。

３

「──那家伙，似乎能回溯已逝的时光。虽说貌似没法倒流太久就是了」

罗姆爷用大手摩挲着自己的秃头，面露苦涩地如此说道。

那张脸上浮现的，是认真苦恼的痕迹。老人的眼中，对自己所得结论的疑虑、以及将其说出口的不安，都丝毫不见踪影。

我如此确信着。──敌人正在穿越时间。这般，荒谬至极的结论。

而这件事绝对无法一笑置之，佩特拉・雷蒂心知肚明。

「────」

倒吸一口气，将差点漏出的悲鸣压抑回去，佩特拉紧紧地握紧了拳头。即便如此还是没能完全化解冲击，引来了担心的声音问道：「佩特拉酱？」

定睛一看，装饰高贵的王侯馆室内──聚集于此的人们中断了之前的谈话，正关注着佩特拉的状况。

「大个子老爷爷呀，你对佩特拉说了什么来着？」

尤其是对罗姆爷投以严厉目光的是梅莉。

在她的眼中佩特拉似乎背负着极大的悲怆感，于是对那位看似谈及了导致如此状况话题的罗姆爷，眯起圆眼睛这般追问。

面对那个眼神，罗姆爷说了声「等等等等」并环视房间里的少女们，

「不必急于下结论。老夫方才与佩特拉谈论的，乃是关于头盔小子一伙的……更确切地说，是关于头盔小子其人的危险性」

「关于阿尔的？那个是……」

「嗯。其实──」

面对追问，罗姆爷将原打算稍后说明的内容提前道出，重复了先前的说辞。这番叙述让室内再度充斥沉默——虽与佩特拉带来的沉默性质不同，但沉寂依旧。

「────」

爱蜜莉娅那双宝石般硕大美丽的眼睛瞪得滚圆，雷姆如澄澈湖面般闪亮的眼眸连连眨动。拉姆明显露出狐疑神情，而梅莉一边摆弄着麻花辫一边歪头，

「有点搞不懂你在说什么呀啊」

吐露出与爱蜜莉娅如出一辙的感想。

不巧的是，在场无人能轻易消化罗姆爷方才的报告。

若缺席的柯林特与他正迎接的罗兹瓦尔在场，情形或许不同。但对于权能这种既非魔法、非术技、亦非加护之物的理解，所需的不只是知识更是想象力，实在难以轻易领会。

更何况，对于罗姆爷的结论心里有数的佩特拉就更是如此了。

「让时间倒流，那……」

『──『死亡回归』』

声音微微颤抖的佩特拉，在她身旁半透明的幻影菜月昴如此低语。

只有佩特拉能听见的幻听、只有佩特拉能看见的幻影『昴』抱着胳膊，一脸严肃地接受了罗姆爷的结论。即便是佩特拉，此刻也没有心思为与心上人面对冲击性事实的反应相同而心跳加速。

──罗姆爷得出结论，认为阿尔是拥有『时间溯行』权能的人。

在普雷阿迪斯监视塔击退了加菲尔和艾莎，在奥古利亚沙丘虽说是借用了『神龙』之力却也与莱因哈鲁特打得难分难解，仅凭三人就突破了罗姆爷指挥的菲鲁特阵营五百人，最终从王都躲开了毫不留情、暴怒状态的爱蜜莉娅，带走了『暴食』的罗伊・阿尔法德。

阿尔犯下的那些恶行与大罪，究竟是如何得以实现的，此刻终于将这些点串联了起来。

有可能。──如果阿尔和昴一样，都是『死亡回归』的使用者的话。

『阿尔那家伙和我一样是异世界人。所以，觉醒类似力量的可能性相当充分。说起来，异世界题材的话那种模式不是定番吗。但我居然完全没考虑到，太迟钝了……！』

「那么，果然阿尔先生也和昴一样？」

『啊，可能性很高。不，说不定即使是相似的循环能力，阿尔的也可能是更好用的类型呢。这类情况下，并非完全相同的力量也是定番，品味其差异正是异世界题材的乐趣之一』

「这可是关系到自己的性命，定番还是乐趣都无所谓啦。重要的是我们知道了阿尔先生的一个秘密，以及接下来要怎么做，对吧？」

『嗯对是是这样没错。......不过，很多线索都串联起来了。确实若是如此，从莱因哈鲁特那里逃跑或者设陷阱也……能行吗？能行吗？光靠『死亡回归』能搞定莱因哈鲁特吗？感觉死个一百次都不够吧？』

アルが推定タイムリープの使い手だとわかり、『スバル』がそう头を抱える。その自分を过小评価する『スバル』に、ペトラは内心で激しくムッとする。

的确，莱因哈鲁特很厉害。历代最强且世界最强的『剑圣』这个传闻，就连还是乡下姑娘时的佩特拉也听说过，而加入爱蜜莉娅阵营后，更加详细到像假情报般的信息多得双手手指都数不过来。

极致的是至今仍在奥古利亚沙丘压制着『嫉妒魔女』这一事实。

若无那番狮子奋迅的活跃，世界恐怕早已迎来毁灭，作为彰显其厉害程度的标尺，很难再准备出比这更强的指标了吧。

但是，可是，稍微等一下——佩特拉心想。

莱因哈鲁特确实很厉害，毕竟是『剑圣的加护』的持有者，强得离谱，所以我觉得他能承担与之相称的重大工作并不奇怪。

反倒是对抗超出实力的敌人，为了取得超出预期的成果，不惜榨干已有力量以上的全力去挑战的昴，在厉害程度上绝对更胜一筹，我是这么认为的。

所以说，那个『昴』比起莱因哈鲁特更看轻自己这件事，对佩特拉来说很不甘心，希望他能挺起胸膛说自己更厉害。

话虽如此，但如果因此察觉到昴优点的人增加太多也很困扰。

「嘛～我觉得目前有我和爱蜜莉娅姐姐大人、雷姆姐姐大人，再加上碧翠丝酱和帕特拉修酱，已经是完美阵容了」

就算有人后知后觉地发现了昴的魅力，也已经形成了难以攻破的铜墙铁壁般的包围圈，佩特拉对此颇为自得。

目前令人不安的是过于温柔的昴会过分偏袒对方的展开，但即便如此也依然相信着会将爱蜜莉娅放在第一位的昴。──不过，这对佩特拉来说也是相当烦恼的地方。

总之──

「如果罗姆大人神志正常，而且罗姆大人的眼睛没瞎的话，那可真是麻烦呢」

「虽然对你的说话方式有很多在意的地方，但你能理解真是帮大忙了。正因如此，那头盔混蛋……阿尔德巴兰才能突破我们的包围网。爱蜜莉娅在监狱塔被压制住，恐怕也是因为那家伙的权能吧」

「那个、对不起。我还不太能反应过来……」

拉姆和罗姆爷、特别是聪明的两人似乎要接连推进话题，但爱蜜莉娅在那里叫停了。在爱蜜莉娅身旁，雷姆也可爱地点了点头，

「我也、和爱蜜莉娅大人一样。回溯时间，是吗？姐姐大人，那是什么意思……」

「也对呢 刚醒来状态不佳的雷姆 罗姆大人确实说明不足呢──请看这个」

「那个是……圣金币？」

拉姆快步上前　向爱蜜莉娅和雷姆展示一枚圣金币。

圣金币上刻有那位『神龙』波克肯尼卡的印记，在向爱蜜莉娅她们充分展示这枚圣金币后，拉姆转动她的手，将圣金币当场丢下。

看着它划出坠落地板的轨迹，佩特拉理解了拉姆的意图。利用坠落地板的圣金币来获得时间跳跃的优势──

「危险！真是的，拉姆你也太冒失了吧」

「姐姐大人偶尔会有意想不到的马虎之处。这也是姐姐大人的魅力所在」

但是，在圣金币掉落地面之前，动作迅速的爱蜜莉娅已经将其捡起。爱蜜莉娅将圣金币还给拉姆，雷姆说出了介于安慰与鼓励之间的话语。

收到圣金币的拉姆表情，变得相当耐人寻味。

『啊啦，拉姆是想说只要展示过掉落的方式，因为之前不知道才会掉落，但知道掉落方式的话就能避免掉落之类的吧？』

「大概是这样。不过正好，关于向爱蜜莉娅姐姐大人和雷姆姐姐大人的说明就交给拉姆姐姐大人吧。现在可不是和两人谈话后就能让我满足的状况」

虽然对拉姆很抱歉，但在爱蜜莉娅和雷姆两人赶上之前的讲解就交给她，佩特拉决定先思考接下来的问题——具体来说，就是如何应对阿尔这个让人头疼的问题。

还想要更详细地了解阿尔的权能。即便这样，若能否定刚才『昴』的推测的话──

「——佩特拉酱，真的没问题吗？」

在爱蜜莉娅和雷姆那边由拉姆和罗姆爷费口舌说明的时候，梅莉这样向佩特拉搭话。

梅莉本来应该也是不太理解时间回溯的那一方，但她似乎比起理解阿尔的权能，优先选择了观察佩特拉的情况。

刚才，对罗姆爷发火的时候也是这样──

「梅莉真是的，超级担心我呢。难不成，你最喜欢我了吗？」

「请不要戏弄我嘛。而且，你又不是爱蜜莉娅姐姐，我可不会因为那种态度就被你糊弄过去啦」

「糊弄？」

「从塔里到这儿一路都乒乒乓乓的所以人家就没怎么提啦，佩特拉酱在塔里读过书的事，我可是知道的哦？」

「──。嗯，是呢。谢谢你帮我瞒着爱蜜莉娅姐姐大人她们」

「……只是不想让姐姐们担心，我可以相信的吧？」

「嗯，当然啦」

面露担忧地垂下眉毛的梅莉，握住她的手，佩特拉微笑着点头。对于那双手的触感，梅莉小声低语道：「好温暖啊」。

本想让她安心却可能弄巧成拙了。大概、就像梅莉感受到的那样、现在的佩特拉有点发烧。不过、不是身体不适。就像是知慧热那种东西。

「明明本来就很多事情要想了 现在还得考虑两个人的份」

虽然实际并不存在『昴』这个人　但佩特拉的大脑正在代为追踪他的感情和思考方式。我有自信能相当准确地重现出来。

ただ、思い入れの深さはあるかもだが、スバル一人の『死者の书』を読んだだけのペトラでこの负荷だ。十册以上も読んだというエッゾはどうかしているし、そんなどうかしている人间にしか使いこなせない仕组みの大図书馆を作り上げた、あの塔の设计者と噂されるフリューゲルはもっとどうかしていた。" -> "不过，虽说可能有感情深浅的区别，但仅仅读了昴一个人的《死者之书》，佩特拉就承受了这样的负荷。读了十本以上的艾莎更是有问题，而那个据说设计了塔、建造了只有这种有问题的人才能运用自如的大图书馆的弗琉盖尔，更是问题大发了。

肯定、是那种认为自己做得到的事情别人也一样能做到的类型，无论如何都和佩特拉性格不合，绝对合不来的对象。

但与此同时，佩特拉也明白，如果没有那个不得了的大图书馆，很多事情自己大概会一无所知地度过吧。

然后，在能够知晓的事物中，确实存在着佩特拉所渴望的东西。

只要那能为佩特拉的心中持续点燃火光，我就不想停下脚步。

就算一切结束后　这大脑会沸腾也好

「而且呢 我这么想」

「想……想什么，想什么啊？」

「如果、罗姆爷说的话是真的，阿尔先生的权能和我猜想的一样的话……」

『佩特拉？』

将手指抵在薄唇上，如此低垂眼眸的佩特拉，被梅莉和『昴』窥探着。

互不相识的两人，那困惑的反应如出一辙甚是滑稽，佩特拉一边不合时宜地快要笑出来，一边告知。

那就是──

「──我，可能知道了阿尔先生的弱点」

４

「──也就是说，即便这不是圣金币而是加菲的全力一击，已经看穿加菲行动的爱蜜莉娅大人也能轻松躲开那显而易见的攻击并反击，让他汪汪大哭起来」

「原来如此，是这样啊……但是等等！把加菲尔弄哭也太可怜了。我想用更温和的方式和加菲尔搞好关系呢」

「既然如此，不反击也无妨。只要爱蜜莉娅大人能游刃有余地避开所有攻击，加菲迟早会心态崩溃，这样就能和平收场了」

「那我就放心了……放心？真的吗？可是心态崩溃了耶？」

从雷姆手中接过圣金币的爱蜜莉娅冒出问号歪着头。

此刻她脑内正忙碌地上演着加菲尔像孩子般哭闹或沮丧跪地的画面，但拉姆交接的解说任务总算完成了——阿尔德巴兰的权能『时间溯行』概要已传达完毕，雷姆轻抚胸口松了口气。

「真不愧是呢，雷姆。居然能说服那位爱蜜莉娅大人」

「若是能帮上姐姐大人的忙就好了。虽然让加菲做出了牺牲……」

「只要自己哭哭啼啼消沉一下就能推进事情的话，加菲也该心满意足了吧。听说他正悠哉地睡着，待会儿拉姆会去探望的」

「是啊，呢。加菲若是能得到姐姐大人的探望，想必会欣喜若狂吧……」

对着唉声叹气耸着纤瘦肩膀的拉姆，雷姆的心情有点复杂。

随着记忆复苏想起来了，原本雷姆和加菲尔就因为拉姆而处于对立关系。从小时候起，就讨厌着倾慕拉姆的加菲尔不自量力，是经历过多次争吵的交情。

但是回想起帝国中加菲尔的努力，以及归途中的交流等等，若仍以过去的印象对待他，实在非常过意不去。

更何况如今的加菲尔没能完成守护昴和碧翠丝等人的职责。醒来后他定会极度消沉，责备自己吧。

「对那样的加夫落井下石也太过可怜……明白了。这里就由雷姆来让步吧。因为现在必须让加夫也尽早重新振作起来，成为解救那个人的战力才行」

「是呢。不过，被雷姆的独占欲束缚也不坏哦？如果雷姆不愿意的话，把加夫什么的往后放放也可以哦？」

「所以，不说‘请不要走’这话，姐姐大人是明白的吧」

「谁知道呢」

面对浮现淡淡微笑、凛然回应的拉姆那耀眼的样子，雷姆叹了口气。

在沉睡期间和失去记忆期间，这两个阶段里，究竟让拉姆这番关怀和挂念，白白耗费了多少呢。

当然，雷姆让其担心的对象并不仅仅是拉姆。

也给阵营的全体成员，以及外界的人们添了麻烦。——是该说幸运吗，原本雷姆与非相关人士的交友关系就是零，所以这方面的受害算是比较少。

「倒不如说，我觉得比起失忆之前，失忆期间的我，反而和卡秋娅小姐、米泽尔妲小姐她们更好地进行了交流呢……」

回顾着重新舞动的人生记录，雷姆抱持着这般感想。

虽说在阴差阳错被抛到的佛拉基亚帝国里，为了生存下去而迫不得已，但无依无靠时的雷姆反而更擅长人际关系是怎么回事啊。

挙句、完全不肯敞开心扉的雷姆，却依然数次数次地疏远着试图献身般接近的昴等等，让自己想要掐住自己的脖子。

「至少、如果昴君能正面看着雷姆的眼睛说话的话……啊、可是拒绝这么做的也是雷姆自己、呜呃……」

记忆がなかったのだから仕方がなかった、と自分を拥护したいレムと、それでもちゃんと话せていればスバルの真心が伝わったはずだ、と自分を说得したいレムがいる。" -> "想为自己辩护说没有记忆也是没办法的雷姆，和想说服自己如果当时能好好交谈的话应该就能传达昴的真心意的雷姆，同时存在。

いずれにせよ、スバルを笔头に、レムが周りに盛大な迷惑をかけてしまったのは事実なので、ここから全霊を以て挽回していかなくてはならない。

「首先，要平安无事地解决这个事态。之后为了让昴君看到雷姆的谢意，我会折断自己的手指……就是这样呢」

「……就算那么做了，昴非但不会高兴，说不定还会惊吓到死掉所以请绝对不要这么做哦」

「啊，佩特拉小姐……」

听到她小声决心的雷姆回过头，只见皱着眉头的佩特拉站在那里。虽然心想不该被她听见，雷姆还是对她伸出手掌说道「不」，

「请不要阻止。雷姆、雷姆对昴君感到很抱歉。若不惩罚这份不中用，实在没脸见昴君……」

「那么，雷姆姐姐不是因为想向昴道歉，而是为了让自己好受才要那样受罚的吗？」

「才、才不是！我没有那种打算……」

「就算没那种打算，结果也会变成那样啦。知道吗？昴希望雷姆姐姐做的不是受罚，而是希望你能收回在姐姐睡着期间没能得到的幸福哦」

「────」

眼角温柔垂下的佩特拉，听到这番话雷姆不由得倒吸一口气。

那是因为这番话与那个早晨、阿拉姆村遭受魔兽威胁的事件解决后，昴对自责的雷姆所说的言语有着相似的余韵，是一次温柔而甜蜜的说教。

不知为何，那时的昴与眼前的佩特拉，有那么一瞬间重叠在了一起。

「……这一定正是大家都受到了那个人影响的证明呢」

「嗯？怎么了，雷姆姐姐大人」

「没什么。只是佩特拉小姐的话语让我回想起了一份令人怀念的重要心情。您还记得吗？魔兽袭击阿拉姆村时的事情」

「……呃，嗯，是的。我记得」

面对雷姆的询问，佩特拉的脸颊略微僵硬了一下。随即，她的视线飘忽不定地转向了房间角落里那位名为梅莉的少女。

那似乎是在雷姆沉睡期间加入阵营，在爱蜜莉娅她们于帝国奋战时也在王国尽责的少女。总觉得似乎有点面熟，但为何此刻佩特拉会如此在意她呢？

「咳咳。总之，请雷姆姐姐不要再伤害自己了。要是雷姆姐姐尊贵的白鱼般的手指受伤，世界都会陷入一片黑暗」

「佩特拉小姐……」

「如果您无论如何都不肯停手的话，我也会承担连带责任折断手指的」

「佩特拉小姐!?」

见佩特拉猛地将小手攥成拳头，雷姆的声音不禁变得尖细。见状，佩特拉对雷姆的反应露出恶作剧般的笑容，接着说道「所以」

「不可以做那种事哦」

「──。好……我明白了」

被佩特拉叮嘱后，雷姆怯生生地点头回应。

这固然有被佩特拉的热情所压倒的成分，但更准确地说，是因为从佩特拉身上感受到的昴既视感让她无从反驳。

方才就觉得她与昴重叠的身影，此刻阻止雷姆的方式——用自身的极端去抵消险些急躁行事的雷姆，这点简直如出一辙。

「────」

透过佩特拉深切体会到昴的影响力之大，雷姆陷入了沉默。

某种意义上，现在佩特拉的样子正是她比雷姆更理解昴的证明，就算产生嫉妒心和醋意也不奇怪。但不可思议的是，雷姆对佩特拉连一丝那样的感情都没有。

虽然不明白为什么会这样 但此刻思念着昴的同时 另一根心刺正卡在雷姆心中

那是──

「──阿尔大人的 权能」

正是方才刚用圣金币向爱蜜莉娅说明完毕的『时间逆行』权能

ラム的根気强い说明のおかげでその恐ろしさを理解したレムだったが、エミリアに说明するために自分の中で噛み砕く中、沸々と涌き上がってきたある疑念があった。

最初觉得太荒唐，立刻就想要否定。但是，很快就无法彻底否定了。

观测先未来、通过时间回溯来回避不期望事态的权能──、

「──那个人、也是？」

薄薄地萌芽的怀疑之火，那在雷姆之中眨眼间便壮大起来，凭借蔓延的火势将思考的平原焚烧殆尽。而在如此燃烧残留的余烬中，散布着许多点燃火焰、增强火势的火种。

例如，从昴身上总是飘散着浓密的瘴气香味。

例如，那股瘴气屡屡变得更加浓重，甚至仿佛要将昴包裹起来。

例如，昴以无法解释的洞察力察觉事态，并推导出解决方法。

例如，多亏了昴的存在，许多死亡得以避免，雷姆也是其中之一。

这些一个个单独看来只像是吹毛求疵或找茬的因素，仅以名为权能的这一唯一违规为核心，便惊人地严丝合缝。

但是，万一、万一雷姆的这种直觉是真的，那么名为菜月・昴的少年，尽管拥有着无与伦比的力量──

「却只为了某个人而使用它。……真是多么吃亏的人啊」

倘若任何时候都能重来、能够按照自己的意愿随意修正的话，那就能尽情任性妄为，甚至随心所欲地重塑世界了吧。

实际上，阿尔正是使用那份力量，即使与全世界为敌，也仍继续前行以实现自己的目标。那份力量、那种可能性，就存在于该权能之中。

但昴并没有那样做，也没有那样使用。──这一点，最为清楚的正是未能随昴心意行事的代表者雷姆。

倘若昴是为了按照自己的意愿操控他人内心而使用力量的话，那么雷姆折断昴手指那样的事根本就不会发生。

换言之，手指被折断这一事实本身，正是昴诚实的证明。

「果然，雷姆也想折断手指和昴君凑成一对……！」

「刚才不是让你放弃了一次吗!?」

「不是的，佩特拉小姐。这次并非出于无颜面对的消极理由，而是想与昴君分担相同痛楚的积极……」

「不管积极消极向上向下全都——不——行——哦！」

对方根本没有听进去，雷姆的干劲就这样不了了之。

总之，暂且不论屈指可数的那件事，在雷姆心中「昴与阿尔德巴兰是同类型权能持有者」的推测越发确信。只是，即使听了『时间溯行』的话题，拉姆和爱蜜莉娅她们似乎也没有产生和雷姆同样的想法。

那不是因为雷姆更加深入、更加理解昴的事情——并非如此。

「……不如说，恰恰相反呢」

与雷姆不同，爱蜜莉娅他们没有产生这种想法的理由，在于除了沉睡的雷姆之外，大家在迄今为止的日子里都见证了昴努力的身影。

听你这么说，昴在雷姆持续沉睡的一年多期间，与碧翠丝签订了契约，并且为了成为配得上爱蜜莉娅的骑士而不断努力着。正因为知道昴的努力，所以才不会怀疑他带来的成果中会有其他因素。

那份努力，虽然懊悔到心都要被撕碎般，但雷姆并不知道。──因此，对昴能做之事的认识与周围存在着巨大隔阂。

但是，这丝毫不会减弱昴的英雄气概。

比起任何事情 这个状况证明了即便昴拥有权能也并非万能。昴至今为止绞尽智慧与勇气 持续为他人竭尽全力的事实不会动摇。

即使是在此刻 雷姆依然能够帮助昴的力量 依然好好地保留着。

「既然明白了……姐姐大人！」

被囚禁的昴正在求救。──当雷姆在自己的思考中得出这个确信时，她急忙想将这个想法与拉姆等人共享，以增加商讨的材料。

这是基于直觉部分和感知瘴气的鬼族嗅觉为前提的说法，虽然很难让人信服，但若是聪慧的拉姆和心胸宽广的爱蜜莉娅的话，应该会认真听我说的。

这么想着，雷姆正要对转身的拉姆她们说出「怎么了？」──，

「──我现在回来了。来晚了」

就在那一瞬间。

雷姆们聚集的王侯馆大厅里，如同眨眼般现出两位男子。一位是戴着单边眼镜、印象精明的美男子，柯林特。而柯林特带来的，是对雷姆而言也相识已久有大恩的主人──

「罗兹瓦尔！　你来了呢」

「诶ーー，情况已经从柯林特那里听说了。听闻昴君和碧翠丝的困境，再加上王选根基可能动摇的事态，就算我说自己帝国之旅的疲惫也……可ーー不能这么说呢ーー」

「嗯，非ーー常可靠呢。马上就去参加大家的讨论……不过，在此之前」

「──？」

迎接登场人物──罗兹瓦尔的爱蜜莉娅用手示意了他的背后。对于这个动作转过身去的罗兹瓦尔，那双左右异色的瞳孔捕捉到站在那里的雷姆，对上了焦点。

与之相应，雷姆用手指捏住裙摆恭敬地行了一礼，

「罗兹瓦尔大人，承蒙您赐予了相当长的休假。无论是前往帝国迎接一事，都容我再次向您致谢。──雷姆，回来报到了」

「────」

对于雷姆的那番谢意与归来的问候，罗兹瓦尔的喉咙轻微地响了一声。刚这么想，下一秒他那高挑的身躯就猛地一晃，像是头晕般踉跄了一下。

「罗兹瓦尔大人！」

「啊，不，没事没事。……只是事情来得突然，差点被信息淹没了ーー而已」

一旁的拉姆立刻撑住他的身体，罗兹瓦尔苦笑着这样回答道。

大概是因为有人喊出了雷姆的『名字』，使得『记忆』开始回溯了吧。

虽然遗憾的是这份记忆并非源自与热心擦拭铁球──晨星的昴之间的羁绊之力，但目睹原本空白的归属之地逐渐被填满的感觉并不坏。尽管或许会被指责为不谨慎。

无论如何──

「──欢迎回来，雷姆。等局面稳定后，务必讲讲你不在时宅邸的……尤其是拉姆的故事吧」

「好的。我衷心期待着」

罗兹瓦尔以惊人的理解力迅速消化了突然回忆起重获雷姆的冲击。雷姆一边由衷钦佩主人坚韧的精神力，一边准备重新主导谈话节奏。

但此时雷姆的袖口被人从后面轻轻拽住──

「老爷，法兰黛莉卡姐姐没有一同回来吗？」

「啊，我让法兰黛莉卡留在跋利耶尔领地了。既然接下了职责，按柯林特的说法──既不忍心抛下修尔特君，也该由本人来完成法兰黛莉卡被寄予的使命呐」

「柯林特哥哥要代替法兰黛莉卡姐姐的职责？……这怎么可能呢？」

「真是严厉啊。为了打消你的疑虑，我也必须努力才行呢。加油」

佩特拉确认了未与罗兹瓦尔一行人同返的法兰黛莉卡的去向，如此蹙眉说道，而柯林特则以坦然的态度立誓要奋发努力。

就在这番交谈之际，雷姆望着拉住自己袖口的佩特拉侧脸，不禁疑惑地歪头问道：「佩特拉小姐？」

此刻，佩特拉明显打断了雷姆的话语，转而提起了别的话题。当然，法兰黛莉卡的去向也是令人关心的话题，但此举意味深长。

在雷姆如此心生疑惑的另一边，爱蜜莉娅正向罗兹瓦尔介绍罗姆爷，并开始谈及需要跨越阵营界限采取对策之事。佩特拉望着这一幕，忽地转向雷姆，轻轻招手示意。

然后──

「……莫非，雷姆姐姐也察觉到了昴的异常？」

「──！听你这话，佩特拉小姐也注意到了昴的权能……」

「再多说可就危险了。……说不定会被『魔女』听到哦」

「────」

将自己的手指竖在唇前，如此宣告的佩特拉让雷姆也不由得闭上了嘴。

虽然没有明说，但刚才的口吻却精准地说中了雷姆的内心。也就是说，这也证明了佩特拉同样认为昴是拥有『时间回溯』权能的人。而且，从她的态度来看，可以知道她比雷姆掌握着更多的信息。

『魔女』像在质问，这种表达或许有些突兀——

「既然听说莱因哈鲁特大人正在奥古利亚沙丘抵御『嫉妬魔女』，这种说法就称不上夸张了呢」

「嗯，也跟那件事有关。虽然不敢百分百确定，但总觉得这事还是不说为妙。——毕竟，我再也不想体会那种感受了」

切切实实、蕴含着近乎可怕的真实感的佩特拉的轻语，简直就像是实际知晓了说出那句禁忌话语时的伤害一般，带着沉甸甸的分量。面对佩特拉的这般模样，雷姆也将那刚要编织出口的话语，自然地咽回了喉咙深处。

但若是那样，将昴至今为止的真正功绩向大家公开的机会就──

「……那种事、那个人是不会在意的对吧」

在失去记忆前和失去记忆后、雷姆获得了两次了解昴的机会。

通过这两次机会所明白的是、昴那令人心头一震的坚强诚挚。对他而言、自己被毫无保留地评价、所有一切都变得清晰可见这种事都是次要的。

昴的行为与思念，其一切为人所知，希望他能受到所有人的称赞、获得回报，这终究只是雷姆的价值观、雷姆的愿望而已。

「──雷姆姐姐，请让我问一个问题」

将自己的祈祷吞下肚，佩特拉对着还残留着那份感伤余韵的雷姆说道。

虽然并非特别小的声音，但雷姆认为那是她不愿让周围听见、蕴含着想仅在自己与佩特拉之间交流意图的一声。

正因为如此，昴在谈论非常重要的事情时，也曾用这样的眼神和声音开口。

「雷姆姐姐，只要是帮助昴的事情，什么都愿意做吗？」

再次感受到与昴相似的佩特拉的质问。在那背后，雷姆察觉到她怀揣着「自己能行」的强烈决心。

并非对那份心境抱有对抗意识。但是，连一秒钟都不需要。

「嗯，当然啦。──因为，我是昴君的雷姆呀」

如此回应，对雷姆而言是无需丝毫犹豫的事。

５

──每分每秒，阿尔德巴兰都切实感受到不断堆积的身心消耗。

「食物就地筹措，水可以舔舐冷却空气制成的冰……但睡眠时间被削减是真的够呛」

持续不断的顽固妨害工作，就这样长久折磨着阿尔德巴兰一伙。

令人讨厌的是，大部分损害并非以造成我方受伤为目的，尽是些强制消耗的手段，比如污染食物和水、野营时遭虫群袭击、妨碍睡眠等。

而有时又会扔来像最初采石场布置的那种落石级别的大规模陷阱，其恶劣程度尤为突出，绝不容许丝毫松懈。

目前最大的问题是没有完全阻止这种干扰的手段。

「武斗派内政官……武斗派内政官呢。看来这粗暴的称号不是白叫的」

爱蜜莉娅阵营的内政官奥托・苏文是个时常能见到的温和美男子。

阵营中被戏弄的角色兼缓冲材料、虽然希望其常驻于日常岗位，但在枪林弹雨中始终恪守支援本分的幕后功臣──这种认知可是大错特错。

阿尔德巴兰过于轻视了"能与任何生物对话"这一事实。此刻正以难以置信的速度与数量为此付出代价。

「问题不只有阴湿内政官……还有大叔和菲鲁特的事情」

除了妨碍工作之外，更让阿尔德巴兰头疼的是同行成员内部产生的不和，以及不容忽视的问题苗头。

原本菲鲁特并不在阿尔德巴兰的预定成员之列，但如今因『阿尔德巴兰』相关事宜不得不带着她行动的存在，在此造成了巨大困扰。

这正是菲鲁特触及亨克尔情绪逆鳞的问题所在。

亲生儿子莱因哈鲁特将『嫉妒魔女』困在奥古利亚沙丘之际，作为障碍挡在面前的生父威尔海姆被亨克尔亲手刺伤。而菲鲁特险些因触及他濒临极限的精神状态而付出生命代价。

「……不过说真的，差点没命的情况其实发生过好几次吧？」

事实上，若非阿尔德巴兰用『领域』重置事态，最坏的结局根本无法避免。

原本强行用『神龙』意识覆盖阿尔德巴兰就已处于极不稳定的状态。若是再出现严重刺激『龙』本能的因素，『死者之书』的魔法很可能失效。

亨克尔刺伤菲鲁特正是如此——暴怒的『阿尔德巴兰』险些让团伙在失控中遭遇毁灭性崩溃，但这一切被强行抹消了。

阿尔德巴兰将时间倒回冲突发生前，粗暴地打断了亨克尔与菲鲁特的对话。

「可是这也只是权宜之计罢了。要是不小心让大叔和菲鲁特酱独处的话，明显又会闹出流血事件。但话说回来，除了八重以外没人能管住罗伊那混蛋……靠，这又不是什么狼和山羊过河的脑筋急转弯。而且我最不擅长那种玩意了」

虽说这算是所谓的逻辑谜题，但现状确实很接近那种情况。

被迫把脑力浪费在本不该存在的智力较量上，感觉非常糟糕。可即便如此，狼和山羊——

「——亨克尔大人也好菲鲁特大人也好，随便舍弃一方不就轻松多了吗？」

「——。我都说了不会那么干的啊」

突然被打断沉思的轻快声音让阿尔德巴兰咂舌回应。

双手背在身后蹦蹦跳跳走来的正是八重。看到她独自一人，头盔下的阿尔德巴兰眯起了眼睛。

「喂，怎么只有你一个。至少该有个人陪着……」

「耐打的菲鲁特大人和波克大人待在一起，烦人的大罪司教被吊起来了，难看的亨克尔大人也被捆好了。总之现在暂时是安定下来了啦」

「……就算那样，也不能保证没有漏洞吧」

「是的呢。但是但是，现在最可能出现大漏洞的地方是阿尔大人那里哦～？」

一边说着，八重蹲到抱膝而坐的阿尔德巴兰面前。被她猫一般的红瞳窥视着，阿尔德巴兰感到了不自在。

无论回答得多么生硬，她的判断都是正确的。——毫无疑问，成员中消耗最严重的非阿尔德巴兰莫属。

「但是，那是理所当然的吧。我想要达成的目标最大最多。那么，我来承担辛苦是应当的……」

「可如果结果是阿尔大人中途垮掉的话，岂不是惨不忍睹吗？」

「……你想说什么」

「所～以～说～啦，八重酱想说的话就如我一直传达的那样。在阿尔大人啪嚓一声被压扁之前，还是降低胜利条件吧」

「所以说那个是……」

「──凭什么、阿尔大人就非得拘泥于干净的手段呢？」

八重撑着叠起的膝盖托腮，尖锐地插话进来。

察觉到八重细如丝线的双眼微微睁开、声线中的玩味已然消失，阿尔德巴兰霎时语塞。

趁著阿尔德巴兰的沉默，八重继续道。

「对方可是不择手段哦。当然啦～毕竟对方被阿尔大人夺走了盟友、遭受创伤，甚至连世界命运都悬于一线。那当然会拼死反抗嘛～什么光明正大正面交锋、违背正道的手段都无所顾忌」

「……我明白让你受委屈了。不止是接连不断的骚扰，在王都还害你遭遇了『剑鬼』」

「不对。我不是想抱怨……不过嘛～要说这是抱怨倒也没错呢～」

「你说什──」

后半句「么意思」未能说出口。

不意间、没能躲开径直伸来的八重的手，阿尔德巴兰被按住额头，就那样向后翻倒。而在睁大眼睛的阿尔德巴兰上方，推倒了这边的八重滑溜溜地覆盖了上来。

「────」

在极近的距离，阿尔德巴兰与八重的视线交错。

她在想什么，看不透的玻璃珠般的红瞳。不管那在想什么，都无所谓。若是不知悔改还敢反抗，就从她那里夺走这机会。

瞬间，阿尔德巴兰立即用舌尖抵住后槽牙埋入的药囊，试图通过自杀来重来这一刹那──

「──夫人已经过世了哦，阿尔大人」

「──呃」

「已经去世了。您自己不也多次说过吗」

在即将饮下毒药的瞬间，被近在咫尺的八重如此告知，阿尔德巴兰的喉咙发出声响。

无需多言。普莉希拉・跋利耶尔已死。这是一切的前提。是阿尔德巴兰下定决心的理由、起因、以及最后的枷锁。

因为她消失了，阿尔德巴兰便解开了束缚自己的一切枷锁，即使明知道会将所有存在都变为敌人、令世界陷入混沌，也开始了这一切。

「真的吗？」

「啊……？」

「真的、是这样吗？夫人哪里都不在。所以已经怎样都无所谓了。背叛谁也好，毁掉什么也罢，不管被人怎么想都完全没关系。──真的吗？」

面对接连不断的追问，阿尔德巴兰动弹不得。

至今仍能靠舌尖的轻微动作将这一刻化为乌有。以此为保险——不，即便没有这份保险，阿尔德巴兰或许也不会行动。

毕竟，八重的言语与眼神中蕴含着比钢线更坚韧的束缚力。

「────」

「真的吗？」她追问道。究竟在寻求怎样的答案呢？

真的吗，她如此问道。的确是真的。除此之外我还能说什么呢。

真的吗，她如此问道。她在质问阿尔德巴兰的决心是否正确。

「结果或许有些糟糕。造成的损害也可能超乎想象。但我也这样想。──行事手法，真是非常非常漂亮呢」

「绮丽……？」 -> 「漂亮……？」

「从正面相对 用策略超越并克服 不足的战况就利用对方弱点但不会造成人员伤亡。阿尔大人的觉悟很纯粹。所以才会像这样 陷入如此如此狼狈的境地」

「────」

「──阿尔大人 请别再继续渴慕太阳了？」

阿尔德巴兰的头盔被光滑伸来的八重双手从两侧夹住。那并非试图脱下头盔的手势，而是不让他避开视线的手势。

那手势与被低语的话语束缚了阿尔德巴兰的灵魂，封住了他的行动。

「────」

──别再，渴望着，太阳了。

「在地面匍匐爬行沾满泥泞，停止仰望天空来沐浴鲜血吧。没关系的。反正我已经是污秽之身，无论是泥泞还是鲜血，都不介意一起沾染」

「──。不管你、要说些什么，我」

「不必连无法退让的东西也退让。但若您如此期望 就请不要勉强维持体面。若是连那份体面都能舍弃的话——」

话语在此中断　八重的唇角弯出舒缓的半月形。

那抹在血色中晕开的八重微笑，显得无比虚幻，与某个人的微笑重叠在了一起。

「──没有人，能胜过我的阿尔大人」

──那是构成了阿尔德巴兰的、铭刻在灵魂深处的某个人的微笑。

「────」

面对着浮现血色微笑、近在咫尺地如依附般、如怜爱般、如哀叹般如倾诉般如渗染般如渴望般宣告的八重，阿尔德巴兰长长地吐出一口气。

然后──，

「──领域展开，矩阵再定义」

为了不放弃真正难以放手的事物，哪怕浑身沾满鲜血与泥泞，他也如此想道。

６

「──呜……」

被一阵格外强烈的头痛刺痛大脑，奥托微微漏出一声呻吟。

他持续开启着平时并非一直开放的通道，已经将『言灵加护』维持了二十小时以上。为了不错过任何一条传入的信息，这真是字面意义上不眠不休的战斗。

「……爱蜜莉娅大人，似乎已经与边境伯爵们会合了呢」

虽然无法与派去追踪阿尔德巴兰他们的数量相提并论，但为了掌握己方的动向，奥托也在王都的爱蜜莉娅她们那边放了虫子。话虽如此，目前并不打算主动与同伴取得联系。

眼下奥托的作战是以加护为前提的，并不需要人手。不如说，不被扰乱集中力才更重要──而且很明显会被同伴阻拦。

因为无论怎么想，一旦爱蜜莉娅她们知道奥托已经流了超过一杯量的鼻血，肯定不会允许他继续这个作战。

「但是，这是必要之举哦」

一边用手帕按住滴落的鼻血，奥托低声自语道。

不久之后，阿尔德巴兰他们就会抵达卡拉拉基都市国家的摩格阿雷德大喷口，并在那里达成某个目的吧。那里恐怕就是极限了。

虽然终究只是奥托的直觉，但他能确信，一旦对方达成目标就是己方的败北条件，那也是夺回菜月・昴和碧翠丝的最后机会。

因此，必须阻止他们。但是，奥托自己并没有决定性的手段。

能给出决定性一击的　永远都是奥托之外的某人。

奥托・苏文能做的，只有为某人进行援护射击。──所以，哪怕是挤干全身鲜血，也要为这次援护射击倾注全力。

『──少爷，请您不要死啊』

「……您不说‘别乱来’呢」

『少爷您乱来不就是跟兴趣爱好差不多嘛。我都不会说让您停下明明说了也停不下来的事。所以，请您千万别死掉啊』

对着这样摆出一副理解者模样摇晃身体的爱龙福尔夫，奥托露出了苦笑。

基本上、奥托虽然与阵营全员分头行动、但为了确保移动手段和紧急情况时的谈话对象──为了防止因『言灵加护』过度沉溺于其他生物的思考而无法回归、他只与作为生命线的福尔夫共同行动。

真不愧是自幼相识的福尔夫，奥托的想法和行动似乎都被他看透了，这份可靠着实帮了大忙。

尤其是在这样远离人烟的山中行动时。

『不过话说回来，您这鼻血还真是哗啦哗啦流得够酣畅淋漓啊』

「并不是我想让血流出来才流的。我自己也没想到居然能持续使用加护这么长时间」

『加护用多了也会成长吗？嘛~少爷说不定意外地血气方刚，稍微出点鼻血反而可能更好呢』

「就算是安慰，能听到您这么说我也得救了」

还在被昴他们抓住之前、两人单独行商的时候、经常以这样的方式在山和森林里福尔夫地互相开着玩笑过日子。一边进行着与那时相似的交谈、一边想着已经走到相当远的地方了呢、这样想着。

理由全都、在奥托身上。福尔夫只是、跟过来了而已。

「哈啊……」

『哎呀，好大的叹气声。要是累了的话，稍微睡一会儿如何？刚才不是说对方也在休息中……现在的话不用担心跟丢，不是正好能休息吗？』

「说什么呢。正因为是休息时间才不能打扰。不如说现在正是大好时机哦」

『把这种状况当成大好时机，少爷您的坏习惯可真是一点没改呢』

呆掉的风中晃动着粗脖子的福尔夫，那悠闲的语调与态度，考虑到现状本该觉得太过从容，但若明白这是为了不让奥托焦躁而刻意表现的轻松，也就不会生气了。

实际上，和福尔夫交谈期间，奥托的精力正逐渐恢复。——托他的福，似乎还能再坚持一阵子。

『我倒不是怀着那种打算和少爷说话的呀』

「就算没那个打算也帮到我了。我的福尔夫是最棒的搭档」

『少爷真是的，净会说好听话！』

对着不满低声嘟囔的福尔夫露出笑容，随后奥托做了个深呼吸。

重新将意识聚焦到频道上，再度向追踪阿尔德巴兰他们的鸟、虫、鱼群发出指令，试图尽可能捕捉对方的动向。

这种大范围的索敌与谍报性能，正是奥托・苏文的真正本领。

无论、奥托的这种做法既非强制也非洗脑，因此与提供协助的生物充分协商并达成共识至关重要。不过，相互磨合条件、明确交易所需物品的步骤，对商人而言是理所当然的流程。

基本以食物和调停天敌关系等代价为条件，换取对方协助进行妨碍工作。借此获取目标的位置情报，并对其水源、食物和睡床进行骚扰。

「只不过，对方可是有『神龙』坐镇呢……」

就连奥托也从未想过，自己竟会有将『神龙』的存在视为妨碍工作障碍而感到棘手的一天。理所当然地，生物总是会畏惧更强大的生物。因此无论奥托多么热切地请求，大多数生物都不愿接近『神龙』。

但是，牠们──唯独索达虫，却是例外。

相比个体更重视群体生存与未来的它们，是连『神龙』都毫不畏惧地接近、并带回情报的高手。奥托能至今未跟丢阿尔德巴兰一伙、且不放松干扰工作的手脚，也绝对是多亏了索达虫。

「这件事办完之后，我答应过会给他们安排能安稳生活的土地，但老实说，光这样恐怕还不足以表达感谢之情呢」

『……要是太偏袒索达虫的话，法兰黛莉卡大小姐和佩特拉大小姐她们的脸色会越来越难看哦』

「我知道为什么女性大多讨厌索达虫。但是，如果了解到这次的功绩，说不定看法会改变哦」

虽说如此，奥托也明白那希望渺茫。

别说女性阵营了，就连加菲尔也对索达虫有抵抗感──因为和奥托在『圣域』的战斗，似乎留下了心理阴影。昴和碧翠丝也是，等到顺利解放之后，听到索达虫的贡献时会露出怎样的表情呢。

「至少，应该让我亲自向虫群代表表达感谢──」

「──不过，我觉得那个有点难度哦～？」

「────」

瞬间，奥托的耳边掠过既非虫鸣亦非小动物、甚至连福尔夫都不是的声音。正当他倒吸一口凉气时，奥托的身体猛然悬空而起。

『少爷!!』

失去龙车后，原本直接跨在背上的奥托体重骤然消失，察觉异常的福尔夫发出拼命的喊声。

福尔夫的惨叫徒劳地消散在空中，奥托被悬吊在山中一棵枯瘦的树木上，脖颈与手腕被纤细的触感缠绕绞紧，只能在半空中胡乱蹬动着双腿。

尽管他勉强将手指卡在颈间避免了即刻窒息——

「咯……呃……！」

「哇。明明不像战斗人员却能有如此迅速的反应真是厉害。这就是所谓的常备不懈的心态吧？大哥，说不定你在忍术方面也大有成就了呢？虽然我觉得还比不上被称作天才的我啦」

吊在半空、晃晃悠悠摇摆的奥托，其脚下浮现出一道纤细的身影。那是一位红发、身着带有华族元素的侍者制服的少女──特征，完全一致。

乃是阿尔德巴兰一伙的成员之一，亦是奥托必须铲除的敌人──、

「您看，我不是说过了嘛，阿尔大人。──我都说了，没人是您的对手哟」

──红之忍术，八重・天膳如此染红脸颊，仰望着被吊起的奥托。

７

「──阿尔大人，请停止对太阳的焦渴吧？」

说出那句话时，她究竟怀抱着怎样的心情，无人知晓。

自己是以恐惧驱使她服从、用憎恨束缚她、将复仇心作为担保来利用的立场。从那样的她看来，被逼入绝境的我的模样想必是让她十分痛快吧。

只是，话虽如此，实际上确实有许多细微之处反应对不上的情况也是事实。

那么、她矛盾态度背后隐藏的真正意图到底是什么。

寻求那个答案的事、我放弃了。──可以确定的事情、只有一件。

「──领域展开，矩阵再定义」

那个八重・天膳的建议、摘除了阿尔德巴兰心中的一道枷锁。

虽非刻意施加　但潜意识中设下的枷锁、限制、门槛──大致是抑制阿尔德巴兰权能绝对性的精神锁链

随着它的解除　阿尔德巴兰的选择将拓展出无限的广度──

「瞄准 十二时至三时方位。──开火 阿尔塔」

『明白 起源』

指示に淀みなく応じて、すぐ背后に控える『アルデバラン』が翼を広げる。

对于被称为奥尔特这件事，我并没有感到困惑。通过《死者之书》，我已经完成了自身意图的更新与共享。至于被称作起源这种事，更是微不足道的小事。

根本无需对此发表见解，白光——龙之吐息已然释放。

「────」

『神龙』的龙壳、将其性能最大限度发挥出的吐息威力惊人，即便是那位『剑圣』莱因哈鲁特・范・阿斯特雷亚，也仅能勉强抵消。

那是在『剑圣』缺席的战场上──不，是朝着连战场都算不上的区域横扫而出的攻击，将那里存在的自然、人造物，尤其是不仅动植物、连包含人类在内的生命，全都抹消殆尽。

认真的『龙』之吐息射程可达数公里 被毫无预兆降临的毁灭之光吞噬时 任何人连感受疼痛的闲暇都没有便会消散。

──而现在 阿尔德巴兰对『阿尔德巴兰』下达指令 实施了那一击。

「────」

正如指示的那样，从十二点到三点──将方位对应到钟表位置的时钟定位法，将指定区域烧毁殆尽，将其路径上的一切都化为乌有。

恐怕，失去的生命岂止数百数千，不下数万吧。

「哈哈哈～搞什么玩意儿！」

那个、目睹了将所有事物都用力量强行压制的蹂躏之后、被吊起来的罗伊・阿尔法德发自内心愉快地嗤笑。手臂被绑住吊起来的罗伊、将自由的脚底板合在一起、不用拍手而用拍脚来起哄。

但是，光是嚷嚷起哄的只有罗伊一个人，在场的成员中并没有人会对阿尔德巴兰的行为加以指责。

有的只是愉悦、理解、顺从、畏惧──无论哪种，都是包含了不可抗力的共犯者们。见证了这场行为之后，阿尔德巴兰他们或许才真正意义上成为了共犯。

然后，在他们的视线注视下，阿尔德巴兰仰望着天空。

「────」

龙之吐息释放而出，不仅大地被烧尽，其影响还波及天空与大气。

云彩被吹散，本该降临的风雨被驱散的那片土地上，深深烙印着龙的痕迹。可谓是龙愤怒的爪痕。

当然啦，没有生物不畏惧压倒性存在——『龙』的怒火。

既然不存在能够抵抗狂怒暴走的『龙』的存在，那么所有生命在『龙』的暴脾气面前都得低头，拼命隐藏自身，等待风暴过去就是铁则。

──因此，那些早早靠近那愤怒爪痕的鸟虫之类，简直不自然到了极点。

「猜错了啊」

目睹被吐息焚毁的区域上空聚集起确认灾情的鸟群，阿尔德巴兰在口腔内泄出一缕即将消散的低语。

多数动物都很单纯，忠于本能。倘若出现扭曲本能的不诚实行为，便证明有某种非自然因素在干涉。

换言之，这正是施行那种非自然干涉的存在仍存活的证据。

确认这点后，阿尔德巴兰──

「──下一个」

在低语的口中解开毒药包，呷入猛毒。

然后──

×　×　×

「瞄准，三点钟方向至六点钟方向。──动手吧，奥尔塔」

接着，在返回的起始点向『龙』下达指令，要求蹂躏下一个区域。

８

「瞄准，六点钟方向至九点钟方向。──动手吧，奥尔塔」

「瞄准，六点钟方向至八点钟方向。微调」

「瞄准，六点钟方向至七点钟方向」

「瞄准，固定七点钟方向。调整射程，吐息输出八成」

「七成」

「六成」

「六成五分」

「六成五分五厘」

「──六成五分五厘」

「确定──」

９

──七百一十四。

被八重称赞手法干净利落后，阿尔德巴兰改变了想法。

意识到自己不自觉的傲慢，认真斟酌达成真正目标所需之物，并得出了答案。

──不杀生的束缚。

这是自阿尔德巴兰决意排除菜月・昴，决心遵循自身造物目的那一刻起，便规定必须遵守的最低底线。

他下定决心，在这个已然失去太多、连太阳般存在的她也已消失的世界里，绝不再让任何事物继续逝去。

然而，因过分执着于此誓约，阿尔德巴兰不自觉地为自身权能戴上了枷锁。

为遵守不夺任何人性命的誓言，他连通往目标的征途也设下了同等约束。

若凭借阿尔德巴兰的『领域』之力，在反复重演的世界中所发生的事象，皆可直至其矩阵画上终止符前彻底抹消。──既然如此，只要最终符合『不杀』的平衡，过程里的死亡便无需踌躇。

将这一结论置于意识之外，正是阿尔德巴兰无意中给自己戴上的枷锁。为了挣脱这个枷锁，阿尔德巴兰白白耗费了大量时间。──不，如果没有八重那番话，或许至今他仍未能察觉。

「咱早就知道老哥会用加护来削弱咱们。问题在于老哥的周密布局和无穷无尽的手段，咱们根本找不到防备的办法……」

卸下枷锁的阿尔德巴兰，用蛮力强行突破了这道难题。

说白了其实并不复杂。追兵借助虫鱼鸟兽的视野和行动力，掌握了阿尔德巴兰他们的动向，并展开了多方面的妨碍行动。

但根据对敌人加护效果的推测，对动物的指挥既非心灵感应般的交流，也非洗脑般的绝对控制。应该都是加护者亲自与对象对话，每次口头下达指令。

并且要执行这点，指挥追兵的本人也必须持续追踪阿尔德巴兰他们。──通过龙之吐息强行推断出了那个追兵的位置。

「用时钟方位缩小区域，靠吐息的深度测算距离。要是咱这边干出离谱事儿，对方就不得不亮出手牌来确认状况。肯亮手牌就说明老哥平安无事。但要是对方不肯亮牌呢？」

手牌──意味着连动用通过加护安插在敌方的棋子都来不及，便已从这个世上消失的证据。

确认这点后，阿尔德巴兰回归『领域』。锁定追兵所在方位，测算距离将对方位置精确到极限。当然这过程中山脉森林乃至城镇都遭到波及，出现了大量牺牲者──但这一切都被重置归零了。

通过『领域』进行最终账目清算后，除阿尔德巴兰外的牺牲者为零。──不，既然阿尔德巴拉的『死』不被计入，牺牲者就是零。

「加上塔选成员那次，一共一千三百四十七次……可真让老子费了不少劲啊」

被本以为已经排除掉的对手摆了一道，没有比这更耗损身心的了。

从这个意义上来说，追兵──奥托・苏文给阿尔德巴兰带来的困扰，甚至超过了『剑圣』和『剑鬼』，这么说也毫不夸张。实际上，若在王都指派阿尔德巴兰去对付爱蜜莉娅、派八重去对付威尔海姆都是他的指使，那他们所受的损害可就远不止阿尔德巴兰的一千三百四十七次『死亡』了。

当然，正是因为判断出对方有如此威胁，阿尔德巴兰才不择手段，将这个强敌名副其实地吊了起来。

「阿尔大人，这边这边啦～」

八重轻快地挥着手，在下方招呼着阿尔德巴兰他们。听从八重的呼唤，『阿尔德巴兰』降落到地面，他从其背上跳了下来。

在山腰处，先一步到达目标点的八重身后，是被吊在树上的恶魔内政官，以及被绑住手脚倒在一旁的地龙。地龙似乎对钢丝的束缚进行了相当激烈的抵抗，淡青色的龙皮上渗出了血，身体仍在痛苦地扭动。

那并非是为了逃避疼痛，更像是出于对被吊起来的主人的担忧而做出的动作。

「不愧是地龙，这份忠诚心真了不起。回想起来，现在这代的帕特拉修也是那种感觉呢」

「虽然也曾闪过杀一儆百的念头，但感觉这家伙更像是越打压越顽固的类型，所以就作罢了。八重酱觉得如何？」

「俺也觉得这样处理正确。再说了，杀鸡儆猴也得让人看见才有效果吧」

看着悄然来到身旁并排站立的八重，阿尔德巴兰在头盔下撇了撇嘴。

在阿尔德巴兰的视野中，被吊起的内政官──奥托的双眼和嘴自不必说，从脖颈到脚尖全被钢线层层缠绕，完全动弹不得。

原本单根钢线需要凝神细看才能确认其存在。如今既然清晰可见如同拘束具，真不知究竟缠了多少层。

「光线进不去，声音传不出。莫说低语，连呼吸都可能成为与外界沟通的途径。因此我将全身毫无缝隙地捆绑，只留脚踝处一道空气通道。这样他光是呼吸就已竭尽全力，再无余力传达意志了」

「……我明白这不是你的泄愤，而是警惕的证明。毕竟实际来说，要是给那个大哥开口的机会，真不知道他会干出什么事来」

「我才不会因为私怨行动呢～。八重酱可不是那么坏的忍术哦？」

竖起手指抵着脸颊，露出可爱笑容的八重心情相当好。

毕竟至今为止一直被迫尝尽专精于骚扰的奥托带来的辛酸，虽说没有私怨，但积攒的怨气恐怕相当深厚。本来嘛，对敌人进行骚扰和消耗战，正是忍术的独门绝技。

「既然终于能压制住那股劲儿，会心情好也是当然的吧」

「呜～阿尔大人真是完全不懂女人心。那个阴险彻底执拗性格最差的纠缠型对手被制服，当然会觉得很痛快呀？」

「这说得比我还过分吧」

「不过最棒的还是阿尔大人好好展现了怪物本色。没有拘泥于渺小的人性之类的东西，彻底贯彻了怪物的身份」

「────」

「为了达成目标，就算被波克大人用尽全力扔出去也没什么大不了的」

「你其实对作战计划相当不满吧……」

八重纠正阿尔德巴兰的误解后，最后又补充了这么一句。

不杀的意识改革，以及追兵位置的确定。即便完成了这两点，若让对方察觉意图就毫无意义了。为此，需要最快抵达敌人所在的手段——即由飞行的『阿尔德巴兰』将八重投掷至目标位置。

这方法既粗暴又将八重的性命置于极大危险中，但鉴于目标位于缓冲物较多的山区，能用钢丝术制造缓冲垫的八重被认为是最合适的人选。

「这项任务可不能说因为大叔怎么被扔都不会死，就交给现在的亨克尔大人呢」

「就算山上开个大叔型窟窿大叔也照样活蹦乱跳啦，不过确实不能让现在状态的大叔承担重任呢」

如此交谈的阿尔德巴兰与八重瞥了眼在『阿尔德巴兰』身后局促不安的亨克尔，相互耸了耸肩。

至于亨克尔，让两人产生如此感受的原因，理所当然地，是他与菲鲁特之间关系的裂痕。

这个问题虽然因为暂且采取了应对措施而保持了暂时的平静，但那却招致了『阿尔德巴兰』的不悦，终究不过是权宜之计。

虽然希望火焰别再重燃，但即便真是如此，现在的状况既不适合委托重任，也没有足以托付的信任——这便是阿尔德巴兰与八重的共同见解。

无论如何──

「──将军了」

身动きと抵抗を封じられた奥托、もはや银色的茧と言うべき状态の相手を见上げ、阿尔德巴兰は长长延续的对局的一席で胜利を得る。

ただし、アルデバランが対局している相手はオットーだけではなく、王国规模、世界规模での対戦者たちとの多面打ちだ。一个落とさずに済んだからといって、それを会心の出来事として持ち歩き続けることはできない。

最重要的是，必须彻底排除，以免再度以对决者的身份回归。

「就算削去眼睛耳朵舌头和手脚～人家也是能遵守阿尔大人的命令的哟～」

「──八重」

「好～的～阿尔大人真是好～可～怕～」

施加无法再战的伤害，只留下性命让其撤离战线，实属欺瞒。

对于阿尔德巴兰来说不杀的束缚，并非是只要没死就能算遵守了的灵活程度，也不该如此。那种做法，就跟宣称只要夺走全世界人类的手脚就能实现世界和平一样。

所以阿尔德巴兰不会从奥托・阿斯苏文那里夺走眼睛、舌头、手脚。

取而代之从他那里夺取的，是战斗的理由。

为此──，

「──罗伊、咒印的适用范围放宽。轮到你了」

10

「──罗伊、咒印的适用范围放宽。轮到你了」

そう、自分を见上げる相手が声を発したのを、全身をくまなく拘束された奥托・苏文は确かに闻いていた。──一点だけ、阿尔德巴兰他们误解了奥托的『言灵加护』的效果。

言灵，也就是声音这种东西是音的振动。而振动这种东西，即使奥托的耳朵被堵住，只要在传达范围内就接触着奥托的身体。『言灵的加护』并非翻译从耳朵传入的声音。而是感知接触名为奥托这一存在的意志这一振动，并将其拾取。

故而──，

「不管怎么说都是奇缘呢，大哥。在普利斯提拉时，莱伊和路伊都没能吃成大哥，结果还是这样被端到了我们面前啊」

如此舔着舌头的『暴食』大罪司教、罗伊・阿尔法德的声音，奥托也能确实地感受到。

「────」

但是，令人从心底感到悔恨的是，奥托已经什么都做不到了。

虽说一直凭借『言灵的加护』持续拾取着周围的声音，但嘴巴被堵住，手脚被封住，连自己发出意志都被阻断的现在，奥托无论如何都无能为力。

『要对少爷、做什么啊……住手、请住手啊……！』

在悬吊着的正下方，能听见福尔夫痛苦的诉求令人心痛。

目前看来，阿尔德巴兰他们似乎不打算对福尔夫造成更多伤害，更别说取他性命了。既然如此，希望福尔夫能乖乖地、彻底地躲过这场风暴。现在这才是最大的愿望。

还有就是──

「──呃」

用不成声的声音，发自内心地担忧着不在此处的同伴们。

听说爱蜜莉娅和拉姆、佩特拉跟梅莉、雷姆和柯林特，还有与罗兹瓦尔、菲鲁特阵营的人也在合作。一定能找到妙计的吧。如果可以的话，真想用奥托自己的手，连加菲尔的那份一起，让对方尝尝苦头。

还有被囚禁的昴和碧翠丝两个人──

「悲伤呢啊啊，哥哥。痛苦呢啊啊，哥哥。但是呢，那种悲喜交集的阿鼻叫唤也一并接纳并爱着你！反正这个世界就是暴饮！暴食！」

缓缓地，感受到『暴食』那污秽的食欲正向自己逼近。对此，奥托除了无能为力地接受、被咀嚼殆尽之外别无他法。

所以继续地，奥托・苏文持续祈祷着。持续许愿着。持续思念着。

祈愿自己的、最后之计能够成功──。

「──那么、我开动了！」

11

「承蒙款待了」

『暴食』的权能效果发动，被吊着的奥托·阿斯·苏文遭到吞噬。

这一行为并未产生相应的特效，也没有魔法演出闪烁光芒，并未发生那种华而不实的事情。仅仅只是按部就班地，盛在盘子里的美味佳肴被送进吃相不雅的对方胃袋之中。——仅仅是进行了如此稀松平常的用餐而已。

「虽然刚才已经看过了，但真的感觉是犯规招式呢。一瞬间，丝线感受到的抵抗力就消失了嘛」

八重毫不掩饰声音中的嫌恶感，一边触碰着吐出钢丝的戒指一边抱怨道。

她此刻的话语意味着被束缚的对象──奥托・苏文试图挣脱钢线束缚的抵抗已经消失了。

这无疑证明了罗伊・阿尔法德的『蚀』已经生效。

「而且啊，咱们还真把你老哥的事儿给记着了。——好像是按约定忍住了只啃『记忆』来着」

「喂喂喂，你这感谢跟感动都还不够啊！先说好，光把『名字』和『记忆』分开来啃可费劲了诶？就跟得不开面包就能把三明治馅料挑出来吃一样，有这种麻烦事儿啊」

「谁管你啊。办不到的话你小子死就完了。给我仔细啃干净点」

面对着被钢丝裹得严严实实、动弹不得的奥托・苏文，正在述说权能辛苦的罗伊让阿尔德巴兰哼了一声。

实际上，不管罗伊再怎么强调这有多高难度，阿尔德巴兰都压根没打算听。不管怎么挑三明治的馅料，那都不是诉苦，而是没教养的显摆。——万一搞砸了，罗伊只会因为阿尔德巴兰刻在他身上的咒印效果，被烧尽灵魂而死。

无论怎样、现在让罗伊死掉的话会很困扰的阿尔德巴兰、每次失败都打算重来一遍、摸索能让罗伊顺利完成任务的方法。

「阿尔大人～、那个大罪司教、是不是有点得意忘形啦？既然能用咒印的效果束缚行动的话、压根不用费劲哄劝说服、明明还有更冷酷随意地使唤对方的手段不是吗？」

「刻印咒印这玩意儿、可没你想得那么轻松。说到底、誓约咒印对施加方也有风险。正因如此、刻印的机会一生只有一次。是让那些完全听不进人话的家伙服从的杀手锏啊」

对着凑近耳边悄声说话的八重、阿尔德巴兰一边推着她的额头一边回答。

正如其名、作为咒术之一的咒印、在魔法与咒术分派之前就已存在、其存在形式反而更接近魔法的源头。若因对「咒印」一词的固有印象而发表充满偏见的言论、恐怕会被传授这些知识给阿尔德巴兰的那位、絮絮叨叨说教大半天吧。

「竟然为我们动用如此宝贵的机会……！太好啦，太棒了，太赞了，可以的吧，没问题嘛，不是挺好嘛，因为我相信没问题，暴饮！暴食！这根本就是爱了吧……」

「哈！您是说比起这么可爱又性感的全心奉献系女仆八重酱，更喜欢牙齿不整齐的大罪司教吗！阿尔大人这个花心大萝卜！」

「你才别跟大罪司教打得火热配合默契啊……」

对喋喋不休的罗伊和毫不留情的八重这对组合的连番攻击感到厌烦。

八重想必压根没打算和罗伊和睦相处，但能为动摇阿尔德巴兰的心就不择手段这点着实很忍术。而罗伊那边，作为大罪司教却意外地通情达理，这种随意态度差点让人产生错觉。

但绝不能误会。对阿尔德巴兰而言，八重和罗伊同样都是为达目的可利用、必要时可能被背后捅刀的对象。

而那就是──

「罗伊，别太得意忘形了。赶紧交代刚才吞掉的大哥在盘算什么。老子可不是为让你高兴才给你吞的」

若是不遵从我的意志这边也会采取相同对策、在让『阿尔德巴兰』瞄准罗伊的同时，阿尔德巴兰也给出了明确的警告与告诫。

拘束を解き、折れた手足も治愈魔法で治してやった罗伊だが、决して信用も行动の自由も与えてはいない。ただ、ここから先、计划の诘めに入る状况で、なおも罗伊を吊るしたまま连れ歩くというのは现実的ではなかった。

过度警惕罗伊而导致迟迟不肯打出『暴食』这张强力卡牌，甚至抱牌掉落，可以说是阿尔德巴兰绝对不该犯的失误。

如今罗伊脖子上戴着名为咒印的项圈。『暴食』并非需要战战兢兢对待的炸弹，而是必须谨慎操控的鬼牌。

「要是能听到些有益的话题就好啦～」

如此低语的八重，对于罗伊的有用性持怀疑态度。这也难怪，毕竟对『暴食』的利用一直到最后都持反对态度的就是她。

八重虽然欢迎阿尔德巴兰因自己的建议而改变观念，但也强烈主张比起利用罗伊，更应解除『不杀』的限制。

实际上，正如她所说，如果阿尔德巴兰放弃『不杀』，并决定自由掌控所有对手的生杀大权，那么目标本身就会轻而易举地达成。只需向四面八方散布『阿尔德巴兰』的气息，不让敌人靠近即可。

但是，阿尔德巴兰拒绝了这一点，而是决定将允许其之前的──过程中的『死亡』，并利用罗伊・阿尔法德作为新的方针。

八重似乎对这个决定不服气，但利用大罪司教这种禁手，与阿尔德巴兰行使空缺席位权能的性质截然不同。这是连绵不断地传承下来的世界沉淀的核心，竟然以有用为由，为了自己而动用它。

这种事情，是与世界一同诞生的魔女因子问世以来，除了阿尔德巴兰之外只有一人干过的恶行，就是如此越界的行为。──因此，如果没有与之相称的成果，就背离太阳的意义了。

「所以，告诉我。你可是特意把对方的人生给毁了啊。别说你啥都没……」

「啊~，等等等等。别那么急嘛。你好像误会了，我们也不是吃掉对方就能一下子完全理解所有事情啊。原先就知道的事情嘛，不到必要场合也想不起来对吧？跟那个一样……」

「──俺可不说同样的话」

「……好啦好啦，知道啦~。诶嘿，这位大哥比想像中人生经验丰富，跟那边的福尔夫又是热血关系，我们都感动得眼泪哗啦──」

被打断辩解的罗伊，集中回味著刚吞噬的奥托的『记忆』。

那嬉皮笑脸的表情和态度，充满了品味本应只有加护者本人才能体会的经历与苦恼的愉悦，实在令人作呕又火大。

但罗伊那阴阳怪气的话语突然中断，阿尔德巴兰心生疑惑。

这无疑是挖到了某种令人在意的『记忆』的证明──

「怎么，搞什么」

「哈哈，看来我们比想像中还要周密啊。──有针对自己遭殃时的故障保险措施」

「────」

故障保险──为防止愚蠢错误而设置的安全装置。

当罗伊说出那句话的瞬间，一股剧烈的恶寒窜遍了阿尔德巴兰的全身。

并非针对自己遭受攻击时的对策，而是自己被打败之后的应对措施。──如果奥托・苏文早已准备了这一手，那么现在正是那个时候。

「八重！立刻──」

脱离此地，以及通过自尽使状况回归。

脑海中浮现出两种选择的同时，阿尔德巴兰并未锁定单一对策就行动了。这在某种意义上是有效的，在某种意义上却导致了失败。

那就是──，

「──重新问候，初次见面，阿尔德巴兰大人」

可爱少女的声音，如同突袭一般敲击着阿尔德巴兰的耳膜。

那简直就是在眨眼之间出现的异分子，由于其毫无预兆的出现方式，甚至连本能发出"不行"的警报都来不及。

不该去看那位改变了在佛拉基亚帝国时的样貌和装束的蓝发少女。──意识到这一点，是在目视到她那翻转的女仆裙摆之后瞬间的事情。

瞬间，那位女仆少女的名字、存在与生存方式，急速地威胁着脑髓。

「────」

『暴食』的权能曾一度吞噬了『名字』与『记忆』，从刻有所有生命名字的欧德・拉格纳名册中被删除的少女。这正是因『恶食』的恶意而被吐出、尚未造成实际损害便被搁置的存在，于阿尔德巴兰的脑中爆发。

被强硬地、凭借暴力、因令存在被回想起来的冲击所打击，本应肩负着不得停止思考之宿命的阿尔德巴兰，却被思绪抛弃──

「──阿尔様!!」

八重纤细的手臂下意识地伸向阿尔德巴兰，发出了呼喊。阿尔德巴兰的视野边缘捕捉到那白皙的手指，却无法动弹。

动弹不得、思维被剥夺的一秒间，局势已然变动。

──刹那，阿尔德巴兰的身体从方才所在的空间被剥离，猛然抛向沐浴烈风的苍穹。

「────」

放弃炙烤的太阳之灼光，烧灼着在半空飞舞的阿尔德巴兰的黑瞳。──这是突然开始的、阿尔一伙儿的紧要关头。

──决定世界趋势的摩格阿雷德大喷口争夺战拉开了序幕。

** 第二章 『闪雷蕾姆阵』

１

──在『暴食』罗伊・阿尔法德的手中，奥托・苏文轻易地脱离了战线。

作为『言灵加护』的加护者，史上最精通此道之人的战斗，如其宣言一般，将阿尔德巴兰一伙贬为世界之敌，并使其深受折磨。

正因如此，那场孤独战斗的结局，是以彻底、无助、不容反击的无情封杀方式到来的。

语言被封、行动被封、伎俩被封、急智被封、所有能动用的武器皆遭压制，最终连使其成为自己的『记忆』也被剥夺，奥托・苏文遭受了彻头彻尾的败北。

即便是奥托，当阿尔德巴兰一伙动真格地、以丝毫不给对策准备时间的全力来封杀他时，也毫无应对之法。

既然无法预测对手何时会尝试反击、会从何处发起攻击，那么就连凭借得意加护布置陷阱区域也无法实现。

因此，被袭击的奥托・苏文毫无应对之策──最后的策略，不过是防备遇袭时的『垂死挣扎』罢了。

──仅仅留下了当自己遇害时，让索达虫群体飞起以标记遇袭位置的指示。

２

『阿尔那家伙，在帝国相识之前……在被『暴食』吞噬『记忆』之前，就知道雷姆的事情。这点绝不会有错』

幻影菜月昴提出这个意见时，正值策划奇袭作战的过程中。

望着抱臂盘坐空中、神色凝重的『昴』，佩特拉在他记忆里回想起王都轮回中阿尔与雷姆产生交集的那段往事。

那正是昴在城中犯下重大失误后，拼命试图挽回局面的时期。

ペトラ的にはかなりひどいと思いつつも幻灭まではしないスバルの暴走だが、スバル自身は思い出すだけで身闷えするくらいの赤耻として记忆に刻んでいる。実际、あの场にいた谁もがスバルの暴走には眉をしかめたはずなので、あの姿に幻灭しないで済むのはペトラを除けば、当时から盲目的だったレムくらいのものだろう。

总之，当时未能从那种消极情绪的循环中脱身的昴，为了寻求拯救被魔女教袭击的爱蜜莉娅的方法，曾拜访过普莉希拉的宅邸。

在那里，昴遭到了普莉希拉超乎想象的尖酸刻薄、冷淡至极的对待，但关键的与阿尔和雷姆的接触点，却是在被从那宅邸赶走的当场发现的。

虽然不清楚具体原因──

『阿尔把拉姆和雷姆叫错了名字，还为此超级惊讶。就算问了雷姆，她也说和阿尔是第一次见面』

「意思是阿尔先生单方面知道她们的事吗？因为王选的竞争对手阵营所以调查过……之类的？」

『你说正经的王选对策之类的事情，是由普莉希拉阵营的阿尔负责的？虽然我觉得也不是没这个可能性，但那部分怎样都无所谓。重要的是阿尔认识雷姆这一点。也就是说──』

「跟我们大家一样，只要见到雷姆姐姐，阿尔先生也会『记忆』混乱」

『就是那个。──非要打个比方的话，就是闪光雷姆弹！』

随着啪的一声听不见的响指，昴眨了眨眼，佩特拉也竖起了大拇指。

说实话，把雷姆当作闪光震撼弹来用是有点抵触的，但这种『记忆』反弹没有对抗手段，佩特拉她们早已亲身体会过了。

就像昴附身佩特拉或拉姆时那样，似乎关系越深、情感投入越多，受到的冲击就越大，效果存在个体差异是不可否认的，但哪怕再微小，破绽就是破绽。

接下来就是要趁机──，

「就让阿尔先生知道一下吧。──我们究竟有多愤怒」

３

──在此，请允许我为『暴食』大罪司教，罗伊・阿尔法德进行一番辩解。

凭借其作为『暴食』的特性以及制造了诸多悲剧的『暴食』权能，使阿尔德巴兰一伙吃尽苦头的奥托・苏文被罗伊彻底无力化。那股『侵蚀』不仅令奥托无力化，更将他二十二年的人生历程囫囵咀嚼，喜怒哀乐一切种种都混杂一团，如从盘子里舔食般一口气吞个精光。

喉咙发出声响，结束了这场没有实体的用餐后，罗伊以超越解读『死者之书』的精度与鲜度品尝了奥托・苏文的人生，给出评价：算是克服了相当的艰难困苦，经历了应有的悲欢离合，调味稍显浓重，给个两星。

对于这样品评被吞噬之物，罗伊自己都不禁失笑，觉得简直像是在模仿已故兄弟莱伊・巴登凯托斯。不过话说回来，吞噬『记忆』意味着甚至能够知晓该存在的思维方式与哲学，倘若在战斗过程中，连对方正在图谋什么、策划何事都能了如指掌。

因此原本的话，即使有打倒奥托之后的胜利余韵和成就感，也应该能自然察觉到紧接着策划的奇袭才对。

但是，事情并没有变成那样。──因为在自己被打倒之后，奥托并没有共享同伴们具体会做什么的作战计划。

仅仅只是，奥托・苏文单纯地相信着而已。

只要发出能让自己明白被干掉的信号，同伴们就不会浪费这个机会。

正因为将一切赌在了这并非策略、单纯强烈的羁绊之上──

「──重新自我介绍，初次见面，阿尔德巴兰大人」

那正是在眨眼间的瞬息之事。

对于那个瞬间闯入的青发少女，阿尔德巴兰自不必说，连八重和罗伊、乃至亨克尔以及『阿尔德巴兰』都未能反应过来。

本不该存在的异物，毫无征兆地突然现身。

单是这一事实，就足以夺走身经百战的士兵们的刹那，但在此地因此受到致命伤的，却是连刹那都未能撑过的阿尔德巴兰。

「────」

过去没有交集的八重与亨克尔、自身权能对象外的罗伊、即便共享了『记忆』但灵魂本身不同的『阿尔德巴兰』身上不会发生的现象。

被刻入灵魂的黑色『记忆』受到刺激，连同被强行塞入原本已被去除之物般的粗暴感觉，阿尔德巴兰的意识逐渐被染白。

不知是谁说过，那是『记忆』的闪光震撼弹。

「──阿尔大人!!」

被高亢而拼命的声音呼唤，抓住从染白的意识彼岸伸来的手。然而，这并未将阿尔德巴兰从困境中拯救出来。

「────」

本应稳稳踩在地面的脚底划破天空，阿尔德巴兰发觉身体沐浴着猛烈狂风，失去上下左右的方位感，开始咕噜咕噜地旋转。

处于失控状态，头顶仍是镶嵌在蓝天中的耀眼太阳，其光芒灼烧着头盔内的黑瞳，阿尔德巴兰进一步意识到。

──被以某种方式转移到了空中，抛到了『领域』的外侧。

「──呃！　领域展开，矩阵再定义」

强行被迫中断的『领域』重新设定之际，阿尔德巴兰咬牙切齿。

被对方算计，巧妙地让矩阵完成了更新。──这样一来，就无法回到遭受刚才奇袭之前的状态了。

但是，如果更新判断再迟一些，阿尔德巴兰就会毫无还手之力地落败。

阿尔德巴兰的权能虽是无敌的，但那只限于设定好的『领域』之内。若在其外侧死亡，就和无数生命一样，不会获得重新挑战的机会。

「────」

理解了被赋予的前提条件，阿尔德巴兰的意识聚焦于现实。

既然矩阵被强逼着更新了，那么从此之后发生的一切，对阿尔德巴兰而言，便整体成为了他的珍宝与灾厄，顺风与逆风，善与恶。

「空……！」

听起来如轰鸣般咆哮的风声，拍打全身的猛烈漂浮感，明明没有被打飞的记忆却从高处坠落，这都是因为正式手续被省略了。

一瞬、阿尔德巴兰的脑海中浮现出最强『魔女』的权能，但不对。──如果对手是那个『魔女』的话，发生的现象会不同。不会像这样被抛到空中，更重要的是，阿尔德巴兰会在眨眼间被杀上百次。

因此，从众多最坏可能性中删除这一项。

在缩减可能性的同时，并行收集周围状况的信息。

眼下，要说在风中翻滚的阿尔德巴兰身边的异变──

「──阿尔大人」

就是紧紧抱住阿尔德巴兰独臂的八重。

在被抛向空中之前，她扑向了因遭受『记忆』闪光弹而僵直的阿尔德巴兰，结果一同从森林被抛到了天上。

将此视为吉兆还是凶兆，阿尔德巴兰在脑中区分着有八重在能做和不能做的事，选择了首要任务。

那就是──

「调整姿势！阿尔大人，请不要离开──」

「背背」

抱上来的八重正要设法应对坠落之际，与阿尔德巴兰在口中咬破药包服毒几乎是同时发生的。

能看见八重的绯红双眼猛然圆睁，带着愕然的表情看向这边。但既然已经吞下致死剂量，那也只能作罢。

「待会再问」

血沫从嘴角溢出，伴随着铁锈味感受着它毫不留情地玷污头盔内侧，阿尔德巴兰的意识被狂风撕扯──

×　×　×

「──呃」

虽早有预料，现实仍如连续陆地般迎接着风的呼啸声。

再度睁开闭合的眼睑，眼前依旧是那可憎的阳光璀璨──恶狠狠地瞪了它一眼后，阿尔德巴兰才意识到周遭状况：自己正身处数百米高空。

「开玩笑吧」

转移、瞬间移动、传送。──无论用哪种说法表述实质相同，作为作用于空间的阴魔法领域，这是需要满足所有条件的超魔法。

只要严谨地构建术式，稳稳地刻画出自己的领域，那么在其中实现门与门相连的有限传送还是有可能的。或者就算没有提前准备，只要能想象出目的地的坐标，施术者抱着把门用报废的决心来构建术式的话，说不定也能开出一张单程票。

×　×　×

总而言之，阿尔德巴兰他们被轰飞上天的现象，即使用魔法来实现也是不可能做到的程度，这牵扯到除此之外的犯规技巧。

在加护之中，理应不存在能够引发这种物理现象的家伙。

无论、像莱因哈鲁特那样，将被视为微不足道的加护以异常形式运用自如，并打造成令人畏惧的战斗产物的存在也存在──，

「──这不对。但、若是权能的话」

阿尔德巴兰所知范围内，现存的权能是『愤怒』『暴食』『色欲』由大罪司教持有，『怠惰』『强欲』则由菜月・昴各自拥有。

除却应当归为缺号・番外・盗用之一的阿尔德巴兰的权能这一例外，剩余的可能性便是『傲慢』、以及『虚饰』与『忧郁』。──既然最后二者理应无人能够运用自如，那么剩下的可能性便唯有『傲慢』了。

×　×　×

「『傲慢』来了？长出来了？加入了？──唉，那种事情怎样都无所谓」

アルデバランの知る谁かが『傲慢』に选ばれたのであれ、知らない谁かが『傲慢』として加わったのであれ、考虑すべきは権能の所有者が敌に回った可能性だ。

唯一、除菜月・昴和莱因哈鲁特之外，能凭借那未知数的能力威胁到阿尔德巴兰的，毫无疑问只有权能的所有者──那些被允许扭曲世界规则、肆意蹂躏的概念破坏者们。

×　×　×

「──噢莱伊、冷静下来了」

完全中了敌人的圈套，手忙脚乱惊慌失措的时间该结束了吧？──仿佛听见呼啸轰鸣的风声如此询问，阿尔德巴兰对着拟人化的风作出回应。

要做到那种程度，阿尔德巴兰中对现状的整理已经足够了。

无论、被抛向空中的处境也罢，将八重卷入其中的悔恨也罢，意识被逐渐复苏的『记忆』一片片覆盖的感觉也罢，现实都没有任何改变。

但真正该死的可太便宜了。那可是阿尔德巴兰的命。

若能以这贱命换取头脑、身体和心灵得以喘息片刻，简直是血赚的交易。

「──阿尔大人」

八重紧抱住阿尔德巴兰的独臂，看著她扎起的发辫如欢快摇尾的狗尾巴般激烈飘扬，阿尔德巴兰的思考推进至下一阶段。

必须让自己和八重生还并抵达地面。

为此──

「调整姿势！阿尔大人请别离开我身边──」

「不，那该是我的台词」

就在八重鼓足干劲试图在半空中自主行动时，阿尔德巴兰猛地将她拽回胸前阻止。因这动作使用了右臂，他立刻生成已逐渐熟练的岩石义手高举过顶──瞬间强烈冲击自上方直击义臂，坠落速度骤然加快。

那是即便通过人造手臂也能感受到沉甸甸冲击的、极其凶恶的铁块打击。在呼啸的风声中夹杂着如翻腾毒蛇般扑袭而来的锁链声响，潜藏其中的威胁。

与那名字相反，这是通过能使人类永远沉睡的带刺铁球──晨星所发出的世间罕见的可怕猛击。

「──接招吧！」

朝着这边砸来的铁球对面，背负着太阳般落下的蓝发少女。大幅削弱了阿尔德巴兰的优势，挑起战斗狼烟的对手──雷姆咆哮着。

那额头上缠绕着白色光辉生长的是一支角。那是鬼族的证明，也是为从这个世界上彻底扫除『魔女』痕迹而被创造的决战种族之一的证明。

但比起那更重要的是，对于回想起她存在的阿尔德巴兰而言，这具有别的意义。

那就是──

「说到底/雷姆小姑娘还活着这点/事情就完全不同了啊!!」

４

早已做好觉悟的雷姆纵身跃向空中，女仆装的下摆随风飘扬，她紧握手中的晨星握柄，瞪视着下方的阿尔等人。

──到此为止，奇袭作战按照计划完美发挥了作用。

在阿尔面前暴露雷姆的身影，趁其判断力被夺走而僵直的瞬间用『压缩』掳走。由此将阿尔与他的同伴分隔开来，并且成功将其带往能够封锁仓促行动的场所──早已达成一致的、天空之中。

至于关键的发动时机，多亏了持续追踪阿尔一伙并发动游击战的奥托事先准备好了自己被打倒时的信号。

因为那个信号即等同于阿尔一伙击败强敌奥托、紧张感产生丝毫松懈的瞬间。

「普莉希拉大人待我非常好。作为珍惜普莉希拉大人的人之一，我不能再对阿尔先生的暴行视而不见」

这是在有人反对雷姆前去与阿尔直接对决时，雷姆表明自己意愿的发言。

那终究只是奠定觉悟基础的心态问题，但无疑是雷姆的真心，也是挑战这场战斗不可动摇的动机核心。

当然，就在那个核心的正旁边有着被阿尔囚禁着的昴的存在。说不定这边才是核心呢。──不，果然普莉希拉小姐也是核心，所以核心有两个。碧翠丝大人请容我之后向您道歉。

总之、怀着这样的干劲、雷姆参加与阿尔直接对决部队的事就此决定了。

作戦上、其他战场上并非必须有雷姆在的理由也存在，但比起最初的『记忆』动摇，雷姆对阿尔具有特殊效果的可能性相当大。

而那个可能性正是──

「说到底，雷姆小姑娘还活著这一点就已经让情况完全不同了啊!!」

从上方挥下铁球一击的瞬间 用岩石义腕挡住刚击的阿尔 一边将雷姆的身影纳入视野一边这样怒吼道。

轰鸣的风声不断喧嚣，即便如此依然清晰传达而来的话语，让雷姆确信这是从佩特拉那里听说的、雷姆所不知道的与阿尔的关系起了作用。

「对于不成器的雷姆来说，实在是想不起来和阿尔先生有什么交集呢……」

虽然也向拉姆确认过了，但拉姆和阿尔的交集似乎也仅限于王选正式开始前在王都有过一次交谈的程度。据说并没有进行什么值得留在记忆里的实质性对话，甚至连具体聊了什么都很模糊。

恐怕，我们姐妹与阿尔的交集是单方面的，仅来自对方而已。

但是──

「这种说法太伤人了！在古拉尔被亚拉基亚小姐袭击时，救了我们的正是阿尔先生和──」

话到此处戛然而止，但雷姆强忍着将犹豫咽了回去，

「──不就是普莉希拉小姐吗！」

特意提起普莉希拉的名字，雷姆企图诱发阿尔的动摇。

雷姆自我厌恶着认为自己发挥了能想到的最恶劣的卑劣手段。但这也是阻止阿尔暴行所必需之事，雷姆让身心都化作厉鬼般绷紧了严厉的视线。

与毫无印象的阿尔的交集，以及促使他走向暴行的对普莉希拉的执念。能同时刺激这两点，正是雷姆腾空起舞的意义所在。

阿尔的权能『时间溯行』的恐怖之处我已充分了解。要对抗这一威胁，并非要在肉体上使其屈服。──必须扼杀其心灵。

「────」

面对雷姆的挑衅，阿尔并未提高音量，而是选择了压抑的沉默。

漆黑铁盔内侧，面甲遮蔽了阿尔的表情，连目光都无法窥见。雷姆方才的话语究竟带给他多少痛楚，也无从知晓。

「──要上了！」

但雷姆并未等待阿尔的反应，毫不喘息地再度发起攻击。

雷姆早已定好优先级。她本就是个笨拙平庸、事事都比不过优秀天才又总胜世间万物一筹的姐姐拉姆的姑娘。

若这样的雷姆渴望超越常人之物，唯一能做的便是将对应之事做到极致。

眼下雷姆最擅长的，便是为优先度高的事物而对优先度低的事物闭目不顾。

「修玛！」

咏唱声中，玛娜干涉现世，化作本不可能的现象——魔法已然发动。

与爱蜜莉娅的修玛能操纵热量、通过凝固空气中的水分来生成冰不同，雷姆擅长的是在虚空中用魔法创造出水，并将产生的水从一开始就以冰的形式输出的修玛类型。

虽然不能说哪种修玛更优秀，但爱蜜莉娅型的修玛利用空气中现成的水分，不仅所需玛娜量较少，而且在完成任务后还能留在原地，具有可重复利用的优点。另一方面，雷姆型的修玛由于需要重新制造水，所需玛娜量较多，使用后大多不会残留，而是还原为玛娜。

单看这个说明的话，可能会觉得爱蜜莉娅型的修玛要优越得多吧。但是，雷姆型的修玛也有其强大的优点。

那就是不受空气中的水分含量和水质的影响，能够在希望的地点以希望的形状制造出冰这一点──

「──哈啊啊啊啊啊!!」

雷姆踢击在空中生成的冰之立足点，猛烈地袭向阿尔他们。

只要创造出固定坐标的修玛，就能制成即使雷姆全力踩踏也不会损坏的临时立足点。这样一来，在获得哪怕仅仅一瞬间的支撑后释放的晨星威力，与在空中扭转身体挥出的那一击根本无法相提并论。

轰然作响、旋转着冲向阿尔的铁球毫无手下留情之意。

若被直击绝不可能安然无恙的铁球，仿佛为了回应昴满怀爱意每日为它擦拭打磨的心意，自雷姆手中带着欢欣迫近阿尔，迫近，迫近──，

「不会让你得逞」

这充满爱意的铁球，在直击瞬间被无数丝线从正面层层缠缚捕获。

定睛一看，做出此举的是在阿尔怀中、扭转身体瞪视雷姆的红色忍术──追随阿尔的、强韧无比的操线者。

被阿尔从身后抱住的忍术，从伸出的双手放出丝线展开成网状，以此柔软地、如缓冲垫般接住了铁球。

这番手法固然了得，但雷姆最为关注的并非此处。

原本这场奇袭作战的目的，就是打算让阿尔从盟友中彻底孤立。而她中途插手这件事本身就很不对劲。——不，说不对劲是错的。

雷姆は、何故彼女にそんなことができたのかを知っている。

突然的雷姆出现，全员意识被空白包裹尽管如此，仍留下能伸手触碰那份空白的余地，并将其付诸实际行动。

是什么促使了那样做──，

「──那就是，爱！」

「不对!!」

「不是的!!」

面对充满确信的雷姆的呼喊，阿尔和忍术几乎同时吼了回来。

趁此空隙雷姆强行拉回险些被夺走的晨星，从不愿失去体势的忍术那里收回铁球。为了下一次攻击，她创造出多个新立足点，踢击那些立足点急速下降，追赶二人。

然而──

「虽然害怕被追上，但长有长短有短哦？」

一度紧绷的表情恢复了从容，放出丝线的忍术嫣然微笑。从她手中释放的丝线飞向的，是雷姆在空中制造出的冰之落脚点。

突如被抛向空中、陷入只能任由自由坠落摆布的状况中的阿尔等人，正试图以雷姆制造的踏脚处为支点重整姿态吧。

看起来，忍术的实力在雷姆之上。再加上拥有权能的阿尔组成组合，一旦对方调整好姿态，敌我优势转瞬间就会逆转。

「是啊，我明白。因为我尽是些短处呢」

所以雷姆，不会让他们从那种不便中逃脱。

「──什！？」

听到雷姆的回答──不，一度抓住的触感如雾霭般消散，忍术的表情再次失去了从容。

她缠绕丝线的冰之踏脚处，竟如同梦境幻影般消失了。

当然，既非梦境也非幻影。是玛娜。只是雷姆随心所欲地将其还原成了玛娜。

这正是，一旦冻结就维持原状的爱蜜莉娅型，与只在想冻结时冻结且便于收拾的雷姆型之间，同为修玛却存在的巨大差异。

「简单来说，雷姆更具攻击性」

存外、这类差异除了精通魔法之人以外鲜为人知。即使在魔法研究最为先进的王国，能够将其充分说明者也是凤毛麟角吧。

那凤毛麟角中的一人，正是雷姆的主人兼魔法导师罗兹瓦尔。

「我想起来了。无论过去还是现在，我都觉得雷姆身处幸运之地！」

「──」

在雷姆眼前，忍术使积蓄的力量失去目标，身形失衡。

抱着那名忍术使的阿尔也被牵连险些摔倒，但他仍用额外外装加固了碎裂的义肢，接连挡下雷姆袭来的第二、第三次铁球攻击。

其应对能力堪称精湛，甚至让人怀疑是否动用了『时间溯行』。

然而，若只专注于头顶的雷姆──

「──看招!!」

──从斜下方飞踢而来的爱蜜莉娅修长腿足，已用冰靴武装的脚尖毫不留情地踹中阿尔毫无防备的后背。

５

阿尔德巴兰一伙的分裂。──这对于堪比魔女教、或者说在瞬间风速意义上超越魔女教的世界级威胁而言，是绝对不可回避的战斗前提条件。

为达成此条件所实施的奇袭作战，大约九成都按计划顺利推进。

偏离预期的一成──自行选择升天殉道之忍术的存在会引发何种变数，虽作为不确定因素给作战留下了瑕疵，但过度担忧反而可能令瑕疵扩大。

各自，竭尽全力完成被赋予的职责。

若没有这份信赖与觉悟，阻止阿尔德巴兰一伙的策略便无从成立。

「──其实嘛~大家都吓得发抖露出超受不了的眼神啦」

边说着边懒洋洋地晃动垂下的双臂，『暴食』大罪司教罗伊・阿尔法德舔着嘴唇环视四周。

在其周围，阿尔德巴兰他们刚刚消失之后，就如同替换他们一般接连出现的人影──那是为了打倒阿尔德巴兰一伙而聚集起来的战士们的身影。

面对那毫不退让地直视大罪司教的锐利目光，罗伊不禁兴奋得扭动身躯。

「不错嘛，很不错嘛，说不定真的很棒呢。但是啊，这么多人聚集在一起真的没问题吗？要是你们在这里输掉了的话……搞不好，想要对付我们的人，就会一个都不剩了哦哎！」

「──哈。你才该稍微表现得害怕一点、僵住不动，展示一下可爱之处怎么样？如果你不想和死在砂之塔的兄弟落得同样下场的话。」

「而且啊，难道连魔兽酱也在你们的好球区吗？如果不是这样的话呢……我觉得，我可能就是你们的天敌了呢。」

战士们之中，那个抱着自己胳膊的身影和那个抚弄着三股辫的身影如此回应道。

那毋庸置疑的敌意，对罗伊而言，也不过是点缀盛宴的极品香料罢了。

「开、开什么玩笑……你们这帮家伙！难道看不见『神龙』的样子吗！?王都被破坏成什么样了……怎么可能有胜算啊！」

与情绪高涨的罗伊形成鲜明对比，脸色发青、声音颤抖的是亨克尔。

正如字面意思，倚仗着『神龙』威严的他，对着在龙脚下睥睨自己的敌意啐唾沫，带着充满畏惧与焦躁的神情拼命提高嗓门。

那姿态正可谓是『狐假虎威』，但事实上亨克尔的主张并没有错。若要以毫无对策的状态阻挡拥有绝对力量的『神龙』，等待着的将是无情的毁灭与终幕。

「不过，这仅限于毫无对策的情况罢」

「──啧，巨人族的老头」

「那个巨人族老头，可是知道『亚人战争』的。对于抱有敌意的家伙，慈悲不会施予第二次。──把菲鲁特还来」

屏住呼吸，正面盯着眼神游移的亨克尔，巨躯抚摸着秃头宣告道。对于那巨躯的宣言，亨克尔绷紧了脸颊，但还有另一个动了动的影子。

不是别人，正是被当作靶子的『龙』本身。

『虽然这么说可能不太合适——但被逼到这种单方面挨打的地步，老子可是吓尿了啊。现在正切身体会着"与全世界为敌"这句话的分量呢』

拥有那般威容的『龙』，却用异常人性化的动作抬手扶额。

明明是栖息于亲龙王国的众多生灵只需望见其身影、靠近其身侧便忍不住俯首跪拜的存在，此刻的姿态却无论如何都只让人觉得是截然不同的异类。

至少，在知晓真正『神龙』之人眼中，这股违和感再明显不过。

「不过嘛，我和王国的那些大人物不同，才不会因为这种事就慌慌张张地嚷嚷什么『神龙』形象崩塌啦、品牌价值下跌啦——倒～～是说，我旁边这位小伙子怎么想呢？心里应该有不少想法吧——？」

「不会，老爷，您多虑了，纯属杞人忧天。对早已抛弃的过去品头论足，于我也只是滑稽之举。软弱」

面对着与自身器量不相匹配的龙鳞外壳，俯视着那些毫无惧色的人们，『阿尔德巴兰』眯起了金色的双眸。

然后──

「────」

挡在面前的众人之中，缓缓迈出一个小小身影。自然而然地，不仅是『龙』，连罗伊和亨克尔的目光也汇聚到那个人影上。

虽不清楚她为何被选中，但不可思议的是即使不说也能明白。

她掌握着──这场战事的开火权。

在众人注视下，她──佩特拉・雷蒂指尖指向天空宣告道。

「──这是全面战争。请乖乖认输，被打得落花流水就好」

６

──神明大人，佛祖大人，欧德・拉格纳大人。我发誓终生不再饮酒。

×　×　×

「──这是全面战争。请乖乖认输，被打得落花流水就好」

是的，就在阿尔消失的山中佩特拉宣告的瞬间，紧张感急速膨胀、迸裂。

刹那间，因佩特拉等人出现而提高戒备的阿尔一伙残留成员──『神龙』波克肯尼卡与『暴食』罗伊・阿尔法德，以及亨克尔同时行动。

但三者的行动毫无配合，完全各自为战。

「────」

看到这个动作，佩特拉确信最初的策略──不、最初的策略是阿尔出人意料的闪光雷姆柠檬水，所以这是第二个策略。目的是让阿尔一伙这些各自不可小觑的强敌变成乌合之众并空中解体，这个目标已经达成。

「一开始先孤立阿尔姐姐，然后让剩下的人大吃一惊。这样一来——」

『预备——跑！所有人就开始随心所欲地行动！』

佩特拉与幻影菜月昴的声音接连响起的眼前，『龙』与大罪司教以及亨克尔，全员都依据个人判断行动。为了让这些选择尽可能分散开来，从最初就动用了王选混成军──『阿尔德巴斯特斯』的大半战力。

当然，这项策略也存在被『神龙』一网打尽的巨大风险但──

「──大概，阿尔先生让『神龙』成为同伴的方法，和我是一样的」

对那位鼎鼎大名的『神龙』波克肯尼卡的背叛，佩特拉如此推测道。

关于监视塔顶的波克肯尼卡，佩特拉从爱蜜莉娅那里听取了详情，知晓漫长岁月使『龙』的精神风化。──在那暧昧的意识空白中填入『某物』的方法，佩特拉通过亲身经历比任何人都更熟知。

正如佩特拉用『死者之书』将菜月・昴寄宿于自己意识中那样，波克肯尼卡极有可能也寄宿了与阿尔协同的存在。并且该存在与阿尔高度共享目标，决定共同与世界为敌。

佩特拉赌的正是这点。──阿尔与波克肯尼卡共享的『不杀』誓约。

『──唔！』

起手发动攻势的，是以巨躯灵敏行动的『神龙』。

『龙』庞大的颚门开启，吐出的气息并非让万物归于虚无的毁灭之光──而是用龙庞大玛娜生成的清水雾霭。它将佩特拉为首的『阿尔德巴星团』一举吞没，浸湿了所有人的身体。

瞬息间，因不解『神龙』意图而产生混乱，但这份疑虑很快便消散。

「────」

空气的嘎吱声冲击着鼓膜，刹那间戒备的动作受到阻碍。只见湿润的身体上覆盖着薄薄冰霜，佩特拉等人的身躯转眼间被冻结成冰──

「──乌尔・戈亚」

刹那之间，赤红烈焰将被染上白雾的森林彻底覆盖。

『神龙』企图用浓雾实现的冻结化，被这遮蔽全部视野的火焰膨胀以蛮力压制，瞬间融解冰封，连湿润的身体都在顷刻间被烘干。

完成此举的，是立于人群中心竖起手指、仅凭一句咏唱便阻截了『神龙』谋划的，性格恶劣却堪称王国第一的稀世魔法使──罗兹瓦尔・L・梅札斯。

毋庸置疑，越是高阶的魔法就越需要精密的操控。

不仅能以绝非人人可轻易驾驭的乌尔级魔法即时应对，更当场解除全员冰冻，连衣物都烘干却未造成烫伤，实乃神技。

面对一气呵成达成此等壮举的罗兹瓦尔，就连自古永存的『神龙』亦为之震愕。

就在这时──

「你应该关注的是这边。倾注」

平静而彬彬有礼的一声低语，伴随着超乎想象的猛烈打击。

柯林特轻巧地踏步跃起，用他那双长腿朝着停止动作的『龙』侧脸豪爽地踢去。这一踢的威力，丝毫不逊于加菲尔那炮弹般的猛击，失去平衡的『龙』单手撑地，扬起一片尘土。

『神龙』的先手，被罗兹瓦尔与柯林特这对组合正面压制住了。

「哈哈啊！　把这么美味的脑袋凑在一起，这根本就是爱了吧喂」

撕裂那条『龙』扬起的尘土，龇牙咧嘴的『暴食』大罪司教飞扑而出。

与以全体『阿尔黛巴斯塔兹』为目标的『神龙』不同，垂涎欲滴地冲入战线的罗伊，其目标明确地只有一人。尽管动机是食欲这种野性的冲动，罗伊却以异常精湛的敏捷，将恶毒的言辞对准了威风凛凛伫立着的桃发女仆──

「──拉姆」

伸出的手，通过触碰看不见之物，完成了用餐的准备。

呼喊着名字、嗤笑着的罗伊，与被呼唤名字、表情僵硬的拉姆视线交错，下一瞬间，大罪司教刻意炫耀般舔了下触碰过她的手掌。

『暴食』的权能发动，新的悲剧在此萌芽──并未发生。

「呜噗」

目露惊愕的罗伊，仿佛因未发动的『蚀』的反作用力而感到呕吐感般捂住了嘴。在步履蹒跚的罗伊面前，拉姆轻巧地华丽转身，

「真是愚蠢呢」

跃起的拉姆膝盖，鲜明地击中了这位大罪司教的下颚。

「可恶可恶可恶！都到了这一步……！」

『神龙』与『暴食』，这两者虽然各自目标不同却都选择了攻击，与此相对，最后一人亨克尔的选择却截然不同。

选择了既不同于『龙』之冰冷吐息也不同于大罪司教『暴食』之道路的亨克尔，一边用出鞘的剑牵制着『阿尔德巴顿斯』，却并未向前而是向后跃去。那是期盼着除自己之外的某人能改变战局的、卑屈的举动。

然而──，

「事情可不会如此顺利，当家大人」

「当家大人，其实我一直想这么做」

就在此时，从『压缩』刚结束就潜伏在树上的双胞胎姐妹飘然降落。

菲菈姆与格拉西丝──侍奉阿斯特雷亚家的双胞胎，讽刺地对所侍奉家族的前任家主，从其前后方同时踢出夹击背部与腹部的猛击。

「呜呃……」

『流法』を修めた姉妹的踢击、发出了让人难以想象是娇小少女们所能造成的爆音。亨克尔遭受着仿佛内脏要被挤出来的冲击、翻着白眼发出濒死般的声音。

──几乎同时发生的三种冲突，开场相当顺利，正如所料。

接下来再加上──

『──游戏规则改变了』

只有佩特拉能听见的『昴』的响指高声回荡。以此为信号，战况出现了新的变化。──进一步的『压缩』，将阿尔一伙更加分割开来。

７

──阿尔一伙的可怕之处，佩特拉・雷蒂从结果中更加更加深刻地认识到了。

自从普雷阿迪斯监视塔的背叛以来，阿尔将『神龙』拉为盟友，躲开了莱因哈鲁特和菲鲁特阵营的追捕，并在王都成功协助『暴食』大罪司教越狱。

截至目前的发展中，阿尔与行动共犯者们所扮演的角色各自重大吧，但果然最大的威胁非阿尔本人莫属。

得知了阿尔那非同寻常的命运力──吸引所求结果的力量真面目后，佩特拉心中涌起了无比的信服。

那当然是因为读了《死者之书》后得知的、菜月・昴的真相。

『阿尔那家伙也是读档能力的持有者……那么、那份棘手程度我最清楚不过了。况且、和自身战斗力贫弱的我不同、阿尔是属于自己能战斗的类型、说白了就是我的上位替代在做对手吧』

「……昴不也是和碧翠丝在一起的话就很可靠嘛。而且要论小伎俩和鬼点子、可不会输给奥托先生的」

『可是、原本的俺正和碧翠丝一起被抓着啊、小伎俩和坏点子什么的、又不是强者能洋洋得意炫耀的技能构成吧……』

幻影菜月昴如此缺乏自信地想着、但即便抛开恋慕心和偏心眼不说、佩特拉也不认为昴会劣于阿尔、更不要说什么下位替代了。

关于那一点，实际上从查明阿尔的权能并非时间轮回的罗姆爷那里，也听到了很有意思的考察。

──话说阿尔的时间回溯，说到底不就是短暂时间的重来吗。

「如果真的和昴拥有同样的能力的话，那原本在撞上菲鲁特大人和罗姆爷爷他们之前，就应该能避开那种情况了对吧」

『不过，那份自信也不能太过头啊。也有可能只是重启的地点刚好是无法避开菲鲁特他们的场合罢了。就连俺，也没能完全阻止培提尔其乌斯袭击爱蜜莉娅碳她们啊』

「我觉得几乎是完封——」

说到一半，佩特拉顾及到昴的心情，闭上了嘴。

如果正如佩特拉所说，『昴』完美封印了袭击罗兹瓦尔宅邸和阿拉姆村的『怠惰』大罪司教的话，后续雷姆和库珥修的悲剧就不会发生。

昴已经全力以赴做了能做的事。佩特拉如此评价，但当事人却不这么认为。这一定不仅是针对『昴』，真正的昴也是同样的想法。

这悲哀地关联到菜月・昴极低的自我评价，这件事在佩特拉看来非常令人焦急──，

「只是暂时推迟处理……因为要对付的不光是那位离谱的阿尔先生，还有『神龙』啦忍术女仆啦大罪司教啦亨克尔先生等等」

『重新一看真是群不得了的家伙啊。『龙』、忍者、大罪司教，连莱因哈鲁特的大叔也是，既然是那个莱因哈鲁特的父亲，肯定没那么容易对付吧？』

「关于亨克尔先生我拒绝评论」

对着表情严肃的『昴』，佩特拉将手指在嘴唇上比成叉号表示拒绝回答。

虽然曾在佛拉基亚帝国与亨克尔短暂共事过一阵子，但他总是刻意摆出拒人千里的态度，所以几乎和佩特拉没有交集。

唯一对他有所关照的只有加菲尔，但若是知道亨克尔如今的状况，加菲尔一定会非常沮丧吧。一想到加菲尔失魂落魄地发出「嘎呜……」哀鸣的样子，佩特拉心中对亨克尔的怒火就不断上涌。

因为爱蜜莉娅阵营可是个全员团结一致、会对伤害同伴之人同仇敌忾的阵营啊。

「呼……必须冷静下来。加菲小哥的心情得靠他自己化解才有意义，而我们得为他铺平道路才行」

『虽说要铺路，但该从何处着手才好呢……』

「嗯，说得对。确实会不知所措呢。不过──」

看着『昴』一筹莫展的模样，佩特拉狡黠一笑转过身来。受她的动作牵引，『昴』的视线也跟着转了过去。

在那里，有着总是习惯独自承担一切的菜月・昴屡屡受挫跌倒、历经无数次失败却仍不断取得成果，以及此刻陪伴在此的大家的身影。

『────』

「确实，我觉得阿尔先生他们都是非常棘手的对手，正常交手的话我们确实毫无胜算。──但是，我们这边也相当不普通哦？」

佩特拉单闭着眼睛眨了眨眼，摆出自认史上最可爱的表情，对着瞪大眼睛的幻影菜月昴的侧脸微笑着说道。

就这样，她和这群不普通却可靠的同伴们一起制定了作战计划──

──以奥托・苏文的信号为契机，战斗拉开了序幕。

８

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓这辈子再也不写信了。

×　×　×

──『忧郁』魔女因子带来的权能『压缩』绝非万能。

『压缩』引发的现象，终究只是对可实现事物的压缩──典型应用如缩短前往可抵达地点所需时间。反过来说，即使花费时间也不可能实现的事情，也无法通过『压缩』达成。

例如，即便借助『压缩』之力，普通人也不可能抵达天空彼岸的星辰，同样也无法企及大瀑布的尽头。

权能既是干涉世界法则之术 同时也是彰显世界被构筑得何等坚固、精密的原理。更何况，『忧郁』的魔女因子不过是真品魔女因子的仿制品 虽是人力难以掌控的力量 却终究是无法触及深渊的货色。

化不可能为可能的并非特殊力量 而是为达成目标所耗费的人类意志的积累 权能不过是助推这积累的诸多要素之一。

因此 即便是分割阿尔德巴兰一伙 在最初将阿尔德巴兰扔出战场后 要进一步分割残党也绝非易事。

一旦让对方警惕『压缩』 权能效果的发动的难度便会急剧上升。更何况 对手若是『神龙』或大罪司教之流 光是带离战场就已是极其困难。

『压缩』的弱点在于 其发动对象若非同意效果者或毫无戒备者 适用领域便会极端狭窄。

──而王选混合军『阿尔德巴斯塔兹』以连发奇策克服了这个弱点。

利用数量优势动摇亨克尔，趁执着于『不杀』的波克肯尼卡心理松懈之际，将沉迷于享用盛宴的罗伊・阿尔法德的『暴食』拒之门外。

这些都是直至实施前都无成功把握的奇策。——然而，这世上本就不存在能获得百分之百确信的策略。

有的只是向百分百靠近的努力，以及相信自己已竭尽全力的信念。

能为名为可能性之芽浇灌水露之人的气魄——

「啊啊，多么令人心旷神怡。赞叹」

如此颔首着地后的柯林特正视前方，凝视着『神龙』波克肯尼卡。

用单手支撑着失衡身躯的波克肯尼卡，正面接住了柯林特的视线。眯起金色眼瞳的『龙』身上，能感受到清晰意志的萌芽。

正如佩特拉的推测，『神龙』的龙壳中寄宿着另一种意识——篡夺者的意识。

『────』

理所当然地，注视着我们这边的波克肯尼卡毫发无伤于初击。虽说成功做到了令其惊讶的程度，但这一击距离逼入绝境还差得远。

但即便如此 最初奇袭的目的已经达成。——在对抗『神龙』龙鳞的战域中 与篡夺者对峙的『流星』成员仅有两人。

只剩下了柯林特　与罗兹瓦尔・L・梅札斯两人。

『……和炸飞起源的手法一样啊』

用手撑地支起身子　『神龙』以低沉凝重的声音如此低语。

『龙』用那双金眼环顾四周 注意到他们从方才所在的山中被转移到了相距甚远的岩地平原。

这正是通过『压缩』实现移动 成功将棘手对手分离的证明。

然而——

『叫柯林特是吧。虽然觉得难以置信……看来你就是『忧郁』魔女因子的持有者没错了』

「——。从何处得知该情报？疑问」

『从一位博学多识的熟人神明大人那儿听来的。不过 当时只当是混在胡话里的无稽之谈 直到刚才我都完全没想起来』

用过于人性化的动作耸了耸肩的『神龙』，从其口中说出了『忧郁』一词，以及被指认为魔女因子所有者的事情，让柯林特陷入思索。

倘若篡位者连龙壳的知识都能提取出来的话，知道这些也不足为奇。但若真是如此，至今的言行就有些令人费解了。

若要兼顾两者的逻辑，就只能认为篡位者虽未完全掌握龙壳，却已经从某人处听闻了柯林特的情况——

「要是你们俩自顾自地互相理解，我可是会感到被排斥在外呢—啊」

「老爷……」

「你确实是能处理细致工作的人才，但过度了就会沦为神经质之流。对方如何获得知识并不重要—呀。毕竟，计策已然奏效了嘛」

『计策、呢』

对着责备柯林特的罗兹瓦尔，篡位者猛地张开了背上的双翼。仅是如此就卷起一阵狂风，袭来的风将柯林特他们的头发吹得纷乱。

『虽然轮不到我来说，但你把罗伊啊大叔啊咱们这边的战友先放一边，把你那些伙伴们隔开是不是失策了啊？』

「嚯？这意见倒是有趣啊——要详细说说看吗？」

『你懂的吧。射程范围内人越多，我缩手缩脚的可能性就越大呗。就我这身板和溢出的抛瓦，想手下留情都不容易啊』

「原来如此，说得通。如果目的是限制对方充分发挥实力的话，确实该这么做才——对——嘛——……」

「——不凑巧的是，这个条件对我们也同样适用呢。彼此彼此」

『你说啥？』

龙壳的篡夺者刚用言外之意警告对方别给自己全力发挥的环境，却被柯林特这句话说得眯起眼睛，随即又猛地睁大双眼。

——只见五颜六色的光芒密密麻麻地浮现在空中，将『神龙』团团围住。

『这是……』

乍看之下，它们如同在魔力泉涌中实体化的微精灵们的聚会般淡雅华丽，但只要是稍微精通魔法之人，就能感受到那淡淡光芒的每一缕都是庞大的魔力块——威力骇人的大魔法之瞬动。

当然，其发生源不言而喻，便是史上也罕见的、最强魔法师——

「可别用这种称赞方式啊？ 被知晓老师存在的你如此评价我 可是会让人家心痛到不得了的错误哟ー」

罗兹瓦尔仿佛看穿了柯林特的内心般说道。深知他对老师非同寻常的敬意与执着的我　决定避免草率回应。

总之、如你所见、若是他想以最大火力施展真本事的话、周围的同伴只会碍事。而那是──

「──我也一样。同意」

一边说着，柯林特用抬起的手摘下了戴在左眼上的单片眼镜。

瞬间，空气微弱地震动，那微弱的震动逐渐扩大，一点点，伴随着空间碎裂般的声音，大地开始轰鸣。

摘下的单片眼镜并非特制品。

摘下单片眼镜是为了切换意识的仪式，需要的是回归过去自我的觉悟。──他压制住这股冲动，柯林特强迫自己继续保持着旁观者的立场。

这份忧愁与沉郁被拥有闪耀灵魂的少女指出时，柯林特感到了自我羞愧。

得到了最后的推力，已经再也无法继续停滞不前了。

因此──

『……喂喂』

伴随著骨头嘎吱作响的声音，从柯林特那长著蓝色头发的头部伸出了两根黑色犄角。那既非鬼族象征的角，也非魔兽所拥有的角。──而且既非以上任何一种，在这世界上会生出乌黑犄角的种族只有一个。

那就是早已数量锐减到被认为已经灭种的存在──龙人。

作为强大『龙』族的下一代，选择蜕去龙壳、采取人形的新种族。柯林特也是这群龙人之一，对世界而言具有特殊意义的存在。

因为──

『终于明白这种奇怪感觉的真面目了。你就是，这具身体的──』

「再说下去就煞风景了吧。不需要」

篡夺者仍企图继续辩解，柯林特从正面径直打断了那些话语。

无论换成其他任何人，都没有比柯林特更具资格令篡夺者沉默。

毕竟篡夺者所窃取的龙鳞，哪有比其原本持有者更相称的存在。

「──『魔女』之徒，罗兹瓦尔・L・梅札斯」

『──『神龙』波克肯尼卡』

浮起大魔法、踏稳地面的罗兹瓦尔报上名号。与之相应，篡夺者也厚颜无耻地如此自称。

遵循这种惯例，将自己置于舞台之上已有多少年未曾有过了呢。——怀揣着这般念头，柯林特亦身缠紫电，朗声自报家门。

「──『神龙』之龙人，柯林特」

霎时间，与『神龙』相连的二者骤然行动，展开的魔法迸发威力。宛若天变地异的冲击与破坏在平原上交锋，膨胀的光芒自大地灼烧天空——

——此刻，知晓四百年光阴者们之战，就此拉开帷幕。

９

──神様、仏様、欧德・拉格纳様。生涯、不发誓不抱布偶。

×　×　×

下巴撞上膝盖的瞬间，罗伊・阿尔法德的思绪如闪电般掠过。

诡异、难解、离奇古怪、盘旋的疑虑、疑心、疑问、不对劲、大异常、谬误、千奇百怪、变故、不正常、不正当、混乱、满腹疑团、疑疑疑疑疑疑疑──、

「──去死吧」

拉姆不会放过被这些疑问支配、以某种方式挫了锐气的罗伊。

她伸出的白皙手指狠狠掐住仰面朝天的罗伊的脖子。涌上的呕吐感和呼吸受阻，疼痛与窒息感侵袭着罗伊矮小的身躯。

但拉姆的可怕之处，在于她毫不手软的冷酷。

「芙拉」

掐住喉咙的手间生出的风刃，锐利地正面击中无处可逃的罗伊细颈，毫不留情地将罗伊的首级从躯干上斩飞──

「──根本办不到啊，这玩意儿！」

瞬间，风之斩击掠过，罗伊的脖颈爆裂般喷出鲜血。

但那不过是连试图擒获凶恶罪犯的卫兵们挥出的千把剑——任何一把都无法刺穿的、拥有刚皮之『肉食兽』贝里・哈尼尔加的再现，并未触及罗伊的性命。

「────」

拉姆对意料之外的结果瞠目结舌，就在那一刹那，罗伊将以锁喉招式攻击他的她一同带往战场上空──『跳跃者』多尔克尔的转移之力。

某日突然如天启般与欧德・拉格纳连通获得异能的『跳跃者』，乃是利用其力量暗杀了众多权势者的秩序破坏者。其转移毫无前兆，趁被出其不意而僵直的拉姆以蛮力将其制服，借此空隙对战场上的猎物进行品评──

「艾尔・芙拉！」

「──呜噫──、来真的!?」

毫不犹豫地，侧腹被风魔法猛然击中，罗伊不禁发出赞叹之声。

毫无疑问、转移应该是拉姆意料之外的。但、她将没能砍下罗伊头颅的冲击和转移的惊讶都瞬间消化、立刻进行了反击。何等胆量！何等刚毅！

「干爆你！」

那风刃也贯穿不了『肉食兽』的刚皮。不过，这份果断和行动力值得称赞。所以，怀着称赞的心情，用『拳王』涅吉・罗克哈特的拳打来回礼吧。

剑奴孤岛上曾击碎无数强者头颅的『拳王』一击、承受了这一击的拉姆纤细身躯变得惨不忍睹、软塌塌地压瘪──消失了。

「把拉姆给跟丢了？你这双眼睛真是没用呢」

突如其来的声音，本应消失的拉姆气息出现在身后，罗伊下意识地使出『拳王』一击看都不看就打了过去，却挥了个空。如同魔法一般，气息转移到头顶，延髓被踢中，整个人头朝下地向地面坠落、坠落、坠落──。

「啊～，真漂亮啊～」

从背部朝向地面坠落的过程中，罗伊连防护姿势都不做，只顾痴迷地仰望着头顶──那位翻飞着裙摆、桃色长发优雅飘扬的少女身影。他就这样毫无防备地摔落地面，冲击力从背部穿透至腹部，剧痛贯穿全身，却毫不在意。

──『肉食獣』×『跳跃者』×『拳王』。

对于『暴食』吞噬的精华理外之人，拉姆以其出色的力量、技巧和心智将其完美处理，罗伊不由自主地深受感动。

这里罗伊也必须展示自己的本事，他踢腿站起，屈膝蓄力准备扑向拉姆。

因为──

「待客之道必须全力以赴 要把全部所有的一切统统倾注进去作答才行啊 那种做法根本算不上是爱吧！」

「──这种思维方式 和我在某处听说的故事如出一辙 真是超级讨厌啊」

但是，比起罗伊跳跃返回空中更快的是，从侧面袭来了凶猛的咆哮声。咆哮伴随着锐利的兽爪，以及爆炸般的突进力。

扭曲的犄角与需仰视的巨躯，以支撑那庞大身躯显得过于纤细的四肢灵活地驰骋大地的存在，正是被称为『漆黑森林之王』的凶暴・凶恶的代名词──

「────呜!!」

「呀啊、基尔提拉乌!!」

朝着发出惊叫的罗伊，凶兽的利爪挥落而下。瞬间凭借『食雪者』提斯罗之力抗衡，以曾单枪匹马阻止雪崩的规格外肉身，依次正面接住坠落魔兽的刚腕——右前足、左前足，死死缠斗在一起。

正当他准备运足气力，企图扭断基尔提拉乌的双足──的刹那，滑入魔兽胯下时，与架起法杖的薄红眼眸对上了视线。

「真的，最棒了──」

「芙拉」

未待他说完便被风之子弹击中额头，又被基尔提拉乌的尾击轰飞。被重重弹开、以脚尖滑地止住退势的罗伊抬起了头。

手持法杖的拉姆身后，紧紧趴在基尔提拉乌背上的少女梅莉，将其纤细的手指指向罗伊──不、指向罗伊的背后，叫喊道。

「上啊，魔黑犬宝贝们!!」

「「──呃！」」

梅莉的高声呼喊着回应，无数的红色光点猛然地向罗伊跳跃袭击了过来。

那是露出狰狞獠牙、企图啃噬猎物的黑犬赤红双眸──其身承载着过量咒术与魔法力量的魔兽、沃尔加姆的群群。

魔犬之群毫不留情，将利牙刺入『暴食』躯体，撕裂啃食。讽刺的是，享有『恶食』之名的罗伊・阿尔法德的结局，竟是沦为魔兽凄惨的饵食──

「啊啊啊啊啊啊啊啊──」

那群魔兽因罗伊喉中迸发的突兀歌声而骤然僵直。

动弹不得的猛犬群中，罗伊温柔抚摸着其中一只正咬住自己脖子的家伙的脑袋──紧接着，从伤口喷涌而出的鲜血化作利刃翻腾扭动，将无法逃脱的魔兽们撕裂、贯穿，令它们发出临终的悲鸣。

「哟嗬——」

罗伊缓缓撑起身体站起身来，将全身展露无遗。

遍布罗伊周身的魔犬咬痕中流淌的鲜血化作亮闪闪的刀刃，黑犬群落如同果树枝头成熟的果实般悬挂着，化为死骸。

这是在各地吟游反国诗歌的《悲恋歌人》诺塔的诅咒之歌，与只能操纵自身血液的魔法使《血泪鬼》阿德范的梦幻共演。更进一步地，通过利用死去魔兽残骸中残留的魔力，实现了以颠覆圣王国为目标的《虹幻公》马托克里玛・乔拉东的魔技——以尸体为茧的彩虹色蝴蝶开始羽化，轻飘飘地围绕罗伊飞舞。

对应尸体数量羽化的蝴蝶，翩翩翩翩，翩翩——

「锵锵锵锵——！」

——《食雪者》×《悲恋歌人》×《血泪鬼》×《虹幻公》。

罗伊率领着无数的彩虹色蝴蝶，向给予了他无比甜美款待的拉姆等人，献上了饱含心意的赞美，装点了这华丽的舞台。

然而，对于目光和态度都变得严厉的拉姆与梅莉，她们明显流露出敌意。虽然对此感到一丝遗憾，罗伊还是毫不气馁地露出了笑容。

「呀呀~真是厉害呢。刚才那呼吸完全一致的配合！我都快麻木了哦。你们两个是从什么时候开始变得这么要好的？果然是在我们不知道的砂海旅行期间拉近了距离吧？拉姆小姐和梅莉小姐都好坏啊」

「请不要带着那副鲜血淋漓又惨不忍睹的模样若无其事地搭话。和异常者交谈，会让拉姆小鸟般的心脏因不安而快要破裂啊」

「小鸟心脏！啊呜、能自己说出这种话的地方真是令人尊敬呢。接下来会有什么样的铺垫引爆局势，兴奋得停不下来呀呜」

啪嚓啪嚓地拍手，罗伊唰地将血刃收回体内。在魔兽尸体噗通噗通掉落的过程中，罗伊使咬伤的血凝固，啪嗒止血后陶然地呼气。

真挚的心意似乎没能传达出去，但称赞的心情是真实的。单相思很痛苦。不过，拉姆他们比罗伊期待的还要奋斗，这一点我想好好珍惜。

「那个先放一边，呐」

将对于拉姆等人的怜爱之情暂且搁置一旁　罗伊推测先前十几秒攻防战中发生的不可思议现象的真相──与消失的『神龙』有着密切关联

即便如此 也实在是令人惊讶不已 因为那般庞大身躯的『神龙』 不知何时已从战场的各处消失无踪

「大概、兜帽大叔和忍术姐姐消失的事啊、拉姆小姐她们突然出现的事啊都是同样手法……咦、我觉得应该是柯林特先生干的、感觉像是权能之类的东西呀」

消失的阿尔德巴兰他们、以及取而代之增加的敌人。时隐时现的拉姆的存在、也整体上和『记忆』中柯林特的特殊技能形象吻合。

只不过，若依靠罗伊自身的知识而非『记忆』，能实现这一点的既非个人异能，亦非不同性质的加护，而是权能。

如此一来，柯林特就会成为唯一空席『傲慢』的适任者了。

「嘛~，消失的人现在怎样都无所谓啦~」

不光是『神龙』，战场上还缺少柯林特和罗兹瓦尔的身影。

虽然柯林特的实力深浅不明，但作为权能持有者至少能成为战力吧。罗兹瓦尔和柯林特搭档对抗『神龙』，为了不让心跳不已兴奋雀跃的大规模战斗波及周遭而转移了战场。背景缘由大概如此。

总之，既然已从战场消失，那套时隐时现的戏法今后便再无施展机会。

那么现在比起消失的薄情者，优先享受款待眼前女士们的乐趣才是。

「不错嘛不错嘛，人类真不错啊~」

防止『蚀』的手法、准备无名魔兽的措施、甚至构筑这个战场的所有要素，全是为埋葬罗伊等人精心策划的谋略集合。

针锋相对的事前筹备，即是精心布置，亦是待客之诚。为款待竭尽全力。——这正是所谓的尽心竭力。

「既然这样、老子这边也得用相应的礼节回敬才行啊、不然可就太对不起你那满满爱意的关照了呐」

「──。你想做什么？」

敏锐地察觉到受款待方罗伊的变化、拉姆皱起形状姣好的眉毛。面对明显露出警戒神色的美丽女仆、但罗伊却「不不呐」地摇了摇头。

全力应战──没错、这正是场配得上如此称呼的战斗、可谓是终极对决。

王选混合军、若有菜月・昴在场恐怕会命名为『阿尔德巴托尔斯』的敌阵已做好万全的招待准备、全员都眼神决绝要发挥自己的真正价值、榨干自己的智慧与潜力、拼尽死力战斗到最后一刻。

不仅是拉姆他们、被毫不吝惜投入战力的全员皆是如此、对于罗伊・阿尔法德而言正是想给全员打满分、画上大红花的巅峰状态。

那朵大红花唯一美中不足的瑕疵、并非在对方身上。──而是在我方这边。

「────」

视线余光瞥见的角落、那里有着与罗伊一同被遗留在战场、啪嗒啪嗒流着鼻血狼狈跪地的红发男人──亨克尔的身影。

从『暴食』的视角来说可能有些冒犯，但罗伊对亨克尔的评价意外地不错。

这种生活态度——作茧自缚的死结加上似乎永远无法坦白的阴暗烦恼——大概有着唯有如此才能产生的浑浊涩味，作为珍馐倒是引起了我的兴趣。

不过这一切的大前提是，不能妨碍主菜的香气与卖相，而现在的亨克尔即使从『暴食』视角来看也一无是处。

「不管多奢侈的晚宴，只要有混着剩饭的盘子摆在桌上就全毁啦」

唯独在全员团结一致拼上性命的战场上，混入一个可能破坏战局的因子，哪怕是『暴食』也难以忍受。

所以说──

「大叔啊——别一直畏畏缩缩的爽快点行动起来哟噢！」

「大、大罪司教……」

突然提高音量的罗伊让满脸鼻血的亨克尔抬起头来。与他对上视线后，看到那双蓝眸不自然地游移，罗伊觉得有些好笑。

简直就像是在依赖般的眼神。哪怕有一丁点对罗伊的同伴意识或想要依靠的心情的话，向大罪司教寻求这些也未免太不顾体面到没有限度了。那种没有底线的难堪，从某种意义上是无可替代的，但现在却只是纯粹的，碍事。

「──干脆，让叔叔从重担中解放出来吧啊？」

既不拯救。也不抛弃。

只是嘿嘿嗤笑一声，罗伊向亨克尔提出了第三个选项。

「────」

即使双眼圆睁呆立原地的亨克尔，也确实接收到了那个提案。

重担、以及被如此形容之物对亨克尔而言有多重要，罗伊并不清楚详情。但想必是比自己的生死更重要的东西吧。亨克尔亲眼目睹并深知，罗伊拥有夺走它的手段。

罗伊的那番话绝非威胁，而是切实可行的选择。

因此──

「就~该这样才对嘛」

面对咬紧牙关的男人表情变化，罗伊因发自内心的喜悦而心跳加速。响应着罗伊高涨的情绪，彩虹色的蝴蝶们开始如求爱般翩翩起舞。

在彩虹色鳞粉诡异闪烁的天空下，罗伊懒懒地伸出舌头嗤笑。──这样才算真正意义上的全面战争开始了。

「想被满足却又不想被满足。──人生啊，真是韵味深长得令人吃惊呐」

10

──老天爷，佛祖大人，欧德・拉格纳大人。我发誓这辈子绝对不碰针线活。

×　×　×

「呜诶……」

后背与胸口遭受夹击般的冲击，亨克尔无能为力地瘫倒在地。

卡洛尔与格里姆──长期侍奉阿斯特雷亚家的佣人夫妇的孙女们，这对双胞胎曾受『流法』启蒙的踢击，是忽略稚嫩的致命凶器。

「嗷呜，呜噗，呕呃」

自佛拉基亚帝国停战以来，几乎没能好好吃过一顿饭。从空荡荡的胃里榨出胃液，亨克尔狼狈地跪倒在地。

「「────」」

看着冷冷俯视这样的亨克尔的菲菈姆和格拉西丝，拉姆自嘲地扭曲了脸颊。

就算这样、亨克尔也是阿斯特雷亚家的现任当家。对于这样的亨克尔、理应宣誓忠诚的雷门迪斯家的女儿们、是何等不敬的眼神啊。亨克尔别说她们了、就连她们的父亲也是从出生起就认识的──。

「我们的忠诚是献给若様的」

「当家主大人 把前任家主给捅了个透心凉」

面对这对双子锐利的回答 亨克尔甚至没法抱怨 只能沉默不语。

两者都是令人哑口无言的正当道理，对她们憎恨亨克尔、将其视为敌人而言，都是太过具有说服力的理由。前者不断折磨着亨克尔，后者则成为新添苦难的罪过，如沉重巨石般压覆全身。

即便如此──，

「死不了啊……」

碾磨后槽牙挤出的呻吟 包含着双重含义。──既是都做到这份上了可不能死 也是都被折腾成这样了居然还没死。

然后亨克尔自身，也不清楚是怀着哪种打算脱口而出的。

「咕、呜！」

面对这样根基摇摇欲坠的亨克尔，双胞胎毫不留情。毫无迷茫。

将『流法』运转全身的少女们的手脚，已然锤炼到堪比钢铁的境界。被那如同暴风雨般的连续打击击中，就如同置身于钢铁的暴雨之中。

上下、左右、前后，菲菈姆与格拉西丝以完美对称的配合猛攻，亨克尔只能用剑护住要害，一味防守，被打得遍体鳞伤。

──『流法』，回想起来，这个亨克尔也未能真正掌握。

很多一流的剑士、战士都能无意识运用的战技，即使被条理清晰地仔细教导，亨克尔也无法将其完善到足以用于实战。

菲菈姆和格拉西丝，记得当时应该才十二岁吧。

尽管是由她们的亲祖父母传授，花费了远超她们年龄两倍以上的岁月，但亨克尔的『流法』却连那两人都远远不及。

若能将此归咎于才能差距而放弃挣扎　亨克尔的千百苦痛是否能减轻分毫。

「可、恶……！」

面对作为牵制而挥出的剑击，双子仅凭眼神交流的配合便敏捷地避开。这缺乏击中意图的剑技被准确看穿，从手肘到腋下直至脖颈的要害全被逐一刺穿。

骨头吱嘎作响，从只能吐出胃液的口中滴落鲜血。不由自主低头的瞬间，双胞胎伺机翻身跃起，鞋底狠狠踢中了我的鼻梁正上方。

「嘎──噗」

亨克尔后仰着猛然倒地，后脑勺遭受了重击。

视界明灭闪烁，呜嗡耳鸣声遥远传来，亨克尔强行拉回差点呆滞的意识，慌忙撑起身体架起剑瞪向正面。

眼前、翻转身子的双子并肩着陆，仔细地拂去衣角抬起头来。──交错的视线中，亨克尔看到了两人细微的困惑神色。

「────」

姐妹困惑的真相，正是亨克尔依然屹立不倒这件事本身。

时间上不过短短十几秒，仅仅如此亨克尔就已遍体鳞伤。衣服沾满泥泞，滴答流淌的鼻血更是将胡茬凌乱的脸庞糟蹋得一塌糊涂。

然而，亨克尔没有倒下。虽然狼狈不堪，却始终睁着眼睛。从手感来判断，这令菲菈姆她们难以置信。

「哈啊、哈啊……♡」

但可悲的是，能让双子震惊的耐久力根本谈不上任何优势。

倘若眼前之人不是亨克尔，或许还能选择以切肉断骨的战术稳守反击——耐心承受对手攻击伺机而动，瞄准决定性瞬间予以还击——

「唔、呜……♡」

架起的长剑剑尖不住颤抖，亨克尔的虚张声势在任何人眼中都显而易见。

胜负已然决定无异于──不、说到底根本算不上战斗。因为并非战斗、胜负之类根本无从决定。连竞争胜负的阶段、都未曾达到。

亨克尔・阿斯特雷亚总是如此，甚至连那个前提都无法触及。

「但是、那样……♡」

绝不能倒下。必须撑过去。

若是在此倒下、至今为止究竟是为了什么而行动。究竟是为了什么刺杀父亲、威尔海姆・范・阿斯特雷亚、将会变得不明所以。

只要继续咬牙坚持，哪怕只剩一层皮也还有希望。一定能看到光明的。

会是阿尔德巴兰还是『神龙』，又或者是八重呢。最不济来个罪司教也行。总会有谁打破战局，为亨克尔带来希望──就在此时。

「大叔啊——别一直磨磨蹭蹭的了赶紧利索点干活哟！」

突然，撕裂战场的声音传来，亨克尔猛地抬起头。

有意识后才第一次注意到。战场的任何地方都没有『神龙』的巨躯。不仅是阿尔德巴兰和八重，连『神龙』也消失的战场上，留在这边的只有亨克尔和

「你、你这、大罪司教……！」

那边也只有与敌人对峙的『暴食』罗伊・阿尔法德。

「──」

亨克尔一边对连周围状况都看不清的自己感到失望，想着究竟是从什么时候开始变成这样的，一边揣测着呼唤自己的罗伊的意图。

大罪司教と连携しようなんて、正直、自分でもどうかしていると思う。だが、ヴォラキア帝国で、エミリアの骑士であるナツキ・スバルは『暴食』を従えていた、らしい。それと同じだと思えば、强烈な抵抗感は无理やり饮み下せた。

特意从监狱塔里逃出来。大罪司教也不想死吧。就算是应该唾弃的对象，只要目的相同就有携手的余地──

「──干脆让大叔从重负中解脱吧？」

但是，紧接着抛出的话语，彻底违背了亨克尔的期待。

「────」

这既非援助的提议，也非求救的呼喊。只是一句极不合时宜且任性的狂言。

到底在想些什么。你明白现在的状况吗。既没有用莫名其妙的力量撬开道路的阿尔德巴兰，也没有最强生物『神龙』，更没有精通小伎俩和刁难的八重。这里只有软弱脆弱无力的亨克尔，和秉性卑劣的大罪人罗伊而已，为何要与我制造隔阂。——不，并非制造了隔阂。隔阂本就存在。存在着无法填补的差距、无法跨越的悬崖、隔绝的绝对鸿沟，只是如今才清楚地意识到这一点。意识到了，又能怎样。那家伙说的话，又能怎样。明白了那家伙言下之意的自己，又该如何。——将亨克尔从重负中解放？将这早已与亨克尔灵魂愈合的重负？

──那是不可原谅的，我绝不容许。

「就~该这样才对嘛」

那个、罗伊发自内心愉快地说出的声音，并未传入亨克尔的耳中。

面对以摇曳如幽鬼般动作站起的亨克尔，对峙的菲菈姆与格拉西丝先是微微绷紧脸颊，随后无言交换眼神，彼此颔首。

然后──、

「当家的，请做好觉悟」

「把所有火力统统砸进去」

或许是认为不痛不痒的连击会适得其反，能切身感受到双胞胎的杀气变得愈发锐利。

正如宣言所言，接下来将是竭尽全力的一击吧。刚察觉到这点，菲菈姆与格拉西丝便蹬地而起，笔直冲向亨克尔。──不，并非笔直。

「「──嘿！」」

声音与动作同步，双胞胎用踢击剜开大地，并将其朝正面踢飞。遮蔽整个视野，被剜开的大地逼近而来。

对此，亨克尔挥剑将其一分为二。既非人，也非生命。若仅是物体，斩断便无需亨克尔的犹豫。

然而，在斩断的大地彼端、开阔的视野中，并未出现菲菈姆她们的身影。

取而代之的是双子从左右两侧夹住亨克尔，将至今为止获得最大加速的一击毫不留情地刺向了亨克尔的两肋。

「──咕」

这毫不夸张地是双胞胎用尽全力的一击，以至于亨克尔的手臂都被打得陷了进去。

亨克尔的肋骨被击碎、冲击直达其内侧包裹的内脏。他以惊人的势头涌上的血从口中大量喷出、亨克尔几乎昏厥。

但没有失去意识。勉强站稳了。不仅站稳了——还咬紧牙关扭转身体，强行抓住了刺入自己体内的姐妹的手臂。

「──啊」

「不妙」

手腕被紧紧勒住的疼痛让菲菈姆和格拉西丝皱起了脸。

就这样两人用被亨克尔抓住的那只手相反的自由之手、自由之脚，对亨克尔连续发动打击，虽如暴风雨般殴打钢铁，但亨克尔并未放开抓住的手臂。

这并非我渴望获得的东西。即便如此，能断言亨克尔比他人优秀的，就只有这超乎寻常的坚韧体格，而最能善用这特质的方法，大概就是这个了吧。

尽管遭到疯狂殴打，仍试图抓住对方。──连剑士的风度都谈不上，正是亨克尔・阿斯特雷亚式的、毫无优雅可言的粗野反击。

「──啊啊啊啊!!」

鼻血弄脏了、被揍得肿起的脸面下，亨克尔高举起双臂，将抓住的双子猛烈地、朝着地面砸落。

この瞬间、相手が子どもであることも、自分の家に仕える存在であることも、ハインケルが生まれた顷から知るキャロルとグリムの孙娘であることも、忘れる。──否、忘れるのではなく、目をつむり、干坤一掷、二人を头から地面に──、

11

──神啊、佛啊、欧德・拉格纳大人。我发誓此生再也不唱歌。

×　×　×

以尸体为蛹 以生命余烬为燃料羽化的虹色之蝶──『虹幻公』所创的这项魔技 绝非创造新生命之物

归根结底 蝶只不过是借用了其形态 本质是与生命创造相对的死亡具现化

「兄长大人的王牌对吧 虹色魔法」

在吞噬的『记忆』之中，刺痛的感官甜美地令人回想起缠绕剑刃的虹光极光──原理上来说，『最优骑士』施展的绝技与虹色蝴蝶本是同根生。

『最优』凭借其才能与契约精灵们的力量实现的那一切，『虹幻公』不过是以榨干性命为代价发动而已。

「但这招威力可不会打折扣啊」

将接触对象连根掀飞的死亡之蝶，随着罗伊的笑容为信号，约二十只一齐朝拉姆与梅莉袭来。

面对这般威胁，拉姆与梅莉当即心有灵犀。

「拉姆姐姐——！」

「称呼不对啦」

「知道啦——夫人！」

伴着恰到好处的认真对话，骑乘基尔提拉乌的梅莉上前。她拍打漆黑魔兽的脊背，借其刚腕强行折断身旁树木。

伴着噼里啪啦的破碎声倾倒的树木间，拉姆闪身冲入，蹲伏着将法杖笔直架好——

「艾尔・芙拉」

席卷而起的狂风将折断的树木猛然掀飞，撞向蝶群。洒落死亡鳞粉的蝴蝶们被迎面击中，迸发极光般的爆裂。

「呜～～！」

最・适・解！　说着，无法抑制颤抖的罗伊懊恼地跺着脚。

拥有将万物构造分解并破坏之力的虹色蝴蝶，说白了就是触之即亡的火之魔石。以其绝大破坏力为代价，它只能使用一次──让其撞击障碍物后爆破解体才是最安全之策。

即便如此，初次见面就能应对到这种程度，真让罗伊大吃一惊。

「但・是・啊!!」

要是就这样被蝴蝶全灭了，『虹幻公』在九泉之下也会哭湿枕巾吧。

从正面突击的蝴蝶消散于虹色爆炸中，但幸存下来的蝴蝶各有五只，绕过那绚丽的爆裂大幅回旋，瞄准了拉姆她们。

加之这次不仅是蝴蝶，罗伊也借助『跳跃者』之力跃向那边。随即用『雪食』的刚腕企图先扑杀基尔提拉乌。

──『虹幻公』×『跳跃者』×『雪食』。

极光炫目遮蔽了拉姆等人的正面，幸存虹蝶从左右包夹，正后方则由转移而来的罗伊负责——无路可逃的三重杀招毫不留情地炸裂在拉姆等人面前──瞬间，婴儿啼哭声撕裂了罗伊的鼓膜。

「────嗯嗯」

被这不合时战的尖叫声瞬间夺走思考的罗伊，眼前发出婴儿啼哭的竟是堪称神明失败作的亵渎造型魔兽——它挥舞着骨制成的燃烧双枪，将组成包围网的虹蝶集体烧尽。

再度迸发的极光爆炸中，罗伊任发丝在爆风中翻飞，凝视着眼前出现的异形存在——本该只存在于砂海地底的饿马王。

「带它过来可是费了好大劲哎」

由巨角构成的头部与配备巨口的人类上半身形躯体，支撑其的超大马身部分——说是人马一体却扭曲丑恶到极致。──这样的饿马王，竟与梅莉方才骑乘的基尔提拉乌互换了位置。

「────」

这个事实让罗伊的思绪千丝万缕地紊乱，『记忆』的大型会议摸索着答案。

被提上议程的是，眼前事件的真相、迫在眉睫的危机的应对措施、对令人震惊的事实的适当反应，各种紧迫性交织在一起。

那个、在选出最优先议题的前一刻──

「──搞什么你这家伙，长著张猪一样的蠢脸」

真后方传来声音的主人、那巨大的拳头击穿了罗伊的矮小身躯。

「──呃」

背部遭受重击、整个人浮空而起的罗伊身体飞越了饿马王与梅莉的头顶。连爆裂的极光都被他甩在身后，贴着地面滑行的罗伊单手插入地面急停，扭身着地，用杂耍般的动作重整架势，迫使敌人放弃追击。

罗伊的视野捕捉到了骑在饿马王背上的梅莉、其身旁出现的黑色西装打扮的猪头人巨汉、以及处于与刚才明显不同位置的拉姆。──新敌人的出现与瞬间发生的匪夷所思的置换战术，这本该被彻底否定的可能性再度浮现。

这本该只有从现场消失之人才能使用的特殊技能再次被发动──

「──不对啊，不是那样的」

正因为有着『记忆』，反而陷入了先入为主的观念无法自拔。

这一瞬间的替换是权能所致，那是柯林特的力量。所以自己先入为主地认为，在柯林特与『神龙』一同消失后的战场上，没有必要戒备那股力量。

但是──

「──你他妈也算个当爹的，别对小孩子出手!!」

耳边传来被怒火燃爆的粗犷吼声，紧接着是重重一击──视野边缘，用双臂抓住双子少女的亨克尔，脸上挨了一拳。

将那猛烈一击打出的，是罗伊『记忆』中认识的高大男人──本该在战斗开始瞬间就不在场的加斯顿。

「────」

面部被击穿的亨克尔向后仰倒，双胞胎在千钧一发之际逃过一劫。

罗伊的激将法到底有没有奏效呢，亨克尔似乎也一度逼近了目标，但这次反击的势头似乎从一开始就被挫败了。

不过，罗伊也没资格嘲笑亨克尔。毕竟他也是被同一个对手用同样的手法挫败的。

而且，这个对手并非柯林特。

「诶～？真的吗～？会有这种事情吗～？」

想不出其他可能性，罗伊被这过于意外的真相搞得连自己都怀疑起自己来了。

那声音里蕴含的感情满是惊讶，完全没有否定或贬低那个事实的意图。完全没有，但假如那是真的话，可真是荒唐至极、意料之外了。

最初以为，那个起初用智谋将阿尔德巴兰他们逼入绝境、只差一步之遥的老巨人才是嫌疑人。──但这个推测，因知晓她的『记忆』所提示的「难不成」的可能性而被推翻。

「不要啊不要不要不要不要不要啊」

纵然想缓缓摇头否认，却无法否定已察觉的可能性。

毕竟，罗伊通过『记忆』知道她是能做到那种程度的孩子。对于那般年纪的少女竟获得如此高评价，就连一笑置之都做不到。

她的努力也好，胆量也好，实绩也好，目标也好，都知晓着『记忆』所见证的一切。

那不是柯林特。那是在拉姆她们与罗伊冲突的战斗中，也在痛殴亨克尔的双子之战中，一直以绝妙时机介入的存在。

它俯瞰着这场全面战争，持续使用权能重构着局势。

那是──

「──佩特拉酱，你从什么时候当上大罪司教啦？」

「这话，听起来可真刺耳呢。反正都要用难听的称呼，不如这样叫」

这么说着，寄宿着魔女因子、凭借权能支配战场的游戏制定者───佩特拉・雷蒂将手按在自己胸前，吐出舌头「呸」了一声，说道。

「──『忧郁魔女』，佩特拉・雷蒂哟」

** 第三章 『忧郁魔女〉

１

──神啊，佛啊，欧德・拉格纳大人。我发誓这辈子都不跟小孩子玩了。

×　×　×

『比如说，要是柯林特兄长大人持有的魔女因子能给别人……给我用的话，是不是不用支付代价也能随便『转移』啦？』

那是当佩特拉从柯林特那里得知『忧郁』魔女因子的存在，以及其与『压缩』权能的关系时，最先想到的恶意用法。

柯林特说过他并非魔女因子的适格者，使用『压缩』的权能需要付出代价──必须支付相应的代价。同时，『忧郁』的魔女因子是为特定个体量身打造的一次性因子，终究与佩特拉也无法相容。

因此，拥有『死亡回归』权能的『魔人』菜月・昴与协助他的『魔女』佩特拉・雷蒂——这种充满特别感的组合在成立前就宣告解散，说实话，我虽然松了口气，却也尝到了遗憾的滋味。

その后、『忧郁』的魔女因子被排除在议题之外，几乎确定将用于与同伴汇合以及突入敌阵──然而在制定将阿尔一伙一网打尽的作战计划过程中，它再次受到了关注。

魔女因子对未被选中者很是冷漠，没有代价就绝不借出力量。因此，无法与任何人适配的『忧郁』魔女因子，是无人能够驾驭的东西。

这便是长年担任『忧郁』魔女因子管理者的柯林特的说明。

然而，反过来说──

「──只要能够支付代价的话 就算是非柯林特兄长大人的人也能使用『压缩』对吧」

对于佩特拉的这番构想　柯林特并未改变表情。

这反而让佩特拉确信了自己想法的正确性。若是真心想隐瞒 柯林特本该表现出「完全没想到」的惊讶模样。本该虚张声势地说从未尝试过 所以不清楚能否顺利。

「要想对付阿尔先生他们 最低条件就是将全员分散隔离。若排除阿尔先生 最难应付的对手当属『神龙』大人……但柯林特兄长大人会设法解决的 对吧？」

「关于这点我也能保证。柯林特可是能成为对付『神龙』波克肯尼卡的王牌关键人物哒～诶。用法 对了吗？」

「──。没问题」

在作战会议过程中　豪言能够压制『神龙』的正是柯林特。

老实说 无论是关于『忧郁』魔女因子的事 还是代替法兰黛莉卡的发言 都让人震惊他和罗兹瓦尔究竟共同隐藏了多少秘密 但终归是值得信赖的。

不过，虽说柯林特很可靠，但也不能凡事都依赖他。

「不过，如果柯林特兄长大人要专心对付『神龙』大人的话，用『压缩』就没法让人进出去了吧？」

「不否认。肯定。当然，我会竭尽全力将所有人送达战场，但……」

「唔~嗯。那样的话，『压缩』的优势就浪费掉了啦。因为『压缩』最厉害的地方就是像传送门一样，可以随时调配或替换战力嘛」

平静却饱含坚定热忱的柯林特誓言，应当不是谎言吧。

他一定能确实地将我方最大战力送抵敌阵。这本身就是破格的成果。但若是能期待更多，那这也是场应当尽可能追求极限的战斗。

「那么，话题就转移到权能转让上了啊。实际上，在商讨之前，老夫想先确认这是否真是可行的方案」

「──。关于那个。犹豫」

「柯林特兄长大人，请把材料全部摆到桌子上」

「────」

「我认为现在正是讨论大家手头有什么牌、哪些牌能用到什么程度的场合。所以，请不要有所隐瞒」

面对吞吞吐吐的柯林特，佩特拉明确地如此要求。

他不愿多说的理由，以及纠结是否要隐瞒情报的原因都心知肚明。虽然明白，但这场讨论是为了拯救王国、拯救世界──拯救菜月・昴他们的商讨会。

声称要毫无隐瞒的佩特拉被梅莉瞪了一眼，这反倒成了可爱的小插曲。

「……若论可能与否，答案是可行。认可。『忧郁』的魔女因子也并未与我适配，仅仅是持有而已。责任」

「那样的话，岂不是只要更换持有者就行？哈！还真是便于操作的东西呢。要是柯林特不小心弄丢了可就酿成大惨案了」

「弄丢确实是个问题，但被偷走或强行夺走也很可怕呢。从这个意义上来说，由柯林特持有倒是令人信服」

出乎意料的是，『忧郁』的魔女因子似乎是种相当危险的东西。

对于交给柯林特管理这件事表示理解的意见，佩特拉也表示同意。一直保持冷静、对任何事情都能应对自如的柯林特，或许正适合担任管理者吧。

不过──

「这份职责，这次或许还是交给其他人为好」

「换作其他人……但是，魔女因子可是非常危险的东西呢。我之前在『圣域』见过。是非常……非常可怕的东西」

「……风险，绝对是存在的。但是，如果能够顺利运用的话……」

「──唔、佩特拉酱，我是反对的哦」

对著提高声调、情绪化地最先表示反对的梅莉，佩特拉垂下了眉梢。

她一直担心着佩特拉，这我明白也很开心。毕竟佩特拉刚认识梅莉那会儿，曾试图让她喜欢上自己。

我认为爱意是钝化杀意的最佳武器。这个判断完全正确。

「虽然可能有点用力过猛了吧」

『先说好，我也和梅莉意见一致。虽然没让我听具体内容，但佩特拉已经付给柯林特先生某些东西了。要再付出更多的话，我们可没法让步』

唯有自己才能听见的幻听，让佩特拉切实感受到被珍视的滋味。

敢断言——幻影菜月昴虽是佩特拉一厢情愿的妄想，但还原度绝对高到连真正的昴在场都会说出同样台词的程度。

「幸好法兰黛莉卡姐姐和碧翠丝大人都不在这儿」

光是一个梅莉，就足以让佩特拉的心旌剧烈摇曳。

若是再加上法兰黛莉卡与碧翠丝的双重打击，恐怕连佩特拉都要溃不成军。要是加菲尔和奥托也在场会怎样？加菲尔定会气得大吼大叫，但奥托应该能理解我吧。

反正眼下阵营里最乱来的就是奥托，他根本没资格对佩特拉指手画脚。

怀揣着这般被宠爱的幸福少女自觉，佩特拉——

「——还是好好分工吧。要让所有人都能最大限度发挥所长」

２

——天神大人、佛祖大人、欧德・拉格纳大人。我发誓此生绝不重游故地。

×　×　×

佩特拉轻轻确认了下藏在怀里的方形盒子的触感，同时屏住了浅短的呼吸。

那个掌髻钗大小的盒子里，装着通过玩弄言辞、笼络周围人成功托付给我的『忧郁』魔女因子。

老实说，我本来想象会是更严密的、堪比特大咒物那样层层封印的东西，所以当柯林特掏出像戒指盒一样的箱子时，我还以为是在开玩笑。

然而，"求婚什么的，简直像死亡Flag一样呢"——这般开玩笑的余裕，早已被那匣子散发出的压倒性凶煞之气彻底碾碎。

那股令人作呕的强烈压迫感并未消散。──至今仍是。

「──不集中注意力的话」

そう言叶にすることで、ペトラは正気を保つよう己を强く戒める。──今日までペトラは、てっきり自分が强靭な精神力の持ち主だと思っていた。

即使读了『死者之书』也没有精神崩溃，即使意中人对自己丝毫不动心，也从未想过要放弃让她回心转意。我自觉以这个年龄而言，也算是经历了不少修罗场、闯过了不少刀山火海。

这样的佩特拉，面对魔女因子带来的破坏性全能感也不禁头晕目眩。

「不行不行，我……昴、支持我」

『佩特拉、加油！不能输！明明说了不要赌博结果还是赌了，要是这都输掉可就糟了！会讨厌你的！』

「那就、绝对不输……」

虽然靠脑补被喜欢的人鼓励来重整旗鼓感觉相当没救了，但实际确实有效，思念的力量真伟大。

魔女因子在恋心面前又能算什么呢。

与魔女因子的抗争，归根结底是精神层面的问题，所以思念之力成为特效药也是理所当然。──而这药效的好坏，再也没有比因此再也不能作为普通村姑的佩特拉更清楚的人了。

故而──，

「──火之八，贵族！花之三，乃是战士！」

震耳欲聋的嘶哑声音冲击着鼓膜，佩特拉猛地睁大眼睛，紧紧咬住后槽牙。

『压缩』发动，佩特拉的脑中浮现八×八的方格——采用沙特兰兹棋盘划分方式的战场指定位置上，强行插入指定的人材。

果不其然，眨眼间被带到战场的菲鲁特阵营二人──菲鲁特的随从加斯顿与协助者『豚王』多尔泰罗各自挥动刚腕，将亨克尔与『暴食』迎面揍飞。

「诶～？真的吗～？会有这种事啊～？」

以杂耍般的举动化解了拳击冲击的罗伊抬起那张令人火大的脸，将一直紧盯不放的拉姆的视线剥离，看向这边。

关于直接战斗的拉姆和梅莉、与菲菈姆和格拉西丝保持距离、处在能把握战场全局位置的罗姆爷、以及乘在他肩上的佩特拉的事情。

「不啊不要不要不要不要不要啊」

缓缓摇摆头部，罗伊的表情在喜悦与困惑之间来回切换。但最终他嚼碎了那份困惑，只留下喜悦的表情，说道。

「──佩特拉酱，是从什么时候当上大罪司教的？」

不愧是大罪司教。似乎能感知到魔女因子的所在地──不对，若是那样应该更早察觉这个机关才对。大概是通过判断『压缩』是权能，进而推理出谁能最娴熟运用它的位置的结果。嗯，完全不值得佩服。

「那种说法，超级难听啦。反正都要用难听的称呼方式，不如这样叫」

丝毫没有流露出对罗伊洞察力的警惕，佩特拉将手按在自己胸前，确认着怀中小盒的触感，吐出舌头说了声「略」。

「──『忧郁魔女』，佩特拉・雷蒂哦」

报上这个头衔的行为，在大多数场合都不受欢迎。

不仅自己报上名号不被允许，由他人提起更是绝对不行。那是无论有无觉悟，都会被世上所有对象憎恶的、如同诅咒般的称号。

但是，佩特拉却堂堂正正地，仿佛那是值得骄傲的事物一般报出了名号。

「因为，人家一点都不觉得害羞嘛」

毕竟，佩特拉侍奉的主人是『冰结魔女』，而佩特拉的心上人又是那位倾心于魔女的温柔杰出骑士。

３

──神啊佛啊欧德・拉格纳大人。我发誓今生绝不采摘美丽的花朵。

×　×　×

──『忧郁魔女』佩特拉・雷蒂。

「～～呜！」

面对如此自称的佩特拉的宣言，罗伊・阿尔法德感受到了高潮般的悸动。──既有对她竟做到如此地步的震惊，也有对她愿为自己做到这般程度的喜悦。

主动吸纳魔女因子，让自己成为『魔女』、『魔人』或大罪司教之类的存在，简直不可理喻。更何况罗伊曾听那个自称是自己母亲的怪物说过，『忧郁』魔女因子是无法与任何人适配的缺陷品。

实际上，从窥探到的尚显鲜活的『记忆』来看，佩特拉既无被魔女因子选中的理由，也感觉不到足以冲动性毁灭世界的破坏特质。她只是个坚强努力、程度有别却随处可见的普通少女。──正因如此，佩特拉这番超乎常理的决断才显得珍贵，令罗伊感动不已。

「最──棒了！出来一趟真是太好了──！」

张开双手，罗伊在狂喜中哽咽，感谢这份款待与相遇。

啊啊　居然如此大张旗鼓地自称『忧郁魔女』。利用魔女因子并非佩特拉的独断专行，而是『阿尔迪巴兰众』的集体意志吧。这可真是厉害。太离谱了。难道就没有哪个靠谱的常识人，列举些无聊的道理来阻止这种荒唐行径吗。

『忧郁』的魔女因子竟然被利用 这种不择手段的周密──正是强烈深刻巨大火热 除了罗伊他们着想款待的心意之外还能是什么呢

「啊~『忧郁』的魔女因子……妈妈可是超级想要来着呐」

想要想要、什么都想要。尤其是对爱情与获得爱情的手段饥渴不已的母亲，极度渴求着世界某处存在的『忧郁』魔女因子。若知道下落，母亲想必会非常开心吧。──当然，这般特别的佳肴，岂有分给旁人的道理。

「这可是饥饿孩子可爱的任性呀，还请多多包涵呐！」

承认欲求的化身、且最爱受到他人尊重的母亲、若是知道罗伊优先自己胜过她、会暴怒成何等模样可谓一目了然。

曾一度因母亲如此任性而烦不胜烦、但如今的罗伊心境已与往昔略有不同。——哪怕是母亲那任性妄为又自以为是的病态自恋、他似乎都能以无可替代的个性予以尊崇的心境。

就在这时——，

「土之六、女王！阳之六、猎人！阴之五、贵族！」

×　×　×

——神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生绝不在人前落泪。

×　×　×

呼应着巨人族老人的指示、佩特拉的双眸微微泛起光芒。

并非实际发出光彩。而是因分神于使用生疏的权能所致、能看出是其猛然用力的瞬间。虽是平时无需在意的细微习性、但在瞬息决胜负的战斗中、这即便是关乎生死的情报。

在罗伊的视野中，拉姆与猪人、以及骑乘饿马王的梅莉的身影消失了。──而在消失的同时，以三方包围罗伊的形式现身，并发动攻击。

那个时机，通过佩特拉眼中的光芒就能一目了然。唯独这点，并非战斗职的她，是无法归咎于她的不可抗力。

当然，这类厨师的独门手法所带来的影响，也被美食家们视为享受美味的诀窍。

「好啦好啦，打扰一下啦──」

攻击即将命中之际，罗伊在胸前双手合十。──瞬间，如同被左右强力挤压的沙堆般大地隆起，切断了拉姆与猪人对罗伊的视线。将二者交由大地应付，罗伊将意识集中到最嘈杂的婴儿哭啼声上。

即使不回头也能感知到涌入脑后的视野，那里，载着梅莉的饿马王骨枪──以及配套飞来的基尔提拉乌怪臂正挥舞而来。

大幅度倾斜身体，回避、回避、再回避，罗伊舔了舔嘴唇。

『压榨屋』菲格多尔是使用从自己视野两端到正中央都被紧紧压碎的异能专精活埋的杀手，而『千面圣女』耶尔娜则拥有上下左右三百六十度、绝不遗漏哀叹悲泣弱者眼泪的广阔视野与心胸。──但是，『魔兽使』梅莉的能力，也绝不逊色于他们。

「────唔!!」

面对沃尔加姆群、砂海饿马王、以及名为『漆黑森林之王』而声名显赫的基尔提拉乌，梅莉接连不断地驱使着魔兽们的手腕让罗伊连感动的喘息都做不到。操控着角未折断魔兽的梅莉手法虽已通过『记忆』预习过，但在普雷阿迪斯监视塔时未能亲身体验其真正价值，所以能看到实物实在令人兴奋不已。

「生来就拥有那种加护的话，想必人生一定波澜万丈吧？你是过着怎样的人生，告诉我们嘛，梅莉！」

「……问我过着怎样的生活啊，这话，之前昴哥哥和爱蜜莉娅姐姐也对我说过呢」

「嘿诶？然后呢然后呢？」

一边灵巧地躲过饿马王的骨枪和基尔提拉乌的利爪，一边瞪着舔舐唾液的罗伊，梅莉带着充满敌忾心与厌恶的表情做了个鬼脸，

「刚才那些爱啊啥的谈资也是这么回事哟，说到底重要的不是说什么而是谁来说呢！」

面对这无从辩驳的真理，罗伊「哈呵！」一声被将了一军。

在罗伊身后土壁被猪头人击碎，头顶上消失又现身的拉姆正坠落下来。正面背后头顶，被三维包围的罗伊胯下与两胁的空间发生扭曲，埋没于历史阴影、终被吞噬的『魔弄师』亚尔杜雷的魔技发动──魔法生成的炎与冰与土枪瞬间完成瞄准。

目标是梅莉与猪头人，还有拉姆──但她不见了。

×　×　×

──神明大人，佛祖大人，欧德・拉格纳大人。我发誓这辈子绝不帮人擦眼泪。

×　×　×

「老是跟丢拉姆。不如扔掉？你那对眼睛」

──在的。

近乎贴身拥抱的极近距离处，现出了拉姆纤细的身影。

「嘻嘻嘻嘻嘻嘻嘻嘻嘻──！」

──『压榨屋』×『千面圣女』×『魔弄师』。

甚至连融合了全新理外之人力量的他们都更胜一筹，从多角度逼近的三人，知晓这一切是何人造就的罗伊喉咙发出了高鸣。

令喉咙震颤的并非愤怒，而是欢喜。因这跃动，心中的扑通扑通停不下来。

任由那份悸动驱使，罗伊将一度瞄准的三属性长枪重新校准，令其相互冲撞，借助产生的爆风与水蒸气，迫使拉姆等人重整态势。

「────」

瞬间，他瞥见视野尽头、远处的佩特拉眼神骤然专注。

『千面圣女』的救赎之眼没有错过再度发动的『忧郁』权能的预兆。若能掌握其消失与再现的时机，形势将一口气倒向这边──刹那，他倒吸一口气。

「以为是为了避免受伤才『转移』的？」

炙热的蒸汽强迫对方选择转移，本应消失的女声从蒸汽另一端传来。

遮蔽视野、必定造成烧伤的白色热浪被粗暴地撕裂，从中冲出的是拥有淡红双眸的主人──虽说凭借风之加护减轻了伤害，但对方故意选择承受攻击的思维方式让罗伊措手不及。

「──不、不仅如此」

让罗伊脑中排除承受攻击选项的，是此前显露的『转移』征兆。

他一直将某个现象作为信号——确保自身始终处于『千面圣女』视野内，并借此判断权能发动时机。那个信号确实显现了『转移』的征兆。

但假如，连那一点、甚至连非战斗职业导致的不可抗力都是陷阱的话。——正当罗伊如此思考时，至今仍与他四目相对的佩特拉眨了眨眼。

带着满是俏皮、犹如将男人玩弄于股掌之中的蛊惑微笑。

「──『忧郁魔女』、最──棒──啦──！」

就在承认敌人卓绝实力的瞬间，罗伊・阿尔法德的『暴食』觉醒了。

畅快的呼喊在脑中迸发，无数选择枝在罗伊脑内分岔闪耀。

解放积蓄的『记忆』宝库，从杂乱堆砌的无尽财宝中寻求闪耀之物，寻求沉眠财富在这一刻等待已久的啼哭。

「────」

──目前，最大的焦点在于导致『蚀』失败的那位待客之身的真面目。

罗伊对拉姆发动的『蚀』失败了——那是对企图吞噬『记忆』而将手伸向灵魂之人所施展的。

但她的确是拉姆。这点从刚吞噬的新鲜『记忆』中也很明确：『记忆』的来源称她为拉姆，周围其他人也称她为拉姆，甚至连她本人自称也是拉姆——她彻头彻尾就是拉姆。

尽管如此，以拉姆这个名字却未能满足『蚀』的发动条件。在这种情况下，最可能导致『蚀』失败的原因是──

「──真名，被更改了」

发动『蚀』需要的是从欧德・拉格纳管理的灵魂名册中窃取目标的准备。因此目标的名字必须是欧德・拉格纳所记录认定的那个。

许多情况下，那是在出生时命名之际进行的誓愿──当那份祈祷传达之时，真名便被铭记于堪称伟大虚头的欧德・拉格纳之中。

基本上，一旦确定的真名无论本人如何自我认知都不会改变。欧德・拉格纳所认可的、极少数例外是──

「──拉姆・梅札斯」

「──呜」

对准突破蒸汽、试图将一击送达此处的拉姆，罗伊抢先触碰到了。

真名变更最多的理由是源于『婚姻』。──并且拉姆让梅莉称呼自己为夫人。从『记忆』来看，拉姆心中思念着谁也毋庸置疑。

确信了这一点，罗伊对睁大淡红双眸的拉姆──不，是对拉姆・梅札斯的灵魂发动『蚀』，意图啃食她的『记忆』，将她毫不保留地享用殆尽──

「我开动──噗欸」

瞬间，仿佛被塞了满口污物般的感受，让罗伊瞪大了眼睛。

那是『蚀』失败的证明、全身因剧烈排斥感而颤抖，本该迎接盛宴的心理准备被从内部撕裂的罗伊的思考被不合理的疑问所支配。

为何、为什么、理解、结婚、拉姆、真名、疼妹妹、品味差、边境伯、专一、性格恶劣、优秀、可靠、唯独品味差、性格也恶劣、结婚、热情──。

「──偷看了奥托的『记忆』？真蠢呢」

「啊──？」

「想趁着这种紧急状况，以为拉姆会安分当罗兹瓦尔大人的伴侣？──若是真正了解拉姆，就不会产生的误会呢」

面对微微咧开嘴唇的拉姆的嘲笑，罗伊理解了。

故意让对方称呼夫人也是，依靠亲信的『记忆』引导至错误结论的误导──事实上，罗伊已经把低风险的重新开始选项从脑中抹去，对确信能吞噬的高回报的拉姆的灵魂伸出了舌头。

若是没有吞噬奥托・苏文的『记忆』，就不会做出的判断。

「算是替奥托那份，暂且」

伴着宣言袭向罗伊・阿尔法德的，是拉姆裹挟旋风的拳、猪头人岩石般的铁拳、缠绕爆炎燃烧的骨枪与凶兽的刚臂。

４

──神明大人佛祖大人欧德・拉格纳大人。我发誓这辈子绝不再提当年勇。

×　×　×

「──你他妈也算个当爹的，少对小鬼出手啊!!」

比起直击面门的拳头，这句话更刺痛对方的内心。──目睹这一幕的罗姆爷，正是如此想象着亨克尔所承受的痛楚。

凭借自身抗打能力展开的先手战术，亨克尔本想借此反击菲菈姆和格拉西丝，却在即将得手时被加斯顿──准确来说，是被那位运用『压缩』将加斯顿瞬间移送至战场的少女的巧妙调度彻底阻止。

「真是的，够厉害的啊……」

确认摆脱对方擒拿的双子姐妹安然无恙的同时，罗姆爷悄然在意的是坐在自己肩上的少女——佩特拉的侧脸。

「────」

那双硕大圆睁的眼瞳眯细起来，佩特拉收紧可爱脸庞上的双颊，认真的视线毫不松懈地投向两处战场。

一边是『暴食』罗伊・阿尔法德与背叛王国的剑士──『背剑者』亨克尔的战场。原本那里还有敌人的主谋阿尔德巴兰及其随从忍术，甚至包括了向其臣服的『神龙』波克肯尼卡的身影。

瓦解那群危险分子，制造各个击破的战况。为此制定的计划以精通『忧郁』权能的柯林特的意见为核心，但成功的前提是全员团结一致，而掌握成败关键的无疑正是佩特拉。

若没有她，这场战斗甚至无法开始。──如今亦然。

「──呜」

坐在罗姆爷肩头的佩特拉咬紧嘴唇，爪子深深掐进他的肩膀。少女的指甲虽不以为痛，但她下意识这么做时的心中煎熬却超乎想象。

让人成为『魔女』和大罪司教的魔女因子，将其置于身边的负担，除了当事人以外无从知晓。而且佩特拉所担负的职责，作为候补罗姆爷的名字也曾被提及。

虽然直接战斗力匮乏，但凭借机灵和判断力，是适合站在战场上的立场。

罗姆爷和佩特拉正是如此，虽然最终阵营差异成为了决定性因素，但佩特拉的职责本是可能由罗姆爷肩负的。

因此，罗姆爷心中下定决心，这场战斗夺回菲鲁特虽是首要目标，但第二目标是为佩特拉竭尽全力。为了让佩特拉的负担能减轻些许，为了让战况判断与指示不出疏漏和失误，他要全力以赴。

「──花之三，女王。雷之二，贵族。花之五，猎人」

唧哩地，俯瞰着战场的同时，罗姆爷向肩上的佩特拉发出能让她听清的指示。每次佩特拉接收到指示并行使权能，肩上的爪痕就变得更深、数量也增多了。

基本、『压缩』有机会登场是在与『暴食』的战场上。

罗伊似乎察觉到了罗姆爷等人参与了战斗布局，但拉姆的战术走位极其精妙，持续吸引着敌人的注意力以免我方受到伤害。

即便算上『压缩』仍是千钧一发、进退拉锯的攻防持续着，这是因为『暴食』的手段与底牌数量众多，但另一边的战场却在手段与底牌的极端匮乏上形成鲜明对比。

「──唔」

连痛呼声都被打击声淹没，亨克尔持续遭受着狂风暴雨般的殴打。

菲菈姆和格拉西丝姐妹中加入了加斯顿，以速度扰乱对手的双子再加上刚腕的助力，此刻上演的已是近乎私刑或制裁的单方面暴力。

但对方仍未屈膝。菲菈姆她们也无法松懈攻势。

无论哪个战场，要打破僵局都需要投入一颗石子。——正当我这么想的瞬间。

「——罗姆爷爷」，如此呼唤的佩特拉与罗姆爷的视线对上了。

「────」

视线的交错，仅凭这一点罗姆爷就明白佩特拉和自己想到了同一处。连点头确认的时间都吝于花费，罗姆爷在最关键的刹那紧盯战局。

然后──

「阳之五，女王──！」

指令脱口而出的同时，佩特拉按在罗姆爷肩头的手猛然发力，圆睁的双眸发动『压缩』──刹那攻防过后，罗伊被拉姆等三人的联手攻击贯穿。

「──得手了！」

『暴食』的矮小身躯被狂风裹挟，承受著『豚王』与两头魔兽的攻击倒飞而出。罗伊喷洒著大量鲜血被击飞至半空，无疑遭受了重创。

致命一击命中前夕，罗伊虽试图对拉姆发动『暴食』权能，但未能奏效而产生致命破绽亦是关键。──布下此局并成功实施的拉姆之胆识，以及提出建议的佩特拉之构思，令罗姆爷再度惊叹。

「纵使能想到改名之法，后续的构思才是真正困难之处吧」

更名后的拉姆・雷蒂。──乃是经过正式手续，成为佩特拉・雷蒂养女的存在。

阿斯特雷亚领与梅札斯领、只要具备领主及其职务的代理职能即可利用的制度、通过反向利用该制度的收养关系、原本可能被『暴食』盯上的前线成员全体都已改名。只因这是靠所谓抽签决定的毫无规律可循的组合、此战期间『暴食』绝无可能探出我等正式姓名。

那便是、为了背叛大罪司教企图的『阿尔德巴顿队』奇策。

「但这下就……」

局势已动。正是为实现打破胶着状态的渴求一着、罗姆爷握紧了硕大的拳头。

并乘此势头、欲将另一侧局势也推动而投去视线──

「……谁也不准动！若珍惜这家伙……这位的性命的话！」

──那边也发生了状况变化、面临着亨克尔将剑抵在被反剪双臂的菲鲁特颈前的最恶困境。

５

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓这辈子再也不讲喜欢的故事了。

×　×　×

「至今抱歉了。从各种意义上、都给大叔添了太多负担」

没错阿尔德巴兰前来道歉的时候，正是在菲鲁特谈话的亨克尔即将失控之际，被他毫不留情地用暴力揍趴之后的事情。

说实话，对于自己差点酿成大错的事实心知肚明，挨揍也没资格抱怨——亨克尔如此反省着。不可能有不接受道歉的选择。

不过，唯独菲鲁特察觉到的事实——那件事，绝对不能就这么放着不管。

持续沉睡的亨克尔之妻，卢安娜・阿斯特雷亚。——这位亨克尔最爱的女性之所以长眠不醒，其原因正在于他们的儿子莱因哈鲁特。

「嘛，等等呗。大叔我和菲鲁特小姑娘之间具体发生了什么我就不细问了。但我说过了吧？光让大叔你一个人承担负担真是对不住了，之类的」

「……完全搞不懂你在说啥。道了歉，然后又能怎样」

「当然，我不会因为道了歉就说今后也请继续忍耐啊。首先，菲鲁特小姑娘的事由我这边来处理」

「说是处理……」

「不会干危险的事啦。虽然说不定会有点粗暴就是了」

面对说着这话耸了耸肩的阿尔德巴兰，亨克尔绷紧了脸颊。

虽然是个摸不透在想什么、让人捉摸不透的男人。即便如此，我也理解他正以失去普莉希拉的悲伤为动力，开始与世界为敌。

阿尔德巴兰的心中，确实存在着对那位强烈的『太阳姬』的挚爱。

然而、阿尔德巴兰还保留着最低限度的良知——不至于为此牺牲一切。──感觉那已经彻底消失、枷锁也被解开了。

「你……你到底想干什么」

「不会对大叔你不利的。只是、有件事想确认一下」

不知为何、咕噜作响的喉咙里、亨克尔感到了强烈的干渴。似乎想听又不敢听那句话的后续、这是只有胆小鬼才会拥有的某种预感。

对亨克尔的内心波动佯装不知、阿尔德巴兰说出了那个所谓的问题。

那就是──

「十五年前、从城中被绑架的王族的名字──」

「──菲鲁奥雷・露格尼卡」

说出这个名字对亨克尔来说──不，在露格尼卡王国中不知何时已成了类似禁忌的认知。

十五年前、从露格尼卡王城遭到绑架，自此下落不明的王弟之女。

在王国漫长的历史中，并非没有遭遇不幸人生的王族。但生于祝福之中，其成长与结局却无人述说的存在，唯她一人。

露格尼卡王国第四十一代国王兰德哈尔・露格尼卡之弟，福尔德・露格尼卡的女儿，十五年前被指控由亨克尔绑架的王族。

不过，那绑架嫌疑实属诬陷——然而阴差阳错，最终亨克尔还是对理应宣誓效忠的王家，对恩重如山的福尔德，犯下了不可挽回的不敬之罪。

那是对王家与友谊的背信行为，其性质比背叛王国更为明确。

「──伊塔达基马斯（我开动了）」

眼前正在进行的，罪孽深重且丑恶的仪式。

从阿尔德巴兰的提问中，亨克尔早已预感到了这一幕，或许甚至有所期待。即便心知这场仪式曾引发诸多悲剧，仍旧如此。

因为若能成功，亨克尔便无需亲手杀她。

「承蒙款待了」

手与手相合，在宣告仪式结束的罗伊那小小的背影中亨克尔回过神来。由于太过想要移开视线，因沉溺于思考而字面意义地错过了眼前的行为。

每当重复着骑士不应有的行为，即便如此仍一边觉得有着纠结部分的自己的心很滑稽，亨克尔与愉快嗤笑的罗伊交换着走到前面。

然后──，

「──菲露奥蕾大人」

单膝跪地，亨克尔对她如此称呼道。

对于那声呼唤，她眨动绯红的双眸，从正面看着跪下的亨克尔。

「────」

在沉重的沉默中，亨克尔感到了喉咙的──不，是灵魂的干渴。

到底，在期待着什么样的回答呢。如果被回答那是自己的事，就意味着仪式的失败。如果被回答说不知道那是什么，那样的话亨克尔果然也会苦恼吧。

果然，对于连自己都没有答案的亨克尔，其答案是──，

「那是，哪位的事情呢？　不，说起来……」

「──啊」

「──我，是谁呢？」

意味仪式成功的这句回应，最终却伤害了亨克尔，令他陷入懊恼。

「菲尔奥蕾，那是我的名字……感觉不太适应呢」

被夺去『记忆』的菲尔奥蕾，其态度简直判若两人。

原本从举止动作、说话方式到表情控制都浸透著粗俗与教养匮乏的痕迹，此刻却像是谎言般——她携带著与王族相称的优雅与柔和，令亨克尔惊愕不已。──不，反倒说，至今为止的举止才是错误的。

倘若没有十五年前的悲剧，她本应是受众人爱戴的王族一员。

「不过代价嘛，可能早就跟王族其他家伙一样病死了也说不定」

正当亨克尔涌起这番感慨时，阿尔德巴兰说了句刻薄话。

但事实确是如此。那种仿佛针对王族而来的原因不明的瘟疫，若菲尔奥蕾当时身在城中，恐怕她也难逃毒手吧。──这意味著什么，亨克尔似乎隐约察觉到了什么，却闭上眼拒绝直视。

亨克尔已经连身心都撑到极限了。明明毕生心愿的实现就在眼前，接二连三追加的冲击性事实却让内心无法承受。

「怎么了，您有什么烦心事吗？」

对着下意识用手遮住脸的亨克尔，正是菲尔奥蕾本人如此搭话道。

『记忆』缺失、自身明明正处于更加令人不安的境地、即便如此仍关心他人的姿态中、亨克尔确实看到了露格尼卡王家的血脉。──老好人、优先他人胜过自己、不像当权者的执政者正是『狮子王』的血脉。

「如果？」

「──。不、没什么。感谢您的关心」

「是吗。那样的话就太好了。虽然算不上能帮上什么忙，毕竟一直都只是在给您添麻烦」

这样说着，菲尔奥莱像是松了口气般露出微笑，亨克尔的胸口阵阵作痛。

『──我不是保证过了吗，小伊。你的愿望一定会实现的。像你这样始终真诚面对心愿的人，除了哥哥以外我再没见过第二个啊』

突然闪过脑际的，是曾经伴随着笑容抛来的温暖话语。

身份悬殊 本不该妄称对方为友 但如今想来 在生来就被寄予厚望这点上 我们算是有着相似烦恼的同志

此刻 亨克尔确实从那关切着自己的绯红双眸中 窥见了故人的影子

同时也确信了残酷的真相──当『暴食』权能发动时便已证实　她确凿无疑正是菲露茉蕾・露格尼卡

既然如此──

「……这样一来 王选也该结束了吧」

「这又从何说起啊 大叔」

「还有什么从何说起 进行王选的理由 不就是为了寻找适合王位的『继任者』吗 说白了 就是因为王家绝嗣才采取的次优方案……既然现在知道根本没绝嗣 那些人肯定会立马变卦」

所以 王选就失去意义了 根本没有理由再让王座空悬一年半之久

讽刺的是 正因为普莉希拉死去 暴走的阿尔德巴兰让『暴食』越狱 而被吞噬『记忆』前的菲露茉蕾刺中了亨克尔的要害 真相才得以大白

简直就像是为了让菲鲁奥雷登上王位，连世界都为此安排妥当了一样。

当然，亨克尔并没有说出什么没神经的话，比如连普莉希拉的死都是为了这个——而且，如果菲鲁奥雷能登上王位，那正是他所期望的。

只要卢安娜能醒来，之后所有事情都能顺利解决，这就是亨克尔的愿望。妻子醒来，『嫉妒的魔女』离去，菲鲁奥雷登上王位。——简直是再好不过了。

「奥尔塔，这是最圆满的处理方法了。有意见吗？」

「……勉强算是，在我能妥协的范围内又不伤害小姐的、毕达哥拉斯式的解决方案吧，奥莉根。只是——」

「只是？」

『这个计划，是奥莉根你一个人想出来的吗？总觉得不太像你的风格啊』

「────」

就在亨克尔这样说服自己的同时，关于如何处置菲鲁奥雷的问题，阿尔德巴兰和『神龙』正那样争执不休。

原本，强烈支持菲鲁奥雷存在的正是『神龙』。虽然和阿尔德巴兰像同一个人似的意气相投，但唯独对她的处理方式意见分歧。而其原因，也在菲鲁奥雷被确定为菲鲁奥雷之后得以理解。

据说是因为露格尼卡王家与『神龙』之间缔结的盟约，将两者联系在了一起。

『──。嘛，也罢。实际上，大叔所背负的问题就此解决了，对吧。但接下来，可是有要带着什么都不懂的菲鲁奥雷酱四处走的问题存在啊？』

「──呃、那是……」

「若是那样的话，根本不成问题哦～。对吧，阿尔大人？」

对于冷不防地从自己身旁探出脸来的八重，亨克尔倒吸了一口气。

她或许是看透了亨克尔内心的不安，向这边投来仿佛嘲弄般的秋波，然后像是向阿尔德巴兰撒娇般地如此催促道。

八重那种小瞧亨德尔的态度是常有的事。并无违和感。

有违和感的，是阿尔德巴兰对待她的态度。

「……是啊。和大叔也约定好了」

「约、定？」

「菲鲁特……不对，菲露托莉大小姐的事，由这边来处理哦」

无法理解这句话的含义，亨克尔感到困惑。

约定也好处理也罢，都已是完成之事。被『暴食』之力吞噬了此前『记忆』的菲露托莉，对亨克尔而言已非威胁。

即便如此──

「──奥尔・纱幕」

阿尔德巴兰以平淡却分明带着无情的态度，在困惑的亨克尔面前对菲露托莉执行了那份『处理』。

那般果决──不，该说是好坏皆抛的决绝态度，令亨克尔狼狈不堪。

阿尔德巴兰与八重关系的变化、『神龙』对菲露托莉的情感、『暴食』被允许的行动限制扩展、曝光的菲露托莉真相。──虽绝称不上团结，但亨克尔正逐渐感受到日益扩大的裂痕与偏差。

在此情形下，亨克尔决心至少自己要保持清醒。

无论陷入何等窒息的困境，在目的达成前这个团体若分崩离析，困扰的终将是亨克尔。

所以──

「──就算只有我、也要好好地」

如此、『处置』完毕后的菲鲁特──变成只有手掌大小的、黑色球体的她被接了过来、亨克尔如此立下誓言。

立下了誓言。──明明立下了誓言。

「不想让菲鲁特大人受伤的话、就退下……！」

陷入困境的亨克尔将那份誓言与决心都抛之脑后、把长大了的菲鲁特反剪双臂架住、把剑抵在她纤细的脖颈上。

「菲鲁特……呜」

对于亨克尔的暴行、体格健壮的男人悔恨地用另一个名字称呼菲鲁特。

不停攻击着的菲菈姆与格拉西丝也停下了动作、视线中混杂着愤怒与轻蔑、或许还有忧虑与困惑、与亨克尔对峙着。

在她们看来、惊讶恐怕是双重的吧。

如同时而出现时而消失的她们一样、菲鲁特突然出现在亨克尔手中、而且亨克尔还用别的名字称呼她。

但无论是自己的拼命劲儿还是她们的困惑，比起突然被拽到这种场合、最后还沦为人质的菲鲁特的震惊程度，都只能算是小巫见大巫吧。

「很抱歉，我不想动粗。请配合一下」

亨克尔发自内心地厌恶着对身为人质的菲欧蕾说出这番话的虚伪自己。

他努力过。为了不让菲欧蕾卷入这场突然爆发的战斗，亨克尔尽了最大努力。但他放弃了。一如既往，努力没有结果。

所以、我打碎了阿尔德巴兰托付的黑球、放出被封印的菲尔奥莱、将剑抵在她脖子上、威胁出现的敌人。

「别动、你不想让这位受伤吧」

就这样染指了最恶劣的行为，却依然虚伪地对菲奥蕾尽礼数，这正是亨克尔心中还残留着一丝良知的证明。

在无法确信她是菲鲁奥蕾的期间，还能将那美丽的金发和赤瞳等王族证明当作单纯的偶然相似而忽视。但既然已经确信她就是菲鲁奥蕾，亨克尔便无法再像之前那样对待她了。

若问是否因对象不同而改变态度，确实如此。——亨克尔自幼被父母教导要对露格尼卡王族之人尽忠。

「──」

作为迟来王牌的非尔奥蕾，被抬起脸的她喉咙里发出细微的呜咽。

刚从那个黑球中解放出来的菲鲁奥蕾，或许是意识尚未恢复清晰，又或许是因局势骤变而不知所措，只是任凭亨克尔摆布。

虽令人心焦，但胁迫已然生效，对方的动作也颇为迟钝。亨克尔便想趁此机会，一边担心着消失的阿尔德巴兰等人，一边先确保与同陷战场的罗伊共同安全──

「──菲鲁特!!」

与先前那个体格壮硕的男子挤出的声音不同，这声呼喊充满力量。

与重要之人重逢的喜悦、以及可能正是亲爱之情的反面所致的微怒、对其身体的担忧与势必带其归去的激昂，这些情感混杂在一起的呼喊声，高昂地响彻战场。

「────」

听到这声音，亨克尔怀中的菲露奥蕾微微动弹。

即便处于『记忆』缺失的状态，即便不明敌我立场，强烈的感情若是冲自己而来，或许终能传达。她缓缓眨动那双亦是王族凭证的红瞳，与远方向自己呼喊的老迈巨人对上视线。

她双唇轻启，编织话语。

那是──

「──罗姆爷！让加斯顿他们退下！那玩意儿要来了!!」

那是将方才还属于王族的娴静姿态抛诸脑后，粗犷而有力的──仿佛因重要之人的呼唤，将以蛮力夺回本应失去的『记忆』一般的、雄壮凛然的『金狮子』的呐喊。

６

──神啊佛啊，欧德・拉格纳大人。我发誓这辈子绝不用爱称喊人。

×　×　×

──当然、菲鲁特能够向同伴诉说困境，并非亨克尔所想的什么奇迹般的感人故事那般童话。

正如不仅是菲鲁特，还有那些遭受其害的当事人及相关者们的悲剧至今已充分说明的那样，『暴食』权能的残酷无情。如此种种悲剧的根源，不可能唯独在菲鲁特时仅凭心绪问题就能解决，岂有此理。

因此，菲鲁特能从『菲露奥蕾』变回『菲鲁特』的理由简单明了──原本菲鲁特就并未被罗伊吃掉『记忆』。

「接下来这事儿啊，好像我们非得吃掉菲鲁特小妹的『记忆』不可啦。──菲鲁特小妹，不跟我们合作吗？」

罗伊说出这话，正是在阿尔德巴兰决定对察觉多余事实、可能给集体行动带来裂痕的麻烦人物菲鲁特进行『处置』之后。

看样子是打算连菲鲁特察觉的多余事实一起，让罗伊吃掉其『记忆』，顺便连傲慢无礼处处顶撞的菲鲁特的人格也一并处理掉。

按菲鲁特的说法，失去『记忆』的时候就已经等于被杀了。就这样还非要坚持贯彻不杀原则，阿尔德巴兰的想法我可不敢苟同。

「可是，就算这样也没道理让老子喜欢上你啊。首先，凭什么要老子跟你这种家伙合作？」

「哈哈~嗯，你这态度真让人受不了啊~。不过不用担心哦，菲鲁特妹妹。说到底缜密的作战啦完美的计划之类本来就不是我们的风格嘛。咱想拜托菲鲁特妹妹的只有一件事——被吃掉的『记・忆♪」

「……继续说」

闭上一只眼睛的菲鲁特，从罗伊的话中找到了值得一听的价值。对此反应罗伊「这才对嘛！」发自内心愉快地笑道，

「一直陪着面具大叔们倒也不是不行。但要是啥都不做的话，最好的结果也就是在关键时刻被当成弃子处理掉……你看，连咒印都被刻上了，我们现在的处境也挺不妙啊」

「所以，你这处境不妙的家伙要和我这状况危险的家伙互相帮助吗？」

「对对对！菲鲁特小妹就假装失去了『记忆』，继续专心寻找反击的机会吧。我们会趁着菲鲁特小妹可能制造的破绽，尝试从被囚禁的大罪司教这个身份中脱身」

「──。要是我把这些告诉头盔佬他们，引发你们内讧就能轻松除掉你，这种可能性也不是没有哦？」

「对对对就是这种路子！尽管放马过来呀」

罗伊啪啪拍手欣喜若狂，菲鲁特本想深究其真实意图，却立刻放弃了这个念头。毕竟若对方有意隐瞒恐怕也看不透，而且在菲鲁特眼中罗伊的发言完全不似作伪

况且实际上，从菲鲁特的立场来看这反而是求之不得的提议。──照现在这样发展下去，菲鲁特只会束手无策地被夺走『记忆』

「不过啊，要想吞噬我可是需要知道我的名字的。你兄弟就是因为不懂这个才吐得稀里哗啦的吧」

「嘛~，确实是这么回事呢。不过菲鲁特酱你心底某处也明白吧？自己的真名和王国悲剧中闻名的那位公主殿下是一样的吧」

「────」

「啊~，还是说你想确认一下呢？如果凭那个名字能让『蚀』成功的话，我们的『记忆』确实会被夺走，但也能得到证明呢。怎么样？」

「哼，廉价的挑衅呢。——我奉陪」

对着伸出懒洋洋的长舌头、窥探这边脸的罗伊，菲鲁特说道。

自己究竟是什么人。——这种无聊的问答对菲鲁特来说根本无所谓。她知道有人想让她觉得这并非无所谓，但刚才那套『记忆』被夺走就等于被杀的理论是一样的。

菲鲁特早已作为名为『菲鲁特』的人积累了人生。抱歉，无论开局如何，并非『菲鲁特』的人生在开始之前就已经结束了。

那种东西不需要。所以，她才顺势加入这令人不爽的『暴食』的企图。

「赢家只会是我」

「咯咯、啊哈哈！　我就知道你会这么说！　我一直相信着！　不过，为了不让菲鲁特酱一个人独占胜利，我们也会最大限度买个保险哦？」

「保险啊？别说那么逊的话。要赌就赌一发定胜负」

「那份勇猛虽然很帅让人憧景啦，但对我们来说重要的不是矜持或勇敢。──弱肉强食，仅此而已」

这么说着，罗伊像是庆祝密约成立般咬得牙齿咯吱作响。

那之后，罗伊如约假装吞噬了『记忆』，保护了菲鲁特的自我。

菲鲁特也同样遵守了与半信半疑的罗伊之间的密约，演出了一个没有『记忆』──对一无所知的王族、菲露欧蕾・露格尼卡的模仿秀。

「抱歉啦，模仿对象我能想到的只有库珥修姐姐」

作为被夺走『记忆』的受害者，菲鲁特最先想到的就是库珥修・卡尔斯腾。参考了态度和说话方式骤变的她而扮演的菲露欧蕾，似乎颇得阿尔德巴兰他们、尤其是亨克尔的欢心。

不过，扮演菲尔欧雷的机会既不多也不长，菲鲁特很快就因阿尔德巴兰的魔法被封进了奇妙的黑色球体中。球体内部非常憋闷、绝非舒适之地──但也曾因此得救。

多亏了扮演菲鲁特的那场蹩脚戏码，才没有露出破绽。要是菲尔特演技穿帮的话，『保险』就会启动——罗伊是这样威胁我的。

即使菲鲁特不采纳提案，也要设计成让她不得不采纳，为了防备她采纳后背叛而准备的、字面意义的『保险』。

那是──

「──从我的影子里滚出来!!」

被亨克尔扭住双臂，剑刃抵在脖子上的菲鲁特喊道。

这正是『暴食』大罪司教罗伊・阿尔法德为欺骗阿尔德巴兰等人脱身而准备的绝招『保险』与暗牌。

那是与『白鲸』和『大兔』齐名的三大魔兽最后一头──

「──黑蛇!!」

──自诞生以来，在这个世界上杀害生命最多的病灶魔兽『黑蛇』，因违反了既定的密约而产生反应，被召唤至双方阵营全面战争的战场之上。

７

──神啊，佛啊，欧德・拉格纳大人。我发誓这辈子绝不让任何人进家门。

×　×　×

对方设下的『保险』就是『保险』。──先说清楚，当初菲鲁特答应罗伊的条件时，也并非立刻就打算反悔。

那份威胁菲鲁特也是知道的，如果轻举妄动，不仅自己的性命难保，还可能给周围带来巨大的灾害。

因此，她本打算虽不情愿但暂且按罗伊的策略行事，扮演菲露奥蕾・露格尼卡，尽可能寻找阿尔德巴兰他们的破绽。当然，她心里盘算着要反过来利用试图算计他们的罗伊。

然而，菲鲁特的这番决心，不久便不得不改变了方针。

「──菲鲁特!!」

从封印中获得解放，感受着脖颈上钢铁的冰冷触感，菲鲁特全神贯注地把握着现状。首先浮现在脑海的是扮演菲鲁特的『保险』──无论罗伊是否在场，都必须防止可能发动的那个。在此基础上，寻找能让在场的阿尔德巴兰等所有人措手不及的良机。

这一切的心理准备，在听到熟悉的声音呼唤自己的瞬间便土崩瓦解。

「────」

虽然被紧紧束缚着，菲鲁特仍勉力抬起头，看见了。

战场深处，大声呼唤菲鲁特的，正是才分别两三天就已令人怀念的罗姆爷的身影。在欣喜的同时，她意识到自己正是为此而被当做人质，强行维系着即将剥落的菲鲁特面具──视线交汇了。

并非与罗姆爷。而是与他肩上那名少女淡蓝色眼眸的，交汇。

──瞬间，海量的信息以惊人的势头涌入了菲鲁特的脑海。

「──呜」

浊流般的思绪在菲鲁特那双红眸闪烁的内侧，争分夺秒地狂乱奔腾。

──看来战斗正处于白热化阶段，阿尔德巴兰和八重、『神龙』缺席的战场上只剩下罗伊和亨克尔展开全力决战，分割・奇袭战术，指挥得真不愧是咱的罗姆爷，莱因哈鲁特继续应付着『魔女』，还有，还有，另外，另──，

「──罗姆爷！快让加斯顿他们撤退！那玩意儿要过来了!!」

在无情的情报浊流中奋力游弋后，菲鲁特嘶声高喊认为这才是最佳方案。

即便因畏惧『保险』而继续维持菲鲁特的演技，陷入绝境的罗伊为自保而违背承诺的可能性极高。毕竟对方是大罪司教。约定被打破比被遵守更符合常理，这样想才更自然。

说到底罗伊从一开始就在撒谎。──什么和菲鲁特里应外合，趁阿尔德巴兰他们不备逃走纯属弥天大谎。罗伊从一开始就盘算着要将包括菲鲁特在内的阿尔德巴兰、八重、波克肯尼卡、亨克尔所有人一网打尽。

所以──，

「──那混蛋要从咱的影子里钻出来了!!」

就这样抢先罗伊一步的行动，没有丝毫犹豫或迟疑。

唯一可能存在的顾虑，就是无法应对『保险』的风险，但这份顾虑被在场的人员构成、特别是罗姆爷的存在打消了。

──只要有罗姆爷在，就没有办不到的事。

这个世界中许多人对于『剑圣』莱因哈鲁特・范・阿斯特雷亚所抱有的期待，菲鲁特却在这个年老的巨人身上寄托着。

故而──

「──是黑蛇啊!!」

即便从自己的影子里，汹涌的『死亡』洪流倾泻而出，菲鲁特的眼眸中，胸膛里，也未曾存在一丝一毫的恐惧。

８

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生绝不亲眼见证任何人的临终。

×　×　×

作为三大魔兽之一角，身为病巢之魔兽的『黑蛇』。

大致上来说，危害所有人类便是魔兽这种族的生态，但在这其中三大魔兽之所以被视为别格，纯粹是因为遵照那些魔兽的存在方式后，所造成的损害规模实在过于庞大。

──各国曾多次组织讨伐队，将其大半连存在一同抹消的雾之『白鲸』。

──以天灾般的食欲吞噬无数生计，乃至将悲剧也一并吞食的食害『大兔』。

与黑蛇一样，被称为三大魔兽的那些恐怖无需赘言。但与白鲸和大兔相比，黑蛇的存在仍显得格格不入且异常怪异。

如前所述，三大魔兽乃是造成远超其他魔兽危害的存在。──若严格遵循此条件，黑蛇则不应归为三大魔兽，而应被称为独一无二的大魔兽。

只因它曾毁灭过往存在的大国，令五大国缩减为四国，黑蛇所夺走的性命，纵使与白鲸或大兔相比也远超其上。

「呜啊──!?」

听闻黑蛇现身的消息，又目睹紧随其后的景象，罗姆爷不禁发出了惊愕的叫声。

刹那间自菲鲁特脚下影子喷涌而出的，是浓郁到足以看清实体的瘴气块──恰似影子本身昂首而起，那正是令一切生命本能地联想到『死亡』的凶恶无比之威胁的显现。

然而──，

「哎哟喂，那是什么眼神……！」

明明近在咫尺就能深刻感受到可怕魔兽的气息，但菲鲁特看向自己的眼神中却毫无恐惧只有信任，这让罗姆爷的心沸腾起来。

他强行压制住对老年人来说奢侈的惜命本能，想要回应那份期待。

「佩特拉啊！」

「在！」

刹那，应答的少女身体一跃，从罗姆爷肩头跳下。对聪明少女的判断微微颔首，罗姆爷凝视正前方──发动了『压缩』。

「────」

嗡的一声，仿佛将周围万物甩在身后的感觉震颤着罗姆爷的灵魂。

倘若过去罗姆爷──巴尔加・克罗姆威尔参与的众多战役中拥有这般力量，那么战术、胜负乃至历史都将截然不同吧。

目睹权能之力，切身感受到魔女因子时，不禁让人想起这些『如果』。或许这正是被魔女因子选中者沉迷力量、沉溺全能感而误入歧途，堕落成骇人存在的缘由。

而这正是──

「──」

佩特拉紧紧咬住后槽牙，用坚强的心忍耐着。

尽管时间短暂，但魔女因子无疑给她带来了相当大的负担。明明想立刻解放她，现实却反而强迫她行使力量。罗姆爷也不过是这令人憎恶的现实中的一环，实在可气。

正因如此，正因是强迫，至少要带回最好的结果。

「──雷之八，战士。花之八，兵士」

思维爆裂的感觉与厚唇编织话语是同时发生的。

×　×　×

──神明大人，佛祖大人，欧德・拉格纳大人。我发誓这辈子不吃最爱吃的东西。

×　×　×

遵照罗姆爷的指示，迅速做出判断的佩特拉用『压缩』将菲菈姆、格拉西丝和加斯顿三者拉回，抛向战场后方。与之交替，罗姆爷向前跃出同等距离，强行从仍被亨克尔钳制的菲鲁特身边撕扯开，试图再次撤离。

然而──

「太过分啦，不是说好一起逃的嘛──」

瞬间，黏稠般令人不快的声音与肉体被强行贯穿的讨厌声响重叠在一起。

伴随著迟来袭来的灼热痛楚，罗姆爷呻吟著，与刺入右侧腹部的贯手——其主人罗伊染血的狞笑对上了视线。

本应在先前列姆她们的联合攻击中受到致命伤的罗伊，此刻遍体鳞伤的矮小身躯被鲜血染得通红，却依然向我们露出獠牙。

「你这、对罗姆爷……！」

「我警告过了吧？这些家伙啊，连俺们说的话也根本不听啊！」

对著怒火中烧的菲鲁特咂嘴咬牙，罗伊扬了扬下巴示意身后。

冲天而起的黑色污浊之柱，莫说触碰，仅仅映入眼帘便足以侵蚀性命——所有生灵皆凭灵魂直觉感知到这份威胁。

并非虚张声势亦非恫吓，而是名为『黑蛇』的凶险传说确然降临于此。

「──唔呃」

强忍著侧腹被剜开的剧痛，罗姆爷的思绪飞转。

この场で対応しようとするのは下策も下策。何はなくとも黒蛇の邪舌の范囲外に逃れなくては。だが、ロイは当然こちらの妨害にかかるため、『圧缩』で逃れるのは难しい。ロイは黒蛇の魔祸を避ける手立てがあるのか、あるいは自爆覚悟の道连れ戦术か。それを止める最善手を、ひねり出せひねり出せひねり出せ──、" -> "试图在此处应对乃是下策中的下策。无论如何都必须先逃至黑蛇邪舌的范围之外。但罗伊显然会进行阻挠，因此难以用『压缩』逃脱。罗伊究竟是有避开黑蛇魔祸的手段，还是抱着自爆觉悟的拖人下水战术呢。快想出来快想出来快想出来──阻止它的最佳对策，

「──保护福尔德的女儿！」

就连罗姆爷自己也不明白，为何沸腾的思绪最终会得出这个结论。只是通往这个结论的思考过程被压缩到极限，呐喊着。

回应罗姆爷这声呕血般呐喊的，是一个男人。

「呜、啊啊啊啊──！」

伴着一声充满恐惧与颤抖的声音 剑光反射性地闪过 将正要扑向罗姆爷巨大身躯的罗伊斜向斩飞出去。

那道银光的凌厉程度甚至连挥剑者本人都感到惊讶 而对于因此得救的菲鲁特来说 这冲击简直如同天塌下来一般。

「你……」

「──！」

菲鲁特瞪圆双眼直盯着对方　亨克尔咬紧牙关伸出手

那冲击笔直地、并非朝着菲鲁特、而是推开了将她护在身后的罗姆爷的巨躯。遭到猝不及防的猛烈撞击、罗姆爷的身体被劲道弹开。

随后、在被迫退的罗姆爷与菲鲁特的注视之下──

「菲露托蕾大人、我──」

那混杂着混乱后悔与爱憎的表情、究竟能向谁如何形容呢。

复杂离奇到极致的唇瓣所编织的话语、究竟是想传达怎样的心情呢。

一切都无从知晓。──因为在答案成形之前、亨克尔・阿斯特雷亚便被倾泻而下的黑蛇这类污浊从头吞没、消失了。

「────」

沐浴着瀑布般的污浊、逐渐被不祥的黑色浸染的大地走向死亡。

树木枯萎、花草腐烂、水流浑浊冒泡。遭受黑蛇邪舌侵蚀之后、生机之色片甲不留、一切都被吞噬、唯独均等地遭到屠戮。

这自然、也包括被污浊劈头盖脸淹没的亨克尔。

「──混账东西！」

「啊嗯~太浪费啦！」

讽刺的是 面对这般景象 菲鲁特和罗伊都露出了不甘心的表情

但是，身为另一名当事人的罗姆爷并没有资格为此哀叹。因为他意识到，虽然亨克尔这次的拼命行动是因自己的喊叫所引发的。

进一步地，无论是否意识到这一点，罗伊的食欲都会立刻切换心情。

「菲尔奥雷・鲁格──「风之二，猎人！」」

如同涌水般致死的污浊涌现之中，罗姆爷的声音淹没了优先考虑食欲的罗伊的声音。

从飞扑过来的矮小身躯旁，罗姆爷扭身像是要远离菲鲁特般，向聪明的搭档发出了不是让他们撤离而是打开局面的指示。

×　×　×

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生绝不重返故乡。

×　×　×

「──唔!!」

「这孩子，连我都没把握能拦住呀！」

随着这声指示，巨躯凶兽与紧扒在它身上的梅莉现出身形。

咆哮与自暴自弃的恶言重叠，兽爪从正面抓住罗伊，『魔兽使』指着污浊的集合体，腹部用力大声怒吼。

「给我坐下!!」

雷鸣般的梅莉号令，向魔兽施加难以抵抗的冲动。

途端、地を这い、影を伝い、枝分かれしようとしていた汚浊の动きが乱れ、凶獣と入れ替わりに飞びずさったロム爷たちが黒蛇の射程から逃れる。逃れ、呼吸を再开、首だけで振り返った先にようよう汚浊の全身を视野に入れ──绝句した。" -> "就在此刻，原本贴着地面爬行、沿着阴影蔓延、正要分裂扩散的污浊动作陡然紊乱，与凶兽互换位置倒飞出去的罗姆爷等人挣脱了黑蛇的射程。脱险后刚重新呼吸，仅凭转动脖颈回头望去，终于将污浊的全身纳入视野──顿时哑然失声。

「────」

这并非魔兽那种可爱的生物，而是被称为『死亡』的现象。

从森林暗影中满溢而出的污浊汇聚成形，勾勒出如蛇体般的轮廓。然而那轮廓既非血肉亦非鳞片，不过是无数病灶偶然拼凑成了那般形状。

覆盖蛇体的鳞状肿块膨胀后炸裂，将乌黑的液滴如脓液般飞溅散布，其触及之物皆无声地腐烂剥落。勉强可称为头部的轮廓前端，如花瓣般绽开时，无数细丝状突起如舌头或触手、又似寄生虫群般蠕动。

那正是配得上『最悪魔兽』之名的、敲响生命警钟的存在。

若白鲸是从空中吞噬历史的存在，大兔是贪婪啃食地上生灵的存在，那么黑蛇便是令世界本身染病腐烂的毁灭灾祸本身。

「这认知大──正──确──！」

在罗姆爷因战栗而模糊的视野中，罗伊立于遭黑蛇污浊侵蚀的大地上高声喝彩。

同时，拖着长尾的巨躯魔兽全身喷血，承受来自正下方的掌击被高高轰向天际。

「影狮子酱──！」

被瞬间甩落的梅莉慌忙伸手，却无能为力。

被吹飞的魔兽基尔提拉乌不断旋转着，束手无策地坠落在黑蛇扩散污浊的大地上，其巨躯被邪舌舔舐，以惊人的速度遭受侵蚀。将那凄惨临终咆哮抛在身后，罗伊同样立于污浊的中心。——不过，罗伊操控着从重伤处流出的血液，形成了甲壳类般的足部，营造出双脚不沾地的姿态。

「啊~，不用哭也可以哦，梅莉。那孩子会重生的，看好了」

这么说着的罗伊打了个响指，被污浊吞噬、化为黑色块状物的基尔提拉乌便膨胀起来，魔兽的巨躯转变为无数彩虹色的蝴蝶。

大小各异的彩虹色蝴蝶翩翩起舞，在弥漫的黑蛇瘴气中，罗伊邪恶地嗤笑着。

「菲鲁特，那家伙把黑蛇给……」

「虽说他自己是说过操纵不好，但居然干出这种有条件地藏进咱影子里的事。实在没法老实相信他啊」

「真让人伤心啊！难道是因为信不过我们才背叛的吗？连大罪司教都敢欺骗，这种恶劣行径要让王室出身的血脉哭泣了吧？」

「抱歉啊，老子的血可是贫民街的水和面包造出来的。不管父母是谁，背叛你这家伙才不会有哭哭啼啼的愧疚感呢」

菲鲁特对前来挑衅的罗伊勇敢地回嘴，她的视线瞟向盘绕的黑蛇污浊——被黑色浊流吞噬的、亨克尔所在的位置。看过基尔提拉乌刚才的下场，亨克尔的结局不难想象。

无论是对于罗姆爷还是阵营里的任何人来说，他都不是会留下好印象的男人。但毕竟是莱因哈鲁特的父亲。和曾是人质的菲鲁特之间，恐怕也有过对话吧。

落得成为黑蛇饵食的结局，作为报应来说未免太过凄惨。

「——乌尔・戈亚!!」

这感伤，被粗暴的吼声烧尽了。

罗姆爷他们的头顶上飞跃而过，森林被煌煌照耀的同时业火向黑蛇逼近。冲突、爆炎使污浊剧烈震颤，带有热量的腐臭一口气将现实感强加而来。

那样对黑蛇发动毫不留情攻击的，是新加入战局的人物──

「喂，菲鲁特！既然平安回来了就发号令啊！这可是你的工作！」

代替问候的华丽一击后，拉珍斯这样激励道。

看来相当勉强，明明刚参战就开始喘粗气的拉珍斯。但是，这番激励效果立竿见影。

菲鲁特微微睁大眼睛后，立刻勇敢地绷紧脸颊──

「罗姆爷，让我赢吧」

「……净说胡话」

「要是不可能我才不会说呢」

「老夫可没说是不可能。是说你太乱来，这么说的」

再加上侧腹有伤，看来是不可能敏捷行动了。热血上头的劲儿过去后，现在能冷静思考了，觉得还是专心做原本能做的工作吧。

如果，菲鲁特被『暴食』触碰的话，以菲鲁欧雷・露格尼卡之名将会发生什么。──知晓其答案的罗姆爷默杀了感伤，开始转动思绪。

仿佛从罗姆爷的样子中感受到了可靠一般，菲鲁特用双手拍了拍自己的脸颊，

「那么，就如你所愿的发令。──开干了，混蛋们!!」

「「哦──!!」」

响应菲鲁特英勇的号令，以拉珍斯和加斯顿为首，声音响起。

面对着大罪司教与黑蛇，这等世界威胁般的威胁，不仅毫不畏惧反而士气高涨的同伴们让罗姆爷感到骄傲，他也用双手拍了拍自己的脸颊。

「啊──」

沐浴着那投向自己的充满敌意的视线，罗伊抱紧自己的身体，

「受不了了啊──大家大家，最～喜欢了，爱死你们了！」

９

──神明大人，佛祖大人，欧德・拉格纳大人。我发誓终生不握任何人的手。

×　×　×

欲以欢愉，食之。

欲以感谢，食之。

欲以爱情，食之。

既非愤怒 亦非悲伤 既非恐惧 亦非敌意 既非不安 亦非厌恶 既非憎恨 亦非怨恨 既非叹息 亦非嘲弄 既非轻蔑 亦非诅咒 既非恶意 而是单纯的 想要进食。

──发自内心地 『恶食』的罗伊・阿尔法德 想要将在场所有人吞噬殆尽。

「但是 阻碍这点的障碍还真不少啊」

扯下破烂不堪的衣物 将伤痕累累的肌肤暴露在风中 罗伊舔了舔嘴唇。

『蚀』未能发动 加之拉姆等人趁势招待造成的损害极为惨重 其实就连故作从容的罗伊也早已捉襟见肘。虽说通过『血泪鬼』的魔法止住了大量出血 并利用『虹幻公』之力将死于黑蛇污浊的魔兽与森林生物转化为虹色蝴蝶再利用 但在阿尔德巴兰咒印影响下的罗伊 甚至连逃离战场的自由都不曾拥有。

不过 即便如此 面对如此丰盛的饕餮盛宴 『恶食』的罗伊脑海中压根就不曾浮现过逃跑这个选项。

「我们和『美食家』莱伊可不一样呐」

挑食又爱对猎物挑三拣四的莱伊　连用餐场合都颇为讲究。

正因如此，莱伊在必要时会把逃跑和暂缓进食也当作调味料，但罗伊不同。所谓不加挑剔，就是指对所有对象都会毫无例外地产生食欲。

也就是说，罗伊・阿尔法德想要吞噬这世间的一切人类。

所以逃跑什么的简直荒谬。要是遇到过一次的对象再也见不到的话，用悔恨口水浸湿的围巾就算有再多条也不够用吧。

「这样的话对咱们来说，这前期准备可真是有点棘手啊——」

无论是作为『拉姆』还是『拉姆・梅札斯』都没能吃掉拉姆。

真名的变更，这点确凿无疑。但连她身边人最新的『记忆』都不可靠的话，变更后的真名候选就是无限大——而且恐怕不止拉姆，前线组全员都可能做了相同的准备。

「那样的话，『忧郁魔女』佩特拉・雷蒂这名号能信几分也难说啊——」

当初那个故意报上名号的举动，如今看来也像是特大的陷阱。

这样一来，现阶段罗伊在这战场上能插手的余地，几乎确定只有身为菲鲁特・露格尼卡的菲鲁特了，但就连这点也不确定。

万一、菲鲁特的攻击也挥空「呃噗」并引发《蚀》的呕吐反射的话，那个破绽被罗伊抓住的话这次就真的全玩完了吧。

因此、怀着断肠之痛、罗伊做出了本不该属于《暴食》的决断——

「——吃东西、暂时先往后放放♪」

现在这一刻，要查明这些佳肴的真名并将其逐一吞噬殆尽是不可能的。

为了将她们彻底铲平，此刻最优先的应该是准备保存食品。所幸，跟随罗伊的黑蛇中，有位擅长此道的首领『老苦』。──正因如此，原本理想是在更多人所在之处显现实体，但连这点都算在内，菲鲁特背叛的决策恰恰精准踩中了罗伊最讨厌的时机。

「但这样才对劲！吞噬！才有！价！值！！」

失血濒死、损伤惨重、饥饿中的饥饿、极致饥渴感──『暴食』全开。

双手在胸前合十，将视野从两端到中央的世界一口气凝聚起来。

深深扎根的树木被拦腰折断，尽管大自然踏实的土地也无济于事，『压榨屋』的力量将其翻掘而起，将退至安全地带的猎物退路一并封锁。

「加斯顿！　多尔泰罗！」

试图阻止那道坚固土墙建立的，是两名体格壮硕的男子。僵持仅在一瞬，对抗挤压的反作用力弹回紧握的双手，罗伊被强行撑开双臂，眼前翻涌起赤红漩涡。

「拉珍斯！女仆姐姐！」

三白眼释放的火球与拉姆制造的风相互交织，形成火焰龙卷。罗伊消耗三只飞舞的蝴蝶，以『魔弄师』的水枪迎击。

从尸体残留的玛娜中羽化的蝴蝶，即便单独使用也能发挥破坏性威力，但也可作为外接玛娜罐流转用于魔法。对于想要将自身玛娜留给濒死身体施展『流法』的罗伊而言，黑蛇每杀一人就自动增加的蝴蝶正是额外的援军。

「菲菈姆！　格拉西丝！」

炎之龙卷与水枪风暴激烈冲突，以爆炸般的气势蒸腾的水汽覆盖了视野。

天空染白，大地涂黑，在这被改写为双色的世界中，无视想稍作喘息的罗伊的心情，双子粗暴的猛攻倾泻而下。

以『肉食兽』的刚皮故意吃下攻击，用右手『拳王』与左手『雪喰』的进攻性组合技还以颜色，将双子一同砸落在污浊蔓延的大地上。

「三股辫!!」

然而，在双子即将被致死邪舌吞噬的前一刻，插进的饿马王骨枪捞起少女们，从致命范围回收。用『悲恋歌人』的歌声将刺出的另一根骨枪连同对方手臂一同粉碎，战果之少让罗伊的胃袋因饥饿感的蠕动而蠢动。

咬杀那份饥饿感，罗伊张大嘴巴──

「──Biiiiiiig Weeeeeb!!」

在罗伊的正后方，朝天高高伸展身躯的黑蛇，如同倒下的巨木般缓缓朝着正面——那群聚成一团的猎物们倾倒下去。

具备触之即死特性的黑蛇的狩猎方式，说得难听点，就是与生俱来的蹂躏者那种粗放又缺乏技巧的胡闹。毕竟只需将自身质量倾泻出去就能致对方于死地，自然不需要更多策略或　refinement。

它毫不留情地，朝着菲鲁特等人劈头盖脸地砸下——

「——给我顶住！」

「活下去啊——!!」

凝作一团的怒吼化为力量，将本应崩塌于大地的黑蛇污浊强行推回。

力气担当撕开大地，魔法担当将那片大地加固成盾牌，技巧担当将其向上击出以承接黑蛇，并在盾牌溶解前争取到一秒时间撤离。

全员之间难以置信的默契配合与最优行动——

「────」

果敢、勇敢、何等的豪胆。

明明视野中充斥着散布致命威胁的黑蛇，明明面对的是将昔日强敌（友）的存在转化为力量的罗伊，他们却毫无犹豫地奋勇突进——这番气势简直无法解释。

「正常来说至少该慌张啊惊讶啊发抖啊什么的啦！」

混乱与惊愕与战栗 乃至本应受到的冲击全被小路过滤掉的她们的行动 让罗伊不禁喊道。

超越家人与恋人的默契配合 登峰造极到宛若异类的觉悟与胆识。毫无疑问 她们已经完成了蜕变。──全员共同构成了 过于豪华的一道珍馐。

刚想到这里，面对这阵容丰富多彩且花样繁多的面孔，我的心雀跃起来——既没有前菜也没有副菜更无主菜之分。每一道都同等尊贵而意味深长，是独一无二的存在。

对着因那份悸动而双眼发亮的罗伊，从喷烟中滚出来的菲鲁特竖起了中指。她露出尖尖的虎牙，

「别拖拖拉拉流口水了啊，你个疯子！」

「你们太可爱了受不了啦！」

对作为核心、向伙伴发出开始行动指示的菲鲁特，爱意愈发强烈。

起初被背叛意图时我也曾愤怒，但现在只想说声谢谢你的背叛。能被如此盛情款待，若不回礼可真要辱没大罪司教之名了。

「────」

余光瞥去，黑蛇的动作变得迟缓。

元来，黑蛇是以单调动作逐步侵蚀区域、通过无死角地污染大地来扩大损害的魔兽。作为狩猎方的性能绝不算高。少了一个头确实不在最佳状态，但即便如此动作还是太迟缓了──

「乖乖坐下、吧……！」

梅莉用纤细的手臂紧抱住饿马王，以颤抖的声音阻碍着黑蛇的动作。

双眼通红充血的少女，正过度催动着被赋予的加护，因加护溢出而血液灼烧，遭受着如脑髓沸腾般的痛苦。

但她的『魔操加护』甚至干涉到了三大魔兽之一的黑蛇。──老实说，即便考虑到这点，黑蛇的反应也显得迟钝。

「难得的机会！那个！就由我！来补上吧！」

罗伊怀着并非称赞被完全压制的黑蛇、而是称赞完全压制着的梅莉的心情双手合十，大地便隆起，虹色蝴蝶将其吹飞，污浊的散弹四散开来。

黑蛇本体的动作迟钝的话，散布就由我来负责好了。两次、三次地重复爆炸，进行大范围的黑之散布。

「哈哈啊，哈哈哈哈，哈哈哈哈哈哈啊！」

无论、爆心地にいる罗伊とて汚浊を浴びれば命が危うい。故に罗伊は血の铠で自らをコーーティングし、飞び散る汚浊を浴びない万全の姿势だ。

能够躲避雨水的人类，除了少数例外并不存在。而盛宴餐盘上的全员都不可能是例外，黑蛇的污浊炸弹毫不留情地将战场染成漆黑。猎物们互相庇护也是有极限的。理想情况是让梅莉失去行动能力——，

「哈啊？」

摘下血淋淋的面罩后，从罗伊的喉咙里漏出了呆滞的声音。

视线前方，在散布的污浊中逐渐腐烂的森林里，有一片侥幸免于受害的空间──聚集在一处的美餐们背靠背，成功防住了致命的散弹。

「没有啊」

成群彩虹蝶的无法防御鳞粉，被狂舞的大地散弹所拦截。

「不可能的吧」

从视野边缘到中央的碾压式压迫，其势头被压制，发动遭到阻挠。

「没有啦都说了」

贯穿鼓膜的叫歌所瞄准的拖延步伐，被风与炎制造出的爆音给掩盖。

「没有的吧、都说了没有、正因为没有才这样啦」

『灵魂的胃袋』被彻底颠覆，可抓住之物被毫不吝惜地挥霍，连其存在曾令人畏惧的事实也遭抹消——凭借理外之力，天地异变接连引发。

但以菲鲁特为核心的『阿尔黛巴斯达团』却悉数精准应对，全员如单一生物般协同作战，始终以最优行动持续抗衡。

──奇怪。

「────」

一边毫不间断地重复著仿佛要削去世界与常识的攻击，罗伊一边疑问著。

再怎么说，也太奇怪了。确实她们很勇敢。她们彼此信赖。她们的目的只有一个。她们优秀又能干。她们很强。

──即便如此，还是奇怪。

人类再怎么说，也无法做到如此最优化的行动。

尽管如此，菲鲁特他们却能针对所有攻击，从手牌中选出最有效的卡片，以最佳时机持续出牌。

这种感觉罗伊是知道的。正是在监狱塔战斗过的阿尔德巴兰。

囚われのロイの封印を解いたアル德巴兰は、力の差を见せつけるためにロイをボッコボコにした。手も足も出ずに完封されたあの不可解、あれと──否、近いが、违う。あれはあくまでアル德巴兰単体の异常性だ。しかし、これは敌全员の异常性だ。

──很明显，这不太对劲。

「──啊～，我看走眼了呢～」

常识行不通的常外、道理说不通的理外、不值一提的论外。

接连遭遇这些异常状况，差点让空腹的肚子被疑问填满的罗伊，终于想到了一个再理所当然不过的事实，不禁自我厌恶起来。虽说肚子饿得慌，但脑子缺血到这种地步，要是因为自己搞砸了觅食行动可就糟了。

既有气势十足的号令，又让人误以为敌人的核心是菲鲁特——连罗伊的这种思维诱导也是她们作战计划的一部分。在这场战斗中，已经多少次为她的表现感到惊讶了。罗伊察觉到他真正的核心人物并非菲鲁特，而是藏在她身后的幕后黑手，并将视线投向了那边。

刹那间，那个黑手「啊」地眨了眨眼——

×　×　×

──神啊、佛啊、欧德・拉格纳大人。我发誓此生绝不希望修复与人的关系。

──神啊、佛啊、欧德・拉格纳大人。我发誓此生绝不为了任何人动怒。

──神啊、佛啊、欧德・拉格纳大人。我发誓此生绝不向任何人透露秘密。

──神啊、佛啊、欧德・拉格纳大人。我发誓终生不让任何人看到我的软弱。

──神啊、佛啊、欧德・拉格纳大人。我发誓终生不与任何人共赏朝日。

×　×　×

「──难道说、你终于察觉到了？」

如此回应着，将当场所有同伴的思考过程以及为此进行讨论的共享过程『压缩』的『忧郁魔女』，单眼闭起眨了个wink。

10

──神啊、佛祖啊、欧德・拉格纳大人。我发誓一生都不挑食。

×　×　×

说到底，为什么佩特拉会处于保管『忧郁』魔女因子的立场呢。

原本的所有者柯林特不行的原因，在于他有只有他才能完成的职责──必须承担抑制『神龙』波克肯尼卡的任务。

而归根结底，可以说只要不是他，所有者是谁都可以。

当然，在使用『忧郁』权能方面存在适不适合的问题，即使是无需权能也能成为战力的爱蜜莉娅和梅莉、有着专属职责的雷姆等人也早早退出了候选。但是，即使除去她们，候选者依然大有人在。

所以，搁置一直留到最后的拉姆和罗姆爷，佩特拉被选为魔女因子所有者的理由，比起综合战斗力等判断，有着更重大的原因。

──简而言之，就是因为佩特拉最能熟练运用权能。

「──『暴食』的大罪司教……虽然莱伊那混蛋确实自称会胡乱啃食眼前一切，但这招式数量也太不正常了吧。怎么办？」「接近战、中距离和远程攻击都能应对，确实棘手」「这犯规了吧。简直像少爷一样」「「要是和莱因哈鲁特一样那谁赢得了啊！」」「别大声嚷嚷！格拉西丝，不许胡说八道。会让人晕头转向的」「哈！感情真好啊。既然已经觉得胜券在握，不如让拉姆也分享一下这份心情？」「这丫头说话真讨厌……」「不过女仆姐姐的说法也有道理。下一步呢？」「基本方针是继续现行战术。确实对手拥有全能距离的作战手段……」「「手段？」」「不管手牌数量有多少，能选择手牌的脑袋只有一个。只要持续发动波状攻击，对方必定会出错牌」「即便不这样，对方的伤势也很重。等不及的时候就会想强行改变局面吧。对罗姆大人来说算是表现不俗了」「嘿，咱家罗姆爷很厉害吧？」「说得是呢，罗姆大人很可靠」「啪啪，罗姆大人」「现在可是在拼命战斗中啊！」「虽然打断你们欢乐的氛围很不好意思，但饿马王他们也有各种情况要说明，我脑袋都快炸了哦？」「「──对不起!!」」

与面面相觑、深入讨论并无二致的作战会议内容，佩特拉运用『忧郁』的权能，将其『压缩』为一瞬的事件。

所有人都在反复叠加着彻底纠结直至得出最佳思路这一过程的『压缩』。

『既然能像柯林特先生所做的那样压缩移动距离和时间，那么思考时间与讨论时间的压缩也能做到……这正是概念系能力常见的思维转换！』

「一直用着相同方式的柯林特兄长大人，脑子实在太顽固了呢」

権能の作用の微调整に集中しながら、ペトラが半透明のイマジナリースバルと軽口を交换する。──戦闘中だ。普通なら気が散る、と文句も言いたくなるかもしれないが、今のペトラに限っては、この『スバル』とのやり取りに大いに助けられている。

『忧郁』的魔女因子被保管的小箱子──佩特拉将继承自柯林特的它藏入怀中，持续用灵魂体验着这份力量带来的恐怖引力。

「虽然由自己来说有点那啥，但引力这个形容，简直太贴切了」

无法抵抗而被吸入的感觉，将其比喻为引力，佩特拉自我告诫着。

哪怕只是一秒的松懈，魔女因子就会立刻用「那个也能做到」「这个也能做到」来诱惑佩特拉，试图解除她作为人类的重要枷锁。

若无事发生时便会晃晃悠悠地、仿佛窥探悬崖底部般委身于那股被吸入的感觉──，

「但是不行」

──全能感，是让人沉醉的甜蜜蜜汁。

魔女因子就会趁虚而入利用人类心灵的脆弱之处。而且其手段是以实现最想达成的欲望为名，用"这个怎么样"的形式呈现在面前。

越是拥有重要之物、怀有无法退让愿望的人，就越难以抵抗这种诱惑。

那一定是，就连『强欲魔女』也好，曾是『怠惰』大罪司教的培提尔其乌斯・罗曼尼康帝也罢，都不会是例外的。

佩特拉也是，若是没有支撑自我的手段的话会变成怎样都不知道。

但是──

『佩特拉！需要阿顿阿珍的支援！』

「因为阿汉先生在休息中呢！交给我吧！」

被少年般勇猛的呼声叩击心扉，佩特拉发动权能──通过『压缩』洒落的污浊与挥舞的血色大镰的攻击中该如何行动的犹豫，让拉珍斯与加斯顿二人的思考与沟通过程得以压缩，促使他们选择最佳应对。

二人互换应对逼近攻击的方式，加斯顿以『流法』接下血色大镰，拉珍斯用火球加特林扫清污浊，精彩地化解了危机。

对此『昴』竖起大拇指，佩特拉也以竖大拇指回应。

『干得好，佩特拉！就保持这样！帅呆了！』

即便仅是幻影，意中那副从容得意的笑容仍令心潮澎湃。

就是这份情感。正因拥有它，佩特拉才能保持自我超越极限。──与历代众多受魔女因子蛊惑者不同，佩特拉并不孤独。

这使她免于堕落为『忧郁魔女』。

因为──

「人家不想被斯巴鲁讨厌嘛」

若想嘲笑这份虚荣尽管笑吧。尽可手指着她，尽情嘲笑佩特拉。

必要的话，场面话要多少有多少。这可是拯救世界的战斗。要将生活在王国的众多人民从不安中解救出来。必须守住王选这个重要舞台。因为大家的目光都聚焦在我身上啊。

冠冕堂皇之外的理由也有很多呢。平时总是想偷懒的拉姆姐姐也在奋战。留守的法兰黛莉卡姐姐为我们祈祷平安。奥托先生总是太乱来。最讨厌被老爷算计着行动了。想让爱蜜莉娅姐姐和雷姆姐姐看到我帅气的一面。要连同加菲尔先生的份一起加油。梅莉酱别露出那种担忧的表情啦。碧翠丝酱，我绝对会救你的所以不准哭。

那些全部都是重要的东西，毫无疑问是佩特拉努力的理由，但最重要的并非如此。

最重要的，是你。

「──昴」

不想让你看到我不堪的一面。不想让你看到我狼狈的模样。因为哪怕只有一秒钟，我也不想让你眼中的我有所松懈。

若是为了让永远追逐着闪耀之人的你回过头来，就必须永远伪装成闪闪发光的模样，那我就这么做吧。

我早已被引力牵引着坠落。

才不是什么魔女因子呢。我的全部都是由对你的、爱与恋构成的。

「所以，没关系啦」

无论被魔女因子如何诱惑，佩特拉都绝不会屈服。

只要这份恋慕之情还在，『暴食』也好『黑蛇』也罢，根本就没什么可怕的。

11

──神明大人，佛祖大人，欧德・拉格纳大人。我发誓这一生绝不因他人而哭泣。

×　×　×

『阿尔钢炮团』──不、应当称之为『忧郁魔女』及其使徒的这个集团的实力，远远超出了罗伊的期待和想象。

「很棒啊，很不错嘛，很好对吧，可以嘛，挺好的吧，只能说棒，就是说很好，正因为能说很好，正因为会被夸很棒！暴饮！暴食！」

说到底，罗伊根本搞不懂《忧郁魔女》在搞什么鬼。

不过，可以明确的是，『忧郁魔女』正在最大限度地活用自身的权能，为菲鲁特等人开辟活路，对抗着『暴食』的权能。

在战斗中，菲鲁特等人并没有发挥出超越自身实力的成果。

只是，她们的实力上限、其最大值被持续引出并发挥出来罢了。而使之成为可能的，正是『忧郁』权能的效果──

「不过，应该不至于能随心所欲到无法无天的地步吧」

如前所述，罗伊已经从母亲口中听闻了『忧郁』魔女因子所持有的缺陷。

那份与任何人都无法适应的魔女因子，虽是赋予持有者干涉世界规则的绝大力量，却同时也是会索求相应代价的缺陷品。

也就是说，看似完美的『忧郁魔女』的应对能力，迟早也会迎来极限。至于那极限何时来临，则取决于能支付多少代价了吧。

「懂啦懂啦，佩特拉小姐可是最喜欢菜月先生了嘛」

『灵魂的胃袋』──若追溯罗伊吞食的宝库中所收纳的最新『记忆』，便能深切感受到这位世界新诞生的『魔女』那份令人心头震颤的纯粹心意。

虽是年幼未熟的少女，她却是个能为炽热爱意不惜性命的孩子。

若有人说，要夺回被抢走的重要之物，须将性命以外的东西燃作柴薪，她定会毫不犹豫地将一切献作燃料吧。

而事实上，她也正如此行动。──但库存并非无限。

「接下来，就看哪一方先消耗殆尽了」

正如『忧郁魔女』存在极限，罗伊的生命亦有其期限。

他故意不治疗那汩汩流血的伤口，只因连这流淌的鲜血都要重塑为实现目标的武装，化作抗争的手段。

这大量失血，正持续点燃着罗伊・阿尔法德生命的导火索。

诚然，这场战斗已置于吞噬或被吞噬的临界线上。

「哈哈」

吐着炙热灼人的气息，罗伊向令自己灵魂跃动的饥饿感致谢。

迄今为止罗伊作为『暴食者』，将一切事物随心所欲地啃食殆尽。吞食、舔舐、贪婪地咀嚼，侵蚀众多人生，这一切都是为了填补罗伊・阿尔法德与生俱来的饥饿。

为此罗伊、在找到满意的味道之前将全世界都试了个遍──怀着这样的心态持续着进食活动，吃了却失望，吃了却沮丧，吃了却扫兴，即使『蚀』了又『蚀』也填不满的饥饿感持续不断地支配着他。

正当罗伊那看似永无止境的盲目进食活动进行时，那种变化粗暴地、过于鲜明地袭来。

那就是──

『来啊，试试看啊。看你能不能吞噬我，这可是生死攸关的事。怎么样，你这家伙』

在那片砂海中耸立的塔里，有个拥有压倒性灵魂的家伙，差点撑爆了名为罗伊・阿尔法德的容器，原因就是他把那玩意儿塞满了嘴巴。

──雷德・阿斯特雷亚。

接触了被称为初代『剑圣』的男人的灵魂这件事，给罗伊带来了巨大的改变。

自称『暴食』、四处奔波致力于饮食活动的同时，罗伊也在忧虑着。——身为这样的自己，所怀有的饥饿感恐怕永远无法得到满足吧。

『倒也不是说那种东西就你小子一个人特别或者有啥了不起的？本姑娘和其他的阿猫阿狗啊，大家大家大——家——伙，全都他妈渴求着填不满的爱哩。你小子想要的那个连名儿都没有的玩意儿，本姑娘就帮你找找看呗。不过嘛，本姑娘想要的东西……你丫心里有数吧？』

说罢、妖艳而嗜虐地嗤笑着、怪物扬言要成为罗伊的母亲。

既非敞开心扉，亦非依赖其存在，罗伊只是渴望自己无法发现的可能性，才接受了母亲的提议。这件事似乎遭到莱伊的嘲笑与路伊的轻蔑，但和母亲之间本就是利害关系，所谓的利用大概彼此彼此吧。

但是，无论吞噬多少、握住被爱玷污的手，都得不到想要的东西。

莱伊试图通过赋予每一餐价值来寻找填补饥饿的方法，而路伊似乎对为了填补饥饿想要什么有着具体的展望。

只有罗伊。唯独罗伊没有。——而这个，终于找到了。

『少胡扯了，你这家伙。弱肉强食——这才是活着的意义吧』

啊啊，没错没错。正是如此。

我所渴求的，是活着的实感。是能够发自内心笑着说"我还活着"的理由。

所以──

『为了想要的东西拼上全部——这不是理所当然的吗？』

啊啊，没错没错。正是如此。

即便没有丝毫爱情与敬意，母亲的那条教诲却莫名地正确无比。

所以──，

「若不把所有能用的手段统统毫无保留地全部砸进去，根本算不上爱对吧！」

既然对方已经为我突破了极限，这边也必须做出回应才行。

难得精心准备的大餐没能吃完的话『暴食』之名可要哭了。

「来呀来呀来呀来呀，快来尝尝鲜快来看看呀──！」

以因失血而逐渐冰冷的四肢为代价，心中的激情已达到最高潮。

将流出的鲜血变为模仿虫足的棘脚，随着跃动的罗伊一同呼应，其背后黑蛇化作污浊之柱冲天而起，重新开始那千篇一律的倾覆狩猎。

──轰隆隆地让风发出呜咽，病毒毫无遮掩地倾泻向森林。

诞生的是极其亵渎、看似无从抵御的毒浪。它字面意义上地吞噬战场，将一切染黑，并以压顶之势试图将万物疫病化直至死亡。

但是──，

「加油──！」

「「──活下去啊!!」」

如同傻瓜死记硬背般的号令与应和，成为了集结全力的反击之嚆矢。

拉姆的裂风撕开黑波，以跟随梅莉的饿马王为首的兽群则打开了突破口。紧随其后的壮汉们，包括新被召唤出来的在内团结一致──挥出的铁锤猛烈击碎大地，化作抵御邪毒的防护壁垒。

那是凭个体力量相形见绌的人们，正因为所有力量汇聚一堂才产生的刚力，是乌合之众的生的努力，击退回涌而来的死亡结果的战斗。

「看来呀，佩特拉小妹的权能，不就是把事件缩短嘛～？」

「才。不告诉你」

「这么冷淡的回答反而让人更来劲啦！」

攻势毫不停歇，在黑色蛇群的污浊如雨般倾泻而下的环境中，身披血色铠甲的罗伊突击前进，接连切换不同理外之人的异能・术技・逸脱，拳击与魔法与咒歌，层层叠叠地朝着猎物们倾注而下。

但每一次，她们都立刻重组阵形，将物理攻击与魔法攻击编织结合，交融在一起进行对抗──究竟谁守住了哪里，早已无从知晓。唯有全体共同承受、全体协力推回这一事实，正在改写战场。

──即便在这场激战之中，罗伊的眼球依旧骨碌碌地转动着，审视着猎物。

大致上『忧郁魔女』的权能是『缩短』应该没错。借此她缩短了移动的时间与距离恐怕连思考与判断的时间也一并调度着呢。

作为证据，在战场上不断出现又消失的『忧郁』使徒们，即便是初次参战者也能毫不困惑地应对突如其来的状况——不，是将困惑的部分『缩短』，使其能够立刻适应当前局面。

「不过这种状态还能维持多久呢啊！」

虽然很佩服他们的应变能力和高昂士气，但逼近极限这点彼此彼此。不过，优势在罗伊这边。因为后方还有黑蛇这个威胁──即便『忧郁魔女』们能击败罗伊，也还得对付这头凶恶魔兽。

也就是说、她们可不能输给罗伊耗尽力气。那种、不能全力以赴的处境、就像盘子里的一小撮──

「──这里就是、决战胜地不对是『蚀』地来着啦!!」

黑色巨蛇的躯体再次冲天而起，污浊如暴雨般倾泻而下的待机状态。

为应对此招，『忧郁魔女』们一齐摆好架势的瞬间，释放了『记忆』。

那就是──

「──『蚀连星』」": "「——『蚀连星』」

既非『日食』亦非『月食』，而是将罗伊・阿尔法德独创的全新餐桌礼仪，献予饕餮餐盘们。

12

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生不与任何人共眺星辰。

×　×　×

瞬间，战场上迸发而出的，是罗伊・阿尔法德至今吞噬过、但认为不值得记住的那些堪称粗粮的众多『记忆』中的一部分。

经历过普雷阿迪斯监视塔的事件后，『恶食者』改变了自身进食行为的意识。

对所有食材心怀感激，对一切机缘抱有敬意。──这个世界上没有难吃的食材。只不过是自己不懂其美味、长了一根笨蛋舌头罢了。

比如说，有些鱼带毒。但是，若能妥善处理掉鱼体内含毒的内脏，便能享受到远超中毒痛苦的美味。

对『暴食』来说猎物也是一样的。从头部到臀部，世界上根本不存在完全没用、没有品尝价值的食材。

无论什么食材都有能用的部位。──所以，我使用了它。

「──『痛楚记忆』」

要是认真活着的话，谁都会有一两个痛到无法承受的记忆吧。

将那般、无数的『痛苦记忆』，从罗伊积蓄的『灵魂的胃袋』中抽取出来，混合调和，朝着眼前的战场倾泻而去。──那是肉眼不可见之物。故而也无从躲避。是将概念，强加于对方的亵渎之行。

当然，即便掷出『痛楚的记忆』，那也不会直接作用于对方。因为那字面意思就是一段毫无实感的『记忆』，所以即便砸中猎物们，它们也没有体会那份痛楚的余地。

那么，究竟会发生什么。──仅仅会连锁地唤起近似的『记忆』罢了。

「──啊」

最初、微弱的声响从人群中漏出。

那群此前一直发出勇猛吼声、眼中蕴藏着勇气与觉悟、怀有直面一切障碍气概的、堪称真正的勇士的存在。

从他们的唇间，漏出的既非战吼，亦非彼此的名字，而是尖锐的音调。

「啊、啊、啊、啊啊啊啊啊──!!」

而且，一旦开始泄漏，便永无止境。

瞪大双眼，张大嘴巴，即使不愿也用手捂住发出尖叫的部位，发出吐血般的凄厉惨叫。

而且并非只有一人如此。在场的所有人，都开始尖叫了。

「「──呜啊啊啊啊啊啊啊啊!!」」

罗伊一股脑倾泻而出的『疼痛记忆』虽然处于概念范围内，却让身体将曾体验过的近似疼痛，如同此刻正在发生般重新忆起。

若是曾在过去承受过的疼痛便能忍耐──这个答案是否定的。过去难以承受的疼痛，无论置于现在还是未来，都无法承受。

撞击的痛楚、擦伤的痛楚、被砍的痛楚、被刺的痛楚、骨折的痛楚、被剜挖的痛楚、粉碎的痛楚、裂开般的痛楚、灼烧般的痛楚，所有一切的痛楚，『痛觉记忆』都会将其唤醒。

而且，是将至今人生中尝过的无数痛楚一次性涌现。

「嘎──」

发不出声的声音，由菲鲁特、拉姆、罗姆爷、梅莉、菲菈姆、格拉西丝、加斯顿、拉珍斯、多尔泰罗，以及被『忧郁』权能之力召唤到战场的使徒们，接连不断地发出。

没有人，能承受得住。其中，发出最高亢惨叫的──

『──佩特拉!!』

下颌如同痉挛般猛地弹起，被迫也尝遍了曾致使菜月・昴走向『死亡』的诸多痛楚的，不是别人，正是佩特拉・雷蒂。

13

──老天爷，佛祖大人，欧德・拉格纳大人。我发誓这辈子再也不跟人约好碰面了。

×　×　×

『──佩特拉!!』

听到幻影菜月昴拼命的叫喊，看来作为自己所见幻影的他无需品尝这份痛苦，佩特拉如此安下心来──并没有。

做不到。这等余裕，在品尝着『死亡』痛楚的佩特拉・雷蒂身上并不存在。

「──啊」

嘶哑的气息，漏出。好痛。好痛。好痛好痛好痛。好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛好痛──。

「──噫」

被斩开的肚子好痛。被碾碎的眼睛好痛。被贯穿的胸口好痛。被随机袭击的背部好痛。因拙劣的匕首使用而割伤的手指好痛。冷水劳作导致的冻疮好痛。突然被砸碎的头好痛。伴随锁链声响的拷问让身体好痛。被风剐蹭的喉咙好痛。跳下后撞击到的尖锐岩石好痛。全身被揍得破烂不堪身心俱痛。为了逞强而手下留情的修炼让手脚好痛。冻僵撕裂的手指、脚踝好痛。被舔舐的眼球恶心又疼痛。被冻住手铐并粉碎的手腕好痛。跪在冰冷地面上的膝盖、全身上下都在嘎吱作痛。被混乱的奥托推落后身体好痛。之后被白鲸追赶狼狈逃窜既难堪又疼痛。被冰封在极寒中灵魂好痛。为了让他下定决心处决而被迫暴走命脉好痛。为了被处决而被刺穿胸口好痛。因『死亡回归』的告白而被攥紧心脏好痛。被纠缠不休的『怠惰』权能抓住好痛。因失去雷姆的恐惧而刺穿自己的喉咙好痛。时隔数月的剖腹肚子好痛。被瓦砾击中全身、手臂被切碎、最后被啃食全身好痛。被猛兽玩弄、再次全身被咬碎好痛。最后又自己刺穿喉咙、好痛、好痛、好痛、好痛、好痛──。

「──呜」

『佩特拉！　佩特拉！　不行、不要去、佩特拉!!』

疼痛支配了脑海。身体内部、头脑内部、内心深处，明明本该全部被■■■所填满，此刻却被疼痛将一切尽数覆盖。

从头顶到脚尖，身体里没有一处不感到疼痛。全身上下、构成自身的所有部分都化作了痛楚，自己是为了品尝痛楚而生、由痛楚构成，痛楚本身也在疼痛，疼痛疼痛疼痛疼痛疼痛疼痛疼痛疼痛疼疼疼疼──。

「──呃」

视野染上一片鲜红，过于吵闹的自己的声音听起来如同耳鸣，鼻腔深处刺鼻的血腥味，嘴里涌出大量带着死亡味道的唾液，全身肌肤都在难以承受的冲击下泛起鸡皮疙瘩。

此刻，■■■・■■■才真切体会到，仅仅阅读《死者之书》绝无法真正理解的痛苦正清晰地渗透进来。借由这份痛楚，■■■・■■■才从字面意义上真正痛彻地领悟了■■■・■■■。

痛苦将■■■・■■■的外壳与内在，整个涂抹覆盖，在其中真切地感受到痛。

「──啊」

所有尝过的痛苦，全都与■■■・■■■的，菜■■・■昴■的，菜■月・■昴■的──菜月・昴的、伴随着惨烈的丧失感的悔悟记忆相连。

「────」

好痛。让爱蜜莉娅死了。好痛。让菲鲁特死了。好痛。让罗姆爷死了。好痛。让雷姆死了。好痛。让阿拉姆村的大家死了。好痛。让拉姆死了。好痛。让法兰黛莉卡死了。好痛。让佩特拉死了。好痛。让碧翠丝死了。好痛。让奥托死了。好痛。让罗兹瓦尔死了。好痛。让琉兹死了。好痛。让加菲尔死了。好痛。好痛。好痛。──好不甘心。

「不甘心」

好痛。好痛好痛。好痛好痛好痛。好痛好痛好痛好痛。──那又怎么样。

「不想输」

就算痛，就算苦，悲伤和不甘要更加难受得多。

大家都喜欢，无法放弃大家。那样的、喜欢大家、无法放弃大家的你，我也喜欢得无法放弃。

所以──，

「──把我、当作是谁啊」

■■■・■■■是，■■拉・■伊■是，佩■拉・■伊特是──佩特拉・雷蒂是，学得快又有才华还是可能性的集合体前途无量，未来一片光明。

那个人，那些人，如此相信着佩特拉。──那么，就去做吧。

「能做到」

应该能做到吧，佩特拉・雷蒂。

为了不让那些对我说我能做到的人变成骗子。

还是说大家是相信了又弱小又悲惨什么都做不到的佩特拉的骗子呢？

「那种事情、怎么可能嘛」

能做到。应该能做到。如果说能做到，就不会只是耍嘴皮子而是去做。去做吧。快去做。能做的。现在就做。马上做。现在！ 你看，做啊，做啊──去做吧!!

「压缩……唔嗯」

以『忧郁』的权能之力，进行『压缩』。

就像将距离、移动时间、思考时间、商议时间『压缩』一般，此刻即将降临在佩特拉等人身上的恐怖瞬间，也被『压缩』了。

疼痛，是多么可怕的东西啊。

仅仅是微不足道的疼痛也会让人泪眼汪汪，若是稍尖锐些的疼痛便会彻夜难眠，而若是沉闷的钝痛，甚至可能影响往后的人生。

无论轻微、尖锐还是沉闷，感受疼痛的时间总是显得漫长。

将那一秒如十秒、一小时如半日、一天如永恒般漫长的时间感，『压缩』起来。

「大家，咬紧牙关哦」

『──虽然一秒钟就结束，但会带来百倍的疼痛哦!!』

没有说或许是一万倍。

因为无论说与不说，无论有无心理准备，该做的事情都不会改变。

「──『压缩苦痛』」

『忧郁魔女』迈向新阶段的力量，就此解放。

14

──神明大人佛祖大人、欧德・拉格纳大人此生此世我发誓绝不惋惜与他人的别离

×　×　×

「────」

亮相的新招式毫无疑问地炸裂开来，将猎物们完美的协同作战打得裂痕遍布。

听着充满邪毒的黑色蛇身纷纷倒下的风声，从对面传来五光十色的悲鸣・绝叫・惨叫的地狱呼号。

那些声音全都显得痛苦不堪，若是有时间的话，罗伊大概会为她们哭上一整晚直到天明，然后将这份心情写成诗歌付诸东流吧。

但是，没有那个时间。也没有写诗的学识，想必也写不出什么像样的作品。

可是，可怜她们的心情是真的。对她们并没有怨恨。连憎恶的感情都没有。连爱恨交织都谈不上，有的只是单纯的爱意。

心爱之物痛苦哭叫的样子，有谁会想看呢。那种东西，充其量只是享受她们人生的调味料罢了。调味料不是主食。把它当作主菜什么的，是变态才会做的事。

「我们才不会做那么过分的事呢」

通过让『痛苦记忆』产生连锁反应的『蚀连星』，猎物们的行动被彻底切断。

接下来是倾泻而下的黑蛇污浊──因为这项任务由『老苦』负责，所以不会夺走她们的性命。而是封锁她们的思考与行动，将她们永远禁锢在死亡的边缘。这样一来就和酒藏一样了。只需等待熟成之时，直到解开真名的最佳饮用时刻来临。

被阻拦的水边虽无路可逃，痛苦与黑暗似乎永无止境，但最终她们经历的痛苦会丝毫不剩地收归罗伊体内并消失，这样也不错吧。品尝这般苦涩、舔舐殆尽、尽情享受，也正是食活之道。

「啊～明明现在不能立刻吃掉，看着成熟的果实真是──」

好痛、刚想说出口，罗伊的话语就被打断了。

并非遭到了反击。不如说正相反。猎物们发出了格外强烈而巨大、仿佛用悲痛刺穿胸膛般的凄厉尖叫。临终的惨叫——用这样的形容来形容其音量也毫不夸张。

一瞬间，罗伊睁大了眼睛，但这反而意味着计策进一步成功了──

「──疼呜呜呜！　好疼啊啊啊!!」

「「给我起来呀啊啊啊啊──!!」」

直后，难以置信的反应与团结，否定了本应吞噬猎物的终焉。

15

──神様、佛様、欧德・拉格纳様。我发誓这辈子绝不和人一起看夕阳。

×　×　×

刹那，菲鲁特尝到了仿佛被剥去全身皮肤、用金属刷子蘸饱盐水让莱因哈鲁特打磨般的地狱式疼痛。

「呜咕」

有生以来第一次因剧痛尝到内脏翻搅的错觉。半边脑袋发麻，甚至产生血液在体内倒流的错觉。

不清楚发生了什么。──不，是清楚的。是佩特拉做了什么。

「这小不点真够厉害的……」

菲鲁特静静称赞着这名与自己身高相仿的少女的奋战。

在这场激烈到被强行压缩进程的谈判中，她明白是佩特拉与罗姆爷以绝佳的配合统合了混合军团。这很了不起。毕竟罗姆爷是世上最聪明可靠的人，那佩特拉无疑是天才吧。

那个天才，做出了超乎想象的事情，把对方的某个东西彻底摧毁了。

虽然因此尝到了离谱的痛楚，但那个事实——挨了这一下的似乎不只自己一个人——让菲鲁特没有流出眼眶中浮现的泪水。

「话虽如此，你这家伙，运气也差到离谱了吧」

这样扭曲着脸颊的菲鲁特所看见的，是视野边缘那个矮小的影子──汉巴里。

和从一开始就加入战斗的加斯顿、中途加入战斗的拉珍斯不同，汉巴里是在关键局面蓄势待发地参战的。──就在那个瞬间，刚才那个离谱痛的家伙被放了出来，所以这已经不是不走运能形容的了。

但是──，

「──运气是没有，但棒极了」

菲鲁特几乎是抢夺般地一把抓住了那个——被眼角挂着泪花的汉巴里拿在手里的东西。──那就是能够成为阵营王牌的，『星杖』。

使用方法她是知道的。就连莱因哈鲁特也无法轻易承受的星光──将其释放。菲鲁特竭尽全力，调动全身的力量，全部注入，倾其所有。

接下来就是──，

「该往哪儿揍啊！」

16

──神様、仏様、欧德・拉格纳様。生涯、誓不踩踏并肩同行者的影子。

×　×　×

「──呜哦哦哦哦！好痛啊啊啊!!」

「「快躲开啊啊啊啊──!!」」

已分不清哪边才是魔兽嘶吼的绝叫与咆哮震天动地，如同千般灾厄汇聚而成的黑蛇蛇身，被来自正下方的爆风狠狠推回。

光与暗的奔流肆虐战场，撕裂苍穹般的冲击让罗伊的全身因惊愕而灼热。

发生了什么。如何做到的。──这一切，皆可不论。

「佩特拉小──姐！」

唯独是谁做到的这一点确凿无疑，罗伊・阿尔法德抵达了高潮。

太厉害了。值得喝彩。必须与罗伊体内众多的『记忆』们一同，为她献上雷鸣般的掌声。

究竟要牺牲自己到何种程度，才能让『忧郁』的魔女因子做到那般地步。

想像一下推测一下，若是不能舍弃常人的幸福之类的一切，这场战斗、这般势均力敌的局面、那种程度的旁若无人，就无法实现了吧。

──想要变得幸福。

那理应是人绝对不灭、坚定不移且不可分割的愿望。

那即便是罗伊──不，即便是莱伊即便是路伊，即便是大罪司教们，即便是恶棍即便是罪犯也不会改变，是绝对的祈愿。

为此而活着。但是，若不舍弃那份幸福，就无法应对这个局面。

「────」

用一瞬眨眼拭去因欢喜而湿润的眼瞳，罗伊望向从同伴手中夺过白色手杖的菲鲁特。

在这最后关头，既然看似几乎派不上用场的小人族特意带来，那必定是珍藏的秘密武器。

也就是说──

「要是那样都不行的话人家可是会哭的哦!?」

虹色蝴蝶飞舞，冰与火的长枪倾泻而下，血腥巨镰从四方袭来，并非左右而是前后方向的碾压开始压迫，少年般的女高音被诅咒般地吟唱着。

「快保护菲鲁特!!」

风将蝴蝶尽数斩落，冰与炎的魔弹击碎了炎与冰之枪，厚实肌肉在被斩裂的同时接住了血色大镰，刹那的双击贯穿了前后涌来的大地，老人与猪人的巨躯彻底抵挡住了使血肉崩溃的咒歌。

「真漂亮呜！但是呜──」

波状攻击被铁壁般的联手防御所阻挡，但罗伊并未气馁。

至此，一直克制未用的『转移』发动了，转瞬间罗伊的身影出现在了菲鲁特他们群体的正中间，目标是菲鲁特──并非如此，

「这边的两人也是关键人物吧？」

他瞄准的是在迎击阵容中，连站起来的余力都没有的两位少女的背部。

『忧郁魔女』与『魔兽使』，二者都是让与『暴食』和『黑蛇』的战斗能够势均力敌所不可或缺的敌方战力。没有人能来得及阻止出现在两人背后的罗伊。

舔着嘴唇的罗伊，右手承载着『拳王』，左手承载着『雪噬』，温柔地──，

──瞬间，梅莉的发丝蠕动，白光击穿了罗伊的左眼。

「嘎呜呜!?」

被烧灼般的痛感贯穿，罗伊的左眼视野彻底消失。正当他瞪大仅存的右眼试图理解变故时，溃烂左眼的狙击手──藏于梅莉发间的小蝎子，映入了他的视野。

这是未知的存在。不在『记忆』中的底牌、暗棋、毕生全力之战。

「连这么小的同伙都──」

本想接着说「竟敢拼命顽抗」，话语却戛然而止。

因为更早一步，他脚下的土地背叛了他，将他毫无征兆地抛向高空。

「────」

并非魔法。未感知到玛娜的波动。

那么又是『忧郁魔女』所为吗？──不，即便强如她也不可能背后长眼。

引发异变的是大地的隆起。无预警、无协调、猛然弹射的土块。

「──搞什么啊，可靠过头了吧喂，本大爷的伙伴们」

突然传入耳中的这句话，是尖利到令『记忆』里浮现出无数对应片段的熟悉嗓音。

『地灵加护』与大地呼应，只要双脚着地便能化作无人能破的铁壁，正因过于可靠，本不该被听见的声音。

滴溜溜地，浮空的罗伊在倒转的视野中映出大地，对蠢动的病巢魔兽施加狂暴的催动。

与方才不同，罗伊与黑蛇距离拉开。血铠虽将剥落，但污浊如雨飞散便需猎物分神应对。

「坐下!!」

那带哭腔的呐喊，一瞬扰乱了黑蛇的动作。

但停滞不过眨眼之间。即便被夺走这刹那，罗伊的算计也未落空——瞬息，欲冲天而起的魔兽蛇躯，爆裂。

爆散，倾泻的污浊，在那污秽大地上滚出一道黑影。

「噗哈、咳嗬、噶嗬嘎……」

「骗人的吧」

呛咳着跌入世间最骇人污浊潭的红发男子，带着远超顽固或苟活的冲击力，令罗伊愕然失语。

为何、还活着。疑惑与涌上的食欲让罗伊的肚子不争气地叫了起来。

「哟，这边看过来啊」

凭借轻盈的跳跃追上悬空罗伊的金发少年，磨响着他那尖利的獠牙，夸张地挥起戴着银色臂铠的拳头。

要是这一拳砸下来，半死不活的罗伊根本不堪一击。

即便心知这不过是拖延片刻的权宜之计，罗伊仍为争取撤离的机会，再度凭借『跳跃者』的异能使出『月食』，

「唔」

──却被左侧死角袭来的索达虫撞乱了专注。

「────」

烦人的振翅声与恶心的触感引开视线，只见远处数十米外倚着树木的青鳞地龙，以及本该空无一物的龙背上坐着的男人身影。

男人朝这边伸出手指，发现视线交汇时咧嘴一笑。一副得逞的得意模样。

紧接着狂风呼啸，裹挟着风压的拳头笔直朝罗伊袭来。

那声音异常缓慢　仿佛传到耳边需要很长时间──这才意识到。

「──这是佩特拉酱搞的鬼吗？」

「没错。我刻意留到最后才说。活该」

站立于地面的『忧郁魔女』在延展的时间中向罗伊宣告胜利。

对此，罗伊似乎已无计可施。此外，暴怒猛虎的拳击已逼近至五枚硬币的距离。

在遭受直击前，还能做些什么？思索间，灵光一现。

「好厉害好厉害真了不起啊，佩特拉。但是啊，为了胜利付出的代价是不是太大了点？」

「输不起吗？我们这边可没人被干掉哦。明明是大罪司教却这么难看呢」

「『忧郁魔女』当对手的话就没辙了。但是牺牲可不只是性命的问题。未来啊希望啊可能性啊，这些才是关键。从今往后佩特拉那漫长漫长的人生会变得多寂寞，我们都是发自内心担心啊」

──硬币，剩余四枚的分量。

至少，要将想要隐藏的代价挖掘出来，用那份痛苦将自己铭刻于她心中。

面对罗伊如此恶劣的进食行为，佩特拉眨了眨眼，露出一副茫然的表情。按理说，不可能有人会在不知代价的情况下就支付才是，那种反应──，

「──该不会是，误会了什么吧？」

「误会？」

「好奇怪啊。我还以为奥托先生肯定会说呢。──这次的敌人是整个世界之类的」

「────」

──硬币，还剩三枚的量。

并没有，被直接告知。但那种气概确实存在于『记忆』中。

考虑到阿尔德巴兰的所作所为及其造成的损害，可以说这是正当的认知。但那本应仅限于此才对。

「难道说……」

「那个难道」

──硬币，剩余两枚的分量。

在被拉长的感官中，虽无法奢求像屏息这般奢侈的举动，罗伊却在心灵的喉咙处吞咽着心灵的呼吸，注视着柔美地、如『魔女』般微笑的她。

本应未能适配魔女因子的少女，却无疑是『忧郁的魔女』。

因为──

「忧郁』的魔女因子，只要支付代价谁都能使用，只要代价足够对等谁都能代为执行。——所以就是王都的大家在共同支付啊

「────」

「那么我再说一遍。——活该！」

——硬币，还剩一枚。

因为，如此滥用『忧郁』魔女因子的存在，罗伊闻所未闻。

这要不是『忧郁魔女』的话，那还能是什么呢。

「──啊、多谢款待了」

剩余，零张。──『豪华虎』的一击，炸裂开来。

「────」

它毫不留情地击穿了罗伊的面门，将其打落到黑蛇翻滚的地面。那矮小身躯径直坠向污浊之中──就在刹那之前。

「──给我爆裂吧!!」

在如此咆哮的菲鲁特手中，闪耀光芒的法杖释放出淹没世界的白光。

这一击准确无误，化作无从逃避的断罪之击，将那些行径恶劣之徒统统吞噬。

──这便是『恶食』进食活动的，最后一幕。

** 第四章 『声』

１

──睁开眼睛的那一刻，自己究竟是何人，完全一头雾水。

『────』

身在何处、今夕何夕、姓甚名谁、发生何事，统统浑然不知。

眼睛看不见。声音听不到。手脚动弹不得。双脚悬空不着地。连呼吸都困难至极，简直寸步难行──但唯独，能感受到『声音』。

『────』

视觉、嗅觉、触觉、味觉，尤其是听觉都被封闭了，却能听见『声音』。

面对无数、众多、数不清的『声音』毫无招架之力的自己，简直就像被抛进地狱摇篮里的无助婴儿。

『────』

杂乱无章、毫无规律、持续袭来的『声音』风暴。

就像毫无防备地被雨水浇打的婴儿那般，我也险些溺毙于『声音』之中。干脆就这样溺死算了──

『──少爷！少爷，您没事吧！我这就来救您！』

──。────。听见了巨大的『声音』。

在众多、无数的『声音』之中，能清晰地感觉到那是朝着自己而来的『声音』。什么都做不到。即便如此也能明白。──那是指向自己的、强烈的『声音』。

所以──，

『──奥托大哥、给俺咬紧牙关撑住了』

听到那个『声音』后，漂浮感降临，激烈的声响──让鼓膜因『声音』之外的声音而震动，从全身的压迫感中解放出来。当紧闭的双眼准备好接纳光线时，终于能与对自己发出的『声音』及其主人们面对面了。

「『让你久等真是对不住啦。全都怪老子太弱了』」

「『您在说什么啊，加夫先生！要不是加夫先生和大家赶来，少爷现在还得吊着呢……啊啊，少爷，少爷！您认得我吗!?』」

在那里的是金发少年与拥有淡蓝色龙皮的巨型地龙。感受到的『声音』与听到的声音相互重叠，不会错。

地龙贴近坐在地上的自己，少年用力抓住了自己的肩膀。

「『现在你啥都搞不懂吧？不过没关系。咱们一起夺回来。老子不够的部分，就靠大家帮忙……啧！』」

「────」

「『所以说啊，奥托大哥就在这里……』」

应该是想说要保持安静。

看来，眼前的少年知道我一无所有的状况，似乎正想办法帮我解决。大概，连我为何会变得空洞的缘由他也清楚。

想要了解那个缘由、想要追问清楚。这股冲动，自然是存在的。

存在归存在──，

「『──有什么、我能做的事吗？』」

从唇间漏出的那道『声音』是否成了像样的语调，我并不清楚。只是，看到少年与地龙都瞪圆了双眼，想来应该是传达到了吧。

老实说，我什么都搞不明白。虽不明白，但唯有一件事能够断言。──对于自己被从那地狱般的摇篮中救出此事，我心怀感激。

更重要的是──，

「『──面对这般倾注真心前来相助的人们，任谁都会想回应期待的吧』」

「『啊，那是自然……』」

对我的话语瞪圆了双眼的少年与地龙，齐声吐息并合着『声音』说道。

「『──真有少爷的风格』」

「『真像奥托大哥呀』」

听着那阵『声音』，遥想变得空虚之前的自己，我不禁绽开了笑容。

──倘若存在将自己变成这样的某位人物，我倒想对它说句「这下你可满意了吧」。

２

「──哎呀呀!!」

高昂的银铃声般嗓音，伴随着与其轻快感形成鲜明对比的强力踢击贯入。

确认这记绝佳成果的同时，雷姆紧握住了晨星的握柄。

这正是将魔法制造的冰制落脚点同时用于实战与扰乱，吸引对方注意上空，并彻底贯彻对爱蜜莉娅援护的结果。

当然，若能直接用昴持续打磨出的爱情铁球决出胜负自是求之不得，但也不可过于贪心。昴在帝国时，面对雷姆也是实实在在地循序渐进了。倘若昴耐心不足，急着对雷姆宣称「我要我要」的话──

「那时候可能就不只是手指，连手臂和腿都会折断了呢」

如今记忆恢复，光想到自己竟会对昴做出那般粗暴之举就足以令人晕厥，但雷姆自己也觉得，以当时的心境很可能真干得出来。

所以说，凡事讲究步骤与阶段都很重要。这和烹饪是一个道理。尽管烹饪还算得上拿手，但除此之外总爱跳过步骤，正是雷姆的坏毛病。

而说到坏毛病，还有一个──

「──切忌过早下定论！」

轻易认定‘已经决定了’而松懈，正是缺乏想象力的表现。

思考停止是恶——曾如此告诫我的，正是那位教导了内心空白的雷姆如何定立心境的普莉希拉。──即便她已逝去，那份教诲依然存活。只要这份教诲仍让雷姆存活，它便会永远存续。

所以──，

「──呃、骗人!?」

即便爱蜜莉娅发出惊愕之声时，雷姆的思考也未曾停止。

眼下、从阿尔等人死角的正下方踢来的爱蜜莉娅，她那穿着冰靴的一击本该以足以折断脊柱的势头刺中阿尔。

但是，阿尔防住了那一击。──用岩石之箱覆盖住了他们自己。

「那就是罗姆大人所说的──」

雷姆判断那正是『时间溯行』的效果。

作为瞬间防御的判断，覆盖全身的那招实在是周全过头了。使用魔法需要结果想象和术式构建。无论缺少哪项魔法都无法成立，而且越是试图施展复杂的招式，结果想象所需的时间就越长。

阿尔的那一招，对于来自死角的奇袭印象过于固化了。

「────」

虽然头脑里明白原理，但再次面对这种犯规招式，雷姆不禁咬住了脸颊内侧。

原本，阿尔的权能就连莱因哈鲁特都能躲过已是事实。照这样继续攻击下去，会不会全部被化解呢的消极想法──

「──雷姆!!」

那股不良思绪的螺旋，被爱蜜莉娅的呼喊打得粉碎。

透过空中出现的岩箱缝隙，雷姆与爱蜜莉娅的视线交错。与险些被权能威胁压垮的雷姆不同，爱蜜莉娅紫绀色眼眸中的光芒尤为强烈。这给予了雷姆勇气。

「────」

唰地眼中恢复了力量，鬼化之角的活性化让雷姆全身充满活力。

身体不断向下坠落，开战至今已过去三十秒──能精确感知这点，是因为遥远后方可见的长长岩壁上刻着的印记。

カララギ都市国家に存在する巨大な大地の切れ目、アグザッド渓谷は地上から谷の一番深いところまで五千メートルの高低差があり、その落下时间はおおよそ百秒。岩壁に事前に刻んだ印は十秒间隔で、现在三本目を通过──地底まで、あと七十秒。

「还早得很──!!」

「──现在才要开始!!」

爱蜜莉娅与雷姆的声音重叠，凭借着获得的勇气与涌上的力量重新展开攻击。

雷姆大幅后仰身体扭转身体的爱蜜莉娅在双手生出冰锤瞬间如炮弹般势头的晨星裹挟横扫暴风的冰锤同时被释放那些击碎了阿尔们进入的岩石箱子──伴随轰鸣声四散纷飞的岩石碎片中上下分开的敌人向雷姆和爱蜜莉娅猛然袭来

爱蜜莉娅的方向有阿尔前往，而雷姆的方向则有红发忍术──

「──不对，你也是！」

「是的，正是阿尔大人的万能贴心女仆，八重酱」

「那是雷姆专属的昴君称号！」

并非忍术而是一头红发的女仆──不、自称为八重的她的开场白被打断，雷姆一边用右手拉回铁球，一边向着飞来的八重挥出左臂的刚腕。

但是，对此八重在空中做出不自然的制动，回避。

只见她用抛向身后的丝线将自己与阿尔相连，通过精妙的控丝技法操纵彼此的动作，躲开雷姆的攻击轨道，同时甩出的丝线却缠上了我的脖颈。

「──修玛」

迫近的威胁让雷姆肌肤刺痛，她凭借脊髓反射制造出冰项圈护住要害。当丝线缠上项圈的瞬间，她猛地抽头避开了被斩首的命运。——凭借瞬间判断捡回一命的雷姆，用铁球拽起微微挑眉的八重的后背作为目标。

然而，八重以仿佛背后长眼般的精准度闪开了从背后袭来的铁球，对着因错身而过时接住飞回铁球的雷姆所露出的惊讶表情吐了吐舌，

「正映在你的眼中哦？」

对于那份挑衅一瞬间差点就火冒三丈，雷姆受到了心中卡秋娅的叱咤。

「笨蛋笨蛋，这完全正中对方下怀吧！」对想象中像猫一样叫唤的卡秋娅点头回应，雷姆一边称赞着敌人那仿佛能利用对手眼中映现景象的高超技艺，

「既然如此，就请仔细睁大眼睛看好吧！」

そう言って、引き戻したモーニングスターの鉄球を氷で包み、包み、包み、その质量を倍化の倍化の倍化して、十メートル级の氷块として打ち下ろす。

「是不是我的挑逗有点太过火了呢!?」

轰隆一声，伴随着撕裂风压逼近的冰块，声音变调的八重激烈挥舞双手，连续刻印、刻印、刻印晨星冰块，通过分化、分化、分化质量来歼灭。

然后、最终剥除冰层只剩下光秃秃的铁球时、将其对准胸膛正面、用网状分布的丝线分散冲击力承受住、被猛烈地向下弹开。

在坠落的前方──

「这次！和！王都！那时候！不一样！不会让你！逃掉的！哦！」

「普通！　那样！　做的话！　就是我赢家通吃！　对吧！」

互相冲突的爱蜜莉娅与阿尔，正彼此用言语和武器激烈交锋。

两人周围各自漂浮着由冰与石块随意制成的武具，他们不断随手抓起近处的武器——不分敌我——挥舞互击。

「呀！　嘿呀！　欸！　呜呀！　看招！　叮叮叮叮叮叮！」

与可爱的呼喝声相反，爱蜜莉娅的攻势毫不留情、连绵不绝。

但阿尔以杂技般的动作，用最短距离挥出的斧、枪、剑，持续格挡着爱蜜莉娅如雨点般落下的剑、枪、斧。这恐怕也是『时间溯行』的成果——先承受攻击，在命中前回溯，再将武器置于曾被击中的位置。如此循环。

「──阿尔大人！」

就在这进退拉锯的攻防间，被雷姆击落的八重追了上来。糟了——短暂形成二对一的局面，雷姆也为加速坠落而试图踩踏借力点——不，

「爱蜜莉娅大人！」

刹那间的判断下，雷姆并非指望自己能追上，而是将希望寄托于先行一步的铁球。

冲击被八重驱散，即便如此仍以同样速度坠落的铁球，仿佛寄宿着打磨得锃亮的昴的心意气一般，向着身处困境的爱蜜莉娅飞扑而去。并且，在阿尔与八重的同时攻击抵达她之前，让爱蜜莉娅抓住了锁链。

「呜、呀啊啊啊啊!!」

将此前制造出的落脚点并非用于蹬踹而是用作支撑，把抓住锁链的爱蜜莉娅垂直钓起──如同割裂即将汇合的阿尔与八重般将爱蜜莉娅拽向上空，使双方分据上下空间，阻止了两组人的汇合。

「谢谢！超级难对付！」

「不客气！深有同感！」

与来到同一位置的爱蜜莉娅携手合作，雷姆感叹敌人的棘手程度。

原本雷姆她们只需应对阿尔一人，但八重的介入实在太过麻烦。不仅是单纯变成二对二的局面，她本人更是实力超群。而且这份实力与阿尔并肩作战时并非简单叠加，而是呈倍数增长。

「是啊，简直就像我和那个人一样……」

「咦？刚才提到了昴吗？」

「非常抱歉，这件事请容后再说！」

雷姆边瞪圆双眼的爱蜜莉娅这样回应着，边再度穿过岩壁上的标记──确认距离抵达地底还剩六十秒后，用力咬紧牙关。

先前的想法是对的。八重很强，和阿尔在一起就更难对付了。

要想解决那个，虽然于心不忍──，

「将两位分开。爱蜜莉娅大人！」

「嗯！配合我！」

彼此紧握着手，爱蜜莉娅将空着的手、雷姆将握着武器的手，分别朝向眼下的两人──，

「阿尔──」

「──修玛!!」

两种修玛混合交织，伴随大气嘎吱作响的声音，冰块在半空中显现。

当然，仅仅扔出石子是够不着阿尔他们的。所以为了不重蹈覆辙，不是在释放冰的方式上，而是在出现的位置上下了工夫。

「切──」

被蔓延的冰阻挡，听不见头盔内的咂舌声。但只要看结果就能确信，对方肯定咂舌了。

雷姆与爱蜜莉娅的协同魔法，制造出薄而平的冰板，夹在处于上下位置的阿尔与八重之间，阻碍了二人的汇合。冰板在保持强度的同时，是扩张至极限的直径三十米的圆盘。在下落过程中难以潜入或越过，加之平坦的设计使得八重的丝线也难以切断。

「阿尔先──」

「──八重，暂时撑住」

隔着冰板手叠着手，冰下的阿尔这样对冰上的八重命令道。感受到此，八重陷入了何种心境，雷姆了然于心。

正如雷姆为了昴而进行这场战斗，八重也同样如此──

「被重要的对象期待的话，就会干劲十足呢」

「不对」

对雷姆的认同冷淡回应，屈膝的八重轻旋身躯变为赤足。

冰板因其巨大体积承受空气阻力，下落速度显著减缓。八重落于冰面之上，雷姆与爱蜜莉娅也随后降下，一前一后地包围了她。

「──重新想想，魔法还真是麻烦呢～。不过不过，真是吓了我一跳。听说要一起使用魔法，是相当高难度的技术吧？」

「没错。因为魔法最重要的是要将结果具体地想象出来」

如前所述，魔法的重点在于对结果的想象，而要与他人共享这种想象是很困难的。

因此，即便魔法使们协同作战，术式的构筑与施展也是各自独立的。像刚才雷姆和爱蜜莉娅那样，协调发动一个魔法的情况很罕见。

即便如此，雷姆确信能够做到，爱蜜莉娅也回应了这份期待。

那一定是因为思念着同一对象而产生的同伴间的共鸣──，

「──也就是说，是爱」

「……我虽然不太喜欢那个结论，但还是归结为两位魔法用得好的缘故吧」

「虽然遗憾，但能得到夸奖我很开心。因为我的指导老师是位非常出色的人」

「我也是。莉娅告诉我要自由自在地去发挥呢」

「那和我在村子里时接受的教育方针一样呢～爱蜜莉娅大人果然也是天才型的啊～」

带着苦笑耸了耸肩的八重，她说着「那个啊」，看了看前后的雷姆她们，

「我既然会在这里现身就证明各位的计划已经失败……波克大人很快也会赶来，不如省去无谓的周旋直接投降？」

「不行哦～虽然确实没想到你也会一起来着实吓了一跳……」

「雷姆等人也并非在玩闹。况且你们倚仗的『神龙』大人此刻并不在场呢──因为我们主上正在亲自招待他」

「……对手可是『神龙』哦？是不是期待过头了？」

「那么，你是不相信阿尔吗？」

八重歪着头对爱蜜莉娅的提问「唔」地屏住呼吸，悄然摆开架势。她手足二十根手指上戴着的戒指──虽重量各异，却给人以同时操控二十把晨星战锤的神技预感，雷姆握紧铁球，爱蜜莉娅则凝出冰霜双剑。

余光瞥见的冰层下方，不受风阻影响的阿尔仍在不断下坠，与他们的距离越拉越远。

而阿尔正是在为八重争取时间。──她必定在酝酿着什么计策。

「爱蜜莉娅大人，阿尔先生他……」

「嗯，我明白。必须超级～抓紧时间了」

在简短完成的沟通中，果然雷姆对先前八重疑问的回答确信无疑。能跟爱蜜莉娅如此心意相通，若是没有昴在的话简直无法想象。

抛开雷姆的心中思绪不谈，冰上的三人静静地、昂扬着战意──，

「──『红樱』八重・天膳」

「──『冰结魔女』爱蜜莉娅」

「──『英雄的辅佐人』雷姆」

报完名号的同时，雷姆与爱蜜莉娅踏破冰面逼近八重。

从屈膝蹲下的八重手中，二十条丝线如跃动般放出，一边用锁链与魔法将其击散，雷姆为了触及冰下的阿尔，向阻挡在前的『红樱』发起挑战。

「呀啊啊!!」

咆哮呐喊着的雷姆，既非逞强也非虚张声势，而是完全相信着。

相信拉姆他们会对付『暴食』们，而关于最大威胁的『神龙』，罗兹瓦尔他们也必定会各自好好完成任务。

为此，现在就要打倒眼前的八重，抵达阿尔身边。

又通过一处标记、距阿古兹阿德谷地底还有五十秒──

──阿尔一边向下落入冰层深处，一边凝视着冰面上那场美丽而激烈的冲突，

「我不认为你会输……但别忘了啊，奥尔塔。你还有非做不可的事」

那仅在口中喃喃的低语，终究未能传至冰面之上。

３

──背叛太阳的阿尔德巴兰及其共犯们。

与可能引发世界崩溃的恶徒们的战斗、与山中的『暴食』的战斗、以及与阿古兹阿德谷的阿尔德巴兰的战斗，全都进入了下一阶段。

当然，预计最为残酷的第三场战斗也不例外。

借由这世界新诞生的『忧郁魔女』权能，战场转移至无需顾及周边损害的岩地带，身为王国守护者而广为人知的『神龙』波克肯尼卡──此刻，能随心驾驭其强大龙壳的篡夺者，正与正统龙人相对峙。

各自蕴藏着强大力量的同伴之间的战斗，原本只有岩石与砂砾的岩原野上，仿佛承诺了永远的不毛一般激烈，又激烈，化为了描绘出壮绝的情景。

那正是，与『神龙』的战斗中所预想到的战祸。

但是──，

「──唔」

视野模糊，意识朦胧，耳鸣声超过了吵闹变成了无声。使不上力的手脚，甚至连两对是否都好好地连接在躯干上都不知道。

每次细微呼吸，从头顶到脚尖都有种如同被闪电击中的疼痛，是因为折断的骨头把体内伤得遍体鳞伤吗？又或者，是从负荷过重的门反馈超过了容许量，身体快要裂开了也说不定。

想到那里，才意识到自己正仰面倒在破碎的岩石大地上。

「────」

一个，明白了自己的状态后，其他也渐渐明白了的事情。

大地在摇晃，天空仿佛要炸裂的感觉，大气中浓重地显现出玛纳激烈冲突引发的玛纳风暴的影响，自己倒下似乎还没过多久。一分钟？三十秒？

「──五秒钟，老爷。报告完毕」

怀抱疑问的答案被准确传达，然而，连牵动嘴角苦笑的余力都没有。

对方也没期待回答。──不对、是根本没法期待吧。大地的震动、天空的爆裂、大气的玛娜风暴一切的起点都是对方和那个对方。

『龙』与龙人的战斗，如同天变地异般狂暴，以蛮力改变世界。──在那场战斗的旁边，倒着一个别说半死不活、根本是九死一生程度的人。

「────」

已经，连声音都听不真切了。

──罗兹瓦尔・L・梅札斯的性命，已是风中残烛。

４

「──罗兹瓦尔和柯林特先生都说能做到呀。应该没问题吧？」

那是《阿尔德斯巴斯》作战会议中的一个场景，在讨论该由谁来对抗『神龙』波克肯尼卡时，爱蜜莉娅的发言成了决定性的一击。

不听取详细说明就将战场托付给爱蜜莉娅的判断，这并非欠考虑的轻率之举，而是基于确凿的信赖，罗兹瓦尔对她感到钦佩与感激。

形势所迫。罗兹瓦尔早已半作觉悟，即便会让多年计划稍有偏差，此刻也必须揭露柯林特的来历──那就是『神龙』之龙人的真实身份。

「但若要说明此事，就不得不提及我们之间的契约」

理所当然地，罗兹瓦尔在知晓柯林特身为谁人龙族后，仍以梅札斯家仆身份接纳了他。这自然并非看重其身为管家出众的才能，而是认定他的存在颇具价值。

对于罗兹瓦尔必须完成的夙愿而言──此人乃是不可或缺的人才。

「纵使坦言相告，想必各位的态度也不会改变吧。谏言」

知晓内情的柯林特向隐瞒此事的罗兹瓦尔如此进言。

并无顽固否定的理由。事实上，罗兹瓦尔也持相同见解。即便公开罗兹瓦尔的隐情，阵营中爱蜜莉娅她们的态度恐怕也不会动摇。

即便如此，罗兹瓦尔仍不愿说明原委，这只能说已是他的本性了。

罗兹瓦尔啊，不把自己放在优势地位就无法与他人对峙。要掌握对方的意图，抓住弱点，理想情况下还想扣个人质。

无法承受失败的年月累积，将罗兹瓦尔塑造成了怯懦的恶人。

所以说，就算知道昴和爱蜜莉娅他们是非常善良的一群人，罗兹瓦尔也没法坦白自己的真心。

「不过嘛～我倒不觉得这会有什么问题呢ー」

重要的不是全盘托出，而是充分发挥与能力相符的真正价值。

在这一点上，罗兹瓦尔自负绝不落后于伙伴们。倒不如说，正因为怀着隐藏真心的愧疚，他反而觉得必须展现出成果才行。

「……亏欠？身为‘魔女’弟子的我？」

虽然内心抱有那样的疑问，罗兹瓦尔还是将其暂且搁置。

无论如何，在未透露柯林特内情的情况下，罗兹瓦尔决定与他共同踏上战场——迎战夺走『神龙』龙鳞的敌人。

接下来——，

「趁此机会试试手吧。——为我屠『龙』之术的精进」

５

——那场战斗中，根本不存在什么热身试探。

摘下单片眼镜，周身缠绕紫电的柯林特——头顶生出漆黑双角的他，褪去长久佩戴的万能管家面具，化作独一无二的龙人。

一步踏出的瞬间，鞋底迸发雷光，弹射的初速追上了音爆。

「────」

大气爆鸣，每步踏落都如炮弹轰击般震撼天地。

炸裂的紫电化作推进力，柯林特笔直冲向端坐苍穹的威仪巨影。——展开雄壮龙翼、背负太阳的『神龙』波克肯尼卡猛然张开颚门。

刹那，喷吐的龙息化作白色热线，将柯林特迎头吞噬。

『龙』之吐息乃是纯粹的玛纳奔流，是未赋予魔法指向性的纯粹力量。即便如此，一滴无害的水汇聚成束亦能化作冲毁国家的洪流，获得压倒性势能的玛纳足以轻易蚀现实世界──，

「──作为开幕问候可算不上高明。太拙劣了」

那道都市崩坏级的白光，被柯林特挥落的手刀如劈竹般斩断。吐息从中裂开，为避开直击他而向背后泻去。取而代之的是大地被烧灼剥落，崩碎的岩片化为砂砾，连砂砾也熔作带有粘性的赤红流体。

弃此残局于不顾，率先突进的柯林特身形高跃，直逼天际的『龙』。

『啧，烦死了！』

咆哮的『龙』扭转身躯，甩动粗壮坚韧的巨尾。绞杀着风旋回的尾击，将无处可逃的柯林特迎头击中──惊雷轰鸣响彻。

一道格外强烈的紫电照亮天空，下一秒被弹开的竟是『龙』的尾部。

原理与跺地加速相同 是通过缠绕的紫电炸裂产生的冲击波。柯林特将其作用于空中自己的脚底 把冲击当作立足点 再将肩膀到手肘乃至拳头依次引爆雷光 以难以置信威力的拳击对抗『龙』之尾。

而更令人畏惧的是　那股紫电──

「再陪我玩一会儿吧。无尽」

云层散尽的晴空之中，无视天气状况的闪电光芒层层叠叠地闪烁不定。

『噢噢噢噢噢噢──!!』

怒吼声响彻云霄的『龙』振动双翼盘旋回转。每当紫电迸发，柯林特便以更快的速度在其周围纵横无尽地穿梭跳跃。

これまでと同じく、靴里に発生した紫电の炸裂がクリンドを宙に浮かせ、翼を持たない竜人に空を自由にする権利を与えていた。无论、勤勉な竜人は空中游歩を楽しむだけではなく、『龙』へと猛撃を加えることを忘れない。

「────」

以毫厘之差躲过挥来的龙爪，缠绕雷光的打击砸进体格与攻击距离都远超自己的对手面部，随即引发了最高潮的雷爆。打击+雷击的双重攻势，这并非一次两次，而是在眨眼间叠加了十次二十次。

『可恶──』

被重叠紫电的雷爆夺去制空权，唾骂的『龙』进一步提升了高度。

不仅是放眼望去尽是荒野的地面，若将天空也包含在内便是三百六十度，拥有翅膀的『神龙』特权便是不分三维战场。

但是──

「──阿尔・二重奏」

──提升高度的『神龙』，一头栽进了巨大的水块中，迷失了上下方位。

『──!?』

在惊愕中吐出大气泡的『神龙』，其巨躯被包裹进了由周围湿气与地底抽取的水流汇聚于一点所形成的、直径超过数十米的水球之中。

伴随着水压发出的嘎吱声，被水之牢笼囚禁的『神龙』睁大了黄金之眼。

「把我忘在一边自己倒是挺嗨嘛，真冷淡呢ー」

那条『龙』的视野下方，将『龙』囚禁在水球中的罗兹瓦尔露出笑容。

立于最初被柯林特斩裂的吐息、其热浪掠过而形成的黑亮玻璃质地表上，罗兹瓦尔指向天空中的水球，步步紧逼。

二重奏即双重奏，这魔法也并非将龙囚于水球便告终结。——紧接着，封住『龙』的水球因产生的灼热而泛起泡沫，开始沸腾。

此时，又一道紫电强烈闪烁——

「稍显、华丽地献上了。轰雷」

柯林特挥出的拳头伴随着雷鸣刺向水球。——刹那，闪光窜过整个水块，紫电在内部奔腾，灼烧着『龙』与水球本身。

下一瞬间，热力与压力达到极限——水球随着轰响爆散。

失去去处的紫电撕裂战场，堪比爆炎的水蒸气风暴呈放射状肆虐，幸存于白热化的水块如雨般自晴空倾泻至大地。

「────」

引发的强烈爆轰，其威力足以将小镇规模的区域彻底湮灭。

虽说有龙人相助 但魔法使本不该以单人之身发挥此等破坏力 如今这毫不留情的一击纵然是『龙』也──

『──啊啊 可恶 脑袋都凉透了』

龙翼划破白色蒸汽 化作爆心地点的空中 『神龙』如此嘟囔着。──没错 是嘟囔。若是伤势或轻或重 这嘟囔想必会化作咒骂吧。

也就是说 悬空的『龙』安然无恙。──不 是毫发无伤的状态。

「……虽然早就知道了，但亲眼看到还是会消沉嘛～」

仰望着那无损生还的身影 罗兹瓦尔闭上一只眼 只留下那只青瞳。

面对那般火力却毫发无伤的『神龙』。这并非罗兹瓦尔的魔法威力不济 也非『龙』瞬间想出了最佳防御法。──真相虽接近后者 但事实却更为绝望 是压倒性的不合理。

「老爷 请勿气馁。激励」

在罗兹瓦尔身旁　为躲避爆轰而落下的柯林特着地了。

一边用紫电烘干淋到的水球的水，一边表情和声调都不变地说着话的柯林特，但那其中有着长久交往所传来的些许关心。──在那漫长的交往中，关于『神龙』的不讲理也从他那有所耳闻。

「──果然，保护『心核』的龙鳞和龙晕很麻烦呢ー」

克莱因特的鼓舞并没有得到回应，罗兹瓦尔将此作为自己仍未丧失战意的证明说出口。──龙鳞与龙晕，这正是令『神龙』波克肯尼卡被称为地上最强存在的最大理由，也是必须跨越的不合理之理。

「────」

──『云龙』梅佐蕾娅与『邪龙』巴尔格伦，这两条『龙』与『神龙』波克肯尼卡的区别究竟在何处，其答案就在于龙鳞与龙晕之中。

尚且年轻、作为『龙』正处于成长途中的梅佐蕾娅，以及因创造的龙人死去而失去精神均衡、丧失了未来的巴尔格伦。二者均未能充分培育龙壳，无法锻造出『神龙』所拥有的两种铠甲。

那就是──

「物理性的攻击无法穿透的龙鳞，以及魔法性质的攻击无法近身的龙晕」

「如果不能攻克那双重铠甲，就无法触及『龙』的心核。再确认」

柯林特的话甚至让人感到绝望，那正是攻略『神龙』最大的难关。

拥有压倒性物理防御的龙鳞，以及超乎常理的魔法防御龙晕，不剥开这两重强大的防御，就无法将攻击送达其弱点『心核』。

不是两者择一，而是两者都必须。必须剥开双重铠甲，否则无法超过作为魔力体的『龙』那惊人的恢复力，无法使其陷入战斗不能状态。

所以，要打倒『神龙』，就需要近身战和魔法战两方面的专家。

不过──，

「在剥掉龙晕之前，那种火力居然都无伤，真是服了呀—」

「不愧是被称为地上最强的『龙』，绝非虚名呢。叹息」

「刚才那叹息是不是有点炫耀的意味啊—？好歹它原本也算是你的对手嘛。只有你知道的弱点什么的，偷偷告诉我也可以哦？」

「有的。是『龙剑』。即刻回答」

「也太直白了吧……」

被即刻回答的『龙剑』，是一把能够斩断不可斩之物的魔剑。

凭借那『龙剑』的性能，想必确实能无视龙鳞与龙晕，直接攻击到『心核』吧。搞不好光是拿『龙剑』殴打，就能对『神龙』造成伤害。

当然，讨论一件不在手边的武器也只是空谈，于事无补。

「仅供参考，龙鳞的话以颈部的逆鳞为目标比较好。那是旧伤。至于龙晕嘛……就看老爷您努力的程度了吧。期待」

「现在，对一个第一张王牌都没奏效的我，这话说得可真轻巧啊ー」

「是这样吗。──如果是艾姬多娜大人的话倒是能做到。独白」

「────」

真不愧是彼此交情长久才能有的对话啊。

对于厚着脸皮如此补充的柯林特，罗兹瓦尔虽然心知肚明这正是对方的意图，但心中还是切实地被点燃了火焰。

当然，即便现在，罗兹瓦尔也没有狂妄到认为自已已经赶上了老师──，

「身为学生，总不能让老师蒙羞ー是吧」

必须完成的宿业与渴望达成的悲愿，为罗兹瓦尔伤痕累累的灵魂注入活力，让聚焦于眼前课题的双眸充满力量。

魔法的历史就是反复试错的过程，罗兹瓦尔的人生亦是如此。

刚解决一个问题，下一个难题立刻接踵而至，就这样不断探寻解法持续挑战。但正是因为攻克了所有难题，自己才能站在这里。

失去师长之后，始终如一地，独自一人。

「本来就不存在比我更具可能性的人类」

斗胆自称吧。罗兹瓦尔无疑是现代最强的魔法使。

不存在任何比罗兹瓦尔更可能突破『神龙』波克肯尼卡龙晕的可能性。──不，就连那微小的可能性，也在这四百年间被培育壮大。

在魔法领域，不可能存在罗兹瓦尔无法跨越的难关。绝不允许存在。

这正是罗兹瓦尔・L・梅札斯的誓言，也是他决心独行的荆棘之路。

因此──，

「──我将赌上我的全部存在，超越这个难题」

伴随着这句决心的话语，罗兹瓦尔为了再次突破前人未至的龙晕，开始在天空中描绘足以让常人脑浆沸腾的术式。

６

──克里恩德认为，『龙人』这一立场实在相当棘手。

说到底，龙人终究只是『龙』的次世代形态，严格来说并非与作为原型的『龙』是同一存在。尽管如此，却继承了『龙』大部分的记忆、经验与感情，背负着难以割舍为不同存在的精神混杂。

这点克里恩德也不例外，波克肯尼卡时代的影响深深烙印在如今自我的存在方式中。──若要说具代表性的例子，就是对不成熟可能性的强烈憧憬。

对于生来便是作为『龙』这一绝对种族诞生的波克肯尼卡而言，能自行决定生存方式、朝着目标成长的人类的不成熟，既耀眼又珍贵。

这一特质在成为龙人的如今依然延续着，眼下克里恩德对蕴藏巨大可能性的不成熟存在──幼子怀着无尽的尊敬、敬爱、珍视、怜惜与疼爱。

如此这般柯林特的、可谓是从前世带来的天性，法兰黛莉卡等人似乎存在相当大的误解。只不过，法兰黛莉卡自身另有想要隐瞒的龙人族隐情，因此连她周围在内，都一直未曾主动去解开这个误会。

「话虽如此，要是因此被安妮罗洁大人和佩特拉、碧翠丝大人和梅莉、爱蜜莉娅大人疏远的话，还是有点让人窝火呢。不服气」

总而言之，不仅是柯林特，『龙』与龙人族之间有着斩不断的联系。

龙人族的成长会促使『龙』成长，龙人族的死亡会扼杀『龙』的精神，这份联系显而易见——事实上，龙人族若有需要，甚至能将自身精神寄宿于天空的龙骸之中，尽情发挥作为『龙』的真正力量。

「听说在帝国，梅佐蕾娅和那位龙人少女也曾这样做过。感兴趣」

柯林特成为龙人族也已很久，但与其他龙人族几乎毫无交集，对于在佛拉基亚新诞生的玛德琳，他倒是想着日后有机会能交谈一番。

她所声称的对龙壳的灵魂寄宿，柯林特也曾多次回归到『神龙』波克肯尼卡身边，为了履行与露格尼卡王国的盟约而来。

「不过，现状是龙壳的支配权被某种手段夺走了。犯规」

原本，龙人只需触摸龙壳就能将灵魂寄宿到自己的『龙』中。但对于柯林特来说，时隔约四十年的灵魂归乡失败了，龙壳落入了篡夺者手中。

「并非没有担忧过……。痛心」

无论『龙』这种种族多么强大，夺取空壳的手段并非为零。

正如柯林特所知，邪精灵中有着能够依附他人身体的力量存在，同伴之间也曾谈论过，若是那种力量的话，或许也能夺取龙壳。──与名为修斯的邪精灵，已经很久没见了。

「如今已是无用之事。感伤」

いずれにせよ、『龙』が竜壳を夺われる事例はありえることであり、竜壳を取り戻すためには『心核』を打つ必要があるとクリンドは知っている。──问题は、竜壳を夺われたのが『神龙』で、竜鳞と竜晕が『心核』への障害となって立ちはだかっていることだ。" -> "不管怎么说，柯林特都知道『龙』被夺走龙壳的情况是有可能发生的，而要夺回龙壳就需要击打『心核』。──问题在于，被夺走龙壳的是『神龙』，龙鳞和龙晕正成为通往『心核』的障碍阻挡在前。

「龙鳞这边由我来戳逆鳞，龙晕的突破则非老爷您莫属。请专心」

『神龙』拥有的绝对防御、在龙鳞与龙晕深处守护着的『心核』──击中它，便是柯林特与罗兹瓦尔被托付的战场的胜利条件。

幸好啊，已经找到了突破龙鳞的方法。──在与『剑圣』雷德・阿斯特雷亚的生死搏斗中留在他脖子上的白色旧伤，正是这绝对防御的唯一破绽。

「转来转去，竟然是那个无礼之徒的一击成了活路真是气人。气死我了」

那个吃龙肉的变态，一会儿说要尾巴，一会儿嚷着要吃肠子，最后甚至试图挖出心脏。他到底把旅伴当成什么了。

最终演变成互相残杀——且不论受伤的经过，龙鳞的突破口已经存在。

因此，通往胜利的道路在于罗兹瓦尔能否突破龙晕之壁。

「这就是我需要挤出时间来完成的任务。专心」

四百年、罗兹瓦尔一直钻研不息。如今，这份钻研正面临考验。──在这场极致的试炼中，柯林特再度切身感受到『龙人』是何等棘手的存在。

从名为罗兹瓦尔的不成熟之处开始的生命燃烧方式，那份耀眼，对于柯林特而言是无比尊贵、惹人怜爱、必须加以呵护的对象。

『────呜!!』

令苍穹畏惧，使大地战栗，威胁世界的『神龙』咆哮声响彻四方。

力ある声は振动を天地に伝播させ、空を裂く轰音が奔流となってクリンドを呑み込む。引き裂かれていく音、それに巻き込まれ、クリンドの体も裂け、爆ぜる──寸前、生じた大量の雾の中に紫电を缠って飞び込み、天鸣が文字通り雾散する。

细小的水粒子为声音开辟道路，大幅削弱了毁灭性的冲击波。

「──阿尔・特里奥」

越过雷驰于雾中的柯林特，逼近『龙』的是三色光辉。

红蓝绿三色光芒绚烂共鸣，刹那间膨胀的光芒灼烧天空。──百米规模的爆风与烈焰骤然生成，肆虐的冰火风暴裹住『龙』，宛若世界终焉的色彩与景象将战场的晴空涂改为人间地狱。

「嘘──！」

朝着那片地狱，柯林特伴着空中电光疾驰着投身而入。

在世界终焉、化作地狱的战场景象中存活，并将此作为自身存在的证明肆意挥洒力量，正是经历过『魔女』时代的强者之证。

『──欢迎光临!!』

统御着绘制支离破碎混色图案的天空，证实仍安然无恙的『神龙』发出高亢咆哮。

展开龙翼的『龙』背后，那里悬浮着岩块构成的巨臂，总计十二根的它们如同欢迎的喝彩般猛烈咆哮，刚拳迎接着柯林特。

「──封枷、第二解禁」

在与岩石巨臂撞击的前一刻，柯林特头部黑角释放的光芒增强了一档。

迸发的紫电，缠绕其身的柯林特暂时获得了与『龙』同等的防护。柯林特将这种坚固运用于攻防，把全身当作不坏的武具来抗衡『神龙』的攻击。

轰雷一闪，令天际发出惨叫的紫电爆发击碎了『龙』创造的岩腕，实现了体格悬殊二者的乱打战。

「竟采取不顾形象的战斗方式。实在难以想象是『龙』所为。颇具创意」

『讲究漂亮取胜的阶段早就过了八百年啦。我看来最近的敌役趋势就是——真正的强家伙会毫不迟疑耍阴招！』

一根、两根、三根，随着巨臂接连被砸碎，柯林特对这个答案表示赞同般点了点头。

自赞并非我的爱好，但能将『神龙』波克肯尼卡的龙壳运用得最娴熟、最强大的果然还是柯林特。无论容器多么强大，若内容物不同便无法完全发挥其本领。

而那不足的部分，篡夺者并非通过激发龙壳的真正价值，而是选择了若是『龙』便不会使用的伎俩滥用来弥补。

并且那些伎俩的范围，已达至毫无可爱之处的领域，将柯林特逼入绝境。

『──呃咕』

挥舞着十二只巨腕与龙爪、尾击风暴的『神龙』，其喉咙深处正轰隆着盘旋起光芒。

那是同时锤炼、在『龙』的口腔中被压缩的炎与水的奔流。并非常识中炎水相抵。被禁锢的庞大热量与水分无处可逃，为寻求力量的出口而破裂──刹那，柯林特在自己正面生成紫电冲击波，企图借助向后弹开来脱离那『神龙』的瞄准。

「──唔！」

那道攻击、被如同围困般延伸出的岩石巨臂所阻挡。试图用雷爆乱舞炸飞那包裹般握紧的岩石手掌──却、

『──给我吹飞吧！』

──紧接着，伴随着震耳欲聋的轰鸣声，整个战场如同遭受重击般发生了剧烈爆炸。

将所有产生之物燃烧殆尽的热浪，连同撕裂世界的冲击波，一同袭向无处可逃的柯林特全身，对向『龙』挑战的愚者施加了过度的天罚。

「……呜」

猛地用力咬紧后槽牙，柯林特解除了覆盖全身的紫电屏障。他瞬间激发黑角，以紫电最大输出张开了堪比龙晕的防御壁。即便如此，若果真硬接下方才那一击，即便是柯林特也难免遭受致命伤吧。

没错，若是硬接下的后果——

「——阿尔・四重奏」

发出那道声音的正是柯林特身后、越过被烧毁失去原形崩落中的岩石巨臂咏唱大魔法的罗兹瓦尔。

使用飞行魔法升空、加入了柯林特与『神龙』空战的罗兹瓦尔，以同时发动四属性的高超技艺抵消了那惊人的爆轰。

『喂喂，真的假的啊……』

面对这一事实，『神龙』会发出惊愕的声音也无可厚非。

刚才篡夺者的一击，其破坏力足以达到毁灭城市的级别。而对方不仅以人类之躯抵消了攻击，还成功守护住了柯林特，这等控制力已然超出了常理。

只要稍有差池，反而会增幅『神龙』的攻击，搞不好两人都会变成焦炭。这简直就像是在一公里外穿针引线般的神技。

不过，还称不上是完全胜利。

「……真是服了，呐—诶」

如此虚弱地抱怨着的罗兹瓦尔脚步踉跄，失去控制地头朝下坠落。

「旦那様！　急行」

对着那坠落的罗兹瓦尔猛蹬空中紧追而至，柯林特瞠目结舌。

罗兹瓦尔的身体仅因相互抵消的爆轰余波就被撕得粉碎，尤其是受损严重的右臂已化作惨不忍睹的焦黑溃烂肉块。

尽管罗兹瓦尔能运用所有魔法，唯独治愈魔法无法使用。带着这般伤势能否继续战斗，实在太过──

『别见怪，起源正等着呢！』

「呜──！」

然而抱着负伤罗兹瓦尔的柯林特，『神龙』并未手下留情。

柯林特一边为让罗兹瓦尔负伤的不明失误感到羞愧，一边以炸裂紫电的雷走术不断腾空闪避卷起旋风的龙翼化成的斩光，踢碎风刃，用身体格挡横扫的龙翼，借雷爆冲击顺势向后跃开。

强行拉开距离重整态势的刹那──『龙』之尾击已然落下。

「──」

将雷爆冲击转化为旋转力，硬生生吃下『神龙』甩尾的重击。

虽然用下意识护住脑袋的手臂躲开了致命一击，但朝地面直冲而下的威力依然惊人。即便直接坠落大地，惯性也足以掘出坟墓般的深坑──，

『──补刀要上喽』

对着向下坠落的柯林特等人，如此宣告的『神龙』深深吸了一口气。

在高速攻防转换的战斗中，需要蓄力的动作会致命。因此，除起手外被视作封招杀手锏的全力『龙』之吐息，此刻正要释放。

即便施展雷走也无法逃离这场毁灭，已然无计可施。──至少对柯林特而言。

「──阿尔・昆塔特」

原本浑身松弛卸力，将攻防全部抛给柯林特的罗兹瓦尔，其积蓄到极致的最大火力终于发动。

──已成形的术式启动时，天穹显现出将五道光芒收束其中的巨大魔法阵。

火与水、风与土、再加上阳──通过超越人智的合理方式叠加重合相反之理并收束而成的存在，乃是仅允许存在于秩序外侧的压倒性毁灭力量。这股力量与『神龙』释放的吐息正面冲突──瞬间，世界失去了声音与色彩。

「────」

解放的力量与力量交织，鲜明地撕裂了天地之间的交界线本身。

烈火狂吹、天空冻结、旋风涡卷、大地剧烈隆起，所有这些都被光所增幅，矛盾的五种力量化为光柱，战场接连不断地崩坏。

在战斗开始前还遍布岩石的荒野一带，此刻充满了令人失去上下方向感的光与轰音的乱舞，一切都被吞没进混沌的坩埚之中。

「────」

就其破坏世界均衡的意义而言，这已是足以匹敌由欧德・拉格纳抹消存在的众多禁术的术法。它之所以未被作为禁术消灭存在，无非是因为根本无需禁止――世上压根没有能使用它的人。

曾让与此相同的宏大魔法──不、超魔法得以实现的，唯有『强欲魔女』艾姬多娜与『最初的魔法使』缪缪缪仅此二人。

涉足禁忌的超魔法，并非『破坏』而是『否定』的一箭。

「老爷，您这个人啊……真是让人佩服得五体投地」

谁又能相信这幅天翻地覆的景象，竟是一个人钻研的证明呢。

那人走过的道路与刻下的足迹，其细节多是为伦理所不容的行径，或许会遭人厌恶憎骂，否定其存在方式。

但是，柯林特并没有否定。也没有轻蔑。或许这是值得轻蔑的吧，但当目睹超越了限度的某种事物时，内心涌起的冲击对人类和『龙』来说都没有区别。

实实在在、被彻底震撼了。人类啊、竟然能够积累到这种地步吗。

──柯林特、深爱着人类的可能性。

天生弱小脆弱又不完整的他们究竟追求什么、渴望什么，这兴趣永无止境。从这个观点来看，罗兹瓦尔曾是接近最高分的保持者。

据柯林特所知，再没有比罗兹瓦尔更不堪、更执着于遥不可及的可能性而持续挣扎的人了。

──若是没有才能，本该能更早放弃。

──若是能成为像『剑圣』那般被选中的存在，本不必如此痛苦。

两者皆非的罗兹瓦尔所拥有的，唯有超乎常理的执念。

所以柯林特才尊敬其存在方式，认同其前行脚步，并施以援手。

「那份祈愿至今仍在我心中持续闪耀。——誓愿」

如此立下誓言，柯林特缓缓将罗兹瓦尔平放在地面上。

这位流着血泪、因过度滥用高强度门而全身痉挛的稀世魔法师，与其功绩相比，这沙之床榻实在过于简陋，但眼下也只能让他忍耐。

──只因承受了魔法师极限之境的『神龙』，此刻仍毫发无伤地存活着。

７

──就这样，现实向着已将生命置于风中之烛的罗兹瓦尔追逼而来。

「——还剩五秒，老爷。报告」

迎来四散意识回归的，是异常冷静的声音。

ただ、それでクリンドを责める気にはならない。五秒もあれば、『神龙』はロズワールのことを五十回は杀せたはずだ。──『不杀』缚りをしているという话があるから、戦闘不能にするために四肢を溃して伤を冻らせておく、くらいか。

如果是罗兹瓦尔的话，为了让他陷入战斗不能的地步是会做到那种程度的。

柯林特从那场灾祸中成功守护了罗兹瓦尔，出色地完成了前卫的职责。

问题在于──

「我这副狼狈模样吗」

『龙』与龙人的战斗中插手，轻易就陷入濒死的我真是太难堪了。虽然并非掉以轻心，但总觉得自己还能做得更好。

多亏了主动承担魔女因子的佩特拉的奋战，将『神龙』引入的战场已遍布罗兹瓦尔的事先准备，他本该上演一场堪称生涯最高峰的魔法战斗。

如此激烈的战斗，可以说是自与柯林特共同对抗《忧郁魔人》以来。如果仅看结果，并不能简单地说明《神龙》比《忧郁魔人》更强。

无论如何──，

「……必须、更改、胜利条件了」

即便此刻，柯林特或许仍深信罗兹瓦尔能东山再起而奋战着，但自身的极限自己最清楚。体力已耗尽，体内一团糟，剧烈的魔力消耗甚至严重侵蚀了生命力。

事先准备的诸多大魔法，终究未能突破『神龙』的龙辉。即便是五种阿尔级魔法同时发动也未能奏效。倘若存在可能性，那便是六属性阿尔级同时发动，但即便是全盛时期也无人成功的魔法，以现在的状态绝无可能实现。

大脑如沸腾般的灼烧感与全身血液倒流般的剧痛，正是罗兹瓦尔耗时四百年筛选出的、一族最高阶的门濒临崩溃的证明。

再继续下去已无意义。既然准备的杀手锏不起作用，那就降低目标门槛，至少完成最低限度的任务。

原本这场战斗的目的在于阻止阿尔德巴兰的计划，只要能将『神龙』牵制在此处便已足够。

所以此刻应当明智地、随机应变地、专注于支援持续抵抗的柯林特。

那就是──，

『罗兹瓦尔、不许勉强自己，但这是超级重要的任务。所以、要加油！』

『罗兹瓦尔大人、至今给您添了许多麻烦。终于、能报答您的恩情了。让我们一起成为那个人……成为昴的力量吧！』

『既然是老爷说过要做的事、就请不要更改哦。……虽然我讨厌老爷、但觉得您不会输给任何人这点可是真的』

『罗兹瓦尔大人、祝您武运昌隆。──此外、还请尽情施展』

「……哎呀」

本该机智灵活地、彻底专注于柯林特的援护──

但当他察觉时、罗兹瓦尔已经抱着惨不忍睹的右臂、摇摇晃晃地站了起来。

「────」

不对劲。明明打算用更为狡猾、渴求胜利的平庸魔法师的战斗方式、而非鬼鬼祟祟模仿罗兹瓦尔所憧憬的伟大魔法师的做法。

究竟、为什么、自己会站起来呢。

难道说、你还不打算放弃吗。明明准备的手段都已经行不通了。明明至今为止、从未取得过超出实力的成果。

「──怎么、站起来了啊。本来是打算替你收尸的」

正因为还在为自己的行为感到惊讶，对于这突如其来的声音，罗兹瓦尔反而没被吓到。

那个声音的主人慢慢地、如同描绘世界终结般踏在荒芜的大地上，摇摇晃晃地站到了不可靠的罗兹瓦尔的身边。只是──，

「抱歉啊，我连歪头的力气都舍不得浪费呢。……你个子太矮了，看不清你是谁，不过这里可不是小孩子该出场的场合——啊」

「谁是小孩子！你这家伙、真是个可恨的男人……！」

半开玩笑半认真、对罗兹瓦尔这句话、对方彻底动真格地怒吼起来、原本看不见的身姿逐渐升起、映入视野边缘。并非对方长高了。而是用魔法使地面隆起、通过临时的垫脚台调整了视线高度。

真是无聊透顶的魔法浪费呢，不过我并不讨厌。

完全不顾罗兹瓦尔的内心想法，做出这番举动的黑衣绿发小人族抱起双臂——

「就让我重新刻进你脑子里，好让你忘不了老子是谁。——就由我这个『灰色』的艾莎・卡德纳，抢先超越『神龙』给你看啊！」

** 第五章 『魔法师』

１

──紫电炸裂乱舞，柯林特在战场上空四面八方、纵横无阻地飞跃。

『──唔!!』

追逐雷爆之光，如暴风般袭来的龙爪撕裂天空，每当虚无空间被撕开，产生的真空波便逐渐封锁龙人的退路。

在选项被逐一剥夺的过程中，柯林特谨慎而大胆地在空中周旋，将『龙』的目标锁定在自己身上，使其注意力连余波都不会波及地面。

「超出了我方的预期吗。令人惊叹」

躲闪并化解着每一击都足以改变地形的『龙』之暴威，同时从正面与之抗衡，柯林特不禁对篡夺者的龙壳运用发出赞叹。

正如前文所述，篡位者并未能完全掌控『神龙』的龙铠。——这无异于将『剑圣』的躯体赋予刚出生的婴儿。原本就是强求不得之事。

因此柯林特也对篡位者并非发挥作为『神龙』的真正本领，而是连龙铠都化为胜利工具的贪婪姿态感到佩服，并再度敬佩起弱小人类所展现的坚强一面。

然而当战斗超出预期逐渐拉长后，他才察觉。——篡位者适应龙铠的速度远超柯林特意料，同时仍在持续成长的事实。

「听说您曾与『剑圣』和『剑鬼』交锋至此地步。令人信服」

即便凭借『神龙』的龙铠，篡位者仍通过多次与难以轻易压制的强者交战，相当程度地激发出了作为『龙』的潜能。从守护『心核』的龙鳞与龙辉光芒中，也能充分感受到这份沉甸甸的成效。

「人类的可能性真是……。由衷折服」

所谓完整个体之类的妄言——如此自诩的『龙』之存在方式何等滑稽。

为何、『龙』能作为最强的生命体、在地上如入无人之境般行走。──那巨大而肆无忌惮的脚步声就是答案、柯林特如此认为。主张强烈、谁都无法从其存在上移开视线。无法置之不理。正是这点让『龙』、在地上拥有了最大的颜面。

所以『龙』才在这地上失去了容身之处、消失在大瀑布的彼方。

「────」

明知是不合时宜的感伤、往事依旧在龙人胸中往复穿梭。

在天空绽开无数裂痕、轰然咆哮的狂风卷起巨岩与冰砾四处飞散的环境中、凭借十重、二十重叠加的冲击波贯穿前行时、柯林特的脑海里描绘着四百年前──被地上驱逐、振翅远去的同胞们的身影。

那天、留在地上的究竟是离群的孤狼还是怪胎、虽说一般认为具备正常思维与判断力的『龙』都已前往大瀑布的另一侧、但按柯林特的说法则正好相反。

『龙』之所以能成为顶点生物、是因为其生命被设计成了最强。既然如此、所谓『龙』就必须持续学习与成长、以免常保此座不致旁落。

龙人族诞生这件事本身，不正是那条『龙』存在方式的证明吗？

「更重要的是，您难道没有察觉吗？──（失笑）」

柯林特将缠绕的紫电化作轰雷，击碎了铺天盖地的数百块岩块与冰块，成功将『龙』的注意力吸引到自己身上，随即望向地面。

在那里──

「──龙鳞与龙晕，这就是『神龙』让你那张王牌失效的原理吗？」

「「无力化」这个说法我可不能当作没听见啊。希望你能用无效化或是无害化来形容呢——」

「现在是纠结这种无聊事情的时候吗！……不同属性同时发动，是应用了『二属性交叉式』吗？但混合三种属性的话，火与风的收敛压力控制要如何解决？」

「简单得很。直接把收敛压力本身作为核心就行了。因相互干涉而产生的术式不平衡，只要第三种属性是水就配合火，是土就配合风，这样就能修正啦。」

「竟然利用属性的螺旋干涉！?荒唐，让相位相反的属性相互碰撞的话，术式会彼此抵消，门的临界偏差轻易就会被超越……原来是极点压缩啊！」

「噢～居然能靠自己摸索到那个地步，意外地能干嘛。看起来是相当新颖的术式构建，明明像是自学成才……不对，仔细一看，那难道是我家上上代留下的术式基础吗？」

「唔……！」

「放到现在，将体内循环的玛娜视为圆环的『均衡环流』才是主流，这早就被认定没有价值而该被废弃的……相关资料明明很早前就失传了，难道是你？」

「嘛，追求魔法之道多少都得有点觉悟！说到底，那文献可是在露天摊铺上积满了灰啊！我从中发现了『统合环流』，让发动魔法时的玛娜使用效率得到了飞跃性提升！」

「拿着别人的理论还这么理直气壮～呢」

「我承认确实是受到了启发，但改进和优化本就是进步的常态！那你难道想说你自己从未受过任何人的教诲或指导吗！?」

「────」

「别突然沉默啊！退一万步讲，就算有功劳也不是你的，而是你的上上代罗兹瓦尔・J・梅札斯女士的伟大功绩！」

「那意思就是说，那也和我差不多啊。——回到正题吧。我从未考虑过『整合环流』。既然你明白『双属性交叉式』的问题点，那不用我说明『三角重心制控』为何不适合『多属性交叉式』了吧？」

「你是在小瞧我吗？每多一种同时发动的属性，螺旋干涉的紊乱就会成倍增加。就算用『三角重心制控』能同时发动三种属性，但更多的话……不，你这家伙刚才实现了五属性同时控制。到底是怎么做到的？」

「原来如此。想听答案啊。好啊，我就告诉你吧。验证自己的求知欲与深渊之魔的真髓才是魔法的精髓，但你的热情也就这种程度——」

「等等等等等等，你给我闭嘴……！五属性、螺旋干涉、极点压缩……不，那家伙的术式是用『均衡环流』来……原来如此！是『三角重心制控』的重叠并联！」

「──！」

「也就是说用『三脚重心控制』将三重属性的同时发动叠加成两重来运行！在那第二重的三重属性中，用发动了的阳属性来辅助自身的门，以螺旋干涉产生的收敛压力为核心，实现了三重属性与双重属性的极点压缩，从而实现了那个……」

「没错，正是如此！那就是证明『五重共鸣点』实际存在的突破口！」

「你疯了吗！?每一手、每一瞬、每一分、每一毫！稍有偏差就会引起螺旋崩溃彻底完蛋！以你为中心会形成第二个阿古扎德溪谷的！?」

「但是，并没有变成那样。——那就是，至高至远的魔道之巅啊」

「────」

「害怕吗？艾莎・卡德纳君」

「啊啊，当然可怕。而渴望着那一切的自己的这份心境才更可怕啊，罗兹瓦尔・L・梅札斯」

——就这样，地上两位魔法使互相碰撞着彼此的钻研，互相砥砺。

「真是相当生动的表情呢。超出预料」

原本就有被托付的职责。因此，在与『龙』战斗的最前线，身缠紫电激战，是柯林特自愿期望并承担的。」

但是，就算没有被赋予那个角色，柯林特大概也会遵循自己的信念，选择像这样与曾经的自己的龙壳和紫电交锋吧。

人类与人类之间的切磋琢磨，正试图创造出崭新的『某种东西』。

那正是，未被认同崭新价值观的同胞们视为异端、自愿选择被遗弃在地面上的『神龙』波克肯尼卡──其龙人族，柯林特的夙愿。

因为这是以封闭可能性为代价的『忧郁』魔女因子，以及从未被侵蚀的精神性中最为坚固的支柱。

２

对于并肩而立的艾莎・卡德纳，罗兹瓦尔几乎一无所知。

名字有所耳闻。知道她是新加入菲鲁特阵营的人才，因其才能出众而迅速成为阵营核心人物之一的内政负责人，仅此而已。

虽说确实有关于她是魔法使的情报 但大家只以为她是师从不明自学成才的野路子魔法使 实际上她也确实是自学 所以这种认知倒也没错。

──其实过去曾有一次，罗兹瓦尔被艾莎无故找茬，那件事由昴他们解决了。但虽然罗兹瓦尔记住的事情很多，却有着对不感兴趣的琐事立刻忘记的癖好，当时的艾莎也是那遗忘中的一个。

不过，罗兹瓦尔的那份遗忘，以及认为她不过是个冒牌魔法使的认识，都在面对艾莎本人、目睹他构筑魔法的理论后被颠覆了。──是真货。

而且，对于彼此都心知肚明对方是真货的两人而言，并不需要太多言语。

「稍微休息一下喘口气。待会儿还得让你再乱来一次」

如此告知的艾莎，从为与罗兹瓦尔视线齐平而搭建的脚架上跳下，向前一步踏入战场，仰望着天空。

大魔法与超魔法的连发，加之『龙』与龙人的冲突叠加，受到滞留玛娜剧烈影响的搅动，原本蔓延着苍色的天空化作了虹色摇曳的异常气象。此处仍有无数紫电炸裂连锁，驰骋空中的龙人的独斗仍在持续。

力不能及，在罗兹瓦尔倒下之后，柯林特依旧尽职尽责地完成了自己的使命──，

「为何他独自战斗？你这家伙搞错了啊」

「……你说什么？」

「莫非你觉得魔法师无法与他人协同作战？不，调和才是真正的精髓！」

在瞠目结舌的罗兹瓦尔面前，说出这话的艾莎周身浮现出无数水球。

水球内部已吸纳了大量崩落的岩块，裹挟着这些石块猛然急速上升──径直冲入柯林特与『神龙』愈演愈烈的战场。

「那是──」

与其说是乱来，更像是毫无意义，罗兹瓦尔难以理解艾莎的意图。

虽说是单一操控的水属性魔法，但对近百数量举重若轻的驾驭技巧令人赞叹——然而那种程度的水球，即便连带着岩块砸过去，恐怕连吸引『龙』注意的效果都没有。

反倒可能妨碍正独力与『神龙』周旋的柯林特的战术。

「再说一次，罗兹瓦尔。──你这家伙，彻底想错了」

面对艾莎的宣告以及紧随其后的景象　罗兹瓦尔不禁屏住了呼吸。

他唤出的无数水球，并非用于攻击『神龙』。──爆裂的紫电将水球与岩块炸得粉碎，借力跃空的柯林特速度更上一层。

加速了的柯林特，水球如同引导其进路般大范围散开，作为发射台令龙人的一击变得更加尖锐、沉重、鲜明，贯穿了『神龙』的龙鳞。

轰音与冲击波传至地表，艾莎继续对沐浴强风的罗兹瓦尔说道。

「确实，他确实具备单挑空战能力。但据我推测，那魔法光辉的真正设计初衷并非如此，而是令人惊叹的防护性能。正因他是经验老道的强者，才能以不同运用方式作战，但若消除力量逸散现象，本来的威力根本不可同日而语」

「──。【保留空白符】不过，如果在空中准备立足点，反而会难以分散目标。【保留空白符】能够自由蹬踏天空的柯林特的优势岂不是可能会丧失？」

「【保留空白符】你认为他是无法根据需要在二者间切换运用、【保留空白符】驾驭不了的半吊子吗？【保留空白符】若是如此，你所缺乏的不仅是体贴之心，连识人的眼光也没有」

「────」

「罗兹瓦尔，与人并肩作战并非意味着盲目信任对方、不加防备。而是该放手时就放手，该补位时就补位。照你的做法，就算一百加一百能变成互不干扰的两百，也绝不可能让一百加一百产生共鸣变成一千」

如此阐述着自己主张的同时，艾莎对上空战局的支援也丝毫未停。

这片岩石荒野最不缺的就是浮空岩块。即便柯林特以肉眼难以捕捉的速度消耗着作为落脚处的水球，其增长数量依然压倒性地多过消耗，大有铺天盖地之势。

『啧，我还以为是谁在耍小聪明，原来是老师啊！』

察觉到被利用的落脚点源自艾莎后，『神龙』狂暴地怒吼着。龙爪一击便粉碎上百水球，紧接着朝地面的魔法使们喷吐出龙息——

「建议您别东张西望哦，就像这样。证明完毕」

柯林特的双脚从正下方狠狠踢中了那条『龙』的下颚。未能释放的吐息在那条『龙』的口腔内爆炸，可以看到冲击使得獠牙四散崩飞。

『可、恶……！』

因自爆而后仰的『神龙』，其周围的空气发生扭曲、弯折，不稳定但强大程度毋庸置疑的魔法光芒扩展开来，那条『龙』试图发动它照猫画虎的大魔法。

即使能将紫电作为屏障的柯林特和依赖龙晕进行防御的『神龙』能够承受，但若那股力量落向地面，罗兹瓦尔他们将毫无招架之力。

「──既然如此，唯有让其在空中爆炸」

幸运的是，这里存在着大量随机释放的玛娜，以及基于在旁边仔细观察过的『统合环流』而形成的魔法水球。──介入那个魔法的构成，改写其性能。

「你这家伙，那是我的魔法!?」

「魔法不属于任何人。道路始终是敞开的。──这是我老师的教诲」

瞬间、束缚失控的水球，吸入周围的玛娜进行极点压缩──强行介入对『神龙』试图构筑的大魔法进行自我诠释，故意搞砸其最终形态的构建。

由此引发的是艾莎所担忧的螺旋崩坏──在这场战斗中屡次破碎的天空，此刻再度爆发极光大迸裂。

灼热与极寒交替来袭，空中巨石熔化、冻结、迸裂四散。雷光将残渣尽数烧尽，风压把灰烬与沙尘吹飞到数公里外的惨烈景象。

「太乱来了吧，你这家伙!?差点连作为同伴的他也一起炸飞了啊!?」

「但是，你守护住了。──这就是你所说的和谐，对吧？」

闭上黄色的那只眼睛眨眼，罗兹瓦尔让变了脸色的艾莎安静下来。

事实正是如此，用层层叠叠的水带包围了在空中被大爆炸卷入的柯林特，将那毁灭性的火力最大限度地抑制住并成功防御的，正是艾莎的本事。

要是艾莎的话、咱觉得她就能察觉罗兹瓦尔的意图然后去干这事。要是角色对调的话、凭着本事和体贴的差距、绝对搞不成的各得其所。

果然自己是个泯灭人性的恶人。——只不过，还有改良和改善、进步的空间罢了。

「即便如此这番行径，我也不得不怀疑老爷是否神志正常了。鬼畜」

虽、虽然似乎能听到柯林特因艾莎的急智而免于坠落的怨言，但面对他那张冷脸的说教，也都是结束战斗之后的事了。

然后──、

「艾莎・卡德纳君」

「──。干嘛，罗兹瓦尔・L・梅札斯」

被喊到名字的艾莎像是要对抗般回喊过来的样子很有趣。将这般心思隐藏在血与汗弄花了的妆容底下，罗兹瓦尔叹了口气。

而后重新凝视着『灰色』的艾莎・卡德纳──，

「──希望你能助我一臂之力。开创这世上从未有过的新魔法」

罗兹瓦尔自暴自弃地说，连他自己都觉得这种说法很卑鄙。──毕竟沉迷于魔法之道的人，又怎么可能抗拒得了这种诱惑呢。

３

──正在构建术式的中途，艾莎・卡德纳不由自主地快要掉下眼泪。

「笨蛋笨蛋笨蛋，这该死的泪腺。现在不许工作，给我继续怠惰着」

她如此叱责着自己身体的功能，绷紧脸颊将快要溢出的泪水硬生生止住。

艾莎讨厌怠惰。那是因为小人族既不具备优秀的身体能力，也不受门之加护，许多同胞要实现目标，就必须付出比其他种族更多的努力。虽然小人族唯一的种族特性是容易获得加护，但和同属菲鲁特阵营的汉巴里等人不同，艾莎连这根签也没抽中，是个显而易见的『一无所有者』。

艾莎讨厌怠惰。这并非因为被迫过着比他人更严苛的生活──而是因为一旦以小人族的出身为理由，被人带着「啊，果然如此」的态度轻视，就会让她觉得，怎么说呢，实在难以忍受。

仮にエッゾが立てた目标に届かなかったとしても、それは小人族だったからではない。人生とは一度言い訳を许せば、怠惰や怠慢にあっという间に攻め込まれ、自分をグズグズでドロドロの甘々人间に仕立て上げてしまうと、よくわかっている。

话说回来，哥哥和姐姐就是那样。艾莎虽然是十个兄弟姐妹中的老幺，但除了自己之外的其他兄弟全都获得了加护，并仗着这一点过着懒散放纵的生活。

倒不是说这样不好。那是哥哥姐姐的人生。虽然想说不好，但忍着不说。要忍耐。

只是，如果这种事发生在自己人生里的话，那可忍不了。

所以艾莎・卡德纳在露天摊贩那里发现了被收在箱子深处、积满灰尘的魔法文献时，便发誓要将人生奉献给这份感动，绝不再找借口。

「你这家伙也是这样吧，罗兹瓦尔。……一看就知道了」

虽已位居王国的宫廷魔导师之席，处于授予精通魔法属性者『有色』称号的地位，却以不教导他人、不与外界往来著称的罗兹瓦尔。纵然作为边境伯的才能堪称能干，但其魔法师地位不过是靠家世与政治力量购得。──如此怀疑罗兹瓦尔并曾发起挑战的往事，是艾莎难以忘怀的黑历史。

但是，当实际目睹罗兹瓦尔展开的魔法构建之精炼、所描绘术式之瑰丽时，艾莎从心底感到了羞愧。

艾莎与罗兹瓦尔是同龄人。而且艾莎曾狂妄地认为，在同龄人中没有人比自己更努力。她自以为投入了全部生存时间，才触及到魔法本质的一鳞半爪。但完全不是这样。——罗兹瓦尔与艾莎之间，在魔法的探究与钻研上，简直像是存在着百年以上的差距。

那是绝不能归咎于才能差距、种族差异或出身悬殊的绝对真相──因此，艾莎・卡德纳喜悦得几乎要落下泪来。

「──」

站在自己梦寐以求领域的人，是比自己更努力的家伙，真是太好了。

那份理解与敬佩和感谢，让艾莎心潮澎湃，让最厌恶懈怠的艾莎有生以来第一次命令泪腺偷懒。

怀抱着这样的想法，艾莎也为了展示积累的探究成果而集中精神。

在魔法中，需要强烈想象即将发生的结果。这无异于将自己是怎样的人、在思考什么、渴望什么、将什么定为目标等全部暴露出来的行为。

所以，魔法没有谎言。──只要看其魔法，便能知晓那人的一切。

「──呐，你明白的吧，罗兹瓦尔」

那究竟是真的说出了声的话语呢？还是过度透支的门与耗损生命的集中力所制造的错觉呢？

「……啊啊，当然明白，艾莎・卡德纳君」

但是，与怀疑是幻觉幻听的心思相反，回应确实存在。

极限的玛那高涨交融之景化作苍白 就连为了守护我等而奋战的紫电轰雷也听不见 即便如此彼此的存在却近得仿佛连心跳声都能传达

透过编织成形的魔法　两位毫无保留的魔法使的意识相互交融

罗兹瓦尔积累的岁月 全心钻研的成果 无人能追及自己 独自朝著顶点持续前行的时光 都传了过来

过度追求的结果 会让人不由自主地陷入孤独 罗兹瓦尔也一直保持著孤独

但是 对著未曾流下的泪水起誓 艾莎必须告诉罗兹瓦尔

「你究竟打算独自一人走到何种地步 现在的我还不明白 但是 无论有多少人试图将你推向遥远的存在 唯独我不会这样」

如果努力与钻研能让他到达那般境界 那么自己也能做到相同──不 是更能超越

「无论你多么喜好孤独 即使选择独自死亡 即使试图前往无人能及之地 唯独我会死死咬住你不放」

虽然无法理解想要放弃的心情，但想要叹息的心情艾莎也能明白。

只是竭尽全力做了自己能做到的事，回过神来周围已经空无一人。──毕竟谁都不愿认为，那是自己的错。

「精通属性者获得的称号，『赤』与『绿』，还有『黄』三色已授予你。但『青』之位让与菲利克斯・阿盖尔氏，且『白』与『黑』之位依旧空缺。──可知此中深意？」

「────」

「可知我被称作什么吗？是『灰色』的艾莎・卡德纳。可知灰色是由何色构成？──罗兹瓦尔，我终将追上你的脚步」

所以，我将把与艾莎・卡德纳所体会过的相同感谢，奉献给伟大的魔法使。

「──你绝不会独自走这条路的」

４

天空的色彩，早已消失殆尽。

晴朗苍穹中的蓝色已然消退，唯有褪色的灰白幕布不断蔓延，大气本身的价值逐渐稀薄，仿佛即将虚幻地消散。

闪光撕裂褪色的天空。柯林特缠绕紫电如缎带般雷驰，那已非「跳跃」二字所能形容，其势宛若要将天穹踢裂。

对峙的则是被龙鳞与龙晕守护、将淡光闪耀的龙壳舞动于空中的巨影──每当龙爪闪烁之际虚空便随之撕裂，真空断层裹挟着轰鸣声向龙人汹涌袭来。

「────」

连发出声音的余裕都没有。唯有紫电鸣响。

紧接着翻飞的龙翼，夹杂在突风中的无数光弹闪耀天空。它们如星屑般点缀在灰色的天际，描绘出凶猛的轨迹向柯林特逼近、逼近、逼近。──轰雷眨眼间，数百道光束之雨被贯穿，无数闪光点缀寂寥苍穹。爆裂的余波向上方偏斜扩散，连一星碎片都未曾抵达地上两名魔法师所在。

『────』

下一瞬间，所有人都真正意义上地看到了天上繁星闪烁的景象。

在褪色天空的彼方 从遥远彼岸坠落之物是被巨大引力牵引 朝着地面笔直突进的星光──犹豫仅是刹那 连眨眼都不及

「──！」

格外强烈的紫电迸溅　连锁的雷爆将龙人朝着星辰坠落的天际推升

『────!!』

『神龙』吐息释放的奔流化作白热灼烧天空 却既未指向天际的龙人 也未瞄准地上的魔法使 径直奔向远方大地

炸裂的紫电与『龙』之咆哮相互交融 在天际尽头破碎的星辰强烈又强烈地 将褪色的天地照耀得刺眼──

「──阿尔・塞克斯特特」

咏唱撼动了地平线　天空屏住了呼吸

构成世界的全部玛纳被赋予相异的六色职能 奔涌的力量相互交织融合 本应瞬时崩溃的干涉却生出同一律动 以失色世界本身为媒介 形成美丽圆环

不久后，六色奔流汇聚成一道，化为斩断天地界限的光柱。

光柱不偏倚任何一色，仅仅选择将名为『魔法』的根源本身所显现的极光作为己色，光柱逐渐蜕变为吞噬一切的力量。

──在那光柱的中心，禁锢着『神龙』的巨大身影。

抵抗的利爪、双翼、吐息皆被虚无吞噬，『龙』之力尽数化为魔法的食粮，光柱愈发粗壮，光芒愈加炽烈。

伸向天际的光柱刺破万里无云的天空，将高层大气与遥远地平线映照得一片白茫。那一瞬，天地法则被骤然改写。

──这是自魔法体系诞生以来，连『最初魔法使』与『强欲魔女』都未曾达成的绝对奇迹。

『──啊』

在声音消亡的世界里，那声过于微弱的赞叹，与引发的惊天事件相比实在微不足道。

但已足够让人确信。──此刻，『神龙』的龙晕已被击碎。

然后──，

「──封枷、第三解禁」

撕裂天空、烧灼大地、六种属性保持均衡化为支柱的世界正中。贯穿那极光漩涡的唯一一抹带着色泽的紫电从天坠落。

如同击碎星辰坠落的陨铁，那身躯缠绕着闪电自天际突入。蹬踏虚空的脚步迸发爆音，将自身化作贯穿唯一点的至高箭矢。

目标是逆鳞。──『神龙』脖颈上唯一的要害，号称绝对防御的铠甲上唯一的蚁穴。被光柱吞噬、其龙晕已被剥离的『龙』身上，通往『心核』的最后壁垒。

「感谢吧。──感谢」

紫电如拖着尾迹的彗星般，穿透音障与龙鳞的防护，拳头轰然砸入。

光柱的辉煌与紫电的奔流相互交织，冲击震撼虚空，伴随着破碎声响，光的缎带在『龙』的全身奔窜。

倾尽全力的打击，与史上罕有的魔法这一奇迹的顶点相结合，此刻正击穿了『神龙』龙铠最深处的最深处，沉眠于其中的『心核』。

『────』

确凿的一击贯穿身体，舒展双翼悬浮于中天的『神龙』缓缓望向大地。就在那里，他辨认出那个确已奄奄一息的渺小存在，『龙』爪如惯常般伸向自己头部附近划破空气。——仿佛下意识将手指探向自以为仍戴着的头盔金属扣。

『啧，真难堪……穿着这么厚的木屐还搞成这样，连推给星星都、办不、到啊』

就这样，带着令人恼火的、与『神龙』应有的庄严毫不相称的、过分平庸的咒骂，统治天空的绝对存在被重力牵引，坠向大地。

携着摇曳的光之残渣，撕裂虚空，伴随着轰鸣声，不断坠落。

——这便是与夺走『神龙』波克尼卡龙壳的篡夺者之间的了结。

５

贯穿天地的六色光柱，在眼前缓缓消散。

逐渐褪去灰白、曾忘却本色的天空慢慢恢复色彩，不久苍穹便如回想起自己为何被称为蔚蓝般，开始变得淡澈澄明。

「────」

面对这番景象，罗兹瓦尔看见身旁的艾莎眼中流下了泪水。

那是喜悦吗，还是不甘呢，无论是哪种都理所当然会情绪激动的情景。虽说有两人合力，但罗兹瓦尔和艾莎完成了将被首次铭刻在魔法史上的伟业。

四色与双色、极限的魔法控制、不容丝毫破绽的术式构筑，以及连刹那偏差都无法容许的终极调和──这便是超越了『神龙』龙晕的境界。

罗兹瓦尔的钻研与艾莎的探究，二者缺一不可方能实现的魔法。

然而──

「终有一日……即便只靠我一人，也定要构筑出这个术式……！」

面对流着止不住眼泪却如此豪言壮语的艾莎的侧脸，罗兹瓦尔笑了。

既非傻眼也非嘲讽。──没错那才正是魔法使的姿态。

魔法最重意象。凡是能想象之事无所不能即为魔法。

「是吧老师」

そう、呟いた罗兹瓦尔的身体倾斜，缓缓地向地面倒下。艾莎急忙伸手想要扶住他，但遗憾的是，消耗过度的他先摔倒了。

就这样、即将倒下的罗兹瓦尔差点要把艾莎压扁──、

「──赶上了。好消息」

危急关头，那道冷冽的嗓音与有力的臂膀，同时挽救了险些跌倒的罗兹瓦尔与被其压扁的艾莎。

一旁站定的柯林特，这位在激战中途飞向天际、碎星而归的全能管家，不知何时已重新戴好单片眼镜，额间的黑角也收了起来。

只不过，平日里完美的仪态已凌乱不堪，展现出了罕见的、不符其风格的模样。

「即便如此，除了执事服之外几乎毫发无伤，龙人族真是犯规——啊呐」

「老爷，恕我失礼提出更正。并非因为是龙人族，而是作为『神龙』龙人族的我特别而已。断言」

「……果然是在炫耀吧？就因为你的容器害得我们变成这副德性？」

「不许指着我！只是腰……不、是全身脱力站不起来而已！」

保持着向前倾倒的姿势无法起身的艾莎不甘心地嘟囔着。看到她那样子柯林特遗憾地耸耸肩，（真是的）（性格还不错嘛）

「变了呢。你明明该是更符合超越种身份的达观类型才对」

「既然如此请允许我说出完全相同的话奉还。──老爷您才应该坚持做个精明取巧的平庸魔法师不是吗？确认」

隔着单片眼镜眯起眼睛的柯林特准确地说中了罗兹瓦尔的想法。确实本来是那么打算的。但是罗兹瓦尔没能做到。

不仅没能做到还站起身做出了连想都没想过的乱来之事。

那就是──

「只是注意到了而已。……至今以来的日子并不是一个人独自走下来的这件事」

「────」

对于罗兹瓦尔的回答柯林特以及不知为何连艾莎都陷入了沉默。

「（不知为何）这说法有点太做作了啊」

不仅是交情长久的柯林特，艾莎在刚才发动超魔法时，两人的自我险些互相融合。罗兹瓦尔当时的心情和祈祷，恐怕无法对他完全隐瞒吧。

「嘛，我倒是因为习惯了意识交融所以能理解，但艾莎君你为什么没事呢？按理说脑袋应该会坏掉——才对呀」

「别把可怕的事说得这么轻巧！恐怕是《死者之书》的恩惠。在监视塔待机时，我为了阅读《死者之书》而学会了清空心绪的方法……」

「原来如此。这就是魔法使。我懂了」

总觉得柯林特得出了有些失礼的结论，但此刻不便深究。

相比之下，更该优先的是——

「老爷，我们确实完成了受托的任务。圆满达成。但是……」

「啊，说得是——呢」

罗兹瓦尔接过柯林特说到一半的话，轻轻呼出一口气，望向远方。柯林特和倒在地上的艾莎也望向同一方向——地平线的彼端。

那是与『神龙』交战后环境剧变迥异往昔的岩原野，在其更前方的阿尔德巴兰一伙的最终目的地──

「──摩格阿雷德大喷口」

６

在撕裂天地的战斗最后，目送前去迎击巨星的龙人的『神龙』，被迫面临两个选择。──是排除魔法师，还是完成自己的职责。

一定能赢。这般傲慢，在迸发的紫电与释放的大魔法面前早已荡然无存。

故『龙』依其龙壳中所寄宿之人格信念　优先排除了最坏的可能性。

──所吐出之气息　瞄准远离战场的一点笔直奔驰而去。

环绕四周的山脉　其山麓处被凿出的巨大地孔──摩格阿雷德大喷口。

从地表窥见的只有淡青色的水面。但在那深处，遍布地底的水脉与火脉相互交织，潜藏着世上独一无二的巨大空洞。

那个空洞深深深不见底，甚至延伸至世界尽头的彼端、大瀑布的彼岸。——那道摩格阿雷德大喷口，迎来了生命的吐息。

「────」

白热的奔流被喷口吸入，响起了撼动基岩的轰鸣声。刹那间，看似归于平静的水面开始震颤──猛然爆裂。

那现象既不是撕裂地面的爆炸，也不是喷火的火山爆发。

随着轰鸣，天地仿佛倒转，白银的水流如柱子般从喷口升起，岂止数百米，甚至超越了山脉顶峰的高度直冲云霄。水柱沐浴阳光闪耀七彩光芒，一边散布着蒸汽与轰鸣声，一边将大量水滴洒向地平线。

──当那喷涌停止之时，大地上将被凿出新的空洞。

那是从地表无法想象的巨大空洞，当光与蒸汽深处的深渊张开大口时，其对面等待着的是被视为与地上不同的空域彼方。

『神龙』最后的咆哮，成为了确实的唤醒信号，让摩格阿雷德大喷口觉醒了。

──为了终结『尾随星』、菜月・昴的旅程，其终点，近了。

《了》

** 后记

这次也是！感谢大家陪伴到第42卷完结！我是长月达平＆鼠色猫！

话说，虽然一直强调九章的主题是『疾风怒涛！』，但这次在此基础上，我还将『巅峰对决！』这样的元素也作为自己的主题加入了进来。帝国篇的最终战斗规模已经相当庞大，但九章绝不输给它！我们正在挑战！

在Re0中我每次都努力让每个章节呈现出不同的阅读趣味和独特魅力，但第七章＆第八章的帝国篇却是激情叠加激情，连档位切换都被暗长月＆暗鼠色猫嘲讽「你真的有在换挡吗～？」所以第九章我打算彻底切换档位把暗长月＆暗鼠色猫揍翻在地。

现在、作品里正处于全面战争的高潮阶段，角色们竭尽所能奋战的模样真棒呢。无论是观赏还是描写我都喜欢。虽然写起来很辛苦，但角色们这么努力对作者来说真是莫大的荣幸。全面战争、应该还会再持续一阵子吧。

已经公布动画第四季的制作也在稳步推进中、为了不输给这股势头、正片也会全力全开努力下去的、今后也请多多指教！

那么那么，本次也请允许我进入惯例的谢辞作为结束问候！

责任编辑池本先生，这次也在世界炎热的氛围中，凭借深厚的信任让我完成了与火热截稿日的战斗，在此表示深深的感谢！最后的冲刺阶段，真的帮大忙了！

插画的大冢老师，本次终于揭开神秘面纱的柯林特、楚楚动人的菲鲁特、令人怀念装扮的雷姆以及喷发的摩格阿雷德大喷口，总之想看的画面接踵而至让作者超级兴奋！相信读者们也一定会非常兴奋！非常感谢！

设计的草野老师，这次也感谢您为封面插画增添了华美色彩！这是无损背景壮丽感的出色工作！

花鸡老师＆相川老师的第四章漫画版，以及高濑若弥老师的第五章漫画版，都描绘出了与小说和动画不同的Re:0，每次拜读都让我欣喜不已、热血沸腾充满动力！非常感谢！

MF文库J编辑部的各位、校对人员、各书店负责人及营业人员，每次都承蒙诸位鼎力相助，本次才得以顺利出版！一直以来非常感谢！

然后然后最后，向一直以来享受故事的各位致以最大限度的感谢！　能够写下想写的内容、推进写作进度，都是多亏了各位的支持！　Re:0，是时候回收至今撒下的伏笔了！　敬请期待！

那么下次，愿能在第43卷再会！　敬请期待《疾风怒涛！》的《顶上决战！》、星星与星星激烈碰撞的故事！　我会加油的!!

2025年8月《将不输给夏日的热情倾注于盲打之中！》

Re：从零开始的异世界生活 42

长月达平

MF文库J

2025年9月25日　发行

ver.001

©Tappei Nagatsuki 2025

本电子书籍依据下述版本制作

MF文库J『Re：从零开始的异世界生活 42』

2025年9月25日　初版发行

発行者　山下直久

発行　株式会社KADOKAWA

●咨询请联系

https://www.kadokawa.co.jp/

（请前往「咨询」页面）

※根据具体内容，有时可能无法予以答复。

※支持服务仅限日本国内。

※Japanese text only

禁止擅自复制、转载、分发、传送本电子书籍的全部或部分内容，亦禁止在网站等处转载。此外，禁止擅自改动、篡改本电子书籍的内容。

根据购买本电子书籍时已同意的条款，无论有偿或无偿，均不得将本电子书籍转让给第三方。

本电子书籍的内容基于底本发行时的采访及撰写内容。


