#+title: Re:从零开始的异世界生活 第四十三卷
#+setupfile: ./setup.setup

* 第四十三卷
** 序章 『梦的终结』

──将回归梦之城的阿尔德巴兰包裹其中的，是难以言喻的复杂情感。

熟悉的光景、熟悉的芬芳、熟悉的音色、熟悉的温度。

被熟知的蓝天与绿色平原包围，挟着熟知的青草芬芳的风声掠过耳畔，熟知的阳光温度笼罩全身，阿尔德巴兰伫立在这幅铭刻于心的风景中。──刹那间，脑海中那些褪色泛黄的记忆画卷骤然鲜活起来，重新绽放出绚丽光彩。

「────」

这正是，名副其实的，让阿尔德巴兰魂牵梦萦到连梦境都反复重现的梦之城。

在流逝的岁月里，他曾怀疑过这座城是否真实存在。当实感逐渐远去时，他甚至质疑过自己的神智。即便如此，这座梦之城依然作为浸透阿尔德巴兰血肉骨髓、永生难忘的灵魂学舍，始终矗立在遥远的彼方。

──历经四百又十年的漫长岁月，阿尔德巴兰终于重返故地。

「────」

在山丘上、白色阳伞下、能看到纤细柔韧的剪影伫立着。仅由黑白两色构成的美丽女人、正俯视着山丘下的阿尔德巴兰。

当那双黑瞳与自己四目相对时，即便隔着距离也能清晰辨识的美貌灼烧视网膜的刹那，阿尔德巴兰确信这正是令自己魂牵梦萦到几乎相信宿命的『魔女』。

从出生之日起，直至那个瞬间都未曾片刻分离的相伴者。

对阿尔德巴兰而言，这是用言语都无法道尽的、承载着太多情感的存在。

「──先生」

存在过。确实存在过。有过。确实有过。存在过。确实在这里存在过。

『魔女』也好、梦之城也好、阿尔德巴兰的过去也好，全都不是被正常世界所不容的阿尔德巴兰所制造的虚妄幻象。

「老师……」

想倾诉的事，多如牛毛。想传达的事，不计其数。

想交谈的话语，多如繁星。

只不过，最想和『魔女』分享的，是阿尔德巴兰这样延续生命、在漫长岁月尽头得以重逢的这份情感。

怀着那份急切的心情，阿尔德巴兰朝着山丘上的『魔女』所在之处──

「──阿尔德巴兰」

刚迈出的脚步，被那声呼唤硬生生拽住了。

渴望渴望渴望、持续渴望的『魔女』之声，对此感慨万千──才怪。阿尔德巴兰停下脚步，是出于另一个理由。

是因那声音、以及『魔女』凝视自己时眼神的冰冷与锐利，而止步。

「老、老师？」

被违和感支配而停步的阿尔德巴兰，正被『魔女』默默注视着。

她是个求知欲旺盛、充满好奇心、知识欲化身的人。但此刻『魔女』黑色眼眸中蕴含的东西，与阿尔德巴兰所知的『魔女』有着决定性差异。

明明该是阿尔德巴兰熟悉的样子，阿尔德巴兰熟悉的声音，阿尔德巴兰熟知的『魔女』，其存在方式却令人感到决定性不同。

那个理由、原因、真相是──

「──『强欲魔女』」

这正是『魔女』对阿尔德巴兰所怀疑虑与不安给出的回答。

「──啊」

『魔女』仅吐出这一句话，用仿佛观察实验动物般的冷漠黑瞳，注视着阿尔德巴兰会作何反应。

理解了。直觉到了。──确信了。

眼前的她，确实该是与阿尔德巴兰共度时光的『魔女』吧。但某种意义上，那个『魔女』早已永远消失了。

她适配了──适配了『魔女』的身份。

适配那份被渴求的自私，却仍令人如此焦灼、无论如何都无法据为己有的，真正意义上作为『魔女』完成所需的资格──魔女因子。

『魔女』已然蜕变。──从阿尔德巴兰的引路人，化身为『强欲魔女』。

在这场不容败北的战斗中，阿尔德巴兰落败了。作为代价濒临死亡的『魔女』，在临终之际与阿尔德巴兰分别后，被选中了。

──以真挚的爱为代价，获得了成为实现愿望之力的非人者的资格。

「──爱为何会消减呢」

不明白。阿尔德巴兰无法理解『强欲魔女』提出的疑问。

唯有一点可以明确。

「老师……不，『强欲魔女』艾姬多娜」

「────」

「我绝对要──亲手杀了你」

──阿尔德巴兰早已失去了一切。除了性命之外的所有事物。

** 第一章 『冰上决战』

１

──异常值。

雷姆认为这正是自己被赋予的使命，也是必须完成的职责。

为了阻止使用『时间回溯』这种超规格权能、突破重重阻碍来到这里的阿尔──所需的正是这个异常值。

『那铁盔混蛋的权能确实强悍。但不管多强的力量，使用它的终究是人类。是人就会犯错。虽说那家伙的权能连错误都能抹消，但并非无限。只要不断叠加预料之外的状况，把他逼到极限，铁盔混蛋终会犯下无法挽回的失误。──那就是打倒他的胜机』

这是曾将阿尔逼入绝境的罗姆爷提出的策略。

对于罗姆爷的献策，精通战术的拉姆、罗兹瓦尔和柯林特都没有异议。因此雷姆会全力执行这个计划。

阿尔应该遭受的，是让他叫苦不迭的意外。若说这需要比拼耐力，那雷姆也绝非等闲之辈。

毕竟──、

「──因为我，近距离见识过那个人」

要说最大的胜算是什么，那就是雷姆最关键的、最棒的制胜法宝。

「呀啊啊──!!」

咆哮着倾尽全力，雷姆挥出的手臂稍迟一步释放的铁球狂暴地划破长空。

笔直旋转的尖刺铁球瞄准的目标，是红发忍术师八重・天膳──在以海拔五千米的阿古扎德峡谷为舞台的下坠战斗中，这场对决正随着与这名惊人忍术师的交锋进入新阶段。

在半空凝结的冰之圆盘，成为双方比拼根基的战场。

就连这个试图强加意外的战术，也是雷姆与爱蜜莉娅协力构思的成果。但被塞入意外因素的不仅是阿尔他们。我们也是。

轰隆一声，撕裂风压的咆哮一击既沉重又锋利。

带刺铁球──晨星的威胁无论引以为傲的斩击技艺多么精湛，用细线捆束都无法防御。它毫不留情地袭向身为异常者的八重。

「──呃」

面对逼近的威胁轻哼一声，放弃迎击的八重就地侧翻。铁球擦过正在冰盘上翻滚的她身侧，徒然划破长空──

「嘿呀！」

伴着清脆击打声，听起来悠哉的锐利呼喝迎击了铁球。

这是隔着八重位于另一侧的爱蜜莉娅，用穿着冰靴的脚踢飞袭向自己铁球的爽快声响。爱蜜莉娅修长的腿凌空回旋，铁球被暴力弹回，追向侧翻闪避的八重，眼看就要嵌入她的侧腹──

「才不会得逞呢」

下一秒，八重侧翻时手掌触及的冰盘表面，被钢线剥离覆盖住她身体，化作阻挡铁球的盾牌。当然这薄盾仅能抵挡一击。半秒龟裂，再半秒尖刺已穿透盾面，整整一秒后彻底粉碎。

然而，对于敏捷的忍术使而言，这一秒就已足够。

「骗人!?」

爱蜜莉娅不禁发出悲鸣。但雷姆此刻也是同样心情。

在二人视野中，用临时冰盾避开追击的八重轻盈跃起，赤足踏上完全伸展的晨星锁链，顺着锁链一口气疾奔。

爱蜜莉娅为那杂技般的平衡感瞪大眼睛，雷姆更震惊于她在锁链上行走却丝毫不显沉重的步法，而惊愕还在延续──随着八重挥动手臂，冰与石制成的刀剑正从她们头顶接连倾泻而下。

「这是──」

这正是二十秒前爱蜜莉娅与阿尔在空中制造、未被回收的冰制与石制武器。八重用钢线将它们拽落，化作危险骤雨再度利用。

「都怪我没收拾干净！」

「阿尔先生您也没收拾啊！」

「摊上不会收拾的主人，咱们都不容易呢？」

反省、补救与挑衅交织在一起，雷姆和爱蜜莉娅忙于应付从天而降的刀剑。爱蜜莉娅用双手的冰之双剑将其击落，但雷姆的情况不妙。

右手被晨星占据，而此刻晨星正被八重当作立足点无法贸然收回。只能徒手用仅剩的左手防御。

「来不及──」

正当她以为避不开而准备承受攻击的瞬间──有人猛地推开雷姆的肩膀，而那个推开她的人被坠落的石制长剑贯穿了胸膛。

「──昴君！」

在雷姆情不自禁的喊声中，被贯穿胸膛的是菜月・昴──的冰制人偶。这个过分精巧的冰雕菜月・昴保护了雷姆，带着宛如本尊的英勇笑容竖起大拇指，缓缓倒下。

「呜诶？刚才那是、难道说是爱蜜莉娅大人吗？」

「嗯，没错。──而且，昴可不是一个人在战斗！」

在皱眉的八重应声的瞬间，六道人影从爱蜜莉娅背后飞窜而出。全都是与刚刚倒下的菜月・昴相同外貌的冰像。

它们全员仿佛各自拥有意识般摆出个性鲜明的姿势，同时扑向在锁链上奔跑的八重。只要那些冰之指尖有任何一处触及八重──

「不巧，我最擅长的就是多人战」

刹那间，二十条跃动的钢丝束缚住扑来的冰之菜月・昴们。缠绕在脖颈、躯干与四肢的钢丝猛然收紧，六具冰像凄惨地四分五裂。

「昴──!!」「昴君!!」

雷姆与爱蜜莉娅的悲鸣声重叠着，响彻化为凄惨残骸的冰之菜月・昴。

在四散飞溅的冰像碎片后方，仍立于锁链的八重逼近雷姆。电光石火间，雷姆松开晨星破坏八重的立足点。对着必然在空中挣扎的忍术使者，她拧身准备祭出全力的回旋踢──

「毕竟，我可不想正面吃下鬼族的踢击呢」

话音未落的八重突然屈膝，锁链松弛的瞬间从视野边缘掠过。

沉腰的八重在空中完美保持平衡，她指尖射出的致命丝线正要如套索般缠上雷姆的脖颈。是斩首还是绞杀——千钧一发之际，脚下锁链骤然绷直颠覆了她的预判。

「什」瞪大眼睛的八重不愧是顶尖高手，立即用脚趾弹开锁链后跃。她的视线清晰捕捉到代替雷姆拽动晨星锁链的身影。

那是胸口插着石剑最先倒下的、冰之菜月・昴。——即便倒下也不放弃战斗的冰之菜月・昴，拯救了雷姆。

这个人真的总是、为了他人不顾一切地乱来——

「就算感动得哭出来也是冒牌货吧！」

「就算是冒牌货也一样！」

八重扭曲的嘴唇尚未闭合，雷姆全力使出的后旋踢已笔直贯穿她胸口正中。

２

——异常个体。

八重认为，阻止这一切正是自己被期待履行的职责与使命。

在八重心中，阿尔那反复无常又可怕的怪物评价始终未变。──但能令他消耗、产生负荷的，正是不断叠加的异常状况。

『哈！老夫和比自己强的家伙打到半死的次数可多着咧？但活到最后的总是老夫，为了填补和那些怪物之间的差距，咱们这种偷偷摸摸的把戏就是卑鄙的生存之道嘛。只要让对方没法全力发挥，总有机会割下强者的脑袋。──反过来不也一样？喀喀喀喀喀！』

这番话，正是向八重传授忍术生存之道与技巧的村长『恶辣翁』的忠告。

她对村长的观点并无异议。但意外的是，实际验证的机会并不多。毕竟多数对手都比八重弱小。面对正面较量不会输的对手，根本用不上阴招。

那首次败北的对手正是阿尔，八重的生存之道从此扭曲。如今这个光是接触就令全身恐惧战栗的存在，只希望他能早一秒消失。为此，必须让阿尔实现那个愿望，那份期盼。

所以──，

「──我不想让那些会逼迫那位大人的东西靠近」

她知道自己很扭曲。但无可奈何。八重喜欢辛辣讨厌甜食。可这是与生俱来的天性，是自己无法改变的宿命。

既然生来就是这样的自己，那就要贯彻这样的活法。

因为八重有八重理想的、与阿尔关系的终结方式──。

「──呃」

被雷姆——那个长角少女如此称呼的她——的踢击直中，八重用身体操控术将冲击分散至吱嘎作响的四肢，把意志传导至肌肉内脏，这正是忍术的生存之道。

但即便施展全力也无法做到无伤。虽未轻视鬼族的力量，但从对方的站姿和动作来看，自己低估了其实力。通过鬼角吸收周围玛娜、爆发性提升身体能力的鬼族特性远超想象。

「再加上爱蜜莉娅大人的即兴发挥太棘手了呢～」

一边承受着判断失误的代价，然而八重却神色从容地低语。

实际上效果相当显著，但绝不能让她察觉。忍术就是要杜绝对手获取情报。若真要给，那也是用于诱导的虚假信息。那般明显的脚步踉跄，雷姆自不必说，就连观战的爱蜜莉娅和八重也会认定这是追击良机。即便如此，若八重表现得游刃有余，任谁都会犹豫是否该追击──

「爱蜜莉娅大人！」

「诶！还没完呢！」

不过那仅限于对手是堂堂正正的战斗高手的情况下。

八重制造的喘息空间毫无意义，两人毫不留情地扑向被击飞的八重。

并非无谋之举。而是拼死、竭尽全力。这才是眼下最难对付的。

「既然如此这边就用手脚不干净的坏习惯来对付！」

对抗之际，八重将双脚趾大大张开，配合双手十指操纵二十条钢线。

插在冰盘立足点上的数把刀剑——那些由冰与石制成的武器被钢线缠缚，随着八重手指的动作，钢线与刀剑交织出轻重错杂的裂风在冰面上肆虐。

沉重的刀剑与轻盈无形的钢线，应对失误就会失去一两根手脚。虽然阿尔被命令不得杀人，但只要留条命就不算违抗命令。

如此自我欺骗着，八重毫不留情地向雷姆和爱蜜莉娅迸发斩击之意。

然而──

「哈啊啊啊!!」

「呀！　嘿！　哈！」

咆哮的雷姆与狂攻的爱蜜莉娅将八重的攻击悉数击溃。

无需言语眼神的二人配合固然惊人，但更令人费解的是她们防御本应不可视钢线的方式。刀剑可见，但钢线无形。

对此理由产生疑问的八重，迟了一拍才察觉到。──好冷。比站在冰上更甚的寒冷。

「──呃、冰雾」

呢喃的吐息泛起白霜，勾勒出空气中漂浮的细小冰晶闪烁的轨迹。八重明白同样的原理也作用于钢线，使无形的丝击被冰雾显形。但冰与钢线的相性之差，远不止于此。

「──冰柱魔线」

瞬间，随着编织而出的咏唱，大气开始发出尖锐的悲鸣。

当将世界染白的寒气愈发狂暴地显露獠牙，冰雾浓度持续增加时，最先遭殃的便是质量处于劣势的钢线。

以轻盈纤薄为最大特色的钢线优势，在这冻结的世界里被碾碎。钢线能斩裂疾风，却斩不开暴风雪。──因此，判断仅在瞬息之后。

「────」

八重亲吻手指上的戒指，刹那，烈焰顺着钢线在冰面上爆燃而起。

连冻结的裂风都能推回的热浪，这迫使钢丝放弃了『不可视』的优势，转而赋予其在冰雾中也能抵御严寒的力量。

「请陪我共舞烈焰！」

缠绕火焰的钢丝释放灼热线击，『红樱』上演着燃烧之舞。

面对那照亮溪谷的煌煌炎舞，携着清冽冰雪的两人──不，连同七具冰像共九道身影飞扑而来。

「应邀奉陪！」

「踩到脚的话可别怪我哦！」

爱蜜莉娅手持冰之双剑滑入八重在冰面上制造业火漩涡的射程。

爱蜜莉娅用带刃长靴在冰面滑行，画出圆弧轨迹配合这边的炎舞，施展出看似舒缓实则凌厉的曲线攻击。

与爱蜜莉娅那快慢极致的攻势并列，雷姆选择与冰像组成密集阵型直线突进──堪称绝景──

「啊啊啊啊啊啊──!!」

雷姆如野兽般咆哮着双手向天，将那双白色拳头如雨点般砸下。

面对这堪称弹幕的风暴般攻势，八重扭身、下蹲、后仰、跨步循环往复，以舞蹈般的连贯动作擦弹闪避、闪避、闪避──

「如果只是无脑的连续攻击，永远都碰不到我哦？」

即便拥有鬼族的身体素质，八重也不会漏看从躯干传导至四肢的力量流向。雷姆的鬼族力量虽堪称惊人，却尚未达到『剑鬼』那般例外领域。若要说违和感，反倒是无视人体构造行动的冰像更为异常。

总之照这样下去，八重能永远应付他们两个──

「──不对」

险些被轻松选择带偏的八重，自己给自己喊了暂停。

这个战场是对手选的。放任对方为所欲为就正中下怀了。要阻止异常状况，自己也得成为对方的异常才行。

「眼下当务之急是──」

雷姆的连击被化解，爱蜜莉娅从背后的攻击也被回避，以冲撞而来的冰像为踏板跃向空中，八重睥睨着脚下将自己和阿尔分隔开的冰之圆盘。透过白雾朦胧的冰盘，锁定阿尔模糊的身影，她射出丝线。

四肢的钢丝向圆盘全方位延伸，八重扭转全身，倾注全力。

结果──

「──改变局面。这也是，计算之内吗？」

伴随着八重的全神贯注，冰之圆盘如陀螺般旋转，强大的离心力袭向冰面上所有人。──战场就此迈向下一阶段。

３

──『意料之外』。

爱蜜莉娅激励自己，所谓意想不到之事，正是当下他们最有力的武器。

若突然受惊，人们会瞬间忘记原本的打算。阿尔为此次计划理应思虑周全，而『意料之外』正是要击溃这些谋划。

『莉娅遇到危机时，总喜欢直接用蛮力解决对吧？当这招不管用时，才会第一次烦恼该怎么办呢……但我可爱的女儿可是拥有能砰地一声推开所有问题的力量哦，所以别停下脚步继续加油吧？莉娅可是我引以为豪的女儿，继承了最强大的基因呢』

是的，帕克曾经说过的话语，此刻在爱蜜莉娅脑海中温柔地复苏。

虽然最近令她感到安心的总是昴的话语，但当明确知道昴遭遇危险的此刻，最先鼓励爱蜜莉娅的果然还是帕克。

与雷姆联手对阿尔发动的攻势，因八重突然介入而陷入苦战──已经额外越过两道崖壁刻印，距离抵达地底只剩三十秒左右。

虽然内心焦躁不已，但绝不能就此认输。尽管不算擅长，将这份焦躁感反压给阿尔他们，正是此刻爱蜜莉娅的使命。

「──因为这种事，普莉希拉根本不可能期望的吧」

之前，爱蜜莉娅曾被阿尔救过。抛开这点不谈，爱蜜莉娅也想成为阿尔的力量。不仅是因为共享着同样的痛苦，不仅如此，出于本能的感觉，爱蜜莉娅想要拯救他。

因为爱蜜莉娅和普莉希拉，本应该能成为朋友的──。

「──呜、昴！」

猛然间，挟带热量的旋风卷起涡流，以八重为中心旋转的冰之圆盘。

如同转碟般急速旋转的冰盘上，模拟昴的冰之士兵们因承受不住施加的离心力，踉跄着被甩飞出去。它们要么毫无抵抗之力地从圆盘抛落，倒霉的则撞上溪谷岩壁粉身碎骨。但在那之前，别忘了它们曾及时拉住险些滑倒的爱蜜莉娅，成功救了她。

「雷姆她──」

穿着冰刀鞋抵抗旋转的爱蜜莉娅，在冰面上搜寻着雷姆的身影。担心她也和冰之士兵们同样遭遇──爱蜜莉娅的视野中，猛然腾起剧烈的火焰。

膨胀火焰的根部，雷姆和八重在那里激烈冲突，圆盘中央升起爆炎。

重新接住抛向空中的铁球的雷姆，与集结燃烧丝线的八重激烈碰撞，以双方冲击为火种膨胀的爆炎热浪将雷姆的身体弹向外围滑去。

「不行！」爱蜜莉娅大喊，瞬间思考扑向雷姆的方法但──

「──严禁分心」

踢击冰面的刹那，八重如尖刺般的牵制已飞袭而至。

燃烧钢丝束缚的石龙刀一击，与延迟袭来的丝击二段连招。面对需要大范围二段回避的攻击，爱蜜莉娅正欲思考──却因想起昴和帕克这两位可靠同伴的话语而放弃。

比起思考更相信直觉，爱蜜莉娅朝被弹飞的雷姆跃去。──字面意义上，她振翅飞向了雷姆。

「哇」地瞪大双眼，面对这令人惊愕的景象，八重一时愣在原地。这是她首次露出如此破绽百出的姿态，但此刻的爱蜜莉娅根本无暇顾及这些。她径直扑向雷姆，抓住她的手腾空而起。

──只见爱蜜莉娅的后背，赫然伸展着由冰晶凝聚而成的翅膀。

「谢、谢谢您，爱蜜莉娅大人……这对翅膀是？」

「之前昴给我画过的。他说背上长着翅膀的叫天使。虽然昴偶尔会提起，但没想到真的能变出来呢！」

面对被救起的雷姆提出的疑问，爱蜜莉娅笑容灿烂地回答。

不过说到底这只是徒具外形的赝品。无法像真正的鸟儿那样振翅飞翔，顶多只能借助风力滑翔。而且必须像现在这样处于高空坠落的过程中才能实现，就算想给昴展示也很困难。

虽然想着要是他能陪着一起从五千米高空坠落就好了，但要做到这点──

「爱蜜莉娅大人！我们反击吧！」

「好啊！」

展开冰翼的爱蜜莉娅，对怀中斗志昂扬的雷姆点头回应。

相信对「回击」一词产生的直觉，爱蜜莉娅将翅膀从背部剥离后，与雷姆一同沿冰面直线滑降，两人在空中旋转的同时，下砸的脚跟直击横向旋转的冰盘──为圆盘添加了纵向旋转。

结果圆盘在保留横向旋转的同时叠加纵向旋转，形成纵横交错的奇诡运动轨迹，正转、反转、再正转再反转，将战场化为无序混沌。

简直就像昴和加菲尔在罗兹瓦尔宅后院建造的训练场里，为培养『平衡感』而设置的『娱乐设施』那般。

「那这个我可超级拿手哦！」

爱蜜莉娅在上下左右无规律变换的苛酷立足点上飞驰。正为练习成果欣喜时，她突然担心起雷姆能否适应，

「请您不必担心！」

应答的雷姆将铁球刺入冰盘，猛然拽动锁链直冲中央。虽势头不及爱蜜莉娅，却充满力量感且稳如磐石，帅气非常。

「不如说、我得更小心别摔个四脚朝天……！」

在纵横交错的混乱冰盘上（或者说下）、拼命保持平衡不被甩落的爱蜜莉娅、一边搜寻着本该同处战场的八重身影、一边眨动紫绀色眼眸。

找到了。八重依旧待在冰盘离心力最弱的正中央。即便如此、爱蜜莉娅仍察觉到她理应被甩得晕头转向、正试图伸展蜷缩的双腿。

屈膝跪在冰盘上的八重、并未被旋转的立足点所摆布。

理由显而易见──她用钢线剜空了冰盘中心、制造出仅此处不受旋转影响的安全地带、正守株待兔般等着爱蜜莉娅她们。

「────」

──刹那间、缠绕火焰的钢线迸发、燃烧的银闪划过爱蜜莉娅的视野。

４

──燃烧着、火焰的银闪。

若有俯瞰此景且通晓此技者、必会认出八重・天膳所施展的、正是钢线居合术。

纤细而无固定形态之物竟能构成居合术的形态，这是任何人都无法想象的。更何况钢丝术，在忍术漫长的历史中，除少数天才外，别说掌握，连基础都是遥不可及的幻之技法。

这记绝杀被史上最具忍术天赋的『红樱』锤炼至更高境界的事实，包括阿尔德巴兰在内，无人知晓。

──正因如此，雷姆能挡下炎之银闪，只能称之为奇迹。

「──普莉希拉小姐」

雷姆唇间吐出的，是让她站立于此、指引她至此的女性之名。此刻这位恩人，又为雷姆留下了捡回性命的征兆。

感受到了。──八重那直到此刻都未曾显露的、确凿杀意。

人类感情寄宿于玛娜之中。因此玛娜感知敏锐者，更易察觉他人情感。据说精灵读取对方思想的能力亦源于此。

然后，因鬼化而通过角吸收周围魔力的雷姆，也在无意识中发挥出相同的感知力，以数倍于平常的程度接收着爱蜜莉娅和八重的情绪。

「迄今为止──」

都未曾感受到。──不，是即便感受到也未能察觉的知觉。

能感知到这些的背景存在诸多因素。既有取回自我的缘故，也因怀着夺回昴的使命感。但最重要的另有其他。

最重要的是帝国城郭都市古拉尔中，与普莉希拉共度的那些日子带来的影响。

在那段绝不漫长的时光里，普莉希拉屡屡向雷姆抛出谜语般的话语，给予她深度审视自我的契机。当时因治愈魔法的不完善与对无能自己的懊恼，雷姆只是肤浅地模仿着普莉希拉的言语──

「直到现在，才终于稍微明白了一点」

即便此刻，也不敢说完全理解了那时话语的全部答案。想必这是要用一生完成的课题。而且，再也无法与她核对答案了。

这令人悲伤。感到寂寞。胸口作痛。

「──现在，好想和您说话。普莉希拉大人」

轻声低语，闭上眼睛。而当她睁开双眼时，雷姆作为鬼族的天赋就此觉醒。

她能敏锐感知到混在玛那中的微弱敌意、杀意、攻击意图──当这些情绪仿佛带上颜色显现时，雷姆分毫不差地将铁球对准了那个方位。

为将她和爱蜜莉娅一同斩断而袭来的炎之银闪，她将晨星砸向能一击扫开它的位置，把必杀攻势改写为不杀之局。

钢铁与钢铁相击的尖锐声响彻四周，在手掌承受强烈反冲的同时，雷姆的反击正面对轰了八重释放的一闪。

「────」

面对这个事实她微微屏息，但八重仍屈身摆出下一招架势。

狂暴的无数银闪在释放前化为杀意驰骋虚空，雷姆抢先出手，沿着那些轨迹轰出铁球、锁链与魔法。

数个瞬间——几乎同时发生的刹那重叠，八重的攻击尽数被雷姆挡下。

「啊...」胸腔中漏出一声叹息。

啊啊，这就是、真正的鬼族所见到的景象。──拉姆与生俱来便触及的领域一角，雷姆也终于在迟了十年多后用手指触碰到的瞬间。

「──雷姆!!」

爱蜜莉娅一边挥舞铁球持续扫荡燃烧的钢线风暴，一边呼唤着雷姆。

那声音里蕴含的紧迫感并非对被保护的感谢，而是对状况变化——且是朝不利方向变化的警示。

余光瞥见爱蜜莉娅时，她正伸长双腿吸附在冰盘上，在旋转的视野中转动双眸，

「阿尔不见了！哪里都没有！」

「──」

听到爱蜜莉娅走投无路的声音，雷姆也终于察觉到阿尔从视野中消失的事实。

本该绕到冰盘下方、只能旁观雷姆她们战斗的阿尔，在因旋转而视野无阻的天空中却不见踪影。

雷姆正思索着去向，忽然被闪电般的直觉驱使抬起头，凝望远方的天空。

坠落中的阿格扎德峡谷，那道撕裂大地的狭长裂缝彼端，遥望着不断下落的雷姆等人，逐渐远去的黑影依稀可见。

那身影与先前的爱蜜莉娅如出一辙，背部伸展着石制羽翼──乘着风势以惊人速度滑翔的阿尔。

刹那间掠过雷姆脑海的，是爱蜜莉娅对冰盘使出的那记重击。那一击令立足点纵向旋转，将八重间的战斗推向新维度──却被反将一军。

「我和爱蜜莉娅大人蹬踏地面的瞬间──」

当时阿尔紧贴冰盘背面，借助雷姆与爱蜜莉娅蹬踢引发的旋转势头，获得了直冲天际的推进力。

「────」

若就此让阿尔逃脱，全盘战略将彻底崩溃。

连续制造意外消耗阿尔体力，再祭出我方『杀手锏』的战术将沦为泡影。──电光火石间，雷姆与爱蜜莉娅的视线猛然交汇。

「──雷姆」

本应无法听见的爱蜜莉娅意志，此刻正通过玛娜传向雷姆。

鬼角所能感知的，不仅是敌意的征兆。它更通过吸收坚定不移的信任与期待，将无穷力量赐予雷姆。甚至让人觉得，比起吸收玛娜，背负那份心意才是真正的力量源泉。

没错，正因为被分予了力量──

「──我出发了！」

「路上小心!!」

抡起全力挥下的重击砸向冰盘，急剧加速圆盘的纵向旋转，借着这股势头，原本贴在冰面上的爱蜜莉娅被一口气射向高空。

裹挟着冰晶光辉的爱蜜莉娅再度展开背后冰翼，乘着风势追赶飞向远方的阿尔，在阿古扎德峡谷的天空中翱翔、翱翔、不断翱翔。

就这样将追击阿尔的任务交给飞走的爱蜜莉娅──

「──不会让你追上去」

「这可是我的台词呢～」

坠落的冰盘上相对而立的两位女仆──雷姆与八重，鬼族与忍术使，『英雄的辅佐者』与『红樱』，最后的激战就此展开。

──通过阿格扎德峡谷岩壁的标记再前进，距离地底还有二十秒。

** 第二章 『八重・天膳』

１

──所谓忍术，就是不能对任何事物倾注感情。

这是在佛拉基亚帝国的忍术之里，那些被禁止选择忍术以外生存方式的人们所必须遵从的绝对教义，是比扎根帝国大地的铁血戒律更应恪守的铁则。

若对某物动了感情，精心锤炼的忍术之刃便会轻易生锈。

正因如此，身为忍者必须无一例外地将这条铁则铭刻灵魂，绝对服从。

可即便如此──

「我说你啊，是不是这样？跟老子一样因为啥都能干两下子，活着反倒没劲了吧。心里头装着点啥不也挺好？」

听着这个牙齿意外整齐的村长咧着嘴说笑，八重当时莫名火大——这人把忍者的铁则扔哪儿去了？

──包括她当时强烈认定自己绝不可能那样活着。

２

──『红樱』八重・天膳，是百年难遇的忍术天才。

周围的人都称赞她是忍术之村有史以来最具天赋的人，甚至有人高声赞扬她的潜力足以媲美卡拉拉基都市国家的『礼赞者』。

说实话，八重本人深切希望不要拿自己和那种离谱的对象比较，但村里人根本不顾她的感受，狂热追捧她的天资。

然而，与周围的评价形成鲜明对比的是，八重极度厌恶自己被『特殊』对待。

那是一种对『特殊』的生理性抵触——别人被特殊对待时无所谓，但自己一旦被『特殊』对待，就会涌上难以忍受的感觉，恨不得抛弃一切的『特殊』过敏症。

对于这种过敏体质的八重而言，忍术之村的铁律非常契合。

将心灵寄托于某物 就是在自己心中创造『特别』。既然对这份『特别』过敏 八重便能毫不费力地遵守忍术的铁则。实在是件好事。──不过这种适合忍术的特质 也成了周围人将八重视作『特别』对待的部分原因 所以也算有利有弊。

──说到底忍术之道险峻　绝非人人都能胜任。

其门槛之高 据说见习生千人里仅有一人能成为下忍 下忍千人里仅有一人能成为中忍 中忍千人里才终于有一人可晋升上忍──堪称狭路。顺带一提 每次听到这个比喻 八重都觉得哪有十亿人想当忍术使。

总之　用这种说法来形容选拔的残酷程度确实恰如其分。

首先 忍术修行从刚懂事的年纪就开始了 对象基本都是外村掳来的孩童。由于非人道且荒谬的修炼会导致见习生大批死亡 从外界掳掠适龄幼童反倒更有效率。

当然、对掳来的孩子会使用药物、暗示和干扰记忆的术技，让他们将家人和故乡等记忆忘得一干二净。八重也不记得父母的长相，连自己真正的名字都不知道。『八重』这名字是后来才得到的，在那之前人们都根据她的发色称她为『赤之八号』。

没有资质的人首先就会在记忆处理环节栽跟头。要么记忆消除效果不佳，要么反过来消除过头变成废人——情况五花八门。但说到八重，这丫头薄情得很，居然干脆利落地全忘了。干脆到连负责记忆处理的藤老天膳都目瞪口呆。顺便一提，这位藤老后来成了八重的命名之父，正是他让八重继承了自己家族的名号。

虽说是命名之父与孩子的关系，但两人之间更像是冷酷的指导者与学生的关系。对八重而言，藤老也不过是村里接触频率较高的对象罢了。

无论如何，通过这种手段强行剥夺心灵依靠，用忍术这支黑色画笔肆意涂抹的纯白画布——失去过往的空白幼儿就此诞生，这便是非人养成机构忍术之村的真髓，无关肉体改造的人体改造就此开始。

为掌握超越人类常识的柔体与轻功而进行的骨骼破坏矫正、从微量逐步适应致死量的抗毒训练、通过亲身体痛来牢记体术与忍术道具危险性的日常课程，折断的骨头、撕裂的皮肉、流失的鲜血都被规定了最低标准。

若有死者出现，其尸体便作为适应死亡的训练教材不得下葬，每日在床榻旁逐渐腐烂的尸骸末路与腐臭侵蚀着心神，接二连三有人陷入疯狂。

这些所谓恐怖的训练，八重都轻松完成了。——不，其实八重也付出了相应努力，只是在旁人眼里显得游刃有余罢了。

骨骼破坏与矫正已学会切换痛觉开关的方式 内脏溶解般的毒苦所导致的血尿血便被控制在最低限度 忍术道具只要碰过一次就能像十年老友般运用自如。唯有尸体的腐臭令人难熬 但说到底终究会习惯的。

就这样、年幼的八重以破例的速度成为了最初千人中的一员。

「──从今日起，你就叫八重・天膳」

被认可为下忍的那天，藤郎给我取了这个名字。

可惜、她并没有什么特别的感慨。毕竟在『红之八号』时期就受到与其他同辈不同的待遇，名字的有无对八重的自我认知并未产生特别影响。不过可以肯定的是，从那时起她就已对『特殊』待遇感到厌烦。

──至于为何藤郎会给自己取名八重，至今仍不得而知。

闻くチャンスを逃した。今となってはそれなりに気に入っているし、テンゼンの方も语感がいい。何かの间违いで、ヤエ・ダンクルケンにならなくて本当によかった。

八重这番讽刺，却被村长用「喀喀喀喀喀！这小丫头片子口气不小啊！」一笑带过。

无论如何，即便称呼从『赤之八号』变成八重・天膳，对八重而言世界的触感与作为忍术师的生存之道都未曾改变。——改变的从来不是八重，而是她所处的环境。

——这正是八重对『特殊』过敏的最大原因。

３

话说回来，虽是以最年少最短纪录晋升下忍的八重，却有人被她本人所厌恶的『特殊』深深吸引。——正是藤郎・天膳。

作为命名者兼指导前辈的藤郎，彻底迷上了八重那种能将所学之一发挥出十成、甚至百成千成效果的天赋。

这行为无疑违背了忍术师「不可对任何事物动情」的铁则。

必须亲手将不世出的天才八重・天膳培养成非凡的忍术师。——藤郎就这样被这种近乎偏执的使命感所支配。

「你明明有这种才能。为什么就是不明白!?」

双眼充血地吼出这句话的藤郎，始终强硬地相信着八重的才能。

虽然她早已察觉藤郎注视自己的眼神日渐炽热，但这次爆发带来的灾难——藤郎准备的『蛊毒』，仍远超八重的想象。

这个与佛拉基亚帝国选拔皇帝的『选帝之仪』同构的仪式，将当时与八重同级的三十名下忍卷入其中，演变成可能关乎忍村存亡的愚蠢暴行。

被带离村子的下忍们在森林里奉命自相残杀直至最后一人，他们毫不质疑上级命令，徒然浪费着生命。——最终正如策划仪式的藤郎所愿，仅剩八重・天膳存活。

但因为她始终采取不主动出击、只反击来袭者的战术，甚至放走了最后求饶的同僚，令他勃然大怒。

——不，准确地说，发怒的不是他，而是他们。

被八重・天膳的才能所倾倒、误入歧途的不止藤郎一人。受他话语感化，或是亲眼目睹八重的成长，企图通过执行名为『蛊毒』的仪式让八重背负扭曲期望的大有人在。

若这些人因八重背叛了他们的期待而将其处决后自尽，倒还显得有几分可爱。但那些坚信八重可能性，决意错误地反复实施『蛊毒』直至成功的家伙，八重能给予他们的只有超度。

「你是颠覆忍术存在方式之人……！」

直到生命最后一刻，藤郎都坚信着八重的可能性而死。

在那些喋喋不休的喉咙被剜开，倒在血泊中的命名之父与愚蠢同伴们的尸体上，讽刺般纯净的白雪樱花瓣正簌簌飘落。

八重永远记得那些被鲜血浸染的花瓣，以及随之而来的难以名状的徒劳感。

「──哎哟喂，这可真是了不得啊。一群乳臭未干的小丫头片子，居然把上忍都给全灭啦？」

姗姗来迟的里长悠哉的感慨，印证了藤郎他们暗中活跃的事实。虽说他应该不至于认为村里那些不安分子全交给八重处理就完事了。

「所以，全都死透啦？」

虽非出于这般猜忌，八重还是对里长的询问撒了谎。

藤郎等人不满的根源在于——八重放跑了其中一名求饶的同僚，但她隐瞒的不仅是那人会『蛊毒』的事实，更刻意忽略了这名忍术之里叛逃者的存在。

那位同僚曾提议「啊—既然这样你要不要也一起逃？」但八重斩钉截铁地拒绝了。并非想留在村里，只是不愿与之为伍。

论实力八重远胜于他。可本能却在嘶吼着警告——若八重终有一死，必是与此人并肩而立之时。

「──失策失策」

从丢下这句话转身离去的同僚身上，我感受到了他想抹杀所有知晓自己存活之人的意志，但所幸对方尚有理性能够放弃这个奋斗目标，使得在这场『蛊毒』中只有八重和那位同僚幸存。

多亏不必成为唯一的幸存者，患有『特别』过敏症的八重心想：自己身上的『特殊性』或许也能稍微淡化些吧。

「那咱就回去咯。——『红樱』哟」

背对着她的里长，用八重首次听闻的别名称呼她。

藤郎最终也没能问出为何给自己取名八重。但里长如此称呼她的理由，即便不说也心知肚明。

——在那个忍术师接连丧命的夜晚，盛放的白雪樱被鲜血大肆浸染。

４

——『红樱』八重・天膳，是举世罕见的忍术天才。

当她以最年轻之姿晋升上忍，这份认知成为无可动摇的共识时，八重那偏执的『特别』过敏症已到了无可救药的地步。

对八重而言，被他人『特殊』对待既是诅咒也是威胁，更是只会给人生带来负面影响的可怕干涉。自从藤郎那件事之后，这类让她如此确信的事例屡见不鲜，八重早已对『特殊』精疲力尽。

「你这家伙，不就是那个嘛？和咱一样，正因为啥都能凑合着干，这样活着才没劲不是？心里头总得搁点儿啥才对吧？」

村长竟要亲自让这样的八重打破忍术铁则，简直不可理喻。说到底，八重根本不追求什么人生意义。那种东西本就是多余的累赘。

所谓人生意义，无非是期待自身能力、怀抱未来希望——这等同于相信自己的『特殊』，无疑精准踩中了八重的地雷。

所以八重刻意让自己远离众人期待与憧憬的忍术形象。

那正是与藤郎天膳赌上性命都要完成的忍术形象背道而驰的存在——轻浮的举止、捉摸不透的言行、看似亲切却绝不与人深交的姿态。

作为那般轻浮浅薄之人，八重・天膳将自己精心打扮了一番。

为避免误会事先声明，这是厌恶『特殊』的八重必然的选择，绝非参考了村长的角色性格。

不深究任何人的人生，不直面任何人的目光，不被任何人珍视。

这正是『红樱』八重・天膳的处世之术与人生哲学──

「──该不会真把这种丑陋活法，当作自己的天赋了吧？」

没错，当两人独处时突然被搭话，八重因那抹赤红的美貌而屏息。

对『特殊』严重过敏的八重，既厌恶自己被『特殊』对待，也对他人之特殊格外敏感。──而她的『特殊』堪称完美。

──『血染新娘』普莉希拉・跋利耶尔。

被领民尊称为『太阳姬』的她共度的日子，对身为忍术执行过各种任务的八重而言也极为鲜明且印象深刻。──八重以女仆身份潜入普莉希拉麾下，实为帝国『九神将』奇夏・戈尔德的指使。

远在露格尼卡王国参与王选的她，对帝国究竟有何种意义，八重既未被告知，也无意询问。

虽说如此，任务中难以理解的不合理之处仍令她不禁侧首。

基本只需监视目标动向并汇报，未接到任何破坏或妨害指令，更非要求速速暗杀。日复一日平淡的女仆生活，说来或许冒犯，实属对天才忍术『红樱』的浪费。

事实上，对掌握全套潜入技术的八重而言，潜入跋利耶尔宅邸执行女仆工作轻而易举，仍是与往常无异的轻松任务。

唯独接触普莉希拉时，必须万分谨慎。

由于工作性质，八重也常有见到要人的机会。命令八重执行此次任务的『白蜘蛛』是如此，姑且算是村长的『恶辣翁』也是帝国的要人之一。虽说是远远望见，但也曾见过皇帝阁下──那时还与皇帝身旁的『青色雷光』对上视线还被挥手致意，让人深刻体会到天外有天的恐怖。那才称得上是『特别』的存在。

即便是见识过这些大人物的八重看来，普莉希拉这个人也深不可测，完全无法预料她会看透什么。

明明不该如此，却多次怀疑她是否早已识破自己帝国刺客的身份。当然，也无法断言绝无可能──普莉希拉身上具备着堪称魔性的、令人费解的吸引力。

对此，八重将『特别』的普莉希拉视为不幸之人而心生怜悯。

她那稀世美貌自不必说，就连举止言行、甚至吐息中都蕴含着魅惑他人魔性的普莉希拉，无论他人情愿与否，都会以这份『特别』触及所有人的视线、情感乃至人生。

众人会对她寄予厚望、怀抱期待，也会被邪恶的欲望和情感所支配吧。──就连八重怀有的这份怜悯，也是她的『特别』所引发的。

方才她那句话，简直像看透了八重心中所想般脱口而出。

在私人房间里低头看着手边的书，连为我准备茶水这边瞥都不瞥一眼，正这么想着就突然毫无征兆地说出那种话。不过，普莉希拉身边时八重总是保持着警惕。所以这次也能隐藏惊讶装出平常的样子。

她轻佻地带着戏谑的态度，表现得毫无认真之意，脸上挂着微笑。

面对八重这种敷衍的态度，普莉希拉眯起一只眼——

「──迟早，你这家伙也会迎来必须倾尽自身一切的时刻。千万、千万要将妾身的话语铭记于心。准备要做到『ぱーふぇくと』才行」

那句话的真意，八重没能听进去。

既有忍术的直觉在告诫她，若追问可能会引起怀疑。但恐怕更多的是，八重对此感到厌恶。

从『特别』的普莉希拉口中，会向自己抛出不利的话语。

所以八重，并不知晓普莉希拉那句话的真意。

藤郎为自己取名八重的理由也好，里长近乎骚扰般屡次企图让自己违背忍术铁则的算计也罢，全都——

──因为这就是八重・天膳的人生哲学：既不追求『特别』，也不被要求『特别』。

５

最终，八重的想法是正确的。

那般光芒耀眼、以烈火般『特别』姿态迷倒众人的普莉希拉，也倒在了残酷无情的帝国大地上，散尽了生命。

然后，那些渴求着她已失去的『特别』之人，在被无处安放的感情灼烧灵魂的同时，仍想报答那份『特别』，正燃尽自己的人生。

八重・天膳，不希望被那样的『特别』所摆布。

所以，所以才这样。

所以必须尽快，将让自己产生不良执念的『特别』，从这个世上抹去。

这正是对被迷恋的『特别』抛弃的他，八重赌上性命协助的唯一理由──

「──呃」

纵横无尽、不顾上下左右高速旋转的冰之圆盘，即便如此仍以其为立足点构筑战场的八重，迎击袭来的青发鬼──雷姆。

挥出的右手钢线纵向疾驰，左手钢线横向扫出缠住的刀剑。两种斩光形成的难以躲避的狙击，将雷姆从正面与背后同时夹击。

──因对方的配合，八重让爱蜜莉娅从战场上逃脱了。

背生冰翼的爱蜜莉娅借助旋转冰盘的冲势与风力，朝着远方天空中逐渐飞离的阿尔紧追不舍，身影急速远去。尽管她即将脱离钢丝的射程范围，仍有机会发动丝线远投攻击──

「严禁东张西望！」

随着雷姆以超人反应挡下双重攻击的怒吼，这最后的机会也被彻底粉碎。

「突然变这么难缠太狡猾了吧？到底是什么原因──」

「──是爱！」

「……就不该问！」

八重俯身贴附在旋转的冰面上，躲过受情绪驱使而狂暴挥舞的铁球，对着不讲道理强化自身的鬼族少女吐了吐舌头。

附加了纵横向旋转的冰盘虽运动轨迹难以预测，但转速却存在固定节奏。八重凭借天生敏锐度捕捉规律，以灵活步法闪避刚腕攻击，如同冰上舞者般轻盈跳跃，试图将战局拉入自己擅长的中距离。

「绝不会让你得逞……！」

与华丽攻克冰盘的八重形成鲜明对比，雷姆的决策简单明了——她将贯手、脚尖、握着的短铁球接连砸向冰面，以野兽般的动作紧追八重。

那是与优雅精致完全背道而驰的、粗暴凶猛的肉食兽狩猎风格——即便如此，却快得惊人。转眼间就缩短了与翩然闪避的八重之间的距离。

「这般不顾形象，女仆的品格何在？」

「不巧，我们主人对女仆要求的资质只有一项——拼尽全力！」

抬头的雷姆以三肢撑地扭转身体，借助冰盘旋转之势掷出铁球重击。八重调动钢丝卸去力道，不甘心地咬紧牙关。

两大阵营的最强女仆对决——八重可没闲心拿这种事开玩笑。

虽在技巧上更胜一筹，实力也自诩高出对方不止一级而是三级，但八重和雷姆之间单纯就是相性不佳。那能捆缚绞合、对任何攻击都有招架余地的钢线，为确实挡住雷姆以一击必杀为目的的晨星，不得不动用双手七根手指。既然如此，便用剩余的钢线瞄准必杀——，

「啊啊啊啊啊!!」

四肢插入冰面、咆哮的雷姆全身蒸腾起红色热气。

这是由于数千米高空下降导致的低温、充盈全身的玛娜激活了鬼族特性，再加上八重施加的钢丝撕裂伤正在急速恢复的结果。

在此期间，八重一边躲避雷姆的致命一击，一边在她身上刻下多处旨在使其丧失战斗力的伤痕。但无一能超越鬼的恢复力。

而最重要的是──

「嘘──」

她亲吻戒指，钢线再度被火焰吞噬。

那一瞬间，用弥漫的火焰遮蔽雷姆视线的八重，朝着热浪另一侧她的脖颈，将拉回的手臂一闪──以逼近音速的速度放出钢线，企图斩首。

这是秘传书中没有的、八重原创的忍术技巧──用阿尔的风格来说，就是必杀技。

射程不明的不可视线击，本应成为绝命一闪斩杀任何对手。然而，雷姆却躲开了这一击。──而且，不是一次，是两次。

「──」

初次施展时，曾贪心地企图将雷姆和爱蜜莉娅一并狙杀。

被挡下是因为目标太大。为了不让这样的借口成立，本该确实击杀雷姆的一闪──被躲开并非奇迹或偶然。是必然。

雷姆已经看穿了八重的钢线术。周围已无冰雾，并未使用与爱蜜莉娅相同的探测方法。即便如此，鬼仍让忍术的必杀失效。

「不会让你得逞」

放弃了毫无意义的掩饰表情，八重紧绷嘴角低语。

不会让你得逞。不会让你如愿。不会让你阻止。──雷姆也好爱蜜莉娅也罢，都由八重来阻止。

展开石翼，阿尔未等这场战斗分出胜负便逃向天空。

八重既不认为这是被遗弃，也不觉得遭到背叛。虽不排除被放弃的可能性，但阿尔生性吝啬。无论是手牌还是棋子，都不会轻易舍弃。

所以八重将阿尔的撤离视为托付。他理解为这是命令自己无论如何都要阻止紧追不舍的两人。

因此，阿尔将杀人许可证托付给了八重。

「──就算杀死也要阻止」

阻止、阻止、无论如何都要阻止。

将妨碍阿尔目的的存在全部清除。──为了让那个失去『特别之人』普莉希拉而挣扎的阿尔，尽早从世界上消失。

若不这样做，八重・天膳就无法变回那个遵守忍术铁则、对万物毫无眷恋、厌恶并远离『特别』的自己。

６

「──是你运气太差了」

是的，那个令八重・天膳恐惧的怪物，反反复复说着同样的话。

受命潜入、被派遣至跋利耶尔宅邸的日子突然迎来了终结。

每日的女仆工作，戏弄可爱的见习执事，与不被当作骑士对待的小丑骑士斗嘴，侍奉那位可怕又耀眼的『太阳姬』倒也不坏。

但命令既下，八重的个人感受无关紧要。只需完成任务，然后消失。

就在她准备执行突然下达的暗杀指令，悄然接近寝室里的普莉希拉时，那个男人在昏暗宅邸的走廊上拦住了八重。

面对无需解释、早有预谋的阻挠，八重与男人──阿尔展开了死斗。

话虽如此，实力差距显而易见。虽是王选候补的骑士，阿尔的实力远逊于八重，胜负本该瞬间分晓──本该如此。

「──只是运气不好罢了」

明明已确实贯穿心脏的男人，却用同样轻松的语气抛出话语。

即便遭遇如此异常事态，八重的身体仍毫无停滞地行动，将下一次致命攻击砸向对手。

杀也杀不死的家伙，我可不是头一回遇到了。世上多的是奇奇怪怪的奇葩人类，我还跟长着三颗心脏的怪物干过架。不过把那家伙第三颗心脏打爆后也就死透了。说白了，只要杀到死透就行。

我砍下过他的头。把身子劈成两半。放火烧遍全身。扯断四肢。撕开喉咙。敲碎脑袋。剜出眼球。剥掉全身的皮。粉碎所有骨头。捣烂内脏。灌下毒药。埋进土里。沉入水中。勒住脖子。勒住脖子以外的部位。我把忍术的招式试了个遍，夺走所有能夺走的性命，用尽所有能用的杀人手法。

「──是你运气不好」

可是无论杀多少次，阿尔都会爬起来，对我说同样的话。

八重使尽了掌握的忍术招式，尝试了能想到的所有手段，最后甚至放弃思考任凭本能驱使，可还是杀不死他。怎么也杀不死。

「──是你运气不好」

试过让他后悔出生的拷问。没用。试图放弃任务逃跑。没用。想要拉别人下水。没用。

终于决定到此为止，把绳子套在自己脖子上结束一切。

「──是星星的错啊」

就连这个，也没用。

「──是星星的错啊」

不断重复的相同问答，徘徊在永不终结的死亡螺旋之间，被永无止境地赋予相同轮回，八重・天膳有生以来第一次感到恐惧。

「──是星星的错啊」

只要能得救，什么都愿意做。发过誓什么都愿意做。

只要能结束，什么都愿意做。发过誓什么都愿意做。

「──是星星的错啊」

就算懂得了恐惧，阿尔、那个男人、那个怪物，也没有原谅他。

「──是星星的错啊」

即使心灵被摧毁得体无完肤，怪物的无常轮回依然没有尽头。

次数，早已数不清了。这世上再没人像八重这样，与这个怪物相互厮杀如此多次。

数不清的次数里，八重杀死他；不愿去数的次数里，八重被他杀死。

「──只是运气不好罢了」

这样的对手，别无二家。不需要。连想都不愿去想。

即便如今已从怪物的心血来潮带来的无尽螺旋中解脱，即便此刻仍宣誓效忠并全心全意协助其目标，这句话依然铭刻在灵魂深处。

「──只是运气不好罢了」

必须尽快让怪物消失，让那个男人消失，让阿尔消失。

无论出于何种契机、何种理由、何种羁绊，八重・天膳的心都绝不能被任何事物束缚。

「──只是运气不好罢了」

──她的心，绝不能被任何事物束缚。

７

「──只是运气不好而已」

随着八重唇间吐出这句话，无形的斩光迸发，直取雷姆纤细的脖颈。

雷姆在肌肤战栗的感知中察觉危机，反射性挥动紧握晨星的手臂，让锁链截击于刀光轨迹之上，将其格挡开来。

──生死一线，此刻无疑正立于生死线上。

在失去记忆、丧失战斗力的佛拉基亚帝国未曾经历过的修罗场中，雷姆抵达了连失忆前与大罪司教及白鲸战斗时都未能企及的境界。

「──昴君」

感受着发热额头上的角──从那里源源不断涌入的力量、情感与世界的脉动，雷姆轻唤心爱少年的名字，让自己的灵魂为之振奋。

耀眼『太阳姬』给予的建议与对意中人情愫的高涨相互交织，流淌在雷姆体内的鬼族之血，正逐渐发挥出其原本应有的性能。

即便如此与八重的实力差距悬殊，雷姆能在至今所见屈指可数的强者八重面前坚持至此，并非仅靠一己之力。

这是众多力量结晶共同作用的结果──为了阻止八重，不，是为了阻止阿尔他们而顽强抵抗至今。

从普雷阿迪斯监视塔开始，与菲鲁特阵营的冲突和王都攻防战，再加上奥托执着的追踪，以及这次的分割袭击，通过反复实施非常规与稳健的战术，阿尔他们已被名为无法逃脱的消耗战的锁链紧紧束缚。

雷姆与八重之间的实力差距能暂时被填补，多亏了那锁链的重量。再加上，堪称讽刺的机缘巧合成为了雷姆的顺风。

「──」

咬牙切齿的八重手指跃动，挥出的钢线撕裂长空逼向雷姆。

面对倾泻而下的无数斩光，雷姆通过角敏锐感知、回避、回避、达成完全回避，维系着本该断绝的性命，在战场上死死纠缠。

那神乎其技──不，鬼乎其技的回避秘诀只有一个。

「──杀气」

看得见。感受得到。传递而来。──通过鬼族的角，对方的意志。

闪避那看似染上颜色的死线，循迹，反击，雷姆向八重逼近。

自从爱蜜莉娅追赶阿尔脱离战场前后，八重的攻击里明显开始混杂杀意。毫不迟疑要斩首断肢的杀意乱舞──那强烈刺激着鬼族本能，讽刺地化作顺风催生出雷姆的超常反应。

如果八重从一开始就遵循不杀方针与雷姆对峙，恐怕雷姆会更早被她制服。──但当八重真正开始发挥忍术本领时，她的攻击反而无法触及雷姆了。

「────」

雷姆将脚尖刺入旋转的冰盘支撑身体，在飞溅冰屑闪烁的视野中，捕捉到八重那张笑容消失、正凝视这边的面孔。

八重眯起狭长的眼眸锐利如刀，自律克己的姿态美得夺目，雷姆能感受到那具柔韧锻炼过的躯体正燃烧着使命感的火焰。

必须实现的愿望与无论如何都要达成的祈愿，赋予八重超常力量，让她怀着即便与全世界为敌也在所不惜的觉悟。

而这份使命感从何涌起——雷姆心知肚明。

「因为我也……雷姆也是，同样的存在」

即便额头生角、遍体鳞伤、从五千米高空直坠而下，雷姆能像这样站立于此的理由，同样源于使命感。

然后，这份使命感究竟从何而来，雷姆没有避讳的理由。

那就是──，

「──爱!!」

「蠢货就只会这一招……！」

面对咆哮的雷姆，八重回应声中带着焦躁。

压抑情感、从不显露真心的忍术原生色彩。雷姆既不认为这是不成熟也不觉得是傲慢。咬紧牙关是理所当然的。──若为某人倾尽全灵的话。

「────」

视野边缘激战正酣时，岩壁刻划的线条掠过雷姆的意识。

阿古扎德峡谷，五千米，最后一根，距地底还有──，

「──十秒!!」

「──」

直面如怒涛般袭来的丝线攻击，雷姆故意如此喊道。

提供情报。增加判断素材。扰乱思维让二十根手指中的一两根迟疑也好。激怒对方，暴露情感，使其憎恨自己。让恶意、敌意、杀意满溢而出，再将其穿越，穿越，穿越越越越──。

然后──，

「就是这里！」

雷姆和爱蜜莉娅的算计得逞──最后十秒，随后在五秒的位置，来自正下方的冲击毫不留情地击穿了冰盘。

８

「──是你运气不好」

是的，盘踞在八重心里的怪物时常这么低语。

直到现在，八重仍会在梦中听见那男人说过千百次的声音。那是最糟糕的噩梦。

最初，阿尔这句口头禅令八重感到憎恶。八重心灵龟裂破碎绝非时运不济，分明是那怪物所致。难道还想推卸责任吗——

但渐渐地，八重意识到这并非男人的托词，性质截然不同。

「──是你运气不好」

每当说出这句话时，阿尔从未显露胜利者的傲慢。

那话语中不含轻蔑或嘲弄，或许更接近慈悲或同情之类的情感。

正因如此，那个怪物、那个男人、阿尔，始终没有说出那句话作为佐证。

关于普莉希拉・跋利耶尔之死，他从未归咎于时运不济。

对于没能挽救她生命的无能自己，他也未曾抱怨命运弄人。

「──是你运气不好」

怪物也好，男人也好，阿尔会说出那句话的时候，总是当自己那不讲理的力量，挫败了对方的愿望或目的之时。他总是对对方这样说着。

──错不在你。

啊啊，讨厌。讨厌讨厌。真的讨厌。

这种事情，根本不想察觉。

阿尔的话语，男人的眼神，怪物的内心，根本就不想意识到。

八重不想对阿尔找出恐惧以外的理由。不想怀抱。不想记住。

所以，想尽快结束。

──不想给这份『特别』，赋予恐惧以外的名字。

９

「错的，全部，都是星星……」

听到从自己唇间漏出的低语，八重刹那间找回了飞散的意识。

瞬间，她察觉到自己身体被抛向空中，视野天旋地转。

冲击，没错，有冲击袭来。

冰之圆盘从正下方受到某种打击，碎冰的冲击贯穿了八重全身。

「什么情况」，往脚下看去，击碎冰面的竟是数千米深峡谷的地底──那里冻结了奔流的大河形成的巨大冰山，而撞击点正是其顶端。

这超出常理的怪力，显然是爱蜜莉娅所为。但更令人震惊的是──

「……真是个难缠的女人呢」

在旋转的视野中，碎裂的冰晶化作璀璨的钻石尘雾，八重看见顶着发光尖角的雷姆正穿梭于这片绝景。

碰撞瞬间，雷姆为躲避冲击腾空而起，此刻正借飞散的冰块加速，朝滞空中的八重猛冲而来。

──将距离冰山相撞的五秒，误导成还剩十秒。

丧失冷静乃忍术大忌，落于下风是女仆失职，辜负托付更非『红樱』所为──

「──只是运气不好罢了」

八重宣告的对象，既非迫近眼前的鬼族少女，也非狼狈不堪的自己，而是那个早已飞向遥远彼方、此刻不在场的怪物。

当非同寻常的怪物对他人说出那番话时，对怪物而言也有着相同的意味。

「──啊」

全身嘎吱作响，手脚也失去知觉。但是，疼痛？麻木？这些早在地狱修行中就克服了。通过拷问训练被折断全身骨头，经历放血致死的濒死训练也都熬过来了。耳边传来村长那刺耳的笑声，仿佛在说「这下见识到了吧」。气得要死。虽然气得要死——，

「──啊」

重复了成千上万、数十万、数百万、数千万次相同的动作。

八重操纵着数百年无人使用的钢线，这需要以毫米为单位移动指尖的精湛技艺，在手指麻木、流血、意识朦胧的状态下。

即便这副身躯的生命已流失九成，操纵钢线的手指也绝无差错。

「──啊啊啊啊啊！」

伴着喷血的惨叫，被钢线捆缚的冰块瞬间狂暴地划破长空。

被冲击震碎的冰盘碎片、用丝线缠住的那些碎片随着八重全身的律动在空中嗡鸣，朝着扑来的雷姆横抡猛砸。──轰鸣声响彻云霄，被冰块殴打的雷姆以惊人势头倒飞出去。

仿佛要对飞出去的雷姆追加攻击般，钢线捕获的冰块接连、接连、接连不断地投掷而出，如流星般倾泻向先一步落在冰山顶部的雷姆。

飞扬的白色雪烟、弥漫的冰雾中混入了鲜血，将冰山化作恶鬼的墓碑。──刹那间，墓碑从内部被贯穿，猛然伸长的铁球笔直刺向八重。

「──呜」

凶恶的铁块、以及附带的尖刺剜开八重的躯体，贯穿侧腹。

但重要脏器已挪至侧边。凭借忍术非人道的肉体改造，八重能移动体内器官位置。穿过脏器间隙的尖刺、被收紧的肌肉强行封堵。

武器被夺。下一秒，染血恶鬼撕裂弥漫的白色雪烟冲天而起。

那道轨迹笔直无曲、毫无花巧、不加修饰，纯粹以满腔心念径直突进。──只见网状分布的钢丝迎面拦截了飞袭而来的雷姆。主动投身死地的雷姆雪白肌肤绽开无数裂痕，眼看她就要被分割成数百肉块──

「──修玛」

千钧一发之际，雷姆的嘴唇吟诵出这场战斗中屡次目睹的魔法。

本应将雷姆身体切得粉碎的钢线，其触感突然中断。只见嵌入她肉体的钢线连带着鲜血一同冻结凝固。──这与甘愿承受铁球攻击的八重采用的武器封锁思路完全相同。

刹那、亲吻戒指的动作为钢线点燃火焰，用冻结的爆炎对抗血液的凝固──太慢了。

「呀啊啊──!!」

雷姆没有放过钢丝瞬间的弯曲，咆哮着向八重挥起拳头。

染血的白拳，八重从中看出了决一死战的全力。

因此，不能吃下这招。——为了不吃下这招，必须亮出王牌。

「────」

雷姆用双手双脚共二十根手指操控，避开了所有袭来的钢线。

但是，还有。八重・天膳的王牌，那是——

「呸」

微微吐出的舌尖，从戴在那里的戒指中，释放出最后的斩光。

这一击准确无误地命中猛然逼近的雷姆纤细脖颈，将其生命一刀两断。

10

——『红樱』八重・天膳，是举世无双的忍术天才。

对其才能与实力给予高度评价的『恶辣翁』奥尔巴特・邓克尔肯说道。

这是对或许终有一天能与自己比肩的天才少女的建议——不，是忠告。

「讨厌吧？老夫也有过经验啊。像咱们这种非凡之人啊，总比普通忍术师活得久些，见识过各种玩意儿。所以偶尔会这样啦。也会有守不住忍术铁则的时候嘛」

「嗯？你说没有重要东西的人就弱爆了？不对不对，老娘说的可不是这个理儿。是这么回事啦——不知道啥毒就解不了对吧？从小不碰毒就是为了不被毒死。那心里头留个念想不也一样？就像为了防止被毒死才不碰毒似的」

「毕竟咱既没爱过人也没被人爱过嘛。会变得超弱的啦。——头一回懂得珍惜别人的忍术使啊。喀喀喀喀喀！」

11

寒光一闪，从舌尖勾着的戒指迸出钢线，准确无误地掠过扑来的鬼族少女细颈，将头颅与躯干的连结一刀两断。

解除不杀戒律的阿尔，成功扫清了前进路上的障碍。

想到这个事实，以及阿尔知晓后的反应，八重胸腔深处泛起阵阵绞痛——

「——哈？」

就在即将沉溺于苦涩的刹那，八重眼前的景象让她怀疑自己的眼睛。

毫无疑问，八重的钢丝斩断了雷姆纤细的脖颈。确实感受到了切断猎物生命的触感，听到了斩断血肉骨骼与生命的风切声。

然而──

「──这边也，耍了花招呢」

八重的赤红瞳孔与雷姆的淡蓝眼眸交汇。那双眼睛，仍未失去光芒。

接着，本该确实切入脖颈的夺命红线，缓缓消失。──既非格挡也非闪避，本该确实夺命的一击，被强制取消了。

这绝非仅用鬼族恢复力就能解释的、本不该存在的奇迹。能引发此等奇迹般事件的，纵使世界广阔也──

「──阿尔大人」

即便与世界为敌也绝不会落败的怪物，她曾渴望借助那份力量。

这么做是为了，抹消自己心中萌生的『特别』。

可是──

『──只是运气不好罢了』

闭上眼睛，又会听见令人毛骨悚然的可怕话语。

唯独此刻不可思议地，带给八重的并非恐惧。

「败因是」

「──是爱」

与答案一同挥出的巨臂，将铁球狠狠砸进八重的躯体。

比五千米高空坠落更为致命的鬼之一击炸裂──在阿格扎德溪谷的冰山顶部，鲜红的樱花四散飘落。

──名为八重・天膳的『红樱』，在青鬼面前凄美激烈地凋零了。

** 第三章 『阿尔德巴兰』

１

「──没有人能战胜我创造的你哦」

阿尔德巴兰能清晰回忆起『魔女』昨日才说过这句话般。

按实际时间算已是近二十年前，体感时间则漫长到不愿细想。至少可以肯定，这远比普通人生老病死的一生要长久得多。

他持续度过了太多毫无意义的时光。但若问阿尔德巴兰的精神是否已达到活过数百年的不老精灵同等境界，答案是否定的。人类精神从不成熟到成熟，最终老练达观，是因为在经历的时间中尝遍酸甜苦辣，给予了精神成长的空间。

但是，阿尔德巴兰所经历的时间，不过是为了突破眼前横亘的困难而不断停滞的瞬间。实际上从数秒到最长不过数分钟，即便将这等短暂时光重复无数次，也无法指望获得人性层面的成长厚度。

因此、阿尔德巴兰认为、凭借权能不断累积的时间不过是消磨自己心灵却毫无成长的、无为的时间。

然而，即便是如此无为的时光，若重复上百、上千、上万次，大脑也会自然而然地开始整理记忆，试图从阿尔德巴兰那里夺走真实的回忆。

即便如此也无法淡忘的记忆，那绝非刻在脑中、而是深深烙印在灵魂里的回忆确实存在，开篇那句话正是如此。

不过，若是听到现在阿尔德巴兰的见解，那个对一切都充满好奇心的化身——『魔女』嘟囔着「这样啊，真遗憾呢」的身影就会浮现在眼前。明明装出一副无法理解感情的样子，却是个善于操纵他人、狡猾的『魔女』。即便明白这一点，阿尔德巴兰也无法违抗『魔女』的言行。

说是被这样调教、改造的——或许能和从八重那里略有耳闻的忍术之里的非人行径一较高下。

这种情况下，究竟是和『魔女』相提并论的忍术之里更疯狂，还是单枪匹马对抗忍术之里历史的『魔女』更离谱，算是半斤八两吧。

——总之，现在的阿尔德巴兰是由『魔女』创造出来的产物。

「话虽如此，你也有权选择自己的人生。这一点，即便是造物主也不该单方面侵犯。所以，如果你真心觉得无法服从于我，随时可以退出计划。那是你的自由」

每逢此时，『魔女』都会这样说着，仿佛在试探阿尔德巴兰的决心。

对『魔女』而言实属罕见的顾虑。她惯用的策略是——一旦获得对方承诺，就会步步紧逼不让对方收回诺言。事实上，阿尔德巴兰接受『魔女』布置的课程和课题中，不乏让他因先前承诺而后悔到想放弃的内容。

每当让他完成这些时，『魔女』总在得到首肯后绝口不提放弃二字。——可偏偏对最初那份决心，她却反复追问。

那或许，是『魔女』特有的罪恶感与纠葛吧，你觉得呢？

自称不懂感情的『魔女』，终究并非不知愤怒悲伤与喜悦。既然能表露这些情感，想必也会怀有罪恶感，或对未来的恐惧吧。

至少在与『魔女』共处的时光里，阿尔德巴兰虽常觉得她是『不懂人心的魔女』，却从未认为她是『没有人心的魔女』。

『没有』与『不懂』之间，横亘着截然不同的风景。

那或许是以『魔女』提问的形式表现出来的吧。如果是这样，那么每一个提问都意味着『魔女』曾经犹豫过吗。

她是否曾因担忧阿尔德巴兰即将踏上的残酷道路而纠结，是否想过要尊重阿尔德巴兰自身的意志，让他自己选择人生。

倘若、倘若、万一、亿分之一的可能性，『魔女』怀有那样的心情——讽刺的是，那反而会成为阿尔德巴兰绝不改变决心的理由。

所以——，

「——这样啊」

对于阿尔德巴兰千篇一律的回答，『魔女』的反应也总是如出一辙。

说不定，我们都被骗了。

从阿尔德巴兰诞生到迎接命运之日，『魔女』或许花了大量时间对他进行洗脑。阿尔德巴兰所期待的罪恶感或犹豫之类的情绪，『魔女』可能根本不存在。

说不定，她就是那样邪恶的『魔女』。

但即便这样当面质问，『魔女』仍会浮现那黑白分明的美丽微笑，

「这不是当然的吗。——我可是，邪恶的魔法使啊」

就这样用真假难辨的回答，把阿尔德巴兰耍得团团转。

２

阿尔德巴兰正沐浴着呼啸的狂风，在高速滑翔中穿梭。

背上那对用石头打造的笨拙翅膀，靠着它迎风飞行的自己想必滑稽极了。石翼的成型对大小和硬度有着微妙要求——太大容易被风吹偏，太小又兜不住风，只能可怜巴巴地倒栽回地面。

「一次就成功的伊卡洛斯真叫人佩服……！」

说到人造翅膀，就会想起用蜡翼飞天的伊卡洛斯老前辈。且不论结局如何，单凭他敢用人造翅膀逼近太阳的胆量就令人肃然起敬。阿尔可是摔了几百回，才勉强能拙劣地滑翔。

「难不成…『领域』的弱点被精准狙击了？」

当时绝不能继续坠落。这个事实与焦躁感，正是阿尔德巴兰从石翼等级1手忙脚乱提升到勉强能飞水平的最大原因。

阿尔德巴兰也自负其『领域』是无敌的权能，但并非完全没有弱点。不料此次对手的奇袭，正是从两个角度直击其弱点。

阿尔德巴兰的『领域』正如其名，存在效果范围。

基本上以阿尔德巴兰为中心展开的『领域』，不仅包含水平方向的扩展，还包括上下──即高低差的覆盖。

结果奇袭造成的转移将阿尔德巴兰逼出设定好的『领域』之外，同时叠加了超高高度坠落这第二重『领域』破坏手段。因此阿尔德巴兰只能在急速坠落中，反复于飞出『领域』前自尽、坠落中途重新开始，最终不得不决定用石翼脱身。

接下来只要八重能拖住时间，尽量拉开距离消除高低差──

「──阿尔!!」

一道银铃般锐利的声音，呼唤着如此拼命的阿尔德巴兰。

略微回头望去，只见从比阿尔德巴兰低得多的空中，却有天使——不、是爱蜜莉娅的身影正朝相同方向清晰可见地翱翔而来。

她在那纤细的后背上背负着冰制的翅膀，虽然和阿尔德巴兰是相同的手法，却以那出色的外观拉开压倒性的差距，同时又在迅速缩短距离。

「不敢相信」

只能哑然地、几乎像是佩服般地嘟囔着。

阿尔德巴兰为了完成这对笨拙的石翼付出了多少艰辛，正如前文所述。正因为有这番苦心，才对蜡制翅膀的伊卡洛斯抱有敬意。然而，与神话中的伊卡洛斯如出一辙，爱蜜莉娅一次性就成功造出人造翅膀的才能，让人涌起的不是敬意而是挫败感。

「不是那边天才，而是考了六百次都落榜的我是个废物这事反而还有救」

阿尔德巴兰的『领域』优势在于，凭借无限次尝试能死磕到那一丁点儿胜机出现，持续翻动手牌才是最大优势。

然而，虽然莱因哈鲁特是如此，但世界上偶尔会存在能持续引出正确答案的存在。所谓正确答案，虽因个人能力与胜利目标各异，但共通点是与阿尔德巴兰不同——他们被命运所爱。

──阿尔德巴兰被命运所厌恶。

究竟是阿尔德巴兰先厌恶命运，还是命运先厌恶阿尔德巴兰，如今已无从知晓，唯独这点是无可动摇的事实。无论被其他什么所爱、被什么所憎，命运都是阿尔德巴兰绝对的敌人。

所以必须杀死它。──哪怕与世界为敌，也要弑杀命运给你看。

正因不愿如此，命运才将自己宠爱的存在接连派来充当刺客。此刻站在这里的爱蜜莉娅与雷姆便是如此。

「──。真是因果报应」

选择雷姆作为突袭阿尔德巴兰的人选，究竟是谁的主意？

无论提议者是谁，从制造阿尔德巴兰破绽的角度而言都是最合适的人选。当她身为『暴食』权能的受害者时，受其影响的阿尔德巴兰未能察觉雷姆存在的异常，反而与她建立了正当的关系。

因此，当阿尔德巴兰第一眼看到从『暴食』枷锁中解放的雷姆时，那记『记忆』的闪光震撼弹令他体内产生了比他人更巨大的空洞。

──因为他邂逅了本不该在此、原本应当死去的存在。

「────」

至于这是通过何种方法达成的结果，根本无需争论。

毫无疑问，他做到了。菜月・昴反抗了命运，战胜了命运。菜月・昴拥有这样的力量。雷姆的存在就是证明。

但是，可是，即便如此──普莉希拉・跋利耶尔却没有获救。

「──既然你要这么做，老子也绝不会手下留情」

流过的泪水也好，伤害自己的拳头也罢，试图靠近的关怀亦然，全都毫无意义。

渴求的既非眼泪，亦非伤痕，更不是安慰。仅仅是一个人的性命而已。

「──」

头盔深处传来血腥味，阿尔德巴兰咬紧牙关猛然转身。石翼变形维持着不自然的飞行轨迹却保持平衡，与空中的爱蜜莉娅对峙。

虽然爱蜜莉娅与美丽的冰翼极为相配，但无论她像天使般多么可爱，扑扇人造翅膀也无法获得速度和高度。初速全靠雷姆击打冰盘的反作用力提供冲劲，随后的加速则依靠另一种方法──，

「呀！嗒！嘿！」

虽是早已听惯的泄气吆喝声，但每次喊出都会提升她的速度与高度。她不断在空中制造出作为踏脚石的冰柱，通过蹬踹这些冰柱持续获得加速度和冲力。

「简直蠢透了……」

这是唯有兼具非凡魔法天赋与庞大玛娜之人才能实现的暴力破解法。

虽然阿尔德巴兰凭借与『阿尔德巴兰』的契约能借用『神龙』这个外接玛娜槽的力量，但即便被要求效仿也绝对做不到。──因为天赋的差距可以用无限试错来弥补，唯独身体能力的鸿沟无法逾越。

溪谷绵长辽阔，夹击飞行二人的岩壁仍无止境。当阿尔德巴兰因无法甩开追兵而咬牙切齿时，猛然强力起跳的爱蜜莉娅已调整至相同高度──，

「──阿尔！求求你听我说！我会好好听的！」

「说得轻巧。明明二话不说就下狠手想把我冻成冰棍。要真掉到最底下，你是打算连整条河一起冻住交差吧」

「可是！那个计划已经失败了！」

「太天真也是问题啊，王选候补！」

为避开坠落地底变成冰雕的路线，他选择用石翼脱身。结果虽甩下了八重却未能摆脱追击。即便如此，成功分离爱蜜莉娅和雷姆、避免同时应对两人，或许该算成果。

而这个答案──

「现在就告诉你。──老子的态度和当初在王都没两样！」

咆哮声中，他扬起的手掌迸发岩弹，在爱蜜莉娅面前展开飞石弹幕。

猝不及防迎来宛如真实射击游戏场景的爱蜜莉娅，在瞪视飞石弹幕后突然绷紧面容，

「就算是我，也要说多少遍都行。再也不想为谁消失到无可奈何这种事哭泣了!!」

爱蜜莉娅如此高声宣言，冰翼闪耀光芒，破碎的冰晶与冻结大气的哀鸣，在飞石弹幕密布的阿古扎德峡谷中高高回荡。

３

──对于自己作为『尾随星』的存在意义，阿尔德巴兰从未过多烦恼。

虽说每个人在青春期都难免会思考自己为何诞生、生命从何而来又去向何方、对父母产生无端叛逆之类的命题，但这些对阿尔德巴兰而言都颇为遥远。

毕竟对阿尔德巴兰来说，连该叛逆的父母对象都难以设定，加之权能特性使他根本无法体会生命消逝的真实感。关于为何诞生已有明确答案，而为何被创造的问题，他倒觉得或许能用『爱』来回答。

因此，阿尔德巴兰从未有机会直面青春期应有的命题。

「这样啊，看来不能指望你有青春期般的情感和冲动了。这有点遗憾呢。我本来还设想过你会以什么形式迎来叛逆期，准备了好多应对方案」

这是『魔女』对阿尔德巴兰——这个成长过程顺风顺水完全不用人操心的孩子——发出的叹息。虽不认为他缺乏情感，却时常说出些没心没肺的评论。

渴望知晓多数乃至全部事物的『魔女』恶习，实在是棘手的存在，但也有无可奈何的一面。毕竟无法遏制这种欲望正是『魔女』的天性。

阿尔德巴兰也认识其他『魔女』，但无论哪位『魔女』，虽程度各异，唯独在无法违背本性这点上都带着亵渎般的扭曲。

不过话说回来，为了取悦『魔女』而刻意表演青春期也挺奇怪的。——某种意义上，这种逆反心理说不定反倒算得上青春期特有的情感呢。

「果然连父母都不是的我，只靠表面模仿为人父母的体验还是太投机取巧了……要是造出碧翠丝的话，那边说不定能体验到呢」

对着如此自言自语的『魔女』，阿尔德巴兰所感受到的寂寥，想必是与青春期无关的、更为别样的某种情绪。只不过，那究竟是什么，很难将其具象化地寻求出来，况且要这么做的话彼此的关系就太复杂了。

因此，阿尔德巴兰与『魔女』的关系──

「──老师」

这般呼唤后，正沉醉于探索思维迷宫的『魔女』抬起了脸。

每当看见那双映出阿尔德巴兰身影的黑瞳，以及随着「怎么了嘛」的歪头动作从纤细肩头滑落的雪白发丝时，都不禁让人觉得这『魔女』真是狡猾。

明明总是沉迷于自己的事，对欲望坦诚到极点，压根不会考虑他人心情，可每当阿尔德巴兰呼唤时，必定会与之四目相对。

面对这样的『魔女』，产生不了青春期应有的反抗心也是理所当然。

说到底动机就很薄弱，『魔女』以权能性能实验为名被施加了超过百万次『死亡』，内心早就崩溃了。不过就算再怎么控诉这点，关键的记忆也只留在阿尔德巴兰那里，对毫无实感的『魔女』来说不过是对牛弹琴罢了。

但是，我也明白『魔女』为何要如此彻底地做到让人连反抗之心都涌不出来的地步。

毕竟这段时间里，幸存的『魔女』除了眼前的她之外，就只剩一人成了其他『魔女』们直接或间接的死因。阿尔德巴兰与『魔女』们──大罪魔女们的交集，也不过是在这座梦境之城中，由『魔女』亲手收集的她们灵魂短暂对话的幻象罢了。

而后，受『魔女』教诲的阿尔德巴兰，将她们中的这样一个人──

「──不得不请你们杀掉」

这正是身为『尾随星』的阿尔德巴兰，尚未迎来青春期便被赋予的存在意义，纵使死上百万次也必须达成的人生指标。

为了将阿尔德巴兰变成这样，『魔女』遭到其他『魔女』们的谴责，并与同伴们诀别，可见其觉悟已臻极致。

「──谁都无法战胜我创造的你」

这句话对阿尔德巴兰而言既是骄傲，也是存在的依据。

老实说，虽然觉得『魔女』的性格糟糕透顶，对她的管教方式和方针制定也有诸多不满，但从未犹豫过要回应『魔女』的期待。

他深信自己能够做到。

那时的阿尔德巴兰还拥有左臂，即便知晓『死亡』，却未曾体会过真正的败北，所以才能如此坚信。

虽然不曾有过青春期──但那毫无疑问是无法抹去的愚蠢黑历史。

４

「咿呀──」

面对迎面冲入碎石弹幕的爱蜜莉娅，阿尔德巴兰强压下内心的犹豫，毫不留情地倾泻出全部火力。

正如在王都冲突时那样，阿尔德巴兰本能地对爱蜜莉娅处于劣势。

这已然是生命根源性的弱点，正因如此，即便在王都也无法对其他对手采取那般决绝手段。

当时借助『阿尔德巴兰』之力落下巨岩，以守护王都为代价阻止了爱蜜莉娅的追击，但此处并无可供牵连之物。

选择此地为战场，亦是基于上次教训的考量。

「我可没闲情到能为你成长高兴的地步！」

遗憾的是，阿尔德巴兰的心胸还没宽广到会为敌人成长欣喜。虽对将爱蜜莉娅定义为敌有过刹那抗拒，但他紧紧闭上了眼睛。

若论觉悟，早在遇见普莉希拉之前就已下定。严格来说，阿尔德巴兰的觉悟对象并非眼前爱蜜莉娅——

「就算是二手觉悟，对付纸老虎也够用了」

「知道是纸老虎就给我认真准备啊！」

面对高举着自知是纸老虎觉悟的阿尔德巴兰，爱蜜莉娅的果决丝毫未减。

爱蜜莉娅傲然闪耀着冰翼，她在周身生成超过百根的冰桩，正面对抗阿尔德巴兰制造的岩片风暴并将其抵消。对于仍未消散的风暴，她毅然亲身冲入其中，选择用双剑劈开飞石的正面较量。

「就算是资深魔法使，同时发动多个魔法也该很吃力才对……！」

即使是同属性魔法，也如同右手持笔写文章、左手同时绘画般困难——这是她从『魔女』处学到的常识。若涉及不同属性，据说需要为此专门扩容大脑。

按此理论，同时操控冰翼×冰柱×冰桩×双剑这四种魔法，相当于让四肢各自执行不同动作的杂技。更何况她还施展着蹬踏空中冰柱这种违反常理的追踪术，展现出超越奥运选手的运动能力，今日阿尔德巴兰的震惊额度早已售罄──

「为什么你还能用这么淡定的状态迎接我啊！」

飞砾的弹幕，爱蜜莉娅企图用勇气和腕力突破。但，姑且不论无法挫败的勇气，阻止腕力的手段还是有的。──砂砾的包围网。

「────」

瞠目结舌的爱蜜莉娅，被阿尔德巴兰制造的极微小砂粒风暴从正面包围。双剑和冰桩都无法完全防御的这招，不仅遮蔽了爱蜜莉娅的视野──，

「──呜、好重!?」

试图甩开缠绕的砂粒而挥动手臂的爱蜜莉娅发出惊呼。

接触她四肢与白色服装的砂粒，通过与周围砂粒结合形成重量与硬度阻碍行动。曾在砂海对莱因哈鲁特使用过的减益攻击──超音速移动的莱因哈鲁特靠冲力挣脱了，但这种方法对爱蜜莉娅也行不通。

此外砂粒侵蚀冰翼，剥夺了承受风力的翅膀性能。失去平衡的爱蜜莉娅本该笔直坠向地面──却未坠落。她舍弃被砂粒吞噬的冰翼，从天使变回天使般的美少女，因而逃过一劫。

但是──，

「──你净化了吧！」

让她舍弃翅膀才是阿尔德巴兰的真正目的。

即便姿态笨拙，凭借石翼悬挂滑翔的阿尔德巴兰时速仍超百公里。要追上他必须依赖翅膀，但阿尔德巴兰根本不给爱蜜莉娅重新展开冰翼的机会。

霎时间，伴随轰鸣声从岩壁突刺而出的，是自侧面抓向峡谷中飞行的爱蜜莉娅的石质巨臂。而且绝非区区一两根──以岩壁为素材延伸出的岩石手臂，已然形成逼近数百之众的大军。

「说是千手观音致敬……不如讲更像鬼屋后台的机关呢」

这与鬼屋经典桥段──从纸窗突然伸出无数手臂的场景颇为相似。但不同于那些吓唬人的把戏，这些巨臂是动真格要擒获爱蜜莉娅。

只要被抓住一条腿就性命攸关，正是决定阿尔德巴兰能否逃脱的关键时刻──

「这种──「──看我突破!!」」

本欲说出的「局面能突破吗」被高涨的气势彻底盖过。

虽说不该指望靠努力就能解决困境，但偏偏能用努力创造奇迹正是爱蜜莉娅可怕的地方。

失去翅膀的爱蜜莉娅将那恐怖淋漓尽致地展现──她用手中的冰剑斩飞第一只巨臂的手指，随即以无害化的断指为踏台高高跃起。

势头并未消亡。虽因失去翅膀而坠落的高度，此刻也被大幅夺回。

但即便如此，巨臂虽不及千手之数，仍有上百只严阵以待──

「──士兵先生，请助我一臂之力！」

响应爱蜜莉娅的呼唤，那群有着可憎外表的冰之士兵再度登场。

曾在坠落的冰盘上大闹的冰兵们，此刻英勇地以扑向爱蜜莉娅的岩石巨臂为踏台迎战：有的用身体阻挡，有的击打改变轨道，有的摆着姿势被压垮粉碎，展现出多样化的奋战姿态。

共计七具菜月・昴的冰兵，不断阻止干扰爱蜜莉娅的岩臂，成为她移动的踏台，粉碎后反复重生，在最大限度维持七具上限的法则下，持续守护爱蜜莉娅免受数百只岩石魔掌侵袭，始终支援着她的战斗。

──曾经『魔女』说过，所谓魔法就是将思念与愿望具象化的产物。

虽然觉得那个『魔女』竟会说出如此浪漫的台词，但此刻阿尔德巴兰眼前所见——菜月・昴外形的冰兵正在协助爱蜜莉娅的景象，究竟又是何种愿望的具现化？

胃袋深处翻涌作呕。这并非比喻，而是真实不虚的生理反应。

阿尔德巴兰将这股翻腾的负面情感，尽数倾注到下一轮攻击中。

那便是──

「──天妇罗盖饭抱歉啦，王牌再现」

随着阿尔德巴兰的话语，爱蜜莉娅他们头顶──与阿古扎德峡谷等宽的巨型岩块正笔直坠落。

无处可逃的巨质量碾压——正是王都所设陷阱的复刻版。

５

他渴求的──不，需要的，是毕生仅此一次的胜利。

可以说阿尔德巴兰的人生，正是为这场胜利而存在的。

自诞生以来，阿尔德巴兰被赋予、灌注、获赐的一切，都是为了赢得胜利、为了抓住胜利、为了夺取胜利而准备的路标。

「──没有人能战胜我创造的你哦」

从『魔女』那里获得的这句话，是阿尔德巴兰人生的指南针。──所以当这份信仰被粉碎时，阿尔德巴兰确实死过一次吧。

若是论『死』，早已体验过无数次到懒得去数。但真正意义上的『死』，恐怕是在那一天那一刻品尝到的。

这是『魔女』的夙愿，为此甚至创造了阿尔德巴兰，准备了毕生仅此一次绝对不能失败的战斗。

即便如此──

「──在绝不能输的地方，你却输了」

望着在熟悉草原的白茶桌前品味红茶香气的『魔女』，阿尔德巴兰被绝望击垮，终于意识到自己犯下了何等深重的罪孽。

仅用黑白两色就能展现出的美貌巅峰——堪称『魔女』的存在，那副美到令人憎恨的躯体上毫无伤痕的模样，正是此处乃梦境世界的证明。

因为真正的『魔女』早已为庇护本该赢得战斗却败北的阿尔德巴兰，失去了全部手脚，沦为只能等待死亡的凄惨模样。

那血液的温热、腥臭、粘稠感，绝不可能是虚假的。

既然如此，当这一切全部消失，用虚构覆盖应有现实的这个世界，反倒是由显而易见的谎言堆砌而成的存在。

「虚构这种说法我不太喜欢呢。虽然知道严格来说并非如此，但总会想起讨厌的家伙」

不知这是『魔女』特有的玩笑，还是她真心想说不合时宜的话，直到最后阿尔德巴兰都没能理解『魔女』的真实想法。

只是觉得自己被憎恨着。或者说是令她失望，被彻底放弃了吧。

然而——

「手臂看来是没法复原了呢」

『魔女』视线所及之处，是从上臂开始就被阴影吞噬的阿尔德巴兰的左臂。

痛楚，不存在。这也再次证明此处是『魔女』的梦境之城──若回归现实，想必会有超乎想象的剧痛灼烧大脑吧。而且那是无法通过『死亡』抹消的、永不消失的真实痛觉。

「失去一条手臂，在绝不能输的战斗中败北。看来我的计划似乎要以失败告终了。已经能想象朋友们七嘴八舌的样子了。──到头来，还是要托付给那些试图继承弗琉盖尔遗志的家伙们。真不甘心啊」

对于自己的败北将夺走『魔女』的一切这件事，感到无比悲哀。

不寻求任何人理解，甚至远离同为同胞的『魔女』们和旅途伙伴，即便如此也要实现的愿望，却被阿尔德巴兰彻底破坏了。

即便如此，阿尔德巴兰那空洞的灵魂里，败北前的热情仍未复苏。

在绝不能输的战斗中败北，阿尔德巴兰的心彻底折断了。

人生中唯一不容许失败的初战，将阿尔德巴兰的心碾得粉碎。

那便是通过见证最为亲近的存在——『魔女』不可避免的死亡，从而在真正意义上给予阿尔德巴兰无法东山再起的致命伤吧。

「──谁都无法战胜我创造的你」

所以，当这句话被再度说出口时，阿尔德巴兰未能理解其含义。

「事到如今已顾不上体面。变更胜利条件吧。把她交给那边处理……我们，去阻止二次灾害」

『魔女』既聪慧又自私。

她抛下因自责而无法正常思考的阿尔德巴兰，自顾自推进话题。变更胜利条件与提出新目标──但阿尔德巴兰根本不认为这些能实现。毕竟，他已经失败了。

即便如此──

「──谁都无法战胜我创造的你」

阿尔德巴兰不明白究竟是什么让『魔女』说出这种话。

『魔女』没有对茫然呆立的阿尔德巴兰多作解释，她缓缓起身走近，从正面笔直地凝视着他。

毕生所见次数最多、注视最久的『魔女』脸庞──此刻浮现出从未见过的表情。

「──是星星的错」

我明白那不是阿尔德巴兰的错，她表达的是这个意思。

未及理清涌上心头的感情，梦境之城便突兀地迎来终结。

如同粗暴撕碎连环画舞台般的收场方式，其后显露的是惨烈的现实。瞬间，疼痛与丧失感支配大脑，噪音与鲜血侵蚀理智。天地浸染成浓墨般的漆黑，连时间感都已模糊，阿尔德巴兰的恸哭被逐渐崩坏的世界悲鸣所淹没，甚至无法传达到自己耳中。

然而，在这片天翻地覆的世界里，在连自己声音都听不见的喧嚣中，那道嘶哑微弱、气若游丝的声响却清晰地传了过来。

不愿错过的『魔女』，最后的咏唱──

「──奥尔・纱幕」

×　×　×

──当阿尔德巴兰再度恢复意识时，一切早已结束。

这哪里是结束，分明是又一次开始，开始后又结束，结束后再开始。在如此反复无数次后，世界已不留丝毫『魔女』的痕迹。

「──你从哪来的？是什么东西？」

对着茫然呆立的阿尔德巴兰发出质问的，是个素未谋面的陌生人。

那个与衣衫褴褛的阿尔德巴兰不相上下的男人，正用混杂着恐惧与戒备的眼神盯着他。

语言能听懂。虽缺乏人际交往经验，但从某种意义上说这反而不成问题。

重要的是这里何处，此刻何时。

「基努海夫……剑奴孤岛啊。『魔女』？那都是几百年前的事了吧？」

听到对方提出如此怪异的问题，阿尔德巴兰长吁一口气。见状，男人表情从困惑骤变为惊骇。

因那声叹息突然化作呜咽，瘫坐在地的阿尔德巴兰已是泪如雨下。

『──谁都不可能赢过我创造的你』

数百年前被遗弃的『魔女』话语，在灵魂深处挥之不去。

因为将那个人变成说谎者的罪孽，阿尔德巴兰曾渴望死亡。

却未能死去。

６

「──做个了断吧！竟能活着走出『斯帕鲁卡』！从此刻起，你这混蛋也是剑奴孤岛的剑奴之一！欢迎啊，废物！」

这粗暴的欢迎与赞美之声，与辱骂几乎别无二致。

随着这番欢迎，粗野低俗的欢呼声席卷会场，阿尔德巴兰如同倚靠巨大尸体般跪倒在地。

他无力倚靠的，是被长剑深深刺入粗壮脖颈而断气的魔兽基尔提拉乌的尸骸。基尔提拉乌失去右前足与后腿，脸上凝固着比痛苦更甚的混乱与困惑的表情。

望着那可悲的遗容，肩膀随急促呼吸起伏的阿尔德巴兰感到沉痛。──虽然立刻意识到这份同情虚伪得令人作呕。

「居然活下来了啊。真让人吃惊」

用复杂神情迎接伤痕累累的阿尔德巴兰的，是剑奴孤岛上的一名剑奴，也是在岛屿边缘发现苏醒的阿尔德巴兰的男人。

他那复杂的表情，恐怕是对阿尔德巴兰熬过了新人试炼『斯帕鲁卡』的不满表现。作为不幸被指派照顾首个发现者阿尔德巴兰的他来说，要是阿尔德巴兰死在这次『斯帕鲁卡』中反倒省事了。

无论如何，阿尔德巴兰的存活令男人震惊，但吃惊的不止他一个。

阿尔德巴兰自己也难以掩饰对生还的惊讶。

──在这场绝不能输的战斗中败北后，阿尔德巴兰被抛入了未知的环境。

陌生的环境、陌生的人群、充斥着未说明规则的那里，对阿尔德巴兰而言正是未开垦的处女地，宛如被扔进了新世界。

唯一能确定的是，自己恐怕已失去存在价值，甚至连为这份价值丧失而哀叹的对象都已不复存在。

所以──

「明明说什么想死，结果不过是嘴上逞强罢了」

混杂着讥讽与挖苦的男人话语，将阿尔德巴兰的心撕得粉碎。

当理解到自己是被『魔女』之手所救时，阿尔德巴兰被无尽的失落感与自责吞噬，发自内心地渴望死亡。所以当被以成为剑奴的测试为名，扔进赌上性命的『斯帕鲁卡』时，他反而觉得正中下怀。

事实上，当阿尔德巴兰与其他四名同病相怜的新人被带进斗技场，直面基尔提拉乌时，他本打算毫不抵抗地赴死。

可是即便如此，阿尔德巴兰还是活了下来。

在其余男人或挑战、或逃跑、或求饶却接连被杀的过程中，作为最后幸存者的阿尔德巴兰本该被魔兽利爪贯穿，遭践踏折断肋骨，吐着血沫迎来死亡。

然而──

『──谁都不可能战胜我创造的你啊』

当这句话掠过脑海的瞬间，阿尔德巴兰已然展开了『领域』。

与那需要数亿次挑战仍无法战胜的对手相比，能在三百零四次就反杀的『斯帕鲁卡』对阿尔德巴兰而言并非痛苦。

真正的痛苦在于之后——活下来后的自问自答。──为什么、怎么回事、出于什么意图，自己竟没有死。

在得不出答案的情况下，阿尔德巴兰成为了剑奴孤岛上生存的剑奴之一。

「嗯？想知道外面的事？就算你这么说，俺来这儿也很久了……」

作为被认可的剑奴，获得在这座岛上生存资格的阿尔德巴兰开始追求知识。结果沦为阿尔德巴兰纠缠不休问答牺牲品的，是负责照料的剑奴。

「不要近期局势而是想了解历史？真少见啊。不过俺也不太清楚咧？嘛，『魔女』……『嫉妒魔女』的话倒是知道」

原本不抱希望试探的『魔女』情报竟被剑奴知晓已令人吃惊，而对方战战兢兢道出的『魔女』传说——竟专指『嫉妒魔女』这一事实，带来了更大的震撼。

险些毁灭世界、被『三英杰』封印的『嫉妒魔女』。

其他『魔女』的传说在此世并不存在，关于『大罪魔女』们的记录也遍寻无获。当听闻这一切都发生在近四百年前时，阿尔德巴兰陷入了绝望。

四百年的岁月，不仅抹去了『大罪魔女』们在世界上的痕迹，难道连那个不惜抛弃一切也要履行誓约的『魔女』的存在都会被遗忘吗。

但更残酷的是──

「──其他『魔女』？啥玩意儿啊。该不会是你的妄想吧？」

面对男人的质疑，阿尔德巴兰无言以对。

绝不可能是妄想。确实，与『魔女』共度的日子深深刻在阿尔德巴兰记忆中，她的教诲、触碰的指尖、诉说的话语，全都记得一清二楚。

这个世界上确实存在过另一位试图对抗拥有恐怖力量的『魔女』的『魔女』。──而阿尔德巴兰正是她的弟子，也是『魔女』最后的王牌。

「操！搞什么鬼！老子只是回答了问题，突然就他妈动手打人！」

被否定『魔女』存在而暴怒的阿尔德巴兰殴打的男子唾骂道。

在这环境──不，被抛到这个新世界后，与最初恩人的诀别竟是这般模样。随后与其他剑奴们也屡屡类似决裂，阿尔德巴兰逐渐孤立。

──多次听闻自己被传为『魔女』蛊惑的异类。

某种意义上，这评价没错。也无心纠正。但被和魔女教那帮莫名其妙的家伙相提并论实在火大。

据说那群人打着让『魔女』复活的旗号，专干些近乎恐怖活动的勾当。每次听到这种类比就大闹特闹，风评愈发恶劣。

「……像你这种魔女疯子，绝对不得好死」

这句话，是在剑奴孤岛时任总督安排的死斗中，被阿尔德巴兰蛮刀斩杀的首位恩人临终的诅咒。──他如此确信着。

阿尔德巴兰将那些称他为魔女狂的人，在死斗中杀了个精光。

但这并非为了泄愤。也不想洗刷『魔女』的污名。说到底，『魔女』们的末路连污名都谈不上，连存在的痕迹都被彻底抹消了。

所以，阿尔德巴兰没有向『魔女』寻求自己继续活下去的理由。──他只是想知道，自己究竟为何被允许存活。

为了知晓这个答案，他绝不能死。

最初从『斯帕鲁卡』手中幸存，之后又不断在死斗中活下来，都是为了这个。

所以每次展开『领域』与人刀剑相向时，都要吞噬数百次死亡，践踏所有剑奴的性命，活下去。活下去。持续活下去。

然后──，

「──居然能活下来。连比你强的对手都能战胜的你这般厄运，我甘拜下风」

没错，面对阿尔德巴兰捡起微小胜机斩杀强敌的胜利，总督道出了不知该算愕然还是钦佩的称赞。

阿尔德巴兰折断蛮刀随手一扔，背向欢呼稀落的斗技场。

──在剑奴孤岛醒来后的十年，转眼间就过去了。

７

「──抱歉啦要用天丼这招，王牌再来一次」

话音刚落，头顶便有超质量的岩块笔直坠落。

面对阿尔德巴兰那套甘愿被嘲为老把戏的策略，爱蜜莉娅一边闪避从岩壁伸出的石质巨臂，表情骤然变化。

「────」

先是因巨岩的出现而瞠目，紧接着王都时被阿尔德巴兰巧妙逃脱的悔恨浮现在眼角眉梢，此刻她又紧紧闭眼抗拒着那份挫败感，睁开眼将岩块纳入视野时「能做到吗……」闪过一丝怯懦，随即像在说「只能上了！」般振作精神，用比怯懦前更坚定的目光直视前方。──这番百变表情不过瞬息之间，心态调整之快实在令人称奇。

「但光靠气势可搞不定啊」

巨岩擦过溪谷岩壁，边剥落边下坠。

重整旗鼓的爱蜜莉娅首先尝试的方法，是在巨岩的坠落轨道上制造巨大的冰盖，以此承受巨岩的重量。──然而阿尔德巴兰却用魔法生成的岩炮弹施展岩弹炮，直接击穿溪谷岩壁进行干扰。

随着岩壁被击碎，无法严丝合缝覆盖整个溪谷的冰盖，最终只能随着巨岩一同坠落沦为追加攻击。

「既然如此──！」

眼看用冰盖接住岩石的方案失败，爱蜜莉娅立刻采取次手段。

她重新展开先前解除的冰之翼，在天使再临姿态下屈起修长双腿。随后将鞋底抵住后方冰之士兵们的踢腿──借助这份原版菜月・昴绝对无法企及的腿力，一口气腾空而起。

「────」

爱蜜莉娅猛然加速的态势出乎意料，从岩壁伸出的数百条手臂纷纷抓空，放任天使逃亡──不，放任其向阿尔德巴兰发起冲锋。

由于将意识和行动分给了迎击，逃跑的阿尔德巴兰速度与势头都减缓了，与一口气逼近的爱蜜莉娅之间的距离正急速缩短。

为拖延时间留下的八重，因她创造的巨大优势被彻底瓦解，传来了「阿尔大人真是的～一点都不值得人家支援呢～」这般带刺的话语。

「要是现在被抓到确实是这样啦！」

阿尔德巴兰对着幻听中的八重如此回嘴，同时用飞石弹幕迎击爱蜜莉娅。然而面对继巨岩坠落后的二次攻击，爱蜜莉娅在空中以神圣姿态扭转身体避开了。

「真的假的!?」

阿尔德巴兰瞪大眼睛——那对理应无法自由活动的人造翅膀竟完成了这般动作。

当然，冰造的天使之翼并未拍动。爱蜜莉娅此刻三维轨迹的真面目，是在巨大冰翼内侧追加的小型冰翼——通过重叠多层冰翼改变风的流向，并利用身体倾斜来发挥翼缘调节功能。

这种空气动力学的应对方式，也绝对是靠天生的直觉完成的。

「要追上你了──！」

即便为回避而横向翻滚，爱蜜莉娅也几乎不减速。

与呼喊着的她之间的距离正在消失。若保持这个速度，从坠落的巨岩波及范围内逃脱对爱蜜莉娅来说应该来得及。本以为必杀的一击却被从容避开，阿尔德巴兰可谓千钧一发──这本应是两位当事人共同的认知瞬间。

「──」

爱蜜莉娅的绀紫色瞳孔猛然睁大，那双大眼睛染上了惊愕的神色。

在她的视野中，阿尔德巴兰并未采取任何特殊行动。虽然持续发射着无法命中的飞石连击，但既没有展开新的魔法，也没有出现躲避她的超机动动作。

即使借助冰兵之力加速飞行的爱蜜莉娅也不例外，照这样下去就会被飞扑而来的她追上，再也躲不开那冻彻骨髓的指尖。

那即是说，爱蜜莉娅已满足此处的胜利条件。──尽管如此，爱蜜莉娅的眼瞳中却不见欢喜或了然的神色。

因为──、

「──我应该说过吧，要天妇罗盖饭」

以阻挡坠落巨岩及其可能造成的重大破坏为代价，阿尔德巴兰得以在与爱蜜莉娅的王都战斗中获胜并脱身。

因此，即便被说缺乏新意，他仍决定执行那个曾一度奏效的相同策略。

不过、这次被卷入的无辜民众在场一个都没有。──无辜的民众。

「──阿尔!!」

叫喊着的爱蜜莉娅的手，不顾一切地向阿尔德巴兰伸去。──朝着被落石威力卷入的、除爱蜜莉娅外唯一的存在。

８

『──谁都无法、战胜我创造的你哦』

十年的岁月漫长无情，将阿尔德巴兰的人性毫不留情地剥蚀殆尽。

本该闭眼就能清晰忆起的面容、声音、温暖，却被亲手了结之人的死相、临终惨叫、冰冷回溅的鲜血逐渐覆盖。

『──谁都无法战胜我创造的你哦』

正确。那句话是正确的。确实，没人能杀死阿尔德巴兰。

这十年来，我多次被驱赶到剑奴孤岛『斯帕鲁卡』，在死斗场上历经无数生死关头，杀尽了那些根本不可能战胜的高手与非人之物。

『──谁都无法战胜我创造的你哦』

过了十年，剑奴孤岛的成员早已和最初截然不同。

阿尔德巴兰早就是最资深的元老之一，知晓他被『魔女』迷惑的异常者传闻的人已经一个不剩。自从阿尔德巴兰明白『魔女』是禁忌话题、大多数人只知道传说的皮毛后，他也彻底不再提起『魔女』的事了。

但这并非出于得不到答案的失望或死心，而是某种更深刻的东西导致的转变。

『──谁都无法战胜我创造的你哦』

十年间，在遭人遗忘的剑奴孤岛被迫不断厮杀，这个只重复着生命交换的空间里支配阿尔德巴兰的，是巨大的绝望。——对『魔女』是否真实存在、其存在本身产生怀疑的绝望。

『──没有人能赢过我创造的你』

只要闭上眼睛，那声音确实能听见。我记得有人这样说过。

但是，可是，那真的，发生过吗。

『──没有人能赢过我创造的你』

『魔女』的容颜，想不起来了。

『魔女』的声音，想不起来了。

『魔女』的体温，想不起来了。

十年间反反复复回味的记忆像翻烂的书本般支离破碎，即使用胶带拼贴修补也无法阻止劣化，最终连记忆本身都化为尘埃。

就这样回忆化作尘埃，从指缝间簌簌掉落，再也无从知晓。

──『魔女』真的存在过吗？

──阿尔德巴兰的记忆，确实是发生过的事吗？

『──没有人能赢过我创造的你』

偶尔会没来由地想要毁掉名为自我的存在。

在这种时候，阿尔德巴兰会故意解除『领域』投身死斗，被拼死攻来的对手打得七零八落，试图窥视死亡的深渊。——不，他甚至会想，与其只是窥视，不如干脆坠下悬崖算了。

但偏偏在这种时候，『领域』总会以意想不到的方式拯救阿尔德巴兰。

『──没有人能战胜我创造的你』

仿佛为了证明那个是否真实存在都值得怀疑的『魔女』的话语，明明只差一步就能杀死阿尔德巴兰的对手，却屡次在他眼前精神崩溃。

每当看到对手翻着白眼丧失理智与战意时，阿尔德巴兰总能感觉到某种无形之物在试图延续自己的生命，于是怀着难以排遣的心情斩下了对方的头颅。

十年过去了，阿尔德巴兰依然不明白自己被延续生命的意义。

不仅如此，他甚至怀疑是否真的存在那个想要延续自己生命的东西。

『──没有人能战胜我创造的你』

只是，感到毛骨悚然。

构成自己的一切都是虚假的，『魔女』所花费的心思和话语实际上根本不存在，阿尔德巴兰或许真的是被『魔女』迷惑的异常者——这样的自问自答侵蚀着内心，无眠的日子持续了数年。

『──谁都无法战胜我创造的你』

那句对阿尔德巴兰而言曾是赖以生存的支柱、构成自我根基的话语，如今却显得如此可怕。

这一切或许都是妄想的产物，阿尔德巴兰背负的使命、理应存在的相遇与别离，全都不曾真实存在——这样的怀疑持续啃噬着他。

『──谁都无法战胜我创造的你』

永无止境的、自问自答的螺旋。

仿佛沉入充满无解负面绝望的沼泽，动弹不得的感觉。

这种唯独无法决定死法的时光，今后也将永远持续。——阿尔德巴兰停滞的日子，在某天突然迎来了转机。

那个转机是——

『──听着，散落剑奴孤岛的乌合之众们』

──通过传声管响彻全岛的，是少女那如火焰般炽烈凶猛的声音。

９

岛上剑奴们的集体暴动，以及以此为佯动的新皇帝暗杀计划。──降临在阿尔德巴兰身上的转机真相，似乎就是如此。

不过区区剑奴能获得的情报仅止于此，阿尔德巴兰也不想知道更多细节。总之看起来结局并未导致政权颠覆。

唯独在这件事中，十年未变的阿尔德巴兰产生了重大意识转变。──他救下了陷入危机的银发少女。

当然这与阿尔德巴兰原本的目的毫无关联。

银发少女只是个萍水相逢的犬人族，与阿尔德巴兰认识的那个银发人物毫无瓜葛。但成功拯救她这件事，以及骚乱中那个如火焰般唯我独行少女的声音，促使阿尔德巴兰下定决心。

──为了确认『魔女』真实存在，前往封闭世界的外侧。

『──谁都无法战胜我创造的你哦』

一次又一次被投放到湖中的水生魔兽杀死后，阿尔德巴兰终于逃离了囚禁自己十余年的岛屿，登上了不被水包围的陆地。──严格来说，由于整个世界都被大瀑布包围着，可以说根本不存在不被水包围的陆地，但他还能打起精神开这种玩笑。

『──谁都无法战胜我创造的你』

对阿尔德巴兰而言，这句话既是诅咒，也是慰藉；既是束缚，也是宽恕。

为了辨明那暧昧模糊、方向不明却又无比庞大的情感源头的色彩、温度与不确定的确定性，阿尔德巴兰决定追寻『魔女』的踪迹。

时间所剩无几。在封闭岛屿度过十余年的过程中，阿尔德巴兰所行走的世界正逐渐接近他记忆中的模样。

剩下的，只需验证阿尔德巴兰心中的回忆是否真实。

而验证此事所需的是，确证『魔女』的存在──

「──为何《福音书》中没有记载您的存在呢？」

这么说着，阿尔德巴兰对那个故意夸张歪头的魔女教大罪司教，明明清楚指出问题的粗略理由，却用手指拨弄漆黑铁盔——从剑奴孤岛逃脱时获赠的饯别礼上的金属扣，含糊其辞地回应。

决定追寻『魔女』踪迹的阿尔德巴兰，在寻求线索过程中试图接触的对象，正是在岛上屡屡听闻的邪教集团——魔女教。

不过，虽说是费尽周折找到的对象，谈判却始终难以顺利进行。

「──你，是『怠惰』对吧？」

老实说，与这位大罪司教的战斗，堪称阿尔德巴兰人生中最棘手的恶战之一。

原本就罕有不死就能取胜的先例，即便如此仍是个难以捕捉胜机的强敌。最终虽达成了胜利条件，却算不得真正取胜。

想来其凶恶程度，比起那些同样虚实难辨的『大罪魔女』们──与『魔女』相比也毫不逊色。

总之──

『快住口的斯！　大不敬的斯！　莎缇拉！　除了莎缇拉！　其他什么『魔女』的故事！　简直是大逆不道的斯！　这世上唯一有资格再临的、只有赐予我宠爱的她而已的斯！！』

这位言行脱轨、丧失理智的大罪司教，话语中究竟有几分可信度尚不得而知。但那段激烈告白，纵使对旁人毫无意义，对阿尔德巴兰却非如此。

──正是这番既信奉『嫉妒魔女』，却又承认其他『魔女』存在的发言。

『──谁都无法、战胜我创造的你哦』

阿尔德巴兰耐心地反复与大罪司教相遇，引出话语，进行必要交流，刺激对方后献出性命，再从最初开始──如此周而复始，终于从大罪司教身上获取了所需情报。

而后，他飒爽地掠过疾驰而来的大罪司教，将这场邂逅化为乌有。

「啊啊！啊──！呜呼！怠惰怠惰怠惰怠惰怠惰──啊!!」

魔女教的包围网中逃脱、消失无踪的阿尔德巴兰的存在，想到让错失猎物的大罪司教吐血般尖叫的画面，但已经不在意了。

此时的阿尔德巴兰心中只有一个愿望──确认『魔女』的真实存在。

『大罪魔女』们，她们的殒命方式我都知晓。

『愤怒魔女』中陷阱受辱而死，『色欲魔女』在大火中焚尽，『暴食魔女』于沙海枯竭而亡，『傲慢魔女』沉入大水深处，『怠惰魔女』屠龙后坠入大瀑布。

而『嫉妒魔女』被封印在世界尽头，最后的『魔女』则是──

「──原来如此。能从墓地以外进入这个地方，算是结构缺陷呢。『圣域』的机制也是，收尾太草率了。虽然也有无可奈何的部分」

在广阔到望不见边际、非现实般的青空下存在的草原。凉风吹拂的小高丘上，摆放着白色桌椅与遮阳伞。

那毫无疑问是存在于阿尔德巴兰记忆中、逐渐淡薄消逝的光景。

立于景象中央的，是仅用黑白两色便能勾勒出的美丽存在──

「──爱意为何会消退呢」

历经曲折终于抵达的梦幻之城。

阿尔德巴兰甚至开始怀疑自己的神志，几乎要相信这可能是幻影。

面对与这名学生时隔十余年——对对方而言则是跨越四百年的重逢，真实存在的『魔女』──不，『强欲魔女』浮现出没有血色的微笑，献上祝词。

献上了祝词。

10

对阿尔德巴兰来说，失去单臂后的人生反而更为漫长。

因此平时几乎不觉得这是障碍，但偶尔还是会感到不便。──比如现在抱着失去意识之人时。

「硌得慌可就饶了我吧」

如此抱怨的阿尔德巴兰双臂中──被血肉之躯与石制义肢横抱着的，是软绵绵失去意识的爱蜜莉娅。

绵长溪谷中，阿尔德巴兰与爱蜜莉娅的空中追逐战在此落下帷幕。

没什么大不了的。王牌和之前在王都让爱蜜莉娅逃脱时用的是同一招。

心地善良的爱蜜莉娅无法坐视任何人在战斗中牺牲。——她也是在帝国『大灾』中失去普莉希拉，心灵遭受重创的其中一人。

所以为了保护站在坠落巨岩直接攻击路线上的阿尔德巴兰，她毫不犹豫地挺身而出。

「虽说没有其他能确实命中的方法，但这战术连我自己都觉得够渣的」

当然，这也是阿尔德巴兰经过反复尝试其他对策后得出的结论。

虽然尝试过调整巨岩坠落轨道、击碎岩石制造岩崩、选择飞石弹幕路线及穿插其他魔法，但除了把自己当人质的犯规招式外，爱蜜莉娅总能凭借临场急智和直觉突破所有攻击，最终只能出此下策。

「这样既不会消除罪恶感，也不可能获得原谅就是了」

这番无人聆听的辩解，拙劣到恐怕连爱蜜莉娅都不会原谅吧。

为了保护阿尔德巴兰，毫无防备擦过巨岩质量的爱蜜莉娅遭到全身强烈冲击，终究失去了意识。乍看之下应该没有会留下后遗症的伤，顶多是较严重的脑震荡罢了。——为了让结果如此，我慎重地调整了力道。

「真是绕了好大一圈啊。……等八重汇合才是上策吧」

从高处坠落以及与爱蜜莉娅的逃亡剧结束后，终于有余裕确认周遭状况。由此得知此处很可能是世界最大峡谷——阿格札德峡谷的夹缝地带，与目标摩格阿雷德大喷口形成了巨大高低落差。

虽然已经突破露格尼卡王国国境进入卡拉拉基都市国家，但要攀爬坠落的数千米高度并返回原路线仍需耗费相当时间。

而且——

「奥塔暂且不论，罗伊和大叔能顺利会合吗……？」

被分散的同伙中，『阿尔德巴兰』的战斗力无需担忧，但罗伊・阿尔法德和亨克尔在实力与人品方面都令人极其不安。当然，罗伊的行动已被咒印束缚，出于惜命应该不会破坏规则。

「总之，指望他们在集合地点全员到齐才是最稳妥的」

阿尔德巴兰最优先事项是抵达摩格阿雷德大喷口并达成目标。

虽需借助『阿尔德巴兰』的力量完成目标，但最坏情况下也并非没有替代方案。此外，罗伊的『暴食』权能之力对计划引发的灾祸善后不可或缺。

因此，必须设法让他们在目标达成后汇合并听从指示。

「本想防止二次灾害，结果搞出三次四次灾害的话可就操蛋了」

一边这样抱怨着，阿尔德巴兰倾斜背后石制的翅膀，在保持速度的同时缓缓降向溪谷的地底、那条奔流大河的岸边，总算勉强成功着陆。——骗人的。其实抱着爱蜜莉娅自爆了六次，第七次才终于着陆成功。

「抱歉啊，爱蜜莉……娅」

为防止大河突然涨水导致水位上升发生溺水，阿尔德巴兰没有将爱蜜莉娅放在地底，而是安置在岩壁稍高处的凹陷处。

在留下她独自离开前的最后一句话时，他稍微犹豫该如何称呼。犹豫的结果，还是用阿尔德巴兰一贯的方式称呼了她。——除此之外，此刻的他缺乏勇气去使用那个能正确界定两人关系的称谓，毕竟现在的关系本就不正确。

「──呃」

刚咒骂完懦弱的自己，剧烈的头痛便席卷而来，阿尔德巴兰咬紧了牙关。

刚渡过难关稍有松懈，债务便立刻喷涌而出。他勉强抑制住状况，进行十秒深呼吸后咽下毒素——如此反复，让精神稳定下来。

但用这种方法虽然能让心灵喘息，身体──尤其是大脑却无法喘息。

现实中大脑已持续运转近一百小时。

一路上靠着『阿尔德巴兰』的治愈魔法勉强糊弄过来了，但除非让身心彻底关机一次，否则这种过载状态是不会缓解的吧。

虽说如此，还是告诉自己再坚持一下。

『──谁都无法战胜我创造的你呢』

「啊，没错，老师。──谁都无法、战胜我。是的。正是如此」

只要闭上眼睛，阿尔德巴兰的脑海中就会浮现那句话。

以此为支撑，阿尔德巴兰──，

『──快看啊，又来了』

『又是妾身的──』

『妾身的──』

「────」

断断续续地，传来听不真切的声音。

那究竟是谁说的、何时说出的话语、自己的灵魂会被灼烧到何种程度——正因为明白这一切，阿尔德巴兰堵住了心中的耳朵。

不要停下脚步。就这样决定了。已经决定了。

果然不该停下脚步啊，就这样决定了。

既然决定了──

11

──那是当阿尔德巴兰捂住心耳、好不容易爬出溪谷、重新赶往摩格阿雷德大喷口之后的事。

「什」

阿尔德巴兰的唇间漏出一丝紊乱的气息。

会下意识脱口而出也情有可原。毕竟那是从意识外侧飞来的意外事故，是大脑深处认定绝不可能发生的突发状况。──在阿尔德巴兰前进路线仅两米开外，一根巨大冰柱从天而降直插地面。

「────」

阿尔德巴兰咽下唾沫回头望去，瞬间理解到这极巨冰柱是来自被他遗弃在溪谷地底的爱蜜莉娅之手。

但以她所受的伤势。爱蜜莉娅的意识理应还需数小时才能恢复，换言之这记临死反扑竟是在无意识状态下发动的。

「离谱到家的执念……」

不过转念一想，若阿尔德巴兰早五秒攀上悬崖，此刻便已被冰柱碾成肉泥，某种意义上可说是避开了双重悲剧。

无论、直撃されていたとしても、アルデバランは権能でそれをやり直し、喰らわないという结果を引き寄せることになるが、エミリアのためにも、アルデバランの精神卫生的にも、彼女の手にかかる机会はないに越したことはない。

即便如此──、

「战斗中偶尔会发生这种事，真瘆人」

在剑奴孤岛『斯帕鲁卡』，即便在殊死搏斗中，身负致命伤的对手也会榨干最后的生命力发动可能同归于尽的一击。在阿尔德巴兰的经历里，甚至有被斩首后还能杀死他的家伙。

这是早已决定好的行动，即便意识或生命消逝，残留在四肢中的情感余烬也会试图将其完成。

如今爱蜜莉娅的最后一屁也是拼死想要阻止阿尔德巴兰的心意具现化之物──

「──等等」

为了称赞那股精神力，阿尔德巴兰屏住了呼吸。

眼前、以掠过阿尔德巴兰的形式耸立在大地的冰柱──那正是、简直像神话巨人会挥舞的巨大巨大冰之枪。但作为以狙杀阿尔德巴兰为目的的招式而言，怎么说都太夸张了。

这种、巨大的东西、简直像是──

「──锚」

没错，就在他轻声嘟哝的瞬间。──以爱蜜莉娅射出的冰枪为标记，正当阿尔德巴兰准备前往摩格阿雷德大喷口时，新的刺客被送了进来。

那是──

「──哟，头盔佬，一会儿不见就破破烂烂了嘛」

「……彼此彼此吧，你这张嘴倒是变毒了啊，菲尔托雷酱」

彼此跨越战场的第一个阶段，晋升至下一阶段的同伴。

菲鲁特・露格尼卡──不，以菲鲁特为首的混成军，正如他们投掷『记忆』闪光弹时那样，挡在了前方。

** 第四章 『领域的加害者』

１

「──我也是，和你一样不成器的女儿啊」

阿尔德巴兰永远无法忘记『魔女』说出这句话时那忧郁的表情。

我这样想着。──就连这样一位仿佛知晓世间一切真理的『魔女』，原来也会有感叹自己力不从心的时刻啊。

「当然会有啦。说白了，你的存在……你现在会在这里这件事本身，就是我能力不足的证明呢」

被这么一说，阿尔德巴兰的心情很复杂。

对阿尔德巴兰而言，这位『魔女』的存在感太强烈了，虽然不愿承认，但她确实很伟大。尽管能拿来比较的对象不多，但无论怎么比都会觉得她非同寻常。

这样的『魔女』说自己不成器，实在让人高兴不起来。

不过，若非这位『魔女』自我否定，如今与阿尔德巴兰的关系也无从谈起。倘若『魔女』不必承认自己的不完美──

「那时候，我和你也只不过待在各自本该在的地方罢了。虽然可以尽情想象未曾发生的未来，但很不巧你抽中了最坏的命运。说来惭愧，这对我倒是侥幸呢」

那种伪恶的说话方式里，似乎混杂着『魔女』特有的幽默和『魔女』特有的真心话，各占一半。实际情况就不得而知了。

毕竟，那个总爱装模作样说自己不懂人心的『魔女』的真实想法，就连相处已久的阿尔德巴兰也觉得暧昧不清、难以捉摸。

但是，如果『魔女』的说辞是正确的，那就太奇怪了。

要知道，按阿尔德巴兰的说法，现在的处境可是最糟糕的星象排列，但阿尔德巴兰却不觉得和『魔女』共度的日子有什么不幸。

确实，虽说要经历被美其名曰试炼的百万次死亡体验，就算拒绝也会被用不喜欢的名字称呼，实在算不上什么正常的幸福环境。

「居然能从和残次品『魔女』的生活里找到价值，你也真是个可怜的孩子」

这句低语既是自嘲，也带着明显的他嘲，相当复杂。

但阿尔德巴兰没有漏听其中掩饰不住的柔和余韵。

即便微不足道、容易混淆、难以理解的感情，『魔女』也确确实实拥有。寻找能证明这一点的痕迹，正是阿尔德巴兰的趣味。

实际上如何并不清楚。或许只是臆测或误解。

重要的是阿尔德巴兰如何感受，『魔女』的真意属于『魔女』。──而阿尔德巴兰认定的真相，只属于阿尔德巴兰。

「这种干脆利落的态度真是相似呢。果然影响这种东西不容小觑」

眯起黑瞳，用手指拨弄着白色前发，『魔女』如此说道。

这是越过阿尔德巴兰注视着某人，同时凝视着映在阿尔德巴兰瞳孔中的自己时，『魔女』低声吐露的感慨。

影响，当然存在吧。无论是出身，还是成长环境。

对阿尔德巴兰是，对『魔女』亦是。

不成器、不完美、不完整。──这对『魔女』而言是可耻的过去吗？

正因为存在这样的过去才有与『魔女』共度的日子，这样想算是诅咒吗？

若要说唯一能确定的事──，

「──阿尔德巴兰」

阿尔德巴兰的十年，与对方跨越四百年的已知情景中的重逢，在那里目睹的『魔女』──不，『强欲魔女』的姿态，否定了那日所说的不成器之时，阿尔德巴兰所品尝到的，是难以忍受的丧失感与绝望。

２

──咔嗒咔嗒地用手指拨弄着黑头盔的金具，阿尔德巴兰俯瞰着状况。

眼前，甚至令人感到神圣的巨大冰锚，以及以其为标志整齐列阵的一行人，正堂堂正正地与阿尔德巴兰对峙着。

相对的是菲鲁奥雷──不，以菲鲁特为中心的一群人，她们能在此齐聚的意义，阿尔德巴兰故意没有追问。

不问也明白。──罗伊和亨克尔，已经败北了。

虽然不认为连『阿尔德巴兰』都会输，但既然『龙』没有赶到现场，看来就连『阿尔德巴兰』也被用什么方法拖住了。

老实说，尽管有权能和不杀两条束缚，但能在击败『暴食』大罪司教的基础上，甚至对『神龙』也采取了对策，这超出了想象。

到底准备了什么计策，就算问了也不会得到回答吧──

×　×　×

──二百四十六。

「──再怎么说，魔女因子也下定太大决心了吧，佩特拉小妹妹」

「──！」

面对阿尔德巴兰正面的指摘，菲鲁特等人之间弥漫着紧张。

其中脸颊绷得最紧的，自然是被点名的佩特拉本人。在她们看来，佩特拉的权能应当是王牌兼最高机密。

事实上这个方针已与所有同伴充分共享。

但再铁石心肠的人，也无法对突如其来的试探毫无反应。

面对阿尔德巴兰的质问，众人虽竭力控制表情和情绪，可只要视线或意识稍有波动，那矛尖就会反复试探着追溯。最终顺着细微反应追溯到的尽头，阿尔德巴兰想要的答案正倔强地矗立着。──虽说万万没想到吸收魔女因子的竟是佩特拉。

「按我原先的预估，读过那东西的佩特拉小妹妹或梅莉小妹妹，根本不可能重返战线才对」

在普雷阿迪斯监视塔将菜月・昴和碧翠丝封印的阿尔德巴兰，击退了加菲尔和艾莎后，并未伤害佩特拉一行人而是放过了他们。

这不仅是因为没有排除的必要，更是预判了后续发展所采取的策略──为了无论如何都要拖住莱因哈鲁特，必须让『嫉妒魔女』显现。

作为触发这一关键点的棋子，阿尔德巴兰选中佩特拉等人来诵读菜月・昴的『死者之书』。事实上，阿尔德巴兰与莱因哈鲁特的战斗因『嫉妒魔女』的乱入而中断，成功排除了计划中最大的障碍。

然而──

「……光是读普通人的书都可能精神崩溃，那家伙居然扛住了菜月・昴的『死者之书』？」

虽有先例。──阿尔德巴兰心里其实再清楚不过，但正因如此才更确信无人能复刻，这就是『死亡』概念的绝对性。

在某些情况下，菜月・昴的『死者之书』堪称是能越级击杀的棘手咒物。能不被那东西摧毁心智的家伙，怎么可能随处可见。

「……不过，小看他人可是我的坏毛病啊」

无论阿尔德巴兰作何感想，佩特拉确实站在了这里。

她不仅未被阅读『死者之书』的冲击摧垮心智，甚至不惜让魔女因子寄宿己身来阻止阿尔德巴兰。或许正是阅读『死者之书』的经历，才让佩特拉决绝至此。

『──谁都无法战胜我创造的你』

掠过脑际的『魔女』话语本为激励阿尔德巴兰，绝非助长其傲慢令其失足。

若误解这点，阿尔德巴兰此番必将真正失去『魔女』。——彻底沦为『强欲魔女』，永远丧失那颗真实存在过的心。

「──说到底，命运还是不能交给别人啊」

将涌入心头的感伤用深呼吸压入心底，阿尔德巴兰迈步向前。

敌人强大、阻碍重重、没有同伴、无人可夸──即便如此，仍决定前行。

瞬间──

「──噢噢噢噢!!」

──燃烧着怒意的金虎刚拳，凶猛贯穿了阿尔德巴兰的头颅。

３

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓这辈子再也不参加庆典了。

△▼△▼△▼△

──总计六十一人。

这正是货真价实、与『暴食』罗伊・阿尔法德决战之后，为与阿尔的最终决战重整编制的『阿尔德巴兰团』──爱蜜莉娅阵营与菲鲁特阵营的全部战力。

佩特拉不禁对激战过后未经喘息就重组、还能保留如此多成员的团队心生感激与敬佩。但这绝非贬低那些未能跟上重组团队的同伴。

『毕竟奥托和梅莉也都经不起更多乱来了』

正如幻影菜月昴所言，奥托和梅莉──两人都在与『暴食』的战斗中成为关键，但被吞噬『记忆』的奥托自不必说，为阻止黑蛇而过度使用加护的梅莉消耗剧烈，必然要退出战线。

不止她们如此。在最后关头罗伊打出的王牌──被『暴食』权能反刍过去的痛楚，精神因此磨损至极限的人也一样。与身体创伤不同，即便有佩特拉的『压缩』，心灵磨损也难以轻易恢复。不过即便如此，梅莉仍坚持要通过『压缩』恢复时间重返战线──

「就算预支生命，昴也不会高兴的哦？」

被佩特拉这样说服后，她虽不情愿──真的非常不情愿──还是接受了退出战线的事实。

老实说，看到梅莉被搬出昴的名号就轻易被说服的态度，佩特拉的少女心路产生了微妙的抵触，但毕竟是自己干的，便没有多说什么。

而且她还有警戒『暴食』招来、战斗后失去踪影的黑蛇的任务。没能让她完全休养实在抱歉。

『只能让能干的人填补能干的空缺。不过话说回来，就算失忆了也会冲进修罗场的家伙也挺危险的』

「好厉害呢。就算失忆了奥托先生还是那样，忍不住这么想」

『天生的秉性……说不定是风险成瘾者或战争狂魔那种类型』

这种感慨若是被本人听见，不论有无记忆大概都会吐槽"能别说这么难听的话吗!?"，但会被这么想也是无可奈何。

总之『暴食』确实削弱了我们宝贵的战力，让决战可用的手牌变得拮据。加菲尔回归虽值得高兴，但无法为爱蜜莉娅和雷姆全力以赴，无论对佩特拉还是对『昴』都是痛心之事。

不过即便如此──

「──我们会赢的，昴」

『啊，去夺取胜利吧。为了不辜负至今所有的积累』

△▼△▼△▼△

──神明、佛祖、欧德・拉格纳大人。我发誓此生绝不与人诉说梦想。

△▼△▼△▼△

「──说到底，命运还是不能交给别人摆布啊」

内容虽显自暴自弃，语调却暗藏觉悟，随着阿尔这句话化为行动信号。

「──噢噢噢噢!!」

以咆哮的加菲尔为先锋，『阿尔德巴斯特团』猛然展开行动。

注视着他们的动向，佩特拉在自己胸前紧紧攥住双拳。

──以爱蜜莉娅射入的冰锚为标记，佩特拉带着『阿尔德巴斯特团』将现场距离『压缩』，再度挡在阿尔面前。

老实说，爱蜜莉娅和雷姆不在现场，阿尔意外带出的随从女忍也未见踪影，这终究令人不安，

『──阿尔那边，没有解除不杀约束的理由』

将此视为定心丸，多少是过分期待了对方的能力与信条。

但回想拥有『时间溯行』权能的阿尔至今的战绩，这便是依据。正因权能过于强大，某种意义上阿尔才能被容许这般轻视战术。

而且这个前提，即便在如今已将他与同伴分离的情况下，根本上仍未改变。

「嘎呜」

正面，毫无预备动作就冲过来的加菲尔发出痛苦呻吟。

原因在于他突进的轨迹与凭空出现的石板相撞。面部被预判先制攻击的埋伏石板击中，加菲尔的身体在空中翻转。阿尔擦过其正下方，同时迎击紧随金虎的战斗力。

接着是拉姆、菲菈姆＆格拉西丝三人。

『巧得很，粉发姐妹花登场！来啊，会怎样!?』

４

──三十七。

用石板迎击率先冲来的加菲尔，从他后空翻的身体下方穿过。

时机意外地苛刻。石板插入太早会被横扫，太晚则会让加菲尔直接通过。面部被击中的刹那，身体已记住并实践了这点。

「嘎呜」

听着后脑勺传来的呻吟声，面朝前方的阿尔德巴兰迎来三方袭来的黑影。

来自左右的菲菈姆及其姐妹，与稍斜上方的拉姆默契配合。双胞胎特有的协作精度，加上拉姆初见便能适应的异常性，构成令人瞩目的团队作战。

就在这时──，

「雷姆小妹在后头悬崖摔成肉饼咯」

「才没有。别小看拉姆和雷姆的姐妹情」

言语的毒性被姐妹间的共感消解，未能生效。

既然毫无动摇，说明拉姆所言非虚。从中解读出雷姆平安与八重下落不明的事实，反而让毒性作用在了我方。

然而──，

「──地土工艺」

利用从『龙』处流转而来的玛那，石质刀剑瞬间包围阿尔德巴兰。为躲避接连从大地突刺的剑锋枪尖，双胞胎大幅扭身闪避，产生片刻延迟，三者的配合转为拉姆独自进攻。

对准落单的拉姆，将顺势拾起的石龙刀迎面劈去──，

「不错嘛。借我用用」

先前被拉姆用风魔法卷起的刀剑劈砍，下颌遭侧面贯穿。

×　×　×

──九十一。

「好吧。我不借了──」

话音刚落，拉姆任由风卷来的石剑擦身而过，那柄石剑在掠过时脆裂崩解，与此同时阿尔德巴兰的必杀一击已朝拾武器落空的她轰然袭来。

拉姆以缠绕旋风的手刀格挡，精妙操纵气流借空中体位获取压力试图强行突破僵局。阿尔德巴兰用岩石义肢抓住她脚踝，顶着风刃反击将其甩向身后。

「──啧」

听着背后拉姆不甘的咬牙声，阿尔德巴兰继续突进，先前被扰乱的菲菈姆与疑似名为格拉西丝的姐妹此刻同时扑来。

面对这份不容因稚嫩外表而大意的凌厉攻势，阿尔德巴兰将原生右臂与义肢左臂向两侧展开，掀起横扫180度视野的砂浪怒涛。

翻涌的滔天砂浪吞没少女们，化作将她们镇压大地的囚笼──

「──阴之六，战士！风之五，魔法使！花之八，王！」

突如其来的压力从正面狠狠砸来，背部朝下摔进了自己制造的刀剑之海。

×　×　×

──一百一十二。

「──阴之六，战士！风之五，魔法使！花之八，王！」

听见的刹那，强行收拢张开的双臂，将沙浪枪口固定对准正前方──就在眨眼后出现的络腮胡巨汉被浪涛吞没，陷入与菲菈姆和格拉西丝相同的境地。

阿尔德巴兰趁机脱身，斜向飞窜试图越过敌阵──

「乌尔・戈亚!!」

保持着腾空姿势，无法躲避的炎之刚球直击内脏，体内燃起熊熊烈火。

×　×　×

──一百四十六。

「乌尔・戈亚!!」

用沙砾压制住双子与巨汉，面对逼近的火球故意慢了一拍。代替被火焰直击的，是阿尔德巴兰仓促制作的劣质土偶──相当于爱蜜莉娅用冰再现菜月・昴的魔法劣化版。

原本瞄准阿尔德巴兰头部发射的火球，在这场需要刹那决断的战斗中，竟被拙劣的土偶成功挡下。

「哈!?」

操纵火球的瘦削男子——那个眼神凶恶、舌钉晃动的家伙——见状倒吸一口凉气。

除非是精通魔法的大师，否则释放完乌尔级魔法后根本无法连续施法。阿尔德巴兰对着那张惊愕的脸竖起人造中指，这次终于能继续推进——

「——给老子碎!!」

斜后方迸发的光之冲击波直袭阿尔德巴兰脊背，足以灼烧世界的白光照得连意识都被彻底吞没。

×　×　×

——一百四十七。

「——给老子碎!!」

循着这声勇猛战吼回头，阿尔德巴兰看见菲鲁特正龇着虎牙英姿飒爽地摆出架势，而她手中魔杖正是光源所在。

那根被生前『魔女』夸耀为『连神龙都曾击溃』的『星杖』，正是名为『流星』的魔导器——说到底都是师父造的孽。

「在这儿被老师妨碍也太扯了吧」

前方漫长的无尽挑战、那道必须跨越的高墙，竟是由为阿尔德巴兰指明道路的『魔女』亲手所制，一股忧郁的情绪油然而生。

那道白光毫不留情地吞噬了阿尔德巴兰。

那么──

×　×　×

──一百四十八。

「──给老子碎!!」

──这道逼近的白光，究竟该怎么攻略才好。

△▼△▼△▼△

──神啊佛啊欧德・拉格纳啊。我发誓这辈子绝不送礼。

×　×　×

「──『忧郁』的权能到底是啥能力？」

△▼△▼△▼△

──神啊佛啊欧德・拉格纳啊。我发誓这辈子绝不向人挥手。

×　×　×

「──光用传送根本说不通。权能不该是这种玩意儿吧」

△▼△▼△▼△

──神啊佛啊欧德・拉格纳啊。我发誓睡前必祈祷。

×　×　×

「──肯定代表着某种概念。对吧？『忧郁』、『忧郁』啊」

△▼△▼△▼△

──神啊佛啊欧德・拉格纳啊。我发誓绝不抚慰他人伤痕。

×　×　×

「──心情低落、压抑、阴天、消沉、凹陷。……凹陷？」

△▼△▼△▼△

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生绝不因晴空而喜悦。

×　×　×

「──你在压缩吗，时间和距离之类的。不对，你压缩的不止这些吧？」

△▼△▼△▼△

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生绝不因雨天而哀叹。

×　×　×

「──把不够用的思考时间压缩填满了？不过，魔女因子这种东西啊……」

△▼△▼△▼△

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生绝不与任何人共赏彩虹。

５

「──魔女因子这种东西，哪有这么方便好用啊？」

刹那，突破『阿尔德巴斯特』包围网直逼正面的阿尔说出的话语，让佩特拉的脊背窜过一阵战栗。

被铁盔覆盖的阿尔双眼无法看见。──但视线交汇了。这种确凿感让佩特拉觉得内心被看穿，心脏因焦躁而狂跳。

不知为何，阿尔对魔女因子的了解竟比佩特拉更为透彻。

『佩特拉!!』「──花之八，魔女!!」

「──！」

内心思念之人的呼喊声与迫在眉睫的嘶哑指令重叠，佩特拉将自身萌生的犹豫『压缩』，为了不被阿尔伸来的手臂抓住，她躲过那只手拉开距离──将这一过程『压缩』，瞬间脱离。

「喂喂，连自己的空隙都不留吗……！」

眼见佩特拉从面前消失，挥空的阿尔咋舌回头。

大幅耸动肩膀的阿尔与佩特拉重新拉开对峙距离。怒目相对的二人之间，站着阿尔拼死突破的『阿尔德巴斯塔队』同伴们。要再次触及佩特拉，必须跨越同样的障碍。

但佩特拉心中完全没有得逞的感觉。

『佩特拉，刚才阿尔的话……』

「我知道。……真的，可以重来」

对身旁浮现的幻影菜月昴的话语，佩特拉眯起眼睛点头。

事到如今并非有所怀疑，但实际目睹阿尔的『时间回溯』时，仍不禁为其超规格的表现感到震惊。

加菲尔的先制攻击也好，拉姆与菲菈姆＆格拉西丝的联手攻势也罢，乃至加斯顿和拉珍斯通过『压缩』从三方发动的围攻、菲鲁特的包抄，以及听从罗姆爷指挥的六十人干扰部队——阿尔全都完美应对了。

而且都是以"唯有此法"的最优解形式完成的。

『咱家这个思考压缩虽然也能达成类似效果……』

「那只是在拼命思考直到得出正确答案而已。和昴还有阿尔先生的能力，终究还是有点不同呢」

『……按理说老子本该也有这么强的』

挠着头的『昴』垂头丧气地说着。但佩特拉并不这么认为。

昴有昴的战斗方式，他直面自己的权能，挽回了本应失去的众多事物，拯救了佩特拉等人。根本没有半点值得羞愧的地方。

虽然这么想着——

「……为了向我伸出手，你重来了多少次？」

在佩特拉的认知中，阿尔的实力作为战士还算凑合──确切地说，是远不及拉姆和加菲尔、恐怕也敌不过亨克尔的水平。即便如此，阿尔仅凭一人就戏弄了『阿尔德巴斯塔团』，甚至差点将死对方。

『别说十次，说不定都重复二十次了』

「……或许更多呢」

对于『昴』的乐观估计，佩特拉预想可能是其十倍二十倍的次数。

实际上，若换成佩特拉置身突破『阿尔德巴斯塔团』的立场，即便拥有预知后续发展的权能，她也没有百次挑战内通关的自信。更何况阿尔虽借助了『龙』之力，却有着连莱因哈鲁特都能回避的战绩。

要达成这种伟业，人类究竟要扼杀多少心志才能持续挑战。

倘若阿尔的『时间回溯』真如佩特拉他们所想，是和菜月・昴一样以『死亡』为代价的能力，那么眼前之人便是披着轻浮外皮的可怕『魔人』。

如今的阿尔早已克服了『死』的恐惧与丧失感──不，世上根本不存在能克服那种东西的人类。准确来说，那不是克服而是麻木。连畏惧『死亡』的生命本能都已麻痹。那正是阿尔强大的秘诀，也是身为『魔人』的绝对性根源。

若要超越那份绝对性，我们也必须付出相应的代价。

『──佩特拉』

「没问题的，昴。……因为我、不要紧的」

是盘踞在脑海中的存在。

唯独对幻影菜月昴，佩特拉那个连『阿尔德巴雷』全员和爱蜜莉娅阵营都无人知晓的秘密已然暴露。

这件事也被眼前精通魔女因子的『魔人』点破了。

──自称为『忧郁魔女』的存在，不会被命运眷顾。

「即便如此，这种事也构不成让我停手的理由」

如此自欺欺人地，佩特拉・雷蒂──『忧郁魔女』发动了权能。

以干涉世界之理为代价，从自身存在中逐渐流失的未来，无论多么重要且无可替代，新生的『魔女』都毫无犹豫。

６

──七千零一十一。

「即便如此，这种事也构不成让我停手的理由啦」

望着远处佩特拉翕动的嘴唇，阿尔德巴兰不禁想脱帽致敬。当然并非真的摘下头盔，但确有这般冲动。

「……菜月・昴这家伙真是」

咬牙切齿的阿尔德巴兰已摸清敌团──自称『阿尔德爆破团』。这命名品味倒合他胃口。总之通过此前与『阿尔德爆破团』的交锋，佩特拉吸收的『忧郁』魔女因子及其权能大致规格已被解析。

但凡战斗皆如此，关键在于获取大量精准的敌方情报。与权能者或加护持有者的对决堪称信息战，而『领域』在这方面极具优势。

虽然活用其优势揭示了『忧郁』的权能，但这性能实在荒谬绝伦。将间隙与时间碾压──『压缩』的力量，在应用层面上恐怕无人能及。事实上，敌方似乎将思考和商议时间都『压缩』了，即便是短短一秒的攻防，经过深思熟虑的最优策略也会接连不断袭来，纵使是阿尔德巴兰也难以突破。

实际上，仅为突破短短十一秒的攻防，就迫使阿尔德巴兰重复尝试了七千次之多。

「即便如此，『忧郁』的权能与巴尔加的相性简直糟透了……」

在『阿尔德巴斯特小队』中，也有被折磨得苦不堪言的巴尔加・克罗姆威尔的身影。

那个完全不利用天赋巨躯的智谋怪物，凭借被赋予的无限思考时间，向同伴下达唯一的最优解指令，将阿尔德巴兰逼入噩梦般的绝境。

若被巴尔加玩弄于股掌之间，很可能再度封杀阿尔德巴兰。因此，即便不得不耗费思考时间，也绝不能给予太多试错机会。

更何况，『忧郁』的魔女因子是必须尽快夺取的麻烦东西。

『──『忧郁』的魔女因子是次品。是为勇者准备的唯一物品，与其他任何人都无法适配。反过来说，也可以认为只要支付代价就能与任何人适配。因为人类是可以靠觉悟来零碎出卖太多东西的生物啊』

这是之前从『魔女』那里听来的，关于『忧郁』的魔女因子的情报。

或许是有相当深的感触吧，『魔女』对于堪称例外的两个魔女因子不愿多谈，但一旦开始讲述就变得滔滔不绝。

若要将那段不得要领的长篇大论总结起来，要点如下。

──『忧郁』的魔女因子会以所有者的意志为代价发动权能。

──使用『忧郁』的魔女因子所需的代价，若非所有者便无法支付。

「──菜月・昴」

思考至此，阿尔德巴兰再次对菜月・昴感到愤怒。

无论、ペトラが『忧郁』の魔女因子を取り込むことになった过程に、『死者の书』を読ませた自分の计划が无関系とアルデバランは思わない。だが、切挂けを作ったのがアルデバランであるなら、切挂け以外の责任はナツキ・スバルにある。

考虑到阿尔德巴兰和菜月・昴的关系，说到这种程度也是理所当然的吧。

佩特拉人生中笼罩的巨大阴影，是以菜月・昴为开端的。不能说、也不认为他怀有恶意，但其影响力无疑巨大。这不止限于佩特拉，在『阿尔德巴星团』──不，在这场战斗之前的诸多场合也展现过，可以说是一种命运力。「──咔」即便如此，说这是命运力也颇具讽刺。毕竟不是别人，正是菜月・昴和阿尔德巴兰最憎恨命运的立场，「──嗯」而他们的行动却堪称决定了命运。「──噗」想到这里，掠过阿尔德巴兰脑海的是她鲜红炽烈的言辞。那个，「──嘞」她在最后时刻吐露的赞美，正灼烧着阿尔德巴兰的心脏。他刻意移开视线，堵住耳朵。「──嘶」如今早已过了反省自身行为的时机。支撑现在阿尔德巴兰的并非逝去的她，而是与老师的誓约。「──啊」阿尔德巴兰为何而生，又为何被冠以阿尔德巴兰之名，此刻正是其集大成接受考验之时。为此根本无暇驻足思考──等等，等等等等。是不是太长了？本该在短暂换气、深呼吸的间隙重启战斗。「──咯」理应如此。对方不想让我们喘息。我们也不愿给予对方更多时间。「──呢」本该有此共识，为何阿尔德巴兰还能如此从容地思考──「──ー」。不妙。很奇怪。什么？她说了什么？远处，佩特拉嘴唇的翕动被察觉。一字一句地捕捉那唇瓣编织的音节。在思考的间隙拾取、拼凑那些碎片。太慢。焦躁。简直慢得离谱。快理解含义，快抓住意义，快领悟意图。──。────。────。不行。无法让思维静默。边想边做也行。『Compress』？压碎吗？压碎什么？『Agony』？疼痛？痛苦？苦恼……苦恼？烦恼、思索、剖析。该死，中招了。思维被『压缩』了。──思考被『压缩』了!!

７

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生绝不违背重要约定。

△▼△▼△▼△

「──『压缩苦痛』」

借由『忧郁』权能实现的思考『压缩』──加速同伴思维、省略商议过程、让全员直接打出经深思熟虑的最优解，这种强力增益效果正是佩特拉为阿尔准备的对抗策略之一。

「要考虑的事情太多的话，脑袋会过载爆炸对吧」

尽管僭越，但此刻的佩特拉自负地认为，关于『死亡回归』这项『时间溯行』，自己仅次于昴和阿尔，是世界第三了解之人。

凭借这份学识，以及亲身体验过昴所经历的『死亡』痛苦，她找到了让近乎无敌的阿尔权能失效──不，使其『过载』的方法。

那便是通过加速思考对精神施加的过载。

从前在王选刚开始时，曾在王都与爱蜜莉娅吵架决裂的昴，就因承受巨大压力与精神负荷导致心智彻底磨损。

那虽因雷姆的奉献和对大罪司教的愤怒意外获得了振作的契机，但曾一度丧失战意变成空壳确是事实。──此刻重现这一幕。

『说实话，对我来说这段黑历史太痛苦了……但变成废柴也算值了！』

虽难以全盘肯定这个握紧拳头的幻影菜月昴，但道理确实如此。

早已对『死亡』麻木的阿尔，无论叠加多少次『死』恐怕都不会挫败其心志。

但即便如此，就算主动与世界为敌，阿尔终究是人类。

精神出现裂痕迎来极限是不可避免的。此刻，诱发这种状态。

为此不惜牺牲自己的任何东西──

「──领域展开，矩阵再定义」

在思维加速的煎熬中，能感觉到阿尔轻声说出这句话。

精神正承受着高负荷，但这种状态是双刃剑。阿尔的心智与头脑在如此剧烈消耗下濒临极限，与『阿尔德巴斯特』同理，其思维的『压缩』可能转化为最大增益效果，迎击佩特拉他们的概率是五五开。

因此，从此刻开始的战斗才是真正意义上的『阿尔德巴斯特』决胜关头──

「──大家！现在才要开始哦！别松懈啊！」

「「──噢!!」」

对于佩特拉的激励，被『压缩』了交流时长的同伴们发出回应。

她正因这份可靠而振奋，准备重新迎战阿尔时──察觉到了。

方才有力回应的伙伴中，有个声音缺席了。

或许只是错过时机。但佩特拉感到异样，余光扫向那边寻找未回应者的身影。

随后，发现了。

「──罗姆爷爷？」

那位没有回应的大参谋，肩负着俯瞰战场、适时下达精准指示职责的魁梧老人，正缓缓翻着白眼轰然倒地。

８

──时间，仅仅倒流刹那。

「──领域展开，矩阵再定义」

听到阿尔德巴兰如此宣言，罗姆爷那宽厚的肩膀猛然震颤。

佩特拉运用『忧郁』权能的计策已然发动──通过加速阿尔德巴兰的思考对其精神施加负荷，令其急速衰竭。虽对加速阿尔德巴兰思维存有顾虑，但既然双方条件对等，罗姆爷也认定这是比拼综合实力的决胜时刻。更重要的是他判断自己也能为此战略贡献力量。

作为昔日以亚人联合『大参谋』之名肆虐的巴尔加・克罗姆威尔，这份力量定能为菲鲁特等现代之人所用。

实际上，罗姆爷的算计命中了。在与『暴食』的战斗后，他继续作为指挥者调度同伴们的行动，并成功将阿尔德巴兰逼入绝境。──然而，令罗姆爷震惊且剧烈动摇的异变发生了。

「──领域展开，矩阵再定义」

随着阿尔德巴兰如此宣言，罗姆爷的站位在一瞬间改变。──不，改变的不仅是罗姆爷，阿尔德巴兰、菲鲁特以及参与这场战斗的所有人站位，都倒退到十几秒前的状态重新开始。

而这样的状况，罗姆爷已经重复经历了五次──

「──这、这是什么情况」

转动脖颈环视四周，罗姆爷在五次目睹的相同光景中，沉重地挤出这句话。

能察觉到这场异变的，除罗姆爷外别无他人。

「──大家！就从这里开始哟！别松懈啊！」

「「──噢!!」」

作为证明，在佩特拉充满斗志的指挥声中，除罗姆爷外的所有人齐声响应。

就这样朝着阿尔德巴兰一齐扑了上去。

「罗姆爷！　给个指示！」

未察觉这边的动摇，手持『星杖』的菲鲁特正在寻找攻击位置。除了菲鲁特外，其他拥有决定性技能的同伴们也正奔跑着等待罗姆爷的指示。

望着他们的背影，罗姆爷咽下苦涩的唾沫，发出与先前不同的指令──

「──领域展开，矩阵再定义」

──与阿尔德巴兰的第六次最终决战开始了。

９

──阿尔德巴兰的『领域』是与魔女因子相关的权能。

但阿尔德巴兰并非魔女因子的持有者。『魔女』称此为特例或番外，而阿尔德巴兰认为盗用或缺失编号的说法更贴切。

这种现象早有先例，比如曾与魔女因子适配并获得权能的『大罪魔女』们，即便死后仅剩灵魂仍保有相同力量。

对此『魔女』推测：魔女因子或许是开启干涉世界权限之门的钥匙，而一旦门被打开，即便失去钥匙也会保持开启状态。

那种情况下，没有魔女因子的阿尔德巴兰、或是『魔女』本人的存在就无法解释，对此有种假说认为——或许是与魔女因子适配者之间的联系，让他们天生就打开了干涉世界之权限的门扉。

不过──，

「就像有翅膀的存在无法向无翼者说明如何挥动翅膀，我们这些并非后天获得的权能也难以解释。硬要说的话，就是天生门扉半开的状态吧」

这似乎是本人倾注全力的幽默，『魔女』说着露出得意的表情。可惜阿尔德巴兰完全笑不出来，但内容本身确实令人信服。

半开的门通风差劲又难以操控。想窥视却总被遮挡视线，还频繁发生夹手之类的意外。若能像『魔女』那样干脆选择不开门倒也好。

但要做到这点，阿尔德巴兰就未免太过平庸无能。

对坚持不开门的阿尔德巴兰而言，根本看不到完成『魔女』期待之职责的希望。既然如此，哪怕是半开状态，阿尔德巴兰也根本没有拒绝开启门扉的选项。

因此，阿尔德巴兰半开门的权能中存在诸多不透明之处。──凭借使用手感与经验法则，再结合『魔女』的推测，以掌握八成左右全貌的状态运作着。

或许有人觉得这样很危险，但就像不懂手机原理也不妨碍安全使用手机一样。当然，阿尔德巴兰的权能毕竟与性命息息相关，和手机的情况略有不同。

总之，这个权能虽已陪伴他度过体感时间长达十几倍的人生，但关于『领域』仍存在许多黑箱。──偶尔发生的bug就是最典型的例子。

──所谓『领域』中的bug，是指设定好的矩阵主导权持有者从阿尔德巴兰转移到矩阵内其他对象的现象。

通常阿尔能凭自身意志设定『领域』，被允许在既定时空内进行无限挑战。期间持续挑战的阿尔记忆会始终保留，按惯例要每次尝试不同验证来寻找突破口。

然而，若因某些按钮错位导致BUG出现，保留记忆并『重开领域』的权利将转让给矩阵内的他人。其结果就是，对方在『领域』解除前，会不断重复这个永无止境的矩阵轮回。

かつて、『魔女』といた顷には発现しなかったこのバグは、初阵に败北し、権能への信頼を损なったことが原因で発症したとアルデバランは睨んでいる。

实际上，每次出bug都必定是阿尔德巴兰怀疑自己权能的时候。

早在剑奴孤岛时，被迫与毫无胜算的强敌死斗之际。此后，在与因自身立场而迷茫的莱普・跋利耶尔冲突时，以及迎战普莉希拉派来的刺客八重・天膳时，这个BUG都曾出现过。

最重要的是──

「──有意思。把权能的主导权交给对手这种事，我可从没听说过」

在梦之城迎战阿尔德巴兰的『强欲魔女』时，这一幕发生了。

「真是相当稀有的体验。原来如此，那就是你所见的世界啊。确实，如果对发生现象的原因毫无头绪，那确实是足以令人发狂的现象呢」

他向着面目全非的『强欲魔女』挥刀，要求她归还自己认识的那个『魔女』。

但当运用『领域』进行的种种尝试、所有创意都完全无效时，阿尔德巴兰心中对权能产生了猜疑——仿佛印证这点般，系统出现了错误。

「对权能绝对性的怀疑，由此产生的变化……那是源自软弱的力量。可惜的是，对丧失理智的存在无法生效。她如此，我亦如此」

面对困惑的阿尔德巴兰，『强欲魔女』详细描述了自己经历的地狱。

那确实是阿尔德巴兰熟知的『领域』世界，同时又存在着决定性差异，令人难以理解『强欲魔女』是如何忍受下来的。

正如『强欲魔女』自己所言，难道是因为失去理智才得以忍受吗？

「行使权能时，多数情况下你都是弱者。为了找出微小的胜机、撬开缝隙并最终夺取而依赖『领域』，可谓受害者。而若将强迫你使用『领域』的对手视为加害者，这便是受害者与加害者间主导权的交换」

面对欢快揭露地狱真面目的『强欲魔女』，阿尔德巴兰感到全身血液逐渐凝固，同时意识到这正是自己亲手缔造的噩梦。

将梦之城化作噩梦的元凶，『领域』中产生的异常，皆源于阿尔德巴兰的软弱——那是源自「弱小」这项不被容许之罪的惩罚。

「计划仍在推进。首要目标虽已受挫，次要目标依然有效。我们此刻所做的一切，不正是为了拼凑那点仅存的最优解吗？你我都是如此。对吧？」

『强欲魔女』嗤笑着，仿佛要共同拖拽那罪孽的十字架——那沉重得让人几乎想抛下的、独自无法承受的十字架。

面对那张既想看见又不愿看见的笑脸，阿尔德巴兰下定了决心。

「我绝对要——亲手杀了你」

『领域』的漏洞、源自自身弱点的力量、甚至连阿尔德巴兰败北的烙印都加以利用，完美履行了『尾随星』的职责。

「──爱为何会消减呢」

『强欲魔女』如耳语般的呢喃，其答案，阿尔德巴兰并不知晓。

失去了渴求爱的『魔女』，失去了深爱的『太阳姬』，时至今日，依然不知。

──也不愿，知晓。

10

──思考开始加速。在佩特拉的权能压迫下，阿尔德巴兰无法为喷涌而出的杂乱思绪排序，脑袋几乎要炸裂。

「──该死」

可怕的权能。与效果参差不齐的加护不同，大多数权能都能持续发挥超规格的力量，佩特拉的『压缩』也不例外。权能往往取决于持有者头脑的灵活性，适用性极高。要么异常固执，要么因脆弱而衍生出灵活性──能引出魔女因子强大力量的才能，很大程度上受这种精神特质影响。大罪魔女和大罪司教属于前者，阿尔德巴兰和佩特拉则可归为后者。无论是加护者还是权能持有者，甚或无能之辈，阿尔德巴兰始终觉得后者更难对付。事实上，对阿尔施加『压缩』思维的攻击效果立竿见影，这种逼得我方为保存精神力而耗尽余力的阴险手段堪称完美。在需要瞬间判断的战斗中，持续探寻最优解的能力极为珍贵。但本质上，战斗永远无法做到万全。因此必须在某个节点下定决心，停止思考并付诸行动。佩特拉的『压缩』却强制填补本应舍弃的思维冗余，迫使得出相同结论需耗费双倍精力。结果阿尔德巴兰以巨额精神力消耗为代价，面对士气高昂的『阿尔德爆破团』持续给出穿针引线般精准极限的解答。就在这场消耗战途中──

「──罗姆爷!!」

『阿尔德巴兰队』的攻防刚告一段落，耳边就传来近乎悲鸣的喊声。发出声音的菲鲁特瞪大双眼，望向远处那具正在崩塌的老年巨躯。霎时间不仅是菲鲁特，『阿尔德巴兰队』其他成员也因动摇而心神震颤。在尚未理解发生何事之际，巴尔加・克罗姆威尔已然倒下。

「────」

虽不知手法为何，但凶手的候选人显然只有一个。结果除奔向倒地的巴尔加之人外，其余敌意尽数集中于阿尔德巴兰。承受着这些敌意的阿尔德巴兰，却在『阿尔德巴兰队』看不见的头盔深处，与队员们同样惊愕地瞪大双眼。

「──你成了『领域』的加害者啊」

这并非有意为之。但他已明白发生了什么。『领域』的漏洞被触发，作为加害者之一的巴尔加被赋予了主导权。而这位老巨人恐怕被迫重复了足以令心智崩溃的、短暂时间的轮回。

「切」

起死回生、千载难逢，能称之为如此的机会来临，阿尔德巴兰却并不欢迎。如前所述，bug的发生与阿尔德巴兰的意志无关——至少，并非主动发动。而且，阿尔德巴兰无法为bug的发动感到欣喜。因为bug在多数情况下，会摧毁被卷入对象的心灵。

「剑奴孤岛也好，莱普老爷子也罢，八重那家伙也是……」

凡是与阿尔德巴兰对峙、被『领域』bug吞噬、陷入无法逃脱的『死亡』循环之人，无一例外都出现了精神异常。心灵被摧毁的剑奴们被阿尔德巴兰斩首，丧失理智的莱普・跋利耶尔忘却了多年野心，因恐惧屈服的八重・天膳化作了忠实的仆从。这种扭曲心灵存在方式的『领域』bug，对施加不杀条件的阿尔德巴兰而言，几乎只会带来与『死亡』同义的结局。因此，阿尔德巴兰无法为这种了结感到喜悦。——当真如此？

『──谁也无法战胜我创造的你哦』

一度、里切ってしまった『魔女』の声が、期待が、理想が、闻こえる。相手の执念に、作戦に、団结力に、万が一を、亿が一を、兆が一を、恐れ、警戒し、疎んだことで、『领域』はバグの発生する条件を満たした。──言うなればそれは、アルデバランが権能を、自分を、『魔女』を、疑ったからに他ならない。

『──谁都无法战胜我创造的你哦』

又一次听见『魔女』的声音。──看见下一个加害者翻着白眼倒下。

11

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生不爱喧嚣。

△▼△▼△▼△

「──罗姆爷爷？」

局势开始变动。──而且是朝着对佩特拉他们不利的方向。

远处，罗姆爷突然倒下的身影让佩特拉瞪大了双眼。她的内心被涌现的惊讶、不解、不安、动摇以及其他无数情感所支配，几乎要淹没全身──，

『──佩特拉!!』

「──呜」

幻影菜月昴的一声大喝，在千钧一发之际拉回了佩特拉的意识。

对意外状况感到惊讶无可厚非。被意识之外的攻击打中还能保持镇定的人根本不存在。但身为『忧郁魔女』的佩特拉，有比惊讶更重要的事要做。

将针对突发状况的所有反应进行『压缩』。

「开什么玩笑！这他妈怎么回事！快把罗姆爷叫醒！」「少胡扯！他突然就翻白眼了！喂，到底发生什么了！?」「现在怎么办！没有老爷子的话，谁能……」「该死！拉姆！现在只有拉姆了！」「──真没办法。女王的棋子不能用了。给我牢牢记住了」「再不行动就和等饲料的猪没两样。先发制人了」「混蛋！都到这一步了怎么可能输！」「「那当然!!」」

瞬间将蔓延的动摇『压缩』至一瞬，佩特拉履行了『忧郁魔女』的职责。

虽然尚未查明原因。但应对方案已即刻敲定，所有人团结一致开始寻求最佳对策。——当然，佩特拉也不例外。

代替倒下的罗姆爷，拉姆接管了指挥塔的职责，佩特拉发动权能，将她与罗姆爷之间的移动距离和时间『压缩』，飞奔过去。

「罗姆爷爷……啊」

佩特拉俯身查看脸朝下倒地的罗姆爷，顿时哑然失声。——因为倒下的罗姆爷脸上毫无生气，渗出仿佛瞬间衰老百年的疲惫感。

『虽说原本就不是什么生命能量爆裂的面相……』

「刚才明明不是这样的，绝对。而且如果察觉到身体异常，罗姆爷爷肯定会向我们报告的」

罗姆爷很清楚，贸然隐瞒身体异状反而会成为资敌行为。

倘若『忧郁』权能造成过度负荷，或是出现像这样昏倒的征兆，他肯定会主动上报。

「果然不是我的权能问题。是阿尔先生对罗姆爷爷做了什么……」

『……但，做了什么？』

陷入同样的疑问死胡同，佩特拉与『昴』一同迷失在答案中。

此前，『阿尔德巴斯特团』也在拉姆的指挥下持续着围剿阿尔的战斗，佩特拉也无法将思绪全倾注在罗姆爷的昏迷上。

如此想着，佩特拉正要中断思考──

「──笨蛋！那边才该优先！」

背对着这边的菲鲁特，当头修正了优先级顺序。

面对瞪圆双眼的佩特拉，手持『星杖』的菲鲁特龇出尖锐的虎牙

「不想办法解决刚才那招，所有人都会用同样方式被干掉」

菲鲁特不甘心地咬着牙，仿佛印证她的话语般，原本包围并压制阿尔的『阿尔德巴斯特团』成员正在减少。环顾四周，激战中被遗落的数人已倒地不起。

从菲鲁特的措辞来看，他们倒下原因与罗姆爷相同──

「罗姆爷才不会白白挨打！给我找！肯定有什么机关！」

听到菲鲁特的控诉，佩特拉再次看向倒地的罗姆爷那巨大身躯。

她认为罗姆爷是个精明人，也是能回应菲鲁特期待的存在。所以如果菲鲁特相信有蹊跷，那就肯定有问题。

『可话说回来，突然被权能轰个正着的话根本没法留后手吧……！』

「……你觉得是权能？」

『不然说不通！要是魔法姐姐大人早发现了！』

「说的也是」

菲鲁特的确信×对拉姆洞察力的信赖。

这两点结合印证了击倒罗姆爷的是阿尔的权能。而如果罗姆爷真的留下了什么——

「——！是这个」

当佩特拉仔细检查无力横卧的罗姆爷全身时，发现老巨人的粗大手指沾着泥土。那新鲜的污痕正是用手指抓挠地面留下的。

她猛撞因倒地冲击而偏移的巨躯，在踉跄之际发现了罗姆爷留在地面的讯息。

那是——

『记号？汉字……不对，地图符号……』

「都不是，要更简单！」

看到相同东西的『昴』正在思索时，佩特拉用尖锐的声音喊了暂停。

罗姆爷留在地面上的记号──那是粗横线上叠加了四条短竖线的东西。既非汉字也非地图符号，而是以五为一组计数的『画线法』。

也就是说，罗姆爷在即将失去意识前──

「──是在数，某种东西的数量？」

12

──『领域』的漏洞，开始侵蚀阿尔德巴兰的计划。

「可恶……」

面对这个事实的恼恨，让阿尔德巴兰从紧咬的牙缝中漏出咒骂。最先倒下的是『阿尔德巴斯特』的军师巴尔加・克罗姆威尔。尽管失去了指挥中枢却能立即重整旗鼓，或许是佩特拉权能的效果。但若说这效果只是拖延时间，那么情感层面的恢复就是每个人的个人实力。每次深切感受到这群人内心的坚强时，阿尔德巴兰的软弱就会暴露无遗。

「可恶……呃」

就在想到自己还不够成熟的刹那，『阿尔德巴斯特』又有一人退出。那个扛着大砍刀的小混混膝盖一软跪倒在地，吐出黄色胃液昏了过去。阿尔德巴兰没有反击。也做不到。作为基本战术，加菲尔被推出来对付基础属性相差悬殊的对手，连反击都难以进行。然而对手的战力却在稳步削减，这是阿尔德巴兰意料之外的漏洞导致的结果。

『──谁都无法战胜我创造的你哦』

又听见了『魔女』的声音。紧接着下一个漏洞出现，新的退出者产生。这对阿尔德巴兰来说很痛苦。难以忍受。──『领域』漏洞造成的精神磨损，有时会导致比肉体『死亡』更可怕的结局，阿尔德巴兰在剑奴孤岛苏醒后的日子里深刻体会到了这一点。所以阿尔德巴兰不希望『领域』漏洞导致违背本意的结──

「──你他妈把什么都怪到别人头上啊」

「──啊？」

「不用看脸也明白啊。虽然像莱因哈鲁特那样，把什么都当成自己责任的嘴脸也很让人火大……但你这家伙比那混蛋还过分」

菲鲁特从『阿尔德巴斯特队』的人墙缝隙间，死死瞪着正试图撕开裂口的阿尔德巴兰。她锐利的赤红目光中，蕴含着对阿尔德巴兰毫无虚假的强烈轻蔑与愤怒。这是她既未被带走时、也未命令罗伊吞噬『记忆』时展现的激烈情绪，令人难以理解究竟何事真正触怒了她的逆鳞。既非情同家人的巨人倒下，亦非险些被夺走的人生轨迹——此刻菲鲁特对阿尔德巴兰怀抱的愤怒根源在于——

「有那位公主在时就对公主言听计从，等她不在了这回又换个人当主子？明明夸下海口说要与全世界为敌，结果你这混蛋连自我都没有吗」

「────」

面对菲鲁特那副打心底里火冒三丈的表情和话语，阿尔德巴兰脸颊微微绷紧，随即对无知小丫头的胡言乱语涌起怒意。说什么没有自我——这种狂言也该有个限度。竟敢在不知道阿尔德巴兰只能自称阿尔德巴兰的理由的情况下，大放厥词说他没自我。愤慨灼烧着五脏六腑，连从二头肌到不存在的断臂都泛起熟悉的疼痛。这种无用的激情早该抛弃才对。本该很拿手的——干脆地切割、嘲弄、当作碍事之物嗤之以鼻然后舍弃。被这种东西牵绊住而迷失目的才是本末倒置，不与真实的生命情感正面交锋正是阿尔德巴兰的特技——不，是从那颗黑球中解放后十八年间习得的处世之术。所以这次也，同样地——

「菲鲁特大人说得没错吧啊！」「给老子接受报应吧！」「去死吧蠢货！」「已经没人站在你那边了！」「阿尔大人，请做好觉悟」「审判时刻到了」「像猪一样嚎叫吧」「——真是愚蠢」

「——！」

以怒涛之势袭向阿尔德巴兰的污言秽语、轻蔑风暴。他本想像往常一样置若罔闻──却被『压缩』了思考，被迫强行处理。与平日不可同日而语的超高速处理回路，将多余思绪与情感尽数碾碎。

『──谁都无法战胜我创造的你』『──谁都无法战胜我创造的你』『──谁都无法战胜我创造的你』『──谁都无法战胜我创造的你』『──谁都无法战胜我创造的你』『──谁都无法战胜我创造的你』『──谁都无法战胜我创造的你』『──谁都无法战胜我创造的你』『──谁都无法战胜我创造的你』『──谁都无法战胜我创造的你』『──谁都无法战胜我创造的你』

当阿尔德巴兰内心正呐喊着"不能这样下去"时，那个声音逐渐侵蚀了他的意志。他抗拒着沉沦，转而寻找引发事件的少女核心──那位迫使阿尔德巴兰必须深思万象的『忧郁魔女』──

「──刚才是在，数什么数字吗？」

「────」

远远望见的『忧郁魔女』佩特拉・雷蒂，看着倒下的巴尔加・克罗姆威尔留下的某种讯息，如此低语的模样被察觉了。瞬间，从阿尔德巴兰体内黏稠地、漆黑地、炽热的冲动满溢而出，化作言语。

「──是星星的错啊」

「哈，没错。老子才不听任何人使唤。这才是你的真心话吧」

对着阿尔德巴兰被激情侵蚀的声音编织的话语，菲鲁特龇牙咧嘴。这本该与她毫无、彻底、分毫、半点、一毫米的相似之处，却与普莉希拉・跋利耶尔浮现的笑容如出一辙。这是噩梦。——要终结它。唯有如此，阿尔德巴兰才首次主动引发了『领域』的异常。

「──领域展开，矩阵再定义」

13

——神明啊佛祖啊欧德・拉格纳大人啊。我发誓这辈子绝不指望任何人的善意。

△▼△▼△▼△

「──领域展开，矩阵再定义」

从如此宣言的阿尔声音里感受到确切变化，佩特拉猛然回头。

在这场战斗中已经多次听到的那声呼喊，恐怕是阿尔的权能发动条件之一吧。正如罗姆爷事先推测的那样，阿尔能够施展的『时间溯行』虽然范围有限，但似乎是相当强力的能力。

其时间跨度比菜月・昴的『死亡回归』更短，而且还是自觉发动的。

『要是棒球游戏能手动存档的话，比如每次击球时都存档读档，记住下一球的球种和投球位置就能连续打出全垒打了吧』

「能理解但很难想象。真有人会这么做吗？」

『要向只懂游戏皮毛的孩子解释这个概念实在太难了……』

虽然读过菜月・昴的『死者之书』，自认为比皮毛懂得多些，但就缺乏实感的记忆这点而言，幻影菜月昴说得没错。

虽说窥探过昴的记忆，但佩特拉的感性终究属于她自己。当然，就像对爱蜜莉娅和雷姆的态度那样，关键在于这份情感在昴心中占据多大比重。

总之──

『──不能移开视线』

「我知道」

声音和氛围的变化，恐怕与阿尔的战斗已进入下一阶段。

在此期间，虽然像罗姆爷那样被用相同手法削减战力，但以拉姆、加菲尔、菲鲁特为核心的『阿尔德巴斯特』主力仍奇迹般健在。『压缩』的思维与协作无疑成为巨大力量，佩特拉也甘愿承受诸多弊端，将『忧郁』权能发挥到极致。

「干死你们啊!!」

「「──哦哦!!」」

仿佛助推佩特拉的斗志般，菲鲁特的鼓舞令士气爆发。

『阿尔德巴斯特』的连续施压确实正逐渐耗尽阿尔的余力，磨损其精神，将他的身心逼至致命性消耗的边缘。

接下来就是比拼双方谁先气力耗尽而倒下──就在佩特拉咬紧牙关、振奋身心的那一刻。

「诶？」

本该紧闭的嘴不由自主地张大，佩特拉愕然呆立。

那是当然的吧。毕竟，就在刚才。『阿尔黛巴斯塔』们干劲十足，士气高涨地展开了对阿尔的总攻。——然而这群『阿尔黛巴斯塔』的成员们，却突然像多米诺骨牌般接连倒下，毫无抵抗之力地瘫倒在地。

「────」

拉姆也好，加菲尔也罢。菲鲁特、菲菈姆与格拉西丝，拉珍斯、加斯顿、汉巴里和多尔泰罗，主力成员自不必说，『阿尔黛巴斯塔』的其他成员们也接连倒下，全员都失去了力量，没有一个人能站起来。有人昏迷不醒，有人因剧烈消耗而目光涣散，还有人像人偶般僵直不动。

所有人，是所有人啊。——不，还站着的家伙有一个。

「——是星星」

跨过倒地不起的『阿尔黛巴斯塔』包围圈，向前迈步的人物用手指拨弄着黑色铁头盔的金属部件，如此嘀咕道。

听着那些话，佩特拉感到大脑的一部分仿佛麻痹般无法正常思考。思维停滞是不行的。『压缩』虽然能填补事件发生的间隙，却无法填补空白。

「是星星不好」

阿尔边说边走近，原本扶着头盔的手伸向呆立原地的佩特拉。

必须立刻处理、应对、解决──

『──佩特拉！立刻向正后方『压缩』!!』

「──！」

听到近乎怒吼的喊声，佩特拉条件反射地『压缩』空间向后飞跃。相比倒跳获得更大距离的她双膝颤抖，隔着岩场望向阿尔。

视线尽头，阿尔反复开合没能抓住佩特拉的手，发出长长叹息。随后保持距离与佩特拉正面对峙──

「──比赛开始」

×　×　×

「──领域展开，矩阵再定义」

就在阿尔说出比赛开场宣言的瞬间。

就在那个阿尔发言的同时，另一个不同的阿尔发言紧随其后。这种本人同时发声的诡异现象，让试图理解状况的佩特拉大脑瞬间宕机。

但是，意识到这种停滞会致命，她立刻试图重新集中精神──，

「看招吧你们这群混蛋!!」

「「──噢噢!!」」

「诶!?」

紧接着，震撼空间的勇猛吼叫与回应声传来，吓得人魂飞魄散。

此刻展开在眼前的，竟是本该在瞬息间全军覆没的『阿尔德巴斯塔队』完整阵容。以拉姆为司令塔，加菲尔为先锋，手持『星杖』的菲鲁特担任终结者的阵型，她们正朝着阿尔冲杀而去。

然而──，

『喂、喂喂喂喂、这搞什么』

身旁浮现的幻影菜月昴愕然吐出困惑。即使明白这份困惑与自己同调，佩特拉心中也未能涌现丝毫安宁。

只是在剧烈动摇中，还没来得及说出劝阻的话，局势已骤然变化。

「──呜」

这简直就是方才情景的完美复刻。

『阿尔黛巴斯特』的成员们一齐崩溃倒下，那个曾经如此可靠的团体分崩离析。在强大英勇的拉姆、加菲尔和菲鲁特都接连倒下的过程中，佩特拉再次与唯一留下的阿尔四目相对。

「是星星」

「────」

「都是星星的错」

同样完全相同的宣告，接下来的动作也如出一辙，佩特拉并非被催促，而是任由内心的情绪驱使，通过『压缩』向后跳去。

再次拉开距离与阿尔对峙时，听到了他叹息的声音。

那是──

「──比赛开始」

──那便是永无止境的佩特拉・雷蒂地狱的开端。

** 第五章 『佩特拉・雷蒂』

１

──佩特拉・雷蒂是出身于露格尼卡王国阿拉姆村的乡下姑娘。

虽天生丽质且心灵手巧，但除此之外并无特别之处，本应与载入史册的大事件无缘，恐怕会怀着对都市的憧憬，作为普通村民度过一生吧。

故而，偏离了『原本』路线、与多个足以载入史册的重大事变产生关联的当下佩特拉的存在方式，正是被干涉扭曲后的产物。

对于这份命运曾遭扭曲的事实，佩特拉本人也心知肚明。

『原本』的佩特拉该是个仗着可爱劲儿趾高气扬，误以为能把周围大人小孩都玩弄于股掌之间的烦人丫头。想必『原本』的她会在未被纠正这份误解的情况下，摆着小世界统治者的架子恣意妄为吧。

倒也不觉得那样的人生有什么不好。想来那般活法，自有其快乐幸福之处。

只不过，如今偏离了『原本』的佩特拉所持的价值观，已无法将那视作幸福罢了。

「因为那样的世界里，根本没有我现在喜欢的任何一个人对吧？」

没有昴。没有法兰黛莉卡。没有爱蜜莉娅。没有碧翠丝。没有梅莉。没有拉姆。没有雷姆。没有琉兹。没有安妮罗洁。没有加菲尔。没有奥托。没有柯林特。罗兹瓦尔嘛...勉强往后排。──但是，大家都不在那里。

「那种事、想想就毛骨悚然」

如果没能遇见最珍视的人们才是『原本』的自己，而此刻的存在只是命运碰撞的偶然结果，那我真心庆幸脱离了『原本』。

正因为踏上非『原本』的道路，才会接连遭遇窒息般的痛苦、锥心的疼痛、蚀骨的悲伤、令人发狂的艰辛，甚至比死亡更绝望的境遇。

但比起这些磨难，更重要的是我获得了、抓住了某些东西。

虽不知『原本』会是怎样，但能选择现在的自己真好。

所以佩特拉・雷蒂能由衷地说：

「哪怕人生能重来千百次，我也要再次偏离『原本』」

并且无论多少次都想要遇见你，告诉你：

因为那个与你承受相同痛苦的人，正满身伤痕地渴求着星辰。

佩特拉・雷蒂在此——

２

——向神明、佛祖、欧德・拉格纳大人起誓。此生绝不目送任何人离去。

△▼△▼△▼△

「——哈」

她狠狠吐息，猛蹬坚硬岩地，不顾一切地狂奔。

矫正姿势、前倾身体，以连自己都着迷的理想起跑姿势，用这辈子最快的速度跑着、跑着、跑着、跑了。

咚咚作响的血液流动声吵得人心烦，仿佛要爆炸般剧烈跳动的心脏从内侧捶打着胸膛，连自己粗重的喘息都被甩在身后，就这样奔跑着。

即使拼尽全力奔跑也──

「──Play Ball」

当这句冰冷宣告触及后背的瞬间，视野骤然剧变。

回过神来，这辈子跑得最快的双腿已然停驻，只能呆立在岩场上。眼前本该背对的熟悉光景中，铁盔男人低语着。

「──领域展开，矩阵再定义」

这是用漆黑头盔遮住面容的男人，动用权能开始某种谋划的信号。

此刻因对方的宣言而开启，而在自己视野中，不明就里的同伴们正爆发出震撼大气的怒吼。

「干掉你们这群混蛋!!」

「「──噢!!」」

以勇猛少女的呐喊为中心，整支队伍的士气高涨到极点，随即爆发。乘着这股势头，她们一齐扑向铁盔。——但是，不行。

结果早已注定。她们伸出的手无论如何都够不到对方。

「────」

如同丝线断裂般，三十七人稀里哗啦地当场瘫倒。

看似同时倒下。但其实通过细致观察每个人的倒地方式，早已知道其中存在微妙的先后顺序。不过从第一人倒下到最后第三十七人倒地，前后差距最多两秒。

根本没有介入这几秒钟的余地，那次挑战以徒劳告终。

『才不是徒劳。搞清楚这个方法行不通本身就不是徒劳』

正当干燥的感想掠过鼓膜时，声音响起——不，并非鼓膜。这声音与真正通过空气振动传来的不同，所以被震动的并非鼓膜。

既然不是鼓膜在震动，那到底是什么在震动呢。

『还用说吗，是心啊』

心。──没错，没错。正是如此。因为心灵在震颤，所以能听见。

内心依然留有震颤的余地。仿佛证明这点般，他就在那里。

那个，他的名字是──，

「──昴」

『啊哈，确实在这儿呢，佩特拉』

听到他唇间唤出佩特拉这个名字，她松了口气。

没错。我是佩特拉・雷蒂，依然还好好保留着这个名字。

既然如此，所以，倘若如此，那么，这样的话，正因如此。

「──比赛开始」

──佩特拉・雷蒂还必须继续这场地狱巡游。

３

──神明大人，佛祖大人，欧德・拉格纳大人。我发誓终生不接受任何人的施舍。

△▼△▼△▼△

「──领域展开，矩阵再定义」

「──比赛开始」

从这句宣言开始，又以那句宣言终结的短暂时刻。

佩特拉被困在不足一分钟的循环里，究竟度过了多少时光。

「……啊咧，其实连一秒都没过去呢」

她在心中如此吐槽自己的低语，佩特拉「哈」地漏出沙哑的喘息。

连我自己都觉得那是极度讽刺、自嘲、看破红尘的嘀咕。没想到自己能发出如此被漆黑感情玷污的声音，甚至为此感到惊讶。

但这绝非什么误会，或是听错了谁的声音。

因为在这里──

「能听到的只有我、那些人、那个男人，还有昴的声音而已」

扑通一声跌坐在地，佩特拉把额头抵在抱紧的膝盖上嘟囔着。

眼前，三十七人的集团正要扑向那个戴头盔的独身男子，无声无息遭反杀的场面又一次上演。

真是疯了。为什么就是不明白呢。

「大家是不是都傻啊？明明知道会被干掉，为什么连对策都不想就直愣愣地扑上去呢……」

看，又被干掉了。噼里啪啦地，全倒下了。

这已是司空见惯的景象，比早晨电视节目英雄时段里，那些被正义伙伴反复打倒的反派更滑稽的模样。

无数次、无数次、无数次无数次无数次、无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次无数次──。

「──简直蠢透了」

明明应该也有聪明人混在里面，为什么、到底为什么、就是不肯动脑筋。明明都被整过那么多次了，为什么、就不肯试试别的方法。

我懂的。那些人根本没意识到自己被整过多少次。他们不知道被整过多少次，也不明白今后还会被整多少次。

既然不知道未来会发生什么，被显而易见的后续发展吞噬也是没办法的事。这根本就是在迁怒。蛮不讲理。荒唐至极。我都明白。虽然明白。

「可大家都是大人了，快想想办法呀……」

向着屈起的膝盖，一次又一次、一次又一次、用额头狠狠撞去。

好痛。不痛。好痛。不痛。好痛。不痛。好痛。不痛。好痛。好痛。

「啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊「──play ball」啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

×　×　×

啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊「──领域展开，矩阵再定义」啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊」

循环的终点与起点，无论在何处发声都成功了。所以？

「喂、怎─么了!?」

「佩特拉！怎─么了、谁对你做了什么!?」

「退下，佩特拉！你可是拉姆她们的要害啊！」

面对佩特拉突然发出怪声的异常举动，正欲扑向铁盔的同伴们猛然停住动作，脸色大变地惊呼起来。察觉到佩特拉的异状，众人立刻用最鲜活的声音表达关切，试图用话语安抚她。

好开心。谢谢。最喜欢大家了。真的。真的。但是，不要。

「……我全都知道哦？」

我知道佩特拉这样慌乱时，大家会说什么样的话。

我知道当佩特拉拼命解释循环时，大家会一起苦恼地思考。

我知道当佩特拉提出用『压缩』让全员分散逃跑的方案时，大家会认真倾听。

知道。全都知道。看过、听过、说过、教过、传达过、商量过、思考过、烦恼过、挑战过、尝试过、努力过、放弃过、捡起过、又丢弃过。

「说点不一样的话嘛。给我看点不一样的嘛。不一样嘛。刚才也好、之前也好、下次也好、这回也好、做点不同的事情嘛……！」

佩特拉把脸皱成一团，露出丑陋至极的表情，声音也难听地嘶哑着，指甲都快剥落般抓挠地面，发出不明所以的吼叫。众人顿时哑然，立刻锁定了原因，将怒火的矛头指向铁盔男，龇牙咧嘴。

「佩特拉，站起来。拉姆会扶着你的」

扑向铁盔的人群中，有一个人抽身向佩特拉伸出手。

好温柔。即使在这种状况下，即使声音和表情都很严厉，手的动作却很温柔。最喜欢了。

「但是呢」

「──比赛开始」

×　×　×

「──领域展开，矩阵再定义」

看，皱成一团的脸也好，剥落的指甲也好，沙哑的声音也好，全都恢复原状。

为我担心的心情也好，涌起的义愤也好，对妹妹的忧虑也好，全部重置。──被重置后，用全新的心情，再次享受新的开始与终结吧。

「来吧，你们这群混蛋!!」

「「──噢!!」」

大家真好啊。能用清爽的心情，再次那样痛快地呐喊。

做不到。我做不到。明明试着一起努力过，也一起努力了上百次。但什么都没改变，大家也都先倒下了，翻着白眼，太狡猾了吧。

「要不，我也耍个赖吧」

撅起嘴唇，稍微说了这样的话。

就在这期间，大家不知不觉都睡着了，佩特拉面前，伴随着杂乱的脚步声，一个摆弄着自己头盔金属扣的男人正靠近过来。

「────」

男人缓缓地，将那摆弄金属扣的手伸向佩特拉。

我在想啊，那个头盔真的有好好保养吗。上油啊，干擦啊，不维护可不行吧。感觉是一直战斗连澡都没洗过的对手呢，这样的手伸过来，稍微有点抗拒呢。但是，忍住。忍住忍住，等着那只伸过来的手碰到。一直盯着看的话会很难办吧。那就闭上眼睛，趁这期间抓住我吧。好，一——，二——，三——……。

×　×　×

「──领域展开，矩阵再定义」

对吧。我就知道。被抓到也不行呢。啊哈哈，去死吧。

４

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓这辈子绝不提失败经历。

△▼△▼△▼△

「──领域展开，矩阵再定义」

以此为信号开始的循环，当佩特拉意识到自己被卷入其中时，即便面对这种异常事态，她也保持着惊人的冷静没有慌乱。

当然动摇是有的，但比起预想中的程度要轻微得多。

因为──

『佩特拉！我们在短时间循环里！阿尔用的招式跟刚才不一样了！』

代替佩特拉喊出这句话的，是和她共享着同一段循环、唯一理解时间重复流动的幻影菜月昴。

这个『昴』的存在，以及被卷入前最后看到的罗姆爷留言──地面上刻着的某种计数标记，共同压制了佩特拉的动摇。

「罗姆爷爷也经历过和我现在相同的处境」

在一根横线上叠加四根竖线的那个，是被称为『画线法』的计数记录方式，如果用汉字表示一般会用「正」字。

罗姆爷通过将它写在地面上的方式，试图传达自己所处的状况──毕竟很难想象仅仅五次他就变成了那样，所以他想表达的是陷入了循环。这对陷入同样状况的佩特拉来说或许已经是迟来的信息，但并非如此。

罗姆爷的信息，是警钟。──也就是说，罗姆爷想说的是。

「如果一直重复下去的话，就会变得像罗姆爷爷一样哦」

罗姆爷被卷入了循环，在重复的时间中被消磨殆尽。

那正是佩特拉他们对阿尔使用的战术本身，简直可以说是被以牙还牙了。虽然没想到连报复都在阿尔的算计之内，但如果毫无心理准备就陷入同样状况的话，佩特拉或许也会走上和罗姆爷相同的命运。

『不，不只是罗姆爷。从那个感觉来看，拉姆她们也是』

「……是啊。阿尔先生对扑过来的大家也施加了同样的权能……不过，循环开始的时机，大家也都还有意识对吧？」

『有啊。……虽然是重复的状况，但好像也会反映循环外实时发生的事情？比如被干掉的人就会退出循环之类的？如果是那样的话』

「──现在，只剩下我了」

『昴』说出的内容太过绝望，佩特拉不由得绷紧了脸颊。

如果假设在这个循环轮到佩特拉时，『阿尔德巴斯特』的伙伴们注定败北的命运已无法改变的话，

「就算这个循环结束也……」

『等等等等，别这么悲观。就算……就算是那样吧？我们还有『忧郁』的权能。用它来『压缩』冷却时间之类的』

「……把昏迷时间『压缩』，让大家一次性醒过来？」

『没错！虽然没试过，但要是能成功不就超厉害吗？』

听到『昴』打响指提出的点子，佩特拉嘴角微微放松了些。

说实话，那挺难的。虽然能用权能『压缩』商量时间和学习新技术的时间，但那需要相应的能量。

简而言之，如果把佩特拉的一天『压缩』掉，就会消耗掉一天份的能量。

如果是三天就压缩三天的量，七天就压缩七天的量。倘若要修复这颗磨损的心需要一个月、甚至以年为单位的时间，那根本没法提供『压缩』所需的能量。

『压缩』也绝非万能之力。──不过即便如此，

「──嗯，我觉得超级厉害哦。说不定能行呢」

『对吧？所以首先要在脑子里刻下这点。脱离轮回后，第一件事就是让倒下的大家站起来。不然的话一下子就会被压制住』

我向积极设想轮回结束后发展的『昴』点头回应。

这样回头想来，恐怕罗姆爷也产生了同样的念头。又或者那位贤老即便心灵磨损殆尽，也会无意识地将书写地面信息作为第一要务，通过无数次重复将这个行为烙印成本能，从而规定每次轮回苏醒后的行动。

若是如此，就该采纳『昴』提出的预先确定轮回苏醒后行动的方案。

只是──

「……罗姆爷爷究竟重复了多少次，才让身体记住这个动作的？」

即便心灵支离破碎到无法维持自我意识，罗姆爷仍坚持在每次轮回后第一时间用手指抓挠地面。要让这个动作成为本能，铭刻进灵魂深处，变成心灵崩溃后仍能执行的机械行为，究竟需要经历多少次轮回的累积。

「────」

『佩特拉，我们来验证吧。之前碧翠子曾设计过让我在相同走廊无限轮回的机关。如果规则相同，要终结轮回就必须满足特定条件』

看着喉头『咕噜』滚动吞咽口水的佩特拉，『昴』这样宣告着后续方针。佩特拉回以「嗯」的轻快微笑并点头，重新将视线投向正前方。

「看招吧，你们这群混蛋!!」

「「──噢噢!!」」

就在刚才佩特拉与『昴』对话的间隙里，『阿尔德巴斯塔』的同伴们不断向阿尔发起挑战，然后在他面前接二连三倒下的场景仍在循环上演。

老实说，我真心尊敬『死者之书』中那个认真对待每次轮回、将所有经历都深深烙印在心里的昴，也觉得那样很帅气——但要在不满一分钟的循环里做到同样的事实在太难了。

『俺也觉得啊，这种情况下要求你每次都为同伴的死痛苦挣扎确实强人所难。但还是要好好记住』

「重复的次数？」

『这也包括在内，更重要的是佩特拉每次愤怒、懊悔、悲伤的心情』

「──嗯，说得对」

在这个不断重复的世界里，在无数次的轮回中，能继承这份感情的只有自己——所以要像『昴』说的那样，牢牢记住这一切。

就算阿尔不知道脱离循环后佩特拉他们遭遇了什么，我也绝不会原谅他。一定要让他知道我们承受了多少痛苦。

怀揣着这份誓言，佩特拉与『昴』互相点头示意，面向前方。

「是星星。──都是星星的错」

然后与迎面而来的阿尔正面对峙──，

「──比赛开始」

『「──比赛开始」』

就这样，她英勇地宣告了地狱巡游的启程。

５

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓这辈子绝不让任何人给我梳头。

△▼△▼△▼△

──于是佩特拉在这片下定决心闯入的地狱中持续徘徊。

「……该怎么办才好？」

抱膝蹲坐着，把额头一次次撞向膝盖，反复自问自答。

该怎么办。该做什么。怎样才能结束这个循环。

「条件是什么？」

结束循环需要条件。──那个人曾对佩特拉这么说过。

佩特拉也持相同意见。这类不断重复相同情境的套路中，某种终止条件被触发是既定模式。这是惯例。是规定好的。规则、既然是规则就必须遵守。不行。应该遵守了。正因为遵守着，所以肯定有正确结束的方法。好，到此为止。这个讨论结束了。既然已经结束，就来思考条件吧。终止的触发条件，有哪些？

「各种方法都试过了哦？」

她运用『压缩』能力，理应比普通人尝试了更多种挑战。

既和同伴们合作击败过铁盔，也因「不能打倒」而用『压缩』让全员逃脱。当然，佩特拉自己也尝试过逃到极限距离，故意被铁盔最后伸出的手抓住过，甚至主动跳进铁盔臂弯里过。都没用。

我们考虑到每个同伴都可能持有某种突破方案，于是尝试了全员讨论、深入剖析个人情况、互相坦白秘密、倾听各自的家庭背景、出身和故乡故事，甚至进行了连十年老友都不会涉及的对话交流。没用。

索性尝试直接攻略铁头盔吧——和铁头盔交谈、冷落它、在没有同伴的情况下单挑胜负、在不使用『压缩』的状态下对决、逃跑、嘲弄、夸奖、无视。毫无意义。

「那到底要怎么办才好啊!?」

试过了。不是都试过了吗。能想到的法子全都轮过一遍了不是吗。试了也是白费功夫不是吗。试了也没用不是吗。试了也毫无意义不是吗。

「看招吧，你们这群混蛋!!」

「「──噢噢!!」」

「吵死了!!」

明明什么都做不到，还元气十足地大喊大叫真让人火大。不帮忙的话至少别妨碍我思考。啊，我在迁怒。讨厌讨厌，最讨厌这样的自己。根本不想这么想。什么啊，装什么乖孩子？这才是真正的我吧。根本不是什么喜欢大家。只是喜欢那个说着最喜欢大家啦心胸宽广慈悲为怀温柔平等装模作样的自己而已对吧对吧。

「吵死了吵死了吵死了吵死了吵死了……」

右边左边上边下边前边后边过去未来现在今天明天昨天后天大前年去年今年来年前世今生来世全部所有一切统统都吵死了。

「──现在，第几次了？」

烦死了。去死吧。不然，杀了你哦。

「接关啦」

早知道了。

×　×　×

「──领域展开，矩阵再定义」

又回到老地方。惊讶吧？偶尔也会说些开场白以外的台词呢。

ループしている间、みんなそこにあるただの操り人形じゃないから、何か言ったら反応してくれるし、何かしたら応えてくれる。みんなだけじゃなく、鉄兜も同じ。

虽然理所当然，但我遭遇了什么，铁头盔是知道的吧。

「所以呢？」

就算明白了，世界终结、下次开始时连幕后黑手都不会跟来。

佩特拉总是独自一人，不断重复着同一个世界。没有人、没有任何人能理解佩特拉的苦恼与挣扎。一个人、就一个人。孤零零的。是孤零零的吗？

「──呜、昴！　昴！?　在哪里！?　到底在哪里！?」

『佩特拉！』

就像被闪电击中般突然想起的瞬间，那道身影哗地出现在佩特拉眼前。看到那张脸，确认了那确实是昴之后，佩特拉呼出了憋着的那口气。

虽然觉得所有的一切都快要模糊消散、快要无法理解了，但即便如此也并非全部遗忘，也并非被抛弃。

「昴……呜」

她挂着哭唧唧的表情，任由瞬间涌出的泪水弄脏脸庞，朝他跑去。飞扑过去。他慌忙伸出双手，试图接住佩特拉。──但没能接住。

穿过去了。她直接摔在空荡荡的地面上，连防护动作都没做。好痛。脸撞到了。昴──不对，是『昴』，没有接住佩特拉。理所当然。一直都是这样。因为『昴』的双手，永远被其他人占满。

「那就别伸手啊！」

『佩特拉……』

「那样就好……就那样放着不管，让我死掉不就好了。在村子里，什么都不做，被魔兽杀死不就好了……」

她知道的。如果菜月・昴什么都不做，佩特拉早就死了。

本该死去，却活着。被迫活着。因为被迫活着，才会像这样遭遇痛苦，承受疼痛，却连结束都做不到。

『对不起，佩特拉……对不起！但再等等！别那样说……』

「哈、哈啊!? 什么意思？我都这么惨了还要骂我!? 都这么、一次又一次、一直这么痛苦，哭个不停……还、还要骂、骂我？要骂我吗？哈、啊哈、啊哈哈、别这样啦!!」

大声吼了出来。这下爽了。——这下完蛋了。

露出沉痛表情的『昴』站在那里，佩特拉气得想吐血。想挖出自己的心脏。想把脑袋轰飞。不对，就这么干吧。

「结束轮回的，最直白的触发条件……」

边说边比出手枪姿势，食指抵住自己太阳穴。指尖开始聚集魔力，朦胧的白光淡淡亮起。

见状『昴』慌忙伸手。反正也碰不到。看吧，挥空了。

『等等佩特拉！别冲动！我懂但我懂你先别用这方法！万一这正好中了对方的计……』

「那就和我结婚啊!!」

『──』

「嫁给我吧！当我的昴吧！当第一的！既然救了我就要结婚！把我整个人生都抱走吧！我的命也变成昴的吧！那样就好啦。但不是吧？那就不是我的命。要是我的命的话，让我自己决定怎么用嘛」

连我自己都不知道在说什么。

总之就是气得要死。没一件事顺心。对什么都帮不上忙的大家生气，对造成这种局面的铁罐头也生气。讨厌死了。最讨厌了。但是喜欢昴。哈。搞不懂。明明什么都不肯为我做。可是一直都在为我做点什么，现在也在想办法不是吗。虽然不肯结婚。

「什么啊，傻乎乎的」

『佩特──』

啊，不是啦？不是说昴哦？因为傻乎乎的是我嘛。

啊—啊，这种脑袋已经不需要了吧。拜拜。

这么想着，手指枪「biu」地射出白光──

×　×　×

「──领域展开，矩阵再定义」

────。

────────。

────────────对吧。早猜到了。

啊哈哈哈哈。啊哈哈哈哈哈哈。啊哈哈哈哈哈哈哈哈哈哈。

６

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生绝不奢求幸运。

△▼△▼△▼△

──『忧郁魔女』佩特拉・雷蒂怀着不可动摇的决心投身战斗。

从柯林特处继承的魔女因子，其带来的『忧郁』权能可能性远超常规，甚至让人不禁认为——在构建有利于自己的战局方面，这世上恐怕不存在比此权能更优秀的战力了。

当然，要驾驭如此力量就需要付出相应代价。——正所谓"能力越大责任越大"，虽然可能有点偏差。

无论如何，既然甘愿承受这般巨大缺陷，就必须让优势充分发挥作用。否则下定连至亲都要持续欺骗之决心的佩特拉就太不值了。

「法兰黛莉卡姐姐不在真是太好了」

如果『阿尔德巴斯塔斯』中有法兰黛莉卡参战的话，佩特拉能否将谎言坚持到底就不好说了。与其说是法兰黛莉卡的洞察力，不如说佩特拉对法兰黛莉卡毫无招架之力。

面对这个凭实力赢得自己最高敬意的法兰黛莉卡，佩特拉根本藏不住秘密。肯定会把心底话全倒出来，对着法兰黛莉卡哭哭啼啼撒娇依赖。

单论隐瞒真相这点，全盛期的拉姆和奥托也同样棘手。只不过因雷姆复活而飘飘然的拉姆，以及失去『记忆』的奥托当时都无法发挥原本的洞察力，才没识破佩特拉的谎言。

「柯林特哥哥大人究竟看穿了多少又放了我一马呢」

年龄不详真意难测、仅凭「是同伴」这点值得信赖的柯林特，就算完全看透佩特拉的盘算也不奇怪；反过来说，正因为和罗兹瓦尔交情甚笃，就算他对人心微妙处毫无察觉也实属正常。

无论如何，柯林特从一开始就知道佩特拉付出了巨大牺牲。

既然已经一次性支付了大笔代价，那么不再额外奉献也好，认为付过一次就等于持续奉献也罢，这两种立场都能成立。

既然如此，佩特拉觉得不如默默接受这份觉悟来得干脆。

无论柯林特的真实意图如何，佩特拉既然已经掷出了骰子。

「现在、掷到几点来着……」

不饮酒。不写信。不抱玩偶。不动针线。不唱歌。不陪孩子玩耍。不造访回忆之地。不摘美丽的花朵。不碰喜爱的食物。不归故乡。不在人前落泪。不为他人拭泪。不谈往事。不讲心爱的故事。不用昵称唤人。不邀人进家门。不陪谁走完最后一程。不握任何人的手。不指望关系修复。不为谁动怒。不透露秘密。不向任何人示弱。不与谁共赏朝阳。不挑三拣四。不为谁哭泣。不奢望星辰。不与人相约。不在夕阳下漫步。不踩同行者的影子。不留恋离别。不谈梦想。不参与庆祝。不送礼物。不挥手道别。睡前不祈祷。不抚慰伤痕。不为晴空欢喜。不为雨天叹息。不仰望彩虹。不欣赏寂静。不违背约定。不渴求善意。不送别启程之人。不接受施舍。不谈失败经历。不让任何人束发。不祈求幸运。──太多了。

若细数献上的代价便永无止境，佩特拉的人生可谓一片黑暗。

「即便如此，这已经算是相当不错的状况了」

高明谎言的诀窍，在于将真实的要素混入谎言之中。──虽说是老生常谈，但佩特拉的谎言最终却呈现出与之相似的微妙效果。

──由持有者佩特拉之外的众人共同分摊支付『忧郁』权能的代价。

这正是大家同意让佩特拉持有魔女因子的条件，但这种方法能作为代价适用的，仅限于以权能效果对象为中心的『压缩』。

若是爱蜜莉娅所期望，且为移动爱蜜莉娅而施放的『压缩』，便可从爱蜜莉娅处支付代价发动；但若是佩特拉因认为爱蜜莉娅有危险而用『压缩』移动她，则需由佩特拉支付代价。──这一点，除持有者外无人能察觉。

『阿尔德巴斯塔斯』的每一次商议也好，将阿尔连同爱蜜莉娅和雷姆一起抛到阿格扎德溪谷时也好，危急关头猛然拽回同伴时也好，将全员承受的剧烈痛苦『压缩』至刹那瞬间时也好——这些代价都是由佩特拉支付的。

想来，越是献上珍贵之物时，『忧郁』权能的效果容量就越大。

这既是对世界的影响，同时也源于佩特拉对世界干涉力的减弱。或许单纯就是，倘若佩特拉献上整个人生的话，『忧郁』的魔女因子将会带来更强大的力量。

「不过，我不会那么做」

即便权能逐渐侵蚀佩特拉・雷蒂——让她像零碎出售自己的人生般削减未来期许，放弃诸多幸福——她也绝不会自暴自弃地豁出性命，做出极端选择。

「因为那样太逊了嘛」

不想让人看见逊爆的样子。不想做逊爆的事。

和『暴食』大罪司教、罗伊・阿尔法德战斗时的感觉一模一样。──只要这份心意还在支撑着，佩特拉就不会迷失自我。

因为佩特拉，佩特拉・雷蒂是向着星辰──

７

──神明啊、佛祖啊、欧德・拉格纳大人啊。我发誓此生绝不支撑任何人的后背。

△▼△▼△▼△

「──领域展开，矩阵再定义」

为什么非得让我遭遇这种事不可？

我做错什么了吗？我一直是个好孩子对吧？我一直努力当好孩子对吧？

为什么、怎么会变成这样，谁来、好好地、给我说明啊。

「看招吧你们这群混蛋!!」

「「──噢!!」」

到底要怎么办才好？能做的我都做了？重复尝试了多少次？

想到的办法全都试过了。战斗然后胜利过？战斗然后失败过？战斗然后杀死过？不战斗就死掉过？逃跑过？哭泣过？

「是星星啊。──都是星星的错」

尝试过很多次死亡。尝试过很多次击败。尝试过很多次逃跑。

无数次道歉过。无数次愤怒过。无数次流泪过。

真的、好害怕啊。真的、好痛啊。真的、好难受啊。

「──Play ball」

我早知道的。永远不会结束对吧。根本不会为我停下对吧。就算现在听到这个瞬间的我哭喊得撕心裂肺，就算有人担心我，只要十秒钟就会忘光光对吧。不对，不是忘记。是根本不曾知晓。是把我抛在脑后。只有我、被留在原地。

「──领域展开，矩阵再定义」

已经受够了。我讨厌所有人。最讨厌最讨厌、超级讨厌。

为什么不救我？明明我拼了命在呼救，为什么啊？

不会结束。永不终结。不肯停下。不让我解脱。我、直到此刻依然。

「看招吧你们这群混蛋!!」

「「──噢噢!!」」

无论哭泣、嘶吼、吵闹还是诅咒，都只是重复相同的轮回。

真厉害。是我搞错了。居然妄想能解决什么的，真是太自以为是了。我那些、可靠的、可靠的？明明什么都没为我做过的？算了无所谓。那些可靠的同伴们来着，都有谁来着。那个女强人什么的明明那么厉害，为什么就是跨不过这道坎呢。

「是星星啦。──是星星、太坏了」

但是呢、我懂的。我明白的。因为没办法嘛。脑子越来越越来越、转不动了嘛。对眼前的事、渐渐失去兴趣了嘛。不对哦。不是失去兴趣、而是自己在主动远离。这么做的理由、我也懂的。

「──Play Ball」

因为、我不想讨厌大家嘛。但是、想着大家的事情时、就会对什么都不为我做的大家产生讨厌的感觉。所以不去想。不去思考。为了不讨厌大家、干脆不再思考。大家的事情什么的、不去想。大家的事情我才不知道。啊、不对不对。抱歉抱歉、骗你的骗你的、最喜欢了。来、最——喜——欢。

「──领域展开，矩阵再定义」

因为没办法呀。毕竟还是个孩子嘛。就算踮起脚尖、也没法一跃变成大人呀。要是永远永远、停留在这个重复的时间里、总有一天能长大吗？很遗憾并不能哦。因为只是重复相同的时间嘛。再怎么努力都一样嘛。既然努力也没用那干脆别努力了不好吗？

「看招吧、你们这群混蛋!!」

「「──哦哦!!」」

对对，努力也没意义的。都是一样的。哈啊，努力反而吃亏了。还是别想那么复杂了吧。哈啊，努力反而吃亏了。一点意义都没有。我啊，一直在做徒劳的事呢。对吧。是这样吧。我早就知道了。

「是星星。──是星星的错啦」

说到底，努力也没用啊。就算努力，我也不可能成为国王。不可能被重视。也不可能和那个人结婚。所以，已经没办法了。真的没办法了。

「──比赛开始」

既然没办法，那就放弃吧。

『──才没有什么没办法』

为什么？

『放弃啊，说起来不容易。......但其实很容易』

为什么？怎么回事？

『说什么心灰意冷啊、自我毁灭啊，都只是擦伤程度的小事』

为什么？怎么回事？你还能说这种话？

『因为』

为什么？怎么回事？你还能说这种话？然后呢？

『因为──』

为什么？怎么回事？你还能说这种话？然后呢？接下来──？

『──我们还能继续。小菜一碟』

────────。

────────────。

────────────────真是的，撒谎技术有够烂呢。

早就知道了。

△▼△▼△▼△

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生永不放弃。

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生绝不屈膝。

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生无悔选择。

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生不流悔恨之泪。

──神明大人、佛祖大人、欧德・拉格纳大人。我发誓此生不忘所爱。

８

──佩特拉・雷蒂是出身于露格尼卡王国阿拉姆村的乡下姑娘。

『原本』的佩特拉并非会参与决定世界大势之战的女孩。

作为一介村姑，要么凭可爱与小聪明过上稍好的生活，要么被时代洪流吞噬凄惨丧命。本该仅此而已。

但偏离了『原本』路线、知晓如今自我的佩特拉如此想着。

「就算能重来无数次人生，我也还是会偏离『原本』路线吧」

对、对了。偏离『原本』，佩特拉终会再次回到这里。

然后，我想说。对将佩特拉从『原本』的道路上拉离、拯救了我的你。

对露出痛苦表情，用拙劣谎言拼命想牵起我手的你，我要这么说。

「──托星星的福，我才能在这里」

「────」

『────』

说着用手背擦拭嘴唇的佩特拉，让阿尔和『昴』哑口无言。

阿尔暂且不论，我明白『昴』沉默的理由。他大概以为自己用拙劣的谎言和鼓励，让佩特拉沮丧到说不出话了吧。

确实，那是拙劣的谎言。虽说掺点真话才是高明谎言的诀窍，但这个连半点真实都没有的谎言，堪称最差劲的。

「但是，我不想让自己喜欢的人成为骗子」

所以，我重新站起来了。靠自己的力量。因为安慰和鼓励都靠不住，因为你一直用担心的眼神看着我，明明触碰不到却想抚摸我的头、想支撑我的后背，看到你这样坚强又拼命的样子，我只好投降了。这就是爱上你的弱点吧。

「我喜欢的人啊，可是从不说谎的哦」

你看，我这不是站起来了吗。因为佩特拉站起来了，所以昴没有说谎。

轮回的世界很痛苦。让一度濒死的心重新振作并非易事。不如说，这是我人生中最艰难的事。但是，我站起来了。真的站起来了。因为就在那里，有个始终相信着最最新鲜出炉的、软趴趴弱兮兮的佩特拉的人。

「我的星星啊，一颗坏掉的都没有呢」

好厉害。必须努力才行，真不容易。明明我算是手巧的类型。明明是做什么都能很快上手的类型，但要满足这个人的期待，真的超难。不过，正因为这个人毫无根据地相信着「佩特拉才不会输！」——哪怕是在足以让任何人精神崩溃倒地不起、被迫重复几百次几千次几万次相同事情的地狱里——所以只能拼了吧。

既然菜月・昴相信佩特拉・雷蒂是能在几万次循环中都不崩溃的坚强女孩，那就这么做吧。

「异世界的女孩子啊，要是连奇迹都不能自己创造的话可混不下去哦」

若不做到偏离所谓『原本』命运轨迹的程度，就连发自内心觉得可爱的对象都遇不到。

「──阿尔先生，不管你重复多少次都是白费功夫哦」

打断那些关于星星责任的套路台词后，佩特拉对沉默的阿尔说道。

这不是逞强也不是虚张声势，而是佩特拉的真心话──即使这个时间重复的不是几万次，而是几亿、几兆次，也无法将佩特拉磨损殆尽。

说什么女孩子的爱是无限的──也和童话般的解决方法不同。

「这个循环是要重复到阿尔先生的敌人心力交瘁为止对吧？」

无论战胜阿尔、杀害阿尔还是将阿尔抛到遥远彼方，循环都没有结束。

无论输给阿尔、被阿尔捕获还是试图逃往远方，循环都没有结束。

无论自杀、让人杀死自己还是绝望地放弃一切，循环都没有结束。

单纯重复上万次后，循环依然没有结束。

「但是啊，该在哪里收场应该是由阿尔先生决定的吧？」

要让永不结束的循环终止，除了阿尔主动解除『领域』外别无他法。

说什么对象精神崩溃就会自动结束，哪有这么方便的循环。每次终止的时机，应该都是身处循环中的阿尔有意识地做出的选择。

究极、只要让阿尔发出认输的声音，别说一万次，就算第一次也能终结这个循环。──前提是能让那个永远初次登场、谨慎又胆小的阿尔做出这个决定。

「所以啊，我希望你能在这里收手。除了我以外大家都已经倒下了，小路的战果已经很够了吧。再继续下去也没有意义了」

我再重申一遍，佩特拉这可不是虚张声势也不是逞强。

照这个节奏无限循环下去，佩特拉的心也不会崩溃。

因为、佩特拉已经选择了。

「我呢，已经无法放弃，也不能后悔，就算不甘心也哭不出来，更忘不了最喜欢的大家。──就这样成为了这样的『魔女』」

──佩特拉・雷蒂之所以选择成为『忧郁魔女』。

「呐，阿尔先生。──这个故事，还要讲多少次？」

面对『忧郁魔女』歪着头提出的疑问，眼前的阿尔喉咙轻轻颤动。

铁盔深处，他那看不见的眼瞳中，我察觉到黑沉沉的情感在『忧郁魔女』浑圆眼瞳的深处翻涌，仿佛窥见了某种不可名状之物。那或许与阿尔心中深深扎根、无法抹去的伤痕有关。

说不定他从前也曾深深凝视『魔女』的双眸，因而受过伤害。

将那份创伤──

「──『压缩苦痛』」

把阿尔背负的创伤『压缩』后狠狠灌入。

脑髓沸腾，血液逆流，喜悦悲叹幸福不幸全数搅碎，剥开那从未愈合的伤口结痂，往上面涂抹的不是盐而是创伤。

将这份未来人生中会让他想起数十次数百次数千次、每次都以泪洗面的创伤刺激，在此刻以数千倍的浓度逼他咽下。

「──啊」

刹那间，阿尔对『忧郁魔女』的恐惧与被刺激的创伤『压缩』产生反应——不是肉体的反应，而是灵魂向着触手可及的最近救赎伸出双手。

换言之──、

「──游戏结束！」

让无尽循环终结的方法，就是开启下一个循环。

怀揣这份确信，『忧郁魔女』将手搭在身旁意中人无法触碰的手上，十指交缠着露出微笑。

「真逊呢。──换作昴的话，这种心灵受挫的擦伤肯定会逞强说根本不痛」

『你呀，实在是帅气过头了，佩特拉』

她听见意中人用虚弱却自豪的语气如此说道。

『忧郁魔女』内心充盈着这份情感，却依然直面着你。

漫长到足以摧毁心智的重复时光终于落幕。然而，她心中毫无感慨。

受伤的心灵、渴望终结的软弱、不甘的泪水——这一切都已被献祭为代价。──以此为交换，『忧郁魔女』迈向了未来。

９

──解除『领域』，重新编织，再度构筑矩阵。

这意味着承认了本该必胜的『领域』强加于人后的必然败北。

但这也是无可奈何。早有先例。『领域』无法杀死身为加害者的『魔女』。

当然、所谓杀戮不过是权宜之计，瞄准的目标始终仅限于心灵──

「────」

堂堂正正地宣称要挺过『领域』的佩特拉──不、已经不能再简单地称她为佩特拉了。她毫无疑问地、彻底堕落变质了。

「──『忧郁魔女』」

过去，击败阿尔德巴兰『领域』加害者的，是『强欲魔女』。

回想起来，阿尔德巴兰的权能无论在『领域』主导权属于受害者还是加害者的模式下，都会在必须取胜的关键对决中落败，实在不吉利。

总之、即使现在『领域』被弹开了、战况仍是阿尔德巴兰更有利。

「──呜」

『忧郁魔女』之外、以讨伐阿尔德巴兰为目标的『阿尔德巴斯塔斯』已全军覆没、很不巧『领域』造成的精神损耗是绝对的。阿尔德巴兰可不是用演技或装死就能糊弄过去的半吊子、他早已下定决心要强行展开『领域』。

按理说，本该是在确认过目标断了一两只手脚后，才做出将『领域』转移到下一个目标的判断。由于自我缺乏连续性，无从得知自己用何种方式确认这点，但既然现在的自己能想到，循环中的自己必然也能想到。

所以可以笃定地说。──除了『忧郁魔女』外，谁都站不起来。

「不过，那边也心知肚明」

阿尔德巴兰可不会天真到以为既然自己能站起来，其他同伴也该站起来，就这般低估眼前的『忧郁魔女』。

既然如此，必然存在。『忧郁魔女』手中握有从这里逆转的策略。

──那张声称托星辰之福才有今天、甚至沦为『魔女』仍强颜欢笑的少女的底牌。

「────」

『领域』解除的瞬间，阿尔与『忧郁魔女』短暂获得自由，双方距离约五米，但在对方权能面前等同虚无。不，既然拥有『压缩』这类权能，距离根本不足为恃。

──但，终究是权能。

『忧郁』的权能，对方肯定会将这张牌打出来。

权能效果中最有可能的，当然是通过『压缩』召唤他人。

可能性是──

「──雷姆小姑娘，或是梅莉小姑娘。再不然，就是边境伯老爷？」

当考虑此刻不在场、且『忧郁魔女』能调动的战力时，最先想到的就是这些人选。雷姆应该正与八重激战，但既然拉姆没有表现出动摇，说明她尚未通过共感察觉到败北的滋味。虽难以想象那个八重会落败，但现在必须考虑这种局面。率领魔兽的梅莉，以及在帝国横行无忌的怪物级火力持有者罗兹瓦尔，都足以构成威胁。

但不论是谁，都只是单纯强大、棘手而已。

正如迄今为止证明的那样，靠数量和强度是无法逼退阿尔德巴兰的。若这就是对方的目的，未免太过肤浅──

「不对──」

阿尔德巴兰从『忧郁魔女』的瞳孔中直觉到：这些都不是正确答案。

原本，对方就能将思考过程『压缩』，导出无视时间概念的结论。连阿尔德巴兰灵光一现又立刻舍弃的想法，『忧郁魔女』也该在实施前的斟酌阶段就抛弃。——也就是说，不对。

要从根本上转变思路才能追上。

『忧郁魔女』若在此召唤，必是能打开局面的存在——

「——难道！」

咬牙切齿，瞪大双眼。瞬间，仿佛见证了阿尔德巴兰的神经突触火花般，『忧郁魔女』扬手挥下。——刹那，『压缩』发生。

此刻闯入阿尔德巴兰与『忧郁魔女』之间的身影是。

「——哇哦。比想象的更修罗场呢」

——戴着镣铐动作受制的『暴食』罗伊・阿尔法德。

10

「────」

看见罗伊坠落的瞬间，阿尔德巴兰确信了对方的意图。

对败北的罗伊存活并不惊讶。本就认为他八成还活着。

原本，要想拯救『暴食』的受害者们，罗伊的存在就是必须的。实际上，通过让他吐出雷姆的『名字』，对方应该更加确信这一点了。

暂且不论如何让他合作，如果夺走性命就无法谈判了。——在死亡的两成情况中，我担心的是要么遭遇无法生擒的激战模式，要么因为罗伊过度挑衅而被杀也在所难免的模式。

无论如何，罗伊的存活实属侥幸。——但对方的意图可不妙。

『忧郁魔女』在此特意召唤罗伊，若非单纯的资敌行为，自然有其理由。有其目的。罗伊的存在对她有利，定有密约之类的勾当。

而且，她一边阅读菜月・昴的『死者之书』，一边竟意外复活，并能从菜月・昴的知识中捕捉到『嫉妒魔女』行动的理由。只要明白这点，就能连锁性地采取行动。

那就是——

「——莱因哈鲁特！」

假设『忧郁魔女』与罗伊的密约，就是让其使用那份『暴食』权能的话，那么连『领域』都无法通用的、失去心灵的『忧郁魔女』，为了夺回菜月・昴，选择极致的自我牺牲也不足为奇。

这正是阿尔德巴兰也预想到的、通过『暴食』权能拯救世界的方式──从读过菜月・昴『死者之书』的人物身上，夺取那份『记忆』。

『嫉妒魔女』的显现，无非是为了追踪菜月・昴的『记忆』，将知晓其权能『死亡回归』的存在抹杀。若按阿尔德巴兰的计划让那份『记忆』消失，『嫉妒魔女』便不会再威胁世界。

而一旦『嫉妒魔女』收手，被牵制住的世界抑止力就会到来。

正是那位历经无数挑战与陷阱、曾一度成功击退的『剑圣』。

──只要『剑圣』莱因哈鲁特・范・阿斯特雷亚抵达，一切就结束了。

计划会崩溃。因此，阿尔德巴兰倾注全部灵魂来阻止这一切。

『忧郁』的权能将『暴食』的罗伊・阿尔法德强行召唤至此──

「──禁止吞噬『记忆』！否则咒印会烧灼你！」

一度放松的条件再次收紧。

反复变更条件对施咒者阿尔德巴兰的灵魂也造成严重伤害，体内深处的欧德出现裂痕，根源受损的灼烧感席卷大脑。

「──呃、但这样」

就能避免罗伊吞噬『忧郁魔女』『记忆』的事态。

若『嫉妒魔女』不撤退，『剑圣』也将抵达此处──

「──阿尔先生」

就在他以为成功阻止而握紧拳头的瞬间。

『忧郁魔女』呼唤了阿尔德巴兰。她本以为自己打乱对方计划会让其露出苦涩表情，此刻那张脸确实充满痛苦。

但那并非悲叹自身未来的表情。──而是怜悯着这边的神色。

「你──」

阿尔德巴兰在毛骨悚然中思考着『忧郁魔女』表情的含义。

但是，那样做是不行的。不应该去思考。比起思考，应该立刻去死。如果现在死去的话，不管那是什么，总会有办法的吧。

阿尔德巴兰在关键时刻，又没能死成。

就像让这个世界的太阳，沉落下去时那样，再来一次。

「──比赛开始」

『忧郁魔女』正要说出阿尔德巴兰的台词的那一瞬间。

──阿尔德巴兰的天敌，正站在他背后。

11

「──我可能发现阿尔先生的弱点了」

那是在『阿尔德巴兰战队』正式成立前，为打倒阿尔一伙而召开作战会议时，成为『忧郁魔女』的佩特拉所察觉到的。

罗姆爷的证言表明，阿尔的权能与菜月・昴所持有的『死亡回归』属于同类型的循环能力时，如果连发动条件都和昴相同的话，佩特拉心想那或许有办法阻止。

不过，当时还只是灵光一闪，并没有确凿的证据。

必须向本人确认那种方法是否可行，而且除了《死者之书》的联系外，佩特拉和她——不，与他的联系几乎等于零。

但倘若有可能的话，在《阿尔德巴斯特》行动前取得了联系，并约定好作为真正万不得已、将阿尔逼入绝境时的王牌登场。

然后——

「——Play ball」

无数次听到的宣告词，此刻原样奉还。《忧郁魔女》透过作为诱饵横亘在自己与阿尔之间的罗伊・阿尔法德，凝视着对方。

可悲的是，阿尔完全按照《忧郁魔女》的算计，如她所愿地行动了。

看到罗伊就会想逼他使用权能——这个与菲鲁特密约、对阿尔怀有叛意的罗伊。若在《时间溯行》中有机会探知这个事实，他本会怀疑罗伊的意图。

果然，阿尔如预期般行动，选择了封锁罗伊的背叛。

与罗伊同时现身于背后的『忧郁魔女』王牌，恐怕完全超出了所有人的预料。那个人的参战，本应是无人能预想到的。

此刻在场的『阿尔德巴兰团』六十一人，确实是爱蜜莉娅阵营与菲鲁特阵营战力的总和──这句话毫无虚假。──仅限于爱蜜莉娅阵营与菲鲁特阵营的战力。

所以──

「已经破破烂烂了喵。──帮你治好，好吗？」

霎时间，纵使寻遍整个世界也无人能及的治愈术师──『青』之菲利斯的最顶级治愈魔法，从阿尔身上夺走了『死亡』。

12

──『青』之菲利克斯・阿盖尔。通称菲利斯。

身为王选候选人库珥修・卡尔斯腾的首席骑士，王国最强──不，世界最强的治愈魔法使。同时亦是阿尔德巴兰三人天敌中的最后一人。

为了计划连菜月・昴与『剑圣』莱因哈鲁特・范・阿斯特雷亚都成功避开的阿尔德巴兰，终究未能躲过这绝不该遭遇的最后障碍。

此刻他正对阿尔德巴兰施以温柔慈悲又残酷的魔法。

「啊、嘎啊啊啊──!!」

全身寒毛直竖的瞬间，阿尔德巴兰猛地甩动身体，将站在背后的对手──菲利斯狠狠摔向地面，同时解开含在口中的毒药包。

瞬间溶解在舌粘膜上的毒药本该给阿尔德巴兰的生命机能带来致命危机，让他在数秒内死亡──却没有。理应崩坏的组织被逐一修复，就连从头盔里喷出的鼻血也在一秒内止住了。

「该死──」

他当即幻化出石龙刀抵住自己脖颈，用力划下。

粗大的血管被切断，喷涌的鲜血本该威胁阿尔德巴兰的性命──却没有。伤口瞬间愈合，痛感仅如被针轻轻扎了一下。

「操、操、操蛋……！」

中招了。这分明是针对阿尔德巴兰最可怕也最有效的封印手段。

封印『死亡回归』的方法再简单不过。──不让他死。仅此而已。

世间最温柔的救济之手，正是杀死阿尔德巴兰和菜月・昴的方法。

「这就结束了哦。阿尔先生」

如此，『忧郁魔女』对狼狈不堪的阿尔德巴兰轻声宣告。

无法死去。无法重来。瞥见瘫在一旁的菲利斯，甚至想过让他解除治愈魔法──，

「不行哦。还是说，想和小菲利来场无谓的拉锯战？」

即便剑刃相向也面不改色的菲利斯，他也是怀着觉悟前来挑战的一员。

倘若菲利斯对自己施加了与当前阿尔德巴兰同等的治愈魔法，那么无论如何挣扎都无法让菲利斯在此解除魔法。

那么强行展开『领域』攻心如何。──不行。刚要抓住漏洞的解脱感，因被『忧郁魔女』击退而再度远去。更何况，即便击垮菲利斯的精神，阿尔德巴兰的魔法也没有解除的道理。

换言之，阿尔德巴兰此刻已──，

『──谁都无法战胜我创造的你哦』

「────」

又听见了『魔女』的声音。──就在那一瞬。

凄厉而毁灭性的冲击波在远方产生，将阿尔德巴兰、『忧郁魔女』以及站在这最终局面的一切存在，一口气吞噬殆尽。

13

──这绝非『神龙』蓄意引发的助攻。

当战场被改变，与龙壳原主的战斗持续展开，两名魔法师实现的奇迹超魔法贯穿龙晕时，『神龙』做出了重大抉择。

它优先考虑的并非此刻眼前的胜利，而是作为半身的另一个自己所开启的战斗——那目的、愿望、夙愿，选择将其实现置于首位。

『────呜!!』

释放的『龙』之最终吐息，既未瞄准龙人也未锁定魔法师们，而是朝着远方大地奔袭──命中那应抵达的终点：地面上敞开的巨大空洞、被誉为世界至深至暗之处的摩格阿雷德大喷口。

由此引发的天地异变，在世间镌刻下难以言表的震撼。即便在这片战场，其影响也化作滔天土浪汹涌袭来。

正是在决出胜负的瞬间，巨浪冲向阿尔德巴兰与『忧郁魔女』的战场。

「────」

阿尔德巴兰浑然不觉地被席卷而来的尘土与倾泻而下的洪水吞没，同时瞪大了眼睛注视着这千载难逢——真正意义上的千载难逢之机。

这无疑是带给阿尔德巴兰的最后机会。在阿尔德巴兰的人生中极为罕见──本应在与普莉希拉相遇时就耗尽的幸运，再次发挥了作用。

「──」

短暂的呆滞转瞬即逝，阿尔德巴兰顶着风雨，在浓烟弥漫的战场上凝神搜寻着那个身影。

「在哪里……！」

既非『忧郁魔女』，亦非菲利斯，更非倒下的『阿尔德巴斯特』。

在这战场上，唯一仅存的、阿尔德巴兰或许还能施展的手段。

被封印『死亡』、失去同伴的阿尔德巴兰，与仅存于己身的『魔女』共同追寻悲愿的、最后方法。

那就是──

「──罗伊!!　在的话就过来！　把我……把我的『名字』吃掉!!」

阿尔德巴兰不顾一切地激发咒印链接，在承受巨大负荷的同时感受着阿尔再次龟裂的痛楚，以让灵魂吐血的觉悟呐喊道。

将现状归零的策略——即便是权能被封印的阿尔德巴兰也能执行的唯一对策。

利用『暴食』罗伊・阿尔法德，让那家伙的权能吞噬自己的『名字』。借此从所有人记忆中消失，实现彻底逆转的掀桌战术。

为此，阿尔德巴兰在弥漫的滚滚沙尘中搜寻着可憎的『暴食』身影，放声呐喊。

「吃掉我！我的、我的『名字』是——」

被命名为阿尔德巴兰，背负着『尾随星』命运的存在。

本应抹除菜月・昴实现『魔女』夙愿，却怀着对太阳的渴望背负宿命，最终失去一切的窝囊废。

那个『名字』是——

「雷格尔。——菜月・雷格尔!!」

这正是背叛『魔女』期待、令太阳沉沦的愚昧之星所持有的『名字』。

** 第六章 『锁链之音』

１

──菲利斯协助『阿尔德巴斯塔兹』的理由，当然只是为了他的主君库珥修・卡尔斯腾。

原本菲利斯与威尔海姆一同造访王都，是为了直接向王城请愿加入前往已开放的普雷阿迪斯监视塔的调查团。

阿尔德巴兰一伙袭击王都──『暴食』大罪司教越狱，以及『剑鬼』与『神龙』的激战，都发生在这一时期。

「──有要事相告，亦有要事相求」

向菲利斯等人说明原委并请求协助的是奥托・苏文。当这位爱蜜莉娅阵营的内政官告知阿尔──阿尔德巴兰的暴行及莱因哈鲁特参战的消息时，与积极前倾的威尔海姆不同，菲利斯对协助平息事态始终缺乏积极性。

诚然、作为近卫骑士团的一员、平日里我对扰乱王国治安之徒怀有愤怒。但、单论战斗力我实在弱小、甚至连本该是唯一长处的治愈术、都没能用来拯救最重要的主人、这样的自己究竟还能做什么呢。

实际上，在随后的战斗中威尔海姆败给『神龙』，落得意识无法恢复的重伤下场，这让菲利斯愈发坚定了这个念头。

然而，即便是那样的菲利斯，也发生了令其无法低头的事态。

「好久不见，菲利克斯大人」

そうカーテシーしたメイド──レムと対面し、自分の中に、彼女と会话し、共に戦った出来事が苏ったとき、フェリスは『暴食』の権能が剥がせるものだと知った。

那正是能解开库珥修背负的两个诅咒——『记忆』与『龙之血』其中之一的活证人。

「……既然这样，不就只能干了喵」

就连一直陪伴在痛苦的库珥修身边、不断鼓励因无能为力而消沉的菲利斯的威尔海姆也曾被打倒过。

应要求协助『阿尔德巴斯特队』，阻止即使与世界为敌也要达成目的的阿尔德巴兰一伙。──即便其动机根源有着令人共鸣的缘由，菲利斯仍为库珥修下定决心不惜一切。

不过──

「──虽然完全没想到会让我当王牌呢」

在骇人的喷烟暴风与倾盆暴雨中捂住口鼻防尘的菲利斯，正感慨着这意外降临的重任。

佩特拉运用名为『压缩』的能力，既能瞬间转移目标又可加速对话进程──凭借这份力量反复施展"将伤者传至菲利斯处治疗后再送回战场"的犯规战术，『阿尔德巴斯特队』才得以与强敌周旋。

光是这份差事已相当艰巨，更未曾料想会被委以对抗身怀绝技的阿尔德巴兰的决胜关键。

──为阿尔德巴兰施加持续生效的治愈魔法。这正是作为对抗阿尔德巴兰的王牌，交付给菲利斯不容有失的使命。

说到底，即便是现在也未能完全理解菲利斯的能力。

综合佩特拉和罗姆爷的说法，可以理解为当阿尔德巴兰判定自己『遭受致命伤』时，就会回溯到受伤前的时间──据说他就是持续滥用这种能力渡过危机，甚至连莱因哈鲁特都能击退。

老实说，真让人忍不住要怀疑大家究竟在认真讨论什么。如果那是真的也太无敌了。根本没人能赢吧。

而据说能击败这种无敌能力的，竟是菲利斯的治愈魔法，这就更离谱了。

实在是觉得太赌运气了。

说不定只会沦为白白让大伙好不容易逼入绝境的敌人完全恢复的蠢行。

即便如此，倘若、万一菲利斯真能成为这场战斗的关键──

『勿懊悔，菲利斯。汝之心灵弥足珍贵。当为汝之才华自豪。……那是此世最为温柔的力量』

「──殿下」

曾经有人如此评价并盛赞过菲利斯的力量。

那时也好现在也罢，菲利斯的力量仍未达到『青』之称号的水准。但即便如此，我希望他不将此视为诅咒而持续锤炼的这份坚持是有意义的。

为此──，

「──罗伊！！在的话就过来！把我……把我的『名字』吃掉啊！！」

从看不见的粉尘深处，混杂在轰隆作响的狂风与大地的悲鸣中，传来了声音。

菲利斯的治愈魔法确实发挥了王牌效果。剧烈摇晃的阿尔德巴兰身影与这拼命的喊叫就是证明。

但对方仍未放弃。──菲利斯也支起纤细的膝盖，思考着。

「为了我最重要的人，我还能做什么？」

２

「利杰鲁。──菜月・利杰鲁啊!!」

阿尔德巴兰在蒙蒙升腾的尘土中高声呼喊，拼命瞪大双眼。

暴雨、狂风、地鸣嘈杂不堪，周遭声音完全无法辨明。在视觉听觉都靠不住的情况下，仍声嘶力竭地呐喊着。

被施加的可憎治愈之力，转眼间便治愈了因吐血而惨叫的喉咙。一边承受着这讽刺的恩惠，一边继续全力嘶吼。

「罗伊！　罗伊!!　快找到我！　我是里格鲁！　菜月！　里格鲁!!」

每喊出一次，就仿佛灵魂被无形锉刀削剐般心痛，阿尔德巴兰仍不断重复呼喊着、呼喊着、持续呼喊着那个名字。

菜月・里格鲁。──这是阿尔德巴兰在自称『尾随星』之前的真名。

「──呃」

根本毫无实感。唯有烦躁感顽固地黏在脑海角落。

对阿尔德巴兰而言，比起父母从未直接呼唤过的本名，被『魔女』无数次呼唤的阿尔德巴兰反而更耳熟能详。就连这个称呼，也在『魔女』堕落为『强欲魔女』时化作了伤痕。

早已不明白自己『原本』究竟是谁。──但自我认知无关紧要。重要的是欧德・拉格纳如何记录这条可悲的生命。

所以──

「──我，是菜月・里格鲁」

对于这个只令人感到厌恶的名字，阿尔德巴兰选择亲自承认它。

即使拒绝、疏远或憎恶，生命也无法选择自己的父母。

「────」

阿尔德巴兰继续嘶吼着，拼命在浓烟中搜寻罗伊的身影。

先前破坏性的暴风肆虐后，战场上的人几乎全被吹飞。阿尔德巴兰也被掀翻了好几个跟头，『忧郁魔女』和菲利斯、罗伊想必也不例外。

照理说现在战场上应该没人能行动了。但对方可是把王牌菲利斯留到最后一刻的主儿。就算还藏着后手也不奇怪。——如今阿尔德巴兰的『领域』被封，那张暗牌很可能成为决胜关键。

「妈的……！」

被封住权能的菲利斯施展的治愈魔法——持续治疗着阿尔德巴兰的这道术式，其发动所需的魔力全从阿尔德巴兰自身榨取。如今『阿尔德巴兰』与魔力回路相连，这近乎无限的恢复力简直令人发指。

「既然不能指望『领域』的话……！」

索性、打算耗尽束缚自身的玛娜、用大魔法扫清障碍。这般念头浮现时、阿尔德巴兰已在脑海中勾勒出数道术式。

这些都是从『魔女』处习得、却因无法筹措发动所需资源而被束之高阁的知识、但如今与『阿尔德巴兰』相连便能够使用。

如同莱因哈鲁特那时一般、要运用这些、在没有『领域』的情况下开辟出路──

「呜……」

──就在这念头闪过的刹那、翻涌的呕吐感堵住了阿尔德巴兰的喉咙。

「啊？」

阿尔德巴兰因剧烈眩晕与耳鸣几欲跪地。他慌忙环顾四周以为遭袭、却空无一人。随即意识到──此刻令阿尔德巴兰目眩的真相、是异常沉重的压迫感。

不容许选择失误的压迫感、正碾碎着阿尔德巴兰的肝胆。

「……开玩笑的吧」

俯视着自己颤抖的右手、阿尔德巴兰哑然失声。

在这赌命战场上，自己迄今所做的一切都将化为乌有的紧要关头，托那该死的治愈魔法的福身体状态绝佳，正是需要最快最佳判断的当口，却因胆怯导致脑子转不动这种事，简直恶劣的玩笑。

但现实既非玩笑也非儿戏。纵使噩梦般荒谬，这就是事实。

──因为阿尔德巴兰，从未在不使用权能的情况下做出过决定性抉择。

在这场战斗开始之前，无论是在佛拉基亚帝国，王选期间，剑奴孤岛上，还是更早与『魔女』共度的日子里，阿尔德巴兰的选择永远都是权能庇护下的最优解。

无论犯下何等失误，都能重来，选择其他选项，将失败一笔勾销。不断重复这般行径，正是阿尔德巴兰的生存之道。而如今，这套行不通了。

「────」

不清楚该引发何等规模的风才能吹散浓烟又不致死人。让降水蒸发的热量也好，抵消地鸣的冲击也罢，甚至连该从浓烟的左腿还是右腿迈步才能获得最佳答案，一切尽是未知数。

无法确认之事，令人恐惧。

行走在没有正确答案保证的道路上，犹如在黑暗中摸索前行。

阿尔德巴兰无法踏上那种毫无回报确信的道路。——毕竟，无法发挥权能的阿尔德巴兰，不过是个无药可救的傀儡。

两名『魔女』也好，心爱的女人也罢，那个傀儡都没能拯救。

「──」

一旦开始思考，脑中便尽是糟糕的念头。

让罗伊吞噬自己『名字』的策略是否最优解？是否还有其他可行手段？该不该以咒印为盾放任罗伊暴走再趁机突袭？或是寻找突破性死法来钻完全治愈的空子？又或者该趁尘土飞扬时逃走？诸如此类诸如此类，只有焦躁的感情在——

『──快看，又来了』

「────」

那份焦躁的情感，骤然被浇灭般停滞下来。

迷茫与恐惧，因权能被封而一口气喷涌出的阿尔德巴兰负面情绪——仿佛被这些情绪拖拽而出，深埋心底的最大悔恨开始发烫。

阿尔德巴兰呼出一口气，体验着与触碰就会烫伤、仅是靠近就会炙烤皮肤的极限热量截然相反，仿佛连一滴血液都彻底冻结的感觉。

『又是妾身的──』

「……住手」

『妾身的──』

「住手啊啊啊──!!」

被迫直面那通过捂住耳朵、移开视线、强行压抑在心底深处而得以逃避的事物，阿尔德巴兰发出惨叫。

拒绝听见的声音，拒绝看见的微笑，拒绝渗透进来的热度，龇牙咧嘴。──瞬间，强行睁开的眼中映出硝烟彼端微弱的残影。

「────」

刹那，那道身影虽混在尘土飞扬中，但绝不会错。是罗伊。是『暴食』。

从这喷涌而出的悔恨中──不，此刻围绕阿尔德巴兰的最恶劣状况中，唯一能将他拽出的光明，我看见了。瞬间，冲了出去。

「──罗伊！　我在这儿！　把我！　把我的『名字』吃掉!!」

踌躇的脚步中蕴含的迷茫、探寻死法的怯懦、企图逃避的软弱、怀疑自身选择的怠惰，全都在蹬地瞬间的冲击中粉碎殆尽。

此刻，阿尔德巴兰面对眼前飘落的选择，通过专注抓住其中一项，选择了逃离最恐怖的事物。

──阿尔德巴兰至今始终借助权能之力，逃避着那仅有一次的『选择』机会。因此，他从未知晓。

当人『选择』某物时，被逃离现场的迫切感所驱使作出的抉择，绝不可能为命运开辟出肯定的道路。

而这──

「──阿尔大人」

这个从正面抱住企图在浓烟彼方寻找逃避之影的阿尔德巴兰的存在──本该是同伴的八重・天膳的举动，恰恰证明了这点。

３

──当雷姆败北之际，八重的『下一场』战斗早已开始。

被吹飞后、在冻结大河上形成的冰山斜面翻滚坠落时、连本该做到的止血法等一切手段都放弃了、全力扮演着濒死的败者。

这样做的目的是──

「──我没打算取你性命。因为那个人、会伤心的」

当说出这句话的鬼族少女发动治愈魔法时、八重赢得了最初的赌注。

老实说、想到交战时的毫不留情、说什么没打算取性命简直厚颜无耻、但既然实际保住了性命也就无从抱怨。──更重要的是、若敢抱怨的话、难得的机遇就会化为泡影。

遗憾的是、即便强如八重也不存在从这里逆转雷姆的可能性。

最后攻防中雷姆无效化八重斩击的机关、只要这个谜题不解开、即便偷袭成功、也没有击杀雷姆的把握。这同样只会白白浪费千载难逢的良机。

因此、幸存下来的八重另有目标。──将仅存的全副灵魂灌注于、最后的效忠之中。

就连雷姆也警惕着反击，将治愈魔法的效果控制在最低限度——仅止于愈合出血的伤口、阻止死亡倒计时的程度。再加上彻底束缚了毫无抵抗的八重四肢，显然是要杜绝她发挥人质或俘虏之外的作用。——但即便如此，也不得不说她对忍术的认知还是太天真了。

只要不是当场死亡，就算脑袋搬家也要完成任务才是忍术的生存之道。

她卸开全身关节挣脱锁链，燃烧丹田无视濒死重伤。

这么做是因为她坚信，即便是未能完成任何受托任务的八重，在最后关头也必定能为阿尔做些什么。

——而八重期待的千载良机，来得比想象中更快。

当剧烈冲击吞噬阿格扎德峡谷及周边大地，引发的天地异变以暴风、洪水与地震形式席卷而来时，八重行动了。

レム试图保护ヤエ免受冲击，但她挣脱了レム，离开了溪谷，到达了悬崖上──在那里，ヤエ深切感受到了包括自己在内的アル共犯们的能力不足。

在足以覆盖整个巨大峡谷的沙尘占据视野的情况下，阿尔别说抵达摩格阿雷德大喷口了，就连刚爬上来不久的地点都被敌人拖住了脚步。

那是如果八重、『阿尔德巴兰』、罗伊・阿尔法德、亨克尔、被阿尔召集的共犯者们完成了使命的话，本可以避免的苦难。

正因如此──

「────」

尘土飞扬遮蔽视线、地动山摇掩盖声响、狂风呼啸扰乱气息的空间中，八重却将五感捕捉到的有限信息统合起来，精准锁定了必须在此寻获的目标。

恐怕没有比忍术更能充分利用这种状况的了。第一次对被掳到忍术之村心怀感激，八重飒爽地冲向对方脚下。

这次一定要、无论如何都要成为他的力量──

「──罗伊！我在这儿！把我！把我的『名字』吃掉吧!!」

──我必须对阿尔有用才行，明明是这样想着的。

「──阿尔大人」

她冲破弥漫的尘土，迎面抱住了飞身而出的男人。通过肌肤感受到那触碰身体的温度、重量与生命的脉动，八重对自己的行为感到由衷困惑。

「──八、重？」

被强行拦住而前倾的阿尔，窥视着近在咫尺的八重侧脸，用难以置信般的语气如此低喃。

那颤抖的声音里充满惊叹与混乱，但八重也同样如此。──不，若想到自己方才的决心，可以说八重比阿尔更加混乱。

「我……」

阿尔所处的状况她大致明白。

他正被某种手段逼入绝境，试图在这混乱局面中寻找活路。为此应当利用『暴食』，将阿尔送至混在粉尘中的大罪司教处，这才是八重能为阿尔做到的最佳且最后的效忠。

明明清楚这些，八重却阻挡了阿尔的去路。用整个身体撞上去，拦住了他。

为什么。我向惊愕的自己发问。──八重因为惧怕阿尔，所以希望他死去，为了让他死掉，甚至打算助他达成目的。但若是现在被逼入绝境的阿尔，或许八重自己就能亲手杀掉。所以呢？所以我才阻止阿尔，想让他尝尝我遭受过的恐怖报复吗？

「我……」

『──是爱』

面对涌现的疑问，雷姆毫不犹豫断言的身影掠过脑海，八重屏住了呼吸。

不对，绝对不对。虽然同为想帮主人实现目标的女仆，但八重和雷姆的根本动机完全不同。没有参考价值。

只是想起那个因荒唐庞大的执念而贯彻信念的鬼，八重忽然察觉到自己某种心情。

「我──」

八重，曾经希望阿尔死去。因为阿尔这个怪物太可怕，怕得不得了。

但是──

「──我似乎，无法忍受忘记阿尔大人这件事」

──并非想要永远失去你。

４

「────」

对于抱住自己说出理由的八重，阿尔德巴兰陷入了空白。

不明白。不明白。不明白的事情，实在太多。──阿尔德巴兰本该用『领域』摧毁八重的心灵，让她以我方死亡为条件成为绝对协力者。

对八重那份任性的信赖，在这终极时刻遭到了背叛。

她难道一直在等待这个最完美的背叛时机吗？

不明白。不明白。只是，停下脚步的阿尔德巴兰终将被追上。──被那本该塞住耳朵、移开视线、深埋心底的，最想逃避的声音。

『──看吧，又是妾身赢了』

「……普莉希拉」

在这本该竭力抓住眼前任何可能性的时刻，阿尔德巴兰口中漏出的低语既非『暴食』，也非阻拦自己的女人，更不是自己的名字。

明明已身处因该作为时未作为、让后悔如灰烬般堆积的当下，阿尔德巴兰却再次渴望着灰烬之山。

「什么叫……」

赢了，普莉希拉。

你已经死了。明明已经死了。死了就意味着输了。死了就意味着无法实现愿望了。死了还能不结束的，这世界上只有我和菜月・昴。所以，你不该是这样的。

可你倒是说说，到底什么算是赢了。明明是最不适合说嘴硬话的女人，却在最后最后关头嘴硬了吗。

为什么，最后，你要笑啊，普莉希拉。

「星星──」

「──啊？」

「是星星、不好、阿尔大人……」

当阿尔德巴兰分神于没有答案的自问时，八重从他内心深处仰望着。

听到她慌乱的声音和话语内容，阿尔德巴兰屏住了呼吸。星星作祟这种话，阿尔德巴兰经常挂在嘴边，八重也听惯了。

所以，这是报复吗。在拖住阿尔德巴兰的此刻，用这个报复──不，八重绯红的眼瞳正诉说着并非如此。

那双眼瞳点燃了真挚的光芒，与昔日『魔女』相同的光辉，说道。

不是阿尔德巴兰的错。

「──呃、怎么可能」

「怎么可能有啊」，瞬间涌起的激情在心中翻腾。

事到如今的状况、迄今为止的事态、演变成这样的罪过，这一切都归咎于阿尔德巴兰，归咎于菜月・昴，绝不可能与我们无关。

这份怒火──

「──阿尔!!」

连沙尘都无法阻挡的银铃之声，霎时撕裂了沸腾的空气。

５

猛然跃起的爱蜜莉娅匆忙跳上溪谷，眼前的景象令她震惊。

「感觉超级～剧烈的震动原来是……」

遮蔽视线的漫天粉尘、持续轰鸣不止的风声。再加上非但未平息反而愈演愈烈的地面震颤——昏迷期间竟发生了如此剧变。

但她不会气馁。不会消沉。爱蜜莉娅没有沮丧的余裕。

「必须赶快阻止阿尔……」

大家之所以将阻止阿尔的任务托付给爱蜜莉娅和雷姆，是因为相信她们最适合这份使命。而雷姆像追逐飞驰的阿尔般将她送出去，正是对爱蜜莉娅寄予厚望的证明。

背负着这一切，为了帮助昴和碧翠丝而鼓足干劲的我，怎么可能让阿尔逃走──

「──找到了！阿尔和……咦!?那个女孩!?」

爱蜜莉娅气势汹汹地冲进烟尘中，却在尘土飞扬的另一头发现了阿尔，以及与他相拥的八重身影，不由得再次震惊。

本该由雷姆负责牵制八重。既然八重出现在此，就意味着雷姆可能遭遇不测──虽说菲利斯施展了号称强效治愈魔法的咒术，但依然担心着她的安危。

「立刻──」

正当她猛踏地面想要追上去问个明白时。──爱蜜莉娅的视野中，相拥的阿尔与八重身后，烟尘被剧烈搅动着席卷而来。

那是始终未曾停歇的鞋底震颤，是持续轰鸣的大地哀鸣真身。伴随着剧烈的地面震动汹涌袭来的，是滔天洪水般的激流。

目睹这股洪流无情地冲刷战场、吞噬万物的景象，爱蜜莉娅不假思索地加快了蹬地速度，

「──阿尔!!」

听到呼唤猛然抬头的他与盔甲深处的目光交汇，爱蜜莉娅越过相拥的两人头顶，直面汹涌袭来的洪水。

然后──、

「──冰柱魔线！」

６

大气发出尖锐悲鸣，难以置信规模的冰结之术向洪水席卷而去。

那奔涌而来的，简直像是将整个湖泊像水桶般倾倒而出的神话级洪水。银发飘扬的美丽少女将汹涌而来的洪水接连急速冻结，筑起冰川。

「呀啊啊啊──!!」

但这不过是冰冻与洪水之间徒劳的拉锯战。

虽然爱蜜莉娅释放的寒气能冻结部分洪水，后续浪涛却会越过冻结层再度袭来，迫使她持续施术。反复拉锯间形成了冰霜撑起的伞状结构，以及在其上无尽奔流的辽阔冰川。

「呜呀啊啊啊──!!」

以散发寒气的爱蜜莉娅为起点，冰伞呈圆形扩张，并顺着大水流扩大规模，笼罩在阿尔德巴兰头顶，最终缓缓掠过。

规模越大重量也随之增加，冰伞逐渐龟裂，超重量的坠落只是时间问题──

「────」

刹那间，爱蜜莉娅瞥向这边，与阿尔德巴兰视线交汇。

不知对此作何感想，爱蜜莉娅的嘴唇紧紧抿起──

「呜啦啊啊啊──!!」

原本发出嘎吱龟裂声的冰伞被加固，濒临崩塌的巨大冰河建筑仍在继续。面对即将坠落的冰伞，从地面不断延伸出的冰柱成为支撑的巧思，然而阿尔德巴兰关注的却是另一处。

自称『冰结魔女』，实际上也展现出与之相称实力的爱蜜莉娅。但此刻，若她突破极限爆发的力量与方才的眼神交汇有关──

在溪谷设下的巨岩陷阱、以及保护阿尔德巴兰时那样，如果这次爱蜜莉娅也是为了守护阿尔德巴兰而发挥力量的话。

这样想着，现在才察觉到。──爱蜜莉娅，确实一直注视着阿尔德巴兰，也曾试图与阿尔德巴兰交谈。

「我──」

嘶哑的声音从喉咙漏出，后续的话语却接不上来。

只是，总觉得有个很大很大、无法挽回的巨大错位。──早在权能被封印前，就已经存在无法重来、无法弥补的错位。

『──谁都不可能战胜我创造的你哦』

真的是这样吗，老师。那为什么我会在这里。

为什么我最后让老师露出了那样不像他的表情。

『──看吧，又是妾身赢了』

究竟算什么胜利。到头来还是没弄明白。

但是普莉希拉，说着这种话得意大笑的你，真的──

「──到此为止了」

──刹那间，将一切横扫殆尽的不讲理铁锤，化作光芒贯穿战场。

７

「里格鲁。──菜月・里格鲁!!」

──罗伊・阿尔法德确实听到了那高亢的灵魂呐喊。

那拼命又绝望、饱含能打动听者胸臆情感的诉求，若是喜爱人类慑人激情与悲喜交加切望的『美食家』莱伊・巴登凯托斯，定会欣然倾听这份愿望，边舔嘴唇边满足其需求吧。

「不过~待在这儿的可不是莱伊，是我们呢~」

『美食家』莱伊与『恶食』罗伊，这对共享同个『暴食』魔女因子的双子──准确说是连同胎中死去的路伊在内的三胞胎，意外地性情不合。

对于饮食的重视之处，明明是血脉相连的兄弟却截然不同。

但从未哀叹过这种食性差异。倒该庆幸兄弟间不必争夺相同猎物。无法自由选择猎物、只能从『灵魂的胃袋』偷吃的路伊似乎对此深感焦躁──

「没办法没办法。我们也觉得妹妹很可爱啦。可是，可是啊？吃饭是为了自己填饱肚子，可没本事去满足别人的胃袋哟」

所以，即便可怜巴巴喊着饿的妹妹令人同情，那也不过是身边陌生人的空腹罢了。

即便得知莱伊在砂之塔如幻影般消散，那也不过是身边陌生人搞砸了顿饭。

倒也没觉得活该，更不会为那种吃法哀叹惋惜。脑子里只闪过一个念头──真浪费啊。

「啊~从莱伊的『美食』观点来看，我们这种整天饿肚子的家伙大概是不及格废物吧……但作为『恶食者』的我们，明明吃了莱伊也不错嘛」

罗伊忽然发觉自己莫名将莱伊和路伊排除在食谱之外，滑稽地想着原来自己意外地没抛弃家族爱呢。明明『恶食者』向来是见什么吃什么的，居然会挑盘子。

「啊~真是干了件可惜事啊」

很遗憾，莱伊已经死了。路伊也是，自从在那座沙塔度过的时间以来，就再没在『灵魂的胃袋』里感受到她的存在，不知道怎么样了。──真的，真的很遗憾。要是下次还能碰到妹妹，一定要啃食她的灵魂。

「毕竟，我们可是『暴食者』啊」

无论多么丑陋恶心的东西，只要想吞噬就忍不住伸出舌头。

即便是『美食家』不屑一顾、『饱食者』推开盘子的东西，也要吃得干干净净。

──最重要的是，根本无法想象要放弃曾经渴望吞噬的东西。

「──!!」

在粉尘对面高声呼喊的阿尔德巴兰正陷入绝境──不、正因为被置于完全相反的境地，反而莫名陷入了困境。此时他想起罗伊的存在，试图通过喂食『名字』来逆转局面，这般果决令人佩服。

为了操控并带走他而刻下的咒印 此刻正被激发 阿尔德巴兰正拼命呼唤着罗伊。无法触碰的灵魂仿佛被灼烧般 这种不可思议的疼痛袭击了罗伊 他的身体在地面上抽搐跳动。这痛苦正胁迫着灵魂屈服——若想逃离这般折磨 就必须顺从 简直就是对灵魂的虐待。

「我懂、我懂的、当然懂、懂啦、都说了我懂、就算懂、也只能懂了吧！正因为懂才说懂啊！暴饮！暴食！」

你想说的我明白。想让我做的我也明白。被逼到绝境的心情，我也明白。

老实说、即便灵魂正被这般灼烧、罗伊仍对阿尔德巴兰心怀感激。──多亏被带出监狱塔、才能得到这或许再难拥有的进食机会。虽然不喜欢任人摆布地进食、但来者不拒正是罗伊的优点、这点对阿尔德巴兰而言想必也很方便吧。

「不过啊~要是被误会了可就麻烦了呢~」

正因为心怀感激，才愿意对你言听计从。──但这终究是在罗伊能容忍的范围内，若非如此就请允许罗伊随心所欲。

比如说──，

「──找·到·你·了」

只要是值得以命相搏也想吞噬的猎物，就必定会吞食殆尽——这就是他的生存之道。

８

「里格鲁。──菜月・里格鲁啊!!」

这声呕血般的呐喊，确实传进了『忧郁魔女』的耳中。

就在他刚从意识外侧席卷而来的爆风与威压中挣扎起身时——那股足以夷平大地的冲击波已对战场造成了巨大破坏。

『──佩特拉！你没事吧!?该死的，这突然怎么回事!?大家都平安吗!?』

即使刺耳的耳鸣支配着颅腔，幻影菜月昴担忧的呼喊仍能穿透鼓膜清晰可闻。正当这个『昴』陷入混乱与忧虑、挂念着倒地同伴们的安危时，阿尔开头那声呐喊传了过来。

「────」

在蒙蒙卷起的沙尘中，吐出嘴里沙粒的『忧郁魔女』，从混杂着暴风的阿尔的喊叫声中，得到了来自两个方向的惊讶。

一个是阿尔为了打破这种局面而选择的利用『暴食』权能的方法。另一个则是阿尔喊出的自称其真名的名字。

菜月・利格尔。──这个名字的发音，显然与菜月・昴并非毫无关联。

「既然和昴一样是异世界人，阿尔德巴兰是假名这点早就心知肚明……」

但突然冒出的名字竟是菜月・利格尔，这种巧合未免太过蹊跷。

利格尔是星星的名字，而菜月这个姓氏偏偏又与昴相同。──难不成被召唤到异世界的条件是菜月姓氏＋星星名字的组合吗。

『那家伙……』

当然，『昴』也和『忧郁魔女』一样对这个疑问皱起了眉头。

阿尔身上谜团重重，『忧郁魔女』们虽已做好与世界为敌的觉悟与他交锋，却连他的本心和真意都一无所知。这也是证据之一。

然而──，

「──对不起呢。我、已经做出选择了」

在此刻优先考虑无法解开的谜题，『忧郁魔女』可没这么幼稚。

现在最该优先处理的并非阿尔新提出的谜题，而是这个几乎打光所有手牌却仍有翻盘手段的阿尔。

阿尔提出的吞噬『名字』策略若被执行就无计可施。──通过遗忘又想起雷姆的过程，其效果已得到验证。

「所以、要动手咯、昴」

当『忧郁魔女』如此低语时，『昴』并非站在身侧而是正对面。并非飘浮而是脚踏实地，他正与我正面相对。

『────』

直视着那双漆黑瞳孔，『忧郁魔女』品味着奇妙感慨。

此刻的他不过是任我摆布的幻影，绝非真正的菜月・昴。在外人看来这定是场滑稽梦境，对『忧郁魔女』而言也只是最趁手的骗局。

「可是、却不肯和我结婚呢」

『佩特拉，我……』

「骗你的骗你的。只是想稍微捉弄你一下的魔女玩笑」

轻轻吐出舌头，『忧郁魔女』向被捉弄到的『昴』道歉。

此刻不肯乖乖听话的『昴』的存在，反倒让『忧郁魔女』觉得这正是自己心意高洁的体现，甚至感到骄傲。

喜欢的人按自己预想般行动固然开心，却也心情复杂。

「因为我啊，就是喜欢上了告诉我我自己有多蠢的昴嘛」

『……那可真是光荣。我啊，是个幸福到无可救货的大笨蛋』

「──这话倒是一点没错」

对于如此回应自己告白的『昴』，『忧郁魔女』绽开嘴唇笑了。随后她在原地轻盈转身，将后背留给『昴』。

经过一拍思考或是犹豫的间隙，『昴』从身后抱住了『忧郁魔女』。

这远超期待与希望的一百分。而且，就算是真正的昴本人在场也一定会这么做，所以不会影响『忧郁魔女』的评分。

所以，就这样被那双臂膀抱着──，

「──找·到·了」

黏腻的声音近在咫尺响起，烟尘彼端的威胁正在逼近。

那是循着『忧郁魔女』指向天空的指尖──所释放的白光为标记，猛然袭来的『暴食』大罪司教，罗伊・阿尔法德。

龇牙咧嘴的罗伊与『忧郁魔女』的视线激烈碰撞。

然后──，

「──我叫佩特拉・鲍曼哦」

『忧郁魔女』维持着指尖向天的姿势报上姓名。

为应对『暴食』而由『阿尔德巴兰』实施的姓名洗牌──这是在领主罗兹瓦尔协助下，作为正式生效的改名仪式成果。众人自由选择名字时，『忧郁魔女』继承了最敬爱之人的姓氏。

但此刻揭露隐瞒至今的新名字不为别的。──正是杀手锏。

『──佩特拉』

用无法触碰的手臂，却仍用力抱紧的『昴』呼唤着自己。听到那声音，『忧郁魔女』也将手叠在同样无法触碰的手臂上，露出微笑。

微笑着，献上一切代价成为『忧郁魔女』的少女宣告道。

「──昴，最喜欢你了」

９

置于舌尖，发动『蚀』，吞噬瞬间渗透全身的满足感令躯体战栗。

「～～啊！」

这『蚀』的巅峰快感，正是连吞噬过无数『名字』与『记忆』、贪食人生的罗伊都找不到替代品的『暴食』真髓。

饥饿，饥饿，过度饥饿的饥渴感才是『暴食』的存在意义。──正是在产生些许满足错觉的刹那，才能感受到令人沉醉的生命充盈。

那正是──

「──极品啊！」

遵守约定的『魔女』滋味，让回味舔唇的罗伊沉醉在极致的爱欲中。

被远超期待的情感、超出担忧的强烈程度、超越希望的纯真所俘虏，罗伊沉浸在这满溢全身的饱足感中，尽情品味着真正的『蚀』为何物。

没错，没错，没错没错没错，正是为了这份滋味而活。

──即便因破除咒印的代价使灵魂燃烧殆尽，对这『蚀』也绝无后悔。

那些涌入的『记忆』，清晰地揭示了路伊渴求的理由。但不幸的是，与妹妹不同，罗伊的味蕾感受到的最甜美之物，竟是少女的祈祷。

能将区区一盘料理爱到如此地步的『魔女』，完美超越了品尝前的所有期待。

因此，『暴食』大罪司教罗伊・阿尔法德笑了。

在被破除咒印证据的青色火焰灼烧时，笑了。

「──承蒙款待了」

然后，在连灵魂都被青焰燃尽的瞬间──

「──到此为止」

突然在战场上迸发的深红火焰，毫不留情地一闪劈开了那青色火焰。

10

──提到『剑圣』莱因哈鲁特・范・阿斯特雷亚的代名词，最先浮现的理所当然会是『剑圣的加护』。

然而，若是更了解莱因哈鲁特那超乎常理之处的人，便会知晓他所拥有的诸多加护，正是令其冠绝历代最强『剑圣』名号的原因之一。

昔日，在与史上最强存在之一『强欲』大罪司教雷格鲁斯・柯尼亚斯交战时，曾与其并肩作战的菜月・昴目睹了莱因哈鲁特持有的众多加护，尤其将『不死鸟的加护』评价为破格存在。

原本以他那压倒性实力，就连夺取一次性命都极为困难，而死后仍能复苏的『不死鸟的加护』之力，堪称犯规招式。

但倘若知晓菜月·昴曾嗤之以鼻判定为作弊能力的『不死鸟的加护』其真正破格之处，恐怕会彻底颠覆他的评价吧。

「──『不死鸟的加护』」

由于在与那位『强欲』大罪司教的战斗中曾使用过一次，准确来说这是新获得的下一项『不死鸟的加护』，但引发的现象相同，区分并无意义。

重要的是，这项加护发动时，受加护者莱因哈鲁特・范・阿斯特雷亚丧失的生命会复苏，同时包括致命伤在内的所有伤势都将痊愈。

因此此刻，莱因哈鲁特为在世界毁灭边缘力挽狂澜，与『嫉妒魔女』残影持续三天三夜战斗所受的一切创伤都将归零。

这其中包含阿尔德巴兰协同『神龙』对莱因哈鲁特造成的双臂功能性损伤，就连不眠不休持续作战的疲劳也被活力之炎焚烧殆尽。

仅此便足以证明『不死鸟的加护』力量超乎常理，但莱因哈鲁特仰仗这项加护的真正价值还在后头。

由于阿尔德巴兰设下的某种机关，在现代复苏的『嫉妒魔女』的威胁。与其出现时相同，在突然消失的瞬间，莱因哈鲁特获得了战斗终结的决断──以及立即让自己负上致命伤的觉悟。

若仅仅是为了治愈自身伤势，莱因哈鲁特本不必刻意自伤，只需等待伤口自然愈合。

换言之，莱因哈鲁特所求于『不死鸟加护』的并非伤势治愈，而是该加护所持有的另一重效果，那便是──

「────」

──缠绕真红火焰的瞬间，莱因哈鲁特于战场正中央复苏。

这正是『不死鸟加护』所具备的超规格效果之一端，令逝去的加护者在所望之地重生的复活之炎。

虽与雷格鲁斯・柯尼亚斯交战时，这份力量曾复苏于共同作战的菜月・昴眼前，但此刻莱因哈鲁特复苏于何处自不待言。

正是在本该与阿尔德巴兰交战的主人脚下──为了给莱因哈鲁特收拾残局。

「────」

从逆风翻卷的火焰中现身战场的莱因哈鲁特，瞬间就察觉到此处是遭受天地异变的异常空间。

即便是莱因哈鲁特，也不禁对这景象感到震惊──

「莱因哈鲁特！」

听到突如其来的呼唤而回头的莱因哈鲁特，目睹了容貌可爱的友人拼命呼唤自己的身影，以及被那位友人抱在怀中的主人──菲鲁特的身影。

一眼就看出事态非同寻常，莱因哈鲁特立刻想要奔向主人。被友人菲利斯抱着的菲鲁特垂着头，浑身无力。虽然不可能有比菲利斯更合适的帮手，但至少想出声呼唤──

「──喂」

「────」

比莱因哈鲁特迈步更快的，是那虚弱沙哑的声音。

在粉尘中，被菲利斯发出的淡淡光芒包裹的菲鲁特──她头部集中接收着治愈之光，缓缓抬起脸，尽管视线多次失焦，仍用赤红眼眸捕捉到了那位骑士。

然后，她拼尽全身力气，挤出了一句话。

那是──

「──后面，交给你了」

那句话让莱因哈鲁特明白，自己该做的并非挂念主人。

莱因哈鲁特的主人很强。甚至远比莱因哈鲁特更强。

因此──，

「──到此为止」

将完成使命的主人托付给友人，被推了一把的莱因哈鲁特奔赴战场。

瞬间掌握区域内所有气息的位置，锁定需歼灭的敌人，朝被青焰包裹的『暴食』罗伊・阿尔法德挥出一闪，将其从世上彻底抹消。

「──承蒙款待了」

灼烧嗤笑的罗伊・阿尔法德的，是以他灵魂为燃料永不熄灭的青焰。因此莱因哈鲁特给了他痛快，避免长久痛苦。

接着──，

「──阿尔大人，这次定要阻止您」

面对立于沙尘中的阿尔德巴兰，莱因哈鲁特蹬地飞驰。那是即便不借助『压缩』之力，也足以碾碎空间的超高速移动。

就在那莱因哈鲁特与阿尔德巴兰之间，少女猛然张开双臂。红发少女以最快速度移动试图庇护阿尔德巴兰。一记踢击，连反应都不容许的莱因哈鲁特手刀击中她的颈部，将她的意识瞬间收割至远方。

接着，面对毫无防备的阿尔德巴兰，莱因哈鲁特再次挥动手臂──，

「──那是，我的职责」

──刹那，阿尔德巴兰的躯体，被『剑圣』的全力一击命中。

11

远处，沙尘彼端蓝色火焰四散，意识到这点的下一秒，眼前已是八重纤细后背崩塌的光景。

下意识伸手想扶住倾倒的她，究竟是出于何种心理？无论如何，阿尔德巴兰的手终究没能触及。向来如此。

而后，连眨眼间隙都不存在，白闪已将阿尔德巴兰身躯横斩──，

「──呃」

毫无疑问，腰身以上遭手刀一闪，阿尔德巴兰被劈成两半。

だが、真二つになった瞬间から再生が始まり、それこそビデオの逆再生のような势いでアルデバランの肉体は复元、両断された胴体が即座に修复される。

那是阿尔德巴兰施加的『蓝色』治愈魔法非同寻常的威力，以及远超寻常名剑的『剑圣』手刀锋利度共同实现的人体切割魔术。

但是──

「死不了……！」

这句呐喊，究竟是作为肯定还是否定的宣言回荡着呢？

莱因哈鲁特的一击，没错，是莱因哈鲁特。本应连『嫉妒魔女』都召唤出来才得以无力化的他现身了，承受着毫不留情的手刀，然而，没有死去。

既然将胴体斩成两段，莱因哈鲁特必定是怀着杀死阿尔德巴兰的意图发动攻击。然而『青』之治愈术甚至凌驾于那位『剑圣』的杀意之上，阻止了权能的发动。

「────」

阿尔德巴兰强忍着转瞬即逝到令人怀疑是否真实存在过的痛楚，继续思考。

莱因哈鲁特在场。不妙。糟糕。一切都要完蛋。而且他出现在这里的理由，若非世界已被抛弃，就意味着『嫉妒魔女』退却了。

而若『嫉妒魔女』退却，便只剩下灭口的理由不复存在这一种可能。──这即是说，罗伊打破了咒印誓约，将权能用于『忧郁魔女』的证据。明知这么做的代价是要用性命偿还。

大罪司教竟不惜赌上性命，也要报复被强迫服从的仇吗？唯一能确定的是──阿尔德巴兰亲手斩断了突破现状的可能性。

「──呃」

『暴食』的可能性从指缝间滑落。

承认这个事实后，阿尔德巴兰咬牙切齿地迸发思考，决心将此后所有行动都用于打破现状。

无论是呼吸、心跳，还是指尖滴落的每一滴汗珠，都不容许丝毫浪费。

如此强烈告诫着自己的灵魂，阿尔德巴兰接住了倒下的八重。──接住八重？

「──啊？」

就在刚才，阿尔德巴兰才刚确定了自己该做的事。

明明已经下定决心，从此刻起要连刹那的刹那都用来渡过这场意外，为何却向八重伸出手，将她抱了起来。

她已失去意识，绝不可能是装死。即便抱起八重，也无法打开局面。

可是，为什么，阿尔德巴兰──

「你也心知肚明。──到此为止了」

正当阿尔德巴兰因无法理解自身行为意义而惊愕万分时，传来莱因哈鲁特的声音——这位与『嫉妒魔女』死斗却仍精神饱满的男人。

说什么到此为止放弃吧，莱因哈鲁特倒是说得轻巧。

说得，轻巧。

「哼，虽说『剑圣』肯定也背负了不少……但老子也不是用半吊子的觉悟就能随便放手的货色」

「────」

「还早、还早着呢！就这点……就这点程度！别擅自替老子放弃啊！」

阿尔德巴兰强撑气势，狠狠瞪视莱因哈鲁特。

至少要用气势压倒对方，哪怕只抓住一个破绽也好。但在阿尔德巴兰的猛攻下，莱因哈鲁特扬起手刀迎击。

曾将阿尔德巴兰一刀两断的『剑圣』之手，此刻正紧握着某物。

──那是不该存在于世的、用魔法编织的黑球。

「这招如何？」

阿尔德巴兰瞪大双眼僵在原地，终于明白方才『剑圣』那一闪的目标并非取他性命，而是要将躯干彻底劈开。

莱因哈鲁特是故意的。──他赌上『青』之力，字面意义地剖开了对方的腹部。

剖开阿尔德巴兰的腹部，将其中的东西拽了出来。

这本该被扔进摩格阿雷德大喷口、那个通往世界尽头的洞穴──

「可惜啊，这玩意儿可撕不烂!!」

冲击余波未消。但主导权仍在己方手中。

这是『魔女』创造的禁术，能彻底封印从魔女因子获取力量的产物。即便是莱因哈鲁特的怪力，或是足以毁灭世界的『龙』之吐息也休想破坏。

然后，无论发生什么，阿尔德巴兰都绝不会解开那个封印──

「不对，被封印在这里的是昴吧？──既然如此，我就拔出来」

瞬间，异常力量的奔流令大气震颤，世界发出清晰可感的战栗。

那把剑的出鞘竟重要到如此地步，连世界本身都无法忽视。

那就是──

「──『龙剑』雷德」

不可能存在的光之闪击，斩断了『剑圣』手中那颗小小的魔玉。

12

『──谁都无法战胜我创造的你』

将阿尔德巴兰命名为『尾随星』，并灌输一切的『魔女』曾如此说过。

『──看吧，又是妾身赢了』

赋予阿尔德巴兰『尾随星』之外意义的『太阳姬』曾如此说过。

「────」

愚蠢无能的阿尔德巴兰失去了两者，明明拥有能修正错误选择的权能，却始终选择最半吊子的道路。

只为不让终结世界的『魔女』诞生。──一切都是为了这个目标。

接受『魔女』的教诲，试图按其心愿杀死『魔女』。──却失败了。

与普莉希拉相遇，试图通过让她成为王来杀死『魔女』。──失败了。

回归初心，试图通过除掉菜月・昴来杀死『魔女』。──失败了。

「──啊」

炫目的光芒四溢，即便隔着铁盔也能感受到眼球被灼烧的痛感，阿尔德巴兰目睹了眼前这依靠蛮力创造的奇迹，以及那超常力量的结果。

由超常之力引发的现象，同样被另一股超常之力斩断并封印。当封印解除时，阿尔德巴兰唯一能做的，就是像突然发作的癫痫般，用双臂死死勒紧那纤细的身躯。

然后──，

「──！」

本不可能听见的微弱呼吸声，却狠狠撕扯着阿尔德巴兰的意识。

那是来自后方——正对汹涌洪水释放力量、用骇人寒气阻挡浊流吞噬战场的银发少女。

若那是力竭被洪水吞没的悲鸣，尚可忍受。

若那是因莱因哈鲁特登场而安心的叹息，尚可忍受。

倘若那是可憎的阿尔德巴兰被逼入绝境的痛呼，我尚能忍受。

但是，哪个都不是。──她那双紫绀色的眼眸凝视着的，只有一人。

因为阿尔德巴兰永远无法映入她的眼帘。

「──菜月・昴啊啊啊!!」

咆哮。呐喊。嘶吼。

字面意思般地，用吐血般的沙哑声音，阿尔德巴兰喊出了那个名字。

从光芒中飞窜而出的，是抱着身着礼服大精灵的黑发少年──绝不可能认错的那个人，借着从黑球中解放的势头单膝跪地。

然后，张开双唇，开口第一声便喊道。

「──雷姆!!」

仿佛回应那声音般，锁链声刺痛了阿尔德巴兰的鼓膜。

13

──雷姆爱着菜月・昴。

这已是不可动摇的事实，就连尚未完全取回『记忆』的雷姆，纵使不情愿也该承认这点。

或者说，无论有没有『记忆』，雷姆被昴吸引都是必然的事，老实说真不明白她之前一直在忍耐什么。

「不，不对。那说得也太轻巧了……首先那样的话，就算那个人什么都没为我做，我不也会喜欢上他吗」

雷姆认为自己的感情并非那么廉价的东西。

反倒是个性情乖僻、疑心重重、不会轻易敞开心扉的女人——这才是雷姆眼中的自己。连自己都不禁战栗，这是何等难以接近的姑娘啊。

与坦率又慈悲的拉姆、或是嘴上不饶人却心思透亮惹人怜的卡秋娅截然不同。

没错，『原本』的雷姆就是个难以接近、态度恶劣的性格糟糕女。

眼界与天地都狭隘不堪，光是守护自己有限的圣域就已竭尽全力，根本无暇顾及体谅周遭他人。——然而，菜月・昴却闯了进来。

他闯进来，踏得乱七八糟，又牵起手，带着她离开——雷姆就这样彻底沦陷了。

而且像这样沦陷的，即将沦陷的，今后还会越来越多、越来越多。

「但是，即便如此，第一个沦陷的是雷姆这点不会改变」

菜月・昴的好，最先领会到的就是这个雷姆。

爱蜜莉娅或许也是个不错的对手，但在深度与分量上请容我坚持雷姆才是第一。这一点同样无可动摇。——这是与菜月・昴相关的重要之事。

「宅邸、王都、弗琉盖尔大树」

这是失去『记忆』之前，爱着菜月・昴的雷姆与他共同走过的轨迹。

「密林、城郭都市、帝都及连环龙车」

这是失去『记忆』之后，开始爱上菜月・昴的雷姆与他共同走过的轨迹。

「过往、现在与未来」

这是取回『记忆』的现在，重新爱上菜月・昴的雷姆与他共同前行的轨迹。

哪怕八重不说那么多次，就连雷姆也明白用『爱』这一个词来概括全部实在太过粗暴。

即便如此，若问及推动自己、断言绝不后悔的希望原动力究竟是什么，果然除了『爱』之外别无他想。

──雷姆因爱而能相信菜月・昴。

──雷姆因爱而能为菜月・昴倾尽所有。

──雷姆因爱之故，能与菜月・昴期许相同的未来。

『──雷姆姐姐，请容我问一个问题』

那是奔赴战场前，与一位同样深爱着菜月・昴的少女——如同雷姆那般——所进行的对话。

她也同样与菜月・昴相遇，明白他是偏离『常规』之人。并因这份认知感到幸福，决心与他共赴荆棘之路。

明知那双眼睛正直视着他人而非自己，却仍无法抑制地渴望那份爱的目光投向自己。

『雷姆姐姐，只要能帮助昴，您什么都愿意做吗？』

后来雷姆时常回想。

问出这句话时，究竟需要多大的勇气。

为传达早已备好的话语，究竟经过了多少深思熟虑。

而倘若当时，自己给出的答案违背了对方的期待——那位少女究竟要背负多大的觉悟与理想，才敢独自踏上那条路。

「是的，当然。──因为，我是属于昴君的雷姆」

所以，能够毫不犹豫地回应那份心意，对雷姆来说是无可替代的骄傲。

要说的话，那就像是与对菜月・昴的感情深度一较高下。而且唯独对能被他倾心的爱蜜莉娅，有着绝不能退让的秘密誓言。

实现这个誓言究竟会引发什么，雷姆其实并不清楚。

唯一明白的是，这能成为帮助菜月・昴——不，说反了。是成为菜月・昴，那个温柔少年所要背负的众多思念中，最初的其中一人。

奢望更多就太贪心了。但取回『记忆』后变得贪婪的自己，即便明白是奢望，仍忍不住渴求再往前踏出一小步。

比如说当被雷姆她们推动前行的少年走上征途时，能想起雷姆和少女的奉献，在他心中激起比涟漪更汹涌些的波澜。

这就是雷姆的——

「——雷姆!!」

白光彼端，他的身影出现的瞬间，雷姆酸楚的感怀霎时粉碎四散。

瞬间，雷姆被内心涌出的无尽情感激流所摆布，不由自主地涌现出想抛开一切扑向那胸膛的冲动。忍耐著。

紧接著，鞋底紧咬的大地爆裂，眼看隆起的岩壁就要占据视野──残留火焰余温的『剑圣』一记斩击将其劈开，道路敞开。

笔直地，毫无阻碍地，雷姆与心爱少年的视线交汇。

「────」

与那拼死却仍抹不去大地般温柔的少年，黑瞳与视线交错。

咽下想说的千言万语、想倾诉的万般思念、想献上的亿万祈祷，雷姆开口。

「请让现在的我……让雷姆，重新爱上您吧」

刹那间，竭尽全力挥动手臂。──铁球笔直地，划破长空。

14

──锁链声，响起。

那一刻，自己吐血般的惨叫也好，忘我状态下释放的极大魔法引发的大地隆起也罢，就连『剑圣』挥出的至高一闪抵消了天地异变之事，以及抱着精灵现身的男子似乎用『强欲』权能掌握了局势之事，乃至不知不觉用力抱紧怀中体温灼热的女子身躯之事——对阿尔德巴兰而言全都无所谓。

他只是不顾一切地伸出手。——不，试图伸出手。却没能做到。

右臂抱着背叛的女子，失去的左臂连同『魔女』的期望被遗弃在那个时代，阿尔德巴兰终究没能伸出手。

取而代之的是——

「——阿尔」

他听见那个吸引了全场目光的男子注视着自己，唤出了这个名字。

那双漆黑眼瞳中蕴含的感情，那仿佛连阿尔德巴兰都想拯救的菜月・昴的眼神，最最最——

「最讨厌了，混账东——」

——锁链声，响起。

15

——我爱你。

16

——深深吐息，在心灵深处，拉紧名为觉悟的弓弦。

「────」

刚刚交谈过的少女们、尤其是佩特拉的体贴让我心痛。缺乏坦率带着小恶魔态度的梅莉、公事公办的菲菈姆，她们那样做似乎也都是在为我着想，以碧翠丝为首的好幼女们都聚在一起。

「不愧是『幼女使』呢。对双方来说都不光彩啊」

抛开刚被这么叫的时候不说，佩特拉她们不可能永远保持幼小，想必非常不满吧。只要还带着永远幼小的碧翠丝，这个绰号恐怕就摘不掉了。当然，要是和碧翠丝闹翻就另当别论了──

「要是能做到的话，呢」

按理说这个计划的实现难度本可以更低些。

实际上，除了碧翠丝以外，我从没见过对人类友好的阴属性大精灵。也正因如此我认为她是被设计出来的，但与我熟知的『魔女』不同，我不明白『魔女』的血亲们有何意图。

无论如何，对于阴属性专家碧翠丝而言，结合她的出身，很可能揭示出计划中不可或缺的关键因素。——所以时机才如此重要。

就连通过契约与目标灵魂相连的碧翠丝，也必须用禁术强行纳入。

「────」

咯吱作响的弓弦声清晰地传递出张力逐渐达到顶点的讯息。

就这样，无论重复多少次都会被震撼的景象——踏入收藏着海量书籍、巨大书架填满广阔空间的『塔吉忒』书库，然后——凝视。

「木拉库」

获得大精灵全方位支持的男子，通过简短咏唱实现了最大效果，只见他轻巧跃上高耸的书架，将某本书悄悄藏匿其间。

「────」

即便远远能辨认出是书本，也无法看透封面题写的是何人姓名。

这书库里所有的『死者之书』，除了标题外外观完全相同，厚度也无差异，仔细想想实在蹊跷。毕竟对吧？

五岁幼童因病夭折与百岁老人波澜壮阔的寿终正寝，这两种人生竟被装订成同等厚度的书籍，简直毫无道理。这个书库必定是『魔女』利用了欧德・拉格纳的特性构筑的空间，将死者人生以书本形式具现化的产物。

既然如此，『魔女』为何偏要煞费苦心建造这般难以检索的书库？

「你不觉得在捧书邂逅的刹那，不该掺杂多余杂音吗？」

模仿着『魔女』可能会说的台词自言自语后，竟真觉得这就是她故意建造低检索性书库的正解理由，不由得一阵反胃。

说到底，本就连回忆『魔女』这件事都想极力避免——自从她死去后，却像反弹般不断想起她。

『——谁都不可能赢过被我创造出来的你呢』

忽然闪过念头：若此处真是收藏死者人生之书的书库，那么『魔女』的书必然也藏在某处吧。

然后——

『——瞧呀，又是妾身赢了』

捂住耳朵、移开视线、用灵魂抗拒着远离的声音，其主人的《死者之书》亦是如此。

「……到底、算什么胜利啊，普莉希拉」

难忘的最后，与她临终的对话中，曾浮现胜者般的笑容。伴随那笑容宣告的胜利宣言，其意义至今仍未明了。

即便明白也无济于事。因为她已然逝去。与逝者再无法交换言语、传递心意。

但，即便是单向的交流，能实现理解的正是这座大图书馆普雷阿迪斯。

「……我真是蠢啊。不，我就是个蠢货。那不过是个借口罢了」

一切都是为了计划，为促成曾一度放弃的与『魔女』共谋的策略，刻意准备的让那群男人安慰伤心自己的掩护故事。

居然真心为此动摇心神，简直是招魂人反被魂勾了去。

更重要的是──

「别来、拯救我」

若读了那本书，若再次被那沉没太阳的眩光灼烧，或许会像放弃『尾随星』的那天一样，自己又将动摇。

没有拯救价值的愚蠢星球，又是这样。

所以──，

「──是星球，不好啦」

用这句话让自己死心，重新迈出停下的脚步，在书库中前行。

书架上静静藏着一本书，虽然看不见标题，但那本书冠以谁的名字，就算不看也能猜到。

如果那个男人鬼鬼祟祟藏着自以为对他不利的《死者之书》，那本书的标题只会有一个。──而找出这本书，也是执行这个计划所需的拼图。

想找的两本书，我和那个男人的《死者之书》都已找到。

那么接下来，就是实行时刻──，

「哎呀呀。简直像在图书馆捣蛋的熊孩子呢……」

这么嘟囔着，慢慢走近正在挠头的男人背后。对方没察觉我的靠近，正从刚藏完书的书架旁离开，

「要是被充满求知欲的艾莎小姐发现就糟了……话说今后可能还会频繁有人进出，是不是该全处理掉？总共有多少本──」

「──处分是指什么啊，兄弟？」

「──」

当我对着那嘟嘟囔囔的背影搭话时，对方夸张地抖了下肩膀。

倒吸一口气转过脸的男人面颊微微僵硬，明显就是做了亏心事的模样。看着这藏不住事的反应，我故意轻佻地耸耸肩，

「喂喂，你也太怂了吧。就是随便聊聊而已」

「……啊，抱歉抱歉。自言自语被人听见，超级尴尬的吧？」

「这心情我倒懂，但被当成坏人我可就伤脑筋了啊」

「坏人什么的……」

对着歪头困惑的对方扬了扬下巴，让他注意身后。这时从那边传来啪嗒啪嗒的可爱脚步声，碧翠丝正走过来。

她用娇小的身躯挤进我们之间，鼓起脸颊，

「喂，你这家伙，不许突然吓唬昴。在贝蒂看不见的地方，昴莫非是传说中的跳蚤心脏吗？」

「跳蚤心脏……咱兄弟？我觉得不至于这么怂吧」

「……如果那是对我厚脸皮或不要脸的评价，我倒可以坦然接受。但你了解我什么，凭什么这么想」

「──这个嘛。说不定我知道的比兄弟你想的还要多哦？」

听着袒护自己的碧翠丝被男子啪啪轻抚着头说出的话，他稍作思考后给出模棱两可的回答搪塞过去。

倘若此刻说出比现有话题更深的信息──比如连来到这个世界前，与父母之间微妙的隔阂和自卑感都了如指掌，对方会作何感想。

当然不会做这种蠢事。虽然多次被这种冲动驱使，但每次都会摆弄头盔金属扣忍耐下来。

思考时的小习惯，那提醒自己勿忘计划的金属碰撞声。

「真是意味深长呢。竟敢在贝蒂面前宣称很了解昴，是不是小瞧了精灵与契约者之间的甜蜜关系呀」

「正因为太甜蜜了。哎呀呀，打扰你们火热的新婚期真不好意思」

咔嗒咔嗒摆弄着头盔接缝处的这边，抱臂的碧翠丝显然相当不悦。为避免触怒她而耸了耸肩，对方便笨拙地用手指挠着脸颊，

「别……别在意啦。我和碧翠子有时间就会卿卿我我的，现在嘛，你看，就是那个啦。这边书库优先对吧？」

「真是方方面面都承蒙关照了啊。不，说真的不开玩笑，让我重新道个谢。就算只有三天，为我腾时间也很辛苦吧。碧翠子妹妹也抱歉啦拉上你兄弟。谢谢你们能一起来」

「贝蒂和昴是两位一体，在一起是理所当然的吧。──还有，贝蒂可没慈悲到反复提醒同件事，你要自己好好改正哦」

「明白明白。──您家孩子可真温柔呢」

「嗯，是这样呢」

面对男人无可奈何的苦涩笑容，碧翠丝轻轻握住了那只手。

不知为何对话陷入僵局。若说一拍即合，听起来像是自己与对方很合拍，这反而让人不太愉快。但即便如此，本应能顺畅进行的对话接球，现在却如此磕磕绊绊。是因为被看到了相当不妙的东西吗？──又或者，是因为藏起了与这边预想不同的书名。

比如说，那可能正是我刚才想到的两本书中的某一本。

如果是那样──

「阿尔，那个……状态怎么样？」

「──。搞什么啊，这种拿捏不准距离感的青春期父母式提问。……如你所见，毫无成果。本以为三天就能搞定，现在可真没辙了。这书量，简直像在沙漠里找一根针吧？」

「──呜、但别放弃啊。好好找吧！我也会帮忙的！」

「喂喂，兄弟？」

刚这么想，就被对方猛然前倾的势头逼得后仰。

「会帮忙的」——对方曾无数次、无数次地用不变的诚意向我起誓。既不觉得那是谎言，也不为此生气。──毕竟，我从未期待过。

最该被期待的、最想被实现的，终究没能如愿。

所以说──、

「别用这种分不清是谁想来的气势啊。连我都变得像兄弟一样热血沸腾的话，不就太不合理了吗」

「成为吧。拼命成为吧。用三天时间，全力以赴做到最后。然后……」

声音在颤抖。──并非这边，而是听见对方的声音在震颤。

或许是过度共情，又或是本应退去的浪潮再度涌来，情感重新翻涌。惋惜与懊悔的情绪，比常人感受得更加强烈。这我明白。

那是唯有自己与这个男人，世上仅存二人所拥有的、名为权能的诅咒。

只不过那里存在着能用它拯救所爱之人的男人，与无能为力的自己。

而若继续纵容这个男人泛滥的爱，终将孕育出──毁灭世界的存在。

为了阻止这一切，至少，我要履行『尾随星』的使命──、

「──昴」

声音发颤的碧翠丝牵着垂首男人的手，轻声唤出那个名字。

呼唤声中蕴含的情感静谧深沉，与她可爱外表截然相反的，是那份印证着她作为长生大精灵的神秘庄严感。

「────」

面对大精灵的呼唤，当事人屏住呼吸说不出话。

看着这般反应，她又用手指拨弄着头盔接缝处，做出决定。——再交换一两句话语后，就动手。

如对方所言，在这座塔里搜查书库的期限是三天。随着日程不断消耗，思绪就会转向其他事情。所以要在那之前行动。

「——三天，那样不行吗？」

男人挤出来的话语，不知为何听着像在哀求，或许这也证明我方同样变得神经质了吧。——不禁稍稍思考。

三天，按对方说的寻找《死者之书》，如果真的找到，知晓了消失女子最后留下的全部思念，又会怎样呢。

可以断言。——什么都改变不了。

这道伤不会愈合，疼痛也不会消失。说到底，我根本不期望那样。

所以，明明知道对方抛出的问题会与自己擦肩而过，却还是故意这样回答。

「──是星星的错」

就连我自己也不清楚，是用肯定还是否定的眼光看待那颗星。

将现场的两颗星——普雷阿迪斯与阿尔德巴兰——不，是将昴与参宿四相互对照时，究竟该责备谁的过错，又该安慰谁的无辜，连我自己也。

「────」

太过感伤了。这次对话回合打得拙劣，我这边也一样。

照这种节奏交谈下去，很可能会被对方带偏说出可疑的话。已经决定了。就在下一回合，我如此下定决心。

在沉默的对手说完星之命名者该说的台词时出手。──向门注入玛那，编织术式，开启禁术之门。

然后──

「──阿尔」

然后，与快要哭出来的菜月・昴四目相对。

「──奥尔・纱幕」

那并非我的咏唱。──刹那间，理解了一切。

阿尔德巴兰在一场绝不能输的战斗中，又一次败北了。

『──看吧，又是妾身赢了』

心爱女人那再也无法重现的胜利笑容与临终之声传入耳中──下一秒，阿尔德巴兰的世界陷入黑暗。

17

「菜月阁下，虽然这话起不到安慰作用，但你的担忧确实应验了。他在提炼玛那、编织术式。若稍有差池，立场就会逆转吧。我全面支持你的判断是最佳选择」

目睹全程的矮人族──艾莎・卡德纳的话语，正如他所说，丝毫未能抚慰昴的内心。

明明应该存在其他不必伤害任何人就能解决的方案。

「老大，俺实在搞不懂啊。但是、但是啊！就连屁都不懂的俺也敢说这句话！……俺是真高兴老大你能平安无事」

和艾莎一样被赋予俯瞰局势的职责、想必正因无能为力而焦躁不已的小弟，用直白的话语和有力的臂膀抱住昴的肩膀，这样说道。

而且像这样陪伴在昴身边的并不只有他，

「昴真的好好做出决定了吗。……明明贝蒂可以代替你承担一切的，结果却因此受伤，真是个笨蛋呢」

「碧翠丝……」

「不过那个禁术是贝蒂和昴两个人完成的吧？昴准备术式，贝蒂构筑魔法，昴负责咏唱，贝蒂输送玛那。所以这份罪孽要和贝蒂对半分哦。一个人扛太多太狡猾了」

「──」

昴狠狠咬紧牙关，他的右手——那因自身不成熟而不得不紧握黑色球体的手，正以几乎要让指节无法张开的力度死死攥着。

──那是将除此以外别无阻止方法的阿尔囚禁其中的魔玉。

「────」

想要阻止。想要挣扎。拼命挣扎着，渴望找到答案。

可是做不到。如果又因为昴的脆弱导致相同事态发生，想到要让她们再次杀死昴的话，这种事──

「──不行。有非去不可的地方」

品尝着胸腔深处、体内所有内脏都在震颤的感觉，跪地的昴从原地站起，缓缓走出『塔吉忒』书库。

牵着碧翠丝的手，带着担忧的加菲尔和艾莎，昴呵斥着随时可能瘫软的双腿，穿过走廊抵达目标房间。

然后──

「哎呀呀？哥哥怎么啦？书库的东西找到了吗？」

发现出现在入口的昴，坐在房间角落木桶上的梅莉顶着头上小红蝎，一起歪过头。

那副平安无事又带着小嚣张的少女模样也令人心头一紧，但更重要的是──

「──昴，怎么了？忘了什么东西吗？」

听到梅莉的呼唤，背对着这边的少女转过头来。她正收拾晚餐用过的炊具锅子，圆睁的双眸映出昴的身影眨了眨。

「──啊」

目睹那名少女的瞬间，昴的身心不由自主地僵住了。

她略显困惑地歪头后，立刻伸直屈着的膝盖唤道「昴？」。接着摇摇晃晃地迎向步履不稳的昴，

「碧翠丝酱，发生什么了吗？总觉得昴他……」

「或许发生了什么呢。不过贝蒂可不会说出口哦。……只是他现在似乎特别想见佩特拉呢」

「见我？」

面对碧翠丝的回答，少女──佩特拉露出呆愣的惊讶表情。近距离看着那丰富的表情变化，昴紧绷的脸颊也渐渐松弛下来。

将发出「唔嗯？」这般意味深长叹息的梅莉抛在身后，昴凝视着正对面的佩特拉，犹豫片刻后

「佩特拉，虽然这话有点怪……可以抱抱你吗？」

「──。不说出来直接抱紧我也行啦。啊，果然，那样还是不行。光是想象就心跳加速到心脏要坏掉──呜」

恶作剧般微笑的佩特拉，那句温柔答复尚未说完时，昴已伸手将她身体拉近，紧紧拥入自己怀中。

「咦、呃……」

面对突如其来的拥抱，佩特拉难掩慌乱。对于近来胆识渐长、逐渐处变不惊的少女而言，这堪称罕见的明显动摇。

但此刻在场之人，无一能出言调侃这般情状。

因为──

「呐，昴，不要紧吗？」

从怀抱中轻轻探出的手，温柔触上昴的脸颊。

面对近在咫尺——近到岂止呼吸相闻，连彼此心跳都几乎相撞的距离传来的少女询问，昴屏住呼吸挤出笑容。

「当然没──」

这是理所当然的。毕竟你看，佩特拉不是这样精神十足地在这里吗。

不只是佩特拉。碧翠丝也好，加菲尔也好，梅莉也好，艾莎也好菲菈姆也好都没事。塔里的大家，没能来到塔里的大家，全都平安无事。

已经发生的坏事，全部都化为乌有了。

当然，我并非知晓全部发生过的事，也知道并非所有发生过的事都是坏事。

有对立与和解，有背叛与友谊，有诀别与重逢，有诅咒与誓言，有憎恨与爱──还有阿尔德巴兰与菜月・昴。

「──或许，并不算没事」

紧抱着佩特拉时，望着始终不离手的魔玉，不经意间，漏出了这句话。

而一旦从唇间溢出的软弱话语，就不会仅止于颤抖的声音。滴滴答答地，真心话化作泪水，从眼角不断涌出。

「──不是的」

本想像个英雄般挺起胸膛，让昴发动『死亡回归』，挽回无数不可挽回之事，并回报那些甘愿留在被置换世界的佩特拉他们。

做不到啊。悲伤又懊悔，为自己的无力感到窝囊，根本挺不起胸膛。

「根本、不行啊……」

对付出巨大代价的佩特拉也好，对理应取回一切的雷姆也好，对直到最后都不放弃与阿尔对话的爱蜜莉娅也好，对虽被一同封印却仍解读禁术术式、让昴得以使用『死亡回归』的碧翠丝也好，对参与那场战斗的、昴认识或不认识的所有人也好——

最后，对连对话机会都没能创造的阿尔──，

「对不起──」

「──昴！」

突如其来的高亢尖锐声音，打断了本该说出口的道歉话语。

那是让咽下话语的胸膛内部、从那里窥视昴的佩特拉的声音。

她圆睁的双眸仿佛被巨大情感所撼动，用轻抚着啪嗒啪嗒掉泪的昴脸庞的手，悄悄拭去那些泪水，

「终于说出来了呢。说自己不算没事」

「──啊」

「不用那么害怕也没关系哦。不必全部一个人承担的。对吧，碧翠丝酱」

「……那是当然。贝蒂可是昴的搭档呀」

被佩特拉催促的碧翠丝，紧紧抱住了昴的身体。面对因两位少女的体温而困惑的昴，佩特拉依然微笑着，

「梅莉酱」

「诶？我就不用了啦。有佩特拉酱她们就够了……」

「梅莉酱」

「……知道啦」

梅莉轻巧地从木桶上跳下，带着不情愿的态度站到昴身旁，轻轻拽了拽他的衣角。仿佛要代替闹别扭的主人般，从她发间窜出的小红蝎爬上昴的肩膀，将身体贴上了他的脸颊。

「加尔菲先生」

「噢！老大！本大爷也在啊！」

他飞扑而来的冲劲撞上后背，令昴发出「呜哦!?」的惨叫。眼看就要向前栽倒，又拼命稳住身形以免压到佩特拉。

无视昴的努力，佩特拉从他怀里探出头望向房间入口，

「艾莎小姐和菲菈姆酱也来吗？」

「我是局外人，就不参与了。不过，我确实是菜月阁下的同伴」

「我刚到这里，还不太清楚状况……不过好吧」

后来出现的气息毫不犹豫地、轻快贴向他的右腰附近。

这下全方位无死角的拥抱姿势完成了。──被这份温暖包围着，昴「哈」地忍不住漏出喘息。

「搞什么啊」

旁人看来──实际上确实有艾莎这个旁观者在，对她而言，现在的昴他们该是多么滑稽的模样啊。

毛茸茸地，大家这样紧贴在一起，简直像笨蛋一样。

「没关系啦。告诉我『当个笨蛋也没关系』的人，不就是昴嘛」

「有这回事？」

「有的啦！」

「……在我认识的人里，大概没有比佩特拉更聪明的了」

他这么想着。肯定没错。所以在聪慧的她眼里定然一览无余。真厉害。这才是真正的聪明。和埃布尔那种聪明的笨蛋完全不同。

然后──

「我决定了」

虽然还顶着哭得稀里哗啦的脸，被温柔的大家从四面八方抱住弄得乱七八糟，刚刚才承认自己一点也不好，但还是决定了。

力不从心和考虑不周，为这些懊悔消沉什么的，可不行。

「阿尔，你好像讨厌我到无法原谅的地步吧」

真正的原因我并不清楚。但，绝不会就这样不明不白地结束。

因为有无数濒临终结的事物，被无数不愿终结的意志挽留了下来，所以完全不行的菜月・昴，下定了决心。

那就是──，

「──我一定会把你也救出来」

即便那是与全世界为敌的暴行，也要将好事坏事全部打包，用『死亡回归』重置一切的菜月・昴的誓言。

听到菜月・昴的誓言，佩特拉・雷蒂满足地点了点头。

正是为菜月・昴付出最多代价、下定最坚定决心、完成最需要勇气的抉择的佩特拉・雷蒂点着头──，

「这才像我的昴」

──于是，未能成为『忧郁魔女』的少女，绽开了花般的笑容。

幕间　『声援』

──对于『忧郁魔女』佩特拉・雷蒂而言，该追寻的、该抵达的、该到达的结局，从一开始就只有一个。

那还是在成为『忧郁魔女』之前，当身为普通村姑的佩特拉・雷蒂读到菜月・昴那本荒谬的『死者之书』时。

那是当她知晓菜月・昴持续战斗着，以自己的『死亡』为代价改变众多人命运时。

那是当她通过与菜月・昴共度的平凡日常，深深爱上这个会为何事喜悦、为何事悲伤、对何事感到幸福与不幸的人时。

──将这些五花八门的理由统统捆扎起来，结局早已注定。

「反正啊，昴你也想帮阿尔先生的对吧？」

老实说，在佩特拉看来这简直离谱。

要是掰着手指数阿尔干过的勾当，就算用尽手脚所有指头都不够数，非得动用『不可视之手』来补足不够掰的手指才行。

那种程度的事，阿尔早就做过不计其数无法挽回的事了。──但即便如此，我也不认为阿尔是天生的极恶之徒，更不觉得他是边嘲笑着一切边犯下那些事的。

「这该不会也是被昴的书毒害的影响吧……」

虽然由自己来说有点那个，但佩特拉是个现实主义者，能承担的范围也很狭窄。与其说是狭窄，不如说是刻意保持狭窄更恰当。

因为啊，佩特拉自信要是将拥有的器量毫不保留地全部用上，自己也是个能塞进相当多东西的容器。这份自信她毫不掩饰。

但就是不想把器量的每个角落都用尽，也不愿珍惜所有能塞进去的东西。

可是──

「昴的贪心……」

但，我就是喜欢这点。──不对。是连这点也喜欢。

正因无法改变这样的菜月・昴，佩特拉・雷蒂才会行动。

这是个如同被剧烈割裂身体，仿佛被无情撕碎心灵般疼痛的决定。

──让菜月・昴发动『死亡回归』，重置所有事件。

从决定离开普雷阿迪斯监视塔、与幻影菜月昴同行的那一刻起，佩特拉・雷蒂就朝着那个结局迈进。

她强硬主张成为『忧郁』魔女因子的持有者，将权能使用伴随的代价支付除部分外全集中在自己身上，毫不吝啬地打出谈判筹码，通过提供所有可传达的情报，决定了『阿尔德巴斯塔斯』的方针。

「如果是因为我读了昴的书才导致『嫉妒魔女』暴走──那这个也能利用起来吧」

这正是阿尔利用『死者之书』设下、反过来利用困住佩特拉的陷阱。

自从『暴食』大罪司教罗伊・阿尔法德被放出监狱塔，意识到其权能效果时，佩特拉心中就有疑问。──倘若阅读过『死者之书』的佩特拉的『记忆』被夺取，『嫉妒魔女』会如何判定。

而这很可能正是阿尔所说的并非意图毁灭世界的、驱散『嫉妒魔女』的作战计划。因此，当『阿尔德巴兰团』全力击溃罗伊・阿尔法德时，他们绑缚着奄奄一息的罗伊，立下了约定。

「如果想吃掉我，我会给你创造机会」

当然，这是若对方不遵守便可毫不留情撕毁的约定。

深受菜月・昴恶劣影响的佩特拉，是个连讨厌之人的约定都能轻易践踏的法外之徒。

而且万一计划实现时，他们还成功拉拢了可靠的盟友作为后盾。

「雷姆姐姐真是太厉害了」

带着深受菜月・昴影响的感慨，她抛开偏爱由衷想道。

雷姆察觉到昴的『死亡回归』──虽最初称为『时间回溯』，但能发现这点，虽说有罗姆爷揭开阿尔权能真相的契机，终究是靠她自己。

雷姆凭借自己意识到菜月・昴是不断牺牲性命战斗之人。──为此欣喜的同时，却也感到不甘。

「但是、正因为如此、才能托付给雷姆姐姐。……不、只有雷姆姐姐才行」

即便旅途中会遇到多少好事、获得多少难以割舍的回忆，佩特拉・雷蒂也决心要将这一切全部推翻、当作从未发生过。

而这甚至意味着、连终于取回『名字』与『记忆』、真正意义上归来的雷姆的存在、也要一并抹消。

对于明知如此仍要行动的佩特拉来说、她有义务将雷姆卷入其中。

作为同样知晓会消失的同志、作为从心底不愿让最珍视之人错过任何事物的女性。

唯有深信除此之外别无选择、为了爱能舍弃一切的人、才值得托付。

那种拼命寻找其他更好答案、直到最后一刻都不放弃的人、根本没法托付这么残酷的事。

所以能做到这件事的、只有佩特拉和雷姆两个人。

「菜月·昴和爱蜜莉娅姐姐都累坏了吧。对不起呀。明明这样我还成了累赘。对不起呀。明明想一直一直、向你们道永远不够的谢……」

想传达谢谢、真正意义上的谢谢。

作为读过《死者之书》知晓一切的佩特拉・雷蒂、本想声援踏上荆棘之路的爱蜜莉娅与粉身碎骨持续支撑她的菜月・昴的那条道路。

这已无法实现。佩特拉・雷蒂虽拼尽全力、但终将变回一无所知的村姑。

正因如此才不甘心、才悲伤、才说不尽谢谢与对不起。

即便如此──

「……能做的事、全都做了吧」

在有限的状况下、自己应该已经竭尽全力了吧。

就连阿尔也准备了确保不败的全明星阵容。要推翻这点却只能试错一次、实在是场不公平的战斗。

但还是做到了。真的做到了。中途本应失去记忆的奥托参战时确实有点慌、不过这就是全员参与的成果吧。

「呵呵～这样是不是超厉害？爱上我了吗？」

『──。是啊。快爱上了』

歪着小脑袋，用自己能摆出的最可爱表情迎接对方。

面对佩特拉这般可爱的举止和提问，幻影菜月昴害羞地笑了。

这是佩特拉想让他说出口的诡计？还是说连真人都会说出口的逼真演技？

「反正消失前，就往对自己有利的方向理解吧」

轻轻伸手，将无法触碰的手叠在一起，十指交缠。这种程度的幻影特权，总该被允许吧。毕竟已经很努力了。

『话说，能问个问题吗？虽然以我的立场问这个有点怪』

「嗯～？什么呀？」

『从柯林特先生那里获得魔女因子前，佩特拉你曾为移动支付过一次代价……但没告诉我吧？那个到底是什么呢』

「既然当时没让你听到，不如就这样永远别问？」

『太残忍了吧』

看着对方可怜兮兮的表情也觉得可爱，佩特拉噗嗤轻笑。

不过果然，就算是幻影昴也是昴。佩特拉不想被看到、不想被知道而隐藏的事，哪怕是脑袋里的住人也不能擅自行动。

对此感到安心的佩特拉吐了吐舌头，

「嘿—咻」

虽然让幻影菜月昴露出了苦涩的表情，但佩特拉就是想隐藏。

就算有一个不想让幻影菜月昴看到的少女秘密也无妨。而且这个少女秘密里，还带着一点点少女心的狡猾。

那时候，佩特拉向柯林特献上了自己的某个可能性作为代价。

那就是──，

「──我要成为昴新娘的可能性」

知晓佩特拉心意的柯林特，当时的惊讶程度相当夸张。

看到献上自己幸福未来可能性的佩特拉时，那个背负沉重历史的龙人族超越者柯林特的热泪盈眶反应令人难忘。

所以，真的很抱歉。──因为佩特拉通过那个代价确信了。

「如果能用那个当代价的话，就说明我真的拥有那个未来的可能性」

从『忧郁』魔女因子的特性来看，准确来说应该是『为了获得佩特拉与昴结婚的未来而付出的努力』这种对世界影响力的献祭吧。

不过，这些细枝末节对那时的佩特拉而言根本无关紧要。

重要的是佩特拉・雷蒂能够相信自己会成为菜月・昴的新娘。

而这点，正是触及世界核心的魔女因子为她证明的。

正因为有了这份确证，她才能下定决心坚持到底，直到最后一刻都在全力奔跑。

所以──

「要加油啊，我。──能否抓住机会全看我的努力了哟」

这是成为『忧郁魔女』的她，向那个没有成为『忧郁魔女』的未来自己送上的应援——来自一个为自身幸福利用魔女因子的村姑。

──这份来自异世界女孩既坚韧又精明的爱之应援，着实有些沉重。

** 第七章 『Reweave』

１

──远远望着跋利耶尔宅邸工作的仆人们，法兰黛莉卡始终无法平息心中那份焦躁。

「与老爷同行享受宾客待遇是常有的事……但在如今的宅邸里，规矩就有些不同了呢」

法兰黛莉卡如此抱怨时，翠绿眼眸中映出的是宅邸内忙乱的景象。

能看出这里聚集着行动利落、纪律严明的优秀人才。即便得知法兰黛莉卡他们带回的噩耗，仍能维持正常运作。──单凭这点就值得敬佩。

「普莉希拉大人似乎深受爱戴呢」

传达给佣人们的噩耗──正是宅邸主人、同时也是她们主君的普莉希拉・跋利耶尔，在佛拉基亚帝国丧命的讣告。

「────」

法兰黛莉卡微微垂目，从阳台俯瞰着庭院与宅邸轻叹。

法兰黛莉卡也因自身立场，对罗兹瓦尔和爱蜜莉娅等侍奉对象抛下自己离开宅邸，只能祈祷其平安归来的心境深有体会。当得知这份祈祷未能实现时，内心该承受多大的冲击啊。

事实上有许多佣人陷入悲伤，流泪者亦不在少数。得知噩耗后无一人离开宅邸，亦可说是与普莉希拉关系的体现。

不过这其中并不仅因普莉希拉受人仰慕──

「──修尔特大人毅然的态度，打动了我们的心」

令法兰黛莉卡深受触动的，正是那位随普莉希拉同赴帝国、肩负传达其死讯与遗志之责，并完美达成使命的年幼从者的姿态。

看似纤细如小动物般不可靠的修尔特，却未将招人怨恨的角色推给罗兹瓦尔或法兰黛莉卡，而是亲口陈述，以言语完成了重任。

佣人们选择不离宅邸、继续现有职务，对普莉希拉的追慕之情与对修尔特的信赖无疑起了重要作用。就连作为局外人的法兰黛莉卡也红着眼眶表示赞同。

所以──

「──哎呀，原来在这儿啊，法兰黛莉卡。害我好找～呀」

「老爷……」

轻轻抬手，踏入阳台的高挑身影──罗兹瓦尔迎面而来，法兰黛莉卡当即屈膝行礼。

「劳您亲自寻找，实在抱歉。请问有何要事？」

「要说要事也算不上呢──。这边刚处理好准备工作，只是想和你聊聊罢了」

「准备工作……」

「没错，就是准备工作哟──」

罗兹瓦尔眯起异色双瞳中黄色的那只，挂着浅笑走到栏杆旁的法兰黛莉卡身侧，背靠栏杆说道

「这片土地颇值得玩味。我在南部熟人不多。普莉希拉大人已故的丈夫莱普・跋利耶尔卿，风评可不怎么好呢──」

「被老爷这么说，那位想必会很不满吧」

「哎呀，真严厉。你也像佩特拉那样，渐渐失去对我的顺从了吗──？还是说──」

歪着头的罗兹瓦尔突然凝视身旁法兰黛莉卡的眼睛

「──你反感我利用修尔特君的计划？」

「……我并不认为老爷的所作所为是错误的。那是为了王选……更进一步说，是为了爱蜜莉娅大人和阵营的利益，这一点我也心知肚明」

「道理上虽然如此，但要打心底里接受可没那么容易呢～」

正因为明白这点还故意说出来，才显得罗兹瓦尔性格恶劣到骨子里。在爱蜜莉看来，这大概就是希望有人能好好管教他的恶作剧心理表现吧。

「以我和老爷的关系，这很难办到呢，爱蜜莉娅大人……」

如果此刻在场的是爱蜜莉娅或佩特拉就能用正道，拉姆在场就能用邪道促使罗兹瓦尔反省了吧。但或许预料到这点，现在这里只有法兰黛莉卡。

而法兰黛莉卡即使抛开无法偿还的恩情不谈，也明白罗兹瓦尔故作恶人的行径终究是为了阵营。

──爱蜜莉娅阵营能团结一致的最大目的，归根结底还是王选。

在那场王选中，爱蜜莉娅从加入佛拉基亚帝国开始就全程落后。即便不算这点，她起步就已慢人一拍。要想扳回这落后的一圈，甚至伺机获得推进力，就不能只靠正面进攻。

为此，罗兹瓦尔正默默推进着忠心耿耿的暗中活动——试图拉拢刚失去普莉希拉・跋利耶尔这根顶梁柱的跋利耶尔领地。

「既然普莉希拉大人已逝，在选出下任领主前需设置代理暂政官。所幸我能从亲信中推出候选人，联络员则借用琉兹大人麾下『梅尔兹』中的一位即可」

「……把老婆婆的那些孩子牵扯进来，是否为时尚早？」

「俗话说得好，要让可爱的孩子去旅行？若一直殷勤地将他们关在金丝笼里，就永远学不会振翅。我也深表同意——呀」

看着罗兹瓦尔步步为营、滴水不漏地推进计划，法兰黛莉卡不禁怀疑爱蜜莉娅对罗兹瓦尔的评价是否属实——他并非伪善者，而是真正的恶徒。

或许正因为连扮演反派都能做到天衣无缝，他才始终无法真正获得阵营同伴们的信任。实在太过较真了。

「老爷，至少该稍微手下留——」

正当她想要指出这点，以免这个误会不仅在阵营内部，更会在跋利耶尔领地乃至修尔特心中埋下巨大疑虑时——

「——糟、糟糟、糟糕了！边境伯大人，您在哪儿啊！?」

「刚才那是...修尔特大人？」

突然听到下方传来修尔特惊慌失措的声音，法兰黛莉卡与罗兹瓦尔对视。挑眉的罗兹瓦尔似乎也毫无头绪，离开栏杆的主人转身对庭院里冲出来的修尔特唤道：「修尔特君」。

被叫住的修尔特顿时睁圆了骨碌碌的眼睛，

「边境伯大人！请您立刻过来！有位想见您的人，还有件必须请您聆听的要事！」

「──方才您所目睹的，正是已故夫人的遗志」

「────」

自称八重・天膳的红发少女女仆说完这番话，揭开了火漆封印的信件内容，罗兹瓦尔闻言瞪大了凝固的双眼。

鲜少见到主人如此明显的动摇神情，但这反应也情有可原。就连确认过相同内容的法兰黛莉卡，以及在场的所有人都被震惊笼罩。

尤其是作为信件内容核心人物的修尔特，他所受的冲击最为强烈。

那封信的内容是──

『──跋利耶尔家现任当家普莉希拉・跋利耶尔，为确立正式继承人，特此宣布将名为修尔特之人改姓为修尔特・跋利耶尔，迎入跋利耶尔家作为嫡子及继承人』

「普莉希拉大人，要选我……？」

面对突如其来的变故，修尔特不停眨着眼睛，露出分不清梦境与现实的表情。

然而，从后方将手搭在如此震惊的修尔特双肩上，透露了信件下落的八重边微笑着，边用脸颊蹭着少年说道「你也太吃惊了吧」。

「考虑到夫人对修尔特君的溺爱程度，这不是完全有可能的事吗？──虽然我想若是真的，原本是打算在王选期间保密的」

「八重大人……八重大人是何时知晓此事的？明明几个月前就离开宅邸，好不容易才回来……」

「──。我知道的时候，夫人和修尔特君正要启程前往帝国呢。准备那封信也是差不多那时候」

听到八重平静的回答，修尔特眼中积聚起大颗泪珠。

据闻，八重曾是这座宅邸的女仆，暂时休假期间得知普莉希拉死讯后匆忙赶回。

正如所见，与修尔特关系亲密的八重似乎深得普莉希拉信任，甚至被委以保管她遗书中重要信件之责。

这个真相的揭露，将极大扰乱罗兹瓦尔的计划──

「──不过考虑到修尔特大人的情况，或许这样也不错呢」

「……法兰黛莉卡？」

「虽然可能与老爷的初衷稍有出入……但修尔特大人和宅邸众人的心灵应该都能得到救赎呢。──她真是位了不起的人物啊」

尽管身为王选候补且与爱蜜莉娅敌对立场，法兰黛莉卡不得不将几乎毫无交集的普莉希拉评价为非凡人物。

毕竟──

「能如此偏离老爷的算计，毫无疑问定是爱蜜莉娅大人的劲敌呢」

２

「────」

八重再次垂眸看向遗留的信笺，从背后抱住那具微微颤抖的娇小身躯时，不禁为自己选择返回跋利耶尔宅邸的决定轻叹。

──这一切都是为了协助阿尔达成他追求的目标而做出的判断。

「没有信号就说明～塔里的计划失败了吧～」

原本八重应与前往普雷阿迪斯监视塔的阿尔在最近城镇汇合，协助完成他所谓的使命，并履行见证其生命终局的约定。

然而，到了指定时间仍未收到汇合信号，八重判断阿尔的计划失败，便从最近的城镇撤离──随即径直返回了跋利耶尔领地。

「这么大摇大摆地回到宅邸，还是自从夫人暗杀被阿尔大人阻止以来的头一回吧」

不过，若是不引人注目的形式，她其实为了与阿尔保持联络而相当频繁地出入宅邸。──就连用作返回宅邸借口的书信，也是在这些不引人注目的出入期间，躲在阁楼里获取的情报。

虽然对修尔特，以及企图从中渔利的恶劣贵族──罗兹瓦尔・L・梅札斯及其随从女仆谎称是普莉希拉托付的书信。

「实际上，不过是偷看到夫人准备妥当后收进秘密金库的过程罢了」

正因为收信的金库是隐蔽金库，这封无人知晓其存在的书信得以曝光，八重作为被托付秘密的一方赢得了信任。为此虽对利用已故的普莉希拉稍感愧疚──

「──不过夫人啊，您真以为我没看见吗？」

说实话，那即便是八重心中也无法明确解答的谜团。

普莉希拉准备收养修尔特的文书是在前往帝国前夕，将其收进金库也是同期之事。但八重虽只是短暂侍奉过那位主人，却不敢小觑她的洞察力。那位能洞穿他人内心的女中豪杰，当真相信过八重已离开吗？

『──好好利用这份文书为自己谋利吧。顺带把修尔特救出来』

将文书藏在若非掀翻宅邸就绝不可能发现的隐蔽金库里——那金库连潜伏阁楼的八重都找不到——恐怕正是普莉希拉的刻意安排。

无论如何──

「那我就恭敬不如从命了，夫人。──因为我得等着阿尔大人」

决定接受普莉希拉好意的八重，为此回到了宅邸。

如前所述，未能发出继续行动信号的阿尔，很可能在监视塔遭遇失败导致计划难以推进。但阿尔不会死。他还活着。

「毕竟阿尔大人可是个怪物呢」

阿尔不会死、杀不死的怪物。正因为如此，八重才会追随他。

为了见证他达成目的心满意足地死去，见证自己恐惧的存在消失的那一刻。──为此，必须让修尔特与爱蜜莉娅阵营保持距离。

若阿尔遭遇不测，必定与同往监视塔的爱蜜莉娅阵营有关。必须时刻待在能立即行动的位置，防备他随时可能脱身。

所以──

「修尔特酱，让我们继承夫人的遗志吧。没问题的。今后我也会回到宅邸，继续协助修尔特酱哦」

「八重大人……是。遵命……！　我、我定要回应普莉希拉大人的期待！　这份协助之责，恳请八重大人来担当！」

面对率真可爱的修尔特──不，已成为修尔特・跋利耶尔的少年这番决心，八重夸张地眯起眼梢，其他佣人们也感动得眼眶湿润。罗兹瓦尔随行的女仆用手指拭去眼角泪水，被这份坚毅深深打动。

似乎只有算盘落空的边境伯露出暧昧神情，但即便死后，普莉希拉仍能凌驾他人算计的事实令人痛快。

没错，普莉希拉是值得效忠的主人。──唯有这点，千真万确。

「在下、会加油的！　因为想在阿尔大人和亨克尔大人回来时、展现出优秀的样子！」

只是、对着这样满脸通红干劲十足的修尔特、八重犹豫着该如何回答。

期盼阿尔归来的心情八重也是一样的。但关于亨克尔──、

「……亨克尔大人嘛～可能暂时有点难回来呢～」

３

「──咕哇啊！」

伴随着漂浮感的下一秒就坠落地面，亨克尔发出了低沉的惨叫。

呻吟片刻后，缓缓转动四肢解开束缚。当被细绳捆住的手脚重获自由时，他确认着久违的解放感──

「该死的……！」

他如此愤懑不平，像诅咒发生在自己身上的不幸般狠狠啐了一口。

──将亨克尔捆绑起来，丢在无人造访的森林小屋中的，是一位自称阿尔德巴兰协助者的少女八重。

她原本是侍奉普莉希拉的女仆，又是被派遣来暗杀的刺客，这段莫名其妙的经历后，她怂恿道只要协助阿尔德巴兰，就能获得亨克尔梦寐以求之物──『龙血』的机会。明明是她先来蛊惑的。

「阿尔德巴兰那混蛋一断联，计划就泡汤了开什么玩笑……」

最后，当亨克尔要求她说明并继续计划时，她毫不留情地用膝撞和肘击殴打，把鼻血直流的他捆起来后迅速消失了。

对亨克尔而言，根本没理由遭受这种过河拆桥的对待。

「一个个的，全都……」

原本仰仗的普莉希拉死了，想转而依靠的爱蜜莉娅又拒绝了他，当他试图抓住阿尔德巴兰伸来的援手时，却被甩开手坠入了深渊。

结果，亨克尔的前景又倒退回了王选开始前的死胡同。

「但是，即便如此……」

无法放弃。怎么也放弃不了。甚至连放弃这件事，都从未做到过。

摇摇晃晃地站起身来，用袖子擦干早已凝固的鼻血，迈步前行。那双脚要迈向何方毫无头绪。即便没有方向，也无法停下脚步。

──因为亨克尔・阿斯特雷亚，是丈夫，也是父亲。

「等着我，卢安娜、莱因哈鲁特。我……我会……」

沙沙地拖着脚步，将手搭在腰间悬挂的剑柄上，亨克尔继续前行。

没有目标。──只有多年来缠绕着的、锈迹斑斑的祈祷。

４

「──最后还是闹得鸡飞狗跳匆匆忙忙的，真是抱歉，艾莎小姐」

「不，这也是没办法的事。情况有变我们这边也清楚。现阶段在交接人员到来前我不能离开这里，但有必要的话随时可以作证」

「帮大忙了。……真的」

小声这么嘀咕着，昴向彬彬有礼应对的艾莎低头致谢。

地点是普雷阿迪斯监视塔的五层，眼前矗立着巨大门扉的宽阔楼层。在这里昴──不，昴一行人再次打点好行装，正准备早早离开高塔。

仅仅停留了半日，趁着塔外天色转亮的清晨便启程出发。

「总觉得啊，哥哥们老是这么慌慌张张的呢。就不能更安稳点从塔里回去吗」

「说得对呢。上次是被抛到帝国，这次又是这样匆忙折返」

「那又不是昴的错啦。全都是阿尔先生的错……真是的，都不知道该怎么说修尔特君了。……阿尔先生这个大笨蛋」

最后轻声补充着对话的，是回归组的少女们。

当然，对于演变成这样的状况，每个人都有自己的想法。无论是仅停留半日，还是不得不仓促离去，亦或是招致这般局面的缘由。

只是作为昴来说，看着引发事端的人一直被谴责也很不好受。

「老大，行李都装上龙车啦。随时都能出发咯」

就在这时，加菲尔微微推开大门从外面回来搭话。他早一步去龙车帮忙装载行李，此刻对举起手的昴皱起眉头，

「摆出这副抠抠搜搜的臭脸干啥啊老大。跟『劳拉吉的倒刺』一个德行，俺懂你心里膈应但也没辙啊」

「嗯，我知道你想给我打气，但完全没共鸣啊。倒刺？劳拉吉？」

「说啥傻话呢！一旦发生的事就改变不了。所以，现在该琢磨的是接下来怎么办对吧？本大爷啥忙都愿意帮」

加菲尔露出獠牙笑着，用力拍了拍昴的肩膀。

那股威力，差点让昴那瘦弱的肩膀粉碎，但心里却是百分百的开心。而且，正如加菲尔所说──既然决定了要做，从这里开始才是最重要的。

「──我会好好弄清楚的。自己究竟背负了什么」

说着，昴摸了摸自己的胸口──挂在脖子上的魔玉，表明了决心。

──和这颗魔玉一样，昴和碧翠丝也被封印其中，在此期间阿尔掀起的那场大战，其详细情况我们并不清楚。

魔玉内部一片漆黑，身体无法动弹，意识也模糊不清，就像变回胎儿浸泡在母亲子宫的羊水中一般，始终沉浸在那种如梦似幻的状态里。

在那里连昴的梦境都飘忽不定，没有什么是确凿的。虽然可爱的碧翠丝仍顽强地分析着封印我们的禁术并试图破解术式，但昴能做的只有在保有类似意识的时刻，发动『强欲』权能──『柯尔・雷欧尼斯』来感知附近同伴的存在与强烈的情感波动。

即便如此，由于对同伴的思念与拼死决心，加上情感剧烈起伏的不断重复，灵魂始终能感知到事态正朝着非比寻常的方向发展。

其中尤为突出的，是觉悟与决心色彩强烈的佩特拉，以及对昴怀抱着只能用庞大・肥大来形容的感情的雷姆。──正因如此，昴才能带着确信提出清晨离塔的方针。

这固然是因为造访普雷阿迪斯监视塔的目的本就是阿尔，得知那只是他的借口后已失去意义，但不仅如此──

「──『暴食』大罪司教肯定有办法把吃掉的东西好好吐出来，对吧？」

「没错。那里有至今被吞噬的人们……也有雷姆的『记忆』和『名字』」

或许是对『死亡回归』前轮回中，最巧妙将『暴食』权能用于作战的佩特拉的话语，昴深深点头。

那一瞬间，连言语都来不及交换的刹那，用理解一切的眼神将晨星砸向昴的雷姆。──她华丽操控着昴每日打磨的带刺铁球，确实已取回自我。这毫无疑问是『暴食』干涉所致。

既然能确信这点，而且『暴食』的躯体也已被控制。没有理由不乘胜追击，逼他把吃掉的东西吐出来。

所以，为了这次直接谈判──，

「──走着瞧吧，怀念的王都！去见『暴食』，让他把一切都吐出来！再说了，对王国的历史也好，这个世界的历史也好，我似乎都不能无动于衷」

想起被指尖捏住的魔玉深处封印的阿尔，昴告诫着自己。

听到昴这番决心宣言，并肩而立的碧翠丝握紧他的手，加菲尔用手指抚过自己的獠牙，梅莉则耸了耸停着小红蝎的肩膀。

接着，昴迎向佩特拉那凛然坚毅的微笑目光。

为了那个自称阿尔德巴兰、『昴的尾随星』，用与昴相同的力量对抗却又立誓必救的存在，菜月・昴向着王都进发。

去知晓吧。因为已经明白，一无所知是不诚实的，会让自己无法原谅自己。

所以──，

「──命运女神，放马过来吧！」

背负着思念，跨越横亘在前的诅咒，菜月・昴如此宣言道。

５

──就在菜月・昴表明决意的同一时刻。

此刻在遥远之地，当菜月・昴宣告要启程前往的目的地──亲龙王国露格尼卡的王都中，正发生着某桩异变。

「────」

正值王都民众大多尚在睡梦中错过黎明时分的清晨，本应被寂静笼罩的露格尼卡王城，却弥漫着异常的氛围。

这股异样的源头，正是王城中央──王座之间。

因王室病逝导致王选开启的王城，在国王空缺期间，除非举行重要典礼，否则王座之间始终紧闭大门。

但此日此刻，王座之间的大门却洞开着，王国重臣──『贤人会』成员、深受已故国王信赖的家臣们，乃至散发着肃杀气息的王国兵尽数聚集于此。

「────」

这些人无一不是在无王之国度里肩负重任的要员。

无论是清晨的召集还是迟到者都未曾出现，那些睡眼惺忪或态度散漫的混账家伙，此刻在场者中一个也不存在。

因此，不论时段如何，此刻汇聚于此的目光重量堪称等同于整个王国。

──而那位女性正沐浴在这般注视中，却仍保持着静谧的气场。

「────」

铺着红毯的大理石地面上，单膝跪地的是位身披蓝衣、双手交叠胸前低垂头颅的人物。那祈祷姿态如此精妙，令武官想起武技要诀，文官忆起礼仪规范，不禁暗自叹息。

仅凭祈祷的姿势，女性便已彻底震慑全场。

「──嗯哼。能否请您，抬起头来呢」

人群中唯有一人未被女性的祈祷姿态吸引，此刻发出了声音。

那温和理性、令听者自然生出这般印象的声线主人，正是迎接跪拜少女的城中要员之一──不，甚至可说是代表人物的存在。

麦克罗托夫・马克马洪。──在国王缺席的露格尼卡王国中，这位执掌国政舵轮的『贤人会』核心人物，即便在这场临时设立的场合里，依然是拥有最大发言权与决定权的大人物。

这位以卓越智谋和对王国非凡忠诚贡献著称的智者，其存在感之巨大，甚至让国王本人都曾开玩笑说「即便露格尼卡国王死了国家也不会动摇，但若他死了王国就会灭亡」。

温柔的外貌与平和的谈吐容易招致误解，实则却是露格尼卡王国中若为盟友则最可靠、若为敌手则最可怕的杰出人物。──麦克罗托夫正是长久以来完美契合这般评价的存在。

「──嗯」

听到麦克罗托夫的话语，低着头的女性缓缓抬起脸庞。当紧闭的眼睑睁开时，与她四目相对的麦克罗托夫微微倒抽一口气。

麦克罗托夫的这个反应并非他独有。作为同属『贤人会』一员在场的波尔多・谢尔盖夫、以武官代表身份立于近卫骑士团长的马科斯・吉尔达库、作为文官核心人物的利凯鲁特・霍夫曼，以及其他所有此刻身处王座之间的人们，都各自产生了反应。

仅是存在于此就天然吸引所有人视线的魔性女子。但此刻众人的反应，并不仅因她的姿态而起。──而是容貌。

那长而绚烂的金发与寄宿着凛然强韧意志的绯红双眸，以超越单纯美丽的冲击力，刺穿了在场──不，是整个露格尼卡王国人们的意识。

然后──，

「──首先为突然造访致歉，同时感谢诸位欣然接纳。考虑到彼此立场，这本该是非所愿之事」

女子仿佛早已习惯这般注视，单膝跪地的姿态扫视着在场的贤人与要人们，如此开口说道。

既不过分谦卑、也不失分寸的她一开口，在场众人便压下短暂的惊讶与动摇，将应对之事委任给自己的代表麦克罗托夫。

领会到这层意图后，坐在椅子上的麦克罗托夫用手指捋着自己蓄的长长胡须，轻叹一声「唔」，

「哎呀呀，这可真是说了件难以启齿的事呢。不过，装腔作势也没意义吧。毕竟您所言确是事实。」

「您能如此直言不讳，我也如释重负。毕竟我这般资历尚浅，方才还战战兢兢生怕在各位面前说不出话来。」

「唔，话虽如此您倒是泰然自若。看来很习惯成为众人焦点呢。心里有数的……恐怕不止一两点吧。」

「是啊。我不否认。」

虽有着近乎祖孙的年龄差，但麦克罗托夫与女性的对答毫无滞涩，似乎不会因身份差异演变成单方面的试探。

双方都不约而同地这样判断后，如同突然泄了气般同时微笑起来，

「这么一大清早的，可不能随意占用各位繁忙的时间。那我就直截了当……请允许我进入正题」

「嗯，这样也好。我这把年纪早起倒不觉得辛苦，但重要的事无论多大年纪都难以忍受被拖延。──更何况这还是来自与王城保持距离的『神龙教会』的发言，就更是如此了」

「────」

本该从容不迫地推进话题，麦克罗托夫的话却让室内空气骤然紧绷。虽然这立刻因对孤身前来王城的女性失礼而缓和，但个中缘由在场所有人都心知肚明却无可奈何。

麦克罗托夫提及的『神龙教会』，顾名思义是尊崇『神龙』波克肯尼卡存在，信仰其力量恩惠与守护盟约的宗教团体。正如露格尼卡王国自称『亲龙王国』，以与『龙』的深厚渊源著称，只要是王国子民，或多或少都蒙受过『神龙』恩惠。

正是出于这种自觉，即便没有正式隶属教会，露格尼卡国民大多也对『神龙』怀有敬畏之心。在这样的环境中，那些正式隶属教会的人对『神龙』怀有多么强烈的信仰更是不言而喻。

为了防止这股巨大影响力动摇国政，『神龙教会』不靠近执掌王权的王城，双方各自在领地内为国民的幸福做贡献。──这是彼此心照不宣的默契。

正因如此，『神龙教会』的修女造访王城，并要在包括『贤人会』在内的众人面前发言，实属破例之举。

只是──

「──这是值得的」

正因为明白这是破例之举，才有足够理由打破这项不成文的规定。

女子这句斩钉截铁的断言，确实起到了让麦克罗托夫等人聚集于王座之间，并让他们对即将听闻的内容产生期待的作用。

因此，女子遵从贤人们无声的催促，道出了──自己此行的理由。

「近来王国的危难，『神龙教会』全体信徒都深感忧虑。虽因默契而与国事——王位选拔战……王选保持距离，但听闻水门都市灾祸一事后，实在坐立难安」

「水门都市……普利斯提拉的魔女教事件吧。我等也为该都市的受灾痛心不已，但总不至于『神龙教会』要对涉事王选候补者们提出劝诫吧？」

「若真如此，就与你们打破默契急忙赶来的用意，以及值得听取意见的说法自相矛盾了。……很矛盾」

脱口而出的反驳暴露了本性，慌忙改口的模样显出女子的年轻。为掩饰尴尬，她轻轻干咳一声，

「总之，对王选候补们并无怨言。虽说其中确实存在想提意见的对象，但这不是『神龙教会』的集体意志，仅属个人见解」

「若非教会立场，那便是作为王国国民的坦率意见。反倒该积极倾听才是……嗯哼，不过这就偏离主题了」

「是啊。麦克罗托夫大人是位健谈之人这点我会记住，但言归正传。──我们想讨论的并非追责，而是受害情况」

「──。愿闻其详」

「在水门都市普利斯提拉遭受魔女教侵害的人们……据说已确认多起病例，『神龙教会』能够提供救济手段」

──刹那间，这句话的含义令整个王座厅的空气剧烈躁动。

但作为骚动源头的女性始终保持着凛然姿态，即便承受着贤者们审视的目光也依旧笔直正视前方。她的眼神与态度毫无动摇，显然若非胸有成竹绝不会如此断言。

「──嗯」

麦克罗托夫用这声简短的附和斩断了躁动的空气。

即便如此，身为王国首屈一指贤者的麦克罗托夫也不禁对这提议感到震惊。贤者用手指轻捻胡须的动作泄露了些许忙乱，

「若此事属实，实在是求之不得。将这个消息带来王城的……」

「光靠我们擅自推进事务，恐怕不会得到好脸色吧。况且」

「不会给好脸色的不仅是咱们城里的人，魔女教也是吧」

对这不言而喻的事实，女子也轻点下巴向麦克罗托夫表示赞同。

当然，若能抹消魔女教造成的损害，对魔女教而言也绝非乐见之事。正因如此，『神龙教会』才渴望这般局面。

「──王国切实的庇护。由于掌管国政的我们与执掌信仰的『神龙教会』之间存在隔阂，多年来始终未能真正实现呢」

「是的，正是如此。想借此机会实现它。这是『神龙教会』的集体意志。──为促成这个决断，我们有个提案」

「嗯哼，提案吗？说来听听」

「首先请您过目。我们能实施的救济措施，其实际验证」

女子将手按在胸前说完这话，麦克罗托夫惊讶地扬起眉毛。

这简直是求之不得的提议。如她所言，作为判断材料无可挑剔。只不过，要把水门都市的受害者立即带到王都来──

「您心中应该已有一个人选。第一位就由那位担任」

「──。好吧。首先，允许你提出议案。──马科斯团长」

「是！」

被麦克罗托夫点名后，铠甲巨汉以洪亮声音应答，这位王国近卫骑士团团长马科斯上前向『贤人会』席位敬礼。

「能否请您带她过来。这关系到王国存亡。务必谨慎」

「遵命。──我将亲自陪同前往」

「好的，大脸……不对，是大块头的先生。拜托您了」

女性轻轻低头行礼，她表情也显出几分柔和。或许因为事态正按她期望发展，来自『神龙教会』的访问目的即将达成。

麦克罗托夫明知会显得唐突，仍向她发问。

关于这位自称『神龙教会』使者、清早就召集麦克罗托夫等王国重臣入城的女性，比其教会身份更引人注目的原因。

那就是──

「──非常失礼，能否请教您的名字呢，修女大人」

６

「──我是从『神龙教会』派遣来的修女哦」

被马科斯亲自带领、造访王侯馆的女性──自称修女的对象面前，菲利斯难以掩饰困惑。

菲利斯与威尔海姆一同滞留王都的目的，是为了向王城直接请愿──获准加入前往已开放的普雷阿迪斯监视塔的调查团，向被赞颂为全知全能的『贤者』求教能解救至今仍持续痛苦的库珥修的方法。

当然，已经从普雷阿迪斯监视塔归来的爱蜜莉娅等人来信告知，『贤者』的存在与其智慧并非如此便利之物。但即便如此，比起迟迟没有进展的治疗魔法开发，这仍是更具可能性的途径。

「真是，蠢透了。无论怎么改良现有治疗魔法，都只是让自己不会死掉，连库珥修大人的一丝痛苦都消除不了」

怀着近乎执念的『青』之研究，虽在短期内将现存露格尼卡王国的治疗魔法水平提升不是一级而是三级，但对现在的菲利斯而言毫无价值。

眼下、最想救的人却救不了。这个事实将菲利斯逼入绝境，坠入黑暗。

所以、才想依靠普雷阿迪斯监视塔和『贤者』的睿智──

「……库珥修大人、真的能得救？『神龙教会』？真、真的吗？」

「信仰不容谎言、我们也没有折磨迷途之人的兴趣。就算信不过我这修女、总该信得过你们团长吧」

修女回应声音颤抖的菲利斯、用手示意同行的马科斯。当菲利斯对马科斯喊出「团长！」的高亢声音时、他如岩石般坚毅地点头、

「听闻『神龙教会』掌握着未公开的魔法与术技。以麦克罗托夫大人为首的『贤人会』诸位也认为值得信赖」

「……可、可是、如果库珥修大人又出了什么意外」

「──『奎因之石无法独自升起』」

「──！」

修女平静道出的这句话、让菲利斯不禁倒抽一口气。

在涌动的感情乱流中湿润双眸的菲利斯，修女轻轻向她伸出手，用纤细的手指一根根温柔地解开菲利斯紧紧攥住的拳头。

任人摆布的菲利斯，忽然注意到她美丽的金发和蕴含认真光芒的绯红眼眸，不由得看得入神。

加速混乱的认知，不明白这意味着什么──

「求求你。请让我拯救你重要的人吧。『神龙教会』始终祈愿着王国子民的幸福。无论秉持何种主义，这一点都不会改变」

「啊、你是……你究竟是谁？」

「────」

面对菲利斯的质问屏住呼吸，但她用眨眼压下细微犹豫，仍温柔握着这边的手回答道。

那是──

「──菲尔奥蕾。这就是，我的名字」

──十五年前从王城被掳走下落不明的王弟之女。拥有王族特征的金发红瞳的修女，报出了与那位消失的公主相同的名字。

《完》

** 后记

庆祝第九章完结！非常感谢！我是长月达平！我是鼠色猫！

因此，该称为阿尔德巴兰篇的第九章顺利完结了！我在后记中一直强调的『疾风怒涛』主题，是否成功守住了呢？作者自负地认为这章保持了高涨的张力，给人一气呵成的强烈感受。

话说这次我想认真写后记，所以后记篇幅没用往常狭窄的分栏排版。

无论如何，第九章就是阿尔德巴兰的故事。

原本他以「戴头盔遮脸、能娴熟使用和昴相同现代世界语言的异世界人」这个噱头登场时，就明显是故事重要人物，但详情长期秘而不宣。如今突然反转，在主角缺席的第九章扛起大梁——在这种情境下，阿尔德巴兰的表现超出了我的预期。

从作品序章开始，《Re:Zero》就埋下了许多持续贯穿的重大伏笔和未解之谜，而第九章则翻开了多张这样的暗牌，将其暴露在光天化日之下。当然，看完第九章的结局后，想必大家都迫不及待想看到真正意义上的揭牌之日，不过包括阿尔德巴兰相关剧情在内，能透露的内容很多，作者现在可是相当畅快。

想必各位也明白，第九章的收尾方式在开篇时就已确定。因为作者想在第九章做的，就是重新描绘『死亡回归』。

随着卷数累积章节推进，帝国篇因剧情残酷而频繁使用『死亡回归』，但在封禁这种『死亡回归』后，又描绘了阿尔德巴兰带来的另一种『死亡回归』，最终菜月・昴的『死亡回归』成为决胜一击──。

正因平时采用昴的视角才无法展现的、『死亡回归』另一面的无常感，若能通过第九章让各位体会到，那这番描写就真正有了价值。

──『死亡回归』很恶心。这正是我在写Re:Zero时不想忘记的初心。

在第九章中不仅描写了阿尔德巴兰一伙，还能展现久违的菲鲁特阵营的活跃、莱因哈鲁特的超人表现以及佩特拉・雷蒂的故事真是太好了。第九章既是阿尔德巴兰篇，同时也想聚焦那些深爱着菜月・昴的角色们，所以描写这场全力战VS全力战时真的让我心潮澎湃。

接下来故事即将进入两位数的第十章，主线将转移到停滞许久的王选上。自称失踪王女之名的『神龙教会』修女、历经漫长苦难后重新行动的库珥修阵营、缺少一位候选人的王选将如何发展──故事终于要正式进入Re:Zero后半战了。

那么虽然依依不舍，还是按照惯例以谢辞作为结束语吧。

感谢责编池本先生，第九章后半战高潮迭起，加上现实中的活动非常忙碌，但总算顺利完成。埋了十年的伏笔回收得很精彩呢。非常感谢。

插画师大冢先生，从同时描绘九章完结与十章开篇的封面插画开始，到本卷各处的高潮场景以及遵循设定的插画对故事的完美烘托，真的承蒙关照了！角色们充满情感的姿态，正是构筑九章的脊梁。

设计师草野先生，这次设计的LOGO兼具虚幻感与征兆般的强烈表现力，令人拍案叫绝。不愧是您的手笔，真的非常感谢。

花鸡先生＆相川先生的第四章漫画化，以及高濑若弥先生的第五章漫画化，始终以令人不敢松懈的高质量给予我强烈动力。感谢诸位描绘Re:Zero的世界，每次都感激不尽！

MF文库J编辑部的各位，校对人员、各书店负责人及营业人员也鼎力相助，使得本次得以顺利出版。一直以来非常感谢。

最后要向见证九章完结的读者们致以最大谢意。线下活动的签名会与大家的应援都是我创作的动力。第十章也请多多指教！

那么，让我们在下一卷第44卷再见！故事终于迎来高潮，究竟会揭露什么，又将如何发展，敬请关注接下来的Re:Zero！

2025年12月《穿着厚厚的防寒衣物，呼出白色的气息》


Re：从零开始的异世界生活 43

长月达平

MF文库J

2025年12月25日　发行

ver.001

©Tappei Nagatsuki 2025

本电子书籍基于以下内容制作

MF文库J『Re：从零开始的异世界生活 43』

2025年12月25日　初版发行

发行人　山下直久

发行　株式会社KADOKAWA

●咨询

https://www.kadokawa.co.jp/

（请前往「咨询」页面）

※根据内容不同，可能无法予以答复。

※仅限日本国内提供支持服务。

※Japanese text only

禁止擅自复制、转载、分发、传送本电子书籍的全部或部分内容，或在网站上转载等。同时，也禁止擅自修改、篡改本电子书籍的内容。

根据购买本电子书籍时同意的条款，无论有偿或无偿，均不得将本电子书籍转让给第三方。

本电子书籍的内容基于底本发行时的取材与撰写内容。


