#+title: Re:从零开始的异世界生活 第四十三卷 (转自web版)
#+setupfile: ./setup.setup

* 第四十三卷 web版

** 序章 『梦的终结』

（保留自机翻文库版）

──将回归梦之城的阿尔德巴兰包裹其中的，是难以言喻的复杂情感。

熟悉的光景、熟悉的芬芳、熟悉的音色、熟悉的温度。

被熟知的蓝天与绿色平原包围，挟着熟知的青草芬芳的风声掠过耳畔，熟知的阳光温度笼罩全身，阿尔德巴兰伫立在这幅铭刻于心的风景中。──刹那间，脑海中那些褪色泛黄的记忆画卷骤然鲜活起来，重新绽放出绚丽光彩。

「────」

这正是，名副其实的，让阿尔德巴兰魂牵梦萦到连梦境都反复重现的梦之城。

在流逝的岁月里，他曾怀疑过这座城是否真实存在。当实感逐渐远去时，他甚至质疑过自己的神智。即便如此，这座梦之城依然作为浸透阿尔德巴兰血肉骨髓、永生难忘的灵魂学舍，始终矗立在遥远的彼方。

──历经四百又十年的漫长岁月，阿尔德巴兰终于重返故地。

「────」

在山丘上、白色阳伞下、能看到纤细柔韧的剪影伫立着。仅由黑白两色构成的美丽女人、正俯视着山丘下的阿尔德巴兰。

当那双黑瞳与自己四目相对时，即便隔着距离也能清晰辨识的美貌灼烧视网膜的刹那，阿尔德巴兰确信这正是令自己魂牵梦萦到几乎相信宿命的『魔女』。

从出生之日起，直至那个瞬间都未曾片刻分离的相伴者。

对阿尔德巴兰而言，这是用言语都无法道尽的、承载着太多情感的存在。

「──先生」

存在过。确实存在过。有过。确实有过。存在过。确实在这里存在过。

『魔女』也好、梦之城也好、阿尔德巴兰的过去也好，全都不是被正常世界所不容的阿尔德巴兰所制造的虚妄幻象。

「老师……」

想倾诉的事，多如牛毛。想传达的事，不计其数。

想交谈的话语，多如繁星。

只不过，最想和『魔女』分享的，是阿尔德巴兰这样延续生命、在漫长岁月尽头得以重逢的这份情感。

怀着那份急切的心情，阿尔德巴兰朝着山丘上的『魔女』所在之处──

「──阿尔德巴兰」

刚迈出的脚步，被那声呼唤硬生生拽住了。

渴望渴望渴望、持续渴望的『魔女』之声，对此感慨万千──才怪。阿尔德巴兰停下脚步，是出于另一个理由。

是因那声音、以及『魔女』凝视自己时眼神的冰冷与锐利，而止步。

「老、老师？」

被违和感支配而停步的阿尔德巴兰，正被『魔女』默默注视着。

她是个求知欲旺盛、充满好奇心、知识欲化身的人。但此刻『魔女』黑色眼眸中蕴含的东西，与阿尔德巴兰所知的『魔女』有着决定性差异。

明明该是阿尔德巴兰熟悉的样子，阿尔德巴兰熟悉的声音，阿尔德巴兰熟知的『魔女』，其存在方式却令人感到决定性不同。

那个理由、原因、真相是──

「──『强欲魔女』」

这正是『魔女』对阿尔德巴兰所怀疑虑与不安给出的回答。

「──啊」

『魔女』仅吐出这一句话，用仿佛观察实验动物般的冷漠黑瞳，注视着阿尔德巴兰会作何反应。

理解了。直觉到了。──确信了。

眼前的她，确实该是与阿尔德巴兰共度时光的『魔女』吧。但某种意义上，那个『魔女』早已永远消失了。

她适配了──适配了『魔女』的身份。

适配那份被渴求的自私，却仍令人如此焦灼、无论如何都无法据为己有的，真正意义上作为『魔女』完成所需的资格──魔女因子。

『魔女』已然蜕变。──从阿尔德巴兰的引路人，化身为『强欲魔女』。

在这场不容败北的战斗中，阿尔德巴兰落败了。作为代价濒临死亡的『魔女』，在临终之际与阿尔德巴兰分别后，被选中了。

──以真挚的爱为代价，获得了成为实现愿望之力的非人者的资格。

「──爱为何会消减呢」

不明白。阿尔德巴兰无法理解『强欲魔女』提出的疑问。

唯有一点可以明确。

「老师……不，『强欲魔女』艾姬多娜」

「────」

「我绝对要──亲手杀了你」

──阿尔德巴兰早已失去了一切。除了性命之外的所有事物。

** 第一章 『冰上决战』

（分节标题保留自文库版）

１

──异常值。

雷姆认为这正是自己被赋予的使命，也是必须完成的职责。

为了阻止使用『时间回溯』这种超规格权能、突破重重阻碍来到这里的阿尔──所需的正是这个异常值。

『那铁盔混蛋的权能确实强悍。但不管多强的力量，使用它的终究是人类。是人就会犯错。虽说那家伙的权能连错误都能抹消，但并非无限。只要不断叠加预料之外的状况，把他逼到极限，铁盔混蛋终会犯下无法挽回的失误。──那就是打倒他的胜机』

这是曾将阿尔逼入绝境的罗姆爷提出的策略。

对于罗姆爷的献策，精通战术的拉姆、罗兹瓦尔和柯林特都没有异议。因此雷姆会全力执行这个计划。

阿尔应该遭受的，是让他叫苦不迭的意外。若说这需要比拼耐力，那雷姆也绝非等闲之辈。

毕竟──、

「──因为我，近距离见识过那个人」

要说最大的胜算是什么，那就是雷姆最关键的、最棒的制胜法宝。

「呀啊啊──!!」

咆哮着倾尽全力，雷姆挥出的手臂稍迟一步释放的铁球狂暴地划破长空。

笔直旋转的尖刺铁球瞄准的目标，是红发忍术师八重・天膳──在以海拔五千米的阿古扎德峡谷为舞台的下坠战斗中，这场对决正随着与这名惊人忍术师的交锋进入新阶段。

在半空凝结的冰之圆盘，成为双方比拼根基的战场。

就连这个试图强加意外的战术，也是雷姆与爱蜜莉娅协力构思的成果。但被塞入意外因素的不仅是阿尔他们。我们也是。

轰隆一声，撕裂风压的咆哮一击既沉重又锋利。

带刺铁球──晨星的威胁无论引以为傲的斩击技艺多么精湛，用细线捆束都无法防御。它毫不留情地袭向身为异常者的八重。

「──呃」

面对逼近的威胁轻哼一声，放弃迎击的八重就地侧翻。铁球擦过正在冰盘上翻滚的她身侧，徒然划破长空──

「嘿呀！」

伴着清脆击打声，听起来悠哉的锐利呼喝迎击了铁球。

这是隔着八重位于另一侧的爱蜜莉娅，用穿着冰靴的脚踢飞袭向自己铁球的爽快声响。爱蜜莉娅修长的腿凌空回旋，铁球被暴力弹回，追向侧翻闪避的八重，眼看就要嵌入她的侧腹──

「才不会得逞呢」

下一秒，八重侧翻时手掌触及的冰盘表面，被钢线剥离覆盖住她身体，化作阻挡铁球的盾牌。当然这薄盾仅能抵挡一击。半秒龟裂，再半秒尖刺已穿透盾面，整整一秒后彻底粉碎。

然而，对于敏捷的忍术使而言，这一秒就已足够。

「骗人!?」

爱蜜莉娅不禁发出悲鸣。但雷姆此刻也是同样心情。

在二人视野中，用临时冰盾避开追击的八重轻盈跃起，赤足踏上完全伸展的晨星锁链，顺着锁链一口气疾奔。

爱蜜莉娅为那杂技般的平衡感瞪大眼睛，雷姆更震惊于她在锁链上行走却丝毫不显沉重的步法，而惊愕还在延续──随着八重挥动手臂，冰与石制成的刀剑正从她们头顶接连倾泻而下。

「这是──」

这正是二十秒前爱蜜莉娅与阿尔在空中制造、未被回收的冰制与石制武器。八重用钢线将它们拽落，化作危险骤雨再度利用。

「都怪我没收拾干净！」

「阿尔先生您也没收拾啊！」

「摊上不会收拾的主人，咱们都不容易呢？」

反省、补救与挑衅交织在一起，雷姆和爱蜜莉娅忙于应付从天而降的刀剑。爱蜜莉娅用双手的冰之双剑将其击落，但雷姆的情况不妙。

右手被晨星占据，而此刻晨星正被八重当作立足点无法贸然收回。只能徒手用仅剩的左手防御。

「来不及──」

正当她以为避不开而准备承受攻击的瞬间──有人猛地推开雷姆的肩膀，而那个推开她的人被坠落的石制长剑贯穿了胸膛。

「──昴君！」

在雷姆情不自禁的喊声中，被贯穿胸膛的是菜月・昴──的冰制人偶。这个过分精巧的冰雕菜月・昴保护了雷姆，带着宛如本尊的英勇笑容竖起大拇指，缓缓倒下。

「呜诶？刚才那是、难道说是爱蜜莉娅大人吗？」

「嗯，没错。──而且，昴可不是一个人在战斗！」

在皱眉的八重应声的瞬间，六道人影从爱蜜莉娅背后飞窜而出。全都是与刚刚倒下的菜月・昴相同外貌的冰像。

它们全员仿佛各自拥有意识般摆出个性鲜明的姿势，同时扑向在锁链上奔跑的八重。只要那些冰之指尖有任何一处触及八重──

「不巧，我最擅长的就是多人战」

刹那间，二十条跃动的钢丝束缚住扑来的冰之菜月・昴们。缠绕在脖颈、躯干与四肢的钢丝猛然收紧，六具冰像凄惨地四分五裂。

「昴──!!」「昴君!!」

雷姆与爱蜜莉娅的悲鸣声重叠着，响彻化为凄惨残骸的冰之菜月・昴。

在四散飞溅的冰像碎片后方，仍立于锁链的八重逼近雷姆。电光石火间，雷姆松开晨星破坏八重的立足点。对着必然在空中挣扎的忍术使者，她拧身准备祭出全力的回旋踢──

「毕竟，我可不想正面吃下鬼族的踢击呢」

话音未落的八重突然屈膝，锁链松弛的瞬间从视野边缘掠过。

沉腰的八重在空中完美保持平衡，她指尖射出的致命丝线正要如套索般缠上雷姆的脖颈。是斩首还是绞杀——千钧一发之际，脚下锁链骤然绷直颠覆了她的预判。

「什」瞪大眼睛的八重不愧是顶尖高手，立即用脚趾弹开锁链后跃。她的视线清晰捕捉到代替雷姆拽动晨星锁链的身影。

那是胸口插着石剑最先倒下的、冰之菜月・昴。——即便倒下也不放弃战斗的冰之菜月・昴，拯救了雷姆。

这个人真的总是、为了他人不顾一切地乱来——

「就算感动得哭出来也是冒牌货吧！」

「就算是冒牌货也一样！」

八重扭曲的嘴唇尚未闭合，雷姆全力使出的后旋踢已笔直贯穿她胸口正中。

２

——异常个体。

八重认为，阻止这一切正是自己被期待履行的职责与使命。

在八重心中，阿尔那反复无常又可怕的怪物评价始终未变。──但能令他消耗、产生负荷的，正是不断叠加的异常状况。

『哈！老夫和比自己强的家伙打到半死的次数可多着咧？但活到最后的总是老夫，为了填补和那些怪物之间的差距，咱们这种偷偷摸摸的把戏就是卑鄙的生存之道嘛。只要让对方没法全力发挥，总有机会割下强者的脑袋。──反过来不也一样？喀喀喀喀喀！』

这番话，正是向八重传授忍术生存之道与技巧的村长『恶辣翁』的忠告。

她对村长的观点并无异议。但意外的是，实际验证的机会并不多。毕竟多数对手都比八重弱小。面对正面较量不会输的对手，根本用不上阴招。

那首次败北的对手正是阿尔，八重的生存之道从此扭曲。如今这个光是接触就令全身恐惧战栗的存在，只希望他能早一秒消失。为此，必须让阿尔实现那个愿望，那份期盼。

所以──，

「──我不想让那些会逼迫那位大人的东西靠近」

她知道自己很扭曲。但无可奈何。八重喜欢辛辣讨厌甜食。可这是与生俱来的天性，是自己无法改变的宿命。

既然生来就是这样的自己，那就要贯彻这样的活法。

因为八重有八重理想的、与阿尔关系的终结方式──。

「──呃」

被雷姆——那个长角少女如此称呼的她——的踢击直中，八重用身体操控术将冲击分散至吱嘎作响的四肢，把意志传导至肌肉内脏，这正是忍术的生存之道。

但即便施展全力也无法做到无伤。虽未轻视鬼族的力量，但从对方的站姿和动作来看，自己低估了其实力。通过鬼角吸收周围玛娜、爆发性提升身体能力的鬼族特性远超想象。

「再加上爱蜜莉娅大人的即兴发挥太棘手了呢～」

一边承受着判断失误的代价，然而八重却神色从容地低语。

实际上效果相当显著，但绝不能让她察觉。忍术就是要杜绝对手获取情报。若真要给，那也是用于诱导的虚假信息。那般明显的脚步踉跄，雷姆自不必说，就连观战的爱蜜莉娅和八重也会认定这是追击良机。即便如此，若八重表现得游刃有余，任谁都会犹豫是否该追击──

「爱蜜莉娅大人！」

「诶！还没完呢！」

不过那仅限于对手是堂堂正正的战斗高手的情况下。

八重制造的喘息空间毫无意义，两人毫不留情地扑向被击飞的八重。

并非无谋之举。而是拼死、竭尽全力。这才是眼下最难对付的。

「既然如此这边就用手脚不干净的坏习惯来对付！」

对抗之际，八重将双脚趾大大张开，配合双手十指操纵二十条钢线。

插在冰盘立足点上的数把刀剑——那些由冰与石制成的武器被钢线缠缚，随着八重手指的动作，钢线与刀剑交织出轻重错杂的裂风在冰面上肆虐。

沉重的刀剑与轻盈无形的钢线，应对失误就会失去一两根手脚。虽然阿尔被命令不得杀人，但只要留条命就不算违抗命令。

如此自我欺骗着，八重毫不留情地向雷姆和爱蜜莉娅迸发斩击之意。

然而──

「哈啊啊啊!!」

「呀！　嘿！　哈！」

咆哮的雷姆与狂攻的爱蜜莉娅将八重的攻击悉数击溃。

无需言语眼神的二人配合固然惊人，但更令人费解的是她们防御本应不可视钢线的方式。刀剑可见，但钢线无形。

对此理由产生疑问的八重，迟了一拍才察觉到。──好冷。比站在冰上更甚的寒冷。

「──呃、冰雾」

呢喃的吐息泛起白霜，勾勒出空气中漂浮的细小冰晶闪烁的轨迹。八重明白同样的原理也作用于钢线，使无形的丝击被冰雾显形。但冰与钢线的相性之差，远不止于此。

「──冰柱魔线」

瞬间，随着编织而出的咏唱，大气开始发出尖锐的悲鸣。

当将世界染白的寒气愈发狂暴地显露獠牙，冰雾浓度持续增加时，最先遭殃的便是质量处于劣势的钢线。

以轻盈纤薄为最大特色的钢线优势，在这冻结的世界里被碾碎。钢线能斩裂疾风，却斩不开暴风雪。──因此，判断仅在瞬息之后。

「────」

八重亲吻手指上的戒指，刹那，烈焰顺着钢线在冰面上爆燃而起。

连冻结的裂风都能推回的热浪，这迫使钢丝放弃了『不可视』的优势，转而赋予其在冰雾中也能抵御严寒的力量。

「请陪我共舞烈焰！」

缠绕火焰的钢丝释放灼热线击，『红樱』上演着燃烧之舞。

面对那照亮溪谷的煌煌炎舞，携着清冽冰雪的两人──不，连同七具冰像共九道身影飞扑而来。

「应邀奉陪！」

「踩到脚的话可别怪我哦！」

爱蜜莉娅手持冰之双剑滑入八重在冰面上制造业火漩涡的射程。

爱蜜莉娅用带刃长靴在冰面滑行，画出圆弧轨迹配合这边的炎舞，施展出看似舒缓实则凌厉的曲线攻击。

与爱蜜莉娅那快慢极致的攻势并列，雷姆选择与冰像组成密集阵型直线突进──堪称绝景──

「啊啊啊啊啊啊──!!」

雷姆如野兽般咆哮着双手向天，将那双白色拳头如雨点般砸下。

面对这堪称弹幕的风暴般攻势，八重扭身、下蹲、后仰、跨步循环往复，以舞蹈般的连贯动作擦弹闪避、闪避、闪避──

「如果只是无脑的连续攻击，永远都碰不到我哦？」

即便拥有鬼族的身体素质，八重也不会漏看从躯干传导至四肢的力量流向。雷姆的鬼族力量虽堪称惊人，却尚未达到『剑鬼』那般例外领域。若要说违和感，反倒是无视人体构造行动的冰像更为异常。

总之照这样下去，八重能永远应付他们两个──

「──不对」

险些被轻松选择带偏的八重，自己给自己喊了暂停。

这个战场是对手选的。放任对方为所欲为就正中下怀了。要阻止异常状况，自己也得成为对方的异常才行。

「眼下当务之急是──」

雷姆的连击被化解，爱蜜莉娅从背后的攻击也被回避，以冲撞而来的冰像为踏板跃向空中，八重睥睨着脚下将自己和阿尔分隔开的冰之圆盘。透过白雾朦胧的冰盘，锁定阿尔模糊的身影，她射出丝线。

四肢的钢丝向圆盘全方位延伸，八重扭转全身，倾注全力。

结果──

「──改变局面。这也是，计算之内吗？」

伴随着八重的全神贯注，冰之圆盘如陀螺般旋转，强大的离心力袭向冰面上所有人。──战场就此迈向下一阶段。

３

──『意料之外』。

爱蜜莉娅激励自己，所谓意想不到之事，正是当下他们最有力的武器。

若突然受惊，人们会瞬间忘记原本的打算。阿尔为此次计划理应思虑周全，而『意料之外』正是要击溃这些谋划。

『莉娅遇到危机时，总喜欢直接用蛮力解决对吧？当这招不管用时，才会第一次烦恼该怎么办呢……但我可爱的女儿可是拥有能砰地一声推开所有问题的力量哦，所以别停下脚步继续加油吧？莉娅可是我引以为豪的女儿，继承了最强大的基因呢』

是的，帕克曾经说过的话语，此刻在爱蜜莉娅脑海中温柔地复苏。

虽然最近令她感到安心的总是昴的话语，但当明确知道昴遭遇危险的此刻，最先鼓励爱蜜莉娅的果然还是帕克。

与雷姆联手对阿尔发动的攻势，因八重突然介入而陷入苦战──已经额外越过两道崖壁刻印，距离抵达地底只剩三十秒左右。

虽然内心焦躁不已，但绝不能就此认输。尽管不算擅长，将这份焦躁感反压给阿尔他们，正是此刻爱蜜莉娅的使命。

「──因为这种事，普莉希拉根本不可能期望的吧」

之前，爱蜜莉娅曾被阿尔救过。抛开这点不谈，爱蜜莉娅也想成为阿尔的力量。不仅是因为共享着同样的痛苦，不仅如此，出于本能的感觉，爱蜜莉娅想要拯救他。

因为爱蜜莉娅和普莉希拉，本应该能成为朋友的──。

「──呜、昴！」

猛然间，挟带热量的旋风卷起涡流，以八重为中心旋转的冰之圆盘。

如同转碟般急速旋转的冰盘上，模拟昴的冰之士兵们因承受不住施加的离心力，踉跄着被甩飞出去。它们要么毫无抵抗之力地从圆盘抛落，倒霉的则撞上溪谷岩壁粉身碎骨。但在那之前，别忘了它们曾及时拉住险些滑倒的爱蜜莉娅，成功救了她。

「雷姆她──」

穿着冰刀鞋抵抗旋转的爱蜜莉娅，在冰面上搜寻着雷姆的身影。担心她也和冰之士兵们同样遭遇──爱蜜莉娅的视野中，猛然腾起剧烈的火焰。

膨胀火焰的根部，雷姆和八重在那里激烈冲突，圆盘中央升起爆炎。

重新接住抛向空中的铁球的雷姆，与集结燃烧丝线的八重激烈碰撞，以双方冲击为火种膨胀的爆炎热浪将雷姆的身体弹向外围滑去。

「不行！」爱蜜莉娅大喊，瞬间思考扑向雷姆的方法但──

「──严禁分心」

踢击冰面的刹那，八重如尖刺般的牵制已飞袭而至。

燃烧钢丝束缚的石龙刀一击，与延迟袭来的丝击二段连招。面对需要大范围二段回避的攻击，爱蜜莉娅正欲思考──却因想起昴和帕克这两位可靠同伴的话语而放弃。

比起思考更相信直觉，爱蜜莉娅朝被弹飞的雷姆跃去。──字面意义上，她振翅飞向了雷姆。

「哇」地瞪大双眼，面对这令人惊愕的景象，八重一时愣在原地。这是她首次露出如此破绽百出的姿态，但此刻的爱蜜莉娅根本无暇顾及这些。她径直扑向雷姆，抓住她的手腾空而起。

──只见爱蜜莉娅的后背，赫然伸展着由冰晶凝聚而成的翅膀。

「谢、谢谢您，爱蜜莉娅大人……这对翅膀是？」

「之前昴给我画过的。他说背上长着翅膀的叫天使。虽然昴偶尔会提起，但没想到真的能变出来呢！」

面对被救起的雷姆提出的疑问，爱蜜莉娅笑容灿烂地回答。

不过说到底这只是徒具外形的赝品。无法像真正的鸟儿那样振翅飞翔，顶多只能借助风力滑翔。而且必须像现在这样处于高空坠落的过程中才能实现，就算想给昴展示也很困难。

虽然想着要是他能陪着一起从五千米高空坠落就好了，但要做到这点──

「爱蜜莉娅大人！我们反击吧！」

「好啊！」

展开冰翼的爱蜜莉娅，对怀中斗志昂扬的雷姆点头回应。

相信对「回击」一词产生的直觉，爱蜜莉娅将翅膀从背部剥离后，与雷姆一同沿冰面直线滑降，两人在空中旋转的同时，下砸的脚跟直击横向旋转的冰盘──为圆盘添加了纵向旋转。

结果圆盘在保留横向旋转的同时叠加纵向旋转，形成纵横交错的奇诡运动轨迹，正转、反转、再正转再反转，将战场化为无序混沌。

简直就像昴和加菲尔在罗兹瓦尔宅后院建造的训练场里，为培养『平衡感』而设置的『娱乐设施』那般。

「那这个我可超级拿手哦！」

爱蜜莉娅在上下左右无规律变换的苛酷立足点上飞驰。正为练习成果欣喜时，她突然担心起雷姆能否适应，

「请您不必担心！」

应答的雷姆将铁球刺入冰盘，猛然拽动锁链直冲中央。虽势头不及爱蜜莉娅，却充满力量感且稳如磐石，帅气非常。

「不如说、我得更小心别摔个四脚朝天……！」

在纵横交错的混乱冰盘上（或者说下）、拼命保持平衡不被甩落的爱蜜莉娅、一边搜寻着本该同处战场的八重身影、一边眨动紫绀色眼眸。

找到了。八重依旧待在冰盘离心力最弱的正中央。即便如此、爱蜜莉娅仍察觉到她理应被甩得晕头转向、正试图伸展蜷缩的双腿。

屈膝跪在冰盘上的八重、并未被旋转的立足点所摆布。

理由显而易见──她用钢线剜空了冰盘中心、制造出仅此处不受旋转影响的安全地带、正守株待兔般等着爱蜜莉娅她们。

「────」

──刹那间、缠绕火焰的钢线迸发、燃烧的银闪划过爱蜜莉娅的视野。

４

──燃烧着、火焰的银闪。

若有俯瞰此景且通晓此技者、必会认出八重・天膳所施展的、正是钢线居合术。

纤细而无固定形态之物竟能构成居合术的形态，这是任何人都无法想象的。更何况钢丝术，在忍术漫长的历史中，除少数天才外，别说掌握，连基础都是遥不可及的幻之技法。

这记绝杀被史上最具忍术天赋的『红樱』锤炼至更高境界的事实，包括阿尔德巴兰在内，无人知晓。

──正因如此，雷姆能挡下炎之银闪，只能称之为奇迹。

「──普莉希拉小姐」

雷姆唇间吐出的，是让她站立于此、指引她至此的女性之名。此刻这位恩人，又为雷姆留下了捡回性命的征兆。

感受到了。──八重那直到此刻都未曾显露的、确凿杀意。

人类感情寄宿于玛娜之中。因此玛娜感知敏锐者，更易察觉他人情感。据说精灵读取对方思想的能力亦源于此。

然后，因鬼化而通过角吸收周围魔力的雷姆，也在无意识中发挥出相同的感知力，以数倍于平常的程度接收着爱蜜莉娅和八重的情绪。

「迄今为止──」

都未曾感受到。──不，是即便感受到也未能察觉的知觉。

能感知到这些的背景存在诸多因素。既有取回自我的缘故，也因怀着夺回昴的使命感。但最重要的另有其他。

最重要的是帝国城郭都市古拉尔中，与普莉希拉共度的那些日子带来的影响。

在那段绝不漫长的时光里，普莉希拉屡屡向雷姆抛出谜语般的话语，给予她深度审视自我的契机。当时因治愈魔法的不完善与对无能自己的懊恼，雷姆只是肤浅地模仿着普莉希拉的言语──

「直到现在，才终于稍微明白了一点」

即便此刻，也不敢说完全理解了那时话语的全部答案。想必这是要用一生完成的课题。而且，再也无法与她核对答案了。

这令人悲伤。感到寂寞。胸口作痛。

「──现在，好想和您说话。普莉希拉大人」

轻声低语，闭上眼睛。而当她睁开双眼时，雷姆作为鬼族的天赋就此觉醒。

她能敏锐感知到混在玛那中的微弱敌意、杀意、攻击意图──当这些情绪仿佛带上颜色显现时，雷姆分毫不差地将铁球对准了那个方位。

为将她和爱蜜莉娅一同斩断而袭来的炎之银闪，她将晨星砸向能一击扫开它的位置，把必杀攻势改写为不杀之局。

钢铁与钢铁相击的尖锐声响彻四周，在手掌承受强烈反冲的同时，雷姆的反击正面对轰了八重释放的一闪。

「────」

面对这个事实她微微屏息，但八重仍屈身摆出下一招架势。

狂暴的无数银闪在释放前化为杀意驰骋虚空，雷姆抢先出手，沿着那些轨迹轰出铁球、锁链与魔法。

数个瞬间——几乎同时发生的刹那重叠，八重的攻击尽数被雷姆挡下。

「啊...」胸腔中漏出一声叹息。

啊啊，这就是、真正的鬼族所见到的景象。──拉姆与生俱来便触及的领域一角，雷姆也终于在迟了十年多后用手指触碰到的瞬间。

「──雷姆!!」

爱蜜莉娅一边挥舞铁球持续扫荡燃烧的钢线风暴，一边呼唤着雷姆。

那声音里蕴含的紧迫感并非对被保护的感谢，而是对状况变化——且是朝不利方向变化的警示。

余光瞥见爱蜜莉娅时，她正伸长双腿吸附在冰盘上，在旋转的视野中转动双眸，

「阿尔不见了！哪里都没有！」

「──」

听到爱蜜莉娅走投无路的声音，雷姆也终于察觉到阿尔从视野中消失的事实。

本该绕到冰盘下方、只能旁观雷姆她们战斗的阿尔，在因旋转而视野无阻的天空中却不见踪影。

雷姆正思索着去向，忽然被闪电般的直觉驱使抬起头，凝望远方的天空。

坠落中的阿格扎德峡谷，那道撕裂大地的狭长裂缝彼端，遥望着不断下落的雷姆等人，逐渐远去的黑影依稀可见。

那身影与先前的爱蜜莉娅如出一辙，背部伸展着石制羽翼──乘着风势以惊人速度滑翔的阿尔。

刹那间掠过雷姆脑海的，是爱蜜莉娅对冰盘使出的那记重击。那一击令立足点纵向旋转，将八重间的战斗推向新维度──却被反将一军。

「我和爱蜜莉娅大人蹬踏地面的瞬间──」

当时阿尔紧贴冰盘背面，借助雷姆与爱蜜莉娅蹬踢引发的旋转势头，获得了直冲天际的推进力。

「────」

若就此让阿尔逃脱，全盘战略将彻底崩溃。

连续制造意外消耗阿尔体力，再祭出我方『杀手锏』的战术将沦为泡影。──电光火石间，雷姆与爱蜜莉娅的视线猛然交汇。

「──雷姆」

本应无法听见的爱蜜莉娅意志，此刻正通过玛娜传向雷姆。

鬼角所能感知的，不仅是敌意的征兆。它更通过吸收坚定不移的信任与期待，将无穷力量赐予雷姆。甚至让人觉得，比起吸收玛娜，背负那份心意才是真正的力量源泉。

没错，正因为被分予了力量──

「──我出发了！」

「路上小心!!」

抡起全力挥下的重击砸向冰盘，急剧加速圆盘的纵向旋转，借着这股势头，原本贴在冰面上的爱蜜莉娅被一口气射向高空。

裹挟着冰晶光辉的爱蜜莉娅再度展开背后冰翼，乘着风势追赶飞向远方的阿尔，在阿古扎德峡谷的天空中翱翔、翱翔、不断翱翔。

就这样将追击阿尔的任务交给飞走的爱蜜莉娅──

「──不会让你追上去」

「这可是我的台词呢～」

坠落的冰盘上相对而立的两位女仆──雷姆与八重，鬼族与忍术使，『英雄的辅佐者』与『红樱』，最后的激战就此展开。

──通过阿格扎德峡谷岩壁的标记再前进，距离地底还有二十秒。

** 第二章 『八重・天膳』

１

──所谓忍术，就是不能对任何事物倾注感情。

这是在佛拉基亚帝国的忍术之里，那些被禁止选择忍术以外生存方式的人们所必须遵从的绝对教义，是比扎根帝国大地的铁血戒律更应恪守的铁则。

若对某物动了感情，精心锤炼的忍术之刃便会轻易生锈。

正因如此，身为忍者必须无一例外地将这条铁则铭刻灵魂，绝对服从。

可即便如此──

「我说你啊，是不是这样？跟老子一样因为啥都能干两下子，活着反倒没劲了吧。心里头装着点啥不也挺好？」

听着这个牙齿意外整齐的村长咧着嘴说笑，八重当时莫名火大——这人把忍者的铁则扔哪儿去了？

──包括她当时强烈认定自己绝不可能那样活着。

２

──『红樱』八重・天膳，是百年难遇的忍术天才。

周围的人都称赞她是忍术之村有史以来最具天赋的人，甚至有人高声赞扬她的潜力足以媲美卡拉拉基都市国家的『礼赞者』。

说实话，八重本人深切希望不要拿自己和那种离谱的对象比较，但村里人根本不顾她的感受，狂热追捧她的天资。

然而，与周围的评价形成鲜明对比的是，八重极度厌恶自己被『特殊』对待。

那是一种对『特殊』的生理性抵触——别人被特殊对待时无所谓，但自己一旦被『特殊』对待，就会涌上难以忍受的感觉，恨不得抛弃一切的『特殊』过敏症。

对于这种过敏体质的八重而言，忍术之村的铁律非常契合。

将心灵寄托于某物 就是在自己心中创造『特别』。既然对这份『特别』过敏 八重便能毫不费力地遵守忍术的铁则。实在是件好事。──不过这种适合忍术的特质 也成了周围人将八重视作『特别』对待的部分原因 所以也算有利有弊。

──说到底忍术之道险峻　绝非人人都能胜任。

其门槛之高 据说见习生千人里仅有一人能成为下忍 下忍千人里仅有一人能成为中忍 中忍千人里才终于有一人可晋升上忍──堪称狭路。顺带一提 每次听到这个比喻 八重都觉得哪有十亿人想当忍术使。

总之　用这种说法来形容选拔的残酷程度确实恰如其分。

首先 忍术修行从刚懂事的年纪就开始了 对象基本都是外村掳来的孩童。由于非人道且荒谬的修炼会导致见习生大批死亡 从外界掳掠适龄幼童反倒更有效率。

当然、对掳来的孩子会使用药物、暗示和干扰记忆的术技，让他们将家人和故乡等记忆忘得一干二净。八重也不记得父母的长相，连自己真正的名字都不知道。『八重』这名字是后来才得到的，在那之前人们都根据她的发色称她为『赤之八号』。

没有资质的人首先就会在记忆处理环节栽跟头。要么记忆消除效果不佳，要么反过来消除过头变成废人——情况五花八门。但说到八重，这丫头薄情得很，居然干脆利落地全忘了。干脆到连负责记忆处理的藤老天膳都目瞪口呆。顺便一提，这位藤老后来成了八重的命名之父，正是他让八重继承了自己家族的名号。

虽说是命名之父与孩子的关系，但两人之间更像是冷酷的指导者与学生的关系。对八重而言，藤老也不过是村里接触频率较高的对象罢了。

无论如何，通过这种手段强行剥夺心灵依靠，用忍术这支黑色画笔肆意涂抹的纯白画布——失去过往的空白幼儿就此诞生，这便是非人养成机构忍术之村的真髓，无关肉体改造的人体改造就此开始。

为掌握超越人类常识的柔体与轻功而进行的骨骼破坏矫正、从微量逐步适应致死量的抗毒训练、通过亲身体痛来牢记体术与忍术道具危险性的日常课程，折断的骨头、撕裂的皮肉、流失的鲜血都被规定了最低标准。

若有死者出现，其尸体便作为适应死亡的训练教材不得下葬，每日在床榻旁逐渐腐烂的尸骸末路与腐臭侵蚀着心神，接二连三有人陷入疯狂。

这些所谓恐怖的训练，八重都轻松完成了。——不，其实八重也付出了相应努力，只是在旁人眼里显得游刃有余罢了。

骨骼破坏与矫正已学会切换痛觉开关的方式 内脏溶解般的毒苦所导致的血尿血便被控制在最低限度 忍术道具只要碰过一次就能像十年老友般运用自如。唯有尸体的腐臭令人难熬 但说到底终究会习惯的。

就这样、年幼的八重以破例的速度成为了最初千人中的一员。

「──从今日起，你就叫八重・天膳」

被认可为下忍的那天，藤郎给我取了这个名字。

可惜、她并没有什么特别的感慨。毕竟在『红之八号』时期就受到与其他同辈不同的待遇，名字的有无对八重的自我认知并未产生特别影响。不过可以肯定的是，从那时起她就已对『特殊』待遇感到厌烦。

──至于为何藤郎会给自己取名八重，至今仍不得而知。

闻くチャンスを逃した。今となってはそれなりに気に入っているし、テンゼンの方も语感がいい。何かの间违いで、ヤエ・ダンクルケンにならなくて本当によかった。

八重这番讽刺，却被村长用「喀喀喀喀喀！这小丫头片子口气不小啊！」一笑带过。

无论如何，即便称呼从『赤之八号』变成八重・天膳，对八重而言世界的触感与作为忍术师的生存之道都未曾改变。——改变的从来不是八重，而是她所处的环境。

——这正是八重对『特殊』过敏的最大原因。

３

话说回来，虽是以最年少最短纪录晋升下忍的八重，却有人被她本人所厌恶的『特殊』深深吸引。——正是藤郎・天膳。

作为命名者兼指导前辈的藤郎，彻底迷上了八重那种能将所学之一发挥出十成、甚至百成千成效果的天赋。

这行为无疑违背了忍术师「不可对任何事物动情」的铁则。

必须亲手将不世出的天才八重・天膳培养成非凡的忍术师。——藤郎就这样被这种近乎偏执的使命感所支配。

「你明明有这种才能。为什么就是不明白!?」

双眼充血地吼出这句话的藤郎，始终强硬地相信着八重的才能。

虽然她早已察觉藤郎注视自己的眼神日渐炽热，但这次爆发带来的灾难——藤郎准备的『蛊毒』，仍远超八重的想象。

这个与佛拉基亚帝国选拔皇帝的『选帝之仪』同构的仪式，将当时与八重同级的三十名下忍卷入其中，演变成可能关乎忍村存亡的愚蠢暴行。

被带离村子的下忍们在森林里奉命自相残杀直至最后一人，他们毫不质疑上级命令，徒然浪费着生命。——最终正如策划仪式的藤郎所愿，仅剩八重・天膳存活。

但因为她始终采取不主动出击、只反击来袭者的战术，甚至放走了最后求饶的同僚，令他勃然大怒。

——不，准确地说，发怒的不是他，而是他们。

被八重・天膳的才能所倾倒、误入歧途的不止藤郎一人。受他话语感化，或是亲眼目睹八重的成长，企图通过执行名为『蛊毒』的仪式让八重背负扭曲期望的大有人在。

若这些人因八重背叛了他们的期待而将其处决后自尽，倒还显得有几分可爱。但那些坚信八重可能性，决意错误地反复实施『蛊毒』直至成功的家伙，八重能给予他们的只有超度。

「你是颠覆忍术存在方式之人……！」

直到生命最后一刻，藤郎都坚信着八重的可能性而死。

在那些喋喋不休的喉咙被剜开，倒在血泊中的命名之父与愚蠢同伴们的尸体上，讽刺般纯净的白雪樱花瓣正簌簌飘落。

八重永远记得那些被鲜血浸染的花瓣，以及随之而来的难以名状的徒劳感。

「──哎哟喂，这可真是了不得啊。一群乳臭未干的小丫头片子，居然把上忍都给全灭啦？」

姗姗来迟的里长悠哉的感慨，印证了藤郎他们暗中活跃的事实。虽说他应该不至于认为村里那些不安分子全交给八重处理就完事了。

「所以，全都死透啦？」

虽非出于这般猜忌，八重还是对里长的询问撒了谎。

藤郎等人不满的根源在于——八重放跑了其中一名求饶的同僚，但她隐瞒的不仅是那人会『蛊毒』的事实，更刻意忽略了这名忍术之里叛逃者的存在。

那位同僚曾提议「啊—既然这样你要不要也一起逃？」但八重斩钉截铁地拒绝了。并非想留在村里，只是不愿与之为伍。

论实力八重远胜于他。可本能却在嘶吼着警告——若八重终有一死，必是与此人并肩而立之时。

「──失策失策」

从丢下这句话转身离去的同僚身上，我感受到了他想抹杀所有知晓自己存活之人的意志，但所幸对方尚有理性能够放弃这个奋斗目标，使得在这场『蛊毒』中只有八重和那位同僚幸存。

多亏不必成为唯一的幸存者，患有『特别』过敏症的八重心想：自己身上的『特殊性』或许也能稍微淡化些吧。

「那咱就回去咯。——『红樱』哟」

背对着她的里长，用八重首次听闻的别名称呼她。

藤郎最终也没能问出为何给自己取名八重。但里长如此称呼她的理由，即便不说也心知肚明。

——在那个忍术师接连丧命的夜晚，盛放的白雪樱被鲜血大肆浸染。

４

——『红樱』八重・天膳，是举世罕见的忍术天才。

当她以最年轻之姿晋升上忍，这份认知成为无可动摇的共识时，八重那偏执的『特别』过敏症已到了无可救药的地步。

对八重而言，被他人『特殊』对待既是诅咒也是威胁，更是只会给人生带来负面影响的可怕干涉。自从藤郎那件事之后，这类让她如此确信的事例屡见不鲜，八重早已对『特殊』精疲力尽。

「你这家伙，不就是那个嘛？和咱一样，正因为啥都能凑合着干，这样活着才没劲不是？心里头总得搁点儿啥才对吧？」

村长竟要亲自让这样的八重打破忍术铁则，简直不可理喻。说到底，八重根本不追求什么人生意义。那种东西本就是多余的累赘。

所谓人生意义，无非是期待自身能力、怀抱未来希望——这等同于相信自己的『特殊』，无疑精准踩中了八重的地雷。

所以八重刻意让自己远离众人期待与憧憬的忍术形象。

那正是与藤郎天膳赌上性命都要完成的忍术形象背道而驰的存在——轻浮的举止、捉摸不透的言行、看似亲切却绝不与人深交的姿态。

作为那般轻浮浅薄之人，八重・天膳将自己精心打扮了一番。

为避免误会事先声明，这是厌恶『特殊』的八重必然的选择，绝非参考了村长的角色性格。

不深究任何人的人生，不直面任何人的目光，不被任何人珍视。

这正是『红樱』八重・天膳的处世之术与人生哲学──

「──该不会真把这种丑陋活法，当作自己的天赋了吧？」

没错，当两人独处时突然被搭话，八重因那抹赤红的美貌而屏息。

对『特殊』严重过敏的八重，既厌恶自己被『特殊』对待，也对他人之特殊格外敏感。──而她的『特殊』堪称完美。

──『血染新娘』普莉希拉・跋利耶尔。

被领民尊称为『太阳姬』的她共度的日子，对身为忍术执行过各种任务的八重而言也极为鲜明且印象深刻。──八重以女仆身份潜入普莉希拉麾下，实为帝国『九神将』奇夏・戈尔德的指使。

远在露格尼卡王国参与王选的她，对帝国究竟有何种意义，八重既未被告知，也无意询问。

虽说如此，任务中难以理解的不合理之处仍令她不禁侧首。

基本只需监视目标动向并汇报，未接到任何破坏或妨害指令，更非要求速速暗杀。日复一日平淡的女仆生活，说来或许冒犯，实属对天才忍术『红樱』的浪费。

事实上，对掌握全套潜入技术的八重而言，潜入跋利耶尔宅邸执行女仆工作轻而易举，仍是与往常无异的轻松任务。

唯独接触普莉希拉时，必须万分谨慎。

由于工作性质，八重也常有见到要人的机会。命令八重执行此次任务的『白蜘蛛』是如此，姑且算是村长的『恶辣翁』也是帝国的要人之一。虽说是远远望见，但也曾见过皇帝阁下──那时还与皇帝身旁的『青色雷光』对上视线还被挥手致意，让人深刻体会到天外有天的恐怖。那才称得上是『特别』的存在。

即便是见识过这些大人物的八重看来，普莉希拉这个人也深不可测，完全无法预料她会看透什么。

明明不该如此，却多次怀疑她是否早已识破自己帝国刺客的身份。当然，也无法断言绝无可能──普莉希拉身上具备着堪称魔性的、令人费解的吸引力。

对此，八重将『特别』的普莉希拉视为不幸之人而心生怜悯。

她那稀世美貌自不必说，就连举止言行、甚至吐息中都蕴含着魅惑他人魔性的普莉希拉，无论他人情愿与否，都会以这份『特别』触及所有人的视线、情感乃至人生。

众人会对她寄予厚望、怀抱期待，也会被邪恶的欲望和情感所支配吧。──就连八重怀有的这份怜悯，也是她的『特别』所引发的。

方才她那句话，简直像看透了八重心中所想般脱口而出。

在私人房间里低头看着手边的书，连为我准备茶水这边瞥都不瞥一眼，正这么想着就突然毫无征兆地说出那种话。不过，普莉希拉身边时八重总是保持着警惕。所以这次也能隐藏惊讶装出平常的样子。

她轻佻地带着戏谑的态度，表现得毫无认真之意，脸上挂着微笑。

面对八重这种敷衍的态度，普莉希拉眯起一只眼——

「──迟早，你这家伙也会迎来必须倾尽自身一切的时刻。千万、千万要将妾身的话语铭记于心。准备要做到『ぱーふぇくと』才行」

那句话的真意，八重没能听进去。

既有忍术的直觉在告诫她，若追问可能会引起怀疑。但恐怕更多的是，八重对此感到厌恶。

从『特别』的普莉希拉口中，会向自己抛出不利的话语。

所以八重，并不知晓普莉希拉那句话的真意。

藤郎为自己取名八重的理由也好，里长近乎骚扰般屡次企图让自己违背忍术铁则的算计也罢，全都——

──因为这就是八重・天膳的人生哲学：既不追求『特别』，也不被要求『特别』。

５

最终，八重的想法是正确的。

那般光芒耀眼、以烈火般『特别』姿态迷倒众人的普莉希拉，也倒在了残酷无情的帝国大地上，散尽了生命。

然后，那些渴求着她已失去的『特别』之人，在被无处安放的感情灼烧灵魂的同时，仍想报答那份『特别』，正燃尽自己的人生。

八重・天膳，不希望被那样的『特别』所摆布。

所以，所以才这样。

所以必须尽快，将让自己产生不良执念的『特别』，从这个世上抹去。

这正是对被迷恋的『特别』抛弃的他，八重赌上性命协助的唯一理由──

「──呃」

纵横无尽、不顾上下左右高速旋转的冰之圆盘，即便如此仍以其为立足点构筑战场的八重，迎击袭来的青发鬼──雷姆。

挥出的右手钢线纵向疾驰，左手钢线横向扫出缠住的刀剑。两种斩光形成的难以躲避的狙击，将雷姆从正面与背后同时夹击。

──因对方的配合，八重让爱蜜莉娅从战场上逃脱了。

背生冰翼的爱蜜莉娅借助旋转冰盘的冲势与风力，朝着远方天空中逐渐飞离的阿尔紧追不舍，身影急速远去。尽管她即将脱离钢丝的射程范围，仍有机会发动丝线远投攻击──

「严禁东张西望！」

随着雷姆以超人反应挡下双重攻击的怒吼，这最后的机会也被彻底粉碎。

「突然变这么难缠太狡猾了吧？到底是什么原因──」

「──是爱！」

「……就不该问！」

八重俯身贴附在旋转的冰面上，躲过受情绪驱使而狂暴挥舞的铁球，对着不讲道理强化自身的鬼族少女吐了吐舌头。

附加了纵横向旋转的冰盘虽运动轨迹难以预测，但转速却存在固定节奏。八重凭借天生敏锐度捕捉规律，以灵活步法闪避刚腕攻击，如同冰上舞者般轻盈跳跃，试图将战局拉入自己擅长的中距离。

「绝不会让你得逞……！」

与华丽攻克冰盘的八重形成鲜明对比，雷姆的决策简单明了——她将贯手、脚尖、握着的短铁球接连砸向冰面，以野兽般的动作紧追八重。

那是与优雅精致完全背道而驰的、粗暴凶猛的肉食兽狩猎风格——即便如此，却快得惊人。转眼间就缩短了与翩然闪避的八重之间的距离。

「这般不顾形象，女仆的品格何在？」

「不巧，我们主人对女仆要求的资质只有一项——拼尽全力！」

抬头的雷姆以三肢撑地扭转身体，借助冰盘旋转之势掷出铁球重击。八重调动钢丝卸去力道，不甘心地咬紧牙关。

两大阵营的最强女仆对决——八重可没闲心拿这种事开玩笑。

虽在技巧上更胜一筹，实力也自诩高出对方不止一级而是三级，但八重和雷姆之间单纯就是相性不佳。那能捆缚绞合、对任何攻击都有招架余地的钢线，为确实挡住雷姆以一击必杀为目的的晨星，不得不动用双手七根手指。既然如此，便用剩余的钢线瞄准必杀——，

「啊啊啊啊啊!!」

四肢插入冰面、咆哮的雷姆全身蒸腾起红色热气。

这是由于数千米高空下降导致的低温、充盈全身的玛娜激活了鬼族特性，再加上八重施加的钢丝撕裂伤正在急速恢复的结果。

在此期间，八重一边躲避雷姆的致命一击，一边在她身上刻下多处旨在使其丧失战斗力的伤痕。但无一能超越鬼的恢复力。

而最重要的是──

「嘘──」

她亲吻戒指，钢线再度被火焰吞噬。

那一瞬间，用弥漫的火焰遮蔽雷姆视线的八重，朝着热浪另一侧她的脖颈，将拉回的手臂一闪──以逼近音速的速度放出钢线，企图斩首。

这是秘传书中没有的、八重原创的忍术技巧──用阿尔的风格来说，就是必杀技。

射程不明的不可视线击，本应成为绝命一闪斩杀任何对手。然而，雷姆却躲开了这一击。──而且，不是一次，是两次。

「──」

初次施展时，曾贪心地企图将雷姆和爱蜜莉娅一并狙杀。

被挡下是因为目标太大。为了不让这样的借口成立，本该确实击杀雷姆的一闪──被躲开并非奇迹或偶然。是必然。

雷姆已经看穿了八重的钢线术。周围已无冰雾，并未使用与爱蜜莉娅相同的探测方法。即便如此，鬼仍让忍术的必杀失效。

「不会让你得逞」

放弃了毫无意义的掩饰表情，八重紧绷嘴角低语。

不会让你得逞。不会让你如愿。不会让你阻止。──雷姆也好爱蜜莉娅也罢，都由八重来阻止。

展开石翼，阿尔未等这场战斗分出胜负便逃向天空。

八重既不认为这是被遗弃，也不觉得遭到背叛。虽不排除被放弃的可能性，但阿尔生性吝啬。无论是手牌还是棋子，都不会轻易舍弃。

所以八重将阿尔的撤离视为托付。他理解为这是命令自己无论如何都要阻止紧追不舍的两人。

因此，阿尔将杀人许可证托付给了八重。

「──就算杀死也要阻止」

阻止、阻止、无论如何都要阻止。

将妨碍阿尔目的的存在全部清除。──为了让那个失去『特别之人』普莉希拉而挣扎的阿尔，尽早从世界上消失。

若不这样做，八重・天膳就无法变回那个遵守忍术铁则、对万物毫无眷恋、厌恶并远离『特别』的自己。

６

「──是你运气太差了」

是的，那个令八重・天膳恐惧的怪物，反反复复说着同样的话。

受命潜入、被派遣至跋利耶尔宅邸的日子突然迎来了终结。

每日的女仆工作，戏弄可爱的见习执事，与不被当作骑士对待的小丑骑士斗嘴，侍奉那位可怕又耀眼的『太阳姬』倒也不坏。

但命令既下，八重的个人感受无关紧要。只需完成任务，然后消失。

就在她准备执行突然下达的暗杀指令，悄然接近寝室里的普莉希拉时，那个男人在昏暗宅邸的走廊上拦住了八重。

面对无需解释、早有预谋的阻挠，八重与男人──阿尔展开了死斗。

话虽如此，实力差距显而易见。虽是王选候补的骑士，阿尔的实力远逊于八重，胜负本该瞬间分晓──本该如此。

「──只是运气不好罢了」

明明已确实贯穿心脏的男人，却用同样轻松的语气抛出话语。

即便遭遇如此异常事态，八重的身体仍毫无停滞地行动，将下一次致命攻击砸向对手。

杀也杀不死的家伙，我可不是头一回遇到了。世上多的是奇奇怪怪的奇葩人类，我还跟长着三颗心脏的怪物干过架。不过把那家伙第三颗心脏打爆后也就死透了。说白了，只要杀到死透就行。

我砍下过他的头。把身子劈成两半。放火烧遍全身。扯断四肢。撕开喉咙。敲碎脑袋。剜出眼球。剥掉全身的皮。粉碎所有骨头。捣烂内脏。灌下毒药。埋进土里。沉入水中。勒住脖子。勒住脖子以外的部位。我把忍术的招式试了个遍，夺走所有能夺走的性命，用尽所有能用的杀人手法。

「──是你运气不好」

可是无论杀多少次，阿尔都会爬起来，对我说同样的话。

八重使尽了掌握的忍术招式，尝试了能想到的所有手段，最后甚至放弃思考任凭本能驱使，可还是杀不死他。怎么也杀不死。

「──是你运气不好」

试过让他后悔出生的拷问。没用。试图放弃任务逃跑。没用。想要拉别人下水。没用。

终于决定到此为止，把绳子套在自己脖子上结束一切。

「──是星星的错啊」

就连这个，也没用。

「──是星星的错啊」

不断重复的相同问答，徘徊在永不终结的死亡螺旋之间，被永无止境地赋予相同轮回，八重・天膳有生以来第一次感到恐惧。

「──是星星的错啊」

只要能得救，什么都愿意做。发过誓什么都愿意做。

只要能结束，什么都愿意做。发过誓什么都愿意做。

「──是星星的错啊」

就算懂得了恐惧，阿尔、那个男人、那个怪物，也没有原谅他。

「──是星星的错啊」

即使心灵被摧毁得体无完肤，怪物的无常轮回依然没有尽头。

次数，早已数不清了。这世上再没人像八重这样，与这个怪物相互厮杀如此多次。

数不清的次数里，八重杀死他；不愿去数的次数里，八重被他杀死。

「──只是运气不好罢了」

这样的对手，别无二家。不需要。连想都不愿去想。

即便如今已从怪物的心血来潮带来的无尽螺旋中解脱，即便此刻仍宣誓效忠并全心全意协助其目标，这句话依然铭刻在灵魂深处。

「──只是运气不好罢了」

必须尽快让怪物消失，让那个男人消失，让阿尔消失。

无论出于何种契机、何种理由、何种羁绊，八重・天膳的心都绝不能被任何事物束缚。

「──只是运气不好罢了」

──她的心，绝不能被任何事物束缚。

７

「──只是运气不好而已」

随着八重唇间吐出这句话，无形的斩光迸发，直取雷姆纤细的脖颈。

雷姆在肌肤战栗的感知中察觉危机，反射性挥动紧握晨星的手臂，让锁链截击于刀光轨迹之上，将其格挡开来。

──生死一线，此刻无疑正立于生死线上。

在失去记忆、丧失战斗力的佛拉基亚帝国未曾经历过的修罗场中，雷姆抵达了连失忆前与大罪司教及白鲸战斗时都未能企及的境界。

「──昴君」

感受着发热额头上的角──从那里源源不断涌入的力量、情感与世界的脉动，雷姆轻唤心爱少年的名字，让自己的灵魂为之振奋。

耀眼『太阳姬』给予的建议与对意中人情愫的高涨相互交织，流淌在雷姆体内的鬼族之血，正逐渐发挥出其原本应有的性能。

即便如此与八重的实力差距悬殊，雷姆能在至今所见屈指可数的强者八重面前坚持至此，并非仅靠一己之力。

这是众多力量结晶共同作用的结果──为了阻止八重，不，是为了阻止阿尔他们而顽强抵抗至今。

从普雷阿迪斯监视塔开始，与菲鲁特阵营的冲突和王都攻防战，再加上奥托执着的追踪，以及这次的分割袭击，通过反复实施非常规与稳健的战术，阿尔他们已被名为无法逃脱的消耗战的锁链紧紧束缚。

雷姆与八重之间的实力差距能暂时被填补，多亏了那锁链的重量。再加上，堪称讽刺的机缘巧合成为了雷姆的顺风。

「──」

咬牙切齿的八重手指跃动，挥出的钢线撕裂长空逼向雷姆。

面对倾泻而下的无数斩光，雷姆通过角敏锐感知、回避、回避、达成完全回避，维系着本该断绝的性命，在战场上死死纠缠。

那神乎其技──不，鬼乎其技的回避秘诀只有一个。

「──杀气」

看得见。感受得到。传递而来。──通过鬼族的角，对方的意志。

闪避那看似染上颜色的死线，循迹，反击，雷姆向八重逼近。

自从爱蜜莉娅追赶阿尔脱离战场前后，八重的攻击里明显开始混杂杀意。毫不迟疑要斩首断肢的杀意乱舞──那强烈刺激着鬼族本能，讽刺地化作顺风催生出雷姆的超常反应。

如果八重从一开始就遵循不杀方针与雷姆对峙，恐怕雷姆会更早被她制服。──但当八重真正开始发挥忍术本领时，她的攻击反而无法触及雷姆了。

「────」

雷姆将脚尖刺入旋转的冰盘支撑身体，在飞溅冰屑闪烁的视野中，捕捉到八重那张笑容消失、正凝视这边的面孔。

八重眯起狭长的眼眸锐利如刀，自律克己的姿态美得夺目，雷姆能感受到那具柔韧锻炼过的躯体正燃烧着使命感的火焰。

必须实现的愿望与无论如何都要达成的祈愿，赋予八重超常力量，让她怀着即便与全世界为敌也在所不惜的觉悟。

而这份使命感从何涌起——雷姆心知肚明。

「因为我也……雷姆也是，同样的存在」

即便额头生角、遍体鳞伤、从五千米高空直坠而下，雷姆能像这样站立于此的理由，同样源于使命感。

然后，这份使命感究竟从何而来，雷姆没有避讳的理由。

那就是──，

「──爱!!」

「蠢货就只会这一招……！」

面对咆哮的雷姆，八重回应声中带着焦躁。

压抑情感、从不显露真心的忍术原生色彩。雷姆既不认为这是不成熟也不觉得是傲慢。咬紧牙关是理所当然的。──若为某人倾尽全灵的话。

「────」

视野边缘激战正酣时，岩壁刻划的线条掠过雷姆的意识。

阿古扎德峡谷，五千米，最后一根，距地底还有──，

「──十秒!!」

「──」

直面如怒涛般袭来的丝线攻击，雷姆故意如此喊道。

提供情报。增加判断素材。扰乱思维让二十根手指中的一两根迟疑也好。激怒对方，暴露情感，使其憎恨自己。让恶意、敌意、杀意满溢而出，再将其穿越，穿越，穿越越越越──。

然后──，

「就是这里！」

雷姆和爱蜜莉娅的算计得逞──最后十秒，随后在五秒的位置，来自正下方的冲击毫不留情地击穿了冰盘。

８

「──是你运气不好」

是的，盘踞在八重心里的怪物时常这么低语。

直到现在，八重仍会在梦中听见那男人说过千百次的声音。那是最糟糕的噩梦。

最初，阿尔这句口头禅令八重感到憎恶。八重心灵龟裂破碎绝非时运不济，分明是那怪物所致。难道还想推卸责任吗——

但渐渐地，八重意识到这并非男人的托词，性质截然不同。

「──是你运气不好」

每当说出这句话时，阿尔从未显露胜利者的傲慢。

那话语中不含轻蔑或嘲弄，或许更接近慈悲或同情之类的情感。

正因如此，那个怪物、那个男人、阿尔，始终没有说出那句话作为佐证。

关于普莉希拉・跋利耶尔之死，他从未归咎于时运不济。

对于没能挽救她生命的无能自己，他也未曾抱怨命运弄人。

「──是你运气不好」

怪物也好，男人也好，阿尔会说出那句话的时候，总是当自己那不讲理的力量，挫败了对方的愿望或目的之时。他总是对对方这样说着。

──错不在你。

啊啊，讨厌。讨厌讨厌。真的讨厌。

这种事情，根本不想察觉。

阿尔的话语，男人的眼神，怪物的内心，根本就不想意识到。

八重不想对阿尔找出恐惧以外的理由。不想怀抱。不想记住。

所以，想尽快结束。

──不想给这份『特别』，赋予恐惧以外的名字。

９

「错的，全部，都是星星……」

听到从自己唇间漏出的低语，八重刹那间找回了飞散的意识。

瞬间，她察觉到自己身体被抛向空中，视野天旋地转。

冲击，没错，有冲击袭来。

冰之圆盘从正下方受到某种打击，碎冰的冲击贯穿了八重全身。

「什么情况」，往脚下看去，击碎冰面的竟是数千米深峡谷的地底──那里冻结了奔流的大河形成的巨大冰山，而撞击点正是其顶端。

这超出常理的怪力，显然是爱蜜莉娅所为。但更令人震惊的是──

「……真是个难缠的女人呢」

在旋转的视野中，碎裂的冰晶化作璀璨的钻石尘雾，八重看见顶着发光尖角的雷姆正穿梭于这片绝景。

碰撞瞬间，雷姆为躲避冲击腾空而起，此刻正借飞散的冰块加速，朝滞空中的八重猛冲而来。

──将距离冰山相撞的五秒，误导成还剩十秒。

丧失冷静乃忍术大忌，落于下风是女仆失职，辜负托付更非『红樱』所为──

「──只是运气不好罢了」

八重宣告的对象，既非迫近眼前的鬼族少女，也非狼狈不堪的自己，而是那个早已飞向遥远彼方、此刻不在场的怪物。

当非同寻常的怪物对他人说出那番话时，对怪物而言也有着相同的意味。

「──啊」

全身嘎吱作响，手脚也失去知觉。但是，疼痛？麻木？这些早在地狱修行中就克服了。通过拷问训练被折断全身骨头，经历放血致死的濒死训练也都熬过来了。耳边传来村长那刺耳的笑声，仿佛在说「这下见识到了吧」。气得要死。虽然气得要死——，

「──啊」

重复了成千上万、数十万、数百万、数千万次相同的动作。

八重操纵着数百年无人使用的钢线，这需要以毫米为单位移动指尖的精湛技艺，在手指麻木、流血、意识朦胧的状态下。

即便这副身躯的生命已流失九成，操纵钢线的手指也绝无差错。

「──啊啊啊啊啊！」

伴着喷血的惨叫，被钢线捆缚的冰块瞬间狂暴地划破长空。

被冲击震碎的冰盘碎片、用丝线缠住的那些碎片随着八重全身的律动在空中嗡鸣，朝着扑来的雷姆横抡猛砸。──轰鸣声响彻云霄，被冰块殴打的雷姆以惊人势头倒飞出去。

仿佛要对飞出去的雷姆追加攻击般，钢线捕获的冰块接连、接连、接连不断地投掷而出，如流星般倾泻向先一步落在冰山顶部的雷姆。

飞扬的白色雪烟、弥漫的冰雾中混入了鲜血，将冰山化作恶鬼的墓碑。──刹那间，墓碑从内部被贯穿，猛然伸长的铁球笔直刺向八重。

「──呜」

凶恶的铁块、以及附带的尖刺剜开八重的躯体，贯穿侧腹。

但重要脏器已挪至侧边。凭借忍术非人道的肉体改造，八重能移动体内器官位置。穿过脏器间隙的尖刺、被收紧的肌肉强行封堵。

武器被夺。下一秒，染血恶鬼撕裂弥漫的白色雪烟冲天而起。

那道轨迹笔直无曲、毫无花巧、不加修饰，纯粹以满腔心念径直突进。──只见网状分布的钢丝迎面拦截了飞袭而来的雷姆。主动投身死地的雷姆雪白肌肤绽开无数裂痕，眼看她就要被分割成数百肉块──

「──修玛」

千钧一发之际，雷姆的嘴唇吟诵出这场战斗中屡次目睹的魔法。

本应将雷姆身体切得粉碎的钢线，其触感突然中断。只见嵌入她肉体的钢线连带着鲜血一同冻结凝固。──这与甘愿承受铁球攻击的八重采用的武器封锁思路完全相同。

刹那、亲吻戒指的动作为钢线点燃火焰，用冻结的爆炎对抗血液的凝固──太慢了。

「呀啊啊──!!」

雷姆没有放过钢丝瞬间的弯曲，咆哮着向八重挥起拳头。

染血的白拳，八重从中看出了决一死战的全力。

因此，不能吃下这招。——为了不吃下这招，必须亮出王牌。

「────」

雷姆用双手双脚共二十根手指操控，避开了所有袭来的钢线。

但是，还有。八重・天膳的王牌，那是——

「呸」

微微吐出的舌尖，从戴在那里的戒指中，释放出最后的斩光。

这一击准确无误地命中猛然逼近的雷姆纤细脖颈，将其生命一刀两断。

10

——『红樱』八重・天膳，是举世无双的忍术天才。

对其才能与实力给予高度评价的『恶辣翁』奥尔巴特・邓克尔肯说道。

这是对或许终有一天能与自己比肩的天才少女的建议——不，是忠告。

「讨厌吧？老夫也有过经验啊。像咱们这种非凡之人啊，总比普通忍术师活得久些，见识过各种玩意儿。所以偶尔会这样啦。也会有守不住忍术铁则的时候嘛」

「嗯？你说没有重要东西的人就弱爆了？不对不对，老娘说的可不是这个理儿。是这么回事啦——不知道啥毒就解不了对吧？从小不碰毒就是为了不被毒死。那心里头留个念想不也一样？就像为了防止被毒死才不碰毒似的」

「毕竟咱既没爱过人也没被人爱过嘛。会变得超弱的啦。——头一回懂得珍惜别人的忍术使啊。喀喀喀喀喀！」

11

寒光一闪，从舌尖勾着的戒指迸出钢线，准确无误地掠过扑来的鬼族少女细颈，将头颅与躯干的连结一刀两断。

解除不杀戒律的阿尔，成功扫清了前进路上的障碍。

想到这个事实，以及阿尔知晓后的反应，八重胸腔深处泛起阵阵绞痛——

「——哈？」

就在即将沉溺于苦涩的刹那，八重眼前的景象让她怀疑自己的眼睛。

毫无疑问，八重的钢丝斩断了雷姆纤细的脖颈。确实感受到了切断猎物生命的触感，听到了斩断血肉骨骼与生命的风切声。

然而──

「──这边也，耍了花招呢」

八重的赤红瞳孔与雷姆的淡蓝眼眸交汇。那双眼睛，仍未失去光芒。

接着，本该确实切入脖颈的夺命红线，缓缓消失。──既非格挡也非闪避，本该确实夺命的一击，被强制取消了。

这绝非仅用鬼族恢复力就能解释的、本不该存在的奇迹。能引发此等奇迹般事件的，纵使世界广阔也──

「──阿尔大人」

即便与世界为敌也绝不会落败的怪物，她曾渴望借助那份力量。

这么做是为了，抹消自己心中萌生的『特别』。

可是──

『──只是运气不好罢了』

闭上眼睛，又会听见令人毛骨悚然的可怕话语。

唯独此刻不可思议地，带给八重的并非恐惧。

「败因是」

「──是爱」

与答案一同挥出的巨臂，将铁球狠狠砸进八重的躯体。

比五千米高空坠落更为致命的鬼之一击炸裂──在阿格扎德溪谷的冰山顶部，鲜红的樱花四散飘落。

──名为八重・天膳的『红樱』，在青鬼面前凄美激烈地凋零了。

** 『阿尔德巴兰 Ⅰ』

『——谁也赢不了我亲手造就的你哟』

被『魔女』这么说过的事，阿尔德巴兰至今仍历历在目，仿佛就在昨天。若按实际时间算，那已是将近二十年前；但要说体感时间，那更是远远不止。

即便记得某一个局面被他反复挑战了多少次，但所有挑战的总次数他根本记不住，更别提把所有度过的时间加起来那种天文数字——连想都不想去想。只是可以肯定的是，他耗费的时间，远远超过了一个人从生到死走完一生所需的时光。

话虽如此，即便他花费了那样漫长的时光，阿尔德巴兰的心境也并未因此抵达那种不老、动辄能活上数百年的精灵所拥有的境界——并没有那回事。

若说人的精神会由稚到熟，终至老成而达观，那是因在所度过的时光里尝遍酸甜苦辣，从而给予心灵成长的余地。可阿尔德巴兰所度过的那些不属于现实流逝的时间，说到底只是为了突破眼前横亘的难关而反复堆叠的、一个个停滞的瞬间。实际上，不过是从数秒到最长也不过数分钟的片段，被无数次重复罢了。那样的时间，就算堆到天上去，也很难指望一个人因此成长。

因此，阿尔德巴兰认为，因权能而被不断重复的时间的堆叠，只会磨损他的心，却无法令他成长，是无为的时光。

即便是那样无为的时间，只要反复上几次、上百次、上万次、上亿次，脑子也会自然而然地整理记忆，试图从阿尔德巴兰那里夺走真正的回忆。

尽管如此，仍有无法褪色的记忆——那种并非刻在脑中，而是镌刻在灵魂里的回忆——而开头那句话，正是如此。

不过，要是阿尔德巴兰说自己既不记得所有的时间，也不想把它们记住，眼前便会浮现出那位渴求知晓一切、好奇心的化身——『魔女』——轻声呢喃一句「这样啊，真遗憾」的样子。

明明口口声声说自己无法理解感情，却又擅长以演技随心所欲摆布他人的『魔女』。即便明知如此，阿尔德巴兰仍无法违逆她的言语与态度。

若说他就是被那样调教、被那样改造出来的——这么一说，或许真能和雅耶曾略略提过的忍术之里那等泯灭人性的作风不相上下。

要说这回，是与『魔女』并列被对待的忍术之里疯得离谱，还是能以一己之力与忍术之里的历史抗衡的『魔女』更为可怖，也不过是半斤八两。

——总之，如今的阿尔德巴兰是由『魔女』造出来的存在。

「话虽如此，你依然有过自己人生的权利。那一点，即便我是造物主，也绝不该单方面侵犯。所以，如果你由衷觉得无法服从我，随时都可以退出计划。那是你的自由。」

『魔女』三番五次这样说，像是在反复叩问阿尔德巴兰的觉悟。

对『魔女』而言，这样的体贴实属罕见。她的一贯手段是，一旦拿到对方的承诺，便设法周旋，不让那句允诺有回撤的余地。

实际上，『魔女』交给阿尔德巴兰的课程与课题里，有不少内容简直如噩梦一般，如果不先让他承诺绝不放弃，光是摆出来就足以叫人打退堂鼓。做那类事时，『魔女』只要让他点头一次，之后就绝不会再问他要不要停下。

然而，唯独在那最根本、最源头、最初的觉悟上，她却屡屡追问。

阿尔德巴兰将那解作是『魔女』式的罪恶感与内心挣扎，然而事实是否如此呢。

自称无法理解感情的『魔女』，却并非不知愤怒、悲伤与喜悦。若能发露那样的喜怒哀乐，她也当能怀有罪恶感，亦或对未来的恐惧。

至少，在与『魔女』共度的时光里，阿尔德巴兰即便会觉得她是不懂人心的『魔女』，却从未认为她是没有人心的『魔女』。

『没有』和『不懂』之间，展开的是截然不同的风景。

或许，那正是以来自『魔女』的发问这一形式表现出来的。若真如此，那么每一次提问，是否就意味着『魔女』曾经迷惘过一次？

她是否曾为那条终将让阿尔德巴兰去行走的残酷道路而忧虑，在尊重阿尔德巴兰自身意志、让他自己去选择那份人生之间，经历过挣扎？

如果，若是，万一，亿中之一，『魔女』确有那样的心情——讽刺的是，恰恰这一点，才是阿尔德巴兰不翻转其觉悟的理由。

所以——

「——是吗。」

对阿尔德巴兰那一成不变的回答，『魔女』的反应也总是如出一辙。

也许，他被骗了也说不定。

自阿尔德巴兰诞生起直至那一天的到来，『魔女』或许花了大把时间把他彻底洗脑。阿尔德巴兰所期望看到的那种罪恶感、犹疑之类的情绪，『魔女』也许根本不曾有过。

也许，她就是那样的坏『魔女』。

然而，就算正面如此质问，『魔女』也会绽开那黑白相映的美丽微笑，

「当然了。——我可是个坏魔法使哦。」

就这样，用一句不知真心还是谎言的答复，将阿尔德巴兰戏弄于掌心。

160

狂风呼啸扑面而来，阿尔德巴兰正以惊人的速度滑翔。

他背后张开由石头铸成的双翼，借风前行。那副模样他自己也觉得可笑至极，但此刻已顾不得体面。

得趁雅耶还能把对方牵制住的空当，尽可能拉开距离，抹平高度差。

「不至于专门冲着我的『领域』来狙击吧。」

阿尔德巴兰嘴上这么嘀咕着，然而他的意识大半已被背上石翼的成形与操控占据。

石翼的成形需要微妙的拿捏，大小与硬度都得细致调校。太大就会过度受风势摆布，太小又根本达不到目的。硬度与密度的强弱也牵连到重量，削得过头也好，不够也罢，都难逃坠落的下场。

「能一次就成功的伊卡洛斯，真让人佩服啊……！」

说到靠人造的翅膀飞上天，当然会想到那位用蜡制翼的前辈伊卡洛斯。且不论他的结局，能用人造之翼不止滑翔，甚至还振翼逼近太阳，这一点确实令人由衷惊叹。

就拿阿尔德巴兰来说吧，光是因为翅膀做得不成样，不知坠落了多少回。——那可正中对手下怀。经过一次次的重试，总算做成了现在这副石翼。

即便如此，这也依然是一门没有极限专注与万分谨慎就无法达成的险技——

「总不能就那样一直往下掉啊。」

正是这份现实与焦躁，才让阿尔德巴兰从石翼 Lv1 起步，慌里慌张地一路刷到好歹能飞的程度——虽自诩握有无敌的权能，阿尔德巴兰的『领域』也并非全无弱点。

此次敌人的奇袭，无意间同时戳中了那道弱点的两个侧面。严格来说，该称作从两个角度对同一个弱点发动了进攻。

阿尔德巴兰的权能『领域』有其生效范围。

奇袭所带来的瞬移，把阿尔德巴兰从他设定的『领域』范围之外抛了出去。更糟的是，瞬移的落点还附带自超高空坠落，这便成了第二重针对『领域』的破坏，铺天盖地袭向阿尔德巴兰。

结果，阿尔德巴兰在以极高速度坠落的同时，不得不在冲出『领域』之前先行自尽，并在坠落途中一再重启。在这番循环里，他判断在超高空、行动受限的状态下，一边下坠一边扭转局面根本不可能，于是又尝试了种种对策，最终决定以『石翼』脱离。

至少如此一来，高度变化趋于缓和，『领域』的维持也相对轻松了些。就这样，阿尔德巴兰总算好不容易解开了一处纠结成死结的难题——

——阿尔！！

这时，正拼命稳住身形的阿尔德巴兰，忽被那清脆如银铃的声音尖锐地呼唤了一声。

阿尔稍稍回头，只见在比他低得多的高度上，却朝着同一方向飞来的——艾米莉娅酱……不，艾米莉娅的身影，清清楚楚。

她那纤细的背上背着一对冰做的翅膀，明明用的是和阿尔一样的手法，却在外形上漂亮得把阿尔远远甩开，还一路猛追，飞快地拉近距离。

「难以置信。」

阿尔都看呆了，甚至忍不住发出近乎佩服的嘟囔——这也不难理解。要把这对石翼做成，哪怕丑得要命，阿尔吃了多少苦，如前所述。也正因为那些苦功，阿尔才会对长着蜡翼的伊卡洛斯心生敬意。

可偏偏艾米莉娅像那位神话中的伊卡洛斯一样，一下子就把人造的翅膀做成了，轻而易举便达到了阿尔历经无数次失败才得到的同等成效。与其说阿尔对她心怀敬意，不如说更真切地感到了决定性的差距，甚至涌上了败北感。

「与其承认那丫头是天才，不如说坠落了六百多回的我只是太废了——可偏偏这么想还更好受一点，这才叫一点救赎都没有啊。」

阿尔德巴兰的『领域』之强，在于凭借无限次的试错，撑到那一线胜机降临的持久战。他最大的优势，就是能一直翻动手里的牌，直到对手失手、局势转为阿尔德巴兰有利。

然而，正如与莱因哈鲁特之战所示，这世上偶有能一次次抽中正确答案的存在。何为正确，因个人的能力与胜利目标各不相同，但共同点在于——他们与阿尔德巴兰不同，受命运偏爱。

——阿尔德巴兰被命运厌弃。

究竟是阿尔德巴兰先嫌了命运，还是命运先厌了阿尔德巴兰，已无从知晓，但唯有这一点无可动摇。且不论他还被谁爱着、被谁憎着，命运都是阿尔德巴兰的绝对之敌。

所以，必须把它杀掉。——就算把整个世界都置于对立面，也要亲手杀死命运。

正因不愿如此，命运便不断把它所宠爱的存在一个接一个当作刺客派来。此时此地，艾米莉娅与雷姆便是如此。

「——这就是因果吧。」

作为奇袭手，最先进言选雷姆的人，究竟是谁？

不管是谁提出的，若是要在阿尔德巴兰心中制造空白，她都是再合适不过的人选。当雷姆是『暴食』的权能受害者时，处于其影响下的阿尔德巴兰没能察觉到雷姆这个存在的异质，不期然地与她建立起了正当的关系。

因此，在那场记忆闪光弹的瞬间，得知普莉希拉已死，雷姆也从『暴食』的枷锁中解放，他比任何人都遭受了更大的空白——因为他撞见了一个本不该在这里、本应早已死去的存在。

「——」

至于那是以何种方式被牵引而来的结果，已无须争辩。毫无疑问，他做到了。菜月・昴抗争命运，并战而胜之。菜月・昴拥有那样的力量，而雷姆的存在便是其证明。

然而，尽管如此——他却没有拯救普莉希拉・跋利耶尔。

「——你要是这么做，那我也不会手下留情。」

流下的眼泪也好，用拳头折磨自己也罢，试图贴近的体贴亦然，通通没有意义。

所渴求的既不是眼泪、不是伤痕、也不是安慰。要的只是那唯一之人的性命。

「——！」

在头盔深处，他咬紧牙关，直咬得口中泛起血腥味，阿尔德巴兰猛地回望身后。与此同时，他改变双翼的角度与厚薄，将速度与机动性的损失压到最低，在半空中与穷追不舍的艾米莉娅目光交错。

艾米莉娅与那对美丽的冰翼相得益彰，然而无论她再怎么可爱，也不可能仅靠扇动造出来的翅膀来获取速度或高度。起步的瞬间倒是借了雷姆猛击冰盘所产生的反作用力，但随后追赶上来的方式则另有其法——

「呀！咤！嘿！」

像她出手攻击时一样，艾米莉娅发出的口号有点让人提不起劲，可每当那声音响起，她的速度与高度便一阶又一阶地攀升。方法简单明快——她以魔法在空中不断造出可供落脚的冰柱，再一脚踢上去，持续获得加速与冲劲。

那些造出的冰柱短暂停滞后，便被艾米莉娅的脚力踢向下方，随即化作玛娜雾散，回归于大气，又再重生为新的落脚点。再度一蹬，再度积势。就靠着这般反复，她穷追上了阿尔德巴兰。

「荒唐至极……」

这是一种只有具备非凡魔法天赋，又能挥霍庞大玛娜的人才办得到的蛮力解法。

托那条联结所赐，阿尔德巴兰能把名为『神龙』的外挂玛娜储槽当作后备来借力，但就算让他照着艾米莉娅的做法去做，他也无论如何办不到。

问题不在玛娜的容量，而在悟性与身体能力的差距过于悬殊。——悟性也许能靠无数次试错来弥补，身体能力的差距却无法填平。

峡谷又长又阔无尽延展开去，夹在两人飞行路线左右的岩壁同样连绵不绝。既然前进的方向一致，艾米莉娅的追击便不会停止。

看准这一点，艾米莉娅又踢踏出一根新的冰柱，虽然仍有距离，却把高度与这边拉平。她以冰翼维持着平衡——

「——阿尔！拜托我们谈谈吧！我会好好听的！」

「说得倒轻巧。口口声声不由分说，结果下手却毫不留情地想把我冻成冰疙瘩。要是刚才那么一路掉到最下面，你八成打算连河一起冻住，把我一举擒下吧。」

「可是！那一套已经失败了！」

「太老实也不是什么好事啊，王选候补！」

袖手旁观地任由自己坠到谷底，那可正是会彻底落进对手陷阱的典型套路。

为摆脱那一切，他孤注一掷地选择了偏离冰盘的坠落轨迹——虽说没能一口气对付两人，但好歹把艾米莉娅和雷姆分开了，这就该算赚到了吗。

答案是——

「现在就让你见识。——我的态度，和王都那时可一点没变！」

阿尔德巴兰抬手，为了甩开穷追不舍的艾米莉娅，在空中凝出块块石块，逼她撞进由飞石织成的弹幕。

出乎意料地，眼前竟展开了一幕宛如真实射击游戏般的景象。迎着那道飞石弹幕，艾米莉娅让冰翼熠熠生辉，

「我也会说无数次。我再也不想因为觉得谁的离开是没办法的事而哭泣了！！」

高声疾呼着的艾米莉娅一头扎进弹幕，碎裂的冰与冻结的空气发出尖厉的悲鸣，在阿格扎德峡谷中回荡不止。

161

——身为『尾随星』，阿尔德巴兰几乎没怎么为自身存在的意义烦恼过。

据说人人在青春期多少都会想一想，自己为何而生，生命从何处来又归于何处，甚至对父母涌起来由不明的逆反之心一类的情绪。可这些命题，对阿尔德巴兰而言一直都算是相当遥远的东西。

就阿尔德巴兰而言，究竟该把『需要反抗的父母』设定为谁，这本身就很棘手；再加上权能的性质，他根本无法产生『失去的生命会消失』这样的实感。关于自己为何而生，他早已被给予明确的答案；至于为什么会出生，他想，大概也能勉强回答是『爱』。

所以，阿尔德巴兰从未去直面那些本该在青春期面对的课题。

他不觉得那是失败，也不觉得可惜。世上有种说法，年轻时的苦头要花钱也要去吃；可那些长大后会羞得称作黑历史的经历，又有什么价值呢。能不经历的就不必经历。——就像任何人一样，死亡只需在人生的最后来一次就足够了。

「这样啊，指望你出现青春期那样的情动与冲动是不可能了吗。这有点遗憾呢。我还想着你会以何种形式迎来叛逆期，事先构想了各种应对呢。」

这番话，是那位『魔女』的叹息。她并非无心，却常常说出不近人情的评语，针对那位省心地茁壮长大的阿尔德巴兰。

对阿尔德巴兰而言，她是自他出生以来相伴最久的那位『魔女』。然而她有个恶癖，总想把人类的一切选择与情感、无数的可能性，全都一一见识。

而且多半时候，这种欲望一旦被唤起便难以刹车，这正是『魔女』的本性。

阿尔德巴兰也与她之外的『魔女』打过交道，哪怕程度不同，但在这件事上没有一位『魔女』能违逆自己的天性，而这在他看来无比亵渎。

所以，若把那位『魔女』那副意犹未尽地等待阿尔德巴兰迎来青春期的姿态，也视作被不可抗的天性驱使，倒也有不得不承认的无奈。可就算如此，为了取悦『魔女』而去装出青春期的模样，也让人难以理解。——某种意义上，正是这种想要反抗的心思，倒更像是青春期的情动。

「果然，让一个连父母都不是的我，只在表面上去摹仿所谓为人父母的经历，未免也太过自我方便了吧。……如果造出了碧翠丝，那样的体验就能体会得到吗？」

对着这样像自言自语般自我设问的『魔女』，阿尔德巴兰心头泛起的寂寥，想来与青春期无关，更像是别的什么。只是那究竟是什么，要将它具体化并不容易；况且，以他们之间盘根错节的关系，也难以那样做。

于是，正如『魔女』所定下的那般，阿尔德巴兰与她之间的关系——

「——老师。」

他这么唤了一声，正沉浸于『思考的迷宫』探索乐趣中的『魔女』便抬起头来。

那双黑色的瞳眸映出阿尔德巴兰的身影，她歪着头来一句「什么事呀」，披在肩上的纯白长发顺势垂落。每每见到这副模样，阿尔德巴兰都会想着，这个『魔女』真是犯规。

明明总是只顾自己的事，坦率追逐自身的欲望，丝毫不打算体察他人的心思，可一到阿尔德巴兰呼唤她时，她必定会与他对上视线。

对这样的『魔女』，起不了青春期式的逆反心，也是理所当然。

本就动机单薄，再加上心身早已屈服，深知违逆『魔女』不过徒劳。打着为熟练驾驭权能而进行性能实验的名义，『魔女』让阿尔德巴兰经历了逾百万次的『死亡』，高下早已分明。

当然，这话阿尔说再多也没用，关键的『魔女』只会来一句「反正我的记忆里一次也没留下，要我生出罪恶感也很为难哦」，拿这话当作挡箭牌罢了。

总之，也明白『魔女』之所以做到那种地步的理由。

毕竟在那时，幸存下来的『魔女』，除去眼前的她之外，只剩那一人——她成了其他『魔女』们直接或间接的死因。阿尔德巴兰与『魔女』们的接点，也并非发生在她们生前。

他只能在由那位『魔女』准备的限定空间里与她们相见。那里见到的她们早已是死者，仅仅是被收集起来的灵魂。

于是，在『魔女』的教导之下，阿尔德巴兰必须把让她们落得如此下场的那个人——

「——必须让你去杀掉她。」

那就是，身为『尾随星』的阿尔德巴兰在尚未步入青春期前便被赋予的存在意义，是他即便死上一百万次也必须完成的人生指针。

为了把阿尔德巴兰变成这样，『魔女』饱受其他『魔女』的非难，甚至与同伴决裂，可见其觉悟之坚决已至极致。

「——谁都赢不了我创造出来的你」

被这样说，对阿尔德巴兰而言既是骄傲，也是他存在的根基。

说实话，阿尔德巴兰觉得这位『魔女』的性格糟糕透顶，她的管教方式与方针的指引也有许多令他不满之处，但即便如此，他在回应『魔女』的期待这件事上从未犹豫。

阿尔一直相信，自己做得到。

那时的阿尔德巴兰，还保有左臂的他，即便知晓『死亡』，却不曾真正体会过败北，所以才会如此笃信。

倒也谈不上经历过青春期——但毫无疑问，那是愚不可及、挥之不去的黑历史。

162

「啧——！」

见艾米莉娅迎着如骤雨般的碎石弹幕正面冲来，阿尔德巴兰强压下心中的犹豫，毫不留手地倾尽火力。

在王都那一战亦是如此，阿尔德巴兰本能地对艾米莉娅没有抵抗力。

这几乎是刻进生命根源的某种弱点，也因此，他在王都时也无法像对其他对手那样果断出手。

那时他借『阿尔德巴兰』的力量落下巨岩，以守住王都为交换，逼停了艾米莉娅的追击；可眼下这里没有任何能被殃及的东西。

从这个意义上说，把战场拉到这道巨大的峡谷，正是对上次交手的切实反省。

「我这边可没那份余裕去感激你的成长啊！」

可惜，阿尔德巴兰的心境远未宽裕到能为自己或敌人的成长而喜悦。他对把艾米莉娅定义为『敌人』仍有一瞬的抵触，但终究还是狠狠闭上了眼，将那份犹疑摁了下去。

正是那份觉悟，早在很久以前，甚至在与普莉希拉相遇之前就已下定。

严格来说，阿尔德巴兰所立下的那份觉悟所指向的对象，并不是眼前的艾米莉娅——

「就算是回收再用的觉悟，也能当个纸糊的架子派上点用场。」

怀着那份明知只是纸糊的觉悟，他高举其上，着手斩断艾米莉娅的追击。

艾米莉娅笔直无畏地，让背后的冰翼熠熠生辉，毅然冲入拳头大小的岩片风暴之中。

那一击原本是指望她哪怕为了回避，或者摆出以柔化解的架势，也能让她的行动稍稍滞慢；然而，不祥的预感成真，艾米莉娅选择了以最短距离的直球对决——

背生冰翼，脚下绽出可供落足的冰柱，甚至还发射出对抗弹幕的冰杭；至于穿透拦截飞来的碎石，则由她双手紧握的冰之双刃尽数击散。

他从『魔女』那里学到，魔法的同时发动，即便对熟练的魔法使来说也极为困难。

即便是同一属性的魔法，要做到如同左右手各执一支笔，右手写文章、左手画插图这般强人所难的活儿，也得有相应的本事才行。若换成不同属性，那简直就像为此额外增设几颗大脑的奇技。阿尔德巴兰就曾亲眼见过『魔女』同时操使五种属性的场面。老实说，他当真怀疑过，那位比常人还小一号的『魔女』，那颗小脑袋里是不是塞了五颗小脑子。

就算撇开这种规格外的逸闻不谈，即便是同样火属性的魔法，要同时放出翼、冰柱、冰杭与双刃四种术式，也已是货真价实的绝技了。

更何况，为了施展那套离谱的追踪术，对方还拿出了连奥运选手都望尘莫及的运动性能——如今只觉得今天的惊讶点数已经用光了。

「所以，就尽量把动摇成分降到最低来迎接吧！」

面对飞礫的风暴，艾米莉娅选择以勇气与臂力硬闯。可勇气且不论，若对方摆出的威胁并非靠臂力就能冲破，又当如何？

——

下一步的攻势早已备好，正欲拉近距离的艾米莉娅只觉面颊一紧。

她眼前，无处可逃地一下子铺开的是比飞石更细小、往往让人忽视其危害的砂砾编织的包围网。那简直等同于一头扎进暴雨里，除非有在半空中把雨点逐个躲开的匪夷所思，否则想做到毫发无伤根本不可能。

当然，撒沙子并不只是为了遮她的视线——

「——好重！？」

艾米莉娅挥臂想把缠上的沙子抖落，惊呼出声。那些沾在她手脚与白衣上的砂粒彼此凝聚，凭借重量与硬度来妨碍她的动作。这是在砂海里对莱因哈鲁特也使过的减益攻势——能超越音速的莱因哈鲁特尚且凭着冲势把它们硬生生震脱，但那种做法艾米莉娅做不到。

更进一步——

「翅膀——」

砂砾的首要目标，是干扰支撑艾米莉娅飞行的冰翼。扑入尘沙中的冰翼被砂侵蚀，无法发挥应有的受风性能。照此下去，艾米莉娅势必重心失衡，猛然失高直坠地面——为免如此，她当机立断抛弃了不听使唤的双翼，从『展开冰翼的艾米莉娅』一转，回到『只是个少女』的状态，得以化险为夷。

「——抛离了吗！」

然而，让她做到那一步，才是阿尔德巴兰的真正目的。

就算逼得她放弃一次冰翼，若是艾米莉娅的话，也能立刻将同样的翼再度展开，在不丢失上升与前进势头的情况下重新起步。可不管她的身体能力多么离谱，也追不上时速超过一百公里的简易滑翔翼。

因此，阿尔德巴兰接二连三出手，不让艾米莉娅重新展开双翼。

伴随轰鸣自岩壁猛然探出的，是想从侧面擒住在峡谷上空飞行的艾米莉娅的石制巨臂。只要那些巨臂把她的势头打掉，就算艾米莉娅再生出新的一对翅膀，也再追不上速度不减的阿尔德巴兰。

而且，横在艾米莉娅面前的巨臂并非一两条——以岩壁为素材突兀伸出的岩石手臂，数量简直逼近数百。

「与其说是向千手观音致敬……倒不如说更像鬼屋的幕后。」

和鬼屋里的定番桥段——从纸拉门后同时伸出一堆手——画面感差不多。只是与那种纯为唬人的装置不同，这些巨臂是真的要去抓住艾米莉娅。

哪怕只要有一条抓住她的脚，这场追逐就将宣告结束，阿尔德巴兰的逃亡便算成功的决胜关头——

「这就——」「——我要加油！！」

「能跨过去吗」刚要脱口而出的话，被逼人的气势硬生生抹去。

这本不是靠拼劲就能办到的事，可偏偏她像是能光凭努力就把不可能化为可能——这正是艾米莉娅可怕之处。

失去双翼的艾米莉娅，将这份可怕发挥得淋漓尽致——她回腕旋转手中的冰剑，先将迎面第一条巨臂的手指斩落，把失去威胁的残块当作踏板，高高跃起。

势头未衰，高度也被她大幅夺了回来。

然而，那些巨臂虽不至千手之多，却仍有上百条在前方伺机而动——

——兵士们，借我一点力量！

应艾米莉娅的呼唤，长相狰狞的冰之士兵再度现身。

在冰盘坠落之中，原本只能束手无策、被砸得粉碎的冰兵们，此刻却以扑向艾米莉娅的土块巨臂为立足点，勇敢迎击：有的以身强行拦下，有的挥拳打偏其轨迹，还有的虽被压倒粉碎，却不忘摆出一个造型，形形色色，各显其能。

尤令阿尔德巴兰心烦的，是其中那个牵住艾米莉娅的手，一边把她从巨臂的魔爪下解脱，一边几乎以抛掷的方式助她向前突进的家伙。

一共七具冰之『菜月・昴』，完成职责便粉碎，再度诞生又去支撑艾米莉娅，复又被砸得粉碎却再度苏生，如此反复不休；在不打破『最多七体』的法则下，挡在蜂拥而至的数百只岩石魔手之前，守护着艾米莉娅，不断助她一臂之力。

——「魔法，乃是将思念与愿望化为形体之物。」那位『魔女』曾如此言道。

以那位『魔女』而言，这话未免过于浪漫——但若想到有人会把风化作刀刃去将对手切碎，或任凭怒火催生红莲烈焰以烧尽一切，那也勉强称得上是将思念与愿望具现化，倒也说得过去。

那么，此刻阿尔德巴兰眼前所见，那些具备菜月・昴的姿貌的冰之兵助艾米莉娅一臂之力的情景，又究竟是何等愿望的具现？

胃的深处翻腾不已。那并非比喻，而是货真价实的事实。

阿尔德巴兰将那股不断涌上的负面情绪，接续到了下一次攻势上。

那便是——

「——抱歉又是老一套，杀手锏再来一回。」

话音落下，艾米莉娅等人的头顶上方——阿格扎德峡谷狭窄谷间几乎占满全幅的、如发簪般的巨大而强悍的岩块，直直坠落而下。

无处可逃，以庞大质量实施的压杀——正是他在王都布下的陷阱之再现。

163

他所渴望的——不，他真正需要的，是一生仅此一次的胜利。

为了那场胜利，说阿尔德巴兰的一生因此而存在也不为过。

自他诞生以来，赋予阿尔德巴兰的一切、倾注在他身上的一切、所受的一切恩惠，皆是为那场胜利铺就的路标——为的是得到它、抓住它、夺下它。

对于其中的意义与沉重的责任，阿尔德巴兰自以为理解得足够透彻——是这么以为的。

然而，一旦到了真正被追问其意义的时刻，本以为具备的觉悟、预先拟定的计划、千锤百炼的灵魂，尽数归于无意义。

『——谁也赢不了我亲手造就的你哟』

来自『魔女』的这句话，是阿尔德巴兰一生的指针。

只要还能信得过这句话，无论前路横亘怎样的障碍，他都不会被阻止。而至于自己会有一天再也无法相信『魔女』这回事——这话他绝不会当着她说，也不愿让她听见——他一直以为绝无可能。

所以，他坚定地相信，正如『魔女』所言，自己不会输给任何人。

——而当那份信仰被粉碎之时，阿尔德巴兰想必确实死过一次。

如果说『死亡』，阿尔已经体会到多到连去数都嫌可笑的地步了。

虽然一直觉得去数本身就很荒唐，但既然被要求去数，阿尔也就照数了；可就算把实际的次数一一记录下来，那份荒谬感也丝毫不减，阿尔确确实实把它尝了个够。

不过，真正意义上的『死』，阿尔想是在那一天、那一刻，才真正尝到的。

那是『魔女』的夙愿。为此，她甚至铸就了阿尔德巴兰，安排了一场一生仅此一次、绝对不能输的战斗。

然而——

「——在绝不能输的地方，你输了。」

在那片熟悉的草原上，在茶会的白色桌旁细嗅红茶芬芳的『魔女』的身影，让阿尔德巴兰猛然明白自己犯下了多么深重的罪，他被绝望彻底击垮。

那位仅凭黑与白两色便能勾勒出美貌之巅的『魔女』，她那美得叫人发恨的身姿上连一处伤痕都没有——这正是此地只是梦境的明证。

毕竟，在现实中，她为了庇护没能赢下那场本该必胜的战斗的阿尔德巴兰，失去了手脚，只剩下等待死亡降临的凄惨模样。

他怔怔地望着那道身影，恍惚间只是在想一个过分理所当然的事实——这位『魔女』体内也流着红色的血。

那血的温度、气味与触感，不可能是假的。

那么，剥夺了这一切，用虚构涂抹掉本应存在的现实的这个世界，才是明明白白的一整块谎言。

「我不太喜欢『虚构』这个说法。明知道严格意义上不是同一个词，但还是会不由得想起一个讨厌的家伙。」

那究竟是『魔女』式的玩笑，还是她由衷地只是想说些不合时宜的话，阿尔德巴兰直到最后也没能看透『魔女』的心思。

只是，他觉得自己被憎恶了。或者说，让她失望透顶，被彻底断了念想。

然而——

「你的手臂，恐怕是无从找回了呢。」

『魔女』的视线投向了阿尔德巴兰那条自肩头起被阴影夺走的左臂。

没有痛感。这也同样是这里是『魔女』的梦之城的证据——一旦回到现实，必将有超乎想象的疼痛灼烧他的脑髓。而且，那是真正无法用『死亡』抹消、永不消退的疼痛。

「失去了一只手臂，在一场绝不该败的战斗里败了。看样子，我的计划终要以失败收场。眼前都能浮现朋友们对我指指点点的样子。——到头来，也只能把一切托付给那些想要继承弗琉盖尔遗志的人。不甘心啊。」

想到自己的败北会从『魔女』身上夺走一切，他悲痛至极。

她不求任何人的理解，离开了同胞的『魔女』们与一同旅行的伙伴，哪怕如此也要去实现的愿望，却被阿尔德巴兰毁于一旦。

而最可悲的是，明知这一切，阿尔德巴兰那已然空洞的灵魂里，依旧不肯重新燃起败北前的觉悟与炽热。

在一场不容失败的战斗中败下阵来，阿尔德巴兰的心折断了。

一生中唯一一次不许败北的初战，将他的心碾得粉碎。

而当他见证与自己最为亲近的『魔女』那不可避免的死亡时，这道伤将真正意义上令阿尔德巴兰再也无法复起。

『——谁也赢不了我亲手造就的你哟』

因此，当那句话再次被说出口时，阿尔德巴兰仍然不明其意。

事已至此，已顾不得体面。那就改改胜利条件吧。她就交给那边……我们要去阻止二次伤害。

『魔女』既聪明，又自私。

她留下无数困惑，将因自责与罪恶感而无法正常思考的阿尔德巴兰抛在一旁，擅自下了结论，不容他反驳便要将话题推进下去。

被更改的胜利条件、另行提出的阻止二次伤害这一目标——可就连那样的事，他都不觉得自己能达成。因为阿尔德巴兰已经失败了。

即便如此——

『——谁也赢不了我亲手造就的你哟』

是什么让『魔女』说出这种话，阿尔德巴兰并不明白。

她没有多说什么，只是起身向呆立的阿尔德巴兰缓缓走来，迎面站定，笔直地与他相对。

那张他这一生中看得最多、看得最久的『魔女』的脸上——浮现出一个他从未见过的表情。

「——只是时运不济罢了。」

他明白，那就是说，这并不是阿尔德巴兰的错。

情绪汹涌而来，尚来不及下结论之际，梦之城便猝然终结。

像把纸芝居的舞台都撕裂般的粗暴收场，而在那之后显现的，是惨烈的现实。刹那间，痛楚与失落攫住了大脑，喧嚣与鲜血侵蚀着他的认知。天地被染得漆黑一片，黑到连时间的感觉都迷失其间；阿尔德巴兰的慟哭，被崩坏世界的悲鸣涂抹殆尽，甚至传不到他自己耳中。

然而，在那样一个一切尽皆错乱的世界里，在嘈杂到连自己声音都听不见的轰鸣之中，那道沙哑、孱弱、奄奄一息的声音却清清楚楚地传了过来。

不容错过的『魔女』的，最后的吟唱——

「——奥尔・纱幕」

×××

阿尔德巴兰下一次恢复意识，已是万事终结之后——不，岂止是终结，又再度开始；开始的终了，再开始又终了。像那样一遍又一遍地反复了不知多少次之后，世界上已不见『魔女』的丁点痕迹。

是因为前提不同，抑或因施术者是拥有绝大力量的『魔女』，那与自己操使时截然不同的魔法效果令他一时茫然——

「——你，从哪儿来的？你是什么人？」

发问，来自一个他全然陌生的声音。

和阿尔德巴兰一样衣衫褴褛、寒酸落魄的男人，正用夹杂着惊惧与警惕的目光看着他。

话是听得懂的。虽说与人打交道的经验贫乏，但在某种意义上这也不成问题。

要紧的是，这里是哪里，如今又是什么时候。

「基奴海布……剑奴孤岛。『魔女』？那都是几百年前的事了吧？」

男人像是被问了怪话，语气里带着狐疑。阿尔德巴兰吐了口气。见状，男人的神情由狐疑骤然变作骇然。

因为那口吐出的气化作了呜咽，阿尔德巴兰当场崩倒，泪如雨下。

『——谁也赢不了我亲手造就的你哟』

几百年前被他遗下的那位『魔女』的话，至今仍牢牢黏在他的灵魂上，挥之不去。

因自己让那个人成了说谎者这一罪孽，阿尔德巴兰只想一死了之。

可他死不了。

** 『阿尔德巴兰 Ⅱ』

「——老梗重炒，抱歉了，王牌再临。」

话音刚落，正上方一块超重量级的巨岩直坠而下。

明知会被骂成『炒冷饭』，阿尔德巴兰仍甘之如饴地使出这一步。正一边躲过自岩壁伸出的石之巨臂一边飞来的艾米莉娅，神情一变。

「——」

起初，她为巨岩的存在瞪大了眼；随即，王都里被阿尔德巴兰轻易甩开的悔恨浮上脸颊与眼角。

为不让心被那份败北感压倒，她猛地闭了闭眼，再睁开时把坠落的岩块映入视野，心头「我能做到吗……」地闪过一瞬软弱，旋即又像在给自己鼓劲似的——「只能上了！」精神一振，目光比动摇前还要凌厉有力，牢牢望向前方。——而这一连串百变的表情，不过一秒之间，她调整心绪的速度之快，真叫人惊讶。

「不过，光靠气势可不顶用啊。」

巨岩擦削着峡谷的岩壁一路坠落。

振作起来的艾米莉娅首先尝试的，是在巨岩的下落轨道上盖上一道巨大的冰盖，以承受那块大岩的重量。——然而阿尔德巴兰却以魔法造出的岩弹炮狂轰猛打，发射岩石炮弹，直接把峡谷的岩壁打穿，粗暴地加以阻挠。

墙壁被砸碎，那本该严丝合缝堵住峡谷的冰盖也再难贴合，只能作为与巨岩一同坠落的无聊追击。

「那就——！」

眼见用冰盖承受岩石失败，艾米莉娅立刻换上下一手。她将先前抛弃的冰之翼重新背负，仿佛再临般收拢修长的双腿。随即，将鞋底对上贴在她正后方的冰之兵们的踢腿——借来那股原本的菜月・昴绝对无法施展的腿力，一举飞翔而起。

———

猝然加速的艾米莉娅令对手大意，从岩壁伸出的数百条手臂纷纷抓空，放过了艾米莉娅的逃离——不，是放过了她对阿尔德巴兰的呐喊般突击。

因将心神与动作分去迎击，逃窜的阿尔德巴兰速度与气势都放缓，与猛冲上前的艾米莉娅之间的距离迅速拉近。

为争取时间而留下的雅耶，她好不容易创造出的优势被一下子清空，耳畔传来她的挖苦：「阿尔大人哪，真是让人白费力气呢～」

「要是在这儿被逮住，那可真就成那样了啊！」

阿尔德巴兰回敬了幻听中的雅耶一句，随即以飞石的弹幕迎击艾米莉娅。可对这招紧随『坠岩』之后的二手把戏，艾米莉娅却在空中宛若神祇般一扭身，轻灵躲过。

「开什么玩笑！？」

能靠那对本该难以自由操控的人造羽翼做到这一点，这一事实令阿尔德巴兰目瞪口呆。

理所当然，冰做的艾米莉娅酱的羽翼并没有扇动。她此刻那条立体的飞行轨迹，其奥秘在于：在巨大的冰翼内侧又追加了小型冰翼——通过叠加多层冰翼，改变切风的方式，并借身体的倾斜让翼缘吃风，从而新增了以姿态控制机动的功能。

这种近乎航空力学的应对，她无疑全凭天生的直觉在做。

「要追上了——！」

即便为回避而做出横向回转，艾米莉娅的速度几乎不减。

她这一声喊出口的同时，两人之间的距离飞速缩短。照这速度下去，就连坠落巨岩的波及范围，她也能及时脱离。连自以为是杀手锏的一击都被从容躲开，阿尔德巴兰当真是千钧一发——那一瞬间，本应是身处局中的两人都不约而同得出的判断。

「——」

艾米莉娅那双紫绀色的眸子陡然瞪大，清丽的大眼被惊愕的色彩尽数染上。

在她的视野里，阿尔德巴兰没有做出任何特别的举动。不中的飞石仍在连番抛来，却没有展开新的魔法，也没有施展绕开她的超机动。

就算面对借助冰兵之力、势头更盛的艾米莉娅的飞行也一样。照这样下去，他会被迎面飞来的她追上，便再也躲不开那冻彻的指尖。

那也就意味着，艾米莉娅将达成此地战局的胜利条件。——尽管如此，艾米莉娅的眼中却没有喜悦或得意。

因为——

「——我不是说过了吗，要来一记重复桥段。」

当初为了拦下坠落巨岩可能造成的惨重破坏，作为交换，阿尔德巴兰得以在王都与艾米莉娅的战斗中赢了就撤。

因此，就算被说成毫无新意，他也要照搬那套曾经奏效的策略。只是，这一次，这里不会有任何无辜的民众被卷入。——无辜的民众是不会的。

「——阿尔！！」

艾米莉娅高声呼喊，拼命伸手向阿尔德巴兰探去。——伸向那名除她之外、唯一会被落石之威波及的存在。

164

——胜负已分！干得好，竟然从『斯帕鲁卡』里活了下来！从今往后，你也是这剑奴孤岛上的剑奴之一！欢迎啊，你这个废物！

这粗野的欢迎与称赞，和辱骂几乎没什么分别。

紧随其后的，是粗鄙下流的喧嚣，将会场整个吞没。阿尔德巴兰一边听着，一边扶着那具庞大的尸体跪倒在地。

他无力地倚靠着的，是脖颈粗壮、被长剑深深贯穿而断绝气息的魔兽基尔提拉乌的亡骸。基尔提拉乌失去了右侧的前足与后足，脸上残留的神情，与其说是痛苦，不如说是在混乱与困惑之中被夺走了性命。

望着那可怜的死相，阿尔德巴兰肩头随着粗重的呼吸起伏，不禁心生悲痛——但他很快就厌恶起自己，这份同情实在过于虚伪。

「能活下来，不错嘛。真让我吃惊。」

迎上这副破败模样的阿尔德巴兰的，是个衣着粗陋的男人——剑奴孤岛上的一名剑奴，也是他醒来时第一个发现他的人。

那名男子之所以神情复杂，大概是因为在他看来，阿尔德巴兰竟能在新人登龙门——『斯帕鲁卡』中活下来，实在不可思议。再说，作为最先发现他的人而倒霉地被指派去照看阿尔德巴兰，他心里也许还觉得，要是阿尔德巴兰索性死在这场『斯帕鲁卡』里，反而不用让麻烦长期缠身。

无论如何，阿尔德巴兰的存活令那名男子吃惊，而吃惊的并不止他一人。

阿尔德巴兰同样也无法掩饰对自己仍然活着的惊讶。

——在一场不容败北的战斗中落败后，阿尔德巴兰被遗落在了未知的环境里。

陌生的环境，陌生的人群，连规则都含糊其辞的地方，对阿尔德巴兰而言简直就是未开之地，仿佛被丢进了一个全新的世界。

唯一可以确定的，是自己大概已经失去了存在的价值，而就连会为这份价值的丧失而悲叹的人，也一并失去了。

所以——

「嘴上嚷着想死，果然还是光说不做啊。」

那名男子半是刻薄、半是冷嘲的话语，将阿尔德巴兰的心一刀刀划开。

在意识到自己首战落败，却又从本该到来的终结中苟活下来时，阿尔德巴兰被无尽的失落与自责吞没，打心底里只想一死了之。对这样的他而言，剑奴孤岛考验新人的『斯帕鲁卡』再合适不过。

那种随口带过的说明未免太过不近人情，但归根结底，那就是一场被迫拿命去博的试炼——无法成为剑奴者，唯有一死。对巴不得赴死的阿尔德巴兰而言，简直方便得不能再方便。

事实上，阿尔德巴兰与同样境遇的四名新人一同被押往斗技场，与基尔提拉乌相对之时，他打算就此不作抵抗，任人宰割。可就是这样，阿尔德巴兰却活了下来。

在阿尔德巴兰以外的男人们或是上前挑战、或是仓皇逃窜、或是低声哀求，终被一一杀死之际，成了最后一人的阿尔德巴兰，本该在挨了魔兽的爪击、又被踩断肋骨、口吐血沫之中迎来死亡。

然而——

「没有人能战胜我所创造的你。」

那句话掠过脑海的瞬间，阿尔德巴兰已经展开了『领域』。

与那个挑战了数亿次仍然无法战胜的对手相比，只花了三百四次就能反杀的『斯帕鲁卡』，对阿尔德巴兰而言并不算痛苦。

真正的痛苦在其后——在侥幸活下来的自我拷问之中。

——为什么，怎么会，抱着什么念头，自己竟没有死？

「嗯？想知道外面的事？就算你这么说，我来这儿也很久了啊……」

被承认为剑奴的阿尔德巴兰，得到了在这座岛上生存的资格。

在这座封闭的岛上，他明白了这里隶属佛拉基亚帝国，被囚的剑奴们被迫上演供人取乐的厮杀，岛内的治安早已死绝。可他想知道的仍旧还有很多。

于是，饱受阿尔德巴兰穷追猛问的，便是负责照料他的那名剑奴。

「不是最近的局势，而是想知道历史吗……我也不算多懂啊？嘛，关于『魔女』的事……『嫉妒魔女』这种程度倒是知道。」

他本来也没抱什么希望去打听『魔女』，没想到那名剑奴竟然知道；而对方则像连开口都觉得可怕似的，讲起了关于『魔女』的传说——然而，那些传说却只指向『嫉妒魔女』一人，这让他更为震惊。

差点毁灭世界，最终被『三英杰』之手封印的『嫉妒魔女』。

除此之外，这世上再无其他『魔女』的传说，大罪之『魔女』的记录也无处可寻。而且得知那还是将近四百年前的事，阿尔德巴兰不禁绝望。

四百年那样漫长的岁月，竟把大罪之『魔女』们的痕迹从世上抹去，连那位不惜舍弃一切也要履行约定的『魔女』，她的存在都要被遗忘吗。

然而，更残酷的是——

「——『强欲魔女』？那是什么玩意儿。不会是你臆想出来的吧？」

面对男人的质疑，阿尔德巴兰无言以对。

绝不可能是妄想。与『魔女』共度的日子确凿无比；她的教诲、指尖的触感、曾对他说过的每一句话，阿尔德巴兰全都记得。

这世上确实曾有另一位『魔女』，她要对抗那位潜藏可怖力量的『魔女』。——阿尔德巴兰是她的弟子，也是她的王牌。

「可恶！这算什么啊！我不过照你问的老老实实回答，竟然说打就打！」

因『魔女』的存在遭到否认而怒火中烧的阿尔德巴兰挥拳相向，被他殴打的男人恶狠狠地吐出这番话。

被抛进这片环境——不，抛进这个新世界后，与最初的恩人分道扬镳就是以那样的方式发生的。除此之外，他也以相似的方式与其他剑奴决裂，阿尔德巴兰因而陷入孤立。

——他被传成是个被『魔女』蛊惑的异常者。这样的风言风语，他不知听过多少次。率先四处宣扬的似乎还是那位恩人；某种意义上，这评价也不算错，他无意更正。

然而，被人拿来和什么魔女教那群莫名其妙的家伙相提并论，却令他愤懑。

据说，那帮人打着让『魔女』复活的旗号，在各地干的尽是近乎恐怖行径的勾当。为此他又去闹事，嚷着别把他与那种家伙混为一谈，名声也再度恶化。

「……像你这种迷恋魔女的疯子，绝不会有好死。」

那是当时由剑奴孤岛的总督撮合的一场死斗里，被阿尔德巴兰的蛮刀斩杀的第一位恩人，临终吐出的怨言。

阿尔德巴兰一边拭去溅在身上的恩人返血，一边对那句「绝不会有好死」的临终恶语深深点头——这话，八成没错。

『领域』依旧健在，阿尔德巴兰在剑奴孤岛的死斗中一次又一次活了下来。

凡是称他为魔女狂的家伙，最终无一例外都被安排与阿尔德巴兰对上，统统倒在那口蛮刀之下。

阿尔德巴兰无意泄愤。也不想为『魔女』洗刷污名。说到底，『魔女』们的末路并非蒙冤背锅，而是连存在本身都被抹消了。

因此，阿尔德巴兰没有把自己活下去的理由寄托在『魔女』身上。——他只是想知道，自己究竟是为了什么才被留下这口气。

为了知道这个答案，他不能死。

从最初的『斯帕鲁卡』活下来，之后的每一场决死之战都活下来，都是为了这个。

所以，他动用『领域』，每当与人交锋，便吞下数百次死亡，在践踏无数剑奴性命的同时，活下去。活下去。一直活下去。

而后——，

「——竟然活了下来。你那连上位者都奈何不了的恶运之强，令人折服」

就这样，对于阿尔德巴兰捡起微末胜机、反杀更强对手的胜利，总督投去了既像嗟叹又似钦佩的称赞。

将断裂的蛮刀掷去，阿尔德巴兰背对着欢声稀少的斗技场。

——自从在剑奴孤岛醒来，十年转瞬即逝。

165

『——谁都赢不了我创造出来的你』

十年的岁月太长，毫不留情地将阿尔德巴兰的人性一寸寸削落。

一闭上眼，那些本该能清晰忆起的脸庞、声音与温度，便仿佛被我亲手了结之人的死相、他们临终的惨叫，以及那冰冷的溅血，一层层涂抹殆尽。

『——谁都赢不了我创造出来的你』

没错。那句话没错。确确实实，谁也杀不死阿尔德巴兰。

这十年里，阿尔德巴兰被一次次赶往剑奴孤岛『斯帕鲁卡』，在生死擂场上不知跨过了多少回生死一线，把那些看上去根本不可能战胜的高手，乃至非人的怪物，尽数斩杀。

因他接连上演以弱胜强的奇迹，为了让阿尔德巴兰死在台上而拼凑出的莽撞死战并非一两次；可每逢如此，倒下的总是那些被看好的剑奴。于是，阿尔德巴兰的存在也渐渐成了一种禁忌，几近不可触碰。

『——谁都赢不了我创造出来的你』

十年一过，剑奴孤岛上的面孔早已与最初判若两人。

阿尔德巴兰早就成了最资深者之一，知晓他那『被魔女蛊惑的异常者』流言的人，一个也没剩下。阿尔德巴兰也在明白『魔女』的话题是禁忌、而绝大多数人不过知其传说的皮毛之后，彻底不再提起『魔女』。

然而，那并非因得不到想要的答复而生的失望或死心所带来的变化，而是更为深重的东西。

『——谁都赢不了我创造出来的你』

十年，被遗落在剑奴孤岛，被迫不断厮杀，在那只反复上演生死交换的空间里，支配着阿尔德巴兰的，是无边的绝望。

那是对『魔女』是否真的存在、对其存在本身都生出怀疑的绝望。

『——谁都赢不了我创造出来的你』

只要闭上眼睛，那声音确乎还能听见。他记得，的确被那样说过。

然而，可是，那件事，真的，存在过吗。

『——谁都赢不了我创造出来的你』

『魔女』的脸，想不起来。

『魔女』的声音，想不起来。

『魔女』的温暖，也想不起来。

那些回忆就像那盘十年来只要一有空就反复回看的录像带，被磨得发白；就算把扯断的带子勉强接回去也再无法播放，最终连带子本身都化作尘埃。

于是当回忆本身化为碎屑，尘埃从指缝间尽数漏尽之时，阿尔德巴兰已分不清了。

——『魔女』真的存在过吗？

——阿尔德巴兰的记忆，真的是确实发生过的事吗？

『——谁都赢不了我创造出来的你』

有时，他会不由分说地想把名为『自己』的存在砸个粉碎。

这种时候，阿尔德巴兰便故意解开『领域』，赴一场死战，让那些拼命进攻的对手把自己打得稀烂，想要去窥见死亡的深渊。——不，岂止是窥见，他甚至会想，索性就坠崖算了。

可偏偏在这种时候，『领域』总会以出乎意料的方式救下阿尔德巴兰。

『——谁都赢不了我创造出来的你』

仿佛为了证明那位连真实是否存在都令人怀疑的『魔女』的话语，那些明明只差一步就能杀死阿尔德巴兰的对手，却一次次在他眼前精神崩溃。

每当看到对手翻着白眼，失去理智与战意，阿尔德巴兰便觉得有某种看不见的东西在试图让他活下去，怀着难以排解的郁结，将对方的首级斩落。

十年过去了，阿尔德巴兰所追寻的、自己为何被留下性命的意义依然不得而知。

甚至连是否真有那样一个试图让他活下去的存在，也令人怀疑。

『——谁都赢不了我创造出来的你』

只是，太可怕了。

塑造自我的一切若竟都是虚妄，『魔女』为他倾注的心力与言语其实一件都不存在，那么阿尔德巴兰会不会只是个被『魔女』迷住的疯子？在这样的自问自答中，他的内心被一点点侵蚀，失眠的日子一连持续了好几年。

『——谁都赢不了我创造出来的你』

那句曾经是阿尔德巴兰的依托、构筑自我根基的话语，如今却可怖到了极点。

不断地怀疑着：这一切是否只是臆想的产物；阿尔德巴兰所背负的使命，理应存在的相逢与离别，是否全都从未存在过。

『——谁都赢不了我创造出来的你』

无尽头的自我质询之螺旋。

仿佛坠入一个无法给出答案、被阴郁绝望灌满的泥沼，不止腰部，连胸口都沉没其中，动弹不得。

那样的时光，只剩下无法决定该如何去死，而它还将无休无止地延续下去。——阿尔德巴兰停滞的岁月，却在某一天，突兀地迎来了转机。

那场转机——

「——听好了，散落在剑奴孤岛上的乌合之众。」

——那是透过传声管回荡在整座岛上的声音，带着如少女之焰般凶猛的炽热。

166

——剑奴们的一齐蜂起，以及把对其的应对当作佯动的新皇帝暗杀计划。

降临在阿尔德巴兰身上的转折，其真相似乎便是如此。

不过，身处剑奴孤岛的一介剑奴，不可能得到详尽的信息，阿尔德巴兰也不打算再去追究更多细节。姑且就岛上运作并无变化这一点来看，他认定政权并未被颠覆。

至少，在这一时点，关于皇帝更替的说法并不在阿尔德巴兰的认知之中。

若说在此次事态中，有什么让阿尔德巴兰切实体会到自身发生了巨大的变化，那便不言自明——他救下了那名陷入险境的银发少女。

当然，这与阿尔德巴兰本来的目的无关。

那银发少女是个偶遇的犬人女孩，与阿尔德巴兰所牵连的那位银发之人毫无关联。然而，能救下她这一点，以及在骚动之中以唯我独尊之姿走自己道路的那位宛如火焰般的少女的声音，一并促使阿尔德巴兰下定了决心。

——为确认『魔女』的真实存在，他要走出这片封闭的世界。

『——谁都赢不了我创造出来的你』

一次又一次被放养在湖中的水栖魔兽杀死，阿尔德巴兰终于脱离了被囚禁十余年的岛屿，踏上了不被水所环绕的陆地。——严格来说，这个世界是被巨大的瀑布整圈包裹着的，所谓不被水围住的陆地根本不存在。能想起这种轻松的调侃，也说明他还能强打起些精神。

『——谁都赢不了我创造出来的你』

那对阿尔德巴兰而言，是诅咒，是慰藉，是束缚，也是宽恕。

为了辨明那份暧昧而无定向、却又无比庞大的感情之源的色彩、热度，以及那种不确定中的确定，阿尔德巴兰决定追寻『魔女』的痕迹。

可供挥霍的时间并不多。在那座封闭的岛上度过的十余年间，不知不觉间，阿尔德巴兰如今所行走的世界，正逐渐逼近他记忆中的那个世界。

接下来，只需确认阿尔德巴兰心中的那样东西是否为真。而要确认这一点，所需要的，是关于『魔女』的确证——

「——为何『福音书』里没有记载您的存在呢？」

话虽如此，对于那位把脑袋夸张得过分歪向一边的魔女教大罪司教，阿尔德巴兰虽大致明白其中缘由，还是只用指尖拨弄着头盔的金属件，含糊其辞地把话搪塞了过去。

他自那时起便一直戴着的漆黑铁盔，是从剑奴孤岛带出的饯别之物；它既结实耐用，又是能将面容完全遮蔽的全罩式，他对之爱不释手。

像那样外观引人注目的对手，在重要的『福音书』里却只字未提，这一点似乎很不合这位嗓门大、动作也聒噪的大罪司教的胃口。

「——你是，『怠惰』，对吧？」

老实说，与这位大罪司教的一战，是阿尔德巴兰一生中屈指可数的苦战。

本就如此，能做到一次都不死就取胜的情况反而寥寥；即便如此，这家伙依旧是个连捡拾一线胜机都极为艰难的强敌。最终，虽说达成了胜利条件，却终究没能取胜。

大罪司教的『魔女』们 —— 与那群『魔女』本尊一样，即便拿来和那些存在都成疑的她们相比，也是在凶恶程度上丝毫不落下风的对手。

总之——

『——谁都赢不了我创造出来的你』

拿到想要的情报后，阿尔德巴兰心想，这么一来，总算也算有个交代了。——要确认『魔女』的实在性，最有可能掌握线索的，便是在剑奴孤岛上也屡次听闻其名的邪教组织——魔女教。

据说他们平时藏身何处全然不明，不过那只是当你试图去搜寻时的情况；若要将其引出，却并不困难。——只要散布魔女教所崇奉的『嫉妒魔女』的风声，便会有人疾驰而至。

当然，若应付不了那些风驰电掣赶来的家伙，那就只会无惨送命，落得个世上最愚蠢的死法。

「住手！这是不敬！莎缇拉！除了莎缇拉——除了『嫉妒魔女』之外的『魔女』的话题！简直是不敬至极！在这世上有资格再临的，唯有那位会赐予我宠爱的她一个人！！」

对于这位把常轨尽弃、失却理智的言行堆叠到骇人程度的大罪司教，他的言辞究竟能信到何种地步，尚不得而知。

然而，那疯子的激白即便对旁人毫无意义，于阿尔德巴兰而言却不同。

『——谁都赢不了我创造出来的你』

他锲而不舍地一次次重来，与大罪司教反复遭遇，套出话头，完成必要的交涉，又一次次逼他爆发，随即以性命为代价，再从头开始——就这样不懈叠加，阿尔德巴兰终于从大罪司教那里获得了想要的情报。

随后，他径直无视那位飒爽赶来的大罪司教，让那场相遇仿佛从未发生。

啊啊！啊啊！呜呼！怠惰怠惰怠惰怠惰怠惰——啊！！

可以想见，阿尔德巴兰从魔女教的包围网中脱身并隐去行踪，会让那个失手的大罪司教气得吐血般发出惨烈的嘶吼，但他已不再在意。

此时阿尔德巴兰心中只有一个愿望——确认『魔女』的确存在。

他知道大罪『魔女』们各自的死法。

『愤怒魔女』被诱入陷阱而狂死，『色欲魔女』在大火中被烧尽，『暴食魔女』在沙之海里枯死，『傲慢魔女』被沉入滔天洪水，『怠惰魔女』屠龙后坠入大瀑布。

而『嫉妒魔女』被封于世界尽头，至于最后那位『魔女』——

——原来如此。能从墓地之外进入此地，这在结构上就是个缺陷。『圣域』的机制也罢，收尾都显得过于粗疏。虽说其中也有不得已之处。

在那广阔得望不见尽头、近乎不真实的蓝天下，延展着一片草原。清凉的风掠过的小高丘上，摆着一张白色的桌子和一把阳伞。

那无疑是阿尔德巴兰心中那幕几近淡去的记忆景象。

其中心，是只用黑与白两色便能描绘的美丽存在——

「——爱为何会减少呢？」

历经曲折，他终于回到了梦中的城堡。

怀疑起自己的神智，阿尔德巴兰甚至差点相信这也许不过是个幻影。

与那名弟子的重逢，于他是相隔十数年，于她则跨越四百年；真实存在的『魔女』——不，『强欲魔女』以一抹不见血色的微笑致以祝贺。

167

「——」

对阿尔德巴兰而言，成了独臂之后度过的岁月已经更长。

因此平日里，他几乎不会把只有右臂当作劣势；可即便如此，极为罕见的时候，他还是会在那上头感到不便。

比如，当他不得不抱着一个失去意识的人时。

「这硬邦邦的，饶了我吧。」

如此嘀咕着的阿尔德巴兰怀中——连同那只由魔法造出的石制义臂在内，他抱着的，正是浑身无力、昏迷不醒的艾米莉娅。

辽阔峡谷中拉开帷幕的阿尔德巴兰与艾米莉娅的空中追逐，最终因阿尔德巴兰使出的犯规招数而落幕，以艾米莉娅倒地收场。

不过如此而已。他的王牌，正与在王都逃脱艾米莉娅之手时所用的一样。

心地善良的艾米莉娅，无法坐视在战斗中有人逝去。——她同样在帝国的『大灾』中失去了普莉希拉，心上留下了深重的伤痕。

因此，为了庇护硬生生站在落下巨岩直击路线上的阿尔德巴兰，她毫不犹豫地挺身而出。

「虽说没有别的万无一失的命中法，这招连我自己都觉得下作。」

当然，这也是阿尔德巴兰在反复试探、尝尽其他计策之后的结论。

无论是调校巨岩的落点，击碎岩体引发石崩，甄选飞石弹幕的航道，还是夹杂其他魔法，他都一一试过；然而，除了把自己当做人质这一策外，艾米莉娅皆凭借当场的灵光与直觉判断，漂亮地逐一破去。

每每实施其他方案的愚蠢阿尔德巴兰，终局无非是被艾米莉娅的手指一触便冻作冰雕的未来，因而也只能依赖这道苦肉计。

「这并不会让罪恶感消失，也不代表能得到原谅。」

这种并非要说给谁听的借口，幼稚得就连艾米莉娅也不会原谅。

为庇护阿尔德巴兰，毫无防备地被巨岩的体量擦过的艾米莉娅，浑身遭到重击，终究还是失去了意识。乍一看并无会留下后遗症的伤，最多也只是较为严重的脑震荡——为使结果不过如此，他谨慎地拿捏了分寸。

「这一绕可真够远的啊。……等雅耶，才是上策吗？」

自高处坠落、与艾米莉娅的追逃一幕告一段落后，他这才腾出余裕确认四周。于是明白过来，这里恐怕位于号称世界最大峡谷的阿格扎德峡谷之中，而他们与目的地摩格阿雷德大喷口之间已被拉开了巨大的高差。

他们已越过露格尼卡王国的国境，闯入卡拉拉基都市国家；可要沿着坠下的数千米再艰难攀回，回到原先的路线，恐怕得花上相当一段时日。

况且——

「且不说奥尔塔，罗伊和大叔还能汇合得上吗……？」

在被分开的共犯者当中，『阿尔德巴兰』的战斗力倒是让人放心，可罗伊・阿尔法德和亨克尔，无论实力还是人性都让人极为不安。当然，罗伊的行动被咒印束缚，只要还惜命，理应不会违反规则。

不管怎样，最稳妥的还是指望他们在集合地点齐聚。

阿尔德巴兰当下最该优先的是赶往摩格阿雷德大喷口，并完成目标。

为此目的需要『阿尔德巴兰』的力量；最坏的情况下，即便没有『阿尔德巴兰』，也并非毫无办法。再者，罗伊『暴食』的权能之力，是为这次计划所利用的灾厄善后所不可或缺的。

所以，就算是在达成目的之后，也得设法会合，让他们服从指示。

打着防止二次灾害的主意，结果把三次四次灾害都闹出来，那可真是要命。

一边这么嘟囔着，阿尔德巴兰倾了倾背上的石翼，在维持速度的同时，慢慢朝峡谷地底、顺着那条奔流的大河岸边，总算顺利着陆。——骗你的。怀里抱着艾米莉娅连着自爆了六回，好不容易到第七次才总算成功落地。

要是这会儿连站都站不起来，那可真成笑话了。

有一次不光是双腿，连腰都遭了殃，险些全身麻痹，连毒都喝不下。好不容易设法滚进河里溺死了，但同样的失误不想再犯。

总之——

「抱歉了，艾米莉娅……小姑娘。」

为了防止万一大河暴涨、水位上涨把人淹了，阿尔德巴兰没有把艾米莉娅放在低处，而是将她横放在岩壁上一个略有高度的凹处。

就这样把她撇下之前，最后一句话要怎么称呼她，他犹豫了一下。犹豫过后，终究还是照往常那样，以阿尔德巴兰的方式称呼了她。——除此之外，那些能代表他与她之间『正确关系』的称呼，在这段并不正确的关系里，他没有勇气说出口。

「——」

刚咒骂了自己的怯懦，便有一阵令人眼前发黑的头痛疾驰而过，阿尔德巴兰咬紧了牙。

好不容易渡过难关，刚一松懈，积欠便要汹涌爆发。他硬是将其拽住，深呼吸十秒，然后仰头灌下毒药——反复如此，才勉强稳定住精神。

可这种做法就算能让心稍稍换口气，身体——尤其是大脑——却没法换气。

按实际时间算，他的大脑已经连轴运转了将近一百个小时。

一路上，靠着阿尔德巴兰的治愈魔法东拼西凑地撑了过来，但若是不把身心彻底关机一次，这份过载恐怕不会缓解。

尽管如此，他仍告诫自己再咬牙坚持一下。

『——谁都赢不了我创造出来的你』

「啊，是啊，老师。——谁都赢不了我。没错。就是这样。」

一闭上眼，那句话便在阿尔德巴兰的脑海中复苏。

以此为支撑，阿尔德巴兰——、

「——看吧，又。」

「——」

「又是妾身的——」

「——」

「妾身的——」

断断续续、含混不清的声音，传来了。

因为知道那是谁的声音，是何时说过的话，也知道那会把自己的灵魂灼烧到何等地步，阿尔德巴兰堵上了心灵的耳朵。

不能停下。就这么决定了。已经决定了。

他下定了决心：果然，绝不能停下脚步。

既然决定了——、

168

——那是在堵上心灵之耳的阿尔德巴兰，好不容易爬上峡谷，刚刚重新启程赶往摩格阿雷德大喷口的当口。

「……啊」

从阿尔德巴兰口中溢出的，只是一声嘶哑的吐息。

不由得脱口而出也无可厚非。毕竟那是从意识的盲区飞来的意外，是他在脑海深处都认定不可能发生的突发状况。——就在阿尔德巴兰的行进路线前方不过两米处，一根巨大的冰柱轰然刺落。

「――――」

咽下口水，回头望向峡谷的深处——被他留在那里的艾米莉娅，正是她把这根庞大的冰柱砸了下来。

不过以她所受的伤势，艾米莉娅的意识要恢复少说也得几小时。也就是说，她在昏迷之中，硬是甩出了这最后一击。

「这执念也太可怕了……」

尽管如此，若是阿尔德巴兰再早五秒登上崖顶，此刻就会被那根冰柱直接压在底下。由此看来，他算是从两方面都躲过了悲剧。

当然，就算被正面命中，阿尔德巴兰也能凭借权能把这一刻重来，把结果导向不挨这一击。可不论是为了艾米莉娅，还是出于阿尔德巴兰自身的精神卫生，最好都别让她亲手了结他的机会出现。

即便如此——

「战斗里这种事偶尔也会遇到，但还是够吓人的」

即便在剑奴孤岛『斯帕鲁卡』，在你死我活的搏杀中，也常有已负致命伤的对手榨尽最后一丝生命力，挥出足以把人一并拖下水的反扑一击。以阿尔德巴兰的经历来说，甚至有家伙被斩下头颅之后，还把他给杀了。

人一旦将「就这么做」刻进行动里，即便意识或性命已经流逝，残留在四肢上的意志余烬也会驱使身体去把那件事完成。

方才艾米莉娅那昏迷前的最后一招，也是「无论如何都要拦下阿尔德巴兰」这份心念的具现——

「——慢着。」

正想称赞那份精神力的阿尔德巴兰，猛地屏住了呼吸。

眼前，擦着阿尔德巴兰身侧钉入大地的冰柱——不如说是一柄巨大无比的冰之长枪，仿佛只有神话中的巨人才会挥舞的那种。可若是以击杀阿尔德巴兰为目的而放出的招式，无论如何也未免太夸张了。

这般巨大的东西，简直就像——

「——锚。」

就在他不由自主低声吐出这个词的下一瞬——以艾米莉娅打下的冰之长枪为标记，正欲奔向摩格阿雷德大喷口的阿尔德巴兰，迎来了新的刺客。

那是——

「——哟，头盔佬，这才一会儿没见，就成这副破烂模样了啊。」

「……这话彼此彼此，你说话也变得够难听了啊，菲尔奥蕾。」

彼此都挺过了战场的第一阶段，迈入了下一个局面。

由菲尔奥蕾・露格尼卡——不，菲鲁特——率领的混成军，正如先前把『记忆』的闪光弹猛然掷来之时那样，横在前方。

** 『魔人 VS 魔女』

「——我也和你一样，是个不成器的姑娘。」

阿尔德巴兰永远不会忘记『魔女』说出这句话时那抹忧郁的神情。

他不禁这样想着。

连这样一位一张脸仿佛把世间万有的规律尽收眼底、态度好似将知识的根须延展至世界每个角落、举止间像是通晓森罗万象的『魔女』，竟也会有想要哀叹自己力有未逮的时刻吗。

「当然有。要说的话，你的存在……你现在会是这个样子，本身就像是在证明我还不够。」

被这么一说，阿尔德巴兰心中五味杂陈。

对阿尔德巴兰而言，这位『魔女』的存在分量极重——虽不愿承认，但确实伟大。尽管几乎没有可供比较的对象，可不论拿来同什么相比，她的存在感都大得惊人。

听她自称不成器，阿尔德巴兰并不觉得欣喜。

只是，若非那样的自我认定，阿尔德巴兰与她也不会有如今的关系。倘若『魔女』身处一个无需承认自身不成器的立场——

「那时候，不过是我和你都待在各自本该待的地方而已。把心思放在没有那样发展的未来上是自由的，但不巧你抽中了最坏的命运。抱歉的是，这对我而言却是侥幸呢。」

那种故作恶相的说法里，仿佛等分掺着『魔女』式的幽默与『魔女』式的真心。究竟如何，其实并不清楚。

一向扬言自己不懂人心的『魔女』，她的本心对与她相处已久的阿尔德巴兰而言也依旧暧昧、难以捉摸。

然而，若『魔女』的说法属实，那就有些奇怪了。

毕竟，眼下的境遇对阿尔德巴兰来说，似乎正值运势最坏的星象，可阿尔德巴兰却不曾把与『魔女』共度的日子当成不幸。

确实，他曾以『试炼』之名被迫体验被杀百万次，也即便他厌恶并拒绝，仍被人以自己不喜欢的名字呼唤——这样的环境无论如何都同常人的幸福相去甚远。

「竟能在与一个不成器的『魔女』的生活里发现价值，你也真是个可怜的孩子。」

那是句既自嘲又嘲人的复杂低语。

然而，其中那抹怎么也藏不住的温柔回响，阿尔德巴兰并未错过。

即便渺小、即便容易混淆、即便难以分辨的情感，『魔女』身上也确确实实存在。去寻找足以让人相信这一点的痕迹，是阿尔德巴兰的嗜好。

究竟如何不得而知，也许不过是一厢情愿或误解。

重要的是阿尔德巴兰如何感受；『魔女』的真意属于『魔女』。——于阿尔德巴兰而言的真相，属于阿尔德巴兰自己。

「能这样干脆地割舍的姿态，真是很相像呢。果然，所谓影响不容小觑啊。」

『魔女』眯起黑色的眼眸，指尖拨弄着额前的白发，如此说道。

那是『魔女』隔着阿尔德巴兰望向某人，又看着映在阿尔德巴兰眼中的自己时，低声吐露的述怀。

影响，当然会有。无论是出身，还是成长。

于阿尔德巴兰如此，于『魔女』亦然。

不成器、不充分、不完整。——那对『魔女』而言，是应当蒙羞的过去吗？

正因如此才有与『魔女』共度的日子——这样想，是诅咒吗。

若要说还有一件可以肯定的事——

「——阿尔德巴兰」

在阿尔德巴兰的十年，与对方而言跨越四百年的熟悉光景中重逢之时，他所目睹的『魔女』—— 不，『强欲魔女』的身影，否定了那日她所言的拙劣之处。那一刻，阿尔德巴兰尝到的，是难以承受的失落与绝望。

169

——咔哒咔哒地用指尖拨弄着黑盔的金属扣，阿尔德巴兰俯瞰着局势。

眼前，几乎令人感到神圣的巨大冰之锚矗立，而以其为标记整齐列开的阵容，正堂堂与阿尔德巴兰对峙。

与之相对的是以菲尔奥蕾——不，以菲鲁特为中心的一队人马。对于她们竟能在此齐聚的意义，阿尔德巴兰并未刻意追问。

不问也明白——罗伊和亨克尔败了。

倒不至于连『阿尔德巴兰』都输了吧；可既然『龙』没有赶来，看来连『阿尔德巴兰』也不知被什么办法牵制住了。

老实说，虽说有『权能』和『不杀』两重束缚，可在打倒了『暴食』的大罪司教之上，连『神龙』都做了对策，实在超出想象。

究竟备了什么计策，就算问了也不会得到回答吧——

×××

——二百四十六。

「不管怎么说，魔女因子这回事，你的觉悟也未免下得太过头了吧，佩特拉小姑娘。」

「——」

被阿尔德巴兰这样正面一针见血地指出，菲鲁特等人之间顿时绷紧了气氛。

其中脸颊绷得最紧的，当然是被点名的佩特拉本人。对她们而言，佩特拉的权能是王牌，是最高机密。

实际上，这一方针也确实已经在全员之间明确共享。

可就算再怎么铁石心肠，猝不及防的一刺也不可能毫无反应。

对阿尔德巴兰的追问，众人都竭力收拾表情与心绪，但只要视线或心神哪怕有一点点波动，他只需顺着那把矛头反复试探追索即可。结果，顺着那细微反应追到的尽头，赫然就是阿尔德巴兰想要的答案。——只是，答案竟会是吞下了魔女因子的佩特拉，这一点也确实让他大吃一惊。

「按我原先的设想，读了那个的佩特拉小姑娘或梅莉小姑娘，本来就不可能再回到战场上的。」

在普雷阿迪斯监视塔里将菜月・昴与碧翠丝封禁的阿尔德巴兰，击退加菲尔和艾莎之后，没有对佩特拉她们下手，而是选择放她们离开。

那不仅是因为没必要清除她们，更是为着后续而预先布下的一步棋。

要拖住莱因哈鲁特，非得让『嫉妒魔女』现身不可。

作为引发其现身的触发器——让人去阅读菜月・昴的『死者之书』的人选——阿尔德巴兰将目光投向了佩特拉她们。事实上，阿尔德巴兰与莱因哈鲁特的战斗因『嫉妒魔女』的闯入而被迫中断，计划中最大的障碍也由此被清除。

然而——

「……光是随便读谁的一册都可能把人读到精神崩溃，你居然还挺过了菜月・昴的『死者之书』？」

并非没有先例。——阿尔德巴兰对此的心里有数多得过头，可即便如此，他仍无法相信别人也能重复这一点，这便是『死亡』这一概念的绝对性。

在某些情况下，菜月・昴的『死者之书』甚至是足以用来击倒更强者的王牌级特级咒物。能不被那本书折断心志的人，绝不会多。

「……算了，小看别人是我这家伙的坏毛病。」

不管阿尔德巴兰怎么想，事实是，佩特拉此刻就站在这里。

她不仅没有被阅读『死者之书』的冲击击垮心志，甚至为了阻止阿尔德巴兰，不惜染指将魔女因子寄宿于身这般的暴举。或许，正是读过『死者之书』的经历，才把佩特拉逼到那般境地。

『——谁也赢不了我亲手造就的你哟』

在脑海中掠过的『魔女』的话语，是为了让阿尔德巴兰振作，绝不是让他自得忘形、反被绊倒的东西。

若是曲解了这句话，阿尔德巴兰这一次就会真的失去『魔女』。——那位沦为『强欲魔女』、将那确实存在过的心真正遗失了的『魔女』，这一次，的的确确。

「——归根结底，命运还是不能指望别人来替我决定。」

把心头涌起的感伤随一口深呼吸沉入胸腔深处，阿尔德巴兰抬眼向前。

敌强、障碍多、无同伴、无可夸耀——即便如此，仍决定前行。

刹那——，

「——哦哦哦哦！！」

——怒火熊熊的金虎之刚拳，悍然轰在阿尔德巴兰的脑袋上。

170

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生再不与喜庆之事沾边。

171

——总计六十一人。

这正是货真价实的——在与『暴食』罗伊・阿尔法德分出胜负之后，为了与阿尔的最终决战而重新编组的『阿尔德巴兰之刃』，亦即艾米莉娅阵营与菲鲁特阵营的总力。

在那场激战刚刚结束、连喘口气的工夫都没有就被再编成的队伍里，竟还能有这么多人留下，佩特拉不禁满怀感激与敬佩。可这绝不是在贬低那些没能跟上重整队伍的人。

「奥托和梅莉，不能再让他们胡来了。」

正如幻影・菜月昴所言，奥托和梅莉——两人都在与『暴食』的战斗中起到了决定性作用。然而，『记忆』被吞噬的奥托自不必说，为了阻止黑蛇而过度动用加护的梅莉也消耗严重，退出前线已是必然。

不止他们。罗伊在最后关头祭出的底牌，那让人反复咀嚼过往痛楚的『暴食』权能，也把不少人的精神磨到了极限。与肉体的伤不同，心灵的磨损就算有佩特拉的『压缩』也不可能轻易恢复。尽管如此，梅莉还是一直坚持要把恢复时间『压缩』后重返战线——

「就算透支寿命，昴也不会高兴的哦？」

在佩特拉的劝说下，梅莉虽然万分不情愿，真的是极不情愿，但还是接受了撤出前线。

老实说，梅莉一听把昴搬出来就答应的态度，让佩特拉那点少女心多少有些别扭，不过这是她自己用的手段，也就不再多说。

况且，她还肩负着警戒那条被『暴食』引来、战后便销声匿迹的黑蛇的职责。没法让她完全休养，实在过意不去。

『只能让能做的事交给能做的人来填补。话说回来，也有那种就算没了记忆也会冲进火线参战的危险家伙。』

「真厉害呢。就算没有记忆，奥托先生还是那个样子，不由得会这么想。」

『大概是天生的性子吧。说不定就是个风险成瘾者。』

这样的感慨，不论对方有没有记忆，要是当本人听见，多半会吐槽一句「能不能别说得那么难听啊！？」但就算被这么想，也无可奈何。

总之，『暴食』确实狠狠削弱了我方宝贵的战力，让这场高潮之战的手牌愈发捉襟见肘。加菲尔的归队固然可喜，但无法为艾米莉娅和雷姆倾尽全力，于佩特拉也好、于『昴』也罢，都是痛心之事。

然而，即便如此——

「——我们会赢的，昴。」

『啊啊，去争取胜利吧。不能让一路累积到现在的一切白费。』

172

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生再也不与任何人谈论梦想。

173

「——归根结底，命运这种东西还是不能托付给别人。」

话里带着敷衍，语气却埋着觉悟。阿尔这句话，成了号令。

「——哦哦哦哦！！」

以怒吼的加菲尔为先锋，『阿尔德巴兰之刃』骤然发动。

目送着他们的动向，佩特拉在胸前紧紧握住双手。

——以艾米莉娅打入的冰之锚为标记，佩特拉带着『阿尔德巴兰之刃』将与现场的距离『压缩』，再次挡在阿尔面前。

说实话，现场没有艾米莉娅和雷姆的身影，被意外带走的阿尔的随从——那名女忍——也不见踪影，这终究是个令人不安的因素，然而——

『——阿尔那边没有解除不杀约束的理由。』

把这当作安心的凭据，也多少是对对方的能力与信条寄予了过多期待。

不过，想想拥有『时光倒流』权能的阿尔至今为止的战法，这便是依据。

也正因那权能过于强大，在某种意义上，阿尔到现在为止都还能摆出那种戏耍般的打法。

而这个前提，即便眼下已经将同伴从他身边强行剥离，究其根本也没有改变。

「咯噶——！」

正面，毫无预兆猛冲上来的加菲尔发出一声痛哼。

原因是他的突进轨迹与凭空落下的石板迎面相撞。被看穿先手的埋伏石板正中脸面，加菲尔整个人在半空中翻转。阿尔从那翻飞的加菲尔正下方掠过，转而迎击紧随金虎之后的战力。

随后而至的是拉姆，以及菲菈姆和格拉西丝——合计三人。

『巧了，竟是粉发姐妹组！来吧，会怎么样！？』

174

——三十七。

用石板迎击抢先出手的加菲尔，趁他向后空翻之际，从他身下穿过。

时机出奇地苛刻。石板插入得太早会被一扫而空，太晚则会让加菲尔直接穿过去。必须把握打中面门的那一瞬——用身体去记住，并将之付诸实践。

「咯噶！」

后脑勺传来痛哼声的同时，阿尔德巴兰抬眼向前，三路身影已从不同方向扑来。

左右两侧是菲菈姆与她的孪生姐妹，略高的斜上方则是拉姆——彼此呼吸一致的连携。

双子特有的精密配合，再加上拉姆初见便能无缝接入的反常，凑出一套令人咋舌的团队攻势。

这时——

「雷姆小姑娘，在后面的悬崖下已经被拍成薄饼了哦。」

「还差得远呢。别小看拉姆和雷姆的姐妹之爱。」

言语的毒被姐妹间的共感应所中和，毫不起效。

既然毫无动摇，便证明拉姆的话不假。顺势拾起其中所指——雷姆平安无事，而雅耶的安危不明——反倒是毒在这边起了作用。

然而——

——地土工艺

借由与『龙』的通路回流的玛娜，在阿尔德巴兰周围竖起石之刀剑成阵。为避开接连自大地弹出的剑尖与枪穗，双子大幅度地闪身回避，短促的一瞬迟滞由此而生，三者的配合转为拉姆的单独攻势。

趁势朝那独自一人的拉姆，将顺流拾起的石龙刀正面砸下——

「不错呢。借来用用。」

拉姆以风之魔法将刀剑托起，挥剑掠过之际，他的下颌便从侧面被狠狠打穿。

×××

——九十一。

「不错呢。借来——还是算了。」

话音一落，拉姆以风牵引来的石剑擦身而过，那柄从她身侧掠出的石剑脆生生崩解。她失手没能拾起武器，阿尔德巴兰的一击便仿佛被吸引般直取她身前。

拉姆以缠绕着风的杖将其格住，巧妙操纵气流，身在空中却硬生生借风取势，企图在刀剑相抵的角力中压倒对手。他以岩制的义腕攫住她的足踝，顶着风之刃的反击，将她朝身后抛掷出去。

「——」

背后传来拉姆咬牙的声响，阿尔德巴兰更进一步猛冲。先前的搅乱让那对似乎名为菲菈姆与格拉西丝的姐妹稍稍落后，此刻却一齐扑了上来。

那份绝不能因年幼而掉以轻心的敏捷逼近之际，阿尔德巴兰张开自己的右臂与义肢的左臂，掀起横扫一百八十度视野的沙涛。

翻涌的漫天黄沙将少女们吞没，化作把她们按进大地的牢笼——

「——阴之六，战士！风之五，魔法使！花之八，王！」

他被骤然涌起的重压正面砸中，仰面坠入自己造出的刀剑之海。

×××

——一百一十二。

「——阴之六，战士！风之五，魔法使！花之八，王！」

声入耳的瞬间，他强行合拢张开的双臂，将沙浪的喷口锁定在正前方——恰在眨眼之后现身的大胡子壮汉被沙涛尽数吞没，陷入与菲菈姆和格拉西丝相同的境地。

就此避过险境，阿尔德巴兰斜向跃出，打算越过敌阵——

「乌尔・戈亚！！」

仍在半空的姿势，他挨了一个无可躲避的炎之刚球，五脏六腑燃烧起来。

×××

——一百四十六。

「乌尔・戈亚！！」

用砂子压制住双子和大个子，面对逼近的火球，他反而刻意慢了一拍。替他正面挨了这一击的，是阿尔德巴兰匆忙捏出的粗陋土偶——艾米莉娅曾用冰再现菜月・昴的那种魔法的劣化版。

那枚为按住猛然窜出的阿尔德巴兰脑袋而射出的火球，在这须臾决断的战斗里，竟被那不成样的土偶成功诱开。

「啥！？」

施术者是个眼神凶狠、打着舌钉的瘦削男人，他对阿尔德巴兰的应对倒吸一口气。除非是熟练的魔法使，否则乌尔级的魔法可不是想放就能连发的。阿尔德巴兰冲他竖起了那具假人的中指，这回总算可以更进一步——

——给我崩裂！！

斜后方，自那一带发射的光之冲击波正面轰在阿尔德巴兰的背上。仿佛能把世界都烧穿般的白光，将他的意识都涂抹成一片空白。

×××

——一百四十七。

——给我崩裂！！

听见那声英武的嘶吼，他循声回首，阿尔德巴兰看见行凶者是露出虎牙、面容英挺的菲鲁特，而光的源头则在她握着的魔杖上。

那是生前的『魔女』夸口说过连『神龙』都曾被打哭过的『星杖』——名为『流星』。归根结底，是师父留下的烂摊子。

「这节骨眼上被老师搅局，简直离谱得像个 BUG。」

前路漫漫、挑战无休无止，而那道必须翻越的高墙，竟是出自为阿尔德巴兰指明道路的那位『魔女』之手，这个事实令他心头涌起一抹忧郁。

阿尔德巴兰随即被白光毫不留情地吞没。

那么——

×××

——一百四十八。

「——给我冲破！！」

——这道步步逼近的白光，到底该怎么攻略才好。

175

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不送礼。

×××

「——『忧郁』的权能，究竟能做到什么？」

176

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生再也不向任何人挥手。

×××

「——靠单纯的传送根本解释不了。权能，绝不该只是那种玩意。」

177

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生睡前绝不祈祷。

×××

「——它应当是在体现某种概念，对吧？『忧郁』，是『忧郁』吗。」

178

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不贴近任何人的伤痛。

×××

「——情绪下沉、低迷、阴天、消沉、凹陷。……凹陷？」

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不因晴空而欢喜。

×××

「——你是在压缩空间和距离吗？不，被你压缩的可不止这些吧？」

179

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不为雨空而哀叹。

×××

「——把不够用的思考时间也压缩着补上吗？不过，所谓魔女因子可……」

180

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不与任何人一同仰望彩虹。

181

「——魔女因子，可不是那么合你心意的东西吧？」

刹那，阿尔突破了『阿尔德巴兰之刃』的包围网，直逼到她的正面。听到他的话，佩特拉只觉一股寒意沿着脊背直窜而上。

铁盔遮住了阿尔的双眼——然而，她却分明感到彼此的视线对上了。那种仿佛心底被看穿的实感，让佩特拉的心头升起焦躁。

不知为何，阿尔对魔女因子的精通，竟在佩特拉之上。

「佩特拉！！」

「——花之八，魔女！！」

「——」

在逼迫得近乎嘶哑的指令与内心所系之人的呼喊叠作一团之际，佩特拉将心头滋生的犹豫『压缩』，为了不被阿尔伸来的手臂捉住，从那只手下钻开，与对手拉开距离——连这一整段过程也一并『压缩』，一口气甩开。

「喂喂，连自己的空档都能抹掉吗……！」

眼前的佩特拉骤然消失，扑了个空的阿尔啧了一声，回头望去。

阿尔的肩膀剧烈起伏，他与佩特拉之间的距离又得重新来过。对峙的两人之间，站着那些他拼命才冲破的『阿尔德巴兰之刃』的同伴们。想再一次抵达佩特拉身边，就得再越过同样的关卡。

然而，佩特拉却丝毫没有得计的快意。

『佩特拉，刚才阿尔的话……』

「我明白。……真的，重来了。」

对身畔浮现的幻影菜月昴的这句话，佩特拉眯起眼，轻轻点头。

并非到了这一步还在心存怀疑，然而当真正亲眼见识到阿尔的『时光倒流』时，仍不免为那份离谱到出格的力量而震惊。

无论是加菲尔的先手攻势，还是 拉姆 与 菲菈姆 & 格拉西丝 的联手攻击，亦或是加斯顿、拉珍斯、菲鲁特借『压缩』从三面发起的围堵，再加上遵照罗姆爷指示行动的五十名妨碍者——阿尔全都应对得完美无缺。

而且对这一切，他每一次都像抓住了唯一的最优解般破局。

『我这边把思考『压缩』起来，也能勉强得出类似的结果就是了……』

「那只是一直拼命思考，直到得出『这就是正确答案』而已。和昴你、还有阿尔先生的力量，果然还是有点不一样呢」

『……按理说，我也应该这么强才对啊』

挠着头的『昴』沮丧地垂下肩膀，自觉不争气。可佩特拉并不这么想。

昴就是昴，他直面自己的权能，把本该失去的许多都留了下来，一次次救下了佩特拉他们。他身上没有半点『不争气』。

这样想着的同时——

「……为了把手伸向我，你重来过多少次？」

以佩特拉所知，阿尔作为战士的实力不过中等——更别提远远不如拉姆与加菲尔，恐怕也敌不过亨克尔。即便如此，阿尔却仅凭一人就戏耍了『阿尔德巴兰之刃』，差点把他们逼入绝境。

『别说十次了，说不定已经重复了二十次。』

「……也许更多。」

对『昴』那有些天真的估计，佩特拉反而预想到可能性会高出十倍、二十倍。

事实上，若是换作佩特拉去算计『阿尔德巴兰之刃』，就算拥有知晓后续发展的权能，她也没有把握在区区一百次的尝试内通关。更何况，阿尔即便借用了『龙』的力量，也曾留下连莱因哈鲁特都被他躲开的战绩。

为了成就那样的事情，人究竟得把心杀到什么地步，才能不断地发起挑战呢。

若真如佩特拉等人所想，阿尔的『时光倒流』与菜月・昴一样，是以『死』为代价的力量，那么站在那里的，便是披着轻佻外皮的可怖『魔人』。

阿尔早已将『死』的恐惧与丧失感——不，不可能有人能真正克服那种东西。与其说是克服，不如说是麻痹。

连『畏惧死亡、不愿让它靠近』的生命本能都被麻痹了的存在——那，正是阿尔之所以强大的秘密，也构成他作为『魔人』的绝对性。

想要超越那份绝对性，我们这边也必须付出相称的代价。

『——佩特拉』

「没事的，昴。……我真的，没事。」

那是个盘踞在脑海里的存在。

唯有幻影的菜月・昴，识破了佩特拉的秘密——那件她既未告诉『阿尔德巴兰之刃』的任何人，也未对艾米莉娅阵营的任何人吐露的事。

那正是眼前这位精通魔女因子的『魔人』也说过的话。

——对自称为『忧郁魔女』的存在，顺遂的命运不会报以微笑。

「即便如此，这种事，也不能成为让我停下的理由。」

就连欺骗自己也在所不惜，佩特拉・雷蒂——『忧郁魔女』行使了权能。

以干涉世界之理为代价，她的未来正从名为『自己』的存在中被一点点剥夺。即便那是多么重要、无可替代，这位新生的『魔女』也没有半分犹豫。

182

——七千十一。

「即便如此，这种事，也不能成为让我停下的理由。」

看见站在远处的佩特拉吐露此言，阿尔德巴兰心下不禁生出脱帽致意之感。虽未真的摘下头盔，但心情已到了想这么做的地步。

毕竟，不是吗。

「……真是无法原谅啊，菜月・昴这家伙。」

咬着牙的阿尔德巴兰，环视一路拼凑至此的混成军——似乎给自己起了个名号，叫作『阿尔德巴兰之刃』。这品味他倒颇为中意，至于这名字的来历嘛，他不太想多想。

不管怎样，借由至此与『阿尔德巴兰之刃』的攻防，已经将佩特拉吞纳的『忧郁』魔女因子及其权能的多半机制摸得一清二楚了。

任何战斗皆然，关键在于尽可能多且准确地掌握对手的情报。与大罪司教或『魔女』的交锋尤为如此，若不先弄清对方持有的权能为何就贸然对上，往往只会被单方面斩杀。——能挺过这类初见即死的陷阱，正是阿尔德巴兰与菜月・昴的强项。

这一强项发挥得淋漓尽致后，阿尔德巴兰所把握到的『忧郁』权能，却称得上荒唐至极。将空间与时间碾碎——『压缩』的力量，无论在应用广度还是在棘手程度上，都几乎无人能及。

更有甚者，这项权能似乎连思考也能『压缩』，以至于哪怕只有一秒的攻防，经过深思熟虑、打磨至锋的结论也会接二连三地袭来。对阿尔德巴兰的『领域』而言，那同样是难以轻易解开的难题。

事实上，光是穿过短短十一秒的攻防，就足足需要重试七千次。

而且，折腾到这份上，关键的佩特拉却还是给跑了。——既然被拉开了同样的距离，再想追上，恐怕需要拿出同等，甚至更激烈的手段。

再怎么说，『忧郁』的权能跟巴尔加的相性也是差到极点……

『阿尔德巴兰之刃』的一员中，还有那个让人吃尽苦头的巴尔加・克罗姆威尔的身影。

那家伙明明有着得天独厚的魁梧身躯，却丝毫不去活用，纯靠智谋取胜。一旦被赋予不受限的自由思考时间，便会以逼近唯一解的最优抉择来压制阿尔德巴兰。

那无疑是如虎添翼般的梦魇组合。

若是在巴尔加的股掌之间起舞，他大概又会把阿尔德巴兰彻底封死。因此，就算不得不剥夺他的思考时间，也绝不能给他太多反复试错的机会。

更何况，一直让『忧郁』的权能运作下去，也并非阿尔德巴兰的本意。

因为——

——『忧郁』的魔女因子是个缺陷品。它是为勇者准备的独一份，除此之外与谁都不相容。换个说法，只要支付对价，也能与谁都达成适配；可人这种生物啊，一旦拿觉悟作筹码，实在能把太多东西切割出卖呢。

这是先前从『魔女』口中听来的，关于『忧郁』魔女因子的情报。

或许她另有所虑，那位『魔女』对那两种堪称番外的魔女因子并不愿多谈；可一旦被磨到让步，解释时却反倒滔滔不绝。

将那番冗长却不得要领的话概括起来，要点如下。

——『忧郁』的魔女因子会以持有者的意志为代价发动权能。

——使用『忧郁』的魔女因子所需的代价，除持有者本人外无人能够承担。

「——菜月・昴」

想到这里，阿尔德巴兰再次对菜月・昴涌起怒火。

当然，他并不认为佩特拉会吸收『忧郁』的魔女因子这件事，与自己让她去读『死者之书』的计划毫无关系。然而，若说契机是阿尔德巴兰造成的，责任的一大部分仍在菜月・昴身上。

念及阿尔德巴兰与菜月・昴之间的关系，这么说也并不为过。

笼罩佩特拉一生的巨大阴影，源自菜月・昴。并不是说他心怀恶意，阿尔也并不那么认为，可他的影响力不言而喻地巨大。那并不只局限于佩特拉，『阿尔德巴兰之刃』——不，在这场战斗之前的许多场合，它也都发挥过作用，简直可称之为某种命运之力。

――コ

即便如此，所谓命运之力，想来也是讽刺。偏偏菜月・昴与阿尔德巴兰，才是最痛恨命运的人——

――ン

而他们的行动，却几乎可以说是在决定命运本身。

――プ

正这么想着，阿尔德巴兰脑海中掠过的，是她那鲜红炽烈、鲜明至极的话语。那句——

――レ

在最后一刻她所吐露的赞誉，仿佛要将阿尔德巴兰的心灼烧。他强行撇开目光，堵上对此的耳朵。

――ス

如今才来反省自己的所作所为，早已过了那个时候。此刻支撑阿尔德巴兰的，不是已失去的她，而是与先生的誓约。

――ア

阿尔德巴兰为何而生、为何而被铸成阿尔德巴兰，这一切的集大成，正要接受检验。为此更没有停下脚步思量的余暇——等下，等下等下等下。

太久了吧？

明明只该借着一口气、一个深呼吸的空当，战斗便会再度开幕。

――ゴ

本该如此。对手不愿让这边换气，这边也不愿给对手太多时间。

――ニ

明明在这一点上双方早已有共识，为何阿尔德巴兰却还能如此从容地思考——

――ー

糟了。不对劲。怎么回事？她说了什么？阿尔看见远处佩特拉的嘴唇在动。把那双唇吐出的音节一一拾起。把塞进思绪缝隙里的那些东西捡起、拼在一起。慢。焦躁。慢得过头。捕捉含义，捕捉意义，捕捉意图。——。————。————。不行，没法让思考闭嘴。就边想也行。「コンプレス」？是压扁吗？压扁什么？「アゴニー」？疼痛？苦痛？苦恼……苦恼？烦恼、思索、抽丝剥茧。可恶，被算计了。被『压缩』了。

——我的思考，被『压缩』了！！

183

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不泄露重要的秘密。

184

「——『コンプレス・アゴニー』」 （译注：『压缩・痛楚』）

由『忧郁』的权能施加的思考『压缩』——一种能让同伴的思考加速、省去商量、以全员反复推演出的最优手迅速出招的强力增益，把它赋予阿尔，正是佩特拉为他准备的对策之一。

「要考虑的事情一多，脑袋就会爆掉的，对吧。」

也许有些自不量力，但如今的佩特拉自认在名为『死亡回归』的『时光倒流』上，自己仅次于昴与阿尔，是这个世界第三清楚的人。

凭借佩特拉的学识，加上昴对『死亡』痛楚的追体验，他们找到了让看似几乎无敌的阿尔之权能失效——不，令其过载的方法。

那就是以思考加速为刃，对精神施加过度负荷。

当年王选刚开启时，昴在王都与艾米莉娅不欢而散，因巨大的压力与精神负担而将心灵彻底磨损。

虽说后来在雷姆的奉献与对大罪司教的怒火中意外获得了振作的契机，但他确实一度丧失战意，成了空壳。——现在，就要再现那一幕。

如今，已对『死亡』的恐惧麻木的阿尔，也许无论堆叠多少次『死亡』，心志都不会被折断。

可就算他主动将全世界置于敌对一侧，阿尔终究还是个人类。

他的精神会出现裂隙，终将抵达极限，这是无法避免的。——要做的，就是诱发它。

为此，无论以自身的什么为代价——

「——领域展开，矩阵再定义。」

在思考加速的折磨之中，阿尔静静地吐出了这句话。

精神负荷虽高，但这种状态是一把双刃剑。阿尔在这一路上的剧烈消耗让他的心灵濒临极限，与此同时，他也有可能像『阿尔德巴兰之刃』那样，将那份思考的『压缩』发挥到极致，反过来迎击佩特拉他们——两种走势，不相上下。

因此，从这里开始的战斗，才是真正意义上对『阿尔德巴兰之刃』的考验——

「——大家！从现在起才是真正的开始！别松懈！」

「——哦！！」

在佩特拉的激励下，交流被『压缩』的伙伴们齐声应和。

佩特拉觉得这令人踏实，正要重整旗鼓，与阿尔的决战再开——却猛地察觉到不对。

刚才那些响亮回应的声音里，有一个没有传来。

或许只是错过了时机。然而那股诡异的违和感令佩特拉不由侧目，去寻找那位没有应声之人的身影。

然后，她找到了。

「——罗姆爷爷？」

那位没有回应的大参谋——肩负着俯瞰战场、适时而精准地下达指令之责的巨躯老人，正慢慢翻着白眼，向大地崩塌倒下。

185

——时间，仅仅回溯了一个刹那。

「——领域展开，矩阵再定义」

没错，听到阿尔德巴兰如此断言，罗姆爷那宽阔的肩膀为之一颤。

他眼睛陡然瞪大，望着正与混成军对峙、伫立不动的阿尔德巴兰的身影，心中生出不该有的动摇，整个人僵在原地。

佩特拉打算借用『忧郁』的权能之策，罗姆爷也已听闻。

那是一计要让阿尔德巴兰的思考加速，对他的精神施加负荷，一口气将之消耗殆尽。对此，罗姆爷也认为，要打倒那个会『时光倒流』的阿尔德巴兰，这是必要的步骤，于是答应协力。

虽对加速阿尔德巴兰的思考心存顾虑，但这边同样会将思考『压缩』至最善手，他也接受了这是一个要以综合实力步步逼杀的局面。正因有了这样的方针，罗姆爷觉得自己也能出上一臂之力，这一点分量不小。

而事实上，在与阿尔德巴兰的战斗中，罗姆爷的盘算确实奏效。

他迅速调动伙伴们，成功将阿尔德巴兰逼入绝境。——然而，让罗姆爷震骇并引发这份动摇的，却是从那之后开始的。

「——领域展开，矩阵再定义」

就这样，阿尔德巴兰话音刚落，罗姆爷的站位便在瞬间发生了变化。——不，变化的并非只有罗姆爷，包括阿尔德巴兰、菲鲁特在内，参加这场战斗的所有人都被拉回到短短十几秒前，重新来过。

而这样的循环，罗姆爷已经经历了整整五次——

「——这到底是什么状况。」

猛地转动脖颈，罗姆爷在那已看过五次的同一幕景象中，沉沉挤出这句话。

察觉到异样的，只有罗姆爷一人。

「——大家！从现在开始！别松懈！」

「——哦！！」

正是明证：在佩特拉英勇的号令下，除了罗姆爷之外的所有人都应声回应。

随即，他们一齐朝阿尔德巴兰扑去。

「罗姆爷！给个指示！」

手持『星杖』的菲鲁特并未察觉这边的动摇，正寻觅出手的位置。除她之外，其他拥有致胜绝技的伙伴们也奔走着，盼着罗姆爷下达指令。

望着他们的背影，罗姆爷咽下一口苦涩的唾沫，抛出了与刚才不同的命令——

「——领域展开，矩阵再定义。」

——与阿尔德巴兰的第六次最终决战，正式开始。

** 『领域之加害者』

——阿尔德巴兰的『领域』是与魔女因子有渊源的权能。

然而，阿尔德巴兰并非魔女因子的持有者。

『魔女』称其为番外或特例，但阿尔德巴兰觉得不该用那种好听的词，理应说成盗用或缺番。

作为现象并非没有先例。比如那群曾与魔女因子适配、获得权能的『大罪魔女』，即便死后只余灵魂，也依旧保有相同的力量。

对此，『魔女』推测，魔女因子是一把开启通往『获得干涉世界之权』之门的钥匙；而一旦门被打开，即使失去钥匙，它也会继续敞着。

如此一来，虽能解释『大罪魔女』，却仍无法解释阿尔德巴兰与『魔女』她自身；对此，她倾向于『继承说』。

与魔女因子适配之存在间非同寻常的牵连，或许使得他们自出生起，那扇名为『权能』的、通往干涉世界之权的门便已被开启。

不过——

「就像有翼之物很难向无翼者解释扇动翅膀的感觉一样，我们这种并非后天附加的权能也难以言明。大概就是生来那扇门就半掩着吧。」

会那样说的那位『魔女』之所以一脸得意，大概是她自以为抖了个使尽浑身解数的笑话吧。可惜，阿尔德巴兰一点也笑不出来，不过对内容本身倒是点头认可。

的确，如果那扇门能完全敞开，通风会好得多。可如今通风不畅，只能隔着半掩的门缝往里张望，把手伸进去试探。于是要么被门挡着，要么把手夹住，总免不了遭遇意料之外的状况。

也许学那位『魔女』那样，干脆不去开门才更果断。然而要做到那一点，阿尔德巴兰太过平凡，也太过无力。若是不去开门，阿尔德巴兰便没有履行『魔女』所期望之职责的胜算。

既然如此，哪怕只能半开，阿尔德巴兰也不可能选择不去开门。

于是，阿尔德巴兰的权能便像一扇半开的门，仍有诸多不透明之处。凭借使用时的体感与经验法则，再加上『魔女』的推测，所掌握的也不过全貌的八成左右。即便如此，行使这份权能并无障碍，阿尔德巴兰也从不迟疑去用。

这也许听起来有些危险，但就像不懂手机的原理也不至于用手机把命搭进去一样。尽管如此，阿尔德巴兰的权能与性命息息相关，终究和手机不是一回事。

总之，这份权能以体感时间把阿尔的人生拉长了十几倍，但『领域』里仍有许多黑箱——时不时冒出来的 BUG，就是最典型的一种。

所谓『领域』中的 BUG，是指在设定好的『矩阵』里，主导权的持有者并非阿尔德巴兰，而是转移到了同一矩阵中的其他对象。

通常，阿尔德巴兰会凭自己的意志构筑『领域』，并且只被允许在那被限定的时间与空间内进行无数次挑战。其间，记忆始终由阿尔德巴兰保持，每一次挑战都做出不同的验证，按部就班地去摸索突破口。

然而，一旦某个环节出错引发了 BUG，重置『领域』的权利就会移交给矩阵中的他者。对方将不得不在『领域』解除之前，没完没了地反复经历那道永无终结的矩阵。

阿尔德巴兰断定，这个从前在『魔女』麾下时从未显现的异常，是在首战败北、对自身权能的信赖受损之后才发作的。

事实上，每次出现异常，必定是在阿尔德巴兰怀疑自己权能的时候。早在剑奴孤岛，被迫与万无一胜算的强敌展开死斗之时便如此；此后，在与让阿尔德巴兰不知所措的莱普・跋利耶尔的冲突，以及与普莉希拉派来的刺客雅耶的交锋中，这个异常也都发生过。

更有甚者——

「——有趣。把权能的主导权交给对手，这种事闻所未闻。」

在梦之城向迎接阿尔德巴兰的『强欲魔女』发起挑战之时，那一幕发生了。

「相当稀有的体验。原来如此，那就是你所见的世界啊。的确，要是对正在发生的事一无所知，这现象足以让人发疯。」

他朝那早已面目全非的『强欲魔女』挥刀而上，要求她把自己所认识的『魔女』还回来。

他从各个角度发起攻势，当反复试探与巧思统统失效之时，阿尔德巴兰心中对权能滋生的疑念，仿佛为此作证般，异常随之出现。

「对权能之绝对性的疑念，由此生出的变化——那是从弱小衍生出的力量。遗憾的是，这种效果对沉溺于疯狂的存在无从奏效。她亦然，我亦然。」

强欲之魔女向困惑的阿尔德巴兰娓娓道来她所亲尝的地狱。

那确乎是阿尔德巴兰所知的『领域』之世界，同时又在决定性处迥然不同，让人不明白强欲之魔女究竟是如何熬过的。

正如她自己所言，是因不复清醒，方能承受吗？

「行使权能之时，多半你是弱者。为发掘那微乎其微的胜机，将之撬开，并最终将其抓住，你唯有依傍『领域』，可谓受害者。而若把把『领域』强加于你的对手称作加害者，那么这便是受害者与加害者之间主导权的置换。」

看着强欲之魔女兴高采烈地揭露地狱的真相，阿尔德巴兰只觉体内血液渐渐冰冷，也明白那正是由他自己造就的噩梦。

无论是将梦之城化为噩梦，还是『领域』中出现的 BUG，其因皆在阿尔德巴兰的软弱——名为『弱小』的、不可饶恕之罪所降下的惩罚。

「计划还在运转。第一目标是受挫了，但第二目标仍然健在。只是只能把所剩无几的最优……你也好、我也好，现在这样做就是为了它。对吧？」

那罪的十字架，沉重得让人几乎要以『一个人背不动』为由丢弃的十字架，『强欲魔女』却带着嗤笑，说要一起拖着走。

面对那既想见又不想见的微笑，阿尔德巴兰下定了决心。

「我一定——会亲手杀了你。」

——就连『领域』的漏洞，连由自身软弱衍生出的力量，甚至连阿尔德巴兰失败的烙印都要拿来利用，为了作为『尾随星』履行自己的职责。

「——爱，为何会减少呢？」

『强欲魔女』低声呢喃的这个问题，阿尔德巴兰并不知道答案。

他失去了渴求爱的『魔女』，也失去了所爱的「太阳公主」，直到现在，仍然不知道。

——也不想知道。

186

思绪在加速。

大概是佩特拉所拥有的权能所致，在被那权能挤压的思考里，阿尔德巴兰面对无止境涌出的杂乱念头无法排出优先级，头几乎要被撑爆。

「——可恶。」

可怕的权能。

与性能参差不齐的加护不同，大多数权能一经发动皆是非同寻常且超出常规的力量，佩特拉的『压缩』也不例外。权能多半取决于持有魔女因子者头脑的柔韧程度，而在这方面，她的应用性强得过分。

要么抱有异样强烈的执念，要么具备源于弱者的灵活性——能引出魔女因子强大力量的才能，与这类精神性有着极大的关联。大罪魔女与大罪司教属前者，阿尔德巴兰与佩特拉则可归于后者。

而且，无论是受加护者、魔女因子的适合者，抑或是无能力者，阿尔德巴兰觉得难缠的，向来都是后者那类人。

事实上，针对把『压缩』施加于思考的阿尔德巴兰所展开的攻势，正合对方之意，立竿见影。对想要避免精神消耗的阿尔德巴兰而言，那种不断削减余力的阴险劲儿可谓十足。

就阿尔德巴兰而言，若不计权能，他也属弱者之列。在每一瞬都需作出判断的战斗中，能够时时探求最善手的力量有多么有用，毋庸置疑。可战斗之中，本就不可能做到万无一失。因此，必须在某处做出决断，斩断思绪，付诸行动。佩特拉的『压缩』却会强行填满那些本应被舍弃的思考余白，使人就算得出同样的结论，也要付出成倍以上的消耗。

故而阿尔德巴兰以巨大的精神力浪费为代价，仍不断对士气正盛的『阿尔德巴兰之刃』采取最优举措，给出如将丝线穿过针眼般的极限答案。

而就在这番消耗之中——

「——罗姆爷！！」

刚从与『阿尔德巴兰之刃』的攻防中脱身之际，耳边传来的却是一声近乎悲鸣的呼喊。

喊出这声的菲鲁特瞪大了眼，望见远处那具年迈的巨躯轰然崩倒。刹那间，不仅是菲鲁特，『阿尔德巴兰之刃』的其他人也心神为之动摇。

不明所以之间，巴尔加・克罗姆威尔倒下了。

「――――」

当然，即便不知道是怎么做到的，能下手的候选也只有一个。于是，除却奔向倒下的巴尔加之人，其余所有的敌意尽数汇聚到阿尔德巴兰身上。在那些敌意的注视下，阿尔德巴兰在头盔深处——那是『阿尔德巴兰之刃』看不见的地方——双眼猛地睁圆，和『阿尔德巴兰之刃』一样满是惊愕。

「——成了『领域』的加害者了啊。」

并非蓄意为之。但他明白，因自己而起，究竟发生了什么。

『领域』的 BUG 发动了，让作为加害者之一的巴尔加握有了主导权。然后那位老巨人八成被迫将那短短的一瞬，重复到足以把心压垮的次数。

啧。

即便这是可称作起死回生、千载难逢的机会，阿尔德巴兰也并不欢迎。

如前所述，这个 BUG 的发生与阿尔德巴兰的意志无关——至少并非他主动触发。而阿尔德巴兰也无法为它的发动而高兴。

因为在大多数情况下，BUG 会摧毁被卷入者的心灵。

「不论是剑奴孤岛，还是莱普老爷子，亦或那家伙雅耶……」

凡是与阿尔德巴兰对峙、被『领域』的 BUG 吞没，进而陷入无法脱身的『死亡循环』的那些人，无不在精神上出现了异常。

心被摧毁的剑奴们被阿尔德巴兰斩首，失去神智的莱普・跋利耶尔忘却了多年的野心，屈服于恐惧的雅耶・天泽则化作忠实的仆从。

将人之心态扭曲的『领域』所出现的 BUG，对于在执行计划时给自己加上『不杀』条件的阿尔德巴兰而言，只会带来几乎等同于『死亡』的结局。

故而，阿尔德巴兰无法为这样的收场感到高兴。——当真如此吗？

『——谁也赢不了我亲手造就的你哟』

那位曾被自己背叛过的『魔女』的声音、期许与理想，清晰可闻。

因畏惧、警惕并厌恶对手的执念、他们的谋划与团结，以及那万分之一、亿分之一、兆分之一的可能，『领域』满足了 BUG 发生的条件。——换言之，那不过是因为阿尔德巴兰怀疑了权能，怀疑了自己，也怀疑了那位『魔女』。

『——谁也赢不了我亲手造就的你哟』

又一次，『魔女』的声音传来。——他看见下一个加害者翻着白眼倒地。

187

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不再贪恋宁静。

188

「——罗姆爷爷？」

局势动了。——而且，是朝着对佩特拉她们不利的方向。

罗姆爷猝然巨躯一晃，轰然倒地，佩特拉猛地瞪大了眼睛。胸中涌起的惊愕、茫然与不可理喻的困惑、动摇，以及无数情绪几乎要将她吞没，然而——

「——佩特拉！！」

「——！」

她几乎被卷走的意识，被幻影的菜月昴一声喝止生生拉回。对意料之外的事态感到震惊并无不妥。被从意识之外横空重击，能不动摇的人类不存在。可身为『忧郁魔女』的佩特拉，在惊愕之前更该做的，还有一件事。

那就是，将对既成事实的一切反应予以『压缩』。

「别开玩笑了，发生了什么！谁去把罗姆爷弄醒！」

「别胡说，他突然眼一翻就白了！怎么回事，谁对他做了什么！？」

「喂，怎么办！没有老爷子的话，谁来……」

「可恶！拉姆！只能靠拉姆了！」

「——真拿你们没办法。女王的棋子就不能用了。给我铭记于心。」

「不立刻行动，就跟等喂食的猪没两样。先下手为强。」

「可恶！都到这一步了，不能输！」

「当然！！」

霎时，她将扩散开的动摇尽数『压缩』，佩特拉履行起了『忧郁魔女』的职责。

原因尚未查明。然而，应对很快便敲定，全员同心协力开始摸索最优解——当然，佩特拉也不例外。

她将现场交给代替倒下的罗姆爷接过司令塔职责的拉姆，自己发动『忧郁』的权能，将与罗姆爷之间的移动距离『压缩』。

「罗姆爷……！」

伏倒在地的罗姆爷那具巨躯，靠佩特拉纤细的手臂根本扶不起来。然而她俯身探看那侧过脸的老巨人的面庞，喉头猛地一滞 —— 倒下的罗姆爷脸上毫无生气，仿佛一下子老去百年般，透出令人心惊的疲惫。

『本来也不是那种生命能量要炸裂似的面相……』

「刚才明明不是这样的，绝对。而且，如果觉得自己身体有异，罗姆爷一定会及时报告、联络、商量的。」

罗姆爷很清楚，轻率地隐瞒身体异状只会适得其反，反成利敌之举。

若是『忧郁』的权能施加了过度负荷，或者出现了会像这样昏厥的征兆，他绝对会主动申明。

『会不会是权能连发过头，把罗姆爷的寿命都耗尽了——这种让人笑不出来的可能？』

「这可一点都不好笑，否决……果然，我觉得那不是我的权能。是阿尔对罗姆爷做了什么。」

「可是，做了什么？」

陷入同样的死胡同，佩特拉和『昴』一起对答案一筹莫展。

与此同时，『阿尔德巴兰之刃』在拉姆的指挥下继续战斗，逼阿尔就范，佩特拉也不能把心思全都花在罗姆爷昏倒这件事上。

正这么想着，佩特拉试图起身——

「——笨蛋！那边优先！」

「——……」

就这样，被背对着她的菲鲁特当头纠正了优先顺序。

佩特拉瞪大了眼，握着『星杖』的菲鲁特咧出尖尖的虎牙，

「要是搞不定刚才那玩意儿，咱们全都得用同样的法子被放倒。」

菲鲁特懊恼地咬牙。正如她所说，原本包围并步步紧逼阿尔的『阿尔德巴兰之刃』人数正在减少。放眼望去，在激战中被落下的人有好几个倒在地上。

从菲鲁特的话来看，他们倒下的理由和罗姆爷一样——

「罗姆爷不可能白白挨这一招！找！一定有些什么！」

和菲鲁特来回耽搁了不过几秒，佩特拉便看向罗姆爷魁梧的身躯。

佩特拉觉得罗姆爷精明老练，也是能回应菲鲁特期待的人。所以，只要菲鲁特相信有什么，那就一定有什么。

『话虽这么说，要是突然被权能一把砸过来，哪还能留下什么啊……！』

「……你觉得，是权能吗？」

『不然就说不通！要是魔法，拉姆肯定会察觉的！』

「对吧」

菲鲁特的坚持×对拉姆洞察力的信赖。

这两相叠加，便印证了打倒罗姆爷所用的是阿尔的权能。而如果罗姆爷真的留下了什么——

「——！这个」

无力地横卧的罗姆爷，佩特拉把那具身体从头到脚检查了一遍，这才注意到老巨人的粗大手指沾了泥。那是刚沾上的污迹——用指尖在地上刮出的痕。

她用身体猛撞，挪动了因倒地冲击而错位的庞大身躯，趁着一个踉跄，佩特拉看见了罗姆爷临倒之际在地上留下的信息。

那是——

『记号？汉字……不，地图符号……』

「不是那个，更简单！」

看着同样的东西而陷入思索的『昴』，佩特拉尖声打断了他。

罗姆爷写在地上的记号——是一条粗横线上叠着四道短竖线。既不是汉字，也不是地图符号，而是每五划计作一组的『正字计数法』。

也就是说，罗姆爷是在意识被夺走的前一瞬——

「——在数着什么吗？」

189

——『领域』的漏洞，已经开始侵蚀阿尔德巴兰的计划。

「可恶……」

这份现实叫人恼恨，阿尔德巴兰咬紧牙关，从齿缝里挤出咒骂。

最先倒下的，是『阿尔德巴兰之刃』的参谋巴尔加・克罗姆威尔。即便失了司令塔，仍能立刻重整旗鼓，应该是佩特拉的权能在起效吧。可要说那份效能只是填补了空当，那么把情绪层面拉回来的，是他们各自的底气与实力。

每每切身感到他们一人一人心志之坚，阿尔德巴兰自身的软弱便越发显眼。

「可恶……」

念及自己的未熟之际，『阿尔德巴兰之刃』又有一人脱队。扛着大砍刀的阿珍膝头一软栽倒，喷出黄色的胃液，当场昏厥。

阿尔德巴兰这边没有反击。也根本反击不了。对手以最基本的战术，把基础素质强出一截的加菲尔顶在最前，连反击都无从展开。可即便如此，对方战力却在稳步被削减，那是阿尔德巴兰未曾意图的『漏洞』所致。

『——谁也赢不了我亲手造就的你哟』

他又听见了『魔女』的声音。

紧接着，下一个 BUG 发作，又有新的离脱者出现。

那对阿尔德巴兰而言，是煎熬。是痛苦。难以忍受。——『领域』的 BUG 带来的精神磨耗，有时会招致比肉体的『死』更为骇人的结局。这一点，阿尔德巴兰自从在剑奴孤岛醒来后的日子里，已深刻地明白。

所以，阿尔德巴兰不愿让『领域』的 BUG 主导一个他并不情愿的收场——

「——你这家伙，凭什么把一切都怪到别人头上？…」

「——啊？…」

「不用看你那张脸也知道。像莱因哈鲁特那样，把什么都算在自己头上、摆出那副『都是我的责任』的德行也够让人火大了……可你这，比那家伙还要过分。…」

在『阿尔德巴兰之刃』结成的人墙后方，菲鲁特正从人影缝隙间瞪着正撬开突破口的阿尔德巴兰。她那锐利的红瞳里，燃着对阿尔德巴兰毫不掩饰的尖刻轻蔑与怒火。

那是她在被人掳走之时，乃至在他命令罗伊去吞噬『记忆』之时都未曾表现出的炽烈。阿尔德巴兰不明白，直到现在，究竟是什么真正触犯了她的逆鳞。

既不是如家人般的巨人倒下，也不是她一路走来的轨迹险些被夺走，菲鲁特此刻对阿尔德巴兰怀抱的怒火，其源头是——

「那时候有那位公主在，你就听公主的摆布；人一不在了，这回又要听别人的号令吗？口口声声放话要把全世界都当敌人，结果你这家伙压根儿就没有自己的主见吗？」

——

面对菲鲁特那张写满了『火大』的脸和她的这番话，阿尔德巴兰微微绷紧了面颊，随即被这不知轻重的小丫头的妄言激起了怒意。

说什么没有自我，这种放肆也要有个限度。说阿尔德巴兰没有自我——连他为什么只能自称『阿尔德巴兰』的理由都不知道，就敢说出口。

愤懑像火一样灼烧五脏，甚至让那条从上臂往下已不存在的手臂都泛起了久违的痛感。

这种无用的激情就该被丢弃。这本该是他的拿手好戏。把它一刀两断，冷笑一声，将其当成碍事的东西加以嘲弄，然后抛之脑后。

一旦被这类感情缠住脚，迷失了目标，那就本末倒置了。避而不见真正鲜活的情感，这正是阿尔德巴兰的特长——不，确切地说，是自那枚黑球释放出来后的十八年里，他所学会的一种处世之术。

所以这一次，也照旧——

「菲鲁特大人说得没错啊！」

「为你干下的事付出代价吧！」

「去死吧，蠢货！」

「已经没人站在你那边了！」

「阿尔大人，做好觉悟吧。」

「审判之时。」

「像猪一样叫唤吧。」

「——真是个笨蛋。」

「——！」

如怒涛般朝阿尔德巴兰砸来的污言秽语、轻蔑的风暴。正想照例当做耳旁风——思考却被『压缩』，被强行逼着去处理。被压缩得以远非常态的速度运转的思考回路，将多余的念头、情感，统统剔除。

『——谁也赢不了我亲手造就的你哟』『——谁也赢不了我亲手造就的你哟』『——谁也赢不了我亲手造就的你哟』『——谁也赢不了我亲手造就的你哟』『——谁也赢不了我亲手造就的你哟』『——谁也赢不了我亲手造就的你哟』『——谁也赢不了我亲手造就的你哟』『——谁也赢不了我亲手造就的你哟』『——谁也赢不了我亲手造就的你哟』『——谁也赢不了我亲手造就的你哟』『——谁也赢不了我亲手造就的你哟』

不能再这样下去——阿尔德巴兰内心那股逼迫感正被一道声音一点点涂抹殆尽。他厌恶将自己交给它，于是去寻找位于事态根源的少女。

迫使阿尔德巴兰对万象穷思不已的『忧郁魔女』——

「——是在数什么吗？」

阿尔德巴兰远远看见『忧郁魔女』——佩特拉・雷蒂——望着倒下的巴尔加・克罗姆威尔所留下的某种讯息，低声喃喃。

刹那间，阿尔德巴兰心底涌出一股黏稠、漆黑、炽热的冲动，化作言语。

「——都是星星的错啊」

「哈，没错。别再对任何人言听计从——那才是你的本心。」

阿尔德巴兰那被激情磨得嘶哑的话音甫一出口，菲鲁特便咧牙一笑。

明明那笑容与她全然、不曾、有一丝一毫一片一毫米相像，却偏偏与普莉希拉・跋利耶尔所浮现的笑意同质。

噩梦。——我要终结它。

于是，阿尔德巴兰生平首次主动引发了『领域』的漏洞。

「——领域展开，矩阵再定义」

190

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不奢求任何人的善意。

191

「——领域展开，矩阵再定义」

听见阿尔这么说的声音里传来确切的变化，佩特拉回过头去。

那声口号在这场战斗里已经听过好几次了，恐怕是阿尔发动权能的某种触发条件。正如罗姆爷事先的推测，关于什么领域、矩阵之类，阿尔能够施展的『时光倒流』虽受限制，却是极其强力的能力。

回溯的跨度比菜月・昴的『死亡回归』更短，而且是当事人自觉可控的。

『如果棒球游戏可以手动存档的话，比如在打击时把每一球都存档再读档，把下一球的球种和投球位置记住，就能接连不断地轰出本垒打吧』

「我懂，但还是不好懂。真的会那样做吗？」

『要把游戏这种概念解释给只知道皮毛的孩子，确实很难……』

因读过菜月・昴的『死者之书』，自觉比只知其表更了解一些，但作为缺乏实感的『记忆』，幻影菜月昴的说法并没有错。

虽说偷看过昴的『记忆』，可佩特拉的感性终究还是佩特拉的。固然，像他对艾米莉娅和雷姆的态度那样，关键在于那些情感在昴心中占据多大的分量。

总之——

『——眼睛可不能离开』

「我知道」

随着声音与气氛的变化，与阿尔的战斗恐怕又迈入了下一个阶段。

与此同时，虽然也在以与罗姆爷相同的手法不断被削去战力，但以拉姆、加菲尔、菲鲁特为核心的『阿尔德巴兰之刃』主力仍奇迹般地健在。

被『压缩』的思考与协同无疑化作了巨大的力量，而佩特拉也不顾诸多弊端，将『忧郁』的权能用到极致，总算见到了成效。

「上啊，你们！！」

「——哦！！」

似乎顺着佩特拉的气势，菲鲁特的鼓舞让士气轰然爆发。

『阿尔德巴兰之刃』层层叠加的压迫，的确在削去阿尔的余力、磨损他的精神，把他的身心逼到濒于致命的消耗。

接下来便是比谁的气力先告枯竭、谁先无法再站立的较量——是的，就在佩特拉咬紧牙关，鼓舞起身心之时。

「诶？」

不由自主地，原本紧闭的嘴巴一下张开，佩特拉怔住了。

这也不奇怪。毕竟，就在刚刚。『阿尔德巴兰之刃』才刚打起精神，士气如虹，意气风发地要对阿尔发起总攻——结果『阿尔德巴兰之刃』的众人却忽然像被推倒的棋子般连环倾覆，毫无还手之力地当场崩落。

——

拉姆也好，加菲尔也好。菲鲁特、菲菈姆和格拉西丝，拉珍斯、加斯顿、汉巴里、多尔泰罗……不止是这些主力，『阿尔德巴兰之刃』的其他成员也无一例外，全都力竭倒地，谁也站不住。有人当场昏厥，有人因剧烈消耗而双眼失焦，有人则如人偶般僵直，动弹不得。

所有人，所有人都是如此。——不，还有一个人站着。

「——星啊。」

跨过倒伏成圈的『阿尔德巴兰之刃』，那人一边前行，一边用指尖摆弄着自己头上黑色铁盔的金具，低声如此说道。

听见这话，佩特拉只觉脑海有一角像被麻痹了一般，怎么也转不动。不能停下思考才行。『压缩』纵能填上事件与事件之间的缝隙，也填不满空白。

「——都是星星的错啊」

一边说着，走近过来的阿尔把手从头盔上移开，朝呆立不动的佩特拉伸去。

得马上应对、应付、想对策——

「——佩特拉！笔直向后『压缩』！」

「——！」

在那仿若怒吼的呼喝下，佩特拉反射性照办，『压缩』空间，猛地向后飞退。比起仓皇后撤，她拉开了远得多的距离，膝盖发颤，隔着岩场望向阿尔。

在那目光中，阿尔一边开合着方才没能抓住佩特拉的手，长长叹息。随后在与佩特拉拉开距离的状态下，彼此直直对峙——

「——Playball。」

×××

「——领域展开，矩阵再定义。」

就在她以为阿尔喊出了比赛开始的口号的瞬间。

紧接着，仿佛叠在那句话上，又有另一个阿尔的发声追随而至。那种宛如同一个人同时发声的现象，让正试图把握局势的佩特拉脑中一瞬当机。

然而，她立刻意识到这种停滞会致命，赶忙打起精神——

「干了啊，你们这帮家伙！！」

「——哦！！」

「诶！？」

随即，震撼空间的豪迈呐喊与应声炸响，把她惊得目瞪口呆。

那里展开的，竟是明明方才还在瞬间陷入毁灭状态的『阿尔德巴兰之刃』，却依旧完好的身影。以拉姆为司令塔、加菲尔为先锋，手持『星杖』的菲鲁特担任终结手的布阵下，他们正要与阿尔正面碰撞。

然而——

「喂、喂喂喂、喂，这到底是……」惊愕间，漂浮在身旁的幻影・菜月昴吐露出困惑。即便明白那份困惑与自己所感无二，佩特拉的心也未有片刻安宁。

只是，在巨大的动摇下，还来不及吐出挽留的话，局势便先一步动了。

「——呃」

那正是方才情景的重演。

『阿尔德巴兰之刃』众人齐齐崩落，那般可靠的集体轰然瓦解。强悍、勇武的拉姆与加菲尔，连菲鲁特也接连倒地之中，佩特拉再一次与唯独仍然屹立的阿尔对上了视线。

「——星啊。」

「————」

「——都是星星的错啊」

同样的宣告，后续的动作也一模一样。佩特拉并非被催促，而是顺从内心的情动，借由『压缩』向后跃去。

再次拉开距离后与阿尔怒目相对，她听见他叹息的声音。

那是——

「——Playball。」

——那是佩特拉・雷蒂无尽地狱的开端。

** 『佩特拉・雷蒂』

——佩特拉・雷蒂是露格尼卡王国下辖的一个村落——阿拉姆村出身的乡下姑娘。

她生得容貌出众，又天性灵巧，但除此之外并无可称道之处，本来也不该有机会卷入会被载入史册的大事，恐怕会就那样怀着去城市的梦想，作为一介村民结束一生吧。

因此，如今这位偏离『本来』轨道、屡次卷入足以名留青史的巨变的佩特拉，她的样子，是被某种干涉扭曲出来的。

而命运遭到扭曲这件事，佩特拉本人也心知肚明。

『本来』的佩特拉，是个仗着自己可爱，误以为能把身边的大人小孩都玩弄于股掌之间的、让人头疼的丫头。想必在『本来』的轨道上，那样的误解也不会被纠正，她会一直自以为是地把自己当作狭小世界的统治者，任性地过日子吧。

倒也不觉得那是糟糕的人生。那样也自有那样的快乐与幸福。

只是，以如今这个偏离『本来』的佩特拉的价值观来看，已无法将那当作幸福。

「因为在那里，现在的我喜欢的人，一个也不在吧？」

昴不在。法兰黛莉卡不在。艾米莉娅不在。碧翠丝不在。梅莉不在。拉姆不在。雷姆不在。琉兹不在。安妮罗洁不在。加菲尔不在。奥托不在。柯林特不在。罗兹瓦尔嘛，姑且先放一放。——可是，大家都不在。

「那样的世界，光是想想就不寒而栗。」

如果没能与我最喜欢的那些人相遇的，才是『本来』的我，而如今在这里的这个我，是某种命运碰撞后的结果，那么，能偏离出来，真是太好了。

走上了并非『本来』的那条路之后，我接二连三地遭遇了痛苦也好、疼痛也好、悲伤也好、煎熬也好，陷入过要命的境地，也经历过觉得死了反而更轻松的时刻。

但是，比那些艰难更重要的，是有些东西被我获得了，被我抓住了。

所以，佩特拉・雷蒂由衷地这样想。

「就算人生能重来无数次，我也会再次偏离『本来』。」

然后，无论多少次都要与你相遇，如此传达。

因为那个知晓与你相同痛苦的人，会带着痛楚与煎熬，向星辰许下心愿。

佩特拉・雷蒂——，

192

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不再送别任何人的远行。

193

「——」

狠狠吐出一口气，猛地一蹬坚硬的岩地，拼命地奔跑起来……

调整动作，前倾姿势，一个连自己都要迷上的理想起跑，然后以此生最快的速度跑啊、跑啊、跑啊、一直跑。

咚咚——体内涌动的血声吵得人心烦意乱，心脏像要爆裂般从胸腔里内侧猛捶，把自己粗重的呼吸都甩在身后，我只管奔跑。

可即便这样拼命地跑——

「——Playball」

那句冰冷的宣告传到背后的瞬间，视野倏然一变。

回过神来，那双以生平最快速度奔跑的脚已然停下，佩特拉呆立在岩地上。眼前，是本该背对而去的那幅熟悉景象，其中，戴着阿尔的男人低声呢喃：

「——领域展开，矩阵再定义」

那是那个以漆黑头盔遮面的男人动用权能，开始某种企图的信号。

这一刻由他的宣告拉开序幕，而在我所见的视野里，不知他在谋划什么的同伴们猛然发声，震得大气轰鸣。

「上啊，你们这群家伙！！」

「——哦哦！！」

以那位英勇少女的口号为中心，整队的士气攀至顶点，轰然炸裂。借着这股气势，她们一齐扑向阿尔。——可是，不行。

结果已然明了。她们伸出的手，无论如何也触不到对方。

——

如同断了线似的，三十七人纷纷在原地崩然倒下。

乍看像是同时倒下。然而，实际上其中也存在微妙的先后，这一点，早在逐一细察每个人倒下的样子时就已经知晓。只不过，从第一个倒下到最后第三十七个倒下，前后也不过不足两秒的差距。

在那区区几秒里根本无从插手，那番挑战也就徒劳收场。

『也不算是白费。明白这条方法不行，本身就不是白费。』

正当这样干涩的感想在鼓膜边回响时，一个声音——不，不是鼓膜。因为这声音并非通过震动空气传到耳中的那种，所以被震动的并不是鼓膜。

既然不是鼓膜在颤，那究竟，是哪里在颤动呢。

『还用说吗，是心啊。』

心。——对，没错。正是如此。因为心在颤，所以听得见。

心里仍旧保有可以颤动的余地。仿佛作为那份证明，他就在那儿。

那个，他的名字——

「——昴」

『啊，我在这儿，佩特拉。』

听见他的唇唤出『佩特拉』这个名字，心里这才松了口气。

没错。我是佩特拉・雷蒂，到现在还没有把它放手，仍旧紧紧抓着不放。

既然如此，所以，如果是那样，那么，既然如此，正因如此。

「——Playball」

——佩特拉・雷蒂仍不得不继续这场地狱巡行。

194

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不再接受任何人的施舍。

195

「——领域展开，矩阵再定义」

「——Playball」

从那句宣言开始，以那句宣言结束的片刻。

被困在一个连一分钟都不到的循环里，佩特拉究竟度过了多少时间。

「……话说，连一秒都没过去来着」

对着自己的心声这么吐槽了一句，佩特拉「哈」地泄出一口嘶哑的气息。

她也觉得，那是极尽犬儒、自嘲、对世无望的喃喃。甚至连她自己都被吓了一跳，没想到自己竟能发出那样被漆黑情绪浸透的、浑浊的声音。

但这绝不是弄错了，更不是把谁的声音给听岔了。

因为在这里——

「只会有我、那些人、那个男人，还有昴的声音。」

佩特拉啪嗒一屁股坐倒在地，把抱在怀里的双膝紧紧拉近，额头抵在膝上，低声嘟囔。

眼前，三十七人的队伍正要朝那名孤身一人的戴头盔男人扑去，而他们连叫都来不及便被反杀的那一刻，又一次上演。

真是，哪里不对劲。为什么就是不肯明白呢。

「大家脑子都不好使吗？明知道会被打倒，为什么一点工夫都不做，就那么直挺挺地扑上去啊……」

瞧，又被收拾了。一个接一个，全都倒下去。

这已经是再熟悉不过的光景，比起早间电视节目里的英雄时间里那些被正义的伙伴打得落花流水的反派，这副丑态佩特拉看得还要多、更滑稽。

一次又一次，一次又一次，一次又一次又一次又一次又一次，又一次又一次又一次又一次又一次又一次又一次又一次又一次又一次又一次——

「——像傻子一样。」

明明其中也该有聪明人，为什么，为什么就一点巧思都没有。明明已经被打倒了那么多次，为什么就不试试别的办法呢。

佩特拉明白。那些人根本没有意识到，自己已经被杀了多少次。他们不知道这件事已经发生过多少回，也不明白接下来还会一而再、再而三地发生。

既然他们不知道前路，被明摆着的后续发展裹挟也无可奈何。这不过是迁怒，是不讲理，是荒诞。佩特拉知道。佩特拉都知道，可是——

「可就算这样，你们也都是大人了，想点办法啊……」

佩特拉把额头一次又一次地撞在抱紧的膝头上。

疼。不疼。疼。不疼。疼。不疼。疼。不疼。疼。疼。

「啊啊啊啊あ啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊——「——Playball」啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊」

×××

啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊「——领域展开，矩阵再定义」啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊」

在小循环的终点和起点，两边佩特拉都成功发出了声音。然后呢？

佩特拉忽然发出怪叫的离谱举动，让正要扑向那戴着阿尔的家伙的大家动作一变。她们看向这边，望见抓着脑袋歇斯底里乱喊的佩特拉，一个个脸色大变。

「喂，怎么了！？」

「佩特拉！怎、怎么回事，谁对你动了手！？」

「退后，佩特拉！你可是拉姆她们那边的要！」

呼喊声接连而至。因为担心发出怪叫、又被异变硬生生砸进身子的佩特拉，大家在那一瞬，用最真切的声音与言语，想要贴近她。

开心。谢谢。最喜欢大家。真的。真的。可是，我不要。

「……我全都知道哦？」

只要佩特拉像这样失了态，大家会对她说些什么，我全都知道。

只要佩特拉拼命把『小循环』解释清楚，大家就会一起为此绞尽脑汁的，佩特拉知道。

只要佩特拉提出用『压缩』让全员分头逃散的方案，他们也会愿意听的，佩特拉知道。

佩特拉知道。全都知道。佩特拉看过、听过、说过、教过、传达过、商量过、思考过、苦恼过、迎上去过、琢磨过、挑战过，扔下过，捡起过，又再丢掉过。

「说点不一样的话吧。给我看不一样的东西吧。请不一样吧。和刚才、和从前、和接下来、和这一次，做点不一样的事吧……！」

佩特拉把脸哭得一团糟，丑得一塌糊涂，声音也难听得破破裂裂，指甲都快掀起了还在抓挠地面，发出不成话的叫声。众人先是哑然失声，随即锁定了原因，把怒火的矛头对准那戴阿尔的男人，露出獠牙。

「佩特拉，站起来。拉姆会借你个肩膀。」

朝阿尔男扑去的人群中，有一人抽身而出，向佩特拉伸出手。

好温柔。明明是这种局面，明明声音和表情都很凌厉，可那只手却那么温柔。最喜欢了。

「不过呢」

「——Playball」

×××

「——领域展开，矩阵再定义」

好了，皱成一团的脸也好，掀起的指甲也好，破碎不堪的嗓音也好，全都恢复如初。

他们对佩特拉的担心也好，胸中涌起的义愤也好，对那位像妹妹一样的孩子的忧虑也好，全都重置。——重置之后，以一颗干干净净的心，再次尽情享受新的开始与终结。

「上啊，你们这群家伙！！」

「——哦！！」

大家真好啊。总能以焕然一新的心情，又那样痛快地喊出来。

佩特拉做不到。做不到啊。明明想要一起努力，也确确实实一起拼过不止一百次。可是什么都没变，大家总是先一步倒下，翻着白眼就睡过去，擅自这样，太不公平了吧。

「那我也，耍赖一下好了。」

噘起嘴，佩特拉轻轻地就说了这么一句。

正这么想的时候，大家不知不觉已经都睡过去了。佩特拉面前，踏着杂乱的靴音，一个摆弄着自己头盔扣件的男人正靠近过来。

「——」

男人慢慢地，将摆弄着那扣件的手伸向佩特拉。

佩特拉在想，那顶头盔他有没有好好保养啊？滴点油、拿布干擦擦，这些维护总得做吧。感觉他一直在打打杀杀，连洗个澡都没空，让那样一只手伸过来，总让人有点抗拒。不过，忍。咬牙忍着，等那只伸过来的手够到自己。一直盯着看会不会让你下不来手呢？那我把眼睛闭上，你趁这会儿把我抓住吧。好，一——、二——、三——……。

×××

「——领域展开，矩阵再定义」

果然啊。佩特拉早就知道了。就算抓住也没用。啊哈哈哈，去死吧。

196

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不谈及失败之事。

197

「——领域展开，矩阵再定义」

以此为信号启动的循环——在刚意识到自己被卷入其中时，佩特拉即便面对这等异状，也没有过分失态，仍旧保持了冷静。

当然也有动摇，但比起预想，已经轻了许多。

因为——

「佩特拉！我们陷入短时间的循环了！是阿尔的下一招！」

替佩特拉喊出这句话的，是与她共享那场她被卷入的循环、唯一能理解时间反复流动的存在——幻影的菜月・昴。

那位『昴』的存在，以及佩特拉在被吞没前一瞬看到的罗姆爷的留言——刻在地面上的、用于计数的刻痕——压住了她的动摇。

「罗姆爷也遭遇了和现在的我一样的事。」

那道一横配四竖的记号，是一种被称为『画线法』的计数方式，若用汉字来表示，则通常写作一个『正』字。

罗姆爷把它写在地上，借此将自己所处的状况传达给了佩特拉。

很难认为罗姆爷仅仅在刻下五道记号后就变成了那副模样，因此他想传达的并不是自己重复了多少次，而是『正在重复』这一事实——对陷入同样处境的佩特拉来说，这似乎是来得太迟的信息，但并非如此。

罗姆爷留下的讯息，给了佩特拉一个一目了然的警钟。

也就是说，罗姆爷想表达的是：

「要是一直这样重复下去，就会变成罗姆爷那样。」

倒下的罗姆爷身上并无外伤，并不是在反复的时间里累积的伤势作祟才变成那样。——不，从某种意义上说，那的确也是累积的结果。

也就是说，罗姆爷在一次次的时间循环中，精神被磨损殆尽了。

这正是佩特拉等人『阿尔德巴兰之刃』对阿尔施展过的战术本身，几乎可以说是以牙还牙般被原样奉还的局面。

倒也不认为阿尔是特意冲着报复去的，但无论如何，若在毫无心理准备的情况下被卷入这种局面，佩特拉也很可能会步上罗姆爷的后尘。

「不，不止罗姆爷。照那种感觉看，拉姆她们也是。」

「……是啊。阿尔先生也把同样的权能施加给了所有扑过来的人……可循环开始的那个时点，大家不都是还有意识的吗？」

「有。……虽然是在反复的状况里，但会不会连循环之外实时发生的事也会被反映进来？被打倒的家伙会一个个从循环里脱离？要是那样的话——」

「——就只剩下我了。」

和『昴』敲定的推测过于绝望，佩特拉不由得绷紧了面颊。

如果假设，当这一轮循环的锅甩到佩特拉头上时，『阿尔德巴兰之刃』的伙伴们注定倒下的命运无法改变的话——

「就算这一轮循环结束之后……」

『等、等、等等，别那么悲观。假设——就算是那样也好吧？我们还有『忧郁』的权能。用那个，把冷却时间给『压缩』之类的』

「……把昏迷的时间『压缩』，一下子把他们叫醒？」

『对！没干过，但要是能做到，不就很厉害吗？』

对『昴』啪地打了个响指冒出的这个主意，佩特拉微微屏住了呼吸。

说实话，那恐怕相当困难。利用权能，去『压缩』用来商量的时间，或者掌握新技术所需的时日并非不行，但需要相应的能量。

直白点说，把佩特拉的一天『压缩』，就得消耗一天分的能量。三天就是三天分，七天就是七天分。要是让磨损殆尽的心灵恢复需要一个月，甚至以年为单位，那『压缩』所需的能量根本无从供给。

『压缩』绝不是万能的——可即便如此，

「——嗯，我觉得非常厉害。也许能行」

『对吧？所以先把这事刻进脑子里。只要一冲出轮回，第一件要做的，就是把倒下的大家拉起来。不然会被人一口气压制住。』

佩特拉点头，回应着那位积极设想轮回解除后局面的『昴』。

回过头去想，恐怕罗姆爷也抱着同样的念头。或者说，那位睿智的长者即便心灵磨损到近乎破碎，也仍把在地上刻下讯息这件事无意识地放在了最优先，通过一次又一次的积累，把轮回开启时的动作固定成了本能。

如此一来，『昴』提出的『预先决定轮回开启后立刻该做什么』的方案，就该采纳。

只是——

「……罗姆爷爷究竟重来过多少次，才把那件事刻进了身体？」

就算心都磨得稀碎，连自我都守不住，罗姆爷也仍在轮回刚一开启时，用手指在地上刮下字迹。要把那动作磨到纯熟，烙进灵魂里，哪怕心碎也能做到，他究竟累积了多少次？

「――――」

『佩特拉，来验证一下吧。以前碧翠子曾经设过一个局，让我在同一条走廊里无止尽地轮回。如果规则和那时一样，这个轮回也有让它结束的条件。』

咕咚一口咽下唾沫的佩特拉，听见『昴』给出了下一步的方针。她微笑着「嗯」了一声点头回应，重新望向前方。

「上啊，你们这群家伙！！」

「——哦！！」

就在佩特拉与『昴』方才的对话间隙，『阿尔德巴兰之刃』的同伴们一遍遍向阿尔发起挑战，又在他面前接二连三地倒下，这一幕反复上演。

说实话，在『死者之书』里所见的，那种把每一次循环都郑重对待，把任何经历都踏踏实实积累进自身的昴，让人既敬佩也觉得很帅。可想在这种连一分钟都不到的循环里做同样的事，恐怕很难。

『就算是我，也觉得在这种情况下，每次看着大家被打倒都要老老实实去承受那份痛苦，这要求太勉强了。可是不管怎样，把它牢牢记住吧』

「重复的次数？」

『那也是，不过更要记住的是，每一次你都确确实实地生过气、懊悔过、悲伤过——佩特拉的那份心情』

「——嗯，是啊。」

在这不断重复的世界里，在这一次又一次的循环当中，能把这份心情延续下去的只有她自己。于是她照『昴』所说，把它确确实实地记在心里。

就算阿尔不知道佩特拉她们在脱离小循环后遭了怎样的罪，也绝不会原谅他。她们吃了多少苦，一定要让他明白。

怀着这份誓言，佩特拉与『昴』相视点头，望向前方。

「是星星。——都是星星的错。」

随即，她与逼近到眼前的阿尔正面怒目相向——

「——Playball」

「——Playball」

就这样，豪迈地宣告要启程踏上地狱巡游。

198

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不让任何人替我束发。

199

——于是佩特拉在自己下定决心跳入的地狱里，不停徘徊。

「……该怎么办？」

她抱膝蹲下，额头抵在膝上，一次又一次地自问自答。

该怎么办。要做什么。要怎么做，才能让这场小循环结束。

「所谓的条件，是什么？」

要让这场小循环落幕，必须满足某个条件。——那个人是这么对佩特拉说的。

佩特拉也持同样的看法。这种一遍又一遍重复同一状况的情形，按常理必然有某个结束条件作为触发。约定俗成。规矩。既然是规则，就得遵守。不可以不守。应该是在遵守。既然遵守了，那就一定有让它收场的方法。好，打住。这场讨论到此为止。既然结束了，就来思考条件。能触发结束的，有哪些？

「各种各样的都试过了哦？」

把『压缩』运用到极致，比常人尝试了更多花样。

和伙伴们联手干掉阿尔也做过；要是不能打倒，那就用『压缩』让所有人撤离也试过。当然，让佩特拉自己逃到极限的远方也试过，刻意去被阿尔最后伸来的手抓住也试过，甚至还主动一头扎进阿尔的臂弯里。全都白费。

考虑到每个同伴或许都握着什么破局的办法，他们开过会，逐一把个人与来龙去脉抠得一清二楚，彼此倾诉过私密话，也打听了各自的家事、出身与故乡的故事，连十年挚友都未必会说的话都听了又说。没用。

干脆觉得去接近阿尔才是正解，于是试着和阿尔说话、把他推开、在没有同伴的情况下单挑，赢过也输过；不用『压缩』去战斗，赢过也输过；逃跑、嘲弄、夸奖、甚至唱过歌。全都没用。

「那我到底该做什么！？」

做过。不是都做过了吗。能想到的，已经全试了一遍不是吗。做了也没用，不是吗。做了也不行，不是吗。做了也毫无意义，不是吗。

「动手啊，你们这些家伙！！」

「——哦！！」

「吵死了！！」

反正什么都做不到，还叫得那么起劲，真让人火大。帮不上忙的话，至少别妨碍我思考。啊，我在迁怒。讨厌，讨厌，讨厌这样的自己。不想这么想。什么嘛，在装乖吗？这才是真正的我吧。对大家根本就没有喜欢什么的吧。口口声声说着喜欢大家、最喜欢大家，不过是喜欢那种看起来心胸宽广、慈悲温柔、对谁都一视同仁的「自己」的样子而已，对吧，对吧。

「吵死了吵死了吵死了吵死了吵死了……！」

左也好右也好，上下前后、过去未来现在、今天明天昨天、后天前天、去年今年明年、前世今生来世，全都、全部、所有的一切，all everything，吵死了。

「——现在，大概第几次了？」

烦死了。去死吧。要不，我来杀了你？

「继续。」

我就知道。

×××

「——领域展开，矩阵再定义」

又回到了同一个地方。吃惊了吧。偶尔也会说点不是「Playball」的台词。

在循环的这段时间里，大家并不是摆在那儿的木偶，你说点什么就会回应，做点什么也会作答。不只是大家，阿尔也是一样。

理所当然，阿尔也明白佩特拉这边遭遇了什么。

「那又怎样？」

就算明白，可当一个世界终结，下一次开始时，就连设局的人都不会跟过来。

佩特拉总是一个人，把同一个世界无止境地从头再来。没有人会懂佩特拉的苦恼与挣扎。一个人，一个人。孤零零。孤零零的。真的是孤零零的吗？

「——昴！昴！？你在哪！？你在哪里！？」

『佩特拉！』

仿佛被雷击般忆起的刹那，那道身影哗地出现在佩特拉眼前。看清那确实是昴，佩特拉这才吐了口气。

明明觉得一切都将要模糊褪色、消散，自己也快要什么都分不清了，可也并非全都忘光了，也并非被抛下不管。

「昴……」

她哭得一塌糊涂，泪水瞬间决堤，糊得满脸都是，朝他奔去。她扑了上去。他下意识伸出双手，想要抱住佩特拉。——没能做到。

穿了过去。她毫无缓冲地扑倒在空荡荡的地上。好痛。脸撞到了。昴——不对，『昴』没有接住佩特拉。当然。一直都是这样。『昴』的手，总是被别的人占满。

「那就别伸出手来啊！」

『佩特拉……』

「就那样……就那样放着不管，让我死掉不就好了。就在村子里，什么都不做，被魔兽杀了不就好了……」

她知道。如果菜月・昴什么都不做，佩特拉早就已经死了。

明明死了，却还活着。偏偏活了下来。正因为活了下来，才会像这样吃尽苦头，承受疼痛，却还是无法结束。

「对不起，佩特拉……对不起！但是等一下！别那么说……」

「哈、哈！？什么意思？我都已经这么难受了，你还要训我！？这样，一次又一次、一次又一次，一直这么痛苦，我都哭成这样了……还、还要、训、训我？要训我吗？哈、啊哈、啊哈哈，别这样！！」

——

佩特拉冲着『昴』吼了。做了。——做错了。

面露沉痛、心如刀绞的『昴』在那儿，佩特拉只觉得想要吐血。想把心脏挖出来。想把脑袋轰飞。与其这样，不如就那样做吧。

「让这次循环结束，最简单明了的触发器……」

一边说着，她用手比成手枪，将食指抵在自己的太阳穴上。把玛娜汇聚到指尖，朦胧的白光隐约亮起。

见状，『昴』惊愕地伸手朝佩特拉抓去。反正碰不到嘛，看，又扑了个空。

「等等，佩特拉！别冲动！我懂，我懂，但先别用那种方法！要是让你那么做，正中对方下怀的话……」

「那就，跟我结婚！！」

『——！』

「把我娶了吧！做只属于我的昴吧！把我放在第一位！我都救了你，跟我结婚！把我的整个人生都揽在怀里！把我的命也变成昴的！那样的话我就答应。可不是那样吧？那样的话就不再是我的命了。既然是我的命，就让我按我的方式去用吧！」

佩特拉连自己都不明白自己在说什么。

总之，对一切都火大。没有一件事顺心。对不肯想办法改变现状的大家也生气，对把局面弄成这样的阿尔也生气。开始讨厌了。讨厌讨厌。可我还是喜欢昴。哈。什么意思啊。他明明什么都没为我做。可他一直在做些什么，现在也在想办法吧。虽然不肯跟我结婚。

「这算什么，蠢得要命。」

『佩特——』

「啊，不对哦？我不是在说昴哦？像笨蛋的是我自己。」

「啊——，这种脑袋，已经不要也行了吧。再见。」

这么想着，从手指枪里「砰」地射出白光——

×××

「——领域展开，矩阵再定义」

——。

————。

————————。

————————————。

————————————————对吧。我早就知道了。

啊哈哈哈哈。啊哈哈哈哈哈哈。啊哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈。

200

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生不再祈求幸运。

201

——『忧郁魔女』佩特拉・雷蒂怀着毫不动摇的觉悟迎战。

从柯林特那里受托的魔女因子，其所带来的『忧郁』权能潜能之庞大超出常规。若说用来把局面操纵至对己方有利，世上恐怕再没有哪一种力量能比这更有效——它强大到让人不禁如此断言。

当然，要挥使那等力量，必然要付出相应的代价。——所谓能力越大，责任越大。也许有点不太一样。

无论如何，既然甘愿承担那巨大的负面效应，就必须让好处尽数发挥出来。否则，连亲近之人也要持续欺瞒的佩特拉，岂不太不值当。

「幸好法兰黛莉卡姐姐不在。」

要是法兰黛莉卡也参加了『阿尔德巴兰之刃』，佩特拉是否还能把谎言瞒到最后就很难说了。与其说是因为法兰黛莉卡的眼力，不如说佩特拉就是对她没辙。

对于那位主动赢得她至深敬爱的法兰黛莉卡，佩特拉根本无法藏着掖着。她一定会把心里话一股脑儿倾诉出来，哭着撒娇，向法兰黛莉卡依偎求助。

若只论保不保得住秘密，状态最佳的拉姆和奥托也同样让她难以撒谎。只是，因雷姆复活而飘飘然的拉姆，和丢失了『记忆』的奥托，都无法发挥他们一贯的洞察力，所以也没能察觉佩特拉的谎言。

「柯林特哥哥，到底知道到什么程度，才装作没看见放过了我呢」

年龄成谜、心思难测，唯一能确定的是他站在自己这边的柯林特，要说把佩特拉的盘算看得一清二楚也不奇怪；反过来，既然和罗兹瓦尔关系要好，要说对人心的细微处全然迟钝，也并不意外。

无论如何，柯林特在最初那一刻，就已经知道佩特拉付出了重大的牺牲。

既然已经付出过一次巨大的代价，那么是『除此之外再也不献出任何东西』，还是『既然都付过一次了，反正一样，再继续奉上更多』，两种想法他都可能有。

那么，就当作是在她下定决心的背后，有人默默推了她一把吧——对佩特拉而言，这样想最为圆满。

不管柯林特的真实意图如何，佩特拉的骰子已经掷出去了。

「现在，是第几个来着……」

不饮酒。不写信。不抱布偶。不用针线。不唱歌。不和孩子玩耍。不去探访承载回忆的地方。不采摘美丽的花。不吃喜爱的食物。不回故乡。不在人前落泪。不替任何人拭去泪水。不谈往事。不讲喜欢的故事。不以昵称唤人。不把任何人请进家门。不为任何人送终。不握住任何人的手。不再期望修复关系。不向任何人示弱。不与任何人一同看日出。不抱任何偏好与厌恶。不为任何人而哭。不向星辰许愿。不与人相约碰面。不与谁在晚霞中同行。不踩踏身旁同行者的影子。不为离别而留恋。不谈梦想。不参加任何庆祝。不送礼。不挥手。睡前不祈祷。不去抚慰伤痛。不为晴空而欢喜。不为雨天而叹息。不仰望彩虹。不欣赏静谧。不违背重要的约定。不奢求善意。不去送人远行。不接受施舍。不谈失败的经历。不让任何人替自己束发。不奢望幸运。——太多了。

要是把奉献的代价一一数来，简直没完没了，佩特拉的人生可说前路一片漆黑。

「即便如此，这已经算是相当好的了。」

善于撒谎的诀窍，是在谎言里掺入真实的精华。——这话众所周知，但佩特拉的谎言，结果也带上了类似的意味。

——将『忧郁』的权能所需的代价，由持有者佩特拉以外的许多人分摊。

这是大家愿意让佩特拉持有魔女因子的条件，不过，能用这种方式当作对价的，只有以权能的效果对象为中心的『压缩』。

若是艾米莉娅所愿、为了移动艾米莉娅而施行的『压缩』，便能由艾米莉娅付出对价来发动；可要是佩特拉自觉艾米莉娅有危险，由她以『压缩』将对方移走，那么支付对价的就会变成佩特拉。——这一点，持有者以外的人无法自觉。

无论是每一次与『阿尔德巴兰之刃』的商议，还是把阿尔连同艾米莉娅、雷姆一并丢进阿格扎德峡谷的时候，抑或在险境中骤然把同伴拉回来的时刻，又或将全员所尝的强烈痛苦在刹那间『压缩』之时，那份对价，付出的都是佩特拉。

佩特拉猜测，越是献出重要之物，『忧郁』的权能可发挥的效果容量就越大。

那既是对世界的影响，同时也像是由于佩特拉对世界施加影响的干涉力减弱所致。恐怕很简单地说，只要佩特拉把整个人生都奉上，『忧郁』的魔女因子就会带来更为强大的力量。

「可是，我不会那么做。」

即便权能侵蚀着佩特拉・雷蒂，仿佛在把自己的人生切割售卖，让将来的期望一点点缩水，叫她舍弃许多幸福，佩特拉也不会自暴自弃地扔掉性命，不会去寻求那样极端的选择。

「那样，太难看了嘛。」

不想让人看见自己难看的样子。不想做难看的事。

与『暴食』的大罪司教罗伊・阿尔法德交战时一样。——只要这份心意仍在支撑着她，佩特拉就不会失去自我。

因为佩特拉，佩特拉・雷蒂，向星辰——、

202

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生不做任何人的后盾。

203

「——领域展开，矩阵再定义」

为什么非得让我遭这种事？

我做过坏事吗？我不是一直都很乖吗？不是一直努力做个好孩子来着吗？

为什么，为什么，会变成这样，谁来，好好，给我解释一下。

「干了啊，你们这帮家伙！！」

「——哦！！」

我该怎么办？我什么都做了啊？做了好多次啊？

能想到的，全都做了。战斗并赢了？战斗并输了？战斗时让人死了？战斗时我死了？不战而死？逃了？哭了？

「是星星。——都是星星的错。」

佩特拉死了很多次。也打倒了很多人。也逃了很多次。

道过很多次歉。生过很多次气。流了很多很多眼泪。

非常害怕。非常疼。非常难受。

「——Playball」

我知道的。不会结束，对吧。不会结束给我看，对吧。就算现在这一瞬间听见我歇斯底里地哭，哪怕会担心，也会在十秒后忘掉吧。不，不是忘掉。是不再知道。把我甩在后面。只有我，被扔下。

「——领域展开，矩阵再定义」

我不要了。讨厌你们。讨厌讨厌，最讨厌。

为什么不来救我？明明我这么拼命地在叫，为什么？

不会结束。不会完。不肯结束。不让我结束。我，现在也是。

「开干了，你们这群家伙！！」

「——哦！！」

哭也好、喊也好、闹也好、诅咒也好，都是同样的重复。

真厉害。我搞错了。还以为也许能想点办法，居然还自我陶醉。我的、可靠的，可靠的？明明什么都没为我做？算了吧。那些所谓可靠的同伴，都是谁来着。明明那个女人她们那么厉害，为什么这关却怎么也过不去呢。

「是星星。——都是星星的错。」

不过呢，我懂了。我明白了。毕竟也没办法嘛。脑子一点一点、越来越不转了。对眼前的事，也渐渐没了兴趣。不对。不是没了兴趣，是我在主动疏远。为什么会那样，我也懂。

「——Playball」

因为啊，我不想讨厌大家。可是一想到大家，那些什么都不做的大家，我就会开始讨厌起来。所以不要。不要去想。为了不讨厌你们，干脆不再去想。关于大家，统统不想。大家的事，谁管啊。啊，不对。对不起对不起，骗你的，我超喜欢大家。来，喜——欢——。

「——领域展开，矩阵再定义」

因为没办法啊。还只是个孩子嘛。就算踮起脚，也不可能一下子就变成大人。在这里就这样，一直一直过着同样的时间，久了就能变成大人吗？很遗憾，不会。因为只是同样时间的重复。不管怎么努力都一样嘛。既然努力了也是一样，那不努力不就行了吗？

「干了啊，你们这帮家伙！！」

「——哦！！」

对对，努力也没意义。反正都一样。唉，努力吃了亏。要不要干脆别把事想得那么复杂呢。唉，努力白费了。一点意义都没有。我一直都在做无用功。对吧。是啊。我早就知道。

「是星星。——都是星星的错。」

说到底，就算努力也没用。就算努力，我也不可能当上国王。我也不会被人好好珍惜。我也不可能，和那个人结婚。所以，已经没办法了。没办法的呀。

「——Playball」

既然没办法，那就，算了吧。

『——哪有什么「没办法」。』

为什么？

『放弃并不容易吧。……可它，又很容易。』

为什么？为什么？

「心会折也好，就算自己会死，也不过是擦伤而已。」

为什么？为什么？你怎么还能说这种话？

「因为——」

为什么？为什么？你怎么还能说这种话？然后呢？

「因为——」

为什么？为什么？你怎么还能说这种话？然后呢？接下来——？

「——我们还大有可为。小菜一碟。」

――。

――――。

――――――――。

――――――――――――。

――――――――――――――――真的，你啊，真不擅长撒谎呢。

我早就知道了。

204

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不放弃。

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生绝不屈膝。

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生不为选择而后悔。

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生不流悔恨之泪。

——神啊、佛啊、欧德・拉格纳大人啊~ 我发誓此生不忘我所爱。

205

——佩特拉・雷蒂，是露格尼卡王国下辖一座村落——阿拉姆村出身的乡村姑娘。

『本来』的佩特拉，本不是会参与左右世界大势之战的女孩。

作为一个普通的乡村姑娘，凭着她的可爱与小聪明过上稍微好一点的生活，或者被世间的巨浪吞没，凄惨地散尽了性命。她不过是那样的存在。

但是，偏离了『本来』的轨道，并且知晓了如今自己的佩特拉想着：

「即便人生能重来无数次，我也还是会再次背离『本来』。」

对，就是这样。离开『本来』，无论多少次，佩特拉都会再来到这里。

然后，她想要说。对那个让佩特拉从『本来』的道路上偏离、把她救出来的你。

对那个带着痛苦的表情，编着拙劣的谎言，拼命想牵着她的手把她拉走的你，她想这样说：

「——托群星之福，我才能在这里。」

『———』

「———」

如此说着，又用手背擦了擦自己嘴唇的佩特拉，让阿尔和『昴』都哑口无言。

且不论阿尔，佩特拉明白『昴』失语的缘由。他大概以为，自己拙劣的谎言与鼓励，把佩特拉打击得连话都说不出来了吧。

的确，是个拙劣的谎言。明明才刚说过，巧妙的谎言要掺进一点真话才是诀窍，可那句话里却连半点真东西都没有，是笨拙至极的谎言。

「可是，我不想让我喜欢的人，变成骗子啊。」

所以，佩特拉振作起来了。靠自己。因为安慰也好、鼓励也好都靠不住，因为他一直用担心的眼神望着我，明明不敢碰我，却还是想伸手去揉我的头、想去托住我的背。看着他那份笨拙而拼命的样子，我就想，真是拿他没办法啊。这是恋上他的弱点。

「我喜欢的人啊，可不是骗子哦。」

因为，佩特拉就这样站起来了。佩特拉站起来了，所以，昴不是骗子。

反复的世界很苦。要把那颗一度濒死的心重新立起来，并不是容易的事。不如说，是我这辈子里最难、最辛苦的一回。可我站起来了。站起来了。因为就在我身边，有个人一直相信着眼前这个总是最新的、笨手笨脚、弱不禁风的佩特拉。

「我的星星，一点坏的地方都没有哦。」

好厉害。非得拼命不可，好辛苦。明明我算是手巧的那种人，明明做什么都能很快上手，可要回应这个人的期待，实在太难了。可这个人啊，就算是在那种能把谁的心都压得粉碎、让人再也站不起来的可怕地狱里，就算要被迫把同样的事做上几百次、几千次、几万次，他也会毫无根据地相信：「佩特拉不会输！」既然他这样相信，我还能不去做吗。

如果菜月・昴相信，佩特拉・雷蒂是个就算经历成千上万次循环也不会让心破碎的坚强女孩——那就这么干。

「异世界的女孩子呀，要是连奇迹都不能自己掀起，是活不下去的哦。」

不做到把自己从『本来』命运轨道上硬生生拧出去的程度，连那个能从心底里爱到不行的对象都遇不上。

「——阿尔先生，想重复多少次都行，但我觉得是徒劳。」

佩特拉打断了那句关于星星的错之类的套话，对沉默的阿尔如此说道。

这不是逞强，也不是虚张声势，而是佩特拉的真心话——哪怕这段时间不是重复上万次，而是上亿、上兆次，也磨不垮佩特拉。

也不是那种『因为女孩子的爱是无限大嘛』之类童话式的解法。

「这不就是个要反复到把阿尔先生的对手的心磨到彻底耗尽为止的循环吗？」

就算战胜了阿尔、杀了他、把他扔到遥远的地方，也不会结束。

就算败给阿尔、被抓住、或者拼命逃到遥远的地方，也不会结束。

就算亲手杀了自己、被人杀死，或是在绝望中想把一切都丢开，也不会结束。

说白了，已经重复了一万次以上，却仍旧没有结束。

「不过呢，在哪儿收手，应该是由阿尔先生来判断的，对吧？」

要结束这无尽的循环，除了让阿尔解开『领域』，实在想不出别的办法。

并不是那种对象的心一碎就会自动终结的便利循环。每一次结束的时机，应该都是身处循环中的阿尔有意识地决定的。

归根结底，只要让阿尔认输，别说一万次，哪怕第一次也能让这场循环结束。——只要能让那个永远处在『初回』的、谨慎而怯懦的阿尔下定那样的决心。

「所以，我希望你就在这里收手吧。除了我之外，大家都已经倒下了，阿尔先生的战果已经足够了吧。再继续，也没有意义了呀。」

再强调一遍，佩特拉这话既不是虚张声势，也不是逞强。

就算照这样无休止地反复循环，佩特拉的心也不会崩溃。

因为，佩特拉已经做出了选择。

「我啊，已经无法放弃，也不能后悔，就算再不甘也哭不出来，也没法忘记我最喜欢的大家。——我成了那样的『魔女』。」

——因为佩特拉・雷蒂选择成为『忧郁魔女』。

「喂，阿尔先生。——这话，还要说几次？」

听见侧着脑袋发问的『忧郁魔女』的这一句，阿尔喉头轻轻一动。

阿尔之下，看不见他的双眼；然而却能察觉，他的目光仿佛在『忧郁魔女』那圆圆的瞳孔深处看见了什么不可名状之物，因而蘊生出漆黑的情绪。那大概与阿尔心中深深扎根、无从抹除的伤痕有关。

也许他曾经也这样，深深凝视过『魔女』的眼睛，于是受了伤。

那份创伤——

「——『压缩・痛苦』。」

将阿尔背负的创伤，『压缩』后狠狠塞入。

让脑髓沸腾，让血流倒灌，把喜悦也好哀叹也罢，幸福也罢不幸也罢，那道还未愈合的伤口上刚结的痂一把撕开，不是撒盐，而是把创伤本身狠狠揉进去。

把那种会让他在往后的人生里一遍、十遍、百遍、千遍地想起就会落泪的创伤刺激，于这一刹那，以成千上倍的浓度让他尽数承受。

「——啊。」

刹那之间，面对对『忧郁魔女』的恐惧与被刺激后的创伤的『压缩』，阿尔并非以肉体，而是以灵魂作出反应，伸手去抓那最近在咫尺、最容易攫取的救赎。

也就是说——

「——游戏结束了！」

——让无尽的循环画上句号的办法，是让下一次循环开始。

抱着这样的笃定，『忧郁魔女』与身旁心上人那只无法触及的手十指相扣，指节相叠，含笑。

「真不体面呢。——要是换成昴，他明明会逞强地说『心都折了也不过是擦伤罢了』」

『你，帅得过头了啊，佩特拉』

她听见心上人有气无力，却又带着自豪地如此说道。

『忧郁魔女』怀抱着那份满足，仍旧面向前方。

——那么，这里就是，最后的，胜负关头。

既然把受创的心、想要就此结束的软弱、因不甘而流下的泪水，统统当作代价献上——在得到所渴望的那种胜利之前，『忧郁魔女』绝不松懈。

206

——解开『领域』，重新缔结，重构矩阵。

那等同于承认，将理应必胜的『领域』强行加诸于人，这一招注定会败北。

然而，别无他法。已有前例可循。『领域』无法杀死被它推为加害者的『魔女』。

当然，这里的『杀』只是权宜之称，瞄准的终究也仅限于心灵——、

「――――」

大大方方地宣称要撑过『领域』的佩特拉——不，如今已不能再仅仅称她为佩特拉了。她名副其实，已然化身为那样的存在。

——『忧郁魔女』。

过去，打倒阿尔德巴兰『领域』中加害者的，是『强欲魔女』。

回想起来，无论『领域』的主导权在受害者还是加害者手中，阿尔德巴兰的权能在首战时都吃了败仗，真是不祥。

总之，即便此刻『领域』被弹开，战况仍是阿尔德巴兰占优。

「——」

除了『忧郁魔女』之外，高举讨伐阿尔德巴兰旗号的『阿尔德巴兰之刃』已然覆灭。遗憾的是，借由『领域』施加的心灵磨耗是绝对的。阿尔德巴兰并非抱着那种温吞的觉悟才决定把『领域』强行加诸他人，演戏或装死并不足以逃脱。

更确切地说，他应当都会先确认到把目标的手脚砍落一两条这种程度，才会判断将『领域』转移到下一个目标。由于自我没有连续性，佩特拉也无从得知自己究竟用了什么办法来确认，但既然现在的佩特拉能想到，循环中的佩特拉也一定能想到。

所以，佩特拉可以笃定地说——除了『忧郁魔女』，没有人能再站起来。

「不过，那边也明白这一点。」

自己能站起来，其他同伴也一定能站起来——阿尔德巴兰还没天真到抱着这种甜得发腻的预期就贸然行动，他可没把眼前的『忧郁魔女』看得那么轻。

既然如此，就有的。『忧郁魔女』必然握着从这里翻盘的方策。

——那位就算被变成了『魔女』，仍旧扬言『托群星之福才有如今』的少女，她的底牌。

——

『领域』被解开，阿尔与『忧郁魔女』仅在一瞬间进入了解放状态。彼此相距约五米，但在对方的权能面前，这点距离等同于无——或者说，只要她有那种名为『压缩』的权能，距离根本算不上任何让人安心的凭据。

不过，归根到底也只能是权能。

她一定会打出『忧郁』的权能这张牌，主动发难。

而最有可能出现的效果，当然是借由『压缩』召来他人。

可能会被召来的，是——

「——雷姆小姑娘，还是梅莉小姑娘？又或者，边境伯老爷？」

若从「不在场、且是『忧郁魔女』能调度」的战力去思考，最先浮现的便是那些人。雷姆理应正与雅耶激战正酣，但既然拉姆没有半点动摇，通过共感应能分辨的败北滋味并未传来。那样的雅耶会输难以想象，可此时却不得不把这种可能纳入盘算。

带着成群魔兽的梅莉，和那位在帝国也横行无忌、火力堪称怪物级的罗兹瓦尔，也完全在可能之列。

然而不论哪一个，都不过是强而已、难缠而已。靠数量或强度逼迫阿尔德巴兰，到现在为止已经证明行不通。若她的打算真止步于此，那也未免太浅薄——

不对——

并非其中任何一个，阿尔德巴兰从『忧郁魔女』的眼神里直觉到这一点。对方本就能将思考过程『压缩』，导出无视时间概念的结论。像阿尔德巴兰这类刚冒头就被自己否掉的念头，『忧郁魔女』也会在动手前的斟酌阶段就弃之。——也就是说，不是那样。

得从根子上翻转思路，才能追上她。

若『忧郁魔女』此刻要召来的人，必是有凭有据足以打破僵局的存在——

——难道！

咬紧牙关，瞠目而视。下一瞬，仿佛见证了阿尔德巴兰脑海里突触的电光乍现，『忧郁魔女』高举的手猛然挥落。——刹那，『压缩』发动。

就在阿尔德巴兰与『忧郁魔女』之间，猛地闯入的，是——

「——哇哦。比想象中的修罗场呢。」

——戴着手枷、行动被束缚的『暴食』罗伊・阿尔法德。

207

在看到从天而降的罗伊的瞬间，阿尔德巴兰便确信了对方的意图。

他判断有八成可能罗伊还没死。

本就如此，若要拯救『暴食』的受害者们，罗伊的存活必不可少。事实上，既然已经让他吐出了雷姆的『名字』，『阿尔德巴兰之刃』就更应当笃定这一点。

至于如何让他配合另当别论，但若夺了他的性命，连谈判都无从谈起。——那两成会死的情况，一种是处境不允许、无法设法保全他的性命；另一种则是罗伊过度挑衅，把对方激怒到『杀了也无可厚非』的地步的情形。

无论如何，罗伊能活着是件幸事——然而，对方的盘算却不妙。

在此时此地，『忧郁魔女』特地把罗伊叫来，如果不是单纯的利敌之举，那必然有其理由。有其目的。必定存在某种能让罗伊为她所用的密约之类的东西。

而那位在翻读『死者之书』时竟仍得以复活的她，能从菜月・昴的知识里捡拾出『嫉妒魔女』行动的缘由。一旦明白这一点，便能由此引发连锁反应，去做成某些事。

那就是——

「——让莱因哈鲁特来！」

假如『忧郁魔女』和罗伊缔结的密约，是让他动用那项权能，那么，对于一位心灵破碎到连『领域』都不再奏效的『忧郁魔女』而言，为了夺回菜月・昴，作出极限的、自我牺牲的抉择也并不奇怪。

那便是连阿尔德巴兰也预见到的，由『暴食』的权能实施的世界救济——从读过菜月・昴『死者之书』之人身上，夺走那份『记忆』。

而一旦『嫉妒魔女』抽身，原本被牵制住的世界抑止力便会降临。

那个曾在层层挑战与陷阱中，被他们勉强击退过一次的『剑圣』。

——只要『剑圣』莱因哈鲁特・范・阿斯特雷亚赶到，一切就结束了。

计划将会崩溃。正因如此，阿尔德巴兰将全力以赴加以阻止。

凭借『忧郁』的权能，被拉到此处的『暴食』罗伊・阿尔法德——

「——禁止吞噬『记忆』！否则就让咒印将你灼烧！」

他把先前放松的条件再次收紧。

反复更改条件，连作为烙下咒印一方的阿尔德巴兰的灵魂也遭受了沉重创伤，他清晰地感到体内深处的奥德出现了裂纹。那并非疼痛，而是一种巨大的失落——据说连菜月・昴也曾尝过的、根源被损坏的感觉。

不过如此一来，罗伊吞噬『忧郁魔女』的『记忆』这一事态就能避免了。

只要『嫉妒魔女』不退下，『剑圣』也无法赶到这里——

「——阿尔」

正以为成功阻止、情不自禁握紧拳头的那一瞬。

『忧郁魔女』唤了阿尔德巴兰一声。他原以为她的算计落空，必然会是一副苦涩的表情；她确实露出了痛苦的神色。

然而那并非为自己未来哀叹的表情——而是在怜悯这边。

「你在——」

伴随着浑身汗毛乍立的战栗，阿尔德巴兰思索起『忧郁魔女』那副表情的含义。

然而，那是错误的。不该去思考。与其思考，不如立刻去死才对。要是此刻已经死了，不管那是什么，总还有办法应对。

阿尔德巴兰在关键时刻，又一次，没能去死。

又像当初让这个世界的太阳沉落之时那样，再一次。

「——Playball」

就在『忧郁魔女』替阿尔德巴兰说出了他本该说却没能说出口的那句台词的瞬间——

阿尔德巴兰的天敌，已站在了他的身后。

208

「——我，好像明白阿尔先生的弱点了。」

那是『阿尔德巴兰之刃』正式结成之前，为了打倒阿尔一行而举行的作战会议期间，成为『忧郁魔女』的佩特拉所得到的一个领悟。

根据罗姆爷的证言，当得知阿尔的权能与菜月・昴所拥有的『死亡回归』同属一种类型的能力时，佩特拉便想到：若连发动条件都与昴相同，那就有办法加以阻止。

当然，那时她还没有确证。

那种方法是否可行，还得向当事人确认。而且，除去在『死者之书』上的那点交集外，佩特拉与她——不，是他之间几乎没有任何联系。

但若有可能，便在『阿尔德巴兰之刃』行动前先行接洽，约定在将阿尔逼到真正意义上的极限时，作为压箱底的王牌登场。

然后——

「——Playball」

将那句被反复宣告的话原样奉还，忧郁魔女隔着被她当作诱饵、丢在自己与阿尔之间的罗伊・阿尔法德，望向对手。

可悲的是，阿尔完全依照忧郁魔女的打算、她所期望的那样行动了。

只要看见罗伊，他就会以为目的是逼他动用那项权能。——毕竟罗伊与菲鲁特暗订密约，心怀对阿尔的背叛。若是在『时光倒流』的循环中有机会打探到这一事实，他就会去怀疑罗伊的盘算——她是这么预判的。

果不其然，阿尔依照预期行动，选择封死罗伊的背叛。

却万万没料到，与罗伊动作几乎同一时刻，忧郁魔女的底牌出现在她的身后。那样一个人的存在，他根本不可能想象得到。

此处集结的『阿尔德巴兰之刃』六十一人，确是艾米莉娅阵营与菲鲁特阵营所能动员的全部战力，这句话并非虚言。——就艾米莉娅阵营与菲鲁特阵营派出的成员而言。

所以——。

「都已经破破烂烂了喵。——让人家来治好你，喵？」

瞬间，即便放眼整个世界也再无出其右的治愈术师——『青』的菲利斯——施展出最上级的治愈魔法，从阿尔身上夺走了『死』。

209

——『青』的菲利克斯・阿盖尔。通称，菲利斯。

王选候补库珥修・卡尔斯腾的第一骑士，王国最强——不，世界最强的治愈魔法使。也是阿尔德巴兰的三大天敌中，最后的那一人。

为了计划，连菜月・昴与『剑圣』莱因哈鲁特・范・阿斯特雷亚都能设法摆脱的阿尔德巴兰，绝不该撞上的最后一道障碍。

而那人，向阿尔德巴兰施下了温柔慈悲、却残酷至极的魔法。

「啊、啊啊啊啊——！！」

全身汗毛倒竖的刹那，阿尔德巴兰猛地甩动身体，将站在背后的对手——菲利斯——摔向地面，同时解开口中含着的毒药包。

那东西瞬间渗入舌头的黏膜，对阿尔德巴兰的生命机能造成致命危机，按理说数秒之内便会将他送入死亡——然而并没有。原本该崩坏的组织被一一修复，就连在头盔里喷涌而出的鼻血，也在一秒之内止住了。

「可恶——」

于是他当机立断，凝出一把石龙刀，将刃抵在自己的颈侧，猛地一划。

粗大的血管被割断，汹涌的鲜血喷涌而出，却并未——威胁到阿尔德巴兰的性命。伤口立刻愈合，疼痛甚至不过像被针尖轻轻一刺。

「可恶、可恶、可恶……！」

着了道。在所能想到的一切手段里，这是最可怕、也最有效的阿尔德巴兰封锁法。

封住『死亡回归』的办法其实再简单不过——不让他死。仅此而已。

世上最温柔的一双手，反倒成了杀死阿尔德巴兰与菜月・昴的方法。

「到此为止了哦，阿尔先生。」

『忧郁魔女』就这样平静地对狼狈失态的阿尔德巴兰宣告。

死不了。也无法重来。索性，他看向倒在一旁的菲利斯，甚至起了让他解除那治愈魔法的念头——

「不行哦。还是说，你想和小菲利来一场徒劳的耗劲比试？」

即便剑锋指向他，菲利斯也不改神色；他亦是下定了觉悟闯入此局的人之一。

若菲利斯也给自己施下了与此刻阿尔德巴兰同等的治愈魔法，那么无论如何挣扎，现在都不可能逼他解除魔法。

也就是说，阿尔德巴兰在这里已经无计可施——

『——谁都赢不了我创造出来的你』

「――――」

又一次，『魔女』的声音传来——就在那一瞬。

可怖而毁灭性的冲击波自远方爆生，将阿尔德巴兰、『忧郁魔女』，以及立于这场终局的所有一切，瞬息吞没。

210

——那绝不是『神龙』有意为之的援助。

战场被迫更易，与龙壳真正的持有者鏖战，当两位魔法使实现的奇迹之超魔法洞穿了龙晕之时，『神龙』做出了重大的抉择。

它并未将此刻自己眼前的胜利置于优先，而是将作为其半身的另一个自己、他们开启的目标、愿望与宿愿的达成置于首位。

『――――！！』

被释放出的『龙』的最后一息，并非奔向龙人或魔法使们，而是指向遥远的彼方——命中了它应当抵达的目的地：大地上张开的巨大孔洞，被称为世界最深最暗、直通地底的摩格阿雷德大喷口。

由此所掀起的、宛若天变地异般的灾祸与全世界的惊叹，难以言喻；而在这片战场上，那股力量亦化作巨大的大地之浪，汹涌扑来。

就在与『忧郁魔女』决出胜负的瞬间，巨浪席卷了两人的战场。

——

不明所以间，他被喷涌而出的激流与扑面的尘埃烟柱吞没，阿尔德巴兰却猛然瞪大了眼——真正意义上的、千载难逢的机会降临了。

这毫无疑问是降临于阿尔德巴兰的望外之机，也是最后的机会。

这并非『忧郁魔女』的算计，而是阿尔德巴兰一生罕见——本以为在与普莉希拉相遇时就已用尽的——那点好运，再度起了作用。

「——」

几乎要愣住也只是刹那。阿尔德巴兰在风与水的鞭打中，盯向被水雾遮蔽的战场，去寻找那个目标。

不是『忧郁魔女』，不是菲利斯，也不是倒下的『阿尔德巴兰之刃』。

而是在这片战场上，唯一、最后、或许还能由阿尔德巴兰打出的那一手。

在『死亡』被封印、同伴尽失之后，阿尔德巴兰与只剩在自己体内的那位『魔女』共同指向的夙愿——将其实现的最后方式。

那就是——

「罗伊！！在的话就出来！把我……把我的『名字』给吃掉！！」

阿尔德巴兰胡乱地更改着咒印的条件，在巨大的负荷下再次体会到欧德龟裂的痛感，抱着让灵魂吐血的觉悟，嘶声怒吼。

将这一局面归零——即便被封禁了权能的阿尔德巴兰也能做到的唯一一着。

让『名字』被吞噬，从所有人的记忆中抹除，以此将一切翻盘。

为此，他在翻涌的尘烟中搜寻那可憎的『暴食』的身影，仰天怒吼。

「把我吃了！我的、我的『名字』是——」

被命名为阿尔德巴兰，被强加上『尾随星』宿命的存在。

把菜月・昴从世界里剔除，替『魔女』完成她的夙愿。即便背负这样的宿命，仍旧憧憬着太阳，最终落得一无所有的废物。

那『名字』是——

「利格尔。——菜月・利格尔！！」

那是背弃了『魔女』的期待，让太阳沉落的愚蠢之星的『名字』。

** 『最后的侍奉』

——菲利斯之所以会协助『阿尔德巴兰之刃』，当然是为了他的主君库珥修・卡尔斯腾。

起初，菲利斯与威尔海姆一道，为了能加入前往开放后的普雷阿迪斯监视塔的调查团，特地来到王都，打算进王城当面交涉。

阿尔德巴兰一行的王都袭击——『暴食』的大罪司教被人从牢中放出，甚至还与『剑鬼』『神龙』上演了激战——正是在此时发生的。

「——有件事想禀告各位，同时也希望得到你们的协助。」

向菲利斯等人说明来龙去脉并提出协助请求的，是艾米莉娅阵营的内政官奥托。从他口中得知阿尔——阿尔德巴兰的暴行，以及莱因哈鲁特参战的消息后，菲利斯与一旁迫不及待的威尔海姆不同，对全力配合一事并没有那么积极。

诚然，身为近卫骑士团的一员，平素面对扰乱王国治安之辈，他自有怒火。可是，单论战斗力他并不强，更何况连自己唯一的长处——治愈术——都无法用来拯救最为重要的主君，那么自己究竟还能做些什么呢。

事实上，在紧接而来的战斗中，威尔海姆败给了『神龙』，被打成重伤昏迷不醒，这一结果让菲利斯的那份念头愈发强烈。

然而，就连这样的菲利斯也不得不抬起头来，因为发生了无法继续低迷的事态。

「好久不见，菲利克斯大人。」

与行屈膝礼的女仆——雷姆——面对面之际，菲利斯脑海中浮现出与她对话、并肩作战的往事，也由此得知，『暴食』的权能是可以剥离的。

这也就意味着，她是活生生的证据，证明库珥修所背负的两道诅咒——『记忆』和『龙之血』——其中至少有一项可以被解除。

「……既然如此，就只能干了喵。」

曾一直陪伴痛苦中的库珥修，也不断鼓励着因自觉无能为力而消沉的菲利斯的威尔海姆，如今也倒下了。

菲利斯决定应请求出手，借力『阿尔德巴兰之刃』，去阻止那伙即便以全世界为敌也要达成某种目的的阿尔德巴兰一行。为此，什么都可以做。

话虽如此——

「——倒是没想到，会轮到我来当王牌。」

在骇人的喷烟与暴风中，被倾盆而下的雨滴抽打着，菲利斯用手捂住口鼻防尘，感慨自己被赋予的这份出乎意料的角色。

佩特拉以名为『压缩』的力量，能在转瞬之间移动目标，亦能让谈话在刹那间收束——借此，她一再使出把伤员送到菲利斯身边，治好后再送回战场的犯规手段，『阿尔德巴兰之刃』也因此得以紧咬强敌不放。

光是那份工作就已经相当吃重了，却没想到还把对付拥有离谱之力的阿尔德巴兰的决胜一击交给了她们。

——在阿尔德巴兰身上施加一种常时发动的治愈魔法。作为对付阿尔德巴兰的王牌，这个不容失败的任务落在了菲利斯肩上。

说到底，哪怕到现在，菲利斯也仍未完全理解。

综合佩特拉与罗姆爷的说法，菲利斯的理解是：当阿尔德巴兰判断自己『受了致命伤』时，时间会倒回到负伤之前——他正是滥用这一点，一次次渡过绝境，甚至连莱因哈鲁特都被他逼退。

老实说，正常人都要怀疑大家究竟在认真讨论些什么。若那是真的，也未免太过无敌。谁还能赢得了他？

更何况，所谓击败这等无敌之力的办法，竟然是菲利斯的治愈魔法。

未免也太像一场豪赌了。

也许，这样做不过是把大家好不容易逼入绝境的敌人治得恢复如初的蠢举。

即便如此，哪怕只是万一，如果菲利斯能成为这场战斗的胜负手——

「不要懊悔，菲利斯。你的心高贵无比。为你的才华而自豪吧……那是这世上最为温柔的力量。」

「——殿下」

曾经，有人如此评说过菲利斯的力量，也如此替他而自豪。

那时也是，如今亦然，菲利斯的力量仍未能配得上『青』的称号。可即便如此，不把它当作诅咒，而是不断打磨至今 —— 这一切应当是有意义的。

为此——

「——罗伊！！在的话就来！把我……把我的『名字』吞下去！！」

从看不见的粉尘深处，在轰鸣喧嚣的风与大地的悲鸣中，传来了声音。

菲利斯的治愈魔法看来的确发挥出了作为底牌的效果。阿尔德巴兰那强烈动摇的身影，以及这声拼死的呼喊，便是证明。

然而，对手还没有放弃。——菲利斯也支起纤细的膝盖，思索着：

「为了我最重要的人，我还能做些什么？」

211

「利格尔。——我是菜月・利格尔！！」

在浓烈翻涌的尘烟中扬声高喊，阿尔德巴兰竭力凝神寻望。

暴雨、狂风与地鸣喧嚣不绝，周遭的声息几乎辨不清。在既不能依赖视觉也不能依赖听觉的情况下，他仍仿佛要把喉咙撕裂般放声怒吼。

施加在身上的可憎治愈之力，将嘶喊到几乎吐血的嗓子转瞬修复。他一边享受着这份讽刺般的恩赐，一边仍以全力嘶声咆哮不止。

「罗伊！罗——伊！！来找我！我是利格尔！菜月！利格尔！！」

每一次吐露，灵魂便仿佛被无形的锉刀一点点磨削般痛楚难当，阿尔德巴兰仍不知多少次地呼喊那个名字，呼喊、呼喊，呼喊个不停。

菜月・利格尔。——在自称『尾随星』之前，阿尔德巴兰的真名。

「——」

毫无实感。只有令人厌烦的感觉黏在脑海一隅挥之不去。

对阿尔德巴兰而言，比起那个从未被父母亲口呼唤过的名字，被『魔女』一遍遍呼唤的『阿尔德巴兰』要更合他的耳朵。可连这称呼，也自『魔女』成了『强欲魔女』的那一刻起，化作了伤口。

他已不再明白自己『本来』为何者——然而，自我认同无关紧要。重要的是，欧德・拉格纳会如何记录下这条可怜的性命。

所以——，

「——我是，菜月・利格尔。」

对那个一报上来就只觉恼人的名字，阿尔德巴兰仍认其为己。

即便他拒斥也好、嫌恶也罢，命也好父母也罢，都不是能由人挑的。

「——」

仍旧嘶声怒吼着，阿尔德巴兰在翻涌的烟尘里拼命搜寻罗伊。

先前那股毁灭性的暴风将战场上的一切几乎统统掀飞。阿尔德巴兰自己也被滚翻了好几遭，『忧郁魔女』、菲利斯、罗伊想来也不例外。

按理说，此刻这片战场上再无人能动。可对手连王牌菲利斯都捂到最后一刻才打出，手里还藏着伏牌也不奇怪。——而在阿尔德巴兰的『领域』被封死的现在，那就足以成为定胜负的一手。

「可恶……！」

至少想着把『领域』强行按到菲利斯身上，哪怕只救下菲利斯也好，可不行。那种将差点抓住的 BUG 随心所欲使唤的感觉，被『忧郁魔女』击退后又远了一截。况且就算撇开这一点不谈，目标的随机性也太强；要是再打到『忧郁魔女』身上，简直惨不忍睹。

更何况，菲利斯的治愈魔法——那道持续为阿尔德巴兰恢复的术式，是靠从阿尔德巴兰自身挪用发动所需的玛娜才得以维持。

而这在如今因与『阿尔德巴兰』相连，几乎等同于无尽无穷。

「『领域』指望不上了的话……！」

索性抱着把成了枷锁的玛娜耗尽的觉悟，用大魔法将障碍一举清除。这个念头一浮现，阿尔德巴兰便在脑海中勾勒出一道又一道术式。

这些无一不是从『魔女』那里学来的，却因无法负担发动所需的资源而被束之高阁——但如今既已与『阿尔德巴兰』连结，便能施展。

就像对付莱因哈鲁特时那样，借此在没有『领域』的情况下寻找突破——，

「呕……！」

——念头才及于此，汹涌而上的呕意便堵住了阿尔德巴兰的喉口。

剧烈的眩晕与耳鸣袭来，阿尔德巴兰一个「啊？」差点跪倒。他慌忙环顾四周，以为遭了袭击，却谁也不在。——随即意识到，

此刻令他目眩的根源，竟是不寻常的压力。

那种『这一步绝不能选错』的压力，正死死攥住阿尔德巴兰的心胆，几乎要将其捏碎。

「……骗、人的吧」

低头望着自己颤抖的右手，阿尔德巴兰一时语塞。

在这修罗场，在一切所为或将化为泡影的生死关头，靠着那可恶的治愈魔法，身体状态反倒好得很；明明是需要做出最快最优判断的当口，却因为发怵而脑子转不动——简直像个糟糕的笑话。

可现实并非玩笑。就算如噩梦一般，那也是事实。

——因为阿尔德巴兰从未在没有权能的情况下，做出过决定性的抉择。

这场战斗开始以前，无论在佛拉基亚帝国，还是王选，或是剑奴孤岛，甚至更早与『魔女』相处的那些日子里，阿尔德巴兰的选择始终是有权能庇护的最优解。

无论犯下怎样的失败，都能重来，改选别的选项，把失败一笔勾销。反复如此活到现在，这就是阿尔德巴兰的活法。而这一切，如今行不通了。

「——――」

不清楚要掀起多大规模的风，才能把喷烟吹散而不致伤及性命；让降水蒸发所需的热量也好，用来抵消地鸣的冲击也罢，在这片烟雾前该先迈出右脚还是左脚，哪一步才能通向最好的答案——一切尽是未知数。

无法确认的事，最令人恐惧。

走在没有正确答案保证的道路上，就像在黑暗中摸索前行。

那种没把握会有回报的道路，阿尔德巴兰走不下去。——毕竟，无法发挥权能的阿尔德巴兰，就是个无可救药的木偶。

无论是那两位『魔女』，还是心爱的女人，那样的木偶都没能救下。

「——」

一旦开始思考，脑海里便尽是坏念头掠过。

让罗伊吞下自己的『名字』的计策，真的是最优解吗？难道没有别的可以出手的办法？拿咒印作盾放任罗伊横冲直撞，再伺机而动会不会更好？能不能找出一种在完全治愈的缝隙间穿针引线般奏效的、划时代的死法？又或者，趁着尘土飞扬混乱逃走，反而更好？等等等等，唯有情绪越发焦躁——。

『——看吧，又来了』

「——」

那股焦灼的情绪，仿佛被兜头浇了盆冷水般戛然而止。

迷惘与恐惧，因权能被封而一口气迸发的阿尔德巴兰的负面情绪，在那牵引之下，深埋心底的最大悔恨也开始发烫。

那是种极限的热量——一触即灼，仅仅在旁便似要灼肤；却又与之相反，让他连血液的每一滴都冷透的感觉。阿尔德巴兰吐出一口气。

『又是妾身的——』

「……住手」

『妾身的——』

「住手啊啊啊——！！」

他一直以捂住耳朵、移开目光、把一切硬生生塞进心底的方式逃避直视，而当他几乎被逼得与之正面相对之时，阿尔德巴兰发出绝叫。

他拒绝耳畔的声音，拒绝眼前的微笑，拒绝渗入的炙热，龇牙以对。——刹那，他强行撑开的双眼里，喷烟彼端映出一缕微弱的残影。

那只是掩于尘烟的一瞬之姿，但绝不会错。那是罗伊。是『暴食』。

能把他从这汹涌而起的悔恨——不，从此刻包围阿尔德巴兰的最恶局面中拉出来的唯一光明，他看见了。瞬间，他奔了出去。

「——罗伊！我在这里！来吃我！把我的『名字』吃掉！！」

那一步迈出的犹疑，盘算死法的怯懦，想要逃向他策的软弱，质疑自身抉择的怠惰，都在那一瞬蹬地的冲击里被粉碎。

此刻，阿尔德巴兰将眼前飞来的选择死死攥住，心无旁骛，以此选择从最可怕的事物面前逃离。

——阿尔德巴兰至今借助权能之力，一直在回避那仅此一次的『选择』的机会。故而，他并不知晓。

每当必须『做出选择』时，若只是被一心想要逃离当下的念头所驱使，那样的选择绝不可能把命运引向光明。

那一点——

「——阿尔大人。」

便由本应是同伴的雅耶・天泽的举动得到了证明：当阿尔德巴兰出于逃避的心态，打算扑向喷烟彼端显现的身影时，她从正面抱住他的身体，将他拦了下来。

212

——在败给雷姆的那一刻，雅耶的『下一场』战斗就已经开始了。

被轰飞出去，沿着冻结大河上凝成的冰山斜面一路翻滚坠落，她干脆连本该做的止血之类的处置都统统放弃，竭尽全力去扮演一个濒死的败者。

这么做的目的在于——

「——我不打算取你性命。那个人，会伤心的。」

当那位说过这话的鬼族少女施展治愈魔法时，雅耶赢下了最初的赌局。

说实话，想起交战中的那份毫不留情，「没有取命的打算」这话从她嘴里说出来也真够可笑的；但既然确实捡回一命，也就无从抱怨。——更何况，要是开口抱怨，难得的机会就会化作泡影。

可惜的是，从此刻起，雅耶想在雷姆面前翻盘的可能性终究不存在。

在最后的攻防里，既然仍未参透雷姆是如何将雅耶那一闪无效化的门道，那么就算偷袭得手，也未必能将雷姆一举斩落。这同样不过是把千载难逢的良机白白糟蹋而已。

因此，雅耶的所图另在他处——是把仅剩不多的全部身心倾注进去的最后一桩效命。

就连雷姆也警惕反击，将治愈魔法的效用压到最低，只把渗血的伤口黏合住，勉强止住通往死亡的倒计时。再加上将毫无反抗之力的雅耶手脚以锁链拘束，彻底到不让她发挥做人质、俘虏以上的任何作用。——然而，即便如此，对忍术的认识还是不得不说太过天真。

只要不是当场即死，哪怕脑袋飞了，忍术也要把活儿干到底——这就是它的行当。

卸下全身关节以脱离锁链，至于濒死的重伤，也能以燃烧丹田而暂且置之不理。

如此一来，哪怕是被托付的一切一件也未能完成的雅耶，也该能在最后的最后，为阿尔做点什么——她是这么想着。

然后——

「———」

——雅耶所瞄准的千载一遇，比想象中更早地降临了。

惊天动地的冲击将阿格扎德峡谷与周遭大地猛烈吞没，天变地异的余波化作暴风、洪水与地震扑面而来，雅耶动了。

他从试图替他挡下冲击的雷姆身边脱身，脱离峡谷，登上崖顶——在那里，雅耶痛感到，包括他自己在内，由阿尔召集来的共犯者们力量不足。

漫卷整条长峡的沙尘遮蔽了视野，阿尔别说抵达摩格阿雷德大喷口了，甚至刚一上去便被敌人堵住了脚步。

这本是只要雅耶、『阿尔德巴兰』、罗伊・阿尔法德、亨克尔，以及阿尔召集的共犯者们各尽其责，就不必承受的劫难。

正因为如此——

「——」

尽管尘烟搅乱视线，地鸣吞没声息，逆卷的风撕碎气味，雅耶仍将五感所得的寥寥信息整合起来，准确捕捉到了该找的人。

恐怕再没有什么比忍术更能在这种局面中发挥到极致。他头一次为自己曾被忍术之里掳走而心怀感激，飒然奔向那人。

这一次，无论如何，都要成为他的力量——

「——罗伊！我在这里！吃了我！把我的『名字』吃掉！！」

——明明想着，必须要为阿尔效力的。

「——阿尔大人。」

她破开弥漫的沙尘，正面抱住了自烟尘中冲出的男人。触及那具身体的热度、重量、鲜活的脉动，雅耶对自己的所作所为由衷困惑。

「——雅……耶？」

被强行拦下而身形前倾的阿尔，侧头望向近在咫尺的雅耶的侧脸，像是看见了难以置信的东西般喃喃道。

他那颤抖的声音里有惊讶与混乱——然而，雅耶亦然。——不，若想起自己就在片刻之前还抱持的觉悟，甚至可以说雅耶比阿尔更为混乱。

「我……」

她大致明白阿尔所处的境地。

他以某种方式被逼上绝路，试图在这场混乱中寻到生机。为此该被利用的是『暴食』，而奔赴粉尘之中的大罪司教身边，才是让阿尔达成目的、也是雅耶所能做到的，最好的、最后的效劳。

即便明知如此，雅耶却仍拦下了阿尔的去路。以身相撞，将他生生阻住。

为什么？她向惊愕的自己发问。——雅耶因为害怕阿尔，所以希望他去死；为了让他去死，才想让他达成自己的目的。然而，如今被逼入绝境的阿尔，也许能由雅耶亲手杀掉。是因为这样吗？所以，她才去阻止阿尔，想让他为令自己品尝到的恐惧付出代价？

「我……」

『——是爱。』

面对冒出的疑问，那位毫不迟疑一锤定音的雷姆身影掠过脑海，雅耶屏住了呼吸。

不对，断然不是。虽说同为想让主人成就其志的女仆，但雅耶与雷姆在根本动机上截然不同，毫无参考价值。

只是，想起那位以近乎荒唐的巨大情感贯彻一念的鬼，雅耶忽然察觉到自己某种心意。

「我——」

雅耶曾盼阿尔去死。因为名为阿尔的怪物让她恐惧到无以复加。

可是——

「——我好像无法忍受忘掉阿尔大人。」

——我并不想永远失去你。

213

「————」

对抱住了自己并说出缘由的雅耶，阿尔德巴兰的脑海一片空白。

我不明白。我不明白。不明白的事，太多了。——阿尔德巴兰的『领域』摧毁了雅耶的心，她本该以我的死亡为条件，成为绝对的协力者。

然而，那份对雅耶的任性信赖，在这最终的关头被背叛了。

难道她一直在伺机，等待着最妙的背叛时刻吗？

我不明白。我不明白。只是，停下脚步的阿尔德巴兰，被追上了——被那道他以为捂住耳朵、移开目光、压入心底深处、却最想逃避的声音追上。

「——且看，又是妾身的胜利。」

「……普莉希拉。」

明明是在这等必须竭力去攫取哪怕一线可能性的瞬间，阿尔德巴兰口中逸出的低语，却不是『暴食』，不是拦住他的那个女人，甚至不是他自己的名字。

在那些该做、该有所为的时刻，他什么都没能成就，让悔恨如灰一般层层堆积成了今日的他。可即便如此，阿尔德巴兰仍旧仰望那座灰之山。

「什么是……」

那就是胜利吗，普莉希拉。

你死了。你已经死了，不是吗。死了，就意味着败北。死了，就意味着愿望无法实现。能在死去之后却不以终结收场的，在这世界里，只有我和菜月・昴。——所以，你并不是那样。

然而，究竟，这算哪门子的胜利。明明是这个世上最不可能说输家嘴硬话的女人，到了最后的最后却嘴硬了吗。

为什么，到了最后，你却笑了呢，普莉希拉。

「星——」

「——啊？」

「是星星的错，阿尔大人……！」

正把心神耗在无解自问上的阿尔德巴兰，怀中的雅耶仰起脸望着他。

她那毫无余裕的声音，以及那句话的内容，让阿尔德巴兰屏住了呼吸。「都是星星的错」这句话，阿尔德巴兰曾反复挂在嘴边，雅耶也都听在耳里。

所以，这是在回敬吗。如今她拦下了阿尔德巴兰，是在拿这句话回敬他——不，雅耶那对赤红的眼睛在诉说，并非如此。

那双瞳中燃起真挚的光，与昔日那位『魔女』同样的光，分明在说。

这不是阿尔德巴兰的错。

「——这不可能——」

「开什么玩笑」，一腔怒火倏然涌起。

眼前的局势、一路至今的种种、走到如今的功罪，统统压在阿尔德巴兰、在菜月・昴身上，绝不可能说成不是我们造成的。

而那一切——，

「——阿尔！！」

连砂尘都无法阻挡的银铃般声音，一瞬间便撕裂了那股骤起的沸腾。

214

艾米莉娅猛地起身，急急一跃冲出峡谷，眼前的景象令她目瞪口呆。

「还以为只是超——大的摇晃，结果……」

铺天的粉尘几乎遮满视野，风啸轰鸣不止。更糟的是，大地的震动非但没有平息，反而愈演愈烈。她昏迷的这段时间里，事态已经变得一发不可收拾。

可她不气馁，不沮丧。艾米莉娅没有垂头丧气的工夫。

「得火速追上阿尔……」

之所以把阻止阿尔的任务交给她，是因为大家都相信，艾米莉娅和雷姆最适合这件事。而雷姆之所以把她送去追赶飞离的阿尔，是因为雷姆对艾米莉娅抱有期待。

背负着这一切，为了救出昴和碧翠丝，她已经卯足了劲，因此绝不能让阿尔逃掉——

「——找到了！阿尔和……咦！？那个孩子！？」

满怀气势地冲入尘幕中的艾米莉娅，隔着飞扬的黄土，看见了阿尔——以及正与他相拥的雅耶，又一次大吃一惊。

本该由雷姆拦住雅耶。如今雅耶却出现在这里，便不免令人担心雷姆——菲利斯口称「只是个小小的咒语」，替她施下了强力的治愈魔法，可即便如此，她的安危仍令人在意。

「马上——」

正要追上去问个明白，她猛地一蹬地，就在那一瞬——在艾米莉娅的视野中，于相拥的阿尔与雅耶的另一侧，拨散粉尘的巨大异变袭来。

那正是始终未歇的足底摇晃、无休无止的大地悲鸣的真相。伴着地面剧烈震颤汹涌逼来的，是海量的突发洪流。

目睹它要毫不留情地将战场，将一切尽数冲走，艾米莉娅不假思索地加快了冲刺的速度，

「——阿尔！！」

他在呼唤中猛然抬头，头盔深处的双眸与她的视线交错。艾米莉娅一跃越过相拥二人的头顶，直面迎上正面扑来的洪浪。

然后——

「——冰柱魔线！」

215

「————」

空气发出尖厉的悲鸣，难以置信规模的冰封朝那股大水铺展开来。

涌来的是——仿佛把一座巨湖当作水桶掀翻倒扣般，堪称神话级的滔天洪涝。银发飘扬的美丽少女将汹涌灌来的洪流所到之处一一迅速冻锁，筑起冰河。

「呀啊啊啊——！！」

然而这不过是冰封与山洪之间一场胜算渺茫的拉锯战。

艾米莉娅释放的冷气将洪水的一部分冻结，下一股浪潮又越过那层冰扑来，她再将其冻结。如此反复，冻结便搭起了一道冰之穹盖，而在穹盖之上，洪流无尽奔涌、铺展开去，化作一片浩大的冰川。

「呜呀啊啊啊——！！」

以散发冷气的艾米莉娅为起点，冰之穹盖自圆心向外扩张，并顺着水势不断壮大，掠过阿尔德巴兰的头顶，终至越身而去。

规模越大，重量愈沉，穹盖开始出现裂纹，那等超重量何时坠落，也只是时间问题——

「————」

刹那间，朝这边瞥来的艾米莉娅，与阿尔德巴兰的目光对上了。

不知心中掠过了什么，艾米莉娅的唇线陡然绷紧——

「喝啊啊啊——！！」

发出嘎吱与龟裂声的冰之华盖得到了加固，明明眼看就要崩落的大冰河的建造仍在继续。为支撑那将坠的华盖，自大地接连伸出的冰柱化作支点，这般别出心裁的巧思——然而，阿尔德巴兰的目光却不在此处。

自称『冰结魔女』，而且事实上也展现出与那名号相称之力的艾米莉娅。可如果说此刻她之所以爆发出超越极限的力量，是因为先前那一个眼色的话——

就像在峡谷里布下巨岩陷阱，又像她护住阿尔德巴兰时那样，这一次的艾米莉娅也是为了保护阿尔德巴兰才动用了力量的话——

这么一想，他这才后知后觉地明白。——艾米莉娅一直都好好地在看着阿尔德巴兰，也试着与阿尔德巴兰说话。

「我——」

嘶哑的声音自喉间溢出，却再也接不下去。

只是，似乎哪里发生了一个巨大、巨大、无法挽回的错位。——在权能被封之前就已经无法重来、无法挽回的，那样的错位。

「——看吧，又是妾身的胜利呀」

赢的究竟是什么呢？这点，到最后也仍是不明所以。

可是，普莉希拉，你就那样说着，得意洋洋地笑着的你，真的——

「——到此为止」

——刹那间，那柄横扫一切的理不尽之铁槌化作光芒，贯穿了战场。

** 『锁链之音』

「利格尔。——我是菜月・利格尔！！」

——那高声张扬、如灵魂嘶吼般的呐喊，罗伊・阿尔法德确实听见了。

那是拼命而绝望、足以击打听者胸臆的情感诉求。若是热爱人类那近乎鬼气森然的激情，以及悲喜交织的迫切渴望的『美食家』莱伊・巴登凯托斯在此，他一定会兴致勃勃地倾听那份愿望，边舔舌边满心欢喜地予以响应。

「可惜，在这儿的不是莱伊，而是我们呢」

『美食家』的莱伊与『恶食』的罗伊，这是一对共享『暴食』魔女因子的双胞胎——严格说来，加上在母胎中夭折的路伊，是三胞胎——然而兄弟间的性情却出奇地不投合。

对于进食究竟看重什么，明明流着同样的血、由同样的骨肉构成，却完全不同。

不过，他们并未为这种食性差异而嗟叹。相反，该庆幸不用兄弟间为同一猎物大打出手。至于无法自由挑选猎物、只能从『灵魂的胃袋』里偷吃的路伊，似乎对此颇感懊恼——

「没办法没办法。我们也确实觉得妹妹很可爱啦。可、可是呢？吃饭这种事是为了自己，去填饱别人的肚子那种巧妙的把戏，我们可做不到呀」

所以，就算可怜那个诉说饥饿的妹妹，那也不过是近在身侧的外人的空腹。

就算被告知莱伊在砂之塔中如烟散去，那也只是身边外人的一场用餐失败。

谈不上幸灾乐祸，也不会为那顿饭的收场而悲叹。心里只浮起一个念头——真是可惜。

「啊，从莱伊的『美食』视角看，我们这些始终挨饿的家伙大概就是落第、失格、被挤出局的废物吧……可作为『恶食』的我们，其实把莱伊吃掉也行啊。」

奇怪的是，罗伊忽然意识到自己竟把莱伊和路伊排除在食谱之外，便觉得好笑——原来自己的家族之爱也不至于一文不值。明明是看见什么就手到擒来、干干净净一扫而空的『恶食』，居然还会挑盘子。

「啊，真是太可惜了啊。」

遗憾的是，莱伊已经死了。路伊也自从在那座砂之塔里度过那段时光之后，『灵魂的胃袋』里再也感觉不到她的存在，不知她落得何种下场。——真的，真的遗憾。要是还能再与妹妹相触，我一定要咬上一口她的灵魂。

「毕竟，我们就是『恶食』嘛。」

不管多么丑陋可憎的东西，只要起了吞噬之心，舌头就绝对忍不住会伸过去。

就算是连『美食家』都懒得瞥一眼、连『饱食』都会把盘子推开的玩意，也要一滴不剩地吞下去。

——更何况，要我放弃那种一旦起了『想尝一口』之心的东西，根本不可想象。

「——！！」

粉尘那头扯着嗓子怒吼的阿尔德巴兰，本该是绝体绝命——不，恰恰相反，被逼得处于与之完全相反的状态，反倒不知为何更像是陷入了绝境。这个时候还能想起罗伊，打算让他吞下『名字』来翻盘，倒也够机灵，让人刮目相看。

为了把对方变成唯命是从的随行者而刻下的咒印——阿尔德巴兰将其激活，拼命呼唤罗伊。那种仿佛连无法触及的灵魂都被火烤般的不可思议之痛袭上罗伊，他的身体抽搐着在地上弹跳。那是以痛相胁——想摆脱这份痛楚就顺从吧——对灵魂施加的虐待。

「懂，懂啊，当然懂，早就说了我懂，我本来就懂，就算说是懂也只能去懂吧！正因为我说我懂！暴饮！暴食！」

你想说什么，我懂。你想让我做什么，我也懂。你被逼到穷途末路，我也懂。

老实说，就算到了魂魄几乎要被灼烧的地步，罗伊仍然在心里感谢阿尔德巴兰。——多亏被他从监狱塔里带了出来，才捞到了一次也许此生再无的进食机会。按人吩咐吃东西他不怎么喜欢，但罗伊的优点就是从不挑食，这一点对阿尔德巴兰来说想必也方便得很。

「不过呀，要是你误会了那可就麻烦了呢。」

因为心存感激，听他的话也不是不行。——可那终归只能在罗伊愿意让步的范围内；若不是那样，就请容他随心所欲。

比如说——

「——找到了。」

他有一种食性：一旦认定了哪怕拿命去换也要吞下的猎物，就必定会把对方吃进肚里。

216

「利格尔。——菜月・利格尔！！」

那几乎吐血般的嘶喊，也确确实实传进了『忧郁魔女』的耳中。

从意识之外汹涌而来的爆风与暴压，给战场造成的破坏极为惨重；在仿佛将大地抹平的冲击波中翻滚，刚刚好容易支起身来的当口——

『——佩特拉！你没事吧！？可恶，这到底怎么回事！？大家都还好吗！？』

即便刺耳的嗡鸣支配着整个颅内，幻影・菜月昴那为这边担忧的声音却不经由鼓膜，依旧清晰入耳。就在那位『昴』因倒下的同伴而困惑忧心之际，传来的，正是开头阿尔的那声叫喊。

———

在如雾般翻卷的沙尘中，『忧郁魔女』吐出闯进嘴里的砂粒，对夹在暴风里的阿尔的呼喊，生出了两重惊异。

其一，是阿尔为打破僵局而选择的对『暴食』权能的运用方式。其二，则是他所高喊为自己真名的那个名字。

菜月・利格尔。——这名字的回响，显然与菜月・昴并非无关。

「若他和昴一样是异世界来客，阿尔德巴兰是化名这一点早就不言自明……」

可在这节骨眼上蹦出的名字却是菜月・利格尔，这未免也太过离奇的暗合了。

利格尔是星名，而『菜月』这一姓氏又与昴完全相同。——难不成，被召往异世界的条件，就是『菜月』姓氏加上星名的组合不成。

『那家伙是……』

理所当然，『昴』也和『忧郁魔女』抱有同样的疑问，皱起了眉头。

阿尔身上谜团重重，『忧郁魔女』她们在与那位下定将全世界为敌之决心的他相对时，对他的本心与真意依旧一无所知。这也同样，是其中一个明证。

然而——

「——抱歉呢。我已经做出选择了。」

在这种局面下，把解不开的谜团摆在首位，『忧郁魔女』可不是那种孩子气的人。

此时此刻最该优先考虑的，并非阿尔新抛出的谜团，而是如何应对那个即便几乎把手牌尽数打光，仍能翻盘的阿尔。

阿尔那让人『吞下』自己『名字』的策略，一旦付诸实施，便无计可施。——雷姆被遗忘，又被想起，这一点已足以证明其效力。

「所以，要上了，昴。」

『忧郁魔女』低声呢喃时，『昴』并非在侧，而是立于正前。不是漂浮于空，而是双足踏地，他正面与这边相对。

『――――』

直直凝视那双黑色的眼瞳，『忧郁魔女』心中泛起一缕奇异的感慨。

在这里的他，无论怎么挣扎也不过是按自己愿望所见的幻影，绝不是货真价实的菜月・昴。对外人而言，这无疑是一场滑稽的梦；对『忧郁魔女』来说，也不过是最合她心意的虚妄罢了。

「可你还是不会和我结婚，对吧」

『佩特拉，我……』

「骗你的骗你的。只是想让你为难一下的魔女玩笑」

她轻轻吐了吐舌头，向被自己逗得为难的『昴』道了歉。

对于眼前这个不肯对自己言听计从的『昴』的存在，『忧郁魔女』干脆把它当成自己情感高洁的证明，甚至感到几分自豪。

心上人能如自己所愿，固然令人欣喜，却也复杂。

「因为我喜欢上的，就是那个让我明白自己是个笨蛋的昴啊」

『……那可真是我的荣幸。我这家伙，是个幸福得不得了的大笨蛋』

「——这话真没错」

听到『昴』对她的告白如此回应，『忧郁魔女』唇角绽开笑意。随即她在原地轻轻一转，把背脊交给了『昴』。

一拍之间，也许是思索，也许是犹豫，随后，『昴』从背后抱住了『忧郁魔女』。

这在期待也好、愿望也好，都是满分。而且，就算那不是幻影而是真正的昴，他也一定会这么做，因此也不会影响『忧郁魔女』的打分。

所以，就这样被那双臂抱在怀里——

「——找到你了。」

伴着那黏腻的声音在近旁响起，威胁从喷烟的另一端逼近。

那是循着『忧郁魔女』举向头顶的指尖——从那里放出的白光为标记，猛然赶来的『暴食』的大罪司教，罗伊・阿尔法德。

龇牙的罗伊同『忧郁魔女』的视线交错。

「——佩特拉・鲍曼哦。」

手指仍指向天际，『忧郁魔女』自报其名。

作为对付『暴食』的对策，『阿尔德巴兰之刃』进行了名字的洗牌——在领主罗兹瓦尔的协助下，那被作为具有正式效力的改名之仪而获准。众人各自自由选择名字之中，『忧郁魔女』取了自己最敬爱之人的姓氏。

然而，此刻揭开那一直隐藏至今的改名之名，其意无他——这是她的底牌。

「——佩特拉。」

在那无法触及的手臂中，昴依然收紧了拥抱的力道，呼唤着她。听到那声音，她也将手覆在同样无法触及的手臂上，『忧郁魔女』微笑起来。

含笑着，献上一切代价成为『忧郁魔女』的少女开口道。

「——昴，我最喜欢你」

217

将之置于舌上，发动『蚀』，在吞噬的瞬间渗透全身的充足感令他浑身战栗发麻。

「～～！」

这种『蚀』的绝顶感，正是就连至今吞噬了无数『名字』与『记忆』、贪婪掠食他人一生的罗伊也想不出任何替代之物的『暴食』醍醐味。

饥、饥、饥到过头的饥饿感，正是以此为存在理由的『暴食』。——在那连碎片都仿佛被填满的错觉刹那，便能不可遏止地感到生命的充盈。

那正是——、

「——极上！」

信守约定的『魔女』之味，以至大的爱意令罗伊沉醉，他在余韵里舔舐着唇瓣。

被超出期待的情感、超出忧惧的强烈、超出所望的纯真所俘获，罗伊在逐渐浸透全身的饱腹中，尽情体味何谓真正的『蚀』。

的的确确，的的确确，的的确确的确确的确，他就是为这一味而活。

——即便因破除咒印的代价而灵魂灼烧，对这次『蚀』也绝无悔意。

在涌入的『记忆』中，路伊渴望的理由被清楚揭示。然而，遗憾的是，与妹妹不同，让罗伊的味蕾感到最为甘美的，是少女的祈祷。

那位对仅仅一盘菜都爱到如此地步的『魔女』，她在尚未入口时的期待，已被漂亮地超越。

于是，『暴食』的大罪司教罗伊・阿尔法德嗤笑了。

在被作为破除咒印之证的青色火焰灼烧之中，他仍在嗤笑。

——「承蒙款待了！」

而在连灵魂都将被那青之火焰烧尽的瞬间——

——「到此为止。」

骤然在战场上腾起的猩红烈焰，毫不留情地一掠而过，将那抹青焰斩断。

218

——提到『剑圣』莱因哈鲁特・范・阿斯特雷亚的代名词，理所当然，首先浮现的便是『剑圣的加护』。

然而，对莱因哈鲁特那份非常识更为了解的人都知道，他所拥有的数多加护，也是让『历代最强的剑圣』之名广为人知的原因之一。

过去，当他与史上最强者之一——『强欲』的大罪司教雷格鲁斯・柯尼亚斯交锋时，身处其侧并与之并肩作战的菜月・昴，曾在莱因哈鲁特无数加护之中，尤其将『不死鸟的加护』评为离谱到超规格的存在。

毕竟，单凭其压倒性的实力，要想哪怕仅仅夺走他一次性命都已困难至极，更遑论还能在死后再次复起的『不死鸟的加护』——这等力量，简直就是犯规。

然而，那令菜月・昴无语并断定为外挂的『不死鸟的加护』，若是知晓其真正的超规格之处，他的评价只会更加被颠覆。

——『不死鸟的加护』

由于在与那位『强欲』大罪司教的战斗中曾发动过一次，严格来说，此刻这一枚已是后来新赐予的下一枚『不死鸟的加护』，但两者引发的现象并无二致，区分与否毫无意义。

重要的是，这份加护一旦发动，作为加护持有者的莱因哈鲁特・范・阿斯特雷亚失去的性命将会复归，同时包括致命伤在内的一切伤势悉数痊愈。

因此，这一刻，为了在世界走向灭亡的边缘将其拦下，莱因哈鲁特与『嫉妒魔女』的残影鏖战三天三夜所背负的一切创伤，都被一笔勾销。

其中也包括阿尔德巴兰与『神龙』合力施加于他、令其双臂报废的重创，甚至连不眠不休持续作战累积的疲惫，亦被活力之炎尽数焚尽。

仅此便足以证明『不死鸟的加护』的力量有多么超规格，然而莱因哈鲁特倚仗这份加护的真正价值，还在后头。

因阿尔德巴兰所布下的不知何种机关，复归现世的『嫉妒魔女』之威胁。与其现身时一样，在那股威胁骤然消失的瞬间，莱因哈鲁特判定战斗已然终结——并立刻作出对自身施加致命伤的决定。

如果他的目的仅仅是治愈伤势，莱因哈鲁特大可不必自伤，只需等待伤口自愈。

也就是说，他向『不死鸟的加护』所求的并非疗伤，而是这道加护的另一重效应，那就是——

「——」

——披覆真红之炎，刹那之间，莱因哈鲁特在战场正中央复生。

这正是不死鸟的加护所拥有的超规格效能之一——以复活之炎，将殒命的受护者于其所愿之地再度降生。

与雷格鲁斯・柯尼亚斯交战时，这股力量曾让他在并肩作战的菜月・昴眼前复起；而此刻，莱因哈鲁特复生的所在，自不必多言。

在那位应当正为他收拾残局、与阿尔德巴兰交战的主人的身旁。

「——」

自逆风翻卷的火焰中现身战场的莱因哈鲁特，一眼便看出此地已是天变地异笼罩下的异常空间。

即便是莱因哈鲁特，见到那一幕也不禁为之一惊——

「莱因哈鲁特！」

被突如其来的呼唤唤回身的莱因哈鲁特，看见了那位以娇俏容颜承载着拼命决心的友人，以及被那位友人抱在怀中的君主人——菲鲁特。

他一眼便明白事态非同寻常，情不自禁想要冲到主人身边。被友人菲利斯环抱着的菲鲁特低垂着头，浑身无力。世上再没有比菲利斯更合适的人选了，但他至少想开口唤她一声——

「——喂。」

「———」

还未等莱因哈鲁特踏出一步，那道虚弱沙哑的声音便先吐露而出。

飞尘之中，菲鲁特被菲利斯所散发的淡淡光辉包裹——治愈之光集中洒在她的头部。她缓缓抬起脸庞，焦点屡次涣散，却仍以那双赤红的瞳眸锁住了一之骑士。

随后，她将全身的力气不遗余力地聚拢，只化作一句话。

那是——

「——剩下的，交给你。」

这一句话，让莱因哈鲁特明白自己此刻该做的，并不是为主人担忧。

莱因哈鲁特的主人很强。甚至，比莱因哈鲁特更强得多。

因此——

「——到此为止吧。」

将已尽其所当尽的主托付给友人，在那声嘱托的推动下，莱因哈鲁特奔赴战场。

刹那间，他把握了散布在一带的气息所在，从中直取必须应对的敌人所在，将被青色火焰包裹的『暴食』罗伊・阿尔法德一闪斩杀，从这世上抹消。

「——多谢款待了！」

那样嗤笑着的罗伊・阿尔法德所燃烧着的，是以他的灵魂为火种而燃起、决不熄灭的青色火焰。故此，为免他长受折磨，莱因哈鲁特出手予以介错。

然后——

「——阿尔阁下，这一次，我一定会拦下你。」

面对立在砂尘中的阿尔德巴兰，莱因哈鲁特猛地蹬地跃起。那是不借助『压缩』之力，也像将空间碾碎般的瞬速动作。

霎时，一个少女张开双臂挡在莱因哈鲁特与阿尔德巴兰之间。红发的少女以最快的速度冲上去想要庇护阿尔德巴兰。转瞬之间，快得不容反应，莱因哈鲁特的手刀击中她的颈侧，顷刻便夺去了她的意识。

随即，面对变得毫无防备的阿尔德巴兰，莱因哈鲁特再度收臂——

「——那是我的职责。」

——刹那间，『剑圣』动真格的一击击中了阿尔德巴兰的躯干。

219

远处，砂尘彼端的青色火焰四散。而在意识到那一点的下一瞬，眼前便是雅耶那纤细的背影崩然倒下。

情急之下伸手去接住倒下的她，是出于怎样的心理驱使？无论如何，阿尔德巴兰的手都没有碰到她。总是这样。

接着，连眨眼的空隙都没有，一道白光横扫阿尔德巴兰的躯干——

「——呃」

确实，腰间被手刀一闪，阿尔德巴兰被劈成了两截。

然而，从被劈成两截的瞬间起再生便已开始，以宛如录像倒放般的速度，阿尔德巴兰的肉体复原，被斩断的躯干立刻修复。

那是由加诸阿尔德巴兰身上的『青』之治愈魔法的非凡威力，和远胜寻常名剑的『剑圣』手刀锋芒，共同实现的人体切断魔术。

然而——

「死不了……！」

这声诉说，究竟听来是肯定还是否定呢。

莱因哈鲁特的一击——没错，是莱因哈鲁特。那个明明不惜召来『嫉妒魔女』都要让其无力化的他却现身了，手刀也毫不留情地斩下，然而，还是死不了。

既然把躯干斩为两段，莱因哈鲁特理当是抱着杀死阿尔德巴兰的意图出手的。可是，『青』的治愈术甚至凌驾于那位『剑圣』的杀意之上，阻止了权能的发动。

「——」

把那一瞬间几乎让人怀疑是否存在的疼痛抛在一边，阿尔德巴兰开始思考。

莱因哈鲁特在这里。不妙。糟了。一切都会化为乌有。而他出现在此地，若不是意味着他已弃世界于不顾，那就说明『嫉妒魔女』已经退去了。

而『嫉妒魔女』一旦退去，就再没有杀人灭口的理由。——也就是说，罗伊违背了咒印的誓约，把权能用在了『忧郁魔女』身上。他明知那样做的惩罚要以性命来偿还。

大罪司教为了报复被强行逼迫，竟连命都抛了出去吗。可以确定的一点——阿尔德巴兰以自己的所为，亲手断绝了打破这局面的可能性。

「——ッ」

『暴食』这一可能性，从指缝间滑落。

认清这个事实，阿尔德巴兰咬紧牙关，让思绪电光火石，自此刻起将之后的一切行动，尽数用来破局。

无论是呼吸与心跳，还是自指尖滴落的每一滴汗，都不容有丝毫浪费。

在灵魂深处如此严厉告诫自己，阿尔德巴兰一把搂住了将要倒下的雅耶。——搂住……雅耶？

「——啊？」

就在方才，阿尔德巴兰才刚刚确定了自己该做的事。

明明下定了决心，从此刻起连刹那的刹那都要用尽来挺过这场意外，可为什么还会伸手去抱起雅耶？

她已经失去意识，绝无可能是在拿手的装死。就算把雅耶抱起来，也无法打破眼前的局面。

可就是这样，为什么，阿尔德巴兰却——

「你也明白的吧——到此为止了。」

在不明白自己举动意义、呆立当场的阿尔德巴兰耳边，响起了莱因哈鲁特的声音，那声音健康平静，叫人难以相信他方才还与『嫉妒魔女』死战不休。

到此为止吧，放弃吧，莱因哈鲁特轻描淡写地这么说。

说得，倒是轻巧。

「是啊，『剑圣』你大概也背负了不少东西……可我也不是抱着那种随随便便、说放就放的廉价觉悟才开了这个头的。」

「――――」

「还、还没完。就这点儿……就这点儿！别以为我会自顾自地认输！」

虚张声势地吼着，阿尔德巴兰死死瞪向莱因哈鲁特。

哪怕只是想在气势上压过对手，也好让自己抓住哪怕一个可供着力的支点。可面对阿尔德巴兰这股气势，莱因哈鲁特只是举起方才挥出手刀的那只手，予以回应。

方才将阿尔德巴兰劈成两断的『剑圣』的手刀，正紧紧攥着某样东西。

——那是本不该存在于此、由魔法编织的黑色球体。

「这样如何？」

阿尔德巴兰瞪大双眼，哑口无言，这才明白过来：先前『剑圣』那一闪的目标并非他的性命，而是确确实实要将他的躯干斩为两截。

莱因哈鲁特是有意为之。——相信『青』的力量，照字面把肚子剖开。

劈开阿尔德巴兰的腹部，把它取了出来。

本该把它丢进摩格阿雷德大喷口，扔进那通往世界彼方的洞穴之中——，

「可是啊，裂不开啊！！」

冲击传不进去。即便如此，主导权还在我们这边。

那是『魔女』所创的、能确实封住受魔女因子赐力之物的禁术。就算是莱因哈鲁特那夸张的怪力，哪怕是足以毁灭世界的『龙』之吐息，也破坏不了它。

而且，无论发生什么，阿尔德巴兰都不会去解开那道封印——，

「不，这里被封着的是昴吧？——那样的话，就拔得出来。」

刹那，异乎寻常的力量奔流而出，令大气战栗，令世界确确实实地一阵发抖。

其重大到如此地步：那把剑被拔出的瞬间，已是连世界本身都无法无视的大事。

那正是——

「——『龙剑』雷德。」

不应存在的光芒一闪，将『剑圣』手中的小小魔玉斩为两截。

220

『——谁都赢不了我创造出来的你』

将阿尔德巴兰命名为『尾随星』，并把一切都安排好的『魔女』如此说道。

『——看吧，又是妾身赢了。』

赋予阿尔德巴兰除『尾随星』之外意义的『太阳公主』如此说道。

「――――」

愚蠢而无力的阿尔德巴兰两者皆失，明明是个拥有得以纠正错误选择之权能的存在，结果却始终走在最半吊子的道路上。

只是不让终结世界的『魔女』诞生。——他的一切步履，皆为此。

接受了『魔女』的教诲，依其所愿去杀『魔女』。——失败了。

与普莉希拉相遇，试图让她成为王以此杀死『魔女』。——失败了。

回归初心，企图通过除掉菜月・昴来杀死『魔女』。——失败了。

「——啊」

炫目的光芒汹涌迸发，即便隔着铁盔也仿佛有双眸被灼烧之感，阿尔德巴兰注视着眼前以蛮力强行缔造的奇迹，目睹那股超乎常理之力的结果。

由理外之力引发的事象，又被同样的理外之力斩断并封缄；当那层封缄被解开之时，阿尔德巴兰所能做到的，就只有像发起癔症般，死死地、一次次收紧抱着那具纤细身躯的双臂。

于是——

「——」

一缕本不该听见的、微弱的呼息，划过阿尔德巴兰的意识。

那是来自后方的——那名银发少女的呼吸。她挥洒力量，对抗汹涌而来的洪水，以骇人的寒气，阻止战场被浊流吞没。

若那是一声无力回天、被洪水压倒的哀叹，他还能承受。

若那是对莱因哈鲁特登场而释然的吐息，他也还能承受。

若那是对可恶的阿尔德巴兰被逼入绝境的称心之叹，他也还能承受。

可是哪一样都不是。——她那紫紺色的双眸注视的，只有一个人。

因为阿尔德巴兰从来都映不进她的眼里。

「菜月・昴——！！」

咆哮。呼喊。嘶吼。

阿尔德巴兰用仿佛吐血般的嘶哑嗓音，叫出了那个名字。

从光芒中跃出的，是怀抱身着礼裙的大精灵的黑发少年——那绝无可能是旁人的那个人，借着自黑色球体中解放的余势，单膝着地。

然后，唇瓣张开，脱口而出的第一声便是——

「——雷姆！！」

仿佛回应那声呼喊一般，锁链的响动刺穿了阿尔德巴兰的鼓膜。

221

——雷姆爱着菜月・昴。

这已是不容动摇的事实；就算是在完全取回『记忆』之前的雷姆，也不得不勉勉强强承认这一点。

不如说，无论有没有『记忆』，雷姆会被昴吸引都是必然。说实话，也不明白她到底在忍什么。

「不，不对。你那样说也未免想得太开了……首先，照那种说法，就算那个人什么都没为我做，我也会喜欢上他，不就成那样了吗？」

雷姆觉得，自己的感情没那么方便得合人意。

相反，在她看来，自己是个难相处、疑心重、不会轻易敞开心扉的女人。连她自己都为此发怵：我居然是这么一个让人难以亲近的姑娘。

这和坦率又慈悲的拉姆，和嘴上刻薄却把真心写在脸上的可爱卡秋娅，简直天差地别。

没错，『本来的』雷姆，是个难以接近、态度又差的性格丑女。

视野与世界都很狭窄，只顾着守住那片有限的自我圣域，已是分身乏术，离体察周遭的体贴也很遥远。——可即便如此，菜月・昴还是闯了进来。

闯进来，踏得一地凌乱，牵起她的手，把她带了出去，于是雷姆便对他死心塌地。

而被他变成那样的，或将要变成那样的，今后只会越来越多。

「但就算如此，其中最先变成那样的，是雷姆，这一点不会改变。」

最先懂得菜月・昴之好的人，是雷姆。

艾米莉娅也许能打成平手，但论深度与分量，就请允许雷姆坚持自己才是第一个。这同样是无可动摇之事。——关于菜月・昴的，重要之事。

「宅邸、王都、弗琉盖尔大树。」

那是失去『记忆』之前，爱着菜月・昴的雷姆与他一同走过的路。

「密林、城郭都市、帝都与连环龙车。」

那是失去『记忆』之后，开始去爱菜月・昴的雷姆与他一同走过的路。

「以往、此刻、与未来。」

而在如今取回『记忆』之后，重新爱上菜月・昴的雷姆将与他继续踏上的路。

把这一切都用一句『爱』来概括，未免太过粗暴——就算不用雅耶一再提醒，这点雷姆当然也明白。

即便如此，若要问究竟是什么在驱动着她，使她能斩钉截铁地说无论发生什么都绝不后悔，这份希望的原动力，终究仍只会想到『爱』。

正因为爱，雷姆才能相信菜月・昴。

正因为爱，雷姆才能为菜月・昴竭尽所能。

正因为爱，雷姆才能盼望与菜月・昴拥有同一个未来。

——雷姆姐姐，我只想问一个问题。

那是她在奔赴战场之前，与一位同样爱着菜月・昴的少女之间的对话。

她也因与菜月・昴相遇，而偏离了『本来』的人。她将此视为幸福，决心与他一同踏上荆棘之路。

她明知那双眼睛笔直注视的并非自己，即便如此，仍无法不渴望那份充满爱意的目光能转向自己——她就是这样的人。

雷姆姐姐，为了救昴，您什么都做得到吗？

事后，雷姆曾想过。

要把那样的问题说出口，究竟需要多大的勇气。

而要把接下来准备好的话语传达出来，又经过了多么深思熟虑。

倘若雷姆回以不合所望的答复，那位少女又打算背负着多么沉重的觉悟与理想，独自一人踏上那条路呢？

「是的，当然。——因为我是昴君的雷姆啊。」

也正因此，能毫不迟疑地作出那样的回答，于雷姆而言是无可替代的骄傲。

可以说，那是一场关于对菜月・昴的情意究竟有多深的比拼。也是一份绝不能托付给旁人的隐秘誓约——至少，绝不能托付给那位受他青睐的艾米莉娅。

达成那份誓约之后会发生什么，雷姆其实并不清楚。

她所知道的，只是那将会成为对菜月・昴的助力——不，正好相反才对。是菜月・昴、那个心地温柔的少年，今后要背负起的无数思念，而她能成为其中的第一个。

再求更多便是奢望。可自从『记忆』归来，变得贪心的自己，明知那是奢望，还是忍不住想把心愿向前再多伸出一寸。

譬如说，当那个被雷姆她们从背后推了一把的少年走上那条路时，能想起雷姆与那位少女的奉献，在他胸中，不必多，只要比细碎涟漪更大那么一点的波澜泛起。

唯有这个，就是雷姆的——

「——雷姆！！」

隔着白光，当那道身影显现的一瞬，雷姆那点惹人怜爱的感怀应声粉碎。

刹那间，内心无尽涌起的情感洪流将她翻卷摆布，雷姆情不自禁地几乎要把一切都抛开，奔进那怀抱。她忍住了。

紧接着，被鞋底牢牢踩实的大地轰然爆裂，隆起的岩壁几乎要席卷视野——然而，身上仍留有火焰余韵的『剑圣』一记挥斩将其尽数横扫，前路豁然洞开。

笔直，一线相连，雷姆与那令她怜爱的少年的视线贯通。

「————」

与那抱着必死决心、却依旧掩不住与生俱来的温柔的少年对视，他的黑瞳与她的视线交错。

将想说的千言、欲诉的万念、欲奉上的亿万祈祷尽数咽下，雷姆说道：

「请再一次，让现在的我……让雷姆，重新去爱你吧。」

刹那，她倾尽全身力气挥臂——铁球笔直、如一条直线，破空疾驰。

222

——传来了锁链的声响。

就在那一瞬，自己几乎吐血般的惨叫也好，在忘我之际释放的极大魔法令大地隆起也罢，『剑圣』挥出的至高的一闪斩断冻结的空气、甚至连天变地异都被其抹消也罢，抱着精灵现身的男人似乎以『强欲』的权能掌握了局势也罢，乃至他不由自主将怀中发烫的女子抱得更紧也罢——这一切，对阿尔德巴兰而言统统都无关紧要。

只是拼命地想伸出手。——不，应该说是试图伸手。却做不到。

右臂正抱着那个背叛他的女人，失去的左臂则连同『魔女』的期待一并遗落在了那个时代，阿尔德巴兰伸不出手。

取而代之——、

「——阿尔。」

他听见那位吸引了在场所有目光的男人注视着自己，呼唤着。

那双黑瞳里寄宿的情感，那位菜月・昴仿佛连阿尔德巴兰也、若能做到便会去拯救的那种颜色，最、最、最——、

「我最讨厌，混账——」

——锁链响了。

223

——我爱你。

** 『——不是』

——我爱你。

224

——深深吐出一口气，在心底，拉满名为觉悟的弓弦。

「————」

刚才与我来往的那些少女们，尤其是佩特拉的体贴，让我胸口发疼。不怎么坦率的孩子们——摆出『艾米莉娅酱』式态度的梅莉，做派干脆得近乎『生意经』的菲鲁特——也都以那样的方式在为我着想。以碧翠丝为首，身边还真是聚齐了一群好幼女。

「不愧是所谓的『幼女使』啊。对谁来说都不算光彩。」

刚开始这么叫也就罢了，佩特拉她们也不会一直年幼。只要我还带着永远年幼的碧翠丝，这个外号恐怕就很难从我身上摘掉。当然，要是和碧翠丝闹翻了那就另当别论——

「要是我做得到就好了啊。」

按理说，这个计划本该能以更低的难度实现。

事实上，除了碧翠丝，我从未见过对人类友好的阴属性大精灵。也正因如此，我才觉得她是被『设计』出来的存在。至于与我所知的那位『魔女』不同、另一个『魔女』系谱的意图究竟为何，我并不清楚。

无论如何，身为阴属性专家的碧翠丝，连同她的出身在内，都有可能识破计划中不可或缺的要素。因此，时机至关重要。

就连通过契约与对象的灵魂相连的碧翠丝，也必须用禁术一并纳入。

「——」

伴着咯吱作响，能清楚感觉到弓弦正一点点绷紧。

随即，踏入那无论多少次目睹都令人震撼的景象——在广阔的楼层上，被装满海量书籍的书架彻底填满的『塔吉忒』书库——看见了。

「木拉库」

在大精灵的万全支援下，以短短的咏唱便发挥出最大效果的那个男人，轻巧一跃登上高耸的书架顶端，将一本书悄然藏了进去。

「——」

远远望去虽能看出是本书，却看不清那是题着谁名字的书。

这座书库里的『死者之书』除了标题外，外观全都一模一样，连厚薄也没有区别。细想之下这实在古怪：五岁便病倒夭折的孩子，和历尽波折、百岁而终的一生，怎么可能写成同样厚度的书。

这里无疑是一座利用了欧德・拉格纳性质的书库，但将其以书的形态输出出来的，应该是『魔女』。

既然如此，『魔女』为何还要特地打造一个让人摸不着头脑的书库呢。

「不想在那份拿起时的只此一度的邂逅里，混入多余的杂音嘛。」

像是『魔女』会说的话，把这话亲口说出口后，竟愈发觉得它或许就是答案，这让我心里很不是滋味。

明明我一直尽量回避去想起『魔女』。——可自从她死去之后，仿佛反弹般，我反而更频繁地想起她。

「——谁也赢不了我创造出来的你啊。」

我一瞬间想到：如果这里真是收纳着将死者一生编成书的书库，那么，『魔女』的书当然也会在某个角落吧。

然后——

「——看吧，又是妾身赢了。」

那道让我捂耳避目、用灵魂去拒绝、拼命远离的声音……她的『死者之书』也同样会在这里吧。

「……到底赢的，是什么啊，普莉希拉。」

在那难以忘怀的最后、与她的临终对话中，她露出了胜利者般的笑容。伴随着那笑容宣告的胜利，其含义至今我仍不明白。

就算弄明白了也无济于事。毕竟她已经不在了。与亡者，已无法再交换言语与心意。

然而，哪怕只是单方面的，也能让理解成为可能的，正是这座大图书馆普雷阿迪斯。

「……我是在犯蠢吗。不，对，我就是蠢。那不过是个借口罢了」

一切都是为了计划——为了让与『魔女』的计策，那份曾经一度放弃的谋划得以成立，而预先编造出的、好让那些男人来安抚自己这副伤心模样的掩护之词。

却偏偏会被它动了真心，这可就不是『捉木乃伊的人反被裹成木乃伊』那么点事了。

更何况——

「别救我」

一旦把那本书读了，一旦再次被那颗早已沉落的太阳的耀眼所灼烧，自己或许就会像放弃『尾随星』的那一天那样，再度动摇。

那颗不值得被拯救的愚蠢之星，又要重演一遍。

所以——

「——都是星星的错啊」

用这句话让自己死心，重新迈开停住的步子，继续在书库中前行。

书架上悄然藏着的一册书，标题看不清楚；可它以谁的名字为题，不看也明白。

如果说那家伙鬼鬼祟祟、觉得对自己不利而藏起来的『死者之书』有一本的话，那它的标题只可能是一个。——而把那本书找出来，也同样是让这份计划得以实施所必不可少的一枚拼图。

要找的两本书——我和那家伙的『死者之书』——已经找到了。

那么，接下来就是动手的时刻——

「真是的，活像在图书馆里搞事的小捣蛋啊……」

我这样嘟囔着，慢慢朝那个正挠着头的男人背后走去。没察觉我靠近的他，一边从刚把书藏好的书架前离开，一边自言自语：

「要是被探究心的化身艾莎小姐发现就糟了……不如说，今后也有可能会陆续有大批人进进出出，要不要干脆全都处理掉？一共多少本——」

「——处理？处理什么啊，兄弟？」

「——」

我在他嘟嘟囔囔的背后开口的瞬间，他夸张地一抖肩。慢慢回头望向我的男人，表情微微发僵，明显是干了什么心虚的事。

对于这种不擅掩饰的反应，我故意夸张地耸耸肩，

「喂喂，你也太容易受惊了吧。我不过随口搭了个话而已。」

「……啊，抱歉抱歉。自言自语被人听见，挺尴尬的吧？」

「这心情我不是不能理解，但要因此把我当坏人可就不行了，懂吗。」

「坏人……？」

我朝歪着头的他下巴一抬，把他的注意力引向身后。只见那边伴着哒哒可爱的鞋音，碧翠丝正走了过来。

她用那小小的身子插到两人中间，鼓着腮帮子，

「喂，你，不许突然把昴吓一跳。在贝蒂看不见的地方，昴就是那种心脏像跳蚤一样小的家伙吗？」

「跳蚤的心脏……兄弟他？我可不觉得他是那号人。」

「要是这是基于我厚脸皮、不要脸的评语，我也乐意照单全收。可你看见了、知道了我哪一点，才会这么想？」

「——是啊。嘛，说不定我知道的，比兄弟你以为的多得多哦？」

对于那男人一边拍拍为昴出头的碧翠丝的头、一边说的话，略一思量，也只是给了个不痛不痒的回答。

要是此刻把话题再往外扯，说自己连来到这个世界之前，与父母之间那点微妙的错位和自卑之类都知道，他会作何感想呢。

当然，不会做那样的蠢事。那种冲动上头的时刻并不是没有，但每一次都拨弄着头盔的金具，把它硬生生压了下去。

那是沉思时的叮当一响，是告诫自己别忘了计划的金属声。

「真是意味深长呢。居然敢在贝蒂前面说自己对昴很了解。你也把精灵和契约者的甜蜜关系看得太轻了吧。」

「真是甜得发腻呢。唉，打扰你们热乎乎的蜜月，真是不好意思啊」

我一边咔哒咔哒摆弄着头盔的接缝，抱着手臂的碧翠丝已是大为恼火。为了不惹她更不开心，我耸了耸肩，对面那人笨拙地用指尖挠了挠自己的脸颊，

「不，别在意。我跟碧翠子只要有时间就会腻在一起嘛。现在那个，怎么说来着，这边的书库才是当务之急，对吧？」

「多方照顾，谢过，だ。不是开玩笑的，让我郑重道个谢。哪怕只有三天，为了我挤时间也该挺辛苦的吧。碧翠子酱也是，让兄弟陪你一块来，真是抱歉。能一起来，谢谢你啊」

「贝蒂和昴是一体的，所以在一起是理所当然的，かしら。——还有，贝蒂可没慈悲到会一而再地重复同样的提醒，给我自己改过来哦」

「明白明白。——你家姑娘真温柔啊」

「嗯，是啊」

那男人含糊地苦笑着，碧翠丝轻轻握住了他的手。

不知为何，话头并不热络。要说一呼即应，听上去像我和对方很合拍，这并不让人高兴，但我们之间的对话接球至少一直都能配合得很有节奏。如今会这么生硬，是他以为我看到了什么对他很不利的东西吗。――还是说，他把一本与我预想不同标题的书藏了起来。

比如，那可能就是我方才在脑中浮现的两本书中的其中一本。

「阿尔，那个，情况怎么样？」

「――。什么啊，你那问题，活像个拿不准怎么把握和青春期孩子距离的家长。……如你所见，毫无成果。我还以为三天就够，但这阵仗还是让人犯愁。这书的数量，搁M里都属于在沙漠里丢一根针的级别吧？」

「――但是，别放弃。好好找下去！我也会帮你的！」

「喂喂，兄弟？」

正这么想着，眼前的人忽然猛地前倾扑上来的气势，逼得我不由得向后一仰。

说要出力相助，他一遍又一遍，以不变的诚意向我起誓。那话不是谎言，这件事本身我也不觉得可气。――毕竟，我根本没抱期待。

我最期待的、最希望他去做的那件事，他没有做到。

所以――，

别拿出那股让人都分不清到底是谁想来的气势了。这样下去，我也得像你这兄弟一样火气腾腾，才算说得过去啊。

就变吧。一起变，拼了命地。三天，全力以赴干到底。那样的话——

声音在发抖。——不是我，而是听见对方的声音在发抖。

或许是入戏太深，或许是自以为已然退去的浪潮又折返，情感再度翻涌。惋惜与懊悔，他感受到的远胜于常人。这一点我明白。

那是我与这个男人，世上唯二所共有的，名为『权能』的诅咒。

只是因此，那里站着能以此拯救所爱之人的他，和做不到的我。

而若是继续纵容那份爱的延续，终会诞生——足以终结世界的存在。

为了阻止这一切，至少，我也要履行『尾随星』的使命——

——昴。

握着那低头、声音颤抖的男人的手的碧翠丝，静静地呼唤了那个名字。

那声呼唤所蕴的情感宁静安详，与她可爱的外表相反，透出一种仿佛在昭示她亦度过漫长岁月的大精灵之威，神秘而庄严。

——

面对大精灵的呼唤，当事人却屏住呼吸，半个字也说不出来。

见着那反应，我又用指尖拨弄起头盔的接缝，作下决定。——再来一两句言语的往复，便动手。

对方说得没错，在这座塔里搜寻书库的期限是三天。日程被一点点消耗，脑子便会开始转向别处。因此，要在那之前动起来。

「——三天，这还不行吗？」

男人像是从喉咙里挤出来的话，不知为何听上去带着一种攀附不放的恳切——或许也是我这边同样变得神经紧绷的明证吧。——我略一沉吟。

三天，照对方的话去找『死者之书』，如果万一找到了，将那位消失的女人临终所遗的心念，一丝不漏地知晓了的话，会怎样呢。

我可以笃定地说。——什么也不会改变。

这道伤不会痊愈，痛也不会消失。我本就不愿那样。

所以，对于对方抛来的提问，明知这会是南辕北辙的答复，我仍旧刻意这样回道。

「——都是星星的错啊。」

连我自己也不明白，那句「星星的错」，究竟是以褒抑还是以贬抑的目光说出的。

此刻在场的，是两颗星：普雷阿迪斯与阿尔德巴兰——不，昴与利格尔。把它们硬生生对照在一起时，我究竟是在责谁为恶，又在宽谁无辜，连我自己也说不清。

「——」

我变得太过感伤了。这次对话的来回应对拙劣，归根结底我也一样。

照那样继续你来我往，被牵着鼻子走下去，我这边也很可能说出让人起疑的话。已经决定了。下一次就动手，就这么定了。

等对方噤口不语之际，等那个被赐予星之名、又给他人冠以星名的男人把下一句话说完的瞬间，发动。——让玛纳流经门，编织术式，开启禁术之门。

然后——

「——阿尔」

我与一张几乎要哭出来的脸对上了视线，那是菜月・昴。

「——奥尔・纱幕」

那不是我的咏唱。——我明白了。

阿尔德巴兰在一场非赢不可的战斗中，又一次败北了。

『——看吧，又是妾身赢了』

那位让人怜爱的女子，那再也无法挽回的、得意扬扬的笑容与声音传来。——下一瞬，阿尔德巴兰的世界陷入黑暗。

225

「——菜月殿，虽说这话也称不上安慰，但你的忧虑确实应验了。他在凝炼玛纳，编织术式。只要差一步，立场就会逆转。我完全站在你这边，认定你的判断是最善的。」

将全部经过尽收眼底的小人族——艾莎・卡德纳的那番话，正如他自己所说，确实起不到抚慰昴内心的作用。

难道就没有别的、可以不让任何人受伤就能了结的办法吗。

「老大，这玩意儿我可不懂啊。只是、只是啊！就算啥都不懂的老子，也能说这一句！……老大你能平安无事，老子就高兴。」

与艾莎一样被安排去居高临下地观望局势、心里必定憋屈又焦灼的小弟，用直截了当的话语和结实的手臂搂住昴的肩，这么说道。

而这样陪在昴身边的，也不止他一个——

「昴，有好好地下定决心了吗？……明明贝蒂也可以代替你，把一切都承担下来，可你却因此受了伤，真是个笨蛋呢。」

「碧翠丝……」

「不过，那道禁术可是贝蒂和昴两个人一起完成的。昴准备了术式，贝蒂构筑了魔法，昴负责咏唱，贝蒂导通了玛娜。所以，这份重担贝蒂要跟你对半分。要是你一个人全背了，可就是耍赖了哦。」

「——」

昴猛地咬紧牙关，他的右手将那枚黑色的球体攥得死死的，紧到蜷起的手指都再也张不开——因为自己的无能，他只能做到这种地步。

——那枚把阿尔关进其中、除此之外别无他法阻止他的魔玉。

「——抱歉。我得去一个必须去的地方。」

胸腔深处、乃至体内所有脏腑都在颤抖的感觉涌上来。跪着的昴撑起身子站起，慢慢走出『塔吉忒』的书库。

他牵着碧翠丝的手，带着一脸担心的加菲尔和艾莎，一遍遍呵斥着随时要垮掉的双腿，沿着走廊前行，终于抵达了目的地的房间。

然后——

「咦呀？大哥哥，怎么了呀？书库里要找的东西呢？」

看到出现在门口的昴，坐在房间一角酒桶上的梅莉，和顶在她头上的小红蝎一起歪了歪脑袋。

那份平安无事、还摆出一副小小得意的模样，也让他胸口一紧，但更让他在意的则是——

「——昴，怎么了？饭还没好呢？」

听到梅莉搭话，背对着这边的少女回过身来。她正用嵌着魔石的炊具煮着锅物，圆圆的眼睛里映出昴的身影，眨了眨。

「——啊」

亲眼看见那名少女，昴不由得身心一僵。

她略显疑惑，随即伸直方才弯着的膝盖，轻声唤道：「昴？」然后迎上脚步摇摇晃晃、站也站不稳的昴，与他正面相对，

「碧翠丝酱，发生什么事了吗？总觉得昴他……」

「或许是有点事吧。不过，贝蒂可不会从贝蒂的嘴里说哟。……只是，现在他好像无比想见佩特拉，差不多就是这样かしら。」

「我吗？」

被碧翠丝的回答弄得一愣，少女——佩特拉惊讶地睁大了眼。近在眼前看着她那丰富多变的神情，昴脸上的僵硬也慢慢松弛下来。

将背后发出意味深长一声「呼嗯？」的梅莉暂且抛在脑后，昴凝视着与自己面对面的佩特拉，犹豫了片刻，开口道：

「佩特拉，话可能有点奇怪……我可以抱你一下吗？」

「——不说也可以直接抱啦。不过，啊，果然还是不行。光是想想就心怦怦跳，心脏要坏掉了——呜」

佩特拉恶作剧似地一笑，她那温柔的回答还没说完，昴已伸出手臂将她拉了过来，紧紧抱进自己的怀里。

「诶、那个……」

面对这突如其来的拥抱，佩特拉显然难掩困惑。对这个不知不觉间已愈发沉稳、几乎对什么都不再动摇的少女而言，这样明显的慌乱实属少见。

然而，在这里，没有一个人会因此拿她开玩笑。

因为——

「喂，昴，你没事吧？」

一只从怀中轻轻伸出的手，柔软地触碰上昴的脸颊。

近在咫尺，近到不止能感到彼此的呼吸，仿佛连心跳都要相撞——面对少女在这般距离下的询问，昴屏住呼吸，扯出笑容。

「没事的——」

那是当然。不是吗？因为——佩特拉还这样精神地在这里。

不只是佩特拉。碧翠丝也好，加菲尔也好，梅莉也好，艾莎也好，菲菈姆也好，全都安然无恙。

塔里的人，没能来到塔的人，大家都平安无事。

已经发生的那些坏事，全都变得仿佛从未发生。

当然，他并非知晓一切，也明白并非发生的一切都是坏事。

有对立与和解，有背叛与友谊，有诀别与重逢，有诅咒与誓言，有憎恨与爱——还有阿尔德巴兰与菜月・昴。

「——也许，并不没事。」

抱着佩特拉，看着那枚怎么也离不开她手中的魔玉，我不由得低声吐露。

而那句自唇边溢出的软弱，并未止于一声勉强挤出的干涩之音。点点滴滴，真心化作泪水，从眼角一并滑落。

——不是。

我想去回报佩特拉她们——那些挺起胸膛说着「没事」，让昴去『死亡回归』，让他把本已无可挽回的许多重新夺回，并接受了作为代价而被遗落的世界的人。

做不到。悲伤又懊悔，为自己的力量不足而羞愧，根本抬不起头。

一点也不行……！

献上了太多代价的佩特拉也好，本该把一切都夺回来的雷姆也好，直到最后一刻都不肯放弃与阿尔对话的艾米莉娅也好，就算一同被封印仍解读了禁术术式、把王牌交到将要『死亡回归』的昴手里的碧翠丝也好，那场战斗中参与的，无论昴所知或不知的人们也好，所有、所有，全部的人。

最后，连对话的机会都没能创造出来的阿尔——

对不——

——昴！

突如其来的高而尖锐的声音，生生打断了那句本该说出口的道歉。

那是被他硬生生咽回胸口的言语——从他胸前仰起脸望向昴的，是佩特拉的声音。

她那圆圆的瞳仁被巨大的情绪晃得微微发颤，手还扶着泪水扑簌簌落下的昴的脸颊，

「你终于说出来了呢。说你并不好。」

「——啊」

「不用那样害怕哦。所有的一切，也不必一个人扛。对吧，碧翠丝酱？」

「……那是当然的说。贝蒂可是昴的搭档来着。」

在佩特拉的催促下，碧翠丝紧紧地抱住了昴的身子。面对两个少女的温度而不知所措的昴，佩特拉仍旧微笑着，

「梅莉酱。」

「诶？我就不用了吧。佩特拉她们就够了……」

「梅莉酱。」

「……好啦好啦。」

梅莉轻巧地从木桶上一跃而下，板着一张不满的脸，浑身都写着不情愿，走到昴身边，轻轻捏住了他的衣摆。仿佛在替那样的主人表达心意似的，她发间蹿出的那只小红蝎跳到昴的肩头，把身子贴在他的脸颊上蹭了蹭。

「加菲尔先生。」

「哦喔！大将！」

「咕哦！？」

等得不及似的猛地扑过来的冲劲结结实实撞在他的背上，他忍不住痛哼出声。想到要是向前栽倒就会把佩特拉压扁，他拼命稳住脚步，硬是撑住了。撑住了，可是——

「艾莎和菲菈姆也来吗？」

「我是局外人，就不打扰了。不过，我站在菜月殿这边。」

「我也是刚到，还没弄清楚情况……明白了。」

随后现身的身影毫不犹豫，悄然依在他的右腰旁。

至此，全方位、无处可逃的拥抱阵势完成——被那份温暖一拥而上，昴不由得「哈」地吐了口气。

「这是什么情况。」

旁人看来——实际上，正有艾莎在旁边看着——在他眼里，如今的昴他们会显得多么傻气吧。

大家毛茸茸地挤成一团，蠢得要命。

「没关系。让我明白自己是笨蛋的人，是昴呀。」

「有过这种事吗？」

「有过的。」

「……在我认识的人里，大概没有谁比佩特拉更聪明了。」

我是这么想的。一定是这样。所以在聪明的她眼里，一切都一清二楚。好厉害。这才叫真正的聪明，和像埃布尔那样的「聪明的笨蛋」完全不同。

「我决定了。」

虽然我现在还哭得一把鼻涕一把泪，被温柔的大家从四面八方抱住，整个人都软成一团，才刚刚承认自己一点都没事是假话，但我已经下定决心了。

「阿尔，你好像讨厌我，讨厌到连原谅都做不到的程度，不过——」

原因的真相我并不清楚。只是，不会在一无所知中就此结束。

无数濒临终结的事物，被无数不愿让它们终结的意志所挽回，于是，根本算不上「没事」的菜月・昴，下定了决心。

那就是——

「——我一定会把你也救出来。」

哪怕那是把世界尽数树敌的暴举也无妨，把好事也好、坏事也好统统一并，用『死亡回归』抹消成未曾发生——这是菜月・昴的誓言。

听到这份誓言，佩特拉・雷蒂满意地点了点头，

「这才是我的昴！」

——是的，那位没有成为『忧郁魔女』的少女，绽开了笑容。

** 幕间　『声援』

——对『忧郁魔女』佩特拉・雷蒂而言，理应追寻、必将抵达、终该归落的结局，从一开始就只有一个。

那是从她尚未成为『忧郁魔女』、只是个普通乡村姑娘的佩特拉・雷蒂，一不小心读到了名为菜月・昴的『死者之书』那种了不得的东西时起。

那是从她得知菜月・昴以自身的『死亡』为代价，为了改变无数人的命运而一路战斗至今的那一刻起。

那是从与他共同度过不经意的日常，明白菜月・昴因何欢喜、因何悲伤、对何物感到幸福与不幸，并因此愈发怜爱他的那个时候开始。

——把这些形形色色的理由统统捆在一起、包裹成束，答案早就注定了。

「反正，昴也想把阿尔先生的事设法解决掉，对吧？」

老实说，对佩特拉来说，这是荒唐透顶的话。

要是把阿尔干下的事一一掰着指头数，就算把手脚所有的手指都用上也不够，恐怕还得把『不可视之手』都动员出来，去掰那些不够用的指头。

阿尔犯下的无法挽回的事多得像座山。——可即便如此，也并不觉得阿尔是个天生的极恶之徒，更不是一边嘲笑一切一边做下那些事的人。

「难道这也是受了昴那些书的毒吗……」

虽说这么评价自己有点不好意思，但佩特拉是个现实派，而且她能揽下的范围也很窄。与其说窄，不如说是她刻意把它缩小了。

毕竟，只要把自己的器量毫无保留地用出来，她自信自己其实是一只能塞进相当多东西的器皿——对此她并不害羞。

可要把那器量的每个角落都用上，并且对塞进去的每一样都珍而重之——她做不到。

可偏偏——

「昴这家伙真是贪心……」

不过，我就喜欢他这一点。——不对，那一点我也喜欢。

也正因为改变不了这样的菜月・昴，佩特拉・雷蒂才要去做。

那是一个像被生生割肉、无情撕心般的痛苦抉择。

——让菜月・昴『死亡回归』，把一切重置。

自从离开普雷阿迪斯监视塔、下定决心与幻影的菜月・昴同行的那一刻起，佩特拉・雷蒂便一直朝着那个结局一路迈进。

她强硬主张由自己担任『忧郁』的魔女因子持有者，将除去极少部分外使用权能所需的代价一概集中由自己承担，能出的谈判筹码毫不吝惜，能交出的情报统统摊开，就此敲定了『阿尔德巴兰之刃』的方针。

「如果『嫉妒魔女』之所以发狂，是因为我读了那本书——那也能拿来利用，对吧。」

自从『暴食』的大罪司教罗伊・阿尔法德被从监狱塔放出、她意识到其权能的效用之时起，佩特拉心中便有个疑问——若是将阅读『死者之书』的佩特拉的『记忆』夺走，那么『嫉妒魔女』会作何判定？

她也隐约觉得，那大概正是阿尔所说「并非打算把世界毁掉」的、用以驱散『嫉妒魔女』的作战。

因此，当『阿尔德巴兰之刃』以总力击破罗伊・阿尔法德时，她一边捆起奄奄一息的罗伊，一边做出了约定。

「要是你想吃我，我会给你创造机会。」

当然，这份约定只要不用遵守，她就会毫不留情地违背。

受菜月・昴恶劣影响的佩特拉，是个对讨厌之人的约定毫不在意、破起来连眼都不眨的无法者。

此外，万一那件事真的实现，她也已经做好了准备——把一位令人心安的强力同伴拉到了自己这一边。

「雷姆姐姐大人，真是了不起啊。」

她沉下心来想道。撇开因菜月・昴而生的厚重偏爱不谈，她也由衷地这么认为。

雷姆察觉到了昴的『死亡回归』——起初以为是『时光倒流』。虽然契机是罗姆爷揭开了阿尔的权能真相，但雷姆终究是靠自己悟到的。

雷姆靠自己明白了：菜月・昴是个以性命为代价一直战斗到现在的人。——为此感到高兴的同时，她也不免懊恼。

「但是，正因为如此，才能托付给雷姆姐姐大人。……不，除了雷姆姐姐大人，不行。」

无论途中会遇到多么好的事，无论会收获多么难以割舍的情感，佩特拉・雷蒂都已决定把这一切统统推翻，让它们仿佛从未存在。

而这也意味着，连那件「我们迎回了终于夺回『名字』与『记忆』、在真正意义上回到身边的雷姆」的事实，也会一并被抹消。

明知如此仍要去做的佩特拉，有责任把雷姆也卷进来。

作为同样清楚『终将消失』的同志，也作为同样从心底希望那位最爱之人不再错过任何东西的女人。

只能托付给那些坚信『非此不可』，愿为爱舍弃一切的人。

对那些总觉得还会有更好的答案，会到极限的极限、拼尽全力搜索到最后一刻的人，没法把这么残酷的事交给他们。

所以，这里就由佩特拉和雷姆来完成。

「昴也好，艾米莉娅姐姐也好，一定已经很累了吧。对不起。明明如此，我却还成了负担。对不起。我一直一直，都想把那份怎么也说不够的谢意，说给你们听……」

我想说「谢谢」，想把真正意义上的「谢谢」传达给你们。

作为读过『死者之书』、知晓一切的佩特拉・雷蒂，我想为踏上荆棘之路的艾米莉娅，以及选择粉身碎骨去支撑她的菜月・昴，他们的那条道路，送上支持与祝福。

但那无法实现。佩特拉・雷蒂会竭尽全力，却终究要回到一无所知的村娘。

为此不甘，又难过，「谢谢」和「对不起」怎么也说不够。

即便如此——

「……我把能做的，全部都做到了吗？」

在有限的处境里，她是否已经把自己能做的，全部都做到了呢。

阿尔八成也准备了不输的底牌吧。可为了顶回那一手而反复试错，我们这边却只有一次机会，这也未免太不公平了。

但我们做到了。硬是做到了。中途明明不该有记忆的奥托也参战，这一度确实让我有点打退堂鼓，不过不管怎么说，这一切都是全员参战的成果。

「呵呵，这有点厉害吧？会爱上我吗？」

「……嗯。好像要爱上了。」

我微微歪着脑袋，用自己能演出的最可爱的表情相迎。面对佩特拉那可爱的举止与提问，幻影的菜月昴就那样露出腼腆的笑容。这是佩特拉为了让我听到而编出来的迷惑之词？还是就算换成真的他，也大概会说出口、逼近真实的回答？

算了，反正马上就要消失了，就往对自己有利的那一边理解吧。

我轻轻伸出手，将手覆在那只触不到的手上，十指相扣。就这点作为幻影的额外福利，应该也无妨吧。毕竟真的很努力了。

「话说，可以问你一个问题吗？不，从我的立场这么问有点奇怪就是了」

「嗯～？什么？」

「在从柯林特先生那儿得到魔女因子之前，有一次，为了移动，佩特拉付了代价吧……你没跟我说过呢？我一直在想，那到底是什么来着。」

「既然没让你听，那就干脆一直别听下去，怎么样？」

「太残忍了吧。」

他那副可怜巴巴的表情也显得可爱，佩特拉忍不住轻轻噗嗤一笑。

不过不愧是昴——就算只是幻影，昴也还是昴。对于佩特拉不想让他看、不想让他知道而藏起来的东西，就算只是脑海里的住客，也不会擅自越界。

在这点上松了口气的佩特拉吐了吐舌头，

「保——密——哦——」

虽然让幻影的菜月昴苦着脸了，但佩特拉还是想把它藏起来。

至少有一个连幻影的菜月昴也不让他看到的少女秘密，总可以吧。而且这个少女的秘密里，还掺着一点点少女心的小小算计。

那时，佩特拉把自己某种可能性当作代价献给了柯林特。

那就是——

「——我成为昴的新娘的可能性。」

知晓佩特拉心意的柯林特，当时的惊讶可谓非同小可。

背负着『龙人』那般沉重历史的柯林特，看着佩特拉以近乎献身的姿态奉上自己的可能性时，那目光与动容的反应，令人难以忘怀。

也正因如此，才更觉得抱歉。——毕竟佩特拉借由那份代价，反而得到了确信。

「既然能把它当作代价，那就说明，我的未来确确实实存在那样的可能性。」

若从『忧郁』的魔女因子的机能来考量，严格说来，她所奉献出去的，应当是那份对世界的影响力——也就是「为了得到与昴结婚的未来，佩特拉将付诸的种种努力」。

然而，这些枝节，在那一刻的佩特拉看来都无足轻重。

重要的是，相信「佩特拉・雷蒂会成为菜月・昴的新娘」的那个未来。

而这一点，正是触及世界核心的魔女因子替她作了证明。

正因为握有那份确证，她才下定决心把一切做到底，直到最后一刻也不曾停下脚步。

所以——

「加油啊，我。——能不能抓住机会，就全看我有多努力啦！」

那是——从一个成了『忧郁魔女』、为自己的幸福而动用魔女因子的乡村姑娘，送给那个「不会成为忧郁魔女的未来的自己」的打气。

——出自一位坚韧而精明的异世界少女，略显沉重的爱的应援。

** 第七章 『Reweave』

——远远望着在跋利耶尔宅邸里忙碌的仆人们，法兰黛莉卡心头涌动着难以平复的不安，怎么也安不下来。

「与主人同行，受人以宾客之礼，这样的情况倒也常有……不过，在这座宅邸里，如今的规矩多少有些不同呢。」

如此低声喃喃的法兰黛莉卡，她那双翠眸中映出的，是一派忙碌的宅邸景象。

一眼便能看出，这里聚集的是干练而步调统一的精锐。即便听闻法兰黛莉卡一行带回的凶讯，也未至于陷入瘫痪——仅此一点，便足以令人敬佩。

「普莉希拉大人，似乎很受人仰慕呢。」

传达给仆人们的噩耗——那是这座宅邸的主人、亦是她们的主人普莉希拉・跋利耶尔，已在佛拉基亚帝国殒命的讣告。

「——」

法兰黛莉卡微垂睫目，自阳台俯瞰庭园与宅邸，轻轻吐出一口气。

身处这样的立场，她也并非不明白：罗兹瓦尔、艾米莉娅等她侍奉之人将她留在宅中、独自离去，而她只能祈祷他们平安归来、静候佳音的那种心境。若是得知那份祈祷最终未能应验，胸口所受的冲击又会是何等之重呢。

事实上，许多仆人都沉浸在悲伤中，落泪者亦不在少数。得悉讣告后，没有一人选择离开宅邸，这也可说是他们与普莉希拉之间情谊的体现。

然而，此中缘由并不只因普莉希拉备受爱戴——

「——修尔特大人那份毅然的态度，实在扣人心弦。」

让法兰黛莉卡如此深受触动的，是那位幼小侍从的姿态：他随同普莉希拉前往帝国，肩负起传达她的死讯与遗志之责，并出色地将其完成。

修尔特身形纤细，看起来像小动物般让人难以倚靠，然而他没有把扮黑脸的任务推给罗兹瓦尔或法兰黛莉卡，而是以自己的嘴、自己的话，独自扛下了这份大任。

仆人们没有离开宅邸，选择继续坚守现职，其中对普莉希拉的思慕与对修尔特的信赖，占了极大的分量，这是毋庸置疑的。对此，即便身为局外人，也忍不住眼角发热的法兰黛莉卡亦深以为然。

因此——

「——哎呀，你在这里啊，法兰黛莉卡。我可找了你好一会儿呀——」

「老爷……」

轻轻扬手，迈步踏上阳台的那道修长身影——罗兹瓦尔。迎上他的法兰黛莉卡当场屈膝，轻轻一礼。

「让您费心找我，实在抱歉。请问有何贵干？」

「也谈不上什么要紧的事呢——。这边的安排告一段落了，我只是想和你聊聊罢了。」

「安排……」

「对，正是安排——」

罗兹瓦尔薄薄一笑，异色双眸中只留那只金色的眼睛睁着，与站在栏杆旁的法兰黛莉卡并肩，背靠在栏杆上，

「倒是块颇有看头的土地。南部我结识的人不多。曾为普莉希拉大人丈夫的莱普・跋利耶尔卿，风评可不怎么好呢——」

「被老爷您这么一说，那位恐怕也要不高兴了吧。」

「哎呀，这话可真不留情。你啊，也被佩特拉那孩子带坏了，对我少了几分顺从了吗——？还是说——」

罗兹瓦尔微微歪头，探身凝视着身旁法兰黛莉卡的双眸，

「——不太喜欢我打算利用修尔特那孩子的计划，是吗？」

「……我并不觉得老爷在做错事。那是为了王选……更进一步说，也是为了艾米莉娅大人和整个阵营，这一点我也明白。」

「道理上固然如此，但要让心也一起点头，可就没那么容易了啊——」

明知如此还偏要这么说，罗兹瓦尔这坏性子可真是根深蒂固。若换作艾米莉娅来形容，大概会说是「想被好好训一顿的恶作剧心」吧。

「以我与老爷的关系，那可难办呢，艾米莉娅大人……」

若此刻有艾米莉娅或佩特拉在，还能用正面手段促他反省；若是拉姆在，也能用些旁门左道让他收敛。可仿佛预先料到了这一点，这里偏偏只有法兰黛莉卡。

而法兰黛莉卡即便撇开那份无以为报的恩情不谈，也看得出罗兹瓦尔那副假装作恶的行径，是为了阵营着想。

——艾米莉娅阵营能作为一个阵营凝聚起来，最大的目的归根结底还是王选。

在那场王选里，因前往佛拉基亚帝国的那段时间，他们整整落下了一截。更何况，艾米莉娅本就起步落后。要想追回这圈差，甚至再求一股推进力，就不能只依赖正攻法。

为此，罗兹瓦尔正冷静而有条不紊地推进他那近乎献身的暗中运作，试图把刚刚失去绝对支柱『普莉希拉・跋利耶尔』的跋利耶尔领拉到己方。

「既然普莉希拉大人已经去世，在选出下一任领主之前，就必须设立代理的临时政务官。幸好，我这边的人里可以提名候选人；至于联络人，从琉兹殿那边的一个——『梅尔兹』当中借一位过来就行。」

「……把婆婆大人的那些孩子也卷进来，是否为时尚早？」

「不是说，可爱的孩子就该让他们上路见世面吗？一味体贴地把人关在鸟笼里，可学不会怎么振翅。我也是这个意见——呢。」

看着罗兹瓦尔稳扎稳打、冷静无懈地把计划一项项敲定，法兰黛莉卡几乎要认真怀疑，艾米莉娅对他的评价是否属实——这人恐怕不是假装为恶，而是货真价实的恶党。也未免太认真了。

「老爷，至少请再多留些手——」

她正打算点明这一点，免得这样的误解不只在阵营内发酵，更在跋利耶尔领，乃至在修尔特心里埋下巨大的疑念之际——

「——出、出出、出出出，大事不好了！边境伯爵大人，您在哪里——！？」

「刚才那声音，是修尔特大人？」

忽然，从下方传来修尔特慌乱的呼喊，法兰黛莉卡与罗兹瓦尔对视一眼。罗兹瓦尔挑了挑眉，似乎也毫无头绪，便直起身子离开栏杆，回过身去，俯视着眼下冲进庭院的修尔特，唤了一声：「修尔特君。」

这声招呼一出，被叫到的修尔特把那双圆溜溜的眼睛瞪得老大，

「边境伯大人！请您立刻过去！有人想请您一见，还有一桩想请您听的事！」

226

「——方才请您过目之物，便是已故夫人的遗志。」

说罢，那位自称雅耶・天泽的红发少女——女仆——揭示了那封加封蜡的书信内容，罗兹瓦尔怔然瞪大了眼。

「————」

主人如此将动摇表露于外实属罕见，但这反应也并非不可理解。确认了相同内容的法兰黛莉卡，以及同席的所有人，无不为之震撼。

尤其是作为信中所述之事的中心人物的修尔特，惊愕更为强烈。

那封书信的内容是——

「——跋利耶尔家现任当主普莉希拉・跋利耶尔，于确定自身正式继承人之际，特此将修尔特改名为『修尔特・跋利耶尔』，并宣布将其迎为跋利耶尔家嫡子及继承之子。」

「普莉希拉大人，把我……？」

对这突如其来的事，修尔特眨了眨眼，一脸分不清是梦是醒的茫然。

然而，就在这时，他的双肩从背后被人按住。把那封书状的下落说出来的雅耶微笑着，亲昵地将脸颊在少年脸上蹭了蹭，道：「也太吃惊了啦。」

「考虑到夫人对小修尔特的溺爱，这事一点也不稀奇吧？——按理说，本来是想在王选期间先保密的。」

「雅耶大人……雅耶大人，您是从什么时候知道这件事的？明明几个月前就离开了宅邸，好不容易才回来……」

「——我是知道在夫人和小修尔特准备启程前往帝国的前一刻。那封信也是那个时候准备的。」

听了雅耶这平静的答复，修尔特的眼中渐渐蓄满了大颗的泪珠。

听说，雅耶曾在这座宅邸里担任女仆，前阵子一直在休假，得知普莉希拉的讣闻后便匆忙赶来。

正如所见，与修尔特关系亲近的她也深得普莉希拉信任，甚至被托付守护她遗下的重要书信。

而由此揭开的事实，狠狠搅乱了罗兹瓦尔的计划——

「——但是，若是想到修尔特大人，也许这反而是件好事。」

「……法兰黛莉卡？」

「或许这同老爷的打算略有出入……但修尔特大人和宅邸众人的心灵，应该都能因此得到救赎。——她果真是位了不起的人呢。」

尽管对方是王选候补，与艾米莉娅立场敌对，法兰黛莉卡对于那位几乎毫无交集的普莉希拉，也只能评为大人物。

毕竟——

「能把老爷的盘算都扰得如此失准，毫无疑问，她一定会是艾米莉娅大人的好敌手呢。」

227

「――――」

雅耶再次将目光落在留下的书状上，从背后抱紧因小小身躯而颤抖的修尔特，轻轻叹息，叹息自己选择亲自回到跋利耶尔邸的决定。

——这一切，都是为了配合阿尔所追求的目标，为了助他达成而作出的判断。

「没有发出约定的信号，那就是塔里的计划失败了呢～」

本来按照约定，雅耶应当在普雷阿迪斯监视塔就近的城镇与前往那里的阿尔会合，协助他完成那份非做不可的使命，并见证他在性命走到尽头时的最后一刻。

然而，到了指定的时间也不见合流的信号升起，雅耶便判断阿尔的计划告败，从最近的城镇撤出——随即折返，旋即回到了跋利耶尔领。

「能大摇大摆地回到宅邸，还是自从那回夫人的暗杀被阿尔大人挫败之后的头一遭呢。」

不过，只要不是明目张胆的方式，为了与阿尔联络，她其实一直相当频繁地出入这座宅邸。——这次作为回府借口所用的那封书状，其实也是她在一次不那么公开的潜入时，藏身阁楼打探到的消息。

至于修尔特，以及那些企图将他当作猎物的恶劣贵族——罗兹瓦尔・L・梅札斯与他的贴身女仆——他们看到的那封书状，则被她谎称为普莉希拉所托。

「实际上，不过是我偷眼瞧见夫人把它准备好，又收进了秘密金库而已。」

多亏那封书状被收在暗藏的金库里，除了雅耶之外根本没人知道它的存在。得以指明那封书状的下落，雅耶也以被托付秘密之人的身份赢得了信任。为此而利用已故的普莉希拉，她心里多少还是有些愧疚——，

「——但夫人，您真的以为我没看见吗？」

说实话，这一点连雅耶自己也没个明白的答案，是个谜。

普莉希拉拟好将修尔特收为养子的那封书状，是在动身前往帝国的前夕，收入金库也在同一时段。虽说普莉希拉只是她曾短暂侍奉过的主子，雅耶却绝不敢小觑对方的洞察力。那位目光仿佛能看穿他人心底的女杰，真的会相信雅耶不在场吗？

『——把这封书状用得漂亮，让它为你所用。顺便也把修尔特救了吧』

把书状藏在那处不把整座宅邸翻个底朝天就绝对找不到的暗藏金库里，除了潜伏在阁楼的雅耶，谁也发现不了——或许这正是普莉希拉的用心安排。

无论如何——，

「我会照做的，夫人。——我还得等阿尔大人。」

决定领受普莉希拉厚意的雅耶，为此回到了宅邸。

如前所述，未能发出继续计划信号的阿尔，大概是在监视塔上出了差错，致使计划的推进陷入了难以为继的局面。可阿尔不会死。他还活着。

「因为阿尔大人，是个怪物啊。」

阿尔不会死，也杀不死。正因为他是这样的怪物，雅耶才会追随他。

为了见证他达成目的，心满意足地死去；为了亲眼看见那个曾令自己恐惧的存在从世上消失。——为此，必须让修尔特与艾米莉娅阵营保持距离。

若阿尔出了什么事，那必然与随他同行至监视塔的艾米莉娅阵营有关。为了在他从那里脱身之际及时应对，必须待在随时可以行动的位置。

所以——

「修尔特酱，让我们继承夫人的遗志吧。没关系的。接下来我也会回到宅邸，来协助修尔特酱。」

「雅耶大人……是。是的……！我一定会不负普莉希拉大人的期望！还请雅耶大人协助我！」

天真可爱的修尔特——不，是已成为修尔特・跋利耶尔的少年——他的决心让雅耶夸张地垂下眼角，其他仆人们也仿佛深受感动，眼眶含泪。罗兹瓦尔身边的侍女也用手指拭去眼角的泪水，为他的坚强所动容。

只有那位似乎打错算盘的边境伯爵还挂着含糊的表情，但这反倒像是一份证据：即便死去，普莉希拉仍旧超出了某些人的算计，真叫人痛快。

没错，普莉希拉是个值得侍奉的主人。——唯有这一点，毋庸置疑。

「我会拼命努力的！等阿尔大人和亨克尔大人回来的时候，要让他们看到我堂堂正正的样子！」

只是，面对脸涨得通红、如此铆足劲的修尔特，雅耶却犹豫了，不知该如何作答。

盼着阿尔归来，雅耶也是一样。

然而，关于亨克尔——

「……亨克尔大人嘛，恐怕就有点难回来了呢～」

228

「——咕、呃啊！」

紧接着一阵失重般的飘浮感，他便猛地摔落在地，亨克尔发出一声低低的惨叫。

他呻吟了好一会儿，这才慢慢活动手脚，解开束缚。被细线捆住的手腕与脚踝重获自由，他细细确认这久违的解放感——

「他妈的……！」

他苦涩地把话吐了出去，仿佛在诅咒降临在自己身上的不幸。

——把亨克尔捆起来，丢在无人问津的森林中的小屋里的，是那位自称阿尔德巴兰协力者、名叫雅耶的少女。

她原本是侍奉普莉希拉的女仆，同时又是由她派出的刺客，这般来历莫名其妙的家伙，却怂恿说只要配合阿尔德巴兰，亨克尔渴求之物——『龙之血』的到手机会就会降临。明明是她先这么挑唆的。

「阿尔德巴兰那家伙一没消息，就说计划失败，开什么玩笑……」

到头来，当亨克尔要求说明并继续计划时，她却毫不留情地膝撞、肘击连番招呼，把他打得鼻血直流，捆了个结实，转身便消失得无影无踪。

站在亨克尔的立场，他实在没理由遭这种临阵抽梯的对待。

「一个个的……！」

所倚仗的普莉希拉死了，接下来想依靠的艾米莉娅也拒绝了，好不容易打算抓住阿尔德巴兰伸来的手，却被一把甩开，坠入深渊。

结果，亨克尔的前路又退回到王选开始之前的穷途末路。

「但是，即便如此……」

无法放弃。无法死心。连死心这种事，我都从未做到过。

——可恶！

他摇摇晃晃地从地上撑起身子，用袖子抹去早已干涸的鼻血，迈步走去。脚下无所指向。即便没有去处，也无法停下脚步。

——因为亨克尔・阿斯特雷亚，是丈夫，也是父亲。

等着我，卢安娜、莱因哈鲁特。我要……我会……

拖着脚步一步步挪动，手按在腰间佩剑的柄上，亨克尔继续前行。

没有目的地。——他身上所剩的，唯有那份缠绕多年的、破败生锈的祈祷。

229

「——结果闹得一团糟，这么匆忙，真是抱歉，艾莎小姐。」

「不，这也是没办法的事。情况有变，我这边也了解。眼下在替换的人手过来之前我不能离开这里，但如有需要，我随时可以出面作证。」

「帮大忙了……真的。」

小声吐出这句话，昴向以绅士风度相待的艾莎低头致意。

地点是普雷阿迪斯监视塔的五层，正对巨扉的宽阔大厅。昴——不，众人已再次收拾好行装，正打算尽早离塔启程。

只停留了半日，等到塔外天色转明，便在清晨出发。

「总觉得你们这个小哥哥总是忙忙叨叨的呢。就不能老实点，从塔里安安稳稳地回去吗？」

「说得也是。上回被一把丢到帝国，这回又是这么个匆匆折返。」

「那又不是昴的错。都是阿尔先生不好……我都不知道该怎么跟修尔特君说了。……阿尔先生这个笨蛋。」

最后低低补上一句的，是准备返程的少女们。

说到底，大家对会弄成这样各有各的想法。对只停留半天也好、对不得不匆忙离开的局面也好，甚至对招致这一切的原因，也都各有感触。

只是对昴来说，让那位成了缘由的人一直被指责，总归让他不好受。

「大将，龙车上的行李我都装好啦。随时都能出发啦。」

这时，稍稍推开大门、从外头回来的加菲尔出声道。先一步把行李装上龙车的他，看见昴举了举手，便皱起眉头，

「摆着一张哭丧脸呢，大将。我知道你会往心里去，就跟那什么『拉乌拉吉的深爪』一个样儿——」

「嗯，我知道你是在安慰我，但我还是没听明白。深爪？拉乌拉吉？」

「总之啦！已经发生的事儿改不了了。所以接下来怎么应对才是关键，对吧？本大爷能帮的，全都帮你。」

咧嘴露出獠牙一笑，加菲尔重重拍了昴的肩膀。

那一下的力道让人担心昴那单薄的肩头会不会当场碎掉，但心里却无比痛快。再者，正如加菲尔所说——既然决定要做，接下来才是真正重要的。

「——我会好好弄清楚的。我究竟背负了什么。」

说着，昴伸手触碰胸前——那挂在颈间的魔玉，以此表明决心。

——与这枚相同的魔玉之中，昴与碧翠丝曾被封印；而在那期间，阿尔掀起了一场极其庞大的战斗，具体详情，昴并不清楚。

「———」

魔玉内部一片黑暗，动弹不得，连意识是否存在都模糊不清，仿佛回到了胎儿时期，浸在母体的羊水里，始终停留在那般如梦似幻的状态中。

在那里，昴的梦与醒都朦胧不清，没有任何能称得上确凿的东西。可爱的碧翠丝不愧为她，一直坚韧地埋头分析封住这边的禁术、拆解术式；而昴能做的，不过是在偶尔勉强清醒时，发动『强欲』的权能——『柯尔・雷欧尼斯』，去捕捉近旁伙伴们的存在和强烈的情感变化而已。

尽管如此，也多亏了那反复涌动的思念与拼命，以及情绪的剧烈起伏，他才能以灵魂持续感知到这场非常事态的推移。

其中尤为鲜明的，是佩特拉那满溢觉悟与决意的色彩，以及雷姆对昴的情感——除了巨大、膨大，已无更贴切的形容。正因为如此，昴才能带着确信，提出天一亮便离开塔的方针。

这不仅是因为他们造访普雷阿迪斯监视塔的目的本就为了阿尔，如今明白那不过是他的借口，继续留下已失去意义；还因为——

「——『暴食』的大罪司教，是有把吃下去的东西完完整整吐出来的方法的，对吧？」

「没错。那里有迄今为止被吃掉的人们的……雷姆的『记忆』和『名字』也在其中。」

也许是在一次死亡回归前的那个小循环里，佩特拉将『暴食』的权能最巧妙地纳入了作战之中，她的话让昴深深点头。

那一瞬，连话都来不及说出的刹那，雷姆以看透一切的眼睛，将晨星狠狠砸向昴。——那颗昴每日打磨的带刺铁球在她手中被操纵得行云流水，她确实找回了自我。那无疑是『暴食』介入的结果。

有了这个确信，再加上『暴食』本人已经被控制住，没有理由不把他逼得把吞下的统统吐出来。

所以，为了这场当面的谈判——

——走吧，久违的王都！去见『暴食』，叫他把一切都吐出来！而且，不论是这王国的历史，还是这个世界的历史，看来我都不能再置身事外了。

昴捏着指间的魔玉，想着封在其深处的阿尔，告诫自己。

对昴这番决意，站在身旁的碧翠丝牵住了他的手，加菲尔用手指抚过自己的獠牙，梅莉则耸了耸载着小红蝎的肩。

随后，佩特拉以凛然而坚毅的微笑投来目光，昴迎上那道注视。

为了阿尔德巴兰——那个自称『昴的尾随星』、以与昴相同之力与之敌对、而昴又发誓无论如何都要救回来的存在——菜月・昴启程奔赴王都。

我要知道。因为我明白，装作不知是不诚实，那会让我连自己都无法原谅。

所以——，

「——命运大人，奉陪到底！」

背负着思念，踏过横亘眼前的咒缚，菜月・昴作出了这样的宣言。

230

——与菜月・昴的决意宣言同一时刻。

此时此刻，在遥远的彼方，菜月・昴宣称要动身前往的目的地——亲龙王国露格尼卡的王都，正发生着一桩异变。

「――――」

清晨，王都的大多数人仍在沉睡，在梦中错过了晨曦的到来；本应被寂静所笼罩的露格尼卡王城，却弥漫着一股异样的气息。

这股气息的源头，正是王城的中心——玉座之间。

因病而致王家断绝，这也成了王选的契机。由此国王空缺的露格尼卡王城，除重要典礼之外，玉座之间一向紧闭不启。

然而这一天，这个清晨，玉座之门却被大大敞开。其内聚集着王国的重臣——『贤人会』的成员、深得已故国王信任的家臣们，以及一众身上带着森严而凝重的紧张气息的王国兵。

「――――」

无一不是在国王缺位的王国里，于各自岗位肩负重任之人。

即便是清晨的召见，也无人迟到；更无一人以困倦的眼神或散漫的态度失礼。

因此，不论时辰，此处所承受的注视之重，几乎可以说等同于整个王国。

——而她在将这份目光尽数一身承受的同时，仍将周身的静谧维系如初。

铺满红毯的大理石地面上，一人身披靛蓝之衣，单膝跪地，双手于胸前相扣，俯首垂颈。她祈祷的姿态洗练至极，使武官忆起武技，使文官想起礼法，皆不由轻叹。

仅仅只是祈祷这一举止，便已令她压倒了周遭的一切。

「唔……可以抬起脸来吗？」

然而在这当口，唯有一人未被她的祈祷所夺心，开口发声。

那声音温和而理智，令倾听者自然而然生出那样的印象。其人乃迎接这位跪着的少女而来的城中要员之一——不，甚至可以称之为代表。

麦克罗托夫・马克马洪。——在国王不在的鲁格尼卡王国中，掌舵国政的『贤人会』核心人物；即便在这场仓促召开的场合，他依旧是拥有最大话语权与决定权的巨擘。

以其卓绝的智谋，以及对王国非同寻常的忠诚与贡献而闻名的智者，其存在感之大，甚至让露格尼卡的国王本人都曾玩笑道：「就算露格尼卡国王死了，国家也不会动摇；可要是他死了，王国就会灭亡。」

他温和的面容与柔和的语调容易让人产生误解，然而事实却是，在露格尼卡王国里，若将他争取为友，便是最可靠的倚仗；若将他逼为敌人，便是最可怕的对手。——麦克罗托夫，正是多年独享此等评价的人物。

「……是。」

顺着麦克罗托夫的话，先前低着头的女性缓缓抬起了脸。随着那紧闭的眼睑开启，与她对视的麦克罗托夫微微倒吸了一口气。

而麦克罗托夫的反应，并非他一人如此。同为『贤人会』一员而在场的波尔多・谢尔盖夫，作为武官代表站在这里的近卫骑士团长马科斯・吉尔达库，文官阵营的中坚利凯鲁特・霍夫曼，以及除此之外，此刻在玉座之间见证这一瞬间的所有人，无不各自有所反应。

只要站在那里，便自然而然吸引众人目光的魔性之女。然而，此刻众人的反应，并不只是因为她的风姿——而是因为她的容貌。

那长而柔亮的金色长发，承载着凛然坚意的绯红瞳眸，所表达的不止于美本身，其意义直刺在场之人——不，直刺露格尼卡王国之人的心。

而后——

「——首先，要感谢诸位对我这突如其来的来访仍予以盛情接待。若从彼此的立场而论，这并非理想之举吧。」

似乎早已习惯那般注视，女子单膝跪地，环视列坐的贤者与要人，如此开口。

她既不过分谦卑，也不失分寸的开场，让在座众人暂压惊愕与动摇，将应对交由他们的代表麦克罗托夫。

领会此意，端坐椅上的麦克罗托夫用指尖抚弄自己那长长的胡须，间以一声「唔——」的轻叹，

「哎呀呀，这可真是把不太好说的话直言了啊。不过，空话奉承也无益。您所言，确是事实。」

「您能如此直言，我也算是放下肩头重担了。毕竟我如诸位所见不过是个后生晚辈，方才还在担心当着大家的面会一句话都说不出来，所以心里惴惴不安。」

「唔，话虽如此，你却颇为从容不迫。看来颇惯于处在众目之下嘛。至于缘由……我想并不在少数。」

「是呢。我不否认。」

两人年岁差得仿佛祖孙，然而麦克罗托夫与那名女性的应对丝毫不滞，看起来并不会因段位差异而沦为由一方主导的试探。

两人不约而同看出这一点，像松了口气似的同时露出微笑，

「一大清早的，不能肆意占用各位忙碌的时间。那就……容我直入正题吧。」

「唔，这样做比较好。到我这把年纪，早起并不觉辛苦，可重要的话题无论几岁都难以忍受被拖延。——况且若还是来自一直与王城保持距离的『神龙教会』的来意，那就更是如此。」

「——」

原本只是从容示意她继续说下去，谁知麦克罗托夫的一句话令室内空气骤然绷紧。那份紧张很快便以「对独自前来王城的女性失礼」为由被缓和下来，然而会变成这样的缘由，却是此处无人能够左右的。

——麦克罗托夫口中提到的『神龙教会』，顾名思义，是尊奉『神龙』波克肯尼卡之存在，信仰其力量所赐恩惠与守护之盟约的宗教团体。

露格尼卡王国正如其自称『亲龙王国』一般，以与『龙』之间非同寻常的深厚渊缘而著称，凡王国之民，或多或少皆蒙『神龙』之恩。

基于这份自觉，即便未公开隶属教会，露格尼卡的大多数国民也对『神龙』怀有敬畏之心。在这样的土壤之中，那些公开隶属于教会的人，对『神龙』的信仰之深之切更是不言自明。

为防止那等巨大的影响力动摇国家，『神龙教会』不靠近掌理国政的王城，彼此各守其分，在各自的领域为国民的幸福出力——这便是不成文的默契。

也正因如此，『神龙教会』的修女造访王城，意图在包括『贤人会』在内的诸人面前发言，才显得格外罕见。

只是——，

——有这个价值。

正因为明白这事非同寻常，才有足以打破那条不成文规矩的理由。

她的这番断言，的确起到了作用，让人期待——把麦克罗托夫等人召集到王座之厅，专程听上一回，是值得的。

于是，她顺着贤人们无言的示意开口——陈明自己来访的理由。

「近来王国危难，『神龙教会』的全体信徒由衷忧心。按默契，我们一直与作为国事的王位选拔战……也就是王选保持距离，然而自从得闻水门都市的那场灾祸，便坐立难安，再也按捺不住了。」

「水门都市……普利斯提拉的那起魔女教事件啊。那座城市所受之害，我等亦痛心不已，不过莫非『神龙教会』要对卷入事变的王选候补诸位提出苦言？」

「那样的话，不就和我们不惜打破默契、急匆匆赶来，以及先前说过『值得一听』的那句话相矛盾了吗。……矛盾。」

这番脱口而出的反驳里露了真性情，随即改口的样子也暴露了她的年轻。为掩饰那份窘迫，女性轻轻咳了一声，

「总之，对各位王选候补并无怨言。虽说也不是没有让我想提几句的人，但那并非『神龙教会』的共识，只是个人意见而已。」

「既然不是教会的见解，那便是身为王国臣民坦率的意见。相反，我认为我们理应积极倾听……唔姆，这样一来话就岔开了。」

「是啊。麦克罗托夫大人是个通情达理之人，这点我会记下，不过还是回到正题。——我们想谈的，不是追究责任，而是受害之事。」

「……请讲。」

「在水门都市普利斯提拉，遭受魔女教祸害的人们……据称已确认有多起病例，而『神龙教会』能够提供救济之法。」

——刹那间，那句话的分量令玉座之间的空气哗然震荡。

然而，作为震源的那名女子仍姿态凛然，在贤人们的注视下笔直伫立。她的目光与态度毫不动摇——若非胸有成竹，绝不可能说出那样的话。

「——唔姆。」

只这一声附和，麦克罗托夫便将席间的骚动一刀斩断。

尽管如此，身为王国屈指可数的贤者，麦克罗托夫也不禁为这位女性的提议而惊讶。贤者以拨弄胡须的指尖，泄露出一丝细微的忙乱，

「若这属实，可谓求之不得。把这件事带到王城来的，是……」

「只凭我们擅自推进，恐怕得不到好脸色看吧。而且——」

「不愿给好脸色看的，恐怕不止是我们王城的人，魔女教也一样吧。」

对于这等不言自明的事实，女子也微微收了收纤细的下颌，表示赞同。

理所当然，若能将魔女教造成的损害一笔勾销，那对魔女教而言绝非可喜之事。也正因如此，『神龙教会』才渴求它。

「——王国确凿的庇护。由于掌管国政的我们，与掌管信仰的『神龙教会』之间的距离，这件事这些年来一直未能在真正意义上实现啊。」

「是的，正是如此。借此机缘，我们想把它变为现实。这是『神龙教会』的总意。——为了推动这项决断，我方有一个提案。」

「唔，提案么。是什么？」

「先请过目——我们所能施行的救济，其确凿的证明。」

女子将一只手按在胸前，说到这里，麦克罗托夫不由扬起了眉梢。

那是求之不得的提议。正如她所说，作为判断依据再合适不过。只是，想立刻把水门都市的受害者带到王都——

「您至少心里该有一位人选。第一位，就请那位。」

「……很好。首先，允许你去接触她。——马科斯团长。」

「是！」

被麦克罗托夫点名后，以轰然之声应诺的是一名披甲巨汉——王国近卫骑士团团长马科斯。他上前一步，向『贤人会』的席位敬礼。

「能请你护送她同行吗。这将关乎王国大事。务必谨慎。」

「遵命。——由我亲自随行。」

「嗯，大脸……不，身材高大的那位。请多关照。」

微微低头致意的女性，面上也添了几分柔和。大概是因为事态正朝她所期望的方向推进，她自『神龙教会』而来的此行，看来能发挥应有的意义。

面对这位女性，明知会显得有些突兀，麦克罗托夫仍旧提出了一个问题——关于这名自称『神龙教会』使者、从清晨便将麦克罗托夫等王国重臣召集至城中的她，之所以备受瞩目，并非仅仅因为她是『神龙教会』的相关人士。那是——

「——十分失礼了，但能请教一下您的名字吗，修女大人？」

231

「——我是由『神龙教会』派遣来的修女。」

在马科斯亲自带领下，来到王侯馆的那名女性——自称修女的人，令菲利斯难掩困惑。

菲利斯与威尔海姆一同滞留王都，是为了直接向王城陈情——请求允许他加入前往已开启的普雷阿迪斯监视塔的调查团，从号称全知全能的『贤者』之叡智中，求得拯救至今仍饱受折磨的库珥修的方法。

当然，来自已从普雷阿迪斯监视塔归来的艾米莉娅等人的书信也已送达，得知了『贤者』的存在与其智慧并非那么尽如人意。可即便如此，与迟迟难有进展的治愈魔法研发相比，那仍更有希望。

「真是，像个笨蛋一样。不管把现有的治愈魔法改良到什么程度，也不过是让自己死不掉，却连库珥修大人的一分痛楚都缓解不了。」

抱着近乎祈求的心情所进行的『青』的研究，已在这短短时间内，将露格尼卡王国现存的治愈魔法水准提升了不止一阶，甚至三阶。可对如今的菲利斯而言，那却毫无意义。

当下，最想救的人却救不了。这一事实将菲利斯逼入绝境，推向黑暗。

所以才想去普雷阿迪斯监视塔，求助于『贤者』的睿智——

「……能救库珥修大人？『神龙教会』？你、你是认真的吗？」

「信仰不会说谎，我也没有让迷途之人更加受苦的嗜好。就算不信我，你总能信得过你的团长吧。」

修道女应着声音发颤的菲利斯，抬手示意同行的马科斯。菲利斯高声唤了句「团长！」，他面色如岩，微微颔首，

「我听说『神龙教会』掌握着未对外公开的魔法与术技。以麦克罗托夫大人为首的『贤人会』诸位也认为，值得一信。」

「……可、可是，万一库珥修大人又出了什么事——」

「——『奎茵之石，一个人举不起来。』」

修道女平静的这句话出口，菲利斯不由得屏住了呼吸。

情绪翻涌，菲利斯的眼眶泛起水光。修道女轻轻伸出手，以纤细的指尖将他那紧攥成拳的手指，一根一根，温柔地抚开。

任由她摆布的菲利斯，忽而留意到她美丽的金色长发与盛着认真光芒的绯红瞳眸，不由瞠目。

一种足以令混乱雪上加霜的觉察袭来，却不明白那意味着什么——

「拜托。请让我去救你重要的人。『神龙教会』始终祈愿王国子民的幸福。无论拥有什么样的立场，这一点没有例外。」

「你、你是……你是谁？」

「————」

被菲利斯的追问噎住，她只把那一丝犹疑收进眨眼之间，仍轻轻握着这边的手，给出了答案。

那是——

「——菲尔奥蕾。这是我的名字。」

——十五年前自王城被劫、下落不明的王弟之女。那位拥有王族特征——金发与赤瞳——的修女，报上了与那名失踪王女同样的名字。

** 后记

庆祝第九章完结！非常感谢！我是长月达平！我是鼠色猫！

因此，该称为阿尔德巴兰篇的第九章顺利完结了！我在后记中一直强调的『疾风怒涛』主题，是否成功守住了呢？作者自负地认为这章保持了高涨的张力，给人一气呵成的强烈感受。

话说这次我想认真写后记，所以后记篇幅没用往常狭窄的分栏排版。

无论如何，第九章就是阿尔德巴兰的故事。

原本他以「戴头盔遮脸、能娴熟使用和昴相同现代世界语言的异世界人」这个噱头登场时，就明显是故事重要人物，但详情长期秘而不宣。如今突然反转，在主角缺席的第九章扛起大梁——在这种情境下，阿尔德巴兰的表现超出了我的预期。

从作品序章开始，《Re:Zero》就埋下了许多持续贯穿的重大伏笔和未解之谜，而第九章则翻开了多张这样的暗牌，将其暴露在光天化日之下。当然，看完第九章的结局后，想必大家都迫不及待想看到真正意义上的揭牌之日，不过包括阿尔德巴兰相关剧情在内，能透露的内容很多，作者现在可是相当畅快。

想必各位也明白，第九章的收尾方式在开篇时就已确定。因为作者想在第九章做的，就是重新描绘『死亡回归』。

随着卷数累积章节推进，帝国篇因剧情残酷而频繁使用『死亡回归』，但在封禁这种『死亡回归』后，又描绘了阿尔德巴兰带来的另一种『死亡回归』，最终菜月・昴的『死亡回归』成为决胜一击──。

正因平时采用昴的视角才无法展现的、『死亡回归』另一面的无常感，若能通过第九章让各位体会到，那这番描写就真正有了价值。

──『死亡回归』很恶心。这正是我在写Re:Zero时不想忘记的初心。

在第九章中不仅描写了阿尔德巴兰一伙，还能展现久违的菲鲁特阵营的活跃、莱因哈鲁特的超人表现以及佩特拉・雷蒂的故事真是太好了。第九章既是阿尔德巴兰篇，同时也想聚焦那些深爱着菜月・昴的角色们，所以描写这场全力战VS全力战时真的让我心潮澎湃。

接下来故事即将进入两位数的第十章，主线将转移到停滞许久的王选上。自称失踪王女之名的『神龙教会』修女、历经漫长苦难后重新行动的库珥修阵营、缺少一位候选人的王选将如何发展──故事终于要正式进入Re:Zero后半战了。

那么虽然依依不舍，还是按照惯例以谢辞作为结束语吧。

感谢责编池本先生，第九章后半战高潮迭起，加上现实中的活动非常忙碌，但总算顺利完成。埋了十年的伏笔回收得很精彩呢。非常感谢。

插画师大冢先生，从同时描绘九章完结与十章开篇的封面插画开始，到本卷各处的高潮场景以及遵循设定的插画对故事的完美烘托，真的承蒙关照了！角色们充满情感的姿态，正是构筑九章的脊梁。

设计师草野先生，这次设计的LOGO兼具虚幻感与征兆般的强烈表现力，令人拍案叫绝。不愧是您的手笔，真的非常感谢。

花鸡先生＆相川先生的第四章漫画化，以及高濑若弥先生的第五章漫画化，始终以令人不敢松懈的高质量给予我强烈动力。感谢诸位描绘Re:Zero的世界，每次都感激不尽！

MF文库J编辑部的各位，校对人员、各书店负责人及营业人员也鼎力相助，使得本次得以顺利出版。一直以来非常感谢。

最后要向见证九章完结的读者们致以最大谢意。线下活动的签名会与大家的应援都是我创作的动力。第十章也请多多指教！

那么，让我们在下一卷第44卷再见！故事终于迎来高潮，究竟会揭露什么，又将如何发展，敬请关注接下来的Re:Zero！

2025年12月《穿着厚厚的防寒衣物，呼出白色的气息》


Re：从零开始的异世界生活 43

长月达平

MF文库J

2025年12月25日　发行

ver.001

©Tappei Nagatsuki 2025

本电子书籍基于以下内容制作

MF文库J『Re：从零开始的异世界生活 43』

2025年12月25日　初版发行

发行人　山下直久

发行　株式会社KADOKAWA

●咨询

https://www.kadokawa.co.jp/

（请前往「咨询」页面）

※根据内容不同，可能无法予以答复。

※仅限日本国内提供支持服务。

※Japanese text only

禁止擅自复制、转载、分发、传送本电子书籍的全部或部分内容，或在网站上转载等。同时，也禁止擅自修改、篡改本电子书籍的内容。

根据购买本电子书籍时同意的条款，无论有偿或无偿，均不得将本电子书籍转让给第三方。

本电子书籍的内容基于底本发行时的取材与撰写内容。


